### ISSUE TITLE
Using template variables in a text/html panel

### ISSUE THREAD

**Issue by ionitadaniel19** [grafana/grafana#10005]
If i use the template parameter value in Option for Text Panel Options/html mode the value is parsed as { value }  and error in javascript is raised.
E.g: 
 template value $test = "MyView"
  
 var urlDesired = 'http://..../'+$test;  
results in 
 urlDesired = http://.../{MyView} instead of http://.../MyView

Note that the title of the text panel can use that variable correctly.
Found in Grafana v4.6.2 (commit:  #8db5f08).
Related to :  #2442.

**Comment by SeriousM** [comment]
I noticed the same problem today where variables are rendered as {x} and {x,y}.
Here are the places where it was wrong:

### Drilldown-Link
#### Setup
![image](https://user-images.githubusercontent.com/462013/33442268-0ad39208-d5f5-11e7-8600-16dfd606086e.png)

#### Link popup works
![image](https://user-images.githubusercontent.com/462013/33442368-4a93ab1c-d5f5-11e7-9302-f4eed4c858a0.png)
> points to `http://server.lan:5603/dashboard/db/logs?var-regionId=central`
This works with panel-repeat

#### Click on panel fails
![image](https://user-images.githubusercontent.com/462013/33442407-67687862-d5f5-11e7-869d-5d03bc703509.png)
> points to `http://server.lan:5603/dashboard/db/logs?var-regionId=%7Bcentral,and,other,values,here%7D&refresh=30s&orgId=1`
This does NOT works with panel-repeat

### Text Plugin
#### Setup

```md
[Logs](/dashboard/db/logs?var-regionId=$regionId)
```
#### Result
> points to `http://server.lan:5603/dashboard/db/logs?var-regionId={central}`
This does NOT works with panel-repeat

PS: sorry for hijacking the issue.

**Comment by SeriousM** [comment]
Just a short update: once I forced the dashboard to rerender (eg. change the template variable selection) the variable expanded correctly in the text plugin, but not in the url params of the drillin definition

**Comment by torkelo** [comment]
>  If i use the template parameter value in Option for Text Panel Options/html mode the value is parsed as { value } and error in javascript is raised.

Yes, disable multi & all value if you want just a single value

**Comment by SeriousM** [comment]
> Yes, disable multi & all value if you want just a single value

ok, so there won't be a fix beside of "just don't use it that way"?
Thanks
