### ISSUE TITLE
A template variable value breaks some panels of the dashboard

### ISSUE THREAD

**Issue by BenjaminDebeerst** [grafana/grafana#10000]
I have a Grafana dashboard set up with a couple of template variables. For some values this dashboard works just fine, for others with no noticeable difference (length, special characters) all the panels on the dashboard break. The query editor for the panels show `{{ctrl.target.refId}} ({{ctrl.target.datasource}})` instead of the query and the JS console shows `Panel data error: TypeError: a is undefined`.

On other dashboards the same issue affects just some of the panels, but so far I have been unable to understand the difference between the panels that makes the one to break and the other not to break.

The answers to the issue template questions:
- What Grafana version are you using? 4.5.1
- What datasource are you using? Prometheus
- What OS are you running grafana on? Linux, 4.4 Kernel
- What did you do? Select another value for a template variable
- What was the expected result? The panels should change the data shown, matching the template variable selection
- What happened instead? All panels show the red exclamation mark in the corner and the queries vanish from the 'edit query' dialogue, being replaced by `{{ctrl.target.refId}} ({{ctrl.target.datasource}})`

Here's the Stacktrace from the JS Console
```
Panel data error: 
TypeError: a is undefined
Stack trace:
c@http://grafana.company.org/public/app/plugins/datasource/prometheus/datasource.js?bust=1511790240190:4:170
l@http://grafana.company.org/public/app/boot.26e86561.js:75:1446
Sg@http://grafana.company.org/public/app/boot.26e86561.js:76:2113
execute/k</a.prototype.interpolateQueryExpr@http://grafana.company.org/public/app/plugins/datasource/prometheus/datasource.js?bust=1511790240190:4:1201
this.formatValue@http://grafana.company.org/public/app/boot.26e86561.js:10:22221
this.replace/<@http://grafana.company.org/public/app/boot.26e86561.js:10:23603
this.replace@http://grafana.company.org/public/app/boot.26e86561.js:10:23326
execute/k</a.prototype.query@http://grafana.company.org/public/app/plugins/datasource/prometheus/datasource.js?bust=1511790240190:4:1593
execute/k</b.prototype.issueQueries@http://grafana.company.org/public/app/boot.26e86561.js:74:13256
execute/i</b.prototype.issueQueries@http://grafana.company.org/public/app/boot.26e86561.js:20:8395
i@http://grafana.company.org/public/app/boot.26e86561.js:61:24011
l/<@http://grafana.company.org/public/app/boot.26e86561.js:61:24433
$eval@http://grafana.company.org/public/app/boot.26e86561.js:61:31584
$digest@http://grafana.company.org/public/app/boot.26e86561.js:61:30053
$apply@http://grafana.company.org/public/app/boot.26e86561.js:61:31869
x/i<@http://grafana.company.org/public/app/boot.26e86561.js:61:27919
f@http://grafana.company.org/public/app/boot.26e86561.js:60:10161
pb/k.defer/c<@http://grafana.company.org/public/app/boot.26e86561.js:60:11624
```

**Comment by grobie** [comment]
Hey @mtanda, any idea what the issue could be? Thanks!

**Comment by mtanda** [comment]
@BenjaminDebeerst 
@grobie 

I guess the execution path is like following.
The 'Multi-value' templating variable option is selected.

query()
https://github.com/grafana/grafana/blob/v4.5.1/public/app/plugins/datasource/prometheus/datasource.ts#L101

interpolateQueryExpr()
https://github.com/grafana/grafana/blob/v4.5.1/public/app/plugins/datasource/prometheus/datasource.ts#L65-L77

prometheusSpecialRegexEscape()
https://github.com/grafana/grafana/blob/v4.5.1/public/app/plugins/datasource/prometheus/datasource.ts#L15

If this assumption is correct, try to select only one of template value in the dropdown.
e.g. If `$foo` variable contain `value1`, `value2`, ..., select `value1`.

**Comment by mtanda** [comment]
Oh, sorry. I read the issue again, the dashboard works for some values, but it doesn't work for other values.
It's very strange.

**Comment by mtanda** [comment]
Some of values are broken or contain invalid value.

related code of template variable expansion.
https://github.com/grafana/grafana/blob/v4.5.1/public/app/features/templating/templateSrv.js#L90

To debug the issue, it is better to check the dashboard json.

Please check dashboard json from `View JSON` menu.

The JSON should have the information about currently selected value.
https://gist.github.com/mtanda/bba25b17d935035b704cb69bfc96bf67#file-gistfile1-txt-L354-L358
(This json result get from http://play.grafana.org/dashboard/db/3-promcon-templating?orgId=1)

**Comment by BenjaminDebeerst** [comment]
Hi @mtanda,
thanks for looking into it so quickly. You first comment did already point me in the right direction. I probably need to fix the template query because for some values of template variable 1, there are no values to be found with the query for variable 2.
The template variables use queries that depend on each other, so this is a user issue: the prometheus targets just don't export sufficiently uniform labels.

I checked the JSON as you suggested and in both the failure and non failure case, the label value part of the Json looks the same: The options array is empty.

However the template value drop down offered an empty string option. Excluding this from the label selection made it disappear and fixed the dashboard.
So in the template query I changed
`label_values({__name__="my_metric",label1=~"$label1",label2!=""}, label2)` to `label_values({__name__="my_metric",label1=~"$label1"}, label2)`
This fixed it.

However, I would expect Grafana to fail more gracefully.

Thanks again for the quick follow-up.

**Comment by BenjaminDebeerst** [comment]
Ah and for completeness, the value part of those template variable looks like this:

```        "current": {
          "text": "All",
          "value": "$__all"
        },
```

**Comment by torkelo** [comment]
#10000 !! whoohoo

**Comment by torkelo** [comment]
you win a prize!

**Comment by BenjaminDebeerst** [comment]
What's the prize? A feature request for free? ;-)

**Comment by torkelo** [comment]
feature requests are always free :) send your address to hello@grafana.com if you want a Grafana T-shirt.

**Comment by BenjaminDebeerst** [comment]
I discussed this offline with @grobie, I think I should be more clear what the actual issue is: The key aspect is how the Grafana `label_values(some_metric, foo)` function works when `some_metric` has no label `foo` attached to it. In this case I see the follwing
* the `options` field in the dashboard json shows an empty array (as expected)
* the specified "Custom all value" is used (as expected)
* the template variable dropdown shows two options:
  * `All` (expected)
  * `<empty string>` (not expected)

This is how it looks:
![empty-string-option](https://user-images.githubusercontent.com/2771038/33275842-0e3272ce-d394-11e7-906c-c5223147e502.png)

And that latter thing seems to break it somehow.

**Comment by mtanda** [comment]
Not sure this PR will fix the issue. But this PR fix bug of containing 'undefined' in templating value. 
https://github.com/grafana/grafana/pull/10004
