### ISSUE TITLE
Windows build FAIL: TestLogFile

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10006]
Recent [windows builds](https://ci.appveyor.com/project/Torkeldegaard/grafana) are failing with:

```
=== RUN   TestLogFile
  When logging to file ..
    Log file is empty .x
Failures:
  * c:/gopath/src/github.com/grafana/grafana/pkg/log/file_test.go 
  Line 42:
  Expected: nil
  Actual:   'remove grafana_test.log: The process cannot access the file because it is being used by another process.'
4 total assertions
--- FAIL: TestLogFile (0.02s)
FAIL
FAIL	github.com/grafana/grafana/pkg/log	0.066s
```

I'm guessing it has something to do with:
https://github.com/grafana/grafana/commit/c3699d82591b3b818f8d88fab0f85069d0d078dd

since that is the last one that passed:
https://ci.appveyor.com/project/Torkeldegaard/grafana/history

**Comment by daniellee** [comment]
Thanks for reminding us! Will fix.

**Comment by bergquist** [comment]
Doh! I guess the FileWriter need to be closed in the test.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/commit/c0e087640bd8227b28b74f357e0d314ff4c79308

https://ci.appveyor.com/project/Torkeldegaard/grafana/build/5321
