### ISSUE TITLE
Support row repeats with new grid

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10008]
Here are the tests for panel repeats (add new row repeat scenarios here).
https://github.com/grafana/grafana/blob/develop/public/app/features/dashboard/specs/repeat.jest.ts

When repeating a row: the grid position must be updated so the layout is correct after repeats (similar to how it's done for panel repeats but it is  much tricker for rows)

**Comment by alexanderzobnin** [comment]
@torkelo should this be closed after merging?

**Comment by torkelo** [comment]
Yes :)
