### ISSUE TITLE
Invalid dimensions for plot

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#10003]
Please include this information:
- What Grafana version are you using?
Grafana v4.6.2 (commit: 8db5f08)

- What datasource are you using?
PSQL

- What OS are you running grafana on?
Linux

- What did you do?
Played with dimensions and position of panel on dashboard

- What was the expected result?
Work

- What happened instead?
It shows error shown on screenshot: 

<img width="302" alt="screen shot 2017-11-27 at 17 02 26" src="https://user-images.githubusercontent.com/327717/33276114-d73093cc-d394-11e7-883d-740a07485036.png">

I'm not sure if it isn't a bug but I cannot simply reset the panel dimensions in any way in order to it show properly. When dashboard loads, it shows this error instead. Is there a way to reset the panel's dimensions or does it have to be recreated? If it's a bug, can I somehow help to debug it?

**Comment by torkelo** [comment]
Make sure the row or panel has a height
