### ISSUE TITLE
Grafana Subpath Issue

### ISSUE THREAD

**Issue by uppalarakesh2** [grafana/grafana#10007]
Hello,

I am using docker grafana:latest image to setup grafana ,docker container is running on port 3000. when i do http://10.2.11.111:3000 which is my localhost i could hit the grafana page. when i try do a nginx reverse proxy which is running on other host https://10.2.12.121 i couldn't do a reverse proxy. when i see the grafana documentation there is concept called sub path. Then i passed Env variable to my dockercontainer
docker run -i -t -d -p 3000:3000 -e "GF_SERVER_ROOT_URL=http://10.2.11.111/grafana ". Now the issue is grafana is unable to hit in localhost also it is redirecting to http://10.2.11.111/grafana/login. 
I tried to hit at nginx level it throws error badgate way

So my question is  SERVER_ROOT_URL should be localhost IP address or nginx running IP i.e (https://10.2.12.121). I am confused on this. can u be specific on this

**Comment by svenklemm** [comment]
it should be address as your users see it, so nginx in your case
