### ISSUE TITLE
Grafana API can't create a working datasource (without gui interaction)

### ISSUE THREAD

**Issue by brandonrdn** [grafana/grafana#10019]
Issue: When using the Grafana API to create a datasource, the datasource is unusable until interacted with via the GUI.

Steps to error:
1. Created CentOS 7.3 box with Grafana (tested versions 4.6.2, 4.6.1, 4.6.0, 4.5.2, 4.5.1, and 4.5.0), elasticsearch(latest), and httpd(latest) installed.

2. Ran the following commands to create datasources:
- curl -X POST --insecure -H "Content-Type: application/json" -d '{"name":"datasource","type":"elasticsearch","url":"http://127.0.0.1:9200","isDefault":true,"database":"logstash*","access":"proxy","jsonData":{"esVersion":5}}' https://admin:admin@127.0.0.1:8443/api/datasources

3. Logged into the GUI and verified that both datasources were created with the correct settings.

4. Checked Dashboards in GUI, which produced the following error:
     - {"root_cause": [{"type": "illegal_state_exception","reason": "value source config is invalid; must have either a field context or a script or marked as unwrapped"}],"type": "search_phase_execution_exception", "reason": "all shards failed","phase": "query","grouped": true,"failed_shards": [{"shard": 0,"index": "logstash-2017.11.27","node": "0SpVCAZxTDWJAb9pzFeUWQ", "reason": {"type": "illegal_state_exception","reason": "value source config is invalid; must have either a field context or a script or marked as unwrapped"}}]}

5. Went back to the Datasources in the GUI. Changed the name of datasource to datasource1 (no other settings were changed). Changed the name of datasource1 back to datasource(again, no other settings were changed).

6. Went to the Dashboards GUI again, with results now showing as expected. 

We originally discovered this issue when utilizing a Puppet module to install grafana and utilizing a custom type/provider to create the datasource. Once we discovered the issue we tested using the curl command after the Puppet run, then went on to spin up a new CentOS-7.3 box without puppet and manually installed grafana, then tested the datasources with the API command, and still received the same issues. As stated previously, we've tested this on Grafana versions 4.6.2, 4.6.1, 4.6.0, 4.5.2, 4.5.1, and 4.5.0 with the same results for each.

**Comment by torkelo** [comment]
It's because your missing a lot of properties.

This is the request payload the frontend sets when you save a elasticsearch datasource: 

```json
{
  "id": 5,
  "orgId": 1,
  "name": "github",
  "type": "elasticsearch",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http:\/\/localhost:10200",
  "password": "",
  "user": "",
  "database": "github",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "esVersion": 5,
    "timeField": "created_at",
    "maxConcurrentShardRequests": 256,
    "timeInterval": "10s"
  },
  "secureJsonFields": {
    
  },
  "version": 202,
  "readOnly": false
}
```
