### ISSUE TITLE
Ugly scrollbar for table view in firefox

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10014]
I have recently started using the new Firefox... it seems to work really really well.  I have some dashboards that are taking 30s to render that render instantly in firefox!  (another issue... and i'm still trying to figure out why -- does not happen with 4.6.0)

Most things look great, but scrollbars are off:

![ff-scrollbar](https://user-images.githubusercontent.com/705951/33320986-43a82a56-d444-11e7-967f-0aeff93adc5a.png)

Lets all hope this is not a common problem!

**Comment by torkelo** [comment]
this is already fixed in upcoming v5 (in develop branch), soon merged to master (2-3 weeks)
