### ISSUE TITLE
Slack Alert Notifications - The "Send Test" action with "Include Image" and Bot token fails

### ISSUE THREAD

**Issue by galan** [grafana/grafana#10012]
- What Grafana version are you using?
**4.6.2** (docker via helm chart stable/grafana 0.5.0)
- What datasource are you using?
**Prometheus**
- What OS are you running grafana on?
**Docker image**
- What did you do?
**Configured a Slack notification channel with a bot token and the "include image" option, and used the "send test" feature**
- What was the expected result?
**Message successfully sent to Slack with no errors and image**
- What happened instead?
**Message is successfully sent to Slack, but without image and Grafana shows an error: "Failed to send alert notifications". Log file entry below**
 
```
t=2017-11-28T10:28:49+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=0 isDefault=false
t=2017-11-28T10:28:49+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=0 notification=Slack-Staging
t=2017-11-28T10:28:49+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
t=2017-11-28T10:28:49+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=9 orgId=1 uname=xxx@xxx.de error="open public/img/mixed_styles.png: no such file or directory"
t=2017-11-28T10:28:49+0000 lvl=eror msg="Request Completed" logger=context userId=9 orgId=1 uname=xxx@xxx.de method=POST path=/api/alert-notifications/test status=500 remote_addr=11.242.3.20 time_ms=651 size=48 referer=https://grafana.xxx.de/alerting/notification/1/edit
t=2017-11-28T10:29:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalHandler ruleId=1 name="offset lag alert" changing state to=no_data
```

Refering to https://github.com/grafana/grafana/issues/9590, which is closed, but not fixed

**Comment by daniellee** [comment]
I cannot recreate this. With a fresh docker image of Grafana, I added a slack notification channel with a Slack hook and a bot token and it worked when sending a test.

**Comment by daniellee** [comment]
Tested on the latest master docker image and get the same error but don't get the error locally on master. Seems Docker related.

**Comment by daniellee** [comment]
When opening the image file, a relative path was used which does not work inside a docker container as the working directory is set to `/` resulting in the "no such file or directory" error.

**Comment by galan** [comment]
That was fast, thank you for fixing
