### ISSUE TITLE
`Invalid interval string, expecting a number followed by one of "Mwdhmsy"` with prometheus

### ISSUE THREAD

**Issue by tipsy** [grafana/grafana#10017]
- What Grafana version are you using? `4.6.2`
- What datasource are you using? `prometheus-2.0.0`  (also tried `prometheus-1.8.1`)
- What OS are you running grafana on? `Windows 10 PRO`
- What did you do? `I followed prometheus' grafana tutorial` : https://prometheus.io/docs/visualization/grafana/
- What was the expected result? `Pretty graphs`
- What happened instead? `Invalid interval string, expecting a number followed by one of "Mwdhmsy"`

Since there are no other mentions of this, I suspect this might be a PICNIC situation. I'm not sure what it could be though.

I followed this tutorial: https://prometheus.io/docs/visualization/grafana/
And these setup instructions: http://docs.grafana.org/installation/windows/ (even tried changing the port)

The `Link to graph in prometheus` button works fine, and auto-complete shows all the metrics I'm exporting to prometheus.

**Comment by MojaveRider** [comment]
I'm using Grafana 4.6.2, Prometheus 1.8.2 on Linux and I'm getting the exact same error.

**Comment by bio** [comment]
I successfully added prometheus 2.0.0 data source (proxy), created dashboard with simple graph but it didn't work. Error message below:

```
Panel data error: Error: Invalid interval string, expecting a number followed by one of "Mwdhmsy"
    at Object.a.describe_interval (kbn.js:189)
    at Object.a.interval_to_ms (kbn.js:200)
    at Object.a.calculateInterval (kbn.js:172)
    at e.calculateInterval (metrics_panel_ctrl.ts:207)
    at e.updateTimeRange (0.be20b78823b4c9d93a84.js:19135)
    at u (angular.js:17051)
    at angular.js:17095
    at f.$digest (angular.js:18233)
    at f.$apply (angular.js:18531)
    at angular.js:20448
```

**Comment by torkelo** [comment]
what does your query and panel settings look like?

**Comment by tipsy** [comment]
@torkelo I went through everything again and I found the error. When adding the data-source I left out the time-unit from my scrape-interval. I didn't check that part yesterday, due to a big green banner saying `Data source is working`. I'll close the issue, but please create an issue for adding form validation (if it doesn't exist already).

**Comment by kennedykinyanjui** [comment]
Also make sure you have the "s" at the end i.e. 15s.
