### ISSUE TITLE
[hover tooltip]-values are rounded

### ISSUE THREAD

**Issue by HarmOtten** [grafana/grafana#10016]
A picture says more than a 1000 words:
![image](https://user-images.githubusercontent.com/10838083/33336697-085e84b8-d471-11e7-96b4-2f4b7b50cf2b.png)

Both Energy and Runtime values are rounded. This should not happen.

- What Grafana version are you using? **4.6.2**
- What datasource are you using? **MariaDB**
- What OS are you running grafana on? **Raspbian jessie**

**Comment by torkelo** [comment]
by default the tooltip will show the same number of decimals as the y-axis (which is determined by the min/max of the data and how high the graph is). If you need more you can specify number of decimals for the legend (this will also be used by hover tooltip), or you can set decimals for the y-axis (Axes tab)

![image](https://user-images.githubusercontent.com/10999/33370512-02d5fc9c-d4f8-11e7-8ce0-5362c17989ac.png)

**Comment by qm3ster** [comment]
Should that apply to Explore view too?
![image](https://user-images.githubusercontent.com/10551234/76687723-50019b00-662f-11ea-86ab-1e2d87de95a9.png)
