### ISSUE TITLE
Different behavior between dashboard api and datasource api

### ISSUE THREAD

**Issue by anthraxn8b** [grafana/grafana#10023]
Hi @all!

Grafana version: 4.6.2 (from DockerHub)
Prometheus Datasource (should not be relevant here)
The OS used in the docker container :-)

What I did:
I deleted a not existing DATASOURCE via HTTP-API. Result was: 200
I deleted a not existing DASHBOARD via HTTP-API. Result was: 404

What I expected:
A consistent behavior of the HTTP-API.
200 is okay because the result (if the element exists or not before calling) is the same if the element is not there at the end - right?
404 is okay because the element is not deleteable because it does not exist...

Greetings!

**Comment by AustinWinstanley** [comment]
The non-existing datasouce deletion resulting in a 200 (or 500) is fixed here #12387 following this duplicate issue #12313 .

**Comment by bergquist** [comment]
Closed by #12313
