### ISSUE TITLE
Add dimension filtering to CloudWatch `dimension_values()`

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#10029]
I had like to improve `dimension_values()` to add dimension filtering.

I push multidimensional custom metrics into CloudWatch. They typically have both an `install_name` and `instanceId` dimension. `install_name` describes the name of the stack (`live`, `staging` etc.), `instanceId` is self-describing. I had like to be able to define two template variables to quickly drill down to instance metrics. Unfortunately, Grafana allows me to list all `instanceId` values but does not allow me to list `instanceId` values filtered by `install_name`. UX would be much better if only relevant `instanceId` are displayed once `install_name` is selected.

Skimming through the code I noticed that this feature seems to exist in the go backend, see https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L327, but is not available in the frontend, see https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.js#L241.

Is there any reason to not allow filtering from the `dimension_values` query ?

**Comment by cykl** [comment]
It seems that this feature has even been removed: https://github.com/grafana/grafana/commit/891d7c134cf9e33c29a9f543f4a27ffedc9e7098

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/10873
