### ISSUE TITLE
RSS Feed Ability

### ISSUE THREAD

**Issue by resnostyle** [grafana/grafana#1002]
I would like to request the ability for grafana to pull in RSS pages into a dashboard for example this page.: http://status.aws.amazon.com/rss/cloudfront.rss

**Comment by rroethof** [comment]
I second this request, would love it in my dashboard.

**Comment by sahilthapar** [comment]
:+1:

**Comment by afflick** [comment]
+1

**Comment by tima** [comment]
+1 Supporting the Atom syndication format also would take it to the next level.

**Comment by zepspaiva** [comment]
+1

**Comment by vbichov** [comment]
+1

**Comment by hb3b** [comment]
+1

**Comment by Swebask** [comment]
+1

**Comment by all-things-database** [comment]
+1

**Comment by AAERob** [comment]
+1

**Comment by timrchavez** [comment]
+1

**Comment by anja98** [comment]
+1

this is good to compliment the dashboard with RSS incident reports from source.

Any updates on this?

**Comment by sachinrase** [comment]
+1

**Comment by ehues** [comment]
+1

**Comment by tomasGk** [comment]
+1

**Comment by firadaboss** [comment]
+1

**Comment by torkelo** [comment]
we have started design work on a new rss feed panel, https://github.com/grafana/grafana/issues/9517#issuecomment-364479369

**Comment by kaihendry** [comment]
Apologies @torkelo though #9517 appears to about the UI aspects of a [News feed](https://github.com/grafana/grafana/issues/9517#issuecomment-379712894) panel.

We need a [valid](https://validator.w3.org/feed/) source RSS feed, a transformation of https://grafana.com/docs/http_api/annotations/ ideally. Perhaps if you're amenable, we can re-open and I (or someone with some better JS skills) can propose a PR?

**Comment by r4yfx** [comment]
I would like to add it as a datasource if at all possible. This will allow RSS feeds to come from aws

https://status.aws.amazon.com/
