### ISSUE TITLE
How to populate data for grafana as zeros if there is no data in certain range?

### ISSUE THREAD

**Issue by eurbon** [grafana/grafana#10028]
I have a problem. 

For example if I make a POST request to grafana API asking data points for the last 24 hours and it has data only for last 16 hours, then I will get data only from the moment there was actual data.

Example: http://prntscr.com/hgqlj2

In example you see that between 10.00 and 11.00 there was no data meaning I wont get any points. 

I want to put zeros in these so I could render the points on my mobile app easier.

How could I achieve this? Or there is no other way than handling it on my mobile app side?

**Comment by svenklemm** [comment]
Some datasources support this but grafana itself does not. Which datasource are you using?

**Comment by eurbon** [comment]
Im using multiple ones,

OpenTSDB

Apache Ambari

PostgeSQL

**Comment by torkelo** [comment]
this is up to the data source query processing to manage

**Comment by svenklemm** [comment]
PostgreSQL does support it not sure about the others.
