### ISSUE TITLE
Prometheus instant query and "full" interval (singlestat / avg)

### ISSUE THREAD

**Issue by champtar** [grafana/grafana#10021]
- What Grafana version are you using?
4.6.2

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Linux CentOS 7.4

- What did you do?
Try to compute an hit ratio for a singlestat panel with $__interval and instant query
```
sum(increase(http_requests_total{state="hit",instance=~"$node"}[$__interval])) / sum(increase(http_requests_total{instance=~"$node"}[$__interval]))
```
setting from/to 1h apart

- What was the expected result?
```$__interval``` should be equal to the "full" interval (3600s) when using instant query

- What happened instead?
```$__interval``` is still a fraction of the "full" interval depending on min step and resolution (300s in my case)

```
sum(increase(http_requests_total{state="hit",instance=~"$node"}[$__interval])) / sum(increase(http_requests_total{instance=~"$node"}[$__interval]))
```
gives
```
api/datasources/proxy/1/api/v1/query?query=sum(increase(http_requests_total%7Bstate%3D%22hit%22%2Cinstance%3D~%22127%5C%5C.0%5C%5C.0%5C%5C.1%3A3000%7C127%5C%5C.0%5C%5C.0%5C%5C.1%3A9090%7C127%5C%5C.0%5C%5C.0%5C%5C.1%3A9100%7C172%5C%5C.27%5C%5C.209%5C%5C.157%3A9100%22%7D%5B300s%5D))%20%2F%20sum(increase(http_requests_total%7Binstance%3D~%22127%5C%5C.0%5C%5C.0%5C%5C.1%3A3000%7C127%5C%5C.0%5C%5C.0%5C%5C.1%3A9090%7C127%5C%5C.0%5C%5C.0%5C%5C.1%3A9100%7C172%5C%5C.27%5C%5C.209%5C%5C.157%3A9100%22%7D%5B300s%5D))&time=1511924400"
```

My goal is to show an hit ratio in a singlestat panel, with instant query, i just need the "full" interval and I'm all set
Right now I'm basically doing an average in grafana of the average returned by prometheus (which gives me wrong results)

**Comment by free** [comment]
You can define a hidden template variable of type *Interval*, with an *Auto option* and a *Step count* of 1. It won't always exactly match the length of the selected time range, as it will round to some multiple of tens of seconds or minutes (e.g. `24m` -> `20m`, `25m` -> `30m`), but you can put the actual variable value in the panel title or somewhere, if that's a problem. For the provided time range choices (e.g. *Last 30 minutes*, *Last 12 hours* etc.) it will match exactly.

**Comment by aocenas** [comment]
The behavior of $__interval is correct, what you probably want to use here is [$__range](https://grafana.com/docs/grafana/latest/variables/global-variables/#range) variable.
