### ISSUE TITLE
Custom plugins don't work

### ISSUE THREAD

**Issue by mgtriffid** [grafana/grafana#10034]
**- What Grafana version are you using?**
4.7.0-pre1
**- What datasource are you using?**
SimpleJson
**- What OS are you running grafana on?**
Linux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**- What did you do?**
Clone the latest Grafana from master (554c7ba96f28c48a3d868a0a663f605aefb4a43c)
yarn install --pure-lockfile
Download SimpleJsonDataSource zip archive from https://grafana.com/api/plugins/grafana-simple-json-datasource/versions/1.3.5/download
Extract contents of folder grafana-simple-json-datasource-f7b32fb into public/app/plugins/datasource/grafana-simple-json-datasource
npm run build && go run build.go build && ./bin/grafana-server
Open localhost:3000
Login as admin
Go to Datasources
Click "Add data source"
In the dropdown for type select "SimpleJson"
**- What was the expected result?**
Settings for SimpleJson data source appear
**- What happened instead?**
Error message in top right corner says:
`Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/datasource/grafana-simple-json-datasource/module Loading app/plugins/datasource/grafana-simple-json-datasource/module`

Actually we have a custom datasource plugin which for some reason no longer works with Grafana 4.6.1. I thought this is caused by some changes in plugin system. So downloaded SimpleJson datasource to take close look at it and find what do we miss in our plugin, but unfortunately it also doesn't work with exact same error message and I don't know where to dig now. Could you please assist?

**Comment by muthukrishnanr4** [comment]
hey,

Did u find the solution...i too have same problem....

**Comment by daniellee** [comment]
I'll take a look - I saw the same thing with another plugin.

**Comment by muthukrishnanr4** [comment]
Any update on this issue...

**Comment by torkelo** [comment]
Looks like you tried to install a custom external plugin to grafanas internal built in plugins dir. External plugins to the plugins dir (data/plugins)
