### ISSUE TITLE
query() always uses now as an end of time range in alerts

### ISSUE THREAD

**Issue by andrei-kolosok** [grafana/grafana#10039]
query function uses now() as an end of time range despite any second time-parameter

Example:
`
query(A, 10m, now-5m)
`

Expectable behavior: time range from the 10th minute in the past to 5th.

Actual time range array:
```
points:Array[10]
0:Array[null,1512048660]
1:Array[1613.5666666666666,1512048720]
2:Array[1606.9333333333334,1512048780]
3:Array[1618.8166666666666,1512048840]
4:Array[1623.6833333333334,1512048900]
5:Array[1632.95,1512048960]
6:Array[1617.35,1512049020]
7:Array[1630.1,1512049080]
8:Array[1627.9166666666667,1512049140]
9:Array[378.21666666666664,1512049200]
```
the last item's timestamp is 30/11/2017, 14:40:00 (instead of -5 minutes), which it current time, the amount of basket is also not correct (10 instead of 5).

The idea of such query is using of "completed" basket of data rather than the one in progress.

Looks like the problem is with the function `formatTimeRange` in `pkg/tsdb/graphite/graphite.go:157`, which should replace `now-Xm` to `-Xm` accordingly: 
http://graphite.readthedocs.io/en/latest/render_api.html#from-until

**Comment by bergquist** [comment]
Closed by #10042
