### ISSUE TITLE
Use POST Requests to query data from influxdb

### ISSUE THREAD

**Issue by datamuc** [grafana/grafana#10038]
Please include this information:
- What Grafana version are you using?  
4.6.2
- What datasource are you using?  
influxdb
- What OS are you running grafana on?  
Linux
- What did you do?  
Build a long query
- What was the expected result?  
Result of the query
- What happened instead?  
```
414 Request-URI Too Large

Request-URI Too Large
The requested URL's length exceeds the capacity
limit for this server.


Apache/2.2.12 (Linux/SUSE) Server at localhost Port 443
```
Using POST instead of GET requests would circumvent the problem.

The documentation of InfluxDB [is already fixed.](https://github.com/influxdata/influxdb/issues/8747) So you are save to use POST requests instead. The Apache is running in front of grafana and I have no control over it.

**Comment by praveenmsingh** [comment]
Hi @torkelo, wondering when would this feature be available

**Comment by mephinet** [comment]
For those running into this problem and using nginx: you can increase the [large_client_header_buffers](https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) as a work-around.

**Comment by jd-piq** [comment]
AWS ELB/ALB limits request line to 16k so we're unable to use the load balancer in front of Grafana. 
Would be great to be able to use the body content instead of having to use the query string and avoid running into these kinds limitations.
