### ISSUE TITLE
slack Grafana Hubot Integration --> ERROR SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by amicableperson** [grafana/grafana#10033]
I'm new to node.js / NPM / hubot ..so pls bare with me

Demo version Grafana v4.6.2 installed on windows 7 (64 bit )
Hubot installed with slack adapter on windows 7 (64 bit) 
Slack windows app 

slack:
user: ping
slack : PONG (slack and hubot communication is working fine) 

user: graf list

This fails in grafana.coffee for JSON parsing 

[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] ERROR SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>:null:null)
    at C:\Users\xxxxxxx\Documents\PROJECTS\slack\ahubot\node_modules\hubot-grafana\src\grafana.coffee:297:19
    at IncomingMessage.<anonymous> (C:\Users\xxxxxx\Documents\PROJECTS\slack\ahubot\node_modules\scoped-http-client\src\index.js:95:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

when i printed the body (response from grafana) it shows html response which offcourse JSON cannot parse

how to fix the output from grafana in the format expected by JSON 

-------------------------------------
[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] DEBUG Message 'aiodemo graf list' matched regex /
ons = { id: null }
[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] DEBUG Executing listener callback for Message 'ai
[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] DEBUG { Accept: 'application/json',
  'Content-Type': 'application/json' }
[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] DEBUG http://localhost:8090/
[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] DEBUG search
[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] DEBUG <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#000">

    <title>Grafana</title>

                <base href="/" />

                  <link rel="stylesheet" href="public/build/grafana.dark.css?v4.6.2">

                        </footer>
                </grafana-app>

        <script>

          ----------------------

                window.grafanaBootData = {
                        user:{"isSignedIn":false,"id":0,"login":"","email":"","name":"","lightTheme":false,"orgId":0,"orgName":"","orgRole":"","isGrafanaAdmin":false,"gravatarUrl":"","timezo
ne":"browser","locale":"en-US","helpFlags1":0},
                        settings: {"alertingEnabled":true,"allowOrgCreate":false,"appSubUrl":"","authProxyEnabled":false,"buildInfo":{"buildstamp":1510823965,"commit":"8db5f087e","env":"prod
uction","hasUpdate":false,"latestVersion":"4.6.2","version":"4.6.2"},"datasources":{"-- Grafana --":{"meta":{"type":"datasource","name":"-- Grafana --","id":"grafana","info":{"author":{"name
":"","url":""},"description":"","links":null,"logos":{"small":"public/img/icn-datasource.svg","large":"public/img/icn-datasource.svg"},"screenshots":null,"version":"","updated":""},"dependen
cies":{"grafanaVersion":"*","plugins":[]},"includes":null,"module":"app/plugins/datasource/grafana/module","baseUrl":"public/app/plugins/datasource/grafana","annotations":true,"metrics":true
,"alerting":false,"builtIn":true,"routes":null},"name":"-- Grafana --","type":"datasource"},"-- Mixed --":{"meta":{"type":"datasource","name":"-- Mixed --","id":"mixed","info":{"author":{"na
me":"","url":""},"description":"","links":null,"logos":{"small":"public/img/icn-datasource.svg","large":"public/img/icn-datasource.svg"},"screenshots":null,"version":"","updated":""},"depend
encies":{"grafanaVersion":"*","plugins":[]},"includes":null,"module":"app/plugins/datasource/mixed/module","baseUrl":"public/app/plugins/datasource/mixed","annotations":false,"metrics":true,
"alerting":false,"queryOptions":{"minInterval":true},"builtIn":true,"mixed":true,"routes":null},"name":"-- Mixed --","type":"datasource"}},"defaultDatasource":"-- Grafana --","disableLoginFo
rm":false,"disableSignoutMenu":false,"externalUserMngInfo":"","externalUserMngLinkName":"","externalUserMngLinkUrl":"","googleAnalyticsId":"","ldapEnabled":false,"panels":{"alertlist":{"base
Url":"public/app/plugins/panel/alertlist","hideFromList":false,"id":"alertlist","info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos":
{"small":"public/app/plugins/panel/alertlist/img/icn-singlestat-panel.svg","large":"public/app/plugins/panel/alertlist/img/icn-singlestat-panel.svg"},"screenshots":null,"version":"","updated
":""},"module":"app/plugins/panel/alertlist/module","name":"Alert List","sort":6},"dashlist":{"baseUrl":"public/app/plugins/panel/dashlist","hideFromList":false,"id":"dashlist","info":{"auth
or":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/dashlist/img/icn-dashlist-panel.svg","large":"public/app/p
lugins/panel/dashlist/img/icn-dashlist-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/dashlist/module","name":"Dashboard list","sort":7},"gettingstarte
d":{"baseUrl":"public/app/plugins/panel/gettingstarted","hideFromList":true,"id":"gettingstarted","info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","li
nks":null,"logos":{"small":"public/app/plugins/panel/gettingstarted/img/icn-dashlist-panel.svg","large":"public/app/plugins/panel/gettingstarted/img/icn-dashlist-panel.svg"},"screenshots":nu
ll,"version":"","updated":""},"module":"app/plugins/panel/gettingstarted/module","name":"Getting Started","sort":100},"graph":{"baseUrl":"public/app/plugins/panel/graph","hideFromList":false
,"id":"graph","info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/graph/img/icn-graph-panel.svg",
"large":"public/app/plugins/panel/graph/img/icn-graph-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/graph/module","name":"Graph","sort":1},"heatmap":{
"baseUrl":"public/app/plugins/panel/heatmap","hideFromList":false,"id":"heatmap","info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos"
:{"small":"public/app/plugins/panel/heatmap/img/icn-heatmap-panel.svg","large":"public/app/plugins/panel/heatmap/img/icn-heatmap-panel.svg"},"screenshots":null,"version":"","updated":""},"mo
dule":"app/plugins/panel/heatmap/module","name":"Heatmap","sort":5},"pluginlist":{"baseUrl":"public/app/plugins/panel/pluginlist","hideFromList":false,"id":"pluginlist","info":{"author":{"na
me":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/pluginlist/img/icn-dashlist-panel.svg","large":"public/app/plugins
/panel/pluginlist/img/icn-dashlist-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/pluginlist/module","name":"Plugin list","sort":100},"singlestat":{"ba
seUrl":"public/app/plugins/panel/singlestat","hideFromList":false,"id":"singlestat","info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"log
os":{"small":"public/app/plugins/panel/singlestat/img/icn-singlestat-panel.svg","large":"public/app/plugins/panel/singlestat/img/icn-singlestat-panel.svg"},"screenshots":null,"version":"","u
pdated":""},"module":"app/plugins/panel/singlestat/module","name":"Singlestat","sort":2},"table":{"baseUrl":"public/app/plugins/panel/table","hideFromList":false,"id":"table","info":{"author
":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/table/img/icn-table-panel.svg","large":"public/app/plugins/p
anel/table/img/icn-table-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/table/module","name":"Table","sort":3},"text":{"baseUrl":"public/app/plugins/pa
nel/text","hideFromList":false,"id":"text","info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/te
xt/img/icn-text-panel.svg","large":"public/app/plugins/panel/text/img/icn-text-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/text/module","name":"Text
","sort":4}}},
                        mainNavLinks: [{"text":"Dashboards","icon":"icon-gf icon-gf-dashboard","url":"/","children":[{"text":"Home","url":"/"},{"text":"Playlists","url":"/playlists"},{"text"
:"Snapshots","url":"/dashboard/snapshots"}]}]
                };
        </script>

        <script type="text/javascript" src="public/build/manifest.5d26d942b1e2171a9c11.js"></script><script type="text/javascript" src="public/build/vendor.ebd7fde2922615864fb4.js"></script>
<script type="text/javascript" src="public/build/app.5331f559bd9a1bed9a93.js"></script></body>
</html>

[Wed Nov 29 2017 22:25:11 GMT-0600 (Central Standard Time)] ERROR SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>:null:null)

**Comment by torkelo** [comment]
please report issue here: https://github.com/stephenyeargin/hubot-grafana
