### ISSUE TITLE
[bug]  Incorrect alert occurs. "No data"

### ISSUE THREAD

**Issue by kimbc** [grafana/grafana#10035]
Please include this information:
- What Grafana version are you using?
grafana v4.5.2 (commit: v4.5.2)

- What datasource are you using?
prometheus

- What OS are you running grafana on?
CentOS Linux release 7.4.1708 (Core)

- What did you do?
there is a data, but Incorrect alert occurs. "No data"

- What was the expected result?
I expected "Yes data"

- What happened instead?
but it occured "No data"

![image](https://user-images.githubusercontent.com/33241099/33419027-fa128b26-d5eb-11e7-9e1d-9314b6d6d7fc.png)

-- metric

metric query : max(max_over_time(mysql_global_status_threads_connected{instance="pro200_247-148"}[10s]) or mysql_global_status_threads_connected{instance="pro200_247-148"})

![image](https://user-images.githubusercontent.com/33241099/33419096-3cf79148-d5ec-11e7-90ac-d9bd28490880.png)

-- alert config

![image](https://user-images.githubusercontent.com/33241099/33419121-5c873ec8-d5ec-11e7-89f3-b665446130f7.png)

-- test rule result

![image](https://user-images.githubusercontent.com/33241099/33419208-d10031b0-d5ec-11e7-8658-80ab6f35f8d1.png)

thanks.

**Comment by kimbc** [comment]
I think this is related with template variables. (not sure)

I removed this dashboard,  and re-create it without template variables.

it works good. there is no bug.

thanks.

**Comment by lkqy** [comment]
hi kimbc, I also reach it when there is  template variables.
data souce varible:
![image](https://user-images.githubusercontent.com/1754588/33511425-a329809c-d755-11e7-9562-b764cbf82edc.png)


when save alert config, it alert:
![image](https://user-images.githubusercontent.com/1754588/33511426-abd10468-d755-11e7-825e-0571ebd76452.png)

**Comment by torkelo** [comment]
template variables are no supported in alerting queries.
