### ISSUE TITLE
New Ansible provisioning role

### ISSUE THREAD

**Issue by paulfantom** [grafana/grafana#10045]
[Ansible role listed in docs](https://github.com/picotrading/ansible-grafana) hasn't got any updates in ~2 years, thus it doesn't support many things grafana got since that time, so I wrote a [new role](https://github.com/cloudalchemy/ansible-grafana) (PRs welcome :smile: ). This one has fully featured CI pipeline with unit tests written in [molecule framework](https://github.com/metacloud/molecule). It also supports things like adding datasources (via grafana API) and dashboards (taken from official site). This role is used in production by company I work for ([SoInteractive](https://github.com/SoInteractive)), and we are commited to support it. Currently this role isn't as universal as picotrading one, but it is easier to configure and I am aiming to support all grafana configuration options in 1.0 release of my role.

Would you be interested in including this role in your documentation?

**Comment by bergquist** [comment]
A Pull request would be appreciated :)

**Comment by paulfantom** [comment]
@bergquist here you go :)

BTW official documentation site is a little bit messy. There is a link to [installation via provisioning tool](http://docs.grafana.org/installation/provisioning/) which links to one page. However after clicking "Edit this page" it links to [GitHub 404](https://github.com/grafana/grafana/edit/master/docs/sources/installation/provisioning.md).

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10055

**Comment by paulfantom** [comment]
@bergquist one question, is [official documentation site](http://docs.grafana.org/) rebuild periodically from github sources or it is rebuild on demand?

**Comment by bergquist** [comment]
rebuilt on demand. Will publish soon when I've made some more changes :)

**Comment by paulfantom** [comment]
@bergquist thanks :+1:
