### ISSUE TITLE
Special characters in influx measurement names are not URL encoded correctly

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#10048]
- What Grafana version are you using? **4.6.0**
- What datasource are you using? **InfluxDB**
- What OS are you running grafana on? **Ubuntu 16.04** (with Chrome on MacOS as client)
- What did you do? **Query a metric with '>' in the measurement name**
- What was the expected result? **To see the data of that metric**
- What happened instead? **There was no data returned**

Reason: The `>` in the measurement name was URL encoded as `%26gt%3B` instead of `%3E`. This means it was translated to the HTML symbol `&gt;` before it was URL encoded, instead of directly encoding `>`. 

I tried with an older version of grafana (4.1.1) in the same browser, and there the encoding happened correctly and the query worked.

**Comment by SamuelToh** [comment]
@coussej @torkelo I just checked Grafana version 5 and I couldn't replicate it. Probably can close this.
