### ISSUE TITLE
Alert List Panel is not respecting row height or Max Items

### ISSUE THREAD

**Issue by christianblackburn** [grafana/grafana#10047]
Grafana version: 4.6.2
Datasource: Grafana
OS running Grafana: Windows Server 2012 R2

The style for the <div class="panel-alert-list"> element doesn't seem to be being set, which stops the Alert Panel from respecting the row height.

Playground example - http://play.grafana.org/dashboard/db/alerting?orgId=1

**Comment by daniellee** [comment]
The height problem might be fixed in master but I also noticed that the max items field does not work when current state is chosen:

![image](https://user-images.githubusercontent.com/434655/33475868-39e1c9c6-d680-11e7-9e54-525ca9d668f2.png)

**Comment by schweikert** [comment]
Please consider backporting this to the 4.6.x branch, if possible.

**Comment by torkelo** [comment]
fixed in master
