### ISSUE TITLE
Dashboard: Copy paste panels and rows

### ISSUE THREAD

**Issue by xo4n** [grafana/grafana#1004]
Hi 
At the moment is is possible to copy a graph within a row in a dashboard would it be possible also to duplicate a row within a dashboard and to copy an existing graph to a different dashboard?

**Comment by swehner** [comment]
I've added a pull request with an implementation of this feature, that we use to compose dashboards (mostly custom dashboards to investigate issues and correlate events ocurring in different graphs). https://github.com/grafana/grafana/pull/1920

**Comment by zerthimon** [comment]
+1

**Comment by rajdeepbhattacharya** [comment]
+1

**Comment by aleung** [comment]
+1
It's two years since this feature request was raised. Hope it can be put into roadmap.

**Comment by ot3** [comment]
Likewise

**Comment by DrGkill** [comment]
I would love this feature too.

**Comment by MarkBlah** [comment]
+1 yes please!

**Comment by utkarshcmu** [comment]
Until we get this feature in Grafana itself, we can use `wizzy` https://utkarshcmu.github.io/wizzy-site/local-commands/row-commands/

**Comment by fksimon** [comment]
Copying panels seems like basic need.
+1

**Comment by jeromegit** [comment]
+1 for me too.
It's a struggle to copy from one dashboard to another.
It should be easy to click on the row's green handle and do a copy and then, later on, click on another row (possibly in a different page) and do a paste.
Thanks!

**Comment by ArtieReus** [comment]
+1

**Comment by PhantomPhreak** [comment]
+1

**Comment by voiprodrigo** [comment]
just needed this! 
+1

**Comment by jcromero** [comment]
+1

**Comment by spacemoose** [comment]
+1

**Comment by aplsek** [comment]
+1

**Comment by coofercat** [comment]
As a workaround, try the Json edit method:

Click on 'Manage Dashboard' -> 'View JSON'. Cut and paste all of the JSON to the left hand pane on this Json editor: http://www.jsoneditoronline.org/. Click the arrow pointing to the right to populate the data view. You can duplicate rows quite easily, you can even duplicate or remove panels, but you may want to use Grafana for that.

Once happy, click the left arrow to re-generate Json, cut and paste it into 'Import Dashboard' in Grafana. A bit cumbersome, but it works!

**Comment by aplsek** [comment]
I understand the workaround. But if you want to use Grafana in big production systems this becomes a problem.

If you have tens of dashboards with hundreds of graphs, you want to share graph definitions across dashboards so if you update a graph it propagates to all dashboards where this graph is displayed. 

Otherwise you keep maintaining the same graph across different dashboards and you never know if you have got them all or missed some.

**Comment by ehcoolguy** [comment]
@coofercat Thanks for the hint! I used this method as the workaround on current stable version (4.2.0). Just one thing I would mention that while "duplicate" row within jsoneditor, don't forget to change the "id" property in each component, or you may find all component with same ID changed as well.
Honestly, I hope this can soon become the standard function in Grafana, is there any progress on this?

**Comment by edi-bice** [comment]
+1

**Comment by jamerobe** [comment]
+1

**Comment by bfosberry** [comment]
thanks @torkelo, still helping users after all this time

**Comment by willihelm** [comment]
+1

**Comment by Dark0096** [comment]
+1

**Comment by mgolahi** [comment]
+1

**Comment by luisdavim** [comment]
+1

**Comment by bergerx** [comment]
Many people have been asking about this feature for a long time. In my current team, as people suffered the lack of this feature in their previous work places, we've been discussing previously rejected PRs like #1920 and still not having it even after 2+ years in the project.

What about bringing #1920 to discussion again? This would address many people's suffering.

**Comment by luisdavim** [comment]
I agree with @bergerx closing a PR because the UX is not good enough and not providing any better alternatives is not the best way to deal with this. If that had been merged the UX would have certainly evolved in the past 2 years if users didn't find it good enough.

**Comment by torkelo** [comment]
It's not?

**Comment by MarvAmBass** [comment]
+1

**Comment by biohazardxxx** [comment]
+1
3 years later..... thats a pitty :-(

**Comment by wols** [comment]
@umjoshi Grafana 4.6.0...
1. Graph Panel JSON: 'select all' and copy to clipboard
2. add new (default) Graph Panel
3. Graph Panel JSON: 'select all' and delete
4. copy from clipboard and 'Update'
...a workaround but it works for me.

**Comment by ivspbitec** [comment]
+1

**Comment by ivspbitec** [comment]
+1 
Row panel JSON and copy it to clipboard will be great for me

**Comment by npockrus-bnet** [comment]
+1
I've been using grafana for about 4 days and I'm already needing this.

**Comment by honza-s** [comment]
+1 for this feature too.
workaround using json export/import is working but imo it could be more straightforward.

**Comment by torkelo** [comment]
Initial support for copying panels between dashboards is now implemented, not great but at least something. 

<img width="444" alt="screen shot 2017-12-26 at 13 23 07" src="https://user-images.githubusercontent.com/10999/34356656-f8df3ba6-ea3f-11e7-8647-ed151fd2ee94.png">

Think we need to evolve this feature a bit further. Maybe even to a fully backend saved "Favourite panels", a simple modal to name the panel and saved it, and some way to view "favourite panels" from the add panel view and you have a pretty good way to reuse panels.

**Comment by beingyash** [comment]
Copy-pasting rows like we do panels would be great. What's the challenge involved here?

**Comment by trallnag** [comment]
If you have the need to have a whole set of panels available in multiple different dashboards, wouldn't the way to go be provisioning via something like grafonnet / jsonnet? I can imagine that introducing a feature like that into Grafana itself would also introduce a bunch of new complexities

**Comment by Gilbert-T** [comment]
+1
yes, please

**Comment by tonycasanova** [comment]
We use the duplicate panel all the time so thank you for that functionality!   Being able to duplicate Grafana Rows with many panels under them would be awesome.   We monitor the same / similar metrics from different levels of the system which requires duplicate rows with slight changes.

**Comment by IshaGirdhar** [comment]
+1, row duplication functionality would be really appreciated.

**Comment by malekhin** [comment]
It would be convenient to copy Row along with everyone Visualizations

**Comment by qazer2687** [comment]
+1

**Comment by sooren0936** [comment]
+1 that would great to make **copy row** OR add another feature - **link to row** (like panel link)

**Comment by DYH-Hong** [comment]
Related to [#23762](https://github.com/grafana/grafana/issues/23762)
