### ISSUE TITLE
Configuring Grafana for Active Directory LDAP authentication

### ISSUE THREAD

**Issue by pvginkel** [grafana/grafana#10040]
I'd like to request an update to the LDAP configuration at http://docs.grafana.org/installation/ldap/. It took me quite some time to configure Grafana in a decent way for Active Directory and the referenced documentation and other sources on the Internet weren't of much help. Specifically it suggests you need to have a read only user and its password stored in the `ldap.toml`. This is not ideal, nor necessary.

Anyway, what I found.

Assuming:

* IP address of the AD server: `10.0.0.1`;
* AD domain: `CORP`;
* AD DNS name: `corp.local`.

Then, the following configuration will work.

```yaml
[[servers]]
host = "10.0.0.1"
port = 3269
use_ssl = true
start_tls = false
ssl_skip_verify = true
bind_dn = "CORP\\%s"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=corp,dc=local"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"
```

This configuration specifically works around what the documentation describes as how you should configure your `bind_dn`. By including the AD domain in the `bind_dn`, you can leave the `bind_password` and the bind will be done on the username and password. This is Active Directory specific and likely won't work in OpenLDAP (see https://serverfault.com/a/643615). The only thing you then need is the `search_filter` which in the above example searches on username, and the `search_base_dns` which has the expanded DNS name form.

The port uses a default, encrypted, port. There are a few options for this, and https://technet.microsoft.com/en-us/library/dd772723(v=ws.10).aspx has the details.

And that's it. You still need to configure `[[servers.group_mappings]]` in a decent manner, but that should be it. Also, there are still a few more options in e.g. to provide a certificate (and `ssl_skip_verify = true` is not ideal). Review and modify as necessary.

**Comment by torkelo** [comment]
thanks, we will try to add this to the docs as a concrete example for active directly setup.

**Comment by darkchilli** [comment]
thanks, pvginkel.

I tried your config with Active Directory and it works.
Except our AD doesn't work with SSL, I modified two lines below:

--- ldap.toml ---
port = 389
use_ssl = false

grafana main config attached below:
--- grafana.ini ---
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true      ; It's recommended to leave it on if you want AD user to be automatically created in Grafana. Switch this off will make new user unable to login (if they have never logged on grafana before)

Our environment:

Grafana                       4.6.2
AWS Microsoft Active Directory

**Comment by cuseinovic** [comment]
Hello, 

Thanks @pvginkel ! 
Your configuration and your basesearch are good ! I have just one question about the bindDN. How it's works with your configuration ? Because I've wrote my bind account + password

**Comment by tylerauerbeck** [comment]
@pvginkel @torkelo I'd be more than happy to write this if no one has gotten to this yet. Just walked through these steps and everything worked great.

The question I have is whether it makes sense to clob this together with the existing documentation for LDAP (which is generally the approach that everyone else takes) or whether it makes sense to create a seperate page for Active Directory documentation completely.

**Comment by simonmiller99** [comment]
thanks @[pvginkel] you have saved me an awful lot of head scratching that post.

**Comment by eraydel** [comment]
Excellent!

**Comment by marefr** [comment]
This was extracted and put into the [ldap documentation](https://grafana.com/docs/auth/ldap/#active-directory). Please let us know if there's something missing. Thanks

**Comment by SvenMW** [comment]
please reopen and remove:

```
ssl_skip_verify = true
```

from the current docs and instead explain how to configure a certificate correctly.

inexperienced users will just C&P your docs into their settings and open themselves up to MITM attacks without knowing it.

the current docs are insecure and not fit for production usage this way:

https://grafana.com/docs/grafana/latest/auth/ldap/

see this document for a reasoning, why secure documentation defaults matter:

https://www.ftc.gov/about-ftc/bureaus-offices/bureau-consumer-protection/office-technology-research-investigation/guiding-to-safety-how-technical-documentation-writers-can-encourage-software-security

especially point 3 "Make examples secure":

> Insecure examples can cause real vulnerabilities. Suppose that example code uses an outdated, unsafe algorithm. Developers who simply copy and paste that code could create vulnerabilities in their own code. Some developers may ignore even clear warnings surrounding the example code. As a result, your examples should be as safe as possible under common use cases. Be sure to highlight any remaining risks and assumptions prominently.

HTH
