### ISSUE TITLE
Hello, I just want to tell you, that i found little bug on your web pages. On http://docs.grafana.org/features/panels/singlestat/#coloring There is sentence 5. Invert order: This link toggles the threshold color order. You have bad address to picture in Example. http://docs.grafana.org/img/docs(v1/gyr.png I think, there is problem with "docs(v1", it should be "docs/v1"

### ISSUE THREAD

**Issue by jjeanis** [grafana/grafana#10043]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
thanks, but looks fine?

![image](https://user-images.githubusercontent.com/10999/33517391-d7536238-d783-11e7-80fd-689286bb05a1.png)

maybe a temporary issue

**Comment by H4rry12** [comment]
Sorry for late reaction
But the first one is still broken.
![eror](https://user-images.githubusercontent.com/17526386/34480380-60e895aa-efac-11e7-9cfd-2282257232d5.png)
