### ISSUE TITLE
Passing array variable via URL

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#10054]
In this https://github.com/grafana/grafana/issues/1078#issuecomment-63458678, I found a way how to pass variables via url to my dashboards. 

This works http://url/dashboard/db/dashboard-name?var-ips=111.222.333.445&var-ips=111.222.333.444

This does not http://url/dashboard/db/dashboard-name?var-ips[]=111.222.333.445&var-ips[]=111.222.333.444

I think the second example is the proper way of passing array via get parameters but it is not supported by Grafana. Is that a bug or feature?

_Grafana v4.6.2 (commit: 8db5f08)_

**Comment by torkelo** [comment]
That is not how you do it. The standard way to pass arrays via urls is to repeat the query key, like this:

?var-server=backend_01&var-server=backend_02&var-server=backend_03
