### ISSUE TITLE
[Feat Req]: Support orgId query parameter when anonymous access is enabled 

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#10057]
- What Grafana version are you using?
4.6.2

- What datasource are you using?
influxdb

- What OS are you running grafana on?
linux ubuntu 16.04

- What did you do?
open alert email link "View your Alert rule"

- What was the expected result?
bring user to grafana (login page if required) then after login show (alert graph)

- What happened instead?
link lands user to the public grafana dashboard with error at top right "Dashboard not found"

NOTE:
 - anonymous access enabled
 - use multiple orgs

**Comment by torkelo** [comment]
cannot replicate this, maybe your instance has anonymous access enabled and use multiple orgs? Should work even in that case It think though.

**Comment by steverweber** [comment]
* anonymous access enabled
Yes

* and use multiple orgs
Yes

**Comment by steverweber** [comment]
Also i should note, this has never worked correctly in passed version.

**Comment by torkelo** [comment]
Think you need to disable anonymous access for it to work properly.

**Comment by steverweber** [comment]
disabling anonymous access and deploying a second grafana service/server for anonymous access would workaround the issue.

**Comment by steverweber** [comment]
likely faster for me to try to patch than deploy another server and maintain it.

fyi, nice code to read however i'll need a little direction.

thinking .. perhaps somthing needs to be done with comparing ` orgQuery.Result.Id` in:
https://github.com/grafana/grafana/blob/314bff1b786d57065b8b80e569d5da8565d6f927/pkg/middleware/middleware.go#L77
```
like
if ctx.OrgId is set && orgQuery.Result.Id != ctx.OrgId {
    ctx.AllowAnonymous = false
}
```

or perhaps in : `func Auth(options *AuthOptions) macaron.Handler `
https://github.com/grafana/grafana/blob/05d43999dc83c2adc5bda27eb8e41e0b762c35ea/pkg/middleware/auth.go#L76
```
# something like...
if c.AllowAnonymous {
    anonymousOrg := m.GetOrgByNameQuery{Name: setting.AnonymousOrgName}
    if err := bus.Dispatch(&anonymousOrg); err == nil {
        if c.OrgRole != anonymousOrg.Result.Id  {
           notAuthorized(c)
           return
        }
    }
}
```

Im not much of a go programmer so my attempts might be pitiful/

**Comment by steverweber** [comment]
also seems to have issues with  anonymous login,:  https://github.com/grafana/grafana/issues/9933

**Comment by Jguer** [comment]
Closing stale issue
