### ISSUE TITLE
Missing core dependency

### ISSUE THREAD

**Issue by sstalin** [grafana/grafana#10053]
Regarding PR https://github.com/grafana/grafana/pull/10051
Can you please add the missing dependency?

**Comment by torkelo** [comment]
which plugin is using this?

**Comment by sstalin** [comment]
@torkelo I've created plugin for MonetDB which at the time was using SystemJS and query-part as dependency. The plugin is heavily inspired by the older version of InfluxDB source plugin. 

Thanks

**Comment by torkelo** [comment]
Like to wait exposing this unless we have to. So far you are the only one who has used this internal component. Going forward we will be more explicit about what you can use. We might reconsider if there is demand for something like this but this component is very complex and we will likely rework it in the future.
