### ISSUE TITLE
Time macros in postgres templating

### ISSUE THREAD

**Issue by RSloeserwij** [grafana/grafana#10066]
Hi,

I was trying to include the time macros in a template variable query for a postgres datasource in version 4.6.1 .  I found out however, that both $__unixEpochFrom() and $__unixEpochTo() were read as 0, meaning that both timeFrom and timeTo were set to 1970-01-01. Is there a way around this?

![image](https://user-images.githubusercontent.com/20596929/33553457-276ccbc6-d8f9-11e7-8f2f-de2fec4e08c0.png)

**Comment by svenklemm** [comment]
Looks like the timerange context is not properly passed along on template queries. Influxdb and mysql are affected by this aswell it seems.
