### ISSUE TITLE
Create DEVELOPMENT.md with more details about how to setup a dev env for Grafana

### ISSUE THREAD

**Issue by WOOOFEI** [grafana/grafana#10062]
### I was trying to add some my own features to grafana these days, it takes so long to run grunt build every time, is there any solution can speed up grunt build in development?  😋

**Comment by bergquist** [comment]
Install yarn and run `yarn dev` instead. 

We should create a `DEVELOPMENT.md` with more details about the dev setup and link to it from README.md

**Comment by WOOOFEI** [comment]
I'm looking forward to it.😀

**Comment by torkelo** [comment]
No, it's npm run watch (if you want to work m on frontend)

**Comment by torkelo** [comment]
Npm run watch, takes time to start first time (15 sec) but then after change its just one about 1-3 seconds

**Comment by bergquist** [comment]
Haha. we clearly need this! :)

**Comment by torkelo** [comment]
Well it's pretty clearly included in README and build from source docs.

**Comment by oddlittlebird** [comment]
@ivanahuckova , @marcusolsson , @torkelo - We have expanded the contribution documentation for developers considerably since 2017. Has this issue been addressed? Can we close it?

**Comment by torkelo** [comment]
yes
