### ISSUE TITLE
In the multiple browser tab using the same account to access different "orgid" dashboard, "Not found" error occurs.

### ISSUE THREAD

**Issue by YouZhengChuan** [grafana/grafana#10065]
Please include this information:
- What Grafana version are you using?
4.7.0-pre1
- What datasource are you using?
mysql
- What OS are you running grafana on?
MacOS 10.13.1
- What did you do?
If you use the same account in more than one browser tab to access the dashboard in a different "orgid", a "Not found" error will appear, like this:

## 1. Browse the grafana home page in each of the two browser tabs
![image](https://user-images.githubusercontent.com/3882312/33551535-9d28bafe-d92c-11e7-9e2e-8284605b45d9.png)

## 2. In one of the tabs, switch to the other "orgid"
![image](https://user-images.githubusercontent.com/3882312/33551775-67a7b5be-d92d-11e7-8cb8-2c500fc6c70a.png)

## 3. In another tab to access the dashboard, will get “dashboard not found”
![image](https://user-images.githubusercontent.com/3882312/33551816-8a41ba52-d92d-11e7-8137-c040747c6987.png)

![image](https://user-images.githubusercontent.com/3882312/33551885-da27069e-d92d-11e7-9908-eb34dd09ee2e.png)

**Comment by torkelo** [comment]
Simultaneously using multiple orgs is not supported

**Comment by maufc** [comment]
Does grafana supports multiple browser windows or browser tabs in order to view different dashboards on its?
I open multiple tabs and dashboards doesnt load
Is it a cookies configuration issue?
What about multiple users login? not supported too?
Thanks!
