### ISSUE TITLE
Postgres $__timeGroup macro in select requires "as time" in query

### ISSUE THREAD

**Issue by wanderutwells** [grafana/grafana#10074]
Grafana version: 4.6.2
OS: Linux (Amazon Linux AMI)

Can $__timeGroup be made to imply "AS time" in queries in the same way that $__time does?

For example this works:

```
SELECT
  $__time(purchase_datetime),
  company as metric,
  sum(paid_price) as value
FROM
  purchases
WHERE
  $__timeFilter(purchase_datetime)
GROUP BY 1,2
ORDER BY 1,2 ASC
```

While this:

```
SELECT
  $__timeGroup(purchase_datetime,'10m'),
  company  as metric,
  sum(paid_price) as value
FROM
  purchses
WHERE
  $__timeFilter(purchase_datetime)
GROUP BY 1,2
ORDER BY 1,2 ASC
```

Results in: "error": "Found no column named time"  and requires $__timeGroup(purchase_datetime,'10m') AS time to work

Thanks

**Comment by svenklemm** [comment]
The initial version of the macro was meant to be used in the group by clause where the ```as``` would produce a syntax error i later enhanced the macro so it could be used in the select clause aswell. I guess now that it can be used as part of the select most people use it there and it makes sense to include the column alias.

This will break queries which use the current behaviour though.

**Comment by torkelo** [comment]
tricky, introducing breaking changes are not great but making it more consistent is also important.

**Comment by AndyMender** [comment]
I think it would be a good idea to reflect this in the docs: http://docs.grafana.org/features/datasources/postgres/
and the "Show Help" drop-down menu in the panel. As it is now it reads:
Example of group by and order by with $__timeGroup:
```language="postgresql"
SELECT
  min(date_time_col) AS time_sec,
  sum(value_double) as value
FROM yourtable
group by $__timeGroup(date_time_col, '1h')
order by $__timeGroup(date_time_col, '1h') ASC
```
which is not correct as we know (grouping must include `time`).

**Comment by svenklemm** [comment]
grouping must not include time in the latest version so the docs are correct for postgres

**Comment by AndyMender** [comment]
> grouping must not include time in the latest version so the docs are correct for postgres

There is a discrepancy between what Grafana expects and what is a valid PostgreSQL statement.
Below is a valid SQL statement (although not exactly what I want), which returns an `avg` of column "P_AC_N" and corresponding *selected* time intervals as `time_bucket `(aggregation function of the timescale database extension, though any `extract` aggregation would be equally valid):
```
SELECT avg("P_AC_N") AS "Leisung AC", time_bucket('10m', time)
FROM "inverters"
WHERE extract(epoch from "time") BETWEEN 1355094000 AND 1355439599
GROUP BY time
ORDER by time asc;
```
Grafana however will show `Found no column named time`. If I change it to:
```
SELECT avg("P_AC_N") AS "Leisung AC", time_bucket('10m', time) AS "time"
FROM "inverters"
WHERE extract(epoch from "time") BETWEEN 1355094000 AND 1355439599
GROUP BY time
ORDER by time asc;
```
Grafana displays the data properly.

Below statement is an invalid PostgreSQL statement:
```
SELECT avg("P_AC_N") AS "Leisung AC", "time" FROM "inverters"
WHERE extract(epoch from "time")
BETWEEN 1355094000 AND 1355439599
GROUP BY time_bucket('10m', time) AS "time"
ORDER by time asc;
```
The `AS` clause cannot appear after `GROUP BY`, although Grafana seems to expect that to happen and `GROUP BY` *must* include the column `time` (per what PostgreSQL expects in its query and per what Grafana returns as a database-side error).

**Comment by svenklemm** [comment]
Which version are you using the Show Help should be correct in 5.0 at least.
Thats the code for the Show Help in the frontend:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/partials/query.editor.html

**Comment by AndyMender** [comment]
We use Grafana 4.6.3 from here: https://grafana.com/grafana/download which seems to be the last stable version.

I see now that a lot of the knit-picks have been addressed since then :). Thank you for your assistance and apologies for the confusion. I will consider updating to one of the 5.0.0-betas perhaps.
