### ISSUE TITLE
target.dsType not updated after switching datasource to postgres

### ISSUE THREAD

**Issue by wanderutwells** [grafana/grafana#10072]
Noticed this while trying to prepare a different bug report.

Grafana version: 4.6.2
OS: Linux (Amazon Linux AMI)

We have an influxdb data source and a postgres datasource. When creating a new panel on a dashboard, influxdb is the default shown. However if I select my postgres datasource and setup my queries is works as expected.

When I view the panel JSON though it still says that the dsType is influxdb even after saving the panel and dashboard. This seems to happen across multiple types of panels (observed with JSON output for graph and table at least). I would expect this to say "postgres" instead. I'm not sure if it's causing any other problems though.

snippet of my JSON output:

  "datasource": "Warehouse Reporting",
  "targets": [
    {
      "policy": "default",
      "dsType": "influxdb",
      "resultFormat": "time_series",
      "orderByTime": "ASC",

**Comment by svenklemm** [comment]
Hmm I think it means your default datasource for the dashboard is influxdb. The JSON for the panels itself should reference your postgres datasource by name though.
Maybe @torkelo or @daniellee can confirm.

**Comment by wanderutwells** [comment]
That is correct. My default datasource is influxdb. I would have expected the panel json to represent the configured datasource of the panel though. If I'm misunderstanding the purpose of this in the panel json, please close the bug. Thanks!

**Comment by bergquist** [comment]
Seems to be an old unused property https://github.com/grafana/grafana/search?utf8=%E2%9C%93&q=dsType&type=

**Comment by bergquist** [comment]
Removed it from the code to not cause any future confusion.
