### ISSUE TITLE
[Bug] Render value as link in Table panel: ampersand symbol "&" is not escaped in link URL, resulting URL is wrong.

### ISSUE THREAD

**Issue by Angrite** [grafana/grafana#10078]
Read before posting: 

Please include this information:
- What Grafana version are you using?  
4.6.2

- What datasource are you using? 
Maria DB

- What OS are you running grafana on? 
Debian Stretch

- What did you do? 
Defined a link in Table panel for row cell, which contains text value with ampersand symbol

- What was the expected result? 
Navigating to dashboard with templating variable

- What happened instead?
Navigation URL is broken, no data selected

Details:

Render value as link in Table panel: ampersand symbol "&" is not escaped in link URL, resulting URL is wrong.
If string value contains ampersand "&", resulting URL contains not-espaped ampersand symbol.
As a result, URL is wrong.

Example: String **O&M** is rendered in URL as **O&M**, not **O%26M**

Grafana 4.6.2, Maria DB

**Comment by Angrite** [comment]
Dear Torkelo, 
Thank you for pointing to the source code!

**Comment by Angrite** [comment]
Well, fast fix is to change here:

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/table/renderer.ts#L130

to 

**scopedVars[cell_variable] = {value: encodeURIComponent(row[i])};** 

Call to encodeURIComponent  used in many places in grafana.

I've built from the source 4.6.2, this fix works. Now I'm testing it on my production server.

**Comment by Codelica** [comment]
Not to hijack this issue, but it seems that & not being escaped may extend further than just table panels.  When adding "links" to a graph panel and using template variables, I'd assume & should be escaped there also?

eg.   var-somevar=$someTemplateVar

where myTemplateVar includes an & like "Steak & Shake", I just see 'Steak%20&%20Shake'

I've been hunting to see if there is some alternate way to output template vars that are escaped by chance, but haven't seen anything.

**Comment by rmunoz10** [comment]
Hi - I'm using grafana v6.5 and running into similar issue - link sends unencoded "AT & T" value and breaks.
