### ISSUE TITLE
Grafana 5.0: Create new folder flow

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#10085]
Remove the modal for the Create New Folder and instead create new page (similar to the Import page).

Ref #10083

**Comment by torkelo** [comment]
It page can still exist in nav under Create (so appears as link there like now).

The page just needs to do this:

this.navModel = navModelSrv.getNav('dashboards', "manage-dashboards', 0);

And the page will get the dashboard section page header & tabs.
