### ISSUE TITLE
Grafana 5.0: Manage Dashboards page UX

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#10081]
Get as much as possible done of the UX for the new Manage Dashboards page but leave creating new components for the next milestone.
 
![image](https://user-images.githubusercontent.com/434655/33601785-86a6a30a-d9ad-11e7-84af-75969c9aa7f1.png)

**Comment by marefr** [comment]
Need some styling of the selected *Tags* and *Clear current search query and filters* before alpha 1. Right now it looks like this:

![image](https://user-images.githubusercontent.com/1668778/33953110-34883da8-e034-11e7-9769-ea495636d489.png)
