### ISSUE TITLE
Variables: Add function/expression variable type

### ISSUE THREAD

**Issue by sparr** [grafana/grafana#10094]
I find myself in the situation where I need to apply a function like `aliasSub(aliasSub(aliasSub(somemetric, "foo\.(bar|meh)\.(aaa|bb|cde|ffff)\.([^.]+)\.([^.]+)-([^.]+)-(\d+)\.([^.]+)\.(.+)", "\2-\3-\7.\4\5\6.domain\2.com"), "domainffff.com", "otherdomain.com"), "1234", "5678")` to thousands of queries across hundreds of panels on dozens of dashboards. I will probably end up using configuration management tools and the API to accomplish this. It would be very useful if I could define a function somewhere in the grafana interface then have it available to use in my queries, then the queries would get rewritten before being sent to graphite, so maybe my query would just be `aliasDomain(somemetric)` and elsewhere I would have defined `aliasDomain` to that whole thing above.

**Comment by bergquist** [comment]
Hm. I think the most reusable way of solving this issue would be to introduce global template variables. Store this kind of expression as a global value and reuse it in all queries.

**Comment by sparr** [comment]
To clarify, my `somemetric` is different on every panel. I basically want to wrap all my existing metric queries in that trio of aliasSub() calls.

**Comment by hugohaggmark** [comment]
This is a sub feature for #1959

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
