### ISSUE TITLE
RFE: Don't hardcode macros in postgres data source

### ISSUE THREAD

**Issue by larsks** [grafana/grafana#10096]
I'm using Grafana (4.6.1) with the PostgreSQL data source (in conjunction with the timescaledb extension). The Postgres data source hardcodes a number of macros, such as `__timeFilter`.  Depending on the structure of the database (or the available database extensions), the queries produced by these filters can be sub-optimal.

Would it make sense to make these macros configurable at runtime? This would allow a grafana administrator to tune them appropriately so that someone writing queries can continue to use, e.g., `__timeFilter` without needing to know the specifics of the backend.

**Comment by svenklemm** [comment]
Do you really need them configurable at runtime or would a more optimized default be sufficient.
I mean you can always build an optimized query with using $__timeFrom() and $__timeTo() primitives its just less convenient. I could imagine adding a type as datasource attribute like compat, postgres9+, timescale which would overwrite certain macros. Would this cover your use case?

**Comment by larsks** [comment]
I was thinking that by making the macros configurable, someone can write a dashboard that uses `__timeFilter` and share that, and someone who wants to use that wouldn't need to worry about rewriting every single query to replace `__timeFilter` with something else.  Allowing the expansion of that macro to be configurable would make that process much easier.

I guess that having "flavors" for the data source as you propose, where flavors could provide different values for the macros, would also solve that problem, albeit in a slightly less flexible way.

**Comment by svenklemm** [comment]
It would be slightly less flexible but it would allow grafana to have better macro expansions builtin. Could you post the macro expansions you would like to see replaced.

**Comment by daniellee** [comment]
The way we have solved this for other data sources is with a version field in the data source settings. But it is extra code that has to be maintained (support, potential for bugs etc.) - how sub-optimal can it be? And how large is the portion of Postgres users that are affected?

The difference between the Postgres data source and say for example the Graphite data source, is that you do not have to use the macros for Postgres to get a working query - they are just an aid.

**Comment by marefr** [comment]
Fixed in #11592
