### ISSUE TITLE
Feature request: Chart option to hide the graph if it doesn't have metrics or fails.

### ISSUE THREAD

**Issue by oprietop** [grafana/grafana#1009]
I think that should be neat just to remove clutter on the dashbards if some graphs are known to miss metrics.

For example I'm getting snmp metrics from multiple hosts with different operative systems. While they will share some of the metrics there will be some graphs that will never belong to a concrete host, a windows machine won't graph raw cpu/mem/io or system load for instance.

Another example would be removing errors and/or drops graphs on network devices if they don't have any.

Some graphs throw an error when they miss metrics because they can't compute the metrics, so i think the option should also care in that scenario.

**Comment by tanioschahine** [comment]
+1
I have a stacked chart with metrics that may be missing due to software versions. The neatest solution for me would be to ignore the missing metrics and go ahead with all the graph. The existing alert mentioning that there are missing metrics should probably remain there.

**Comment by unkn0wn404** [comment]
+1 for me feature will be very useful. To prevent hiding empty graph by default i suggest there must be optional config to decide show or hide graph. For example, here may be condition to hide graphs if no one data for last 24h or sumary series value for last 12hour more then 100 or anything else. So, everyone can decide by themself how to filter data.

**Comment by glucose1016** [comment]
+1 this is definitely useful for metrics that might change names. When templating with the All feature selected it currently pulls all the metrics for a specific tag, some might not have any data since they might represent no longer active data. What this does is create a dashboard with a handful of empty and non empty charts, it would be nice to have a way to automatically hide the empty charts. Currently on influxdb

**Comment by wfhu** [comment]
So what's situation about this issues now? Merged into the current version?
I'd like to have one page to show graphs about redis and memcache. But redis and memcache do not share the same metrics. So when I select redis:port, it should only show the redis related graphs. So the same to memcache:port. I really need this feature!

**Comment by torkelo** [comment]
@wfhu I am not aware of a pull request that implements this feature request

**Comment by dmulitsa** [comment]
+1

**Comment by cixelsyd** [comment]
+1 "they're good charts, Bront"

**Comment by lin-credible** [comment]
**+1**

**Comment by lename** [comment]
+1 hide table row if the value of row is less than certain value (show only alerting rows and rows that are near alert threshold)

**Comment by shaunroselt** [comment]
+1

**Comment by hubertron** [comment]
+1
