### ISSUE TITLE
Add tooltip for Legend format 

### ISSUE THREAD

**Issue by Passpes** [grafana/grafana#10092]
I am currently facing an issue with Grafana/Prometheus. I've got a [panel](https://grafana.com/plugins/vonage-status-panel) and I am trying to add different queries to it. To be able to configure thresholds I should give every query a unique alias but I really don't know how to do that.

**Comment by torkelo** [comment]
Use the Legend Format field: 

From the docs on http://docs.grafana.org/features/datasources/prometheus/#using-prometheus-in-grafana 

Legend format:  Controls the name of the time series, using name or pattern. For example {{hostname}} will be replaced with label value for the label hostname.

**Comment by torkelo** [comment]
@Ijin08 can you add a tooltip that reads "Controls the name of the time series, using name or pattern. For example {{hostname}} will be replaced with label value for the label hostname." 

to the legend format input field for prometheus? either use bs-tooltip or <info-popover> component

**Comment by Passpes** [comment]
I think you didn't get me right, like for Elasticsearch Datasource in Grafana there's an Alias field:
![image](https://user-images.githubusercontent.com/6490137/33617222-7ae1e426-d9df-11e7-9c97-f88a800fdb53.png)

For Prometheus Datasource that field is missing which complicates the task of programming thresholds in Panel plugin - so is there a way to add that field differently named alias and its value will be different from a query to another?

**Comment by torkelo** [comment]
No I get understand you, it's there. Just called legend format and not alias
