### ISSUE TITLE
alternative storage backends

### ISSUE THREAD

**Issue by marco-hoyer** [grafana/grafana#101]
Hi,

I would really like grafana have another backend to persist dashboards to. A mysql, mongodb or filebased backend would be nice.

Kind regards
Marco

**Comment by sberthelot** [comment]
elasticsearch is largely overkill

Why not use WebDAV ? It's easy from JS to access and is well suited to load/save files...

**Comment by torkelo** [comment]
Grafana 2.0 comes with a backend (written in Go, so single binary) that supports sqlite3 embedded storage (or external sql db) so no dependence on elasticsearch  for dashboard  storage

**Comment by marco-hoyer** [comment]
Sounds great. Do you plan to adopt any other datasources like mysql or maybe pluggable datasources? If I want to run grafana on multiple instances, sqlite is a problem.

**Comment by torkelo** [comment]
@marco-hoyer mysql and postgres is also supported

**Comment by kadaan** [comment]
What about those of us in Windows shop?  Will mssql be supported or will it be straightforward to create a data store plugin?

**Comment by torkelo** [comment]
@kadaan mssql is not supported right now, but that dialect could be added. But my understanding is that mysql and postgres both work well on windows so mssql support should not be needed just in order to support windows. 

On a side note, coming from Windows development myself (worked 10 years with mostly C# .NET development, but now 100% on linux systems), long term I want Grafana to work well on windows, even considered spending effort on getting Graphite or InfluxDB to work well on Windows.

**Comment by swehner** [comment]
Are there any plans on implementing ElasticSearch as a backend for Grafana 2.0?
We're actually using Grafana pretty heavily in our setup and have a lot of dashboards (mostly autogenerated) for production machines and a lot of other aspects of our environment.
The elastic search features are fantastic for that, as we can not only search for text ocurring in the title but also other parts of the dashboard definitions.

**Comment by torkelo** [comment]
@swehner elasticsearch is not really a good option as a general purpose data store. It is awesome for search, but not good as primary storage for users, accounts, configuration. 

So for Grafana 2.0 and forward elasticsearch will not be supported for dashboard storage (mysql, postgres or sqlite3 will fill that role). Elasticsearch can still be used for annotations, and eventually metrics and table log data.

**Comment by staticmukesh** [comment]
@torkelo , I want to work on MongoDb integration in Grafana, as an alternative to sqlite/mysql. Are you working on it ?

**Comment by torkelo** [comment]
@staticmukesh nope

**Comment by luisdavim** [comment]
why drop the support to store the dashboards in elasticsearch? For me this is a step back :(

**Comment by naeemkhedarun** [comment]
I appreciate the effort in adding support for alternative databases! Unfortunately, for us, it would have been great to retain the ability to store dashboards in elastic.

**Comment by torkelo** [comment]
@naeemkhedarun it's not really a good alternative for storing master data in, great for logs and search stuff :)

**Comment by naeemkhedarun** [comment]
@torkelo I agree :-) 

Our use case in this instance is dashboards stored in source control and deployed to Grafana. We have multiple Grafana instances behind a load balancer reading from our elastic client nodes. Ideally with the dashboards deployed to the same elastic cluster, we only need one datasource (elastic) to serve all Grafana instances for both dashboards and data. 

With the current Grafana version we need to deploy and maintain a mysql instance too which is undesirable. 

Would you consider that a reasonable case for the feature?

**Comment by torkelo** [comment]
Of course, but looks like MySQL or postgres solves that  awe pretty well (supporting multiple instances of Grafana behind load balancer) don't understand why storing dashboards in elasticsearch would solve, you still need a proper database for grafana to store users profiles, alerts, data source configuration, org setup, session store etc
