### ISSUE TITLE
Stacked lines should not have overlapping lines

### ISSUE THREAD

**Issue by mupdt982** [grafana/grafana#10107]
Please include this information:
- What Grafana version are you using?
  __4.6.0__

- What datasource are you using?
  __InfluxDB__

- What OS are you running grafana on?
  __Linux__

- What did you do?
  __Displayed a stacked graph over a time period where the set of lines changes. Also, `fill(null)` is used in the query, and in the "Display" tab we're using "Null value = null". Issue #705 mentions a workaround for this problem but for other reasons we cannot change the "Null value" option or `fill(null)`.__

- What was the expected result?
  __The stacked lines should not be overlayed.__

- What happened instead?
  __The staked lines are overlayed.__
  
Screenshot 1 shows the incorrect case (where lines are overlayed). This seems to be caused by the new data (new lines) to the right of the graph.

Screenshot 2 shows how the overlay disappears when we zoom in and the set of data to the right goes out of view.

__Update__: It looks like I cannot upload screenshots from here. I can send them over email though.

**Comment by torkelo** [comment]
Sure you can, just drag and drop the images. Please include the raw response from you query. Use query inspector to catch the query grafana send and the response. Maybe there are some nulls

**Comment by mupdt982** [comment]
Our network blocks uploads to github, it seems. Am trying now to include images in the email.

There is missing data in those gaps. We’re not publishing null values, if that’s what you mean. Unfortunately I cannot send over the response as it contains sensitive data.

**Comment by torkelo** [comment]
change fill function to fill(0)

**Comment by mupdt982** [comment]
Just to clarify, `fill(0)` draws lines where we would like to see actual missing data, so this is not a solution for us.

The bug we are reporting is that the lines are overlapping in the stacked plot, which they should never do in a stacked plot. So is definitely bug and the `fill(0)` workaround unfortunately doesn't apply to our use case.

**Comment by torkelo** [comment]
for stacked series Grafana currently requires there to be data for every series.

**Comment by torkelo** [comment]
Oh, forgot to add there are already other reported issues & feature requests to better support stacking of nulls.
