### ISSUE TITLE
When are you releasing version 4.7.0?

### ISSUE THREAD

**Issue by queeno** [grafana/grafana#10108]
Hi there.

Just a quick question. When are you planning to release version 4.7.0?

We can't wait for issue #1789 to be finally released.

Thanks!

**Comment by daniellee** [comment]
We're not sure exactly. The Grafana team is currrently working hard on 5.0 alpha and we do not want to slow down right now to release 4.7.0. Maybe in January after the 5.0 alpha and beta but we're not promising anything :wink:

**Comment by queeno** [comment]
Thanks for getting back to me :-) I am looking forward to both releases!

In the meanwhile, if you could release a 4.7.0 'alpha' (especially the docker container), it would be really super!

Thanks for all the hard work and the amazing project 👍

**Comment by daniellee** [comment]
Nightly Builds are available on docker hub if you want to use the latest in master.

**Comment by queeno** [comment]
Right, thanks very much @daniellee
