### ISSUE TITLE
[Support] Get userId as orgId ?

### ISSUE THREAD

**Issue by SlodeSoft** [grafana/grafana#10104]
Hello, 

I need to get the current userId or login or name i don't know, in my URL as my orgid.

![image](https://user-images.githubusercontent.com/8158963/33666369-13a85450-da9a-11e7-9d16-bfc649675f3d.png)

Is it possible ?

Thanks

**Comment by bergquist** [comment]
Not sure what you're trying to do.
But the username can be found in a cookie name `grafana_user`
