### ISSUE TITLE
Series order in master build issue

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10105]
I am running grafana off the latest master branch, and sometimes the series are not ordered the same as they were returned from InfluxDB.  See:

![image](https://user-images.githubusercontent.com/705951/33673399-e6034c5e-daac-11e7-8799-57f8b8aadcdf.png)

note that influx returned the items in a reasonable order, and grafana is displaying them in a funky order.

Strangly, when you toggle a single value, the order changes again (without making a network request).  Each time you click the order changes again:

![image](https://user-images.githubusercontent.com/705951/33673468-126be47c-daad-11e7-9bf4-fc96c331a175.png)

The strangest part is that this is not consistent.  I have a dashboard with a template variable to a unique ID.  For some IDs, it displays fine -- for others it does not.   The same IDs work or don't consistently though.

Here is the query config:

![image](https://user-images.githubusercontent.com/705951/33673882-4cb084f2-daae-11e7-8ffa-fc74982a7979.png)

**Comment by ryantxu** [comment]
This looks related to #351, but the influx query is returning results in the correct order

**Comment by bergquist** [comment]
Might be related to https://github.com/grafana/grafana/issues/9538

Could you please share the json for the panel?

**Comment by ryantxu** [comment]
Here is the panel JSON:
```
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "$source",
  "fill": 1,
  "id": 4,
  "legend": {
    "avg": true,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [
    {
      "alias": "Site",
      "stack": false
    }
  ],
  "spaceLength": 10,
  "span": 12,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "alias": "$tag_engine",
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "engine"
          ],
          "type": "tag"
        }
      ],
      "measurement": "power",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "kw"
            ],
            "type": "field"
          }
        ]
      ],
      "tags": [
        {
          "key": "tid",
          "operator": "=",
          "value": "$tid"
        }
      ]
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Power",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "kwatt",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}
```

**Comment by ilgizar** [comment]
Observation showed that mixing is not random, but is of order. Only three elements cycle through the places that are at positions 1, 2 and (count >> 1 + 1) [next to the central element].
