### ISSUE TITLE
Github allowed organizations authentication

### ISSUE THREAD

**Issue by adiletmaratov** [grafana/grafana#10111]
Third-party application access policy of Github is "Access restricted" by default for a couple of years now. 
I took config from defaults.ini config file and tried to setup grafana to allow authenticate users from specific organizations only. "Access restricted" policy does not allow third party applications to view organization specific information when authenticating. Instead, there is a different endpoint to get user's organizations membership: "https://api.github.com/users/<username>/orgs", but grafana's [auth.github] api_url is set to "https://api.github.com/user" and grafana tries to get a list of organizations by just appending "/orgs" to the end of api_url, which shows only organizations with "Access allowed" application access policy.

**What was the expected result?**
I expect grafana to take `organizations_url` field from user data response from github and make another request to get organizations that the user is member of. 

**What happened instead?**
Grafana just concatenates "/orgs" to the `api_url` config and makes a request, which is useless in this case.

**Comment by bergquist** [comment]
Closed by #10112
