### ISSUE TITLE
Forward Slash "/" not searchable for Elastiscsearch query

### ISSUE THREAD

**Issue by nkondratyk** [grafana/grafana#10114]
Hi

In variable I use URL with slashes and grafana automatically escapes all slashes and elastic doesn't return any result.
Grafana version - v4.6.0

If I specify without variable:
![image](https://user-images.githubusercontent.com/34338539/33711666-7439892a-db4d-11e7-9e0b-0413ac2d71d1.png)

If I specify variable:
![image](https://user-images.githubusercontent.com/34338539/33711710-98c1b5ec-db4d-11e7-9c29-17d9bd4b8e86.png)

If I escape slashes manually:
![image](https://user-images.githubusercontent.com/34338539/33711746-ba917126-db4d-11e7-92f4-245e44b4500e.png)

Variable settings:
![image](https://user-images.githubusercontent.com/34338539/33711769-ce1172aa-db4d-11e7-9637-2179a2480d00.png)

Please check it

**Comment by nkondratyk** [comment]
Hi

Did you have a chance to check it?

**Comment by torkelo** [comment]
strange it works when I test it:
![image](https://user-images.githubusercontent.com/10999/34108857-025104ce-e402-11e7-9c57-58dccb3d80c2.png)

**Comment by torkelo** [comment]
closing this due to lack of update
