### ISSUE TITLE
Diff series question

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#10117]
Is there a way to subtract a series value from a hard coded value e.g.

diffSeries(2, #A)

We have measured that proxy is adding up some time while going out to internet and hitting the web pages... want to know --- how can i subtract the proxy added time....  until I figure out to put this on internet facing servers...

**Comment by bergquist** [comment]
Please ask questions on the community site. We reserve github for bugs/feature requests.

https://community.grafana.com/
