### ISSUE TITLE
Grafana 5.0 - docs for Dashboard Folder page

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10118]
There is a link in the Call To Action (which is shown when there are no dashboards in the folder) to a docs page for more info on dashboard folders.

Those docs need to be written for the alpha1 release.

**Comment by daniellee** [comment]
First draft written and is in the 5.0 docs branch: https://github.com/grafana/grafana/blob/docs_v5.0/docs/sources/reference/dashboard_folders.md
