### ISSUE TITLE
Millisecond precision not working with PostgreSQL

### ISSUE THREAD

**Issue by fredrikstormo** [grafana/grafana#10116]
We are using TimescaleDB (PostgreSQL) to store data with millisecond precision. The data type is ordinary timestamps without time zone (e.g "2017-12-07 13:10:24.250").
The code for plotting works but the points are only plotted per second and not per millisecond.

```
SELECT
  $__time(time_column),
  value1
FROM
  metric_table
WHERE
  $__timeFilter(time_column)

```
A similar issue was closed #9851, but the problem persists.
We are using grafana v4.6.2 (commit: 8db5f08) and Postgres v 9.6.6

**Comment by svenklemm** [comment]
The fix is not in your version of grafana. You need to use nightly build to get the fix.
