### ISSUE TITLE
"Back to Dashboard" Button Missing

### ISSUE THREAD

**Issue by bulletfactory** [grafana/grafana#10123]
Reviewing changes in the v5 develop branch - If you edit or view a panel,  there's no clear way to get back to the dashboard (I know you can hit esc to return to the dashboard). 

I think we need to be more explicit - It doesn't have to be a large button, perhaps a simple "back" icon like on a browser could work, but I feel like we need something there. Open to discussing.
 
<img width="1724" alt="screenshot 2017-12-07 14 37 23" src="https://user-images.githubusercontent.com/1950595/33735366-14aa19c4-db5d-11e7-9acc-35e3e29deea7.png">

**Comment by torkelo** [comment]
where do think it should go? Having it in the nav always felt clunky to me. And the edit mode has a close action already (that can be made more obvious and bigger). but did not think about the full screen view mode, for this mode we really need the back to dashbord.

**Comment by torkelo** [comment]
done 
![image](https://user-images.githubusercontent.com/10999/33884834-8f7abd7e-df41-11e7-9c12-539525a4a2c9.png)
