### ISSUE TITLE
[Bug] Custom aggregation sizes no longer allowed for Elasticsearch

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#10124]
Grafana version: 4.6.2
Datasource: Elasticsearch

In a recent refactoring (840099bec0b58f464f3605c30c2f072a96f4d994) the "Size" option for ES aggregations was changed from "metric-segment-model" to "gf-form-dropdown", but the "allow-custom" option was left out.

The result is that your only size options are the handful provided as defaults. This is a regression from how it functioned previously. 

As a separate issue, this also makes it more noticeable that "No Limit" should be changed. Since '0' is no longer a valid option in ES, I think the "No Limit" option should be transparent about not actually being limitless.

**Comment by Ultraseamus** [comment]
The fix for this seems like it should be pretty straight-forward. My change fixes the issue, but I end up with a problem where the typeahead dropdown only appears the first time you click it after the page renders if you've entered a custom value that was not part of the original option list. Every time after that the "typeahead dropdown-menu" element fails to set "display: none" to "display: block".

The new issue is less restrictive than the original, but I'm having a hard time figuring out what is going wrong with it.

**Comment by torkelo** [comment]
need to add allow-custom="true" as parameter here, https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/partials/bucket_agg.html#L99
