### ISSUE TITLE
Graph: click anywhere on a graph line to toggle on/off all other graph lines

### ISSUE THREAD

**Issue by FlorinAndrei** [grafana/grafana#1013]
Hover the mouse over one graph line until the box with the label and value appears over it:

![cpu](https://cloud.githubusercontent.com/assets/901867/4910696/d4a05694-6482-11e4-854a-8edd2cbee656.png)

At this point, while the box is still being displayed, it would be great if I could click the left button to make all other graph lines disappear, so that I can see only this one line. Then click again to make everything re-appear.

Something similar could be accomplished with legends (I believe it's CTRL-click), but the legends are usually disabled on such a graph with so many metrics.

Even cooler would be if all other lines would be toggled 90%/0% transparent instead of being toggled  completely off/on.

**Comment by torkelo** [comment]
something like this could potentially be implemented in the future, but just clicking on the graph will be be reserved to for a menu/popup to add annotation/graph comment in the future
