### ISSUE TITLE
influxdb sources: drill-down by distinct next node name

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#1014]
The drill-down interface that comes by default with the graphite data sources is familiar and useful. I'd like to have this as a feature of the influxdb data sources as well. Even though the influxdb data sources don't have the same layout, it wouldn't be too difficult to allow for a drill-down style interface by simply filtering on distinct node names that match the current series prefix and partial node name. If there is a way to do this already that has the same drill-down effect, I haven't found it in the stock grafana+influxdb configuration. I'd prefer not to have to go through an API emulation layer to get it.

A workable approach might be:
1) Do a partial match against all series names, as they are currently shown in the options drop-down.
2) For each matching series name, map a truncated name to a set of top-level options, truncating at the next word boundary by regex. (make the node-boundary regex configurable?)
3) Put these options at the top of the selection list, alphabetically, with a divider and then the rest of the fully-qualified series names.

Selecting one of these prefixes should automatically repeat the process at the next level.

Partial matches might need to be represented differently in the selection list than matches of a full series name when there are naming overlaps with fully-qualified series names.

**Comment by torkelo** [comment]
closing as this issue relates to influxdb 0.8 which is no longer developed
