### ISSUE TITLE
error="open /grafana-server.pid: permission denied"

### ISSUE THREAD

**Issue by FlorinAndrei** [grafana/grafana#10143]
Ubuntu 16.04

Just updated to grafana 4.6.2

When attempting to start the service I get the pid file error no matter what I do.

Used to work great before.

**Comment by FlorinAndrei** [comment]
Started working after I added this line to `/etc/default/grafana-server`:

```
PID_FILE_DIR=/run/grafana
```

**Comment by torkelo** [comment]
yea, the pid file dir is needed so systemd can set the right permission
