### ISSUE TITLE
[Bug] Can't create alert rule: "Evaluator has invalid parameter"

### ISSUE THREAD

**Issue by Somewater** [grafana/grafana#10147]
- What Grafana version are you using
 Grafana v4.4.3 (commit: 54c79c5) 
_From latest version of [docker-grafana-graphite](https://github.com/kamon-io/docker-grafana-graphite) docker image_
- What datasource are you using?
Graphite (also from image above)
- What OS are you running grafana on?
Ubuntu 17.04
- What did you do?
I sent some test counter metrics, create graph for it (with success) and try to create alert rule for it.
- What was the expected result?
Alert rule created after clicking on "Save dashboard" button
- What happened instead?
I receive error when click on "Save dashboard" button (red pop-up): "Problem! Invalid alert data. Cannot save dashboard". And I see something like this in logs:
```
t=2017-12-10T10:25:59+0000 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Failed to extract alert.Reason: Evaluator has invalid parameter   PanelId: 1  DashboardId: 5"
```

**Comment by bergquist** [comment]
Have you configured the Condition threshold?
![image](https://user-images.githubusercontent.com/618863/33820800-645b9712-de51-11e7-91a8-f8c3367e72c6.png)

**Comment by Somewater** [comment]
Oh, my bad. I really tried to test it without value

**Comment by AaronBarge** [comment]
I know this is a few years old but I'm running Grafana v7.0.5. had two alerts I was testing out. I got sidetracked on the first one not setting the **IS ABOVE** and then went to go test the second alert in a new panel filling out the query correclty, and got hit by the alert error in the first panel. 

`Alert validation error: error in condition 0: Evaluator 'IS ABOVE' is missing the threshold parameter PanelId: 30 DashboardId: 100`
The error message works but a possible improvement would be to add the pannel name, so I know where to go look.

**Comment by gurkanguney96** [comment]
Hi all. Firstly, if you can define alert from alert section, I think you can solve this problem.
