### ISSUE TITLE
Add supprort for HUF/ft currency

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#10140]
I would like to create custom currency to the Label, as 'HUF' or 'Ft'. It has a config file on the server? Or is it a feature request? Thank you!

**Comment by bergquist** [comment]
We will not support custom currencies from config files. If you want to add new currencies to Grafana I suggest you create a PR. https://github.com/grafana/grafana/pull/9434

**Comment by sanchomuzax** [comment]
Thank you!
