### ISSUE TITLE
Allow to specify Max Value for Y  for SingleStat Sparkline

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#10148]
- What Grafana version are you using? 4.6.1

- What did you do?
Create SingleStat Panel for CPU utilization with Sparkline

- What was the expected result?
Sparkline looks simiar whenever the cpu usage is floating at 100% or 10%  

- What happened instead?
As I understand what is expected

The Graph Panel allows to specify MaxValue for Y column so I can normalize graphs like CPU usage so 1% always looks low and 100% always looks high whenever it is consistent or if there are spikes. 

It would be great to have similar option for SingleStat too

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
