### ISSUE TITLE
Drag and drop does not work in firefox (at all), 4.6.2

### ISSUE THREAD

**Issue by rathboma** [grafana/grafana#10157]
Using Firefox Developer Edition, version 58.

Drag and drop behavior doesn't even show up. Error in the console:

`TypeError: this.drop is null`

Here's a gif of me trying to drag and drop to no avail

https://cl.ly/3w3W1m1W1Z0X

**Comment by daniellee** [comment]
I just tested on the play.grafana.org site with version 58.0b11 and it works for me:

![firefoxdevedition](https://user-images.githubusercontent.com/434655/33992600-8ffd028c-e0d3-11e7-8938-037703fc9321.gif)

Are you sure the dashboard is editable?

**Comment by torkelo** [comment]
Cannot replicate either, but anyway fixed in master / v5 as well with  new grid system
