### ISSUE TITLE
String data in the Graph plot with InfluxDB

### ISSUE THREAD

**Issue by vortekc** [grafana/grafana#10155]
How can i get non-integer value on my serial graph plot? For example i have this query:
SELECT last("counter") AS "counter",
last("caounter2") AS "counter2",
last("counterName"),
last("counterName2") FROM "autogen"."Counters" WHERE $timeFilter GROUP BY time($interval) fill(previous)
Where counterNames is a string fields with counters IDs. And i need to see their IDs to know what exactly IDs was in this moment of time. But i got only blank spaces as a value for this two fields. 

Can i get this query work for me?

**Comment by torkelo** [comment]
you need to use the table panel to show string data.
