### ISSUE TITLE
threshold "fuzzy"-ness

### ISSUE THREAD

**Issue by kaos** [grafana/grafana#1015]
Hi Torkel,

We'd like to be able to add a threshold to the threshold, in a way. There should be at least X points in sequence beyond the threshold level for it to be considered crossed. Currently, this setting won't make much sense (in grafana, at least) until that time that there are som additional visualizations applied based on crossed threshold levels.

I'm willing to implement it, but I'm opening this ticket for discussion, so it's done in a way that's acceptable to you.

**Comment by torkelo** [comment]
closing due to lack of interest in this feature, might be solved in some capacity in the future by the Grafana alerting
