### ISSUE TITLE
Allow to display annotations based on Prometheus series value

### ISSUE THREAD

**Issue by trnl** [grafana/grafana#10159]
**- What Grafana version are you using?**
4.6.2

**- What datasource are you using?**
Prometheus 2.0

**- What did you do?**
Display annotations on the container start/stop times from kube-state-metrics

Prometheus Datasource in Grafana supports two ways to query annotations.

- A regular metric query
- A Prometheus query for pending and firing alerts (for details see Inspecting alerts during runtime)

But both of them have step and it means that line will be shown only if value equals 1 or more. 

At the same time metric can be a gauge with timestamp value and it can be directly displayed on the panel. One example of that is `kube_pod_start_time` from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/pod-metrics.md). 

```bash
> http -b "http://prometheus2.tools/api/v1/query_range?query=ALERTS{alertname=%22DeadMansSwitch%22}&start=1512936263&end=1513022663&step=10h"
{
    "data": {
        "result": [
            {
                "metric": {
                    "__name__": "ALERTS",
                    "alertname": "DeadMansSwitch",
                    "alertstate": "firing",
                    "severity": "debug"
                },
                "values": [
                    [
                        1512936263,
                        "1"
                    ],
                    [
                        1512972263,
                        "1"
                    ],
                    [
                        1513008263,
                        "1"
                    ]
                ]
            }
        ],
        "resultType": "matrix"
    },
    "status": "success"
}
```

**Comment by torkelo** [comment]
can you describe more what you want Grafana to do that you cant now?

**Comment by trnl** [comment]
@torkelo, sure. 

Right now annotations are displayed based on the existence of the series. So if we make a query q<sub>0</sub> at the time t<sub>0</sub> and result is not `null` - annotation will be displayed on the panel around t<sub>0</sub>.

**In this case, the value of the series is not significant.** 
We also have to define 'step' which will lead to annotation duplication on the chart.

![image](https://user-images.githubusercontent.com/429240/34364238-2932bd02-ea84-11e7-9b9b-a2f75bb5b09e.png)

At the same time, we can have series which has the timestamp as a value, like `kube_pod_start_time` I highlighted above. I want to be able query this metric and use the **value** of the metric to display vertical line on the chart. Now it's not possible.

**Comment by trnl** [comment]
@torkelo, I wonder if it's more clear now?

**Comment by mtanda** [comment]
Just idea to display the annotation without modifying Grafana.
Little hacky but it may works.

```
time() == BOOL kube_pod_start_time
```

or

```
abs(time() - kube_pod_start_time) < BOOL 60 # 60 or more enough big number
```

**Comment by trnl** [comment]
@mtanda, thank you for your suggestion, but I'm not sure it's gonna work. To calculate the annotations grafana make `query_range` with particular `step`. So you can force to use `step=1s`, but it will not be the most efficient way. Also, due the nature of Prometheus, metric with value `X` can only be available at `X+t` because Prometheus scraped it at that time. So if you'll evaluate at time 'X', you'll get no datapoints.

**Comment by trnl** [comment]
I believe people are using something like the following:
```
sum(changes(prometheus_config_last_reload_success_timestamp_seconds[10m])) by (instance)
```

Can be much simpler =)

**Comment by danieldabate** [comment]
We are having the same use case as @trnl. 

@mtanda workaround works, thank you! But having to do it this way seems inefficient and unnatural.

Would be great to see this feature implemented in a future version.
