### ISSUE TITLE
[Bug] CloudWatch no longer display metrics' default alias

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#10151]
- What Grafana version are you using?

4.6.2

- What datasource are you using?

CloudWatch

- What OS are you running grafana on?

Linux Ubuntu 14.04

- What did you do?

Upgraded from 4.2.1

- What was the expected result?

Dashboard being seamlessly migrated.

- What happened instead?

CloudWatch based dashboards no longer display the default alias if no alias is specified.

![image](https://user-images.githubusercontent.com/1764725/33830999-aac6082a-de76-11e7-85d8-0c43456059d8.png)

Looking at the json, I see that an empty alias is present:

```
        "targets": [
            {
              "alias": "",
              "application": {
                "filter": ""
              },
```

 
I think this issue has already been fixed in master, see #9752 . But it has not been backported into the v4.6.x branch. I think it is annoying enough to worth a backport.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9752
Will be included in 4.6.3
