### ISSUE TITLE
Console errors for panels with CloudWatch data source

### ISSUE THREAD

**Issue by bwhaley** [grafana/grafana#10174]
- What Grafana version are you using?
 Grafana v4.7.0-pre1 (commit: a020868)

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Linux (Docker)

- What did you do?
Open the metrics tab for a panel with CloudWatch as a data source

- What was the expected result?
Should be able to edit metrics, stats, dimensions, etc

- What happened instead?
Inability to make any edits and errors in the console. See attached screenshot with errors.  

Possibly introduced in 27e486d678f0f66b302e7dd4e9d6930435b95145?

<img width="1433" alt="cloudwatch_console_errors" src="https://user-images.githubusercontent.com/503816/33912247-f547624e-df49-11e7-8fd7-d83aae060ac4.png">

**Comment by torkelo** [comment]
thanks for reporting this, fixed in latest build.
