### ISSUE TITLE
Feature request: require HTTPS in X-Forwarded-Proto

### ISSUE THREAD

**Issue by haizaar** [grafana/grafana#10175]
Good day,

I'm running the latest Grafana on k8s in GKE using stable helm chart. I've configured ingress with kube-lego and have Grafana accessible both from HTTP and HTTPS. 

However I want Grafana to be accessible over HTTPS only and redirect to HTTPS version of itself if accessed through plain HTTP. I know it can be done through reverse proxy, but:

* Google load balancer does not support this feature
* Running dedicated nginx as a separate deployment has its issues [1]
* Finally I thought about running nginx as a sidecar container in Grafana pod, but that would mean I need to fork helm chart

Therefore I'm asking it it would be acceptable for Grafana to support `redirect_to_https` option that will make Grafana server to `return 301 https://$http_host/request_url`. I vouching for this because currently we got to a very good shape where one can deploy Grafana + Kube-lego and have valid HTTPS service with just a couple of keystrokes, finally achieving the vision of simplicity that this whole container echosystem promised since long ago. However there is no out-of-the-box way to enforce security (HTTPS), which still requires DevOps engineering and understanding of internals.

I may be able to implement this feature myself (probably appreciating some guidance), but I would like to know first if maintainers will consider accepting such feature a pull request.

[1]
nginx will resolve upstream DNS name only once. I.e. if you simply point NGINX to k8s service DNS name, and ClusterIP changes later on, it will break until you restart nginx. To do it properly one needs configure nginx resolver and write a custom script that bootstraps the resolver with system configuration (because nginx resolver does not read /etc/resolv.conf and /etc/nsswitch.conf). 
It's doable, but again, requires too much hacking for something that IMHO should be simple.

**Comment by icco** [comment]
I am running Grafana in Docker on Amazon ECS and also would like this, for the same reasons. An ECS service usually sits behind an AWS application load balancer which can send traffic over multiple ports to the same docker container, but will not do the redirect for you. Amazon assumes the application will use `X-Forwarded-Proto` to redirect to https if they want to.

**Comment by walterdolce** [comment]
This has been kind of been requested before already but rejected (#2661 and #1620). 

I wonder whether this could be both achieved via a couple of "naive" methods such as triggering a redirect from HTTP to HTTPS in the app via Javascript and/or to do it when the request is received by Grafana itself and `https` is detected within the URI received?

I am not aware of Grafana's internals so this may not be possible but maintainers/collaborators may be able to shed some light on this.

**Comment by haizaar** [comment]
@walterdolce, I think the proposals you are referring to are a bit different. They involve grafana itself listening on HTTPS. My case is when grafana listens on HTTP and sits behind SSL-terminating proxy.

You idea sounds interesting, albeit hacky :) May it can even possible to do that through plugin - the downside will be that authentication will not be mandated to go through HTTPS.

**Comment by walterdolce** [comment]
@haizaar it's hacky indeed. Advice not be taken into consideration :p
