### ISSUE TITLE
Grafana 5.0 Search input box

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10188]
We have a lot of pages with search/filter box
![image](https://user-images.githubusercontent.com/10999/33937894-8347837e-e005-11e7-94cd-b2c9423aeb67.png)

Maybe we can add new input box style like this? 
![image](https://user-images.githubusercontent.com/10999/33937877-754c178a-e005-11e7-9c83-a60928b1bf5d.png)

**Comment by jschill** [comment]
Added to "Manage Dashboards". Should be added to all similar search inputs.
