### ISSUE TITLE
Error loading data using absolute time

### ISSUE THREAD

**Issue by michael-grafton** [grafana/grafana#10189]
- What Grafana version are you using?
Using v4.5.2
- What datasource are you using?
Graphite
- What OS are you running grafana on?
macOS Sierra v10.12.6
- What did you do?
Using absolute time (i.e. Date & Time to Date & Time) in order to view metrics
- What was the expected result?
Expected data to view for that time period, there is definitely the data there, as when using relative time (i.e. 45 days from now) the data still shows. 
- What happened instead?
Get the following error message
"Internal Server Error" with reponse:

`"<body style="background-color: #666666; color: black;"> <center> <h2 style='font-family: "Arial"'> <p>Graphite encountered an unexpected error while handling your request.</p> <p>Please contact your site administrator if the problem persists.</p> </h2> <br/> <div style="width: 50%; text-align: center; font-family: monospace; background-color: black; font-weight: bold; color: #ff4422;"> </div> <div style="width: 70%; text-align: left; background-color: black; color: #44ff22; border: thin solid gray;"> <pre> Traceback (most recent call last): File &quot;/usr/lib/python2.7/dist-packages/django/core/handlers/base.py&quot;, line 112, in get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/views.py&quot;, line 110, in renderView seriesList = evaluateTarget(requestContext, target) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 10, in evaluateTarget result = evaluateTokens(requestContext, tokens) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens return evaluateTokens(requestContext, tokens.expression) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 28, in evaluateTokens args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args] File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens return evaluateTokens(requestContext, tokens.expression) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 28, in evaluateTokens args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args] File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens return evaluateTokens(requestContext, tokens.expression) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py&quot;, line 24, in evaluateTokens return fetchData(requestContext, tokens.pathExpression) File &quot;/usr/lib/python2.7/dist-packages/graphite/render/datalib.py&quot;, line 229, in fetchData dbResults = dbFile.fetch( timestamp(startTime), timestamp(endTime) ) File &quot;/usr/lib/python2.7/dist-packages/graphite/remote_storage.py&quot;, line 126, in fetch assert len(seriesList) == 1, &quot;Invalid result: seriesList=%s&quot; % str(seriesList) AssertionError: Invalid result: seriesList=[] </pre> </div> </center> "`

**Comment by torkelo** [comment]
looks like a problem with graphite. Not sure what i can be, we have no other reports with similar errors. 

are you using a graphite remote store?
