### ISSUE TITLE
Improve connection to datasource lost indicator

### ISSUE THREAD

**Issue by eloo** [grafana/grafana#10182]
Hi,
i'm facing an issue that sometimes the connection from my grafana to my datasource (prometheus) is lost due to bad connection or something like that. 
My problem with that is when the connection is lost no new data will be shown and only the small spinning wheel is showing up. But this wheel can easily overseen which is quit bad.
So it would be great if a more visible indication for a lost connection will be shown up. Maybe an overlay or the that the graph is shown real empty data.

How do you think about a feature like that?
Thanks

**Comment by torkelo** [comment]
Can you open chrome dev tools when this happens? If the query is just slow and not responding it's not much grafana can do. If your data source is returning an error of some kind that will show in the graph

**Comment by eloo** [comment]
In my case the query wasn't slow. The problem was that the LAN-cable was disconnected which means prometheus wasn't reachable.
And if it would be slow can we add a timeout? because the spinning wheel was stuck multiple hours

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
