### ISSUE TITLE
Issues with annotation tooltip

### ISSUE THREAD

**Issue by wbernest** [grafana/grafana#10196]
Grafana version - 4.6.2
Datasource - openHistorian
OS - Windows 10
Browser - Chrome

I was setting up the annotations for my datasource and I noticed I got an angular error when ever I hovered over the annotation.
![beforeview](https://user-images.githubusercontent.com/11617314/33944244-94ab57ce-dfe9-11e7-865d-d0f0339239d7.PNG)

I clicked the error link and angular said to try using track by $index for the ng-repeat="tag in tags".  So I inserted this into the js files.  Now the annotations looked like this.

![aftertrackbyindex](https://user-images.githubusercontent.com/11617314/33944319-ced343a8-dfe9-11e7-8949-003011f853b3.PNG)

I decided to try splitting the tag list on commas since that is what your documents say to do and the results is this.

![aftersplit](https://user-images.githubusercontent.com/11617314/33944361-ec4334a2-dfe9-11e7-985b-ae9df029e278.PNG)

The typescript file that needs to be looked at is grafana\public\app\features\annotations.ts. (I inserted directly into the compiled/minimized js and they worked)

Before my changes
![before](https://user-images.githubusercontent.com/11617314/33944420-23f8e5cc-dfea-11e7-9dbc-dc10de4f761f.PNG)

After my changes
![after](https://user-images.githubusercontent.com/11617314/33944429-2b90a52c-dfea-11e7-9055-a5745b64dca1.PNG)

**Comment by torkelo** [comment]
what data source are you using for the tags and what is the response from your annotations query?

**Comment by wbernest** [comment]
I am using the openHistorian datasource that we designed.  It is available under the listed data sources on your website.  The response from the query, atleast the only portion that was causing issues which were the tags, was simple a comma separated string.

**Comment by bergquist** [comment]
not sure this is the best way of solving this. I think the annotation code should give a hint about the tags not  containing correct data is better.

**Comment by torkelo** [comment]
Closing this as think it's fixed or not impacting many
