### ISSUE TITLE
Add support for alerting - maybe join forces with tattle?

### ISSUE THREAD

**Issue by ronnyle** [grafana/grafana#102]
https://github.com/wayfair/Graphite-Tattle
You should join forces and take over the world! :)

Seriously - would be great if monitoring and alerting-configuration could be done with the same tool.

**Comment by dworld** [comment]
+1

**Comment by amorphic** [comment]
:+1:

There exists a real need for a quality threshold/alerting mechanism for Graphite.

Grafana has made it easy for users to create beautiful and functional dashboards which really unlock the value inside Graphite metrics. I've noticed that as users become more familiar with Grafana, the next question they ask is 'can I set thresholds and receive alerts when those thresholds are breached'? 

Giving users the ability to configure thresholds/alerting via the same interface that they are already using for analysis/dashboarding (Grafana) would be utterly perfect.

**Comment by euprogramador** [comment]
Hello, my name is Carlos and I'm using grafana as dashboard, but would like to use grafana also for monitoring, however I did not find this functionality, I saw that the grafana is to set thresholds, thought to create software that runs a query to grafana and checks the limits and then immediately is collecting from time to time and validating the limits, and generating a notification to alert any other software. what do you think?

**Comment by djnym** [comment]
Just curious how this is going?  We are currently looking to replace a legacy home grown alerting system, and if possible I'd like us to align with the current grafana roadmap, but I've not found any other open issues.  Is alerting still coming to grafana this year, if so do you have a short list of systems you might try to integrate with, or a sketch of how?

**Comment by Dieterbe** [comment]
Hey folks. Good news! I'm joining the team working on grafana and will work on alerting within Grafana.

**Comment by toni-moreno** [comment]
Wow !!! very good news !!

How do you plan to design this new feature ? As a batch process perhaps ? Linked to the dashboard thresholds or it will have a new editor only for alerting ?  I would like to help as much as I can.

**Comment by cemo** [comment]
@Dieterbe Good luck mate. 

https://vimeo.com/121497776

**Comment by torkelo** [comment]
@Dieterbe yay :)

**Comment by djnym** [comment]
Is this the best place to keep up to date on functionality being added to grafana?  Is there a developer mailing list or something?  Just curious.

**Comment by torkelo** [comment]
@djnym there is a mailing list (user + dev at the moment), and chat on #freenode , but otherwise for feature discussions github is a good place.

http://grafana.org/community/

**Comment by damajor** [comment]
From my point of view alerting should be handled **only** using annotations.

Graphs and any viewing widgets should support annotations filtering, to focus on the one related to the metrics displayed on the widget. They should also support operator alerting with sound and/or visual effect.

This way you let other dedicated components do the specific job like thresholding, trending, correlating events etc...

In few words, alerting in Grafana should only focus on alerting the operator using it.

**Comment by Dieterbe** [comment]
@toni-moreno still a lot to be decided (like how actual check execution will happen, and by what) but in grafana fashion we want to make sure the user experience is really smooth and nicely integrated into the existing UI

**Comment by djnym** [comment]
I really like the interactivity aspect shown in the demonstration video.  Being able to construct a complicated expression with graphite, then trigger based on outliers is ideal.  For instance, say I want to compare a traffic rate to the same rate last week, determine the difference then check if that difference is greater than a threshold.  I can use timeShift and diffSeries, then determine a max or min and trigger if either is above a set threshold.   I can easily and interactively create a graph, if I could then just add a threshold and specify where it goes when it triggers that would be awesome!

**Comment by MichaelLogutov** [comment]
I wholly agree - getting the power of UI to construct and immediately visually check the results of complex expressions on graph in Grafana is a key to good event monitoring solution.

**Comment by minimedj** [comment]
+1 for alerting rules!

**Comment by pavleec** [comment]
+1

**Comment by Zert** [comment]
+1

**Comment by pabloa** [comment]
+1

**Comment by jtsoi** [comment]
+1

**Comment by whisk3y** [comment]
+1

**Comment by johann8384** [comment]
This has kind of been said already. If I were in charge I'd prefer not to have Grafana doing alerting and notifications itself, but being able to add some metadata to a panel like "set a warning here, a critical here" and storing those with the config in Elasticsearch would allow for other tools to read that and self-configure their own rules. I could see folks using that within their own environment to feed Puppet to write out configurations for Nagios or Sensu. Of course, replace that with your CM and Monitoring tools of choice.

I suspect if it would be stored that someone would integrate it to something, and eventually all the things.

**Comment by pabloa** [comment]
Yes. I am working in a prototype under the parameters enumerated.
Grafana must not do monitoring. Monitoring depends of size and cluster
topology. It could be complex one tool makes everybody happy.

**Comment by minimedj** [comment]
As an end user I would want to have notifications and warnings setup via graphana. I don't know how it should be implemented, but I believe it would be very handy to have it all in one place.

It it will be like @johann8384 suggested, it will be just fine for me.

**Comment by damajor** [comment]
@johann8384 That is exactly what I proposed a bit upper in this thread.

Grafana should never an alerting system, but should focus on notifying the operator. I think that alerting is misused here.

The notifications may come from multiple channels and based on some triggers or filters they should raise a visual or sound alarm.

**Comment by pabloa** [comment]
Hello

I wrote a python module called "grafana alerts" to report email alerts based on grafana boards.

Administration is done using grafana UI. Because there is not specific UI support to this project, I am using a text panel to set alert parameters. Example:

![grafana_alert_dashboard_1 0 x](https://cloud.githubusercontent.com/assets/605963/8141347/6b52cc36-111a-11e5-84ab-d724bc90f025.png)

Dashboards must be tagged with a "monitored" tag:

![screenshot from 2015-06-12 01 20 13](https://cloud.githubusercontent.com/assets/605963/8141338/5cbe7986-111a-11e5-8a9e-d743c777858f.png)

Therefore you can have dashboards generating alerts mixed with user dashboards.

The dashboard in the image would trigger an email like:

![screenshot from 2015-06-12 15 52 20](https://cloud.githubusercontent.com/assets/605963/8141406/25f0951e-111b-11e5-9539-5b218df2c322.png)

If you observe the alert table on the right, kafka host is in warning state. This is what is reported in the email.

"Gragana Alert" project is work in progress. Right now version 1.0.0.dev4 is available. To download go to: https://pypi.python.org/pypi/grafana_alerts

Follow the instructions.

Feedback is welcome. :)

**Comment by Dieterbe** [comment]
interesting approach @pabloa !

anyway people, i created a new ticket to discuss the new alerting system for grafana. please read through #2209 (i read through this ticket and I think i adressed everything that was mentioned here)
future discussion/feedback can be done there,
thanks.

**Comment by torkelo** [comment]
closed in favor of #2209
