### ISSUE TITLE
Supporte use of multiple OAuth provider 

### ISSUE THREAD

**Issue by maxenced** [grafana/grafana#10209]
When defining multiple generic oauth provider ([auth.generic_oauth])  only the last one is used, even with different Name. 

Would it be possible to have multiple generic_oauth providers, just like it works when enabling 2 differents auth providers.

Maxence

**Comment by bergquist** [comment]
That's currently not possible. This will have to wait for https://github.com/grafana/grafana/issues/6841

**Comment by maxenced** [comment]
Ok, thanks for info, nice to know there is an ongoing work to enable this :)

**Comment by stvnwrgs** [comment]
#6841 is closed. Any updates on this?

**Comment by sparshSinghal** [comment]
Any update on this?

**Comment by hamidmujtaba** [comment]
Hey guys, Any update now?

**Comment by rafaribe** [comment]
Is it already possible in newer versions of Grafana?

**Comment by Stuv7CB** [comment]
Any update on this?

**Comment by LiuGongqing** [comment]
Any update on this?

**Comment by linoman** [comment]
We're not working on this at the moment 🙂.

Consider looking into federation, we recommend [keycloak](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/keycloak/) for example.

**Comment by dosmanak** [comment]
Is it possible to set org based on some keycloak role provided?
