### ISSUE TITLE
Upgrade to grafana-4.7.0-10747pre1.x86_64 stomped ldap.toml

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#10201]
Upgraded from 4.6.2 to a nightly build (grafana-4.7.0-10747pre1.x86_64) and it stomped my ldap.toml file.

**Comment by torkelo** [comment]
Strange, we have other reports (very few) where rpm has done this, have not been able to replicate it though so seems to be a strange thing that only happens sometimes and also seems to depend on how you installed the rpm.

**Comment by calebcall** [comment]
It did it on both of my servers going from 4.6.2 to the 4.7 pre-release.  The way I installed it was I pulled down the rpm and pushed it to our local yum repository, then I just did a `yum upgrade grafana`.  Thanks

**Comment by torkelo** [comment]
very strange. Have you changed CONF_FILE in your sysconfig file?

from the post install: 

 # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafana/conf/sample.ini $CONF_FILE
    cp /usr/share/grafana/conf/ldap.toml /etc/grafana/ldap.toml
  fi

the ldap.toml file is only copied if there is no CONF_FILE and this is part of the post install only happens on first time install anyway. What OS and version are you running?

**Comment by calebcall** [comment]
I haven't touched the sysconfig file.  This was on CentOS 7.4.
