### ISSUE TITLE
grafana doesn't sort results returned by prometheus correctly.

### ISSUE THREAD

**Issue by ahrtr** [grafana/grafana#10208]
The following query works well on the prometheus query GUI, the records are always displayed in descending order, 
   sort_desc(sum(rate(my_call_count[1h])*3600) by (tenant))

But it doesn't work as expected when the above query is used in the grafana table. The data displayed on grafana table is correct, but the order isn't expected.  I am expecting to see the data being displayed in descending order for each time point, but it isn't. 

Grafana version: 	v4.6.2
Datasource:     Prometheus 
OS on which running grafana:     Oracle Linux Server release 7.3

**Comment by bergquist** [comment]
Try using `instant query` in the metric query editor. That should give you the same result as the prometheus GUI. Prometheus table only uses the last value for each serie. Grafanas table panel support time ranges, which might have a different sort order.

**Comment by ahrtr** [comment]
Thanks for the response, which indeed sovled the issue.  

I think it would be better for grafana to support "two-level" sorting, the first level is sorting the result by timestamp, the second level is sorting the results at the same timestamp based on the query function, i.e., sort / sort_desc.

**Comment by jeremybz** [comment]
Is there a similar workaround for graphs?

**Comment by torkelo** [comment]
closing this as it's does not seem like an important issue and would be problematic to implement in a datas source consistent manner (or without breaking prev behavior)
