### ISSUE TITLE
Feature request: Accept variables in the grid min/max values

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#1021]
Use case is the same as #922

**Comment by torkelo** [comment]
closing due to lack of interest

**Comment by Akeru** [comment]
:cry: well fair-enough if there is no interest

**Comment by cavaliercoder** [comment]
I've got interest!
For example when graph memory utilisation in bytes, I want to use the 'total system memory' metric as the grid max value. Same for disk capacity, swap usage, etc.

**Comment by balrogthane** [comment]
I also have interest! If we're allowed to add dynamic thresholds as in #922, we'd need to have dynamic maxes to ensure the threshold is visible.
