### ISSUE TITLE
TimeStamp is already in epoch time [millisec] stamp but mysql plugin is not reading it properly 

### ISSUE THREAD

**Issue by RashmiSaravanan16** [grafana/grafana#10212]
[image](https://user-images.githubusercontent.com/19386672/33991929-a97d9474-e0f6-11e7-8e82-25d29b2cb7e2.png)

We are dumping data with time which is already epoch timestamp [ '1512645007961'] but its used in mysql plugin it gets converted ['1512645007961000']
now data is not visible on the graph. 
its throwing error Date mismatch zone.

**Comment by daniellee** [comment]
Answered your question on the community site: https://community.grafana.com/t/how-to-add-time-series-queries-with-grafana-and-mysql/3170/5?u=daniellee

But the support for int's should be better - the Postgres data source already supports them.

**Comment by daniellee** [comment]
Related to #8666 - need better timestamp handling.
