### ISSUE TITLE
Grafana Reverse Proxy with APACHE

### ISSUE THREAD

**Issue by mohanraj1939** [grafana/grafana#10210]
- What Grafana version are you using - 4.6.2
- What datasource are you using - MYSQL
- What OS are you running grafana on - UBUNTU
I'm Trying to connect APACHE with GRAFANA.
Apache 2.conf File:
[apache2.txt](https://github.com/grafana/grafana/files/1558892/apache2.txt)

Ports.conf File:
[ports.txt](https://github.com/grafana/grafana/files/1558908/ports.txt)

 Grafana.ini File
[grafana.txt](https://github.com/grafana/grafana/files/1558898/grafana.txt)

Grafana.Log File:
[grafanalog.txt](https://github.com/grafana/grafana/files/1559038/grafanalog.txt)

Expected Output:
Grafana should operate via webserver.

Optained O/P:
![grafana](https://user-images.githubusercontent.com/33648564/33988636-f62df7a2-e0ea-11e7-9159-b5a7667b795f.JPG)

**Comment by torkelo** [comment]
set your root_url in grafana ini to the url you want to access grafana via (the full apache url + sub path)

**Comment by CeriMitch** [comment]
You need to reverse proxy a few more paths.  Here is what I ended up with in my Apache VirtualHost config for the same reverse proxy issue:

SSLProxyEngine on
`
SSLProxyEngine on
ProxyPass /dashboard https://grafana.somewhere.com/dashboard
ProxyPass /public https://grafana.somewhere.com/public
ProxyPass /api https://grafana.somewhere.com/api
`

**Comment by insanemal** [comment]
Yeah this doesn't work. Even with the full url set in root_url correctly

Seriously your documentation kinda sucks.

**Comment by torkelo** [comment]
strange, that should not be required

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass /stats http://0.0.0.0:3000/
    ProxyPassReverse /stats http://0.0.0.0:3000/
</VirtualHost>

**Comment by gyassine** [comment]
This may be useful to some people.. I tried all solutions I found on the net on this issue, but only these settings works for me :
```
<VirtualHost *:80>
ProxyRequests Off
ProxyPreserveHost On
ProxyPass /grafana http://localhost:3000
ProxyPassReverse /grafana http://localhost:3000/grafana
```

with `grafana` (subpath) at the end of `ProxyPassReverse `...

**Comment by lessenko** [comment]
Proxy works well with both configurations as described above.
But browsers present different results.

In firefox all work like a charm. 
But in chrome some menu items are not clickable
For example:  -> Panel Title(clickable) -> Edit (not  clickable)

Test is used to redirect to grafana dashboard from other site. URL  format is:
http://user:password@localhost:port/stats/d/uid_name/dashboard_name

It was used:
    Grafana  5.1.3
    Kubuntu 16.04.1
    apache2 2.4.18
    chrome 66.0.3359.181-0ubuntu0.16.04.1
    firefox 60.0.1
In grafana config.ini is added  two strings:
    http_addr = 127.0.0.1
    root_url = http://127.0.0.1:3000/stats

Thanks.

**Comment by torkelo** [comment]
set root_url to the same address you use to access grafana from your browser (the full apache url)

**Comment by lessenko** [comment]
I use 82 port for proxy. I set root_url = http://127.0.0.1:82/stats. Is it  right?
Chrome has the same problem. Fiefox is well.

**Comment by lessenko** [comment]
For any case:
View, Edit --- not clickable
Share, More, Remove - clickable

Thanks.

**Comment by lessenko** [comment]
I see following errors in chrome developer tools:

![chrome_1](https://user-images.githubusercontent.com/40150500/41250312-3412ff3e-6dbf-11e8-8737-fbf7d2f891d1.png)

**Comment by danadam** [comment]
> strange, that should not be required
> 
> <VirtualHost *:80>
> ProxyPreserveHost On
> ProxyPass /stats http://0.0.0.0:3000/
> ProxyPassReverse /stats http://0.0.0.0:3000/

[Documentation says](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass) that:
> If the first argument ends with a trailing /, the second argument should also end with a trailing /, and vice versa. Otherwise, the resulting requests to the backend may miss some needed slashes and do not deliver the expected results.

It made a difference in my case.

**Comment by lessenko** [comment]
Currently in my configuration it's used:

  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/

Just in case to avoid a problem with Chrome after redirection to Grafana
(extra hash tag  destroys some functionality of Grafana)
I added following code in Grafana's file "/usr/share/grafana/public/views/index.html":
<script type="text/javascript">
   if (location.href.indexOf("#") > -1) {
       location.assign(location.href.replace(/#!\/?/, ""));
   }
</script>

The code is from https://stackoverflow.com/questions/17509521/remove-part-of-url-using-mod-rewrite-with, in  answer by anubhava.

**Comment by cesarvn2010** [comment]
I'm not getting it to work, see my settings below. Can someone help me?

```
<VirtualHost *:443>
    ServerAdmin admin@myu.com
    ServerName myu.com
    ErrorLog "/var/log/httpd/error_log"
    CustomLog "/var/log/httpd/access_log" common

    SSLEngine on
    SSLCertificateFile /path/to/your_domain_name.crt
    SSLCertificateKeyFile /path/to/your_private.key
    SSLProxyEngine on    

    <Location /grafana>
                ProxyPass "http://192.168.6.3:3000/"
                ProxyPassReverse "http://192.168.6.3:3000/"
                ProxyPreserveHost On          

                AuthType basic
                AuthBasicProvider ldap
                AuthName "Restricted access"
                AuthLDAPBindDN cn=apacheldap,ou=DSA,dc=myu,dc=com
                AuthLDAPBindPassword xxxxxxxx
                AuthLDAPURL ldap://ldap2.myu.com:389/ou=people,dc=myu,dc=com?uid?one TLS
                AuthLDAPGroupAttribute memberUid
                AuthLDAPGroupAttributeIsDN off
                Require ldap-group cn=crsintranetrestrita,ou=groups,dc=myu,dc=com
        </Location>
</VirtualHost>
```
```
#################################### Server ####################################
[server]
# Protocol (http, https, h2, socket)
protocol = https

# The ip address to bind to, empty will bind to all interfaces
http_addr = 192.168.6.3

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = myu.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = true

# Log web requests
;router_logging = false

# the path relative working path
static_root_path = public
```
I present more details in [this link](https://www.linuxquestions.org/questions/showthread.php?p=6198596#post6198596).

I left it as suggested, but I still manage to access the link below without going through LDAP authentication, that is, the reverse proxy does not seem to be working.

https://myu.com:3000/grafana/login

And when I put the URL myu.com/grafana, the message "You don't have permission to access this resource."

**Comment by shimatai-mobees** [comment]
This settings is working for me, using SSL, using docker containers for Apache2, Grafana and Prometheus.

In Apache2 conf (e.g: 000-default-le-ssl.conf), setup a VirtualHost like this:

`
<VirtualHost *:443>
        ServerName grafana.mysite.com
        ServerAdmin webmaster@localhost
        DocumentRoot /usr/local/apache2/htdocs

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/grafana_error.log
        CustomLog ${APACHE_LOG_DIR}/grafana_access.log combined

        ProxyPreserveHost On
        ProxyRequests Off
        RequestHeader set X-Forwarded-Proto "http"
        RequestHeader set X-Forwarded-Port 3000
        ProxyPass / http://172.17.0.1:3000/
        ProxyPassReverse / http://172.17.0.1:3000/

        <LocationMatch /api/live/ws>
                 RequestHeader set Upgrade "WebSocket"
                 RequestHeader set Connection "Upgrade"
                 RequestHeader set Host "grafana.wakedev.mobees.com.br"
        </LocationMatch>

        RewriteEngine On
        RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
        RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
        RewriteRule .* ws://172.17.0.1:3000%{REQUEST_URI} [P]

        SSLCertificateFile /etc/letsencrypt/live/grafana.mysite.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/grafana.mysite.com/privkey.pem
</VirtualHost>
`
Remember that `172.17.0.1` is the main IP of docker host (docker0 network interface).

In defaults.ini under Grafana settings directory (inside Grafana's container is hosted in /usr/share/grafana/conf), change this settings:

`
domain = grafana.mysite.com
root_url = https://grafana.mysite.com/
`

Don't forget the trailing slash at the end of root_url!

Now restart your Grafana container and your Apache2 container. That's all!

**Comment by stebberr** [comment]
Working settings of version 8.3.3 for reverse proxy **with sub path**:
Apache2 configuration:
```
<VirtualHost *:443>
    RewriteEngine On
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /grafana/(.*) ws://localhost:3000/$1 [P,L]

    ProxyRequests off
    ProxyPass /grafana http://localhost:3000
    ProxyPassReverse /grafana http://localhost:3000

    ProxyPass / http://localhost:8888/
    ProxyPassReverse / http://localhost:8888/
</VirtualHost>
```
Grafana configuration:
```
[server]
domain = example.com
root_url = https://example.com/grafana/"
serve_from_sub_path = true
```

**Comment by rohoog** [comment]
I experienced errors "Origin not allowed" when retrieving data for the panels. Firefox adds the Origin HTTP header for POST requests. I solved it by adding header rewriting:
```
    RequestHeader edit Origin ".*" "http://localhost:3000"
```
Referer headers don't seem to bother grafana.
