### ISSUE TITLE
Difference between Graphite and Grafana

### ISSUE THREAD

**Issue by vilalobus** [grafana/grafana#10216]
Grafana version: Grafana v4.5.2 (commit: ec2b0fe)
DataSource: Graphite
OS: Debian 9

I'm Using grafana as a test for monitoring. With Collectd (SNMP) and Graphite. I Would like to use Grafana for the "Fancy" Dashboards and Alerting.

Actually, the problem that I'm actually seeing some Huge Peak in the Graphs ( Like a Overflow), but I can see this Only at the Grafana, In Graphite there is no Peak. My Bandwith is actually 150 Mbps and I have peaks with lot of Gbps, and this keep Warning some False Positive.

![grafana](https://user-images.githubusercontent.com/34543753/33995219-716b4054-e0c4-11e7-8258-db6f8ccc8e4b.jpg)

And this not Happen with Graphite:

![graphite](https://user-images.githubusercontent.com/34543753/33995390-f9c1c428-e0c4-11e7-8e1c-26f8d6c1e374.jpg)

I Don't know what to do.

**Comment by bergquist** [comment]
What does your queries look like?

**Comment by vilalobus** [comment]
This are my Queries:

Graphite
![graph-data](https://user-images.githubusercontent.com/34543753/34002247-3be67f60-e0d9-11e7-983c-e566418ccb59.JPG)

Grafana
![graph-data-grafana](https://user-images.githubusercontent.com/34543753/34002274-4f6b10a0-e0d9-11e7-9845-7a42a7d7b59a.JPG)

**Comment by vilalobus** [comment]
Is there any way to set a like a Max Value ? If pass that would discard ? Thanks.

**Comment by daniellee** [comment]
@vilalobus did you solve this?

**Comment by marefr** [comment]
Closing due to no more details.
