### ISSUE TITLE
Incorrect canvas css width causing blurry graphs

### ISSUE THREAD

**Issue by cout** [grafana/grafana#10220]
Read before posting: 

Please include this information:
- What Grafana version are you using? 4.6
- What datasource are you using? random walk
- What OS are you running grafana on? Ubuntu 14.04
- What did you do?
Create a new dashboard, then create a new graph.
- What was the expected result? canvas css width should be an integer
- What happened instead? canvas css width is non-integral

I believe this is the cause of blurry graphs in #7546 and #7496.  Using chromium browser on ubuntu 16.04, I see the following canvas element in the inspector:

       <canvas class="flot-base" width="1313" height="157"
         style="direction: ltr; position: absolute; left: 0px; top: 0px;
         width: 1313.62px; height: 157px;"></canvas>

If I change the css width to 1313px, e.g.:

        <canvas class="flot-base" width="1313" height="157"
         style="direction: ltr; position: absolute; left: 0px; top: 0px;
         width: 1313px; height: 157px;"></canvas>

then the graph is no longer blurry.

I believe this due to a breaking change in jquery 3.0 (https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values), which would mean that this was introduced with the upgrade to jquery 3.1 (#6034).  The graph is not blurry in grafana 3.0, which used jquery 2.1.4.

I'm not sure the best way to fix this.  Flot automatically sizes the canvas to the width/height of the placeholder object, which itself has a non-integer width.

To see the difference when the placeholder is an integral width, type this into the console directly after rendering a graph:

        $(".histogram-chart").width(Math.trunc($(".histogram-chart").width()))

and then resize the browser window to force a redraw.

**Comment by cout** [comment]
In chromium, setting the width of .histogram-chart to calc(100vw) causes the canvas to have an integral width.

**Comment by torkelo** [comment]
this seems to be fixed in master with new grid, at least I am unable to replicate it.

**Comment by cout** [comment]
I can confirm that with the new grid, there are no more blurry graphs, and that the css width on the canvas is integral.  This is because one of the outer DOM elements (.react-grid-item) has its width to an integral value set instead of using the default.

I tested both with the default-sized graph (which appears to be half of the available space) and with a graph sized to full width.  I sized the graph to full width both by clicking and dragging the corner of the graph, and by setting the graph to repeat for a template variable (repeating for a multi-value template variable with 1 value selected yields a full-width graph panel).  In all cases I tested, the canvas had an integral width.

**Comment by KeeganOP** [comment]
I know this is an old issue but don't know if I should open a new or continue the discussion here.

This has resurrected itself but only for the heatmap panel type(?). Changing the css from:
```
<div class="u-wrap" style="width: 740px; height: 166.4px;">
...
</div>
```

to: 

```
<div class="u-wrap" style="width: 740px; height: 166px;">
...
</div>
```

Gets rid of the blurry graph.

**Comment by leeoniya** [comment]
yes, please open a new issue with screenshots, data, panel config, and your devicePixelRatio.
