### ISSUE TITLE
[Feature request] Mixed datasource with template variables

### ISSUE THREAD

**Issue by BobVanB** [grafana/grafana#10224]
Grafana:
	Grafana v4.6.2 (commit: 8db5f08) 

I would like to have the options to use `-- mixed --` datasource in my templateing version.

![screenshot from 2017-12-15 10-10-34](https://user-images.githubusercontent.com/12323223/34034792-37ce0900-e180-11e7-8067-34b89db79e4d.png)

**Comment by bergquist** [comment]
Hi! I'm not sure I understand. Do you want to read template variables from a `-- mixed --` datasource?

**Comment by BobVanB** [comment]
Yes

**Comment by BobVanB** [comment]
@bergquist Do you still need more information?

With graphs i can use --mixed-- datasources and with template i can't.
The result is, that my template variable is missing some values.

**Comment by torkelo** [comment]
Using multiple data sources (using data source variables) is not supported
