### ISSUE TITLE
'Add Panel' icon should match the other grey icons

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10233]
In latest master (5.0.0.pre1), the 'Add Panel' icon is colorful while the rest are muted:

![image](https://user-images.githubusercontent.com/705951/34044090-f139cc8a-e1a3-11e7-9cbe-137157e49d94.png)

I'm not sure, but it also seems weird as the first icon, maybe move it between 'save' and 'settings'.

(Let me know if all these minor issues are useful/annoying... I'm just recording my reaction to new UI and thinking how to introduce it to folks)

**Comment by torkelo** [comment]
no it's by design that this stands out a bit so that it more noticeable
