### ISSUE TITLE
No color indicators for annotations in configuration list or dashboards

### ISSUE THREAD

**Issue by volter** [grafana/grafana#10234]
Running 4.6.3

I guess this could be considered a regression to #3590! The bolt symbol is gone and was replaced by a speech bubble, at least in the configuration list. The annotation control elements have no indicator icon one could color any more at all.

The change seems to have been introduced around https://github.com/grafana/grafana/commit/25aa9df2704ae23f808452a2280ae3dd13c17a0a#diff-805b57143673510f13e88db1613dedfe, but maybe earlier.

I would expect to have markers again on both, the configuration list and the dashboard elements.

**Comment by alitoufighi** [comment]
Is there any hope this can come into reality?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
