### ISSUE TITLE
Improve add user workflow for org admins (and server admins)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10237]
- Create new user from org/users view 
- Delete org user. Should delete user if user is only in this org (ask if this is what user wants).

**Comment by mattttt** [comment]
Spent some time on this today, went down a few paths that didnt yield results. Just as I was leaving the office, had some ideas on how to address, and will post some mockups/flows tomorrow with some refinement.

**Comment by torkelo** [comment]
@mattttt can you add the design mockups here? Then I can move this to ready for implementation

**Comment by mattttt** [comment]
Thought I posed this last week, here is the latest:

![image](https://user-images.githubusercontent.com/2886187/35439291-1aeef296-0268-11e8-996e-803f86c164b5.png)
