### ISSUE TITLE
Heatmap Graph fails to display tooltips in Mozilla Firefox

### ISSUE THREAD

**Issue by andreycizov** [grafana/grafana#10232]
- 4.6.3 (same is the case with play.grafana.org)
- InfluxDB
- Linux
- Using a Heatmap Graph to display histogram data, then moving the mouse over the displayed buckets.
- I am expecting to see an overlay tooltip.
- The tooltip is not displayed and the red line that is usually displayed for X axis under the current cursor position, is instead displayed at the leftmost side of the graph.

Just go here with the latest version of Mozilla Firefox: http://play.grafana.org/dashboard/db/new-features-in-v4-3?orgId=1

[Here's an example of what happens.](https://ibb.co/iBjSaR)

**Comment by marefr** [comment]
Closing this in favor of #12486
