### ISSUE TITLE
[Feature Request] Make editable should save and refresh dashboard 

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10236]
In 5x, you have to set the dashboard editable, save it and then do a full refresh for things to change.  It is very easy to miss this and get confused :)

I would like to be able to edit a dashboard while other people are using it -- but not save this state so that others keep seeing a read-only version.

Is it really necessary to save the change before editing?

**Comment by torkelo** [comment]
yea, we was just looking how this was really bad and needs to be improved.

**Comment by torkelo** [comment]
Need a way for the save model to return a promise so the dashboard settings view knows when the save has completed or been aborted.
