### ISSUE TITLE
[FeatureRequest] Graphite - Templating Query support time series query to look up values or series names

### ISSUE THREAD

**Issue by nathanbower** [grafana/grafana#10242]
I would like to populate a variable with a query numeric query function result.  The specific case is to query a threshold from graphite to review the area above or below a series, use isNonNull() so I can compute a sum and display as a % of time out of bounds for the threshold.

Ex:
myVariable =  averageSeries() returns 0.58
I would like to use that value in removeAboveValue(series, $myVariable)

**Comment by nemenemsrouge** [comment]
thx for linking my case #13699 ^^

**Comment by Hipska** [comment]
I would want to have this feature as well to be able to list servers that have a mysql service check as a Grafana variable: `icinga2.*.services.*.mysql`. Tried as well by adding `aliasByNode`, but that didn't work.

**Comment by hugohaggmark** [comment]
Added this to @grafana/observability-squad but not sure if Graphite or Variable System should handle this without digging into the details.

**Comment by aocenas** [comment]
Yeah this needs to be checked if it is possible currently, there were lot of changes in the variable system and I think simple queries like this should work there.

**Comment by ifrost** [comment]
I think should be easy to add, in a similar way Prometheus supports `query_result` (https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable).

**Comment by gtk-grafana** [comment]
Merged in https://github.com/grafana/grafana/pull/52341, closing

**Comment by Hipska** [comment]
@gtk-grafana did you see my comment? https://github.com/grafana/grafana/pull/52341#issuecomment-1203616137

**Comment by gtk-grafana** [comment]
@Hipska No I missed that! 🤦 Thank you!

**Comment by itsmylife** [comment]
@Hipska I think [the PR](https://github.com/grafana/grafana/pull/52341) resolves this. Do you think something is missing? If yes can you elaborate?

**Comment by Hipska** [comment]
No, It was misinterpreted. The PR wrongly mentioned this issue so they were not linked  and the merge did not make GitHub to close this issue as well.
```md
Fixes #
https://github.com/grafana/grafana/issues/10242
```
should have been changed to
```md
Fixes #10242
```

And then I misinterpreted my own comment as well 🤦

**Comment by shanson7** [comment]
Was any documentation about this feature created? I'm not sure how to use it to accomplish #2 in [this comment above](https://github.com/grafana/grafana/issues/10242#issuecomment-1098048945). It seems it tries to use the `metrics/expand` endpoint which doesn't seem to do what this feature is asking for (which is to use the timeseries data for filtering).

**Comment by bohandley** [comment]
Hi @shanson7, thank you for bringing this to our attention, I don't believe there was documentation added for this. Our apologies, I will create a card to get this done.

> 2. Use the names of the series from a query result (from linked issue [Variables from graphite with filters #13699](https://github.com/grafana/grafana/issues/13699))
>    
>    * To limit the result set to the most interesting values (topN, above threshold, matching condition)

To implement #2, you need a full query, for example `carbon.*.*.*`. Select query type "Metric Name Query," enter the full query and it will return a full list of names for this query. From the variable you can then filter the result set. 
<img width="1033" alt="Screen Shot 2023-01-05 at 12 22 02 PM" src="https://user-images.githubusercontent.com/25674746/210852649-80bb0f06-6310-45a6-b54c-6f026cca2504.png">

The main point of this feature was to mimic the result of "query_result()" variable query in Prometheus, which requires a query that returns values. Entering a partial query will only expand the results of what you entered, for example, carbon.*.*, but this was not what the feature was developed for. Let me know if this helps!

**Comment by shanson7** [comment]
> > 2. Use the names of the series from a query result (from linked issue [Variables from graphite with filters #13699](https://github.com/grafana/grafana/issues/13699))
> >    
> >    * To limit the result set to the most interesting values (topN, above threshold, matching condition)
> 
> To implement #2, you need a full query, for example `carbon.*.*.*`. Select query type "Metric Name Query," enter the full query and it will return a full list of names for this query. From the variable you can then filter the result set. 
> 
> The main point of this feature was to mimic the result of "query_result()" variable query in Prometheus, which requires a full query that returns values. Entering a partial query will only expand the results of what you entered, for example, carbon._._, but this was not what the feature was developed for. Let me know if this helps!

I don't think this is actually what the request 2 is asking for. Part 2 was asking to execute a timeseries query that does some filtering (the examples given are `topN, above threshold, matching condition`) and then the result of that query should be used to populate the variable. This is to limit the results of the variable to the "interesting" values. From the [linked ticket](https://github.com/grafana/grafana/issues/13699) the example is:

`aliasByNode(averageAbove(prod.servers.*.exec_time.mean, 100), -3)`

this will get all of the values where the average is >100. You can then create a dashboard with other metrics that are related (but maybe no correlated) for just these outliers. 

A similar case that I have often wanted to check is the resource usage for our highest hit servers. It might be something like:

`aliasByTags(highestAverage(seriesByTag('task=http_server', 'name=requests_in'), 10), 'host')`

Now we have the 10 `host`s with the highest values for `requests_in` and we can then look at other metrics (memory, cpu, etc) for these heavier hit hosts.

Note: This feature should work for tagged graphite as well as untagged.

**Comment by shanson7** [comment]
@bohandley - Should #13699 be reopened to handle this case?

**Comment by bohandley** [comment]
Thank you! This makes sense, so the metrics/expand endpoint doesn't do the things you're requesting. I have looked through graphite for filtering functions that do what you ask, `topN, above threshold, matching condition` we would need to pass functions like `highestAverage` and `filterSeries`, correct? I think it would be good to re-open https://github.com/grafana/grafana/issues/13699

**Comment by bohandley** [comment]
@shanson7 The update is merged. You can now use those functions in creating a variable to return a list of names.
