### ISSUE TITLE
Grafana alert URL is http, my site is https

### ISSUE THREAD

**Issue by robertchen** [grafana/grafana#10241]
- What Grafana version are you using?
4.6.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
ubuntu
- What did you do?
Setup an alert, the alert sends email with URL to the alert but it is http which my site is https (the url in the alert email is http://mysite.com/grafana/dashboard/db/nginx-monitoring?orgId=1, which should be https://mysite.com/grafana/dashboard/db/nginx-monitoring?orgId=1) 
- What was the expected result?
https instead of http

**Comment by bergquist** [comment]
Have you configured http://docs.grafana.org/installation/configuration/#root-url to be https://mysite.com ?
