### ISSUE TITLE
Index key too long on on migration with MySQL

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#10244]
Please include this information:
- What Grafana version are you using?
5.0.0-pre1

- What OS are you running grafana on?
official docker image `grafana/grafana:master` in Kubernetes

- What did you do?
Upgraded server from `4.6.2` to `5.0.0-pre1`

- What was the expected result?
I'll get all the `5.0` cool stuff 

- What happened instead?
Server crashed on migration old DB schema to new one. 

I'm using MySQL exatly it is upstream docker image [pervona:5.6](https://hub.docker.com/_/percona/) as a storage  and It fails on this SQL:
```SQL
CREATE UNIQUE INDEX `UQE_team_org_id_name` ON `team` (`org_id`,`name`);
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```
 
according to [official documentation](https://dev.mysql.com/doc/refman/5.7/en/create-index.html)
> Prefix support and lengths of prefixes (where supported) are storage engine dependent. For example, a prefix can be up to 767 bytes long for InnoDB tables or 3072 bytes if the innodb_large_prefix option is enabled. For MyISAM tables, the prefix limit is 1000 bytes. The NDB storage engine does not support prefixes (see Section 21.1.6.6, “Unsupported or Missing Features in NDB Cluster”). 

Is default maximum size of index 767 bytes by default for InnoDB tables

here is create table of the table `team`
```SQL
CREATE TABLE `team` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `org_id` bigint(20) NOT NULL,
  `created` datetime NOT NULL,
  `updated` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_team_org_id` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
``` 

I'm not sure what is the right solution here. Maybe would be easier to have simple id for the team which would be used in the index.. 

HOTFIX:
As a hotfix did the trick for me alter of the column `name` to lower number of characters
```SQL
ALTER TABLE team MODIFY name varchar(155) COLLATE utf8mb4_unicode_ci NOT NULL;
```
But thats of course ugly temporary hack

**Comment by DanCech** [comment]
That is the correct solution for mysql, the field length needs to be reduced to conform with the limits.

**Comment by FUSAKLA** [comment]
Yes but I'm not sure if this can lead to situation when grafana will try to persist longer team name than my custom length due to input check for default 255 characters

After testing i see Grafana automatically strips size of team name to max length set in the Database.

Ok it that case it's probably safe way to solve this.

**Comment by torkelo** [comment]
thanks for reporting this, reduced the length for the column

**Comment by FUSAKLA** [comment]
Thanks for fixing this so fast!
