### ISSUE TITLE
Total field should display integrated units

### ISSUE THREAD

**Issue by microbug** [grafana/grafana#10247]
When plotting a graph of network activity I enabled the 'Total' checkbox under 'Legend' in order to give a total amount of data transferred under the graph. I also set the left Y axis units to 'Bytes/sec'. This gives a total but the unit is 'Gbps' — it should be 'Gb' as the total is the amount of data transferred. Screenshot: https://imgur.com/cOAmUsD.

- What Grafana version are you using?
grafana/grafana:latest via Docker

- What datasource are you using?
Graphite output from FreeNAS → InfluxDB → Grafana

- What OS are you running grafana on?
Docker under a Linux host

- What did you do?
Above

- What was the expected result?
Units of Gb

- What happened instead?
Units of Gbps

- Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
I can do this if necessary but it seems overkill.

**Comment by torkelo** [comment]
This is not how the legend stats works. If you want accurate totals you need to use sum aggregation (if you have a rate you need to sum the rate over time). 

Legend stats like Avg, Min, Max, Total are not accurate at the same time, they depends on the metric query and the aggregation function. Sadly almost no TSDB returns time window stats like avg,min, max, total along side the time series data points. These stats can only be accurately calculated on the TSDB side before aggregation. 

Sure Grafana could see you have a rate unit and try to integrate but that will be pretty inaccurate (depending on the aggregation function and how downsampled the data is)
