### ISSUE TITLE
Simplify  copying Panels between similar dashboards

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#10248]
This is a Feature Request.

Right now if I want to copy a panel from one dashboard to another I have to do it through JSON copy-paste.   It would be nice to simplify this  process for panels which have similar enough templating so panel would work in new Dashboard too 

I would suggest some way to be able to "clone" a panel from other dashboard by simply picking that dashboard in panel in the interface to add a panel.

**Comment by torkelo** [comment]
This should be pretty easy to implement. 

Add a new Copy to clipboard option in this menu:

![image](https://user-images.githubusercontent.com/10999/34106140-5f494d4a-e3f7-11e7-8f76-df4e4f90c263.png)

Add option here:

https://github.com/grafana/grafana/blob/master/public/app/features/panel/panel_ctrl.ts#L156

Copy the panel json to clipboard but also store it in global variable and show it as a panel in the add panel view:

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/AddPanelPanel.tsx

![image](https://user-images.githubusercontent.com/10999/34106208-a4f2c45c-e3f7-11e7-8e79-e0064e8cf816.png)

Thinking is that the copied panel is included in that list of panels as "Copied Panel"

**Comment by torkelo** [comment]
This is the same issue as this, https://github.com/grafana/grafana/issues/10248

**Comment by PeterZaitsev** [comment]
Frankly I do not think it is very convenient to run around different dashboards to pull the panels in when you create target one.   I think better usability would be to add "Clone Panel" as the item to the item for "New Panel List"  when I can start  typing panel name and it could do the search over all panel names in all dashboard and let me easily find the panel by name to add it.  

Having said that easy COPY-PASTE for JSON would  be nice to - right now to copy and paste it take a lot of clicks

**Comment by torkelo** [comment]
@PeterZaitsev not sure I agree that sounds way harder and not as easy to know you get the right panel. 

If you have panel you want to copy you can just find it and copy it and it will be available in the add panel menu sounds better to me.

**Comment by torkelo** [comment]
But your approach has some merits as well just a lot harder to implement as well. My suggestion is to start simple.

**Comment by PeterZaitsev** [comment]
@torkelo  understood. I'm all for making what is easy available soon rather than  what is harder available later... if at all

**Comment by torkelo** [comment]
Initial support for copying panels between dashboards is now implemented, not great but at least something. 

Think we need to evolve this feature a bit further. Maybe even to a fully backend saved "Favourite panels", a simple modal to name the panel and saved it, and some way to view "favourite panels" from the add panel view and you have a pretty good way to reuse panels. 

<img width="444" alt="screen shot 2017-12-26 at 13 23 07" src="https://user-images.githubusercontent.com/10999/34356656-f8df3ba6-ea3f-11e7-8647-ed151fd2ee94.png">
