### ISSUE TITLE
Grafana ignores grafana.ini by default in docker container

### ISSUE THREAD

**Issue by andrewb-ms** [grafana/grafana#10243]
Read before posting: 

Please include this information:
- What Grafana version are you using?
Latest stable (why doesn't server settings page list this?)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Debian + Docker (using official docker image made by Grafana)

- What did you do?
Edited /etc/grafana/grafana.ini and this file is completely ignored by Grafana.  Added SMTP settings.  New SMTP settings do NOT show up in Admin/Server settings

- What was the expected result?
New SMTP settings should show up in Admin/Server settings

- What happened instead?
New settings are ignored.  Awesome.  Also, Server Settings page does not say where the values are actually coming from.

There is only one grafana.ini in the container - why is it being ignored?

Settings changes are to enable SMTP and change the server.  Here is what is showin inside the Admin/Server Settings page (this is the default and it won't let me change this):

smtp |  
cert_file |  
ehlo_identity |  
enabled | false
from_address | admin@grafana.localhost
from_name | Grafana
host | localhost:25
key_file |  
password | ************
skip_verify | false
user

**Comment by torkelo** [comment]
> Latest stable (why doesn't server settings page list this?)

The footer on all pages other than dashboard shows the version name. 

Unable to replicate this. When I start grafana docker container using:

```bash
docker run -i -p 3001:3000 \
  -v /home/torkel/dev/grafana-docker/data:/var/lib/grafana \
  -v /home/torkel/dev/grafana-docker/conf:/etc/grafana 
  grafana/grafana:4.6.3
```

and on my conf volume mount dir I have a grafana.ini file those settings take affect.

**Comment by andrewb-ms** [comment]
@torkelo  I am not mounting a specific folder to /etc/grafana but when I edit the ini file in /etc/grafana it does not take effect.  Is the mount necessary to get this to work?  If so, why is that?

**Comment by torkelo** [comment]
> I am not mounting a specific folder to /etc/grafana  

That does not matter, to things running in the container if files are on a mounted volume or not it does not matter. Grafana will read that file /etc/grafana/grafana.ini on startup. Just make sure you restart grafana process after you edit the ini file

**Comment by augisbud** [comment]
not happening for me, I changed the admin password to admin1 and after a restart it doesn't accept the password
