### ISSUE TITLE
[BUG] CloudWatch: Multi-select variables do not work anymore

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#10256]
Read before posting: 

- What Grafana version are you using?

4.6.3 (upgraded from 4.2.1 where everything was fine, was also broken in 4.6.2)

- What datasource are you using?

CloudWatch
- What OS are you running grafana on?

Ubuntu 14.04

- What did you do?

Created a dashboard with a "multi-select" template variable (and many more variables but to nail down the issue only one variable has "multi-select"enabled). Used this variable as a dimension filter and repeat panel.

![image](https://user-images.githubusercontent.com/1764725/34103483-22b501a8-e3ed-11e7-8ac9-f691ea6ab080.png)

![image](https://user-images.githubusercontent.com/1764725/34103513-3a3e17b0-e3ed-11e7-84bc-1eb4322812f0.png)

![image](https://user-images.githubusercontent.com/1764725/34103535-4b7710e0-e3ed-11e7-9e18-8cd3a586976b.png)

- What was the expected result?

Graph is displayed.

- What happened instead?

Panel is empty with no value

![image](https://user-images.githubusercontent.com/1764725/34103563-70b72e26-e3ed-11e7-813f-88fe46e53ced.png)

Query inspector does not work (wheel spins endlessly). Using Firefox dev tools query and response are

![image](https://user-images.githubusercontent.com/1764725/34103616-a7114c36-e3ed-11e7-9fb9-d9c3427f0953.png)

![image](https://user-images.githubusercontent.com/1764725/34103635-bb6f08c6-e3ed-11e7-8b16-5d847d26f305.png)

If I edit the `status` variable to unselect `multi-select` everything works fine. Seems related to `multi-select`. I have not tried what happen where there is only one variable.

**Comment by phr3nzii** [comment]
This is the same as the issue I raised, issue 9903

**Comment by cykl** [comment]
Indeed, I missed it. Duplicate of #9903.
