### ISSUE TITLE
Coloring thresholds in Singlestat panel not preserved when cloning (Save As) dashboards

### ISSUE THREAD

**Issue by ravinoz** [grafana/grafana#10251]
As per title. threshold values in Options > Coloring > Thresholds are lost when cloning a dashboard. All other settings/values in the panel are being preserved.

- Grafana version: v4.5.2 (commit: ec2b0fe)
- Grafana server OS: CentOS6
- Datasource: MySQL (issue applies to others)
- Repro steps:
     1. Create new dashboard
     2. Add Single Stat Panel with the following settings
          Metrics > Data Source: <MySQL datasource>
          Metrics > Query: SELECT 8
          Metrics > Query> Format as: Table
          Options > Coloring > Background: checked
          Options > Coloring > Thresholds: 5,10
     3. Save Dashboard ("New Dashboard")
     4. Save Dashboard As (Settings > Save As) "New Dashboard Copy"
- What was the expected result?
     Options > Coloring > Thresholds in the cloned Dashboard should be preserved (5,10)
- What happened instead?
     Options > Coloring > Thresholds values are lost.

**Comment by torkelo** [comment]
this was fixed in 4.6.x https://github.com/grafana/grafana/issues/9681
