### ISSUE TITLE
non-editable dashboard still opens legend color picker

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10255]
In master (5.0.0-pre1), on a non-editable dashboard if you click the legend, it still opens the color picker:

![image](https://user-images.githubusercontent.com/705951/34102051-02f3bfda-e3e8-11e7-8321-787583f470b9.png)

**Comment by torkelo** [comment]
it seems pointless to hide this.

**Comment by debmalyapan53** [comment]
How do I disable color-picker from popping up in viewer mode?

**Comment by torkelo** [comment]
You can’t, it’s a bonus feature :)

**Comment by debmalyapan53** [comment]
> You can’t, it’s a bonus feature :)

Okay :/ , but the issue is if I reassign any color, it doesnt get reflected across panels, which makes it inconsistent.

**Comment by torkelo** [comment]
It a per panel option
