### ISSUE TITLE
Grafana 5.0: Don't display folders when editing playlists

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10254]
Right now 
* you can add a dashboard folder to a playlist, but when the playlist runs the actual dashboard folder you'll get a dashboard not found message.
* you can only see dashboards in folders if you search for them.

![image](https://user-images.githubusercontent.com/1668778/34100510-ed927848-e3e2-11e7-8afd-1805af9c71a4.png)

1. Modify the query so that no folders are included
2. Make sure that the query by default all dashboards, including the ones in folders, are shown

**Comment by marefr** [comment]
@torkelo @daniellee any thoughts on 2)?

**Comment by daniellee** [comment]
Went with option 1.
