### ISSUE TITLE
[feature request] query inspector for Annotations

### ISSUE THREAD

**Issue by lukebigum** [grafana/grafana#10250]
- What Grafana version are you using?
4.6.3

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
CentOS 6

- What did you do?
Had a hard time getting the Lucene query for Elasticsearch Annotations correct, and couldn't find a way for Grafana to log or display what the data proxy was doing. In the end I had to tcpdump the elasticsearch port and catch it in the act.
 
- What was the expected result?
It would be nice to display exactly what Query API JSON blob is going to be sent to Elasticsearch for Annotations, like it is for graphs.

**Comment by daniellee** [comment]
Sounds like a good idea.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
