### ISSUE TITLE
Grafana doesn't show the points with same timestamp

### ISSUE THREAD

**Issue by techhseeker** [grafana/grafana#10265]
Data Source - InfluxDb - Latest
Grafana - Latest

I am storing data about workflows executions.
The precision for influxdb is set to nanoseconds.

Some of the points have same timestamps , influx stores them correctly as 2 different points because other tags in the data are different.

However Grafana doesn't show all those points with same timestamp.
It only shows 1 record for a given timestamp.

I don't understand how can this be a limitation. I would assume in a time seies database there would be hundreds of records per millisecond. What am I missing?

![image](https://user-images.githubusercontent.com/34136537/34128048-fce1708e-e404-11e7-8961-5d77b92b5f7a.png)
Out of 3 highlighted rows only 1 is displayed in my grafana table - 

![image](https://user-images.githubusercontent.com/34136537/34128091-225b033e-e405-11e7-95a6-ec69354d50c4.png)

My data is ordered by time.

I did a count(*) on influx db and a count (*) using grafana single stats . The counts match. Only the table plugin shows records with unique timestamps.

Please help !!

**Comment by torkelo** [comment]
1) Make sure your InfluxDB query does not have a group by time (that will cause points to be grouped into one based on the group by time interval)
2) Grafana does not support nanosecond resolution, only millisecond resolution timestamps. But you should still see two records (if your query returns two records), if the timestamp is only different in the nanosecond part they will show the same value

**Comment by techhseeker** [comment]
The query doesn't have a groupby clause.

![image](https://user-images.githubusercontent.com/34136537/34165209-44fffd8a-e4a1-11e7-95bc-8247b0cfd433.png)

The query is - 
SELECT * from "wfexecution" where "workflowname" = '$wfname'

The interesting thing is if I do SELECT count(*) from "wfexecution" where "workflowname" = '$wfname' in a single stat plugin, it doesn't group the same timestamp records.Hence returns the correct number of records.

The issue is only with table plugin.

**Comment by techhseeker** [comment]
I changed my table formatting to Table instead of Time Series and that seems to have solved the issue.

Thanks for your help

**Comment by cangfengzhs** [comment]
I have the same problem

**Comment by kipavy** [comment]
same issue... Table view shows 4 points whereas timeseries only shows 1
