### ISSUE TITLE
Isssues with Zabbix as a data source

### ISSUE THREAD

**Issue by Ineptsmeagol** [grafana/grafana#10268]
Hi
I am using Grafana 4.6.1 with Zabbix 3.4 as a back end data source running on Ubuntu 14.0.4.
I have created a singlestat panel that should query an Item that I have set up in Zabbix when I click on the Query Inspector for a metric query and  I see its doing a trigger.get call when it should be doing an item.history.  I have removed the auth token, Ip Addresses, and some description fields

Output of Query Inspector:
xhrStatus:"complete"
request:Object
method:"POST"
url:"http://1.1.1.1/zabbix/api_jsonrpc.php/"
data:Object
jsonrpc:"2.0"
method:"**trigger.get**"
params:Object
id:1
auth:"removed auth token"
response:Object
jsonrpc:"2.0"
result:Array[1]
0:Object
triggerid:"16989"
expression:"{16905}<>0"
description:"Some Desciption"
url:""
status:"0"
value:"0"
priority:"4"
lastchange:"1513641524"
comments:""
error:""
templateid:"16119"
type:"0"
state:"0"
flags:"0"
recovery_mode:"0"
recovery_expression:""
correlation_mode:"0"
correlation_tag:""
manual_close:"0"
lastEvent:Object
id:1

Output of Chrome Dev Tools:
{jsonrpc: "2.0", method: "trigger.get",…}
auth
:
"removed auth token"
id
:
1
jsonrpc
:
"2.0"
method
:
"trigger.get"
params
:
{output: "extend", itemids: ["38804"], expandDescription: true, expandData: true, expandComment: true,…}
expandComment
:
true
expandData
:
true
expandDescription
:
true
itemids
:
["38804"]
monitored
:
true
output
:
"extend"
selectLastEvent
:
"extend"
skipDependent
:
true

**Comment by bergquist** [comment]
Please open issues regarding the zabbix plugin at https://github.com/alexanderzobnin/grafana-zabbix
