### ISSUE TITLE
Feature Request: document Playlists API

### ISSUE THREAD

**Issue by bodsch** [grafana/grafana#10272]
It is possible to expand the API to create playlists too?

**Comment by daniellee** [comment]
It is possible already - it's just not documented. Currently there is no difference between Grafana's internal api and the public api.

**Comment by oddlittlebird** [comment]
It looks like this is now documented: https://grafana.com/docs/grafana/latest/http_api/playlist/

Can we close this issue?

**Comment by marefr** [comment]
Fixed
