### ISSUE TITLE
Graph 'null value' default to 'null' instead of 'connected'

### ISSUE THREAD

**Issue by andreasbalevik** [grafana/grafana#10273]
Hello,

I spent some time trying to figure out why no data was visible in my graph.
Found out that the settings was weird. Graph > Display > Stacking & Null value > Null value was set to 'NULL' instead of 'NULL as zero' or 'connected'.

Is there a way to set what value that should be default when creating a new graph?
Because now i each time have to go to 'Null value' and change from 'null' to either 'null as zero' or 'connected' to get my data displayed.

When i first installed Grafana, it was set to 'Connected'.

Grafana: 4.6.3
OS: Ubuntu 16.04
Datasource: InfluxDB

**Comment by torkelo** [comment]
> Is there a way to set what value that should be default when creating a new graph?

No there is currently no way to set default settings
