### ISSUE TITLE
Logout is broken on small screens from PageHeader

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#10277]
When using "Logout" from the select box navigation on small screens, you get a 404.

![screenshot 2017-12-19 12 56 48](https://user-images.githubusercontent.com/224493/34156171-5b070b8a-e4bc-11e7-8a3b-aca7db1a59ac.png)

**Comment by torkelo** [comment]
This is due to target="_self" logic that the angular router uses on links is missed when you only send the navigate event to the global srv service. (Target "_self" will make the angular router to do a full page reload)
