### ISSUE TITLE
Grafana 5.0: Enable permissions for dashboard folder and dashboards

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#10275]
There is a [hidden, unused modal component for dashboard permissions](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/acl/acl.ts). 

This needs to be converted to a page component that can be used for the new dashboard folder page and for the new combined settings page for dashboards.

Fix route permissions so that they do not conflict with new permissions system:

- [x] Annotations route - remove require editor role and replace with permissions check with fallback to role check
- [x] Dashboard post/delete route - remove req editor role on route and test that the permission system works as it should with default permissions
- [x] alert-notifications route - investigate if req editor role is needed (is needed)
- [x] alert routes - investigate if req editor role is needed (only pause requires editor role

Other fixes:
- [x] when saving new dashboards, check the parent folder for permission to save.
- [x] filter out folders from folder picker that the user does not have permission to save in.
- [x] hide create dashboard cta on dashboard folder page if user does not have permission to create a new dashboard in that folder.
 - [x] hide new dashboard button on dashboard folder page if user does not have permission to create a new dashboard in that folder.
- [x] Change permissions select to new component with description for each item in the dropdown (maybe based on react select component)
- [x] "inherited from folder" text should say which folder
- [x] "inherited from folder" for dashboards in root should have a different text
- [x] investigate removing inherited permissions for a folder (and document)
- [x] Add title to folder permissions page 
- [x] Show warning if user tries to remove their own access to a folder.
- [x] Remove "Update Permissions" button and save on every change.
- [x] Add readonly Admin row to permissions (to show that Admins always have admin permission)
- [x] Disable the pause and settings buttons for alerts in the alert list that the user does not have permission to view/edit.
- [x] Update permissions page to the React version in dashboard settings and remove old Angular version of the page.
- [x] Move help text into popover.
- [ ] When overriding permissions to give lower permissions, warn (or stop) the user that assigning lower permissions does not work. (this is hard - might go with a different approach)
- [ ] warn if dashboard has been moved to another folder via dashboard settings and the user is looking at a stale permission list.

**Comment by daniellee** [comment]
I need some design help cc @mattttt The branch is: https://github.com/grafana/grafana/tree/dashboard_permissions

Current state of the dashboard folder page permissions tab:

![image](https://user-images.githubusercontent.com/434655/34252046-54924b52-e642-11e7-9d43-7b80e477eb07.png)

Current state of the dashboard settings permissions tab:

![image](https://user-images.githubusercontent.com/434655/34252202-e7efd0e0-e642-11e7-83c5-f4c43e3d3c24.png)

**Comment by torkelo** [comment]
@mattttt so to clarify 

What we need help with is a better way to show Role descriptions and "what does permissions do" . 
1) limiting the width of the dashboard setting views to ~800px
2) Create a two column layout where a narrow column to the right of the permission table we can put short description for the roles and link to permission docs.

**Comment by mattttt** [comment]
![image](https://user-images.githubusercontent.com/2886187/35038908-8fc40ab8-fb7c-11e7-8cd4-8ccf444b1fd4.png)

![image](https://user-images.githubusercontent.com/2886187/35038934-a2d5c18c-fb7c-11e7-9d57-ad3777cf3e02.png)

![image](https://user-images.githubusercontent.com/2886187/35038950-a7d745b6-fb7c-11e7-9a83-0fa364f20727.png)

**Comment by torkelo** [comment]
notified his bug, https://github.com/grafana/grafana/issues/10579 the folder pages (list, settings, permissions) is not using the id in the URL. needs to be fixed after this issue is merged I think to avoid merge conflicts.
