### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10284]
- Create profile page that can be accessed by any authenticated user (Viewer/Editor/OrgAdmin)
- url `/user/<userId>/<username>` 

- Viewers & Editors
Can only see Name and Username (And Avatar)

- Org Admin
Can see & edit team memberships

- Server admins
Cae see and edit org membership & reset password & delete user

Will require some changes to the API. 

thoughts @mattttt @daniellee 

The thinking is that this page can be reached by clicking on any user in Configuration / Users page.  And in time replace the Server Admin > Users > Edit User page

**Comment by marefr** [comment]
@torkelo Can viewers/editors/non Org Admins access the Configuration / users page to start with?

**Comment by torkelo** [comment]
thinking yes. but not sure.

**Comment by Ijin08** [comment]
Here is a mockup of what the page could look like:
![org-user-profile](https://user-images.githubusercontent.com/23470681/45424027-80acf100-b695-11e8-829f-d3c64ebb4f6f.png)

Basic idea is to have simple page with basic info. The edit button is only for admins and clicking it turns the page into editing mode or moves to the user edit page in Server Admin.

While working on this some things felt unclear. At the moment Configuration pages are disabled for viewer/editor. Should it continue to be so? There is a edit page for users for Server Admin. Should there be two editing pages?

**Comment by torkelo** [comment]
Can you post a mockup with standalone page look  (Users/Patrick) header and Profile, & Teams as tabs

**Comment by Ijin08** [comment]
![org-user-profile2](https://user-images.githubusercontent.com/23470681/45430851-9aa2ff80-b6a6-11e8-9b22-58ddcb846f72.png)
