### ISSUE TITLE
Erratic bihavor Grafana refresh botton on Quick Range

### ISSUE THREAD

**Issue by opc40772** [grafana/grafana#10288]
Grafana Version: 4.6.0
Datasource: Elasticsarch 5.4
OS: Debian 9

I have my dashboad that takes elasticsearch your data and when I choose the quick range the first time it shows well but if I refresh the same range they are not the same data. For example, if I select the last 30 days when it is shown the first time it is fine, but if I give the refresh button of the graph it is not the same with a big difference
The first time
![screenshot-2017-12-19 grafana - navegacion intervalos personalizados](https://user-images.githubusercontent.com/30729683/34160907-c944d3ae-e49c-11e7-8679-6f398e6d42e3.png)
After refresh button
![imagen](https://user-images.githubusercontent.com/30729683/34160995-17c9af86-e49d-11e7-86af-48009de161e6.png)
As you can see, it's a strange behavior and I do not know what happens.
Any ideas?
Best regards

**Comment by torkelo** [comment]
maybe your template variables change on time range? 

please investigate using Query Inspector: 

https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630

And report what queries are sent to ES and the Elasticsearch response
