### ISSUE TITLE
Proxy HTTP Auth headers missing when rendering PNG

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#10281]
# Env

* Grafana v4.4.1 (commit: 6a9f8ca) 
* Elasticsearch Datasource with Http Auth : With credentials
* CentOS7.3

# Symptom

When exporting to a png (Direct link rendered image) we get a 403 error in the log and in the rendered image. Example with an annotation (metric data is okay as it comes from another datasource that does not require HTTP headers):

![grafana](https://user-images.githubusercontent.com/112638/34157937-da97a222-e4c3-11e7-8e8f-a6fc29611312.png)

# Troubleshooting

When tcpdumping the traffic going through the datasource, we see that The HTTP Credential Headers are missing. Datasource is proxied behind `localhost:8000`

## Datasource request upon normal rendering

```
POST /_msearch HTTP/1.1
Host: localhost:8000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Content-Length: 469
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.8,fr;q=0.5,de;q=0.3
Cas-User: me@example.com
Content-Type: application/json;charset=utf-8
Dnt: 1
Referer: https://grafana.example.com/dashboard/new?panelId=1&fullscreen&edit&orgId=1&from=now-1h&to=now
Via: 1.1 grafana.example.com
X-Authmethod-Used: CAS
X-Forwarded-For: 192.168.42.42, 127.0.0.1, 127.0.0.1
X-Forwarded-Server: grafana.example.com
X-Grafana-Org-Id: 1
```

## Datasource request when exporting image to PNG through `/render/`

```
POST /_msearch HTTP/1.1
Host: localhost:8000
User-Agent: Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1
Content-Length: 271
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
Content-Type: application/json;charset=UTF-8
Origin: http://127.0.0.1:8080
Referer: http://127.0.0.1:8080/dashboard-solo/db/by-usage-and-role?orgId=1&panelId=1&from=1513677417701&to=1513688217701&var-site_usage=foo&var-site_role=All&var-host=node01.example.com&var-precision=$__auto_interval&width=1000&height=500&tz=UTC%2B01:00
X-Forwarded-For: 127.0.0.1, 127.0.0.1
X-Grafana-Org-Id: 1
```

As you can see, `X-Authmethod-Used` and `Cas-User` are missing from the request, explaining the 403.

**Comment by bergquist** [comment]
I'm not sure where those headers come from. When rendering a panel Grafana starts a new subprocess with phantomjs that renders that panel. So I'm not sure how that process should get those headers.

**Comment by torkelo** [comment]
server side rendered images does not support data sources that use Direct access. You might need to change your auth details or URL for your annotation datasource so that it can be accessed and authenticated from grafana server.

**Comment by faxm0dem** [comment]
What's "Direct Access"?

**Comment by torkelo** [comment]
in data source settings how have you configured Grafana to access Prometheus? there are two options, proxy or direct

**Comment by faxm0dem** [comment]
I use Elasticsearch and proxy, not direct access.

**Comment by faxm0dem** [comment]
@torkelo as this was a misunderstanding, can you reopen the issue please?

**Comment by faxm0dem** [comment]
@torkelo or do you prefer if I open a new one?

**Comment by torkelo** [comment]
it seems like grafana cannot access elasticsearch, getting access denied

**Comment by faxm0dem** [comment]
Yes, because it is not forwarding the proxy Headers as it should.
@torkelo please reopen this

**Comment by torkelo** [comment]
it can't PNG rendering is done in the backend without any headers coming from the user (used to capture images in alerting in other scenarios, Grafana will open phantomjs to capture the image.

**Comment by faxm0dem** [comment]
I understand, so this is a limitation in the current design.
Could it be possible to disable the PNG related UI items, in order to not confuse the user? /cc @torkelo
