### ISSUE TITLE
Odd behavior when clicking 'Add Panel' button on a large dashboard 

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10299]
in Grafana 5/master, if you:
1. Add lots of panels to a dashboard
2. Scroll to the bottom of the page (so you can't see the top anymore)
3. Click the Add panel button...

At the very least, it should scroll to the top of the page, better would be to place the new panel somewhere in the visible window.

**Comment by mattttt** [comment]
Agreed that it's strange right now, and as you said, entirely lost when scrolled.

As suggested, I like scrolling up to New Panel, and should animate the scroll to the top. Doing so will reinforce the context (adding it to this dashboard), and that you havent left your existing view. Blinking to the top may be jarring to the user. 

I'm sure you know what I mean, but a couple examples:
https://css-tricks.com/snippets/jquery/smooth-scrolling/
https://www.abeautifulsite.net/smoothly-scroll-to-an-element-without-a-jquery-plugin-2
