### ISSUE TITLE
Playlist fails after a while on Chrome

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#10295]
- What Grafana version are you using?
grafana-4.4.1.windows-x64
- What datasource are you using?
Elasticsearch 2.4.0
- What OS are you running grafana on?
Windows 2012 R2
- What did you do?
Play a playlist with two dashboards in Google Chrome v62
- What was the expected result?
- What happened instead?
Playlist stops after a while with error message `Cannot view or edit playlist`. I figured out the reason is that I have 4 organizations and the playlist is in one organization. For unknown reasons, after a few rotations, Grafana switches to another organization (randomly) which the active playlist does not belong to. This happens on Chrome on multiple computers, but running the same playlist on Firefox works just fine. However, Firefox doesn't display Grafana panels well (visible scroll bar). I'm not sure if this is a bug or has to do with Chrome.

**Comment by bergquist** [comment]
Might be due to orgId query parameter getting out of sync for some reason. not sure.

**Comment by torkelo** [comment]
currently one user cannot use multiple orgs at the same time. It might help in your case to create a separate user for the playlist view

**Comment by anhlqn** [comment]
I'm not using different orgs at the same time. The issue repeated when the playlist was running on Chrome without any other tabs or any other browsers running.
