### ISSUE TITLE
dashboard alert is not showing up on "alert list" and the alert is alerting but not send out any alerts

### ISSUE THREAD

**Issue by robertchen** [grafana/grafana#10294]
Please include this information:
- What Grafana version are you using?
4.6.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Linux in docker

copied dashboard json, to /opt/grafana, the dashboard displays alerts but not in "alert list", the alert is alerting but not send any alerts

The dashboard shows the alert configuration and it is alerting but no alerts email are sent.
![dashboard-alerting](https://user-images.githubusercontent.com/1059160/34173984-57bd8c98-e4c5-11e7-843d-cc046b5a9c34.png)

![alerting2](https://user-images.githubusercontent.com/1059160/34173987-5ba5760e-e4c5-11e7-818b-65d3f9c400a0.png)

Alert list is empty.
![alert-list-empty](https://user-images.githubusercontent.com/1059160/34173994-6078f52a-e4c5-11e7-9b48-0b96a1a78c90.png)

**Comment by robertchen** [comment]
after further research, it seems alerts in dashboard is not imported to grafana as for now.
Also I could not find any examples how to create alerts with API...Is this a really working tool or just looking fancy?

**Comment by bergquist** [comment]
Have you configured [dashboard.json] to read dashboards from `/opt/grafana` ?

To enable alerts in Grafana you need to save the dashboards to the database.

**Comment by robertchen** [comment]
Yes, please see the picture, the dashboard is loading correctly, just not the alerts

**Comment by daniellee** [comment]
@robertchen are you still having this problem? And if you are, are you seeing any errors in the Grafana server logs when saving the dashboard?
