### ISSUE TITLE
Setting Y-Axis precision

### ISSUE THREAD

**Issue by RuiMeireles** [grafana/grafana#10292]
I'm having this strange behaviour. I'm plotting some interface throughput graphs on 10Gbps interfaces, but I'm setting the Y-Axis upper limit on 11Gbps.

<img width="1752" alt="screen shot 2017-12-19 at 16 04 13" src="https://user-images.githubusercontent.com/13831977/34163504-260154c0-e4d7-11e7-8bcc-72edcb88d8a7.png">

This all looks great, unless you're looking at the dashboard. Here the Y-Axis of the graphs show the units without the decimal value, and it's rounding up the non-integer values.

<img width="865" alt="screen shot 2017-12-19 at 16 04 57" src="https://user-images.githubusercontent.com/13831977/34163605-6f510cec-e4d7-11e7-9009-dc259988706a.png">

Instead of showing values [0, 2.5, 5, 7.5, 10] we're seeing [0, 3, 5, 8, 10]. This makes eye reading the graphs extremely imprecise!

How can I change this behaviour? I can't seem to find an option to set "Decimals" in Axis, as we have in Legend. Thank you.

Running Grafana v4.4.1 (commit: 6a9f8ca) on Ubuntu 3.13.0-113-generic

**Comment by torkelo** [comment]
yes, this is a problem related to base 10 based y axis. The decimal calculation and the "even" y-axis ticks is not working correctly for non base 10 y-axis.

https://github.com/grafana/grafana/issues/8957 

You can sort of fix this by hard coding a y axis decimal count (option available latest version of Grafana)
