### ISSUE TITLE
Templating doesn’t work with some fields in Grafana + ElasticSearch

### ISSUE THREAD

**Issue by amjadcas** [grafana/grafana#10296]
I have an issue while templating on Grafana 4.4.1 with ElasticSearch 5.4.1 as a data source on Windows Server 2012.

My goal is to display on Grafana the CPU/RAM usage of a specific process on several servers. Because I don’t want to manually create a panel for each server, I’m creating a variable template linking to the terms of the server field.

Here is an example of how my data looks:

```
{
 _index: infra,
 _type: process,
 _source: {
     cpu: an integer,
     server: a string,
     ram: an integer,
     process: a string
 }
}
```

When I query `{"find": "terms", "field": "server"}` Grafana finds none of the servers (when it’s supposed to find the different servers present in the datasource).

The part that I don’t get is that the same query would correctly work with some of the document fields (but not all)… Any idea of what’s going on?

**Comment by torkelo** [comment]
Elasticsearch terms queries only work on indexed fields. server looks to only be a source property and not a indexed field, might need to update your index mapping

**Comment by amjadcas** [comment]
It was indeed because of the mapping.

`server` is multi-fields, here is its mapping:

```
"server": {
   "type": "text",
      "fields": {
         "raw": {
            "type": "keyword"
         }
      }
}
```

And querying `{"find": "terms", "field": "server.raw"}` works in Grafana!
