### ISSUE TITLE
Dynamically Resize Table Panel

### ISSUE THREAD

**Issue by meshfx** [grafana/grafana#10298]
Hey there,

I have three panels on a page, one of top of the other.  They each have a mysql datasource to display various table data.  The information that is shown is all about artist activity per week, how many people started, how many left and the following weeks starters.  At no point at all three panels full of data and the panels that are full move from week to week.

For example, we had 3 people starting with us this week (3 lines of data in that panel) but 32 people leaving and there are only 5 future starters.  Next week though there are are no new starters so that panel will be empty but we have 51 people leaving.  So on and so forth the panel data is fluid.. BUT the problem is on the big weeks I can never see all the rows in some panels.  

Is there a way to dynamically have grafana resize the panels to show all the data it can.  I know it may not be perfect if all the panels have too much data to show on the screen at once, but happy to see it working if it could as best it can.  As I said, most weeks not all the panels are maxed out with data so this would work well if it were possible.

We display the data on a screen on our room and various production people come in the check names, seats start dates etc etc, when names are off the screen with a scroll bar no-one can access it defeats the purpose.

Anyway, hoping this is achievable.

Thanks.

**Comment by torkelo** [comment]
This is sadly not possible.
