### ISSUE TITLE
[Bug] tsdb.HandleRequest() error time: invalid duration $interval with specified firm 10s 

### ISSUE THREAD

**Issue by robertchen** [grafana/grafana#10293]
Please include this information:
- What Grafana version are you using?
    Grafana v4.5.2 (commit: ec2b0fe) 
- What datasource are you using?
  influxdb
- What OS are you running grafana on?
Linux

I defined the metrics like this with firm time interval in 10S, please see the groupby time(10s):
![nginx-metrics](https://user-images.githubusercontent.com/1059160/34167245-2d210070-e4af-11e7-9216-cedad58e0e2b.png)

The alert is always having issue, tsdb.HandleRequest() error time: invalid duration $interval
![nginx-alert-issue](https://user-images.githubusercontent.com/1059160/34167244-2d141bf8-e4af-11e7-999c-a4735d9e4c20.png)

Looks like grafana alert is not ready for production, even the basic alert does not work. 
Thanks.

**Comment by robertchen** [comment]
seems the issue is gone after using 4.6.2

**Comment by spectraforcetechnologies** [comment]
'im using grafana 4.6.3 facing the same issue 
![pmm-server](https://user-images.githubusercontent.com/35957756/35562929-07c1c222-05db-11e8-8a4a-7960723a10ec.PNG)
![pmm-server2](https://user-images.githubusercontent.com/35957756/35562930-08068682-05db-11e8-8f46-1af6fcc68dea.PNG)

log information:
![pmm-server3](https://user-images.githubusercontent.com/35957756/35562980-376f1920-05db-11e8-8835-e4485639248a.PNG)
