### ISSUE TITLE
Getting "Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by honiewelle** [grafana/grafana#10301]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
**4.6.3**
- What datasource are you using?
**Cloudwatch**
- What OS are you running grafana on?
**Ubuntu16.04**
- What did you do?
**Created single stat panel to show ELB_5xx count**
- What was the expected result?
**Panel should show "0"**
- What happened instead?
**Red notification at the upper left corner of the panel with message "Cannot read property 'length' of null" and panel shows "N/A"**
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 **Request:** 
`{"from":"1513739371866","to":"1513760971867","queries":[{"refId":"metricFindQuery","intervalMs":1,"maxDataPoints":1,"datasourceId":1,"type":"metricFindQuery","subtype":"dimension_values","region":"ap-southeast-1","namespace":"AWS/ApplicationELB","metricName":"HTTPCode_Target_5XX_Count","dimensionKey":"TargetGroup","dimensions":{"LoadBalancer":"app/GW2-UAT-APP-ALB/b78bbf4e4f5e471e","TargetGroup":"targetgroup/ALIPAY-CALLBACK/6b17ecc14eff7d28"}}]}`
**Response:**
`{"results":{"metricFindQuery":{"refId":"metricFindQuery","meta":{"rowCount":1},"series":null,"tables":[{"columns":[{"text":"text"},{"text":"value"}],"rows":[["targetgroup/ALIPAY-CALLBACK/6b17ecc14eff7d28","targetgroup/ALIPAY-CALLBACK/6b17ecc14eff7d28"]]}]}}}`

EDIT: Changed version to 4.6.3

**Comment by daniellee** [comment]
Is it possible for you to upgrade your Grafana? We do not really want to investigate bugs in a version as old as 3.6.2 - there have been a lot of changes to the Cloudwatch code in Grafana since then.

**Comment by honiewelle** [comment]
Hi Daniel, my bad the version should be 4.6.3. I have amended my post earlier.

**Comment by torkelo** [comment]
The network query / and response you pasted is not for a metric query but for a metric find query (used in templating queries and to look up dimension values). Please include the response from the metric request (open query inspector in the metrics tab of your singlestat panel)

**Comment by honiewelle** [comment]
@torkelo here's the response log I got from Chrome Dev Tools:

`{"results":{"A":{"refId":"A","series":[{"name":"HTTPCode_ELB_5XX_Count_Sum","points":null,"tags":{"LoadBalancer":"app/GW2-UAT-APP-ALB/b78bbf4e4f5e471e"}}],"tables":null}}}`

In addition, Query Inspector does not display data and only showing the spinner and the console log shows the following exception:

`Panel data error: TypeError: Cannot read property 'length' of null
    at t.isMsResolutionNeeded (time_series2.ts:238)
    at new t (time_series2.ts:60)
    at e.seriesHandler (module.ts:228)
    at Array.map (<anonymous>)
    at e.onDataReceived (module.ts:225)
    at o.emit (index.js:129)
    at t.emit (emitter.ts:13)
    at e.handleQueryResult (metrics_panel_ctrl.ts:297)
    at u (angular.js:17051)
    at angular.js:17095`

**Comment by lauvdk** [comment]
Also seeing this error. Seems to be working on 4.5.2, but not on ^4.6.

**Comment by mikecroft** [comment]
I've found a very similar error when using the `ebs_volume_ids` template query, [using dashboard 617 "AWS EC2"](https://grafana.com/dashboards/617).

The reason I think it may be the same issue is that I am using the same Grafana version and getting an exception when the EBS query is attempted and using QueryInspector hangs just like @honiewelle describes.

Based on the [cloudwatch datasource documentation](http://docs.grafana.org/features/datasources/cloudwatch/), it looks like the query should work. The stack from the log is below. If this looks like a different issue, I'll remove this comment and open a new issue. I get the same issue on two different Linux environments (same Grafana version), Arch Linux and Ubuntu 16.04.

```
t=2017-12-21T13:56:12+0000
lvl=eror
msg="Request error"
logger=context
userId=1
orgId=1
uname=admin
error="runtime error: invalid memory address or nil pointer dereference"
stack="
/usr/local/go/src/runtime/panic.go:491 (0x431e62)
/usr/local/go/src/runtime/panic.go:63 (0x430d6d)
/usr/local/go/src/runtime/signal_unix.go:367 (0x44924b)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:490 (0xd28174)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:368 (0xd264b4)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:183 (0xd22a57)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/cloudwatch.go:73 (0xd1768d)
/go/src/github.com/grafana/grafana/pkg/tsdb/request.go:17 (0xbb0099)
/go/src/github.com/grafana/grafana/pkg/api/metrics.go:46 (0xde3b5e)
/usr/local/go/src/runtime/asm_amd64.s:511 (0x461191)
...etc...
```

**Comment by paco3346** [comment]
I'm experiencing the exact same issue as @mikecroft

**Comment by peycho** [comment]
I'm having the same issue with displaying single panel and converting null to 0 ot N/A
Grafana v4.6.3 (commit: 7a06a47)
Ubuntu 14.04

![image](https://user-images.githubusercontent.com/170853/34554962-0a9e243e-f138-11e7-98ff-8909f6d94314.png)

![image](https://user-images.githubusercontent.com/170853/34554940-f25d6a9c-f137-11e7-8429-3bf768602c39.png)

**Comment by mtanatwine** [comment]
Not sure how useful it is but also adding to this issue, having the same problem. Grafana 4.6.3 and CloudWatch just not returning anything:
<img width="756" alt="screen shot 2018-01-04 at 15 30 26" src="https://user-images.githubusercontent.com/33697686/34570612-379ac0ec-f164-11e7-97ac-650a74a42af5.png">

**Comment by peycho** [comment]
The null value from cloudwatch is normal in some cases but CPU credit balance is not one of them.

**Comment by mtanatwine** [comment]
@torkelo Is this being looked into? Using the CloudWatch exporter instead is not ideal with an automated environment as IPs and instance IDs change if the instance is terminated.

**Comment by torkelo** [comment]
@mtanda any ideas for what could be wrong here?

**Comment by mtanda** [comment]
@torkelo I guess this fix https://github.com/grafana/grafana/pull/9856 is not released yet?

**Comment by djcrabhat** [comment]
Ya, tracing this through, the problem seems to be when you get a null-set from cloudwatch (like if your ELB had no 4xx errors in the queried time period, you don't get a bunch of 0s, you get null back).  I was gonna try and fix it from the panel's side, but think the empty points array from @mtanda is a much better solution.

**Comment by honiewelle** [comment]
Confirmed this has been fixed in v5. Thanks so much for your hard work guys!
