### ISSUE TITLE
Grafana 5.0: Don't store folderId in dashboard model

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10307]
Right now folderId are stored in the dashboard model, but shouldn't be needed. One consequence right now are that the version history consists of folderId changes if a dashboard have been moved between folders, however one may think that reverting such a version will move a dashboard back to origin folder but that will not happen.

Because of this and since folderId on the dashboard model aren't used for anything else, remove it.

**Comment by zhughes3** [comment]
@marefr 
To associate a dashboard with a particular folder, I was under the impression that I would need to add the "folderId" : "THE_FOLDER_ID" to the json dashboard model.
Is there a different way that this should be done to automate this process and not have to click through the user interface to associate dashboards with a folder.
