### ISSUE TITLE
Grafana didn't display the correct the value until a couple of minutes later

### ISSUE THREAD

**Issue by ahrtr** [grafana/grafana#10308]
The prometheus query is really simple, which is as below, 
sum(my_call_count{component="comp1"})

When the value returned by the query changed from 1 to 2, it's correctly displayed on the prometheus query GUI in 30s ( the scrape interval of prometheus is 30s). But what's displayed on grafana was a little interesting...in the begining, the value displayed on grafana GUI was 1.5, about a minue later(the UI is refreshed every 1m), it's 1.6, and then 1.7....eventually it's the correct value 2.  

Although it's the correct value being displayed on grafana UI in the end, It's really confusing when I saw the intermediate values.  Can you please explain what's the reason? 

Grafana version: v4.6.2
Datasource: Prometheus
OS on which running grafana: Oracle Linux Server release 7.3

**Comment by torkelo** [comment]
Hi, 

Please use the query inspector to troubleshoot the issue. Then you can see that its probably Prometheus that returns something you do not expect. 

Maybe related to step parameter? If you think Grafana issues the query wrong or is not showing the data that prometheus returns please include the Prometheus response (from the grafana metrics tab query inspector)
