### ISSUE TITLE
Wildcard in templating variable are not interpreted with elasticsearch

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#10310]
Hello

I have some elastic documents (json) with an account_id properties

```
{
id: 42,
account_id: 1234
...
}
```

I created a template variable (constant) to filter my dashboard by account_id.
Everything works fine, but if I want to see the whole trafic (without filters) setting a star (*) in the $account_id template doesn't do the job...

The header sent are:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"logstash-*"}
{"size":0,"query":{"bool":{"filter":[{"range":{"created_at":{"gte":"1513181937861","lte":"1513786737861","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"account_id:\\* AND operation_type:(op1 op2)"}}]}},"aggs":{"3":{"filters":{"filters":{"SUCCESS":{"query_string":{"query":"result.exec_code:0000","analyze_wildcard":true}},"REJECT":{"query_string":{"query":"!result.exec_code:0000","analyze_wildcard":true}}}},"aggs":{"2":{"date_histogram":{"interval":"2h","field":"created_at","min_doc_count":0,"extended_bounds":{"min":"1513181937861","max":"1513786737861"},"format":"epoch_millis"},"aggs":{}}}}}}
```

You can notice that the * has been protected with 2 backslashes...

Is it a normal behaviour ? is there another way to implement a "wildcard'" behaviour handled by template variables?

Grafana version = 4.4.2

**Comment by louzadod** [comment]
It worked in the latest 4.6.x for me. But in  5.0.4 the same problem happens to me.

**Comment by marefr** [comment]
@louzadod does it work if you use `${account_id:lucene}`?

**Comment by liujin1993** [comment]
@marefr it does not work

**Comment by marefr** [comment]
Verified that `${varname:raw} works so please use `${account_id:raw}

**Comment by liujin1993** [comment]
@marefr it also does not work. My grafana version is 5.1.   It seems that there is no "raw" format.
![image](https://user-images.githubusercontent.com/31949674/41148643-10dd10c0-6b3c-11e8-8540-e79ef37abb0f.png)

**Comment by marefr** [comment]
We're not explicitly supporting the raw keyword, but what it will do is to fallback to the default for formatting the value. If the value is not an array it will not do any formatting - see the end of the switch case which handles the default case. This means that you could put anything after `${varname:` that's not regex, lucene, pipe, distributed, csv. 

![image](https://user-images.githubusercontent.com/1668778/41276583-ed57ef44-6e24-11e8-8b62-54bf67b37026.png)

![image](https://user-images.githubusercontent.com/1668778/41276587-f0fc69f4-6e24-11e8-83ba-a20fc79af065.png)

**Comment by torkelo** [comment]
closing this in favor of #13756
