### ISSUE TITLE
Dynamic dashboards?

### ISSUE THREAD

**Issue by dialt0ne** [grafana/grafana#1031]
Is the function returned from scripted_async.js called only once? Would it be possible to have that function or some other hook into the auto-refresh to allow adding and removing items from dashboards?

The scenario I envision is a function that will be called after the auto-refresh of data a function could be called to review the local data collected (or call to graphite remotely) and has logic that will add or remove another row, graph, etc. e.g. when CPU usage has exceeded 95% for x data points, display a new row that has swap usage information, number of apache procs and number of connections to the database. Then when CPU usage has been less than 50% for y data points, remove the new row. Even better if tagging was possible for rows and remove by tag.

**Comment by eswarbala** [comment]
I'd like to second this request please. I am looking for a way to add/remove rows whenever new machines/containers are launched. Currently it is not possible as the initial function is called only once.

**Comment by torkelo** [comment]
You can use the http api to do some automation.

Closing this due to lack of interest.
