### ISSUE TITLE
How to let the alert function to support for the third part datasource plugin

### ISSUE THREAD

**Issue by suntenday** [grafana/grafana#10314]
I am now use the third part datasource plugin (https://github.com/aliyun/aliyun-log-grafana-datasource-plugin).
But when I use the alert function , show me the message "not support this datasource"
So how I can use alert function for third part datasource plugin or how I can make some changes in the sources of grafana to let it support.

**Comment by marefr** [comment]
Grafana don't support alerting for third party datasources right now. 

Issue #6841 aims to enable support for more TSDBs for alerting.

**Comment by bergquist** [comment]
To add support for you custom datasource you have to dig into the code yourself. 
I suggest looking at https://github.com/grafana/grafana/pull/8934 as an example.

Closing this since its a question and not a bug/feature.

**Comment by suntenday** [comment]
Thanks I will check it
