### ISSUE TITLE
Tag query expression with empty value

### ISSUE THREAD

**Issue by replay** [grafana/grafana#10318]
According to the tag query format specification a query like `<tag>!=` (with empty value) is valid. But with the current tag query editor this does not seem to be very well supported. The only work-around (besides toggle edit-mode) I have found was to enter `""` as value, but then i can't continue adding more expressions.

This is with the latest grafana `master`, at the commit 3a1f52d8a2fdd1fd3b9bdbee05a48925bf8580f1

**Comment by torkelo** [comment]
Not sure how to fix this as empty value is seen as "no change"  in the typeahead dropdowns

**Comment by DanCech** [comment]
Yeah, that was what I was trying to fix with the dropdown mods that got reverted.

**Comment by torkelo** [comment]
Closing this as it appears to not affect many users (that we know)
