### ISSUE TITLE
request floods from client to server

### ISSUE THREAD

**Issue by dbcook** [grafana/grafana#10312]
We are having a recurring service-impacting problem that is being caused by sporadic instances of  floods of requests coming into the Grafana server from one or a small number of browser clients.

Grafana 4.5.2
Data source: OpenTSDB
Server OS: Linux
Client OS/browser:  Chrome 63.0.3239.84 on Windows

For a while we have been suffering overload incidents that abruptly generate so much load on our OpenTSDB/HBase cluster that service is impaired, and sometimes the cluster has to be partially or fully restarted.

In the investigation, when we implemented metrics to examine TSD read scans by dashboard, we found that during overload incidents were were seeing read scan rates from certain dashboards of up to 10-20 million per hour.

Also when this is happening, the Grafana server logs show requests coming from certain client user/IPs relating to specific dashboards at very high rates, sometimes over 25Hz.  A redacted log of this is attached, where you can see 21 requests logged in under two seconds.  The affected dashboard was recording 18M scans/hour and OpenTSDB had become unusable.  We found the user associated with this, and when he closed his Grafana tabs (he said there were only one or two), the scan load promptly disappeared.

The problem moves around; we've seen it flood half a dozen different dashboards, occasionally more than one at a time.  Traffic plots show that the onset of the rapid requests is nearly instantaneous.

So far this seems like it's either a Grafana client issue, or perhaps some Chrome helper mayhem.  Insights would be greatly appreciated.

[grafana_request_flood_log.txt](https://github.com/grafana/grafana/files/1577509/grafana_request_flood_log.txt)

**Comment by torkelo** [comment]
This is strange, we have not had any similar reports. The most number of queries Grafana sends (per open browser tab) is number panels * auto refresh rate. 

So if your refresh rate is 1s (the lowest possible) and have 20 panels Grafana will issue 25 requests per second.

**Comment by torkelo** [comment]
Can you provide details of the dashboard settings (json model), and any error in chrome dev console ? (when this happens)

**Comment by daniellee** [comment]
Are they bad requests (http status code 400) due to OpenTSDB getting flooded or is there something else corrupting them?

**Comment by daniellee** [comment]
No response for 4 months. Closing.
