### ISSUE TITLE
Hide title of panel in grafana5

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10326]
Grafana 5 does not allow us to hide the title of panels; I miss that feature.

**Comment by torkelo** [comment]
you can still have panels without any title. But the area needs there to have something to grab to drag and top open panel menu

**Comment by roidelapluie** [comment]
It is hard to have small singlestat due to this:
![sstat](https://user-images.githubusercontent.com/291750/34320025-1fe9ab2a-e7f0-11e7-958d-3985e70eddc2.png)

**Comment by NateZimmer** [comment]
This would certainly be nifty!

**Comment by torkelo** [comment]
Implemented by https://github.com/grafana/grafana/pull/16884 (in better form than in version prior to v5)
