### ISSUE TITLE
[RFE] Add support for InfluxDB `tz` clause

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#10322]
- What Grafana version are you using? 4.6.3
- What datasource are you using? InfluxDB

InfluxDB supports timezone for queries since 1.3:
 - https://github.com/influxdata/influxdb/issues/6541
 - https://docs.influxdata.com/influxdb/v1.4/query_language/data_exploration/#the-time-zone-clause

Grafana currently does not allow to configure it (unless you switch to the edit mode) and does not automatically set a `tz` clause.  It means that InfluxDB uses UTC to calculate time buckets which is annoying when you are trying to visualize metrics that should be bucketed according to a given timezone rather than UTC. 

It would be great to be able to explicitly set a `tz`. I am also wondering if Grafana shouldn't automatically set `tz` to the dashboard time zone. Compatibility with InfluxDB < 1.3 should also be taken into account.

**Comment by tecmatia-dp** [comment]
+1
In Table plugin with GROUP BY (1d) is very important the tz() clause.
Although written manually, it is lost when changing edit mode.
The workaround GROUP BY(1d,-2h) is best aproach, but it fails with daylight saving time change.

**Comment by pmouawad** [comment]
+1

**Comment by tecmatia-dp** [comment]
Any news about this?

**Comment by cykl** [comment]
@tecmatia-dp Have you tried @jkreileder patch? Maybe a positive feedback could help it getting merged?

**Comment by overallduka** [comment]
+1

**Comment by torkelo** [comment]
this is now in nightly master , please test and give feedback!
