### ISSUE TITLE
Grafana 4.6.3 dashboards_json load dashboards twice

### ISSUE THREAD

**Issue by snebel29** [grafana/grafana#10335]
Hi,
Grafana 4.6.3 dashboards_json load dashboards twice when providing the dashboards using a kubernetes configmap, the problem seems to be related to how kubernetes configmaps are created and how grafana walk through the dashboards folder, k8s is using an [atomic writer](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/atomic_writer.go) which essentially is a time stamped folder with the real file in it and symlinks pointing to it in the root of the directory.

The issue was originally described into the grafana community forum into [this thread](https://community.grafana.com/t/duplicated-dashboards-while-importing-using-var-lib-grafana-dashboards/4467/5)

## Steps to reproduce the issue

Create a dummy configmap dashboard file like k8s would create it

```
root_dir="gf_troubleshooting"
timestamped_dir="..129812_22_12_14_05_20.630496560"

mkdir ${root_dir} && cd ${root_dir}
mkdir ${timestamped_dir}
ln -s ${timestamped_dir} ..data

cat > "${timestamped_dir}/dummy.json" <<EOF
{
  "timezone": "",
  "title": "The dummy dashboard",
  "version": 1
}
EOF

ln -s ..data/dummy.json dummy.json
```

The file system structure should look like this
```
.
├── ..129812_22_12_14_05_20.630496560
│   └── dummy.json
├── ..data -> ..129812_22_12_14_05_20.630496560
└── dummy.json -> ..data/dummy.json
```

Then run grafana and mount the dashboards folder
```
sudo docker run -it \
  --rm \
  -p 3000:3000 \
  -v $(pwd):/var/lib/grafana/dashboards \
  --name=grafana \
  -e "GF_SECURITY_ADMIN_PASSWORD=secret" \
  -e "GF_DASHBOARDS_JSON_ENABLED=true" \
  grafana/grafana:4.6.3
```

Browse http://localhost:3000 and find the dummy dashboard twice into the dashboard finder

![grafana_duplicated_dashboard](https://user-images.githubusercontent.com/9039085/34325709-f7de4a44-e891-11e7-83dc-c65f99dd92a9.png)

## My Analysis

At first glance seem like the issue is that `filepath.Walk` recursively looks for all files suffixed with .json which would cause the loop to include the file twice as shown below.

https://github.com/grafana/grafana/blob/7a06a47e63316d92eb477579469cdb4def46ee04/pkg/services/search/json_index.go#L88-L110

I was thinking into some solution but realized that there is potentially a major release on the way (5.0.0) with major changes on that code area, and without having empirically proved it because I was unable to make the (provisioning dashboard)[http://docs.grafana.org/administration/provisioning/#dashboards] to work at the first in v5.0.0-alpha from master try looks like this won't be a problem anymore in grafana 5.X.X based on code below, may be the same case for the unreleased 4.7 where changes into provisioning will be released.

https://github.com/grafana/grafana/blob/45eda16a8793df4404c87116f2dcf4083a330ba6/pkg/services/provisioning/dashboards/file_reader.go#L102-L107

I don't feel this is technically a bug, but if there is a chance to release for Grafana 4 I would be more than happy to provide a PR, otherwise I think I will wait for Grafana 5 to get release and be stable to try to adapt all major changes to the [public helm chart](https://github.com/kubernetes/charts/tree/master/stable/grafana) that I'm happily using.

Thanks!

**Comment by torkelo** [comment]
not sure I understand, it sounds like you have the file twice in the tree (one original, and one linked) so it will appear twice. Anyway the dashboard.json feature was removed in v5 and replaced with a dashboard as config (provisioning) feature that syncs dashboard files to grafana db

**Comment by snebel29** [comment]
Hmmm Yes the file is twice... but there is also a broader context involved with how kubernetes implement configmaps that are used to store configuration files for systems such as grafana :-) 

Never mind, I will wait for either the v4.7.3 or v.5.0.0 where the file reader algorithm already skip directories starting by dot like the one created by kubernetes configmaps.

Merry Christmas!
Thanks
