### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: tProvider <- t <- datasourceSrv <- dashboardLoaderSrv

### ISSUE THREAD

**Issue by sheguloves** [grafana/grafana#10333]
I install grafana in my mac by building from source, everything is done. I started grafana server and changed the port 3002, started chrome and viewed "http://localhost:3002". An error thrown in chrome console. "Error: [$injector:unpr] Unknown provider: tProvider <- t <- datasourceSrv <- dashboardLoaderSrv".

**Comment by torkelo** [comment]
thanks for reporting this, my mistake in PR merged yesterday. Fixed now
