### ISSUE TITLE
Hide a query directly in dashboard 

### ISSUE THREAD

**Issue by tsn77130** [grafana/grafana#10331]
Read before posting: 

Hi all

It should be useful to have same behavior that query editor’s eye to show / hide a query, directly on top of dashboard or panel , especiallay for viewers, which can’t enter into query editor.

It is not the same thing thak click on metric, because a panel can have " queries with 10 resultst for each (for example with group by), and it should be useful to hide 1 query (and 10 results) easily.

Please include this information:
- What Grafana version are you using?
4.6.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
linux debian
- What did you do?
Have possibility to hide query

thanks 

thomas

**Comment by torkelo** [comment]
If you use template variables you can change how many series your queries return from the top of the dashboard. Might not cover every possible scenario but I think for your use case it should be good enough
