### ISSUE TITLE
New datasource button is broken when grafana with root_path

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#10336]
Please include this information:
- What Grafana version are you using?
> 5.0.0-10969pre1
- What datasource are you using?
> Vertamedia Clickhouse
- What OS are you running grafana on?
> debian8
- What did you do?
i add
```
[server]
root_url = https:///ui/grafana/
```
navigated to https://172.28.128.27/ui/grafana/datasources
then clicked green button
![default](https://user-images.githubusercontent.com/289277/34326092-2eeb733a-e8b6-11e7-882d-1477ee9017e3.png)

- What was the expected result?
new datasource form will be shown
- What happened instead?
404

it seems that root url is not inserted cause i got https://172.28.128.27/datasources/new

**Comment by torkelo** [comment]
thanks for reporting this, will fix

**Comment by jancaster** [comment]
Hello,

I just want to report that the issue still persists on Grafana 5.0.0 beta1.
At least for the datasource green button.

I checked #10470 and it seems datasource path is not included in the PR.

**Comment by torkelo** [comment]
I fixed that as part of another change, 3 days ago, will be included in beta2
https://github.com/grafana/grafana/commit/0e61a670bb85312666b6ffac43507a0f99e9d030#diff-edc0d02a46b7bd550d81e139bb362f69L55
