### ISSUE TITLE
Refresh shorcut 'R' no longer working 

### ISSUE THREAD

**Issue by cout** [grafana/grafana#10332]
Please include this information:
- What Grafana version are you using? 4.6 and master
- What datasource are you using? any
- What OS are you running grafana on? Ubuntu 16.04 (both server and browser)
- What did you do? Create a dashboard, add a graph, press R
- What was the expected result? I expected the graph to refresh
- What happened instead? Nothing happened.

On grafana 3.0, I could press 'R' to refresh the dashboard as documented here: http://docs.grafana.org/reference/keyboard_shortcuts/

On grafana 4.6 and master, 'R' appears to no longer do anything.  Pressing '?' brings up a list of keyboard shortcuts; "r c" and "r r" are shown as "collapse row" and "remove row", but I have been unable to get those shortcuts to work either.

IMHO given that there is no documented keyboard shortcut for changing the currently focused row, the collapse/remove row shortcuts are less generally useful than refresh, which I used regularly on grafana 3.0.  (it's specifically useful when there are more graphs than fit on a screen, as scrolling down causes the refresh icon to scroll off the screen).  I would prefer to see 'R' restored as a shortcut for refresh, though if the benevolent oligarchy feels the focused row shortcuts to be more useful, I am willing to learn a new shortcut key for refresh.

As for the other shortcuts listed on the webpage:
* Esc works as expected
* F (find) does work, though it is only mentioned in the web docs and not in the on-screen help
* R (refresh) does not work
* Ctrl-S (save) works as expected and is documented in the on-screen help as Mod+S
* in chromium (on Ubuntu 16.04), Ctrl-H brings up web history instead of hiding row controls.  It is documented in the on-screen help as Mod+H, and Mod is documented as CTRL on linux.
* Ctrl-Z (zoom) works as expected
* Ctrl-O (enable/disable crrosshair) works as expected and is documtend in the on-screen help as Mod+O

**Comment by torkelo** [comment]
it's `d r`  was changed in v4
