### ISSUE TITLE
Backward incompatible 5->4.6

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#10337]
Please include this information:
- What Grafana version are you using?
5.0.0-10969pre1
- What datasource are you using?
vertamedia clickhouse
- What OS are you running grafana on?
debian 8
- What did you do?
i have dynamic templated dashboard made for grafana 4.6. i load it like that
```
    // Get dashboard configuration
    $.ajax({
        method: "GET",
        url: "https://172.28.128.27/pm/ddash/?" + $.param(args)
    }).done(function(result) {
        callback(result);
    });
```
I'm trying to test if my app is compatible with new grafana and find ways to do so. 
It loads well. but some panels shown not as expected. 
- What was the expected result?
dashboards panels placed as on previous version
- What happened instead?
dashboard panels is messed.
current one
![default](https://user-images.githubusercontent.com/289277/34326365-9fde297a-e8bb-11e7-8077-a520757f5016.png)
the same but on 4.6.3
![default](https://user-images.githubusercontent.com/289277/34326394-d15fd8ea-e8bb-11e7-97f7-e6487b7716db.png)
 
My dashboard crafted on my backend
[my_dash.txt](https://github.com/grafana/grafana/files/1584800/my_dash.txt)

Probably i have to change something to achieve the same dash. any docs/hints about it?

**Comment by torkelo** [comment]
the problem is the first panel, it has a height set to 50px. remove this property.

**Comment by freeseacher** [comment]
ok first panel looks fixed, and what about 4 panels instead of 2 ?
it has property of min width of 6. previously grafana has 12 columns. 
currently 24 columns. 
do i have to change it to 12 ?

**Comment by torkelo** [comment]
the dashboard has repeated panels. What is the value of the variable you repeat by? How many values selected?

> it has property of min width of 6. previously grafana has 12 columns.
> currently 24 columns.
> do i have to change it to 12 ?

No, that is handled by the migration

**Comment by freeseacher** [comment]
> the dashboard has repeated panels. What is the value of the variable you repeat by? How many values selected?

it's done with custom query  `"query": "bridge,ether1,ether2-master,ether3,ether4,ether5,sfp1,wlan1,wlan2"`

By default nothing is selected so previously it was like selecting all. currently it is also selecting all. but 
  "minSpan": 6 have to be changed to  "minSpan": 12


i do not have any saved dashboards. Cause my dashboards are crafted on my backend side. Dynamic dashboards.
so i have to do migrations by myself. here the code of templates https://github.com/nocproject/noc/tree/microservices/templates/ddash

**Comment by freeseacher** [comment]
between grafana_5.0.0-10984pre1_amd64.deb (7e55509) and grafana_5.0.0-10985pre1_amd64.deb (8fb0692)
something has happend and my dynamic dashboard loader had been broken. 
here is the code 
https://github.com/nocproject/ansible_deploy/blob/microservices/ansible/roles/grafana/templates/noc.js.j2

as for now that code is loaded but not executed.
