### ISSUE TITLE
When switching datasource, repeated templated values are buggy

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10340]
1. Setup 2 prometheus datasources
2. Setup a template, multi = true, includeall = true, and all as default
2. setup a repeated singlestat on that variable
3. switch datasources

Inital panels:

![rpt2](https://user-images.githubusercontent.com/291750/34329840-f00892f6-e90f-11e7-8f53-0b24a435fb94.png)

After changing datasource:
![rpt](https://user-images.githubusercontent.com/291750/34329841-f0254e3c-e90f-11e7-82ce-ef6c456c35aa.png)

Expected:

![rpt2](https://user-images.githubusercontent.com/291750/34329840-f00892f6-e90f-11e7-8f53-0b24a435fb94.png)

**Comment by torkelo** [comment]
Strange, unable to replicate this. Can you open chrome dev tools > Console, any js errors? 

Also when you change data source variable what network requests are made and what are the responses?

**Comment by roidelapluie** [comment]
I have the same with query templates.  Will do a further investigation.

**Comment by roidelapluie** [comment]
This was because I was using a panel with id=0 and id=1.

Fixed in grafonnet.
