### ISSUE TITLE
Sometimes the value of template variable isn't displayed correctly on panel

### ISSUE THREAD

**Issue by ahrtr** [grafana/grafana#10341]
I defined a template variable named "tenant" as below, in which "my_call_count" is a prometheus metrics of the type counter,  
 `label_values(my_call_count, tenantid)`
All the values can be listed successfully at the top of the dashboard.

Afterwards, I created a Singlestat panel, and set the title of the panel as $tenant.  What I expected was that the selected vlaue should be displayed as the title of the panel singlestat.  Sometimes it worked; but sometimes, it didn't, the string "$tenant" instead of the value was displayed directly.

Grafana version: v4.6.2
Datasource: Prometheus
OS on which running grafana: Oracle Linux Server release 7.3

**Comment by torkelo** [comment]
Strange, this has never been reported before. Can you open chrome dev tools Console and see if you see any js errors when this happens?

**Comment by ahrtr** [comment]
I have already fixed this issue, although I don't know the root cause. 

I noticed that the issues happened each time there were some empty tenantid. So the workaround is to make sure there are never any empty tenantid.
