### ISSUE TITLE
Elasticsearch as timeseries datasource

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#1034]
I'm aware of #158, but in this issue I want to discuss whether Elasticsearch is a good fit for storing timeseries data and whether grafana's graph panel should support fetching timeseris data from elasticsearch. I'm not suggesting that grafana should also implement features like log analytics.

Elasticsearch offers the [date_histogram](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_looking_at_time.html) aggregation that could be used to feed the graphs. When comparing the available [aggregations](http://influxdb.com/docs/v0.8/api/aggregate_functions.html) elasticsearch has to offer to InfluxDB's [aggregate functions](http://influxdb.com/docs/v0.8/api/aggregate_functions.html), you can see, that they are quite simmilar.

One could argue, that if InfluxDB already offers this features, why add 'yad' (yet another datasource)? Even though it looks like InfluxDB's development is moving fast, I think that elasticsearch is a more mature, easier to scale scaleable, and easier to install and operate. Also, because it's based on Java it just runs anywhere, even Windows and Solaris for example.

Besides, a lot of people already use elasticsearch to store the dashboards and add annotations to the graphs. If elasticsearch could also be used as a timeseries datasource, you would just have to install one database which again reduces time and cost to install and operate the system.

Because you would store metrics in a json format, the ideas described in [metric 2.0](http://metrics20.org/) could be incorporated. 

A metric document could look something like this:
```
{
	"@timestamp" : "2013-07-20T09:43:58.000+0000",
	"name" : "bulk-request-timer",
	"tags" : {
		"application"  : "my awesome app",
		"host"  : "host-1",
		"datacenter"  : "dc1"
	},
	"values" : {
		"count" : 114,
		"max" : 109.681,
		"mean" : 5.439666666666667,
		"min" : 2.457,
		"p50" : 4.3389999999999995,
		"p75" : 5.0169999999999995,
		"p95" : 8.37175,
		"p98" : 9.6832,
		"p99" : 94.68429999999942,
		"p999" : 109.681,
		"stddev" : 9.956913151098842,
		"m15_rate" : 0.10779994503690074,
		"m1_rate" : 0.07283351433589833,
		"m5_rate" : 0.10101298115113727,
		"mean_rate" : 0.08251056571678642
	}
}
```

Finally, I think that these features should rather be added to grafana than to kibana. IMHO kibana's focus just isn't displaying metrics but analytics. For example, it is not possible to add multiple graphs to one panel. For instance, if you wanted to display multiple percentiles of the response time in one panel, that's just not possible. Also there is no such functionality like grafana's templated queries. That could be implemented in grafana by performing a terms aggregation e.g. on the `host` field to populate the dropdown with all available hosts.

I think @Dieterbe already experimented using elasticsearch as a timeseries database for his graphite-ng project. What are your experiences and thoughts about my thoughts? @torkelo what do you think about all of that?

**Comment by iy-propeller** [comment]
++

**Comment by sunyc** [comment]
+10, would be good to directly import visualizations from kibana4.

**Comment by theduderog** [comment]
@gebrits @felixbarny, I'm using Druid for this type of use case.  You can pre-aggregate data at index time (for records where all dimensions have the same value) and choose what level of time granularity you want to store data at (ms, second, minute, ..., hour, day).  At query time, it does very fast filtering and aggregations, including approximate histograms, percentiles, and uniqueness counts.

This is the Druid plugin I created for Grafana.
https://github.com/Quantiply/grafana-plugins/

**Comment by bechtoldt** [comment]
+1 for metrics support

**Comment by crudbug** [comment]
:+1:

**Comment by agaon** [comment]
+1 for metrics support

**Comment by KingOfPoptart** [comment]
:+1:

**Comment by yehosef** [comment]
+1 - this would be great! Grafana seems much more powerful than kibana right now.

**Comment by howie** [comment]
+1

**Comment by kenhuang** [comment]
+1

**Comment by GuitarrasDeAmor** [comment]
+1, would really love this to happen. We're using Collectd ---> Riemann ---> Elasticsearch and logstash ---> ES ---> Kibana, I'd love to be able to put Grafana in front of our Collectd stats to visualize them easier.

**Comment by ssoto** [comment]
@GuitarrasDeAmor  you can put Grafana in front of you collectd metrics with OpenTSDB:
http://docs.grafana.org/datasources/opentsdb/

**Comment by papaonlegs** [comment]
+1 for metrics support

**Comment by Shumkov** [comment]
+1

**Comment by portante** [comment]
See also: https://github.com/distributed-system-analysis/es-graphite-shim

**Comment by GuitarrasDeAmor** [comment]
Currently, we (our company) is working on an ES ---> Grafana plugin for our internal usage, and plan to contribute it when done.

**Comment by AdrianParente** [comment]
+1 why I'm on this thread.

I'm doing due diligence. I have to run ES in Production:
1. ES Can store this data as it stands, it would be nice to have a mode that expects timeseries metrics.
2. ES Already supports distributed queries.
3. ES Can scale up horizontally automagically.

**Comment by arcolife** [comment]
@AdrianParente hope this works for you -> https://github.com/distributed-system-analysis/es-graphite-shim ..Its a shim that mocks a graphite instance, to connect Grafana's time-series queries to an ES instance.

**Comment by lakshmanav** [comment]
:+1:

**Comment by felixbarny** [comment]
I did some measurements that had some unexpected results: if you tune Elasticsearch, it is even more storage efficient than InfluxDB: https://discuss.elastic.co/t/elk-vs-grafana-influxdb/1686/25. The CERN also did a ES vs InfluxDB vs OpenTSDB benchmark. They found that Elasticsearch scales better than InfluxDB and OpenTSDB for their high-scale time-series analytics use case.

So what is the advantage on InfluxDB then? As far as I can see it is only the better visualisation support -> Grafana and things like continuous queries that you could use to downsample old data to reduce storage space.

Elasticsearch seems to have better support for sophisticated queries/functions through aggregations (moving averages and hold-winters is in the pipeline for 2.0!). The biggest advantage I see is that it is much more mature and scaleable. InfluxDB's clustering API currently is in alpha state and you shouldn't form a cluster with more than 3 nodes. I doubt that they will ever catch up with Elasticsearch in this area. There is just so much more money and manpower behind Elastic. I really hope that Grafana will at some point support Elasticsearch. Otherwise you might loose users that can't use Elasticsearch with it to Kibana.

**Comment by elvarb** [comment]
I'm starting to think that supporting elasticsearch is a really really good idea. It could end up to be the perfect platform for context based metrics, metrics 2.0

**Comment by bechtoldt** [comment]
@elvarb indeed, it is.

**Comment by JozoVilcek** [comment]
+1

**Comment by StefanSa** [comment]
+1

**Comment by philipz** [comment]
+1

**Comment by warroyo** [comment]
+1

**Comment by jmaitrehenry** [comment]
+1

**Comment by aheinz-sg** [comment]
We've been using Grafana + Elasticsearch in production for a couple months now without any trouble. I've made some more improvements to https://github.com/grafana/grafana/pull/2293 and will be deploying the new stuff to production this week.

**Comment by torkelo** [comment]
@aheinz-sg are the improvements added to the #2293 pr ?

**Comment by aheinz-sg** [comment]
Yes. I rebased this morning so all my commits grouped together. The top four commits have been running in production for two months and the bottom four are my recent improvements.

**Comment by torkelo** [comment]
that is great, will try to test it this week

**Comment by torkelo** [comment]
This is going to to be included in next release! 

Not done yet, but starting to look good. 

![elasticsearch4](https://cloud.githubusercontent.com/assets/10999/9661128/9c7325ce-5259-11e5-9ec9-383c08ac3dd7.gif)

You can select multiple aggregations in single series (aggregations other than count need to be numbers datatype in elasticsearch).

You can also add multiple group bys (nested terms in elasticsearch speak)

**Comment by felixbarny** [comment]
nice!

**Comment by elvarb** [comment]
Time to migrate metrics to elasticsearch!

**Comment by fhelje** [comment]
Beautiful any specific version of elastic needed?

**Comment by torkelo** [comment]
@fhelje not sure, aggregations are required, tested with 1.7 but could work with 1.5+

**Comment by yehosef** [comment]
great!

**Comment by bechtoldt** [comment]
nice!

**Comment by syepes** [comment]
Can't wait as InfluxDB is starting to be a pain!

**Comment by rmoff** [comment]
Awesome :+1:

**Comment by jomar83** [comment]
@torkelo Great work! Any eta on this? We're really interested in trying grafana backed by es.

**Comment by torkelo** [comment]
@jomar83 I think I will merge it to master on monday, so will be available in Grafana v2.2 pre release builds 10min after that. 

I hope to release stable Grafana v2.2 in the end of september.

**Comment by felixbarny** [comment]
Wake me up when september ends

**Comment by hashar** [comment]
@aheinz-sg Kudos! That is going to be a killer feature :-}

**Comment by felixbarny** [comment]
I'm playing around with the es support in the elastic_ds branch and I have some notes/wishes:
 * It would be great to be able to limit the "group-by" aggregation (size of the terms aggregation). One usecase would be "Show me the slowest 5 requests". For this to work, the date_histogram aggregation has to be underneath the terms aggregation. Otherwise ES would return the top 5 in each time bucket as supposed to the top 5 of the entire timeframe.
 * Do we have to use the json input for more sophisticated aggregations? Some build ins would be nice. For example for the upcoming ES-2.0 [pipeline aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline.html) like [derivatives](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline-derivative-aggregation.html) (quite essential) and [moving averages](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline-movavg-aggregation.html)
 * Templating: It would be great if they would work like the filters in kibana - when you select one, a filter gets applied to all queries of the current dashboard.

**Comment by torkelo** [comment]
@felixbarny thanks for trying out and for giving me feedback, much appreciated! 

1) Can you describe more about the group by limit/filter, show example query? 

2) I want to add more aggregations (like standard deviation, percentiles etc),  have not looked at the Es 2.0 pipeline stuff yet, will do, thanks for the tip. 

3) Templating, yes, I want to support templating for most stuff. You will be able to have template variable that can be used in all lucene queries for all graphs, that way you can enter a lucene query and filter all graph queries. Other ways to use templating would be to fill a template variable with available fields so you can select field globally in the dashboard, and if that is used in the queries they will update.

**Comment by felixbarny** [comment]
I'll try to explain it with some kibana screenshots:

This is the correct way: 
![bildschirmfoto 2015-09-04 um 11 37 48](https://cloud.githubusercontent.com/assets/2163464/9680769/823117de-52f9-11e5-8583-8e461cecfce2.png)
The date_histogram aggregation is underneath the terms aggregation. This makes sure that only 5 request_names are shown, which are the slowest in the last 4 hours.

Wrong:
![bildschirmfoto 2015-09-04 um 11 38 16](https://cloud.githubusercontent.com/assets/2163464/9680773/84c18592-52f9-11e5-8588-550e7b76a15f.png)
The date_histogram aggregation is above the terms aggregation. That way the slowest requests in each time bucket (5 seconds in this case) are shown. That means that there can be more than 5 request_names.

**Comment by jomar83** [comment]
+1 for recommending pipeline aggs. That is one of the most important features in es 2.0 and isn't even supported in kibana 4.2 beta. It would be great if you would have it ready from the get go.

**Comment by felixbarny** [comment]
Oh, and one more thing. It would be great if grafana could support time-based indices. For example `[stagemonitor-metrics-]YYYY.MM.DD` that way elasticsearch only has to search in the index of the current day if the timespan is -6h for example instead of searching in all indices (possibly years of metric data).

**Comment by elvarb** [comment]
+1 for support for time based indices, essential feature because doing a delete query to remove old data is not optimal

**Comment by torkelo** [comment]
@felixbarny thanks now I understand what you mean. 

Does it ever make sense to do date_histogram first or should that always be last?

**Comment by felixbarny** [comment]
I can't think of a case where this would make sense. I'd start with always applying it last.

**Comment by torkelo** [comment]
@felixbarny yea that was what I was thinking as well. Looking into making the editor more sophisticated now so you can set sort / and limit on group by as well as customize metric aggregations (some, like percentiles and the new piped aggregations require more settings than just the field).

**Comment by arcolife** [comment]
@torkelo hi ! any chance you've tried out http://github.com/arcolife/es-graphite-shim ? I know it doesn't offer native support, but it also supports feature requests like timeseries indices of ElasticSearch. Have been working on it recently and it could offer other improvements too. Like it also supports caching, logging and such. An alternate should be nice too right? ;) Thanks!

**Comment by warroyo** [comment]
+1 for time-based indices, I am looking forward to this being released and this is a must have for it to work with out current setup. this also allows for searching over smaller sets of data. `[stagemonitor-metrics-]YYYY.MM.DD` like @felixbarny  said. This has been supported in kibana for a while and I think there will be a lot of people requesting this.

@torkelo thanks for the hard work on getting ES integrated!

**Comment by felixbarny** [comment]
The time-based index thing relates to #1202

Two more wishes (you probably already have planned this)
 * Aliases for graph names
 * Auto completion of field names (seems to work on your gif but not in the branch)

And by the way, you are awesome!

**Comment by torkelo** [comment]
Been working on this non stop (with little sleep), been so fun trying to make the editor support all of the awesome metrics features in Elasticsearch. 

Have done some substantial changes in query editor and processing to support group by term options (like size, order by, etc). You can order by and reference a metric aggregation. 

![elastic_query_editor_take2](https://cloud.githubusercontent.com/assets/10999/9699540/e2e57744-53e6-11e5-8f64-bcf80c713bdf.gif)

Ignore the gif animation color artifacts due to the encoding. Anyway its looking very good. Next up is supporting Percentiles metric aggregation & Standard deviation (Extended stats). Will also look at alias patterns (series naming), and querying each index individually via day or time pattern like `stagemonitor-metrics-]YYYY.MM.DD`

**Comment by felixbarny** [comment]
I think I know why the auto completion of field names isn't working for me. I have deactivated the _source in my mapping to save disk space. Unfortunately I can't type in the field name manually so I can't really test anything more. Even with activated _source not all fields are available in the drop down.

A better source for the field names might be the [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html). All fields of a particular index are stored there. But it's important to make sure that new fields are also picked up (Kibana fails to do this). Using the mapping information you could even only allow number fields to be selectable for metrics.

**Comment by torkelo** [comment]
why cant you type in the field name manually?

Yea, looking at the mapping could be a good option. But is everything there or just specifically specified indexing rules? Cant recall.

**Comment by portante** [comment]
FWIW, I agree with @felixbarny regarding field names from mappings.  That is what @arcolife has done in http://github.com/arcolife/es-graphite-shim, this queries ES for the mappings and passes them on to Grafana as if it is a Graphite instance.

The same idea could be used here.

**Comment by portante** [comment]
@torkelo, I believe everything is there that ES has been told up front and what it has seen so far.  If someone is adding fields over time to an index, then those fields would be made available when Grafana pulls the updated mapping (I would think).  So Grafana would just need to periodically check for a mapping update.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9700229/e8cb1334-53fb-11e5-8767-9b3161c50989.png)

Yay, percentiles are working.

**Comment by felixbarny** [comment]
I can type them in but they get erased when the input looses the focus. In the first draft this has been working though. 
Dynamically added fields are in the mapping as well.

**Comment by torkelo** [comment]
Switched to fetch fields from mapping instead :) 

@felixbarny I fixed  the issue with not being able to enter custom value. You should be able to do that now for fields.

**Comment by portante** [comment]
@torkelo, sweet!

**Comment by felixbarny** [comment]
I would suggest not using the relative timespans like now-6h in the queries as it requires the server to have the correct time set. For example, if you are running Elasticsearch in boot2docker the time is wrong if your device goes into sleep mode. Using absolute timestamps would help here.

Even if there is only a short time missmatch between client and server, the start and end of the graph might not be populated correctly.

**Comment by elvarb** [comment]
Definitely include now-6h because you should definitely use ntp, you should always use ntp

**Comment by felixbarny** [comment]
Yeah, you should, but the reality is different (for example boot2docker). What is the advantage of now-6h? I can only see disadvantages.

**Comment by felixbarny** [comment]
Templating:
For now, it's only possible to select the field names like `application`, `host`, `value`. It would be cool to be able to fill the values with a terms aggregation of a field. For example all terms of `host`.

**Comment by torkelo** [comment]
@felixbarny 

I think using relative times when possible is good. Your elasticsearch machine / container should have the correct time. I dont think any real installs will be running boot2docker, only local dev env. 

for templating, I agree unique term values is a must, have not started on templating at all, only support metricFindQuery options required by the query editor so far.

**Comment by felixbarny** [comment]
This is more about developer experience. I was quite confused why Kibana displayed the graphs correctly when Grafana didn't. I guess I won't be the only one. Why are relative timeframes better?

**Comment by torkelo** [comment]
because it is more likely that your local computer has incorrect time than the server :)

**Comment by yehosef** [comment]
+1 relative times.  But yes, ES /marvel has lots of problems without ntp so I think it should be assumed.

**Comment by portante** [comment]
FWIW, we work to ensure our metrics are timestamped with UTC values, this solves many problems.

+1 for relative times in UI (as the UI can convert to queries using absolute times).

**Comment by torkelo** [comment]
Added index time patterns

![image](https://cloud.githubusercontent.com/assets/10999/9705301/dcbdcd96-54c0-11e5-99ad-55fdca81682b.png)

next on todo list is alias (series naming) pattern, and templating

**Comment by jomar83** [comment]
@torkelo great work so far thanks, we're already testing it. Two things: 

Can you add "unique count" to the possible aggregations please. 

Also, what is really bad about kibana is the fact that it will show you all fields for creating a chart, even when you limit the scope to a certain type (filter by doc type). Since you're using the mapping for autocompletion it would be great if there was an option to add a type filter, that would also limit the autocomplete scope to that mapping type. 

Right now in kibana this is a nightmare if you have multiple types in an index with many different fields and it shows you 100 different fields you don't really care about, cause u already filtered on a certain type.

**Comment by elvarb** [comment]
Regarding disk space and elasticsearch, it already is very efficient on disk space but for really old data is there some way to downsample metrics? 

Would it maybe be feasible to use logstash to read one index and save a downsampled data into a different index?  Or maybe the same index and then use a delete query for the old data.

**Comment by jomar83** [comment]
Deleting huge amounts of documents is generally not recommended, because it is a very expensive operation. It is much better to partition your data in daily indices and compact them once that's required (using logstash is an option for that). Afterwards drop the compacted indices. In terms of performance it is much cheaper to drop an entire index.

**Comment by elvarb** [comment]
I know it's definitely not ideal to do it like that but if you want to view metric data for 1 year that query is going to be very heavy on the cluster. The points would be around two a day and it would have to query so many indices.

**Comment by torkelo** [comment]
Extended stats now works (Single metric aggregation where you can select all kinds of stats, like standard deviation , upper and lower bounds for standard deviation as well as specify sigma)

![image](https://cloud.githubusercontent.com/assets/10999/9715615/5cbbd06e-5562-11e5-9db7-2dfb7ccb0e02.png)

**Comment by torkelo** [comment]
Alias patterns are now imlemented, 

```
{{term fieldname}} = replaced with value of term group by
{{metric}} = replaced with metric name (ex. Average, Min, Max)
{{field}} = replaced with the metric field name
```

![image](https://cloud.githubusercontent.com/assets/10999/9728582/3e6d108a-5609-11e5-85b0-7ef6de4a3f87.png)

**Comment by jomar83** [comment]
works great, thanks!

**Comment by torkelo** [comment]
I think the implementation and query schema is approaching stability and most query features seem to nr working, except templating.

I have merged this to master, and building new pre release builds (next version is now going to v2.5 since its to many new big features in vnext so I feel like bumbing the version a little more) 

http://grafana.org/download/builds.html

I would love for more to test this out and open NEW issues for problems and improvement ideas. I will open a seperate issue for templating features.

**Comment by torkelo** [comment]
deployed latest to play.grafana.org/master

Simple demo dashboard & metrics
http://play.grafana.org/master/dashboard/db/elasticsearch-metrics

**Comment by portante** [comment]
@torkelo, I tried loading play.grafana.org/master and the "Elasticsearch Metrics" was empty, and clicking on it, took me to a totally blank page.  Perhaps it does not like Chrome, or I don't have proper access?

**Comment by portante** [comment]
@torkelo, well, after about 2 minutes, the page loaded, but the three graphs were blank, and in the top left corner, the exclamation mark mouse over popped up, "Cannot read property '3' of undefined" for the top graph, and "Cannot read property '2' of undefined" for the other two.

**Comment by torkelo** [comment]
@portante that is strange, works great here (stockholm) and from the US

Do you get any request errors in the chrome dev console?

**Comment by portante** [comment]
No errors in the console, the "Simple demo dashboard & metrics" loads fine now.  The main page still has three blank screens across the top.

![image](https://cloud.githubusercontent.com/assets/949097/9754177/83155b44-5694-11e5-9e2e-086c08d6c19b.png)

**Comment by torkelo** [comment]
@portante that is the home dashboard, the reason the dashboard list panels are empty except for the single elastic dashboard is because that is the only dashboard in this grafana install :) 

But does this dashboard still give you errors? 
http://play.grafana.org/master/dashboard/db/elasticsearch-metrics

What browser and os you using?

**Comment by portante** [comment]
I was using Chrome on Mac OS X (10.10.5).

I think it is fine now, no errors in the console: 
![image](https://cloud.githubusercontent.com/assets/949097/9754254/2f759174-5695-11e5-94b5-d4754512c67c.png)

**Comment by aodj** [comment]
I've been playing with v 2.5.0-pre1 and the Elasticsearch integration is very nice. I've only run into a few things so far, which I'll itemise here:
* using date histograms with fields other than `@timestamp` doesn't seem to work. I've had to switch to editing the Lucene JSON and swap out from `@timestamp` to 'event_time' (as is the case in the data I'm using). I've a gist of the resulting JSON [here](https://gist.github.com/aodj/0ba7a4225d7994f430a2#file-lucene-json).
* Switching to the alternative editor mode loses you the ability to add in aliases for trends and set intervals
* Searches that work in Kibana for returning multiple datasets don't work in Grafana. For example, if i want to show a count of all records, and a count of records that have a field name (in my case `errname`) I could do `Split Lines` aggregation with a filter for '*' and another for '_exists_errname' (see [here](https://imgur.com/6iYDylB))

Otherwise, this is a really nice update and being able to make use of Grafana to graph data from ES is wonderful. Thanks so much!

**Comment by torkelo** [comment]
@aodj thanks for your feedback! Will try to improve the editor, and fix the issues you have encountered. 

You should be able to set the timestamp field when you add the data source

**Comment by aodj** [comment]
Ah, yes, changing the timestamp field in the datasource fixed that; I didn't set that up myself, hence why I didn't think to tweak it :+1:

**Comment by aodj** [comment]
As a word of warning, I managed to horribly crash my ES cluster by querying for too much data, causing an OutOfMemory error for the Java heap. I think Kibana has some mechanism that stops you from requesting too many data points, by scaling the interval value, probably to avoid this scenario.

**Comment by torkelo** [comment]
the date  histogram interval is scalled automatically when set to auto.

Yes it is very easy to crash Elasticsearch, for example by using a terms histogram with a field with high cardinality

**Comment by torkelo** [comment]
@aodj 

added support for filters aggregation 
![image](https://cloud.githubusercontent.com/assets/10999/9996615/16c4df8e-6088-11e5-8559-cbaaa58dea03.png)

Also fixed so you can use alias and lucene query when in raw json query mode 

https://github.com/grafana/grafana/issues/2785

**Comment by felixbarny** [comment]
I have a strange problem when using a `Sum` of a metric. Each server periodically reports the number of open sessions. In the dashboard, I want to see the total count of all sessions across all servers. But even if only one server is online that has one session, the count is wrong (it is higher). The reason for this is probably that Elasticsearch sums all values of a given time bucket. So if I report every second and the time buckets (the interval) are 30 seconds, grafana shows 30 as the session count. Can someone help me?

**Comment by torkelo** [comment]
@felixbarny you should use average or max in that case

**Comment by felixbarny** [comment]
But when I have 3 servers with one session each, what I'm typically interested in is that I have 3 sessions in total not that i have 1 session in average.

**Comment by torkelo** [comment]
to solve a case like that we have to scale the values depending on the time range (date histogram interval), 

Not sure elastic has a built in mechanism for this or if it needs to happen all in grafana

**Comment by felixbarny** [comment]
What do you exactly mean by that? How would that work?

**Comment by felixbarny** [comment]
@aodj @torkelo I would try using [doc values](https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html) to mitigate the high memory consumption.

**Comment by felixbarny** [comment]
I've posted a question on stackoverflow about this. Hopefully this can be solved. If not, it would be a big drawback of using Elasticsearch as a TSDB :(

http://stackoverflow.com/questions/32761614/sum-count-of-sessions-with-kibana

**Comment by elvarb** [comment]
I think the solution for you is buckets, you first split the query by hostname and then use avg sessions. That way you get as many results as you have servers, then in the graph you stack the results.

**Comment by yehosef** [comment]
I answered there - You should take the average aggregation and then multiply it by the number of servers.  This will compensate for the time and give you average/per server number.  Then you multiply by num servers to get avg for the cluster.

**Comment by 1tft** [comment]
+∞ Elasticsearch as data source! (because InfluxDB is so unstable)

We used to use a query like ... WHERE  "value" <= 15 AND "value" > 0 AND "servername" = ... for a grafana InfluxDB query.
Purpose, I want to define different (stacked) series which only shows a filtered range.

So my question, is it possible to define a query (in Grafana for Elasticsearch data source) including a statement like ... WHERE  "value" <= 15" ... to filter data on value base?

**Comment by felixbarny** [comment]
The lucene equivalent would be `value: [* TO 15]`

**Comment by 1tft** [comment]
@felixbarny Thank you, awesome this seems to work!
More than one reason to migrate finally from Influx to elastic...

**Comment by Yumeji** [comment]
I'm getting the 'cannot read property length of undefined' (same error as https://github.com/grafana/grafana/issues/192) when I (1) Add my data source, and (2) Add my first graph. I'm new to grafana so presumably I'm missing something obvious but I can't imagine what. There is definitely nothing wrong with the elasticsearch installation as it is used in production. Is there a guide somewhere describing elasticsearch + grafana? Thanks much for your work.

**Comment by torkelo** [comment]
@Yumeji check chrome dev console network tab, any elastic request / response that can be relevant there for troubleshooting?

**Comment by Yumeji** [comment]
Sorry for the delay in getting back to you. When I tried readding the datasource it worked. However I also seem to have had problems using a time field other than @timestamp. This might be my error but just throwing it out there in case it's something you haven't tested. Haven't had the time to set things up thoroughly.

**Comment by felixbarny** [comment]
I wrote a blog for Elastic about how to tune ES for using it as a TSDB: https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store

**Comment by 1tft** [comment]
Hello Felix, thank you for this great article. We are also looking deeper into elastic (2.0) as TSDB in comparison to KairosDB. Later I can post our performance test results and experiences with the collectD connection via logstash.
You wrote: index=no for all metric values. This reduces the index size but also means you can't search the values. I don't think its always fine because somtimes you want to count all values e.g. higher than 3s (and lower than 6s) and graph this count. So you can determine SLA issues etc.?!

**Comment by 1tft** [comment]
Anybody know how a working query for a template variable for elasticsearch in grafana looks like? I tried a query like { "MATCH" : { "HOST" : "hostname" } } but it doesn't work. Maybe templating is not yet working for elastic in Grafana 2.5 ?

**Comment by felixbarny** [comment]
That's why I've called it an aggressive optimisation. 

See #2696

**Comment by felixbarny** [comment]
But in your example you could perform a max and a min aggregation over your series and check whether the value is over 6/under 3.

**Comment by 1tft** [comment]
Today I tried felixbarnys mapping suggestions from elastic blog post, thank you felixbarny for sharing your knowledge!  For information: with index=no setting for string fields (tags) like "hostname" [query e.g. {"find": "terms", "field": "hostname"}] ( grafana produced no datapoints using these fields as query filter or lucene template queries. I don't know if Kibana use other queries against ES so that you can set index=no for such string fields where you know the exact values.

Next week I will send millions of datapoints to our elasticsearch and check performance. I have 3 physical ES 2.0 nodes with 128GB RAM and fast SAN storage (unfortunately no SSDs). I will use < 32Gb heap memory for ES to benefit from the compressed ordinary object pointers.

**Comment by felixbarny** [comment]
That's why in the dynamic mapping for all strings, I'm setting `"index": "not_analyzed"`. I think I didn't stress this point enough. This is indeed needed to filter by tags.

**Comment by anudharm** [comment]
How do we add template variables on grafana while using elastic search as datasource. Trying to move away from Influx as its being a pain. With Influx backend,  we have grafana dashboards with hostnames as template variable. Filtering based on hostname, shows metrics dashboard for particular host.
How do we achieve the same thing on grafana with elasticsearch as data source?

**Comment by 1tft** [comment]
@anudharm see #2696 for further details. I use metric docs containing data like this:
{
"@timestamp": "1442165810000",
"metricname": "cpu_user",
"application": "oracledb",
"hostname": "my.hostname",
"value": "80.4"
}

I have to use @timestamp in unix time epoch in miliseconds. Regarding felixbarnys elastic blog post, he manged to use unix time epoch in seconds.
Than I use this template query: {"find": "terms", "field": "hostname"} specified for template variable $hostname which you can use now in you metric filter etc..

**Comment by 1tft** [comment]
@felixbarny Thank you for clarification. I used your suggestion regarding setting index=not_analyzed for all string fields but also set index=no for my hostname string field. That doesn't work. Now I only use the index=not_analyzed for all string fields and this works.

**Comment by anudharm** [comment]
@1tft Thank your the pointers. That really helped. Is there a way to filter the template variable based on another variable with es based templating? We have racks and nodes in our deployment. If a user selects a rack, the node dropdown would just show nodes in that specific rack. With Influx we had host list as 

show tag values from HostInfo with key=HostIp WHERE Rack = '$Rack'

**Comment by anudharm** [comment]
Hi,

Thanks, figured that out! Using  "query":lucene query helped in that.
{"find": "terms", "field": "hostip", "query": "rack:$Rack"}

I know grafana currently supports only "terms" based queries. Wouldn't it be easy to add "term" based query (not-analyzed string field)? With these template variables the terms being returned are analyzed strings (strings separated by unicode character) and not exact strings.

**Comment by 1tft** [comment]
@anudharm I don't understand exactly what you want. At the moment queries against not_analyzed fields are working and also tried a template query against "value" field which is float and indexed and it is also working.
Is your template query  {"find": "terms", "field": "hostip", "query": "rack:$Rack"} working?

**Comment by bechtoldt** [comment]
Can you submit separate issues please? This issue is closed for some time.
