### ISSUE TITLE
New Multi-Stat Panel

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10358]
Use case to be able show many stats or small graphs in one panel. Singlestat panel is very inefficient as each panel issues it's own queries.

## Multi stat panel basic requirements 
1) Support horizontal and vertical layouts
2) Support different layout configurations 
3) Support bars (horizontal gauge and thresholds) 
4) Support small graphs 
5) Maybe a trend option (to show percent up/down) 

### Design ideas and inspiration 
![](https://user-images.githubusercontent.com/10999/34377968-f35c2e1e-eaf3-11e7-8dab-35bd1e409ed6.png)'

![](https://user-images.githubusercontent.com/10999/34377981-036b92d6-eaf4-11e7-9f36-1136afb78886.png)

![](https://user-images.githubusercontent.com/10999/34377972-f8096396-eaf3-11e7-9c76-ce11fdd4fd78.png)

![](https://user-images.githubusercontent.com/10999/34378078-7d27aa9c-eaf4-11e7-9476-2107c07d97af.png)

Mockup C
![multistat!UNITO-UNDERSCORE!test](https://user-images.githubusercontent.com/23470681/36731189-4886c00a-1bca-11e8-925b-678667dc7598.png)

Todo & Decisions 

* [ ] Create a new panel named multi-stat 
* [ ] Try write as much as possible in React 
* [ ] Support singlestat mode
* [ ] Support bar guage mode 
* [ ] Try to reduce duplication in data prep/handling code between singlestat,table,graph & multistat 

Options:

* Layout [Stat, Stat+Sparkline, Stat+Full Graph (future layout option), Honeycomb (future layout option)]
* Layout direction (Horizontal, Vertical) 
* Unit 
* Stat (min/max/avg/etc)
* Font size (auto/small/medium/large)

Thresholds:

* Array (so you can have n+) 
Instead of having an operator (like greater than or less then) we can sort the threshold rules so that it always greater than. So the lowest threshold is always fist. 
* Option for what the thresholds should be applied to (background, value, etc) should live outside the threshold rules. 

So example: 

```json
{
"thresholds": [
{
"value": 40,
"mode": "custom",
"color": "#bf1b00"
},
{
"value": 60,
"mode": "critical",
}
]
]
```

mode: ok, warning, critical, custom

Requirement / Design todo

* [ ] How to define thresholds?
* [ ] How to define colors (automatic / interpolated based on thresholds, or user defined)?
* [ ] Maybe flesh out conditional formatting feature, https://github.com/grafana/grafana/issues/11418

**Comment by Diegonarducci88** [comment]
This improvement in single stat I wait a long time, I always found it very limited, I'm looking forward to this improvement

**Comment by mattttt** [comment]
Another piece of inspiration, would be nice to use for repeating stat panels:

![screenshot 2018-01-17 17 07 58](https://user-images.githubusercontent.com/2886187/35052893-fe524ea0-fba8-11e7-80e4-004f200d9733.png)

**Comment by JamieSu0419** [comment]
We also need this feature

**Comment by torkelo** [comment]
Settings model WIP:
```js
{
  direction: "vertical|horizontal",
  template: [
    { 
        type: 'bars', 
        elements: [
           { type: 'metric-name' },
           { type: 'stat', value: 'avg' },
        ]
    }
 ],
  anotherLayoutExample: [
    {          
        type: 'container', 
        direction: 'vertical', 
        elements:  [
              { type: 'metric_name'  },
              { type: 'stat', value: 'avg' },    
      ]
    },
    { type: 'bars' }
 ],
}
```

**Comment by Ijin08** [comment]
Here are some design ideas for this I have worked at: 
![multistat_test](https://user-images.githubusercontent.com/23470681/36731189-4886c00a-1bca-11e8-925b-678667dc7598.png)

**Comment by bric3** [comment]
Following a reply in tweeter, I'd like to inject another set of ideas :

Netflix has a dashboard that is able to show different metrics ([source](https://t.co/Kp766enAF4))

Notice the path (that could be a label name) with a colored background, the request per seconds with the variation, the errors, status codes, latencies, some graphs, etc.

![image](https://user-images.githubusercontent.com/803621/37477152-37baa584-2877-11e8-8e7a-1b319146a8bf.png)

Currently my only way is to use a repeating panel, but this does not show everything I would like and it is taking a lot of space on the dashboard.

In the same way Percona created their own panel, for monitoring db queries performance ([source](https://www.percona.com/blog/2017/12/01/percona-monitoring-and-management-1-5-qan-grafana/))

That panel is very interesting because it has a search function, it can expand itself to show more queries. And of course shows additional metrics like count, latencies, ...

![image](https://user-images.githubusercontent.com/803621/37477958-4cb22f8c-2879-11e8-85c4-f9304263f405.png)

**Comment by Diegonarducci88** [comment]
when implemented ???

**Comment by hmmxp** [comment]
Dear All,

Will this be implemented in version 5.1 or 5.2? The multi stat panel and repeating stats panel will be very useful to display data

**Comment by bergquist** [comment]
look at this @bjartek

**Comment by torkelo** [comment]
@alexanderzobnin So maybe the auto layout was not the best idea as when you edit a panel it will always be in wide (horizontal) layout. So a layout direction option will be needed :) 

I updated the task list in the issue description.

**Comment by alexanderzobnin** [comment]
@torkelo ok

**Comment by rshejnberg** [comment]
Any updates on when this feature might be getting released?

**Comment by jamessewell** [comment]
I came here from #6419 - I'm looking for a way to have a singlestat which represents a percentage show the sparkline with a min/max of 0/1 (or 0/100). 

Does this PR help with this? It looks like it doesn't it just allows a set of stats to use the same scale.

**Comment by debmalyapan53** [comment]
Any update on this?

**Comment by yesoreyeram** [comment]
I have built[ Boom Summary Panel](https://github.com/yesoreyeram/yesoreyeram-boomsummary-panel) which can be used as multistat panel. This can be used to extract stats from table outputs

![image](https://user-images.githubusercontent.com/153843/53750112-df169780-3ea0-11e9-9eff-f6159d4b6f4b.png)

**Comment by torkelo** [comment]
Closing this as it wil be baked into many visualizations, not a single multi stat panel

**Comment by xuhuihihi** [comment]
> Another piece of inspiration, would be nice to use for repeating stat panels:
> 
> ![screenshot 2018-01-17 17 07 58](https://user-images.githubusercontent.com/2886187/35052893-fe524ea0-fba8-11e7-80e4-004f200d9733.png)

Are there any reference examples?

**Comment by Daly123456** [comment]
probe_ssl_earliest_cert_expiry{instance=~"$target"} -time()
i have this instruction it lets me display ssl expiry time using prometheus as datasources and Multistat as a panel type !
i need to convert time visualised to days ! For exemple 72 days !
i need help as soon as possible please !
![commiu](https://user-images.githubusercontent.com/46686877/71735663-4dc0da80-2e4f-11ea-8546-d0bc6d798833.PNG)

**Comment by Daly123456** [comment]
problem solved thanks for not responding

**Comment by sowndarya22** [comment]
> problem solved thanks for not responding

Even I have the same problem. Can you please tell how did you fix this

**Comment by sowndarya22** [comment]
probe_ssl_earliest_cert_expiry{instance=~"$target"} -time() 

The below showing wrong output in grafana

**Comment by Daly123456** [comment]
which panel did you used  ?

**Comment by sowndarya22** [comment]
> which panel did you used ?

grafana dashboard id - 7587

**Comment by Daly123456** [comment]
can u upload a screenshot ?

**Comment by sowndarya22** [comment]
> can u upload a screenshot ?

![image](https://user-images.githubusercontent.com/40585727/72166140-b69bdb80-3396-11ea-96fe-b608b0802f75.png)

**Comment by sowndarya22** [comment]
![image](https://user-images.githubusercontent.com/40585727/72166235-df23d580-3396-11ea-9b0d-6e971629901a.png)

**Comment by Daly123456** [comment]
try to use only this fonction ( time()) to verify your know where the problem did come from !

**Comment by sowndarya22** [comment]
time() gives a value 50 years, 0 months, 3 weeks

**Comment by Daly123456** [comment]
try to check your ssl manuelly from your site ! 

![image](https://user-images.githubusercontent.com/46686877/72167387-58d5b680-33cb-11ea-9103-cb0a04cfc07f.png)

**Comment by sowndarya22** [comment]
> try to check your ssl manuelly from your site !
> 
> ![image](https://user-images.githubusercontent.com/46686877/72167387-58d5b680-33cb-11ea-9103-cb0a04cfc07f.png)

![image](https://user-images.githubusercontent.com/40585727/72167505-39be3100-3399-11ea-87cc-b0f024537014.png)
