### ISSUE TITLE
Elasticsearch query for fetching count in Singlestat

### ISSUE THREAD

**Issue by nayeemnayyu** [grafana/grafana#10354]
This is my elasticsearch mapping,

{
  "enriched_logs": {
    "aliases": {},
    "mappings": {
      "log": {
        "properties": {
          "authors": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "articles": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "timestamp": {
            "type": "date"
          },
          "title": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": 1513763089541,
        "number_of_shards": 5,
        "number_of_replicas": 1,
        "uuid": "ItbKyb9ZTqCp15YIfDde_w",
        "version": {
          "created": 5050199
        },
        "provided_name": "enriched_logs"
      }
    }
  }
}

Just wanted to get the number of articles by particular author.

- Grafana version --- 4.4.3
- Datasource --- Elasticsearch
- OS --- Ubuntu 16.04

**Comment by torkelo** [comment]
please open questions on the community site (https://community.grafana.com/). And describe your question in more detail. Have you tried specifying a query in singlestat? Got any error? What is the response from your query? (using query inspector to investigate query and ES response). What are your singlestat panel options?
