### ISSUE TITLE
Building the worldmap type of different panels in the DashBoard, which setting data will affect each other. For example.colors

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#10359]
Please include this information:
- What Grafana version are you using?   v4.5.2
- What datasource are you using?    ElastricSearch
- What OS are you running grafana on?   Windows64
- What did you do?   When creating a worldmap type of panel, settings the color item's data will affect each other.
- What was the expected result?   The settings for colors has on influence on each panel
- What happened instead?     For example. Creating a worldMap type panel and setting its colors of worldmap configuration items in the first, as shown in Figure 1. And then when you create a worldmap type panel again, which initial value of colors for the worldmap configuration item will be the color seted by the previous panel, as shown in Figure 2,if you set the color of the second panel, as shown in Figure 3. The colors of the first panel will be the same as the second color, as shown in Figure4.
 FIG. 1
![image](https://user-images.githubusercontent.com/34366341/34378292-127e5e52-eb30-11e7-9d01-de4e8dc91363.png)

    FIG. 2
   ![image](https://user-images.githubusercontent.com/34366341/34378313-2fe87392-eb30-11e7-8639-06083b514b40.png)

   FIG. 3
  ![image](https://user-images.githubusercontent.com/34366341/34378329-3fbbd458-eb30-11e7-99fe-3ee00a14d305.png)

  FIG. 4
  ![image](https://user-images.githubusercontent.com/34366341/34378342-4c3ff358-eb30-11e7-83a3-04dae8c73107.png)

**Comment by torkelo** [comment]
please open issue in worldmap panel repo, https://github.com/grafana/worldmap-panel

**Comment by zhoumin8023** [comment]
The worldmap is just one example. This is the case in many parts of grafana. For example the panel of picturel.while also has an influence on each other about settting information .

**Comment by daniellee** [comment]
@zhoumin8023 it is a bug in the worldmap panel when properties are not deep cloned. I thought it was fixed but it is the Clock panel that got fixed. Will do a new release of the worldmap panel with a deep copy of the properties.
