### ISSUE TITLE
[Feature Request] Date Time on X-Axis in UK Format

### ISSUE THREAD

**Issue by ssnkhan** [grafana/grafana#10352]
- What Grafana version are you using?
4.6.3

- What datasource are you using?
Postgres

- What OS are you running grafana on?
macOS

- What did you do?
Run a query which returns a count of a column, over time. Grafana displays the date along the x-axis in the American notation of MM/DD, rather than the expected UK notation of DD/YY

- What was the expected result?
Grafana should detect local settings or allow an override so that the user can select their preferred date display format, such as DD/MM/YYYY

- What happened instead?
Adds date along x-axis in the American notation MM/DD

- If related to metric query / data viz:
Graph - Time Series

**Comment by torkelo** [comment]
duplicate o https://github.com/grafana/grafana/issues/1459
