### ISSUE TITLE
Table panel time series aggregations for text data

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#10360]
In some cases values in time series returned by the data source may be a string (app version, hostname, etc). It's impossible to show this data in table panel with `time series aggregations` mode in current Grafana version (that worked in previous versions). This caused by `TimeSeries.getFlotPairs()` function which calculates series stats. That doesn't make sense to calculate values like `avg`, `min` or `max`, but I think `current` should work for any kind of data. Example of fixed behaviour:

Before:
![screenshot from 2017-12-27 13-40-16](https://user-images.githubusercontent.com/4932851/34379272-7e1e0aec-eb0b-11e7-9cf5-96310ede6484.png)

After:
![screenshot from 2017-12-27 13-39-12](https://user-images.githubusercontent.com/4932851/34379257-691443fa-eb0b-11e7-96ae-fbdc49d1daa0.png)

**Comment by torkelo** [comment]
not sure I understand. 

> In some cases values in time series returned by the data source may be a string (app version, hostname, etc). It's impossible to show this data in table panel with time series aggregations mode in current Grafana version (that worked in previous versions). 

time series data in strings and you want time series aggregations on strings? How do you aggregate hostnames? Can you show some example of returned data?

**Comment by alexanderzobnin** [comment]
Sure:

![screenshot from 2017-12-27 13-46-49](https://user-images.githubusercontent.com/4932851/34379460-68b65136-eb0c-11e7-90f7-a97734e21798.png)

**Comment by alexanderzobnin** [comment]
In some cases, it makes sense to show the current value of this metric for the set of hosts, for example. That was possible in old versions (I think it was unexpected behaviour).

**Comment by torkelo** [comment]
that does not look like a time series, the value is a string. Is table format not better suited for data like this?

**Comment by alexanderzobnin** [comment]
Hm... Maybe table format is really a better solution.

**Comment by alexanderzobnin** [comment]
I handle this in the Zabbix data source (https://github.com/alexanderzobnin/grafana-zabbix/commit/a3db5dbcecaffdfb1063655c2a7c17d9850aaedb)
