### ISSUE TITLE
Graphite v1.1 Template queries

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#10366]
Graphite v1.1 provides autocomplete endpoints that are quite handy. Using these to populate template variables would be very useful when using tag-based metrics. 

Something similar to the [OpenTSDB datasource](http://docs.grafana.org/features/datasources/opentsdb/#query-variable) would likely be sufficient.

**Comment by DanCech** [comment]
See #10139

**Comment by shanson7** [comment]
@DanCech - That's similar to what OpenTSDB Datasource supports. I think that's a good start, but it becomes more useful when you can add more filters from existing template variables.

**Comment by DanCech** [comment]
You mean to use another variable to filter the returned values? I was thinking about adding support for a second parameter, so then I think you could say something like `tagValues("tag", "$othervar")`

**Comment by shanson7** [comment]
Exactly! You can see it here: http://docs.grafana.org/features/datasources/opentsdb/#nested-templating

It's variadic in the OpenTSDB datasource so both:
`tag_values(cpu, hostname, env=$env)`
and
`tag_values(cpu, hostname, env=$env, region=$region)`
work, with the latter being more specific.

It also works with multiple values, which is useful, but more work.

**Comment by DanCech** [comment]
hmm, we could possible leverage the auto-complete endpoint for this, which would support a syntax quite like the opentsdb tag_values, except that there wouldn't be a metric.  I'll experiment with that a little

**Comment by DanCech** [comment]
Added support for `tag_values(tag, [, expression]*)` and `tags([expression]*)` in #10139

**Comment by Perlovka** [comment]
`tag_values(hostname, region=~$region)` does not work with multivalue $region

Request looks like this when `$region={r1,r2}`:
`/tags/autoComplete/values?expr=region=~{r1&expr=r2}&limit=10000&tag=job`

**Comment by Perlovka** [comment]
@DanCech could you point me please how exactly this should be used in nested templates? Cause I can't find any docs about this new syntax.

Let's say I have one multivalue variable `$region = tag_values(region)`
And I want to use it in second variable, to get available jobs in selected regions:
`$job = tag_values(job, region=~$region)`
How the right query shoud look?

**Comment by DanCech** [comment]
`$job = tag_values(job, region=~${region:regex})`

**Comment by Perlovka** [comment]
Oh, I finally found it (https://github.com/grafana/grafana/issues/9911) Thanks =)

**Comment by Perlovka** [comment]
With the new syntax, nested template autoupdate is not working anymore. If I change the region, job value does not gets updated automatically.

**Comment by shanson7** [comment]
Can this be closed? Seems like it's done (and it's great :)
