### ISSUE TITLE
Postgres datasource errors when password contains forward slash (/)

### ISSUE THREAD

**Issue by timgifford** [grafana/grafana#10364]
Please include this information:
- What Grafana version are you using? ` Grafana v4.6.3 (commit: 7a06a47)`
- What datasource are you using? `Postgres`
- What OS are you running grafana on? `Linux version 4.9.0-4-amd64 (debian-kernel@lists.debian.org)`
- What did you do? Created a new Datasource with a password that contains a forward slash `/`. Password was `asdf/ghik`
- What was the expected result? Successful connection or invalid password
- What happened instead? Error message displayed: `dial tcp: address tcp/asdf: unknown port`

**Comment by marefr** [comment]
There is a fix in the master branch for passwords with symbols like # that cause problems in the connection string. And also a fix in xorm, the ORM that Grafana uses that will be included in the next release of Grafana.

#9830

**Comment by marefr** [comment]
Thank you for the report.

I have confirmed that the fix for #9830 also solves this problem with slash-character in the password so I'll close this.
