### ISSUE TITLE
Add User in Organisation by API is returen 403 Forbidden

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#10372]
Grafana version: 4.6.3
OS: windows

I use the api to Add User in Organisation, but return **403 Forbidden**, is any configration to change?
**url**: http://localhost:3000/api/orgs/3/users
**request**: {
 "loginOrEmail":"admin", 
 "role":"Admin"
}
**response**:
{
"message": "Permission denied"
}

I use the APIKey, APIKey is correct， because the create organization is ok. please help me. thank you very much. @torkelo

**Comment by pf23** [comment]
Similar problem to me.

Grafana version: 5.0.0

url: http://admin:admin@localhost:3000/api/orgs
headers: {
 "Accpet": "application/json",
 "Content-Type": "application/json",
 "Authorization": "a-valid-api-key"
}

response:
{
"message": "Permission denied"
}

It returns "Unauthorized" if I did not pass the api key.

Other similar requests which need server admin privileges receive the same response.

**Comment by torkelo** [comment]
This api route requires server admin permissions (Which we do not have an API key for)
