### ISSUE TITLE
join mode for collectd metrics in influxdb not supported

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#10387]
In influxdb 1.4.2, a new configuration option has been introduced - "parse-multivalue-plugin". This defaults to "split" which is the "old" behaviour.

e.g. for the "interface" metric, it might appear like this:

OLD:
interface_rx,host=hostname,instance=bond0,type=if_errors
interface_rx,host=hostname,instance=bond0,type=if_octets
interface_rx,host=hostname,instance=bond0,type=if_packets
interface_tx,host=hostname,instance=bond0,type=if_errors
interface_tx,host=hostname,instance=bond0,type=if_octets
interface_tx,host=hostname,instance=bond0,type=if_packets

> select * from interface_rx where time > now() - 5m and host = 'hostname' and instance = 'bond0'
name: interface_rx
time                host                             instance type       value
----                ----                             -------- ----       -----
1514622418790124022 hostname bond0    if_octets  18720681518
1514622418790124839 hostname bond0    if_packets 113002148
1514622418790125687 hostname bond0    if_errors  0

NEW:
interface,host=hostname,instance=bond0,type=if_errors
interface,host=hostname,instance=bond0,type=if_octets
interface,host=hostname,instance=bond0,type=if_packets

> select * from interface where time > now() - 10m
name: interface
time                host                             instance   rx          tx          type
----                ----                             --------   --          --          ----
1514621938790063238 hostname bond0         239064566   0           if_octets
1514621938790063932 hostname bond0         3984409     0           if_packets
1514621938790064515 hostname bond0         0           0           if_errors

**Comment by yellowpattern** [comment]
Actually, it may not be necessary to change anything, except to rewrite dashboards.

**Comment by yellowpattern** [comment]
Hmm...
SELECT field(rx) derivative(1s) alias(rx)
SELECT field(tx) derivative(1s) alias(rx)

produces two serieses, "interface.rx" and "interface.tx".

How do I remove the "interface." from the series name?

**Comment by torkelo** [comment]
you can you alias expressions to control series names. 

closing this as this as it seems to be not related to any feature or bug in Grafana
