### ISSUE TITLE
Please add  AWS/States Cloudwatch AWS

### ISSUE THREAD

**Issue by vikaskoppineedi** [grafana/grafana#10386]
- What Grafana version are you using?
grafana-4.6.3-1
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
Amazon linux AMI
- What did you do?
 While Templating, namespaces() Won't list the AWS/States namespace. 
Error Message from Log ""Unable to find namespace AWS/States"". 
Stepfunction Monitoring Reference [https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/sfn-metricscollected.html]

- What was the expected result?
List Available Stepfunction Names, Stepfucntion available metrics. etc .
- What happened instead?
Error Message from Log ""Unable to find namespace AWS/States"".

**Comment by vikaskoppineedi** [comment]
Any help fixing this is appreciated.

**Comment by vikaskoppineedi** [comment]
Anyone, please help fix this issue. It's been 20 days. Or at least tell me how to make this change and use it on my own version of grafana.

**Comment by mtanda** [comment]
This commit is a good example for you.
https://github.com/grafana/grafana/commit/5c94daa011e6b175e58b9850ed689c9cc669ea39#diff-138f230a03ac8392e9cd5f05c3e2ab62

Let's try :-)

**Comment by vikaskoppineedi** [comment]
Hi Mtanda,

I made the changes in my local repo , built it and checked and it worked. So how do i make a pull request

**Comment by vikaskoppineedi** [comment]
Hi mtanda,

I have build the code and started  the server, and my changes worked.  I don;t know why the tests are failing on circli. 

https://github.com/grafana/grafana/pull/10607

can you please help resolve this issue.
