### ISSUE TITLE
Problem rendering alert list panel.

### ISSUE THREAD

**Issue by fernandobeltranjsc** [grafana/grafana#10388]
Please include this information:
- What Grafana version are you using?
4.6.2
- What datasource are you using?
InfluxDB 
- What OS are you running grafana on?
Windows
- What did you do?
Click share into Alert List panel  (image direct link)
- What was the expected result?
Get the rendered image with alert list.
- What happened instead?
Get the folowing error:
Server side error :(
Timeout error. You can set timeout in seconds with &timeout url parameter
Check the Grafana server logs for the detailed error message.
Server side error :(
Rendering failed.
Check the Grafana server logs for the detailed error message.

On any other panel type, the rendered image is displayed right
Log error only show error 500 on request =GET path=/render/dashboard-solo/db/basecamp status=500

**Same behaviour can be reproduced in Grafana Live Demo:**
http://play.grafana.org/render/dashboard-solo/db/alerting?orgId=1&panelId=3&from=1514708718924&to=1514719518924&width=1000&height=500&tz=UTC%2B01%3A00

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/alertlist/module.ts#L78 

think the alertlist panel needs to call renderCompleted, 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/text/module.ts#L55

**Comment by fernandobeltranjsc** [comment]
I think that "Pie Chart" panel has the same problem.  Try to render with direct link image, same error.

**Comment by alexanderzobnin** [comment]
Pushed fix for this, but found another rendering bug:

![alerting-layout](https://user-images.githubusercontent.com/4932851/34720112-a5b33224-f54e-11e7-9635-a0ac72b2fdf5.png)

![screenshot from 2018-01-09 14-53-03](https://user-images.githubusercontent.com/4932851/34720070-84853840-f54e-11e7-8792-641327d6412a.png)
