### ISSUE TITLE
Enforce stricter go code formatting and vetting. 

### ISSUE THREAD

**Issue by mjtrangoni** [grafana/grafana#10381]
- What Grafana version are you using?
master branch
- What datasource are you using?
none
- What OS are you running grafana on?
CentOS7.4
- What did you do?
run [gometalinter](https://github.com/alecthomas/gometalinter)
- What was the expected result?
    1. no issues, or less than at least. 

I`ve just taken a look at the output, and I think running this within CircleCI should add some value to the project. Thanks!

- What happened instead?
```
$ gometalinter --vendor ./... | awk '{print $NF}'| sort | uniq -c
     13 (deadcode)
    116 (errcheck)
     68 (gas)
     10 (goconst)
     62 (gocyclo)
   2848 (golint)
    887 (gotype)
     35 (ineffassign)
      3 (interfacer)
     22 (maligned)
      1 (megacheck)
      3 (structcheck)
     14 (unconvert)
      1 (varcheck)
     47 (vetshadow)
```

**Comment by bergquist** [comment]
Good idea! We will start working on the build in the beginning of Q1. This should be one of the improvements.

**Comment by mjtrangoni** [comment]
mmm, this is going worst

```
$ gometalinter --vendor ./... | awk '{print $NF}'| sort | uniq -c
     14 (deadcode)
    122 (errcheck)
     69 (gas)
     12 (goconst)
     64 (gocyclo)
   3079 (golint)
    957 (gotype)
     38 (ineffassign)
      3 (interfacer)
     25 (maligned)
      1 (megacheck)
      3 (structcheck)
     14 (unconvert)
      2 (varcheck)
     57 (vetshadow)
```

**Comment by bergquist** [comment]
Sure. This is not part of our CI build process yet. We will add once we work more on https://github.com/grafana/grafana/issues/9633

Maybe not all checks but some of them.

**Comment by bergquist** [comment]
Thank you for the contributions! Most of these checks makes sense. Would be great to have them in CI but only enable one at the time. 

`deadcode, ineffassign,structcheck, unconvert, varcheck, gosimple` would be a great start :)

**Comment by mjtrangoni** [comment]
@bergquist Perfect! I will be creating a PR on it.

**Comment by bergquist** [comment]
@mjtrangoni small PR's for code changes is preferred for changes like this :)

**Comment by mjtrangoni** [comment]
Status update: we are checking now **structcheck**, **unconvert**, and **varcheck** at CircleCI. Let see how this works in everyday life, and we can maybe enable some more in a near future. 
```
$ gometalinter --vendor --deadline 6m ./... | awk '{print $NF}'| sort | uniq -c
      9 (deadcode)
    123 (errcheck)
     70 (gas)
     15 (goconst)
     78 (gocyclo)
   2961 (golint)
     38 (ineffassign)
      4 (interfacer)
     25 (maligned)
     55 (vetshadow)
```
