### ISSUE TITLE
Add documentation for version and schemaVersion properties of dashboards

### ISSUE THREAD

**Issue by babolivier** [grafana/grafana#10382]
In [the online documentation](http://docs.grafana.org/reference/dashboard/#json-fields), the description for `version` and `schemaVersion` properties of dashboards is "TODO".

As I didn't understand the difference between these two immediately and had to check on my dashboards' JSON to understand it, I think it might be great for new users to have these properties properly documented.

PR incoming.

**Comment by rafaeleyng** [comment]
Where can I find the information about what is the most recent schema version?

**Comment by marefr** [comment]
@rafaeleyng in a perfect world [here](https://grafana.com/docs/grafana/latest/reference/dashboard/), but to be sure needs to check code:
current master: https://github.com/grafana/grafana/blob/d2a13c4715ab0311b55cfa9e144dbce4d5ab2cc2/public/app/features/dashboard/state/DashboardMigrator.ts#L33
6.7.x: https://github.com/grafana/grafana/blob/c5ea64c2c26a74e4e4b9ba883e21857a0ebd6bff/public/app/features/dashboard/state/DashboardMigrator.ts#L33
