### ISSUE TITLE
[Feature request] Allow parentheses in macro expansion for Postgres data source

### ISSUE THREAD

**Issue by bascarsija** [grafana/grafana#10380]
Effectively a clone of issue #8411 (which applies only to MySQL), but for Postgres.

Using:
Grafana v4.6.3 (commit: 7a06a47)
Postgres data source

Given:
```
"SELECT $__time(timezone('PST',p.last_updated_date)), p.position FROM p inner join x using (x_id) WHERE $__timeFilter(timezone('PST',p.last_updated_date)) ORDER BY 1 asc "
```

Expected:
```
"SELECT timezone('PST', p.last_updated_date) AS "time", p.position FROM p inner join x using (x_id) WHERE extract(epoch from timezone('PST', p.last_updated_date)) BETWEEN 1514490490 AND 1514512090) ORDER BY 1 asc "
```

Actual:
```
"SELECT timezone('PST' AS "time"), p.position FROM p inner join x using (x_id) WHERE extract(epoch from timezone('PST') BETWEEN 1514490490 AND 1514512090) ORDER BY 1 asc "
```

and

Given:
```
"SELECT $__time(extract(epoch from p.last_updated_date)), p.position FROM p inner join x using (x_id) WHERE $__unixEpochFilter(extract(epoch from p.last_updated_date)) ORDER BY 1 asc "
```

Expected:
```
"SELECT extract(epoch from p.last_updated_date) as "time", p.position FROM p inner join x using (x_id) WHERE extract(epoch from p.last_updated_date) >= 1514491287 AND extract(epoch from p.last_updated_date <= 1514512887 ORDER BY 1 asc "
```

Actual:
```
"SELECT extract(epoch from p.last_updated_date AS "time"), p.position FROM p inner join x using (x_id) WHERE extract(epoch from p.last_updated_date >= 1514491287 AND extract(epoch from p.last_updated_date <= 1514512887) ORDER BY 1 asc "
```

**Comment by atpage** [comment]
Broken for me as well.  I am trying to select an average time as my time column:

    SELECT
        $__time(start_time+(end_time-start_time)/2),
        ...

and it's generating

    SELECT
        start_time+(end_time-start_time AS time/2),
        ...

This seems like a bug not a feature request.

**Comment by tve** [comment]
I don't know whether this is related but the way the $__timeFilter expansion inserts itself into the parenthesis of the time variable is unfortunate. In my example it works thanks to operator precedence, but other examples are bound to fail.
![image](https://user-images.githubusercontent.com/39480/52909127-c28b2600-3237-11e9-933a-14cab2974462.png)
Specifically, the `$__timeFilter` expands to
```
(ts + interval '24 hours' BETWEEN ... AND ...)
```
when I expected to see
```
(ts + interval '24 hours') BETWEEN ... AND ...
```

**Comment by chaitan94** [comment]
I agree with @atpage that this is more of a bug report than a feature request.

However, there is a workaround for this issue as of now. Instead of using `$__timeFilter`, we should be able to simulate the same desired functionality using `$__timeFrom` and `$__timeTo`.

For example, in my case, I wanted to do `$__timeFilter(to_date(day, 'DD/MM/YYYY'))` which didn't work as expected. However, I was able to achieve the same behavior using `$__timeFrom() <= to_date(day, 'DD/MM/YYYY') AND to_date(day, 'DD/MM/YYYY') < $__timeTo()`

While this is sort of obvious, I hope this can help people who are new to grafana.

**Comment by mrtristan** [comment]
my situation using sql server

`and $__timeFilter(coalesce(cc.ContributionDate, oc.ContributionDate))`

becomes

`and coalesce(cc.ContributionDate BETWEEN '2019-11-29T13:04:02Z' AND '2019-11-29T19:04:02Z')`

which is clearly broken. 

for anyone unfamiliar, `coalesce` is just a "if the first thing is null, use the second"

**Comment by oscarkilhed** [comment]
The problem we're facing with this is that the macro expansion is very basic. In order to fully support nesting functions and macros we would probably have to create an actual SQL parser instead of relying on regexes.
