### ISSUE TITLE
Docs for how to build your own version of Grafana and docker-image

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#10384]
* Building from source
* Building custom docker containers

ref https://github.com/grafana/grafana/pull/9421

**Comment by bergquist** [comment]
will be solve by our new build pipeline

**Comment by bergquist** [comment]
the dockerfile in the root folder was added in 5.3.0 so you need to upgrade.

**Comment by daixiang0** [comment]
@bergquist could share dockerfile which use to build v5.2.1 image since i can pull this version from docker hub.
I want to custom UI so i build fronted code and use below Dockerfile but failed:
```
From grafana/grafana:5.2.1
ADD public /usr/share/grafana/
EXPOSE 3000
USER grafana
ENTRYPOINT [ "/run.sh" ]
```
I can run but my changes do not work.
Is there any something wrong?
