### ISSUE TITLE
aliasByNode in influxdb

### ISSUE THREAD

**Issue by Ram6562** [grafana/grafana#10398]
How to write aliasByNode(8) in InfluxDB-grafana because i can't see aliasByNode option 

- What Grafana version are you using?
  v4.6.2
- What datasource are you using?
  Influxdb
- What OS are you running grafana on?
  Ubuntu

**Comment by torkelo** [comment]
it'a graphite option that InfluxDB does not have. 

If you have measurement names with dots in them you can the Alias Pattern `$1` or `$2` to get the first or second node.

**Comment by Ram6562** [comment]
Please can you send example how to query following 
  - Alias Pattern $1 or $2 to get the first or second node.

**Comment by torkelo** [comment]
<img width="520" alt="screen shot 2018-01-02 at 12 25 55" src="https://user-images.githubusercontent.com/10999/34482409-1aa33bca-efb8-11e7-8dd9-dfc947a934e8.png">

**Comment by Ram6562** [comment]
Unable to get data by node wise

On Jan 2, 2018 4:56 PM, "Torkel Ödegaard" <notifications@github.com> wrote:

[image: screen shot 2018-01-02 at 12 25 55]
<https://user-images.githubusercontent.com/10999/34482409-1aa33bca-efb8-11e7-8dd9-dfc947a934e8.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grafana/grafana/issues/10398#issuecomment-354747615>,
or mute the thread
