### ISSUE TITLE
It makes no sense to sort the records in table via time when the column "time" is hidden

### ISSUE THREAD

**Issue by ahrtr** [grafana/grafana#10396]
Generally the records displayed in table are sorted by time by default, which is fine. But if a user hides the column "time" and checks the option "instant", then it means that the user doesn't care about the time at all, then it makes no sense to sort the records via time any more.

**Comment by torkelo** [comment]
You can click on another panel to sort based on that. Or you can disable sorting and let prometheus set order by clicking first on the column that has the arrow up or down. Click it so the arrow disappears, then no grafana sorting is used
