### ISSUE TITLE
Alert List Improvements

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10397]
Currently the alert list page design & item is lacking and inconsistent with the alert rule item design used by the alert list panel. 

Current view: 
<img width="797" alt="screen shot 2018-01-02 at 10 06 51" src="https://user-images.githubusercontent.com/10999/34479060-c9dd8e74-efa4-11e7-9a40-d5a9f3417ae2.png">

Alert list panel:
<img width="553" alt="screen shot 2018-01-02 at 10 08 08" src="https://user-images.githubusercontent.com/10999/34479079-dd282732-efa4-11e7-98db-7e572ef4aa41.png">

Todo:
1) Align design to something similar to alert list panel. Make the pause and configure icons into buttons. Not sure about the button type & size. Use btn-inverse & btn-small for now. Will try to consult @mattttt with some feedback here. Also we need to reduce the height of each item, tighten up the padding a bit.

2) Refactor css for alert list & item, now it's a mess and mix of card css and markup mixed with some custom markup and css. This needs be refactored from scratch I think. Skip using the card css and markup and use completely custom alert-list styles and markup. Refactor class naming to better follow BEM. Since we only need to support list layout a lot of the markup and wrapper classes can be removed. These classes are used in 3 places (alert list page, alert list panel, and alert list history  in graph alert tab) so all needs to be updated to reflected the updated design and markup/class names. Plan is to share components here long term. So the AlertRuleItem can be used in the alert list panel. But that will require some angular -> react wrappers and figuring out how to pass mobx state via angular -> react for small components. Have not tested how that will work yet so let's wait with trying to reuse the same component here for now (but that is the long term goal). 

3) Update design of alert list page, add search field before filter state
<img width="504" alt="screen shot 2018-01-02 at 10 45 16" src="https://user-images.githubusercontent.com/10999/34479993-159bb930-efaa-11e7-87de-8a4d58c34230.png">

Search rule name, state, evalData matches (need to add this to model). Try to highlight matched words in the actual alert list items. 

This needs to be done either after this PR is merged or in the same branch as this PR:
https://github.com/grafana/grafana/pull/10392

**Comment by ryantxu** [comment]
I noticed that the `NO DATA` state has funky formatting:
![image](https://user-images.githubusercontent.com/705951/34515883-a6f2165c-f074-11e7-908f-96e2852d0f69.png)

just FYI
