### ISSUE TITLE
How to show time in y axes in granfana

### ISSUE THREAD

**Issue by peggiepxf** [grafana/grafana#10394]
Thanks for looking into my issue.
I want to show  time in y axes in graph in granfana,anyone could help advise?
e.g
I use influxdb,and below is my measurements.I want to show time1(20:15 ,25:25)in y axes in graph in granfana.
But if I select time1,it show nothing in y axes
> select * from table
name: table
time                               action time1
1513555200000000000 test   20:15
1513641600000000000 test   25:25

**Comment by torkelo** [comment]
this is not currently possible, only numeric values are a allowed strings like "20:15" cannot be graphed
