### ISSUE TITLE
is there any alternatives for aliasByNode in influxDB

### ISSUE THREAD

**Issue by Ram6562** [grafana/grafana#10399]
Please send me an example for(Alias Pattern $1 or $2 to get the first or second node)

- What Grafana version are you using?
   v4.6.2
- What datasource are you using?
  Influxdb
- What OS are you running grafana on?
  ubunut

**Comment by Ram6562** [comment]
FROM default trybase.dc_sync_delay.byOrg WHERE org =~ /^$OrgID$/
GROUP BY  time (5m) tag (host)
ALIAS BY $0 $tag_host

for above query i am getting $0  as trybase
                                              $1 as dc_sync_delay
                                              $2  as byOrg  from ( FROM default trybase.dc_sync_delay.byOrg )

**Comment by torkelo** [comment]
you seem to have figured it out , I did show you an example in https://github.com/grafana/grafana/issues/10398#issuecomment-354747615 

not sure why you opened a new question. And please read the text in the new issue description that specifically says on the first item to post questions on the community site :)

**Comment by Ram6562** [comment]
sorry!

i referred  #10398 (comment) this solution only 

but am not sure is it correct or not . can you please clarify:

 (FROM default trybase.dc_sync_delay.byOrg WHERE org =~ /^$OrgID$/
GROUP BY  time (5m) tag (host)
ALIAS BY $0 $tag_host

for above query i am getting $0  as trybase
                                              $1 as dc_sync_delay
                                              $2  as byOrg  from ( FROM default trybase.dc_sync_delay.byOrg ) )

**Comment by torkelo** [comment]
I think you need to clarify 
`$1 as dc_sync_delay`
`$2 as byOrg`

This looks correct as if you split your measurement name (`trybase.dc_sync_delay.byOrg`)  you 
get `[trybase, dc_sync_delay, byOrg]` so $0 will be first node, $1 second etc

**Comment by Ram6562** [comment]
please clarify 
measurement name means node?

**Comment by torkelo** [comment]
no, measurement name is an InfluxDB term, `trybase.dc_sync_delay.byOrg` is your measurement name

**Comment by Ram6562** [comment]
i am getting measurement name instead of node (by specifying $1 in alias By)  
how can i get node wise ? 

please clarify

**Comment by torkelo** [comment]
I have no idea what your talking about, what do you mean by node? what I mean by node (and aliasByNode in graphite) is part of the metric name if you split metric name by dots (influxdb it's the measurement name). 

Can you describe what you want to do? and what you mean by node?

**Comment by Ram6562** [comment]
i am getting measurement name instead of node (by specifying $1 in alias By)  
how can i get node wise ? 

please clarify
