### ISSUE TITLE
Parameters from grafana.ini are ignored

### ISSUE THREAD

**Issue by martinler** [grafana/grafana#10406]
- What Grafana version are you using?
Version 5.0.0-11057pre1

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Debian 9

- What did you do?
Modified grafana.ini to disable some parts of login page

- What was the expected result?
no signup button, no login fields

- What happened instead?
signup button and login field remains in place

BTW you can note visual glitch on my Safari 9 (yeah, not up-to-date)

![screen shot 2018-01-03 at 10 02 59](https://user-images.githubusercontent.com/19344005/34514343-5e8dc48a-f06d-11e7-8515-332a320f10d7.png)

**Comment by torkelo** [comment]
strange, when I set this in grafana.ini (then restart grafana-server)
```ini
[auth]
disable_login_form = true
```

the username and password fields are removed

**Comment by martinler** [comment]
Here is copy/paste from my grafana.ini. As you can see, editing is working for other parameters (google oauth).

[users]
# disable user signup / registration
;allow_sign_up = false

[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
;disable_login_form = true

**Comment by torkelo** [comment]
the settings are commented out (the leading `;` )

**Comment by martinler** [comment]
My fault. Confusing for me to use two comment elements.

Anyway, signup button remains, i can fill form, just after form i'm informed about disabling of registration.

# disable user signup / registration
allow_sign_up = false

# Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
disable_login_form = true

![screen shot 2018-01-03 at 10 17 53](https://user-images.githubusercontent.com/19344005/34514856-95539380-f06f-11e7-9ccf-71afb2db2a17.png)
![screen shot 2018-01-03 at 10 20 33](https://user-images.githubusercontent.com/19344005/34514890-d3ada9e0-f06f-11e7-9f3f-43f0d5ecfd6e.png)

**Comment by VitaliyDemchuk** [comment]
@martinler i have same problem.
When i change `allow_sign_up=false` in [users] block, signup buttom and form is view.

**Comment by torkelo** [comment]
Fixed in latest master

**Comment by VitaliyDemchuk** [comment]
@torkelo thx.
