### ISSUE TITLE
[Feature Request] Option to prefix dashboard names/url with folder name

### ISSUE THREAD

**Issue by Chris-Hicks** [grafana/grafana#10408]
- What Grafana version are you using?
Grafana v5.0.0-pre1 (commit: e480a38)
- What OS are you running grafana on?
Debian

 ## Request
We have started evaluating v5 prior to release and think it would be useful to prefix the dashboard name with the folder.  We currently use the following naming convention for our dashboards:

Area - Sub Area - Dashboard Name

The new version brings the feature of dashboard folders (which we really like).  We would like to use the folders to drop the Area from dashboard title i.e.:

Folder Name = Area
Dashboard Name = Sub Area - Dashboard Name

The issue we have is the names will no longer be unique as we have some dashboard like:

Area1 - Sub Area1 - Title
Area2 - Sub Area2 - Title

**Comment by marefr** [comment]
Closed #10408 via #10683

**Comment by marefr** [comment]
Closed via #10683
