### ISSUE TITLE
[Feature Request] Configure panel X, Y, Width and Height

### ISSUE THREAD

**Issue by Chris-Hicks** [grafana/grafana#10409]
- What Grafana version are you using?
Grafana v5.0.0-pre1 (commit: e480a38)
- What OS are you running grafana on?
Debian

 ## Request
Configure a panels X, Y, Width, Height in the general settings.

I can see that this may be problematic as you may enter settings that would cause panels to overlap but when you are trying to maintain a distinct layout across multiple dashboards it is difficult to position panels exactly the same without changing the JSON.  

I believe some work has been started in PR #10390

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
