### ISSUE TITLE
Not able to use variables with InfluxDB

### ISSUE THREAD

**Issue by martinler** [grafana/grafana#10402]
- What Grafana version are you using?
Version 5.0.0-11057pre1

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Debian 9

- What did you do?
1) created template variable "unit_id_all"
2) used this variable in dashboard query from select menu (image 1)

- What was the expected result?
Ability to use template variable in dasboard

- What happened instead?
Variable placeholder is not accepted, imediate result is error (image 1+2), after save/reload value is unknown/undefined, Query inspector don't show any result at this moment (image 4). After click to field Query inspector show no-standard view (image 4)
![1](https://user-images.githubusercontent.com/19344005/34490071-dbf24f70-efde-11e7-8cb9-8f072f396806.png)
![2](https://user-images.githubusercontent.com/19344005/34490069-dbcdaf80-efde-11e7-98b8-1082e2b1f846.png)
![3](https://user-images.githubusercontent.com/19344005/34490068-dba103cc-efde-11e7-95d9-0deeb3b3681f.png)
![4](https://user-images.githubusercontent.com/19344005/34490067-db75847c-efde-11e7-9af1-968d295ab7a4.png)

.

**Comment by martinler** [comment]
Workaround: togle edit mode and change specific value to variable in text edit mode. It's not possible to togle back to GUI editing, all changes are lost and default "new" query is shown.

**Comment by exbane** [comment]
I receive this same issue.. Started when i updated to 5.0pre.. I've updated to each nightly after that to see if it fixes the problem but it has not yet.. 

I get the following error with i try to use variables with InfluxDB 
![capture](https://user-images.githubusercontent.com/12447405/35403335-5f741d24-01cd-11e8-9e1b-8665f1eb93e3.PNG)

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
