### ISSUE TITLE
How to see all the data fields and values in grafana

### ISSUE THREAD

**Issue by Ram6562** [grafana/grafana#10405]
like we are able to see all the fields name and values as table format in kibana 

    What Grafana version are you using?
    v4.6.2
    What datasource are you using?
    Influxdb
    What OS are you running grafana on?
    ubunut

**Comment by torkelo** [comment]
Please, for the second time. Read the new issue description that opens with 
> Read before posting: 
Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 

You can view all fields in table panel

<img width="918" alt="screen shot 2018-01-03 at 10 03 10" src="https://user-images.githubusercontent.com/10999/34514341-5ca82a8e-f06d-11e7-8241-631818f4391e.png">
