### ISSUE TITLE
Upgrade path from 0.9.13 to latest version (1.1.1) ?

### ISSUE THREAD

**Issue by admin-pro** [grafana/grafana#10403]
Hello,

I'm currently running with the graphite version 0.9.13 (i'm not sure).

How i can upgrade from my actual version to the latest(v1.1.1) please ?

I need to reinstall from scratch and migrate my data or i can perform an upgrade inplace.

Thank you very much guys.

Have a nice day and happy new year

Edited: 

For more information here was the steps how i have installed graphite from source(from history) : 

git clone https://github.com/graphite-project/graphite-web.git && git clone https://github.com/graphite-project/carbon.git && git clone https://github.
com/graphite-project/whisper.git

cd whisper; git checkout 0.9.13-pre1; python setup.py install
cd ../carbon; git checkout 0.9.13-pre1; python setup.py install
cd ../graphite-web; python check-dependencies.py; git checkout 0.9.13-pre1; python setup.py

Thank you very much for help...

**Comment by torkelo** [comment]
check out the release notes to see if there are any specific upgrade tasks. 

http://graphite.readthedocs.io/en/latest/releases/1_0_0.html
http://graphite.readthedocs.io/en/latest/releases/1_1_1.html

Don't think there are any specific upgrade tasks.

**Comment by admin-pro** [comment]
Ok thank you Torkelo.
