### ISSUE TITLE
Influxdb Grafana query

### ISSUE THREAD

**Issue by arunimachoudhary** [grafana/grafana#10413]
I need some urgent help. We had a graphite and grafana dashboard with query:
![image](https://user-images.githubusercontent.com/35067517/34522426-8dc02d06-f0b8-11e7-9744-2cd8f2526ddb.png)
Please help me to replicate this query in influxdb grafana dashboard.

- What Grafana version are you using: 4.6.2
- What datasource are you using: Influxdb
- What OS are you running grafana on:Ubuntu

**Comment by torkelo** [comment]
That impossible they have totally different query languages and data models. 

please use community site for questions. https://community.grafana.com/
