### ISSUE TITLE
Dashboard name uniqueness & folders

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10419]
Today with current folder & dashboard urls dashboard names needs to be globally unique. This lessens some of the usefulness of Folders. Need to discuss some possible solutions to this. 

Update:
After a lot of discussions we've agreed on solving the dashboard name uniqueness and folders problem. We'll add the folder slug to the beginning of the dashboard slug. When renaming a folder, all dashboards in that folder needs to be updated with a new slug.

Related issues: 
https://github.com/grafana/grafana/issues/7883
https://github.com/grafana/grafana/issues/10408

**Comment by roidelapluie** [comment]
I would love to be able so specify the slug in the dashboard JSON file.

**Comment by luketopa** [comment]
How is the folder structure expected to work/look? So from the Grafana Menu would it be Dashboard, then have a structure for each org? 

Something like this?

Main Org

Dashboards/
|
├── Servers/
│   ├── Dashboard 1
│   ├── Dashboard 2
│   ├── Dashboard 3
│   └── Dashboard 4
|
├── Databases/
│   ├── Dashboard 1
│   └── Dashboard 2
| 
└── Other etc./
    ├── Dashboard 1
    ├── Dashboard 2
    ├── Dashboard 3
    └── Dashboard 4

**Comment by marefr** [comment]
@luketopa 

> So from the Grafana Menu would it be Dashboard, then have a structure for each org?

Yes

> Something like this?

Yes

**Comment by acleaves-gresham** [comment]
> How is the folder structure expected to work/look? So from the Grafana Menu would it be Dashboard, then have a structure for each org?
> 
> Something like this?
> 
> Main Org
> 
> Dashboards/ | ├── Servers/ │ ├── Dashboard 1 │ ├── Dashboard 2 │ ├── Dashboard 3 │ └── Dashboard 4 | ├── Databases/ │ ├── Dashboard 1 │ └── Dashboard 2 | └── Other etc./ ├── Dashboard 1 ├── Dashboard 2 ├── Dashboard 3 └── Dashboard 4

Interestingly, I still get the warning following this style.
