### ISSUE TITLE
Grafana 5.0.0-11057pre1: Coloring in singlestat not working with MySQL

### ISSUE THREAD

**Issue by martinler** [grafana/grafana#10418]
- What Grafana version are you using? 5.0.0-11057pre1
- What datasource are you using? MySQL, InfluxDB
- What OS are you running grafana on? Debian 9.2
- What did you do?
Created single stat pane, get value from MySQL, tried to use coloring for changing color
- What was the expected result?
pane should be orange with tresholds 100,500
- What happened instead?
pane is green

![screen shot 2018-01-03 at 19 14 16](https://user-images.githubusercontent.com/19344005/34533387-527cf538-f0ba-11e7-9553-dfb2c38a6e28.png)

**Comment by torkelo** [comment]
can you open query inspector and view the exact data your query returns? (in metrics tab, top right you find query inspector). 

The problem is very likely that the data your query returns are not numbers but strings.

**Comment by martinler** [comment]
Yes, correct, in db this field is defined as varchar. Thanks.
