### ISSUE TITLE
Grafana v5.0 bug, Dashboard settings side menu links not respective appSubUrl 

### ISSUE THREAD

**Issue by friesoft** [grafana/grafana#10416]
- What Grafana version are you using? Grafana 5.0.0 Nightly (11065pre1)
- What datasource are you using? InfluxDB/Elasticsearch
- What OS are you running grafana on? Red Hat 7.4

- What did you do? 
Using Grafana behind an Apache Reverse Proxy (with a custom context path) 
Clicking through the ui leads to wrong URLS (wrong redirects) as they lack the context path
Example: 
https://ourproxy.domain.com/grafana-qs/dashboard/db/mydashboard?refresh=1m&orgId=1&editview=settings
Clicking on General/Annotations/Variables/Links/Versions/View JSON doesn't honor the context path (grafana-qs) leading in URLs like those: https://ourproxy.domain.com/dashboard/db/mydashboard?editview=versions&refresh=1m&orgId=1&panelId=&fullscreen=&edit=

Same applies to:
* Mark as favorite (in the Dashboard View)

Related config:
```
# The public facing domain name used to access grafana from a browser
domain = ourproxy.domain.com

# The full public facing url
root_url = https://ourproxy.domain.com/grafana-qs/
```

- What was the expected result?
Correct URLs (containing the context path)

- What happened instead?
Wrong URLs in the UI - leading to wrong redirects

**Comment by friesoft** [comment]
Same applies to: https://ourproxy.domain.com/grafana-qs/dashboards/folder/93/myfolder
Clicking on the "Dashboards" link is missing the context: https://ourproxy.domain.com/dashboards

**Comment by friesoft** [comment]
Also applies to https://ourproxy.domain.com/grafana-qs/org/teams => Add Team

**Comment by torkelo** [comment]
Maybe your apache reverse proxy config is not setup correctly? both nginx and apache is working.

try something like this
```

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass /grafana http://0.0.0.0:3000
    ProxyPassReverse /grafana http://0.0.0.0:3000
</VirtualHost>
```

**Comment by friesoft** [comment]
We are using Apache httpd with the following config:
```
  <Location "/grafana-qs">
    ProxyPreserveHost On
    ProxyPass http://ourip:3001
    ProxyPassReverse http://ourip:3001
  </Location>
```

I guess it is really a bug (and I guess as you reopened the issue you think so too :) )

**Comment by marefr** [comment]
Related to #10363
