### ISSUE TITLE
Implement tag filter and folder filters in search side filterbox

### ISSUE THREAD

**Issue by Chris-Hicks** [grafana/grafana#10411]
- What Grafana version are you using?
Grafana v5.0.0-pre1 (commit: e480a38)
- What OS are you running grafana on?
Debian

 ## Request
The tag picker filter appears to have been removed from v5.  The only way I can find to filter on tags is to find a dashboard with the relevant tag and select it.  After selection there is no way to remove the filter i.e. I would expect to be able to re-select the tag and all dashboards re-appear.

**Comment by torkelo** [comment]
yes, we hid it because we did not manage to implement the new UX for this in time for merge to master. will be fixed soon.

**Comment by torkelo** [comment]
Just use regular select boxe for the tags filter. Skip folder filter for now

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/34817246-be891380-f6b7-11e7-91d9-65b5da8d896c.png)

Add these.
