### ISSUE TITLE
Problem! Unauthorized Error throwing after successful login using ldap credentials.

### ISSUE THREAD

**Issue by drnarahari** [grafana/grafana#10420]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Ubuntu
- What did you do?
- What was the expected result?
- What happened instead?
Getting an error Problem Unauthorized after logging in.
<img width="1657" alt="screen shot 2017-12-27 at 2 55 33 pm 2" src="https://user-images.githubusercontent.com/11853428/34539983-731130b0-f098-11e7-8832-981e8dd2e796.png">

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
can you open chrome dev tools & network tab and identify what request your getting unauthorized? Maybe it's your data source that has some custom auth that is not working

**Comment by drnarahari** [comment]
Failed to load resource:/api/dashboards/home the server responded with a status of 401 (Unauthorized). This is the error I see.

**Comment by drnarahari** [comment]
The issue is now resolved , we had a problem in a load balancer setting.

**Comment by Tikam02** [comment]
@drnarahari how do you solved it???

**Comment by nnsense** [comment]
@drnarahari it would be helpful for the community if you could share the setting you've changed with us. Thanks.
