### ISSUE TITLE
Caching option for Grafana Templating Queries 

### ISSUE THREAD

**Issue by xbblq7n** [grafana/grafana#10423]
I am looking for options to improve templating response time via caching.
Could anyone please let me know, if there is an option in Grafana to verify if the template queries can be cached.

Grafana Version used: V4.6.2
Datasource: Prometheus
OS: Linux

**Comment by torkelo** [comment]
The is only one way (currently) to cache them and that is to set Refresh to Never.  Then it the query is only executed when you hit update in variable options. But the query is still executed every time you change another variable that your template query uses.
