### ISSUE TITLE
[bug] missing profile icon

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#10426]
- What Grafana version are you using?
grafana_5.0.0-11065pre1

The profile icon is missing, though the users profile can still be accessed when hovering over the blank location. We are using ldap authentication.

![image](https://user-images.githubusercontent.com/20041843/34561242-f0578922-f140-11e7-9f78-ed8070776355.png)

**Comment by torkelo** [comment]
Does your grafana-server have internet access? Maybe it's call to gravatar to fetch profile is failing

**Comment by daveselan** [comment]
Not directly, it's behind a company firewall.

Version 4.x always showed a silouette, assuming it was a default. Seeing ldap user profile pictures would be nice, my guess is our server should provide them, but I don't know what is required to get ldap gravatar integration working?

![image](https://user-images.githubusercontent.com/20041843/34561952-2775407c-f144-11e7-8095-2ed202240e36.png)

**Comment by liujin1993** [comment]
+1

**Comment by alexanderzobnin** [comment]
@torkelo Previous version used a trick for default icon. Backend returns transparent png image if avatar not found. And frontend always placed default icon under the avatar image. Now side menu implementation was changed. So I think we should add default icon to the backend. What do you think? I don't know why it wasn't done in the previous version, maybe there was some reason for this?

**Comment by torkelo** [comment]
think it was because the fallback was an icon and the avatar api could only return images. We have an image that the gravatar proxy should return in case of request error, https://github.com/grafana/grafana/blob/master/public/img/user_profile.png

**Comment by benbourner** [comment]
Happened again? I am using  v8.1.5 (c725a4259a) with LDAP users, and get blank icons for them (local admin account works fine with icon):
![image](https://user-images.githubusercontent.com/29915126/135872115-b7c94bd5-f4e3-48b0-a970-d7533b158a25.png)

**Comment by zeddit** [comment]
Happened again. I am using v9.5.2 (cfcea75916) with LDAP. 
<img width="156"  src="https://github.com/grafana/grafana/assets/30164206/3f8edbd9-dded-47b3-8a48-e785e296f8e8">
because the user avatar is not showing, user cannot find the sign out button to log out.
