### ISSUE TITLE
Running grafana behind reverse proxy

### ISSUE THREAD

**Issue by Meghna-singh** [grafana/grafana#10422]
I want to run grafana behind ngnix. my nginx.conf has
server {
  listen 80;
  root /var/www;
  index index.html index.htm;

 location /grafana/ {
   proxy_pass http://localhost:3000/;
  }
}
}
root_url = %(protocol)s://%(domain)s:%(http_port)s/

but i am not able to run behind nginx...please help.

**Comment by torkelo** [comment]
set your root_url to the full url you want to use in your browser (the nginx url plus grafana sub path)
