### ISSUE TITLE
Dashboard links "Open in new tab" does not work

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10425]
This option does not seem to have it's desired effect.

**Comment by karanmagdani** [comment]
The url won't open in a new tab when I am using `:urlescape` for a cell. Is this expected behavior?

**Comment by psjgiganti** [comment]
The dashboard link will only open in a new tab if I flag it as a drop down

**Comment by biohazardxxx** [comment]
Thanks psjgiganti. However I think that is not intended behavior it should also open in new tab when not drop down.
