### ISSUE TITLE
Update go-stack to a newer version

### ISSUE THREAD

**Issue by dlsniper** [grafana/grafana#10435]
Hi all,

Currently Grafana doesn't play nicely with Delve on OSX due to a bug in LLVM. The bug is caused by an old version of ` go-stack `, see the details here: https://github.com/derekparker/delve/issues/852

Would it be possible to use a newer version of ` go-stack `? Also would it be possible to start using ` golang/dep ` a package manager to facilitate the adoption of it?

Thank you.

**Comment by bergquist** [comment]
We would like to change to `golang/dep` at some point but we will wait until its stable enough to be included in go itself.
