### ISSUE TITLE
Show all alert thresholds (for multi-condition alert)

### ISSUE THREAD

**Issue by shirakaba** [grafana/grafana#10430]
## Setup

* Grafana v4.6.3
* Datasource: Prometheus
* OS: Ubuntu

## Background

When you make an alert with multiple conditions, it only displays a threshold line on the graph for the first condition (corroborated in [this comment](https://github.com/grafana/grafana/issues/7258#issuecomment-351247600) on issue #7258 ).

I'd like the option to display threshold lines for each/all conditions.

## Use case

I'd like to show separate alert thresholds for both HD and SD video streams outputting at low bitrate. Currently it only shows the 2,500,000 bit/s threshold, but it should show the 1,500,000 bit/s threshold too:

![sd vs hd bitrate](https://user-images.githubusercontent.com/14055146/34571743-314d9338-f167-11e7-9faa-4a0421a5f4c3.png)

**Comment by Caffe1neAdd1ct** [comment]
On multi condition alerts which enter alerting for one of the conditions:

- the chart isn't highlighted with a red border
- the heart (top middle of the chart) is still white

Would be nice to have these two visual issues fixed at the same time. I've double checked the chart has definitely entered alerting, dashboard is saved and i've refreshed several times to make sure.

**Comment by williewheeler** [comment]
This would be great. Some thoughts:

- The visual design may be tricky. Would be desirable to make it clear which threshold goes with which metric.
- May want the option to remove the shading from the "bad" side of the threshold. Otherwise there could be a bunch of overlapping regions that make the chart hard to read.

**Comment by gillesdemey** [comment]
Closing this one as multiple threshold visualisations are supported in both the detail view and editor view of the new Grafana Alerting with the following caveats;

* Multiple single threshold values work as intended
* Multiple range threshold will work fine
* Multiple single thresholds and ranges works _but_ it will only show the range thresholds

![image](https://github.com/grafana/grafana/assets/868844/ed19a972-ab9c-4d99-917e-1ecb9b8e30e2)
![image](https://github.com/grafana/grafana/assets/868844/b8968bcc-2f80-4655-89d6-470112d38c69)
