### ISSUE TITLE
matched wrong index when use elasticsearch datasource with datepattern hourly

### ISSUE THREAD

**Issue by songjiao** [grafana/grafana#10438]
elasticsearch datasource  config:

![image](https://user-images.githubusercontent.com/4986593/34596915-82f67c4c-f21e-11e7-9889-9fbed69a56c7.png)

dashboard timezone set to use "Local browser time" . For me local browser time is "utc +8"
when query "Last 1 Hour" it's seem match index use "utc 0"  
![image](https://user-images.githubusercontent.com/4986593/34597058-5dd33af8-f21f-11e7-882f-ee677aa5ea26.png)

check code(line 16):
https://github.com/grafana/grafana/blob/27835f373e581430aab7763eb08075fb308c8353/public/app/plugins/datasource/elasticsearch/index_pattern.ts
  getIndexForToday() {
    if (this.interval) {
      return moment.utc().format(this.pattern);
    } else {
      return this.pattern;
    }
  }

**Comment by torkelo** [comment]
index date patterns are always UTC

**Comment by torkelo** [comment]
All log generators and other Elasticsearch tooling generate utc date index patterns, otherwise it is impossible to query the data from different local time zones.
