### ISSUE TITLE
unit kg is converted in an uncommon way

### ISSUE THREAD

**Issue by NextBlaubeere** [grafana/grafana#10436]
Hello,

Im using the unig kg (kilogramms) for my heating-system.
Whenever my graph is displaying over 10000 kg it is "translating" that into 10Mg, which is technically correct but in a common way of usage totally useless.

So can there be a button added that grafana does not convert into other metrics and stay in kg?
(and maybe change Mg to ton)

regards

**Comment by torkelo** [comment]
tricky no formal standard abbreviation for Tonne, https://en.wikipedia.org/wiki/Tonne  
>  It is a symbol, not an abbreviation, and should not be followed by a period. Informal and non-approved symbols or abbreviations include "T", "mT", "MT", and "mt".[8] Some of these are SI symbols for other units: "T" is the SI symbol for the tesla and "Mt" is the SI symbol for megatonne (equivalent to one teragram);

**Comment by jrgilman** [comment]
@torkelo this is an old issue but still relevant. When selecting a mass unit (Fields > Units > Mass) you get the option of mg, g, kg and then metric tons (t). But when Grafana decides to round up 1000kg it does to Mg (mega grams). Would it not be more logical to follow the dropdown and round up to metric tons also?

**Comment by frankyenshaw** [comment]
@torkelo this is still the case on grafana 8.  Is there any way to customize this behavior?

**Comment by gldraphael** [comment]
@torkelo - there is a standard symbol for the metric tonne. It is _t_.

From the same Wikipedia link you shared (emphasis mine):

>The **tonne (symbol: t)** is a unit of mass equal to 1000 kilograms. It is a non-SI unit accepted for use with SI. The official SI unit is the megagram (symbol: Mg), a _less common way_ to express the same mass.

From the [BIMP SI brochure](https://www.bipm.org/en/publications/si-brochure), §4:

![image](https://github.com/grafana/grafana/assets/10794213/e2449db3-6a8e-4383-b883-882fc7e54cf4)

I'm of the opinion that a case could be made for both tonnes and megagrams.

**Comment by mdvictor** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!

**Comment by tolik518** [comment]
This is kinda annoying since Mg is so uncommon that I have had never seen it in the wild.

As a workaround just type in `kg` and select `Custom value: kg`. You wont get conversion to ton, but you wont have to deal with uncommon abbreviations
