### ISSUE TITLE
Grafana 5.0.0-11057pre1: not able to create drilldown link with specific variable from "all" page

### ISSUE THREAD

**Issue by martinler** [grafana/grafana#10432]
- What Grafana version are you using? 5.0.0-11057pre1
- What datasource are you using? MySQL, InfluxDB
- What OS are you running grafana on? Debian 9.2
- What did you do?
Trying to achieve same setup as in Grafana 4.6, where this worked for me. Two dashboards, first with general informations about all units (vertical repeating of one row of panels), second dashboard with detail about specific unit.  Only way how to achieve repeating of rows is to set variable "incude all option", and then set value in popup menu to all. 

Drilldown link set on first dashboard on one of repeating panes, option "include variables" is on, target is second dasboard. 
- What was the expected result?
After click on unit number 65, user is transfered to second dasboard with details about unit number 65.
- What happened instead?
Instead of unit number 65 on which user clicked there is transfered value "all", so dashboard is not working. When i've tried to use "$unit_id" value as URL parameter, generated URL includes all values of "$unit_id" variable, so second dashboard is not working too.
![list of all units](https://user-images.githubusercontent.com/19344005/34578784-84dfc24a-f186-11e7-8e96-018a785d557f.png)
![detail of unit 1](https://user-images.githubusercontent.com/19344005/34578783-84bd2bae-f186-11e7-8a88-35c2df5ab282.png)
![detail of unit 2](https://user-images.githubusercontent.com/19344005/34578782-849c5c9e-f186-11e7-929d-e110b7909992.png)

**Comment by martinler** [comment]
Clarification: there are two links on panel. One is whole panel area - this is not working correctly, with "all" error. When i click on link in popup in corner, this link works correctly. Fascinating.

**Comment by torkelo** [comment]
unable to replicate, 
http://play.grafana.org/master/dashboard/db/singlestat-drilldown-link?panelId=11&orgId=1&var-app=backend&var-server=backend_01&var-server=backend_02&var-server=backend_03&var-server=backend_04&var-interval=1h

<img width="622" alt="screen shot 2018-01-05 at 09 21 02" src="https://user-images.githubusercontent.com/10999/34600845-cdaaa3d2-f1f9-11e7-8b0e-ff9ff6e9587e.png">

**Comment by torkelo** [comment]
is your singlestat panel repeated based on for each value of  the "$unit_id" ? Can you show your panel general options tab?

**Comment by martinler** [comment]
Detail of general tab. 
Just re-confirmed - link in corner pop-up is correct, "whole panel" link is incorrect.
![screen shot 2018-01-05 at 13 11 36](https://user-images.githubusercontent.com/19344005/34608730-0777aa72-f21a-11e7-9c5c-47315cabdb22.png)

**Comment by torkelo** [comment]
strange, works when I test it here 
http://play.grafana.org/master/dashboard/db/singlestat-drilldown-link?orgId=1&var-app=backend&var-server=backend_01&var-server=backend_02&var-server=backend_03&var-interval=1h

**Comment by martinler** [comment]
Ok, i had some time to do some research and i found where this bug is coming from.

When i will create single stat based on InfluxDB data, created drilldown link is correct on both places - in corner "tooltip", and when i click all space of single stat (exception see later). When i create single stat based on MySQL db, corner tooltop is correct, all-pane link is incorrect and directs to "all" variable instead of specific one.

Exception for InfluxDB - when there is no data returned from InfluxDB for this single stat, then the all-pane link is incorrect as well (with "all" instead of specific variable value)

My feeling is that if there is "null" value, then this error is happening. And for some reason all values from MySQL are for this feature (all-pane link) considered as "null".

Hope that my explanation makes sense, i can share with you my test dashboard.

**Comment by martinler** [comment]
(currently on Grafana 5.0.0-beta1)

**Comment by martinler** [comment]
Hello, any change to test it/confirm? Thanks

**Comment by martinler** [comment]
Hello @torkelo 
as i reported on Feb 15 i think that i've been able to give you more info about this issue - when it's happening. Please, can you confirm/deny? Thanks

**Comment by Dukeofdork** [comment]
We have the same issue. Grafana 5.1
Link in Inspector is correct, however when clicking the panel it is wrong. 

I don't know if it is a case of miss configuration, since it is working in the Inspector.

* If I select "Include variables" it is correct in the Inspector, but the "panel link"  renders to: ?var-server=All
![image](https://user-images.githubusercontent.com/12622444/39701271-d21add94-5200-11e8-85ec-ad5e64eedce9.png)

* If I define a Url param, and de-select "Include variables" the Inspector is still correct but the panel link renders: var-server=%7Server1,Server2,Server3%7D
![image](https://user-images.githubusercontent.com/12622444/39701353-2924352c-5201-11e8-82e0-d9f5b027936b.png)


The later, is almost correct, except I obviously only want one server, so like this: var-servers=Server1

**Comment by deshike22** [comment]
Has this issue fixed. I am getting the same for MySQL. But works perfectly fine with zabbix data source.
