### ISSUE TITLE
[Feature request] remove template variable from where clause when selecting "all" as the value

### ISSUE THREAD

**Issue by chenl87** [grafana/grafana#10431]
Hi,

I'm building a dashboard with some business metrics using Grafana v4.6.3. I'm using InfluxDB as the datasource and I have some tags with very high cardinality where I want to expose their values to the Dashboard's end users.
I'm currently exposing about 10 template variables with the ability to select multi-value and "all" value. Most of the time the queries will be with the "all" value. The problem is in this case that the generated query is a regex query with all available values piped for each variable.

My feature request here is to omit the relevant where clause from the query when choosing "all" as a value of a template variable.

The difference in performance here is significant. When in default all of my vars are "all" values it takes about 50 seconds for all panels to show up. Same query without the unnecessary where clauses take about 2-3 seconds.
I know I could work around it with ad hoc filters, but currently, it has a few drawbacks:
1. Can't put different labels on tags as in template vars
2. Can't choose multiple values (And I can't choose the same tag again and select "OR" between them)
Plus, I want to expose in the dashboard only the variables that are relevant to the end users (ad hoc shows all tags).

Thanks!

**Comment by dannyz29** [comment]
+1

**Comment by ssnkhan** [comment]
+1

**Comment by torkelo** [comment]
the templating system is interpolation based, so removing something before the variable is not possible. You can specify a custom all value (a regex wildcard for example).
