### ISSUE TITLE
Getting frontend panel values with JavaScript

### ISSUE THREAD

**Issue by bilportistivraboti** [grafana/grafana#10440]
What is the best way to get the values and thresholds for every panel in the frontend? Could not find API for that.

Please include this information:
- What Grafana version are you using?
Version 4.6.3 (commit: 7a06a47)
- What datasource are you using?
Graphite-api
- What OS are you running grafana on?
Debian 9

**Comment by torkelo** [comment]
you can get thresholds via the dashboard api (which returns the dashboard json model which includes the thresholds). 

The metric values are not included in any Grafana API as those are fetched directly from your data source so if you want fetch metric values you need to access your data source HTTP api directly.
