### ISSUE TITLE
Docs feedback: features/panels/singlestat.md

### ISSUE THREAD

**Issue by ianpmurphy** [grafana/grafana#10441]
There isn't anything which details what singlestat is expecting to be passed. The example query which appears isn't explained, by which I mean it doesn't say what data types are expected or what, for example, is the metric column? This maybe explained somewhere else, but I haven't found it yet and there doesn't seem to be a link to it.

**Comment by torkelo** [comment]
It is expecting a time series query that returns time series which in this case  you can select what value of the time series to show (avg, latest, etc). If your query returns table formatted data you can select column in the options tab instead.
