### ISSUE TITLE
Expose a configuration to change the max cache age.

### ISSUE THREAD

**Issue by burtonator** [grafana/grafana#10447]
Right now Grafana has the max HTTP cache age to 3600 ... or 1 hour.

The app is somewhat large and going to embedded charts is slow when our customers come back to the UI.

Changing the cache TTL to a higher value would be nice.  

You're using a version in the URL anyway so why not just make it infinity?

**Comment by torkelo** [comment]
It can be increased to infinite for revisioned js & css files, but not everthing under public

**Comment by burton-scalefastr** [comment]
agreed.  That and the woff2 and ttf fonts.  Those should benefit too. 

I think we're going to set a ACL in our load balancer to change the cache control manually.

**Comment by tpatel** [comment]
Seems like we could cache forever everything under `/public/build`. That could save almost 3Mo / reload (after 1 hour of inactivity).

**Comment by torkelo** [comment]
yes, everything under build with max age would be great.

**Comment by tpatel** [comment]
@torkelo I've just proposed a way to cache these assets in the following PR: https://github.com/grafana/grafana/pull/11536
