### ISSUE TITLE
Alert "State history" not recording alert state change

### ISSUE THREAD

**Issue by abmsalam2014** [grafana/grafana#10445]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using? v4.4.1 and Grafana database is on PostgreSQL
- What datasource are you using? InfluxDB for the graph
- What OS are you running grafana on? RedHat Linux 7
- What did you do? Configuring alert for a graph
- What was the expected result? Alert state history change when alert condition met and trigger notification
- What happened instead? Alert "State history" tab shows no state change and no notification is being triggered
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

<img width="830" alt="screen shot 2018-01-05 at 7 42 24 pm" src="https://user-images.githubusercontent.com/7095607/34634438-11e5ec66-f252-11e7-8eec-64ff50ce10d1.png">

<img width="758" alt="screen shot 2018-01-05 at 7 42 57 pm" src="https://user-images.githubusercontent.com/7095607/34634449-2bd3d174-f252-11e7-8d49-38734a3d76d3.png">

<img width="784" alt="screen shot 2018-01-05 at 7 51 00 pm" src="https://user-images.githubusercontent.com/7095607/34634457-345044f4-f252-11e7-879f-de72853b74ae.png">

**Comment by torkelo** [comment]
Test Rule does not create history events. Can you upgrade to latest? think we fixed a few sqlite3 issues in v4.5 that could cause alert history events not being saved correctly.

**Comment by abmsalam2014** [comment]
Thanks Torkelo. We are waiting for version 5 to come out to upgrade our environment since v5 has some features that we are looking for. Any idea when Grafan v5 might be released?

**Comment by torkelo** [comment]
we hope to release v5 beta in january

**Comment by abmsalam2014** [comment]
Thanks Torkelo. We got the issue resolved. Looks like the Grafana instance under the load balancer that had the alert configuration set to true was not running. Is the issue of getting multiple alerts from multiple instances under a load balancer is fixed in v5?

**Comment by rdica** [comment]
I am having this issue with 4.6.3. Should I create a new issue or continue to use this one?

![grafana-ipmi-no-history](https://user-images.githubusercontent.com/16609801/36389403-f14cf9fc-156c-11e8-9516-276d7a543bc6.png)

**Comment by rdica** [comment]
Deleting the manually added annotations made the alerting history visible on the dashboard graphs I'd added them to.

![grafana-ipmi-visible-history](https://user-images.githubusercontent.com/16609801/36400912-daa3e802-15a1-11e8-975d-0b8cec8a2147.png)

**Comment by torkelo** [comment]
yes, that looks like a new issue  @rdica

**Comment by torkelo** [comment]
I created a new issue for that, fix incoming, https://github.com/grafana/grafana/issues/10968

**Comment by mcmxii** [comment]
Hi, anyone encounter the State History got auto deleted? I'm running Grafana v5.0.0-beta4 (commit: 1de8891).
