### ISSUE TITLE
Embedded charts should have a spinner or progress indicator.

### ISSUE THREAD

**Issue by burton-scalefastr** [grafana/grafana#10446]
When embedding a chart in an iframe it's impossible to see that the chart is loading until it's done.

My chart setup now is taking 2-3 seconds and the page seems broken until it suddenly snaps into view.

**Comment by torkelo** [comment]
could not replicate this in v5

**Comment by zapic0** [comment]
I'm using 5.0.4 and still see no spinner nor indicator of loading, only a gray rectangle while loading.

**Comment by alphagoh** [comment]
Hello - has this issue been resolved?
