### ISSUE TITLE
Bug with templating & question about dynamic dashboard

### ISSUE THREAD

**Issue by swe** [grafana/grafana#10458]
- Grafana version: 4.6.2
- Database: InfluxDB
- OS: Fedora 26 (Server Edition)
- Host: crocco1, crocco2, etc... (collecting using query `SHOW TAG VALUES WITH KEY = "host"` in templating)
- DB Measurements: CPUPERF, DKCPPERF, etc... (collecting using query  
`SHOW TAG VALUES WITH KEY = "measurement" WHERE host=~ /$host/` in templating)
- DB Tags: depends on measurement (this query do not working `SHOW TAG VALUES WITH KEY = "alias" WHERE measurement=~ /$measurement/`

At first, I have such problem:
![image](https://user-images.githubusercontent.com/21012998/34709990-9d028b3a-f52a-11e7-9778-17b764d5039a.png)
I have a variable named $measurement, so I do not understand how to fix this bug.

Secondary.
Maybe do I do something wrong? I try to create a dashboard with dynamically changing data. So, if a user chooses a host, next he should choose measurement. At this time on the dashboard should show all data with any tags. After choosing measurement he should choose tag if he wants to see one tag or multiple tags. But the main problem is that I have a lot of data (graphs) in every measurement and in every measurement are different tags. So how do I solve this?

**Comment by swe** [comment]
This solution hasn't solved my problem.

**Comment by torkelo** [comment]
if you need help with influxdb query syntax please open a question on the community site (https://community.grafana.com)
