### ISSUE TITLE
Grafana 5.0.0-11057pre1: Alert notification to Telegram is not working

### ISSUE THREAD

**Issue by martinler** [grafana/grafana#10451]
- What Grafana version are you using? 5.0.0-11057pre1
- What datasource are you using? MySQL, InfluxDB
- What OS are you running grafana on? Debian 9.2
- What did you do?
a) setup notification chanel to Telegram (it's working, test message to group was delivered)
b) setup alert with targets mail and Telegram
- What was the expected result?
get notification both on mail and Telegram
- What happened instead?
got notification just on mail
![screen shot 2018-01-08 at 17 17 21](https://user-images.githubusercontent.com/19344005/34680014-0ceb87dc-f498-11e7-8998-3388da1f9817.png)

**Comment by bergquist** [comment]
Could you please enable debug logging, reproduce this and share the logs?

**Comment by xlson** [comment]
Likely to be a duplicate o #10975
