### ISSUE TITLE
How to show (currentValue-oldValue) in grafana

### ISSUE THREAD

**Issue by vsawant1608** [grafana/grafana#10459]
Read before posting: 

I have data like below

timestamp,a,aMinusAlast
2017-12-26 09:00:00,0,0
2017-12-26 09:05:00,9,9
2017-12-26 09:10:00,7,(7-9=-2)
2017-12-26 09:15:00,10,(10-7=3)
2017-12-26 09:20:00,8,-2

I need to plot the aminusAlast against time. Is there a way grafana can calculate this value?

Please include this information:
- What Grafana version are you using?
- What datasource are you using? - ElasticSearch
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Not sure elasticsearch has that query capability. 

Ask questions on the community site please :) https://community.grafana.com
