### ISSUE TITLE
Cannot specify a relative path for a data source

### ISSUE THREAD

**Issue by ritchiecarroll** [grafana/grafana#10453]
In cases where a reverse proxy is in use, a relative path would be ideal - this way a data source hosted on the same server as Grafana would be easily accessible, e.g., Grafana is on `http://myserver/grafana` where data source would be accessible via `../api/grafana`.

The UI validation in the data source configuration screen prevents entry and testing of relative paths as it is requiring a fully specified URL.

This will likely only have applicability when the data source access is set to _direct_ - as it is in this case where the "configured" data source path may not always match the client's access path which can cause access issues.

FYI, if you manually edit the data source record in the database, the relative path works just fine.

- What Grafana version are you using?
  4.6.3 (also tried 4.6.2)
- What datasource are you using?
  Issue is for any data source, although testing target is openHistorian
- What OS are you running grafana on?
  Tried Windows and Linux (various browsers)

**Comment by bergquist** [comment]
This seems like a rare use case. If more people upvote or comment on it we will consider implementing it. A simpler solution for this would be to run Grafana and the data source on different ports. Any specific reason you have to use direct access?

**Comment by torkelo** [comment]
you can use relative if you use proxy access mode (then just specify localhost in url). If you use direct access you need a full url .

**Comment by ritchiecarroll** [comment]
@bergquist 

**_More Detail:_**
 
_Background:_ If you are using a front end to Grafana, say a website in front of Grafana where reverse proxy is enabled, and this web site is responsible for security and you use `auth.proxy` to authenticate with Grafana - then direct access is preferred since host headers/cookies that control authentication are passed through all the Grafana requests back through the main web server that can validate each request for security. 

_Use Case:_ With the background operation in effect, one user may configure the direct access web site with a path that is inaccessible to another user (DNS, differing IP routes, intra vs extra net locale, etc) - in this case the solution is simple, use a relative path for direct access to Grafana data source API. Take for example that a user on the same machine may be accessing the web site via the intranet and the datasource is configured with an external DNS that resolves to an IP that only works on the internet, not on the local network - the internal user cannot use the datasource now.

_Justification:_ Ultimately I agree that this may be a rare use case, so getting up votes would take a while, however, it is extremely useful when a configuration like this in operation. The risk is low as this would simply allow a relative URL during UI validation when `access` is set to `direct`.

Thanks for your consideration.
J. Ritchie Carroll

**Comment by wbernest** [comment]
I am currently having this same issue.
