### ISSUE TITLE
Slack: Alert Notification Message only handles first @mention

### ISSUE THREAD

**Issue by agolomoodysaada** [grafana/grafana#10450]
Please include this information:
- What Grafana version are you using?
4.6.2
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Create an alert with a notification message that includes multiple @ mentions.
- What was the expected result?
All mentions to be highlighted. For example:

This is an alert message
[@person1]() [@person2]() [@person3]()

- What happened instead?
Only the first mention was highlighted and recognized in Slack.

This is an alert message
[@person1]() @person2 @person3

**Comment by byeong0430** [comment]
@agolomoodysaada I have the same issue. I found out that only @channel works..

**Comment by bergquist** [comment]
Closing this since Slack updates their API and we reworked the slack notifier since this issue was opened. https://github.com/grafana/grafana/issues/21933
