### ISSUE TITLE
Variables don't get individual values when using repeated row&panel

### ISSUE THREAD

**Issue by BitonicEelis** [grafana/grafana#10468]
Grafana version: 5.0.0-pre1
Datasource: influxdb
OS: Ubuntu 17.04

Steps to reproduce:

1. make fresh new dashboard
2. define multi-value variables "ding" and "dong" with simple enumerated values:
![variables](https://user-images.githubusercontent.com/31100282/34719473-48917abe-f53b-11e7-8fd5-9c6309add118.png)
![ding](https://user-images.githubusercontent.com/31100282/34719941-16ac5a12-f53d-11e7-97d0-b26f8854ca06.png)
(same for dong)
3. add a row, repeated for "ding":
![row](https://user-images.githubusercontent.com/31100282/34719954-28ed29cc-f53d-11e7-8891-7c72ce8b9097.png)
4. Add a text panel to the row, repeated for "dong":
![text](https://user-images.githubusercontent.com/31100282/34719963-381d02e6-f53d-11e7-90b5-29efb3a3328c.png)
5. Select "1" and "2" for "ding", and "4" and "5" for "dong".

Expected result:

I expected that I would get 4 panels, with titles:

    ding=1,dong=4
    ding=1,dong=5
    ding=2,dong=4
    ding=2,dong=5

Instead, I get 4 panels with titles:

    ding=1+2,dong=4
    ding=1+2,dong=5
    ding=2,dong=4+5
    ding=2,dong=4+5
    
Like this:

![bad](https://user-images.githubusercontent.com/31100282/34720089-cdb69b6e-f53d-11e7-8d87-d3a36cf05122.png)

**Comment by torkelo** [comment]
combining row and panel repeats has never 100% been supported. but it does look like support has degraded in v5
