### ISSUE TITLE
grafana_5.0.0-11111pre1 : (pie chart) _this2.$rootScope.colors is undefined

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#10462]
- What Grafana version are you using?
grafana_5.0.0-11111pre1

Pie chart panel error with any datasource.
Version grafana_5.0.0-11065pre1 didn't have this issue.

![image](https://user-images.githubusercontent.com/20041843/34714902-c63d5cb2-f522-11e7-9a43-a929b8f8b3b9.png)

**Comment by torkelo** [comment]
thanks for reporting this! fixed!
