### ISSUE TITLE
Singlestat Panel Current Value Incorrect

### ISSUE THREAD

**Issue by ivoribeiro** [grafana/grafana#10466]
Please include this information:
- What Grafana version are you using? : Version 4.6.3 (commit: 7a06a47)
- What datasource are you using? : alexanderzobnin/grafana-zabbix
- What OS are you running grafana on? : Linux loqr-monitoring-vm 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- What did you do? : Singlestat panel 
- What was the expected result? Current value
- What happened instead?  Average value
![captura de ecra_2018-01-09_10-25-27](https://user-images.githubusercontent.com/15598128/34716798-d73d7dca-f528-11e7-96d9-2ac233deb511.png)
- If related to metric query / data viz:
 ![captura de ecra_2018-01-09_10-26-17](https://user-images.githubusercontent.com/15598128/34716777-c4ff3a5e-f528-11e7-9c6f-a34aa8bec0b4.png)

**Comment by torkelo** [comment]
strange, unable to replicate. if you hit refresh do you get the same? does your screenshot show the last value?

**Comment by ivoribeiro** [comment]
Refresh doesn't resolv , the last value is 0 Or 1 not  a decimal number :/

A ter, 9/01/2018, 12:57, Torkel Ödegaard <notifications@github.com>
escreveu:

**Comment by torkelo** [comment]
and can you show panel json?

**Comment by ivoribeiro** [comment]
Now is everything ok, i will take a print when the problem comes again.
![captura de ecra_2018-01-09_14-38-51](https://user-images.githubusercontent.com/15598128/34726119-012ca3e6-f54b-11e7-8ff0-6734ca284984.png)
