### ISSUE TITLE
[bug] prometheus datasource multi-value template variable expand incorrect

### ISSUE THREAD

**Issue by jiming** [grafana/grafana#10461]
Please include this information:
- What Grafana version are you using?
   4.6.3
- What datasource are you using?
  prometheus 2.0
- What OS are you running grafana on?
  ubuntu 16.04
- What did you do?
  plot multiple line with `  by (service)`
- What was the expected result?
   plot multiple line
- What happened instead?
   plot only the first 
- If related to metric query / data viz:
  `sum(rpc_durations_seconds{service=~'$serviceName'}) by (service)` only draw one line, I already selected `normal and uniform`, which is wrong  
   query inspector result is, which replace the $serviceName as `normal` instead of `(normal|uniform)` as document described
```
xhrStatus:"complete"
request:Object
method:"GET"
url:"http://kudu:9090/api/v1/query_range?query=sum(rpc_durations_seconds%7Bservice%3D~'normal'%7D)%20by%20(service)&start=1515404291&end=1515490631&step=600"
```

  - `sum(rpc_durations_seconds{service=~'normal|uniform'}) by (service)` draw two line correctly
 
from https://community.grafana.com/t/single-graph-with-multiple-plots-for-multi-value-template-variable/856 

I found some hint.
 I tried the play.grafana.com, which is correct. So I guess it is a new bug introduced in newer version.

Thanks!

Jiming

**Comment by torkelo** [comment]
strange, no other reports like this and unable to replicate. Can you show your variable config?

**Comment by jiming** [comment]
![image](https://user-images.githubusercontent.com/455978/34718359-4add4862-f571-11e7-93aa-f4afc0b313e2.png)

**Comment by jiming** [comment]
![image](https://user-images.githubusercontent.com/455978/34718648-76cdce50-f572-11e7-875b-7f36275e6b92.png)

**Comment by jiming** [comment]
@torkelo Any suggestion please?

**Comment by torkelo** [comment]
for what? you specified aaaa in Legend format and that is the name the series got. Looks to be working. What do you want to do?

**Comment by jiming** [comment]
Thanks @torkelo 

 I marked `aaaa` to make it more clear. Apparently it mislead you. 

Let me try to show it again. I capture two pictures, one hide query A and one hide query B. They are the same panel. They are supposed to output same result. But they are not as expected.

* Hide query B  
![Hide query B](https://user-images.githubusercontent.com/455978/34818739-b27b5f32-f6f6-11e7-93e0-21db3de05ffc.png)

* Hide query A  
![Hide query A](https://user-images.githubusercontent.com/455978/34818766-c717c7b4-f6f6-11e7-8a23-6bae5592f640.png)



And please take a look at query inspector of query A please, it just did not expand the `serviceName` to `(normal|uniform)` as expected.

![image](https://user-images.githubusercontent.com/455978/34818938-4349ef88-f6f7-11e7-9bfa-923de5760c1f.png)

**Comment by tettaji** [comment]
I'm having the same issue, where a multi-value template variable isn't expanded in a query to Prometheus.

Let's say you've got a multi-value variable named `var`, with values `something` and `otherthing`.

And in a graph you're querying Prometheus the following:
```
query{key=~"$var"}
```
You would expect Grafana to send the following query to Prometheus, right?
```
query{key=~"(something|otherthing)"}
```
But instead, the actual query being sent is:
```
query{key=~"something"}
```

**Comment by torkelo** [comment]
Have you selected two values? No other reports on issues with multi-valued template variables for prometheus (and this is a very common setup) so it sounds strange.

**Comment by marefr** [comment]
@tettaji is using start of regex syntax do any difference? Like

`query{key=~"^$var"}`

**Comment by tettaji** [comment]
Nope, after some mucking about, I figured out what the issue was in my case (maybe this help @jiming as well).

I entered `.*` as the "Custom All value", which somehow caused only the first value from the template variable to be used. If I leave the field blank, the query is correctly expanded to `query{key=~"something|otherthing"}`.

I do find this behaviour a bit odd though; if leaving the field empty is the correct way to expand variables like this, I would expect it to also query with whatever is entered in that field, i.e. `key=~".*"`.

Maybe it would be a good idea to have this documented in http://docs.grafana.org/reference/templating/#formating-multiple-values ?

**Comment by marefr** [comment]
@tettaji contributions are always very welcome. If you want to update the documentation and submit a pull request for that it would be awesome :+1:

**Comment by tettaji** [comment]
@marefr done: https://github.com/grafana/grafana/pull/11412

**Comment by jiming** [comment]
Thanks @tettaji

**Comment by bkez322** [comment]
I'm also having this issue on Grafana v5.1.0. 

I do not have "Custom All Value" set. 

The variable value preview shows multiple value for a query, but only one value seems to be used when I check the Prometheus query inspector (and I am using `~=`).

**Comment by bkez322** [comment]
I detail the issue I'm having more here: https://community.grafana.com/t/possible-bug-multi-value-variable-query-appears-to-not-be-working/9361
