### ISSUE TITLE
Close/hide 'Add Panel' before saving a dashboard

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10472]
I find it quite weird that you can save a dashboard when you have the *Add Panel* opened. This will result in that the *Add Panel* are visible next time you visit your saved dashboard.

~~Shouldn't we always close the *Add Panel* before saving a dashboard?~~

We should close/hide the *Add Panel* if open before saving a dashboard.

Kind of related to #10299

**Comment by torkelo** [comment]
yes!
