### ISSUE TITLE
bug: histogram mode in graph panel ignores groups

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#10479]
- What Grafana version are you using?  grafana_5.0.0-11111pre1
- What datasource are you using?  InfluxDB

The histogram legend in the graph panel only shows "count #" even when the data is grouped.

It probably wasn't supposed to, but the previous version (v4.x) did show colored group counts, though the graph didn't represent those colors in the bars, it was useful to see the grouped counts that could be sorted.

**Comment by torkelo** [comment]
there is already a feature request for this, https://github.com/grafana/grafana/pull/8613
