### ISSUE TITLE
Query to prometheus is distorted under certain conditions

### ISSUE THREAD

**Issue by alxrem** [grafana/grafana#10471]
- What Grafana version are you using?
4.6.3 (latest docker image)
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
linux (docker environment)
- What did you do?
1. Configure prometheus server with exporter that contains '.' (dots) in the name of instance.
1. Configure datasource of type "prometheus" in the proxy mode.
1. Create variable `instance` by the query `label_values(instance)` and select option "Include All option".
1. Create graph with the metric that uses this variable f.e. `http_requests_total{instance="$instance"}`
- What was the expected result?
Graph of the selected metric.
- What happened instead?
"No data points" message on the panel.
In the Query inspector we can see that value of `$instance` is passed as `127%5C%5C.0%5C%5C.0%5C%5C.1`
- If related to metric query / data viz:
```
 {
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/api/v1/query_range?query=http_requests_total%7Binstance%3D%22127%5C%5C.0%5C%5C.0%5C%5C.1%3A9090%22%7D&start=1515498668&end=1515499568&step=30"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": []
    }
  }
}
```
Here is configs to quickly reproduce bug with docker-compose: [grafana-bug.zip](https://github.com/grafana/grafana/files/1615022/grafana-bug.zip)

Run environment by `docker-compose up`, open grafana at http://localhost:3000, create proxied datasource named "prometheus" with address http://prometheus:9090 and import dashboard from `dashboard.json`

**Comment by torkelo** [comment]
if you enable all your query must use regex operator 

http_requests_total{instance=~"$instance"}
