### ISSUE TITLE
[Bug] Templates dropdown go under the graphes in grafana 5

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10481]
It happens often that in Grafana 5 we can not select values of the variables because the dropdown is under the panels.

![templa](https://user-images.githubusercontent.com/291750/34742107-5c509914-f585-11e7-9c55-e38918a2ec60.png)

Happens with both graph panel and text panel.

grafana-5.0.0-11081pre1

**Comment by torkelo** [comment]
what browser & OS are you using?

**Comment by roidelapluie** [comment]
Chrome and firefox on Windows and linux

**Comment by roidelapluie** [comment]
How to reproduce:

1. Create a templated value which requires a dropdown.
2. Add a graph to the dashboard.
3. Click the graph.

**Comment by roidelapluie** [comment]
https://gist.github.com/74a4e3b1362b3f3920c1ad707685a8ac

**Comment by roidelapluie** [comment]
Update: to reproduce, click on the title of the graph.

**Comment by torkelo** [comment]
ah, I see. @alexanderzobnin must be related to your z-index work around for the grid & panel menus. Seems clicking on a panel title causes its zindex to be higher than the variable dropdowns

**Comment by alexanderzobnin** [comment]
@torkelo Yes, confirmed. Working on the fix.
