### ISSUE TITLE
How to write query in InfluxDB  templating

### ISSUE THREAD

**Issue by Ram6562** [grafana/grafana#10483]
i want to replicate following templating query intto InfluxDB templating,  please help me

 [`dats.duration.var_loop.*.$org.*.*`]   

- What Grafana version are you using?
    v4.6.2
- What datasource are you using?
    InfluxDB
- What OS are you running grafana on?
   Ubuntu

**Comment by torkelo** [comment]
please use community site for questions (https://community.grafana.com), I think this is the 4th time I have informed you of this. If you open another question I might have to block from ever opening a github issue on this repository again (would prefer not to do this).
