### ISSUE TITLE
Grafana drops graph details (looks like 30 sec aggregation)

### ISSUE THREAD

**Issue by Savemech** [grafana/grafana#10489]
- What Grafana version are you using?
Version with bug is 4.6.3 (didn't test other versions)
- What datasource are you using?
Prometheus 2.0+
- What OS are you running grafana on?
Ubuntu 16.04 from apt repo
- What did you do?
Update Grafana from 4.6.0-beta3 commit 9a91a88 to 4.6.3 (beta to stable)
- What was the expected result?
Awesome graphs, these annotations https://community.grafana.com/t/release-notes-v4-6-x/3179
- What happened instead?
All broken, 😭 
Good:
[![good](https://i.imgur.com/IrKImw7.png)](https://i.imgur.com/IrKImw7.png)
Bad:
[![bad](https://i.imgur.com/LfFuQ0M.png)](https://i.imgur.com/LfFuQ0M.png)

This is very same graphs, nothing else changed, just hit F5 and click View

**Comment by Savemech** [comment]
And actually I did notice, we have TV on wall, so after grafana was updated, and this very same graph still is present, but js code under the hood is not refreshed by hitting F5, all graphs looking good, so this is definitely somewhere on frontend(I suppose).

**Comment by Savemech** [comment]
Also, https://github.com/grafana/grafana/pull/8073 may related

**Comment by torkelo** [comment]
please include graph settings and your prometheus query and the response from prometheus. 

You can find the raw response from prometheus in the Query insector in graph metrics tab.

**Comment by torkelo** [comment]
Since you seem to have a very low scrape interval. You need to specify this interval in your grafana data source edit page.

**Comment by Savemech** [comment]
Well, I did upgrade again to latest version, and if I drop 5s(which is I use for installations) it's show same as for "Bad" Graph screenshot.
If I go for scrape interval 1s, I see sharp, as before. 
Does it counter as a bug?

**Comment by jeffmendoza** [comment]
@torkelo I see the same behavior. I posted my details here: https://community.grafana.com/t/bad-prometheus-graphs-starting-with-4-6-2/5162
