### ISSUE TITLE
snapshot of dashboard containing graphs gives "unauthorized" error

### ISSUE THREAD

**Issue by ArnY** [grafana/grafana#10484]
- What Grafana version are you using?
4.6.3
- What datasource are you using?
influxdb and zabbix. The problem is present with both
- What OS are you running grafana on?
Debian Stretch (9.3)
- What did you do?
Created a dashboard with several panels: graphs, single values, tables. Generated a snapshot for that dashboard. 
- What was the expected result?
The snapshot should load with all data visible and no error
- What happened instead?
The dashboard loads properly but gives a popup "Unauthorized" and all the graphs are empty. Single value panels and tables are properly working. Tested with only one graph and the problems shows up not matter the datasource I used: zabbix or influxdb.
 
Chrome's dev tools show the error could be related to annotations, could be related to #7659 ?
![snapshot](https://user-images.githubusercontent.com/138363/34764686-8a191d02-f5ef-11e7-8a58-ca225e5f87ab.png)

**Comment by torkelo** [comment]
this is due to the graph metric query not finishing on time, try increase the timeout when you make the snapshot

**Comment by ArnY** [comment]
indeed, that was it. Thanks! The error wasn't very explicit.

**Comment by beerygaz** [comment]
I have the same issue,. my timeout is set to 20 seconds, the snapshot renders in under 2 nut I still get the popup.  Just simple graphs, no alerts or annotations.

**Comment by donkidd** [comment]
@beerygaz I have the same issue have you snapshot loads fast, only graphs loads in seconds. Timeout it longer, have you figured out what to do about this?
