### ISSUE TITLE
Alert Notification Channels as configuration

### ISSUE THREAD

**Issue by ThomasVdBerge** [grafana/grafana#10487]
Since Grafana v5.0.0-pre1, we are now able to use datasources as configuration. The one thing I am still missing is the set Alert Notification Channels as Configuration.

**Comment by wangchaobin** [comment]
Looking foward to this feature.
For some security reason, channels and rules are very difficlut to migrate. If store them as conf file just like dashboards  would be perfect.

**Comment by peay** [comment]
Unless someone's already working on this, I'll give it a try.

**Comment by bergquist** [comment]
To make this really good we need to change how `alerts` refer to `alert notifications`

The alerting model refers to alert notifiers via the numeric ID. So it's very tricky to provision dashboard with alerts using provisioned alert notifiers since we cannot guarantee the order of who alert notifiers are inserted into the DB. To solve this we should introduce string ID's for alert notifiers, just like dashboards and support numeric and string id's when referring to alert notifiers in the alerting model.

**Comment by peay** [comment]
How about adding a `[]string` field `NotificationsNames` to `alerting.Rule`?

`orgId, name` is already a unique key for alert notification channels, so a list of names in a rule should uniquely identify a set of alert notifications. `NewRuleFromDBAlert` can be modified to add the corresponding numeric IDs to `model.Notifications`, in addition to those it already adds from `rule.Notifications`. Adding a new field as opposed to modifying the existing `Notifications       []int64` would make the change backward compatible.

This new field would only be used when provisioning from a YAML file, though: editing in the UI would still set use numeric IDs.

**Comment by bergquist** [comment]
The problem with using names is that alert notifiers cannot be renamed without breaking all the alerts using that alert notifiers. We need to support both `{"uid": "938459"}` and old numeric id to be backward compatible. 

When introducing the new uid field we can migrate all current notifiers like we did with dashboards https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/dashboard_mig.go#L160

**Comment by peay** [comment]
Names would only be used when you provision from YAML though, everything else would still use numeric IDs. But OK, point taken, let me have a stab at adding `uid` to alert notification channels. Do you prefer this done in https://github.com/grafana/grafana/pull/11747 or in a separate PR?

**Comment by ramato-procon** [comment]
Can you add this to 5.3 please?

**Comment by sirkjohannsen** [comment]
Pretty please ???? :heart_eyes:

**Comment by albestia** [comment]
Please!!! We are trying to automate deployment process and this is our lasting task.
If I can help in any way...

**Comment by machbio** [comment]
```
sqlite> .schema alert_notification
CREATE TABLE `alert_notification` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `org_id` INTEGER NOT NULL
, `name` TEXT NOT NULL
, `type` TEXT NOT NULL
, `settings` TEXT NOT NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
, `is_default` INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX `UQE_alert_notification_org_id_name` ON `alert_notification` (`org_id`,`name`);
```

**Comment by Lukkie** [comment]
Any updates on this?

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/14229
