### ISSUE TITLE
use kafka as notification channel fail response status 415 

### ISSUE THREAD

**Issue by hereTac** [grafana/grafana#10492]
Please include this information:
- What Grafana version are you using?  4.6.3
- What datasource are you using?  influxdb
- What OS are you running grafana on? centos6.7

-----------------------------------------------------------------
I want to use kafka as my notification channel .Here is the Setting.
Kafka settings
Kafka REST Proxy
http://172.31.10.136:8082
Topic
test
`Failed to send alert notifications`

-----------------------------------------------------------------
Here is the error log 
`t=2018-01-11T15:12:07+0800 lvl=info msg="Alert Rule returned no data" logger=alerting.evalHandler ruleId=11 name="hdfs fs -ls . 响应(s) alert" changing state to=no_data

t=2018-01-11T15:12:07+0800 lvl=info msg="New state change" logger=alerting.resultHandler alertId=11 newState=no_data prev state=alerting

t=2018-01-11T15:12:07+0800 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=11 sent count=1

t=2018-01-11T15:12:07+0800 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/hadoop_cluster-ji-qun-zheng-ti-gai-kuang-liao-jie-wo-men-de-ji-qun?&panelId=11"

t=2018-01-11T15:12:08+0800 lvl=info msg=uploaded logger=alerting.notifier url=

t=2018-01-11T15:12:08+0800 lvl=info msg="Sending notification" logger=alerting.notifier type=kafka id=3 isDefault=false

t=2018-01-11T15:12:08+0800 lvl=info msg="Notifying Kafka" logger=alerting.notifier.kafka alert_state=no_data

t=2018-01-11T15:12:08+0800 lvl=eror msg="Failed to send notification to Kafka" logger=alerting.notifier.kafka error="Webhook response status 415 Unsupported Media Type" body="{\"records\":[{\"value\":{\"client\":\"Grafana\",\"client_url\":\"http://localhost:8080/dashboard/db/hadoop_cluster-ji-qun-zheng-ti-gai-kuang-liao-jie-wo-men-de-ji-qun?fullscreen\\u0026edit\\u0026tab=alert\\u0026panelId=11\\u0026orgId=1\",\"description\":\"hdfs fs -ls . 响应(s) alert - fghfth\",\"details\":\"Triggered metrics:\\n\\n\",\"incident_key\":\"alertId-11\"}}]}"`

-----------------------------------------------------------------
I install confluent's kafka-rest 3.0.1 . I tested the example.

**Comment by torkelo** [comment]
@utkarshcmu any idea?

**Comment by zhangxin0112** [comment]
I change confluent's to 1.0.It still error. The same error messages like above what described.
It is seem bug with some headers.  Hope your answer. @utkarshcmu

"There are some headers which need to be set for Kafka REST Proxy, which I have added in the code. Also, in the future we might want to move to a more native TCP based alerting for Kafka instead of HTTP."

**Comment by tinder-ubhatnagar** [comment]
I will look into this today and see why we are facing issues sending alerts to Kafka via Proxy.
