### ISSUE TITLE
How to write template query in influxdb grafana

### ISSUE THREAD

**Issue by Ram6562** [grafana/grafana#10491]
how to replicate following graphite template to influxdb template query in grafana v4.6.2

`stats.timers.call_loop.*.$org.*.*`

**Comment by torkelo** [comment]
Sorry, I am  do you understand written english?  I have asked you to post questions on the community site 5 times now :( This is not very nice of you. 

https://github.com/grafana/grafana/issues/10483#issuecomment-356570011
