### ISSUE TITLE
DAX metrics support

### ISSUE THREAD

**Issue by Enigo** [grafana/grafana#10494]
Hello team,

please, add support for DAX CloudWatch metrics.

- What Grafana version are you using? 
Grafana v4.6.3 (commit: 7a06a47)
- What datasource are you using?
AWS
- What OS are you running grafana on?
Linux

There are the whole bunch of metrics,  for example, check this [article](https://aws.amazon.com/blogs/aws/amazon-dynamodb-accelerator-dax-in-memory-caching-for-read-intensive-workloads/)

Thanks!

**Comment by sunker** [comment]
@Enigo resource DynamoDb and its metrics are already supported. What more do you want?

**Comment by Enigo** [comment]
@sunker 
resource DynamoDb != resource DAX
there is the list with all the metrics available for DAX
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/dax-metrics-dimensions-dax.html

and also we are now on Grafana v6.3.3 (84d0a71) and I still don't see any DAX metrics there

**Comment by kenju** [comment]
@Enigo @sunker 

Hi 👋 

I'm working on the same problem with you, and I submitted a PR just now 
👉 https://github.com/grafana/grafana/pull/21644
