### ISSUE TITLE
Support JavaFx Webview

### ISSUE THREAD

**Issue by thhart** [grafana/grafana#10496]
Please include this information:

* What Grafana version are you using?
4.6.3
* What datasource are you using?
InfluxDb
* What OS are you running grafana on?
openSUSE Tumbleweed, Linux hp 4.14.12-1-default #1 SMP PREEMPT Fri Jan 5 18:15:55 UTC 2018 (3cf399e) x86_64 x86_64 x86_64 GNU/Linux
* What did you do?
Opened Grafana in a JavaFx Webview renderer
* What was the expected result?
Graphs should look like the same as in Firefox
* What happened instead?
Webview can not render graph grid and graph samples in a Java(TM) SE Runtime Environment (build 1.8.0_151-b12) client. Grafana is fully interactive and responsive except the graphs are rendered correct.

These are two screenshots how rendering looks ok and how rendering fails in a JavaFx WebView.

Firefox all graphs visible:
![grafana - host overview - mozilla firefox!UNITO-UNDERSCORE!223](https://user-images.githubusercontent.com/2632538/34835833-5c87bcec-f6f6-11e7-9cca-94f8e5356902.png)

Webview with same data and time range:
![javafx webview!UNITO-UNDERSCORE!224](https://user-images.githubusercontent.com/2632538/34835837-6003b6e6-f6f6-11e7-8652-198ab0caf1e5.png)

This is the code how the Webview is constructed.

```
package test;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.web.*;
import javafx.stage.Stage;

public final class TestBrowser extends Application {
public static void main(String[] args) {
launch(args);
}

@Override
public void start(Stage stage) throws Exception {
stage.setTitle("JavaFX: WebView");

WebView webView = new WebView();
webView.setFontScale(1.5);
WebEngine webEngine = webView.getEngine();
webEngine.setJavaScriptEnabled(true);
EventHandler<WebErrorEvent> handler = new EventHandler<WebErrorEvent>() {
public void handle(WebErrorEvent event) {
System.err.println(event.getMessage());
}
};
webEngine.setOnError(handler);
webEngine.setOnAlert(new EventHandler<WebEvent<String>>() {
public void handle(WebEvent<String> event) {
System.err.println(event.getData());
}
});
//webEngine.setAllowFileAccess(true);
String url = "http://192.168.188.87:3000/dashboard/db/host-overview?orgId=1";
webEngine.load(url);

StackPane sp = new StackPane();
sp.getChildren().add(webView);

Scene root = new Scene(sp);

stage.setScene(root);
stage.show();
}
}

```

**Comment by bergquist** [comment]
I'm not sure we will every give first-hand support from the grafana core team for JavaFx webview. I'm leaving this issue open if more people have the same problem or have a solution.

**Comment by Reygok** [comment]
I have the exact same problem, just so you know this is still relevant

**Comment by bergquist** [comment]
Please try the new 5.0 beta.

**Comment by thhart** [comment]
Thanks for picking up. I tested a new fresh install. The problem is a bit different. It does not get to a point for loading any data now. It popups a warning box with a network error. The error appears regardless if I chose a predefined Dashboard or create a new Panel without any datasource attached yet:

Network error: undefined(undefined)

Version: Grafana v5.0.0-beta3 (commit: 5e33a52) 

![javafx webview_231](https://user-images.githubusercontent.com/2632538/36384322-32f1ec6a-158f-11e8-8acb-f52ac681ee4a.png)

**Comment by torkelo** [comment]
Closing this due to lack of interest

**Comment by SammyDerksen** [comment]
> Please include this information:
> 
> * What Grafana version are you using?
>   4.6.3
> * What datasource are you using?
>   InfluxDb
> * What OS are you running grafana on?
>   openSUSE Tumbleweed, Linux hp 4.14.12-1-default [Duplicate panel with 3 x colspan 3 panels will add not add to empty row #1](https://github.com/grafana/grafana/issues/1) SMP PREEMPT Fri Jan 5 18:15:55 UTC 2018 ([3cf399e](https://github.com/grafana/grafana/commit/3cf399e8fcb46470f0cdfb1d1f3e8f58b23d26c0)) x86_64 x86_64 x86_64 GNU/Linux
> * What did you do?
>   Opened Grafana in a JavaFx Webview renderer
> * What was the expected result?
>   Graphs should look like the same as in Firefox
> * What happened instead?
>   Webview can not render graph grid and graph samples in a Java(TM) SE Runtime Environment (build 1.8.0_151-b12) client. Grafana is fully interactive and responsive except the graphs are rendered correct.
> 
> These are two screenshots how rendering looks ok and how rendering fails in a JavaFx WebView.
> 
> Firefox all graphs visible: ![grafana - host overview - mozilla firefox!UNITO-UNDERSCORE!223](https://user-images.githubusercontent.com/2632538/34835833-5c87bcec-f6f6-11e7-9cca-94f8e5356902.png)
> 
> Webview with same data and time range: ![javafx webview!UNITO-UNDERSCORE!224](https://user-images.githubusercontent.com/2632538/34835837-6003b6e6-f6f6-11e7-8652-198ab0caf1e5.png)
> 
> This is the code how the Webview is constructed.
> 
> ```
> package test;
> 
> import javafx.application.Application;
> import javafx.event.EventHandler;
> import javafx.scene.Scene;
> import javafx.scene.layout.StackPane;
> import javafx.scene.web.*;
> import javafx.stage.Stage;
> 
> public final class TestBrowser extends Application {
> public static void main(String[] args) {
> launch(args);
> }
> 
> @Override
> public void start(Stage stage) throws Exception {
> stage.setTitle("JavaFX: WebView");
> 
> WebView webView = new WebView();
> webView.setFontScale(1.5);
> WebEngine webEngine = webView.getEngine();
> webEngine.setJavaScriptEnabled(true);
> EventHandler<WebErrorEvent> handler = new EventHandler<WebErrorEvent>() {
> public void handle(WebErrorEvent event) {
> System.err.println(event.getMessage());
> }
> };
> webEngine.setOnError(handler);
> webEngine.setOnAlert(new EventHandler<WebEvent<String>>() {
> public void handle(WebEvent<String> event) {
> System.err.println(event.getData());
> }
> });
> //webEngine.setAllowFileAccess(true);
> String url = "http://192.168.188.87:3000/dashboard/db/host-overview?orgId=1";
> webEngine.load(url);
> 
> StackPane sp = new StackPane();
> sp.getChildren().add(webView);
> 
> Scene root = new Scene(sp);
> 
> stage.setScene(root);
> stage.show();
> }
> }
> ```

I have the same Problem. It should look like this:
![image](https://user-images.githubusercontent.com/66695048/185636524-a9221a70-4663-41d1-9454-1e9c4096b238.png)

but it looks like this:
![image](https://user-images.githubusercontent.com/66695048/185636622-d1bb79f4-c74c-4941-967c-9f38647f3f4e.png)
