### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by burton-scalefastr** [grafana/grafana#10499]
Using Grafana 4.6.2 with Prometheus 2.0.0

I'm receiving this error:

16metrics_panel_ctrl.ts:171 Panel data error: TypeError: Cannot read property 'replace' of undefined
    at r (datasource.ts:95)
    at m (lodash.js:660)
    at Function.pa [as map] (lodash.js:9570)
    at t.interpolateQueryExpr (datasource.ts:143)
    at Object.formatValue (templateSrv.js:116)
    at templateSrv.js:228
    at String.replace (<anonymous>)
    at Object.replace (templateSrv.js:200)
    at t.createQuery (datasource.ts:231)
    at t.query (datasource.ts:166)

what's REALLY weird is that I can't change/fix the metric:

This is what it looks like:

![image](https://user-images.githubusercontent.com/33988567/34851171-bc52b88e-f6dd-11e7-8384-f5df5b34f72d.png)

This is what a functional metric looks like.

![image](https://user-images.githubusercontent.com/33988567/34851196-d0d7da28-f6dd-11e7-8dab-459e935475b1.png)

... so I'm unable to actually fix these metrics due to some Grafana bug.

**Comment by burton-scalefastr** [comment]
Looks like this is being triggered by the 'node' tag not present on these metrics.  Once I added it the error went away.

**Comment by torkelo** [comment]
strange, can you try to remove the query and re-add it, do you get the same ?

**Comment by burton-scalefastr** [comment]
I can't re-add it... The only way it will work is if I manually specify a 'node' tag.

Then it works. 

But if I specify 'all' the metrics without the node tag cause it to break.

Once it's in broken state I can't fix it in the UI and need to reload.

... basically all the tags are required.

**Comment by torkelo** [comment]
what is the value of your template variable when you get this bug? (can you open dashboard View JSON) find the templating section in the json and copy paste it here?

**Comment by burton-scalefastr** [comment]
The variable in the metric is missing. So I imagine it's null... 

The metric has cycled through so I can try to pull it up on older chart data if necessary.

**Comment by mattrussi** [comment]
Grafana: v4.6.1
Prometheus: v1.8.2

We are experiencing the same issue. @torkelo, here are the templating values from the dashboard JSON.

This is the default view of the dashboard which works.
```
      {
        "allValue": null,
        "current": {
          "text": "cassandra",
          "value": "cassandra"
        },
        "datasource": "$environment",
        "hide": 0,
        "includeAll": false,
        "label": "",
        "multi": false,
        "name": "configuration",
        "options": [],
        "query": "label_values(jvm_info,job)",
        "refresh": 1,
        "regex": "([A-Za-z0-9\\_]+)",
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
```

Changing 'configuration' value to 'kafka' outputs this. The only difference I can see is that it now adds the 'tags' attribute to 'current'.
```
      {
        "allValue": null,
        "current": {
          "tags": [],
          "text": "kafka",
          "value": "kafka"
        },
        "datasource": "$environment",
        "hide": 0,
        "includeAll": false,
        "label": "",
        "multi": false,
        "name": "configuration",
        "options": [],
        "query": "label_values(jvm_info,job)",
        "refresh": 1,
        "regex": "([A-Za-z0-9\\_]+)",
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
```

All panels now show this error like @burton-scalefastr's OP.
```
Panel data error: TypeError: Cannot read property 'replace' of undefined
    at r (datasource.ts:94)
    at m (lodash.js:660)
    at Function.pa [as map] (lodash.js:9570)
    at t.interpolateQueryExpr (datasource.ts:141)
    at Object.formatValue (templateSrv.js:116)
    at templateSrv.js:228
    at String.replace (<anonymous>)
    at Object.replace (templateSrv.js:200)
    at t.createQuery (datasource.ts:229)
    at t.query (datasource.ts:164)
```

**Comment by torkelo** [comment]
Can you try Grafanav 5.2? think this has been fixed
