### ISSUE TITLE
[bug] Export to CSV should use dashboard timezone setting

### ISSUE THREAD

**Issue by dmossie** [grafana/grafana#10497]
I am having an issue exporting data. I think the issue is I am trying to export the data in UTC, but it exports it in local time.

![excel](https://user-images.githubusercontent.com/30665550/34845333-62ce12d6-f6c9-11e7-9708-ca387b1a7ed1.png)
![grafana](https://user-images.githubusercontent.com/30665550/34845334-62e77e56-f6c9-11e7-96f0-6ca1b625fef3.png)

I discussed this with @DanCech on Slack.
Right now it's going to use the browser timezone for the export because it just uses `moment(<timestamp).format(<format)`

**Comment by marefr** [comment]
Relabeling this as bug instead of feature due to report in #11427

**Comment by svet-b** [comment]
I had a go at a fix. Would appreciate any feedback!

**Comment by marefr** [comment]
Weird. Reopening this. Thanks for pointing this out.

**Comment by svet-b** [comment]
Yeah I don't think that a fix was ever put in, and I never got the chance to fix up my PR either. Unfortunately probably won't get a chance to do that in the near future, though maybe it could serve as a ("nearly-there") basis for someone else. https://github.com/grafana/grafana/pull/11453
