### ISSUE TITLE
[Bug] Decimal points always +1 to configured value making impossible to set 1 decimal place

### ISSUE THREAD

**Issue by elektro255** [grafana/grafana#10490]
**Steps to reproduce:**
1. Go to http://play.grafana.org
2. Edit server requests grph, set Axes->Left Y->Decimals to 1
3. Hover over the graph or show min/max values in legend

**Expected:**
Number of decimal places is 1
**Actual:**
Number of decimal places is 2 (it is always +1 to the set value except for the 0)

Grafana version: 4.6.1, 4.6.3

 
![screenshot from 2018-01-10 13-06-30](https://user-images.githubusercontent.com/7024830/34795765-370f994c-f608-11e7-998d-74210c71e0c7.png)

**Comment by torkelo** [comment]
tooltip decimals are controlled via setting legend decimals. (Go to legend tab). Why this difference? The y-axis decimals do not need as much precision usually.
