### ISSUE TITLE
[Bug] Grafana 5 Pie Chart - No right side display

### ISSUE THREAD

**Issue by dxm765** [grafana/grafana#10498]
Please include this information:
- What Grafana version are you using? Grafana v5.0.0-pre1 (commit: f3a66ec) (January 11th 2018 install)
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Ubuntu Server 16 LTS
- What did you do? Make Pie chart
- What was the expected result? Display measurements based on legend position I select.
- What happened instead? No measurement displayed when "right side" selected.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Recently started testing Grafana 5 Alpha to tinker with the new grid, imported my previous Grafana 4.6.x dashboard with the same datasources and realized my pie charts with right side legends did not display.

Photo's here: https://imgur.com/a/KEKUq

**Comment by bergquist** [comment]
Thank you for reporting this but this should be opened at https://github.com/grafana/piechart-panel

Closing this.

**Comment by torkelo** [comment]
we have a fix, need to merge it and publish a new version of pie chart panel, 
https://github.com/grafana/piechart-panel/pull/114/files
