### ISSUE TITLE
Data source query pre flight OPTIONS request does not use credentials

### ISSUE THREAD

**Issue by janhurst** [grafana/grafana#10503]
When a panel is making a target query I can see the pre flight OPTIONS request that hits my Web API controller being rejected as unauthorized. 

Inspecting the headers of the request (via Fiddler) I can see that no authentication headers are sent in the OPTIONS request. 

I am expecting the pre flight OPTIONS request to include authentication headers.

My Web API controller is configured only to allow windows authentication.

I have traced this back (I think) to the backend_srv.ts line 93 after which I get a little lost. (apologies I am only just starting my Javascript journey :))

I'm not sure exactly what the $http property holds, but I am assuming it is an injected HTTP client of some type.

I am running the binary Grafana v4.6.3 (commit: 7a06a47e6) on a Windows 7 development machine.

The data source is based upon simple-json-datasource. The only part of the datasource that I am modifying are the methods that make requests against my Web API. I am simply converting the Grafana javascript objects into my Web API's format, and converting the response that I get back into Grafana's expected structure.

In the data source configuration, I am setting "with credentials", which is working as expected for the target search etc

**Comment by torkelo** [comment]
this is up to the browser, they do not send credentials in the OPTIONS call , so your api cannot have auth enabled for this HTTP method

**Comment by janhurst** [comment]
@torkelo thanks, but that does not make sense to me.

the call to $http is being passed an object that has various parameters for the http call. i would have assume that there is a javascript based http client that is making the actual request?

**Comment by torkelo** [comment]
well the OPTIONS call is not made by javascript / Grafana, it is made by the Browser to check if the domain allows for access outside it's domain (CORS check). So there is no control over this call as it's a built in security feature in Browsers.
