### ISSUE TITLE
Light theme grid chart lines much not visible (vs dark theme)

### ISSUE THREAD

**Issue by burton-scalefastr** [grafana/grafana#10509]
The background grid lines in the dark are much more visible than the light theme:

![image](https://user-images.githubusercontent.com/33988567/34891739-7a101d6e-f78b-11e7-9998-08d33b9cbe56.png)

![image](https://user-images.githubusercontent.com/33988567/34891745-823adc54-f78b-11e7-9aeb-0f41802b2502.png)

**Comment by torkelo** [comment]
agree the grid lines are not visible enough in light theme
