### ISSUE TITLE
Dashboards are duplicated when importing from file

### ISSUE THREAD

**Issue by darahayes** [grafana/grafana#10508]
Environment Info:
* version - docker.io/grafana/grafana:master (5.0.0-pre1)
* no datasource
* Running grafana master docker image on OSX 10.12.6

Hi there, my team and I are very interested in the new feature introduced by https://github.com/grafana/grafana/pull/10052

### The Problem

We're able to get Grafana to scan a folder and it adds dashboard files to the database. We can also see that Grafana notices changes to an existing dashboard file. However, it does not update the dashboard in the database, instead it creates an entirely new dashboard.

According to [docs/sources/administration/provisioning.md](https://github.com/grafana/grafana/blob/master/docs/sources/administration/provisioning.md)

> When grafana starts it will update/insert all dashboards available in the configured folders. If you modify the file the dashboard will also be updated.

I believe this feature is not working as expected. I can see that the dashboard configuration is undergoing a major overhaul and there's a lot of conversation here: https://github.com/grafana/grafana/issues/9957

Is this issue being worked on by the Grafana Team? We'd be happy to propose some solutions and submit a PR if necessary. Cheers.

**Comment by torkelo** [comment]
can you show your dashboard json (ignore panels and templating etc) just the root properties. What change was made (that caused duplicate)

**Comment by bergquist** [comment]
If you change the title, Grafana will create a new dashboard with the new title. 
That's the only reason for this to happen that I can think of. 

I think this should be improved by linking the filepath of the dashboard json to the dashboard in the database.

**Comment by darahayes** [comment]
@bergquist Thanks for your reply. I spent some time reading the relevant code and I've realised it was indeed changing the title that caused the issue. It seems that we are using the slugified title to find the dashboard in the database.

The approach of linking the file path would work. I'd be happy to help with this if you need it.

**Comment by wtrocki** [comment]
As this is typical import filesystem problem maybe better aproach will be to use calculate `md5` from file and use it as `file-id` in database?
This will cause duplicates when editing as fingerprint will change. 

Apart from that problem I think that it will be cool if grafana exported dashboards will not include id or import implementation will ignore `id`. Currently when `Id` value is present dashboards will not appear and error message is not clear.  I'm happy to contribute any changes in this area upon agreement.

**Comment by torkelo** [comment]
but if title was changes should not the old dashboard be deleted? Or do we not handle deletions for provisioned dashboards?

**Comment by bergquist** [comment]
@torkelo We dont handle deltion currently. 

To do that we need either a relations table or `foreign id` of some kind for linking the dashboard with the json file.

**Comment by wtrocki** [comment]
@torkelo - IMHO That may cause some unexpected results in some environments. 
For example when mounting external volume in docker with dashboards or just when changing configuration to separate folder dashboards can be removed which may be confusing.

IMHO This functionality is perfect for seeding containers with volumes. If problem will happen with volume (let's say corruption etc.) I do not expect dashboards to disappear. For CRUD it's always best to use API. Import operation should not support delete.

**Comment by bergquist** [comment]
I think we should introduce a new column on the `dashboard` table called `source_id` or something like that. If the dashboard is created thru provisioning from files it should contain the full path to the file. Future providers like HTTP can use the URL or something like that to uniquely identify the source of the dashboard. Without the link to the source, it's not possible to find dashboards that should be deleted. 

Deletion should be optional per provider but should be possible to disable.
