### ISSUE TITLE
Grafana with influxdb - Decimals not working for very small values

### ISSUE THREAD

**Issue by gaardiolor** [grafana/grafana#10507]
Hello, I'm using Grafana 4.6.3 with Influxdb 1.4.2 on Linux. When I have very small values, for example 0.00000064, influxdb sends them in scientific notation to Grafana, 6.4e-07 . That's also the way they're presented in tooltips and legend, even when I set the Decimals to 8 in the Legend. Since I've set the decimals to 8 I'm expecting to see 0.00000064 . 

![image](https://user-images.githubusercontent.com/22920143/34885443-4f6b6dcc-f7c0-11e7-88ed-8172b3919d06.png)

**Comment by torkelo** [comment]
Grafana will switch to scientific notation if there are not significant digits beyond 7 decimals

**Comment by gaardiolor** [comment]
So.. beyond the first seven decimals (after the dot) is digit '4' . Isn't that significant ? What purpose has the Decimals setting in this case ?

**Comment by hackhowtofaq** [comment]
> Grafana will switch to scientific notation if there are not significant digits beyond 7 decimals

Any reason for this? Is it possible to customize this switch to 8 decimals?
