### ISSUE TITLE
Custom Time Range always uses browser time zone

### ISSUE THREAD

**Issue by MrSecure** [grafana/grafana#1050]
When selecting a custom time range, the dashboard setting for "Time Correction" (browser / utc) is ignored, and the browser time zone is always displayed.

Note the "From" value showing 16:18:45 as the start time (local time), but the graph shows starting some time around 22:20 (UTC).

![screen shot 2014-11-11 at 22 24 11](https://cloud.githubusercontent.com/assets/1155636/5005322/7f6204ce-69f1-11e4-91b1-e4049095ffa4.png)

**Comment by stonith** [comment]
@torkelo I opened ticket #277 previously on this. It's fairly common that teams will use UTC across all servers and communicate in UTC as well to avoid confusion between remote teams. Maybe grafana 2.0 with the backend will be easier to add proper UTC handling in the timepicker?

**Comment by torkelo** [comment]
The Grafana 2.0 backend will not are this easier, it is so hard because of javascript  date handling. But will try to fix this, and add a user preference for time zone (instead of dashboard  setting)

**Comment by tuxinaut** [comment]
+1

**Comment by merlinr68** [comment]
+1 - this is showing events on the wrong day due to using browser offset and not the UTC timestamp (the data has a 'Z' on the end of the ISO-8601 timestamps, but it is ignored)

**Comment by torkelo** [comment]
fixed in #2761
