### ISSUE TITLE
Reference an instance of a panel (rather than copying it) to a different dasboard

### ISSUE THREAD

**Issue by ravinoz** [grafana/grafana#10500]
I've searched for a similar feature request and couldn't find anything, but this may be closely related (or an extension) to **Simplify copy of panels between clipboards #10323**

- What Grafana version are you using? **4.5.2**
- What datasource are you using? **Elasticsearch, mySQL, Zabbix, others.**
- What OS are you running grafana on? **CentOS6**
- What did you do?
**Copy panel** from one dashboard to another through JSON copy-paste. This creates a new distinct panelID

- What is the desired result?
I am looking for the ability to "**clone link**" a panel from a dashboard to another ie both dashboards will end up referencing the same panel ID. 
Changes made to the panel in either dashboard would reflect in the other. 
The panel could have a distinct symbol in the header to suggest it is "linked". 

Was this previously requested?

**Comment by ravinoz** [comment]
As I was writing this I realized the panelID is not unique per organisation but per dashboard, so this might complicate things a bit...

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1803
