### ISSUE TITLE
In the dashboard filter <=, => dosen't work when filter key's type is not [date], such as ip type;

### ISSUE THREAD

**Issue by Hao8816** [grafana/grafana#10513]
1. version grafana-4.6.0
2. datasource  elasticsearch
3. Mac os
4. when i use dashboard filter, if the type of filter key is not [date], it dosent't work, but elasticsearch support other range types , such as [ip], if i choose [ip] type as a filter key, i can't find key in my query dsl ; 

getRangeFilter() {
    var filter = {};
    filter[this.timeField] = {
      gte: "$timeFrom",
      lte: "$timeTo",
      format: "epoch_millis",
    };

    return filter;
  }

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
please use community site for questions (https://community.grafana.com). 

Grafana has no range filter in the query editor. You can use range filters in the lucene query
