### ISSUE TITLE
Hi ! I am using Grafana's latest version and my need is to monitor and alert events on RabbitMQ we are using at my organisation www.sayint.ai . I am building things from source to cutomize Grafana as per current and future needs. All is good except the fact that each build takes about 140seconds to get completed. I use ` npm run build `. Any solution for this would be appreciated.

### ISSUE THREAD

**Issue by thesolotraveller** [grafana/grafana#10516]
Read before posting: 

- Questions should be posted to https://community.grafana.com.
https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by bergquist** [comment]
If you want to rebuild the frontend assets when you change something you can use `npm run watch` instead.

**Comment by thesolotraveller** [comment]
But here the only difference would be it would be automatically as the
watcher detects a change. It will take the same time. Right ?

**Comment by thesolotraveller** [comment]
npm run watch is cool for front end .
So for backend I turned to bra watcher as on official docs but not able to
run command - bra run. Any helpful doc or any blog or something would be
appreciated. Thanks

On 15 Jan 2018 4:00 p.m., "Mohit Gupta" <09mohit1994@gmail.com> wrote:

But here the only difference would be it would be automatically as the
watcher detects a change. It will take the same time. Right ?

**Comment by daniellee** [comment]
@thesolotraveller are you on Windows? bra unfortunately does not work there. 

If you are not on Windows, then you just need to install it like the [docs](http://docs.grafana.org/project/building_from_source/#developing-grafana) say:

> go get github.com/Unknwon/bra

This assumes that you have already installed Go.

**Comment by thesolotraveller** [comment]
@daniellee I am on Ubuntu. 
I think I got to edit the .bra.toml . It might have gone. 
Thanks
