### ISSUE TITLE
Option to control SingleStat Stat -> Current using previous value when current values is null

### ISSUE THREAD

**Issue by sandeepbangera** [grafana/grafana#10524]
SingleStat Options , Stat -> Current using previous value when current values is null is not intuitive. The feature currently works has documented http://docs.grafana.org/features/panels/singlestat/ i.e.  current - The last value in the series. If the series ends on null the previous value will be used. 

We were using SingleStat to show a API UP/Down status. We had mapped NULL to "Canary DOWN" to indicate that the canary which was doing API check status is DOWN. We noticed that our canary went down and was not posting any metrics data and we could clearly see a gap in the Spark Line, But the message displayed was "UP" i.e. last value before the canary went down. This was misleading because folks looking at the dashboard were thinking the API was UP at current time. I think grafana should always just display the current value at all times. Please suggest if there is any workaround to get this behavior.

Grafana version used:  v4.5.2
datasource (Prometheus)

**Comment by torkelo** [comment]
I can see this being a problem. The reason for Current ignoring the last null is that many time series databases return a null for the last value because the last value has not been reported yet. So the next to last value is usually the last reported value. This is of course not true for all data source and all types of queries. So there should probably be an option to control this behavior.

**Comment by benjamin-demarteau** [comment]
Came here to say that, we have a server that's down, so it's not sending stats, yet the counter still shows the last value instead of 0:
![screen shot 2018-05-08 at 15 53 08](https://user-images.githubusercontent.com/33421385/39761285-fe0f7ac2-52d7-11e8-9ed3-77e2e20018fb.png)

**Comment by torkelo** [comment]
What datasource are you using? Influxdb requires fill(null) in order for to detect no data

**Comment by benjamin-demarteau** [comment]
That's graphite.

**Comment by MMulthaupt** [comment]
Having the same problem as the OP. Knowing whether your services can be reached at all is one of the firsts things I want to get out of a dashboard. There doesn't appear to be a sensible workaround which does not introduce a blind spot.

**Comment by cptaffe** [comment]
This is a problem for me using cloudwatch metrics

**Comment by bmoe24x** [comment]
+1 as this being an issue, also is unintuitive and a first time user wouldn't assume this behavior before reading this Visualization's specific docs

**Comment by torkelo** [comment]
In the new stat panel we have separate options for "Last" and "Last non-null"

**Comment by bmoe24x** [comment]
> In the new stat panel we have separate options for "Last" and "Last non-null"

@torkelo is this reflected [in the documentation](https://grafana.com/docs/grafana/latest/features/panels/singlestat/) anywhere or only available in a beta/unstable version?
