### ISSUE TITLE
template search_type count 400 bad Request

### ISSUE THREAD

**Issue by PGDream** [grafana/grafana#10525]
- version describe 
> elasticsearch 5.5.0
> grafana 4.6.0
- error info
> http://xxxx/api/datasources/proxy/16/_msearch?search_type=count
> Query String Parameters
> search_type:count
> request body
> {"search_type":"count","ignore_unavailable":true,"index":"polaris-monitor"}
{"size":0,"query":{"bool":{"filter":[{"range":{"create_time":{"gte":"1515465724574","lte":"1516092124574","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"product_name","size":500,"order":{"_term":"asc"}}}}}
> response error
> Template variables could not be initialized: Elasticsearch error: No search type for [count]

**Comment by torkelo** [comment]
in your Grafana edit datasource page, specify elasticsearch version 5.x

**Comment by PGDream** [comment]
thk you, data can show!~
