### ISSUE TITLE
Text doesn't align on menus with walk downs

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#10527]
- What Grafana version are you using?
grafana_5.0.0-11215pre1

The alignment on the menu text is off.

![image](https://user-images.githubusercontent.com/20041843/34991776-bd33a50e-fac2-11e7-9b7a-a3c1930886f9.png)

![image](https://user-images.githubusercontent.com/20041843/34992583-879a5be2-fac5-11e7-95e9-cea45a8e1e2f.png)

**Comment by torkelo** [comment]
unable to replicate, what browser and OS are you using?

**Comment by daveselan** [comment]
Sorry for not including that info.

Browser: Firefox Quantum 57.0.4 (64-bit)
OS: Debian GNU/Linux 8.4 (jessie)

**Comment by torkelo** [comment]
thanks, can replicate in firefox as well.

**Comment by daveselan** [comment]
Both Chrome and Safari look fine, actually much cleaner overall.  An ugly white scrollbar is always shown on Firefox even when one isn't needed.

**Comment by daveselan** [comment]
Thanks.
