### ISSUE TITLE
IndexBy is not a function

### ISSUE THREAD

**Issue by jeangabin03** [grafana/grafana#10520]
Hi,

I upgraded Grafana 3.x.x to 4.6.x, and since then I have the error "_.indexBy is not a function"

![728dfcce-2e5e-11e7-9e29-c33958afbab4](https://user-images.githubusercontent.com/22960320/34943929-ebcf86b4-f9fd-11e7-902b-f3b9a8cd159a.png)

I've been using it with Zabbix, on CentOS and never had any trouble with the previous version. 
I have just run a yum update grafana and I go this problem.

Any Information or Solution about that ?

Thanks in advance =-)

**Comment by torkelo** [comment]
you will need to update your zabbix plugin
