### ISSUE TITLE
Image render timeout for graph panel with legend shown as table on the right and with at least one value

### ISSUE THREAD

**Issue by nklebedev** [grafana/grafana#10526]
Grafana version is 5.0.0-11204pre1.

Direct image rendering (via phanotomjs) is resulted in timeout for any panel if this panel has legend on the right, formatted as table and has at least one value (min, max, avg, current or total). Therefore, images for such kind of panels can't be embedded into alerts.

From log:
Loading a web page: http://localhost:3000/dashboard-solo/db/<mydashboard>...
Timeout error. You can set timeout in seconds with &timeout url parameter

I made some investigation on the issue by adding some logging to the *phantomjs/render.js*. As far as I can see the **rootScope.panelsRendered** is always undefined in line 61 and rendering finally interrupted by timeout.

**Comment by torkelo** [comment]
very strange, managed to track it down to this line the css: 
https://github.com/grafana/grafana/blob/master/public/sass/components/_panel_graph.scss#L138 

when I remove that line it starts to work. Some strange phantomjs bug

**Comment by Adorfer** [comment]
loooks like we are having this with  Grafana v5.0.0 (commit: af6e283) 
(if it's something different, pleace notice)

```
t=2018-03-02T16:43:02+0100 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/node-byid?panelId=1&theme=light&width=600&height=300&var-nodeid=30b5c26f38e4"
t=2018-03-02T16:43:08+0100 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"

```

**Comment by Adorfer** [comment]
false alarm, it was just the change of the base-url of PNGs...
in the "other frontend" a rewrite-rule does the job now. 

        rewrite ^(.*)/dashboard-solo/db/(.*)$ $1/d-solo/000000012/$2 last;

**Comment by plachetka** [comment]
rewrite ^(.*)/dashboard-solo/db/[dashboardname]/(.*)$ $1/d-solo/[dashboardid]/[dashboardname]$2 last;

**Comment by gino0631** [comment]
Would it be possible to clarify whether the old style rendering URLs like /grafana/render/dashboard-solo/db/icinga2-default are supposed to work in Grafana 5 or not?

**Comment by marefr** [comment]
`/grafana/render/dashboard-solo/db/icinga2-default` should redirect to `/grafana/render/d-solo/<uid>/icinga2-default` as long as you only have one dashboard named icinga2-default.

**Comment by gino0631** [comment]
@marefr all dashboard names are unique, but the redirection does not seem to work. The exact situation is now described in #11180.
