### ISSUE TITLE
Use previous value if value is not available at beginning of time range

### ISSUE THREAD

**Issue by Programie** [grafana/grafana#10537]
I'm storing some values in InfluxDB. The values are only written to the database if they have been changed which leads to not showing the values if they haven't been updated in the specified time range.

Example:

The last time a value has been updated is 24 hours ago, so there is no data point in the database for the last 24 hours. I select the last 6 hours to show in Grafana but I don't see any values as the values were not updated in the last 6 hours.

Would it be possible to "ask" InfluxDB for the last value before the start of the time range so Grafana could show that value instead of not showing any value at all? Or maybe storing the same value (even if it's unchanged) is the better way? But that would result in a much bigger database.

Grafana version: 4.6.3
Datasource: InfluxDB
OS: Debian Stretch 9.3

**Comment by DanCech** [comment]
The correct way to handle this is to write the current value each time it is observed.  Right now you don't have a way to distinguish between the value being unchanged or not collected at all.

**Comment by Programie** [comment]
So I should store a value once per minute (or whatever interval I want to use) even if the value has not been changed?

I just found some similar issue for InfluxDB: https://github.com/influxdata/influxdb/issues/6878

So maybe it is a "datasource issue" instead of an issue in Grafana as it must be implemented in the datasource?

**Comment by DanCech** [comment]
Yes, just store the current value every minute.  If you don't then you have no way of knowing whether the collector is broken or the value just hasn't changed.

At least part of the reason that no TSDB I'm aware of implements this logic is that you have no way of knowing how far back you'd need to look to find a value, and if you have a value that changes infrequently then you'll also have issues as the last stored reading rolls out of your retention window.  Basically implementing it would be a nightmare for aggregation, expiration, and querying.

TSDBs are optimized for storing values on a regular interval, you're just causing problems for yourself by trying to "save space" by not storing them.

**Comment by Programie** [comment]
OK, thanks for the explanation! Then I will store the value every minute.

**Comment by geoff-nunan** [comment]
I have this same problem, and storing the data every minute is not a viable solution. 
I am monitoring the state of machines in factories, and doing analysis of the performance of the machines. These machines may only change state once every few hours or more.

If I store machine state every minute, I am storing around 200x more data per machine. I need to monitor over 1000 machines, so that blows out my data storage volumes to x200,000.

All that extra data, just because the fill(previous) does not look outside the time range...

Please, please can we get this fixed?

**Comment by Cjkeenan** [comment]
I also would be interested in this but I wonder is this an issue with Grafana or more of an issue with InfluxDB?
