### ISSUE TITLE
Feature request: Support Pagerduty notification channel using Pagerduty V2 API

### ISSUE THREAD

**Issue by jbaublitz** [grafana/grafana#10531]
Currently Pagerduty is in the process of deprecating their API V1 support. For Pagerduty notification channels to work in the future, the notifier for Grafana alerting will need to be updated to use the V2 API. The documentation for Pagerduty V2 API is [here](https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2). The migration looks fairly painless and mostly involves adding a few new required JSON keys and hitting a different endpoint.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10533
