### ISSUE TITLE
FEATURE REQUEST: add copy row json

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#10536]
Would be handy to be able to get the row json, so you can copy and paste it in an other dashboard.

**Comment by torkelo** [comment]
in Grafana v5 we are downplaying the need for rows (and they work a bit differently). 
https://www.youtube.com/watch?v=BC_YRNpqj5k

So not sure we need this.

**Comment by f1-outsourcing** [comment]
Ooooh looks very nice!!!!
