### ISSUE TITLE
Failed Install/Build - Failed to detect generated javascript files in public/build logger=settings

### ISSUE THREAD

**Issue by luketopa** [grafana/grafana#10532]
Please include this information:
- What Grafana version are you using? 5.0pre
- What datasource are you using? n/a
- What OS are you running grafana on? CentOS 7
- What did you do? Build from master
- What was the expected result? For it to work
- What happened instead? It doesn't work

go version: go1.9.2 linux/amd64
Node: v6.9.1
NPM: 3.10.8

Hi I followed the below steps to the T!

Building the backend

go get github.com/grafana/grafana
cd ~/go/src/github.com/grafana/grafana
go run build.go setup
go run build.go build

npm install -g yarn
yarn install --pure-lockfile
npm run build

npm run test

All test pass, when I go to my directory and run ./grafana-server

The first line in the log is 

**EROR[01-16|16:55:26] Failed to detect generated javascript files in public/build logger=settings**

All I have in /Public is

app  dashboards  emails  fonts  img  robots.txt  sass  test  vendor  views

I had some issues with node-sass but I believed I resolved these to get the tests to pass. 

***Update***

Okay so I have a page loading under localhost/login

Inspecting in chrome I see none of the build components are been found.

GET http://0.0.200.133/public/build/manifest.88c08830a289dae4a657.js net::ERR_ABORTED
login:86 
GET http://0.0.200.133/public/build/app.393035ce4c2de8a988e8.js net::ERR_ABORTED
login:14 
GET http://0.0.200.133/public/build/grafana.dark.css?v5.0.0-pre1 net::ERR_ABORTED
login:86 
GET http://0.0.200.133/public/build/vendor.7915bc9802d81712754c.js net::ERR_ABORTED
login:86 
GET http://0.0.200.133/public/build/manifest.88c08830a289dae4a657.js net::ERR_ABORTED
login:86 
GET http://0.0.200.133/public/build/vendor.7915bc9802d81712754c.js net::ERR_ABORTED
login:86 
GET http://0.0.200.133/public/build/app.393035ce4c2de8a988e8.js 404 (Not Found)

Where are these? under Master/Public you have no build folder with these files?

Can I create a build folder and just add these in?

**Comment by torkelo** [comment]
fixed some of the building from source instructions in README and docs. Also fixed the npm run test task, it cleaned build dir (So you cannot run it after build, this was unnecessary so removed this) 

To build frontend assets run "npm run watch" (if you want to develop / change frontend parts), otherwise npm run dev or npm run build ( depending on if you want optimised/minimized frontend
