### ISSUE TITLE
cannot save dashboard

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#10535]
Read before posting: 

Please include this information:
grafana-4.6.3-1.x86_64
influxdb-1.4.2-1.x86_64
CentOS release 6.9 (Final)
- What did you do?
I have been working on a dashboard for while, and suddenly when I try to save changes, the popup with the save button is not responding and the changes are not saved.
I can however create a new dashboard and save it.

i added in "/etc/grafana/grafana.ini"
```
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
level = debug

```
But I don't see to much in the logging, looks more like info than debug level

Also validated the json with some online tool.
When I try to import json, I can also not press the import button.

**Comment by f1-outsourcing** [comment]
Strange thing is that I could save it via the tablet having an old firefox browser.

**Comment by torkelo** [comment]
strange, no other reports of hanged save dialog in v4.6.3. The reason for not showing anything in backend server log is that this probably is a frontend (js) hanging. Maybe chrome was having a bad day? 

If you get this behavior again, try opening chrome dev tools and inspect the console for errors.
