### ISSUE TITLE
Fetch all dependent datasource calls in parallel

### ISSUE THREAD

**Issue by burton-scalefastr** [grafana/grafana#10534]
This is a screenshot of my browser requests performing rendering of a page with about 8 dependent XHR calls.

Notice the waterfall timings?

Wouldn't the metric know all the resources it needs ahead of time and wouldn't it be possible to fetch them all at once?

Is there something preventing it from doing so?

Looks like this page could go from 4s down to about 1.5 if you dispatched them in parallel.

The protocol for all of this is H2 so there should be no head of queue blocking. (I verified but forgot to include it in the screenshot).

![image](https://user-images.githubusercontent.com/33988567/35011758-29917930-fabc-11e7-8f9e-81f51464cf69.png)

**Comment by torkelo** [comment]
rendering (panel metric queries) are done in parallel. What is sync is all template variable queries that have "refresh on dashboard load" are fetched before the dashboard is loaded. So those queries will have to be completed before dashboard can load. You can change this by changing the Refresh option in the template variable options view. 

Also template variable queries that depend on each other (that use another variable in its query) cannot possibly be done in parallel as they depend on each other. 

In you screenshot there are a bunch of template variable queries, then 2 metric (time series) queries that are in parallel
