### ISSUE TITLE
Allow multiple column sorting on the Table panel

### ISSUE THREAD

**Issue by TGG-Solutions** [grafana/grafana#10541]
I need to be able to populate a table from a metric query, then sort on multiple columns on the resulting table.

For example, I have 10 columns returned from a query, but I want to be able to sort the data by Price, then Time, then Volume. This is for ad hoc data exploration so doing this type of sorting in the metric query itself is not the desired result.
Multiple other table controls typically support multiple column sorting.

**Comment by theneva** [comment]
For what it's worth, this issue makes one use case unfeasible for my company.

We want to show Google Cloud quota usage in percent ordered by usage on a dashboard that refreshes every 10 seconds.

Items switch place every time it refreshes:

![grafanasort](https://user-images.githubusercontent.com/1404650/57755544-7b56e900-76f1-11e9-8c09-a3c763ee9570.gif)

The movement is incredibly distracting, not to mention jarring when looking at it 😅

The data come from a Prometheus data source, and the Prometheus query function `sort_desc(…)` behaves in the same way, so I can't work around this limitation with a Table panel.

I ended up making a Graph panel instead. It isn't nearly as easy to grok, but at least doesn't have random jumping.

**Comment by MJahanzaibAlam** [comment]
I was able to use the [Datatable Panel plugin](https://grafana.com/grafana/plugins/briangann-datatable-panel) to sort on multiple columns (in Grafana version 6.3.5). Other than not using the specified link for column URLs, it seems to work fine.

**Comment by lukaszgryglicki** [comment]
+1 on this feature - would be really nice to have sorting by multiple columns in tabular panels.

**Comment by Yifan-Song** [comment]
Wondering if this problem could be solved in any method now?

**Comment by zoltanbedi** [comment]
This is already supported you need to hold down the `shift` key.
