### ISSUE TITLE
PNG rendering issue

### ISSUE THREAD

**Issue by mageo** [grafana/grafana#10546]
**- What Grafana version are you using?**

Grafana 4.6.3

**- What datasource are you using?**

Graphite

**- What OS are you running grafana on?**

Debian stable

**- What did you do?**

Compared the graph rendered in browser and as PNG image.

**- What was the expected result?**

Both should be similar.

**- What happened instead?**

They are very different. Below are screenshots of both:

![cmts](https://user-images.githubusercontent.com/12015577/35044001-fe93451e-fb8e-11e7-9ff4-8ad268943c95.png)
![screenshot from 2018-01-17 14-00-56](https://user-images.githubusercontent.com/12015577/35044002-feb63de4-fb8e-11e7-9326-4ac34afc0af8.png)

I checked the values of the metric used and the graph generated in Grafana interface is correct.

Query inspector result : [query_inspector.txt](https://github.com/grafana/grafana/files/1639113/query_inspector.txt)

I can provide any further required info.

**Comment by torkelo** [comment]
the dimensions of your graphs are different, so not sure what difference your referring to. 

Graphite can return different results depending on the width of the graph (as width controls maxDataPoints) and your consolidation function (consolidateBy in graphite is default to avg)

**Comment by mageo** [comment]
I'm referring to the fact that on the correct graph, the yellow and blue metrics stop around the 27 of November, replaced by the red and orange ones. On the PNG image, the yellow and blue metrics are still present after the 27...

**Comment by torkelo** [comment]
and if you make the dimensions is the difference still there?

**Comment by mageo** [comment]
As the can see below, the difference is still there, even with similar dimensions:

Web interface:
![screenshot from 2018-01-18 08-50-09](https://user-images.githubusercontent.com/12015577/35086438-f314324a-fc2c-11e7-97e7-eb9e2a5a380d.png)

PNG image:
![cmts_915](https://user-images.githubusercontent.com/12015577/35086448-f963fffe-fc2c-11e7-8545-d0d6fdfb3457.png)

**Comment by torkelo** [comment]
could you turn on requests logging grafana or graphite and compare the requests to graphite?

**Comment by mageo** [comment]
I can see a little difference in the requests on the "from" and "until" arguments.

The web interface is using relative values : from=-1y&until=now

The PNG rendering is using absolute values : from=1484730654&until=1516266774

If I change the values from absolute to relative in the PNG rendering, I get a correct PNG image:
![cmts_until_now](https://user-images.githubusercontent.com/12015577/35090104-031429be-fc39-11e7-8def-76a8e183fa30.png)

**Comment by torkelo** [comment]
ok, looks like a strange graphite bug or behavior.

**Comment by mageo** [comment]
Ok, I will upgrade graphite and let them now if it's still present...

Thank you for your help on this ! :+1:
