### ISSUE TITLE
Single Stat last data point messes the aggregation

### ISSUE THREAD

**Issue by pparth** [grafana/grafana#10543]
Hello,

I have seen that whenever my query returns a “NaN” as the last data point of a time period, the Single Stat Panel shows a “NaN” even if there are many other data points with proper values and i have set the Stat parameter to be “Average”. When the query returns a proper value as the last data point, everything works as expected; average is calculated and presented by the panel.

The thing is that the panel works ok when NaN values are present in any other timestamp of the selected time window, expect the last one. So, executing a query for a time window of 1 hour and with an Atlas server step size of 1 minute, i get back 60 data points. The first 20 may be NaN, then the rest of them may have proper values. In this case, panel works ok and it actually averages the 40 values. However, if the last data point is NaN, then panel shows NaN, even if there are many other data points with a proper value.

We are using our custom data source plugin that talks to a Netflix Atlas time series server. NaN means that there is not data point available for the specific timestamp.

**Comment by torkelo** [comment]
Can you show raw response from you query? (open query inspector in metrics tab)

**Comment by pparth** [comment]
`{
start: 1516086900000,
step: 300000,
legend: [
"Errored Request Percentage"
],
metrics: [
{
atlas.dstype: "rate",
atlas.offset: "0w",
deployment.aws.availability-zone: "us-west-1c",
deployment.aws.instance-type: "m4.large",
deployment.canary.enabled: "false",
deployment.environment: "prod",
deployment.stack.name: "agora-api-gateway-prod-1512555538643",
http.request.method: "GET",
http.request.rootBoundedContext: "undefined",
http.resourceMethod: "ApiGatewayEndpoint.doGet",
name: "http.server.requestRate",
registration.application.name: "api-gateway",
registration.application.service.boundedContext: "API",
registration.application.service.name: "apiGatewayAS",
statistic: "count"
}
],
values: [
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
"NaN"
],
[
0.06199243692269543
],
[
0
],
[
0.009891849116328144
],
[
0.07379420272743377
],
[
0.6505303873879152
],
[
0
],
[
0.010156064863400923
],
[
0.009175153683824202
],
[
0.008575348730848389
],
[
0
],
[
0.02867429190429158
],
[
0.06983876355023835
],
[
0.024548483254427485
],
[
0
],
[
0.048607102712883925
],
[
0.008409957389549227
],
[
0.0033983551960850935
],
[
0.005850519233581981
],
[
0
],
[
0.008476012883539578
],
[
0.01508250128201261
],
[
0.04787923167915282
],
[
0
],
[
0.008355382258738338
],
[
0
],
[
0.040029736375593296
],
[
0.024094450244960246
],
[
0.30786536810633186
],
[
0.13641848995225359
],
[
0.06454262747168925
],
[
0.03597861842105264
],
[
0.028972070923629627
],
[
0.005079881130781538
],
[
0.025278058645096062
],
[
0.006974635575291195
],
[
0.06306797007138147
],
[
0.007804979576970107
],
[
0.0022627505996289086
],
[
0.015423768026528879
],
[
0
],
[
0.029546065001343005
],
[
0.018617206953526793
],
[
0.03897116134060797
],
[
0
],
[
0.0431385706753583
],
[
0.004615420118616297
],
[
0.002477577919825579
],
[
0.01073629511928024
],
[
0.02940468871127269
],
[
0.02134117423883146
],
[
0.029982555604012213
],
[
0.02910713852572344
],
[
0.06125499228187098
],
[
0.010480202896728082
],
[
0.07020954849859581
],
[
0
],
[
0.07055562555121588
],
[
0.010664846532858397
],
[
0.002924233119864317
],
[
0.08373894384257076
],
[
0.0504274325232927
],
[
0.03754458419373006
],
[
"NaN"
]
],
notices: [ ]
}`

**Comment by pparth** [comment]
This last "NaN" is the one that breaks things.

**Comment by torkelo** [comment]
what datasource is this? "NaN" is not an acceptable value for a time series datapoint in Grafana. 

And what does the data source return to the panel?

**Comment by pparth** [comment]
Atlas data source. You can find an older version here: https://github.com/briangann/grafana3-atlas-datasource. We haven't got the time to push the latest version to Grafana repo yet.

**Comment by torkelo** [comment]
ok, would be interesting to know what the data source returns. It needs to filter out the "NaN" values before the data is returned to the panel as that is not a valid value, null is ok.

**Comment by mgtriffid** [comment]
@torkelo , this is an example of what comes as argument to `onDataReceived` of `public/app/plugins/panel/singlestat/module.ts`:
```
[{"target":"Errored Request Percentage","datapoints":[[0,1516253460000],[0,1516253520000],[0,1516253580000],[0,1516253640000],[0,1516253700000],[0,1516253760000],[0,1516253820000],[0,1516253880000],[0,1516253940000],[0,1516254000000],[0,1516254060000],[0,1516254120000],[0,1516254180000],[0,1516254240000],[0,1516254300000],[0,1516254360000],[0,1516254420000],[0,1516254480000],[0,1516254540000],[0,1516254600000],[0,1516254660000],[0,1516254720000],[0,1516254780000],[0,1516254840000],[0,1516254900000],[0,1516254960000],[0,1516255020000],[0,1516255080000],[0,1516255140000],[0,1516255200000],[0,1516255260000],[0,1516255320000],["NaN",1516255380000],[0,1516255440000],[0,1516255500000],[0,1516255560000],[0,1516255620000],[0,1516255680000],[0,1516255740000],[0,1516255800000],[0,1516255860000],[0,1516255920000],[0,1516255980000],[0,1516256040000],[0,1516256100000],[0,1516256160000],[0,1516256220000],[0,1516256280000],[0,1516256340000],[0,1516256400000],[0,1516256460000],[0,1516256520000],[0,1516256580000],[0,1516256640000],[0,1516256700000],[0,1516256760000],[0,1516256820000],[0,1516256880000],[0,1516256940000],["NaN",1516257000000]],"allIsZero":false,"allIsNull":false}]
```
So you suggest to tweak our datasource so that it filters out "NaN" string?

**Comment by torkelo** [comment]
yes, that string needs to be replaced with null
