### ISSUE TITLE
Inconsistency on graphs between refreshes

### ISSUE THREAD

**Issue by ParadoxD** [grafana/grafana#10557]
**- What Grafana version are you using?**
Version 4.6.3 (commit: 7a06a47)

**- What datasource are you using?**
Prometheus 2.0.0+ds3

**- What OS are you running grafana on?**
Debian GNU/Linux 9.2 (stretch)

**- What did you do?**
Monitored several dashboards with varying data including but not limited to nginx RPS, phpfpm request duration, gearman workers (available/queued/working), etc.

**- What was the expected result?**
Display of data between refreshes should remain consistent.  This makes the graphs almost impossible to use reliably.

**- What happened instead?**
Several graphs, regardless of timeline size or refresh rate, will "jump" around between refreshes.  Essentially, it's as if history is being rewritten with each refresh. Viewing the same query directly in Prometheus does not display this behavior.

Visual example (5s refresh):
![2018-01-18_10-08-40](https://user-images.githubusercontent.com/1508373/35107388-c888ed74-fc3e-11e7-86f7-d70faff2ef9f.gif)

**- If related to metric query / data viz:**
Example request: `/api/datasources/proxy/1/api/v1/query_range?query=netdata_phpfpm_request_duration_milliseconds_average%7Binstance%3D~%22core-www-1%7Ccore-www-2%7Ccore-www-3%7Cscraper-1%7Cscraper-2%7Cscrubber-1%7Cscrubber-2%22%2Cdimension%3D%22max%22%7D&start=1516289135&end=1516290935&step=30`

Response:
[https://pastebin.com/HqUnHr1U](url)

**Comment by torkelo** [comment]
Can you include a graph and a response from Prometheus where you identify Grafana is not showing what Prometheus returns? This is probably a problem with your Prometheus query where it's response is not consistent across refreshes.

**Comment by ParadoxD** [comment]
Upon toying with Prometheus a bit, I discovered that it is related to [https://github.com/grafana/grafana/issues/9705](url) - where the step resolution affects the accuracy of the graph.  Changing my scrape interval and adjusting my queries has gotten me a stable timeline.
