### ISSUE TITLE
backslash in prometheus label in not escaped properly

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10555]
When I use a variable to choose between multiple label/value that have a backslash, the regexes in the graphes are not working.

grafana5

**Comment by torkelo** [comment]
Can you show your variable value & options, and your query and the query sent by Prometheus by Grafana?

**Comment by roidelapluie** [comment]
`https://prometheus/grafana/api/datasources/proxy/3/api/v1/query_range?query=sum(mymetric{fbio='yes',name=~'aa|get',dbenv='prod',licensename=~'foo\\\bar|bar\\.foo\\.bar\\.be|irop|softop1',receiver=~'none|other',sender=~'abc|none|other',status=~'finished|no traffic|validation_error',fbio=~'no'}) by (status)&start=1516266705&end=1516281825&step=60`

**Comment by roidelapluie** [comment]
The problem is `foo\\\bar`

**Comment by roidelapluie** [comment]
![bug1](https://user-images.githubusercontent.com/291750/35215947-344c4676-ff66-11e7-9e82-31bff5fb99b8.png)
