### ISSUE TITLE
[Feat Req]: Show time since last value above/below stat

### ISSUE THREAD

**Issue by bengalaviz** [grafana/grafana#10550]
I'd like to create a Singlestat panel with the time since last stat was recorded above/below a threshold.

Currently I have a script that pulls records from a service every 10 minutes. I would like to show, as part of the Singlestat panel, the time that has passed since the the metric was above 0. This way we would know if data hasn't been pulled in a while.

**Comment by DanCech** [comment]
What TSDB are you using?

**Comment by bengalaviz** [comment]
Graphite.

**Comment by DanCech** [comment]
About the closest you could get right now would be to use the sum of http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.isNonNull to count the number of non-null data points in the period, which will tell you whether you're missing any (or `isNonNull(some.series)|offset(-1)|scale(-1)` to instead count the null values)

**Comment by torkelo** [comment]
this type of query needs to be done in the metric query and not calculated by grafana . Singlestat already has "time since last point", just need to include thresholds in your query.

**Comment by bengalaviz** [comment]
I'm still trying to figure this out. When I query the data from graphite, I get

`8:Array[null,1517337240]
9:Array[1,1517337300]
10:Array[null,1517337360]
11:Array[null,1517337420]`

Grafana says the "Time of last point" is 12:37 PM. But I want it to show the "Time of last point" to be 12:35 PM because that was when the last value was 1.

**Comment by AlixBa** [comment]
Indeed. Time of last point includes null data. Could we have something like Time of last not null point ?

**Comment by AlixBa** [comment]
Do you have any solution to this case @torkelo?

**Comment by torkelo** [comment]
@AlixBa depends on your TSDB and it's query capability

**Comment by AlixBa** [comment]
Same as @bengalaviz, I'm using graphite. I get points every 20s and I would like to have a singlestat with the last time the point changed. I'm able to get a correct serie with null everywhere except when it changed, but when I use Last point, it gets me the last null point :/

**Comment by bengalaviz** [comment]
I've actually modified the singlestat/module.ts to add this for me. 

I added a new "valueNameOptions" called "Time of last point" and updated the "setValues(data)" function to search for the last non zero point value.

**Comment by joseapdmota** [comment]
Trying to pull this out with InfluxDB.
Do you have an idea on how to do it @torkelo, or if it is possible?

**Comment by dbartz** [comment]
> this type of query needs to be done in the metric query and not calculated by grafana . Singlestat already has "time since last point", just need to include thresholds in your query.

@torkelo as described above
> Indeed. Time of last point includes null data. Could we have something like Time of last not null point?
including thresholds in the query does not help. Would it then not be a good idea to add such an option (and re-opening this issue)?
