### ISSUE TITLE
Users were removed automatically from organization 

### ISSUE THREAD

**Issue by liuweibigmicro** [grafana/grafana#10569]
Please include this information:
What Grafana version are you using? -- version 4.6.0
What datasource are you using? -- InfluxDB
What OS are you running grafana on? -- Windows server 2012 R
What did you do?
I created an organization with templates for a few people in my group. However, they got removed from the organization from time to time and every time I had to add them back. It also happened once one person got moved from one organization to another without admin's approval.

What was the expected result?
Users stay in the same organization unless Admin add/remove them

What happened instead?
Users get removed from the organization or moved a different one without admins' approval

Thanks for your help!

Wei

**Comment by torkelo** [comment]
Do you have ldap configured? When LDAP is enabled you need to specify your org memberships in the ldap.toml file by specifying group memberships. 

http://docs.grafana.org/installation/ldap/#mappings
