### ISSUE TITLE
PostgreSQL Datasource password

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#10562]
Please include this information:
- What Grafana version are you using? 4.6.2
- What datasource are you using? PostgreSQL
- What OS are you running grafana on? Ubuntu Xenial
- What did you do? I'm trying to add a datasource with a secure password( chars like %&/\? and so on )

this datasource doesnt seems to support secure passwords. 
I can confirm that '%' , '/' , '?' doesnt work, probably more. it breaks the connection

for example abc/0123
results in 'dial tcp: address tcp/abc: unknown port'

and /abc0123
results in 'dial tcp: lookup zabbix on 10.0.0.2:53: server misbehaving'

**Comment by marefr** [comment]
There is a fix in the master branch for passwords with symbols like %, /, ? that cause problems in the connection string. And also a fix in xorm, the ORM that Grafana uses that will be included in the next release of Grafana. So I'll close this.

Please refer to the following issues
#9830
#10364
