### ISSUE TITLE
Proposal: metric documentation and discovery through standardised metric discovery format

### ISSUE THREAD

**Issue by arussellsaw** [grafana/grafana#10565]
Hi! i've been thinking about how to improve metric documentation and discovery for our team, and as a part of this i was thinking about ways to expose a metric registry along with descriptions and links to dashboards for each metric.

I think this would be a really handy feature to integrate into the grafana ui, if there was an agreed upon standardised format for metric documentation, anyone would be able to integrate documentation and discovery into the UI by implementing a simple JSON structure.

i won't propose any format yet as i haven't actually spent any time on this yet. i'm just thinking about it and thought it'd be good to have some discussion in here.

**Comment by torkelo** [comment]
it would be cool
