### ISSUE TITLE
Graph using PostGresSql

### ISSUE THREAD

**Issue by ldurans** [grafana/grafana#10567]
I have a chart that I need to buy values between months / years. In graph I created two metrics, but graphfana does not separate. Any idea?

Return Query A:
"2017-12-20"; "12/20/2017"; 723499.64
"2017-12-21"; "21/12/2017"; 708555.15
"2017-12-22"; "12/22/2017"; 613323.83
"2017-12-23"; "12/23/2017"; 444682.64
"2017-12-24"; "12/24/2017"; 291532.77

Return Query B:
"2016-12-20"; "20/12/2016"; 826679.88
"2016-12-21"; "21/12/2016"; 789456.01
"2016-12-22"; "12/22/2016"; 638744.77
"2016-12-23"; "12/23/2016"; 611520.19
"2016-12-24"; "12/24/2016"; 322699.84
 

![image](https://user-images.githubusercontent.com/10197544/35153235-c677e66a-fd0c-11e7-839d-c196829d2670.png)

How can I make the information separate and allow analysis

**Comment by bergquist** [comment]
Hi! Please ask questions at the community site https://community.grafana.com/
