### ISSUE TITLE
 Flickering can not be achieved by adding a timer control border.

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#10575]
Read before posting: 
Please include this information:
- What Grafana version are you using?  -4.5.2
- What datasource are you using? default
- What OS are you running grafana on?  window 64
- What did you do?   Blinks by adding a timer to control the presence or absence of a border.
- What was the expected result?  Flickering can not be achieved by adding a timer control border.
- What happened instead?  
  The timer boxWidthToString property value changes with the timer, but the page shows no change
picturelt_ctrl.js
![image](https://user-images.githubusercontent.com/34366341/35203103-6f04f740-ff61-11e7-9786-33bd14f9b709.png)

moduel.html  
![image](https://user-images.githubusercontent.com/34366341/35204201-84349a16-ff67-11e7-9cb8-6f559a74c8c6.png)

Flickering can not be achieved by adding a timer control border.can you help me?thank you very much!

**Comment by torkelo** [comment]
this seems to be related to an custom external plugin (picturelt_ctrl), please seek help with plugin author

**Comment by zhoumin8023** [comment]
But that plugin author does not reply me, can you help me?thank you very much!

**Comment by zhoumin8023** [comment]
can you help me? I need your help.help me,help me!!!!!

**Comment by torkelo** [comment]
sorry no, can't support every plugin out there

**Comment by zhoumin8023** [comment]
What's wrong with that? There is no strict limit on knowledge. How about you help me find the author?

**Comment by torkelo** [comment]
but there is a strict limit on time :) have about 1000 open issues and 62 open PRS review and 20 unanswered community questions on https://community.grafana.com  I have to prioritize, troubleshooting  unknown custom plugin code is not top prio :) 

Where did you install the plugin?

**Comment by zhoumin8023** [comment]
So, I understand you, thank you
