### ISSUE TITLE
Templates: refresh on time change does not change on autorefresh

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10578]
When we use template variables and set thom to «refresh on time change», I expect them to be refreshed when autorefresh is on and that the refresh happens.

It is not the case.

grafana: Grafana 5

**Comment by torkelo** [comment]
Strange, unable to replicate. When I set on variable in the dashboard below to refresh on time range change and enable auto refresh I see one request being sent to update the variable options. 

![image](https://user-images.githubusercontent.com/10999/35216434-dd3cdf6a-ff67-11e7-9dd4-cad3127bdd6a.png)

Can you inspect chrome dev tools network tab? Make sure there is no request being sent there for your query variable?

**Comment by roidelapluie** [comment]
I must have dreamed this one. I can not reproduce it. Will repoen if needed.
