### ISSUE TITLE
Elasticsearch: Forced Query

### ISSUE THREAD

**Issue by dploeger** [grafana/grafana#10577]
Grafana version: 4.6.3 (Docker version)
Datasource: Elasticsearch

Truth be told: We'd like to use Grafana as a cost-effective alternative to Kibana/X-Pack.

This should be fairly ease as Grafana allows organizations, where users can not modify the admin-configured Data-Sources. For this to work, though, we need to map each organization to a different index. Instead, we would like to have a "forced query" in the datasource settings. Some kind of "query-prefix", that is added for every query running through the elasticsearch data source.

That way we could map organizational data to tags, for example and query for the matching tags.

**Comment by torkelo** [comment]
I think we need to start with enforcing the index setting, 
https://github.com/grafana/grafana/issues/5880

**Comment by dploeger** [comment]
Oh, okay. I didn't realize that.
