### ISSUE TITLE
RDS CPU Utilization value is null when test rule

### ISSUE THREAD

**Issue by adityahilman** [grafana/grafana#10576]
- What Grafana version are you using?
4.6.3
- What datasource are you using?
Cloudwatch 
- What OS are you running grafana on?
Docker version 
- What did you do?
Create alert rule 
- What was the expected result?
CPU Utilization value is not null
- What happened instead? 
CPU Utlization return no data (null)
![screenshot from 2018-01-22 11-27-11](https://user-images.githubusercontent.com/9929233/35205371-386b954e-ff67-11e7-9c75-d5020e716c83.png)

**Comment by bergquist** [comment]
Are you sure there are any datapoints in the timerange? `2m` - `now-1m` is only 60s. 

Any chance you can share a screenshot of your query?

**Comment by torkelo** [comment]
Another reason could be time mismatch between Grafana server and prometheus server, if it's off by more than 60s it could cause issues like this.

**Comment by adityahilman** [comment]
Solved. No data from cloudwatch in the timerange.
