### ISSUE TITLE
Repeat panel for all values of hidden variable

### ISSUE THREAD

**Issue by julianoromani** [grafana/grafana#10588]
Hi,

I want repeat a panel for every value of a variable, but the variable is hidden. Is it possible put a checkbox when I select "Include All option", to check All for default?

In some cases, I don´t want a iteraction of user, just display All values in separate panels.

In community already have a [topic](https://community.grafana.com/t/repeat-with-hidden-variable/3465/12) about this, but without solution.

Thanks

Juliano R.

**Comment by julianoromani** [comment]
I found a solution for this, with help of my friends of “Grafana Brasil” group in telegram:

- Create the variable which “Include All option” not hidden.
- In dashboard select “All” on this variable
- Save the dashboad
- Edit the variable to hidden
- Save the dashboard

But if we have a checkbox is much better.

Juliano

**Comment by torkelo** [comment]
Just make sure the All option is saved before you hide the variable
