### ISSUE TITLE
Zooming in graph set as histogram resets time to the beginning of unix epoch time

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#10581]
In Grafana 4.6.3 when zooming in a graph where the x-axis is configured in mode histogram the resulting time range will be something like 1970-00:59:59 - 1970 00:59:59 afterwards. It seems the histogram numbers are used as unix epoch time when zooming in a histogram shouldn't affect the time setting at all.

**Comment by torkelo** [comment]
think this was fixed in https://github.com/grafana/grafana/pull/9914

**Comment by xlson** [comment]
Ah, I searched for a related issue but guess I should have looked harder.
