### ISSUE TITLE
Add support for region annotations in datasources

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#10589]
Hello Grafana experts,

I am trying to use region/range annotations in grafana and hoping I can get that fed by a measurement table in influxDB. Currently only markers and single annotations are permitted.
If anyone has ideas that would help that would be much appreciated.

Thanks

-Achraf

**Comment by siwyd** [comment]
This would be great for deployments for instance. Right now, I've got annotations that show the start of a deployment and the end of a deployment. Showing this as a region would be nice.

**Comment by fangel** [comment]
I have next to no knowledge of Grafana, but I also thought this would be a super nice addition too, so I investigated what it might take.

Please correct me if I'm wrong, but my understanding is that regions are created when two events share the same `regionId`-property. So for a external datasource to create region annotations, they would only have to provide some way of mapping a field into the `regionId`-property.
Of course for this to work, ones external datasource need to have a field that can be used to correlate the start and end event of a range-annotation.

If someone can verify that exposing a `regionId` from the external datasource is enough, I don't mind trying to create a PR to extend the Elasticsearch datasource with the option of providing a `regionId`-field just like there are fields to provide the time- & text-fields.

**Comment by mtanda** [comment]
Seems correct, if share `regionId`, Grafana create region annotations.
https://github.com/mtanda/grafana-google-calendar-datasource/pull/10/files

**Comment by fangel** [comment]
Interesting. If I have the time, I'll try to create a PR for the Elastic DS to have support for mapping a field from Elastic into the `regionId`-property.

**Comment by fangel** [comment]
I've finally gotten around to create a PR for the Elastic DS - if anyone else is feeling tempted by looking at adding it to other datasources, it was quite straight forward.

**Comment by ryantxu** [comment]
I think the best path for this is to simplify the internal annotation representation with something like #17647, then if any datasource defines an endTime it is a region

**Comment by Jens-H-Eriksen** [comment]
It would be really nice if this could be implemented for SQL datasources as well ?

**Comment by Bercon** [comment]
https://github.com/grafana/grafana/pull/20752 adds support for this for Postgres ds

**Comment by carolwu-1206** [comment]
Is there any update of this issue on InfluxDB?

**Comment by gliu93** [comment]
It's been a few years? This is really a very wanted feature. Thanks a lot!

**Comment by horazont** [comment]
@carolwu-1206 

It seems to work just fine in influxdb now. AFAICT, the time end column needs to be a unix timestamp in millisecond precision, otherwise weird stuff happens (or it simply doesn't work at all).

Tested with Grafana v8.2.5 (b57a137acd).

**Comment by viewpointsa** [comment]
Yes work for me too. See my influxdb serie :
```
time                description                                  id                                   tags                      timeEnd       title
----                -----------                                  --                                   ----                      -------       -----
1622638773000000000 Maintenance made by  .       00000000-0000-0000-0000000000 maintenance,              1636117887000
```
My annotation query in grafana, using variable and simple quote :
`SELECT * FROM "event" WHERE ("id" = '$systemid') AND ($timeFilter) LIMIT 100`

![image](https://user-images.githubusercontent.com/22960684/145380961-e49b937a-024c-4737-8e85-463ef0c6cc3b.png)

**Comment by danldsk** [comment]
For InfluxDB do you have to set the timeEnd timestamp as a tag? 
I can't get it working

**Comment by gelicia** [comment]
This looks like something that would need to be implemented in individual datasources. InfluxDB was what the original poster wanted, and that looks like it was fixed. Please open tickets for other Grafana-supported datasources that need region annotations. If you want to see if it is possible already, the documentation for the datasource you are wondering about or the [community forum](https://community.grafana.com/) may be able to assist you. Thank you!
