### ISSUE TITLE
Update OpsGenie Notifier to support different api domains

### ISSUE THREAD

**Issue by bkaganyildiz** [grafana/grafana#10586]
https://github.com/grafana/grafana/pull/10584

Please include this information:
- What Grafana version are you using?
To update OpsGenie Integration 
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
I have updated OpsGenie Notifier script
- What was the expected result?
Able to send notifications to various OpsGenie domains
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10584
