### ISSUE TITLE
Add datapoint metadata in the graph panel

### ISSUE THREAD

**Issue by MatthewDolan** [grafana/grafana#10590]
Feature Request:

Allow the ability to return metadata for each datapoint a datasource returns. Then take that metadata and pass it through the "graph-click" app event in the graph panel.

Motivation:

Using a datasource plugin, we want to be able to do show the user more information when they click on a specific datapoint in the graph panel. Right now, a datasource plugin can register a "graph-click" app event handler to know whenever a user clicks on a specific "item" (i.e. a datapoint) in a graph panel. But the event doesn't have very much information about the datapoint that was clicked (only the X and Y values of the datapoint). We need some more information in that event handler (e.g. a global identifier) to give the user more information about the datapoint.

**Comment by torkelo** [comment]
this would be very hard to do so do not expect thing anytime soon.  It would require a new time series format that datasources can return and new api methods & flags in the datasource abstraction.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
