### ISSUE TITLE
Arithmetic Calculations on Singlestat Panel

### ISSUE THREAD

**Issue by jeanduporte** [grafana/grafana#10593]
Hi,

I want to make an arithmetic calculation on a Grafana on a Singlestat Panel.

Here is the formula : 
![formula](https://user-images.githubusercontent.com/28293036/35281162-8b4b0fe2-0052-11e8-83e5-fba3fcbef0ff.png)

Here is my series:
Serie1 = volume_3
Serie2 = conductivity
Serie3 = volume_4

I can do the calcul between Max and Min for each serie:
<img width="1259" alt="1" src="https://user-images.githubusercontent.com/28293036/35281448-343ac458-0053-11e8-9f4d-8383075e9e2e.png">
<img width="1261" alt="2" src="https://user-images.githubusercontent.com/28293036/35281449-345c06ae-0053-11e8-8eef-cc3f3d14e63d.png">
<img width="1262" alt="3" src="https://user-images.githubusercontent.com/28293036/35281451-3489779c-0053-11e8-87c4-969b79c50b02.png">

So the result must be 58.165 but it does not work when I do the calculate like you can see:
<img width="1265" alt="4" src="https://user-images.githubusercontent.com/28293036/35281508-61b3b4a8-0053-11e8-8c6c-4fb4f8d62064.png">

Any ideas of how I can do?

**Comment by torkelo** [comment]
Not sure, Arithmetic calculations are the responsibility of  the time series query layer not the visualisation panel. So if your unable to do your math with Graphite functions maybe you can the new function plugin feature in Graphite 1.2 where you can add new functions as plugins, https://github.com/graphite-project/graphite-web/pull/2146

**Comment by jeanduporte** [comment]
Finally I found how to do. Here is the solution :

![1](https://user-images.githubusercontent.com/28293036/35575782-91af0902-05dd-11e8-935e-cb5bdb296c87.png)

It works with the panel "Graph" but not on a "Singlestat" panel.
