### ISSUE TITLE
logined user cannot access anonymous org

### ISSUE THREAD

**Issue by tangdi** [grafana/grafana#10599]
Please include this information:
- What Grafana version are you using?
4.3.2
- What datasource are you using?

- What OS are you running grafana on?
Mac
- What did you do?
I have one user and he does not belong to the anonymous org explicitly.
- What was the expected result?
After anonymous access enabled, a logined user should be able access the anonymous org not matter whether he is in the org explicitly.
- What happened instead?
If user has logined and he does not belong to the anonymous org, he cannot access anonymous org and the response is 404 not found. But if the user does not login, he can access anonymous org

I think this might have some thing to do with **_org_redirect.go_**. It only checks for org-user mappings and does not take into anonymous org into account. 
```go
		cmd := models.SetUsingOrgCommand{UserId: ctx.UserId, OrgId: orgId}
		if err := bus.Dispatch(&cmd); err != nil {
			if ctx.IsApiRequest() {
				ctx.JsonApiErr(404, "Not found", nil)
			} else {
				ctx.Error(404, "Not found")
			}

			return
		}
```

**Comment by torkelo** [comment]
To access the anonymous org he needs to sign out, otherwise he will not take on the the "anonymous user"
