### ISSUE TITLE
Could not build Grafana from source code with master?

### ISSUE THREAD

**Issue by zhangxin0112** [grafana/grafana#10592]
Please include this information:

What Grafana version are you using? 4.6.3
What datasource are you using? influxdb
What OS are you running grafana on? centos6.7

-----------------------------------------------------------------
I build Grafana from source code with the version of master.
I had done with “Building the backend”.
I do "Building frontend assets" now.
My terminal stucked with "npm run watch" for a long time .
---------------------------------------------

![tim 20180123164949](https://user-images.githubusercontent.com/8244097/35266332-eaa2d0c8-005d-11e8-9340-f1aeb574d185.png)

**Comment by marefr** [comment]
Hey. `npm run watch` will run until you kill it. You run `npm run watch` mainly when developing Grafana. You can run `npm run build` instead.

**Comment by marefr** [comment]
Don't see that you have any problems so closing this
