### ISSUE TITLE
After 'npm run watch', I change the source code of front-end(just some text of button), but it's no work.

### ISSUE THREAD

**Issue by a67586646** [grafana/grafana#10597]
I change 'public/app/partials/login.html' like this.
```
<div class="login-button-group">
  <button type="submit" class="btn btn-large p-x-2" ng-click="submit();" ng-class="{'btn-inverse': !loginForm.$valid, 'btn-primary': loginForm.$valid}">
    Log Innnnnnnnnnn
  </button>
  <div class="small login-button-forgot-password">
    <a href="user/password/send-reset-email">
      Forgot your password?
    </a>
  </div>
</div>
```
But the text of log in button is 'Log in'.How can I change this?

**Comment by marefr** [comment]
You need to restart the grafana-server. See https://github.com/grafana/grafana#recompile-backend-on-source-change. Questions like these should be asked on our community site. Closing this

**Comment by torkelo** [comment]
If you set app_mode = development in your custom.ini file you do not need to restart backend when frontend has recompiled
