### ISSUE TITLE
Phantomjs rendering broken due to migration from govendor to dep

### ISSUE THREAD

**Issue by nklebedev** [grafana/grafana#10602]
grafana_5.0.0-11345pre1

From log:
grafana-server[48998]: t=2018-01-24T14:20:15+0300 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/infra?&panelId=8"
grafana-server[48998]: **Can't open '/usr/share/grafana/vendor/phantomjs/render.js'**
grafana-server[48998]: t=2018-01-24T14:20:15+0300 lvl=eror msg="failed to render an image" logger=png-renderer error="exit status 255"

Actually, there is no render.js next to phantomjs in /usr/share/grafana/vendor/phantomjs/ folder.

**Comment by bergquist** [comment]
This is due to the migration from govendor to dep. 

Fix incoming tomorrow.

**Comment by cristianocasella** [comment]
Hi @bergquist,
Sorry if I come back on this old topic, notification with direct image sending with Telegram si still not working, there is any planning about this trouble?
