### ISSUE TITLE
[Feature Request] Graph-Table Shared Tooltip

### ISSUE THREAD

**Issue by GitMrPriest** [grafana/grafana#10601]
I apologize if the feature exists, but I could not find any reference to it, or a plugin that allows it.

There is the "Shared Tooltip" feature, that aligns points between graphs with similar queries, right?
However, I want to show more data for a certain point, so I'd like to connect graph and table, or at least, once you click on a point in the graph, the line in the table referring to the same data is highlighted.

For instance, for automated testing, a feature is tested in different environments, with different app versions and the like. Each data point basically has results for a test, and other information about that test.
The graph shows me "tests executed" and "tests failed".
So when I click on it, the table containing the same query, but with different data shown, highlights the rest of the data for that test, for instance, duration, OS, Browser Version, etc...

A simple example below:
![image](https://user-images.githubusercontent.com/29352793/35327320-ff727144-0101-11e8-8293-edd48485eb37.png)

I am not sure if it matters, but we are using InfluxDB with Grafana.

If there are other ways to do it, please refer me to them.
I appreciate the help!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
