### ISSUE TITLE
CrateDb-Alerting: The datasource does not support alerting queries

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#10608]
I setup alerting but Grafana send me "DataSource does not support"

CAN YOU HELP ME HOW TO FIX IT??

and i want a full details..!!

Thanks!!!....In Advance..
![dataerror](https://user-images.githubusercontent.com/30747120/35379259-81e114da-01db-11e8-9f65-faa0c3d1d386.JPG)

**Comment by marefr** [comment]
The datasource does not support alerting queries. Nothing you can do about it for the moment. There's support for backend plugins in the making (see #6841 ) which eventually would allow plugin authors to implement support for alerting feature for any data source. 

Closing this. Questions regarding plugins should be asked in the plugin repository and/or our community site.

**Comment by vishuPPatel** [comment]
I need to the Cratedb data source get Alerting ...!!! i don't  change the data source ??

How to without changing data source in cratedb??


Thanks!!...
