### ISSUE TITLE
[Feature Request] Add .keyword fields in listboxes for Elasticsearch (ver. >=5.0) 

### ISSUE THREAD

**Issue by GedPL** [grafana/grafana#10616]
Starting with Elasticsearch 5.0 string type fields have additionally <field_name>.keyword fields which are used for aggregations. Currently you can only select them typing manually. Would be great to have them available for selection in Grafana's listboxes (for example in graph's metrics, ad-hoc filters, etc.)

Thanks !

**Comment by torkelo** [comment]
Do they exist in the mapping? If they are in the mapping they should appear. Try Grafana v5 (nightly build) think we made change a month back or so the index mapping parsing to also include .keyword fields.

**Comment by GedPL** [comment]
Previously had 4.4.1 version. Upgraded to 4.6.3 and got it !
Thanks !
