### ISSUE TITLE
Using mod_auth_mellon with grafana behind a reverse proxy in HTTPS

### ISSUE THREAD

**Issue by zpol** [grafana/grafana#10615]
I was so happy because finally got Grafana working with SAML 2.0 using mod_auth_mellon as authproxy with Okta as IdP.

Everything works fine using HTTP, except there's a message saying: Your content is going to be sent though an insecure connection .... 

Ok so I tried to switch to HTTPS but I've been stuck for two days debugging this. 
I get a: 400 Error: Bad request. Because at some point something is doing a HTTP request: 

`
Mixed Content: The page at 'https://grafana-sso.stg.example.cloud/mellon/postResponse' was loaded over HTTPS, but requested an insecure favicon 'http://grafana-sso.stg.example.cloud/mellon/login?ReturnTo=http%3A%2F%2Fgrafana%2Dsso.stg.example.cloud%2Ffavicon.ico&IdP=http%3A%2F%2Fwww.okta.com%2Fexxxxxxxxxxxxxxx7'. This content should also be served over HTTPS.`

But I didn't find why. Everything is set to use HTTPS. 
And lso it's a little bit strange because it's requesting a favicon.ico which doesn' t appear anywhere into grafana's source code... 

Context: 
The Grafana is behind a reverse proxy running inside an apache into an EC2 instance which is in a TG(Target Group) that is pointed by a LB.

So: 

`FQDN --> LB --> TG --> EC2(httpd+mod_mellon) --> Grafana `

**My Apache CFG:** 
```

<VirtualHost *:80>
        DocumentRoot /var/www/
        ServerName grafana-sso.stg.example.cloud
        ServerAlias grafana-sso.stg.example.cloud
        ServerAdmin webmaster@grafana-sso.stg.example.cloud

        RewriteEngine On
        RewriteCond %{THE_REQUEST} /healthcheck [NC]
        RewriteRule ^ - [R=200]

        LoadModule auth_mellon_module /usr/lib64/httpd/modules/mod_auth_mellon.so

        MellonCacheSize 100
        MellonLockFile "/var/run/mod_auth_mellon.lock"
        MellonPostTTL 900
        MellonPostSize 1048576
        MellonPostCount 100
        MellonDiagnosticsFile logs/mellon_diagnostics
        MellonDiagnosticsEnable Off

        SSLProxyEngine On
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        ProxyPass /mellon/ !
        ProxyPass /heclthcheck/ !
        ProxyPass / https://grafana.stg.example.cloud/
        ProxyPassReverse / https://grafana.stg.example.cloud/

        RequestHeader set X-WEBAUTH-USER %{MELLON_user}e env=MELLON_user
        RequestHeader set X-WEBAUTH-USER %{MELLON_email}e env=MELLON_email
        RequestHeader set X-WEBAUTH-USER %{MELLON_username}e env=MELLON_username
        RequestHeader set X-Forwarded-Proto "https"

        <Location />
                Require valid-user
                AuthType "Mellon"
                MellonEnable "auth"
                MellonVariable "cookie"
                MellonCookiePath /
                MellonUser "NAME_ID"
                MellonSessionDump Off
                MellonSamlResponseDump Off
                MellonEndpointPath "/mellon"
                MellonDefaultLoginPath "/"
                MellonSessionLength 86400

                MellonSPPrivateKeyFile /etc/httpd/mellon/mellon.key
                MellonSPCertFile /etc/httpd/mellon/mellon.cert
                MellonIdPMetadataFile /etc/httpd/mellon/idp-metadata-grafana-stg.xml

                MellonRedirectDomains [self] example-admin.okta-emea.com
        </Location>

        ErrorLog /var/log/httpd/grafana-sso.stg.example.cloud-error.log
        CustomLog /var/log/httpd/grafana-sso.stg.example.cloud-access.log combined
        LogLevel debug

</VirtualHost>
```

**My Grafana CFG:** 
```

[alerting]
execute_alerts = true
app_mode = production
[auth.proxy]
auto_signup = true
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
[database]
host = stg-grafanadb01.xxxxxxxxxxxxxx.us-east-1.rds.amazonaws.com:3306
name = grafana_dbname
password = grafana_passwd
type = mysql
user = grafana_user
[external_image_storage]
provider = s3
[external_image_storage.s3]
access_key = **********************
bucket_url = http://example-grafana.s3.amazonaws.com/stg/
secret_key = *****************************
[server]
http_port = 3000
[smtp]
cert_file =
ehlo_identity =
enabled = false
from_address = grafana@localhost.example
from_name = Grafana
host = localhost:25
key_file =
password =
skip_verify = false
user =
[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = Admin
```

**My Okta config:** 

Single Sign On URL:     https://grafana-sso.stg.example.cloud/mellon/post
ResponseRecipient URL:  https://grafana-sso.stg.example.cloud/mellon/postResponse
Destination URL:        https://grafana-sso.stg.example.cloud/mellon/postResponse
Audience Restriction:   https://grafana-sso.stg.example.cloud/mellon/metadata
Default Relay State:    https://grafana-sso.stg.example.cloud/

Some ideas? Thank you in advance.

**Comment by torkelo** [comment]
specify root_url (under [server]) section to your complete url you use in the browser (maybe https://grafana-sso.stg.example.cloud/)  , not sure what the favicon is about it looks like it's not Grafana that is accessing but your SSO login site

**Comment by zpol** [comment]
Thanks @torkelo we already tried that but it's still not working, looks like our IdP is posting assertions to my service provider via plain HTTP instead of HTTPS. I opened a ticket and waiting for response... Anyway over http everything is working fine.

**Comment by zpol** [comment]
Ok finally figured out how to solve this! 👍 
Desperation led me to think that it was something related to Okta but it wasn't. 

At the end it was because mod_auth_mellon is behind a LB so you have con configure apache like the documentation says.

Everything is well explained here: 

But in summary: 
- Compile and enable diagnostics in mod_auth_mellon
- Set the ServerName parameter to the same exact URL your using as SSO URL / Relay State.
  i.e.: 

`  1 <VirtualHost *:80>
  2         DocumentRoot /var/www/
  3         ServerName https://grafana-sso.stg.example.cloud
  4         ServerAlias grafana-sso.stg.letgo.cloud
  5         ServerAdmin webmaster@grafana-sso.stg.example.cloud
  6
  7         RewriteEngine On
  8         RewriteCond %{THE_REQUEST} /healthcheck [NC]
  ....`

Cheers!

**Comment by arunjadhav16** [comment]
Is there any post where  detail information available for Okta Grafana integration using proxy. I am trying to setup my Grafana instance for authentication using Okta behind proxy.

**Comment by arunjadhav16** [comment]
After configuration I get following error any idea 
The requested URL /mellon/post was not found on this server.

**Comment by zhang2kai** [comment]
hello, i am looking for a way to access grafana with Saml2 and i will use your ideal,would you please tell me how much work should i do or how much time will i spend on this? thanks.

**Comment by MahadevG** [comment]
@zpol 
I am trying to create SSO for grafana. I have a WebApplication(It will do some testing and it will return some reports). Dashboard those reports I am using Grafana. when use create a account for my application(ex: abc with password :xyz). It should be possible for him to login to grafana using the same username and password. How can I do this??. 
Already I tried with Google auth by following [Documentation ](http://docs.grafana.org/installation/configuration/)
Can you please share any documentation to achieve this??

**Comment by prabhinmp** [comment]
<VirtualHost *:443>
ServerName grafana.xxx.com     
    SSLEngine On
     SSLCertificateFile /etc/httpd/conf.d/ssl/xxx.cer
     SSLCertificateKeyFile /etc/httpd/conf.d/ssl/xx.key
SSLCACertificateFile /etc/httpd/conf.d/ssl/RootWcdGlobalsign.cer
SSLCertificateChainFile /etc/httpd/conf.d/ssl/IntermediateWcdGlobalsign.cer

<Location / >

    MellonEnable info
    MellonEndpointPath /mellon/
    MellonSPMetadataFile /etc/httpd/saml2/mellon_metadata.xml
    MellonSPPrivateKeyFile /etc/httpd/saml2/mellon.key
    MellonSPCertFile /etc/httpd/saml2/mellon.crt
    MellonIdPMetadataFile /etc/httpd/saml2/idp_metadata.xml

    AuthType Mellon
    MellonEnable auth
    Require valid-user


</Location>

               ProxyPass "/"  "http://localhost:3000/"
        ProxyPassReverse "/"  "http://localhost:3000/"
   ErrorLog /var/log/httpd/grafana-sso.stg.example.cloud-error.log
        CustomLog /var/log/httpd/grafana-sso.stg.example.cloud-access.log combined
        LogLevel debug
</VirtualHost>


SSO: keycloak saml

From grafana its getting redirect tot keycloak , after successful login at SSO  the user is not logged in grafana. Can you please suggest . @zpol
