### ISSUE TITLE
Date Format cannot be customized in table in v 4.6.3 (regression?)

### ISSUE THREAD

**Issue by ictcorebiz** [grafana/grafana#10612]
- What Grafana version are you using?
4.6.3
- What datasource are you using?
ElasticSearch
- What OS are you running grafana on?
Linux
- What did you do?
Use table panel, add "column style" on a date field (formatting works as expected). Now I want to enter the date format "DD-MM-YYYY", but the field is not-editable.
- What was the expected result?
Expected to be able to use custom date formats (like before)
- What happened instead?
Only allowed to select format from the list

**Comment by torkelo** [comment]
Ok, seems to be a bug introduced in this commit. 

https://github.com/grafana/grafana/commit/7a7e8c57d118daa3921406c8e835186173335445

@Ijin08 you seem to have changed the date format from a  metric-segment-model  to a native select input. The metric-segment-model component allowed custom formats (inputs) which the native select does not.  

Please change it to use the gf-form-dropdown component (the component that is meant to replace the metric-segment-model component)

**Comment by ictcorebiz** [comment]
Will this be backported to the 4.6 codeline, or should I make a manual fix in the running environment?
