### ISSUE TITLE
Customizing alert keywords

### ISSUE THREAD

**Issue by hah2930** [grafana/grafana#10614]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
[4.6.3]
- What datasource are you using?
[Graphite]
- What OS are you running grafana on?
[Ubuntu]
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Dear All,

I need some help with the alert keywords. Normally, when the alert is fired, the message says [Alerting] followed by the alert message. When the alert is reset, the message says [OK] followed by the alert text.

Is there anyway I can change the reset message from saying [OK] to [RECOVERY] or [CLEARED] etc…

Many Thanks!

**Comment by bergquist** [comment]
Thank you for taking the time to improve Grafana.

That's currently not possible and I don't see us adding it in the near future. Maybe once we implement https://github.com/grafana/grafana/issues/5848 

I'm closing this issue since this exact feature won't be added unless its a part of #5848
