### ISSUE TITLE
Grafana alert condition does not work on time when trigger is fired

### ISSUE THREAD

**Issue by user-redans** [grafana/grafana#10629]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
   Grafana v4.6.3
- What datasource are you using?
   InfluxDB
- What OS are you running grafana on?
  Ubuntu 14.04.5
- What did you do?
   The email is send immediately, after alert is firing, not on time query (A, 3m, now), after 3 min
  ( Evaluate every: 10s )
- What was the expected result?
   i want that email send after 3m of firing alarm
- What happened instead?
The email is send immediately, after alert is firing, not on time query (A, 3m, now), after 3 min
  ( Evaluate every: 10s )

**Comment by torkelo** [comment]
that is not how it works.  the `query (A, 3m, now)` specifies the time range for the metric query (3m from now to now). 

You specified evaluation every 10s so the query (and alert rule) is going to be executed every 10s, if the conditions are true and the alert rule state changes the notifications fire immediately

**Comment by user-redans** [comment]
there is a way to send email after 3m, not immediately?

**Comment by torkelo** [comment]
no not currently

**Comment by user-redans** [comment]
ok. Thanks for help!
