### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by hanwenbo** [grafana/grafana#10625]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
last
- What datasource are you using?
no
- What OS are you running grafana on?
centos
- What did you do?
install
- What was the expected result?

- What happened instead?
```
# github.com/grafana/grafana/vendor/github.com/grafana/grafana_plugin_model/go/datasource
vendor/github.com/grafana/grafana_plugin_model/go/datasource/service.go:20: cannot use GRPCServer literal (type *GRPCServer) as type DatasourcePluginServer in argument to RegisterDatasourcePluginServer:
	*GRPCServer does not implement DatasourcePluginServer (wrong type for Query method)
		have Query("context".Context, *DatasourceRequest) (*DatasourceResponse, error)
		want Query("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *DatasourceRequest) (*DatasourceResponse, error)
```
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by hanwenbo** [comment]
# github.com/grafana/grafana/pkg/social
pkg/social/social.go:114: cannot use SocialGithub literal (type *SocialGithub) as type SocialConnector in assignment:
	*SocialGithub does not implement SocialConnector (wrong type for Client method)
		have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
		want Client("context".Context, *oauth2.Token) *http.Client
pkg/social/social.go:128: cannot use SocialGoogle literal (type *SocialGoogle) as type SocialConnector in assignment:
	*SocialGoogle does not implement SocialConnector (wrong type for Client method)
		have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
		want Client("context".Context, *oauth2.Token) *http.Client
pkg/social/social.go:143: cannot use SocialGenericOAuth literal (type *SocialGenericOAuth) as type SocialConnector in assignment:
	*SocialGenericOAuth does not implement SocialConnector (wrong type for Client method)
		have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
		want Client("context".Context, *oauth2.Token) *http.Client
pkg/social/social.go:166: cannot use SocialGrafanaCom literal (type *SocialGrafanaCom) as type SocialConnector in assignment:
	*SocialGrafanaCom does not implement SocialConnector (wrong type for Client method)
		have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
		want Client("context".Context, *oauth2.Token) *http.Client

**Comment by wbeling** [comment]
In case someone find the same error while building this project. Just type:
`go version`
If it is < 1.9 then you need to upgrade _golang_.
