### ISSUE TITLE
Cannot setup & build when go version is 1.9.3

### ISSUE THREAD

**Issue by liuhuiiris126** [grafana/grafana#10626]
Grafana version 5.0.0-pre1

OS CentOS release 6.5 (Final)

Go version 1.9.3

I can't setup grafana successfull, because I use go1.9.3. It shows
```
signal: segmentation fault (core dumped)
```

so I change the go version to 1.9.2 , then done

**Comment by bergquist** [comment]
What do you mean with setup? 
What database are you using?

I can compile, test and run grafana on golang 1.9.3.

**Comment by liuhuiiris126** [comment]
when I run 'go run build.go setup'，I have not started the service yet

**Comment by bergquist** [comment]
I created a branch and upgraded Grafana build pipeline to use 1.9.3. Let's see if it returns any errors
https://circleci.com/gh/grafana/grafana/11403

**Comment by bergquist** [comment]
The build was successful. So I think something is broken on your machine. 

does `go run build.go build` work?

**Comment by bergquist** [comment]
Closing this since the build works fine on Circle ci. feel free to ping me if `go run build.go build` doesn't work.
