### ISSUE TITLE
[Feature Request] - Grafana 5.0 - Dashboard - Rows - Add option to query data source only when row is expanded

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#10620]
Background:
Each panel in a dashboard (typically) represents a query to the specified data source.  When opening a dashboard with many panels, many concurrent queries to the data source(s) are also performed.  With a large dashboard (with many panels), this can cause a significant load on the data source.  A large dashboard may have many panels hidden within a row, that are only viewed when needed by expanding the row.

Feature Request:
A useful feature would be to have panels only query the data source (and update themselves) when they are displayed; when the row they are within is expanded to be displayed.

This would need to be optional, as the current use case (when dashboard is opened, all panels are updated) is also useful in some instances (and is the current mode).

This would likely  improve performance (actual and perceived) as unneeded queries (and panel updates) could be delayed until actually needed.

Notes:
- What Grafana version are you using? v5 - Nightly
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? RedHat/ CentOS 7

**Comment by torkelo** [comment]
collapsed rows have never caused panel metric queries to fire. The panel is not loaded at all so no requests are issued for panels inside collapsed rows.

**Comment by davewat** [comment]
You are correct.  Was looking as incorrect data.  Thanks.
