### ISSUE TITLE
html/template: "index" is undefined && /favicon.ico=500 && login=500

### ISSUE THREAD

**Issue by Nefariis** [grafana/grafana#10621]
- Grafana 4.6.3 (latest)
- Influx 1.4.2 (but it's not a db issue)
- Windows
- Start the grafana-server and go to http://localhost:8083
- Expected: The login page loads
- Result: "html/template: "index" is undefined"

I've been using grafana for years now on both osx and linux (I love the product), but I have a client that needs it installed on windows and I am running into some issues. 

I started the grafana-server just fine like normal but when I travel to localhost:port, I am receiving the error `html/template: "index" is undefined`

Here are the server logs -

```
t=2018-01-25T14:27:31-0800 lvl=info msg="Starting Grafana" logger=server version=4.6.3 commit=7a06a47e6 compiled=2017-12-14T00:36:59-0800
t=2018-01-25T14:27:31-0800 lvl=info msg="Config loaded from" logger=settings file=C:\\Users\\mcphzw1\\Documents\\grafana-4.6.3/conf/defaults.ini
t=2018-01-25T14:27:31-0800 lvl=info msg="Config loaded from" logger=settings file=C:\\Users\\mcphzw1\\Documents\\grafana-4.6.3\\conf\\custom.ini
t=2018-01-25T14:27:31-0800 lvl=info msg="Path Home" logger=settings path=C:\\Users\\mcphzw1\\Documents\\grafana-4.6.3
t=2018-01-25T14:27:31-0800 lvl=info msg="Path Data" logger=settings path=C:\\Users\\mcphzw1\\Documents\\grafana-4.6.3\\data
t=2018-01-25T14:27:31-0800 lvl=info msg="Path Logs" logger=settings path=C:\\Users\\mcphzw1\\Documents\\grafana-4.6.3\\data\\log
t=2018-01-25T14:27:31-0800 lvl=info msg="Path Plugins" logger=settings path=C:\\Users\\mcphzw1\\Documents\\grafana-4.6.3\\data\\plugins
t=2018-01-25T14:27:31-0800 lvl=info msg="App mode production" logger=settings
t=2018-01-25T14:27:31-0800 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-01-25T14:27:31-0800 lvl=info msg="Starting DB migration" logger=migrator
t=2018-01-25T14:27:31-0800 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-01-25T14:27:31-0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-01-25T14:27:31-0800 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-01-25T14:27:31-0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-01-25T14:27:31-0800 lvl=info msg="Starting plugin search" logger=plugins
t=2018-01-25T14:27:31-0800 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-01-25T14:27:31-0800 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-01-25T14:27:31-0800 lvl=info msg="Initializing Stream Manager"
t=2018-01-25T14:27:31-0800 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:8083 protocol=http subUrl= socket=
t=2018-01-25T14:27:39-0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=500 remote_addr=127.0.0.1 time_ms=8 size=36 referer=
t=2018-01-25T14:27:39-0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=500 remote_addr=127.0.0.1 time_ms=6 size=36 referer=http://localhost:8083/login
t=2018-01-25T14:27:41-0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=500 remote_addr=127.0.0.1 time_ms=8 size=36 referer=
t=2018-01-25T14:27:41-0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=500 remote_addr=127.0.0.1 time_ms=6 size=36 referer=http://localhost:8083/login
```
I've tried numerous ports, multiple browsers, completed a fresh install, and googled every combination of "favicon.ico, grafana, login, and 500" - but I cannot make out what the issue is. I was hoping to get a hand in helping troubleshoot this.

Any help on the issue would be greatly appreciated.

Thank you
-Zach

**Comment by Nefariis** [comment]
just in case this helps -

![image](https://user-images.githubusercontent.com/26125080/35417284-9ed96780-01e1-11e8-8114-12d9b39f57c4.png)

**Comment by torkelo** [comment]
strange, did you build this yourself? 

Can you check what files you have in C:\Users\mcphzw1\Documents\grafana-4.6.3\public\views ? 

What is the working dir for grafana-server? (how did you start it), if you do not specify homepath via  command line path you need to have C:\Users\mcphzw1\Documents\grafana-4.6.3 as working dir

**Comment by Nefariis** [comment]
So it was a folder issue - vendor, test, views didnt copy over or deleted itself ./? 

What's weird - I unzipped it two separate times and received the same error message. So I copied everything from the zip/public into public and works. I have no idea why some folders didn't unzip/copy/or were deleted and I can't seem to repro. 

I guess this issue can be closed - thanks for the help.
