### ISSUE TITLE
root_url doesn't change the URLs

### ISSUE THREAD

**Issue by harshil-hbo** [grafana/grafana#10623]
Read before posting: 

Please include this information:
- What Grafana version are you using? : 4.6.3
- What datasource are you using?: Graphite
- What OS are you running grafana on? : Amazon Linux
- What did you do? 
Running Grafana on an EC2 instance (@ ip `a.b.c.d`) behind an ELB with SSL termination at ELB. Added a DNS entry in Route53 (stats.example.com)  for the ELB so that Grafana is accessible with a domain name. Changed settings in grafana.ini `server.root_url`: `https://%(domain)s/` and `server.domain`=`stats.example.com`
- What was the expected result?
Things would work fine and panels would render without issues
- What happened instead?
Panels do not render directly. See a mixed content warning with HTTPS broken error. The console reads `stats.example.com/dashboard/f/ was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://a.b.c.d/render'. This request has been blocked; the content must be served over HTTPS.

**Comment by torkelo** [comment]
if you add a subpath to root_url you need a reverse proxy as well that adds the sub path and rewrites the urls

**Comment by harshil-hbo** [comment]
There is no subpath. Grafana is hosted at `stats.example.com` and not `www.example.com/stats`. I need grafana to return `https://stats.example.com/render` instead of `http://a.b.c.d/render`. I believe changing the root_url config option would do that.

**Comment by torkelo** [comment]
sounds like you have setup a data source with direct access over http (then grafana will issue requests to that datasource directly from the browser) switch to proxy mode to have grafana-server proxy the request to Graphite
