### ISSUE TITLE
[Bug/Feature request] Variable based drop-down selection not saved to JSON

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#10627]
Please include this information:
- What Grafana version are you using? **Version 5.0.0-pre1 (commit: ee973a9)** and **Version 4.6.2 (commit: 8db5f08)**
- What datasource are you using? **Influx**
- What OS are you running grafana on? **Ubuntu 17**
- What did you do?
I'm using dashboard with drop-downs.
One drop-down selects single value from a static array of choices and the other one use Influx query to get its values and allows selecting a single value.
I'm selecting values from both, save and export dashboard as JSON.
Then I'm choosing another dashboard, go back to the original one, select *different* values from both original dropdowns and save.
Then I'm importing dashboard from just saved JSON, and choose to overwrite it.
Static dropdown restores to original value while dynamic one is not changed.
It means that the selection from dynamic drop-down is not saved.
I think it should.
I don't know if this is a bug or feature request.
- What was the expected result? **dashboard restored from JSON should be in exactly the same state as when exported**
- What happened instead? **Value from a dynamic/variable based dashboard was not restored**

**Comment by torkelo** [comment]
Go to dashboard settings / View JSON if you want to capture a complete backup of the current dashboard. 

The share / Export dashboard feature will clean the dashboard of all metric data (query variable values and current selected value for query variables) to make it easier to share on grafana.com or to other grafana instances

**Comment by lukaszgryglicki** [comment]
Thanks.
Just wondering...
Can we have a checkbox on JSON export that says "Include all metrics data" or something similar?
Anyway - can live without this. Will just have to use "View JSON" to save all dashboards in all projects (so I will postpone this a bit because that will be about 10 x 24 + 39 = 279 JSONs to manually copy-paste).

**Comment by torkelo** [comment]
We will try to improve the scenario for dashboards managed through the new provisioning system (http://docs.grafana.org/administration/provisioning/#dashboards ) so that it will be possible to mark dashboards as "read only" in the sense that you cannot save them through the UI, but when you try save you will be given a JSON modal instead and a "Copy JSON to clipboard" button. 

Will that work for your usecase?

**Comment by lukaszgryglicki** [comment]
Sure, that will be better than manual copy.
Anyway - I will have to export and reimport soon due to big differences between v4 and v5 JSONs so this is not a problem anymore.
For me, it is enough that I can cop entire dashboard state - no matter how to do this.
The more important now is how many clicks does it require :P 
Importing and exporting many dashboards recently (due to adding "table" tag, hiding date picker and updating one drop down value) and I did that so many times that I could probably do that blind and my mouse was hovering over a dialog that didn't yet appeared very often :P
