### ISSUE TITLE
Panel descriptions not showing as new lines

### ISSUE THREAD

**Issue by JosephFY** [grafana/grafana#10636]
- What Grafana version are you using?
4.4.3 ( also same behavior on 5.0.0-pre1)
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Redhat 7.4

Panel descriptions are not showing as new line on upper left corner although they are entered as separate lines in the description section. 
![image](https://user-images.githubusercontent.com/28739923/35450137-bbeb6d66-0284-11e8-83a5-d326744c731d.png)

![image](https://user-images.githubusercontent.com/28739923/35450106-a2d9edfc-0284-11e8-98e3-9aba809a05f2.png)

when entering empty lines between the lines it works
![image](https://user-images.githubusercontent.com/28739923/35450162-cf0821b4-0284-11e8-8096-abe2ca59b1a4.png)

![image](https://user-images.githubusercontent.com/28739923/35450240-ff71a10e-0284-11e8-931e-84022c3ec4d2.png)

PS: I recall I'v noticed the same behavior on the alerting descriptions as well, will have to double check on that and submit a new inquiry for it, just though it worth mentioning here

Thank you

**Comment by torkelo** [comment]
markdown requires two newlines to form a new paragraph (and hence create newlines)

**Comment by JosephFY** [comment]
Thank you for the reply @torkelo . We are planning to use the descriptions a lot as we are expanding the number of users who will access grafana and that will help adding a lot of the FAQ and having the empty lines consumes so much space on the sceen. is this something that would be worked on in a future releases?

**Comment by torkelo** [comment]
if you want a single linebreak in markdown use two white spaces

**Comment by noozoo** [comment]
Two white spaces didn't work for me, either in the same line or on a new line; but two white spaces and then a new line did.

**Comment by kfirfer** [comment]
not working for me

**Comment by katzda01** [comment]
None of the suggestions worked for me at all (Grafana v10.2.3)
