### ISSUE TITLE
Telegram inline images not working

### ISSUE THREAD

**Issue by ratchetnclank** [grafana/grafana#10631]
Would it be possible to add image support for telegram notifications?

The API supports sending images, so it could be added.
https://core.telegram.org/bots/api#sending-files

**Comment by xlson** [comment]
Support for inline images in Telegram notifications was added through #9967 but does not work properly. Discussion that issue here. I'm taking a look at it.

**Comment by fanvinga** [comment]
@xlson The feature of Telegram Bot in-line image notifications works well in commit #594447f5 . But as my test result shows(you can find it in additional discussion of or #9967), it doesn't work in commit #31a5134.

**Comment by nklebedev** [comment]
@ratchetnclank, the reason is described in #10602 and fixed by commit #ac2b36c.

**Comment by xlson** [comment]
@nklebedev @fanvinga: thanks for clearing that up.

**Comment by cdalexndr** [comment]
Image upload doesn't work in Grafana v6.3.3 (commit: 84d0a71).
The option **Upload Image** is ON in the notification channel settings.
In Telegram I received the following text with no image:
```
[Alerting] Errors / container alert
State: Errors / container alert
Message: Found errors
URL: http://todo:3000/d/17hihJ5Zk/docker-metrics?fullscreen&edit&tab=alert&panelId=10&orgId=1

Metrics:
web: 0.001
logstash: 0.003
filebeat: 0.017
```

**Comment by papagian** [comment]
@cdalexndr could you please open a new issue referencing this one?
