### ISSUE TITLE
Grafana GroupBy prometheus template support

### ISSUE THREAD

**Issue by stefan-improbable** [grafana/grafana#10632]
Grafana supports multi-selectable template variables for prometheus: http://docs.grafana.org/img/docs/v4/templated_dash.png. They can be used in query like `up{server=~"$server"}`, however `count(up{server="abc"}) by ($groupby_vars)` does not work. It is possible to hack around this, but it would be better if grafana supported this natively.

**Comment by mtanda** [comment]
I guess this issue is caused by all template variables are joined by "|".
https://github.com/grafana/grafana/blob/v5.0.0-beta1/public/app/plugins/datasource/prometheus/datasource.ts#L68

In by clause, we need to use "," character.

**Comment by stefan-improbable** [comment]
@mtanda yeah, that's correct. If there was an option to use , instead of | (we need both), it would solve my issue.

**Comment by torkelo** [comment]
this will be possible once we add a new interpolation syntax that will allow you to specify formatting when you use the variable: 
https://github.com/grafana/grafana/issues/9911 

example: 
```
count(up{server=~"${server:regex}"}) by (${groupBy:comma})
```

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/pull/11002 is merged.
But, unfortunately it contains extra `{` and `}`.
https://github.com/grafana/grafana/blob/v5.0.0/public/app/features/templating/template_srv.ts#L120

**Comment by torkelo** [comment]
Now we just need to add a comma format so ${host:comma}  not sure what name is best comma or csv

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/11141
