### ISSUE TITLE
can't disable /metrics endpoint

### ISSUE THREAD

**Issue by alterationx10** [grafana/grafana#10638]
The Prometheus /metrics endpoint doesn't seem to be disabled when setting the key under [metrics]. I've tried setting it in the grafana.ini file and further via the environment variable. I can confirm that /admin/settings reports that metrics enabled = false, but the /metrics endpoint still puts out data.

Please include this information:
- What Grafana version are you using?

grafana/grafana:4.6.3 
[Grafana v4.6.3 (commit: 7a06a47) as reported on the bottom of the installation]

I also tried with grafana:4.6.2 and grafana:master

- What OS are you running grafana on?
Docker image in kubernetes

- What did you do?
disabled metrics via grafana.ini as well as tried setting the environment variable GF_METRICS_ENABLED to false

- What was the expected result?
/metrics would not provide metrics

- What happened instead?
/metrics still provides metrics

**Comment by bergquist** [comment]
This is by design. Maybe the configuration could be more explicit. Any reason why you want to disable it?

**Comment by alterationx10** [comment]
I have an ingress to expose grafana publicly, and didn't want the /metrics endpoint exposed. 

It's not a big deal if it's always on, I was just expecting is to not return anything based on setting the config to false from the docuentation ```Enable metrics reporting. defaults true. Available via HTTP API /metrics.```

So does that mean 
```
[metrics]
enabled = true
```
just puts out  _more_ information?

**Comment by palmerabollo** [comment]
@bergquist Could you please elaborate? I also want to expose grafana publicly without the /metrics endpoint exposed. If GF_METRICS_ENABLED doesn't disable the endpoint, what is it for? Thanks.

**Comment by monotek** [comment]
Imho this should be reopened. 
Its also an issue for us with 5.0.x

**Comment by bergquist** [comment]
Just me beeing wrong. Fix incomming.

**Comment by bergquist** [comment]
It's now possible to require basic auth for the endpoint as well https://github.com/grafana/grafana/issues/13577
