### ISSUE TITLE
MySQL nested template variables not evaluating correctly

### ISSUE THREAD

**Issue by tardoe** [grafana/grafana#10640]
Please include this information:
- What Grafana version are you using?
4.6.1
- What datasource are you using?
InfluxDB and MySQL (for template vars)
- What OS are you running grafana on?
Ubuntu
- What did you do?
3 Template Variables queried using MySQL:
$customer =  `select name from customer`
$fleet_num = `select fleet.fleet_name from fleet join <with customer> where customer in($customer)`
$vehicle = `select vehicle.name from vehicle join <with customer> join <with fleet>  where customer.name in($customer) and  fleet.name in($fleet)`
I then created a templated row that repeats on Vehicle Fleet and shows vehicle details on a given row, with one fleet to a row.
- What was the expected result?
Each variable was executed correctly for the drop down boxes for variables and when filtering on fleet, only the correct vehicles for that fleet are shown. When a repeating row based on the $fleet_num variable is created with graphs that filter on $customer, $fleet_num AND $vehicle would only show metrics that apply to the combination $fleet_num AND $vehicle - e.g. only vehicles for that fleet number should be shown. 
- What happened instead?
The correct drop down box behaviour was shown however, for each repeating fleet_num row all vehicles across all fleets are shown. Given certain vehicle numbers are the same (non-unique) across fleets, metrics for vehicles that don't exist in a given fleet are shown. It's as if the $vehicle variable isn't being re-evaluated with a single $fleet_num in the query.

**Comment by torkelo** [comment]
nested variables and repeating rows does not work like that. The variable queries are issued before the repeat is performed, it is not performed per row. Variable value is scoped to row, but the the nested (child query variable) will not execute it's query based on the scoped parent variable value.

**Comment by lucavignali** [comment]
Hi, although this request was closed as it is not a bug, I see the concept of nested variable + repeat feature as very useful. Are you considering it as a roadmap feature?
Thanks,
Luca
