### ISSUE TITLE
Provide an API at grafana.com for uploading/managing shared dashboards.

### ISSUE THREAD

**Issue by burton-scalefastr** [grafana/grafana#10641]
We are trying to share our dashboards with the community and need a way to automatically upload them.

We've created:

https://github.com/scalefastr/scalefastr-prometheus-grafana-dashboards

which are "known good" dashboards with Grafana + Prometheus 2.0.

Many of them have been changed and we're about to make another big modification to them to unify labels.

It would be nice to have an API where we can take them and upload them to 

https://grafana.com/dashboards

without having to do so manually.

We can attach all the metadata and make them machine readable so your community can discover them.

**Comment by mliyanagamage** [comment]
I believe the correct way to distribute custom dashboards is to build an app plugin

**Comment by bergquist** [comment]
Building an app plugin would be one way of solving the issues. All thou If you want to iterate quickly on the dashboards I think its better to upload them to grafana.com. We just need to do a better job enabling that flow.

**Comment by torkelo** [comment]
There is an API for grafana.com, signup and go to your org profile to create an API Key. With that API key you can upload a dashboards using the same API that the grafana.com frontend uses. The API is not documented so you need to upload / update a dashboard with chrome dev tools open and inspect the API calls the grafana.com frontend makes.

**Comment by bergquist** [comment]
@torkelo then I think this issue should be about adding docs/improving the flow.

**Comment by davidnewhall** [comment]
It took me an hour of google to find this thread. Googling "grafana api" and hoping for docs on how to use the public grafana.com API to manipulate my shared dashboards is unbelievably complicated. And to come here and read, from a post a year ago, that it's undocumented and the only way to figure it out is with chrome.. uhg.  Please consider adding a simple one page doc that says "There are no docs for grafana.com/api" and maybe link this issue. I don't know. Save someone else an hour please.
