### ISSUE TITLE
5.0: Side bar hiding/unhiding very distracting

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#10642]
Please include this information:
- What Grafana version are you using?
5.0 (5.0.0-11408pre1 nightly build)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux CentOS/7

- What did you do?
Let mouse cursor sit idle for a minute.
After being idle for a minute, move the cursor.

- What was the expected result?
Not resize the window contents.

- What happened instead?
Window contents get resized/moved.

----

While I personally don't like the side bar, I don't imagine that's going to go away. But at the least can we make the auto-hide functionality customizable? A UI preference for setting the idle timer duration, and disabling it completely? The setting would be both per-organization, and per-user like the UI theme setting currently is.

Another possible solution might be to make the side bar hidden by default, and pop up when you mouse over (or click like you currently do) the grafana logo, but the pop-up behavior would be an overlay, and would not resize the window content.

**Comment by torkelo** [comment]
We can fix the scroll issue so that counts as an activity so the inactive view won’t trigger

**Comment by torkelo** [comment]
Closing on his as there already is an issue for that

**Comment by phemmer** [comment]
Wrong issue. The scroll thing is #10643

**Comment by torkelo** [comment]
Yes, sounded like fixing that would fix this (in email maybe you updated this issue?).  Anyway you can hide sidebar if you do not want inactive view make panels wider

**Comment by phemmer** [comment]
yes, when this issue was originally created it covered 2 different issues, but then I split the scroll wheel thing out into its own issue so it could be addressed separately.

The problem is that the side bar is not customizable at all. You can neither disable the auto-hide functionality, nor can you make it always auto-hide and pop up only when you need it (as an overlay so it doesn't re-arrange your window contents) and go back to hiding.

**Comment by phemmer** [comment]
Should I open a new issue for this?

**Comment by torkelo** [comment]
not sure it is worth it, we are not going to change the sidebar, you can hide it already, which reduces the movement when going to inactive mode.  But maybe this will be a more common request after v5 :) But we will keep an eye out for more feedback on an idle timer setting / disable setting.

**Comment by BugRoger** [comment]
We are running our Grafanas in `?kiosk=true` mode. The sidebar is quite distracting. Not sure if it is supposed to auto-hide. If so, that is not working. If not, maybe it would be an idea to permanently hide it in kiosk mode.

Another URL parameter `?dv=true` to set inactive view mode would work too, without having to do the whole org/preferences thing.

**Comment by torkelo** [comment]
it should definitely hide in kiosk mode, it will hide automatically (when in normal mode), will fix the kiosk mode.

**Comment by svet-b** [comment]
Just wanted to check before I open (yet another) feature request on this - is there actually a configuration option to have the sidebar hidden by default, until the user explicitly clicks to open it? Or did the "you can hide it already" comment above simply mean that the user can hide it by clicking on the icon?

We have an organization where most users are simply viewers with little or no Grafana experience. There's very little in the sidebar that would actually be relevant for these users, so having a hidden-by-default sidebar would make for better UX.

**Comment by jmls** [comment]
@svet-b did you ever get an answer to this ?

**Comment by svet-b** [comment]
@jmls afraid I haven't

**Comment by jmls** [comment]
ok, thanks. I *think* that writing a value to localStorage may work

`localStorage.setItem('grafana.sidemenu', 'false');`

playing around with it atm

**Comment by jonathanstrong** [comment]
is there currently a url parameter setting that can disable the auto-hide of the sidebar? I too find it distracting, I have several dashboards open and if the auto-hide has triggered it takes 2-3 seconds for the browser to render when I mouseover to investigate something. Small annoyance but happens to me all day long.

**Comment by torkelo** [comment]
we are investigating a move to a top nav bar:
https://github.com/grafana/grafana/issues/13573 

But not 100% decided yet, needs more testing & feedback.

**Comment by jonathanstrong** [comment]
top nav bar looks great! thanks!
