### ISSUE TITLE
Not update expand row content

### ISSUE THREAD

**Issue by ilgizar** [grafana/grafana#10647]
1. Repeat row (variable1) with repeat graph (variable2).
2. Collapse row.
3. Change variable2 value.
4. Expand row.

Repeat graphs are not changed.

Grafana version: v5.0.0-pre1 (commit: c34d458)
Datasource: TestData
Server OS: Ubuntu 16.04.3 LTS (4.4.0-72-generic)
Client OS: Ubuntu 17.10 (4.13.0-21-generic)
Browser: Google Chrome 63.0.3239.132

**Comment by alexanderzobnin** [comment]
Fix doesn't work for rows except first one, as described in #10679
