### ISSUE TITLE
Influxbd - disctinct included into count query

### ISSUE THREAD

**Issue by JulienChampseix** [grafana/grafana#1064]
Using influxdb it allow to run count of distinct fields but over grafana it looks like not possible (without passing over query editor mode). 
That will be great if grafana could propose at the same level as max/min/mean/count/../..
Could be labelled 'countuniq'.

Example of query running fine over influxdb : 
select count(distinct(fqdn)) from hosts.metrics

By this way, this type of data could be used over singlestat.

**Comment by Bostwickenator** [comment]
I just ran into this. It would make a good addition.

**Comment by MorrisJobke** [comment]
I also tried hard to get this working and then found the query editor. Maybe someone can give me a hint where to add this in the code base.

**Comment by torkelo** [comment]
the distinct aggregation function was added a long time ago, so closing this
