### ISSUE TITLE
5.0: drop-down menus slow to open

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#10646]
Please include this information:
- What Grafana version are you using?
5.0 (5.0.0-11408pre1 nightly build)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux CentOS/7

- What did you do?
Edit a graph and click on any of the fields which result in a drop down menu, for example the `fill()` option.

- What was the expected result?
Menu opens immediately.

- What happened instead?
Menu opens after a 500ms delay. Verified through browser profiling. It's ~500ms every time.
![image](https://user-images.githubusercontent.com/1826947/35489192-8e2d59b4-0461-11e8-9fed-f998711e8557.png)

Browser: Chrome 62.0.3202.94

**Comment by torkelo** [comment]
fixed by reverting, https://github.com/grafana/grafana/commit/cd2161e7966fd05daed843ee5e45cac78b335d13
