### ISSUE TITLE
InfluxDB: Enable ::tag and ::field in Query Builder

### ISSUE THREAD

**Issue by Genmutant** [grafana/grafana#10654]
Environment:
- Grafana Version: 5.0.0-pre1, Linux Version: 5.0.0, Package Iteration: 1517219402pre1
- InfluxDB 
- Windows 7

In InfluxDB I have in the same measurement a field (old values) and tag (for new entries) with the same name "InitialState". I want to force the use of the tag.

That's possible by using ::tag
> Use ::[field | tag] to differentiate between an identical field key and tag key .

I can't use that in the normal query builder, because it get's converted to "InitialState::tag", which doesn't work. It should be "InitialState"::tag (or analogous "InitialState"::field). It would be nice to have the possibility to force that without converting the query to a raw query.

**Comment by torkelo** [comment]
where do you want this ? In the where clause?

**Comment by Genmutant** [comment]
I personally only need it in the where clause, but I think it would be sensible to add it to the select clause, too.

**Comment by mpetersen42** [comment]
@torkelo 

telegraf changed how networks store SNMP data to InfluxDB so it's possible many people could need this.  I'd say anywhere you're presenting a series of know tags to select from it should use ::tag or ::istag in the query by default.

https://github.com/influxdata/telegraf/issues/4326
https://github.com/influxdata/telegraf/issues/4203

**Comment by m-peko** [comment]
Is there a plan when this feature is going to be implemented?

**Comment by bohandley** [comment]
We are closing this due to the age of the issue. Please reopen if this is still an issue with current version of Grafana.
