### ISSUE TITLE
CloudWatch: Rename period to min period in query editor

### ISSUE THREAD

**Issue by tuukkamustonen** [grafana/grafana#10656]
When you select too low period or too long time range into CloudWatch query, Grafana automatically adjusts (increases) the period, but doesn't tell the user that this happened. With following:

![image](https://user-images.githubusercontent.com/94327/35507219-b4015864-04f4-11e8-9515-f45c2f74f64b.png)

If you're inspecting a time range of, say, a few hours, then the query is sent in with period of `60` as it should. But if you zoom out to a few days or so, Grafana auto-increases the query (in `Query Inspector`):

![image](https://user-images.githubusercontent.com/94327/35507280-df665522-04f4-11e8-9394-931200c35ee4.png)

I guess it makes sense to do this, to prevent user from overloading the system/CloudWatch. But it should be informed to the user (e.g. flash message, or something).

I'm seeing https://github.com/grafana/grafana/pull/9753 that added `{{period}}` for being able to refer to / print out the used period. That's nice, but maybe a warning would be useful as well?

- What Grafana version are you using? `4.5.1`
- What datasource are you using? `CloudWatch`
- What OS are you running grafana on? `Linux`

**Comment by torkelo** [comment]
agree, should rename the property in the UI to say "Min period"
