### ISSUE TITLE
Expose user's partial query in ad hoc filter

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#10658]
If I create a custom datasource plugin that implements `getTagValues()` and `getTagKeys()`, the ad hoc query system will know how to populate the dropdowns.

However, `ad_hoc_filters.getOptions()`, which calls these two functions, does not pass down the current string/query. This means its impossible to filter matches from my datasource backend.

```typescript
if (segment.type !== 'value') {
promise = ds.getTagKeys();
} else {
options.key = this.segments[index - 2].value;
promise = ds.getTagValues(options);
}
```

Since no query arguments are passed to `getTagKeys()` or `getTagValues()`, I need to do a search for `*` on my datasource, despite the user having typed a few matching characters. This could result in 1000+ results.

**Comment by wernerdaehn** [comment]
Oh yes, that is a big issue at the moment!

**Comment by wernerdaehn** [comment]
It is quite funny to have an api like getTagKeys(options) where options is empty always.

**Comment by wernerdaehn** [comment]
Actually, it is worse. A true bug in my point of view, not an enhancement.

If you type 10 chars in the adhoc filter variable, this api gets called ten times with the same input is short succession.

**Comment by andig** [comment]
This is happening here to be precise: https://github.com/grafana/grafana/blob/83da3660da163129a61f0d77927e263de9c4224f/public/app/features/dashboard/components/AdHocFilters/AdHocFiltersCtrl.ts#L51

**Comment by wernerdaehn** [comment]
@andig I don't have Grafana as a dev environment at hand. Do you mind stepping in?

**Comment by daniellee** [comment]
This has since been ported from Angular to React so I don't think this bug exists anymore. I can re-open if it is still an issue.

https://github.com/grafana/grafana/blob/master/public/app/features/explore/AdHocFilterField.tsx#L101

**Comment by seanlaff** [comment]
> This has since been ported from Angular to React so I don't think this bug exists anymore. I can re-open if it is still an issue.
> 
> https://github.com/grafana/grafana/blob/master/public/app/features/explore/AdHocFilterField.tsx#L101

@daniellee I believe that is passing the `key` in the `key-value` pair, not the partially written string/hint of the textbox. Is the partial string available in `extendedOptions` in `loadTagKeys()/loadTagValues()`? If not I think this is still an issue
