### ISSUE TITLE
Support adhoc filters in other template variable definitions

### ISSUE THREAD

**Issue by daldoyle** [grafana/grafana#10668]
When defining an adhoc template variable, it appears to only be applied to the metrics request and not to any other template requests. It would be useful if the key/values could be applied to other template variables as well. 

In Elastic this might take the form of:
{"find": "terms", "field": "my_field", "query": "$adhocfilter"}

The use case here is trying to implement a rough "search" approximation in grafana using adhoc filters and then having the remaining filters respond to that to select actual entities to show. If there is a better way to go about this I would be happy to learn, too.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
