### ISSUE TITLE
Create Annotation API needs to validate timestamp for milliseconds

### ISSUE THREAD

**Issue by rrusso1982** [grafana/grafana#10664]
In grafana 4.6.3 when you use the annotation API to create an annotation it does not validate that the timestamps passed into the API are in milliseconds.  I was originally passing in a timestamp in seconds and this results in a successful message but no annotation being created.

JSON sent to API: 
{"text": "test standard", "tags": ["test"], "time": 1517236732}

Result Message:
{"message":"Annotation added"}

Actual Result was that no annotation was added to the DB.

**Comment by torkelo** [comment]
Not sure that is true, it is added. at least when I test in master/v5. 

{
    "id": 4685,
    "message": "Annotation added"
}

**Comment by torkelo** [comment]
we added id in response in v5
