### ISSUE TITLE
View for assigned permissions per team and per user.

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#10660]
1. On the team page, add a section with all the specific permissions (dashboard and dashboard folder) assigned to that team.
2. Create an org user page and add a section with all the specific permissions (dashboard and dashboard folder) assigned to that user as well as a section showing the teams the user belongs to.

**Comment by MachEleven** [comment]
It would also be nice that any team member can see the user names of the other members which belong to the same team. It's good to know who you're collaborating with.

**Comment by Ijin08** [comment]
A mockup of what a org user page could like:
![org_user_mockup](https://user-images.githubusercontent.com/23470681/35973945-931ad126-0cd7-11e8-9bed-b6445a703c73.png)

**Comment by bergquist** [comment]
This would be great. Lets hope we have more time for this after 6.0.
Would be sweet if we could list any kind of permissions as well since we might add more in the future.
