### ISSUE TITLE
Grafana 5.0: modal for adding permissions

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#10676]
Currently, the interaction for creating a permissions is:

1. Create dashboard permission with the View permission (which is default)
2. Change the newly created permission to be Editor (for example)

This means that two calls are made to the database. This could be avoided (and would be more user friendly) with a modal where the user can both choose the permission type and permission (e.g. User with permission Edit).

- [ ] Create a popover modal component in React
- [ ] Replace existing component with new popover component in the Permissions component

![image](https://user-images.githubusercontent.com/434655/35555874-e1e73bb6-05a0-11e8-87b7-bdc7273b2e36.png)

Ref #10275

**Comment by mattttt** [comment]
this was one of the original variants, and might be much nicer. The main issue is disabling the Add button, which is a bit of a strange pattern: 

![image](https://user-images.githubusercontent.com/2886187/35569074-0e5cfef4-0599-11e8-9774-bf1853523641.png)
