### ISSUE TITLE
The panels are not updated after changing the settings of repeat

### ISSUE THREAD

**Issue by ilgizar** [grafana/grafana#10674]
1. Add variable var1 [ser1,ser2,ser3]
2. Select two values
3. Add panel with title $var1
4. Back to dashboard. Panel named "ser1 + ser2" - ok.
5. Edit panel and set repeat for each value of var1
6. Back to dashboard. Panel named "ser1 + ser2" - **failed**. I had to see two panels with names ser1 and ser2.
7. Select third value of valiable and panels reproduce.
8. If you remove the repeat, then the clones remain on the panel until you change the value of the variable.

**Comment by torkelo** [comment]
repeats are only processed after you change the variable value (or reload the dashboard)
