### ISSUE TITLE
can I make a reference on a panel defined on another dashboard

### ISSUE THREAD

**Issue by berserk24** [grafana/grafana#10678]
Hello!
I have many dashboards. I have panels repeated in several dashboards.
I would like create new dashboard and use refer to some existing panel in some dashboard.
I would like use panels and dashboards like objects for create new dashboards.
I would like changed panel in one place and it changing everywhere.

**Comment by torkelo** [comment]
there is already a feature request to reuse panels across dashboards, so closing this
