### ISSUE TITLE
"Editor role" can't create and save dashboard in Grafana 5

### ISSUE THREAD

**Issue by MachEleven** [grafana/grafana#10671]
- What Grafana version are you using?
grafana_5.0.0-11441pre1_amd64.deb 
- What datasource are you using?
influxdb 1.4.2
- What OS are you running grafana on?
Ubuntu 16.04.3 LTS
- What did you do?
I logged into Grafana as a user with "editor" role. I created a dashboard with a graph panel. I tried to save the dashboard.
- What was the expected result?
A user with an "editor" role can create and save a dashboard.
- What happened instead?
When I try to save the newly created dashboard, I received an error "! Access denied to this dashboard". When I log in with an admin user, I can create and save a dashboard.

**Comment by torkelo** [comment]
thanks for reporting this
