### ISSUE TITLE
how to set width of row in Grapa panel? 

### ISSUE THREAD

**Issue by szediktam** [grafana/grafana#10687]
Graph panel has a var "span" to set the panel width in columns.
How to set the width in rows with a min or max width, when the panel has many rows.

**Comment by szediktam** [comment]
@alexanderzobnin  @torkelo  Thank you for your time.

**Comment by torkelo** [comment]
> How to set the width in rows with a min or max width, when the panel has many rows

Sorry do not understand this question. rows do not have width, they are full width. 

In next version v5 rows will no longer be needed (only there for backward compatibilty), https://www.youtube.com/watch?v=BC_YRNpqj5k

**Comment by szediktam** [comment]
![screenshot from 2018-01-31 17-24-42](https://user-images.githubusercontent.com/6055078/35614951-b2440a04-06ab-11e8-8769-f1d6f1a2778c.png)

in this graph panel, there ars two rows ,ip_public and ip_rivate. ip_public has no context, so the ip_public and ip_private are overlapped. And is there a ver set a width for each row to keep context fit?
