### ISSUE TITLE
Add Hungarian `Ft` currency

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#10685]
See http://www.xe.com/symbols.php for currency symbols reference

Usage of the Hungary Forint of the value is 65123

* International format: `65123 HUF`
* Local format: `65 123 Ft`

Thank you!

**Comment by sanchomuzax** [comment]
@CLAassistant Please, confirm it. I can't add PR. Thank you!

**Comment by sanchomuzax** [comment]
What is the next step?

**Comment by marefr** [comment]
@sanchomuzax have you tried to open a PR?

**Comment by sanchomuzax** [comment]
Unfortunately, I don't know how to do this.

**Comment by marefr** [comment]
Core Grafana team haven't currently this on our roadmap so either you have to contribute yourself if you're eager to get his feature implemented or either wait for some other contributor.

Maybe the following links can help you get started contributing:
* https://help.github.com/en/articles/creating-a-pull-request
* https://www.youtube.com/watch?v=qPVrkv_s_Bc&feature=youtu.be

To implement this you'll need to add a new format to the categories.ts file:
https://github.com/grafana/grafana/blob/23d461af1395492227312d4826a3b60def9ab471/packages/grafana-ui/src/utils/valueFormats/categories.ts#L98-L115

**Comment by sanchomuzax** [comment]
Sorry, I'm not a developer, only a data analyst. I haven't used such development features yet as "pull request". :(

**Comment by ryantxu** [comment]
In 6.6 (the next release) you can just type: `currency:Ft` in the unit box
