### ISSUE TITLE
[Feature Request] Force slug in new dashboard

### ISSUE THREAD

**Issue by schmurfy** [grafana/grafana#10688]
I am using grafana 1.4.2 and the auto generated slug really is a pain when the dashboards themselves are generated, I would prefer using my internal identifiers but I cannot since doing so imply that the title will be the identifier too :(

Would you accept a pull request to allow passing the slug when creating/updating a dashboard ?
If no slug is provided the current behavior holds and if a slug is passed it is used, how does that sound ?

**Comment by torkelo** [comment]
In Grafana v5.0 we are introducing a new 9-12 char long unqiue id for dashboards (that will be used in the url as well) so the title slug is only there for URL readability

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/7883#issuecomment-361247921

**Comment by torkelo** [comment]
Oh and this new uid can be set in the dashboard model before first save so it's not an id that needs to be generated by grafana server so it's something you can control.

**Comment by schmurfy** [comment]
Thanks, I am not sure it really serve my purpose though, what I would like to have is this: `/dashboard/db/COMPANY004007`, from what I understand the url will also include the auto generated slug, right ? and why limit the uid to 12 characters ?

**Comment by marefr** [comment]
We will actually allow the uid to be 40 characters. In your case in v5.0 you'll get a url of `/d/COMPANY004007/<slug of dashboard title>` where the slug of dashboard title is only used for human-readable urls and the uid is used for retrieving the dashboard.
