### ISSUE TITLE
Have Grafana running in background or make api call to display graph?

### ISSUE THREAD

**Issue by jenhogan** [grafana/grafana#10682]
I have a graph embedded in my web app that only shows up when Grafana is running. 
I know grafana is running locally, but is there way to have the graphs still show up using a grafana api call or something? Or to run grafana in the background without having to launch localhost?

**Comment by torkelo** [comment]
please use community site for questions. There is a graph render api you can use to get images from panels , example http://play.grafana.org/render/dashboard-solo/db/graph-styles?orgId=1&from=1517324782173&to=1517328382173&panelId=3&width=1000&height=500&tz=UTC%2B01%3A00
