### ISSUE TITLE
docs: Pages link to outdated 'provisioning' page

### ISSUE THREAD

**Issue by fhemberger** [grafana/grafana#10691]
I noticed an issue with the provisioning docs, coming from a Google search:

- `docs/sources/index.md` still links to `installation/provisioning` instead of `/administration/provisioning#configuration-management-tools`. (PR: #10690)
- `installation/provisioning` has been removed from the master branch and thus should be removed from the server as well, redirecting to `/administration/provisioning#configuration-management-tools` instead.
- `installation/provisioning` still links to an outdated Ansible role (PR: #10689)

**Comment by fhemberger** [comment]
@torkelo Please reopen, http://docs.grafana.org/installation/provisioning/ is still on the server and appears on Google searches. Should send a 301 redirect to http://docs.grafana.org//administration/provisioning#configuration-management-tools instead.

**Comment by torkelo** [comment]
pushed new version now, should be fixed soon

**Comment by fhemberger** [comment]
Thanks! :+1:

**Comment by fhemberger** [comment]
@torkelo Just noticed the same issues in v5.0 docs.

**Comment by torkelo** [comment]
yea, it will be fixed on next merge from master to v5_docs branch

**Comment by fhemberger** [comment]
Ah, ok. Wasn't sure if I selected the right branch for the PR … thanks!
