### ISSUE TITLE
Zoom on a graph leads to a jump to the top of the dashboard

### ISSUE THREAD

**Issue by Farfaday** [grafana/grafana#10696]
Hi,

I tested today **master** from https://hub.docker.com/r/grafana/grafana/tags/
When zooming with the cursor on a graph located at the bottom of a big dashboard, the page jumps back to the top of the board. This forces the user to scroll back down to the graph he was looking at.

Many thanks for the good job!

François

**Comment by torkelo** [comment]
thanks for reporting this, will fix asap!
