### ISSUE TITLE
Proxy backend doesn't forward query params

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#10698]
I'm using the latest stable with ClickHouse datasource

![image](https://user-images.githubusercontent.com/327717/35632596-60a25b82-06a7-11e8-8fd6-16aa384c0ef9.png)

Using access mode `proxy` doesn't forward query part of url:

https://url/grafana/api/datasources/proxy/1/?query=SELECT%201%20FORMAT%20JSON&add_http_cors_header=1

Returns `Ok.` With ClickHouse, that means that `https://clickhouse.url/` has been accessed instead of `https://clickhouse.url/?query=SELECT 1 FORMAT JSON&add_http_cors_header=1`, that would have returned

```
{
	"meta":
	[
		{
			"name": "1",
			"type": "UInt8"
		}
	],

	"data":
	[
		{
			"1": 1
		}
	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 0.000063939,
		"rows_read": 1,
		"bytes_read": 1
	}
}
```

So when calling this https://url/grafana/api/datasources/proxy/1/?query=SELECT%201%20FORMAT%20JSON&add_http_cors_header=1, this gets actually called https://url/grafana/api/datasources/proxy/1/

**Comment by torkelo** [comment]
please ask the ClickHouse developers, the proxy does proxy the complete request (including params) so must be something strange with the data source or your setup.
