### ISSUE TITLE
Grafana authproxy whitelists the client ip instead of the reverse proxy ip

### ISSUE THREAD

**Issue by samaust** [grafana/grafana#10707]
**My understanding of the authproxy whitelist setting**

First, let’s make sure I understand how the whitelist setting is meant to work. For security purposes, if the whitelist is set, Grafana should only authenticate a user using the X-WEBAUTH-USER header if the request passed through the reverse proxy that's configured to handle the authentication. The whitelist setting is there to prevent Grafana from authenticating a user if the request did not pass through the reverse proxy that's configured to handle the authentication.

If my understanding is incorrect and whitelist is meant to whitelist a client ip, the documentation needs to be improved because it's not obvious that this is the goal.

**My setup**

Grafana version : 4.6.2
OS : Debian Stretch

My setup uses HAProxy reverse proxy, then Apache reverse proxy then Grafana. HAProxy is on server A. Apache and Grafana are on server B. Apache is used to host an authentication frontend that authenticates the user into Grafana using Grafana authproxy.

The Grafana authentication works when I leave the whitelist config option in auth.proxy blank.

The Grafana authentication fails when I add the Apache server ip to the whitelist. I get the error “Request for user (usename) is not from the authentication proxy” from :
https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy.go#L138

The expected result is that the authentication succeeds after the whitelist check.

**Analysis**

Looking at the code, the whitelist check is only done if there’s at least one ip set in the config file. It’s skipped if the whitelist config is blank. That works as intended.

The check compares the source ip to all the ips in the whitelist config. The check is successful if at least one the two ip are equals.

I think there’s an issue with the code that gets the source ip. Let’s look at the code.

```
remoteAddrSplit := strings.Split(ctx.Req.RemoteAddr, ":")
sourceIP := remoteAddrSplit[0]
```

If I’m not mistaken, ctx.Req.RemoteAddr is from :
https://github.com/go-macaron/macaron/blob/master/context.go#L140

The code is :

```
// RemoteAddr returns more real IP address.
func (ctx *Context) RemoteAddr() string {
	addr := ctx.Req.Header.Get("X-Real-IP")
	if len(addr) == 0 {
		addr = ctx.Req.Header.Get("X-Forwarded-For")
		if addr == "" {
			addr = ctx.Req.RemoteAddr
			if i := strings.LastIndex(addr, ":"); i > -1 {
				addr = addr[:i]
			}
		}
	}
	return addr
}
```

The ip comes from X-Real-IP or X-Forwarded-For header. In my case it comes from X-Forwarded-For.
I’ve got two reverse proxy in front of Grafana so X-Forwarded-For looks like :
"pc_connecting_to_grafana_ip, server_A_ip, server_B_ip".

That’s what’s supposed to happen (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For). The first ip is the client, the second the first proxy and the third the second proxy.

`sourceIP` contains the result of indexing `remoteAddrSplit` at index 0, so it contains the client ip. It should instead use the last index to contain the last reverse proxy server ip.

Also, the client could spoof/manipulate the X-Forwarded-For and add any ip he wants to the beginning of the string.

If someone has access to your local network, they could just spoof the whole X-Forwarded-For header. In that case, it would be better to look at the connection ip to see if it's coming from the reverse proxy right in front of Grafana.

**Comment by torkelo** [comment]
> Also, the client could spoof/manipulate the X-Forwarded-For and add any ip he wants to the beginning of the string.

That needs to protected for by the reverse proxy.

But your right looks like for this Grafana should look at the second IP. Strange that no one else has reported this.

**Comment by corny** [comment]
```golang
remoteAddrSplit := strings.Split(ctx.Req.RemoteAddr, ":")
sourceIP := remoteAddrSplit[0]
```
How is this supposed to work with IPv6? Does ist only work with legacy IP?

**Comment by corny** [comment]
> If I’m not mistaken, ctx.Req.RemoteAddr is from :
> https://github.com/go-macaron/macaron/blob/master/context.go#L140

If i'm not wrong:
`ctx.Req` is a `*http.Request`. `(ctx *Context) RemoteAddr()` is only used for logging.

**Comment by marefr** [comment]
@samaust I've opened a PR to fix this. In my mind the only thing we need to do is to use macaron function RemoteAddr() to get the last ip. Please try it out if possible.

**Comment by marefr** [comment]
I was a bit too fast there. Will need to add some more code to handle this

**Comment by marefr** [comment]
@samaust now it should be all set. Please try out the PR branch if possible.

**Comment by samaust** [comment]
@marefr Thank you for the PR. I tested it and it works.

**Comment by hc4** [comment]
This fix broken my setup.
I have only squid3 as a reverse proxy.
With this fix Grafana tries to validate client's IP, instead of reverse proxy's IP.

I looked docs and can't understand this fix.
prev. version used ctx.Req.RemoteAddr to validate IP - and it is coorect, because ctx.Req.RemoteAddr just returned network addres of server, from wich request received.

now it uses ctx.RemoteAddr(), which tries to parse client's IP from request headers, which is incorrect.

**Comment by marefr** [comment]
@hc4 if your proxy isn't adding X-Real-IP or X-Forwarded-For headers then ctx.RemoteAddr() are using the ctx.Req.RemoteAddr. See https://github.com/go-macaron/macaron/blob/master/context.go#L146

**Comment by hc4** [comment]
My proxy adds X-Forwarded-For, because I want to monitor real user IP.
Actually I can't get purpose of this fix,
Proxy whitelist needed only to verify, thed USER tag received from reverse proxy and not from any other server. There is no sense in validating IP in X-Forwarded-For

**Comment by marefr** [comment]
Well yes because the IP of your proxy should be at the end of X-Forwarded-For and the client ip (real ip) at the beginning of the X-Forwarded-For. When you're whitelist an IP address you're saying that the IP of this proxy is trusted and expected.

I don't understand how you've configured this - Are you whitelisting client IP (real end user) addresses?

**Comment by hc4** [comment]
Wiki [says](https://en.wikipedia.org/wiki/X-Forwarded-For): Since it is easy to forge an X-Forwarded-For field the given information should be used with care. **The last IP address is always the IP address that connects to the last proxy**, which means it is the most reliable source of information. X-Forwarded-For data can be used in a forward or reverse proxy scenario.

**Comment by marefr** [comment]
I'm under the impression that the IP address of squid proxy should be included at the end of X-Forwarded-For.

**Comment by hc4** [comment]
> I'm under the impression that the IP address of squid proxy should be included at the end of X-Forwarded-For.
Wiki says you're wrong :)

Anyway, you **must** check actual IP, from which request was received. Otherwise spoofer can format any X.forwarded-for tag and hack your server.

**Comment by marefr** [comment]
I read the link referenced above, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For and it clearly states that all proxies a request pass are included in the X-Forwarded-For.

Now I'm confused. When looking at it now the original `ctx.Req.RemoteAddr` should contain `<IP address>:<port>`. Don't understand why it didn't work for @samaust but I think we need to revert this fix. 

Thank you @hc4

**Comment by hc4** [comment]
Mozilla dev page looks like cutted version from wiki.

Full version is:
> The general format of the field is:
X-Forwarded-For: client, proxy1, proxy2
where the value is a comma+space separated list of IP addresses, the left-most being the original client, and **each successive proxy that passed the request adding the IP address where it received the request from**. In this example, the request passed through proxy1, proxy2, **and then proxy3 (not shown in the header)**. proxy3 appears as remote address of the request.

**Comment by marefr** [comment]
Have opened a PR to revert #12299 

Reading original description. 

> HAProxy is on server A. Apache and Grafana are on server B

I guess that `ctx.Req.RemoteAddr` not returns the IP address of the machine since they're on the same machine and instead returns empty address/localhost/127.0.0.1 or something like that.

**Comment by hc4** [comment]
I have squid and grafana on same server.
Squid listens 3000 port on public ip
Grafana listens 127.0.0.1:3000
And everything worked fine, until this fix

**Comment by marefr** [comment]
@samaust we've reverted #12299

We've confirmed that this issue wasn't an actual issue - it worked as expected before. Please have a look at how you've configured your whitelists.

**Comment by towolf** [comment]
@marefr thanks for reverting. I was affected by the wrong fix as well. We have Apache with custom SSO module on localhost and I actually had to comment out the whitelist to make 5.2.0 work.

**Comment by marefr** [comment]
@towolf okay. There's a v5.2.1 release out now which includes the revert

**Comment by samaust** [comment]
You can keep this issue closed. Sorry about all that. It was a configuration mistake on my part. I'll explain.

As @marefr said

> I guess that ctx.Req.RemoteAddr not returns the IP address of the machine since they're on the same machine and instead returns empty address/localhost/127.0.0.1 or something like that.

That's correct. The ip check is started by 

`if err := checkAuthenticationProxy(ctx.Req.RemoteAddr, proxyHeaderValue); err != nil {`

In my case, ctx.Req.RemoteAddr returns "::1" which is the localhost IPv6 address. I don't know why it does not return an IPv4 address such as "127.0.0.1", that would make more sense to me.

Apart from that, @corny was right when he said

> ctx.Req is a *http.Request. (ctx *Context) RemoteAddr() is only used for logging.

The ip check uses the ip returned by `ctx.Req.RemoteAddr`. While the pkg\middleware\logger.go Logger function calls `c.RemoteAddr()` to log the ip. `ctx.Req.RemoteAddr` returns a single ip address from the request, in my case the localhost ::1 address. `c.RemoteAddr()` from the package macaron.v1 returns the string from X-Forwarded-For, which contains the cliend ip address and the first proxy server ip address.

As @hc4 said, the X-Forwarded-For does not contain the ip address of the second proxy server. Instead, that ip is located in the request.

**Comment by katmai** [comment]
is there any chance this one is still causing issues? i am trying to whitelist grafana access from a reverse proxy as well and it looks like it's doing the same thing:

t=2018-09-04T08:15:21-0400 lvl=eror msg="Proxy authentication required" logger=context error="Request for user (mark) from 1.1.1.1 is not from the authentication proxy"
t=2018-09-04T08:15:21-0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/users status=407 remote_addr=2.2.2.2 time_ms=1 size=1715 referer=
t=2018-09-04T08:23:30-0400 lvl=eror msg="Proxy authentication required" logger=context error="Request for user (mark) from 1.1.1.1 is not from the authentication proxy"
t=2018-09-04T08:23:30-0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/users status=407 remote_addr=2.2.2.2 time_ms=1 size=1715 referer=
t=2018-09-04T08:31:33-0400 lvl=eror msg="Proxy authentication required" logger=context error="Request for user (mark) from 1.1.1.1 is not from the authentication proxy"
t=2018-09-04T08:31:33-0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/users status=407 remote_addr=2.2.2.2 time_ms=1 size=1715 referer=

**Comment by katmai** [comment]
i am on grafana 5.2.2: ii  grafana                          5.2.2

**Comment by Mahender-224** [comment]
i'm using a grafana v6.2 , when i try to show the grafana graph in my html page , it is saying "127.0.0.1 refused to connect" . how can i solve the problem

**Comment by Mahender-224** [comment]
how can i solve the problem >127.0.0.1 refused to connect" when i try to show the grafana graph in html

**Comment by marefr** [comment]
@Mahender-224 is this really related to this issue? Are you using auth proxy with whitelisted ip addreses? If not, please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
