### ISSUE TITLE
Display MySQL data including backspaces in datatable

### ISSUE THREAD

**Issue by ZoeThivet** [grafana/grafana#10708]
- What Grafana version are you using?
**4.6.3**
- What datasource are you using?
**MySQL**
- What OS are you running grafana on?
**Ubuntu 14**
- What did you do?
**Created a datatable**
- What was the expected result?
**Display MySQL data including backspaces**
_Navigateur ouvert.
Timeout configuré à 15 secondes.
Début du test : 1517457041111_
**This is how I see the data in phpmyadmin**
- What happened instead?
**Display  MySQL data without backspaces**
- Include raw network request & response
**"Navigateur ouvert.Timeout configuré à 15 secondes.Début du test : 1517446519923" (got this from the inspector)**

I also tried editing my data, including \n, \\\n or \<br>, with no success.

Thanks in advance for the help

**Comment by torkelo** [comment]
add a column style for your text column and set type to String and check preserve formatting,

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/35667038-7477a524-072c-11e8-9549-9a04cd33a189.png)
