### ISSUE TITLE
Grafana 5.0: dashboard permissions in dashboard settings are incorrect when folder is changed and dashboard not saved.

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#10703]
The dashboard settings page should disable the permissions edit view if the dashboard has been moved to another folder via dashboard settings. Otherwise the user is looking at a stale permission list with inherited permissions from the original folder.

**Comment by marefr** [comment]
@daniellee Hmm, isn't this already fixed. Just tried it and got the text "You have changed folder, please save to view permissions." on the permission tab after changed folder under settings.
