### ISSUE TITLE
Showback/remediation of alert notification failures

### ISSUE THREAD

**Issue by mlamanuzzi** [grafana/grafana#10709]
Running Grafana 4.4.3 on Centos 7.2.1511

In regards to the alert engine:

After alert rules are evaluated, and a condition is met, the annotation table is updated and any applicable notifiers are invoked. However, in the result handler, there is no check to see if any error was encountered when attempting to send the notification.

Perhaps there could be another column in the alerts table indicating whether or not the notification was successful, and there could be another mechanism to re-send any failed notifications. This of course might become problematic if there are continual failures.

At the very least the annotation should perhaps include information about the failed notification.

Does anyone else have any thoughts around this topic?

**Comment by ItshakEli** [comment]
Another detail:

Table Transform: Json Data

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
