### ISSUE TITLE
Use innodb in sessions example in documentation 

### ISSUE THREAD

**Issue by alexillsley** [grafana/grafana#10713]
Where mysql is used for sessions, the documentation has an example to create a table to store them with MyISAM engine. http://docs.grafana.org/installation/configuration/#session

I suggest this is changed to InnoDB engine. If MySQL has strict mode enabled and use MyISAM engine you will get this error and be unable to login;

lvl=eror msg="Failed to start session" logger=context error="Error 1105: Percona-XtraDB-Cluster prohibits use of DML command on a table (grafana.session) that resides in non-transactional storage engine with pxc_strict_mode = ENFORCING or MASTER"

**Comment by torkelo** [comment]
that documentation is outdated, grafana will automatically create session table, will remove docs
