### ISSUE TITLE
[Feature request] Add stack/unstack toggle to panel menu

### ISSUE THREAD

**Issue by jacekn** [grafana/grafana#10714]
Please include this information:
- What Grafana version are you using? 4.6.3
- What datasource are you using? Prometheus
- What OS are you running grafana on? Ubuntu 16.04

Currently if I want to switch between stacked and unstacked mode for graph panel I have to edit the panel and toggle "stacked" box there.
It would be useful to have stack/unstack toggle next to each panel for easy way to change mode.

Justification:
 *  both stacked and unstacked modes have advantages and often neither is clearly better than the other
 * sometimes it's not clear whether lines are stacked or not, I need to add "stacked/unstacked" to panel title
 * ability to quickly toggle mode would save some users from creating duplicated panels
 * it would allow anonymous users to switch panel mode. Currently only logged in users have this ability

I think implementation could be similar to one for https://github.com/grafana/grafana/issues/9722

**Comment by torkelo** [comment]
will need to be added to the panel menu, so you can click on the panel title then toggle stack from there.

**Comment by AntoineThebaud** [comment]
I like this feature on the Prometheus UI, it would be great to have it on Grafana also.

To (try to) improve the proposal made in the rejected PR https://github.com/grafana/grafana/pull/15885 , maybe the 'Toggle stacking' option added here could be shown/hidden based on a new parameter that would be available under Panel Edit > Visualization > Stacking & Null value like the following : 

![alt text](https://i.imgur.com/2gOcfKb.png)

This to avoid having too much corner-cases option displayed all the time.

WDYT ?

**Comment by rafaelpirolla** [comment]
Isn't there any way to create a template variable and use it in the stacking JSON Model?
```
{
        "current": {
          "selected": true,
          "text": "Off",
          "value": "normal"
        },
        "hide": 0,
        "includeAll": false,
        "label": "Stacked",
        "multi": false,
        "name": "stacking",
        "options": [
          {
            "selected": true,
            "text": "Off",
            "value": "normal"
          },
          {
            "selected": false,
            "text": "On",
            "value": "none"
          }
        ],
        "query": "Off : normal, On : none",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
```

And then:
```
"stacking": {
              "group": "A",
              "mode": "${stacking}"
            },
```
