### ISSUE TITLE
Tooltips broken for heatmap when using time series bucket

### ISSUE THREAD

**Issue by thattolleyguy** [grafana/grafana#10724]
I know this has been addressed in #9332 but I'm still able to reproduce it.

I've been debugging and think I've found the issue. First, I'm using time series buckets and that's what makes it fail. It looks like when we get the x bucket index from the mouse position, the data bucket doesn't line up exactly with how the getBucketBound method works. For example, if my buckets are 30 seconds apart then the getBucketBound method will return values that fall on exactly 0 and 30 second marks every minute. However if my buckets are on the 5 and 35 second mark of every minute then we can't find a bucket for the position. I'm not a js expert but I'll try and commit a fix when I get a chance. If anyone else thinks it's an easy fix, feel free to fix it!

**Comment by thattolleyguy** [comment]
Another issue I found is with the y bucket scaling. I have buckets for .25, .5, 1, 2, 4, 12, 18, 24, 48 hours and I'm trying to graph it with a log 2 scale. The buckets that don't fall exactly on the power of 2 scaling don't get tooltips (12,18,24,48).

**Comment by daniellee** [comment]
@thattolleyguy yes, a PR to master would be best.

cc @alexanderzobnin can you take a look at this?

**Comment by alexanderzobnin** [comment]
Fixed by #10742
