### ISSUE TITLE
Ldap Auth: user does not belong in any of the specified ldap groups

### ISSUE THREAD

**Issue by nskalis** [grafana/grafana#10721]
Read before posting: 

Please include this information:
- What Grafana version are you using?
```
v4.6.3 (commit: 7a06a47)
```

- What OS are you running grafana on?
```
Static hostname: xxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: fedaac08342a8cbe1b2e01c6c42019da
           Boot ID: 7686ef6b444d495d8dfd489847a71dee
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.21.1.el7.x86_64
      Architecture: x86-64
```

- What did you do?
```
host = "xxx"
port = 636
use_ssl = true
root_ca_cert = "xxx.pem"
bind_dn = "uid=xxx,ou=xxx,dc=xxx,dc=xxx"
bind_password = "xxx"

search_filter = "(uid=%s)"
group_search_filter = "(&(objectClass=posixGroup)(member=%s))" 
group_search_base_dns = ['ou=xxx,ou=xxx,ou=xxx,dc=xxx,dc=xxx']

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "cn" 
email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=grafana,ou=xxx,ou=xxx,ou=xxx,dc=xxx,dc=xxx"
org_role = "Admin"
```

- What was the expected result?

The problem seems to be that:
`group_search_filter = "(&(objectClass=posixGroup)(member=%s))”`
and %s must be the full DN of the user that is a member e.g. (I am a member of the `grafana` group)

`%s = uid=nskalis,ou=xxx,dc=xxx,dc=xxx `
And not just `nskalis` - the group stores DN’s of members in the member attribute.
In other words, here

`t=2018-01-19T12:40:15+0100 lvl=info msg="Searching for user's groups" logger=ldap filter="(&(objectClass=posixGroup)(member=nskalis))"`

**Eventually %s needs to be replaced with something that represents the users DN**

- What happened instead?
```
t=2018-01-19T12:40:06+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=xxx time_ms=1 size=29 referer=
t=2018-01-19T12:40:15+0100 lvl=info msg="Searching for user's groups" logger=ldap filter="(&(objectClass=posixGroup)(member=nskalis))"
t=2018-01-19T12:40:15+0100 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc4201d0f50)({\n DN: (string) (len=35) \"uid=nskalis,ou=xxx,dc=xxx,dc=xxx\",\n FirstName: (string) (len=5) \"Nikos\",\n LastName: (string) (len=6) \"Skalis\",\n Username: (string) (len=7) \"nskalis\",\n Email: (string) (len=25) \"xxx@xxx\",\n MemberOf: ([]string) <nil>\n})\n"
t=2018-01-19T12:40:15+0100 lvl=info msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=nskalis groups=[]
t=2018-01-19T12:40:15+0100 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2018-01-19T12:40:15+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=xxx time_ms=128 size=42 referer=http://xxx/login
```

**Comment by drix1994** [comment]
If I can, I'll join to problem with a similar problem.
My conf:

> bind_dn = "%s@simple.domain.ldap"
> search_filter = "(sAMAccountName=%s)"
> search_base_dns = ["DC=zz,DC=xx,DC=cc,DC=vv"]
------
> Atributtes:
> [servers.attributes]
> name = "givenName"
> surname = "sn"
> username = "cn"
> member_of = "manager"   -- it contains info about group in LDAP
> email =  "mail"

My definition of group:
> [[servers.group_mappings]]
> group_dn = "CN=zz,OU=xx,OU=cc,OU=vvvvvL,DC=bb,DC=nn,DC=nnnn,DC=mmmmmm"
> org_role = "Viewer"
> org_id = 1

Response from log. Something is wrong, because for test, I wrote definistions the same as ldap group info recevied from log:
> t=2018-02-02T11:26:47+0100 lvl=info msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=pyzikdar groups="[CN=zz,OU=xx,OU=cc,OU=vvvvvL,DC=bb,DC=nn,DC=nnnn,DC=mmmmmm]"
> t=2018-02-02T11:26:47+0100 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
> t=2018-02-02T11:26:47+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=126.84.84.167 time_ms=67 size=42 referer=http://kpiviewer.corpnet.pl:8080/login

Without difinition ldap group Im connetting properly and I can log in. Can I please for help without open new issue? My Grafana verson is the same as above and it runs on redhat. 
Grettings and thaks !

**Comment by nilan3** [comment]
+1

**Comment by ptselios-inmarsat** [comment]
I have a similar problem. 
But in my case, I have Grafana 5.3.4.
You can change the filter. I use FreeIPA/IdM and the search filter I use is this: 

`(&(objectClass=posixGroup)(member=uid=%s,cn=users,cn=accounts,dc=example,dc=com))`

Although I don't get the "user does not belong in any of the specified ldap groups" error, the groups are empty. 
I am strongly suspecting a bug in the code and the way it handles group membership.
