### ISSUE TITLE
Integrating Grafana in to angularjs application with auto login and get user specific dashboard?

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#10728]
I want to integrate grafana into my angularjs web application for monitoring purpose. I want something through which I can redirect to grafana dashboard with credentials by surpassing the grafana login page , means direct dashboard page should be displayed of logged in user of grafana. 

Grafana Team How to Do this Give me guidance..

Thanks!!!.....

**Comment by daniellee** [comment]
This is not a scenario that we are going to spend time on trying to support.

These links might help you:
- https://community.grafana.com/t/embed-grafana-dashboard-in-web-application/3142
- https://github.com/grafana/grafana/issues/4136
- https://stackoverflow.com/questions/35583712/embedding-a-secured-grafana-into-web-application

**Comment by nttoan26** [comment]
hi @daniellee , I believe you could guide @vishuPPatel to use Grafana's AuthProxy to handle authentication
