### ISSUE TITLE
Penultimate value singlestat (position [current -1])

### ISSUE THREAD

**Issue by guillelb** [grafana/grafana#10723]
Grafana: 4.6.3
Datasource: Graphite

I am running an app which is continuously collecting data and writting in graphite, and a singlestat gauge showing the latest value (current).
It works perfectly, but sometimes grafana reads the value of the last datapoint before of it has written completely, and the singlestat gauge shows an incorrect value until the next refresh.

How can I show the penultimate value (last-1 datapoint) instead the current value. It would solve my problem.

**Comment by daniellee** [comment]
In future, can you ask questions on the community site. Thanks.

Maybe the Graphite [timeshift](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.timeShift) function would work in your case?
