### ISSUE TITLE
Save dashboard as new in other folder

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#10720]
It should be possible to save a copy of a dashboard (using Save as...) in another folder.

**Comment by daniellee** [comment]
Is it not already?

![image](https://user-images.githubusercontent.com/434655/35703505-93bf7e1e-079c-11e8-8bbe-0c89b2a5827b.png)

**Comment by bergquist** [comment]
@daniellee we got an error when trying to save it.

**Comment by daniellee** [comment]
@bergquist Works for me on latest master (What I tried: 1. Go to dashboard settings 2. Click Save as.. button 3. Choose folder in modal 4. Click Save). What's the error you are getting?

**Comment by marefr** [comment]
@daniellee the problem is with the new url structure, which is not in master yet
