### ISSUE TITLE
Cannot overwrite a dashboard/folder

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10735]
This is a bug due to implementation of #10419 

If you're importing a dashboard that have the same title as an existing folder or dashboard in the general folder and click on *Import (Overwrite)* it results in *Failed to import dashboard" error. Note that the dashboard json you're importing does not have a unique identifier (*uid*).

The same error occurs if you trying to save a dashboard with a title that already exists and you choose to overwrite.

Also, we need to make sure that saving a dashboard with a title that already exists on a folder is not possible, i.e. the conflict confirm modal *Dashboard with the same name exists.* should not be shown.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/validation_srv.ts#L28

This have to handle the new uniqueness requirements.

**Comment by marefr** [comment]
### Proposal for new logic when creating/updating a dashboard
In general, the new *uid* field are handled just like the *id* field, i.e. if a dashboard are found by uid that dashboard will be updated if current version are provided or overwrite flag are set to true.

#### Current logic
- No id with an optional uid and a title that doesn't exist in folder creates a new dashboard.
- Id allows update of existing dashboard if current version are provided or overwrite flag are set to true.
- Id with an existing title in folder allows overwrite of dashboard and the overwritten dashboard will have the same id and uid as before.

#### New logic
- No id and uid with a title that doesn't exist in folder creates a new dashboard.
- Id without uid, allows update of existing dashboard/folder if current version are provided or overwrite flag are set to true.
- Uid without id allows update of existing dashboard/folder if current version are provided or overwrite flag are set to true.
- Id without uid, with an existing title in folder allows overwrite of dashboard and overwritten dashboard will have the same id and uid.
- Uid without id, with an existing title in folder allows overwrite of dashboard and overwritten dashboard will have the provided uid and the same id as before.
- Ensures that changing an existing folder to a dashboard yields error.
- Ensures that changing an existing dashboard to a folder yields error.

**Comment by DBarthe** [comment]
Hi,
I'm also facing this problem while trying to update a dashboard with `"overwrite": true` within automation script.
I got a `"{\"message\":\"A dashboard with the same name in the folder already exists\",\"status\":\"name-exists\"}"`.
Actually I send the same id, but do not increment the version number.
