### ISSUE TITLE
Wrong visualization of alerts

### ISSUE THREAD

**Issue by asiekkowa** [grafana/grafana#10734]
**- What Grafana version are you using?**
 Grafana v4.6.3 (commit: 7a06a47)
**- What datasource are you using?**
graphite (gocarbon)
**- What OS are you running grafana on?**
Debian (docker)
**- What did you do?**
I had created a graph which shows used space on disc. Left Y (query A) shows metric in kilobytes, Right Y shows metric in % (query B). Then I have created an alert rule: if usage is more than 95% send error.
**- What was the expected result?**
Send error when usage of space on disk is bigger than 95%. Show correct visualization on graph.
**- What happened instead?**
Visualization of alert on graph is wrong - I mean alert line - it points on 95 KiB instead of 95% - due to this error whole background of graph is reddish. (but at least Grafana calculate alerts in correct way). 
![image](https://user-images.githubusercontent.com/22298133/35733065-2a187ad0-081c-11e8-8766-4766dd4e0700.png)
green line - query A, yellow line - query B

![image](https://user-images.githubusercontent.com/22298133/35733072-314f6476-081c-11e8-8ae0-83a5f571f857.png)

**Comment by torkelo** [comment]
The thresholds is not percent but the same unit as your metric query response data. (bytes?) 

If you want to specify percent your query needs to return percentages
