### ISSUE TITLE
New dashboard URL policy is not consistent

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10736]
Hi

With latest grafana 5.0.0 I have dashboards URLS like:

http://127.0.0.1:3000/d/uHywmhCzz/my-dashboard

But when I delete the grafana DB and reprovision from scratch the dashboards, the URL is changing.

This is a disaster and breaks the promise of having a grafana fully provisionned by files.

Proposal is to remove the uHywmhCzz and replace it by a slug of the folder.

**Comment by roidelapluie** [comment]
This is breaking for us and prevents us to upgrade.

**Comment by torkelo** [comment]
you can provide a uid string in your json dashboard. Then the URL will be the same after each provisioning. If there is no uid then Grafana will create it. 

The good thing about the uid compared to the slug is that you now can update dashboard titles without breaking links to the dashboard.

**Comment by roidelapluie** [comment]
ping @marefr about this :)

**Comment by roidelapluie** [comment]
Thank you, I did miss that. This is then excellent!!!

**Comment by torkelo** [comment]
Np. We will try to document and mention this clearly in the release notes & provisioning docs, many will run into this as well.

**Comment by bergquist** [comment]
@roidelapluie cu at FOSDEM tomorrow? :)

**Comment by roidelapluie** [comment]
@bergquist I am at CentOS dojo now and at Config Management Camp on Mon and Tues but I can not make it to fosdem as I am moving next week... :(

**Comment by bergquist** [comment]
Aight. Then we will see each other at GrafanaCon instead! :)

**Comment by roidelapluie** [comment]
At first sight I can not set a UID in the JSON with latest nightly. Will investigate further.

**Comment by roidelapluie** [comment]
Nevermind I got it working.
