### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mdeora** [grafana/grafana#10733]
t=2018-02-02T11:40:58+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:491 (0x431e62)\n/usr/local/go/src/runtime/panic.go:63 (0x430d6d)\n/usr/local/go/src/runtime/signal_unix.go:367 (0x44924b)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:490 (0xd28174)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:368 (0xd264b4)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:183 (0xd22a57)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/cloudwatch.go:73 (0xd1768d)\n/go/src/github.com/grafana/grafana/pkg/tsdb/request.go:17 (0xbb0099)\n/go/src/github.com/grafana/grafana/pkg/api/metrics.go:46 (0xde3b5e)\n/usr/local/go/src/runtime/asm_amd64.s:511 (0x461191)\n/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0xdff9cb)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)\n/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xb98243)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)\n/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xb97ac4)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)\n/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:79 (0xb985ca)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)\n/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb979e0)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x7f19c0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7d4863)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7d459a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xb95571)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)\n/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x803412)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:296 (0x7fd98b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7f6387)\n/usr/local/go/src/net/http/server.go:2619 (0x692de3)\n/usr/local/go/src/net/http/server.go:1801 (0x68f09c)\n/usr/local/go/src/runtime/asm_amd64.s:2337 (0x4638c0)\n"

When accessing the cloudwatch AWS ec2 dashboard, its crashing.

**Comment by bergquist** [comment]
What verison of Grafan are you using

**Comment by robbwagoner** [comment]
I see this same issue with Grafana v4.6.3 on Ubuntu 14.04.

```
$ head -2 /etc/os-release
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"

$ apt list installed grafana
Listing... Done
grafana/now 4.6.3 amd64 [installed,local]
```

.deb package source: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.6.3_amd64.deb

AWS EC2 dashboard via [monitoringartist aws-ec2 dashboard .json](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/master/aws-ec2/aws-ec2.json)

IAM Role policy assigned to the EC2 instance running Grafana <sup>+</sup>:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cloudwatch:GetMetricData",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics",
                "ec2:Describe*"
            ],
            "Resource": "*"
        }
    ]
}
```

<sup>+</sup> **Where is the required IAM Policy documented? I looked but couldn't find anything.**


From `/var/log/grafana/grafana.log`

```
t=2018-02-22T22:51:42+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin 
error="runtime error: invalid memory address or nil pointer dereference" 
stack="/usr/local/go/src/runtime/panic.go:491 (0x431e62)
/usr/local/go/src/runtime/panic.go:63 (0x430d6d)
/usr/local/go/src/runtime/signal_unix.go:367 (0x44924b)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:490 (0xd28174)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:368 (0xd264b4)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:183 (0xd22a57)
/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/cloudwatch.go:73 (0xd1768d)
/go/src/github.com/grafana/grafana/pkg/tsdb/request.go:17 ...
```

**Comment by mdeora** [comment]
Grafana Version 4.6.3 (commit: 7a06a47)
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"

**Comment by mdeora** [comment]
Also, I just tried creating an template ebs_volume_ids($region, $instance_id) -> throwing same error.
Though other queries like ec2_instance_attribute and dimension_values are working fine.

**Comment by VR6Pete** [comment]
I also have same issue here.

**Comment by davidjeddy** [comment]
Running into the same issue here.

Installed w/o an issue, added datasource, added dashboards; flawlessly.

Tried to access EC2 metrics:
![image](https://user-images.githubusercontent.com/6232455/36769102-357141ca-1c10-11e8-9bd9-da9edf50a318.png)

The first query errors with a 500:
```
Server side error :(
runtime error: invalid memory address or nil pointer dereference
Check the Grafana server logs for the detailed error message.
```

**Log:**
```
[ec2-user@ip-172-31-42-101 ~]$ tail -10 /var/log/grafana/grafana.log
t=2018-02-28T03:47:29+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=47.205.10.142 time_ms=125 size=34 referer="http://ec2-23-23-47-191.compute-1.amazonaws.com:3000/dashboard/db/aws-ec2?orgId=1"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=47.205.10.142 time_ms=188 size=34 referer="http://ec2-23-23-47-191.compute-1.amazonaws.com:3000/dashboard/db/aws-ec2?orgId=1"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=47.205.10.142 time_ms=188 size=34 referer="http://ec2-23-23-47-191.compute-1.amazonaws.com:3000/dashboard/db/aws-ec2?orgId=1"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=47.205.10.142 time_ms=173 size=34 referer="http://ec2-23-23-47-191.compute-1.amazonaws.com:3000/dashboard/db/aws-ec2?orgId=1"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
t=2018-02-28T03:47:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=47.205.10.142 time_ms=159 size=34 referer="http://ec2-23-23-47-191.compute-1.amazonaws.com:3000/dashboard/db/aws-ec2?orgId=1"
```

**Environment:**
Version 4.6.3 (commit: 7a06a47)
Amazon Linux

**Comment by robbwagoner** [comment]
Hi @bergquist - any ideas what's going on with this issue?

**Comment by hc1tneville** [comment]
I'm having the same issue, but I can narrow it down.  This issues shows up for me when I query available VPCs within the us-east-2 region.  Other regions work fine.  I am directly hitting the tsdb/query endpoint.. with curl.  (The full request was copied from Chrome developer tools.)  The query below fails.  If I change the region to us-east-1 - it will work.  

{"from":"1521387516311","to":"1521560316311","queries":[{"refId":"metricFindQuery","intervalMs":1,"maxDataPoints":1,"datasourceId":2,"type":"metricFindQuery","subtype":"ec2_instance_attribute","region":"us-east-2","attributeName":"VpcId","filters":{}}]}

I will also add that us-east-2 WORKS as expected (even in us-east-2) in 4.5.0.  It breaks somewhere before 4.6.3.. and remains broken in 5.0.3.

However cn-north-1 returns "{"message":"Metric request error"}"  (We don't list that as an available region in our console.  So, it may not really be available.)

**Comment by mdeora** [comment]
I am facing this issue in ap-south-1 region. So It doesn't seem like its region specific issue.

**Comment by mtruiz81** [comment]
hi,

I got exactly same issue, using  Grafana v4.6.3.

**Comment by torkelo** [comment]
Is this still an issue in v5.2 ?

**Comment by mdeora** [comment]
Haven't checked yet in 5.2, Is there anything specific for this done in this version?

**Comment by hc1tneville** [comment]
Yes, I can confirm that this is still there in 5.2.1.  I am testing with the following 2 queries:

ec2_instance_attribute(us-west-2, VpcId, {}) <- This returns 2 VPCs - but we have 5 in that region, so it's not quite right.
ec2_instance_attribute(us-east-2, VpcId, {}) <- This fails completely with the log entry below.

t=2018-07-19T17:41:06+0000 lvl=eror msg="Request error" logger=context userId=4 orgId=1 uname="Tom Neville" error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:505
0x433b48)\n/usr/local/go/src/runtime/panic.go:63
0x432bbd)\n/usr/local/go/src/runtime/signal_unix.go:388
0x449a89)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:467
0xdceedb)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:189
0xdcab04)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/cloudwatch.go:74
0xdbf7bf)\n/go/src/github.com/grafana/grafana/pkg/tsdb/request.go:17
0xa40019)\n/go/src/github.com/grafana/grafana/pkg/api/metrics.go:45
0xead24d)\n/usr/local/go/src/runtime/asm_amd64.s:575
0x461531)\n/usr/local/go/src/reflect/value.go:447
0x4be7d8)\n/usr/local/go/src/reflect/value.go:308

**Comment by torkelo** [comment]
@mtanda any chance to take a look at this?

**Comment by mtanda** [comment]
When I add alerting feature in 4.6.0-beta1, I rewrite backend datasource code.
I'll try to make a time for investigating this bug.

Related code.
https://github.com/grafana/grafana/blob/v4.6.3/pkg/tsdb/cloudwatch/metric_find_query.go#L490
https://github.com/grafana/grafana/blob/v5.2.1/pkg/tsdb/cloudwatch/metric_find_query.go#L467

**Comment by mtanda** [comment]
I make a PR.
https://github.com/grafana/grafana/pull/13221
