### ISSUE TITLE
Playlist shows left side panel 

### ISSUE THREAD

**Issue by jsedy7** [grafana/grafana#10740]
- I'm using Grafana v5.0.0-11571pre1
- Datasource: **Prometheus**
- Debian -> Docker container

I started playlist with three Dashboards. On the first dashboard is a left side panel which is hidden after few seconds. Second dashboard is normal without left side panel and on the third dashboard is the same situation, but after third dashboard is the first dashboard again with left side panel. I don't know, If is that expected behaviour. 

I expect, that left side panel is still hidden during the next iteration of playlist. I expect show of left side panel after reaction on mouse click or something else. 

Thank you! 🙂

**Comment by torkelo** [comment]
thanks for reporting this, fixed in https://github.com/grafana/grafana/commit/40c9d5f2a3694c8ce7ea697a72516362e0851c07
