### ISSUE TITLE
Graphite 1.1.X datasource with Tags issues many unnecessary fetch requests

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#10744]
Please include this information:
- What Grafana version are you using? 
Master docker image (as of noon 2018-02-02)
- What datasource are you using? 
Graphite 1.1.X
- What OS are you running grafana on?
 Linux Server / Mac client
- What did you do? 
Went to edit a panel.
- What was the expected result?
The tag keys/values would be visible and available to edit.
- What happened instead?
Many (48) tag key/value expression resolutions were issued to the backend resulting in ~12 seconds of latency before they all filled in.

I'm not sure exactly why these queries are necessary, since the panel was saved already and not being edited yet. It's not very kind to the backend and causes the user to wait.

On a similar note, it seems like the autocomplete for tag values doesn't debounce, causing a lot of concurrent (not cancelled) requests to the server. Tag key requests look to be cancelled properly if the user keeps typing (but aren't debounced). 

Finally, it seems like when a user selects a tag key, a request is made to get an initial set of tag values for the expression. I don't see that this is used as when I click into the tag value field, a brand new (identical) request is made. I'm guessing there is some sort of validation or something?

**Comment by alexanderzobnin** [comment]
Could you also explain the last paragraph in details?
