### ISSUE TITLE
UX: Permissions list

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10747]
Would be nice to get user & team avatars in this list as well as user full name (only showing login/username currently).

The Icon is the only thing that separates Users from Teams. Maybe we need a label instead? Team: User: and then we can use the avatar img instead. 

<img width="997" alt="screen shot 2018-02-03 at 09 58 13" src="https://user-images.githubusercontent.com/10999/35765659-e507003a-08c8-11e8-9688-1a175dbe64e5.png">

thoughts @mattttt ? @Ijin08 can you do a mockup?

**Comment by Ijin08** [comment]
![permissions_mockup_v2](https://user-images.githubusercontent.com/23470681/35802566-e04dcfc0-0a70-11e8-99c0-3151b33d0c2b.png)
This was a bit tricky. I tried Team: and User: which didn't turn out so good:
![permissions_mockup_no2](https://user-images.githubusercontent.com/23470681/35802505-a1aca016-0a70-11e8-8e2b-7e8401bfb43c.png)

![permissions_mockup_no](https://user-images.githubusercontent.com/23470681/35802496-98ce5e44-0a70-11e8-9978-88e2e1f77893.png)

Instead I put user/team after(I prefer the second one):
![permissions_mockup_v1](https://user-images.githubusercontent.com/23470681/35802556-d7bcfd0e-0a70-11e8-8d21-7f4ef530c0c6.png)

**Comment by marefr** [comment]
Hmm tricky. Maybe easier/nicer if we add sections in table dividing users and teams?

**Comment by torkelo** [comment]
thoughts @mattttt ?

**Comment by Ijin08** [comment]
That isn't a bad idea:
![permissions_mockup_v4](https://user-images.githubusercontent.com/23470681/35812097-5b33b4a6-0a90-11e8-83e9-70c2812a959b.png)
![permissions_mockup_v3](https://user-images.githubusercontent.com/23470681/35812080-524a1f24-0a90-11e8-9468-225148050b11.png)

**Comment by Ijin08** [comment]
![permissions_mockup_v5](https://user-images.githubusercontent.com/23470681/35814905-8b569cfa-0a97-11e8-8f73-5b7948d65209.png)

**Comment by marefr** [comment]
Agree

**Comment by mattttt** [comment]
I havent had the time yet to build an alternate mockup, however a few notes on the latest.

The blue text is sometime used for links, in other cases we use it for emphasis (query editors). It looks good, and jumps off the page, but on this page in particular, it feels like there isnt consistency. 

I suggest we leave it for `Viewer` and `Can`, and we try a different header style for the sections and explore the same style as the bold, white text used for "Add Permissions For:" in the add box above?

Want to play with this a bit, as I think it'll be a convention we use elsewhere.

**Comment by Ijin08** [comment]
Great feedback @mattttt 
Changed the blue color. I leave this too you so looking forward to see
![permissions_mockup_v6](https://user-images.githubusercontent.com/23470681/36022865-e4cfa90c-0d8a-11e8-9a17-3fe9a2af66d6.png)
 what you come up with.

**Comment by Ijin08** [comment]
Torkel wanted me to try on more thing:
![permissions_mockup_v7](https://user-images.githubusercontent.com/23470681/36025502-914fad8c-0d93-11e8-8816-9d9af0a5856c.png)

**Comment by torkelo** [comment]
Think I prefer that over all the other options, things align more and becomes easier to parse . Needs icons for the different roles :)  We can still sort so that all team rules are listed together before User rules etc.

**Comment by Ijin08** [comment]
![permissions_mockup_v9](https://user-images.githubusercontent.com/23470681/36096866-831a78c0-0ff8-11e8-9566-726e3d77c33f.png)

**Comment by torkelo** [comment]
I have started some initial work on this in this branch, https://github.com/grafana/grafana/compare/dashboard-acl-ux2 

@Ijin08 can you take over (checkout the above branch)
