### ISSUE TITLE
UX: Improve save modal

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10748]
- make leaving a note optional (do not show input field)
- save current time range
- save current variables

**Comment by torkelo** [comment]
related https://github.com/grafana/grafana/issues/8805

**Comment by Ijin08** [comment]
So my idea at the moment is to add a options button that expands the modal to show the different options:
![save_modal_closed](https://user-images.githubusercontent.com/23470681/35813340-a4510fe6-0a93-11e8-8a13-5653ed3c5e71.png)
![save_modal_open](https://user-images.githubusercontent.com/23470681/35813349-aced6e38-0a93-11e8-8583-dfa8cf815867.png)

**Comment by mattttt** [comment]
I think this makes a lot of sense. 

Originally though the options opening above the button (on click) is an anti-pattern, though it's just as odd to show the options below and split up the button row. 

Let's go ahead and build this as @Ijin08 proposes above, use it, and see how we can iterate accordingly.

**Comment by Ijin08** [comment]
Felt the need to explore this option as 
![save_modal_tabs](https://user-images.githubusercontent.com/23470681/35850259-7481f9c4-0b24-11e8-98a5-e7c465e8a425.png)
well:

**Comment by Ijin08** [comment]
![save_modal_tabs_quick](https://user-images.githubusercontent.com/23470681/35853468-e01c68dc-0b2d-11e8-9637-69bab8b3919a.png)

![save_modal_tabs_options](https://user-images.githubusercontent.com/23470681/35853486-ec35ab42-0b2d-11e8-825f-6669f2149ade.png)

**Comment by kfdm** [comment]
Having options to save (or not save) the current time range and current variables is quite a nice improvement ! I know that will help make things easier with some of my usage.

Though I am curious why there is a need to move things to an Options tab. While I understand wanting to reduce clutter, I wonder if everything on the same tab and just letting the user submit without filling anything out (perhaps add (optional) into the placeholder text) would be a simpler way to handle it.

**Comment by Ijin08** [comment]
Talked with @mattttt a while back about this and we are thinking of having a modal with short message and buttons for save, options and cancel. Hitting options will close modal and open new one in a appealing way.

![savemodal_v3closedoptions](https://user-images.githubusercontent.com/23470681/38607528-30e9e1cc-3d79-11e8-86f8-fc9fd1a5f4f2.png)

![savemodal_v3openoptions](https://user-images.githubusercontent.com/23470681/38607529-310980c2-3d79-11e8-874a-dc0d1ad920f0.png)

@torkelo , @mattttt , @davkal thoughts?

**Comment by kfdm** [comment]
Just an outside opinion, but I think using the second dialog only would provide a better flow. By hiding the note box behind options, it's much less likely that users will bother filling it out. By leaving everything on the same dialog, but making it optional, users that don't want to add a note can just skip it while making it easy to add a note if you want. Leaving both options (time range and variables) unchecked by default seems reasonable.

In a more involved operation, having a separate options dialog makes sense, but I feel like in this case, it adds an unnecessary extra step.
