### ISSUE TITLE
Graph Point Popup Truncates Numeric Value

### ISSUE THREAD

**Issue by nickman** [grafana/grafana#1074]
Using OpenTSDB and Grafana 1.9.0 (Dev).
This is not a critical issue for me, but I figured I would report it.

Obviously there is a limit to how wide the popup should be but I am seeing the numeric value truncated when the full metric name is long[ish].  Example:

![image](https://cloud.githubusercontent.com/assets/597608/5073329/2b5bdcbc-6e4f-11e4-86fa-277fb4c3fc09.png)

I'd be happy if the box was simply as wide as it needed to be, but other options are:
- Drop the value to the next line
- Create an indented tree for each segment of the metric name.
- Prefer truncation of the metric name over truncating the value.

**Comment by torkelo** [comment]
closing this as your series name is too long
