### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by karnamonkster** [grafana/grafana#10758]
Please include this information:
- What Grafana version are you using? - 4.6.3
- What datasource are you using? - ES & MySQL
- What OS are you running grafana on? - CentOS 
- What did you do? - I am trying to access grafana behind nginx proxy with a subpath
I did the changes on the root url & nginx configuration but somehow stuck at the login page.
------------------------------
Grafana configuration
```
# The ip address to bind to, empty will bind to all interfaces
http_addr =

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
#domain = localhost
domain = mywebsite.local

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false

# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s:/risk
#root_url = %(protocol)s://%(domain)s:%(http_port)s
```
----------------------------
================
NGINX configuration

```
location /risk/ {
        proxy_pass http://ip_of_grafana:3000/;
        proxy_max_temp_file_size 0;
#       rewrite ^/risk(.*) /$1 break;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass      $http_upgrade;
}
```

=================
Grafana & Nginx are running on different servers.
- What was the expected result? - 
I should be able to successfully login using http://mywebsite.local/risk 
- What happened instead?
Once i log in, i get a popup Unexpected Error. 

Kindly help

**Comment by torkelo** [comment]
what was the error? (check grafana-server logs)

**Comment by karnamonkster** [comment]
t=2018-02-06T07:29:26+0400 lvl=info msg="Initializing Stream Manager"
t=2018-02-06T07:29:26+0400 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/risk socket=
t=2018-02-06T07:29:27+0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-02-06T07:29:31+0400 lvl=dbug msg="Looking for App Dashboard Updates" logger=plugins
t=2018-02-06T07:29:37+0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-02-06T07:29:39+0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.141.25.11 time_ms=0 size=34 referer=
t=2018-02-06T07:29:47+0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-02-06T07:29:51+0400 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1

**Comment by karnamonkster** [comment]
t=2018-02-06T07:29:26+0400 lvl=info msg="Initializing Stream Manager"
t=2018-02-06T07:29:26+0400 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/risk socket=
t=2018-02-06T07:29:27+0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-02-06T07:29:31+0400 lvl=dbug msg="Looking for App Dashboard Updates" logger=plugins
t=2018-02-06T07:29:37+0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-02-06T07:29:39+0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.xx.xx.xx time_ms=0 size=34 referer=
t=2018-02-06T07:29:47+0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-02-06T07:29:51+0400 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1

**Comment by karnamonkster** [comment]
I fixed the issue. It had to do with the Nginx configuration I had other subpath as /home for other site which was getting redirected after grafana (mywebsite.local/risk ) and login page.
Thanks for your help anyways.. Moving on to the next steps.
