### ISSUE TITLE
Unexpected event_publisher configuration present in grafana 4.6.3 Debian Stretch (9) package

### ISSUE THREAD

**Issue by stefano-m** [grafana/grafana#10765]
The configuration files installed by the  grafana 4.6.3 Debian Stretch (9) package seem to include the `event_publisher` configuration that was removed in dea631bedca9f24c86cd4b3ce56f27c917c3382c (#9645).

I am quite surprised because there is no trace of that config in the repository and I wonder where it comes from.

I have come across this issue because we enabled the `event_publisher` by mistake causing the grafana service to fail.

The debian file has been obtained from

https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.6.3_amd64.deb

as indicated on the grafana website.

- What Grafana version are you using?

Version *4.6.3* from the *Debian* package.

```shell
 dpkg -l grafana
ii  grafana     4.6.3   amd64      Grafana
```

- What datasource are you using?

N/A

- What OS are you running grafana on?

Debian Stretch

- What did you do?

Install the debian package

- What was the expected result?

No `event_publisher` section in the default configuration file

- What happened instead?

The `event_publisher` section is present in the configuration files

```shell
$ grep -nri -C 3 event_publisher /etc/grafana/
/etc/grafana/grafana.ini-361-
/etc/grafana/grafana.ini-362-
/etc/grafana/grafana.ini-363-#################################### AMQP Event Publisher ##########################
/etc/grafana/grafana.ini:364:[event_publisher]
/etc/grafana/grafana.ini-365-;enabled = false
/etc/grafana/grafana.ini-366-;rabbitmq_url = amqp://localhost/
/etc/grafana/grafana.ini-367-;exchange = grafana_events
```

```shell
$ grep -nri -C 3 event_publisher /usr/share/grafana/conf/
/usr/share/grafana/conf/sample.ini-361-
/usr/share/grafana/conf/sample.ini-362-
/usr/share/grafana/conf/sample.ini-363-#################################### AMQP Event Publisher ##########################
/usr/share/grafana/conf/sample.ini:364:[event_publisher]
/usr/share/grafana/conf/sample.ini-365-;enabled = false
/usr/share/grafana/conf/sample.ini-366-;rabbitmq_url = amqp://localhost/
/usr/share/grafana/conf/sample.ini-367-;exchange = grafana_events
--
/usr/share/grafana/conf/defaults.ini-383-
/usr/share/grafana/conf/defaults.ini-384-
/usr/share/grafana/conf/defaults.ini-385-#################################### AMQP Event Publisher ################
/usr/share/grafana/conf/defaults.ini:386:[event_publisher]
/usr/share/grafana/conf/defaults.ini-387-enabled = false
/usr/share/grafana/conf/defaults.ini-388-rabbitmq_url = amqp://localhost/
/usr/share/grafana/conf/defaults.ini-389-exchange = grafana_events

```

**Comment by torkelo** [comment]
yes, this section was removed in v5 (not yet released), this option is still there in v4.6.3
