### ISSUE TITLE
Allow rows (or panels) to repeat zero times

### ISSUE THREAD

**Issue by matthiasr** [grafana/grafana#10764]
Please include this information:
- What Grafana version are you using?

4.6.3

- What datasource are you using?

Prometheus

- What OS are you running grafana on?

Linux

- What did you do?

Create a dashboard with template variables that either have 1 or no values, depending on whether a class of metrics exists on the selected Prometheus server (via a templated datasource)

- What was the expected result?

When there is no match for the label value, the row is hidden.

- What happened instead?

The label value becomes "None", and the row is still shown, with no data on the graphs.

Motivation:

The use case we have is for our log systems. Most of the dashboard is about the health of the log storage cluster (Kafka). This is the same for both systems. However, depending on the _source_ of the logs, we have different shipping agents (rsyslog, custom shipper) with different metrics and semantics.

There are separate Prometheus servers for each system and cluster. Since we have multiple clusters in each system, we use data source templating already. Right now, we need to have two copies of this dashboard (with all the associated issues with divergence). I created template variables to probe for the presence of the metrics from each of the shippers, and made the corresponding rows repeat based on these. However, I ran into the issue that it's actually impossible to have 0 templating values, because if nothing comes back from `label_values(some_shipper_metric, job)` the templating variable becomes None.

Possible solutions (incomplete list): make it possible to have no value in a template variable at all (not even None); or make repeating rows and panels recognize None and hide. I think the latter would has less potential for side-effects elsewhere.

**Comment by torkelo** [comment]
they cant be hidden completely then there would be no source panels to repeat. Not sure what the best way to solve this. Think templating & repeating panels is not the best solution, maybe programmatic generation of dashboards instead?

**Comment by matthiasr** [comment]
It could just toggle the "Collapse" state of the remaining row? That way the row is still "there" but not taking up much space.
