### ISSUE TITLE
[Bug] Dashboards list "captures" the mouse scroll, even if panel is begger than list of dashboards on it

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#10772]
Please include this information:
- What Grafana version are you using? **grafana-server: `Version 5.0.0-pre1 (commit: ee973a9)`, grafana-cli: `Grafana cli version 5.0.0-pre1`**
- What datasource are you using? **InfluxDB: `InfluxDB shell version: 1.3.6`**
- What OS are you running grafana on? **Ubuntu 17: `Linux cncftest.io 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`**
- What did you do? 
**I have a list of dashboards panel, it contains a long list of dashboards. I've resized it to be bigger than this list (and there is more than 100px space below the last dashboard). There are two different panels above it. When I place the mouse over the 1st dashboard and then scroll down using the mouse wheel, it scrolls until the mouse pointer is over the dashboards list. Once it is on the dashboard list - panel "captures" mouse scroll and I cannot scroll more. It also shows vertical scroll bar on this dashboard list panel, which moves just a few pixels (but again, the panel is a lot higher than all dashboards on the list). I can only scroll down when I move mouse maximum right where the main page scrollbar is.
I think there should be no vertical scroll bar on the dashboards list in this case, and it should not capture the mouse wheel.** 
- What was the expected result?
**Dashboards list should not have a vertical scrollbar in this case and it should not capture mouse wheel scroll.**
- What happened instead?
**Dashboard list captured mouse wheel, showed vertical scroll-bar that is 99% size of the dashboard list and just moved few pixels up and down, no matter how big is the dashboard list. This was not happening on Grafana V4 I believe.**

This is the place where it happens:
https://k8s.devstats.cncf.io/dashboard/db/dashboards?refresh=15m&orgId=1
It happens on "All Kubernetes dashboards" panel.

Original issue here: 
https://github.com/cncf/devstats/issues/60

**Comment by daniellee** [comment]
The above commit fixes the wheel scroll getting stuck on a child panel with scroll. Will also investigate why the dashlist always gets a scrollbar.

**Comment by lukaszgryglicki** [comment]
Great thanks!
Please let me know when Nightly Build of V5 is ready for this fix. I'll update my Grafanas.
Thanks again!

**Comment by daniellee** [comment]
@lukaszgryglicki The latest nightly build now contains this fix: https://grafana.com/grafana/download/5.0.0-11634beta1

The second error is related to whether the dashlist has the `Show headings` option selected. If it is not selected then the height seems to be incorrectly calculated. Trying to figure out a fix for it now.

**Comment by lukaszgryglicki** [comment]
Thanks.
Will update all Grafanas on test & prod probably tomorrow, assuming that there will be a nightly build that fixed both problems.
Thanks for super-fast reaction!
