### ISSUE TITLE
[Bug or Feature] Can't see tags on dashboard drop-down

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#10778]
Please include this information:
- What Grafana version are you using? 
I'm using two different v5.0-prerelease Grafanas:
- https://k8s.cncftest.io uses:  **grafana-server: `Version 5.0.0-pre1 (commit: ee973a9)`, grafana-cli: `Grafana cli version 5.0.0-pre1`** - and this build is OK
- https://k8s.devstats.cncf.io uses: **grafana-server: `Version 5.0.0-pre1 (commit: 3a0459e)`, grafana-cli: `Grafana cli version 5.0.0-pre1`** - and this build is broken IMHO

- What datasource are you using? **InfluxDB: `InfluxDB shell version: 1.3.6`**

- What OS are you running grafana on? **Ubuntu 17: `Linux cncftest.io 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`**

- What did you do?
- I click Grafana dashboards drop-down menu on https://k8s.cncftest.io (which uses older nightly build) - it displays tags on the drop-down:
![screen shot 2018-02-05 at 18 39 45](https://user-images.githubusercontent.com/2469783/35819870-41422fdc-0aa4-11e8-8073-c52bc30d8118.png)
- I click Grafana dashboards drop-down menu on https://k8s.devstats.cncf.io (which uses newer nightly build) - it doesn't display tags on the drop-down menu (but there are the same tags, as you can see from filter menu):
![screen shot 2018-02-05 at 18 39 55](https://user-images.githubusercontent.com/2469783/35819935-7a737892-0aa4-11e8-8a93-afa16268a7d8.png)

I can filter for tags on both Grafanas, so tags are there, but not visible in a newer build...

Is this a bug, or expected feature (like tags being removed from the drop-down)? 
 
- What was the expected result?
**I think both Grafanas should show tags on the drop-down**
- What happened instead?
**Only the older v5 nightly build show the tags**

cncf/devstats issue here: https://github.com/cncf/devstats/issues/64

**Comment by marefr** [comment]
Please upgrade to latest nightly. It was fixed in https://github.com/grafana/grafana/commit/162f4941f0a21b16878eebc51960af7a410b7778

**Comment by lukaszgryglicki** [comment]
Great, I'm waiting for https://github.com/grafana/grafana/issues/10772, so will update when this is fixed too.
Thanks!
