### ISSUE TITLE
Unable to switch org when too many orgs listed

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#10774]
Please include this information:
- What Grafana version are you using? 
5.0.0-beta1

- What datasource are you using?
Not Applicable

- What OS are you running grafana on?
Ubuntu 16.04 & Chrome

- What did you do?
Switch organization with 30 plus organization

- What was the expected result?
Scroll bar or search bar should be visible to switch org

- What happened instead?
Scroll bar or search bar not available to see the entire list

**Comment by nono303** [comment]
+1

**Comment by Othyus** [comment]
+1

**Comment by Magellan2K** [comment]
+1

**Comment by bennysan** [comment]
+1

**Comment by hjf1223** [comment]
How about  to add a searchbox to filter org by name?
