### ISSUE TITLE
Error with google auth (5.pre1)

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#10775]
I just copied my google auth config from a 4x server to 5x dev server, and after selecting the account, it redirects to:

![image](https://user-images.githubusercontent.com/705951/35816361-cbee93e6-0a9a-11e8-9669-e5b8c97d5d06.png)

html/template: "404" is undefined

I have not tried to debug much yet... but will keep you posted when I get a chance

**Comment by torkelo** [comment]
strange, unable to replicate. 

There does look like there is an issue with the error handling but google oauth should work, works on http://play.grafana.org/login after upgrade from v4 without any config changes. 

What are your oauth settings?

**Comment by torkelo** [comment]
fixed the issue with the error handling, but the error you get is due to config.

**Comment by ryantxu** [comment]
thanks!  yes, I moved setup to a new hostname that was not yet allowed by my google site configs
