### ISSUE TITLE
Index too long on MySQL 5.0.0-beta1

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#10779]
This issue is identical with https://github.com/grafana/grafana/issues/10244 except now it concerns  index `UQE_dashboard_org_id_folder_id_title`

Using official docker image version 5.0.0-beta1

When running migration SQL:
```
CREATE UNIQUE INDEX `UQE_dashboard_org_id_folder_id_title` ON `dashboard` (`org_id`,`folder_id`,`title`);
```

fails with
```
Sqlstore::Migration failed err: Error 1071: Specified key was too long; max key length is 767 bytes
```

**Comment by marefr** [comment]
Thanks for reporting this @FUSAKLA. Will try to resolve this as soon as possible. In the meantime you should be able to resolve this by alter the dashboard title column to a lower length than 255, for example 190 as seen in solution for #10244

**Comment by FUSAKLA** [comment]
yep i already did that so I'm not blocked by this.

Thank's for looking into this so quiclky!
