### ISSUE TITLE
Update docs for restarting docker container

### ISSUE THREAD

**Issue by uppalarakesh2** [grafana/grafana#10784]
Hello,
I have used official docker image of grafana to do the setup, When i run the grafana container it works fine and i could hit the grafana URL  everything looks  fine.
When i do a service grafana-server restart it says failed but still my grafana works fine. So when i try to install plugins in the container using below command
grafana-cli plugins install grafana-piechart-panel,
 It installs successfully but asks for a restart which i cannot do and i couldn't see the plugins on grafana dashboard though it is installed.

Grafana logs
/var/log/grafana/grafana.log

t=2018-02-06T01:55:06+0000 lvl=info msg="Shutdown started" logger=server code=1 reason="Startup failed"
t=2018-02-06T01:55:06+0000 lvl=info msg="stopped http server" logger=http.server
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-02-06T01:55:06+0000 lvl=info msg="Stopped CleanUpService" logger=cleanup reason="context canceled"
t=2018-02-06T01:55:06+0000 lvl=info msg="Stopped Stream Manager"
t=2018-02-06T01:55:06+0000 lvl=info msg="Stopped Alerting" logger=alerting.engine reason="context canceled"
t=2018-02-06T01:55:06+0000 lvl=info msg="Shutdown completed" logger=server reason="context canceled"

**Comment by bergquist** [comment]
Are there any logs before `t=2018-02-06T01:55:06+0000 lvl=info msg="Shutdown started" logger=server code=1 reason="Startup failed"` ? That would make it easier to understand what happened.

**Comment by uppalarakesh2** [comment]
t=2018-02-06T01:42:10+0000 lvl=info msg="Starting Grafana" logger=server version=4.6.0-beta2 commit=fff4cfd compiled=2017-10-17T10:17:32+0000
t=2018-02-06T01:42:10+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-02-06T01:42:10+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-02-06T01:42:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-02-06T01:42:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-02-06T01:42:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-02-06T01:42:10+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-02-06T01:42:10+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-02-06T01:42:10+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-02-06T01:42:10+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-02-06T01:42:10+0000 lvl=info msg="App mode production" logger=settings
t=2018-02-06T01:42:10+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana-server.pid pid=65
t=2018-02-06T01:42:10+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-02-06T01:42:10+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-02-06T01:42:10+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-02-06T01:42:10+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-02-06T01:42:10+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-02-06T01:42:10+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-02-06T01:42:10+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2018-02-06T01:42:10+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2018-02-06T01:42:10+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-02-06T01:42:10+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-02-06T01:42:10+0000 lvl=info msg="Initializing Stream Manager"
t=2018-02-06T01:42:10+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2018-02-06T01:42:10+0000 lvl=eror msg="Fail to start server" logger=server error="listen tcp 0.0.0.0:3000: bind: address already in use"
t=2018-02-06T01:42:10+0000 lvl=info msg="Shutdown started" logger=server code=1 reason="Startup failed"
t=2018-02-06T01:42:10+0000 lvl=info msg="stopped http server" logger=http.server
t=2018-02-06T01:42:10+0000 lvl=info msg="Stopped Alerting" logger=alerting.engine reason="context canceled"
t=2018-02-06T01:42:10+0000 lvl=info msg="Stopped Stream Manager"
t=2018-02-06T01:42:10+0000 lvl=info msg="Stopped CleanUpService" logger=cleanup reason="context canceled"
t=2018-02-06T01:42:10+0000 lvl=info msg="Shutdown completed" logger=server reason="context canceled"
t=2018-02-06T01:55:06+0000 lvl=info msg="Starting Grafana" logger=server version=4.6.0-beta2 commit=fff4cfd compiled=2017-10-17T10:17:32+0000
t=2018-02-06T01:55:06+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-02-06T01:55:06+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-02-06T01:55:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-02-06T01:55:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-02-06T01:55:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-02-06T01:55:06+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-02-06T01:55:06+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-02-06T01:55:06+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-02-06T01:55:06+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-02-06T01:55:06+0000 lvl=info msg="App mode production" logger=settings
t=2018-02-06T01:55:06+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana-server.pid pid=189
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-02-06T01:55:06+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-02-06T01:55:06+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-02-06T01:55:06+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-02-06T01:55:06+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-02-06T01:55:06+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-02-06T01:55:06+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2018-02-06T01:55:06+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2018-02-06T01:55:06+0000 lvl=info msg="Registering plugin" logger=plugins name=Annunciator
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing Stream Manager"
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2018-02-06T01:55:06+0000 lvl=eror msg="Fail to start server" logger=server error="listen tcp 0.0.0.0:3000: bind: address already in use"
t=2018-02-06T01:55:06+0000 lvl=info msg="Shutdown started" logger=server code=1 reason="Startup failed"
t=2018-02-06T01:55:06+0000 lvl=info msg="stopped http server" logger=http.server
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-02-06T01:55:06+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-02-06T01:55:06+0000 lvl=info msg="Stopped CleanUpService" logger=cleanup reason="context canceled"
t=2018-02-06T01:55:06+0000 lvl=info msg="Stopped Stream Manager"
t=2018-02-06T01:55:06+0000 lvl=info msg="Stopped Alerting" logger=alerting.engine reason="context canceled"
t=2018-02-06T01:55:06+0000 lvl=info msg="Shutdown completed" logger=server reason="context canceled"

**Comment by uppalarakesh2** [comment]
Below is the info i get when i do a restart grafana which is in docker container

 service grafana-server restart
[ ok ] Stopping Grafana Server: Grafana Server is not running but pid file exists, cleaning up.
[FAIL] Starting Grafana Server: failed!

**Comment by seanlaff** [comment]
I'm experiencing the same problem- I mounted in my plugin directory when starting the container as a workaround.

**Comment by xlson** [comment]
Docker runs the Grafana process directly within the container and upstart/systemd is not involved at all. Because of that, `service grafana-server restart` won't do anything. To restart grafana is to restart the docker container. 

Have you tried using environment variables to have Grafana install the plugins at startup instead? ([more about that here](http://docs.grafana.org/installation/docker/#installing-plugins-for-grafana)) Alternatively, you could download the plugins using `grafana-cli` and add them to the container before it boots either by creating your own docker image that extends the official one or by mapping a volume into the container with the plugins you need.

**Comment by daniellee** [comment]
How to restart should be in the docs: http://docs.grafana.org/installation/docker/#installing-using-docker

**Comment by ilayn** [comment]
When Docker container is restarted it goes back to the pristine condition with no plugin installed. Could you please tell me how to install a plugin in a docker container after it is created?

**Comment by xlson** [comment]
@ilayn It's hard to give specific Azure advice, you are probably better served by going to https://community.grafana.com/ for detailed help.

But a good start would be to look at the persistent storage instructions for the Grafana docker image. You will probably have to look at the specifics of how to configuring persistent storage on Azure. See: https://grafana.com/docs/grafana/latest/installation/configure-docker/#save-your-grafana-data

**Comment by ilayn** [comment]
That's also [another track](https://github.com/MicrosoftDocs/azure-docs/issues/16481) that I got stuck but thanks for the tips.
