### ISSUE TITLE
[Feature Request] Add image attachments for Pushover notifications

### ISSUE THREAD

**Issue by jeroenj** [grafana/grafana#10780]
[Pushover 3.0 now supports image attachments.](https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30\0)

It would be a nice addition if an image of the related graph gets sent with the notification just like it happens with email (and probably other notifications.

**Comment by bergquist** [comment]
Pull request would be appreciated.

**Comment by jpenalbae** [comment]
PR #14852 should close this

**Comment by bergquist** [comment]
@jeroenj any chance you have time to test the PR?

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/14852
