### ISSUE TITLE
Teams - Per-team Permission Changes Affecting All Dashboards, Not Just the Target

### ISSUE THREAD

**Issue by cailen** [grafana/grafana#10781]
Hi,

When adding a team to a dashboard folder, the change not only takes effect for that particular dashboard but instead sets it for all dashboard folders.

For example: "Folder 1", I add the "dev" team as "Admin". If I go to "Folder 2", "dev" team shows up as "Admin." If I delete "dev" team from "Folder 2", it deleted it also from "Folder 1"

Version: Grafana v5.0.0-pre1 (commit: a906dd8) on Ubuntu (Docker version 17.12.0-ce, build c97c6d6) pulling grafana:master.

**Comment by marefr** [comment]
@cailen this have been fixed today. It's included in the v5.0 Beta 1 released today and the latest nightly builds.
