### ISSUE TITLE
[Feature Request] Add "Toggle Edit Mode" to ElasticSearch Data Source

### ISSUE THREAD

**Issue by PeterWeiler** [grafana/grafana#10783]
- What Grafana version are you using? 4.6.3
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Ubuntu-16.04

The InfluxDB data source offers a "Toggle Edit Mode" feature where a query can be manually entered.  This facilitates entering complex queries (e.g. having InfluxDB perform calculations across multiple fields) not otherwise supported by the Grafana query editor; it also enables users to take advantage of new InfluxDB features / syntax before they are incorporated into the query editor.

Please add the same capability to the ElasticSearch data source.  This will enable users to take advantage of a much richer set of aggregations, including pipelines to perform calculations, prior to their incorporation into the Grafana query editor.

**Comment by torkelo** [comment]
This can't work for Elasticsearch as Grafana needs the query model to understand how to process the Elasticsearch response (a response that is infinitely more complex than any other TSDB and is close to impossible to parse if you do now know the intent of the query). 

We can let small parts of the query be "raw json" (like each aggregation or metric definition) but  not the whole thing. There already is an issue for this so will close this one
