### ISSUE TITLE
Multiple queries Influxdb

### ISSUE THREAD

**Issue by bonaime** [grafana/grafana#10790]
- What Grafana version are you using?
Grafana v4.6.3 (commit: 7a06a47)
- What datasource are you using?
InfluxDB, version 1.4.3, branch 1.4, commit 60d27e6995558f38a39e90b35a92cbac080310a3
- What OS are you running grafana on?
Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
- What did you do?
I can graph one measurement from influxdb (collectd) but I can not plot another mesurement on the same graph. If the first query is disable and the second one is exactly a copy of the first one, grafana does not graph anything and show a "Network Error: undefined(undefined)" error

- What was the expected result?
I expect to see two measurements on the same graph

- What happened instead?
no graph

  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, 

working query A
SELECT mean("value") FROM "df_free" WHERE ("host" = 'XXX') AND time >= 1515776185743ms and time <= 1516078010588ms GROUP BY time(2m) fill(null)

not working query A and B
SELECT mean("value") FROM "df_free" WHERE ("host" = 'XXX') AND time >= 1515776185743ms and time <= 1516078010588ms GROUP BY time(2m) fill(null);SELECT mean("value") FROM "df_free" WHERE ("host" = 'XXX') AND time >= 1515776185743ms and time <= 1516078010588ms GROUP BY time(2m) fill(null)

not working query B with A disabled
;SELECT mean("value") FROM "df_free" WHERE ("host" = 'XXX') AND time >= 1515776185743ms and time <= 1516078010588ms GROUP BY time(2m) fill(null)

When I connect with CLI to influxdb, I get values with those 3 queries

![capture d ecran 2018-02-06 a 06-02-18 10 09 53](https://user-images.githubusercontent.com/750709/35851760-4171fa34-0b29-11e8-8900-a0b7574a41e9.png)
![capture d ecran 2018-02-06 a 06-02-18 10 10 20](https://user-images.githubusercontent.com/750709/35851766-49201a72-0b29-11e8-9d59-cb492071c77f.png)
![capture d ecran 2018-02-06 a 06-02-18 10 10 01](https://user-images.githubusercontent.com/750709/35851767-4939a96a-0b29-11e8-950e-b2a50408761f.png)

**Comment by torkelo** [comment]
can you open chrome dev tools network tab and inspect the response from InfluxDB for your query B?

**Comment by bonaime** [comment]
With both queries or only B query, I have the "Network Error: undefined(undefined)" error and no response: "failed to load response data" in chrome dev tools network tab

**Comment by torkelo** [comment]
check network tab, is a request to influxdb sent? what does influxdb respond with?

**Comment by bonaime** [comment]
For just query B, the request sent is 
";SELECT mean("value") FROM "df_free" WHERE ("host" = 'XXX') AND time >= 1515776185743ms and time <= 1516078010588ms GROUP BY time(2m) fill(null)"
chrome show me the query in red
and no anwer from influxdb. In the response panel , I have only " Failed to load response data". 
Maybe the semicolon starting the request is a problem in this case

**Comment by torkelo** [comment]
so influxdb responds with an empty body? Sounds like a problem with your influxdb server, strange.

**Comment by torkelo** [comment]
sounds very strange that influxdb is not even returning an error, can you check influxdb logs?

**Comment by bonaime** [comment]
with just query A the query is
"SELECT mean("value") FROM "df_free" WHERE ("host" = 'XXX') AND time >= 1515776185743ms and time <= 1516078010588ms GROUP BY time(2m) fill(null)"
and the answer is basicaly all the data I want
{"results":[{"statement_id":0,"series":[{"name":"df_free","columns":["time","mean"],"values":[[1515776160000,3646822809.6],[1515776280000,3646822809.6],[1515776400000,3646822809.6],[1515776520000,3646822809.6],[1515776640000,3646822809.6],[1515776760000,3646822809.6],
......
[1516076640000,null],[1516076760000,null],[1516076880000,null],[1516077000000,null],[1516077120000,null],[1516077240000,null],[1516077360000,null],[1516077480000,null],[1516077600000,null],[1516077720000,null],[1516077840000,null],[1516077960000,null]]}]}]}

**Comment by torkelo** [comment]
yes, but it was query B that was failing, why show query A response? did you check error logs in InfluxDB? are you sure InfluxDB resposne is empty? what is the status code from influxdb?

**Comment by bonaime** [comment]
It is very strange.
Query A is disable: when I disable or enable query B, I did not see anything on influxdb log
With Query B disable:  I disable or enable query A, I see the queries in influxdb. 

So I think with only query B, the query does not come through influxdb

**Comment by bonaime** [comment]
And in chrome dev network, I have
net::ERR_CONNECTION_RESET

**Comment by bonaime** [comment]
Here are the http request from chrome dev network
Query A working
http://influxdbserver:port/api/datasources/proxy/2/query?db=collectd&q=SELECT%20mean(%22value%22)%20FROM%20%22df_free%22%20WHERE%20(%22host%22%20%3D%20%27XXX%27)%20AND%20time%20%3E%3D%201515776185743ms%20and%20time%20%3C%3D%201516078010588ms%20GROUP%20BY%20time(2m)%20fill(null)&epoch=ms
Query B not working
http://influxdbserver:port/api/datasources/proxy/2/query?db=collectd&q=%3BSELECT%20mean(%22value%22)%20FROM%20%22df_free%22%20WHERE%20(%22host%22%20%3D%20%27XXX%27)%20AND%20time%20%3E%3D%201515776185743ms%20and%20time%20%3C%3D%201516078010588ms%20GROUP%20BY%20time(2m)%20fill(null)&epoch=ms

For the B query, there is a "%3B" before SELECT !

**Comment by torkelo** [comment]
strange, works fine for me against influxdb 1.4.3

![image](https://user-images.githubusercontent.com/10999/35857111-67d0cade-0b38-11e8-9e74-0b50c43825d4.png)

**Comment by bonaime** [comment]
<img width="841" alt="capture d ecran 2018-02-06 a 06-02-18 12 48 06" src="https://user-images.githubusercontent.com/750709/35858421-a62e806a-0b3c-11e8-8de0-3a1c069a90b0.png">

**Comment by torkelo** [comment]
and if you click on response in network tab when both queries are there what do you see? 

The `%3B` is the correct way to separate queries and works fine against influxdb 1.4.3

**Comment by bonaime** [comment]
<img width="1143" alt="capture d ecran 2018-02-06 a 06-02-18 13 07 37" src="https://user-images.githubusercontent.com/750709/35859025-d40fa2aa-0b3e-11e8-9376-7d4ba3a5779f.png">

**Comment by torkelo** [comment]
strange, wonder what could be wrong with your influxdb server so that it does not respond. Checked inflxudb server logs and grafana-server logs?

**Comment by bonaime** [comment]
Found the problem ! Influxdb and Grafana are not hosted locally and not even in my company. I am sure that is is our firewall which filters some requests. It is the reason why I don't see anything in the logs of grafana and influxdb. When I connect localy to grafana, I don't have any problems !

**Comment by torkelo** [comment]
that's great!
