### ISSUE TITLE
Truncated variable values, for large bigint values

### ISSUE THREAD

**Issue by jdavid** [grafana/grafana#10799]
Grafana 5.0.0-beta1 on Ubuntu Artful installed from https://packagecloud.io/grafana/testing/debian/
Datasource: PostgreSQL 9.6

Added a variable. Query: SELECT column FROM table
Where the column's type is bigint

Expected result: 6951419298100303058
Got instead: 6951419298100303000

This is to say: for very large values the values are truncated in Grafana (...3000 instead of ...3058)

**Comment by torkelo** [comment]
Grafana uses float64, so it needs to fit that. but this should fit in a float64. Maybe an issue with the postgres s golang driver.

**Comment by jdavid** [comment]
Actually I think it doesn't fit. With Python:

    >>> int(float(6951419298100303058))
    6951419298100302848

I have the exact same result in C.

**Comment by torkelo** [comment]
ok, then I will close this
