### ISSUE TITLE
Grafana hangs when sending session cookie of expired session

### ISSUE THREAD

**Issue by goran-rumin** [grafana/grafana#10797]
Setup:
- 2x Grafana 4.6.3 in Docker (HA setup)
- one PostgreSQL database for data and sessions
- default config related to sessions (except `provider` and `provider_config`)

Session in DB is deleted after 1 day of inactivity, but if browser is not closed in that time, grafana_sess cookie is never deleted. When you open Home Dashboard after 1 day, Grafana correctly shows the interface as anonymous user but when you click Login, Grafana is stuck at trying to load login view. Same behaviour is observed when trying to logout right after doing login. Expected behaviour would be to ignore the cookie if its value is invalid.

How to reproduce (No. 1):
1. Login
2. Logout

How to reproduce (No. 2):
1. Login
2. Don't close the browser
3. Get value of your grafana_sess cookie
4. Connect to PostgreSQL DB and execute `delete from session where session.key='<cookie value>'`
5. Refresh (or reopen grafana) in browser and try to login

**Comment by torkelo** [comment]
this sounds very strange, any errors in grafana.log?

**Comment by torkelo** [comment]
> How to reproduce (No. 1):
> Login
> Logout

Not sure I follow you. Logging in / out is working fine, we would have thousands complaining if this did not work.

**Comment by goran-rumin** [comment]
No related errors in grafana.log. 
I know that Login/logout is common functionality, but with described setup, same problem happens. It may be important to mention that I use LDAP Authentication.

**Comment by torkelo** [comment]
So Logout always hangs for you in every case?

**Comment by goran-rumin** [comment]
Yes, I also tried using admin user that is added through .ini file, same thing.

**Comment by torkelo** [comment]
tested both scenarios with postgres, unable to replicate anything wrong. Do others get this behavior? Maybe something with your browser? What browser do you use? Do you have a proxy infront of grafana that could be causing issues?

**Comment by goran-rumin** [comment]
I use Chrome 63. It's not related to browser because I get same behaviour in Safari 11.0.1. In front of two Grafanas is HAProxy. I don't believe it's related to it either since it returns 504 when Grafana is stuck and never hangs when proxying other Grafana endpoints like dashboards.
Other users of this Grafana installation get same behaviour with various operating systems and browsers.
Did you try it with HA setup?

**Comment by torkelo** [comment]
and you HAProxy logs and grafana-server logs? Is there a request there that hangs? any errors?

**Comment by goran-rumin** [comment]
After additional investigation, my conclusion is that this is most likely Docker issue since I observed other strange behaviours related to Docker commands on one instance, while other Grafana instance behaves as expected. 
I will post solution here when I manage to pinpoint exact problem.
Sorry for the inconvenience.

**Comment by goran-rumin** [comment]
If anyone encounters this problem, issue is related to Docker and described here https://github.com/moby/moby/issues/30135 - log deadlock happens which makes whole container unresponsive. Issue is resolved by updating Docker to 17.03+ version.
