### ISSUE TITLE
Heatmap: disable log scale when using time time series buckets 

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#10792]
How to reproduce:
1. create heatmap panel.
1. use _Time series buckets_ data format
1 set scale to _log (base 2)_
1. add query like this
    <img width="1224" alt="screen shot 2018-02-06 at 13 46 01" src="https://user-images.githubusercontent.com/4932851/35855425-3d32c26c-0b44-11e8-9ec5-6fd8873910c1.png">
1. enable tooltip and hover any bucket

You will not see a tooltip.

Seems, this issue caused by a reason similar to #10724

**Comment by thattolleyguy** [comment]
@alexanderzobnin I was taking a look into this but don't have a good solution. Are you working on it or should I keep trying? Thanks for your help.

**Comment by alexanderzobnin** [comment]
@thattolleyguy I'm working on fix.

**Comment by torkelo** [comment]
changed title, log scale should not be used/enabled for time series buckets

**Comment by thattolleyguy** [comment]
@torkelo why not? This is exactly what I need in my use case

**Comment by torkelo** [comment]
because with time series buckets it's the time series database that is responsible for doing the bucketing, so we can support log scale but then the time series bucket sized needs to follow log scale as well

**Comment by torkelo** [comment]
so the log scale option option in grafana makes no sense as it is up your tsdb query to control the size of the buckets (logarithmic size or not), it cannot be changed later in Grafana.

**Comment by thattolleyguy** [comment]
So I'm using prometheus and my buckets represent time intervals (15m, 30m, 1h, 2h, 4h, 12h, 18h, 24h, 48h). They are roughly log2 but not exactly and that's where the problem lies. I could line them up with a log 2, but I figure grafana should have the ability to graph whatever is returned on a scaled axis

**Comment by torkelo** [comment]
Yes I agree that is completely separate issue where the scale is totally controlled by the buckets returned , we have an open feature request for that and some initial work to support that use case

**Comment by thattolleyguy** [comment]
Got it, so you're not saying no log scale. You're just saying the scale shouldn't be manually set, it should be determine automatically by the data?

**Comment by torkelo** [comment]
> determine automatically by the data?

yes, so if data returns series named, 10, 100, 150, 170, 2000 

you will get those y-axis ticks.

**Comment by alexanderzobnin** [comment]
Fixed by #11087
