### ISSUE TITLE
[Feat] Import dashboard to folder

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10796]
Should be possible to select a specific folder when importing a dashboard. Right now a dashboard is always imported to the General folder.

* Solution must take permissions into account when importing a dashboard to a folder which is not *General*.
* Need to change access logic to import page in sidenav, dashboard search and manage dashboards page. Use same solution as in #11858 

From #10134:
Should be possible to provide a folder identifier (as querystring) when importing a new dashboard.

Import dashboard when folder identifier provided
- [ ] Folder drop down pre-populated based on folder identifier

In manage dashboards page
- [ ] Add an "import dashboard" button/link

In manage folder page
- [ ] Add an "import dashboard" button/link, when clicking it should include folder identifier as querystring

**Comment by marefr** [comment]
Consider adding possibility to import as "new" dashboard, i.e. removing uid/generate a new uid. Feedback from #11064

**Comment by wombat** [comment]
Why is it not possible to import a dashboard to a folder uid? This would make it way easier to use folders and dashboards across multiple instances as the folderid always changes between installations and one currently needs to fiddle with the ids manually.

**Comment by marefr** [comment]
@wombat not sure what you're referring to. When you import dashboard through UI you get a drop down to select which folder the dashboard should be stored in. If you're talking about the HTTP API there are no import dashboard HTTP API - use the create/update dashboard endpoint for that.

**Comment by autarchprinceps** [comment]
Is it possible to import it into a folder when you do so via configmap in Kubernetes?

**Comment by marefr** [comment]
@autarchprinceps If you use provisioning you can specify a folder where dashboards should be stored see https://grafana.com/docs/administration/provisioning/#dashboards

**Comment by autarchprinceps** [comment]
@marefr Thanks for that link, but that only enables a folder on a level of dashboard provider. The configmap sidecar is setup as a single dashboard provider in the official Grafana chart, meaning I could only put all dashboards in the same folder. Yes, I could change that folder, but it would still be the same as all others, which defeats the point.
I understood your initial issue as such, that this should be configurable on the level of dashboard what folder they are for, that's why I commented on this here.

**Comment by marefr** [comment]
@autarchprinceps gotcha. The Grafana helm chart is not developed/maintained by Grafana so I suggest you to ask for help there, https://github.com/helm/charts/tree/master/stable/grafana.
