### ISSUE TITLE
Support annotations for Graphs with time shift & relative time overrides

### ISSUE THREAD

**Issue by davidhusselmann** [grafana/grafana#10805]
Version: Grafana v4.6.2 (commit: 8db5f08)
Datasource: Graphite/Carbon
OS: Ubuntu 14.04

**_Steps to reproduce:_**

1. Add a graph to the dashboard with **override relative time** of 4 hours.
1. Top right, show only last 15 minutes.
1. Create an annotation
1. Confirm annotation is visible on the graph.
1. Wait 15 minutes

**_Observed_**
The annotation is no longer visible.

**_Expected behaviour:_**
Annotation should be visible for 4 hours, even if the dashboard is filtered by the last 15 minutes.

**Comment by torkelo** [comment]
Currently annotations are global for the whole dashboard so only use the dashboard time range.

**Comment by dmhv** [comment]
For some of our use cases this would be really useful. Any updates, as it's been quite some time since last activity here?

**Comment by aocenas** [comment]
Seems like this is a duplicate of https://github.com/grafana/grafana/issues/9822
