### ISSUE TITLE
Wrong keyboard shortcut (CTRL + H)

### ISSUE THREAD

**Issue by the0ffh** [grafana/grafana#10802]
Grafana version: latest
OS: Linux

<kbd>CTRL</kbd>+<kbd>H</kbd> opens browser history instead of performing 'Hide row controls', as described in 'Keyboard shortcuts' popup.

**Comment by torkelo** [comment]
thanks for reporting this, removed it from the help modal as this is an old shortcut that is no longer there. 

if you want to hide controls do `d` `v` , will go into view/inactive mode, downside with this mode is that any mouse movement will return you to normal mode.
