### ISSUE TITLE
Permission denied when adding worldping endpoint

### ISSUE THREAD

**Issue by emourant** [grafana/grafana#10801]
Read before posting: 

Please include this information:
- What Grafana version are you using?
v4.5.0 (commit: 512535e) 

- What datasource are you using?
Worldping

- What OS are you running grafana on?
docker container

- What did you do?
I am running grafana in google's kubernetes engine. I have the following environment variables set to allow anonymous admin access

```
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
```

When I try to add a new worldping endpoint I get a popup saying "permission denied"

I also see the following message in the logs 
```
t=2018-02-06T20:36:13+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v2/endpoints/discover status=403 remote_addr=10.60.128.14 time_ms=114 size=19 referer=http://grafana.sittercity.it/plugins/raintank-worldping-app/page/endpoint-config
```

I am able to create dashboards, add datasources and perform other admin tasks.

**Comment by torkelo** [comment]
make sure your grafana.com api key is a Admin key

**Comment by ppeble** [comment]
@torkelo Thank you for taking the time to respond, this was exactly the problem. Cheers!
