### ISSUE TITLE
Cannot test alert -  Evaluator has invalid parameter

### ISSUE THREAD

**Issue by sjezewski** [grafana/grafana#10803]
Please include this information:
- What Grafana version are you using?
4.0.2 via the `grafana/grafana:4.0.2` image
- What datasource are you using?
heapster
- What OS are you running grafana on?
running on containers, via that image (I assume ubuntu)
- What did you do?
deployed grafana on k8s via these manifests (https://github.com/pachyderm/pachyderm/tree/master/etc/plugin/monitoring) ... which were just vendored in from the recommended deployment about a year ago
- What was the expected result?
When modifying the predefined 'cluster' dashboard, I was able to add an alert on the 'overall CPU usage' pane. I saved the 'cluster' dashboard successfully after this change. 

- What happened instead?
However, following the same steps for the 'overall Mem usage' pane produces an error:

```
grafana Validation failed Failed to extract alert.Reason: Evaluator has invalid parameter PanelId: 4 DashboardId: 1
```

Which shows up as a flash message on the UI when I try and 'test the alert' or when I try to save the dashboard.

![screenshot from 2018-02-06 14-09-19](https://user-images.githubusercontent.com/597953/35886879-617fefac-0b47-11e8-9056-ab042e02f775.png)

**Comment by torkelo** [comment]
Can you try upgrading to lastest stable release v4.6.3 ? Also check grafana sever log for more details.

**Comment by sjezewski** [comment]
Not sure what happened here. I've redeployed and cannot reproduce.
