### ISSUE TITLE
UX - new panel button on empty row

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1080]
For users new to grafana, it might not be obvious how to add a graph. The "Add a row" indicator is good, how about also adding on a blank row a similar "Add a panel" (or 'object' or 'graph' or whatever terminology is appropriate) to help guide the user. The row menu option on the left of the page is pretty subtle until you know to look for it. 

![2014-11-18_09-44-42](https://cloud.githubusercontent.com/assets/3671582/5085238/b54de9a2-6f07-11e4-950a-c3de24c95bfe.png)

**Comment by rmoff** [comment]
@torkelo do you think this might get added? It trips me up every time I start a blank dashboard. Thanks!

**Comment by torkelo** [comment]
not needed with new grid coming in v5
