### ISSUE TITLE
Collapsed Row functionality in 5.0.0

### ISSUE THREAD

**Issue by previousdolphin** [grafana/grafana#10800]
Prior to beta 5.0.0, the collapased row appears clean / without extraneous text:
![image](https://user-images.githubusercontent.com/27153162/35881587-4649a176-0b4f-11e8-839d-c90bffb281b5.png)

But in the current 5.0.0 Beta, there is a count of hidden panels, and options to configure/delete the row: 
![image](https://user-images.githubusercontent.com/27153162/35881551-2a41f186-0b4f-11e8-8871-31f28db309e1.png)
(also worth noting for the production release of 5.0.0: when there is one panel hidden, the description should likely display "1 hidden panel")

Having the ability to hide this information would be greatly appreciated, as unnecessary text / clutter on a dashboard can be confusing to a user (e.g. give them options / details that draw attention away from the important information).

**Comment by torkelo** [comment]
thanks for your feedback, if we get more similar feedback we will definitely consider changing this.
