### ISSUE TITLE
Grafana Graphic database, issue with metrics

### ISSUE THREAD

**Issue by Kawlesss** [grafana/grafana#10804]
Hi there,

I have an issue when I try to create a data source and then viewing the graphics associated with this datasource. I’m trying to create a Graphite database and I’m not using the port 8080 but the 8085 one.
Here’s a screenshot of my configs :
![image](https://user-images.githubusercontent.com/36199391/35886915-b03581d4-0b60-11e8-9f0d-f16f39f0802e.png)
I get an empty red alert box which is hard for me to pin point the error code.
So when I’m about to choose my Graphite database and for instance I try to write “apps” into my query I get this error message :
![image](https://user-images.githubusercontent.com/36199391/35886977-d7693c64-0b60-11e8-936d-44b07ae52a13.png)
I also configured my grafana localhost port at 8090 because I’m using 8080 for jenkins. I don’t if that can cause an issue. I appreciate any kind of help.

Also, I checked the forums, didn't find anything related (or I don't know how to search for my issue) and posted my issue on https://community.grafana.com but got no answer. 

I'm using Grafana 4.6.3
I'm using Graphite
I'm using Windows 10
View my post above for more info.
Here's the raw answer in chrome :
![image](https://user-images.githubusercontent.com/36199391/35887237-a999a2dc-0b61-11e8-8166-eae4bcf2b1a9.png)

Thanks in advance!

**Comment by torkelo** [comment]
looks like Grafana cannot reach your graphite server, please open questions on https://community.grafana.com
