### ISSUE TITLE
UX - Option to cancel/abandon panel edits

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1081]
Currently changes made to a graph in the panel editor (eg metrics selected) are permanent and instant. It would be good to have a "Cancel" or "Discard Changes" so as to be able to return to the dashboard as it was before editing the panel. Use case is wanting to do ad-hoc exploration of metrics without changing the actual dashboard (and without having to create a duplicate/sandbox version)

**Comment by mattklein123** [comment]
+1

**Comment by gitman0** [comment]
+1

**Comment by happynev** [comment]
+1

**Comment by DranonJoD** [comment]
Please, very useful if you just wanna test and don't copy the original query or queries.

**Comment by torkelo** [comment]
Implemented in 7.0
