### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Magesh29** [grafana/grafana#10812]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by Magesh29** [comment]
Hi,
I'm loading the csv data in ELK and tried creating the graph in grafana. while creating the graph the data's are populated in the graph with current date and time (i.e. 18:00:00), whereas my csv data contains from morning 7:00AM

**Comment by Magesh29** [comment]
can anyone let me know how to generate the graph and load the data from the time interval mentioned in the csv file

**Comment by marefr** [comment]
Questions should be posted to https://community.grafana.com. Closing this since this is a question
