### ISSUE TITLE
"doInit is not a function" in Grafana 5

### ISSUE THREAD

**Issue by lfdominguez** [grafana/grafana#10811]
Hello, great work with Grafana 5, I am using it and looks great. My question is about a plugin that I want to use (https://github.com/MarcusCalidus/grafana-svg-panel), sorry for post my question here but I need make to work.
That plugin works great with stable version (4.6) of grafana, but when I try to use in 5 then the plugin show a message about a "doInit" function. So in grafana 5 there is an API change for plugins????

![](https://user-images.githubusercontent.com/5604131/35884760-a4a3262a-0b59-11e8-84bd-55e5b5b55b9a.png)

**Comment by torkelo** [comment]
most panels will work, this looks like a bug in https://github.com/MarcusCalidus/grafana-svg-panel , trying to add functions to the peristed panel model is not allowed (and never have)
