### ISSUE TITLE
Scrolling is non-native and doesn't match other sites / programs

### ISSUE THREAD

**Issue by bpbp-boop** [grafana/grafana#10810]
There seem to be a few issues with scrolling in Grafana, tested in both Firefox and Chrome
1. the lines scrolled per mousewheel/keyboard up/down doesn't respect the browser/os settings
2. middle click scroll (aka autoscroll) doesn't work
3. the scroll bar is non-native and hard to use because of its small size 

Would it be possible to add a pref to use the browser's native scrolling instead of re-implementing it? 

- What Grafana version are you using?
 Grafana v5.0.0-beta1 (commit: 3e2da1f)

**Comment by torkelo** [comment]
reason is that the native scrollbars look horrible and take up space, 
![image](https://user-images.githubusercontent.com/10999/35908959-720d0cbe-0bf2-11e8-9292-67df9531e95f.png)

Only chrome allows you to style them. We will return to native scrollbars when overlay scrollbars become a standard (only available as an experimental feature in chrome)

**Comment by bpbp-boop** [comment]
Would you consider a PR that replaces the 'perfect-scrollbar' with https://github.com/Diokuz/baron ?

**Comment by torkelo** [comment]
what would be the advantage? perfect scrollbar is better supported and worked a lot better, think I did a tested baron, did not find it as good as perfect scrollbar. But your happy to try to replace it if you can get all scenarios to work. perfect scrollbar also uses native mechanics.

**Comment by bpbp-boop** [comment]
All the issues listed here, basically: https://github.com/utatti/perfect-scrollbar/wiki/Caveats
Basically it seems perfect-scrollbar emulates scrolling while baron hides the native scrollbar, lets the browser handle scrolling and you can then style your own custom one. 

I'll have a play with replacing and see if it's suitable!

**Comment by torkelo** [comment]
Not sure, think they use the exact same method
