### ISSUE TITLE
Bug (v5-beta1): folder api has no org checks

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10820]
This api `/api/dashboards/folders` returns folders from other orgs!

**Comment by daniellee** [comment]
Sorry about that. Added an orgid to GetDashboardPermissionsForUser query but forgot on the folders endpoint. Also missing a test for this.

**Comment by torkelo** [comment]
think it has OrgId, just not being used when your org role is Admin

**Comment by daniellee** [comment]
yes, you're right. Will have a fix in a minute

**Comment by torkelo** [comment]
np, been thinking about the SQL permissions query checks and how we can reuse and simplify them (and fix them), for example: https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/search_builder.go#L182 

is a bit buggy as the org role check does not join on user id, but we can't join on user id when checking role as api keys and anonymous users have a role but not user id. So think we need to add role as an input to query (instead of checking user role via org_user). But a bit problematic that the Role is string and not numeric (so greater then checks are tricky)

**Comment by daniellee** [comment]
Will add multiple org tests to all the routes next week.
