### ISSUE TITLE
Encrypt Data Source Basic Auth in DB

### ISSUE THREAD

**Issue by zarakay** [grafana/grafana#10827]
As part of compliance at the company I work I need to know how Grafana handles passwords and keys. I had a vague look at the code and I can see that usernames and passwords are stored in the database encrypted. However I have noticed that the credentials for each data source is stored unencrypted (as far as I can tell). 

This issue is to confirm whether this is actually the case and to also see if it would be possible to store these credentials encrypted. 

Please include this information:
- What Grafana version are you using?

4.6.3

- What datasource are you using?

Any data source with Basic auth enabled

- What OS are you running grafana on?

MacOS for dev, Linux in Prod

- What did you do?

Added basic auth to data source

- What was the expected result?

data source credentials are stored in database encrypted

- What happened instead?

data source credentials are stored in database unencrypted

**Comment by torkelo** [comment]
most other options are encrypted (certs & client secrets) but this was added in the beginning when we did not have a good solution for encrypting data source settings.

**Comment by mliyanagamage** [comment]
Any plan to migrate these fields onto the new encrypted system?

**Comment by torkelo** [comment]
we definitively want to, not sure when we will have time

**Comment by marioizquierdo** [comment]
+1 same problem here. I was very happy when I found out about the Postgres Datasource, that made super easy to visualize our own time-series data. But I can not push the idea in my company because we have a policy to only store encrypted passwords 😢

**Comment by marefr** [comment]
@marioizquierdo postgres datasource stores the password encrypted

**Comment by marioizquierdo** [comment]
@marefr That is great news, thanks!

I realize I was confused by the description:
> (...) However I have noticed that the credentials for each data source is stored unencrypted (...)

But I realize now this was probably about Basic Auth. I made a local installation to see how things look like in the Grafana DB, made a new Postgres Datasource and inspected the `data_source` table. No trace of the plain password 👍

Sorry for confusing the thread. Is there anywhere in the documentation where explains how passwords are stored for different datasources?

**Comment by marefr** [comment]
The only possible documentation that somewhat explains this is the [provisioning of datasources](http://docs.grafana.org/administration/provisioning/#datasources) if you read the *Secure Json Data* heading.

**Comment by aocenas** [comment]
There are actually multiple places where the handling of passwords is not ideal. MySql and Influx datasource and also the mentioned basicAuth. I am going to try to unify those places so all passwords are stored in the secureJsonData format instead of plain text.

**Comment by torkelo** [comment]
We need to think about how to do this with minimal breaking changes as well. Another note basicAuth in Browser access mode cannot use encryption. 

There are 2 data source password fields currently (Password, and BasicAuthPassword). We can encrypt them in DB and not return them in api. Any other alternatives?

**Comment by aocenas** [comment]
@torkelo I think this can be done basically without any breaking change. We already use secureJsonData to store things that need to be encrypted on the server. So we would just mark password and basic_auth_password columns as deprecated so hopefully people will not use them to store passwords going forward. In `frontendsettings.go#getFrontendSettingsMap` we will need to send secureJsonData back unencrypted for datasources that use direct access so they can pull out passwords and use it to do the requests. For proxy access there should by no need to send secureJsonData to front end.

This would mean we will have to still send the passwords plaintext during FE init for the direct datasources but at least it will be encrypted on the server so I think there is a benefit in that and should resolve this issue.

So this would be backward compatible and basically an opt in behaviour.

Maybe one question is whether we should send whole secureJsonData decrypted for direct datasources or add some option there to say which fields to send, but I assume there is not benefit in having some server only data when you want direct access behaviour.

**Comment by torkelo** [comment]
>  In frontendsettings.go#getFrontendSettingsMap we will need to send secureJsonData back unencrypted for datasources that use direct access so they can pull out passwords and use it to do the requests. For proxy access there should by no need to send secureJsonData to front end.

don't think you need to do that, just need to set basicAuth property (basic auth header defined in frontendsettings). But will probably need to decrypt password and set that in dsMap['password'] or risk breaking some data source plugins, but not sure.

**Comment by aocenas** [comment]
Issue is that Influx datasource actually can use both password or basicAuthPassword for direct access (in case of password it will send it as query param I think). So seems to me it would be better to just do the decryption for whole secureJsonData rather than pick specific properties and just have it as an API (hopefully documented) so to speak, that can be used by plugins to encrypt any values, while still allow both direct and proxy access pattern.

**Comment by aocenas** [comment]
But yeah now I see that we do:
```
dsMap["basicAuth"] = util.GetBasicAuthHeader(ds.BasicAuthUser, ds.BasicAuthPassword)
```
on the backend which means we would have to know whether the `BasicAuthPassword` is in the column or in the secureJsonData, I thought it can be left to the plugin to decide where it takes the creds from. We could still just check which one of them is not null though and use that one.
