### ISSUE TITLE
Grafana 4.1.1 improper error handling Information disclosure security vulnerability 

### ISSUE THREAD

**Issue by rakesh-patnaik** [grafana/grafana#10828]
- What Grafana version are you using? 4.1.1
- What datasource are you using? influxdb
- What OS are you running grafana on? ubuntu14.04
- What did you do?
edit cookie and post curl as follows:

curl 'https://localhost:3000/login' -H 'Origin: https://localhost:3000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://localhost:3000/login' -H '**Cookie: grafana_sess=%00**' -H 'Connection: keep-alive' --data-binary '' --compressed -v

returns HTTP500 with the following runtime error:

              <div class="page-container">
                        <div class="page-header">
                                <h1>
                                        Server side error :(
                                </h1>
                        </div>

                        <h4>**runtime error: index out of range**</h4>

                        <pre></pre>

                </div>

- What was the expected result?
response should not show runtime errors. This might lead to information disclosure vulnerabilities.
https://www.owasp.org/index.php/Information_Leak_(information_disclosure)

- What happened instead?
response included a "index out of range error" 

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by bergquist** [comment]
```bash
curl 'http://localhost:3000/login' \
    -H 'Origin: http://localhost:3000' \
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'Accept-Language: en-US,en;q=0.9' \
    -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' \
    -H 'Content-Type: application/json;charset=UTF-8' \
    -H 'Accept: application/json, text/plain, /' \
    -H 'Referer: https://localhost:3000/login' \
    -H 'Cookie: grafana_sess=%00' \
    -H 'Connection: keep-alive' --data-binary '' --compressed -v

```
