### ISSUE TITLE
Bug (v5.0-beta1) User picker on permission page shows users from other orgs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10824]
The user picker shows users that are not part of the org. 

![image](https://user-images.githubusercontent.com/10999/35929166-22f1be4e-0c2f-11e8-9ffb-0267cf42ace1.png)

**Comment by marefr** [comment]
This is of course not good, but what's also bad is that you can actually select a user from another organization and save the permissions without any problems. This should also be fixed in this issue.
