### ISSUE TITLE
Alerts / Notifications disappear after pod restart

### ISSUE THREAD

**Issue by sjezewski** [grafana/grafana#10825]
- What Grafana version are you using?
4.0.2
- What datasource are you using?
heapster/influxdb
- What OS are you running grafana on?
I'm using the grc.io grafana-heapster-amd64 iamge at version 4.0.2 ... which I assume is based on ubuntu
- What did you do?
I setup an alert + notification. Then I killed the grafana pod.
- What was the expected result?
My alert + notification settings would still be in place when the new pod started up.
- What happened instead?
My alert + notification settings were gone.

This seems like a deal breaker for using grafana for monitoring in production. If my cluster gets saturated and the pod gets evicted (or simply rescheduled), I'll lose all of the monitoring/alert/notifications I've setup!

I must be missing something. Is there a recommended way for persisting this state?

**Comment by bergquist** [comment]
@sjezewski you need configure Grafana to use an external mysql/postgre or mount the grafana.db into the container.
