### ISSUE TITLE
PostgreSQL/JSONb: Invalid type for column time, must be of type timestamp or unix timestamp

### ISSUE THREAD

**Issue by jdavid** [grafana/grafana#10826]
Grafana 5.0.0-beta1 on Ubuntu Artful installed from https://packagecloud.io/grafana/testing/debian/
Datasource: PostgreSQL 9.6

I have a table with a field named "json" of type jsonb. Values in the json field look like
``{'value': 78, 'tst': 1518019200}``

Then, the graph defined as:

    SELECT
      (json->>'tst')::int4 as time,
      (json->>'value')::int4 as value
    FROM table
    WHERE ...

Raises the error: *Invalid type for column time, must be of type timestamp or unix timestamp*
Expected to work.

If I change to a timestamp I get the same error: ``to_timestamp((json->>'tst')::int4)``. The documentation says that both timestamps and numeric values should work.

Variables work fine with the json field.

**Comment by svenklemm** [comment]
Hmm ``` SELECT (json->>'time')::int as time, (json->>'value')::int as value FROM t_json ```
works for me (with int4 too). I dont see why your query shouldnt work. 
Is 'tst' set in every row of the table you are returning?
Can you enable debug logging and check if anything shows up in the error log.

**Comment by jdavid** [comment]
There were some nulls. Thanks!
