### ISSUE TITLE
Grafana 4x and 5-beta login redirect

### ISSUE THREAD

**Issue by cscheuermann81** [grafana/grafana#10829]
Grafana has a "hidden" feature - redirect on login.

The problem is, that a attacker can add a cookie to the browser and perform a redirect after login process and can perform a man-in-the-middle-attack.

The problem was seen in Grafana 4.4.3, 4.6.2 and 5 beta (I haven't check the other versions but I think you can find the bug in also other versions)

The bug exists when logging on - the used datasource isn't interessting :-)

I check the bug in Linux and Windows, in Google Chrome, Firefox and IE.

What did I do:
- Go to Grafana login page
- Open developer tools
- Go to console
- Enter: document.cookie="redirect_to=https://grafana.org"
- Login in
- Result: you are redirected to https://grafana.org
- Expected: I expect that grafana give me a hint or better I choice if I realy want to be redirected to this

**Comment by torkelo** [comment]
can validate the cookie is same domain and ignore it otherwise

**Comment by bergquist** [comment]
Setting the cookie as httpOnly and only redirect using httpOnly should be enough. We never modify `redirect_to` in the frontend

**Comment by torkelo** [comment]
yes, your right, it looks like it is only used in the backend, was sure that this was also in the frontend.
