### ISSUE TITLE
Bug (v5-beta1) GitHub Login

### ISSUE THREAD

**Issue by Xopherus** [grafana/grafana#10823]
I'm using the new v5 beta with the github auth plugin.

Here's our config:
```
[auth.github]
enabled = true
allow_sign_up = true
client_id = ${github_client_id}
client_secret = ${github_client_secret}
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
team_ids = ${github_team_id}
allowed_organizations = ${github_team_name}
```

When a user (who belongs to the github organization) attempts to login we receive:

![image](https://user-images.githubusercontent.com/6126813/35924229-7732115a-0bf0-11e8-8cf9-737770e4996f.png)

I was able to get some info from the logs:

```
t=2018-02-07T14:51:24+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=10.x.x.x. time_ms=0 size=304 referer=https://grafana.mydomain.com/login
t=2018-02-07T14:51:25+0000 lvl=eror msg="User not a member of one of the required organizations" logger=context userId=0 orgId=0 uname=
```

**Comment by DanCech** [comment]
Have you verified that the `${github_team_name}` in your config matches your github organization?  If you are using `team_ids` then you can also just set `allowed_organizations =` since you're already restricting by team id which is more specific anyway.

**Comment by Xopherus** [comment]
Yep, I've verified that. Those have not changed during the upgrade. 4.6 was stable with that configuration, the 5.0 beta is not.

**Comment by Xopherus** [comment]
This seems to be related to the changes in #10112, specifically if your user is a member of a private GitHub org. 

I can lookup my user to get the organizationURL [seen here](https://github.com/grafana/grafana/blob/3d1c624c12e16da69e9fd1be66173c96502e69a6/pkg/social/github_oauth.go#L201)

```
curl -H "Authorization: token foobar" https://api.github.com/user

{
  "login": "Xopherus",
  "organizations_url": "https://api.github.com/users/Xopherus/orgs",
  "type": "User",
  "email": "craborg57@gmail.com"
}
```

Then if I curl the `organization_url` returned in that response, I don't get back all of the orgs I belong to.
```
curl -H "Authorization: token foobar" https://api.github.com/users/Xopherus/orgs

[
  {
    "login": "zerofox-oss",
    "url": "https://api.github.com/orgs/zerofox-oss",
  }
]
```

It seems like we should be using [GET /user/orgs](https://developer.github.com/v3/orgs/#list-your-organizations) instead of [GET /user/:user/orgs](https://developer.github.com/v3/orgs/#list-user-organizations). That way if you're running Grafana with a private GitHub org you can still login.

**Comment by IngmarStein** [comment]
We've just updated from 4.6.3 to 5.0.0 beta 3 and GitHub authentication now results in the "User not a member of one of the required organizations". The configuration is supplied through environment variables and is unchanged from the previous version which authenticated successfully.

**Comment by inish777** [comment]
@IngmarStein @torkelo I'll investigate it and fix in 24 hours

**Comment by pesimon** [comment]
Seeing same issue here with priv Github Org and 5.0.0-beta4

**Comment by torkelo** [comment]
fix is coming in beta5 (or get it now in nightly build), reverted the https://github.com/grafana/grafana/issues/10823  change that caused the issue

**Comment by pesimon** [comment]
Just checked Grafana v5.0.0-beta4 (commit: 3964d6b) but still 
`t=2018-02-20T15:47:26+0000 lvl=eror msg="User not a member of one of the required organizations" logger=context userId=0 orgId=0 uname=` unfortunately.

**Comment by pesimon** [comment]
#11028 works. thx a lot
