### ISSUE TITLE
Grafana/Graphite Query Question

### ISSUE THREAD

**Issue by TiepelPa** [grafana/grafana#10839]
Please include this information:
- What Grafana version are you using?
4.6
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 7

Hello there,
this isn't really an Issue, rather than a Question. Is there any way to filter hosts through their metrics? My problem is that I want to make some dashboards on one Server for a lot of hosts. One dashboard for simple metrics, which every host should have and some with special metrics (like metrics for MySQL or Apache Server). I'm using the Graphite Query already but every host has a similar name so you can't filter them through their name and I don't want to have an empty Dashboard because it's not a MySQL Server. Is there a way to do this?

Thanks

**Comment by torkelo** [comment]
please use community site for questions (https://community.grafana.com)
