### ISSUE TITLE
grafana 5.x beta1 not able to scroll on table (device ipad)  

### ISSUE THREAD

**Issue by manojown** [grafana/grafana#10836]
I'm not able to scroll on table panel with any ipad (touch event).
i try out with different size ipad and also with safari and chrome but its doesn't work.

**Comment by torkelo** [comment]
Did this work before? We have not changed the scrolling for the table panel.

**Comment by marefr** [comment]
We tried in emulated mode in chrome yesterday and was able to reproduce it. Then we tried again and then it worked. Very strange.

**Comment by manojown** [comment]
Actually this is very strange because when i try in emulate mode in chrome its work superbly but when i try in specific  ipad then its not work . At starting i think may issue of chrome so i update this and try out but won't work and also try out in safari but my bad.
**I think you need to try in specific device . (Ipad mini , ipad )**
**Note - I try this in iPhone 6s and is work fine.**

grafana version - **grafana_5.0.0-11686beta1**

**Comment by daniellee** [comment]
I think this is fixed by #11456 but I can reopen if this is still a problem. Tested on iPhones and on MacOS.

**Comment by martintamke** [comment]
Hello 
The scroll Bar does not appear With grafana v5.1.4 on iPad with iPados v 13.1 
Is this issue solved in Grafana v6 ?

**Comment by marefr** [comment]
@martintamke yes they should be solved
