### ISSUE TITLE
CloudWatch statistic

### ISSUE THREAD

**Issue by dimakievua** [grafana/grafana#10837]
- What Grafana version are you using?
5.0.0-11596pre1 
- What datasource are you using?
CloudWatch
- What OS are you running grafana on?
RHEL 7.4
- What did you do?
Try to build graphs using cloudwatch as data source
- What was the expected result?
Build graphs for all services I use on AWS 
- What happened instead?
Data for some services fetch correctly. I can build graphs ECS (domain, not service), ELB, EC2, SQS. But most of data absent - ECS services, CloudFront, DynamoDB, ES, S3. For some services I can see dimensions, it fetch entities name (ES domains for example), for some no even such info.    There are no error logs in log files regarding this. 
- If related to metric query / data viz:
Probably mapping in data source. I didn't try specific query, just fetch data.
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
  AWS ES request:
{"from":"1518001635977","to":"1518088035977","queries":[{"refId":"A","intervalMs":60000,"maxDataPoints":1367,"datasourceId":2,"type":"timeSeriesQuery","dimensions":{"DomainName":"elastic-test"},"metricName":"CPUUtilization","namespace":"AWS/ES","period":"60","region":"eu-west-2","statistics":["Average"]}]}

Response:
{"results":{"A":{"refId":"A","series":[{"name":"CPUUtilization_Average","points":[],"tags":{"DomainName":"elastic-test"}}],"tables":null}}}

I understand this data source is new and version 5.0.0 is not released yet, but this data source looks quite promising so I want to help at this stage.

**Comment by torkelo** [comment]
please use community site for questions. 

Not sure why your not getting data for all your metrics, maybe you have to enable them in Cloudwatch (some metrics you need to enable/pay for)

**Comment by dimakievua** [comment]
Hi @torkelo,
Not sure it's "How to ..." type of question. I can see all the metrics in CloudWatch page. I can see my domain name in AWS/ES items in Grafana. I use admin account to fetch data during test integration. Also I can see a lot of data for some metrics, just part of them missing. Could you please have a look at this issue? What kind of logs could I provide to you?

**Comment by dimakievua** [comment]
UPD:
Try to fetch data with AWS CLI and get the same result as Grafana. Some Metrics available in CLI, some not. Will dig at AWS side.
