### ISSUE TITLE
Moving objects across rows destroys the arrangement

### ISSUE THREAD

**Issue by dschade2016** [grafana/grafana#10831]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
**Grafana v5.0.0-beta1 (commit: 3e2da1f)** 
- What datasource are you using?
**No.**
- What OS are you running grafana on?
**Docker Repo - grafana/grafana:latest**
- What did you do?
**Add and move objects like Graph/Single Stat.**
- What was the expected result?
**That the view is preserved.**
- What happened instead?
**The arrangement was destroyed. Objects that were previously in a row are now in a different row.**
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

![fatadventurousgrayfox-size_restricted](https://user-images.githubusercontent.com/23652401/35961743-ff079690-0cae-11e8-805f-aadccdd7778a.gif)

**Comment by torkelo** [comment]
not seeing anything wrong in the image. Your moving a panel down a row, and it will push the panel there down.

**Comment by dschade2016** [comment]
Pls. show the second part of the image. You can see that graph four now in row two. Before it was in row three.

**Comment by torkelo** [comment]
ah, sorry missed the bottom of the dashboard.

**Comment by torkelo** [comment]
T

**Comment by torkelo** [comment]
@alexanderzobnin this is probably an issue in the grid component, 

maybe here:
https://github.com/STRML/react-grid-layout/blob/master/lib/utils.js#L180 

I added tests to that lib to replicate the issues:
https://github.com/STRML/react-grid-layout/blob/master/test/spec/utils-test.js#L289

To develop the grid component, just git clone the project somwhere then.  type `yarn link` in the grid layout component repo directly. Then in Grafana type `yarn link react-grid-layout` to use your local dev version of react grid.

**Comment by alexanderzobnin** [comment]
Seems, this caused by `react-grid-layout` bug https://github.com/STRML/react-grid-layout/issues/714
