### ISSUE TITLE
Alerting with Elastic search not working properly 

### ISSUE THREAD

**Issue by sandeepdev92** [grafana/grafana#10833]
![grafana_alert2](https://user-images.githubusercontent.com/36206764/35964077-a91fceae-0cdc-11e8-89b4-cf73931186cc.jpg)

i configured Grafana alert with elastic search and its execute on every 5 min but i got unwanted alert on every morning at the same time.find attached image for the same.

elastic search pattern-daily basis 

![grafana_alert](https://user-images.githubusercontent.com/36206764/35963742-b1a47cce-0cdb-11e8-9320-15c544543fdb.jpg)

**Comment by imatpro** [comment]
Hi, 

The alerting on elasticsearch datasource doesn't working in 5.0.0-beta1

"The datasource does not support alerting queries"

Thanks for helping

**Comment by sandeepdev92** [comment]
Hi
 i m using Grafana v4.4.1  and elastic search  5.x . 
my question is alerting queries working ??

**Comment by imatpro** [comment]
Elastic Search datasource does not support alerting queries in 4.X.X

In lastest stable 4.6.3 does working to, hope in 5 stable working

**Comment by torkelo** [comment]
Elasticsearch alerting is not supported yet, might come in v5.1

**Comment by sandeepdev92** [comment]
then how it is showing alerting in Grafana v4.4.1 with elastic search 5.x in the below schreenshots.
![image](https://user-images.githubusercontent.com/36206764/35966835-01dcd80e-0ce5-11e8-8f8b-766b170cb36f.png)

**Comment by sandeepdev92** [comment]
please comment

**Comment by torkelo** [comment]
Maybe you used a custom build that merged the ES PR? Or changed data source from a supported dasource to elasticseach

**Comment by sandeepdev92** [comment]
i am using ES of AWS please find below data-source config for the same
![image](https://user-images.githubusercontent.com/36206764/35972862-6ce74800-0cf9-11e8-9dcf-65ea557ff334.png)

**Comment by sandeepdev92** [comment]
please comment

**Comment by marefr** [comment]
If you navigate to a page that isn't a dashboard you should be able to find a commit at the bottom - please paste that here.

**Comment by sandeepdev92** [comment]
![image](https://user-images.githubusercontent.com/36206764/35988954-e43f27ca-0d25-11e8-86fd-5bf70a5dd076.png)

**Comment by sandeepdev92** [comment]
hi Marefr please find above image for the same

**Comment by torkelo** [comment]
Alerting has never ever worked in any version of Grafana, you must have had another data source used in the alert rule or some way gotten a alert history event.
