### ISSUE TITLE
Unable to migrate grafana db(4.4.1) to  grafana 4.6.3

### ISSUE THREAD

**Issue by sandeepdev92** [grafana/grafana#10830]
t=2018-02-08T05:32:53+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-02-08T05:32:53+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-02-08T05:32:53+0000 lvl=info msg="App mode production" logger=settings
t=2018-02-08T05:32:53+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana-server.pid pid=4753
t=2018-02-08T05:32:53+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-02-08T05:32:53+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-02-08T05:32:53+0000 lvl=info msg="Executing migration" logger=migrator id="Add last_seen_at column to user"
t=2018-02-08T05:32:53+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Add last_seen_at column to user" error="attempt to write a readonly database"
t=2018-02-08T05:32:53+0000 lvl=eror msg="Exec failed" logger=migrator error="attempt to write a readonly database" sql="alter table `user` ADD COLUMN `last_seen_at` DATETIME NULL "
t=2018-02-08T05:32:53+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: attempt to write a readonly database\n"

**Comment by torkelo** [comment]
Grafana needs write access to the disk/volume where database is located
