### ISSUE TITLE
Allow entire configuration to be version controlled

### ISSUE THREAD

**Issue by rickardp** [grafana/grafana#10846]
The use of SQLite to back configuration is not well suited for immutable deployment scenarios.

Ideally, if everything would be stored in editable json, one could configure Grafana locally, check in and deploy.

A solution that might be easier to implement is to use something like JSONDB. The files are not exactly Ho-nan creatable but reasonably easy to diff and merge.

We can’t be talking about huge data quantities here, can we?

**Comment by torkelo** [comment]
Grafana supports MySQL and Postgres as well for large high availability setups. Grafana needs a real database to store user preferences, user annotations (graph comments), user dashboard favorites, meta analytics, alert history, alert state, ldap sync information, the list goes on. It could not use something as simple as a json file as main db :) 

In Grafana v5.0 we introduce a new provisioning feature that enabled you to setup data sources and dashboards, and we will extend that to more things in the future:

http://docs.grafana.org/v5.0/guides/whats-new-in-v5/#data-sources

**Comment by rickardp** [comment]
I understand there are many use cases for Grafana, but I think there is a substantial user base that are only interested in a stateless dashboard, basically with only a guest user and an admin that can create and edit dashboards.

But it sounds like this will be handled in 5.0, so I'm keeping my fingers crossed that will solve it.

**Comment by torkelo** [comment]
yes, stateless dashboards will be supported, Grafana will sync dashboards on disk to it's main database.
