### ISSUE TITLE
Feature Request: Change base amount of tiles per row in row editor

### ISSUE THREAD

**Issue by DanielChristow** [grafana/grafana#10847]
Read before posting: 
Please include this information:
- What Grafana version are you using? 4.6.3
- What OS are you running grafana on? Ubuntu 16.04.3

The request:
- Please consider adding configurable tile amounts per row in Grafana. I'm speaking of the default 12 tiles wide being configurable to any number you set, with the user's intelligence being the guiding force on limit and appearance.

For example, with a dashboard I'm building, a system has 11 nodes: a load balancer, ui node, and 9 app nodes. Another platform that I'm dashboarding has 13 nodes: a front end load balancer, 6 ui nodes, a back end load balancer, and 5 db nodes. 

If this is already a feature, I was unable to find how to configure it quickly with either online documentation or poking around the UI + config files. 

Thanks Torkelo! You and team been doing an amazing job and buy-in on this product is ever increasing in my organization. Keep up the great work!

**Comment by torkelo** [comment]
In Grafana v5.0 we are getting rid of the row concept (it still there for backward compatibility) the new grid engine is much more flexible and enables new layouts, it's also using 24 columns: 
https://www.youtube.com/watch?v=Izr0IBgoTZQ
