### ISSUE TITLE
It shouldn't be possible to add permission of user/team that don't exists

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10842]
It shouldn't be possible to add dashboard permission of user/team that don't exists at all or in organization where dashboard are saved.

**Comment by marefr** [comment]
https://github.com/grafana/grafana/blob/d4f74cbb90aeb5d552ad86e247b002d7d1e0e1d3/pkg/services/guardian/guardian.go#L48-L59

https://github.com/grafana/grafana/blob/d4f74cbb90aeb5d552ad86e247b002d7d1e0e1d3/pkg/services/guardian/guardian.go#L109-L127

https://github.com/grafana/grafana/blob/d4f74cbb90aeb5d552ad86e247b002d7d1e0e1d3/pkg/services/guardian/guardian.go#L129-L141

**Example:**
Issues may arise with above code that checks if user has admin role first
- Org A and Org B exists
- A user U is admin in Org A and viewer in Org B
- A dashboard D exists in Org B with the following permissions
  - Everyone with Admin Role Can Admin	
  - Everyone with Editor Role Can Edit
- If user U using the dashboard acl api for dashboard D and the organization A he can execute GET/POST/DELETE since he is actually an admin user

For example user U can send the following request which will result in that he can admin the dashboard:
```http
POST /api/dashboards/id/192/acl HTTP/1.1
Host: localhost:3000
X-Grafana-Org-Id: 2
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0
Cache-Control: no-cache
Postman-Token: 50e4bbb6-b314-596c-d055-6cbd7f6d577b

{
  "items":[
    {
      "id":null,
      "userId":0,
      "teamId":0,
      "role":"Viewer",
      "permission":4
    }
  ]
}
```

The same example should be applicable for folders as well

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
