### ISSUE TITLE
PostgreSQL datasource does not correctly expand timeFilter on variable template

### ISSUE THREAD

**Issue by miceno** [grafana/grafana#10848]
Grafana v4.6.3 (commit: 7a06a47)
 PostgreSQL datasource
 Server: CentOS 7
 Client: MacOS X

I am creating a template variable to hold a set of values, filtered by __timeFilter.

The query is:
`SELECT distinct message ->> 'device_id'  from  sns_log_testing WHERE MESSAGE ->> 'app_package' IN ($app_package) and $__timeFilter(received)`

where `received` is a "timestamp with time zone" field.

I would expect a list of devices names.

I only get an empty list.

The returned query expands `TO` and `FROM` to 0 (see below).

Request HEADERS:
```
POST /api/tsdb/query HTTP/1.1
Host: dev-sns-main-02.hi.inet
Connection: keep-alive
Content-Length: 237
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: http://dev-sns-main-02.hi.inet
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: http://dev-sns-main-02.hi.inet/dashboard/db/orestes-tests?orgId=1&editview=templating
Accept-Encoding: gzip, deflate
Accept-Language: es,en;q=0.9,ca;q=0.8,en-US;q=0.7
Cookie: _ga=GA1.2.253716511.1447678515; grafana_user=admin; grafana_remember=fb22c7aba68d3cb56be306ac80c24902bfe21fe0d97cd2a80cfe4bffc7eb644891; grafana_sess=1fa6691a46966ab0
```

Request payload
```
{
  "queries": [
    {
      "refId": "device",
      "datasourceId": 1,
      "rawSql": "SELECT distinct message ->> 'device_id'  from  sns_log_testing WHERE MESSAGE ->> 'app_package' IN ('com.telefonica.BoredomFighter') and $__timeFilter(received)",
      "format": "table"
    }
  ]
}
```

Response:
```
{
  "results": {
    "device": {
      "refId": "device",
      "meta": {
        "rowCount": 0,
        "sql": "SELECT distinct message ->> 'device_id'  from  sns_log_testing WHERE MESSAGE ->> 'app_package' IN ('com.telefonica.BoredomFighter') and extract(epoch from received) BETWEEN 0 AND 0"
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "?column?"
            }
          ],
          "rows": [
            
          ]
        }
      ]
    }
  }
}
```

If I remove timeFilter, I will received all the values.
``` 
 Request payload
 
 {
   "queries": [
     {
       "refId": "device",
       "datasourceId": 1,
       "rawSql": "SELECT distinct message ->> 'device_id'  as device from  sns_log_testing WHERE MESSAGE ->> 'app_package' IN ('com.telefonica.BoredomFighter')",
       "format": "table"
     }
   ]
 }
```

Response:
```
{
  "results": {
    "device": {
      "refId": "device",
      "meta": {
        "rowCount": 333,
        "sql": "SELECT distinct message ->> 'device_id' as device from  sns_log_testing WHERE MESSAGE ->> 'app_package' IN ('com.telefonica.BoredomFighter')"
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "device"
            }
          ],
          "rows": [
            [
              "A6C9EC5E-40E7-4FDD-9E5A-27CE69E0533B"
            ],
            ...
            [
              "C5C4B1D1-0048-4A5C-B9C8-7129C2AEE51C"
            ],
            [
              "C5C4B1D1-0048-4A5C-B9C8-7129C2AEE51C"
            ]
          ]
        }
      ]
    }
  }
}
```

**Comment by svenklemm** [comment]
Seems like timerange context is not passed along in your query. In what context is this query executed? If its a template query you need to select refresh on timerange change. 
See https://github.com/grafana/grafana/issues/10066
This fix is only in nightly versions or 5.x beta though.

**Comment by brylie** [comment]
I am having this issue, but not using a template query. The values from the time range selector are not passed in to the SQL query. When I inspect the query, I see the raw string `where $__timeFilter(created)`.

**Comment by marefr** [comment]
@brylie $__timeFilter(created) will be converted to proper sql in the baclend before the query is sent to the database, i.e. `WHERE created BETWEEN <start> AND <end>`.

**Comment by brylie** [comment]
@marefr that is what I was expecting. However, when looking at the `rawSql` I see the time macro directly. I.e. it is not expanded to the expected result from the documentation.

**Comment by marefr** [comment]
@brylie Not sure what you mean, but maybe this makes it more clear? 

![image](https://user-images.githubusercontent.com/1668778/45096517-00304280-b121-11e8-9163-cbb2830c04d5.png)

The generated sql is generated in the backend
