### ISSUE TITLE
Provisioning yaml/json format to use camelCase for properties 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10859]
The http api & dashboard json is using camelCase so becomes very inconsistent that the yaml settings use underscore as separator.

**Comment by torkelo** [comment]
It's even inconsistent in the examples, 
![image](https://user-images.githubusercontent.com/10999/36028547-b4df188a-0d9f-11e8-80b3-4540e751ebcc.png)

This will be a breaking change for all who tried it before stable, but think it's worth it to get a consistent solution. We could try to support both formats if we are afraid to break stuff for people who already tried this feature.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10896
