### ISSUE TITLE
Grafana MySQL database Issue

### ISSUE THREAD

**Issue by TiepelPa** [grafana/grafana#10852]
Please include this information:
- What Grafana version are you using?
4.6
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 7
- What did you do?
Changed MySQL to main Database
- What was the expected result?
for it to work
- What happened instead?
grafana doesn't start: msg= "Failed to parse /etc/grafana/grafana.ini, missing closing key quote from grafana:password@mysql-server

hi there,

I tried to setup grafana to use MySQL as grafana's main Database but it didn't work. First I created a database with the name 'grafana' and gave it usage on my MySQL-Server. Then i created a table:
mysql> create table `session` (
    -> `key`   char(16) not null,
    -> `data`  blob,
    -> `expiry` int(11) unsigned not null,
    -> primary key (`key`)
    -> ) ENGINE=MyISAM default charset=utf8;
Query OK, 0 rows affected (0.01 sec) 

I restarted grafana-server.service and it didn't work. 

msg= "Failed to parse /etc/grafana/grafana.ini, missing closing key quote from grafana:password@mysql-server

Thanks

**Comment by torkelo** [comment]
you do not need to create the session table, grafana will do that for you. 

Your Grafana ini file cannot be parsed. Please use community site for questions
