### ISSUE TITLE
Stacked values displayed incorrectly

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#10857]
Please include this information:
- What Grafana version are you using? **v5.0.0-beta.2**
- What datasource are you using? **InfluxDB: `InfluxDB shell version: 1.3.6`**
- What OS are you running grafana on? **Ubuntu 17: `Linux cncftest.io 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`**
- What did you do?
Displaying dashboard with stacked values, values are sparse, but "null as zero" is selected, some values appear like flying (they don't touch the bottom):
![screen shot 2018-02-09 at 13 00 58](https://user-images.githubusercontent.com/2469783/36027034-dcc6c920-0d99-11e8-8c20-9ea76661154f.png)
![screen shot 2018-02-09 at 13 01 03](https://user-images.githubusercontent.com/2469783/36027035-dce7b806-0d99-11e8-8df1-8230c6a253fd.png)
![screen shot 2018-02-09 at 13 06 15](https://user-images.githubusercontent.com/2469783/36027089-0a22298c-0d9a-11e8-9714-5f24f7515409.png)

Happens here: https://cncf.cncftest.io/d/000000012/issues-repository-group?orgId=1&from=now-90d&to=now&var-period=d&var-repogroup_name=cncf%2Fdevstats&var-repogroup=cncf_devstats
 
- What was the expected result?
**Display all values correctly**
- What happened instead?
**As described**

cncf/devstats issue here: https://github.com/cncf/devstats/issues/69

**Comment by svenklemm** [comment]
The following query works:
```
SELECT max(/^[[repogroup]]$/) FROM "issues_opened_[[period]]" WHERE $timeFilter GROUP BY time(1d) fill(0)
```
You need to fill missing values for stacked bar graphs if you do not have data in every interval.

Did your query work in earlier versions?

**Comment by lukaszgryglicki** [comment]
Well, I've recently changed all dashboards to use "null as zero" it helped everywhere, but not here.
For example here: https://prometheus.cncftest.io/d/000000004/companies-stats?orgId=1

I was using a special code to actually fill influx data with zeros before.
But recently I've figured out that "null as zero" solves the problem.
It works ideally in the link above, and there are data gaps there too.
Then why isn't it working in this case?

Of course, I can add fill(0) is absolutely needed, but why Group by time(1d) and not for example time(1h) - what is charts has different aggregating periods?

**Comment by torkelo** [comment]
This is due to stacking and interpolation when dealing with data with inconsistent distance between data points and data points for missing data (is no null/0 values in data). For best possible stacking behavior Grafana needs there to be values for each interval (so use group by time and fill(0) ) 

![image](https://user-images.githubusercontent.com/10999/36028216-75002caa-0d9e-11e8-8df3-04ac0aaa45ca.png)

**Comment by lukaszgryglicki** [comment]
But which GROUP BY TIME?
time(1h), time(1d)? is this constant or depending on something?

**Comment by torkelo** [comment]
> But which GROUP BY TIME?

not sure what you mean, it depends on the data and how big groups you want (how big the bars will be). Group by time is just a way in InfluxDB to group data into buckets, it also allows you tell influxdb to insert null or zero for time buckets where there is no data points.

**Comment by lukaszgryglicki** [comment]
Right, I need to dig into this, but currently, have no time. maybe I'll check during the weekend.
Thanks, that's probably all.

**Comment by lukaszgryglicki** [comment]
This only happens when using more than 1 influx series.
If using single influx series (with multiple values and nulls) all is fine.
I will revert to my gaps filling algorithm instead of using `group by time(period) fill(0)`
Why?
group by time(period) depends on the "Period" value from the drop-down (which is a template variable). This alone isn't a big issue anyway...
The biggest problem is that InfluxDB only supports period = 1s, 1m, 1h, 1d, 1w. But no month, quarter, year support at all.
