### ISSUE TITLE
Incorrect escaping added to spaces in Elasticsearch template variable

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#10853]
- What Grafana version are you using? 4.1.2
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? Linux
- What did you do? 
Added a template variable of type "Custom". With values:
INFO WARNING CRITICAL FATAL, WARNING CRITICAL FATAL, CRITICAL FATAL, FATAL
![image](https://user-images.githubusercontent.com/8266640/36021233-d60a79e4-0d8d-11e8-98b2-567fb1c7feb8.png)

I want to use this template variable in a Lucene query using [field grouping](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Field%20Grouping), to achieve this type of query (notice the space between the INFO and WARNING, which Lucene interprets as OR):

![image](https://user-images.githubusercontent.com/8266640/36021307-0fbf91c4-0d8e-11e8-9451-203f34a4a789.png)

I.e. query for all logs that are INFO OR WARNING. 
- What was the expected result?
Return records that have either INFO or WARNING level
- What happened instead?
When I replace my manual field query with the Grafana template variable `$AlramLevel`, Grafana inserted escape characters before the space, which breaks the Lucene Query.  My manual query, that works (notice the space between INFO and WARNING):

```
{"size":500,"query":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1518157841290","lte":"1518168641291","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"@fields.eventAction: Alarm.Raise AND @level:(INFO WARNING)"}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"fielddata_fields":["@timestamp"]}
```

The query generated when using the template variable (notice the \\\\ before the spaces in the level field):

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["systemevent-2018.02.09"]}
{"size":500,"query":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1518158910137","lte":"1518169710137","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"@fields.eventAction: Alarm.Raise AND @level:(INFO\\ WARNING\\ CRITICAL\\ FATAL)"}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"fielddata_fields":["@timestamp"]}
```
This query does not return any results.

How do I create custom template variable values that contain spaces that do not get escaped when template variable substitution happens?

**Comment by torkelo** [comment]
closing as similar to this feature request, https://github.com/grafana/grafana/issues/6789
