### ISSUE TITLE
[v5.0-beta1] Error when building frontend assets:  File to import not found or unreadable: base/font_awesome

### ISSUE THREAD

**Issue by jan--f** [grafana/grafana#10866]
I'm trying to build the v5.0.0-beta1 branchm more specifically the frontend asstets. Following https://github.com/grafana/grafana/blob/v5.0.0-beta1/README.md I installed yarn and ran ```yarn install --pure-lockfile```. When running ```npm run watch``` I get the following error when 
```grafana.[light,dark].scss``` is built:

```
ERROR in ./public/sass/grafana.dark.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "base/font_awesome";
^
      File to import not found or unreadable: base/font_awesome.
Parent style sheet: /home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/public/sass/base/_fonts.scss
      in /home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/public/sass/base/_fonts.scss (line 1, column 1)
    at runLoaders (/home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/async/dist/async.js:958:16)
    at options.error (/home/jan/obs/home:jfajerski:branches:security:logging/grafana/tmp.CkeQKtIqHx/grafana-5.0.0beta1/node_modules/node-sass/lib/index.js:294:32)
```

And many more of the same.

This is on a fairly recent SUSE Tumbleweed.

**Comment by torkelo** [comment]
strange, nothing on our dev machines and CI server, what version of node are you using?

**Comment by jan--f** [comment]
node was at 6.12.3-1.1. I just updated to 6.12.3-2.1 but that doesn't change anything.

**Comment by daniellee** [comment]
Did you try the usual "delete the node_modules directory and then run yarn install --pure-lockfiles again" step? (Fixes a lot of problems with npm)

And do you get any errors when running yarn install?

**Comment by jan--f** [comment]
Just did the "delete and yarn install".  No change.
yarn does not produce errors, but a warning that might be connected?
```
yarn install --pure-lockfiles
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > sass-loader@6.0.6" has unmet peer dependency "node-sass@^4.0.0".
[4/4] Building fresh packages...
Done in 32.27s.
yarn install --pure-lockfiles  36.29s user 10.92s system 144% cpu 32.584 total
```

**Comment by torkelo** [comment]
Can you try to do new git clone ? Sounds like one of your sass files is corrupt

**Comment by jan--f** [comment]
Same behaviour in a fresh clone.

However if I change the first two lines [here](https://github.com/grafana/grafana/blob/master/public/sass/base/_fonts.scss#L1) and remove the ```base/``` path component things build fine.

**Comment by jan--f** [comment]
Seems like this was introduced with the addition of webpack https://github.com/grafana/grafana/commit/0c86241c5b476cf3b4e8876dd92027cad9f95a0f#diff-4877afcc92c4c82a82c0065ebd8dc499

**Comment by torkelo** [comment]
That was introduce long ago and has been working since then, strange.

**Comment by jan--f** [comment]
@torkelo seems like there is an issue in the sass path parser. As @tserong noticed the error only happens if there is a ```:``` in the path string, say ``` /home/jan/obs/home:jfajerski:branches:security:logging/grafana/```. If I do the same in ```/home/jan/code/grafana``` it works with the ```base/``` component.

In any case the include without the ```base/``` component should be correct shouldn't it?

**Comment by torkelo** [comment]
Yes, an you submit PR?

**Comment by jan--f** [comment]
sure will do.
