### ISSUE TITLE
oauth2 with Azure Active Directory failing

### ISSUE THREAD

**Issue by BharatRed** [grafana/grafana#10867]
Please include this information:

    What Grafana version are you using? Grafana v4.2.0 (commit: 349f3eb) 
    What datasource are you using? N/A
    What OS are you running grafana on? Ubuntu
    What did you do? Try to log on
    What was the expected result? Success
    What happened instead? `Feb  9 14:57:54 influxGrafanaVm grafana-server[40825]: t=2018-02-09T14:57:54+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=1 orgId=1 uname=admin error="Get : unsupported protocol scheme \"\""`

Config: 
`#################################### oauth2 with Azure Active Directory #########
[auth.generic_oauth]
name = Azure AD
enabled = true
allow_sign_up = true
scopes = openid
client_id = <client_id>
client_secret = <client_secret>
auth_url = https://login.microsoftonline.com/<directory_id>/oauth2/authorize
token_url = https://login.microsoftonline.com/<directory_id>/oauth2/token
api_url =
team_ids =
allowed_organizations =`

The client_id, client_secret, directory_id were obtained using instruction here: http://docs.grafana.org/installation/configuration/#auth-generic-oauth

If `api_url` as `"https://login.microsoftonline.com/<directory_id>/openid/userinfo"` is specified then the following error occurred: 
`Feb  9 14:56:28 influxGrafanaVm grafana-server[40595]: t=2018-02-09T14:56:28+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=1 orgId=1 uname=admin error=EOF`

**Comment by DanCech** [comment]
The `api_url` setting should not be needed since Azure AD returns the user data as a JWT payload in the access token.

Can you enable debug logging in your .ini file and see what it says?

```
[log]
level = debug
```

You're looking for entries mentioning `id_token`

**Comment by DanCech** [comment]
Ah, I didn't notice you're running an old version of Grafana, Azure AD support was added in 5.0.0-beta1

**Comment by BharatRed** [comment]
:) good to know, I will update grafana and give it another try

**Comment by BharatRed** [comment]
Upgraded Grafana to 5.0.0-beta1. Azure AD authentication works as expected. Thanks a lot.
