### ISSUE TITLE
[v5.0-beta1] Light Theme Weirdness

### ISSUE THREAD

**Issue by gmr** [grafana/grafana#10869]
In Grafana 5.0b1 the new gradients in the light theme do not work well with the highlight shadows as seen in this example:

![screen shot 2018-02-09 at 12 55 46 pm](https://user-images.githubusercontent.com/49469/36042082-b04f6f4c-0d98-11e8-9e37-dff04d0cab0a.png)

Screenshot taken in Safari Version 11.0.3 (13604.5.6)

Unsolicited feedback from the few of us that use the light theme in my office is that we prefer it without the gradient. I guess we can customize the CSS to get rid of it once things are released.

Otherwise we're digging the improvements. Keep up the good work!

**Comment by torkelo** [comment]
That looks very strange, can you show a full screen view ?

**Comment by gmr** [comment]
![screen shot 2018-02-09 at 3 09 43 pm](https://user-images.githubusercontent.com/49469/36047850-4b1e0382-0dab-11e8-95aa-87f930c65b36.png)

**Comment by torkelo** [comment]
seems to be only safari that has this bug
