### ISSUE TITLE
Compatibility Datatable panel with Grafana v5

### ISSUE THREAD

**Issue by mozmozmoz** [grafana/grafana#10860]
Hi guys,

I meet an issue with a large table panel on Grafana (same issue has been mentioned here grafana/grafana#4157)

In the issue #4157, we can to see an alternative solution with Datatable panel (https://grafana.com/plugins/briangann-datatable-panel/installation), but it doesn't works with Grafana v5.0.0-beta1.

Do you have any tips ?

Thanks in advance

**Comment by torkelo** [comment]
this panel plugin is using a non standard way to get panel height, needs an update to work in v5:
I opened an issue for that
https://github.com/briangann/grafana-datatable-panel/issues/20

**Comment by mozmozmoz** [comment]
Thank you Torkel for this feedback
