### ISSUE TITLE
Table Panel & Support for nested object types (full raw object & _source for ES) 

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#10871]
v5.0-beta1 - Elasticsearch Datasource - Table Plugin - Options tab - Data - Columns - Add:

This will list all of the fields available within the returned documents, from under the _source root, along with the top level fields of _index,_type,_id.  However, the _source field itself is not available.

Adding the _source field as an **option** would allow for the inspection of the entire document as returned by Elasticsearch within the table view.  This is useful when analysis is being done by an engineer to decide which fields are needed.  This would also replace similar functionality that is available via the Elasticsearch Kibana dashboard and not require the technician to use Kibana for that information.

Please include this information:
- What Grafana version are you using? v5.0-beta1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? CentOS7
- What did you do? Table Plugin - Add Column
- What was the expected result? Would like to select "_source" as option
- What happened instead? It is not available, but other top level fields are (_index,_type,_id)

**Comment by davkal** [comment]
Will check if it matches another feature request...

**Comment by Elfo404** [comment]
Closing this as probably it doesn't apply to the current table panel, things have changed quite a bit :)

Please feel free to open a new updated issue (or comment on this one) if needed.
