### ISSUE TITLE
Add customizable auto-refresh interval

### ISSUE THREAD

**Issue by korservick** [grafana/grafana#10879]
Grafana version: 4.6.3
Datasource: Graphite

In addition to https://github.com/grafana/grafana/issues/10877
Is it possible to add 'auto' interval in auto-refresh dashboard option from calculated $__interval or $myinterval (from templated variables)?

**Comment by torkelo** [comment]
You can customize the options available in the refresh interval drop down under dashboard settings

**Comment by korservick** [comment]
I had in mind the automatic change of the auto-update interval depending on the selected range. 
Let me explain:
For "last 5 min" it is convinient to use 1,2...5 second auto-refresh (depends on metric interval). 
If user choose "last 7 days" or "last 30 days" on the same dashboard he did not saw last 10 second of metric in dashboard (because its just 1 point) but Grafana will continue to make requests to the backend 1,2...5 per second.
For automatic draw precisions its convinient to use summarize($__interval, avg, false) function. Next step is autocalculated auto-refresh and cache-timeout, isnt it?

**Comment by andreioss** [comment]
I think it would be useful feature!
