### ISSUE TITLE
[Feature Request] Support text slicing/replacement in Alias Patterns

### ISSUE THREAD

**Issue by yuha0** [grafana/grafana#10872]
The column names returned by InfluxDB are prefixed with aggregation function names, which makes the graph look really bad when it contains many fields:

![image](https://user-images.githubusercontent.com/3008244/36072768-304734c0-0eeb-11e8-9c8c-ef5b6d199ed5.png)

Ideally, I'd like to remove all the "mean_" prefixes. 

Can we support text slicing or replacement so that I can either cut the first 5 characters or replace "mean_" with ""(empty string)?

**Comment by torkelo** [comment]
You can already solve this using the field alias function (will render InfluxDB query as `mean('sleeping') AS 'sleeping'`

**Comment by yuha0** [comment]
@torkelo Thanks. I am aware of the alias function, but it does not work with wildcard:

```
SELECT last(*) AS <my_alias> FROM <some_measurement>
```

If `my_alias` is an empty string, it falls back to the default (`<agg function name>_<col_name>`). If it's a non-empty string, column name will be displayed as `<my_alias>_<col_name>`.

**Comment by Wyatts** [comment]
This shouldn't have been closed because it's not solved at all unless you always know exactly what you're grabbing and never use any wildcards.  In the world of server orchestration, neither of these is the case, and inability to do this is making monitoring of our swift cluster annoying.

**Comment by sbraz** [comment]
Hi @torkelo could you please re-open this issue? The idea would be to perform a replacement on an alias pattern such as `$tag_metric`.

**Comment by PeterHurtenbach** [comment]
Would also appreciate a solution for aliases with mean wildcard patterns from InfluxDB.

**Comment by sbraz** [comment]
@torkelo sorry to insist but can you please reopen this issue?

**Comment by Eraac** [comment]
In my case, I run query into stackdriver, retrieve all publish operation from topic, then I use the new stat panel and group them by topic_id, but some of them have very long name making the font-size ridiculously small.

Obviously i can override manually all fields but is tedious, we need the ability to remove a prefix (or suffix) making this dynamic and very more elegant

**Comment by lux4rd0** [comment]
Would love to see something like this as well. When doing something similar as `GROUP BY time($__interval), "host"` and then `ALIAS BY "$tag_host"` - would be nice to drop things like domain name... A lot of great uses to clean up alias naming!

**Comment by mihaidraghici98** [comment]
I am interested in adding this feature. Saw similar feature request but no answer. Why using empty string for AS can't have the behavior of not appending the alias at all? I have tried AS "\n" which miraculously will be an empty string in the legend but the "_" (underscore) will still be there.

**Comment by sbraz** [comment]
It looks like the new _Rename by regex_ transformation can be used for this, it was added by #29281.
