### ISSUE TITLE
Add customizable cache timeouts in Graphite datasource

### ISSUE THREAD

**Issue by korservick** [grafana/grafana#10877]
Grafana version: 4.6.3
Datasource: Graphite

Can we add internal variable $__interval_s (not $__interval_ms) and add this variable as 'auto' option in Datasource.Graphite.Options.Cache_timeout for automatic cache resize?
It is nice to add $myinterval variable (for some complex customizations) from templates to this option too. It needs to additional convert interval type to seconds because Graphite API by default work with numerical interval in this variable).

**Comment by torkelo** [comment]
Not sure we want to add this. Have not had this requirement for over 4 years, so it's probably not a common scenario and sounds like it will add some complexity.
