### ISSUE TITLE
Embed in iframe results in 404 page not found when using reverse proxy

### ISSUE THREAD

**Issue by sni** [grafana/grafana#10878]
Please include this information:
- What Grafana version are you using: 4.6.3
- What datasource are you using: shouldn't matter, but Influxdb and Prometheus
- What OS are you running grafana on: shouldn't matter, but Centos, Debian
- What did you do? Created an iframe from the Share->Embed menu
- What was the expected result? seeing an graph / dashboard
- What happened instead? Grafana returns the "Page not found" page

When enabling router_logging = true, it looks identical from wheter called within an iframe or directly. However, when i open the url without an iframe, it works.

Works (directly without iframe):
```
t=2018-02-12T11:56:29+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/dashboard-solo/db/prometheus-stats status=200 remote_addr="::1, 192.168.123.2" time_ms=1 size=16372 referer=
t=2018-02-12T11:56:30+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/db/prometheus-stats status=200 remote_addr="::1, 192.168.123.2" time_ms=3 size=10114 referer=
t=2018-02-12T11:56:30+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=200 remote_addr="::1, 192.168.123.2" time_ms=2 size=192 referer=
t=2018-02-12T11:56:30+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/annotations status=200 remote_addr="::1, 192.168.123.2" time_ms=0 size=2 referer=
```

Does not work (inside iframe):
```
t=2018-02-12T13:01:37+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/dashboard-solo/db/prometheus-stats status=200 remote_addr="::1, 192.168.123.2" time_ms=1 size=16372 referer=
```

I assume it has something todo with the url routing/resolving. We use grafana behind a reverse proxy and the following root_url.
```
root_url = %(protocol)s://%(domain)s/projectname/grafana/
```

I cannot reproduce the issue with the docker image grafana/grafana:4.6.3 which has no specific root_url set.
The issue still exists in latest grafana/grafana:latest docker image when used behind a reverse proxy with root_url set.
```
grafana-server -v      
Version 5.0.0-beta1 (commit: 3e2da1f)
```

**Comment by torkelo** [comment]
unable to replicate this with any of our many servers running behind reverse proxy (and subpath). 

Strange. Maybe something wrong with your reverse proxy and headers to disable iframeing?

**Comment by sni** [comment]
The reverse proxy config is find, but i found a interesting detail. It works if the grafana domain is different than the one which hosts the iframe, but it breaks if both have the same domain, ex.:
iframe is hosted at http://domain/iframe.html and the reverse proxy listens at http://domain/grafana/
It works for 
iframe hosted at http://onedomain/iframe.html and the reverse proxy is at http://otherdomain/grafana/

**Comment by torkelo** [comment]
Sounds like browser iframe protection , check headers coming from your reveres proxy, maybe you need to remove or add the header that allows iframing from other domain

**Comment by sni** [comment]
iframing is allowed, i can see the grafana page, its just that grafana tells me it cannot find the page i am looking for. Also it works when grafana is deployed at / and not in /grafana. So i think its some
internal angular voodoo. Also, according to the router_logging, the exact same request arrives in the logfile.
Is there any place i can dig more into the internal angular routing or would it help if i create a simple docker-compose scenario which makes this issue better reproducable for you?

**Comment by tomchiverton** [comment]
Did you ever get to the bottom of this ? I think I have the same issue with iframe'd Grafana content.
