### ISSUE TITLE
WorldMap (by country?) - new kind of graph

### ISSUE THREAD

**Issue by mradamczyk** [grafana/grafana#1088]
Hi,

I'd like to start the discussion about the new kind of graph that seems to be very useful for me. Let's say we have some geographical data - for example the number of registrations or entries grouped by country. Right now, there is no really good way to present such data in Grafana, just because there are to many countries to have one line per country on one chart. One solution is to have topX countries only, but, I think more interesting, would be to have a worldmap chart like in Kibana.

1. Given a query that returns one value per country for a given time range we could present these values on a country map with countries colored according to the value.

2. Each country could be clickable. Clicking on a country might result in selecting a template variable.

These are some ideas that me and my team would love ;) With this kind of graph we will be albe to use InfluxDB+Grafana for almost everything we need.

**Comment by perseo22** [comment]
+1

**Comment by sungjuly** [comment]
+1

**Comment by vvikash** [comment]
+1

**Comment by gbrian** [comment]
Yes, please! :+1: 
Do you think a kind of "aliasByNode" will do the job ?

live.data.france.metrics.visits
live.data.spain.metrics.visits
live.data.italy.metrics.visits

We can the use "aliasByGeoNode(live.data.*.metrics.visits, 1, LEVEL (country, city))".
Even more simplistic initial version could work using aliasByNode, as we are in a MAP the alias will represent the country. 

Thanks for the great job done!

**Comment by jagha** [comment]
+1

**Comment by polds** [comment]
+1

**Comment by utkarshcmu** [comment]
+1

**Comment by CyberGoat** [comment]
+1

**Comment by digrich** [comment]
+1 That would be good to have. 

Currently we plot all the logged in users on jVectorMap and monitor their latencies. This helps us to know at the high level if any users of specific region are having the bad latency.

**Comment by akqzx** [comment]
+1

**Comment by ColtonProvias** [comment]
If this were to be implemented, it would probably be best to standardize to using ISO country codes instead of country names.

**Comment by bergquist** [comment]
This will proberbly not make it into grafana core atm. But in next release it will be possible to add panels as plugins. Please check https://github.com/grafana/panel-plugin-piechart

**Comment by dluksza** [comment]
Having a map "graph" that can plot data base on longitude and latitude (in degrees) would be an awesome feature!

**Comment by SaaldjorMike** [comment]
+1

**Comment by nopzor1200** [comment]
+1

**Comment by ruudboon** [comment]
+1

**Comment by akrus** [comment]
+1

**Comment by marfago** [comment]
+1

**Comment by carkar** [comment]
+1

**Comment by evanbreznyik** [comment]
+1  but suggesting you also do lat/lon/radius for the point so you can dictate relative sizes of lat/lon markers (for grouping or comparison, etc)

**Comment by erowan** [comment]
+1

**Comment by bergquist** [comment]
This have been solved by the worldmap plugin https://github.com/grafana/worldmap-panel
