### ISSUE TITLE
Improve dashboard building flow for provisioned dashboards

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#10883]
Currently, we the workflow for provisioned dashboards are kind of limited. When dashboards are provisioned from disk we set `editable` as false which makes it a little bit harder to modify the dashboard in Grafana but that's not a good experience. 

The experience we want to enable is something like this
- [x] It should not be possible to save provisioned dashboards from the UI
- [x] It should be possible to modify the dashboard in the UI. 
- [x] Once the user tries to save it, Grafana should give a modal popup saying it's not possible.
- [x] That popup should also help the user copy the dashboard.json into the clipboard. (either by just displaying a textarea with the json or a button). The user is then responsible for updating the dashboard on disk. How the dashboard json files are updated on disk is up to the user.

**Comment by fchiorascu** [comment]
I don't think is a good way this. I faced the same problem. Usually I modify and change in GUI the Dashboards and also save the json. Is good option to have the possibility to modify on Grafana UI the Dashboards, export, save, etc.

**Comment by bergquist** [comment]
@fchiorascu not sure I understand you. We want to make it possible to modify the dashboards in the GUI and make it easier to export them. 

But we don't want to support saving the dashboard, cause then its hard to decide which dashboard is the correct one. The on in the database or the one on disk.
