### ISSUE TITLE
Elasticsearch no hits. {"size": 0} on query

### ISSUE THREAD

**Issue by cosmos1978** [grafana/grafana#10882]
see [https://github.com/grafana/worldmap-panel/issues/82](url)

**Comment by torkelo** [comment]
Please ask questions on community site

**Comment by cosmos1978** [comment]
To bad this is closed. because there are some breaking changes in elasticsearch.
[https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_aggregations_changes.html#_literal_size_0_literal_on_terms_significant_terms_and_geohash_grid_aggregations]

size: 0 is no longer valid for the terms, significant terms and geohash grid aggregations. Instead a size should be explicitly specified with a number greater than zero.

this has not been updated yet in grafana. the ticket was raised on the worldpanel github but the problem is caused by grafana itself.
