### ISSUE TITLE
Singlestat Enhancement Request - line breaks/multi line text

### ISSUE THREAD

**Issue by ianpmurphy** [grafana/grafana#10885]
It would be very handy if the Singlestat panel could allow either \n or <br> in the text… or some way to insert css to affect only that individual panel, which would allow styling.

At the moment the titlebar appears in small text. If you have a kiosk type setup on a big screen in a departmental area displaying, say, days since last accident, all you can display is the title in small text and the some text + value+some text.
If you put ‘Time since last accident’ and ‘Days’ it gets displayed as a block of text, wrapping in the panel. Ideally what you want is something like this in the middle of a box:

Time since last accident
45 Days

Adding support for some sort of a line break character would be the simplest solution here, allowing for three line texts, but displacing the panel title may also be feasible via panel-specific css.
Allowing CSS would also allow background images to be inserted, which I have seen quite a few requests for out there.

What do you think?

**Comment by NasusOptimus** [comment]
Hi, we are using "</br>" for linebreaks in Prefix and Postfix option.

**Comment by torkelo** [comment]
See above

**Comment by PhilsLab** [comment]
<br> tags don't seem to work anymore - did i miss anything?

**Comment by jrussell-datto** [comment]
I think this was mis-understood, because I also have this issue.
Text data that contain line breaks are having the line breaks stripped out when displayed on a singlestat panel. Adding `</br>` to the prefix or postfix does not change this.  Can this behavior be changed?

**Comment by oscar-vidal** [comment]
Also need to find a way to introduce a new line, is there any update on this? thanks

**Comment by mkrakowitzer** [comment]
Have the same issue here, need to be able to insert linebreaks when using "Text mode" with the Name option selected.

**Comment by Samuel-Morgan-Tyghe** [comment]
7 years and ive been waiting 2 days. Such a ridiculous problem

**Comment by ianpmurphy** [comment]
I made the original posting several years ago. Since it was impossible to achieve this with singlestat what we did was to use a dynamic text panel with embedded html as a template, so for example

`
< div style="background:{{BGColor}};width:100%;height;100%;text-align:center;" >
< br/ >
  < div style="font-size:48px" >{{value}} Days
  < /div> 
  < div style="font:bold;font-size:36px" >Some text about days
< /div >
< br/ >
< br/ >
< /div >
`

combined with a query which returns time, value, BGColor, Metric. I can't remember why we included a time and metric but Grafana takes the above template and replaces the two `{{templatevalues}}` with the values in the query. 
It works well and allows you to configure things however you want. 


The only problem is if you have a lot of panels and need to update the template. You just have to edit all the panels one by one.
