### ISSUE TITLE
https://github.com/f1kshatriya/grafana/commit/2ebdc0352da356a671324102a8034f5948160257, 解析json后继续引用对象导致空指针问题，fail to call MarshallJson and don`t throw the error, then create a painc(nil point)

### ISSUE THREAD

**Issue by f1kshatriya** [grafana/grafana#10889]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
closing this as there is no issue description
