### ISSUE TITLE
Table does not update on refresh period. Only ctrl f5 shows updated data

### ISSUE THREAD

**Issue by olsonnn** [grafana/grafana#10886]
- What Grafana version are you using?
grafana-5.0.0-beta1.linux-x64
- What datasource are you using?
prtg datasource
- What OS are you running grafana on?
centos7.3
- What was the expected result?
updated table data after manual refresh or periodic refresh
- What happened instead?
data was not updated. only after ctrl f5
- If related to metric query / data viz:
no
Browser: Opera 51 / Chrome 63
Column styles also applied

Not sure if this is grafana or plugin issue 
https://github.com/neuralfraud/grafana-prtg/issues/51

**Comment by torkelo** [comment]
The built in Grafana table refreshes on auto refresh or time range change, or when hitting refresh button. Maybe an issue with this plugin
