### ISSUE TITLE
Dashboard share button with time range, variables, etc..

### ISSUE THREAD

**Issue by mradamczyk** [grafana/grafana#1089]
I really like this feature: https://github.com/grafana/grafana/issues/864, but it's not very intuitive how to share the whole dashboard preserving the time range and template variables.

I know it's possible by clicking on a panel name, then "share" and than by unmarking second option. A similar modal as for sharing panel but for dashboards would be very useful for me.

The button could be located in "save" menu or even in main menu. It should be also possible to select preserving the time range and template variables while sharing dashboard after clicking "share" on a dashboard list.

**Comment by mcortinas** [comment]
Yes, I think this is a good idea too!

**Comment by tima** [comment]
+1

**Comment by torkelo** [comment]
This is actually implemented in Grafana 2.0 (develop branch) already :) 

![image](https://cloud.githubusercontent.com/assets/10999/6592239/5b6bcc98-c7cb-11e4-9242-0eafa08a2813.png)


I have highlighted the dashboard share button
