### ISSUE TITLE
Query editor show only field keys from default retention policy

### ISSUE THREAD

**Issue by pwudthi** [grafana/grafana#10893]
- What Grafana version are you using? 
4.6.3

- What datasource are you using? 
InfluxDB

- What OS are you running grafana on? 
Oracle Linux 6.5

- What did you do?
Create Continuous Query to generate mean, max, min for all measurements
`CREATE CONTINUOUS QUERY aggregates ON graphite BEGIN SELECT mean(*), max(*), min(*) INTO graphite.rp_90d.:MEASUREMENT FROM graphite.standard./.*/ GROUP BY time(1m), * END`
Continuous Query can generate data into new measurements with new retention policy
In Grafana query editor, it list only filed keys in the default retention_policy.measurement

- What was the expected result?
Query editor should list the field keys when the retention policy has changed

- What happened instead?
When I have changed the retention policy and select the measurement, the field keys list is blank.
- If related to metric query / data viz:

### default retention policy
> show field keys from influxdb_database
> name: influxdb_database
> fieldKey        fieldType
> --------        ---------
> numMeasurements float
> numSeries       float
> 

### rp_90d retention policy:
> 
> show field keys from rp_90d.influxdb_database
> name: influxdb_database
> fieldKey             fieldType
> --------             ---------
> max_numMeasurements  float
> max_numSeries        float
> mean_numMeasurements float
> mean_numSeries       float
> min_numMeasurements  float
> min_numSeries        float
> numMeasurements      float
> numSeries            float
>

**Comment by torkelo** [comment]
This is fixed in v5 / master
