### ISSUE TITLE
Add Folder name in dashboard title

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10895]
It is nice to have the same dashboard name in different folders

![rbo](https://user-images.githubusercontent.com/291750/36150318-9071d38a-10c3-11e8-820d-4dafc3470fc2.png)

It would be great on the top of pages to have the folder next to the title

![rbo2](https://user-images.githubusercontent.com/291750/36150319-909f57ce-10c3-11e8-96ad-7952f28962a3.png)

**Comment by shalstea** [comment]
+1

**Comment by tecmatia-dp** [comment]
+1

And Dashboard List plugin, Favorites, Dashboard links...
