### ISSUE TITLE
Failing to add ElasticSearch datasource in Grafana - receiving 403

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#10908]
I'm using Grafana 4.6.3.
I'm trying to add datasource for Amazon elastic search as a service (Version 6.0)
I have the url endpoint, I've opened policy access and https access from grafana.
When trying to run curl command I'm able to receive data from ES.

While trying to save & test the data source I'm receiving 403 error.
Am I missing something ?

**Comment by torkelo** [comment]
not sure, we know others use this combination, so must be something wrong with the permission options. Did you use access  proxy or direct in grafana?

Closing this as questions should go to community site

**Comment by neerajjain92** [comment]
@torkelo I am facing the same issue.
