### ISSUE TITLE
Repeating graphs jump to the next row when wrapping

### ISSUE THREAD

**Issue by stephenliang** [grafana/grafana#10915]
Please include this information:
- What Grafana version are you using?  v5.0.0-beta (3e2da1fee53675ec9254995472ae403000b94e83)
- What datasource are you using? Cloudwatch
- What OS are you running grafana on? RHEL
- What did you do? 

1. Create a datasource using Cloudwatch:

```
Variable Name: test
Type: query
Datasource: Cloudwatch
Query: regions()
Selection Options: Multi-value
```

2. Create a row
3. Create another row
4. Using the "test data: random walk" default dashboard, I set the repeat to "For each value of 'test'", direction horizontal, min width blank on the first row.
5. Select 5+ regions forcing a wrap

- What was the expected result?

The graphs wrap in the same row. There shouldn't be any graphs in the next row.

- What happened instead?

The wrapped graphs go to the next row, forcing other graphs in the next row down.

![](https://i.imgur.com/ipIVuEHl.png)

**Comment by torkelo** [comment]
This might be the same issue as https://github.com/grafana/grafana/issues/10917 not sure. @alex can you investigate?

**Comment by alexanderzobnin** [comment]
Yes, maybe, trying to replicate, but without success.

**Comment by alexanderzobnin** [comment]
@stephenliang could you test it against latest build? I can't replicate this. There were some fixes for rows/panels repeat, maybe this was fixed.
