### ISSUE TITLE
Row in Templates are not proceed correct

### ISSUE THREAD

**Issue by gtaspider** [grafana/grafana#10917]
Grafana 5.0beta1
win10x64

When templating with rows (Row -> Settings -> Repeat for: ) panels of above row move into the new created row. But not allays, it depends on the height of the row (i guess) and the arrangement of the panels like shown in the gif below:
![20180214grafanabug2](https://user-images.githubusercontent.com/25346567/36228836-9f3d39d2-11d5-11e8-9a75-4038ce3ef4f0.gif)

**Comment by torkelo** [comment]
fix coming in v5-beta3
