### ISSUE TITLE
Grafana Elasticsearch query

### ISSUE THREAD

**Issue by ThuyLeVn** [grafana/grafana#10928]
Hello,

I have a query in Grafana (Elasticsearch Data source)

"query":"(container_shortName:$container) AND (tags.keyword:^(*fluent_log*))" 

But it is not run correct. May you give me a suggestion for this case??

![image](https://user-images.githubusercontent.com/24593553/36266206-3dc938d0-1271-11e8-9070-de9c2ca02a06.png)

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by ThuyLeVn** [comment]
Similar 
![image](https://user-images.githubusercontent.com/24593553/36267470-3c470624-1274-11e8-9c9f-5be875127691.png)

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by ThuyLeVn** [comment]
![image](https://user-images.githubusercontent.com/24593553/36269464-9065dbae-1279-11e8-9247-76a850289dfe.png)
