### ISSUE TITLE
Dashboards Corrupted When Moving Multiple Dashboards Between Folders

### ISSUE THREAD

**Issue by cailen** [grafana/grafana#10926]
Hello all,

Earlier today, I was trying to select and move several dashboards from one folder to another folder. After doing so, I noticed a lot of the dashboards ceased to exist.

Upon looking at the grafana.db, it looks like it either completely wiped out or corrupted the "dashboard" table. The dashboard_version table was fine so I was able to restore the dashboards from snapshots, but this required me to first replace grafana.db with a backup copy.

Grafana v5.0.0-beta1 (commit: 8c027ea) in Docker

**Comment by bergquist** [comment]
@cailen Can you see anything about it in the logs?

**Comment by cailen** [comment]
@bergquist I wish I did; unfortunately docker flushed them. I do still have a copy of the corrupted database however if you would like me to send you that privately? It's small.

**Comment by bergquist** [comment]
@cailen that would be interesting. Could you please send it to carl at grafana.com ?

**Comment by cailen** [comment]
Carl, I just sent it to you from my work email with the issue number attached. Let me know if you need anything else.

**Comment by torkelo** [comment]
Have you seen this issue again? We have failed to replicate this and no other reports :(
