### ISSUE TITLE
[bug?] Null value setting in graph seems to not work for PostgreSQL data source 

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#10938]
- What Grafana version are you using?
4.6.3
- What datasource are you using?
PostgreSQL (PG 10.2)
- What OS are you running grafana on?
Debian 8.1

Looks like setting for null value does not work with PostgreSQL data source. Graph does not change shape neither when I set "null value" to "null" nor to "null as zero". Values are still just connected.

Here is graph with PostgreSQL data source:
![image](https://user-images.githubusercontent.com/17564930/36302268-20853dcc-1308-11e8-9bd4-cd18aad9f60a.png)

And here how it looks with Elasticsearch data source:
![image](https://user-images.githubusercontent.com/17564930/36302398-9b920784-1308-11e8-8d71-97d1fd0d77ba.png)

Thanks for looking at it.

**Comment by torkelo** [comment]
Does your query return null values? Please include response from your query

**Comment by machytkafitanalytics** [comment]
Ah, yes, I see, you are right - there are gaps in data like this one:

shoes | 2018-01-23T01:00:00+01:00 | 100
shoes | 2018-01-26T01:00:00+01:00 | 100

Elasticsearch is able to fill gaps automatically...

**Comment by torkelo** [comment]
yes, you need to do the equivalent in your query

**Comment by machytkafitanalytics** [comment]
OK, I created this crazy query - I am sure there are better ways how to do it - but this is quick enough and fill gaps in data with nulls. Of course it is tailored for my use case only which shows summary data for whole date, therefore castings to date - but maybe it can help to some other to find some inspiration...

```
with 
metricsdata as (
    SELECT    
      partition_date::date as partition_date,    
      category as metric,    
      sum(coalesce(value,0)) as value  
    FROM    
      my_pg_metrics_parent_table  
    WHERE    
      metricname = '.....' AND    
      shop = $shopname AND     
      $__timeFilter(partition_date )
    group by 1, 2 )
SELECT  
    d."time",  
    c.metric,  
    sum(m.value) as value
FROM  ( select generate_series( $__timeFrom()::date, $__timeTo()::date, '1day'::interval)::date as "time") d
cross join (select metric from metricsdata group by metric) c 
left join metricsdata m on d."time" = m.partition_date and c.metric = m.metric
group by 1, 2 
order by 1, 2
```
Thanks for help
