### ISSUE TITLE
Elasticsearch: Grafana generates the same queries in different ways

### ISSUE THREAD

**Issue by srubasheuski** [grafana/grafana#10939]
- Grafana version: 4.6.3
- Datasource: Elasticsearch 6.2.1
- OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)

We have dashboard with 3 templating variables:
   - group
   - host
   - metric

All variables using Elasticsearch datasource.

1) group
Query: {"find": "terms", "field": "group_name.keyword", "query":"group_name:'GROUPNAME*'"}
Options: Multi-value

2) host
Query: {"find": "terms", "field": "host.keyword", "query":"group_name.keyword:$group"}
Options: Multi-value

3) metric
Query: {"find": "terms", "field": "item_name.keyword", "query":"(host.keyword:* +$hostname)"}
Options: Multi-value

The problem is that Grafana generate queries to the Elasticsearch in some cases with double quotes and in other cases without.

**How to reproduce:**

- Select $group: SOMEGROUP, $host: one host is selected by Grafana and query looks like this:

{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["INDEX-NAME-\*"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1518763319964","lte":"1518774119965","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"(host.keyword:* +**SOME.HOST**)"}}]}},"aggs":{"1":{"terms":{"field":"item_name.keyword","size":500,"order":{"_term":"asc"}}}}}

- Now select another group with multiple values $group: ANOTHERGROUP, $host: one host is selected by Grafana, but this time select multiple hosts, the query looks like this (all hosts in double quotes):

{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["INDEX-NAME-\*"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1518764100635","lte":"1518774900636","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"(host.keyword:* +**(\\"SOME.HOST\\" OR \\"ANOTHER.HOST\\")**)"}}]}},"aggs":{"1":{"terms":{"field":"item_name.keyword","size":500,"order":{"_term":"asc"}}}}}

- And finally if select for $host only one host now, the query is:

{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["INDEX-NAME-\*"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1518764360729","lte":"1518775160729","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"(host.keyword:* +**(\\"SOME.HOST\\")**)"}}]}},"aggs":{"1":{"terms":{"field":"item_name.keyword","size":500,"order":{"_term":"asc"}}}}}

As you can see, we did the same action in the first and the third points, but the query was generated in different way. Due to this issue we can't create universal query for the variables. Is it possible to generate queries in the same way, for example, use double quotes in all the queries?

**Comment by torkelo** [comment]
> metric 
Query: {"find": "terms", "field": "item_name.keyword", "query":"(host.keyword:* +$hostname)"}
Options: Multi-value

Can you show definition for $hostname,  variable what options does it use? 

Unable to replicate this: 

when selecting only 1 value of a multi valued variable Grafana sends this query: 

{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["metrics-2018.02.16"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1518785984524","lte":"1518789584524","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"@source:(\"backend\")"}}]}},"aggs":{"1":{"terms":{"field":"@hostname","size":500,"order":{"_term":"asc"}}}}}

as  you can see it sends  `@source:(\"backend\")`  when having multiple selected it sends `@source:(\"backend\" OR \"site\")`

**Comment by srubasheuski** [comment]
So, I generated some testing data and now I can add some details about this issue.

As I mentioned above, we have dashboard with 3 variables:

![image](https://user-images.githubusercontent.com/7078675/36376904-fd8668e8-1585-11e8-94d2-abf04cce1ddf.png)

- **$group**
![image](https://user-images.githubusercontent.com/7078675/36376922-0ea1f674-1586-11e8-873a-8e9e8413d5c2.png)

- **$hostname**
![image](https://user-images.githubusercontent.com/7078675/36376961-33657f1c-1586-11e8-8a0a-e43b0bd11870.png)

- **$metric**
![image](https://user-images.githubusercontent.com/7078675/36376976-4684b86a-1586-11e8-8249-5eb832e87024.png)
 
**The issue:** Grafana generate queries to the Elasticsearch in some cases with double quotes and in other cases without.

**How to reproduce**

When we open the dashboard, which was saved with selected group with **ONE** host, Grafana generates query to the Elasticsearch **without** double quotes:

![action-1](https://user-images.githubusercontent.com/7078675/36378265-3c8f5130-158b-11e8-841d-971685841d09.gif)


![image](https://user-images.githubusercontent.com/7078675/36377195-49f5f954-1587-11e8-887e-e2f0a26ae7dc.png)


Then we can choose all groups all hosts, we can see that every host is in double quotes:

![action-2](https://user-images.githubusercontent.com/7078675/36378402-af966aec-158b-11e8-8e03-2db4fdf994fc.gif)


![image](https://user-images.githubusercontent.com/7078675/36377524-8a840dfc-1588-11e8-8c9c-957bbb72e529.png)

And now we select **the same group and the same host from the first action**, now Grafana generates query **with** double quotes:

![action-3](https://user-images.githubusercontent.com/7078675/36378649-a7291f34-158c-11e8-8805-e378ea85e71f.gif)


![image](https://user-images.githubusercontent.com/7078675/36377555-a93c4124-1588-11e8-915a-eea391246bcb.png)

Please let me know, if you need more info about the issue.
