### ISSUE TITLE
Support alert if condition lasts for a certain duration

### ISSUE THREAD

**Issue by wernight** [grafana/grafana#10949]
Grafana support alert based on a query over a certain period. However say I want to alert if (avg(), 30min, now) ABOVE 100, and a new metric appears above 100, then its average will be above and the alert will trigger immediately. What I mean by appear is for example if I graph all instances and a new one is created.

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/ does have `for:` which allow just that: setting a duration. I'd like the same in Grafana if possible.

**Comment by torkelo** [comment]
What do you mean a new one ? Sounds like a problem in the query, if your query only returns one data point for a new metric then the avg will be the same for that one metric. Not sure grafana can solve that l, You can include a condition that count number of data points as well, that could address it

**Comment by wernight** [comment]
If you look at the alert-manager it supports alerting only when a condition is true for over a certain duration. As you said the issue is when the query only returns one data point (or few), so avg is instantly high.

Could have Grafana implement a "for" like alert-manager. What do you think?
