### ISSUE TITLE
[Feature Request] Add external tags in alert definition

### ISSUE THREAD

**Issue by Thib17** [grafana/grafana#10940]
Grafana: 4.6.3
Datasources: Prometheus/Graphite/Elasticsearch
OS: CentOS

#### Use case
We are using Grafana alerting engine. Currently there is a single field (`Message`) to describe an alert. So we lack some information that would be used to identify, filter, route or handle these alerts (e.g. severity or owner_team or ...). Parsing `Message` field is not very usable.

#### Further information
- Alerting mechanism seems to be ready to manage such information as a set of key-value pairs called `Tags`. Indeed a field `Tags map[string]string` is already present in both [`pkg.services.alerting.EvalMatch`](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/models.go#L21) and [`pkg.tsdb.TimeSeries`](https://github.com/grafana/grafana/blob/master/pkg/tsdb/models.go#L39) structures.
- Some datasource seems to already return TimeSeries with `Tags` like cloudwatch, influxdb, and opentsdb (I didn't test it).
- At least one notifier already use `Tags` if they are provided: [Prometheus Alertmanager](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/alertmanager.go#L71). (We are using it)

## Request
Adding a set of key-value pairs that doesn't come from parsing timeseries. This could be called `ExternalTags` and be defined in alerts configuration. This way we can provide information about the alert (and not only the timeseries) with a flexible format. 

cc @torkelo , @bergquist , @iksaif

**Comment by bergquist** [comment]
This makes sense. I'll review the PR once I get time

**Comment by torkelo** [comment]
Not about the implementation, think this should not be a simple "external notification tags" but implemented as alert rule tags (https://github.com/grafana/grafana/issues/6552) that can be included in state change events, & used for search for alert rules (so needs to be in a table & indexed)

**Comment by bergquist** [comment]
@torkelo yea your right. That increases the size of the implementation but that's the correct way to solve this.

**Comment by Thib17** [comment]
Ok, thank you for your feedbacks.
I'll come back to you ASAP with a more complete implementation or questions.

**Comment by torkelo** [comment]
closing this as its so similar to , https://github.com/grafana/grafana/issues/6552
