### ISSUE TITLE
Custom panel not showing in icingaweb

### ISSUE THREAD

**Issue by zevilz** [grafana/grafana#10951]
I used [this dashboard](https://grafana.com/dashboards/1572). Panels worked fine in icingaweb. Then I create [new dashboard](https://gist.github.com/zevilz/ff3cda3a5c5881480207b85af54227d9) with one panel, set it in isingaweb grafana module. But my panels not showing, link to grafana panel working. What I do wrong?

![17-02-2018 12-26-58](https://user-images.githubusercontent.com/12094229/36339038-07ce94dc-13de-11e8-8918-8af485377772.png)
![17-02-2018 12-28-52](https://user-images.githubusercontent.com/12094229/36339043-22ee1d50-13de-11e8-88cd-8f69583d9e37.png)

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

Maybe there is a GitHub repo for incinga grafana plugin where you can open questions. Also include more details on what is going wrong (error messages , network traffic, logs etc)
