### ISSUE TITLE
Possible to cast legend labels as a float?

### ISSUE THREAD

**Issue by choldgraf** [grafana/grafana#10954]
I'm trying to show several timeseries that are created via the Prometheus `histogram_quantile` query. It creates a label for each "bucket" (e.g., `1.0, 2.0, 10.0, 15.0, inf` etc). However, because these are interpreted as strings, they aren't sorted properly (e.g. in the above case, Grafana plots it in the order `1.0, 10.0, 15.0, 2.0, inf`). This is problematic for things like stacked plots.

I've played around with the "legend format" field to cast legend values as floats before sorting, but nothing has worked so far. Anybody has success with doing this?

**Comment by bergquist** [comment]
AFAIK Prometheus only allows you to sort based on values https://prometheus.io/docs/prometheus/latest/querying/functions/#sort() not serie names

**Comment by torkelo** [comment]
Not sure where this logic should be, Graphite has sorting functions for series names as well. Grafana only allows you to sort legend by legend values avg/min/max etc.

**Comment by choldgraf** [comment]
I actually had a related question to this on the prometheus repo (https://github.com/prometheus/client_python/issues/247) and got feedback that something like this would need to be implemented on the side of whatever service ingests the prometheus data.

**Comment by Gaboose** [comment]
For posterity, if anyone still has this problem like me, play with your legend input box. I had this problem but my labels were unformatted (`{le="+Inf"}`, `{le="5"}`, `{le="10"}`, etc.) and they were being sorted as strings. Putting `{{le}}` into the Legend field made Grafana parse and sort them as floats.
