### ISSUE TITLE
Invalid interval string, expecting a number followed by one of "Mwdhmsy" 

### ISSUE THREAD

**Issue by Sibbern** [grafana/grafana#10950]
Grafana v4.6.3
Prometheus 2.1.0 with node_exporter
Ubuntu 16.04

Installed Prometheus, node exporter, nginx & Grafana in that order, imported numerous dashboards to see if the data was received on Grafana but ended up receiving this error:

`Invalid interval string, expecting a number followed by one of "Mwdhmsy"
i</a.describe_interval@http://..........:3000/public/build/app.5331f559bd9a1bed9a93.js:1:3025
i</a.interval_to_ms@http://.......:3000/public/build/app.5331f559bd9a1bed9a93.js:1:3147
i</a.calculateInterval@http://.........:3000/public/build/app.5331f559bd9a1bed9a93.js:1:2704
g</e.prototype.calculateInterval@http://........:3000/public/build/0.be20b78823b4c9d93a84.js:7:17966
g</e.prototype.updateTimeRange@http://........:3000/public/build/0.be20b78823b4c9d93a84.js:7:17725
u@http://........:3000/public/build/vendor.2305a8e1d478628b1297.js:43:68722
c/<@http://.........:3000/public/build/vendor.2305a8e1d478628b1297.js:43:69127
$digest@http://............:3000/public/build/vendor.2305a8e1d478628b1297.js:43:74824
$apply@http://..........:3000/public/build/vendor.2305a8e1d478628b1297.js:43:76636
M/a<@...........:3000/public/build/vendor.2305a8e1d478628b1297.js:43:72695
i@http://.......3000/public/build/vendor.2305a8e1d478628b1297.js:43:21868
mt/c.defer/n<@http://........:3000/public/build/vendor.2305a8e1d478628b1297.js:43:23332
**`
Image example: http://prntscr.com/ifvvob**

Prometheus.yml config: http://prntscr.com/ifvvj3

Data source: http://prntscr.com/ifvwe7

Have been trying to fix this issue for the past days and I've already looked on all the posts in github related to this error but haven't found any luck.

Does anyone know how to solve this?

Thanks

**Comment by torkelo** [comment]
What dashboard are you using ?

What is your data source config ? Make sure scrape interval includes time unit like 10s, same for step parameter in query

**Comment by Sibbern** [comment]
Have tried 4 different dashboards with the same result:

Prometheus, redis
Prometheus stats
Prometheus memcached
Prometheus system

I screenshooted my configs so you could see them above in my post. I changed the scrape interval to 15s instead of 15 and that removed the error but I am still not receiving any data from the panels?

**Comment by jwenz723** [comment]
@Sibbern, I had this same issue. I solved it by following the suggestion above from @torkelo .  I had "15" entered in the Scrape Interval field rather than "15s". As shown in the screenshot here. Hopefully that will help you get the issue resolved.

![image](https://user-images.githubusercontent.com/8587171/37165141-22590852-22b9-11e8-95c1-38917fbe242d.png)

**Comment by Sibbern** [comment]
Thank you for your reply Jwen.

I fixed it a couple of weeks ago with exactly the same problem as I had forgot the "s" tag at the end.

Thank you anyway! Hope this post will help others in the future.

**Comment by manoj-bandara** [comment]
Very helpful. happened to me. Ideally there should be validation at the "Data source  definition" window to avoid mis-direction

**Comment by QuincyC379** [comment]
tks,it works!
