### ISSUE TITLE
Render image error in notification

### ISSUE THREAD

**Issue by jsedy7** [grafana/grafana#10952]
Version: **5.0.0-beta3**
OS: Debian (Docker)

Hello, 
I have a problem with rendering image to my email notification. When alert is firing, I receive an email notification, but without image with a graph. I enabled debug logging and I added my logs. Have anyone the same problem? 

![screenshot_20180217_121814](https://user-images.githubusercontent.com/8748774/36340496-2f7ff516-13de-11e8-8c54-41062714f76b.png)

```
t=2018-02-17T12:19:18+0100 lvl=info msg="New state change" logger=alerting.resultHandler alertId=66 newState=alerting prev state=ok
t=2018-02-17T12:19:18+0100 lvl=info msg=Rendering logger=png-renderer path="d-solo/CC3Wof3kz/alerting?panelId=2"
t=2018-02-17T12:19:18+0100 lvl=dbug msg="[phantom] /www/grafana/tools/phantomjs/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory" logger=png-renderer
t=2018-02-17T12:19:18+0100 lvl=eror msg="failed to render an image" logger=png-renderer error="exit status 127"
t=2018-02-17T12:19:18+0100 lvl=dbug msg="Image rendered" logger=png-renderer path=/www/grafana/data/png/AH3lcR359hloXwPMxd6s.png
t=2018-02-17T12:19:18+0100 lvl=info msg=uploaded logger=alerting.notifier url=http://grafana:3001/public/img/attachments/AH3lcR359hloXwPMxd6s.png
t=2018-02-17T12:19:18+0100 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email id=2 isDefault=false
t=2018-02-17T12:19:18+0100 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[me@email.com]
t=2018-02-17T12:19:18+0100 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.929 alertId=66 name="Alert test" firing=true
```

**Comment by bergquist** [comment]
Seems like `libfontconfig` is missing in the container.

What container did you use? `grafana/grafana-docker` installs `libconfconfig` https://github.com/grafana/grafana-docker/blob/master/Dockerfile#L6

**Comment by jsedy7** [comment]
Ahh, yes! It's problem in my Dockerfile. I created my own image but I forgot to add `libfontconfig`
After adding and build image again It works correctly. Thank you for your support and sorry for the unnecessary issue. 🙂

**Comment by m-peko** [comment]
I have the same issue but on Alpine Linux. I have added `fontconfig` but that did not solve the issue.
