### ISSUE TITLE
Ignoring sample.yaml is bad

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10963]
Latest grafana ignore sample.yaml in provisioning.

This is very non intuitive.

Proposal:

Stop ignoring sample.yaml and rename sample.yaml to sample.yaml.example

**Comment by bergquist** [comment]
Yea that's a better way to solve it. I'll fix this tomorrow/later today.

**Comment by roidelapluie** [comment]
This is especially hepful for people who will want to try the feature by changing the sample.yaml :)

**Comment by bergquist** [comment]
Thank you for reporting this :)
