### ISSUE TITLE
[OAuth] Github OAuth with allowed organizations fails to login

### ISSUE THREAD

**Issue by yudiandreanp** [grafana/grafana#10964]
Grafana version: 5.0.0-beta3
OS: Ubuntu 16.04 4.4.0-98-generic, grafana is with Docker 1.12.6

What did I do:
I tried setting up Github OAuth with allowed_organization turned on. Had the user:email,read:org scopes. Made sure that the users are the members of the organization.

Expected result:
Users from the correct organization logged in

What happened instead:
Got the 
"Login Failed
User not a member of one of the required organizations"
error

Some logs from the login (masked the remote_addr):
t=2018-02-19T18:37:20+0000 lvl=eror msg="User not a member of one of the required organizations" logger=context userId=0 orgId=0 uname=
t=2018-02-19T18:37:20+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=xx.xxx.xxx.xxx time_ms=2332 size=29 referer=https://dashboard.airyrooms.com/login

The auth.github settings:
[auth.github]
enabled = true
allow_sign_up = true
client_id = xxx
client_secret = xxxxxx
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
allowed_organizations = airyrooms

The setting above worked with Grafana 4.6.3

**Comment by yudiandreanp** [comment]
It also worked on v5.0.0-beta1

**Comment by lostick** [comment]
still happening on our side using the nightly build

**Comment by vglafirov** [comment]
Confirmed, it doesn't work on beta1 though. Please reopen the issue.

**Comment by torkelo** [comment]
Fix was merged today, available in nightly
