### ISSUE TITLE
Alertings not visible for viewer role in Grafana 5.0

### ISSUE THREAD

**Issue by DanielWebelsiepCURSOR** [grafana/grafana#10966]
- What Grafana version are you using?
Grafana 5.0 beta 4
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Windows 10 64bit Enterprise (Fall Creators Update)
- What did you do?
Enable anonymous login and open https://"grafana server":"port"/alerting/list
- What was the expected result?
Alerting Tab is showing alerts, Alerting tab should be available in menu.
- What happened instead?
Alterting tab is not visible and no alertings are display.

I updated a second grafana installation from 4.6.3 to 5.0 beta to check the new plugins. Anonymous login is enabled and the new alerting plugin was empty. Now I see that the alerting tab was missing and the alert list don't show any alerts. This worked with 4.6.3. I'm using the same (updated/merged) custom.ini with the same dashboards (except adding the new altering panel). Login with user ends in the same result. Login with another user having editor or admin roles can see alertings.

**Comment by torkelo** [comment]
You need editor/Edit permissions to access alert rules.

**Comment by DanielWebelsiepCURSOR** [comment]
The alerting Plugin don't shows any alerts in viewer roler. Is also editor permission needed to access alerts?

**Comment by torkelo** [comment]
Yes

**Comment by thlapin** [comment]
This is an unfortunate change from v4 as we use a viewer role on large screens and we were making use of the alert panel to show the alerts.

Could this potentially be reviewed with this case in mind? I believe it should be possible to at the very least view alert rule results with the viewer role.

**Comment by gladhorn** [comment]
I think it would be great to let viewers see alerts (not interact with them). I have a status dashboard with some alerts to monitor e.g. disk usage, but it's not very useful since currently only logged-in users can see the alerts.

**Comment by zeebonk** [comment]
I agree with @thlapin and @gladhorn, we also use the alerts list on a big screen and it seems unnecessarily  unsafe to have those running with edit rights.

**Comment by flopp999** [comment]
I also would say that a viewer should be able to see alert in alert lists

**Comment by UzairM** [comment]
I also agree with the above statements

**Comment by EdeHeltovics** [comment]
This is really an unfortunate disfunction. Our customers were heavily using this feature in 4.x version as viewers, and now they are very disappointed loosing this functionality.

**Comment by torkelo** [comment]
there is a feature request to change this back, https://github.com/grafana/grafana/issues/11167

**Comment by carlossmartini** [comment]
I'm seeing this issue in 7.2.1 right now.  The alert icon does not even show up for viewer role.  Is this something that was reverted after this thread?

**Comment by vdituro** [comment]
This is really unfortunate. It is really functional for viewers to have access to alarm state. Too bad
