### ISSUE TITLE
[Bug]Error 1054: Unknown column is displayed when using Constant variable in MySQL in dashboard variable setting

### ISSUE THREAD

**Issue by GoodLights** [grafana/grafana#10965]
Please include this information:
- What Grafana version are you using?
 v5.0.0 beta4

- What datasource are you using?
 MySQL

- What OS are you running grafana on?
 CentOS7

- What did you do?
 5.0.0 Beta 4 has been updated to Grafana's 4.6.3 environment

- What was the expected result?
 As with version 4.6.3, you can use Constant variables for conditional expressions in the Where clause.

- What happened instead?
 The following error screen was displayed.
 Templating
Template variables could not be initialized: Error 1054: Unknown column 'variable' in 'where clause'

 Since Grafana 4.6.3 successfully used Constant variable for MySQL query, please correspond.

**Comment by torkelo** [comment]
What is the value of the variable? (and options), and how it it used ? (include query, and query inspector details)

**Comment by GoodLights** [comment]
Variables are set as follows.

[Variable1]
 Name user
 Type Constant
 Value xxxxx

[Variable2]
 Name group
 Type Query
 Data Source mysql
 Refresh On Dashboard Load
 Query
  select g.name from usrgrp u inner join rights r on u.usrgrpid = r.groupid inner join groups g on r.id = g.groupid where r.permission > 0 and u.name = $user group by g.groupid order by g.name;
 Sort Disabled

The following message is displayed when registering variable 2 above.
Template variables could not be initialized: Error 1054: Unknown column 'xxxxx' in 'where clause'

**Comment by torkelo** [comment]
I think you need quotes around the value

**Comment by mengxianyao** [comment]
I meet the same problem.
can you tell me the solution?
