### ISSUE TITLE
Grafana access dashboard readonly with out logging into grafana 

### ISSUE THREAD

**Issue by uppalarakesh2** [grafana/grafana#10978]
We are using Grafana v4.6.0-beta running in docker container. I have created Dashboards in Grafana, Is there a way can i can give the URL of grafana dashbords to my team members, so that they can access the dashboard in read-only mode with out logging into grafana. Right now it is asking for login when i share the URL to the team

**Comment by bergquist** [comment]
You can use anonymous mode http://docs.grafana.org/installation/configuration/#auth-anonymous
