### ISSUE TITLE
Telegram Bot Inline Image Mode Does't Work

### ISSUE THREAD

**Issue by fanvinga** [grafana/grafana#10975]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

- What Grafana version are you using?
Grafana v5.0.0-beta3 (commit: 2e9433c) 
using the master branch of grafana docker (grafana/grafana:master)

- What datasource are you using?
Influxdb

- What OS are you running grafana on?
Debian 8.9 server

- What did you do?
pull the latest image and use "--link docker-f8643d:influxdb -v /root/monitor/grafana:/var/lib/grafana -e GF_SERVER_ROOT_URL="https://MYDOMAIN" to run it and without any other changes.

- What was the expected result?
Telegram Bot Alerting works well with include images mode enabled.

- What happened instead?
No alerting sent if enable include images mode (but if the status of alerting become OK , the Notification works well and the test message sent well)
Everything works well if disable include images mode.(no images will be sent)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Can you show grafana-server log output? Maybe contains info on why image could not be rendered.

**Comment by fanvinga** [comment]
The log of enable include images mode:

root@debian:~# docker logs -f docker-f64adc
t=2018-02-20T15:24:35+0000 lvl=info msg="Starting Grafana" logger=server version=5.0.0-beta4 commit=dceac3a compiled=2018-02-20T12:39:16+0000
t=2018-02-20T15:24:35+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-02-20T15:24:35+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-02-20T15:24:35+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-02-20T15:24:35+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-02-20T15:24:35+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-02-20T15:24:35+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2018-02-20T15:24:35+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2018-02-20T15:24:35+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=https://status.unlimit.fun"
t=2018-02-20T15:24:35+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-02-20T15:24:35+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-02-20T15:24:35+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-02-20T15:24:35+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-02-20T15:24:35+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2018-02-20T15:24:35+0000 lvl=info msg="App mode production" logger=settings
t=2018-02-20T15:24:35+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-02-20T15:24:35+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-02-20T15:24:35+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-02-20T15:24:35+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-02-20T15:24:35+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-02-20T15:24:35+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-02-20T15:24:35+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2018-02-20T15:24:35+0000 lvl=info msg="Initializing Stream Manager"
t=2018-02-20T15:24:35+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2018-02-20T15:24:35+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-02-20T15:24:35+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-02-20T15:24:39+0000 lvl=warn msg="Failed to get slug from database, Dashboard not found"
t=2018-02-20T15:26:03+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=40 newState=alerting prev state=ok
t=2018-02-20T15:26:03+0000 lvl=info msg=Rendering logger=png-renderer path="d-solo/Vr9RTsqzz/network-telecom?panelId=8"
t=2018-02-20T15:26:04+0000 lvl=info msg=uploaded logger=alerting.notifier url=
t=2018-02-20T15:26:04+0000 lvl=info msg="Sending telegram image notification" logger=alerting.notifier.telegram photo=/var/lib/grafana/png/aLLoZzwuNB4dUjAcZwc1.png chat_id=484546226 bot_token=508219778:AAFaT8AhVFs8WHvurnXblu9g8ftjYP3Agig
t=2018-02-20T15:26:08+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook=TGBOT

**Comment by fanvinga** [comment]
@torkelo Hello, I have already submitted the log.Can you help me check what is the problem? As i know if empty message is sent to https://api.telegram.org/bot=BOT_API_TOKEN , it will feedback 400 bad request error code .

**Comment by IamAliBaba** [comment]
provider = local

This way its sendinging only url

**Comment by pho** [comment]
As I said over here: https://community.grafana.com/t/telegram-alerts-test-message-succeeded-but-400-bad-request-on-real-alerts/806/19

Hi, I’ve looked at the telegram notifier and the problem is that the sendPhoto telegram api endpoint for the inline message, does not have a “message” field like the text only version has, but a “caption” one instead, and this caption field is limited server-side to 200 chars, but the length of the caption is not being checked at any moment on our module

A quick test hardcoding the caption sent to a couple words seems to be working right.
I would PR something but I dont know how I should format the message to be constrained into this limit

Also, the test message is working because its using the text message format, but includes an image as an external link not as an embedded one.

**Comment by fanvinga** [comment]
@IamAliBaba In v5.0.0-beta4 (commit: dceac3a)  "provider = local" is being used as default setting

**Comment by fanvinga** [comment]
@pho do you mean that the include images mode is not available and needs to wait for further progress ?
But in earlier versions, all of this worked fine. I guess the issue may be related to the recent refactoring of alerting notifications?

**Comment by pho** [comment]
@fanvinga The inline picture mode is working only if you are lucky enough that the whole caption (state + message + url + metrics) fits in 200 chars

**Comment by fanvinga** [comment]
@pho LOL My workround is disable include images mode temporarily :)
