### ISSUE TITLE
[Feature Request] Embed Dashboards.

### ISSUE THREAD

**Issue by JoeyG1973** [grafana/grafana#10979]
Checked all the usual places.

Please allow the embedding of dashboards.

This was asked earlier and it got a lot of up votes but was closed for some reason. https://github.com/grafana/grafana/issues/4757

**Comment by torkelo** [comment]
you can do this already, what more do you need?

**Comment by JoeyG1973** [comment]
Waiting on a colleague who know more than me to respond.  Please don't close this.  :)

**Comment by soffos** [comment]
@torkelo 
We're looking to embed an entire dashboard in a webpage, similar to the ability to embed panels found at: http://docs.grafana.org/reference/sharing/#embed-panel, where access to the navigation is removed.

Looking around, it appears the only way to represent a dashboard is with a snapshot, which retains the ability to navigate around the rest of the tool.

The functionality could be somewhat replicated by embedding every panel on a dashboard, but that wouldn't retain the shared time-zoom the dashboard provides.

**Comment by torkelo** [comment]
closing this, in favor of https://github.com/grafana/grafana/issues/4757
