### ISSUE TITLE
Persist time window between dashboards

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1097]
It would be really neat to have an option to make the chosen time window "sticky". 
Use case is detailed analysis of an event pinpointed to a given time frame. Opening related dashboards reset the time window. Current workaround is to have all possible graph details in one dashboard and collapse the rows I guess.

**Comment by mmolnar** [comment]
I am also having this issue, if i need to correlate multiple dashboards to one incident or time window then its a pain to filter them out.

I think its something that could be easily done with grafana backend. To just lock all dashboards to current time window for current user.

Or just make the time window available as parameters in the uri so we can share time filtered dashboards between users just by sending a link.

**Comment by fksimon** [comment]
As a updated to 4256, we did get this working by tagging each page and creating dashboard links.   It did require we edit every dashboard to have all links for the tag we created so we could move from dashboard to dashboard and not lose the time settings.   Works but painful.

**Comment by aderumier** [comment]
+1

**Comment by mattiash** [comment]
I often investigate incidences that require me to look at a specific time period across several different dashboards. I have learnt to copy the "&from=xx&to=yy" from the url of one dashboard, open a new dashboard and then paste the string at the end of the new dashboard url. Hardly elegant, but it works.

A "Pin" option with a thumbtack (https://fontawesome.com/icons/thumbtack?style=solid) would make this a lot easier...
