### ISSUE TITLE
[Bug] Scrollbar works incorrectly in Grafana 5.0 Beta4 in some cases

### ISSUE THREAD

**Issue by Civil** [grafana/grafana#10982]
Grafana Version: 5.0b4

Video of the bug: https://youtu.be/ljqXzYo1arU

Steps to reproduce:
1. Enter full screen mode on the right most monitor you have.
2. Move your mouse to the right most part of your screen.
3. Try to move scroll bar with the mouse.

In grafana 4.x it was working ok. In grafana 5.0b1-b4 it will behave like on video. Scrollbar itself works ok if you place your mouse in the middle of it, not he right most corners.

**Comment by torkelo** [comment]
unable to replicate here in chrome 64 on linux or mac , what browser are you using?

**Comment by Civil** [comment]
I've tested that on Chrome on Mac and tested on Chrome on Linux.
It's important that it should be right most pixel.
