### ISSUE TITLE
[Bug] MySQL tag templating with __text and __value

### ISSUE THREAD

**Issue by duhow** [grafana/grafana#10985]
Using Grafana v4.7.0-pre1 (commit: 603725a), when using the templating query with MySQL and `__text`and `__value` fields, tags load, but when clicking on them, no value is selected.

Current values:
**Query:** `SELECT name AS __text, id AS __value FROM clientlist WHERE name != ""`
**Tag query:** `SELECT name AS group FROM clientgroups ORDER BY name`
**Tag value query:** `SELECT name FROM clientlist WHERE id IN (SELECT DISTINCT cli FROM clientgroup_assoc a JOIN clientgroups c ON a.cgid = c.id WHERE c.name = "$tag")`

**Comment by torkelo** [comment]
does your  `SELECT name FROM clientlist WHERE id IN (SELECT DISTINCT cli FROM clientgroup_assoc a JOIN clientgroups c ON a.cgid = c.id WHERE c.name = "$tag")` query return anything? Can you show the network traffic for your 3 variables requests (when you select a tag it should fire the tag value query and select values)

**Comment by duhow** [comment]
All queries return values. I'll attach them shorting and renaming elements, but as told you, the problem only appears when using `__text` and `__value` (without that works fine), also tried to modify many times the **tag value query** by using the id/name fields, renaming field, but nothing happens.

### Query result
```json
{
  "results": {
    "clients": {
      "refId": "clients",
      "meta": {
        "rowCount": 143,
        "sql": "SELECT name AS __text, id AS __value FROM clientlist WHERE name != \"\""
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "__text"
            },
            {
              "text": "__value"
            }
          ],
          "rows": [
            [
              "SERVERONE",
              2
            ],
            [
              "SERVER-N1",
              3
            ],
		........
            [
              "SERVER-N1111",
              1381
            ],
            [
              "SERVER-N1112",
              1384
            ]
          ]
        }
      ]
    }
  }
}
```

### Tag result
```json
{
  "results": {
    "clients": {
      "refId": "clients",
      "meta": {
        "rowCount": 77,
        "sql": "SELECT name AS grp FROM clientgroups ORDER BY name"
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "grp"
            }
          ],
          "rows": [
            [
              "Servers"
            ],
            [
              "Client 1"
            ],
            ......
            [
              "Client 24"
            ]
          ]
        }
      ]
    }
  }
}
```

### Tag value query result
```json
{
  "results": {
    "clients": {
      "refId": "clients",
      "meta": {
        "rowCount": 34,
        "sql": "SELECT name FROM clientlist WHERE id IN (SELECT DISTINCT cli FROM clientgroup_assoc a JOIN clientgroups c ON a.cgid = c.id WHERE c.name = \"Servers\")"
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "name"
            }
          ],
          "rows": [
            [
              "SERVERONE"
            ],
            [
              "SERVER-N35"
            ],
            ......
            [
              "SERVER-N48"
            ]
          ]
        }
      ]
    }
  }
}
```

**Comment by daniellee** [comment]
@duhow are you still having this issue? I couldn't recreate it - it worked for me. The error handling in this tag feature is pretty bad (it seems it is still an experimental feature after all these years). If it is not working, are you seeing any errors in the Chrome dev tools console?

**Comment by daniellee** [comment]
No reply for a while so I'm going to close this issue - I can reopen it if you are still having problems.

**Comment by itelmenko** [comment]
I have same problem in Grafana 5.3.1

Query
`SELECT name AS __text, id AS __value FROM workers`
Tags query
`SELECT type FROM workers GROUP BY 1 ORDER BY 1`
Tag values query
`SELECT id FROM workers WHERE type = '$tag'`

When I select any tag it doesn't select  corresponded option in list

**Comment by sanchomuzax** [comment]
> No reply for a while so I'm going to close this issue - I can reopen it if you are still having problems.

I have similar problem.

When I select any tag it doesn't select corresponded option in list of tags, while I using multiple values in the Query with `name AS __text, id AS __value`. If I use only on value in the Query, than the tag selector is working. 

I tried your example but not working for me.

~~~
Grafana v5.4.3
MariaDB 10.1.8
~~~

**Comment by xRoker** [comment]
Grafana 6.0.2, not working even with a single value.

**Comment by duhow** [comment]
@daniellee please reopen.

**Comment by JornBrouwers** [comment]
It is working for me based on the query of @daniellee 

Query: 
`select  concat_ws(' ', Name, MA.idMachine) as __text, 
idMachineAllocation as __value 
From MachineAllocation as MA, Customer as Cu 
where MA.idCustomer = Cu.idCustomer`

Tags Query:
`SELECT NAME FROM Customer`

Tags Value Query:
`SELECT idMachineAllocation 
FROM MachineAllocation MA, Customer 
WHERE MA.idCustomer = Customer.idCustomer and Name = '$tag'`

**Comment by dreamfalcon** [comment]
Also not working here:
Grafana 6.4.4

![image](https://user-images.githubusercontent.com/5775148/68607413-790af700-04a8-11ea-98db-b0e2cc42e851.png)

**Comment by Jens-H-Eriksen** [comment]
After a lot of poking around in version 6.5.1 I finally found out that the value tag _must be a string_, Thus casting my **Id** (which is an int) to a nvarchar(10) got it working.

![image](https://user-images.githubusercontent.com/26311915/70033958-c0206f80-15b0-11ea-940f-568a40e2f21e.png)
