### ISSUE TITLE
[Bug] Function list positioned incorrectly in Grafana 5.0 beta4

### ISSUE THREAD

**Issue by Civil** [grafana/grafana#10981]
Datasource: Graphite, specified as 1.1.x
Grafana: 5.0 beta4

We were testing grafana's ability to show custom functions and if group contains too many functions, list of them is partly outside of working area without ability to scroll it down.
Screenshot is in attachment. There is obviously something in the end of the list, but it's not reachable.

![screen shot 2018-02-21 at 9 59 35 am 2](https://user-images.githubusercontent.com/844380/36471219-f9566714-16ed-11e8-97f2-204cf3db987d.png)

**Comment by torkelo** [comment]
This looks fixed, you can scroll down to see all options
