### ISSUE TITLE
Right Y axis isn't displayed on a graph

### ISSUE THREAD

**Issue by bperel** [grafana/grafana#10983]
This issue is always reproducible for me.

- What Grafana version are you using?
3.0.0 beta 3
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Debian Jessie (official Grafana image)
- What did you do?
I configured a graph with two series. Since their values are quite different, I decided to set up 2 Y axes : one for the high-number series (0 to 125000) and one for the low-number series (0 to 50) : 
![screenshot from 2018-02-21 10-55-08](https://user-images.githubusercontent.com/1484692/36473789-e868113e-16f5-11e8-8bb2-7df0f6b9073c.png)

- What was the expected result?
I expected the graph to show 2 Y axis
- What happened instead?
Only the left Y axis is shown : 
![screenshot from 2018-02-21 10-58-53](https://user-images.githubusercontent.com/1484692/36473899-3bf56752-16f6-11e8-9a9e-884733707589.png)

If I swap the Y-min and Y-max of the 2 axes in the config, then the left Y axis shows the expected new Y-min and Y-max on the graph, but the right Y axis still doesn't show.

- When refreshing the graph, the following request is done :
  Request : `/api/datasources/proxy/1/query?db=grafana&q=SELECT "newItems" FROM "autogen"."jenkins_custom_data" WHERE time >= 1517478546001ms and time <= 1518342546001ms;SELECT "totalItems" FROM "autogen"."jenkins_custom_data" WHERE time >= 1517478546001ms and time <= 1518342546001ms&epoch=ms`
Response: 
```json
{
  "results": [
    {
      "statement_id": 0,
      "series": [
        {
          "name": "jenkins_custom_data",
          "columns": [
            "time",
            "newItems"
          ],
          "values": [
            [
              1517539801000,
              6
            ],
            [
              1517626198000,
              9
            ],
            [
              1517712606000,
              9
            ],
            [
              1517798977000,
              6
            ],
            [
              1517885278000,
              10
            ],
            [
              1517971747000,
              6
            ],
            [
              1518058151000,
              4
            ],
            [
              1518144490000,
              5
            ],
            [
              1518230969000,
              11
            ],
            [
              1518317361000,
              14
            ]
          ]
        }
      ]
    },
    {
      "statement_id": 1,
      "series": [
        {
          "name": "jenkins_custom_data",
          "columns": [
            "time",
            "totalItems"
          ],
          "values": [
            [
              1517539801000,
              118940
            ],
            [
              1517626198000,
              118949
            ],
            [
              1517712606000,
              118958
            ],
            [
              1517798977000,
              118964
            ],
            [
              1517885278000,
              118974
            ],
            [
              1517971747000,
              118980
            ],
            [
              1518058151000,
              118984
            ],
            [
              1518144490000,
              118989
            ],
            [
              1518230969000,
              119000
            ],
            [
              1518317361000,
              119014
            ]
          ]
        }
      ]
    }
  ]
}
```
 
Did I do something wrong?

**Comment by torkelo** [comment]
You need to assign a series to the right y axis , it will not be rendered if there are no series assigned to it, you can assign it to right y axis by clicking on series color icon

**Comment by MediaMaquina** [comment]
> You need to assign a series to the right y axis , it will not be rendered if there are no series assigned to it, you can assign it to right y axis by clicking on series color icon

Could you tell me where is this "series color icon" i don't see it at all. =(

**Comment by Kuri-su** [comment]
yes, you must add `series override` in `Visualization page`(grafana v6.x),  to setting series assign  to the right y axis.

ref: 
* https://grafana.com/docs/grafana/latest/panels/visualizations/graph-panel/#series-overrides
