### ISSUE TITLE
Template-alias for groupBy tagValue

### ISSUE THREAD

**Issue by gekr** [grafana/grafana#10992]
Hi,

Working with Grafana and OpenTSDB datasource.
Would like to show a metric tagged by the vm-ID (tag_key).
Basically works good, but the legend shows the vm-ID which I would need to replace by the human readable name.

Is there anyway to introduce somekind of mapping (e.g. templating like $vmID2Name([[tag_key]])) here?

Of course, I know the easy solution would be to introduce a new opentsdb TAG, but this is not possible for me ...

Thanks in advance and BR,
g.

![image](https://user-images.githubusercontent.com/17470762/36531433-20461042-17be-11e8-84aa-3e7dbbf72f33.png)

Please include this information:
- What Grafana version are you using? -- 4.6.3
- What datasource are you using? -- OpenTSDB
- What OS are you running grafana on? -- CentOs

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1153

**Comment by widy21** [comment]
have you resolved this problem？I have the same scene with you，thank you.
