### ISSUE TITLE
is remove "read only editer" ?

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#10991]
in grafana 5.0, is remove "read only editer" ? 
http://play.grafana.org/d/000000012/grafana-play-home?orgId=1   which role user is it by default?

**Comment by bergquist** [comment]
Viewer will be default.
You can enable `read only editors` alike behavior with `viewers_can_edit` https://github.com/grafana/grafana/blob/master/conf/sample.ini#L212

**Comment by ntting** [comment]
@bergquist Thank you for your prompt reply！！
