### ISSUE TITLE
Option to align tables

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1099]
The legend table option is great. Would it be possible to add an option to fix its size, so that across panels the graph time points can still align? At the moment I have this, where the longer metric aliases in the second graph mean that vertically the times are at different points between the two graphs

![2014-11-19_14-58-47](https://cloud.githubusercontent.com/assets/3671582/5107813/99dca528-6ffc-11e4-9a2b-0844d7f4122e.png)

**Comment by Iker-Jimenez** [comment]
I am interested in this feature too, maybe add a % setting for the graph and leave the rest for the legend table?

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/3437
