### ISSUE TITLE
Auth proxy authenticated user still shown login page

### ISSUE THREAD

**Issue by ckloote** [grafana/grafana#10997]
Using Grafana 4.6.3 on CentOS 7.2, I’m attempting to get auth proxy to work in conjunction with an anonymous org for non-authenticated users. This is mostly working but for one small issue.

I’ve set up auth proxy as described in the Grafana docs, except for I’m redirecting to my auth provider only then the /login URL is hit. This way unauthenticated users can still access the page. Then, a user selecting login will get redirected to the 3rd party auth provider, and any user with a session should be treated as logged in.

What’s happening is that when a user clicks the login link they do get redirected to the 3rd party auth page, log in successfully, and get redirected back. But instead of landing on their default dashboard, they land on the Grafana login page. This happens even though the user session is definitely known to Grafana. This can be confirmed by viewing source on the login page, and the user id can be seen in `window.grafanaBootData`. Also, if you then just change the URL in the browser window by hand from the /login URL to the root URL, the the page loads in the context of the logged in user (userid set, editor role set instead of viewer role).

This appears to be a bug, as discussed in my community post on this issue here:

https://community.grafana.com/t/auth-proxy-authenticated-user-still-shown-login-page/5344

I wanted to ensure a GitHub issue got submitted on it, so I'm effectively reposing here. 

Thanks!

**Comment by torkelo** [comment]
Your custom login provider needs to redirect the home url, not login url. 

The login page will be shown if you try to go it that url, even with autoproxy configured
