### ISSUE TITLE
alerting with subqueries not working properly (Influx datasource)

### ISSUE THREAD

**Issue by shreyasns** [grafana/grafana#10990]
I'm using Grafana 4.2 and when I run the following query 
<pre>
select count("first") from (select first("value") from "jvm.memory.total.max"  WHERE $timeFilter group by  time(2m) , host, dc limit 10)  WHERE $timeFilter group by time(2m),  dc
</pre>
Alert always fails as it gets a 400 response from influx. The reason being the $timeFilter in the outer query is not being replaced. 

logs from influx
<pre>
query?db=cassandra&epoch=s&q=select+count%28%22first%22%29+from+%28select+first%28%22value%22%29+from+%22jvm.memory.total.max%22++WHERE+time+%3E+now%28%29+-+5m+group+by++time%282m%29+%2C+host%2C+dc+limit+10%29++WHERE+%24timeFilter+group+by+time%282m%29%2C++dc HTTP/1.1" 400 79 "-"
</pre>

**Comment by bergquist** [comment]
This have been fixed in 4.3.0 https://github.com/grafana/grafana/issues/7969
Please upgrade :)
