### ISSUE TITLE
[Feature request] Use labels/terms as buckets in heatmap

### ISSUE THREAD

**Issue by pablorf-dev** [grafana/grafana#10993]
- What Grafana version are you using?
4.6.3, also tested in 5 beta
- What datasource are you using?
ElasticSearch
- What OS are you running grafana on?
Debian 9
- What did you do?
Try to setup a heatmap with term as an histogram
- What was the expected result?
A heatmap with label/term/category as Y axis, color as count, and X axis as time.
- What happened instead?
Get an error 

What I want to do is to transform this histogram into a time heatmap with its labels in Y axis:

![imagen](https://user-images.githubusercontent.com/15102049/36534034-aeb1653c-17c5-11e8-9543-7a4116cab9f4.png)

Related to #8529 ?

**Comment by KrisTC** [comment]
If I understand your request properly. I managed to get this to work working. But it doesn't quite work they way I want. I am using elastic search source.

![image](https://user-images.githubusercontent.com/16052773/53579866-4d421e00-3b72-11e9-893a-6118b25e4a80.png)

I do my query and get back the data I want:
![image](https://user-images.githubusercontent.com/16052773/53579988-8da19c00-3b72-11e9-99ad-c882b8920ad4.png)

Then select Data format as "Time series buckets".
That is it really.

But when showing in this way I don't have changing the "count" to something else. In my case, I want to show duration rather than count. The value in my query is a duration, I really want to specify the label for "count" and also the unit. So that time in ms can be formatted like it does on other charts.

![image](https://user-images.githubusercontent.com/16052773/53580378-60a1b900-3b73-11e9-9b2f-bb58173c5669.png)

When showing in this way I would also prefere it to describe the bucket they way it does. The data values are aligned with the result not the pairing.

Hope this is helpful / and feature can be made better:

In case it is useful here is my query response:
`
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/2/_msearch",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"mmv-perf-filebeat-aws-*\",\"max_concurrent_shard_requests\":256}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1551353765562\",\"lte\":\"1551353800405\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"beat.hostname.keyword:MGR  AND uri.keyword:*api\\\\/event*\"}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"ResponseCode.keyword\",\"size\":10,\"order\":{\"_term\":\"desc\"},\"min_doc_count\":1},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"10s\",\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":\"1551353765562\",\"max\":\"1551353800405\"},\"format\":\"epoch_millis\"},\"aggs\":{\"1\":{\"avg\":{\"field\":\"ResponseDuration\"}}}}}}}}\n"
  },
  "response": {
    "responses": [
      {
        "took": 2,
        "timed_out": false,
        "_shards": {
          "total": 15,
          "successful": 15,
          "skipped": 0,
          "failed": 0
        },
        "hits": {
          "total": 9687,
          "max_score": 0,
          "hits": []
        },
        "aggregations": {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "2": {
                  "buckets": [
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353760000",
                      "key": 1551353760000,
                      "doc_count": 0
                    },
                    {
                      "1": {
                        "value": 3151
                      },
                      "key_as_string": "1551353770000",
                      "key": 1551353770000,
                      "doc_count": 1
                    },
                    {
                      "1": {
                        "value": 6861.571428571428
                      },
                      "key_as_string": "1551353780000",
                      "key": 1551353780000,
                      "doc_count": 7
                    },
                    {
                      "1": {
                        "value": 4174
                      },
                      "key_as_string": "1551353790000",
                      "key": 1551353790000,
                      "doc_count": 16
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353800000",
                      "key": 1551353800000,
                      "doc_count": 0
                    }
                  ]
                },
                "key": "\"410/Gone\"",
                "doc_count": 24
              },
              {
                "2": {
                  "buckets": [
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353760000",
                      "key": 1551353760000,
                      "doc_count": 0
                    },
                    {
                      "1": {
                        "value": 386.4852941176471
                      },
                      "key_as_string": "1551353770000",
                      "key": 1551353770000,
                      "doc_count": 204
                    },
                    {
                      "1": {
                        "value": 319.75
                      },
                      "key_as_string": "1551353780000",
                      "key": 1551353780000,
                      "doc_count": 4
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353790000",
                      "key": 1551353790000,
                      "doc_count": 0
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353800000",
                      "key": 1551353800000,
                      "doc_count": 0
                    }
                  ]
                },
                "key": "\"409/Conflict\"",
                "doc_count": 208
              },
              {
                "2": {
                  "buckets": [
                    {
                      "1": {
                        "value": 25948.138461538463
                      },
                      "key_as_string": "1551353760000",
                      "key": 1551353760000,
                      "doc_count": 65
                    },
                    {
                      "1": {
                        "value": 10079.466666666667
                      },
                      "key_as_string": "1551353770000",
                      "key": 1551353770000,
                      "doc_count": 15
                    },
                    {
                      "1": {
                        "value": 10142.452380952382
                      },
                      "key_as_string": "1551353780000",
                      "key": 1551353780000,
                      "doc_count": 42
                    },
                    {
                      "1": {
                        "value": 10205.604166666666
                      },
                      "key_as_string": "1551353790000",
                      "key": 1551353790000,
                      "doc_count": 48
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353800000",
                      "key": 1551353800000,
                      "doc_count": 0
                    }
                  ]
                },
                "key": "\"304/Not Modified\"",
                "doc_count": 170
              },
              {
                "2": {
                  "buckets": [
                    {
                      "1": {
                        "value": 25770.35135135135
                      },
                      "key_as_string": "1551353760000",
                      "key": 1551353760000,
                      "doc_count": 37
                    },
                    {
                      "1": {
                        "value": 5982.222222222223
                      },
                      "key_as_string": "1551353770000",
                      "key": 1551353770000,
                      "doc_count": 27
                    },
                    {
                      "1": {
                        "value": 7352.375
                      },
                      "key_as_string": "1551353780000",
                      "key": 1551353780000,
                      "doc_count": 32
                    },
                    {
                      "1": {
                        "value": 4890.894736842105
                      },
                      "key_as_string": "1551353790000",
                      "key": 1551353790000,
                      "doc_count": 38
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353800000",
                      "key": 1551353800000,
                      "doc_count": 0
                    }
                  ]
                },
                "key": "\"204/No Content\"",
                "doc_count": 134
              },
              {
                "2": {
                  "buckets": [
                    {
                      "1": {
                        "value": 21262
                      },
                      "key_as_string": "1551353760000",
                      "key": 1551353760000,
                      "doc_count": 3
                    },
                    {
                      "1": {
                        "value": 16.12
                      },
                      "key_as_string": "1551353770000",
                      "key": 1551353770000,
                      "doc_count": 25
                    },
                    {
                      "1": {
                        "value": 14
                      },
                      "key_as_string": "1551353780000",
                      "key": 1551353780000,
                      "doc_count": 1
                    },
                    {
                      "1": {
                        "value": 8
                      },
                      "key_as_string": "1551353790000",
                      "key": 1551353790000,
                      "doc_count": 6
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353800000",
                      "key": 1551353800000,
                      "doc_count": 0
                    }
                  ]
                },
                "key": "\"201/Created\"",
                "doc_count": 35
              },
              {
                "2": {
                  "buckets": [
                    {
                      "1": {
                        "value": 22092.6
                      },
                      "key_as_string": "1551353760000",
                      "key": 1551353760000,
                      "doc_count": 15
                    },
                    {
                      "1": {
                        "value": 487.560773480663
                      },
                      "key_as_string": "1551353770000",
                      "key": 1551353770000,
                      "doc_count": 1448
                    },
                    {
                      "1": {
                        "value": 660.4284128745838
                      },
                      "key_as_string": "1551353780000",
                      "key": 1551353780000,
                      "doc_count": 901
                    },
                    {
                      "1": {
                        "value": 1511.2875816993464
                      },
                      "key_as_string": "1551353790000",
                      "key": 1551353790000,
                      "doc_count": 306
                    },
                    {
                      "1": {
                        "value": null
                      },
                      "key_as_string": "1551353800000",
                      "key": 1551353800000,
                      "doc_count": 0
                    }
                  ]
                },
                "key": "\"200/OK\"",
                "doc_count": 2670
              }
            ]
          }
        },
        "status": 200
      }
    ]
  }
}
`

**Comment by KrisTC** [comment]
also note the weird bug that made me not have confidance that it was working properly: https://github.com/grafana/grafana/issues/13019

**Comment by pkubiak** [comment]
@KrisTC Hi, you can change alignment of bucket labels (in Grafana 7.0.*) by setting `Axis -> Y Axis -> Bucket Bound = middle` in panel configuration.

**Comment by pbaumard** [comment]
It seems that using non numeric labels in time series buckets is a very common use case for heatmaps. See #26317 for example.

We are using it, and for now it seems the only minor issues are:
- the "count" in tooltip (as in [previous comment](https://github.com/grafana/grafana/issues/10993#issuecomment-468334316)), which could be something generic such as "value" in our case
- the flood of "Error parsing histogram label" in console from [heatmap_data_converter.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/heatmap/heatmap_data_converter.ts#L83).

**Comment by leeoniya** [comment]
the new heatmap panel allows you to customize "count" in the tooltip and should work better for this case. closing as resolved.
