### ISSUE TITLE
Adhoc filter of Table causes Browser error: 'indexOf' of null at Object.getAdhocFilters (templateSrv.js:87)

### ISSUE THREAD

**Issue by elapse2039** [grafana/grafana#11007]
- What Grafana version are you using?
Community  Grafana v4.6.3 (commit: 7a06a47)

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
Ubuntu 16.04

- What did you do?
Created a dashboard, created a table and clicked on magnifying glass to filter out an entry.  The table simply lists in descending order the count for specific term in a record and contains ~15 items.  Then selecting a table entry initially showed a filtered dashboard... using adhoc filter.  At some point, it then started to show nothing with javascript exception in the browser.

- What was the expected result?
The entire dashboard would update itself and create an adhoc filter.  This worked initially, then suddenly without explanation stopped working.

- What happened instead?
For some time, the dashboard updated and filtered out all data except matching the entry I selected in table.  However, I saved the dashboard and then tried to repeat this filtering... the filter was created but all dashboard widgets went blank - where they had previously shown data.  The Chrome browser logs showed this for each dashboard widget:

Panel data error: TypeError: Cannot read property 'indexOf' of null
    at Object.getAdhocFilters (templateSrv.js:87)
    at t.query (datasource.ts:289)
    at e.issueQueries (metrics_panel_ctrl.ts:281)
    at e.issueQueries (module.ts:229)
    at u (angular.js:17051)
    at angular.js:17095
    at f.$digest (angular.js:18233)
    at angular.js:18462
    at i (angular.js:6362)
    at angular.js:6642

**Comment by torkelo** [comment]
unable to replicate, can you consistently get the same error? 

Can you replicate here: 
http://play.grafana.org/d/000000140/github-repo-trends-comments?orgId=1&var-repo=grafana%2Fgrafana&var-interval=14d

**Comment by nickfr** [comment]
I have the same error on GrafanaCloud. I get a second "Filters +" alongside the first - deleting the filter doesn't help and the dashboard is irretrievable without reverting.

<img width="254" alt="screen shot 2018-02-28 at 08 37 28" src="https://user-images.githubusercontent.com/12948741/36777775-ac514f5e-1c62-11e8-90c7-fe76a05aa487.png">

**Comment by torkelo** [comment]
Can you open templating section and show the settings for the ad hoc variable , what data source does it use?

What data source does the table panel use ? The ad hoc filters table integration does not work if the table data source is mixed or using a data source variable

**Comment by nickfr** [comment]
This is what I see in the templating section for both of the filters in there
<img width="599" alt="screen shot 2018-02-28 at 10 27 02" src="https://user-images.githubusercontent.com/12948741/36782804-04642aae-1c72-11e8-852b-4f5661563644.png">

My dashboard has a mix of table and graph panels - two different data sources are used but both are elastic search.

Any idea how I reset this? (clearly I can revert but would lose changes although it's not a huge deal) as the dashboard is broken. Going into templating and deleting those filter variables does not fix the problem.

If it is the mix of data sources then I guess I also need to stop the user being able to filter?

thanks

**Comment by torkelo** [comment]
You will have to remove the ad hoc filter (from templating setting view). Or you ca fix the problem by selecting one of your elasticsearch dataource in the data source drop down.

The ad hoc filters only applies to one data source , if you have two data elasticsearch datasources you have to add two ad hoc filters manually.

**Comment by fatalglitch** [comment]
I'm getting this same error anytime I try to apply an ad-hoc filter, by clicking the "+ magnifying glass" on elasticsearch dashboards.

Elasticsearch 5.4.5
Grafana v4.6.0-pre1 (commit: 3a1e70d) 

> TypeError: Cannot read property 'indexOf' of null
>     at Object.getAdhocFilters (https://grafana.my.site/public/build/0.035b87ffd4860776b1d4.js:1:414723)
>     at t.query (https://grafana.my.site/public/build/0.035b87ffd4860776b1d4.js:7:76340)
>     at e.issueQueries (https://grafana.my.site/public/build/0.035b87ffd4860776b1d4.js:7:19548)
>     at e.issueQueries (https://grafana.my.site/public/build/0.035b87ffd4860776b1d4.js:7:256534)
>     at u (https://grafana.my.site/public/build/vendor.dfc053f42dd8fa712242.js:43:68722)
>     at https://grafana.my.site/public/build/vendor.dfc053f42dd8fa712242.js:43:69127
>     at f.$digest (https://grafana.my.site/public/build/vendor.dfc053f42dd8fa712242.js:43:74824)
>     at f.$apply (https://grafana.my.site/public/build/vendor.dfc053f42dd8fa712242.js:43:76638)
>     at f.i.updateVariableValue (https://grafana.my.site/public/build/app.d8ac25420c5bc428d29e.js:8:10336)
>     at f.i.switchToLink (https://grafana.my.site/public/build/app.d8ac25420c5bc428d29e.js:8:10652)

**Comment by fatalglitch** [comment]
Just upgraded to Grafana 5.1.2 and still having the same issues. Was hopeful this was fixed in newer versions.

> TypeError: Cannot read property 'indexOf' of null
>     at t.getAdhocFilters (https://grafana/public/build/0.5c89ac3fc7a3e78b3629.js:1:57726)
>     at t.query (https://grafana/public/build/0.5c89ac3fc7a3e78b3629.js:7:99935)
>     at e.issueQueries (https://grafana/public/build/0.5c89ac3fc7a3e78b3629.js:7:17849)
>     at e.issueQueries (https://grafana/public/build/0.5c89ac3fc7a3e78b3629.js:7:294640)
>     at u (https://grafana/public/build/vendor.0cea50118711e7e6c839.js:87:69119)
>     at https://grafana/public/build/vendor.0cea50118711e7e6c839.js:87:69565
>     at d.$digest (https://grafana/public/build/vendor.0cea50118711e7e6c839.js:87:75262)
>     at d.$apply (https://grafana/public/build/vendor.0cea50118711e7e6c839.js:87:77076)
>     at HTMLButtonElement.<anonymous> (https://grafana/public/build/vendor.0cea50118711e7e6c839.js:87:148891)
>     at HTMLButtonElement.dispatch (https://grafana/public/build/vendor.0cea50118711e7e6c839.js:82:34743)

**Comment by marefr** [comment]
@fatalglitch please include your full dashboard json model for further help

**Comment by torkelo** [comment]
Are you using a mixed data source in the panel?

**Comment by torkelo** [comment]
closing due to lack of updates. Will reopen when we have more info on the panel & dashboard settings used (like what table data source is, etc). The ad hoc filters seem to have no data source defined which looks strange, maybe mixed data source is used or a variable data source?
