### ISSUE TITLE
Please add radiation units

### ISSUE THREAD

**Issue by victorclaessen** [grafana/grafana#11001]
I added common units in radiation and health physics monitoring, Bq, Ci, Gy, rad, Sv, rem. C/kg, R, Sv/h.
PR #11000

**Comment by bergquist** [comment]
Interesting. Is there any chance you could share some info about why you need those units and how you use Grafana? You can reach me on carl at grafana.com is you want to talk more in private. 

Btw. We will merge this to 5.1 regardless if you want to share or not :)

**Comment by bergquist** [comment]
Closed by #11000
