### ISSUE TITLE
Cannot see a way to deselect/remove adhoc "Filter" from dashboard

### ISSUE THREAD

**Issue by elapse2039** [grafana/grafana#11008]
- What Grafana version are you using?
Community  Grafana v4.6.3 (commit: 7a06a47)

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
Ubuntu 16.04 server, U16.04 Desktop using Chrome browser.

- What did you do?
Created a dashboard, created a table and clicked on magnifying glass to filter out an entry.  The adhoc filter appears at the top left handside of the dashboard.

The problem I have is I cannot figure out how to remove the adhoc filter.  I see "Filter" and can edit and change the entries but cannot see any UI button or way to remove the filter.  I have to reload the page entirely ensuring the filter URI params are taken out.  

As a user how do I deselect/remove the adhoc filter once it has been applied to a dashboard?

**Comment by torkelo** [comment]
if you click on the filter key the top item is "-- remove filter --"

**Comment by elapse2039** [comment]
Thanks for the tip.  The -- remove filter -- only appears if I select 2 days of history or less.

If I select 7,30 days of history, then clicking on the filter key there is no top item... there are no items whatsoever... there is just a empty text box to enter text in.

**Comment by elapse2039** [comment]
I've also just noticed all drop-downs are blank if I use >2 days history timeline.  This includes when I attempt to add a Graph to a panel, and try to build out a metric query.  The term's drop down box is blank, editable text box.

**Comment by torkelo** [comment]
Sounds like you get a JavaScript error , can you open chrome dev console and look for errors there ?

**Comment by elapse2039** [comment]
I dont get a javascript error but I see a 404... from an elasticsearch mapping query.  This happens until I shrink the time to within a period that I know has data... like 1hr instead of 24hr window (only last 3hrs of data) then the filter terms is populated.

https://aaa.abc.com/g1/api/datasources/proxy/3/logstash-exp-2018.02.26/_mapping 404 (Not Found)

**Comment by MichalDuma** [comment]
Any updates? I have the same issue. 
Everything is fine if I select 2 days of history or less. Then --remove filter-- option is available.
But if I select 7,30 days of history, then clicking on the filter key there is no top item... there are no items whatsoever... there is just a empty text box to enter text in.

**Comment by torkelo** [comment]
7.3 days ? Can you open browser dev tools console and check for errors? What is network the request and response when you click the ad hoc filter key drop down?

**Comment by MichalDuma** [comment]
7, 30 means - when I select 7 or 30 days

I checked for errors. When I selected 30 days I get error 404 which begins with:

`Possibly unhandled rejection: {"data":{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id"`

So it looks like it doesn't know how to handle exception when there is no index for some days in selected timeframe.

**Comment by torkelo** [comment]
yes, should show error in this case.

**Comment by MichalDuma** [comment]
why so?
when I choose range e.g. last 30 days I don't have info if index existed or not 30 days ago.
So when I choose last 30days and create filter then I can't remove it because of this error. 
So probably it shouldn't allow me to choose range 30days if index doesn't exist instead of showing error.

**Comment by yarix** [comment]
in my case i don't get to see the --remove filter-- on any time range.
the error is 405 method not allowed:
![image](https://user-images.githubusercontent.com/6409857/64942948-119f4500-d873-11e9-8d49-2cff340feff2.png)

BTW-I have editor role.
