### ISSUE TITLE
API error message red herring "Dashboard" vs "dashboard"

### ISSUE THREAD

**Issue by grantoverby** [grafana/grafana#11009]
Grafana docs specify a json key “**d**ashboard”. http://docs.grafana.org/v4.2/http_api/dashboard/

The error I got from Grafana: [{"fieldNames":["**D**ashboard"],"classification":"RequiredError","message":"Required"}]

Here's impact of the bug, in my case:

Docs must be wrong, let me resend with a capital D.
Same error.
Clearly this must be a bug in Grafana, but nothing on google.
Let’s send with dashboard and Dashboard in the document.
Still doesn’t work.
To the source code…
Grafana is written in go, a language I don’t know; freaking awesome.
… an undisclosed amount of time goes by …
Source looks right. Maybe curl is screwing it up somehow??? Surely not, but…
curl --trace shows 7b 20 20 22 64 61 73 68 62 61 6f 72 64 22 3a 20 {  "dashb**ao**rd":
I couldn’t have…
I did: jq '{ dashb**ao**rd: . }'

I admit that 98% of the fault here lies with good ol' programmer hubris and my uncanny ability to out derp myself, but I'm placing 2% of the blame on the docs vs error message inconsistency.

**Comment by marefr** [comment]
Please spell dashboard correctly. It should not be *dashbaord* (not the a and o misplacement)

**Comment by grantoverby** [comment]
Ditto.... also shouldn’t be Dashboard
