### ISSUE TITLE
Multiple values selected form variable causing syntax error in postgres

### ISSUE THREAD

**Issue by snandan2290** [grafana/grafana#11004]
- Grafana version  = 5.0
- Datasource  = postgres
- OS = RHEL

i have on variable which is having values 100, 101, 102 and Multiple and All option is enabled, but when ever i chose All option grafana sending values like '100', '101', '102' but expected for postgres stored procedure is '100,101,102' so it is causing syntax error

**Comment by marefr** [comment]
I don't think that using postgres stored procedures from Grafana are supported. Please show me the query you're using.

The use case for variable with multiple values and select all is to use it with a `IN` clause, i.e. `WHERE something IN($my_variable). And for this it works as it should.

**Comment by marefr** [comment]
Should be possible to do now since #9911 is closed so I'm closing this.
