### ISSUE TITLE
"Copy invite" - Button generates invite URL without http port

### ISSUE THREAD

**Issue by OldSparkyMI** [grafana/grafana#11012]
Please include this information:
- What Grafana version are you using?
=> Grafana v5.0.0-beta4 (commit: 1de8891)
- What datasource are you using?
=> ./.
- What OS are you running grafana on?
=> via Docker
- What did you do?
=> Invite a new user
- What -was- is the expected result?
=> After clicking "Copy invite", a URL with port is copied
=> e.g.: https://somehost.de:3000/...
- What happened instead?
=> a URL without the port ist copied
=> e.g.: https://somehost.de/...

 
![image](https://user-images.githubusercontent.com/3809272/36645881-8c619d60-1a6f-11e8-9c68-a2ad2e44f8ed.png)

**Comment by marefr** [comment]
Please include your [server configuration](http://docs.grafana.org/installation/configuration/#server). Are you sure that you haven't forgot to include the port in your root_url?

**Comment by OldSparkyMI** [comment]
![grafana](https://user-images.githubusercontent.com/3809272/36661129-b6112a7a-1ada-11e8-85fe-7ccf2d617a60.png)

**Comment by marefr** [comment]
Then you should include the port in the root_url.

**Comment by OldSparkyMI** [comment]
Why @marefr ?
Every other link adds the port automatically. 
Everything works beside this link.

**Comment by torkelo** [comment]
think link is different as it is emailed as well so needs to be a complete full absolute url, all other links in the Grafana UI are relative (do not include domain or port) just `/org/users` for example.
