### ISSUE TITLE
Unable to save a datasource

### ISSUE THREAD

**Issue by mar1ged** [grafana/grafana#11019]
Grafana 4.6.3
Datasource Prometheus (2.1)
Running grafana on RHEL 7.2

I tried to add a datasource running on the same server. But all I get is a red box and an exclamation mark when trying to save and test:
![grafana_1](https://user-images.githubusercontent.com/16045549/36671167-0076537c-1afb-11e8-9c3e-0584793735bc.png)

The network trace of Chrome shows this:
![grafana_2](https://user-images.githubusercontent.com/16045549/36671179-0e6efd80-1afb-11e8-948f-f5c47195b3f7.png)

When I run `curl  http://localhost:9091` on the server Grafana is running on it seems like Prometheus can be reached:

`<a href="/graph">Found</a>.`

**Comment by torkelo** [comment]
you specified localhost and access Direct, so that means it will try to access prometheus on the same server you are running your browser on, switch to "proxy" mode if you want the prometheus communication to go via grafana-server

**Comment by mar1ged** [comment]
Sorry for that, I should have looked at the (i). I thought that "proxy" is a Internet Gateway (proxy)

![grafana_4](https://user-images.githubusercontent.com/16045549/36671949-c7d7bbca-1afd-11e8-8a73-3b16a22902de.png)
