### ISSUE TITLE
Grafana 5: white area over bottom panels in kiosk mode

### ISSUE THREAD

**Issue by futrix** [grafana/grafana#11010]
After upgrading from 4.6 to 5.0.0beta4 I've noticed that bottom panels are partially covered with white area in the kiosk mode (d-k). There is a scroll bar on the side.

I've tried clearing browser cache, different browser (Chrome on Windows, Ubuntu, and Firefox on Windows) - it's the same everywhere I try. 

![grafana5_white_field_bug](https://user-images.githubusercontent.com/22995814/36628897-2450e7e2-194f-11e8-9fac-404a4a36beba.PNG)

**Comment by jorgav** [comment]
Same, I can reproduce this using Firefox and Chrome.

**Comment by feiyuw** [comment]
+1

**Comment by marefr** [comment]
Verified. Same problem with dark theme
