### ISSUE TITLE
Singlestat text/sparkle showing outside the panel

### ISSUE THREAD

**Issue by JosephFY** [grafana/grafana#11022]
Please include this information:
- What Grafana version are you using?
 Grafana v4.4.3 (commit: 54c79c5)
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Redhat 7.4

Not sure if this is a bug itself or should be a PR. When creating singlstat panels with a large monitor size (using 22") and get opened by a smaller monitors ( laptop 14") it's showing like this with the font and spark lines being outside the panel
![image](https://user-images.githubusercontent.com/28739923/36677383-9bf60dec-1ad3-11e8-9940-40ab42478b09.png)

looks find when I resize the stat phone size no smaller percentage

![image](https://user-images.githubusercontent.com/28739923/36677429-bdcc085e-1ad3-11e8-98ff-44fdba8c97c7.png)

A solution might be to have an option to wrap the text if it's  **ONLY**  bigger then the panel. Having it dynamically wrap helps a lot for the dashboards look and creation cross different monitor sizes.

Thank you

**Comment by torkelo** [comment]
as you can see the text is to big/long your panel
