### ISSUE TITLE
Alerting based on series rather than all data?

### ISSUE THREAD

**Issue by jacktang** [grafana/grafana#11025]
Hello,

Is it possible to create alerting based on time series rather than all data? Say 5 servers' system load are monitored (host as tag), and if 4 time series data are stored in backend, the alerting should be fired.

**Comment by bergquist** [comment]
Grafana does not support that naitivly. But your datasource might have a way of doing that. What datasource are you using?

**Comment by jacktang** [comment]
the backend is influxdb

**Comment by bergquist** [comment]
Sorry for the slow response... Must have lost this in the sea of notifications I get :(

This answer describes how to get the series count using influxdb https://community.influxdata.com/t/how-to-get-series-count-from-measurement/4492
