### ISSUE TITLE
Use fields values in titles, links etc.

### ISSUE THREAD

**Issue by vmoloko** [grafana/grafana#11026]
Example: I have some entries like "$metric,environment=...,host=...,component=...,link=...   value=...\n" in InfluxDB.
In Grafana I have several dashboards for each env with many Singlestat panels with healthchecks for each host.
![image](https://user-images.githubusercontent.com/16567139/36715927-799b5226-1ba9-11e8-80ac-0cb73a77db3b.png)
I would like to use values of fields "host" and "link" when I set the title and link. I tried: "link", $link, $tag_link etc. I can't use these fields as template variables because I want to divide my Singlestats between several rows.
Can I do that somehow?
Thank you.

I am using Grafana v4.6.2 (commit: 8db5f08), InfluxDB.

**Comment by torkelo** [comment]
no you cannot use metric query results in the panel drill down links, that is only possible from the table panel.

**Comment by vmoloko** [comment]
@torkelo Is it going to be implemented? It seems to be a useful feature. I mean not only in links but everywhere inside a singlestat.
