### ISSUE TITLE
grafana Alert "execution timeout" and "Failed to send webhook", "context deadline exceeded"

### ISSUE THREAD

**Issue by YouZhengChuan** [grafana/grafana#11020]
- Verison: grafana 2.4
- SystemOS: MacOS
- GoVersion: golang 1.8

## Alert configure

![image](https://user-images.githubusercontent.com/3882312/36671796-02bcadba-1b38-11e8-901e-0e7fff9f0a58.png)

## Alert execution logs
![image](https://user-images.githubusercontent.com/3882312/36671970-93a4d816-1b38-11e8-9415-d2ba5e61fd3a.png)

## Analysis
The timeout for each goroutine is limited to 30 seconds. If the query time is longer than 30 seconds, the failure notification will not be sent via the webhook.

- timeout set
https://github.com/grafana/grafana/blob/6f4c043dd672b7f4ac6f25d00b9b22ebbeb597cf/pkg/services/alerting/engine.go#L111

- ctxhttp timeout
https://github.com/grafana/grafana/blob/6f4c043dd672b7f4ac6f25d00b9b22ebbeb597cf/pkg/services/notifications/webhook.go#L86

**Comment by bergquist** [comment]
This should be improved. 

Query/parsing data should have a timeout of 30s.
If that's finished within 30s notifications should not be canceled.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/issues/14701
