### ISSUE TITLE
Grafana 5: Panel plugin render boundry

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#11023]
After upgrading to the 5.4 beta, my issue is that my panel plugins are no longer allowed to draw outside of their pre-defined boxes.

I'm fairly certain that this is by design (I think I even remember reading about this change coming), and it makes sense for the most part. But for my use-case, without a workaround, it prevents me from moving to Grafana 5.x.

My specific use-case is a search plugin I've built for my team. The specifics are not important, but it enables search-as-you-type against our elasticsearch cluster, and displays completion suggestions in a dropdown menu. If the panel for that search-bar is only as tall searchbox itself, then the dropdown gets cut off. If I make the panel tall enough to accommodate the dropdown, then there is a lot of wasted space when the dropdown is not visible.

Mostly I'm interested in a wrokaround. Although, with that usecase in mind, I do not think it's particularly odd for a plugin to need to draw outside of its initial panel.

**Comment by torkelo** [comment]
Can’t think of a workaround , the drop down needs to live outside the panel. Maybe if you used popoverSrv and with that opened a popover

**Comment by Ultraseamus** [comment]
I'll try popoverSrv.

Right now I've hacked it well enough to work. I'm basically using css and jquery to edit my plugin's parent elements to make overflow visible, and set a z-index. It's not the cleanest solution, but it gets the job done.

As a low-priority feature request, I do think this should be addressed. I suspect other plugin developers will run into a similar issue.

It could be implemented as a "General" panel option. Two additions: a "Hide Overflow" flag, and a "z-index" value for when hide overflow is false.
