### ISSUE TITLE
Alert State history does not update when alerting series changes

### ISSUE THREAD

**Issue by sparr** [grafana/grafana#11039]
I am using hosted Grafana.net with a hosted Graphite data source. I have an alert configured against a graphite query with a wildcard, which produces multiple series. When the alert fires, the State history for the alert shows something like "first.series=alertingvalue1, second.series=alertingvalue2". If both of those series stop alerting then a new history entry appears saying "OK", and a future alert gets its own entry. If, however, second.series gets fixed and third.series starts alerting then I don't get a new alert (which is a separate concern) and the point of this bug report is that the single entry in the state history still shows "first.series=alertingvalue1, second.series=alertingvalue2" instead of what I want which is "first.series=alertingvalue1, third.series=alertingvalue3".

**Comment by sparr** [comment]
My workaround for this is to use the "Test Rule" button, but that only tells me which series are problematic at the current time, and can't tell me the state of the alert in the past.

**Comment by torkelo** [comment]
this behavior is described in detail in the docs. http://docs.grafana.org/alerting/rules/#multiple-series

we want to improve multi series support by adding per series state tracking, there is already a feature request / issue for that so closing this

**Comment by sparr** [comment]
@torkelo The docs describe the notification-sending behavior, not the state history behavior. I understand how it makes sense for them to mirror each other due to reflecting the same backend information, but that doesn't make the documentation informative on the subject.

**Comment by torkelo** [comment]
well state history & notifications are the same in this case as we send out notifications when alert rule change state. And if an alert rule that has a query that returns multiple series and 2 series are triggering the alert condition, so rule goes to alerting, then if 2 other series cause the alert to fire the alert rule is still in alerting so no state change (no alert history item, or notification happens)
