### ISSUE TITLE
Singlestat sparkline doesn't show crosshair

### ISSUE THREAD

**Issue by spiffytech** [grafana/grafana#11033]
I'm using Grafana 4.6.3, with data sources like ElasticSearch and NewRelic.

We have a bunch of Single Stat graphs with sparklines because we want both a number and a graph in the same cell. 

However, we don't get crosshairs or date labels on our sparklines, so it's difficult to correlate our sparklines with each other or with our regular graphs. Please add support for crosshairs on sparklines.

**Comment by torkelo** [comment]
sparklines are just that sparklines, if you need graphs you need the graph panel.

**Comment by torkelo** [comment]
we might add a big number value to the graph panel at some point :)
