### ISSUE TITLE
[5.0-beta5]missing profile icon happened again!

### ISSUE THREAD

**Issue by tangyong** [grafana/grafana#11038]
Missing profile icon happened again while I built 5.0-beta5 on my machine which can access internet.

![error1](https://user-images.githubusercontent.com/187414/36780870-333f21a2-1caf-11e8-9f2c-5806eae54821.png)

please team looks at the above.

Thanks!

**Comment by tangyong** [comment]
althouth #10426 has been fixed in beta1, today, after I built beta5, the issue happened again.

**Comment by tangyong** [comment]
Noting if having not found, should use user_profile.png:

func newNotFound() *Avatar {
	avatar := &Avatar{notFound: true}

	// load user_profile png into buffer
	path := filepath.Join(setting.StaticRootPath, "img", "user_profile.png")

	if data, err := ioutil.ReadFile(path); err != nil {
		log.Error(3, "Failed to read user_profile.png, %v", path)
	} else {
		avatar.data = bytes.NewBuffer(data)
	}

	return avatar
}

However, my console has not displayed "Failed to read user_profile.png...", instead, the following tells us avator directory exists , but the image has not been broken...

![err2](https://user-images.githubusercontent.com/187414/36781368-a7a49e54-1cb0-11e8-91ee-8714d11bdf34.png)

**Comment by marefr** [comment]
Do you have internet access to fetch avatar from gravatar?

**Comment by tangyong** [comment]
@marefr  yes, I can access https://en.gravatar.com/ via proxy.

**Comment by tangyong** [comment]
or saying: how I should confirm I can have internet access to fetch avatar from gravatar based on your meaning, then I will confirm?

**Comment by marefr** [comment]
Thanks. That was what I meant. If you switch to network tab in chrome dev tools - what does the request/response look like? Could it be a caching problem? Try a refresh hard of the browser tab

**Comment by tangyong** [comment]
@marefr pl. seeing the following image

![err2](https://user-images.githubusercontent.com/187414/36790080-a128d14e-1cce-11e8-9d7c-ec4c790539a9.png)

**Comment by tangyong** [comment]
@torkelo 

yes, I used http proxy to access internet, pl. seeing the above image

**Comment by tangyong** [comment]
pl. seeing the above again while loading the avatar

![err3](https://user-images.githubusercontent.com/187414/36790314-561dd07c-1ccf-11e8-9c47-352b29501031.png)

**Comment by tangyong** [comment]
![err4](https://user-images.githubusercontent.com/187414/36790705-abd7a55a-1cd0-11e8-887c-f1b16d4a54da.png)

![err5](https://user-images.githubusercontent.com/187414/36790718-b2bc528a-1cd0-11e8-931e-54b5809e32f2.png)

**Comment by tangyong** [comment]
heads displays status 200, however, response is "failed to load response data", indeed, I can access access https://en.gravatar.com/ via my http proxy.

**Comment by tangyong** [comment]
@torkelo 

haha,  I understood you said because the getting avatar code is in backend using go language. I will see my env http_proxy and https_proxy setting.
