### ISSUE TITLE
Cloudwatch Provisioning Grafana - Keys not added?

### ISSUE THREAD

**Issue by ThomasVdBerge** [grafana/grafana#11030]
https://github.com/grafana/grafana/issues/11005

Thank you for updating the documentation!

Unfortunately, this does not seem to work. The keys do not get added. Here is my datasources configuration:

datasources:
- name: Cloudwatch
  type: cloudwatch
  access: direct
  org_id: 1
  json_data:
    authType: "keys"
    defaultRegion: "eu-west-1"
    trends: 1
  secure_json_fields:
    accessKey: ****
    secretKey: ****
  version: 1
  editable: true

When looking at a dashboard which uses it, it shows nothing. 

Docker error logs shows something like:
> Metric request error" logger=context userId=1 orgId=1 uname=admin error="Failed to call cloudwatch:ListMetrics

When looking at the datasource on the web UI, accessKey and secretKey are empty (While, normally it should ay something like "Configured"

**Comment by davidjeddy** [comment]
@ThomasVdBerge  you might want to censor the accessKey and secretKey, else you'll wake up to someone spinning up services on your account and footing you the bill :).

**Comment by bergquist** [comment]
@davidjeddy good call. I've edited it but might be too late.

**Comment by ThomasVdBerge** [comment]
gewgewgew was by far not an original AWS key ;-)

**Comment by bergquist** [comment]
Your keys should be under `secureJsonData` 

ex https://github.com/grafana/grafana/commit/d95eabfeec00a2386a64db9461e119ff0c8ac4f6#diff-91d126a761668691c49c3ff0b5c238aaR205
