### ISSUE TITLE
String in value stat panels

### ISSUE THREAD

**Issue by sahilthapar** [grafana/grafana#1103]
I'm using influxDB and here's my use case,
I would like to show the current state of the machine, ACTIVE / INTERRUPTED / STOPPED in the panel. 
Is there any way of doing this currently ?

**Comment by steverweber** [comment]
the table panel will show strings.  So this might work.
https://github.com/grafana/grafana/pull/1771

**Comment by torkelo** [comment]
as of Grafana 2.1 you can now show string values in single stat panel, forgot to close this issue
