### ISSUE TITLE
Modify config.js with request ARGS

### ISSUE THREAD

**Issue by mebrunet** [grafana/grafana#1104]
I would love to be able to modify the config.js file based on request parameters

This way I could have "http://grafana-url" serve some default or example dashboard as specified in the config file but 

"http://grafana-url?iinfluxdb=db-name&influxuser=exampleuser&inlfuxpw=password...etc." 

would serve up a dashboard based on those config parameters.

This would allow me to get basic user functionality out of Grafana by simply making new databases and users on my influxdb.

Any thoughts on how I could do this. Thanks.

**Comment by torkelo** [comment]
Should be solved with the forthcoming grafana backend (comes with account management, where accounts have their own data sources)
