### ISSUE TITLE
Provide option for floating dashboard menus

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#11042]
We have some large dashboards that have several pages worth of panels with many (10+) variables. The user would be required to repeatedly scroll up and down to make menu selections as they progress with their observations.

The problem is finding an easy and elegant way to navigate these larger dashboards.
Making use of rows so you can hide parts of the dashboard only works if you aren't repeatedly refering to them all and feels a bit clumsy.

A floating top of dashboard menu area would be a nice way to acheive this and allow for quick variable selections whilst looking anywhere on the dashboard without loosing your point of focus with repeated scrolling, especially when toggling between selections that can be painful.

**Comment by vsdogra** [comment]
This would definitely be very much appreciated. It'll make a world of difference in Grafana's usability if the template variables are floating (sort of like the dashboard/time selector)

**Comment by GrzegorzLyp** [comment]
Can we have this feature soon?

**Comment by Daniel-Mompean** [comment]
any news ?

**Comment by torkelo** [comment]
Closing as this same as it's the same as https://github.com/grafana/grafana/issues/11166
