### ISSUE TITLE
Filter prometheus template label_values

### ISSUE THREAD

**Issue by benmathews** [grafana/grafana#11047]
I would like to be able to pass a regular expression to prometheus template label_values so that I can have a subset of the label values returned in the template variable. 

My use case is I have lots of deployments. For a given deployment N, there is also going to be a N_autoscaler and N_canary that I would like to ignore. 

The syntax for defining a variable could be something like

label_values(deployment, '^.*(-autoscaler|-canary).*$')

**Comment by roidelapluie** [comment]
You can do that:

label_values({deployment!~".(-autoscaler|-canary)."}, mylabel)

**Comment by benmathews** [comment]
When I worked out a query I got an error.

`label_values(avg(kube_deployment_spec_replicas{namespace="platform",deployment!~".*(-autoscaler|-canary)"}) by (deployment) > 0, deployment)`

I've got two prometheus for HA, but realized that grafana was probably already deduping, so I successfully tried 

`label_values(kube_deployment_spec_replicas{namespace="platform",deployment!~".*(-autoscaler|-canary)"}, deployment)`

What would be the best way to get this documented?

**Comment by roidelapluie** [comment]
Try query_result(query) with a regex to extract the labels
