### ISSUE TITLE
Grafana 5.0.0 does not single quotes template variable value in dashboard with PostgreSQL datasource

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#11049]
- What Grafana version are you using?
5.0.0
- What datasource are you using?
PostgreSQL 10.2
- What OS are you running grafana on?
Debian 8
- What did you do?
testing new Grafana 5.0.0

Looks like new Grafana 5.0.0 does not add single quotes around template variable value so dashboards with PostgreSQL datasource now fail with error 
`Templating init failed 
pq: column "asos" does not exist`

Reason:

* query sent by Grafana 4.6.3 - see `shop = 'asos' ...` line:

"SELECT
  now() as time,
  shop_country as metric,
  sum(value) as value
FROM
  aggregations.dashboards_external
WHERE
  metricname = 'returns_after_billing_external' AND 
  "structure" = 'mdateshopcountry' AND 
  shop = 'asos' AND 
  shop_country = 'SHOPTOTAL' AND 
  $__timeFilter(partition_date)
group by 1,2
order by value desc
limit 10"

* query sent by Grafana 5.0.0 - see `shop = asos ...` line

"SELECT
  now() as time,
  shop_country as metric,
  sum(value) as value
FROM
  aggregations.dashboards_external
WHERE
  metricname = 'returns_after_billing_external' AND 
  "structure" = 'mdateshopcountry' AND 
  shop = asos AND 
  shop_country = 'SHOPTOTAL' AND 
  $__timeFilter(partition_date)
group by 1,2
order by value desc
limit 10"

Could you please look at it? Otherwise I like new Grafana 5 very much.
Great job. Thank you all very much.

**Comment by torkelo** [comment]
you need to check the "mulit-value" or "all" option for Grafana to handle the quoting

**Comment by machytkafitanalytics** [comment]
OK, thanks, it works now, but in Grafana 4.6.3 it worked as it is - without multi-value checked.
So this is a bit unfortunate breaking change. 
Thank you very much anyway.

**Comment by machytkafitanalytics** [comment]
we need to select only one value - as it worked in 4.6.3
this breaking change means I had to edit all queries and add single quotes

**Comment by torkelo** [comment]
Sorry about the breaking change, it was a mistake in earlier version of grafana that quoted single (non multi) variable. You need to manually quote it, reason is that if grafana quote it it severely limits where and how you can use a variable in the query

**Comment by machytkafitanalytics** [comment]
OK, fair enough
thank you
