### ISSUE TITLE
Disable signup still displays signup button on login page

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#11041]
There's still backend validation when trying to sign up so this not a critical fix.

**Comment by flopp999** [comment]
Reopen this, please reply if I shall open a new issue.
I have disabled Signup, I click "Forgot password" forgot-password page shows up correctly, but when I click Go Back I come to a login-page where Signup is visible. I can click on Signup and then fill in all fields, but as soon as I click to signup a red notification on top-right tell me that signup is disabled.
Why does Signup button shows up on Login after I click Go back?
Grafana 5.2.3
![signup](https://user-images.githubusercontent.com/21694965/44832426-2179c600-ac2b-11e8-9c0d-c249dc2252a7.png)

**Comment by marefr** [comment]
@flopp999 have not been able to reproduce this. Would suggest you to open a new issue and reference this issue. Please make sure you've cleared any static asset cache just in case.
