### ISSUE TITLE
Annotations do not cover selected range in 5.0 and 5.0-beta5

### ISSUE THREAD

**Issue by playqdrew** [grafana/grafana#11045]
Please include this information:

* What Grafana version are you using? 5.0 and 5.0-beta5 docker images
* What datasource are you using? InfluxDB
* What OS are you running grafana on? Ubuntu
* What did you do? Tried to add an annotation 
* What was the expected result? annotation added to the selected range
* What happened instead? annotation seems to extend to all time

You can see the issue here: https://youtu.be/IaEBLYjhlsA

**Comment by nmat** [comment]
been encountering this also. Not sure why it happens. Does not seem to matter time range or anything either.

**Comment by torkelo** [comment]
this is strange, unable to replicate this, what database are you using? (for grafana's internal db) , 

If you zoom out do you see any boundaries for the annotation? Can you check your grafana db, annotation table, find the latest annotation, what is the value of the epoch column?

**Comment by playqdrew** [comment]
@torkelo I believe we are using the internal sqlite3 DB. I wonder if this has to do with being an 'upgrade' from an older version? I'm not sure how to query that internal DB directly.

**Comment by nmat** [comment]
The system used to create it for me is influxdb for the metrics and standard annotations from grafana.

So if you zoom out...the annotation marker may dissapear.

If you zoom in then it covers the whole screen or a range that was not defined. Have also tested to pause the screen if auto refresh is set but still get the same problem after adding a annotation.

**Comment by daniellee** [comment]
Can not recreate this now so closing. If this is still a problem then we can re-open the issue.
