### ISSUE TITLE
[Feat] Include folder name in recently viewed dashboard list

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#11056]
Using Grafana 5.0 (actually a slightly earlier version) built from source
Using MetricTank as the data source.

We have hundreds of folders and over 1,000 dashboards.  Teams clone the dashboard and can save it without renaming it.  Therefore the dashboard may exist twice (just by name).

Please have in the auto-complete search for dashboards by name to prefix with the directory, e.g.

my_dir/scott_dashboard
your_dir/scott_dashboard

**Comment by torkelo** [comment]
they are grouped by folder, is that not enough?

**Comment by shalstea** [comment]
Sorry I should have experimented more.  Yes grouping is sufficient.  However I did notice that the most recent doesn't give the folder...  so that would be nice to address.

**Comment by marefr** [comment]
Thanks. I've updated the title of the issue to better reflect your feature request.

**Comment by marefr** [comment]
If or when we decide to implement this we should probably do this for starred dashboard list as well.
