### ISSUE TITLE
Graph panel: Null values always as 'connected' in less than approx. 22h timeframe

### ISSUE THREAD

**Issue by darkblaze69** [grafana/grafana#11052]
Grafana 5 beta4
Using zabbix as datasource, 30 sec update interval in datasource items.
Max data points set by default to 'auto'.

Null values always appear as 'connected' in graph in less than 21h-22h timeframe despite of "Stacking & Null" setting value. Larger timeframes appear to work as expected. As illustrated in GIF.

![Null values gif](https://user-images.githubusercontent.com/6976920/36843456-d5c59660-1d70-11e8-8afc-dd3aed0020fe.gif)

**Comment by torkelo** [comment]
This is likely an issue in zabbix not grafana. You can inspect the data your query returns in the metrics tab, Query inspector.
