### ISSUE TITLE
Cannot upload images directly to slack.

### ISSUE THREAD

**Issue by eMerzh** [grafana/grafana#11059]
Hi, i have Grafana 5.0.0 (but seems to be the case also with 4.6.3)
and trying to use slack.upload api, 
i previously used an external storage (webdav) but wanted to switch to upload api.

i've added my token to the dedicated input (yes it start with xoxb)

and my logs tell me that it was picked up by grafana, but i can't see the image

```
t=2018-03-02T08:15:45+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=2 newState=alerting prev state=ok
t=2018-03-02T08:15:45+0000 lvl=info msg=Rendering logger=png-renderer path="d-solo/000000013/brol?panelId=4"
t=2018-03-02T08:15:46+0000 lvl=info msg=uploaded logger=alerting.notifier url=http..../u3T2Ia4xw4cPSLayZBsd.png
t=2018-03-02T08:15:46+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=2 notification="Slack SY"
t=2018-03-02T08:15:47+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
```

i recieved the alert but did not had an image with it.
(it work if i remove my token and use the external storage)

**Comment by bergquist** [comment]
Is the `URL` field left empty?

**Comment by eMerzh** [comment]
Hi, 

Thanks for the help, it's configured like this  : 

<img width="630" alt="capture d ecran 2018-03-06 a 09 25 02" src="https://user-images.githubusercontent.com/177003/37021702-bd8a7350-2120-11e8-8444-d656c9bd543f.png">

i should remove the hook url ?

**Comment by bergquist** [comment]
Yeap. 

I'll make this issue about improving the docs/ui.

**Comment by eMerzh** [comment]
@bergquist .... the field is required

**Comment by eMerzh** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/177003/37021874-6093e8ce-2121-11e8-99ff-2b9aef5bac06.png">

**Comment by SharpEdgeMarshall** [comment]
+1 confirm same issue

**Comment by eMerzh** [comment]
it seems to be a visibilty issue.. 
if i send it to a public channel, all good!
and the doc says : 
> By default all newly-uploaded files are private and only visible to the owner. They become public once they are shared into a public channel (which can happen at upload time via the channels argument).

i'm looking for a way to make it "public" in a channel

**Comment by eMerzh** [comment]
oook so, in fact the bot must be part of the channel to be able to upload image there ... (which kinda make sense, but is not obvious)

so issue resolved for me but @bergquist  may still wana add that in the doc or smth :)

**Comment by bergquist** [comment]
@eMerzh Yea that should be mentioned in the docs :) Thank you for finding the issue and reporting it!

**Comment by SharpEdgeMarshall** [comment]
Sorry i'm still not understanding, actually i've invited the bot user in the channel but images are not sent
