### ISSUE TITLE
"Refreshed in every..." as an own dropdown

### ISSUE THREAD

**Issue by pkkummermo** [grafana/grafana#1105]
The header "5 minutes ago to a few seconds ago refreshed every 5s" gives information about the current timespan of the shown graphs. What we would like is an option to choose refresh rate as a separate dropdown from the interval chooser.

That would mean that the header "5 minutes ago to a few seconds ago refreshed every 5s" would have two click points and two dropdowns. The [5 minutes ago to a few seconds ago] and [refreshed every 5s]. 

What do you think?

**Comment by torkelo** [comment]
time picker improvements in 2.6
https://github.com/grafana/grafana/issues/2761
