### ISSUE TITLE
Non-admin user can't create organization

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#11060]
Not sure is it bug or feature but in the previous version any user could create organization if `allow_org_create` option was enabled in config. That was mentioned in docs till version 4.5:

> Note: If Grafana is configured with users.allow_org_create = true, any User of any Organization will be able to start their own Organization and become the administrator of that Organization.

In 5.0 non-admin user can't reach page `/org/new` from navigation and create new org, but this is still possible to do via API I think because backend code allows this:

```go
pkg/api/api.go
// create new org
apiRoute.Post("/orgs", quota("org"), bind(m.CreateOrgCommand{}), wrap(CreateOrg))
...

pkg/api/org.go
// POST /api/orgs
func CreateOrg(c *middleware.Context, cmd m.CreateOrgCommand) Response {
if !c.IsSignedIn || (!setting.AllowUserOrgCreate && !c.IsGrafanaAdmin) {
return ApiError(403, "Access denied", nil)
}
...
```

**Comment by torkelo** [comment]
yea, not sure if we should fix it by only allowing grafana admins to create new orgs or add a nav to this page :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
