### ISSUE TITLE
[CloudWatch]Dimension's positioning/order should be stored in the json dashboard

### ISSUE THREAD

**Issue by nomihtaa** [grafana/grafana#11062]
Grafana version  4.5 to 5.0 on Centos 7
Datasource :  CloudWatch

**Scenario :**
I don't really know how to classify this request, but i understand there is a bit of a hack with cloudwatch datasource to be able to query cloudwatch with multiple values when you have at least 2 dimensions :

* If you put a dimension parameter based on a template variable with multiple values on first position, then grafana will send multiple queries to get values for each element and everything works well.

* If you put that same multiple value dimension parameter in second position, grafana will send a unique 
 query with a multiple value list which doesn't seems to be supported yet by cloudwatch ([issue 7991](https://github.com/grafana/grafana/issues/7991))

Since dimensions are working differently according to the order you put it in, the dimensions's order should be kept when saving the dashboard but instead it is automaticaly sorted in alphabetical order when saved to json.

So, if for exemple you have 2 dimensions : ServiceName and Clustername and put Servicename as a multiple value parameter in first position, as soon as you reload the board it switch to second position because of alphabetical order and break the board.

**Comment by TestrucAAT** [comment]
NB : There is a workaround to keep dimensions in order :  
In template, declare a variable for each dimension with prefixes like "a_", "b_", ect...  in the name and with the name of the dimension as a value, then call theses variables instead of the "real" dimensions names in the query.
Not pretty but working !

**Comment by adic26** [comment]
> NB : There is a workaround to keep dimensions in order :
> In template, declare a variable for each dimension with prefixes like "a_", "b_", ect... in the name and with the name of the dimension as a value, then call theses variables instead of the "real" dimensions names in the query.
> Not pretty but working !

Can you guys give me an snapshot of how to do ☝️  , I seem to be confused at the point when you say `with the name of the dimension as a value` ? What value...its a query right?

**Comment by darkchilli** [comment]
> > NB : There is a workaround to keep dimensions in order :
> > In template, declare a variable for each dimension with prefixes like "a_", "b_", ect... in the name and with the name of the dimension as a value, then call theses variables instead of the "real" dimensions names in the query.
> > Not pretty but working !
> 
> Can you guys give me an snapshot of how to do ☝️ , I seem to be confused at the point when you say `with the name of the dimension as a value` ? What value...its a query right?

Say we want to change "Region, Rule" into order "Rule, Region"

Create variable as below:
------ Variable 1 -------
Name: 1_Rule
Label: 1_Rule
Hide: Variable 
Type -> Custom
Values seperated by comma: Rule
------ Variable 2 ------
Name: 2_Region
Label: 2_Region
Hide: Variable 
Type -> Custom
Values seperated by comma: Region
![tmp1](https://user-images.githubusercontent.com/8434715/52095512-47125d80-2617-11e9-87cb-cb0c6631135c.png)
![tmp2](https://user-images.githubusercontent.com/8434715/52095533-5ee9e180-2617-11e9-8181-f931f708032b.png)

------ Finished creating variables -------

In our dashboard -> panel -> Dimensions, configured it as below:
![tmp](https://user-images.githubusercontent.com/8434715/52095465-13373800-2617-11e9-82ca-4bf47d9a2480.png)

**Comment by adic26** [comment]
Thank you so much! Hopefully this will help others

**Comment by chipironcin** [comment]
This is affecting us too. Bump!

**Comment by sunker** [comment]
The way multi-valued template variables are being handled is totally rewritten in grafana 6.5 (already available in 6.5-beta1), so this workaround should not be necessary. Read more about this [here](#11062)
