### ISSUE TITLE
Export and import remove original dashboard

### ISSUE THREAD

**Issue by TheoGndr** [grafana/grafana#11064]
- What Grafana version are you using?
Grafana v5.0
- What datasource are you using?
InfluxDb
- What OS are you running grafana on?
Ubuntu 16.04.4 LTS
- What did you do?
When i export a dashboard and i import it, the original dashboard is removed while i change name and data worry.
- What was the expected result?
The original dashboard should stay.
- What happened instead?
The original dashboard is removed.

Thanks for your great job.

**Comment by marefr** [comment]
You need to remove the uid property in exported json before importing it if you want o import a complete new dashboard. 

We'll consider this when implementing #10796. Thanks for feedback
