### ISSUE TITLE
http: proxy error: context canceled

### ISSUE THREAD

**Issue by prsnnkrsh** [grafana/grafana#11069]
**- What Grafana version are you using?** 
Grafana - 4.5.2
**- What datasource are you using?**
Prometheus 1.7.2 connected via grafana backend proxy.
**- What OS are you running grafana on?**
Debian 9.3
**- What did you do?**
Required to view the "Container CPU Usage" Dashboard for a cluster for periods ranging between 5m to 6 hours
The query goes like this 
````sum by (container_name)(irate(container_cpu_usage_seconds_total{instance=~"$VMs",image!="",container_name!="POD"}[5m]))````
**- What was the expected result?**
Expected to see CPU stats for the containers in each node in the cluster
**- What happened instead?**
Received the graph render for first 2 nodes. The subsequent nodes got 502 Proxy error 

![screenshot_2018-03-02_17-00-17](https://user-images.githubusercontent.com/31932594/36926013-3300aae8-1e3b-11e8-9fc6-1c6ac0f203f4.png)

```
502 Proxy Error

Proxy Error
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request GET /api/datasources/proxy/1/api/v1/query_range.
Reason: Error reading from remote server

```
The logs from grafana show,
```
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10010 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10002 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10002 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled
t=2018-03-02T19:58:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/query_range status=502 remote_addr=10.233.68.1 time_ms=10009 size=0 referer="https://192.168.58.45/grafana/dashboard/db/container-cpu-usage?orgId=1"
2018/03/02 19:58:35 http: proxy error: context canceled

```
Initial analysis looks like if the TTFB is greater than 10s the graphs get the proxy error. 
![screenshot_2018-03-02_16-51-24](https://user-images.githubusercontent.com/31932594/36925824-57363532-1e3a-11e8-9b3c-e77e53a88f78.png)

 Running the Query inspector for the failed nodes, seem to work fine.

![screenshot_2018-03-02_17-04-35](https://user-images.githubusercontent.com/31932594/36926155-dfc29642-1e3b-11e8-95c8-f5bc17947a18.png)

I tried to search online with  keywords and they weren't helpful. Grafana community page doesn't seem to load right for me. 

Can you please point me in the right direction to solve this issue?

**Comment by bergquist** [comment]
do you see any errors in the Prometheus logs?

**Comment by prsnnkrsh** [comment]
Yes..all panels are using the same datasource. 
and we have not enabled TLS between Grafana and Prometheus. so it not likely to be the issue.

**Comment by prsnnkrsh** [comment]
Are there any rendering options (timeouts, thresholds etc) that can be optimized?

**Comment by bergquist** [comment]
I've seen similar reports where networking in containers causes the problem. One way of identifying that is to switch to direct mode for a while and see if it makes any difference.

**Comment by pgporada** [comment]
We're not using containers for any part of this monitoring stack.

**Comment by theonlydoo** [comment]
Same issue here on `5.4.0`, I use HAProxy to oauth2 proxy on some app, including grafana, all my apps are working, I can auth on grafana, but it breaks grafana's connectivity (`Server`, directly peered on prometheus hosted @http://localhost:9090)

**Comment by Jonathan34** [comment]
i believe i have the same problem in #15258

**Comment by theonlydoo** [comment]
Hey @here forgot to come back but I found a probable root cause for this.
In my case, I was behind haproxy and I tried to enable h2. Disabling it resolved my issue.

**Comment by Jonathan34** [comment]
i still get a timeout as described in https://github.com/grafana/grafana/issues/15258#issuecomment-460796753 with Grafana 6.0.0-beta1

**Comment by dongwangdw** [comment]
same issue from 5.2.
@theonlydoo what do you mean by enable h2? Is it a haproxy setting?

**Comment by theonlydoo** [comment]
yeah that was prior to haproxy 2.0, h2 wasn't possible end to end. I rolled back to 1.1. H2 was enabled only on the `frontend`. Haven't retried w/ end to end h2, I'd be glad to know if it runs smoothly now :-)

**Comment by davkal** [comment]
Havent seen this in a while. Please reopen if still an issue.
