### ISSUE TITLE
Changing templated value from dropdown is causing unsaved changes

### ISSUE THREAD

**Issue by cnicolov** [grafana/grafana#11063]
First of all I would like to thank you for your great work!

We are experiencing some strange behavior after upgrading to Version 5 and I am not sure if it's a bug, but:

### What Grafana version are you using?
5.0
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu Linux
### What did you do?
Go to a dashboard with a templated datasource/label_value() query and change the template value from the dropdown, then try to select some other dashboard.
### What was the expected result?
Not to prompt for unsaved changes when I try to change to different dashboard
### What happened instead?
Prompt for unsaved changes when I try to change to different dashboard

The dashboards were automatically migrated from Grafana 4, but the behaviour is the same on newly created dashboard also

**Comment by terjesannum** [comment]
I noticed the same and got rid of that prompt by unchecking editable in the dashboard settings

**Comment by torkelo** [comment]
thanks for reporting this, indeed a bug!

**Comment by roidelapluie** [comment]
Oh thanks! I have been hit by that but not reporting because I never found the cause.

**Comment by bergquist** [comment]
@cnicolov @roidelapluie 

When Grafana load an 4.0 dashboard it will perform the migration in the browser. Therefore change parts of the dashboard json and ask you if you want to save the changes. Might that been what you experienced? 

Are you able to reproduce this after saving the dashboard once?

**Comment by cnicolov** [comment]
@bergquist I'm able to reproduce after initial save

Also tried with newly created dashboard and the behaviour is the same

**Comment by bergquist** [comment]
This is due to the `dash.iteration` property. 

Looking into the code I don't understand why its updated. Perhaps it's not cloned properly?
@alexanderzobnin do you have any idea why this property is updated?

**Comment by torkelo** [comment]
That is updated on every repeat process to aid cleanup , should be ignored in unsaved changes diff (it was before in v4 but maybe changed name )

**Comment by bergquist** [comment]
Ok. PR on its way!
