### ISSUE TITLE
Block removing super admin permission from last super admin user

### ISSUE THREAD

**Issue by dhammond08** [grafana/grafana#11067]
- What Grafana version are you using? **Version 4.6.3 (commit: 7a06a47)**
- What datasource are you using?
- What OS are you running grafana on? **Centos 7**
- What did you do? **Accidentally removed grafana-admin from admin user** 
- What was the expected result? **not to be able to do that - essentially locking user out of making admin changes on grafana**
- What happened instead? **no users with admin permission!**
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by dhammond08** [comment]
Just to note, I was able to login to the sqlite3 database and update the admin user row to specify is_admin = 1 to resolve this.

**Comment by danielbh** [comment]
I can do this if you'd like. Below is what I propose...

- [There needs to be validation on the data layer](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/user.go#L479) much like it is done in the data layer for [removing admins from organizations](https://github.com/grafana/grafana/blob/9cc6c2128a8cca647e31a2d6e4d41603b9245995/pkg/services/sqlstore/org_users.go#L161)

-  [There needs to be validation on the api layer and give a 400](https://github.com/grafana/grafana/blob/master/pkg/api/admin_users.go#L101) like that is [done in remove user from organization api](https://github.com/grafana/grafana/blob/master/pkg/api/org_users.go#L123)

How does this sound? Thanks!

**Comment by danielbh** [comment]
Hmm It looks like I misunderstood the requirements. I was focused on the fact that you can delete the last admin user through the api as an admin. The validation and prevention of this might be opened as a separate issue. Thoughts?

Let me re-evaluate how the toggling is done on permissions to remove someone as an admin.

**Comment by danielbh** [comment]
Seems pretty straightforward still.

- [return 400 in AdminUpdateUserPermissions in api](https://github.com/grafana/grafana/blob/master/pkg/api/admin_users.go#L79)

- [do a check if last admin in UpdateUserPermissions in sqlstore](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/user.go#L500)

Will get those done over the weekend. Thanks.

**Comment by robpob10** [comment]
Hi,
This fix prevents the final admin user being deleted via the /admin/users/edit/ page, but it can still be deleted via the /admin/users page.

Would it be possible to extend the fix to cover that case as well?

**Comment by marefr** [comment]
The referenced PR is implemented in API so should work as expected. Please note that this is for last admin in organization and not last super admin in grafana instance.
