### ISSUE TITLE
Spark lines are showed below expected position in 5.0.0

### ISSUE THREAD

**Issue by onorua** [grafana/grafana#11074]
After migration from 4.6.0 to 5.0.0 I have noticed weird spark lines position. 
### 5.0.0 ###
<img width="195" alt="screen shot 2018-03-03 at 10 45 18 pm" src="https://user-images.githubusercontent.com/407040/36939145-f15c045c-1f34-11e8-9052-ed810583974d.png">

### 4.6.0 ###
<img width="325" alt="screen shot 2018-03-03 at 10 43 01 pm" src="https://user-images.githubusercontent.com/407040/36939147-f69d173a-1f34-11e8-87b2-723289d0df8b.png">

I've checked this on Safari as well as Chrome - the result is the same.

**Comment by onorua** [comment]
I've noticed this behavior for certain size of the objects. If the size is big enough, it shows correctly:
<img width="316" alt="screen shot 2018-03-04 at 11 04 24 pm" src="https://user-images.githubusercontent.com/407040/36950568-6afa3cae-2000-11e8-9f4b-91d1c107516e.png">

**Comment by torkelo** [comment]
The panel title is not allowed to wrap, need to fix that via css
