### ISSUE TITLE
Upgrade 2.6.0->4.6.3 with influxdb 0.8 plugin breaks dashboards

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#11070]
After upgrading from version 2.6.0 to 4.6.3 and installing the influxdb 0.8 plugin the dashboards are broken because the datasource is no longer recognized. It seems the influxdb 0.8 plugin is not compatible with the built-in influxdb 0.8 support of previous versions.
I've experienced this on a CentOS 7 systeme using the official RPMs.

**Comment by torkelo** [comment]
Have you installed the external plugin for 0.8? 

Please ask questions on the community site https://community.grafana.com
