### ISSUE TITLE
user with Editor role - Grafana 5

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11077]
Please include this information:
- What Grafana version are you using?
5.0.0
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
Linux Debian Stretch

If a user with Editor role cannot edit folder/dashboard permissions, why do a user with Editor role see Manage in the Dashboard menu?

I would see that a user with Editor role CAN edit folder/dashboard permissions because the user can create new dashboards so why not be able to edit who shall see the new dashboards?
I understand that a user with permissions to edit folder/dashboard permissions can see all users that is in the organisation but maybe that is not a bad thing, if that would be a bad thing don't give a user Editor role.
Right now  user with Editor role will create a dashboard then the user must contact a Admin so the new dashboard will be set to correct permissions.

**Comment by flopp999** [comment]
I played around a little now and I do see why a user that don't have permissions to edit folder/dashboard permission, can see Manage in Dashboard menu.
If a user with role Viewer get permissions to add Dashboards in a one or more folder this is the place where the user can add a new dashboard.
The user with role Viewer and permission to add dashboard will not see the "New dashboard" in the normal place(Home menu and to the right)

**Comment by daniellee** [comment]
The Manage page is most useful for a user with the admin role but maybe sometimes a viewer or editor will need to do some sort of management like bulk deleting or moving dashboards.

Also, an admin can assign the Admin permission for a specific folder or dashboard to an editor or viewer which is another reason the Manage page should be accessible to viewers and editors.

Thanks for taking the time to discuss this - I am closing this for now but if you have any more questions or doubts then I can reopen the issue.
