### ISSUE TITLE
Phantomjs abandoned

### ISSUE THREAD

**Issue by jan--f** [grafana/grafana#11078]
Hi,
with the recent [phantomjs announcement](https://github.com/ariya/phantomjs/issues/15344) it seems like the project is abandoned for now. While it seems there is [an effort to continue](https://github.com/ariya/phantomjs/issues/15345) the work, there is currently no up-to-date version of phantomjs.

I was never a fan of simply dropping in a binary blob and with phantomjs 2.1.1 it was still possible to build ones own version. Considering the age of this version and the dependence on openssl 1.0 I think a more recent version would be better (including and update to the openssl dependency), but I so far was not able to build 2.1.3 or 2.1.4.

I was wondering what the grafana team and community thinks.

**Comment by daniellee** [comment]
Thanks for posting this - we have had plans for a long time to migrate away from PhantomJS. We will be switching to headless chrome (see this [PR](https://github.com/grafana/grafana/pull/10751)) but there is still some work left to do before this gets released.

**Comment by torkelo** [comment]
we have a plugin that handles image rendering via headless chome:
https://github.com/grafana/grafana-image-renderer

**Comment by gueluelue** [comment]
@torkelo this sounds great, thanks for your work!

1. There are some issues with yarn conflicting with cmdtest, so no idea how to get it to run if I don't have yarn installed yet
2. Is there a plan to make it available on the plugins page? https://github.com/grafana/grafana-image-renderer/issues/8
