### ISSUE TITLE
Why modify class = “search-container” property of the left value does not take effect?

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#11088]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using? grafana-5.0
- What datasource are you using?   es
- What OS are you running grafana on? linux
- What did you do?  Dynamically modify the value of the class = ”search-container“ attribute
- What was the expected result? Dynamically modify the value of the class = ”search-container“ attribute
- What happened instead?   Modify the value of the class = “search-container” property's left value with the modified value as undefined
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
code:(public/app/core/components/search/search.ts)

export function searchDirective() {
  return {
    restrict: 'E',
    templateUrl: 'public/app/core/components/search/search.html',
    controller: SearchCtrl,
    bindToController: true,
    controllerAs: 'ctrl',
    scope: {},
	link: function(scope, elem){
	  var search = elem.find('.search-contain');
	  var leftTest = search.css("left","100px");
          var test = leftTest.css("left");
	  console.log(leftTest.css('left'));
	}
  };
}
**Why left value console.log undefined? Instead of 100px**

**Comment by daniellee** [comment]
Is this a bug report or a question about custom development?

If it is a question then please post a question on the community site instead and close this issue. Thanks.

**Comment by zhoumin8023** [comment]
this is custom development

**Comment by torkelo** [comment]
Please use community site for questions
