### ISSUE TITLE
Grafana 5.0 with machbase variable feature problem

### ISSUE THREAD

**Issue by merturl** [grafana/grafana#11083]
Grafana version 5.0
Machbase
windows10
i want use this
![image](https://user-images.githubusercontent.com/23473356/36960389-26b3ae9c-208a-11e8-8a96-87ba50de7a32.png)
and Grapth feature 'alert' but only return error msg like picture
![image](https://user-images.githubusercontent.com/23473356/36960789-e73f7c44-208b-11e8-987c-6d71b266179b.png)

Grafana 5.0 is not supported this in Machbase?

**Comment by bergquist** [comment]
Machbase is not a supported plugin so you have to contact the plugin author.
