### ISSUE TITLE
[Bug] Broken Snapshot data 

### ISSUE THREAD

**Issue by rnovikovP** [grafana/grafana#11082]
Please include this information:
- What Grafana version are you using?
 4.6.3
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Linux
- What did you do?
1) Open  Dashboard  https://pmmdemo.percona.com/graph/dashboard/db/prometheus?orgId=1
2) Expand all collapsed Rows 
3) make Snapshot

- What was the expected result?
Get all panels with data in the snapshot 

- What happened instead?
See: 
https://snapshot.raintank.io/dashboard/snapshot/jtQLBrFZfE4kfPbZ7MYEqhAmZEUr4xzG?orgId=2

Some graphs age not displaying data on snapshots. 
Looks like some timeout on getting  data because  from first "broken panel - all other are broken too"  

P.S. is this expected that in Spanshot I'll get  ONLY data from expanded rows?

**Comment by torkelo** [comment]
Yes, only expanded rows (visible data) is captured. You can increase timeout in the snapshot modal beforehand
