### ISSUE TITLE
Theme not applied to rendered PNG

### ISSUE THREAD

**Issue by martenjacobs** [grafana/grafana#11084]
- What Grafana version are you using?
Grafana v4.6.3
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 16.04.3 LTS
- What did you do?
Click on a graph, click "share", select a theme from the dropdown and click the "Direct link rendered image" button
- What was the expected result?
I expected to get a rendered PNG in the selected theme
- What happened instead?
I got a rendered PNG in the dashboard theme

**Comment by bergquist** [comment]
What do you mean by selected theme? 

I selected light theme at `/org` and it works as expected in 5.0.0
![image](https://user-images.githubusercontent.com/618863/37020916-e4cf3714-211d-11e8-8e04-122b89cf8eed.png)

**Comment by martenjacobs** [comment]
Just upgraded to v5.0.0 and the bug still exists there

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/13232
