### ISSUE TITLE
Failed send Alert notification with image to Telegram "Bad Request: MEDIA_CAPTION_TOO_LONG"

### ISSUE THREAD

**Issue by p5i** [grafana/grafana#11089]
Running Grafana 5.0.0 on Ubuntu 16.04.4 LTS with Graphite datasource.

Configured notification channel to Telegram.
- "Send Test" is working
- All notifications without image are working
- "OK" notifications with image are working
- "Alerting" notifocation with image doesn't work with following error messages in log file (debug level logging):
`t=2018-03-05T14:31:05+0300 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Disk usage alert" id=5
t=2018-03-05T14:31:05+0300 lvl=info msg="New state change" logger=alerting.resultHandler alertId=5 newState=alerting prev state=ok
t=2018-03-05T14:31:05+0300 lvl=info msg=Rendering logger=png-renderer path="d-solo/000000004/some-dashboard?panelId=15"
t=2018-03-05T14:31:07+0300 lvl=dbug msg="[phantom] Loading a web page: https://localhost:3000/d-solo/000000004/some-dashboard?panelId=15 status: success 30000" logger=png-renderer
t=2018-03-05T14:31:07+0300 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=4
t=2018-03-05T14:31:08+0300 lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/6n8PgVKw6Ev62yuJzrfL.png
t=2018-03-05T14:31:08+0300 lvl=info msg=uploaded logger=alerting.notifier url=
t=2018-03-05T14:31:08+0300 lvl=dbug msg="Sending notification" logger=alerting.notifier type=telegram id=1 isDefault=true
t=2018-03-05T14:31:08+0300 lvl=info msg="Sending telegram image notification" logger=alerting.notifier.telegram photo=/var/lib/grafana/png/6n8PgVKw6Ev62yuJzrfL.png chat_id=-111111111 bot_token=2222222222222222222222222222
t=2018-03-05T14:31:08+0300 lvl=dbug msg="Sending webhook" logger=notifications.webhook url=https://api.telegram.org/bot2222222222222222222222222222/sendPhoto http method=POST
t=2018-03-05T14:31:08+0300 lvl=dbug msg="Webhook failed" logger=notifications.webhook statuscode="400 Bad Request" body="{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: MEDIA_CAPTION_TOO_LONG\"}"
t=2018-03-05T14:31:08+0300 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook=somehook
t=2018-03-05T14:31:08+0300 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=189.967 alertId=5 name="Disk usage alert" firing=true`

- What was the expected result?
Alerting notification sent to Telegram chat
- What happened instead?
No alerting notification sent and "400 Bad Request: MEDIA_CAPTION_TOO_LONG" error in log file

It may depend on message size. In my case the message in Telegram is 422 character long when successfully sent without image.

**Comment by xlson** [comment]
Same as #11011
