### ISSUE TITLE
Phantom render.js is incorrectly retrieving number of active panels

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#11099]
https://github.com/grafana/grafana/blob/54c79c564870bf4b36ce630e93513f485e598ab8/vendor/phantomjs/render.js#L60 in grafana 5 should read:
`var panels = angular.element('plugin-component').length;` 
instead of 
`var panels = angular.element('div.panel:visible').length;`

The change is required as the `div.panel` class is applied not only on panels but also of rows for example, leading to overcounting the actual data panels. 
The consequence is that the check below (currentlyRenderedPanels >= panels) never evaluates to true.

**Comment by torkelo** [comment]
why? panel class is still used in v5. Can you provide more detail when it's wrong?

**Comment by amuraru** [comment]
The change is required as the `div.panel` class is applied not only on panels but also of rows for example, leading to overcounting the actual data panels. 
The consequence is that the check below (currentlyRenderedPanels >= panels) never evaluates to true.
