### ISSUE TITLE
Legend Values Out of View

### ISSUE THREAD

**Issue by mgresser** [grafana/grafana#11098]
- What Grafana version are you using?
Grafana 5.0
- What datasource are you using?
Influxdb 1.4.3
- What OS are you running grafana on?
CentOS 6
- What did you do?
Created a graph and added a legend with values.
- What was the expected result?
I expected a table with the legend keys and current values to be created at the bottom of the graph.
- What happened instead?
The table was created but it is positioned just out of view (the top of the letters can be seen).
- If related to metric query / data viz:
The values seem fine, this seems to be purely about how they are drawn.

Here's an example of a pie chart which should have a legend:
![screen shot 2018-03-05 at 4 29 29 pm](https://user-images.githubusercontent.com/3034779/37000923-db570e22-2092-11e8-9076-c8931206212f.png)

**Comment by mgresser** [comment]
It seems like this issue may be specific to the pie chart panel type.

**Comment by Ijin08** [comment]
Is the legend still not visibel after you refresh?

**Comment by torkelo** [comment]
Make sure you are using latest published version

**Comment by torkelo** [comment]
Of the pie chart panel

**Comment by imranhum1** [comment]
Same issue. I upgraded the grafana 4.x. to grafana 5.0 yesterday and I noticed the pie charts have the same issue.

**Comment by rsichel107** [comment]
Have this issue as well.
