### ISSUE TITLE
[Feature-Request] Humanized time formatting (".. time ago")

### ISSUE THREAD

**Issue by infernix** [grafana/grafana#11096]
Would be great to set timestamp formats to humanized form, e.g. "just now", "x minutes/hours/days ago" etc. For some data this gives a far more intuitive idea about data than a timestamp.

I'm creating this here as a reminder, will likely submit a PR for this in the near future.

**Comment by torkelo** [comment]
This already exists in the units under duration sub menu

**Comment by infernix** [comment]
Aha, so for reference, with tables, Time needs to be set to `Type: Number`. Perhaps this should also be exposed under `Type: Date`?

**Comment by gurpal2000** [comment]
This doesn't seem to work for tables using the latest versions of everything. I'm trying to display uptime in something other than just seconds. No options on the dropdowns work. Should I open another bug?
