### ISSUE TITLE
Profile menu "invisible" when gravatar is disabled

### ISSUE THREAD

**Issue by svenklemm** [grafana/grafana#11097]
The menu entry to access the profile menu in the left sidebar is almost invisible when you have gravatar disabled. This happens in light and dark theme.
 
Screenshot to demonstrate:
![image](https://user-images.githubusercontent.com/31455525/36998527-8526c922-20bd-11e8-8e00-a7a033aeec2e.png)

**Comment by blysik** [comment]
Seeing this also.
