### ISSUE TITLE
4th ALIAS BY is not shown in graph

### ISSUE THREAD

**Issue by Jeroen88** [grafana/grafana#11108]
If a create a graph with 4 data queries, each with an ALIAS BY only the first 3 are shown.

Please include this information:
- What Grafana version are you using?
Grafana v4.6.1 (commit: cac8b97) 
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu
- What did you do?
I created a graph with 4 data queries using 'ALIAS BY'
- What was the expected result?
All 4 aliases shown under the graph
- What happened instead?
Only 3 aliases show up
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Does all 4 queries return a series ? Please include queries and the response from influxdb, you can get the view the raw response from influxdb using the query inspector in metrics tab.

**Comment by Jeroen88** [comment]
@torkelo Thanks Torkel, I was about to close the issue, because indeed the fourth serie has no data.
