### ISSUE TITLE
Template menu - unable to scroll 

### ISSUE THREAD

**Issue by VR6Pete** [grafana/grafana#11104]
I’m running latest 5.x and have a large number of server names in a menu created via templates. 

However on iOS 11 (not validated on other devices) I am unable to scroll through the list of instances. Instead it just scrolls the whole page and not the individual server list. 

Please let me know if you require more information. 

Cheers

Pete

**Comment by u-nik** [comment]
Same problem here. Tested with Safari and latest Chrome on IOS 11 and just the same on Android 6 and Chrome.

**Comment by daniellee** [comment]
This is fixed now - could scroll through the whole list here on this test dashboard: https://play.grafana.org/d/T0ITd62Gk/prometheus-long-variable-list?orgId=1
