### ISSUE TITLE
Add keyboard shortcut `pd` for "duplicate panel"

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#11102]
In the new grid model in 5.0, I find that "duplicate panel" is the most predictable way of inserting new graphs into the dashboard.

Even in the older versions I used duplicate all the time, and now it is even more useful but even less accessible in that submenu.

Adding a `pd` shortcut would help a lot here.

Maybe even consider moving "Share" to the submenu and "Duplicate" to the top level?

![image](https://user-images.githubusercontent.com/345210/37006467-d08a08a0-20d8-11e8-911b-c760b82b3913.png)

**Comment by bergquist** [comment]
I think we should add the `dp` shortcut but I don't want o move `Duplicate` up to the top level. I think this is a feature for power user and can, therefore, be "limited" to shortcuts.

**Comment by towolf** [comment]
I'd be fine with just the shortcut, but I really think that anyone who is building dashboards needs "Duplicate" all the time. Who wants to redo every panel every time? Usually one wants to create a series of panels with slight variations in each, maybe changing a single variable.
