### ISSUE TITLE
Make resize handle visible in dark theme

### ISSUE THREAD

**Issue by cmcginty** [grafana/grafana#11103]
Please include this information:
- What Grafana version are you using? 5.0
- What did you do? Edit a chart panel to change width.
- What was the expected result? There is no option to change the width.
- What happened instead? Nothing.

The only workaround I found was directly editing the JSON object. It seems strange that this has not been implemented yet, so I'm guess there is some bug in the UI that is degrading my experience.

**Comment by torkelo** [comment]
you can resize any panel by dragging the bracket in the lower right corner. There is a bug in v5 stable where this resize handlebar is not visible enough.

**Comment by torkelo** [comment]
The css rule for the grid resize handle bar is no longer correct since we reverted to a fork for the grid component.
