### ISSUE TITLE
Share PNG for plugin panels (e.g. Pie Chart) not working

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#11106]
Please include this information:
- What Grafana version are you using? 
5.0
- What datasource are you using? 
Prometheus, but I don't think it matters for this issue.
- What OS are you running grafana on? 
Windows
- What did you do? 
Create a new dashboard panel using the Pie chart plugin. Try to share the panel via "Direct link rendered image"
- What was the expected result?
Click the link to get a PNG of the pie chart. This works for other graph panels in the same dashboard.
- What happened instead?
Timeout error displayed in browser. Server logs:
```
INFO[03-06|08:31:58] Rendering                                logger=png-renderer path="d-solo/SoT6hL6zk/test-dashboard?orgId=1&panelId=6&from=1520296317353&to=1520317917353&var-instance=dst_anonymous-169&width=1000&height=500&tz=UTC%2B02%3A00"
EROR[03-06|08:32:58] Timeout error. You can set timeout in seconds with &timeout url parameter logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
EROR[03-06|08:32:58] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/SoT6hL6zk/test-dashboard status=500 remote_addr=[::1] time_ms=60157 size=1763 referer="http://localhost:3000/d/SoT6hL6zk/test-dashboard?orgId=1"
EROR[03-06|08:32:58] failed to render an image                logger=png-renderer error="exit status 1"
```

I suspect this is not restricted to the Pie chart panel, but is a problem with all plugin panels. The [grafana-reporter](https://github.com/IzakMarais/reporter) uses the png endpoint when creating pdf reports. In addition to  the [pie chart plugin panels not renedering](https://github.com/IzakMarais/reporter/issues/17), users of the [Zabbix plugin panel have reported the same issue](https://github.com/IzakMarais/reporter/issues/29).

**Comment by torkelo** [comment]
Have you updated the pie chart panel to latest version?

**Comment by torkelo** [comment]
Can replicate this as well. Seems to be a bug in pie chart panel, works in singlestat and graph panel. 

created issue in pie chart panel plugin repo:
https://github.com/grafana/piechart-panel/issues/131
