### ISSUE TITLE
Detailed documentation about Annotation is needed

### ISSUE THREAD

**Issue by javenfang** [grafana/grafana#1111]
For a newbie, I cannot catch up with the current annotation doc:  http://grafana.org/docs/features/annotations/

Detailed usage docs are welcome.

**Comment by jaimegago** [comment]
In addition a screenshot showing the mouse rollover feature that displays the metadata associated with the event would be cool

**Comment by dnotivol** [comment]
I totally I agree, I would thank a lot a little example of annotations with graphite events. I'm kind of stuck with that, couldn't have it working by now...

**Comment by torkelo** [comment]
graphite events just works, put in a wildcard or any text int the tag filed. The tricky thing is creating graphite events as that feature is pretty badly documented. I hope do to another Grafana screencast for annotations, and update the docs.

**Comment by dnotivol** [comment]
Thanks torkelo, I was playing with it, but I don't see any event although I see them in graphite. As you say, I guess my problem is with graphite side... the django login and so on... quite a mess for me.

**Comment by mablae** [comment]
When using with elasticsearch it is not clear, what index/record format is needed. 
The field mapping needs documentation.

**Comment by mikeparker** [comment]
Similarly with prometheus annotations it's not clear how to convert a time-series query into a query that returns data that draws annotations. The default text seems to suggest it's designed for alerts but not all annotations will be based off alerts. For example, i'd like to add an annotation when the release number increases.

**Comment by cemo** [comment]
@mikeparker have you ever found a way for your usecase? I have a similar use case and desperately  looking for documentation for it.

**Comment by cemo** [comment]
@torkelo please make me correct that a regular prometheus must include a [timestamp] and a string value of `1`? Am I reading wrong?

[timestamp]: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L207-L217

**Comment by cemo** [comment]
For those who are interested in prometheus annotations. As I pointed at my previous comment, `1` is necessary. If you have a series in which only you want to calculated increase and create annotation from it, you need to use `increase` function and than you need to use `vector > bool 0` . Note that `bool` is mandatory. This will cause a 0 or 1 style vectors and it will be totally ok. I will send a PR regarding it.
