### ISSUE TITLE
Hide row options when not logged in

### ISSUE THREAD

**Issue by oiooj** [grafana/grafana#11112]
update from `grafana-4.3.2-1` to `grafana-5.0.0-1`  

Can anyone edit this without login? It's dangerous.

![image](https://user-images.githubusercontent.com/2253095/37022147-02fb46c6-215d-11e8-8e07-bdc06bb4f91d.png)

**Comment by torkelo** [comment]
Thanks for reporting this! 

it's not really dangerous as you cannot save any changes. But we will make sure settings/delete icons are hidden!

**Comment by oiooj** [comment]
@torkelo Thanks, I have already tried it. It's not really dangerous.
