### ISSUE TITLE
No data when selecting only one value in Multi-value Templating

### ISSUE THREAD

**Issue by 6d6178** [grafana/grafana#11110]
#### OS: CentOS 7.4.1708

I am trying to use templating with Multi-value enabled. Datasource for Templating and for the Graphs is the same Graphite Data Source.
When I enable the Multi-value Templating and select only one value, the Graph says "No data points".
When I select an additional value in the Templating I will get two Graphs drawn.
When I disable Multi-value Templating and select a value I will get a single Graph drawn. 

From this behaviour I assume that the formating of a single Multi-value selected is not conform. From the Query Inspector it looks like that even the single value is encapsulated by "{}". Graphite seems to not like that.

**Comment by torkelo** [comment]
Upgrading Graphite to latest stable should solve this.

**Comment by 6d6178** [comment]
Graphite is installed from the EPEL-Repository, therefore 0.9.16 is the latest version. I am installing Graphite 1.1.2 through pip right now to make it work and for the new features but would prefer to use a single Package Manager. Do you know by any chance when the EPEL-Repo will be updated? I think I remember from the GrafanaCon Videos that you are really invested in Graphite. (Thank You for that)
