### ISSUE TITLE
Unable to set `esVersion` using Provisioning

### ISSUE THREAD

**Issue by stefanes** [grafana/grafana#11126]
Adding a data source using the [new Provisioning mechanism](http://docs.grafana.org/administration/provisioning/#datasources) leaves the Elasticsearch version empty when setting to `5.6+`:

```
  jsonData:
     esVersion: 6
     timeField: "timestamp"
```

`http://<host>:8080/api/datasources/<id>`:
```
{"id":...,"orgId":...,"name":"...","type":"elasticsearch","typeLogoUrl":"","access":"proxy","url":"http://<host>:9200","password":"","user":"","database":"...","basicAuth":false,"basicAuthUser":"...","basicAuthPassword":"...","withCredentials":false,"isDefault":false,"jsonData":{"esVersion": 6,"timeField":"..."},"secureJsonFields":{},"version":1,"readOnly":false}
```

I have also tried setting `esVersion` to `"6"`, `"5.6+"`, `"56"`, `5.6+`, `5.6` - same behaviour. 

![image](https://user-images.githubusercontent.com/5484354/37037263-3a530826-2152-11e8-937c-f020f3899f41.png)

---

- What Grafana version are you using?
**5.0.0**
- What datasource are you using?
**Elasticsearch**
- What OS are you running grafana on?
**Windows Server 2012 R2**
- What did you do?
**[Add data source using provisioning](http://docs.grafana.org/administration/provisioning/#datasources)**
- What was the expected result?
**Elasticsearch version set to 5.6+ in UI**
- What happened instead?
**Elasticsearch version empty**

**Comment by stefanes** [comment]
Setting it to `5` works as expected:
```
  jsonData:
     esVersion: 5
     timeField: "timestamp"
```
![image](https://user-images.githubusercontent.com/5484354/37037232-2407c5d4-2152-11e8-8024-ab74e012a1f5.png)

**Comment by bergquist** [comment]
Hm.. these docs needs to be updated. 
Es versions are stored as numbers. So

 esVersion | number 
-------| ------
 2.x | 2 
 5.x |  5 
 5.6+ | 56 

I'll update the docs to mention this.

**Comment by stefanes** [comment]
Figured it out (sorry for the spam).

The only alternative I had not tried was of course the correct one, `56` w/out the quotes:
```
  jsonData:
     esVersion: 56
     timeField: "timestamp"
```
![image](https://user-images.githubusercontent.com/5484354/37037575-e0e860f0-2152-11e8-8de4-645d788b14e7.png)

Does this mean that the documentation is wrong?

| Name | Type | Datasource |Description |
| ----| ---- | ---- | --- |
| ... | ... | ... |  ... |
| esVersion | **string** | Elastic | Elasticsearch version |
| ... | ... | ... |  ... |

**Comment by bergquist** [comment]
the change will be published next time someone publishes the docs.

**Comment by Tower450** [comment]
the documentation is still missing... or i did not find it.

**Comment by marefr** [comment]
@Tower450 see `esVersion` in https://grafana.com/docs/administration/provisioning/#datasources

**Comment by Tower450** [comment]
@marefr  thanks :)

**Comment by Tower450** [comment]
pretty weird when i specify
```
jsonData: { ...
esVersion: 70,
...
```

The datasource is still at 5

**Comment by marefr** [comment]
@Tower450 From https://grafana.com/docs/administration/provisioning/

"Elasticsearch version as a number (2/5/56/60/70)"

So use `5` if your version is below 5.6 or `56` if your version is from 5.6 but less than 6.0.

**Comment by marefr** [comment]
You need to restart grafana for dashboard provisioning changes to update or use the api to reload https://grafana.com/docs/http_api/admin/#reload-provisioning-configurations

**Comment by Tower450** [comment]
@marefr  i actually reload grafana don't worry i am aware of this. I use ES 7.2 so 70 is the good value since the documentation says that it's a number type.

**Comment by Tower450** [comment]
all good thanks a lot for your help, the problem was on my side.

**Comment by dcvtruong** [comment]
I have a setting "esVersion: 70" but it always get set 5.x in grafana datasource.  I make sure to restart grafana (6.3.5).  Any ideas?

![Screen Shot 2019-12-20 at 3 06 24 PM](https://user-images.githubusercontent.com/45860078/71293346-b9c51e00-233a-11ea-88b8-76071f1f1681.png)

![Screen Shot 2019-12-20 at 3 06 40 PM](https://user-images.githubusercontent.com/45860078/71293371-c9446700-233a-11ea-8dde-1a788709c860.png)

**Comment by dcvtruong** [comment]
@Tower450 What was the problem you having? Thanks.

**Comment by andrew-pickin-epi** [comment]
jsonData: 
    esVersion: "70"
    interval: "Daily"

Both are ignored.

**Comment by marefr** [comment]
@andrew-pickin-epi this is yaml. Make sure it's correctly formatted. Looks like you'tr adding 70 incorrectly as a string "70". Please refer to the [documentation](https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#configure-the-data-source-with-provisioning).

**Comment by andrew-pickin-epi** [comment]
setting a string or integer both are ignored. As is the interval.

**Comment by AlKapkone** [comment]
Hello, I want to configure **7.10+** version using esVersion and down know how to do it)
**710** and **71** don't work for - it changes Datasource version to **5.x**.
Could anyone help with that ?)

**Comment by marefr** [comment]
@grafana/observability-squad can you please have a look at this. Seems to be a lot of confusion since you added support for semver. Thanks

**Comment by Elfo404** [comment]
starting from Grafana 8.0, `esVersion` should be a semver-valid string (ie. `"7.10.0"`).

```yaml
  - name: es-prov
    type: elasticsearch
    access: proxy
    database: "[metrics-]YYYY.MM.DD"
    url: http://localhost:12200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7.10.0
      timeInterval: "10s"
```

using this configuration correctly generates this:
![Screenshot 2021-11-09 at 15 39 04](https://user-images.githubusercontent.com/1170767/140955431-6e1e392d-849c-45d2-96e4-b32ff532249f.png)

we should probably better describe how to provision an ES datasource and what format is expected in https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#configure-the-data-source-with-provisioning, I'll create an issue and update docs.

I also just found that when using some string that is not in the default options (ie. `"7.8.0") the dropdown in datasource settings remains empty but everything works as expected.

**Comment by AlKapkone** [comment]
@Elfo404 Thanks a lot!
