### ISSUE TITLE
Using mongoDB as back-end repository

### ISSUE THREAD

**Issue by jeromegit** [grafana/grafana#1112]
I have using mongoDB as a repository of a large amount o measurement and I was wondering if you have considered using as a back-end repository the same way you have graphite, openTSBD and InfluxDB.
mongoDB has a very large audience of dedicated users and I bet that opening grafana to it would an instant success.

Thanks.

**Comment by archana5075** [comment]
Hi Jeromegit,
Are you still working on Grafana and MongoDB integration?

**Comment by jeromegit** [comment]
Hi Archana,
I looked into it but decided that Graphite was good enough for what I wanted.

**Comment by trblft** [comment]
Hi, I just discovered Grafana, I would like to get into the Datasource plugin development code. I saw in another post that you considered building a plugin API? Did I get it wrong?
I would like to know how grafana reaches its datasources? It looks like webservices. Is there a standard webservice query API for all TSDB systems? If so, would Grafana reach any webservice implementing this API? Where can I get info about Grafana dev?
Thanks and congratulations for this awesome piece of work.

**Comment by trblft** [comment]
Oh sorry, I forgot to mention I posted here because I would like to build a web service based on this:
https://github.com/Lothiraldan/MongoTSDB
 It is a kind of MongoDB TSDB python layer.

**Comment by jeromegit** [comment]
Hi trblft,
I'm a user of Grafana but not a developer of for the tool.
I suggest that you post your request to a broader audience.

Good luck!

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
INTP <http://www.mypersonality.info/personality-types/intp/>

**Comment by 4l3xp** [comment]
Hi, just checking if anyone is currently working on an API spec to implement unsupported datasources. I am feeling temped to cheat and just copy opentsdb's so that I can use Aerospike with the existing plugin without any modifications to the backend. Mercie.

**Comment by bergquist** [comment]
This will probably not go into Grafana core until a lot of people want it.

As now it's possible to add custom datasources to Grafana.
ex https://github.com/grafana/datasource-plugin-kairosdb

**Comment by uberduper** [comment]
Maybe not ideal as a tsdb, it would be useful to me for templating using metadata stored in mongo.

**Comment by jochenonline** [comment]
I just wanted to add to this discussion that there is a universial timestamp field of mongoDB which ist call `_id` if filled with an ObjectID which is the default. Getting the timestamp out if it is quite [simple](http://stackoverflow.com/questions/6452021/getting-timestamp-from-mongodb-id).

**Comment by bacheson** [comment]
Mongo is definitely a capable ts datastore. Server density pushes 350TB of ts data each month. Mongo is a must for Grafana.

**Comment by torkelo** [comment]
it has at least traditionally had HORRIBLE write performance due to database wide locks, maybe some of that has improved. But a Graphite, Prometheus or InfluxDB would probably perform many orders of magnitude better and have a lot better on disk compression/usage.

**Comment by bacheson** [comment]
The lock you speak of disappeared almost 4 years ago in 2.2. The performance of 3.x is lightyears ahead of 2.x.

I use InfluxDB and it's so far from being production ready. I think Paul and his team will get there but as it stands it's not ready for primetime.

The main advantage of running mongo is that I need a document store regardless. Using something like Graphite forces my team to administrate yet another system and become familiar with all it's gotchas.

**Comment by torkelo** [comment]
interesting, so you can easily write around 10K docs per sec? what is the storeage requirement for each document, in Graphtie it's 12 bytes, in InfluxDB and Prometheus its around 2 bytes :)  

Also mongodb has almost none of the metric query features that Graphite has which reduces the usefulness of the metrics to close to zero. But Data sources are plugins, anyone is welcomed to implement a mongo db data source :)

here is a example plugin:
https://github.com/grafana/simple-json-datasource

**Comment by bacheson** [comment]
Going into details about how this ts db is better or that is better is not the point. The point is that Mongo is extremely popular and Grafana is worse-off not having it as a core plugin. Just sayin :)

I'll take a look at your custom plugin option. Thanks for your time. I use Grafana everyday and am indebted to you sir.

**Comment by torkelo** [comment]
I am sure it would. But since it's not a TSDB it's not really suitable for it I feel. But since Grafana is pluggable I am sure some very basic support should be easy to do by anyone who wants get there hands dirty :) 

Then can then get the plugin listed on grafana.net 

Since we have this plugin site and grafana-cli tool to install plugins, it is not very likely that more data source will be added to the core "included" plugins.

**Comment by memelet** [comment]
Just curious, how does mongodb differ from elasticsearch in this regard?

**Comment by torkelo** [comment]
Elasticsearch is very different from MongoDB

**Comment by rafalkrupinski** [comment]
I'm also interested in this subject. @torkelo can you elaborate?

**Comment by blak3r2** [comment]
Where i see Mongodb fitting into the grand scheme of things is not so much for TS data.  But, what inevitably happens once you have a great dashboard tool you want to display data in say a table or single stat at the top of your dashboards... I would love it for that use case.

**Comment by josser** [comment]
Simple case: I have users in mongo, I want to show singlestat number of active users by simple count() of Users.find({status: 'active'})
I don't want historical information for this value, just current value, so I don't want to push this to influx or graphite.

**Comment by bergquist** [comment]
@josser @blak3r2  I suggest you use https://grafana.net/plugins/grafana-simple-json-datasource and write a small webb app that queries mongodb and returns it as timeseries to grafana.

**Comment by josser** [comment]
@bergquist Looks cool! Thank you!

**Comment by linar-jether** [comment]
You can also check out this snippet, it is a python backend for the simple-json-datasource with support for table queries, timeseries, template variables, annotations and html panels

https://gist.github.com/linar-jether/95ff412f9d19fdf5e51293eb0c09b850

**Comment by RashmiSaravanan16** [comment]
Have we got any work around to connect the mongodb to grafana ???

**Comment by pschichtel** [comment]
I'd be interested in getting time series data from a MongoDB. The data was not originally intended to be visualized, it's just stored by an application for restore and forensics functionality. So the data is already existing in a MongoDB, very detailed and consistently timestamped.
I'd prefer to use this existing data which contains everything I need, instead of duplicating it into a TSDB.

I might build a small data source plugin soon-ish if nobody else has done something already.

**Comment by bineesh13487** [comment]
@archana5075 Were you able to integrate Mongo with Grafana ?

**Comment by kurrasaradhi** [comment]
@pschichtel, did you manage to build a data source plugin for MongoDB-Grafana ?

**Comment by maracuja-juice** [comment]
There seems to be a plug-in for that now: https://github.com/JamesOsgood/mongodb-grafana
