### ISSUE TITLE
Invisble error on new Prometheus data source.

### ISSUE THREAD

**Issue by Nyhillius** [grafana/grafana#11122]
Hello,

I would try to add a new data source from my API exposing Prometheus data but I have an unexpected invisible error. I think it is not a normal behavior. My team is on Grafana V5.0.0.

Thanks.

![screenshot_1](https://user-images.githubusercontent.com/17960462/37031120-a7bc5baa-214e-11e8-84a0-4c308e9bc469.png)

**Comment by bergquist** [comment]
Could you please open your developer console and see if there is any error?

**Comment by Nyhillius** [comment]
Yeah of course. It is just a "ERR_CONNECTION_TIMED_OUT" error.

**Comment by bergquist** [comment]
This have been answered on our community site. https://community.grafana.com/t/prometheus-on-api-endpoint-and-grafana/5918

You need to set up a Prometheus server to store the metrics.

**Comment by Nyhillius** [comment]
I know it is me. But it is for reporting the invisible error. Thanks.

**Comment by bergquist** [comment]
Oh yea. Sorry :) We will look into giving a better message.
Its not possible to capture the timeout error message but we should have a better default error message.

**Comment by torkelo** [comment]
This looks like it's fixed 

![Screenshot from 2020-11-11 09-48-25](https://user-images.githubusercontent.com/10999/98789770-11f98880-2403-11eb-993d-1a3feead086f.png)
