### ISSUE TITLE
Case-insensitive sorting for template values

### ISSUE THREAD

**Issue by cross** [grafana/grafana#11128]
In grafana 4.1.1, there are options for sorting template values alphabetically or numerically, ascending or descending.  However, one of my sets of values for a template includes mostly capitalized words and a smaller number of all-lower-case words.  So that people can easily find the lower-case values, I'd like to sort in a case-insensitive manner.  Otherwise, my "a" strings are below the 40+ strings starting with capital letters.

Searching around for information suggests this has not been added in more recent versions, so I wanted to submit the request here.  It would be easy to add as an option.  Is there something that I've failed to configure in my installation that already supports it?

Thank you.

**Comment by bergquist** [comment]
Any chance you can transform the result to lower/upper case in your datasource?

**Comment by cross** [comment]
It's using graphite as a data source.  So, the actual source of the data that's being put into graphite could be changed, but I don't think I'm likely to convince someone of that.  (and that would still leave the older data in Graphite/carbon wrong)  These are strings that are displayed to humans, and therefore subject to concerns beyond data cleanliness.  :-)

**Comment by bergquist** [comment]
I guess this makes sense. But I'm afraid it won't be a high prio for a while.

**Comment by cross** [comment]
Okay.  I'll look at adding it myself, I have recently made a test server running grafana 5.x.

Question for you, adding new variable sort values.  It would make visual/conceptual sense to put these between "alphabetical" and "numeric" in the current list of sortOptions.  But, if that [numeric] value is stored, then it would mess with people when they upgraded.   Should I put the new pair of case-insensitive alphabetical options at the end, with new/higher numeric values?

**Comment by daniellee** [comment]
Closed by #11280
