### ISSUE TITLE
Duplicate alerts using 4.6.3

### ISSUE THREAD

**Issue by Jonnymcc** [grafana/grafana#11132]
- What Grafana version are you using?
4.6.3

- What datasource are you using?
Graphite and Prometheus

- What OS are you running grafana on?
Amazon Linux

- What did you do?
Configured alerts

- What was the expected result?
Alert fires once

- What happened instead?
Alert fires twice

Our deployment has Grafana running on one EC2 instance in the east region and one in the west. They are configured to use PostgreSQL 9.6.1  running in RDS as a common backend (which should allow deduping of alerts?). Not sure how to debug what is going on. The behavior is inconsistent but when it happens the same state is listed in the alert history twice within the same second. It also results in two duplicate notifications being sent.
 
I've tracked down the PR that should enable deduping of alerts https://github.com/grafana/grafana/pull/7632/files @bergquist

**Comment by Jonnymcc** [comment]
The de-duplication logic only prevents a notification from being sent twice? It would be nice for the executor to not store state changes twice.

**Comment by bergquist** [comment]
This have been fixed in 5.3
