### ISSUE TITLE
Empty playlists cannot be deleted

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11133]
Please include this information:
- What Grafana version are you using?
5.0
- What datasource are you using?
Influx
- What OS are you running grafana on?
Debian
- What did you do?
Trying to delete existing empty playlist
- What was the expected result?
See attachment
- What happened instead?
It still exist

I have upgraded from 4.6.3 -> 5.0

When I try to edit the playlist, it open a page to create a new playlist.

![playlist](https://user-images.githubusercontent.com/21694965/37077362-f6a503ca-21da-11e8-812f-a9d446ac76ac.png)

**Comment by glitchsys** [comment]
Same problem. I have a playlist that can't be deleted. If I click on "Edit" it brings me to a blank playlist, even the Name is blank.  Name should have been the name of the playlist I was trying to edit.  I tried creating a new playlist with the same exact name but it only resulted me in having 2 playlists with the same name, I can delete the new one but not the original one. How do we manually delete a playlist?

**Comment by glitchsys** [comment]
You can delete the playlists from the database.  I'm using postgresql and I was able to:

grafana=# delete from playlist;
DELETE 2
grafana=# alter sequence playlist_id_seq restart;
ALTER SEQUENCE
grafana=# delete from playlist_item;
DELETE 4
grafana=# alter sequence playlist_item_id_seq restart;
ALTER SEQUENCE

I'm sure with some database manipulation you could fix the missing playlist but for me I only had 3 playlists and they were easy enough to re-create so it was easier for me to just wipe the tables and re-build the playlists.
