### ISSUE TITLE
Don't alias package import unless needed.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11134]
We alias the `models` package as `m` all over the codebase. 
```go
import m "github.com/grafana/grafana/pkg/models"
```

Which is a legacy from when we started using GO and didn't have that much experience with it (4 years ago the go eco system didnt provide much guidance either). Aliasing import should be avoided unlesssss
* package name is very long
* repo name contains `-`

We decided a year ago that all new code we write should avoid aliasing `models` as `m` but I can see how this is confusing for external developers. So let's just fix it all over the codebase.

**Comment by bergquist** [comment]
Apparently.. everyone in the team didn't Agree with me :) So I'll turn this into a discussion instead!  

Ive done some local searching on my computer to find the files containing the most `m.` and found these files. 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/dashboard_folder_test.go
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/dashboard.go
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/org_test.go
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/user.go

I don't think any of those would suffer that much from using `models` instead of `m`. Some parts would be a little bit more verbose but that could be solved with helper functions etc.

**Comment by marefr** [comment]
We've added some code guidelines regarding this (#17890) and will work towards eventually removing all the models aliases so closing this.
