### ISSUE TITLE
Text Panel HTML mode - loads on every key press

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#11147]
Read before posting: 

Please include this information:
- What Grafana version are you using?
= Version 5
- What datasource are you using?
= N/A
- What OS are you running grafana on?
= Centos 7
- What did you do?
= Entered a Kibana iframe link into the text panel using HTML mode
- What was the expected result?
= Expected result is that the iframe should load upon clicking away from panel entry mode just like most data sources.
- What happened instead?
=  While entering the query in any data source query text box the query doesnt get sent on every character change, however with text panel the panel reloads on every character change which reloads the iframe every time and makes browser sluggish 
 
See gif below for more details:

![peek 2018-03-07 15-52](https://user-images.githubusercontent.com/12910496/37102925-ecc7d2f6-2220-11e8-93d1-6fd6a690dfe2.gif)

https://gfycat.com/WateryImperfectAsp

**Comment by boyskila** [comment]
Hi, if no one is currently working on this issue can I try to find some solution?

**Comment by torkelo** [comment]
This is fixed in v7.0
