### ISSUE TITLE
AWS Elastic-Search 1.5 is not working in grafana

### ISSUE THREAD

**Issue by kishorerv93** [grafana/grafana#11149]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
**GRAFANA 5.0**
- What datasource are you using?
AWS ES-filebeat ES-logstash ES-playbacks
- What OS are you running grafana on?
Linux 14.04
- What did you do?
Datasource is working i can able to scrap the metrics from grafana server and when i added the data source to grafana, it working but when i updated to 5.0 . still the data source is working but not able to see the metrics on dashboards
- What was the expected result?
- What happened instead?
**ERROR : unknown elastic error response.**

 
Inspector Response in grafana:

"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[REpgivgcQXT_u_xWoZQ][filebeat-2018.03.06][0]: RemoteTransportException[[Magilla][inet[/10.212.67.174:9300]][indices:data/read/search[phase/query]]]; nested: SearchParseException[[filebeat-2018.03.06][0]: from[-1],size[0]: Parse Failure [Failed to parse source [{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1520354626004\",\"lte\":\"1520441026004\",\"format\":\"epoch_millis\"}}}

**Comment by waqark3389** [comment]
@kishorerv93 I believe v5 does not support elasticsearch 1.5. You can use grafana 3.

**Comment by kishorerv93** [comment]
Yes, i figured it out . Thanks anyhow ! 👍

**Comment by bergquist** [comment]
Yeap. 1.x support has been deprecated.
