### ISSUE TITLE
Ldap group support does not work with groupOfUniqueNames

### ISSUE THREAD

**Issue by sbskas** [grafana/grafana#11151]
With grafana version 5.0, ldap.toml configuration describes a way to use ldap group matching using distinguishednames.
I quote: 
>\# Users with nested/recursive group membership and an LDAP server that supports LDAP_MATCHING_RULE_IN_CHAIN
>\# can set group_search_filter, group_search_filter_user_attribute, group_search_base_dns and member_of
>\# below in such a way that the user's recursive group membership is considered.
>\#
>\# Nested Groups + Active Directory (AD) Example:
>\#
>\#   AD groups store the Distinguished Names (DNs) of members, so your filter must
>\#   recursively search your groups for the authenticating user's DN. For example:
>\#
>\#     group_search_filter = "(member:1.2.840.113556.1.4.1941:=%s)"
>\#     group_search_filter_user_attribute = "distinguishedName"
>\#     group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]
>\#
>\#     [servers.attributes]
>\#     ...
>\#     member_of = "distinguishedName"'

Unfortunately, there is no such code to support that claim. member_of cannot be anything but the 4 hardcoded attributes (name, surname, username, email) .
Anything different get cleanup out by the function getLdapAttrN.

This has the following consequence to change the role of any user that doesn't match the LDAP group back to the catchall (in the example, viewer).
I issued a pull request https://github.com/grafana/grafana/pull/11150 to fix this and permit to specify a DN attribute to match against the dn of a node.

**Comment by zoltanbedi** [comment]
I think this issue is fixed then, isn't it? I'm going to close this and if you think this is still an issue we can reopen it.
