### ISSUE TITLE
[Updating dashboards between orgs Grafana v5.0.0]

### ISSUE THREAD

**Issue by pf23** [grafana/grafana#11156]
- What Grafana version are you using?
v5.0.0

- What datasource are you using?
influxDB

- What OS are you running grafana on?
CentOS7

- What did you do?
Called http api `POST /api/dashboards/db` to update the folder of one dashboard. 
The goal of the operation is to move one dashboard from one folder to another (these two folders belong to two different orgs). Thus, I only updated field `folderId` and kept the others untouched.

- What was the expected result?
Successfully updated.

- What happened instead?
message: "Failed to save dashboard"

In the source code, `/grafana/pkg/api/dashboard.go` line 263, I've found the exact error message but no specific reason is provided. 

Moving between folders of the same org is successful. Is it allowed to update dashboards between orgs, like moving a dashboard between folders of two orgs?

**Comment by daniellee** [comment]
Currently, this is not allowed. The idea being that orgs are supposed to be separate from each other and not be able to access each others dashboards, data sources etc.

In this case, you will have to export the dashboard and the import it into the other org (and then delete it from the 1st org).
