### ISSUE TITLE
Play All Saved Dashboards option for Playlist

### ISSUE THREAD

**Issue by Krylon360** [grafana/grafana#1116]
Would it be possible to add a Play All option in the playlists modal that; instead of having to go through every dashboard and save it as a favorite; it will play all dashboards currently saved in the grafana-db (ElasticSearch/InfluxDB)?

**Comment by mzupan** [comment]
+1 for playing all for a tag

**Comment by alberts** [comment]
It would also be very useful to be able to get a permalink to such a playlist.

**Comment by utkarshcmu** [comment]
@bergquist How about initializing the saved playlists list with an existing playlist of all saved dashboards instead of an empty list? With a title "Play All" or something? I can work on a PR if you agree.

**Comment by bergquist** [comment]
@utkarshcmu the item added to the playlist would have to be a wildcard. Otherwise new dashboards will not be added to a playlist. I guess a new playlist item type named something like `all` would be possible.

**Comment by utkarshcmu** [comment]
I think at this point the question is "do we really need this feature?". It has been almost a year. :)

**Comment by torkelo** [comment]
With the advent of persisted Playlista I would say no
