### ISSUE TITLE
Dashboard: Fixed template variables in top of windows as you scroll

### ISSUE THREAD

**Issue by ldktta** [grafana/grafana#11166]
- UI Feature request

When scroll down page to view extra graphs, fixed template variables in top of windows.

![image](https://user-images.githubusercontent.com/14881332/37159150-d3839edc-22cb-11e8-83d9-84a100659726.png)

**Comment by JamesGalt** [comment]
Would be nice to have the setting in the dashboard settings, so it becomes optional

**Comment by baiwfg2** [comment]
@bergquist  Hi. Is this issue being working on ? I also think it's very useful, especially when we have a long dashboard, and when we scroll down, the template variable panel is no longer seen, which is not desirable.

**Comment by rongearley** [comment]
Is this feature being worked on?  I'd really like to use it.

**Comment by daniellee** [comment]
@rongearley it won't be in the upcoming 6.4 release but will probably make it into a release this year.

We would like to test how well this works before deciding if having an option make sense. The general principle is that we try to minimize the number of dashboard options.

The next step for us to do some UX and UI testing to see how well this works for different types of dashboards. This is also a feature that would probably not work well on mobile or smaller screens so we need to research that too.

**Comment by cqcn1991** [comment]
> @rongearley it won't be in the upcoming 6.4 release but will probably make it into a release this year.
> 
> We would like to test how well this works before deciding if having an option make sense. The general principle is that we try to minimize the number of dashboard options.
> 
> The next step for us to do some UX and UI testing to see how well this works for different types of dashboards. This is also a feature that would probably not work well on mobile or smaller screens so we need to research that too.

Hi, is there any update?

**Comment by steven-haslam** [comment]
I would be grateful for any update on this feature request since have sticky template variables would greatly enhance the usability of a dashboard that involves scrolling to access all visible panels (especially if panels are viewed at different display resolutions and on tablets).  Thank you in advance.

**Comment by hassanfarid** [comment]
I have design suggestion for this request.

We can add a drop down in the header bar, along with date range, when the page has scrolled and dashboard variables are hidden.

The drop down icon / link can open up dashboard variables overlayed, when required.

This will ensure page realstate is secured and not being used by dashboard variables when not required.
@torkelo

**Comment by pankaj-dahiya** [comment]
This feature request opened more then 2 years ago still work in progress? Reason you have mentioned that this feature may not work with smaller screens seems not much legitimate to me. The drop down icon wiil be a nice approach too. Waiting for this to be included in grafana soon.

**Comment by apippin** [comment]
I too have been super annoyed by this. The simplest way I found to fix this issue was to write a Tampermonkey (browser extension/plugin) userscript in our browsers that runs on our grafana pages when loaded. The userscript that has worked well for us, so I thought I would share it here in case it helps others work around this until they implement this feature:

`// ==UserScript==
// @name         Grafana Sticky Variable Bar
// @namespace    https://<YOUR GRAFANA BASE URL GOES HERE>/
// @version      0.4
// @description  Makes the variable bar sticky in view and edit screens
// @author       Alan Pippin
// @match        https://<YOUR GRAFANA BASE URL GOES HERE>/*
// @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
// @grant        GM_addStyle
// @run-at       document-idle
// ==/UserScript==

function addCustomSearchResult (jNode) {
    // Find variables wrappers
    var viewVarwrap = document.getElementsByClassName('submenu-controls');
    var viewDashboardwrap = document.getElementsByClassName('dashboard-container');
    var editVarwrap = document.querySelector('div[class$="variablesWrapper"]');

    // Find the navbar to move the variables wrapper into
    var editNavbar = document.querySelector('div[aria-label="Panel editor content"');

    // If we found the edit screen Navbar and Varwrap, do this
    if(editVarwrap && editNavbar) {
        editNavbar.insertBefore(editVarwrap, editNavbar.firstChild)
    } else if(viewVarwrap && viewDashboardwrap) {
      // If we found the view screen Navbar and Varwrap, do this
      var bgColor = window.getComputedStyle(document.body, null).getPropertyValue('background-color');
      viewVarwrap[0].style.position = "fixed";
      viewVarwrap[0].style.zIndex = 2000;
      viewVarwrap[0].style.width = "90%";
      viewVarwrap[0].style.backgroundColor = bgColor;
      viewVarwrap[0].style.top = "52px";
      viewDashboardwrap[0].style.paddingTop = "90px";
    }
}

//setTimeout(addCustomSearchResult, 30000);
waitForKeyElements (".panel-header", addCustomSearchResult);
waitForKeyElements (".submenu-controls", addCustomSearchResult);
`

The panel edit screen is completely unusable when you have a lot of variables, as it puts a squeeze on what you can see in the panel. Viewing the dashboard is super annoying to use and hard to manage when you have a lot of variables and panels too when you have to scroll to the top of the page every time you need to make a change and scroll back down to see its affect on the panel you were at. The userscript above fixes these annoyances.

**Comment by ukkathva** [comment]
This will be a very useful feature to have.

**Comment by Daniel-Mompean** [comment]
any target ? since 2018

**Comment by src-dbgr** [comment]
This feature would be very nice to have.

**Comment by MarkVorkosigan** [comment]
That's what I name "open source" - 2,5 years waiting for simple and useful feature that people desire.

**Comment by birdayz** [comment]
no problem. you can implement it yourself or pay someone to do it for you

**Comment by tanzeelrana** [comment]
I think it should not be difficult to implement this ourselves. I might try to create a branch off of the release branch and if I am able to achieve this I can create a pull request.

**Comment by Mario-Hofstaetter** [comment]
This would be a GREAT addition for grafana to have 🎉 
It should be configureable in the dashboard settings, and also include Dashboard links and annotation toggles as sticky, not only the variables, as opposed to the screenshot of OP.

Since the first betas of Grafana 8 are popping up, I searched for this feature and unfortunately it's still open and not planned :-/
 @tanzeelrana any luck with a PR?

I just tried the tampermonkey script of @apippin and it looks to be a bit broken (in Grafana 7?).
Tried it on <https://grafana.wikimedia.org/d/000000377/host-overview> , the dashboard name was overlapping the variables.

**Comment by bolbat** [comment]
Would be great to have such feature

**Comment by thdesous** [comment]
@daniellee  Would be great to have such feature

**Comment by xiaobeiyang** [comment]
Implemented this feature in PR https://github.com/grafana/grafana/pull/41388, and hope Grafana team can merge it.

**Comment by hassanfarid** [comment]
thanks @xiaobeiyang .

**Comment by ukkathva** [comment]
Thank you

**Comment by adfilho1** [comment]
> I too have been super annoyed by this. The simplest way I found to fix this issue was to write a Tampermonkey (browser extension/plugin) userscript in our browsers that runs on our grafana pages when loaded. The userscript that has worked well for us, so I thought I would share it here in case it helps others work around this until they implement this feature:
> 
> ```js
> // ==UserScript==
> // @name         Grafana Sticky Variable Bar
> // @namespace    https://<YOUR GRAFANA BASE URL GOES HERE>/
> // @version      0.6
> // @description  Makes the variable bar sticky in view and edit screens
> // @author       Alan Pippin
> // @match        https://<YOUR GRAFANA BASE URL GOES HERE>/*
> // @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
> // @grant        GM_addStyle
> // @run-at       document-idle
> // ==/UserScript==
> 
> function addCustomSearchResult (jNode) {
>     // Find variables wrappers
>     var viewVarwrap = document.getElementsByClassName('submenu-controls');
>     var viewDashboardwrap = document.getElementsByClassName('dashboard-container');
>     var editVarwrap = document.querySelector('div[class$="variablesWrapper"]');
> 
>     // Find the navbar to move the variables wrapper into
>     var editNavbar = document.querySelector('div[aria-label="Panel editor content"');
> 
>     // If we found the edit screen Navbar and Varwrap, do this
>     if(editVarwrap && editNavbar) {
>         for (var i = 0; i < viewVarwrap.length; i++) {
>             viewVarwrap[i].remove()
>         }
>         editNavbar.insertBefore(editVarwrap, editNavbar.firstChild)
>     } else if(viewVarwrap && viewDashboardwrap) {
>       // If we found the view screen Navbar and Varwrap, do this
>       var bgColor = window.getComputedStyle(document.body, null).getPropertyValue('background-color');
>       viewVarwrap[0].style.position = "fixed";
>       viewVarwrap[0].style.zIndex = 100;
>       viewVarwrap[0].style.width = "90%";
>       viewVarwrap[0].style.backgroundColor = bgColor;
>       viewVarwrap[0].style.top = "52px";
>       viewDashboardwrap[0].style.paddingTop = viewVarwrap[0].clientHeight+"px";
>     }
> }
> 
> waitForKeyElements (".query-editor-row", addCustomSearchResult);
> waitForKeyElements (".submenu-controls", addCustomSearchResult);
> ```
> 
> The panel edit screen is completely unusable when you have a lot of variables, as it puts a squeeze on what you can see in the panel. Viewing the dashboard is super annoying to use and hard to manage when you have a lot of variables and panels too when you have to scroll to the top of the page every time you need to make a change and scroll back down to see its affect on the panel you were at. The userscript above fixes these annoyances.

damn helped me a lot, now we can wait for the official solution.

**Comment by Mario-Hofstaetter** [comment]
Sad to see this did not make it for Grafana 9, which is somewhat suprising. This is annoying users every day, when using dashboards causing lots of scrolling. 

On the other side exotic nice-to-have features like a UI query builder for PromQL and LogQL are being added. Well I guess user feedback and customer demand justify these decisions ¯\\_(ツ)_/¯ 
IMHO any intermediate user that is a bit familiar with promql / logql will prefer the code editor and be faster with it, but maybe I am wrong, or not the target audience, or both.

After all grafana is still OSS.. so we should be happy with what we get.

**Comment by alex-lx** [comment]
@Mario-Hofstaetter Meet the same problem, and I use another chrome extension: sylus with several css lines to fix it.

```css
.submenu-controls {
    position: fixed;
    top: 50px;
    z-index: 100
}

.dashboard-content {
    padding-top: 44px
}
```

**Comment by MarioAzulay** [comment]
It's 2022 guys...any news?

**Comment by seven-mile** [comment]
oh no😥

**Comment by cszhi** [comment]
Looking forward to this feature

**Comment by Dubrzr** [comment]
Can't wait to get this feature!

**Comment by bob454522** [comment]
I have read this full thread atleast 1x time, probably 2 or 3x times by now.  Has anyone from grafana given a reason why this feature has not been added?  (even if added as an optional user setting)?

to be clear-  Im not complaining as i LOVE GRAFANA, and am very grateful for it-  
but it seems weird as the dev team clearly does so MUCH dev work and SO QUICKLY,  yet have not addressed or commented on this pretty clear UI issue.    
(to see what im referring to just checkout the milestones to see how MUCH work and progress the grafana dev team makes on a daily/hourly basis,  
https://github.com/grafana/grafana/milestones
its really amazing).

tks
(LOVE GRAFANA!!)

**Comment by lucaswhornsby** [comment]
Hello @bergquist -- hope you're doing well! I'm new to this thread and wanted to check in on the status of this feature. 

Enabling the freezing of the filters at the top of the dashboard will create a much more efficient dashboard navigation experience for us, since we will have visibility of and access to the global filters that have been applied wherever we are on the dashboard, instead of having to keep scrolling up and down every time we want to view or change the filters. This is especially valuable for dashboards that have multiple panels and rows, which can become quite long. This is a table stakes feature that has long been normalized by the ability to freezing rows on Excel, so hopefully it will be enabled on Grafana soon. 

I'd really appreciate an update on this. Thanks!

**Comment by gbeyer3** [comment]
HELLO Grafana team -- Would you please give the community's  the COURTESY of an answer ?? 

Going on FIVE years for this basic UI fix.

**Comment by easy2stake** [comment]
Hello 2023!
Any news :) ?

**Comment by xiaobeiyang** [comment]
It seems that Grafana team bought tall enough screens, and do not need scroll down dashboards.

**Comment by andrewmcdonald-oxb** [comment]
I headed to the community forum to ask about just this feature, and saw the link to here. This would be a valuable addition to core Grafana as some of our dashboards do get long, and it's a pain scrolling back to the top just to change variable selection. I hope the Grafana team can respond here soon, it'd be nice to know where this is on the roadmap.

**Comment by Daniel-Mompean** [comment]
since 2018 guys, we are proliferating Grafana in the world, help us!!!

**Comment by Sparky-code** [comment]
Adding a +1 for "please implement this, it would be a solid quality of life add"
A big fan of Grafana and all that y'all do. Thanks!

**Comment by Smeany** [comment]
I tried my best guys. I've implemented a sticky toolbar that hides on scrolling, so that theres no need for an additional menu option.

**Comment by bobower** [comment]
Continuously following

**Comment by jbaris** [comment]
Any news on this?

**Comment by Daniel-Mompean** [comment]
since 2018 guys, we are proliferating Grafana in the world, help us!!!

**Comment by Sfonxs** [comment]
> I too have been super annoyed by this. The simplest way I found to fix this issue was to write a Tampermonkey (browser extension/plugin) userscript in our browsers that runs on our grafana pages when loaded. The userscript that has worked well for us, so I thought I would share it here in case it helps others work around this until they implement this feature:
> 
> ```js
> // ==UserScript==
> // @name         Grafana Sticky Variable Bar
> // @namespace    https://<YOUR GRAFANA BASE URL GOES HERE>/
> // @version      0.6
> // @description  Makes the variable bar sticky in view and edit screens
> // @author       Alan Pippin
> // @match        https://<YOUR GRAFANA BASE URL GOES HERE>/*
> // @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
> // @grant        GM_addStyle
> // @run-at       document-idle
> // ==/UserScript==
> 
> function addCustomSearchResult (jNode) {
>     // Find variables wrappers
>     var viewVarwrap = document.getElementsByClassName('submenu-controls');
>     var viewDashboardwrap = document.getElementsByClassName('dashboard-container');
>     var editVarwrap = document.querySelector('div[class$="variablesWrapper"]');
> 
>     // Find the navbar to move the variables wrapper into
>     var editNavbar = document.querySelector('div[aria-label="Panel editor content"');
> 
>     // If we found the edit screen Navbar and Varwrap, do this
>     if(editVarwrap && editNavbar) {
>         for (var i = 0; i < viewVarwrap.length; i++) {
>             viewVarwrap[i].remove()
>         }
>         editNavbar.insertBefore(editVarwrap, editNavbar.firstChild)
>     } else if(viewVarwrap && viewDashboardwrap) {
>       // If we found the view screen Navbar and Varwrap, do this
>       var bgColor = window.getComputedStyle(document.body, null).getPropertyValue('background-color');
>       viewVarwrap[0].style.position = "fixed";
>       viewVarwrap[0].style.zIndex = 100;
>       viewVarwrap[0].style.width = "90%";
>       viewVarwrap[0].style.backgroundColor = bgColor;
>       viewVarwrap[0].style.top = "52px";
>       viewDashboardwrap[0].style.paddingTop = viewVarwrap[0].clientHeight+"px";
>     }
> }
> 
> waitForKeyElements (".query-editor-row", addCustomSearchResult);
> waitForKeyElements (".submenu-controls", addCustomSearchResult);
> ```
> 
> The panel edit screen is completely unusable when you have a lot of variables, as it puts a squeeze on what you can see in the panel. Viewing the dashboard is super annoying to use and hard to manage when you have a lot of variables and panels too when you have to scroll to the top of the page every time you need to make a change and scroll back down to see its affect on the panel you were at. The userscript above fixes these annoyances.

An alternative which works on the latest grafana version is this:

```js
// ==UserScript==
// @name         Grafana Sticky Variable Bar
// @namespace     <insert here url>
// @version      0.6
// @description  Makes the variable bar sticky in view and edit screens
// @author       gem85247
// @match        <insert here url>/*
// @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
// @grant        GM_addStyle
// @run-at       document-idle
// ==/UserScript==

function GM_addStyle(css) {
  const style = document.getElementById("GM_addStyleBy8626") || (function() {
    const style = document.createElement('style');
    style.type = 'text/css';
    style.id = "GM_addStyleBy8626";
    document.head.appendChild(style);
    return style;
  })();
  const sheet = style.sheet;
  sheet.insertRule(css, (sheet.rules || sheet.cssRules || []).length);
}



GM_addStyle ( `
    section[aria-label="Dashboard submenu"] {
    position: fixed;
    top: 81px;
    left: 0;
    z-index: 999999;
    width: 100%;
    display: flex;
    padding: 8px 8px 0px 16px;
    -webkit-box-align: center;
    align-items: center;
    box-shadow: rgb(0, 0, 0) 0px 0.6px 1.5px, rgba(0, 0, 0, 0.4) 0px 2px 4px, rgba(0, 0, 0, 0.23) 0px 5px 10px;
    background: rgb(24, 27, 31);
    }
` );



GM_addStyle ( `
    div.scrollbar-view > div > div{
    margin-top: 40px;
    }
` );
```

**Comment by rfmoz** [comment]
+1

This functionality could be very helpful.

**Comment by Kariton** [comment]
> > I too have been super annoyed by this. The simplest way I found to fix this issue was to write a Tampermonkey (browser extension/plugin) userscript in our browsers that runs on our grafana pages when loaded. The userscript that has worked well for us, so I thought I would share it here in case it helps others work around this until they implement this feature:
> > ```js
> > // ==UserScript==
> > // @name         Grafana Sticky Variable Bar
> > // @namespace    https://<YOUR GRAFANA BASE URL GOES HERE>/
> > // @version      0.6
> > // @description  Makes the variable bar sticky in view and edit screens
> > // @author       Alan Pippin
> > // @match        https://<YOUR GRAFANA BASE URL GOES HERE>/*
> > // @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
> > // @grant        GM_addStyle
> > // @run-at       document-idle
> > // ==/UserScript==
> > 
> > function addCustomSearchResult (jNode) {
> >     // Find variables wrappers
> >     var viewVarwrap = document.getElementsByClassName('submenu-controls');
> >     var viewDashboardwrap = document.getElementsByClassName('dashboard-container');
> >     var editVarwrap = document.querySelector('div[class$="variablesWrapper"]');
> > 
> >     // Find the navbar to move the variables wrapper into
> >     var editNavbar = document.querySelector('div[aria-label="Panel editor content"');
> > 
> >     // If we found the edit screen Navbar and Varwrap, do this
> >     if(editVarwrap && editNavbar) {
> >         for (var i = 0; i < viewVarwrap.length; i++) {
> >             viewVarwrap[i].remove()
> >         }
> >         editNavbar.insertBefore(editVarwrap, editNavbar.firstChild)
> >     } else if(viewVarwrap && viewDashboardwrap) {
> >       // If we found the view screen Navbar and Varwrap, do this
> >       var bgColor = window.getComputedStyle(document.body, null).getPropertyValue('background-color');
> >       viewVarwrap[0].style.position = "fixed";
> >       viewVarwrap[0].style.zIndex = 100;
> >       viewVarwrap[0].style.width = "90%";
> >       viewVarwrap[0].style.backgroundColor = bgColor;
> >       viewVarwrap[0].style.top = "52px";
> >       viewDashboardwrap[0].style.paddingTop = viewVarwrap[0].clientHeight+"px";
> >     }
> > }
> > 
> > waitForKeyElements (".query-editor-row", addCustomSearchResult);
> > waitForKeyElements (".submenu-controls", addCustomSearchResult);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The panel edit screen is completely unusable when you have a lot of variables, as it puts a squeeze on what you can see in the panel. Viewing the dashboard is super annoying to use and hard to manage when you have a lot of variables and panels too when you have to scroll to the top of the page every time you need to make a change and scroll back down to see its affect on the panel you were at. The userscript above fixes these annoyances.
> 
> An alternative which works on the latest grafana version is this:
> 
> ```js
> // ==UserScript==
> // @name         Grafana Sticky Variable Bar
> // @namespace     <insert here url>
> // @version      0.6
> // @description  Makes the variable bar sticky in view and edit screens
> // @author       gem85247
> // @match        <insert here url>/*
> // @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
> // @grant        GM_addStyle
> // @run-at       document-idle
> // ==/UserScript==
> 
> function GM_addStyle(css) {
>   const style = document.getElementById("GM_addStyleBy8626") || (function() {
>     const style = document.createElement('style');
>     style.type = 'text/css';
>     style.id = "GM_addStyleBy8626";
>     document.head.appendChild(style);
>     return style;
>   })();
>   const sheet = style.sheet;
>   sheet.insertRule(css, (sheet.rules || sheet.cssRules || []).length);
> }
> 
> 
> 
> GM_addStyle ( `
>     section[aria-label="Dashboard submenu"] {
>     position: fixed;
>     top: 81px;
>     left: 0;
>     z-index: 999999;
>     width: 100%;
>     display: flex;
>     padding: 8px 8px 0px 16px;
>     -webkit-box-align: center;
>     align-items: center;
>     box-shadow: rgb(0, 0, 0) 0px 0.6px 1.5px, rgba(0, 0, 0, 0.4) 0px 2px 4px, rgba(0, 0, 0, 0.23) 0px 5px 10px;
>     background: rgb(24, 27, 31);
>     }
> ` );
> 
> 
> 
> GM_addStyle ( `
>     div.scrollbar-view > div > div{
>     margin-top: 40px;
>     }
> ` );
> ```

this prevents overlapping with "Add Visualisation" or the first "Row" of dashboards. And it does also work with the search bar toggle. even if you have multible rows of variables.
```js
// ==UserScript==
// @name         Grafana Sticky Variable Bar
// @namespace     <insert here url>
// @version      0.7
// @description  Makes the variable bar sticky in view and edit screens
// @author       gem85247
// @match        <insert here url>/*
// @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
// @grant        GM_addStyle
// @run-at       document-idle
// ==/UserScript==


function GM_addStyle(css) {
  const style = document.getElementById("GM_addStyleBy8626") || (function() {
    const style = document.createElement('style');
    style.type = 'text/css';
    style.id = "GM_addStyleBy8626";
    document.head.appendChild(style);
    return style;
  })();
  const sheet = style.sheet;
  sheet.insertRule(css, (sheet.rules || sheet.cssRules || []).length);
}


function adjustSubMenuPosition() {
  const submenu = document.querySelector('section[aria-label="Dashboard submenu"]');
  if (submenu) {
    const mainView = document.querySelector('.main-view');
    if (mainView && mainView.classList.contains('main-view--search-bar-hidden')) {
      // Adjust the position when the class changes
      submenu.style.top = '41px';
    } else {
      // Reset the position when the class reverts
      submenu.style.top = '81px';
    }
  }
}


GM_addStyle ( `
    section[aria-label="Dashboard submenu"] {
    position: fixed;
    left: 0;
    z-index: 100;
    width: 100%;
    display: flex;
    padding: 8px 8px 0px 16px;
    -webkit-box-align: flex-start;
    align-items: flex-start;
    box-shadow: rgb(0, 0, 0) 0px 0.6px 1.5px, rgba(0, 0, 0, 0.4) 0px 2px 4px, rgba(0, 0, 0, 0.23) 0px 5px 10px;
    background: rgb(24, 27, 31);
    }
` );


GM_addStyle ( `
    div.scrollbar-view > div > div{
    margin-top: 90px;
    }
` );


GM_addStyle(`
  div.react-grid-layout {
    margin-top: 8px;
  }
`);


GM_addStyle(`
  .css-1978mzo-canvas-content {
    padding: 0 16px 16px 16px;
  }
`);


const mainView = document.querySelector('.main-view');
if (mainView) {
  const observer = new MutationObserver(adjustSubMenuPosition);
  observer.observe(mainView, { attributes: true });
}


adjustSubMenuPosition();

```

**Comment by anthonyalayo** [comment]
Anyone on this thread know who we can @ for this request? I came here after being pained by this user experience over and over, but didn't expect a thread to exist since 2018. 

For bigger dashboards that have a decent amount of scroll, losing track of what variables you are selecting is a bummer.

**Comment by deanmax** [comment]
I just found this 5 years old issue after creating a new one https://github.com/grafana/grafana/issues/76745.

**Comment by evictorero** [comment]
Hi everyone, we have been working on this feature but it's not yet available. I can't provide an ETA but it's something we are aware of and working on. I will let you know in this thread as soon as it is ready.

**Comment by bgalvao** [comment]
+1 subscribed to this issue

**Comment by gbeyer3** [comment]
Five (5) YEARS (!) and 8 months . . .and counting. :-(

**Comment by 1OOsei** [comment]
Hi, any chance to push this feature. It's super annoying everyday and sounds like a basic feature from my perspective to make the UI more user friendly.
We could also think about moving the section on the left side for example in a separated independents panel which won't move when we scroll down.
please go go go. :-) I guess we have enough people interested into this to make like quickly.
thanks

**Comment by gbeyer3** [comment]
Since Grafanalabs is ignoring our requests here, I have cross-posted the issue to the Grafana Community Support forum at

[[SIX (6) Year Old Request for Grafana UI Bug Fix – When will it be addressed?](https://community.grafana.com/t/six-6-year-old-request-for-grafana-ui-bug-fix-when-will-it-be-addressed/109327)](https://community.grafana.com/t/six-6-year-old-request-for-grafana-ui-bug-fix-when-will-it-be-addressed/109327)

**Comment by yusufgungor** [comment]
+1

**Comment by ebabeshko** [comment]
It's already 2024, and we really need this feature

**Comment by dgrr** [comment]
bro, 6 years

**Comment by anthonyalayo** [comment]
@evictorero can we get an ETA? Is there a feature branch we can follow?

**Comment by evictorero** [comment]
Thanks for your feedback. This is something we all want and I can share we are working on it. The good news is we aim to make it available behind a feature toggle in Q2.

**Comment by shashi1iitk** [comment]
+1 for this issue.
Really frustrated to see this issue has been going on for almost 6 years.
It's a needed feature in Grafana

**Comment by amit-sawhney** [comment]
Just commenting for extra emphasis on how nice this would be, running into needing this now. Excited for this feature :)

**Comment by ChristopherWriight** [comment]
+1 - please make this happen!

**Comment by natellium** [comment]
Hey there, this was implemented as part of the migration to the new Scenes based architecture (#63433). We're planning to launch this in G11 behind a toggle and roll it out to everyone as we ensure the new architecture is stable. Bit of a sneak peak:

https://github.com/grafana/grafana/assets/74534993/8473cd70-ac64-4c8a-b59d-55963db42d7a

**Comment by ebabeshko** [comment]
Just wanted to mention that this long-awaited feature is already available in Grafana 11 behind **dashboardScene** feature toggle.

However I think that placement of time picker and refresh rate on the same line with variables and navigation buttons wasn't actually a good idea, I would prefer them to stay where they were earlier.

Because now my navigation buttons have been moved left by time picker and refresh rate, and that looks not very nice:
![Scenes](https://github.com/grafana/grafana/assets/63898296/de346bd0-f7b7-4931-b366-8ee398eaa042)

**Comment by dgrr** [comment]
> Just wanted to mention that this long-awaited feature is already available in Grafana 11 behind **dashboardScene** feature toggle.
> 
> However I think that placement of time picker and refresh rate on the same line with variables and navigation buttons wasn't actually a good idea, I would prefer them to stay where they were earlier.
> 
> Because now my navigation buttons have been moved left by time picker and refresh rate, and that looks not very nice: ![Scenes](https://private-user-images.githubusercontent.com/63898296/330930172-de346bd0-f7b7-4931-b366-8ee398eaa042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDEzNTgsIm5iZiI6MTcxNTgwMTA1OCwicGF0aCI6Ii82Mzg5ODI5Ni8zMzA5MzAxNzItZGUzNDZiZDAtZjdiNy00OTMxLWIzNjYtOGVlMzk4ZWFhMDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE5MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMzliZjIzZThjYTE3NDJmZjQ5YzkwNmU1Zjc0ODg3YjhmZTE0MTMwYWRiNDgzNTM3Y2EyZjc1MjY1OWU4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-NJHkNXVl8IYdoPYbxA3Ir_WIPABG9_0I9Paic9w0bQ)

I'd add the variable names to the bar 👀

**Comment by houtaru** [comment]
> Just wanted to mention that this long-awaited feature is already available in Grafana 11 behind **dashboardScene** feature toggle.
> 
> However I think that placement of time picker and refresh rate on the same line with variables and navigation buttons wasn't actually a good idea, I would prefer them to stay where they were earlier.
> 
> Because now my navigation buttons have been moved left by time picker and refresh rate, and that looks not very nice: ![Scenes](https://github.com/grafana/grafana/assets/63898296/de346bd0-f7b7-4931-b366-8ee398eaa042)

Hi, how do you enable this feature?
I try version 11.2.0 but not work

**Comment by larry-cdn77** [comment]
Could this be an option? The old behaviour (scrollable controls) means I could have a lot without using up a lot of screen space. On a tablet I am often prevented from viewing my dashboard altogether – panels shrink to nothing 🙂

![Image](https://github.com/user-attachments/assets/6f6d5e33-c817-4a42-8c5b-15d36c52b5e4)

**Comment by larry-cdn77** [comment]
Another example, exaggerated to the point of grotesque, and also a slightly different issue I suppose to do with space reserved for the time picker?

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/8d1ffe69-e380-49a6-b877-7eee7f3ade9c" />

**Comment by nmosafi** [comment]
@larry-cdn77 Is completely right. This has really caused a problem for our users of our dashboards. Yes we can add a query string to hide the variables, but being able to scroll down to hide them is a far better user experience. I strongly suggest having some option to choose whether variables are always shown, or scroll out of view like they used to.
