### ISSUE TITLE
Kiosk mode does not work reliably when embedding grafana in iframe

### ISSUE THREAD

**Issue by RalfJung** [grafana/grafana#11160]
To embed statistics into our website, we put Grafana into an iframe like so:
```
<iframe id="stats-frame" src="https://$HOSTNAME/grafana/d/overview/uebersicht?theme=light&kiosk" width="100%" height="960" frameborder="0"></iframe>
```
When opening that URL directly in the browser, it goes into kiosk mode as expected. However, for some reason, when putting into an iframe, the menu bar on the left and dashbaord selection in the top is shown anyway.

To make thing even worse, if I navigate to another page and then use the "back" button to go the page containing the iframe, everything looks as expected. If I then hit F5 to reload the page, the menu bar comes back. This is reproducible in both Firefox and Chromium.

Please include this information:
- What Grafana version are you using? 5.0
- What datasource are you using? Prometheus
- What OS are you running grafana on? Linux

**Comment by RalfJung** [comment]
To make things even better, if I open the "network" tab of the developer tools in Firefox and hit F5, the kiosk mode *does* work. Is this somehow timing-sensitive...?

**Comment by bergquist** [comment]
Being Iframed is not a goal for Grafana.
