### ISSUE TITLE
Alert List panel view permissions

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [grafana/grafana#11167]
Please include this information:
- What Grafana version are you using?
v5
- What datasource are you using?
MySQL
- What OS are you running grafana on?
Arch
- What did you do?
Opened dashboard with Alerts List panel 
- What was the expected result?
Panel should display alerts 
- What happened instead?
empty panel - `no alerts` text displayed
- If related to metric query / data viz:

User has view permissions but can't see alerts in Alerts list panel.

**Comment by Caffe1neAdd1ct** [comment]
Interestingly if i navigate to `/api/alerts?state=ok&state=no_data&state=alerting` while using the `View` user the api shows all the alert information in json.. so there must be some panel logic not showing the api response if the user doesn't have edit permissions...

**Comment by Caffe1neAdd1ct** [comment]
`pkg/services/sqlstore/alert.go`

lines 110-112:

```
        if query.User.OrgRole != m.ROLE_ADMIN {
		builder.writeDashboardPermissionFilter(query.User, m.PERMISSION_EDIT)
	}
```

Can we change this to `m.PERMISSION_VIEW`?

**Comment by Caffe1neAdd1ct** [comment]
Also on this note, clicking on slack alerts tries to edit the panel's alert rather than initially showing the alerting panel in a view mode.

`/d/000000006/alerts-dashboard?fullscreen=true&edit=true&tab=alert&panelId=34&orgId=1`

I would personally prefer to view the panel before editing the alert.

`/d/000000006/alerts-dashboard?fullscreen&panelId=34&orgId=1`

**Comment by bergquist** [comment]
Im not sure why we settled for `Editor`. do you remember @daniellee ?

**Comment by Caffe1neAdd1ct** [comment]
That's why I've not raised a pull request as I wondered why it was set that way and if anything else hung of that select query builder method.  I'm happy to attempt a pull however my go knowledge isn't great...

**Comment by VR6Pete** [comment]
+1 for being able to view the alert panel as a “viewer” user permission. Makes more sense in my opinion :)

**Comment by tiagoReichert** [comment]
Do we have some news regarding this topic? 
In my use case, I would also need that the Alert Panel is shown to users with "Viewer" permission.

**Comment by UzairM** [comment]
I also need to show alerts to users with viewer permission

**Comment by anthony-sticky** [comment]
Same here

**Comment by Caffe1neAdd1ct** [comment]
It doesn't look like a hard change, however a check as to why it was locked to Editors only would be best. If anyone can answer that question we would be in a good position to start a pull request :+1:

**Comment by taasjord** [comment]
In which version was this "broken" (although it seems intentional), so we can roll back to? It was working in 5.0.0-beta-1, but not in  5.0.4. Was it still working in -beta5?

**Comment by carlossmartini** [comment]
I'm seeing this issue in 7.2.1 right now.  The alert icon does not even show up for viewer role.  Is this something that was reverted after this thread?

**Comment by marefr** [comment]
@carlossmartini this issue is not about alert icon in side bar/side menu, it's about the alert list dashboard panel type.

**Comment by carlossmartini** [comment]
Not sure if we're using different terms to talk about the same thing, but doesn't the alert icon take you to the alert alert rules & notification page?  If so, shouldn't a viewer be able to view that page? I got to this issue via issue #10966 which I thought was the same issue that I'm seeing currently.

**Comment by marefr** [comment]
@carlossmartini #10966 is about the "alert alert rules & notification page" you refer to above.
