### ISSUE TITLE
Hide or Remove filter option from Table Panel.

### ISSUE THREAD

**Issue by realtabmj** [grafana/grafana#11170]
### What did you do?
I have added table panel in dashboard. I'm using "Raw Document" for "metric" under metrics tab and "JSON document" for "Table transformations" under options tab. Now I click on "Filter for Value" in one of the cell in table panel For example: Column Empid with value = 1234

### What was the expected result?
The whole dashboard should filter for the particular value Empid = 1234 

### What happened instead?
Whole dashboard become blank and shows nothing. But if I use variables and select Empid = 1234, dashboard filters and shows records for only 1234. So there are 2 issues/queries here:
1. I want to remove or hide the option of having filter value in table panel 
2. Understand the reason why the filtering does not work when used from Table Panel.

Please help on this. This is show stopper and critical for business and if not resolved they are planning to shut down plans of using Grafana :(

**Comment by jehutywong** [comment]
+1

**Comment by Zauxst** [comment]
+1

**Comment by ds3366714** [comment]
+1

**Comment by visago** [comment]
+1

**Comment by ibmdcb** [comment]
+1

**Comment by Sas002** [comment]
Is there any fix for this issue. I can see same error when we filter with Namespace and Node status get N/A and does not show any data for Nodes. Which seems Grafana not able to reach Nodes.

**Comment by iordachelm** [comment]
+1

**Comment by torkelo** [comment]
think this is a limitation in your elasticsearch mappings, the "Filter for value" will work but needs to be filterable by elasticsearch
