### ISSUE TITLE
How to import dashboard history 

### ISSUE THREAD

**Issue by jl98800** [grafana/grafana#11179]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by jl98800** [comment]
Maybe there is an Influx solution to importing dashboard history (data points).  We keep data for 21 days so that's as much as we'd like to migrate.

**Comment by marefr** [comment]
Are you talking about version history for a dashboard?

**Comment by jl98800** [comment]
Not version history - I saw that - but our dev team that created the dashboard also wanted all the data points to follow the dashboard.  Is there some influx tool or trick to do that?

**Comment by marefr** [comment]
Closing this as it seems more like a question of how to migrate data with influxdb. Questions should be posted on our [community site](https://community.grafana.com).
