### ISSUE TITLE
Error when creating dashboard through API

### ISSUE THREAD

**Issue by admd** [grafana/grafana#11176]
Please include this information:
### What Grafana version are you using?
Grafana v5.0.0
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
OpenSUSE Tumbleweed
### What did you do?
Tried to create a dashboard through HTTP API with the standard example given on this page.``
POST /api/dashboards/db HTTP/1.1
Accept: application/json
Content-Type: application/json
```
{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "rows": [
      {
      }
    ],
    "schemaVersion": 6,
    "version": 0
  },
  "folderId": 0,
  "overwrite": false
}
```
Dashboard is created with the response similar to mentioned on the same page. But when i go and visit grafana UI, I get terror mentioned below.
### What was the expected result?
A new Dashboard in grafana
### What happened instead?
TypeError: Cannot read property 'length' of undefined
true
Dashboard init failed
### If related to metric query / data viz:
No

**Comment by marefr** [comment]
I see that the documentation is a bit outdated. Will update that. But I just created a dashboard through the Grafana UI and the following payload was sent in the request:

```json
{
  "dashboard": {
    "annotations": {
      "list": [
        {
          "builtIn": 1,
          "datasource": "-- Grafana --",
          "enable": true,
          "hide": true,
          "iconColor": "rgba(0, 211, 255, 1)",
          "name": "Annotations & Alerts",
          "type": "dashboard"
        }
      ]
    },
    "editable": true,
    "gnetId": null,
    "graphTooltip": 0,
    "id": null,
    "links": [],
    "panels": [],
    "schemaVersion": 16,
    "style": "dark",
    "tags": [],
    "templating": { "list": [] },
    "time": { "from": "now-6h", "to": "now" },
    "timepicker": {
      "refresh_intervals": ["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"],
      "time_options": ["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"]
    },
    "timezone": "",
    "title": "New dashboard Copy",
    "uid": "",
    "version": 0,
    "hideControls": false
  },
  "overwrite": false,
  "message": ""
}
```

Please try this out for now

**Comment by marefr** [comment]
Just verified that your request works fine if you remove the rows property.

**Comment by admd** [comment]
Thank you @marefr for the quick response and for the amazing product. :+1:
