### ISSUE TITLE
graphite datasource: noNullPoints support

### ISSUE THREAD

**Issue by scrwr** [grafana/grafana#11171]
In order to keep traffic and response data structures low, graphite has a noNullPoints option. Grafana should offer an option to support it.

- What Grafana version are you using?
docker://grafana/grafana:latest

- What datasource are you using?
graphite

- If related to metric query / data viz:
Regular with Null Points
```
curl 'https://grafana/api/datasources/proxy/1/render' 
-H 'Cookie: grafana_user=...; grafana_sess=...' 
--data 'target=...&from=-5min&until=-1min&format=json&maxDataPoints=1'

[{"target": "e1", "datapoints": [[null, 1520508480]]}, {"target": "e2", "datapoints": [[null, 1520508480]]}, {"target": "e3", "datapoints": [[null, 1520508480]]},...
```

Without null points (expected):
```
curl 'https://grafana/api/datasources/proxy/1/render' 
-H 'Cookie: grafana_user=...; grafana_sess=...' 
--data 'target=...&from=-5min&until=-1min&format=json&noNullPoints=True' 

[{"target": "e456", "datapoints": [[1.0, 1520508720]]}, {"target": "e765", "datapoints": [[1.0, 1520508600]]}, {"target": "e987", "datapoints": [[1.0, 1520508600]]}, {"target": "e1082", "datapoints": [[1.0, 1520508660]]}]
```

**Comment by bergquist** [comment]
Not sure we want to introduce an option for this. Or where such option should exist. Seems like an edge case few people would use.

Reducing response size is always nice but if your response is large and contains a lot of null values I think there is something wrong with the data or the response is very hard to visualize anyway.

**Comment by scrwr** [comment]
Its event stream like data (from many targets in our case). In order to visualize event totals over all these targets with the option to highlight the origin target (so grouping is not an option), you would like to only gather their event datapoints and skip all datapoints, where no data happend. I know, it might be an edge case, but for me, this is an option of the DB very similar to maxDataPoints, so if they think, there is a valid reason for having it, I think we are probably not too much of strangers. ;)

**Comment by izavyalov** [comment]
> Reducing response size is always nice but if your response is large and contains a lot of null values I think there is something wrong with the data or the response is very hard to visualize anyway.

It depends on visualization chosen. 

>  Or where such option should exist. Seems like an edge case few people would use.

There is a **Options** section that allows to set _maxDataPoints_ and next to it one could have _noNullPoints_.

**Comment by metametadata** [comment]
+1. This would make it easier to debug series with many nulls.
