### ISSUE TITLE
Derivative does not work with metric: Count (ES datasource)

### ISSUE THREAD

**Issue by CountDracula** [grafana/grafana#11175]
- What Grafana version are you using?
**4.6.3**
- What datasource are you using?
**Elasticsearch (5.6.1)**
- What OS are you running grafana on?
**Ubuntu 16.04.3 LTS**
- What did you do?
**Trying to construct a line graph with derivative on Count (document count) as the metric**
- What was the expected result?
**A graph containing a line with the derivative values**
- What happened instead?
**No data points are returned because the ES request fails with error: "type":"illegal_argument_exception","reason":"No aggregation found for path [1]**

Here's the request sent by Grafana to ES:
 ```
{ "search_type": "query_then_fetch",
	"ignore_unavailable": true,
	"index": "my-test-index-*"
}
{
	"size": 0,
	"query": {
		"bool": {
			"filter": [{
				"range": {
					"@timestamp": {
						"gte": "1519918298933",
						"lte": "1520523098933",
						"format": "epoch_millis"
					}
				}
			},
			{
				"query_string": {
					"analyze_wildcard": true,
					"query": "*"
				}
			}]
		}
	},
	"aggs": {
		"2": {
			"date_histogram": {
				"interval": "1d",
				"field": "@timestamp",
				"min_doc_count": 0,
				"extended_bounds": {
					"min": "1519918298933",
					"max": "1520523098933"
				},
				"format": "epoch_millis"
			},
			"aggs": {
				"3": {
					"derivative": {
						"buckets_path": "1",
						"unit": "1d"
					}
				}
			}
		}
	}
}
```
So basically a wrong value is passed to the buckets_path if using Count (document count) as the metric. 

Instead of:
``` 
"buckets_path": "1"
``` 
it should be set to

```
"buckets_path:": "_count"
```

This can easily be confirmed by changing the value manually and sending the query to ES, e.g. via Kibana console. This results in e.g. the following response:
```
....
"aggregations": {
    "2": {
      "buckets": [
        {
          "key_as_string": "2018-03-02T00:00:00.000+01:00",
          "key": 1519945200000,
          "doc_count": 5005694
        },
        {
          "3": {
            "value": -2689011
          },
          "key_as_string": "2018-03-03T00:00:00.000+01:00",
          "key": 1520031600000,
          "doc_count": 2316683
        }
.....
```

Judging by the issue [https://github.com/grafana/grafana/issues/8843](https://github.com/grafana/grafana/issues/8843) this problem also happens with Moving Averages. The above fix should also resolve said issue.

Furthermore, there seems to be an UI bug as well:

![image](https://user-images.githubusercontent.com/7106312/37202260-4c113f76-238a-11e8-9b54-b7418a321151.png)

As can be seen from the picture, for some reason the Metric Derivative row has 'Count select field'  as the field name instead of just plain 'Count'.

**Comment by huangwd15** [comment]
same error

**Comment by willemdh** [comment]
Same problem with Elasticsearch 6.4.2 and Grafana 5.1.4-1

**Comment by marefr** [comment]
@willemdh derivative for count is not supported in Grafana at the moment, doesn't matter what version of elasticsearch you're using. That's why this issue is labeled as feature request

**Comment by willemdh** [comment]
@marefr Hey my issue is that when I select derivative on metric `system.network.in.bytes` I get no result at all. Other aggregations work fine. If this issue was made especially for derivative on count, I might have anohter issue indeed.

**Comment by marefr** [comment]
@willemdh Please use query inspector to troubleshoot. Use the query there and manually submit it to your elasticsearch instance and compare to query inspector response. If you think there's a bug, please open a new issue. Thanks
