### ISSUE TITLE
[Bug] A folder admin cannot add user/team permissions for folder/its dashboards

### ISSUE THREAD

**Issue by pf23** [grafana/grafana#11173]
- What Grafana version are you using?
v5.0.0

- What datasource are you using?
Nothing to do with datasource.

- What OS are you running grafana on?
CentOS7

- What did you do?
First, grant an editor  `admin` permission on a folder. 
When this editor tries to manage the folder, like granting permissions to certain team or user, he cannot retrieve the list of all folders / users. 
**modified------**
When this editor tries to manage the folder, like granting permissions to certain team or user, he cannot retrieve the list of all teams / users. 

- What was the expected result?
Folder admins can always access all the folders and users, whatever org role it is.
**modified------**
Folder admins can always see the list of **all teams and users**, whatever org role it is.

- What happened instead?
Folder admins of org role `editor` or `viewer` have very limited permission on handling folder permissions, because he cannot get the list of org folders and org users.
**modified------**
Folder admins of org role `editor` or `viewer` have very limited permission on handling folder permissions, because he cannot get **the list of org teams and org users**. 

By the way,  I believe currently the permission management on folders and dashboards is kind of confusing. Always granting the creator of the folder/dashboard  `admin` role (along with the right to list folders and users when managing permissions) no matter what org role the user is, thus he can manage them all by himself, not to bothering an admin, will it be better?

**Comment by ermazi** [comment]
the same problem.

**Comment by kpocius** [comment]
We create a team, then create a folder, and grant admin permissions for that team to manage their own folder. The issue is as described above - while every member in the team has admin permission for the folder, they can't add additional users to the folder because they have no permission to see team/user list. For now, the only workaround seems to make someone in the team an admin for the organization, but that creates a security problem because now particular team members can go and mess with everyone's folders, dashboards, etc.

**Comment by torkelo** [comment]
Think the issue description is wrong.

> Folder admins can always access all the folders and users, whatever org role it is.

This makes no sense, (the folder part). If you admin for one folder does not make you able to view all other folders. You should only be able to access other folders & dashboards that you have access to (by org role, team or user permissions). 

This issue should rather only be about the user & team apis. If they should be accessible from users with viewer or editor role

**Comment by daniacs** [comment]
Same issue here. Steps:
1. Create a folder (F) containing a dashboard (D)
2. Create a team with 2 members (Ma, Mb)
3. On "Manage folder dashboards & permissions", choose tab "Folder Permissions" and include Ma as Admin role.
4. Logoff admin. Logon Ma. 
5. As Ma, choose Dashboards -> Manage -> Folder (F) -> Tab "Permissions"

A red "DIV" appears with "Access Forbidden".
It returns 403 for URL /api/teams/search?perpage=10&page=1

**Comment by marefr** [comment]
After reading @daniacs comment I finally understand the issue. Confirmed as bug. 

I think some confusion here because @pf23 wrote 
> ... he cannot retrieve the list of all folders / users.
> ... all the folders and users, whatever org role it is.
> ... get the list of org folders and org users.

And I imagine he meant to write teams and users instead. @pf23 can you update your issue description?

**Comment by pf23** [comment]
There are actually two problems, or ideas.  Let me make it clear. (There are confusions in my initial post, I've modified them.)

1. Suppose you are an `admin` of a folder, with limited org role like  `editor` or `viewer`. When you try to modify the permission, you cannot get the list of teams and users in this org. Then how could you add them into permission list?

I think perhaps everyone should have the right to know all the team names and user names, which is the prerequisite for him to modify permissions.

2. Creator of dashboard or folder doesn't have `admin` permission to the dashboard or folder by nature, unless he is org admin. Why not grant creator admin role to what he created?

**Comment by marefr** [comment]
@pf23 1) is address by #11526. 

2) As an administrator of a Grafana install or a folder you should be able to restrict/change existing admin (that created folders/dashboards) in one place and not manually edit permissions for each folder/dashboard. Could you please elaborate why this is needed?

**Comment by pf23** [comment]
@marefr 
1) Thx!
2) Suppose there is a org `Editor`. He creates a folder/dashboard, wanner add some teams/users to manage the folder/dashboard. At this time, there are 3 alternatives, he  
* is allowed to do so by himself, by granting him `admin` role to what he created, and keeping his org role unchanged, 
* asks an org `Admin` for permission (not preferred I suppose)
* isn't allowed to have this kind of right, which means he can create but not able to manage permissions on what he created.

Below are some ideas and how I solved the problem in my situation.

In my situation, there are 
1. various project teams, hoping to create and manage folders/dashboards by themselves. You know some projects need to keep privacy of their data even if in the same corp, so that any one of them should not be org `admin` role.
2. system administrators, they usually only care about system level things, rarely create folders/dashboards.

Accordingly in my practice, I've written a proxy to automatically grant the creator `admin` permission to the folders/dashboards they created (their org roles remain unchanged), so that they can manage them without bothering a org `admin`. So far works well. 

Creating more orgs can be another alternative for my situation, but it causes some other problems (and I suppose it is not encouraged to use more than one org in a company from your design?). 

After all, it is difference on designing. I see in current design, only org `admin` are the group to create and manage folders/dashboards. (`Editors` can create but cannot manage them, which could make them upset, lol). Creators and admins are actually the same and only group, which are the org `admins`.

**Comment by marefr** [comment]
Thanks @pf23 now I understand. Basically your thoughts apply to users having org role editor. I can understand that it's a need for supporting org role editors to be able to manage permissions/settings of a folder that they've created. Could you please create a new feature request for this? Thanks
