### ISSUE TITLE
Make it possible to disable user

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11188]
### What Grafana version are you using?
5.0

Possibility to disable a user. I want to keep the user in the system but I don't want the user to be able to login.

I can change the password but then the user can change it by using the "Forgot password"-function at the login page.

**Comment by bergquist** [comment]
Not sure about this. Might be useful. Leaving this unprioritized for now.

**Comment by 88weighed** [comment]
As a workaround you can remove the user from all organisations. The account will still be there, but without any rights.

**Comment by flopp999** [comment]
Thanks, I will try it

**Comment by xlson** [comment]
We're working on implementing the disabling of users.

Implementation:
- users can be disabled/enabled by server admins in the users ui
- disabled users are not able to login to grafana (they will be told that it is because they are disabled)

**Comment by marefr** [comment]
Closed by #16820

**Comment by alexanderzobnin** [comment]
This feature is still not complete (I need to add UI for disabling users).

**Comment by alexanderzobnin** [comment]
@xlson guess this should be closed since we merged all PRs
