### ISSUE TITLE
[Feature request] Date/time control of user

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11189]
### What Grafana version are you using?
5.0

Possibility to set a date and/or time when the user shall be disabled to login, I want to keep the account but not allow the user to login.

**Comment by bergquist** [comment]
We might make it possible to disable accounts but I cant see us adding this kind of feature to Grafana. It's a unique request, so I think you would have to implement some kind of script that disable/enable users using the API (if we make it possible to disable users)
