### ISSUE TITLE
prometheus template time active labels/pods

### ISSUE THREAD

**Issue by kfox1111** [grafana/grafana#11184]
I've got a set of java processes running one per pod in kubernetes and metrics are scraped per pod into prometheus.

Some are sometimes malfunctioning, so I have a dashboard in grafana that templates out the pod name and lets you select one for display of the detailed graphs. Some of the graphs in particular show all the different kinds of memory in the java pools on the same graph to make it easy to spot weird things that may be happening. This does not lend itself to aggregating all the pods together, but needs to be displayed separately per pod to show problems easily.

So far, I templated with:
label_values(kubernetes_pod_name)

The problem comes in when you use kubernetes rolling upgrades. new pods come in and old pods go out. So currently, I have 3 active and 12 historical. The list is full enough and the names random enough its hard to find the active ones in the list.

I need a way to limit the list to only contain kubernetes_pod_names that have actively returned data during the user selected time window.

----
One idea for a new template query function:
query_result_values(promquery, label_name) - do prometheus query, return just the values of the specified label name. This lets them be passed to a query that selects based on label value easily.

There needs to be a way to pass the current time range as variables through the promquery to restrict it too.

**Comment by kfox1111** [comment]
Another alternative, query_result could be made to work with an additional feature that would let you do a regex replace on the result, where the initial string is just the data from the query, and the label name/values are mapped to regex values. so you could
/.*/$kubernetes_pod_name/

**Comment by davkal** [comment]
We can only work with Prometheus Labels API which does not take time parameters to limit the results to the recent ones. We could use the Series API instead, but its responses might be too big and make it unstable. It's really a downstream issue: https://github.com/prometheus/prometheus/issues/6865

**Comment by davkal** [comment]
Closing this for now.

**Comment by kakkoyun** [comment]
> We can only work with Prometheus Labels API which does not take time parameters to limit the results to the recent ones. We could use the Series API instead, but its responses might be too big and make it unstable. It's really a downstream issue: [prometheus/prometheus#6865](https://github.com/prometheus/prometheus/issues/6865)

Hello @davkal, I suppose this mentioned issue is handled by https://github.com/prometheus/prometheus/pull/7288. It'd be great to have support for these new parameters. I don't have much experience with Grafana codebase, I'd be glad to give it a shot.

Shall I create a new issue for it? Or should this issue be reopened?

cc @bwplotka

**Comment by zoltanbedi** [comment]
Hi @kakkoyun, I think it would make sense to create a new issue.

**Comment by kakkoyun** [comment]
Added a new issue https://github.com/grafana/grafana/issues/27537
