### ISSUE TITLE
Legacy PNG URL in Graphana 5.0.x redirect failing behind Apache reverse proxy

### ISSUE THREAD

**Issue by kav2k** [grafana/grafana#11180]
### What Grafana version are you using?
Version 5.0.1 (commit: a747ec3)
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Tried to display graphs with icingaweb2-module-grafana in direct mode
### What was the expected result?
Graph is displayed inside Icinga Web 2
### What happened instead?
Request to Graphana URL times out with a HTTP 500

---

Scenario: using Icinga2 + Icinga Web 2 + https://github.com/Mikesch-mp/icingaweb2-module-grafana (v.1.2.0)

The above module embeds Graphana graphs into Icinga Web 2 interface. It worked fine until Graphana 5.0.x and stopped working now.

The module uses legacy URLs (`render/dashboard-solo/db/`) and Graphana is supposed to redirect it to the new URLs (`d-solo/`). **However, that redirect fails in a reverse proxy setup, and Graphana spits out 500 after a timeout.**

Graphana log:

```
t=2018-03-09T17:31:39+0100 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/base-metrics?var-hostname=odin&var-service=apt&var-command=apt_verbose&panelId=10&orgId=1&width=640&height=280&theme=dark&from=now-7d&to=now&trickrefresh=now"
t=2018-03-09T17:31:39+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname= method=GET path=/dashboard-solo/db/base-metrics status=301 remote_addr=127.0.0.1 time_ms=4 size=259 referer=
t=2018-03-09T17:31:39+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname= method=GET path=/graphana/d-solo/000000003/base-metrics status=404 remote_addr=127.0.0.1 time_ms=3 size=13294 referer=
t=2018-03-09T17:32:39+0100 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2018-03-09T17:32:39+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/dashboard-solo/db/base-metrics status=500 remote_addr=130.92.120.51 time_ms=60002 size=1772 referer="https://example.com/icingaweb2/monitoring/list/services?servicegroup_name=apt&sort=service_severity"
t=2018-03-09T17:32:39+0100 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"
```

#10878 may be related.

See also https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/116

---

#### Apache configuration
Apache provides both Icinga Web 2 on `/icingaweb2` and Graphana on `/graphana`, acting as a reverse proxy for the latter:

```
    <Location "/graphana">
        ProxyPass http://localhost:5000
    </Location>

    ProxyPassReverse /graphana http://localhost:5000
```

#### Relevant Graphana configuration:
```
[server]
# Protocol (http, https, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 127.0.0.1

# The http port  to use
http_port = 5000

# The public facing domain name used to access grafana from a browser
domain = example.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://%(domain)s:%(http_port)s/graphana/
```

#### Relevant icingaweb2-module-grafana configuration:

Host: example.com/graphana
Protocol: Secure: https
Graphana access: Direct

To clarify: Direct appends an `<img>` to the page.

```
<img src="https://example.com/graphana/render/dashboard-solo/db/base-metrics?var-hostname=odin&var-service=apt&var-command=apt_verbose&panelId=10&orgId=1&width=640&height=280&theme=dark&from=now-7d&to=now&trickrefresh=now">
```

I have tried with Proxy (which tries to fetch the graph in the backend), which fails as well, and iFrame, which works (but is rather ugly, I prefer Direct which worked before).

iFrame embeds this:

```<iframe src="https://example.com/graphana/dashboard-solo/db/base-metrics?var-hostname=odin&var-service=hostalive&var-command=hostalive&panelId=9&orgId=1&theme=dark&from=now-6h&to=now"></iframe>```

---

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
```
https://example.com/graphana/render/dashboard-solo/db/base-metrics?var-hostname=odin&var-service=apt&var-command=apt_verbose&panelId=10&orgId=1&width=640&height=280&theme=dark&from=now-7d&to=now&trickrefresh=now
```
Response (HTTP 500):
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#000">

    <title>Grafana - Error</title>

    <base href="/graphana/" />

    <link rel="stylesheet" href="public/build/grafana.dark.css?v">

    <link rel="icon" type="image/png" href="public/img/fav32.png">
    <link rel="mask-icon" href="public/img/grafana_mask_icon.svg" color="#F05A28">

  </head>

  <body class="theme-dark">
    <div class="main-view">
      <div class="page-container">
        <div class="page-header">
          <div class="page-header__inner">
            <span class="page-header__logo">
              <i class="page-header__icon fa fa-frown-o"></i>
            </span>
            <div class="page-header__info-block">
              <h1 class="page-header__title">
                <a class="text-link" href="login">Grafana</a><span> / Server Error</span><span></span>
              </h1>
              <div class="page-header__sub-title">Sadly something went wrong</div>
            </div>
          </div>
        </div>
      </div>
      <div class="page-container page-body ng-scope" style="padding: 2rem">
        <div class="alert">
          <div class="alert-icon"><i class="fa fa-exclamation-triangle"></i></div>
          <div class="alert-body">
            <div class="alert-title">Timeout error. You can set timeout in seconds with &amp;timeout url parameter</div>
          </div>
        </div>
        <br />
        
        <div style="padding: 2rem 0 0">
          <p>Check the Grafana server logs for the detailed error message.</p>
        </div>
      </div>
    </div>
  </body>
</html>
```

**Comment by plachetka** [comment]
There is no problem with reverse proxy:

---
RewriteEngine on
RewriteRule ^/grafana/render/dashboard-solo/db/**mydashboardname**(.*) /grafana/render/d-solo/**mydashboardid**/**mydashboardname**$1 [R=301,L]

ProxyPreserveHost On
ProxyPass /grafana/ http://127.0.0.1:3333/
ProxyPassReverse /grafana/ http://127.0.0.1:3333/

---

This solutions works. By the way: there will be an update for icingaweb2-module-grafana soon.

**Comment by gino0631** [comment]
The problem is that "internal redirects" to the new URLs do not work, probably because Grafana tries to redirect internally from /dashboard-solo/db/... to **/grafana**/d-solo/... (or whatever the location is named) which can only be understood by the reverse proxy. So yes, a possible workaround is to implement redirects to the new URLs in Apache.

**Comment by marefr** [comment]
Confirmed as bug using a reverse proxy, in my case I tried with nginx. Seems like the server redirect in Grafana don't take the root url into consideration.

**Comment by kav2k** [comment]
Can confirm that it fixes my setup. Thanks, impressive response time!

**Comment by iDemonix** [comment]
+1 - I've upgraded and I'm still receiving the timeout too.

**Comment by marefr** [comment]
@nklmilojevic @iDemonix  Are you trying to render a panel that are in a collapsed row?

**Comment by nklmilojevic** [comment]
@marefr I've tried both and it's the same.

**Comment by iDemonix** [comment]
No, the dashboard I use is unchanged and the rows are uncollapsed, just seems to be the 10 second timeout still. I'll get more time to debug tomorrow.

**Comment by marefr** [comment]
Okay. If you save the dashboard one time just so that the migration up to v5 get persisted. Does it make any difference after when rendering a png?

One other thing you can do to possible get more information from phantomjs is to add the following to your [log] section in .ini configuration:

```
[log]
...
filters = png-renderer:debug
```

or otherwise

```
[log]
level = debug
```

Please include if you get any interesting debug messages from phantomjs when your render call fails.

**Comment by nklmilojevic** [comment]
Ok, I made a copy of the dashboard, it's still the same.

Here's the log:

```t=2018-03-19T16:33:12+0100 lvl=dbug msg="[phantom] Loading a web page: http://localhost:6000/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500&tz=UTC%2B01%3A00&render=1 status: fail 60000" logger=png-renderer
t=2018-03-19T16:34:12+0100 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2018-03-19T16:34:12+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy status=500 remote_addr=myaddress time_ms=60003 size=1763 referer="https://mygrafanadomain.com/d/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1"
t=2018-03-19T16:34:12+0100 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"```

If I roll back to 4.6.3 this rendering finishes in a matter of seconds.

**Comment by marefr** [comment]
Thanks. If you browse some of these url's:
* http://localhost:6000/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500&tz=UTC%2B01%3A00&render=1
* http://localhost:6000/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500&tz=UTC%2B01%3A00
* http://localhost:6000/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500&render=1
* http://localhost:6000/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500

Replace localhost:6000 with domain if you're using that.

Do you get a rendered png using any of these url's?

**Comment by iDemonix** [comment]
Re-saving the dashboard seems to have done the trick for me, it now seems like the icingaweb2 module isn't following the 302, but that's an issue for their repo.

**Comment by nklmilojevic** [comment]
@marefr yes, all these links are working for me when I replace the domain. Any ideas why? Thanks!

**Comment by marefr** [comment]
@nklmilojevic it's working when you use localhost but not domain or the other way around?

**Comment by nklmilojevic** [comment]
It's working when I use live domain (grafana.mydomain.com).

**Comment by marefr** [comment]
Okay interesting. Going to try and see if I can reproduce it...

**Comment by marefr** [comment]
@nklmilojevic I've just tried the following setup and that works as expected.

I can render using both of these url's:
* http://localhost:3000/render/d-solo/000000003/big-dashboard?orgId=1&panelId=4&from=1521543529596&to=1521547129596&width=1000&height=500&tz=UTC%2B01%3A00
* http://grafana.myproxy.com/render/d-solo/000000003/big-dashboard?orgId=1&panelId=4&from=1521543529596&to=1521547129596&width=1000&height=500&tz=UTC%2B01%3A00

**/etc/hosts**
```
127.0.0.1 grafana.myproxy.com
```

**Grafana config**
```
[server]
domain = grafana.myproxy.com
```

**nginx config**
```
events { worker_connections 1024; }

http {
  sendfile on;

  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;

  server {
    listen 80;
    server_name grafana.myproxy.com;

    location / {
      proxy_pass http://localhost:3000/;
    }
  }
}
```

Would it be possible for you to include your grafana [server] config and nginx config?

**Comment by nklmilojevic** [comment]
Sure, I'll leave the config below. Here's the example, I cannot render through this url:

https://grafana.mydomain.com/render/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521533435197&to=1521555035197&width=1000&height=500&tz=UTC%2B01%3A00

But it works through this:

https://grafana.mydomain.com/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500&tz=UTC%2B01%3A00&render=1

Notice the first one is the one that is opened when I click direct link, and it has /render/ in url, and the one that works has only &render=1 at the end of the URL.

Here's the grafana.ini:

```
[server]

protocol = http
http_addr =
http_port = 6000 
domain = grafana.mydomain.com
root_url = https://grafana.mydomain.com
```

NGINX config:

```
server {
    listen 80;
    server_name grafana.mydomain.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443;
    server_name grafana.mydomain.com;
    
    location / {
        proxy_pass http://localhost:6000;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;

        proxy_max_temp_file_size 0;

        #this is the maximum upload size
        client_max_body_size 10m;
        client_body_buffer_size 128k;

        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;

        proxy_buffer_size 4k;
        proxy_buffers 4 32k;
        proxy_busy_buffers_size 64k;
        proxy_temp_file_write_size 64k;
    }

    location ~ /.well-known {
        allow all;
    }

    ssl on;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !MEDIUM";
    ssl_dhparam /etc/nginx/dhparams.pem;

    ssl_certificate /etc/letsencrypt/live/grafana.mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.mydomain.com/privkey.pem;
}
```

**Comment by marefr** [comment]
Okay interesting. Please try and comment out your root url to the default, i.e.

```
;root_url = https://grafana.mydomain.com
```

Then I think both of the url's should work

**Comment by nklmilojevic** [comment]
I've tried that and it's still the same.

**Comment by marefr** [comment]
That's really weird. 

The thing with the `&render=1` is only an internal parameter that is set by phantomjs when you call https://grafana.mydomain.com/render/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521533435197&to=1521555035197&width=1000&height=500&tz=UTC%2B01%3A00

The idea is that Phantomjs then are calling http://localhost:6000/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521533435197&to=1521555035197&width=1000&height=500&tz=UTC%2B01%3A00&render=1

In your case with `root_url = https://grafana.mydomain.com` I guess that phantomjs are calling https://grafana.mydomain.com/d-solo/5p3h4ikmk/zabbix-server-dashboard-copy?orgId=1&panelId=1&from=1521451911462&to=1521473511462&width=1000&height=500&tz=UTC%2B01%3A00&render=1. Seems like phantomjs cannot access https://grafana.mydomain.com?

Please try and set the `root_url = %(protocol)s://%(domain)s:%(http_port)s/` explicitly so that phantom uses localhost:6000 instead

**Comment by nklmilojevic** [comment]
Hm, I tried it and it's the same. 

Is this somehow related to https://github.com/grafana/grafana/pull/11282 which is fixed in upcoming 5.0.4?

**Comment by marefr** [comment]
Only if you're trying to render a panel that is located inside a collapsed row.

**Comment by nklmilojevic** [comment]
I've tried it on a collapsed row and also a dashboard with only one graph without collapsable rows and it's the same.

**Comment by matthenning** [comment]
I can reproduce @nklmilojevic's behaviour. Grafana 5.1.3 on Debian 9.4 through an NGINX reverse proxy.
