### ISSUE TITLE
debian package: insserv: script grafana: service grafana already provided!

### ISSUE THREAD

**Issue by dahabakuk** [grafana/grafana#11194]
2 init scripts are provided with the grafana package:

# dpkg -L grafana | grep init.d
/etc/init.d
/etc/init.d/grafana-server
/etc/init.d/grafana

# apt show grafana
Package: grafana
Version: 5.0.1
Priority: extra
Section: default
Maintainer: contact@grafana.com
Installed-Size: 156 MB
Depends: adduser, libfontconfig
Homepage: https://grafana.com
Download-Size: 51.7 MB
APT-Manual-Installed: yes
APT-Sources: https://packagecloud.io/grafana/stable/debian stretch/main amd64 Packages
Description: Grafana

# systemctl status grafana
● grafana.service - LSB: Start grafana at boot time
   Loaded: loaded (/etc/init.d/grafana; generated; vendor preset: enabled)
   Active: active (exited) since Sun 2018-03-11 10:56:06 CET; 1min 13s ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/grafana.service

Mar 11 10:56:06 server systemd[1]: Starting LSB: Start grafana at boot time...
Mar 11 10:56:06 server systemd[1]: Started LSB: Start grafana at boot time.

but the service is not running:

# ps waxu|grep grafana
root      1311  0.0  0.0  12784   952 pts/0    S+   10:57   0:00 grep grafana

trying to disable the grafana init script:

# systemctl disable grafana
grafana.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable grafana
insserv: script grafana: service grafana already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header

enabling grafana-server errors out on debian stretch with:

# systemctl enable grafana-server
Synchronizing state of grafana-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable grafana-server
insserv: script grafana: service grafana already provided!
insserv: script grafana: service grafana already provided!
Failed to enable unit: Unit /run/systemd/generator.late/grafana.service is transient or generated.

starting the init script manually everything works:

# systemctl start grafana-server
# ps waxu|grep grafana
grafana   1641  0.2  0.7 304400 31916 ?        Ssl  11:00   0:00 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning

**Comment by RREE** [comment]
I have the same problem. 

Manually starting the grafana-server works without problems. But I cannot enable it to start automatically at reboot. I have to remember to start it manually everytime I have to reboot my server machine (about 2 a year)

**Comment by l0ckt1ght** [comment]
in /etc/systemd/system:
`   0 lrwxrwxrwx  1 root root   35 Jan 31 13:11 grafana-server.service -> /lib/systemd/system/grafana.service
   0 lrwxrwxrwx  1 root root    9 Feb  4 15:26 grafana.service -> /dev/null
`
/lib/systemd/system/grafana.service doesn't exist for me.

checking /etc/init.d/ I have two scripts:
grafana
grafana-server

the grafana-server init script has the name set as grafana for init info, so I changed it to 'grafana-server'

removed the /etc/systemd/system/grafan-server.service

issued systemctl daemon-reload
then systemctl enable grafan-server

it falls back to init scripts and successfully enabled it and loads on reboot

**Comment by Gedioa** [comment]
> in /etc/systemd/system:
> ` 0 lrwxrwxrwx 1 root root 35 Jan 31 13:11 grafana-server.service -> /lib/systemd/system/grafana.service 0 lrwxrwxrwx 1 root root 9 Feb 4 15:26 grafana.service -> /dev/null`
> /lib/systemd/system/grafana.service doesn't exist for me.
> 
> checking /etc/init.d/ I have two scripts:
> grafana
> grafana-server
> 
> the grafana-server init script has the name set as grafana for init info, so I changed it to 'grafana-server'
> 
> removed the /etc/systemd/system/grafan-server.service
> 
> issued systemctl daemon-reload
> then systemctl enable grafan-server
> 
> it falls back to init scripts and successfully enabled it and loads on reboot

Thanks this fixed my grafana problem i just received after apt-update en apt-upgrade
(you forgot one "a" in grafana)

**Comment by WillemWever** [comment]
> in /etc/systemd/system:
..........
> it falls back to init scripts and successfully enabled it and loads on reboot

Thanks a lot l0ckt1ght, this works for me!

**Comment by torkelo** [comment]
Closing this as this seems to be a very uncommon problem
