### ISSUE TITLE
Hide database credentials from database.url in "Server Admin"?

### ISSUE THREAD

**Issue by n0guest** [grafana/grafana#11190]
Hello.

In "Server admin" section all passwords and secrets replaced by "*" symbols. But it isn't affects database url, which also contains sensitive information. E.g:

```
mysql://UserName:SomeSecret@ServerName:3306/DatabaseName
```
It would make sense to hide username&password at least (could be easily replaced by regexp?).

Thanks.

PS: It reproducible on "fresh" Grafana 5.0.1

**Comment by bergquist** [comment]
This should be solved by replacing the SQL password in the connection string with ****

https://github.com/grafana/grafana/blob/master/pkg/api/admin.go#L11

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/11258
