### ISSUE TITLE
how to set  configuration when set nginx reverse proxy

### ISSUE THREAD

**Issue by cqiuping** [grafana/grafana#11197]
### What Grafana version are you using?
5.0.0-1 x86_64
### What datasource are you using?
mysql
### What OS are you running grafana on?
CentOS release 6.5 (Final)
### What did you do?
running grafana behind a reverse proxy with nginx
### What was the expected result?
successfully running grafana behind a reverse proxy with nginx
### What happened instead?
can not  running grafana behind a reverse proxy with nginx, my nginx.conf include a conf.d, and there are setting about grafana in my conf.d:
```
server {
        listen 80;
        root /usr/share/grafana; #my grafana directory
        index index.html index.htm;

        location /grafana/ {
                proxy_pass http://127.0.0.1:3000/;
                rewrite ^/grafana/(.*) /$1 break;
                proxy_set_header Host $host;
        }
}

```
and in my grafana.ini, the domain and root_url like this:
```
;domain = foo.bar

;enforce_domain = true

;root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

```
when i visit http://[server_ip]/grafana, the page will redirect to http://[server_ip]/login and will return 404 at last. when i visit http://[server_ip]/foo.bar/grafana, which will still return 404 .
i don't know why, can anyone help me? thx~

**Comment by bergquist** [comment]
Please ask questions on the [community site](https://community.grafana.com/)

We have a guide for setting up grafana behind a reverse proxy http://docs.grafana.org/installation/behind_proxy/

**Comment by cqiuping** [comment]
I am sorry for ignorance， i just do it as the reverse proxy docs, then still can not solve it, i will ask the question on the community site, thx.
