### ISSUE TITLE
[Feat] Support custom collation/charset for MySQL storage

### ISSUE THREAD

**Issue by CAFxX** [grafana/grafana#11198]
### What Grafana version are you using?
The problem appears in both 5.0.0 and 4.6.x, and it appears to be still present on master.

### What datasource are you using?
none yet (failure occurs when setting up sql configuration storage) 

### What OS are you running grafana on?
linux x64, kernel 4.4

### What did you do?
Attempted to use for config storage a mysql-compatible product (clustrix) that does not include support for utf8mb4_unicode_ci (only for utf8_general_ci)

### What was the expected result?
Grafana to be able to use this database for storing it's dashboard/user configuration (not for time series)

### What happened instead?
The database returns an error when sending the first query because the request uses an encoding that is not supported by the database

### Potential solution
Would it be possible to have the collation (**edit**: and the charset) be user-configurable? Right now it is hardcoded to utf8mb4_unicode_ci: https://github.com/grafana/grafana/blob/f1fc1672be130febcb8df05cb3f7559a7d5e4743/pkg/services/sqlstore/sqlstore.go#L119-L120

**edit**: maybe this could be made generic by allowing the user to pass in a [URL.Values](https://golang.org/pkg/net/url/#Values) object, that SQLStore would then fill in with the appropriate defaults. This would allow users greater control over their database connection, without requiring grafana to know about every possible connection option.

**edit**: caution: please note that the current default collation (`utf8mb4_unicode_ci`) and charset (`utf8mb4`) are currently hardcoded in a bunch of different places besides the connection string: https://github.com/grafana/grafana/search?utf8=%E2%9C%93&q=utf8mb4&type=

**Comment by JnMik** [comment]
I would appreciate this too. 

I tried concatenation queries with SET NAMES 'utf8'; ... 
I also tried to CAST the metric field with CONVERT(name USING utf8) as metric, but it wasn't working either.

So all my french accents appears broken in Grafana.

Is this planned at all in the backlog ?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
