### ISSUE TITLE
tables missing data when resize in responsive mode

### ISSUE THREAD

**Issue by renx123** [grafana/grafana#11196]
### What Grafana version are you using?
grafana-5.0.1-1
### What datasource are you using?
mysql
### What OS are you running grafana on?
centos 7

I am having problems with grafana version 5 after upgrading. It seems tables don't show all data with smaller screen (iphone6, iphone X etc). Shows OK on PC and ipad. Also possible to reproduce with responsive browser window. Table has over 100 rows. Tried to hide first coulum with names and then it fits better. So it must be related to the first coulum which after resizing has information on double rows 

https://www.dropbox.com/s/qmbumsi8wsq9rwv/test2.mp4?dl=0

At the end of the video it's seen how it cuts out data.

**Comment by bergquist** [comment]
@Ijin08 perhaps you could take a loot at this?

**Comment by Ijin08** [comment]
I am not able to see what data that is not shown on smaller screen. It looks ok to me.

**Comment by torkelo** [comment]
closing this, not able to see what is not shown when reducing size either, and no update in over > month
