### ISSUE TITLE
Bug 9094 reintroduced in 5.0.1 (Pending invitations tab disappeared)

### ISSUE THREAD

**Issue by tcgjensen** [grafana/grafana#11202]
- What Grafana version are you using?
5.0.1

- What datasource are you using?
not relevant for this bug

- What OS are you running grafana on?
Centos

- What did you do?
I invited a new user and clicked (by accident) "send invite email", but I do not have an email server connected to grafana.

- What was the expected result?
Usually a new tab called pending invitations appears next to the tab users. The pending invitations tab displays all the users that have been invited but don't have an account yet.

- What happened instead?
After submitting it said created invite for user but the pending invitation tab is not shown.

We don't use an e-mail server. That's why selected the box skip sending invite e-mail when I created the user. When I created users in the past I usually went into the pending invitations tab and copied the invite link for the new user and sent it manually. However this is no longer possible due to the missing view.

**Comment by marefr** [comment]
I tested without a proper smtp server setup and invite a new user with and without *Send invite email* checked and it created two pending invites, see screenshot below:

![image](https://user-images.githubusercontent.com/1668778/37284243-18197238-25fb-11e8-932d-332ad993eb29.png)

When using *Send invite email* checked and without proper smtp config an error will be shown and the page will not automatically refresh to show the pending invites. But if you hit refresh you'll find them.

**Comment by tcgjensen** [comment]
But it does not appear when i do it. I can make a video showing it. Dont
close my ticket when it is still an issue.

**Comment by marefr** [comment]
Could it be related to your role in the organization?

**Comment by tcgjensen** [comment]
I am not one for admitting it, but it might just have been me that have
misunderstood something.
I am not able to recreate it now, but the fact is that I invited a new user
and afterwords I could not see it in the pending...and still now I am
unable to invite a user with same username/email - I get user exists when I
try....

It is really annoying that you are not able to create two users with same
email.

Anyway I think you afterall can close the ticket, but I am stil wondering
where this invited user - that I cant see - is...? Is there some queue
where I can find him and delete him? He does not appear in any of the
GUIs...


2018-03-12 17:38 GMT+01:00 Marcus Efraimsson <notifications@github.com>:

**Comment by marefr** [comment]
Please check server admin. Maybe you created a user in server admin and thought you invited that user? I'm closing this for now. Please come back here if the problem would come up again and we'll consider re-opening it.
