### ISSUE TITLE
Postgres Sqlstore Migration Failure

### ISSUE THREAD

**Issue by rabun788** [grafana/grafana#11204]
### What Grafana version are you using?
Working: 4.6.2  Not Working: 5.0.1
```
Total dashboards 1271
Total users 2
Active users (seen last 14 days) 2
Total organizations 1
Total datasources 22|
Total playlists 4
Total snapshots 47
Total dashboard tags 62
Total starred dashboards 219
Total alerts 1
```
https://community.grafana.com/t/postgres-migrator-issues-from-4-6-2-5-0-1-11204/6086?u=kmjackson788
### What datasource are you using?
`FROM postgres:9.4`
### What OS are you running grafana on?
Darwin High Sierra | Linux Centos7 --> both with Docker
### What did you do?
Tried to upgrade to 5.0.1 from 4.6.2
Not touching postgres, stopped old version (4.6.2) and started up 5.0.1. Failed to start. log is called startup.log
### What was the expected result?
A clean startup that would have migrated the 4.6.2 data to the 5.0.1 data in Postgres.
### What happened instead?
[startup.log](https://github.com/grafana/grafana/files/1802603/startup.log)
```
t=2018-03-12T11:34:10+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-03-12T11:34:10+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2018-03-12T11:34:10+0000 lvl=info msg="App mode production" logger=settings
t=2018-03-12T11:34:10+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=postgres
t=2018-03-12T11:34:10+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-03-12T11:34:10+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-03-12T11:34:10+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-03-12T11:34:10+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-03-12T11:34:10+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-03-12T11:34:10+0000 lvl=info msg="Executing migration" logger=migrator id="Migrate all Read Only Viewers to Viewers"
t=2018-03-12T11:34:10+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: pq: Could not complete operation in a failed transaction\n"
```
### If related to metric query / data viz:
n/a
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 Failed to start, so no info.

*Let me know if you need my pg_dump for debugging.*

**Comment by rabun788** [comment]
[grafana_postgres_pgdump.sql.tar.gz](https://github.com/grafana/grafana/files/1802617/grafana_postgres_pgdump.sql.tar.gz)
The pg_dump backup that is failing.

**Comment by marefr** [comment]
That's weird. The only thing it's executing for the "Migrate all Read Only Viewers to Viewers" is `UPDATE org_user SET role = 'Viewer' WHERE role = 'Read Only Editor'` and you wrote that you only have 2 users. Wonder if there's something else happening after this?

* Did you backup the database before upgrade? 
* Have you tried upgrading/starting up multiple times? 
* Could you please include the content of your migration_log table?

There are of course workarounds for getting your upgrade working, but it would be interesting to know why this is happening.

**Comment by svenklemm** [comment]
The sequence for your migration_log id is out of sync with your data.

The following command should fix it:
```
alter sequence migration_log_id_seq restart with 174;
```

**Comment by rabun788** [comment]
Thanks @svenklemm ! That did it!

**Comment by marefr** [comment]
@svenklemm just of curiosity how/where did you that this was the problem?

**Comment by svenklemm** [comment]
Hey @marefr ,

i loaded his dump and got the same error he got when trying to start grafana. Then I checked postgres error log where i  saw the actual errors:
```
ERROR:  duplicate key value violates unique constraint "migration_log_pkey"
DETAIL:  Key (id)=(125) already exists.
```
Which led me to check the sequence used for migration_log
```
grafana=# select last_value from migration_log_id_seq ;
 last_value
------------
        127
```
And the highest value for the id in migration_log that is actually used:
```
grafana=# select max(id) from migration_log;
 max
-----
 174
```
So the sequence needed to be reset to 174 to continue gernerating valid ids again.

This error can happen if you insert into migration_log without using the sequence, like when you migrate from sqlite or mysql. If you do that you need to adjust all sequences after migration.

**Comment by marefr** [comment]
Awesome. Thanks a lot for that detailed description!

**Comment by mkue** [comment]
Thanks a lot! I had exactly the same problem.

**Comment by gelicia** [comment]
Also wanted to comment that this debugging flow helped me as well! Thanks for the documentation!
