### ISSUE TITLE
Is there a limit for amount of dashboard by tag (Links, w/out dropdown)?

### ISSUE THREAD

**Issue by n0guest** [grafana/grafana#11203]
Hello.

I'm trying to add links to dashboards by tag. Links to 6 dashboards shown as expected, but link 7th dashboard only shown when "dropdown" is enabled. Is this a hardcoded limit or bug?

PS: Grafana 5.0.1 from deb package

**Comment by bergquist** [comment]
I'm not sure I understand what you are trying to do. Link how?

linking from a dashboard to other dashboard can contain more than 6 links 
![image](https://user-images.githubusercontent.com/618863/37329265-6a31a228-269d-11e8-8cd3-c0c6cc6736bc.png)

**Comment by n0guest** [comment]
> I'm not sure I understand what you are trying to do. Link how?

I'm very sorry. I counted one more time. And it looks like problem can be reproduced on 7+ dashboard links. Here is how it looks:

![screenshot-20180313-144743](https://user-images.githubusercontent.com/5829393/37340014-a7320c1e-26cd-11e8-92f7-43a3c587975c.png)

As you can see, without "grouping" there are links only to 7 dashboards. When in the dropdown there is more of them (10 in fact). But all of them added in "Links" with one differences - with or without enabled option "as dropdown":

![screenshot-20180313-145046](https://user-images.githubusercontent.com/5829393/37340083-f4ad2c3a-26cd-11e8-9197-90e6aa2b55a5.png)

All other options are the same - dashboards by tag "test". I hope, i explained it clear enough)

**Comment by torkelo** [comment]
yes, when showing dashboard as individual links the limit is 7

**Comment by torkelo** [comment]
will add tooltip about this
