### ISSUE TITLE
Cannot update datasource in v5.0.1. 'Save & Test' does nothing. Status code 415

### ISSUE THREAD

**Issue by viktorsmari** [grafana/grafana#11209]
### What Grafana version are you using?
v5.0.1 commit: a747ec3
### What datasource are you using?
Influxdb
### What OS are you running grafana on?
docker-compose running grafana, influxdb, [https-portal](https://github.com/SteveLTN/https-portal) for nginx+letsencrypt
### What did you do?
We were changing the server URL. Tried to update the datasource accordingly. Unable to click 'Save & Test', resulting in code 415 in the console
### What was the expected result?
The datasource URL should be updated.
### What happened instead?
Nothing. Console log shows:

angular.js:12837 POST `URL` 415 ()
(anonymous) @ angular.js:12837
g @ angular.js:12564
u @ angular.js:12312
u @ angular.js:17145
(anonymous) @ angular.js:17193
$digest @ angular.js:18331
$apply @ angular.js:18628
(anonymous) @ angular.js:27456
dispatch @ jquery.js:5206
g.handle @ jquery.js:5014
16:34:31.305 angular.js:14794 Possibly unhandled rejection: {"data":[{"classification":"ContentTypeError","message":"Unsupported Content-Type"}],"status":415,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources","data":{"name":"test","type":"influxdb","url":"`URL`","access":"direct","jsonData":{"keepCookies":[]},"secureJsonFields":{}},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"complete"}

** Response: **
[{"classification":"ContentTypeError","message":"Unsupported Content-Type"}]

**Comment by marefr** [comment]
Was it influxdb url you changed and then pressed save?

Could you please include screenshots of network request/response payload that fails using chrome dev tools. Also the full url of that request would be valuable. Thanks

**Comment by viktorsmari** [comment]
Yes it was the influxdb url we were changing

![2018-03-12_539x48](https://user-images.githubusercontent.com/1689020/37297618-6c1d0ae8-261e-11e8-965f-8f9aee4915ba.png)
2
![2018-03-12_449x432](https://user-images.githubusercontent.com/1689020/37297619-6c456560-261e-11e8-9819-57268940405f.png)

**Comment by viktorsmari** [comment]
I can confirm that this is an nginx related thing. If I skip http**s** and go to the url and port 3000 - the 415 error stops.

However, I remember I was able to change the url a few grafana versions ago, which means something has changed in grafana which is causing this.

**Comment by marefr** [comment]
Are you using a grafana/nginx configuration according to http://docs.grafana.org/installation/behind_proxy/#nginx-configuration? 

For further help, please include specific grafana configuration parameters changed and your nginx config, if possible.

**Comment by viktorsmari** [comment]
Here is the nginx config, based on the https://github.com/SteveLTN/https-portal/blob/master/examples/custom_config/nginx-conf/my.example.com.ssl.conf.erb
```
server {
    listen 443 ssl http2;
    server_name <%= domain.name %>;

    ssl on;
    ssl_certificate <%= domain.chained_cert_path %>;
    ssl_certificate_key <%= domain.key_path %>;

    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache shared:SSL:50m;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
    ssl_prefer_server_ciphers on;

    ssl_dhparam <%= dhparam_path %>;

    # Prevent Nginx from leaking the first TLS config
    if ($host != $server_name) {
        return 444;
    }

    <% if domain.upstream %>
    location / {
        proxy_pass <%= domain.upstream %>;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #Fixes long datasets being cut off when writing from telegraf to influxdb 
        chunked_transfer_encoding off;
        gzip off;
        proxy_set_header Content-Type "text/plain";
        proxy_http_version 1.1;
        proxy_buffering off;

        <% if ENV['WEBSOCKET'] && ENV['WEBSOCKET'].downcase == 'true' %>
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 2h;
        <% end %>
    }
    <% else %>
    location / {
        root   <%= domain.www_root %>;
        index  index.html;
    }
    <% end %>
}
```

**Comment by viktorsmari** [comment]
**Update**: I am also getting this issue when I am trying to rename a dashboard.

![2018-03-13_814x155](https://user-images.githubusercontent.com/1689020/37353471-b2486bfe-26df-11e8-8981-82263d2944de.png)

Failed to load resource: the server responded with a status of 415 ()

angular.js:14794 Possibly unhandled rejection: [{"classification":"ContentTypeError","message":"Unsupported Content-Type"}]

**Comment by marefr** [comment]
Based on your nginx config where you have some `proxy_set_header Content-Type "text/plain";` it seems like that is the problem, i.e. when a request with json payload is sent from grafana client to server it's somehow are sent with content-type != application/json

**Comment by viktorsmari** [comment]
You are right. Thank you for your help!
