### ISSUE TITLE
Opening a collapsed row causes the Save dialog to appear when leaving

### ISSUE THREAD

**Issue by kerams** [grafana/grafana#11208]
### What Grafana version are you using?
5.0.1
### What datasource are you using?
InfluxDB 1.5.0
### What OS are you running grafana on?
Windows Server 2016
### What did you do?
* Navigate to a dashboard that has a row in the collapsed state.
* Open the row without making any other changes to the dashboard
* Navigate to a different dashboard
### What was the expected result?
I expected to be taken to the new dashboard right away (I think this is how it worked in 4.6.3)
### What happened instead?
Unsaved changes dialog appears.

**Comment by bergquist** [comment]
The json setting for open/collapsed rows should be removed before checking if a dashboard have unsaved changes. https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/unsaved_changes_srv.ts#L94

**Comment by kerams** [comment]
The fix for this is not included in 5.1.0, is it?

**Comment by kerams** [comment]
@torkelo FYI, does not look good using the nightly either.

**Comment by torkelo** [comment]
it is included, I cannot replicate any unsaved changes dialog after expanding or collapsing a row (that was saved in either state)

**Comment by torkelo** [comment]
Can you include your dashboard json?

**Comment by kerams** [comment]
While preparing an example for you I noticed it works OK once I resave the dashboard. The diff revealed that lines like 
```
"yaxis": {
    "align": false,
    "alignLevel": null
}
```
were being automatically added to some panels, and those were marked as changes. Sorry for the false alarm :)
