### ISSUE TITLE
Can I use influxdb variable in grafana alerts notification message?

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#11219]
Please include this information:
### What Grafana version are you using?
 4.6.2
### What datasource are you using?
 influxdb
### What OS are you running grafana on?
 ubuntu14.04

**Comment by bergquist** [comment]
Thats currently not supported. But thats something we will add once we start working on https://github.com/grafana/grafana/issues/5848

**Comment by crazy-canux** [comment]
Thanks！
