### ISSUE TITLE
associate a server's two metrics (out of many servers's metrics) for an an alert

### ISSUE THREAD

**Issue by th3333** [grafana/grafana#11216]
Hi,

I am trying to create an alert for servers with high load (i.e. > 20) and it is not in testing mode. The metrics (coming from graphite) are in one single graph as A and B:

```
A:       company.monitor.server.*.load
B:       company.status.server.*.isTesting
```

the star above is the wildcard for all the servers (hostnames as server01, server02, server03…) . The “isTesting" is a number of either 1 or 0 for each server ( 1 means it is in testing and no means it is not in testing).

Can someone let me know how I can create an alert so if a server with high load (AND it is not in testing) will trigger an alert?

(the difficulty is to associate a server’s load with the corresponding “isTesting” value.)

Many thanks.

**Comment by bergquist** [comment]
That's not supported in Grafana. Some datasources allow you to join/mix data in the query. Since it looks like your using Graphite you might want to take a look at http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.divideSeriesLists
