### ISSUE TITLE
Table panel with clickable cell setting variable using any row column value

### ISSUE THREAD

**Issue by ntodorov70** [grafana/grafana#11210]
This request is similar to #3754 but I need a specified variable to be set on a cell click.
I know I can achieve this opening the dashboard's URL adding the variable and the needed value as URL parameter. The last causes a annoing "flickering" page reload and the selected time interval get lost. I hope this can be prevented by directly setting a variable. Could you please check if this can be implemented easily?

**Comment by bergquist** [comment]
What datasource are you using? Sounds like you want to use ad-hoc filters
 http://docs.grafana.org/reference/templating/#variable-types

**Comment by ntodorov70** [comment]
Thank you for the quick answer. Ad-hoc filter is not what I'm looking for.
I have to visualize apache logfile and I have the incoming reqest types stored in a "req_type" tag in influxdb. 
I list the values of the tag in a variable. Selecting a "req_type" value in the dropdown forces it's traffic to be displayed in a graph panel.
This works excellent without flickering.
Now I would like to order the request types based on the max request count and displaying both (type and max count) in a table.
In the table the user can get an impression of how many requests of every type have been handled and visualize the traffic of a given type by selecting the corresponding row in the table. As said it works with the "render value as link" functionality but the reload causes flickering of the page and  loss of the selected time interval.

**Comment by kushalsen38** [comment]
hi @bergquist @marefr 

I am using the grafana 6.7.2.
I have added a link to a cell in a table panel (dashboard-1), which when clicked goes to a different dashboard (dashboard-2).

Now, in dashboard-2, we have a drop-down (same as cell value in dashboard-1). In the drop-down in dashboard-2 have a template variable based on the drop-down template variable i have 2 table panel which get populated in the dashboard-2. 
 
i want it should select the same value same as the cell value clicked in dashboard-1.

Currently as i have use the link in dashboard-1 as: d/postloaddetailv1/postload-detail-dashboard?orgId=1&refresh=10s&var-Taskflow="$__cell" 

![table-dashboard-1](https://user-images.githubusercontent.com/56292329/81257678-8832c200-9051-11ea-8856-616b8fc85154.JPG)

In the dashboard-2, my drop-down variable is not selecting any value. And the other panel in dashboard-2 that are dependent on the drop-down is showing up the data for the 1st value from the drop-down.  

Any one help me on this.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
