### ISSUE TITLE
Added concentration units

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11211]
I have never been using Github to help creating code, so please tell me if I am doing something wrong.

I will try to add more units to Grafana, I will add below units

We are measuring gases and we use a lot of different units for this:
ppm
ppb
ng/m3
ng/Nm3
μg/m3
μg/Nm3
mg/m3
mg/Nm3
g/m3
g/Nm3
Nm3

all N above means Normal cubic meter, which is normalized(NTP)

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/11212

**Comment by shred** [comment]
Can you use a superscript 3 ( ³ ) for cubic? A normal 3 looks just wrong here, it hurts my eyes. :wink:

**Comment by flopp999** [comment]
I had the same thought but I looked at square meters and the superscript 2 was really small and difficult to see.
Can you check square meters unit and reply what you think about my thought?

**Comment by shred** [comment]
IMHO I wouldn't think too much about the readability. m³ is the official SI notation, and it is consistent to the other notations used in Grafana (like m², ft² or sec²). One could use the browser zoom to enhance readability.

**Comment by flopp999** [comment]
@shred I am just about to change to ³.
Do you see any other unit that have 3 instead of ³.
I found Nm3, dm3 and m3.
What do you think about Feet/sec², would that be "Feet/s²"?

**Comment by shred** [comment]
I have found no other units than the one you have found already.

About the seconds... According to SI, the correct notation would be s², not sec².
