### ISSUE TITLE
Time limit on graph (clean before 03:00)

### ISSUE THREAD

**Issue by whiteud** [grafana/grafana#11217]
Grafana v.5.0.0 (commit: af6e283)
Datasource: Elasticsearch
OS: Linux, Docker

I select query range on dashboard "Last 12 hours" on all charts, but i see graph only from 3:00AM to now:
![image](https://user-images.githubusercontent.com/29026259/37327126-11fa6924-26a6-11e8-8064-8d3e802daeee.png)

But if i use Query Inspector i see in response objects before 3:00
![image](https://user-images.githubusercontent.com/29026259/37327181-39ad0350-26a6-11e8-9393-87eab3eba371.png)

unixtime: 1520881560 is 12.03.2018 7:06PM, but on chart all graphs (from Elasticsearch) begining in 13.03.2018 3:00AM. Zabbix datasourse show more 6h.

I try query on Graylog and see all history.

**Comment by whiteud** [comment]
Any news? How fix this?

**Comment by torkelo** [comment]
can you show the complete response in json, what timezone are you in? Grafana shows the data ES returns and we have no other reports on issues like this so it's 99% a query issue or data issue. If you enable points you can see all data points your query returns. 

Also a thing with the data point you show in your screenshot, it says doc_count: 0, which is shown in the graph, so can't actually see any issue here :)

**Comment by whiteud** [comment]
That my settings of Datasource: ![image](https://user-images.githubusercontent.com/29026259/37901569-43da5f90-30fa-11e8-8cd1-df2b34b22ba2.png)

Preferences in user: Timezone: Default,
Preferences in Configuration: Timezone: Local browser time

that complete response:
[complete_response.txt](https://github.com/grafana/grafana/files/1847439/complete_response.txt)

On other Grafana installed not in Docker - i dont see problem like this

**Comment by torkelo** [comment]
i can only see 0 values before 3am, so the graph looks correct

**Comment by whiteud** [comment]
This chart from Grafana (24h): ![image](https://user-images.githubusercontent.com/29026259/37905536-dd85f020-3107-11e8-98d0-c31afcbc0812.png)

This chart from Graylog (24h): ![image](https://user-images.githubusercontent.com/29026259/37905573-f47892ec-3107-11e8-94c8-2ebdde869043.png)

Requests are the same

**Comment by whiteud** [comment]
requests are the same:

Grafana graph (24h): 

![image](https://user-images.githubusercontent.com/29026259/37905681-4ce4f006-3108-11e8-89f4-06fa4e94508b.png)

Graylog graph (24h):
![image](https://user-images.githubusercontent.com/29026259/37905712-688a0792-3108-11e8-8fa1-432d08e0478b.png)

**Comment by torkelo** [comment]
Request can’t be the same, or if they are it is strange ES but you encountered.

Maybe you have not specified index pattern correctly so not all indices are queried? Compare the exact full ES request between what Grafana sends and what graylog sends

**Comment by whiteud** [comment]
Request are the same, i sure (before create this issue i used Grafana 4 month and i not seeing those problem) . I have 10 graphs and all  after 3:00.

Standalone Grafana on preProd show all history, dashboard are the same

Probably really a problem in ES

**Comment by whiteud** [comment]
I check ElasticSearch, installed 2.4.1 version, but Elastic not have limits.
One think, ElasticSearch working in cluster mode for Graylog frontend, maybe this reason?
