### ISSUE TITLE
AlertRules: List shows orphaned alert rules (dashboard panel no loner has alert rule or dashboard does not exist)

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11224]
### What Grafana version are you using?
5.0.0
### What datasource are you using?
Influxdb
### What OS are you running grafana on?
Debian
### What did you do?
Added a dashboard with alert and then delete the dashboard
### What was the expected result?
Dashboard and alert should be deleted
### What happened instead?
Dashboard was deleted but Alert is still running

I have wrote about my problem in the community
https://community.grafana.com/t/alert-still-running-dashboard-deleted/6116

**Comment by flopp999** [comment]
any updates?

**Comment by marefr** [comment]
No similar reports for latest versions so I would guess whatever problem there was has been fixed.
