### ISSUE TITLE
URL param for "inactive mode"

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#11228]
We are using Grafana on Raspberry Pi driven monitors.

This works great, but animation and reflow is not so great due to lack of hardware power.

Now some of our TV dashboards are used in `?kiosk` mode, and all is fine with those.

But some dashboards are not using "kiosk" because the creator wants to keep the dashboard title and hence the Rpi has to animate the dashboard to go inactive.

We would prefer an URL param (e.g. `?inactive`) to start in inactive mode right away.

Would something like this work?
```diff
--- a/public/app/core/components/grafana_app.ts
+++ b/public/app/core/components/grafana_app.ts
@@ -117,6 +117,11 @@ export function grafanaAppDirective(playlistSrv, contextSrv, $timeout, $rootScop
           appEvents.emit('toggle-kiosk-mode');
         }
 
+        // check for inactive url param
+        if (data.params.inactive) {
+          appEvents.emit('toggle-sidemenu-hidden');
+        }
+
         // close all drops
         for (let drop of Drop.drops) {
           drop.destroy();
```

**Comment by bergquist** [comment]
Makes sense. Any chance you could submit a PR? Would also need to update the docs.

**Comment by dario-collavini** [comment]
Hi. This works well but I have an issue is using param '?inactive'.
It seems that the inactive status is maintained for like 1 minute (even moving the mouse), then after that period sidebars are restored when mouse is moved. Two things:
1) is it possible to always stay in tv mode? No just for 1 minute
2) The first minute tv mode is 'on', no zoom out/mark favourite/etc... button are displayed, but you can hover over a button and its label is displayed... Button function should be removed in this case

**Comment by towolf** [comment]
@dario-collavini my patch basically starts the dashboard already in inactive mode, with the sidebar hidden.

The only thing I wanted to achieve was to avoid the animation of hiding the sidebar later.

I did not even consider mouse activity, because our TVs do not have inpout devices attached.

To ignore mouse activity, I think more code is needed to make a kiosk mode + dashboard title.

**Comment by dario-collavini** [comment]
Thanks for the reply.
For our purposes, a mix of kiosk and tv mode would be helpful: the user must not navigate in different sections through the left sidebar or upper dashboard name, but needs to be able to change time intervals or refreshing times at his will, hence displaying just zoom out/ time interval buttons.
It would be nice to have it.
