### ISSUE TITLE
[Feature request] Alerting on Google Hangouts Chat

### ISSUE THREAD

**Issue by PatrickSchuster** [grafana/grafana#11221]
### What Grafana version are you using?
4.6.3
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu
 
Hi,
I'm trying to set up an alert using webhooks to a Google Chat / Hangouts chat room. I used the [official Google Chat documentation](https://developers.google.com/hangouts/chat/how-tos/webhooks) on setting up webhooks.

However, in Grafana there is currently no Google Chat type available in the alerting type dropdown list. I've tried using "webhook", but can't get past a "Webhook response status 400 Bad Request" error message. 

I think this is the case because there is currently no way to specify a custom HTTP message required by the Google Chat webhook?

So my question would be: Has anyone successfully set up a Google Chat alert configuration and could tell me how he/she get it to work?

Thank you!

**Comment by wbrauneis** [comment]
For the official JSON message format reference please refer to https://developers.google.com/hangouts/chat/reference/message-formats/

**Comment by bergquist** [comment]
Naitive support for this have to wait until we support backend plugins

**Comment by wbrauneis** [comment]
Adding the alert configuration for Hangouts Chat to the standard code base like the other configurations already available is not a viable solution?

**Comment by bergquist** [comment]
@wbrauneis only if its provided as a pull request and upvoted by the community. We don't want to support yet another API for a minority of our users.

**Comment by vainkop** [comment]
@PatrickSchuster did this work for you? https://developers.google.com/hangouts/chat/reference/message-formats/

If yes, can you share?

Thanks :)

**Comment by PatrickSchuster** [comment]
Hello everyone,
I implemented a Google Hangouts Chat notifier in my [pull request](https://github.com/grafana/grafana/pull/11410) using the official JSON message format (https://developers.google.com/hangouts/chat/reference/message-formats/).

A sample alert notification (without a graph screenshot) looks something like this:
![google_chat_grafana_alert](https://user-images.githubusercontent.com/3827255/38025225-dfcf4d0a-3287-11e8-95d7-b973844a6d7f.PNG)

**Comment by PatrickSchuster** [comment]
Hi @bergquist , 
I wanted to ask if you might have time to review my [pull request](https://github.com/grafana/grafana/pull/11410). There are a couple of upvotes on this issue as well as the pull request and it might be worth considering. :)
Thank you!

**Comment by n0guest** [comment]
+1

It would be great to have this feature.

**Comment by ondrejFuchs** [comment]
+1
It would be great to have this feature by Neuron Soundware.

**Comment by bill0k** [comment]
+1 aswell. 
Not a big change.

**Comment by xtroncode** [comment]
+1
this is needed

**Comment by cw-pratik** [comment]
+1
really need this

**Comment by sjernigan** [comment]
+1

**Comment by shanodj** [comment]
+1

**Comment by auntispam** [comment]
+1

**Comment by PcoWegenenVerkeer** [comment]
+1
We need this

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/11410
