### ISSUE TITLE
tooltip is broken on heatmap

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#11243]
![bucket](https://user-images.githubusercontent.com/291750/37404170-5f698802-2791-11e8-81d4-6a2523828c97.png)
On this view the tooltips are not working. No tooltip is shown when hovering the tiles.

**Comment by alexanderzobnin** [comment]
Did you enable it? Any errors in browser JS console?

**Comment by alexanderzobnin** [comment]
@roidelapluie ping

**Comment by bergquist** [comment]
@roidelapluie ping

**Comment by roidelapluie** [comment]
I will try to confirm if we go for heatmaps.
