### ISSUE TITLE
How can i show html code bellow attached picture???

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#11244]
![simplejson](https://user-images.githubusercontent.com/30747120/37404242-52ad003c-27b7-11e8-8ac7-7d7442240716.JPG)

particular basic auth  Details portion  hit to this page https://github.com/grafana/grafana/blob/master/public/app/features/plugins/partials/ds_edit.html

can you guide me how to debug this page..

Thanks!!!....

**Comment by bergquist** [comment]
What version of Grafana are you running? That does not look like a bundled datasource.

**Comment by vishuPPatel** [comment]
we are using 5.0 and  change the name and basic authentication & API but not get the code of the basic authentication.

I want to some changes in plugin(Simplejson).

Can you guide me where is code of the basic auth ??


Thanks!!!!....In Advance

**Comment by bergquist** [comment]
basic auth is implemented in each datasource plugin.
in SimpleJson is implemented here https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js#L14

Closing this issue since its not related bug/feature request for Grafana.

**Comment by vishuPPatel** [comment]
this is not error but can't find the basic auth..
Thanks @bergquist ...
