### ISSUE TITLE
Changing default datasource does not  seem to affect alerting engine

### ISSUE THREAD

**Issue by pavel-mutafchiev** [grafana/grafana#11253]
### What Grafana version are you using?
4.6.3
### What datasource are you using?
influxdb
### What OS are you running grafana on?
centos

We have two Influxdb instances (Influx1 is usually default) where multiple VMs report metrics with Telegraf replicating the metrics between the two databases. We have one Grafana instance which has both influxes configured as datasource. We have over a thousand alert rules related to various metrics coming from the VMs. All alerting dashboards are configured to get metrics from the default datasource.
 
We switched the default datasource to Influx2 as Influx1 had to be switched off for some maintenance. After confirming that all the panels were still being populated with data we switched Influx1 off expecting no alarms to be triggered.  Instead, all configured alarms that were configured to alert in case of execution error/timeout went into alerting state saying Connection Refused by Influx1 while all the graphs had no interruptions and were getting data from Influx2. 

Unfortunately I wasn't present during the time and I have no way to reproduce the issue again till the next time we need to turn off one or both of the influxes, which may take a while as this is a production environment.

**Comment by bergquist** [comment]
This is expected but frustrating. Should be fixed. 

Not sure how yet.

**Comment by flopp999** [comment]
We have same kind of error. We change database name in Grafana, still same database name in InfluxD, it results as with error same as @pavel-mutafchiev wrote
