### ISSUE TITLE
Change Grafana title on the login page

### ISSUE THREAD

**Issue by fmoreni** [grafana/grafana#11255]
Hi
I'm trying to change the grafana title name below the logo in the login page to some other name. can anyone help me out.
i'm using Grafana-5.0.1
thank you
![captura de tela 2018-03-14 as 21 31 10](https://user-images.githubusercontent.com/5358270/37438105-5a2db2da-27cf-11e8-894e-b006dd226aa8.png)

If it is necessary to compile, does anyone know which part of the code it is in?
Thanks

**Comment by bergquist** [comment]
Please ask questions on our community site [https://community.grafana.com/](https://community.grafana.com/)

We want issues on github to be about bugs and features requests.
