### ISSUE TITLE
Grafana 5: scrolling the panel does not work on touch devices

### ISSUE THREAD

**Issue by Trubochkin** [grafana/grafana#11259]
I already asked this question [here](https://community.grafana.com/t/grafana-5-overflow-scroll-doest-work-on-mobile/5480). I think it will not be superfluous. 

### What Grafana version are you using? 
 - v5.0.2;
### What datasource are you using?
 - It based on simple-json-datasource;
### What OS are you running grafana on?
 - Windows 10 Pro
### What did you do?
 - I need to have scrolling in my panel plugin on the touch devices ([link](https://community.grafana.com/t/grafana-5-overflow-scroll-doest-work-on-mobile/5480))
### What was the expected result?
 - read [here](https://community.grafana.com/t/grafana-5-overflow-scroll-doest-work-on-mobile/5480/10)
### What happened instead?
 - read [here](https://community.grafana.com/t/grafana-5-overflow-scroll-doest-work-on-mobile/5480/3)

**Comment by daniellee** [comment]
We are not using perfect scrollbar anymore so this seems to work now. 

Scrolling test dashboard here: https://play.grafana.org/d/Z0nO9goMz/scrolltest?orgId=1

I can re-open if this is still an issue.

**Comment by Trubochkin** [comment]
@daniellee, thanks! It works perfect
