### ISSUE TITLE
Support derivative aggregation units with Elasticsearch

### ISSUE THREAD

**Issue by LoadingZhang** [grafana/grafana#11256]
Grafana version: v5.0.0 (commit: af6e283)
Datasource: Elasticsearch 

In grafana, derivative will summing all results together when interval set big even if on avg value.
Such as derivative is 3 per minute, if interval set 5m, derivative will be 3*5=15.The result is not we want.
If can add [unit ](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-derivative-aggregation.html#_units)in es query, it would be help to solve this problem:

```
"derivative": {
"buckets_path": "price",
"unit": "minute"
}
```

**Comment by marefr** [comment]
Seems to be fixed so closing this.

![image](https://user-images.githubusercontent.com/1668778/50167091-a6771100-02e8-11e9-817e-3667f569c166.png)
