### ISSUE TITLE
When Ctrl-F on a long listing page, a browser not scrolling automatically to a found occurrence.

### ISSUE THREAD

**Issue by darkblaze69** [grafana/grafana#11252]
Grafana 5 / Windows 10 / Firefox 52.6 ESR and Chrome 65.
If doing Ctrl-F (I'm looking for a word) on a long listing page particularly Server Admin > Settings, the page not scrolling automatically to a first found word as expected. 'Find dialog' just shows a number of occurrences. But even arrows down/up dialog buttons not working in the 'Find dialog'. F3 is also useless to cycle through occurrences.

**Comment by Zhankin** [comment]
same problem, in the previous version (4.x) worked fine

**Comment by azhiltsov** [comment]
same here on Grafana-5.0.4 
Pages like "Data Sources", "Users", "Teams" just does not scroll to the found entry. 
Integrated "Filter by .." functionality works fine though

**Comment by torkelo** [comment]
related to the scroll component we use in v5, discussed here, https://github.com/grafana/grafana/search?q=scroll+&type=Issues&utf8=%E2%9C%93 we are investigating alternatives that will restore native behaviors

**Comment by daniellee** [comment]
Fixed by #11456
