### ISSUE TITLE
Unneeded scrollbar appears on legends of rendered graphs

### ISSUE THREAD

**Issue by friesoft** [grafana/grafana#11268]
### What Grafana version are you using?
5.0.2

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Red Hat 7.4

### What did you do?
Render one panel using share -> "Direct link rendered image". The graph has a legend as table to the right. The image contains the legend but with a scrollbar even though it wouldn't be needed (and isn't shown on the graph itself)

![icinga2-influxdb-hostalive](https://user-images.githubusercontent.com/124109/37489388-b787bd5e-2897-11e8-940b-ae41f3d6e42f.png)

### What was the expected result?
No scrollbar should be shown

### What happened instead?
Scrollbar is displayed in rendered image

**Comment by friesoft** [comment]
For comparison the same rendered image in an earlier 5.0 build (pre beta, shortly after the version number was increased from 4.6 to 5) before the new grid engine was built in.

OLD:
![grafana_5pre](https://user-images.githubusercontent.com/124109/37489745-e785ebe2-2898-11e8-9c4c-0f53ba74578f.png)

NEW:
![grafana_5 0 2](https://user-images.githubusercontent.com/124109/37489746-e7ef3a52-2898-11e8-977e-50c583188408.png)

Imho the old rendered grid contained slightly more information (more time/unit steps)

**Comment by daniellee** [comment]
Which browser are you using? The scrollbar showing looks like a bug.

We are not planning to do any more changes to the ticks algorithm on the x and y axis at the moment - there are so many edge cases and I think it works ok for most of them at the moment.

**Comment by friesoft** [comment]
The scrollbar appears no matter the browser (tried current version of Firefox and Chrome).

**Comment by stemilo** [comment]
Hi all,

I'm having the same problem with Grafana 5.4.3 (Firefox and Chrome). With the previous version (4.x) didn't find this issue. 
In particular, the scroll bar on the legend appears when I reduce the page zoom.

**Comment by nullpainter** [comment]
Same issue here. Appears to only be when there are several items in the legend.

Grafana 6.2.5, Chrome 76.0.3809.132  on Windows.

![image](https://user-images.githubusercontent.com/1732347/64566460-27f85d00-d3aa-11e9-8075-d2a54ee8d3fe.png)

**Comment by ivanahuckova** [comment]
/duplicate of https://github.com/grafana/grafana/issues/17147

Issue #17147 was closed as well as it seemed to only show in some edge cases when using browser zoom.
