### ISSUE TITLE
Modifying provisioned datasources that are marked as uneditable

### ISSUE THREAD

**Issue by kerams** [grafana/grafana#11262]
### What Grafana version are you using?
5.0.1
### What datasource are you using?
InfluxDB 1.5.0
### What OS are you running grafana on?
Windows Server 2016
### What did you do?
* Provisioned an InfluxDB datasource in a Yaml file and set `editable: false`.
* Opened the datasource in the UI and changed its Type in the dropdown
### What was the expected result?
The Save and Delete buttons should have remained disabled.
### What happened instead?
The Save and Delete buttons got enabled and allowed me to modify the datasource.

**Comment by bergquist** [comment]
This have been fixed in an recent release. Cant remember which one but its fixed.
