### ISSUE TITLE
Scoping of template variables in Row repeats

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#11263]
Please include this information:
* Grafana version 4.6.3 and 5.0.2
* InfluxDB

⚠️ Extensive use of the word "thing" incoming!

### What did you do?

1. Create a dashboard with 2 multi-value template variables, **thing** and **subthing**, both which get their value from a query. **subthing** gets its values based on what values are selected in **thing**, in other words the **thing** variable is used in the query for **subthing**.
2. Repeat rows for **thing**.
3. Repeat single stat panel in that row for **subthing**.

### What was the expected result?
I expected to get a row per **thing**, and in that a panel per **subthing** of that **thing**. A total of ```thing * subthing``` panels.

### What happened instead?
I got a row per thing, and a panel for all **subthings**, not just te **subthings** related to that **thing**. A total of ```thing * thing * subthing``` panels.

I learned form other issues in this repo that combining row and panel repeats is not 100% supported, but I would expect that if template variable b depends on variable a, and one repeats a row for each a, the values of b should be contained to the scope of a in that row.

**Comment by torkelo** [comment]
Nesting like this with repeated rows is not supported and will likely never be. Each row would have issue another query for subthing values, this is require to retry major change to the templating/variable engine

**Comment by coussej** [comment]
In understand. Thanks anyway!
