### ISSUE TITLE
Cannot store sessions in the password-protected REDIS

### ISSUE THREAD

**Issue by tral** [grafana/grafana#11266]
### What Grafana version are you using?
5.0.2
### What datasource are you using?
mysql
### What OS are you running grafana on?
debian
### What did you do?
trying to configure grafana for storing sessions in password-protectes instance of redis
### What was the expected result?
grafana understands "password" directive
### What happened instead?
grafana does not start

### Problem

If my redis-server is NOT password-protected, this connection string works fine:
```
provider_config = addr=127.0.0.1:6379,pool_size=100,prefix=grafana
```
but if I set password to "123" and modify connection string like that:
```
provider_config = addr=127.0.0.1:6379,pool_size=100,prefix=grafana,password=123
```
grafana just doesn't start at all.

Is it bug or I just use wrong directive "password"? Documentation tells nothing concerning this case.

**Comment by daniellee** [comment]
Don't see anything obviously wrong with the connection string. What error did you get in the Grafana server logs? Or were there any useful error messages in the console in your browser?

**Comment by tral** [comment]
I'm sorry, it works fine now. Please close this issue
(I'd only like to ask you adding "password" directive in documentation)

**Comment by tral** [comment]
And also please add db selection, for example this string:
```
provider_config = addr=127.0.0.1:6379,pool_size=100,prefix=grafana_sess_,password=pass,db=3
```
thank you!
