### ISSUE TITLE
Add tab-hopping to graphical query editors

### ISSUE THREAD

**Issue by iDemonix** [grafana/grafana#11276]
**Feature Request**

The new Graphite metric editor is great, but what'd be nice is if when I've finished typing the name of a metric (i.e. say the first part is `collectd`) that I could press tab and then jump to the next section and start typing immediately. At the moment I have to type `collectd` (or similar) then press tab to jump to another control, or click somewhere, then click the box next along, then I can start typing again.

Not sure how hard this would be to implement, but it'd be a really nice little time saver and would add to the keyboard shortcuts Grafana has nicely.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
