### ISSUE TITLE
Variable single-selection handling with Graphite

### ISSUE THREAD

**Issue by herver** [grafana/grafana#11274]
### Environment
Grafana version: 5.0.2
Datasource: Graphite  (0.9.16-2.el7)
OS: CentOS 7.4

### What did you do?
Use a variable in the following query:
`aliasByNode(sumSeriesWithWildcards(eos.$instance.versions.*, 1), 2)`

And then select only one value for $instance.
### What was the expected result?
Get some data back

### What happened instead?
No data is returned

### If related to metric query / data viz:
The query that is sent to the Graphite rendering endpoint is not formatted properly when only one value is selected in the variable drop down list:

 * Generated query:
`aliasByNode(sumSeriesWithWildcards(eos.{pps}.versions.*, 1), 2)`

 * Expected query: 
`aliasByNode(sumSeriesWithWildcards(eos.pps.versions.*, 1), 2)`

Note how the **expected** query doesn't have the curly braces...
 
Please let me know if you need more details !

**Comment by bergquist** [comment]
But that query should work the same way AFAIK.

**Comment by yiip87** [comment]
This was reported previously in #5936
I'm able to reproduce this issue with Grafana v5.3.4 (69630b9)

**Comment by hugohaggmark** [comment]
Closing this issue as I can't repro it on Grafana v7.4.0-pre (db637a3630) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
