### ISSUE TITLE
[Feature Request/ bug] Dashboard - (any)Plugin - Add Permission for 'Add to Panel List' for Viewers

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#11273]
Dashboard - (any)Plugin - Add Permission for 'Add to Panel List' for Viewers

Within a Dashboard, when clicking on any Panel Nam, a menu appears.  Select More and you will have several additional options appear.  Currently only Editors and Admins have an option for 'Add to Panel List'.  It would be useful for Viewers to have this option as well (or some other variation).

Why: In a large environment, it is useful to have several dashboards with examples that Users can view, but not edit (and break), having only Viewer permissions  These same users can also have other folders where they are Editors, and can build their own dashboards.  By providing the 'Add to Panel List' option where they have Viewer only access, allows them to find a panel that is built to their needs, and easily copy it into a dashboard they are building.

The alternative today is that they must view the Panel JSON, copy to clipboard, and then create a new Panel in their own dashboard (where they have Editor rights), and paste the JSON.  The new 'Add to Panel List' option makes this a much more elegant solution (since it is only there temporarily), and appears to be built just for this purpose, but the usefulness is limited as it is not available to Viewer permission users,.

What Grafana version are you using? v5.0.2
What datasource are you using? Elasticsearch
What OS are you running grafana on? CentOS7
What did you do? Select any panel's menu (on a Dashboard) - More - Add to Panel List
What was the expected result? Would like to 'Add to Panel List' option when for Viewer permission aswell
What happened instead? Add to Panel List is only available for Editor or Adminn

**Comment by bergquist** [comment]
You can get this behavior with the `viewers_can_edit` setting http://docs.grafana.org/installation/configuration/#viewers-can-edit
