### ISSUE TITLE
Bug with secret fields

### ISSUE THREAD

**Issue by xorsnn** [grafana/grafana#11270]
![grafana_bug](https://user-images.githubusercontent.com/10442030/37505789-aa14bcca-28f7-11e8-94dd-091c91137dba.gif)

grafana version: v5.0.1 (commit: a747ec3)
datasource: Prometheus
os: running oficial docker container on ubuntu 16.04

The following happens to all secret fields regardless of datasource 

to reproduce:
1) create new Prometheus datasource
2) check "With CA Cert"
3) type something to the sert input field
4) save the datasource
5) everything looks OK
6) without changing anything press save button for the SECOND time
7) I expect nothing to change, but i see visible end empty cert input field

**Comment by daniellee** [comment]
Thanks for the gif - wish all our bug reports looked like this!
