### ISSUE TITLE
Grafana 5.0.2 panics on startup if database URL has special characters in the password

### ISSUE THREAD

**Issue by zackelan** [grafana/grafana#11281]
Repro:

```
docker network create grafana

docker run --net=grafana --name postgres -p 5432:5432 -d \
  -e "POSTGRES_USER=grafana" \
  -e "POSTGRES_PASSWORD=sec{ret" \
  postgres:9.6

docker run --net=grafana --name grafana \
  -p 3000:3000 \
  -e "GF_DATABASE_TYPE=postgres" \
  -e "GF_DATABASE_URL=postgres://grafana:sec{ret@postgres:5432/grafana" \
  grafana/grafana:5.0.2
```

Results:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x843a0d]

goroutine 22 [running]:
github.com/grafana/grafana/pkg/setting.applyEnvVariableOverrides()
        /go/src/github.com/grafana/grafana/pkg/setting/setting.go:241 +0x5dd
github.com/grafana/grafana/pkg/setting.loadConfiguration(0xc42003ae68)
        /go/src/github.com/grafana/grafana/pkg/setting/setting.go:415 +0x34b
github.com/grafana/grafana/pkg/setting.NewConfigContext(0xc420028e68, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/setting/setting.go:473 +0x54
main.(*GrafanaServerImpl).initLogging(0xc4202adb80)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:107 +0xba
main.(*GrafanaServerImpl).Start(0xc4202adb80, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:56 +0x58
main.main.func2(0xc4202adb80)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:89 +0x2f
created by main.main
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:87 +0x2c5
```

Not a major bug, there are several workarounds - specifying the database config piecemeal instead of
using an env var, or percent-escaping the special character (in this case as %7B). However, this worked
under 4.5.2, and caused some head-scratching while testing our upgrade to 5.x. Ideally Grafana should
log a "hey, your password should be URL-escaped" error instead of panicking. A mention of this edge
case in http://docs.grafana.org/installation/configuration/#database would also be helpful.

**Comment by DanCech** [comment]
It looks like that character prevents https://golang.org/pkg/net/url/?m=all#Parse from being able to parse the url, and the code in https://github.com/grafana/grafana/blob/master/pkg/setting/setting.go#L239-L249 doesn't properly check that the `url.Parse` call succeeded before trying to use the `u` object.

**Comment by bergquist** [comment]
In this case `applyEnvVariableOverrides` should return a human-readable error and pass it all the way back to `.../grafana-server/server.go`
