### ISSUE TITLE
Row containing repeating panels doesn't update the count of hidden panels

### ISSUE THREAD

**Issue by cross** [grafana/grafana#11283]
Grafana master (5.1.0-pre), graphite datasource, linux

Given a dashboard that has a panel, then under that a a row containing a repeating version of the above panel, I notice that if the row is closed, the notation on the row saying "(N hidden panels)" does not update when I select a different number of values with the multi-select variable that is what the panel repeats on.  Once I open the row, the number of expected panels (based on the variable values) appear, and re-closing the row will now display the correct number of hidden panels.

Would it be possible to understand the change in number of panels hidden in a row without opening the row?

**Comment by bergquist** [comment]
This would be quite tricky to implement. Not sure its worth spending time on. 

Leaving this open for now but might close it unless we get a PR for it.

**Comment by hugohaggmark** [comment]
This is still the case in Grafana v7.4.0-pre (db637a3630). But as there is very little feedback or upvotes, I'm going to close this issue because we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
