### ISSUE TITLE
User Authentication & Groups & Roles

### ISSUE THREAD

**Issue by ikkaro** [grafana/grafana#1128]
Would be awesome a dashboard access control by groups, users or roles.

**Comment by jpbarron** [comment]
+1 Agreed.  Being able to filter what data was visible to a user using InfluxDB user account pass through might be an option for this.  Graphite doesn't have a user concept for access to specific metrics which is unfortunate.

**Comment by cjs226span** [comment]
+1

**Comment by delpass** [comment]
+1

**Comment by jaimegago** [comment]
+1

**Comment by shoonoise** [comment]
+1

**Comment by zsuzhengdu** [comment]
+1

**Comment by smalik03** [comment]
+1

**Comment by Foxeronie** [comment]
+1

**Comment by Ironchunk** [comment]
+1

**Comment by bergquist** [comment]
+1

**Comment by Guillaumichaud** [comment]
+1

**Comment by jmvitali** [comment]
+1

**Comment by alaurent1A** [comment]
+1

**Comment by hquestroy** [comment]
+1

**Comment by gundaswaraj** [comment]
+1

**Comment by aishuiyer2001** [comment]
+1

**Comment by saketh86** [comment]
+1

**Comment by gallesio** [comment]
+1

**Comment by idanz** [comment]
+1

**Comment by smeapng** [comment]
+1

**Comment by adigov** [comment]
+1

**Comment by ekarak** [comment]
+1

**Comment by tkuehne-deliveryhero** [comment]
+1

**Comment by maberle** [comment]
+1

**Comment by rmyhren** [comment]
+1

**Comment by xFRaNeRx** [comment]
+1

**Comment by phemmer** [comment]
Just throwing out a workaround which might be viable for others.
In our use case, we have a lot of users and several shared dashboards. We want people to have their own personal dashboards that they can tweak at will, but not be able to modify the shared dashboards, or pollute the org with a profusion of dashboards.

Users being able to register their own orgs helps with this, but we have several data sources, and this would require sharing the passwords to all the data sources, and require every user to set them up. And then when a data source configuration changes, every user will have to go and update their own copy.

The solution we implemented was to use database triggers. Basically whenever a new org is created, a database trigger copies all the data sources from the main org.
Also, when a data source in the main org is updated, if the copied data source hasn't been modified, the copy is updated with the same change.

For sqlite3 (the default), the triggers are:

```sql
CREATE TRIGGER org_insert_copy_main_org_data_sources AFTER INSERT ON org
FOR EACH ROW
BEGIN
	INSERT INTO data_source
		(org_id,version,type,name,access,url,password,user,database,basic_auth,basic_auth_user,basic_auth_password,is_default,json_data,created,updated,with_credentials)
		SELECT
			NEW.id,version,type,name,access,url,password,user,database,basic_auth,basic_auth_user,basic_auth_password,is_default,json_data,created,updated,with_credentials
		FROM data_source
		WHERE org_id=1
	;
END
;

CREATE TRIGGER data_source_main_org_update AFTER UPDATE ON data_source
FOR EACH ROW WHEN NEW.org_id=1
BEGIN
	UPDATE data_source
		SET
			version=NEW.version, type=NEW.type, name=NEW.name, access=NEW.access, url=NEW.url, password=NEW.password, user=NEW.user, database=NEW.database, basic_auth=NEW.basic_auth, basic_auth_user=NEW.basic_auth_user, basic_auth_password=NEW.basic_auth_password, json_data=NEW.json_data, updated=NEW.updated, with_credentials=NEW.with_credentials
		WHERE
			id!=NEW.id
			AND version=OLD.version AND type=OLD.type AND name=OLD.name AND access=OLD.access AND url=OLD.url AND password=OLD.password AND user=OLD.user AND database=OLD.database AND basic_auth=OLD.basic_auth AND basic_auth_user=OLD.basic_auth_user AND basic_auth_password=OLD.basic_auth_password AND json_data=OLD.json_data AND with_credentials=OLD.with_credentials
	;
END
;
```

**Comment by banjoh** [comment]
+999

Any plans here? Any support needed?

**Comment by daniellee** [comment]
Proposal for Dashboard Groups and a Permissions Model: https://github.com/grafana/grafana/issues/1611#issuecomment-287742633

**Comment by lunacite** [comment]
+1

**Comment by hsluoyz** [comment]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible and the logic can be altered at any time by modifying the model file.

I have seen the permission model in the proposal and I think it can be expressed by casbin. So I think we can consider using casbin when grafana implements access control security. So what do you think?

**Comment by tammytankian** [comment]
+1

**Comment by augray** [comment]
+1

**Comment by G-Geary** [comment]
+1

**Comment by lubyou** [comment]
+1

**Comment by mjtnajafi** [comment]
+1

**Comment by shamimgeek** [comment]
+1
