### ISSUE TITLE
Format numbers in Single Stats

### ISSUE THREAD

**Issue by adamzr** [grafana/grafana#11285]
In Single Stat panels numbers should be formatted with separators like 1,234,567. This will make the numbers easier to read.

**Comment by ryantxu** [comment]
You can do that already with `Units` > `None` > `Local Format`
![image](https://user-images.githubusercontent.com/705951/37661232-9d8e0fdc-2c54-11e8-9e0b-42b43cf03da6.png)

**Comment by adamzr** [comment]
@ryantxu I didn't know that. Thanks!
