### ISSUE TITLE
Use tab/labels from datasource response to enrich alerts.

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#11287]
Can we add some meta data / tags to the alerts created ? With that meta data, It will be easier to identify the type of alerts. ( Example : alerts for particular application, server, teams etc..)

This willl also helps to filter the alerts in alerts list panel. So that we can have single dashboard with multiple alerts list panel each for seperate purpose.

![image](https://user-images.githubusercontent.com/153843/37555759-7523cd24-29e4-11e8-9503-c3a06781c58b.png)

**Comment by yesoreyeram** [comment]
This is related to the issue https://github.com/grafana/grafana/issues/9174 but not similar.

**Comment by bergquist** [comment]
This is kinda tricky since Grafana doesn't understand the underlying data. Right now it only understands series names and numbers. But something like this would be great for datasources that have tag/labels so it would be easier to choose which tag/labels that might be interesting.

**Comment by yesoreyeram** [comment]
@bergquist instead tag from datasource respone, can't we have tags for the alerts created in grafana alert table itself? some thing like this.. 

![image](https://user-images.githubusercontent.com/153843/37653186-e403f78e-2c35-11e8-900b-d193bcc11ee6.png)

Just an idea. ( though this idea is not new; We are already having this for dashboards )

**Comment by bergquist** [comment]
That is kinda what https://github.com/grafana/grafana/pull/10989/files is trying to do :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
