### ISSUE TITLE
Provisioning Elasticsearch indexName not documented

### ISSUE THREAD

**Issue by AlbinoGeek** [grafana/grafana#11292]
### What Grafana version are you using?
- 5.0.2.linux-x64
### What datasource are you using?
- Elasticsearch
### What OS are you running grafana on?
- CentOS 7 x64
### What did you do?
- Follow the documentation linked at:
http://docs.grafana.org/administration/provisioning/

I have tried `index` and `indexName` at the top level, and in `jsonData` with no changes in result.
### What was the expected result?
- Information about Elasticsearch such as specifying `indexName`
### What happened instead?
- Every field except `indexName` works, so the datasource does not function
[https://i.imgur.com/QomZe3A.png](https://i.imgur.com/QomZe3A.png)

**Comment by AlbinoGeek** [comment]
It is not even something you can set in:
https://github.com/grafana/grafana/blob/3a1f52d8a2fdd1fd3b9bdbee05a48925bf8580f1/public/app/plugins/datasource/elasticsearch/config_ctrl.ts

Nor is it mentioned on the datasource page:
http://docs.grafana.org/features/datasources/elasticsearch/

**Comment by bergquist** [comment]
The Elastic datasource uses `database` to configure what index to use. This is completely lacking in the docs.
