### ISSUE TITLE
Grafana InfluxDB manipulatable Queries in Browser Development Tools

### ISSUE THREAD

**Issue by n3k232** [grafana/grafana#11294]
Hi,
i hope somebody can help me here,
i have noticed that you can see and maipulate every Query grafana is sending to the InfluxDB Backend, even if you use the Proxy mode on the Data-Adapter.I meanevery User can get every Datapoint from the Influx if he wants to. Maybe someone has a solution to hide these queries from the User.

I mean even if i build a Dashboard for pre-definhosts or Services the User can get the Data from Hosts or Services he shouldnt be able to see.

Please include this information:
### What Grafana version are you using?
5.0.0 Stable
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
SLES 12.3
### What did you do?
Building a Dashboards
### What was the expected result?
A Dashboards for for several People
### What happened instead?
Even if Dashboard is build for special Domains anyone can manipulate the Queries

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
https://icinga2-grafana.kamu.adm:3000/api/datasources/proxy/1/query?db=icinga&q=SHOW%20TAG%20VALUES%20WITH%20KEY%20%3D%20%22HOSTDISPLAYNAME%22%20where%20HOST%20%3D%20host_1234&epoch=ms

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/issues/6180#issuecomment-251389810
