### ISSUE TITLE
generic_oauth doesn't work with certain client secrets

### ISSUE THREAD

**Issue by senritsu** [grafana/grafana#11299]
Running Grafana 5.0.3 on Ubuntu 16.04 LTS

When configuring `generic_oauth` to interface with [Identity Server](http://identityserver.io/) we had a peculiar issue with the client config.

Certain client secrets do not work, and result in an "invalid client credentials" error from the IdP after consent when grafana tries to retrieve the token.

The issue seems to appear for client secrets that contain a trailing `=`, and for very long client secrets.

Using `foo` worked, `foo=` didn't.

Initially we used a crypto random string with 32 characters that had a trailing `=`, after removing the `=` it still didn't work. After clipping it to 8 characters it worked.

Similar secrets (32 characters, some with trailing `=`) worked for other client applications without issues.

**Comment by DanCech** [comment]
The provided client secret is passed directly to the official oauth2 library https://godoc.org/golang.org/x/oauth2 , it is possible that the config system is somehow mangling them.  Are you quoting the client secret in the config file?

**Comment by senritsu** [comment]
As far as I know we didn't quote it. 

Personally I didn't know the config system used even supported quotes, as the docs seem to only use literals and comments. I only entered the issue on our end in the latest stages of desperation, so I had no chance to dig into the docs very deep myself.

**Comment by bergquist** [comment]
You might have to wrap the password with three `"` to make it work. http://docs.grafana.org/installation/configuration/#password
