### ISSUE TITLE
[5.0.x] Unable to get a rendered image of graph-panel in a collapsed row

### ISSUE THREAD

**Issue by Ziars** [grafana/grafana#11296]
Greetings!

I've discovered a nasty bug with sharing panel functionality after upgrading from v.4.6.3 to v.5.0.x. This bug makes impossible to get a rendered image of a graph-panel in some cases.

How to reproduce:

1. Create a dashboard with a collapsed row, containing a graph-panel
2. Collapse the row
3. Save the dashboard
4. Expand the row
5. Try to get a rendered image of a graph-panel: "Share panel" -> "Link" -> "Direct link to rendered image"

Instead of displaying the rendered image, the attempt ends with a timeout:

> Grafana / Server Error
> Sadly something went wrong
> 
> Timeout error. You can set timeout in seconds with &timeout url parameter
> 
> Check the Grafana server logs for the detailed error message.

Here's what I get while trying to launch the command manually:

```
# /usr/share/grafana/tools/phantomjs/phantomjs --ignore-ssl-errors=true --web-security=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url='http://localhost:3000/d-solo/Cin6opguo/dashboard?refresh=1m&orgId=1&from=1521458576699&to=1521462176700&var-interval=%24__auto_interval_interval&var-env=production&var-host=somehost&var-host=somehost&var-host=somehost&var-http_error=All&panelId=59&width=1000&height=500&tz=UTC%2B03%3A00' width=1000 height=500 png=/path/to/grafana/data/png/nSQ7ZaRdxVooK4MZ7sKp.png domain=localhost timeout=60 renderKey=0jNOEE0jhPHvcSLSiv1TExX5TM5xsV0T
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Loading a web page: http://localhost:3000/d-solo/Cin6opguo/dashboard?refresh=1m&orgId=1&from=1521458576699&to=1521462176700&var-interval=%24__auto_interval_interval&var-env=production&var-host=somehost&var-host=somehost&var-host=somehost&var-http_error=All&panelId=59&width=1000&height=500&tz=UTC%2B03%3A00 status: success 60000
ERROR: null is not an object (evaluating 'e.panel')
http://localhost:3000/public/build/0.62c2e3e7aa607c7f2d09.js:15
TRACE:
 -> : 0 (in function "apply")

  phantomjs://code/render.js:48 in onError
```

Could you please investigate this issue?

Additional info:
  Grafana version: 5.0.3
  Datasource: Prometheus 2.2.0
  OS: Ubuntu 16.04

**Comment by ZhukovAlexey** [comment]
https://github.com/grafana/grafana/issues/11114#issuecomment-373668194

**Comment by daniellee** [comment]
Might be fixed in the master branch by https://github.com/grafana/grafana/pull/11282 if this is the same issue as #11114

**Comment by bergquist** [comment]
fixed by https://github.com/grafana/grafana/pull/11282
