### ISSUE TITLE
when use "order by time desc" why hover tooltip series and crosshair not match??

### ISSUE THREAD

**Issue by merturl** [grafana/grafana#11293]
### What Grafana version are you using?
5.0.3
### What datasource are you using?
Influxdb
### What OS are you running grafana on?
windows10 64bit
### What did you do?
i use order by time desc with limit 30

### What was the expected result?
i want get result "order by time limit 50 result"

### What happened instead?
I could get latestdata but crosshair and hover tooltip data is not matched problem

I've attached a screenshot.

<img width="892" alt="picture1" src="https://user-images.githubusercontent.com/23473356/37582982-a9fdccf2-2b92-11e8-8fdb-14455983fc37.PNG">

my cross hair pointed last point but tooltip and "a green border Highlighter"  pointed first point
this is bug?????

**Comment by marefr** [comment]
Think you'll need to order by ascending, please try that and close issue if that solves your problem.

**Comment by merturl** [comment]
thakn you for reply,
i try to use ascending,it is work very well but ascending is not need to me
but descend still hasn't worked,so i'm using offset instead of descend+limit

**Comment by torkelo** [comment]
Time series needs to be sorted in ascending time order
