### ISSUE TITLE
LDAP config is case sensitive

### ISSUE THREAD

**Issue by atommaki** [grafana/grafana#11300]
LDAP config (ldap.toml) is case sensitive in the distinguished names, where it shouldn't be.
This works for me:
```
group_dn = "CN=somegroup,OU=Groups,DC=company,DC=net"
```
But this doesn't:
```
group_dn = "CN=somegroup,OU=Groups,dc=company,dc=net"
```
(with an Active Driectory server if it matters)

Grafana version: 5.0.3 (current latest)
OS: CentOS 7.4

**Comment by belope** [comment]
Hello, don't know when, but this appears to be fixed at least in version 7.4 I have mixed case group_dn and it works.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by atommaki** [comment]
It's clearly a bug and not a feature request. However it may be fixed in the meantime (as @bolope said), I can't check it right now.
