### ISSUE TITLE
what is the use of Datasource - Provisioning(5.0)

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#11302]
Hello....Grafna Team 

Datasource - Provisioning start from (version 5.0) am i Right??

can you guide me what is the use of the Datasource - Provisioning in grafana??

what can doing we  for the Datasource - Provisioning in grafana??

Thanks!!!....

**Comment by bergquist** [comment]
You can find more info about provisioning in our docs http://docs.grafana.org/administration/provisioning/

Please ask questions on our community site [https://community.grafana.com/](https://community.grafana.com/)

We want issues on github to be about bugs and features requests.

**Comment by vishuPPatel** [comment]
@bergquist  i want to ask you just provisioning  it's some changes on grafana configuration file.

Is it right??

Thanks!!!...
