### ISSUE TITLE
Custom plugin based on official table plugin

### ISSUE THREAD

**Issue by CorentinDy** [grafana/grafana#11308]
### What Grafana version are you using?
5.0.0
### What datasource are you using?
influxdb
### What OS are you running grafana on?
docker/ubuntu
### What did you do?
I've duplicate the table plugin into the plugins (/var/lib/grafana/plugins) directory (and tried into the official plugins directory) but i've always the same error : 
```Fetch error: 404 Not Found Instantiating http://ip:port/public/app/plugins/panel/tableCustom/module Loading app/plugins/panel/tableCustom/module``` 
for the official directory plugins and 
```Fetch error: 404 Not Found Instantiating http://192.168.56.101:3000/public/app/plugins/panel/tableCustom/module.js Loading app/plugins/panel/tableCustom/module```
 for the plugins directory (/var/lib/grafana/plugins)
The plugin is writen in typescript so no js files.
I've made the id change in the plugin.json file.
### What was the expected result?
Get the official plugin working and let me try to modify the official plugin

**Comment by CorentinDy** [comment]
I've tried on windows and it's the same problem , the module.js file can't be found but it's a typescript plugin

**Comment by bergquist** [comment]
Core plugins are bundled in Grafana build process so they work a little bit different even thou they are using the same API. I suggest you look at https://github.com/briangann/grafana-datatable-panel instead to get started.

**Comment by CorentinDy** [comment]
So i can't build Grafana and edit the plugin manually by running `npm run watch` to compile it ? 
I really need to customize the official Table plugin from Grafana.

**Comment by daniellee** [comment]
@CorentinDy you can fork Grafana, edit the plugin manually and run npm run watch. If you want to create an **external** plugin then you have to handle the build yourself.

Here is an example of how someone extracted the Graph panel from the Grafana into its own repo (and handles the build with webpack):

https://github.com/CorpGlory/grafana-graph-panel
