### ISSUE TITLE
Edit panel position problem

### ISSUE THREAD

**Issue by Aysha94** [grafana/grafana#11304]
Hello
 
I'm using grafana version 5.0.3 with osipi data source on windows os .
When I try to add a new graph or any type of data representation, I get the edit panel moved up on top of the graph. in such a way it  hides the graph, instead of being down under the graph  

attachment shows what I mean
![edit panel](https://user-images.githubusercontent.com/36470909/37643522-b435126c-2c18-11e8-87c8-b08558886f06.PNG)

**Comment by marefr** [comment]
Please check/open an issue in the specific data source repository: https://github.com/GridProtectionAlliance/osisoftpi-grafana

**Comment by Aysha94** [comment]
The problem seems to be with the browser as it works fine with firefox while in internet explorer it doesn't.
Screenshots demonstrate the difference

**Edit panel (Firefox)**
![grafana_edit3](https://user-images.githubusercontent.com/36470909/38602680-f6b90b36-3d5a-11e8-8526-439d0560f1ce.PNG)

**Edit panel (Internet Explorer)**
![grafana_edit2](https://user-images.githubusercontent.com/36470909/38602695-04adc77c-3d5b-11e8-9f9c-bd8a0c605e55.PNG)

**Login page (FireFox)**
![grafana_login1](https://user-images.githubusercontent.com/36470909/38602791-48ea8a38-3d5b-11e8-884b-d40175e09741.PNG)

**Login page (Internet Explorer)**
![grafana_login2](https://user-images.githubusercontent.com/36470909/38602833-68a53a9e-3d5b-11e8-91a9-5a376f16bbe9.PNG)
