### ISSUE TITLE
Team membership based on LDAP groups

### ISSUE THREAD

**Issue by cubranic** [grafana/grafana#11301]
Grafana version: v5

In v5 and the new permission system, teams have become more useful than org-level roles as they allow us fine-grained control over dashboards in individual folders. However, they're not integrated into LDAP at all. It seems like it would be a useful feature to have, and could work very similarly to existing `group_mappings` configuration. E.g.:
```
[[servers.group_mappings]]
group_dn = "cn=ops,dc=example,dc=com"
team_name = "Operators"
```

**Comment by bergquist** [comment]
This is something we will work on eventually.

**Comment by VR6Pete** [comment]
Great to hear +1

**Comment by Pierre-Xavier** [comment]
This would be really cool and useful ! +1

**Comment by couloum** [comment]
Agree: would be great to have!

**Comment by lakshmi-github** [comment]
Definitely! +1

**Comment by dschade2016** [comment]
This would be realy realy nice!! ;) +1

**Comment by GianniMorini** [comment]
Agree, +1

**Comment by nilan3** [comment]
+1

**Comment by PhantomPhreak** [comment]
I'm waiting for this feature too!

**Comment by tomuk5** [comment]
+1

**Comment by tomuk5** [comment]
+1

**Comment by Mwilloughby1982** [comment]
+1 need this desperatly

**Comment by evaryont** [comment]
LDAP is nice, but will it support mapping groups sent via OAuth providers to teams? Specifically, I'm switching from LDAP authentication to OAuth powered by Keycloak.

**Comment by bmagistro** [comment]
@bergquist Has anything been started on this/is there something you guys have in mind for how this should look?  We would like to have this sooner and would consider helping with the development if we can but wanted to see if there were any thoughts about implementation first?

**Comment by torkelo** [comment]
@bmagistro 

Hi, yes we have started working on this. 

![image](https://user-images.githubusercontent.com/10999/46931808-02a18880-d04d-11e8-8bc4-3d3c8f3c1ee6.png)

We have made it possible to go into a team and there add one or more ldap groups to sync with. The sync only happens during login still. We also want to implement an active in the background sync (it's on the todo list). 

But it might disappoint you still as this feature is one of the first features we are doing as part of the Grafana Enterprise offering (commercial version of Grafana). We have reached a point where we need to make Grafana Enterprise more appealing other than including support & premium plugins. So the goal is to take a few features that only cater to the really large companies and make those part of the commercial code base. We have been successful in staying 100% OSS for almost 5 years with only a minor open core model with our premium plugins, this is a minor change in that strategy. One we will take step by step and listen to community feedback along the way. 

We will soon have an Enterprise build available for download & trials. It will also contain data source permissions.

**Comment by torkelo** [comment]
The first iteration on this will ship in Grafana v5.4 Enterprise (beta next week).

To read more on Grafana Enterprise: https://grafana.com/enterprise
Docs for the feature: http://docs.grafana.org/auth/enhanced_ldap/

Repeating what i wrote in the comment above: It might disappoint you that his feature is one of the first features we are doing as part of the Grafana Enterprise offering (commercial version of Grafana). We have reached a point where we need to make Grafana Enterprise more appealing other than including support & premium plugins. So the goal is to take a few features that only cater to the really large companies and make those part of the commercial code base. We have been successful in staying 100% OSS for almost 5 years with only a minor open core model with our premium plugins, this is a minor change in that strategy. One we will take step by step and listen to community feedback along the way.

**Comment by mattrussi** [comment]
Thanks for the transparency, @torkelo!

**Comment by NotAFile** [comment]
One thing I do worry about with this kind of strategy is that community pull requests for features that grafana labs plans to add to their enterprise offering will not be accepted as they conflict with grafana lab's business model. This is less of an issue if there is a plugin system in place that allows the community to replicate these features. But of course, this is not in the interest of Grafana Labs.

**Comment by wiad** [comment]
I too appreciate the transparency, but I wish that would extend to the pricing of Grafana Enterprise which seems to be so secret you have to share your contact information to get it. Which is something I reflexively refrain from doing since that typically results in endless emails/phone calls from sales persons. Not saying that is the case with Grafana Labs, but if you want to sell a product I wish you would be clear about the pricing.
