### ISSUE TITLE
Annotation List panel

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11323]
There is currently a built-in panel to show: `dashboards`, `plugins`, and `alerts`

It would be nice to have a supported way to list and navigate the (newish) built-in editable Annotations. 

I have started a custom panel, but it feels like something that could/should be a core feature.

![image](https://user-images.githubusercontent.com/705951/37689816-a383fff2-2ca7-11e8-93e7-8df76ab23fa1.png)

Clicking a row takes you to:

![image](https://user-images.githubusercontent.com/705951/37689892-fa7b60f2-2ca7-11e8-9821-3e8675cab79b.png)

See:
https://github.com/ryantxu/annotations-panel

Is there interest in doing this (soon) in grafana core?  Or should I keep it as a plugin?  (I'm fine either way)

**Comment by bergquist** [comment]
Something like this could be done with the table panel http://docs.grafana.org/features/panels/table_panel/#annotations

But that's per dashboard. Showing annotations based on tags would be more flexible. I'm no 100% sure about including it in core. I like it but might not be popular enough to be in core. But if you build it as a plugin we can always include it later. If that's ok with you?

**Comment by ryantxu** [comment]
I'll publish as a plugin and we can revisit later.  The more I look, the more complicated it gets :) in particular the difference between general datasource `Annotation Queries` and the builtin editable annotations from the `/api/annotations` endpoint.

**Comment by daniellee** [comment]
@torkelo I published Ryan's panel - the team should discuss if this should be included in core Grafana or if we would prefer to keep it as an external plugin.

**Comment by marefr** [comment]
I just used the plugin for investigating an annotation bug. Worked like a charm. I think we should include it in core.

**Comment by Dieterbe** [comment]
while i can't speak to the quality of this plugin or the burden of maintaining it, i will say that i've found Grafana's support for annotations currently rather rudimental (#17382 , #17379 )
annotations may not currently be a hugely popular feature but I think it's more to do with the support for it being still basic.
the concept of annotations should gain a lot more adoption if you ask me. Better UI support will help, and also better ways to create annotations (hence my side project https://github.com/raintank/memo ; i plan to start promoting memo and the idea of deployment tools auto-creating annotations more, hopefully this will make it a more commonly used feature. but let's discuss in a next eng meeting...)
