### ISSUE TITLE
Table panel shows an unnecessary overflow when last column is hidden

### ISSUE THREAD

**Issue by luarx** [grafana/grafana#11331]
### What Grafana version are you using?
5.0.3
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Debian
### What did you do?
Create a panel table with Prometheus data and **hide last** column.
### What was the expected result?
A table with Prometheus date without an unnecessary overflow.
### What happened instead?
A table with Prometheus date with an unnecessary overflow.

It happens because of **border** property increases the cell width.
![table_bug](https://user-images.githubusercontent.com/22997139/37729904-89b910ac-2d3e-11e8-8d6c-9482027bb981.PNG)

Last column has a **border-right: none** property. But if this column is hidden, the last column is another column that does not have this property. 
If I add **border-right: none** in the last visible column it works:
![bug_fixed](https://user-images.githubusercontent.com/22997139/37729944-a49c72f6-2d3e-11e8-8789-f327b0616c21.PNG)

**Comment by zoltanbedi** [comment]
Couldn't reproduce it in current master.
