### ISSUE TITLE
Escape key doesn't close time picker dialog [5.x]

### ISSUE THREAD

**Issue by eheydrick** [grafana/grafana#11332]
Selecting the time picker and then hitting escape without changing anything does not close the picker in 5.x. In 4.6 the picker is closed.

### What Grafana version are you using?

5.0.3

### What datasource are you using?

Any

### What OS are you running grafana on?

Linux

### What did you do?

1. Select time picker
2. Press escape

### What was the expected result?

The picker dialog should close

### What happened instead?

It did not close

**Comment by ryantxu** [comment]
related... and this keeps tripping me and some users up... in 4x you could close the picker by clicking anywhere not in the popup.  In 5x it stays open until you hit either 'apply' or the range button again.
