### ISSUE TITLE
Suggesting signing up for grafana.com on fresh Grafana installs. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11336]
When people install Grafana for the first time we want to suggest going to grafana.com/docs.grafana.org to learn more about Grafana. 

When introducing features like this is **very** important to not be too intrusive or interrupt current installs. To avoid that we need to detect if its a blank install or if someone configured it for certain usage.

We should avoid this if.
 * default admin password is not `admin`
 * there are any dashboards in the database.
 * there are any configured datasources

If any of those are true we should consider this Grafana install active and should, therefore, avoid showing this kind of information.

**Comment by roidelapluie** [comment]
yes?

**Comment by bergquist** [comment]
@roidelapluie sorry :) placeholder for myself. Rewriting this.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)
