### ISSUE TITLE
Create annotation with right-click, context-menu

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11340]
You can currently create an annotation by holding `ctrl` down while clicking on a graph panel.  This is a super useful feature, but feels kinda hidden and has required direct training with every user so far.

Rather than have right-click open the default image download context (that saves a blank image!), what about adding a context menu?  (i know this is often considered an anti-pattern, but it feels less secret then ctrl+click)

![image](https://user-images.githubusercontent.com/705951/37770045-651e1414-2dd3-11e8-9d6c-98c32d67e0a8.png)

Thoughts?  (FYI, i don't plan to work on this soon)

**Comment by torkelo** [comment]
I think adding a "add annotation" action in the panel dropdown menu would better, this action could either open the add annotation popup or just show a small modal that explains how you do it (with ctrl/cmd)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
