### ISSUE TITLE
Avoid variable interpolation by escaping $

### ISSUE THREAD

**Issue by dlanza1** [grafana/grafana#11359]
I have a query in Grafana for templating (against Influx) which has a tag which key contains the $ character.

How can I escape $ to avoid its interpolation with the variable?

Query: SHOW TAG VALUES FROM "exdemon-analysis" WITH KEY = "analyzed_metric.attributes.$owner"

"analyzed_metric.attributes.$owner" is the key, $owner should not be replaced.

**Comment by bergquist** [comment]
As long as you dont have a template variable named `$owner` nothing should be replaced.

**Comment by dlanza1** [comment]
Correct @bergquist , thanks for your answer!
