### ISSUE TITLE
No way to create rows in grafana 5.0

### ISSUE THREAD

**Issue by edio** [grafana/grafana#11355]
Please include this information:
### What Grafana version are you using?
5.0.3
### What datasource are you using?
irrelevant
### What OS are you running grafana on?
irrelevant
### What did you do?
tried creating new row in grafana
### What was the expected result?
there's a ui control to create new row
### What happened instead?
there's no control to create new row

I do understand that new layout engine does not require rows, but rows are still a valuable feature and a way to organize dashboards. There should be a way to group and collapse panels.

**Comment by Ashald** [comment]
IMO, the most valuable feature of rows is that they can be collapsed.

**Comment by marefr** [comment]
You find *Row* as a panel when clicking on Add Panel. Please ask questions on our community site.

**Comment by 1tgr** [comment]
"Click Start to shut down"
