### ISSUE TITLE
[Feature Request] missing "-+ Sizing" in 5.0

### ISSUE THREAD

**Issue by urbanb** [grafana/grafana#11353]
FR for  the "**-+**" back again in 5.0 , they really speed up creating dashboards.
![image](https://user-images.githubusercontent.com/12294952/37799458-06a5489c-2e20-11e8-89b2-2ad3a153cc1d.png)

Please include this information:

**Comment by torkelo** [comment]
All panels have small resize handles in lower right allowing for quick resize
