### ISSUE TITLE
If using 'http' protocol, setting 'cookie_secure' to 'true' should hard exit with an appropriate error message

### ISSUE THREAD

**Issue by jcmcken** [grafana/grafana#11350]
### What Grafana version are you using?

4.5.2

### What datasource are you using?

Not relevant (issue occurs on plain Grafana installation)

### What OS are you running grafana on?

CentOS 7.4 (but probably not relevant)

### What did you do?

Set up grafana using ``protocol = http`` under ``server``, and ``cookie_secure = true`` under ``session``.

### What was the expected result?

Some sort of runtime error advising that this configuration isn't supported. This is documented, but it should be a hard failure.

### What happened instead?

Instead of failing outright, it lets you do it, but you get varying degrees of weird problems:

* If using plain login, you get a "TOO_MANY_REDIRECTS" error (when using Chrome). 
* If using OAuth, the final redirect back to Grafana after OAuth authorization fails hard with a Go exception at [this line](https://github.com/grafana/grafana/blob/v4.5.2/pkg/api/login_oauth.go#L73). Grafana tries to read the session state ID, but it is ``nil``, and this fails the type hint.

In either case, there's no useful debug logging to understand what's failing (with ``level = debug`` and routing logging enabled).

**Comment by torkelo** [comment]
Note sure we can do that, many have reverse proxy in front of grafana that handles the SSL termination
