### ISSUE TITLE
Why http api create a dashboard not working.

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#11356]
### What Grafana version are you using?
4.6.2

### What datasource are you using?
influxdb

### What OS are you running grafana on?
ubuntu16.04

### What did you do?
first, export a dashboard.
second, import this dashboard with http api:
    POST /api/dashboards/db
then, the dashboard said:
    Datasource named ${DS_INFLUXDB-TELEGRAF} was not found

### What was the expected result?
    Can I autodetect the datasource name.
    Or, I have to modify all exported json file before import.

**Comment by marefr** [comment]
You cannot import an exported dashboard using the http api. You need to use http api to do a GET of a dashboard (alternatively show json of dashboard in UI and copy that) to get the dashboard json. Then use http://docs.grafana.org/http_api/dashboard/#create-update-dashboard
