### ISSUE TITLE
Default Datasource for variables

### ISSUE THREAD

**Issue by munokar** [grafana/grafana#11358]
Hello,

I was quite sure that in the past there was a possibility to use the default datasource in "Templating" by selecting default.
In Grafana 5 I have to select the datasource for my query but cannot select "default" like I can do for example in regular queries in panels.

Was that feature lost at some time?

Some of our dashboards where I was sure using something like default in the past are now looking like:

![grafik](https://user-images.githubusercontent.com/26091678/37817818-542c7ac4-2e78-11e8-8ad9-3dcd69336c88.png)

So datasource is "empty" but the interessting thing is that the variable is still working!

Regards
Timo

Please include this information:
### What Grafana version are you using?
5.0.3
### What datasource are you using?
Graphite
### What OS are you running grafana on?
RHEL 7.4
### What did you do?
Update from Grafana 4

**Comment by jedimt** [comment]
Also seeing this with 5.0.4 with a new install. The Data source is empty on every dashboard I have automatically imported through dashboard provisioning. 
![image](https://user-images.githubusercontent.com/10234760/38367858-c8c02ed8-38b1-11e8-848c-435045d2643c.png)
![image](https://user-images.githubusercontent.com/10234760/38367933-f51fd604-38b1-11e8-8ada-721613561d46.png)
![image](https://user-images.githubusercontent.com/10234760/38367945-feb815fa-38b1-11e8-8124-4df422f22c3d.png)

**Comment by marefr** [comment]
@jedimt that's not the same problem. Please note that you cannot use a dashboard json that have been exported thru dashboard -> share -> view/save json in provisioning. Provisioning dashboards require a dashboard json taken from dashboard -> settings -> view json or dashboard property returned from  HTTP api when doing a HTTP GET of a dashboard.

**Comment by jedimt** [comment]
OK, missed that in the documentation. Thanks for the clarification.

**Comment by hugohaggmark** [comment]
Sorry for this very late response, but it seems like the __`default`__  data source is no longer an option for Query Variables. I really don't know the details surrounding this decision so I'm going to close this bug for now. We can always reopen this issue if it gets more upvotes or feedback. 

Thank You to you for taking the time to create this issue!

**Comment by jakubgs** [comment]
The hell? Why would there not be a default option like in graphs? Every time I change the name of my default source it breaks all variable queries in all dashboards.

**Comment by Rohlik** [comment]
I think this https://github.com/grafana/grafana/pull/21495 is related to this problem or not?
