### ISSUE TITLE
[Feat] More information about folders/dashboards on manage dashboard page

### ISSUE THREAD

**Issue by vynjo** [grafana/grafana#11366]
Love the ability to manage, organize, dashboards in 5.x, but thought of the below would greatly benefit folks working in teams - one of our customers mentioned that with a large team, having quick access to modification date (along with owner, maybe last modified by) would really help when a large number of users are working collaboratively on dashboards. 

Maybe the feature is already there, and I missed it, if so, my apologies.

<img width="997" alt="screen shot 2018-03-23 at 9 13 31 am" src="https://user-images.githubusercontent.com/3148323/37831700-e3a404de-2e7c-11e8-848f-20d520170475.png">

Please include this information:
### What Grafana version are you using? 
5.0.1
### What datasource are you using?
IRONdb
### What OS are you running grafana on?
Ubuntu

**Comment by marefr** [comment]
This seems like a good thing to have. Thanks! We'll see if or when we decide to implement this. 

If you're interested in this feature please upvote the issue by adding a :+1: reaction to the top post. If a lot of people upvotes this we might consider it/prioritize it.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
