### ISSUE TITLE
add elasticsearch alerting

### ISSUE THREAD

**Issue by WPH95** [grafana/grafana#11368]
### feature
- base on 5.0.1
- No Third-party elasticsearch Golang SDK used
- Strictly follow the implementation of other datasouce code [mostly influxdb datasource]
- Control line of source code is around 1000 lines [no including test]
- Code logic strictly follow the implementation of  public/app/plugin/app/elasticsearch, e.g.
    - query.go  ->  query_builder.ts
    - response_parser.go -> elastic_response.ts

## CODING PHASE 1 [Finished]
- [x] parser Grafana internal elasticsearch query model -> model_parser.go
- [x] convert query model to elasticsearch search body -> query_builder.go
- [x] ElasticsearchExecutor -> elasticsarch.go
- [x] parser elasticsarch response -> response_parser.go [in process]

in this phase, I plan to unsupported 
- pipeline aggs [I haven't fully understood this part. =.=]

## CODING PHASE 2 [Finished]

- [x] get Series Name support
- [x] index list support interval (maybe import third part golang moment lib)
- [x] pipeline aggs support
- [x] some necessary tests

## CODING PHASE 3
- [ ] A full covering test suite exists.
    - [ ] test pipeline aggs response
- [ ] trim Datapoints support
- [ ] processAggregationDocs
- [ ] more clearly golang es model -> models.go

**Comment by bergquist** [comment]
How does this compare to https://github.com/grafana/grafana/pull/8934 ?

**Comment by WPH95** [comment]
hi @bergquist , i see roadmap delayed elasticsearch alerting, and #8943 look like hard to merge and no one to maintain, so I want to contribute to the community. and write a simple, clea, small pr :)

Although #8934 has been running steadily for a year in the production environment, but is difficult to merge into Master for some reason [https://github.com/grafana/grafana/pull/8934#issuecomment-363399208]

this pr solved most problems

i will finished CODING PHASE 1 in today [GMT+8] and plan to finished CODING PHASE 2 in this weekend

Finally, please forgive my English writing ability is not  good

**Comment by marefr** [comment]
I'm closing this since we already have an open feature request issue for elasticsearch alerting. Further discussions around PR will be discussed in PR.
