### ISSUE TITLE
Fracture display issues

### ISSUE THREAD

**Issue by Runamook** [grafana/grafana#11360]
### What Grafana version are you using?
grafana-5.0.3-1.x86_64
### What datasource are you using?
graphite 1.0.0-pre1
### What OS are you running grafana on?
Fedora release 25 (Twenty Five)

I have a graph, that displays metrics that generally have values less than 1 but with spikes to a hundred.
![image](https://user-images.githubusercontent.com/23465060/37820835-ed553b68-2e92-11e8-8605-20b11a03f1f0.png)

Log scale helps to deal with this in general:
![image](https://user-images.githubusercontent.com/23465060/37820855-ff0dadae-2e92-11e8-81f5-475ed2be1605.png)

I modify Axes -> Left-Y -> Decimals to 4, to have more precise axis: 
![image](https://user-images.githubusercontent.com/23465060/37820912-268c82c4-2e93-11e8-9590-abd6485a4819.png)

The issue is, when I hover over the graph, the toolip shows 0 unless I hover over the spike, or narrow down the timeframe so the spike is not selected:
![image](https://user-images.githubusercontent.com/23465060/37820971-5a8a2d38-2e93-11e8-86ec-a7228d551cf8.png)
![image](https://user-images.githubusercontent.com/23465060/37820976-60a0db18-2e93-11e8-81c7-3ad5da104f6f.png)

Is it possible to show fractions on a graph with a spike to hundreds?
To my mind that would perfectly complement log scale feature.

**Comment by marefr** [comment]
Please ask questions on the [community site](https://community.grafana.com/)! You find a similar decimals input field in the Legend tab to.

**Comment by Runamook** [comment]
Thank you
