### ISSUE TITLE
HTTP api always based on primary key 

### ISSUE THREAD

**Issue by pf23** [grafana/grafana#11362]
### What Grafana version are you using?
Grafana v5.0

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
CentOS 7

### What did you do?
Created a dashboard without `uid`. It is impossible to delete it via HTTP APIs because method `DELETE /api/dashboards/uid/:uid` is the only one to delete a dashboard and you must provide its `uid`.

Here are keys of table `dashboard`  with `id` being the primary key and `uid` being a normal one. 

| Field | Type  |   Null |    Key    |
|:----:|:------:|:-----:|:--------:|
| id  |  bigint(20)| NO |   PRI   |
| uid | varchar(40) | YES |  |

To avoid any above situation, my suggestion is that most HTTP APIs support methods based on primary key or a non-repeatable  key, under which the only way to operate the dashboard is to modify database directly.

**Comment by bergquist** [comment]
How did you create the dashboard without UID? That should not be possible. 

UID should not be nullable. I guess we forgot to make it not nullable in the migration.

**Comment by marefr** [comment]
So the only way of deleting a dashboard before introducing *uid* was by slug :smile:

**Comment by torkelo** [comment]
If you create a dashboard without uid, the response json Will contain the generated uid , think we can close this

**Comment by pf23** [comment]
Sorry I am not sure how and when I created those dashboard without uids. For now I can't replicate the situation of creating ruined dashboard. Below are more details I can recall.

 I upgraded Grafana from v4.0.3 to v5.0.0, deleted and created batchs of dashboards using scripts by calling HTTP APIs, and finally found some ruined dashboards. 

Chrome Console Inspect shows front-end called "http://grafana5.wacai.info/api/search?folderIds=0&query=&starred=false" when I clicked `Home`, and the response contains some seemingly ruined dashboards with uid being "", for example,
```json
{
    "id": 2744,
    "uid": "",
    "title": "cn.fudata/eureka-service",
    "uri": "db/cn-fudata-eureka-service",
    "url": "/d//cn-fudata-eureka-service",
    "type": "dash-db",
    "tags": [
      "cn.fudata"
    ],
    "isStarred": false
  },
}
```
Clicking them returns `404 not found` directly , and no url was requested by front-end.

When I tried to delete them. I found no API based on `id` to delete the dashboard. So I was wondering if someone else met similar issue. To delete those dashboards, finally I directly deleted them by `id` from database. Guess the data structure is ruined somehow (probably when upgrading).

**Comment by torkelo** [comment]
that is super strange, creating a dashboard with empty uid should not be possible

**Comment by marefr** [comment]
Could it be same problem as in #11186?

**Comment by pf23** [comment]
@marefr Quiet similar. I am using InfluxDB, upgrading Grafana from v4.0.3 to v5.0.0.

**Comment by marefr** [comment]
@pf23 I meant your Grafana configuration database, sqlite (default), mysql or postgres?

**Comment by pf23** [comment]
@marefr I am using mysql as configuration database.

**Comment by marefr** [comment]
@pf23 what mysql version? 

If you execute the following statement:
```sql
UPDATE dashboard SET uid=lpad(id,9,'0') WHERE uid IS NULL
```

Does that "fix" your dashboards not having a uid? The above statement should have been executed as a migration step.

**Comment by pf23** [comment]
Yeah, It works. Did not realize that I should execute the statement after migration. Much appreciated! @marefr.

**Comment by marefr** [comment]
@pf23 Glad that helped. in normal cases you should not need to execute this manually, Grafana should automatically in the database migration step. We have an open issue #11090 that hopefully will make the migration logic better of handling errors etc.

**Comment by dmitrios** [comment]
While specifying uid as varchar(40) is fine in JSON extract, it does not seem to be editable as field in the UI. Having validation verify that this value is indeed unique would help to reduce possible duplicates on edit before doing the export.

**Comment by marefr** [comment]
@dmitrios It should be editable in UI since #1429 was resolved (targeted to be included in v5.2 release)

**Comment by dmitrios** [comment]
@marefr : #1429 seems to be JSON editing in grafana. However, since uid needs to be checked against dups, it should be shown in dashboard "Save As" dialog. Obviously did field should be validated to inform user that it is indeed unique.

**Comment by marefr** [comment]
@dmitrios It will be checked when you save and you'll get an overwrite warning if a dashboard is going to be overwritten.

**Comment by dmitrios** [comment]
Good enough. Thx!
