### ISSUE TITLE
[bug] Wrong decimal format on rendered snapshot PNG

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#11372]
### What Grafana version are you using?
` Grafana v5.0.3 (commit: 91162f3)`

### What datasource are you using?
`InfluxDB`

### What OS are you running grafana on?
`CentOS`

### What did you do?

I would like to create snapshots from my graphs to PNG files. I'm using the local format for units with `0` decimal value in the `Legends` and the `Left Y` fields also. 

Nonetheless the format of the average numbers on the rendered PNG files is not integer.

### What was the expected result?

If I set the `0` decimal value for `Legends` and `Left Y` field also, then the rendered PNG snapshot let it be the same format.

![2018-03-24 20-03-29](https://user-images.githubusercontent.com/2911588/37868275-03a19c88-2fa4-11e8-9186-ebfd04d81ef1.png)

**Comment by Ramalama2** [comment]
Will this ever e fixed?

**Comment by torkelo** [comment]
looks to be fixed https://play.grafana.org/render/d-solo/omhnF9hGk/png-legend?orgId=1&from=1605007380079&to=1605028980079&panelId=2&width=1000&height=500&tz=Europe%2FStockholm
