### ISSUE TITLE
Can't render Dashboard PNG after upgrading to 5.0.3

### ISSUE THREAD

**Issue by Natalique** [grafana/grafana#11374]
Hi, 
When working with Grafana 4.3.2 i can render a png file for the whole dashboard (not just 1 panel) by accessing 
 <IP>:<PORT>/render/dashboard/db/<DASHBOARD_NAME>
I tried to do the same with version 5.0.3 but i keep getting a timeout error 
Also tried accessing <IP>:<PORT>/render/d/<DASHBOARD_UID>/<DASHBOARD_NAME>
As I saw that there were changes in the url in 5.0.x 
I keep getting the same error. Even when increasing timeout to 30000 

My panels are not collapsed 

I can access a single panel  on <IP>:<PORT>/render/d-solo/<DASHBOARD_UID>/<DASHBOARD_NAME>?panelId=11
But i want to render the full dashboard in 1 image as I did in 4.3.2v 

Please include this information:
### What Grafana version are you using?
5.0.3
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Official Docker image
### What did you do?
I tried to access rendered image of a dashboard on - <IP>:<PORT>/render/d/<DASHBOARD_UID>/<DASHBOARD_NAME>
### What was the expected result?
Get the PNG 
### What happened instead?
Time out message - Timeout error. You can set timeout in seconds with &timeout url parameter

 
Thanks!

**Comment by artiatoisa** [comment]
+1

**Comment by ryantxu** [comment]
FFIW, in #8363 @torkelo said rendering whole dashboards is not supported

**Comment by torkelo** [comment]
not officially at least (it's more like a hidden api hack at the moment)

**Comment by Natalique** [comment]
Thanks. 
Will v5.0.x support this in the future? 
Most of our dashboards are sent using this "hack"

**Comment by ofershany** [comment]
+1

**Comment by ittaiyam** [comment]
+1

**Comment by austinbutler** [comment]
Getting this too, even with single panels.

**Comment by alexeyYakovlev1982** [comment]
+1

**Comment by Natalique** [comment]
By the way this works in grafana v5.0.0
You can see in grafana play even - (now i had to adjust the height, otherwise it cuts off the dashboard after the first two panels, which doesn't happen in grafana v4.x)

http://play.grafana.org/render/dashboard/db/4-years-of-grafana?orgId=1&width=1800&height=900&from=1522735337553&to=1522756937553&var-servers=All

**Comment by artiatoisa** [comment]
I think it’s very important to have auto choose of height. Because there’s cases with value of height which depend on repetitive rows and panels.

**Comment by torkelo** [comment]
seems to work here, http://play.grafana.org/render/dashboard/db/4-years-of-grafana?orgId=1&width=1800&height=900&from=1522735337553&to=1522756937553&var-servers=All

Not sure why there is a timeout in your case, you need height and width in url
