### ISSUE TITLE
FR: Persisted playlist (and playlist url)

### ISSUE THREAD

**Issue by nickman** [grafana/grafana#1137]
Our Grafana dashboards are becoming quite popular with our Ops groups. I would like to be able to define different play lists, categorized by arbitrary subject areas so each group can play the dashboards relevant to them.

**Comment by tabacco** [comment]
This would be fantastic. We like to use Grafana on TVs in the office, and it's a pain to have to re-set-up the playlist whenever the raspberry pi the browser is running on gets rebooted.

**Comment by savingschampion** [comment]
^ Exactly that use case here too, This is for our business team who can just about turn on an Iphone :smile:

**Comment by AkoyaP6618** [comment]
We use Grafana for application monitoring and want to create a playlist for each application. It would be awesome to create a playlist once and edit/use it everytime you want.
I am looking forward to add a list of playlists to the home-dashboard :smile:
:+1:

**Comment by utkarshcmu** [comment]
PR submitted in #3582

**Comment by utkarshcmu** [comment]
@bergquist : Keeping track of playlist issues here:

#377
#791
#1116

**Comment by utkarshcmu** [comment]
@bergquist Do you think the UI is somewhat better and implicit now for the playlist feature in playlist branch? Please let me know if there needs any improvement in the UI. Thanks.

**Comment by bergquist** [comment]
I'm currently working on some UX improvements. 

Some other things that I think should be included before merging to master. 
* Deleted dashboard should be remove from playlist
* reorder dashboard order in playlist

After that I think it's ready for master.

**Comment by nikita-graf** [comment]
Looks better! I'm going to implement 1st feature from list. How do you think reorder should work? Drag'n'drop?

**Comment by bergquist** [comment]
I think it would be fine to use arrows for moving dashboards up and down the list. Drag'n'drop would be nice but not required.

**Comment by nikita-graf** [comment]
Ok, let's use arrows. I'll have time today-tomorrow to add them.
