### ISSUE TITLE
Alerts - Customize when to send notifications (example: ignore no-data notifications)

### ISSUE THREAD

**Issue by nmat** [grafana/grafana#11378]
Please include this information:
### What Grafana version are you using?
5.0.3

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Ubuntu 16.04.4 LTS

### What did you do?
Setup alert for graph to send alerts to microsoft teams

### What was the expected result?
Ability to say what type of alert should send information to teams

### What happened instead?
Every alert is sent even no-data alerts.

**Comment by bergquist** [comment]
If you set `no data` to `Keep Last State` there won't be any state changes/alert notifications.

Otherwise, this has to wait until https://github.com/grafana/grafana/issues/5856 is implemented.
