### ISSUE TITLE
Grafana 5.x no row title hide option

### ISSUE THREAD

**Issue by DirtyCajunRice** [grafana/grafana#11373]
Please include this information:
### What Grafana version are you using?
5.0.3

 There is no longer an option to hide row title, leaving a row with an "Empty" title as a huge bulky empty space between rows

**Comment by torkelo** [comment]
The row needs to be visible as that is the only way way can show the row option menu. If you do not want to see the row title you can remove the row completely, rows are not needed for layouts in v5.0

**Comment by DirtyCajunRice** [comment]
I would love to just remove the rows but without rows moving a single item
moves EVERYTHING ruining the entire layout

**Comment by torkelo** [comment]
What? Moving a panel does not change the layout of other panels. Can you record a video to show what you mean?

**Comment by DirtyCajunRice** [comment]
Absolutely. I’ll record it in the morning

**Comment by hellhond** [comment]
@torkelo another use case for hiding the row title: https://community.grafana.com/t/grafana-5-how-to-hide-colapse-panel/4707/10

We use the row repeat feature, and thus cannot remove the row by itself.

It's probably not a common use, but wanted to comment on it anyway.

**Comment by stevenh** [comment]
I agree with OP, v5 does eat a lot more vertical space than before so it would be nice to see an option to auto hide row headers or use the jump out vertical ... as per v4. 

The inactive mode would definitely help but it feels like the pop out as seen here in v4 solved the problem very elegantly.
![image](https://user-images.githubusercontent.com/104239/41349309-694177f0-6f07-11e8-9c20-236554e937f0.png)
![image](https://user-images.githubusercontent.com/104239/41349348-892e529a-6f07-11e8-8810-677df4783edf.png)

Here's an example, which shows the wasted vertical space in v5 vs v4.
**Version 4 Layout**
![image](https://user-images.githubusercontent.com/104239/41348795-b55fea56-6f05-11e8-90e3-4b88673664ee.png)
**Version 5 Layout**
![image](https://user-images.githubusercontent.com/104239/41348880-f3e6508a-6f05-11e8-9b4a-3448996f9869.png)

**Comment by torkelo** [comment]
yes, but you do not need rows in v5 for layout, only to segregate big sections on big dashboards which is why we think having row titles always there ok (And fixes the huge bad UX issue of having the barely visible row menu icon)

**Comment by ppx17** [comment]
But you need rows if you want to use the repeat for $var on a row right? We have a dashboard with a row of the same graphs, repeated for every server in the system that is being displayed on a TV. The row repeat option makes it zero-effort to add new servers, and we have a text block at the start of each row identifying the server with a large font so you can also read it from a distance without losing vertical space. However the row header then becomes quite large, costing about 80 pixels per row.

![row-spacing-grafana](https://user-images.githubusercontent.com/1229068/42167548-af27d4c4-7e0e-11e8-99f4-8be6a47de36f.png)

**Comment by lekobob** [comment]
I agree on this issue as well.  I found that you can now repeat the panels in a row with a variable as well but you are still left with the row header taking up vertical space.  Frankly I have no use for that label.

**Comment by KevinSeminara** [comment]
Hopefully a way to implement hiding row headers can be found and not introduce bad UX issues. Or at least hiding them in inactive mode would certainly help.

**Comment by pieroxy** [comment]
We heavily uses repeated rows that contain a horizontally repeated panel so that we have repetition in both directions. v5 made all our dashboards 50% taller than previously and they don't fit on a single screen anymore. Please do something !!

**Comment by marefr** [comment]
@pieroxy Please try out the new experimental feature for [autofit panels to optimize space on current tv/monitor](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#new-experimental-features).

**Comment by andyl** [comment]
I'm also having a problem with this.  

Would it be possible to add an option to run a dashboard in "V4 Mode"?  The V4-style controls solved our needs perfectly.
