### ISSUE TITLE
Inconsistent behaviour in image uploader to S3

### ISSUE THREAD

**Issue by dene14** [grafana/grafana#11385]
### What Grafana version are you using?
4.6.3, official docker image
### What datasource are you using?
n/a
### What OS are you running grafana on?
Linux

### What did you do?
Configuring external image storage on S3 bucket.

```
[external_image_storage.s3]
path = "/upload"
bucket = "bucket.example.com"
```

Resulting in upload path `s3://bucket.example.com/upload/VdKnktoG9NmunLpzXPNL.png` whereas publication URL will include doubled slash in the URL: `https://s3.amazonaws.com/bucket.example.com//images/VdKnktoG9NmunLpzXPNL.png`

The issue rather minor and easily reproducible. Happens due to difference in path normalization in 2 different places:
1. Upload path
2. Resulting public link to an image

Please note: AWS S3 counts every `/` as nested object, so basically it's allowed to have multiple consecutive slashes in path and they will be taken as nested objects by S3. Thus it's better to add some note about leading slash and don't do any special path normalization.

**Comment by marefr** [comment]
As this bug is 3 years old, and no one else seems to be facing this issue, I'm going to close this. If this is still something that's happening to you; feel free to comment and we can consider re-open this issue.
