### ISSUE TITLE
How to update grafana.ini with http api?

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#11389]
Just get the settings, how to set the settings?

Please include this information:
### What Grafana version are you using?
4.6.2

### What datasource are you using?
influxdb

### What OS are you running grafana on?
ubuntu14.04/16.04

### What did you do?
update grafana configuration with http api.

**Comment by bergquist** [comment]
you mean reload or update values?

**Comment by crazy-canux** [comment]
Just like how to make auth.anonymous from false to true with http api?
And how to config smtp parameters with http api?

**Comment by bergquist** [comment]
That's not possible. You can only change `grafana.ini` from the file itself.

**Comment by crazy-canux** [comment]
Why we don't have this feature?
For automation it's necessary.
Http api is better than modify the configuration file itself.

Thanks!
