### ISSUE TITLE
Reduce panel header height when title is absent - Grafana 5.0.3

### ISSUE THREAD

**Issue by YehonatanVonage** [grafana/grafana#11394]
Hi,
I'm one of the developers of the grafana status panel:
https://grafana.com/plugins/vonage-status-panel

I encountered a UI issue in the status panel in Grafana 5.0.3. When there is no panel title, the header height takes some of the height of the panel (27px), and makes the data in the panel to be lower. When there are a lot of panels in the same window, it doesn't look good.

Can you reduce the panel header height to 10px in case there is no title?

Here is sample of the panel in Grafana 4.6.2:
![screen shot 2018-03-27 at 12 14 37 pm](https://user-images.githubusercontent.com/18004951/37958228-9fc61178-31b8-11e8-9402-0b4bacbab65d.png)

and the same one in Grafana 5.0.3:
![screen shot 2018-03-27 at 12 14 09 pm](https://user-images.githubusercontent.com/18004951/37958233-a30bc918-31b8-11e8-82ba-24f38d7094c9.png)

Thanks

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
