### ISSUE TITLE
How to create multiple dashboard using dashboard provisioning?

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#11397]
Hello…Grafana Team I want to create multiple dashboard using dashboard provisioning

in here doc just this

apiVersion: 1

providers:

name: ‘default’
orgId: 1
folder: ‘’
type: file
disableDeletion: false
editable: false
options:
path: /var/lib/grafana/dashboards
we are using simple-jsone datasbes plugin that’s iwant to ask you how to create more about into dashboard provisioning

can you guide me how to create the multiple dashboard??

Thanks!!!..

**Comment by bergquist** [comment]
Please ask questions on our community site [https://community.grafana.com/](https://community.grafana.com/)

We want issues on github to be about bugs and features requests.

I will update the docs about provisioning to explain it in more details
