### ISSUE TITLE
Broken time conversion in column type Date for PostgreSQL data source

### ISSUE THREAD

**Issue by niku64** [grafana/grafana#11404]
### What Grafana version are you using?
grafana-5.0.3
### What datasource are you using?
PostgreSQL
### What OS are you running grafana on?
Gentoo
### What did you do?
I have configured an SQL query with `$__time(thing_created_at)` which was translated to `thing_created_at as time`, then set a column type to `Date` in column styles.
### What was the expected result?
In grafana-4.6.3 the resulting string in the time column was the same as `to_char(thing_created_at, 'YYYY-MM-DD HH:mm:ss') as time`.
### What happened instead?
Time column shows `1970-01-18 hh:mm:ss` instead of `2017-03-27 hh:mm:ss`.

**Comment by marefr** [comment]
Should be fixed in #11306. Will be included in v5.1 release.
