### ISSUE TITLE
Auto Adjusting Panel Height 

### ISSUE THREAD

**Issue by Krylon360** [grafana/grafana#1141]
@torkelo would it be possible to have the panels resize themselves based on either the Browser Window Size; or Screen Size?
I ask because in my env; I build our dev teams performance dashboards using 3 24" Dell LED displays; and my MBP 15"Retina ( hopefully a 27" TB Display next quarter ). 

On my 24's I can have 3 rows, 2 panels per row; with Legend enabled on each panel; and it will fill the screen without scrolling (depending on how many values the legend has).

I was just issued a 52" LG LED TV due to noticing that when walking to some of the dev team areas where they have their dashboards on a screen anywhere from 42" - 80" the layout is jacked. Jacked as in where what is a full layout on my 24", on their TV's it's only taking up half the screen.

Does that make sense at all? 
I'd imagine this could be done through _ or a JQ function (though I think JQ needs an event to fire off before it will do the resize() event)

Let me know if you need me to take a snapshot of the TV Display (I'll have to take a photo of it; I doubt you want a 52" Screenshot. heh)

**Comment by the-invoice** [comment]
What if you add relative row height option? E.g. row height = 0.25 * view port height. With #2623 it will make nice looking auto adjusting dashboards (width of panels already adjusting automatically). And there no need in second render pass.

**Comment by pdf** [comment]
You could alternatively look at just doing some flexbox layout, which is (pardon the pun) quite flexible for these sorts of layout issues.

**Comment by tal** [comment]
We're also using it to put things on TV screens frequently and would love to be able to set a viewport to a screen forcing every element to be contained within it. Alternately if there's any way to build a plugin or greesemonkey script to do the same that'd be good.

Thanks

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Comment by datlaphani** [comment]
Any suggestions on how to get this implemented? This will be very helpful feature for our executives who display dashboards on 70inch TV.

**Comment by jamesbradlee** [comment]
Please re-open.

<img width="2402" height="854" alt="Image" src="https://github.com/user-attachments/assets/27167651-804c-4452-98cf-b5c3a9f8edcd" />

Please… We need to see…

If I resize the panel to support many series like the following:

<img width="1571" height="2279" alt="Image" src="https://github.com/user-attachments/assets/d32adf16-d7b6-4824-bf20-2e01dab659b3" />

Then when I change the variables to something that only has 8 series, it takes up so much more space than necessary that it actually becomes harder to orient around:

<img width="1571" height="2275" alt="Image" src="https://github.com/user-attachments/assets/cb7f3958-4b69-4d3f-85ab-5d83469ac724" />

Support for auto adjusting panel heights would make the user experience all the better. Please 🙏
