### ISSUE TITLE
Query-editor create a gap between real and visual position of the cursor if there are ligatures

### ISSUE THREAD

**Issue by clement-lefevre** [grafana/grafana#11420]
Please include this information:
### What Grafana version are you using?
Latest (5.0.3)
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Debian and/or Docker
### What did you do?
Just used the Query editor
### What was the expected result?
No graphical glitch
### What happened instead?
There's a gap between cursor real position and where user see it

You can run through https://bugzilla.mozilla.org/show_bug.cgi?id=1447923 as I initially reported the bug as a Firefox one. We investigated and went through, but Grafana seems to be the source of the biggest part of the issue as it created its own custom form field for the query editor and assume cursor position.

Read first comments of the above-mentioned bug is probably better, but to summarize: the font Firefox is using is making automatic ligatures, and for every ligatures character, there's an increasing gap between where the cursor really is and where user is seeing it. This makes the query editor really really painful to use.

**Comment by torkelo** [comment]
Closing this as it appears to affect no one else
