### ISSUE TITLE
[bug] Can't create Data Source via localhost

### ISSUE THREAD

**Issue by Piknik1990** [grafana/grafana#11424]
- What Grafana version are you using?
grafana-5.0.3-1.x86_64.rpm
- What datasource are you using?
prometheus-2.2.1.linux-amd64
- What OS are you running grafana on?
CentOS 7.4 
- What did you do?
I tried to create Data Source for the Prometheus on http://localhost:9090/ 
- What was the expected result?
I would like install on the one server Prometheus and Grafana and to connect Grafana with Prometheus via localhost:9090 port and close the 9090 port in firewall for outside.
- What happened instead?
Changes to saved, connect-test is failed, I don't have text of test result, Granafa tried send requiest to localhost:9090 via MY browser, I saw metrics in the Prometheus web-interfase, but can't saw they in Grafana daskboard. If I tried introduce outside IP in URL - all is fine.

![grafana - mozilla firefox 2018-03-28 18 42 37](https://user-images.githubusercontent.com/28757514/38041676-0ffb94ec-32bb-11e8-9864-51d967854975.png)

**Comment by marefr** [comment]
Please change Access to proxy. Closing this for now. Consider re-opening it if proxy doesn't work.
