### ISSUE TITLE
Provide nightly builds for Windows

### ISSUE THREAD

**Issue by turt2live** [grafana/grafana#11426]
The build instructions for Windows on the website appear to be missing: https://grafana.com/grafana/download/5.1.0-13334pre1?platform=windows

I'm also having some major issues trying to build `master` on Windows, so that might be related somehow.

**Comment by ryantxu** [comment]
FYI, you can get latest windows builds from:

https://ci.appveyor.com/project/Torkeldegaard/grafana/build/artifacts

**Comment by turt2live** [comment]
@ryantxu thanks! I'm still a bit curious as to why grafana.com doesn't have the builds available though. In fact, it looks like all the 5.x nightly builds are missing Windows artifacts.

**Comment by bergquist** [comment]
seems like this is missing in the appveoyer configuration. We are currently investigating how to cross compile grafana so we might build the windows version on windows as well.

**Comment by xlson** [comment]
As @bergquist mentioned we are currently reworking our builds and will make sure nightlies for windows is available again when that is finished.

**Comment by xlson** [comment]
This was fixed in 5.2.
