### ISSUE TITLE
row menu: insert row

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#1142]
Adding rows to the top of a complex dashboard is a bit cumbersome. It would be nice to be able to insert a row before or after an existing row without having to move one up from the bottom.

**Comment by utkarshcmu** [comment]
<img width="901" alt="screen shot 2015-10-09 at 3 36 24 am" src="https://cloud.githubusercontent.com/assets/1019609/10381283/0bc80d9c-6e37-11e5-82ba-0eb701bd4839.png">

@torkelo - If this UI looks ok, I can work on the PR. It should be quick.

**Comment by bob454522** [comment]
hi,  was this feature removed?  (the one in the screen shot)?  i cant seem to find it in v7.2.0  (logged in as admin).

I was searching for this exact functionality, as we often have several panels at the very top of a dashboard (thus NOT in any row),  and then several rows below those "top, non-row'd panels".
Whenever we go to add a new row (via "add panel"->"convert to row") , it is inserted at the very top, and thus captures all of our panels at the top (so we have to move everyone of the panels out of the new row, and back to the very top)

The feature pictured above would solve our issue.
thank you! 
(LOVE grafana!)
