### ISSUE TITLE
Format request

### ISSUE THREAD

**Issue by tehdirector** [grafana/grafana#1143]
I've noticed a few comments about having more format types. With the "singlestat" panel I think this is a something that is needed more than ever. I know there are too many different formats to "can" each of them into a selectable format but could you allow formatting of the numbers with regex or something similar.

My use case in particular is for currency but could apply outside the currency format. I am able to use the prefix for the appropriate "$" but when the numbers get over 100k it would be nice to have thousands separators so I can print $ 14,560,338.56 instead of $ 14560338.56 and easily determine the number from a distance.

Thoughts? And thank you for Grafana! this has saved me more than you will ever know!

**Comment by torkelo** [comment]
Fixed with the decimal precision override 
https://github.com/grafana/grafana/issues/1253#issuecomment-78561547

**Comment by FooBarWidget** [comment]
I'd also like to see thousands separators. I am tracking a metric that is growing very slowly, but it is over a million, so having thousands separators is more useful than the short format.

**Comment by mkeagar** [comment]
+1 for thousands separators. We have some count metrics that we want to display the exact number for that get into the hundreds of thousands and millions.

**Comment by nurriz** [comment]
+1 for the thousands separator. When you get singlestat panels that go into the billions, readability takes a dive.

**Comment by jhorowitz** [comment]
+1 for thousands separator

**Comment by adamklein** [comment]
+1

**Comment by jhorowitz** [comment]
If someone could direct me to the area of the codebase I should be looking at, I'd be happy to make a PR. After that I'd love to continue contributing. @torkelo

**Comment by schneyra** [comment]
+1
