### ISSUE TITLE
Dashboard links don't open the correct dashboard

### ISSUE THREAD

**Issue by Francesco-Cocchioni** [grafana/grafana#11432]
### What Grafana version are you using?
5.0.3
### What datasource are you using?
Bug not related to datasource
### What OS are you running grafana on?
Debian 9
### What did you do?
Click on a dashboard link
### What was the expected result?
Open the correct page
### What happened instead?
Open another page

Hello,

i'm having problems with the "Dashboard Links"; I'm referring to the links available under "Dashboard Settings" -> "Links".

Suppose i have 3 dashboard named: "1) DASHBOARD1", "2) DASHBOARD2", "3) DASHBOARD3" all with the same tag named "TAG".

In each dashboard i have configured the "Dashboard Links" as:

Type: dashboards
With tags: TAG
As dropdown: Checked
Title: TITLE
Time Range: Checked
Variable values: Checked
Open in new tab: Not Checked

The link of each dashboard showed in the dropdown menu (top right) is:

http://MY_IP/dashboard/db/1-DASHBOARD1i?from=1503597600000&to=1504202400000
http://MY_IP/dashboard/db/2-DASHBOARD2?from=1503597600000&to=1504202400000
http://MY_IP/dashboard/db/3-DASHBOARD3?from=1503597600000&to=1504202400000

while the link of each dashboard in the main navigation menu (top left) is:

http://MY_IP/d/UNIQUE_ID1/1-DASHBOARD1
http://MY_IP/d/UNIQUE_ID2/2-DASHBOARD2
http://MY_IP/d/UNIQUE_ID2/3-DASHBOARD3

When i click on the dashboard for opening "2) DASHBOARD2" the system instead open "1) DASHBOARD1"; The link:

http://MY_IP/dashboard/db/2-DASHBOARD2?from=1503597600000&to=1504202400000

bring me to "1) DASHBOARD1". 

Using the main navigation menu link:

http://MY_IP/d/UNIQUE_ID2/2-DASHBOARD2

bring me to correctly to "2) DASHBOARD2".

There is a bug on how "Dashboard Links" maps, inside the database, the page name to the actual page to load; maybe the dashboard links should have the id in the path like in the main navigation menu to avoid this problem.

"2) DASHBOARD2" was created as a copy of "1) DASHBOARD1", using the save as functionality on "1) DASHBOARD1".

Sometimes also "Dashboard Links" return ad error saying that the dashboard has not been found.

**Comment by torkelo** [comment]
this sounds very strange, we have not updated the urls yet for dashboard links, but they should still work as old links should redirect to new url. 

so if you open

http://MY_IP/dashboard/db/2-DASHBOARD2?from=1503597600000&to=1504202400000

What url does it redirect to? your saying it redirects to 

http://MY_IP/d/UNIQUE_ID1/1-DASHBOARD1

that should be impossible, as it will use the slug `2-DASHBOARD2` to look up the unique id. 

I replicated your scenario on play site, unable to replicate what you describe. Works perfectly there.

http://play.grafana.org/d/O9BPcomik/z-dash2?from=now-6h&to=now&orgId=1

**Comment by Francesco-Cocchioni** [comment]
I was just able to replicate the "Dashboard Not Found" error; i think that both the wrong redirection and the "Dashboard Not Found" are related to the same problem. In the previous post i forgot to specify that this problem occurs with dashboards which have the same name and tag in different organization, and that after a while the problem seems to solve by itself. By the way bellow the step i just used to recreate the "Dashboard Not Found" error.

1) Create two organization, ORG1 and ORG2;
2) Create inside ORG 1 two dashboard called "1) DASHBOARD1" and "2) DASHBOARD2", both with the same tag named "TAG" and the dashboard link configured as follow:

- Type: dashboards
- With tags: TAG
- As dropdown: Checked
- Title: DASH LINK
- Time Range: Checked
- Variable values: Checked
- Open in new tab: Not Checked

3) Go to both "1) DASHBOARD1" and "2) DASHBOARD2" and export their JSON removing their "uid" field;
4) Go to ORG2 and import the JSON of "1) DASHBOARD1" and then "2) DASHBOARD2", keeping the same names;
5) Clicking on the dashboard link for "1) DASHBOARD1" inside "2) DASHBOARD2" give the "Dashboard Not Found" error. The same occurs if you try to click the link for "2) DASHBOARD2" inside "1) DASHBOARD1".

Attached you can find some images proving the problem. As you can see from "Dashboard Link.png" inside "2) DASHBOARD2" there is a dashboard link for "1) DASHBOARD1"  with the following path:

http://192.168.1.61/dashboard/db/1-dashboard1?from=now-6h&to=now

After clicking this link the "Dashboard Not Found" error appears, with Grafana trying to open the page with ID "rbVoBTiik" (image "Dashboad Not Found.png"). If you open the main navigation menu i see that the id associated to "1) DASHBOARD1" inside "ORG2" is "j2lBomiz" (image "Main Navigation Menu.png"). So the dashboard link resolve the name "1-dashboard1" to the wrong id; by the way "rbVoBTiik" is the id associated to "1) DASHBOARD1" inside "ORG1".

![dashboard link](https://user-images.githubusercontent.com/3011259/38408161-9c77327e-397c-11e8-9336-77fe24162f0b.png)
![dashboard not found](https://user-images.githubusercontent.com/3011259/38408162-9c91ea06-397c-11e8-8987-8795ea956f98.png)
![main navigation menu](https://user-images.githubusercontent.com/3011259/38408163-9cac22c2-397c-11e8-94e2-d675b125f85b.png)

**Comment by marefr** [comment]
@Francesco-Cocchioni thanks for your detailed description. I've followed all your steps and cannot reproduce your problem. I'm on latest master commit  (5.1-pre), but not sure that should matter. If you want/can please try the nightly build and see if you can reproduce it.

The only way I can somehow replicate your behavior is if I try to load one of the dashboards by new url (/d/.../slug) and change the orgId querystring parameter to the other organization id and try to load that page.

**Comment by Francesco-Cocchioni** [comment]
Hello,

here the additional info requested; i recreated the problem with a new dashboard called "3) DASHBOARD3" inside "ORG1".

As before, the ID returned by the database ("QD9dTymmk") belong the the "3) DASHBOARD3" inside the other specular organization ("ORG2"), and not the current organization where the dashboard link is clicked ("ORG1").

Unfortunately i can't try any nightly build.

For the log i used the following settings inside grafana.ini:

[server]
router_logging = true

[database]
log_queries = true

[log]
level = Debug

![dash link](https://user-images.githubusercontent.com/3011259/38488957-4665f850-3be5-11e8-8769-a8ffeb3816db.png)

![not found](https://user-images.githubusercontent.com/3011259/38488972-4f0a373c-3be5-11e8-9051-131049bb4c03.png)

![main menu](https://user-images.githubusercontent.com/3011259/38488977-51f04158-3be5-11e8-9e9f-537d4e7820d5.png)

![network tool 1](https://user-images.githubusercontent.com/3011259/38488980-54eb4eca-3be5-11e8-9f9b-ac6005a26e83.png)

![network tool 2](https://user-images.githubusercontent.com/3011259/38488981-551346c8-3be5-11e8-8c67-6f45a7aa3697.png)

![network tool 3](https://user-images.githubusercontent.com/3011259/38488982-554f7a62-3be5-11e8-96cf-f84ad417b9e9.png)

[Log.txt](https://github.com/grafana/grafana/files/1889140/Log.txt)

**Comment by torkelo** [comment]
unable to replicate this, are you sure you are not having an open tab and changing org or loading another orgs url in an seperate page then going back to the other tab? Grafana does not support using two orgs at the same time (per user/browser).

**Comment by Francesco-Cocchioni** [comment]
Yes i am.

As you can see from the image i have only one tab open, and i have also only one instance of Chrome opened.

Is there something else i can do to help?

**Comment by torkelo** [comment]
Hi, 

I found the cause for this. It's the browser that caches the 301 redirect, since the url is the same in the two orgs the redirect from the other org will be reused. 

We will fix this by adding the orgId to the redirect. (also update so the links are correct in the first place). 

1) temp work around is to change to the links to do not open in new tab, that way the redirect will be handled in the frontend (so should not have this effect).

**Comment by marefr** [comment]
There's already an open issue for fixing the links here #10705
