### ISSUE TITLE
SystemJS no longer adds cache busting parameter.  Breaks plugin upgrades

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11446]
In a recent release of a plugin, i changed the path to an html file and a couple people are seeing 404s.  After investigating, it looks like caching issues in production mode.

https://github.com/NatelEnergy/grafana-discrete-panel/issues/46

I don't know if there is a good solution.  It looks like the some files get a version appended to the end to bust the cache, but the javascript files do not.

**Comment by torkelo** [comment]
strange, both the html loader cache buster and the system js cache buster are still in place and unchanged.

https://github.com/grafana/grafana/blob/v5.0.3/public/app/app.ts#L85

https://github.com/grafana/grafana/blob/v5.0.3/public/app/features/plugins/plugin_loader.ts#L52

**Comment by torkelo** [comment]
maybe the systemjs cache buster hack has stopped working in recent version of systemjs?

**Comment by ryantxu** [comment]
Another report for a different plugin:
https://github.com/ryantxu/ajax-panel/issues/6

yes, the systemjs cache buster isn't busting :(

**Comment by torkelo** [comment]
my guess is that it's systemjs cache busting hack that has stopped working, 
https://github.com/grafana/grafana/blob/master/public/app/features/plugins/plugin_loader.ts#L53

**Comment by ryantxu** [comment]
Yes, the cacheBust method grafana uses does not work in SystemJS 0.20 😢  

I tried the method suggested here: https://github.com/systemjs/systemjs/issues/172#issuecomment-278565952
```
const cacheBust = '?bust=' + Date.now();
let resolve = System[System.constructor.resolve];
System[System.constructor.resolve] = function (key, parentKey) {
  return resolve.call(this, key, parentKey).then(function (resolved) {
    return resolved + cacheBust;
  });
};
```

This correctly adds the cacheBust url, but the loaded plugin gets a error:
```
Plugin component error Error: Cannot read property 'load' of undefined
  Instantiating http://localhost:3000/public/plugins/natel-discrete-panel/module.js?bust=1525683568611
  Loading plugins/natel-discrete-panel/module
    at :3000/public/build/0.44653aeda45a818a7862.js:4058
```

**Comment by ryantxu** [comment]
I found a solution that works, but it quite ugly.

This only applies the cacheBusting to `public/plugins` since the rest are bundled with webpack.
```
// add cache busting
// Hacky solution for SystemJS 0.20 from:
// https://github.com/systemjs/systemjs/issues/1616#issuecomment-289268010
// SystemJSLoader$1 -> RegisterLoader$1 -> Loader
var Loader = System.__proto__.__proto__.__proto__.constructor;
var loaderResolve = Loader.prototype.resolve;
var metadataSymbol;
function getMetadataSymbol(loader, mustFindKey) {
  if (metadataSymbol) {
    return metadataSymbol;
  }
  if (loader["@@metadata"]) {
    //some browsers dont support Symbol()
    return metadataSymbol = "@@metadata";
  }
  var symbols = Object.getOwnPropertySymbols(loader);
  for (var i = 0; i < symbols.length; i++) {
    var s = symbols[i], lov = loader[s];
    if (lov && typeof lov === 'object' && lov[mustFindKey]) {
      return metadataSymbol = s;
    }
  }
  throw new Error("I tried: "+mustFindKey);
}

const cacheBust = '?bust=' + Date.now();
Loader.prototype.resolve = function hackedLoaderResolve() {
  const loader = this;
  return Promise
    .resolve(loaderResolve.apply(loader, arguments))
    .then(function (key) {
      // Only manipulate external plugins
      if (key.indexOf('public/plugins/')>0) {
        const newKey = key + cacheBust;
        const metaSymbol = getMetadataSymbol(loader, key);
        const metadata = loader[metaSymbol];
        const moveMe = metadata[key];
        if (moveMe) {
          delete metadata[key];
          metadata[newKey] = moveMe;
        }
        key = newKey;
      }
      return key;
    });
};
```

Perhaps there is a better solution in more recent SystemJS?  (0.21.3)

**Comment by marefr** [comment]
@davkal could you take a look at this?

**Comment by githubSiYao** [comment]
> I found a solution that works, but it quite ugly.
> 
> This only applies the cacheBusting to `public/plugins` since the rest are bundled with webpack.
> 
> ```
> // add cache busting
> // Hacky solution for SystemJS 0.20 from:
> // https://github.com/systemjs/systemjs/issues/1616#issuecomment-289268010
> // SystemJSLoader$1 -> RegisterLoader$1 -> Loader
> var Loader = System.__proto__.__proto__.__proto__.constructor;
> var loaderResolve = Loader.prototype.resolve;
> var metadataSymbol;
> function getMetadataSymbol(loader, mustFindKey) {
>   if (metadataSymbol) {
>     return metadataSymbol;
>   }
>   if (loader["@@metadata"]) {
>     //some browsers dont support Symbol()
>     return metadataSymbol = "@@metadata";
>   }
>   var symbols = Object.getOwnPropertySymbols(loader);
>   for (var i = 0; i < symbols.length; i++) {
>     var s = symbols[i], lov = loader[s];
>     if (lov && typeof lov === 'object' && lov[mustFindKey]) {
>       return metadataSymbol = s;
>     }
>   }
>   throw new Error("I tried: "+mustFindKey);
> }
> 
> const cacheBust = '?bust=' + Date.now();
> Loader.prototype.resolve = function hackedLoaderResolve() {
>   const loader = this;
>   return Promise
>     .resolve(loaderResolve.apply(loader, arguments))
>     .then(function (key) {
>       // Only manipulate external plugins
>       if (key.indexOf('public/plugins/')>0) {
>         const newKey = key + cacheBust;
>         const metaSymbol = getMetadataSymbol(loader, key);
>         const metadata = loader[metaSymbol];
>         const moveMe = metadata[key];
>         if (moveMe) {
>           delete metadata[key];
>           metadata[newKey] = moveMe;
>         }
>         key = newKey;
>       }
>       return key;
>     });
> };
> ```
> 
> Perhaps there is a better solution in more recent SystemJS? (0.21.3)

Thank you very much.I've soluted my question.
