### ISSUE TITLE
Enhancement Request- Gridding / Alignment of Chart Areas

### ISSUE THREAD

**Issue by incansvl** [grafana/grafana#11447]
Grafana: 5.0.3
Grafana host: Windows 7 Pro, 64 bit
MySQL server: Maria DB 10.2, Debian Jessie 64 bit

**Enhancement Request**

The Grafana dashboard drawing tools work by aligning the bounding box / outer edge of each panel (at least in the horizontal direction) to a layout grid. This makes it easy to get a tidy-looking dashboard layout set up quickly.

However, the internal layout of panels is largely automatic, based on the contents. There is the ability to set a minimum width on the Legend (if it exists), but other than that it's a "black box" process. This means that when multiple charts are stacked, the actual chart areas (e.g. where the time series are drawn) may not align, if (for example) the space taken up by the axis labels differs between the charts.

See below for an example. I've deliberately made this extreme by removing the legend from one chart, but in practice differences in charts like, say, having a difference in the number format on axis labels will lead to minor misalignment, which is in some ways more disconcerting.

This is especially true when using the "Shared crosshair" or "Shared tooltip" option, which sees the crosshair "bending" as it is moved across the charts

![grafana chart alignment](https://user-images.githubusercontent.com/28898330/38149244-c3056aee-3451-11e8-9a8f-632bd99c5709.png)

I realise this could be a challenging problem to solve. Some initial thoughts on how this could be handled are-

1. Have an alternative layout mode that works "chart area out" rather than "panel area in". In this mode the user would drag the corners of the chart area to align with the grid, and the layout logic would then "shrink wrap" the axis labels, legend, title etc. around the chart body. Note this could lead to inconsistent panel sizes misaligned to the grid unless the panel widths were "rounded up" to the next available gridding point (i.e. adding empty padding space within the panel to make it fit the grid).

2. Keep the panel layout UI the same as today, but allow the chart area to be dragged (reduced in size only), maybe against a finer "sub grid" than the panels themselves, to allow multiple charts to be properly aligned.

**Comment by torkelo** [comment]
just layout our panels with similar display settings (legend below). or with legend to the right, use the custom width option to set a custom width (this requires all graphs below to also use legend to the right) 

What your requesting is not really feasible.

**Comment by incansvl** [comment]
Re:
> use the custom width option to set a custom width (for the legend)

I did try that early on. It can make things a bit better, but ultimately it's a fudge because-

1. A fixed-width legend on one chart doesn't scale in the same way as the other (auto-width) legends when the browser width is changed. For this to work in general one would need the ability to set the legend width as a multiple of the "1/12 browser width" horizontal gridding units, instead of in pixels.

2. You'll still have problems with (say) different number formats on the axis labels taking up differing amounts of space.

I do accept (as I said in the original post) that this is a tricky thing to solve in the UI. However in terms of producing "production quality" dashboards these things make a difference. If it's not going to be possible to handle this interactively, would it be possible to provide some help for tweaking the layouts via CSS? e.g.-

- A "custom CSS" field at the edit-dashboard and edit-panel levels.
- Some documentation on the css structure used in the default style.

**Comment by torkelo** [comment]
It’s not possible  to solve with css (to my knowledge)

The fixed width legend of course needs to be applied to all graphs and be the same.
