### ISSUE TITLE
Total the current value 

### ISSUE THREAD

**Issue by premvectone** [grafana/grafana#11444]
Hello I have installed Telegraf, InfluxDB and Grafana to Monitor Network Statistics. 

And I have added my 5 switch with custom OID value and its giving the exact value

Now I want to calculate the total value of **current value**

I tried to do that but it showing overall total value for every switch instead of that I need to calculate the current value of all 5 switch. 

Previously I have used cacti to get the total count. Now I want to use grafana
![total](https://user-images.githubusercontent.com/37932454/38138705-c97c68f4-341b-11e8-873d-1c505a58dfec.png)

**Comment by torkelo** [comment]
Use a singlestat panel and calculate the total in your influxdb query.

**Comment by premvectone** [comment]
Thank you. Can you please let me know how to send report for every 1 hours of my graph
