### ISSUE TITLE
Repeated SingleStat panel with variable All option doesn't handle missing values when prefix is filled

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/grafana#11441]
Resembles #6595 a bit
Please include this information:
### What Grafana version are you using?
5.0.4
### What datasource are you using?
grafana-zabbix 3.9.0 (Zabbix 2.4.6)
### What OS are you running grafana on?
Centos 7
### What did you do?
- Setup SingleStat panel with repeat on variable $ssk_id. 
- Entered variable $ssk_id as value prefix:
![image](https://user-images.githubusercontent.com/14870891/38132668-a8b5e250-3414-11e8-8d33-b8d9f109bc12.png)
- Applied value map value to text: null -> Н/Д
![image](https://user-images.githubusercontent.com/14870891/38132729-fec60f76-3414-11e8-8c38-08ed5d126cdd.png)
- Then choose variable option **All** on the dashboard

### What was the expected result?
when value of single stat missing(null) then show repeated single stat panel with:
$ssk_id: Н/Д

### What happened instead?
- variable $ssk_id expanded to a list of all possible values in braces when value is missing(null)
- But, it's all fine when the value is present:
![image](https://user-images.githubusercontent.com/14870891/38132787-42495f1e-3415-11e8-843a-8db0eba5f425.png)
- If you remove variable from prefix: it works fine - null is changed to Н/Д
- If you choose variable $ssk_id other than 'All' then it works fine.

**Comment by torkelo** [comment]
must be a bug in call to templateSrv.replace when using the value mapping. thanks for reporting this.

**Comment by PrincipalsOffice** [comment]
Hi, I am interested in working on this bug fix.

**Comment by PrincipalsOffice** [comment]
I am not able to replicate this bug with custom data, @v-zhuravlev could you provide more details on how to replicate this?

**Comment by PrincipalsOffice** [comment]
@v-zhuravlev @torkelo, After some second thoughts, I wonder if this should be considered as a feature instead of a bug? AFAIK, when option **All** is selected the default behavior has always been displaying a list of all possible values?

**Comment by v-zhuravlev** [comment]
@PrincipalsOffice , It's already inside of some sort of iteration:
like
```
for sskid in ALL:
  show_singlstat(sskid)
```
So what's the purpose or use case could be to display the whole list inside the iteration step if sskid==null?
I would say it's a bug too.

**Comment by torkelo** [comment]
we are deprecating the singlestat panel, please switch to the new stat panel. It supports repeating internally if your query returns many results
