### ISSUE TITLE
Templating: Multi-select variable value 

### ISSUE THREAD

**Issue by yinchuan** [grafana/grafana#1144]
Template Variable with auto-complete is awesome! Thanks.
I think add a selectable template variable value can make template much good!
In my usecase, I usually show several metrics in same graph, the metrics have same path except one node, for now I must go to Graph Edit -> Duplicate Metric and modify the only one different node, that's borning. 
Thanks!

**Comment by torkelo** [comment]
work in progress on this
![multiselect](https://cloud.githubusercontent.com/assets/10999/7392057/81f7b5b2-ee85-11e4-9213-dcbc9b16ecd2.gif)

**Comment by cemo** [comment]
@torkelo cool :)

**Comment by yinchuan** [comment]
Wow, It's great! Thanks!

**Comment by torkelo** [comment]
This feature has been redesigned, the latest version looks like this 
![new_multi_select](https://cloud.githubusercontent.com/assets/10999/7896104/4b851902-06ae-11e5-98d2-0af77ebb0bf7.gif)

**Comment by bwinterseg** [comment]
This feature is fantastic! Does it need to be turned on somewhere? I am using Grafana v2.02 and I don't have that option in the drop down.  I've been googling for a while and can't find an answer.

**Comment by torkelo** [comment]
@bwinterseg as you can on github this issue is added to the 2.1 milestone, which means it is included in the very soon to be released 2.1 version. 

You can download daily pre release builds here:
http://grafana.org/download/builds.html

**Comment by bwinterseg** [comment]
Thanks Torkelo! I apologize that I missed that.  Thanks for the quick response and for such an amazing dashboard.

**Comment by raperumain** [comment]
Hi Team,

I am using the following Query ,

select collection_date AS time , count(cpu) AS “payment”
from host
where host_name=‘payment’
group by collection_date
order by 1

++ Using Add Query , i have added same query 10 time with different host_name

The graph is showing perfectly with 10 lines , But i want metrics should be in Drop-Down list , so that i can select what ever server i want and ‘ALL’ option if required.

Note:
I am using Postgres as a DataSource.

Thanks in Advance

**Comment by marefr** [comment]
@raperumain Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

For starters to get a series by hostname you can group by hostname, i.e.

```sql
select collection_date AS time, host_name, count(cpu)
from host
group by 1, 2
order by 1
```

When you have a variable drop down with hosts you can add a where clause

```sql
...
where host_name in($var)
...

**Comment by tonix-tuft** [comment]
> This feature has been redesigned, the latest version looks like this
> ![new_multi_select](https://cloud.githubusercontent.com/assets/10999/7896104/4b851902-06ae-11e5-98d2-0af77ebb0bf7.gif)

Hello, I need to do something similar, but in my case I would need to show results grouped by the week of the year and a line/bar chart for two or more years selected by the user.

Something like this:

![Screen Shot 2020-07-31 at 09 46 13](https://user-images.githubusercontent.com/10134421/89013110-9c662280-d313-11ea-9a98-5302e56e2c5b.png)


How can I achieve this with Grafana?

Thank you!

**Comment by Jaff** [comment]
I am looking for a similar solution, and still not finding method for adding select-box to drop-down for multiple selection. I  didn't find details in docs, if someone can help, please let me know.
