### ISSUE TITLE
why   $tag_<tag_key>  not working in 5.0.3 ?

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#11442]
### What Grafana version are you using?

5.0.3

### What datasource are you using?
influxdb

### What OS are you running grafana on?
ubuntu16.04

### What did you do?

$tag_host working in my grafana-4.6, but not working in 5.0

![bug](https://user-images.githubusercontent.com/14313415/38135235-99954af6-3449-11e8-95b1-d4292d1e3b42.PNG)

**Comment by svenklemm** [comment]
For ```$tag_<tag_key>``` to work you need to group by ```<tag_key>```

**Comment by crazy-canux** [comment]
Ok.
But, I don't need to group by host.
Thanks
