### ISSUE TITLE
Strange artefact with "Min/MaxMean Graph" and "For each value of" option

### ISSUE THREAD

**Issue by nicolargo** [grafana/grafana#11440]
Hello,

i create a MMM Graph using the following configuration:

![image](https://user-images.githubusercontent.com/776747/38132362-153f2292-340b-11e8-901c-daed133a22cc.png)

It work fine with a single Graph:

![image](https://user-images.githubusercontent.com/776747/38132435-59aa60ae-340b-11e8-8a9c-477d43bf782e.png)

But have a strange behaviour with multiple variable selection:

![image](https://user-images.githubusercontent.com/776747/38132506-a01d6b9e-340b-11e8-8be7-d6b300bbf043.png)

![image](https://user-images.githubusercontent.com/776747/38132469-7e3472de-340b-11e8-9ec4-fd0ea09734c3.png)

**Comment by torkelo** [comment]
not seeing any problem.

Please include your queries and the response from InfluxDB :)

**Comment by nicolargo** [comment]
Have a look on the second graph...

![selection_361](https://user-images.githubusercontent.com/776747/38186564-f6dc9744-3653-11e8-8735-02d32ea05156.png)

The second graph seems to have the first one in background...
