### ISSUE TITLE
Values from Prometheus fluctuate from real value to zero with each refresh   

### ISSUE THREAD

**Issue by moshe0076** [grafana/grafana#11443]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.0.3 and 5.0.4
### What datasource are you using?
Prometheus 2.2.1
### What OS are you running grafana on?
Grafana's Official Docker 
### What did you do?
Configured Prometheus as a data source. On refresh the values on all graphs fluctuate from real value to zero with each refresh.
### What was the expected result?
Real values should be displayed.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
True Values:

![selection_010](https://user-images.githubusercontent.com/6275314/38138076-5ee6ee54-3431-11e8-8fe5-73a56fbc2939.png)

After auto refresh: 

![selection_011](https://user-images.githubusercontent.com/6275314/38138099-8fc12e36-3431-11e8-8221-22011ab6f236.png)

**Comment by torkelo** [comment]
please include your prometheus query and the response from promethus (use query inspector), and the displayed value.
