### ISSUE TITLE
Typo in MSSQL help

### ISSUE THREAD

**Issue by SokoloffA** [grafana/grafana#11455]
https://github.com/grafana/grafana/blob/00f67ea7c7511ff5cb18fd05cfaba9c6f299e98f/public/app/plugins/datasource/mssql/partials/query.editor.html#L52
Typo in line, instead of 
```AND column &t;= DATEADD(s```

should be 
```AND column &lt;= DATEADD(s```

**Comment by daniellee** [comment]
Thanks for reporting this!
