### ISSUE TITLE
view json didn't work on grafana-5.0

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#11454]
### What Grafana version are you using?
5.0

### What datasource are you using?
influxdb

### What OS are you running grafana on?
ubuntu16.04

### What did you do?
I can use http api import  dashboard by "view json" in 4.6.
But, when I upgrade to 5.0, it's not working.

### What was the expected result?
I want to import the dashborad to another grafana.

### What happened instead?

How can I get the usefull json for http api?

**Comment by torkelo** [comment]
Please include more detail? 

Complete request to api, and the response. Grafana UI uses the same API and no other reports on failure to save dashboards using the normal dashboard api.
