### ISSUE TITLE
Imported dashboards are not fully imported, "grid" and "yaxes" fields vanish

### ISSUE THREAD

**Issue by BeUseful** [grafana/grafana#11452]
#### Every time I export a dashboard and then try and import said dashboard into another grafana server everything doesn't fully import.
-------------------------------
**Reproduce:**

1. Export a dashboard using a v2.1.3 Grafana Web GUI on Cent6.9
2. Import that dashboard in step 1) into a v4.6.3 Grafana Web GUI on Cent6.9
3. Now export the dashboard imported in step 2) and compare it with the json in step 1

#### The json in step 1 is mostly the same (as you would expect) when compared with the json in step 3,  however certain fields such as "grid", "yaxes", and "y_formats" don't get fully populated and thus cause tiny inconsistencies.

I do understand that the schema versions changed between v2 and v4, and as a result their had to be some translation done in between, however whats really strange is that if instead of importing the dashboard entirely, if I instead only copy paste a single graph from v2 instance to a v4 instance, those missing fields actually get filled/translated properly.
This seems to suggest that their may be some different form of translation methodology used between importing an entire dashboard vs a just a single graph.

#### If their is a quicker workaround / solution I am missing here, please let me know. ####
-------------------------------
**Example:**

**JSON_EXPORT_STEP_1:** 

  "grid": {
    "leftLogBase": 1,
    "leftMax": 100,
    "leftMin": 0,
    "max": null,
    "min": null,
    "rightLogBase": 1,
    "rightMax": null,
    "rightMin": null,
    "threshold1": null,
    "threshold1Color": "rgba(216, 200, 27, 0.27)",
    "threshold2": null,
    "threshold2Color": "rgba(234, 112, 112, 0.22)"
  },
  "x-axis": true,
  "y-axis": true,
  "y_formats": [
    "percent",
    "short"
    ]
  }

**JSON_EXPORT_STEP_3:**

  "grid": {
    "max": null,
    "min": null
  },

  "yaxes": [
    {
      "show": true,
      "min": 0,
      "max": 100,
      "logBase": 1,
      "format": "percent",
      "label": ""
    },
    {
      "show": true,
      "min": null,
      "max": null,
      "logBase": 1,
      "format": "short"
    }
  ],
  "xaxis": {
    "show": true,
    "mode": "time",
    "name": null,
    "values": [],
    "buckets": null
  }

-------------------------------

**More details:**

What datasource are you using? => graphite
What did you do? => exported a dashboard from a v2.1.3 Grafana instance using the webgui and imported it into a v4.6.3 instance of grafana
What was the expected result? => that the dashboards look/are identical 
What happened instead? => minor inconsistencies specified above.

**Comment by torkelo** [comment]
The schema migration looks correct. What looks different?
