### ISSUE TITLE
row edit icon not shown

### ISSUE THREAD

**Issue by jokerlee** [grafana/grafana#11466]
grafana 5.0.2 with ldap enabled.

data source: elastic search

user can add rows to the dashboard, but cannot edit and delete it, edit/delete button is not shown when mouse hovering on it.
only admin user can edit or delete.

normal ui, admin user
![image](https://user-images.githubusercontent.com/1501465/38245728-e4b7f788-3771-11e8-97f0-3340ebc7e76f.png)

bad ui, normal user with edit permission, no edit/delete button is shown
![image](https://user-images.githubusercontent.com/1501465/38245729-e55902c2-3771-11e8-8507-3f2f2e24bcc7.png)

**Comment by torkelo** [comment]
yea, looks like a bug, the DashboardRow component does not check the dashboard canEdit property instead it just checks the user  role.

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/DashboardRow.tsx#L98
