### ISSUE TITLE
Template vars in InfluxDB tags query throw parsing errors

### ISSUE THREAD

**Issue by droidnxs** [grafana/grafana#11467]
Grafana version: 5.0.0
Data source: InfluxDB
I have created a variable called "ip" using an InfluxDB tag query. InfluxDB allows WHERE clause in tag queries, which I am leveraging by substituting the already created grafana variable in the WHERE clause. I am trying to achieve this by using the $ip variable in another template variable query (tag query) as follows:
`SHOW TAG VALUES FROM oracle WITH KEY="service" WHERE ip=~'/$ip/'` but it doesn't seem to work. I am getting the error `Template variables could not be initialized: error parsing query: found \., expected regex at line 1, char 72` . What could be the issue?
Edit: It seems that the substituted variable is sent with escape characters in the InfluxDB tag request. 
`SHOW TAG VALUES FROM apmsql_oracle WITH KEY="service" WHERE ip = '1\.2\.3\.4'` which is causing the error.

**Comment by alextavgen** [comment]
We have more general problem with InfluxDB Tags queries https://github.com/grafana/grafana/issues/11482

**Comment by torkelo** [comment]
try `ip=~/$ip/`   

InfluxDB regex is without single quotes
