### ISSUE TITLE
Text panel size

### ISSUE THREAD

**Issue by Knaky41** [grafana/grafana#11471]
### What happened instead? Unable to set the size of panel

Hi,

I just migrated to Grafana V5. I used to export my dashboard with the internal renderer. 

In the previous version, I was able to set the height of a text panel and it changed the size of the text panel.

From now, I can't find a way to to the same. When I render my dashboard, the panel of the text is very large of only two words.

Could you please tell me where I can change the height parameter that affect the rendering ?

Thanks.

**Comment by torkelo** [comment]
http://docs.grafana.org/reference/dashboard/#panel-size-position
