### ISSUE TITLE
Single Stat value change - animated

### ISSUE THREAD

**Issue by Tittan31** [grafana/grafana#11477]
Please include this information:
### Windows x86

Hi, is it possible to do somehow animated value changes?
I mean, when value of the single stat for example change from 235 to 260 the numbers change somehow animated. Not just immediately change, but some nice numbers rotation animation could appear.

Only a tip for make dashboard more pretty.

**Comment by marefr** [comment]
Please use the [community site](https://community.grafana.com/) for questions. Github are mainly for feature requests and bug reports.

What you're asking for is not supported in singlestat panel. Possible for you to build a custom panel plugin that has this functionality.
