### ISSUE TITLE
Table hyperlink help text doesn't use curly brackets

### ISSUE THREAD

**Issue by spedepekka** [grafana/grafana#11478]
### What Grafana version are you using?
5.0.3

I had a link which ended to slash  ( / ) and I wanted to add a word after that slash to the hyperlink.

`$__cell/foo` will lead to double slash and `$__cellfoo` doesn't work, so through try and error I figured out that `${__cell}foo` will give the link http://something/foo instead of http://something//foo

The curly braces should be in the help as well.

**Comment by marefr** [comment]
Please use the [community site](https://community.grafana.com/) for questions. Github are mainly for feature requests and bug reports.

Have you tried `[[__cell]]/foo`?

**Comment by spedepekka** [comment]
I did this issue, because pull request wanted the issue ID.

**Comment by marefr** [comment]
Okay gotcha. But I recommend you to try if the [[__cell]]/foo format works. In that case I would like that to also be mentioned in documentation.

**Comment by torkelo** [comment]
@marefr think we should not talk about that syntax, ${varname} should be the prefered syntax going forward, ([[asd]] should be considered deprecated)
