### ISSUE TITLE
Scroll out the top bar navigation section - like in older versions

### ISSUE THREAD

**Issue by Tittan31** [grafana/grafana#11475]
Please include this information:
### Top menu buttons and dashboard title are still visible o the top - it only party disapears after some time and even if that happen that area is not used for panels and it appear like empty space. . I am not able to outscroll it off the visible area. It was much better in 4.x

Please is it possible to have the same behavior in 5.x like in 4.x in the dashboard top menu items?
I am using the fuctionality when i press F11, make fulscreen in browser and scroll down the dashboard to hide all he top menu items and use trully clean view on panels without any disturbing text and buttons which i don't want to see all the time. Maybe there could be some setting option to hide this menus at all

Thank you guys.

**Comment by marefr** [comment]
Just use the [kiosk mode](http://docs.grafana.org/reference/playlist/#tv-or-kiosk-mode).

**Comment by Tittan31** [comment]
Exactly what i needed. Thank you ! :-)
