### ISSUE TITLE
mattn/go-sqlite3 outdated, does not compile on Solaris

### ISSUE THREAD

**Issue by dewi-ny-je** [grafana/grafana#11486]
I experienced the issue mentioned in

https://github.com/mattn/go-sqlite3/issues/514

I copied in the grafana/vendor/mattn the latest release and the issue disappeared.

Please update go-sqlite3 to the latest version, so that the compilation completes without issues on Solaris.

**Comment by marefr** [comment]
@dewi-ny-je what Grafana version were you using when you reported this issue? Seems like we already have version 1.6 of mattn/go-sqlite3 since Grafana v5.0.0-beta1 that's includes the fix of your referenced issue.

**Comment by dewi-ny-je** [comment]
I just checked and the Changelog.md was listing 5.1.0 (unreleased).
The compilation was performed on 2017-04-04, the download at most 7 days earlier, but more likely 2-3 days earlier.

As written, after manually replacing the included mattn/... with the trunk from their repo, it worked fine.
If you check the dates, the 1.6.0 release comes few days before the fix I needed.
As long as you provide 1.7.0, you should be fine.

**Comment by marefr** [comment]
In that case you referred to the wrong issue in mattn/go-sqlite3 and/or there was some other fix in 1.7.0 that fixed your problem.

Just wanted to verify that this was still an issue for you. Thanks
