### ISSUE TITLE
Add Unit Relative Humidity

### ISSUE THREAD

**Issue by hoerup** [grafana/grafana#11488]
Relative Humidity is measured in %RH, which is not included in the current set of units.

**Comment by dewi-ny-je** [comment]
Scientifically speaking, %RH is not a unit of measure.

**Comment by flopp999** [comment]
I will remove %RH with same argument as @dewi-ny-je

**Comment by ryantxu** [comment]
In 6.6, you can just type "%RH" in the unit field
