### ISSUE TITLE
InfluxDB tag queries return panic:runtime error

### ISSUE THREAD

**Issue by alextavgen** [grafana/grafana#11482]
**Problem: A lot of Grafana grafs were with missing Data Points. Sometimes problem repaired by itself.**

We found that this problems was related to the queries with `WHERE` clause. More precisely it was related to the queries where Grafana Variables are used

So main problem were in the variables definition.

We found that TAG QUERIES gave totally wrong results, if gave anything.

So we checked same queries with hardcoded values in **InfluxDB (Cronograf)** and **Grafana** in preview of Variables settings.

So when In InfluxDB query like this
`SHOW TAG VALUES ON poms_influx FROM logins WITH KEY = mobile WHERE site = 'Foo'`

returned all mobile services for Foo site

Same query from Grafana Variables sessions query returned
```

{"results":[{"statement_id":-1,"error":"SHOW TAG VALUES ON poms_influx FROM logins WITH KEY = mobile WHERE site = 'Foo'
 [panic:runtime error: invalid memory address or nil pointer dereference]"}]} 
```

So we originally have regexps in our TAG queries and it is similar to this issue [11467](11467) but when we tried with hardcoded values it didn't work either and issue is more general.

We got it on **Grafana 4.6.2** and on **Grafana 5.0.4 (commit: 7dc36ae2f)**
Updated: **influxdb-1.5.0-1.x86_64**
Grafana on Windows  and Linux CentOs, both system affected
**Centos 7.4.1708
Windows Server 2008 R2 Enterprise**

Main problem that this bug is dissapear and shows up again within some days. Last week we had 4 cases where this problem occurs and disappear after a while from hours to days.

**Comment by torkelo** [comment]
this looks like a bug or issue in InfluxDB, the query grafana sends is correct and the error is happening in InfluxDB
