### ISSUE TITLE
[Feat] CloudWatch GetMetricData support

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#11487]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html
We can use Math expression!!

**Comment by djhworld** [comment]
I'm interested in looking into this, but I have a feeling it's quite a significant change given the request/response model is a lot different, and would probably require frontend changes to support adding maths expressions over existing queries. 

Is there anywhere we can discuss this?

**Comment by mtanda** [comment]
@djhworld Please see https://github.com/grafana/grafana/pull/11624 .
Actually, I change frontend code little.
