### ISSUE TITLE
[Bug] Certain time ranges incorrectly display data

### ISSUE THREAD

**Issue by codingwatermelon** [grafana/grafana#11485]
System Information:
- Grafana v5.0.4 (commit: 7dc36ae) with InfluxDB on CentOS 7

I noticed that certain ranges don't show correct data. An example is attached to this post. As you can see, the first picture shows that there is a spike in CPU usage at around midnight on 4/4 (which is correct). This graph is shown using the 'This week so far' quick range. You can also see the time range in the top right corner for both pictures.

The second picture shows no spike in CPU usage around the same time as mentioned before (which is incorrect), even though the spike is clearly within the range from before. This graph is shown using the 'This week' quick range.

This seems to be the case for a handful of other ranges, including 'This month', 'This year', 'This year so far', and even custom ranges set to be equivalent to 'This week', etc...

Below I've included the request URL for the different types of graphs as discussed above:

**This week so far:**
https://grafana.server:3000/api/datasources/proxy/1/query?db=grafana&q=SELECT last("value") FROM "autogen"./^check_cpu-wmi$/ WHERE ("hostname" =~ /^REDACTED$/ AND "service" =~ /^check_cpu-wmi$/) AND time >= 1522576800000ms GROUP BY time(2m), "metric", "service" fill(none)&epoch=ms

**This week:**
https://grafana.server:3000/api/datasources/proxy/1/query?db=grafana&q=SELECT last("value") FROM "autogen"./^check_cpu-wmi$/ WHERE ("hostname" =~ /^REDACTED$/ AND "service" =~ /^check_cpu-wmi$/) AND time >= 1522576800000ms and time <= 1523181599999ms GROUP BY time(5m), "metric", "service" fill(none)&epoch=ms

I'll include the network response if necessary.

![screen shot 2018-04-04 at 9 15 28 am](https://user-images.githubusercontent.com/32379178/38331456-feceeca8-37ee-11e8-98aa-af5f869ec667.png)
![screen shot 2018-04-04 at 9 15 44 am](https://user-images.githubusercontent.com/32379178/38331457-ff004ce4-37ee-11e8-8a8d-b2d8853d8621.png)

**Comment by josepiratilla** [comment]
Have you checked the response from influxDB at both cases. Seems that it is related with the response of the InfluxDB. My guess is that in the first call, you are getting a sample over 2 minutes buckets. And at the second you are getting this sample at 5 minutes buckets. The peak could be masked by a higher average period.

**Comment by torkelo** [comment]
You query picks the last value of each time bucket
