### ISSUE TITLE
[Bug] Histogram: Highest value bucket is not shown

### ISSUE THREAD

**Issue by christopherlange** [grafana/grafana#11498]
### What Grafana version are you using?
Version 5.0.4
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu
### What did you do?
Created a histogram with the following InfluxQL SELECT statement (detailed names changed). 
SELECT max("field") FROM "series" WHERE $timeFilter GROUP BY "tag"
### What was the expected result?
All data points shown on the histogram.
### What happened instead?
While the SELECT returns n values, the histogram shows n-1 values with the maximum bucket value not shown on the x-axis. Making a Table panel with the original select statement shows that all data is being pulled from InfluxDB.

**Comment by torkelo** [comment]
thanks for reporting this, this is indeed a bug in how we draw histograms. Seems to be rooted in how we draw bars as the bar needs space to the right in order be drawn. Maybe we can fix it by changing how render the x-axis ticks in the histogram so the last tick has space to actually render a bar. 

<img width="1207" alt="screen shot 2018-04-06 at 06 59 35" src="https://user-images.githubusercontent.com/10999/38404132-2c39e510-3968-11e8-84b2-10e356714c27.png">

@alexanderzobnin can you investigate this? Might be a quick solution by just adjusting the x-axis tick generation.
