### ISSUE TITLE
Request: create template variable that will contain user name (user login)

### ISSUE THREAD

**Issue by shizacat** [grafana/grafana#11493]
Hello,
I am saw posts: https://github.com/grafana/grafana/issues/4922, https://github.com/grafana/grafana/issues/8882

But they are all closed. But there is no solution. Could you still add such a variable? Or at least to plan her.
Can do datasource, which will return current user login.

**Comment by torkelo** [comment]
reopened https://github.com/grafana/grafana/issues/4922 as it should not have been closed
