### ISSUE TITLE
How to add dashboard using dashboard provisioning(Example of cratedb and SimpleJSON)??

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#11490]
Hello...

Any one know or experiment of dashboard provisioning if you have any example of the dashboard configuration of(Cratedb and SimpleJson)??

If you have any proper working  configuration example share with us.

Also Request to the grafana team to updated the document of the dashboard provisioning  and please don't close the issue without get solution.

Thanks....

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
