### ISSUE TITLE
Query editor for variables mis-aligned with the one for graphs

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11491]
Grafana 5.0.3 with Prometheus

While queries for getting data from Prometheus and into Grafana variables have more syntax than PromQL alone, it would still be nice to have highlighting, completion, etc.

Furthermore, in graph definitions, I can click "Link to Graph in Prometheus" and have all variables filled out in my query. Working with nested variables in Grafana becomes painful after some levels and having a way to jump into Prometheus to see source data would often help.

A trivial example of nested variables with the correct substring to use as link to Prometheus would be:
label_values(>>>ifHCInBroadcastPkts{customer="$customers",instance="$devices"<<<}, ifDescr)

**Comment by torkelo** [comment]
This would be reallt nice, but first we need to implement a way for data source plugins to override and provide a custom query editor UI component for the template variable query.

This is something we have wanted to do for a while, could not find an issue for it so created this issue. 
https://github.com/grafana/grafana/issues/11505
