### ISSUE TITLE
Allow more than 20 previews when creating a variable

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11508]
Grafana 5.0.4 with Prometheus

When creating a variable, I would sometime prefer to see more than the max 20 values of "Preview of values". Defaulting to 20 is fine, but there should be an option to extend the amount of previews, and to show all of them.

**Comment by bergquist** [comment]
I don't want to introduce an option for this. But I think some kind of "show more" feature would be ok. 

Increasing this to 50 would be ok as a short-term solution.

**Comment by RichiH** [comment]
For completeness' sake: I didn't mean "an option" as in "make this a config setting", just "allow the user to do so". A "show more" button would suffice.

Quoting the edited out part: I am ambivalent on 20, 50, or something else being the default.
