### ISSUE TITLE
Variable definition autoselects data source during creation, but not for saving

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11507]
Grafana 5.0.4 with Prometheus

Adding a new variable, "Data source" is empty. Yet, I can write a query and see results in "Preview of values". Actually _saving_ the variable forces me to select a data source, though.

Setting a default is fine, but then it should be set for both exploration and creation of the variable. Furthermore, having things magically work this way means users might be running queries against a wrong data source without realizing their mistake.

**Comment by hugohaggmark** [comment]
Closing this as you can't write a query before selecting a data source in Grafana since at least 6.0. We're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
