### ISSUE TITLE
Windows Server 2012 as Client Telegraf - Grafana & InfluxDB - Only network & Uptime graph shows

### ISSUE THREAD

**Issue by esxi1979** [grafana/grafana#11506]
hello all,

Windows Server 2012 as Client Telegraf - Grafana & InfluxDB - Only network & Uptime graph shows, i tried 2 Jason files (dashboard but same patterns) , windows server which is client here, do not have firewall

pls suggest

thx

**Comment by esxi1979** [comment]
The fact that i get other data suggest the DB connection is ok. Also when i use the linux client all graphs coming ok , so DB connectivity i not issue 

Grafana cli version 5.0.3
Running on RHEL 7

**Comment by daniellee** [comment]
Please ask questions on the [community site](https://community.grafana.com/).
