### ISSUE TITLE
Plugins: Make template variable query a plugin UI component

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#11505]
Template query editor can be much improved from the current text box that is shared among all data sources. In order to do that we need to add a way to make this into a plugin component, similar to annotations query editor and metrics query editor.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by jackw** [comment]
@torkelo is this issue still relevant?

**Comment by torkelo** [comment]
No , implemented long ago
