### ISSUE TITLE
Visualize regex input and output when creating variables

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11509]
Grafana 5.0.4 with Prometheus

Writing Regex is sometimes hard for newer members of our teams. Having a built-in exploratory tool which would list all input and all output data as a table with two rows would go a long way.

If you want to get fancy, highlighting regex and matches, plus aligning matches in the list (think how GitHub shows diffs) would be even better.

**Comment by davkal** [comment]
Something interesting for @hugohaggmark

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
