### ISSUE TITLE
Test alert rule suffer MarshalJSON error

### ISSUE THREAD

**Issue by xikunyang** [grafana/grafana#11512]
### What Grafana version are you using?

5.0.4

### What datasource are you using?

prometheus 2.2.1

### What OS are you running grafana on?

Linux 3.10.0-693.11.1.el7.x86_64

### What did you do?

create alert rule, and test rule.

### What was the expected result?

show warnning state

### What happened instead?

lvl=eror msg="body json marshal" logger=context userId=1 orgId=1 uname=admin error="json: error calling MarshalJSON for type null.Float: invalid character 'N' looking for beginning of value"

### If related to metric query / data viz:

![image](https://user-images.githubusercontent.com/36947547/38413040-2f6ba12e-39bd-11e8-9238-ea5f617438de.png)

![image](https://user-images.githubusercontent.com/36947547/38413310-e37cf1ae-39bd-11e8-9f82-fbc8e2875b88.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
http response:

`{"message":"body json marshal"}`

grafana log:

```
lvl=eror msg="body json marshal" logger=context userId=1 orgId=1 uname=admin error="json: error calling MarshalJSON for type null.Float: invalid character 'N' looking for beginning of value"
```

**Comment by xikunyang** [comment]
Today I try it again, cannot reproduce now...

**Comment by pokemane** [comment]
I'm actually getting this same error.  @xikunyang did you restart Grafana between the time when you *could* reproduce the issue, and when you stopped being able to reproduce it?  I don't want to disturb whatever may be happening.

**Comment by xikunyang** [comment]
@pokemane I don't remember weather I had restart Grafana. Only one things is the data growing.

**Comment by andel7** [comment]
How this issue was resolved ? I having that issue as well ?
version=5.0.4

**Comment by rovan** [comment]
I`m facing the same issue, version=5.1.4

**Comment by mtparet** [comment]
I have the same issue too again.

**Comment by mtparet** [comment]
In the logs I got this error:
```
error="json: error calling MarshalJSON for type null.Float: invalid character '+' looking for beginning of value"
```

**Comment by agolomoodysaada** [comment]
Also experiencing this issue on 5.4.2

**Comment by tamer-hassan** [comment]
Also experiencing this issue on Grafana v6.0.1 (commit: 0c44a04)

**Comment by songjiao** [comment]
when use reduce function like percent_change or percent_diff, in some case you may got xx/0 ,in golang it present +Inf Or -Inf. that cause error:

**Comment by songjiao** [comment]
when use reduce function like percent_change or percent_diff, in some case you may got xx/0 ,in golang it present +Inf Or -Inf. that cause "json: error calling MarshalJSON for type null.Float: invalid character '+' looking for beginning of value"
