### ISSUE TITLE
Share icon missing - mobile devices

### ISSUE THREAD

**Issue by VR6Pete** [grafana/grafana#11523]
Hello,

When viewing a dashboard on a mobile device the icon to share the dashboard is not visible.

This is incredibly useful when sharing on the go either locally or via snapshot.raintank.io 

The icon appears on the desktop browser though. 

Cheers. 

Pete

**Comment by torkelo** [comment]
there is no space for it on mobile view so it's hidden

**Comment by matjazmav** [comment]
It is missing in firefox too 

![image](https://user-images.githubusercontent.com/9011654/38471997-77be8708-3b79-11e8-9321-320d17eeaa11.png)

**Comment by VR6Pete** [comment]
I gathered it was hidden due to small screen estate. 

Perhaps a small pop up menu could be implemented that displays all of the hidden icons.

**Comment by flopp999** [comment]
I have also seen this.
Try to open a private/incognito tab it worked for me,I don’t know why but maybe something with cache or adblocker

**Comment by danhawkes** [comment]
Yeah, think this is adblocker related. For me, was using 'Fanboy’s Annoyance List​​​​​​​​​' in ublock origin:

![screen shot 2018-05-08 at 10 57 26](https://user-images.githubusercontent.com/3388897/39750988-ab7b6eca-52ae-11e8-81c7-78b89258e123.png)

**Comment by dswarbrick** [comment]
Indeed it seems to be related to adblockers. I am using Adblock Plus, and found that the icon is blocked by enabling the "Block social media icons tracking" option in ABP.

Sadly it is also blocked in another part of the UI - the "link to dashboard in Prometheus" icon in the query editor is broken.

**Comment by torkelo** [comment]
Closing this as related to browser extension
