### ISSUE TITLE
Unable to scroll down in Chrome - pages overflow off bottom of screen. Work in Edge.

### ISSUE THREAD

**Issue by AlexHeylin** [grafana/grafana#11524]
Please include this information:
### What Grafana version are you using?
5.0.4
### What datasource are you using?
Affects all - MySQl, Graphite, PRTG.
### What OS are you running grafana on?
Windows 10 (same machine as "server" and running Chrome browser)
### What did you do?
Opened web page and tried to scroll down (mouse, page down, & arrow keys). Any long page will do - including most of the datasource set up pages, the dashboards etc
### What was the expected result?
Page would scroll down
### What happened instead?
Nothing.  No scroll bar. Page Down and arrow keys don't scroll the page either.  Possible to see the whole page by zooming out to 25% but then it's too small to work with.
Change to full screen mode (F11) and scroll bar appears and scrolling works. Exit full screen mode and scrolling still works as expected.
In Edge the page will scroll immediately after load - no need to go full screen etc.

**Comment by torkelo** [comment]
strange, unable to replicate this here. What version of chrome are you using?

**Comment by daniellee** [comment]
We just made a major change to scrolling in the master branch #11456 which affects page scrolling. This change will be released in 5.1 (which will be soon).

**Comment by daniellee** [comment]
@AlexHeylin can you test this again after the 5.1 release (hopefully will be released next week) - I think these issues are resolved.

**Comment by AlexHeylin** [comment]
@daniellee - it's working great in the 5.1 beta. Thanks 😄
