### ISSUE TITLE
[docs website]drop-down button in responsive version of the site is functioning improperly

### ISSUE THREAD

**Issue by shiveshabhishek** [grafana/grafana#11521]
Please include this information:
### What Grafana version are you using?
grafana docs :latest
### What datasource are you using?
not required
### What OS are you running grafana on?
Ubuntu 17.10(Chrome browser responsive view & in mobile :Chrome browser)
### What did you do?
Clicked on drop-down button
### What was the expected result?
when clicked on drop-down, it should open up and when clicked again, it should close.
### What happened instead?
functioning randomly.

![grafana](https://user-images.githubusercontent.com/29581152/38453930-4b1847e2-3a7b-11e8-8b04-f61474afabe6.gif)

**Comment by Ijin08** [comment]
Has been fixed.
