### ISSUE TITLE
[Bug] Pause all alerts with api does not work anymore

### ISSUE THREAD

**Issue by Labbs** [grafana/grafana#11522]
### What Grafana version are you using?
v5.0.4
### What datasource are you using?
Prometheus/Cloudwatch
### What OS are you running grafana on?
Ubuntu 16.04.3
### What did you do?
`curl http://127.0.0.1:3000/api/admin/pause-all-alerts --user admin:xxxxxxxxxxxxx -X POST -d '{"paused": true}' --http1.1`
### What was the expected result?
All alerts in status pause
### What happened instead?
{"alertsAffected":14,"message":"alerts un paused","state":"pending"}

I do not have any error / information in the grafana logs during the API call.
All alerts change status for Pending and a few seconds later in status OK.

**Comment by Labbs** [comment]
Same test with grafana v4.6.3 (commit 7a06a47) and same result.

Another test:
`curl http://127.0.0.1:3000/api/alerts/47/pause --user admin:xxxxx -X POST -d '{"paused": true}'`
Same result : `{"alertId":47,"message":"alert un paused","state":"pending"}`

**Comment by torkelo** [comment]
you are missing `-H "Content-Type: application/json"` from your call  (without this the paused json flag you send is not parsed), will add some better validation here.
