### ISSUE TITLE
Add data source: redshift into grafana gives ERROR:- Metric request error

### ISSUE THREAD

**Issue by golokeshpatra45** [grafana/grafana#11533]
Host : -  psql -h <endpoint> -U <userid> -d <databasename> -p <port>

SSL Mode: -  tried with all but gives same error.

![image](https://user-images.githubusercontent.com/26374269/38496568-b653c4f4-3c1b-11e8-941a-40bf2096fc9d.png)

please help me out

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
