### ISSUE TITLE
Variable list from query

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#11539]
When passing variable values via query parameter like http://play.grafana.org/d/000000176/4-years-of-grafana?orgId=1&var-servers=x&var-servers=y it is not possible to create typical list of values as seen here http://play.grafana.org/d/000000176/4-years-of-grafana?orgId=1&var-servers=All

Thus it's impossible to have rows/panels repeat by that variable with dynamic values as there is no list to be repeated.

This repeats:
![image](https://user-images.githubusercontent.com/327717/38511048-21c403f6-3c27-11e8-8467-a08f19a19dcd.png)

This does not:
![image](https://user-images.githubusercontent.com/327717/38511098-4c6bb216-3c27-11e8-8f85-ece6743c5413.png)

**Comment by torkelo** [comment]
not sure I understand, work fine. 

just change variable to allow multi, and change Cool Graph to repeat for each server selected:

http://play.grafana.org/d/000000176/4-years-of-grafana?orgId=1&var-servers=backend_01&var-servers=backend_02
