### ISSUE TITLE
[Bug] mysql time column doesn't support non nullable timestamps 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#11535]
Having a table structure of 

```sql
CREATE TABLE `test` (
  `time` int(11) NOT NULL DEFAULT '0',
  `int_value` int(11) DEFAULT NULL,
  PRIMARY KEY (`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

and then issuing a time series query of 

```sql
SELECT time as time_sec, int_value FROM grafana.test;
```

Results in the following error: `Invalid type for column time, must be of type timestamp or unix timestamp, got: *int32 0xc4209f9588`

**Comment by svenklemm** [comment]
looks more like the driver returns int32 but grafana only accepts int64 there, but thats just a guess

**Comment by marefr** [comment]
@svenklemm that's definitely the case, but it will return `*int32* if it's a nullable column.
