### ISSUE TITLE
[Feature Req] Send more details during alert notifications using webhooks

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#11538]
### What Grafana version are you using?
`5.0.4`
### What datasource are you using?
Graphite
### What OS are you running grafana on?
MacOS

We're trying to use webhooks to integrate with some custom flows which are triggered by Grafana alerts. However, the lack of detail in these alert notifications make it incredibly difficult to correlate events.

## Example:
We have a panel that has 4 series, `A`, `B`, `C`, `D`, and an alert configuration along the lines of:

- if `A` > 1000 *OR* `B` > 1000 *OR* `C` > 1000 *OR* `D` > 1000

When `B` triggers, we get the following body sent to our API:

```
{
    "evalMatches": [
        {
            "value": 15.748,
            "metric": "{prod}{stats} Lambda Alert Test",
            "tags": null
        }
    ],
    "ruleId": 2,
    "ruleName": "{stats} Test Lambda Alert",
    "ruleUrl": "http://beta.grafana.abc.com:3001/d/GzKT10mmk/sandbox?fullscreen=true&edit=true&tab=alert&panelId=2&orgId=1",
    "state": "alerting",
    "title": "[Alerting] {stats} Test Lambda Alert"
}
```

This is a relatively useful chunk of data, especially the addition of `tags` being passed. However, when this alert returns to healthy, much fewer details are sent:

```
{
    "evalMatches": [],
    "ruleId": 2,
    "ruleName": "{stats} Test Lambda Alert",
    "ruleUrl": "http://beta.grafana.abc.com:3001/d/GzKT10mmk/sandbox?fullscreen=true&edit=true&tab=alert&panelId=2&orgId=1",
    "state": "ok",
    "title": "[OK] {stats} Test Lambda Alert"
}
```
 
The conundrum here is that when we get the "all clear" alert, we don't know *which* metric has been cleared. Since we are updating annotations via the Grafana API based on which metrics are unhealthy, this makes it difficult to update the correct annotations when a metric returns to a healthy state.

## Request
Since we're sending to a webhook, I recommend sending significantly more data, since the body will likely need to be parsed by the destination API anyway. Better to have more details than you need, rather than the alternative.

**Comment by bergquist** [comment]
Currently, grafana does not keep track of what series are violating the thresholds. Only that some series for that alert is doing that. 

I'm closing this since it's not currently possible to add more details until https://github.com/grafana/grafana/issues/6041 have been fixed.

**Comment by josefkorbel** [comment]
Came here from #17535. If I am fetching the alerts from Alert API, there are all those informations available, how it is not being passed to the Webhook? #6041 is almost 2,5 years old thread. Any news? This is unfortunately very limiting for us :/
