### ISSUE TITLE
datasource provisioning not working if datasource has nested jsonData options

### ISSUE THREAD

**Issue by SPFZ** [grafana/grafana#11537]
### What Grafana version are you using?
5.0.4

### What datasource are you using?
[grafana-prometheus-alertmanager-datasource](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource) but other datasources might be effected if they use nested configuration

### What OS are you running grafana on?
Ubuntu 16.04 (Linux vagrant 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
Docker version 17.12.0-ce, build c97c6d6

### What did you do?

* Installed Grafana as Docker Container
* Installed Alertmanager Datasource Plugin version 0.0.4 (https://grafana.com/plugins/camptocamp-prometheus-alertmanager-datasource/installation)
* provisioned the datasource via config file:

```
apiVersion: 1
deleteDatasources:
datasources:
- name: alertmanager
type: camptocamp-prometheus-alertmanager-datasource
access: proxy
url: https://192.168.77.30
version: 1
editable: false
jsonData:
tlsSkipVerify: true
severity:
critical: 3
warning: 2
info: 1
```

### What was the expected result?
That the datasource is added and the plugin is configured as set up.

### What happened instead?
Datasource is added but configuration from jsonData is not applied. Also verified via api:

```
# request to https://192.168.77.20/api/datasources
[
        {
"id": 21,
"orgId": 1,
"name": "alertmanager",
"type": "camptocamp-prometheus-alertmanager-datasource",
"typeLogoUrl": "public/img/icn-datasource.svg",
"access": "proxy",
"url": "https://192.168.77.30",
"password": "",
"user": "",
"database": "",
"basicAuth": false,
"isDefault": false,
"readOnly": true
        },
....
```

jsonData is missing

Setting up via grafana web gui works as expected. The problem seams to be that the nested structure is not properly handled while reading the config. The problem might be somewhere around here: https://github.com/grafana/grafana/blob/v5.0.4/pkg/services/provisioning/datasources/types.go#L222
I tried to find an issue but there is nothing that is obvious to me.

I also tried different variants of configuration formatting (documentation suggests json blob), so I tried things like this without success:
`jsonData: {"tlsSkipVerify":true, "severity": {"critical":page,"warning":critical,"info":warning}}`
`jsonData: '{"tlsSkipVerify":true, "severity": {"critical":page,"warning":critical,"info":warning}}'`
`jsonData: '{"tlsSkipVerify":true, "severity": {"critical":"page","warning":"critical","info":"warning"}}'`

```
jsonData:
tlsSkipVerify":true
severity: {"critical":page,"warning":critical,"info":warning}}

# produces in the api but does not work in the datasource configuration
"jsonData": {
"severity": "{\"critical\":page,\"warning\":critical,\"info\":warning}}",
"tlsSkipVerify": true
},
```

@bergquist Since you might be familiar with the code of the provisioning it would be very kind if you could take a look at this, thanks in advance.

**Comment by maxwo** [comment]
Got the same problem for the exact same use-case: alertmanager datasource plugin.

This requires nested JSON data, which is currently unsupported.

Thanks, and great job for this release: love the look'n'feel 👍

**Comment by mbreedveld** [comment]
Same over here only with an elasticsearch data source. It's only possible to change these settings in the ui and not via the jsonData field inside the datasource yaml files.

**Comment by njbartlett** [comment]
I have hit the same problem in Grafana 5.1.0. Trying to use the same plugin...

**Comment by thschoen** [comment]
I got the same issue with Grafana 5.3.4. Will there be a fix in one of the next releases?

**Comment by ptselios-inmarsat** [comment]
I hit exactly the same issue with 5.3.4 using the Cloudwatch plugin (which HAS nested JSON data)

**Comment by Xaroth** [comment]
I too am seeing this issue with fetzerch-sunandmoon-datasource.

**Comment by jcard0na** [comment]
I have encountered the same issue.  Adding additional detail in case it helps:

**What Grafana version are you using?**

Grafana v5.4.2 (d812109)

**Datasource**

Timescaledb/Postgres 9.6

**Steps**

1. Create datasource via webui.  Database connection succeeds.
2. Read back via API.  Got:
```
datasource = {
                    'orgId': 1, 
                    'name': 'Oddity', 
                    'type': 'postgres', 
                    'typeLogoUrl': '', 
                    'access': 'proxy', 
                    'url': 'database:5432', 
                    'password': 'XXXXX',
                    'user': 'postgres', 
                    'database': 'my_db', 
                    'basicAuth': False,
                    'basicAuthUser': '', 
                    'basicAuthPassword': '', 
                    'withCredentials': False, 
                    'isDefault': False, 
                    'jsonData': {'postgresVersion': 906, 'sslmode': 'disable', 'timescaledb': True},
                    'secureJsonFields': {'password': True}, 
                    'version': 2, 
                    'readOnly': False
                     }
```
3. Delete and try to re-create the same datasource via API with the above arguments.
4. Read back and observe missing fields `jsonData`
```
datasource = {
   'id': 19, 
   'orgId': 1, 
   'name': 'Oddity', 
   'type': 'postgres', 
   'typeLogoUrl': '', 
   'access': 'proxy', 
   'url': 'database:5432', 
   'password': 'XXXXX, 
   'user': 'postgres', 
   'database': 'my_db', 
   'basicAuth': False, 
   'basicAuthUser': '', 
   'basicAuthPassword': '', 
   'withCredentials': False, 
   'isDefault': False, 
   'secureJsonFields': {}, 
   'version': 1, 
   'readOnly': False
}
```

**Comment by SPFZ** [comment]
Problem is being circumvented by using a flat config structure in the grafana-prometheus-alertmanager-datasource. Therefor I close this issue. https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/issues/26

**Comment by Xaroth** [comment]
@SPFZ What about the other datasources that have this same issue? such as fetzerch-sunandmoon-datasource

**Comment by Duologic** [comment]
Also see https://github.com/grafana/grafana/issues/11537#issuecomment-450082815 which has the same issue.

**Comment by SPFZ** [comment]
Since the Bug was open for about 10 month I assumed that it is "won't fix". @bergquist Is this a bug which would be fixed in the future or should datasources stick to a flat json structure?

**Comment by bergquist** [comment]
The ratio of incoming issues/bug reports and our capacity makes it hard to fix everything. 
I dont want to rule out this being fixed by the Grafana team or external contributors. 

I'd like to reopen this.

**Comment by ajr2493** [comment]
Also running into this issue trying to configure a cloudwatch datasource with v6.0.0-beta1.

```
- name: 'cw-data-prod'
  type: 'cloudwatch'
  jsonData:
    timeField: '@timestamp'
    authType: 'arn'
    assumeRoleArn: 'arn:aws:iam::***:role/test-grafana'
    defaultRegion: 'us-east-1'
```

Web UI shows datasource is added, but none of the jsonData config appears to be respected. Fix would be much appreciated.

**Comment by Duologic** [comment]
@ajr2493 That doesn't look like the same issue, there is no nesting in your config.

When configuring the Cloudwatch plugin, I had to drop the assumeRoleArn information. The SDK somehow figures that out by itself. I don't know the timeField attribute and I don't see it in the docs, maybe that is the issue?

Give this a try:

```
  - name: Cloudwatch
    type: cloudwatch
    jsonData:
      authType: arn
      defaultRegion: us-east-1
```

**Comment by marefr** [comment]
@ajr2493 yes not same issue as this, please open a separate issue.

**Comment by fetzerch** [comment]
I'd like to fix this issue in `sunandmoon-datasource` by flattening the `jsonData` from `{ "position": { "latitude": 40, "longitude": 10}}` to `{ "latitude": 40, "longitude": 10}`.

Similar to what has been done in https://github.com/alexanderzobnin/grafana-zabbix/pull/600/files or https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/30/files.

Is there a way to do this in a backward compatible way so that people who're upgrading from the old version don't have to reenter the settings?

What I had in mind is something like the following code in the plugin constructor:

```
    if ('position' in instanceSettings.jsonData) {
      instanceSettings.jsonData.latitude = instanceSettings.jsonData.position.latitude;
      instanceSettings.jsonData.longitude = instanceSettings.jsonData.position.longitude;
      delete instanceSettings.jsonData.position;
    }
```

But that didn't have the desired effect and the fields in settings are still empty.
Would be nice to get some help on that from a more experienced plugin developer.

**Comment by Duologic** [comment]
I think this should be fixed in Grafana, not in the plugins itself.

**Comment by Xaroth** [comment]
@fetzerch Check out my fork of your datasource, I fixed it in a similar fashion as you suggest.

**Comment by fetzerch** [comment]
@Xaroth sure the change itself is trivial. Still I would prefer to not break existing installations on update. I would prefer a way do implement it in a backwards compatible way - I just don't see how that can be done at the moment.

**Comment by Xaroth** [comment]
@fetzerch Assign the values you use either from the jsonData.position dict _or_ from the jsonData dict directly? That should work in a backwards compatible way. If the values from jsonData.position is used, you can update the jsonData dict to keep the interface functional.

**Comment by treksler** [comment]
> Same over here only with an elasticsearch data source. It's only possible to change these settings in the ui and not via the jsonData field inside the datasource yaml files.

I am not sure if nested jsonData is required to produce this issue in elasticsearch. 
Rather, nothing is loaded from jsondata, when provisioning an Elasticsearch datasource. 
could be a separate issue
