### ISSUE TITLE
Feature Request: Legend support id ->  name translate

### ISSUE THREAD

**Issue by springside** [grafana/grafana#1153]
Legend support id -> name translate.

Some times we use the "id" , an auto increase number in database as primary key,   as part of the counter name. But in the graph, we wish to display the "name".

Does Grafana support alias the id -> name?  For example, call a RESTful API to get the id->name mapping in JSON format

**Comment by grzegorz-dubicki** [comment]
+1!!!

**Comment by xaka** [comment]
+1. One of the most missing features for me. I think I could work on it, though I'm not sure where to start yet. I was thinking of somekind of a cache that you either could build up by pulling data from data sources or feeding it into grafana using its REST API, which seems to be easier approach for the beginning. Later you could tell metric query to send a node of query through a named cache and call it good.

**Comment by Dieterbe** [comment]
+1, related, it would also be useful to have extra information (metadata, textual description) about metrics. obviously that wouldn't fit in a legend entry as suggested here, but maybe could appear as a tooltip as you hoover over the legend entry. maybe the api could return a doc with 2 fields: `key` (used in legend) and `extra` (used in tooltip) or something.

**Comment by IzakMarais** [comment]
+1. We have this exact use case and it is high priority for us: I also would be willing to work on this. Some initial high-level guidance would be good though. 

Some implementation decisions:
* Where will the mapping live. Options include 
   * the built-in grafana sqlite DB or 
   * elasticsearch.   
* How will the mapping be populated. 
    * Via Grafana REST API or 
    * pre-populated elasticsearch table. 
* How to activate the feature on the UI
  * Per metric setting. Similar to the current openTSDB alias feature, we could extend the syntax from the current `$tag_<tagk>` to also support `$tag_lookup_<tagk>` 
  * In addition there might be some global activation required?

**Comment by IzakMarais** [comment]
Looking at https://github.com/grafana/grafana/issues/1034#issuecomment-138457644 from https://github.com/grafana/grafana/issues/1034 would it be possible to use those new elasticsearch aliasing and mapping features to achieve this usecase?

**Comment by torkelo** [comment]
@IzakMarais if your time series metrics are all located in Elasticsearch, then yes it could. but not sure if the metrics editor and aliasing feature allows you to use a field (doc property) in the alias that is not use to generate a series.

**Comment by IzakMarais** [comment]
I have started working on a PR for this and would appreciate feedback on design decisions.

### Ownership of the mapping data
We do not want the _ID -> name_ mapping data to be owned by Grafana; it should live in an external datasource. We use this mapping in other applications and manage its state in a stand-alone service. The first external mapping datasource I will support is elasticsearch. Later I will add a custom datasource plugin to talk to our own ID mapping service.

### UI location 
There mapping is enabled on a per dashboard setting:
<img width="470" alt="dasbhoard settings" src="https://cloud.githubusercontent.com/assets/8266640/10994008/0c4ae2fc-847c-11e5-954f-b1b04bc1a8f1.png">
This avoids coupling between the metrics datasources and the mapping datasource. The feature should work for all metric datasources without requiring special implementation for each one. 

The mapping also requires a special `$map(id)` syntax in the legend alias and replaces it with the id->name:
<img width="687" alt="metric settings" src="https://cloud.githubusercontent.com/assets/8266640/10994064/730dc2f2-847c-11e5-9763-a8948d7a32da.png">
This syntax identifies when calls to the mapping datasource are necessary.

**Comment by mtanda** [comment]
For CloudWatch, translate instance id => instance name tag is useful.

**Comment by unkn0wn404** [comment]
Hope ID translation also will work for graph name and variables templates. It will be awesome.

**Comment by IzakMarais** [comment]
@unkn0wn404 could you clarify what you mean? 
Current it works only in the Legend Alias, but there it can wrap a template variable, so that should work.
Graph name is not something we need but I could consider adding it.

**Comment by IzakMarais** [comment]
I added unit tests as well as support for template variable. This allows the displayed template variable text to be treated as IDs and replaced with their names. The underlying template variable values are unaffected.

Also, it only replaces text for template variables present in the ID map database. In the example below, only 3 variables have name mappings.

![template variable map](https://cloud.githubusercontent.com/assets/8266640/11331407/151e5072-91c3-11e5-8a38-4ad755f91216.gif)

Here it is in action for the legend aliases:

![legend alias map](https://cloud.githubusercontent.com/assets/8266640/11331412/2876133a-91c3-11e5-814e-8f6bffc0aa4b.gif)

Next up: graph titles.

**Comment by unkn0wn404** [comment]
@IzakMarais i means graph title, and as i see on your demo you already done it.
Also ID mapping will work on dropdown variables list?
I means something like variable $user [1,2,3,4] -> $user [name1,name2,name3,name4]

**Comment by IzakMarais** [comment]
Thanks for clarifying. 

> Also ID mapping will work on dropdown variables list?

Yes, that is what the first of the above two demos show (the description of the demo is _above_ it). 

>  i means graph title

I am currently working on graph title.

**Comment by IzakMarais** [comment]
### ID mapping for graph titles

![title map](https://cloud.githubusercontent.com/assets/8266640/11368815/7054f0e8-92c4-11e5-8383-19ed5412235a.gif)

Will submit a pull request tomorrow.

**Comment by IzakMarais** [comment]
Please vote (+1) this issue if you will find it useful, my PR is [still being considered, pending more interest from the community.](https://github.com/grafana/grafana/pull/3334#issuecomment-170467484)

**Comment by thomas-tomlinson** [comment]
As long as it's something that applies to more than just the ElasticSearch data source +1 for me.  Would be extremely helpful in graphing items such as network switch ports where the description text could be pulled from a external source.

**Comment by adrianlzt** [comment]
+1

**Comment by GautamGupta** [comment]
+1

**Comment by jan-pieter** [comment]
This would indeed be a nice feature. Currently I'm using a workaround by using a Chrome extension ([Word Replacer II](https://chrome.google.com/webstore/detail/word-replacer-ii/djakfbefalbkkdgnhkkdiihelkjdpbfh)) to replace the ID's with the names.

**Comment by hzhzh007** [comment]
＋1

**Comment by kmacmcfarlane** [comment]
+1

**Comment by wojciechszela** [comment]
+1

**Comment by aleung** [comment]
+1

**Comment by tsupertramp** [comment]
+1

**Comment by lucadistefano** [comment]
+1
tag names can change but id remains!

**Comment by polynomial** [comment]
+1

**Comment by scottglazier** [comment]
+1

**Comment by noahjohnhay** [comment]
+1

**Comment by hilljmd** [comment]
+1

**Comment by yossale** [comment]
+1

**Comment by schnell18** [comment]
+1

**Comment by Hypfer** [comment]
So is there a solution for this issue?

**Comment by IzakMarais** [comment]
I'm afraid not, as far as I know. 

My PR wasn't accepted since it added too much complexity. I've moved on to other things, so my fork hasn't been updated to Grafana 4.0. 

My employer tried to get this prioritised for development via Grafana commercial support. However,  the complexity of implementing this properly outweighed its priority.

**Comment by gekr** [comment]
+1

**Comment by gtaspider** [comment]
Is there any chance we see this in future builds? I implemented a version on my own which adds the name to the InfluxDB database, but this feels kind of stupid to me... A similar request has been made here and a lot of upvotes:
https://github.com/grafana/grafana/issues/1032
Thanks

**Comment by g00g1e** [comment]
I need this feature.

**Comment by alsbi** [comment]
+1

**Comment by tony38000** [comment]
need this great feature too

**Comment by dorachan2000** [comment]
+1

**Comment by BlackRider97** [comment]
+1

**Comment by WestFarmer** [comment]
any updates on this?

**Comment by praetp** [comment]
when can we see this submitted ?

**Comment by Tairy** [comment]
+1

**Comment by hexuallyactive** [comment]
+1

**Comment by Hypfer** [comment]
You do realize that everyone receives an email each time of you writes `+1`

Cease.

**Comment by alamsyahho** [comment]
+1 would be really useful to have this feature

**Comment by ljs617966244** [comment]
+1

**Comment by harlam** [comment]
+1

**Comment by kenny-heyi** [comment]
+1

**Comment by shay-berman** [comment]
We also need such feature.
@torkelo  - any timeline for this feature?

**Comment by Ldsystem** [comment]
+1

**Comment by franck102** [comment]
Very useful feature, and hopefully this would work for multi-value variables. Today a Prometheus query such as
sum by ($groups) ...
... uses the Prometheus labels in the legend:
{complex_prometheus_label_name="foo",other_complex_prometheus_name="bar"}

It would be great to have __text used in that legend.

**Comment by slavon4ever** [comment]
+1

**Comment by larytet** [comment]
Browser plugin like GreaseMonkey and a user script could do the trick for a specific case.

**Comment by raiden2012** [comment]
+1

**Comment by astohs** [comment]
+1

**Comment by joneepenk** [comment]
+1

**Comment by atellier** [comment]
I really need this feature as well, as we use code / ids for our labels, and would like to display their friendly names in the legend instead. I can have it hardcoded or from database. I have looked at transformations, read all the issues, etc.... but have not found a way to that.
Anybody succeeded to "hack" a solution until we *hopefully* get official support for that? I will take it for now!
Thanks

**Comment by MikaelElkiaer** [comment]
I am also looking for something to solve this. My current hacks consist of a "metadata" time series for Prometheus and a JSON API datasource for Grafana Loki.

I would love some Dashboard functionality for mapping values, across data sources and across various view elements.
