### ISSUE TITLE
Allow dynamic titles when using repeated panels/rows

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#11534]
Currently, there's is no way to set the title value to something else than static text or variable.

The problem is that when using repeated panels/rows, there's no way to set dynamic value into title other than $variable that is being repeated by.

So far, I haven't found a easy way how to repeat by one value and display other related value in row/panel title with Postgres datasource. I believe it's very similar with most of other datasources.

If I could for example enter query into title, it would be great.

**Comment by simPod** [comment]
This would work https://github.com/grafana/grafana/issues/1032

**Comment by shaharb-hs** [comment]
I don't understand how #1032 resolves this. I've put a variable in the title, but I see the variable only in the first panel. It is missing in the repeating panels.
