### ISSUE TITLE
[Feature Req] Org `Editor` should  be able to manage permissions/settings of a folder that they've created

### ISSUE THREAD

**Issue by pf23** [grafana/grafana#11542]
Suppose there is an org Editor. He creates a folder/dashboard, wanner add some teams/users to manage the folder/dashboard. At this time, there are 3 alternatives, he
* is allowed to do so by himself, by granting him admin role to what he created, and keeping his org role unchanged,
* asks an org Admin for permission (not preferred I suppose)
* isn't allowed to have this kind of right, which means he can create but not able to manage permissions on what he created.

I advise to grant the creator admin permission to the folders/dashboards they created (their org roles remain unchanged), so that they can manage them without bothering an org.

Please check #11173 for more details.

**Comment by pf23** [comment]
#11173

**Comment by marefr** [comment]
I think this request are valid. It's not consistent if an editor can create a folder, but after this have no possibility to edit settings or permissions for it. Feels like this should be the default even if there may be users that won't have it like this.

**Comment by marefr** [comment]
We probably want to add a permission for the creator of the folder with admin permissions. A bit work here since we need to take care of the implicit inheritance of permissions.

**Comment by xlson** [comment]
Implemented in #15977
