### ISSUE TITLE
Startup script returns error on starting grafana (debian official docker image)

### ISSUE THREAD

**Issue by danielllek** [grafana/grafana#11545]
Official debian stretch docker image comes without systemd.
Grafana startup script returns error on such system (although grafana starts normally).

```
# /etc/init.d/grafana-server start
[FAIL] Starting Grafana Server: failed!
# tail -4 /var/log/grafana/grafana.log
t=2018-04-10T11:30:59+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-04-10T11:30:59+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-04-10T11:30:59+0000 lvl=info msg="Initializing Stream Manager"
t=2018-04-10T11:30:59+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

If I install systemd, script ends as expected:

```
# /etc/init.d/grafana-server start
[ ok ] Starting Grafana Server:.
```

Another minor problem, scripts hangs for 25 seconds when stopping grafana (with or without systemd):

```
# time /etc/init.d/grafana-server stop
[ ok ] Stopping Grafana Server:.

real        0m25.074s
user        0m0.060s
sys        0m0.205s
```

Grafana 5.0.4 on Debian GNU/Linux 9.4 (stretch) (official debian docker image)

**Comment by torkelo** [comment]
I do not think this is systemd related, as we have run the deb on old non systemd system for ages without issues. Probably something missing in the docker image. Anyway we stopped using the deb package for docker image so this should not be relevant anymore
