### ISSUE TITLE
[Feature Request] playlist looping through the (custom) variables list

### ISSUE THREAD

**Issue by foxmask** [grafana/grafana#11546]
### What Grafana version are you using?  Grafana v5.0.4 
(commit: 7dc36ae) 
### What datasource are you using? 
default
### What OS are you running grafana on? 
linux

### Details 
With a playlist, made of one dashboard, I'd like to be able to loop through the list of the custom variables I made.

**Comment by iDemonix** [comment]
+1

**Comment by bergquist** [comment]
dupe of https://github.com/grafana/grafana/issues/773

**Comment by foxmask** [comment]
nice !
