### ISSUE TITLE
[Feature Request] Allow the simplejson datasource /annotations api to associate a time range to an annotation

### ISSUE THREAD

**Issue by alsterg** [grafana/grafana#11549]
According to documentation at https://github.com/grafana/simple-json-datasource, this datasource doesn't seem to support associating a time range to an annotation, albeit Grafana native annotations do.

It would be nice to have the ability to generate annotations like this:
```
[
  {
    annotation: annotation, // The original annotation sent from Grafana.
    time_from: time, // Time since UNIX Epoch in milliseconds. (required)
    time_until: time, // Time since UNIX Epoch in milliseconds. (required)
    title: title, // The title for the annotation tooltip. (required)
    tags: tags, // Tags for the annotation. (optional)
    text: text // Text for the annotation. (optional)
  }
]
 ```

**Comment by bergquist** [comment]
This issue should be opened at https://github.com/grafana/simple-json-datasource
