### ISSUE TITLE
Built in template variable that contains the full range in Prometheus

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#11544]
I have a Prometheus database from which I wish to expose singlestat metrics of the form "average value over entire window".

Right now, I can do this using the query `my_metric{foo = "bar"}` and selecting "Average" as the mode from the singlestat panel.

This is okay but sometimes I want Prometheus to calculate the value, using an instant query, and to just have Grafana display this value. In other words, I want a query like `avg_over_time(my_metric{foo = "bar"}[1h])"`, where the "1h" is equal to the size of the Grafana data window (`to - from`). 

I request that a variable be exposed for this.

**Comment by sandersaares** [comment]
If I understand it right, this feature is also mentioned in the comments of https://github.com/grafana/grafana/issues/7664

**Comment by roidelapluie** [comment]
$__range is implemented

**Comment by davkal** [comment]
`$__range` is indeed implemented.
