### ISSUE TITLE
Send daily 'reports' to Slack, email, etc

### ISSUE THREAD

**Issue by brylie** [grafana/grafana#11558]
In addition to alerting, it would be useful to have daily summary reports sent to communication channels such as Slack or email. For example, a single chart or dashboard render would be sent to a Slack channel every morning at 8am (UTC).

# Feature request
Allow users to schedule sending 'reports' to supported communication channels.

**Comment by andrewb-ms** [comment]
Any update on this?

**Comment by aocenas** [comment]
I think at this moment this is only enterprise feature is that right @xlson ? Not sure though if it can report to slack and even if so if it make sense to keep this request for OSS or not.

**Comment by xlson** [comment]
@aocenas This is correct. We can close it for now.

**Comment by davidnewhall** [comment]
As an enterprise customer, this is exactly what I'm after. 
> Allow users to schedule sending 'reports' to ~~supported communication~~ configured notification channels.

Right now I can only send reports to email addresses, and I really want them in Slack.
