### ISSUE TITLE
Scientific unit prefix doesn't seem to work below unity

### ISSUE THREAD

**Issue by victorclaessen** [grafana/grafana#11559]
### What Grafana version are you using?
v5.1.0-pre1 (commit: 9e1a1ed57)
### What datasource are you using?
MySQL
### What OS are you running grafana on?
Debian 9 x64
### What did you do?
I updated to the latest 5.1.0 pre-version to test out the new radiation units (from #11001). I made a graph with a MySQL datasource behind it. The data consists of fractional numbers as values. I set the axis unit to Sv/h. The data in the table is stored with a unit of µSv/h, so I divide the value field by 1E6 in the query.
### What was the expected result?
I was expecting values in the 10<sup>-6</sup> range to be labelled with µSv/h (_i.e._ the prefix **µ** for micro to be added to the unit).
### What happened instead?
The prefix was not added. Instead, the labels seem to be a mix of scientific formatting (5e-7 Sv/h) and "short" formatting (0.0000010 Sv/h). See the attached screenshot.

![prefix units](https://user-images.githubusercontent.com/11179036/38614736-6de8e432-3d8e-11e8-8cf0-efb1bdbe5666.png)

I have made other graphs with radiological units, and in cases where the values are above unity, the prefixes ARE added. If I multiply the values in this table by 1E6, then I get a plot with **M**Sv/h (prefix **M** added for **mega**sievert per hour) as expected. So it seems like a bug that it wouldn't add the µ prefix when the values are small. _Please note that this is just a fictional example, we do not measure (or generate) megasieverts per hour, that would be...eh...somewhat distressing._

#### request

`{"from":"1523436774011","to":"1523447574011","queries":[{"refId":"A","intervalMs":30000,"maxDataPoints":386,"datasourceId":2,"rawSql":"SELECT\n  date_sub(timestamp, interval 2 hour) as time_sec,\n  value/1e6 as value,\n  'FTA' as metric\nFROM log_armd1\nWHERE $__timeFilter(timestamp)\nORDER BY timestamp ASC\n","format":"time_series"},{"refId":"B","intervalMs":30000,"maxDataPoints":386,"datasourceId":2,"rawSql":"SELECT\n  date_sub(timestamp, interval 2 hour) as time_sec,\n  value/1e6 as value,\n  'Vault' as metric\nFROM log_armd2\nWHERE $__timeFilter(timestamp)\nORDER BY timestamp ASC\n","format":"time_series"},{"refId":"C","intervalMs":30000,"maxDataPoints":386,"datasourceId":2,"rawSql":"SELECT\n  date_sub(timestamp, interval 2 hour) as time_sec,\n  value/1e6 as value,\n  'FELICE Hall' as metric\nFROM log_armd3\nWHERE $__timeFilter(timestamp)\nORDER BY timestamp ASC","format":"time_series"}]}`

#### response (partial)

 ```
{"results":{"A":{"refId":"A","meta":{"rowCount":1971,"sql":"SELECT\n  date_sub(timestamp, interval 2 hour) as time_sec,\n  value/1e6 as value,\n  'FTA' as metric\nFROM log_armd1\nWHERE timestamp \u003e= FROM_UNIXTIME(1523436774) AND timestamp \u003c= FROM_UNIXTIME(1523447574)\nORDER BY timestamp ASC\n"},"series":[{"name":"FTA","points":[[0.00000155,1523443317000],[0.0000017,1523443319000],[0.00000159,1523443321000],[0.00000149,1523443323000],[0.00000164,1523443325000],[0.00000148,1523443328000],[0.0000016299999999999999,1523443330000],[0.00000152,1523443332000],[0.0000016699999999999999,1523443334000],[0.00000156,1523443336000],[0.00000171,1523443338000],[0.0000016000000000000001,1523443340000],[0.00000149,1523443343000],[0.00000159,1523443345000],[0.00000148,1523443347000],[0.0000016299999999999999,1523443349000],[0.00000153,1523443351000],[0.00000168,1523443353000],[0.00000157,1523443355000],[0.00000147,1523443358000],
.... part removed to keep the size of this post reasonable ...
[0.000000050999999999999993,1523447543000],[0.000000048,1523447545000],[0.000000044,1523447547000],[0.00000028899999999999995,1523447549000],[0.000000261,1523447551000],[0.000000244,1523447554000],[0.000000228,1523447556000],[0.000000213,1523447558000],[0.00000019900000000000002,1523447560000],[0.000000186,1523447562000],[0.00000016800000000000002,1523447564000],[0.000000157,1523447566000],[0.00000014699999999999998,1523447569000],[0.00000013700000000000002,1523447571000],[0.000000128,1523447573000]]}],"tables":null}}}

```

**Comment by vhartong** [comment]
I am also encountering this problem, but I would like to describe it more generic:
Scientific notation comes in handy when a number is really big or really small, say 0.0000012345 = 1.2345e-6. When selecting the scientific notation, grafana shows the number as 1.2345e-6. When selecting the option to have less numbers behind the decimal sign, say two, it will first remove the decimal values that are not requested and then convert it in scientific notation. 
Hence 0.0000012345 => 0.00 => 0e0 instead of showing 1.23e-6. It sort of defeats the purpose of having scientific notation.

**Comment by victorclaessen** [comment]
So in this location I see that the function decimalSIPrefix is referenced.

https://github.com/grafana/grafana/blob/ec6d69f468db48efb322059858e21c563301094a/packages/grafana-ui/src/utils/valueFormats/categories.ts#L267

I find the definition for this function here:

https://github.com/grafana/grafana/blob/b05afd7e4e57811149505d4b35c2ae4f9e59aab5/packages/grafana-ui/src/utils/valueFormats/symbolFormatters.ts#L25

I'm entirely sure how this code is intended (perhaps one of the developers can assist?) but I see at least some sub-unity-prefixes (nano, micro, milli) defined. However, if that function does not get an offset, those sub-unity-prefixes get sliced off the array, and will never actually be used. 

For instance in the case of pressure, one of the formats is _millibars_, and that is defined with an offset of -1 `decimalSIPrefix('bar', -1) `.

So it seems the way it works now is that you have to define the smallest possible prefix you are expecting, and then scale your data by that prefix. Example: If I want to show my radiation data (values ranging from µSv to Sv) and I want to be able to show the µ prefix, I should change 
https://github.com/grafana/grafana/blob/ec6d69f468db48efb322059858e21c563301094a/packages/grafana-ui/src/utils/valueFormats/categories.ts#L273
to `{ name: 'microSievert (µSv)', id: 'radsv', fn: decimalSIPrefix('Sv', -2) },`
and then multiply my data by E-6. If I were to do that, then probably units would correctly change from µSv to mSv to Sv on increasing values.

That doesn't really seem like the best way to do it, right? It would seem more logical/practical to me to have the format definition in the base unit (Sv in this case) and not in the smallest prefix that you expect. Surely, there will come someone else after me wants nanoSieverts...and then we'd have to change the format definition again (and scale our data by E-9).

**Comment by torkelo** [comment]
units are defined in the base unit (how Grafana should interpret source value), and looks like it works as intended

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/20144
