### ISSUE TITLE
Docs feedback: features/datasources/mssql.md

### ISSUE THREAD

**Issue by dominicrusso** [grafana/grafana#11562]
In the documentation for Using Microsoft SQL Server in Grafana:

Under Data source options, the Host option states that if a port is omitted, default 1443 will be used. Typically the default for MSSQL is 1433 NOT 1443. I believe this may be a typo that could confuse a lot of users!

**Comment by marefr** [comment]
Thanks for reporting this! Fixed and published. Will take a few minutes before you'll see any changes.
