### ISSUE TITLE
DB Migration Failures -- migrating from local sqlite to RDS Auora (MySQL)

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#11564]
### What Grafana version are you using?
5.x

### What datasource are you using?
mysql

### What OS are you running grafana on?
MacOS

### What did you do?
Modified `custom.ini` from sqlite to mysql configuration

### What was the expected result?
Migration would initiate and complete successfully 

### What happened instead?
Portions of the migration fail (dashboards and datasources no longer loaded)

### DEBUG output of startup:

```
DBUG[04-11|14:58:06] Skipping migration: Already executed     logger=migrator id="create index UQE_org_user_org_id_user_id - v1"
DBUG[04-11|14:58:06] Executing                                logger=migrator sql="INSERT INTO `org` (`updated`\n, `id`\n, `version`\n, `name`\n, `created`) SELECT `updated`\n, `id`\n, `version`\n, `name`\n, `created` FROM `account`"
INFO[04-11|14:58:06] Executing migration                      logger=migrator id="copy data account to org"
INFO[04-11|14:58:06] Skipping migration condition not fulfilled logger=migrator id="copy data account to org"
DBUG[04-11|14:58:06] Executing                                logger=migrator sql="INSERT INTO `org_user` (`id`\n, `org_id`\n, `user_id`\n, `role`\n, `created`\n, `updated`) SELECT `id`\n, `account_id`\n, `user_id`\n, `role`\n, `created`\n, `updated` FROM `account_user`"
INFO[04-11|14:58:07] Executing migration                      logger=migrator id="copy data account_user to org_user"
INFO[04-11|14:58:07] Skipping migration condition not fulfilled logger=migrator id="copy data account_user to org_user"
DBUG[04-11|14:58:07] Skipping migration: Already executed     logger=migrator id="Drop old table account"
```
 
I can access the service, but I don't have any of my old dashboards -- I had to recreate my primary org (I had deleted the Main Org. before). Datasources from my .yaml no longer automatically load on startup either.

**Comment by torkelo** [comment]
Can you show the complete log?

**Comment by daniellee** [comment]
Don't see the bug here. If you switch database then you will have to manually migrate your data to the new database. Grafana doesn't do any magic in this case.

Closing - as there has been no response for > 3 weeks and it does not look like a bug.
