### ISSUE TITLE
Add new property that include all non matching series to alert notifications

### ISSUE THREAD

**Issue by bluefish6** [grafana/grafana#11560]
Feature request: add `evalNotMatches` or `evalResults` in alerting JSONs

### What OS are you running grafana on? Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1052-aws x86_64)
As mentioned in the other issue (link at the bottom), it would be nice to have information about the measured values not only when getting a "ALERTING" alert, but also when getting a "OK" alert as well (in JSON sent on state change via webhook).

See examples:
1) The "state history" shows only the "incorrect" metrics, but omits the "ok" metrics when the state is changed to "OK"

![image](https://user-images.githubusercontent.com/3324881/38616349-083a0822-3d94-11e8-8f8d-946918db86c3.png)

2) The JSONs sent in ALERTING state are correct:

```
{
'state': 'alerting',
'ruleId': 21,
'ruleName': 'Metrics (Influx) server - CPU usage alert',
'ruleUrl': 'http://localhost:3000/d/000000007/alerts-app-start-here?fullscreen=true&edit=true&tab=alert&panelId=14&orgId=1',
'evalMatches': [{'value': 100, 'tags': None, 'metric': 'cpu_usage'}],
'title': '[Alerting] Metrics (Influx) server - CPU usage alert'}
```

but omit the newly measured value in the OK JSON:

```
{
'state': 'ok',
'ruleId': 21,
'ruleName': 'Metrics (Influx) server - CPU usage alert',
'ruleUrl': 'http://localhost:3000/d/000000007/alerts-app-start-here?fullscreen=true&edit=true&tab=alert&panelId=14&orgId=1',
'evalMatches': [],
'title': '[OK] Metrics (Influx) server - CPU usage alert'
}
```

Currently the evalMatches shows the values that triggered the alert, but does not show values when the state is changed to OK (as no values match the alerting rules anymore).

The proposed solution is one of the following:

* introduce `evalNotMatches` field which would include all the metrics that were NOT evaluated as resulting in an alert.
* AND/OR introduce `evalResults` field which would include all the metrics, regardless of their evaluation result.

The source issue and the source comment is here:
https://github.com/grafana/grafana/issues/7001#issuecomment-380189986

**Comment by rnsc** [comment]
Hi, is anyone working on this currently in the Grafana team?
Not sure I can help, but I'd be happy to provide feedback on testing the implementation.

**Comment by bergquist** [comment]
This is not something we can support for all alert evaluations. When monitoring hundreds of machines this would be very verbose. 

But I think this could be supported for test evaluations in case the operator wants to verify the query.

**Comment by armandgrillet** [comment]
This is fixed in Grafana Alerting, the value is in the OK notifications.
