### ISSUE TITLE
Disable the ability for dashboard users to enter in arbitrary HTML content

### ISSUE THREAD

**Issue by jl98800** [grafana/grafana#11565]
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

This is a feature request. For security reasons - for us to continue using Grafana we need to be able to:

1. Disable the ability for dashboard users to enter in arbitrary HTML content (cross site scripting)
2. Restrict Grafana's dashboard editing of other dashboards (I believe v5 has ACLs for this)

**Comment by torkelo** [comment]
closing this as we already have an issue for this, 
https://github.com/grafana/grafana/issues/4117
