### ISSUE TITLE
Bug: Annotation limit showing wrong

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11569]
### What Grafana version are you using?
5.0.4
### What datasource are you using?
Influx
### What OS are you running grafana on?
Debian

Creating a new 15 graphs in a dashboard, setting up alert on each graph.
One day there should have been an alert on each graph, which I could see because the heart was red.
But I only had the red lert annotation line in 10 graphs, it should have been in all of them.
Checking settings and it was set to 100 annotations, I know that something a setting can show wrong so I changed it to 50 and directly I could see all 15 annotations as I was expecting.

So it seems to be set to 10 but in the setting it shows 100 as default

**Comment by torkelo** [comment]
thanks for reporting this, it appears the 100 limit is only defined in the UI when you create new annotations (or modify the existing auto generated one). 

The backend query default is 10:
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/annotation.go#L205

Easiest fix would be to change the backend default to also be 100
