### ISSUE TITLE
altering not Evaluate  exactly when i set by 24h

### ISSUE THREAD

**Issue by wg1026688210** [grafana/grafana#11568]
os :centos 7
version:5 
 i set Evalute every 24h at 9 a.m.   but it work at  8 p.m.  is it bug by timezone?

**Comment by torkelo** [comment]
you cannot control what time of day it will evaluate, it will evaluate every 24 hours. So if it was more than 24 hours since last evaluation it will evaluate (no matter what time of day)

**Comment by wg1026688210** [comment]
emm..but why not  evaluating every 24h means work 9 a.m.  next day  when  i set it at 9 a.m.                            i wanna find the regulation of the scheduler to report the some information which software running last day   .    i think it's a common needing for most of developers to report of software running  .could u help me

**Comment by wg1026688210** [comment]
should i mean set 1 day

**Comment by wg1026688210** [comment]
should i set 1d
