### ISSUE TITLE
Grafana 5.0.4 won't start on mysql SIGSEGV

### ISSUE THREAD

**Issue by mmajews** [grafana/grafana#11570]
Dear community,

We installed grafana 5.0.4 recently, and we stumbled upon the following issue...

### What Grafana version are you using?
5.0.4
### What datasource are you using?
Not relevant
### What OS are you running grafana on?
SLC6, a flavor of Red Hat 6
### What did you do?
I installed grafana 5.0.4, configured it to connect to a mysql instance, and started the server
### What was the expected result?
The server should start, the database schema should be created
### What happened instead?

t=2018-04-12T10:11:52+0200 lvl=info msg="Starting Grafana" logger=server version=5.0.4 commit=7dc36ae compiled=2018-03-28T13:52:41+0200
t=2018-04-12T10:11:52+0200 lvl=info msg="Config loaded from" logger=settings file=/opt/grafana/grafana-5.0.4/conf/defaults.ini
t=2018-04-12T10:11:52+0200 lvl=info msg="Path Home" logger=settings path=/opt/grafana/grafana-5.0.4
t=2018-04-12T10:11:52+0200 lvl=info msg="Path Data" logger=settings path=/opt/grafana/grafana-5.0.4/data
t=2018-04-12T10:11:52+0200 lvl=info msg="Path Logs" logger=settings path=/opt/grafana/grafana-5.0.4/data/log
t=2018-04-12T10:11:52+0200 lvl=info msg="Path Plugins" logger=settings path=/opt/grafana/grafana-5.0.4/data/plugins
t=2018-04-12T10:11:52+0200 lvl=info msg="Path Provisioning" logger=settings path=/opt/grafana/grafana-5.0.4
t=2018-04-12T10:11:52+0200 lvl=info msg="App mode production" logger=settings
t=2018-04-12T10:11:52+0200 lvl=info msg="Initializing DB" logger=sqlstore dbtype=mysql
t=2018-04-12T10:11:52+0200 lvl=eror msg=ShowSQL logger=sqlstore.xorm show=show
t=2018-04-12T10:11:52+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2018-04-12T10:11:52+0200 lvl=info msg="[SQL] SELECT `TABLE_NAME` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? and `TABLE_NAME`=? []interface {}{\"grafana\", \"migration_log\"} - took: 68.676µs" logger=sqlstore.xorm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d4c97]

goroutine 22 [running]:
crypto/tls.(*Config).Clone(0x0, 0x6)
	/usr/local/go/src/crypto/tls/common.go:550 +0x37
github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql.cloneTLSConfig(0x0, 0xc420208c00)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql/utils_go18.go:21 +0x2b
github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql.getTLSConfigClone(0xc4205280a1, 0x6, 0xc4205280a1)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql/utils.go:81 +0xa6
github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql.parseDSNParams(0xc42013b980, 0xc420528066, 0x41, 0xc4205cb398, 0x418668)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql/dsn.go:545 +0x448
github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql.ParseDSN(0xc420528000, 0xa7, 0xc42016a3c0, 0xc4205cb578, 0x18)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql/dsn.go:377 +0x281
github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql.MySQLDriver.Open(0xc420528000, 0xa7, 0x0, 0x0, 0xc4201c4c00, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql/driver.go:62 +0xe6
github.com/grafana/grafana/vendor/github.com/go-sql-driver/mysql.(*MySQLDriver).Open(0x2168710, 0xc420528000, 0xa7, 0x40, 0x4, 0x4, 0xb)
	<autogenerated>:1 +0x48
database/sql.(*DB).conn(0xc4201897c0, 0x1f88020, 0xc420016088, 0x1, 0x10, 0xc4202f6a70, 0x7ff61e4928c8)
	/usr/local/go/src/database/sql/sql.go:999 +0x130
database/sql.(*DB).query(0xc4201897c0, 0x1f88020, 0xc420016088, 0x148c463, 0x60, 0xc42015f260, 0x2, 0x2, 0x1, 0x30, ...)
	/usr/local/go/src/database/sql/sql.go:1299 +0x66
database/sql.(*DB).QueryContext(0xc4201897c0, 0x1f88020, 0xc420016088, 0x148c463, 0x60, 0xc42015f260, 0x2, 0x2, 0xc4205cb910, 0x418668, ...)
	/usr/local/go/src/database/sql/sql.go:1281 +0xd2
database/sql.(*DB).Query(0xc4201897c0, 0x148c463, 0x60, 0xc42015f260, 0x2, 0x2, 0xc42019c6c0, 0xc4205cb990, 0x40)
	/usr/local/go/src/database/sql/sql.go:1295 +0x82
github.com/grafana/grafana/vendor/github.com/go-xorm/core.(*DB).Query(0xc42015e880, 0x148c463, 0x60, 0xc42015f260, 0x2, 0x2, 0x2, 0x2, 0xc4203fec80)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/core/db.go:79 +0x73
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).queryRows(0xc4203fec80, 0x148c463, 0x60, 0xc42015f260, 0x2, 0x2, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session_raw.go:71 +0x3d9
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).queryBytes(0xc4203fec80, 0x148c463, 0x60, 0xc42015f260, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session_raw.go:142 +0xa3
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).isTableExist(0xc4203fec80, 0xc4202f6a70, 0xd, 0xc4202f6a70, 0xd, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session_schema.go:170 +0x93
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).IsTableExist(0xc4203fec80, 0x115e500, 0xc420098c00, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session_schema.go:165 +0xbd
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Engine).IsTableExist(0xc4201b2160, 0x115e500, 0xc420098c00, 0x2168700, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/engine.go:1077 +0x93
github.com/grafana/grafana/pkg/services/sqlstore/migrator.(*Migrator).GetMigrationLog(0xc420168440, 0x145ab4a, 0x15, 0x0)
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/migrator/migrator.go:51 +0x10a
github.com/grafana/grafana/pkg/services/sqlstore/migrator.(*Migrator).Start(0xc420168440, 0xc420168440, 0x1f90000)
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/migrator/migrator.go:77 +0x8d
github.com/grafana/grafana/pkg/services/sqlstore.SetEngine(0xc4201b2160, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/sqlstore.go:101 +0xb3
github.com/grafana/grafana/pkg/services/sqlstore.NewEngine()
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/sqlstore.go:86 +0x116
main.initSql()
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:102 +0x20
main.(*GrafanaServerImpl).Start(0xc4202c7b00, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:59 +0x6e
main.main.func2(0xc4202c7b00)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:89 +0x2f
created by main.main
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:87 +0x2c5

### Here is the config snippet (hiding critical information ...):

[database]
type = mysql
host = <hostname>:<port>
name = grafana
user = <username>
password = """<userpassword>"""

ssl_mode = skip-verify

ca_cert_path = /etc/pki/tls/private/privkeygrafana.pem
client_key_path =
client_cert_path =
server_cert_name =

log_queries=true

**Comment by bergquist** [comment]
this is reproducible locally. generate a dummy pem file and set `ssl_mode` to `skip-verify`.

**Comment by bergquist** [comment]
Wouldnt you want to supply a client cert and client key as well?

**Comment by mmajews** [comment]
It is the same with dumy file. I am pretty sure that we do need to supply client cert and client key, it was working like this before and nothing on the database level changed.

**Comment by mmajews** [comment]
BTW we used PostgreSQL and it seems to be working fine, but with mysql it is still strange issue.

**Comment by mmajews** [comment]
Unfortunately we do not have time to investigate it more (we can stick with PostgreSQL), so I am closing the issue.
