### ISSUE TITLE
Deleted users not removed from user table

### ISSUE THREAD

**Issue by choppedpork** [grafana/grafana#11573]
I'm seeing the same issue as originally described in #3265 - that one is closed now so opened a new one but feel free to close this one and I can just move my comment there, wasn't sure if you'd be happy with resurrecting a ticket that has been closed for 3 years now :).

The way I stumbled upon this is when our LDAP instance got migrated, some usernames have been changed and none of those users are able to log in due to the unique email constraint. I've deleted one of the users from the Grafana UI but they're still unable to log in. I'm using SQLite for storage, have had a look in the database and the user has indeed not been deleted from the `users` table but is no longer visible in the UI.

I'm running the official 5.0.4 Docker image (on Ubuntu 16.04 / Docker 17.12.1), grafana.ini is all set to defaults except for the following environment variable overrides:
```
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_LDAP_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=x
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_SERVER_ROOT_URL=x
      - GF_AWS_PROFILES=default
      - GF_AWS_default_ACCESS_KEY_ID=x
      - GF_AWS_default_SECRET_ACCESS_KEY=x
      - GF_AWS_default_REGION=x
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=x
      - GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET_URL=x
      - GF_EXTERNAL_IMAGE_STORAGE_S3_ACCESS_KEY=x
      - GF_EXTERNAL_IMAGE_STORAGE_S3_SECRET_KEY=x
```
Here's the deleted users row I found in SQLite (name / email obscured):
```
43|0|user|user@company.com|User|||||1|0|0||2017-09-04 13:51:37|2017-09-04 13:51:37|0|2018-04-12 09:34:41
```
Not sure if this is relevant but this Grafana instance has probably originally deployed as 2.x and happily upgraded since. The original ticket states this works as expected in 2.5 - I'm wondering if maybe there's some migration that somehow didn't get applied correctly? Let me know if there's anything else I could dig out from the database that could be helpful.

**Comment by bergquist** [comment]
Hm. Did you remove them from org page (`/org/users`) or server admin page (`/admin/users`)?

If you remove a user from the org page it still exists on the server since that user can belong to multiple orgs. To completely remove a user you need to remove them from the admin page.

**Comment by choppedpork** [comment]
Thanks @bergquist - what I've done was going through to the cog menu on the left -> Users. This does indeed take me to /org/users. I've spent a few minutes trying to find the server admin page but I don't seem to be able to and when I amend the browser URL to /admin/users I just get redirected to the home page. Would I need to be a non-LDAP user to access this?

**Comment by bergquist** [comment]
@choppedpork then your not logged in as grafana admin. To completly delete users you need to grafana admin access. 

This is quite... confusing. we are aware :)

Hopefully this wont be a problem once we merged the auth refactoring to not only relay on email as unique identifier for ldap. https://github.com/grafana/grafana/pull/11354

**Comment by choppedpork** [comment]
Ah brilliant, thanks! Confusing indeed but that's all cleared up now. The admin UI seems to be broken when I log in (missing menus in the left-hand pane, empty list after navigating to `/admin/users`) but now that I understand where the issue is I can just drop all the affected users from SQLite and patiently wait for the external auth refactor. Thanks a lot @bergquist - I think this is quite likely to be the cause of the other reports in #3265 too.
