### ISSUE TITLE
Postgres time macros can cause unusable performance degradation on Redshift

### ISSUE THREAD

**Issue by nrmitchi** [grafana/grafana#11578]
### What Grafana version are you using?
v5.0.4
### What datasource are you using?
Postgres -> Redshift

### What did you do?
Used the `$__timeGroup` and `$__timeFilter` macros. They destroyed query performance.

In #9570, the format of the time macros was modified to support Redshift (implying that Redshift support is at least a partial goal here). Note that there was also a concern mentioned on the PR regarding performance.

In #9527, it was also modified to use a format of `"extract(epoch from %s) BETWEEN %d AND %d"`. From a performance point of view, this is horrendous against Redshift.

I have a pretty simple use case right now, with a query along the lines of:
```
SELECT 
    date_trunc('minute', requesttime),
    count(requestid),
    percentile_cont(0.5) WITHIN GROUP (ORDER BY backendprocessingtime asc) as "p50",
    percentile_cont(0.95) WITHIN GROUP (ORDER BY backendprocessingtime asc) as "p95",
    percentile_cont(0.99) WITHIN GROUP (ORDER BY backendprocessingtime asc) as "p99"
  FROM 
    logs
  WHERE 
    requesttime > getdate() - interval '1 hour' AND
    requesttime < getdate()
  GROUP BY
    1
  ORDER BY 
    1
```
> This typically returns in ~200ms.

```
--- With macro use ($__timeFilter):
SELECT 
    date_trunc('minute', requesttime),
    count(requestid),
    percentile_cont(0.5) WITHIN GROUP (ORDER BY backendprocessingtime asc) as "p50",
    percentile_cont(0.95) WITHIN GROUP (ORDER BY backendprocessingtime asc) as "p95",
    percentile_cont(0.99) WITHIN GROUP (ORDER BY backendprocessingtime asc) as "p99"
  FROM 
    logs
  WHERE 
    extract(epoch from requesttime) BETWEEN 1523538900 AND 1523549700
  GROUP BY
    1
  ORDER BY 
    1
```
> This never completed, and used close to 100% CPU

When using the time macros, and Grafana writes the query to extracts epochs from all of the times, simply for the comparison, appears to:
 1) Make any sort keys on the Redshift tables completely useless
 2) Drastically increase Redshift CPU

In the end, this led to the query not completing after 5 and a half minutes with nearly 100% CPU (at which point I had to kill it). Noting that the grafana request timeout seems to be 1m, this was not usable.

I propose that the macros stop either stop using epochs (at least in the $__timefilter macro), or make this configurable in some way/shape/form. It is likely relatively okay to continue the epoch use in the $__timeGroup macro, as at that point you will likely be dealing with a much smaller data set, and it does give nice results (such as arbitrary time groupings).

Currently as a work-around I've had to avoid using the group macros, which means my charts wont respect time selectors and such. It's working for now, but I'm hoping we can get this resolved in a way that reasonably works on redshift.

**Comment by marefr** [comment]
Fixed in #11592
