### ISSUE TITLE
feature request: fixed top bar

### ISSUE THREAD

**Issue by stapelberg** [grafana/grafana#1158]
When having many graphs in a dashboard, it’s inconvenient to scroll to the top in order to hit the refresh button. I suggest making the top bar static, so that it’s always visible.

What do you think?

**Comment by simple-snow** [comment]
Makes sense to me. +1

**Comment by stapelberg** [comment]
@torkelo I see that you’ve added the wontfix label. Can you explain the rationale behind that decision? Three users have expressed interest, and there doesn’t seem to be a downside to having this feature.

**Comment by torkelo** [comment]
well 3 users out of thousands. The main reason is that it does not seem needed and like a good idea, breaks some standard web behaviour,  encourages large/long dashboards
