### ISSUE TITLE
Add `Team Admin` role that can only can edit its own team.

### ISSUE THREAD

**Issue by drt-infor** [grafana/grafana#11584]
We would like to have the ability to designate a member(s) in a given Team as a "Team Admin" so that they could self-manage the ability to add/remove users to/from their Team.

We are currently running Grafana 5.0.3 in Docker containers on Linux.

**Comment by paulsson** [comment]
I would really like to see this implemented.  It would remove the need for the Org admin(s) to manage users for all Teams within the Org.
It would be best if this were a permission at the Team level vs the Org level.
ie. If I am an "admin" for 2 out of 5 Teams, I can only manage users for those 2 Teams.

**Comment by yijingping** [comment]
@drt-infor @paulsson  I have finished this feature on this pull request: https://github.com/grafana/grafana/pull/13144 , and waiting to be merged.
