### ISSUE TITLE
Docs feedback: guides/getting_started.md

### ISSUE THREAD

**Issue by BartNT** [grafana/grafana#11580]
Read before posting:

**Comment by BartNT** [comment]
The Getting Started documentation fails to explain how to start up after installation of the server. 
localhost:8080 requires a username | password, which is not documented in the Getting Started. Pitty, now it all stops.

**Comment by bergquist** [comment]
Thank you for your feedback. But I can't find any mentions of running something on port 8080 in the getting started docs. Could you be more explicit?

**Comment by BartNT** [comment]
The installation guide for W10 explains to set this port and how to start the server.

Where are the next steps explained to get the user side started?

The Getting started does not explain the first steps and assumes the user has started up in the browser somehow? Localhost:8080 is the obvious step from the installation instruction, but it would be better if this would be explained to get started. Next hurdle is not explained either: how to login?

Simple things that would avoid initial frustraitions and belief for newbies.

Hope this helps.


Kind regards,
Bart Netten - TNO

-----Original Message-----

**Comment by torkelo** [comment]
@Ijin08 can you take a look at this? 

I think we should add a "Logging in" section to each install guide that describes open browser to default address & port & login with admin/admin. Then link to Getting started guide. 

getting started guide should start with a logging in section, same as in each install guide. Then describe Gow you add a data source & create your first dashboard.
