### ISSUE TITLE
valriable select problem

### ISSUE THREAD

**Issue by merturl** [grafana/grafana#11597]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
i building from source code of "Commits on Apr 14, 2018"
### What datasource are you using?
influxDB 1.5.1
### What OS are you running grafana on?
windows10
### What did you do?
select another options of variable
### What was the expected result?
select another option of variable
### What happened instead?
not selected and console printed error
![image](https://user-images.githubusercontent.com/23473356/38789178-7962e964-4173-11e8-9634-690fc3994cbb.png)
![image](https://user-images.githubusercontent.com/23473356/38789140-4410fc10-4173-11e8-8f6a-73d6242a8e09.png)

**Comment by bergquist** [comment]
Could you please share the templating query and any network requests send for that query?

**Comment by merturl** [comment]
this is my templating query
<img width="557" alt="query" src="https://user-images.githubusercontent.com/23473356/38796159-83042236-4195-11e8-89f5-21c37bf8375b.PNG">

request,response
Request URL: http://localhost:3000/api/datasources/proxy/1/query?db=PGK07007_CTC&q=show%20field%20keys&epoch=ms
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:3000
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-cache
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 16 Apr 2018 07:44:57 GMT
Expires: -1
Pragma: no-cache
Request-Id: 0f294ecf-414a-11e8-9f72-000000000000
Transfer-Encoding: chunked
X-Influxdb-Build: OSS
X-Influxdb-Version: unknown
X-Request-Id: 0f294ecf-414a-11e8-9f72-000000000000
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: toggles=%7B%22ui-wp-upgrade%22%3Atrue%7D; grafana_user=admin; grafana_remember=b8f8b1c2c5097abd2cd70efe84e7f076ce52ef108e150b76bf5eff0b9c2fdafa40; grafana_sess=299598bf940e998d
Host: localhost:3000
Pragma: no-cache
Referer: http://localhost:3000/d/J0YGmlmiz/timeshifit-test-dashboard
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
X-Grafana-Org-Id: 1
db: PGK07007_CTC
q: show field keys
epoch: ms

**Comment by merturl** [comment]
this problem is fixed by this commit https://github.com/grafana/grafana/commit/e7bcd8c3c3662cb7e6d94756fc71c059962e8c95
