### ISSUE TITLE
Exporting data as CSV results in modified graphs

### ISSUE THREAD

**Issue by joehealy** [grafana/grafana#11598]
It appears that the function mergeSeriesByTime in public/app/core/utils mutates the seriesList it is provided. This causes the data in the graph to change next time it is redrawn.

It can be fixed by a refresh or any action that causes a requery of the datasource.

Please include this information:
### What Grafana version are you using?
5.0.4

### What datasource are you using?
Custom data source, but can replicate with influxdb
### What OS are you running grafana on?
linux

### What did you do?

Add 2 series to a graph panel. Each should have data available on different time steps.

![screenshot from 2018-04-16 16-30-10](https://user-images.githubusercontent.com/2563935/38793186-86bbf748-4193-11e8-8721-85b172d7ac41.png)

Export Panel data as csv, selecting the "series as columns" option.

Resize the panel and watch the data change. Gaps appear in between each record:

![screenshot from 2018-04-16 16-30-33](https://user-images.githubusercontent.com/2563935/38793191-8ccd7d6e-4193-11e8-8f3e-315f29ecf183.png)

The display will be "fixed" following a refresh.

**Comment by torkelo** [comment]
thanks for reporting this! definitely looks like a bug.
