### ISSUE TITLE
on the worldmap panel didn't show result of 2 queries -  only result of  1 query appear

### ISSUE THREAD

**Issue by andrewtk** [grafana/grafana#11591]
### What Grafana version are you using?
  -- 5.0

### What datasource are you using?
         -- mySql

### What OS are you running grafana on?
 -- Linux Debian 7

### What did you do? 
I am create 2 queries , but on the map appear only one 
http://prntscr.com/j5k4fr
http://prntscr.com/j5k4mz

### What was the expected result? 
result of 2 queries

### What happened instead? 
show only result of one query

### Include raw network request & response: 
http://prntscr.com/j5k167 

------------first query
SELECT
  UNIX_TIMESTAMP(settled) as time_sec,
  exchange as value,
  country as metric
FROM BillingInvoices 
WHERE entity_id = "EMPLOYEE"
group BY country
ORDER BY created ASC

----second query
SELECT
  UNIX_TIMESTAMP(settled) as time_sec,
  exchange as value,
  country as metric
FROM BillingInvoices
WHERE entity_id = "inventory"
group BY country
ORDER BY created ASC

**Comment by bergquist** [comment]
The worldmap panel does not support aggregating multiple queries. 

Please open issues about the worldmap panel at https://github.com/grafana/worldmap-panel
