### ISSUE TITLE
Make temp file time to live configurable

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#11607]
Could you please make the cleanup of temp files configurable?

Currently, it's hardcoded as 1 day (#6917, #6922). This is bad for everyone using "local" storage, because mail alerts sent out on the weekend have a broken link / missing image on Monday.

Location in source code: https://github.com/grafana/grafana/blob/3b836c9c5f1d320f3001f0a628fadbc8c97b6e51/pkg/services/cleanup/cleanup.go#L69

**Comment by rlueckl** [comment]
@bergquist Do you have any news? Somebody with knowledge of the code could probably do this in a few minutes (read parameter from config file and pass it to the cleanup module). If I knew Go and my way around the Grafana source code, I'd do it myself...

**Comment by xapon** [comment]
@rlueckl I wanted to try contributing to grafana and gave your issue a try. Hopefully it will be merged!

**Comment by rlueckl** [comment]
Thank you very much, that looks great! I hope it gets merged.

**Comment by marefr** [comment]
Fixed by #12274
