### ISSUE TITLE
[Feature request] Focus to the row with the same timestamp on a table when hovering on a data point on a graph

### ISSUE THREAD

**Issue by tgquan67** [grafana/grafana#11603]
Version: 5.0
Datasource: InfluxDB
OS: Debian 9.4

I have a measurement in InfluxDB with one main data field displayed on a graph and one auxiliary field displayed on a table. Since displaying the data from the auxiliary field in the tooltip is not going to be supported any time soon, can you make it so that when I hover over a data point on the graph, the row with the same timestamp on the table is somehow focused on too (similar to how all graphs can share crosshair)?

**Comment by bergquist** [comment]
This would be nice. But I'm not sure how easy it is to implement.

**Comment by jarmokivekas** [comment]
I'm lacking this feature as well. I have timestamped eventlogs to go with regular timeseries graphs. 

I tried adding them as annotations, but the large number of events floods the graphs: 

![screenshot from 2018-09-04 22-37-27](https://user-images.githubusercontent.com/3074453/45053682-5eaedf80-b093-11e8-976a-4f9b45af46d5.png)
