### ISSUE TITLE
Unable to save playlist, Permission Denied

### ISSUE THREAD

**Issue by ant0nwax** [grafana/grafana#11601]
I am unable to save a Dashboard Playlist
I would like to add a Playlist in order to use Kiosk/TV Mode of ONE Dashboard

Steps:
- Menu/Dashboard/Playlist
- +New Playlist
- +Add to Playlist (Environment-Dashboard)
- Create New Playlist

Result I am able to reproduce after restarting grafana server:
- Permission Denied (also as admin user)
- Unable to save playlist

Logs:
t=2018-04-16T11:14:40+0200 lvl=info msg="Request Completed" logger=context userId=8 orgId=1 uname=teamtv method=POST path=/api/playlists status=403 remote_addr=[IP-REMOVED] time_ms=0 size=31 referer=https://monitoringsrv.domain.tld/grafana/playlists/create

**Comment by ant0nwax** [comment]
INVALID

**Comment by pinakispecial** [comment]
Getting same problem in Openshift Grafana dashboard. How did you solved thsi?

**Comment by ant0nwax** [comment]
sorry i cant remember, i just see the comment i wrote INVALID :) so it was not the issue
