### ISSUE TITLE
Duplicating panels shifts existing panels in unexpected ways

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#11606]
### What Grafana version are you using?
v5 @ ee303c03e
### What datasource are you using?
Prometheus
### What did you do?
In a row that spans all columns I duplicated panel A that was in a row with another panels B. The duplicate will be called C.
### What was the expected result?
```
A C
B
```

or 

```
A B
C
```

### What happened instead?
The other panel B got pushed down.
```
A C
  B
```

**Comment by torkelo** [comment]
> 2) 
> Con: if you have more panels below you now have an empty row in the middle 

This will never happen unless there is no way for panels to flow upward and fill the empty space. 


So it will be like this 
A B C
D E G 

if you duplicate A (A') and place it below you will end up with a layout like this
A B C
A' E G
D 

So you push D down but E G will remain in place (assuming all panels have same width).  Not sure if this is better than what we have now, but probably in some scenarios. 

What we have now is 1) but with a twist, if there is space to the right, and by space I mean if the panel can fit in width wise to the right of the panel. But if adding it to the right would make it go outside the bounds of the grid it is placed below the panel instead.

I think we can definitely improve the current duplication logic. but what is correct in duplicating to the right or below feels very context specific. Maybe if there is no panels to the right, then we prefer that (if it fits). If there are panels to the right or it does not fit we add it below.

**Comment by davkal** [comment]
Yup, you're right, the empty row will only happen if the panels below cannot flow up.

But the issue remains, in your scenario I end up with A' under E, and not under D.

![screen shot 2018-04-16 at 17 09 44](https://user-images.githubusercontent.com/859729/38817648-13e88640-4199-11e8-9d1b-646abcd4ab3f.png)

Here is the dashboard json:
https://gist.github.com/davkal/0f05a1224109a6fb1edc1ca086a3f4bb

**Comment by torkelo** [comment]
I am unable to replicate that, 
given this dashboard, 
http://play.grafana.org/d/CFB9yKZmk/duplicate?orgId=1 

if I duplicate A it will add it to the right, and push B Down. 

So I end up with: 
<img width="1217" alt="screen shot 2018-04-17 at 07 06 14" src="https://user-images.githubusercontent.com/10999/38849715-e35a60e6-420d-11e8-85c7-36d822de16a4.png">

**Comment by torkelo** [comment]
Can we close this?

**Comment by aocenas** [comment]
Also can't replicate this. I guess I will close this, can reopen if needed.
