### ISSUE TITLE
weird issue: User is losing admin rights for some reason

### ISSUE THREAD

**Issue by olsonnn** [grafana/grafana#11600]
What Grafana version are you using?
v5.x
What datasource are you using?
n/a
What OS are you running grafana on?
CentOS 7.x
What did you do?
**add admin rights to a user (works fine)**
**After a while, the user is back to viewer rights.**

This happened for several users. i'm clueless. It seems to happen random..
What to check...
 (users via ldap)

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/ldap/#ldap-to-grafana-org-role-sync 

you need to remove the all [[servers.group_mappings]] to disable the ldap group -> grafana org role mapping (happens on login)

**Comment by olsonnn** [comment]
dohhh. how stupid. thanks. Issue fixed
