### ISSUE TITLE
Support raw formatting option for disabling quotes in variable interpolation

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#11614]
Building on the template variable interpolation feature introduced in #9911, support is needed for a raw format for variable interpolation. The main use case is to disable quotes for multi-value variables that are automatically quoted and concatenated.

## Example

For a multi-value variable named `host`, the current syntax for a template variable is: `$host` and for a data source like Postgres, it currently returns quoted interpolated values:

`'server1','server2','server3'`

To get the raw formatted version, the syntax would be: `${host:raw}` and the interpolated values would be:

`server1,server2,server3`

The code for interpolating multi-value variables and adding quotes is duplicated in several data sources:

- [Postgres](https://github.com/grafana/grafana/blob/v5.0.4/public/app/plugins/datasource/postgres/datasource.ts#L16-L33)
- [MySql](https://github.com/grafana/grafana/blob/v5.0.4/public/app/plugins/datasource/mysql/datasource.ts#L16-L37)
- [MS SQL](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mssql/datasource.ts#L16-L37)

ref #11021

**Comment by svenklemm** [comment]
Isn't this equivalent to `${host:csv}`? At least for the list case this seems to produce the desired result. And non-lists shouldnt be autoquoted. But replacing the datasource specific code is still a good idea.

**Comment by daniellee** [comment]
@svenklemm it is. Had totally missed that had been added to template_srv. Then what we want to do is add a csvquoted option and refactor the 3 sql data sources to use that. A raw formatting option should be added too.

**Comment by hugohaggmark** [comment]
Seems like the interpolation code is still in the data sources, but the formatting option __`raw`__ is already in Grafana (since `?.?.?` or at least 7.0.0). Therefore, I'm closing this issue. We're also trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
