### ISSUE TITLE
[Feat] Should enable "Save As" when a user with viewer role has edit permission in another folder

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11625]
It's common that users copy each other's dashboards to get started or make minor changes that meet their own requirements. Not being able to use `Save as` dashboard as a viewer is a big limitation for some organizations. 

When users load a dashboard the backend should query the database and see if the user is editor in any folders. If that the case, Grafana should enable the user to use `Save As` and give the user a modal asking for which folder the dashboard should be saved in.

**Comment by shalstea** [comment]
+1

**Comment by bergquist** [comment]
When users load a dashboard the backend should query the database and see if the user is editor in any folders. If that the case, Grafana should enable the user to use `Save As` and give the user a modal asking for which folder the dashboard should be saved in.
