### ISSUE TITLE
Enhancement : Dashboard Save As should not automatically copy tags.  It should be optional

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#11627]
Grafana 5.0.3
MetricTank - datasource

With ~2,000 dashboards that people are constantly cloning from existing ones we have two feature requests:

1. When building a Dashboard List one would want to be able to select the Tag(s) and the Folder(s).  This should be an AND clause in the search, e.g. limit the results to the list of dashboards where one of the Tag(s) is set AND they exist in the specified Folder(s) - this is a more important feature.

2. I would love to be able to specify that on a dashboard, if I create a tag, that when someone does a Save As the tag is not copied.  If I am the owner of the tag I don't want it to be inherited/copied.  This is a nice to have feature.

**Comment by shalstea** [comment]
I am ok with deferring #2 it is a nice to have only.  It is used heavily here as we have ~2,000 dashboards with hundreds of users.  It was partially used because we didn't have folders.  Now that we have those the tags use may drop off.

**Comment by marefr** [comment]
1) Has been fixed by #11525. 

@shalstea  Is 2) still valid, would be nice to update the description and title of this to reflect that only 2) is the feature request.

**Comment by shalstea** [comment]
Updated

**Comment by Ijin08** [comment]
<img width="501" alt="screenshot 2019-02-14 at 16 31 18" src="https://user-images.githubusercontent.com/23470681/52797471-41d0fc00-3076-11e9-8f1b-9ca2d860a18a.png">

**Comment by torkelo** [comment]
Think I prefer this: 

<img width="545" alt="screen shot 2019-02-14 at 18 08 10" src="https://user-images.githubusercontent.com/10999/52804043-89aa5000-3083-11e9-85fd-e0de682b8293.png">

Not sure we need to add keep description option right now, is there a request for that?, maybe after we add even more options and can hide some behind an options tab or something. Don't want this form modal to be too busy.

**Comment by shalstea** [comment]
This is an all or nothing approach (which is OK).  What about a selective copy option, where initially they have no tags and can drag-and-drop the ones they want to copy over ?  But it would likely be a lot more work.

**Comment by Ijin08** [comment]
Maybe a simpler solution(at least the implementation) could be to show the tags and give the opportunity to remove them. 

<img width="1440" alt="screenshot 2019-02-15 at 14 48 16" src="https://user-images.githubusercontent.com/23470681/52860912-2971e780-3131-11e9-9553-ac1528d89578.png">

**Comment by shalstea** [comment]
The problem I see with that is that most people are lazy.  They don't look at it and just want to save.  Which perpetuates the current behavior.  I would prefer to not copy any by default.  If they have to manually add them afterwards I am ok with that.

**Comment by Ijin08** [comment]
I understand. Here is kind of the opposite of what suggested before. It also gives the opportunity to add new tags and manually add tags from the original Dashboard. 

<img width="1440" alt="screenshot 2019-02-15 at 16 07 03" src="https://user-images.githubusercontent.com/23470681/52865275-96d74580-313c-11e9-8408-f3edab1ebf7d.png">

**Comment by shalstea** [comment]
So, just to confirm, you get the left hand-side by default (no tag copy), when you toggle the add tags, you see the tags available, and when you click on them they are added.

If that is correct, then this would be really nice.

**Comment by Ijin08** [comment]
Yes, that is correct. Not sure how difficult or how much work is needed to implement this though.

**Comment by shalstea** [comment]
No problem. This looks very good.  Can always be done in phases.

**Comment by torkelo** [comment]
Initial simple solution for this is now merged and will be included in v6.1

Since this save as menu is used quite frequently I wanted to keep it as simple as possible. 

![image](https://user-images.githubusercontent.com/10999/54031926-679e7c00-41b0-11e9-946a-fe020f920bdb.png)

**Comment by shalstea** [comment]
That is fine.  Will you have a follow-up ticket to do the more complicated or are you not going to do that at all ? If you are going to do it, can you post the follow-up ticket?

**Comment by torkelo** [comment]
here is a follow up issue that requests the ability to select tags in the Save As modal
https://github.com/grafana/grafana/issues/15876
