### ISSUE TITLE
OAuth providers not present when trying to sign in when `anonymous access` is enabled. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11626]
* Enable any OAuth provider
* Enable anonymous access
* go to `http://localhost:3000`
* click `sign in` in the bottom left corner
* no oauth providers :man_shrugging: 

Grafana should make a full page redirect to `/login` since oauth providers are added by the backend when browsing that url.

**Comment by torkelo** [comment]
I don't understand this, if I go to http://play.grafana.org/login I see OAuth providers, and it has anonymous access enabled. If this bug was true would we not have thousands of complaints. Anonymous + OAuth must be pretty common.

**Comment by bergquist** [comment]
I can reprodue this locally. If you click the `Log in` text you get redirected to the "OAuth less" login page.

play.grafana.org runs 5.0.0 so its quite far behind. `Log in` is not even clickable on play.grafana.org

**Comment by torkelo** [comment]
can also replicate on master, must be something introduced after v5.0.0 so this should be a critical bug we need to fix in before v5.1

**Comment by bergquist** [comment]
Good catch. Not sure why I put it in 5.2

**Comment by torkelo** [comment]
was able to fix issue, the Sign In (text link) did not have a target="_self" so did not trigger a full page reload.
