### ISSUE TITLE
Version 5 tag label font hard to read

### ISSUE THREAD

**Issue by Jonnymcc** [grafana/grafana#11629]
### What Grafana version are you using?
5.0.4

### What datasource are you using?
prometheus/graphite

### What OS are you running grafana on?
AWS Linux

### What did you do?
Looking at label on dashboard picker.

### What was the expected result?
Clear easy to read labels.

### What happened instead?
They look fuzzy/blurry.
![screen shot 2018-04-17 at 10 35 05 am](https://user-images.githubusercontent.com/1041598/38876920-746ac676-422b-11e8-876b-ded38921f0cf.png)

### Other...
Using Firefox 52.7.3 (64 bit) on Mac OS X 10.11.6.

Anyone else noticing this?

**Comment by torkelo** [comment]
thanks for reporting this! fixed!

**Comment by Jonnymcc** [comment]
Thanks @torkelo !
