### ISSUE TITLE
Dragging Rows in Grafana 5.0.4 not possible

### ISSUE THREAD

**Issue by notes-jj** [grafana/grafana#11634]
### What did you do?

Add a Row, which will appear on top of all rows. The Row can't be moved around by drag and drop. There is no menu any more for the row order like in Grafana 4.x.

### What was the expected result?

Rows should be moved around by drag and drop.

### What happened instead?

Row Title was selected.

### Comment

I tested with up-to-date Firefox and Chrome.

I like rows for not rendering the hidden panels, if they are not shown. We have some very database load intense dashbords, where all rows are hidden and you only view the rows you need for the analayses and no query will be performed, if rows are hidden.

**Comment by bergquist** [comment]
You need to collapse the row first. Then you can move them

**Comment by guidoiaquinti** [comment]
Can we make the dotted array more visible? I hit the same issue as @notes-jj today
