### ISSUE TITLE
Version 5: Side menu hiding/unhiding very distracting

### ISSUE THREAD

**Issue by progan** [grafana/grafana#11631]
### What Grafana version are you using?
5.0.3

The side menu autohide is very distracting especially when it happens on a second monitor in the visual periphery. An option to pin it open or otherwise disable the autohide feature would be nice.

My experience is:

1. I'm working on something else in another window
2. The side menu autohides and draws my attention because the contents of the entire grafana window jumps. 
3. I then instinctively mouse over to/click on the grafana window as my focus is drawn to it.
4. The side menu autoshows.
5. I am suddenly not happy that I was distracted from what i was focused on for no good reason.
6. Repeat....

It is really annoying and I'd like the option of disabling the side menu autohide.

**Comment by torkelo** [comment]
you can hide the sidemenu by clicking on the grafana logo, then this jumpy behavior will go away.

**Comment by torkelo** [comment]
but we have gotten other similar reports like yours so you are not alone in this. We will consider adding a user preference for this!

**Comment by RandomReaper** [comment]
:+1: for the user preference
