### ISSUE TITLE
Phantomjs not installed on brew install

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#11638]
Direct rendered links do not work after installing Grafana with brew install. It seems the PhantomJS binary is not installed in the `tools/phantomjs` subdirectory. This might require a PR to the [brew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/grafana.rb) for Grafana.

ref #11235

**Comment by ZachBenz** [comment]
@daniellee I experience this issue even with the phantomjs binary for macOS manually installed in the tools/phantomjs subdirectory.  I’m using phantomjs 2.1.1 downloaded from here: http://phantomjs.org/download.html

**Comment by ZachBenz** [comment]
That is, #11235 under macOS is not resolved by manually installing phantomjs after doo g a brew install.

**Comment by daniellee** [comment]
@ZachBenz we only have a few macs to test on here but it worked on 2 out of 2. So hope this resolves it for you. The brew package will be probably be updated on Thursday or Friday this week.

**Comment by ZachBenz** [comment]
@daniellee Thanks!  Looking forward to testing.

**Comment by daniellee** [comment]
@ZachBenz did you get a chance to test this yet?

**Comment by mlamoure** [comment]
On 5.1 installed on Mac via Brew, PhantomJS is working for SingleStat and Graph panels, though the render takes more than 30 seconds for a 24 hour query which I found strange because the dashboards load very quickly.  I also use a lot of Discrete panels and 5.1 seems to have broken those.

**Comment by daniellee** [comment]
@ZachBenz closing this issue as it seems to work on MacOS for other people.

@mlamoure PhantomJs is problematic and we will be switching it out for headless Chrome in the next version of Grafana. I see you have already opened an issue in the Discrete panel repo.

**Comment by ZachBenz** [comment]
@daniellee Confirmed all is working now - thanks!
