### ISSUE TITLE
cancel the keyboard shortcut

### ISSUE THREAD

**Issue by fenfenraorao** [grafana/grafana#11636]
What Grafana version are you using?
latest

Can I cancel the keyboard shortcut? If so, in what way?Thank you.

**Comment by bergquist** [comment]
Do you want to disable all shortcuts?

**Comment by fenfenraorao** [comment]
yes,is it possible?Thank you.

**Comment by torkelo** [comment]
no, that is not possible

**Comment by piengeng** [comment]
hi, grafana is hijacking browser's ctrl-k shortcut key, how do i disable this ctrl-k behavior? ctrl-k is used for the search bar/input in firefox. it's quite annoying, really appreciate if there's an option to disable these keyboard shortcuts. Github also hijacked ctrl-k but there's an option to disable this behaviour...

**Comment by TimShilov** [comment]
Is that still not an option? I really think it should be.
While hotkeys can undoubtedly improve efficiency for many, they can also inadvertently override and conflict with pre-established browser and extension hotkeys that users rely on. This can lead to both confusion and a degraded experience for those who have certain workflows or accessibility needs.

For example:
* Browser Conflicts: In Arc Browser, the Command + S hotkey is used to toggle the sidebar. However, within Grafana, this same hotkey has a different action, leading to unintended consequences when I try to use it.
* Extension Conflicts: I frequently use the Vimium extension, which employs the j and k hotkeys for navigation. When Grafana captures these inputs, it disrupts my ability to navigate seamlessly.

**Comment by sombek** [comment]
@TimShilov I agree I am suffering from `⌘ + S` shortcut, is there anyway to disable this shortcut?

**Comment by piengeng** [comment]
hey folks, just to share my workaround on firefox via this suggestion https://support.mozilla.org/en-US/questions/1241294 probably similar config on chrome (not my main browser)

some other sites also hijack some browser's default keyboard shortcuts, so this is kinda permanent, and I'm happy with this.
