### ISSUE TITLE
install custom plugins for error: This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by webliuxiang** [grafana/grafana#11647]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
v4.6.3
### What datasource are you using?
all
### What OS are you running grafana on?
Centos 7
### What did you do?
install custom plugins
### What was the expected result?
working OK
### What happened instead?

![image](https://user-images.githubusercontent.com/25944130/38948324-d6104fa8-4371-11e8-9458-b029a1079b47.png)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana@4.6.3~prebuild: grafana@4.6.3
6 info lifecycle grafana@4.6.3~build: grafana@4.6.3
7 verbose lifecycle grafana@4.6.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle grafana@4.6.3~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/go/src/github.com/grafana/grafana/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/go/bin:/home/liuxiang/.local/bin:/home/liuxiang/bin
9 verbose lifecycle grafana@4.6.3~build: CWD: /opt/go/src/github.com/grafana/grafana
10 silly lifecycle grafana@4.6.3~build: Args: [ '-c', 'grunt build' ]
11 silly lifecycle grafana@4.6.3~build: Returned: code: 1  signal: null
12 info lifecycle grafana@4.6.3~build: Failed to exec build script
13 verbose stack Error: grafana@4.6.3 build: `grunt build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid grafana@4.6.3
15 verbose cwd /opt/go/src/github.com/grafana/grafana
16 verbose Linux 3.10.0-693.17.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error grafana@4.6.3 build: `grunt build`
22 error Exit status 1
23 error Failed at the grafana@4.6.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### If related to metric query / data viz:
..

**Comment by bergquist** [comment]
We cannot support or answer questions about why custom plugins do not work as expected. You have to ask the maintainers of the custom plugin.
