### ISSUE TITLE
How to sort the grafana dashboard 

### ISSUE THREAD

**Issue by szediktam** [grafana/grafana#11649]
Hi, all,
I use grafana4.4.0, and I want to show my dashboards sorted by my wish. But they return order by a-z.
I name the title of dashboard as 01XXX,02XXX, and it works. But it not perfect. 
Is there a way to sort the dashboard as my wish?

**Comment by szediktam** [comment]
when I search the dashboard, I want to sort them as my wish.
![screenshot from 2018-04-19 15-42-05](https://user-images.githubusercontent.com/6055078/38977944-6fe4a55e-43e8-11e8-8227-370e482595e1.png)

**Comment by daniellee** [comment]
No, there is no way to sort them in the Grafana UI. Maybe dashboard folders is a way to get what you want? You could organize related dashboards in folders.

http://docs.grafana.org/reference/dashboard_folders/
