### ISSUE TITLE
RuleCount is not increased in the Alert Scheduler - the previous alert entry is deleted

### ISSUE THREAD

**Issue by tcgjensen** [grafana/grafana#11641]
Please include this information:
### What Grafana version are you using?
 Grafana v5.0.1 (commit: a747ec3)
### What datasource are you using?
Influx
### What OS are you running grafana on?
Centos 6.9
### What did you do?
When creating the second alert on a graph, the previous one gets deleted. This means I can only have one alert. As soon as I create another alert, the existing one gets deleted in the alert engine, however the alert config is visible in grafana. Only the lastest alert is visible in the alert panel (and it is configured to show 10).
The ruleCount does not get increased.
### What was the expected result?
Want to have more alerts at the same time.  The ruleCount should get increased.
### What happened instead?
The existing alert gets deleted and the new one gets inserted. The ruleCount remains 1.
The alert config is visible in grafana, but the "heart" remains white.

**Comment by tcgjensen** [comment]
It seems to be very unstable. Sometimes I am able to create more alerts, but then suddenly when I create another one or I just save the dashboard, the alerts disappear in the Alert Panel/List. The alert config is available on each graph, and the ruleCount is not correct.

Is this a known bug in version 5?

**Comment by tcgjensen** [comment]
Example of grafana log, where it is possibile to see that I have a situation where I have 6 rules (alerts) configured and then when I create the 7th alert, 5 previous ones are deleted - and I am NOT deleting them, eventhough it says "removed from dashboard".

t=2018-04-18T15:08:55+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=6
t=2018-04-18T15:08:58+0200 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=2
t=2018-04-18T15:08:58+0200 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=2
**t=2018-04-18T15:08:58+0200 lvl=dbug msg="Alert inserted" logger=sqlstore name="Exception Log - new errors alert" id                                                                                  =40
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=34 reason="Removed from dashboard"
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=35 reason="Removed from dashboard"
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=36 reason="Removed from dashboard"
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=37 reason="Removed from dashboard"
t=2018-04-18T15:08:58+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=38 reason="Removed from dashboard"**
t=2018-04-18T15:09:01+0200 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="A                                                                                  ccount Payments - Not Captured, Cancelled or Rejected alert" id=33
t=2018-04-18T15:09:01+0200 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://192.168.234.8:8086/quer                                                                                  y?db=rator&epoch=s&q=SELECT+max%28%22count%22%29+FROM+%22account_payment_backlog%22+WHERE+%28%22customer%22+%3D+%27                                                                                  vimla%27+AND+%22system%22+%3D+%27prod%27+AND+%22capture_status_id%22+%21%3D+%2780%27+AND+%22capture_status_id%22+%2                                                                                  1%3D+%2760%27%29+AND+time+%3E+now%28%29+-+10m+and+time+%3C+now%28%29+-+5m+GROUP+BY+time%28200ms%29%2C+%22payment_ty                                                                                  pe%22%2C+%22capture_status_id%22+fill%28null%29"

**Comment by tcgjensen** [comment]
In the below, I update an alert that exists on a graph, but is not recorgnized by the scheduler and then it inserts it and a different alert with id=33 is removed, when it is not supposed to.

t=2018-04-18T15:19:24+0200 lvl=dbug msg="Alert inserted" logger=sqlstore name="Provisioning Task Backlog - pending tasks alert" id=41
t=2018-04-18T15:19:24+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=33 reason="Removed from dashboard"
t=2018-04-18T15:19:25+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=2

**Comment by tcgjensen** [comment]
In this case I have 3 alerts configured which is visible and also in the scheduler, I then delete a 4th alert which is not known to the scheduler and the consequence is that two of the others are deleted:

t=2018-04-18T15:38:30+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=3
t=2018-04-18T15:38:31+0200 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Exception Log - new errors alert" id=40
t=2018-04-18T15:38:31+0200 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://192.168.234.8:8086/query?db=rator&epoch=s&q=SELECT+max%28%22count%22%29+FROM+%22exception_log%22+WHERE+%28%22customer%22+%3D~+%2F.%2Avimla.%2A%2F+AND+%22system%22+%3D~+%2F.%2Aprod.%2A%2F%29+AND+time+%3E+now%28%29+-+10m+and+time+%3C+now%28%29+-+3m+GROUP+BY+time%281m%29%2C+%22source_key%22%2C+%22source_type%22%2C+%22table_name%22+fill%28null%29"
t=2018-04-18T15:38:31+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.525 alertId=40 name="Exception Log - new errors alert" firing=true
t=2018-04-18T15:38:38+0200 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2018-04-18T15:38:38+0200 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=1
t=2018-04-18T15:38:38+0200 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2018-04-18T15:38:38+0200 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=1
**t=2018-04-18T15:38:38+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=41 reason="Removed from dashboard"
t=2018-04-18T15:38:38+0200 lvl=dbug msg="Deleting alert" logger=sqlstore id=42 reason="Removed from dashboard"**
t=2018-04-18T15:38:40+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1

**Comment by bergquist** [comment]
Please upgrade to 5.0.4 this is due to a bug in 5.0.0/1/2 

https://github.com/grafana/grafana/issues/11222
