### ISSUE TITLE
Add an option to open link content into another window/tab

### ISSUE THREAD

**Issue by jeromegit** [grafana/grafana#1165]
Hi Torkel,
A quick suggestion here.
I love the drilldown/detail link functionality. I just wished it open the content into a different window/tab instead of overwriting the current dashboard. 
I would suggest to add that behavior as an option.

Thanks in advance.

**Comment by torkelo** [comment]
Was fixed in 2.1 

![image](https://cloud.githubusercontent.com/assets/10999/9987190/61d9bb2c-6045-11e5-8b3a-e54ebb4e56f5.png)

**Comment by jeromegit** [comment]
Thanks Torkel!

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
INTP <http://www.mypersonality.info/personality-types/intp/>
