### ISSUE TITLE
Global Grafana admin must have Admin in current organization to see 'Server Settings' menu

### ISSUE THREAD

**Issue by jcmcken** [grafana/grafana#11657]
### What Grafana version are you using?

Grafana v5.0.3 (commit: 91162f3)

### What datasource are you using?

Not relevant to issue

### What OS are you running grafana on?

CentOS 7.4

### What did you do?

Granted a user global Grafana admin (``is_admin = true`` in ``users`` table). This user only has 'Viewer' and 'Editor' to various organizations.

### What was the expected result?

User has the ability to administer Grafana globally (including change own organization permissions if necessary).

### What happened instead?

User cannot see the 'gear' icon in the left-hand menu until I add the user as an 'Admin' on current organization. When user switches to other organizations, the gear icon disappears, and user cannot access global settings (until switching back to the dashboard where they have 'Admin' role).

It seems like the global admin 'Server Settings' is nested under the Organization Admin permission, when really it should be a separate menu/permission independent of organization membership.

**Comment by dschade2016** [comment]
We have the same issue. Users with "Viewer" role cannot see "Server Settings". Pls fix it in 5.1.4 ?
