### ISSUE TITLE
Dashboard API returning incorrect panels, related to default saved template variables

### ISSUE THREAD

**Issue by cchance27** [grafana/grafana#11653]
Grafana 5.0.4
Prometheus 2
Docker

I have 2 prometheus variables (nested), in the dashboard all displays fine for example below i get the panels for the 2 ipaddresses that match the var-location for dawn beach...

$location = label_values(sysLocation{job="canopy450"}, sysLocation)        filtered: /(.*) \[.*/
$ipaddress = label_values(sysLocation{sysLocation=~"$Location.*", job="canopy450"}, instance)

My panels repeat on $ipaddress, which works great in the dashboard, but in api i seem to run into an issue....

I have tested and confirmed what the issue is... Basically when an api call is made say ...  
http://localhost:3000/api/dashboards/uid/wiFGLNqzz?var-IPAddress=All&var-Location=Bar

If the default saved variables from the dashboard has say 3 values for IPAddress, and i'm repeating on IPAddress for all my panels, if the new var-Location returns only 2 IPAddresses the API seems to be filling in the missing repeated panels, and returning the var-Location i requested for the first 2 sets of panels, and then the default saved panels for the rest 

So say i have var-Location = Foo  as my default that returns ip 192.168.1.1 and 192.168.1.2

If i then call the API for var-Location = Bar and Bar only has a return of ip 192.168.1.10 the api will give me a set of panels for

192.168.1.10 and 192.168.1.2 which is obviously incorrect, it should only return the panels from 192.168.1.10

**Comment by cchance27** [comment]
I've managed to work around this temporarily, by saving the default value in the dashboard to a result that only returns 1 value for ipaddress, that way if theirs any result it will get overridden which works around the issue, but is just that a work around.

**Comment by bergquist** [comment]
You cannot save template variables by passing them as querystrings to the API. They have to be updated in the dashboard.json and then sent to the API.
