### ISSUE TITLE
Refresh changes graphs dramatically

### ISSUE THREAD

**Issue by adi** [grafana/grafana#11665]
### What Grafana version are you using?
Grafana v5.0.4 (commit: 7dc36ae)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Linux (Docker)

### What did you do?
I tried to create a load graph from a Kube cluster with the 'sum(node_load1)' expression.

### What was the expected result?
A stable graph

### What happened instead?
A graph that changes dramatically on both X an Y axes with every refresh.
<img width="1436" alt="screen shot 2018-04-20 at 06 49 00" src="https://user-images.githubusercontent.com/10928150/39030203-e7f57f66-4468-11e8-95ae-9fee032c183f.png">
<img width="1431" alt="screen shot 2018-04-20 at 06 48 52" src="https://user-images.githubusercontent.com/10928150/39030204-e8299db4-4468-11e8-98a5-4d0a5324c620.png">

I also tried not to sum the load values and the results were even more changing:
<img width="1438" alt="screen shot 2018-04-20 at 07 05 09" src="https://user-images.githubusercontent.com/10928150/39030275-500b02c4-4469-11e8-959f-573d8101639d.png">
<img width="1430" alt="screen shot 2018-04-20 at 07 05 03" src="https://user-images.githubusercontent.com/10928150/39030277-503896f8-4469-11e8-8548-9d3518304571.png">

**Comment by bergquist** [comment]
This is expected behavior due to how sampling works in prometheus. There is a issue for how we can improve this experience to make it less "jumpy" https://github.com/grafana/grafana/issues/9705
