### ISSUE TITLE
[Feature Request] Duplicate datasource; use as template for new datasource

### ISSUE THREAD

**Issue by petemyron** [grafana/grafana#11664]
I'd like the ability to duplicate a datasource--or use an existing datasource as a template for creating a new one. 

In my case, I write many types of measurements to an InfluxDB with their own, unrelated database. It'd be nice to copy an existing datasource, change the database name, credentials if needed, and save as a new datasource without having to copypasta or type all the details.

**Comment by markusressel** [comment]
I'd recommend you look into defining data sources using yaml as described here:
http://docs.grafana.org/administration/provisioning/#example-datasource-config-file

I use it for the exact same reason you are describing.

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

If you work/update your datasources frequently I strongly suggest you provision them from files. I dont see us implementing this in any near future so I'm closing this issue. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.
