### ISSUE TITLE
If the variable is the e-mail address, the reference variable is not updated

### ISSUE THREAD

**Issue by haozhixin** [grafana/grafana#11667]
If the variables in the check box are mailboxes, it will not be updated if the variable is quoted below.

The version I used is 5.0.4
My mailbox is 21 strings

It should be the @ symbol without a change of meaning
Is there any good way to avoid this problem?

**Comment by daniellee** [comment]
I think using the raw option for template variable formatting should avoid this problem: https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#raw
