### ISSUE TITLE
Text clipping for sign in

### ISSUE THREAD

**Issue by nikoalch** [grafana/grafana#11660]
### What Grafana version are you using?
HG 5.0.4

Text clipping- not consistent between browsers

FF
![image](https://user-images.githubusercontent.com/33036213/39018931-9e13c6aa-43f5-11e8-915f-b07b95ebd31b.png)

Safari:
![image](https://user-images.githubusercontent.com/33036213/39019009-e297ef72-43f5-11e8-9545-734c935a77ff.png)

Chrome:
![image](https://user-images.githubusercontent.com/33036213/39019041-f8a77b48-43f5-11e8-8a7c-86013fec785b.png)

**Comment by daniellee** [comment]
@nikoalch I think this is fixed now as the login screen looks totally different now.
