### ISSUE TITLE
subURL miss parsed

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#11672]
if I configure a subURL via:

`root_url = %(protocol)s://%(domain)s:%(http_port)s/dash/`

then I can't access any URL include `dashboard`. The redirection is done in nginx with:

```
location /dash/ {
proxy_pass http://127.0.0.1:3000/;
}
```

The link e.g. for a new dashboards `http://192.168.1.1/dash/dashboard/new?gettingstarted&orgId=1` brings then: `http://192.168.1.1/dash/board/new?gettingstarted&orgId=1`

All subURLs starting with `d`, `da`, ... `dashboard` are also broken.

Other subURLs without a subset of `dashboard` are working.

**Comment by pulux** [comment]
forgot
bug in v5.0.4
worked in v4.6

**Comment by pf4sh** [comment]
I think this is a major bug and may not easy to fix. Can anybody give a release in which it will be fixed?
