### ISSUE TITLE
No data points for custom cloudwatch metrics

### ISSUE THREAD

**Issue by alexsabau86** [grafana/grafana#11676]
Please include this information:
### What Grafana version are you using?
v5.0.1

### What datasource are you using?
Cloudwatch with custom metric namespace

### What OS are you running grafana on?
Running grafana in a docker container prom:grafana:latest

### What did you do?
Created a new dashboard with graphs for displaying disk_free custom metric, scraped by the cloudwatch agent.

### What was the expected result?
I should see the custom metric in grafana dashboard

### What happened instead?
The graph is displaying No data points

### If related to metric query / data viz:
I can view the custom metrics just fine in AWS.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 There's nothing to show.

Note* - Other metrics I am able to see in grafana from the same EC2 instance - No data points are displayed only for the custom metrics. The custom metric namespace is not giving any errors when I click on Save & Test.

**Comment by alexsabau86** [comment]
Does anyone have any idea about what could be happening here? Would really appreciate some hints, thank you!

**Comment by alexsabau86** [comment]
Managed to find the solution for this. In grafana, when adding a new graph, I had to specify all dimensions that were displayed in cloudwaatch for a given custom metric. That way I was able to get data to display.

**Comment by zmokhtar** [comment]
@alexsabau86, I had the same problem.  Adding all dimensions fixed it for me.  You are my hero!

**Comment by jjones3000** [comment]
> Managed to find the solution for this. In grafana, when adding a new graph, I had to specify all dimensions that were displayed in cloudwatch for a given custom metric. That way I was able to get data to display.

how exactly did you do this. That's my problem, I can't see anyway to do this
