### ISSUE TITLE
[Feat] Grafana Promethues Variables Query

### ISSUE THREAD

**Issue by MoSunDay** [grafana/grafana#11674]
OS Version：
```
Linux m 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Grafana Version:
```
I'm try 5.0.0~5.0.4 and 5.1-beta1
```
On Promethues
```
label_replace(cluster_info_meta{cluster_image='grafana'},'cluster_image','test','job','info')
Get
cluster_info_meta{cluster_image="test",cluster_name="test",instance="localhost:5000",job="info"}
Or
label_replace(cluster_info_meta{cluster_image='grafana'},'cluster_image','mself/$1:.*','cluster_image','(.*)')
Get 
cluster_info_meta{cluster_image="mself/grafana:.*",cluster_name="test",instance="localhost:5000",job="info"}
```
But on Grafana
```
label_replace(cluster_info_meta{cluster_image='grafana'},'cluster_image','test','job','info')
```
Grafana show me tihis message
```
Templating
Template variables could not be initialized: parse error at char 14: could not parse remaining input "(cluster_info_m"...
```
ps:
```
cluster_info_meta

cluster_info_meta{cluster_image="grafana",cluster_name="test",instance="localhost:5000",job="info"}  1
cluster_info_meta{cluster_image="prometheus",cluster_name="test",instance="localhost:5000",job="info"} 1
```

**Comment by marefr** [comment]
@MoSunDay Relabeled this as a feature request since it has never worked using for example the Prometheus function label_replace in template variable queries.

As a workaround, please use the *query_result(query)* helper, see [documentation](http://docs.grafana.org/features/datasources/prometheus/#query-variable) for more information.

**Comment by var23rav** [comment]
@marefr Using **query_result(query)** how can we get the label values, am looking for **label_values(query, label_name)**.

Feature: **It will be helpful if Grafana could provide some transformation on result(template variables).**
eg: regex replace, case change,...

**Comment by marefr** [comment]
You'll have to use the regex field to extract label values

**Comment by var23rav** [comment]
@marefr Thanks man.. Just now sort it out, was about to post that.
Its good that, grafana won't allow to use more than one group in regex. They take the group value as variable value

regex:    /job-prefix-([a-zA-Z0-9-]*)/
variable value: will be ([a-zA-Z0-9-]*)

query_result(query) will be an added benefit if we wanted to change the text itself.

**Comment by MoSunDay** [comment]
Thank you very much for your answers

**Comment by lch0000** [comment]
For change "node" from 10.10.xxx.xxx to 10.20.xxx.xxx
querry: query_result(label_replace(kube_pod_info{pod=~"$pod"}, "node", "10.20.$1", "node", "10.10.(.*)"))
regex: /.*node="(.*?)".*/
