### ISSUE TITLE
Feature Request: Support optional free-form Description on charts and/or dashboards

### ISSUE THREAD

**Issue by nickman** [grafana/grafana#1168]
It would be helpful to be able to define a free form text description for charts and/or dashboards. Optional to define. Could be hidden but revealed on a "?" icon. Sounds silly, but hear me out. I am finding that viewers frequently do not understand what a specific chart means because the displayed metric names, or the relationship betwen them is not self-explanatory. This feature would go a long way to make some of these displays self-desribing.

**Comment by addshore** [comment]
+1
Notes could also be displayed on hover over the title, or as a pop up on clicking another link.

**Comment by utkarshcmu** [comment]
+1 for hidden notes/text.....

**Comment by utkarshcmu** [comment]
@torkelo What do you think about this? 

<img width="1423" alt="screen shot 2016-01-15 at 12 09 13 am" src="https://cloud.githubusercontent.com/assets/1019609/12348443/5da3ebf4-bb1c-11e5-980d-e3d80ce88e56.png">

Also notes should be optional, if someone does not want to put in any notes, he should not. 

If you think this looks good, I can work on a PR.

**Comment by torkelo** [comment]
It's ok, like this one more though
https://cloud.githubusercontent.com/assets/10999/5267773/91092438-7a08-11e4-806a-22c8d3ef0b90.png

**Comment by utkarshcmu** [comment]
@torkelo My mind is in a dilemma as I want notes/help text for the panels in the next version. But I am still in favor of something similar to screenshots in #1505. May be the tooltip icon at the left bottom of the panel. Or may be using Collapses -> http://mgcrea.github.io/angular-strap/#/collapses. Let me explain my use case. We have 100s of dashboards and a lot of them has 15-20 graphs OR 30-40 Singlestat panels on a single dashboard. Space on these highly useful graphs are precious.

**Comment by sslupsky** [comment]
+1  

A useful enhancement to this idea would be to provide for an elasticsearch query to fill the notes or a text panel.

**Comment by alchuk** [comment]
@sslupsky 
+1
And moreover, this might be implemented as a 'hidden' variables, similar to 'templating' variables.

I'm waiting for this feature as I'd like to put interface descriptions and some additional info (configured interface shaping rate or purchase order) on the graph panel.

**Comment by utkarshcmu** [comment]
@sslupsky Checkout screenshots in #4079 What do you think about that?

**Comment by alchuk** [comment]
@utkarshcmu The help tooltip might be useful when you are dealing with information, that might be missing for the most of graphs or appear on periodic basis. I personally need a way to add a "notes" field for every graph.

**Comment by torkelo** [comment]
this was added in 4.1 https://github.com/grafana/grafana/issues/4079#issuecomment-267586552
