### ISSUE TITLE
New Graph Legend Display mode: Big Singlestat

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#11684]
Really think a legend mode like this could be super useful and make legend much more TV friendly (easy to read). 

![image](https://user-images.githubusercontent.com/10999/39084071-78c3b75e-456f-11e8-8e5b-e25c247b5926.png)

Think this will require some new options:

1) legend big singlestat mode

Also open to start saving hidden series (via legend click) state in dashboard state so you can for example have graphs with 5 series but by default only 1-2 is shown.

**Comment by yellowpattern** [comment]
It would be cool to have some other options for "big singlestat". For example, you've got "Average CTR" and maybe a left corner could have min and a right corner max, or each corner is n-sigmas from the mean and so on. Sometimes the graph option for the bottle of the singlestat is good but other times, other values in a smaller font would be cool.

e.g. In "Total Clicks", maybe an average min or average max or something. but maybe that is putting too much in one box...
