### ISSUE TITLE
[feature request] Datasource for several organizations

### ISSUE THREAD

**Issue by b2ronn** [grafana/grafana#11680]
I have several organizations in Grafana.
I have a few datasources that all organizations need.
It would be good if I could define this once in the some config file in /etc/grafana/provisioning/datasources/
In Grafana 4 I use Triggers in MySQL. 
type: feature request

**Comment by bergquist** [comment]
This is not something we want to add. 

But if you configure your datasources from files it would be very easy to make sure one datasources is configured in multiple orgs. 

http://docs.grafana.org/administration/provisioning/#datasources
