### ISSUE TITLE
rpm signing if failing on circle ci

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#11686]
![image](https://user-images.githubusercontent.com/10999/39089067-afbdf068-45be-11e8-9932-e950637cb3a0.png)

Was reported on twitter as it is affecting the v5.1 beta release.

Not sure what the cause for the error can be.

**Comment by xlson** [comment]
The problem is that rpmmacros expects a ubuntu user to exist. Our build container runs as root and is not based on ubuntu. I'll add a circleci user so that we can use the same user/id in all containers on circleci and switch the script to using that user.
