### ISSUE TITLE
Anonymous Authentification

### ISSUE THREAD

**Issue by stevenrsz** [grafana/grafana#11691]
Hello,

I would like to create for the role viewer an anonymous authentification then no password is necessary to view dashboards.

So on the .ini files, I configured this : 

[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = exampleOrg

# specify role for unauthenticated users
org_role = Viewers 

But everybody on my exampleOrg have an anonymous authentification ....
How to just for the same organization, only to allow the role viewer ?

PS: I am using the last version ( v5.0.4) , and using CentOS.

Regards,

Steve

**Comment by bergquist** [comment]
Your role configuration is invalid. It should be `Viewer`
You can read more about anonymous access at http://docs.grafana.org/installation/configuration/#auth-anonymous

**Comment by stevenrsz** [comment]
Sorry ,

Yes, indeed it is Viewer on my ini.file

but all the organization have an anonymous acces ... And I want just the role : Viewer for my organization
