### ISSUE TITLE
Variable select doesn't render data until F5

### ISSUE THREAD

**Issue by zBurrito** [grafana/grafana#11696]
### What Grafana version are you using?
5.0.4

### What datasource are you using?
Graphite

### What OS are you running grafana on?
Centos 7

### What did you do?
I have defined multiple variables that are multi-value and has an all option.
As default the ALL option is selected, when I deselect the ALL option and I select another value it shows no results. When I press F5 the correct results are shown, when I click the grafana refresh button it doesn't.

### What was the expected result?
Show the result of the data of the variable query.

### What happened instead?
It shows "No data to show".

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
When the ALL value is select, it correctly returns all the json in the render request, when another value is selected the render request is empty and when I press F5 while another value is selected the render request also shows the right json.

**Comment by torkelo** [comment]
strange, unable to replicate this here: https://play.grafana.org/d/000000143/templating?orgId=1 

Can you include all the requests Grafana is making to Graphite (and the graphite response) that happens when you change the template variable value?

**Comment by daniellee** [comment]
Closing due to lack of response. I will reopen the issue if you answer with more details.

**Comment by zBurrito** [comment]
It was due to an older version of graphite-carbon (0.9.6). We have now updated it to 1.1.3 and it's working now.
