### ISSUE TITLE
Tooltip hovering datapoints sometimes. 

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#11693]
### What Grafana version are you using?
5.0.4

When the tooltip is on right side of crosshair it is OK but when tooltip is on left side it is too much to the right so it hide the data points
<img width="960" alt="tooltip2" src="https://user-images.githubusercontent.com/21694965/39119403-0af8afc6-46ec-11e8-8e08-fc7a6b2e15a0.png">
<img width="960" alt="tooltip" src="https://user-images.githubusercontent.com/21694965/39119404-0b1e0b90-46ec-11e8-9008-14d21dbe04a2.png">

**Comment by torkelo** [comment]
Fixed in upcoming new graph panel
