### ISSUE TITLE
Enhancement - dashboard creation with folder permissioning is awkward

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#11701]
Grafana 5.0.3
MetricTank

We have enabled authentication and permissioning on folders.  An end-user can't create a new dashboard without first navigating to a folder that they own and then clicking on the new dashboard option.  This is really awkward.

It should be easy to start a new dashboard.  When saving it, they should be shown only a list of folders that they are permissioned for.

**Comment by marefr** [comment]
Fixed by #11858 and #10796
