### ISSUE TITLE
Grafana graphs not rendering on old browsers

### ISSUE THREAD

**Issue by jeffdesc** [grafana/grafana#11706]
### What Grafana version are you using?
v5.0.4
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Raspbian Stretch
### What did you do?
Loading the Grafana dashboard on Raspbian Stretch. Running Screenly OSE (using UZBL viewer behind screens).
### What was the expected result?
The graphs are being loaded and Grafana would display as on a normal browser (e.g. Chrome v65)
### What happened instead?
The graphs themselfs are not being rendered at all. Not even the legend or the panels is being rendered.

Is there any workaround for this?

**Comment by bergquist** [comment]
Solving all browser issues is very time-consuming. I suggest you install chrome on your raspberry.

I'm closing this since we won't work on this unless it's a very requested feature. If that's the case we will reopen this.
