### ISSUE TITLE
Error creating template variable from Prometheus query

### ISSUE THREAD

**Issue by SteveMaddison** [grafana/grafana#11708]
### What Grafana version are you using?
Version: Grafana v5.1.0-beta1 (a07f52568) installed from RPM package
(Issue not present in: Grafana 5.0.4)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
RHEL 7

### What did you do?
Create a template variable based on a Prometheus query, e.g. simply "up".

### What was the expected result?
The query is run and the results are offered as values of the template variable.

### What happened instead?
Templating
Template variables could not be initialized: i.datasource.getOriginalMetricName is not a function

Possibly related to #11674 but error message is different.

**Comment by marefr** [comment]
@SteveMaddison As a workaround, please use the *query_result(query)* helper, see [documentation](http://docs.grafana.org/features/datasources/prometheus/#query-variable) for more information.

**Comment by SteveMaddison** [comment]
@marefr Nice, can confirm _query_result()_ works a treat. Glad we can now stick with the 5.1 line and not have to roll back to 5.0.4.

**Comment by marefr** [comment]
Glad that works. There's still a bug. Using only "up" should work. A fix for this is on its way.
