### ISSUE TITLE
API key authorization not working - getting 401 error

### ISSUE THREAD

**Issue by subbaray** [grafana/grafana#11715]
curl -H "Authorization: Bearer XXXXXXXXXXXXXXXXX" https://grafana.xxxx.com/api/dashboards/home"

I have created API key as admin in main org and got the above curl command provided during api key creation. But still it is not working.

**Comment by daniellee** [comment]
This works for me on my machine - you will need to provide more details for us to able to reproduce this.

- you have an extra double quote at the end, is that just a typo?
- any errors in the grafana server log?
- any non-default settings in the config?
- do you have multiple orgs?

**Comment by subbaray** [comment]
Grafana version is v4.6.3

**Comment by daniellee** [comment]
Not really sure how to help you - this is too little information to see what the problem is. Is it impossible to see the Grafana server logs?

Do any other api calls work? (Like the [search endpoint](http://docs.grafana.org/http_api/folder_dashboard_search/#search-folders-and-dashboards))

**Comment by torkelo** [comment]
closing due to lack of information to help / troubleshoot
