### ISSUE TITLE
[Feature Request] allow configuration of MaxOpenConns/MaxIdleConns/SetConnMaxLifetime for datasources

### ISSUE THREAD

**Issue by t-8ch** [grafana/grafana#11711]
It would be great if the amount of connections to a database (mysql) connection store could be configured.
Currently ( 3a48ea8 ) both MaxIdleConns and MaxOpenConns are hardcoded as 10.
In our case this exhausts the maximum amount of allowed connections on the DB server, starving another application.

The same configuration is possible for the sqlstore, backing users, dashboards etc.
See #7427

Please include this information:
Version: 5.0.4, diagnosed with source of  3a48ea8.
Datasource: mysql
OS: Debian 8.10

### What did you do?

Configured a Mysql datasource, used it in a dashboard, opened the dashboard multiple times.
All connections to the DB were exhausted.

### What you hoped for

A setting to configure the amount of used connections

**Comment by marefr** [comment]
Thanks. If this is implemented we want to have the same/similar functionality for all three sql datasources why I tagged the issue correspondingly. 

Contribution are always welcome if you want to give it a go and submit a PR.

**Comment by t-8ch** [comment]
@marefr Is it fine if I stuff the settings into the pkg/models/datasource.go:DataSource struct?
There already seem to be quite a few fields that are not generic for all datasources.

**Comment by marefr** [comment]
@t-8ch you should use the existing JsonData property. See example [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/postgres/postgres.go#L55) how postgres are using that for a custom setting.

**Comment by m2dc0d3r** [comment]
Is there a fix planned?

**Comment by marefr** [comment]
@m2dc0d3r no. There's an open feature request for it #11711

**Comment by marefr** [comment]
@m2dc0d3r sorry wrong link. There's currently an open PR that somewhat target to fix this
