### ISSUE TITLE
png-rendering ignores height/width if it's the first parameter

### ISSUE THREAD

**Issue by j20d** [grafana/grafana#11725]
I'm on Grafana 5.0.4, just upgraded.

I'm rendering dashboards using 
http://host-goes-here/render/dashboard/db/dashboardname?height=1920&width=1080
That does render the graphs but it sets the height to the default-height.

If I use 
http://host/render/whatever/dashboardname?stupidrenderbug=1&height=1920&width=1080
it works as expected.

**Comment by daniellee** [comment]
This works for me: https://play.grafana.org/render/dashboard/db/grafana-play-home?height=500&width=1000

and this works: https://play.grafana.org/render/d/000000176/4-years-of-grafana?height=900&width=1800

I don't doubt that there is a bug here. We've had a lot of problems with PhantomJS (we will be switching to headless Chrome in the near future).

- What panels do you have on your dashboard?
- Can you create a generic example of this bug and share the dashboard?

**Comment by daniellee** [comment]
Closing due to lack of response. I will reopen the issue if you answer with more details.
