### ISSUE TITLE
datasource.example.js no longer valid after switch to millisecond granularity

### ISSUE THREAD

**Issue by chrisleavoy** [grafana/grafana#1172]
Am I to understand the data array expected to be returned by a data source plugin has changed from seconds to milliseconds?

```
      // get from & to in seconds
      var from = kbn.parseDate(options.range.from).getTime() / 1000;
      var to = kbn.parseDate(options.range.to).getTime() / 1000;

      var series = [];
      var stepInSeconds = (to - from) / options.maxDataPoints;
```

If so I can fix and submit a merge request.

**Comment by mtanda** [comment]
The datasource.example.js is removed in current version.
@torkelo This issue can be closed.

**Comment by bergquist** [comment]
@mtanda thanks!
