### ISSUE TITLE
Grafana logs flooded with info "path=/tags/tagMultiSeries status=404"

### ISSUE THREAD

**Issue by ybizeul** [grafana/grafana#11729]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.0.3
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Debian 8.5
### What did you do?
Normal installation of the Graphite / Grafana stack, but graphite below `/graphite` URL
### What was the expected result?
It seems Grafana is sending request to `/tags/tagMultiSeries` instead of the actual data source URL which is `/graphite/tags/tagMultiSeries` but I'm not sure how, or if the issue is in Grafana
### What happened instead?
Request is sent to wrong URL and get a 404
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
```
t=2018-04-26T02:56:03-0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/tags/tagMultiSeries status=404 remote_addr=127.0.0.1 time_ms=0 size=10349 referer=
```

**Comment by ybizeul** [comment]
It doesn't look like this request comes from Grafana, it's something else I need to identify. Will report when I find it

**Comment by bergquist** [comment]
@ybizeul closing this since it's not from Grafana

If you find out it is from Grafana we can reopen this.

**Comment by ybizeul** [comment]
Thank you, it was indeed a carbon config issue
