### ISSUE TITLE
Auth related Config changes not reflecting on Grafana 5.0.4

### ISSUE THREAD

**Issue by priyankatapar** [grafana/grafana#11730]
I am trying to enable Github auth on grafana, but its not picking the config changes.

"I already removed ; to uncomment the config" 
1. I tried changing the config in /usr/local/etc/grafana/grafana.ini and also in /usr/local/opt/grafana/share/grafana/conf/defaults.ini

**Config file changes:**
[auth]
disable_login_form = true

#################################### Github Auth ##########################
[auth.github]
enabled = true
allow_sign_up = true
client_id = ***************
client_secret = ********************************
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
;team_ids =
allowed_organizations = coupa

Restarting grafana service after config changes
sudo launchctl stop grafana
sudo launchctl start grafana

**When I login into Grafana, Server Admin -> Settings page is not showing up changed config values.**

<img width="873" alt="screen shot 2018-04-26 at 3 26 18 pm" src="https://user-images.githubusercontent.com/38099579/39299406-43230c58-4966-11e8-97f7-c4b0424ce797.png">

**Login page is not showing Github login button.**

**Comment by marefr** [comment]
Feels like you're not editing the correct config file then. How are you running Grafana and on what platform, docker, ubuntu/rpm/deb? Have read the [config file location documentation](http://docs.grafana.org/installation/configuration/#config-file-locations)?

**Comment by priyankatapar** [comment]
I had installed it on Mac OS and as well as Centos (AWS ec2 instance). I was editing the correct config file, because I also edited some log related config, which worked but auth related config din't reflect.

Mac config file path: /usr/local/etc/grafana/grafana.ini
CentOS config file path: /etc/grafana/grafana.ini

Thanks,
Priyanka Tapar

**Comment by marefr** [comment]
So it works now or what? If you try to logout and login do you see the login using Github button? Does it work as expected etc?

**Comment by daniellee** [comment]
After restarting, can you check the grafana server logs? I cannot recreate this - Grafana picks up auth changes for Github for me.

**Comment by daniellee** [comment]
@priyankatapar did you get this working?

**Comment by daniellee** [comment]
No response for a couple of weeks so closing this issue - I can reopen if this is still a problem.
