### ISSUE TITLE
Graph Y-axis autoscaling doesnt work when hiding series.

### ISSUE THREAD

**Issue by PresidentCamacho** [grafana/grafana#11734]
Please include this information:
### What happened instead? It did not

This is how the data looks like unfiltered:

![image](https://user-images.githubusercontent.com/5015774/39307790-11694bd4-4964-11e8-95ea-aaac8719658a.png)

This is the configuration of Series override

![image](https://user-images.githubusercontent.com/5015774/39307768-000eefce-4964-11e8-8464-3511dadb2e7f.png)

This is the result, Y-axis should've recalculate on the visible serie(s).

![image](https://user-images.githubusercontent.com/5015774/39307719-dea2f81c-4963-11e8-9062-4cff43b49c19.png)

Also I noticed that the tooltip is still there for the hidden series, maybe should add a series override for tooltip as well?

 
![image](https://user-images.githubusercontent.com/5015774/39307895-5bc3207e-4964-11e8-96fd-34c806ef63b4.png)

**Comment by daniellee** [comment]
Your issue is correct - the series overrides doesn't remove the series, just hides it.

If you are using the latest version of the Azure Monitor plugin (v0.1.1), you should be able to filter out series via the query using the new filter field. And this is how you would handle this situation for most data sources.

**Comment by PresidentCamacho** [comment]
Do you have a example on how to filter out series using the filter? I can't find any documentation on it.

**Comment by torkelo** [comment]
To filter out series you can use the new transform or series override hide option
