### ISSUE TITLE
Value formatting of thousands with unit short

### ISSUE THREAD

**Issue by kerams** [grafana/grafana#11732]
### What Grafana version are you using?
5.1-beta

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Windows Server 2016

### What did you do?
Create a graph for a metric where values go above 1000, select Unit - short in the Axes tab. Leave Decimal values for Axes and Legend set to auto.

### What was the expected result?
In the tooltip as well as the legend, I expected values like 2258, to be shown as 2.3 K or simply 2258.

### What happened instead?
2258 is shown as 2.258 K, which makes little sense to me.

**Comment by daniellee** [comment]
The setting for tooltip decimal places is the same as the legend. You can set the decimal places to 1 here under Values:

![image](https://user-images.githubusercontent.com/434655/39324742-85e73ea4-4990-11e8-8998-dc28d6723a6c.png)

And then you will get 2.3 K.

**Comment by kerams** [comment]
That isn't much help when I'm dealing with integers exclusively (in their 'unshortened' form),

**Comment by Sarke** [comment]
This is still an issue.  The thousand range looks odd:

![Grafana](https://user-images.githubusercontent.com/2719310/82630093-8ff07b80-9ba6-11ea-8c37-50c0e8d5c867.png)

Setting the decimal to 1 (as the suggested solution) makes little sense as mentioned:

![Grafana](https://user-images.githubusercontent.com/2719310/82630137-adbde080-9ba6-11ea-8169-23efedff6096.png)
