### ISSUE TITLE
Feature: Explore UI skeleton

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#11741]
New Explore section for adhoc queries.

Quick prototype that assumes Prometheus datasource as default, and light theme.

**Comment by phemmer** [comment]
Why not just edit the panel, and then not save it?

**Comment by torkelo** [comment]
I am also a bit confused by going from panel to Explore UI. At least as a primary scenario to start with.

I feel the main use case is starting from scratch when you want to explore what data you have, and quickly do a bunch of semi related ad hoc queries. If the starting (and most important) use case is making it easier to edit panel queries and discard changes then I can see that being easily done by improving panel edit mode. I know the explore UI wants to do more, but at least In my mind the primary scenario I would start with is making a super easy to use UI that lets users explore what data they have when starting from scratch.  

We can discuss more during a hangout next week.

Thoughts @bergquist  @daniellee ?
