### ISSUE TITLE
Add notifier for Webex Teams

### ISSUE THREAD

**Issue by peay** [grafana/grafana#11750]
This issue is to track support of notifications for Cisco [Webex Teams](https://www.webex.com/products/teams/) rooms (recently re-branded from Cisco Spark).

I sent a working PR for that in https://github.com/grafana/grafana/pull/11702, but Grafana currently does not accept new notifiers. This needs to be revisited once backend plugins are available.

**Comment by danielwagn3r** [comment]
This would be great especially since the generic webhook notifier doesn't provide the features, see #6956 , need to use it as a workaround.

**Comment by itshorty** [comment]
Also with the new Incomming Webhooks Feature this should be very similar to discord

**Comment by briski0074** [comment]
+1 on Webex Teams Webhook

**Comment by kungfuweapon** [comment]
+1 on Webex Teams Webhook, would be really nice for our project.

**Comment by tremahts** [comment]
+ 1 for Webex Teams webhook

**Comment by vinesh2011** [comment]
+1 for Webex Teams webhook

**Comment by ElisaFrancesconi** [comment]
+1  for Webex Teams webhook

**Comment by cinesia** [comment]
+1 for Webex Teams webhook

**Comment by glhewett** [comment]
+1 for Webex Teams webhook

**Comment by liqingwang** [comment]
+1 for Webex Teams webhook

**Comment by gsraocisco** [comment]
+1 for Webex teams Webhook!

**Comment by dipeshtripathi** [comment]
+1 for Webex teams Webhook!

**Comment by ramukima** [comment]
Basic webex notification feature PR here: https://github.com/ramukima/grafana/pull/1

**Comment by fferraro87** [comment]
+1  for webex integration
