### ISSUE TITLE
LDAP login with MariaDB/MySQL database and dn>100chars not possible

### ISSUE THREAD

**Issue by dschade2016** [grafana/grafana#11754]
### What Grafana version are you using?
 Grafana v5.1.0 (commit: 844bdc53a), (via Docker)
### What datasource are you using?
None
### What OS are you running grafana on?
CentOS7, Docker 18.03.0-ce
### What did you do?
Clean container start with LDAP configuration via GF_* and ldap.toml file and mysql configuration
### What was the expected result?
Successful login with AD credentials
### What happened instead?
Failed to login with the following error:
`"Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="Error 1406: Data too long for column 'auth_id' at row 1"`

With sqlite3 we have no problem. 

![2018-04-27 14_02_41-grafana-sql-ldap1](https://user-images.githubusercontent.com/23652401/39361761-2952126a-4a24-11e8-92b9-0ab5e968f3c9.png)

We have fixed the problem in the database scheme. [Name Length Limitations for LDAP Simple Bind Operations based on Microsoft.](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc756101(v=ws.10))

![2018-04-27 14_02_41-grafana-sql-ldap2](https://user-images.githubusercontent.com/23652401/39361856-84da56d8-4a24-11e8-9660-5c8137b6c59d.png)

**Comment by vitalvas** [comment]
Repeats also on PostgreSQL.

What Grafana version are you using?
Grafana v5.1.0 (commit: 844bdc53a), (via package)

What OS are you running grafana on?
Ubuntu 16.04

**Comment by Ajaysrndpt** [comment]
Any idea when this issue will be fixed?
