### ISSUE TITLE
Graphpanel Edit for IE11 in Version 5.1.0 beta does´t work

### ISSUE THREAD

**Issue by bgruenefeld** [grafana/grafana#11759]
as the Issue https://github.com/grafana/grafana/issues/11165 was closed
and the following pull request (https://github.com/grafana/grafana/pull/11416) is merged in Version 5.1.0 beta, i thought that editing a graph panel under IE11 would work correct.

### What Grafana version are you using?

grafana-5.1.0-beta1

### What datasource are you using?

grafana 

### What OS are you running grafana on?

Windows 10

### What did you do?

try to edit graph 

### What was the expected result?

a correct graph panel dialog shown under the graph

### What happened instead

shown in the attached screenshoot

![image](https://user-images.githubusercontent.com/10279112/39364186-6d8496de-4a2d-11e8-87ee-f3326e59ef6c.png)

**Comment by daniellee** [comment]
Try installing the stable version of 5.1.0. Fixed by #11722 after beta was released.

Basically, we fixed it and then broke it again when working on issues with the scrollbar and then fixed it again :-)

I will reopen if this is still a problem.
