### ISSUE TITLE
"All Series" Tooltip with "Percent" for Multi Series

### ISSUE THREAD

**Issue by theomega** [grafana/grafana#1175]
How to reproduce:
1. Set up a graph with multiple series and set:
- "Axes and Grids" -> "Format" to "Percent"
- "Display Styles" -> "Multiple Series" to "Stack" and "Percent"

_**Observe:** Tooltip shows percentages (good)_
1. Enable: "Display Styles" -> "Tooltip" -> "All Series"

_**Observe:** Tooltip shows absolute values but puts a % after them (bad)_

Screenshot:
![screenshot - 03 12 2014 - 14 47 34](https://cloud.githubusercontent.com/assets/905977/5281244/649e92f4-7afb-11e4-9054-238e05a3ae62.png)

Version: 1.9.0

**Comment by torkelo** [comment]
The tooltip no longer show percent but the unit you have specified
