### ISSUE TITLE
How to filter by hostname when using labels in Prometheus?

### ISSUE THREAD

**Issue by michaelseto** [grafana/grafana#11764]
Hello All,

In my docker-compose file for Prometheus, I am specifying multiple targets for nodeexporter and cadvisor. With each target, I have a label named 'host' (ex. labels: {'host': 'servername'}). The purpose of me doing this is so that I can hopefully open the dashboards for Docker Host and Docker Containers and filter by which hostname I want to see.

So far, it has been a big challenge getting familiar with the filtering syntax.

Could someone please help me with this filtering? Thanks so much!

**Comment by michaelseto** [comment]
I figured out the CPU Usage filter,

"sum(rate(node_cpu{host="server_name"}[1m])) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\",host="server_name"}))"

How about for the memory? I see the expression is like so -

node_memory_MemTotal - (node_memory_MemFree + node_memory_Buffers + node_memory_Cached)

**Comment by daniellee** [comment]
Please ask questions on the community site https://community.grafana.com
