### ISSUE TITLE
for a snapshot api, do not use:  refresh: on time Range chart. 

### ISSUE THREAD

**Issue by londonanthonyoleary** [grafana/grafana#11768]
in grafana 5
I am generating snapshots using the rest api.
For a template variable, do not use:  refresh: on time Range chart.  otherwise you will get a ,templating init failed, datasource not found; alert popup in the snapshot.  this would be a grafana bug. on, dashboard load, property had the same issue.

**Comment by daniellee** [comment]
I don't understand - what is the bug in Grafana?

**Comment by daniellee** [comment]
No response - closing. I can reopen if more details are provided.
