### ISSUE TITLE
no alerts displayed in snapshots

### ISSUE THREAD

**Issue by londonanthonyoleary** [grafana/grafana#11765]
in grafana 5,
created alerts from prometheus to grafana. This appeared correctly in grafana, but they did not appear in a snapshot.
will this be fixed?

**Comment by daniellee** [comment]
Seems to work for me:

https://snapshot.raintank.io/dashboard/snapshot/Wwheu9Xpge0lrQ8fTzZ46OGoDKfD6JQG?orgId=2

Any more details you can provide?

**Comment by marefr** [comment]
@londonanthonyoleary it works for me when disable the *Annotations & Alerts (Built-in)*. Save the dashboard. Then create your snapshot. 

To give some more context:
* *Annotations & Alerts (Built-in)* annotation are enabled
* A second prometheus annotation query exist that are enabled
* Rendering annotations in dashboard works (non built-in available, only prometheus)
* Creating a snapshot will not render any annotations
* Disable *Annotations & Alerts (Built-in)* and save dashboard. Create snapshot
* Prometheus annoations are rendered

**Comment by londonanthonyoleary** [comment]
Thanks for that, I can see the alerts now from prometheus if i disable the grafana alerts (Built in). bBut will you be able to support internal grafana annotations and external alerts in a snapshot in the future?

**Comment by torkelo** [comment]
this should be fixed in v5.2
