### ISSUE TITLE
Singlestat using image/icon as background

### ISSUE THREAD

**Issue by alisson276** [grafana/grafana#11760]
Singlestat is a nice plugin, but it will be better if it had a possibility of using a icon on background. That icon  could be configured on editor setting position (up, bottom, rigth, left) and size (110%, 50%, etc).

Image using a patched singlestat:
![singlestat with icon](https://user-images.githubusercontent.com/13340485/39364819-960d79b8-4a05-11e8-98a9-d766b291da02.png)

**Comment by daniellee** [comment]
There are lots of community plugins that cover this use case.

- https://grafana.com/grafana/plugins/aceiot-svg-panel
- https://grafana.com/grafana/plugins/dalvany-image-panel
- https://grafana.com/grafana/plugins/larona-epict-panel
- https://grafana.com/grafana/plugins/pierosavi-imageit-panel
- https://grafana.com/grafana/plugins/bessler-pictureit-panel
- https://grafana.com/grafana/plugins/marcuscalidus-svg-panel
