### ISSUE TITLE
Tables: titles don't scroll with the content

### ISSUE THREAD

**Issue by FluffyAlpaca** [grafana/grafana#11762]
Hi! 

### What Grafana version are you using?
I'm using Graphana 5.0.4. 
### What datasource are you using?
I'm using a PostgreSQL datasource
### What OS are you running grafana on?
I'm on Windows 10.
### What did you do?
I created a table panel. I made a query that returned many fields and so, many columns : 
![image](https://user-images.githubusercontent.com/25431347/39365751-5e552e9e-4a32-11e8-8d57-3faaeda2b722.png)

When I scroll down, everything is fine. 
The problem is when I scroll to right: the content is scrolling, but not the titles, so the content is not aligned anymore with titles:
![image](https://user-images.githubusercontent.com/25431347/39365863-ad1d8b8e-4a32-11e8-93f2-67023a7335a9.png)

It's not an emergency, but it's not really handy. 
Thank you for your time!

**Comment by daniellee** [comment]
Thanks for the well-written issue. 

There is already an issue for this: #11468 so closing as a duplicate.
