### ISSUE TITLE
for snapshot api,null value field option not implemented

### ISSUE THREAD

**Issue by londonanthonyoleary** [grafana/grafana#11767]
in grafana 5,
in the Grafana dashboard /panel/Graph/display menu , for the  chart null value field options,  my rest api sent this this correctly to grafana but the snapshot did not pick it up,this seems a bug in Grafana snapshot api.

**Comment by daniellee** [comment]
Can you provide more detail and if possible a link to a snapshot showing this problem.

**Comment by daniellee** [comment]
Closing this - no response for 21 days. I can reopen if more details are provided.
