### ISSUE TITLE
react-resizable-handle shows up in the panel editor

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11771]
This is a super minor issue that I notice with recent builds, but do not remember in earlier 5x builds.  When you go to the panel editor the bottom right now has a resize icon and changes the cursor.  It does not do anything, but is a bit weird.

![image](https://user-images.githubusercontent.com/705951/39376693-dd981624-4a52-11e8-8d8b-a31776ac7e48.png)

**Comment by marefr** [comment]
At the same time it would be nice to hide the icon in the lover right corner when in kiosk/inactive mode - please evaluate that in solution.

**Comment by davkal** [comment]
Cannot repro the resize issue on Chrome/Mac. Looking into icon hiding...

**Comment by marefr** [comment]
@davkal I can reproduce it on Ubuntu Chrome and Firefox

**Comment by davkal** [comment]
Aha, that's the browser's cursor for the CSS value `cursor: se-resize;`, just looks different on my machine. Anyways, I'm hiding the resize indicator in fullscreen panels and low-activity views. That should solve it.

**Comment by towolf** [comment]
This works with `?inactive` but not with `?kiosk`. @davkal did you intend for the controls to be hidden in kiosk mode as well?

**Comment by towolf** [comment]
Just found the comment on the PR:

> IMO the difference between fullscreen and kiosk mode is that the latter is still interactive, just with no means of navigating away.

We use kiosk mode for fullscreen on wall-mounted TVs. I think hiding the controls is warranted there as well.

**Comment by marefr** [comment]
@towolf I was thinking that kiosk mode go into inactive mode eventually as well - maybe I was wrong?

**Comment by towolf** [comment]
@marefr You're right, I did not expect that and did not wait long enough. The handles do disappear. That's ok then.
