### ISSUE TITLE
[Feature request] Vertical centered values on Single Stats when using smaller font sizes

### ISSUE THREAD

**Issue by Brausmith** [grafana/grafana#11779]
Using single stat panels with smaller font sizes and shorter panel heights, the padding around the value is not vertically centered.
Panels can have small font sizes, which for users like me, suggests so that smaller panels can be used.

This request is to be able to use smaller font sizes while maintaining an even padding top and bottom around the value.

_For clarity, I don't use the word 'padding' in a coding sense, just to portray the intent of the request._
![image](https://user-images.githubusercontent.com/3722950/39421492-a558df4e-4cac-11e8-88ba-8c3d92316427.png)

**Comment by zoltanbedi** [comment]
Singlestat has been deprecated and replaced by stat panel where this works.
