### ISSUE TITLE
Allow UI to save changes for provisioned dashboards 

### ISSUE THREAD

**Issue by unguiculus** [grafana/grafana#11778]
### What Grafana version are you using?
5.1.0
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Official Docker image

We have an automated Grafana setup on Kubernetes with dashboard provisioned from disk using the new provisioning feature. Our workflow is the following:

* Create/edit dashboards in the UI
* Export dashboards and commit the to Git

Since we like to have everything automated, we have a script that exports all dashboards using the API. With provisioned dashboards being readonly now (#10883), this approach no longer works. We have to manually copy and paste the dashboard JSON from the UI so we can commit it. Doing stuff manually in an automated world is IMHO an anti-pattern. While I understand the rationale behind #10883 regarding database vs. filesystem, there should still be some way to export modified provisioned dashboards via API.

**Comment by torkelo** [comment]
No the new provision workflow enforces automation. 

If you want to use API -> export & import via API you can do that. But provisioning enforces saved changes to dashboard to go through provisioning so you always know what is the correct & latest state. 

 You can still use your workflow of changing it UI and backing it up in git but you have to use API to export & import.

**Comment by torkelo** [comment]
But I agree, maybe an option in provisioning to "allow UI save" is worth considering if that is what many users want.

**Comment by unguiculus** [comment]
Of course, I can still use the API to export dashboards. But since I cannot save a provisioned dashboards, the export is useless since it doesn't contain unsaved changes.

**Comment by kolaCZek** [comment]
Same story... I had to downgrade back to 5.0.4.

**Comment by torkelo** [comment]
@bergquist is there any way to opt out of the Provision save modal and make provisioned dashboards updatable via UI/api ?

**Comment by povilasv** [comment]
This is also an issue for me and it would be great to make this configurable. 

As we have a `grafana2git` exporter, which queries grafana API and makes commits to git and then grafana is fed off git via provisioned dashboards and `5.1` breaks this flow

**Comment by olitheolix** [comment]
Same here. Since this behavior still exists in v5.2, may I ask if there are plans to revert it or is it here to stay?

**Comment by bergquist** [comment]
We won't revert this change but we should introduce an option for allowing users to save over provisioned dashboards.

**Comment by rshejnberg** [comment]
Same thing here, I've downgraded until 5.0.4 until a way to do this is provided as this is critical functionality for me

**Comment by irispenker** [comment]
Hi
We are trying to use grafana with docker container for both developement and deployment. 
Since saving the provisioned dashboards is not allowed , we cannot use it for automating development to create dashboards that will be later deployed.
Please advise when a fix for this will be provided.

**Comment by devminded** [comment]
How about being able to edit the dashboard in a "namespace" (or as a draft with a short retention time) and once the editor is happy with the change there is a "save/commit" step.

**The commit step should be a plugable action that could:**

- Push it back directly to the "main" dashboard (for legacy behavior).
- Just save as a draft and have something poll these drafts and export it through the API and apply whatever promotion-/provision-process we'd like outside of Grafana.
- POST a message to any http-endpoint, and do as above, avoiding polling.
- Bonus feature: Push it directly to git and for example let our automation re-provision the dashboard back to "main".

**Comment by chrisys** [comment]
Looking for this feature here too. The use case is that I've built a sample project in a container with a dashboard to be used as an initial starting point which I'd like users to be able to customise for their own needs. Using the provisioning method right now they can't make and save changes without duplicating the dashboard first. I'd suggest that even adding a 'Save As' function to part of the "Cannot save provisioned dashboard" UI would be a basic improvement to the UX.

**Comment by jfloodopt** [comment]
I am looking for this feature as well or a workflow solution that allows developers to bulk import dashboards into Grafana from github without provisioning so that they can work on them and then export. We were using the provision / export option for local development on developer workstations with an older version of Grafana. Without this feature we are stuck manually copy and pasting json to update developer workspaces which leaves us with potential for work to be lost.

**Comment by lacksfish** [comment]
+1

Saving edits in UI on provisioned dashboards would be a nice-to-have.

**Comment by psreekala** [comment]
We are in need of this feature as well.

**Comment by machao23** [comment]
Please add this feature,thanks
