### ISSUE TITLE
Enhancement: Limit Tags by Metric

### ISSUE THREAD

**Issue by wattwood** [grafana/grafana#1177]
As the number of metrics and tags grow, it's becoming increasingly difficult to create graphs with tags.  Can Grafana be enhanced to limit the tag results based on the metric provided?

**Comment by jtakkala** [comment]
This issue sounds very like it's solved by #1349.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/2119

**Comment by bergquist** [comment]
Closed since its fixed by #2119
