### ISSUE TITLE
Bug: Graph Auto Refresh not working

### ISSUE THREAD

**Issue by bdonnahue** [grafana/grafana#11776]
Please include this information:
### What Grafana version are you using?
5.0.4
### What datasource are you using?
MySQL
### What OS are you running grafana on?
CentOS 7
### What did you do?
Setup graph for mysql datasource with auto refresh set to 5s
### What was the expected result?
The graph would refresh every 5 seconds
### What happened instead?
The graph did not refresh
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
There were no network requests shown in the Developer Tools

**Comment by daniellee** [comment]
This sounds really strange - could you provide more details. 

- What does your mysql query look like
- does it work when you press the refresh button in Grafana (beside the timepicker button)? 
- Any errors in the Grafana server logs?

**Comment by daniellee** [comment]
Closing due to lack of response. I will reopen the issue if you answer with more details.

**Comment by bdonnahue** [comment]
@daniellee Apologies for the delay here
The query is a simple select:
`SELECT
  UNIX_TIMESTAMP(date_time) as time_sec,
  price as value,
  'foobar' as metric
FROM sampledata1;
`
The refresh button does work and it updates the graph.
I did not see any errors in the logs etc relating to this graph.

I will note that the data set was very small and only existed in January so perhaps the date had some effect?
