### ISSUE TITLE
Increased loading speed / scrollingn not working

### ISSUE THREAD

**Issue by darox** [grafana/grafana#11793]
Since I've upgraded to grafana 5.1 (docker), I'm experiencing increased loading speeds and scrolling on smartphones isn't working anymore. Tested on:
Google Pixel XL 2
Galaxy Note 8
Huawei P20 Pro

**Comment by daniellee** [comment]
Could you provide more detail please.

- On which pages are you seeing increased loading speed? Any special dashboards that are slower? If possible, can you show a comparison between 5.0 and 5.1 with a video or performance stats from the Chrome dev tools.
- Can you provide more details about the scrolling problems. Which pages are affected? Does it not work at all?

**Comment by daniellee** [comment]
Is the scrolling issue the same as #11710 ?

**Comment by daniellee** [comment]
@darox should I close this? We really want to know if there are problems with performance or scrolling but I can't reproduce anything with so few details.

**Comment by darox** [comment]
@daniellee I've received an updated docker image and now it seems to be better. Therefore I can be closed.
