### ISSUE TITLE
Display Series Override based on value of second metric

### ISSUE THREAD

**Issue by karora** [grafana/grafana#11790]
I have a plot (of temperature) for which I would like to modulate the colour by using a second metric (of whether the heating is turned on).

I have achieved this currently by using two separate plots of `(temperature * heating_on) > 0` and `(temperature * heating_off) > 0`, but this seems quite hackish.

Since there is already a facility for Display Series Overrides it would be nice if I could put a metric in there instead of a regex.

### What Grafana version are you using?
5.0.4

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Linux (Docker)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
