### ISSUE TITLE
4.6.2 -> 5.1.0: Graph, axes unit "none" does not show original decimals precision anymore

### ISSUE THREAD

**Issue by tw-bert** [grafana/grafana#11792]
### What Grafana version are you using?
grafana_5.1.0_amd64.deb
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
ubuntu.xenial64
### What did you do?
Copied grafana.db from our live system to a separate VM, upgraded to Grafana 5.1.0 to check for issues
### What was the expected result?
To see the same data with the same precision. '1.01' must stay '1.01' in the legend and the tooltip.
### What happened instead?
'1.01' becomes '1' in Grafana 5.1.0

Grafana 4.x:
![image](https://user-images.githubusercontent.com/3413888/39474606-1a216ea6-4d55-11e8-83f6-3d36e208d939.png)

Grafana 5.1.0:
![image](https://user-images.githubusercontent.com/3413888/39474626-2c9ce8ee-4d55-11e8-860c-0bc2442bbf27.png)

Both Axes are configured the same:
![image](https://user-images.githubusercontent.com/3413888/39474651-4c77cac6-4d55-11e8-8065-c2d9aa234080.png)

Here is the full JSON of the panel (Grafana 4.6.2):

```json
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "$datasource",
  "editable": true,
  "error": false,
  "fill": 1,
  "grid": {},
  "id": 65537,
  "interval": "$inter",
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "hideEmpty": true,
    "hideZero": true,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": true,
    "total": false,
    "values": true,
    "sortDesc": true,
    "sort": "current"
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "span": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "alias": "$tag_host:$tag_port $tag_env - $col",
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "$interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "redis_used_cpu_sys",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"mem_fragmentation_ratio\") as \"frag\" FROM \"$rp\".\"redis\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(none)",
      "rawQuery": true,
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Memory Fragmentation",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "cumulative"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "none",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "none",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": false
    }
  ]
}
```

**Comment by daniellee** [comment]
I had a quick look at this and seem to work for me but I haven't tried to recreate the issue with your dashboard json yet.

The decimals field on the axis tab does not control the number of decimal places for legend values. That field is on the legend tab. But it seems to be the same issue for the axis values as well.

**Comment by tw-bert** [comment]
Hi @daniellee , thanks for having a look.
The difference is there (see screenshots), but it's not consistently reproducable, as I just found out.
Setting the number of decimals explicitly, on the legend tab (thanks!), works fine for us.
Feel free to close this issue if you don't feel the need trying to reproduce it.

**Comment by daniellee** [comment]
@tw-bert I can reproduce this. It seems to be connected to a change we made to the code that calculates the number of decimal places for the y-axis. I added it to the milestone for the next release. Thanks for reporting this!

ref https://github.com/grafana/grafana/commit/3cdf0dce562692ad93125ee09bbc51fe7530c3bc#diff-d93fe1310378a95c4a7cd8787b5052fd

**Comment by chuski92** [comment]
In my particular case, I was showing ping's ms and found the same problem, but now I need to set legend->values->decimals to 3 to see 3 decimals in tooltip or legend. I upgraded from 4.6 to 5.1 also.
But doing that solves it.
