### ISSUE TITLE
Chart Export API for Interpolating Single Charts on Other Websites

### ISSUE THREAD

**Issue by baweaver** [grafana/grafana#1179]
I'd like to be able to get a single chart from Grafana and interpolate it on another page (say, using AngularJS) that binds the data source dynamically.

Ex: We have a page for each Amazon Instance we have and for each page it imports the charts from Grafana to display data about the instance. Bonus points if it can bind to a socket and auto-refresh the data.

Is this currently possible? I can't find anything about an API we could poll for that type of data.

**Comment by anthonywebb** [comment]
I would be interested in this as well

**Comment by torkelo** [comment]
Not sure what you are asking. You could iframe a single graph from grafana on another web page.

**Comment by NorthIsUp** [comment]
is there a way to get a share link that is literally just the graph (and legend as an option)? Or is the gafana header always included?

**Comment by torkelo** [comment]
Not currently, but I did open an issue for it:
https://github.com/grafana/grafana/issues/1334
