### ISSUE TITLE
Singlestat metric is stopping work after reload tab. First open of dashboard works correctly.   

### ISSUE THREAD

**Issue by apolegoshko** [grafana/grafana#11795]
Please include this information:
### What Grafana version are you using?
5.1.0
### What datasource are you using?
Zabbix datasourse
### What OS are you running grafana on?
Debian (Jessie)
### What did you do?
- Create dashboard with several **Singlestat** metrics (4 metrics)
- Open dashboard in other tab (for edit or read). All looks well.
- Hitting F5 (or Ctrl+R) button in just opened tab, and one of metric stop working (showing N/A)
### What was the expected result?
- All metrics showing results (not N/A)
### What happened instead?
- One of metric stop working (showing N/A)
### If related to metric query / data viz:
-
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 -

Hi here, metric stops working after hitting reload button in the same tab or fresh opened tab. Please let me know if you need some claraficiation.

**Comment by woodsaj** [comment]
This is most likely a problem with your zabbix server not returning results for queries.
As requested in the issue template, please include raw network request/responses from your browser.

**Comment by slider90** [comment]
I have the same issue. Problem with 4 and more single stat panels on dashboard, one single stat has N/A value.

When I first enter to dashboard (4 single stats), I have N/A problem with one single stat panel, and have no query from zabbix for single stat panel - only 7 requests (method: "user.login + 3 methods - item.get and 3 history.get) .

But when enter to this single stat panel and refresh -  it works. Then going back - all 4 dashboards work. And refreshing grafana button it works (4 requests with history.get methods), but browser refreshing makes one panel N/A.

**Comment by daniellee** [comment]
@slider90 as @woodsaj requested, can you provide the network requests and response. 

https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630

or

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
