### ISSUE TITLE
Install a plugin without restarting the Grafana server 

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#11807]
Please include this information:
### What Grafana version are you using?
**5.0.1**
### What OS are you running grafana on?
**Cloudfoundry**

I upload some plugin files to data/plugins/, we want to register plugin but don't restart grafana-server, how to do it?

**Comment by daniellee** [comment]
Not currently possible.

**Comment by torkelo** [comment]
Closing this as it’s the same as this feature request https://github.com/grafana/grafana/issues/4843

**Comment by bamb00** [comment]
Hi @daniellee,

I'm using Grafana 4.5.2 and could not restart grafana after installing the pie-chart-panel plugin using grafana-cli.  Is this allow?

Thanks.
