### ISSUE TITLE
Loading large number of Graph panels waits for all to load

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#11806]
When loading a dashboard with large number of panels, the dashboard waits for all them to load and just after they all are loaded, they are shown. The data are already in memory so it would be better that loaded panels are displayed just as soon as they receive the data.

I have tried to record the situation http://g.recordit.co/KG5uHKTNOC.gif You can see the loader disappear for panels that are loaded but they show no data yet.

**Comment by daniellee** [comment]
Sounds like it is related #7452 that was originally merged in Grafana 4.3 but had to be reverted. Might be time to revisit it.

**Comment by simPod** [comment]
Looks a bit similar. But that implements lazyloading – panels do not load before you scroll to them

This is a bit different. They all load, but even though the request for data is finished, they do not show data and wait until all requests are finished.

**Comment by simPod** [comment]
I tried to investigate and found this line

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/module.ts#L209

I don't know what `this.annotationsPromise` does but moving `this.render(this.seriesList);` out of it solves this.

I tried

```js
    this.render(this.seriesList);

    this.annotationsPromise.then(
      result => {
        this.loading = false;
        this.alertState = result.alertState;
        this.annotations = result.annotations;
      },
      () => {
        this.loading = false;
      }
    );
```

**Comment by torkelo** [comment]
Do you have any annotation queries in the  dashboard?

**Comment by simPod** [comment]
Understood. 

But what is the reason it takes so long then? Are you saying that all panels wait for annotations query to complete, right? That would make sense.

So the issue probably is this

![image](https://user-images.githubusercontent.com/327717/39596696-7ef717ee-4f13-11e8-80fb-eec03411354a.png)

I define dashboards using JSON only. I don't use annotations yet so my JSON definition I'm sending via API to Grafana looks like this:

```php
            'annotations' => [
                'list' => [],
            ],
```

The annotation definition in dashboard is therefore shown as 

```json
"annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
```

Shouldn't it at least be queried as the first one then?

(it triggers this request:

> curl 'http://domain.com/grafana/api/annotations?dashboardId=15&from=1525287136790&to=1525373536790' -H 'Accept-Encoding: gzip, deflate' -H 'X-Grafana-Org-Id: 1' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://domain.com/grafana/dashboard/db/dashboard-name?from=now-24h&to=now&var-bucket=1%20minutes&orgId=1' -H 'Cookie: grafana_user=admin; grafana_remember=2d269e041fsd1c65728d3ab21a279e81be6b9c7f165fb02cf661a5ddf61b9a33a0f58; grafana_sess=18f57f8f814sdfsd267f2; _ga=GA1.2.1960542240.1510244623; a98e53615d37a31cc52f76d8ef02a22318bae5df=6f39340f2eaf0d31940625c094bb7e18160d1e30; 6c046e19abae502b6c47ff83a8eb4d8727f7dd4e=5a6baf26a53dda2163a1824a; dd898f14bdc9dab95346cf7057db6ffdb10ba1c8=5a6baf26a53dda2163a18249; __zlcmid=kfh4m42ZhU7Mol; SL_C_23361dd035530_VID=n6Ll-PazkhGY; SL_C_23361dd035530_KEY=6f39340f2eaf0d31940625c094bb7e18160d1e30; SL_C_23361dd035530_SID=pqVj3j1gMIcu' -H 'Connection: keep-alive' --compressed

**Comment by simPod** [comment]
Just checked, it' some default annotation, dunno what exactly is it's role but I guess it has to be loaded after all queries are finished?
