### ISSUE TITLE
Variable Quoting in PostgreSQL queries

### ISSUE THREAD

**Issue by smithje** [grafana/grafana#11800]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What did you do?
* I set up two custom variables: Foo with values a,b,c and Bar with values d,e,f.  Both of these allow multiple selects.
* I set up a row that repeats on the values of Foo. 
* I set up a graph inside the row with postgres as the data source.  I would like to use the locally scoped value of Foo as the column name in my query and the values of Bar in the where clause like so: WHERE x IN (${Bar})
Here is an example query:
    SELECT ${Foo}
    FROM table
    WHERE x in (${Bar})
### What was the expected result?

I would expect the query to look like this:
    SELECT a
    FROM table
    WHERE x IN ('d', 'e', 'f')

### What happened instead?
Instead, the query looks like this:
    SELECT 'a'
    FROM table
    WHERE x IN ('d', 'e', 'f')

The $Foo variable is quoted even though, in this context, it is not multi-valued.  I tried to get around this by specifying the csv formatting, but this causes problems with the where clause.

    SELECT ${Foo:csv}
    FROM table
    WHERE x in (${Bar})

Here is the result from this query:

    SELECT
    a
    FROM table
    WHERE 
    x in (d,e,f)

The csv formatting is applied to $Bar as well, even though I did not specify that.  I don't see a different format from the list that would be appropriate for this case to override the csv for $Bar.

**Comment by daniellee** [comment]
We will be adding a raw mode soon: https://github.com/grafana/grafana/issues/11614

But that the csv formatting is applied to both is a bug.

**Comment by svenklemm** [comment]
I think this affects all datasources but non-sql datasources dont need to control quoting.

**Comment by sanchomuzax** [comment]
What is the solution or workaround of this problem? Thank you!

Database: postgresql
