### ISSUE TITLE
Github auth: doesn't update email in backend when it changes -- UNIQUE constraint

### ISSUE THREAD

**Issue by rwaweber** [grafana/grafana#11818]
Please include this information:
### What Grafana version are you using?
5.0.4
### What datasource are you using?
prometheus, though not really relevant
### What OS are you running grafana on?
Centos 7.4
### What did you do?
I found that after expiring my grafana session(logout) and having my primary email changed on github, when logging back in through the github OAuth flow, I was greeted with an error screen:
<img width="982" alt="screen shot 2018-05-03 at 2 41 56 pm" src="https://user-images.githubusercontent.com/5834777/39596391-3141a06a-4ee0-11e8-928a-4c1ce4d203cd.png">

Upon digging through the logs, I got a couple lines:
```
May 03 17:26:26 grafana.lan grafana-server[17848]: t=2018-05-03T17:26:26+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=10.0.0.15 time_ms=12 size=311 referer=https://grafana.lan/login
May 03 17:26:27 grafana.lan grafana-server[17848]: t=2018-05-03T17:26:27+0000 lvl=eror msg="Failed to create account" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.login"
May 03 17:26:27 grafana.lan grafana-server[17848]: t=2018-05-03T17:26:27+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=10.0.0.15 time_ms=398 size=1710 referer=https://grafana.lan/login
```

Which led me down a bit of a rabbit hole, that ended up being not terribly productive.

I was able to replicate with some users who had recently changed their email with github, but those that hadn't I was unable to replicate with.

Next, I took to looking in the sqlite db that grafana creates to see if there was anything to be gleaned from that, and low and behold I found that the *old* email persisted in the database over the newer one that is retrieved in the request from github.

To test my hunch in an inelegant way, I removed my user from the user table in the database and then logged in again and was successful in doing so.

I imagine that if I just updated my email to the email that is received in the request where the login matches(username), it would've allowed me to log in.

### What was the expected result?
Email address should be updated on subsequent logins if they do not match. Probably using the username as a primary identifier? Haven't looked at the code yet to be able to gauge difficulty.

### What happened instead?
Users whose emails had changed since their original login did not update.

### Next steps
I would be happy to put together a PR to help out with this, just wanted to get all the details down while its still fresh.

**Comment by marefr** [comment]
Thanks for the thorough bug report! Contributions are always welcome.

**Comment by DanCech** [comment]
This can be solved by updating the github oauth module to return an `Id` field in the `BasicUserInfo` struct, which will then be used to track an account even if the email changes.
