### ISSUE TITLE
New  "stack" method for boolean graphs

### ISSUE THREAD

**Issue by tecmatia-dp** [grafana/grafana#11810]
### What Grafana version are you using?
Grafana 5.1.0
### What datasource are you using?
InfluxDB 1.5.0

Hi to all.
Something that is not well resolved in Grafana is the support for boolean or digital variables. It is very useful to be able to combine several variables of this type in the same graph, even with other analog variables. However, the current stack option does not work for this.

We need to achieve this:

![capturaapilardigitales](https://user-images.githubusercontent.com/38155834/39569808-9fdb044a-4ec6-11e8-8e8c-805b9d9f41d0.png)

I have done by modifying the current stack plugin (file jquery.flot.stack.js), and playing with the two axes, but the correct thing would be to have an independent option.

In industrial and IoT environments, this need to visualize analog data (flow rate, for example), and digital data (pumps that produce flow, for example) is very common.

**Comment by hugohaggmark** [comment]
I believe this feature was introduced in Grafana 7.0 with transformations so I'm going to close this issue. 
![image](https://user-images.githubusercontent.com/562238/98772603-668f0a80-23e7-11eb-8b14-b9c233581e1a.png)

Thank You to you for taking the time to create this issue!
