### ISSUE TITLE
Visualize Elasticsearch queries

### ISSUE THREAD

**Issue by hbceylan** [grafana/grafana#11812]
How can I visualize elasticsearch queries?

**Example:** 
**path:** /api/offer 
**value:** backend_processing_time

Grafana version: 5.0.3

<img width="1260" alt="elasticsearch" src="https://user-images.githubusercontent.com/23728382/39576865-4e0b8f32-4ee8-11e8-9cc4-5080f730c819.png">
<img width="1372" alt="grafana" src="https://user-images.githubusercontent.com/23728382/39576866-4e2a93a0-4ee8-11e8-96cd-e4a8ec4292a9.png">

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
