### ISSUE TITLE
Two AWS Cloudwatch healthcheckIds in a single serie, Is it possible?

### ISSUE THREAD

**Issue by PresidentCamacho** [grafana/grafana#11823]
What Grafana version are you using? v4.6.3
What datasource are you using? AWS Cloudwatch
What OS are you running grafana on? Linux (dunno dist)
What did you do? Adding a second dimension in healthcheckid
What was the expected result? The value aggregating (Check two healthcheckid:s in a single serie)
What happened instead? The second healthcheckId disappeared.

I want to add two healthcheckids to a serie like this:

![image](https://user-images.githubusercontent.com/5015774/39618772-8a9882dc-4f85-11e8-8ffe-fabceeea62e9.png)

But when going to another tab and then back again the other dimension will disappear. Is this intended? Is it even possible to add two healthcheckIds to a single serie?

**Comment by marefr** [comment]
Don't think amazon cloudwatch api supports two healthcheckIds to a single serie - have you tried similar query in aws cloudwatch ui? 

Not sure if you want multiple series or aggregate both to one serie. If multiple series one easy way of solving that is to create an additional query by clicking on *Add Query* button.

Would be nice if you could include screenshots when dimension exist and when going to another tab and it disappears. Also, include query inspector request/response for both scenarios.

Thanks

**Comment by PresidentCamacho** [comment]
I've it on a singlestat panel and it doesn't handle two series. Or am I wrong is it possible to aggregate two series in a singlestat panel?

It seems like the request payload only has one healthcheckid in it.

![image](https://user-images.githubusercontent.com/5015774/39622933-3273b8f6-4f94-11e8-832c-3a4acf55f169.png)

**Comment by marefr** [comment]
No there's no support for aggregating data from multiple series in singlestat panel. You need to use a datasource that supports aggregation for these kind of use cases. Seems like cloudwatch api don't support multiple dimensions of same key so closing this. Will consider reopen this if I misunderstood in some way.
