### ISSUE TITLE
Scrollable plugin panels require single root div since 5.1

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11820]
Since 5.1 and the switch to baron scrollbar, it appears that scrollable plugins now behave strangely if the template has multiple root elements.

The baron scrollbars get configured on the first div it finds.  Maybe it could/should automatically wrap things in another div?

https://github.com/grafana/grafana/blob/master/public/app/features/panel/panel_directive.ts#L116

This change affects most of my published plugins... making them have odd behavior in 5.1

**Comment by marefr** [comment]
That's unfortunate. For possible future changes I think it's better that each panel have a root element that they own and control even if it right now requires you to update all your panels.

The whole scrolling implementation is very fragile to changes so I would not like to add a special handling if there are one root element or multiple etc. If you think this can be implemented in an easy and good way I'll considering reopen this issue.

**Comment by ryantxu** [comment]
In #11829, I proposed a change that seems to fix this.  I think it is best to not require plugins to have a single root

```
<div class="panel-content">
-      <ng-transclude class="panel-height-helper"></ng-transclude>
+      <div class="panel-height-helper">
+        <ng-transclude ></ng-transclude>
+      </div>
</div>
```

And:
```
-          let scroller = panelContent.find(':first').find(':first');
+          let scroller = panelContent.find(':first');
```
