### ISSUE TITLE
[Feature request] More flexible size for annotation popup

### ISSUE THREAD

**Issue by tgquan67** [grafana/grafana#11827]
Version: 5
OS: Debian 9
Data source: InfluxDB

Right now, on my dashboards the annotation is being pulled from InfluxDB as pre-styled HTML (and I'm glad that it is rendered correctly). However the width of the popup is limited by default, so it cannot hold something wide like a table (I tried, and it looked horrible). So my only choice is to make it a long flattened list. But that leads to another problem: the popup is so long that it covers all nearby triangle annotation marks, and that makes moving among annotations points quite difficult (unless I have enough space below the marks).
More details: currently my screen can show 3 rows of graph with 4 graphs on each, and the annotation is at least as long as the height of 2 graph panels.

**Comment by marefr** [comment]
This feels a bit like an edge case having pre-styled HTML in annotations. Would a possible solution/workaround be to render a link in annotation instead that you can click to get redirected somewhere to see all relevant information? Another option would be to render annotations in a table panel?

It would be nice if you could provide a screenshot in issue description which pin-points your problem.

**Comment by tgquan67** [comment]
![grafana_annotation_1](https://user-images.githubusercontent.com/3193541/39628211-fda46e5a-4fb0-11e8-8310-b11c878e609e.PNG)
![grafana_annotation_2](https://user-images.githubusercontent.com/3193541/39628212-fdc42b8c-4fb0-11e8-8a3d-a4003d24351f.PNG)
Sorry I removed all text in the photos. As you can see, when an annotation popup appears, it covers some other annotation marks next to it unless there is enough space for it to appear below the marks, and it will only disappear if I move the mouse out of it, which is irritating when I need to check multiple annotations. 
And displaying data immediately from the graphs is exactly what I need, to both the ideas of using tables and using external links are not feasible.
According to my tests, the annotation popup's width cannot go over around 1.5 times what is shown in the photo.

**Comment by torkelo** [comment]
the annotation tooltip is designed for small & short text & links. 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
