### ISSUE TITLE
How to show annotations of prometheus rules in grafana by datasource?

### ISSUE THREAD

**Issue by szediktam** [grafana/grafana#11835]
### What Grafana version are you using?
          Grafana 4.4.0
### What datasource are you using?
          Prometheus
### What OS are you running grafana on?
         Centos7.4 in a container
### What did you do?
         I want to show annotations of prometheus rules in grafana
I set a rule as below:
          - alert: Ceph Osd Down
            expr:  ceph_osd_up{ceph_daemon=~".+"} == 0
            for: 5m
            labels:
              alertgroup: storage
              severity: critical
            annotations:
              description: Ceph osd {{ $labels.ceph_daemon }} down in ceph cluster
              summary: Ceph osd {{ $labels.ceph_daemon }} down in ceph cluster

And I set a prometheus datasource in grafana to connect prometheus.
When I show ALERTS,It only return as below:
ALERTS{alertgroup="storage",alertname="Ceph Osd Down",alertstate="firing",ceph_daemon="osd.1",instance="192.168.15.2:9283",job="ceph-mon",kubernetes_name="ceph-mon",kubernetes_namespace="ceph",severity="critical"} 

I can not get the info of annotations/summary/description to show more info about the alert rule?

Anyway to make it？

**Comment by szediktam** [comment]
Maybe,  the ALERTS dont return the annotations of prometheus rules.

I also cannot put lable such as {{ $labels.ceph_daemon }} into the alertname.like this:
- alert: **Ceph Osd  {{ $labels.ceph_daemon }}  Down**
  expr: ceph_osd_up{ceph_daemon=~".+"} == 0
  for: 5m
  labels:
    alertgroup: storage
    severity: critical
  annotations:
    description: Ceph osd {{ $labels.ceph_daemon }} down in ceph cluster
    summary: Ceph osd {{ $labels.ceph_daemon }} down in ceph cluster

it doesn't work.

Anyway to make it. Thank you in advance.

**Comment by FUSAKLA** [comment]
Metric ALERTS has only labels. If you are interested in annotations you can send then to the Alertmanager and use Alertmanager datasource plugin which allows you to display them.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by szediktam** [comment]
@FUSAKLA   I install the prometheus-alertmanager-datasource, BUT I dont know how to import the alerts. 
The alertmanager datasource only support TABLE and Single. But  in my grafana4.4.0, it occur a error "Cannot read property 'match' of undefined"

How to use it. Thank you.
