### ISSUE TITLE
Graph panel / legend texts shifts on the left each time we move scrollbar on firefox

### ISSUE THREAD

**Issue by tsn77130** [grafana/grafana#11830]
Hi,

Please include this information:
### What Grafana version are you using?
5.1.0
### What datasource are you using?
influxdb
### What OS are you running grafana on?
debian 8
### What did you do?
Scroll table legend in a graph panel
### What was the expected result?
Normal scroll
### What happened instead?
On firefox (not chrome), when we scroll items in legend table, legend texts shifts on the left each time we move scrollbar

Link to screenshot [here](https://www.noelshack.com/2018-18-5-1525440894-capture.png)

**Comment by marefr** [comment]
What version of Firefox are you using? Is this true for all your scrollable legend tables or maybe only those legends having a lot of series?

**Comment by daniellee** [comment]
Could reproduce this:

![image](https://user-images.githubusercontent.com/434655/39702755-1c6d1ae2-5206-11e8-9a8d-428114364aa7.png)

**Comment by or4cle** [comment]
We're having the same issue, using the latest version of FireFox.

**Comment by retzkek** [comment]
@daniellee I upgraded to 5.1.3 but I'm still seeing this:
![image](https://user-images.githubusercontent.com/1627510/40573032-0e34251e-6080-11e8-9af4-f02476727fc2.png)
![image](https://user-images.githubusercontent.com/1627510/40573035-1b411500-6080-11e8-8097-05f51c8f677c.png)

**Comment by avdv** [comment]
For me, 5.1.3 indeed fixed the problem. Maybe you have some stale files in your browser cache? Try in a private tab or clear your cache...

**Comment by retzkek** [comment]
Cache was disabled. It seems to manifest when the legend has a scrollbar.

**Comment by torkelo** [comment]
What version of Grafana are you running? (Check in footer on non dashboard page or in profile sidemenu)

**Comment by cedwardstesla** [comment]
Sorry I forgot to mention that.
```
grafana-server -v
Version 5.1.3 (commit: 087143285)
```

**Comment by torkelo** [comment]
And the browser says the same?

**Comment by cedwardstesla** [comment]
Yep.
![image](https://user-images.githubusercontent.com/22446413/40681279-93cb74e2-633d-11e8-913d-50128931e83a.png)

Firefox 60.0.1

**Comment by tsn77130** [comment]
5.1.3 fixed the problem for me too, with 60.0.1 version

**Comment by marefr** [comment]
Have tried using Firefox 60.0.1 and Grafana 5.1.3 with the following panel

<details>
<summary>Panel json</summary>

```json
{
  "aliasColors": {},
  "bars": false,
  "datasource": "Grafana TestData",
  "decimals": 3,
  "fill": 1,
  "id": 19,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": true,
    "total": true,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "refId": "A",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "B",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "C",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "D",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "E",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "F",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "G",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "H",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "I",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "J",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "K",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    },
    {
      "refId": "L",
      "scenarioId": "csv_metric_values",
      "stringInput": "1,20,90,30,5,0",
      "target": ""
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Legend Table No Scroll Visible",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": [],
    "buckets": null
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "gridPos": {
    "x": 12,
    "y": 58,
    "w": 12,
    "h": 7
  },
  "yaxis": {
    "align": false,
    "alignLevel": null
  },
  "dashes": false,
  "dashLength": 10,
  "spaceLength": 10
}
```

</details>


    
@cedwardstesla please clear your browser cache and do a "hard refresh" of grafana - still same problem?

**Comment by cedwardstesla** [comment]
Strange. I tried a hard refresh, private window, I went to Preferences --> Privacy & Security --> Manage data --> Deleted all data for the Grafana website, still no dice.
Restarted the server Grafana is hosted on in case there was any strange caching there. I double checked the `legend.ts` file on the server and the fix mentioned in the 5.1.3 commit is there. I also tested on Firefox Nightly and it has the same problem.

Not really an urgent issue or anything from my end, just wanted to make sure you guys were aware.

One other observation: separate panel scrollbars seem to be linked somehow. I can make them race each other 😁 

![2018-05-30_10-18-46](https://user-images.githubusercontent.com/22446413/40736619-5fe29064-63f3-11e8-8e2b-3a915d1b9c48.gif)

Let me know if I can grab you any more information from my end.

If I look at the properties the width is constantly expanding but the offset isn't.
![image](https://user-images.githubusercontent.com/22446413/40735885-451f832e-63f1-11e8-97eb-5d080f532430.png)

![image](https://user-images.githubusercontent.com/22446413/40735925-5bbb121a-63f1-11e8-8a05-74421968d560.png)

**Comment by marefr** [comment]
Thanks for the detailed information. 

Was able to kind of reproduce the same behavior. Given 3 panels in a dashboard with a lot of series (scroll visible). Doing only like you did in animated gif I cannot reproduce it. If I edit a panel and add a fixed width of the legend when I go back to dashboard I can reproduce it. If I save the dashboard and reload it I can no longer reproduce it.

Do you happen to have fixed width of legend?

> One other observation: separate panel scrollbars seem to be linked somehow. I can make them race each other 

That's what this issue is about - what other problem are you talking about? 

Regarding my panel you tried had more than one series - strange.

**Comment by cedwardstesla** [comment]
No fixed width.
`sideWidth` is either missing or `null`.
```
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "hideEmpty": true,
    "hideZero": true,
    "max": false,
    "min": false,
    "rightSide": true,
    "show": true,
    "sort": "avg",
    "sortDesc": true,
    "total": false,
    "values": true,
    "sideWidth": null
  },
```

> That's what this issue is about - what other problem are you talking about?

Sorry, thought that was something new, if not ignore me.

For your panel I can see the 10+ queries if I go to edit but they don't show up on the panel.

I'll test installing Grafana on a fresh machine and importing the dashboard later today.

**Comment by jenlersadnie** [comment]
After upgrading to 5.1.3 I'm now having an issue that setting a right-justified legend to fixed width _fixes_ the issue, but having it with an "auto" width, the issue persists. Let me know if you need more information.

Firefox 60.0.2, Grafana v5.1.3 (087143285), totally cleared cache.

**Comment by cartw** [comment]
I still see this issue on 5.2.1 on FF 61.0.1 in cases where the legend requires a scroll bar. On a dashboard with multiple graph panels, if the legend reuires a scrollbar then just moving the mouse over a panel causes metric names to shift left.

**Comment by marefr** [comment]
@cartw make sure that you've cleared the browser cache. Still problem?

**Comment by cartw** [comment]
Hi - yep. Private window and cleared cache. Reloaded the dashboard. Panels with a legend scroll bar still shift the metrics names left when I mouse over/away from the legend. The FF inspector show the width, min-width and max-width elements are all incrementing by 15px each time.
 
Looking a bit more closely, this is happening when no width is set in the Legend options. If I set a width then the same mouse actions result in the scrollbar for the legend intially being close to the metric names but then rather than the metric names moving, the scrollbar moves right until it reaches the edge of the graph panel.

**Comment by marefr** [comment]
@cartw Unable to reproduce. Would recommend you open a new issue with details and instructions for how to reproduce it.

**Comment by PacoDu** [comment]
I'm facing the same issue with grafana 5.3.1 and chrome 70.0.3538.77 and firefox 60.3.0esr but this time the table is moving to the right

**Comment by torkelo** [comment]
Try Grafana nightlies, (available on download page), should solve this issue.

**Comment by starlilyth** [comment]
Grafana v5.3.4 (69630b9) (3 days ago)
Graph is exported to an iframe, and when the number of items in the legend (set to 'table') exceeds the iframe height, a scroll bar appears (good). 

Firefox Version 63.0.1 Build ID 20181030165643 on macOS High Sierra
Scrolling the legend table causes the legend table to grow to the left, over the graph. 

Google Chrome Version 70.0.3538.102 (Official Build) (64-bit) on macOS High Sierra
Scrolling the legend table causes it to shrink to the right. Its slow but it does happen.  

@torkelo @marefr Try it for yourself here with live data: https://gpmfdev.getpimp.org/farmer/7/farmstatus
This is a development site but the page is public.
