### ISSUE TITLE
alert api does not update EvalData values when in "alerting" state

### ISSUE THREAD

**Issue by stuartmclean** [grafana/grafana#11849]
## What Grafana version are you using? 

5.1.0

## What datasource are you using? 

Prometheus

## What OS are you running grafana on? 

Ubuntu (various)

## What did you do? 

call the alert api

## What was the expected result? 

I expect to see differences in the EvalData -> evalMatches data as values change in data being monitored

## What happened instead? 

EvalData -> evalMatches are frozen in their first alerting state - e.g. the value when running "test rule" in the web console displays "1.76" but in the api the value is locked on "1.70" - which is the value which first triggered the alert.

It also means that if a second server triggers the same alert only the first is shown in the api response.
This seems to have happened to all our alerts since upgrading to grafana 5.

**Comment by bergquist** [comment]
That currently how it's working. 

This will be fixed while working on https://github.com/grafana/grafana/issues/6041
Closing this issue since we won't address just this issue.

**Comment by stuartmclean** [comment]
Thanks - I guess this was actually already documented in the “multiple series” notes [here](http://docs.grafana.org/alerting/rules/) - which generally makes sense when it comes to sending notifications - but I still don’t see why the api response could not be updated.
