### ISSUE TITLE
Docs feedback: installation/docker.md

### ISSUE THREAD

**Issue by freko247** [grafana/grafana#11847]
### What Grafana version are you using?
5.1.0
### What OS are you running grafana on?
Linux
### What did you do?
Migrated from 5.0.4 to 5.1.0
### What was the expected result?
According to current documentation only breaking change is the permissions.
### What happened instead?
Grafana database moved from `/var/lib/grafana/data/grafana.db` to `/var/lib/grafana/grafana.db`, so when I started 5.1.0 my configuration was reset. When I moved my old database file to the new location everything worked.
 
Can you update the documentation accordingly?

**Comment by daniellee** [comment]
That sounds wrong - don't think there have been any changes about moving the grafana.db  file.

@xlson can you investigate this?

**Comment by xlson** [comment]
The Grafana database file has not been moved. Could it perhaps be that you have overridden the location of `grafana.db` in a config file that you no longer include? or perhaps in an environment variable?
