### ISSUE TITLE
[feature request] Expose some way for plugins to use standard annotations UI

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11856]
For https://github.com/NatelEnergy/grafana-discrete-panel/issues/28, I am hoping to reuse the standard annotations UI.

Ideally we could post an event like:

```
this.$rootScope.appEvent('show-annotation', {
event: {...},
pos: { pageX: 100, pageY: 200 },
});
```

```
this.$rootScope.appEvent('show-annotation-editor', {
pos: { pageX: 100, pageY: 200 },
});
```

**Comment by daniellee** [comment]
Sounds reasonable. There are a couple of panels that could use this functionality.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
