### ISSUE TITLE
today() as Time Range

### ISSUE THREAD

**Issue by TweetyHH** [grafana/grafana#1186]
Instead of a concrete date in the "from" field in the "custom time range" it would be nice if today() and yesterday() would also be valid values. 
In the consequence it would be posible to have a dashboard which goes from (for example) "today 8:00" till "now" without change every day the concrete date.

**Comment by rsheldon** [comment]
Nice - I'd take it a step further and say today, this week, this month (calendar not 30d) and this year.

**Comment by hotsnow77** [comment]
+1 for today, this week, this month, this year

**Comment by Codesleuth** [comment]
+1 from me too

**Comment by torkelo** [comment]
Implemented! 

Add the today option in dashboard settings / Time picker tab. 
![image](https://cloud.githubusercontent.com/assets/10999/9204441/999daf8a-405d-11e5-97b2-d4c737ee495b.png)

Add `today` to the list (lower case). 

![image](https://cloud.githubusercontent.com/assets/10999/9204459/ae723ce6-405d-11e5-8823-f91d6f45ccf3.png)

Question/Feedback requested:
After time picker option Today has been selected should the time picker say "Today" or "19 hours ago to to now" 

![image](https://cloud.githubusercontent.com/assets/10999/9204488/ec2441b0-405d-11e5-9653-331cfcc816fb.png)

**Comment by Codesleuth** [comment]
Great stuff, thank you! :trophy:

**Comment by hotsnow77** [comment]
Thanks!
I think the time picker should say "Today"

**Comment by KiNgMaR** [comment]
Excellent, thank you! Is it also implemented for "Override relative time" e.g. in the Single Stat panel?

Also, how often are the nightly RPMs built from master?

I would prefer seeing "Today" over "Last X hours" in the time picker.

**Comment by torkelo** [comment]
This feature is being remade (and with different config syntax to support more variants), the reason for the change is to support things like "The day so far", "Yesterday", "This day last week" 

Today: will show the whole current day (midnight to midnight), and syntax will be 
`now/d to now/d`

Day so far will be
`now/d to now`

**Comment by KiNgMaR** [comment]
awesome! :+1:

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9975663/be0ed83c-5ec4-11e5-9348-a5b4680b109a.png)
