### ISSUE TITLE
 Error - Login error: read tcp 10.2.118.134:37906->000.000.00.000:1433: read: connection reset by peer

### ISSUE THREAD

**Issue by MarcosAugustoOliveiraSilva** [grafana/grafana#11861]
Grafana Version: Grafana - 5.1.1
Datasource: Microsoft SQL Server
SQL Server Version: 2017 Developer Edition (64-bit) on Linux (Ubuntu 17.10)  
OS: Ubuntu 17.10
Object: Create a datasource(Microsoft SQL Server) and connection with host
Expected result: Successful connection with host
Erro: Login error: read tcp 10.2.118.134:37906->000.000.00.000:1433: read: connection reset by peer

![image](https://user-images.githubusercontent.com/26351465/39723785-47c5bb1a-521d-11e8-9175-732811b92a60.png)

![image](https://user-images.githubusercontent.com/26351465/39723665-ea0c39ae-521c-11e8-9481-7528361c9366.png)

![image](https://user-images.githubusercontent.com/26351465/39723705-0685334c-521d-11e8-9356-35513579a485.png)

**Comment by marefr** [comment]
What version of sql server? 2008? Have you read [known limitations](http://docs.grafana.org/features/datasources/mssql/#known-issues) in documentation?

**Comment by MarcosAugustoOliveiraSilva** [comment]
Good Afternoon @marefr, i've already read documentation and created the grafanareader user with the right privileges.
Sometimes when i try a lot to connect, the error `Error - Login error: read tcp 10.2.118.134:37906->000.000.00.000:1433: read: connection reset by peer changes` to `Login error: EOF`, but i'm not using SQL server 2008, so i don't need to install MSSQL 2008 R2 Service Pack 2 ,MSSQL 2008 Service Pack 3 and Cumulative update package 3 for MSSQL 2008 SP3.

**Comment by marefr** [comment]
So what version of SQL server are you using? `SELECT @@VERSION` and paste here.

**Comment by marefr** [comment]
That's the exact same version as we're using when developing/testing the mssql datasource on linux. So I would guess that your problem is network related. Any firewalls? Can you ping sql server instance from grafana server?

**Comment by MarcosAugustoOliveiraSilva** [comment]
Sorry for delaying to respond, we were having problems with the server, but now it is normal, here is the test, ping is normal

![image](https://user-images.githubusercontent.com/26351465/40250960-4c6861ec-5aae-11e8-9a3c-67d76c7d70ae.png)

**Comment by andreluna** [comment]
I get the same problem, when I do the command line connection from Grafana server to the Microsoft SQL Server server the connection usually happens, either by Telnet on port 1433 or by a Python script I did to fetch data in the database data. For Grafana the connection does not happen, any help?
![grafana](https://user-images.githubusercontent.com/2491448/40548830-338bd5e2-600c-11e8-8714-9266f13e8bb1.png)

**Comment by andreluna** [comment]
![grafana2](https://user-images.githubusercontent.com/2491448/40549668-7b2ca8c0-600e-11e8-996e-5dc4ef097e50.png)
no custom configurations.

**Comment by torkelo** [comment]
did you get it to work? We have no other similar reports so closing this (hoping it's a network issue on your end)

**Comment by andrconstruction** [comment]
I am faced with same problem. Version 10.50.1600.1. Has the same error

**Comment by marefr** [comment]
@andrconstruction Please upgrade to latest service pack. We have a [known issues](http://docs.grafana.org/features/datasources/mssql/#known-issues) section in our documentation.
