### ISSUE TITLE
Configure default values for panels

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11864]
It should be possible to configure new default values per panel type. So the Grafana Admin can configure new default values for ex `line fill`, `line width` without modifying the default values for the panel in the frontend code. 

A simple solution for this would be to read json files from disk and extend the panels default with those values before extending with the values from the dashboard.json.

`panel default -> json from disk -> dashboard.json`

**Comment by RichiH** [comment]
Did you create this based on discussions with me, or David, during KubeCon? What is this magic? It's even down to roughly the same hour of creation!

**Comment by bergquist** [comment]
Making your work obsolete is one of my main objectives.

**Comment by RichiH** [comment]
Funny same here!

Sent by mobile; please excuse my brevity.
