### ISSUE TITLE
[Feat] MSSQL Integrated Security

### ISSUE THREAD

**Issue by J-den-Boer** [grafana/grafana#11876]
### What Grafana version are you using?
v5.1.1
### What datasource are you using?
MSSQL
### What OS are you running grafana on?
Windows 2012R2
### Feature request
Being able to setup a data source using Integrated Security including Encrytion.
For example an jdbc url: jdbc:sqlserver://myhost.acme.com:1433;databaseName=myDB;integratedSecurity=true;encrypt=true
### What was the expected result?
Connectivity to the MSSQL database server using the credentials of the Grafana service.

**Comment by ramiro** [comment]
This would need to wait for [denisenkom/go-mssql](https://github.com/denisenkom/go-mssql) to support the feature.

As of today, its [README](https://github.com/denisenkom/go-mssqldb#features) file states:

> * Supports SQL Server and Windows Authentication
> * Supports Single-Sign-On on Windows

it still doens't support integrated auth on non-WIndows platforms. See also https://github.com/denisenkom/go-mssqldb/issues/54#issuecomment-50568862

**Comment by Akabell95** [comment]
Hi there!
Any updates on this?

**Comment by danyvas** [comment]
Hi,

Any updates on this?
