### ISSUE TITLE
[UX/UI] Make stacked and left/right axis easier to discern in graphs

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11871]
@davkal as per our chat at KubeCon.

It is currently very hard to discern what specific lines in a graph mean just by looking at them. I propose the following changes to the defaults:

* Use fill only in stacked graphs
  * Optionally autodetect sum() in Prometheus or other pre-Grafana sum/stack to activate fill, or at least suggest it
* Use line width 3 for left axis
* Use line width 1 for right axis

**Comment by RichiH** [comment]
PS: I am fully aware that this would attach even more state to axes as opposed to time series (via overrides), but in my opinion this would be a Good Thing(tm) and actually help with clean design of dashboards.

**Comment by davkal** [comment]
IMO fill in non-stacked line graphs is an anti-pattern, as the potential is quite high for information to be hidden.
Perhaps we should attach logic to unset fill in non-stacked by default. And if users like fill for aesthetic reasons they need to actively choose it.

I do like the idea of distinguishing the left vs right axis lines. I'll have a play of how that will actually look.

As for the query-dependent suggestion, for now I find it hard to see how this can be done in an non-annoying way (both on a UX and implementation level). I'll have a think.
