### ISSUE TITLE
[UX/UI] Global defaults for graph look & feel

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11872]
@davkal as per our chat at KubeCon.

Related to https://github.com/grafana/grafana/issues/11871
Being able to define global defaults / overrides would be useful. Let's say I always need my left axis to have line fill 2 and line width 4, it would be nice to be able to set this from a central place.

This would have obvious implications on "Export as JSON" etc as users may want to export those defaults along with the actual dashboard/graph.

**Comment by bergquist** [comment]
Dupe of https://github.com/grafana/grafana/issues/11864 unless you think I missed something?
