### ISSUE TITLE
Change admin password view after first login

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#11882]
This will be a second step the first time a user logs in to Grafana.
After logging in the user will come to a second view and be instructed to change password. 

![newuserchangepassword_v3part1](https://user-images.githubusercontent.com/23470681/39763285-fcf8bbda-52dc-11e8-9e8e-77bae962e7ad.png)

**Comment by zkry** [comment]
I would like to work on this if no one else is.

**Comment by grrywlsn** [comment]
Is it possible to disable this prompt? I can't find a flag to do so.

**Comment by marefr** [comment]
@grrywlsn no not possible. Change password and it's gone.

**Comment by bergquist** [comment]
If you change the default admin password to something else this popup wont appear http://docs.grafana.org/installation/configuration/#admin-password

**Comment by grrywlsn** [comment]
@bergquist thanks for the link. Is it likely a flag will be added to disable the popup? 

I deploy Grafana immutably (config loaded at startup time), so it seems a valid use case to disable it for the few times I might log in as admin (and don't care if others might know its password).

**Comment by bergquist** [comment]
I think it makes sense to provide a config option for this. Makes the experience of turning it off much better for the operator. We should open a new issue for that.

**Comment by DanCech** [comment]
I'm not a fan of anything that encourages users to leave the default admin password in place in the config

**Comment by grrywlsn** [comment]
That's assuming that all users might benefit from the admin password being changed, which isn't true in my case.

Perhaps it's best to default the prompt to on (as it is) but allow an override flag to disable it if it's not required.

**Comment by DanCech** [comment]
Changing the existing `[security]` `admin_password` setting to something other than `admin` will prevent the popup from being displayed.  The only reason I can see for adding (yet) another config setting would be for someone who needed to keep the admin user password set to `admin`, which seems unlikely.

**Comment by whirlwin** [comment]
Another alternative is to enable anonymous access. What's the point of having the admin user if everyone knows the username/password combination anyways?

In grafana.ini:
```
[auth.anonymous]
enabled = true
org_name = <name of the organization>
```

Or using env variables:

```
GF_AUTH_ANONYMOUS_ENABLED=true
GF_AUTH_ANONYMOUS_ORG_NAME=<name of the organization>
```

**Comment by yisonPylkita** [comment]
Ready to use idea of @whirlwin  for anyone using Docker image for this
```bash
docker run -p 3000:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true grafana/grafana:7.5.4
```
then go to localhost:3000 and voilà

**Comment by 6harat** [comment]
one observation is, if you override the password while starting using ENV variable `GF_SECURITY_ADMIN_PASSWORD=foobar`, the reset password screen doesn't show up on first time login.
