### ISSUE TITLE
EL 5.5 and 6.0 geopoint - Worldmap plugin

### ISSUE THREAD

**Issue by rsliotta** [grafana/grafana#11881]
Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 

Hello we have both Elasticsearch 5.5 and 6.0.

6.0 works perfect, but 5.5 does not. After investigating we found that the rest call returns 2 formats:

5.5 returns a field called GEO like:

      "GEO" : {
        "lon" : 100.99,
        "lat" : 13.36
      },
and 6.0 returns a field called GEO like:

"GEO" : "13.45,101.03"

Can you suggest either a fix or how we can fix it?

**Comment by daniellee** [comment]
What does your query look like? It sounds like you are not using the geohash functionality: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html

Here is a query for geohashes on ES 5:

![image](https://user-images.githubusercontent.com/434655/39998045-19d2e3f0-5785-11e8-932b-c84868745647.png)

and:

![image](https://user-images.githubusercontent.com/434655/39998078-32a536ee-5785-11e8-92a3-92b2833ee2ce.png)

The data returned from this query is in this form (similar to the response described in the ES docs):

```json
 {
    "1": {
      "value": 2
    },
    "key": "sze",
    "doc_count": 2
  }
```

**Comment by daniellee** [comment]
Closing this issue due to no response for a few weeks.
