### ISSUE TITLE
Macros not resolved in Query variables

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#11886]
Tried to use macros like `$from` or `$interval' with Postgres datasource in Query variable. It seems like it is not supported and the macro is not being resolved.

So `SELECT $from` is sent to DB as `SELECT $from` instead of `SELECT '2018-05-08T...`

I guess this is feature request then (?) It is not mentioned in http://docs.grafana.org/reference/templating/ that it shouldn't work though.

**Comment by marefr** [comment]
Please read the [postgres documentation](http://docs.grafana.org/features/datasources/postgres/#macros). Seems like you mixed up the concepts of macro functions and template variables.
