### ISSUE TITLE
Sorted all series value tooltip

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#1189]
Would it be possible to have the series sorted in the tooltip as they are in the table view ?

**Comment by languitar** [comment]
+1

**Comment by ecables** [comment]
+1

**Comment by Dieterbe** [comment]
+1

**Comment by hcooper** [comment]
Is this the sort of thing people are after?
https://github.com/grafana/grafana/pull/3117

**Comment by erikformella** [comment]
yaaaa!

**Comment by mvadu** [comment]
+1 @torkelo  sorry for creating a duplicate

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/3165

**Comment by Akeru** [comment]
:+1: Thanks !

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/commit/b939a27a8dcdbd6a405a270784692ad226a84d8b
reverted.

**Comment by mvadu** [comment]
@bergquist @torkelo  Can we reopen this issue, so that we know this is in the pipeline for a future fix?

**Comment by Gueust** [comment]
Does this feature will be inserted again, after the revert ? It is unclear if the feature has been considered unwanted, or if it has been forgotten after the revert.

**Comment by torkelo** [comment]
@Gueust after using it for a day it was reverted because just made inspecting series values as you hover impossible as they keep jumping around

**Comment by Gueust** [comment]
I see. But that was the point ^^ For instance being able to identify the top CPU using machines among tens of machines. 
Since it was disabled by default, I do not really see the problem (if you do not want the order to change at every point, just do not enable it). But it is also understandable to only include features that provides a real and important bonus.

**Comment by hcooper** [comment]
I'm not aware it was ever optional (at least when I was working on it).
Being able to toggle it on or off would be a good feature for someone to
add though.

On 28 April 2016 at 13:44, Gueust <notifications@github.com> wrote:

> I see. But that was the point ^^ For instance being able to identify the
> top CPU using machines among tens of machines.
> Since it was disabled by default, I do not really see the problem (if you
> do not want the order to change at every point, just do not enable it). But
> it is also understandable to only include features that provides a real and
> important bonus.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/1189#issuecomment-215554060>
>



-- 
Coops

**Comment by bergquist** [comment]
This will be available in 3.1 as an option. Thank you @hcooper and @Gueust for helping put!
