### ISSUE TITLE
Automatic redirect to sign-in with OAuth

### ISSUE THREAD

**Issue by Nick-Triller** [grafana/grafana#11893]
# Motivation

In case Grafana authentication uses OAuth only, the user still needs to press the "Sign in with OAuth" login button. I think it would be worthwile to have the option of skipping the login screen altogether. Another person was seeking the same functionality [here](https://community.grafana.com/t/skip-the-login-screen-all-together/4687).

![image](https://user-images.githubusercontent.com/6010357/39801141-78b5b380-536a-11e8-9853-dbe7ba67a805.png)

# Proposal

I propose a configuration option "AUTH.OAUTH_AUTO_LOGIN" which makes the frontend try to login with OAuth automatically without having to press a button first.

# Implementation

I will be happy to take on the implementation if there are no objections to the feature itself.

**Comment by daniellee** [comment]
Sounds good. We would accept a PR for this.

**Comment by marcelfischer** [comment]
+1

**Comment by marefr** [comment]
Fixed by #12029
