### ISSUE TITLE
After importing dashboard json file max function in graph metrics query changed to mean and one of WHERE conditions missing

### ISSUE THREAD

**Issue by evgenyf** [grafana/grafana#11895]
I've tried to use following grafana versions: 2.6, 3.0.4, 3.1.1, 5.1.1
OS: Ubuntu
Datasource: InfluxDb
I imported attached json file that contains dashboard with one graph.
This graph has metrics query with sum and two where conditions: 
("space_name" = 'MYSPACNEWEXPORTEDONE' AND "space_active" = 'true').
But now when graph displayed matrics query has only first WHERE condition of two and sum was changed to mean.
It can be seen in both metrics query edit modes.
BTW: until query edit mode is not changed original json file displayed when I try to see dashboard json file ( Share -> Export - View JSON ).
Screenshots are attached as well.
Thank you,
Evgeny

[dashboard_one_element.zip](https://github.com/grafana/grafana/files/1986914/dashboard_one_element.zip)

[screenshots.zip](https://github.com/grafana/grafana/files/1987009/screenshots.zip)

**Comment by torkelo** [comment]
The raw query editor mode does not update the UI mode. So when you switch between raw query mode and UI editor you lose your changes. 

similarly if you edit the query property in the json and then import that will not have any effect as it will be overritten by the query model. You need to switch query editor mode and stay in text mode
