### ISSUE TITLE
Having a long title that doesn't fit in one line breaks panel height calculation

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#11905]
When having a long title that doesn't fit in one line, the height of the panel is still calculated as if it still had one line header

You can see that when repeating the panels, the first one is overlapped by the second one in the grid

![image](https://user-images.githubusercontent.com/327717/39871302-a6c7c7ae-5464-11e8-9d0b-08cd6d57c9e7.png)

**Comment by torkelo** [comment]
thanks for reporting this. Need to hide the rest of the title in case it's to long:

overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;

**Comment by marefr** [comment]
Fixed by #12142
