### ISSUE TITLE
[UI] Scrolling on mobile does not hide browser's navbar

### ISSUE THREAD

**Issue by nmaggioni** [grafana/grafana#11909]
### What Grafana version are you using?
5.1.2

### What datasource are you using?
N/A

### What OS are you running grafana on?
Debian

### What did you do?
Open a dashboard on a mobile device (Chrome on Android, specifically), and try to scroll down in order to hide Chrome's tabs and url bar.

### What was the expected result?
Chrome's navbar should have hidden while scrolling down, as it did with the layout Grafana had in _v4.6.3_.

### What happened instead?
Chrome's bar did not hide, since the page itself is not being scrolled: only the content of the central dashboard's container is being moved (the _div_ with classes `scroll-canvas scroll-canvas--dashboard`) while the rest of the page (header and left sidebar) remains still.

With the new UI introduced since Grafana _v5.0_, Chrome does not detect any scrolling and consequently does not hide the title bar - **this makes it impossible to use Android tablets to show dashboards without also showing the rest of the browser's UI**.
Kiosk mode unfortunately suffers the same issue, even though the top and side bar are correctly hidden and only the content of the dashboard itself is on screen.

---

Maybe the scrolling container could be removed in kiosk mode, so that the old scrolling behavior could be reintroduced in mobile browsers?

Or maybe I'm missing something and there's a simpler way to hide Chrome's tabs/navbar on Android? Maybe there's another browser that could do this? Firefox (both standard and Focus) seems to be behaving the same way.

**Comment by daniellee** [comment]
Not sure if we are going to fix this - I think this was done on purpose (makes it easier to navigate on mobiles - especially with large dashboards) and kiosk mode on a tablet seems like a niche use case to me.

cc @torkelo @davkal any opinion on this?

**Comment by davkal** [comment]
I am in favor of keeping the mobile experience in line with how other webapps/native app work. Scrolling is a big part of mobile, and so is careful use of real estate. The suggestion to simply not use the scroll wrapper sounds good. I'll take a look once I dig out my Pixel. 

@nmaggioni what can you tell me about your dashboard structure (how many rows, panels/per row, panel types)?

**Comment by nmaggioni** [comment]
It mostly is a 3x4 grid, using graphs, gauges and single values. A screenshot is surely worth more than words, so here it is! I decreased the browser's zoom in order to fit all the rows in one view.

![cattura](https://user-images.githubusercontent.com/3594528/39994136-a6ddb728-5778-11e8-9dcf-d3c65601b76c.JPG)

**Comment by torkelo** [comment]
Seems like the only way to fix this is to remove fixed dashboard header on mobile.

**Comment by hamid-elaosta** [comment]
It really should be able to hide the browser address bar. I can't see any reason you'd have to remove the header bar to do so, here's an example of it done and working just fine with a persistent header bar and still hiding the browser address bar; https://www.home-assistant.io/demo/ (open on mobile, obviously to see what I mean)

**Comment by nmaggioni** [comment]
@hamid-elaosta Not sure how you're doing it, on the tablet that I'm testing this onto the Chrome's tab/address bar is not hiding when scrolling, even in Home Assistant's demo instance.

I'm using the latest Chrome for Android version _(v69.0.3497.100)_ on _Android 6.0.1_.
