### ISSUE TITLE
[FeatureRequest] Variables: Add query string advanced formatting option

### ISSUE THREAD

**Issue by harshitha-m** [grafana/grafana#11902]
What Grafana version are you using?
5.1
What datasource are you using?
Mysql
What OS are you running grafana on?
Windows
What did you do?
Case:
Drop down Multivalue variable : "Location"
A table which has  "Used Devices" in the specified Location (From drop down) and within the time range   

When i click on the a particular Device , Im directed to the "Device Details" Dashboard

What was the expected result?
ISSUE 1)I should be able to include Time Range in the URL of clickable cell .Hence should get the same time range in new Dashboard
ISSUE 2)When i include Multivalue  Location variable in URL of clickable cell .This  "var-Location=Loc1&var-Location=Loc2 " should be in the URL .Hence Location drop down in Device Details Page should have "Loc1+Loc2'

What happened instead?
ISSUE 1)I did not Find any Option or method to include the time range
ISSUE 2)I Find "var-Location=Loc1,Loc2".Hence getting the same in Location Drop Down.

**Comment by daniellee** [comment]
Partial duplicate: #9291

**Comment by daniellee** [comment]
This is something we should implement and we would definitely accept a PR for it.

We should add a formatting option for query string variables here:

http://docs.grafana.org/reference/templating/#advanced-formatting-options

**Comment by aryabov18** [comment]
The table panel, like other panels, has the drilldown link configuration which supports passing variables and time frame.
Why just don't add the ability to use the base drilldown link inside the cell link definition with adding the value of the current cell. Like that:
$__drilldown_1&var-instance=$__cell
The change should be simple to implement.

**Comment by kejingl** [comment]
Any update on developing a feature to handle ISSUE 2)?

**Comment by hugohaggmark** [comment]
I can see how this is a valuable feature anytime you're using multi value variables in any kind of link.

**Comment by hugohaggmark** [comment]
I just found out that `${__all_variables}` can be used in links, which was first introduced in #17267. If I'm understanding this issue correctly, then this issue is solved, so I'm closing this issue.

Thank You to you for taking the time to create this issue!
