### ISSUE TITLE
Unable to do any aggregation / calculation of metrics for simplejson datasource

### ISSUE THREAD

**Issue by sam5558** [grafana/grafana#11903]
Please include this information:
### What Grafana version are you using?
v5.1
### What datasource are you using?
Simplejson (sadly ..)
### What OS are you running grafana on?
Centos7
### What did you do?
I'm trying to aggregate two metrics and use them in widgets like simplestat or graphs.
### What was the expected result?
Seems like grafana is relying on datasources to do this job, but sadly i was unable to aggregate multiple metrics or do any simple calculation for them

Also, note that i tried to use the [metaquery](https://github.com/GoshPosh/grafana-meta-queries), but sadly it just won't work ...

![image](https://user-images.githubusercontent.com/26897744/39866956-a31754fe-544a-11e8-986d-9f8fd50f787e.png)

**Comment by daniellee** [comment]
SimpleJSON is exactly that, simple. It does not do aggregations as that is specific to the underlying data source. Either you have to aggregate on your backend or fork the SimpleJSON datasource and add them yourself (which is very common to do - lots of the external datasource plugins are forks of SimpleJSON).
