### ISSUE TITLE
How to select all the data of variables into a SQL list？

### ISSUE THREAD

**Issue by cybfly** [grafana/grafana#11906]
Hello everyone, Thanks for your time:
I am using Grafana V5.1.0.
up{host="10.0.0.1", instance="xxx"}   up{host="10.0.0.2", instance="xxx"}
Assume i have a variable named hosts such as label_values(up, host), the value return is:
  ==> "10.0.0.1","10.0.0.2"
Now i wanna use this in my SQL script: 
  ==> select ip from ip_table where ip not in ("10.0.0.1","10.0.0.2")

I tried to use "ALL" option for my hosts.
How can i set it to "ALL" forever?
Or is it possible for me to format the label_values(up, host) into one variable  ("10.0.0.1","10.0.0.2")?
Because i don't need one single value of this list, i need all of them.

I checked the glob/regex/pipe/csv/lucene in  "Advanced Formatting Options".
But i can not find the right way.
![image](https://user-images.githubusercontent.com/1582140/39871782-820939f0-5498-11e8-8906-fc1956e7e8b4.png)

![image](https://user-images.githubusercontent.com/1582140/39871863-c56d3e9e-5498-11e8-8208-d0d5e3c6d1d1.png)

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by cybfly** [comment]
Sorry @torkelo
