### ISSUE TITLE
[UX/UI] Offer upper/lower/mean/median/percentile/current horizontal annotation

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11911]
@davkal 

This is loosely related to
* https://github.com/grafana/grafana/issues/9084
* https://github.com/grafana/grafana/issues/9085
* https://github.com/grafana/grafana/issues/11910

Being able to compare e.g. spikes automatically without mouse-overing specific graphs would be quite useful. While having the ability to define those through Prometheus, or some other backend, the low-hanging fruit would be to use the data Grafana already has and compute horizontals based on that.

This will obviously become really crowded if there's more than a few time series per graph panel, but that's easy to work around in daily operations by decreasing the amount of thoses.

**Comment by davkal** [comment]
I'd quite like you to draw this for me :) @RichiH 

What's also important, would your run those stats across the displayed range, or sliding windowed (I imagine this would get really busy)?

A common technique to add this to a graph is different background shades (red/amber/green), but that would need us to interpret what the bands represent, i.e., which band is green (or make this super-configurable).

**Comment by RichiH** [comment]
Are you in London this week by any chance? I can also sit down with Tom in persona and hangout you in.

This can become _very_ crowded, but so can a lot of other things in Grafana. User discretion advised.

**Comment by RichiH** [comment]
PS: It would always be computed over the displayed data.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
