### ISSUE TITLE
Cannot remove $timeFilter

### ISSUE THREAD

**Issue by nzhammer** [grafana/grafana#11923]
I have a graph in Grafana where I want to remove $timeFilter because I need to see all of the data on that graph, not only the data from the $timeFilter. I toggle edit mode, delete WHERE $timeFilter, and then click out of the box. In all other cases, that causes the graph to show my changes, but nothing happens. I need to be able to delete $timeFilter so that I can see all data queried from the beginning of time.

Please include this information:
### What Grafana version are you using?
v5.1.0 
### What datasource are you using?
influx
### What OS are you running grafana on?
ubuntu
### What did you do?
removed WHERE $timeFilter
### What was the expected result?
To be able to see the data without the $timeFilter
### What happened instead?
I could still see the data with the $timeFilter applied

**Comment by daniellee** [comment]
Works for me.

With time filter returns 61 values:

![image](https://user-images.githubusercontent.com/434655/39988161-edd6465c-5766-11e8-82c3-ba4bdb731f00.png)

Without time filter returns 1508 values:

![image](https://user-images.githubusercontent.com/434655/39988251-2ad721de-5767-11e8-8b9e-96a9b3b05f97.png)

Can you not just choose a large time interval - last 50 years? This approach will not work very well with the graph panel which is built on the time interval from the time picker. The data returned is for all time but the x-axis will still show what you have chosen in the time picker (last 1 hour or whatever).

**Comment by nzhammer** [comment]
I'm not in a place where I can verify at the moment, but I'm guessing the issue was that it actually was querying the full data set, but the x-axis does not update. Will we ever be allowed to have an x-axis that doesn't have to adhere to $timeFilter? I need to see big trend graphs alongside $timeInterval data.

**Comment by torkelo** [comment]
x-axis will adhere to the dashboard or panel time range
