### ISSUE TITLE
Merge multiple queries in table view

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#11922]
Grafana: 5.0
Backend: influxdb
OS: CentOS 6

For a panel, I want to have multiple columns for values from multiple queries. e.g.
Query A:
SELECT MAX(rx) AS packets FROM interface WHERE instance = 'bond0' and type = 'if_packets' AND time > now() - 24h GROUP BY host
Query B:
SELECT MAX(rx) as bytes FROM interface WHERE instance = 'bond0' and type = 'if_octets' AND time > now() - 24h GROUP BY host

If I use a "Table" to show this, I end up with 4 columns:
time, hostname, packets, bytes
The lines for packets/bytes share the same time and where a row has a value for packets, it does not have a row for bytes.

What I would like to see is grafana merge lines that have a common time field - or at least provide the option to specify which columns you want to merge on.

Using "Time series" output does not get me any closer to what I want to see as output.

**Comment by daniellee** [comment]
I don't think we will be implementing this in Grafana any time soon. Feels like this belongs in the data source.

See joining series in the InfluxDB docs on how to do this in your InfluxDB query instead: 

https://docs.influxdata.com/influxdb/v0.8/api/query_language/#joining-series

**Comment by yellowpattern** [comment]
In both of the examples on that page, a single value is the end result 
of the join.

**Comment by marefr** [comment]
It should already be implemented in #10050. Given that your rows you want to merge have the exact same time returned from influxdb - you can check this using the query inspector.

There's an example here using Prometheus: https://play.grafana.org/d/000000065/prometheus-console-tables?panelId=2&fullscreen&edit&orgId=1&tab=metrics

I tried to build a merged table using 2 influx db queries on play.grafana.com, but we may some issues with the data there - I always got different times for two queries even if the queries was the same.

**Comment by daniellee** [comment]
I didn't know we had this already. I built a dashboard on the play site showcasing it:

https://play.grafana.org/d/Zzlfq17mk/influx-table-merge?panelId=2&fullscreen&edit&orgId=1

Closing this as it is already implemented.

**Comment by yellowpattern** [comment]
Yes 10050 is what I want to do! It just doesn't work with influxdb as a 
source - is it prometheus only at present?

**Comment by daniellee** [comment]
It does work with InfluxDB if the timestamps match up, it is in the table data format and the fields are named differently. Use the alias function to give different field names. I updated the example on play to use aliases: https://play.grafana.org/d/Zzlfq17mk/influx-table-merge?panelId=2&fullscreen&edit&orgId=1

**Comment by FdeFabricio** [comment]
@daniellee I managed to join two queries in one table but when I order the values, it doesn't do it properly. Any thoughts of how to solve it?

![](https://user-images.githubusercontent.com/1853854/48350522-a1320100-e66e-11e8-86e3-bd90e61b53a8.png)

**Comment by orena1** [comment]
Hi @daniellee do you know how to do it with Grafana 7.0? which has a new table plugin... Thanks

**Comment by PyvesB** [comment]
Unfortunately, this doesn't seem to work anymore. Here's what I get when I open the "Influx Table Merge" example previously linked:
<img width="1025" alt="Screenshot 2020-07-29 at 12 47 06" src="https://user-images.githubusercontent.com/10694593/88791274-bf6cc700-d199-11ea-925b-79e334034ebb.png">

**Comment by torkelo** [comment]
Can you show the raw data for both queries?

**Comment by PyvesB** [comment]
> Can you show the raw data for both queries?

I don't know what the raw data for the queries is. I simply opened the [official example](https://play.grafana.org/d/Zzlfq17mk/influx-table-merge?editPanel=2&orgId=1&from=now-1h&to=now) as I wanted to reproduce this in my own Grafana instance, but observed that the example wasn't working as expected.
