### ISSUE TITLE
Cloudwatch panel does not allow arbitrary variable values in query

### ISSUE THREAD

**Issue by cyberw** [grafana/grafana#11925]
I query cloudwatch with a Custom Variable as instance id (Dimensions: InstanceId = $instanceId).

This works fine when the value of the variable is one of the pre-configured ones, but when I type something else into the dashboard it doesnt work (it queries the previously configured value or selects the top pre-configured one if I reopen the dashboard with a `&var-instanceId=<some value not present in the custom variable configuration>` in the url)

I can use arbitrary variable values for other things (panel title, WHERE-clause for influx queries etc) without issues.

Grafana v5.1.2 (c3c690e21), CentOS

**Comment by daniellee** [comment]
Not sure if I understand as this worked for me. I typed `ddd` into a variable and then checked the query that was sent to Cloudwatch in the the network tab in Chrome. The dimensions field with value `ddd` was sent to Cloudwatch:

```json
{"from":"1525696218319","to":"1526301018319","queries":[{"refId":"A_","intervalMs":300000,"maxDataPoints":1622,"datasourceId":44,"type":"timeSeriesQuery","alias":"","application":{"filter":""},"dimensions":{"ddd":""},"functions":[],"group":{"filter":""},"host":{"filter":""},"item":{"filter":""},"metricName":"NetworkPacketsOut","mode":0,"namespace":"AWS/EC2","options":{"showDisabledItems":false},"period":"600","region":"aregion","statistics":["Average"]}]}
```
![image](https://user-images.githubusercontent.com/434655/39997765-4cce5b32-5784-11e8-87c0-16d38f511710.png)

**Comment by cyberw** [comment]
Hi!

The issue is with the dimension value (right hand side), not the dimension key. Dimension key works as it should.

**Comment by cyberw** [comment]
@daniellee were you able to reproduce it now?

**Comment by daniellee** [comment]
This is due to [this line](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.ts#L377) which only uses the variable `options`. This code would have to be changed to look at the `current` value as well.

**Comment by mtanda** [comment]
@daniellee please check https://github.com/grafana/grafana/pull/11990

**Comment by cyberw** [comment]
Cool stuff!

Looking forward to seeing this in a release!
