### ISSUE TITLE
Alerting: Add Flowdock Notification Channel

### ISSUE THREAD

**Issue by waltsu** [grafana/grafana#11932]
**Feature request**

[Flowdock](https://flowdock.com) is a team inbox with chat. It brings all of your conversations, work items and tools into one place.

It'd be great to support alerting to Flowdock via POST to [REST API](https://www.flowdock.com/api)

**Comment by bergquist** [comment]
This will have to wait until we support backend plugins. https://github.com/grafana/grafana/issues/6841 We are currently not accepting new alert notifiers unless proven really popular.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
