### ISSUE TITLE
Single stat on Chrome has Scroll Bar with 2px

### ISSUE THREAD

**Issue by ThomasRunting** [grafana/grafana#11937]
Please include this information:
What Grafana version are you using? Latest Docker Image
 What datasource are you using? PRTG
 What OS are you running grafana on? Docker on Ubuntu server 16.04

On Edge
![2018-05-15 10_51_32-microsoft edge](https://user-images.githubusercontent.com/2153950/40030487-3257c1c6-582e-11e8-975c-4f8154718b6a.png)

On Chrome
![2018-05-15 10_53_57-grafana - internet connection](https://user-images.githubusercontent.com/2153950/40030521-65a3115c-582e-11e8-82fc-bd41ff3f0674.png)

This has only happened in the last few weeks so i believe it is due to a chrome update. I am on chrome 66.0.3359.139

**Comment by torkelo** [comment]
Dam, we might need to revert this and do a patch release. 
https://github.com/grafana/grafana/issues/11710

**Comment by ThomasRunting** [comment]
I can confirm with my grafana got updated last night and the issue is not happening.

**Comment by simPod** [comment]
It kinda hides content 🤔 

![image](https://user-images.githubusercontent.com/327717/40241841-4c3e7342-5abc-11e8-9ea1-0c2960ea086c.png)
