### ISSUE TITLE
Prometheus Annotation for label value change

### ISSUE THREAD

**Issue by nvx** [grafana/grafana#11948]
A common convention in Prometheus is to have a constant metric with application version information, for example a metric exposed by Prometheus itself:

```
prometheus_build_info{branch="HEAD",goversion="go1.9.2",instance="localhost:9090",job="prometheus",revision="5211b96d4d1291c3dd1a569f711d3b301b635ecb",version="1.8.2"} 1
```

It would be really handy to have an annotation appear when a specific label changes, eg the version label changes. Note that the metric has a constant value of 1.

As far as I can tell, this does not appear to currently be possible. I can make an annotation appear constantly with the version information, but not only showing the "first" time the label appears with that value. Using the Prometheus function changes() does not work as the metric is constant, and the metric first appearing is not considered a change.

**Comment by FUSAKLA** [comment]
You can achieve this for example using something like
```
changes(count(prometheus_build_info))
```

Since this is not valid because `changes` needs range vector as input you will have to add recording rule to Prometheus as 
```
- record: prometheus_build_info:count
    expr: count(prometheus_build_info)
```

Than you can add annotation query to Grafana
```
changes(prometheus_build_info:count)
```

For more info about subqueries refer to this article
https://www.robustperception.io/composing-range-vector-functions-in-promql/

**Comment by bergquist** [comment]
@FUSAKLA Thank you for answering this questions. I'm closing this.

**Comment by nvx** [comment]
Hi @FUSAKLA, having a quick look at what you've suggested appears to lose all label information. Ideally you would have information in the label like "version X deployed on instance Y", doing a count() appears to lose all that information. This doesn't appear possible doing the count approach. For the same reason it doesn't handle multiple jobs very well either.

**Comment by chrko** [comment]
```
prometheus_build_info unless (prometheus_build_info offset 1m)
```

currently evaluating this query!
