### ISSUE TITLE
Grafana 5.1.0+ is not requesting graphite for data in Browser mode

### ISSUE THREAD

**Issue by knuzhdin** [grafana/grafana#11943]
#### What Grafana version are you using?
5.1.0+

#### What datasource are you using?
Graphite

#### What OS are you running grafana on?
Ubuntu 14.04

#### What did you do?
Updated from 5.0.4 to 5.1.0
Looking at Graph from Graphite datasource in Browser == Direct mode

#### What was the expected result?
A complete graph

#### What happened instead?
Empty graph, with no data

----
The change that I see is that in 5.0.4 grafana it uses POST requests to get data. After 5.1.0 grafana (or browser on its behalf) is sending OPTIONS HTTP request to check for CORS, and no requests for data follows (even after I made the graphite server to respond with all the CORS headers needed).

BTW, proxy or the Sever mode is working fine.

**Comment by torkelo** [comment]
Can you show output from your chrome dev console? Is the CORS request succeeding? If there is an issue with your CORS setup chrome usually prints errors in the console.

**Comment by marefr** [comment]
Propably a cause of distributed tracing headers. There's an open issue #11494 to not send those headers when using direct mode.

**Comment by knuzhdin** [comment]
I somehow missed CORS failure on x-panel-id header request!
Why is grafana sending X-Dashboard-Id and X-Panel-Id headers?

**Comment by marefr** [comment]
Those headers can be used to investigate certain issues/problems with for example slow running queries. Then if you for example log http requests you can see requests taking long time what dashboard and what panel was the origin of the query.

**Comment by knuzhdin** [comment]
Marcus, I agree, thank you for reply!
But it looks like it would be great to have an option to disable those headers in datasource settings :)

**Comment by marefr** [comment]
Yeah the issue I referenced above will remove the sending of those headers when using direct/browser mode.

As a workaround you may be able to configure CORS for your graphite instance if you have a proxy in front of it and configure the proxy to respond to CORS preflight (HTTP OPTIONS) request with certain headers.

```
Access-Control-Allow-Origin: <domain/host>
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Authorization, Content-Type, X-Dashboard-Id, X-Panel-Id
```

**Comment by knuzhdin** [comment]
Yes, I did exactly this, thank you!
