### ISSUE TITLE
grafana-alerting

### ISSUE THREAD

**Issue by wissal123** [grafana/grafana#11944]
Hello,

i want to configure grafana to send alerting to my account but dosn't working, this is the error

![image](https://user-images.githubusercontent.com/39095491/40073633-e39f7fd6-5866-11e8-96f1-783f14fea65f.png)
here is the grafana configuration:
![image](https://user-images.githubusercontent.com/39095491/40073759-4554efa4-5867-11e8-9be8-e75c7268bb01.png)
thanks to help me.

**Comment by wissal123** [comment]
dataSource is Influxdb , i think SMTP server is not working ,this is the new error:
![image](https://user-images.githubusercontent.com/39095491/40107126-f818417a-58e6-11e8-8173-736e8c6d5e2c.png)

**Comment by wissal123** [comment]
please i want to know is what to install the DNS for SMTP server it works?

**Comment by daniellee** [comment]
Are you getting any smtp errors? The logs above are not errors - they just say that when the query is executed by the alerting engine that no data was returned from the query. 

Do you have template variables in your query? That is not supported yet: #6557
