### ISSUE TITLE
[BUG] Deleting a panel from the edit mode, leaves the page blank

### ISSUE THREAD

**Issue by sebiglesias** [grafana/grafana#11941]
Please include this information:
### What Grafana version are you using?
Grafana v5.1.2
### What datasource are you using?
Graphite
### What OS are you running grafana on?
High Sierra 10.13.14
### What did you do?
I deleted a panel from the edit mode of that same panel.
### What was the expected result?
Be taken out of the edit mode, and see my whole dashboard without that panel.
### What happened instead?
The whole dashboard dissapeared, and I had to refresh to see my dashboard again.

**Comment by daniellee** [comment]
After removing a panel, you are still in edit mode so if you pressed the "go back" button (or esc) you would go back to the dashboard. 

So after removing the panel, the user should be taken back to the dashboard.

![image](https://user-images.githubusercontent.com/434655/40066044-818a9c8e-5863-11e8-9f8d-cf04bd057f83.png)

**Comment by sebiglesias** [comment]
I believe that by adding a `ng-click="ctrl.exitFullscreen();"` to the Delete button would solve this issue.
