### ISSUE TITLE
Chart draw error 

### ISSUE THREAD

**Issue by thanhlv93** [grafana/grafana#11947]
Hello,
I'm just know about grafana and try to create my chart with it. 
But in my chart there is some error (like image) I dont know how to fix it.
![bug](https://user-images.githubusercontent.com/5988002/40093932-88dd1238-58ee-11e8-959a-56e200b816a6.png)

### What Grafana version are you using?
Grafana v5.1.2 (c3c690e21)

### What datasource are you using?
Postgrest

### What OS are you running grafana on?
Ubuntu

### What did you do?
Create a chart to monitor the time to handle the log files.

### What was the expected result?
Remove the column I mark in the image.

Please tell me if you have any suggest.
Thanks all.

**Comment by torkelo** [comment]
cant see any error in image. Grafana will show the data your query returns, open query inspector and compare the graph with the data your query returns. 

Please ask questions on the community site https://community.grafana.com
