### ISSUE TITLE
Dashboard and absolute links don't use template variables properly

### ISSUE THREAD

**Issue by vmoloko** [grafana/grafana#11952]
- What Grafana version are you using?
Grafana v5.1.0 (844bdc53a)
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Centos 7
- What did you do?
I created a template variable "env".
I created a repeated singlestat healthcheck panel templated with "env" variable.
I included "env" variable inside "Metrics", "General->Title", "General->Drilldown/detail link->Dashboard" and ""General->Drilldown/detail link->Title"
- What was the expected result?
Dashboard link is templated and link for each panel contains proper "env" value.
- What happened instead?
Templating metric value itself (singlestat value), panel title and link titles are templated. Each panel contains corresponding "env" value, as expected.
But Dashboard link is always for the first "env" value.
The same behavior is for absolute links, so I can't use them either (ex.: for templated panels for 2 envs "a" and "b" with templated links "http://${env}", links on both panels redirect you to "http://a").

Is it an expected behavior?

**Comment by torkelo** [comment]
looks to be an issue here, https://github.com/grafana/grafana/blob/master/public/app/features/panellinks/link_srv.ts#L82 

where we only interpolate the title. Sadly we will not be able to support this use case as we will soon update these links to they use the new uid style urls. 

https://github.com/grafana/grafana/issues/10705
