### ISSUE TITLE
Explore menu in custom panel?

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#11953]
Using the latest grafana build, I have a custom panel using https://github.com/ryantxu/ajax-panel it extends `metrics-panel-ctrl` it adds the explore menu:

![image](https://user-images.githubusercontent.com/705951/40117327-f1552508-5916-11e8-8d0e-6f2920638dfe.png)

Strangely, this does not seem to happen for other custom panles I have that extend `metrics-panel-ctrl`

**Comment by daniellee** [comment]
Yes, can recreate this.
