### ISSUE TITLE
 grafana-cli: command not found

### ISSUE THREAD

**Issue by conradwt** [grafana/grafana#11957]
### What Grafana version are you using?

Grafana Server - Version 5.0.0 (commit: NA)

### What datasource are you using?

I do not have a datasource because I'm trying to install the grafana-cli to install the kubernetes-app plugin.

### What OS are you running grafana on?

macOS 10.13.4

### What did you do?

I have installed the grafana-server

### What was the expected result?

I would expect that the grafana-cli to be installed when installing the grafana-server

### What happened instead?

$ grafana-cli plugins install grafana-kubernetes-app
-bash: grafana-cli: command not found

**Comment by daniellee** [comment]
Did you install it using the instructions here: http://docs.grafana.org/installation/mac/

Just tested on a mac (macOS 10.13.3) here and it seems to work. Can you provide more details on how you installed Grafana, please.

**Comment by conradwt** [comment]
@daniellee I have installed Grafana using the documentation here:  https://github.com/grafana/grafana

**Comment by daniellee** [comment]
@conradwt 

The instructions there are usually used by people who want to submit a PR for Grafana or want to fork Grafana.

If you install from source, then you will have to add the grafana-cli to your path manually (Homebrew and the other installation packages do this for you normally).  See [here for how path works on MacOS](http://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/).

Alternatively, you can just cd to your Grafana home folder and run: 

`./bin/grafana-cli --pluginsDir "./data/plugins" install grafana-kubernetes-app`

**Comment by conradwt** [comment]
@daniellee At this time, the only installation method provided in the docs for macOS is through `Homebrew`.  It would be nice to have a `Bash install alternative` which simply installs in `/usr/local`.

**Comment by daniellee** [comment]
@conradwt your wish is granted. We have just added a tar ball to the mac download page. It is only available for recent nightly builds right now but will be available for all Grafana versions in the future. 

https://grafana.com/grafana/download/5.2.0-17531pre1?platform=mac
