### ISSUE TITLE
Dashboard Provisioning does not resolve symlinks

### ISSUE THREAD

**Issue by jmcarless** [grafana/grafana#11958]
Dashboard provisioning is not working for me when set to a symlink directory. Is this a known limitation? I've been searching around this github and the community site for a bit and haven't found any documentation about this.

### What Grafana version are you using?
We are testing out provisioning on the new 5.1.2 version

### What OS are you running grafana on?
Amazon Linux 2017.09

### What did you do?
Put json dashboards in a symlink "current release" directory (pointed to by the yaml file in the provisioning/dashboards directory). 

### What was the expected result?
Dashboards loaded

### What happened instead?
No Dashboards found
 
### More Details
In my provisioning yaml file, this is set: `path: /srv/www/dashboards/current`
This is a symlink directory: `current -> /srv/www/dashboards/releases/20180516223247`
When i change my yaml file to this: `path: /srv/www/dashboards/releases/20180516223247`, the dashboards load as expected.

There are no errors or messages related to dashboards or that specified directory in `/var/log/grafana/grafana.log`.

**Comment by bergquist** [comment]
This is a bug. We don't resolve symlinks for the dashboard root folder. Only for the content within that folder.
