### ISSUE TITLE
Create datasource with api only works when I test it in the GUI first

### ISSUE THREAD

**Issue by shyam-biradar** [grafana/grafana#11950]
Create datasource with api only works when I test it in the GUI first. Can not use the datasource in dashboard before save and test.

**Comment by shyam-biradar** [comment]
Same issue: #3371

Have you fixed this issue?

**Comment by shyam-biradar** [comment]
Steps:
1. Use mysql as database of grafana
2. Create datasource of type myql using api, I have used ansible grafana_datasource module
3. Create dashboard and add panel which uses above datasource
4. Dashboard will not work, error: unable to fetch datasource
5. If you go to datasource wizard and save and Test it, then dashboard will work.

**Comment by torkelo** [comment]
you must be missing something in the API call when you create the datasource. Grafana UI uses the same API, can you compare the API call the browser makes against the one you do?

**Comment by shyam-biradar** [comment]
Thanks Torkelo. Will check.

**Comment by shyam-biradar** [comment]
It was just browser refresh thing. Working.

**Comment by johnmathew234** [comment]
@shyam-biradar 
this still doesn't work for me. Can you share how you did it?
