### ISSUE TITLE
Alerting Notification Channels - Add HTTP_PROXY configuration setting

### ISSUE THREAD

**Issue by ShloYo** [grafana/grafana#11962]
Versions: v4.4.1/v5.0.4/v5.1.1
Datasource: InfluxDB
OS: Ubuntu 14.0.4.5 LTS

Preface:
There has been a lot of discussion about HTTP proxy with regard to Notification Channels; in particular Slack.  While setting the environment variables HTTP_PROXY and HTTPS_PROXY at the OS works for Grafana, there are other applications hosted on the same server that **must not ever** send communication through the HTTP Proxy.

Feature Request:
On the create/edit an alert notification channel setting, permit the Grafana administrator to optionally add an HTTP proxy address through which Grafana shall communicate to the URL of the destination API.  In short, Grafana should use it's own internal HTTP_PROXY configuration rather than relying on any system-wide HTTP_PROXY configuration.  This kind of HTTP proxy handling is common in many other applications.

**Comment by marefr** [comment]
You should be able to provide the environment variables when starting Grafana, in startup script for example, removing the need of having this config globally.

Also, use the `NO_PROXY` env varable to specify what you don't want to go through proxy.

**Comment by ShloYo** [comment]
@marefr - thank you for your comment.  There clearly is value in your suggestion.  However, adding a line to `/etc/init.d/grafana-server` : `export HTTPS_PROXY=http://<proxy_server>:<proxy_port>` is useful but, it will actually redirect  output traffic globally from Grafana through the proxy.  In a lot of cases, particularly that of notification channels, some are destined over the internet to external targets while others are destined to internal targets.  Unfortunately, the global environment setting is an all-or-nothing proposition.

**Comment by marefr** [comment]
@ShloYo that's why I mentioned the `NO_PROXY` which you can use to tell what urls not to be proxied.

**Comment by ShloYo** [comment]
Thank you for the clarification, @marefr.  Now, I have the full picture.

**Comment by marefr** [comment]
Closing this since I don't see Grafana implementing support for different proxy configurations throughout datasources, alert notifiers etc. Will reconsider reopen if there's a lot of upvotes.

**Comment by dharou** [comment]
Hi , 
My Slack API call is not using the proxy though I properly set : HTTPS_PROXY=https://10.X.X.X:8080 in grafana.ini  ( I have also tried init.d , setting env ,etc) , I am runing the 5.30 beta1  .. I need to demo this grafana - slack interface in a couple of days so thanks advance for your help.

**Comment by marefr** [comment]
You cannot set HTTPS_PROXY in grafana.ini - only environment variables. 

Please try `HTTPS_PROXY=10.X.X.X:8080` or `HTTPS_PROXY=https://10.X.X.X:8080/`

**Comment by dharou** [comment]
Thanks for your answer , I have tried all posibilities to set the proxy but it turns , looking at my tshark capture that grafana is still trying to reach Slak on port 443 instead of going through the proxy. 
Curl command given by Slack is properly working and use the proxy .. 
do you think there is a work around ? 
ps : runing RHEL , I have set that in etc/profile , init.d - grafana, etc with no results

**Comment by dharou** [comment]
export in init.d works ! thanks ,( but not with a systemctl start .. , but I wili figure this out  later and share )  Thanks again

**Comment by yarix** [comment]
> Closing this since I don't see Grafana implementing support for different proxy configurations throughout datasources, alert notifiers etc. Will reconsider reopen if there's a lot of upvotes.

sorry to read that - i'm facing a similar problem with Prometheus Datasouces. 
in my case some data-sources needs to go via proxy, while others do not.
configuring that with environment variables will probably solve the issue, but it's really not how i'd expected it to be solved.

i would love to see a proxy configuration per data-source in the data-source GUI or provisioning file.

**Comment by feixiaohuijava** [comment]
In my case, i add http_proxy=http://ip:port was wrong ，it was bad Gatway and cannot connect to .... But if you set http_proxy=ip:port , it shows successful connect.

**Comment by gjemp** [comment]
For me following worked :
/etc/sysconfig/grafana-server service env conf is the right place to where the http_proxy env key must be added for systemd services . Hope it helps others who had similar issue.

PS! i use Grafana 6.3.5 on RH 7.6

Br,
G

**Comment by kotchuprik** [comment]
global HTTP-proxy is not the best way when a grafana container works with other containers (like https://github.com/grafana/grafana-image-renderer or victoria metrics(!)).

**Comment by jinjin123** [comment]
os: centos7   I think
grafana: 7.5.9
env file: /etc/sysconfig/grafana-server 
env variable: HTTPS_PROXY=10.X.X.X:8080  ### not use protocol  work for me

**Comment by zahid-alam** [comment]
> os: centos7 I think
> grafana: 7.5.9
> env file: /etc/sysconfig/grafana-server
> env variable: HTTPS_PROXY=10.X.X.X:8080 ### not use protocol work for me

Thank you so much. It worked for me as well!

**Comment by HBLiB** [comment]
Broken in Grafana 8,
I installed Grafana 7.5.9, as others were saying it worked on that version, and it does indeed work in that version.

At least the Alerters try a direct connection.

**Comment by josefzahner** [comment]
I'm using Grafana 8.0.4 on Centos 7 (systemd) and it does work in my case (sorry @HBLiB ). But it took me hours to find the working solution provided by @jinjin123. So disappointing that such an important configuration part is so bad documented.

**Comment by shawnlu-nj** [comment]
Grafana 9.5.19 running on docker does not work, with “--env https_proxy=192.168.1.50:8888”. Email notifications do not go through the Linux global proxy at all. Only when selecting Slack and DINGDING Talk as notification methods, the Linux global proxy is used.
