### ISSUE TITLE
grafana datasources yaml doesn't support environment value

### ISSUE THREAD

**Issue by like-inspur** [grafana/grafana#11961]
I create a grafana instance with grafana/grafana:5.1.2 image. I want to config different datasources for different grafana. So I config a datasources.yaml under /etc/grafana/provisioning like this:
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://$PROMETHEUS_SERVER:9090

And I create an environment value for $PROMETHEUS_SERVER，but no value on grafana web page.
![1](https://user-images.githubusercontent.com/18571465/40160497-73165494-59e0-11e8-9a3d-be5d62114b20.png)
![2](https://user-images.githubusercontent.com/18571465/40160514-7d6287b0-59e0-11e8-9352-93bf604f5422.png)

@matschaffer @damm @ctrochalakis @Dieken @jd

**Comment by bergquist** [comment]
Grafanas provisioning does not support read environment variables.
