### ISSUE TITLE
Multi-value template variables not working as expected in application dashboard

### ISSUE THREAD

**Issue by DarrenWhiteABB** [grafana/grafana#11968]
### What Grafana version are you using? 
4.6.3
### What datasource are you using? 
A proprietary data source (ABB's real time database) and a custom datasource plugin (fork of simple json)
### What OS are you running grafana on? 
Windows Server 2012 R2 Datacenter
### What did you do? 
1. Opened an application dashboard which had three query template variables
1a. The third template variable was created as multi-value
2. Selected two values in the third template variable dropdown list
3. Saved dashboard
4. Refreshed the webpage
### What was the expected result?
The value of the 'text' property should be displayed for each option in the third dropdown before and after refreshing the webpage
### What happened instead?
The value of the 'value' property was displayed on webpage refresh instead.

This issue only arises when the dashboard is saved and reloaded with more than one value selected in the third template variable dropdown. I have stepped through the datasource code and can confirm that the text and values are mapped correctly in the mapToTextValue() function. 

I checked the dashboard JSON, before saving the dashboard, with two options selected in the third template variable dropdown and the text and value properties in the 'current' object (found in the templating object of the dashboard JSON) appear as expected. Then when the dashboard is saved and the webpage is reloaded the text property in the 'current' object, in the dashboard JSON, has been updated to show the value instead of the expected text.

**Comment by daniellee** [comment]
Confirmed as a bug. We will get a fix for this into the next Grafana release. Thanks Darren for reporting this!

**Comment by torkelo** [comment]
Grafana will try to look up the option based on the url value or text so it should find the option and use that. 

https://github.com/grafana/grafana/blob/master/public/app/features/templating/variable_srv.ts#L208

Only if the option is not found is the url value used for both text & value.
