### ISSUE TITLE
series are disapperaing from the panel

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1196]
I have noticed this for several times, When I try to drill down the a time period on the chart, I noticed that series all together disappeared for a chart. I do see this behavior on off,. even when the charts are auto refreshing, series on the chart may disappear. Has anyone else noticed this behavior?

**Comment by torkelo** [comment]
Can you open chrome dev tools and inspect the graphite render request? Maybe check if there are any javascript errors? The blank graphs are probably caused by slow graphite or some unexpected response from graphite. But I need more info from you
