### ISSUE TITLE
Google Oauth for multiple organizations in grafana

### ISSUE THREAD

**Issue by vishuroy12** [grafana/grafana#11965]
Hi,
we have multiple organizations created in grafana, and we are using those organization other than "Main org." Last time i tried to enable google Oauth but it was authenticating to "Main org.", i want that authentication should work for different organizations too. Is there any way of doing this.

What Grafana version are you using? = 5.1
What datasource are you using? = Multiple
What OS are you running grafana on? = Ubuntu 16.04

**Comment by daniellee** [comment]
Duplicate of #9766

Sorry - don't think it is possible right now.
