### ISSUE TITLE
The heatmap panel does not properly display Google Stackdriver metrics of value type `Distribution`

### ISSUE THREAD

**Issue by mweiden** [grafana/grafana#11979]
The heatmap panel does not properly display Google Stackdriver metrics of value type `Distribution`.

I realize the Stackdriver plugin is not officially supported yet, but wanted to raise this as an issue for when it is officially supported.

### What Grafana version are you using?
5.0.4

### What datasource are you using?
https://github.com/mtanda/grafana-google-stackdriver-datasource

Version: https://github.com/mtanda/grafana-google-stackdriver-datasource/commit/54b41df3bdc991137d43ebdcd5b174a2d74e882b

### What OS are you running grafana on?
Linux

### What did you do?
Use the heatmap panel with google metrics of value type `Distribution`, aggregation `REDUCE_SUM`, `ALIGN_DELTA`

### What was the expected result?
A heatmap similar to that displayed in Stackdriver metrics with the same display parameters

![screen shot 2018-05-18 at 4 43 38 pm](https://user-images.githubusercontent.com/538456/40262241-c035e4f8-5aba-11e8-8f59-9d17fb356f0b.png)
*Generated with Stackdriver*

### What happened instead?
The y-axis scale is off and the buckets do not seem to display properly
 
![screen shot 2018-05-18 at 4 43 15 pm](https://user-images.githubusercontent.com/538456/40262251-ca8ce62c-5aba-11e8-87a3-e815908d30c1.png)
*Generated with Grafana*

**Comment by mtanda** [comment]
Please attach screenshot, and version (commit hash) of datasource plugin.
Recently, I add distribution value type support in stackdriver plugin, it is not tested well.
Please let me check your problem.

**Comment by mweiden** [comment]
@mtanda I've updated the description with the info you requested. I've also generated this using the latest version of your code and the metric `cloudfunctions.googleapis.com/function/execution_times` which should be a fairly common use case.

**Comment by mtanda** [comment]
@mweiden 
https://github.com/mtanda/grafana-google-stackdriver-datasource/pull/26 change may fix issue.

To use heatmap plugin, you need to set heatmap panel plugin like following.
![image](https://user-images.githubusercontent.com/224552/40300131-4e9347ee-5d23-11e8-8364-83f81b0dc1e6.png)
Set alias as `{{bucket}}`.

![image](https://user-images.githubusercontent.com/224552/40300162-6292669e-5d23-11e8-82ed-5c82348c5f1f.png)
Set format as `Time series buckets`.

**Comment by mweiden** [comment]
@mtanda @torkelo great, thanks!
