### ISSUE TITLE
Inconstant unit filtering for velocity

### ISSUE THREAD

**Issue by steakunderscore** [grafana/grafana#11975]
### What Grafana version are you using?

Grafana v5.0.4 (commit: 7dc36ae)

### What OS are you running grafana on?

Ubuntu

### What did you do?

Typed "kilometre" into the unit selector

### What was the expected result?

"kilometres/hour" to be displayed

### What happened instead?

Other units showed up that involve kilometres, but not the one I wanted.

**Comment by daniellee** [comment]
Closed by #11976
