### ISSUE TITLE
Playlist : allow to save under specific folder

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#11978]
Playlist is a special type of dash-board but it does not follow dashboard's ACL model, as a result, if the user is having viewer role at org level only, even he/she has editor role for some folders, creating playlist will get "permission denied". Playlist should be allowed to be saved under specific folder that user has write permission.

**Comment by shalstea** [comment]
+1

**Comment by dansarginson** [comment]
+1

**Comment by marcobrinkmann** [comment]
+1

**Comment by ehatch90** [comment]
+1

**Comment by jsabin** [comment]
+1

**Comment by mkeagar** [comment]
+1

**Comment by excedra** [comment]
+1
