### ISSUE TITLE
Singlestat threshold tooltip vs implementation is incorrect

### ISSUE THREAD

**Issue by rdxmb** [grafana/grafana#11971]
### What Grafana version are you using?
grafana:5.0.4

### What datasource are you using?
influxdb

### What OS are you running grafana on?
docker container "grafana/grafana:5.0.4"

### What did you do?
coloring single stats

### What was the expected result?
As explained with the tooltip, the thresholds both are "inclusive" for the "middle color", in other words:

```
VALUE < 50 = Green
50 <= VALUE <= 80 Yellow
VALUE > 80 Red
```

### What happened instead?
The second value seems to be inclusive for the third color:

```50,80 will produce: 
VALUE < 50 = Green
50 <= VALUE < 80 Yellow
VALUE >= 80 Red
```

So either the implemenation is not correct or the tooltip.

![screenshot_20180517_152642](https://user-images.githubusercontent.com/30314040/40180818-00f1e628-59e8-11e8-8a5c-98ff10fd774b.png)

**Comment by daniellee** [comment]
I don't think we will be changing the threshold implementation so the tooltip text needs improving.
