### ISSUE TITLE
Problem with smart decimal precision when using scaled unit formats

### ISSUE THREAD

**Issue by loopping** [grafana/grafana#1197]
Hello,
I'm using the latest git from today.
I have series with big value differences.

When using the "None" format :
![img1](https://cloud.githubusercontent.com/assets/7744271/5306514/4caf81b6-7c05-11e4-8c7f-b5022cef768a.png)

Now using the same series with the "short" format:
![img2](https://cloud.githubusercontent.com/assets/7744271/5306539/7b05abb2-7c05-11e4-9542-a96b65469cf1.png)

Thousands and millions in this case are invalids.

Regards

**Comment by torkelo** [comment]
I have added a decimal override option for graph and singlestat panel where you can specify decimal precision for legend and tooltip (works with unit formats) 
https://github.com/grafana/grafana/issues/1253#issuecomment-78561547
