### ISSUE TITLE
timeGroup macro improvements and expose built in variables like MaxDataPoints

### ISSUE THREAD

**Issue by jgiganti** [grafana/grafana#11972]
Version 5.1.2, MSSQL data source, Windows

Before this plugin I implemented the simple json interface against my data store. The query on that interface had some properties that helped in the calculation of what data to return. Specifically 

* Interval/IntervalMS
* Max Data points
* Range

I found the _timeFrom() and _timeTo() macros to handle Range, but I do not see a way to get the interval, or the max data points.

It would be convenient for a macro to be able to supply the interval and/or max data points and maybe even update the timeGroup macro to be able to just take a dateColumn and then default to the correct interval based on the range. If valuable the generated Sql could also apply Max Data Points.

I have been keeping my data in Unix Epoch form, and did not save it as a DateTime, In order to use the timeGroup macro, I had to add a date time column to my data. For instance I had a simple query

```
SELECT
$__timeGroup(Time, '1440m') as time,
avg(Value)
FROM
Counter_Test
WHERE
$__timeFilter(Time)
GROUP BY
$__timeGroup(Time, '1440m')
ORDER BY 1
```

This is expanded to 

```
SELECT
CAST(ROUND(DATEDIFF(second, '1970-01-01', Time)/86400.0, 0) as bigint)*86400 as time,
avg(Value)
FROM
Counter_Test
WHERE
Time >= DATEADD(s, 1523971929, '1970-01-01') AND Time <= DATEADD(s, 1526563929, '1970-01-01')
GROUP BY
CAST(ROUND(DATEDIFF(second, '1970-01-01', Time)/86400.0, 0) as bigint)*86400
ORDER BY 1
```

I was wondering if a **timeGroupEpoch macro could be created _(Also same ideas about expanding the date range into the interval)_. Using the same Query as before except with $**timeGroupEpoch(TimeEpoch ) as time and $__unixEpochFilter(TimeEpoch ) it could expand to the following which I think might be more efficient

```
SELECT
        (TimeEpoch - (TimeEpoch % 86400)) time,
        Avg(Value) intervalValue
FROM
        Counter_Test WITH (NOLOCK)
WHERE
        TimeEpoch >= 1523972683 AND TimeEpoch <= 1526564683
GROUP By
        (TimeEpoch - (TimeEpoch % 86400))
ORDER BY 1
```

**Comment by marefr** [comment]
#12892 is now closed and solves one of your problem

**Comment by okke-formsma** [comment]
I would love to see an interval / intervalms option so the resolution is appropriate for the graph.

Thanks for the awesome mssql plugin!

**Comment by thatsparesh** [comment]
@okke-formsma could you share an example/testdata to work with?
@marefr is this request to expose Interval/IntervalMS and Max Data points for all SQL data sources, or just MSSQL?

**Comment by marefr** [comment]
@FatherTime1 there's now support for `$__unixEpochGroup` macro function since a while back.

@thatsparesh Yes, if we receive a proposed PR for this feature we would expect it to work for all three SQL datasources.

**Comment by marefr** [comment]
I would like to add that implementing this probably is blocked by https://github.com/grafana/grafana/pull/13086

**Comment by hugohaggmark** [comment]
@marefr should I add this to your project board?

**Comment by marefr** [comment]
Nothing we're currently planning to work on so should not be on our project board

**Comment by codeincarnate** [comment]
This could potentially be possible though it looks like it's not something widely requested at the moment. If we get some momentum behind this feature request or if anyone would otherwise like to contribute a PR for this please feel free to re-open 😄.
