### ISSUE TITLE
Login with LDAP cannot keep permissions

### ISSUE THREAD

**Issue by virnet** [grafana/grafana#11983]
### What Grafana version are you using?
Version 5.1.2 (commit: c3c690e21)
### What datasource are you using?
mysql
### What OS are you running grafana on?
CentOS release 6.5 (Final)
Linux iZ2ze35fwy8k6tw1t0ecc2Z 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
### What was the expected result?

1. join ldap, and  configure group_mappings:

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"
    org_id = 4
    (org_id=4,org_name=monitor)

2. use ldap user (sunlinyao) login grafana

3. use Grafana Admin  grant  authorization 
    user:sunlinyao, org: monitor,role: admin
    user:sunlinyao, grant  Grafana Admin
![image](https://user-images.githubusercontent.com/29397860/40212327-f964c660-5a81-11e8-8de7-e24f2b4ea9de.png)

3. Re logged in(sunlinyao)
![image](https://user-images.githubusercontent.com/29397860/40212290-d920f7e8-5a81-11e8-8f02-d48f736e0101.png)
![image](https://user-images.githubusercontent.com/29397860/40212312-ed8d4d1c-5a81-11e8-9172-d5ea9d456921.png)

### What happened instead?
user: sunlinyao
org: monitor
role: Viewer

and user: sunlinyao not manage grafana

**Comment by dschade2016** [comment]
When u remove the [[servers.group_mappings]] block. U have full control in Grafana backend. We had the same "issue". Pls try and give us feedback.

**Comment by virnet** [comment]
thanks, Your idea is feasible.

**Comment by virnet** [comment]
but in Grafana Version 4.6.2 (commit: 8db5f08). Without this problem

**Comment by daniellee** [comment]
From the [docs for ldap sync](http://docs.grafana.org/installation/ldap/#ldap-to-grafana-org-role-sync):

> In [[servers.group_mappings]] you can map an LDAP group to a Grafana organization and role. These will be synced every time the user logs in, with LDAP being the authoritative source. So, if you change a user’s role in the Grafana Org. Users page, this change will be reset the next time the user logs in. If you change the LDAP groups of a user, the change will take effect the next time the user logs in.

In your case, LDAP is the authoritative source and will overwrite your changes in Grafana.

**Comment by DanCech** [comment]
The recommended approach for your situation is simply to create a group in your LDAP store for grafana admins, map that group to the admin role, and add any users who you want to be grafana admins to that group.

**Comment by virnet** [comment]
thanks

**Comment by liujin1993** [comment]
I encountered the same issue. I solve this by modifing source code of pkg/login/ext_user.go 
After delete the code as follow, you can change the role of ldap user permanently. 
![image](https://user-images.githubusercontent.com/31949674/41087744-040092cc-6a70-11e8-8661-369c75b53bb9.png)
![image](https://user-images.githubusercontent.com/31949674/41087928-adc88922-6a70-11e8-853d-bce1dd3009fb.png)

**Comment by DanCech** [comment]
@liujin1993 this is not a recommended approach
