### ISSUE TITLE
[feature request]timegroup support epoch time type

### ISSUE THREAD

**Issue by yangliuyu** [grafana/grafana#11987]
I have installed grafana v5.1.3 commit: 0871432 on a CentOS 7.4.1708 server, using a MySql 7 database as datasource

since the $__timeGroup(column,'5m') -> cast(cast(UNIX_TIMESTAMP(column)/(300) as signed)*300 as signed)
can we provide similiar $_timeEpochGroup(column, '5m', 0) which column is a time epoch or may support ms in unit (column DIV 1000 to get the second value)

or can we add a custom macro config which user can define adhoc transform

**Comment by marefr** [comment]
Closed in favor of #12892
