### ISSUE TITLE
Cloudwatch autofill not working on duplicated queries

### ISSUE THREAD

**Issue by kaihendry** [grafana/grafana#11984]
Please include this information:
### What Grafana version are you using?

Grafana v5.1.2 (c3c690e21)

### What datasource are you using?

AWS

### What OS are you running grafana on?

Archlinux, via a `docker run grafana/grafana`

### What did you do?

Duplicate a query

### What was the expected result?

Loadbalancer name suggestion

### What happened instead?

Nothing

https://s.natalian.org/2018-05-18/autofill.mp4

**Comment by torkelo** [comment]
Grafana does not magically change your query when you change your datasource. 

So when changing datasource have to update the query and select dimensions that are relevant for that datasource.
