### ISSUE TITLE
Is there a way to export metrics deployed in Grafana by API ?

### ISSUE THREAD

**Issue by sam5558** [grafana/grafana#11989]
### What Grafana version are you using?
V 5
### What datasource are you using?
SimpleJSON, InfluxDB
### What OS are you running grafana on?
Centos 7
### What did you do?
I'm trying to find a way to export metrics used by Grafana to display singlestat & graphs in my dashboards.

I want to use grafana as an endpoint where all metrics from different sources centralizes, and them request my metrics from one place (grafana) via an API HTTP request.

I've searched in the [Grafana API](http://docs.grafana.org/http_api/), but it doesn't seem it's possible to do it.
Any suggestions, toughts about this issue is welcome
Thanks

**Comment by daniellee** [comment]
This is not currently supported. Grafana does not support a common way to query different data sources. 

The endpoint that could be used for this is: http://docs.grafana.org/http_api/data_source/#data-source-proxy-calls but you will have to build the queries yourself. The result would be in the same format (if you queried InfluxDB and SimpleJSON both would return the data in Grafana's timeseries format).

Example query for InfluxDB:

```
https://play.grafana.org/api/datasources/proxy/2/query?db=site&q=SELECT%20mean(%22value%22)%20FROM%20%22logins.count%22%20WHERE%20(%22datacenter%22%20%3D~%20%2F%5EAsia%24%2F%20AND%20%22hostname%22%20%3D~%20%2F%5Eserver%5C%5C%5C%5C5%24%2F)%20AND%20time%20%3E%3D%20now()%20-%201h%20GROUP%20BY%20time(1m)%2C%20%22hostname%22&epoch=ms
```



We do have a plans to build a meta query language that would work for all datasources so closing this issue in favor of that: #3677

**Comment by sam5558** [comment]
I see.

Thanks @daniellee

**Comment by unfor19** [comment]
Hi @sam5558 , I know it's been 2 years ... But still, if you need a tool that can scrape all the metrics that are being used in your Grafana dashboards, you can use this - https://github.com/unfor19/frigga

It's a simple CLI which can do two things - 
1. Get the list of metrics that are present in your Grafana dashboards - dumps to a JSON file
1. Generate `metric_relabel_configs` to your `prometheus.yml` to keep only the metrics in ☝️

**Comment by sumit2k21** [comment]
@unfor19 Hi, It is not giving details of the dashboard metrics. It just gives the information from the bashboard Json, nothing from inside it.

**Comment by unfor19** [comment]
@sumit2k21 yes you are right, I thought that he only needs the metrics names, not that data, sorry for misleading

**Comment by sumit2k21** [comment]
> @sumit2k21 yes you are right, I thought that he only needs the metrics names, not that data, sorry for misleading

Hi @unfor19 Thanks for clarifying, Is there any way via API calls to get metrics data from the dashboard ? not just the metric names ?
