### ISSUE TITLE
Influx graphs do not properly do "alias by" for tags with dots in the name.

### ISSUE THREAD

**Issue by cheribral** [grafana/grafana#11982]
We have been using grafana for a while with influx which is awesome, but we have had one annoyance with kubernetes stats from telegraf.  The issue is that we cannot 'alias by' our tag names because they have dots in the name like `io.kubernetes.container.name`.  Grafana only follows up to the first dot in the $tag_ pattern, and there doesn't seem to be a way to escape the dots.

The lack of escaping means one cannot properly label things in the legend so it gets quite messy.

**Comment by daniellee** [comment]
You need to use the alternative syntax: `[[tag_pattern]]`

ref:

https://github.com/grafana/grafana/issues/6706
