### ISSUE TITLE
Add support for new Cloudwatch GetMetricData API (MetricMath)

### ISSUE THREAD

**Issue by fsilva1992** [grafana/grafana#11991]
Recently, AWS Cloudwatch team launched a new API for cloudwatch `GetMetricData` adding support for native metric math.

More info:
https://aws.amazon.com/about-aws/whats-new/2018/04/amazon-cloudwatch-adds-metric-math-to-enable-custom-operations-on-metrics/

**Comment by marefr** [comment]
Closing this in favor of #11487
