### ISSUE TITLE
remove updateLegendValues from TimeSeries2.ts or expose it properly

### ISSUE THREAD

**Issue by jonyrock** [grafana/grafana#11997]
https://github.com/grafana/grafana/blob/c40b0ea1dfbb824eb3c444cc39ee982c0dab04a7/public/app/core/time_series2.ts#L27

I think that file `time_series2.ts` should be responsible only for algorithms for timeseries, but not rendering for GraphPanel.

Moreover, it is hidden in https://github.com/grafana/grafana/blob/85879a701493a2562b9cd8bffb3fe1067ea36aa3/public/app/features/plugins/plugin_loader.ts

`import TimeSeries from 'app/core/time_series2';`

* only TimeSeries default export imported here

but `exposeToPlugin('app/core/time_series2', TimeSeries);`

where funtion

```
function exposeToPlugin(name: string, component: any) {
System.registerDynamic(name, [], true, function(require, exports, module) {
module.exports = component;
});
}
```

loses info about named exports cuz you imported only `default`

I haven't made a big research about exporting mechanism.

**Comment by daniellee** [comment]
I think it is on purpose that this is not exposed to plugins but I agree that it is strange that the function is in the time_series2.ts class and it should be moved into the graph.ts.

If you are building a plugin, you could just copy in the code. We don't want plugins to depend on the graph panel's legend rendering - we might change that in the future.

**Comment by torkelo** [comment]
Closing this as it's part of the deprecated plugin types
