### ISSUE TITLE
Explore for Prometheus should default to "instant" queries

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#11998]
Explore for prometheus should default to instant queries, in table mode (when you go to http://grafana/explore) for the same reasons the prometheus itself does it like that (tune the query before query too much)

**Comment by roidelapluie** [comment]
@davkal that is now implemeted I think

**Comment by davkal** [comment]
Yes, sort of. I've moved the relevant buttons to choose this below the query fields. Now it's more obvious.
