### ISSUE TITLE
Feature request: export & import of graphs

### ISSUE THREAD

**Issue by edasque** [grafana/grafana#120]
From what I can tell this doesn't exist yet. I would love to be able to export & import graphs. Occasionally I want it so I can duplicate it in another dashboard with a different time line & summarize. Sometimes it's to share just one graph. Many different other use cases come to mind.

An import/export from JSON would be great. Also could be used to build graphs from scripts and import them if the JSON syntax is trivial.

**Comment by wrouesnel** [comment]
+1 for this. It works just fine if you directly edit the DB backend, of a dash, so there's no real reason it shouldn't be included that I can see.

**Comment by adammenges** [comment]
Huge :+1: for ability to edit the json of dashboards.

**Comment by torkelo** [comment]
closing this as you can export/import panel json
