### ISSUE TITLE
png-renderer failed to render an image

### ISSUE THREAD

**Issue by elvis-cai** [grafana/grafana#12006]
### What Grafana version are you using?
Grafana v5.2.0, also try with 5.0.0 5.1.0, none worked. 
### What datasource are you using?
prometheus
### What OS are you running grafana on?
alpine, install libstdc++,zlib-dev for phantomjs to work.
### What did you do?
create alert using email channel
### What was the expected result?
Get email notification with image. 
### What happened instead?
Get email without image
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Debug message in Gist: https://gist.github.com/elvis-cai/07d9caac88bb90983c8f3d7438a13d9d

**Comment by torkelo** [comment]
please include grafana server log info. And if they do not tell you what is going on then enable debug logging, set 

```ini
[log]
filters = png-renderer:debug
```

**Comment by elvis-cai** [comment]
@torkelo  Thanks for your quick reply, I add this filter to grafana.ini, it reports one error:
```
/usr/share/grafana/tools/phantomjs/phantomjs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory" logger=png-renderer
```
Below is the result when I use ldd on phantomjs:
```
bash-4.4$ ldd /usr/share/grafana/tools/phantomjs/phantomjs

/lib64/ld-linux-x86-64.so.2 (0x7f40ca0fa000)

libz.so.1 => /lib/libz.so.1 (0x7f40c9ee3000)

libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x7f40c9ca6000)

libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x7f40c99f8000)

libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f40ca0fa000)

librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f40ca0fa000)

libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f40ca0fa000)

libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f40c96a6000)

libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f40ca0fa000)

libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f40c9494000)

libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f40ca0fa000)

ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f40c926c000)

libexpat.so.1 => /usr/lib/libexpat.so.1 (0x7f40c904b000)

libbz2.so.1 => /usr/lib/libbz2.so.1 (0x7f40c8e3e000)

libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7f40c8c10000)

Error relocating /usr/share/grafana/tools/phantomjs/phantomjs: backtrace: symbol not found

Error relocating /usr/share/grafana/tools/phantomjs/phantomjs: backtrace_symbols: symbol not found

Error relocating /usr/share/grafana/tools/phantomjs/phantomjs: __rawmemchr: symbol not found
```
Detailed logs are in this gist:  https://gist.github.com/elvis-cai/0fae320e6bd5466f727435e4629e7e7e

**Comment by torkelo** [comment]
Looks like your missing a library requires for phantomjs to work, what OS are you on?
