### ISSUE TITLE
Should be able to set time correction default (and override) in config

### ISSUE THREAD

**Issue by psa** [grafana/grafana#1200]
Time correction seems to default to browser and all of our graphs are (or were) in UTC. Now they're in a mix as the time correction defaults to browser (which is absolutely the wrong default) and is saved with the graph. So, our old graphs are in UTC and the new graphs depend on whether the author remembered to set it or not.

Please add a configuration point for forcing the default to be UTC. Even better would be allowing an override so we can force all graphs to be saved with a UTC timezone and nobody gets tripped up by trying to debug in multiple timezones (all our servers are, naturally, set to UTC to avoid timezone confusion).

**Comment by pasancario** [comment]
I'll give you another turn around this issue. Imagine you use Grafana as a dashboard to control diferent services around the world, and your business runs in diferent timezones. How can you handle that? 

If I have three dashboards to check service status in China/EEUU/Europe, I'll see only UTC but calculations to correct timezone will be needed by user. So, can we improve this adding also on dahsboard an option to correct timezone (maybe a simple dropdown list in templating, as a parameter). 

I don't know if any other people have this kind of situation, but I think it will be a really useful, for dashboard users.

**Comment by torkelo** [comment]
yea, it would, will take a long time to implement, so a PR is welcome :)

**Comment by torkelo** [comment]
implemented and merged to master, 

![image](https://cloud.githubusercontent.com/assets/10999/14232934/0f3ac5ce-f96e-11e5-9af5-f6058f482f2c.png)

![image](https://cloud.githubusercontent.com/assets/10999/14232936/140b19f0-f96e-11e5-8606-3a35cb91439e.png)
