### ISSUE TITLE
Explore: add a tooltip/hover with legend to graph panel

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#12000]
There is no tooltip on the /explore graph. That would be a nice addition.

The Explore graph panel is not using the Angular graph component, but a re-implementation in React. It's missing a couple of features, including the tooltip. Would be great to have a tooltip React component that mimics the original graph's behaviour.

**Comment by steven-sheehy** [comment]
I'm not sure if my PR #16007 addresses this issue since it only fixes the table tooltips. I don't know what graph tooltip it is referring to here. @roidelapluie can you clarify if my PR addresses your concern?

**Comment by davkal** [comment]
Clarified the issue title. What is desired is the list of series with color and value when hovering over the graph. 
The graph component is being rewritten, see #14582 for the roadmap on component rewrites.

**Comment by steven-sheehy** [comment]
@davkal Thanks for clarifying.

Concerning the contents of the explore graph tooltip, I wanted to give my two cents on what I would like to see (and can help implement, if needed). Currently the graph tooltip in dashboards panel shows every series, making it unusable for graphs with a lot of series like in the popular dashboard 'Kubernetes Cluster Monitoring`:

![Screen Shot 2019-03-16 at 00 36 37](https://user-images.githubusercontent.com/17552371/54471263-3d3a5900-4784-11e9-9b32-49118ccb8c8d.png)

Instead, I'd like to see the tooltip contain data about a single series (the series closest to the cursor), as the Prometheus UI does:

![Screen Shot 2019-03-16 at 00 44 52](https://user-images.githubusercontent.com/17552371/54471305-ce113480-4784-11e9-9343-9dfe333ee1f4.png)

Or, maybe an in between approach with top 10 series + current highlighted.

**Comment by torkelo** [comment]
You know you can switch the dashboard graph tooltip mode to single series as well? In graphs display mode tab there is an option for tooltip

**Comment by steven-sheehy** [comment]
> You know you can switch the dashboard graph tooltip mode to single series as well? In graphs display mode tab there is an option for tooltip

@torkelo Ah, thanks. Didn't realize that was an option. That handles the single series, but the all series tooltip still suffers from what I described above. You may not be able to tell in my screenshot but it's cutting off the top memory containers due to there being too many lines in the tooltip. Think all series tooltip needs to be limited to top 10-25 series. Should I open a separate ticket for that?

**Comment by aocenas** [comment]
@ivanahuckova I think your PR with tooltips should address this right? Can you link it here and close this?

**Comment by ivanahuckova** [comment]
@aocenas yes https://github.com/grafana/grafana/pull/21405 (6.6 release) closes the issue.
