### ISSUE TITLE
Create dashboard from API : Return 302 on root_url//api/dashboards/db

### ISSUE THREAD

**Issue by throrin19** [grafana/grafana#12008]
### What Grafana version are you using?

v4.6.2

### What datasource are you using?

In my problem, it's just add templated dashboards

### What OS are you running grafana on?

Linux Ubuntu

### What did you do?

I just try to create dashboard from API using a basic auth authentication :

```
curl --request POST \
  --url 'http://localhost/api/dashboards/db?orgId=23' \
  --header 'authorization: Basic xxxxxxxxxxxxxxxxxxxxx' \
  --header 'content-type: application/json' \
  --data '{
    "dashboard" : {
        "id" : null,
        "title" : "test dashboard"
        "timezone": "browser",
        "version": 34
    },
    "overwrite": false
}'
```

### What was the expected result?

Dashboard create successfully with correct result

### What happened instead?

The grafana api return a 302 redirection to `http://localhost//api/dashboards/db?orgId=23` (with double `/`).

I try to set requestJS to follow POST 302 redirections but, after that, I get a 404.

The problem occurs on 2 of 3 queries

**Comment by daniellee** [comment]
Is the problem just with this query? Does a simpler query work?

This assumes port 3000 and user `admin` and password `admin`:

```bash
curl "http://admin:admin@localhost:3000/api/dashboards/home"
```

Also what changes have you made to your Grafana config in `[server]` section?

**Comment by daniellee** [comment]
Closing this issue due to no response for a few weeks.

**Comment by throrin19** [comment]
Oups sorry for the long time without any response.

If I make normal request like yours, I have no problem with that. I test that 10-20 times to see if the problem occured but no `302` was returned.

I have this config :


- domain : `localhost`
- http_addr : `0.0.0.0`
- http_port : `3000`
- protocol : `http`
- root_url : `%(protocol)s://%(domain)s:%(http_port)s/`

**Comment by throrin19** [comment]
After other tests, tjhe problem occured randomly if I pass an `?orgId=` query param

**Comment by sivachandran-s** [comment]
Hi 
did you figured it out the fix for this issue as I am too facing a similar problem when I am using ?orgId= query param.
