### ISSUE TITLE
/explore is accessible to users with viewer role

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#12001]
When expore = false, a user can still open the /explore url in grafana

**Comment by torkelo** [comment]
Not sure there is a strong reason to block this, the feature toggle is mostly to hide an unfinished/wip feature

**Comment by roidelapluie** [comment]
Okay then this is an issue. Have you been thinking about people lile fosdem, ccc who present really public dashboards to the public? Do you want grafana to actually be able to let them explore amy metrics so easily?

**Comment by torkelo** [comment]
Oh, it's available for users with viewer role as well? That sounds like another issue (what permission should be required to access explore view).
