### ISSUE TITLE
InfluxDB query builder is showing field types, not fields

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12009]
Using latest from master (5.2.0-pre1) and an InfluxDB 1.5.1, the field selection is showing the field types, not the field names:

![image](https://user-images.githubusercontent.com/705951/40297477-4f25b98c-5ce0-11e8-9bd1-c7e023ae7cf8.png)

The query requested when clicking the dropdown is:
q=SHOW%20FIELD%20KEYS%20FROM%20"turbine1"&epoch=ms

response is:
![image](https://user-images.githubusercontent.com/705951/40297677-e31ad33e-5ce0-11e8-9464-7b082bc8e0a4.png)

**Comment by daniellee** [comment]
Confirmed - searching after what should be reverted now. This is a critical bug.

**Comment by daniellee** [comment]
Had to revert #10677 and that fixes this issue.

Thanks Ryan for the report!
