### ISSUE TITLE
explore: add a datasource dropdown

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#12002]
When going to /explore, we should get a datasource dropdown to be able to select wich datasources to run the queries against

**Comment by davkal** [comment]
Currently only the default datasource is used, and it needs to be Prometheus. To expand this we could add a datasource selector.

Rough feature outline:

- add a UI control to the explore page that allows the selection of a supported datasource
- a datasource can be used in the explore page when its `datasource.ts` has the field `supportsExplore` set to `true`
- the control should list all the datasources that are supported
- all queries issues by the Explore UI should go to the selected datasource
- when changing a datasource, the responses to queries that are running, should be ignored
- figure out where to place the selector control on the page, also consider the split view
- when no supported datasource is found, show a helpful message on where to go to create one
