### ISSUE TITLE
what's  mean orgId  in share link url?

### ISSUE THREAD

**Issue by shaocongcong** [grafana/grafana#12012]
Grafana v5.1.2 (commit: c3c690e21)
influxdb
linux

what's  mean orgId  in share link url? Is it always 1？

**Comment by soffokl** [comment]
@shaocongcong There are organizations in the Grafana hierarchy: 
http://docs.grafana.org/guides/basic_concepts/#organization

So in the share URL `orgid` indicates a unique identifier of the organization. 
It will be different if you switch to another organization and try to share something.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
