### ISSUE TITLE
MySQL query results in unwanted data points since 5.0

### ISSUE THREAD

**Issue by peterdk** [grafana/grafana#12017]
### What Grafana version are you using?
5.1.3
### What datasource are you using?
MySQL
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
I have a mysql query that I use to generate a graph. Before 5.0 this worked perfectly, but since 5.0 suddenly I have spikes in the graph that seem to be caused by Grafana somehow also showing the `id` field (which is part of the query). 
### What was the expected result?
I would expect that the `value` field only would be displayed, not the `id` field from the query as well.
### What happened instead?
It somehow doesn't filter on the `value` field, but also displays unrelated fields (that are present in the query, but are for generating the diff from the mysql data).
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Full query:
```
SELECT
id as current_id,
  UNIX_TIMESTAMP(date) as time_sec,
processed_foo as current,
 (SELECT current - processed_foo from general_statistics where id = current_id - 1) as value,
"processed_foo" as metric
FROM general_statistics
WHERE $__timeFilter(date)
ORDER BY date ASC
```
The `processed_foo` field is a counter, so we use this query to show daily increase in the graph.

I simplified the query to see what is causing the issue:
```
SELECT
id as current_id,
  UNIX_TIMESTAMP(date) as time_sec,
processed_foo as value,
"processed_foo" as metric
FROM general_statistics
WHERE $__timeFilter(date)
ORDER BY date ASC
```
This also results in spikes. When the `id as current_id` is removed, everything is ok. So somehow it doesn't filter on `value`, but also displays the `current_id` value. 

![spikes in mysql query](https://user-images.githubusercontent.com/668007/40311193-7475115e-5d0f-11e8-848a-e5691b65a258.png)

And here the query inspector output:
[spikes.txt query inspector result](https://github.com/grafana/grafana/files/2022790/spikes.txt)

**Comment by peterdk** [comment]
I checked the docs, and it seems that the mysql datasource doesn't rely on `value` anymore. Seems to be changed since 5.0?

I rewrote the query as follows:
```
SELECT d.time_sec, d.value, d.metric from (
SELECT
id as current_id,
  UNIX_TIMESTAMP(date) as time_sec,
processed_foo as current,
 (SELECT current - processed_foo from general_statistics where id = current_id - 1) as value,
"processed_foo" as metric
FROM general_statistics
WHERE $__timeFilter(date)
ORDER BY date ASC) as d
```
Now it displays ok, since no unused fields are returned. But still, I would prefer to use `value` without using this subquery.

**Comment by marefr** [comment]
We changed this to make it work in the same way as Postgresql datasource. One of the good things with this approach is that you can get multiple series plotted out of multiple columns.
