### ISSUE TITLE
Thresholds have started to automatically generate

### ISSUE THREAD

**Issue by havedill** [grafana/grafana#12015]
It seems on Grafana v5.1.0, my graphs have started automatically calculating and creating thresholds for graphs. If you delete the thresholds, they regenerate after a short period of time.

This is using the Zabbix Datasource + DB.

I'm running Grafana on centos 7

You can see in the gif below that i delete the threshold, and it immediately repopulates itself.
https://gfycat.com/PitifulFrequentAdder

**Comment by torkelo** [comment]
Super strange, not sure what could be the cause. 

@alexanderzobnin is this a zabbix feature?

**Comment by marefr** [comment]
@havedill have you defined an alert rule in the alert tab?

**Comment by havedill** [comment]
Negative. No alerts are setup on any of these graphs

**Comment by alexanderzobnin** [comment]
@havedill do you have _Add thresholds_ option enabled in datasource config? If yes, it's an expected behaviour.
http://docs.grafana-zabbix.org/installation/configuration/#configure-zabbix-data-source

**Comment by havedill** [comment]
Thanks Alex, that was it
