### ISSUE TITLE
reusing search widget?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#1201]
Grafana has this great feature where you can dynamically generate dashboards using "scripted dashboards".  it supports looking at url args so you can specify parameters in the url,
let's say a you specify a servername in the url, to generate a dashboard of that server by expanding the servername into your graphite target strings.

it would be nice if we didn't depend on getting such input via url args though.  i would like to build, for example, a page that has a search/filter widget (very similar to the "open dashboard" widget), but populated with all my servernames, so i can select a servername from it and then build the dashboard for that server.  If grafana somehow lets me make a page where i can reuse the search widget, then i can populate it by querying graphite/influxdb for all known values of a certain expression

**Comment by jjmaestro** [comment]
What would be awesome is to have a pub-sub model.

Say you could create Channels in a dashboard. Then, a widget (or parts of a widget) could publish or subscribe to it. For example, a widget with a target picker could publish the target to a channel and then, many queries could subscribe to the channel and then retrieve stuff for that target :)

**Comment by mtanda** [comment]
+1

**Comment by torkelo** [comment]
closing this for now, as the dashboard search is an integral componet to the grafana chrome and not part  of the dashboard , search widget mentioned in issue  could be created as a panel
