### ISSUE TITLE
Parenthesis in InfluxDB resets after editing query

### ISSUE THREAD

**Issue by pukseli** [grafana/grafana#12011]
Editing parenthesis in Influxdb query WHERE clause in query edit mode resets after going to easy edit mode and editing query.  My query should be:
 `"SELECT count("running") FROM "stage" WHERE "A" =~ /banana/ AND ("B" = 'green' OR "B" = 'yellow') AND $timeFilter GROUP BY time(1d) fill(0)"`. 
After edit it resets back to: 
 `"SELECT count("running") FROM "stage" WHERE ("A" =~ /banana/ AND "B" = 'green' OR "B" = 'yellow') AND $timeFilter GROUP BY time(1d) fill(0)"`

What Grafana version are you using? 5.1
What datasource are you using? InfluxDB
What OS are you running grafana on? Ubuntu 16.04

**Comment by torkelo** [comment]
You cannot switch between modes and keep your manual changes, if you want to make changes in text editor mode you need to stay in that mode

**Comment by pukseli** [comment]
Could i you implement parenthesis management to easy edit mode?
