### ISSUE TITLE
Grafana plugins that requires client side installation

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#12028]
We recently started building plugins that might require installed software on the client side. Ex backend plugins written in nodejs will require that the server have a certain version of nodejs available and also the correct dependencies for the OS running Grafana

One solution would be to extend the `grafana-cli` to check if a certain version of nodejs is available and also run `npm/yarn install` during installation. This comes with some security concerns since we will download and execute files. 

Another solution would be to download all deps and bundle them per OS in the plugin package. This would still require the grafana-cli to check for nodejs during installation.

**Comment by DanCech** [comment]
You're going to execute the compiled plugin anyway, so as long as you're not running the compilation with elevated privileges there is very little additional exposure, the main risk would be a compromised dependency that somehow managed to escalate privileges.

**Comment by marefr** [comment]
I'm not sure this is still valid. We solved the packaging of the image renderer plugin by bundling node with the plugin. This haven't received any activity in quite a while so closing this for now. We can always reopen if needed.
