### ISSUE TITLE
Bad handling of null values in mysql datasource

### ISSUE THREAD

**Issue by pvalsecc** [grafana/grafana#12023]
### What Grafana version are you using?
5.1.3

### What datasource are you using?
mysql

### What OS are you running grafana on?
Official Docker image

### What did you do?
I have a graph with a metric defined by this query:
```SQL
select 
    $__timeGroup(report_end, '24h') as time, 
    count(*) as count, 
    spf_pass as metric
from dmarc_records
where $__timeFilter(report_end)
group by time, spf_pass
order by time
```
I've put the graph in stacked mode. And I get two metrics: `0` and `1`

### What was the expected result?

I don't have metrics every day for the two `spf_pass` possible values. I expect the graph to treat the missing value as 0 (I have set null value as 0 in the display tab).

### What happened instead?

The days that don't have a value for one of the metric inherit from the value of the previous day. For example:

Day | nb with spf_pass=0 | nb with spf_pass=1 | expected stacked graph height | actual stacked graph height
--- | --- | --- | --- | ---
2018/05/19 | 5 | 2 | 7 | 7
2018/05/20 | 3 | no record | 3 | 5 (3 plus the 2 value from the previous day)
2018/05/21 | 2 | 6 | 6 | 6

**Comment by torkelo** [comment]
if you have missing data you need to use 
$__timeGroup(time_column,'5m', 0) to insert 0 values for missing data points that way Grafana will know that a missing data point even existed, without that each series will have different number of data points and stacking needs to interpolate which can be inaccurate  

in non stacking scenarios you can also use 
$__timeGroup(time_column,'5m', NULL) to insert null values, this is useful if you want missing data to show up as gaps in the graph

**Comment by pvalsecc** [comment]
Thanks and please excuse me for having missed that.
