### ISSUE TITLE
Ability to specify date in Elasticsearch index name

### ISSUE THREAD

**Issue by XANi** [grafana/grafana#1202]
A lot of setups that log system logs into Elasticsearch use index name derived from date of logging, like logstash-2014.12.08 (for ease of querying and removing old data).

In Kibana you can specify [logstash-]YYYY.MM.DD as index name and it is auto-resolved based on time range, in Grafana you have to use _all index which is quite a bit slower

**Comment by soarpenguin** [comment]
Hello, this feature is added now?

**Comment by torkelo** [comment]
@soarpenguin no not yet

**Comment by torkelo** [comment]
so this is added for metrics, not for annotations, will close this and fix the issue with using date patterned indices for annotations in this issue: https://github.com/grafana/grafana/issues/3061
