### ISSUE TITLE
Some graphes start with 0

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#12024]
with grafana-5.2.0-17116pre1 I see sme prometheus graphes that start at 0:

![5 2](https://user-images.githubusercontent.com/291750/40322243-facc2ed2-5d31-11e8-82ff-27ac9d40b590.png)

It did not happen with 5.1.0-12399pre1:
![5 1](https://user-images.githubusercontent.com/291750/40322242-fab20d9a-5d31-11e8-9f74-29b323187630.png)

grafana-5.2.0-14826pre1 is OK...
grafana-5.2.0-15159pre1 is OK ...
grafana-5.2.0-16649pre1 is OK...
grafana-5.2.0-17011pre1 is NOT OK ...
16893 is NOT OK
16732 is NOT OK
16678 is OK
16711 is OK

So the problem starts in 5.2.0-16732pre1

(tested latest; 5.2.0-17321 and the problem is present)

After bisecting, The cause of this is #10434. I do think that this is a major issue, even if I am happy that you are trying to solve the problems behind #10434.

Note: this is an irate query, but I see the same with a normal metric (without function)

**Comment by roidelapluie** [comment]
16893 is NOT OK
16732 is NOT OK
16678 is OK

**Comment by roidelapluie** [comment]
16711 is OK

**Comment by roidelapluie** [comment]
So the problem starts in 5.2.0-16732pre1

**Comment by roidelapluie** [comment]
tested latest; 5.2.0-17321 and the problem is present

**Comment by roidelapluie** [comment]
Note: this is an irate query.

**Comment by roidelapluie** [comment]
NB: I explicitely set the interval: in those targets.

**Comment by torkelo** [comment]
probably related to the time range step align PR that was merged?

**Comment by roidelapluie** [comment]
if you read the first post you will see that I bissected to the exact nightly build yes

**Comment by davkal** [comment]
This seems to happen on graphs that have **Null value** set to **null as zero**. I was trying to keep the range length (number of datapoints) the same, which now seems ill-conceived. The alignment shifts the range into the future to be a multiple of the interval. The panel then still renders the original range, and now has one or more fewer datapoints. Without **null as zero** you simply get a gap.
I reckon we should expand the range start parameter as well to ensure we cover the whole panel interval.

**Comment by davkal** [comment]
@roidelapluie wanna give #12072 a spin?
