### ISSUE TITLE
Consistant naming of tags

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#12034]
Sometimes we use the term `tag` for singular word. like dashboard tags. In other areas, we use if for key/value. (ex graphite tags and Grafana Annotations). I think we should pick something and stick to it. Right  now it might not be an problem but if we add tags to alert rules we will be able to use those for silencing, routing and passing info to the alert notifiers. So the usage will definitly increase. 

How does other projects name it?
* Prometheus and Kubernetes uses `label` for key-value string. 
* Influxdb tag's are key/value
* Elastic tag's are value only.

**Comment by RichiH** [comment]
`tag` in the initial meaning is "one single string", be it one word or more. `label` has become the canonical name for key/value pairs, it seems.

Having consistent and bijective naming is important.

Or you just get rid of all tags and introduce labels for dashboards, etc :)

**Comment by daniellee** [comment]
@bergquist going to close this. Re-open if you want to continue the discussion.
