### ISSUE TITLE
Request to View More than one values for a metric in Graph Panel 

### ISSUE THREAD

**Issue by harshitha-m** [grafana/grafana#12038]
What Grafana version are you using:   5.1

What datasource are you using:  MySql

 What OS are you running grafana on:    Windows

 What did you do?
Created a Graph Panel with Chemical Names as Metric 
and Avg(Reaction_Time) as Values1 
Min(Reaction_Time) as Values2 
Max(Reaction_Time) as Values3
 
 What was the expected result?
Expected To Get  Values2 and Values3 as a Point,
Values1  as a Bar Graph

**Comment by marefr** [comment]
Please include your full table schema and the query you're using together with your graph panel settings/panel json. Can you also include a screenshot of your actual result? Thanks

**Comment by daniellee** [comment]
Closing as there has been no response for a couple of weeks. Can reopen if more details are provided.
