### ISSUE TITLE
[UX] editview=templating should link to regex documentation

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#12039]
@davkal 
Grafana 5.1.3

When editing a variable via https://play.grafana.org/d/000000029/prometheus-demo-dashboard?editview=templating&refresh=5m&orgId=1 I can mouse-over the `i` to see that this is optional, but I don't actually get a link to documentation, or even an online parser, for the regex flavour used.

**Comment by xlson** [comment]
@RichiH seems like an oversight for sure. Thanks for pointing it out!

**Comment by hugohaggmark** [comment]
Glorious news an external contributor, just added this feature in #28625 to be released in Grafana 7.4.
