### ISSUE TITLE
grafana templating replace 

### ISSUE THREAD

**Issue by bsushant-athena** [grafana/grafana#12035]
Please include this information:
### What Grafana version are you using?
3
### What datasource are you using?
prometheus
### What OS are you running grafana on?
mac os
### What did you do?
My service name is **abc-95** but the metric for that service is **abc_95_star_star**
As I'm using the templating and then using the same template variable in the query so not able to get the exact data. 
I'm not sure whether we can use regex in templating to replace the - with _
Can somebody please help?

**Comment by RichiH** [comment]
Version 3 is ancient; that being said, this does not work in current Grafana, either.

**Comment by torkelo** [comment]
You can only use the regex as a filter and to only extract parts of the value not do string replace. 

Please ask questions on the community site https://community.grafana.com
