### ISSUE TITLE
Can't open a dashboard link with a fixed time window without refresh getting added

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12030]
If you have a dashboard with a saved refresh, there is no way to link to the dashboard without loading the refresh.

For example, the URL:
```
http://host/d/000000007/example?from=1526993304945&to=1526993504945
```
Will redirect to:

```
http://host/d/000000007/example?from=1526993304945&to=1526993504945&refresh=5s&orgId=1
```

It would be nice if either (or both):
* request with an ms `to` parameter turn off refresh
* option to set `refresh=off` or  `refresh=false` in the URL

**Comment by xlson** [comment]
Thanks for reporting this issue, seems like a bug. I would expect Grafana not to start refreshing when a link is opened with a fixed time window.

**Comment by song2park** [comment]
does it work? @ryantxu 
I'm using `grafana-enterprise:11.2.0` at the moment.
My grafana links with a fixed time window gives me empty data even if there are.
I can get the data with `refresh` option.
