### ISSUE TITLE
Migrating from 5.0 to 5.1 Facing Error :Column metric must be of type char,varchar or text, got: float64 1.5

### ISSUE THREAD

**Issue by harshitha-m** [grafana/grafana#12036]
Previous Grafana Version:5.0     ,Present Version:5.1,
Data Source:MySql ,
OS:Windows

Created a Graph Panel with Float Data Type Metric
And Count of Metric as Values  

Expected Result :Bar Graph should be shown without any Errors 
Actual Result:Getting the Error 

Column metric must be of type char,varchar or text, got: float64 1.5

Does 5.1 Version not support Float values as metric?

**Comment by marefr** [comment]
The metric will be the name of the series. You're trying to use a floating point as name for a series - is that intentional? You can cast your metric column to char/varchar.

**Comment by harshitha-m** [comment]
Thanks marefr.. I casted the float values but ordering them in asc or desc was a problem .I Changed my query accordingly .Got the expected results
