### ISSUE TITLE
grafana doesn't display lines on graph with group by time/mean is used

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#12032]
Grafana version: 5.1.2
Database: influxdb 1.5.2

When using grafana on small periods of time and there is not a lot of data available, grafana does not draw any lines on the graph. If I remove the "GROUP BY time($__interval)" and corresponding "mean()" aggregation, grafana can happily draw the graph. The only difference between the attached two screen captures is the change in the query by removing GROUP-BY.

This *only* happens when there is a very small amount of data for grafana to work with. It happens with all data series, not just this one. This is very reproducible.

The most common "workaround" is just to "wait for more data to be collected". I haven't researched how long I need to wait.

For best effect, use a data series that you've just started populating in influxdb rather than choose one that has a lot of data and pick a middle. Or one where there is a significant gap (say an hour or two) between the last set of data and the latest data that you want to look at.

<img width="642" alt="screen shot 2018-05-23 at 4 18 32 am" src="https://user-images.githubusercontent.com/24280758/40382036-b1960b4c-5e40-11e8-9dd4-8f3cca08d8e9.png">

<img width="628" alt="screen shot 2018-05-23 at 4 18 11 am" src="https://user-images.githubusercontent.com/24280758/40382023-a6cfd4a4-5e40-11e8-8838-925227cfc902.png">

**Comment by yellowpattern** [comment]
Some additional screen shots. Two screen shots show different points on the same graph. The third is from query inspector. What's really interesting is all of the null values returned by influxdb.

![screen shot 2018-05-23 at 4 28 54 am](https://user-images.githubusercontent.com/24280758/40382629-311fbdd0-5e42-11e8-9d7f-5d23bce40eb9.png)
<img width="1372" alt="screen shot 2018-05-23 at 4 27 43 am" src="https://user-images.githubusercontent.com/24280758/40382630-31d38842-5e42-11e8-9a2b-40fb396f6b31.png">
<img width="1357" alt="screen shot 2018-05-23 at 4 27 30 am" src="https://user-images.githubusercontent.com/24280758/40382631-331241e4-5e42-11e8-920b-0bf568d87baa.png">

**Comment by yellowpattern** [comment]
A workaround is to use "fill(previous)" in the influxdb query (removes all of the "null" elements, of course) but this seems like a rendering bug in grafana if it isn't ignoring nulls...?

**Comment by torkelo** [comment]
change fill(0) if you do not want null values, Grafana does not render a line if two consecutive points are null. 

In display tab you can also set "null mode" to connected to ignore null values.

**Comment by yellowpattern** [comment]
"Connected" for "Null value" fixes the problem. Seriously, why isn't that the default?
