### ISSUE TITLE
Feature request: share single live dashboards by link for anonymous access.

### ISSUE THREAD

**Issue by positron96** [grafana/grafana#12031]
Right now there are 3 options to share data:
 * share a snapshot and send link to everyone. It does not include live data.
 * anonymous users with View permission.  But then anonymous users will be able to see all dashboards with "View" permission, so this option does not allow to share several dashboards with different clients and not allow them to see each other's dashboards.
 * create users and give them permissions to view specific dashboards. But then users will have to hassle with logins, emails, etc.

I believe it will be very useful to have an option to share a live dashboard without ability to view other dashboards and without need to authenticate. For quick demos/showcases/share purposes. 

It would be similar to "Anyone with a link can view" permission from Google Docs or Skydrive or "Unlisted" videos on youtube.

Please include this information:
### What Grafana version are you using?
v5.0.4
### What datasource are you using?
Influx
### What OS are you running grafana on?
docker image in Debian

**Comment by DanCech** [comment]
See #3792 for discussion on this topic.

**Comment by positron96** [comment]
Hello Dan. 
I've read the discussion but did not find any relevant information. Snapshots do not contain live data, do they? They contain, well, snapshots of data of specific time-frame, if I got it right. This feature request is about having "snapshots that show live, current data". If it is already implemented, please point me at it.
