### ISSUE TITLE
url variable value that is not a full value, that uses a wildcard, coupled with refresh on load

### ISSUE THREAD

**Issue by carioka88** [grafana/grafana#1203]
Hello!

When I try to share my panel, specifying the following template variables as: 
host=All and broker=agileinf

[..]?panelId=1&fullscreen&from=now-24h&to=now&var-host=All&var-broker=agileinf&var-top=5

The plot displays nothing.

But if I changed "All" by '*' directly in the url, it displays the correct information

[..]?panelId=1&fullscreen&from=now-24h&to=now&var-host=*&var-broker=agileinf&var-top=5

In the json file I have,
[...]
 "templating": {
    "list": [
      {
        "type": "query",
        "datasource": "graphite",
        "refresh_on_load": true,
        "name": "host",
        "options": [],
        "includeAll": true,
        "allFormat": "glob",
        "query": "msgbrk.*.*",
        "current": {
          "text": "All",
          "value": "*"
        },
        "refresh": true
      },
[...]

What is wrong? Should I change my json file description? 

Thanks!

**Comment by torkelo** [comment]
Is this still an issue? Can you show me what the graphite request is that is failing? I cannot see a broker variable in your json
