### ISSUE TITLE
Grafana 5.1 - Dashboard Import

### ISSUE THREAD

**Issue by RamsNelluri** [grafana/grafana#12033]
Please include this information:
### What Grafana version are you using?
5.1
### What datasource are you using?
Graphite, ElasticSearch (Issue is independent of DataSource)
### What OS are you running grafana on?
Linux
### What did you do?
Step1. I need to replicate a dashboard with different name. 
Step2: Exported the dashboard (For example: Name of the dashboard: Dashboard1)
Step3: While importing I changed the dashboard name and imported. (Newely imported dashboard Name: Dashboard1 - Latest)
Step4: After importing, I could see the new dashboard (Dashboard1 - Latest) Replaced the (Dashboard1). No longer see the old dashboard.

Did little further investigation by comparing the 2 JSON files, could find that, import is not generating dashboard UID, instead using the same Dashboard UID

### What was the expected result?
Should have created the new dashboard keeping the old one Intact
### What happened instead?
Replaced the dashboard but with new name

**Comment by xlson** [comment]
The UID of the dashboard json being the same as the the one you exported is what's tripping you up here. When importing a dashboard with a UID Grafana will automatically replace the existing dashboard with the same UID. This feature makes sense in [provisioning](http://docs.grafana.org/administration/provisioning/#dashboards) but gets in the way when importing and exporting through the Grafana UI.

A possible fix for this is being tracked here #11860
