### ISSUE TITLE
probleme with $__timestamp and char 

### ISSUE THREAD

**Issue by zwakrim** [grafana/grafana#12040]
Dear all,

im using grafana v4.6.3 the datasource is a postgresql. 

im tryen to collect some data and to filter with the $__timestamp (see picture) the problem is that the "date" column is an char column and it is not working also when i convert them to time. could you please help 

![image](https://user-images.githubusercontent.com/21273047/40430041-6d5cca24-5ea4-11e8-9722-1dcf03caef64.png)

**Comment by RichiH** [comment]
v4.6.3 is quite old; v5.1.3 is current. Can you try upgrading to a current version, first?

**Comment by zwakrim** [comment]
will it resolve the problem ?

**Comment by zwakrim** [comment]
not really an answer

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Please try to use something like this instead:

```sql
to_timestamp("Date", '<format>') BETWEEN $__timeFrom() AND $__timeTo()
```

**Comment by zwakrim** [comment]
thanks it works
