### ISSUE TITLE
Backend Plugins: Pass user information

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#12043]
It is useful to restrict permission in backend plugin.
For example, I want to use the user information to restrict log viewing permission in sumologic plugin.
https://github.com/mtanda/grafana-sumologic-datasource

I guess, we need to extend backend plugin protocol, and pass it like following code.
https://github.com/mtanda/grafana/commit/512ecda60918a55d418de182fa93845cd67a33c1

@bergquist This is the feature request what I told you in GrafanaCon.

**Comment by bergquist** [comment]
Hm. I'm not sure how `context.Context` is sent over the wire to none Go projects. Also `context.Context` is only common in golang. How about adding User information to the datasource request contract? https://github.com/grafana/grafana-plugin-model/blob/master/datasource.proto#L6

How much info would you need about the user? I'm a little hesitant to sending to sensitive data to the plugin.

**Comment by mtanda** [comment]
I think, UserId, OrgId of models.SignedInUser are enough for my use case.
I can get name of user and organization by calling Grafana API, and mapping privilege for the user.
