### ISSUE TITLE
How to use Grafana API's to Create Grafana Users??

### ISSUE THREAD

**Issue by MahadevG** [grafana/grafana#12048]
Hi,
I am new to API's I have very low idea API's . I got grafana API's but I don't to how to utilize them. 
Please Can anyone  explain me what are the ways to use them. 

I have api to create user please anyone tell me how i can use that api??
I am using Grafana 5

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Everything should be documented [here](http://docs.grafana.org/http_api/).
