### ISSUE TITLE
Remove QueryOptionsCtrl references

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12042]
A datasource used to be able to expose a `QueryOptionsCtrl` and this would add a top level option to the query control.

It seems that this does not work anymore, and has been replaced by setting `plugin.json` with:
```
  "queryOptions": {
    "minInterval": true
  },
```

There are still some references to QueryOptionsCtrl in the code:
https://github.com/grafana/grafana/search?utf8=%E2%9C%93&q=QueryOptionsCtrl&type=

should these be removed?

**Comment by torkelo** [comment]
Yes, these should be removed. The reason we removed this component was to streamline and simplify the metrics tab UI (so we could have datasource selection and options at the top)

**Comment by flunardelli** [comment]
Since QueryOptionsCtrl was removed, is there another way to have custom datasource options or common query options ?

**Comment by torkelo** [comment]
Not currently, only min interval and cacheTimeout
