### ISSUE TITLE
Stacking does not play well with negative y-transform

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#12053]
Grafana: version 5.1.2
Database: influxdb 1.5.2
Browser: Safari 11.0.3

This may be related to the issue I just closed (looks like a bug-cousin) ... when using "Stacked" display for lines, the draw option for "transform negative Y" does not look like it gets understood properly.

At the point in time where the cursor is placed, there are no values below the 0-line when quite obviously there should be.

<img width="1359" alt="screen shot 2018-05-24 at 10 44 09 pm" src="https://user-images.githubusercontent.com/24280758/40486318-467c6814-5fa4-11e8-82b9-4ec5bfdbf122.png">

**Comment by yellowpattern** [comment]
There are some points above that have clearly made it to "negative Y" but not all that should have been.

**Comment by torkelo** [comment]
you need to create different stack groups for the two series. Add a series override stack B

**Comment by yellowpattern** [comment]
Thanks!
