### ISSUE TITLE
Include "All" when repeating panels for template values

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#12051]
### What Grafana version are you using?
v4.6.3, v5.1.3
### What datasource are you using?
Prometheus

### Description

When using a template variable, there is the option to enable "All". When selected, all valid values will be considered at the same time. For a single panel that use it, this usually means displaying multiple metrics, or including multiple in an aggregate. For a repeating panel that uses it, this means all options in the menu will be selected and all possible panels will be displayed. This makes sense.

What I am missing, is a way to include "All" itself as value to be included.

#### Steps

* Create a template variable like "cluster" or "country" that has multiple values, including "All".
* Create a panel that uses this variable in a query, and it repeats for the variable.

#### Desired outcome

* Panel 1: The metric combined for all clusters.
* Panel N+1: The metric from cluster X.

This first panel (combined) is not a new feature. Grafana already supports this when a panel is not repeated (in which case, the "All" value is passed to a single panel).

At this time, the only way to achieve the desired outcome is to duplicate all panels on the dashboard. One repeating, and one not repeating.

#### Alternative

If https://github.com/grafana/grafana/issues/1032 were fixed, then a better workaround could be to create a custom variable where by the possible values are manually entered, including a label "All" that correlates to a wildcard value (and disabling Grafana's own "All" option). Then it would be among the "real" values considered for repetition.

**Comment by Krinkle** [comment]
@xlson No, the problem is that when you have a variable with three values (x, y, z). It is possible to use that in a single panel (e.g. to show the sum of the metrics from x,y,z together in one panel), and it is possible to use it in a repeating panel whereby each metric is shown separately.

However, I would like to be make a panel repeat itself in a way that also includes the "All" value.

Let me provide an example. For Wikipedia's use of Prometheus, we aggregate most metrics by data centre. We have dropdown menus like these:

| Template variable | Dropdown menu
|--|--
| <img width="735" alt="screen shot of the template variable for site" src="https://user-images.githubusercontent.com/156867/40496974-f7e5075a-5f72-11e8-85c7-fa707542b408.png"> | <img width="215" alt="screen shot of the dropdown menu for site" src="https://user-images.githubusercontent.com/156867/40496872-bad2aa8e-5f72-11e8-9a1b-1d1515ccd375.png">

Then, here is an example of a panel that uses the variable:

<img width="1420" alt="screen shot of panel" src="https://user-images.githubusercontent.com/156867/40497139-5cf7eb08-5f73-11e8-8d68-d56bb8b57c9a.png">

The above screenshot shows "Varnish cache hit percentage" for site=All, meaning requests and responses from all sites combined. If I select one of the individual sites from the template variable dropdown instead, then it shows the percentage for just that one site.

What I would like is for the dashboard to repeat this panel for each of the sites, as well as for all sites combined (e.g. the Grafana "All" option).

Currently, I can either repeat the panel and lose "All", or don't repeat the panel and lose the individual sites.

These examples can be seen at <https://grafana.wikimedia.org/dashboard/db/resourceloader>.

It currently shows the following if I don't repeat panels

* site: [ x All, codfw, eqiad, esams ]
* HTTP Status (site=All)
* Cache Status (site=All)

To see the same panel for an individual site, I have to choose a different option, it does not allow me to see them all at once.

Alternatively, I could repeat the panels and hide the variable:

* HTTP Status (site=codfw)
* HTTP Status (site=eqiad)
* HTTP Status (site=esams)
* Cache Status (site=eqiad)
* Cache Status (site=eqiad)
* Cache Status (site=esams)

Now, I no longer have the "site=All" version of the panel.

**Comment by xlson** [comment]
@Krinkle I think I understand what you mean now. Thanks for elaborating.

While I think what you're suggesting would make sense for some users I'm not sure how we would go about adding that functionality without making Grafana harder to understand in the process.

**Comment by Krinkle** [comment]
@xlson Ease of use is important, and these principles resonate with me. I think in this case the sensible compromise is to use the repeating panel for individual clusters, and to accept the extra maintenance requirement of manually keeping the first row duplicated for showing all clusters together.
