### ISSUE TITLE
Template variables disappearing

### ISSUE THREAD

**Issue by gms1234** [grafana/grafana#12054]
### What Grafana version are you using?
` Grafana v5.1.3 (commit: 087143285) `

### What datasource are you using?
`Graphite 1.2-dev 
`
### What OS are you running grafana on?
`Ubuntu 16.04.4 LTS (4.4.0-042stab127.2 x86_64)`

### What did you do?
I defined a variable (specifically an interval). When I go to the Home Dashboard tab it shows up, but after opening a specific dashboard it completely disappears (even in the variables tab).  

My `grafana.log` doesn't show any error.

**Comment by torkelo** [comment]
Variables are saved per dashboard, so go the dashboard where you want the variable, after you added it, save the dashboard.

**Comment by gms1234** [comment]
That was actually the problem, thank you.

But still, this is really confusing because you can define a variable from the Home Dashboard view. But from in this view you can't save a dashboard. Is this intended?
