### ISSUE TITLE
[FR] Multiple units in one graph

### ISSUE THREAD

**Issue by iyanmv** [grafana/grafana#12059]
Apparently, [it is not possible to display more than two units](https://community.grafana.com/t/multiple-units-how-to-display-multiple-units-in-one-graph/4137) (one unit in the left y axis and another in the right y axis) in a graph in Grafana. I can imagine some scenarios where having multiple units (and scales) in one graph would be very useful.

Is this in the roadmap of Grafana? Does it make sense to add this feature?

**Comment by iyanmv** [comment]
Doing a more carefully search I found these related issues:
#1893 #7397

**Comment by xlson** [comment]
You can "thumbs up" issue #7397 as a way to show your interest in the issue.
