### ISSUE TITLE
[Feat] TiDB as backend database

### ISSUE THREAD

**Issue by CrazyNash** [grafana/grafana#12058]
### What Grafana version are you using?
The latest one

### What did you do?
Configure TiDB as database

### What was the expected result?
It works.

### What happened instead?
Grafana can't start.

### If related to metric query / data viz:
no

TiDB is compatible to mysql, the problem here is TiDB has more strict requirement for table altering. It doesn't support multi schema change, but we have this in code, can we split this kind of sql into multi ones? and is there any other issue to support TiDB so far?
 

> t=2018-05-25T05:07:14+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Update user table charset" error="Error 1105: can't run multi schema change"
t=2018-05-25T05:07:14+0000 lvl=eror msg="Exec failed" logger=migrator error="Error 1105: can't run multi schema change" sql="ALTER TABLE `user` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, MODIFY `login` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , MODIFY `email` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , MODIFY `name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL , MODIFY `password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL , MODIFY `salt` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL , MODIFY `rands` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL , MODIFY `company` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL , MODIFY `theme` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL ;"
t=2018-05-25T05:07:14+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: Error 1105: can't run multi schema change\n"
[root@10-25-62-59 grafana]#

**Comment by marefr** [comment]
> TiDB is compatible to mysql, the problem here is TiDB has more strict requirement for table altering.

Then I would say it's not compatible looking from a Grafana perspective. We have no plans on supporting this right now. We'll leave this open as a feature request and if lot's of people upvote this and/or someone submits a pull request to fix it we'll consider this.

**Comment by CrazyNash** [comment]
I have fixed this issue, but hit a new one

> INFO[05-25|17:11:48] Executing migration                      logger=migrator id="alter dashboard.data to mediumtext v1"
EROR[05-25|17:11:48] Executing migration failed               logger=migrator id="alter dashboard.data to mediumtext v1" error="Error 1105: unsupported modify column charset utf8 not match origin utf8mb4"
EROR[05-25|17:11:48] Exec failed                              logger=migrator error="Error 1105: unsupported modify column charset utf8 not match origin utf8mb4" sql="ALTER TABLE dashboard MODIFY data MEDIUMTEXT;"
EROR[05-25|17:11:48] Server shutdown                          logger=server reason="Service init failed: Migration failed err: Error 1105: unsupported modify column charset utf8 not match origin utf8mb4"

I am going to fix this, and if everything goes well, I will submit my changes for your consideration.

But this is a fresh setup, why so many migration operations? seems an upgrade from V1 to V2 gets involved from every fresh setup? is this a bug?

**Comment by DanCech** [comment]
The database schema is maintained this way to ensure that there is no difference between a fresh install and an upgraded one.

**Comment by aocenas** [comment]
Going to close this, there did not seem to be much traction for this and it's not something we have plans on supporting right now.
