### ISSUE TITLE
Dashboard version cleanup can't keep up when more than 100 changes are being made every 10 minutes

### ISSUE THREAD

**Issue by charlemagnelasse** [grafana/grafana#12068]
I've already asked to reopen #8887 but this wasn't done. I must therefore open a new ticket for the problem. Please see the discussion in #8887 for more details

----

This is what I now got (and the status which was just requested a couple of seconds after the log entries were shown):

    t=2018-05-22T09:31:12+0200 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 keept=110
    t=2018-05-22T09:31:12+0200 lvl=dbug msg="Deleted expired snapshots" logger=cleanup rows affected=0
    t=2018-05-22T09:31:13+0200 lvl=dbug msg="Deleted old/expired dashboard versions" logger=cleanup rows affected=100
    t=2018-05-22T09:31:13+0200 lvl=dbug msg="Deleted expired login attempts" logger=cleanup rows affected=0

    echo 'select count(*) from dashboard_version;select dashboard_id,count(*) from dashboard_version group by dashboard_id;'|sudo sqlite3 /var/lib/grafana/grafana.db
    22585
    23|20
    27|20
    28|20
    29|20
    30|20
    31|20
    32|20
    33|52
    34|343
    35|604
    36|604
    37|613
    38|613
    39|613
    40|613
    41|613
    42|613
    43|613
    44|613
    45|613
    46|613
    47|613
    48|613
    49|613
    50|613
    51|613
    52|613
    53|613
    54|613
    55|613
    56|613
    57|613
    58|613
    59|613
    60|613
    61|613
    62|613
    63|613
    64|613
    65|613
    66|613
    67|613
    68|613
    69|613
    70|613

----

The bug in the code is that you only allow MAX_VERSIONS_TO_DELETE (100). This is a lot less than what grafana adds in each cleanup period. https://github.com/grafana/grafana/blob/f0d77804daf79d251a813c92cb6954e93600923b/pkg/services/sqlstore/dashboard_version.go#L70

Btw. I've played around with the versions_to_keep to check what influence it has. This is the reason why it now only deletes down to 20 entries for the first couple of dashboard_ids. Will switch later back (but this will not help because of the bug which was explained earlier)

    [dashboards]
    versions_to_keep=1

**Comment by xlson** [comment]
I'm curious, how often do you update your dashboards and how many dashboards are you updating? Is there any way you could run those updates less frequently?

As you've pointed out the current codebase will only allow you to delete 100 versions every time the cleanup job is executed and the cleanup job only runs every 10 minutes. We might want to make this configurable.

**Comment by charlemagnelasse** [comment]
They are updated every 60 seconds and there are around 45 dashboards which are generated.

And no, it is not possible to reduce the number of dashboards or the refresh interval. This also worked perfectly fine in the past.

**Comment by xlson** [comment]
@charlemagnelasse We're looking into a solution. In the meantime, I'd suggest you stay on an earlier version if possible.

Discussed this with @bergquist and what we probably want to do is to split this up into two SQL queries, one (select from versions, group by dashboard > dashboard versions_limit) that finds the dashboards with too many versions and one that deletes the extras. The first one wouldn't be transactional but the second would be, to limit locking of the tables as much as possible.

**Comment by nharkins** [comment]
hi. i'm on the DBA side of an installation running grafana `v6.2.5 (6082d19)`, and the revision count of our largest dashboards are still growing despite implementing `versions_to_keep=30` (see below), so i suspect it is this bug (adding the recommended debug at https://github.com/grafana/grafana/issues/8887#issuecomment-390882873 to confirm). 
I realize this will eventually get fixed, but in the meantime, could the devs please advise/confirm a safe method to manually purge the old versions... is it as simple as writing a script to just delete the rows less than the latest number of versions_to_keep for each dashboard_id? Or would that leave dangling references/break anything? (NOTE: it seems mysql still does not allow IN subqueries with LIMIT on the same table, or else a single query could do the correct purging).
```
> SELECT dashboard_id, COUNT(*) FROM grafana.dashboard_version GROUP BY 1 ORDER BY 2 DESC LIMIT 10;
+--------------+----------+
| dashboard_id | COUNT(*) |
+--------------+----------+
|         2310 |  8356192 |
|         2417 |  7176573 |
|         2717 |  1963666 |
...
```

**Comment by torkelo** [comment]
Are you using provisioning? Maybe different files with same uid or using provisioning in HA setup with servers with different files ?

**Comment by nharkins** [comment]
Yes, provisioning is being used, and not misconfigured. It was quite aggressive at some point, but the revision rate is not as high currently. Please advise on how to clean up, since the automated purging seems unable to do so. Is it safe to simply use sql to delete the older rows?

**Comment by torkelo** [comment]
Yes, it is safe

**Comment by bergquist** [comment]
There are several potential improvements to this.

 * Splitt SQL queries into multiple executions instead of one transaction
 * Increase max limit of how many dashboards versions to delete
 * delete dashboard versions in batches to reduce locks.

I don't want to introduce settings unless we really really have to :)
