### ISSUE TITLE
Grafana problems with Yandex SMTP

### ISSUE THREAD

**Issue by Unb9rn** [grafana/grafana#12062]
Hello! I'm trying to set up Grafana notifications with SMTP using Yandex's post for domains.
I'm running Grafana 5.1.3 Docker image (on Kuberentes, if this is important)
I'm setting up SMTP via env vars:
```

        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: smtp.yandex.ru:465
        - name: GF_SMTP_USER
          value: notify@example.com
        - name: GF_SMTP_PASSWORD
          value: somepassword
        - name: GF_SMTP_SKIP_VERIFY
          value: "true"
        - name: GF_SMTP_FROM_ADDRESS
          value: notify@example.com

```
I am perfectly able to log in to this account via webif, but Grafana fails to send test message with logs:

```

 t=2018-05-25T09:32:17+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp [2a02:6b8::38]:465: i/o timeout"
t=2018-05-25T09:32:17+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=unb0rn error="dial tcp [2a02:6b8::38]:465: i/o timeout" 
```

Using Yandex's guide for SMTP setup:
`https://yandex.com/support/mail/mail-clients.html#imap`

**Comment by xlson** [comment]
The configuration looks good to me, not sure why it wouldn't work. Could you try running Grafana locally on your machine without Docker to see if it has something to do with your kubernetes/docker setup?

**Comment by Unb9rn** [comment]
The problem was in Google Cloud Platform, which is unable to establish connections on any SMTP ports. Fixed by using custom SMTP port. Thanks.

**Comment by xlson** [comment]
Glad to hear you worked it out. Thanks for reaching back to us to let us know what the problem was!
