### ISSUE TITLE
Invalid epoch timestamps

### ISSUE THREAD

**Issue by rudibroekhuizen** [grafana/grafana#12061]
Epoch timestamps that consist of 9 digits result in invalid dates. This is true for all dates between  April 24, 1938 and September 9, 2001:

-999999999 (GMT: Sunday, April 24, 1938 10:13:21 PM) to 
999999999 (GMT: Sunday, September 9, 2001 1:46:39 AM)

This is what happens:
20010910 becomes **1000080000000** which is correct
20010908: **999907200000000000** which is incorrect

**Query used:**
SELECT
  count(*), $__time("date")
FROM table
WHERE
  $__timeFilter("date")
GROUP BY time

**Generated query:**
SELECT
  count(*), "date" AS "time"
FROM table
WHERE
  "date" BETWEEN '1868-05-25T09:04:49Z' AND '2018-05-25T09:04:49Z'
GROUP BY time

### What Grafana version are you using? 
5.1.3

### What datasource are you using? 
PostgreSQL

### What OS are you running grafana on? 
Ubuntu 16.04

### What did you do?
Create histogram and table using timestamp

### What was the expected result?
Show all values, also between April 24, 1938 and September 9, 2001

### What happened instead?
Invalid timestamp, points are not plotted in the histogram between these dates. Tables shows 'invalid date' for these timestamps

### If related to metric query / data viz:
![screenshot from 2018-05-25 10-58-24](https://user-images.githubusercontent.com/4686274/40537028-23624a82-600e-11e8-9f5f-b309fd2f68b1.png)

![screenshot from 2018-05-25 11-30-07](https://user-images.githubusercontent.com/4686274/40537360-04e69b20-600f-11e8-941d-50c7c3ff7ac6.png)
![screenshot from 2018-05-25 11-32-25](https://user-images.githubusercontent.com/4686274/40537497-56c0dbf4-600f-11e8-8c5a-6a23fc20fbbf.png)

**Comment by xlson** [comment]
Thanks for reporting this issue. The epochs are handles as millisecond (when they are seconds) epochs incorrectly and that's whats causing issues.

**Comment by marefr** [comment]
@xlson can you add this to the changelog?
