### ISSUE TITLE
Embedded panel triggers scroll to element

### ISSUE THREAD

**Issue by Argoday** [grafana/grafana#12075]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.0-pre1 (f17100e98)
### What did you do?
Used an embedded panel via iframe on a parent page where iframe initially loads out of view (aka the parent window is tall enough to have a scroll bar)
### What was the expected result?
Expect that iframe loads without affecting parent window's current scroll position.
### What happened instead?
When iframe loads the parent window scrolls to that iframe

### What caused it?
Best I can tell the root cause is commits: https://github.com/grafana/grafana/commit/9549aadd2676d88ef6ec25a2f8e1d24b4d8caf46 , https://github.com/grafana/grafana/commit/aac1b250afdb08deec327044688cd5f9a0e8ff72 , and https://github.com/grafana/grafana/commit/25ec7b5b027fbd99a7dd5c4f446d9a4f5e2c44ec (basically the `scrollTop = 0` and `focus()` parts) worked on as part of https://github.com/grafana/grafana/pull/11456

Looks like this `scroll to top` behavior is also triggering for embedded panels ...

**Comment by xlson** [comment]
Thanks for reporting this issue and looking into what's causing it.

**Comment by shalstea** [comment]
+1

**Comment by sni** [comment]
+1

**Comment by davidwadler** [comment]
+1

**Comment by jc-datto** [comment]
+1

**Comment by sni** [comment]
A ugly workaround for now is to set the embeded grafana iframe to `style="visibility: hidden; position: absolute; top: 0px;"` which basically puts it invisible at the top of the page. Then add an onload to the iframe which reverts that.

```
<iframe 
  src=".../grafana..." style="visibility: hidden; position: absolute; top: 0px;"
  onload="this.style.position=''; this.style.visibility=''; this.style.top='';"
></iframe>
```

This still jumps if you start scrolling before grafana finishes loading, but nothing which could'nt be solved by some little javascript.

**Comment by Argoday** [comment]
Doesn't need javascript to fix that up, instead just set `position: fixed;` and you are good :stuck_out_tongue:

**Comment by dehrax** [comment]
I recreated a bare minimum version of this issue. https://gist.github.com/dehrax/e4268d887dd811c2944f8dcb58a3c273

**Comment by dehrax** [comment]
It seems like this can be solved by passing `{preventScroll: true}` to `.focus()`. Am I missing some detail by doing this?

**Comment by torkelo** [comment]
which focus call?
