### ISSUE TITLE
Step interval not being used when set

### ISSUE THREAD

**Issue by EmilioD** [grafana/grafana#12074]
### What Grafana version are you using?
5.1.2
### What datasource are you using?
PrometheusDB 2.2.1
### What OS are you running grafana on?
RHEL 7.5
### What did you do?
specified a step for a graph or set to auto
PromDB scrape interval (or min interval scrape now) is set to 1s for prometheus as well as in grafana data source
### What was the expected result?
the query would reflect specified step or display interval as step size
### What happened instead?
the query includes a step= value that is different from that specified (I have not identified the source of this number) - it seems to be generally 2, 5, 10, or 20 but I cannot figure out where these steps are coming from.
The desired step interval can be seen set in the graph JSON, yet in the query its not honored
### If related to metric query / data viz:
![capture1](https://user-images.githubusercontent.com/4438169/40559089-9630eba8-6023-11e8-956c-7fd46f9c4520.PNG)
this graph includes a step=1 yet the query url has step=20  (I have not identified the source of this number) - it seems to be generally 2, 5, 10, or 20 but I cannot figure out where these step values are coming from.

![capture2](https://user-images.githubusercontent.com/4438169/40559088-96227a1e-6023-11e8-8840-80dec2267d81.PNG)
The desired step interval can be seen set in the graph JSON, yet in the query its not honored

 This may be slightly related to https://github.com/grafana/grafana/issues/9705 and/or https://github.com/grafana/grafana/pull/8073 but those appear to issues with setting (or not) the step interval - not specifically having an step interval set but it not being honored and some other step is being used instead.

**Comment by torkelo** [comment]
It’s a min step option , Grafana Will increase the value so as not to return to much data or for Prometheus to hit its datapoint limit. So as you zoom out the step will increase , if it was locked at 1 your query could easily (after zoom out) return megabyte of datapoints and crash your browser.

But we might in the future add more ways to control step

**Comment by EmilioD** [comment]
would there be a way to override that? 1 MB or more per query is not unacceptable in some cases.

**Comment by torkelo** [comment]
What 1mb? You want to have a lower step then what grafana sets, it will increase the data returned (beyond the number of pixels in a graph)
