### ISSUE TITLE
[Feature Request] Prometheus Heatmap: Hide buckets with zero value

### ISSUE THREAD

**Issue by erikjohnston** [grafana/grafana#12080]
It would be nice to be able to hide buckets that have a zero value when using the prometheus 'spectrum' mode, e.g. so that it produces something like the example graph on http://docs.grafana.org/features/panels/heatmap/. Without it I find that it becomes hard to discern outliers when everything is solidly coloured.

The 'opacity' mode helps with that issue, but I much prefer the spectrum mode as it allows me to pick out the peaks more easily.

Similarly, it would be good to hide buckets when getting null values, so that you can see there is a gap in the graph rather than nothing happening.
 
(Current version: `Grafana v5.1.0 (844bdc53a)`)

**Comment by dschneller** [comment]
Same would be appreciated not for Prometheus, but Elasticsearch pre-aggregations.

**Comment by fjlour** [comment]
This is actually much needed since when using Elasticsearch pre-aggregations, and using a Sum, if the sum is 0, it colors the bucket.
Only when using Opacity mode it works as intended: i.e. zero shows no color in bucket.

I too request an option to show 0 as null in spectrum mode.
