### ISSUE TITLE
Permission issue when adding datasource to Organisation through HTTP API

### ISSUE THREAD

**Issue by sngedal** [grafana/grafana#12086]
Hi,
I am trying to add datasource to Organization through HTTP API but receiving failure response as “Permission Denied”.
Here are the steps that were followed:

1. Create Organization
2. Create User
3. Add User to Organization as Admin
4. Add datasource to Organization with Org Admin user credentials that were created in second step
5. All the above steps are done through HTTP API. Fourth step is throwing error response as “Permission Denied” while adding datasource.

Please help me on this issue.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Please verify that your user has a current/active organization selected. You can verify this by signing in to Grafana with the user created in step 2) or alternatively do a `HTTP GET /api/user`.

**Comment by sngedal** [comment]
@marefr I posted in community site(https://community.grafana.com/t/permission-issue-when-adding-datssource-to-organization-through-http-api/7756) too. 
I verified through REST API and I see that it is showing up only Main Org but not the Org which was created in step 1
Then I tried to switch user context for signed in user and it worked!!!
Thank You so much for your advise.

**Comment by marefr** [comment]
Thanks! You may have been hit by a bug tracked in #11076.
