### ISSUE TITLE
MSSQL spaces in the tables and from

### ISSUE THREAD

**Issue by perplexityjeff** [grafana/grafana#12084]
I have successfully added the MSSQL datasource to Grafana. However in the syntax for MSSQL normally when a table or from has spaces in it you are required to use [Date and Time] for example. However this doesn't seem to work. 

I tried the following syntax, I have removed some company details. 

SELECT TOP(1) FROM [DATABASE].[dbo].[TABLE B_V_$Change Log Entry] 

However it doesn't seem to be able to handle the spaces from what I can see. Please let me know if I am doing anything wrong or if it is just unsupported. 

I am using the following systems.

Windows Server 2016 with SQL Server 2016
Debian 9 with  Grafana v5.1.3

**Comment by xlson** [comment]
@marefr can you take a look at this?

**Comment by marefr** [comment]
@perplexityjeff if you check the query inspector - what is the actual query generated using the above statement? I think that the issue may be `[TABLE B_V_$Change Log Entry]` - does it work better if you use `[TABLE B_V_[[Change]] Log Entry]`?

**Comment by perplexityjeff** [comment]
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1527491140018"
to:"1527512740018"
queries:Array[1]
response:Object
results:Object
A:Object
message:"mssql: Incorrect syntax near the keyword 'FROM'."

It seems to be even if you do not over complicate it. Just for example dbo.User is working however dbo.User Group requires me to do something about the space and normally in MSSQL [ ] would work but it seems in this it doesn't.

**Comment by perplexityjeff** [comment]
I think I believe in magic now. I copy and pasted the first sql query out of SQL Management Studio and no issue it just works. I fail to see at this time what the difference is or was but it works. 

In the end the full query was this.

SELECT [Date and Time] As Time ,[User ID] ,[Type of Change] ,[Primary Key Field 1 Value], [Old Value], [New Value] FROM [DATABASE].[dbo].[TABLE B_V_$Change Log Entry] WHERE $__timeFilter([Date and Time])

And this works great. Thank you for the quick responses everyone keep doing you @marefr.
