### ISSUE TITLE
API GET api/orgs hardcoded limit of 1000 organizations to return.

### ISSUE THREAD

**Issue by rrickardt** [grafana/grafana#12091]
First, thank you kindly for awesome work on grafana.

I am working on use-case where i separate users and dashboard with different organizations. When i create more than 1000, i am unable to list them in API, but i can see them in sqlite backend. So i found hardcoded limit here:

https://github.com/grafana/grafana/blob/83b7bbd60bc2be28e2f891f92da84e3dac74e81f/pkg/api/org.go#L167

I can do some PR to f.e. 10k, but i am not sure if this makes sense and what are overall plans with organizations concept.

Are there any details to share?

Thank you.

**Comment by marefr** [comment]
Hello. May I ask you how many users you expect to end up with? This is a real edge case and not something that we will work on except maybe if a PR is submitted.

If you plan to submit a PR I would suggest that you implement paging properly. Everything is already in place to handle paging in the SearchOrgsQuery handler. All you need to do is adding support for taking in the limit and page by querystring while still validating that the current defaults are used when no limit or page querystring parameter are provided.

If you would like this to be supported in the UI then you would also need to implement paging support there. You can see how paging for users in server admin have been implemented client side [here](https://github.com/grafana/grafana/blob/master/public/app/features/admin/admin_list_users_ctrl.ts#L20) and [here](https://github.com/grafana/grafana/blob/master/public/app/features/admin/partials/users.html#L69).

Would be nice if [orgs http api documentation](https://github.com/grafana/grafana/blob/master/docs/sources/http_api/org.md#search-all-organisations) is updated as well.

**Comment by rrickardt** [comment]
Hello,

well, this is definitely edge case and i do not think there will be someone else asking for the same thing. I will use teams for separation and rework my use-case. I am closing this. If there is someone asking for the same limit, please reopen, i will PR.

Thank you for your time.
