### ISSUE TITLE
Impossible to set auto refresh when interval is fixed

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#12105]
When the time interval is fixed it is no longer possible to set auto refresh on the graphes.

![1](https://user-images.githubusercontent.com/291750/40704865-ab7f1d30-63e9-11e8-85bb-a81852a6fa3f.png)
![2](https://user-images.githubusercontent.com/291750/40704866-abadbdde-63e9-11e8-8ae4-a48df5adc9f7.png)
![3](https://user-images.githubusercontent.com/291750/40704871-afed3780-63e9-11e8-8388-d9f1e607838e.png)

Version:  Grafana v5.2.0-pre1 (commit: f32e3a2)

**Comment by marefr** [comment]
Don't know what you mean by "no longer". Tried v4.6.3 and there it's not supported with auto refresh using absolute time. What version do you imply this have been working on?

**Comment by BrutalBirdie** [comment]
Histrionically view #3192

**Comment by BrutalBirdie** [comment]
Found a temporary fix for this Issue.
My Grafana Version ist v5.1.2 (commit: c3c690e21) append for example &refresh= 100ms to the URL.
Example:
http://localhost:3000/d/s0xtkY7mk/ultra-foo-bar?orgId=1&from=1528282800000&to=1528299000000&refresh=100ms

**Comment by torkelo** [comment]
Auto refresh for fixed time ranges is currently not supported
