### ISSUE TITLE
Share panel link didn't work after embed to another GUI.

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#12104]
### What Grafana version are you using?
5.1.0

### What datasource are you using?
influxdb

### What OS are you running grafana on?
ubuntu14.04

### What did you do?
embed the panel to another GUI.
and I want to share the panel link.

### What was the expected result?
Show the panel, just like share the panel link from grafana dashboard.

### What happened instead?
Show nothing.

This is the panel link from grafana:

http://localhost:3000/d/e5Ef8jkmz/system?orgId=1&panelId=5&fullscreen&from=1527641899401&to=1527663499401&var-server=All&var-datasource=default

And, it's works fine.

This is the panel link from my GUI after enbed:

http://localhost:3000/d-solo/e5Ef8jkmz/system?orgId=1&from=1527576991714&to=1527663391714&var-server=All&var-datasource=default&panelId=5&fullscreen

 This didn't work.

**Comment by marefr** [comment]
> http://localhost:3000/d-solo/e5Ef8jkmz/system?orgId=1&from=1527576991714&to=1527663391714&var-server=All&var-datasource=default&panelId=5&fullscreen
> This didn't work.

So what happens?

If I go to a dashboard, pull down menu for a panel and select share. Then switch to embed tab follow the instructions I get a embed link which is `http://localhost:3000/d-solo/...`. Loading that link works without any problem.

**Comment by crazy-canux** [comment]
I use embed link with iframe to put the panel to my own web gui.
And on my own web gui, I click    share -> link -> copy.
And paste the link to browser, but nothing show up.

Don't know why.

**Comment by marefr** [comment]
Thanks for the clarification. Confirmed bug. The pasted link includes a querystring parameter `&fullscreen` - removing that renders the panel correctly.

**Comment by crazy-canux** [comment]
That's right. 
Workaround is remove "fullscreen".

**Comment by torkelo** [comment]
This is not relevant anymore, an embedded panel has no share panel menu
