### ISSUE TITLE
PagerDuty alerting is using wrong data type for custom_details key

### ISSUE THREAD

**Issue by sbacelic** [grafana/grafana#12115]
As API per [docs](https://v2.developer.pagerduty.com/docs/events-api-v2#pagerduty-common-event-format-pd-cef) optional _custom_details_ field should be an object, not a string:

Snippet from [pagerduty.go](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/pagerduty.go#L79)

```
customData := "Triggered metrics:\n\n"
for _, evt := range evalContext.EvalMatches {
        customData = customData + fmt.Sprintf("%s: %v\n", evt.Metric, evt.Value)
}
...
payloadJSON.Set("custom_details", customData)
```

In PagerDuty event management you could filter events based on the contents of this field, but it requires object key to define filtering condition:

![screen shot 2018-05-30 at 16 36 55](https://user-images.githubusercontent.com/647434/40727228-bb98b9b8-6427-11e8-8670-7c1d3592590d.png)

Changing this could be breaking change but it would be a correct implementation, but as probably no one is using this event filtering, as its impossible to filter by custom_details, maybe fixing this won't be breaking change after all? 

Does it make sense to send a PR to fix this?

**Comment by torkelo** [comment]
Yes , a PR would great
