### ISSUE TITLE
Document how to rotate the secret key used to encrypt secure_json_data values

### ISSUE THREAD

**Issue by mattbostock** [grafana/grafana#12113]
Grafana uses a [secret key](http://docs.grafana.org/installation/configuration/#secret-key) to encrypt datasource credentials in a field called `secure_json_data` in its database. A [default is provided](https://github.com/grafana/grafana/blob/v4.6.3/conf/defaults.ini#L160-L161).

There should exist documentation explaining how an administrator can rotate the secret key, for example if it were leaked or if the default was not overridden.

### What Grafana version are you using?

4.6.3

### What datasource are you using?

N/A

### What OS are you running grafana on?

Linux

**Comment by marefr** [comment]
Right now the only way of doing this would be to change the secret key and manually update all data sources and set password (for example).

**Comment by oddlittlebird** [comment]
Is this a doc issue or a new feature request?

If a doc issue, then what needs to change in the docs to address it?

**Comment by marefr** [comment]
Feature request is here #15348. So currently add docs about when rotating the current secret key you have to manually re-configure all data sources and app plugins.

**Comment by marefr** [comment]
Would say the existing [docs](https://grafana.com/docs/grafana/latest/installation/configuration/#secret-key) is enough so will close this.
