### ISSUE TITLE
Slack notification sending body from app, image from bot user

### ISSUE THREAD

**Issue by Khord** [grafana/grafana#12116]
In the example [here](http://docs.grafana.org/alerting/notifications/), it shows the image inline with the notification body. In my testing as seen below, the app is sending the notification, then the bot user sends the image in a 2nd pic. Am I doing something wrong? It's a bit annoying for users to get 2 slack notifications in a row since the image takes a moment longer to upload.

![image](https://user-images.githubusercontent.com/21085666/40741862-a579cd46-641a-11e8-8591-ea66d251f0a7.png)

**Comment by rossmckelvie** [comment]
Do you have slack notifications configured to use a webhook, or a bot token, or both? I currently have s3 configured for external images in my `grafana.ini`, and only a webhook token for the alert settings, and I do not get any images with notifications. I am going to try adding the bot token again, but iirc it would send 2 separate messages like your screenshot. Kind of a bummer especially if you use slack's threads.

**Comment by Khord** [comment]
Both, using the bot token because I don't want to configure external image hosting. I believe what is happening is that the webhook is sending the notification and the bot user is sending the image, maybe because Grafana hasn't been designed to have the option to send the full notification via just the bot user.

**Comment by marefr** [comment]
You'll get two posts in slack since you're using the bot token to upload images to slack - this is a limitation of slack I would say. If you want one post please change to use the external image store.

**Comment by rossmckelvie** [comment]
@marefr I have external configured, with webhook and not a bot token, and alerting does not include the image.

**Comment by marefr** [comment]
@rossmckelvie what version of Grafana? Have you checked the *Include image* in the notification channel setup?

if you look in grafana server log when alert is triggered, do you get any information about possible issue with the external image storage? Please refer to the troubleshooting header [here](http://docs.grafana.org/alerting/rules/#notifications) for how to enable debug logs for certain parts of the alerting feature.
