### ISSUE TITLE
Appveyor build no longer archives the bin folder

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12110]
I know there there is effort to improve how all the builds are managed...  it seems the changes in:
https://github.com/grafana/grafana/commit/0bfbb1c16169ae2dbe96afa2c022101a7ac02fe0
https://github.com/grafana/grafana/pull/11920

Now leave the appveyor builds without a `bin` folder.  The size is ~30mb rather than ~50mb

This is the last build with a real artifact:
https://ci.appveyor.com/project/Torkeldegaard/grafana/build/6151/artifacts

Does circle build the windows artifacts?  if so, where are they?

**Comment by marefr** [comment]
You find them currently under nightly builds on grafana.com, for example https://grafana.com/grafana/download/5.2.0-18177pre1?platform=windows

**Comment by marefr** [comment]
Each commit pushed to master will build and package a nightly build in circle ci, see https://github.com/grafana/grafana/blob/master/.circleci/config.yml
