### ISSUE TITLE
Setting up OAuth2 with AAD not working

### ISSUE THREAD

**Issue by anmiralles** [grafana/grafana#12114]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
I am using helm stable chart but modify docker image pulled to latest. 

### What datasource are you using?
I am using Prometheus DS but this is not relevant for the issue.

### What OS are you running grafana on?
I am running Grafana on kubernetes 1.9.2 

### What did you do?
I am installing Grafana using helm stable chart and trying to setting up oauth2 with Azure Active Directory but finding same issue described here: [9703](https://github.com/grafana/grafana/issues/9703)

### What was the expected result?
The expected behaviour is signing in using AAD oauth2 authentication process.
As explained [12079](https://github.com/grafana/grafana/pull/12079) the issue should be solved since 2 days ago and merged in latest release.....

### What happened instead?
Instead when getting the token grafana is not going through the established HTTP_PROXY and trying directly, so getting time out connection:

t=2018-05-29T14:08:24+0000 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="Post https://login.microsoftonline.com/92e84ceb-fbfd-47ab-be52-080c6b87953f/oauth2/token: dial tcp 104.40.240.49:443: getsockopt: connection timed out" 

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![grafana](https://user-images.githubusercontent.com/5773365/40722817-abf27f6c-641d-11e8-9478-6c3ade8dffe3.png)

**Comment by marefr** [comment]
Please include more details:
* Your auth config (skip your secret keys and such)
* Are you running grafana using `HTTP_PROXY=<proxy url> ./grafana-server`?
* Are you running grafana behind reverse proxy?

**Comment by anmiralles** [comment]
Adding more details:

1. My Auth configuration:

auth.generic_oauth:
    name: Azure AD
    enabled: true
    allow_sign_up: true
    client_id: 644d3af2-0cf3-4e50-98fb-cec2822c49ca
    client_secret: ***********
    scopes: openid email name
    auth_url: https://login.microsoftonline.com/*********/oauth2/authorize
    token_url: https://login.microsoftonline.com/********/oauth2/token

2. Proxy configuration in values.yaml from grafana chart:

## Extra environment variables that will be pass onto deployment pods
env:
   HTTP_PROXY: http://*****.ericsson.se:8080 
   HTTPS_PROXY: http://******.ericsson.se:8080
   NO_PROXY: .ericsson.com,.ericsson.se,127.0.0.1,prometheus-server

3. I am running Grafana behind the previous proxy configured as env variables. All of them are present on container ENV variable and I suppose Grafana is using them.

If any other info required, just ask please.

Thanks in advanced for great job.

;)

**Comment by marefr** [comment]
reg 3) I would recommend you to try and verify that the proxy is actually working - maybe it's a docker issue? Are you using the proxy in any other case in Grafana?

**Comment by anmiralles** [comment]
Hi Markus,

we are running a lot of docker containers deployed on kubernetes cluster and there is no proxy issue with any of them. This is the common way in enterprise, having a proxy to external world.

What do you mean with "maybe it is a docker issue"?  you mean, the grafana docker image from this repo: 
https://hub.docker.com/r/grafana/grafana/

All I can say is that the docker container has the HTTP_PROXY, HTTPS_PROXY and NO_PROXY env variables set, and from inside it I have connectivity to the outside world, just doing a curl to wikipedia.org, for example.

I will continue investigating but it is exactly the same issue described here: [9703](https://github.com/grafana/grafana/issues/9703), with exactly the same stacktrace.

And finally, we are not using the proxy in any other use case because we are connecting with an internal prometheus server and just configuring dashboards, typical use case.

Thanks for your help.

**Comment by anmiralles** [comment]
Hi again Markus,

please close the issue. It is working with master branch...

I used latest thinking that is the same but for sure there are new commits to master branch. Now is working.

It was my bad....

Thanks and hope all issues will be solved as this one, without doing anything.
