### ISSUE TITLE
withCredentials  is enforced when defining datasource but not in dashboard

### ISSUE THREAD

**Issue by fbacchella** [grafana/grafana#12127]
I have a SSO solution in front off our ElasticSearch that defines a cookie to give access to it.

When defining the ElasticSearch datasource, there is a check bock called withCredentials. I think it uses https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials.
And indeed it works, I can see a SSO cookie forwarded when it’s checked.
But when defining a dashboard that uses that source, the cookie is not used any more. So grafana should be consistent. Either remove withCredentials from the source definition or add it to the dashboard definition.

I've just tested using grafana 5.1.3.

**Comment by marefr** [comment]
Are you using the direct/browser access mode? Please include more details of your requests/response where it's working and when it's not working - the network and console tab of chrome dev tools is good for this. Thanks

**Comment by fbacchella** [comment]
Yes, I'm using the direct/browser access mode

In editing data source, I see in the request to Elastic:
```
OPTIONS https://esserver/es/_msearch
Host: esserver
User-Agent: ...
Accept: application/json, text/plain, */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: http://...:3000/datasources/edit/2
Origin: http://...:3000
Cookie: _CAS_logsprod_cookie=...
Connection: keep-alive
DNT: 1
```

And ES is happy, and that make the source editor happy too, I got a 'Index OK. Time field name OK.'

But when editing a new dashboard, I see:
```
OPTIONS https://esserver/es/_msearch
Host: esserver
User-Agent: ...
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://...:3000
Connection: keep-alive
DNT: 1
```

The cookie is gone, there is 2 new Access-Control headers. 
And of course, the access is then denied on ES.
So the button "save and test" in source definition is not very usefull, as it's not doing a real consistent test.

**Comment by marefr** [comment]
The requests above are not controlled by Grafana - it's the browser which automatically does them. You have to use the proxy/server access mode in data source configuration.

**Comment by fbacchella** [comment]
They are controled by the javascript code, see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials:

The XMLHttpRequest.withCredentials property is a Boolean that indicates whether or not cross-site Access-Control requests should be made using credentials such as cookies, authorization headers or TLS client certificates. Setting withCredentials has no effect on same-site requests.

```
xhr.withCredentials = true;
```
 is probably missing.

If they can be no control about that, remove the check box in the source definition.

**Comment by marefr** [comment]
Yes so we're setting withCredentials here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L47

And then the options (withCredentials property included) flows down to this: https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L171

Here angular take over the responsibility for sending the request. Could be a bug in Angular, haven't been able to verify this.

Not sure, but maybe you'll need to respond with a https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials header from elasticsearch? How have you configured elasticsearch for CORS?

**Comment by fbacchella** [comment]
It's all done in apache:
```
    <Location />
        AuthType CAS
        CASSecureCookie CAS_logsprod_cookie
        CASScrubRequestHeaders on
        RequestHeader set CAS_uid expr=%{tolower:%{REMOTE_USER}}
        SetEnvIf Origin ".*" AccessControlAllowOrigin=$0
         Header always set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
         Header set Access-Control-Allow-Credentials true
         Header set Vary Origin
         # Bug in kibana that uses this header
         Header unset access-control-allow-origin
        <RequireAny>
            Require expr !(%{HTTP_USER_AGENT} =~ /Mozilla/)
            Require valid-user
        </RequireAny>
    </Location>
```

But I will check about this Access-Control-Allow-Credentials. The documentations indeed says:
The Access-Control-Allow-Credentials header works in conjunction with the XMLHttpRequest.withCredentials property or with the credentials option in the Request() constructor of the Fetch API. Credentials must be set on both sides (the Access-Control-Allow-Credentials header and in the XHR or Fetch request) in order for the CORS request with credentials to succeed.

And it's missing in some case.

**Comment by fbacchella** [comment]
Ok, it's now always returned, the HTTP response is:
```
HTTP/1.1 302 Found
Date: Fri, 01 Jun 2018 12:43:09 GMT
Server: Apache
Access-Control-Allow-Origin: http://...:3000
Access-Control-Allow-Credentials: true
Vary: Origin
Location: https://sso...
Content-Length: 399
Keep-Alive: timeout=5
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

And it doesn't help.
The javascript consols throws:
```
{
  "err": {
    "data": null,
    "status": -1,
    "config": {
      "method": "POST",
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "jsonpCallbackParam": "callback",
      "url": "https://..../es/_msearch",
      "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":[\".monitoring-es-6-2018.06.01\"]}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"timestamp\":{\"gte\":\"1527835389856\",\"lte\":\"1527856989856\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"30s\",\"field\":\"timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":\"1527835389856\",\"max\":\"1527856989856\"},\"format\":\"epoch_millis\"},\"aggs\":{}}}}\n",
      "withCredentials": true,
      "retry": 0,
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json;charset=utf-8"
      }
    },
    "statusText": "",
    "xhrStatus": "error"
  },
  "cancelled": true
}
```

It's says it's a POST, but the network tabs says it's a OPTIONS.

**Comment by marefr** [comment]
Any other error in the console?

**Comment by fbacchella** [comment]
OK, got it. CORS first send a OPTIONS with no credentials at all. Depending of the response, it decide what to do and it really dislike the 302 the SSO was sending.
It was not a bug in grafana, but it looks CORS is very difficult to setup correctly.
Now by settings my apache conf too:
```
    <Location />
        AuthType CAS
        CASSecureCookie CAS_logsprod_cookie
        CASScrubRequestHeaders on
        RequestHeader set CAS_uid expr=%{tolower:%{REMOTE_USER}}
        SetEnvIf Origin ".*" AccessControlAllowOrigin=$0
         Header always set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
         Header always set Access-Control-Allow-Credentials true
         Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, PUT"
         Header always set Vary Origin
         # Bug in kibana that uses this header
         Header unset access-control-allow-origin
        <RequireAny>
            Require expr !(%{HTTP_USER_AGENT} =~ /Mozilla/)
            Require expr (%{REQUEST_METHOD} == "OPTIONS")
            Require valid-user
        </RequireAny>
    </Location>
 ```

But I don't know why the same request "OPTIONS https://esserver/es/_msearch" sends the cookie in source definition but not in dashboard definition.

**Comment by marefr** [comment]
> But I don't know why the same request "OPTIONS https://esserver/es/_msearch" sends the cookie in source definition but not in dashboard definition.

Not sure I understand what you mean by source definition. If you're talking about when saving and testing the datasource - that's a GET request which normally don't is victim for CORS. POST requests almost everytime victom for CORS negotiation.

Using proxy/access mode is not an option for you and configure the whitelisted cookies setting?

**Comment by fbacchella** [comment]
I'm talking about the definition of Data Sources and the button Save and test. It send an GET, CORS it much less picky then, the cookie is indeed send and everything works fine.
But latter, in dashboard edition, it uses POST, then the navigator wants to check with OPTIONS and then everything falls apart. Perhaps the data source definition should not use GET then but POST, to be closer to the real uses in the dashboard.
But everything is working fine for me now, with the Apache configuration I show you.

**Comment by marefr** [comment]
Yes, changing the test datasource operation is definitely something we would like to improve for several of our datasources. Glad you sorted it out :+1:

**Comment by torkelo** [comment]
Browser never sends credentials in the OPTIONS call
