### ISSUE TITLE
Dashboard list doesn't autoscroll up when reduced when selecting a tag

### ISSUE THREAD

**Issue by bolind** [grafana/grafana#12126]
### What Grafana version are you using?
 Grafana v5.0.1 (commit: a747ec3)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu 16

### What did you do?
Created many dashboard with some tags, such that the dashboard list is longer than available screen height. Then scrolled to the bottom, and selected a tag, thus making the list shorter (by half.)

### What was the expected result?
That the resulting, filtered dashboards were visible.

### What happened instead?
The dashboard list doesn't autoscroll up (or autoreduce its height), so it appears there are no dashboards, when they are in fact hidden. Scrolling up makes everything fine.

**Comment by marefr** [comment]
Unable to reproduce on latest master 5.2.0 pre. Please upgrade to later version. If I misunderstood something let me know and I'll consider opening this again.

**Comment by bolind** [comment]
Issue also appears to be fixed in 5.1.3. Thanks!
