### ISSUE TITLE
Generated Query for Oracle plugin

### ISSUE THREAD

**Issue by achennuru** [grafana/grafana#12121]
Please include this information:
### What Grafana version are you using?
5.2.0-14847
### What datasource are you using?
Oracle
### What OS are you running grafana on?
Linux - CentOS release 6.9 (Final)
### What did you do?
Run sql queries and expect to see generated query.
### What was the expected result?
There should be a Generated Query link which shows the query that grafana is attempting to execute.
### What happened instead?
There is no link for Generated Query.

**Comment by Krinkle** [comment]
Test.

**Comment by daniellee** [comment]
This is implemented now in the Oracle data source.
