### ISSUE TITLE
Panels look very different in the different browsers

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#12139]
Using  v5.1.3 (commit: 087143285) on Ubuntu Linux with MySQL as a data source. I think the problems started appearing in Grafana 5.x, but I am not sure. Basically, the dashboard looks very different in the different browsers and it is practically impossible to make one that looks good everywhere. I realize that the different browsers have different style-related quirks, but can't you make the panels a bit more compatible?

The examples below show the differences of some panels (Table, Piechart) from one and the same dashboard in Firefox and Chrome. There are differences in the other major browsers too (IE, Opera) but they are not so drastic (e.g., Opera looks very much like Chrome, with only minor differences).

Table panel, Firefox:

![clipboard01](https://user-images.githubusercontent.com/580507/40909126-7cf5239a-67f1-11e8-93f0-2a5270d669e3.jpg)

Notice how there is very little space at the bottom - just enough to show the paginator. Same panel, Chrome:

![clipboard02](https://user-images.githubusercontent.com/580507/40909175-9afb73d0-67f1-11e8-9494-d8511fda86ba.jpg)

Note the huge and ugly empty space at the bottom.

Another example of a table panel, Firefox:

![clipboard06](https://user-images.githubusercontent.com/580507/40909227-b9594cc6-67f1-11e8-8a70-40f8cb7be7cf.jpg)

Again, the panel is just large enough for the paginator. Same panel, Chrome:

![clipboard07](https://user-images.githubusercontent.com/580507/40909249-caefec74-67f1-11e8-8ce8-f51498da8724.jpg)

Huge empty space at the bottom. If I correct that, in Firefox the paginator will be cut off.

Piechart panel, Firefox:

![clipboard03](https://user-images.githubusercontent.com/580507/40909312-f34effa2-67f1-11e8-9a8c-d7e6183e5627.jpg)

Note the ugly scroll bar. Same panel, Chrome:

![clipboard04](https://user-images.githubusercontent.com/580507/40909297-e1edc572-67f1-11e8-9b20-5d1fc7d66398.jpg)

The scroll bar is now properly black and narrow and practically invisible.

As an aside, why is it not possible to have a Piechart panel with just 2 values that does not have a scroll bar for the legend? No matter how I resize it, there is always a scroll bar and the legend never fits.

**Comment by torkelo** [comment]
Unable to replicate your problem with Grafana v5.1.3 and chrome 64 here:
https://play.grafana.org/d/000000031/table-panel-showcase?orgId=1 

what version of Chrome are you using? 

As for the piechart issue, make sure your using the latest version. If issue still persists, open issue here:
https://github.com/grafana/piechart-panel/

**Comment by bontchev** [comment]
Chrome version is 67.0.3396.62 (Official Build) (32-bit).

Firefox version is 55.0.3 (64-bit).

Piechart is the latest version.
