### ISSUE TITLE
[Feature Request] Variable group/tags search support

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#12130]
Hi,

It would be great if you could extend variable value searching also with the tag values look-up.

![grafana_search](https://user-images.githubusercontent.com/12551929/40837480-d7d4fece-659a-11e8-813a-a69364817d45.png)

Thanks in advance.
PaVliK

**Comment by marefr** [comment]
The groups/tags feature is an experimental feature (as noted in the UI) and not something that we plan to implement further right now so will close this now. Even if an issue is closed it won't mean we never reconsider opening it again. If for example lots of people upvotes this feature we'll consider implementing it/merging a contribution. Thanks
