### ISSUE TITLE
Add/Update installation instructions for ARM/Mac

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#12140]
With the new cross platform build support we'll need to add installation instruction docs for ARM. Also make sure to include instruction/guidelines for phantomjs rendering.

With the new build for mac we'll need to update the documentation to include running standalone MacOS/Darwin binaries besides existing homebrew.

**Comment by torkelo** [comment]
This documentation should be similar to this section:
http://docs.grafana.org/installation/debian/#installing-from-binary-tar-file 

maybe we can update that and use the same wording.
