### ISSUE TITLE
Grafana 5 - piechart not displaying slices

### ISSUE THREAD

**Issue by SashikalaV** [grafana/grafana#12147]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab. - Pasting result of Query inspector

xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/32"
data:"{"statements":[{"statement":"MATCH (n:DATA return distinct n.priority as Priority, count(n) as Count","includeStats":false,"resultDataContents":["row"]}]}"
response:Object
results:Array[1]
0:Object
columns:Array[2]
0:"Priority"
1:"Count"
data:Array[5]
0:Object
row:Array[Highest,1396]
meta:Array[2]
1:Object
row:Array[Medium,10842]
meta:Array[2]
2:Object
row:Array[High,7249]
meta:Array[2]
3:Object
row:Array[Lowest,165]
meta:Array[2]
4:Object
row:Array[Low,1891]
meta:Array[2]
errors:Array[0]

**Comment by marefr** [comment]
Please open an issue in [piechart repository](https://github.com/grafana/piechart-panel). Thanks
