### ISSUE TITLE
Variable value groups not preserved when refresh different than 'Never'

### ISSUE THREAD

**Issue by conet** [grafana/grafana#12155]
Please include this information:
### What Grafana version are you using?
5.1.1
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
CentOS
### What did you do?
Created a variable with value groups/tags, selected some tags, noticed that the tag is displayed in the variable's box instead of the list of selected values, saved the dashboard which works as expected, then reload the dashboard.

### What was the expected result?
That the tag is displayed in the variable's box instead of the list of selected values.

### What happened instead?
The list of values is displayed instead of the selected tag.

Note that if the refresh type is set to 'Never' the group is properly displayed after a reload but this is no option if one has dynamic groups/tags. Things that change in time like 'top 10' a workaround for issue #5013.

I would reproduce it here https://play.grafana.org/d/000000024/templating-value-groups but changes can't be saved.

**Comment by torkelo** [comment]
The value/groups feature in variables is an experimental feature that we will likely not develop further and likely deprecate/remove in the future.

**Comment by conet** [comment]
If you're planning to remove it may I ask what can be used instead to obtain something similar? Two variables one depending on the other?
