### ISSUE TITLE
Is it possible to set default value for 'Legend format' in case variable not available

### ISSUE THREAD

**Issue by iamzhout** [grafana/grafana#12158]
Please include this information:
### What Grafana version are you using?
Version 4.6.3 (commit: 7a06a47)

### What datasource are you using?
prometheus

### What OS are you running grafana on?
Linux

### What did you do?
Create a graph in grafana, and set its 'Legend format' to custom label, and for some recode, variable *{{code}}* *{{subcode}}* doesn't exist, and will display its literal value just as *code* and *subcode*

![image](https://user-images.githubusercontent.com/14846203/40950049-97664198-68a3-11e8-8490-e6b862bf0539.png)

![image](https://user-images.githubusercontent.com/14846203/40950099-d37805fe-68a3-11e8-948e-efe9b1207e34.png)

### What was the expected result?
I want to confirm whether it is possible to set default value, so that when *{{code}}*, *{{subcode}}* is not available, we can set its value to default value, which could be empty string, or some other value.

and I suppose the syntax could be like: `{{code:DEFAULT_CODE}}`

### What happened instead?
Legend format value just display as 'code-subcode'

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

There's already feature request open for this #5970

**Comment by iamzhout** [comment]
@marefr  I do have asked question on community site, [link here](https://community.grafana.com/t/how-to-set-default-value-for-legend-format-if-variable-not-available), and didn't get any reply during the past 2 days, then I post question here. 

Thanks for reply.

**Comment by harryge00** [comment]
@iamzhout  is there a solution now?

**Comment by matschaffer-roblox** [comment]
I found a workaround and posted it on [the community site](https://community.grafana.com/t/how-to-set-default-value-for-legend-format-if-variable-not-available/7860/3?u=matschaffer1)
