### ISSUE TITLE
Can't save dashboard when adding variable 

### ISSUE THREAD

**Issue by szaroubi** [grafana/grafana#12156]
Please include this information:
### What Grafana version are you using?
`grafana-server -v
Version 5.2.0-pre1 (commit: e258f30)`

### What datasource are you using?
`Elasticsearch (version 6)`

### What OS are you running grafana on?
`uname -a
Linux mipgrafana 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### What did you do?
- Open Existing Dashboard
- Go to settings -> variables
- Add variable
- Hit back (blue arrow in top right corner)
- I see the new Variable in the dashboard
![screen shot 2018-06-04 at 3 42 34 pm](https://user-images.githubusercontent.com/7586983/40937936-445516e0-680e-11e8-9806-e7242cf7239f.png)

- hit save (Notice that the JS templating seems to be borken, which leads me to believe it's a FrontEnd issue)
![screen shot 2018-06-04 at 3 43 02 pm](https://user-images.githubusercontent.com/7586983/40937939-47d70c7e-680e-11e8-82f1-70f12ad362e1.png)

### What was the expected result?
Dashboard should save, but doesn't

### What happened instead?
Silent failure

#### Console output (Chrome)
`vendor.e7d78054d3e9f343c870.js:87 TypeError: Cannot read property 'current' of undefined
    at t.compareTemplating (:3000/public/build/0.e7d78054d3e9f343c870.js:15)
    at t (:3000/public/build/0.e7d78054d3e9f343c870.js:15)
    at Object.a [as invoke] (vendor.e7d78054d3e9f343c870.js:87)
    at f.instance (vendor.e7d78054d3e9f343c870.js:87)
    at h (vendor.e7d78054d3e9f343c870.js:87)
    at a (vendor.e7d78054d3e9f343c870.js:87)
    at a (vendor.e7d78054d3e9f343c870.js:87)
    at vendor.e7d78054d3e9f343c870.js:87
    at app.e7d78054d3e9f343c870.js:8
    at vendor.e7d78054d3e9f343c870.js:87
(anonymous) @ vendor.e7d78054d3e9f343c870.js:87
vendor.e7d78054d3e9f343c870.js:87 TypeError: Cannot read property 'current' of undefined
    at t.compareTemplating (:3000/public/build/0.e7d78054d3e9f343c870.js:15)
    at t (:3000/public/build/0.e7d78054d3e9f343c870.js:15)
    at Object.a [as invoke] (vendor.e7d78054d3e9f343c870.js:87)
    at f.instance (vendor.e7d78054d3e9f343c870.js:87)
    at h (vendor.e7d78054d3e9f343c870.js:87)
    at a (vendor.e7d78054d3e9f343c870.js:87)
    at a (vendor.e7d78054d3e9f343c870.js:87)
    at vendor.e7d78054d3e9f343c870.js:87
    at app.e7d78054d3e9f343c870.js:8
    at vendor.e7d78054d3e9f343c870.js:87 "Possibly unhandled rejection: {}"`

#### Console Output (Safari)
`[Error] undefined is not an object (evaluating 'this.dashboardSrv.dash.originalTemplating[t].current')
http://mipgrafana.radio-ip.com:3000/public/build/0.e7d78054d3e9f343c870.js:15
	(anonymous function) (vendor.e7d78054d3e9f343c870.js:87:47629)
	(anonymous function) (vendor.e7d78054d3e9f343c870.js:87:83972)
	i (vendor.e7d78054d3e9f343c870.js:87:21876)
	(anonymous function) (vendor.e7d78054d3e9f343c870.js:87:23334)`

`[Error] undefined is not an object (evaluating 'this.dashboardSrv.dash.originalTemplating[t].current')
http://mipgrafana.radio-ip.com:3000/public/build/0.e7d78054d3e9f343c870.js:15 – "Possibly unhandled rejection: {\"line\":15,\"column\":65358,\"sourceURL\":\"http://mipgrafana.radio-ip.com:3000/public/build/0.e7d78054d3e9f343c870…"
	(anonymous function) (vendor.e7d78054d3e9f343c870.js:87:47629)
	c (vendor.e7d78054d3e9f343c870.js:87:68949)
	$digest (vendor.e7d78054d3e9f343c870.js:87:74826)
	$apply (vendor.e7d78054d3e9f343c870.js:87:76646)
	(anonymous function) (vendor.e7d78054d3e9f343c870.js:87:84019)
	i (vendor.e7d78054d3e9f343c870.js:87:21876)
	(anonymous function) (vendor.e7d78054d3e9f343c870.js:87:23334)`

**Comment by szaroubi** [comment]
Note that I can save the dashboard if I bring changes to a panel.

- Resize panel
- Hit save
- Reload dashboard (force reload)
- Panel is still resized.

**Comment by marefr** [comment]
Please pull the latest commit from master or nightly build. Should be fixed by #12144

**Comment by szaroubi** [comment]
Thanks for the fix.
