### ISSUE TITLE
Alert notification not working in case of datasource error

### ISSUE THREAD

**Issue by megafinz** [grafana/grafana#12151]
### What Grafana version are you using?
Grafana v5.1.3

### What datasource are you using?
Prometheus 2.2.1

### What OS are you running grafana on?
Docker image.

### What did you do?
Created graph panel, set up alerting rule + Slack notification.

### What was the expected result?
I expect Slack notification to be correctly dispatched in case alert state becomes `Alerting` at all times.

### What happened instead?
By default alerting rule should change state to `Alerting` when there is an error or timeout. When I shut down my prometheus datasource container, State History tab correctly displays current condition as `Alerting`, but I'm not getting a notification in Slack. In case `Alerting` state is toggled because of the data conditions, then I get an alert notification as expected.
![](https://i.imgur.com/5lfxowz.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Docker logs:

1. OK → Alerting (data conditions):
```
grafana-alert-test-grafana | t=2018-06-04T13:36:21+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=alerting prev state=ok
grafana-alert-test-grafana | t=2018-06-04T13:36:21+0000 lvl=info msg=Rendering logger=png-renderer path="d-solo/q5CMVNSik/dashboard?panelId=2"
grafana-alert-test-grafana | t=2018-06-04T13:36:22+0000 lvl=info msg=uploaded logger=alerting.notifier url=
grafana-alert-test-grafana | t=2018-06-04T13:36:22+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification="Alert Test"
```
 
2. Alerting (data conditions) → OK:
```
grafana-alert-test-grafana | t=2018-06-04T13:36:51+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=ok prev state=alerting
grafana-alert-test-grafana | t=2018-06-04T13:36:51+0000 lvl=info msg=Rendering logger=png-renderer path="d-solo/q5CMVNSik/dashboard?panelId=2"
grafana-alert-test-grafana | t=2018-06-04T13:36:52+0000 lvl=info msg=uploaded logger=alerting.notifier url=
grafana-alert-test-grafana | t=2018-06-04T13:36:52+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification="Alert Test"
```

3. OK → Alerting (datasource error):
```
grafana-alert-test-grafana | t=2018-06-04T13:37:14+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error Get http://host.docker.internal:9090/api/v1/query_range?end=2018-06-04T13%3A37%3A13.768646Z&query=up&start=2018-06-04T13%3A37%3A03.768646Z&step=15.000: dial tcp 192.168.65.2:9090: connect: connection refused" changing state to=alerting
grafana-alert-test-grafana | t=2018-06-04T13:37:14+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=alerting prev state=ok
grafana-alert-test-grafana | t=2018-06-04T13:37:14+0000 lvl=info msg=Rendering logger=png-renderer path="d-solo/q5CMVNSik/dashboard?panelId=2"
grafana-alert-test-grafana | 2018/06/04 13:37:16 http: proxy error: dial tcp 192.168.65.2:9090: connect: connection refused
grafana-alert-test-grafana | t=2018-06-04T13:37:16+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=127.0.0.1 time_ms=1003 size=0 referer="http://localhost:3000/d-solo/q5CMVNSik/dashboard?panelId=2&render=1&orgId=1"
grafana-alert-test-grafana | t=2018-06-04T13:37:44+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
grafana-alert-test-grafana | t=2018-06-04T13:37:44+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification="Alert Test"
grafana-alert-test-grafana | t=2018-06-04T13:37:44+0000 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook="Alert Test"
grafana-alert-test-grafana | t=2018-06-04T13:37:44+0000 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"
```

**Comment by marefr** [comment]
What setting do you have on your alert rule for the "no data" condition?

**Comment by megafinz** [comment]
There is no "no data" condition set up currently. However I did use that condition previously and it was working just fine.

**Comment by marefr** [comment]
Seems to be an issue with the image rendering timing out

**Comment by megafinz** [comment]
Oh, sorry, I thought you were talking about "Conditions" block. For "If no data or all values are null" case I left the default "No Data" setting.

Pretty basic setup overall:
![](https://downloader.disk.yandex.ru/preview/45e8982e08b74518a4ff0c0f6575221a14afaa8bd56d109c96d967bbc5bfd504/5b15b4cf/VvdTmveLcZdEfFJ_jSS5ItqUYJMekv5NjfAK2PDBZClvMYJMMb7-MAurtJCwuDr6Ho0cGB8O0aL-gAmrIX10TQ%3D%3D?uid=0&filename=2018-06-04_20-52-59.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=2048x2048)

**Comment by megafinz** [comment]
> Seems to be an issue with the image rendering timing out

What kind of image rendering? I don't have any image included in my notification, just some basic text:
![](https://downloader.disk.yandex.ru/preview/84a6eb7abc3d04f8cbc26863e35367ea548a7cdb67c082f7b7c26e83a23225a6/5b15b73e/VvdTmveLcZdEfFJ_jSS5IhRNQaEP04rvZs5DUrBgWbGE2d16jItpa3MOOgwktKGQDNmRkE0ZiW2yGu6TgVNmjQ%3D%3D?uid=0&filename=2018-06-04_21-02-24.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=2048x2048)

**Comment by marefr** [comment]
You provided the following log which states that the image rendering times out. 
`grafana-alert-test-grafana | t=2018-06-04T13:37:44+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"`

Grafana alerting renders an image of the graph when an alert rule goes into alerting state, see [documentation](http://docs.grafana.org/alerting/notifications/#slack). 

For your graph where you've defined your alert rule - if you click on panel title, share and the *Direct link rendered image* link - do you get a rendered image?

**Comment by marefr** [comment]
What access mode are you using, direct/browser or proxy/server?

**Comment by megafinz** [comment]
I'm using the default server access mode. Basically everything is default with a minimal graph/alert/notification setup.

**Comment by marefr** [comment]
Thank you. Finally got time to reproduce it. Confirmed bug. Working in at least Grafana v4.1.0, but not in Grafana v4.6.3 and forward.

**Comment by mstipanov** [comment]
I have the same experience, but it also affected other data sources.
Until we fixed the Prometheus issue, no Elasticsearch alerts was processed.
Can this be related to the same issue or I need to continue my search for the cause.
