### ISSUE TITLE
Include the git commit hash in the master docker container tag 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#12165]
Running Grafana master in k8s or any other orchestrator that caches the docker image on a node is problematic since `master` might be different grafana versions on each node. To solve this Problem we want to include the git commit in the tag.

So instead of deploying `grafana/grafana:master` people can deploy a specific master version. ex `grafana/grafana:master-74adf4`. Since this would polute the docker hub page we have decided to use another repo for master releases. `grafana/grafana-master:<git-commit>`

**Comment by DanCech** [comment]
The concern about "polluting" https://hub.docker.com/r/grafana/grafana/tags/ is a valid one I think, a suggestion would be to have a separate `grafana/grafana-dev` image that can be built on every commit (and potentially on every pr/branch also).

**Comment by bergquist** [comment]
This have been fixed. Those containers can be found at https://hub.docker.com/r/grafana/grafana-dev/tags/
