### ISSUE TITLE
gap between PanelIds

### ISSUE THREAD

**Issue by n3k232** [grafana/grafana#12160]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.1.3 (087143285)

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
SLES 12 SP 3

### What did you do?
Built a Dynamic Dashboard with repeating Rows.
Select Host and Service and repeat the Panel for eacht Unit of the Host

### What was the expected result?
I thought i would get a Dashboard with incremented PanelIDs panel2, panel2 panel3...

### What happened instead?
the First Panel started with ID 2 the second one with ID 13 and so on.

Is this Gap wanted?
because i wanted to curl against the Dashboard sequential to get every Panel from a Service.

**Comment by torkelo** [comment]
panel ids are not sequential, whenever a new panel is added (or repeated) panel id is generated, taking the max panel id + 1

**Comment by dotw** [comment]
then, how to predict the panel Id when using repeat rows?
I'm facing a scenario now that one dashboard is using repeat rows and another system want to reuse the graph using iframe approach. The system can't integrate the pages in because they don't know what panel id will be generated. how to resolve this?
