### ISSUE TITLE
[Feature Request] Only show gear/trash icon when hovering collapsed row

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12163]
When a row is collapsed, the gear and trash icon are all visible:
![image](https://user-images.githubusercontent.com/705951/40967600-bddb3116-68b3-11e8-9452-bcff1ab1bf76.png)

It would be nice if they had the same behavior as open rows -- only showing up when hovered.

Also, do we need the word "hidden" -- that seems obvious and just extra stuff to read.  I would rather see :  

`More Graphs! (7 panels)`

**Comment by torkelo** [comment]
your right, these changes would be great :+1:
