### ISSUE TITLE
timeEnd error when updating Annotation

### ISSUE THREAD

**Issue by olivernz** [grafana/grafana#12173]
### What Grafana version are you using?
5.1.3
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
RedHat

### Description of issue:
I am trying to update the timeEnd via the Annotation API

Create Annotation:
curl -s -X POST -H 'Authorization: Bearer <whatever>' -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{ "time":1527816482028, "timeEnd":1527817082030, "isRegion":true, "tags":[ "Test-A", "jenkins", "smoketest"], "text":"Jenkins (Preliminary): Smoketest_Test-A - 59" }' http://XYZ:3000/api/annotations

Update Annotation:
curl -s -X PUT -H 'Authorization: Bearer ’ -H ‘Content-Type: application/json’ -H ‘Accept: application/json’ -d ‘{ “time”:1527816482028, “timeEnd”:1527816505249, “isRegion”:true, “tags”:[ “Test-A”, “jenkins”, “smoketest”], “text”:“Jenkins: Smoketest_Test-A - 59” }’ http://XYZ:3000/api/annotations/53
**_{“message”:“Failed to update annotation for region end time”}_**

If I look at the code (annotations.go) there definitely is something weird here, which might explain this effect.

if cmd.IsRegion {
	itemRight := item
	itemRight.RegionId = item.Id
	itemRight.Epoch = cmd.TimeEnd

	// We don't know id of region right event, so set it to 0 and find then using query like
	// ... WHERE region_id = <item.RegionId> AND id != <item.RegionId> ...
	itemRight.Id = 0

	if err := repo.Update(&itemRight); err != nil {
		return Error(500, "Failed to update annotation for region end time", err)
	}

}

**Comment by torkelo** [comment]
can you view the logs for more error details?

**Comment by olivernz** [comment]
Ah I think I got it this time round. The setting of the Annotation comes back with two IDs ({"endId":119,"id":118,"message":"Annotation added"}). My regular expression extracted the 1st ID and tried updating that and that gives the above error (works though if it's and annotation without range). If you do the update in the actual ID then it all works. A bit confusing but OK. I just didn't see the response and notice it was doing the wrong ID. So I think you can close this. Sorry for that.
