### ISSUE TITLE
Option to have fullscreen graph URL instead of alert tab URL in alert notifications 

### ISSUE THREAD

**Issue by vovkanaz** [grafana/grafana#12176]
We want follow to the graph url when we've receive email alert instead of alert list button and alert config button.

**Comment by sanchomuzax** [comment]
+1

**Comment by bergquist** [comment]
Yea that makes sense

**Comment by xyzmurali** [comment]
Any update on this, will this be fixed?

**Comment by arvin495** [comment]
If we can have something like "PanelUrl" or "GraphUrl" just like "RuleUrl", alerts can be customized changing respective values in email templates.
I believe it makes sense.

**Comment by santihernandezc** [comment]
This is a pretty old issue, but I think it's worth adding a comment before closing it.
We're not developing new features for Legacy Alerting. We're still fixing bugs when we get bug reports, but the main focus is on the new [Unified Alerting](https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/) system.
