### ISSUE TITLE
Add support for skipping variable value in URL

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#12174]
Please include this information:
### What did you do?
- Opened one of the K8s devstats charts: https://k8s.devstats.cncf.io/d/48/github-stats-by-repository-group?orgId=1
- Changed `Statistic` drop-down value from `Reviewers` (default) to `Commits` (does not matter, this happens when I change any template variable)
- Grafana generated new URL that contains *all* template variable values: https://k8s.devstats.cncf.io/d/48/github-stats-by-repository-group?orgId=1&var-period=h24&var-repogroups=All&var-full_name=Kubernetes&var-docs=%3Ch1%20id%3D%22kubernetes-ghstats-dashboard%22%3EKubernetes%20GitHub%20stats%20dashboard%20(commits)%3C%2Fh1%3E%0A%3Cp%3ELinks:%3C%2Fp%3E%0A%3Cul%3E%0A%3Cli%3ERepository%20groups%20version%20metric%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fmetrics%2Fkubernetes%2Fgithub_stats_by_repo_groups.sql%22%20target%3D%22_blank%22%3ESQL%20file%3C%2Fa%3E.%3C%2Fli%3E%0A%3Cli%3ERepositories%20version%20metric%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fmetrics%2Fkubernetes%2Fgithub_stats_by_repos.sql%22%20target%3D%22_blank%22%3ESQL%20file%3C%2Fa%3E.%3C%2Fli%3E%0A%3Cli%3ETSDB%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fmetrics%2Fkubernetes%2Fmetrics.yaml%22%20target%3D%22_blank%22%3Eseries%20definition%3C%2Fa%3E.%20Search%20for%20%3Ccode%3Egithub_stats_by_repo%3C%2Fcode%3E%3C%2Fli%3E%0A%3Cli%3EGrafana%20dashboard%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fgrafana%2Fdashboards%2Fkubernetes%2Fgithub-stats-by-repository-group.json%22%20target%3D%22_blank%22%3EJSON%3C%2Fa%3E%20(repository%20groups%20version).%3C%2Fli%3E%0A%3Cli%3EGrafana%20dashboard%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fgrafana%2Fdashboards%2Fkubernetes%2Fgithub-stats-by-repository.json%22%20target%3D%22_blank%22%3EJSON%3C%2Fa%3E%20(repositories%20version).%3C%2Fli%3E%0A%3Cli%3EDeveloper%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fdocs%2Fdashboards%2Fkubernetes%2Fghstats_devel.md%22%20target%3D%22_blank%22%3Edocumentation%3C%2Fa%3E.%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Ch1%20id%3D%22description%22%3EDescription%3C%2Fh1%3E%0A%3Cul%3E%0A%3Cli%3EThis%20documentations%20only%20refers%20to%20%3Ccode%3ECommits%3C%2Fcode%3E%20statistic.%3C%2Fli%3E%0A%3Cli%3EThis%20dashboard%20shows%20the%20number%20of%20commits%20(by%20counting%20distinct%20commit%27s%20SHAs)%20for%20a%20selected%20repository%20or%20repository%20group.%3C%2Fli%3E%0A%3Cli%3EYou%20can%20select%20multiple%20repositories%20or%20repository%20groups%20to%20stack%20them.%3C%2Fli%3E%0A%3Cli%3EYou%20can%20filter%20by%20repository%20or%20repository%20group%20and%20period.%3C%2Fli%3E%0A%3Cli%3ESelecting%20period%20(for%20example%20week)%20means%20that%20dahsboard%20will%20count%20commits%20in%20this%20period.%3C%2Fli%3E%0A%3Cli%3ESee%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fdocs%2Fperiods.md%22%20target%3D%22_blank%22%3Ehere%3C%2Fa%3E%20for%20more%20informations%20about%20periods.%3C%2Fli%3E%0A%3Cli%3ESee%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fdocs%2Frepository_groups.md%22%20target%3D%22_blank%22%3Ehere%3C%2Fa%3E%20for%20more%20informations%20about%20repository%20groups.%3C%2Fli%3E%0A%3Cli%3EWe%20are%20skipping%20bots%20when%20calculating%20number%20of%20commits,%20see%20%3Ca%20href%3D%22https:%2F%2Fgithub.com%2Fcncf%2Fdevstats%2Fblob%2Fmaster%2Fdocs%2Fexcluding_bots.md%22%20target%3D%22_blank%22%3Eexcluding%20bots%3C%2Fa%3E%20for%20details.%3C%2Fli%3E%0A%3C%2Ful%3E&var-stat=commits
- When I copy and paste this url into next tab it is not working anymore - displays blank page with error `source code was found in the url`.
- The problem is that dashboard documentation is a template variable that contains HTML file (fetched from the DB).
- I was searching for any option (in template variable definition) to disable including this variable in the url but Grafana documentation says that all template variable values are included in the URL.
### What was the expected result?
- Would be very nice if we can have a checkbox in template variable definition saying `Include variable value in the url` defaulting to `yes`.
### What happened instead?
- When I change any template variable everything still works ok but url becomes extremely long. Only after copy+paste this url into new tab you can see that this url is nt working.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Go to dashboard: https://k8s.devstats.cncf.io/d/48/github-stats-by-repository-group?orgId=1
![screen shot 2018-06-06 at 07 19 16](https://user-images.githubusercontent.com/2469783/41018413-02da4daa-695a-11e8-8f54-9f2ddfabdc7f.png)

Change any template variable (horrible long url is generated but all works fine)
![screen shot 2018-06-06 at 07 20 59](https://user-images.githubusercontent.com/2469783/41018455-2db03788-695a-11e8-8e05-0d4687f716b1.png)

Copy and paste this url and safari blocks
![screen shot 2018-06-06 at 07 14 02](https://user-images.githubusercontent.com/2469783/41018470-3f3c3aec-695a-11e8-9b96-5476f11d3113.png)

Template variable definition:
![screen shot 2018-06-06 at 07 22 04](https://user-images.githubusercontent.com/2469783/41018498-5a9c8f44-695a-11e8-98eb-ea81387e31f1.png)
https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/github-stats-by-repository-group.json#L367-L380
https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/github-stats-by-repository-group.json#L497-L519

**Comment by lukaszgryglicki** [comment]
I've researched Grafana configuration options and didn't find any solution for this.
I've googled a bit and found information that grafana always include all template variable values in the URL.
But this template variable is hidden and cannot be changed from the UI.
So I think there is no sense to include its value in URL.
- One solution could be adding support for skipping some template variables values in the URL.
- Other solution might be that Grafana should skip values of hiden template variables in the URL (user can't change them anyway).

**Comment by torkelo** [comment]
The hidden docs variable has a value that contains a massive html string :)

```html
h1 id="kubernetes-ghstats-dashboard">Kubernetes GitHub stats dashboard (commits)</h1>↵<p>Links:</p>↵<ul>↵<li>Repository groups version metric <a href="https://github.com/cncf/devstats/blob/master/metrics/kubernetes/github_stats_by_repo_groups.sql" target="_blank">SQL file</a>.</li>↵<li>Repositories version metric <a href="https://github.com/cncf/devstats/blob/master/metrics/kubernetes/github_stats_by_repos.sql" target="_blank">SQL file</a>.</li>↵<li>TSDB <a href="https://github.com/cncf/devstats/blob/master/metrics/kubernetes/metrics.yaml" target="_blank">series definition</a>. Search for <code>github_stats_by_repo</code></li>↵<li>Grafana dashboard <a href="https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/github-stats-by-repository-group.json" target="_blank">JSON</a> (repository groups version).</li>↵<li>Grafana dashboard <a href="https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/github-stats-by-repository.json" target="_blank">JSON</a> (repositories version).</li>↵<li>Developer <a href="https://github.com/cncf/devstats/blob/master/docs/dashboards/kubernetes/ghstats_devel.md" target="_blank">documentation</a>.</li>↵</ul>↵<h1 id="description">Description</h1>↵<ul>↵<li>This documentations only refers to <code>Commits</code> statistic.</li>↵<li>This dashboard shows the number of commits (by counting distinct commit's SHAs) for a selected repository or repository group.</li>↵<li>You can select multiple repositories or repository groups to stack them.</li>↵<li>You can filter by repository or repository group and period.</li>↵<li>Selecting period (for example week) means that dahsboard will count commits in this period.</li>↵<li>See <a href="https://github.com/cncf/devstats/blob/master/docs/periods.md" target="_blank">here</a> for more informations about periods.</li>↵<li>See <a href="https://github.com/cncf/devstats/blob/master/docs/repository_groups.md" target="_blank">here</a> for more informations about repository groups.</li>↵<li>We are skipping bots when calculating number of commits, see <a href="https://github.com/cncf/devstats/blob/master/docs/excluding_bots.md" target="_blank">excluding bots</a> for details.</li>↵</ul>
``´

Not really the part of the original use case for template variables but I can see that using variables like this is interesting. So adding an option would be an option worth considering.

**Comment by lukaszgryglicki** [comment]
Possibly just skip adding template variables if they are hidden?
Users can't change them anyway?

But I think that having a flexibility to specify include in url or not would be great.

**Comment by lukaszgryglicki** [comment]
@torkelo can you please poiunt me to the place in code where urls are generated?
I mean the place where template variable values are added to the url?
I want to implement this feature (skipping hidden template variable values) and then create PR for that.

**Comment by lukaszgryglicki** [comment]
Created PR that implements this: https://github.com/grafana/grafana/pull/12259
You can test it https://grafana.cncftest.io/d/12/dashboards?refresh=15m&orgId=1
Login: admin
Password: adminadmin.

I need to find a way to create package froma branch - so I can update our Grafanas to have that option turned on before it gets merged.

**Comment by qc00** [comment]
For those who found this issue, but not sure how to use the fix:

You need to find the variable in the "Json Model" in the dashboard's Settings and set the `skipUrlSync` attribute to `true`.
