### ISSUE TITLE
Macros in trigger URLs do not expand properly

### ISSUE THREAD

**Issue by svdasein** [grafana/grafana#12185]
### What Grafana version are you using?
 5.1.3 

### What datasource are you using?
alexanderzobnin-zabbix-app @ 3.9.1 

### What OS are you running grafana on?
ubuntu intel

### What did you do?
Defined a URL in a trigger with the macro {HOST.HOST} embedded in it

### What was the expected result?
When the links presented in the zabbix triggers panel would have {HOST.HOST} expanded appropriately

### What happened instead?
URL in zabbix triggers panel is rendered with {HOST.HOST}

**Comment by torkelo** [comment]
the zabbix repo is here, https://github.com/alexanderzobnin/grafana-zabbix
