### ISSUE TITLE
instance Multi-value

### ISSUE THREAD

**Issue by dinggel** [grafana/grafana#12195]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
4.4.3
### What datasource are you using?
prometheus
### What OS are you running grafana on?
centos6
### What did you do?
using Selection Options -> Multi-value with instance(ip)
### What was the expected result?
A new line of automatic drawing machines
### What happened instead?
when i select Multi-value with instance variable,it said "No data points"，but if i select Multi-value with dev variable, it work well
query:  io_util{job="[[job]]", group="[[group]]",host="[[hosts]]",dev="[[dev]]"}

 Multiple hosts
![image](https://user-images.githubusercontent.com/22829724/41091020-302de720-6a78-11e8-873b-09f8e8bc7394.png)

Multiple dev
![image](https://user-images.githubusercontent.com/22829724/41091116-6da8cb56-6a78-11e8-8789-8f50b52f25c9.png)

**Comment by marefr** [comment]
Please use regex syntax **`label=~"^$var"`** to support single value/multiple values/all, i.e. `query: io_util{job="[[job]]", group="[[group]]",host=~"^[[hosts]]",dev="[[dev]]"}`

**Comment by dinggel** [comment]
Thanks, Very happy!!!
