### ISSUE TITLE
Number order problem with InfluxDB

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#12193]
Please include this information:

### CentOS

The order function doesn't work properly with number type tags. Please, see the screenshot.
The ordering isn't numeric-based, but text-based, but I have modified the index field to number.
Please, add the numerical sorter function to it as sames as in the Template Variables sorter.

![20180607080652](https://user-images.githubusercontent.com/2911588/41083511-aa44f07c-6a31-11e8-9984-9eb50986f6a0.png)

Thank you!

**Comment by ryantxu** [comment]
In influx, tags are always strings :(

We solved this by using tags like 'T01'

**Comment by sanchomuzax** [comment]
Please, try this and look at the result as I want to do on Table also:

![2018-06-07 22-06-27](https://user-images.githubusercontent.com/2911588/41125377-92ffdd5a-6aa4-11e8-8c22-a223adc4d3f1.png)

**Comment by torkelo** [comment]
Tags in influxdb are strings, so the table panel will sort them as strings.
