### ISSUE TITLE
Add 'sort metric' indicator (preferably a tiny arrow directed according to the sort direction).

### ISSUE THREAD

**Issue by the0ffh** [grafana/grafana#12205]
I admit I have no idea whether the following qualifies as an issue or a feature request, since the functionality is present at least since few releases, but lacks any indicator/indication ('manual/'docs').

The problem is related to the first column in the legend, a metric so to speak. It would be really nice to have e.g. an arrow displaying the sorting order.

Please find below the suggested placing for the one mentioned above.

![screen shot 2018-06-07 at 23 25 29](https://user-images.githubusercontent.com/26150100/41127576-acd310ba-6aab-11e8-9d1f-9c12dcbd3cfb.png)

Idea behind this issue/'feature request is to turn an easter egg into a (in my opinion) standard feature.

Regards,
m.

**Comment by bergquist** [comment]
If you haven't selected a sort order Grafana will use the order of the response from the data source. Which grafana doesn't know anything about. could be asc/desc. We only show the arrow if you selected to override the order by clicking the legend titles. 

Does that give some clarity? I'm not totally sure I understand this issue.

**Comment by torkelo** [comment]
It’s not an Easter egg , it’s hidden, sorting by series name is done your metric query. 

We can hide/disable it even more if you like but not that many who has found this hidden bug :)
