### ISSUE TITLE
Ad hoc Filters & support for number values

### ISSUE THREAD

**Issue by yue6121** [grafana/grafana#12209]
- What Grafana version are you using?  5.1.3
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? Ubuntu 16.04
- What did you do?
ad hoc filter
- What was the expected result?
show the logIds
- What happened instead?
get logId data, but do not show the logIds for select
**the error is**  
Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html
http://errors.angularjs.org/1.6.7/$sce/itype?p0=html
    at angular.js:116
    at a (angular.js:19372)
    at Object.r.(:3000/d/6pT6WTSmz/anonymous function) [as trustAsHtml] 
    at new n (segment_srv.ts:82)
    at r.newSegment (segment_srv.ts:103)
    at repeat_option.ts:14
    at m (lodash.js:660)
    at Function.ps [as map] (lodash.js:9570)
    at repeat_option.ts:13
    at u (angular.js:17145) "Possibly unhandled rejection: {}"

**Comment by yue6121** [comment]
![popo 201868142635](https://user-images.githubusercontent.com/8063831/41142467-5dcd81e4-6b28-11e8-9edc-f3bb415d261f.png)

**Comment by yue6121** [comment]
thank you

**Comment by vmanju123** [comment]
seeing same issue with elastic search data , unable to do adhoc filter .any number based field, any update on how to fix this ?, if someone can point me to grafana code where this functionality is being called, i can take a look and willing to help, thanks

**Comment by svennergr** [comment]
Hi @vmanju123 and @yue6121,

I know this issue is quite old. I think that's why I can not reproduce this on Grafana 9.0.3 / 8.5.6. Thus I am closing this here. If I am mistaking, I am happy to reopen and followup.

https://user-images.githubusercontent.com/8092184/179709926-b1b290b8-741c-4cec-991b-3f61cd2b25c9.mov

Best
@svennergr
