### ISSUE TITLE
Fill Above feature

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#12201]
I'm currenty trying to a little bit of anomaly detection with prometheus data and I got this:

![fill_above](https://user-images.githubusercontent.com/153052/41107018-a42a3658-6a71-11e8-8984-df9dc0948658.PNG)

 With `Fill Below` I'm able to outline the period where the metrics is above the "normal" range but there is no `Fill Above` feature that would allow to outline when the metric is below the range.

Also being able to choose the Fill color would be super nice.

**Comment by torkelo** [comment]
fill below requires a series to fill below to, so fill above would be the exact same, just revert the series you specify it on, and the series you fill to
