### ISSUE TITLE
Images are not rendered when sharing text panel via "Direct link rendered image"

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#12210]
### What Grafana version are you using?
4.6.3
### What OS are you running grafana on?
Linux
### What did you do?
Create an html text panel that includes an image, e.g. 

    Test html text panel rendering in grafana-reporter with images
    <img src="https://facebook.github.io/react-native/img/header_logo.png">

This renders both the text and image correctly in the text panel itself. 
![image](https://user-images.githubusercontent.com/8266640/41142847-8518854a-6af7-11e8-83e1-111835f82fe6.png)

### What was the expected result?
When I share the panel using "Direct link rendered image", I expect both the text and the image to be rendered in the shared PNG. 
### What happened instead?
The image is not present.
![image](https://user-images.githubusercontent.com/8266640/41142809-531cdcda-6af7-11e8-9c31-07cb958e4b20.png)

**Comment by daniellee** [comment]
This works now:

![image](https://user-images.githubusercontent.com/434655/98602189-5b9d8280-22e0-11eb-926d-d515e6a0621a.png)
