### ISSUE TITLE
Right index marches left across graph

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#12214]
Grafana version: 5.1.3
Desktop OS: Mac OS High Sierra
Browser: Firefox 52.8.1 (ESR)

If I swipe the cursor up and down the right index of a graph, the index moves to the left. If I do it enough times, the index can appear in the middle of the graph.

<img width="718" alt="screen shot 2018-06-08 at 11 30 45 pm" src="https://user-images.githubusercontent.com/24280758/41160896-58ce28dc-6b74-11e8-8a54-52610c6b00e7.png">

**Comment by yellowpattern** [comment]
Firefox 60 doesn't support plugins that I need.

I have downloaded and tried "NewMoon 27.9.0 (64-bit)" with the same result.

"NewMoon" is the MacOS X port of the "Pale Moon" browser.

**Comment by torkelo** [comment]
Ok, I can replicate in OSX, seems to be related to the OSX overlay scrollbars.

**Comment by torkelo** [comment]
closing this as it's the same as https://github.com/grafana/grafana/issues/12726 (and that issue has more details & comments)
