### ISSUE TITLE
MySQL Graph panel autoscale problem

### ISSUE THREAD

**Issue by Bernasca** [grafana/grafana#12217]
**What Grafana version are you using?**

Grafana v5.0.3

**What datasource are you using?**

MySQL

**What OS are you running grafana on?**

Ubuntu Docker

**What did you do?**

Whenever i'm using a Graph panel with the MySQL datasource the Y axis doesn't autoscale to the maximum data in the time period. The maximum is always the max data in the table, regardless of the time period.

In the screenshoot you can see that there is no Y-Max setted, and how the Y axis goes to 2500 when the max value for the time period is always below 1500. 
Also check that the max value is 2334, very close to 2500.

![grafana](https://user-images.githubusercontent.com/40073611/41179814-6e2e4950-6b42-11e8-8840-78fc3916fc5b.jpg)

This doesn't happen with other datasources like Elasticsearch

**What was the expected result?**

The Graph should autoscale to the maximum Y axis value whenever you change the time period queried

**What happened instead?**

The maximum Y axis value always stays the same

**Comment by daniellee** [comment]
What does your query look like? Is the time filter correct?

**Comment by Bernasca** [comment]
Hi @daniellee!

I'm sorry, I skipped the query. Here it goes:

SELECT ACTIVIDAD as metric,
            CANTIDAD as value,
            time_sec as time_sec
FROM ORDENES_T3_FIJO_UMBRAL
order by time_sec

I don't see any problems here, because it's too simple. 

Thanks in advance!

**Comment by PyIES** [comment]
You are not using $__timeFilter()
You must change the query by:

SELECT ACTIVIDAD as metric,
CANTIDAD as value,
time_sec as time_sec
FROM ORDENES_T3_FIJO_UMBRAL
WHERE $__timeFilter(time_sec) 
order by time_sec

**Comment by daniellee** [comment]
> The maximum is always the max data in the table, regardless of the time period.

As @PyIES says, you have no where clause in your sql query so you are not filtering the data for the selected time period. So Grafana is showing the data for the time period but calculating the max based on the all the data you have selected. You should use a where clause and Grafana has macros like the $__timeFilter macro to help you write them.

Docs for time series queries for the mySQL datasource: http://docs.grafana.org/features/datasources/mysql/#time-series-queries
