### ISSUE TITLE
Strange error when logging in

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#12212]
Using Grafana  v5.1.3 (commit: 087143285) on Linux with a MySQL data source.

When logging in, something that looks like some kind of error flashes for a _very_ short time (fraction of a second) - then my dashboard loads without a problem. But since it happens every time, it gets kinda annoying. I think it started happening in Grafana 5.x.

It took me quite a lot of effort to catch exactly what the error is, since it appears only very briefly. Eventually, I had to capture a screen video and review it frame-by-frame. Here is the image of the error; it seems to be some kind of page not found error:

![screenshot 2018-06-08 12 05 04](https://user-images.githubusercontent.com/580507/41149508-68c71754-6b14-11e8-8636-0eb9ffbffef2.png)

Why does this happen and how to stop it from happening? It's not caused by something missing from my dashboard, because the dashboard loads just fine. I do have some quirks in my setup, though, so maybe one of them is confusing Grafana somehow? In particular:

1) Grafana is not accessed from the root of the web server but from a sub-directory. Like, it is not on https://www.somesite.com/ but on https://www.sometite.com/grafana. I use Nginx as the web server and the following configuration:

```
    location /grafana {
        proxy_set_header Host $host;
        rewrite /grafana/?(.*)$ /$1 break;
        proxy_pass http://localhost:3000/;
        proxy_set_header Authorization "";
    }
```

2) The home dashboard of the user is not the default list of dashboards but the one particular dashboard (the only existing one) that I want displayed immediately after the user logs in.

Unfortunately, my knowledge of Go is practically non-existent, so I can't quite figure out what Grafana is doing. It seems that this error page is displayed by `public/app/routes/routes.ts` when it can't quite match some path in the URL? But then things seems to recover and the configured dashboard _is_ displayed.

BTW, the error appears not only at login time. If I select "Home" from the Dashboards menu, it appears (again briefly) there too.

**Comment by bergquist** [comment]
Have you configured the `root_url` in `grafana.ini`? http://docs.grafana.org/installation/configuration/#root-url

**Comment by bontchev** [comment]
Yes, I have - sorry for not mentioning it. It is set to this:

```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
```

**Comment by daniellee** [comment]
If you check the network tab in the Chrome/Firefox developer tools, can you see what url is returning a 404 - Not found error? You should also be able to see any 404 errors in the Grafana server logs.

**Comment by bontchev** [comment]
@daniellee, initially I thought so too, but this is _not_ the case. I don't see any such error - neither on the web console, nor in the Nginx error log. And from looking at the code (disclaimer - I don't know Go), it seems to me that this is not a "real" 404 web server error but some error displayed by Grafana itself.

And it doesn't seem to be logged in the Grafana log when this error occurs in `public/app/routes/routes.ts`, either. At least there is nothing about it in `/var/log/grafana/grafana.log`. The only error there is a bit strange

```
{"error":"User not found","logger":"context","lvl":"eror","msg":"Failed to get user with id","t":"2018-06-12T08:08:57.749389191+03:00","userId":3}
```

but the timestamps don't match the times when I test it with the browser, so I assume that's just somebody trying to brute-force the login form.

Is there any other log that I might be missing?

**Comment by daniellee** [comment]
As you say, it is on the frontend. Grafana is a Single Page App so the Go code only loads the initial page and JavaScript. 

But you should be able to see something in the network tab. For example, if I try to access `http://localhost:3000/d/000000563/viewer-dash?orgId=1` and am not logged in, then after logging in I should be redirected to that page and on the network tab, on the first row (with type document) I can see that url:

![image](https://user-images.githubusercontent.com/434655/41301985-a16a74f4-6e69-11e8-80ea-074827071ba8.png)

If I login into the root (`http://localhost:3000) then I should see the home page being loaded - like this:

![image](https://user-images.githubusercontent.com/434655/41302187-28ccf5e8-6e6a-11e8-9bf7-de1ec4bac735.png)

Do you see anything with a 404 on the network tab?

**Comment by bontchev** [comment]
@daniellee, I do _not_ see any such thing. Here is what the browser console displays about the site running Grafana. I am logged in, hover over the "Dashboards" button and select "Home" - which results in the error being displayed briefly and then my configured home dashboard being displayed. As you can see, there are no 404 errors on the Net tab. Everything is 200 OK. But I _do_ see that error page flashing for a fraction of a second.

![clipboard01](https://user-images.githubusercontent.com/580507/41303038-d16e0d68-6e74-11e8-9e4e-ef03747467f9.jpg)

Also, I thought I had posted a message about this, but it seems to have disappeared - the error occurs _only_ when the user is configured to go directly to a particular dashboard, instead of to the default dashboard list.

Would you like me to give you a guest user access to my dashboard, so that you can see for yourself? You won't be able to change anything (the guest user is only a viewer) but the error occurs there too.

**Comment by bontchev** [comment]
No other ideas? Meanwhile, Grafana has been updated to version v5.1.4 (a5fe24fcc) - but the problem still persists. I have created a "test" user with a single panel on the dashboard, just to demonstrate the problem. Does any of you want access to it for testing?

**Comment by torkelo** [comment]
remove the nginx rewrite rule, that should not be needed, and make sure your grafana root_url is correct (the full browser nginx url including subpath) 

http://docs.grafana.org/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-com-grafana

**Comment by bontchev** [comment]
My `root_url` (mentioned above) is correct. The `rewrite` might not be necessary but surely it isn't what is causing the problem?

Anyway, after upgrading to Grafana v5.3.1 (08c7908), it seems that the problem has finally stopped appearing.
