### ISSUE TITLE
[BUG] Templating value not OK

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#12216]
Hi,

### What Grafana version are you using?
5.1.3
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
CentOS 7
### What did you do?
My index contain values with "-".
Example : 
field1 contain "foo-bar", "john-doe" values
I want to get this values as variable with this query : 
``{"find":"terms","field":"field1"}``
### What was the expected result?
A variable with this 2 values : 
- foo-bar
- john-doe
### What happened instead?
A variable with 4 values : 
- foo
- bar
- john
- doe

Thank you

**Comment by liujin1993** [comment]
I think this is due to your Elasticsearch config. By default string  is analyzed, and the type is “text”. You should set mapping to "keyword" using template or dynamic template.

**Comment by daniellee** [comment]
Sounds like a mapping problem, just like @liujin1993 says. So closing this issue - I can reopen it if it turns out to be a bug in Grafana.
