### ISSUE TITLE
Datasource provisioning: should allow one default per organisation

### ISSUE THREAD

**Issue by schweikert** [grafana/grafana#12229]
Currently if I try to provision datasources automatically for our multiple organisations, I get:

    Failed to provision Grafana from config. error: datasource.yaml config is invalid. Only one datasource can be marked as default

In datasources.yaml I have something like:

    - orgId: 1
      name: prometheus
      type: prometheus
      isDefault: True
      access: proxy
      url: http://prometheus.example.com:9090
    - orgId: 2
      name: prometheus
      type: prometheus
      isDefault: True
      access: proxy
      url: http://prometheus.example.com:9090

**Comment by bergquist** [comment]
This should be fixed in https://github.com/grafana/grafana/blob/master/pkg/services/provisioning/datasources/config_reader.go#L92

**Comment by schweikert** [comment]
Thank you!
