### ISSUE TITLE
Feature request: Custom font size for table panel

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/grafana#12227]
We're using a dasboard with a set of table panels, and showing this dashboard on LCD screen.
We had a font size 130% for table panels with grafava v4, but grafana v5 has a reduced font size, so our panels is less readable now. The next step after 130% is 150%, but it's qute big font size (dasboard looks bad with this value).

Is it possible to allow custom values for font size for table plugin? It will make dasboards configuration more flexible.

Thanks in advance!

**Comment by glajchs** [comment]
![image](https://user-images.githubusercontent.com/2104019/49604551-26ea5900-f95c-11e8-9e9c-879af1a8f8c6.png)
Here's an example of how I've jerry-rigged our dashboard to have large text, so we can use it in kiosk mode for our TV (with actual data redacted).
All you do is put a small (as small as you can make it) transparent text box at the bottom, of type "HTML", and put the content like so:
```<style>
.panel-title-text {
    font-size: x-large;
}
.panel-menu-toggle {
    font-size: x-large;
}
.panel-content {
    height: calc(100% - 44px);
}
div.flot-tick-label {
    font-size: x-large;
}
.graph-legend-series {
    font-size: 22px;
}
.graph-legend-icon {
    top: 2px;
}
.graph-legend-icon .fa {
    font-size: 175%;
    top: 4px;
}
.axisLabel {
    font-size: 24px;
}
.panel-content {
    padding: 10px 10px;
}
.left-yaxis-label {
    left: 4px;
}
.right-yaxis-label {
    right: 4px;
}
div.flot-x-axis > div.flot-tick-label {
    font-size: large;
}
</style>```

Not a real fix, but I hope it helps!

**Comment by glajchs** [comment]
![image](https://user-images.githubusercontent.com/2104019/49604708-a1b37400-f95c-11e8-91f7-9d1c05356b3b.png)
Here's an example of how I've jerry-rigged our dashboard to have large text, so we can use it in kiosk mode for our TV (with actual data redacted).
All you do is put a small (as small as you can make it) transparent text box at the bottom, of type "HTML", and put the content like so:
```<style>
.panel-title-text {
    font-size: x-large;
}
.panel-menu-toggle {
    font-size: x-large;
}
.panel-content {
    height: calc(100% - 44px);
}
div.flot-tick-label {
    font-size: x-large;
}
.graph-legend-series {
    font-size: 22px;
}
.graph-legend-icon {
    top: 2px;
}
.graph-legend-icon .fa {
    font-size: 175%;
    top: 4px;
}
.axisLabel {
    font-size: 24px;
}
.panel-content {
    padding: 10px 10px;
}
.left-yaxis-label {
    left: 4px;
}
.right-yaxis-label {
    right: 4px;
}
div.flot-x-axis > div.flot-tick-label {
    font-size: large;
}
</style>```

Not a real fix, but I hope it helps!

**Comment by nilebox** [comment]
you can also set
```
.grafana-tooltip {
    font-size: 24px;
}
```
if you need a giant tooltip font (e.g. during a presentation).

**Comment by bengoa** [comment]
Are you guys still able to use these tricks? 

Seems that it stopped to work with Grafana 6.

**Comment by RamonSalem** [comment]
> Are you guys still able to use these tricks?
> 
> Seems that it stopped to work with Grafana 6.

Stopped working with Grafana 6 here too.

**Comment by NachoDuck** [comment]
If Grafana 6 you need to set the disable_sanitize_html setting for this to work, see https://grafana.com/docs/installation/configuration/#disable-sanitize-html

**Comment by wyxa** [comment]
> If Grafana 6 you need to set the disable_sanitize_html setting for this to work, see https://grafana.com/docs/installation/configuration/#disable-sanitize-html

In Grafana 7 you don't have disable_sanitize_html anymore.
Just for those who are unaware.

**Comment by torkelo** [comment]
Closing this as it's not relevant for new table panel

**Comment by Rudorufu-san** [comment]
This work for me. Grafana 9
**"I stand on the shoulders of titans. Thanks guys!"**
1.Modify the grafana configuration file (grafana.ini)
uncomment (delete ";")

>                                  [panels]
>                                  disable_sanitize_html = true

2.Add at the bottom of the dashboard "text panel" and turn on a transparent background.
3.Open the Options tab and switch to a HTML mode
4.Paste next CSS code:
```
<style>
.panel-title h2{
font-size: 50px;
font-weight: 700;
}
.panel-title {
height: 60px;
line-height: 60px;
}
</style>
```
