### ISSUE TITLE
Feature request: hide panel top as well as top nav in kiosk mode

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/grafana#12228]
We're using Grafana v5 and some dashboards densily packed with table panels. Each panel have a top with a drop-down menu, that exist on the dashboard even in "kiosk" mode with "&inactive"
![panel](https://user-images.githubusercontent.com/8307692/41231865-bbca2ce2-6dae-11e8-9f7d-7c19fc4ac67c.jpg)

This header was much more smaller in grafana v4 and allow to save some space on the screen. To put all the panels on the screen now we have to reduce panel's size and make it less readable.

It is possible to hide panel's top in kiosk mode? This mode is very useful for displaying a dashboard without any additional UI elements.

Thanks in advance!

**Comment by marefr** [comment]
Similar to #10326 but this is clearly for kiosk mode

**Comment by PhantomPhreak** [comment]
I do not insist on doing this in kiosk mode only. For me it looks like an UI element that consumes some space on dasboard without any functionality. So getting rid of it in any mode will solve this problem, but kiosk mode is preferrable because we're using it for displaying dashboards on LCD.
Thanks!

**Comment by amandagmsd** [comment]
Hi,

Any update on this?

This update would be useful for me even in non-kiosk mode.

**Comment by anatolyza** [comment]
+1 
It’s an important feature
I would hate to fork the repo and get stuck on a version for this.

**Comment by torkelo** [comment]
This was fixed long time ago, panels without any title have no header now , no katter if your in kiosk mode or not
