### ISSUE TITLE
Convert all Frontend Karma tests to Jest tests.

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#12224]
## Why

The main advantage of the Karma testrunner is that it can execute the tests in a real browser and that it can execute them in multiple browser in one test run. This tests that the JavaScript works in all supported browsers.

The reasons why are switching to the Jest testrunner:
- Browsers are better at implementing standards. We do not execute the Karma tests in multiple browsers, only PhantomJS. Very few bugs are due to browser incompatibility. Means we don't have any need for its main advantage.
- Performance. The Karma tests are slow. Jest runs tests in parallel.
- The Jest testrunner has some intelligent features that speed up the feedback cycle - for example the fast interactive watch mode runs only test files related to changed files.

## How

Currently a Karma test has the name standard `<filename>_specs.ts` and are located in a `specs` subfolder for the feature being test.

1. Copy the file and rename it to `<filename>.jest.ts
2. Remove `import {describe, it, expect} from 'test/lib/common';` from the jest file.
3. Rename all expectations in the file:
    - `to.be` to `toBe`
    - `to.eql` to `toEqual`
    - `to.contain` to `toContain`
4. Replace mocks/stubs/fakes with Jest mocks
5. All tests should be green, then commit and create a PR and reference this issue.

Some Karma tests might require some extra steps to convert them to Jest tests.

## List of Karma Tests
 
- [x] [singlestat_panel_spec.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/specs/singlestat_panel_spec.ts)
- [x] [version_specs.ts](https://github.com/grafana/grafana/blob/master/public/test/core/utils/version_specs.ts)
- [x] [app_specs.ts](https://github.com/grafana/grafana/blob/master/public/test/specs/app_specs.ts)
- [x] [value_select_dropdown_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/core/specs/value_select_dropdown_specs.ts)
- [x] [backend_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/core/specs/backend_srv_specs.ts)
- [x] [postgres/specs/datasource_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/specs/datasource_specs.ts)
- [x] [influxdb/specs/query_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/specs/query_ctrl_specs.ts)
- [x] [graphite/specs/query_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/specs/query_ctrl_specs.ts)
- [x] [mysql/specs/datasource_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mysql/specs/datasource_specs.ts)
- [x] [elasticsearch/specs/datasource_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/datasource_specs.ts)
- [x] [elasticsearch/specs/elastic_response_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/elastic_response_specs.ts)
- [x] [elasticsearch/specs/query_builder_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/query_builder_specs.ts)
- [x] [elasticsearch/specs/index_pattern_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/index_pattern_specs.ts)
- [x] [elasticsearch/specs/query_def_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/specs/query_def_specs.ts)
- [x] [cloudwatch/specs/datasource_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/specs/datasource_specs.ts)
- [x] [prometheus/specs/completer_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/specs/completer_specs.ts)
- [x] [prometheus/specs/datasource_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/specs/datasource_specs.ts)
- [x] [heatmap/specs/heatmap_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/heatmap/specs/heatmap_ctrl_specs.ts)
- [x] [heatmap/specs/renderer_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/heatmap/specs/renderer_specs.ts)
- [x] [graph/specs/graph_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/specs/graph_specs.ts)
- [x] [graph/specs/tooltip_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/specs/tooltip_specs.ts)
- [x] [graph/specs/graph_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/specs/graph_ctrl_specs.ts)
- [x] [graph/specs/threshold_manager_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/specs/threshold_manager_specs.ts)
- [x] [graph/specs/series_override_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/specs/series_override_ctrl_specs.ts)
- [x] [singlestat/specs/singlestat_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/specs/singlestat_specs.ts)
- [x] [playlist/specs/playlist_edit_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/playlist/specs/playlist_edit_ctrl_specs.ts)
- [x] [alerting/specs/alert_tab_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/specs/alert_tab_specs.ts)
- [x] [alerting/specs/threshold_mapper_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/specs/threshold_mapper_specs.ts)
- [x] [dashboard/specs/share_modal_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/share_modal_ctrl_specs.ts)
- [x] [dashboard/specs/dashboard_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/dashboard_srv_specs.ts)
- [x] [dashboard/specs/history_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/history_ctrl_specs.ts)
- [x] [dashboard/specs/time_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/time_srv_specs.ts)
- [x] [dashboard/specs/history_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/history_srv_specs.ts)
- [x] [dashboard/specs/exporter_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/exporter_specs.ts)
- [x] [dashboard/specs/viewstate_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/viewstate_srv_specs.ts)
- [x] [annotations/specs/annotations_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/annotations/specs/annotations_srv_specs.ts)
- [x] [plugins/specs/datasource_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/plugins/specs/datasource_srv_specs.ts)
- [x] [org/specs/team_details_ctrl_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/org/specs/team_details_ctrl_specs.ts)
- [x] [templating/specs/variable_srv_init_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/templating/specs/variable_srv_init_specs.ts)
- [x] [templating/specs/variable_srv_specs.ts](https://github.com/grafana/grafana/blob/master/public/app/features/templating/specs/variable_srv_specs.ts)

**Comment by torkelo** [comment]
So most of the remaining tests are angular tests, which can be tricky to get to work in node (jest + fake browser env), not sure we have converted a single angular test to node so not sure how this will work :)

**Comment by dehrax** [comment]
I made a list of all the components with listed complexity. This is the estimated difficulty for me to rewrite them. I need a firmer understanding of Angular mocks before I can tackle most of them.
https://docs.google.com/spreadsheets/d/14W6YYUGiKudYVdfSZ-oSUU0FlBgr6eIeAnMaTy-QZxs/edit?usp=sharing

**Comment by daniellee** [comment]
@dehrax you have already classified the tests by difficulty so maybe you could try and convert some of the level 2 tests:

- https://github.com/grafana/grafana/blob/master/public/app/features/org/specs/team_details_ctrl_specs.ts
- https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/time_srv_specs.ts
- https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/history_srv_specs.ts
- https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/specs/history_ctrl_specs.ts

They use the test helper but have normal JavaScript constructors.

**Comment by torkelo** [comment]
one thing that I think can be part of this is changing file name convention so jest uses it's default naming convention (.test|spec.ts).

If some tests proves really hard to convert then a final option would be to try to see if the code under test can be refactored and moved outside the angular component.

**Comment by dehrax** [comment]
I found these, which are not in the list.
- [ ] [datasource/opentsdb/query-ctrl-specs](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/opentsdb/specs/query-ctrl-specs.ts)
- [ ] [datasource/opentsdb/datasource-specs](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/opentsdb/specs/datasource-specs.ts)

**Comment by astral303** [comment]
What a waste of time to do it right now. It would've been better to release 5.3 earlier, such that we could get features such as the super-useful `$range` variable sooner.

**Comment by marefr** [comment]
@astral303 your comment is noted. However, this migration is very important for everyone contributing code to Grafana, for our upcoming migration to React and for our CI to be able to run faster. Looking at maintenance perspective for Grafana it's vital that we continue to improve and iterate on tooling and such that makes life easier for everyone involved making it possible to continue deliver the Grafana we all love. 

Regarding that we could have released 5.3 earlier if we didn't do this - that's not true. The 5.3 plan has been the same without this migration in consideration since we actually had a summer intern doing all the migration work.

You should expect a 5.3 beta release very soon with hopefully a 5.3 stable in the upcoming weeks.
