### ISSUE TITLE
Query not showing when selecting "default" datasource instead of datasource name

### ISSUE THREAD

**Issue by tspadi** [grafana/grafana#12235]
Hello There,
I'd like to report an issue in grafana 5.1.3
we configured a graphite datasource named graphite, and selected it as the default datasource 
we configured another graphite datasource with a different name
In our dashboards, we use "default" to specify our graphite datasource, but we noticed the query editor doesn't show up.
To be able to see the query, we have to select the datasource by its name "graphite"

Here is the behaviour when using "default" which is graphite
![image](https://user-images.githubusercontent.com/34246464/41284658-3483b136-6e3a-11e8-9fae-425bcd601c22.png)

And here when using the datasource by its name : 
![image](https://user-images.githubusercontent.com/34246464/41284614-1c39b3be-6e3a-11e8-8a01-584370194983.png)

We noticed as well that if we switch from default to graphite, the query appears, and stays when we switch back to default, until the dashboard edition is closed. But this behaviour is creating a lot of confusion among users. Could you please fix this ?

**Comment by daniellee** [comment]
This works locally for me (I have multiple graphite datasources and one of them is set as default).

Can you provide some more details:

- check the console in the Chrome Developer tools for JavaScript errors
- check the Grafana server logs for errors
- try saving the default datasource again (maybe toggling it off saving and then toggling it on and saving again).

**Comment by torkelo** [comment]
closing due to lack of updates (more detail)
