### ISSUE TITLE
Unable to change local user password while auth.proxy or ldap is enabled

### ISSUE THREAD

**Issue by Tautvydas3333** [grafana/grafana#12238]
Grafana v5.1.2 
### What datasource are you using?
ZABBIX API
### What OS are you running grafana on?
Debian GNU/Linux (stretch)

### What did you do?
I tried to change password with a local user.
### What was the expected result?
Password change.
### What happened instead?
I got an error:
"You cannot change password when ldap or auth proxy authentication is enabled."

**Comment by daniellee** [comment]
This was done on purpose: https://github.com/grafana/grafana/issues/2495

@torkelo is this a bug or a feature?

**Comment by duckie** [comment]
Yes, the goal is understandable, but it should only be disabled for people actually logged in through LDAP. A local user, or at least admin, should be able to change its password. Now my local admin cant change its password anymore, and changing it in LDAP cant help since it is a local user with no counterpart in the LDAP directory.

To me, #2495 is imcomplete : the spec should be to disable passwords change for LDAP users only.

**Comment by Tautvydas3333** [comment]
I completely agree with duckie. My situation is the same.

**Comment by mayankdevops** [comment]
Hello,
I was facing the same issue. I enabled LDAP and then i wanted to reset my admin (non ldap user) passwd.
I tried from profile, curl, cli and changing the defaults.ini nothing worked. 
Fortunately i tried changing the admin user passwd using "Server-Admin" section and it worked for me.
I am using Grafana version - V5.2.2

Thanks,
-Mayank

**Comment by langebe** [comment]
Is there a status update? This is not a behavior you would expect.

To be honest, I wouldn't care at all if there were CLI options to disable accounts or completely disable local user management.

**Comment by benrubson** [comment]
Same issue here.
I enabled `auth.proxy` to configure a dashboard reachable without password.
Unfortunately now, users can't change their password anymore...
Rather suprising :-|

**Comment by hackery** [comment]
+1 for allowing local users to change their password even when LDAP is enabled. It seems very reasonable to maintain some local users (particularly but not only admin) in case of some failure of the LDAP auth method.

There appears to be an edge case where a pre-existing local user name matches an LDAP user name; in my team we've seen that both the local password and the password from LDAP can be used to log in. Torkel [mentions in #15817](https://github.com/grafana/grafana/issues/15817#issuecomment-470022721) that the internal auth is attempted first; presumably a change would require the authentication source to be recorded with the session, and that determine whether the option is available.

Also - it's been noted here and elsewhere that the Server Admin area can be used to change a user's password (although of course that breaks the principle that the user should be able to change it to something the admin doesn't know); a secondary issue is that this is still available for LDAP users - reinforcing @duckie's suggestion above that #2495 is incomplete. Making a password change there would lead to the situation above where both that and the LDAP password would work.

I'm willing to have a look at the code for a potential PR, but it'd be a Copious Spare Time attempt.

**Comment by s4ndst0rm** [comment]
Hi There,

any Update on this? 
Im facing the same issue with NO LDAP but Auth Proxy enabled.

All other users cannot change their PW.

**Comment by rnersesian** [comment]
Hello !

I am also wondering if this will be fixed in later updates. 

Peace
