### ISSUE TITLE
ways to keep things clean

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#1223]
not sure how others deal with this, but in our case, people like to just create more and more dashboards and/or add more graphs to existing dashboards, and after a while you end up with lots of "stuff" and it's unclear if
1) anyone uses it and
2) what for/how.

if nobody uses it, we could delete it, if some people use it, it is still possible that we would be able to merge several graphs into one, or move some graphs to a different dash, etc.

the first case (used vs not used) is probably easiest to get started with, especially on a dashboard level (we could just track how many times specific dashboards are being displayed, or rely on the "mark as favorite" feature). for graph/widget level, maybe we could add simple 'star' buttons

**Comment by torkelo** [comment]
closing as similar to https://github.com/grafana/grafana/issues/1403
