### ISSUE TITLE
Config keys ending with _FILE are not respected in 5.2.0-beta1

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#12239]
There is a new feature in the grafana docker image to support reading docker secrets from files. Unfortunately this feature conflicts with pre-existing config options that ends in `_FILE` so that they no longer works.

Actual bug: https://github.com/grafana/grafana-docker/issues/170

(added this issue to make sure that we fix it before releasing 5.2.0 stable)

**Comment by DanCech** [comment]
The simplest solution is likely just to add a `| grep -v GF_\(AUTH_LDAP_CONFIG\|SERVER_CERT\)_FILE` at the end of the initial command to exclude those from the list

**Comment by xlson** [comment]
@DanCech Yeah, that would work. I'm was thinking it might be a good idea to go with `-FILE` instead so that we don't have to worry about keeping the run-script updated if we add more file configs in the future.

**Comment by DanCech** [comment]
That's an interesting idea too

**Comment by xlson** [comment]
Fixed by https://github.com/grafana/grafana-docker/pull/172

**Comment by FUSAKLA** [comment]
Could be the `5.1.4` image be rebuild with this fix or could be `5.1.4-1` image be released?

The latest version of docker image is now incompatible

**Comment by xlson** [comment]
@FUSAKLA  we will release a 5.1.5 to fix this issue. Thanks for reporting it.

**Comment by FUSAKLA** [comment]
Great, thanks!
