### ISSUE TITLE
Adhoc templating and save issues

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#12240]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.0-pre1 (1f32871)
### What datasource are you using?
Any
### What OS are you running grafana on?
Any
### What did you do?
Save dashboard with adhoc templating variables
### What was the expected result?
Save problems
### What happened instead?
Some errores encountered
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Hint: grafana/public/app/features/dashboard/save_modal.ts:114 consider **current** attribute but adhoc filtering does not contain it grafana/public/app/features/templating/adhoc_variable.ts.

I have initially fixed in my own code but, before submitting a pull request, I have to inspect some other issues because this kind of variables are never saved.

**Comment by marefr** [comment]
Regression from #11822
