### ISSUE TITLE
Unable to save dashboard 

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#12241]
### What Grafana version are you using?
5.1.2

### What datasource are you using?
N/A ( Simple text panel / Random walk )

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
1 . Login as admin user --> Success
2.  Create dashboard without panels and save --> Success
3.  Add a text panel / random walk panel -> Success
4.  Save the dashboard --> FAIL

### What was the expected result?
Dashboard should be saved

### What happened instead?
Dashboard not saved

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

curl 'http://myip/api/dashboards/db/' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://myip/d/URZpB9Smk/sample?orgId=1' -H 'Origin: http://myip' -H 'X-Grafana-Org-Id: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"dashboard":{"annotations":{"list":[{"builtIn":1,"datasource":"-- Grafana --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations & Alerts","type":"dashboard"}]},"editable":true,"gnetId":null,"graphTooltip":0,"id":6,"links":[],"panels":[{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":null,"fill":1,"gridPos":{"h":9,"w":12,"x":0,"y":0},"id":2,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"nullPointMode":"null","percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{}],"thresholds":[],"timeFrom":null,"timeShift":null,"title":"Panel Title","tooltip":{"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}}],"schemaVersion":16,"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"now-6h","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"timezone":"","title":"Sample","uid":"URZpB9Smk","version":3},"overwrite":false,"message":"sample comment"}' --compressed
 
Chrome network screenshot
![image](https://user-images.githubusercontent.com/153843/41291933-eea7f550-6e48-11e8-8c9d-f1bef078a6bc.png)

IE network screenshot
![image](https://user-images.githubusercontent.com/153843/41291952-0121d106-6e49-11e8-8eab-187b31fe45d1.png)

Actual error in the console
![image](https://user-images.githubusercontent.com/153843/41292003-27cd8796-6e49-11e8-92fb-253ec7b1fb9b.png)

**Comment by yesoreyeram** [comment]
Grafana config

```
app_mode = production
instance_name = ${HOSTNAME}
[paths]
data = /opt/data/grafana/data
logs = /opt/data/log/grafana
plugins = /opt/data/grafana/plugins
[server]
http_port = 3000
[database]
type = mysql
host = 127.0.0.1:3306
name = grafana_prime
user = root
password = xxxxxxxxxxxxxxx
[session]
cookie_name = grafana_aio_sess_test
[dataproxy]
logging = false
[analytics]
reporting_enabled = false
check_for_updates = false
[security]
admin_user = grafanaadmin
admin_password = xxxxxxxxxxxxxxx
[snapshots]
external_enabled = false
[dashboards]
versions_to_keep = 50
[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = true
auto_assign_org_role = Viewer
verify_email_enabled = true
login_hint = Enter your email
[auth]
disable_login_form = false
disable_signout_menu = false
[auth.anonymous]
enabled = false
[auth.github]
enabled = false
[auth.google]
enabled = false
[auth.generic_oauth]
enabled = false
[auth.grafana_com]
enabled = false
[auth.proxy]
enabled = false
[auth.basic]
enabled = true
[auth.ldap]
enabled = true
config_file = /opt/grafana/conf/ldap.toml
allow_sign_up = true
[smtp]
enabled = true
host = XXXXX
user = XXXXX
password = XXXXX
skip_verify=true
from_address = grafana-alerts-test@mydomain.com
from_name = "Grafana Alerts - Test"
[emails]
welcome_email_on_sign_up = false
[log]
mode = console file
level = info
[log.console]
[log.file]
[log.syslog]
[alerting]
enabled = true
execute_alerts = true
[explore]
enabled = true
[metrics]
enabled           = true
interval_seconds  = 10
[metrics.graphite]
address = localhost:2003
prefix = monitoring.grafana.aio.test.%(instance_name)s.
[tracing.jaeger]
[grafana_com]
url = https://grafana.com
[external_image_storage]
[external_image_storage.s3]
[external_image_storage.webdav]
[external_image_storage.gcs]
[external_image_storage.azure_blob]
[external_image_storage.local]

```

**Comment by yesoreyeram** [comment]
@marefr

**Comment by marefr** [comment]
Please change your grafana config so that it's only includes any changes you've made compared to the defaults. It's recommended that you have grafana defaults untouched and your configurations in a separate file. 

How have you installed Grafana? How are you running grafana/started it?

**Comment by yesoreyeram** [comment]
Grafana installed via tar file . Running through supervisor.  Here is the supervisor config

```
[program:grafana]
command = /opt/grafana/bin/grafana-server --homepath=/opt/grafana/ --config=/opt/grafana/conf/grafana.ini &
stdout_logfile = /opt/data/log/supervisor/%(program_name)s.log
stderr_logfile = /opt/data/log/supervisor/%(program_name)s.log
username = _monitoring
password = _monitoring
autorestart = true
```

**Comment by yesoreyeram** [comment]
Running grafana directly from the bin folder also produced the same issue. ( Default configuration. SQLite DB, No Nginx, No supervisor ) :(

**Comment by marefr** [comment]
Are you browsing Grafana from your Ubuntu machine where you've installed Grafana or from another computer?

**Comment by yesoreyeram** [comment]
From a remote windows machine. Grafana is installed in ubuntu-server 16.04 in azure.

**Comment by marefr** [comment]
So there's your problem. I have no knowledge of azure or how you've setup your ubuntu server in azure and will have hard times helping you debug this. For sure you should be able to communicate with your Grafana in azure using `http://hostname:3000` if you're on a computer on the same sub net in azure and/or using a vpn connection.

**Comment by yesoreyeram** [comment]
Thanks @marefr for your help. Let me figure it out. 

BTW, if it is a connection issue, none of my requests should pass through. In my case, i am not able to create dashboard with panel. Dashboard without panels works fine.  Will update this thread once i found the root cause.

**Comment by marefr** [comment]
Good luck. I suspect there might be something related to your hostname/dns that kicks in only when using POST requests.

**Comment by luis13byte** [comment]
I've the same problem, the only temporary solution I have found is to edit the panels and copy the JSON model.

Then import the JSON as a new dashboard, so that every time I want to make changes I am deleting a dashboard (old version) and creating a new one (copy of the old one with changes).
