### ISSUE TITLE
Selecting the current dashboard from dashboard search does nothing... again?

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12248]
Strangely, I am seeing the behavior from  #10231 on one instance but it seems OK on another.

![close](https://user-images.githubusercontent.com/705951/41316702-53dcd28e-6e93-11e8-8b82-9cf9391eb30d.gif)

Note that when you click on the name of the current dashboard, it changes the URL, but does not close the search window.

The main difference in setup between my working vs not working is:

Working: windows build running directly on port 3000
Not working: Debian distribution running behind nginx proxy

**Comment by daniellee** [comment]
The routing is different with/without a subpath so this sounds like a bug.

**Comment by dehrax** [comment]
The code fails here
https://github.com/grafana/grafana/blob/1726f6358fa6564592ba655b2340087ad9a8a53b/public/app/core/components/search/search_results.ts#L66
With a proxy `item.url` is `grafana/d/XokmxjSik/runtime-counter`, while `$location.path()` returns `/d/XokmxjSik/runtime-counter`, hence always returning -1.

I am trying to find where the item urls are generated.
