### ISSUE TITLE
bug: IP segments are fused into a floating-point number

### ISSUE THREAD

**Issue by Kuermel** [grafana/grafana#1224]
Grafana: 1.9.0
Backend: Graphite

You can select individual segments of an IP address. 
![1](https://cloud.githubusercontent.com/assets/6574969/5414528/fa4bd958-821f-11e4-8a35-6ff5e2b5f0e2.png)

After updating the website numbers are merged into a floating point number. 
![2](https://cloud.githubusercontent.com/assets/6574969/5414529/fa4bca4e-821f-11e4-9aa9-083f4c7df5af.png)

When you add a function, there is the following error message:
"Expected closing parenthesis instead found . at position: 25"
![3](https://cloud.githubusercontent.com/assets/6574969/5414527/fa48c326-821f-11e4-8f27-0c4f601cf1b6.png)

**Comment by Kuermel** [comment]
Grafana: 1.9.1
Backend: Graphite

Thanks for the fix with the floating point numbers. This works in version 1.9.1.

But as soon as I add a function, the error appears again in the editor. But the function is executed.
![4](https://cloud.githubusercontent.com/assets/6574969/5611304/5df5edd8-94c5-11e4-9db4-1ae93f8d9f93.png)

**Comment by torkelo** [comment]
@Kuermel strange, seems to work for me.

![image](https://cloud.githubusercontent.com/assets/10999/5611578/a5b32b38-94c8-11e4-9fe9-d8d564c23aa9.png)

Will try having it as first metric segment.

**Comment by torkelo** [comment]
Yes, added a new unit test for an expression alias(2.4.5.6, 'test') and it gives the same error you got, will try to fix.

**Comment by torkelo** [comment]
@Kuermel I am not sure I want to fix this. It requires some complex changes to the lexer and parser. The easy workaround is to not have metric paths begin with a number.
