### ISSUE TITLE
Panels datasource variable is not overwritten when importing dashboard with collapsed rows

### ISSUE THREAD

**Issue by kjetilmjos** [grafana/grafana#12256]
### What Grafana version are you using?
5.1.3

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Official docker image

### What did you do?
Exported a dashboard with panels in a row which is collapsed. The datasource variable in the panels which are under a collapsed row does not chang after importing the dashboard again.

### What was the expected result?
Datasource variable should be changed on all panels in a dashboard regardless of them being in a collapsed row or not.

### What happened instead?
Only datasource variables in panels without in a row are overwritten.

**Comment by marefr** [comment]
Thanks for reporting. Confirmed bug. When exporting a dashboard with collapsed row, the datasource in panel part of collapsed row does not get extracted correctly.
