### ISSUE TITLE
Unable to forward cookies with proxied datasource

### ISSUE THREAD

**Issue by edmondkong** [grafana/grafana#12261]
I'm using a custom Elasticsearch service as the datasource for my Grafana dashboard. An authentication cookie is required to access it, which I want to pass via the Cookie header. 

In my datasource configuration, I've selected the "proxy" access setting which means that all database requests are proxied through the Grafana service. I've enabled the "with credentials" setting in order for this to occur. However I can tell (by Wireshark) that my custom service is not receiving the cookie.

This is the output of the network tab in Chrome:
![image](https://user-images.githubusercontent.com/9369658/41356014-b99d5b0c-6f1a-11e8-9b31-b904103eb9db.png)

I can see that the cookie is being sent to Grafana, so it appears that Grafana is not sending it along with the database requests like it should be.

**Comment by daniellee** [comment]
Did you try the Whitelisted Cookies setting? Grafana deletes forwarded cookies in the proxy but you can whitelist them by name using this setting. 

![image](https://user-images.githubusercontent.com/434655/41364175-33ae8cc0-6f36-11e8-80be-6952295077ed.png)

**Comment by edmondkong** [comment]
Ah yes, I was using v4.5.2 of Grafana initially which does not have this functionality. But the above works for me, thank you.

**Comment by Novitoll** [comment]
@edmondkong, could you please tell what cookies  you whitelisted to access Prometheus? Sorry for the 2 year old question :)
