### ISSUE TITLE
Exporting dashboard metadata through the UI

### ISSUE THREAD

**Issue by bljordan** [grafana/grafana#12266]
### What Grafana version are you using?
5.0.4

### What datasource are you using?
Prometheus, Cloudwatch, Graphite

### What OS are you running grafana on?
CoreOS

### What did you do?
We are using the terraform provider for grafana (https://github.com/terraform-providers/terraform-provider-grafana).

It expects to be passed json blobs that only contain the dashboard object, but not the meta object.  Additionally, the dashboard config -> view json only gives you the dashboard part, not the meta part.  The API provides the whole object.
`
{
  "meta": {
    "type": "db",
    "canSave": true,
    "canEdit": true,
    "canAdmin": false,
    "canStar": true,
    "slug": "dashboard-name",
    "url": "/d/XckjVRNik/dashboard-name",
    "expires": "0001-01-01T00:00:00Z",
    "created": "2018-06-13T20:50:54Z",
    "updated": "2018-06-13T21:19:15Z",
    "updatedBy": "bljordan",
    "createdBy": "Anonymous",
    "version": 2,
    "hasAcl": false,
    "isFolder": false,
    "folderId": 82,
    "folderTitle": "dashboard-name",
    "folderUrl": "/dashboards/f/kdhl-0Sik/dashboard-name"
  },
  "dashboard": {
    "annotations": {
      "list": [
        {
<snip>
`

### What was the expected result?
The request: It'd be nice if we could get the entire object including metadata out of the UI.

### What happened instead?
Only the dashboard is provided through the UI.

### References
https://github.com/terraform-providers/terraform-provider-grafana/issues/23

**Comment by marefr** [comment]
Use the api instead. If you use chrome dev tools network tab you can also see the full payload in UI when loading a dashboard.
