### ISSUE TITLE
Error Entrypoint: /setup.sh -> permission denied 

### ISSUE THREAD

**Issue by chip9965** [grafana/grafana#12264]
Hi

I'm pretty new to docker and the installations with containers. I've made my own docker-compose.yml file for grafana:
------------------ begin yml file ------------------------
version: '3'

networks:
  monitor-net:
    driver: bridge

volumes:
    grafana_data: {}

services:

 grafana:
   image: grafana/grafana:latest
   container_name: grafana
   volumes:
     - grafana_data:/var/lib/grafana
     - ./grafana/datasources:/etc/grafana/datasources
     - ./grafana/dashboards:/etc/grafana/dashboards
     - ./grafana/setup.sh:/setup.sh
   entrypoint: ./setup.sh
   environment:
     - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
     - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
     - GF_USERS_ALLOW_SIGN_UP=false
   restart: unless-stopped
   expose:
     - 3000
   ports:
     - 3000:3000
------------------------ end of yml file -----------------
when I ran the command docker-compose up
------ Output -----------------------
Recreating grafana ...
Recreating grafana ... error

ERROR: for grafana  Cannot start service grafana: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./setup.sh\": permission denied": unknown

ERROR: for grafana  Cannot start service grafana: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./setup.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
-----------------------------------

I've tested this with old grafana-versions also -> same error.

Any help would be preciated!
kind regards

**Comment by marefr** [comment]
Seems like your custom entrypoint setup.sh is the cause and by that nothing to do with grafana docker container. Not sure what you're trying to accomplish with a custom entrypoint, but would recommend to read the [documentation](http://docs.grafana.org/installation/docker/#building-a-custom-grafana-image-with-pre-installed-plugins).

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
