### ISSUE TITLE
Feature request. Playlist schedule

### ISSUE THREAD

**Issue by genuss** [grafana/grafana#12279]
### What Grafana version are you using?
v5.1.3
(deleted other questions as they are not relevant)

I looked in many places but didn't find anything similar already implemented and feature-requests like this. So here is my idea.
At our job we strongly depend on time schedule of external systems: in different time slots there are different metrics to monitor. So we build for instance four dashboards: morning, day, evening and night ones. What we would like is to show these dashboards on our shared monitor with a help of playlists, but playlist currently allow only fixed interval.
How I see it. When you create a playlist you add dashboards there and add a scheduled like this:
````
night     -> 00:00 - 07:00
morning   -> 07:00 - 10:00
day       -> 10:00 - 18:00
evening   -> 18:00 - 22:00
night     -> 22:00 - 00:00
````

Dear maintainers, what do you thing about this idea? Is it interesting to implement and maybe it's already can be achieved somehow?

**Comment by genuss** [comment]
I forgot to tell you how a managed to get a workaround.
Well this is made simply by cron like this:
````
DISPLAY=":0"

0  8  * * * killall chromium-browser && chromium-browser --kiosk "https://grafana/some-dashborard1?kiosk" >/dev/null 2>/dev/null &
30 9  * * * killall chromium-browser && chromium-browser --kiosk "https://grafana/some-dashborard2?kiosk" >/dev/null 2>/dev/null &
0  19 * * * killall chromium-browser && chromium-browser --kiosk "https://grafana/some-dashborard3?kiosk" >/dev/null 2>/dev/null &
````

Works ok, sometimes doesn't work but it's acceptable solution.

**Comment by thestraycat** [comment]
Could this be reopened? Scheduling would be super handy... relying on cronjobs is a good workaround but not a replacement for powerful scheduling in grafana's UI? It could also be handy to be able to nest schedules for example:

Playlist1   -- (Period) Daytime --  9.00am - 5.30pm --   Dashboard 1
                -- (Period) Night Time --  5.31pm - 11.59pm --   Dashboard 2 

This would then allow you to call Playlist1 and the scheduling will take care of the rotations for the desired time windows?
