### ISSUE TITLE
Sorting data in "Table panel for grafana"

### ISSUE THREAD

**Issue by sorrow719** [grafana/grafana#12277]
Hello.
I seen this request: [#10541](https://github.com/grafana/grafana/issues/10541) and same another, i want presorted table by multiplied values in grafana table plugin, any ideas how i can do this at this moment? (Without influx/another db)

env: grafana 5.1 +  prometheus 2.2

**Comment by torkelo** [comment]
not at the moment, you will have to do it in the query. 

Please ask questions on the community site https://community.grafana.com
