### ISSUE TITLE
After adding variable in URL of Render values as link,  Can i use that variable in mysql query of another dashboard's table pannel

### ISSUE THREAD

**Issue by SK5277-SINGH** [grafana/grafana#12270]
_Grafana Version: 5.1.3
Data Source: MySql
OS: Win 10 64 bit_

**You can see in below screenshoot,**
> I added reder value as link on TOKEN ID with URL which is highlighted by yellow color.
> When i clicked on any ToKEN ID it redirect to another deshborad with cell value on which i cliked

![add link](https://user-images.githubusercontent.com/32188436/41395299-121624cc-6f38-11e8-942e-99725bd7bc6a.PNG)

**Now you can see below screenshot,**
> After cliked I got TOKEN ID variable in URL which is rounde by red color 
## Can I use it??

![where condition](https://user-images.githubusercontent.com/32188436/41395331-3d116556-6f38-11e8-8666-348f0bb7b94e.PNG)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

If you create a variable in your dashboard having name=*tokenid* you can refer to it in your query like *${tokenid}.

**Comment by SK5277-SINGH** [comment]
sorry
