### ISSUE TITLE
Network Error: Bad Gateway(502) when Add influx datasource 

### ISSUE THREAD

**Issue by xdk-rachel** [grafana/grafana#12272]
I am using docker and try to connect grafana and influxDB.

When I add datasource which type is influxDB, if I using URL: http://localhost:8086 there will be an error: Bad Gateway(502). But if I use http://172.18.0.56:8086 which if my local IP, it can work.
I don't want to write IP every time because it will be applied to another computer and IP will change.
Do anyone know why? Thank you very much.

Kind Regards
Rachel

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Configure your influxdb container to use the host network in this case.
