### ISSUE TITLE
Datasource interval field not beeing applied if I want No Pattern.

### ISSUE THREAD

**Issue by wireless00** [grafana/grafana#12281]
### What Grafana version are you using?
v5.1.3 build (087143285)

### What datasource are you using?
ElasticSearch
### What OS are you running grafana on?
In a OpenShift Container --> base image <-- CentOS Linux release 7.5.1804 (Core)
### What did you do?
Addind DataSource --> elasticsearch.yml datasources. See snipp.

snipp :
`        - name: Elastic-sdwan-applicationdpi
          type: elasticsearch
          access: proxy
          # <bool> enable/disable basic auth
          basicAuth: true
          basicAuthUser: user
          basicAuthPassword: pass
          # <bool> mark as default datasource. Max one per org
          isDefault: true
          # <bool> allow users to edit datasources from the UI.
          editable: true
          database: "sdwan-*-applicationdpi-*"
          url: http://es-vip.elastic:9200
          jsonData:
            interval: "No pattern"
            timeField: "lastUpdatedDate" `

### What was the expected result?
In the GUI, in the DataSources section for the DS name Elastic-sdwan-applicationdpi, In the ''Pattern'' field, I should see "No Pattern".   If I change the value in the config file to Hourly, it work's.
### What happened instead?
The Pattern field is empty

**Comment by marefr** [comment]
Does it work if you put `null` or `~` instead of "No pattern"?

**Comment by wireless00** [comment]
I did try both, neither work. I even left the interval value empty and I have the same issue. 
The other thing is that "No pattern'' IS a value... I really don't get that one...



![eldetails](https://user-images.githubusercontent.com/29203230/41419026-0a4e9bca-6fbf-11e8-8b13-fa8fbd71eec5.png)

**Comment by wireless00** [comment]
Update, null value does not show a selection of ''No pattern'' in the GUI. However, it seem that when I test my DataSource connection, it now work's. In opposite of ''if I put "No pattern" as a value to interval.

It's still a bug. Not sure if only a GUI bug or not. It need more investigation.

![screen shot 2018-06-14 at 11 18 05 am](https://user-images.githubusercontent.com/29203230/41421368-ab1339a8-6fc4-11e8-9cbd-80d149b5ef33.png)

**Comment by marefr** [comment]
Yeah probably a UI bug

**Comment by wireless00** [comment]
Meanwhile (in the interval) , can I suggest that this doc is updated with a list of possible value for the interval field ? So it's clear that null = No pattern ?

Regards,
