### ISSUE TITLE
Grafana with aws elasticsearch data source not working in phantomjs

### ISSUE THREAD

**Issue by Guruhbk** [grafana/grafana#12285]
Please include this information:
### What happened instead? The pdf rendered with the error. 

I'm using grafana 5.1.3. My data source is aws elasticsearch. I'm using API request and creating a snapshot URL. When I render that URL in phantomjs it shows me an error page. Same URL if I load in chrome/Mozilla browser it works fine. Also if I have any local elasticsearch data source, phantom rendering works fine. I don't know why the issue occurs only with aws elasticsearch. Meanwhile, I checked in puppeteer too. Still the same issue. I'm very sure this is not an authentication issue. It is something to do with AWS Elasticsearch in specific. Any suggestions?
[123_14-06-2018_20-01-00.pdf](https://github.com/grafana/grafana/files/2103278/123_14-06-2018_20-01-00.pdf)

**Comment by torkelo** [comment]
Backend image rendering only works if your datasource is accessible from the backend (access mode Server)
