### ISSUE TITLE
Teamspeak User online alert error tsdb.HandleRequest() error Missing query definition for mode

### ISSUE THREAD

**Issue by CWollinger** [grafana/grafana#12286]
Version:  v4.6.3
Datasource: teamspeak
OS: docker (linux)
Hello,

I want to create an altering rule to teamspeak.clients_online:

Log:
`t=2018-06-14T17:40:40+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalHandler ruleId=3 name="User Online alert" error="tsdb.HandleRequest() error Missing query definition for mode" changing state to=alerting
`

Metrics from telegraf:
`SELECT mode("clients_online") FROM "teamspeak" WHERE $timeFilter GROUP BY time(5m), "name" fill(null)`

Conditions:
`WHEN avg () OF query (A, 5m, now) IS ABOVE 30`

Any hints? Or solutions?

Thanks

**Comment by bergquist** [comment]
Seems like the backend lack support for `mode()`.

Should be added to https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query_part.go
