### ISSUE TITLE
[Feature Request] enable/disable annotation editor

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12289]
The annotation editor is great for annotations saved in the grafana DB, but is is weird/broken for annotations that come from somewhere else.

With my datasource, I see the editor -- can edit the annotation, and when I save it it says:
![image](https://user-images.githubusercontent.com/705951/41439691-0fcf5f04-702c-11e8-8d29-b5031b696c46.png)

It would be better to just hide the edit button.

**Comment by torkelo** [comment]
Strange, it should only show on annotations with an id

**Comment by ryantxu** [comment]
Ah -- I put the event id on the annotation!  I'll remove it.

**Comment by marefr** [comment]
Closing this as it seems to not be an issue. Consider reopen if that was not the case
