### ISSUE TITLE
Alert not work 

### ISSUE THREAD

**Issue by ricoisme** [grafana/grafana#12292]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.1.3
### What datasource are you using?
MS SQL Server
### What OS are you running grafana on?
CentOS7
### What did you do?
Alert

### What was the expected result?
notification by email

### What happened instead?
Invalid alert data. Cannot save dashboard

### If related to metric query / data viz:
SELECT 
 getdate() as time
,[name]
, COUNT(l.database_id) AS 'vlf_count' 
FROM sys.databases s
CROSS APPLY sys.dm_db_log_info(s.database_id) l
where s.database_id not in (1,3,4)
GROUP BY [name]

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
angular.js:14794 Possibly unhandled rejection: {"message":"Invalid alert data. Cannot save dashboard","severity":"error"}

**Comment by bergquist** [comment]
Can you please show a screenshot from your alert tab?

Have you configured a threshold?

**Comment by ricoisme** [comment]
sorry for late replay.
The screenshot as below
![2018-06-19_132017](https://user-images.githubusercontent.com/17023972/41578206-af7750d0-73c3-11e8-9f80-68d1ba708363.png)
![2018-06-19_132042](https://user-images.githubusercontent.com/17023972/41578214-b5b64b90-73c3-11e8-8f69-347ccbb8a0eb.png)

**Comment by torkelo** [comment]
Can you include output from grafana server log from the time you clicked Test Rule?

**Comment by ricoisme** [comment]
Our data source from variables .
![image](https://user-images.githubusercontent.com/17023972/41706439-72826dac-756e-11e8-9b41-9620448bf664.png)

error log as below
![image](https://user-images.githubusercontent.com/17023972/41706575-b7aa64ac-756e-11e8-8e30-3b850b0a9970.png)

**Comment by torkelo** [comment]
Alerting does not support template variables , closing this. There is an open feature request for this

**Comment by mawek** [comment]
@torkelo - where? Can you link it please ?

**Comment by marefr** [comment]
@mawek #6557
