### ISSUE TITLE
Dynamic dashboards

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#1229]
Hi,
is there a way to re-create a dashboard dynamically when e.g. a different template variable is selected? The use-case is that I want to use scripted dashboards that show different graphs depending on the host that is selected (for example a graph per cpu core but each host has a different number of cpu cores).
What I'm looking for is some kind of hook or callback that I can use that gets triggered when a new template variable is select or when the dashboard is re-rendered to re-generate the dashboard description on the fly to add or remove rows and/or graphs depending to the selected host.
Is this possible somehow?

**Comment by nopzor1200** [comment]
We're currently testing a feature discussed in #1888 that I think will meet your use case for how you describe "dynamic dashboards". 

Feel free to give us your feedback there; thanks!

**Comment by dennisjac** [comment]
Unfortunately that doesn't really cover my use-case. Perhaps I can provide a specific example of what I'm trying to accomplish.
I basically want to be able to create a dashboard that displays rows and panels based on the metrics available in the database i.e. the scripted dashboard looks if it finds a metric "<host>.load.shortterm" in influxdb and if it does it will add a cpu-load panel to the dashboard. This works fine right now as long as I don't use template variables.
The moment template variables enter the picture the issue is that the dashboard function does not get called again to re-generate the dashboard with the newly selected template variables. For example I want to add a template variable $host and if a new host is selected rebuild the dashboard as explained above.
I don't even think that this would require hooks but just an option for the dashboard like "re-render the dashboard when a new template variable is selected" (for asnyc scripted dashboards this would imply calling the function that return the dashboard object again).

With that option the dashboard could be completely rebuilt from scratch when a variable is changed which I think would make scripted dashboards much more powerfull.

**Comment by toni-moreno** [comment]
@dennisjac  I think you are better refering to this other Feature Request https://github.com/grafana/grafana/issues/1761

**Comment by mtanda** [comment]
+1

**Comment by anryko** [comment]
Hi dennisjac,
I had same requirements for my infrastructure operations. You could checkout my solution for the problem and reuse it or reimplement/adapt for your needs: https://github.com/anryko/grafana-influx-dashboard

**Comment by zhangyongxing89** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
