### ISSUE TITLE
grafana.ini and defaults.ini not working

### ISSUE THREAD

**Issue by aratz-lasa** [grafana/grafana#12296]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
latest version on Docker
### What datasource are you using?
influxdb
### What OS are you running grafana on?
ubuntu
### What did you do?
I set SMTP configuration in grafana.ini, and later, as it didn't work, in defaults.ini too. And yes, I restarted grafana. And I removed ";" from config.
### What was the expected result?
To see the changes in admin--> server settings, or to be able to send emails as notifications
### What happened instead?
It didn't change its configuration
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
**_grafana.ini and defaults.ini SMTP config:_**
#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = smtp.gmail.com:465
user = email@gmail.com
password = pass
cert_file =
key_file =
skip_verify = true
from_address = email@gmail.com

[emails]
welcome_email_on_sign_up = false

**_Docker log:_**
t=2018-06-15T09:42:05+0000 lvl=info msg="Starting Grafana" logger=main version=4.3.2 commit=ed4d170 compiled=2017-05-31T08:48:16+0000
t=2018-06-15T09:42:05+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-06-15T09:42:05+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-06-15T09:42:05+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-06-15T09:42:05+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-06-15T09:42:05+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-06-15T09:42:05+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.log.mode=console"
t=2018-06-15T09:42:05+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-06-15T09:42:05+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-06-15T09:42:05+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-06-15T09:42:05+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-06-15T09:42:05+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-06-15T09:42:05+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-06-15T09:42:05+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-06-15T09:42:05+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-06-15T09:42:05+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-06-15T09:42:05+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-06-15T09:42:05+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2018-06-15T09:42:05+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-06-15T09:42:05+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-06-15T09:42:05+0000 lvl=info msg="Initializing Stream Manager"
t=2018-06-15T09:42:05+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2018-06-15T09:42:21+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2018-06-15T09:42:21+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[asdasd]
t=2018-06-15T09:42:21+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="SMTP not configured, check your grafana.ini config file's [smtp] section."
t=2018-06-15T09:42:21+0000 lvl=eror msg="SMTP not configured, check your grafana.ini config file's [smtp] section." logger=context userId=1 orgId=1 uname=admin error="SMTP not configured, check your grafana.ini config file's [smtp] section."
t=2018-06-15T09:42:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=412 remote_addr=192.168.56.1 time_ms=17 size=87

**Comment by marefr** [comment]
t=2018-06-15T09:42:05+0000 lvl=info msg="Starting Grafana" logger=main version=**4.3.2** commit=ed4d170 compiled=2017-05-31T08:48:16+0000

Please do a docker pull grafana/grafana:latest

**Comment by aratz-lasa** [comment]
I did it, but it still does not work.

**Comment by marefr** [comment]
Okay, Could you please open a ticket in Grafana's [docker repository](https://github.com/grafana/grafana-docker). If you have any new logs since doing the `docker pull grafana/grafana:latest`, please include those in the new issue. Thanks
