### ISSUE TITLE
[Feature Request] Missing Cloudwatch Lambda Metrics (ConcurrentExecutions)

### ISSUE THREAD

**Issue by balda** [grafana/grafana#12309]
### What Grafana version are you using?
Grafana v5.1.3 (087143285) 

### What datasource are you using?
Cloudwatch

### What OS are you running grafana on?
Ubuntu

### What did you do?
Graph AWS Lambda metrics

### What was the expected result? What happened instead?
Missing Lambda `ConcurrentExecutions` and `UnreservedConcurrentExecutions` metrics

**Comment by mtanda** [comment]
Added in https://github.com/grafana/grafana/pull/16102 .
