### ISSUE TITLE
Commad to delete a particular series from influxdb

### ISSUE THREAD

**Issue by anilkumar-sannamuri** [grafana/grafana#12319]
- What is the command to delete a particular series[i.e., for example out of 10 servers I need to delete one particular server] from influxdb?
- Influxdb version which we are using is "1.5.2".
- Following are the commands which we followed to delete a particular series
    DROP SERIES FROM metric_name WHERE host=hostname

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by anilkumar-sannamuri** [comment]
@torkelo 
A few weeks back I have asked the same question in community channel, but I didn't get any reply to my question. So I created the ticket on GitHub. Sorry for the inconvenience. Can you please help us.

**Comment by torkelo** [comment]
checked influxdb docs? does not mention this?

**Comment by anilkumar-sannamuri** [comment]
@torkelo 
- Yes I went through the influxdb documentation [link](https://docs.influxdata.com/influxdb/v1.5/query_language/database_management/#drop-series-from-the-index-with-drop-series).
- But this did not help.

**Comment by anilkumar-sannamuri** [comment]
@torkelo 
- Can you please help us.
