### ISSUE TITLE
Alert panel rendering issue

### ISSUE THREAD

**Issue by Knaky41** [grafana/grafana#12318]
Please include this information:
### What Grafana version are you using?
5.1.3 
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
Windows
### What did you do?
Try to render the alerting list
### What was the expected result?
Show all the alerts
### What happened instead?
Show only the first one
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Hi,

I just tested the alerting feature for Elastic and it seems working.

However, when I try to render the table via the API, the alert list table show only the first alert and not the other (Either active, no data...).

Thanks for your help.

**Comment by marefr** [comment]
Then you must be on version 5.2.0-beta1 and not 5.1.3 - correct? 

I've just tested the alert list panel and it seems to work for me. Please include the panel json of your alert list panel for further possibility for us to investigate this.

**Comment by marefr** [comment]
So is there still a problem?

**Comment by Knaky41** [comment]
Yes :

I've added the table panel to display all the current alerts of the system.

When I call the API to render the panel, the panel only shows the first alert of the panel (No matter if active, no data or inactive).

Is there any configuration or setting to add to correct this behaviour ?

**Comment by marefr** [comment]
I'm confused now. Are you trying to get alerts from the http api or render them in the alert list panel? Please include more detailed information, as requested earlier your alert list panel json or your http request if you're using the api.

**Comment by marefr** [comment]
If you're trying to render alert annotations in a table, please refer to [documentation](http://docs.grafana.org/features/panels/table_panel/#annotations).

**Comment by Knaky41** [comment]
I'm trying to render the panel using the HTTP API. All the tables are working fine, I'm able to download a picture of the whole table.

I'm just having a problem with the alert tables which displays only the first row when I'm using the rendering API.

Cheers.

**Comment by marefr** [comment]
Please include exactly the HTTP request you're using for us to be able to help you further.

**Comment by Knaky41** [comment]
I'm connecting to dashboard at http://localhost:8080/api/dashboards/uid/99mHqKNmz

And then i'm calling to download the pictures : 

http://localhost:8080/render/d-solo/99mHqKNmz/_?from=1520845206000&height=500&panelId=67&theme=light&to=1520874006000&width=1000

does it help you ?

**Comment by marefr** [comment]
Okay and what is the result? Can you include a screenshot? You're writing above that "I'm able to download a picture of the whole table". Does adding `&height=1000` or higher value help you?

**Comment by Knaky41** [comment]
So I'm trying to export this alarms table:
![image](https://user-images.githubusercontent.com/38044984/41605519-deefb4ce-73e1-11e8-8854-9f46dfdbde70.png)


And i've got this extracted list (Even with height=1000):

![image](https://user-images.githubusercontent.com/38044984/41605553-f30a1328-73e1-11e8-9d27-c391b44bbaeb.png)

**Comment by marefr** [comment]
Thanks. Now its very clear. Confirmed bug

**Comment by torkelo** [comment]
looks fixed in master (v6)
