### ISSUE TITLE
Delete nonexistent datasource cause 500 internal server error

### ISSUE THREAD

**Issue by wangzw** [grafana/grafana#12313]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?

5.1.3 docker image

### What datasource are you using?

Postgres

### What OS are you running grafana on?

Docker container on MacOS

### What did you do?

Delete a deleted/nonexistent datasource using Restful API.

### What was the expected result?

Response 404 - Not found

### What happened instead?

Response 500 - Internal Server Error

### If related to metric query / data viz:

No

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

No
<img width="957" alt="screen shot 2018-06-18 at 09 04 00" src="https://user-images.githubusercontent.com/1254826/41514082-a84ea7ec-72d6-11e8-89b9-33474293a377.png">

**Comment by bergquist** [comment]
Closed by #12387
