### ISSUE TITLE
Dashboard link doesn't work when "As dropdown" option is checked

### ISSUE THREAD

**Issue by lukesilvia** [grafana/grafana#12315]
### What Grafana version are you using?

v5.2.0-beta1 (commit: faa5e69)

### What OS are you running grafana on?

Amazon Linux AMI 2017.09.1.20180307 x86_64 HVM GP2

### What did you do?

I create dashboard link as dropdown. And I click it.

![dashboardlink](https://user-images.githubusercontent.com/42880/41519967-34b76ec4-7306-11e8-8b2d-009103cea280.gif)

### What was the expected result?

When I click the dashboard link, I expect related dashboards are listed in dropdown menu.

### What happened instead?

Navigate to root url.

If as dropdown option is not checked, it seems that dashboard link works well.

**Comment by mjf** [comment]
Pretty similar here but with slightly different configuration. No dropdown menu, just get navigated to the root URL (v5.2.0-beta1).

![non-working](https://user-images.githubusercontent.com/54104/41527957-fc633304-72e8-11e8-8e16-f9af0e780a38.png)

**Comment by marefr** [comment]
Thanks for reporting. Confirmed bug

**Comment by lukesilvia** [comment]
Thank you for checking.
