### ISSUE TITLE
How often is the doc regenerated ? 

### ISSUE THREAD

**Issue by vincent-fuchs** [grafana/grafana#12329]
Hi,

My commit got merged 3 days back (https://github.com/grafana/grafana/commit/c8becf57faca2e5206a6a60c85d56699a18ae6be), but the change still doesn't reflect on http://docs.grafana.org/administration/provisioning/  : it still shows _delete_datasources_

Is it normal ? is anything broken ?

-- 
Vincent

**Comment by torkelo** [comment]
We don't have an automated deploy for docs changes (we should do this), so we only update it when doing bigger changes or releases.  can push out an update now, should be live in about 20min

**Comment by vincent-fuchs** [comment]
ok, thanks for your response. Indeed, I believed the doc generation was automated ;-)
