### ISSUE TITLE
Alert issue for graph panel

### ISSUE THREAD

**Issue by anilkumar-sannamuri** [grafana/grafana#12320]
- We are using ```graph panel``` to generate the alert mail. But this panel is working only when the particular server exceeds the threshold value only.
- Is there a way to get the alert mail when a server goes to the bad state?
- And is there a way to get the alert mail when a server doesn't get any logs?

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by anilkumar-sannamuri** [comment]
- A few weeks back I have asked the same question in community channel, but I didn't get any reply to my question. So I created the ticket on GitHub. Sorry for the inconvenience. Can you please help us.

**Comment by anilkumar-sannamuri** [comment]
- following is the alert condition for graph panel of which we used. Can you please help us. Thanks!
- ![query](https://user-images.githubusercontent.com/28001233/41593245-0d585f78-73dd-11e8-9758-b6f1bb986d44.png)
- ![image](https://user-images.githubusercontent.com/28001233/41593168-c51faee6-73dc-11e8-9ec0-e3a6b64be5f7.png)
