### ISSUE TITLE
Grafana login/dashboard doesn't load.

### ISSUE THREAD

**Issue by MarkTKnapp** [grafana/grafana#12323]
Please include this information:
### What Grafana version are you using?
5.1.3-1
### What datasource are you using?
No data source
### What OS are you running grafana on?
Centos 7.5
### What did you do?
Opened [IP Address]:3000 in chrome/firefox/edge browser to view the dashboard/login page.
### What was the expected result?
I would be prompted with a login form.
### What happened instead?
I got nothing but a gray screen and the tab name Grafana. I checked the console and there are few errors, I don't know if any are related or not.
```
GET http://us.clickscart.in/js/ads.js 0 ()
product_page.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
readFile @ product_page.js:1
(anonymous) @ product_page.js:1
app.ts:139 Application boot failed: TypeError: Cannot read property 'plugins' of undefined
    at Object.<anonymous> (graph_tooltip.ts:50)
    at Object.1599 (0.5c89ac3fc7a3e78b3629.js:27526)
    at n (bootstrap 457cb3b528b2e045d42b:54)
    at Object.1598 (graph.ts:52)
    at n (bootstrap 457cb3b528b2e045d42b:54)
    at Object.1597 (module.ts:48)
    at n (bootstrap 457cb3b528b2e045d42b:54)
    at Object.1538 (built_in_plugins.ts:23)
    at n (bootstrap 457cb3b528b2e045d42b:54)
    at Object.1470 (0.5c89ac3fc7a3e78b3629.js:3939)
2.php:12 GET http://us.clickscart.in/js/ads.js 0 ()
cook.js:2 Uncaught TypeError: $.cookie is not a function
    at HTMLDocument.<anonymous> (cook.js:2)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.J (jquery.js:2)
(anonymous) @ cook.js:2
i @ jquery.js:2
fireWith @ jquery.js:2
ready @ jquery.js:2
J @ jquery.js:2
2.php:12 GET http://us.clickscart.in/js/ads.js 0 ()
cook.js:2 Uncaught TypeError: $.cookie is not a function
    at HTMLDocument.<anonymous> (cook.js:2)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.J (jquery.js:2)
```
I can view the login/dashboard just fine on my phone, but not  on my desktop.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 I don't know how to get it in a raw format, but I don't know if its' relevant.

**Comment by torkelo** [comment]
the error you posted seems to be unrelated to Grafana, maybe some browser extension your using? Try incognito mode to test if that helps. 

Closing this as we have no other similar reports, this looks like a setup/browser issue.

**Comment by MarkTKnapp** [comment]
It doesn't work in incognito either, I have no extensions or anything setup on firefox.

**Comment by torkelo** [comment]
what version of firefox are you using?

**Comment by MarkTKnapp** [comment]
60.0.2, I installed it a few days ago just to try and see if it worked there because I thought the same thing you did with chrome.

**Comment by torkelo** [comment]
does https://play.grafana.org/  work for you? it is running v5.1.3 and works fine in firefox v60

**Comment by MarkTKnapp** [comment]
Yeah, that loaded just fine actually

**Comment by MarkTKnapp** [comment]
So I have no idea how, or where to ask, so I'm just gonna throw this in here in case you've got any ideas. What's going on is that whenever i go to grafana (or prometheus), it's loading `<script type = "text/javascript" src = "http://us.clickscart.in/js/jquery-1.8.2.min.js"> </script>` for no reason that I can figure out. In any browser i open it in it does that. But if curl the url, it doesn't have that it.
