### ISSUE TITLE
Add WeChat Notifier

### ISSUE THREAD

**Issue by robbinfan** [grafana/grafana#12333]
Add a new notifier : WeChat
WeChat is popular in China, you can get more info here: https://www.wechat.com/en/

We need Grafana send alert to WeChat.

**Comment by bergquist** [comment]
Hi @robbinfan  thank you for taking the time to contribute to Grafana! But we are currently not merging new alert notifiers unless they have proven very popular. We already have more notifiers than we can maintain. So this has to wait until we support alert notifiers as backend plugins. In the meantime, I suggest you write a custom web server that integrates Grafanas alert notification webhooks with Wechat.

**Comment by bergquist** [comment]
Closing the wrong issue.. was suppose to close the issue.

**Comment by 47181770** [comment]
It's a good idea to support webchat in grafana alert notification

**Comment by yakexi07** [comment]
please support wechat in grafana alert notification，in china, so many people use wechat every day

**Comment by maracuja-juice** [comment]
Can't you use a normal Webhook for this already?

**Comment by robbinfan** [comment]
Webhook can‘t fully use WeChat’s feature @maracuja-juice

**Comment by jony4** [comment]
> Webhook can‘t fully use WeChat’s feature @maracuja-juice

考虑使用企业微信

**Comment by wxq851685279** [comment]
Is it still not supported in 2021?

**Comment by bytepoem** [comment]
Is it still not supported in 2022?
