### ISSUE TITLE
“now-5m“ in query (A, 10m, now-5m) does not work

### ISSUE THREAD

**Issue by liujin1993** [grafana/grafana#12335]
“now-*m“ in query (A, 10m, now-5m) does not work. As the follow picture,the value of last() should be 10K about.But in fact it is always the value of now rather than now-5m. It has the same problem with other function like avg(),min(),etc.
	
![image](https://user-images.githubusercontent.com/31949674/41580782-a6d5f200-73ce-11e8-8854-a9de42b32062.png)
![image](https://user-images.githubusercontent.com/31949674/41580857-02353282-73cf-11e8-9d35-a7467f692e37.png)

I use the latest version grafana, and the datasource is elasticsearch 5.6.

**Comment by torkelo** [comment]
Can you show your query and your data source type? 

Must be something in your query that makes it time range sensitive (returns different values based on time range)

**Comment by liujin1993** [comment]
@torkelo  The datasource is elasticsearch 5.6.
![image](https://user-images.githubusercontent.com/31949674/41581111-0186a266-73d0-11e8-9cfc-53ca74a5a8a5.png)

**Comment by marefr** [comment]
Thanks. Would it be possible for you to include some request and response data here using the query inspector?

**Comment by liujin1993** [comment]
@marefr 
![image](https://user-images.githubusercontent.com/31949674/41587516-ff0bed68-73e1-11e8-94ef-0541dfdbdd9d.png)

**Comment by marefr** [comment]
@liujin1993 and if you expand the aggregations response a bit to show some returned values?

**Comment by liujin1993** [comment]
It seems that the return values is consistent with the panel. Most points is 10K about, just the value of now is vary low.
I feel the problem is in alert engine but not here.
![image](https://user-images.githubusercontent.com/31949674/41594180-1aac7e6c-73f5-11e8-92b3-155be3c55bba.png)

**Comment by marefr** [comment]
Okay, but the last value is 2600 in your screenshot. Not impossible that it was 1900 earlier? 

Have you tried saving the dashboard with this alert and verify what values it send alerts for, could be a bug with test rule so that it checking against the "now" instead of "now-5m"

**Comment by torkelo** [comment]
the problem is using last() it can usually be lower when grouping in time buckets as the last interval might not be a complete interval. We should probably have a next_to_last aggregation selector in alert rules :) 

Try changing alert rule aggregator func to max()
