### ISSUE TITLE
[Feat] Extended filtering support of dashboards in dashboard links

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#12338]
**Update (thanks @marefr):** 

If you add a dashboard link without tags, it also included folders which generates a weird behavior. Would be nice with the same filtering capabilities as available in the dashboard list panel, i.e. select a folder, filter by tags, and filter dashboard titles by free text query.

**Comment by marefr** [comment]
Are you asking for possibility to include template variables in the dashboard links or do you want to filter dashboards using template variables?

**Comment by ryantxu** [comment]
Can you give an example?  I'm struggling to understand the setup/feature -- but I'm sure you have a clear need.

**Comment by gretamosa** [comment]
Yes, no prob. I describe my use case in networking terms. I have a main/initial dashboard with some generic metrics, then I have some others (more detailed) in terms of IP address, ports/services and so on. In this scenario, it is useful to use dashlist panel like a way to navigate between dashboards. It is identical that "Drilldown / Detail link" in General tab in most panels but more visible. In order to give the same functionality, I proposed to consider templating variables (if available) once clicked on a dashlist item.

I hope that the description has got through :)

Regards,

**Comment by marefr** [comment]
I suggest you use the dashboard links functionality which has exactly the feature you're looking for

**Comment by gretamosa** [comment]
Yes, I didn't know dashboard links. It is what I'm looking for but I'm testing with Grafana v5.2.0-pre1 (1f32871) and it doesn't work with ad-hoc templating variables and it has a weird behavior because it also includes folders (not only dashboards) so when clicking, it fails.

Have you fixed these issues or I create a new one?

**Comment by marefr** [comment]
We've done some fixes recently for dashboard links, please try the latest commit/nightly build. Worked with dashboard drop down and adhoc filters for me when I tested now.

**Comment by gretamosa** [comment]
Ok, fine. I review latest commit and it worked with ad-hoc filters but if you add a dashboard link without tags, it also included folders which generates a weird behavior. You could do a recursive search through created folders or return first-level dashboards without folders.

**Comment by marefr** [comment]
That's a good point and a valid feature request. Will update the issue title/description to reflect this.

**Comment by marefr** [comment]
@gretamosa feel free to modify issue description if you don't agree with my update. Feel free to remove your initial description if that's no longer current.

**Comment by gretamosa** [comment]
Totally agree and initial description updated :)
