### ISSUE TITLE
Option to to disable OK Alert notifications

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#12330]
The new Elasticsearch Alerting capability has added a new dimension to our use of Grafana.  However, for IT Operational use, receiving Alerts when returning to 'OK' Status may be unnecessary and very noisy.  No option currently exists to disable the 'OK' Alerts.

Depending on the use case (and certainly in ours) there may be zero need for 'OK' Alerts, especially when Alerting based on changing operational values (detected virus, high CPU, etc).

Would like a way to globally disable all 'OK' Alerts.  Default to enabled, as is current, but provide the option via the .ini file to disable if desired.

**Comment by bergquist** [comment]
I dont think this belongs in the `grafana.ini` config file but rather as an configuration per alert notifier.

**Comment by davewat** [comment]
The motivation for putting it in the ini is that our team’s view was that we wanted a method to globally disable OK messages.  There are zero use cases that we would ever want to have an OK message (IT and security operations) and wanted to turn it off.   We were actually surprised by the OK message, as we only started testing Alerts with the new Elasticsearch support.

I can see when a per Alert would be adventageous to those who do use the OK message.  Any reason we couldnt have both?  There seems to be some support for globally disabling it ad this PR does (from the forums) as well.

**Comment by sanchomuzax** [comment]
I like to support development, which disables the type of `OK` messages.

I think this option would be better place in the Alert option of the Graph.

`[ ] disable 'OK' messages`

**Comment by fjlour** [comment]
Our team also has the same needs as @davewat. 
It's a lot of noise to have 2 notifications with 4 posts on Slack (webhook + bot with chart image) just to report one event that fired the alert and requested the teams attention.

I believe the best solution was to have a global option in the alert channel and then another option in the graph alert properties to control wether [OK] notifications are sent. 

This allows for a quick toggle ON/OFF all alerts and still allows for a particular chart to have a override behaviour.

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/13680
