### ISSUE TITLE
Add authorization layer to notification channels

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#12332]
Unless I missed something currently all notification channels are available to all users which is a problem in a "you build it, you run it" scenario where users can target the wrong notification channel in their alerts. The result of such "free for all" access according to Murphy's law, is an engineer being paged at 2AM for a service she has not clue about, with a link to a Grafana dashboard she can't access, snoozing the alert forever resulting in hours added to time to detection.

This feature request is about solving this problem by adding an authorization layer to the notification channels.

**Comment by bergquist** [comment]
This is definitely something we should support. But I'm not sure about when it fits our schedule.

**Comment by gschwel** [comment]
I agree, this really needs to be prioritized for an upcoming release. We should have the ability to assign some notification channels as "admin" only. Otherwise critical incidents may not be alerted upon, we have no control over ensuring critical alerts remain unaltered and get to their intended destination.

**Comment by mechero** [comment]
Any update on this feature? It would be enough if only Administrators can edit the settings for the Notification channels. Thanks!

**Comment by Asrafiel** [comment]
Really critical functionality. Any updates?

**Comment by abualy** [comment]
show blocker for us as well, can someone help with the feature implementation ?

**Comment by armandgrillet** [comment]
Role-based-access-control does not exist in Grafana OSS. We are working on adding this to Grafana Alerting for notification policies in Grafana Enterprise and Cloud >= 11.1.
