### ISSUE TITLE
Support MySQL data source to connect via socket

### ISSUE THREAD

**Issue by Yivan** [grafana/grafana#12342]
It seems MySQL provisionning data source doesn't support MySQL socket (but configuring Grafana database as MySQL support it... even if not mentionned in documentation, if the host begin by / it switch to unix socket connection).

Actually i cannot use Grafana because only sockets are used in our infrastructure (security and performance need).

I try with this notation too, but with no luck:
![database](https://user-images.githubusercontent.com/9025839/41592515-16b75c1a-73bd-11e8-8586-0563d769e5bf.png)

Is it a way to use mysql socket for provisionning data source ? If yes it should be documented, if no could it be added please ?

At least documentation here http://docs.grafana.org/installation/configuration/#database should mention unix socket are supported and how to use it (see source code here please: https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/sqlstore.go#L137)

Thanks.

**Comment by dadosch** [comment]
>At least documentation here http://docs.grafana.org/installation/configuration/#database should mention unix socket are supported and how to use it

I created a issue for mysql as a database via unix socket (as well as redis via unix socket). See https://github.com/grafana/grafana/issues/12814

**Comment by marefr** [comment]
Should be quite easy to fix since socket is already supported for Grafana backend mysql database. Anyone interested in contributing?

**Comment by Yivan** [comment]
@Yukinoshita-Yukino Thanks a lot for your PR !

**Comment by thelulzy** [comment]
Does Grafana support socket connection to a MySQL Data Sources now? 

Unless I'm missing something nothing in the UI or docs seems to indicate such.

**Comment by Yivan** [comment]
Hi!

It does a long time, but it should work as the PR has been merged. Yes it is not documented, but you should try by setting the host to `/path/to/socket` (for instance `/run/mysqld/myslqd.sock`), or if it doesn't work maybe to `@unix(/path/to/socket)`

Please see line 25 or the merged code, it detects if it begins with / :
https://github.com/grafana/grafana/pull/13705/files#diff-23ae9b166788f4745701c6907c4306351c42274503b22c577f3c1c25c4e4086fR25

Best regards.
