### ISSUE TITLE
Grafana 5.1.4 breaks LDAP auth?

### ISSUE THREAD

**Issue by schweikert** [grafana/grafana#12344]
I tried out the just released Grafana 5.1.4, and LDAP authentication doesn't work anymore. I downgraded to 5.1.3, and it worked again, so it seems caused by changes introduced with 5.1.4. I see in the logs:

    t=2018-06-19T13:51:26+0000 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 200 \"Network Error\": dial tcp 127.0.0.1:389: connect: connection refused"

The weird part is that it is apparently not using the correct LDAP server but 127.0.0.1:389, which is definitely wrong.

**Comment by marefr** [comment]
How are you running Grafana, debian, docker, windows etc?

**Comment by DanCech** [comment]
I'm guessing that you use `GF_AUTH_LDAP_CONFIG_FILE` to specify the location of your `ldap.toml` file and that the 5.1.4 docker image doesn't work with that because of grafana/grafana-docker#170

Your best bet will be to stick with 5.1.3 until that is fixed

**Comment by DanCech** [comment]
I opened grafana/grafana-docker#172 with a fix for this issue

**Comment by schweikert** [comment]
Yes, indeed

**Comment by marefr** [comment]
Closing this issue in favor of grafana/grafana-docker#170 then

**Comment by peter-iglaev** [comment]
I use grafana.ini which link to ldap.toml. But I have the same error.
I tried versions 5.2.2, 5.1.2, 5.1.3
The host in toml file change to 127.0.0.1

**Comment by marefr** [comment]
@peter-iglaev we have no other reports of this since release v5.1.5 and v5.2.0. Are you running Grafana using docker? Please include how you run it

**Comment by peter-iglaev** [comment]
@marefr move our conversation - https://github.com/grafana/grafana/issues/12719
