### ISSUE TITLE
Dashboard links break after upgrade from 4.x to 5.x 

### ISSUE THREAD

**Issue by keithf4** [grafana/grafana#12349]
Please include this information:

### What Grafana version are you using?

4.6.3 Upgrading to 5.1.x

### What datasource are you using?

Prometheus (not relevant to issue)

### What OS are you running grafana on?

CentOS 7.5

### What did you do?

Upgraded from 4.6.3 to 5.1.4. Just installed new package and restarted grafana

### What was the expected result?

We have several dashboards that link to each other. Links should keep working even if dashboards are removed and imported again.

### What happened instead?

In the course of testing out the new dashboard provisioning system, we found an issue with links between dashboards if you ever remove an old dashboard upgraded from 4.6 and try to import again. If the option to open the linked dashboard in a new tab is chosen, or the link to the dashboard is simply copied and pasted into a new tab, the old UID from when the dashboard was upgraded from 4 to 5 is used. If you just have dashboard links open in the same tab, they continue to work fine.

You can reproduce this issue by following these steps:

1.  Install Grafana 4.6.3
1.  Import any dashboards that were originally made for 4.6 (there is no UID pre-defined in these) and that have at least one link between them. Make sure the option to "Open in new tab" is checked for the link. We have some here you can use, but they may not be useful without all the other setup involved in our software suite since we use variables based on prometheus labels and the links require those. PostgreSQL links to PostgreSQLDetails which links to the rest. https://github.com/CrunchyData/pgmonitor/tree/master/grafana
1. Upgrade Grafana to any 5.1.x version (did not test this in 5.0). All the links should still work, but you'll see the UIDs these dashboards were assigned are pretty generic (000000001, 000000002, etc)
1. Remove any dashboard in the link chain. 
1. Import the dashboard(s) again. You can either import the old 4.6 one or even export and reimport the dashboard again so it's technically a 5.1 dashboard. You can even use provisioning. You'll see a new UID is generated.
1. Try any dashboard link again and when it tries to open in the new tab, you'll see the URL is trying to use the old generic UID value from when the dashboard was originally upgraded. If you change the link to not open in a new tab, it works fine.

This doesn't seem to be a problem with dashboards newly created in Grafana 5.x. They continue to work even after removal and reimporting. So something with these old UIDs created during an upgrade seems to be lingering around even after the old dashboard is removed.

**Comment by bergquist** [comment]
Dashboards that existed in the DB during the migration got their numeric ID as UID. When you import a new dashboard without UID, Grafanas backend will generate a new one. 

To avoid generating a new UID when importing the same dashboard your dashboard have to contain the UID. If an UID already exists in the dashboard.json Grafana will not generate a new one. 
you have to go into settings and view json and use that json.

**Comment by torkelo** [comment]
not sure there is a bug here, will close for now

**Comment by keithf4** [comment]
I get that you can try to keep the UID the same as long as you're exporting it and reimporting it again. The issue is that it's somehow keeping the old UID around and trying to use it when you have "Open in new tab" chosen. If people are trying to reimport their their old pre-5.0 dashboards after they were upgraded for some reason, they're going to keep having this problem forever unless they realize they have to export their old dashboards again to keep that numeric UID around. 

I'd be fine with it generating a new UID and using that consistently. Something is keeping old data around after the upgraded dashboard is deleted. That seems like a bug to me.

**Comment by keithf4** [comment]
That was it! Didn't realize things like that were kept in the browser cache. Thanks!
