### ISSUE TITLE
Influxdb templating variable values placeholder example wrong

### ISSUE THREAD

**Issue by epelc** [grafana/grafana#1234]
The place holder for the `Variable values query` placeholder field seems to be wrong when using `influxdb` as a datasource. It's `app.servers.*` when it should be something more along the lines of `list series /app.servers.*/`. I may not be 100% correct on what it should be but nothing like the example was working for me, and wildcard queries with influxdb seem to require it be in a regex,

![bad template](https://cloud.githubusercontent.com/assets/5204642/5439589/ee3e9ef8-844e-11e4-9b63-c3b24fa1ee72.png)

**Comment by markusr** [comment]
Also the all "All option" seems to be wrong for influxdb. 
It should default ```"value0","value1"``` for querying series and values.
