### ISSUE TITLE
[Question] Simple graph for time series data

### ISSUE THREAD

**Issue by BentCoder** [grafana/grafana#12347]
I am asking this question here because Community site won't let me login so apologies for the noise caused.

```
name: points
time                action    value
----                ------    -----
1529415192464409900 create    0.223
1529415193252917500 download  0.79
1529415194774618000 create    0.387
1529415203019611000 download  0.102
1529415203223282100 update    0.205
1529415203817086100 update    0.59
1529415205250508600 update    0.32
1529415206263275800 create    0.048
1529415206478024300 create    0.214
1529415207106534900 download  0.627
1529415208885618800 create    0.598
```

I have the time series data looks like the one above in InfluxDB and would like to visualise it (graph per "action" so that I have three graphs) with "Graph" option of Grafana so that it looks like the example below. However, I couldn't find a way to do it. Could please someone help me out with this? I am using version `5.1.0`.

```
FROM: autogen
DATABASE: request
MEASUREMENT: points

action: User's action.
value: Time took to complete the action. (millisecond)
```

![untitled](https://user-images.githubusercontent.com/8837278/41605516-7b2c440a-73d9-11e8-9a4e-2b39679f08df.png)

**Comment by torkelo** [comment]
group by action tag? or is action a field? 

Please ask questions on the community site https://community.grafana.com

**Comment by torkelo** [comment]
did you get an error logging in to community site?
