### ISSUE TITLE
Send alert notification for every alert eval regardless of state

### ISSUE THREAD

**Issue by qhh0205** [grafana/grafana#12356]
Hello, everyone,
     I have search the community and github issue, it sames that Grafana alert does not support persistent alarm regardless the state change. I want to alert whenever reach the alarm condition
regardless the alert state transmit, so how can I implement this function?

### What Grafana version are you using?
grafana-5.1.3
### What datasource are you using?
influxdb、elasticsearch
### What OS are you running grafana on?
RHEL7 Linux
### What did you do?
Config the grafana alert.
### What was the expected result?
Expect the grafana to support the persistent alarm regardless the state change.
### What happened instead?
The alert only trigger once when the alert state is still `alerting`(not changed).

**Comment by bergquist** [comment]
You want to send an alert notification every time an alert is executed and in alerting state?
Just curious.. What kind of alert notifier are you using? What kind of interval does the alert rule have?

Would https://github.com/grafana/grafana/issues/7330 solve your problem?

**Comment by qhh0205** [comment]
@bergquist 
Yes, i want to send an alert every time an alert is executed No matter what the alarm state is like. Now, the alert only trigger once when the alert state keep alerting.

### My alert notifier type is webhook i provided:
![image](https://user-images.githubusercontent.com/12775142/41709092-ebdff04c-7574-11e8-8e47-903f739000e8.png)

### The flollowing is my alert config:
![image](https://user-images.githubusercontent.com/12775142/41709160-1ecee5c6-7575-11e8-8bca-82517164cb3f.png)

**Comment by bergquist** [comment]
Ok, that's not possible today. We might add support for this in the future if it's a popular request.

Once we have support for alert notifiers as backend plugins this behavior could be implemented as a plugin.

**Comment by qhh0205** [comment]
@bergquist 
Thank you! I am looking forward to this feature. I used ZABBIX alarm system before, that supports this alarm feature. 
It seems that other people also need such a feature：
1. #7641
2. https://community.grafana.com/t/issues-with-alerting/5531/3

**Comment by WoZ** [comment]
+1 for this feature.

Want to describe my case. I configured grafana to monitor amount of fps in live video streams. On every run a list of streams with low fps may change (and actually it does) but I receive alert only first time. Such way requires alerting all the time regardless of ALERTING state.

**Comment by bergquist** [comment]
This is possible since 5.3 if you configure alert reminder at the same or lower interval as the alert rule. 

It's not exactly what's described in this issue but its close enough that we won't implement this feature.

**Comment by gaizeror** [comment]
@bergquist Hey, I think this feature is a must.
We have alerts that include many processes on a single graph, which means that if a process is down and we get an alert, and another process is being down while not solving the first one, we won't know about it. The reminder causes lots of spam and doesn't give the required value. 
To avoid such risks, we have to split one graph to tens of graphs.

**Comment by bergquist** [comment]
Thats something we want to adress. We are currently redesigning the alert system.

But I'm not sure sending new notifications is a good solution since it could cause lots of notifications if the alert has many series. I think we want to have a better UI for this withing Grafana. IMO the alert notification should only be used to get your attention, the rest of the incident should be followed up withing Grafana. 

Would that make sense?

**Comment by gaizeror** [comment]
> Thats something we want to adress. We are currently redesigning the alert system.
> 
> But I'm not sure sending new notifications is a good solution since it could cause lots of notifications if the alert has many series. I think we want to have a better UI for this withing Grafana. IMO the alert notification should only be used to get your attention, the rest of the incident should be followed up withing Grafana.
> 
> Would that make sense?

I disagree, we missed so many alerts because of that. 
Think of the simplest scenario - High memory alert. 
02:00 am you get PagerDuty, server memory is very high and you start investigating root cause and etc. In the meanwhile, your database primary server's memory increased and now should be alerted, but it's not. 5 mins later you get an alert for host down (your primary db server) and shit got worse.
There are 2 options to prevent such thing:
1. create graph per case (which is totally stupid).
2. support multi notifications per alert (which totally makes sense).

This story happened to us 3 days ago, and forced me to duplicate a single graph 12 times for each super important server

**Comment by bergquist** [comment]
I wrote a small comment in https://github.com/grafana/grafana/issues/6041 about this issue.

**Comment by gaizeror** [comment]
Thanks! hope to see it working soon!

**Comment by ma-sattari** [comment]
+1  from me for this feature

**Comment by pete00067** [comment]
Now grafana has a send reminders option now in the Alert Notifications page. Which allows notification to be sent every interval(selected by you) while alert is still on.

**Comment by cqcn1991** [comment]
I'm not sure if this is the right isssue. 

Here is my use case: we use grafana to monitor series by different type (the 'group by term' setting in grafana). And different type have different meaning (its like stocks)

Sometimes, one type of series (i.e., one stock) triggered the alert and send out msg. But the alerting state will block other alerts from other types (other stocks).

A similar example is that one stock's price dropped sharply triggered some alert; and other stocks's alert following it would not be send (as it is already in `alert status`)

**Comment by qixiaobo** [comment]
> To avoid such risks, we have to split one graph to tens of graphs.

Exactly~

**Comment by qixiaobo** [comment]
> Now grafana has a send reminders option now in the Alert Notifications page. Which allows notification to be sent every interval(selected by you) while alert is still on.

I would have a try

**Comment by chefcook** [comment]
> Now grafana has a send reminders option now in the Alert Notifications page. Which allows notification to be sent every interval(selected by you) while alert is still on.

I tried this out. But basically this is a repeat of the initial alert and not a new trigger.
Are there any updates to the initial request?

**Comment by bryjonez** [comment]
Would really love to see an **OPTIONAL** feature added to be to send alerts for each event that crosses the threshold.

![2021-09-24_7-44-37](https://user-images.githubusercontent.com/91334170/134696299-e7d23e10-eeea-43bf-aab5-d67d5f2ad7b5.png)

**Comment by qixiaobo** [comment]
> Would really love to see an **OPTIONAL** feature added to be to send alerts for each event that crosses the threshold.
> 
> ![2021-09-24_7-44-37](https://user-images.githubusercontent.com/91334170/134696299-e7d23e10-eeea-43bf-aab5-d67d5f2ad7b5.png)

You can use reminders

Now grafana has a send reminders option now in the Alert Notifications page. Which allows notification to be sent every interval(selected by you) while alert is still on.

**Comment by chefcook** [comment]
> You can use reminders
> 
> Now grafana has a send reminders option now in the Alert Notifications page. Which allows notification to be sent every interval(selected by you) while alert is still on.


reminder  != alert

**Comment by qixiaobo** [comment]
> > You can use reminders
> > Now grafana has a send reminders option now in the Alert Notifications page. Which allows notification to be sent every interval(selected by you) while alert is still on.
> 
> reminder != alert

Yeah,  but  this is designed for continued alert in specify channel

**Comment by mertkaant** [comment]
> Would really love to see an **OPTIONAL** feature added to be to send alerts for each event that crosses the threshold.
> 
> ![2021-09-24_7-44-37](https://user-images.githubusercontent.com/91334170/134696299-e7d23e10-eeea-43bf-aab5-d67d5f2ad7b5.png)

Totally agreed with this. This is exactly the same with our use case. I think there aren't any updates about it? I think still there isn't a way to solve this issue? Did you solve this issue @bryjonez ?
