### ISSUE TITLE
Grafana query editor incorrectly quotes boolean parameter

### ISSUE THREAD

**Issue by denilsonsa** [grafana/grafana#12355]
How to reproduce:

1. Go to https://play.grafana.org/d/000000012/grafana-play-home (or to your own Grafana)
2. Create a new graph panel, or edit an existing one.
3. Paste this query: `summarize(apps.fakesite.*.counters.requests.count, '1h', 'sum', false)`
    * Note the `false` parameter is unquoted, even if you look at Query Inspector.
4. ☰ → Toggle Edit Mode.
    * Note the `false` parameter disappeared from the UI.
5. ＋ → add `aliasSub`, then type `(.*)` as the regex.
    * Adding any other function would also work. We just need something to trick the UI into re-generating the query sent to the backend.
6. **BUG!** The graph data has changed, it shouldn't. Depending on the graph/metric, it might just disappear.
    * Query inspector shows `'false'` (with single-quotes) being passed.
    * The graph legend shows `true`, which means the string `'false'` is being evaluated as `true`.
7. Click on the empty third parameter from `summarize()`, then select `false`.
    * The query is now fixed, `false` is being correctly passed unquoted.
8. ☰ → Toggle Edit Mode. Notice the unquoted `false` parameter, as it should be.
9. ☰ → Toggle Edit Mode. **BUG** Notice the `false` parameter disappeared again. But the graph hasn't been updated yet.
10. Move the `aliasSub` function to the left and then back to the right.
    * For humans, this means we did a change, and then we manually reverted the change back to the previous state.
11. **BUG** The graph has been updated, and `'false'` is now quoted.
12. ☰ → Toggle Edit Mode. Notice the query has been changed, `'false'` is now quoted.

Confused? Look at this screencast showing the bug: https://www.youtube.com/watch?v=Xh5MRWRroZQ

Grafana version: 5.1.3 or 5.1.4
Datasource: default (graphite?)
OS: Linux (I don't think it matters for this issue)

I believe this is a **regression**, I think this issue didn't happen in older versions (IIRC, Grafana 3 didn't have this issue, but I don't recall the exact version).

Possibly related issues: #11927 and #2078.

**Comment by torkelo** [comment]
thanks for reporting this, and for such a detailed issue description. 

It is very similar to https://github.com/grafana/grafana/issues/11927 , was introduced in same commit as https://github.com/grafana/grafana/issues/11927 so can be fixed at the same time, added link from that issue to this issue with description of how to fix it.
