### ISSUE TITLE
SNI-PNP-DATASOURCE - The datasource does not support alerting queries

### ISSUE THREAD

**Issue by tifend** [grafana/grafana#12352]
Hello,

We are using Grafana With PNP4Nagios (nagios core) and using datastore as SNI-PNP-DATASOURCE

When creating an alert configuration, it shows this message "The datasource does not support alerting queries".

How can we fix this issue?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Basically alerting isn't supported right now for non Grafana-core datasources. Will be possible when #6841 is fixed.
