### ISSUE TITLE
Alert not working with elastic search as datasource?

### ISSUE THREAD

**Issue by killerfish16** [grafana/grafana#12358]
Dear Team,

We are developing our monitoring system and using Grafana for visualization. And elastic search  as our datasource. 

**Grafana version: 5.1.3**

Currently we are trying to setup alerts. But we are getting the below error
 **2018-06-20T13:23:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=3 name="TMM Message Sent alert" error="tsdb.HandleRequest() error Could not find executor for data source type: elasticsearch" changing state to=alerting**

While searching got the issue id:
https://community.grafana.com/t/is-alerting-supported-for-elasticsearch-database/4077 

So, could you please confirm that still Grafana doesn't support alert for elastic search as data source

If its going released in 5.2 version, is there any tentative data for the release.

Regards,
Raj

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Elasticsearch alerting will be included in Grafana v5.2.0 stable release. For now you can try it out using [v5.2.0-beta1](https://grafana.com/grafana/download/5.2.0-beta1) or a nightly build.
