### ISSUE TITLE
Interpolate SNMP interface bandwidth ---Negative value--- derivation Measurment 

### ISSUE THREAD

**Issue by houchunzhong** [grafana/grafana#12353]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.1.3 (087143285)
### What datasource are you using?
Elasticsearch 6.2.4
### What OS are you running grafana on?
CentOS7.2
### What did you do?
Monitoring Network Switch Interface bandwidth
### What was the expected result?
Interface bandwidth B/S as sampling every 2 minitue
### What happened instead?
Negative value appear in the interface monitoring
### If related to metric query / data viz:

`host:${Switch_Name}AND` `type_instance:${Interface_Name}`
![metric_query](https://user-images.githubusercontent.com/22065653/41639647-3cdde574-7491-11e8-9ba3-5a4200f39c73.jpg)
![collectd_negative_value](https://user-images.githubusercontent.com/22065653/41639606-08b0e8dc-7491-11e8-8d71-64ceb639b981.jpg)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
![grafana_page_loading_network](https://user-images.githubusercontent.com/22065653/41639939-77733b2a-7492-11e8-9da1-e03d92051020.jpg)

**Comment by marefr** [comment]
Please use the query inspector to troubleshoot, see https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630/1. If you still think this is a bug, please include request and some response data from query inspector underlying your problem.

**Comment by houchunzhong** [comment]
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/3/_msearch"
data:"{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"network-*","max_concurrent_shard_requests":256} {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1529483012664","lte":"1529484812664","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host:172.10.1.229AND type_instance:Port\\-channel1"}}]}},"aggs":{"3":{"date_histogram":{"interval":"2m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1529483012664","max":"1529484812664"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"rx","script":{"inline":"_value*8"}}},"4":{"derivative":{"buckets_path":"1"}}}}}} {"search_type":"query_then_fetch","ignore_unavailable":true,"index":"network-*","max_concurrent_shard_requests":256} {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1529483012664","lte":"1529484812664","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host:172.10.1.229AND type_instance:Port\\-channel1"}}]}},"aggs":{"2":{"date_histogram":{"interval":"2s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1529483012664","max":"1529484812664"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"tx","script":{"inline":"_value*8"}}},"3":{"derivative":{"buckets_path":"1"}}}}}} "

**Comment by houchunzhong** [comment]
2:Object
1:Object
value:14661334101.333334
4:Object
value:-6215127925.333334
key_as_string:"1529483160000"
key:1529483160000
doc_count:3

**Comment by houchunzhong** [comment]
hi marefr,
Appreciate your help, As you seen from the query inspector slice view above.

Then object come out -6215127925.333334 value for the bandwidth. Really has no idea this time.

**Comment by marefr** [comment]
Query looks correct. If elasticsearch returns negative derivatives I'm afraid there's nothing you can do right now to fix it - There's currently no support in Grafana for enforcing only non-negative derivatives, see #3561. 

Consider reopen this if you can show that this is an actual bug in Grafana.

**Comment by houchunzhong** [comment]
Dear Marefr,
 I am very new to Grafana, below is the switch bandwidth result. I know it is wrong. Could you tell me how to fix it?

![image](https://user-images.githubusercontent.com/22065653/41729035-d263964c-75aa-11e8-923d-68bb7fb66e58.png)

**Comment by houchunzhong** [comment]
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/54/_msearch"
data:"{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["net-bw-monitor-2018.06.21"]} {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1529593848517","lte":"1529594748517","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host:10.28.212.5AND type_instance:XGigabitEthernet0_0_10"}}]}},"aggs":{"2":{"date_histogram":{"interval":"1m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1529593848517","max":"1529594748517"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"rx","script":{"inline":"_value*8"}}},"3":{"derivative":{"buckets_path":"1"}}}}}} {"search_type":"query_then_fetch","ignore_unavailable":true,"index":["net-bw-monitor-2018.06.21"]} {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1529593848517","lte":"1529594748517","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host:10.28.212.5AND type_instance:XGigabitEthernet0_0_10"}}]}},"aggs":{"2":{"date_histogram":{"interval":"1m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1529593848517","max":"1529594748517"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"tx","script":{"inline":"_value*8"}}},"3":{"derivative":{"buckets_path":"1"}}}}}} "
response:Object
responses:Array[2]
0:Object
1:Object

**Comment by houchunzhong** [comment]
We are using Collectd--60s sampling rate-->Logstash--->Elastic Search---->Grafana to monitor Switch bandwidth.
The data in Elastic Search has proved the bandwidth octet data is correct.
**Bandwidth in switch:**
![image](https://user-images.githubusercontent.com/22065653/41729885-02e6d048-75ad-11e8-9a7a-20caed6071c9.png)
**Bandwidth in ES via Kibana:**
![image](https://user-images.githubusercontent.com/22065653/41729990-391733c4-75ad-11e8-9f90-da4132f4511f.png)

**Comment by houchunzhong** [comment]
Hi Marefr,
I would like to provide more information upon your request.  Really appreciate! 
![image](https://user-images.githubusercontent.com/22065653/41730260-faf83a74-75ad-11e8-9d56-945d39723a33.png)

**Comment by marefr** [comment]
Maybe you have a gap in your data - try setting 0 (zero) in the missing field for avg rx. Besides this I'm saying that if elasticsearch returns a negative value in response to your derivative query you should look in elasticsearch for answers - Grafana can't do anything about this.
