### ISSUE TITLE
export Grafana panel with threshold values

### ISSUE THREAD

**Issue by blah-dj** [grafana/grafana#12361]
I am trying to export a Grafana panel with threshold values, but could not find the url to be used in iFrame which contains threshold value? I understand thresholds can't be created using variables (huh!!) but is it still possible to share a map with threshold values?

**Comment by bergquist** [comment]
Not sure sure what you are trying to do. 

http://docs.grafana.org/reference/sharing/#embed-panel this is the docs for iframing panels. 

Please ask questions on the community site.
