### ISSUE TITLE
Changing time range to "future" on grafana breaks the server

### ISSUE THREAD

**Issue by ErwintheFox** [grafana/grafana#12360]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.1.0
### What datasource are you using?
graphite and cloudwatch
### What OS are you running grafana on?
amazon ami
### What did you do?
changed the timestamp 
from :now-24 hrs .  >>>> from :now+24 hr
![image](https://user-images.githubusercontent.com/39843256/41688287-5c7b5a60-74a0-11e8-82b9-571f7e89fd14.png)

### What was the expected result?
should throw error or something else
### What happened instead?
grafana server broke
with error message 
lvl=eror msg="failed to fetch data source" logger=context userId=0 orgId=1 uname= error="Data source not found"
t=2018-06-20T22:32:52+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/tsdb/query status=500 remote_addr=162.***.2**.** time_ms=577 size=41 referer="https://grafana-proxy-*******************.com/d/cloudsearch/cloudsearch?refresh=1m&orgId=1&from=now%2B24h&to=now"
t=2018-06-20T22:32:52+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/tsdb/query status=500 remote_addr=162.***.2**.** time_ms=340 size=41 referer="https://grafana-proxy-*****************.com/d/cloudsearch/cloudsearch?refresh=1m&orgId=1&from=now%2B24h&to=now"
![image](https://user-images.githubusercontent.com/39843256/41688332-8890d846-74a0-11e8-8429-f175be19c90b.png)
I had to manually restart it 

update:
we use multiple grafana server setup in our production environment where it breaks ,
it did the same thing in a single server setup in our DEV environment too.

**Comment by torkelo** [comment]
Are you using multiple (different) orgs? Maybe at the same time ? What is your grafana setup (single server or multiple)?

**Comment by marefr** [comment]
Think this is same problem as #12199. Please verify your grafana server log. If the same a fix will be included in Grafana v5.2.0 stable.

**Comment by satyan6891** [comment]
I am sorry that I didn't give full information first time.
Yes in our production environment we are using multiple grafana servers but only one "ORG".
we encountered same issue of grafana breaking for entering future timestamp  in our grafana(single server) used in dev environment .

**Comment by marefr** [comment]
Should have been fixed by #12199. But selecting a from date before end date is not supported with the cloudwatch
