### ISSUE TITLE
Dashed lines do not respect z-index

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#12365]
I'm using v5.0.3 and it noticed that when a line is made dashed the z-index is no respected anymore and the line comes on top.

![dashed](https://user-images.githubusercontent.com/153052/41710479-06508114-7546-11e8-8f4f-4366a69e13f1.PNG)

Is this a bug or intended ?

**Comment by ChimealHeltei** [comment]
+1

**Comment by zuchka** [comment]
this appears fixed in Grafana 9. closing for now 👍
