### ISSUE TITLE
Can not import grafana dashboard into perticular folder 

### ISSUE THREAD

**Issue by MahadevG** [grafana/grafana#12369]
### What Grafana version are you using?
5.1.3
### What datasource are you using?
Influx
### What OS are you running grafana on?
Windows 10 pro
### What did you do?
Used Grafana import API to import the dashboard and able to import the dashboard.
### What was the expected result?
Grafana should import dashboard in particular folder (user defined folder)
### What happened instead?
By default it will save dashboard in general folder even though I provide the folder id. 

If it is not possible to import in particular folder how can I move dashboards from general folder to user defined folders using API(I already tried with create/update dashboard API).

**Comment by marefr** [comment]
Should be fixed in #10796

**Comment by eimarfandino** [comment]
I am experiencing the same issue with Grafana v5.3.4. @marefr, has this been resolved?

**Comment by marefr** [comment]
@eimarfandino you'll use the `folder` property in your yaml file to specify which folder provisioned dashboards should be saved, see [docs](http://docs.grafana.org/administration/provisioning/#dashboards).
