### ISSUE TITLE
Support markdown in Annotation description 

### ISSUE THREAD

**Issue by majkinetor** [grafana/grafana#12366]
Annotations are very handy to contain log snippets. Since description doesn't accept Markdown it looks bad due to absence of formatting and tiny window.

![image](https://user-images.githubusercontent.com/85767/41710814-e1bc8324-7546-11e8-8195-32c7c469cb09.png)

**Comment by majkinetor** [comment]
Here is the code for this sample:

https://github.com/majkinetor/psgrafana

```powershell
$Env:GRAFANA_URL             = "http://localhost:3000"        
$Env:GRAFANA_USERNAME = 'admin'
$Env:GRAFANA_PASSWORD = 'admin'

$ErrorActionPreference = 'STOP'

import-module psgrafana
Initialize-Session

$dash = New-Dashboard 'PSGrafana Annotation Test' -Overwrite

$params = @{
    DashboardId = $dash.id
    Time        = (Get-Date).AddMinutes(-30)
    Timespan    = '00:10'    
    Text        =  ps | select ProcessName, CPU -first 25 | ft | out-String
}
New-Annotation @params
```

**Comment by n0guest** [comment]
It would be great to have such feature!

**Comment by redbonta** [comment]
Hello.
We also want this feature, please.
