### ISSUE TITLE
Support reading config value from file when provisioning datasources

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#12368]
By allowing the provisioning system to read config values from disk as an alternative to regular strings, we enable orchastrators such as k8s, mesos and open shift to provide the token value as a file. This way the token management/lifecycle will be completly managed to the orchastrator without changing the datasource.yaml file. 

Ex in kubernetes case
```
<brancz> concretely the service account token is located in /var/run/kubernetes.io/serviceaccount/token
```

cc @brancz

**Comment by brancz** [comment]
Note this is also a common way to distribute secrets generally. Even outside of orchestration systems it's very common to provision secrets separately from configuration. With hashicorp's vault for example people create virtual filesystems to read secrets from, just to give an example and show this is useful in any kind of deployment, and not just Kubernetes/Mesos/OpenShift (but also good for those) :slightly_smiling_face:.

**Comment by bobmshannon** [comment]
Agreed this would be useful especially for secrets.

What would the YAML configuration syntax for this feature look like?

**Comment by sichvoge** [comment]
Any updates on this ticket?

**Comment by brancz** [comment]
In Prometheus what we do is something along the lines of having two fields `secret` and `secretFromFile`, and internally `secret` is populated from `secretFromFile`, if set.

**Comment by sichvoge** [comment]
@bergquist is there any update on this by any chance?
