### ISSUE TITLE
Dashboard rows absorb extra panels

### ISSUE THREAD

**Issue by macgyver603** [grafana/grafana#12376]
### What Grafana version are you using?
Grafana v5.1.3 (commit: 087143285)
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Added a panel underneath an existing row and expanded and collapsed the row
### What was the expected result?
The new panel remains separate from the row
### What happened instead?
The new panel gets absorbed by the row when it is collapsed again. 

I took a look at the dashboard's JSON when the row is expanded/collapsed, and this appears to be a problem with how Grafana saves the state of the row.

When the row is collapsed with it's panel (Panel1), the panel's JSON is included in the row's `panels` array, while the new panel (Panel2) is included in the dashboard's `panels` array:  
```
...
"panels": [
  {
    "collapsed": true,
    "gridPos": {
      "h": 1,
      "w": 24,
      "x": 0,
      "y": 0
    },
    "id": 2,
    "panels": [
      {
        ...
        "gridPos": {
          "h": 4,
          "w": 24,
          "x": 0,
          "y": 1
        },
        "id": 4,
        "title": "Panel1"
      }
    ],
    "title": "Row1",
    "type": "row"
  },
  {
    ...
    "gridPos": {
      "h": 4,
      "w": 24,
      "x": 0,
      "y": 1
    },
    "id": 6,
    "title": "Panel2",
  }
]
```  

However, when the row is expanded, Panel1's JSON gets moved to the dashboard's `panels` array:
```
...
"panels": [
  {
    "collapsed": false,
    "gridPos": {
      "h": 1,
      "w": 24,
      "x": 0,
      "y": 0
    },
    "id": 2,
    "panels": [],
    "title": "Row1",
    "type": "row"
  },
  {
    "gridPos": {
      "h": 4,
      "w": 24,
      "x": 0,
      "y": 1
    },
    "id": 4,
    "title": "Panel1"
  },
  {
    "gridPos": {
      "h": 4,
      "w": 24,
      "x": 0,
      "y": 5
    },
    "id": 6,
    "title": "Panel2",
  }
]
```
When the row is collapsed again, JSON for all panels below it gets incorporated back into the row's `panels` array:
```
...
"panels": [
  {
    "gridPos": {
      "h": 1,
      "w": 24,
      "x": 0,
      "y": 0
    },
    "id": 2,
    "panels": [
      {
        ...
        "gridPos": {
          "h": 4,
          "w": 24,
          "x": 0,
          "y": 1
        },
        "id": 4,
        "title": "Panel1",
        }
      },
      {
        ...
        "gridPos": {
          "h": 4,
          "w": 24,
          "x": 0,
          "y": 5
        },
        "id": 6,
        "title": "Panel2",
      }
    ],
    "title": "Row1",
    "type": "row"
  }
]
```

An additional thing to note is that this example only uses one row for the sake of brevity, but when there are multiple rows in a dashboard, all panels up to the next row will be moved to the row's `panels` array when it is collapsed. Rows are great for hiding bulky table panels or panels with expensive queries, but to work around this issue, these rows have to be placed at the bottoms of dashboards, or additional rows are needed as barriers to prevent hiding too many panels.

**Comment by Ashald** [comment]
This was bugging me for month and I always though that I cannot be the only one having issues with that so never checked if there is an issue about that. @macgyver603 thanks for reporting!

**Comment by torkelo** [comment]
When you collapse a row all panels below it (up to the next row) will be absorbed. 

The new grid layout does not support nesting of grids, so in order to be backward compatible  with the old row system (that no longer is needed to create dashboard layouts) we had to resolve to some less the ideal behavior
