### ISSUE TITLE
[API] Invalid alert data. Cannot save dashboard

### ISSUE THREAD

**Issue by rtokoi** [grafana/grafana#12375]
I cannot create alerts using the HTTP API.

I'm using the /api/dashboards/db (POST) endpoint and when I post a JSON with alerts in the panels, it returns the following error:

[500] Invalid alert data. Cannot save dashboard

If I remove the alerts from the JSON, then I can save the dashboard successfully.

### What Grafana version are you using?
5.1.4

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
CoreOS

### What did you do?
Used the HTTP API to create/update a dashboard

### What was the expected result?
Status code 200 and the dashboard should be created successfully with the alerts in it.

### What happened in stead?
Got status code 500 and the dashboard wasn't updated or created at all. Removing the alerts from the JSON makes it work again.

### Additional information
Here's the JSON used in the request, it's quite long:
https://justpaste.it/7c6pv

**Comment by torkelo** [comment]
Any detail in the grafana server log?

**Comment by torkelo** [comment]
closing due to no more details.

**Comment by rtokoi** [comment]
I apologize for the delay, I've been busy with other stuff. This is what I found in the logs:

**Comment by rtokoi** [comment]
I apologize for the delay, this is what I found in the logs:
```t=2018-07-02T15:03:30+0000 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=0 orgId=1 uname= error="Invalid alert data. Cannot save dashboard"```
I'm running Grafana on K8s

**Comment by rtokoi** [comment]
@marefr Thanks, it worked perfectly when I attributed an ID to each alert.

**Comment by frederiksf** [comment]
> @marefr Thanks, it worked perfectly when I attributed an ID to each alert.

Could you share your json? I have the same issue but adding an ID attribute doesnt help. When i import via the UI everything is ok.

**Comment by rtokoi** [comment]
Hey @frederiksf , here's the template I used (this is only the alert section, btw):

https://jsonblob.com/463b4309-b97d-11e9-9082-4d1556363ba2

Hope it helps.

By the way, if I recall correctly, importing via the UI requires a different format.
