### ISSUE TITLE
[Bug] Graph Alert Config conditions fail on blend of 'is above' & 'is below'

### ISSUE THREAD

**Issue by jedd** [grafana/grafana#12377]
Context:  Grafana 5.0.1 , InfluxDB data source, RHEL7

I have created a dashboard with four metrics :  in / outbound stats for routers at each end of a link.

I have scaled ( x -1) outbound/inbound on one pair to show above/below on 0-centered Y axis.

Creating an Alert notification for 4 conditions:
avg of link A > 9.5Gbps
OR avg of link B > 9.5Gbps
OR avg of link C < 9.5Gbps
OR avg of link D < 9.5Gbps

Graph is set to show Y from -10Gbps up to +10Gbps

I expect to see a high and low red threshold identifier, but see only the high one.

I suspect this is a bug.

![issue - grafana - compound condition bug - 1](https://user-images.githubusercontent.com/114736/41752441-ca7ac7ce-760a-11e8-9245-c33f7d91ca78.png)

FYI,  if I set up an alert with just: 
avg of link C < 9.5Gbps
OR avg of link D < 9.5Gbps

... then I see the lower red threshold identifier, as expected.

![issue - grafana - compound condition bug - 2 - lower-limit works](https://user-images.githubusercontent.com/114736/41752482-1231eee4-760b-11e8-8c0e-69b88c946f34.png)

If I use 'outside range' this also works as expected.

![issue - grafana - compound condition bug - 3 - outside range works](https://user-images.githubusercontent.com/114736/41752487-1ae6dde2-760b-11e8-95b6-6be2d9d29291.png)

**Comment by torkelo** [comment]
Visualized thresholds (and the threshold handles) only support the first alert condition. Think there is already an open feature request to visualize more conditions
