### ISSUE TITLE
Add ability to duplicate row with all panels

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#12372]
Use case:
When creating a dashboard for RED metrics of various different subsystems, it'd make it easier to copy the general panel configuration (axes, display) and just modify all the metric expressions.

**Comment by bergquist** [comment]
I think this makes sense. We could display a new icon when hovering the rows.

**Comment by Unyxos** [comment]
Hi, any update on this ? We need to duplicate rows and their content but can't use templating as the zabbix datasource don't support variables in item name. We could make something using Grafana API to add new elements in the future, but right now we'd need to duplicate it 17 times

thanks!

**Comment by naughtyGitCat** [comment]
Hi, is there any update on this ?

**Comment by davidfeeney** [comment]
+1 Any news on this? We need to recreate a row 40+ times right now. This feature would make that very easy. The repeating rows and values based on variables feature may be an option, but it seems a bit complicated for an operation that could be made simpler.

**Comment by daodennis** [comment]
Commenting here too in case it helps prioritize this more. I've looked at this bug multiple times in the last six months. A templating variable just won't help here.

**Comment by naughtyGitCat** [comment]
Commenting here too in case it helps prioritize this more. I've looked at this bug multiple times in the last six months. A templating variable just won't help here.

**Comment by nmcc1212** [comment]
Any updates?

**Comment by trallnag** [comment]
I've read a tip to just copy / duplicate the row directly via the JSON. But there is quite a big issue with this approach. After duplication / copying there will be panels with non-unique panel ids which will mess up your dashboard quite reliably.

**Comment by nmcc1212** [comment]
surely there's a better way of doing it though

**Comment by robinpecha** [comment]
Any progress?
