### ISSUE TITLE
Grafana 5.1.4 breaks ldap.toml conf host parameter

### ISSUE THREAD

**Issue by ernestgwilsonii** [grafana/grafana#12382]
Version 5.1.3 works (and many other releases)

Version 5.1.4 no longer honors ldap host.
**host = "10.1.2.3"**

Instead ldap now tries an of fails on **"127.0.0.1"**

grafana_grafana.1.6bozowarbaqm@swarm1-node5    | t=2018-06-22T12:23:54+0000 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 200 \"Network Error\": **dial tcp 127.0.0.1:389: connect: connection refused"**

What changed between Docker versions:
grafana/grafana:5.1.3
and
grafana/grafana:5.1.4

**Comment by torkelo** [comment]
Strange, nothing related to ldap & config loading changed.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/compare/v5.1.3...v5.1.4

**Comment by marefr** [comment]
Sounds related to fix of https://github.com/grafana/grafana-docker/issues/170. How are you providing configuration parameters when running your container?

**Comment by ernestgwilsonii** [comment]
5.2.0-beta3 does not have the issue.

5.1.1 = works
5.1.2 = works
5.1.3 = works
5.1.4 = broken <---
5.1.3 = works
5.2.0-beta3 = works

I will just start using 5.2.0-beta3 and higher.

**Comment by ernestgwilsonii** [comment]
5.2.0 non beta works too
Let's close this and not use 5.1.4

**Comment by marefr** [comment]
A 5.1.5 release will be available shortly for those not wanting to upgrade to 5.2.0 yet
