### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ennio1991** [grafana/grafana#12380]
Hi, I am using Grafana 5.1.0 with ClickHouse.
I am concerned that when a chart is exported, through developer tool of any browser, in the network tab is possible to see in clear the queries, the structure of the db and change the queries as well.
I am concerned also about the api that are open:
http://host:3000/api/datasources/proxy/1/?query=

Looks like that everybody can  run every query.

![screen shot 2018-06-22 at 12 49 52](https://user-images.githubusercontent.com/14088522/41773105-2d3cb90c-761b-11e8-8486-5d6fc7c137d4.png)

**Comment by torkelo** [comment]
This is how Grafana works, queries are built and issued by the browser (this required to support templating and dynamic queries), so a user with viewer role can technically issue any query against a data source. 

http://docs.grafana.org/administration/permissions/#data-source-permissions

If you need to isolate sensitive data you need to create a separate organization and add a new data source with credentials that only have access to this restricted data.
