### ISSUE TITLE
Graphite from/until syntax: moving time range of the fixed size in the past (Grafana 5.2)

### ISSUE THREAD

**Issue by alchuk** [grafana/grafana#12381]
Looks like Grafana doesn’t support such a fixed time interval as “From 10:00 AM the day before yesterday, Till 10:00 AM yesterday”. Using direct Graphite-web API this would look like “from=10:00+yesterday-1d&until=10:00_yesterday”

(https://graphite.readthedocs.io/en/0.9.15/render_api.html#from-until)

My case is a statistics file, which is downloaded and parsed only once a day and contains counters for the previous 24 hours period.

**Comment by daniellee** [comment]
This is possible using the time range relative ranges (https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/#time-units-and-relative-ranges):

https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&from=now-1d%2Fd-14h&to=now-1d%2Fd-14h

Sorry that the answer is two years later but might help someone else in the future. 

This expression is not that obvious it is taking the relative range for yesterday and then shifting it by doing minus 14h to get 10 a.m.
