### ISSUE TITLE
Bad legend values

### ISSUE THREAD

**Issue by Jackerg** [grafana/grafana#12389]
Hello, 

I'm facing a strange issue with Grafana v4.6.2 (I can't upgrade) : I've successfully imported values and dates in json format in a InfluxDB and I'm able to see every value on the "Graph" panels. However, when I display the legend, the max,min, current and total values are null whereas the curves show the good values. In addition, when I move my mouse over a certain date. I see the 5 metrics but without value. Here is a picture of my problem : 

![image](https://user-images.githubusercontent.com/37595297/41841742-61784eac-7869-11e8-89da-2ff1c6c7ff9f.png)

Same with the "Pie chart" panel : With 5 metrics, the pie displays but the legend is a complete mess. The min, max are wrong and it seems that metrics take the values of other metrics. 

![image](https://user-images.githubusercontent.com/37595297/41842033-125f6318-786a-11e8-8472-fc872825dafc.png)

Here, it's written 100 for info_violations whereas 100 is the max for the blocker_violations... 

I would appreciate any help, thanks in advance

**Comment by torkelo** [comment]
This is likey that your data is strings, make sure you store the numeric values in InfluxDB as numbers. There is an open issue to show a proper error and not just have it half working like this.

**Comment by anho** [comment]
@torkelo Sorry for bothering, but what about converting the values to numerical representations? We store additional data in Influx fields/tags which will be returned as strings as I can see in the network communication. After going through quite a bit of updates from 4.4 to 5.2 this "feature" - that used to work - is now a major obstacle.
