### ISSUE TITLE
Skipping TLS verify not possible using browser access option

### ISSUE THREAD

**Issue by datamonk** [grafana/grafana#12386]
Tested on latest stable version (5.1.4 – commit a5fe24fcc)
Tested data source: OpenTSDB
OS Used: RHEL 6.latest/7.2+

As of what it seems like the below commit, when setting up a data source, client TLS verification cannot be skipped using the "browser/direct" access method. This option is useful when deferring TLS verification to a custom/external reverse proxy. Without it, client connections are rejected before they reach the proxy.

Breaking Change: https://github.com/grafana/grafana/commit/c04d95f35f535354688d2549bcaab42492fc75fc

**Note:** There is a workaround using the GUI to enable "Skip TLS Verification" option with the browser based access method. Here are the steps:

1. Select "Server (Default)" access option to show all Auth options. (attached tls_option_aval1.png)

![tls_option_aval1](https://user-images.githubusercontent.com/1340871/41797939-e0e41e46-7639-11e8-9498-ea17a426d734.png)

2. Select  the "Skip TLS Verification" checkbox.

3. Go back to Access option and switch to "Browser". (attached browser_option_enabled1.png)

![browser_option_enabled1](https://user-images.githubusercontent.com/1340871/41797938-e0d09eb6-7639-11e8-8c25-a3fc4799c329.png)

Even though the option is hidden, the configuration still maintains and apply's the setting. Our environment currently leverage’s this method to continue using the later releases of Grafana. It would be much appreciated if the option issue was addressed prior to or at the same time as the mentioned workaround. :)

With browser access method saved with skip verify option.
`$ cd ${grafana_base}/data`
`$ ./sqlite3 grafana.db`

`sqlite> .headers ON`
`sqlite> .mode column`
`sqlite> SELECT json_data FROM data_source;`
`json_data`                                                                 
`--------------------------------------------------------------------------`
`{"keepCookies":[],"tlsSkipVerify":true,"tsdbResolution":1,"tsdbVersion":1}`
 
Thanks.

**Comment by bergquist** [comment]
Not sure I understand what you are trying to do..

When configuring the datasource to use `browser/direct` it means that your browser will send the requests to `https://datasource.com:3333` directly and not through Grafana. Grafana cannot disable TLS verification for https://datasource.com if the requests are sent from your browser.
