### ISSUE TITLE
Conditional panel

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#12391]
It would be awesome to be able to completely hide a panel or a row when all the data inside is missing. For instance, it would make sense to hide a graph showing JVM statistics for a host which doesn't run any java code.

In the graph panel we can hide a series wirh only nulls. I'm proposing to hide the graph itself if it doesn't contain any data

**Comment by torkelo** [comment]
Hi, 

Yes. Would be interesting. Closing this as it's similar to this feature request. 
https://github.com/grafana/grafana/issues/4470
