### ISSUE TITLE
Grafite timing out

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1239]
Hi Torkel,

I have a grafana/graphite setup. Sometimes, when I try to look at the data on a smaller, scale (clicking on a particular section of a chart, and picking the certain time frame), I get Internal server error from graphite. Do you think, if changing the timeout value on grafana end, would help fix this issue? Is there a timeout value when refreshing/loading data from data sources like graphite/opentsdb etc?

Thanks,

**Comment by gsaray101** [comment]
I do see this message from graphite:
 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

Is it possible to try again if you get "500 error". If I refresh the graph again, it works but not a good user experience. Is it possible to insert try again if 500 error in grafana?

**Comment by torkelo** [comment]
That is not a timeout (I think). Can you check the graphite server logs to see what is causing the error?

**Comment by gsaray101** [comment]
these are the errors: 

 File "/usr/local/lib64/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
[Wed Jan 07 11:09:25 2015] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/views.py", line 111, in renderView
[Wed Jan 07 11:09:25 2015] [error]     seriesList = evaluateTarget(requestContext, target)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 7, in evaluateTarget
[Wed Jan 07 11:09:25 2015] [error]     result = evaluateTokens(requestContext, tokens)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 18, in evaluateTokens
[Wed Jan 07 11:09:25 2015] [error]     return evaluateTokens(requestContext, tokens.expression)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 25, in evaluateTokens
[Wed Jan 07 11:09:25 2015] [error]     args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 18, in evaluateTokens
[Wed Jan 07 11:09:25 2015] [error]     return evaluateTokens(requestContext, tokens.expression)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 25, in evaluateTokens
[Wed Jan 07 11:09:25 2015] [error]     args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 18, in evaluateTokens
[Wed Jan 07 11:09:25 2015] [error]     return evaluateTokens(requestContext, tokens.expression)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
[Wed Jan 07 11:09:25 2015] [error]     return fetchData(requestContext, tokens.pathExpression)
[Wed Jan 07 11:09:25 2015] [error]   File "/opt/graphite/webapp/graphite/render/datalib.py", line 141, in fetchData
[Wed Jan 07 11:09:25 2015] [error]     raise Exception("Failed after %i retry! See: %s" % (settings.MAX_FETCH_RETRIES, e))
[Wed Jan 07 11:09:25 2015] [error] Exception: Failed after 2 retry! See: list assignment index out of range
[Wed Jan 07 11:09:25 2015] [error] Internal Server Error: /render
[Wed Jan 07 11:09:25 2015] [error] Traceback (most recent call last):

**Comment by torkelo** [comment]
Have not seen that before, but you might be able to solve it by changing: MAX_FETCH_RETRIES
