### ISSUE TITLE
Regarding tab based grouping of graphs on basis of user interest

### ISSUE THREAD

**Issue by avnivamsikrishna** [grafana/grafana#124]
Hi, While visualizing performance data, the amount of data (graphs) we present to user is influenced by comprehension ability of the user. Most of the times by presenting too many graphs we end up confusing the user (/ Dev) and the user loses focus ( decrease in the user Quality of Experience). I was wondering if Grafana supports a tab based grouping of data to be presented.  

Example: User clicks on View Basic Tab then we populate the basic graphs of category basic; if the user selects view advanced tab,  then ideally only the advanced group data would be shown.

Currently, on clicking Show SLA tab (refer the image below) I  am redirecting it to a new URL (adding a new ARG  current_url+ &type=foo) , this would however refresh the whole page and recalculate the targets and populates the data of type foo to the user context.

![screenshot from 2014-02-21 15 01 04](https://f.cloud.github.com/assets/6082425/2228423/11d65828-9adb-11e3-9aee-be276994b9c4.png)

Do you have suggestions of  solving the above use case in a better manner (which might not involve a page refresh, as it may disturb the user experience)

**Comment by torkelo** [comment]
implemented via dashboard links, https://github.com/grafana/grafana/issues/1944
