### ISSUE TITLE
How to create Presto plugin ?

### ISSUE THREAD

**Issue by thanhlv93** [grafana/grafana#12403]
Hello All, 

**What Grafana version are you using?**
Grafana v5.1.2 (c3c690e21)

**What datasource are you using?**
I try to create Presto datasource by use Postgest source code.

**What OS are you running grafana on?**
Ubuntu 16.04

**What did you do?**
I'm reading Postgest plugin source code and I wonder how can I create Presto plugin with this source .
I compared Postgrest plugin source code with Mysql plugin source code and it's not different to much so I think I can create Presto plugin with Postgest source code. 
After download source code and changed keywords,builtinFunctions, dataTypes in function SqlHighlightRules + changed the name of plugin, I moved this plugin to 

> /var/lib/grafana/plugins/presto

and restart grafana-server. 

> sudo service grafana-server restart

After that I login into http://localhost:3300 to add new datasource and I got an error : 

> Unable to dynamically transpile ES module A loader plugin needs to be configured via 
   `SystemJS.config({ transpiler: 'transpiler-module' })`. Instantiating 
    http://localhost:3300/public/plugins/presto/module.js Loading plugins/presto/module

Maybe I missed some step or some config , please tell me if you have any suggest.

**What was the expected result?**
Can query data from Hive through Presto

What happened instead?

Thank you.

**Comment by thanhlv93** [comment]
Anyone has suggest please tell me. Thank you

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by thanhlv93** [comment]
Thanks @torkelo , I created with link : https://community.grafana.com/t/how-to-create-presto-plugin/8310
Please help me.
