### ISSUE TITLE
Drag and drop icons will be carton, and seriously die

### ISSUE THREAD

**Issue by liyaqiu** [grafana/grafana#12409]
grafana-5.1.2-1.x86_64
os:centos6.7
datasource:Prometheus

Drag and drop icons will be carton, and seriously die

![](http://m.qpic.cn/psb?/V11cDoiY31og5v/cpJMaPjOXItOSdB1piTt0nAIVcxjP0jhQZWAlAIsH*8!/b/dDIBAAAAAAAA&bo=XQIDAQAAAAADB38!&rf=viewer_4)

**Comment by liyaqiu** [comment]
![](http://m.qpic.cn/psb?/V11cDoiY31og5v/*Ie*qeog2oK8HuA2WITYA..795eGogpDkJ27yJCcol4!/b/dDEBAAAAAAAA&bo=mQITAQAAAAADB6s!&rf=viewer_4)

**Comment by torkelo** [comment]
what? Please provide more detail. I see nothing wrong in your screenshot.
