### ISSUE TITLE
Login successful as "NULL" user.

### ISSUE THREAD

**Issue by Tautvydas3333** [grafana/grafana#12406]
### What Grafana version are you using?
Grafana v5.1.3
### What datasource are you using?
ZABBIX API
### What OS are you running grafana on?
Debian GNU/Linux (stretch)
### What did you do?
I connect directly to https://localhost/grafana/
### What was the expected result?
Unauthorized login and redirect to login page.
### What happened instead?
Login successful as "NULL" user.
![image](https://user-images.githubusercontent.com/29428142/41891941-11ecd450-791f-11e8-868d-875a4f422a09.png)

**Comment by torkelo** [comment]
Do you have anonymous access enabled?

**Comment by torkelo** [comment]
can you inspect your database? Looks like you have user with username "(null)"

**Comment by Tautvydas3333** [comment]
Anonymous access is commented
#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
;enabled = true

There is no user like "NULL", but every time I try to directly connect to https://localhost/grafana/ a "NULL" user is created.
![image](https://user-images.githubusercontent.com/29428142/41958571-22305290-79f3-11e8-934d-5c8060c12ab6.png)

I discovered what caused the problem, but I still do not know how to fix it in my situation. I am using both SSO and Local login, so I had to add 
![image](https://user-images.githubusercontent.com/29428142/41958738-a03797b6-79f3-11e8-8fd5-290467a3341b.png)
to my apache config because of SSO.

**Comment by torkelo** [comment]
Seem the user header grafana gets contains `(null)` string
