### ISSUE TITLE
Grafana Will not return Proper Dashboard ID (in response)after importing a new dashboard using API

### ISSUE THREAD

**Issue by MahadevG** [grafana/grafana#12404]
While importing the dashboard api is not returning Proper dashboard ID. For all the dashboard ID it provides id as 0 
If I check the dashboard using chrome devtools network tab I am able to some id(in increment order).

### What Grafana version are you using?
5.2.0-beta3 (previously using 5.1.4)

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Windows 10 pro

### What did you do?
Imported the dashboard using Grafana API

### What was the expected result?
Should be able to import the dashboard and as response it should return a dashboard ID

### What happened instead?
Able to import the dashboard but not getting proper dashboard ID. For all dashboard it gives ID=0

### If related to metric query / data viz:

```
import requests
url='http://admin:admin@localhost:3000/api/dashboards/import'
data='''{
"dashboard": {
"annotations": { ]
},
"editable": true,
"gnetId": null,
"graphTooltip": 0,
"id": null,
"iteration": 1529469422136,
"links":[],
"panels": [],
"refresh": "5s",
"schemaVersion": 16,
"style": "dark",
"tags": [],
"templating": {
"list": [ ]
},
"time": {
"from": "now-1h",
"to": "now"
},
"timepicker": {
"refresh_intervals": [ ],
"time_options": [ ]
},
"timezone": "Browser",
"title": "Template dfsad",
"uid": "uid1098",
"version": 1,
"__inputs": [
{
"name": "DATASOURCE",
"label": "CentralDataBase",
"description": "",
"type": "datasource",
"pluginId": "influxdb",
"pluginName": "InfluxDB"
}
],
"__requires": [
{
"type": "grafana",
"id": "grafana",
"name": "Grafana",
"version": "5.1.3"
},
{
"type": "panel",
"id": "graph",
"name": "Graph",
"version": "5.0.0"
},
{
"type": "datasource",
"id": "influxdb",
"name": "InfluxDB",
"version": "5.0.0"
},
{
"type": "panel",
"id": "singlestat",
"name": "Singlestat",
"version": "5.0.0"
}
]
},
"inputs": [
{
"name": "DATASOURCE",
"type": "datasource",
"pluginId": "influxdb",
"value": "CentralDataBase"
}
],
"folderId": 8,
"overwrite": false
}'''
headers={"Content-Type": 'application/json'}
response = requests.post(url, data=data,headers=headers)
print(response)
print(response.status_code)
print (response.text)
```

**Here is the respone**

```
Response [200]
200
{"pluginId":"","title":"Template dfsad","imported":true,"importedUri":"db/template-dfsad","importedUrl":"/d/uid1098/template-dfsad","slug":"","dashboardId":0,"folderId":8,"importedRevision":1,"revision":1,"description":"","path":"","removed":false}

```

**Comment by bergquist** [comment]
In 5.0 we introduced UID's for dashboards instead of numeric ID's since that makes it easier to share dashboards and keep the id/url. 

Seems like we missed to add UID in this response and still return an invalid ID.

**Comment by MahadevG** [comment]
Thanks @bergquist 
I was Using Dashboard ID to update Permission of a Dashboard using API. Now Can I do the same using Uid??

**Comment by MahadevG** [comment]
@bergquist 
Thanks for your reply.
According to [this ](http://docs.grafana.org/http_api/dashboard_permissions/)documentation    we can update user permission using Dashboard ID . If we don't get dashboard ID how can we restrict the permissions??
