### ISSUE TITLE
graphite/gfunc.ts: add sortBy ?

### ISSUE THREAD

**Issue by NotSqrt** [grafana/grafana#12400]
Hi,

I'm currently using grafana 5.1 with graphite 1.1.3.

`sortBy` is not listed in the "Sorting" submenu.
Is it supposed to be pulled automatically from the `/functions` graphite entrypoint ?

I've checked that it is present in that entrypoint.

Thanks !

**Comment by torkelo** [comment]
What Graphite version have you specified in the data sources settings view?

**Comment by NotSqrt** [comment]
`1.1.3`

**Comment by NotSqrt** [comment]
hmm I guess going back to the data source settings view and re-applying "Save and test" made grafana re-detect the version properly. I now see `SortBy` in the menu.
