### ISSUE TITLE
Implement support for plotting confidence interval bands

### ISSUE THREAD

**Issue by yati-sagade** [grafana/grafana#12410]
Grafana serves our graphing needs for most cases, except when there is time-series data with uncertainty around the data points. The usual way of plotting this uncertainty is to include suitable confidence interval bands in line charts (see [this post][1] for an example).

I am willing to help implement this feature unless it is already in the works (doesn't seem like it from my scanning of the issues list).

[1]: https://alesandrab.wordpress.com/2014/09/17/create-line-charts-with-confidence-bands/
Please include this information:
### What Grafana version are you using?
master
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Linux 64 bit

**Comment by ryantxu** [comment]
You can try using the 'fill below' to get a graph like that.

![image](https://user-images.githubusercontent.com/705951/41923738-891101b6-7968-11e8-818c-a54f608160c0.png)

See Display > Series overries > Fill below to:

![image](https://user-images.githubusercontent.com/705951/41923808-b5e96f52-7968-11e8-92d1-6b59bf08012c.png)

**Comment by torkelo** [comment]
duplicate / similar to this feature request, https://github.com/grafana/grafana/issues/516

**Comment by CrashLaker** [comment]
remember also to set fill = 0 under "Draw Options".
took me a while to realize this..
![image](https://user-images.githubusercontent.com/4432491/57465466-0d27a780-7255-11e9-9d5e-b379e7cc0024.png)
