### ISSUE TITLE
postgreSQL too many connection

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#12421]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.0.1
### What datasource are you using?
postgreSQL
### What OS are you running grafana on?
cloudfoundry

Is it 1 query open 1 connection? what is connection mechanism of postgreSQL data source?

![image](https://user-images.githubusercontent.com/13620253/41957871-ec6061a0-7a1a-11e8-8e6c-23bf5d994708.png)

**Comment by daniellee** [comment]
Closing this issue as there have been no comments for two years and it doesn't seem to be a common problem. If this is still an issue then we can re-open it.
