### ISSUE TITLE
[Feature Request] Disable Admin (super user)

### ISSUE THREAD

**Issue by joek** [grafana/grafana#12423]
### What did you do? - I tried to disable the admin user. Everything I tried, was not working. Based on community forum, this is not possible (https://community.grafana.com/t/disable-admin-account/5600)

As we are using OAuth for authentication, I would like to disable the admin user or at least disable the admin login via configuration. As we are automatically setting up grafana for each kubernetes instance, we are running, the manual process described in the community ticket is not working. 

If this change is appreciated, I am willing to contribute a fix.

**Comment by bergquist** [comment]
Could you give the grafana instances a throwaway password for the admin account?

**Comment by torkelo** [comment]
there is nothing magical about the default admin user, you can just to get Server Admin > Users and delete this user.

**Comment by joek** [comment]
@bergquist I could, but the problem is, then I have to make sure it is rotated frequently. This is not possible (as far as I understood the documentation) as admin_password is set once at first start (due to documentation)

@torkelo Agree, the point is, it is done via UI. We will have many instances in the future and do not like to do this on every new instance. (If estimations are right, we will have > 100 of them)

**Comment by joek** [comment]
@torkelo Maybe it is possible to prevent creating the user right at startup?

**Comment by torkelo** [comment]
maybe with a new setting, but then you won't have any super admins, so no user can ever become super 
 (instance) admin.

**Comment by Asgoret** [comment]
@torkelo It's very sad that you can't disable admin user. It't critical a vulnerability. Did it fixed in 7+ version? Or ugly workaround with passwords is only option?
