### ISSUE TITLE
Avoid 'Page Not Found' flicker when loading custom home dashboard

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12429]
When running on a slow connection, I sometimes see the 'Page not found' dialog before anything loads:
![notfound 37](https://user-images.githubusercontent.com/705951/42002484-b9aa373e-7a67-11e8-8dd0-732ebda69d84.png)

Here is a not so great recording to give you an idea:
![close](https://user-images.githubusercontent.com/705951/42002504-d3660e82-7a67-11e8-9c22-69e07472e6f5.gif)

Perhaps this is an `ng-if` vs `ng-show` issue?  or a react equivalent?  This is only an issue when I am connecting over slow networks.

**Comment by torkelo** [comment]
what is the url your loading?

**Comment by torkelo** [comment]
unable to replicate, what auth & settings & url  (any detail about setup) would be helpful. If you try incognito mode can you replicate it there?

**Comment by ryantxu** [comment]
I am unable to replicate on a local instance or notice anything when accessing computer from local network.  However the flash appears when I access it:
* remote slow network through VPN
* phone through VPN

The instance is setup with:
* google authenticaiton
* nginx proxy running at:  https://ourhost/grafana
* loading url: ` https://ourhost/grafana` that redirects to: ` https://ourhost/grafana/d/000000082/home-dashboard?orgId=1`

NOTE, i do not see the flicker when loading ` https://ourhost/grafana/d/000000082/home-dashboard?orgId=1` directly

**Comment by ryantxu** [comment]
@torkelo I found a setting that toggles the behavior!

If the home dashboard is set to 'Default' it loads OK.  When I change it to something else, the 'Not Found' flash happens.

![image](https://user-images.githubusercontent.com/705951/42098602-a093a41a-7bbb-11e8-981a-baf8d6ad3de5.png)

**Comment by torkelo** [comment]
Strange , the play site has that option set and was where I tried to replicate it. Maybe it’s the sub path that is causing it, since play site does not have a sub path and your setup has
