### ISSUE TITLE
Last data point value differs from others (graphite)

### ISSUE THREAD

**Issue by zasca** [grafana/grafana#12426]
### What Grafana version are you using?
3.1.1
5.0.4
### What datasource are you using?
graphite
### What OS are you running grafana on?
ubuntu 14.04
### What did you do?
Click "Refresh" > chrome send request https://test.local/api/datasources/proxy/28/render:
```
Form Data:
  target: aliasByNode(scale(scale(keepLastValue(Test.Stat.Money.cost), 1.18), 0.000001), 3)
  form: -24h
  until: now
  maxDataPoints: 1853
```
### What was the expected result?
Grafana should return exactly the same data as graphite on similar [request](http%3A%2F%2Ftest.local%3A8080%2Frender%2F%3Ftarget%3DaliasByNode%28scale%28scale%28keepLastValue%28Test.Stat.Money.cost%29%2C%201.18%29%2C%200.000001%29%2C%203%29%26from%3D-1d%26format%3Djson):
```
[{"target": "cost", "datapoints": [[1681.76775734, 1530007050], ..., [1681.76775734, 1530093350], [1681.76775734, 1530093400]]}]
```
![grafana_bug1_2](https://user-images.githubusercontent.com/12932949/41971712-3491d45c-7a31-11e8-8eb6-9d387d8f474e.png)

### What happened instead?
Last data point value differs from others (sometimes only):
```
[{"target": "cost", "datapoints": [[1681.7677573400001, 1530007050], ..., [1681.7677573400001, 1530093350], [1681.76775734, 1530093400]]}]
```
![grafana_bug1](https://user-images.githubusercontent.com/12932949/41970277-02de9288-7a2c-11e8-9755-a4ff0b74d971.png)

But sometimes all looks good (except of increasing of all values on 10^−13).

**Comment by zasca** [comment]
I did some more research after posting of the issue.
And it turned out that this is a bug of graphite, when set [maxDataPoints](https://graphite.readthedocs.io/en/latest/render_api.html#maxdatapoints).

**Comment by bergquist** [comment]
Closing this since its graphite related. Thank you for following up! :)
