### ISSUE TITLE
Settings view not found - Grafana Dashboard

### ISSUE THREAD

**Issue by jakirpatel** [grafana/grafana#12432]
Grafana Version: 5.1.4
Datasource: Not configured
OS: CentOS 7

What I did?:

The grafana is configured with LDAP. I removed the default organization Main Org. The system admin menu disappeared and admin user was not able to create any other organization from UI. 

Expected Result: 
Admin should create the organization if there is no organization present. Also, the first organization should be always created with Org Id:1. Or I can modify the organization id as well. 

What happened:
Not able to create an organization through UI. Even I used API to create it but I was not able to create the default organization by org_id 1.

As the org_id 1 is not present my other LDAP users given me the error of Invalid username or password with userid:0 org_id=0

**Comment by torkelo** [comment]
If you removed the default org you must create a New org using the Grafana super admin , and specify the New org id in you LDAP tomt file , New org ids are incremented so you cannot get a org with id 1 again

**Comment by jakirpatel** [comment]
Can you reproduce this issue? I am not confident about creating the Org. with super admin user through UI.

**Comment by torkelo** [comment]
Try Grafana v5.2 we fixed an issue in that release (I think) so that system admin menu still shows even if your now admin in an org (but still super admin). 

Just login as your grafana super admin user & to so server admin > orgs > new
