### ISSUE TITLE
5.2 no longer reports errors before crashing

### ISSUE THREAD

**Issue by SMillerDev** [grafana/grafana#12438]
### What Grafana version are you using?
5.2.0 official RPM
### What datasource are you using?
None
### What OS are you running grafana on?
Latest CentOS 7 version.
### What did you do?
Made a mistake in the datasource provisioning configuration
### What was the expected result?
Errors in the logs and grafana shutting down
### What happened instead?
Grafana just shut down without any mention of an issue.

### More info
Downgrading to the 5.1.4 RPM restores the logging as I expect it to happen.

**Comment by torkelo** [comment]
what log settings do you use? default file log or console/std out?

**Comment by SMillerDev** [comment]
I'm using the default file log (/var/log/grafana/grafana.log) at the default level (info)

**Comment by torkelo** [comment]
and can you provide any details on the crash you encountered? Any way to replicate it?

**Comment by SMillerDev** [comment]
So step by step replication would be something like:

1. Install 5.1.x
2. Set up datasource provision with an invalid yaml file
3. Observe error in logs and failure to (re)start grafana
4. Upgrade to 5.2
5. Observe a lack of errors and failure to (re)start grafana

**Comment by torkelo** [comment]
I can replicate it, will fix! thanks for reporting this!

**Comment by SMillerDev** [comment]
You're very welcome. Thanks for the hard work!
