### ISSUE TITLE
api:api/alerts

### ISSUE THREAD

**Issue by WB-jastme** [grafana/grafana#12436]
version 4.6.3  api: api/alerts          i can get data like this

`{'dashboardId': 22, 'state': 'ok', 'dashboardUri': 'db/bao-jing', 'name': 'slave', 'evalData': None, 'evalDate': '0001-01-01T00:00:00Z', 'executionError': '', 'id': 8, 'newStateDate': '2018-05-09T07:57:12+08:00', 'message': 'mysql', 'panelId': 9}`
the message field  exists

Version 5.1.3   the meesage field was removed , how can i get it?

**Comment by torkelo** [comment]
if you access the alert via the api/alerts/:id route

**Comment by WB-jastme** [comment]
thanks,i saw it in docs.
