### ISSUE TITLE
Grafana not attaching images to alert e-mails

### ISSUE THREAD

**Issue by PedroD** [grafana/grafana#12445]
Grafana Version: 5.2.0-pre1

Settings configuration:

```
(...)
#################################### External Image Storage ##############
[external_image_storage]
# You can choose between (s3, webdav, gcs, azure_blob, local)
provider = 

[external_image_storage.s3]
bucket_url =
bucket =
region =
path =
access_key =
secret_key =

[external_image_storage.webdav]
url =
username =
password =
public_url =

[external_image_storage.gcs]
key_file =
bucket =
path =

[external_image_storage.azure_blob]
account_name =
account_key =
container_name =

[external_image_storage.local]
# does not require any configuration

```

Logs when an e-mail is sent:

> INFO[06-28|13:13:46] New state change                         logger=alerting.resultHandler alertId=3 newState=alerting prev state=ok
> INFO[06-28|13:13:46] Rendering                                logger=rendering path="d-solo/_33lOWvik/sislite-showroom?panelId=6"
> INFO[06-28|13:13:49] uploaded                                 logger=alerting.notifier url=
> INFO[06-28|13:13:49] Sending alert notification to            logger=alerting.notifier.email addresses=[xxxxxxxxxxxxxxxxx@gmail.com]

The resulting e-mail has no rendered screenshot of the panel attached.

What is going on?

**Comment by petemyron** [comment]
does it have a place holder for the image? I'm having trouble with the (under-documented) rendering api where grafana is timing out while supposedly drawing the image. I wonder if it's related.

Grafana says:
```Jun 28 15:46:57 grafana docker[32616]: t=2018-06-28T15:46:57+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/sitespeed-page-details?refresh=15m&orgId=1&var-group=31&var-page=1000&var-browser=chrome&var-connectivity=All&panelId=2&from=now-6h&to=now&width=1024&height=600&tz=UTC-08%3A00"
Jun 28 15:47:38 grafana docker[32616]: t=2018-06-28T15:47:38+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=6 uname=blah@blah.com method=GET path=/render/dashboard-solo/db/blah status=500 remote_addr=blah.blah.blah.blah time_ms=90012 size=1767 referer=
Jun 28 15:47:38 grafana docker[32616]: t=2018-06-28T15:47:38+0000 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"
```

That last `signal killed` is probably from nginx in front of grafana

nginx says:
```Jun 28 15:47:08 grafana docker[26451]: 2018/06/28 15:47:08 [error] 9#0: *436785 upstream timed out (110: Connection timed out) while reading response header from upstream, client: blah.blah.blah.blah, server: grafana.blah.io, request: "GET /render/dashboard-solo/db/blah?orgId=6&panelId=50&from=1530113882902&to=1530200282902&width=1000&height=500&tz=UTC-07%3A00&timeout=90 HTTP/1.1", upstream: "http://blah.blah.blah.blah:3000/render/dashboard-solo/db/blah?orgId=6&panelId=50&from=1530113882902&to=1530200282902&width=1000&height=500&tz=UTC-07%3A00&timeout=90", host: "grafana.blah.io"
Jun 28 15:47:08 grafana docker[26451]: 172.58.41.183 - - [28/Jun/2018:15:47:08 +0000] "GET /render/dashboard-solo/db/blah?orgId=6&panelId=50&from=1530113882902&to=1530200282902&width=1000&height=500&tz=UTC-07%3A00&timeout=90 HTTP/1.1" 504 183 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0"
```

In my case, I've also tried with the newer (?) render api format of `/render/d-solo/[UID]/blah...`

I'll file a bug for the above, but just curious if your logs show the same.

**Comment by PedroD** [comment]
I know very little about this rendering api. The only logs that show up are the ones I've posted above, and I have made no configurations towards changing the way this api works, because [here](http://docs.grafana.org/alerting/notifications/#email) it is said:

> To enable email notifications you have to setup SMTP settings in the Grafana config. Email notifications will upload an image of the alert graph to an external image destination _if available_ **or fallback to attaching the image to the email**. Be aware that if you use the local image storage email servers and clients might not be able to access the image.

So I assumed I should be getting the images attached in the alert e-mails. But I am not, and the only useful info I could get was those logs. I found no error logs.

**Comment by marefr** [comment]
@PedroD what operating system are you using and how are you running Grafana? If possible, please try out Grafana 5.2.0 stable since you seem to be using a nightly build of Grafana (5.2.0-pre).

Please start with enable debug logging of renderer:

```
[log]
filters = png-renderer:debug
```

Also, with the panel in question select Share -> Direct link rendered image - does that work?

**Comment by nutchalum** [comment]
I've a problem with this API too. However, I'm using LINE Notify instead.
It seems like the problem is there both 5.2.0 and 5.2.1
When I switch back to 5.1.2, it works.

**Comment by nutchalum** [comment]
@marefr No, there aren't from an alert. I just tried what you said
`Share -> Direct link rendered image - does that work?` and the result is no, it does not work

**Comment by marefr** [comment]
@nutchalum please open a bug report then and include details about your OS, panel type in use.

**Comment by torkelo** [comment]
t=2018-07-24T05:43:11+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"

This could be caused by running in a container with not enough RAM for phantomjs.

**Comment by battlecow** [comment]
For those coming from Google for this error and utilizing the Prometheus operator manifest, 200meg limit is not enough apparently and causes this issue.  After increasing memory limit all is well.
