### ISSUE TITLE
how can show the log on console?

### ISSUE THREAD

**Issue by yue6121** [grafana/grafana#12443]
- What Grafana version are you using? 5.1.3
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? Ubuntu 16.04
- What problem?
**how can show the log on console?**
 ```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
mode = console file

# Either "debug", "debug", "warn", "error", "critical", default is "debug"
level = debug

# optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug
filters =

# For "console" mode only
[log.console]
level = debug

# log line format, valid options are text, console and json
format = console

# For "file" mode only
[log.file]
level = debug

# log line format, valid options are text, console and json
format = text

# This enables automated log rotate(switch of following options), default is true
log_rotate = true

# Max line number of single file, default is 1000000
max_lines = 1000000
```

I want to see  client.go log with debug on console?but how ?I can not see these messages below.
```
	clientLog.Debug("Executing multisearch", "search requests", len(r.Requests))

	multiRequests := c.createMultiSearchRequests(r.Requests)
	res, err := c.executeBatchRequest("_msearch", multiRequests)
	if err != nil {
		return nil, err
	}

	clientLog.Debug("Received multisearch response", "code", res.StatusCode, "status", res.Status, "content-length", res.ContentLength)

	start := time.Now()
	clientLog.Debug("Decoding multisearch json response")

	var msr MultiSearchResponse
	defer res.Body.Close()
	dec := json.NewDecoder(res.Body)
	err = dec.Decode(&msr)
	if err != nil {
		return nil, err
	}

	elapsed := time.Now().Sub(start)
	clientLog.Debug("Decoded multisearch json response", "took", elapsed)
```

**Comment by marefr** [comment]
You'll need to upgrade to Grafana v5.2.0 first since Elasticsearch backend implementation was introduced there.

**Comment by yue6121** [comment]
thank you , now I uphrade to Grafana V5.2.0 already. I build it with source code, I want to debug the backend code, I had config the .ini file with debug level ,but I can not see  the debug message on console, I need some help now , thanks.

**Comment by yue6121** [comment]
I build grafana with source code,now I want to debug the backend code, I had config the .ini file with debug level ,but I can not see the debug message on console, I need some help now , thanks. 
![11](https://user-images.githubusercontent.com/8063831/42081076-1498258e-7bb7-11e8-91a5-2e808e0b44b8.png)

the backend is run by  `bra run`
![22](https://user-images.githubusercontent.com/8063831/42081088-1e0bbbc6-7bb7-11e8-9666-d07302218624.png)

Can you tell me how to do? Thank you!

**Comment by marefr** [comment]
The elasticsearch backend code is only executed for evaluating alert rules at the moment. When you render graphs in Grafana the frontend code is solely used. We want to change this eventually and make it solely a backend implementation, but no idea of when this will happen.

**Comment by yue6121** [comment]
I set level=debug in .ini file, bug the debug messages were not print on console?

**Comment by marefr** [comment]
How are you executing your elasticsearch queries? Thru alerting? As I wrote earlier you wont get any debug messages if you only render a graph in Grafana UI since the backend elasticsearch is not in play then.

**Comment by yue6121** [comment]
not alerting. Only query data from es.
![popo 201872205145](https://user-images.githubusercontent.com/8063831/42164933-d34f660c-7e39-11e8-8828-fa9d58a1c4f8.png)

**Comment by yue6121** [comment]
did client.go work when I query data from es?
![img20180702_204706](https://user-images.githubusercontent.com/8063831/42165143-2509f48a-7e3a-11e8-9269-6a96c27b7902.png)

**Comment by marefr** [comment]
Please read my comments. **You wont get any debug messages if you only render a graph in Grafana UI**. You need to create an alert rule and when that alert rule is evaluated the backend elasticsearch code will be executed and you'll see debug log messages.

**Comment by yue6121** [comment]
I got it, Thanks a lot!
