### ISSUE TITLE
'direct link rendered image' times out

### ISSUE THREAD

**Issue by petemyron** [grafana/grafana#12446]
### What Grafana version are you using?
5.0.3

### What datasource are you using?
influx, elasticsearch

### What OS are you running grafana on?
ubuntu 16.04

### What did you do?
1. create new graph panel
2. leave the default, 'test data: random walk' datasource
3. click 'direct link rendered image' under stare panel
4. example url: `https://blah.io/render/d-solo/000000023/blah?orgId=6&panelId=56&from=1530113882902&to=1530200282902&width=1000&height=500&tz=UTC-07%3A00`

Other details:
* notice there's no `&fullscreen` at the end, a la #12104 
* I've also tried the older formats for rendering, which, IIRC, are something like: `/render/dashboard-solo/[uid]/[dashboard name]`, `/render/dashboard-solo/[dashboard name]`

### What was the expected result?
png image is displayed

### What happened instead?
nginx in front of grafana returns a 504 gateway timeout, grafana logs show 500.

### If related to metric query / data viz:
The example here shows the `test data: random walk` datasource, but I've tried influx and elasticsearch with real data, too.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

grafana says:
```
Jun 28 15:47:38 grafana docker[32616]: t=2018-06-28T15:47:38+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=6 uname=blah@blah.com method=GET path=/render/dashboard-solo/db/blah status=500 remote_addr=blah.blah.blah.blah time_ms=90012 size=1767 referer=
Jun 28 15:47:38 grafana docker[32616]: t=2018-06-28T15:47:38+0000 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"
```
 
nginx says:
```
Jun 28 15:47:08 grafana docker[26451]: 172.58.41.183 - - [28/Jun/2018:15:47:08 +0000] "GET /render/dashboard-solo/db/blah?orgId=6&panelId=50&from=1530113882902&to=1530200282902&width=500&height=500&tz=UTC-07%3A00&timeout=90 HTTP/1.1" 504 183 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0"
```

**Comment by marefr** [comment]
Would recommend you to upgrade to latest Grafana v5.2.0. Been a lot of fixes regarding rendering and scrollbars after 5.0.3 up to 5.2.0 - see [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md). Closing this for now. Will reconsider open again if you experience the same problem on later version.
