### ISSUE TITLE
[Feat Req] Elasticsearch Adhoc filter query by query_string vs match_phrase

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#12447]
Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
The adhoc query builder for Elasticsearch Data Source uses match_phrase.  If instead used query_string, would provide enhanced query capabilities with adhoc queries (multiple match options per selected field, OR, grouped, wildcard), allowing a greater use of the Elasticsearch query capabilities, while maintaining the standard layout of the Adhoc query filters.  Today, to use the more complex queries, you must edit each panel's Metric-Query-Lucene Query field to match, which is labor intensive for each dashboard panel.

We have been doing this for sometime with our large Elasticsearch cluster, but was waiting until after ES Alerting was released, to ensure there was no impact.  Will submit a PR.

This was one of the most requested changes by our team related to using Grafana with Elasticsearch.

Ref:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

**Comment by davewat** [comment]
![github1](https://user-images.githubusercontent.com/35579731/42061752-30a359a6-7af9-11e8-8564-fb6a20e7a1af.png)
 Example of advanced Elasticsearch query capability.

**Comment by gretamosa** [comment]
Related #10918

**Comment by Elfo404** [comment]
I'm not really sure about it, but we may already have this feature.

**Comment by Elfo404** [comment]
given the way adHoc filters currently work, I'm not sure this would add much value. 
As also mentioned in https://github.com/grafana/grafana/pull/12450 probably the best way to this for now is by using a variable.
