### ISSUE TITLE
Latest Grafana 5.2.0 does not work with NetXMS data source plugin

### ISSUE THREAD

**Issue by ernestgwilsonii** [grafana/grafana#12440]
The NetXMS Grafana data source plugin does not work (it gives an error and won't load the data source plugin page correctly).

I run Grafana in a container and deploy via Docker Compose, so my environment is controlled carefully.

History:
Grafana 5.1.2 = works ok with NetXMS data source plugin
Grafana 5.1.3 = works ok with NetXMS data source plugin
Grafana 5.1.4 = Grafana folks broke LDAP, could not use this version
Grafana 5.2.0 = LATEST (adds fixes needed for other stuff I use) <-- NetXMS data source plugin fails to load

Error:

Plugin Error
Failed to fetch Instantiating https://newen008-grafana.pims.presidio.com/public/vendor/plugin-css/css.js Loading https://newen008-grafana.pims.presidio.com/public/vendor/plugin-css/css.js Instantiating https://newen008-grafana.pims.presidio.com/public/plugins/radensolutions-netxms-datasource/css/query-editor.css!https://newen008-grafana.pims.presidio.com/public/vendor/plugin-css/css.js Loading https://newen008-grafana.pims.presidio.com/public/plugins/radensolutions-netxms-datasource/query_ctrl.js Loading plugins/radensolutions-netxms-datasource/module

This leaves us in a bad position.
I need Grafana 5.2.0 for the latest fixes for my other stuff (Elastic)
but
Only Grafana 5.1.3 (and older) works with the NetXMS data source plugin.

REF: https://track.radensolutions.com/issue/NX-1457
and
REF: https://www.netxms.org/forum/general-support/latest-grafana-5-2-0-does-not-work-with-netxms-data-source-plugin/
![netxms-grafana-plugin-error](https://user-images.githubusercontent.com/6879787/42032720-7fb48f02-7aa8-11e8-8d46-e653762f75ce.png)

**Comment by marefr** [comment]
Works for me. Installed latest version of NetXMS 1.1.0. Add datasource and selecting NetXMS. Everything loads as expected, see screenshot:

![image](https://user-images.githubusercontent.com/1668778/42034582-cb98296e-7ae0-11e8-83bf-27e5e2226506.png)

**Comment by ernestgwilsonii** [comment]
did attempt manually via:
grafana-cli plugins install radensolutions-netxms-datasource
and that did not help.

My normal install is automated using Docker Compose and bind mounting:

# Create the bind mount for Grafana 
mkdir -p /opt/grafana
cp ldap.toml /opt/grafana/
chown -R 472:472 /opt/grafana
chmod a+rw -R /opt/grafana

# docker-compose.yml
version: '3.4'

services:

  # Grafana: https://hub.docker.com/r/grafana/grafana/
  grafana:
    image: grafana/grafana:5.2.0
    hostname: grafana
    environment:
      - GF_SERVER_PROTOCOL=http
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_CONFIG_FILE=/var/lib/grafana/ldap.toml
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,percona-percona-app,raintank-kubernetes-app,ntop-ntopng-datasource,natel-plotly-panel,camptocamp-prometheus-alertmanager-datasource,vonage-status-panel,fetzerch-sunandmoon-datasource,radensolutions-netxms-datasource
    volumes:
      - type: bind
        source: /opt/grafana
        target: /var/lib/grafana
    networks:
      - logging-net1
    ports:
      - mode: host
        target: 3000
        published: 3000
    deploy:
      labels:
        local.description: "Grafana"

networks:
  logging-net1:



# Deploy to Docker
############
# Run Graylog on the Swarm
docker stack deploy -c docker-compose.yml grafana
# Verify
docker service ls | grep grafana

Then login to Grafana and try to add a new NetXMS data source and boom (see attached screen capture).
Note: The same docker-compose.yml above works fine with older versions of the Grafana Docker image, only changing one line:
    image: grafana/grafana:5.1.2  <--works
    image: grafana/grafana:5.1.3  <--works
    image: grafana/grafana:5.2.0  <--fails as described
![netxms-grafana-plugin-error](https://user-images.githubusercontent.com/6879787/42093234-9ad1c68e-7b79-11e8-8a54-74c45af33996.png)

**Comment by marefr** [comment]
Have tried an instance on hosted Grafana which should be similar in setup with proxy and https - that also works as expected with NetXMS.

What url are you browsing grafana on when receiving that error? I have no problem browsing http://localhost:3000/public/vendor/plugin-css/css.js. If you cannot browse `https://<your host>/public/vendor/plugin-css/css.js` I would say you have missed something in in your proxy configuration.

**Comment by ernestgwilsonii** [comment]
image: grafana/grafana:5.2.1 works!

Thanks for everyone's help!
I guess we can close this.

**Comment by marefr** [comment]
That's very strange. The only thing I can imagine is that you're using the authproxy and has whitelisting of IP addresses enabled or that you've got something cached in your browser. Glad 5.2.1 works!
