### ISSUE TITLE
dashlist right margin issues

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12457]
In a recent master build, I am seeing this:

![image](https://user-images.githubusercontent.com/705951/42081058-be34120c-7b84-11e8-8347-2a4610c2125a.png)

It used to have padding on the right as well the left

**Comment by marefr** [comment]
Looks as expected (with padding to the right) for me. Maybe one of your plugins overriding the css? 

![image](https://user-images.githubusercontent.com/1668778/42082181-9d00393c-7b87-11e8-9e49-f952c7f37490.png)

**Comment by ryantxu** [comment]
thanks -- very possible!

I checked on https://play.grafana.org/d/000000012/grafana-play-home?orgId=1  but did not recognize the panels without background
