### ISSUE TITLE
MS SQL Server connection forcibly closed

### ISSUE THREAD

**Issue by drjaydenm** [grafana/grafana#12455]
### What Grafana version are you using?
grafana-5.3.0-22522pre1
### What datasource are you using?
MS SQL Server
### What OS are you running grafana on?
Windows 10 x65
### What did you do?
Trying to setup the MS SQL datasource
### What was the expected result?
The connection test succeeds and the connection can be queried
### What happened instead?
The connection test reports success the first time only. Any subsequent test fails with the message:

`read tcp 172.xx.xx.xxx:51000->172.xx.xx.xxx:1433: wsarecv: An existing connection was forcibly closed by the remote host.`

Any queries for metrics also report this error.

We have checked all firewalls and there is nothing being denied. We can connect to this SQL server on the same machine from other applications.

**Comment by marefr** [comment]
What version of SQL server are you using? `select @@version`

**Comment by drjaydenm** [comment]
Running `select @@version` returns the following

`Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)`

**Comment by drjaydenm** [comment]
It looks like this issue is actually caused by the MSSQL driver being used. I did a little bit of digging and found this [issue](https://github.com/denisenkom/go-mssqldb/issues/177).
Changing to using an IPv4 address instead of a DNS name fixed the issue for us.

**Comment by marefr** [comment]
Thanks for letting us know.

**Comment by godrose** [comment]
@drjaydenm Where exactly did you make the change? I'm hitting the same issue. Thanks

**Comment by williamvm** [comment]
make sure tcp/ip protocol is enabled for your sqlserver. Use .mmc configuration manager to check and change. [Here](https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-configuration-manager?view=sql-server-2017) is more details how to start configuration manager for your version of SQL Server.

![sqlserver-configurationmanager](https://user-images.githubusercontent.com/24420646/54883885-c3ccf580-4e6a-11e9-886c-6bf06cb3be65.jpg)
