### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by 121watts** [grafana/grafana#12453]
[here](https://github.com/grafana/grafana/blob/6281910591747732db1d57a8422d5ec15c9b6148/public/app/partials/login.html#L92) and [here](https://github.com/grafana/grafana/blob/fb2b2c9f656f9d8f894edea70418b78efd3f22f3/CHANGELOG.md)

"promted" is probably meant to be "prompted"? 

😸

**Comment by bergquist** [comment]
Any chance you want to make your first pull request? :)

**Comment by bergquist** [comment]
Nevermind. I'll fix those myself. Thank you for reporting! :)
