### ISSUE TITLE
Templating should be supported for Custom Datasources

### ISSUE THREAD

**Issue by tmonk42** [grafana/grafana#1245]
Custom datasource plugins should be able to make use of Templating features in Grafana.

**Comment by codyaray** [comment]
Another +1 for KairosDB here

**Comment by omar-eyeviewdigital** [comment]
+1

**Comment by tecbea** [comment]
KairosDB +1

**Comment by mikkoibisense** [comment]
+1!

**Comment by tamsky** [comment]
KairosDB ++

**Comment by justmedude** [comment]
+1

**Comment by torkelo** [comment]
It is supported, just that the custom data sources needs to implement metricFindQuery method
