### ISSUE TITLE
Grafana folders APIs don't seem to work with "General" folder

### ISSUE THREAD

**Issue by gavares** [grafana/grafana#12467]
### What Grafana version are you using?
5.0.4

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Oracle Enterprise Linux

### What did you do?
I'm attempting to write a script to synchronize Grafana instances in multiple regions. As part of that, I need to synchronize folders. Getting a list of all folders from `/api/folders?limit=100` returns all folders except for the `General` folder.

Thinking `General` is special, I attempted to fetch the folder explicitly from: `/api/folders/0` as documented by the API. This does not work either. In fact, I can't fetch an folder using that path construction and figured out by trial and error that: `/api/folders/id/4` works for some folder with id 4 that does exist in my instance. Using id 0 for the General folder still does not work.

### What was the expected result?
Listing all folders should include the "General" folder.
Fetching the general folder by id should work
API docs should properly reflect the path for fetching a folder by id

### What happened instead?
The general folder is not included in the listing of all folders
Fetching a folder by Id as documented in the API does not work
Inserting path segment `id` like `/api/folders/id/:id` did fetch some folders
Inserting path segment `id` like `/api/folders/id/0` did not fetch the General folder

**Comment by marefr** [comment]
The General folder will always exist on all Grafana instances. The General folder is special by purpose and by design we don't return that in the HTTP API. We have currently no plans of changing this. Please use the folder/dashboard search api if you want to filter out which dashboards belong to a certain folder.

**Comment by gavares** [comment]
@marefr That seems to address the part about not finding the "General" folder but there is still the issue of the incorrect documentation for the fetch folder api

**Comment by marefr** [comment]
Yes you're right, will update the documentation. Thanks
