### ISSUE TITLE
Grafana shows the error: Value column must have numeric datatype, column: value type: string value

### ISSUE THREAD

**Issue by meier81** [grafana/grafana#12463]
### What Grafana version are you using?
Version 5.2.0
### What datasource are you using?
mySQL
### What OS are you running grafana on?
Raspberry Pi 3 with Stretch, up to date
### What did you do?
Updated Grafana from V5.0.4 to V5.2.0
### What was the expected result?
In Grafana all Dashboards Shows the error: Value column must have numeric datatype, column: value type: string value

My Metrics-Config:
SELECT
  UNIX_TIMESTAMP(TIMESTAMP) as time_sec,
  VALUE as value,
  "Temperatur" as metric
FROM history
WHERE READING="temperature" AND DEVICE="Fuehler_Aussen" AND $__timeFilter(TIMESTAMP)

The structure of my mySQL-Database is enclosed.

 
![mysql database](https://user-images.githubusercontent.com/40598096/42088545-23f1c886-7b9a-11e8-96a2-c38182eb4ce0.PNG)

[JSON.txt](https://github.com/grafana/grafana/files/2149006/JSON.txt)

**Comment by torkelo** [comment]
as the error message says, the value column your query returns must be a numeric type, try casting your string to a number in your query

**Comment by meier81** [comment]
Can anybody help me about converting string to number?

**Comment by muutech** [comment]
@meier81   cast(VALUE as UNSIGNED) as value
@torkelo for table panels using time series, would be nice to be able to print VARCHAR type metrics, would you consider for future releases remove this constraint? thanks and merry xmas!

**Comment by meier81** [comment]
Hello everybody,
my problem fixed with the following change:
CONVERT(VALUE, INTEGER) as value

**Comment by sreedhar-xcube** [comment]
Hi Meier,

   I am also having similer type of issue. I defined one variable and its Type is query. and enable selection option as "multivalue".
 Iam using mysql as data source.
Query:
SELECT
  created_date AS "time",
  CONVERT($ReportColumns, INTEGER) as value
FROM vsa_chat_report_daily
ORDER BY created_date


Final generated sql query : 
"SELECT created_date AS "time", CONVERT('executed_skills', INTEGER) as value FROM vsa_chat_report_daily ORDER BY created_date"

Please help

**Comment by MalteMagnussen** [comment]
I am having a similar type issue. 
Here is the statement in workbench: 
![image](https://user-images.githubusercontent.com/11192971/94677969-06a04100-031e-11eb-9c03-f30cf7bfd244.png)
And here it is in Grafana: 
![image](https://user-images.githubusercontent.com/11192971/94677998-13bd3000-031e-11eb-8d38-22fcbbce7718.png)
I do not understand the error message. 
What do I do? Please help. @meier81 @torkelo @muutech

**Comment by Bubbu17** [comment]
> @torkelo for table panels using time series, would be nice to be able to print VARCHAR type metrics, would you consider for future releases remove this constraint? thanks and merry xmas!

Hello Torkelo, have you considered this for future releases yet? (VARCHAR type metrics)

**Comment by drekaflugan** [comment]
So wait, it's not possible to make tables anymore unless its contents are numeric values?

**Comment by Antohnio123** [comment]
Same problem with Grafana == 7.2.1. (it's a project restriction)
Visualization == "Table"
Datasource == PostgreSQL

Query, working nice in PgAdmin:
SELECT
  "DateTime" as time,
  "tag_name" as "Tag",
  "mistake_type" as "Mistake",

  case when "mistake_type" = 'None values' then 0
  when "mistake_type" = 'Freeze values' then 1 
  when  "mistake_type" = 'High values' then 2
  when  "mistake_type" = 'Low values' then 3 
  else 10 end as "Mistake Type"
FROM vostok.wrong_values

![123](https://user-images.githubusercontent.com/59763511/126301390-fbb18214-d3c0-4865-92b3-81b67d13a069.jpg)

"None values" is a string, there could be also "High values", "Low values" and so on.  
So could someone explain, how to display  string values in Grafana Table Visualization?
