### ISSUE TITLE
Long value error showed in page

### ISSUE THREAD

**Issue by yue6121** [grafana/grafana#12462]
- What Grafana version are you using? 5.2.0
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? Ubuntu 16.04
- What problem?
The backend get the right  value with Long type, but in the page, the value is wrong, I know that JS Max Int is 2^53-1， so the gbId out of range, now I want to know how to fixed? 
There is a func name processBuckets with code 
```
				if key, err := bucket.Get("key").String(); err == nil {
					newProps[aggDef.Field] = key
				} else if key, err := bucket.Get("key").Int64(); err == nil {
					newProps[aggDef.Field] = strconv.FormatInt(key, 10)
				}
```
but not affected.
![33](https://user-images.githubusercontent.com/8063831/42086972-54f4b808-7bc7-11e8-99b3-4189125a91d8.png)

**Comment by torkelo** [comment]
it can't be as it's bigger than max js number. You will have use a string field instead.
