### ISSUE TITLE
Snapshots / TypeError: Cannot read property 'length' of undefined true

### ISSUE THREAD

**Issue by MPopti0n** [grafana/grafana#12477]
**Informations:**

- Grafana `v5.1.4` (a5fe24fcc) with Influxdb `v1.5.3` (Chronograf `v1.5.0.1`) on Win 10 with Google Chrome and Firefox up to date

Created a snapshot (some snapshots!) with [api/snapshots](url) and it's working fine 

```
{
"deleteKey":"w7JjEtV39DjT12YTmtvdU3bYj...",
"deleteUrl":"http://localhost:8886/api/snapshots-delete/w7JjEtV39DjT12YTmtvdU3...",
"key":"J7eDqAhWQJUje8PjPeLCWkNda9...",
"url":"http://###.###.#.###:####/dashboard/snapshot/J7eDqAhWQJUje8PjPeLCWkN..."
}
```
But when I go to the URL (or try to view directly in the snapshot menu of the frontend) it's loading the fontend but I get and error : 
```
TypeError: Cannot read property 'length' of undefined true
```
![2018-07-02 2](https://user-images.githubusercontent.com/36873863/42155764-44555e5c-7db7-11e8-97b7-3a1143856c13.png)

### Raw network request & response: 
 
```
warning rootScope onAppEvent called without localscope
grafana_app.ts:59 warning rootScope onAppEvent called without localscope
0.5c89ac3fc7a3e78b3629.js:36876 TypeError: Cannot read property 'length' of undefined
    at e.upgradeToGridLayout (dashboard_migration.ts:484)
    at e.updateSchema (dashboard_migration.ts:423)
    at e.updateSchema (dashboard_model.ts:762)
    at new e (dashboard_model.ts:83)
    at t.create (dashboard_srv.ts:131)
    at t.setupDashboardInternal (dashboard_ctrl.ts:157)
    at t.setupDashboard (dashboard_ctrl.ts:147)
    at t.init (history.ts:67)
    at e.initDashboard (grafana_app.ts:54)
    at app.5372b9bbcb8c6d1c027e.js:30629 true
```

**Comment by marefr** [comment]
Try and modify the timeout of the snapshot before creating it. If that's not working please include the response from server when loading your snapshot.

**Comment by torkelo** [comment]
> Created a snapshot (some snapshots!) with api/snapshots and it's working fine 

Can you describe what did there? What did you send to this API?

**Comment by MPopti0n** [comment]
@marefr 

Thanks, that solve it :)

**Comment by yangxu1362850636** [comment]
hi, I also encountered the same problem. can u tell me how do u fix the problem, this was my request body,`-d '{"dashboard": {"editable":false,"hideControls":true,"nav":[{"enable":true,"type":"timepicker"}],"rows": [{}],"style":"dark","tags":[],"templating":{"list":[]},"time":{},"timezone":"browser","title":"dashboard1","version":1},"name":"demosnapshot","timeout":4}'`

**Comment by yangxu1362850636** [comment]
@ marefr can u help me ?

**Comment by marefr** [comment]
@yangxu1362850636 increase the timeout property, see [documentation](http://docs.grafana.org/reference/sharing/#dashboard-snapshot). I would suggest you to first search existing topics for answers/create new topic on our [community site](https://community.grafana.com/) if you  encounter problems.

**Comment by yangxu1362850636** [comment]
@marefr i seached community site and i found the similar problem[https://community.grafana.com/t/snapshot-using-http-api-does-nothing/8834/14](url)
but i found nothing can resolve my problem, can u help me at qq?
