### ISSUE TITLE
Cannot use $timeFilter in "On Time Range Change" variables

### ISSUE THREAD

**Issue by LionelCons** [grafana/grafana#12475]
When using a variable that depends on time ranges ("Refresh" set to "On Time Range Change"), the `$timeFilter` variable should be available.

Currently, when using it, we get:
```
Template variables could not be initialized: error parsing query: missing parameter: timeFilter
```

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/7918  (related to same root issue)
