### ISSUE TITLE
Heatmap: r[a] is undefined error

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#12484]
### What Grafana version are you using?

v5.2.1

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Linux

### What did you do?

Use a heatmap with Prometheus data

### What was the expected result?

See the heatmap

### What happened instead?

JS error `r[a] is undefined`.

```
1807/l</t.prototype.transformToHistogramOverTime@http://grafana.company.com/public/build/0.950b64c220f766b8b5f3.js:7:187204
1807/l</t.prototype.transform@http://grafana.company.com/public/build/0.950b64c220f766b8b5f3.js:7:185034
1805/m</t.prototype.query/</<@http://grafana.company.com/public/build/0.950b64c220f766b8b5f3.js:7:178813
s@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:1:53444
ss@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:1:94991
1805/m</t.prototype.query/<@http://grafana.company.com/public/build/0.950b64c220f766b8b5f3.js:7:178588
u@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:68722
l/<@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:69127
$digest@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:74824
$apply@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:76636
x/s<@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:72695
i@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:21868
mt/l.defer/n<@http://grafana.company.com/public/build/vendor.950b64c220f766b8b5f3.js:87:23332
```

**Comment by marefr** [comment]
Could you please troubleshoot your query using the [query inspector](https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630) and verify that the response looks correct? Could you please include your panel json?

**Comment by grobie** [comment]
Yes, the response from Prometheus is always healthy and looks correct. Something throws off the plugin. It works sometimes for specific time ranges, but often this alert is raised.

```json
{
  "cards": {
    "cardPadding": null,
    "cardRound": null
  },
  "color": {
    "cardColor": "rgb(67, 186, 72)",
    "colorScale": "sqrt",
    "colorScheme": "interpolatePuBuGn",
    "exponent": 0.5,
    "max": 10,
    "min": 0,
    "mode": "opacity"
  },
  "dataFormat": "timeseries",
  "datasource": "$prometheus",
  "description": "Histogram over time of GC pauses to collect older-generation objects. Unit is “GC pause seconds, per second”.",
  "gridPos": {
    "h": 7,
    "w": 6,
    "x": 18,
    "y": 20
  },
  "heatmap": {},
  "highlightCards": true,
  "id": 36,
  "legend": {
    "show": false
  },
  "links": [],
  "targets": [
    {
      "expr": "rate(hotspot_gc_collection_time_seconds_total{system=\"$system\",env=~\"$env\",component=~\"$component\",track=\"$track\",name=\"ConcurrentMarkSweep\"}[5m])",
      "format": "heatmap",
      "intervalFactor": 1,
      "refId": "A"
    }
  ],
  "title": "ConcurrentMarkSweep GC Time Distribution",
  "tooltip": {
    "show": true,
    "showHistogram": false
  },
  "type": "heatmap",
  "xAxis": {
    "show": true
  },
  "xBucketNumber": null,
  "xBucketSize": "1m",
  "yAxis": {
    "decimals": null,
    "format": "short",
    "logBase": 1,
    "max": null,
    "min": "0",
    "show": true,
    "splitFactor": null
  },
  "yBucketBound": "auto",
  "yBucketNumber": null,
  "yBucketSize": null,
  "scopedVars": {
    "track": {
      "text": "release",
      "value": "release",
      "selected": true
    }
  }
}
```

**Comment by ccmtaylor** [comment]
I suspect it's related to the set of time series changing in the time window that is displayed by the heatmap.

I observed the error starting to happen during a deploy, which in our case scales up new instances and tears down the old ones, so if the time window of the graph spans across a deploy, there will be some time series that disappear, and some time series that start in the middle of the graph.

Shifting the time window to end before the deploy makes the heatmap show data again.

**Comment by alexanderzobnin** [comment]
@grobie could you please post network response from prometheus for this query?

**Comment by ccmtaylor** [comment]
it might be a red herring though. I looked at three different deploys; two of which produced the error, and one that did not. Looking at the time series in prometheus didn't show any differences between the time series that produce the error vs the ones that don't.

**Comment by alexanderzobnin** [comment]
@ccmtaylor I think I found a root cause - it happens when lower series has no point while upper has one, like:
```
series2: 1 2 3 4
series1: 1 2 3
```
