### ISSUE TITLE
[Bug] Cloudwatch datasource returns 500 for every query error

### ISSUE THREAD

**Issue by alecxvs** [grafana/grafana#12489]
### What Grafana version are you using?

Grafana v4.6.3 (commit: 7a06a47)

### What datasource are you using?

CloudWatch

### What did you do?

Execute a query that results in an error.

![image](https://user-images.githubusercontent.com/513932/42182154-ef54d5e4-7e02-11e8-913a-3878e9cbe8de.png)

This is an invalid query to CloudWatch because "pNN.NN" should be some number like "p99.95"

### What was the expected result?

A 400 error with a descriptive message on the frontend informing me about the invalid parameter

### What happened instead?

A 500 error presenting no details to the frontend

grafana.log:

```none
t=2018-07-02T15:50:24+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=foo error="InvalidParameterValue: The value pNN.NN for parameter ExtendedStatistics.member.1 is not supported.\n\tstatus code: 400, request id: bar"
t=2018-07-02T15:50:24+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=foo method=POST path=/api/tsdb/query status=500 remote_addr=ip-address time_ms=308 size=34 referer="https://myurl/dashboard/db/test?refresh=1m&orgId=1"
```

Cloudwatch appears to return a status code of 400 with its error message but the error is being handled as a 500 regardless.

---

I'm monitoring Grafana 5xx as a means to detect when Grafana or any of the configured datasources is having connectivity or performance issues, but this makes for some very noisy alerts whenever somebody is building dashboards.

**Comment by marefr** [comment]
Confirmed same behavior in Grafana v5.3.0-pre (latest)

**Comment by torkelo** [comment]
@mtanda do you know what this could be?

**Comment by mtanda** [comment]
@torkelo I already make a PR.
https://github.com/grafana/grafana/pull/12495

The backend tsdb code can't response 400, so I prevent backend API call in frontend.

**Comment by alecxvs** [comment]
I should clarify this isn't just an issue with extended parameters, that was just the easiest example to give. Here are a couple other errors I've received due to bad queries (sorry I don't have examples of the queries prepared):

```
"InvalidParameterValue: The parameter Dimensions.member.1.Value must be shorter than 257 characters.\n\tstatus code: 400, request id: ..."
```
I believe I was trying to pass a ludicrous number of values to the dimension here.

```
"InvalidParameterValue: The parameter EndTime must be greater than StartTime.\n\tstatus code: 400, request id: ..."
```
Not sure about this one

I suppose these could also be caught in the front end but I don't think returning a 500 error when the backend receives a 400 is valid.

I dug around a bit to try and understand why this is happening with Cloudwatch and not another datasource like Influx. Influx doesn't throw an error unless it's a network error; it passes successful requests as 200s and any query errors are surfaced to the front end somehow. In the case of Cloudwatch, it appears that the AWS SDK client throws an error on any non-200 status code, and the backend is passing those errors along (which ultimately become 500 errors?) when it could perhaps catch client errors and respond differently.

**Comment by mtanda** [comment]
I understand your situation.

CloudWatch API itself can return status code.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html
https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/

Grafana API can't return 400, always return 500.
https://github.com/grafana/grafana/blob/v5.2.1/pkg/api/metrics.go#L47
https://github.com/grafana/grafana/blob/v5.2.1/pkg/api/metrics.go#L55

I don't want to change current CloudWatch datasource response format.
So, `pkg/api/metrics.go` support to return 400, I can help you.

**Comment by marefr** [comment]
@mtanda you can populate [Error in QueryResult](https://github.com/grafana/grafana/blob/master/pkg/tsdb/models.go#L28) instead of returning error in it and that should propagate back to UI.

**Comment by mtanda** [comment]
@marefr hmm, but it still returns status code 500?

**Comment by marefr** [comment]
Yes, you're correct but it's populating `resp.Message`, see [code](https://github.com/grafana/grafana/blob/v5.2.1/pkg/api/metrics.go#L54), and it's handled in Grafana frontend and automatically shown in toaster, see [code](https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L46-L69).

**Comment by mtanda** [comment]
I agree with improving error message by using Error in QueryResult. (and I'll do it after another PR is merged.)
But, it doesn't solve this issue perfectly.

> I'm monitoring Grafana 5xx as a means to detect when Grafana or any of the configured datasources is having connectivity or performance issues, but this makes for some very noisy alerts whenever somebody is building dashboards.

He suffer noisy alerts, so we need to return 400 for client error.

**Comment by marefr** [comment]
I think that returning a 400 makes more sense than 500 when having an Error in QueryResult

**Comment by alecxvs** [comment]
This isn't really solved is it?

**Comment by mtanda** [comment]
@alecxvs Sorry, it's not solved.
