### ISSUE TITLE
Displaying multiple graphs on one graph causing incorrect statistics

### ISSUE THREAD

**Issue by idbennm** [grafana/grafana#12482]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.0.4-1

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Centos 6.9

### What did you do?
Added three metrics into one graph to show memory usage

```
node_memory_MemTotal{instance=~"$node"}
```

```
node_memory_MemTotal{instance=~"$node"} - node_memory_MemFree{instance=~"$node"} - node_memory_Cached{instance=~"$node"} - node_memory_Buffers{instance=~"$node"} - node_memory_Slab{instance=~"$node"}
```

```
(node_memory_SwapTotal{instance=~"$node"} - node_memory_SwapFree{instance=~"$node"})
```

### What was the expected result?

I was expecting to see graphed 
Ram Total
Ram Used
and 
Swap used in that order

### What happened instead?

When diaplying all three graphs together and you hover over the line displaying swap used it incorrectly displays to the total of the other two graphs. 

If I only select Swap used on the dashboard it correctly displays the amount of swap used. 

### If related to metric query / data viz:

As above

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Screenshot to explain better.

Below screenshot shows Swap used as over 2GB when all three graps are being dispalyed..
![image](https://user-images.githubusercontent.com/18311036/42169141-ce1bd4ce-7e0a-11e8-88c6-1075da20b8cd.png)

Wehn only selecting swap used it shows correct data

![image](https://user-images.githubusercontent.com/18311036/42169173-dd9405e8-7e0a-11e8-8e9b-16441fff3eaf.png)

thanks very much

**Comment by marefr** [comment]
Think you have stacking enabled? Please choose stacked value individual for the hover tooltip under display settings.

**Comment by idbennm** [comment]
@marefr that's great appreciate your quick response, exactly what I need
