### ISSUE TITLE
Redirect to specific panel does not work

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#12485]
### What Grafana version are you using?
v5.2.1
### What datasource are you using?
does not matter
### What OS are you running grafana on?
linux
### What did you do?
* Create dashboard "Foobar" http://grafana.example.com/d/000001042/foobar
* Copy link to dashboard and specific panel ID: http://grafana.example.com/d/000001042/foobar?refresh=30s&panelId=3&fullscreen&orgId=1&from=now-1h&to=now
* Rename dashboard to "Foo"
### What was the expected result?
* Link automatically redirects to new name and shows the selected panel (panelId=3) in fullscreen
### What happened instead?
* Link redirects to new dashboard name, screen is blank neither showing the dashboard nor the selected panel

**Comment by marefr** [comment]
Works perfectly well for me both using a proxy and having ` http://grafana.example.com` and no proxy ` http://localhost:3000`. 

Are you sure that the panel id exist in that dashboard? Is the panel placed inside a row? Do you get any error in chrome dev tools console?

**Comment by marefr** [comment]
Are you by any chance using a proxy with a sub path, i.e. `http://<domain>/grafana?

**Comment by grobie** [comment]
@marefr It seems to be a race condition. I just had it working a few times, but I also hit cases where it's not working. Myself and a couple of colleagues can all reproduce it by opening https://play.grafana.org/d/000000029/prometheus-demo-dashboard-invalid?refresh=5m&panelId=1&fullscreen&orgId=1 one or a handful of times. In the majority of the cases it won't show the panel.

**Comment by marefr** [comment]
The dashboard you're referring to have not been saved with the Grafana 5.0 schema version. Saved it after migration so now it's on latest schema version. Can reproduce the bug. Thanks for reporting
