### ISSUE TITLE
[Bug] nonNegativeDerivative argument hidden if 0

### ISSUE THREAD

**Issue by yuribit** [grafana/grafana#12488]
### What Grafana version are you using?
5.1.2
### What datasource are you using?
Graphite 1.1.2
### What did you do?
1. Create a Graph panel to display the graphite metric A
2. Apply the "nonNegativeDerivative" function passing 0 as argument (max_value).
It should look like `nonNegativeDerivative(A, 0)`
3. Click on "Toggle Edit Mode"
### What was the expected result?
<img width="320" alt="screen shot 2018-07-02 at 11 40 45 am" src="https://user-images.githubusercontent.com/1260900/42180646-dcc4d098-7dec-11e8-85a6-8ad0c3e0f4b7.png">

### What happened instead?

<img width="313" alt="screen shot 2018-07-02 at 11 40 20 am" src="https://user-images.githubusercontent.com/1260900/42180652-e2bae76c-7dec-11e8-91c5-56bacd05eb0e.png">

`nonNegativeDerivative(#A, 0) != nonNegativeDerivative(#A)`

**Comment by marefr** [comment]
Confirmed bug in Grafana 5.3.0-pre (latest) as well
