### ISSUE TITLE
Variables that refresh on time range change should cause panel queries to wait

### ISSUE THREAD

**Issue by PauloTemenos** [grafana/grafana#12497]
I'm seeing an issue where we change the filters/time to options that don't provide results *but* when we change the filters/time back to settings that should show data, Grafana doesn't refresh the data. We have to "F5" the entire page for it to exit this «error state».

I couldn't find a consistency in the behaviour - appears to happen «at random».
How should I debug this further - what can I do to help you guys debug this?

### What Grafana version are you using?
Grafana 5.2.0-1

### What datasource are you using?
ElasticSearch 6.3.0

### What OS are you running grafana on?
RHEL 7.5

### Browser?
Seen in happen in Firefox and Chrome.

### What did you do?
Change filters/time-selection to settings that don't respond with data. Change back to settings that should show data but the tables and graphics do not refresh.

### Include raw network request & response
[Archive 18-07-03 17-17-14 (broken).zip](https://github.com/grafana/grafana/files/2160196/Archive.18-07-03.17-17-14.broken.zip)
[Archive 18-07-03 17-20-20 (OK).zip](https://github.com/grafana/grafana/files/2160197/Archive.18-07-03.17-20-20.OK.zip)
^ find attached a HAR archive for when it fails and one for when it succeeds

**Comment by PauloTemenos** [comment]
Found an intermediate cause: the filtering by Variable becomes .. "broken"?

When the dashboard is «working», this is what it sends as query:
`EnvironmentID:("ABC" OR "BCD" OR "CDE" OR "FGH") AND SOME\ id:("SCRPT1" OR "SCRPT2" OR "SCRPT3" OR "SCRPT4" OR "SCRPT5" OR "SCRPT6" OR "SCRPT7")`

When the dashboard becomes "broken", this is what it sends as query:
`EnvironmentID:("ABC" OR "BCD" OR "CDE" OR "FGH") AND SEAT\ id:__empty__`

**Comment by PauloTemenos** [comment]
Here is some JSON of the Dashboard itself. I hope I didn't remove anything important - I retained the datasource, the JSON of one of the panels (a Table), and the JSON of the Variables ("templates"):

> {
>   "__inputs": [
>     {
>       "name": "{DEL}",
>       "label": "{DEL}",
>       "description": "",
>       "type": "datasource",
>       "pluginId": "elasticsearch",
>       "pluginName": "Elasticsearch"
>     }
>   ],
>   "__requires": [
>     {
>       "type": "datasource",
>       "id": "elasticsearch",
>       "name": "Elasticsearch",
>       "version": "5.0.0"
>     },
> {DEL}
>     {
>       "columns": [],
>       "datasource": "${DS_ELASTIC_SOME_SUMMARIES}",
>       {DEL},
>       "styles": [
>         {
>           "alias": "Time",
>           "dateFormat": "YYYY-MM-DD HH:mm:ss",
>           "pattern": "Time",
>           "type": "date"
>         },
>         {
>           "alias": "Application (script)",
>           "colorMode": null,
>           "colors": [
>             "rgba(245, 54, 54, 0.9)",
>             "rgba(237, 129, 40, 0.89)",
>             "rgba(50, 172, 45, 0.97)"
>           ],
>           "dateFormat": "YYYY-MM-DD HH:mm:ss",
>           "decimals": 2,
>           "mappingType": 1,
>           "pattern": "SOME id.keyword",
>           "preserveFormat": false,
>           "sanitize": false,
>           "thresholds": [],
>           "type": "string",
>           "unit": "short",
>           "valueMaps": [
>             {
>               "text": "blabla (*-002-I)",
>               "value": "SCRPT1"
>             },
>             {
>               "text": "qrewrewre (*-005-I)",
>               "value": "SCRPT2"
>             },
>             {
>               "text": "gcfft (*-007-I)",
>               "value": "SCRPT3"
>             },
>             {
>               "text": "qwegertge (*-001-I)",
>               "value": "SCRPT4"
>             },
>             {
>               "text": "htrrtrtrt (*-003-I)",
>               "value": "SCRPT5"
>             },
>             {
>               "text": "xdtgtytr (*-006-I)",
>               "value": "SCRPT6"
>             },
>             {
>               "text": "jyttrefxd (*-004-I)",
>               "value": "SCRPT7"
>             }
>           ]
>         },
>         {
>           "alias": "Vertical",
>           "colorMode": null,
>           "colors": [
>             "rgba(245, 54, 54, 0.9)",
>             "rgba(237, 129, 40, 0.89)",
>             "rgba(50, 172, 45, 0.97)"
>           ],
>           "dateFormat": "YYYY-MM-DD HH:mm:ss",
>           "decimals": 2,
>           "mappingType": 1,
>           "pattern": "EnvironmentID.keyword",
>           "thresholds": [],
>           "type": "string",
>           "unit": "short"
>         },
>         {
>           "alias": "Read Δ",
>           "colorMode": "cell",
>           "colors": [
>             "rgba(50, 172, 45, 0.97)",
>             "rgba(237, 129, 40, 0.89)",
>             "rgba(245, 54, 54, 0.9)"
>           ],
>           "dateFormat": "YYYY-MM-DD HH:mm:ss",
>           "decimals": 0,
>           "mappingType": 1,
>           "pattern": "Max Read Diff",
>           "thresholds": [
>             "1",
>             "6"
>           ],
>           "type": "number",
>           "unit": "short"
>         },
>         {DEL}
>       ],
>       "targets": [
>         {
>           "bucketAggs": [
>             {
>               "fake": true,
>               "field": "EnvironmentID.keyword",
>               "id": "8",
>               "settings": {
>                 "min_doc_count": 1,
>                 "order": "desc",
>                 "orderBy": "_term",
>                 "size": "100"
>               },
>               "type": "terms"
>             },
>             {
>               "field": "SOME id.keyword",
>               "id": "2",
>               "settings": {
>                 "min_doc_count": 1,
>                 "order": "desc",
>                 "orderBy": "_term",
>                 "size": "100"
>               },
>               "type": "terms"
>             }
>           ],
>           "groupBy": {DEL},
>           "metrics": {DEL},
>           "orderByTime": "ASC",
>           "policy": "default",
>           "query": "EnvironmentID:$EnvironmentIDs AND SEAT\\ id:$ScriptIDs",
>           "refId": "A",
>           "resultFormat": "time_series",
>           "select": [
>             [
>               {
>                 "params": [
>                   "value"
>                 ],
>                 "type": "field"
>               },
>               {
>                 "params": [],
>                 "type": "mean"
>               }
>             ]
>           ],
>           "tags": [],
>           "timeField": "Date"
>         }
>       ],
>       "title": "Max differences per script",
>       "transform": "table",
>       "type": "table"
>     },
>     {DEL},
>     {DEL}
>   ],
>   {DEL}
>   "templating": {
>     "list": [
>       {
>         "allValue": null,
>         "current": {},
>         "datasource": "${DS_ELASTIC_SOME_SUMMARIES}",
>         "hide": 0,
>         "includeAll": true,
>         "label": "Vertical",
>         "multi": true,
>         "name": "EnvironmentIDs",
>         "options": [],
>         "query": "{\"find\": \"terms\", \"field\": \"EnvironmentID.keyword\"}",
>         "refresh": 1,
>         "regex": "",
>         "sort": 1,
>         "tagValuesQuery": "",
>         "tags": [],
>         "tagsQuery": "",
>         "type": "query",
>         "useTags": false
>       },
>       {
>         "allValue": null,
>         "current": {},
>         "datasource": "${DS_ELASTIC_SOME_SUMMARIES}",
>         "hide": 0,
>         "includeAll": true,
>         "label": "Script",
>         "multi": true,
>         "name": "ScriptIDs",
>         "options": [],
>         "query": "{\"find\": \"terms\", \"field\": \"SOME id.keyword\"}",
>         "refresh": 1,
>         "regex": "",
>         "sort": 1,
>         "tagValuesQuery": "",
>         "tags": [],
>         "tagsQuery": "",
>         "type": "query",
>         "useTags": false
>       },
>       {
>         "allValue": null,
>         "current": {
>           "selected": false,
>           "tags": [],
>           "text": "Read Diff",
>           "value": "Read Diff"
>         },
>         "hide": 0,
>         "includeAll": false,
>         "label": "Graphic",
>         "multi": false,
>         "name": "Field",
>         "options": [
>           {
>             "selected": false,
>             "text": "Read Actual",
>             "value": "Read Actual"
>           },
>           {
>             "selected": false,
>             "text": "Read Expected",
>             "value": "Read Expected"
>           },
>           {
>             "selected": true,
>             "text": "Read Diff",
>             "value": "Read Diff"
>           },
>           {
>             "selected": false,
>             "text": "Read Deviation",
>             "value": "Read Deviation"
>           },
>           {
>             "selected": false,
>             "text": "Write Actual",
>             "value": "Write Actual"
>           },
>           {
>             "selected": false,
>             "text": "Write Expected",
>             "value": "Write Expected"
>           },
>           {
>             "selected": false,
>             "text": "Write Diff",
>             "value": "Write Diff"
>           },
>           {
>             "selected": false,
>             "text": "Write Deviation",
>             "value": "Write Deviation"
>           },
>           {
>             "selected": false,
>             "text": "Delete Actual",
>             "value": "Delete Actual"
>           },
>           {
>             "selected": false,
>             "text": "Delete Expected",
>             "value": "Delete Expected"
>           },
>           {
>             "selected": false,
>             "text": "Delete Diff",
>             "value": "Delete Diff"
>           },
>           {
>             "selected": false,
>             "text": "Delete Deviation",
>             "value": "Delete Deviation"
>           },
>           {
>             "selected": false,
>             "text": "Lock Actual",
>             "value": "Lock Actual"
>           },
>           {
>             "selected": false,
>             "text": "Lock Expected",
>             "value": "Lock Expected"
>           },
>           {
>             "selected": false,
>             "text": "Lock Diff",
>             "value": "Lock Diff"
>           },
>           {
>             "selected": false,
>             "text": "Lock Deviation",
>             "value": "Lock Deviation"
>           },
>           {
>             "selected": false,
>             "text": "Execute Actual",
>             "value": "Execute Actual"
>           },
>           {
>             "selected": false,
>             "text": "Execute Expected",
>             "value": "Execute Expected"
>           },
>           {
>             "selected": false,
>             "text": "Execute Diff",
>             "value": "Execute Diff"
>           },
>           {
>             "selected": false,
>             "text": "Execute Deviation",
>             "value": "Execute Deviation"
>           },
>           {
>             "selected": false,
>             "text": "CacheRead Actual",
>             "value": "CacheRead Actual"
>           },
>           {
>             "selected": false,
>             "text": "CacheRead Expected",
>             "value": "CacheRead Expected"
>           },
>           {
>             "selected": false,
>             "text": "CacheRead Diff",
>             "value": "CacheRead Diff"
>           },
>           {
>             "selected": false,
>             "text": "CacheRead Deviation",
>             "value": "CacheRead Deviation"
>           }
>         ],
>         "query": "Read Actual,Read Expected,Read Diff,Read Deviation,Write Actual,Write Expected,Write Diff,Write Deviation,Delete Actual,Delete Expected,Delete Diff,Delete Deviation,Lock Actual,Lock Expected,Lock Diff,Lock Deviation,Execute Actual,Execute Expected,Execute Diff,Execute Deviation,CacheRead Actual,CacheRead Expected,CacheRead Diff,CacheRead Deviation",
>         "type": "custom"
>       }
>     ]
>   },
>   "time": {
>     "from": "now-1d/d",
>     "to": "now-1d/d"
>   },
> {DEL}
> }

**Comment by PauloTemenos** [comment]
Hmm, found the underlying problem... Not the bug I originally though but I believe I uncovered another bug.

The filter in question, the variable: `"SOME\ id: abc"`, was set to **"Refresh" only "On Dashboard Load"**. Since the dashboard opens to «no data», there would be no values for that filter for the remaining existance of the dashboard, dispite time changes.

I changed the variable to **"Refresh - On Time Range Change"** and .. still doesn't work properly. The dashboard opens to "Today" so no data _(correct!)_, then I change it to "Yesterday" which has data but still tables show nothing .. *until* I click the refresh-data button on top right.
_^ it appears changing the time picker isn't refreshing the variable set to "Refresh - On Time Range Change"?_

**Comment by marefr** [comment]
Will probably not work if you have a variable filtered by something. Then you don't expect to get all possible values, only the filtered ones. This is probably a result of that the variable is updated after the panel is refreshed.

**Comment by alphachai** [comment]
+1 on this issue. I have variables that are built based on other variables. Graphs referencing the 'downstream' variable don't reload once the variable updates.

**Comment by torkelo** [comment]
I think with recent changes in master this should now work as expected.

Time range changes does not trigger refresh events now but a time range changed event that variableSrv will listen for and update any variables with refresh on time range change, once that process is complete will dashboard refresh events fire.
