### ISSUE TITLE
Order by not work in table query

### ISSUE THREAD

**Issue by huzhenjie** [grafana/grafana#12494]
`order by` not work in table query

Here is my query

```
SELECT word,sum(cnt)
from hot_word 
where from_unixtime(ts/1000) BETWEEN $__timeFrom() AND $__timeTo() 
group by word
having sum(cnt) > 10
order by sum(cnt) desc
limit 100
```
but order by sort not work

Please include this information:
### What Grafana version are you using?
`v5.0.4`
### What datasource are you using?
`MySQL`
### What OS are you running grafana on?
`Ubuntu`

### What did you do?
Add Panel

### What was the expected result?

`order by sum(cnt) desc`

### What happened instead?

not work

**Comment by marefr** [comment]
Please include screenshot of the table panel result you get.

**Comment by marefr** [comment]
Closing this for now since you haven't responded for a month. Will reconsider reopen if you come back with a response.
