### ISSUE TITLE
[Feat] Only allow access signing in with Google oauth if member of certain group

### ISSUE THREAD

**Issue by stevemsmith** [grafana/grafana#12498]
Please include this information:
### What Grafana version are you using?
4.1.1

### What datasource are you using?
influxdb

### What OS are you running grafana on?
CentOS 7

### What did you do?
Tried to get authorization (by Google Groups) to work.  So you can login to Grafana with your Google ID if you're a member of a group (grafana-admins)

### What was the expected result?
That I would be able to login if I was a member of the grafana-admins group but not if I'm anyone else

### What happened instead?
Everyone in my domain can login.

**Comment by benley** [comment]
I want this too, but it may not be possible until Google implements a `groups` scope in the OpenID Connect / OAuth2 provider.

**Comment by Jguer** [comment]
As of Grafana 10.2 this feature is supported by `allowed_groups`
