### ISSUE TITLE
NO_PROXY not used for graphite datasource

### ISSUE THREAD

**Issue by cosmos1978** [grafana/grafana#12492]
Grafana 5.2.1 on docker swarm cluster version 17.06.2-ee-7
Grafana is not using the NO_PROXY settings when accessing a graphite datasource in server mode.

However when doing a curl from within the container to the graphite-web it seems to work correctly.

I tried it with a single IP address in the NO_PROXY env variable but also with a hostname and nothing seems to work.

all graphite calls keep being send to the proxy server. However when using easticsearch backend it does seem to work correctly.

below my compose config. 10.10.10.20 is the graphite cluster on port 81

 grafana:
    image: grafana/$GRAFANA_VERSION
    user: "472"
    environment:
      - HTTP_PROXY=http://10.10.10.10:8080
      - HTTPS_PROXY=http://10.10.10.10:8080
      - NO_PROXY="127.0.0.1,localhost,client,10.10.10.20"
      - GF_SERVER_ROOT_URL=http://grafanaserver.internal
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      - GF_USERS_LOGIN_HINT=email or perid
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=someserver:25
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_ADDRESS=email@gmail.com
      - GF_EMAILS_WELCOME_EMAIL_ON_SIGN_UP=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel,jdbranham-diagram-panel,raintank-kubernetes-app,natel-plotly-panel
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 5G
        reservations:
          cpus: '4'
          memory: 5G
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=grafana.elkprod.idtv.bc
        - com.df.port=3000
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.grafana == 1
        preferences:
          - spread: node.labels.grafana
    volumes:
      - /docker-containers/grafana/:/var/lib/grafana/
    networks:
      - esnet
      - proxy

**Comment by marefr** [comment]
Could you please include your configuration of graphite and elasticsearch datasource? As I see it there should not be any difference between elasticsearch and graphite if they're configured in the same manner.

**Comment by cosmos1978** [comment]
![graphite1](https://user-images.githubusercontent.com/20052785/42216388-f47ec542-7ec1-11e8-9321-b2af41cbe0a9.jpg)

Here is my graphite config

I have another grafana server installed on a ubuntu machine. I see all the requests comming in my proxy server instead of being ommited by the no_proxy config

When doing a curl request directly within the container it does ommit the proxy

**Comment by cosmos1978** [comment]
![elk1](https://user-images.githubusercontent.com/20052785/42216546-7a7f6f84-7ec2-11e8-850c-74a944a35b1f.jpg)
Here is the elastic config

this however uses a docker service dns entry since elastic is running on the same docker swarm.

**Comment by marefr** [comment]
But shouldn't you have `10.52.91.202` in NO_PROXY since that's the IP address you've configured in Grafana for graphite?

**Comment by cosmos1978** [comment]
Yes and I have it there. but to anonymize I used another IP and I just forgot to change it in the jpg to :-)

**Comment by marefr** [comment]
Okay :) Could you try and enable data proxy logging and then inspect Grafana server log when trying to proxy your datasource requests:

```
[dataproxy]
logging = true
```

You can also enable debug logging of the data proxy if you want:
```
[log]
filters = data-proxy-log:debug
```

**Comment by cosmos1978** [comment]
since I am using a docker image can I use some ENV variable to do that ?
Or can I change the config file insode the container and restart the grafana server process ?

I assume the latter is the best choice ?

**Comment by cosmos1978** [comment]
Thanks.

I will try it tomorrow morning and post the logs here

**Comment by cosmos1978** [comment]
I added the extra logging. This is the output when adding the graphite datasource

t=2018-07-04T07:30:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=1 name="400 errors alert" changing state to=no_data


t=2018-07-04T07:31:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=1 name="400 errors alert" changing state to=no_data


t=2018-07-04T07:31:05+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=1 orgid=1 username=admin datasource=graphite uri=/api/datasources/proxy/3/render method=POST body="target=constantLine(100)&from=-1h&until=now&format=json&maxDataPoints=300"


t=2018-07-04T07:31:06+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=1 orgid=1 username=admin datasource=graphite uri=/api/datasources/proxy/3/version method=GET body=


2018/07/04 07:31:25 http: proxy error: context canceled




7-04T07:31:25+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/3/render status=502 remote_addr=10.255.0.9 time_ms=20002 size=0 referer=http://grafana.elkprod.idtv.bc/datasources/edit/3


2018/07/04 07:31:26 http: proxy error: context canceled




7-04T07:31:26+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/3/version status=502 remote_addr=10.255.0.9 time_ms=20001 size=0 referer=http://grafana.elkprod.idtv.bc/datasources/edit/3

**Comment by cosmos1978** [comment]
Any update on this ?

**Comment by marefr** [comment]
Haven't had time to setup a test for being able to reproduce it. If I do, I will only be able to verify that proxy is used or not used based on some config values. I would recommend you to try and strip down your proxy configuration. For example try to only have your graphite IP in the NO_PROXY just to test and maybe remove the extra elastic network.

**Comment by cosmos1978** [comment]
ok good idea I will do some tests.
Thanks.

**Comment by cosmos1978** [comment]
Did some testing? removed one network used to access grafana via docker-flow ha-proxy and placed only a single ip in the NO_PROXY env variable. But alas the same thing happens.

the request is just forwarded to the HTTP proxy and no_proxy is bypassed

**Comment by cosmos1978** [comment]
still getting this


7-06T09:52:36+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/3/render status=502 remote_addr=10.255.0.9 time_ms=20002 size=0 referer=http://grafana.elkprod.idtv.bc/datasources/edit/3


2018/07/06 09:52:36 http: proxy error: context canceled

**Comment by cosmos1978** [comment]
OK got it working.

It seems you cant use "" around the NO_PROXY list :-)

**Comment by marefr** [comment]
Ohhh :blush: Glad you got it working :+1:  Did not spot those extra quotes

**Comment by dmoronta** [comment]
Hi all, please can someone help me? I have the same situation, but still doesn't working. I put the no_proxy parameter with "" and without "". I have grafana v6.3.0

**Comment by marefr** [comment]
@dmoronta please show how you set this environment variables and how you run (start) Grafana.

**Comment by dmoronta** [comment]
In /etc/default/grafana-server  add the following

https_proxy=10.10.10.1:80
no_proxy=localhost,127.0.0.1, 10.10.10.132

The ip 10.10.10.132 is my grafana/influxdb server.

Grafana starts with the command systemctl start grafana-server.service and have the following configuration:

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/sbin/grafana-server                                                  \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}


LimitNOFILE=10000
TimeoutStopSec=20
UMask=0027

[Install]
WantedBy=multi-user.target

Please let me know if you need some extra information.
Thanks in advance.

:)

**Comment by dmoronta** [comment]
Hi all
Any idea?

**Comment by marefr** [comment]
@dmoronta maybe because you have a space in `localhost,127.0.0.1, 10.10.10.132`. Try change to `localhost,127.0.0.1,10.10.10.132`?

**Comment by marefr** [comment]
Should also be capital letter of env names, like `NO_PROXY` and `HTTPS_PROXY`

**Comment by dmoronta** [comment]
The same result, attach the image
![error](https://user-images.githubusercontent.com/47873213/70804953-8f052380-1d96-11ea-8c7f-cecb3f1284f3.png)

**Comment by marefr** [comment]
@dmoronta that screenshot doesn't help at all. Please include grafana server log (remove any sensitive information).

**Comment by cameronkerrnz** [comment]
Assuming that this is using Golang's httpproxy module, then the following is useful to know with regard to the expected format of the no_proxy or NO_PROXY environment variable.

https://godoc.org/golang.org/x/net/http/httpproxy
```
    // NoProxy represents the NO_PROXY or no_proxy environment
    // variable. It specifies a string that contains comma-separated values
    // specifying hosts that should be excluded from proxying. Each value is
    // represented by an IP address prefix (1.2.3.4), an IP address prefix in
    // CIDR notation (1.2.3.4/8), a domain name, or a special DNS label (*).
    // An IP address prefix and domain name can also include a literal port
    // number (1.2.3.4:80).
    // A domain name matches that name and all subdomains. A domain name with
    // a leading "." matches subdomains only. For example "foo.com" matches
    // "foo.com" and "bar.foo.com"; ".y.com" matches "x.y.com" but not "y.com".
    // A single asterisk (*) indicates that no proxying should be done.
    // A best effort is made to parse the string and errors are
    // ignored.

```
