### ISSUE TITLE
[Feat] Singlestat panel value not visible when using background and light theme

### ISSUE THREAD

**Issue by mcktr** [grafana/grafana#12507]
Hi,

when you are using the light theme and you create a singlestat panel with a dark background color you can't read the value properly because the value also uses a dark font color. 

![grafana-light-theme-dark-value-issue](https://user-images.githubusercontent.com/18580278/42309820-08412f92-803a-11e8-9908-fac3eed987bf.PNG)

A possibility to solve this, would be to make the font color configurable regardless of the thresholds color settings.

Another possibility would be to use dynamically a dark or a light font color based on the background color.

### What Grafana version are you using?
Grafana v5.2.1 (commit: 2040f61)

**Comment by CWempe** [comment]
I agree.

The same goes for the dark theme with light background colors.

![image](https://user-images.githubusercontent.com/1270359/61999308-4a663d80-b0be-11e9-8a01-f3fda9406cc3.png)

Like @mcktr said, a **workaround** would be to be able to customize the font color.
The best **solution** would be a dynamic font color that is always readable no matter the backgroud color.

**Comment by trueuto** [comment]
@CWempe - the best solution would be a dynamic font colour with the option to override it with a custom one. This would address more use cases, e.g. the one mentioned in #28673.
