### ISSUE TITLE
issue to connect gnocchi Datasource

### ISSUE THREAD

**Issue by Shawnma1** [grafana/grafana#12503]
Read before posting: 

Version 5.2.1 (commit: 2040f61)

gnocchi

centos 7.5

gnocchixyz-gnocchi-datasource has been installed successfully,
Grafana is started on 5901 port, keystone gnocchi are on the same host(openstack controller)

cors are configured in gnocchi.conf/keystone.conf
allowed_origin = http://10.113.77.93:5901
or allowed_origin = http://localhost:5901
![image](https://user-images.githubusercontent.com/40825081/42272178-ef086914-7fb7-11e8-98e8-53f4dc119552.png)

gnocchi is started on 8041
tcp6       0      0 :::8041                 :::*                    LISTEN 
keystone is started on 35357
tcp6       0      0 :::35357                :::*                    LISTEN    
grafana is started on 5901
tcp6       0      0 :::5901                 :::*                    LISTEN  

### What happened instead?
Keystone failure: No response status code, is CORS correctly configured ?

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
I tried to use tcpdump to get the packets between port 5901 and port 35357(keystone), but nothing....

this is the http packet captured only for 35357 port, 10.113.69.80 is my desktop to launch firefox.
![image](https://user-images.githubusercontent.com/40825081/42272429-a1333f92-7fb8-11e8-9df2-486da5fdea0f.png)

![image](https://user-images.githubusercontent.com/40825081/42272449-b564aaa0-7fb8-11e8-9a33-9e0c4058b6fd.png)

I am appreciated if anyone can kindly provide help.

**Comment by marefr** [comment]
Please check [plugin repository](https://github.com/gnocchixyz/grafana-gnocchi-datasource) and/or open an issue there.
