### ISSUE TITLE
[Feat] Add plugin dashboards to folders automatically when plugin is installed

### ISSUE THREAD

**Issue by RobertChiperM** [grafana/grafana#12509]
Allow plugins to create folders (maybe directly from the plugin.json file) and then have them populated with specific dashboards. The dashboards currently don't contain the folderUid in their Json model, so maybe adding that would be useful.

**Comment by marefr** [comment]
Can you describe the use case a bit more? Think that it must be possible for a user to override where to import a plugin dashboard but plugin can suggest to put it in a folder. Some users want to have it in certain folder with certain permissions maybe.

**Comment by RobertChiperM** [comment]
What you described is exactly what I want.

**Comment by RobertChiperM** [comment]
The use case would be that when a plugin is installed, it will create one or more dashboard folders and place its dashboards in those folders. This sounds similar to what you described. I didn't manage to find any documentation on how to do that. The dashboard json doesn't contain information about what folder the dashboard is in.

**Comment by wbrowne** [comment]
This is supported, but not yet documented appropriately - will follow up in #36475
