### ISSUE TITLE
Add support for OpenTSDB and templating metric query variable (for tags or series names) 

### ISSUE THREAD

**Issue by wjk1982** [grafana/grafana#1250]
I config as forllows in config.js

 datasources: {
        opentsdb: {
          type: 'opentsdb',
          url: "http://10.16.40.53:3333",
        },
        elasticsearch: {
          type: 'elasticsearch',
          url: "http://10.16.40.30:9200",
          index: 'grafana-dash',
          grafanaDB: true,
        }
      },

opentsdb is datasources and elasticsearch store config info.
I can not use the templated feature,because of lack the function :"metricFindQuery" in  opentsdbDatasource.js  file

I hope add the functions to support the templated feature,thanks

**Comment by IzakMarais** [comment]
+1

For our templating use-case we want the query to return all tag values associated with a specific tag key. 

The search/lookup OpenTSDB API endpoint be useful here: see https://github.com/OpenTSDB/opentsdb/issues/267

Would you consider supporting this style of opentsdb query templating as well?

**Comment by lexh** [comment]
+1
To @IzakMarais' point, that API endpoint seems to be the answer for my use case as well. I would like a dynamic template variable which is populated with the valid tagv's for a given metric and tagk. There are a number of similar scenarios that the endpoint mentioned deals with:

I know the metric, what tagk, tagv pairs are associated with it?
http://tsdb:4242/api/search/lookup?m=test.some_metric

I know the tagk, what metrics and tagv's are associated with it?
http://tsdb:4242/api/search/lookup?m={foo=*}

I want to know what metrics are tagged with a certain tagk, tagv pair.
http://tsdb:4242/api/search/lookup?m={foo=bar}

This endpoint could also be used to address the idea of restricted suggestions in the tagk, tagv typeahead as mentioned in this PR: https://github.com/grafana/grafana/pull/1433 It would require some configuration on the OTSDB end, however, as this endpoint is only available when metadata is enabled by setting `tsd.core.meta.enable_realtime_uid = true` in the OTSDB conf. See [the relevant docs]( http://opentsdb.net/docs/build/html/user_guide/metadata.html)

**Comment by IzakMarais** [comment]
>  I would like a dynamic template variable which is populated with the valid tagv's for a given metric and tagk.
...
 I know the tagk, what metrics and tagv's are associated with it?
http://tsdb:4242/api/search/lookup?m={foo=*}

Yes, as I mentioned, this is our usecase as well.

However, we have found in practice that the search endpoint is too verbose in its return (it returns complete time series information, even if that is not what is required). E.g. if a tagk is associated with only a small handfull of tagv's but with all metrics (e.g. a "host" tagk), the call can become slow and return megabytes worth of data. 

In my scripted dashboard I use to solve this problem, I rather query the [Bosun /api/tagv/{tagk} endpoint](http://bosun.org/api.html)

**Comment by torkelo** [comment]
You can now use these queries in the template query field: 


    metrics()                     // returns metric names
    tag_names(cpu)                // return tag names (i.e. keys) for a specific cpu metric
    tag_values(cpu, hostname)     // return tag values for metric cpu and tag key hostname`

**Comment by gcormier9** [comment]
Is it possible that the metric typeahead got broken? Within "public/app/plugins/datasource/opentsdb/queryCtrl.js", I believe we should be using the query variable. Something like this:

$scope.suggestMetrics = function(query, callback) {
  $scope.datasource.metricFindQuery('metrics(' + query + ')')
    .then($scope.getTextValues)
    .then(callback);
};

**Comment by torkelo** [comment]
@gcormier9 thanks, fixed now

**Comment by soultemple** [comment]
@torkelo 
opentsdb lookup provides search tag values from another tag key & value.
ex: 
/api/lookup?m=cpu{hostname=*,service=talk} 
-> Get hostname list when service is talk 

Within "public/app/plugins/datasource/opentsdb/queryCtrl.js"
conditional lookup query can provide like this: 

$scope.suggestTagValues = function(query, callback) {
      $scope.datasource.metricFindQuery('tag_values(' + $scope.target.metric + ',' + $scope.target.currentTagKey + ',' + $scope.target.conditionTagKey +  '=' + $scope.target.conditionTagValue  ')')
        .then($scope.getTextValues)
        .then(callback);
    };

**Comment by bobrik** [comment]
@torkelo http://opentsdb.net/docs/build/html/api_http/search/lookup.html

It looks like OpenTSDB does something different from what we want.

* `metrics` works as expected, returning all metric names
* `tag_names(cpu)` returns nothing
* `tag_values(cpu)` returns nothing

I think you should use suggest api everywhere to make it work.

Did I miss anything that prevents me from doing it right?

```
curl -s 'http://opentsdb/api/search/lookup?m=tsd.hbase.rpcs%7Btype%3D*%7D' | jq .
```

```json
{
  "type": "LOOKUP",
  "metric": "tsd.hbase.rpcs",
  "tags": [
    {
      "key": "type",
      "value": "*"
    }
  ],
  "limit": 25,
  "time": 11,
  "results": [],
  "startIndex": 0,
  "totalResults": 0
}
```

Here `*` doesn't really help with templating.

**Comment by bobrik** [comment]
Okay, I probably missed the part that you have to enable metadata collection to make it work. Will try that.

**Comment by digrich** [comment]
These methods are not returning any tag values from OpenTSDB. I enabled 'tsd.core.meta.enable_realtime_ts' metadata property also on OpenTSDB config file. 

tag_names(cpu) 
tag_values(cpu) 

Am I missing anything else?

**Comment by bobrik** [comment]
@digrich you have to do `tsdb uid metasync` to populate metadata for existing data.

http://opentsdb.net/docs/build/html/user_guide/cli/uid.html#metasync

**Comment by digrich** [comment]
Great @bobrik, It's working now. Thanks.

**Comment by skygragon** [comment]
@bobrik Is there any way to avoid this manually "tsdb uid metasync"? The http://docs.grafana.org/features/datasources/opentsdb/#templating-queries said differently:

> If you do not see template variables being populated in Preview of values section, you need to enable tsd.core.meta.enable_realtime_ts in the OpenTSDB server settings. Also, to populate metadata of the existing time series data in OpenTSDB, you need to run tsdb uid metasync on the OpenTSDB server.

**Comment by IzakMarais** [comment]
@skygragon Those docs you quoted say exactly the same thing. 

>  to populate metadata of the ***existing*** time series data in OpenTSDB, you need to run tsdb uid metasync...

The manual step is only needed for existin time series data. The setting will ensure all future, new data has metadata.

**Comment by skygragon** [comment]
@IzakMarais The problem is even after I configured "tsd.core.meta.enable_realtime_ts = true", the new metadata (like new tags) are not shown in grafana templating. I have to run "metasync" command again to see those new metadata......

**Comment by snip** [comment]
@skygragon You also need to have tsd.core.meta.enable_tsuid_tracking set to true.
See http://opentsdb.net/docs/build/html/user_guide/metadata.html#enabling-metadata
