### ISSUE TITLE
[Feat] Prevent XSS of data returned from tsdb

### ISSUE THREAD

**Issue by Strum355** [grafana/grafana#12505]
### What Grafana version are you using?:
5.2.1
### What datasource are you using? 
InfluxDB
### What OS are you running grafana on? 
grafana:latest Docker image on Ubuntu 16.04
### What did you do? 
Insert HTML/JavaScript as a tag value for a data point in Influx, `group by` said tag in Grafana
### What was the expected result? 
Expected Grafana to escape said HTML/JavaScript
### What happened instead? 
The HTML/JavaScript was parsed and the JavaScript was executed

Originally found when `country/<int:pk>/` was the tag value and it parsed `<int:pk>` as a HTML tag

Example (the tag name is `path` and its value is `<script>alert('hello')</script>`):
<details>
<img src="https://user-images.githubusercontent.com/18282288/42286696-cd74e8ce-7fab-11e8-846c-e3e067e63210.png">
</details>

**Comment by Strum355** [comment]
further info: In the hover tooltips it seems to escape it as it should, which means when I escape on the backend, its doubly-escaped, causing the legend underneath the bars to appear as they should but in the tooltips theyre doubly escaped

**Comment by dallasgutauckis** [comment]
Out of curiosity, why is this considered a feature request versus a bug?

**Comment by torkelo** [comment]
think this was fixed in v5.3 when we moved legend to react

**Comment by hairyhenderson** [comment]
@torkelo It was not fixed in v5.3, or at least, it's still happening in v5.4.1...

**Comment by hairyhenderson** [comment]
In my specific case, this was using Prometheus as a datasource, with a graph panel - a string like `/api/foo<script>alert(1)</script>` was present in one of the labels displayed in the legend
