### ISSUE TITLE
[Feat] Allow Folder UID to be specified when provisioning dashboards.

### ISSUE THREAD

**Issue by PaulW** [grafana/grafana#12508]
When provisioning dashboards as code, we define the folder for where these dashboards are held, however, unlike the dashboard json, it is currently not possible to manually specify the UID of the Folder object.

When we deploy Grafana as a Deployment in kubernetes, and deploy the dashboards as code, we are able to link directly to each individual dashboard, and when we destroy & redeploy, the links in question still work as expected, as each dashboard has the UID specified in the relevant JSON.

However, when we link to a specific Folder, for example:

https://grafana.internaldns/dashboards/f/zGLygYpDiz/platform-specific

This only works up until the point where we redeploy, as upon deployment, the UID for the folder is always dynamically created.  This also affects we scale Grafana, as we are unable to have a cluster of more than one instance at any point in time, as even though Dashboard links still work, Folder links will fail between all instances.

Therefor, would it be possible to be able to define the UID for the Folder object as part of provisioning?  For example:

``` apiVersion: 1

 providers:
 - name: 'platform-specific'
   uid: 'zGLygYpDiz'
   orgId: 1
   folder: 'Platform Specific'
   type: file
   overwrite: true
   disableDeletion: false
   editable: true
   updateIntervalSeconds: 5
   options:
     path: /var/lib/grafana/custom-dashboards/platform-specific
```

That way, we can deploy updates dynamically, as well as having the ability to scale out as needed.

**Comment by swtch1** [comment]
I'm looking to implement this right now.  As some feedback on the YAML API, does it make more sense to use `folderUID` as the UID field?  I think this calls out that it explicitly applies to the [dashboard folder](https://grafana.com/docs/reference/dashboard_folders/).

**Comment by marefr** [comment]
@swtch1 if you're referring to how to name this new property in yaml file I think `folderUID` or `folderUid` make sense.
