### ISSUE TITLE
[Bug] Dashboard links not updated when changing variables

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#12506]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.0-pre1 (cce9632)

I have found some problems with dashlinks and templating variables. By clicking into dashlink, anchor href is not updated :(

Reviewing public/app/features/dashlinks/module.ts I have found some stranger things:

- Line 48 - function update - there are lines with anchor variable (bad idea) and lines with elem.find('a') (good idea).

I have replaced anchor variable by elem.find('a') and it solved the problem. Consider to submit please.

There is a similar problem with span variable and elem.find('span')

Regards,

**Comment by marefr** [comment]
Could you please explain what you mean by "anchor href is not updated" - screenshot?

**Comment by gretamosa** [comment]
It is difficult to take a screenshot with this situation because I was debugging with Chrome inspector in module.ts line 52.

`anchor.attr('href', linkInfo.href);`

This line updates anchor variable but not the original DOM.

**Comment by marefr** [comment]
But is it a bug in UI - screenshot possible, or javascript error? At least include how you've configured your dashboard and the steps involved getting to module.ts line 52. Is a link not updating when changing template variable or what?

**Comment by gretamosa** [comment]
I think it's a javascript error. I attached a screenshot with the dashlink href and adhoc filter "Filter" with a value. Do you need another screenshot with javascript info?

Hope it helps.

![captura de pantalla 2018-07-05 a las 11 58 15](https://user-images.githubusercontent.com/16796053/42316797-f86cf50e-804a-11e8-89f5-6715b938dfdf.png)

**Comment by gretamosa** [comment]
50% markup problem, 50% javascript error :)

This HTML line 
`<a class="pointer gf-form-label" href="dashboard/db/netflow-custom-topo-real-time?from=now-1h&amp;to=now&amp;var-expIP=All&amp;var-criteria=iBytes" data-placement="bottom"><i></i> <span>netflow custom topo real-time</span></a>`

should be (like url browser bar shows)

`<a class="pointer gf-form-label" href="dashboard/db/netflow-custom-topo-real-time?from=now-1h&amp;to=now&amp;var-expIP=All&amp;var-criteria=iBytes&var-Filter=srcIP%7C%3D%7C150.100.246.43" data-placement="bottom"><i></i> <span>netflow custom topo real-time</span></a>`

This is a breakpoint when javascript error occurs.

![captura de pantalla 2018-07-05 a las 12 35 07](https://user-images.githubusercontent.com/16796053/42318663-0ab0dcc6-8050-11e8-958e-eda96a1b71c3.png)

**Comment by marefr** [comment]
Can't reproduce on latest master 5.3.0-pre1. Please try and upgrade to latest. But are you not asking of the same feature as in #12338 here?

**Comment by gretamosa** [comment]
They are related but are not the same issue. #12338 is about to extend dashlink functionalities (in the same way that dashboard list panel) and this issue is about a possible dashlink bug.

I'll upgrade to latest commit and report my results because module.ts between 5.2.0-pre1 and 5.3.0-pre1 is the same. The use of anchor variable and elem.find('a') is confusing.

**Comment by gretamosa** [comment]
Tested with 5.3.0-pre1 and happens the same issue. I've tried with new dashboards and templating variables and they are not shared between dashboards. How do you test this behavior? just for trying to reproduce.

**Comment by marefr** [comment]
Okay. Can you share your dashboard json and explain when the javascript error occur, when clicking on a link or when changing variable/adhoc filters?

**Comment by gretamosa** [comment]
I've reproduced the issue with these simplified dashboards and default datasource.

[dashboards.zip](https://github.com/grafana/grafana/files/2167198/dashboards.zip)

**Comment by marefr** [comment]
Bug reproduced. Will submit a PR to fix this. Thank you.

**Comment by AndrewStickler** [comment]
Does this bug explain why the current value of variables are not carried forward from one dashboard to another? That capability seemed to regress with 5.2.1.

**Comment by marefr** [comment]
@AndrewStickler yes
