### ISSUE TITLE
Alerts: Execution Error: tsdb.HandleRequest() error time: invalid duration $interval ￼

### ISSUE THREAD

**Issue by ouafnico** [grafana/grafana#12513]
Hi
Since last updates (5.2), my alerts rules can't work anymore.

I got : Execution Error: tsdb.HandleRequest() error time: invalid duration $interval ￼

Please include this information:
### What happened instead? It doesn't work

I'm using $interval as variable on the dashboard. On the graph, I'm using $interval as "Min time interval".
Example of request where I use an alarm 

SELECT mean("used") AS "Used" FROM "disk" WHERE ("host" = 'atlas' AND "path" = '/') AND $timeFilter GROUP BY time($__interval) fill(null)
 
On the graph, I can't put $__interval as min time, I doesn't want it. Only a real interval works, or $interval.

 Thanks

**Comment by marefr** [comment]
Seems like that never has been supported or worked as expected. The error returned from [parsing the interval](https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/model_parser.go#L43-L45) was not handled before, but now it is and that's why you see that error. Closing this and suggests you create a feature request for supporting your use case.

**Comment by SqlAdmin** [comment]
I got the same issue, Im using [percona monitoring management](https://www.percona.com/doc/percona-monitoring-and-management/deploy/server/docker.html). 

Grafana version : 5.1.3
When I tried to set any alert, its showing this error.

**Comment by scriptator** [comment]
Hi, I am running Version 5.2.4 and experience a similar error when trying to set up alerts:

`tsdb.HandleRequest() response error &{error parsing interval $__interval A 0x129521b8 [] []}`

See here my config:
![](https://i.postimg.cc/pXyG8DfK/Bildschirmfoto_2018-09-24_um_11.36.29.png)

**Comment by marefr** [comment]
@scriptator what datasource are you using?

**Comment by scriptator** [comment]
Sry, I forgot to attach the basic infos:

**What Grafana version are you using?**
--> 5.2.4

**What datasource are you using?**
--> postgres

My query looks like this:

`SELECT
  $__timeGroup(measure_date, $__interval),
  avg(value) as Dachboden
FROM
  temperature
WHERE
  $__timeFilter(measure_date) and
  sensor = 'dachboden'
GROUP BY time
ORDER BY time`

**What OS are you running grafana on?**
--> Raspbian GNU/Linux 9 (stretch)

**What did you do?**
--> Tried to install Alerts for the first time

**Comment by marefr** [comment]
@scriptator fixed in #11555 that will be included in v5.3 stable

**Comment by scriptator** [comment]
Thanks for the good news and the fast reply!

**Comment by rakeshratnam** [comment]
Hi , 

Getting same error with mysql  as datasource 
Version : Grafana v5.2.4 (0bbac5c)

error : 
firing:true
state:"alerting"
conditionEvals:" = true"
timeMs:"0.246ms"
error:"tsdb.HandleRequest() response error &{error parsing interval $time A 0xc4213186d0 [] []}"

**Comment by marefr** [comment]
@rakeshratnam same answer to you https://github.com/grafana/grafana/issues/12513#issuecomment-423962522

**Comment by rakeshratnam** [comment]
Thanks for update. I have added more info on below ticket. and I will upgrade my grafana as u suggested.

https://github.com/grafana/grafana/issues/15298

**Comment by fadeawaylove** [comment]
i meet the same problem and I haven't resolved yet

**Comment by marefr** [comment]
@fadeawaylove what Grafana version are you using and what datasource?

**Comment by cholcombe973** [comment]
I'm also hitting this problem with grafana version 6.1.0

**Comment by marefr** [comment]
@cholcombe973 what datasource are you using and what you're query looks like?

**Comment by cholcombe973** [comment]
@marefr postgres as the datasource.  The sql query for the graph is:
```
SELECT  $__time(time), lag(total_subscribed_cap_gb/total_usable_cap_gb*100) over (order by time) "Subscripted Usable Capacity" 
FROM  slo_array_srp 
WHERE  $__timeFilter(time) and region in ($datacenter) and hostname in ($name)
```

**Comment by marefr** [comment]
@cholcombe973 this is not same problem as reported in this issue. You're trying to use template variables ($datacenter and $name) in your alert rule which is not supported #6557.
