### ISSUE TITLE
Error when launching dashboard - e.to is undefined

### ISSUE THREAD

**Issue by klppt63** [grafana/grafana#12514]
I'm on Grafana 5.1.3, on Windows 7, Firefox
After closing and reopening two different dashboards, all of my panels have an error that reads

 "e.to is undefined"

and the Slack trace reads

s.calculateInterval@http://localhost:8181/public/build/app.5372b9bbcb8c6d1c027e.js:1:21238
1534/f</e.prototype.calculateInterval@http://localhost:8181/public/build/0.5c89ac3fc7a3e78b3629.js:7:16317
1534/f</e.prototype.updateTimeRange@http://localhost:8181/public/build/0.5c89ac3fc7a3e78b3629.js:7:16076
u@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:69119
l/<@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:69565
$digest@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:75262
$apply@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:77074
A/s<@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:73133
i@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:21976
me/l.defer/n<@http://localhost:8181/public/build/vendor.7bf3a4849cf75d02739a.js:87:23440

**Comment by marefr** [comment]
Please include your dashboard json model here.

**Comment by marefr** [comment]
This dashboard seems totally broken. First there's invalid json

```
"family": ""Open Sans", Helvetica, Arial, sans-serif"
```

Second, there are no time range selected. Closing this, but consider reopen if you could provide better data that underlines a possible bug.
