### ISSUE TITLE
Elasticsearch: Selecting/templating time field for date histogram

### ISSUE THREAD

**Issue by hackery** [grafana/grafana#12519]
Grafana 5.1.4, Elasticsearch datasource, Windows 7

I'm looking to provide a dashboard control to select which time field in documents is used for date histograms. This seems straightforward by creating a template variable with a list of field names (@timestamp, time, startTime, endTime, firstSeen etc) and referring to it in the grouping clause of the query editor:
 
![image](https://user-images.githubusercontent.com/308470/42377755-96e129ae-811c-11e8-8e1c-de53628dad7d.png)

![image](https://user-images.githubusercontent.com/308470/42376947-01670f40-8119-11e8-9b26-c38ae284b931.png)

However, Grafana doesn't accept a variable entered here - it reverts the entry back to the default **@timestamp** value. Actually, it also reverts if I select another date-typed field like **time** here - so perhaps this selector box has a more generic issue than templating. Should a variable be usable here?

(I've verified that when the `/api/datasources/proxy/6/my-index-*/_mapping` XHR call is made, the returned mapping is showing 'date' type for both relevant fields, as might be expected seeing the autocomplete options.)

**Comment by marefr** [comment]
Only the time field selected in datasource options is supported. There's an open issue for that #7582

**Comment by hackery** [comment]
In which case, the option to change it per query should not appear.
