### ISSUE TITLE
grafana-server.exe exiting without starting the server in Office network

### ISSUE THREAD

**Issue by vrsathi** [grafana/grafana#12527]
Hi,
I have downloaded grafana 5.0.0 and tried to run grafana-server.exe in command window on **Windows 10**.
In my **Office network** it is not starting the server and exiting after this line "Initializing Alerting". Please find below is the info from the grafana.log

Can you please help with this issue.

Note: when I run the same in my **home computer** which is not on Office network, grafana-server is coming up successfully, and I could open the page http://localhost:3000

t=2018-07-07T23:48:29+0530 lvl=info msg="Starting Grafana" logger=server version=5.0.0 commit=af6e28366 compiled=2018-02-28T23:12:58+0530
t=2018-07-07T23:48:29+0530 lvl=info msg="Config loaded from" logger=settings file=C:\\Data\\projects\\grafana-5.0.0/conf/defaults.ini
t=2018-07-07T23:48:29+0530 lvl=info msg="Path Home" logger=settings path=C:\\Data\\projects\\grafana-5.0.0
t=2018-07-07T23:48:29+0530 lvl=info msg="Path Data" logger=settings path=C:\\Data\\projects\\grafana-5.0.0\\data
t=2018-07-07T23:48:29+0530 lvl=info msg="Path Logs" logger=settings path=C:\\Data\\projects\\grafana-5.0.0\\data\\log
t=2018-07-07T23:48:29+0530 lvl=info msg="Path Plugins" logger=settings path=C:\\Data\\projects\\grafana-5.0.0\\data\\plugins
t=2018-07-07T23:48:29+0530 lvl=info msg="Path Provisioning" logger=settings path=C:\\Data\\projects\\grafana-5.0.0\\conf\\provisioning
t=2018-07-07T23:48:29+0530 lvl=info msg="App mode production" logger=settings
t=2018-07-07T23:48:29+0530 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-07-07T23:48:29+0530 lvl=info msg="Starting DB migration" logger=migrator
t=2018-07-07T23:48:29+0530 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-07-07T23:48:29+0530 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-07-07T23:48:29+0530 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-07-07T23:48:29+0530 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-07-07T23:48:29+0530 lvl=info msg="Starting plugin search" logger=plugins
t=2018-07-07T23:48:29+0530 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-07-07T23:48:29+0530 lvl=info msg="Initializing Alerting" logger=alerting.engine

**Comment by torkelo** [comment]
Can you try latest v5.2.1 it has improved logging behavior
