### ISSUE TITLE
Minor graphics bug on login screen

### ISSUE THREAD

**Issue by mafr** [grafana/grafana#12526]
After upgrading from Grafana 5.1.3, longer labels for auth.generic_oauth.name inside the sign-in button overlap with the sign-in symbol (see screenshot).

### What Grafana version are you using?
5.2.1
### What datasource are you using?
N/A
### What OS are you running grafana on?
CentOS 7. The graphics bug can be reproduced on Chrome 67.0.3396.99 and Firefox 61.0.
### What did you do?
No configuration change when upgrading. 
### What was the expected result?
Sign-In symbol and label text don't overlap.
### What happened instead?
Sign-In symbol and text overlap :)
 
<img width="666" alt="grafana-sign-in" src="https://user-images.githubusercontent.com/197857/42412371-6d830a6a-820b-11e8-8f47-221daa8d2630.png">

**Comment by torkelo** [comment]
unable to replicate, 
![image](https://user-images.githubusercontent.com/10999/42493099-c96c6530-841b-11e8-8389-daaf1aa18b29.png)

Your oauth name is too  long.

**Comment by mafr** [comment]
Err, of course it's rather long. In a corporate environment it's really helpful being able to tell users which account to use exactly (there is no other way to customize the login screen to give instructions). This used to work perfectly in 5.1.3, there's no point in breaking it, IMHO.

**Comment by torkelo** [comment]
Sorry that this caused an issue for your. We updated the design slightly on the login page.

**Comment by mafr** [comment]
No worries - it's a cosmetic thing. But most likely we're not the only ones affected :)
