### ISSUE TITLE
Session iproper handling , Exposes DB query

### ISSUE THREAD

**Issue by Girishchandra-Yendargaye** [grafana/grafana#12520]
### What Grafana version are you using?   
Grafana v5.1.3
### What datasource are you using?  
Postgres
### What OS are you running grafana on? 
Centos
### What did you do? 
database queries dashboard
### What was the expected result? 
Query output and no disclosure of queries
### What happened instead?
Disclosing queries,Session are not terminating,SQL injection it accepts

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
On Network tab its shows request as query exposes database table names etc....
Session not at all terminating after 30 minutes which I mentioned in Grafana ini file.

**Comment by marefr** [comment]
I don't understand what the problem is, please be more specific/detailed.

**Comment by Girishchandra-Yendargaye** [comment]
@marefr Sessions of grafana are not terminating automatically....Also if we do F12 query is being shown on console

**Comment by torkelo** [comment]
Grafana is a data exploration UI, it allows you to build dynamic queries and then to visualize that data. Queries are constructed and sent by the browser and there is no way to hide the query from the network traffic. Somehow the backend needs to know the query it is supposed to execute :)

**Comment by Girishchandra-Yendargaye** [comment]
@torkelo What about sessions?

**Comment by torkelo** [comment]
what about them? remove your session & remember cookie and you will be forced to login again
