### ISSUE TITLE
Escaping custom template variable with multi-select

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#12528]
### What Grafana version are you using?
5.1.2
### What datasource are you using?
Prometheus 2.1
### What OS are you running grafana on?
RHEL 7
### What did you do?
1. Create custom template variable `var1` with the following values: `[a-z]+,[0-9]+,u,c` 
2. Create a panel with metric: `rate(my_metric_total{ptype=~"$var1"}[1m])`
3. Test that the metric works fine. 
   3.1. when I select specific value like "u" or "c" the the graph shows only that metric.
   3.2 when  selecting either of the regExp "[a-z]+" or "[0-9]+" graph is rendered with all possible values of `ptype` in the DB that match the pattern.
4. Now, change the template variable `var1` to allow **Multi-value**.
### What was the expected result?
1. First I'd expect the variable and panel to work like in 3 above on a single value.
2. I'd expect the selection of multiple values to work as well.
### What happened instead?
With `multi-value` enabled, only simple values are working properly. for example "u", "c" or both.
values that contain reg-exp aren't working at all.

### network request 

when the variable is not marked as multi-select, there is no extra escaping:

![image](https://user-images.githubusercontent.com/6409857/42415153-52ea7696-824e-11e8-99d1-ce80b51a7cc2.png)

With multi-select, there is additional escaping of characters like "[]+" with double back slash \\:
 
![image](https://user-images.githubusercontent.com/6409857/42415126-8a642988-824d-11e8-8c13-4faf29b6f474.png)

### suggestion for fix:
in multi-value variable escape only the pipe "|", or make a configuration whether to escape the values or not (in my case i'd probably avoid escaping)

**Comment by torkelo** [comment]
by default multi valued regex values are regex escaped, try using ${templateVar:raw} to  disable any escaping

**Comment by yarix** [comment]
thank you for the reply and the advice.
I'd like to mention that using raw, doesn't help:
`rate(my_metric{lbl1="maps",instance="abc:8776", ptype=~"\\[0-9\\]\\+|c:raw"}[1m])`

Making the escaping as configuration (on the variable definition) can be helpful.
Currently, Grafana have inconsistency for variables that contains regex values. 
meaning that regex values in variables that aren't multi-select works perfectly, while on multi-select they just break.

i suppose that `|` is the special case here.

**Comment by torkelo** [comment]
${templateVar:raw} works fine here. Can you try v5.2 ?

**Comment by exceting** [comment]
@torkelo
Hello, we have the same question, our version is v6.1.4, and our config like this:
```
sum(rate(http_server_count{app="$app",method=~"${http_method:raw}",env="$env"}[5m])) by (method)
```
but useless, our http_method like "/pgc/moe/2018/{area:1|2}/api/character/follow/list"  still escaped.

**Comment by netham45** [comment]
Yea, using ${var:raw} doesn't do anything. @torkelo 's suggestion _does not work_. Additionally There's absolutely no need to be applying random escaping to a string before it's sent to a server, especially when all that's selected is 'All' and I have a manual override for 'All'.

How about the option that people asked for years ago instead of terrible "workarounds"?
