### ISSUE TITLE
graphs not showing

### ISSUE THREAD

**Issue by Nurlan199206** [grafana/grafana#12538]
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
```

Please include this information:
### What Grafana version are you using?
5.2.1
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu 17.10 64bit

green line sometimes dissapearing, how to fix that?
 my query: `rate(node_disk_read_time_ms{device="sda1",instance="localhost:9100",job="node"}[5m])/rate(node_disk_reads_completed{device="sda1",instance="localhost:9100",job="node"}[5m])
`
![graph1](https://user-images.githubusercontent.com/22808731/42448258-78531180-839e-11e8-9dcd-e6c06120be19.PNG)

**Comment by torkelo** [comment]
Please include response from Prometheus when the graph is not being shown.

**Comment by Nurlan199206** [comment]
This?
![grafana chart](https://user-images.githubusercontent.com/22808731/42458084-f9e4e842-83ba-11e8-9f0b-1bb6af258553.PNG)


`{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"device":"sda1","instance":"localhost:9100","job":"node"},"values":[[1531144425,"7.163841807909605"],[1531144440,"7.757894736842106"],[1531144455,"7.871313672922252"],[1531144470,"7.739837398373984"],[1531144485,"8.237837837837837"],[1531144500,"8.266666666666667"],[1531144515,"8.054945054945055"],[1531144530,"8.053333333333333"],[1531144545,"7.967567567567568"],[1531144560,"7.945799457994581"],[1531144575,"8.345945945945944"],[1531144590,"8.292682926829269"],[1531144605,"8.443243243243241"],[1531144620,"8.650666666666668"],[1531144635,"8.67032967032967"],[1531144650,"8.825737265415551"],[1531144665,"8.767567567567568"],[1531144680,"8.885333333333334"],[1531144695,"8.9010989010989"],[1531144710,"8.842666666666666"],[1531144725,"8.297994269340974"],[1531144740,"8.300268096514746"],[1531144755,"8.192513368983958"],[1531144770,"7.6353887399463805"],[1531144785,"7.521739130434782"],[1531144800,"7.683377308707124"],[1531144815,"7.565217391304347"],`[1531144830,"7.95778364116095"],[1531144845,"8.224598930481283"],[1531144860,"7.914209115281501"],[1531144875,"8.010695187165776"],[1531144890,"7.924932975871314"],[1531144905,"8.41304347826087"],[1531144920,"8.453825857519789"],[1531144935,"8.25"],[1531144950,"8.118598382749326"],[1531144965,"7.946236559139783"],[1531144980,"7.681697612732096"],[1531144995,"7.763440860215053"],[1531145010,"7.79840848806366"],[1531145025,"7.728045325779037"],[1531145040,"7.978142076502732"],[1531145055,"8.044077134986226"],[1531145070,"8.350132625994695"],[1531145085,"8.28415300546448"],[1531145100,"8.291105121293802"],[1531145115,"7.967213114754098"],[1531145130,"7.611859838274933"],[1531145145,"7.617486338797813"],[1531145160,"7.568733153638815"],[1531145175,"7.4863387978142075"],[1531145190,"6.970822281167109"],[1531145205,"6.972677595628415"],[1531145220,"7.008086253369273"],[1531145235,"7.236559139784947"],[1531145250,"7.342318059299192"],[1531145265,"7.508196721311475"],[1531145280,"7.428571428571428"],[1531145295,"7.431693989071038"],[1531145310,"7.522546419098143"],[1531145325,"7.363128491620111"],[1531145340,"7.335120643431636"],[1531145355,"7.427055702917771"],[1531145370,"7.354166666666666"],[1531145385,"7.252631578947367"],[1531145400,"8.58"],[1531145415,"8.772277227722773"],[1531145430,"8.62899262899263"],[1531145445,"8.673366834170855"],[1531145460,"9.179361179361178"],[1531145475,"9.316582914572864"],[1531145490,"9.274074074074074"],[1531145505,"9.472636815920398"],[1531145520,"9.674185463659148"],[1531145535,"9.678391959798995"],[1531145550,"9.765586034912717"],[1531145565,"9.73469387755102"],[1531145580,"9.662468513853904"],[1531145595,"9.701030927835053"],[1531145610,"9.56743002544529"],[1531145625,"9.724867724867725"],[1531145640,"9.248"],[1531145655,"9.344086021505374"],[1531145670,"9.454545454545455"],[1531145685,"8.08864265927978"],[1531145700,"7.977464788732394"],[1531145715,"8.101123595505618"],[1531145730,"8.022408963585434"],[1531145745,"7.488636363636363"],[1531145760,"7.252124645892351"],[1531145775,"7.0229885057471275"],[1531145790,"6.814814814814814"],[1531145805,"7.497142857142858"],[1531145820,"7.304843304843304"],[1531145835,"7.131428571428572"],[1531145850,"7.11111111111111"],[1531145865,"7.889807162534435"],[1531145880,"7.835164835164835"],[1531145895,"7.9449035812672175"],[1531145910,"7.89010989010989"],[1531145925,"8.068376068376066"],[1531145940,"8.131868131868131"],[1531145955,"8.055096418732782"],[1531145970,"7.966850828729282"],[1531145985,"7.878787878787878"],[1531146000,"7.86021505376344"],[1531146015,"7.838274932614556"],[1531146030,"7.772972972972973"],[1531146045,"7.7088948787062"],[1531146060,"8.29032258064516"],[1531146075,"8.582210242587601"],[1531146090,"7.61290322580645"],[1531146105,"7.7088948787062"],[1531146120,"7.784946236559139"],[1531146135,"7.881401617250675"],[1531146150,"7.1754874651810585"],[1531146165,"7.273743016759775"],[1531146180,"7.153203342618385"],[1531146195,"7.128491620111731"],[1531146210,"7.036011080332409"],[1531146225,"6.8439306358381495"],[1531146240,"6.919220055710306"],[1531146255,"6.815642458100559"],[1531146270,"6.745098039215686"],[1531146285,"6.7011494252873565"],[1531146300,"6.821529745042493"],[1531146315,"6.965909090909091"],[1531146330,"7.226890756302521"],[1531146345,"6.674157303370786"],[1531146360,"6.509803921568628"],[1531146375,"6.584269662921348"],[1531146390,"6.487394957983192"],[1531146405,"6.370786516853932"],[1531146420,"6.5322128851540615"],[1531146435,"6.426966292134832"],[1531146450,"6.296918767507003"],[1531146465,"6.370786516853932"],[1531146480,"6.46498599439776"],[1531146495,"6.561797752808989"],[1531146510,"6.65546218487395"],[1531146525,"6.786127167630057"],[1531146540,"7.011363636363636"],[1531146555,"7.226519337016575"],[1531146570,"7.257617728531855"],[1531146585,"7.224719101123596"],[1531146600,"7.030640668523678"],[1531146615,"6.8522727272727275"],[1531146630,"6.884507042253522"],[1531146645,"6.790960451977401"],[1531146660,"6.602816901408451"],[1531146675,"6.659090909090909"],[1531146690,"6.647887323943662"],[1531146705,"7.254237288135593"],[1531146720,"7.323943661971832"],[1531146735,"7.412429378531074"],[1531146750,"7.425352112676056"],[1531146765,"7.401129943502824"],[1531146780,"7.410764872521248"],[1531146795,"7.378531073446329"],[1531146810,"7.308781869688386"],[1531146825,"7.188235294117647"],[1531146840,"7.034883720930231"],[1531146855,"7.253481894150417"],[1531146870,"7.144444444444445"],[1531146885,"7.276712328767123"],[1531146900,"7.224043715846995"],[1531146915,"7.276712328767123"],[1531146930,"7.3186813186813175"],[1531146945,"7.53972602739726"],[1531146960,"7.661202185792349"],[1531146975,"7.790633608815428"],[1531146990,"7.005464480874316"],[1531147005,"7.173553719008264"],[1531147020,"7.027322404371584"],[1531147035,"7.041322314049586"],[1531147050,"6.9230769230769225"],[1531147065,"6.761643835616439"],[1531147080,"6.747252747252747"],[1531147095,"6.597260273972602"],[1531147110,"6.538461538461538"],[1531147125,"6.598290598290597"],[1531147140,"6.379310344827587"],[1531147155,"7.4301369863013695"],[1531147170,"7.374301675977654"],[1531147185,"7.473389355742297"],[1531147200,"7.524861878453039"],[1531147215,"7.523545706371191"],[1531147230,"7.946808510638298"],[1531147245,"7.786666666666667"],[1531147260,"7.714285714285714"],[1531147275,"7.701333333333333"],[1531147290,"7.48936170212766"],[1531147305,"7.722666666666667"],[1531147320,"7.723404255319149"],[1531147335,"7.787798408488063"],[1531147350,"7.914893617021277"],[1531147365,"8"],[1531147380,"8.01063829787234"],[1531147395,"8.085333333333333"],[1531147410,"8.117021276595745"],[1531147425,"8.165289256198347"],[1531147440,"7.166666666666667"],[1531147455,"7.13091922005571"],[1531147470,"7.0055248618784525"],[1531147485,"7.444141689373298"],[1531147500,"7.380434782608695"],[1531147515,"6.798866855524079"],[1531147530,"6.824858757062147"],[1531147545,"7.202279202279201"],[1531147560,"7.220338983050848"],[1531147575,"7.376770538243625"],[1531147590,"7.35195530726257"],[1531147605,"7.518207282913165"],[1531147620,"7.741573033707865"],[1531147635,"7.809523809523809"],[1531147650,"7.64245810055866"],[1531147665,"7.663865546218488"],[1531147680,"7.58659217877095"],[1531147695,"7.495798319327732"],[1531147710,"7.40983606557377"],[1531147725,"7.803814713896458"],[1531147740,"8.072538860103629"],[1531147755,"8.238341968911918"],[1531147770,"8.01036269430052"],[1531147785,"8.119700748129675"],[1531147800,"7.894988066825776"],[1531147815,"7.786046511627908"],[1531147830,"7.371298405466971"],[1531147845,"7.348416289592761"],[1531147860,"7.381165919282511"],[1531147875,"7.325740318906606"],[1531147890,"7.148558758314856"],[1531147905,"6.844827586206896"],[1531147920,"6.6809421841541745"],[1531147935,"6.669509594882729"],[1531147950,"6.658119658119659"],[1531147965,"6.54320987654321"],[1531147980,"6.599597585513079"],[1531147995,"6.629482071713148"],[1531148010,"6.526732673267327"],[1531148025,"6.306382978723404"]]}]}}

**Comment by Nurlan199206** [comment]
guess i found it, checkbox was checked, it possible because of this?

![grafana checkbox](https://user-images.githubusercontent.com/22808731/42459005-cb8e1188-83bc-11e8-8997-e64405e3a12a.PNG)

**Comment by Nurlan199206** [comment]
i am edited my query, now showing 0ms too, my current query is a below.

`rate(node_disk_read_time_ms{device="sda1",instance="localhost:9100",job="node"}[5m])`

**Comment by torkelo** [comment]
Ok, so I can close?
