### ISSUE TITLE
Include immutable for plugin development

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#12539]
What are thoughts on including and exposing immutable to plugins? 

I am working with react component in plugins, and it would be great to start having immutable as a standard component.

It is easy enough to include in the plugins, but since you can not reuse dependencies it is kinda anoying

Thoughts?

**Comment by torkelo** [comment]
do you mean https://github.com/facebook/immutable-js ?

**Comment by ryantxu** [comment]
yes -- it is similar to lodash, but well immutable :)

It is very commonly used in react land.  It is included in https://github.com/grafana/influxdb-flux-datasource

**Comment by torkelo** [comment]
sure, submit PR :)
