### ISSUE TITLE
Dashboard links variable values can't change 

### ISSUE THREAD

**Issue by eddiewang927** [grafana/grafana#12536]
Please include this information:
### What Grafana version are you using?
V5.2.1
### What datasource are you using?
ES6.2.4
### What OS are you running grafana on?
CentOS 6.6
### What did you do?
Upgrade 4.6.2 to 5.2.1
### What was the expected result?
When changed Dashboard variables, Links's variables should be change
### What happened instead?
Dashboard links variables not change, I need to reflash browser can be change

![34](https://user-images.githubusercontent.com/40748334/42437362-7d9081fa-838f-11e8-8697-21590f8086e7.png)

![33](https://user-images.githubusercontent.com/40748334/42437369-80ac059e-838f-11e8-98f0-096cb1f64929.png)

**Comment by marefr** [comment]
Fixed in #12506
