### ISSUE TITLE
[Feature] Allow transforming two existing annotations into a region via the annotations API

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#12547]
### What Grafana version are you using?
v5.3.0 

Currently, we can only create regions via the UI or via a single API call. The limitation of this is if you're unsure of the ending time for your region (e.g., an alert starts but hasn't completed). While it's possible to keep track of these epochs, and create the full region later (also being sure to delete the original annotation), a more intuitive way is to transform two annotations into a region directly.

An example call for this would be:
`curl -vv -X PUT -H "Content-Type: application/json"  -H "Authorization: Bearer eyJrI...WQjF9" -d '{"regionId":100,"regionEndAnnotationId":2,"isRegion":true}' http://localhost:3000/api/annotations/1`

This would transform annotation `1` and `2` into a single region with id `100`.

**Comment by ryantxu** [comment]
In #17647, you can just set the startTime and endTime on a single annotation event to make a region

**Comment by ryantxu** [comment]
@calebtote this is now possible in master and will be released in 6.4

every annotation now has a startTime and endTime -- if they are different, it is a region
