### ISSUE TITLE
Editor can't add dashboard

### ISSUE THREAD

**Issue by xpinkyx** [grafana/grafana#12543]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.1 (commit: 2040f61)
### What datasource are you using?
I think it isn't important for this issue
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
I created some users and gave them Viewer permissions. Then I put some of them to Team A. I created Folder A and gave Team A viewer permission. Then I assigned one of the users, who's also in Team A, edit permission in Folder A.
### What was the expected result?
The user with the permission to edit in Folder A can create and save new dashboards in Folder A.
### What happened instead?
When this user hit the save button, grafana says "! Access denied to save dashboard." Editing existing dashboards works as expected.
Maybe it's similiar to #10671

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by torkelo** [comment]
If you try latest nightly this should be fixed!

**Comment by xpinkyx** [comment]
Yes, I tried with nightly build and now it works. But grafana crashes whenever there's an installed plugin (I tried with Pie Chart, Annotation and Clock Panel) on a dashboard or when I try to add one of those panels. Should I open a new issue for that?

**Comment by torkelo** [comment]
That is fixed as well I think or we have PR fix, think it was merged yesterday
