### ISSUE TITLE
Case sensitive for username on login

### ISSUE THREAD

**Issue by tecmatia-dp** [grafana/grafana#12549]
### What Grafana version are you using?
5.2.1
### What did you do?
Normal login, with users in Grafana DB
### What was the expected result?
Username should be case insensitive, as in most systems
### What happened instead?
Username is case sensitive.

**Comment by torkelo** [comment]
> Username should be case insensitive, as in most systems

Is that common? it's usually case sensitive. Not sure we can change this at this point.

**Comment by lukecyca** [comment]
Would you accept a PR to fix this?

**Comment by tonglil** [comment]
Would like to see Grafana not break on username case sensitivity.

**Comment by marefr** [comment]
After some investigations seems like the different supported database engines handles unique indices differently. Sqlite and Postgres allows same login and email with different casing, but MySQL does not. Sqlite and Postgres:

![image](https://user-images.githubusercontent.com/1668778/46301885-d9422080-c5a7-11e8-905a-3e90aa0c033f.png) 

Due to this we should probably enforce lowercase for logins and email addresses and always lowercase all input when searching/looking for user by login/email so that all comparisons always are made case insensitive. Need to think about how to handle migrations of possible duplicates for sqlite and postgres.

One possible alternative to consider would be to investigate if it's possible to enable case insensitive matches in our database ORM library.

**Comment by torkelo** [comment]
not yet, but we would like to fix this. Just unsure of how to handle the migration and merging of duplicate users.

The schema migration system allows to execute code with multiple lines of SQL as part of a single "migration transaction", https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/user_mig.go#L134

Need to write one that can handle merging of duplicate users

**Comment by nmaludy** [comment]
FYI this just bit me. 

Our LDAP source (Active Directory) commonly sets `userPrincipalName` with mixed case like so: `First.Last@sub.domain.tld`.

We routinely are able to login to other LDAP enabled sources without needing the specify the exact case of the username. Other sources include things like: VMware, Citrix, SolarWinds, StackStorm, etc.

The weird thing for me was: I could login to the WebUI with all lower case, even though the LDAP credential in the directory is MixedCase, however i could **NOT** authenticate with the API using all lower case, i had to use MixedCase to get it working.

**Comment by florianwgnr** [comment]
More tolerance on spaces would be great for user experiene. What i mean:

With the username in Grafana set to "Test" you cant login - as mentioned above - by typing "test" in the login form. But also adding a space after the username stops you from getting in. I experienced this issue with android autocomplete, it adds a space after the completed word and this prevents the login. 

Try logging into your github account with your username, some letters uppercase and adding a whitespace after it. Works fine and Grafana should handle it accordingly.

**Comment by dmpe** [comment]
This just bit me as well. My goal is to have both ldap **and** oauth (gitlab) and while both work ok, only with ldap am I able to configure admin users as well. 
When using gitlab auth, my username is (displayed as) lowercase causing grafana to think that I am not the same user as compared to when I login using LDAP (which uses uppercase notation). Hence I now have to users, both with the same username - the uppercase (via LDAP) is admin, the lowercase (vit gitlab) is not.

**Comment by mehdisadeghi** [comment]
This just bit me as well. Many users reported problem logging in, just to realize they all enter variants of their email addresses. I have also installed grafana with the official helm chart.

**Comment by apellew** [comment]
We have had this problem as well - when users are set up and email addresses are copy/pasted in and aren't all in lower case. Slightly frustrating.

**Comment by padraic-padraic** [comment]
Just to mention we have also had this issue. Users have tried to log in with different cases, and even gone as far as to try and reset their password (which also fails due to case sensitive lookups), causing lots of frustration.

**Comment by lukecyca** [comment]
My solution is to force all logins and emails to be lowercase. This way you can create a user with mixed case, but it gets stored in lowercase. You can login with mixed case, but it is mapped to lowercase prior to authenticating. This effectively achieves case-insensitive matching.

I have patched my version 6.7.4 of Grafana with the following solution:

```diff
diff --git a/pkg/services/sqlstore/user.go b/pkg/services/sqlstore/user.go
index c401ef18bb..e4e388bee9 100644
--- a/pkg/services/sqlstore/user.go
+++ b/pkg/services/sqlstore/user.go
@@ -61,9 +61,9 @@ func CreateUser(ctx context.Context, cmd *models.CreateUserCommand) error {
 
                // create user
                user := models.User{
-                       Email:         cmd.Email,
+                       Email:         strings.ToLower(cmd.Email),
                        Name:          cmd.Name,
-                       Login:         cmd.Login,
+                       Login:         strings.ToLower(cmd.Login),
                        Company:       cmd.Company,
                        IsAdmin:       cmd.IsAdmin,
                        IsDisabled:    cmd.IsDisabled,
@@ -156,6 +156,9 @@ func GetUserByLogin(query *models.GetUserByLoginQuery) error {
                return models.ErrUserNotFound
        }
 
+       // Ensure case insensitive login matching.
+       query.LoginOrEmail = strings.ToLower(query.LoginOrEmail)
+
        // Try and find the user by login first.
        // It's not sufficient to assume that a LoginOrEmail with an "@" is an email.
        user := &models.User{Login: query.LoginOrEmail}
@@ -188,7 +191,7 @@ func GetUserByEmail(query *models.GetUserByEmailQuery) error {
                return models.ErrUserNotFound
        }
 
-       user := &models.User{Email: query.Email}
+       user := &models.User{Email: strings.ToLower(query.Email)}
        has, err := x.Get(user)
 
        if err != nil {
@@ -207,8 +210,8 @@ func UpdateUser(cmd *models.UpdateUserCommand) error {
 
                user := models.User{
                        Name:    cmd.Name,
-                       Email:   cmd.Email,
-                       Login:   cmd.Login,
+                       Email:   strings.ToLower(cmd.Email),
+                       Login:   strings.ToLower(cmd.Login),
                        Theme:   cmd.Theme,
                        Updated: time.Now(),
                }
```

In addition, one must edit any existing users in the database to set their login and email fields to lower case:

```sql
UPDATE user SET login = LOWER(login), email = LOWER(email);
```

Of course both of these columns have UNIQUE constraints, so if you have multiple user records with the same email or login values (differing only by case) then you need to resolve those first.

This solution works for login, password reset, and creating/editing users. It does not work when searching for users (which is still case sensitive) but that is acceptable for me.

Grafana devs: if this is more useful as PR I'm happy to make one. However I suspect the above is not a sufficiently complete solution for you to consider merging.

**Comment by deepminimal** [comment]
> I have patched my version 6.7.4 of Grafana with the following solution:

Hello! Should I compile APP or just edit this block and restart service?

**Comment by vsile** [comment]
We use Grafana 7.3.1 and have the same issue.
In our case I tried to reset the password.
We have the next email related to user in our user list -  "Myemail@domain.com"

So I clicked "Forgot password" and specified the email "myemail@domain.com". But I haven't got the email.
When I specified the email "Myemail@domain.com" - I have got it.

I think an email should be case insensitive. @torkelo

**Comment by mhollstein** [comment]
Second user object after LDAP login - because of some uppcase letters 

![Second user object after LDAP login](https://user-images.githubusercontent.com/56024424/129710808-c692937a-15e6-45b7-8cf7-61c756573a72.gif)

**Comment by pkolyvas** [comment]
Hey all! 

We're going to close this issue in favor of #41831 - which is an Epic to track the work. After some consideration we have a path to get us from where we are today to where we can enforce lowercase usernames and passwords. 

We've broken the process into parts and will work towards complete resolution - ideally by Grafana 9. You can follow the epic for progress and discussion.
