### ISSUE TITLE
Support PATCH verb in annotations http api

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#12546]
### What Grafana version are you using?
v5.3.0

### What did you do?
Calling a PUT for /api/annotations/ to update an existing annotation

### What was the expected result?
The values passed in would be added to the annotation, without loss of existing data

### What happened instead?
Fields not passed in are nulled out

An example request looks like the following:
`curl -vv -X PUT -H "Content-Type: application/json"  -H "Authorization: Bearer eyJrIjoiTj...iOjF9" -d '{"text":"Annotation Description"}' http://localhost:3000/api/annotations/1`

Before the `PUT`, the annotation contains several other data (e.g., tags, time, etc.). When updating the annotation with `"text":"Annotation Description"`, fields not passed in are nulled out.

**Comment by marefr** [comment]
Changed this to a feature request and changed the title since PUT http verb you should always provide a full payload with all properties set. Patch verb should be used for updating only certain properties.

**Comment by SamuelToh** [comment]
@marefr Maybe for `PUT` operation we can add a validation to raise error when one or more tags are not specified in the request. Do you think is it worth doing it?

I'm happy to raise the issue to do the validation and contribute back.

**Comment by marefr** [comment]
> Do you think is it worth doing it?

Doesn't make sense to me giving my earlier comment.

If your interested in contributing back I recommend trying to add support for the PATCH verb

**Comment by SamuelToh** [comment]
Ok. Got it, after having a look again yes it does not make sense. 

Yes. I will give the `PATCH` verb a go.
