### ISSUE TITLE
Support passing user's OAuth identity to datasources 

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#12556]
Historically, secure connections between grafana and datasources have been managed by certs or tokens- however this is a blanket approach to authorization. Instead, I would like the option for datasource requests to be enriched with the **per-user** oauth information grafana gets during the authentication process.

Since my datasource and grafana _both_ receive authentication from google oauth, I would like grafana to bubble the user token through, so when grafana contacts my application, I can do my own authorization based off the identity of the user. 

I've found some questions in the forums/issues about this
https://community.grafana.com/t/oauth2-authentication-with-a-custom-datasource-plug-in/880
https://community.grafana.com/t/generic-oauth-send-authorization-header-during-opentsdb-queries/5511/3
https://github.com/grafana/grafana/issues/2132

There is talk about adding the oauth information into the grafana user session in this thread, https://github.com/grafana/grafana/issues/12131 but I don't think exposing the identity to datasources is within the scope of that issue.

Thoughts I had around potential issues:
- Could this support datasources with `HTTP Access = Browser`? Doing so would require exposing the `id_token` to the frontend, which theoretically could be misused by a malicious plugin. Perhaps this feature would only make sense when the datasource has `HTTP Access = Server`?
- UX? A grafana instance may have oauth, ldap, and simple users. Perhaps a checkbox of `Include OAuth Authorization Headers (If available)` on the datasource config and leaving it up to the remote datasource to decide what to do if the headers are there?

Would the team be interested in reviewing a PR for this feature?

**Comment by seanlaff** [comment]
Looking into this, I think the path forward would be:

1. Handling the different ways of parsing the `access_token`/`refresh_token`/`id_token`- which grafana already has some logic around (see the `generic_oauth` handler looking for the `id_token` and falling back to the `/userinfo` endpoint if it fails to find it)
2. Persist the token and refresh token to the database (encrypted)
3. Have a datasource setting that lets a user control when the server proxy appends the header `Authorization: Bearer mytoken`
4. Handle the oauth token refresh logic (which already exists in the datasource `routes` code for `client_credentials` oauth... but would need to be abstracted)
5. Update documentation to explain that this feature should be likely be used in conjunction with configuring sensible `scopes` in the grafana oauth configs (to reduce the potential damage a compromised grafana could do, i.e a scope along the lines of  `read:data`. or whatever you've set up in your ID provider that controls data access in your downstream system.)

**Comment by Ilanak** [comment]
@seanlaff , I'm also interested in this feature. 
Do you have any update on that? 
Do you know if this in Grafana's roadmap?

**Comment by Asgoret** [comment]
@Ilanak 

If you want connect Grafana to Prometheus inside OKD/Kuberenetes (last version deployed as prometheus operator).

Datasource:
```
{
"name": "okd",
"type": "prometheus",
"typeLogoUrl": "",
"access": "proxy",
"url": "https://{prometheus_url}",
"basicAuth": false,
"withCredentials": false,
"jsonData": {
    "tlsSkipVerify":true,
    "httpHeaderName1":"Authorization"
},
"secureJsonData": {
    "httpHeaderValue1":"Bearer {service_account_token}"
}
}
```
Create command:
```
curl --insecure -H "Content-Type: application/json" -u admin -p "http://localhost:3000/api/datasources" -X POST -d "@oauth.json"
```

**WORK ONLY ON 5.4.3**

Date: 04.02.2019
