### ISSUE TITLE
Trouble with deleting users in Grafana v5.1.4

### ISSUE THREAD

**Issue by melnikdima90** [grafana/grafana#12558]
Hi
I had Grafana 4.x
I upgraded to Grafana v5.1.4

I deleted current users from Grafana using web.
The user was deleted and disappeared from the user list.
I tried to create a user with the same login.
But the system does not allow it to be created.

I can login to the system under the old login and password is obtained, but not a single dashboard.
So the user was not completely removed from the database.

I use influx DB
Can you help me where grafana save users account?

**Comment by torkelo** [comment]
You probably only removed the user from the current org , go to server admin > users and remove it ther

**Comment by melnikdima90** [comment]
No! You are not right!
I deleted users from “server admin > users”.

**Comment by torkelo** [comment]
Super strange, can you replicate? Any info in the server log?

**Comment by melnikdima90** [comment]
I use influx DB
Can you help me where grafana save users account?
I want check deleting users in database.

**Comment by torkelo** [comment]
Unable to replicate this.

Deleting a user from this view, and it is removed from all orgs & user table. I can no longer login with this user. 

![image](https://user-images.githubusercontent.com/10999/42568230-b935f374-850c-11e8-868c-3c1a92c17ef9.png)

Maybe you have LDAP configured and the user is created when you try to login again?

**Comment by torkelo** [comment]
?? Grafana does not save users in influxdb but in its own database (by default SQLite3) stored in /var/lib/grafana
