### ISSUE TITLE
[Feature] Allow assign different home dashboard for each team

### ISSUE THREAD

**Issue by tecmatia-dp** [grafana/grafana#12550]
Hi all,
In some cases we have different teams, with many users, and with separate access to certain dashboards.
I think it would be interesting to be able to assign different default home dashboard for each team.
Now we are creating a wellcome "dummy" dashboard...It's not the end of the world, but i think it would be interesting.
Thanks.

**Comment by DanCech** [comment]
The problem would be deciding what to do when a user is a member of multiple teams

**Comment by torkelo** [comment]
yes, but I like the idea of having a home "page" for a team. Can list popular dashboards that the team has access etc?

maybe something inspired by trellos landing page. 

![image](https://user-images.githubusercontent.com/10999/42492924-35774e08-841b-11e8-94f9-e3645704b919.png)

But yea, this needs some design & thought.
