### ISSUE TITLE
Coudn't set the graph's title with using variables 

### ISSUE THREAD

**Issue by nidzelska** [grafana/grafana#12559]
### What Grafana version are you using?
v5.1.3
### What datasource are you using?
InfluxDB
### What did you do?
I added 2 graphs in 1 Dashboard for channel monitoring. From DB it came with tags - name and group. 
In title for every graphs in dashboard I used $name ( so every graph automatically got different names) 
When I set up variable "group" (SHOW TAG VALUES WITH KEY = "group" WHERE "name" =~ /^$name$/) it showed me the right result(in Preview of values) , but after using it in the graph's title like: $name - $group - all of graphs got the same group's tag, but different names. 
### What was the expected result?
In graph's title channel with different names get different groups
### What happened instead?
 All of graphs got the same group's tag, but different names.

**Comment by DanCech** [comment]
Variable queries are executed at the dashboard level not per-panel, so that won't work.  I'm not sure if there is a way to do what you're looking for in Grafana.

**Comment by torkelo** [comment]
Not sure I understand you. You can use variables in panel titles, you cannot use panel query results in the title .

Please include dashboard json and explain your compete scenario (all variables and panel setup)

**Comment by nidzelska** [comment]
![screenshot from 2018-07-10 21-27-29](https://user-images.githubusercontent.com/39418013/42529832-29797a0a-8488-11e8-83b8-e173493b07d0.png)
![screenshot from 2018-07-10 21-31-08](https://user-images.githubusercontent.com/39418013/42529975-98a57f1e-8488-11e8-8c17-7c7e721a20fd.png)
![screenshot from 2018-07-10 21-32-08](https://user-images.githubusercontent.com/39418013/42530018-ba523940-8488-11e8-8739-32150b661f94.png)

So, if you see at the picture - there are different names of channel, but the same value of group. 
How can I make it work?

[test.txt](https://github.com/grafana/grafana/files/2181729/test.txt)

**Comment by nidzelska** [comment]
![screenshot from 2018-07-10 21-32-08](https://user-images.githubusercontent.com/39418013/42532067-6651733c-848e-11e8-881f-323e8550778a.png)
![screenshot from 2018-07-10 21-31-08](https://user-images.githubusercontent.com/39418013/42532068-667ab08a-848e-11e8-8d22-81a14dae3a4c.png)
![screenshot from 2018-07-10 21-27-29](https://user-images.githubusercontent.com/39418013/42532070-669e88fc-848e-11e8-88fb-9ea6e453d3bf.png)
So, as you see at the picture - there are different names of channels, but the same values of group.
How can I make it work?
[test.txt](https://github.com/grafana/grafana/files/2181812/test.txt)

**Comment by DanCech** [comment]
The variable system does not support one variable being dependent on the value of the specific instance of another variable used in a repeating row/panel.

**Comment by nidzelska** [comment]
Is there any other way to do what I'm looking for?
Because it works for names, it gets different names by using $name.
After doing SHOW TAG VALUES WITH KEY = "group" WHERE "name" =~ /^$name$/  i can see the result I want to add in graph's title? but I can't add it -- >>
![image](https://user-images.githubusercontent.com/39418013/42533028-55ea8e90-8491-11e8-9748-186187e4c0fa.png)

**Comment by DanCech** [comment]
What happens is that when the dashboard loads the query for `$name` is run and it returns a list of names, then that list of names is used to run the query for `$group`, and it returns a list of groups.

To render the repeating panel, the dashboard loops over the list of `$names` to create each panel *but it does not re-run the query for $group*, so each panel gets the same value.

**Comment by nidzelska** [comment]
Okay, I understand. But how can I re-run the query for $group?  Or it just won't do it?

**Comment by torkelo** [comment]
Nope, you will have construct your dashboard programatically
