### ISSUE TITLE
worldmap threshold not working with negative value

### ISSUE THREAD

**Issue by franzbeppe** [grafana/grafana#12553]
Hello,
configuring threshold on WorldMap plugin does not work as expected when using negative value and 2 threshold.
I set these thresholds: -65,-75 using 3 different colours.
However value between -65 and -75 never get the correct colour.
I'm using Grafana 4.5.2, datasource InfluxDB, and Grafana is running on a CentOS 7.

Francesco

**Comment by torkelo** [comment]
please open issue in worldmap repo, https://github.com/grafana/worldmap-panel
