### ISSUE TITLE
Absolute URI links in dashboards broken between 5.1.5 and 5.2.0

### ISSUE THREAD

**Issue by RobinsonWM** [grafana/grafana#12560]
This appears to be a regression with using absolute URIs for links in Table panels in Grafana 5.2.0.

I'm running Grafana 5.2.1 on Windows Server 2016 Version 1607 x64.  I'm using a Table panel to show the results of an InfluxDB query.  One of the columns in the query result is a string field that contains absolute URIs (the string looks like `http://localhost:8000/dashboard/snapshot/b7ea30a22f9e46079376ba664883501d`.)  On the Table panel under **Column Styles**, I have **Render value as link** enabled, and in the **Url** field, I specified the column that contains the absolute URI, like `${__cell_1}`.  I have **Open in new tab** checked.
In Grafana 5.1.5, I could click the cell, and it would send my browser to that absolute URI.  In Grafana 5.2.0 and 5.2.1, it instead sends my browser to `http://localhost:8000/http://localhost:8000/dashboard/snapshot/b7ea30a22f9e46079376ba664883501d`, and I see a "Not found" page.  It appears to be incorrectly prefixing my absolute URI with the URI of InfluxDB itself.

The workaround appears to be clicking the link, which sends me to the "Not found" page, and then manually removing the first part of the URI in the web browser in order to navigate to the correct URI.

**Comment by torkelo** [comment]
you need to use ${__cell_1:raw} if to disable the by default url encoding that is applied.

**Comment by RobinsonWM** [comment]
That worked, thanks!
