### ISSUE TITLE
Problem with deleting users Grafana v5.1.4

### ISSUE THREAD

**Issue by melnikdima90** [grafana/grafana#12562]
Hi
I had Grafana 4.x
I upgraded to Grafana v5.1.4

I deleted current users from Grafana using web.
The user was deleted using “server admin > users” and disappeared from the user list.
I tried to create a user with the same login.
But the system does not allow it to be created.

I can login to the system under the old login and password is obtained, but not a single dashboard.
So the user was not completely removed from the database.

I use influx DB
Can you help me where grafana save users account?

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/12558
