### ISSUE TITLE
[Feature] Alerting - Allow query for comparison value in conditions

### ISSUE THREAD

**Issue by thejchap** [grafana/grafana#12567]
Hi!
We are new to Grafana and finding it very useful already. Thanks for all the great work :)

We have a use case in which we want to trigger an alert when 2 custom Prometheus metrics diverge from each other. This may be out of scope of Grafana's alerting, but if it is something the team is open to would like to begin work on contributing this. Otherwise we can build this logic elsewhere.

Proposal:

Currently, conditions could read something like this:
```
WHEN last () OF query (A, 5m, now) IS BELOW 1
OR
WHEN last () OF query (A, 5m, now) IS ABOVE 1
```

Proposed functionality would allow this:
```
WHEN last () OF query (A, 5m, now) IS BELOW last () OF query (B, 5m, now)
OR
WHEN last () OF query (A, 5m, now) IS ABOVE last () OF query (B, 5m, now)
```

Perhaps with a toggle to select whether the user is inputting just a static value (current) or building a query.

**Comment by torkelo** [comment]
Yes! This would be great!

Closing this as there already is a feature request for this https://github.com/grafana/grafana/issues/6593

**Comment by thejchap** [comment]
thanks @torkelo! didn't see that
