### ISSUE TITLE
Export to CSV should use the name of the panel as default filename (or allow changing the default filename)

### ISSUE THREAD

**Issue by RollingFred** [grafana/grafana#12576]
Grafana 4.6.3
Datasource: ElasticSearch
OS: Debian

When exporting as CSV (From a Graph or Table Panel0, it saves the file as "grafana_data_export.csv"

It would be great to either be able to change the default filename when exporting, or default it to the name of the panel (to avoid ending up with grafana_data_export.csv, grafana_data_export (1).csv, grafana_data_export (2).csv, etc...)

Thanks!

**Comment by yellowpattern** [comment]
The name of the panel should be more than just the local panel. Maybe include the "path" to the panel?

e.g. grafana_<dashboard>_<panel>_export.csv

**Comment by kammasuresh** [comment]
how do i do that change can you please expalin clearly

**Comment by liujuanjuan1984** [comment]
I wanna to fix this ,too

**Comment by daniellee** [comment]
This is implemented. For example, when downloading a CSV file for a panel named `Open issues ad PRs` then the filename is: `Open issues and PRs-data-2020-11-10 11_27_02.csv`
