### ISSUE TITLE
S3 Image Uploader does not work with ECS Task Role

### ISSUE THREAD

**Issue by maxvw** [grafana/grafana#12570]
The s3 image uploader code is not respecting `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` which causes it to fail inside ECS - this has been fixed previously for CloudWatch though, so I will create a PR with similar changes shortly.

### What Grafana version are you using?
5.1.0

### What datasource are you using?
AWS CloudWatch

### What OS are you running grafana on?
Docker on AWS ECS

### What did you do?
Configure a `taskRoleArn` in ECS that allows uploading to S3 (and CloudWatch access)

### What was the expected result?
That alerts upload images to S3

### What happened instead?
AccessDenied

**Comment by marefr** [comment]
Fixed by #13424
