### ISSUE TITLE
Blank value appears when filtering variable with regex

### ISSUE THREAD

**Issue by vgallissot** [grafana/grafana#12578]
### What Grafana version are you using?
Grafana v5.2.1 (2040f61)

### What datasource are you using?
Graphite

### What OS are you running grafana on?
Ubuntu 12.04.5

### What did you do?
I added a regex to filter 2 strings out of a wildcard query. That works, but a blank value appears and breaks graph queries.

### What was the expected result?
Regex works without adding a blank value.

### What happened instead?
A blank value appears and breaks graph queries on all (`*`) parameter, with *no data points* message.

* If I remove the regex, no more blank value,
* If I use `/.*/` as regex, no blank value,
* It happens only when filtering with `/unwanted|(wanted)/ regex.

See screenshots attached: 
 
![screenshot from 2018-07-11 15-22-04](https://user-images.githubusercontent.com/6567744/42576068-e83e78d4-8521-11e8-8b6c-44fe0554af31.png)

![screenshot from 2018-07-11 15-46-27](https://user-images.githubusercontent.com/6567744/42576067-e81d7a44-8521-11e8-973b-a5200fa108f8.png)

**Comment by torkelo** [comment]
You have a capture group , maybe it matches an empty string or whitespace? What does your query return?

**Comment by vgallissot** [comment]
My query without regex returns 4 values:
* frontend
* backend
* value1
* value2

I used the specific regex `/backend|frontend|(.*)/` to filter to only *value1* and *value2*.
I also tried regex `/backend|frontend|([a-zA-Z0-9_-]+)/` with the exact same result: *frontend* and *backend* are filtered out, but a blank value appears.

There's no whitespace in the query.
The blank value appears when a value is filtered by the regex.
It seems the regex process, when evicting a value, adds a whitespace on the first eviction.

See following screenshots when removing the regex:
![screenshot from 2018-07-12 09-46-31](https://user-images.githubusercontent.com/6567744/42619759-389e54f6-85b9-11e8-9532-9b1052ee2921.png)
![screenshot from 2018-07-12 09-47-11](https://user-images.githubusercontent.com/6567744/42619760-38b63d1e-85b9-11e8-8eb1-57a8ef7ede8a.png)

**Comment by torkelo** [comment]
The regex is not used for filtering but selecting part of the value, there is an open feature req for filtering https://github.com/grafana/grafana/issues/4000
