### ISSUE TITLE
Grafana does not show folders after "General", if it has more than 1K dashboards

### ISSUE THREAD

**Issue by denilsonsa** [grafana/grafana#12582]
## How to reproduce:

1. Have a large enough grafana installation with over a thousand dashboards. (Here we have more than 4K.) Have most of those dashboards be inside the *General* folder (because they were created before folders existed).
2. Create some folders such as "ABC" and "XYZ".
3. Go to either of these two places:
    * `/dashboards` URL (available through the sidebar *Dashboards → Manage*).
    * Click on the top bar from grafana home dashboard, which will open the search interface with the list of all dashboards below it.
4. Notice there are a few folders before *General* (such as "ABC"), and *General* is expanded.
5. Click on *General* to collapse it.
6. BUG!

## What happens?

There are no folders after General.

## What should happen?

More folders should be displayed. In special, I expected to find *XYZ* folder in the list.

## Impact

Folders are less useful because people can't find the folders they created (if such folders are sorted after *General*).

## Why does it happen?

Because of this AJAX request: `/api/search?folderIds=0&…`

It returns all folders before General first, followed by all dashboards inside General. The amount of results is limited to 1000. This means folders after "General" are not listed at all.

Managed to reproduce this issue in grafana version 5.1.4.

## Somewhat related issues:

* https://github.com/grafana/grafana/issues/3623
* https://github.com/grafana/grafana/issues/12327#issuecomment-398304385
* https://github.com/grafana/grafana/issues/12467
 
## Possible solutions:

* Return *General* folder collapsed by default, instead of expanded.
* Change the endpoint to return all folders first, and return *General* dashboards only later.
* Renaming *General* to something silly, like *zzGeneral*.
* Try increasing the limit from 1000. This will just delay the issue, and likely make the grafana index (even) slower.

If backwards compatibility is needed, changes to the API endpoint could be done by adding another parameter, or creating a new endpoint.

**Comment by alexanderzobnin** [comment]
Hi, @denilsonsa ! Thanks for this pretty detailed bug report!

**Comment by jessabe** [comment]
@vijayakumarbathini anyone is more than welcome to submit a pull request with us! We're very grateful for bug fixes, especially. 🙇

**Comment by dsotirakis** [comment]
This is in progress 👀 , as it's been reported again https://github.com/grafana/grafana/issues/37348

**Comment by dsotirakis** [comment]
This should be fixed in #38103
