### ISSUE TITLE
Support variables in Alert List filters

### ISSUE THREAD

**Issue by TambetP** [grafana/grafana#12583]
Hello.
I am using Grafana 5.2.1 and the ability to use variables is Alert List filter options would be a very welcomed addition. That would give the possibility to repeat Alert List based on a variable and show alerts only for that variable. Or just show alerts based on a variable. If this is possible already or in a newer version then please let me know, but I could not find any word about it or could not use variables in the version I am using atm.
Other then that great work with Alert List filter options!

**Comment by torkelo** [comment]
to fix this you need inject templateSrv (in the panel controller constructor). 

Then use templateSrv to interpolate the name & dashboard filter strings:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/alertlist/module.ts#L135 

like this
```javascript
params.query = this.templateSrv.replace(this.panel.nameFilter, this.panel.scopedVars);
```
