### ISSUE TITLE
Resurrection of #3607 -- unwanted scrollbars in embedded panels

### ISSUE THREAD

**Issue by marcmengel** [grafana/grafana#12589]
So scrollbars are again appearing again in embedded panels, no matter how they're sized.

How to reproduce:
pick a panel, click on its title, go to the Embed tab, copy the embed text, paste in a webpage, look at the webpage.

There is an old bug for this #3607 which was closed with version 3.0, but has several people recently saying they're  seeing it, but of course that issue is closed, so I don't think anyone is seeing those comments.

**Comment by torkelo** [comment]
thanks for reporting this.

**Comment by torkelo** [comment]
Sorry for this regression, fix incoming and will be included in v5.2.2 patch (released in 2-3 weeks)

**Comment by torkelo** [comment]
But you can fix later today in nightly builds.

**Comment by marcmengel** [comment]
Thank *you* for fixing it :-).
