### ISSUE TITLE
allow simplified drilldown urls

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#1258]
I would like to link to another web page, with a specific url.  (ie, don't pass any params.)  However there doesn't seem to be a way to tell grafana to not pass a param.

Also, related question, instead of http://, I'd like to specify a different resource, like ftp:// or ssh://.  Is that possible?  

Right now I get a link like:

unsafe:foobar://bar/baz/?from=now-1h&to=no

This is Mac OS X, under Safari.

**Comment by torkelo** [comment]
this was fixed in 2.1 I think
