### ISSUE TITLE
Allow datasources to provide partials for report variable query options

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#12588]
My users love the power of report templating with datasource queries, however they complain about the ux of the query box:

![screen shot 2018-07-12 at 9 07 08 am](https://user-images.githubusercontent.com/3194832/42635136-2d4deedc-85b3-11e8-8fee-fb56fcc1c32c.png)

The want the same query editing experience here that they get when building a panel. (I.e the prometheus ace-editor with syntax highlighting and autocomplete).

Since it is up to the datasource plugin to decide how to parse the text from that `query` input box, I think a datasource should (optionally) be allowed to provide a partial to render there. 

Is there any technical reason this wasn't implemented? Would the team be interested in a PR for this?

**Comment by davkal** [comment]
We're currently consolidating the editor code. As a result, the variable query field could get an upgrade too. Let's revisit this in 4 weeks.

**Comment by seanlaff** [comment]
I think this is doable these days (atleast I think the stackdriver source does it). Closing
