### ISSUE TITLE
Prometheus dashboard export to JSON: export-templating seems to not fully declare DS_PROMETHEUS variable

### ISSUE THREAD

**Issue by javabrett** [grafana/grafana#12587]
### What Grafana version are you using?
Grafana v5.2.1 (commit: 2040f61), running the official Docker image.

### What datasource are you using?
Prometheus 2.3.1

### What OS are you running grafana on?
Linux, Docker

### What did you do?
I want to automatically provision `datasources` and `dashboards` within and via `/etc/grafana/provisioning`.  I mount this directory into the running Docker container.

I have created a `/etc/grafana/provisioning/datasources/prometheus.yml` to define the Prometheus datasource, then I start Grafana (the Docker container).  The Prometheus datasource is well-defined.  I can browse it and see it has Dashboards defined, and Import the dashboard (Prometheus 2.0 Stats).  The dashboard works fine.

I want to use this dashboard and export it to JSON, then add that as `/etc/grafana/provisioning/dashboards/prometheus.yml` to auto-create the dashboard for new builds.

### What was the expected result?
I expect the auto-provisioning to create the dashboard in a working-state, with a chooser for the resulting `DS_PROMETHEUS` variable with a working default value of `Prometheus`.

### What happened instead?
The imported dashboard is in-error, because it cannot locate `DS_PROMETHEUS` datasource, as the variable is not properly decared or set.  There's no drop-down option to allow `DS_PROMETHEUS` to be set to `Prometheus` (the name of my datasource).

Due to the (expected) templating of the dashboard export, panel-elements have `"datasource": "${DS_PROMETHEUS}"` instead of a named datasource, as the export deliberately templates this.  The problem is that the variable seems to be not properly declared in the dashboard JSON.  I was able to fix this, by adding:

```json
"templating": {
    "list": [
      {
        "current": {
          "text": "Prometheus",
          "value": "Prometheus"
        },
        "hide": 0,
        "label": null,
        "name": "DS_PROMETHEUS",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      }
    ]
  },
```

With this added, the dashboard json is imported, the `DS_PROMETHEUS` variable appears at the top of the dashboard, and is correctly-defaulted to `Prometheus`.

Is the dashboard JSON export templating process forgetting to add this `templating` block?

**Comment by torkelo** [comment]
Sorry this is more complicated than it needs to be. The export json feature is designed to be used with UI import feature that allows you to select datasources. Provisioning is automatic so there is no where to specify it (currently) so does not work with these types of dashboards. You need to go to dashboard settings and view json and copy and save that to a file.

We will try to improve this mess in future release

**Comment by javabrett** [comment]
Thanks.

The `Settings` -> `JSON Model` then copy/save JSON seems to provide a model which is compatible with provisioning auto-import of the dashboard.  It did produce for me very close to identical JSON from that of the Export which I then hand-patched with the `templating` section above.  The JSON copy/paste is missing `__inputs` and `__requires` and has an `id` and `iteration` already set, otherwise they are the same.
