### ISSUE TITLE
Variables using new ${app:format} syntax does not get updated app var changes

### ISSUE THREAD

**Issue by macgyver603** [grafana/grafana#12593]
### What Grafana version are you using?
5.2.1

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
I have a template variable that references another template variable and uses the `${var_name:regex}` advanced formatting option so the first variable can be used to filter a Prometheus label value search. However when the first template variable is changed, the one using the advanced formatting options does not refresh unless it is manually updated .

I have the following three variables and their respective queries:

```
release --> label_values(release)
pods --> label_values({kubernetes_pod_name=~"[[release]].*"},kubernetes_pod_name)
nodes --> label_values(container_cpu_usage_seconds_total{pod_name=~"${pods:regex}"}, kubernetes_io_hostname)
```

* `release` only allows one selection at a time
* both `pods` and `nodes` allow for multiple selections or all 

All are coming from the same Prometheus datasource, all are set to refresh `On Dashboard Load`, and I have verified that the `container_cpu_usage_seconds_total` metric is available for all pods for all releases in my Prometheus deployment.

- - -
So, when I select a release name for `release`, `pods` will refresh properly and show a list of the pods associated with that release that are running, but `nodes` will not refresh and will only show the list of values the initial template variable query found. Additionally, changing the selection for `pods` does not have any impact on the variable as well.

However, if the value(s) of `pods` is/are changed, I can force the variable to refresh by going to `Settings >> Variables >> $nodes` and clicking `Update`. After this, the correct list of values will show for `nodes` in the dropdown menu, but if `pods` is changed again, `nodes` will not refresh unless I force it to update again.

- - -
Full variable configurations:

```
{
"allValue": null,
"current": {
"selected": true,
"tags": [],
"text": "chartmuseum",
"value": "chartmuseum"
},
"datasource": "k8s",
"hide": 0,
"includeAll": false,
"label": null,
"multi": false,
"name": "releases",
"options": [],
"query": "label_values(release)",
"refresh": 1,
"regex": "",
"sort": 0,
"tagValuesQuery": "",
"tags": [],
"tagsQuery": "",
"type": "query",
"useTags": false
},
{
"allValue": null,
"current": {
"text": "All",
"value": "$__all"
},
"datasource": "k8s",
"hide": 0,
"includeAll": true,
"label": null,
"multi": true,
"name": "pods",
"options": [],
"query": "label_values({kubernetes_pod_name=~\"[[releases]].*\"},kubernetes_pod_name)",
"refresh": 1,
"regex": "",
"sort": 0,
"tagValuesQuery": "",
"tags": [],
"tagsQuery": "",
"type": "query",
"useTags": false
},
{
"allValue": null,
"current": {
"selected": true,
"text": "All",
"value": "$__all"
},
"datasource": "k8s",
"hide": 0,
"includeAll": true,
"label": null,
"multi": true,
"name": "nodes",
"options": [],
"query": "label_values(container_cpu_usage_seconds_total{pod_name=~\"${pods:regex}\"}, kubernetes_io_hostname)",
"refresh": 1,
"regex": "",
"sort": 0,
"tagValuesQuery": "",
"tags": [],
"tagsQuery": "",
"type": "query",
"useTags": false
}
```

**Comment by macgyver603** [comment]
I thought it was too, but with the Prometheus-backed template variables, the output format for both `$var` and `[[var]]` notations is something like the following if there are multiple values selected for the variable:  
```
{item1,item2,item3,...}
```
This seems to be the case with a Graphite-backed template variable as well.

I didn't notice this problem at first because when the variable is initially created or if the dashboard is initially loaded, the variable substitution for `$var` or `[[var]]` notation has no formatting when one value is selected (no curly brackets around the single value), but when multiple values are selected or a different value is selected, the formatting is then applied to the variable substitution. This does not seem to be the case with the `${var:regex}` notation.

This can be demonstrated with a simple text panel like so:  
```
{
  "content": "# $var\n$node  \n# [[var]]\n[[node]]  \n# regex\n${node:regex}  ",
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 7,
  "mode": "markdown",
  "title": "Panel Title",
  "type": "text"
}
```
Where the variable `node` is a template variable with the option to select multiple values.

I'm not 100% sure if this directly related to the bug I reported, but hopefully it can provide some clue as to what is going on with the template variable formatting.

**Comment by torkelo** [comment]
think this is fixed in v6.x
