### ISSUE TITLE
Alerts are coming from grafana, even the given threshold not breached.

### ISSUE THREAD

**Issue by shivach52668** [grafana/grafana#12591]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.1.4
### What datasource are you using?
CloudWatch
### What OS are you running grafana on?
Ubuntu 16.04 LTS
### What did you do?
Cloud Architect
### What was the expected result?
The Alert has to be triggered when the threshold brached.
### What happened instead?
I have mentioned threshold (Cpu utilization:70%) but the current utilization is 36% here threshold is not breached but i am getting alerts from grafana dashboards.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
<img width="1371" alt="screen shot 2018-07-13 at 12 55 42 am" src="https://user-images.githubusercontent.com/33837510/42654838-a2f880b4-8637-11e8-90ca-f5bcdabe69e8.png">
<img width="801" alt="screen shot 2018-07-13 at 12 56 02 am" src="https://user-images.githubusercontent.com/33837510/42654852-b1564a56-8637-11e8-965e-d02e9a083b71.png">

**Comment by torkelo** [comment]
What is your query? The alert time range is 5m so it could be that your query returns different values on short time ranges. Please include the results from "test rule" button. It looks like your TSDB query sometimes fluctuates (returns higher numbers). You can look at alert history (in alert tab) as well to see more history, maybe your TSDB query returns error sometimes?

**Comment by shivach52668** [comment]
Thanks for the response. For the above problem, i have mentioned, i didn't captured test rule result, Today early morning also i faced similar issue, where i have mentioned the alert as when the DiskSpace threshold breached 80% then grafana has to alert me, this what i have defined, but the alarm triggered, when the Diskspace is 36%, even i checked the alert history we are not getting any point, why it is alerting with false alarms so could you help out.
<img width="1363" alt="screen shot 2018-07-14 at 11 33 47 am" src="https://user-images.githubusercontent.com/33837510/42721591-0cd86390-875b-11e8-91ac-8f685eb17c0e.png">

<img width="1020" alt="screen shot 2018-07-14 at 11 34 08 am" src="https://user-images.githubusercontent.com/33837510/42721594-1354966c-875b-11e8-86bb-10e3d4a7b0cb.png">

<img width="961" alt="screen shot 2018-07-14 at 11 34 45 am" src="https://user-images.githubusercontent.com/33837510/42721595-137cc204-875b-11e8-8a7b-9d3d11a7375a.png">

<img width="824" alt="screen shot 2018-07-14 at 11 41 55 am" src="https://user-images.githubusercontent.com/33837510/42721596-13ca2468-875b-11e8-9ec8-d1282acbebfc.png">

And why i am not getting metric value (threshold value)  in mail notification Image. (Graph).
<img width="798" alt="screen shot 2018-07-14 at 11 43 36 am" src="https://user-images.githubusercontent.com/33837510/42721609-4d211b86-875b-11e8-92e2-edc47f9b6bcf.png">

<img width="801" alt="screen shot 2018-07-14 at 11 43 29 am" src="https://user-images.githubusercontent.com/33837510/42721611-502cbd9e-875b-11e8-93c9-92fa499febe0.png">

**Comment by briangann** [comment]
from the above graph the alert at 07:01:15 was due to "no data", where the alert is set to "If no data or or all values are null: Alerting".  There's a gap in the data which would trigger the alert. If you zoom into the other time ranges you may see more gaps/no_data results.

**Comment by shivach52668** [comment]
hi @briangann,
Thanks for the reply, I agree with your answer, here what exactly i am facing is, i am using AWS CloudWatch as Datasource to pull the metrics from AWS Instances to display in grafana, so by **"Default cloudwatch enabled with 5m, so every 5m when the state changes i am getting alert".**
**CloudWatch Sanpshot:**

<img width="915" alt="cloudwatch-metrics-5m" src="https://user-images.githubusercontent.com/33837510/42959710-55191942-8ba7-11e8-9f90-a5e0e70daf2b.png">

**AlertNotification:**

<img width="504" alt="screen shot 2018-07-19 at 11 04 52 pm" src="https://user-images.githubusercontent.com/33837510/42960471-88540716-8ba9-11e8-8ebc-3240db3de667.png">

But the problem is **"Even when the alert is cleared (state changed from Alerting to Ok state, still i am getting alerts from dashboard, like from the below snapshot, i am getting same "OK" alert from same instance even though the alert state not changed.... **

<img width="504" alt="mail_alerts-5m" src="https://user-images.githubusercontent.com/33837510/42960603-eaf7a792-8ba9-11e8-8486-99a561ffae50.png">

So why it is happening, could you please help me out....

<img width="1416" alt="screen shot 2018-07-19 at 11 24 05 pm" src="https://user-images.githubusercontent.com/33837510/42960936-eba90086-8baa-11e8-8bd9-7d7ce093d44e.png">

**Comment by briangann** [comment]
You might try setting the "If no data or all values are null" set state to "Keep Last State"

There may be a bug lurking here where the alert state transitions from OK -> No Data -> OK  which then generates an alert.

By setting the no-data/null to Keep Last State, the transition won't happen (it will retain the OK state, or whatever was previous).

**Comment by shivach52668** [comment]
Thanks @briangann , I have changed the settings now, let me keep observe that.

But if i keep the **"if no data or all values are null" set to "Keep Last State"** then what happens when there is data not displaying or pulling from CloudWatch to Grafana, can we get the alerts for **"No-Data"** state.

One more issue is "For alert mail notification **"In Notification Channel i have added three mails, so when i add more than three mail recipients, alerts are not triggering **. 
so when i checked the logs, i am getting ....

**Logs:-**

**"t=2018-07-20T06:10:33+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=1 isDefault=false
t=2018-07-20T06:10:33+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[shiva.1234@sample.com  chai1234@sample..com]"
t=2018-07-20T06:10:44+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp 34.250.6.243:25: i/o timeout""**

Snapshot for alert history:

<img width="723" alt="screen shot 2018-07-20 at 3 20 35 pm" src="https://user-images.githubusercontent.com/33837510/42996244-987b0d56-8c30-11e8-961c-46d9731faf01.png">

could you please help me out.

**Comment by torkelo** [comment]
looks like a timeout from your smtp server, do you get this error often?
