### ISSUE TITLE
Asynchronously add/remove rows from a scripted dashboard

### ISSUE THREAD

**Issue by vincentbernat** [grafana/grafana#1259]
Hi!

Currently, we can return asynchronously a complete dashboard. Suppose that I want to modify this dashboard with events from some event source. Currently, I have to trigger a reload. It would be nice to expose the necessary API to add/remove a row after the dashboard has been first rendered.

**Comment by torkelo** [comment]
closing this for lack of interest, scripted dashboards will get a complete makeover at some point :)
