### ISSUE TITLE
Define multiply index names for one elasticsearch source (Feature Request)

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#12599]
Hi everybody,

I use Search Guard to limit access to specific indices. A user I created can for example see filebeat-* and metrics-*.
Currently I try to create a new source for Elasticsearch in Grafana, but when I use *-YYYY.MM.DD I get an error message, because there are insufficient permissions for this user for all indices.
It’s working when I use the specific index names (like [filebeat]-YYYY.MM.DD).
I tried something like {filebeat-*, metrics-*} or other combinations, but it’s not working and I don’t want to create a data source for every index name (for example to count all docs of all the authorized indexes).
So it would be great, if I could define more than one index name in one elasticsearch data source.

Best regards,
Patrick

**Comment by davewat** [comment]
@Foxeronie Not exactly sure the desired result, but have you looked at using Elasticsearch aliases?  That might be more efficient - define an alias, and then assign the appropriate indexes to the alias.  In Grafana, you just use the alias in the Data Source config.

**Comment by Foxeronie** [comment]
@davewat Thanks for this tip. According to the elastic documentation the aliases don't have an auto update. So indices of the next day will be ignored. Setting the aliases every day would be an option, but I think it's not the best.
With the requested feature you can easily limit or expand your indices in your data source.

**Comment by davewat** [comment]
@Foxeronie understood - we solve that by running a cronjob that updates the aliases across a hundred + indexes every couple of mins (usually there is no change, but at least once a day, index names update).  There is no performance impact with aliases, and it gives us a nice management layer, especially when we change the index template, and migrate to new indexes.

**Comment by marefr** [comment]
As @davewat says you can use alias in elasticsearch for certain indices and that is our recommended way to solve your problem. I'm closing this since we're trying to only have issues open that are relevant for the project. I will consider reopen if I misunderstood something or a lot of people show interest in this issue by upvoting it.
