### ISSUE TITLE
auth proxy with anonymous access behavior change

### ISSUE THREAD

**Issue by propertone** [grafana/grafana#12604]
### What Grafana version are you using?
5.2.1
### What OS are you running grafana on?
Linux
### What did you do?
I'm running Grafana behing Apache with auth.proxy and auth.anonymous enabled. Since Grafana 5.1, if the proxy successfully authenticates the user, but the user does not have a Grafana account, they now get an error "Failed to login as user specified in auth proxy header". In Grafana 5.0 and earlier, the user would just be treated as an anonymous user.

This was an unexpected behavior change and I didn't see anything in the Changelog about it. I was relying on the earlier behavior so that only a small number of people who edit dashboards would need Grafana accounts, while everyone else (who is authenticated automatically by Apache via Kerberos) would just have anonymous Viewer access. I think this change happened in commit d5dd1c9bca020ba1913e313ac24a55cb034fb216 by @DanCech 

Was this an intentional change? If not, could the old behavior be restored, or a new option introduced on how to treat users authenticated by the proxy who don't already have a Grafana account.
### Grafana Config
Here's the relevant portion of my Grafana config
```
[auth]
disable_login_form = true
disable_signout_menu = true
[auth.anonymous]
enabled = true
org_role = Viewer
[auth.proxy]
enabled = true
header_name = X-PROXY-USER
header_property = username
auto_sign_up = false
```

**Comment by torkelo** [comment]
This combo is not supported, not sure why it worked before. auto_sign_up = false means the user needs to exist in Grafana, if the user supplied auth proxy header is not found an you do not allow grafana to create this on the fly then an error will be shown. Change auto_sign_up = true to fix this.
