### ISSUE TITLE
Upgrading Grafana

### ISSUE THREAD

**Issue by unridaz** [grafana/grafana#12608]
Hello,

Using Centos as my server OS, I originally installed grafana in version 4. Some weeks ago I upgraded to 5.1.3, and ran into an issue where starting the grafana service would crash. After some troubleshooting and reading I figured that this was because I had queries in which I had removed the time($_interval) "function"?  Another other post I was reading was suggesting that in doing so the query was gathering too many points and causing the crash. Since we only had a handful of queries and dashboards defined at this point we decided to simply scrap our work, install a fresh grafana 5.1.3, and recreate everything. 

My question is, now if I go to upgrade to 5.2 or any other newer version of grafana, am I going to run into the same issue? We have again removed the time($_interval) from many queries as it seems to not be able to display the view we are looking for when this is set.

Thanks!

**Comment by torkelo** [comment]
That is strange, we have no other reports like this. Usually you upgrading from any previous version is troublefree. We work hard on marking Grafana always be backward compatible and safe to upgrade.
