### ISSUE TITLE
Support full page screenshots via chrome dev tools

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#12607]
### What Grafana version are you using?

5.2.1

### What datasource are you using?

Irrelevant

### What OS are you running grafana on?

Irrelevant

### What did you do?

Tried to get a full page screenshot.

### What was the expected result?

Get a full page screenshot like in 4.6.3 before.

### What happened instead?

Only visible area is captured. This is reproducible in both Firefox and Chrome.

For Firefox you can do:

1. Go to https://play.grafana.org/
2. Open developer tools
3. Take the screenshot:

    ![image](https://user-images.githubusercontent.com/89186/42719371-4a3ba1a8-86c9-11e8-9c4d-26a58553688f.png)

4. Observe:

    ![screen shot 2018-07-13 at 18 19 42-fullpage](https://user-images.githubusercontent.com/89186/42719375-5323dce0-86c9-11e8-8d48-43461b6b2801.png)

I paste full page screenshot with tens of panels fairly regularly and this breaks my workflow.

**Comment by torkelo** [comment]
Yes, sadly this won't work with how the fixed dashboard nav & dashboard scroll. Will leave this as a feature request to see how common this use case is.

**Comment by bobrik** [comment]
I'll be more than fine with a button in Grafana itself to make a screenshot and copy it into clipboard.

**Comment by Envek** [comment]
Same here. Quite annoying that it is impossible to create a screenshot of the whole dashboard. 

I'm using Firefox built-in screenshot feature and it works quite well on other sites even on those with fixed menus and etc.

**Comment by Envek** [comment]
Same here. Quite annoying that it is impossible to create a screenshot of the whole dashboard. 

Moreover even when I'm try to screenshot DOM node with Firefox developer tools it creates an image with proper dimensions but only partially filled with visible part of the page.

I'm using Firefox built-in screenshot feature and it works quite well on other sites even on those with fixed menus and etc. Developer tools approach is working fine on other sites as well.

**Comment by relishcolouredhat** [comment]
As bobrik said above - a native way to screenshot a 'whole dashboard' would satisfy the use case on my end. There are browser extensions that can do this currently, but we would love the ability to be able to send a static image of the content of a whole dashboard as either a button or api call (maybe this exists already, but I have not figured out how to use?)

**Comment by torkelo** [comment]
I created this issue to explore ways to fix this 
https://github.com/grafana/grafana/issues/13437

**Comment by LunaticoCR** [comment]
+1, either support browser to take full page screenshot (Firefox for example has it's own built-in way), or Grafana itself provides a way to export current visible dashboard to an image file or to clipboard.

**Comment by alexsuraykin** [comment]
Somebody knows, this issue still exist in Grafana 6.x?

**Comment by sebnow** [comment]
Yes, it still exists.

**Comment by alexsuraykin** [comment]
Ok. Has anyone found a solution how to make a full screenshot through selenium?

**Comment by uselessjargon** [comment]
+1, this would be a great feature to have.

**Comment by llirikk** [comment]
+1

**Comment by LunaticoCR** [comment]
There's a workaround in the last comment of issue [11185](https://github.com/grafana/grafana/issues/11185).

**Comment by alexsuraykin** [comment]
> There's a workaround in the last comment of issue [11185](https://github.com/grafana/grafana/issues/11185).

What about automation tools, selenium and etc?

**Comment by reppners** [comment]
For anyone using browser automation tools this is my pyppeteer (python puppeteer) snippet to workaround this:

```python
    async def shoot(url: str, path: str):
        browser = await launch()
        page = await browser.newPage()
        await page.setViewport({'width': 1900, 'height': 1080})
        await page.goto(url, {'waitUntil': 'networkidle2'})
        elementHandle = await page.J('grafana-app.grafana-app div.main-view div.scroll-canvas div react-container div div.scroll-canvas.scroll-canvas--dashboard div.custom-scrollbar.custom-scrollbar--page div.view div.dashboard-container.dashboard-container--has-submenu div.react-grid-layout.layout')
        boundingBox = await elementHandle.boundingBox()
        height = boundingBox['height']
        await page.setViewport({'width': 1900, 'height': height + 55}) # 55 is the navbar
        await page.goto(url, {'waitUntil': 'networkidle2'})
        await page.screenshot({'path': path, 'fullPage': True})
        await browser.close()
```

I hope this is transferable to all other automation tools out there. 

These are the steps:
* load the dashboard
* select the dashboard DOM element that has the actual height set
  * the css selector in the example is for Grafana v6.2.1 (commit: 9e40b07), you might need to adapt this based on your version!
* read the actual height
* resize the browser page
  * constant 55px on top for navbar, this might also change based on Grafana version but could also be read dynamically like with the selected dashboard element
* reload the page
   * easy way to make sure all content is loaded properly, since there seems to be some lazy loading involved in Grafana based on scroll position
* screenshot it!

**Comment by adamelliotfields** [comment]
Was playing around with Grafana `v6.5.1` tonight.

Here's a 1 liner using [`sindresorhus/capture-website-cli`](https://github.com/sindresorhus/capture-website-cli).

The trick is to get the height first, which is a style attribute on the `react-grid-layout` div. **You only have to do this once** unless you add/remove rows/panels which would obviously change the height of your dashboard.

Run this in Chrome or Firefox Developer Tools Console:

```javascript
document.querySelector('.react-grid-layout').style.height;
// "1710px"
```

Now run this in bash, or make it a cron job, or build a Docker image so you can run it on servers without Node installed.

```bash
# Install the package once globally
npm install --global capture-website-cli

capture-website 'http://localhost:3000/d/mxDGB6xZz/kubernetes?orgId=1&kiosk' \
--full-page \
--overwrite \
--output=screenshot.png \
--element='.react-grid-layout' \
--height=1710
```

Once the command exits, the file will be there, so you could use the AWS/Dropbox/Box CLI to upload it to a bucket or use the Slack CLI to send it to a channel.

**Comment by hnlq715** [comment]
I use chromedp to screenshot grafana dashboard, and use the trick mentioned by @adamelliotfields ,which solved my problem...
thanks again :-)

**Comment by alanjdurkin** [comment]
Here's another workaround (works in chrome at least). Open devtools, find the main-view div (div.main-view), change it's height to 4000px (or whatever works) and then take the devtools screenshot as normal.

**Comment by MrSaints** [comment]
I'm on Grafana v6.7.3 (a04ef6cefc), and @alanjdurkin's solution works reliably.

**Comment by apexskier** [comment]
My workaround in chrome (not using any external tools) -

1. Cycle view mode to "Kiosk" mode
2. Run this in the dev console:
   ```js
   document.querySelector('.grafana-app').style.height = `${document.querySelector('.dashboard-container .layout').clientHeight + 16*2}px`
   ```
3. Run "Capture full size screenshot" action in dev tools

**Comment by danielmotaleite** [comment]
I also needed to take screenshots of the dashboards for a RCA and found that i can't do this anymore in firefox nor chrome with grafana 7.0. 
Using @apexskier  solution almost worked in firefox, i get a screenshot for all the page size, but the graphics not in visible are are just missing. Probably firefox works differently with non-visible areas from chrome (but i didn't tested this one on chrome), so i suspect that all the hacks to increase the view size will not work in firefox

using the add-on referred in https://github.com/grafana/grafana/issues/11185, the https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en works fine, while it looks like a hack by scrolling the page and merge screenshots.

Anyway, either grafana must allow full page screenshots by browser tools, or add a built-in screenshot (or pdf) solution. Current Snapshot feature just generate a link that we can not use in a RCA

**Comment by TheJJ** [comment]
I've "solved" this for me with a bookmarklet, i.e. a **button in the bookmarks toolbar**, which executes @apexskier's code, just wrapped a tiny bit:
``` js
javascript:void(document.querySelector('.grafana-app').style.height = `${document.querySelector('.dashboard-container .layout').clientHeight + 16*2}px`)
```

**Comment by arpitjindal97** [comment]
I found this plugin to be quite useful [GoFullPage](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl/related).

**Comment by bnhf** [comment]
> I found this plugin to be quite useful [GoFullPage](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl/related).

Excellent -- this Chrome plugin actually works to capture Grafana Dashboards in their entirety!

![screencapture-raspberrypi10-3000-d-RwSBnsS7z-apc-ups-detailed-summary-2023-01-28-10_38_58](https://user-images.githubusercontent.com/41088895/215282567-0929f2c0-dcbc-4933-a2ca-1c12d77c5fed.png)

**Comment by nlowe-sx** [comment]
Updated bookmarklet known to work with Grafana 10.2

```javascript
javascript:void(document.querySelector('.grafana-app').style.height = `${document.querySelector('.grafana-app main .scrollbar-view').scrollHeight + 16*2}px`)
```
