### ISSUE TITLE
Import prevents dashboard with same title, but does not prevent dashboard with same uid.

### ISSUE THREAD

**Issue by jflaboe** [grafana/grafana#12602]
Using Grafana v5.1.3.

I was building JSON files for importing with an external Python script, using a current dashboard as a template. I never changed the uid, but I did change the title. Had the title not changed, I would have been warned of overwriting the other dashboard. However, with a different title and the same uid, the dashboard will be overwritten without warning. 

I think either a warning should be given or logic should be added so that Grafana will auto change the uid of an imported JSON file if it will overwrite another dashboard.

**Comment by torkelo** [comment]
Can you try 5.2 , think this has been fixed

**Comment by jflaboe** [comment]
Will have to set up a whole new server to test (I don't have the authority to update the grafana version for the server I'm working on), so I'll take your word for it.

**Comment by torkelo** [comment]
here is the issue https://github.com/grafana/grafana/issues/11515
