### ISSUE TITLE
Issue with the legend of series orders of magnitude apart

### ISSUE THREAD

**Issue by redlus** [grafana/grafana#12610]
Hi,

I'm experiencing an odd behavior when plotting two queries in a graph. While the queries are correctly plotted, the legend does not show decimals when the one series is in the billions and the other is orders of magnitude smaller.

### What Grafana version are you using?
Grafana v5.1.3

### What datasource are you using?
Prometheus v2.2.1

### What OS are you running grafana on?
Linux (Ubuntu 16.04.4 LTS)
The data is shown using Chrome v66.0.3359.181

### What did you do? 
Created a dashboard graph panel with two queries. One returns results in the billions (raw data) and is graphed on the left y-axis, the other returns results which are around 1 (ratio) and is graphed on the right y-axis.

### What was the expected result?
When hovering points on the graph, I'd expect the legend of the second query to show decimals reflecting the small changes. This can be seen here, when hiding the first series (value is 0.90641):
![image](https://user-images.githubusercontent.com/7827282/42735106-6bdd0dee-8857-11e8-88c0-f01321770b55.png)

### What happened instead?
When un-hiding the first series, the legend of the second series is now rounded and does not show decimals, as shown in the screenshot below (value is rounded to 1):
![image](https://user-images.githubusercontent.com/7827282/42735090-38a1a782-8857-11e8-93d3-304174244d38.png)

Adding decimals explicitly through the axes settings does not help:
![image](https://user-images.githubusercontent.com/7827282/42735184-531733d8-8858-11e8-8612-cee39458d9b2.png)

As the data is the same in all cases, this is probably a rendering issue with Grafana/Chrome.

Thanks for your help.

**Comment by torkelo** [comment]
the legend decimals have separate option (As legend can usually need more decimals than y-axis ticks). Sometimes the auto decimals logic in Grafana does not always result in the best possible decimals. 

![image](https://user-images.githubusercontent.com/10999/42757857-cc50d462-8901-11e8-904b-13b854873fd4.png)
