### ISSUE TITLE
/api/alerts does not return eval_data fields

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#12623]
I'm not sure if this is purposeful, but it is an issue we just ran into when trying to correlate a firing alert with what triggered it. The `eval_data` field is missing from the `/api/alerts` queries.

https://github.com/grafana/grafana/blob/a1f0dffe011ca667e45b3b7b67d8da70179f8f2c/pkg/services/sqlstore/alert.go#L76

**Comment by daniellee** [comment]
Good catch - it got lost in this refactor: https://github.com/grafana/grafana/commit/5323971c21b13be7d8212fe44baed1761cd6061e
