### ISSUE TITLE
Allowing unencrypted mails when using remote mail server

### ISSUE THREAD

**Issue by redbaron4** [grafana/grafana#12633]
I am using Grafana-5.2.1 (although the same problem persists with previous Grafana versions as well). We have our own organizational email server that uses plain (unencrypted) connections. Trying to re-use that server for sending email alerts via grafana shows following error in log

> t=2018-07-17T17:14:22 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[REDACTED]
> t=2018-07-17T17:14:22 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="unencrypted connection"
> t=2018-07-17T17:14:22 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="unencrypted connection"
> t=2018-07-17T17:14:22 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=REDACTED time_ms=10 size=48 referer=http://grafana/alerting/notification/1/edit

Would it be possible to have Grafana expose a config option which allows users to specify unencrypted remote mail-server?

My configuration is (does not require any password)

```
[smtp]
enabled = true
host = REMOTE:25
user = XXXX
from_address = ....
from_name = Grafana
skip_verify=true
```

Looking at the issue, it looks like underlying Go library does not allow plain auths but it should be possible to over-ride that as in [this stackoverflow question](https://stackoverflow.com/q/11065913/533524)

**Comment by srik65** [comment]
any workaround for this, same issue "unencrypted connection "

**Comment by liuzheng** [comment]
A dirtay workaround

change the `host = REMOTE:25` to `host = localhost:25`

and change the `/etc/hosts`, change the `127.0.0.1 localhost` to your REMOTE IP, e.g. `10.0.0.1 localhost`

**Comment by saadathydri** [comment]
@liuzheng this workaround is working for me but you are right this is "dirtayyyy" and shouldn't be done. Grafana should resolve this issue.

**Comment by liuzheng** [comment]
@saadathydri this is not Grafana problem, the root reason is this code, from https://github.com/golang/go/blob/master/src/net/smtp/auth.go#L58-L76

```go
func isLocalhost(name string) bool {
	return name == "localhost" || name == "127.0.0.1" || name == "::1"
}

func (a *plainAuth) Start(server *ServerInfo) (string, []byte, error) {
	// Must have TLS, or else localhost server.
	// Note: If TLS is not true, then we can't trust ANYTHING in ServerInfo.
	// In particular, it doesn't matter if the server advertises PLAIN auth.
	// That might just be the attacker saying
	// "it's ok, you can trust me with your password."
	if !server.TLS && !isLocalhost(server.Name) {
		return "", nil, errors.New("unencrypted connection")
	}
	if server.Name != a.host {
		return "", nil, errors.New("wrong host name")
	}
	resp := []byte(a.identity + "\x00" + a.username + "\x00" + a.password)
	return "PLAIN", resp, nil
}
```

this is the golang language std lib issue, so maybe they can try some third party smtp lib

**Comment by sapientiam-1** [comment]
Hi all, I changed the starttls option from:
startTLS policy = NoStartTLS
to
startTLS_policy = false
and now it's working

**Comment by gelicia** [comment]
This seems to work with a setting change. Closing.
