### ISSUE TITLE
ES wrong panel on count and avg

### ISSUE THREAD

**Issue by hjybdrs** [grafana/grafana#12639]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.2.1 (commit: 2040f61)
### What datasource are you using?
ElasticSearch  6.1.1
### What OS are you running grafana on?
CentOS
### What did you do?
i just add a panel and run count and avg agg on some field for a query
### What was the expected result?
graph data correct with es data
### What happened instead?
graph show wrong count and misunderstanding avg
### If related to metric query / data viz:
kibana data after query:
![image](https://user-images.githubusercontent.com/6185339/42864819-4a966488-8a9a-11e8-882e-298f762ea3b9.png)

grafana table:
![image](https://user-images.githubusercontent.com/6185339/42864794-31eaa0a2-8a9a-11e8-82db-2963a04ed500.png)

**Comment by torkelo** [comment]
Maybe something in your query that is not what you expect? Grafana shows the data ES returns. Is there a group by time (histogram) interval that is different than your kibana query? 

You can review the query & ES response using the query inspector (in metrics tab):
https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630
