### ISSUE TITLE
grafana-cli admin reset-admin password does not work if grafana is installed using deb package

### ISSUE THREAD

**Issue by jrwren** [grafana/grafana#12638]
### What Grafana version are you using?
5.2.1

### What datasource are you using?
NA

### What OS are you running grafana on?
Ubuntu 18.04

### What did you do?
Tried to reset my password.

### What was the expected result?
A reset password.

### What happened instead?
```
Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
```

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 

The problem occurs because the deb correctly uses DFHS paths, but these paths don't match what is expected for --homepath.

Using `--homepath /usr/share/grafana` causes the creation of a new database in /usr/share/grafana/data and new logs in /usr/share/grafana/data/logs, instead of using the db which already exists in /var/lib/grafana and the logs which already exist in /var/log/grafana.

An easy work around is to symlink /var/lib/grafana to /usr/share/grafana/data and /var/log/grafana to /usr/share/grafana/data/logs.

**Comment by cristiangauma** [comment]
It also happens on CentOS.

**Comment by xlson** [comment]
Interesting problem. We could potentially do what you suggest to make it work a bit better but we'd still run into the problem of the user having to set `--homepath` explicitly (which might be fine). We'd also run into problems if the user were to change what folders to use (reconfigured data folder in `/etc/defaults/grafana-server` for example).

**Comment by jgschmitz** [comment]
This still doesn't work BTW - <br>
<br>
[root@sogazrealtime yum.repos.d]# grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" "password"
INFO[08-27|16:01:29] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[08-27|16:01:29] Starting DB migration                    logger=migrator

Admin password changed successfully ✔

But it does change the password on the console - the docs are still wrong

**Comment by iowelinux** [comment]
Same here. Ubuntu Xenial.

**Comment by qovert** [comment]
I'm having the same issue running Grafana v5.2.4 (commit: 0bbac5c) : 
:~# grafana-cli admin reset-admin-password --homepath "/usr/share/grafana/" admin
INFO[09-07|23:16:00] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[09-07|23:16:00] Starting DB migration                    logger=migrator

Admin password changed successfully ✔

Confirmed that jrwren's workaround does the trick.

**Comment by sylekta** [comment]
Same as qovert, 5.2.4 and bionic. Also confirmed jrwren's workaround is good.

**Comment by IT-AAA** [comment]
same here (debian 9)

**Comment by jwillmer** [comment]
Same problem. Used the following to fix the password:

```
docker exec -u 0 -it [DOCKERID] bash

ln -s /var/lib/grafana  /usr/share/grafana/data
ln -s /var/log/grafana /usr/share/grafana/data/logs

grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" admin
```

**Comment by shangeo** [comment]
@jrwren thank you. Your workaround saved my day!

**Comment by Izmenoff** [comment]
Grafana v6.1.0
CentOS 7
It doesn't work
sudo ln -s /var/lib/grafana  /usr/share/grafana/data
sudo ln -s /var/log/grafana /usr/share/grafana/data/logs
sudo grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" admin
INFO[04-04|13:11:25] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[04-04|13:11:25] Starting DB migration                    logger=migrator
Admin password changed successfully ✔

**Comment by Izmenoff** [comment]
Steps to recovery admin password for grafana
Install sqlite3

sudo apt-get install sqlite3

Login to the database
sudo sqlite3 /var/lib/grafana/grafana.db

Reset the admin password to “admin”
sqlite> update user set password = '59acf18b94d7eb0694c61e60ce44c110c7a683ac6a8f09580d626f90f4a242000746579358d77dd9e570e83fa24faa88a8a6', salt = 'F3FAxVm33R' where login = 'admin';
sqlite> .exit
Now you can login using this credentials: username: admin and password: admin

https://jenciso.github.io/recovery-admin-password-for-grafana

**Comment by tau-ri** [comment]
THANKS @Izmenoff | ### ** Works fine !**

**Comment by vardhmanandroid2015** [comment]
Thankyou @Izmenoff  as your suggested approach worked as expected...

**Comment by encryptblockr** [comment]
you can reset the admin password
this linux tutorial https://codesposts.com/Wg04jK59 worked for me

**Comment by Izmenoff** [comment]
Is it possible to change password from command line different from admin?

**Comment by gotjosh** [comment]
@Izmenoff sadly no, this is only for the admin password.

**Comment by xlson** [comment]
Once you have changed the admin password you should be able to use the api to change the password of any other. But no, there's no cli for that.

**Comment by diogoim** [comment]
Hi everyone,

In my case we have accidently deleted the superadmin, i am afraid reseting the pass won't help, how can i recreate this user? It is super important, how can we do this without having through a re-installation process?

Thank you all in advance,
Br
Diogo

**Comment by marefr** [comment]
@diogoim if you still have access you may be able to create a new user based on this answer: https://community.grafana.com/t/super-admin-account/5523/6?u=mefraimsson

If your completely locked out I would suggest connecting to the database and either change an existing user in the user table to username `admin` and email `admin@localhost` or change `is_admin` column to 1/true for an existing user.

**Comment by Atem18** [comment]
@diogoim I can confirm that using the command line to reset admin user password : grafana-cli admin reset-admin-password will recreate an admin user with username admin and random numbers. Then you have to query the table user in the database to know its username. Then you can login with that username and the password you have set and after you do what you want.

**Comment by mqgmaster** [comment]
@marefr changing the default admin in grafana.ini, its supposed to works? In my tests its not working. 

Bytheway, why not allow choose the target username in the reset command? The command appears reset only the user ID = 1. I don't completely understand why this issue is closed.

**Comment by lunaticmonk** [comment]
> Same problem. Used the following to fix the password:
> 
> ```
> docker exec -u 0 -it [DOCKERID] bash
> 
> ln -s /var/lib/grafana  /usr/share/grafana/data
> ln -s /var/log/grafana /usr/share/grafana/data/logs
> 
> grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" admin
> ```

This worked for me!

**Comment by sanfx** [comment]
`sudo grafana-cli --homepath /usr/share/grafana  admin reset-admin-password password`

worked for me..

**Comment by cjrobbertse** [comment]
running this command

```
sudo grafana-cli --homepath "/usr/share/grafana" admin reset-admin-password password
```

gives this error

```
Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
```

please advice, I am on macos and used brew install grafana

**Comment by mcicak** [comment]
> running this command
> 
> ```
> sudo grafana-cli --homepath "/usr/share/grafana" admin reset-admin-password password
> ```
> 
> gives this error
> 
> ```
> Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
> ```
> 
> please advice, I am on macos and used brew install grafana

Did you try

```
grafana-cli --homepath "/usr/local/share/grafana" admin reset-admin-password admin
```

After that I get Admin password changed successfully ✔  successful message, but admin password still hasn't change for me.
I also tried `brew services restart grafana` but to no success.

**Comment by msudgh** [comment]
I had the same issue, and `reset-admin-password` approach didn't provide any result. I was continually getting `Invalid username and password` message.

**Comment by pieter2501** [comment]
In case you know the current password and simply want to automate changing the password, an HTTP request like this can do the trick:

`curl "http://admin:**CURRENTPASSWORD**@127.0.0.1:3000/api/user/password" -X PUT -H 'Content-Type: applicat
ion/json;charset=UTF-8' --data-binary '{"oldPassword":"**CURRENTPASSWORD**","newPassword":"NewPass","confirmNew":"NewPass"}'

**Comment by gangstead** [comment]
> @diogoim I can confirm that using the command line to reset admin user password : grafana-cli admin reset-admin-password will recreate an admin user with username admin and random numbers. Then you have to query the table user in the database to know its username. Then you can login with that username and the password you have set and after you do what you want.

I'm in a situation without a server admin and I'm not finding this to be the case.  When I run `grafana-cli admin reset-admin-password new_password`I get:
```
Error: ✗ could not read user from database. Error: user not found
```

Is there any other way of creating / recreating a server admin without modifying the the sqlite db?
