### ISSUE TITLE
Support different color palettes and allow applying them via series overrides

### ISSUE THREAD

**Issue by discordianfish** [grafana/grafana#12632]
I'd love grafana to eventually solve an issue that I come across pretty much always when building dashboards:

In a graph, I have multiple timeseries that belong to different 'groups' of things. For example take a request rate graph split out by status code. Currently grafana would just pick random(?) colors from the palette for each status code.

Yet, we know that different ranges mean different things: 200-299 = okish, 400-499 = something missing, 500-599 = something broken. It would be great if I could somehow define these groups and have grafana be smarter about how to color them.

One way to solve this would be to add support for custom color palettes and allow changing this via the series override, which would allow me to say for the regexp `^2..$` use palette "greens".

There are probably other ways and I don't care much about the specific implementation, but I think there should be something in grafana to help with this.

**Comment by discordianfish** [comment]
Another solution would be to introduce a tint color and have an alternative greyscale palette, that would be good enough for my use cases.

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/4555 so closing this

**Comment by CME64** [comment]
The feature is there and just needs voting, here is the request:
https://github.com/grafana/grafana/issues/17092

And here is the PR:
https://github.com/grafana/grafana/pull/17076
