### ISSUE TITLE
SQL connection leak

### ISSUE THREAD

**Issue by mirwaiso** [grafana/grafana#12636]
https://github.com/grafana/grafana/blob/21e5d61de665383a0b9c26e8f74f144c84b8c047/pkg/tsdb/sql_engine.go#L57

There has been quite a few issues (which surprisingly seems to have been solved) about this: #8513, #9827 .... The problem is as soon as you have a dashboard and opening a second one in a browser or even keep refresh rate very low, you will see that new connections to postgres Server are made (I think other SQL Servers have the same problem as they also use this SQL generic engine). 
After some digging I found out this part where the cache is looked up for a version. But this version is never set -or I don't see it at least- that is why a new engine is always created instead of using the one from cache.
So a possible fix would be this:
`engineCache.versions[dsInfo.Id] = dsInfo.Version `in line 70 somewhere. 
At least this works in my case, but I don't know fully if this breaks something else? Or why are you using versions at all?

**Comment by torkelo** [comment]
thanks for reporting this!
