### ISSUE TITLE
When I use MySQL functions the graph lines not showing when zooming in

### ISSUE THREAD

**Issue by aacostab** [grafana/grafana#12645]
Hi there, like the subject said, I have a problem zooming in the graphs, the lines disappear when I use MySQL functions, in the screenshot that I attach I use the DAT_ADD() function, this because of the datetime column ( sample, format YYYY-mm-dd HH:MM:SS ) of the datasource is on MDT, so if I do not apply that function I see the graph data six hours less.

Sorry but I'm new on Grafana, I did many test but the only thing that I found is that the lines don't disappear when I zooming in only if I don't use any MySQL functions ( like DATE_ADD(), DATE_SUB(), CONVERT_TZ(), etc. ) 

-I use **Local Browser Time** in the TimeZone options

![image](https://user-images.githubusercontent.com/19583379/42913521-b8329d96-8ab2-11e8-9e3a-0ad270b0c562.png)

Grafana v5.2.0
MySQL 5.7.14
Linux x86_64

**Comment by torkelo** [comment]
https://community.grafana.com/t/why-is-my-graph-empty-when-i-zoom-in/24 

There is probably gabs (nulls) in your data, make sure null value in display tab is set to connected, or try the timeGroup macros
