### ISSUE TITLE
How to see the CPU usage of Linux processes as percentage in Grafana?

### ISSUE THREAD

**Issue by Pratheeshpt** [grafana/grafana#12648]
### What Grafana version are you using?
Version 5.1.3

### What datasource are you using?
Simple-json-datasource
Collectd-5.8.0 and rrdtool

### What OS are you running grafana on?
Ubuntu 14.04

### What did you do?
In grafana, I am able to plot the graph of ps_cputime.rrd of individual processes. The ps_cputime.rrd data is captured using collectd. Currently, the user and system CPU time are plotted as 2 graphs.

### What was the expected result?
Is it possible to combine these two into a single graph so that the total CPU usage of the process will be displayed as the sum of user+system CPU time?

Collectd Process plugin reports the CPU time in microseconds of user and system for each processes.  The output is in RRD format and I am using SimpleJson datasource to see the graph in Grafana. Is there any mechanism to convert the CPU time in microseconds to percentage, using garfana? [like applying the formula : (value * 100)/1000000 ]

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
