### ISSUE TITLE
Issue in converting Grafana Dashbaord name to Link, with Special character

### ISSUE THREAD

**Issue by var23rav** [grafana/grafana#12649]
### What Grafana version are you using?
Grafana v5.1.3 (087143285)
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Created two dashboard with names **My# Dashboard**, **My – Dashboard** both are in different folder too
its seems like there is an issue in generating URL from Grafana dashboard, check the below example.

And try to link one panel using to a dashboard(**My – Dashboard**) using Drilldown/ detail link, 
Then when i click on the panel, its get redirected to a wrong dashboard(**My# Dashboard**)
### What was the expected result?
I expect it will take me to  **My – Dashboard**, since through drilldown, i have selected **My# Dashboard**
![screenshot_2018-07-19 grafana - my -- dashboard](https://user-images.githubusercontent.com/7958115/42928142-2abbbd6a-8b54-11e8-9fe3-22622ed3ac5c.png)

### What happened instead?
Its take me to the wrong **My# Dashboard**
### Explanation
Check how the special character affect in the link creation

|Dashboard Name|                                   Generated ID in link|
|:--|:--|
|My testing DASHBOARD				 |my-testing-dashboard|
|My$$$$$$testing-------DASHBOARD	                 |my-testing-dashboard|
|My@@@@@testing@DASHBOARD                         |myatatatatattestingatdashboard|

You can see that irrespective of the special character used(exception: @, ‘@’ converted to ‘at’) and its occurrence, they are converted to 'single - ’ in the id.

So two dashboard with name, ‘My# Dashboard’, ‘My – Dashboard’ will have the same id in link ‘my-dashboard’.

Thereby when I try to link a panel to dashboard using Drilldown/ detail link, using the either of the name( ‘My# Dashboard’, ‘My – Dashboard’). I can’t grantee which dashboard will actually get linked.

https://community.grafana.com/t/issue-in-converting-grafana-dashbaord-name-to-link-with-special-character/8944?u=var23rav

**Comment by torkelo** [comment]
duplicate / related to issue, https://github.com/grafana/grafana/issues/12523 and https://github.com/grafana/grafana/issues/10705
