### ISSUE TITLE
Unable to create new org with allow_org_create config parameter

### ISSUE THREAD

**Issue by FreakyGranny** [grafana/grafana#12646]
Hi there, i'm runnig grafana with docker-compose
`
version: "2"

services:
  grafana:
    image: grafana/grafana:5.2.1
    ports:
      - 3000:3000
    user: "104"
    environment:
      - GF_USERS_ALLOW_ORG_CREATE=true
      - GF_USERS_ALLOW_SIGN_UP=true
`

With that config i'm expected that any user able to create new org, but user with "viewer" role can't see any button. The only way to create new org - be a grafana admin

**Comment by torkelo** [comment]
this is an old option that is only applied to Grafana admins currently. Normal users cannot create new orgs. 

You can set auto_assign_org to false to have each new user created get their own org (even when they signup them selves).

http://docs.grafana.org/installation/configuration/#auto-assign-org
