### ISSUE TITLE
Colored buckets in histogram change size when refreshing

### ISSUE THREAD

**Issue by discordianfish** [grafana/grafana#12659]
### What Grafana version are you using?
- 5.2.1

### What datasource are you using?
- prometheus

### What OS are you running grafana on?
- client is chrome 67.0.3396.79 on linux (ubuntu)

### What did you do?
- Create a histogram
- Click refresh on dashboard

### What was the expected result?
- Histogram bucket width should stay the same and the dashboard look like this
![grafana-histogram-display-bug](https://user-images.githubusercontent.com/275966/42948525-f07d9814-8b6f-11e8-9378-64a1f1e9a5b1.png)

### What happened instead?
- Histogram bucket width changes after clicking the refresh button
- Reloading the browser fixes it
![grafana-histogram-display-bug-reload](https://user-images.githubusercontent.com/275966/42948524-f0578638-8b6f-11e8-81b7-0d1f93aeb4b9.png)

**Comment by torkelo** [comment]
this is probably related to https://github.com/grafana/grafana/issues/12379 , can you try latest nightly build and see if it fixes it? (or wait for 5.2.2 patch release next week)
