### ISSUE TITLE
Is there any API service to generate a Query ?

### ISSUE THREAD

**Issue by ProjectPhoto** [grafana/grafana#12655]
When I read documentation, I cannot find any API service that generates query such as Team or User. And then, I tried to explore that which API service is called while generating a query on UI dashboard. Then I realized that there is a service called as http://localhost:3000/api/tsdb/query and it takes 
{
	"from":"1531968835588",
	"queries":[
		{
			"datasourceId":1,
			"format":"table",
			"intervalMs":120000,
			"maxDataPoints":232,
			"rawSql": "EXECUTE GetTemperature 2",
			"refId" : "A"
		}
	],
	"to":"1531990435588"
}
object as  a parameter but I cannot understand "from" and "to" properties. Finally, when I execute it on postman, I cannot see the query which is expected as auto generated.

Best Regards,

**Comment by torkelo** [comment]
Not sure what you’re asking, please post questions on the community site.

For more details on the http api check api docs on docs site.
