### ISSUE TITLE
Graphite function "interpolate" is missing in grafana

### ISSUE THREAD

**Issue by dariodariodario** [grafana/grafana#12658]
Using Grafana v5.0.4, the underlying graphite supports the interpolate function https://graphite.readthedocs.io/en/1.1.3/functions.html?highlight=interpolate#graphite.render.functions.interpolate, yet grafana does not. I can make it work with the usual Edit mode, but it is not ideal. 

This function works like keepLast value, but instead of keeping the last value for the last N null, will interpolate to the next value. 

Although this seem similar to null -> connected in the display tab, it is useful when you do something like sumSeries to series that have holes, then something like perSecond. The display interpolation does not affect these functions so that why we need the interpolate one.

**Comment by torkelo** [comment]
What graphite version have you specified in datasource config view?

**Comment by dariodariodario** [comment]
1.1.3

**Comment by dariodariodario** [comment]
I mean there is a dropdown and only some available

![screen shot 2018-07-19 at 15 18 49](https://user-images.githubusercontent.com/1387689/42948319-2668d7bc-8b67-11e8-8b82-5214231e008d.png)

**Comment by torkelo** [comment]
Can you try setting it to 1.1.x and hit save? do you see interpolate function then?

**Comment by dariodariodario** [comment]
Yes, with 1.1.x interpolate is available.

**Comment by marefr** [comment]
@dariodariodario Have tried with Graphite 1.1.2 and it works as expected. What's the result of the functions call (using chrome dev tools or similar) with 1.1.3? This is my payload which clearly includes interpolate:

![image](https://user-images.githubusercontent.com/1668778/43066833-079b0178-8e66-11e8-819a-c10830374b20.png)

**Comment by marefr** [comment]
Closing this due to lack of response.
