### ISSUE TITLE
single email to all the recipients in notification channel

### ISSUE THREAD

**Issue by aditimittal** [grafana/grafana#12650]
Please include this information:
### What happened instead? email was sent individually  which is a big problem for big organizations as teams won't be in sync about who is working on that alert

 Please let me know if there is some way I can send a single email to all the recipients i.e all recipients are added in the To at the same time.

**Comment by aditimittal** [comment]
@torkelo will this feature be available anytime soon?

**Comment by holiiveira** [comment]
I have some problems related to this. Any chance of this being implemented?

**Comment by holiiveira** [comment]
@torkelo [That ](https://github.com/holiiveira/grafana/commit/a51faf0c219f576e9b0fc2c5ca2c0ada22b6a97f)solved my problem. Can you see if it's enough for a PR?
