### ISSUE TITLE
Output Graphs at Specific Time Of Day & Email Send i/o timeout Error

### ISSUE THREAD

**Issue by Mon-terr** [grafana/grafana#12652]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana 5.2.0

### What datasource are you using?
Elasticsearch

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
Time Graph & Send Email Alerting

### What was the expected result?
Graph is always output well

### What happened instead?
Hello
I registered it as issues because I think there is a bug in Grafana.

The data from 1:00 am to 9:00 am is not displayed on the graph every day. And by 9 o'clock, all the data from 1:00 to 9:00 will be visible. It is no data message.
How can we solve it?

And the e-mail alarm has 9 out of 10 i / o timeout errors.
![send fail](https://user-images.githubusercontent.com/33366914/42930176-43f20eb0-8b77-11e8-9ce5-7432cfa9f9c1.PNG)
I used 'smtp.gmail.com:465 host
What is the problem with this?

Please help me.
Thanks.

**Comment by torkelo** [comment]
here is the feature request for time of day restrictions: https://github.com/grafana/grafana/issues/6592

The email looks like setup / networking issue, Grafana cannot send email via the smtp server, getting timeout

**Comment by Mon-terr** [comment]
Hi, torkelo! I will check it. Thank you.

Will the first problem be solved with that?
Please take a look at the pictures.

Add Captures
![9 -](https://user-images.githubusercontent.com/33366914/42976395-4e0ea900-8bfc-11e8-91c0-fd38511e6057.PNG)
![9 -](https://user-images.githubusercontent.com/33366914/42976396-4e3fb298-8bfc-11e8-92c6-d42c8a4dff12.PNG)
