### ISSUE TITLE
Performance issues due to large query

### ISSUE THREAD

**Issue by alecxvs** [grafana/grafana#12662]
### What Grafana version are you using?

Grafana v4.6.3 (commit: 7a06a47)

### What datasource are you using?

CloudWatch is the most relevant to this issue for me

### What did you do?

Perform a query dimensioned on a large number (100+) of values from a template variable

### What was the expected result?

The query either finishes successfully or times out

### What happened instead?

CPU usage spikes and Grafana becomes momentarily unresponsive

---

This can probably be resolved through https://github.com/grafana/grafana/issues/3168 depending on what the actual cause of the high resource usage is. I assume it's in the backend, so solving this hinges on the proposed timeouts not only being for queries to datasources but also within the backend itself to keep any one query or dashboard from rendering Grafana unavailable.

Also, the CPU usage being caused by a large query is assumed mostly on circumstantial evidence. The problem there is that there is no apparent way to trace resource hogging to a specific dashboard or query. I've correlated CPU usage spikes and apparent unresponsiveness to loading a particular dashboard that has at least a hundred values in a template variable. Reducing the selected values does improve the situation but we lack direct traceability into where the resources are being consumed. If it were not my own dashboard, and it was someone else's in another organization, I don't think I could be able to trace it back to a specific query. As far as I can tell, I have request logs, backend metrics timings for general endpoints, and my host/process utilization metrics. Now, if backend timeouts are implemented, then we could assume based on metrics or log entries that queries stalling out within Grafana are also using too many resources.

Tangentially, it seems that CloudWatch doesn't handle these types of queries very well. I don't know how this is handled in the backend; maybe limiting how many unique metrics are being retrieved at once would help.

**Comment by marefr** [comment]
@mtanda do you have any insights/thoughts on this?

**Comment by daniellee** [comment]
This issue hits upon several areas of Grafana that we want to improve - timeouts, being able to track badly performing queries to a dashboard and being able to stop users issue queries that will hog database resources. Unfortunately, all of these are long-term goals and that will not help you right now.

Choosing hundreds of values in a variable dropdown is usually not a good idea from a UX/user or from a database standpoint so before we start investigating/making changes is it possible to improve the design of your dashboard? Can those hundreds of values be grouped together?

To take this further, can you give an example of a cloudwatch query with a multi-value template variable and we can investigate the workload created by such a query.

**Comment by mtanda** [comment]
Thanks for @daniellee for responding.

As original author of CloudWatch datasource plugin, I want to talk about performance issue due to current design.

CloudWatch API only has very limited feature when I support templating.
https://github.com/grafana/grafana/pull/5003

So I implement it like, for loop to simple CloudWatch query for all selected templating value.
https://github.com/grafana/grafana/blob/v5.2.1/pkg/tsdb/cloudwatch/cloudwatch.go#L95-L122

This design can't scale for many value, it could cause CPU spike.

Recently, CloudWatch provide GetMetricData API, it may be more scalable.
GetMetricData API support will added in next release.
https://github.com/grafana/grafana/pull/11624

**Comment by marefr** [comment]
Closing this since #11624 now have been fixed.
