### ISSUE TITLE
Preview of values shows none while creating template variable using elasticsearch in Grafana

### ISSUE THREAD

**Issue by TejasviV** [grafana/grafana#12669]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by torkelo** [comment]
Please provide more information, like what query your entering. What query is grafana sending to Elasticsearch and what is Elasticsearch responding with (view in chrome dev tools network tab)
