### ISSUE TITLE
Single Stat Bool, Threshold

### ISSUE THREAD

**Issue by gesandovalr** [grafana/grafana#12663]
Please include this information:
### Color doesn't change.

Hi all,

Excuse me, I been trying to find about how to add bool values as a threshold in Single State Panel, i'm currently using Zabbix as a datasource but unfortunantely, I haven't found the way to do it, I just wanted to know if this is supported.

Thanks and Regards,
German.

**Comment by alexanderzobnin** [comment]
@gesandovalr Could you share your panel JSON, please?

**Comment by torkelo** [comment]
closing this due to no updates
