### ISSUE TITLE
[Feature Request] additional/custom user variables

### ISSUE THREAD

**Issue by quadriq** [grafana/grafana#12667]
It would be nice to have additional user fields/variables, which could be set from WebUI in the user account page.
It could be a simple key=value fields for the first approach. The motivation behind is e.g store API keys to use them later on in "html" dashboards. So those user-variables should be then accessable from dashboards, e.g with %{user_my_api_key}

what do you think?

**Comment by marefr** [comment]
Very similar to #1959. Also similar to #6359
