### ISSUE TITLE
Dashboard links not updated on time-range or variable value change

### ISSUE THREAD

**Issue by jkreileder** [grafana/grafana#12660]
Using 5.2.1:

When you have a dashboard link with 'Include time range' and 'Include variable values' checked, the link doesn't get updated when changing the time range or a variable, i.e. it still contains the time range and variable values it had initially.

**Comment by daniellee** [comment]
Is this different from #12506 ? Guess it is another edge case for this issue.

**Comment by marefr** [comment]
Duplicate of #12506  

Fix will be included in the next Grafana release (5.2.2) or you can use a nightly build
