### ISSUE TITLE
Failed to attach user to existing org when auto_assign_org=false

### ISSUE THREAD

**Issue by bbinet** [grafana/grafana#12666]
### What Grafana version are you using?
v5.2.1

### What OS are you running grafana on?
Linux (Debian stretch)

### What did you do?
I've deleted a user from the server admin page, and then tried to create a new user with the same name/email/password as the deleted user.

### What was the expected result?
Success (204)

### What happened instead?
Internal error (500)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![grafana_create_user_error_500](https://user-images.githubusercontent.com/76281/42995289-c5b27af4-8c10-11e8-9d9c-56bff1a93e75.png)

**Comment by marefr** [comment]
Please check the grafana server log when this error happens and include it here. Thanks

**Comment by bbinet** [comment]
Sure:
```
t=2018-07-23T09:03:38+0000 lvl=eror msg="failed to create user" logger=context userId=13 orgId=49 uname=brunobinet error="UNIQUE constraint failed: org.name"
t=2018-07-23T09:03:38+0000 lvl=eror msg="Request Completed" logger=context userId=13 orgId=49 uname=brunobinet method=POST path=/api/admin/users status=500 remote_addr=172.18.0.1 time_ms=89 size=35 referer=http://localhost:3000/admin/users/create
```

**Comment by bbinet** [comment]
There is no external authentication, but the user was in 2 orgs (its own org and another one that I had created)

**Comment by marefr** [comment]
@bbinet Have you changed the `auto_assign_org` setting? Have you created an organization named *Main Org.* that not has an identifier=1?

```
[users]
# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true
```

**Comment by bbinet** [comment]
@marefr Right, I've set it to false.
Here is my grafana config:
```
GF_USERS_ALLOW_SIGN_UP=false
GF_USERS_AUTO_ASSIGN_ORG=false
GF_PATHS_PLUGINS=/var/lib/grafana/plugins
GF_USERS_AUTO_ASSIGN_ORG_ROLE=Editor
GF_PATHS_LOGS=/var/log/grafana
GF_USERS_ALLOW_ORG_CREATE=false
GF_PATHS_DATA=/var/lib/grafana
GF_SECURITY_ADMIN_PASSWORD=admin
GF_PATHS_CONFIG=/etc/grafana/grafana.ini
GF_PATHS_HOME=/usr/share/grafana
GF_LOG_LEVEL=Info
GF_PATHS_PROVISIONING=/etc/grafana/provisioning
```

**Comment by marefr** [comment]
From [documentation](http://docs.grafana.org/installation/configuration/#auto-assign-org):

> Set to true to automatically add new users to the main organization (id 1). When set to false, new users will automatically cause a new organization to be created for that new user.

In your case that would mean that you've already have an organization named email or username of user you're trying to create.

**Comment by bbinet** [comment]
@marefr Ok, I understand.
I don't know what we can do on grafana side to better explain this issue rather than raising a 500 internal server error.
Grafana could also automatically remove empty org if the deleted user was the last user of the org: it does not make sense to have org without any admin user attached, isn't it?

**Comment by bbinet** [comment]
Or when `auto_assign_org = true`: if we create a new user which  auto assigned org already exists, could we attach the user to the existing org, instead of trying to create an org with the same conflicting name?

**Comment by marefr** [comment]
> Grafana could also automatically remove empty org if the deleted user was the last user of the org: it does not make sense to have org without any admin user attached, isn't it?

Agree what would be a nice to have feature. I think that this is implemented at least when removing org for a user if that user is the only admin left, but not sure.

> Or when auto_assign_org = true: if we create a new user which auto assigned org already exists, could we attach the user to the existing org, instead of trying to create an org with the same conflicting name?

When `auto_assign_org = true` then Grafana will attach all new users to the organization with id=1 and not create any new organizations. 

Note starting from Grafana v5.3 there is a new setting introduced where you can customize the id of the auto assigned org, see #12401.

**Comment by bbinet** [comment]
On Mon, Jul 23, 2018 at 3:22 PM, Marcus Efraimsson <notifications@github.com
> wrote:

> Grafana could also automatically remove empty org if the deleted user was
> the last user of the org: it does not make sense to have org without any
> admin user attached, isn't it?
>
> Agree what would be a nice to have feature. I think that this is
> implemented at least when removing org for a user if that user is the only
> admin left, but not sure.
>
 It does not seem to be implemented, as the deleted user was the last user
of the org.

> Or when auto_assign_org = true: if we create a new user which auto
> assigned org already exists, could we attach the user to the existing org,
> instead of trying to create an org with the same conflicting name?
>
> When auto_assign_org = true then Grafana will attach all new users to the
> organization with id=1 and not create any new organizations.
>
Sorry, I meant when auto_assign_org = false

**Comment by marefr** [comment]
> It does not seem to be implemented, as the deleted user was the last user
of the org.

Think i mixed it up with deleting the last server admin user. And then there is a validation so that you cannot delete the user. Probably not a good idea to automatically remove org when removing last org user because that may come as a surprise for end user. I think the proper workaround here is to deletethe org which will remove all it's users and so forth.

> Sorry, I meant when auto_assign_org = false

Yes, the bug you're hitting could be resolved by attach the user to the existing org, instead of trying to create an org with the same conflicting name.

**Comment by bbinet** [comment]
But, I do want an org to be automatically created for every new user so that they can freely experiment with grafana in their own org.

I think the proper fix when auto_assign_org = false could be that if we create a new user for which an auto assigned org already exists, we could attach the user to this existing org, instead of trying to create an org with the same conflicting name, right?
Or at least, Grafana could send a meaningful error message instead of the 500 internal error.

**Comment by bbinet** [comment]
Sorry I didn't understand correctly your last message.
That's great we are on the same page here!

**Comment by torkelo** [comment]
> But if the user org already exists, then we probably should attach the user to that org.

Would that not be a big security hole? Signing up for Grafana with the same username as an already existing org and being automatically added as member of that org?

**Comment by torkelo** [comment]
Not sure what the fix is we should do for this issue

**Comment by marefr** [comment]
@torkelo  Given your earlier comment 
> Would that not be a big security hole? Signing up for Grafana with the same username as an already existing org and being automatically added as member of that org?

I tend to agree that it would be a security hole. Will close this since there are nothing left to do here.
