### ISSUE TITLE
Memory leak with scripted dashboards

### ISSUE THREAD

**Issue by nirlo** [grafana/grafana#12671]
### What Grafana version are you using?
5.2.1

### What datasource are you using?
influxdb

### What OS are you running grafana on?
RHEL 7

### What did you do?
I've created a scripted dashboard take takes in datasource and host and opens a new tab with the data for that server. When this new tab is left open along with my main dashboard, memory and cpu usage on my station increases until the tabs crash. 

My main dashboard has 53 status panels. refreshing every 30s

My scripted dashboard has 14 graphs for cpu, memory, network, and disk usages. It is static for the last 6h

Dashboards run on Chrome 67.0.3396.99

### What was the expected result?
For the tabs to remain open and memory consumption to not increase

### What happened instead?
Memory leak from dashboards, causing the tabs to eventually crash after reaching 90% memory use (2.5gb just for grafana chrome tabs).

![untitled](https://user-images.githubusercontent.com/21220901/43005726-b9daeefa-8c01-11e8-980c-c71d67f59937.png)

**Comment by nirlo** [comment]
More information:
I've tested by having the main dashboard open with one scripted. As the memory usage increases, I have closed the scripted dashboard and memory usage continues to increase. 

The main dashboard uses Status Panels, a plugin found here https://github.com/Vonage/Grafana_Status_panel

**Comment by daniellee** [comment]
Do you have any other scripted dashboards? Is it just the dashboard with the Vonage Status panels that causes this issue?

**Comment by nirlo** [comment]
I've tested more and it seems to be sporadic. I had the memory spike this morning and crash the two tabs I had open and now have had two tabs open for the last two hours without any memory issues.

Here is the code for my scripted dashboard.  I've scrubbed it a bit for an private company information.

This dynamically creates the dashboard in the smallest amount of code that I could figure out so far, so It could very well be in here. 


`/* Script for dynamically creating server dashboards Version 3.0.0
*
* This version will modularize the script to make it easier to add panels
* and makes changes to the panels.
*
* There are two main parameters that are taken in POST, the server host name
* and the datasource. Currently the datasource is neccessary until the all hosts
* are placed into one datasource.
*
* In version 3.2, I have further condensed and modularized the Script
* and shortened. Add information to the appropriate spots. Titles 
* determines the number of panels needed. Ensure that to added the case
* number to the switches in the for loop to ensure a valid dashboard.
*
* @author Nicholas Lockhart
* @email nlockhart@rbbn.com
*
*/

//Varables

//neccessary variables for the browser
var window, document, ARGS, $, jQuery, moment, kbn;

//dictionary of panel titles
var titles = [
    "Memory",
    "Load",
    "Memory Usage",
    "CPU",
    "Per Process CPU Usage",
    "Per Process Mem Usage",
    "Disk I/O Requests",
    "Disk Usage with Backups",
    "Disk Inodes",
    "Disk I/O time",
    "Network Packets",
    "Network Usage",
    "Packets Dropped",
    "Packets Error"
];

//Setting the various yaxes of the graphs. These determine the what values are shown.
//First in the list is the left axes that is the one typically shown, the second is 
//the right axes. I have not seen a need for it, but it is needed for a valid dashboard.
var yaxes = {
  bytes: [    {
        "format": "bytes",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": "0",
        "show": true
      },
      {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": false
      }],
  short: [    {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": true
      },
      {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": false
      }],
  percent: [    {
        "format": "percent",
        "label": null,
        "logBase": 1,
        "max": "100",
        "min": null,
        "show": true
      },
      {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": false
      }],
  bps: [    {
        "format": "bps",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": true
      },
      {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": false
      }],
  pps: [    {
        "format": "pps",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": true
      },
      {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": false
      }],
  iops: [    {
        "format": "iops",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": true
      },
      {
        "format": "short",
        "label": null,
        "logBase": 1,
        "max": null,
        "min": null,
        "show": true
      }],
  ms: [  {
      "format": "ms",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }]
};

//series overrides. Creates a nicer graph for disk R/W and network input/output
var overrides = {
  one: [{
      "alias": "/in$/",
      "transform": "negative-Y"
    }],
  two: [{
      "alias": "/read/",
      "transform": "negative-Y"
    }]
};

//determines the placement of the panel
var y = 0;


//variables to hold the POST paramters
var datasource = "";
var host = "";
var disk = "";

//the above variables must set before the rest can be done

//sets the host from the parameters
if(!_.isUndefined(ARGS.host)) {
  host = ARGS.host;
}

//sets the datasource from the parameters
if(!_.isUndefined(ARGS.datasource)){
  datasource = ARGS.datasource;
}

//sets the disk. This changes based on the system in question
//currently it will either be '/' for the majority or
//'/idisk1' for artifactory servers
//This depends on what you want to be reported for that particular server
if(host.includes("artent") || host.includes("***")) {
  disk = "\"path\" = '***'";
}else if(host.includes("****")){
  disk = "\"path\" = '*****'"; 
}else if(host.includes("****")) {
  disk = "\"path\" = '*****'"
}else if(host.includes("jnk01")) {
  disk = "\"path\" = '*****'";
}else {
  disk = "\"device\" = 'rootfs"
}

// This should related to the titles array exactly. Add the variables that you need from above
var queries = [
  //Memory query
     "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffreed) as buffered  FROM \"mem\" WHERE host = '"+ host +"' AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
  //Load Query
     "SELECT mean(load1) as load1, mean(lead5) as load5, mean(load15) as load15 FROM \"system\" WHERE host = '"+ host +"' AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
  //Memory used Query
     "SELECT mean(used_percent) as \"Memory Used\" FROM \"mem\" WHERE host = '"+ host +"' AND $timeFilter GROUP BY time($interval)",
  //Cpu query
     "SELECT mean(usage_idle) as \"idle\", mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\" FROM \"cpu\" WHERE host = '"+ host +"' AND cpu='cpu-total' AND $timeFilter GROUP BY time($interval), *",
  //cpu procstat query
     "SELECT mean(\"cpu_usage\") FROM \"procstat\" WHERE (\"host\" = '"+ host +"') AND $timeFilter GROUP BY \"process_name\",  time($__interval) fill(null) ",
  //memory procstat query
     "SELECT mean(\"memory_data\") FROM \"procstat\" WHERE (\"host\" = '"+ host +"') AND $timeFilter GROUP BY \"process_name\",  time($__interval) fill(null)",
  //diskio query
     "SELECT non_negative_derivative(mean(reads), 1s) as \"read\",  non_negative_derivative(mean(writes), 1s) as \"write\" FROM \"diskio\" WHERE(\"host\" = '"+ host +"') AND \"name\" =~/(v|s)d[a-z]$/ AND $timeFilter GROUP BY time($__interval), *",
  //disk totals query
     "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" = '"+ host +"' AND "+ disk +"' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
  //ionodes query
     "SELECT mean(inodes_free) as \"free\", mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" = '"+ host +"' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
  //read/write time query
     "SELECT non_negative_derivative(mean(read_time),1s) as \"read\", non_negative_derivative(mean(write_time), 1s) as \"write\" FROM \"diskio\" WHERE \"host\" = '"+ host +"' AND \"name\" =~/(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
  //network packets query
     "SELECT non_negative_derivative(mean(\"packets_recv\"), 10s) as \"in\", non_negative_derivative(mean(\"packets_sent\"), 10s) as \"out\" FROM \"net\" WHERE (\"host\" = '"+ host +"') AND $timeFilter GROUP BY time($__interval) fill(null)",
  //network usage query
     "SELECT non_negative_derivative(mean(bytes_recv), 1s)*8 as \"in\", non_negative_derivative(mean(bytes_sent), 1s) as \"out\" FROM \"net\" WHERE (\"host\" = '"+ host +"') AND  interface =~ /(vlan|eth|bond|ens).*/ AND $timeFilter GROUP BY time($interval), * fill(none)",
  //packets dropped query
     "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host = '"+ host +"' AND interface =~ /(vlan|eth|bond|ens).*/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
  //netowrk errors query
     "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host = '"+ host +"' AND interface =~ /(vlan|eth|bond|ens).*/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
];

// Anything that sets an attribute to dashboard is neccessary. Remove and risk not knowing what breaks

//variables for managing the dashboard. These dont need to change too much.
var dashboard = {};
dashboard.iteration = 1526303860304;
dashboard.links = [];
dashboard.tags = [];
dashboard.version = 15;
dashboard.uid = "xyLR6aMnl";
dashboard.panels = [];
dashboard.editable = true;
dashboard.gnetId = null;
dashboard.graphTooltip = 0;
dashboard.id = 131;
dashboard.title = host + " Dash";
dashboard.style = "dark";
dashboard.refresh = false;
dashboard.schemaVersion = 16;
dashboard.timezone = "";

//time options
dashboard.timepicker = {
  "refresh_intervals": [
    "5s",
    "10s",
    "30s",
    "1m",
    "5m",
    "15m",
    "30m",
    "1h",
    "2h",
    "1d"
  ],
  "time_options": [
    "5m",
    "15m",
    "1h",
    "6h",
    "12h",
    "24h",
    "2d",
    "7d",
    "30d"
  ]
};
//sets the inital time span for the dashboard
dashboard.time = {
  "from": "now-6h",
  "to": "now"
};
//templating of the dashboard
dashboard.templating =  {
  "list": [
    {
      "auto": false,
      "auto_count": 30,
      "auto_min": "10s",
      "current": {
        "text": "1m",
        "value": "1m"
      },
      "hide": 0,
      "label": null,
      "name": "Interval",
      "options": [
        {
          "selected": true,
          "text": "1m",
          "value": "1m"
        },
        {
          "selected": false,
          "text": "10m",
          "value": "10m"
        },
        {
          "selected": false,
          "text": "30m",
          "value": "30m"
        },
        {
          "selected": false,
          "text": "1h",
          "value": "1h"
        },
        {
          "selected": false,
          "text": "6h",
          "value": "6h"
        },
        {
          "selected": false,
          "text": "12h",
          "value": "12h"
        },
        {
          "selected": false,
          "text": "1d",
          "value": "1d"
        },
        {
          "selected": false,
          "text": "7d",
          "value": "7d"
        },
        {
          "selected": false,
          "text": "14d",
          "value": "14d"
        },
        {
          "selected": false,
          "text": "30d",
          "value": "30d"
        }
      ],
      "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d",
      "refresh": 2,
      "type": "interval"
    }
  ]
};
//annotations for the head of the json dashboard
dashboard.annotations = {
  "list": [
    {
      "$$hashKey": "object:1293",
      "builtIn": 1,
      "datasource": "-- Grafana --",
      "enable": true,
      "hide": true,
      "iconColor": "rgba(0, 211, 255, 1)",
      "name": "Annotations & Alerts",
      "type": "dashboard"
    }
  ]
};

//The meat of the script. This will run through the titles length and ensures that the appropriate 
//panel/row is added to the dashboard. 
for(var i = 0; i < titles.length; i++) {

      var tags = "$col";

      //sets the tag and skips the procstat panels if not reported
      if((!host.includes("*****"))&&(i==4||i==5)) {
        continue;
      } else if(i==5||i==6) {
        tags = "$tag_process_name";
      }

      //various variables for vital appropriation
      var or = [];
      var a = [];
      var x = 0;

      //sets the horizontal position of the panel
      if(i%2 != 0) {
        x = 12;
      }

      //sets overrides for negative y axes graphs
      if(titles[i].includes("I/O")){
        or = overrides.two;
      } else if (titles[i].includes("Network ") || titles[i].includes("Network ")) {
        or = overrides.one;
      }

    //sets the value of the yaxes. refer to yaxes to see the values for the yaxes
    //and add here based on the position in the panel you want to add
      switch(i){
        case 0:
        case 5:
        case 7:
        case 8:
          a = yaxes.bytes;
          break;
        case 1:
        case 12:
        case 13:
          a = yaxes.short;
          break;
        case 11:
          a = yaxes.bps;
          break;
        case 10:
          a = yaxes.pps;
          break;
        case 2:
        case 3:
        case 4:
          a = yaxes.percent;
          break;
        case 6:
          a = yaxes.iops;
          break;
        case 9:
          a = yaxes.ms;
          break;
        default:
          a = [];
          break;
      }
      //Where the panel is added with the specific values evaluated by the script
      dashboard.panels.push({
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": datasource,
      "fill": 1,
      "gridPos": {
        "h": 6,
        "w": 12,
        "x": x,
        "y": y
      },
      "id": i,
      "legend": {
        "alignAsTable": true,
          "avg": false,
          "current": true,
          "max": true,
          "min": false,
          "show": true,
          "total": false,
          "values": true,
          "rightSide": true,
          "sort": "max",
          "sortDesc": true
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": or,
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "alias": tags,
          "groupBy": [
            {
              "params": [
                "$__interval"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "orderByTime": "ASC",
          "policy": "default",
          "query": queries[i],
          "rawQuery": true,
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": titles[i],
      "tooltip": {
        "shared": true,
        "sort": 2,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": a,
      "transparent": true
    });

    //modify the y value. since the current spec of the dashboard has two columns, it is only changed on specific values
    if(i%2 != 0) {
      y+=6;
    }
    

}

return dashboard;
`

**Comment by nirlo** [comment]
So the memory spikes and crashes are sporadic, It crashed this morning after 30 mins with two tabs open. For the last two hours, I've had two tabs open and no issues with memory

This is the code here.

It dynamically creates the dashboard in a few lines as I could muster, so I assume the issue is in here. The documentation on scripted dashboards seems to be minimal

[script_scrubbed.js.txt](https://github.com/grafana/grafana/files/2219684/script_scrubbed.js.txt)

**Comment by nirlo** [comment]
The dashboard with the vonage status panels is not scripted. instead, the scripted dashboard is created when a user clicks on a panel, passing host name and datasource as parameters, opening it in a new tab as a drilldown and larger overview of the server

**Comment by nirlo** [comment]
Update:

Tested further with firefox 61.0.1

It seems that the issue persists on ff, with grafana utilizing almost 2gb of memory.



I captured performance metrics for both the status panel dashboard as well as the scripted drilldown dashboard. I started both of these captures as soon as the tabs were open.

I've attached them here. From what I see, it seems to be an issue with cycle collection and garbage collection with the app?
![drilldown_capture](https://user-images.githubusercontent.com/21220901/43165636-6efc6dfa-8f62-11e8-9796-d87f0e8c1e96.PNG)
![maindash_capture](https://user-images.githubusercontent.com/21220901/43165645-723b9374-8f62-11e8-8f62-1b1665341fcf.PNG)

**Comment by nirlo** [comment]
For interested parties, here are the json files from the performance monitoring from firefox

[Drilldown.txt](https://github.com/grafana/grafana/files/2225430/Drilldown.txt)
[maindash.txt](https://github.com/grafana/grafana/files/2225431/maindash.txt)

**Comment by torkelo** [comment]
should be fixed/improved by merging https://github.com/grafana/grafana/pull/13740
