### ISSUE TITLE
Unauthorized (401) when trying to change default admin password via GUI

### ISSUE THREAD

**Issue by Cweltz** [grafana/grafana#12676]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
v.5.2.1

### What OS are you running grafana on?
Amazon Linux AMI 2018.03 on AWS EC2

### What did you do?
I was trying to first login to the admin default user after installaton of grafana and then i had to change password as expected.

### What was the expected result?
I expected it to be changed and make me log into the console. 
### What happened instead?
I simply received a message "Unauthorized" with no additional information.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

```
Possibly unhandled rejection: {"message":"Unauthorized","severity":"warning"}
(anonymous) @ angular.js:14700
PUT https://dbmc-monitoring.dbmc.dbmc.comp.db.de/grafana/api/user/password 401 () angular.js:12759

angular.js:14700 Possibly unhandled rejection: {"data":{"message":"Unauthorized"},"status":401,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/user/password","data":{"newPassword":"8AjNk6fmYV63CtyHSkRP","confirmNew":"8AjNk6fmYV63CtyHSkRP","oldPassword":"admin"},"retry":0,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"complete"}
```

So I cannot log in into the console as I am unable to change the default admin password for the default admin user. Is there any workaround for it? 

Additional information:
- I just tried creating another user and logging in - Same problem. 
- I am running grafanda as a reverse proxy behind an apache 
- Part of my config:

```
#################################### Auth Proxy ##########################
[auth.proxy]
;enabled = true
;header_name = X-WEBAUTH-USER
;header_property = username
;auto_sign_up = true
;ldap_sync_ttl = 60
#;whitelist = 192.168.1.1, 192.168.2.1

#################################### Basic Auth ##########################
[auth.basic]
;enabled = true
```
```
--- HTTPD Conf
<Virtualhost *:8008>

ServerName dbmc-monitoring.dbmc.dbmc.comp.db.de
RewriteEngine on
RewriteRule ^/?$ /grafana/ [R=permanent,L]
<Location "/grafana">
  ProxyPass http://localhost:3000
</Location>
ProxyPassReverse /grafana http://localhost:3000
</VirtualHost>
```

Thanks so far and regards.

**Comment by daniellee** [comment]
Just so you know that semicolon, `;` means that a line is commented out in an ini file. So in the Grafana ini snippet in the issue, all the lines are commented out. Not sure if that has anything to do with this problem though.

**Comment by daniellee** [comment]
Do you have access to the Grafana server logs? Is there anymore information there?

**Comment by Cweltz** [comment]
That was a really stupid mistake by not seeing these are comments. I am really sorry for my stupidity. 

After commenting everything in I am getting the following problem:

I get a permanent redirect when trying to login so I hit the login button and being redirected to the login page of grafana.

=2018-07-21T09:36:42+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr="10.180.44.101, 10.104.180.169" time_ms=0 size=37 referer=https://dbmc-monitoring.dbmc.dbmc.comp.db.de/grafana/login

apache.conf:
```
ServerName dbmc-monitoring.dbmc.dbmc.comp.db.de
ProxyPass /grafana http://localhost:3000
ProxyPassReverse /grafana http://localhost:3000/grafana
```

Grafana.ini
```
root_url = https://dbmc-monitoring.dbmc.dbmc.comp.db.de/grafana
```

I'm using apache as a reverse proxy which is behind an AWS Load Balancer. 

I'd be glad if you could provide help here.

**Comment by marefr** [comment]
@Cweltz does it make any difference if you use a trailing slash for ProxyPass, ProxyPassReverse and root_url and /grafana/ in apache.conf? We use that configuration when testing apache reverse proxy, see [code](https://github.com/grafana/grafana/blob/master/docker/blocks/apache_proxy/proxy.conf), and if remembering correctly I think there was some problem without trailing slashes, but could be wrong.

**Comment by marefr** [comment]
Closing this due to no response.
