### ISSUE TITLE
Rows aren't merging in a table panel.

### ISSUE THREAD

**Issue by lesovsky** [grafana/grafana#12688]
Hi,

I’m trying to organize data in a table panel and trying to merge values from multiple queries in a table, but with no success.
I’ve started with two metrics, which have the same set of labels and even label's values are the same:
```
1. node_filesystem_total_bytes{db_instance=“db1”,device="/dev/md0",flags=“rw,noatime,nobarrier,stripe=512,data=ordered”,fstype=“ext4”,job=“db_system”,mountpoint="/mnt/nvme",sysid=“6364961867687332226”}
2. node_filesystem_used_bytes{db_instance=“db1”,device="/dev/md0",flags=“rw,noatime,nobarrier,stripe=512,data=ordered”,fstype=“ext4”,job=“db_system”,mountpoint="/mnt/nvme",sysid=“6364961867687332226”}
```

But in the result table, I've got metric’s results are in the separate rows. Take a look at the picture below on Value #A and Value #B
![garafana-table](https://user-images.githubusercontent.com/953312/43058518-7e5e6b9c-8e61-11e8-88a6-fe95eca1db8d.png)

Also I've made a single metric `node_filesystem_usage` with special label `usage` with values like total/free/used. Next I've tried to create table again based on that metric, but got separate rows again.

How can I merge this rows into the single one? Or is it working as intended?

grafana 5.2.1, prometheus data source, centos 7.5 linux. `Table Transform` set to `Table`

**Comment by daniellee** [comment]
They should be merged if the datetime column and labels match and I can't see anything obvious in your screenshot. Can you check using Query Inspector if there is some difference between the rows. You can also trying hiding columns one-by-one to figure out which column is causing the merge not to happen.

Example dashboard: https://play.grafana.org/d/000000065/prometheus-console-tables?panelId=2&fullscreen&edit&orgId=1

Docs: http://docs.grafana.org/features/panels/table_panel/#merge-multiple-queries-per-table

**Comment by marefr** [comment]
@lesovsky There's a workaround in https://github.com/grafana/grafana/pull/10050#issuecomment-393207206 that maybe help?

**Comment by lesovsky** [comment]
@daniellee thank you, for the example. The problem was solved with `sum by ()`, which wasn't obvious for me from Grafana documentation.

Everything works OK now, thanks!
![image](https://user-images.githubusercontent.com/953312/43071865-836c6824-8e8d-11e8-8c13-6899aca5c7e1.png)
