### ISSUE TITLE
[Bug] Saving dashboard with missing alert params results in 500 instead of 400 error

### ISSUE THREAD

**Issue by TDabasinskas** [grafana/grafana#12689]
### What Grafana version are you using?

v5.2.1

### What datasource are you using?

Prometheus, but it's not applicable for this specific issue.

### What OS are you running grafana on?

`grafana/grafana` Docker container.

### What did you do?

1. Create new dashboard with new Graph panel.
2. Go to Alerts tab and create new alert.
3. Do not specify `Is Above` condition.
4. Click `Save Dashboard` button.

### What was the expected result?

/api/dashboards/db/ returns `400` code, as the alert data is invalid (which is the case, as the required data is missing).

### What happened instead?

/api/dashboards/db/ returns `500` code, which represents internal server error.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
```
{
  "dashboard": {
    "panels": [
      {
        "alert": {
          "conditions": [
            {
              "evaluator": {
                "params": [
                  null
                ],
                "type": "gt"
              },
              "operator": {
                "type": "and"
              },
              "query": {
                "params": [
                  "A",
                  "5m",
                  "now"
                ]
              },
              "reducer": {
                "params": [],
                "type": "avg"
              },
              "type": "query"
            }
          ],
          "executionErrorState": "alerting",
          "frequency": "60s",
          "handler": 1,
          "name": "Panel Title alert",
          "noDataState": "no_data",
          "notifications": []
        }
      }
    ]
  }
}
```

**Comment by bergquist** [comment]
This have been fixed in 5.3. it should return 422 now.
