### ISSUE TITLE
plugin open-falcon : The datasource does not support alerting queries

### ISSUE THREAD

**Issue by younglifestyle** [grafana/grafana#12686]
grafana v5.2 , datasource is open-falcon OS is Linux 
I want to use the alarm function, but I found that there seems to be a warning.
“The datasource does not support alerting queries”
I want ask it, how do I need to support the Alerting function?

**Comment by daniellee** [comment]
That is not currently possible. We will be adding a new capability to Grafana soon (1-3 months) that allows plugins to support alerting.
