### ISSUE TITLE
[Feature Request] Save dashboard with new uid

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#12687]
### What Grafana version are you using? Grafana 5.2.1

What I would like to be able to do is use the dashboard in two different folders that have different data sources and queries.

The first thing I tried was to save a dashboard and then re-import it BUT the "uid" for the dashboard stays the same so to have two instances of very similar dashboards, I need to export the dashboard, edit the json file so that it has a new uid and then import it. Now I have two unique instances of the same dashboard and I can edit the new one safely.

Maybe in the "Export" dialogue under "Share", add a "Save to file with new name", next to "Save to file"? This would give the dashboard a new name and a new uid.

I suppose that is a long winded approach to duplicating a dashboard from folder X into folder Y.

**Comment by yellowpattern** [comment]
Should the "Unique identifier" option on Import handle this?

**Comment by marefr** [comment]
Since v5.2.0 you can change the uid when importing, see #12092. If you want to import as new, click on Change and remove the uid value.
