### ISSUE TITLE
Legend: Measurement names move left when scrolling / just moving mouse.

### ISSUE THREAD

**Issue by wesleyorama** [grafana/grafana#12695]
Please include this information:
### What Grafana version are you using?
* Grafana v5.1.0 `( 844bdc53a )`
### What datasource are you using?
* influx
### What OS are you running grafana on?
* Centos
### What did you do?
* move my cursor over the metric name in the legend, scroll a little. 
### What was the expected result?
* the metric names dont start moving left.
### What happened instead?
* the metric names start moving left. 
### If related to metric query / data viz:
* Data Viz
### Browser
* Firefox 61.0.1 (64-bit)
### Client OS
* Fedora 28

Photos / gifs:
https://imgur.com/a/NKMcrHE

https://imgur.com/a/1aXeIEs

**Comment by marefr** [comment]
Please upgrade to at least 5.1.3, fixed in #11830
