### ISSUE TITLE
[Feature Request] ability to display the text of the "Value-to-text" custom template variable aliasing in the table panel

### ISSUE THREAD

**Issue by rofran** [grafana/grafana#12697]
from https://github.com/grafana/grafana/issues/12694

I'm using extensively the Simple JSON Datasource plugin as a custom variable aliasing (with 
/search endpoints that returns { text: "label", value: "rawValue" } map responses).

I would like to use this functionality in the table panel. Currently I'm using the $tag_exampletag 
alias pattern in the "ALIAS BY" table panel propierty which displays unfriendly ID codes. It would be 
possible to denfine a new "table panel alias pattern" which use the text of the "Value-to-text" Simple 
JSON Datasource template variables?
  
For example, being $tagname1 a simpleJSON datasource template variable, could be something similar
to $tagtext_tagname1[$tag_exampletag].

Please include this information:
### What Grafana version are you using?
Grafana v5.1.4 (commit: a5fe24f)
### What datasource are you using?
SimpleJson (Version 1.4.0)

**Comment by marefr** [comment]
Still wrong repo. Think simplejson datasource should add capability for returning more data, like tags, or similar so that you can use that for aliases which I still think this issue belongs in the simplejson repo.
