### ISSUE TITLE
HTTP proxy (grafana hosted on windows server 2016)

### ISSUE THREAD

**Issue by atartareanu** [grafana/grafana#12703]
Please include this information:
### What did you do? try to configure a new notification channel. no direct internet access, but with winhttp proxy set 
netsh winhttp show proxy
Current WinHTTP proxy settings:
    Proxy Server(s) :  proxy.mycompany.org:3128
    Bypass List     :  (none)
 
### What happened instead? timeout

t=2018-07-24T12:23:10+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.webhook error="Post https://vip-149-96-20-164.cust.service-now.com/grafana_alerts.do: dial tcp 149.96.20.164:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." webhook=EOPS-DEV
t=2018-07-24T12:23:10+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=9 uname=admin error="Post https://vip-149-96-20-164.cust.service-now.com/grafana_alerts.do: dial tcp 149.96.20.164:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

is there any possibility to set the http proxy in custom.ini ?

**Comment by marefr** [comment]
No support for setting this in custom.ini. You set proxy through environment variables. Either globally on machine or before starting Grafana. 

See [issue comments](https://github.com/grafana/grafana/issues/1691#issuecomment-102164444) for examples. That's examples for linux environment, but on Windows you'll use appropriate instructions for settings environment variables on Windows.

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by atartareanu** [comment]
thank you.

**Comment by jacobneroth** [comment]
what is the settings for windows ?
