### ISSUE TITLE
Variables not interpreted in Y axis labels

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#12710]
In Grafana v5.2.1 `{{ vars }}` are not interpreted in the labels of Y axis.

**Comment by marefr** [comment]
Please provide more information. What panel? What datasource? What variables, if any?

**Comment by sylr** [comment]
Datasource: Prometheus
Panel: Graph
Variables: Any user defines variable

![screenshot_8](https://user-images.githubusercontent.com/153052/43189453-eaed7c1c-8ff6-11e8-9119-3cd1ffcb493e.png)

**Comment by marefr** [comment]
Thanks. Duplicate of #5983
