### ISSUE TITLE
[Feat] Use metric column as prefix when returning multiple value columns

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#12727]
Currently if you return a metric column and multiple value columns all value columns will be munged into the same series. Would be nice if the metric column could be used as prefix for the value columns.

**Comment by marefr** [comment]
Fixed by #12679

**Comment by beingyash** [comment]
@marefr This also needs to be available for elasticsearch as when multiple queries return the same series names, the transformation operations cannot distinguish the series returned by both queries individually and hence show only the series names once.

**Comment by marefr** [comment]
@beingyash please open a separate issue to track if there isn't one already open.
