### ISSUE TITLE
Postgres return 'message : "pq: syntax error at or near "$""' when create nested variable

### ISSUE THREAD

**Issue by anriqing** [grafana/grafana#12721]
Please include this information:

What Grafana version are you using?
5.2.0-pre1

What datasource are you using?
postgresql

What OS are you running grafana on?
centos 7.0

What did you do?
1. Create a variable named region. It shows below values.
![image](https://user-images.githubusercontent.com/40029056/43240542-a60f5ff6-90c9-11e8-96e6-4803726934db.png)

![image](https://user-images.githubusercontent.com/40029056/43240699-5251cbdc-90ca-11e8-8584-5c277ba1503a.png)

2. Create a nested variable named component. It returns 'message : "pq: syntax error at or near "$""' .
![image](https://user-images.githubusercontent.com/40029056/43240601-ec9ff912-90c9-11e8-8121-1e4a59bc88e1.png)

**Comment by anriqing** [comment]
@marefr  Thank you very much for your advise. 
I updated my grafana to 5.2.2.1, and it still shows the same error message.
![image](https://user-images.githubusercontent.com/40029056/43352805-ca7ba654-925b-11e8-955d-04d3f697551e.png)

**Comment by marefr** [comment]
What postgres version? Seems like you have at least one null value and chinese (?) character in region which could potentially cause your problem.

Could you please include screenshots of configuration screens for rergion and component variable? Also, when this error happens what values of region have you selected?

**Comment by svenklemm** [comment]
Looks like variables are not expanded in variable queries, which i can reproduce.

**Comment by marefr** [comment]
Unable to reproduce using latest master (5.3-pre1)

**Comment by marefr** [comment]
Do you have any null values in those 150? What if you do

`select distinct region_name from sub_change_order_do where region_name is not null` 

Does that work?

**Comment by anriqing** [comment]
You are right. There IS null value in those 150. Your query works too.

**Comment by marefr** [comment]
Closing this. Will consider reopen if you think that null values should be supported in variables.
