### ISSUE TITLE
[Feature request] Alerting on Zulip Chat

### ISSUE THREAD

**Issue by ezq** [grafana/grafana#12732]
Please include this information:
### What Grafana version are you using?
v5.0.0-beta3
### What datasource are you using?
influxdb
### What OS are you running grafana on?
Ubuntu

I'm trying to set up an alert using webhooks to a Zulip Chat. I use de Zulip documentation but alerts never arrive Zulip. 

The question is: Has anyone be succesful to set up notifications to Zulip?

**Comment by marefr** [comment]
Not sure if this is a feature request, a question or both?

For questions, please use our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by ezq** [comment]
Sorry, I'd like to have a connector in to send alerts to zulip chat, I've tried with webhook, but nothing happens. I wan't to know if its posible to use webhook or is necesary to make a new notification channel

**Comment by marefr** [comment]
Webhook works, but you probably need a service/proxy to send the webhooks to which then sends them to zulip

**Comment by devZer0** [comment]
i'm sending personal messages via zulip api this way from linux commandline:

curl -s https://zulip-server.domain/api/v1/messages -u my-bot@chat.cybercon.de:#api-key# -d "type=private" -d "to=$email" -d $"content=my_message_contents_here"

so, if grafana is able to do https request, it should be able to talk to zulip. even with including images.

why do you think we need a service/proxy ?

i have zulip and grafana here and some linux/web knowledge, if you like we can work it out together to make it work and make some little howto

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
