### ISSUE TITLE
[Bug?]Slack Bot Notification only image

### ISSUE THREAD

**Issue by Mon-terr** [grafana/grafana#12735]
Read before posting:

Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue.
Checkout FAQ: https://community.grafana.com/c/howto/faq
Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
Please include this information:

What Grafana version are you using?
Grafana 5.2.0

What datasource are you using?
Elasticsearch

What OS are you running grafana on?
Ubuntu 16.04

What did you do?
Slack Notification

What was the expected result?
receiving body message and image

What happened instead?
I got only image

How can I solve this issue?

My settings
![1](https://user-images.githubusercontent.com/33366914/43304458-360f21f0-91af-11e8-8169-bbc1b0dd313f.PNG)
![default](https://user-images.githubusercontent.com/33366914/43304459-3644c29c-91af-11e8-8989-5f539b229079.PNG)

**Comment by Mon-terr** [comment]
Add logs
(Test Send Logs)

![2](https://user-images.githubusercontent.com/33366914/43308839-d103227a-91bd-11e8-8bd2-b97021c93c58.PNG)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Please read the documentation if you haven't already: http://docs.grafana.org/alerting/notifications/#slack

> If you want to include screenshots of the firing alerts in the Slack messages you have to configure either the external image destination in Grafana, or a bot integration via Slack Apps.

Thing is that testing notification channel only uploads an image. When you configure an alert rule it will include alert details plus any mention. Seems like you're using the bot integration which will create 2 posts in slack whereby using the external image destination you'll get alert plus image in the same post in slack.
