### ISSUE TITLE
Grafana Alerting Issue: tsdb.HandleRequest() error bad_response: bad response code 502

### ISSUE THREAD

**Issue by kamrajshahapure** [grafana/grafana#12739]
While creating any alerts on Grafana, I am facing an error "tsdb.HandleRequest() error bad_response: bad response code 502" every single time, tried to find out but couldn't find the solution since nobody else had this issue in the past. Here is the screenshot for the same

![image](https://user-images.githubusercontent.com/33791474/43317490-a14c9776-91ba-11e8-8e9d-d3f31b8e3a6c.png)

Edit:
1. Grafana version: 5.1.4
2. Datasource: Prometheus 2.3.1

Thanks in Advance :)

**Comment by marefr** [comment]
What grafana version? What datasource and how have you configured it? Any proxy configured to be used for datasource?

**Comment by kamrajshahapure** [comment]
Hi, 
I am using
1. Grafana version: 5.1.4
2. Datasource: Prometheus 2.3.1

(Added same info as an edit)

**Comment by marefr** [comment]
And my other questions? Screenshot of datasource configuration? Any proxy? Any special authentication?

**Comment by marefr** [comment]
So what happens if you change access to Server? I guess it would fail. Server access mode is kind of how prometheus are accessed in when evaluating alerting rules

**Comment by marefr** [comment]
Glad you worked it out. Browser access mode should only be used in the case of you cannot use server access mode due to special authentication or similar.
