### ISSUE TITLE
[postgres] $__timeGroup macro without alias

### ISSUE THREAD

**Issue by svenklemm** [grafana/grafana#12749]
The ```$__timeGroup``` macro is at the moment handled differently between the sql datasources. Postgres is the only one that adds a column alias to make it more convenient to use. Since you can reference columns by their index there was no need to have it without alias for GROUP BY or ORDER BY. Unfortunately you cannot always reference columns by index for example in window functions ORDER BY 1 will not reference the first column but 1 will be interpreted as literal.
For the window function use case it would be very useful to have a $__timeGroup macro that doesn't add an alias. 

Should the postgres $__timeGroup macro be changed to make it identical to the other sql datasources or should another macro be added which doesn't add an alias. 
Changing the postgres macro will be a breaking change.

**Comment by marefr** [comment]
Long term having another macro which basically does the same thing will probably lead to more confusion than introducing a breaking change.

Maybe possible to interpret timeGroup not having an alias and add it for backward compatibility?
