### ISSUE TITLE
iframe height(scroll) rendering issues

### ISSUE THREAD

**Issue by AkshaySharma7** [grafana/grafana#12754]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Hi Team,

I am using iframe to load grafana's dashboard inside an application. I am facing issues with dashboard's scroll bar inside iframe. I have been using Grafana 4.6.2 till date, but facing issues with scroll bar in Grafana 5.2.2. I guess I am facing these issues due to the CSS change. The following is the code through which I am loading Grafana's dashboards in an application - 
![image](https://user-images.githubusercontent.com/31236273/43387375-e4283abe-9403-11e8-8298-5103a204ac77.png)

And the style of the iframe is being set through a JS function - 
![image](https://user-images.githubusercontent.com/31236273/43387459-1d105b40-9404-11e8-9fba-f3256a20458e.png)

The height of the iframe doesn't automatically increases with respect to the content in the dashboards, resulting in a scroll bar inside iframe. Please check the issue, and let me know if there's anything specific to be taken care.

Thanks,
Akshay

**Comment by torkelo** [comment]
think you have to adjust the iframe height dynamically yourself (using code).
https://stackoverflow.com/questions/9162933/make-iframe-height-dynamic-based-on-content-inside-jquery-javascript
