### ISSUE TITLE
[ui] Support iOS home screen "app" icons

### ISSUE THREAD

**Issue by andig** [grafana/grafana#12752]
The UX of adding Grafana as iOS home screen icon could be improved:

  - provide high-res icons
  - add `apply-mobile-web-app-capable` headers that remove the 

Meta headers could look like:

	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	
	<link rel="apple-touch-icon" sizes="57x57" href="ico/apple-touch-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="ico/apple-touch-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="ico/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="ico/apple-touch-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="ico/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="ico/apple-touch-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="ico/apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="ico/apple-touch-icon-152x152.png">
´	<link rel="apple-touch-icon" sizes="180x180" href="ico/apple-touch-icon-180x180.png">

Android has similar requirements for high-res icons. Apps like http://realfavicongenerator.net can help with the implementation (no ad intended- I'm not affilicated with that site in any way).

If you want to give access to a truly high-res version of the grafana icon I'd be happy to support with a PR.

**Comment by torkelo** [comment]
Here is the highest res version we have (currently, source is vector based)
![grafana_icon](https://user-images.githubusercontent.com/10999/43383564-afa9ea6c-93db-11e8-855b-de8be4f79756.png)

**Comment by andig** [comment]
png @torkelo pr ready for review

**Comment by berniezhao** [comment]
One problem with this meta
`<meta name="apple-mobile-web-app-capable" content="yes">`
This tells Safari we support offline mode. When you save the web page to home screen it will remove all cookie and session info.  You will need to login every time.  What’s worse is if you use Oauth in Grafana Safari will pop up new window for authentication but not return to the full screen “app” afterwards so your full screen “app” always logged out.
