### ISSUE TITLE
external panel links are not url escaped

### ISSUE THREAD

**Issue by cxcv** [grafana/grafana#12764]
Please include this information:
### What Grafana version are you using?
5.3-pre1
### What datasource are you using?
mysql
### What did you do?
using an external link from a table, there's no method to urlescape the table cell in the created url
### What was the expected result?
there should be a escape function
### What happened instead?
the data was not fully escaped, this breaks 3rd party applications receiving the data

**Comment by xlson** [comment]
Hi,

Could you explain your use case a further, perhaps with screenshots and examples? Am I correct in asuming that you are using the "Render value as link" functionality of the table panel?

What system are you integrating with and what browser are you using?

**Comment by cxcv** [comment]
Hello xlson,

yes, it's about the table view "render value as link":
![image](https://user-images.githubusercontent.com/234864/43461046-b70fff92-94d2-11e8-945e-16cd8920c509.png)

I'm linking to icingaweb2 and I'm using MySQL as a datasource. The relevant column is text containing special characters like the parenthesis in "FOO (BAR)".
The backend is parsing the URL and interprets parenthesis as delimiters, so the whole string needs to be fully escaped (as in escape(), not as in [encodeURI()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI), which leaves "A-Z a-z 0-9 ; , / ? : @ & = + $ - _ . ! ~ * ' ( ) #" unescaped.)


So, when I create a link without urlescape:
```
/monitoring/monitoring/list/hostgroups?hostgroup_name=service:${__cell_2}
```
the resulting URL in Chrome and in the webserver access log is:
```
/monitoring/monitoring/list/hostgroups?hostgroup_name=service:FOO%20(BAR)
```

The new formatting option "urlescape" escapes all special characters, so the new query looks like:
```
/monitoring/monitoring/list/hostgroups?hostgroup_name=service:${__cell_2:urlescape}
```
The resulting URL in Chrome and in the webserver access log is:
```
/monitoring/monitoring/list/hostgroups?hostgroup_name=service:FOO%20%28BAR%29
```

**Comment by cxcv** [comment]
Hi @all,

there's a PR that adresses this issue, but I get no feedback.
Am I missing anything?


Cheers
Benjamin
