### ISSUE TITLE
Table panel sort by column does not work as expected when column contain missing rows

### ISSUE THREAD

**Issue by davidohana** [grafana/grafana#12763]
Grafana 5.2.2
Datasource: ES 
Mac O/S

Retrieving Raw document from Elasticsearch data source into a table panel, then try to sort it by a numeric column.
If some of the docs does not contain a value for the field represented by this column (no such key in json), rows are not ordered correctly - blanks are interleaved between actual values (see attached image). 

<img width="120" alt="screen shot 2018-07-30 at 18 15 04" src="https://user-images.githubusercontent.com/27995472/43406403-cf70a130-9424-11e8-963b-bd8e57677c1a.png">

**Comment by marefr** [comment]
Please use the `Missing` option of metric and set to 0. Closing this for now. Please let me know if I misunderstood and I'll reopen.

**Comment by marefr** [comment]
Sorry was a bit fast there. If you use the query inspector what does the response look like for Offtopic count having none values - null?

**Comment by davidohana** [comment]
The "Offtopic count" field simply does not exist in the _source for those hits
BTW, I think this problem is in the table panel and not in the ES data source, because I could reproduce it also when using the simple JSON data source.
Also, where is the `Missing` option? could not find it anywhere ..
Thanks

**Comment by marefr** [comment]
Have you tried changing the column style to number?

**Comment by davidohana** [comment]
Yes, sorting is wrong regardless the type of the column

**Comment by marefr** [comment]
Sorry I thought that support for sorting null values was released like in 5.2.0. I see now that the fix #12362 will be included in next major release v5.3 (no release date yet).
