### ISSUE TITLE
Azure datasource with external auth still not working after 5.2.2

### ISSUE THREAD

**Issue by aenima-x** [grafana/grafana#12777]
### What Grafana version are you using?
5.2.2
### What datasource are you using?
Azure
### What OS are you running grafana on?
Ubuntu 14.04
### What did you do?
Use a dashboard that uses azure datasource
### What was the expected result?
It worked before 5.2
### What happened instead?
The dashboars fails, and continually ask for credentials
In the webserver I see that the request comes without user
NOTE: I'm using external auth
 
![image](https://user-images.githubusercontent.com/2791747/43462452-86032102-94ac-11e8-9ddb-a532619f6e0f.png)

**Comment by aenima-x** [comment]
Ok sorry, is my first issue.
I use web server auth, and in the acess_log for every 401 the log the request came without authentication (that is what a mean with no user in the log). That is why the 401.
Before 5.2 it didn't happend.
It only happends with the azure datasource

**Comment by aenima-x** [comment]
![image](https://user-images.githubusercontent.com/2791747/43479632-34ed0352-94d7-11e8-8288-a66b73cae19d.png)

**Comment by aenima-x** [comment]
Even there, after click en save & test, It ask for credentials again

**Comment by cloudenv** [comment]
@aenima-x Thats no need to ask anything. Just make a switch to DataDog. Works like a charm with Azure.

**Comment by marefr** [comment]
@aenima-x what version of azure monitor plugin are you using? What happens when you click on Save & Test? Could you please check chrome dev tools console and network tab for details?

Sounds similar to https://github.com/grafana/azure-monitor-datasource/issues/49

**Comment by aenima-x** [comment]
The last one (0.1.1)
When I click Save & Test, it says "Testing..." but after that the browser ask for credentials again.
In the console and network I see a 401 when it hits /grafana/api/datasource/........./resoursceGroups?api-version=2018-01-01
from angular.js.
When I look in the apache log for that request I see my user in the log, so the request is autenticathed.
I don't know why the 401.

Its not the same of the other issue, I have connectivity to azure. It was working OK before 5.2

**Comment by aenima-x** [comment]
UPDATE: In the 401 it says "AuthenticationFailedMissingToken"

**Comment by aenima-x** [comment]
I think is related to this: https://github.com/grafana/azure-monitor-datasource/issues/21
Seems like an azure related problem, don't know why it started with 5.2.
Forget it.

**Comment by marefr** [comment]
Thanks @aenima-x . Closing this for now. Please let us know if something changes and we'll consider reopen this.
