### ISSUE TITLE
Make timezone configurable when embedding panels/dashboards

### ISSUE THREAD

**Issue by randolph-straub** [grafana/grafana#12772]
For direct link rendered images it is possible to set a "**tz**" query parameter and provide an UTC offset 
See: #5670 and [Doc](http://docs.grafana.org/reference/sharing/) (_Share Panel->Rendered Image->Query Parameters_)

It would be great if we could get something comparable for embedded shared panels and dashboards. What we need is a possibility to parameterize the shared embedded panels/dashboards with an individual timezone or at least the UTC offset.

**Grafana Version:** 5.2.2
**Related To:** data visualization and sharing

**Comment by xlson** [comment]
@randolph-straub Embedded panels should use the browser time zone just like grafana itself. Is there a use case where that isn't enough?

**Comment by randolph-straub** [comment]
@xlson Thank you for your quick reply. Your right and I know that it is also possible to set UTC time at dashboard level. But that is not sufficient for our use case, so please let me explain our concrete use case in more detail.

In our case we have for example 2 embedded panels on a custom page (not delivered by Grafana server) and panel 1 should show the time in UTC+2 and panel 2 should show the time in UTC+8. So we need to tell the embedded chart somehow how to offset the shown time. On our custom page we could calculate the UTC offset for every timezone in the browser so setting a UTC offset would be sufficient for us.

Or a more concrete example would be, if you have metrics for Tokyo and NewYork in your database and want to show these metrics on a custom page by embedding the according panels where the shown time should match the timezone where the date came from. So in this case all Tokyo related panels should show the time in UTC+9 and all NewYork related panels should show the time in UTC-4.

Hope this makes it a bit more clear what we try to achieve.

Thank you for your time.

**Comment by xlson** [comment]
@randolph-straub Thanks for explaining your use case.

**Comment by zsq1314** [comment]
+1,  I need the ability to select UTC+X as a timezone. setting a UTC offset would be sufficient for us. Can you tell me the implementation plan for this feature?

**Comment by MaxMcGlinnPoole** [comment]
This is affecting our team right now, would really like this feature!

**Comment by vdwpsmt** [comment]
Another scenario where the selection of timezone should be controllable with an url parameter.
Suppose you have a common dashboard with a list of  resources spread around the world.  When clicking on 1 of these resources, you open a dashboard link, with the resourceId as a parameter/dashboardVariable.    In some cases it is important to reason in the local time where the resource resides.   In that case it would be convenient to add a second parameter (tz) which opens the dashboard in the timezone as requested.

**Comment by lafrech** [comment]
The OP may not be interested anymore, but I believe the use case is legit and this enhancement request is still relevant.
