### ISSUE TITLE
Option to limit/paginate/scroll results in Legend

### ISSUE THREAD

**Issue by tmonk42** [grafana/grafana#1277]
So when there's a lot of results, having the clickable table to sort by min/max etc is excellent!

What would make it even better is if I could configure the graph to only show the first X results in that table or scroll through the results while keeping the header row in place.

**Comment by mohierf** [comment]
+1

**Comment by Zeelot** [comment]
would love this! I want to limit the legend without limiting the graphs.  Having a scrollable area instead of pushing the graph down would also be great.

**Comment by Minnozz** [comment]
+1

**Comment by jgerschk** [comment]
+1

**Comment by mattttt** [comment]
We'd love this as well (closing Issue #2756 and consolidating here):

For panels with many series, especially those that benefit from the table legend, the ability to have a scrollable legend can keep dashboards tidy and condensed.

For example, this panel height is unnecessarily high to support the legend: 
![image](https://cloud.githubusercontent.com/assets/2886187/9918876/73810ac6-5c97-11e5-8260-97a3a97ce020.png)

To mitigate this, adding the ability to scroll within the legend could help immensely. This would be especially useful where the legend data does not need always be seen - but can be access easily. 

![image](https://cloud.githubusercontent.com/assets/2886187/9918962/ed4bfcc6-5c97-11e5-883a-e51a57367b69.png)

**Comment by digrich** [comment]
+1

**Comment by mtanda** [comment]
+1

**Comment by macbar** [comment]
+1

**Comment by shangeo** [comment]
We need this please +1 !

**Comment by gravaton** [comment]
This would be ideal and let this data be a ton more usable! +1

**Comment by f1yegor** [comment]
+1

**Comment by exbane** [comment]
I've noticed this has come back in 4.2 nightly release.. I don't see any options to limit the table size.. It list all objects without any type of scroll bar - this only happened after we upgraded to 4.2 beta. Thoughts?
