### ISSUE TITLE
Alerts fired but no webhook is sent

### ISSUE THREAD

**Issue by hichamuntitled** [grafana/grafana#12776]
### What Grafana version are you using?
5.2.0 and 5.2.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
I'm trying to monitor CPU usage of my docker swarm services. I've defined an alerts using the 'outside range condition' (I have also tried the other conditions)
### What was the expected result?
If the CPU usage is greater than 75% or less than 20%, then the webhook alert should be sent.
### What happened instead?
Alerts are fired, but the webhooks are sent only few times (3 of 12), instead when I use the 'send test' button in the notification chanel, the webhook is sent.
### If related to metric query / data viz:
the metric used :
 `avg by(container_label_com_docker_swarm_service_name) (irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~"SERVICE_TO_BE_MONITORED"}[5m]) * 100)`

and here is the alert configuration
![alert config](https://user-images.githubusercontent.com/13732188/43462034-5610818c-94d5-11e8-9d82-6a432594871c.PNG)

**Comment by cloudenv** [comment]
@hichamuntitled Dont use Grafana for alerting; Alerting is just as a mock-up with **no real function**. For proper visualising + real alerting I suggest using DataDog (its only $15/host/year so not much). Its far far better.

**Comment by torkelo** [comment]
> Alerts are fired, but the webhooks are sent only few times (3 of 12)

What do you base this on? Do you have an alert history with 12 state changes? Alert notifications are only sent when the alert rule changes state.

**Comment by hichamuntitled** [comment]
based on the 12 tests I ran, only 3 of them sent the webhook and It's random.
I guess it has something to do with #10912, the include image checkbox was checked by default, I unchecked it, and now it working. So, I'm closing this issue.
Thank you.
