### ISSUE TITLE
[Feature request] LINE notifier & notifications for state changes back to OK 

### ISSUE THREAD

**Issue by nutchalum** [grafana/grafana#12781]
It'd be nice to have such an alert when everything is back to normal after an alert was fired.
Just like other popular tools such as PRTG, Zabbix, etc.

**Comment by torkelo** [comment]
Grafana sends notifications when alert rule goes back to OK

**Comment by torkelo** [comment]
Could you describe more or am I miss understanding your feature request?

**Comment by nutchalum** [comment]
Hmm, that's weird

I have never received any notifications when alert rule goes back to green at all
I'm using LINE NOTIFY as an only notification channel, I'll try to reproduce it first then

Thank you

**Comment by nutchalum** [comment]
These pictures will clarify my problem @torkelo  

![line_p201881_133340](https://user-images.githubusercontent.com/22613696/43505048-d6297fe4-958f-11e8-982e-de631d5a1ee4.png)

You may notice that the alert was fired at 13:15 (1:15 PM) 
and went back to normal at 13:28 (1:28 PM) 
and then alert again 13:29 (1:29 PM)

![line_p201881_133512](https://user-images.githubusercontent.com/22613696/43505060-e10acbf2-958f-11e8-81ad-a19cf4648647.png)

However, I only got notifications when there is an alerts (it skipped when they went back to normal)

**Comment by torkelo** [comment]
What’s your options for the line notifier ? Maybe it filters out notifications?

**Comment by nutchalum** [comment]
What do you mean by options? If you mean notification settings, it just this simple

![line_p201881_140419](https://user-images.githubusercontent.com/22613696/43506312-eaa591fc-9593-11e8-9712-b61fae57a8c9.png)

I can't figure out where or what that filter it out

ps. My LINE Notify is a serverless (no callback server, I'm using developer token)

**Comment by shan52** [comment]
I am having problem adding line in Notification Channel. I create the token by going to Line developper -> Messaging API -> Issue a Channel access token. When testing the notification, I am getting the message "Failed to send alert notifications". Any idea?

**Comment by wbrowne** [comment]
This issue should be fixed with https://github.com/grafana/grafana/pull/27639
