### ISSUE TITLE
session/mysql invalid connection

### ISSUE THREAD

**Issue by andytsnowden** [grafana/grafana#12789]
With Grafana 5.2.1 and 5.2.2 we are seeing constant issues with mysql-backed sessions being terminated with errors.  This is causing a lot of user frustration since they get errors when trying to save changes to dashboards only to find their session has ended without explanation.

In looking at the debug logs I see a few errors when a user attempts to save a dashboard.
`Aug 01 16:32:58 es-master03 grafana-server[33544]: [mysql] 2018/08/01 16:32:58 packets.go:36: unexpected EOF`
`Aug 01 16:32:58 es-master03 grafana-server[33544]: [mysql] 2018/08/01 16:32:58 packets.go:36: unexpected EOF`
`Aug 01 16:32:58 es-master03 grafana-server[33544]: 2018/08/01 16:32:58 session/mysql: error checking if session exists: invalid connection`
`Aug 01 16:32:58 es-master03 grafana-server[33544]: [mysql] 2018/08/01 16:32:58 connection.go:372: invalid connection`
`Aug 01 16:32:58 es-master03 grafana-server[33544]: [mysql] 2018/08/01 16:32:58 connection.go:372: invalid connection`

Our back-end mysql is a 3-node active-active Percona Xtradb cluster with HAProxy sitting in front.  We have several other applications talking to this cluster without any sort of timeout/connectivity issues.  It appears Grafana is not validating the DB connection is alive before attempting to use it.

Other Info:
What Grafana version are you using? 5.2.2
What datasource are you using? Elasticsearch
What OS are you running grafana on? CentOS 7.5.1804
What did you do? see above, attempting to use MySQL for session storage
What was the expected result? Sessions don't randomly fail and users lose work
What happened instead? Within a few minutes of login the session fails

**Comment by marefr** [comment]
What Grafana version did you use before 5.2.1 and 5.2.2? 

Make sure that you've configured conn_max_lifetime correctly: http://docs.grafana.org/installation/configuration/#conn-max-lifetime

Please include session and mysql configuration in Grafana.

**Comment by andytsnowden** [comment]
@marefr We have been using 4.5.1 on the old environment.  

Config:
[database]
type = mysql
host = 1.1.1.1:3306
name = grafana
user = username
password = password

;url =
;ssl_mode = disable
;path = grafana.db
max_idle_conn = 10
;max_open_conn =
;conn_max_lifetime = 14400
log_queries =

[session]
provider = mysql
provider_config = user:pass@tcp(1.1.1.1:3306)/grafana

cookie_name = grafana_ny3_sess
cookie_secure = false
session_life_time = 86400


SQL timeout:
mysql> SHOW SESSION VARIABLES LIKE "%wait_timeout%";
+-------------------------------------+----------+
| Variable_name                       | Value    |
+-------------------------------------+----------+
| wait_timeout                        | 28800    |


mysql> SHOW GLOBAL VARIABLES LIKE "%wait_timeout%";
+-------------------------------------+----------+
| Variable_name                       | Value    |
+-------------------------------------+----------+
| wait_timeout                        | 28800    |


We also have HAproxy in between Grafana and MySQL however it's client and server timeouts are set to 50,000

defaults
   timeout connect 5000
   timeout client 50000
   timeout server 50000

**Comment by marefr** [comment]
Seems like you have default [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) configured. 

We did a fix in Grafana v5.3 and that's where the conn_max_lifetime was introduced. Please read the comment https://github.com/grafana/grafana/issues/11155#issuecomment-372830692 for details of problem and the fix we implemented.

Really hard for us to investigate/reproduce using mysql and haproxy. Have no idea if setting timeouts in haproxy affects mysql wait_time. But the problem explained in issue comment seems exactly like this problem.

Sorry, but I would suggest you try and change the conn_max_lifetime and see if you get any difference. I'll try and ask my colleagues and see if they have any idea.

**Comment by andytsnowden** [comment]
I'll take any help I can get 👍 

I reconfigured one of the Grafana instances to talk directly to MySQL and the issue persisted so HAproxy seems to be ok.  For now I've just installed a single redis node and have it handling sessions until 5.3 is out or a workaround is identified.

I'll try changing the conn_max_lifetime settings and see if that has any effect.

**Comment by marefr** [comment]
@andytsnowden have you been able to verify if conn_max_lifetime setting fixed your problem?

**Comment by marefr** [comment]
Closing this due to lack of response. WIll consider reopen on further response.
