### ISSUE TITLE
[Feat] Configure to drop authorization header when using datasource server access mode

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#12797]
Given you're using some authentication mechanism for Grafana which sets the authorization header. If you have a datasource that can't handle this authorization header and/or the datasource are handling authentication in different way there's need for being able to drop the authorization header before forwarding to datasource using Grafan'a server/proxy access mode.

Proposed solution: New setting in datasource http settings.

**Comment by bobrik** [comment]
Does that mean that Grafana silently leaks authorization header to all datasources, e.g. if I use a public prometheus datasource, will it know my authorization header and be able to access my Grafana?

**Comment by marefr** [comment]
@bobrik This is only when using Grafana's HTTP API to make datasource proxy calls from the outside using an Authorization header (to authenticate against Grafana's HTTP API) and the datasource in question don't have any basic auth specified.

One other way would be if you had Grafana running behind a reverse proxy with some special authentication that populate a Authorization header.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
