### ISSUE TITLE
Slack notification channel ignore external_image_storage settings, always upload to slack.

### ISSUE THREAD

**Issue by isclever** [grafana/grafana#12792]
Please include this information:
### What Grafana version are you using?
grafana/grafana:5.2.1
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Docker
### What did you do?
Send alerts with image uploaded to s3 to rocket.chat via slack webhook
### What was the expected result?
Alerts send to channel with image uploaded to s3.
### What happened instead?
Alerts ARE sent to rocket.chat channel but grafana attempts to upload image to slack ignoring external_image_storage setting

Configuration override:
```
t=2018-08-01T19:06:22+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=s3"
t=2018-08-01T19:06:22+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET_URL=https://xxx.s3-ca-central-1.amazonaws.com/"
t=2018-08-01T19:06:22+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_S3_ACCESS_KEY=xxx"
t=2018-08-01T19:06:22+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_S3_SECRET_KEY=*********"
```

Logging when sending a test alert to the slack webhook with images:
```
t=2018-08-01T19:10:01+0000 lvl=dbug msg="Sending webhook" logger=notifications url=http://myrocketchat/${tokenurl} http method=
t=2018-08-01T19:10:01+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
t=2018-08-01T19:10:01+0000 lvl=dbug msg="Sending webhook" logger=notifications url=https://slack.com/api/files.upload http method=POST
```

**Comment by xlson** [comment]
It sounds like you have provided a token (for file upload) in the slack notification channel configuration. If a token is provided the Slack notification channel will use it to do an upload.

Can you please check if that is the case?

**Comment by isclever** [comment]
Removing the token fixes the issue, the URL is enough to post to Rocket Chat, thank you for pointing out my error.
