### ISSUE TITLE
Support for TeraBytes and PetaBytes units

### ISSUE THREAD

**Issue by naveedd** [grafana/grafana#12793]
Grafana 5
datasource MySQL?
OS  Linux

For HPC computing we have the data in terabytes and PetaBytes  for data Max unit we see is Gigabytes, wondering how can we add TB and Petabyte to the list.

**Comment by marefr** [comment]
You can send in a pull request. 

You'll need to add terabyte and petabyte [here](https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.ts#L913-L931) and [here](https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.ts#L454-L466).

Here's an example pull request that you may have a look at: #11212
