### ISSUE TITLE
Is there any lite libary bulit with JavaScript to show powerful graphics

### ISSUE THREAD

**Issue by aleen42** [grafana/grafana#12794]
As we all know that grafana is well supported for graphically showing data based on ElasticSearch, and I just want to ask an issue whether there is a lite edition of library built with JavaScript like any graphic components, to show such powerful graphics. I have rencently wanted to used Grafana to combine with a company's project.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
