### ISSUE TITLE
when I login and get error [runtime error: index out of range]

### ISSUE THREAD

**Issue by HaoChou** [grafana/grafana#12804]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

it is running well before.but tody comes out somethingwrong when i want to login grafana.
i clear my local cookie and restart the grafana-server 。but i can not login.
I was successfully login with admin/ammin before.but now i can't.
this is the response from server:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>Grafana - Error</title>
    <link href='/public/css/fonts.min.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/public/css/grafana.dark.min.af13213c.css">
    <link rel="icon" type="image/png" href="/public/img/fav32.png">
    <base href="/" />
  </head>
  <body>
    <div class="page-container">
      <div class="page-header">
        <h1>Server side error :(</h1>
      </div>
      <h4>runtime error: index out of range</h4>
      
    </div>
  </body>
</html>

and some request params:

Request URL: http://172.18.64.95:3000/login
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 172.18.64.95:3000
Referrer Policy: no-referrer-when-downgrade
Content-Length: 691
Content-Type: text/html; charset=UTF-8
Date: Fri, 03 Aug 2018 07:21:39 GMT
Set-Cookie: grafana_user=admin; Path=/; Max-Age=604800
Set-Cookie: grafana_remember=53efeba99de77fbe5247c2e9a831bb35898ee3d5451f290ee05a809f4deb959ec1; Path=/; Max-Age=604800
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Content-Length: 46
Content-Type: application/json;charset=UTF-8
Cookie: redirect_to=%252F; grafana_user=admin; grafana_remember=150452e140035835e2f719e99adcac1228e2172db3d4853498eac0d6393b932ff6
Host: 172.18.64.95:3000
Origin: http://172.18.64.95:3000
Referer: http://172.18.64.95:3000/login
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
{user: "admin", email: "", password: "admin"}
email
:
""
password
:
"admin"
user
:
"admin"

thank you!

**Comment by marefr** [comment]
Have you upgraded recently or not? Please check your grafana server log and include related information from that here.

**Comment by HaoChou** [comment]
I have add the pie chart plugin  a week ago ，and the pie chart dose not work。

this is the content /var/log/grafana/grafana.log.2018-08-03.001

t=2018-07-31T11:39:02+0800 lvl=info msg="Shutdown started" logger=server code=0 reason="system signal: terminated"
t=2018-07-31T11:39:02+0800 lvl=info msg="stopped http server" logger=http.server
t=2018-07-31T11:39:02+0800 lvl=info msg="Starting Grafana" logger=main version=4.4.3 commit=54c79c5 compiled=2017-08-07T16:50:18+0800
t=2018-07-31T11:39:02+0800 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-07-31T11:39:02+0800 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-07-31T11:39:02+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-07-31T11:39:02+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-07-31T11:39:02+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-07-31T11:39:02+0800 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-07-31T11:39:02+0800 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-07-31T11:39:02+0800 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-07-31T11:39:02+0800 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-07-31T11:39:02+0800 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-07-31T11:39:02+0800 lvl=info msg="Starting DB migration" logger=migrator
t=2018-07-31T11:39:02+0800 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-07-31T11:39:02+0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-07-31T11:39:02+0800 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-07-31T11:39:02+0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-07-31T11:39:02+0800 lvl=info msg="Starting plugin search" logger=plugins
t=2018-07-31T11:39:02+0800 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2018-07-31T11:39:02+0800 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-07-31T11:39:02+0800 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-07-31T11:39:02+0800 lvl=info msg="Initializing Stream Manager"
t=2018-07-31T11:39:02+0800 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2018-07-31T11:43:21+0800 lvl=info msg="Shutdown started" logger=server code=0 reason="system signal: terminated"
t=2018-07-31T11:43:21+0800 lvl=info msg="stopped http server" logger=http.server
t=2018-07-31T11:43:21+0800 lvl=info msg="Starting Grafana" logger=main version=4.4.3 commit=54c79c5 compiled=2017-08-07T16:50:18+0800
t=2018-07-31T11:43:21+0800 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-07-31T11:43:21+0800 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-07-31T11:43:21+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-07-31T11:43:21+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-07-31T11:43:21+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-07-31T11:43:21+0800 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-07-31T11:43:21+0800 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-07-31T11:43:21+0800 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-07-31T11:43:21+0800 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2018-07-31T11:43:21+0800 lvl=info msg="Starting DB migration" logger=migrator
t=2018-07-31T11:43:21+0800 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-07-31T11:43:21+0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-07-31T11:43:21+0800 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-07-31T11:43:21+0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-07-31T11:43:21+0800 lvl=info msg="Starting plugin search" logger=plugins
t=2018-07-31T11:43:21+0800 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing Stream Manager"
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
[root@ip-172-18-64-95 grafana]# tail -f grafana.log.2018-08-03.001 
t=2018-07-31T11:43:21+0800 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2018-07-31T11:43:21+0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2018-07-31T11:43:21+0800 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2018-07-31T11:43:21+0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2018-07-31T11:43:21+0800 lvl=info msg="Starting plugin search" logger=plugins
t=2018-07-31T11:43:21+0800 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing Stream Manager"
t=2018-07-31T11:43:21+0800 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=

**Comment by marefr** [comment]
When you login and get the error doesn't grafana server log include any related information to that? The latest pie chart version is built for latest Grafana version.

**Comment by HaoChou** [comment]
there is nothing writing to the log file when I do login。
and if I am trying to reInstall a latest Garafana，how could I backup the dashboard metadata（json） without login？

**Comment by marefr** [comment]
If you're using sqlite as database you can just copy and paste the data/grafana.db to backup. Otherwise mysql or postgres backup according to their documentation.

**Comment by marefr** [comment]
SInce you receive a 500 error you should be able too see error details in the grafana server log when you try to login.

**Comment by HaoChou** [comment]
ok。thank you very much～mybe try to reinstall is the fast way～

**Comment by HaoChou** [comment]
I have found the reason which makes the 500 error and without any log.
 because  No space left on device！！ The service is ok after clear disk。
