### ISSUE TITLE
Some settings in grafana.ini are not possible to configure using environment variables

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#12800]
Some settings are missing from `conf/defaults.ini` and due to this, it's not possible to override them using environment variables.

Known problems:
- auth.generic_oauth.tls_client_ca (and several other oauth settings)

The problem was brought up here: https://github.com/grafana/grafana-docker/issues/182

**Comment by marefr** [comment]
Is it because their not part of default.ini?

**Comment by xlson** [comment]
@marefr exactly.
