### ISSUE TITLE
[Feat] Client certificate for LDAP connections

### ISSUE THREAD

**Issue by nyxi** [grafana/grafana#12805]
We are running a public endpoint to our on-prem LDAP servers which requires clients to present a valid SSL client certificate when connecting.

Currently Grafana does not let you configure a client certificate to be used when connecting to LDAP servers.

From my limited understanding we need _something like_ the below options in ``ldap.toml``:

```
ssl_client_cert /path/to/client/cert
ssl_client_key /path/to/client/key
```

Which when set, will call the [LoadX509KeyPair](https://godoc.org/crypto/tls#LoadX509KeyPair) function from the [tls](https://godoc.org/crypto/tls) package and append the resulting [Certificate](https://godoc.org/crypto/tls#Certificate) object to the ``Certificates`` field of the [tls.Config](https://godoc.org/crypto/tls#Config) object before executing ``ldap.DialTLS`` in [ldap.go](https://github.com/grafana/grafana/blob/master/pkg/login/ldap.go).

**Comment by marefr** [comment]
Fixed by #12807
