### ISSUE TITLE
[Feat] Local browser time should not be used for absolute dates when timezone is UTC

### ISSUE THREAD

**Issue by balakrishnabk** [grafana/grafana#12817]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.2.1 (commit: 2040f61) version
### What datasource are you using?
influxdb
### What OS are you running grafana on?
ubuntu
### What did you do?
select absolute dates for querying
### What was the expected result?
the timeline should be same and use UTC instead of local browser
### What happened instead?
the calculations are based on browser time when absolute dates are selected
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Reference with screenshots.
https://community.grafana.com/t/grafana-influxdb-difference-resultset-in-previous-week-vs-timerange-filter/9054

**Comment by marefr** [comment]
Changing this to feature instead of bug. Seems this has worked this way since at least Grafana v4.1.0 and I haven't found any other issue related to this.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
