### ISSUE TITLE
Grafana should have a mailing list / google group.

### ISSUE THREAD

**Issue by burtonator** [grafana/grafana#1281]
I'd like to humbly suggest that Grafana should have a mailing list.

Issues and bug tracking are great, but the lack of a mailing list prevents open discussion.

For example, it would be nice to discuss general problems or bugs and collaborate with other Grafana users.  These might be *before* they are issues and when the user doesn't understand what's happening.

It would be a place where people can discuss plugins, collaborate on code together, etc.

Without a a mailing list it's hard for an Open Source project to build community and that's where the major strength of OSS comes from...

**Comment by otisg** [comment]
+1 for ML

**Comment by torkelo** [comment]
There is now a mailing list at: https://groups.io/org/groupsio/grafana , spread the word! :) 

Also spent 2 hours building a community page on grafana.org, http://grafana.org/community/

**Comment by hdost** [comment]
There is also now a developer mailing list https://groups.google.com/forum/#!forum/grafana-developers
