### ISSUE TITLE
Dashboards display templates

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#12818]
Hi,

I have several dashboards that I display on different radiators which have different sizes (especially one that is a combined 2x2 TV screens).

As each radiators as it's own size I thought it would be nice to be able to apply different templates of panel sizes (height and width) depending on the screen you are displaying the Dashboard on to make the most of the display space available on it.

The  way I see it it would be like a variable where you choose a template and the dashboard each components would resize depending on the template you chose.

Each templates would be a set of height & width (or min width for panel with repeat) that could be separately linked to each panels.

Regards.

**Comment by marefr** [comment]
Wouldn't #12768 solve your problem?

**Comment by marefr** [comment]
Then I would say it's very similar to #10916. Do you agree?

**Comment by sylr** [comment]
No really no let me explain a bit more my idea.

I though about defining rules like `Display/Series Override`, e.g. :

```json
{
    "templates": [
        {
            "name": "Big Jumbotron",
            "rules": [
                {
                    "alias": "/CPU/",
                    "height": "500px",
                    "width": "2000px"
                },
                {
                    "alias": "/Mem/",
                    "height": "250px",
                    "min_width": "8"
                }
            ]
        },
        {
            "name": "19\" screen",
            "rules": [
                {
                    "alias": "/CPU/",
                    "height": "250px",
                    "width": "500px"
                },
                {
                    "alias": "/Mem/",
                    "height": "250px",
                    "min_width": "4"
                }
            ]
        }
    ]
}
```

**Comment by marefr** [comment]
Hmm this sounds not like the same direction as we're headed at. We want to minimize the amount of configuration options making Grafana easier to use and develop from a usability and maintenance perspective. Grafana should be clever enough to re-scale a dashboard automatically and #12768 is a good starting point for that so I'll close this. 

We always consider reopening issues if many people upvote.
