### ISSUE TITLE
[Feat] Allow disconnected line graphs when data contains gaps

### ISSUE THREAD

**Issue by andig** [grafana/grafana#12811]
Some data sources like simple-json-datasource are not (always) able to produce one measurement per time period. For those missing data will lead to ugly graphs:

<img width="396" alt="screen shot 2018-08-03 at 18 16 51" src="https://user-images.githubusercontent.com/184815/43653790-6a88f416-9749-11e8-8968-3e5fd0343d70.png">

In addition to the existing Draw Options a `Gap: duration`option should be added: Treat data gaps bigger than `duration` as missing and draw gap. 

Flot supports this using the gaps plugin: http://joeloughton.com/blog/web-applications/flot-plugins-x-gap-threshold/

**Comment by marefr** [comment]
This is something each datasource should implement and I suggest you open a feature request for the [simple-json datasource](https://github.com/grafana/simple-json-datasource).

**Comment by andig** [comment]
@marefr thanks for the reply. As I understood the datasource API I have the feeling that the datasource (any datasource) would need to invent additional timestamps with "null" values in order to implement gaps? While this may be simple for TSDB sources it might be much harder to impossible for SQL datasources? For this assumption- really push down to plugin responsibility?

**Comment by marefr** [comment]
We actually have support for fill in our sql datasources using the $__timeGroup macro where you could fill with null or floating point. What sql datasource are you using?

**Comment by andig** [comment]
> What sql datasource are you using?

simple-json

> This is something each datasource should implement 

Seems this got me confused. So the sql datasources support this via the `$__timeGroup` macro, but simple-json doesn't?

From looking at the code, both simple-json as well as sql (e.g. mssql) seem to use `this.backendSrv.datasourceRequest`. In case of JSON it goes to the user-definable json endpoint, in case of sql it goes to `/api/tsdb/query`.

Looking at the `__timeGroup` implementation for [MySQL](https://github.com/grafana/grafana/blob/5cca47865601b1319cfb81acc83b8a1493d4898b/pkg/tsdb/mysql/macros.go#L107) it is using `GROUP_BY`. AFAIK this will still create gaps without creating new data points. E.g. if you have a metric with data for 1/1 and 12/1 and query a year grouped by day its still only 2 data points in that metric?

I don't think that `__timeGroup` can fix the gaps feature requested, even for SQL sources?

**Comment by marefr** [comment]
It's implemented specifically for the sql datasources (postgres, mysql and mssql) in Grafana backend, see code [here](https://github.com/grafana/grafana/blob/5cca47865601b1319cfb81acc83b8a1493d4898b/pkg/tsdb/mysql/macros.go#L95), [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/sql_engine.go#L274) and [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/sql_engine.go#L347).
