### ISSUE TITLE
alert test rule return thousand of points but source only have few points 

### ISSUE THREAD

**Issue by hiliuxg** [grafana/grafana#12825]
Hi:

When i try to set a alert like the Screenshot below , i found that the logs return thousand of points  , but 
 there are only 5 points in my elasticsearch  datasource over 5 minute .  It will leads to 0 forever when use min function and leads to errror result when use avg function . What caused it? Something I can do to resovle it ?

Regards. 

![1](https://user-images.githubusercontent.com/39675622/43730499-1ac609b8-99de-11e8-86b9-eae3f2a1ada2.png)
![tim 20180807004906](https://user-images.githubusercontent.com/39675622/43730509-1fcf40dc-99de-11e8-94a9-c7411be24018.png)

### What Grafana version are you using?
v5.2.0-beta3
### What datasource are you using?
elasticsearch
### What OS are you running grafana on?
centos 6

**Comment by torkelo** [comment]
What does your query look like? specifically the date histogram options?

**Comment by hiliuxg** [comment]
Found it And solve it !  Super thanks.  When use data histogram  , the inteval configuration item shoud be set to 1m because my data is written for 1m too.  Grafana is the one of best opensource project i have seen before,wishing grafana better and better .
