### ISSUE TITLE
Image rendering fails if it takes more than 2-3 seconds

### ISSUE THREAD

**Issue by giner** [grafana/grafana#12828]
### What Grafana version are you using?
5.2.2

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Linux

### What did you do?
Trying to get rendered graph image for long period

### What was the expected result?
Get image rendered

### What happened instead?
Rendering fails in a 2-3 seconds

> Grafana / Server Error
> Sadly something went wrong
> Rendering failed.
> Check the Grafana server logs for the detailed error message.

### If related to metric query / data viz:
```
t=2018-08-07T01:09:12+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname= method=GET path=/api/datasources/proxy/1/query status=200 remote_addr=127.0.0.1 time_ms=559 size=382791 referer="http://localhost:8080/d-solo/000000074/test?refresh=1m&panelId=4&orgId=1&width=1000&height=500&from=now-30d&to=now&timeout=100000&render=1"
t=2018-08-07T01:09:13+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
t=2018-08-07T01:09:13+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=rpaas error="signal: killed"
```

**Comment by giner** [comment]
I think I know what the problem is. Renderer requires quite a lot of memory for processing when InfluxDB returns a lot of data points. If available memory is not enough then renderer crashes. Can error message be improved so that it is clear what to do when render fails?

**Comment by marefr** [comment]
Have you tried increasing the timeout value? http://docs.grafana.org/reference/sharing/#direct-link-rendered-image

**Comment by giner** [comment]
@marefr, I set timeout to 10000. This didn't help. Increasing memory for the container running Grafana helps though.

**Comment by torkelo** [comment]
yes, phantomjs rendering needs a container with more ram (500mb is usually enough)
