### ISSUE TITLE
[ux] Time series metric coloring broken

### ISSUE THREAD

**Issue by andig** [grafana/grafana#12827]
Upon refreshing the data (simple-json-datasource), timeseries metric change their color from time to time which is highly confusing. The two screenshots below are after refreshing data (*not* after page reload):

<img width="1152" alt="screen shot 2018-08-06 at 21 03 17" src="https://user-images.githubusercontent.com/184815/43739658-1b9b0ce0-99c9-11e8-9fb8-cc2f2d3957fd.png">
<img width="1152" alt="screen shot 2018-08-06 at 21 03 14" src="https://user-images.githubusercontent.com/184815/43739660-1bb63114-99c9-11e8-9231-d5eb9e948acb.png">

This happens both in single panel as well as when to full page is refreshed.

This is the panel `json`: https://gist.github.com/andig/396cd63ce0e2df19da4168ba5030534e. 

Looking the the json, especially the `aliasColors`, my feeling is that this might be connected to https://github.com/grafana/simple-json-datasource/issues/101. Should the json store the metric/target `text` or `value`?

Grafana is Grafana v5.2.1 (2040f61)

**Comment by marefr** [comment]
Please use the query inspector to troubleshoot the response coming back. Verify that the responses are coming back in same order over and over again. It works here as expected https://play.grafana.org/d/9gn3p55ik/graph-series-colors?orgId=1. I doubt this is a Grafana issue so will close this for now. 

Maybe simplejson problem?

**Comment by andig** [comment]
@marefr I really appreciate your quick responses :) I still feel that the current behaviour is a bit unexpected.

The order of the response is currently not guaranteed in my implementation (which I can change). However, the `timeserie` response esplicitly mentions which metric it applies to via the `target` attribute.

Shouldn't this be used for matching instead of the implicit rule of 'query target order must match response target order'?

**Comment by marefr** [comment]
Simple json datasource doesn't do any transformation of the data returned from implementation which means currently you'll need to make sure the order of response is consistent. This may be a feature request to add to simple json datasource.

**Comment by andig** [comment]
Looking at the code simplejson just seems to expose the internal backend interface. Meaning apparently the backend already accepts arbitrary responses instead of mapping value/text?

I'd like to contribute but I'm totally unsure where any transformation would need to go. As the data is retrieved by the backend- wouldn't that need to handle transformation before the frontend is updated for drawing?  

Any pointers to matching source lines would be helpful to get started.

**Comment by torkelo** [comment]
This has nothing to do about matching text/value but series order, I think your api is returning series in non deterministic order? If not that I am not sure
