### ISSUE TITLE
The right table of a panel moves left when scrolling

### ISSUE THREAD

**Issue by lcgogo** [grafana/grafana#12829]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.2.2
### What datasource are you using?
promethus
### What OS are you running grafana on?
ubuntu 16
### What did you do?
Add a panel of Graph with a lot of lines and choose Legend Options with As Table & To the right.
When scrolling the table in panel, the table moves to left.
### What was the expected result?
The table should scroll by my mouse.
### What happened instead?
It moves to left in the panel
### If related to metric query / data viz:
Not think so.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
`<div class="graph-legend-scroll baron__scroller" style="overflow-y: scroll; box-sizing: border-box; margin: 0px; border: 0px none; padding-right: 16px; width: 978px; min-width: 978px; max-width: 978px;">`
I see the width by px is increasing when I scroll.

<img width="764" alt="2018-08-06 5 36 38" src="https://user-images.githubusercontent.com/8175573/43756440-4c1695dc-9a47-11e8-999f-99013222d6bd.png">

**Comment by torkelo** [comment]
thanks for reporting this, we already have an issue for it  (https://github.com/grafana/grafana/issues/12726), it's a bit tricky, we are still figuring out how to solve it.

**Comment by marefr** [comment]
@lcgogo what browser and version are using?

**Comment by lcgogo** [comment]
@marefr I use firefox 61.0.1(64 bit)
