### ISSUE TITLE
[Feat] Protect against brute force based on IP

### ISSUE THREAD

**Issue by jeandet** [grafana/grafana#12836]
As discussed in #7616 current protection works against intrusion but may lead to unattended account blocking. A malicious person may use the current implementation to prevent users from login.

A solution to solve this issue would be to block users per IP. Like this any account would be locked for attacking IP but not for normal users.

**Comment by marefr** [comment]
FYI this will prevent account blocking, but instead an attacker could use different IP addresses and by that circumvent the protection of brute force logins.

There's no perfect way of protecting against these problem besides using external auth and/or implementing two-factor authentication (2FA) in Grafana. I don't see us implementing two-factor authentication in Grafana since you can use oauth with external party and most of them have 2FA support.

**Comment by jeandet** [comment]
@marefr, Grafana gets the public IP of the attacker? If so, his ability to change his IP is really limited.
So yes, this would allow an attacker to have few more chances to brute force the server from 5 to 5*(Number of IPs he can get).

**Comment by josemrs** [comment]
As a workaround it could be possible to use fail2ban, it works great protecting against brute force login attacks.

The only requirement would be to get the IP address in the login error messages.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
