### ISSUE TITLE
The data source is elasticsearch time variable cannot be used

### ISSUE THREAD

**Issue by shandowsoftware** [grafana/grafana#12837]
![image](https://user-images.githubusercontent.com/4735178/43815794-f456810a-9b03-11e8-9f1c-4c77a04f272c.png)

The pic cannot be overwritten with time variables ?

I want to configure the chart of yesterday today. example：

![image](https://user-images.githubusercontent.com/4735178/43815863-5e7d726e-9b04-11e8-93a2-3fc31bb10aab.png)

**Comment by torkelo** [comment]
Elasticsearch query api does not support time shifting (that I know of)

**Comment by marefr** [comment]
I would say this is a duplicate of #12653
