### ISSUE TITLE
[ux] Table panel needs be able to modify column style ordering

### ISSUE THREAD

**Issue by andig** [grafana/grafana#12830]
On Grafana v5.2.1 (2040f61) when working with table panel and datasources with large number of metrics, it is not easily possible to change the order of column styles. 

This is necessary since styling/hiding should be mixed. For example, I want to style all columns named `/time/i` as time, but want to hide all columns like `/Time$/` this doesn't seem to be possible since

1. After matching the /time/i rule further column rules don't seem to get processed.
2. I cannot move the `/Time$/ rule up to take higher precedence.

The ability to reorder the column definitions (outside of fiddling with the dashboard json) should help.

<img width="1123" alt="screen shot 2018-08-07 at 11 02 39" src="https://user-images.githubusercontent.com/184815/43767274-f6e6d00c-9a34-11e8-9242-9286a203a513.png">

**Comment by torkelo** [comment]
if you can't change the order in which you select columns your query you have to wait for this feature request to be implemented https://github.com/grafana/grafana/issues/5082

**Comment by cfrelet** [comment]
Is it implemented?

**Comment by torkelo** [comment]
Yes, using organize fields transform
