### ISSUE TITLE
An error occurred when time between 0h and 8h in early morning using daily pattern setting for elastic datasource 

### ISSUE THREAD

**Issue by hiliuxg** [grafana/grafana#12832]
Hi:

I am in china and my timezone is 8h offset from UTC. I found that grafana can not read new day's index when time between 0h and 8h in early morning . For example,  At 2018-07-30 00:01:30 in my timezone, i chose the last 5 minutes. It is reasonable to say that grafana shoud read 2 indexes. Yesterday's fxbd_pm_keyword_yellowing_count-20180729 index and today's fxbd_pm_keyword_yellowing_count-20180730 index ,but grafana only reads yesterday's index. Then after 8 hours, it returned to normal . I guess it is because the grafana server using utc time which causes this reason or there are some place i do not set correctly ? 

setting for my elastic datasource :

![_20180807194339](https://user-images.githubusercontent.com/39675622/43774062-7478a3de-9a7a-11e8-9df4-987d634773a0.png)

query inspector for my dashboad :

![_20180807194320](https://user-images.githubusercontent.com/39675622/43774053-68b58490-9a7a-11e8-93b1-2d94d968ba06.png)

timezone setting in dashboad setting general item . No matter what item do i setting,it does not work. 

![_20180807194445](https://user-images.githubusercontent.com/39675622/43774235-0e2286d0-9a7b-11e8-92b6-72164c86f703.png)

### What Grafana version are you using?
grafana-5.2.0-beta3
### What datasource are you using?
elasticsearch
### What OS are you running grafana on?
centos 6

**Comment by marefr** [comment]
Your elasticsearch and Grafana instances should use UTC timezone. I would say that this is not that's going to be implemented until #558 is considered.

**Comment by hiliuxg** [comment]
thanks for the reply
