### ISSUE TITLE
LDAP User Attributes are empty

### ISSUE THREAD

**Issue by DanhcS** [grafana/grafana#12840]
Hey,

after successfully logged in in grafana, the user attributes in the User Settings are empty.
Only if i change the values to the uid, the values are shown as the uid. But that makes no sense in case of the email to be the username.

The ldap.toml looks like following:

[[servers]]
host = "my-ldap-server.com“
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false

search_filter = "(uid=%s)"

search_base_dns = ["ou=people,dc=my-ldap-server,dc=com“]

[servers.attributes]
 name = "givenName"
 surname = "sn"
 username = "cn"
 member_of = "cn"
 email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=admins,dc=grafana,dc=org"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=users,dc=grafana,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

What am I doing wrong? The server attributes are spelled correctly.

**Comment by marefr** [comment]
What Grafana version?

Not sure I understand what seems to be the problem. Maybe you could include screenshot that highlights the problem? Have you tried enabled debug logging for ldap and restarted grafana, signing in and then checking grafana server log?

You can enable ldap debug by configure the following in grafana.ini:

```
[log]
filters = ldap:debug
```

Please refer to [documentation](http://docs.grafana.org/installation/ldap/#ldap-authentication) for further details.

Regarding questions, please ask those on our [community site](https://community.grafana.com/) in the future. Github are mainly for feature requests and bug reports.

**Comment by Danilo-Schiller** [comment]
The grafana version is 5.1.1

If i want to enable the ldap debug and want to restart grafana, following error is shown:

Restarting grafana-server (via systemctl):  Job for grafana-server.service failed because the control process exited with error code. See "systemctl status grafana-server.service" and "journalctl -xe" for details.

systemctl shows following message:
Aug 08 13:38:46 grafana systemd[1]: grafana-server.service: main process exited, code=exited, status=1/FAILURE
Aug 08 13:38:46 grafana systemd[1]: Failed to start Grafana instance.
Aug 08 13:38:46 grafana systemd[1]: Unit grafana-server.service entered failed state.
Aug 08 13:38:46 grafana systemd[1]: grafana-server.service failed.
Aug 08 13:38:46 grafana systemd[1]: grafana-server.service holdoff time over, scheduling restart.
Aug 08 13:38:46 grafana systemd[1]: start request repeated too quickly for grafana-server.service
Aug 08 13:38:46 grafana systemd[1]: Failed to start Grafana instance.
Aug 08 13:38:46 grafana systemd[1]: Unit grafana-server.service entered failed state.
Aug 08 13:38:46 grafana systemd[1]: grafana-server.service failed.

**Comment by marefr** [comment]
Are you running Grafana using docker or what platform?

**Comment by Danilo-Schiller** [comment]
Using a RPM-based server.

**Comment by marefr** [comment]
Check grafana server log. Are you using sudo?

Have you tried `sudo service grafana-server restart`?

**Comment by Danilo-Schiller** [comment]
Yes, all Commands are done as sudo.

The log shows following message:

t=2018-08-08T13:49:29+0200 lvl=crit msg="Failed to load ldap config file" logger=ldap error="Near line 3 (last key parsed 'log.filters'): expected value but found \"ldap\" instead"

**Comment by marefr** [comment]
> t=2018-08-08T13:49:29+0200 lvl=crit msg="Failed to load ldap config file" logger=ldap error="Near line 3 (last key parsed 'log.filters'): expected value but found "ldap" instead"

You did incorrectly add the debug logging to ldap config file instead of grafana.ini config file.

I think your problem is that you have no group_search_filter defined since you used `member_of = "cn"`. According to documentation:

```
# In POSIX LDAP schemas, without memberOf attribute a secondary query must be made for groups.
# This is done by enabling group_search_filter below. You must also set member_of= "cn"
# in [servers.attributes] below.
## Group search filter, to retrieve the groups of which the user is a member (only set if memberOf attribute is not available)

# group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
## An array of the base DNs to search through for groups. Typically uses ou=groups
# group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]
```

**Comment by Danilo-Schiller** [comment]
Well in normal case I don't have the a value with the name member_of. So i tried to replace the 'memberOf' with the 'cn'

But i tried also to use following group-filter:
group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"

But it has the same effect:

<img width="476" alt="bildschirmfoto 2018-08-08 um 13 58 27" src="https://user-images.githubusercontent.com/32914118/43835703-2b5f1da6-9b13-11e8-8ca1-0a4b4c709328.png">

The User attributes are empty at the log in, or in this case of the picture it recognizes only the uid but not the cn, sn or mail

**Comment by Danilo-Schiller** [comment]
The debug log shows, that the user attributes are empty:
FirstName: (string) \"\",\n LastName: (string) \"\",\n Username: (string) \"\",\n Email: (string) \"\",\n MemberOf: ([]string) <nil>\n})\n

**Comment by marefr** [comment]
@torkelo do you have any suggestions when user attributes are empty?

**Comment by torkelo** [comment]
@DanhcS does your ldap user have values for properties givenName or sn? what is the cn value? 

Not sure why your ldap server is not returning attributes.What ldap server are you using? 

Closing this as I do not think there is a bug here.
