### ISSUE TITLE
Data Source error - SQL Server

### ISSUE THREAD

**Issue by SuperHasie** [grafana/grafana#12842]
Hi Everyone,

I am new to grafana, I installed it on a VM, set it up as a service and I can connect remotely, but I have an issue with the data source.

I am trying to add a SQL server datasource, but keep on getting this error when testing:

"Unable to get instances from SQL Server Browser on host localhost: read udp [::1]:63362->[::1]:1434: I/o timeout"

I have checked the browser service and the UDP port on the firewall.

Can someone please help me
Thanks

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Are you sure you're using the core microsoft sql server datasource included in Grafana core, see [documentation](http://docs.grafana.org/features/datasources/mssql/).
