### ISSUE TITLE
how to get  alerting metrics like alerting.active_alerts and alerting.execution_time?

### ISSUE THREAD

**Issue by hjybdrs** [grafana/grafana#12859]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
 Grafana v5.2.0 (commit: ad4d717)
### What datasource are you using?
elasticsearch 
### What OS are you running grafana on?
window10
### What did you do?
i want to get alerting metics data when i trigger alerting through webhook
http://docs.grafana.org/alerting/metrics/#metrics-from-the-alert-engine
i have seen this page ,so i set alerting.execution_time in notifications in alert seeting like "multi happened {{alerting.execution_time}}"  but i didnot see the value.
### What was the expected result?
"multi happened 2018-08-09 "

**Comment by torkelo** [comment]
alerting metrics are exported to Prometheus via http /metrics route or pushed to graphite

**Comment by hjybdrs** [comment]
could i get the alerttime through grafana's webhook

**Comment by marefr** [comment]
@hjybdrs there's no field included so the alert time is "now", i.e. when the webhook is received
