### ISSUE TITLE
Unable to get any notifications via LINE

### ISSUE THREAD

**Issue by 9bryan7** [grafana/grafana#12851]
### What Grafana version are you using?
v5.0.3 (grafana/grafana:5.0.3)
### What datasource are you using?
influxdb
### What OS are you running grafana on?
Official docker image in CentOS 7
### What did you do?
Create a LIINE Alert notification
### What was the expected result?
Get a LINE notification
### What happened instead?
I have some alerts and notifications set up to monitor a few metrics. However I keep getting no data alerts on these alarms I have set up. I'm unable to get any notifications via LINE, but I'm able to get notifications via Email. Also I'm able to get a test notification successfully via LINE.

> Notification Channel Setting

![1](https://user-images.githubusercontent.com/5178667/43874908-e928cc30-9bc0-11e8-80aa-07f3c8242589.PNG)

> Alert Rules

![3](https://user-images.githubusercontent.com/5178667/43874824-6e4d2ea2-9bc0-11e8-8c64-bfe4c0f2391a.PNG)

> Line Test Notitication

![2](https://user-images.githubusercontent.com/5178667/43874827-707f79be-9bc0-11e8-8bf5-fed040a96835.PNG)

>  Alert Settings

![5](https://user-images.githubusercontent.com/5178667/43874918-fd9eaffe-9bc0-11e8-9d5b-71642a0ca896.PNG)
![6](https://user-images.githubusercontent.com/5178667/43874950-2bc07674-9bc1-11e8-9cf7-eba4e10d9668.PNG)

> Email Notification

![7](https://user-images.githubusercontent.com/5178667/43874998-637f5ce2-9bc1-11e8-84f2-76f5452be025.PNG)

**Comment by daniellee** [comment]
As alerts are sent from the backend, can you check the Grafana server logs for any errors. Does the server where Grafana is installed have access to the LINE service?
