### ISSUE TITLE
Support anonymous access with role other than "viewer"

### ISSUE THREAD

**Issue by andig** [grafana/grafana#12858]
This is a follow-up of https://github.com/grafana/grafana/issues/2335

### What Grafana version are you using?

Grafana v5.2.1 (2040f61)

### What OS are you running grafana on?

Docker

### What did you do?

I'm running grafana internally- if anonymous user has access he should have access according to the anon user role. This is the config:

    [auth]
    disable_signout_menu = true

    [auth.anonymous]
    enabled = true
    org_role = Admin

### What happened instead?

  - "Sign in" link is still visible. I'd like to hide this link (`disable_signin_menu = true`)
  - Staring of dashboards is not possible although role is admin: `You need to sign in to star dashboards`. 

This is more important than the previous point as it effectively prevents using anonymous access with other roles than `Viewer`.

**Comment by torkelo** [comment]
> disable_signout_menu  

This setting only works if your signed in (via auth proxy or other means). 

> Staring of dashboards is not possible although role is admin: You need to sign in to star dashboards.
 
Starring a dashboard is associated with a user, so you need to sign in to perform this user specific action. 

> This is more important than the previous point as it effectively prevents using anonymous access with other roles than Viewer.

How is that?
