### ISSUE TITLE
Package build fails during webpack w/ typescript definition errors

### ISSUE THREAD

**Issue by scoady** [grafana/grafana#12863]
Good morning!

I am trying to build and package an rpm distribution of Grafana out of the v5.2.1 release tag, and am experiencing some strange behavior on the build.

Here's basically what my build looks like:
```bash
npm install -g grunt
npm install -g grunt-cli
npm install -g yarn
npm install -g coffee-script
npm install -g jsonlint
npm install -g jshint
npm install -g node-gyp
yarn install --pure-lockfile
gem install fpm --no-ri --no-rdoc

export GOPATH=${WORKSPACE}/go
export GOBIN=${GOPATH}/bin

rm -rf ${GOPATH}/src/github.com/grafana/grafana
mkdir -p ${GOPATH}/src/github.com/grafana
cd ${GOPATH}/src/github.com/grafana
git clone https://github.com/grafana/grafana
cd ${GOPATH}/src/github.com/grafana/grafana
git checkout refs/tags/v5.2.1
npm install --save
go run build.go setup
go run build.go build package
```

This fails during webpack, noting missing typescript definitions:
[graf-5.2.1-pdf.pdf](https://github.com/grafana/grafana/files/2274821/graf-5.2.1-pdf.pdf)
 (attached are the build failures).

Note that this only happens if using the go run build.go build package target. 
Go run build.go build succeeds with no errors.

Grafana Version: 5.2.1
Datasource: n/a
OS: Oracle Enterprise Linux 7.4
What did I do: Ran the go build.go build package command
Expected result: Build succeeds
What happened: Build failed with missing typescript dependencies
Node/Go Environment: Go 1.10.2, Node 8.11.x. 

I have read the docs and searched the issues pages but havent seen anyone with similar issues, so hopefully it's just something I overlooked?

Thanks in advance.

**Comment by scoady** [comment]
Answering my own question, but I'll go ahead and leave this around so others with this issue don't spend a ton of time researching this.

This fixed my build:

```bash
sed -i '/compilerOptions/a   "typeRoots": [ "./node_modules/@types" ],' tsconfig.json
```

Looks like it's maybe a downstream issue from awesome-typescript-loader.
https://github.com/s-panferov/awesome-typescript-loader/issues/232

**Comment by torkelo** [comment]
Try using yarn instead:

npm install -g yarn
yarn install --pure-lockfile
