### ISSUE TITLE
Rendering error on explore page

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#12868]
<img width="457" alt="screen shot 2018-08-10 at 11 27 39" src="https://user-images.githubusercontent.com/444037/43950406-7ffb2bec-9c90-11e8-8de0-da0a9b9bc7c7.png">

**Comment by davkal** [comment]
Can't repro. Perhaps it's a caching issue? I'd need to debug this on your machine @tomwilkie

**Comment by davkal** [comment]
The issue is that the styles fingerprint is the release string:
```html
<link rel="stylesheet" href="public/build/grafana.light.css?v5.3.0-pre1">
```
For our CI scenario and folks testing lastest, this can easily lead to old styles being applied to new markup.
