### ISSUE TITLE
Repeating Rows: old data remaining in first row

### ISSUE THREAD

**Issue by fwetzler98** [grafana/grafana#12866]
Hello Grafana-Team,
I am working on a dashboard for “standard server metering” with repeating rows of mixed “singlestat” and “graf” panels which is driven by two variables, nothing really complicated.

**Issue:**
Opening the dashboard takes all Variable content from the last save session, quite normal, all values are correct. Now I am switching variable for another server group (“Umgebung”), the dashboard fills all rows with new content, but the first row has the values from the previous server group except the first panel member. There I cannot distinguish because all servers have same uptime.

Open Dashboard:
![image](https://user-images.githubusercontent.com/42264182/43944015-cf26a39e-9c7d-11e8-9719-d31265fc03b6.png)

Change server group:

![image](https://user-images.githubusercontent.com/42264182/43944032-dc5c0ebe-9c7d-11e8-8569-28da1aa1d104.png)

Refresh or Change Time Range:

![image](https://user-images.githubusercontent.com/42264182/43944036-e1753632-9c7d-11e8-90c0-6f24c43caee5.png)

**Settings:**
Repeating rows for all row elements:

![image](https://user-images.githubusercontent.com/42264182/43944061-ed362904-9c7d-11e8-870b-09a9988bbf28.png)

**Variables:**
1)        “Umgebung”: Custom list, comma separated 
2)        “server”: Query: “SHOW TAG VALUES FROM “system” WITH KEY = “host”
Regex: /$Umgebung.*/

**Environment:**
Ubuntu 16.04.1 LTS (4.4.0-130-generic)
Grafana 4.x, 5.0.4, 5.1
Data source: telegraf 1.3.x, 1.4.x, 1.7.0 with InfluxDB 1.0.1

Interesting issue ...?
I hope you can help

Regards
Frank

**Comment by torkelo** [comment]
thanks for reporting this, we will investigate

**Comment by torkelo** [comment]
Can you try latest Grafana? version v5.2.2 ?

I tried this in master and I cannot replicate this problem

**Comment by fwetzler98** [comment]
Hello Torkel,

just renewed the Grafana docker service to 5.2.2 from docker hub.
[cid:image001.png@01D433BA.B25DC390]
Same behavior …  ☹

But I added my Dashboard in a zip file. Perhaps you can detect what I ‘ve made potentially wrong … or Grafana … 😉

Regards
Frank

**Comment by torkelo** [comment]
Are you stll having this issue? Still unable to replicate, and no other reports so closing this

**Comment by fwetzler98** [comment]
Hello Torkel,

yes, this issue is not solved.
I ‘ve tried any solution in my mind but nothing has helped.

I think that “repeating rows” in combination with Template Variables is the core problem.
Our Templating is based on a consequent Name schema for all components and almost all variables are built by a query which is “formed” by a RegEx.
Additional: in Variables you cannot set Refresh on “Time Range Change” AND “On Dashboard load”, only “OR” is possible.

What I faced additionally that some Dashboards seem to refresh more than once (except the first row!) if you pick another value from a Variable. Perhaps this behavior gives another thought about my issue …

Additionally missing in Grafana: string manipulation functions like “upper()”, “lower()” … I missed that for building a http-link to our XWiki

Regards
Frank
