### ISSUE TITLE
Feature Request: there is any way to put a lateral panel to make a Dashboard list/tree?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1287]
Hi @torkelo.

I would like to have a lateral  list of dashboards  ( o perhaps a tree of them) to fast change between dashboards.

![image](https://cloud.githubusercontent.com/assets/5883405/5586447/3ffb09d0-90ce-11e4-972b-b5c7beb7939d.png)

or

![image](https://cloud.githubusercontent.com/assets/5883405/5586461/c27859e4-90ce-11e4-9e74-24db6f95c2f7.png)

There is any easy way to do that in current master release?

**Comment by torkelo** [comment]
I think this issue is solved by the dashboard list panel

**Comment by toni-moreno** [comment]
It is nor really what I need .
What I need Indeed is more or less something like that.  


![image](https://cloud.githubusercontent.com/assets/5883405/7535522/73cf2c60-f586-11e4-94c1-9feed717b685.png)


Each node of the tree is a dashboard with drilldown links to other dashboards with more detailed metrics.

I would like to replace this dashboard with graphana  if posible
