### ISSUE TITLE
Provisioning datasources should not require manual handling of deletions 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#12875]
Currently, you have to manually add a section to delete data sources, this should all happen automatically.

**Comment by bergquist** [comment]
To solve this we need to identify which file a datasource has been provisioned from. Either by introducing a new relation table as we do with dashboards or a nullable field in the datasource table.

**Comment by torkelo** [comment]
Wont a property in the datasource (table) suffice? Then remove any datasource that is not in any provisioning yaml file.

Tricky thing would be to handle renames without generating a new db id

**Comment by Kot-o-pes** [comment]
just bumping up a thread here, issue is much more painful when you have more then 100 datasources provisioned automatically from ansible run

**Comment by brandan-schmitz** [comment]
Also looking to have this looked at and solved. I also use Ansible to manage many datasources and dashboards as well and this is pretty important that we can manage it without manual changes in the UI.

**Comment by joariasl** [comment]
You can delete the provisioned datasources passing their reference name like

```yaml
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1
```

See more
https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources

**Comment by brandan-schmitz** [comment]
> You can delete the provisioned datasources passing their reference name like
> 
> ```yaml
> # list of datasources that should be deleted from the database
> deleteDatasources:
>   - name: Graphite
>     orgId: 1
> ```
> 
> See more
> https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
> https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources

That is understood and has been mentioned previously. However, this is not the functionality that is needed or requested. It is difficult to have to go back and add individual datasources to be deleted when there are potentially hundreds managed through a CI pipeline. In reality, if a data source is removed from the config it should automatically get removed from the database as that is what the expected behavior would be.

**Comment by bergquist** [comment]
We agree. We just haven't found time to work on it yet.

**Comment by rafecolton** [comment]
This seems to only work if `orgId` is 1 regardless of the datasource ID. Why is that?

Also curious if there is any update on this? Not so bad if there are only a couple of datasources, but it's kind of janky...

**Comment by tommyknows** [comment]
We've also run into this and have wondered. What would need to be implemented here?

An option would be a `deleteStaleDatasources` setting in the config file, which then ensures that all datasources that are registered in Grafana are also defined in the config. Wdyt?
