### ISSUE TITLE
Timestamp in localtime when dashboard set to UTC in graph y-axis

### ISSUE THREAD

**Issue by bscherlein** [grafana/grafana#12872]
### What Grafana version are you using? 
Grafana v5.2.2 (aeaf7b2)
### What datasource are you using?
Prometheus
### What did you do?
Set the graph y-axis to display the value of a query in a dashboard where the timezone is set to UTC, using one of the three provided datetime formats under 'Unit'. (The metric is an epoch timestamp.)
![image](https://user-images.githubusercontent.com/28387556/43956091-18ac20fa-9ca3-11e8-9b88-d7e66553cca9.png)
![image](https://user-images.githubusercontent.com/28387556/43956471-a5c52c24-9ca4-11e8-9ef9-c44489928df4.png)
### What was the expected result?
To see the time in UTC
### What happened instead?
Saw the time in local time

Similar to https://github.com/grafana/grafana/issues/12871.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/12871
