### ISSUE TITLE
Graph range to now() + offset

### ISSUE THREAD

**Issue by surftastic** [grafana/grafana#1288]
Hi,
    will it be possible to show graphs points up to now() but have the graph range go a little further into the future by an offset, e.g. 10m or 30m.
    The use case is we have future events which we know may affect production in influx, we'd like to be able to see these events coming a little ahead of time. So the graph panel would show data points up to now() but events up to now() + offset.
    Hope that makes sense. Awesome system btw !

**Comment by torkelo** [comment]
you can do that in the timepicker, just specify now+10m
