### ISSUE TITLE
how to show tracing info in grafana?

### ISSUE THREAD

**Issue by kongkong56** [grafana/grafana#12888]
how to show tracing info in grafana? i cant find some dashboards in grafana to show some tracing info like jeager

**Comment by kongkong56** [comment]
can show tracing data in elasticsearch?

**Comment by torkelo** [comment]
yes, you can show data from elasticsearch in Grafana (in graphs & tables etc)

**Comment by kongkong56** [comment]
but graphs & tables cant show tracing data like jeager ui

**Comment by torkelo** [comment]
for that we need custom tracing viz which we have yet to implement
