### ISSUE TITLE
Sqlserver $__timeGroup macro issues

### ISSUE THREAD

**Issue by zhangbendong** [grafana/grafana#12881]
Sorry for my bad English:

so show code:

$__timeGroup(CreateOrderTime, '24h') => CAST(**ROUND**(DATEDIFF(second, '1970-01-01', CreateOrderTime)/86400.0, 0) as bigint)*86400 

One week data Group By days , I got 8 result.

![image](https://user-images.githubusercontent.com/4468821/44000891-a4aed3b4-9e5a-11e8-89a8-4fe265a7ee52.png)

So Should this **ROUND**  macro be replace by **FLOOR** or **CEILING** ?

**Comment by svenklemm** [comment]
This should be fixed in master. Grafana 5.3 will use floor in $__timeGroup macro.

https://github.com/grafana/grafana/pull/12470
