### ISSUE TITLE
Alerting to Microsoft Teams not embedding or displaying graph images

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#12898]
**Grafana version:** 5.2.2
**Datasources:** Azure Monitor, ElasticSearch, InfluxDB
**OS:** Ubuntu 16.04 on Azure

**Issue:** Grafana alerts to Microsoft Teams not displaying graph images. Test image does display, but very small, so unreadable.
**Expected result:** Graph image displayed and readable, same as for the Slack integration.

There is very little documentation around the MS Teams integration, so I may have not set something correctly, but I have not found out what. Otherwise it is an inconsistent experience vs. Slack which displays the graph and is viewable at a size you can read. The test notification does work with an image, but it is too small to read any details.

**MS Teams Alert Example:**
![ms_teams_grafana_alert](https://user-images.githubusercontent.com/1184220/44030853-fbb3b6ee-9ef9-11e8-976c-88cca6fdc639.PNG)

**Slack Alert Example:**
![slack_grafana_alert](https://user-images.githubusercontent.com/1184220/44030980-649f00f0-9efa-11e8-9934-41e4f3249c75.PNG)

**Comment by torkelo** [comment]
have you configured an external image store? http://docs.grafana.org/installation/configuration/#external-image-storage 

Anything in grafana server log that could be related?

**Comment by bhozar** [comment]
**I've configured Azure Blog Storage within grafana.ini:**
[external_image_storage.azure_blob]
;account_name = cks
;account_key = randomkeyhere
;container_name = grafana-images


**The grafana.log shows:**
t=2018-08-14T11:22:30+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=32 newState=ok prev state=alerting
t=2018-08-14T11:22:33+0000 lvl=info msg=Rendering logger=rendering path="d-solo/lciQJzgmz/azure-alerts?panelId=38"
t=2018-08-14T11:22:35+0000 lvl=info msg=uploaded logger=alerting.notifier url=
t=2018-08-14T11:22:35+0000 lvl=info msg="Executing teams notification" logger=alerting.notifier.teams ruleId=32 notification=TeamsWarning
t=2018-08-14T11:22:35+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=32 notification=SlackWarning
t=2018-08-14T11:22:35+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack

**Comment by marefr** [comment]
@bhozar please read the [documentation](http://docs.grafana.org/installation/configuration/#comments-in-ini-files) carefully. **;** means a comment so you should remove trailing **;** from 

> ;account_name = cks
> ;account_key = randomkeyhere
> ;container_name = grafana-images

**Comment by bhozar** [comment]
Sorry, had only just added the ; back in. I found the issue and it was further up the config file:

[external_image_storage]
# Used for uploading images to public servers so they can be included in slack/email messages.
# you can choose between (s3, webdav, gcs)
provider = azure_blob

Once set to azure_blob it works fine. Only down side is the image is too small to actually view. Used to Slack where you can click an image and it shows the full image. I'll open a separate feature request. Thanks for the assistance.
