### ISSUE TITLE
Support for drawing Gauges

### ISSUE THREAD

**Issue by albertobaselga** [grafana/grafana#129]
I haven't found any feature request about this, and it would be really really interesting for our company to unify all kind of time series graphs in your dashboard framework.

**Comment by DaveBlooman** [comment]
We'd love this please

**Comment by carlozleite** [comment]
As temporary alternative you can add the justgage libraries in index.html and add a text panel and within it as html include justgage configuration where the value is a variable template. I tested and it worked ....

**Comment by lynchc** [comment]
+1

**Comment by mkevac** [comment]
Any news?

**Comment by torkelo** [comment]
@mkevac no :( so many other issues to work on :)

**Comment by gsaray101** [comment]
+1

**Comment by nimeops** [comment]
Of Course ! +1

**Comment by shankar-piriya** [comment]
+1

**Comment by bamboo54** [comment]
+1

**Comment by vpanizo** [comment]
+1

**Comment by darrynv** [comment]
+1

**Comment by jamesbibby** [comment]
+1

**Comment by digrich** [comment]
+1

**Comment by chrisburrows** [comment]
Gauge would be an excellent addition. Could also consider having an option for the gauge to respond to the shared cross hair. When mouse-over a graph with shared cross hair enabled, the gauge (and singlestat) could show the value at that time, and update as the mouse is moved in time on he graph.

**Comment by utkarshcmu** [comment]
@jmaitrehenry - My 2 cents. :) justgage uses raphael.js, which is a completely different library and Grafana will have an added dependency. But the git repo which I pasted above uses "flot" and we use "flot" for all other panels. So, impo, if we stay with flot, it will be better to manage dependencies. 

Rest is up to you and @torkelo. :)

**Comment by utkarshcmu** [comment]
WIP: 

![grafana_gauge 1](https://cloud.githubusercontent.com/assets/1019609/10557861/5722dcf0-7471-11e5-9285-5a728b2324d6.gif)

Any feedback?

**Comment by stefanoric** [comment]
+1

**Comment by utkarshcmu** [comment]
If anyone is interested to work on this feature with me as I am not a UI expert, here is the fork to contribute:
https://github.com/utkarshcmu/grafana/tree/gauges

**Comment by sslupsky** [comment]
+1

**Comment by gbrian** [comment]
+1

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/3688
