### ISSUE TITLE
Grafana crashing Firefox

### ISSUE THREAD

**Issue by hellajoey** [grafana/grafana#1290]
Hi. I was in the middle of exporting and importing a dashboard configuration and now trying to load Grafana causes my Firefox to not respond. The screen is completely blank except for an error message that says: "Dashboard load failed. Cannot reload unsaved imported dashboard."

I see in my browsing history that the page is forwarding to /grafana/#/dashboard/import/walstop1 and then it freezes. I have cleared the history and restarted my machine and even re-installed (copied) grafana. Same effect. Notably, Grafana is working in Opera including the Walstop-1 saved dashboard.

Any help? Thanks.

-Joey

**Comment by torkelo** [comment]
I tried importing and exporting a json in firefox on play.grafana.org and it worked fine. Might be something in the your json that hangs firefox or a firefox extension?

**Comment by hellajoey** [comment]
Not sure. I have gotten it to work more often than not in Firefox too. I should mention that since leaving this note the same thing also happened in Opera (It didn't freeze but it did prevent any further use of Grafana). From the message I'm guessing it has something to do with setting a dashboard which is imported as the home dashboard and then moving or deleting the json file. 

The problem of it not loading is secondary though to the problem that when this happens no other actions are available in Grafana. There are no menu items in which to back out of the issue. I did find a work around which is to navigate to: http://.../grafana/#/dashboard/file/default.json and reset the home dashboard. I can work with this fix now and just be careful when manipulating imported dashboards that are set as the home dashboard. I figured you'd want to know about this though because unless someone discovers this work around it seems like Grafana is essentially non-working in the given browser. 

Cheers. Love the product.

**Comment by torkelo** [comment]
You can't set an imported dashboard  as a saved default. you have to save it first. Have you checked firefox dev console for js errors?

**Comment by hellajoey** [comment]
Ah, that was probably it. I did not check the dev console, no. I guess I would just suggest trying to allow users to still access the menu items when this happens so they can fix the problem. Otherwise, all you ever see is the error message on a black screen. There's no obvious way out.

**Comment by torkelo** [comment]
Must be an inhandlad exception when loading import route without loading an import json file, will fix that tomorrow!

**Comment by hellajoey** [comment]
Thanks, man. Great stuff.

**Comment by eslowney** [comment]
I have the same issue, is there a workaround if i can't upgrade versions?

Basically, i closed out of firefox for the day.  The next day i open firefox and my browser and all tabs are hung, and every 20 sec I get a "Warning: unresponsive script" error.  Clicking on either stop script or continue just prompts the same warning 20 sec later.  The browser is unresponsive, and i have to kill it from command line.

Opening up firefox again hangs itself.  Hellajoey's fix does work, but I can only type 1 or two letters in the URL bar every 20 sec, so it will take 5-10 min to enter the URL above.  I'll try a safe mode or something just so I can use firefox again.
