### ISSUE TITLE
Using Wildcard in mode filter

### ISSUE THREAD

**Issue by Lukkid** [grafana/grafana#12915]
Read before posting: 

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I try to count the number of wmi_service_status with name wpnuserservice_* to get the number of active user sessions cause the wpnuserservice_* process is running in the same amount than users are logged in.

Thats the result the WMI Exporter is giving:

wmi_service_status{name="wpnuserservice_19d66e00",status="degraded"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="error"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="lost comm"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="no contact"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="nonrecover"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="ok"} 1
wmi_service_status{name="wpnuserservice_19d66e00",status="pred fail"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="service"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="starting"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="stopping"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="stressed"} 0
wmi_service_status{name="wpnuserservice_19d66e00",status="unknown"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="degraded"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="error"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="lost comm"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="no contact"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="nonrecover"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="ok"} 1
wmi_service_status{name="wpnuserservice_1c5eca5b",status="pred fail"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="service"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="starting"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="stopping"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="stressed"} 0
wmi_service_status{name="wpnuserservice_1c5eca5b",status="unknown"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="degraded"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="error"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="lost comm"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="no contact"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="nonrecover"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="ok"} 1
wmi_service_status{name="wpnuserservice_1c98e778",status="pred fail"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="service"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="starting"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="stopping"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="stressed"} 0
wmi_service_status{name="wpnuserservice_1c98e778",status="unknown"} 0

How does I do that?

**Comment by Lukkid** [comment]
btw I actually try this query that dont work:

count(wmi_service_status{name="wpnuserservice_*", status="ok"}) by (name)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You'll need to use the regex format, i.e. name=~"^wpnuserservice_.*"
