### ISSUE TITLE
Feature Request: Add Zabbix API Datasource

### ISSUE THREAD

**Issue by nucleusv** [grafana/grafana#1291]
I try to write new datasource for Grafana to get data from Zabbix database using Zabbix API.

I wrote some code using custom datasource example.

    define([
      'angular',
      'lodash',
      'kbn',
      'moment'
    ],
    function (angular, _, kbn) {
      'use strict';
    
      var module = angular.module('grafana.services');
    
    
      module.factory('ZabbixAPIDatasource', function($q, $http, templateSrv) {
    
        // the datasource object passed to constructor
        // is the same defined in config.js
        function ZabbixAPIDatasource(datasource) {
          this.name 		    = datasource.name;
          this.supportMetrics 	= true;
          this.url 			    = datasource.url;
          this.user 		    = datasource.user;
          this.password		    = datasource.password;
    
    
          this.config           = new Object();
          this.auth             = new Object();
          this.zabbix_api       = new Object();
            this.token          = new Object();
    
    
          this.zabbix_api.request_count = 1;
          this.zabbix_api.token = null;
        }
    
    
          ZabbixAPIDatasource.prototype.query = function(options) {
              // get from & to in seconds
              var from = kbn.parseDate(options.range.from).getTime();
              var to = kbn.parseDate(options.range.to).getTime();
              var queries = ""; //_.compact(_.map(options.targets, convertTargetToQuery));
    
              from = Math.ceil(from + 0);
              to = Math.ceil(to + 0);
    
              var series = [];
              var stepInSeconds = Math.round((to - from) / 100);
    
              for (var i = 0; i < 3; i++) {
                  var walker = Math.random() * 100;
                  var time = from;
                  var timeSeries = {
                      target: "Series " + i,
                      datapoints: []
                  };
    
                  for (var j = 0; j < 100; j++) {
                      timeSeries.datapoints[j] = [walker, time];
                      walker += Math.random() - 0.5;
                      time += Math.ceil(stepInSeconds);
                  }
    
                  series.push(timeSeries);
              }
    
              //console.log(from+" "+to);
              //console.dir(series);
              //console.dir($q);
              // alert(from+" "+to);
    
              console.dir(options);
    
              //var test = this.zabbixLoginIn().then();
    
              //console.log(test);
    
    
              //return $q.when({data: series });
    
              return this.performTimeSeriesQuery(queries, from, to)
                  .then(_.bind(function (response) {
                                return {data: result};
              },options));
        };
    
          ZabbixAPIDatasource.prototype.performTimeSeriesQuery = function(queries, start, end) {
              var reqBody = {
                  start: start,
                  queries: queries
              };
    
              // Relative queries (e.g. last hour) don't include an end time
              if (end) {
                  reqBody.end = end;
              }
    
              var options = {
                  method: 'POST',
                  url: this.url + '',
                  data: reqBody
              };
    
              var auth;
              var token = this;
              if(!this.zabbix_api.token) {
                  auth = this.zabbixAPILoginIn();
                  auth.then(function(auth_token){
                      token =  auth_token;
                      //console.dir(auth_token);
                      //console.dir(token);
                  });
    
    
              }
    
              console.dir(this);
              //console.dir(token);
              return $http(options);
          };
    
          ZabbixAPIDatasource.prototype.zabbixAPILoginIn = function(){
             // this.config.url = this.url;
              this.config.method = 'POST';
              this.config.headers = {'Content-Type':'application/json-rpc'};
    
             // console.dir(this.config.headers);
    
             // var request = new Object();
    
             var self = this;
    
              this.auth.login = {
                  "jsonrpc": "2.0",
                  "method": "user.login",
                  "params": {
                      "user": this.user,
                      "password": this.password
                  },
                  "id": this.zabbix_api.request_count,
                  "auth": this.zabbix_api.token
              }
    
              //this.config.data = this.auth.login;
    
              console.dir(this.config);
    
              var token;
              return $http.post(this.url,this.auth.login,this.config).then(function(response) {
                      self = response.data.result;
                      return { token: token };
                  });
    
    
    
    
    
    
          }
    
          ZabbixAPIDatasource.prototype.setToken = function(data){
              alert('ola');
              //var this.token = data.result;
              console.log('data');
              console.dir(data);
          }
    
        return ZabbixAPIDatasource;
    
      });
    });

The logic is, before making query to zabbix api to get history data, we need to get auth from api.
So every call of function ZabbixAPIDatasource.prototype.query must first check if there a token is?
If not it must call ZabbixAPIDatasource.prototype.zabbixAPILoginIn to get a token.

After that we can do query to history data and return it to controller.
The problem is that this code is async and function returns promise to controller but not in object service. Due to Grafana we cann't change source code to change controller.

How to get this code work:

       var token = this;
       if(!this.zabbix_api.token) {
                  auth = this.zabbixAPILoginIn();
                  auth.then(function(auth_token){
                      token =  auth_token;
                      //console.dir(auth_token);
                      //console.dir(token);
                  }); 

it doens't rewrite this object.
I need to do sync code: first to get result from login function and only after that do history query.
How can I do this?

**Comment by nucleusv** [comment]
I got it: promises chainning and everything is OK:

  var self = this;
          return $http.post(this.url,this.auth.login,this.config).then(function(response) {
              self.zabbix_api.token = response.data.result;

              var request = {
                  "jsonrpc": "2.0",
                  "method": "host.get",
                  "params": {
                      "output": [
                          "hostid",
                          "host"
                      ],
                      "selectInterfaces": [
                          "interfaceid",
                          "ip"
                      ]
                  },
                  "id": 2,
                  "auth": self.zabbix_api.token
              }

              return $http.post(self.url,request,self.config).then(function(response) {



                  return $q.when({data: series });
              });
          });

**Comment by torkelo** [comment]
please move https://github.com/grafana/grafana-plugins
