### ISSUE TITLE
http access has no proxy option and HTTP Error Not Found

### ISSUE THREAD

**Issue by Winnixiaowan** [grafana/grafana#12913]
![1534234611673](https://user-images.githubusercontent.com/42372075/44080714-7535a82a-9fdf-11e8-9332-b5a11a296e8f.jpg)
### What Grafana version are you using?
v5.2.2
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Mac
### What did you do?
add datasource
### What was the expected result?
http access should has proxy option and no HTTP Error Not Found
### What happened instead?
http access only has Server and Browser option but no proxy option

**Comment by torkelo** [comment]
Server = Proxy option

**Comment by torkelo** [comment]
Also specify an address in the URL input field

**Comment by Winnixiaowan** [comment]
Hi,
I have already specify the address in the URL field.
![wechatimg1](https://user-images.githubusercontent.com/42372075/44082607-4b75f404-9fe4-11e8-994b-5279228ea3a5.jpeg)

I cannot get access to http://localhost:8080
In the http access field, there are only two options: server and browser, but I want to use proxy.

Thanks a lot.

**Comment by marefr** [comment]
Select Server - It was renamed from Proxy to Server a while ago

**Comment by Winnixiaowan** [comment]
still HTTP error

**Comment by marefr** [comment]
Looks to me you don't have a graphite instance running locally on same machine as your Grafana instance. You're aware you have to install Graphite separately from Grafana right?

**Comment by Winnixiaowan** [comment]
![1534297611340](https://user-images.githubusercontent.com/42372075/44127525-470e76f2-a070-11e8-8fa4-c51bb8cf08f1.jpg)
It shows not require installation.
So I just need a graphite instance? How to generate?

**Comment by Winnixiaowan** [comment]
I thought I should add datasource at first and get no HTTP error, then add dashboard and edit it to generate data.

**Comment by Winnixiaowan** [comment]
OK, thanks a lot~~
