### ISSUE TITLE
Update tslint.json rules

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#12918]
Add  
   "interface-name": [true, "never-prefix"]

And try these extensions (tslint-react needs to be added via yarn add) 
 "extends": [
    "tslint:recommended",
    "tslint-react",

**Comment by dehrax** [comment]
## tslint-react
[Rules](https://github.com/palantir/tslint-react)
Rules I think should be applied:
- jsx-element with no children should be self closing
- jsx-alignment, closing
 tag must be on its own line and aligned with opening tag

Rules that can be discussed:
- jsx attributes must be on their own line and vertically aligned
- `.bind(this)` not allowed, due to rendering performance impact. (jsx-no-bind)
- jsx-no-lambda. Function declarations inside `render()` not allowed

Rules that shoud not be applied:
- Multiline JS inside JSX

## tslint:recommended
To be continued...

**Comment by dprokop** [comment]
Some summary of the potential work scale after running `tslint:recommended` on the codebase. Maybe you'll find it helpful:

#### Lint issues scale overview:  
```
{
  "quotemark": 18706,
  "prefer-const": 3084,
  "only-arrow-functions": 1768,
  "arrow-parens": 812,
  "ordered-imports": 581,
  "object-literal-shorthand": 398,
  "trailing-comma": 259,
  "object-literal-key-quotes": 132,
  "member-ordering": 127,
  "one-variable-per-declaration": 93,
  "prefer-for-of": 74,
  "interface-name": 71,
  "jsdoc-format": 58,
  "no-angle-bracket-type-assertion": 57,
  "max-classes-per-file": 24,
  "no-conditional-assignment": 9,
  "no-consecutive-blank-lines": 7,
  "no-empty-interface": 5,
  "ban-types": 4,
  "space-before-function-paren": 1,
  "no-var-requires": 1,
  "use-isnan": 1,
  "array-type": 1
}
```

#### Low hanging fruits  (can be autofixed by tslint), ~83% of all issues:
```
{
  "quotemark": 18706,
  "prefer-const": 1044,
  "arrow-parens": 812,
  "ordered-imports": 581,
  "object-literal-shorthand": 398,
  "trailing-comma": 259,
  "object-literal-key-quotes": 132,
  "no-angle-bracket-type-assertion": 57,
  "no-consecutive-blank-lines": 7,
  "space-before-function-paren": 1,
  "array-type": 1
}
```

**Comment by marefr** [comment]
Thanks @dprokop :+1:

**Comment by torkelo** [comment]
@dprokop how did you generate those totals? can't find any tslint formatter that outputs totals

**Comment by dprokop** [comment]
@torkelo I've generated JSON output from tslint and did a quick coding in Node's REPL. For fixable totals, I have selected those errors that had `fix` property defined.

**Comment by dprokop** [comment]
@torkelo here's the gist https://gist.github.com/dprokop/b71b2c26aa99e91ea1fd6adafd880adc

**Comment by dprokop** [comment]
@torkelo as a side effect of this issue I have published https://www.npmjs.com/package/tslint-totals-formatter that may be helpful :)

**Comment by torkelo** [comment]
Nice! Total file count could also be interesting.

Been looking into how to progressivly turn on stricter typescript rules but it so all or nothing, makes it impossible to migrate to I a bug code base.

**Comment by dprokop** [comment]
You can always disable those problematic rules from e.g. `tslint:recommended` globally (or at least change severity to Warning). Or per file basis, if there are places that are hard to migrate at the moment. I would most probably go with such approach to make sure new code is stricter rule set compliant.

**Comment by torkelo** [comment]
added "array-type": [true, "array-simple"],
