### ISSUE TITLE
[sqlserver] timezone in sql

### ISSUE THREAD

**Issue by zhangbendong** [grafana/grafana#12916]
I set Timezone = Default or Local browser time in  [Time Options] , 
but it generates the code use UTC time.

![image](https://user-images.githubusercontent.com/4468821/44087587-ea20ca44-9ff2-11e8-96cd-a229e65fed19.png)

**Comment by marefr** [comment]
That's only a browser setting. The timestamps sent to the datasources that 
Grafana integrates against is always in UTC time. You should make sure to store your timestamp in UTC in database to be sure of compatibility.

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
