### ISSUE TITLE
Password strength estimation is completely bad

### ISSUE THREAD

**Issue by Porkepix** [grafana/grafana#12910]
### What Grafana version are you using?
5.2.2

### What did you do?
I wanted to create an account after I received an email for that.

### What was the expected result?
Have an accurate information about password's strength.

### What happened instead?
It gave me completely wrong strength estimation, and is purely based on the length, considering tests and https://github.com/grafana/grafana/blob/master/public/app/core/components/PasswordStrength.tsx#L13-L30

No, "aaaa" does not have an average strength: it's bad. Same goes for "aaaaaaaaa", it is far from being a strong password.
Password strength isn't just a length question as you can see.

Libs probably exist that test strength, lists of known bad passwords and so on, but if it's just to estimate it given the length, imho it's better not show any information considering how wrong is it.
Making it longer as for https://github.com/grafana/grafana/issues/1892 by extending it from 6 to 8 isn't better.
No, "123456789" or "password1" aren't strong passwords and never will.

Please correct that or remove that estimation, it would be better than giving a wrong security feeling.

**Comment by xlson** [comment]
I agree we should do a bit better than this. Thanks for pointing it out.

**Comment by ramosaj** [comment]
Hello! I'd like to tackle this. It's my first contribution (or attempt to contribute). Any suggestions on how to get started?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/public/app/core/components/PasswordStrength.tsx#L21

**Comment by Lusitaniae** [comment]
Didn't see any activity here so I gave it a shot, please see the linked PR.

**Comment by Lusitaniae** [comment]
To add to this ticket, it seems the password strength is only being used in a few scenarios.

Right now I see it being used in the invitation sign up page.

But its not used at all in 
* Create/Edit user from admin panel
* Change of admin password on first login

Maybe someone would like to have a look?

**Comment by torkelo** [comment]
Removed password strength estimation: https://github.com/grafana/grafana/issues/17748
