### ISSUE TITLE
Add option to disable showing Grafana version in footer & api

### ISSUE THREAD

**Issue by frots** [grafana/grafana#12925]
The default login page sent by the web server disclosed which version is in use. This information about the exact version of the web
application could aid an attacker to craft targeted attacks against this service.

I could not find a configuration option in the documentation or source code to hide the version information.

### What Grafana version are you using?
v5.2.2
### What datasource are you using?
n/a
### What OS are you running grafana on?
n/a
### What did you do?
HTTP GET /login
### What was the expected result?
No version information disclosure to unauthenticated user.
### What happened instead?
The footer discloses the installed version.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
`              <li>
                <a href="https://grafana.com" target="_blank">Grafana</a>
                <span>v5.2.2 (commit: aeaf7b2)</span>
              </li>`

**Comment by xlson** [comment]
We could potentially make it so that you can disable the listing of version information for users that aren't logged in. Not sure it's worth the hassle though; if an attacker really wants to identify the version of Grafana that is running I'm sure they will be able to even without the version number being listed.

@torkelo what is your take?

**Comment by torkelo** [comment]
Would be surprised if this is a common feature to have. But we can leave it open as a feature request

**Comment by frots** [comment]
It's common in software like web/mail servers to have an option to disable version disclosure.

Just the fact that an attacker might be able to find vulnerabilities even without the version information does not mean you should not try to make it as difficult as possible. A layered approach to security is good practice.

[https://www.owasp.org/index.php/Testing_for_Web_Application_Fingerprint_(OWASP-IG-004) & https://www.owasp.org/index.php/Top_10-2017_A6-Security_Misconfiguration]

**Comment by bergquist** [comment]
How about we always hide it on the login page instead?

**Comment by frots** [comment]
Hi @bergquist, that sounds sensible and is actually what the PR does. We only need to get rid of the configuration option though, but the rest is already there.

**Comment by bergquist** [comment]
@frots if you update the PR I will merge it.

**Comment by frots** [comment]
@bergquist I've updated the PR.

**Comment by marefr** [comment]
There may still be an issue since `window.grafanaBootData.settings.buildInfo` contains detailed Grafana build info and is easy to retrieve using Chrome Dev Tools for example.

**Comment by torkelo** [comment]
and the api/health endpoint

**Comment by frots** [comment]
@bergquist @torkelo @marefr , I changed the PR to cover both the api/health endpoint and `window.grafanaBootData.settings.buildInfo`.

**Comment by frots** [comment]
Hi @bergquist @torkelo @marefr, does this issue and the PR need any further changes to be accepted?

**Comment by HyeokJung** [comment]
+1 I totally agree with frots.
I think the option to hide version information should be provided.
This feature very important for security.
There are already too many botnets on the web.

**Comment by abunasar** [comment]
+1 on this!

**Comment by zicklam** [comment]
Upvote from me too +1

**Comment by kskewes** [comment]
+1 from us too.

**Comment by HyeokJung** [comment]
It has been a long time since this issue was raised, but it still does not offer this feature.
I'm waiting for this issue to be accepted officially.
However I can't wait unit that time. 
I'm using nginx sub_filter module to hide version information

location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Accept-Encoding "";

    sub_filter_types *;
    sub_filter_once off;
    sub_filter 'v6.0.2' '';
    sub_filter '3f4c2e7' 'N/A';
}
* sub_filter module is not support regex :'(

**Comment by frots** [comment]
@HyeokJung you can always use my patches in the PR https://github.com/grafana/grafana/pull/12950

**Comment by pgporada** [comment]
I believe this ticket should be re-opened.

**Comment by danner26** [comment]
I believe this should be reopened as well, this is still an ongoing issue.

**Comment by jprenken** [comment]
+1

**Comment by JorritSalverda** [comment]
Can we get this in? Security audits are a *** (peep), this will really help us get them of our back ;)

**Comment by newfield86** [comment]
+1 strange that this take so long..

**Comment by martinr92** [comment]
+1 can't believe that there's still no option

**Comment by pmeisen** [comment]
+1 as well, audits don't like version numbers to be visible or accessible

**Comment by danner26** [comment]
I am unsure how this still needs investigation, this seems to be a simple issue to fix and a needed option for anyone worried about security for a public facing project. 

Can I ask what you still need to make this happen?

**Comment by kir4h** [comment]
+1 on this request! Seems kind of basic to have

**Comment by kskewes** [comment]
This has just been flagged in our Network audit.

**Comment by benclapp** [comment]
Looks like this has been removed in version 7.0 from the UI, however it's still visible in the source for an unauthenticated user
```html
<span class="sidemenu-item-text">Grafana v7.0.0 (aee1438ff2)</span>
```

**Comment by hugohaggmark** [comment]
removed `needs investigation` label because work is already in progress

**Comment by tsn77130** [comment]
For those who use apache2 as proxy, you can use following configuration (with a2enmod substitute)

```
      AddOutputFilterByType SUBSTITUTE text/html
      Substitute "s/Grafana v[0-9]\.[0-9]\.[0-9] \([0-9a-z]*\)/my_replacement_chain/"
```
