### ISSUE TITLE
 Grafana Dashboard Permission UI not appearing

### ISSUE THREAD

**Issue by gtmbanerjee1** [grafana/grafana#12923]
The dashboard permission screen is not coming with admin user. The grafana version is 5.1.4 and OS is ubuntu. The apis for dashboard permission is there.

**Comment by marefr** [comment]
Hey. Could you please elaborate on where you don't see the permission screen and possibly what steps to reproduce. Maybe include screenshot?

**Comment by marefr** [comment]
Closing this due to no response. Will consider reopen on request.

**Comment by marefr** [comment]
@gtmbanerjee1 FYI opened #13201 since I noticed that this problem exists in master branch (not yet released). However, as I wrote above I'm not been able to reproduce it on v5.1.4.
