### ISSUE TITLE
Metric request error while configuring Oracle Datasource

### ISSUE THREAD

**Issue by varundmishra** [grafana/grafana#12929]
### What Grafana version are you using?
Grafana v5.2.1 (3508ea9)
### What datasource are you using?
Oracle Database
### What OS are you running grafana on?
RHEL 6.x
### What did you do?
Trying to configure the Oracle Datasource
### What was the expected result?
The Oracle Datasource is configured correctly
### What happened instead?
Getting the error "Metric request error"
### If related to metric query / data viz:
NA
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
NA

**Comment by torkelo** [comment]
Can you show output from grafana server log?

**Comment by varundmishra** [comment]
@torkelo : I dont have admin access on this Linux server, anything else I can help with from the Grafana end?

**Comment by varundmishra** [comment]
![image](https://user-images.githubusercontent.com/4353038/44148261-e7874fba-a097-11e8-959e-b03af606896a.png)

I am getting this from the Chrome Dev Tools when I click on "Save & Test".

**Comment by marefr** [comment]
@varundmishra this is a premium plugin. I would guess you have a Grafana subscription or are using the 30 day fully refundable trial - then you should already have an email address that you can contact at Grafana Labs for further support.

**Comment by torkelo** [comment]
If you do not have admin access or can access server logs how did you install the plugin? We can't help you without grafana server logs.
