### ISSUE TITLE
Patch releases for older versions should not be tagged as latest

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#12928]
Currently, any stable version we release will be tagged as latest and pushed to Docker Hub. This is usually fine, but cause problems when we create patch releases for older versions of Grafana.

Example:
1. `5.3.0` is released (`grafana/grafana:5.3.0` and `grafana/grafana:latest` are pushed)
2. `5.2.3` is released to patch a problem with `5.2.2` (`grafana/grafana:5.2.3` and `grafana/grafana:latest` are pushed)

In step 2 `grafana/grafana:latest` is incorrectly pointed at the image for `5.2.3` which means users not specifying a version of Grafana when running with docker will get an older version, or in the worst case even downgrade from `5.3.0` to `5.2.3`

**Comment by xlson** [comment]
@briangann Would you mind working on this fix for the docker image deployment for 6.3? We could probably solve it by querying the same file as Grafana itself does for up-to-date checking.

**Comment by marefr** [comment]
@aknuds1 didn't we have this problem recently and/or another issue has been created for it? Maybe we can close this then?

**Comment by gabor** [comment]
i can confirm that this problem is still happening.

**Comment by papagian** [comment]
@grafana/grafana-release-eng can you check if this is still an issue?

**Comment by dsotirakis** [comment]
@papagian, yeah, unfortunately it is :( 
We faced that issue recently, I'll move it to our board, thanks for following up!

**Comment by dsotirakis** [comment]
This is fixed now :) Closing.
