### ISSUE TITLE
Editor of folder get "access denied" while restoring dashboard from historical version

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#12926]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by marefr** [comment]
Haven't received any similar reports. Could the case be that the user in question has no edit access to create/save a dashboard in the general folder?

**Comment by fyang13** [comment]
Yes, we do not allow regular user to save dashboard under general folder.

**Comment by marefr** [comment]
I think that's the problem then looking at the code. Will verify as soon as I get time. Thanks

**Comment by marefr** [comment]
@fyang13 would it be possible for you to include the json content of these two http api requests?

```
<grafana url>/api/dashboards/uid/<your dashboard uid (the value in dashboard url between /d/ and /)>
<grafana url>/api/dashboards/id/<your dashboard id found in previous json content>/versions/<version id you're trying to restore to>
```

If you're using Chrome it should be fairly easy to see the dashboard id in the url of the network request in network tab when you try to [restore your dashboard version](http://docs.grafana.org/http_api/dashboard_versions/#restore-dashboard). The versionId should be included in that url which you can use in the second api request above.

Please strip out any sensitive parts

Make sense? Thanks

**Comment by fyang13** [comment]
@marefr This happened on any dashboards and I can recreate the issue by creating dummy dashboard so I doubt the issue is pertain to specific dashboard. But anyway, you can see https://gist.github.com/fyang13/b117aed7dde5deb1efe112e41a1776e5 for the dashboard json content you requested above.

**Comment by marefr** [comment]
@fyang13 Thank you!
