### ISSUE TITLE
Grafana 5.1.5 Panel column titles are not visible in Iphone

### ISSUE THREAD

**Issue by ShilpaSivanesan** [grafana/grafana#12937]
The panel column titles are not visible if data range is more than 5 days in Iphone
But it loads in android

**Comment by torkelo** [comment]
panel column titles? you mean on the table panel? can you show a screenshot?

**Comment by ShilpaSivanesan** [comment]
Yeah its on table panel

<img width="336" alt="screen shot 2018-08-15 at 10 31 58 pm" src="https://user-images.githubusercontent.com/34906268/44190341-23943e80-a0db-11e8-8c88-06c8e438649b.png">

**Comment by daniellee** [comment]
Can't recreate this. Closing the issue but we can re-open if this is still an issue.
