### ISSUE TITLE
Dividing two elasticsearch metric series and groupby device

### ISSUE THREAD

**Issue by zhiyp** [grafana/grafana#12938]
I need to devid two metric series( sum( hit request number)/ sum(total request number) ) which are groupby device id.
Get hit percent of each device,  and show bottom five devices.

How can I do it in Grafana editor?
Thanks anyway

Please include this information:
### What Grafana version are you using? 
5.1.0
### What datasource are you using? 
ElasticSearch
### What OS are you running grafana on? 
OpenSuse 11

**Comment by xlson** [comment]
I would like to direct you to our [community site](https://community.grafana.com/) where we try to answer general questions about how to use Grafana. Issues are mainly for bugs and feature requests.
