### ISSUE TITLE
Hide Empty Time Points in Graph Panel

### ISSUE THREAD

**Issue by jbalooka** [grafana/grafana#12931]
We are having discrete measurements of a System each day (for 8 hours per day). When we day display this continuosly in a Graph Panel we get huge gaps (16 hours) between measurements (See picture).

Is there any option to hide empty time points for a specific interval:

Aka: Hide empty time points if bigger than 16h.
 
![image](https://user-images.githubusercontent.com/17431444/44150177-d57f4f00-a09e-11e8-8d5d-73c054ac2884.png)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Use the null value=null

**Comment by jbalooka** [comment]
We already looked up community pages etc, but could not find anything useful. Please not we do not want to hide series with null values, we want to remove that huge gap in the middle meaning, the time points should be cut out / made non-continuous if there are no timepoints to plot.

The option you mentioned keeps the time points but will display no points for null values

**Comment by marefr** [comment]
I interpreted it as a question and if you can't find a topic on community site we're saying that you should create one. But maybe this isn't a question then after all.

As I understood your report you would like the line between points A and B (the gap) to not be visible. Then you configure the null value=null in Display tab -> Stacking & null value, see http://docs.grafana.org/features/panels/graph/#display-styles. If I misunderstood, please help me understand what you're trying to accomplish.

**Comment by jbalooka** [comment]
I attached an image where I marked the problematic part. That green are should be cut as there are no values there. Again it is nit the series that has to be gone but the whole time range

![Uploading image.png…]()

**Comment by torkelo** [comment]
Grafana graphs show time 24 hour days and 7 day weeks. Periods of missing data are shown as empty.

**Comment by torkelo** [comment]
There is a feature request to configure grafana to hide some hours in graphs (like weekends or off work hours)

**Comment by jbalooka** [comment]
Thank you. Could you please link this as a duplicate of the feature request please. We would like to have exactly the same with the flavor that off-work hours are configurable
