### ISSUE TITLE
Support for custom time deltas in queries?

### ISSUE THREAD

**Issue by PeterGrace** [grafana/grafana#1293]
Hi there!

I have a well-functioning instance of Grafana showing data from our opentsdb data store.

I would really like to build a bar graph that shows multiple time deltas for the same metric.  For instance, I'd like to have a graph that shows "Historical Network Utilization", where I display not only the previous hour's average utilization, but that hour compared to the same hour yesterday, last week, last month, etc.

Is it possible that starttime/endtime could be specified in the individual metric queries?

**Comment by torkelo** [comment]
This is supported already by graphite using graphites timeShift function which allows you to show the same metric or metric expression from to time periods on the same graph. I would prefer if this is handled in OpenTSDB, so maybe open a feature request with them for timeShift support in its query api?
