### ISSUE TITLE
grafana({{alert.title}})

### ISSUE THREAD

**Issue by SARUNAR** [grafana/grafana#12933]
Read
![image](https://user-images.githubusercontent.com/29358331/44169206-f28f1c00-a090-11e8-9cec-866eabeed82a.png)
 before posting: 
![image](https://user-images.githubusercontent.com/29358331/44169302-31bd6d00-a091-11e8-95c4-9b1997075d40.png)
Both, my grafana and Influx is Up and running 
But I am not sure what is the reason for this error?
![image](https://user-images.githubusercontent.com/29358331/44169340-53b6ef80-a091-11e8-9862-2ad12020973d.png)
Please, let me know anyone gone trough this error

**Comment by torkelo** [comment]
Your using a proxy in-front of Grafana? And have a grafana behind a subpath /grafana this requires you to include sub path in root_url setting in ini file (check docs site for more details)

**Comment by SARUNAR** [comment]
root_url = http://127.0.0.1:3000/grafana

**Comment by SARUNAR** [comment]
Still, same error!
![image](https://user-images.githubusercontent.com/29358331/44186580-81bf2280-a0d7-11e8-8120-3d9278d813dc.png)

**Comment by torkelo** [comment]
your auth proxy config must be wrong the request for js & css looks wrong (the url path), are you rewriting the url path or mapping public path somehow?

**Comment by adamdecaf** [comment]
I'm having this same problem. It seems grafana can't handle the `/grafana/` path for assets.

```
t=2018-09-20T02:10:34+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/grafana.dark.css status=404 remote_addr=10.60.2.1 time_ms=2 size=11815 referer=https://infra.moov.io/grafana/
t=2018-09-20T02:10:34+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/app.4f5454f867a0cc2fe8dd.js status=404 remote_addr=10.60.2.1 time_ms=11 size=11815 referer=https://infra.moov.io/grafana/
t=2018-09-20T02:10:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/manifest.4f5454f867a0cc2fe8dd.js status=404 remote_addr=10.60.2.1 time_ms=3 size=11815 referer=https://infra.moov.io/grafana/
t=2018-09-20T02:10:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/vendor.4f5454f867a0cc2fe8dd.js status=404 remote_addr=10.60.2.1 time_ms=7 size=11815 referer=https://infra.moov.io/grafana/
t=2018-09-20T02:10:35+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/app.4f5454f867a0cc2fe8dd.js status=404 remote_addr=10.60.2.1 time_ms=2 size=11815 referer=https://infra.moov.io/grafana/
```

I'm using traefik and [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy) infront of grafana.

**Comment by lhb008** [comment]
I met this problem again.
```t=2019-03-21T08:19:56+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/ status=404 remote_addr=10.185.99.12 time_ms=1 size=13638 referer=```
Any possible fix method? Thanks very much

**Comment by adamdecaf** [comment]
I ended up putting nginx infront of grafana to rewrite `/grafana/`. You can see my configs here https://github.com/moov-io/infra/blob/master/lib/infra/15-grafana.yml
