### ISSUE TITLE
max metric is 15 rows for metric

### ISSUE THREAD

**Issue by huhongbo** [grafana/grafana#1294]
now A-N rows will work fine the 16th metric not working

**Comment by huhongbo** [comment]
but seems it doesn't work , I debug the URL request 
![dntmon_-_esb](https://cloud.githubusercontent.com/assets/1218296/5610149/8df34c34-94ec-11e4-93be-f707caed8a32.png)
still A-N will get the value

**Comment by torkelo** [comment]
@huhongbo I am not sure I understand what is wrong from the image. Please provide more info.

**Comment by huhongbo** [comment]
@torkelo  the 1-15th row the fine, but after 15th row,the target is same , in this pic show "15m.esb_intf_sysid.count.1033.esb_cs_qry_bill_custqry_001.count" 
whatever you add more metric,after 15th target ,the request always using the last row in the rows.
the pic is part of metric config show that after 15m.esb_intf_sysid.count.1033.esb_cs_qry_bill_custqry_001.count  should be 15m.esb_intf_sysid.count.1024.esb_cs_qry_bill_custqry_001.count  then 15m.esb_intf_sysid.count.1025.esb_cs_qry_bill_custqry_001.count
![dntmon_-_esb](https://cloud.githubusercontent.com/assets/1218296/5610358/24bffe2e-94f1-11e4-9385-db7286fda0a6.png)

**Comment by huhongbo** [comment]
@torkelo I find the problem ,
https://github.com/grafana/grafana/blob/master/src/app/features/graphite/datasource.js#L231
here should add more letters

**Comment by torkelo** [comment]
ah, thanks, missed that one, fixed now!
