### ISSUE TITLE
The ability to reference the column name in Table Panel with "Render value as Link"

### ISSUE THREAD

**Issue by Larry57** [grafana/grafana#12941]
Hello,

I need an user to be able to click a table panel cell to switch to another dashboard. So I am using the "Render value as link" feature.

The target dashboard is using two parameters that corresponds to the "row name" and the column name of the clicked cell.

What I call "row name" is actually the first column value, and I can retrieve it using $__cell_0 as a Url parameter to assign it to a variable of the target dashboard.

Unfortunately, there seems to be no way to retrieve the column name the same way, I [read in the community forum](https://community.grafana.com/t/how-to-get-table-panel-column-name-for-specific-cell-value/8977) that this is not supported.

For now, the user select the Row and the Column names in a dashboard variable, and a use a link to switch to the target variable, but it is not convenient.

So here a feature request I hope it will be useful for someone else as well.

**Comment by WhereItsAt** [comment]
+1

**Comment by droidnxs** [comment]
+1 this would be so useful!

**Comment by sacdpathade** [comment]
+1 Any update on same? I am getting dynamic number of columns for which I need setup URL. When I hard code cell number, it doesn't work with dynamic set of columns as grafana doesn't allow us to setup column order for prometheus data. 

it will be very useful if I can refere cell with it's name rather than number.

**Comment by speedygaurav** [comment]
any update on this?

**Comment by luizferreira094** [comment]
+1

**Comment by shukla2009** [comment]
+1
