### ISSUE TITLE
Dashboard: Find dashboards in folders you do not have access to

### ISSUE THREAD

**Issue by volter** [grafana/grafana#12948]
### What Grafana version are you using?

5.2.2

### What did you do?

I'm trying to grant privileges of a single dashboard inside a folder that also contains other dashboards, without grants.

### What was the expected result?

I expected to see that folder on the menu and I expected only that one dashboard to be visible.

### What happened instead?

If I'm not granting anything to the folder, the folder won't show. However, the dashboard is available when sharing the URL. If instead I am granting permissions for the folder, all of the dashboards it contains are visible. That makes sense as more generic rules win, like the documentation says. However, granting access for a single dashboard doesn't make much sense if you can not navigate there.

**Comment by marefr** [comment]
What menu? Could you please include some screenshots which describes your problem and how you've configured your permissions and for what user/team?

**Comment by volter** [comment]
I created a user who' role is set to "Viewer". I created a team ("interested team") and added this user to it.

A folder called "Folder with secret and not quite as secret dashboards" contains certain "not quite as secret" dashboards I want members of the "interested team" to see.

Neither the team nor the user were granted permissions on the folder, as this would gain them access to all of the dashboards. I therefore only granted permissions on the dashboard to the team.

By "menu" I meant the dashboard search (http://docs.grafana.org/reference/search/). It just won't show the folder, although the team has access to a dashboard inside of it.

![screenshot_20180817_105026](https://user-images.githubusercontent.com/1042313/44257724-3313a480-a20d-11e8-8dbe-2cc286aa584b.png)
![screenshot_20180817_105516](https://user-images.githubusercontent.com/1042313/44257726-36a72b80-a20d-11e8-9564-d839a704ddfb.png)
![screenshot_20180817_105736](https://user-images.githubusercontent.com/1042313/44257730-37d85880-a20d-11e8-95f1-0ec1ff3dbecb.png)

**Comment by marefr** [comment]
Thanks @volter 

The first screenshot on top is that when logged in as this new user which is a member of the interested team?

**Comment by volter** [comment]
No, that's just to illustrate what the Administrator can see. The folder is not visible for the team member at all.

**Comment by volter** [comment]
Are you still missing information here?

**Comment by marefr** [comment]
Thanks @volter

**Comment by norbertwnuk** [comment]
The issue is still there in Grafana 6.0.2, Dashboard level permissions do not override Folder level configuration. Cannot effectively make single dashboard public (e.g. Everyone with Viewer role) in private Folder. That contradicts documentation where permission propagation is [described](http://docs.grafana.org/permissions/dashboard_folder_permissions/), it was (somehow) working for us in Grafana 5.3.x - it might indicating regression introduce by some bug-fix / back-porting.
The workaround would be to add View access for Everyone with Viewer role on Folder level, since it does not propagate to dashboard level still can mark dashboards selectively plus have Folder visible for all.

**Comment by norbertwnuk** [comment]
The tweak is already prepared based on the work in: https://github.com/grafana/grafana/issues/10339# (https://github.com/grafana/grafana/issues/10339#issuecomment-482726770)

**Comment by konradgaluszka** [comment]
**Update.** PR solving this is in https://github.com/grafana/grafana/pull/16741.

**Comment by konradgaluszka** [comment]
@torkelo Can this be merged? 
The code doesn't change permissions model much, just lets the folders that contain dashboards accessible to user to be returned in query. Also hides edit  'cog' icon for such folders because it does not make sense to see what is inside. 
thanks

**Comment by jmurraywv** [comment]
Has this been resolved?
