### ISSUE TITLE
add user to org only effect onec when use ldap 

### ISSUE THREAD

**Issue by zhanglp92** [grafana/grafana#12958]
hi all:

when use ldap,  add user to someone org,  why  noly effect onec ?  3Q.

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by xlson** [comment]
@zhanglp92 I'm not sure I understand what you mean, could you explain in a bit more detail?

**Comment by zhanglp92** [comment]
step1: add user to org.  （user from ldap）

![image](https://user-images.githubusercontent.com/6869148/44279906-c12b7180-a285-11e8-9aca-f377390bc0ed.png)

add successful  and switch org.

![image](https://user-images.githubusercontent.com/6869148/44280185-8544dc00-a286-11e8-8d78-233039f7faa3.png)

step2: sign out user and again log in

![image](https://user-images.githubusercontent.com/6869148/44280229-b1f8f380-a286-11e8-9baa-9a995bf7262e.png)

![Uploading image.png…]()

switch org once ？

I have not english , Hard understand,  3Q.

**Comment by torkelo** [comment]
User org membership is controlled via ldap group mapping’s I ldap.toml , if you want to control this manually in grafana you can remove all group mappings in ldap.toml
