### ISSUE TITLE
Weblogic Server With Collectd

### ISSUE THREAD

**Issue by vutukuribharat** [grafana/grafana#12956]
Hi All,

Can any one suggest me the steps for Monitor Weblogic Server with Influxdb(Datasource)+collectd (Agent) and displaying it through Grafana.

Regards,
Bharath
vutukuribharat@gmail.com.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by toni-moreno** [comment]
Hi @vutukuribharat 

We are working with domainhealth-ng ( https://github.com/toni-moreno/domainhealth-ng) sending data in graphite format  ( not yet suporting direct influxdb ) and using basic graphite to influx transformation rules. Working fine in WebLogic 9/10/11.

**Comment by vutukuribharat** [comment]
Hi @toni-moreno 

Right Now we are working only by using Influxdb and Collectd to monitor weblogic server using grafana. Kindly suggest the way how we can procide to monitor the Welogic.

**Comment by toni-moreno** [comment]
@vutukuribharat  ,  you need a new agent with ability to get metrics from Weblogic MBeans , you can use  https://github.com/toni-moreno/domainhealth-ng as I suggest before. You should compile the war and install in your  weblogic domain as described in the README, you should also configure a telegraf with influx output plugin to your inifluxdb and  listener input plugin listening on the 2003  port ( as graphite does) , and configure your graphite 2 influx rules as described in (https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#graphite)

If you have any concrete question about domainhealth please use the https://github.com/toni-moreno/domainhealth-ng issues.
