### ISSUE TITLE
Disable menu option which display onclick panel title

### ISSUE THREAD

**Issue by pavangond** [grafana/grafana#12954]
Onclick of panel title i don't want to display menu options

![grafana1](https://user-images.githubusercontent.com/34574384/44251175-06638b00-a215-11e8-9c69-744e8984ff7d.png)

I don't want to display View, Share and More options

how can i disable that option?

Please help me

**Comment by torkelo** [comment]
Sorry , disabling this menu is not possible.

Why do you want to disable it?

**Comment by pavangond** [comment]
I don't want to show those options to others, It's not valid in our case

users will get confusion by seeing that menu...

Disabling not possible means atleast can i hide it from others.
