### ISSUE TITLE
Series override : allow to disable stack percent option

### ISSUE THREAD

**Issue by cbonte** [grafana/grafana#12963]
Using grafana 5.2.1, the graph panel plugin allows to stack series as percentage.
Series overrides provide an option to disable the stack option for some series, but nothing is provided to disable the *Percent* option, resulting in weird rendering as such series are still taken into account in the percentage calculation.

An option to override the Percent option would be useful.

**Comment by cbonte** [comment]
Hi !
if possible, I'd like this report to be considered as a bug and not a feature request (also in order to change its visibility and to include it in the 5.3.0 release). It affects the rendering of graphs to to a variable which can't be unset once activated globally.
Thanks ;)

**Comment by torkelo** [comment]
a bug, really? It can't be unset? Sure it can its a checkbox in the display options. It's a global panel option, not all graph options have series overrides, how is that a bug?

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature.
