### ISSUE TITLE
Multiple asks for users/password with Basic Auth when `loginPing() /api/login/ping` request goes in race.

### ISSUE THREAD

**Issue by askomorokhov** [grafana/grafana#12979]
### What Grafana version are you using?
Grafana v5.1.3 (commit: v5.1.3) 

### What datasource are you using?

* Ptometheus, MySQL 

### What OS are you running grafana on?

* MacOS 10.13.6 (17G65)

### What did you do?

* Set up Grafana behind nginx as proxy with Base Auth.
* Login with a Base Auth.
* When session expires, and chart refreshing triggers, cancel first user/password prompt.
* Grafana prompt a Base Auth multiple times.

### What was the expected result?

* when session expires - asks user/password only once.

### What happened instead?

* Grafana asks password multiple times.

## Suggested fix
`pkg/middleware/middleware.go:initContextWithBasicAuth` method creates only new session and does not create `grafana_remember` cookie.
`public/app/core/services/backend_srv.ts:loginPing` function goes into race with other requests
 and `pkg/api/login.go:LoginApiPing` returns HTTP Status code 401 Unathorized - this asks password again.

```diff
diff --git a/public/app/core/services/backend_srv.ts b/public/app/core/services/backend_srv.ts
index cc1a8644a..b59d753d8 100644
--- a/public/app/core/services/backend_srv.ts
+++ b/public/app/core/services/backend_srv.ts
@@ -88,6 +88,7 @@ export class BackendSrv {
return results.data;
}, err => {
// handle unauthorized
+ // TODO: add check if `grafana_remember` exists in cookies
if (err.status === 401 && firstAttempt) {
return this.loginPing().then(() => {
options.retry = 1;
@@ -156,6 +157,7 @@ export class BackendSrv {
}

// handle unauthorized for backend requests
+ // TODO: add check if `grafana_remember` exists in cookies
if (requestIsLocal && firstAttempt && err.status === 401) {
return this.loginPing().then(() => {
options.retry = 1;

```

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

```
curl 'http://localhost/graph/api/datasources/proxy/1/api/v1/query_range?query=mysql_global_status_uptime%7Binstance%3D~%22pmm-server%22%7D%20or%20mongodb_mongod_instance_uptime_seconds%20%7Binstance%3D~%22pmm-server%22%7D&start=1534717341&end=1534760541&step=300' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Grafana-Org-Id: 1' -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Authorization: Basic cG1tOjExMTExMQ==' -H 'Connection: keep-alive' -H 'Referer: http://localhost/graph/d/Fxvd1timk/home-dashboard?orgId=1' --compressed


curl 'http://localhost/graph/api/login/ping' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Grafana-Org-Id: 1' -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost/graph/d/Fxvd1timk/home-dashboard?orgId=1' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed

```

**Comment by marefr** [comment]
Would you be interested in open a PR for this?

**Comment by askomorokhov** [comment]
@marefr , I've just open the PR https://github.com/grafana/grafana/pull/13011. Could you please review.

**Comment by bergquist** [comment]
Closing this since we rewrote auth.

**Comment by stvnwrgs** [comment]
@bergquist  This still happens in Grafana 6.7.3.
