### ISSUE TITLE
Implement possibility to add custom keywords highlights in code editor

### ISSUE THREAD

**Issue by RestfulBlue** [grafana/grafana#12975]
Currently, when developing datasource plugin and use code editor, there s no possibility to highlight custom keywords. For example in sql mode all sql keywords are highlighted : select ,where , group , etc. But in datasource we can provide much more keywords. the main part is snippets, like $time, $interval , etc. In other part is custom keys/values for column/fields.  Adding possibility to pass array of keywords to code editor will make it much more interactive when building queryes 

something like this: 
```
<code-editor content="ctrl.target.rawSql" datasource="ctrl.datasource" on change="ctrl.panelCtrl.refresh()" data-mode="sql" additional-keywords="ctrl.keywords" >
</code-editor>
```

**Comment by marefr** [comment]
I'm guessing you have a custom plugin which uses SQL syntax? As an alternative you could implement your own intellisense, here's an example doing exactly that: https://github.com/Vertamedia/clickhouse-grafana

**Comment by RestfulBlue** [comment]
@marefr  thanks!
