### ISSUE TITLE
Add Graphite's cumulative shorthand function 

### ISSUE THREAD

**Issue by mahmoudimus** [grafana/grafana#1297]
cumulative is basically `partial(conslidateBy, consolidationFunc=sum)`

Grafana's `consolidateBy` function: https://github.com/grafana/grafana/blob/0a4ccdcef28866709a150cc0ee0e7bb409ea4d29/src/app/features/graphite/gfunc.js#L213-L224

It would be useful to keep some graphite queries happy by adding a cumulative shorthand, since this is defined in both `Graphite-API` and `Graphite-Web`:

- http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.cumulative
- http://graphite-api.readthedocs.org/en/latest/functions.html#graphite_api.functions.cumulative

Happy to submit a pull request if there's interest.

**Comment by torkelo** [comment]
Added the cumulative function to the function list.

**Comment by mahmoudimus** [comment]
@torkelo woah! thanks! <3
