### ISSUE TITLE
Cannot read property 'datapoints' of undefined while using Mixed datasource

### ISSUE THREAD

**Issue by hariprakashhp5** [grafana/grafana#12977]
### What did you do?
Was trying out Mixed datasource feature of grafana. I had two queries, one with ES as datasource and other with Graphite as datasource. When both the queries are visible, panel is working fine. When i disable ES query leaving the Graphite query visible, panel is throwing "Cannot read property 'datapoints' of undefined" JS Error. In query inspector im able to see success response with datapoints.
![capture](https://user-images.githubusercontent.com/13902282/44331352-e89d5c80-a486-11e8-8475-2d9d6002ebc6.PNG)

### What was the expected result?
Graph should be plotted, with ES query disabled leaving the Graphite query visible.
### What happened instead?
Getting "Cannot read property 'datapoints' of undefined" JS Error.

**Comment by hariprakashhp5** [comment]
Any ETA for the Bug @marefr

**Comment by marefr** [comment]
Currently targeted for 5.4 release, but we may consider fixing this earlier depending on if there are more upvotes/reports on this issue and/or if someone contribute a fix.

**Comment by avnerlavi** [comment]
Has there been any progress on this? @marefr

**Comment by marefr** [comment]
No. Still not that much upvotes/reports of this so we have prioritized other things instead.

**Comment by marefr** [comment]
@avnerlavi had a look at this to identify why it doesn't work as expected. Found the problem and it was easy to fix so have opened a PR #16409.
