### ISSUE TITLE
Grafana/Server Error Okta Authentication 

### ISSUE THREAD

**Issue by smile18** [grafana/grafana#12987]
### What Grafana version are you using? 
Grafana 5.2.2
### What datasource are you using? 
default datasource
### What OS are you running grafana on? 
Windows 10
### What did you do? 
Trying to implement authentication using OAuth2 with Okta, followed instructions given [here](http://docs.grafana.org/installation/configuration/#set-up-oauth2-with-okta) . When I accessed localhost:3000 , it asked to` signin with okta` after clicking on that button it redirected to Okta login page , after successful login to okta it supposed to redirect to Grafana dashboard but I got below error ...

    Grafana / Server Error
    Sadly something went wrong
    login.OAuthLogin(NewTransportWithCode)

    Check the Grafana server logs for the detailed error message.

    t=2018-08-20T16:01:42-0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=[::1] time_ms=8 size=29 referer=
    t=2018-08-20T16:01:46-0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=[::1] time_ms=12 size=321 referer=http://localhost:3000/login
    t=2018-08-20T16:01:49-0700 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 404 Not Found\nResponse: <!DOCTYPE html><html lang=\"en\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/><meta name=\"robots\" content=\"noarchive\"/><meta name=\"googlebot\" content=\"noarchive\"/><meta name=\"robots\" content=\"noindex\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"apple-mobile-web-app-capable\" content=\"yes\"><meta name=\"googlebot\" content=\"noindex\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<meta name=\"robots\" content=\"none\" />\n\n<link href=\"https://op1static.oktacdn.com/assets/img/icons/favicons/favicon-16x16.c55b69ae49b08edc7c000d12b8e5483f.png\" rel=\"icon\" type=\"image/png\" sizes=\"16x16\"/><link href=\"https://op1static.oktacdn.com/assets/img/icons/favicons/favicon-32x32.99bc356b6e293b927f9e3a2b69761c26.png\" rel=\"icon\" type=\"image/png\" sizes=\"32x32\"/><link href=\"https://op1static.oktacdn.com/assets/img/icons/favicons/favicon-96x96.de98828614fa33ca04fcfaa07679f345.png\" rel=\"icon\" type=\"image/png\" sizes=\"96x96\"/><meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n<meta name=\"msapplication-TileImage\" content=\"/img/icons/favicons/ms-icon-144x144.png\">\n<meta name=\"application-name\" content=\"Okta\"/>\n<meta name=\"theme-color\" content=\"#ffffff\">\n<meta name=\"msapplication-config\" content=\"/img/icons/favicons/browserconfig.xml\"/>\n\n<title><OKTA-DOMAIN> - Page Not Found</title>\n<link href=\"https://op1static.oktacdn.com/assets/css/saasure-min.4a95e8413e510585ab12186308c3a732.css\" type=\"text/css\" rel=\"stylesheet\"/><link href=\"https://op1static.oktacdn.com/assets/css/okta.1ac9f2b74d1a03557e998ae8fa9a5b13.css\" type=\"text/css\" rel=\"stylesheet\"/><link href=\"https://op1static.oktacdn.com/assets/css/sections/errors.eff8629aefc46b70f90ae44f20273789.css\" type=\"text/css\" rel=\"stylesheet\"/>\n\n\n\n\n\n<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>\n\n<script>\n    var okta = {\n        migrateMute: true,\n        locale: 'en',\n        debug: false,\n        deployEnv: 'PREVIEW',\n        userId: '',\n        settings: {\n            orgId: '00of8joxuhc7UES0C0h7',\n            orgName: 'TMobile\\x2Ddev\\x2D864159',\n            serverStatus: 'ACTIVE',\n            persona: '',\n            isDeveloperConsole: '' === 'true',\n            isPreview: 'true' === 'true',\n            permissions: []\n        }\n    };\n</script>\n<script>var _features=[\"OKTA_GROUP_PROFILES_V2_WRITES\",\"OKTA_VERIFY_AUTO_PUSH\",\"O365_APP_SIGN_ON_CLIENT_FILTERS\",\"ONPREM_PROVISIONING\",\"FETCH_USER_LOCALE_FROM_UD\",\"PROV_SALESFORCE_COMMUNITY_AND_PORTAL\",\"MAKE_ADMIN_APP_IMPLICIT\",\"OKTA_SCOPED_TOKENS_FOR_AD_AGENTS\",\"DISABLE_NEW_SIGNIN_FLOWS_TOGGLE\",\"NEW_INTERSTITIAL_PAGE\",\"VERIFY_PASSWORD_WHEN_MINTING_OAUTH_TOKEN\",\"NEW_SIGN_IN_MIGRATION\",\"ENG_USE_CACHED_POLICIES_FOR_EVALUATION\",\"FEATURE_HISTORY_PAGE\",\"OKTA_INTERSTITIAL_SETTINGS\",\"AD_FORGOT_PASSWORD\",\"ADMIN_EMAILS_BCC\",\"ASYNC_REPORT_LIST_PAGE_IN_ADMIN_APP\",\"AD_PASSWORD_RESET\",\"CUSTOM_EXPIRED_PASSWORD_FLOW\",\"GROUP_PASSWORD_POLICY\",\"SAML2_SHA2_CERTS\",\"ADVANCED_SSO\",\"UD_ENABLED_APP_ASSIGNMENT_UI\",\"EMAIL_CUSTOMIZATION\",\"SWITCH_TO_FINGERPRINTJS2\",\"BASIC_SSO\",\"USER_MANAGEMENT\",\"CUSTOM_EMAIL_SENDER_SETTINGS\",\"DELETE_AD_DOMAIN_USING_SID\",\"ADMIN_SITE_COOKIE_WITH_HTTPONLY\",\"GROUP_MEMBERSHIP_RULES\",\"PROV_GOOGLE_EMAIL_ALIASES\",\"DEACTIVATE_INACTIVE_USER_FOR_CPC_AND_OPP_APPS\",\"ENFORCE_UPCOMING_RATE_LIMITS\",\"GOOGLE_ENABLE_CUSTOM_SCHEMA_DISCOVERY\",\"PLUGIN_SITEFLOW_OVERRIDES\",\"REMEMBER_DEVICE_BY_DEFAULT\",\"BUY_BUTTON_FOR_ADMIN_APP\",\"GOOGLE_LICENSE_MANAGEMENT\",\"RATE_LIMIT_EARLY_WARNING\",\"ENG_WRITE_DB_EVENTS_ASYNC\",\"LOCATION_NETWORK_ZONES\",\"SKIP_IMPORT_USER_WITHOUT_EXTERNAL_ID\",\"JIRA_USE_REST_FOR_GROUPS\",\"AD_PASSWORD_SYNC\",\"SMS_SERVICE\",\"OKTA_MFA_POLICY\",\"ONE_PAGE_MFA_FACTORS_UI\",\"SAML2_CASB_SUPPORT\",\"CUSTOMIZABLE_ERROR_PAGE\",\"SEND_USER_LOCKED_OUT_EMAIL_TO_RELEVANT_ADMINS_ONLY\",\"ENABLE_PER_USER_RATE_LIMITS\",\"REFERENCE_AND_ENUM_EXPRESSION_LANGUAGE_UI\",\"NETWORK_ZONES\",\"NEW_SIGNIN_FLOWS\",\"CUSTOM_EMAILS_MULTILANGUAGE_TEMPLATES\",\"OUTBOUND_SAML_AUTHN_INSTANT_FIX\",\"DEPROVISIONING_WORKFLOW\",\"SAML_SUPPORT_ARRAY_ATTRIBUTES\",\"SYMANTEC_VIP_FACTOR\",\"PROV_G2M_GETGO_API_URL_ENABLE\",\"MULTIPLE_NETWORK_ZONES\",\"PHONE_CALL_FACTOR\",\"TOUCHID_FOR_OKTA_VERIFY\",\"SWA_SIGNON_ADMIN_SETS_CREDENTIALS\",\"ALLOW_SWA\",\"FAST_MASTER_PRIORITY_FETCH\",\"UD_MAP_FIELD_TO_LOGIN\",\"IMPORT_PASSWORD_HASH\",\"INBOUND_SAML\",\"DEV_CONSOLE\",\"PLUGIN_DISCOVERY_ENDPOINT\",\"PLUGIN_BLOCK_SSO_REQUESTS_VIA_UNTRUSTED_ORGS\",\"ENABLE_DELAUTH_TIMEOUT_TO_CACHE_REDIRECT\",\"USE_INDEXED_MFA_STATE_TOKEN_STORE\",\"MONTHLY_FLAG_2018_08\",\"SELF_SERVICE_REGISTRATION\",\"YUBIKEY_FACTOR\",\"CDN_CONTENT_ENABLED\",\"NEW_EMAILS_TEMPLATES\",\"UD_INBOUND_SAML\",\"MFA_SECURITY_QUESTION_FACTOR\",\"ISV_PORTAL_SSO\",\"OFFICE365_DO_AUTH_ONLY\",\"PROV_DONT_BLOCK_RTS_JOBS_ON_IMPORTS\",\"LDAP_PASSWORD_RESET\",\"TWILIO_MESSAGING_SERVICE_CAPABLE_SMS_API\",\"PLUGIN_VERIFY_CONTENT_SCRIPT\",\"PROV_PAGERDUTY_V2_API\",\"ELEVATE_EDITION_LIMITS\",\"EXTENSIBLE_PROFILE_ENCRYPTION_APP_USER\",\"EXTENSIBLE_PROFILE_ENCRYPTION_RESOURCE_REQUEST\",\"AD_LDAP_FILTER\",\"DISABLE_ASYNCHRONOUS_USER_DELETE\",\"OKTA_VERIFY_FACTOR\",\"ENG_DELETE_APPGROUPS_WITH_DELETED_GROUP_PUSH_MAPPINGS\",\"POLICY_FRAMEWORK\",\"OKTA_VERIFY_FACTOR_WITH_PUSH\",\"CONSOLIDATE_USERNAME_EL\",\"MULTI_AD_DOMAIN\",\"APP_PROFILE_MASTERS\",\"VALIDATE_IDP_SCHEMA\",\"IWA_CUSTOM_ERROR_URL\",\"ENG_UD_ENABLE_LOCALE_VALIDATION\",\"LDAP_PASSWORD_RESET_SMS\",\"USG_EXTERNAL_ORG_ID_KEY\",\"WORKDAY_LAST_DAY_WORKED_ENHANCEMENT\",\"OAN_OIN_TRANSITION\",\"OKTA_GROUP_MEMBERSHIPS_V2_WRITES\",\"SECURID_FACTOR\",\"AUTH_WHITELIST_URLS\",\"EVENTS_API_APPLY_RECENCY_FILTERING\",\"UD_INBOUND_SAML_SHARED_ACS\",\"ENG_GAA_PRECEDENCE_OVER_MAPPING\",\"SEARCH_INDEXER_FRAMEWORK\",\"CREATE_USER_WITH_PASSWORD_UI\",\"AD_ADVANCED_BATCH_IMPORTS\",\"UNRESTRICTED_APP_CREATION\",\"ADMIN_APPS_LIST\",\"MIGRATE_APP_INSTANCE_ENCRYPTION\",\"U2F_AS_A_FACTOR\",\"AD_INSTANCE_DELAUTH\",\"ENG_EVENT_V1_STREAM_ELASTICSEARCH\",\"DEFAULT_ENTITLEMENTS_MAPPING\",\"UD_DEFINE_ENUM_PROPERTIES\",\"DEPRECATE_PASSWORD_HANDLER_USAGE_IN_APP_DEL_AUTH_ENDPOINT\",\"PROV_ULTIPRO_WRITE_BACK_FOR_GLOBAL_EMPLOYEES\",\"TRUSTED_ORIGINS_UI\",\"API_ACCESS_MANAGEMENT\",\"ENG_OKTA_WINDOWS_VERIFY\",\"PLUGIN_NEW_PAGE_MONITORING\",\"SKIP_WRITING_TO_RECENT_ADMIN_ACTIVITY_DB\",\"SOCIAL_AUTH\",\"WINDOWS_HELLO_FACTOR\",\"ENG_DEVICE_TRUST_ADMIN_UI_V2\",\"BATCH_IMPORTS_REFERENCE_COUNT\",\"APP_SIGNON_QUERY_PARAM_FIX\",\"MFA_SOFT_LOCK_FOR_DELAUTH_USERS\",\"ENG_DUPLICATED_APPGROUPS_FIX\",\"SAGE_SAVED_SEARCH\",\"ATTRIBUTE_LEVEL_MASTERING\",\"MFA_SOFT_TOKEN_FACTOR\",\"ENG_ACCOUNT_CHOOSER_PUBLISH\",\"FORGOT_PASSWORD_HONOR_AD_PASSWORD_POLICY\",\"APP_INSTANCE_ADMINISTRATION\",\"CUSTOMIZABLE_SIGN_IN_PAGE\",\"ISV_PORTAL_SSO_SAML_APP\",\"CLOUD_DIRECTORY\",\"DEV_APPS\",\"CUSTOM_URL_DOMAIN\",\"EXTENSIBLE_PROFILE_ENCRYPTION\",\"PENDING_USER_UX_CHANGES\",\"PROFILE_MASTER_USER_LIFECYCLE_SETTINGS\",\"USER_SITE_COOKIE_WITH_HTTPONLY\",\"AD_PROVISIONING\",\"AUTOMATIC_UD_PROFILE_MIGRATION\",\"IN_PRODUCT_HELP\",\"EXTENSIBLE_USER_SEARCH_API\",\"SELF_SERVICE_CONSOLIDATION\",\"GROUPS_UI_BACKBONE_CONVERSION\",\"RADIUS_APP_MODEL\"];</script><script>window.okta || (window.okta = {}); okta.cdnUrlHostname = \"//op1static.oktacdn.com\"; okta.cdnPerformCheck = false;</script><script>window.okta || (window.okta = {});window.okta.mixpanel = true;</script><script src=\"https://op1static.oktacdn.com/assets/js/saasure.min.3ea3d13b0f3dfd9f322b9322f2d97804.js?v=1\" type=\"text/javascript\"></script>\n\n<script>if (window.module) module = window.module;</script>\n\n</head>\n<body id=\"app\" class=\"no-app  \">\n<noscript><div id=\"noscript-mask\"></div><div id=\"noscript-msg\" class=\"infobox infobox-warning infobox-compact\"><span class=\"icon warning-16\"></span><h3>Javascript is disabled on your browser.</h3><p>Please enable Javascript and refresh this page to use Okta.</p></div></noscript>\n\n<div id=\"container\">\n<iframe id=\"download-iframe\" style=\"display: none;\"><p>Your browser does not support iFrames</p></iframe>\n<span class=\"hide\" id=\"_xsrfToken\">null</span><script>\n    function trackAdminHelpEvent() {\n        // Check if OktaMetrics has been initialized and has component,\n        // then tracks the click of global help link in top right of page for appropriate section\n        if (typeof OktaMetrics !== \"undefined\" && OktaMetrics.component) {\n            OktaMetrics.track('Help');\n        }\n    }\n</script>\n\n<div id=\"header\" class=\"clearfix\">\n        <div class=\"primary-nav clearfix\">\n            <div class=\"container primary-nav-wrap\">\n                <div class=\"logo clearfix\">\n                    <a href=\"/admin/dashboard\"><span class=\"icon oktamainlogo\"></span></a>\n                                        </div>\n\n                </div>\n        </div>\n\n        </div>\n\n\n<div id=\"content\" class=\"clearfix\">\n    <div><a href=\"#\" id=\"startcontent\" class=\"skiplink\"></a></div>\n<span class=\"hide\" id=\"error-code\">404</span>\n\n  <div class=\"error-wrap clearfix\">\n    <div class=\"error\">\n      <img src=\"https://op1static.oktacdn.com/assets/img/ui/http-error-404.e21dc7337e238d67a501b4bd3d3c1f42.png\" width=\"340\" height=\"145\" alt=\"404: Page Not Found\"/><p class=\"error-title\">Page Not Found</p>\n    </div>\n    <div class=\"error-content\">\n      <h1>We couldn't find the page you were looking for.</h1>\n      <div class=\"nav-button-bar\">\n        <a class=\"nav-button button-primary\" href=\"/\">Go to Homepage</a>\n      </div>\n    </div>\n  </div>\n\n<span class=\"hide\" id=\"st-app\">NONE</span>\n\n</body>\n</html>\n"
    t=2018-08-20T16:01:49-0700 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=[::1] time_ms=1187 size=1724 referer=

### What was the expected result?
Expected grafana dashboard after successful login to Okta

### What happened instead?
Displayed above error... 

#################################### Generic Okta ##########################
[auth.generic_oauth]
name = Okta
enabled = true
scopes = openid profile email
client_id = <CLIENTID>
client_secret = <Secret>
auth_url = https://XXX.oktapreview.com/oauth2/default/v1/authorize
token_url = https://XXX-admin.oktapreview.com/oauth2/v1/token
api_url = https://XXXX-admin.oktapreview.com/oauth2/v1/userinfo 

#################################### Basic Auth ##########################
[auth.basic]
enabled = false

### Configs Added at Okta Preview Dashboard ...
![image](https://user-images.githubusercontent.com/369752/44372620-af221c80-a499-11e8-8349-86ae6ce35360.png)

### Action taken after reading server logs ...

I have checked chrome browser for javascript enable option and it is enabled so the log is not giving correct information.  

### Why I didn't raise question in Grafana Community ...
I wanted to raise this question in grafana community [here](https://community.grafana.com) but I am always getting Error saying `Login Error .. There is a problem with your account. Please contact the site's administrator.` all other tabs works perfectly after successful login to grafana so I had to raise question here. Thanks.

**Comment by DanCech** [comment]
You need to remove `-admin` from the `token_url` and `api_url` settings in your configuration.
