### ISSUE TITLE
Zabbix datasource shows no data

### ISSUE THREAD

**Issue by maxfactor1** [grafana/grafana#12984]
Grafana Version: grafana-5.2.2-1.x86_64
Datasource: Zabbix (Alexander Zobnin)
OS: RHEL 7

I have two Grafana/Zabbix configurations, one works as expected. The second one I've set up shows no data points, nothing in the group/host drop-down menus. The only major difference between the two configurations is the working setup uses mysql, and the non-working uses postgres.

I have data within Zabbix itself. CPU, IO stats, load, etc. I have 3 test servers in a group, which should show up within Grafana. The datasource is configured correctly as well (I believe).

I've looked at configurations for my working and non-working environment and I really don't see any difference. 

![screen shot 2018-08-20 at 9 53 32 am](https://user-images.githubusercontent.com/10147572/44348038-03f47180-a45f-11e8-9d2c-53f3c8ae3586.png)
![screen shot 2018-08-20 at 9 45 35 am](https://user-images.githubusercontent.com/10147572/44348043-05be3500-a45f-11e8-8b60-7a631bebfb3a.png)

**Comment by maxfactor1** [comment]
![screen shot 2018-08-20 at 9 46 25 am](https://user-images.githubusercontent.com/10147572/44349872-a57dc200-a463-11e8-9c13-76777b6be46e.png)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Or open an issue in the [zabbix plugin repository](https://github.com/alexanderzobnin/grafana-zabbix). 

I would verify that you're using same timezone in postgres as mysql for starters.

**Comment by maxfactor1** [comment]
Just to reply to your comment -- I have had this issue open without reply on the community site for 3 weeks. I assume because no answers there that I may be experiencing a bug. 

I also reached out to Grafana sales to see about purchasing support but have not heard back after our first communications. I am at somewhat of a stand-still with my Grafana installation.

**Comment by marefr** [comment]
Understood. Let us have a look at the issue in the zabbix plugin repository and come back to you there.
