### ISSUE TITLE
InfluxDB templating - empty response causes " a[0] is undefined"

### ISSUE THREAD

**Issue by zzzuzik** [grafana/grafana#1298]
Hi @torkelo,

Is there any chance to handle the empty response from InfluxDB while calculating template variables?

In my case, one of the variables (servers) affects the next queries `count(ip) from merge(/location\.$servers/)` and InfluxDB returns `[]` because there no series with these names.. It causes `a[0] is undefined` in grafana. I'd like to just consider it as '0`

I found a discussion here; 
https://groups.google.com/forum/#!msg/influxdb/N-HU9jMQ46U/3H78S1OoqcwJ
however, it still wasn't resolved in InfluxDB and might take long time due to v0.9

Thank you

**Comment by torkelo** [comment]
I am not sure I understand where the error occurs. Is "count(ip) from merge(/location\.$servers/)" a query for another variable or a query on a graph?

**Comment by zzzuzik** [comment]
It is a query for another variable.

**Comment by torkelo** [comment]
Found it & fixed. 

It will not return 0 as but an empty result (so no options in the variable). Not sure why you have a count() query in a template variable.

**Comment by zzzuzik** [comment]
Thank you @torkelo! I will test it.
Can I somehow get 0? Through regex field? Otherwise, I will try to workaround it in my scripted dashboard logic.

Answering on your question:
This count() in the template variables is related to this question - #1248
@tmonk42  suggestion from there to use graphite-influxdb won't work for me because it requires hardcoded schema, like 10s. However, InfluxDB allows to have variable schema, that why I'd like to use it. 
I went through all its API to find a way to get the same dashboard that I have with Graphite. And I ran into this blocker: https://github.com/influxdb/influxdb/issues/1262
aslo ask it here: https://groups.google.com/forum/#!topic/influxdb/0Xf5lqUd-Os
I didn't get any answer and assumed that everybody is busy with v0.9

So, to make downsampling with $INTERVAL (dynamic "group by time") working in InfluxDB/Grafana, I decided to switch from SUM to MEAN and calculate amount of IP in the variable to multiply them in graphs. In this case I would get almost same numbers like in Graphite.

As always, appreciate your work!

**Comment by torkelo** [comment]
not sure I understand what you use count for still, as a variable to multiply with? sounds very fragile as template variables are not updated when you change the time range. 

And no, [] cannot be converted to zero. Would mess up other scenarios :(

**Comment by zzzuzik** [comment]
Sorry for my vague explanation, here are two examples:

I need to graph the total connection per location or single server, and I need to have downsampling for different $interval. 
There is no groupByNode for InfluxDB. Continues queries don't help because it is scripted/generated dashboards on the fly.

Examples:
I cannot use use the SUM here because of the InfluxDB behavior when SUM is different (multiplied) for different $interval:
```
select SUM(value) from merge(/$location\.$servers\.connections/) 
where $timeFilter group by time($interval) fill(null) order asc
```
but I can use MEAN for (value*IP count) like this:
```
select MEAN(value*$TOTAL_IP) from merge(/$location\.$servers\.connections/) 
where $timeFilter group by time($interval) fill(null) order asc
```
in this case, $TOTAL_IP variable `distinct(count(ip)) from merge(/$location\.$servers\.connections/)` is calculated based on the current user selection, and I will get proper SUM for different $interval

**Comment by timgriffiths** [comment]
@torkelo Could we re-open this one? 

I hitting this now as well, it would be good in the template variable we could specify what to do when a empty result set is returned (which is possible for a query type template variable) and @zzzuzik is correct as soon as influx see the variable name instead of a valid int it will fail all the results sets even if other series queries are valid will fail 

eg. grafana will request
```
http://bjinf13:8086/query?db=pina&epoch=ms&p=grafana&q=SELECT+mean(atmvolatility)+-+0.2776+FROM+volsurface+WHERE+underlying+%3D~+%2FHHI%2F+AND+expirydate+%3D~+%2F2015-11-27%2F+AND+cds+%3D~+%2FAP_HK%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(10s)+order+by+asc%0ASELECT+mean(atmvolatility)+-+0.2750+FROM+volsurface+WHERE+underlying+%3D~+%2FHHI%2F+AND+expirydate+%3D~+%2F2015-12-30%2F+AND+cds+%3D~+%2FAP_HK%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(10s)+order+by+asc%0ASELECT+mean(atmvolatility)+-+$2_HHI_r+FROM+volsurface+WHERE+underlying+%3D~+%2FHHI%2F+AND+expirydate+%3D~+%2F2016-01-28%2F+AND+cds+%3D~+%2FAP_HK%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(10s)+order+by+asc&u=grafana
```
which looks like this
```
q:SELECT mean(atmvolatility) - 0.2776 FROM volsurface WHERE underlying =~ /HHI/ AND expirydate =~ /2015-11-27/ AND cds =~ /AP_HK/ AND time > now() - 6h GROUP BY time(10s) order by asc
SELECT mean(atmvolatility) - 0.2750 FROM volsurface WHERE underlying =~ /HHI/ AND expirydate =~ /2015-12-30/ AND cds =~ /AP_HK/ AND time > now() - 6h GROUP BY time(10s) order by asc
SELECT mean(atmvolatility) - $2_HHI_r FROM volsurface WHERE underlying =~ /HHI/ AND expirydate =~ /2016-01-28/ AND cds =~ /AP_HK/ AND time > now() - 6h GROUP BY time(10s) order by asc
```
and you can see because the very last query is invalid they all will fail with the following error
```
{"error":"error parsing query: found $, expected identifier, string, number, bool at line 3, char 30"}
```
Which i can't see to work around
