### ISSUE TITLE
Custom Legend Ordering

### ISSUE THREAD

**Issue by Jhors2** [grafana/grafana#1299]
Historically I used this feature a lot in Cacti where the legend generated was something I could custom define to group interesting metrics and visualize them better.

Currently I am using InfluxDB as a backend and run a query similar to the following:
select mean(value) from /ipv4.site_1.device_1.ethernet(...|....)\.bps\.in/ where $timeFilter group by time($interval) fill(0) order asc

This returns a lot of interfaces to me in numeric order, however I do have certain interfaces I'd like to consistently group together.  I understand this is possible by making a dashboard for each graph of interest, however it would be nice to be able to do this via a templated dashboard then drag/drop legend items in the order I am interested in and have this reflect in the graph that is drawn.  Ultimately I would save this template graph and the legend ordering would stick.

**Comment by torkelo** [comment]
Good suggestion. But do not think I will implement this any time soon :( 

So many other things to implement :)

**Comment by torkelo** [comment]
series ordering is up to the time series store/query
