### ISSUE TITLE
Boolean value in Graph pannel (InfluxDB)

### ISSUE THREAD

**Issue by EgoVas95** [grafana/grafana#12997]
Grafana version 5.2.1
InfluxDB version 1.7.0

Hello.
There was a question in the display of Boolean variables in the Graph plugin.
Graphics are drawn well, but the values are not displayed in the preview window. I would also like to see the number of true values that is also inaccessible. If any simple trick for this?
 
It's strange that when you plot the data, the data is recognized as 0 and 1, and the rest is not processed.

**Comment by marefr** [comment]
Boolean type casts doesn't seem to be supported by Influxdb, see https://github.com/influxdata/influxdb/issues/5930, so don't think there's anything you can do in Grafana right now to get this to work.

Agree it's strange that boolean values are plotted, but not visible in the legend/tooltips, but graph panel is only suppose to work with numeric/floating points returned from datasource. That boolean values are plotted is probably just a mistake (unexpected feature).

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
