### ISSUE TITLE
Changing the datasource in the explore view erases the query

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#12992]
- type a query
- change data source
- notice query has disappeared

On Grafana v5.3.0-pre1 (775e95b)

**Comment by marefr** [comment]
@tomwilkie this worked before I suppose? We merged a few explore PR's yesterday/today which in that case broke this behavior.

**Comment by tomwilkie** [comment]
I don't recall, it may have always been like this TBH.

**Comment by davkal** [comment]
Nope, still can repro. Prolly side effect of moving `edited` up the component hierarchy.
