### ISSUE TITLE
Document how to do multiplatform builds with Grafana

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#12990]
There should be some documentation regarding how to build Grafana for multiple platforms in the Grafana dev docs.

**Comment by marefr** [comment]
Can we add most of the usage documentation to the build.go? And then refer to that in documenation.

**Comment by xlson** [comment]
@marefr perhaps. At least some of it could probably be added to it. When it comes to cross-platform builds a lot of it isn't the builds as much as the actual build environment, which is something I think we'll have to mention briefly in the docs.

**Comment by oddlittlebird** [comment]
@marcusolsson, @ivanahuckova - Has this been addressed with the new developer guides?

**Comment by ivanahuckova** [comment]
@xlson @marefr do you think that this [Developer guide](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md) is enough and we can close the issue?

**Comment by xlson** [comment]
Yeah, let's close this for now.
