### ISSUE TITLE
Rows are being duplicated in table with Prometheus datasource and 1s time override

### ISSUE THREAD

**Issue by ehashman** [grafana/grafana#13005]
### What Grafana version are you using?

5.2.2

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Using the upstream docker image from Docker Hub

### What did you do?

I have a table that pulls some pod information from Prometheus, which scrapes Kubernetes. It only shows the last 1s of data (in order to reflect the current state).

When I execute the query in Prometheus, a single record is returned by the query. However, in Grafana, the row is displayed twice.

### What was the expected result?

Only one row should be returned in the table. 

### What happened instead?

Two exact duplicate rows were returned in the table, with an identical timestamp.

This was not the case for the same dashboard in Grafana 4.4.3, which I just upgraded the dashboards from.

I have also confirmed that if two rows are returned, four (duplicates of each) is returned, if three rows are returned, all those are duplicated and 6 are displayed, and so on.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I can't actually attach the network responses or screenshots as I can't send that data outside the work network, however, I've viewed the response with Firefox's network inspector and can confirm only a single object was returned from the Prometheus query in the case of one expected row displaying as two duplicates.

### More info

I have some templated variables which were set to a single pod and namespace for this example. Here's the panel JSON with the query I executed:

```json
{
  "columns": [],
  "fontSize": "100%",
  "hideTimeOverride": true,
  "id": 17,
  "links": [],
  "pageSize": null,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "alias": "Time",
      "dateFormat": "YYYY-MM-DD HH:mm:ss.SSS",
      "pattern": "Time",
      "type": "hidden"
    },
    {
      "alias": "Container Host",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "pattern": "instance",
      "thresholds": [],
      "type": "string",
      "unit": "short"
    },
    {
      "alias": "Namespace",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "pattern": "namespace",
      "thresholds": [],
      "type": "string",
      "unit": "short"
    },
    {
      "alias": "Start Time",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "pattern": "Value",
      "thresholds": [],
      "type": "date",
      "unit": "dtdurations"
    },
    {
      "alias": "Container Name",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "pattern": "container_name",
      "thresholds": [],
      "type": "string",
      "unit": "short"
    },
    {
      "unit": "short",
      "type": "hidden",
      "alias": "",
      "decimals": 2,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "colorMode": null,
      "pattern": "/.*/",
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "thresholds": [],
      "mappingType": 1
    }
  ],
  "targets": [
    {
      "expr": "container_start_time_seconds{namespace=~\"^$namespace$\",pod_name=\"$podname\",container_name!=\"POD\"} * 1000",
      "format": "table",
      "intervalFactor": 2,
      "legendFormat": "",
      "metric": "",
      "refId": "A",
      "step": 2
    }
  ],
  "timeFrom": "1s",
  "title": "Pod Info",
  "transform": "table",
  "type": "table",
  "gridPos": {
    "x": 0,
    "y": 1,
    "w": 8,
    "h": 5
  },
  "datasource": null,
  "timeShift": null
}
```

### Anything else

Thanks for taking a look at this!

**Comment by marefr** [comment]
I think you want to enable the instant checkbox for your query. Then the data will be fetch same way as when looking at console view in Prometheus UI.

**Comment by marefr** [comment]
Closing this due to no response. Will consider reopen given more included details.

**Comment by ehashman** [comment]
Confirmed that this solves the issue, however I will need to go back and update every table on our dashboards to turn this on. Is there any sort of mass migrator from Grafana 4 -> 5 to make this easier?

**Comment by marefr** [comment]
@ehashman no, but you may be able to edit the dashboard json model which could make it easier.

**Comment by Akshatce** [comment]
@marefr 
I am also facing same issue of rows duplication in table with Prometheus datasource, and as per your suggestion I have also enabled instant checkbox for the query. But due to this change I am not able to filter out data by date and time which is provided by Grafana UI.

<img width="960" alt="timeIssueGrafana" src="https://user-images.githubusercontent.com/16661809/61846891-7028f200-aec6-11e9-93f4-dc3c040c4fc1.png">

Can you please give any suggestion to achieve time filtration with out rows duplication in table.

Grafana version:   6.2.5V  
DataSource : Prometheus

Let me know if you need any further details is require for this.

**Comment by torkelo** [comment]
What does your query return? Check query inspector , does it return dupes?

**Comment by Akshatce** [comment]
> What does your query return? Check query inspector , does it return dupes?
@torkelo @marefr 
Yes by checking query inspector I can find same data with different timestamp. Please find attached screenshot.

<img width="959" alt="Duplicatedata" src="https://user-images.githubusercontent.com/16661809/61848373-86857c80-aecb-11e9-925b-e2a23db9ecfb.png">

Same Query result in Grafana:
<img width="958" alt="Grafana_Query" src="https://user-images.githubusercontent.com/16661809/61848411-a4eb7800-aecb-11e9-934d-2aacc6f61374.png">

Same Query result in Prometheus:
<img width="959" alt="Prometheus_Query" src="https://user-images.githubusercontent.com/16661809/61848440-b896de80-aecb-11e9-8a1f-9f86b089eb55.png">

**Comment by torkelo** [comment]
I do not see any duplicates in Grafana , every row has unique timestamp. The Prometheus image is not showing the same thing, it shows an instant query where in Grafana you show a range query (time series), very different

**Comment by mazzy89** [comment]
![image](https://user-images.githubusercontent.com/5463218/68604980-e409fd00-04ab-11ea-83e2-4001bf8576ae.png)

I join the discussion here because I'm trying to solve the exact same problem.

I have a scraper that collects metrics with a different timestamp but the same label `updated`.

I would like to avoid to print out a list of duplicated. Now I've tried to use `Instant` but it does not work as expected. 

I was trying to come up with some PromQL query since Promethus is my backend.

**Comment by kcameron1973** [comment]
Trying to list Cert expiry dates from my blackbox exporter I was getting duplicates in the table but found this trick that cleaned things up:
**topk(1,probe_ssl_earliest_cert_expiry *1000) by (app)**

**Comment by CoreForce** [comment]
Joining the discussion as I face metrics reported in duplicates, even when instant is switched on.
Grafana with Prometheus.
