### ISSUE TITLE
[Bug] Alert icons do not display green or red hearts when the panel has a timeshift configured.

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#13009]
### What Grafana version are you using?
v5.2.1

### What did you do?
Added a timeshift to our dashboard:
![screen shot 2018-08-22 at 5 03 02 pm](https://user-images.githubusercontent.com/1459202/44490795-4d92b700-a62d-11e8-95b6-222376541156.png)

### What happened?
While the alerts are still evaluated fine, the heart is forced into the "no data" grey icon regardless of the state the alert is in.

Before adding the timeshift:
![screen shot 2018-08-22 at 5 03 10 pm](https://user-images.githubusercontent.com/1459202/44490796-4d92b700-a62d-11e8-82bf-dcd37c397ffe.png)

After adding the timeshift:
![screen shot 2018-08-22 at 5 03 19 pm](https://user-images.githubusercontent.com/1459202/44490797-4d92b700-a62d-11e8-935c-59c090a20d7f.png)

**Comment by daniellee** [comment]
Not sure if this is a bug. You would see exactly the same thing if you chose a time interval in the past (e.g. 1 week ago - 2 weeks ago). If I remember correctly this was a design decision to prevent confusion - to signal that you are looking at old data and not the data connected to a triggered alert.

The code for this looks if the `to` value in the selected date range is set to `now`:

```
if (options.range.raw.to !== 'now') {
```

As you have only chosen a small timeshift amount then I can see your use case. If you had chosen a 1w instead then I think the design decision to gray out the heart is still logical. 

Any suggestions on how to improve this without causing confusion?

**Comment by calebtote** [comment]
> The code for this looks if the `to` value in the selected date range is set to now:
This isn't my experience actually -- I tried messing around with the alert, and setting the `to` field to `now-5m` or just `-5m` has no effect on the display.
![screen shot 2018-08-23 at 10 35 01 am](https://user-images.githubusercontent.com/1459202/44532055-394bca00-a6c0-11e8-82ad-ebfd1bd06593.png)
Am I doing something wrong for this test?

As for how to improve the design, my expectation was that so long as the alert timeframe was within the rendered graph, the icon would show appropriately. So for example if I have a timeshift on the graph of -5m, and my alert is configured as `query(B,15m,10m)`, the display would reflect that view.

Perhaps separately, the time selection for this is a bit confusing -- the `from` and `to` fields, imo, should reflect relative times: `-1m, -5m, -10m, ... `

**Comment by torkelo** [comment]
The heart on the panel reflects the current (most recent state of the panel) but for that the panel cannot use any time override or timeshift but must use dashboard time range

**Comment by daniellee** [comment]
@calebtote the `to` field refers to the time range for the whole dashboard, not the alert rule.

Don't know what @torkelo thinks but it sounds messy trying to figure out if the current data is contained within a selected time range with a timeshift applied.

**Comment by calebtote** [comment]
At the very least, I think a tooltip or some documentation on this would be useful.
