### ISSUE TITLE
Official armv6 package?

### ISSUE THREAD

**Issue by mati75** [grafana/grafana#13008]
It is possible to provide official armv6 build or/and deb package? Old raspberry pi and 0/0W version have armv6 cpu but arm build is available for armv7 only.

**Comment by daniellee** [comment]
If you don't mind running a slightly older version of Grafana then there is an armv6 build available here for Grafana v5.1.4 (this is the unofficial arm build for Grafana from fg2it that we adapted to be able to do an official build): 

https://github.com/fg2it/grafana-on-raspberry

I think you are the first person to ask for an armv6 build so I will tag this as a feature request and see how many :+1: it gets from the community.

**Comment by rosenstand** [comment]
Would appreciate this as well. I’m using Grafana to do stats on a small solar setup. I need to use a Pi 3 because of the dependency on ARMv7, which means I can run for 3 cloudy days at most. The Pi Zero W would run for a week without sun light.

I suspect most people trying to use the official build on Pi A/B/Zero will not realize why it doesn’t work. Maybe mention it on the downloads page?

**Comment by xoblite** [comment]
Just as a reference, popular data source Prometheus already provides downloads for ARMv6, see [https://prometheus.io/download/](https://prometheus.io/download/), as do many other projects, see e.g. [https://redis.io/topics/ARM](https://redis.io/topics/ARM). Sure, the Pi Zero isn't a crunching powerhouse by any definition of the word, but it's great for a lot of personal projects and prototyping environments. Pretty please? :)

**Comment by tomewarren** [comment]
I have a few Model B Rev 2 PIs I use for a project that uses Grafana. Please provide ARMv6 builds...

**Comment by Majkl578** [comment]
> I think you are the first person to ask for an armv6 build

@daniellee  There is now 21 :+1:s, any chance to reconsider support for ARMv6? I too am looking for a .deb for RPI Zero. Thanks.

**Comment by GitWhoIsThis** [comment]
I would appreciate it to let fix this issue. It took me so many hours before I discovered the cause of the problem.

**Comment by xlson** [comment]
We will add armv6 builds in the near future.

**Comment by xlson** [comment]
Tasks

- [ ] Build and package binaries (no rpm needed)
- [ ] Deploy to grafana.com
- [ ] Build and deploy docker image

**Comment by xlson** [comment]
@DanCech Can you make it possible to add armv6 packages to grafana.com?

**Comment by sweco-seponr** [comment]
@cloph: Can you share such a crafted url? :-)

**Comment by EoleDev** [comment]
Hi, thanks for adding the support to armv6.
But it seems on a rpi zero w, it is an armv6 with armhf architecture. But the armv6 package is built
against armel architecture.
May you add the armhf for armv6?

**Comment by Majkl578** [comment]
I can confirm the problem, the armhf build is not usable on Pi Zero W.
```
Illegal instruction.
```

New issue for that: #15695

**Comment by Marooned-MB** [comment]
Any update on that? I have Model B Rev 2 and spent some time before I ended up here to see why it's not working.
Thanks

**Comment by pskowronek** [comment]
Ping :) Any hope?

**Comment by mati75** [comment]
```grafana-rpi:
  Installed: 7.3.3
  Candidate: 7.3.3
  Version table:
 *** 7.3.3 500
        500 https://packages.grafana.com/oss/deb stable/main armhf Packages
        100 /var/lib/dpkg/status
```
it's works for me

**Comment by pskowronek** [comment]
Yup, deb is probably fine and I will use it. How about docker image? :/

**Comment by oliverpool** [comment]
`sudo apt install grafana-rpi` works perfectly (after adding the repo: https://pimylifeup.com/raspberry-pi-grafana/ )

However it is an older version (7.4.0 - and not 8.3.3)
