### ISSUE TITLE
Grafana doesn't seem to be sending username and password

### ISSUE THREAD

**Issue by ronmb** [grafana/grafana#1300]
I have a Graphite instance with LDAP authentication and a Grafana instance where I include the username and password in the url of the graphite datasource config.js as documented.

Each time I load Grafana the username and password dialog from the browser is always requested. My assumption is by including the username and password in the URL the username and password dialog from the browser would be avoided. 

I know the CORs is setup correctly cause after I enter the username and password the graphs are shown correctly. I'm curious as to why the username and password is still requested even though I include it in the config.js url for the graphite datasource. 

Am I missing a configuration in my Apache web for Graphite?

**Comment by torkelo** [comment]
Does Graphite LDAP authentication use HTTP Basic Auth? the http://username:password@domain:port syntax is only for basic authentication.

**Comment by kamaradclimber** [comment]
@ronmb could you share your apache configuration ? I am interested in having the same setup as yours (ldap auth on graphite, grafana asking for the ldap auth that will be forwarded to graphite).
