### ISSUE TITLE
Execution Error: Could not find datasource Data source not found in provisioned dashboard targeting Prometheus datasource

### ISSUE THREAD

**Issue by LuisLoranca** [grafana/grafana#13004]
Hi All,

I provision a set of dashboards that use a single Prometheus data source.  All the dashboards are set to use the data source instead of "default".  We have several environments each of them running an instance of Grafana + Prometheus.

Sometimes we start getting the error message (especially after a Grafana container restart)

> Execution Error: Could not find datasource Data source not found

In version 5.0 we could fix it performing the following steps:

1. Go to the dashboard hitting the issue.
2. Go to Settings -> Make it editable.
3. Go back to the dashboard and edit the graph that contains the alert.
4. Go to Alert tab and click on "Test Rule" button.
5. Save dashboard.

After a couple of minutes the alert and the rest of the alerts in the dashboard would detect the data source again and start working correctly.  The problem now is for Grafana v5.2.2 there is no way to save a provisioned dashboard, so we can't fix this issue.

Do you know why this might happen in the first place? both Grafana and Prometheus containers are running in the same box.

Grafana Version: 5.0 and 5.2.2
Datasource: Prometheus container
OS: Windows container

Thanks,
Luis

**Comment by marefr** [comment]
Could you please include your datasource provisioning yaml file and one of the dashboards (json model) which creates this error message. Thanks

**Comment by LuisLoranca** [comment]
Please find the datasource provisioning yaml file and one of the dashboards attached.

[Issue_13004.zip](https://github.com/grafana/grafana/files/2319363/Issue_13004.zip)

Please let me know if more information is required.

Thanks,
Luis

**Comment by marefr** [comment]
You have specified same datasource in delete_datasources and datasources. Please remove the delete_datasources section and it should work better
