### ISSUE TITLE
Minor filter dropdown scrolling glitch

### ISSUE THREAD

**Issue by volter** [grafana/grafana#13016]
### What Grafana version are you using?

5.2.2

### What did you do?

1. Add a table widget that has textual data from ES
2. Click the magnifying glass icon to create a filter
3. Click on the filter field that holds the "fields"
4. If there are several fields, a scroll bar will appear. Now click on the slider button of the scroll bar

### What was the expected result?

I expected that I could drag the slider up and down, since it even changes colour (in Firefox), if you mouse over it.

### What happened instead?

The dropdown just disappears. I tried that in Firefox 61, a 50-something Firefox and Chromium 67. It's worth mentioning that the colour does not change on mouse-over in Chromium.

**Comment by marefr** [comment]
Duplicate of #11744
