### ISSUE TITLE
Alert rule time range validation

### ISSUE THREAD

**Issue by adamzoltan** [grafana/grafana#13015]
Grafana will accept the alert to be configured like this query(A,5m,now-5m) but will crash when the query is executed.

Grfana version: 5.2.1
Datasource: AWS ElasticBeanstalk
OS: Linux

**Comment by torkelo** [comment]
unable to replicate this

**Comment by marefr** [comment]
Should be fixed by #14150 since it looks like datasource is CloudWatch.
