### ISSUE TITLE
Allow Setting the Ratio between Graph and Legend

### ISSUE THREAD

**Issue by santiagopoli** [grafana/grafana#13018]
It would be nice to be able to set the height ratio between the Legend and the Graph in Graph Panels. I have a lot of dashboards which show things like "TOP 10 requests by latency" but I can only see the first 4 items (I have to scroll to see the rest) in the legend list. 

If I could set for example a ratio of 40/60 (Graph/Legend) it would be better because we show these dashboards on TV Screens and we can't scroll on the list.

Maybe there is a way to do this already, but I couldn't find it.

What do you think about this feature?

Thanks!

**Comment by torkelo** [comment]
Right now it's at max 30%

**Comment by voiprodrigo** [comment]
This please... On some panels I need to have huge graphs to avoid hiding/scrolling legends with more items than usual. A little more flexibility would be nice, either by ratios or fixed heights. Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
