### ISSUE TITLE
[Bug] Heatmap tooltip with auto decimals not working as expected

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#13019]
### What Grafana version are you using?
v5.2.2 and master (4db480a)
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu
### What did you do?
Created a heatmap graph:
* Prometheus metric with format as heatmap
* Data format time series buckets
* Tooltip decimals set to auto
### What was the expected result?
That the tooltip should show a sane value for the count of bucket when hovered with mouse.
### What happened instead?
For a count of bucket returned from Prometheus as `372` the tooltip shows a count of `372.e+21`. 

If I change tooltip decimals to something between zero and 20 it works as expected, but setting it to auto or 21 yields the unexpected result.

![image](https://user-images.githubusercontent.com/1668778/44536552-0d026e80-a6fd-11e8-83a5-38d54777c560.png)

**Comment by KrisTC** [comment]
This was affecting me too. Although this bug description gives me a work around!

For me I only see this issue in "time series buckets" mode.
Please fix :)

**Comment by torkelo** [comment]
@alexanderzobnin do you have time to investigate this?

**Comment by alexanderzobnin** [comment]
I will take a look.

**Comment by torkelo** [comment]
fix incoming https://github.com/grafana/grafana/pull/16609
