### ISSUE TITLE
Percentage of multiple series in grafana

### ISSUE THREAD

**Issue by aather** [grafana/grafana#1302]
I have four series that I need to calculate percentage:
Example:
A - nonNegativeDerivative(series A)
B -  nonNegativeDerivative(series B)
C - nonNegativeDerivative(series C)
D - nonNegativeDerivative(series D)

I need to do the  following:
%A =  (A / A+B+C+D   x 100) / scaletoSeconds
%B =  (B / A+B+C+D   x 100) / scaletoSeconds
%C =  (C / A+B+C+D   x 100) / scaletoSeconds
%D =  (D / A+B+C+D   x 100) / scaletoSeconds

How to perform this task in grafana editor?

Thanks for any pointer.

Amer.

**Comment by torkelo** [comment]
You could do something like this:
![image](https://cloud.githubusercontent.com/assets/10999/5624994/ba773f9c-9571-11e4-93fd-57a6b43b2b9a.png)

**Comment by torkelo** [comment]
The divideSeries should be #A. #C

**Comment by aather** [comment]
I am getting "Timeseries data request error". Not sure what could be causing it. No value is missing in any of the series.
![percent-series](https://cloud.githubusercontent.com/assets/5282686/5625748/b175e4d4-9535-11e4-8a63-5babeff709a1.png)

**Comment by torkelo** [comment]
@aather  nonNegativeDerivate function does not take a string parameter, only an optional maxValue parameter (defaults to none)

http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.nonNegativeDerivative

**Comment by semutter** [comment]
I am using grafana v2.0.2, and cannot see such buttons in my grafana web app, may I ask which version of grafana supports this feature

**Comment by torkelo** [comment]
What button?

**Comment by namanjain1993** [comment]
when do i put this divideseries query ??
I am using grafana on opentsdb

**Comment by torkelo** [comment]
OpenTSDB does not have such a query function

**Comment by namanjain1993** [comment]
Would it be possible to get percentage using two queries (Success/Total) ?
For Success- 1 query
For Total - 1 query
This time we need it from elasticsearch queries from grafana.

**Comment by CookieMaya** [comment]
Would it be possible to get percentage using two queries (Success/Total) ?
For Success- 1 query
For Total - 1 query
This time we need it from elasticsearch queries from grafana.

**Comment by daniellee** [comment]
@CookieMaya maybe this would work: https://community.grafana.com/t/basic-elastic-search-query/1543/4
