### ISSUE TITLE
Dashboard provisioning error:  "Dashboard title cannot be empty"

### ISSUE THREAD

**Issue by mottati** [grafana/grafana#13029]
I am attempting to provision dashboards on Grafana Docker container so that they come up when the container is started. 

For simple demonstration purposes, I have reproduced this problem and put the example up on GitHub. The project is here: https://github.com/mottati/grafana-no-title-bug

This uses the 5.2.2 Docker container and attempts to load a single dashboard. When the container
comes up, I get the following message in my container log.

```
grafana_1  | t=2018-08-24T21:01:28+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file="/Dashboards/Main Org./this-is-a-title.json" error="Dashboard title cannot be empty"
```

The json file being loaded has a title which can be seen here, [on line 158](https://github.com/mottati/grafana-no-title-bug/blob/master/Dashboards/Main%20Org./this-dashboard-has-a-title.json#L158
).

This can be reproduced with the following steps:

- git clone https://github.com/mottati/grafana-no-title-bug.git
- cd grafana-no-title-bug/
- docker-compose up 

```
AUTOCHOOSEEARN:z-temp michael.ottati$ cd grafana-no-title-bug/
AUTOCHOOSEEARN:grafana-no-title-bug michael.ottati$ docker-compose up
Recreating grafana-no-title-bug_grafana_1 ... done
Attaching to grafana-no-title-bug_grafana_1
grafana_1  | t=2018-08-24T21:37:48+0000 lvl=info msg="Starting Grafana" logger=server version=5.2.2 commit=aeaf7b2 compiled=2018-07-25T11:17:28+0000

<REDACTED STARTUP LOG > 

grafana_1  | t=2018-08-24T21:37:50+0000 lvl=info msg="Initializing Stream Manager"
grafana_1  | t=2018-08-24T21:37:50+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file="/Dashboards/Main Org./this-dashboard-has-a-title.json" error="Dashboard title cannot be empty"
grafana_1  | t=2018-08-24T21:37:50+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
grafana_1  | t=2018-08-24T21:37:53+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file="/Dashboards/Main Org./this-dashboard-has-a-title.json" error="Dashboard title cannot be empty"
grafana_1  | t=2018-08-24T21:37:56+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file="/Dashboards/Main Org./this-dashboard-has-a-title.json" error="Dashboard title cannot be empty"

```

**Comment by mottati** [comment]
I played around with this a little more. Here is what I believe I have found. I used the following article and git repo to compare:

https://ops.tips/blog/initialize-grafana-with-preconfigured-dashboards/#configuring-grafana
https://github.com/cirocosta/sample-grafana

I was trying to do "round tripping" e.g. creating the dashboard, exporting to a file system, then importing it back. In the process of round tripping, I get these extra json "meta" block that appears confuse the importer:  https://github.com/mottati/grafana-no-title-bug/blob/master/Dashboards/Main%20Org./this-dashboard-has-a-title.json#L2-L23

When I take the "meta" section out, and delete the extra closing bracket at the end, the dashboard imports fine. 

For being able to do "round trip" development, it would be nicer to be able to import exactly the same bits that are retrieved from an export. The way it appears to be working now is that the bits that are retrieved form an export would first have to be modified prior to the next import. 

In my fantasy world, I would love to be able to provide Grafana with a Git URL and Grafana would use Git as its persistence store for dashboards.

**Comment by torkelo** [comment]
export ? the meta section is not included in the view json or save modal (for provisioned dashboards will show you json). The meta section is only returned by the api to inform the UI about dashboard permissions if the current user has saved dashboard or not etc. It's not for saving / importing

**Comment by mottati** [comment]
Thank you. 

I have found my issue however it is a bit subtle so I will document it here.

The following line is suitable for exporting a dashboard to be recreated else where using the REST API.

```
curl -k -u admin:admin "${GRAFANA_URL}/api/dashboards/${dash}" | jq '.dashboard.id = null'  > "$DB$EXTENSION 
```

To make the file suitable for the provisioning one must filter out only the dashboard portion of the JSON. The line would therefore change to: 

```
curl -k -u admin:admin "${GRAFANA_URL}/api/dashboards/${dash}" | jq '.dashboard.id = null' | jq '.dashboard' > "$DB$EXTENSION"
```

Doubtless there is a more elegant way to write this with a single invocation of jq.

The source of my confusion was that the file format allowed by the REST API is slightly more permissive and allows the meta section to be passed in.

**Comment by simonmiller99** [comment]
subtle it may be , but I do think you are correct and I thank you for posting it as I've been labouring under this one myself.

**Comment by raul1991** [comment]
> `curl -k -u admin:admin "${GRAFANA_URL}/api/dashboards/${dash}" | jq '.dashboard.id = null' | jq '.dashboard' > "$DB$EXTENSION"`

Thanks for your answer. :)
Just a heads up for anyone with the latest grafana version, use /api/dashboards/uid/${dash}

**Comment by inkdude** [comment]
> 
> 
> Thank you.
> 
> I have found my issue however it is a bit subtle so I will document it here.
> 
> The following line is suitable for exporting a dashboard to be recreated else where using the REST API.
> 
> ```
> curl -k -u admin:admin "${GRAFANA_URL}/api/dashboards/${dash}" | jq '.dashboard.id = null'  > "$DB$EXTENSION 
> ```
> 
> To make the file suitable for the provisioning one must filter out only the dashboard portion of the JSON. The line would therefore change to:
> 
> ```
> curl -k -u admin:admin "${GRAFANA_URL}/api/dashboards/${dash}" | jq '.dashboard.id = null' | jq '.dashboard' > "$DB$EXTENSION"
> ```
> 
> Doubtless there is a more elegant way to write this with a single invocation of jq.
> 
> The source of my confusion was that the file format allowed by the REST API is slightly more permissive and allows the meta section to be passed in.

Thank you very much!

**Comment by shermanericts** [comment]
This was a lifesaver today.  I'm new to the prom stack so just recently saw this.  Thank you!
