### ISSUE TITLE
Alert query condition doesn't apply properly 

### ISSUE THREAD

**Issue by adamzoltan** [grafana/grafana#13023]
When using certain namespaces the alert query doesn't ignore the data from the selected timerange. 

Namespace: AWS/ApplicationELB Metric: RequestCount

Alert Config:
WHEN sum () OF query (A, 10m, now) IS ABOVE 80000
Test Rule:
message:"Condition[0]: Eval: false, Metric: ALB Request Count - Provider UAA, Value: 56758.000"

Alert Config:
WHEN sum () OF query (A, 10m, now-4m) IS ABOVE 80000
Test Rule:
message:"Condition[0]: Eval: false, Metric: ALB Request Count - Provider UAA, Value: 57351.000"

Alert Config:
WHEN sum () OF query (A, 10m, now-8m) IS ABOVE 80000
Test Rule:
message:"Condition[0]: Eval: false, Metric: ALB Request Count - Provider UAA, Value: 57351.000"

Data is received in every minute.

Grafana version: 5.2.1
Datasource: AWS
OS: Linux

**Comment by marefr** [comment]
I'm not sure I understand your reported problem. 

Have you configured a query to get AWS/ApplicationELB Metric: RequestCount, please include metric screenshot? 

And then you've created an alert rule which you're testing - Have you saved the dashboard before testing it?

**Comment by marefr** [comment]
Closing this due to no response. Will consider reopen given more details included.
