### ISSUE TITLE
Grafana crashes on Android devices

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#13020]
What Grafana version are you using? 5.2.2
What datasource are you using? Influxdb
What OS are you running grafana on? Debian (Armbian on Orange Pi Zero 512MB)

After a few hours the browser on Android devices crashes (it says something like “can’t load site”). I’m testing it on 2 devices and on different browsers. I think this problem doesn’t appear on Windows. I’ve tried connecting Orange Pi Zero via WiFi and Ethernet, but the problem is the same in both situations. Autorefresh in Grafana is set to 10sec.

After reloading the site in browser everything is ok.

**Comment by marefr** [comment]
There can be a lot of reasons for this. Impossible for us to help you without any details/traces/logs. There's an open bug report #12782 which may be the same problem you've experiencing?

As a workaround you may be able to use a playlist with your dashboard and play that. This should work better since playlist will do full page reloads from time to time. Other workaround would be to install some browser extension that reloads the site.

**Comment by szerwi** [comment]
@marefr Ok, I will try playlist, thank you. Is it possible to automatically start playlist after opening the Grafana?

**Comment by marefr** [comment]
@szerwi yes given you open Grafana with certain link. When you've created your playlist and look at playlist list (http://localhost:3000/playlists) there's a start url column that gives you the url to use for playing the playlist and/or clicking on the button Play. You could also enable kiosk mode for the playlist, see http://docs.grafana.org/reference/playlist/#linking-to-the-playlist-in-kiosk-mode.

**Comment by szerwi** [comment]
@marefr I saw that grafana exits Playlist mode when changing time range. Is there any way to prevent from doing this?

**Comment by marefr** [comment]
@szerwi No. But I got the impression that you were displaying a dashboard on a TV screen and didn't have a need to change dashboard configuration. When using playlist you'll have to update dashboard with different time range and save and then playing playlist will show the new timerange. Are you using your Orange Pi Zero as a desktop?

**Comment by szerwi** [comment]
No, Orange Pi Zero is only a server. I display the page on Android tablet. I thought I would be able to change time ranges fast, without need of exiting playlist.

**Comment by marefr** [comment]
Okay. Then playlist is probably not the best workaround for you.

**Comment by szerwi** [comment]
I can live without it :D It is working for a few hours now without crash, so I think playlist solved my problem :Da

**Comment by marefr** [comment]
Cool. Closing this for now then in favor of #12782

**Comment by szerwi** [comment]
@marefr one more question. Is it possible to set absolute time range in Singlestat panel? I would like to reset the measurement at 12pm every day, but it's showing last 24 hours from now. Is it possible to change it?

**Comment by marefr** [comment]
No, that's not supported.

**Comment by szerwi** [comment]
@marefr ok, thank you. And one more question :D How to check how many users are currently connected to the Grafana or watching certain dashboard?

**Comment by marefr** [comment]
There's no support in Grafana to see how many user "are active now". There's some stats in Configuration -> Server Admin -> Stats where you could see active users last 30 days.

If you would like to know the usage activity of dashboard we recommend that you enable [router_logging](http://docs.grafana.org/installation/configuration/#router-logging) and ingest the log files to some other medium where you can analyse them. Other alternative would be to enable [Google Analytics](http://docs.grafana.org/installation/configuration/#analytics).

**Comment by szerwi** [comment]
@marefr ok, thank you. Do you know if there is any command in Linux to show current http requests?

**Comment by marefr** [comment]
`tail /path/to/logfile`

Suggest you from now on asking questions on our community site and/or finding existing answers to your questions.
