### ISSUE TITLE
Can't query data when there is slash in the measurements

### ISSUE THREAD

**Issue by smalenfant** [grafana/grafana#13028]
Please include this information:
### What Grafana version are you using? 

4.6.2

### What datasource are you using?

InfluxDB

### What OS are you running grafana on? 

Centos/containers

### What did you do? 

We are using Juniper OpenConfig telegraf plugin to stream telemetry, the measurement and the fields have "/" in them. 

### What was the expected result?

Being able to query measurements and fields when there is "/" in them.

### What happened instead?

Can't retrieve fields.

### If related to metric query / data viz:

`SELECT mean("value") FROM /junos/system/linecard/interface/ WHERE time >= now() - 6h GROUP BY time(15s) fill(null)`

Specifying the following in the "custom query works":

`SELECT mean("/interfaces/interface/state/counters/in-octets") FROM "/junos/system/linecard/interface/" WHERE $timeFilter GROUP BY time($__interval) fill(null)`

**Comment by torkelo** [comment]
because your measurement starts with `/` and ends with `/` Grafana (& InfluxDB) think it's a regex and will not quote it (as that will not work).  If it only had `/` in the middle it would be quoted.

**Comment by smalenfant** [comment]
@torkelo Does grafana uses regex for measurements or values anywhere? I use it during "WHERE" statements but never to select the data in the first place. What would it take to "quote" both measurements and fields for the selection as this would probably fix it.

This works fine in Chronograf. This data being ingested in InfluxDB comes from OpenConfig/gRPC.

The input looks like the following. Is there anything that we could modify so it would work with Grafana?

```
{"fields":{"/interfaces/interface/init_time":1533910513,"/interfaces/interface/state/counters/carrier-transitions":1,"/interfaces/interface/state/counters/in-multicast-pkts":9465611,"/interfaces/interface/state/counters/in-octets":726213210,"/interfaces/interface/state/counters/in-pkts":9465635,"/interfaces/interface/state/counters/in-unicast-pkts":27,"/interfaces/interface/state/counters/out-broadcast-pkts":957,"/interfaces/interface/state/counters/out-multicast-pkts":10253678,"/interfaces/interface/state/counters/out-octets":302237717230,"/interfaces/interface/state/counters/out-pkts":333472644,"/interfaces/interface/state/counters/out-unicast-pkts":332616764,"/interfaces/interface/state/high-speed":100000,"/interfaces/interface/state/last-change":491007,"/interfaces/interface/state/oper-status":"UP","/interfaces/interface/state/parent_ae_name":"ae34","_component_id":0,"_sequence":713119,"_subcomponent_id":0,"_timestamp":1536080074781},"name":"/junos/system/linecard/interface/","tags":{"/interfaces/interface/@name":"et-0/0/10","device":"174.68.232.53","host":"test","path":"sensor_1000:/junos/system/linecard/interface/:/junos/system/linecard/interface/:PFE","system_id":"BLANK"},"timestamp":1536083160}
```
