### ISSUE TITLE
Make grafana_remember cookie more secure

### ISSUE THREAD

**Issue by lowleveldesign** [grafana/grafana#13032]
It's not really an issue, but rather a suggestion to make the "super secure cookie" more secure. Currently, the **grafana_remember** cookie contains only an encrypted value of a username, which implies that if an attacker steals it from a legitimate user, he/she will be able to authenticate forever. 

My proposition is to create the encryption payload by combining the username with the cookie expiration date. When the cookie expiration date differs from the encrypted value, you will be able to detect tampering and reject such a request. It might be a good idea to also add a version information so you will be able to add new fields in the future. The values in the cookie could be separated by a character forbidden in the username, so (at least for a while) you will be able to detect cookies in an old format and serve them (if backward compatibility is necessary here, of course).

Scope of this change: **login.go**

```go
func tryLoginUsingRememberCookie(c *m.ReqContext) bool {
...
        // validate remember me cookie
        if val, _ := c.GetSuperSecureCookie(user.Rands+user.Password, setting.CookieRememberName); val != user.Login {
return false
        }
...
}
```

```go
func loginUserWithUser(user *m.User, c *m.ReqContext) {
...
        if days > 0 {
c.SetCookie(setting.CookieUserName, user.Login, days, setting.AppSubUrl+"/")
c.SetSuperSecureCookie(user.Rands+user.Password, setting.CookieRememberName, user.Login, days, setting.AppSubUrl+"/")
        }
...
}
```

**Comment by torkelo** [comment]
We are reworking the session store (using session cookie store) and replacing the remember me cookie with an auth token cookie that will also have a stored database entry in an auth token table. But the design for this is not fully fleshed out yet (just started). But your idea is a good one, will leave it open until we figured out how to replace the remember me cookie (hopefully this work will get into v5.4 )

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/7741

**Comment by marefr** [comment]
In #15303 we're replacing the remember me cookie solution with a short-lived token solution. Closing this.
