### ISSUE TITLE
Add ad-hoc filter from the table panel works incorrectly with empty values and values with commas

### ISSUE THREAD

**Issue by AntonSmolkov** [grafana/grafana#13038]
### What Grafana version are you using?
Grafana v5.2.2 (aeaf7b2)

### What datasource are you using?
Elasticsearch 5.6.10(b727a60, lucene_version:6.6.1)

### What OS are you running grafana on?
Debian GNU/Linux 9 (stretch)

### What did you do?
Used table panel with **Metric: raw document** and T**able Transform: JSON data** and loupe sign to  [construct ad-hoc filter](http://docs.grafana.org/guides/whats-new-in-v4-5/#elasticsearch-add-ad-hoc-filters-from-the-table-panel)

### What was the expected result?
Appropriate result on dashboards graph and table

### What happened instead?
Data from dashboard's graph and table disappearing with exception message.

**Filter for an empty value:**
[Screen record](http://recordit.co/n8IynMKkk9)

[Request and response from chrome dev tools](https://github.com/grafana/grafana/files/2322932/empty_request_response.txt)

Looks like grafana construnts incorrect filter for elasticsearch ` exception: ""` instead of ` !(_exists_:"exception")`

**Filter for a value with colon:**
[Screen record](http://recordit.co/39GhrsIohD)

[Request and response from chrome dev tools](https://github.com/grafana/grafana/files/2322933/colon_request_responce.txt)

Not sure, but looks like grafana try to divide text field with commas to separate fields and filter them all  at once

**Comment by marefr** [comment]
Thanks for the excellent bug report. I wish all out bug reports was this detailed

**Comment by marefr** [comment]
@AnSmol Had a quick look at this, but think this has probably never worked as you'd expect. Therefore would like some more feedback.

What ES query would you expect to happen when adding ad hoc filter for empty value, the following:
```
{ 
  must: [
    { match_phrase: { exception: { query: "" } } }
  ]
}
```

What ES query would you expect to happen when adding ad hoc filter for array value, the following:
```
{ 
  must: [
    { match_phrase: { tags: { query: "beats_input_codec_plain_applied" } } },
    { match_phrase: { tags: { query: "aggregated" } } },
    { match_phrase: { tags: { query: "_grok_postfix_success" } } },
  ]
}
```

**Comment by aocenas** [comment]
@AntonSmolkov closing this for now as there was no additional information and it isn't clear what should happen in the cases you mentioned. Please reopen with additional information if this is still relevant for you.
