### ISSUE TITLE
Support dynamic height of panels when rendering server side pngs 

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#13037]
Please include this information:
### What Grafana version are you using?
5.2.2
### What did you do?
Share a text panel via "Direct link rendered image". Either omit the `width` and `height` query parameters, or make the `height` smaller than needed to display all the text content. 
### What was the expected result?
The rendered image should dynamically increase height to be able to contain all the text. This was the behaviour in Grafana 4.6
### What happened instead?
If a `height` is specified and the text does not fit, the remaining text is cut off. If no `height` is specified it renders at a fixed 400px height. 

This is releated to https://github.com/IzakMarais/reporter/issues/52 and https://github.com/IzakMarais/reporter/issues/80. 

A workaround for this problem might be to try to infer the `width` and `height` query parameters from the dashboard panel JSON definition. However, the `w` and `h` JSON fields are not in pixels but rather resemble a Bootstrap-like grid unit size.

**Comment by torkelo** [comment]
this is not easy to support (at least for some panels), given how the new grid layout work and the panel dimension constraints it imposes. 
https://github.com/grafana/grafana/issues/10325

So unless this is a very popular request it won't be a high prio issue for some time.

**Comment by IzakMarais** [comment]
The reporter has worked around this by using the `gridPos` sizes in the grafana dashboard JSON to determine the panel width and heights to request. You are welcome to close this.
