### ISSUE TITLE
grafana alerting do not support  opentsdb scientific notation

### ISSUE THREAD

**Issue by superbool** [grafana/grafana#13048]
Grafana v5.2.1 
database opentsdb 2.3
When use grafana alerting appear error:
```
t=2018-08-28T10:44:01+0800 lvl=info msg="Failed to unmarshal opentsdb response" logger=tsdb.opentsdb error="json: cannot unmarshal string into Go value of type float64" status="200 OK" body="[{\"metric\":\"jvm_memory_used\",\"tags\":{\"app\":\"metrics-server\",\"host\":\"172.18.0.1\"},\"aggregateTags\":[],\"dps\":{\"1535424000\":4.15166544E8,\"1535424060\":4.42432368E8,\"1535424120\":6.49027712E8,\"1535424180\":6.25484448E8,\"1535424240\":\"NaN\"}}]"
t=2018-08-28T10:44:01+0800 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="jvm_memory_used alert" error="tsdb.HandleRequest() error json: cannot unmarshal string into Go value of type float64" changing state to=alerting
```
I notice opentsdb return value  scientific notation,but grafana make is float, is it a bug? 
How can I solve it?

**Comment by superbool** [comment]
@marefr sorry when I tested  I found that is not the problem. The really problem is the last value '\"1535424240\":\"NaN\"' . NaN is not a json format. So the error is 'cannot unmarshal string into float64',because I config Down sample like:
![image](https://user-images.githubusercontent.com/8575470/44715977-b8d7ff80-aaeb-11e8-8e52-fe39d2563552.png)
fill nan ,so opentsdb return 'NaN',fill other value is ok.
So the pull request is alse wrong, you can close it.
https://github.com/grafana/grafana/pull/13049

**Comment by marefr** [comment]
Do you want to close this issue as well?
