### ISSUE TITLE
Lodash 'remove' function wrongly overrided

### ISSUE THREAD

**Issue by 6y5t4r** [grafana/grafana#1304]
In app\components\lodash.extended.js, the 'remove' function is overrided in a way to contradicts the default behavior of lodash.
From what I've seen, this looks like a left over from the days you've used underscore, but it should now be removed, it prevents using 'remove' correctly. (in fact, the code that uses it in app\services\alertSrv.js probably doesn't work as you expect it too...)
The solution is simple - remove the override.

**Comment by torkelo** [comment]
Thanks for informing me, I think the alertSrv code worked but anyway bad practice to override the default implementation in this case. I cleaned up the code in alertSrv as well, it was messy.
