### ISSUE TITLE
[Bug] Dashboard links list should be unique

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#13044]
### What Grafana version are you using?
v5.2.1

### What did you do?

- Have a dashboard, `Linked`, with tags: `a`, `b`, `c`
- Have another dashboard, `Test`, with two sets of dashboard tags to link: `a`,`b` & `a`,`c`

### What was the expected result?
- `Test` dashboard would have a link to `Linked`, once

### What happened instead?
- Because `Linked` matches both sets of tags, it's added to the linked dashboards list multiple times

**Comment by torkelo** [comment]
> Have another dashboard, Test, with two sets of dashboard tags to link: a,b & a,c 

Can you show details here? Do you have two links defined? One with tag filter a & b, and another link with a & c ?

**Comment by torkelo** [comment]
I guess the dashboard link option ”as dropdown” is not used and each dashboard hit gets its own link ?

**Comment by calebtote** [comment]
Correct, we don't use the dropdown option. I've included a screenshot of a test:
![screen shot 2018-08-28 at 3 03 14 pm](https://user-images.githubusercontent.com/1459202/44744629-920dcf00-aad3-11e8-86b6-c2b8877059ef.png)

**Comment by marefr** [comment]
Thank you @calebtote for the additional information.
