### ISSUE TITLE
API: datasources PUT breaks datasource edit UI

### ISSUE THREAD

**Issue by TimSimmons** [grafana/grafana#13046]
### What Grafana version are you using?

v5.2.2

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Linux (in Kubernetes)

### What did you do?

Use http://docs.grafana.org/http_api/data_source/#update-an-existing-data-source to update a datasource URL.

1. Created a new datasource with a working Prometheus url
2. I performed a GET /api/datasources/id
3. Substituted the URL to a new URL that also worked and performed a PUT /api/datasources/id with the slightly modified HTTP body.
4. Viewed /datasources/edit/id

### What was the expected result?

The URL would be updated, and the datasource would continue working as it would have otherwise.

### What happened instead?

The datasource continued to work in dashboards, however it broke in the datasource edit UI, making it unchangeable by hand in the future.

Before:
![before](https://i.imgur.com/Z7MVbvg.png)

After:
![after](https://i.imgur.com/wwgD7b9.png)

**Comment by marefr** [comment]
Please include the request json body used in PUT /api/datasources/id. Replace any sensitive information.

**Comment by TimSimmons** [comment]
I took the body from a `GET /api/datasources/<id>` and changed the URL and did the `PUT /api/datsources/<id>`.
```
{
  "id": 498,
  "orgId": 1,
  "name": "temporary boi",
  "type": "prometheus",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://mynewurl.com",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "secureJsonFields": {},
  "version": 1,
  "readOnly": false
}
```

**Comment by marefr** [comment]
I did as well, but was not able to reproduce it. But when removing the jsonData property I could.

Please include at least 

```json
"jsonData": {
    "httpMethod": "GET"
```

I'm guessing that you've upgraded from an earlier Grafana version that didn't have the HTTP Method feature.

**Comment by TimSimmons** [comment]
I have upgraded from an old version of Grafana, but I created the datasource in question here in v5.2.2. I just created it again, and this was the json that my script sent back:
```
{u'readOnly': False, u'name': u'temporary boi 2', u'database': u'', u'url': u'http://url', u'basicAuth': False, u'jsonData': {u'httpMethod': u'GET', u'keepCookies': []}, u'access': u'proxy', u'isDefault': False, u'typeLogoUrl': u'', u'orgId': 1, u'user': u'', u'version': 1, u'basicAuthUser': u'', u'secureJsonFields': {}, u'password': u'', u'type': u'prometheus', u'id': 499, u'basicAuthPassword': u'', u'withCredentials': False}
```
the `jsonData` bit is there.

I tried to do it by hand with curl, I created a new data source, pulled the data from the API, and then changed the url and tried to repost and got this:
```
$ curl -L grafana.../api/datasources/500 -X PUT --data '{
  "id": 500,
  "orgId": 1,
  "name": "grafanapls",
  "type": "prometheus",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://newurl.com",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "httpMethod": "GET",
    "keepCookies": []
  },
  "secureJsonFields": {},
  "version": 2,
  "readOnly": false
}' -H 'content-type: application/json' -H 'accept: application/json'

[{"fieldNames":["Name"],"classification":"RequiredError","message":"Required"},{"fieldNames":["Type"],"classification":"RequiredError","message":"Required"},{"fieldNames":["Access"],"classification":"RequiredError","message":"Required"}]
```

So that's even different, I must be doing something horribly wrong, I understand if you don't have time to figure that out, but it just seemed odd to me.

**Comment by marefr** [comment]
Works without problem for me using Grafana 5.3-pre1 (master).

```curl
curl -X PUT \
  http://localhost:3000/api/datasources/6 \
  -H 'Authorization: Basic <secret>' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": 6,
  "orgId": 1,
  "name": "Prometheus",
  "type": "prometheus",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://localhost:9090",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "httpMethod": "GET",
    "keepCookies": []
  },
  "secureJsonFields": {
    
  },
  "version": 13,
  "readOnly": false
}'
```
