### ISSUE TITLE
LDAP group doesn't get grafana_admin

### ISSUE THREAD

**Issue by vasrem** [grafana/grafana#13052]
### What Grafana version are you using?
v5.2.1
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
CentOS ( Docker image at Kubernetes Cluster)
### What did you do?
I have set up LDAP authentication and I would like to assign the `IsAdmin` variable to the users of a `group_dn`. I used the following struct in my .toml file.
```
[[servers.group_mappings]]
group_dn = "XXXX"
org_role = "Admin"
grafana_admin = true
```

I have checked the grafana.db file and I see that the `IsAdmin` column is set to 0. 
### What was the expected result?
Give Grafana Admin privileges to my LDAP user.
### What happened instead?
I don't have the Grafana Admin privileges.
### What I did to debug?
I checked the grafana.db file and I saw that the `IsAdmin` column is set to 0 for my user. Also, I tried to debug the code a little bit and I noticed that if I add the following code to the test, the test is failing ( but maybe this is ok ).

```
diff --git a/pkg/login/ldap_test.go b/pkg/login/ldap_test.go
index 1cf98bd1e..1f9e7231a 100644
--- a/pkg/login/ldap_test.go
+++ b/pkg/login/ldap_test.go
@@ -244,13 +244,14 @@ func TestLdapAuther(t *testing.T) {
                        })

                        sc.userOrgsQueryReturns([]*m.UserOrgDTO{})
-                       _, err := ldapAuther.GetGrafanaUserFor(nil, &LdapUserInfo{
+                       result, err := ldapAuther.GetGrafanaUserFor(nil, &LdapUserInfo{
                                MemberOf: []string{"cn=admins"},
                        })

                        Convey("Should create user with admin set to true", func() {
                                So(err, ShouldBeNil)
                                So(sc.updateUserPermissionsCmd.IsGrafanaAdmin, ShouldBeTrue)
+                               So(result.IsAdmin, ShouldBeTrue)
                        })
                })
        })
```

Also, I tried to debug a little bit more and I saw that after [that](https://github.com/grafana/grafana/blob/c7279a4e075425f6c2b53b889601049bfa52c8c1/pkg/login/ext_user.go#L76-L80) code section, the function that is in [that](https://github.com/grafana/grafana/blob/c7279a4e075425f6c2b53b889601049bfa52c8c1/pkg/services/sqlstore/user.go#L472-L482) named `inTransaction` is never executed. I repeat that this happens when I run the tests. Maybe I missunderstand the way that `bus` is working, but as far as I can understand, it triggers a function as soon as you change or set a variable, like you do in [here](https://github.com/grafana/grafana/blob/c7279a4e075425f6c2b53b889601049bfa52c8c1/pkg/login/ext_user.go#L76-L80).

**Comment by marefr** [comment]
Sorry, this feature will be available in Grafana v5.3. You can try it out using a nightly build or the grafana:master docker tag.
