### ISSUE TITLE
How to create a trend graph in single panel with data's associated in different date and time in grafana

### ISSUE THREAD

**Issue by SindhujaSoundarapandian** [grafana/grafana#13051]
Hello,

I have a requirement to display the executions results of successive builds across the weeks in a trend like

Transaction b1 b2 b3
Login            xx yy zz
Dashboard    aa bb cc

we want a trend on login transaction and dashboard transactions across the builds

I tried with timeshift function but its not working. any help is much appreciated

**Comment by torkelo** [comment]
Not sure exactly what you mean. but there is a trend function in graphite 

Please ask questions on the community site https://community.grafana.com
