### ISSUE TITLE
Y axis time label malfunction

### ISSUE THREAD

**Issue by CiaranG** [grafana/grafana#1305]
Something has gone amiss here - see the left-hand Y axis - "10 min" appears twice.
![10min](https://cloud.githubusercontent.com/assets/149233/5635863/d6524388-95e4-11e4-9d07-a2c623f09581.png)

**Comment by CiaranG** [comment]
With the graph scaled up, it appears three times.
![thrice](https://cloud.githubusercontent.com/assets/149233/5635916/4c86676e-95e5-11e4-8db7-78d03500660e.png)

**Comment by CiaranG** [comment]
Actually, is it possible this was fixed between 1.9.0 and 1.9.1? I don't see anything obvious in the changelog, but I noticed after reporting this that 1.9.1 has been released and upgraded. It's no longer happening. Could be just that the data changed in the meantime, but maybe it's fixed?

**Comment by torkelo** [comment]
Yes there was a fix to y axis value rounding that could cause this problem
