### ISSUE TITLE
Explore view: remove query doesn't

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13057]
If I click the 'x' to remove a query (added by navigating to explore from a panel with multiple queries) the query is cleared, but the "Enter a PromQL query" box remains.
<img width="796" alt="screen shot 2018-08-28 at 12 54 53" src="https://user-images.githubusercontent.com/444037/44721360-93360080-aac1-11e8-8209-97ea4c47064c.png">

**Comment by davkal** [comment]
The `x` clears the query. The `-` removes the row. Need to harmonize these icons with the rest of grafana.

**Comment by davkal** [comment]
Closing for now. Will reopen if more complaints come in.
