### ISSUE TITLE
ldap + basic auth for api keys fail

### ISSUE THREAD

**Issue by Raboo** [grafana/grafana#13065]
Hi

I have a grafana installation with ldap and basic auth enabled.
When trying to use api keys to load a dashboard I get a `Basic auth failed` with a 401 HTTP response.

### What Grafana version are you using?
Tested both 4.6.3 and 5.2.2
### What datasource are you using?
OpenTSDB, ElasticSearch, MySQL
### What OS are you running grafana on?
Linux (official grafana docker)
### What did you do?
Try to access dashboard using API e.g. `curl -u "api_key:xx" "https://grafana.xx.com/d/00..."`
### What was the expected result?
200 OK
### What happened instead?
Getting 401 Unauthorized, `{"message":"Basic auth failed"}`

My related grafana conf looks like this
```
[auth.basic]
enabled = true
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
```

Logs when error happens
```
t=2018-08-28T17:14:29+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d/000000024/haproxy status=401 remote_addr=x time_ms=0 size=31 referer=
t=2018-08-28T17:14:29+0000 lvl=eror msg="Basic auth failed" logger=context error="User not found"
```

I'm guessing this is a bug? Cause documentations says that the api_key basic auth should work.
Using the `Bearer` header works, but unfortunately it's not applicable in my case.

**Comment by marefr** [comment]
It's a [feature](12416) that will be included in v5.3. Sorry for not making that clear in the documentation.

**Comment by Raboo** [comment]
It doesn't work with regular browsers, only curl. Have no idea on why, but I get redirected to the login page when using Chrome or Firefox.

**Comment by marefr** [comment]
How/why are you trying to use this feature in the browser?

**Comment by Raboo** [comment]
The more I dig, the more I realize that I need a URL token like suggested in https://github.com/grafana/grafana/issues/3752.

I just saw that Chrome doesn't support basic auth using https://user:pass@url/
See https://www.chromestatus.com/feature/5669008342777856.

However if basic auth worked using a browser, I could internally put a reverse proxy that adds authorization header to circumvent Chrome and eventually Chromecast limitations..

**Comment by marefr** [comment]
Some alternatives left to evaluate:
1. Enable anonymous authentication
2. Setup reverse proxy and configure chromecast to use url of reverse proxy. In proxy validate that device is allowed to access Grafana/certain dashboard and attach api token before proxy to Grafana to authenticate

**Comment by Raboo** [comment]
1. Is not a good option because we have a public endpoint.
2. That is what I did using Grafana Auth Proxy feature. But I didn't get the whitelist to work :(. So I had to create a obscure header name..
3. I tried that in nginx using `proxy_set_header Bearer xxx;` That didn't work. And basic auth failed, but that is because it's not designed for browsers, only api calls.

**Comment by marefr** [comment]
3. Should work for both browser and api if you use a real basic auth account and not an api key

**Comment by Raboo** [comment]
Ok, I never tried with a real user. I will do that and report back.

**Comment by Raboo** [comment]
Didn't work with a ldap user, it did however work with a "local" user. I guess that is survivable.
Thanks @marefr for the guidance. Now I can turn off auth proxy.

**Comment by C-Duv** [comment]
@Raboo I am aiming for pretty much the same goal as you (display dashboard on a kiosk-browser: *Screenly in my case) and I've found your issue by reading #3752.
I see you have *Nginx* acting as a reverse proxy, and LDAP auth enabled *Grafana*.

In your last message, you said you could now turn off [*Grafana*'s *Authproxy*](http://docs.grafana.org/tutorials/authproxy/), so:
* *Nginx* is not doing any auth? Only adding headers (and maybe TLS termination, port change, etc.).
* Authentication is completely handled by *Grafana*?

If you managed to display a dashboard/playlist on a dashkiosk receiver, I am very interested in more details about you setup.

**Comment by Raboo** [comment]
@C-Duv Auth is handled by nginx, but using basic auth instead of Auth Proxy.
Create a local read only user in grafana (invite, accept invite), LDAP user won't be able to use basic auth.

Install a nginx somewhere and set it up a reverse proxy..
Perhaps even add some access rights.
But it should look roughly like this.
```
server {
  listen 81;

  location / {
    proxy_pass https://grafana.yourdomain/;
    proxy_set_header X-Forwarded-For $remote_addr;
    # basic auth, generate using echo -n "username:password"|base64
    proxy_set_header Authorization "Basic XXXX";
  }
}
```
