### ISSUE TITLE
Make dashboard "save as..." available to editors again...

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#13066]
I'd like to see the changes in commit [5c57c7cff56eb5f10c64312b73b9d47b54df571b](https://github.com/grafana/grafana/commit/5c57c7cff56eb5f10c64312b73b9d47b54df571b#diff-febac26e9bf2fa262475591a46b06ebd) reverted or altered. It changed the ability to copy a dashboard via "save as...": Before this commit, every editor could copy a dashboard, regardless of the _editable_ flag. Now, a dashboard can only be copied if it is _editable_.

**The ability to copy dashboards that are not editable was great**, because you had the flexibility to kind of "finalize" a dashboard by removing the flag, but other editors still were able to copy it in order to investigate queries or even learn from them.

Now, there is only one way if you want to copy a dashboard (aside from the fact that you can have look at the full JSON, of course):
1. make the dashboard editable
2. think of a somewhat stupid comment when saving
3. save your own copy ("save as..." button is available now)
4. remove the _editable_ flag on the original dashboard
5. save the dashboard again to make the _editable_ flag permanent again
6. repeat step 2.

This is kind of **unnecessary work** here. Plus, the user most likely **forgets to process steps 4 to 6**. And it kind of spams the **version history**...

### What Grafana version are you using?
5.2.2
### What datasource are you using?
[KairosDB Datasource 3.0.2](https://github.com/grafana/kairosdb-datasource/releases/tag/v3.0.2)
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Try to copy a dashboard which is not _editable_.
### What was the expected result?
The dashboard should be copied via "save as...".
### What happened instead?
The dashboard could not be copied via "save as...", because it was not editable.

**Comment by torkelo** [comment]
I guess simple change to: in dashboard settings.ts
 this.canSaveAs = contextSrv.hasEditPermissionInFolders;

should solve this.

**Comment by marefr** [comment]
@torkelo yes that should be enough
