### ISSUE TITLE
Grafana Graph is not displaying data in real time.

### ISSUE THREAD

**Issue by srikanthpanchakarla** [grafana/grafana#13063]
What Grafana version are you using? 
v5.1.4

What datasource are you using? 
InfluxDB

 What OS are you running grafana on? 
Linux OEL 6.5

What did you do?  I am streaming telemetry data from Router to Pipeline collector at 1 sec interval and making pipeline write data to InfluxDB.

What was the expected result?
When I try to visualize the data using Grafana graph - I see data is not showing in real time. Please review the attached diagram. I am not sure why I am unable to view the data in real time?

![grafana_issue](https://user-images.githubusercontent.com/42774463/44728411-1115fe00-aafa-11e8-8342-e05e35a3764a.png)

**Comment by torkelo** [comment]
Use query inspector in metrics tab to view query sent to influxdb and influxdb response, for the time range you have Grafana Will send a query to influxdb requesting all data last 30min, so maybe time is off on your influxdb server , Local browser computer or the sensor sending data

**Comment by srikanthpanchakarla** [comment]
Thank you so much for your help. Source and InfluxDB server are not in sync in time. Correcting this fixed the issue. Thank you for your tip.
