### ISSUE TITLE
Grafana dashboards storage

### ISSUE THREAD

**Issue by himanshurajput32** [grafana/grafana#13067]
Hi
We are running Grafana(5.2.1) over Kubernetes. Datasource is Prometheus which is also running on same Kubernetes cluster. I have several dashboards over Grafana, those we created from Grafana UI. 
Now issue is that Kubernetes restarts Grafana's docker container if a node in cluster goes down. When it get's restarted It becomes a fresh grafana instance and all the dashboards are lost from UI. 
Is there any way to load grafana dashboards from any storage automaticaly?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

I guess you should use persisted volumes in Kubernetes.
