### ISSUE TITLE
Sort series by series name

### ISSUE THREAD

**Issue by hellajoey** [grafana/grafana#1306]
Hi. I apologize if this is clearly laid out in the documentation. I wasn't able to find it though. I have a graph that displays 3 different series which are split out by a group by. My problem is that with each refresh the order of the series in the legend changes and the colors of the series in the graph change too. How can I freeze those 2 things?

Thanks so much.

-Joey

**Comment by torkelo** [comment]
The order of the series is determined by the metric db query. For example Graphite has function that allows to sort series by maxima etc. InfluxDB used to have an issue like this where order was not the same between queries. This was fixed in v0.7 I think. What does you query look like?

**Comment by hellajoey** [comment]
First off, thanks for the very fast responses Torkel. My query as written in grafana is:

select serviceId, distinct(value) from "jvmMemoryUsage" where $timeFilter group by time($interval), serviceId order asc

And I essentially want to have the series' ordered in the legend by serviceId.

**Comment by torkelo** [comment]
put your serviceId in the series name, like select mean(value) from /.*.jvmMemoryUsage /

It should give you consistent series ordering. I would prefer if the series ordering is handled by the time series store as it has more information available to handle series order. But it could be implemented in grafana if enough people +1 vote for it :)

**Comment by hellajoey** [comment]
Hmm. In my opinion it seems reasonable to be able to expect to set the order in the query. Especially in my case because the serviceId which is a GUID would be redundant there. But I understand if that's not a priority. 

I think that solution brings up a different issue that maybe you can help me with though. Right now, the name for each series in the legend is something like:

jvmMemoryUsage.324h2342h3-23h4234h23-3h4234h23

where 324h2342h3-23h4234h23-3h4234h23 is the serviceId. I would prefer this only show the serviceId if possible. The jvmMemoryUsage is redundant. However, if I'm understanding your suggestion to add the serviceId to the name of the data blob I send to InfluxDB (for instance: name = 324h2342h3-23h4234h23-3h4234h23.jvmMemoryUsage) then I imagine the name of the series in the legend would change to:

324h2342h3-23h4234h23-3h4234h23.jvmMemoryUsage.324h2342h3-23h4234h23-3h4234h23

and that would never fly. Is there a way for me to alias the name in the legend *and* do it in a way that uses the serviceId -- bearing in mind that I don't know the serviceIds while I'm writing the query?

Thanks for the help.

**Comment by torkelo** [comment]
Yes, you are right that you should be able to sort it using the query, so if you cant then it might be a InfluxDB issue. As grafana will present the series in the legend in the order they come from Influx. 

you can alias the series name using a part of the series name (see alias patterns in the influxdb query editor). just put in $2 to in the alias and the series name will be the last segment (segments delimited by dots)

**Comment by hellajoey** [comment]
Oh, very cool. Thank you!

-Joey
