### ISSUE TITLE
Support for flexible y-axis scalings (regression)

### ISSUE THREAD

**Issue by Birne94** [grafana/grafana#13076]
In #6051 @torkelo introduced support for flexible scalings along the y-axis.

During some refactoring of grafana this feature was removed just a few days later: https://github.com/grafana/grafana/pull/5917/commits/81cb4a740b775c485cd6c873677ebbe0bb69f813#diff-73b6d2d157efa75a5bf386d69674b2ffL404

Testing with our grafana instance (v5.2.2 (aeaf7b2)), I was not able to get flexible y-axes running, so I assume this feature was not reintroduced later on.

Was removal of this feature on purpose or did this accidentally happen during refactoring?
Is there any comparable feature or any plans of bringing this feature back?

**Comment by torkelo** [comment]
the feature request is still open, https://github.com/grafana/grafana/issues/979 

We reverted merging the PR as it had a few issues.

**Comment by torkelo** [comment]
here is another related feature request, https://github.com/grafana/grafana/issues/4156
