### ISSUE TITLE
How can double y axis of grafana graphs be included in Kibana?

### ISSUE THREAD

**Issue by RitikaG** [grafana/grafana#1307]
We are working on kibana and all the requirements are getting sufficed. But, the histogram in kibana has only one y axis. How can this be worked upon?

**Comment by torkelo** [comment]
By implementing the feature? I am afraid you will have to open an issue in the kibana github repository

**Comment by RitikaG** [comment]
I mean I want to have grafana like double y axis.

**Comment by torkelo** [comment]
Yes, I understood that. But I am not sure why you are requesting a Kibana feature in the Grafana project repository :) A mistake?

**Comment by RitikaG** [comment]
not really. I wanted to understand how is it structured in Grafana.

**Comment by torkelo** [comment]
Ok I see, sorry  for being so slow :) 

Well it is pretty easy as Grafana is using flotcharts for graphs and it supports multiple y-axis. It has some docs that are pretty easy to understand for how to do it. But I think Kibana 4 (which is a total rewrite of Kibana) is not using flotcharts any more.

**Comment by RitikaG** [comment]
Okay. So, if I use flotcharts in Kibana, I can achieve the same functionality?
Because histograms do not support double y axis in Kibana.
And, I am using Kibana 3.1.2

**Comment by torkelo** [comment]
Yes, but you would have to modify the source and specify two yaxis in the options passed to flotcharts and for the series you also have to specify which axis each series belongs to.

**Comment by RitikaG** [comment]
Right. And thats the point I am stuck at - how and where to make the required changes.

**Comment by torkelo** [comment]
https://github.com/elasticsearch/kibana/blob/v3.1.2/src/app/panels/histogram/module.js#L655

https://github.com/flot/flot/blob/master/API.md#multiple-axes

**Comment by RitikaG** [comment]
Thanks a lot. I'll try with this.

**Comment by RitikaG** [comment]
How can we show the axis labels?

**Comment by torkelo** [comment]
https://github.com/flot/flot/blob/master/API.md#customizing-the-axes
