### ISSUE TITLE
[Feat] Panel padding is too large since Grafana 5.x

### ISSUE THREAD

**Issue by PeggyFree** [grafana/grafana#13077]
### What Grafana version are you using?
5.2.2

### What did you do?
Migrate from Grafana 4.3 to 5.2.2

### What was the expected result?
Similar or better visual result

### What happened instead?
I use several single stat and text panels in my dashboards. In Grafana 4.3, when there was no text in the title, the top bar was very thin, that gave room for the text and single stats. 
Now in grafana 5.x the title bar remains thick, hence the graphics look stretched and small. Unfortunately I don't have a screenshot of my 4.3 dashboard before the migration.

In the attached screenshot I colored the background to show how the panel data is stretched.
Is it possible to set negative or smaller margins/paddings? 

![graf_2018-08-29_16h29_51](https://user-images.githubusercontent.com/29567205/44794767-7543cb00-aba9-11e8-881b-1040052bd3b9.png)

**Comment by torkelo** [comment]
This was a result of a minor breaking change where title bar is required to interact with panel (panel menu), there is a feature request to restore the smaller panel header height  when there is no title present, 
https://github.com/grafana/grafana/issues/11394
