### ISSUE TITLE
Grafana release, tag "latest" on version 4.6.4 

### ISSUE THREAD

**Issue by VincenzoDo** [grafana/grafana#13078]
Hello,

is there a reason why Grafana 4.6.4 is tagged as latest release instead of the 5.2.3?

Best regards,

Vincenzo

**Comment by torkelo** [comment]
thanks for reporting this, fixed!

**Comment by VincenzoDo** [comment]
Are you sure? I still see latest on 4.6.4!

**Comment by marefr** [comment]
@VincenzoDo you're talking about Grafana docker image right?

**Comment by VincenzoDo** [comment]
No sorry maybe I didn't explain myself very well I was talking about the github release
![image](https://user-images.githubusercontent.com/11388017/44841483-be485d80-ac43-11e8-844e-dae26b96433e.png)

**Comment by marefr** [comment]
@VincenzoDo that's because the changes for v4.6.4 was made later than 5.2.3 and is how github releases works. Don't think there a way to change this without rewriting git history

**Comment by VincenzoDo** [comment]
@marefr Ah ok thanks for the info...I'm using a pipeline which uses the latest tag info to fetch and build Grafana so for now I will specify version manually.
