### ISSUE TITLE
Can't evaluate field AppName

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#13072]
When upgrading grafana to https://github.com/grafana/grafana/commit/9423e3e12412f3a88b8cd5b612b396015669a5f9

Following error occurs when running `bin/grafana-server`

template: index:70:64: executing "index" at <.AppName>: can't evaluate field AppName in type *dtos.IndexViewData

I built it using 
```
go run build.go setup
go run build.go build
yarn install --pure-lockfile
yarn run watch
```

**Comment by marefr** [comment]
Works as expected for me. Unable to reproduce your issue. Please make sure you're using `./bin/<architecture>/grafana-server`, see http://docs.grafana.org/project/building_from_source/#running-grafana-locally

**Comment by simPod** [comment]
I see, I was running it without `<architecture>/`. Thanks!
