### ISSUE TITLE
Oauth login seems not Stateless

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#13073]
I recently got rid of the persistence volume of my grafana deployment (with an external postgresql db backend) into kubernetes to make it stateless and be able to have several replicas.

Unfortunately it seems that the OAuth authentication process is stateful.

I've tried 2 replicas of the grafana backend and encountered problems at login when I would get the following error ` login.OAuthLogin(missing saved state)`.

It seems if you start your login with one backend and you get redirected one another one after the redirection the process fails.

Regards.

**Comment by DanCech** [comment]
You need to have a shared session store between the instances, or use a sticky load balancer.

**Comment by sylr** [comment]
Why is this not stored in database ?

**Comment by DanCech** [comment]
Because it's related to the session, not the user.  You can store the session data in the database.

http://docs.grafana.org/installation/configuration/#session

**Comment by sylr** [comment]
@DanCech Thanks, I've tried and it works fine!
