### ISSUE TITLE
Prometheus with https

### ISSUE THREAD

**Issue by turbotankist** [grafana/grafana#13070]
Hello!

Does grafana support prometheus datasouce over https?
We have prometheus server behind nginx with https. It's working!
But when we trying connect there from grafana with URL https://xxxx then we get error:
"Bad gateway"
If https not supporting then why there is checkbox Scip TLS Verification ?

**Comment by marefr** [comment]
Yes that should work. If you're using Server access mode please make sure that Grafana server can access your prometheus instance.

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
