### ISSUE TITLE
Accessing template variables in scripted dashboards

### ISSUE THREAD

**Issue by andreparodi** [grafana/grafana#1308]
Hi,

In the sample scripted dashboards it shows how to access url parameters via the ARGS variable. Is there a similar way to access the values of the template variables?

I noticed that when the dashboard is rendered the template variables are not visible yet so this is probably not possible. I saw there is async dashboards. Should I be using this?

Thanks in advance. 
Andre

**Comment by torkelo** [comment]
Not sure what you are asking. You can define template variables (and their options) in scripted dashboards. And you can define query variables as well. Do you want to access the options in a query variable at the time you are building the dashboard model? That is not possible as the options are only fetched after the dashboard model is created (by the dashboard script). 

Also there is a property on template variables named "refresh", a bool property. Set to true and the query template variables should be fetched (refresh) on dashboard load.

**Comment by andreparodi** [comment]
Thanks a lot for the quick reply.
I wanted to access the template variables in the js code that generates the dashboard. eg. i have 2 template vars from and to which are both numerical values. depending on the value selected for those template variable i want to generate the dashboard model accordingly. From what you are saying I now understand this is not feasable as the dashboard model doesn't get re-generated after a different template variable options has been selected. 

Could you explain what is the use case for the async scripted dashboard example you have? 

thanks in advance
andre

**Comment by torkelo** [comment]
async scripted dashboards is if you want to perform http requests in the script that builds the dashboard model.

**Comment by joehoeller** [comment]
Ok, what do you mean by this, "async scripted dashboards is if you want to perform http requests in the script that builds the dashboard model", I cannot get subsequent ajax calls to update the DOM

**Comment by joehoeller** [comment]
also, i am using scripted asyc ->  callback(dashboard)
