### ISSUE TITLE
[Feature Request] Save Dashboard changes except timerange 

### ISSUE THREAD

**Issue by jkarner** [grafana/grafana#13081]
It would be nice if you could edit and save just the queries or variable changes for the dashboard and not any changes to the time range. I recently updated a metric name on a lot of dashboards and to check the queries I adjusted the time range to a small window. When I saved the updated queries it also saved the reduced time range. 

I know I can look in the version history to see if the time range was updated on accident so I can restore it, but it would be cleaner to have a save option which excludes the time range adjustments.

**Comment by torkelo** [comment]
this was implemented in v5.2 https://github.com/grafana/grafana/issues/10748
