### ISSUE TITLE
Hostname with dots being escaped when query sent to Prometheus when using variable

### ISSUE THREAD

**Issue by gurpal2000** [grafana/grafana#13085]
### What happened instead? Dots are escaped with backslashes in the http request

```
Var: $server
Query: query_result(up{job='node'})
Regex: /.*instance="([^"]*).*/
Preview of values:
 demo.robustperception.io:9090
 demo.robustperception.io:9093
 demo.robustperception.io:9100
```

SingleStat `query: up{job='node', instance='$server'}`
Repeat: For each value of $server

HTTP Query String parameters in the request from Grafana appears like
`query: up{job='node', instance='demo\\.robustperception\\.io:9090'}`

Query brings back nothing.

**Comment by gurpal2000** [comment]
Could it because my query is wrong query_result(up{job='node'}) vs up{job='node'} ?

**Comment by torkelo** [comment]
If you have a variable with Multi select or All value enbled it must be used in a regex context in your prometheus query because grafana will by default preform a regex escape on the value. You can override this behavior by using `${variableName:raw}` but then selecting multiple values wont work
