### ISSUE TITLE
Slow Database Migration During Upgrade with Large Annotations Table

### ISSUE THREAD

**Issue by codylewandowski** [grafana/grafana#13084]
Please include this information:
### What Grafana version are you using?
Upgrading from 5.1.3 to 5.2.3 

### What datasource are you using?
NA - Using Postgres as Grafana's backend database

### What OS are you running grafana on?
Centos 7

### What did you do?
Upgrade Grafana from v5.1.3 to v5.2.3

### What was the expected result?
Grafana updates successfully 

### What happened instead?
During the upgrade of Grafana from v5.1.3 to v5.2.3 we observed that Grafana would appear to fail to start and had errors like `lvl=eror msg="Failed to get user with id" logger=context userId=4042 error="pq: remaining connection slots are reserved for non-replication superuser connections"`. 

Wither further digging we were able to determine that the migration commands here: https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/annotation_mig.go#L94-L111 were taking between 8 and 20+ minutes to complete. As a result, systemd was killing the process at the default of 90s because the grafana-server service was not yet fully started. When grafana-server was started again, it would start the same command again causing multiple of the same command to be in progress. Eventually, this exhausted connections on our Postgres database. 

We were able to manually run the annotation migration commands as well adding an entry in the migration log so that Grafana thought the table was updated. After completing each of these manually, the grafana-service was able to start. 

We also tested with setting the grafana-service `TimeoutStartSec` within systemd to `30m` and it seems that Grafana was able to complete the migration commands and successfully start. 

For additional context, the annotation table in our database is currently 1645 MB and our production environment consists of 8 Grafana servers. 

### If related to metric query / data viz:
NA

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
NA
 
We're not sure what action could even be taken on this, but a few ideas or things that would have helped us could be:
- A callout in the upgrade docs or changelog that a schema change is occurring and that it could take longer on large databases. 
- A database migration tool that could be run outside of the grafana-server startup process.

**Comment by codylewandowski** [comment]
An alternate solution could also be to provide a mechanism to remove or auto clear out old alert states from within the table.

**Comment by dyanneo** [comment]
https://community.grafana.com/t/release-notes-v5-2-x/7894/2?u=dyanneo

**Comment by marefr** [comment]
@codylewandowski #8224

**Comment by marefr** [comment]
I'm closing this in favor of #11090. Will add your suggestion regarding running migrations outside of grafana-server process to that issue. Will try and add some notes to the Upgrade documentation.

Thank you for making us aware of this.
