### ISSUE TITLE
Signup buttons still shows up after disabled signup

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#13096]
Reference #11041 

### What Grafana version are you using?
5.2.3
### What datasource are you using?
Influxdb
### What OS are you running grafana on?
Debian
### What did you do?
Clicked on "Forgot password"-link on login page and then Back
### What was the expected result?
Signup button should not be there
### What happened instead?
Signup button showed up

I also tried to fill in anything in Forgot password, in the email field and then clicked Reset Password, then the button Login, here Signup button also showed up.
I tried with two different installations of Grafana and two different PC.
I think I have seen this behavour before, so it is not a verion 5.2.3 error

**Comment by torkelo** [comment]
@Ijin08 can you investigate?

**Comment by Ijin08** [comment]
I am not able to reproduce the issue. For me if signup is disabled there is no signup button. After clicking forgot-password and then back there still isn't any signup button.
Could you post screen-shots so we might get a better picture of what is happening.

**Comment by flopp999** [comment]
I tried one more time to get these pages, I pressed CTRL+F5 and also F5 to reload the cache. Now it seems to be gone.
I promise that I done this many times but it was still showing signup page.
Can close this issue for now.

**Comment by flopp999** [comment]
I maybe now now how to recreate the "error".
Grafana 5.4.3
signout, click "Forgot my password", now press F5, click Back and I now see Signup again, even if it is disabled
I now tried this in Chrome both Incognito and normal mode, it worked many times
Can anyone confirm this?
