### ISSUE TITLE
Failed upgrading Grafana to 5.2.3: error when "Convert existing annotations from seconds to milliseconds" 

### ISSUE THREAD

**Issue by Cisneiros** [grafana/grafana#13094]
### What Grafana version are you using?
Migrating from Grafana 5.1 to 5.2.3

### What OS are you running grafana on?
Oficial Docker image

### What did you do?
Changed the docker image tag to the most recent one

### What was the expected result?
A nice, secure and upgraded Grafana 🎉 

### What happened instead?
The container fails to start with the following logs:

```
t=2018-08-30T14:55:06+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2018-08-30T14:55:06+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=postgres
t=2018-08-30T14:55:06+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-08-30T14:55:06+0000 lvl=info msg="Executing migration" logger=migrator id="Convert existing annotations from seconds to milliseconds"
t=2018-08-30T14:55:06+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Convert existing annotations from seconds to milliseconds" error="pq: integer out of range"
t=2018-08-30T14:55:06+0000 lvl=eror msg="Exec failed" logger=migrator error="pq: integer out of range" sql="UPDATE annotation SET epoch = (epoch*1000) where epoch < 9999999999"
t=2018-08-30T14:55:06+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: pq: integer out of range"
```

**Comment by marefr** [comment]
What postgres version are you using? What does the following query gives you?

```sql
SELECT * FROM INFORMATION_SCHEMA.columns WHERE TABLE_NAME='annotation'
```

I would guess you have a datatype that is not bigint. Have no idea how you've managed to get that. Could you include `SELECT * FROM "migration_log"`?

Workaround - change the epoch column data type to bigint, then run the migration manually:

```sql
UPDATE annotation SET epoch = (epoch*1000) where epoch < 9999999999
UPDATE "migration_log" SET success=1 WHERE "migration_id"='Convert existing annotations from seconds to milliseconds'
```

**Comment by Cisneiros** [comment]
Hi @marefr 

The field indeed was set as an `integer`. The only migration on that touches this field is its creation (it was created as `integer`).
I changed it to `bigint` and the upgrade happened without issues.

Thanks for the help!

**Comment by marefr** [comment]
@Cisneiros thanks for the update. 

Would still be interesting to see how this occurred since we have no similar reports. Any chance you've migrated from sqlite to postgres back in the days?

Will close this for now, but consider reopen if there are other reports regarding the same problem.

**Comment by jvassbo** [comment]
Just wanted to say we experienced the exact same error today (trying 5.1.4 -> 5.4.2), and we migrated from sqlite to postgresql while on 4.4.3.

**Comment by Cisneiros** [comment]
Just realised I never replied, but we migrated from sqlite to Postgres sometime in the past, yes
