### ISSUE TITLE
No error notification with nested queries based on metrics using template variables

### ISSUE THREAD

**Issue by adrean** [grafana/grafana#13090]
Hello,

I know that alerts do not support queries that use template variables, and when we try to create one, we'll get the nice error notification explaining the problem.
However, if we create a nested query (like dividing 2 metrics with `asPercent`, or even just the simplest reference `#A`) and create an alert on that metric, we won't get any notifications even though it won't work, and the results will be misleading if we don't test the alert

Is it something that could be implemented?  (sorry if it has been done since **version** : 4.6.3 that we use)
Thanks

**Comment by torkelo** [comment]
this works in later version. If you upgrade, to make it work you have to update your query once (like change alias or something), it will cause the full query rebuild (in the json model), so that alert engine has access to the full query
