### ISSUE TITLE
LDAP Authentication Failing

### ISSUE THREAD

**Issue by prakash1243** [grafana/grafana#13095]
Am trying to do the LDAP Authentication integration with my Grafana server, but it fails with the error message:

←[31mEROR←[0m[08-30|18:26:58] Error while trying to authenticate user  ←[31mlogg
er←[0m=context ←[31muserId←[0m=0 ←[31morgId←[0m=0 ←[31muname←[0m= ←[31merror←[0m
="LDAP Result Code 200 \"Network Error\": dial tcp: address ldaps://ckddawc01a.
ad002.ctad.org too many colons in address"

Grafana Version - 5.2.2
OS - Windows 2007

I've attached ldap.toml below.

[ldap.txt](https://github.com/grafana/grafana/files/2337017/ldap.txt)

**Comment by DanCech** [comment]
you need `host = "ckddawc01a.ad002.ctad.org"`
