### ISSUE TITLE
Legend Popup partially out of view when in edit mode

### ISSUE THREAD

**Issue by vonox7** [grafana/grafana#13101]
When editing a panel and clicking onto a graph-legend color, the popup to select the color and axis appears. The top of the popup is out of view, so the axis cant be toggled, see the following screenshot:

![image](https://user-images.githubusercontent.com/621501/44897118-e2b34100-acfa-11e8-92f1-eee3a148b5de.png)

Expected behaviour: The full popup is in view.

Grafanfa 5.2.0, Google Chrome 68

**Comment by vonox7** [comment]
Relates to https://github.com/grafana/grafana/issues/14134

**Comment by daniellee** [comment]
This is not an issue with the new color picker. Tried to recreate this but it never goes out of view.
