### ISSUE TITLE
access Grafana Server in local Application

### ISSUE THREAD

**Issue by ankit-net** [grafana/grafana#1310]
How to use a Hosted Grafana Environment (on some url) on my local application.

I had a url that works as a query for retrieving the data from Hosted Grafana Environment.

So, in order to display the graphs on my local application,  

What procedure's I had to follow?

Also, Does it Mandatory to use host Grafana setup on the local system to get the graphs from remote Grafana Server?

Thanks in Advance.

**Comment by torkelo** [comment]
I do not understand what you are asking. Do you have two Grafana instances, one remote and one local on your machine? Sorry, tried to read your query two times but fail to understand it :(

**Comment by ankit-net** [comment]
Right Now, I had one remote grafana server that is making the graphs correctly. 
My task is to get data from this server and show it on my local application (like java). 
I had been provided with a sample url. 
It is returning the data from remote grafana server in json format.
Is it possible to use this data to show metrics(means graphs) on my java application?

**Comment by torkelo** [comment]
Grafana has no json api it just just a static html+javascript application. 

if you want to show a grafana graph in your local application you need some kind of iframe or web view component as Grafana is a web application.

**Comment by ankit-net** [comment]
Ok.
Another Approach used that we had setup Grafana server on local machine, then uses 'InfluxDB' sandbox to create simple graphs. Then we asked remote server team to share influx db details but they replied that using the url (of this pattern: https://<domain>/db/?p=<alphanumericstring>&q=select+mean(requesttime)+from.......&u=loggly_grafana_read) database credentials are not required. Is it possible?

**Comment by torkelo** [comment]
Dont know, InfluxDB usually requires user and password.
