### ISSUE TITLE
Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" 

### ISSUE THREAD

**Issue by Aravindios** [grafana/grafana#13103]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.3 

### What OS are you running grafana on?
Mac osX inside docker image

here is my logs :
geting error in Webhook response status 400 Bad Request 

lvl=info msg=uploaded logger=alerting.notifier url=

 lvl=info msg="Sending Alertmanager alert" logger=alerting.notifier.prometheus-alertmanager ruleId=3 notification=aravind-alert-M

 lvl=info msg=uploaded logger=alerting.notifier url=

lvl=info msg="Sending Alertmanager alert" logger=alerting.notifier.prometheus-alertmanager ruleId=2 notification=aravind-alert-M

 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook=aravind-Tel
 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Webhook response status 400 Bad Request"

 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=172.17.0.1 time_ms=1325 size=48 referer=http://localhost:3000/alerting/notification/3/edit

 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xyxyxyxy@gmail.com]

lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp 127.0.0.1:25: connect: connection refused"

 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="dial tcp 127.0.0.1:25: connect: connection refused"

 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=172.17.0.1 time_ms=7 size=48 referer=http://localhost:3000/alerting/notification/1/edit

 lvl=info msg="Sending telegram notification" logger=alerting.notifier.telegram chat_id=680463482 bot_token=550938332:AAGULJzTcJRcVfEgDcaTlaIRsflADQvCkpFdsKiE apiAction=sendMessage

 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook=aravind-Tel

 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Webhook response status 400 Bad Request"

lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=172.17.0.1 time_ms=705 size=48 referer=http://localhost:3000/alerting/notification/3/edit

![screen shot 2018-08-31 at 1 28 47 pm](https://user-images.githubusercontent.com/36288173/44900316-ec9c6a80-ad21-11e8-8edc-74a3bd8eb1c6.png)

**Comment by torkelo** [comment]
Anyone who uses telegram that can help investigate this / try and replicate?

**Comment by 0rtem** [comment]
Hi, if your server is working with proxy, probably you should try change grafana-server.service file 
i'd fixed this issue when add two additional variable to grafana-server.service 
[Service]
EnvironmentFile=/etc/sysconfig/grafana-server
Environment=HTTP_PROXY=proxyserver:port
Environment=HTTPS_PROXY=proxyserver:port

**Comment by MichaelDBA** [comment]
I am getting the same error when i try to send an email invite through Grafana.
`Nov 22 15:14:22 ip-172-20-184-96.us-east-2.compute.internal grafana-server[18909]: logger=notifications t=2022-11-22T15:14:22.233952328Z level=error msg="Async sent email 0 succeed, not send emails: myname@mydomain.com err: failed to send notification to email addresses: myname@mydomain.com: dial tcp 127.0.0.1:25: connect: connection refused"`
