### ISSUE TITLE
UI flickering on refresh

### ISSUE THREAD

**Issue by pgrenaud** [grafana/grafana#13110]
Since I updated Grafana, the UI flicker on every refresh.

![video](https://user-images.githubusercontent.com/10713979/44929418-fc6b7d00-ad28-11e8-8c05-c3e211178b6b.gif)

### What Grafana version are you using?

* Current version with the issue: Grafana v5.2.3 (cf4c090)
* Previous version without the issue: Grafana v4.1.2 (3b510b7)

### What datasource are you using?

* InfluxDB 1.6.2

### What OS are you running grafana on?

* Backend: Ubuntu 16.04.5 LTS Linux 4.4.0-134-generic
* Frontend: Samsung Smart TV Web Browser 1.1.0.0311103 (TizenBrowser)

### What did you do?

I upgraded Grafana (I deployed a new VM, installed the latest version and migrated the data/config).

### What was the expected result?

I expected Grafana to work as good as before, or better.

### What happened instead?

The UI is flickering since I updated Grafana.

### If related to metric query / data viz:

N/A

### Include raw network request & response
 
Not possible with Samsung Smart TV Web Browser.

**Comment by pgrenaud** [comment]
> Is it just using normal dashboard auto refresh or are you using a tab that does a full page reload?

It is using the normal dashboard refresh (set to every minutes by default).

> Might be related to Samsung Smart TV Web Browser

It probably is, though is was not occurring with the previous version of Grafana.

**Comment by daniellee** [comment]
This doesn't seem to be a common issue so closing it for now. If this is still a problem then please update the issue and we can re-open it.
