### ISSUE TITLE
Issues with variables in multiselect and repeat mode

### ISSUE THREAD

**Issue by Thijzer** [grafana/grafana#13111]
This issue concerns the variables you create on your dashoard.
My current setup is data source from Prometheus => who collects from server metrics from netdata.

**Scenario:**
When I add a variable onto my dashboard ex $instance represents the instances I have.
When I switch my instance I see my graphs change. [OK works]
But when I change my variable type to a multiselect my dashboard has no values or N/A.
In other words the queries are not working.

**Issue**
On closer inspection the query seem to result into a null response.
The $instance value was now encoding issues, my instance value is a domain+port.
Resulting in a bad query string.
ex : www.domain.com:9000.
This happens ONLY when the $instance is set to multiselect.

hopefully you guys can reproduce this.

**Use Case**
The use case is a live health status board per instance using a status plugin.

**Comment by torkelo** [comment]
If you use multi you need to update your prometheus query and use regex operator in the label matching, 

example server =~ "$myar" 

http://docs.grafana.org/features/datasources/prometheus/#using-variables-in-queries
