### ISSUE TITLE
Docs: Document org & user preferences

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#13129]
Lacking documentation about org & user preferences. The inheritance of theme and timezone preferences seems to cause some confusion, e.g. https://github.com/grafana/grafana/issues/12770#issuecomment-418305143.

**Comment by oddlittlebird** [comment]
Please explain exactly what needs to be added to the documentation and where.

**Comment by marefr** [comment]
The only page mentioning this is [What's new in Grafana v3.0](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v3/#personalization-and-preferences).

Team preferences have been added since I opened the issue. 

Org preferences:
![image](https://user-images.githubusercontent.com/1668778/70826415-2d20da00-1de7-11ea-9613-5db1c84c3577.png)

Team preferences:
![image](https://user-images.githubusercontent.com/1668778/70826425-3316bb00-1de7-11ea-823c-806c32edad85.png)

User preferences:
![image](https://user-images.githubusercontent.com/1668778/70826460-4590f480-1de7-11ea-9594-b39130ffcc17.png)

1. If one preference is configured on my user that will be used for the user, if not see 2)
2. If user belongs to a team and that preference is configured on that then it will be used for the user, if not see 3). Please note that one random team is used if user belongs to multiple teams,
3, If current org of user has that preference configured then it will be used for the user, if theme see 4)
4. Configured them in Grafana config used as theme
