### ISSUE TITLE
Window title got "undefined" prefix

### ISSUE THREAD

**Issue by auntieyi** [grafana/grafana#13123]
### What Grafana version are you using?
v5.3.0-pre1

### What OS are you running grafana on?
Ububtu 16

The window title got undefined prefix:
![image](https://user-images.githubusercontent.com/1725966/45006327-e7ddfc00-b02a-11e8-8e54-a3658d5ccd60.png)

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
