### ISSUE TITLE
Compatibility of dashboard's json schema between 1.8 and 1.9.x

### ISSUE THREAD

**Issue by zdenekpizl** [grafana/grafana#1312]
Hallo,

 I'd like to make sure there is no compatibility issues between version of Grafana 1.8 and 1.9? I mean "will dashboard from 1.8 work seamlessly with 1.9.1"?

Thank you, .zp.

**Comment by torkelo** [comment]
yes, there are no breaking changes in the schema.

**Comment by torkelo** [comment]
For future reference if I ever would introduce a breaking change it will be very prominently mentioned in the changelog and release notes. And I would provide migration paths.

**Comment by zdenekpizl** [comment]
Thank you for clarification.

Best regards .zp.
