### ISSUE TITLE
How to export vectorgraph?

### ISSUE THREAD

**Issue by allenbunny** [grafana/grafana#13126]
How to export vectorgraph?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

See http://docs.grafana.org/reference/sharing/#direct-link-rendered-image

**Comment by maurerle** [comment]
This was then asked in the community site but never answered: https://community.grafana.com/t/how-to-export-vectorgraph/10166

I opened a discussion for feature request here:
https://github.com/grafana/grafana/discussions/67883
