### ISSUE TITLE
Metrics per user or per group security option

### ISSUE THREAD

**Issue by jpbarron** [grafana/grafana#1313]
Hello!

I have a need to filter access to specific metrics based off metric path pattern matching by group preferably, or user worst case.

Using an InfluxDB backend it appears you can configure users to have access to some but not all metrics, which is awesome.  ( see http://influxdb.com/docs/v0.8/api/administration.html#limiting-user-access for details )

What I would like to be able to do, is have the datasource option in the config.js for Grafana not be hard coded, but instead be able to use dynamic username and password from the browser back to the database.

This wouldn't work with graphite data sources of course.

An additional option that might solve #429 could be to update the elasticsearch index path to contain the username so dashboards are unique?  This wouldn't be totally secure since there is no authentication but it is better than nothing.

**Comment by toni-moreno** [comment]
HI @torkelo, @jpbarron . I've been thinking a lot on how to implement a "filter metrics"  option ( not security by itself) as we need also this feature.

I think the best way is add a metric filter option directly on the datasource , in this case grafana should always act as proxy to the backends.

With this new feature , Administrators could create custom datasources for each organization, and editors and viewers will be able only to see metrics from these custom datasources and force them to query data always with grafana 

we are always assuming users can not access directly to the data backends ( graphite/influx/opentsdb)

**Comment by torkelo** [comment]
@toni-moreno I have been thinking along similar lines but not sure how to handle Graphite wildcard queries that can circumvent any filter Grafana can inspect. 

for example:
`aliasByNode(*.*.*.servers.logins.count)`

The security filter needs to be in graphite-web or graphite-api where the wildcard is expanded to a full set of series lists.

**Comment by toni-moreno** [comment]
@torkelo I think a first approach could be filtering metrics in the metricFindQuery() method and also disable direct metric editing,  and json editor if datasource has metric filters,

![image](https://cloud.githubusercontent.com/assets/5883405/8542811/9740cb22-2498-11e5-82a9-1a49c54bb0c3.png)

As you said before you could not ensure always metric filter with imported dashboards from other grafanas. 

 Grafana super administrator will  take care on this issue if  it really would like to implement metric filtering by organization and this first approach will provide us a good starting point and could be "easy" to implement

What do you think about?

**Comment by torkelo** [comment]
@toni-moreno not sure about hiding stuff like that for security reasons when someone with http knowledge could easily query against any data using graphite wildcard queries.

**Comment by toni-moreno** [comment]
In my case I'm designing a big graphite backend but anybody will be able to query metrics directly from graphite because we have been closed  http access from any IP except from then grafana server.

I am also the Admin for all organizations ans I' have defined all datasources as proxy . In this scenario grafana could act as metric filter if disabled any way to put manually the metric name.

In this scenario, anybody shouldn't be able to query not allowed metrics .

**Comment by torkelo** [comment]
@toni-moreno Yes, users who know http can still query any metric using wildcards in the metrics expression. 

Explain how you can filter this query in the Grafana backend:
`aliasByNode(*.*.*.servers.logins.count)`

Given a data source metric security metric filter of `accounting.*`  , there is no way for a Grafana data source proxy to guarantee that security filter.

**Comment by toni-moreno** [comment]
Sorry , In the previous scenario metric filtering should be done on the server side  not on the client.

**Comment by torkelo** [comment]
@toni-moreno I know, but it has to be done on the server side in graphite-web or graphite-api

**Comment by toni-moreno** [comment]
Hi @torkelo you are right , the best way to add metric filtering is on the backend.

So we are working on add metric filtering by user to the graphite backend.

If graphite guys accept this new feature we would like to add a new hability to the grafana datasources which be able to pass REMOTE_USER in the HTTP header . 

After we can configure graphite to get users from HEADER, as explained here

https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example#L134

What do you think about this metric filtering solution?

**Comment by dlmarion** [comment]
+1 to passing the identity of the person at the keyboard back to the datasource. I think the only way to do this today is 2-way SSL and direct access to the datasource. If Grafana authenticated the user and passed the identity information to the datasource, then the datasource could determine the level of access that the user has using some authorization provider.

**Comment by torkelo** [comment]
I think this is best handled in in the DB layer (so in the tsdb), so closing this issue.
