### ISSUE TITLE
Variables: Add variable description option shown in tooltip 

### ISSUE THREAD

**Issue by IntegersOfK** [grafana/grafana#13138]
Hello, I would like to suggest allowing dashboard creators to add tooltips to the template variable dropdowns. The users in my Grafana instance want to know where the information populating the list of metrics/hosts is coming from, so I think it'd be nice to add some tooltip help when they hover over the dropdown. I'm not suggesting each item in a dropdown gets a tooltip, only the template variable label and when the cursor is hovering over the main template variable dropdown field box.

A natural place to add the option to configure this would be in the template variable itself:
![var](https://user-images.githubusercontent.com/529833/45039075-cf70e000-b030-11e8-9e8b-6c26c6131d73.PNG)

What Grafana version are you using?
Grafana v5.2.1

**Comment by torkelo** [comment]
Would make it a description option, in the top section below name. Not really a Selection option.
