### ISSUE TITLE
"Data points outside time range" - Postgres data source has inconsistent timezone at panel

### ISSUE THREAD

**Issue by leslie-qiwa** [grafana/grafana#13143]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
v5.2.3 (cf4c090)
### What datasource are you using?
Postgres
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
Use Postgres datasource to draw one panel
### What was the expected result?
Timestamp has same timezone on both X axis and tooltip
### What happened instead?
If Dashboard timezone is set to local timezone, X axis shows local browser timezone, but tooltip shows UTC timezone. And it always show `Data point outside time rage`
<img width="888" alt="screen shot 2018-09-04 at 3 30 56 pm" src="https://user-images.githubusercontent.com/34456213/45061383-1c68ac80-b059-11e8-81fc-ba4dab8ea76d.png">

If Dashboard timezone is set to UTC, X axis shows UTC, but tooltip shows local browser timezone. 
<img width="856" alt="screen shot 2018-09-04 at 3 35 40 pm" src="https://user-images.githubusercontent.com/34456213/45061404-31ddd680-b059-11e8-860f-82b4cb0216d4.png">

### If related to metric query / data viz:
Yes

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
Here is result of sql 
<img width="441" alt="screen shot 2018-09-04 at 3 32 09 pm" src="https://user-images.githubusercontent.com/34456213/45061420-3bffd500-b059-11e8-9d89-e5b53ece9107.png">
 
<img width="646" alt="screen shot 2018-09-04 at 3 46 29 pm" src="https://user-images.githubusercontent.com/34456213/45061528-b9c3e080-b059-11e8-81c2-2f06f30682b0.png">

**Comment by leslie-qiwa** [comment]
Probably duplicate with https://github.com/grafana/grafana/issues/9356.

**Comment by marefr** [comment]
@leslie-qiwa will close this then. Out of curiosity - what timezone do starttime represent in database?

**Comment by leslie-qiwa** [comment]
It is UTC time. I use timezone type in postgres, and server timezone is UTC. Now I change type to timezonetz which can display correctly.
