### ISSUE TITLE
Dashboards do not respect URLs when browser opens with multiple dash tabs

### ISSUE THREAD

**Issue by thiagomdiniz** [grafana/grafana#13140]
### What Grafana version are you using?
v5.2.3

### What datasource are you using?
MSSQL

### What OS are you running grafana on?
Linux CentOS 7 (install with yum repository)

### What did you do?
I'm setting up the browser (Google Chrome) to start by opening up seven tabs, each with a different dashboard. Some dashboards have variables, which they include in the URL to open the dashboard with the variable initialized. I also included the "&kiosk" parameter in the URL.

### What was the expected result?
Each browser tab should open the dashboard as defined URL.

### What happened instead?
Each time I close and open the browser the tabs open the dashboards "randomly", not respecting the URLs that I set to open with the browser.
Sometimes the same panel appears in several tabs, sometimes the parameter of the variable in the URL is not respected.

Could there be any session / cookie that would impact this simultaneous opening of multiple tabs with different dashboards?

**Comment by viniciusbona** [comment]
Follow the video that demonstrates the reported problem

[https://youtu.be/XEvhI_wmCyA]

**Comment by torkelo** [comment]
Looks like an issue with chrome as the url for the first two tabs is the same after started chrome the second time

**Comment by thiagomdiniz** [comment]
Here we also tested in Firefox and presented the same problem.

**Comment by torkelo** [comment]
I have replicated this now, it's related to login (session renewal). When you close chrome the session is removed. So the first thing Grafana does is redirect you to login page (where you get logged in again using remember me cookie). But to know which page to go back to Grafana sets a redirect url cookie, and this will be the same of some of the tabs when they load at the same time.

possible workaround until we find a better way to handle redirect is to enable anonymous access.

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630) (FireFox) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
