### ISSUE TITLE
Edit mode is not showing up after choosing another page and saving the current dashboard

### ISSUE THREAD

**Issue by ItsJulia** [grafana/grafana#13146]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana 5.2.3

### What datasource are you using?
No datasource

### What OS are you running grafana on?
Windows 7 / Chrome

### What did you do?
I created a new dashboard and added a graph-panel. Then I opened the edit-mode. 
After that I wanted to open the configuration/datasource page. Grafana asked me if I want to save the page and I thankfully saved it. Then the edit-mode was closed and I was still on the dashboard with one default graph. 
Then I changed my mind and wanted to open the edit-mode again, instead of configuring my datasource first.

### What was the expected result?
I expected the edit-mode to show up. 

### What happened instead?
The graph disappeared and the whole dashboard remained empty.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
_Sorry, if that behavior was reported before. I couldn't find a related topic._

**Comment by torkelo** [comment]
Unable to replicate this, if you follow the exact same steps again do you see the same thing?

**Comment by torkelo** [comment]
closing this due to no updates
