### ISSUE TITLE
Add custom functions into function editor

### ISSUE THREAD

**Issue by Onlinehead** [grafana/grafana#1314]
Hi!
We have some custom function in graphite.
Is it possible to add that functions to query editor for fix attention about using wrong function when editing?
It's ok if we need to edit code for do it, but maybe you can add that setting as part of GUI?

**Comment by torkelo** [comment]
You need to add the your custom functions here: 

https://github.com/grafana/grafana/blob/master/src/app/features/graphite/gfunc.js
