### ISSUE TITLE
Backlight value on graph.

### ISSUE THREAD

**Issue by Onlinehead** [grafana/grafana#1315]
Is it possible to add backlight of painted value when you hold mouse on its name in annotation?
Sometimes on big graphics it is more useful then click on each value and check it without other painted values.
Prototype of that effect you can find here: http://code.shutterstock.com/rickshaw/examples/legend.html

**Comment by torkelo** [comment]
name in annotation? You mean the series name in the legend?

**Comment by Onlinehead** [comment]
Right, name in legend.

With best regards, 
Anton Kostenko

**Comment by torkelo** [comment]
Closing due to lack of interest
