### ISSUE TITLE
Resize page (dashboard) to by bigger

### ISSUE THREAD

**Issue by ondrejFuchs** [grafana/grafana#13158]
We use grafana 5.0.4 in company server - Ubuntu. Also we use influxdb. We use grafana to check our devices status. We have columns  with panels of our the devices.
For example:
|company1|company2|company3| ...
| dev-1 | dev-2 | dev-3 | ...
| dev-4 | dev-5| dev-6| ...

And my question is, its possible to add column to right next to another. For now we have full screen and after that I canť add another column next to the most in right and have horizontal slider in botton of page. Is it posible to do it?
For example:
|company1|company2|company3| .. |newcompany|
| dev-1 | dev-2 | dev-3 | ...  | dev- 20|
| dev-4 | dev-5| dev-6| ... | dev- 25

Thanks for response.

**Comment by torkelo** [comment]
No dashboards cannot have be wider than your browser view (no horizontal scrolling , only vertical)

**Comment by nguyenlamlll** [comment]
> No dashboards cannot have be wider than your browser view (no horizontal scrolling , only vertical)

May I know why we do not support placing more panels to the sides (horizontally)? This horizontal scroll is about the position of panels (not the scroll of time like what we have already had.)

Just for reference: I come from Azure. In Azure, I can place more graphs/panels both horizontally and vertically. 

Thanks!
