### ISSUE TITLE
Time macros not expanding in non-templated Postgres query

### ISSUE THREAD

**Issue by brylie** [grafana/grafana#13159]
Grafana version: 5.2.2
Datasource: Postgres
OS: Linux

# What did you do?
Created a Postgres query using either `$__timeFrom()` or `$__timeFilter(created)` time macros. Note, this is *not* a templated query.

# What was the expected result?
The time macro would be expanded, as per the documentation, into an SQL-compatible time string.

# What happened instead?
When inspecting the query, the SQL query string contains the raw macro. E.g. `$__timeFrom()` rather than a date string.

**Comment by torkelo** [comment]
where you specifying this query? 

> Note, this is not a templated query

What do you mean?

**Comment by brylie** [comment]
It is really strange, I have tried using the macros with and without quotes around the field name. It seemed to work once, but has mainly failed to work. When I view the `rawSql` there is typically an unexpanded macro in the query string.

**Comment by marefr** [comment]
@brylie  You must include more details so that we understand what you're trying to do. Full query you're trying to use, screenshots, animated gifs etc. Thanks

**Comment by brylie** [comment]
Here is a screenshot showing a fragment of the query and the `rawSql` string:

![screenshot_20180906_105744](https://user-images.githubusercontent.com/17307/45143339-b0ef1e00-b1c3-11e8-8868-654b22b27a7b.png)

The `$__timeFilter("created")` can be seen on the second line of the `rawSql` string as well as in the query fragment.

This is difficult to debug, as the 'Show SQL' button doesn't always appear. It would be helpful if I could click a 'generate SQL' button before Grafana attempts the query.

**Comment by brylie** [comment]
It seems like the `$__timeFilter("created")` did actually take effect. It is just difficult to see the generated SQL when a query takes a while to execute. It would be better to see the SQL before the query executes.

Apologies for the confusion, but this seems to be more of a 'developer UX' or 'developer experience' bug about how/when generated SQL is displayed.

**Comment by marefr** [comment]
> It is just difficult to see the generated SQL when a query takes a while to execute. It would be better to see the SQL before the query executes.

That's not possible since macros in the query are converted in the backend. 

Each time you leave the query editor (focus outside) the query will be executed (see loading indicator top right of panel) and then generated query will be available. An alternative would for you to have the query inspector open when writing your queries.

As a general rule of thumb we suggest that you start writing a query that returns a low number of rows using a short time range and then iterating on that.

**Comment by brylie** [comment]
> That's not possible since macros in the query are converted in the backend.

Would it be possible to split the query generation from the query execution? That way, the generated query could be returned more promptly, while the query execution could proceed in the background.

> As a general rule of thumb we suggest that you start writing a query that returns a low number of rows using a short time range and then iterating on that.

Good suggestion :-)

**Comment by marefr** [comment]
> Would it be possible to split the query generation from the query execution?

Everything is possible but in this case I would say no. Don't see any point for supporting this. What should you do with the generated query before it has executed??? Macros function are there for ease of use and convenience. You don't have to use the macro functions if you don't want - you can handcraft/tailor all your queries by writing the full queries manually. It will not give you automatic fill of values and such, but you're free to do whatever you want.

**Comment by brylie** [comment]
> What should you do with the generated query before it has executed???

Well, in this case I could visually inspect the query to **speed up the debug** process. A big part of my confusion in this issue was related to delay in seeing query output, both in the 'Show SQL' and in the `rawSql`. Changes I made didn't seem to take effect, even though they may have and the system was waiting for the query to return.

>  You don't have to use the macro functions if you don't want - you can handcraft/tailor all your queries by writing the full queries manually. It will not give you automatic fill of values and such, but you're free to do whatever you want.

We don't have to get argumentative here. I clearly want to use the macros, so the charts correspond with the selected date range. I was simply asking whether it would be feasible to get a quicker glance into the generated SQL, for debugging purposes.
