### ISSUE TITLE
inconsistency in dashboard and snapshot y axis scaling 

### ISSUE THREAD

**Issue by jarmokivekas** [grafana/grafana#13150]
- What Grafana version are you using: Grafana v5.2.3 (cf4c090)
- What datasource are you using: InfulxDB v1.6.2
- Running Grafana on: Ubuntu 18.04

I'm trying to share a dashboard snapshot using the built-in snapshot.raintank.io integration. I'm having unexpected behavior regarding y-axis autoscaling 

Here is a [snapshot to demonstrate the problem](https://snapshot.raintank.io/dashboard/snapshot/08RyBeQngicggx6I6BHppG0Kj7eDD6dP)

The default view when opening the link is fine.

But, [zoom in on the main part of the data at around -160 m](https://snapshot.raintank.io/dashboard/snapshot/08RyBeQngicggx6I6BHppG0Kj7eDD6dP?orgId=2&from=1530186495330&to=1530222937751) in the same snapshot, and now there is lots of empty space between in the range [0, -150]
I'd expect the y-axis to be zoomed to roughly the range [-150, -180]. In Grafana proper this zoom would be done automatically, but in the snapshot the y-axis zoom is disabled.

Default view (ok): 

![screenshot from 2018-09-05 12-30-56](https://user-images.githubusercontent.com/3074453/45084706-a0796d80-b107-11e8-8209-74f5bb499ecf.png)

Zoomed in without y-axis rescaling (in snapshot):

![screenshot from 2018-09-05 12-30-44](https://user-images.githubusercontent.com/3074453/45084734-aff8b680-b107-11e8-9130-a9c711095ea0.png)

Zoomed in *with* y-axis scaling (grafana proper, what I'd expect in the snapshot):

![screenshot from 2018-09-05 12-33-16](https://user-images.githubusercontent.com/3074453/45084894-07972200-b108-11e8-9392-8d8a5148ad6d.png)

---

I looked for solutions in the docs and community but didn't find any. I see how this could be a configuration error on my part, though.

**Comment by torkelo** [comment]
snapshots only store the data your query returns at the zoom level you had when you created the snapshot. So when you zoom in on a snapshot no new query or data is fetched. In the real live dashboard you will see more detail when you zoom in, in a snapshot you will not seem more detail

**Comment by jarmokivekas** [comment]
The dataset has a few outliers near 0 at the beginning and end, but most of the data is in the -160 range. The zoom only discards a few data points, so the data is there to do the zoom, it's just that the y-axis isn't scaled in a way to actually make the data readable for human eyes. The data density is low enough that query for the snapshot returns *all* of my data.

But maybe this is somewhat of an edge case. I can live with snapshots of the zoomed-in data, but it loses a little bit of context when the head and tail of the data is lost.
