### ISSUE TITLE
[Bug]Alerting issue: Not giving expected change in alert when there is change is alerting series.

### ISSUE THREAD

**Issue by amitkumarcn** [grafana/grafana#13164]
### What Grafana version are you using?
5.2.3
### What datasource are you using?
graphite
### What OS are you running grafana on?
macOS high sierra-10.13.6
### What did you do?
Tried configuring alerting for multi series metrics. As per document, if its alerted by series 1, it will not sent notification for alert in series 2.
What i tried : 
1. made series 1 to breach threshold and let alerting trigger.Notification says: series 1 having alert.
2. after sometime, made series 2 to breach threshold.(Not expecting any alert as its already alerting).
3. Fixed series 1.

### What was the expected result?
Expected result: Alert should have recovered as it was for series 1 and re triggered for series 2.
### What happened instead?
What i see is, still showing alert for series 1.

**Comment by marefr** [comment]
We'll need more detailed information, but I think this may be expected. Screenshots would greatly help. 

Think that #12145 included in upcoming v5.3 will make it behave as you expects.

**Comment by amitkumarcn** [comment]
Yes it will. Thanks @marefr
