### ISSUE TITLE
ldap configuration

### ISSUE THREAD

**Issue by ptempier** [grafana/grafana#13163]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
grafana 5.2.2
### What datasource are you using?
postgres + zabbix , but it s not related
### What OS are you running grafana on?
archlinux (auth is via openldap set up via fusiondirectory)
### What did you do?
try to setup ldap with orgs and roles permissions

### What was the expected result?
the auth part works properly, the roles and org part doesnt  works.

### What happened instead?
Login with an ldap account with the same name than a an existing local account is permitted.
You can user either password, you are allowed to change the local password, still other settings seems to come from ldap

All permissions given to the user are removed if he logs out/in grafana, the user will become only part of the default organisation with viewer permissions (this is with auto_assign_org = false).
This setting is actually also changed in the db.

If i want to play along, and get a user without any permissions to login first, so the account appear in the user list and i can set the permissions later (gitlab and rancher do that). It doesn't seems to be possible to have a user login without at least giving him acces viewer access to an organisation.

The oposite would be to think that all configuration is taken from ldap and nothing is local (hence why it s reset at login).
But it's possible to go in the user list and edit the configuration for a user which never existed in local and comes from ldap.

In the configuration the parameter group_dn is actually holding the configuration for the cn of the group

Could the org_id parameter become an array?
So i can give the same group a permissions to a lot of orgs without adding 3 line per new organisation.

**Comment by torkelo** [comment]
> If i want to play along, and get a user without any permissions to login first, so the account appear in the user list and i can set the permissions later (gitlab and rancher do that). It doesn't seems to be possible to have a user login without at least giving him acces viewer access to an organisation.

If you remove all group mappings in the ldap_toml file then you can define org role permissions in Grafana otherwise the orgs and role permissions defined ldap toml will be the one grafana will use. 

> Could the org_id parameter become an array?

There is a feature request for this. https://github.com/grafana/grafana/issues/2608

> In the configuration the parameter group_dn is actually holding the configuration for the cn of the group

what do you mean? It can depend on your ldap system I think, if your ldap supports member_of then group_dn is a full DN path to the group.
