### ISSUE TITLE
Bug in histogram in graph panel

### ISSUE THREAD

**Issue by arielkempf** [grafana/grafana#13161]
Information:
### What Grafana version are you using?
4.6.0, 4.6.4, 5.2.2, 5.2.3

### What datasource are you using?
Custom

### What OS are you running grafana on?
Windows 10

### What did you do?
Have two histograms working fine in Grafana 4.6.0 and 4.6.4. The same data in Grafana 5.2.2 and 5.2.3 produce failed histograms. The first one with wrong x-axis scaling and missing bins, the second one with x-axis scale ok but missing bins as well. See attached images.
On time mode (with time in x-axis), they are displayed correctly in both versions of Grafana.
Running both server and client on Windows 10. Tested with Firefox, Opera and MS Edge. Both histograms are with fixed number of bins.

### What was the expected result?
![hist1-4 6 0](https://user-images.githubusercontent.com/115149/45094599-27bbe680-b0f2-11e8-9e91-5b0eb5557caa.PNG)
![hist2-4 6 0](https://user-images.githubusercontent.com/115149/45094606-2b4f6d80-b0f2-11e8-9f33-5fe154ed8ec5.PNG)

### What happened instead?
![hist1-5 2 2](https://user-images.githubusercontent.com/115149/45094651-415d2e00-b0f2-11e8-8d2f-c630fec6b881.PNG)
![hist2-5 2 2](https://user-images.githubusercontent.com/115149/45094665-49b56900-b0f2-11e8-8359-b94167936a6d.PNG)

**Comment by torkelo** [comment]
can you paste the raw result from your metric query? (found in metrics tab query inspector)

**Comment by arielkempf** [comment]
Here follows the data from our custom datasource plugin:
`
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/2",
    "data": {
      "timezone": "browser",
      "panelId": 7,
      "dashboardId": 2,
      "range": {
        "from": "2017-01-21T05:00:00.000Z",
        "to": "2017-01-27T08:00:00.000Z",
        "raw": {
          "from": "2017-01-21T05:00:00.000Z",
          "to": "2017-01-27T08:00:00.000Z"
        }
      },
      "rangeRaw": {
        "from": "2017-01-21T05:00:00.000Z",
        "to": "2017-01-27T08:00:00.000Z"
      },
      "interval": "15m",
      "intervalMs": 900000,
      "targets": [
        {
          "target": "111.DACA.PV",
          "refId": "A",
          "type": "timeserie"
        }
      ],
      "maxDataPoints": 606,
      "scopedVars": {
        "__interval": {
          "text": "15m",
          "value": "15m"
        },
        "__interval_ms": {
          "text": "900000",
          "value": "900000"
        }
      }
    },
    "params": {
      "op": "READTAG",
      "fmt": "JSON2",
      "tf": "UNX",
      "obj": "111.DACA.PV",
      "drv": "TriHDA2",
      "maxValues": 606,
      "sampleTime": 900,
      "startTime": "2017-01-21 03:00:00",
      "endTime": "2017-01-27 06:00:00",
      "convertUTC": 1
    }
  },
  "response": {
    "Data": {
      "NroVars": 1,
      "Variables": [
        {
          "Name": "111.DACA.PV",
          "Values": [
            119.29245,
            119.281006,
            119.343948,
            119.332504,
            119.324875,
            119.355392,
            119.391632,
            119.301987,
            119.296265,
            119.296265,
            119.307709,
            119.389725,
            119.32869,
            119.364929,
            119.401169,
            119.374466,
            119.401169,
            119.410706,
            119.372559,
            119.298172,
            119.452667,
            119.38591,
            119.317245,
            119.267654,
            119.195175,
            119.269562,
            119.269562,
            119.261932,
            119.265747,
            119.296265,
            119.315338,
            119.368744,
            119.324875,
            119.294357,
            119.252396,
            119.25621,
            119.279099,
            119.315338,
            119.200897,
            119.281006,
            119.279099,
            119.307709,
            119.300079,
            119.305801,
            119.315338,
            119.290543,
            119.315338,
            119.282913,
            119.342041,
            119.330597,
            119.277191,
            119.231415,
            119.324875,
            119.286728,
            119.290543,
            119.324875,
            119.303894,
            119.296265,
            119.305801,
            119.303894,
            119.279099,
            119.315338,
            119.237137,
            119.380188,
            119.374466,
            119.384003,
            119.359207,
            119.363022,
            119.326782,
            119.391632,
            119.359207,
            119.359207,
            119.326782,
            119.374466,
            119.397354,
            119.336319,
            119.351578,
            119.378281,
            119.279099,
            119.334412,
            119.393539,
            119.343948,
            119.340134,
            119.296265,
            119.317245,
            119.342041,
            119.330597,
            119.244766,
            119.242859,
            119.242859,
            119.288635,
            119.315338,
            119.265747,
            119.29245,
            119.298172,
            119.239044,
            119.311523,
            119.282913,
            119.303894,
            119.286728,
            119.301987,
            119.279099,
            119.279099,
            119.261932,
            119.340134,
            119.252396,
            119.235229,
            119.261932,
            119.273376,
            119.336319,
            119.26384,
            119.281006,
            119.271469,
            119.282913,
            119.269562,
            119.240952,
            119.246674,
            119.240952,
            119.265747,
            119.246674,
            119.223785,
            119.225693,
            119.189453,
            119.145584,
            119.208527,
            119.178009,
            119.244766,
            119.223785,
            119.240952,
            119.208527,
            119.252396,
            119.244766,
            119.254303,
            119.242859,
            119.279099,
            119.309616,
            119.214249,
            119.212341,
            119.19136,
            119.178009,
            119.195175,
            119.25621,
            119.311523,
            119.216156,
            119.239044,
            119.326782,
            119.223785,
            119.235229,
            119.319153,
            119.153214,
            119.137955,
            119.122696,
            119.082642,
            119.00444,
            119.073105,
            119.103622,
            119.103622,
            119.124603,
            119.086456,
            119.111252,
            119.139862,
            119.126511,
            119.16275,
            119.143677,
            119.189453,
            119.193268,
            119.281006,
            119.307709,
            119.286728,
            119.330597,
            119.338226,
            119.309616,
            119.223785,
            119.193268,
            119.300079,
            119.322968,
            119.309616,
            119.374466,
            119.282913,
            119.32106,
            119.361115,
            119.364929,
            119.342041,
            119.309616,
            119.309616,
            119.313431,
            119.368744,
            119.305801,
            119.313431,
            119.343948,
            119.416428,
            119.29245,
            119.307709,
            119.334412,
            119.351578,
            119.319153,
            119.351578,
            119.301987,
            119.334412,
            119.336319,
            119.330597,
            119.330597,
            119.269562,
            119.311523,
            119.307709,
            119.286728,
            119.309616,
            119.380188,
            119.281006,
            119.334412,
            119.32106,
            119.260025,
            119.231415,
            119.326782,
            119.288635,
            119.183731,
            119.342041,
            119.258118,
            119.343948,
            119.16275,
            119.250488,
            119.242859,
            119.237137,
            119.248581,
            119.25621,
            119.208527,
            119.197083,
            119.212341,
            119.221878,
            119.181824,
            119.179916,
            119.206619,
            119.225693,
            119.200897,
            119.258118,
            119.16275,
            119.206619,
            119.143677,
            119.168472,
            119.178009,
            119.235229,
            119.284821,
            119.244766,
            119.286728,
            119.324875,
            119.311523,
            119.141769,
            119.13414,
            119.158936,
            119.017792,
            119.031143,
            119.034958,
            118.998718,
            118.987274,
            119.023514,
            119.010162,
            119.021606,
            119.021606,
            119.095993,
            119.046402,
            119.071198,
            118.991089,
            119.034958,
            118.987274,
            119.038773,
            119.023514,
            118.989182,
            119.013977,
            119.033051,
            119.139862,
            119.137955,
            119.168472,
            119.178009,
            119.151306,
            119.2276,
            119.258118,
            119.298172,
            119.29245,
            119.210434,
            119.282913,
            119.298172,
            119.296265,
            119.19136,
            119.2276,
            119.223785,
            119.189453,
            119.174194,
            119.206619,
            119.153214,
            119.187546,
            119.132233,
            119.244766,
            119.147491,
            119.183731,
            119.185638,
            119.221878,
            119.282913,
            119.233322,
            119.193268,
            119.246674,
            119.208527,
            119.221878,
            119.246674,
            119.284821,
            119.214249,
            119.221878,
            119.197083,
            119.225693,
            119.267654,
            119.290543,
            119.176102,
            119.113159,
            119.219971,
            119.281006,
            119.286728,
            119.2276,
            119.240952,
            119.120789,
            119.223785,
            119.208527,
            119.185638,
            119.260025,
            119.16275,
            119.204712,
            119.176102,
            119.216156,
            119.210434,
            119.223785,
            119.284821,
            119.250488,
            119.160843,
            119.193268,
            119.239044,
            119.193268,
            119.124603,
            119.157028,
            119.132233,
            119.225693,
            119.273376,
            119.206619,
            119.313431,
            119.221878,
            119.250488,
            119.305801,
            119.246674,
            119.322968,
            119.380188,
            119.269562,
            119.231415,
            119.311523,
            119.214249,
            119.240952,
            119.195175,
            119.252396,
            119.258118,
            119.294357,
            119.301987,
            119.342041,
            119.240952,
            119.298172,
            119.273376,
            119.330597,
            119.223785,
            119.200897,
            119.229507,
            119.317245,
            119.279099,
            119.248581,
            119.309616,
            119.261932,
            119.250488,
            119.267654,
            119.242859,
            119.305801,
            119.231415,
            119.237137,
            119.210434,
            119.214249,
            119.160843,
            119.271469,
            119.181824,
            119.187546,
            119.2276,
            119.204712,
            119.200897,
            119.237137,
            119.158936,
            119.178009,
            119.124603,
            119.115067,
            119.208527,
            119.206619,
            119.216156,
            119.210434,
            119.200897,
            119.267654,
            119.172287,
            119.29245,
            119.269562,
            119.252396,
            119.231415,
            119.187546,
            119.271469,
            119.168472,
            119.267654,
            119.179916,
            119.218063,
            119.179916,
            119.281006,
            119.122696,
            119.16275,
            119.178009,
            119.208527,
            119.223785,
            119.193268,
            119.172287,
            119.128418,
            119.187546,
            119.166565,
            119.168472,
            119.084549,
            119.122696,
            119.109344,
            119.141769,
            119.132233,
            119.19899,
            119.149399,
            119.147491,
            119.118881,
            119.160843,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178,
            119.092178
          ],
          "Qualities": [
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2
          ],
          "Times": [
            "1484974800",
            "1484975700",
            "1484976600",
            "1484977500",
            "1484978400",
            "1484979300",
            "1484980200",
            "1484981100",
            "1484982000",
            "1484982900",
            "1484983800",
            "1484984700",
            "1484985600",
            "1484986500",
            "1484987400",
            "1484988300",
            "1484989200",
            "1484990100",
            "1484991000",
            "1484991900",
            "1484992800",
            "1484993700",
            "1484994600",
            "1484995500",
            "1484996400",
            "1484997300",
            "1484998200",
            "1484999100",
            "1485000000",
            "1485000900",
            "1485001800",
            "1485002700",
            "1485003600",
            "1485004500",
            "1485005400",
            "1485006300",
            "1485007200",
            "1485008100",
            "1485009000",
            "1485009900",
            "1485010800",
            "1485011700",
            "1485012600",
            "1485013500",
            "1485014400",
            "1485015300",
            "1485016200",
            "1485017100",
            "1485018000",
            "1485018900",
            "1485019800",
            "1485020700",
            "1485021600",
            "1485022500",
            "1485023400",
            "1485024300",
            "1485025200",
            "1485026100",
            "1485027000",
            "1485027900",
            "1485028800",
            "1485029700",
            "1485030600",
            "1485031500",
            "1485032400",
            "1485033300",
            "1485034200",
            "1485035100",
            "1485036000",
            "1485036900",
            "1485037800",
            "1485038700",
            "1485039600",
            "1485040500",
            "1485041400",
            "1485042300",
            "1485043200",
            "1485044100",
            "1485045000",
            "1485045900",
            "1485046800",
            "1485047700",
            "1485048600",
            "1485049500",
            "1485050400",
            "1485051300",
            "1485052200",
            "1485053100",
            "1485054000",
            "1485054900",
            "1485055800",
            "1485056700",
            "1485057600",
            "1485058500",
            "1485059400",
            "1485060300",
            "1485061200",
            "1485062100",
            "1485063000",
            "1485063900",
            "1485064800",
            "1485065700",
            "1485066600",
            "1485067500",
            "1485068400",
            "1485069300",
            "1485070200",
            "1485071100",
            "1485072000",
            "1485072900",
            "1485073800",
            "1485074700",
            "1485075600",
            "1485076500",
            "1485077400",
            "1485078300",
            "1485079200",
            "1485080100",
            "1485081000",
            "1485081900",
            "1485082800",
            "1485083700",
            "1485084600",
            "1485085500",
            "1485086400",
            "1485087300",
            "1485088200",
            "1485089100",
            "1485090000",
            "1485090900",
            "1485091800",
            "1485092700",
            "1485093600",
            "1485094500",
            "1485095400",
            "1485096300",
            "1485097200",
            "1485098100",
            "1485099000",
            "1485099900",
            "1485100800",
            "1485101700",
            "1485102600",
            "1485103500",
            "1485104400",
            "1485105300",
            "1485106200",
            "1485107100",
            "1485108000",
            "1485108900",
            "1485109800",
            "1485110700",
            "1485111600",
            "1485112500",
            "1485113400",
            "1485114300",
            "1485115200",
            "1485116100",
            "1485117000",
            "1485117900",
            "1485118800",
            "1485119700",
            "1485120600",
            "1485121500",
            "1485122400",
            "1485123300",
            "1485124200",
            "1485125100",
            "1485126000",
            "1485126900",
            "1485127800",
            "1485128700",
            "1485129600",
            "1485130500",
            "1485131400",
            "1485132300",
            "1485133200",
            "1485134100",
            "1485135000",
            "1485135900",
            "1485136800",
            "1485137700",
            "1485138600",
            "1485139500",
            "1485140400",
            "1485141300",
            "1485142200",
            "1485143100",
            "1485144000",
            "1485144900",
            "1485145800",
            "1485146700",
            "1485147600",
            "1485148500",
            "1485149400",
            "1485150300",
            "1485151200",
            "1485152100",
            "1485153000",
            "1485153900",
            "1485154800",
            "1485155700",
            "1485156600",
            "1485157500",
            "1485158400",
            "1485159300",
            "1485160200",
            "1485161100",
            "1485162000",
            "1485162900",
            "1485163800",
            "1485164700",
            "1485165600",
            "1485166500",
            "1485167400",
            "1485168300",
            "1485169200",
            "1485170100",
            "1485171000",
            "1485171900",
            "1485172800",
            "1485173700",
            "1485174600",
            "1485175500",
            "1485176400",
            "1485177300",
            "1485178200",
            "1485179100",
            "1485180000",
            "1485180900",
            "1485181800",
            "1485182700",
            "1485183600",
            "1485184500",
            "1485185400",
            "1485186300",
            "1485187200",
            "1485188100",
            "1485189000",
            "1485189900",
            "1485190800",
            "1485191700",
            "1485192600",
            "1485193500",
            "1485194400",
            "1485195300",
            "1485196200",
            "1485197100",
            "1485198000",
            "1485198900",
            "1485199800",
            "1485200700",
            "1485201600",
            "1485202500",
            "1485203400",
            "1485204300",
            "1485205200",
            "1485206100",
            "1485207000",
            "1485207900",
            "1485208800",
            "1485209700",
            "1485210600",
            "1485211500",
            "1485212400",
            "1485213300",
            "1485214200",
            "1485215100",
            "1485216000",
            "1485216900",
            "1485217800",
            "1485218700",
            "1485219600",
            "1485220500",
            "1485221400",
            "1485222300",
            "1485223200",
            "1485224100",
            "1485225000",
            "1485225900",
            "1485226800",
            "1485227700",
            "1485228600",
            "1485229500",
            "1485230400",
            "1485231300",
            "1485232200",
            "1485233100",
            "1485234000",
            "1485234900",
            "1485235800",
            "1485236700",
            "1485237600",
            "1485238500",
            "1485239400",
            "1485240300",
            "1485241200",
            "1485242100",
            "1485243000",
            "1485243900",
            "1485244800",
            "1485245700",
            "1485246600",
            "1485247500",
            "1485248400",
            "1485249300",
            "1485250200",
            "1485251100",
            "1485252000",
            "1485252900",
            "1485253800",
            "1485254700",
            "1485255600",
            "1485256500",
            "1485257400",
            "1485258300",
            "1485259200",
            "1485260100",
            "1485261000",
            "1485261900",
            "1485262800",
            "1485263700",
            "1485264600",
            "1485265500",
            "1485266400",
            "1485267300",
            "1485268200",
            "1485269100",
            "1485270000",
            "1485270900",
            "1485271800",
            "1485272700",
            "1485273600",
            "1485274500",
            "1485275400",
            "1485276300",
            "1485277200",
            "1485278100",
            "1485279000",
            "1485279900",
            "1485280800",
            "1485281700",
            "1485282600",
            "1485283500",
            "1485284400",
            "1485285300",
            "1485286200",
            "1485287100",
            "1485288000",
            "1485288900",
            "1485289800",
            "1485290700",
            "1485291600",
            "1485292500",
            "1485293400",
            "1485294300",
            "1485295200",
            "1485296100",
            "1485297000",
            "1485297900",
            "1485298800",
            "1485299700",
            "1485300600",
            "1485301500",
            "1485302400",
            "1485303300",
            "1485304200",
            "1485305100",
            "1485306000",
            "1485306900",
            "1485307800",
            "1485308700",
            "1485309600",
            "1485310500",
            "1485311400",
            "1485312300",
            "1485313200",
            "1485314100",
            "1485315000",
            "1485315900",
            "1485316800",
            "1485317700",
            "1485318600",
            "1485319500",
            "1485320400",
            "1485321300",
            "1485322200",
            "1485323100",
            "1485324000",
            "1485324900",
            "1485325800",
            "1485326700",
            "1485327600",
            "1485328500",
            "1485329400",
            "1485330300",
            "1485331200",
            "1485332100",
            "1485333000",
            "1485333900",
            "1485334800",
            "1485335700",
            "1485336600",
            "1485337500",
            "1485338400",
            "1485339300",
            "1485340200",
            "1485341100",
            "1485342000",
            "1485342900",
            "1485343800",
            "1485344700",
            "1485345600",
            "1485346500",
            "1485347400",
            "1485348300",
            "1485349200",
            "1485350100",
            "1485351000",
            "1485351900",
            "1485352800",
            "1485353700",
            "1485354600",
            "1485355500",
            "1485356400",
            "1485357300",
            "1485358200",
            "1485359100",
            "1485360000",
            "1485360900",
            "1485361800",
            "1485362700",
            "1485363600",
            "1485364500",
            "1485365400",
            "1485366300",
            "1485367200",
            "1485368100",
            "1485369000",
            "1485369900",
            "1485370800",
            "1485371700",
            "1485372600",
            "1485373500",
            "1485374400",
            "1485375300",
            "1485376200",
            "1485377100",
            "1485378000",
            "1485378900",
            "1485379800",
            "1485380700",
            "1485381600",
            "1485382500",
            "1485383400",
            "1485384300",
            "1485385200",
            "1485386100",
            "1485387000",
            "1485387900",
            "1485388800",
            "1485389700",
            "1485390600",
            "1485391500",
            "1485392400",
            "1485393300",
            "1485394200",
            "1485395100",
            "1485396000",
            "1485396900",
            "1485397800",
            "1485398700",
            "1485399600",
            "1485400500",
            "1485401400",
            "1485402300",
            "1485403200",
            "1485404100",
            "1485405000",
            "1485405900",
            "1485406800",
            "1485407700",
            "1485408600",
            "1485409500",
            "1485410400",
            "1485411300",
            "1485412200",
            "1485413100",
            "1485414000",
            "1485414900",
            "1485415800",
            "1485416700",
            "1485417600",
            "1485418500",
            "1485419400",
            "1485420300",
            "1485421200",
            "1485422100",
            "1485423000",
            "1485423900",
            "1485424800",
            "1485425700",
            "1485426600",
            "1485427500",
            "1485428400",
            "1485429300",
            "1485430200",
            "1485431100",
            "1485432000",
            "1485432900",
            "1485433800",
            "1485434700",
            "1485435600",
            "1485436500",
            "1485437400",
            "1485438300",
            "1485439200",
            "1485440100",
            "1485441000",
            "1485441900",
            "1485442800",
            "1485443700",
            "1485444600",
            "1485445500",
            "1485446400",
            "1485447300",
            "1485448200",
            "1485449100",
            "1485450000",
            "1485450900",
            "1485451800",
            "1485452700",
            "1485453600",
            "1485454500",
            "1485455400",
            "1485456300",
            "1485457200",
            "1485458100",
            "1485459000",
            "1485459900",
            "1485460800",
            "1485461700",
            "1485462600",
            "1485463500",
            "1485464400",
            "1485465300",
            "1485466200",
            "1485467100",
            "1485468000",
            "1485468900",
            "1485469800",
            "1485470700",
            "1485471600",
            "1485472500",
            "1485473400",
            "1485474300",
            "1485475200",
            "1485476100",
            "1485477000",
            "1485477900",
            "1485478800",
            "1485479700",
            "1485480600",
            "1485481500",
            "1485482400",
            "1485483300",
            "1485484200",
            "1485485100",
            "1485486000",
            "1485486900",
            "1485487800",
            "1485488700",
            "1485489600",
            "1485490500",
            "1485491400",
            "1485492300",
            "1485493200",
            "1485494100",
            "1485495000",
            "1485495900",
            "1485496800",
            "1485497700",
            "1485498600",
            "1485499500",
            "1485500400",
            "1485501300",
            "1485502200",
            "1485503100"
          ]
        }
      ]
    }
  }
}
`

**Comment by torkelo** [comment]
do you have auto buckets on or have you specified bucket count?

**Comment by arielkempf** [comment]
It is fixed in 70 buckets. If I change the values or leave it auto, the missing buckets also change. For instance, for the second graph it looks like there is a threshold in 40 buckets. Above that value, the histogram is bugged. Below or equal, it works ok. In auto, it works ok, since it seems to select 40 buckets.

**Comment by arielkempf** [comment]
For the first graph, the threshold is 18 and in auto it's still shown bugged.

**Comment by torkelo** [comment]
can you show settings for each image? I am been unable to replicate any issue so far with standard data sources.

**Comment by arielkempf** [comment]
Here follows the relevant configs. The rest is not set/default. They are the same for both images.
![image](https://user-images.githubusercontent.com/115149/45310778-9be4f880-b4fd-11e8-9141-f50a500e1c39.png)
![image](https://user-images.githubusercontent.com/115149/45310802-a901e780-b4fd-11e8-906a-1d84918aed37.png)
![image](https://user-images.githubusercontent.com/115149/45310818-b9b25d80-b4fd-11e8-9b3a-b4abb1a2cf85.png)

**Comment by arielkempf** [comment]
Were you able to load the data I sent into a Graph panel to check? It's strange that the same data works in 4.6 versions and is not working anymore in 5.2 versions.

**Comment by speakmore** [comment]
+1 any update? I also see missing bins in histogram where are supposed to have data.

**Comment by melrom** [comment]
I have a similar problem with elastic data source, tried to fix the bin size at 6, but grafana appears to totally ignore this and give me bins ranging from 4 bins to 12 bins. Grafana 5.4.0...

**Comment by daniel-dnil** [comment]
I'm seeing this issue as well in Grafana 5.4.3, but in my case the "auto" buckets setting is producing results which gives missing bins. I need to limit the number of buckets manually in order to not loose data in the histogram which I think is a rather severe issue.
