### ISSUE TITLE
[Feature] Natural sorting in templating variables

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#13179]
### What Grafana version are you using?

5.2.3

### What datasource are you using?

Prometheus, but doesn't really matter

### What do you want?

I have a bunch of machies called `{number1}{string}{number1}` and I want to sort them as version strings (in `sort -V` sense):

```
$ echo -e '16foo13\n16foo1\n16foo3' | sort -V
16foo1
16foo3
16foo13
```

Grafana can now sort only alphabetically and numerically and both give weird results:

```
$ echo -e '16foo13\n16foo1\n16foo3' | sort
16foo1
16foo13
16foo3
```

```
$ echo -e '16foo13\n16foo1\n16foo3' | sort -n
16foo1
16foo13
16foo3
```

My suggestion is to add version sort to this dropdown:

![image](https://user-images.githubusercontent.com/89186/45177006-8eaacf80-b1c6-11e8-9a74-f061afd1fbf9.png)

**Comment by bobrik** [comment]
Having an option to do the same sort in legend would be awesome too.

**Comment by sylr** [comment]
I was about to make the same request. I'm using prometheus histograms and natural sorting would be a great help for legend and tooltip: 

![screenshot_21](https://user-images.githubusercontent.com/153052/48837515-e0a2d080-ed85-11e8-8276-04edb66a26ba.png)

**Comment by torkelo** [comment]
For graph:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts#L450

for variable values:
https://github.com/grafana/grafana/blob/master/public/app/features/templating/query_variable.ts#L185

We should probably extract these to a common utility function.

**Comment by Karsonito** [comment]
Please implement such sorting
It's very important and useful for dashboard filters

**Comment by Karsonito** [comment]
Hi Grafana team!
Any chance it will be implemented?

**Comment by VladoPortos** [comment]
Still no luck for natural sorting ? since 2018

**Comment by derekrprice** [comment]
Natural sorting is a [built-in](https://www.php.net/manual/en/function.natsort.php) in PHP.  What language is Grafana implemented in?

**Comment by derekrprice** [comment]
Since 9.6, Postgres supports natural sorts.  You could set it on the column in question: https://stackoverflow.com/questions/9173558/postgresql-order-by-issue-natural-sort#answer-67975489

**Comment by bobrik** [comment]
[According to SO](https://stackoverflow.com/questions/2802341/natural-sort-of-alphanumerical-strings-in-javascript), `localeCompare can` be used here. It seems to work in my brief test:

<img width="651" alt="image" src="https://github.com/grafana/grafana/assets/89186/38679c73-d52c-4aeb-b62d-65d9662538c9">

I'll see if I can come up with a PR.

**Comment by bobrik** [comment]
I opened #78024.

**Comment by bewing** [comment]
I'm slightly confused as to what's going on, but I'm not seeing this working in 11.3.0:

<img width="1007" height="550" alt="Image" src="https://github.com/user-attachments/assets/5679a0ae-9c2e-4a39-b513-e31f825c6957" />

The list in the dropdown variable selector also isn't naturally ordered.

Playing around in a JS playground, I think it **should** work:


```javascript
const arr = ["Ethernet1/1", "Ethernet10/1", "Ethernet2/1", "Ethernet11/1"]
arr.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
console.log(arr)

// prints 
(4) ["Ethernet1/1", "Ethernet2/1", "Ethe...]
0: "Ethernet1/1"
1: "Ethernet2/1"
2: "Ethernet10/1"
3: "Ethernet11/1"

```

Am I mis-understanding where this change is applied?  Natural sorting in the legend is functioning

<img width="105" height="131" alt="Image" src="https://github.com/user-attachments/assets/e062e7e4-0634-4107-968d-efae6fd29297" />

**Comment by bobrik** [comment]
I tried it on v12.2.0 and it works as expected:

<img width="523" height="203" alt="Image" src="https://github.com/user-attachments/assets/881ab957-2459-466e-82d4-b4b528aad821" />

<img width="390" height="560" alt="Image" src="https://github.com/user-attachments/assets/f8d62a38-de6e-4091-8c27-0dece0383b29" />

One minor problem is that I needed to run the query to apply the sorting, but that goes for any sorting type.

The dropdown looks right too:

<img width="253" height="167" alt="Image" src="https://github.com/user-attachments/assets/2769bcb1-5018-450a-b75c-592098e55087" />

If you're not constrained by any third party plugins, I would recommend upgrading.
