### ISSUE TITLE
InfluxDB double query doesn't work because semicolon in URL is not encoded

### ISSUE THREAD

**Issue by zzzuzik** [grafana/grafana#1317]
Hi @torkelo, sorry for bothering you again.

I'm trying to use double query (separated with semicolon) in template variables as a mechanism to fall back to a default value if I don't get any results from InfluxDB, like `[]`
This works perfectly fine from its UI:
``` 
select count(distinct(ip)) from merge(/$location\.$servers\.connections/); select min(default) from default.response
```
and the response is
```
{"name":"merged","columns":["time","count"],"points":[[0,6]]},[{"name":"default.response","columns":["time","min"],"points":[[0,0]]}]
```
if I don't have any IPs I will get just 0..

When I try to use the same query from Grafana, I always get only one result.
I noticed that InfluxDB has percent-encoding for the semicolon, whereas Grafana passes straight `;`
If I replace `;` with `%3B` I get both results.

Could it be fixed please?

**Comment by torkelo** [comment]
Seems to be an angularjs issue, https://github.com/angular/angular.js/issues/9224 

Will try to make a work around that tomorrow.

**Comment by zzzuzik** [comment]
Thanks a lot!

**Comment by zzzuzik** [comment]
Hi @torkelo, any news on this?

**Comment by torkelo** [comment]
no not yet

**Comment by torkelo** [comment]
seems to be an influxdb 0.8 issue, so will close as that datasource is no longer under development
