### ISSUE TITLE
Grafana send alerts without reason

### ISSUE THREAD

**Issue by ondrejFuchs** [grafana/grafana#13174]
Please include this information:
### What Grafana version are you using?
grafana:5.0.4
### What datasource are you using?
influxdb:1.5.1
### What OS are you running grafana on?
Ubuntu 16.04.5 LTS

We setup alerts in grafana as on picture1.  We want to send alerts if any value (neural_network) in influxdb will be bigger than 0,9 , send alert. In alerts we have max (if maximum from 5 minutes interval), send email notification. I don't understand why there is (on picture) alert.
![grafana-alert1](https://user-images.githubusercontent.com/34134418/45157190-af801e80-b1e0-11e8-823e-4c768c4e065a.png)

Also add picture of metrics setting.
![grafana-alets2](https://user-images.githubusercontent.com/34134418/45157194-b313a580-b1e0-11e8-8ae8-0317a1a31bdf.png)

Thanks for any response or help.

**Comment by zhongqin0820** [comment]
From your screenshots, the condition means if the `max()` value from 5 minute ago to now higher than 0.9, it will send an alert.
You can check the value from this range to see whether it is a real bug or just your data issues.

**Comment by torkelo** [comment]
closing this as there has been no update with more details
