### ISSUE TITLE
Trouble with Kubernetes volumes and the 5.1.3+ Docker image

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#13187]
Several users have reported issues with running the  5.1.3+ Docker image on Kubernetes together with persistant storage.

Migrated from the deprecated grafana-docker repo, original issue: https://github.com/grafana/grafana-docker/issues/167

**Comment by RyanHartje** [comment]
The issue you're referring to isn't with the base image, its with the volume permissions when someone tries to use a persisted volume. This would make more sense in the helm chart (which I've opened already), or other projects that setup grafana and PVs.

**Comment by xlson** [comment]
@RyanHartje is there anything we could do on our end to make this work better or are the issues completely based on how the helm chart works? I'm not that knowledgeable about Kubernetes myself and have been meaning to look into this.

**Comment by RyanHartje** [comment]
It's more of a workflow issue. If you are familiar with linux permissions, within the docker image for grafana, we create the user grafana, with a uid of 472:
https://github.com/grafana/grafana/blob/master/Dockerfile#L40
https://github.com/grafana/grafana/blob/master/Dockerfile#L61

We then give this user parts of the filesystem ownership here:
https://github.com/grafana/grafana/blob/master/Dockerfile#L69

The issue being reported is when helm or something else mounts a volume over these directories to persist that data, the ownership is changed to the default.

Here's a walk through of issue replication and identification. 

Steps:

## Start Minikube
```sh
▶ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 160.27 MB / 160.27 MB [==================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
```

## Init Helm
```
▶ helm init
$HELM_HOME has been configured at /Users/ryan/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
```

## Modify Grafana values to persist data
Copy default values file (https://github.com/helm/charts/blob/master/stable/grafana/values.yaml)

Modify:
```
 85 persistence:
 86   enabled: false
 87   # storageClassName: default
 88   # accessModes:
 89   #   - ReadWriteOnce
 90   # size: 10Gi
 91   # annotations: {}
 92   # subPath: ""
 93   # existingClaim:
```

to

```
 85 persistence:
 86   enabled: true
 87   accessModes:
 88     - ReadWriteOnce
 89   size: 10Gi
```

## Run helm install 

```
▶ helm install stable/grafana -f ./values.yml
NAME:   linting-umbrellabird
LAST DEPLOYED: Fri Sep  7 09:18:15 2018
NAMESPACE: default
STATUS: DEPLOYED
[truncated]
```

## Inspect persisted volume permissions 

Here's the deployment template for Grafana in it's helm chart:
https://github.com/helm/charts/blob/master/stable/grafana/templates/deployment.yaml#L256 - enables the PVC
https://github.com/helm/charts/blob/master/stable/grafana/templates/deployment.yaml#L147 - 

Since we see it will be mounted at /var/lib/grafana, let's check out perms in there:
```
▶ kubectl exec linting-umbrellabird-grafana-fccdbc468-9wjc6 -- stat /var/lib/grafana
  File: /var/lib/grafana
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 1572866     Links: 3
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-09-07 13:18:15.591558589 +0000
Modify: 2018-09-07 13:18:32.858762207 +0000
Change: 2018-09-07 13:18:32.858762207 +0000
 Birth: -


▶ kubectl exec linting-umbrellabird-grafana-fccdbc468-9wjc6 -- ls -ahl /var/lib/grafana
total 400K
drwxrwxrwx 3 root    root    4.0K Sep  7 13:18 .
drwxr-xr-x 1 root    root    4.0K May 16 18:25 ..
-rw-r--r-- 1 grafana grafana 384K Sep  7 13:18 grafana.db
drwxr-xr-x 2 grafana grafana 4.0K Sep  7 13:18 plugins
```


What does this look like by default without persistence?
We can helm install the chart with no values file specified to get default behavior.
```
▶ helm install stable/grafana
NAME:   eponymous-ladybug
LAST DEPLOYED: Fri Sep  7 09:29:38 2018
NAMESPACE: default
STATUS: DEPLOYED

▶ kubectl exec eponymous-ladybug-grafana-79cf48b9db-5xfcs -- stat /var/lib/grafana
  File: /var/lib/grafana
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 1057153     Links: 3
Access: (2777/drwxrwsrwx)  Uid: (    0/    root)   Gid: (  472/ grafana)
Access: 2018-09-07 13:30:09.909008138 +0000
Modify: 2018-09-07 13:29:40.667179653 +0000
Change: 2018-09-07 13:29:40.667179653 +0000
 Birth: -

▶ kubectl exec eponymous-ladybug-grafana-79cf48b9db-5xfcs -- ls -ahl /var/lib/grafana
total 400K
drwxrwsrwx 3 root    grafana 4.0K Sep  7 13:29 .
drwxr-xr-x 1 root    root    4.0K May 16 18:25 ..
-rw-r--r-- 1 grafana grafana 384K Sep  7 13:29 grafana.db
drwxr-sr-x 2 grafana grafana 4.0K Sep  7 13:29 plugins
```

For helm specifically, I submitted the following, which I believe fixes this so if persistence is enabled, the chart gives that mount the correct ownership for grafana to work:
https://github.com/helm/charts/pull/6428

**Comment by spali** [comment]
The question ist, should this be solved by the part that makes a persisted volume (the user, docker, kubernetes, etc.).
Or if grafana docker image explizitly supports boostraping container with persisted volume.
In the second case, the common solution would be to set the permissions during startup (entry script or the application itself at least once the data directory is empty or everytime).
This would solve almost all permissions problems But could be against best practice.

**Comment by RyanHartje** [comment]
Turns out, this is fixed now in Helm charts:
https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L24-L26

**Comment by xlson** [comment]
@RyanHartje yeah that looks great. Glad to hear they sorted it. Thanks for explaining how to reproduce the state.

**Comment by xlson** [comment]
@spali The previous image used to set permissions on boot, but this requires the container to run as root and also creates a whole different set of problems. The new image is trying to support running as any user without having to run as root, but it does require any external systems to adhere to the permissions we've set which does not always seem to be the case.

**Comment by spali** [comment]
@xlson thanks for the feedback, makes sense, just don't understand this is not better handled/covered by docker-engine itself independent of the onTop solution. In this case a container user always needs to know implementation details (uid) of a docker image. 🙈

**Comment by ST-DDT** [comment]
@RyanHartje Which version of Kubernetes as you using?
I use 1.10.4 with hostPath volumes (for testing) but the fsGroup property is unknown.

**Comment by RyanHartje** [comment]
@ST-DDT It looks like fsGroup was a part of PSP as of 1.10:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#fsgroupstrategyoptions-v1beta1-policy

Here's how it's implemented in grafana's templates:
https://github.com/helm/charts/blob/master/stable/grafana/templates/podsecuritypolicy.yaml#L37

**Comment by viktorg2** [comment]
I just installed latest grafana image with helm and have same permissions issues  
/code chown: changing ownership of '/var/lib/grafana/dashboards/..2018_09_25_21_23_36.003622224': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards/..data': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards': Read-only file system

**Comment by echo-ray** [comment]
same with docker compose, using the latest version.

And I think grafana should renew some docuement on your website since `/var/lib/grafana/` has been removed. It really misslead me :(

**Comment by srinathganesh** [comment]
that helped me
https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896

**Comment by ST-DDT** [comment]
The following worked for me:

````yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: init-chown-data
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["chown", "-R", "472:472", "/data"]
        volumeMounts:
        - mountPath: /data
          name: grafana-data
      containers:
      - name: grafana-core
        image: grafana/grafana:5.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: grafana-ui
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
      volumes:
      - name: grafana-data
        emptyDir: {} # replace with your storage choice
````

If anyone has suggestions to improve this config, please tell me.

**Comment by kerzhang** [comment]
@ST-DDT , thanks for the sharing. Your solution cleared the pv permission issue for me. However, it caused a new issue. 
I rebuilt the grafana image to install additional plugins by following this method: http://docs.grafana.org/installation/docker/#building-a-custom-grafana-image-with-pre-installed-plugins. 
After following your approach to fixing the pv permission issue, the installed plugins were missing after the pod was deployed. I think it was because of the grafana directory points to the newly created directory.  Now I am struggling with this new problem, no solution yet.

**Comment by xlson** [comment]
@kerzhang You can solve your issue by creating a folder for plugins outside of `/var/lib/grafana` (ex: `/opt/grafana-plugins`) and setting the environment variable `GF_PATHS_PLUGINS` to point to that folder. You will have to make these changes before building your custom Docker image.

**Comment by kerzhang** [comment]
hi @xlson , thank you for the suggestion. So I've followed that direction and updated my Dockerfile as this:
```
ARG GRAFANA_VERSION="latest"

FROM grafana/grafana:${GRAFANA_VERSION}
USER root
RUN mkdir -p /opt/grafana-plugins && chown -R grafana /opt/grafana-plugins
USER grafana
ARG GF_PATHS_PLUGINS="/opt/grafana-plugins"
ARG GF_INSTALL_PLUGINS=""

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi
```

The build result is as this, notice that the plugin was still installed to /var/lib/grafana/plugins:
```
Sending build context to Docker daemon  217.6kB
Step 1/8 : ARG GRAFANA_VERSION="latest"
Step 2/8 : FROM grafana/grafana:${GRAFANA_VERSION}
 ---> 1e1c9863439f
Step 3/8 : USER root
 ---> Running in e5224e937539
Removing intermediate container e5224e937539
 ---> 58c024c0480b
Step 4/8 : RUN mkdir -p /opt/grafana-plugins && chown -R grafana /opt/grafana-plugins
 ---> Running in bc07172f0b1d
Removing intermediate container bc07172f0b1d
 ---> 2a6e967bc47b
Step 5/8 : USER grafana
 ---> Running in a83c47701ccd
Removing intermediate container a83c47701ccd
 ---> 05235a976256
Step 6/8 : ARG GF_PATHS_PLUGINS="/opt/grafana-plugins"
 ---> Running in 1bd40e81d7c1
Removing intermediate container 1bd40e81d7c1
 ---> 53790e169c0a
Step 7/8 : ARG GF_INSTALL_PLUGINS=""
 ---> Running in 7a13327164e6
Removing intermediate container 7a13327164e6
 ---> 3557cffab6c2
Step 8/8 : RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then     OLDIFS=$IFS;         IFS=',';     for plugin in ${GF_INSTALL_PLUGINS}; do         IFS=$OLDIFS;         grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin};     done; fi
 ---> Running in 6c2b186244e9
installing grafana-kubernetes-app @ 1.0.1
from url: https://grafana.com/api/plugins/grafana-kubernetes-app/versions/1.0.1/download
into: /var/lib/grafana/plugins

✔ Installed grafana-kubernetes-app successfully

Restart grafana after installing plugins . <service grafana-server restart>

Removing intermediate container 6c2b186244e9
 ---> 553baf1f6d7b
Successfully built 553baf1f6d7b
```

**Comment by kerzhang** [comment]
@xlson , thank you very much! It finally works this time.

**Comment by Vandersteen** [comment]
For those running k8s on azure with azure files, I finally got it working using:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0472
  - gid=0472
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
```

**Comment by xlson** [comment]
I'm closing this issue for now. Don't see anything we can incorporate in the Dockerfile to make things easier at this point. Perhaps someone with a better understanding and more experience with Kubernetes would like to try to update the documentation.
