### ISSUE TITLE
custom panel js error in grafana-1.9.0

### ISSUE THREAD

**Issue by wjk1982** [grafana/grafana#1318]
I update config.js in grafana-1.9.0 ,as follows

 // Add your own custom panels in config.js
      plugins: {
        // list of plugin panels
    	  panels: {
    		   'custom panel name': { path: '../plugins/custom.panel.example' } 
    	  },
        // requirejs modules in plugins folder that should be loaded
        // for example custom datasources
        dependencies: ['datasource.example']
      }

but can't normal running,the js Error is as follows
![grafana](https://cloud.githubusercontent.com/assets/1272179/5676163/2edb939c-980b-11e4-90e7-658f6a0b830b.png)

**Comment by torkelo** [comment]
Ah, thanks for informing me that the example plugin panel was not working. I fixed it now.
