### ISSUE TITLE
[Feature] Every registered user should be able to create folders

### ISSUE THREAD

**Issue by b2ronn** [grafana/grafana#13189]
Is it possible to make the creation of folders (teams) by an unprivileged user?
When there are many users, it is necessary to spend a lot of time to create personal folders for each user (team).
In Grafana 4 users could create personal organizations. In version 5, there is no such function. But in a personal organization there is no way to easily share dashboards.

type: feature request

**Comment by marefr** [comment]
Not sure what you mean by "an unprivileged user". Are you asking of support for a non-admin or non-editor to create folders? And/or are you asking of support for each user to create a personal folder?

**Comment by torkelo** [comment]
Not sure this is reasonable, viewer role should not be able to create dashboards nor teams

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/11542
