### ISSUE TITLE
[Browser issues] IE error：Invalid dimensions for plot, width = 875, height = 0

### ISSUE THREAD

**Issue by NeverSayFail** [grafana/grafana#13182]
Information:
Grafana version：
5.1.4

datasource：
prometheus

OS：
suse11

Found on IE browser two panels do not appear, reported the following error: 
“Invalid dimensions for plot, width = 875, height = 0”

Chrome,firefox is normal, this problem is not necessary

**Comment by marefr** [comment]
Duplicate of #13118
