### ISSUE TITLE
Build Docker images for arm

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#13186]
We build Grafana for arm64 and armv7 but do not provide Docker images for these platforms. This is something we would like to do in the future as it's becoming more and more popular to use devices like Raspberry Pi to host Grafana.

There is a community PR to solve this in the deprecated grafana-docker repo [here](https://github.com/grafana/grafana-docker/pull/177), unfortunately, it depends on Travis CI and we use CircleCI for the build. CircleCI can't currently build arm images, we hope this is something they rectify in the future.

**Comment by agilob** [comment]
Hi, is this planned for any time soon? I like to run everything in docker on my raspi to avoid polluting /etc/ with config files. Should I wait for it or go with the .debs?

**Comment by xlson** [comment]
@agilob We will implement this sooner or later but I don't have any kind of timeline to offer I'm afraid.

**Comment by Proxx** [comment]
> Hi, is this planned for any time soon? I like to run everything in docker on my raspi to avoid polluting /etc/ with config files. Should I wait for it or go with the .debs?

https://github.com/Proxx/Grafana-armv7

i made a base script that generates the armv7 (raspberry) Dockerfile straight from the original dockerfile binaries

Got the images on dockerhub if you are interested.

**Comment by johanneswuerbach** [comment]
I took a stab at implementing building and pushing arm images from CI https://github.com/grafana/grafana/pull/14617

Feedback welcome 👍

**Comment by xlson** [comment]
Latest `grafana/grafana:master` now has both armv7 and arm64 support thanks to johanneswuerbach.

**Comment by badokun** [comment]
Tested on a raspberri pi 3 b+. When can we expect this to be released?

**Comment by sapkra** [comment]
You can use `grafana/grafana:master`.

**Comment by badokun** [comment]
> You can use `grafana/grafana:master`

Thanks, but I'm looking to prepare a how-to guide and would like to reference a version instead. `master` will be moving forward so may will change at some point

**Comment by dustXman** [comment]
Hey there,
Kudos for all the work so far!

I just tried 
`docker run --name="grafana" -p 3000:3000 grafana/grafana:master`
on my Raspberry PI 3 B running Docker version 18.05.0-ce, build f150324
as a reaction I got nothing ... The image justs stops again. :(
Did the fix for ARM move out of "master"? or is there anything else I need to do for a Raspberry Pi? Is there a possibility to specify a working version?
@badokun Is your How-to somewhere already?

**Comment by Code1110** [comment]
@dustXman: For me this was working fine on a Raspberry Pi 3 B+ using `docker run -d -p 3000:3000 grafana/grafana:master` and Docker 18.06.1-ce. Please note, that most Docker images are not (fully) supported on a Raspberry Pi Zero. Have you tried to run `docker logs grafana` to see the error message?

**Comment by xlson** [comment]
@badokun Grafana v5.4.3 has been released and includes the arm docker images.

**Comment by badokun** [comment]
Thanks so much

**Comment by alexellis** [comment]
@xlson we also build OpenFaaS for ARMHF / ARM64 but semi-automatically.

How did you all get your builds set up / configured? Did you stay with Circle?

**Comment by johanneswuerbach** [comment]
@alexellis on Circle via user land emulation https://github.com/grafana/grafana/pull/14617

**Comment by xlson** [comment]
@alexellis You should be able to find everything you need in the PR @johanneswuerbach supplied.
