### ISSUE TITLE
Key-Value variable

### ISSUE THREAD

**Issue by Kevinsss** [grafana/grafana#13181]
Version: Grafana 5.1.2
OS: windows

Hi, here is the problem, I want to define a K-V variable like `HashMap`.
The variable shows its keys  on the dashboard, when I select keys from `dropdown `list, then I want to retrieve it's value, not the key.
I tried to use two query variables to complete it, like this:
1st variable : `select city_name from city_info`
2nd variable : `select city_code from city_info where city_name = $city_name`
Then, I set graph to `Repeat Model`.
But I select multiple `city_name`, I cannot  use multiple `city_code`  in query( `Graph Metric Tab`)
Is there a way to achieve it?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You should repeat panel by city_code instead, see [demo dashboard](https://play.grafana.org/d/9rDJbRIiz/prometheus-two-variables-with-repeat-of-the-second?orgId=1&var-job=kubernetes-nodes&var-instance=All).
