### ISSUE TITLE
How to integrate Grafana into webapp without using iframe

### ISSUE THREAD

**Issue by geetuvaddeboina** [grafana/grafana#13191]
Is there any way that we can integrate grafana without iframe?can any one help me out

Thanks

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

The answer is basically no. You may be able to integrate by rendering images of panels.

**Comment by geetuvaddeboina** [comment]
@marefr thanks
