### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zhaojiedi1992** [grafana/grafana#13190]
I am a grafana novice, asking how to quote the value I selected in the function.

Here is the picture.
![image](https://user-images.githubusercontent.com/25144156/45213953-a7e97400-b2cb-11e8-8075-bfa1f28b27fc.png)

How to set the value corresponding to the name Host?

![image](https://user-images.githubusercontent.com/25144156/45214026-e41cd480-b2cb-11e8-8aa8-7ecdcbffc780.png)

**Comment by marefr** [comment]
This questions seems related to a datasource plugin you're using which is not part of Grafana core. If you give me the name of the datasource plugin I could help you find a link to their github repository and then I would advise you to create an issue there instead.

In general, questions should be asked on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
