### ISSUE TITLE
Value to text mapping - ranges?

### ISSUE THREAD

**Issue by christrotter** [grafana/grafana#1319]
SingleStat panels are awesome.  Thank you so much.

I would love to be able to specify a range or 'greater-than or less-than' operators in the value-to-text mappings.  This issue mentioned adding range functionality at a later date.  https://github.com/grafana/grafana/issues/1130

![image](https://cloud.githubusercontent.com/assets/8292406/5680585/151099ea-97dd-11e4-8a19-0825190a64c1.png)

So the use case is on my dashboards I want things to be simple, so just display 'OKAY' if the value is below 500.  Above that do whatever.  And you can further that by specifying 500to1000 = WARN, and >1000 = RUH ROH SHAGGY or whatever.

**Comment by nickman** [comment]
+1

**Comment by tehdirector** [comment]
+1

**Comment by rmoff** [comment]
:+1:

**Comment by enri57ar** [comment]
+ 1

**Comment by simple-snow** [comment]
+1

**Comment by pazoozooCH** [comment]
+1

**Comment by ernoaapa** [comment]
+1

**Comment by whisk3y** [comment]
+1 This would be great as I am making a Status Dashboard for back end users.

**Comment by cemo** [comment]
+1

**Comment by agaon** [comment]
+1

**Comment by argais** [comment]
+1 any plans for this? just downloaded a 2.1 .deb and its still not there.

**Comment by davidetempesta** [comment]
+1

**Comment by plopp** [comment]
+1

**Comment by javiermarcon** [comment]
+1

**Comment by xneo64** [comment]
+1

**Comment by sergey-butsky** [comment]
+1

**Comment by karma1911** [comment]
+1

**Comment by afflick** [comment]
+1

**Comment by agaon** [comment]
+1

**Comment by markri** [comment]
+1

**Comment by SteveNewhouse** [comment]
+1

**Comment by romanponomarev** [comment]
+1

**Comment by rurutia** [comment]
+1

**Comment by bblok11** [comment]
+1

**Comment by petterbrodin-goodtech** [comment]
+1

**Comment by miedzwiedz** [comment]
+1

**Comment by utkarshcmu** [comment]
PR #4644 created, implemented this feature, key points are mentioned in the PR.

Here are some screenshots of Singlestat panel editor:

**Value to text mappings removed from Options tab**
<img width="1269" alt="screen shot 2016-04-10 at 11 25 55 pm" src="https://cloud.githubusercontent.com/assets/1019609/14418474/ba9e7d1a-ff73-11e5-828b-7c45dc3b605a.png">

**Moved the value to text mappings to Mappings tab**
<img width="1269" alt="screen shot 2016-04-10 at 11 26 03 pm" src="https://cloud.githubusercontent.com/assets/1019609/14418486/d3acd5d6-ff73-11e5-9bf4-0c0964ed1e10.png">

**Range to text mapping functionality**
<img width="1260" alt="screen shot 2016-04-10 at 11 26 09 pm" src="https://cloud.githubusercontent.com/assets/1019609/14418537/2b531ba6-ff74-11e5-84bd-34a994b1c70b.png">

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/4644

**Comment by bergquist** [comment]
This is merged to the development branch and will be available in grafana 3.1

**Comment by utkarshcmu** [comment]
@bergquist Thanks for merging this functionality. Its available in Grafana master now. :)

**Comment by gam-phon** [comment]
Thanks for merging this awesome feature. How about greater than or less than? How can I define it?

**Comment by fmakawa** [comment]
And if we wanted a range to infinity? As in, the current implementation from my understanding needs you to expressly state a lower and upper limit.  When we state lets say: from 500 to <blank>  the text mapping for that is not triggered because it expecting an upper limit value. It would great if we got true greater than and less than functionality for when we don't have an end limit to what we are monitoring but still want to map those values
