### ISSUE TITLE
Persisting Role After Logout

### ISSUE THREAD

**Issue by Keshav0690** [grafana/grafana#13195]
Grafana - 5.2.1
DataSource - Prometheus
OS - Linux

What did you do?
Tried to change the Role of the user from viewer to Editor by logging in as Admin

What was the expected result?
User's Role changed to Editor. Also If user logged out, and login again into Grafana, role should remain as Editor

What happened instead?
For Active Session user's role is Editor, but when he logged out and again login, user's role changed  to default i.e viewer.

Any help would be appreciated.

**Comment by Keshav0690** [comment]
Grafana - 5.2.1
DataSource - Prometheus
OS - Linux

What did you do?
Tried to change the Role of the user from viewer to Editor by logging in as Admin

What was the expected result?
User's Role changed to Editor. Also If user logged out, and login again into Grafana, role should remain as Editor

What happened instead?
For Active Session user's role is Editor, but when he logged out and again login, user's role changed  to default i.e viewer.

Any help would be appreciated.

**Comment by torkelo** [comment]
Sounds like your using LDAP and have mappings beteeen LDAP groups and Grafana org roles . Remove the ldap group mapping’s from ldap toml and you can handle permissions in Grafana
