### ISSUE TITLE
Help in getting trend with aliasby tag key

### ISSUE THREAD

**Issue by SindhujaSoundarapandian** [grafana/grafana#13197]
Grafana - 5.2.1
DataSource - influxdb 
OS - windows 10

What did you do?
Tried to get the average response trend across builds

Table 1:

Transaction buildno avg 
Search          121       2356
Search          121       2486
Login            121        1256 
Login            121        1286
Search          122       4587
Search          122        1456
Multiple hits are there for every 5 secs once. I tried with the following query 

Select avg from table1 where $timefilter groupby buildno 

I could see single line in graph panel but i couldn't see the transaction details while hovering on it. I also tried with aliasby and groupby clause but after putting all those fields i could see multiple lines against transactions is there a way to plot a single line group by buildno along with the transaction details  when hovered over the panel. 

Anyhelp is much appreciated!

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
