### ISSUE TITLE
graph shows wrong number type

### ISSUE THREAD

**Issue by Kevinsss** [grafana/grafana#13207]
Version: Grafana v5.2.4
OS: Centos6

Hi, I have a strange problem.
I have some datas of metric, the values are integer, like this:
![2222](https://user-images.githubusercontent.com/8381695/45283910-ba54ef00-b511-11e8-99c6-f16d76720268.jpg)
But when I add one panel to show the datas,  I get decimal number on panel. Then I check the settings of `Axes `, and the settings are ok. I also tried to change `Axes Decimals` to 0,but it doesn't work.
![333](https://user-images.githubusercontent.com/8381695/45284211-7c0bff80-b512-11e8-88f5-3ae6af5d7a46.jpg)
I modify some metric values  to above 50,  then it became ok!
 Is this a bug or a normal feature?

**Comment by torkelo** [comment]
legend and tooltip will always add at least 2 decimals (in some cases) when auto decimals is turned on. You can change this if you go to legend tab and override the decimals there (legend decimals is shared with tooltip)
