### ISSUE TITLE
macro timeFilter must use grafana time zone

### ISSUE THREAD

**Issue by PyIES** [grafana/grafana#13205]
### What Grafana version are you using?
5.3.0-beta1
### What datasource are you using?
MySql
### What OS are you running grafana on?
windows 10
### What did you do?
use $__timeFilter(Fecha) macro with time interval in **Last 6 hours**
### What was the expected result?
$_timeFilter(Fecha) is change to 
Fecha between '2018-09-08T13: 27: 05Z' and '2018-09-08T019: 27: 05Z'

### What happened instead?
$_timeFilter(Fecha) is change to 
Fecha between '2018-09-08T18:27:05Z' and '2018-09-09T00:27:05Z'
 
If this macro has this change, and grafana does not use the appropriate time zone, it would have to update hundreds of dashboars

**Comment by torkelo** [comment]
The browser timezone is used (unless UTC) option is set in dashboard or profile. The time range is sent in UTC to server and the query expects the date columns to be using UTC time

**Comment by Joe2099** [comment]
After upgrading to 5.3.0 I see the above behavior. MySQL is set to use SYSTEM timezone, not UTC:
mysql> SELECT @@global.time_zone;
+--------------------+
| @@global.time_zone |
+--------------------+
| SYSTEM             |
+--------------------+
It seems the trailing Z (Zulu timezone) is not picked up by MySQL.

**Comment by marefr** [comment]
Duplicate of #13621
