### ISSUE TITLE
postgres query with window function breaks cursor function in graph panel

### ISSUE THREAD

**Issue by henrythasler** [grafana/grafana#13202]
### Action
Execute the following **postgres** query including a **[window function](https://www.postgresql.org/docs/11/static/tutorial-window.html)** to display the moving average of some value in a **graph panel**:
```
SELECT
  $__time(timestamp),
  avg(temperature) OVER (
	  ORDER BY timestamp DESC
	  ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING
	) as outside
FROM
  outside
WHERE
  $__timeFilter(timestamp)
```
### Expected behavior
Data cursor displays the current value at mouse position
### Observed behavior
Data cursor does **NOT** display the current value at mouse position. Instead, the cursor snaps to t_max (or t_min if you move to the right half of the chart).
![selection_008](https://user-images.githubusercontent.com/6277203/45252948-debc9a00-b35e-11e8-9093-37b7f541b6a0.png)

### Additional Info
Grafana version: v5.3.0-beta1 (commit: e05033a) via docker (same with v5.2.3)
Datasource: postgres 11
Docker Host OS: Debian 4.17.8-1~bpo9+1 (2018-07-23) GNU/Linux

**Comment by svenklemm** [comment]
Hmm this is weird, this only happens when you use window functions? Did you get any javascript errors?

**Comment by henrythasler** [comment]
Query w/o window-function works fine:
```
SELECT
  $__time(timestamp),
  temperature as outside
FROM
  outside
WHERE
  $__timeFilter(timestamp)
``` 

Firefox only shows some warnings:
```
window.controllers/Controllers is deprecated. Do not use it for UA detection. index.js:1362
warning rootScope onAppEvent called without localscope. grafana_app.ts:71:6
```

**Comment by svenklemm** [comment]
Can you add an ORDER BY 1 to your query. Grafana requires data to be sorted by time.

**Comment by henrythasler** [comment]
That's interesting! Reversing sort-order (change DESC to **ASC**) inside the window-function resolves the issue. It seems like the sort order is propagated outside the window-function which makes sense somehow I guess... Maybe that's a topic for some postgres-faq.
```
SELECT
  $__time(timestamp),
  avg(temperature) OVER (
	  ORDER BY timestamp ASC
	  ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING
	) as temp
FROM
  outside
WHERE
  $__timeFilter(timestamp)
```
![selection_009](https://user-images.githubusercontent.com/6277203/45254162-0407d300-b374-11e8-93a4-c68ab850fe96.png)

Anyway, now it works as expected. Thanks for the hint and sorry to bother you for this Grafana-unrelated matter.

**Comment by svenklemm** [comment]
No worries, i think the fact that output needs to be sorted should be documented better.
