### ISSUE TITLE
Query for InfluxDb to select a range of tag keys

### ISSUE THREAD

**Issue by deepSalva** [grafana/grafana#13215]
I am visualizing a data base in Grafana produced for InfluxDb. In one of my measurements I have like 1000 keys or tags or variables. I would like to select a range of them, kind of 200 of them to visualizing them. How can I do it without adding 200 news queries? I already try the query in metrics:

> WHERE key > 1 AND key < 200

But nothing. I don't know if I miss something within Grafana App or should I maybe to add a pattern or a variable?

In the picture I show you can see, the variable key is equal to 1 and in the query below equal to 2. I have 1000 values assigned to key. I would like to visualize a range for example from key=1 until key=200. How can I do that?
![grafpic](https://user-images.githubusercontent.com/27766580/45302059-a5c52680-b512-11e8-8955-ef390f65fdf9.png)

Nevertheless I can select the values from one single key in influxDb:

> select value from leuko where “key” = ‘2’

But I can't run this:

> select * from where “key” > ‘1’ and “key” < 200

Please any thought

Grafana version = 5.2.2
Datasource = InfluxDb
Ubuntu 16.04 
metric query

**Comment by torkelo** [comment]
tag keys in influxdb at not numeric values and (to my knowledge) does not support range filters

**Comment by deepSalva** [comment]
Thanks for your comment. Is there an alternative to achieve what I want? Thanks
