### ISSUE TITLE
simpleJson setup to display data from Json URL with variables in Table panel

### ISSUE THREAD

**Issue by futch7** [grafana/grafana#13216]
Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
below is response from save and test GET, host_name and domain should display in table but i'm getting nothing...  i'm actually passing this URL http://hiper-api-internal.level3.com/hiper/v3/domains/network/view/devices_by_network?domain=green%20networks  --   but the domain variable is being ignored because as you see below it is pulling back domain = red networks data as well.

{
  "identifier" : "761ef3f2-f352-4b56-afc2-c4088abf6c72",
  "host" : "hiper-api-internal.level3.com",
  "uri" : "/hiper/v3/domains/network/view/devices_by_network",
  "version" : "HAPI v3.1.1",
  "environment" : "prod-dallas",
  "owner" : "IN Support <insupport@level3.com>",
  "error" : {
    "code" : 0,
    "message" : "SUCCESS",
    "detail" : null
  },
  "data" : [
    {"host_name":"\"MMD19.AMS1\"","domain":"red networks"},
    {"host_name":"$HOSTNMD1","domain":"red networks"},
    {"host_name":"$HOSTNMD4","domain":"red networks"},
    {"host_name":"140-BBBM18457.WDC1","domain":"red networks"},
    {"host_name":"140-BBBM66172.STL1","domain":"red networks"},
    {"host_name":"140-BBBM76525.ORL1","domain":"red networks"},
    {"host_name":"140-BBBM78667-CHI1","domain":"red networks"},
    {"host_name":"140-BBBN16325-STL1","domain":"red networks"},
    {"host_name":"140-BBBN19689.STL1","domain":"red networks"},

**Comment by torkelo** [comment]
if you are using the simple json data source make sure the http api you are using is returning data in the specified format that the simple json data source supports, https://github.com/grafana/simple-json-datasource#query-api
