### ISSUE TITLE
Add millisecond formatting for interval type dashboard variables

### ISSUE THREAD

**Issue by PauloTemenos** [grafana/grafana#13214]
For the built-in variable $**interval there's the corresponding variable $**interval_ms. However, the dashboard variables of type "Interval" don't have such an option.

I propose the implementation of extra "__ms" variables for variables of type Interval to give dashboard developers numerical_

* access to the size of the time buckets. (I assume this should be quite easy to implement?)

### What can we do with that?
That would allow us to calculate rates out of counts.

If we want a dashboard to have the option for the user to change the granularity of the charts, variables of type "Interval" are the suitable option where we can have "auto" or specific values - pretty cool. We can insert them into an InfluxDB query into the group by:
`GROUP BY time($custom_interval).`

However, if we try to chart rates (count / time_elapsed):

```
SELECT math (
count(xyz) / $custom_interval --< broken, as it will pass a non-number
)
FROM abc
GROUP BY time($custom_interval)
```

Therefore access to the elapsed seconds or milliseconds is required _(without any "s" or "m" or whatever at the end)_, so that we can divide the count by the time elapsed and achieve a rate.

### What Grafana version are you using?
Latest as of 2018-07

### What datasource are you using?
InfluxDB (N/A?)

### What OS are you running grafana on?
N/A

**Comment by 369pie** [comment]
how is it going?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
