### ISSUE TITLE
[Feature] Show whole Dashboard + go to dashboard link

### ISSUE THREAD

**Issue by MarcusCaepio** [grafana/grafana#13218]
Hi all,
after testing the alarming for a few days now, we see that it would be nice to:
- see the whole dashboard in the mail instead of only the alarming panel
- have a button to go to the dashboard directly

Cheers,
Marcus

**Comment by PauloTemenos** [comment]
2) the content of the message sent to the alertees is written by us - we can just put a link in the content..?

**Comment by torkelo** [comment]
1) Not sure we to render the whole dashboard for a single alert 
2) duplicate of https://github.com/grafana/grafana/issues/5848
