### ISSUE TITLE
[BUG?] Alerting - Not firing Alert when Interval is set as AUTO

### ISSUE THREAD

**Issue by Filipe777** [grafana/grafana#13222]
### What Grafana version are you using?
5.2.3

### What datasource are you using?
Elasticsearch 6.4.0

### What OS are you running grafana on?
MacOS High Sierra

### What did you do?
Created an alert for a document count query.

Metrics Query:
![image](https://user-images.githubusercontent.com/31474068/45353900-21c37b00-b5b4-11e8-8107-86667d817983.png)

- Interval is set as **auto**

Alert Config:
![image](https://user-images.githubusercontent.com/31474068/45355482-6f41e700-b5b8-11e8-91ec-16fba952fa6c.png)

- Last 5 minutes time range selected
- Average of Document count is showing 2.8

### What was the expected result?
- `firing: true`
- `state: "alerting"`

### What happened instead?
- `firing: false`
- `state: "ok"`

**Test Rule shows a message Value of 0.056 and with 1499 arrays, each with values lower than 0.1 which is why the alert is never triggered.**
![image](https://user-images.githubusercontent.com/31474068/45354752-56383680-b5b6-11e8-93a2-8ee1b1c2db60.png)
 
**When selecting an integer interval in the `Group by` `Date Histogram` like 10s, the average of the arrays are more consistent with the document count average.**
![image](https://user-images.githubusercontent.com/31474068/45355135-787e8400-b5b7-11e8-9087-06f0f9bf838c.png)

![image](https://user-images.githubusercontent.com/31474068/45355143-7fa59200-b5b7-11e8-88cd-93cca703f7a8.png)

**This triggers the alert as expected.**
![image](https://user-images.githubusercontent.com/31474068/45355860-7a494700-b5b9-11e8-9628-68af614f36de.png)

#### Is the auto bucket size actually taking into account every single document? Not sure if this is a bug or my misuse of the auto bucket size. 

Regards!

**Comment by torkelo** [comment]
Have you specified a min interval in your elasticsearch datasource config page? If not the auto date histogram interval can go very low in a 5m time range (5 minutes / 1500). But if you have specified a min interval (like 10s) in your data source settings then that will be used.

You can also set a min doc count in the date histogram to make sure null buckets are not returned.

**Comment by Filipe777** [comment]
Hi.
Setting up a new alert on another graph I've came across a situation where the **Min Doc Count** in the **Date Histogram** did not made the result value of testing the rule consistent with the average being displayed in the graph. The Alert fails to trigger when it should be triggered.

Metric Query:
![image](https://user-images.githubusercontent.com/31474068/45434032-5bc07a00-b6a5-11e8-96a0-3ea6320fbac8.png)

Alert Config:
![image](https://user-images.githubusercontent.com/31474068/45434057-6975ff80-b6a5-11e8-824a-86cf7bdf59d0.png)

Test Rule Output:
![image](https://user-images.githubusercontent.com/31474068/45434088-77c41b80-b6a5-11e8-83af-31f654f360ed.png)

Making it work:

Metric Query:
![image](https://user-images.githubusercontent.com/31474068/45434208-c7a2e280-b6a5-11e8-82c9-0cef140f3b56.png)

Test Rule Output:
![image](https://user-images.githubusercontent.com/31474068/45434232-d8ebef00-b6a5-11e8-9ffa-a0a790a21c2f.png)

Average Value in the graph:
![image](https://user-images.githubusercontent.com/31474068/45434276-f4ef9080-b6a5-11e8-85cf-d2bac7d9ee3b.png)

The only change made was defining a integer value in the **Interval** field in the **Date Histogram**. I don't understand why it worked in the previous case.
- Same datasource and datasource config
- Same metric type (Count)
- Same **Min Doc Count**
- Same alert config, witch exception on the **IS ABOVE** value.

Thank you for your work!
Regards.

**Comment by marefr** [comment]
@Filipe777 are you still having problem with this? Did you look at 5m range in dashboard when you tested the alert rule?

**Comment by marefr** [comment]
Seems like you get a "half result" at the end and that's maybe why you're getting the weird result. Does it make any difference if you skip trimedges? Could you please try `query (A, 6m, now-1m)`.

**Comment by Filipe777** [comment]
Hi, thank you for the quick reply.

Just changing the conditions to `query (A,6m,now-1m)` produces the same result. Skipping trim edges with minimum doc count as 1 triggers the alert! I've changed the conditions of the alert back to `query (A,5m,now)` and it is alerting as it should with the Test Rule output values consistent with the values displayed on the table graph.

Much appreciated!
