### ISSUE TITLE
Templating Variable Values Query doesn't understand $timeFilter

### ISSUE THREAD

**Issue by JeremyMorton** [grafana/grafana#1322]
I would like to have a template variable only have values that have occurred in the time window that the dashboard is set to.

For example, I have an InfluxDB template variable that uses a query like `select distinct(name) from "event" group by name order asc` and it returns all `name` values ever seen.

I would like to be able to have it use `$timeFilter` in a similar way to how a metric query does; i.e., `select distinct(name) from "event" where $timeFilter group by name order asc` so that the template variable only has values seen during the time period the dashboard is showing, but `$timeFilter` does not seem to be referable from a template variable values query.

**Comment by torkelo** [comment]
This would be a little tricky as the template variable options would need to be refresh every time the time changes (like zoom in or every dashboard auto refresh) and all graphs would have to wait to issue queries until this process completes. Would slow down graph rendering. So unless this gets a lot of +1 votes it will probably not be something implemented.

**Comment by JeremyMorton** [comment]
If the page's currently chosen template variable values aren't changed when changing time, even if the query doesn't have them on the list any longer, then the graphs can issue their queries immediately, with the currently chosen template values, just like now.

The only complication is the All option that uses "glob" or "regex values", where the list is all of the explicit values. That option would have to delay graph query execution until the template queries happen, as you mention.

**Comment by anudharm** [comment]
+1. We also would like to have this feature implemented, to list only nodes that have been active in a particular time range.

**Comment by torkelo** [comment]
the influxdb meta explore queries don't support time filter as the tags are note stored with each time point. So this will be impossible for InfluxDB 0.9.x
