### ISSUE TITLE
$timeFilter variable not expanded as expected

### ISSUE THREAD

**Issue by ewillia1983** [grafana/grafana#13228]
Please include this information:
### What Grafana version are you using?
5.0.4

### What datasource are you using?
InfluxDb

### What OS are you running grafana on?
RHEL 7

### What did you do?
I'm troubleshooting an issue where queries against our autogen retention policy and one_minute aggregate retention policy aren't returning data as I expected.  I set up a table with the following queries:

`SELECT count("execution_time") FROM "autogen"."timed_methods" WHERE  $timeFilter group by time(1h)`
`SELECT sum("count_execution_time") FROM "one_minute"."timed_methods" WHERE  $timeFilter group by time(1h)`

The timeFilter was set to a one hour block of time, using the timePicker utility.  

### What was the expected result?

Time                          | auto        | one
2018-09-11 08:00:00 | 5908256 | 5908256

### What happened instead?

Time                          | auto        | one
2018-09-11 09:00:00 | 0             | 169394
2018-09-11 08:00:00 | 5908256 | 5908256

If I hard code the time filter like this:
``SELECT count("execution_time") FROM "autogen"."timed_methods" WHERE  time >= '2018-09-11T12:00:00.000Z' AND time < '2018-09-11T13:00:00.000Z' group by time(1h)`
`SELECT sum("count_execution_time") FROM "one_minute"."timed_methods" WHERE  time >= '2018-09-11T12:00:00.000Z' AND time < '2018-09-11T13:00:00.000Z' group by time(1h)``

I get the result I'm expecting.

The fully expanded queries from grafana analyzer: 
`q:"SELECT count("execution_time") FROM "autogen"."timed_methods" WHERE time >= 1536667200000ms and time <= 1536670800000ms group by time(1h);SELECT sum("count_execution_time") FROM "one_minute"."timed_methods" WHERE time >= 1536667200000ms and time <= 1536670800000ms group by time(1h)"`

The second time is listed with `<=`, which seems to be what's including the extra time bucket.

>

**Comment by torkelo** [comment]
absolute time ranges in grafana are inclusive (for influxdb at least)
