### ISSUE TITLE
grafana-cli failed to download

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#13234]
### What Grafana version are you using?
5.2.3
### What OS are you running grafana on?
Debian

Link to plugin at Grafana
https://grafana.com/plugins/fatcloud-windrose-panel

Link to plugin at Github
https://github.com/fatcloud/windrose-panel

### What did you do?
`sudo grafana-cli plugins install fatcloud-windrose-panel`

Got this as reply

> installing fatcloud-windrose-panel @ 0.7.0
> from url: https://grafana.com/api/plugins/fatcloud-windrose-panel/versions/0.7.0/download
> into: /var/lib/grafana/plugins
> 
> Failed downloading. Will retry once.
> Failed downloading. Will retry once.
> 
> Error: ✗ Corrupt http response from source. Please try again.
> 
> 
> NAME:
>    Grafana cli plugins install - install <plugin id> <plugin version (optional)>
> 
> USAGE:
>    Grafana cli plugins install [arguments...]

**Comment by torkelo** [comment]
this is fixed 5.2.4

**Comment by marefr** [comment]
Duplicate of #13079
