### ISSUE TITLE
Playlist for mixed graphs from multiple dashboards

### ISSUE THREAD

**Issue by MohamedNazeer** [grafana/grafana#13239]
Hi Team,

Is there any possibility to create a playlist which holds the graphs from multiple dashboards??

As of now we are able to create a playlist with only dashboard level. I want to create playlist with some selected graphs in a dashboard.

**Comment by torkelo** [comment]
no this is not possible right now, the playlist allows a sequence of dashboards to be shown.

Don't think this will ever be implemented so closing this.
