### ISSUE TITLE
Injecting panels through HTTP API

### ISSUE THREAD

**Issue by StefanVahlgren** [grafana/grafana#13236]
Like many others, I've been searching for a way to inject panels dynamically. As I interpret both the documentation for the HTTP API ( http://docs.grafana.org/http_api/dashboard/) and other discussions related to this topic (https://community.grafana.com/t/how-to-auto-create-the-panel-and-graph-through-grafana-api/2505) , injecting panels directly through the HTTP API is not supported.

However, I experimented a bit yesterday with the /api/dashboards/db endpoint, together with the json you get if you use the dashboard Export function. I used the exported dashboard as the json body of the "dashboard" part for the POST request. And it actually worked 👍 So what I have now is a way to dynamically configure and customize graphs just like I need them at any given time, and then throw them away and create new ones when needed.

This Issue is mainly a question: Is what I did something supported? If so, I think it would be very helpful to many if it was documented. To have the possibility to inject entire dashboards with dynamically customized panels is awesome!

Grafana verion: 5.2.4
OS Grafana executes on: Windows 10
Datasource im using (not really relevant I think): InfluxDB

**Comment by torkelo** [comment]
yes, using the dashboard API /api/dashboards/db you can get and update dashboards and dynamically construct / update dashboards
