### ISSUE TITLE
Updating variable's value to empty changes it only visually

### ISSUE THREAD

**Issue by the0ffh** [grafana/grafana#13230]
### What Grafana version are you using?
5.2.4
### What OS are you running grafana on?
Ubuntu 16.04/18.04/, MacOs Sierra/HighSierra
### What did you do?
Removed custom variable value
### What was the expected result?
Custom variable having an empty value
### What happened instead?
Variable is being displayed as empty but keeping previous value

**Comment by torkelo** [comment]
Can't replicate this, an "empty" value is seen as no value selected, so the variable should revert to it's previous value. 

Can you replicate it here? I tried with normal variable, custom variables, with and without multi / all.  
https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1

This sounds like the same issue like this:
