### ISSUE TITLE
Read tcp [::1]:52473->[::1]127.0.0.1:1433 i/o timeout

### ISSUE THREAD

**Issue by fahad237** [grafana/grafana#13233]
Hi All,

I am new to Grafana. I have connected Grafana to Microsoft SQL Database. When i am executing queries in Grafana, sometimes query runs fine and results are displayed however for complex query execution pasted below error is thrown:

read tcp [::1]:52473->[::1]127.0.0.1:1433 i/o timeout

If i run the same query from Microsoft Server Management Studio query runs fine and results are displayed at around 50 secs. It seems error is due to pre set time for Grafana to run query is < 30 secs. My Question is if this time configurable? If NOT what is other option for me to get rid of this error.

Grafana Version: 5.2.3
Windows 7 64 Bits

Regards,

**Comment by torkelo** [comment]
there is no timeout option right now, but there is a feature request:
https://github.com/grafana/grafana/issues/5699
