### ISSUE TITLE
Periodic grafana OK alerts

### ISSUE THREAD

**Issue by jmgonzalezp** [grafana/grafana#13237]
Hello!

I have a problem with some alerts, for some reason they are firing an OK alert every hour, this is the log of one example. Can you help me to troubleshoot it?

```
t=2018-09-10T20:05:30+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=101.510 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T20:18:16+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=304.721 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T20:31:05+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=36.871 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T20:56:47+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=258.264 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T21:09:32+0200 lvl=info msg="New state change" logger=alerting.resultHandler alertId=203 newState=ok prev state=pending
t=2018-09-10T21:09:35+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=147.704 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T21:22:22+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-136.342 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T21:35:11+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-309.020 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T21:47:59+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=21.329 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T22:00:49+0200 lvl=info msg="New state change" logger=alerting.resultHandler alertId=203 newState=ok prev state=pending
t=2018-09-10T22:00:54+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-478.583 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T22:26:28+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-72.841 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T22:39:15+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=25.102 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T22:52:04+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=21.435 alertId=203 name="XXXXXXXXXXXXX" firing=false attemptID=1
t=2018-09-10T23:04:54+0200 lvl=info msg="New state change" logger=alerting.resultHandler alertId=203 newState=ok prev state=pending
```
![image](https://user-images.githubusercontent.com/22073040/45410811-f784c280-b672-11e8-8390-58ee67430483.png)

Thanks.
José M.

### What Grafana version are you using?
5.3.0-beta1
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Red Hat 7

**Comment by marefr** [comment]
Have you by any chance enabled notification reminders? Would be great if you could include some details of alert rule- and notification channel configuration. Thanks

**Comment by jmgonzalezp** [comment]
No, I did not enable notification reminders.
I think that the alert is firing because of this state change, but I don't know why the state goes to pending state.

`t=2018-09-10T23:04:54+0200 lvl=info msg="New state change" logger=alerting.resultHandler alertId=203 newState=ok prev state=pending`

This is the notification channel configuration:

![image](https://user-images.githubusercontent.com/22073040/45491432-01d5b800-b76a-11e8-8bf2-6a206efb7606.png)

And this is the alert rule:

![image](https://user-images.githubusercontent.com/22073040/45491524-334e8380-b76a-11e8-9a94-502817d6d0cb.png)

**Comment by marefr** [comment]
Could it be due to you've configured `Keep Last State` for both no data and execution error or timeout. It worked as expected before upgrading to v5.3 beta1?

**Comment by jmgonzalezp** [comment]
I have confirmed that the annotations of the OK events were visible before upgrading to v5.3 beta1, but the alerts started firing after the upgrade.

I'm not sure how these options can generate the problem, I have configured all alerts in this way and the problem is only happening for some of them.

**Comment by torkelo** [comment]
are you running multiple grafana servers behind proxy? (with shared db) ?

**Comment by jmgonzalezp** [comment]
No, only one grafana server with mysql db.

**Comment by jsedy7** [comment]
Hello, I have a similar problem with alerts from Grafana. I tested it on versions **5.3.0-beta1** and **5.3.0-35572pre1**. When I receive first alert, It's OK... because his state is firing and after resolve I receive OK status. But, If my incident shows again, I not receive firing status, but only OK status after resolve. I think, that's  not correct behaviour. 

![grafana_graph](https://user-images.githubusercontent.com/8748774/45995600-0028c000-c099-11e8-9ac5-23d1c438d1ec.png)
On the graph seems to be everything OK but not in the Slack.  

![grafana_slack](https://user-images.githubusercontent.com/8748774/45995614-0cad1880-c099-11e8-8173-5caaebe13108.png)

**Comment by jmgonzalezp** [comment]
Hello, it seems that it is fixed in last beta2 release.
