### ISSUE TITLE
influxdb dashboard export and import fails due to incorrect coding

### ISSUE THREAD

**Issue by yee379** [grafana/grafana#1323]
i do a lot of regex's for my dashboards, so a lot of the graphs are defined as `/blah/`.

when a dashboard is exported and reimported, these graphs now GET with `%2F` as `/` - which then shows up with the influxdb error `cannot find user root`. if i change the GETs to use `%22` instead, the query to influxdb works as expected.

**Comment by yee379** [comment]
also... even in the normal editor, the `|` character isn't handled well - resulting in the same error (works for lookup tho), eg

    /dhcp-52-(10|21|24|26|27).mydomain.com\/load\/load/

**Comment by torkelo** [comment]
What browser & OS are you using? I cannot replicate this on Chrome and Linux.

**Comment by torkelo** [comment]
Also what version of Grafana? Can you replicate this issue on http://play.grafana.org/#/dashboard/db/influxdb-templated-queries?

**Comment by yee379** [comment]
i'm on influxdb 0.8.8-1 and grafana 1.9.1 on chrome canary 41.0.2272.0 on a mac.

agreed, i couldn't replicate it play.grafana - different version of influx?

shouldn't this raw query work on play.grafana?

    select mean(value) from /apps.backend_(01|02).counters.requests.count/ where $timeFilter group by time($interval) fill(0) order asc

it gives a different error on play.grafana tho (couldn't lookup columns)

**Comment by torkelo** [comment]
@yee379 Your query is using the wong regex path for those series. 

This works
```
select mean(value) from /apps.backend.backend_(01|02).counters.requests.count/ where $timeFilter group by time($interval) fill(0) order asc
```

Tried latest Influxdb 0.8.8 and import json and export json works on templated dashboards. Strange.

**Comment by yee379** [comment]
ah, typo on the regex - i'm sorry for not noticing that... i played around a bit with the regex query on influx itself, and it doesn't seem to pick up there. i think grafana is doing the right thing. consider this a non-issue - keep up the good work!
