### ISSUE TITLE
[Feature] Replace time picker with zoom out controls 

### ISSUE THREAD

**Issue by the0ffh** [grafana/grafana#13231]
Handy when zooming out 'rapidly' from predefined ranges. 
It would be very nice if placement/order of at least these two controls could be customizable.

**Comment by torkelo** [comment]
In Grafana v5.3 (beta out) we moved the zoom to the right so it's easier to zoom out quickly without the button moving. 

![image](https://user-images.githubusercontent.com/10999/45403549-49215300-b65b-11e8-8697-702484786f8e.png)

**Comment by the0ffh** [comment]
Looks nice. What is an ETA for the final version?

**Comment by torkelo** [comment]
Stable should be coming in 1-2 weeks
