### ISSUE TITLE
Debian/Ubuntu repository does not have source-package

### ISSUE THREAD

**Issue by socketpair** [grafana/grafana#13249]
i.e. `apt-get source grafana` does not work even if I add the following line:

`deb-src https://packagecloud.io/grafana/testing/debian/ stretch main`

Please publish your `/debian` folder in order to re-build Debian packages on my own way. Or, maybe you have official PPA ?

**Comment by marefr** [comment]
Have you read the [documentation](http://docs.grafana.org/installation/debian/#apt-repository)?

**Comment by Kaveshnikov** [comment]
It would be nice to have a `/ debian` folder for packaging to do some patches

**Comment by socketpair** [comment]
@marefr, yes, I have. I have no problem installing binary package. I have problems with building my own Debian package from sources.

**Comment by torkelo** [comment]
We sadly cannot provide source package because I order to build grafana you need go, nodejs runtime and about 500mb of node packages, and ruby (for fpm used to create deb package).

Not sure if it’s common to provide source packages for things like grafana that has a big frontend that requires a lot to build.

**Comment by socketpair** [comment]
Yes, I'm ready for such a big build-dependencies. Could you provide debian/control so ?

**Comment by torkelo** [comment]
> Could you provide debian/control so ? 

?

**Comment by socketpair** [comment]
@torkelo in short, could you provide the source package ? Why do you hide it ?

**Comment by torkelo** [comment]
we don't hide it, here is a guide building from source:

http://docs.grafana.org/project/building_from_source 

The source packages are here: 
https://github.com/grafana/grafana/releases 

We do not have time right now to build a deb source package, maybe if there was more demand. But last 4 years it has only been requested once before.

**Comment by socketpair** [comment]
Thanks for the answers. Anyway, since you build deb packages automatically during CI/CD, it is easy to publish /debian folder used during that builds. For example, include it's full contents here: https://github.com/grafana/grafana/tree/master/packaging/deb . By some reason only part is present.

**Comment by panlinux** [comment]
I was also looking for the debian source package, and found this bug.
