### ISSUE TITLE
Grafana Data Source NETXMS HTTP error

### ISSUE THREAD

**Issue by MiguelAfonso1994** [grafana/grafana#13244]
My Netxms integration on grafana is displaying this error, and i dont know what i should do. Any ideas to fix the problem?
This happens when i use the server option
![grafana error](https://user-images.githubusercontent.com/26483256/45420691-b85e6d80-b682-11e8-88eb-2d5f3411bd17.png)
This happens when i use the broswer option
![grafana error browser](https://user-images.githubusercontent.com/26483256/45420769-f52a6480-b682-11e8-8230-b89f5cb88c15.png)

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
