### ISSUE TITLE
Cannot use variable with the syntax [[varname]] with prometheus range vector

### ISSUE THREAD

**Issue by topine** [grafana/grafana#13242]
Hello,

I'm trying to use the $__range_s variable in the prometheus metric range vector selector but the variable is not resolve, maybe because for this case we have 3 "[".

Example: 

For the query:
storage_avg_total_mb_per_second{name=~"$name",type="storageSystem"}[[[__range_s]]s]

This is send to prometheus:

xhrStatus:"complete"
request:Object
method:"GET"
url:"https://localhost/api/v1/query?query=storage_avg_total_mb_per_second%7Bname%3D~%22SVCa11-51%22%2Ctype%3D%22storageSystem%22%7D%5B%5B%5B__range_s%5D%5Ds%5D&time=1536796800"
response:Object
status:"error"
errorType:"bad_data"
error:"parse error at char 73: missing unit character in duration"
message:"parse error at char 73: missing unit character in duration"

Thank you

**Comment by torkelo** [comment]
you can use new prefered syntax ${varname}

**Comment by topine** [comment]
Thanks, works perfectly.
