### ISSUE TITLE
Feature Request: Implement the Variable as "Panel"

### ISSUE THREAD

**Issue by RedHat93** [grafana/grafana#13245]
Hi All,

since some time ago i was thinking if it's possible to have the Variable INSIDE the Dashboard.

Consult big Dahboard became annoying if any time we want to change the variable we need to scroll UP and re-scroll DOWN to see the graphs change.

I was thinking that could be nice to have a "Variable Panel" in order to have the variable near the graphs in wich we would like to change the shown series.

Another idea could also be to implement the Variable on the ROW Layer. 

What do u think? Can be  useful for someone else?

Thx in advance! :)

**RedHat93**

**Comment by torkelo** [comment]
not sure about variables per panel, but maybe https://github.com/grafana/grafana/issues/5329

**Comment by RedHat93** [comment]
Hi Torkelo,

yes, the Variable per Row would be a GREAT achievement to solve our "annoying scroll UP/DOWN".

Thx u so much and sorry for the duplicate Issue.

Have a great day,

**RedHat93**
