### ISSUE TITLE
URL keeps looping after editing variables and returning to dashboard

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13241]
1. Had a dashboard with a table panel using prometheus datasource. 
2. Added a variable that produces values in Settings -> Variables
3. Back to dashboard
4. Select a variable from the variable dropdown
5. Back to Settings -> Variables
6. Clone the variable
7. Back to dashboard
8. Url is constantly changing and one query is executed against prometheus kind of each second or faster and never stops.

Seems like it's flipping between views. Also, variable serialization might be slightly different between the URLs

![url-loop](https://user-images.githubusercontent.com/859729/45415930-0a04f900-b67f-11e8-98b7-684fce74b120.gif)

Noticed in #13212

**Comment by ausevj** [comment]
I was just in a process of creating reproduction steps for this. Seems to happen when switching to a variable with value that has spaces in it.

**Comment by ausevj** [comment]
My steps to reproduce:

1. Create new dashboard;
2. Add new variable:
![image](https://user-images.githubusercontent.com/30463702/45416448-a97ab980-b688-11e8-9d28-20350d9c00a9.png)
3. Save and reload the dashboard;
4. Select 'my test' variable;
5. Go to Settings -> Links;
6. Go to Settings -> JSON model;


Sometimes page becomes unresponsive after step 5, if not - always on step 6.

**Comment by marefr** [comment]
@ausevj which Grafana version are you using?

**Comment by ausevj** [comment]
@marefr using latest code (commit 17861985585c9b291c40c4c5b1626ff4f4aa6f52)

**Comment by torkelo** [comment]
probably related to redux location <-> angular url sync , will investigate

**Comment by torkelo** [comment]
@ausevj thanks for the details on the white space in variable, allowed me to replicate and fix it!
