### ISSUE TITLE
Grafana should cache Data Source connection properties

### ISSUE THREAD

**Issue by barrebre** [grafana/grafana#13257]
Please include this information:
Grafana v5.2.3 (cf4c090)

### What was the expected result?
Grafana will perform proxied queries to data sources without looking up the connection details for that data source every time

### What happened instead?
Grafana looks to the configuration database (PostGres, in this scenario) to load the connection details for data sources every time that data source is queried

Essentially, we will generally have ~40/50 connections to PostGres, but there are intermittent times it will spike to >300 connections. This causes Grafana to log errors like `sorry, too many clients already`, which can impact any operation which relies on the Grafana configuration database (logging in, looking up a user session, getting data source information for dashboard queries or alerting queries, etc). 
I have found that when our connection issues occur, 75% of the queries are the same - 
```SELECT "id", "org_id", "version", "name", "type", "access", "url", "password", "user", "database", "basic_auth", "basic_auth_user", "basic_auth_password", "with_credentials", "is_default", "json_data", "secure_json_data", "read_only", "created", "updated" FROM "data_source" WHERE "id"=$1 AND "org_id"=$2 LIMIT 1```
I use 75% by saying that out of psql dump of `pg_stat_activity` at that moment, out of 319 connections, 243 were the above query. 

I can continue to raise our connection count to PostGres, but it seems that Grafana should cache data from the `data_source` table. This is under the assumption that the only system modifying this table is Grafana, and so Grafana should know when the cache is stale.

(This may be similar to https://github.com/grafana/grafana/issues/12421, but that issue had a different error `too many connections for database`)

**Comment by barrebre** [comment]
As an aside, we have 282 data sources across all of our orgs, given from `COUNT(*)` of the `data_source` table in PostGres.

**Comment by marefr** [comment]
Grafana already caches each datasource lookup for 5 minutes, see https://github.com/grafana/grafana/blob/master/pkg/api/http_server.go#L59.

Or at least that was my assumption. Seems like it overrides default expiration and use 5 seconds, see https://github.com/grafana/grafana/blob/master/pkg/api/dataproxy.go#L33. 

> This is under the assumption that the only system modifying this table is Grafana, and so Grafana should know when the cache is stale.

I agree that we should be able to do much more aggressive caching since we should be able to identify when cache is stale.

**Comment by bergquist** [comment]
Right now it's hard to cache more aggressively since we don't rely on memcache/redis in HA mode. We will reconsider if we still want to be independent or If we should require a cache server for HA mode.

**Comment by torkelo** [comment]
We did not cache tsdb/query at all, opened PR so it uses same cache as datasource proxy api

**Comment by marefr** [comment]
Changed this to reflect lack of caching tsdb/query. For further discussions about caching refer to #10816
