### ISSUE TITLE
Alerts: "Failed to test rule" and "Invalid alert data. Cannot save dashboard" errors

### ISSUE THREAD

**Issue by michaelgarde** [grafana/grafana#13250]
### What Grafana version are you using?
Grafana v5.1.0 (844bdc53a)
### What datasource are you using?
Prometheus 
### What OS are you running grafana on?
It's running in Openshift v3.6.173.0.113 on RHEL7
### What did you do?
I'm trying to test an alert with a Slack notification. I did a test of the Slack notification and it worked without issues.
### What was the expected result?
Something is sent to our Slack channel
### What happened instead?
A popup in the top right saying: "Failed to test rule"
### Additional
It's also not possible to save the dashboard. Attempting to do so results in a "Invalid alert data. Cannot save dashboard" error popup.

**Comment by torkelo** [comment]
Can you show alert tab or provide panel json?

**Comment by michaelgarde** [comment]
> Can you show alert tab or provide panel json?

I apologize for the minimal description. Please find attached panel json.
`
[panel.json.txt](https://github.com/grafana/grafana/files/2376615/panel.json.txt)
`

**Comment by michaelgarde** [comment]
I just noticed something. Alerting apparently doesn't like, when the datasource defined under the Metrics tab is a variable. If I select a specific data source i get a different error message in the top right dialog:
```
Validation failed
Failed to extract alert.Reason: Evaluator has invalid parameter PanelId: 149 DashboardId: 2
```
and below the Test Rul button i get:
```
firing:true
state:"alerting"
conditionEvals:" = true"
timeMs:"102.466ms"
error:"tsdb.HandleRequest() error bad_response: bad response code 400"
```

**Comment by marefr** [comment]
@michaelgarde Thanks for details. Template variables is not supported when using alerting, see #6557. Also, I see that in attached panel json you're referencing ${instances} in query - that's not supported when using alerting.
