### ISSUE TITLE
Specify Notifications for Alerts

### ISSUE THREAD

**Issue by Nessaek** [grafana/grafana#13251]
Hi there,
We have a grafana dashboard that we are generating through json. A typical alert rule looks like this:

```
  "alert": {
              "conditions": [
                {
                  "evaluator": {
                    "params": [
                      300
                    ],
                    "type": "gt"
                  },
                  "operator": {
                    "type": "and"
                  },
                  "query": {
                    "params": [
                      "A",
                      "2m",
                      "now-30s"
                    ]
                  },
                  "reducer": {
                    "params": [],
                    "type": "avg"
                  },
                  "type": "query"
                }
              ],
              "executionErrorState": "alerting",
              "frequency": "60s",
              "handler": 1,
              "message": "alerts",
              "noDataState": "no_data",
              "notifications": []
            }
```

What I'm wondering is, is there (or could there) be a way to specify what notifications (as in to slack, etc) to use for each alert? 

### What Grafana version are you using?
4.6.0, 4.6.4, 5.2.2, 5.2.3
### What datasource are you using?
Custom
### What OS are you running grafana on?
Mac OS

**Comment by torkelo** [comment]
Yes, in the notification array you can specify a list of names that refers to notification channels you define in the alerting section of a grafana (sidemenu)

**Comment by Nessaek** [comment]
Hi, how is this actually done?  Do we add in the id number of the notification channel to the notification array?
