### ISSUE TITLE
Unreadable font

### ISSUE THREAD

**Issue by diegoarioza** [grafana/grafana#13265]
Read before posting: 

The source of the triggers item is a bit readable, it seems that this is blurred, is this a bug?

Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
sqlite
### What OS are you running grafana on?
ubuntu 16
### What did you do?
The source of the triggers item is a bit readable, it seems that this is blurred, is this a bug?
### What was the expected result?
legible font

 
![font](https://user-images.githubusercontent.com/11810798/45511177-9d6b2680-b772-11e8-969f-f076b3a1b3b4.PNG)

**Comment by torkelo** [comment]
I don't recognize this panel, is it from an external plugin?

**Comment by diegoarioza** [comment]
is zabbix triggers.

**Comment by diegoarioza** [comment]
not close

**Comment by diegoarioza** [comment]
is panel

**Comment by diegoarioza** [comment]
![cap2](https://user-images.githubusercontent.com/11810798/45512724-08b6f780-b777-11e8-9a88-84f60831e6a1.PNG)
