### ISSUE TITLE
More that 3 values in single stat treshold settings

### ISSUE THREAD

**Issue by Touchedegris** [grafana/grafana#13264]
Hi,
I have set some Single Stat panels to monitor the last value received from a SNMP poller.  The MIB I poll is inconsistant in values, so I cannot adapt a coloring scheme that makes sense with the result.

It would be nice if we could configure more that 3 colors, where I could assign an individual color for specific values/ranges.

In my example, I am polling the autonegociated value of a port in a switch.  The manufacturer adapted the OID when new standards came in, but never adjusted the order:
                speed100(1),
                speed10(2),
                speedAuto(3),
                unknown(4),
                speed1000(5),
                speed10000(6),
                speed40000(7),
                speed20000(11),
                speed21000(12),
                speed2000(13),
                speed4000(14),
                speed8000(15),
                speed2500(18)
I wanted to have something like a treshold value of 1, 2, 3, 5, 6, so 10, 100 and 1000 have a unique color, over 1000 has a unified color and auto/unknown have a specific color.

Another Idea would be the ability to do value to color mapping.  It could be an option beside the value to texte mapping.

Thanks!

**Comment by torkelo** [comment]
Implemented in new Stat panel and the new field threshold UI
