### ISSUE TITLE
Grafana session_life_time not working

### ISSUE THREAD

**Issue by niranjantungatkar** [grafana/grafana#13267]
### What Grafana version are you using?
- 5.2.3

### What datasource are you using?
- None

### What OS are you running grafana on?
- MacOS High Sierra 10.13.6, Chrome Version 69.0.3497.92
### What did you do?
```
docker run -d \
-p 3000:3000 \
--name=grafana-kc \
-v /Users/xyz/grafana-ini:/etc/grafana \
grafana/grafana:5.2.3

grafana.ini

[session]
provider = file
provider_config = sessions
cookie_name = grafana_sess
cookie_secure = false
session_life_time = 30

[security]
login_remember_days = 0
cookie_username = grafana_user
cookie_remember_name = grafana_remember
```

### What was the expected result?
there shouldn't be grafana_remember and grafana_user cookies.
grafana_sess should not be a session cookie in other words the cookie should have a expiration time

Useful scenario
When a user logs in a grafana and the closes the tab, user does not close the browser, so after 30 secs the grafana_sess cookie should be invalidated and when the user loads grafana again after lets say 1 hour in the same browser(which wasn't closed) he should have to provide credentials

### What happened instead?
grafana_session cookie is a session cookie with expiration time set as 1969-12-31. 
user does not have to provide user credentials after 30 secs of inactivity.

**Comment by torkelo** [comment]
try setting the gc interval to same as session_life_time 
gc_interval_time = 30
