### ISSUE TITLE
How to connect mysql with grafana without having timestamp field in table(mysql)? Is this possible?

### ISSUE THREAD

**Issue by geetuvaddeboina** [grafana/grafana#13272]
Hi,

I am new to grafana i have been doing some examples in grafana by adding timestamp field in mysql table, but now i have bulk of data in mysql without having time field in it, how i can import that data in to grafana? i am not getting any idea which tool should be used or any plugin taht convert mysql in to timeseries database?

can any one help me out?

**Comment by torkelo** [comment]
you can use the table panel with any table data. If you want graphs in Grafana your query currently needs to return time series (so you need a time field). The singlestat panel supports table data as well. 

Please ask questions on the community site https://community.grafana.com

**Comment by geetuvaddeboina** [comment]
Currently, the database we are working do not have time field it has hour(tiny int) and minute(tiny int) field by using those fields we are writing custom query to generate time field ..will that custom query makes any difference if you use like that in future? does all the features in Grafana will support if we write custom query ??

I have already posted the same question in community but i did not got any response so that's why i am posting here again.
[(https://community.grafana.com/t/how-to-connect-mysql-with-grafana-without-having-timestamp-field-in-table-mysql-is-this-possible/10448?u=geetu)]

Thanks.

**Comment by marefr** [comment]
@geetuvaddeboina have patient. We'll not answering questions here.

**Comment by geetuvaddeboina** [comment]
@marefr sorry for the inconvenience caused , i'm new to all these forums.Will continue to post in community site.

thanks &regards,
geetha
