### ISSUE TITLE
Tooltip mixes up values when using 2 axes

### ISSUE THREAD

**Issue by ofirnk** [grafana/grafana#1327]
Showing 4 metrics when 2 of them are attached to the right axis, results:

![grafana_two_axes_tooltip_issue](https://cloud.githubusercontent.com/assets/8449713/5695252/a0453ede-99a0-11e4-8bee-d16ffb297333.png)
Around 00:40 its value _on the tooltip_ is around 11K, which is the value of the *green* metric

So:

<b>Second image shows a value of 11K for the orange metric while its axis (right one) shows the correct value</b>

**Comment by ofirnk** [comment]
These are the REAL values shown on the tooltip for the *orange* metric (which is bound to right axis):

![grafana_two_axes_tooltip_right_axis_only_one_metric](https://cloud.githubusercontent.com/assets/8449713/5695251/994f6848-99a0-11e4-9e17-8924cbebb095.png)
Around 00:40 its value is around 35

**Comment by torkelo** [comment]
What Grafana version are you running? Also, a guess you removed the alias for screenshot purposes?

**Comment by ofirnk** [comment]
Grafana version is 1.9.0-rc1.
And yeah - removed the alias :)

**Comment by torkelo** [comment]
Try upgrading to 1.9.1, There was some fixes related to similar issues in 1.9.0 and 1.9.1

**Comment by ofirnk** [comment]
Right, I'll what my graphite provider plans are and update here

Thanks!

**Comment by naoro** [comment]
Sorry, I was looking at 1.9.1 fixes only and not on 1.9.0 (non rc)

seems like the bug was fixed on #1108 but I'll just have to confirm it in few days as Grafana is updated to latest version

**Comment by ofirnk** [comment]
Sorry, I was looking at 1.9.1 fixes only and not on 1.9.0 (non rc)

seems like the bug was fixed on #1108 but I'll just have to confirm it in few days as Grafana is updated to latest version

**Comment by ofirnk** [comment]
Updating to 1.9.1 did solve the problem, thanks!
