### ISSUE TITLE
Variable Quarry Datatype Limit

### ISSUE THREAD

**Issue by Skillkiller** [grafana/grafana#13271]
Hello
I use the Grafana Cloud and therefore the latest version. As a data source, I use MySQL on my own server, all the data is correct.

But I wanted to create a variable based on Quarry. But can you explain why the results are so drifting apart? Maybe some data type limit?
![grafik](https://user-images.githubusercontent.com/18444809/45521625-17c19800-b7bf-11e8-93b9-2a9b2649a60e.png)

My solution is to output the values as a string

**Comment by torkelo** [comment]
> But can you explain why the results are so drifting apart? 

What? I can't see any driting in the image. Not sure what you mean. 

Please ask questions on the community site https://community.grafana.com
