### ISSUE TITLE
Strange behavior in piecharts

### ISSUE THREAD

**Issue by ventris** [grafana/grafana#13276]
### What Grafana version are you using?
5.x and 4.x

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
centos

### What did you do?
Upgrade Grafana to a new major version, going from 4.x to 5.x.

### What was the expected result?
That the piecharts would behave as they did in 4.x. If you showed the legend at the bottom of the panel it would be shown as an list with columns.

![Grafana 4.x](http://tinbox.nu/grafana4x.PNG)

### What happened instead?
The piecharts legend is changed to a single line with the values listed after each other.   
This breaks most of the dashboards because the line dont wrap so most of the values will be outside the panel. And if you want to show multiple values/percentage it will get cluttered because the values will be shown after each other. 

![Grafana 5.x](http://tinbox.nu/grafana5x.PNG)

@tomwilkie @davkal

**Comment by marefr** [comment]
Please open an issue in [pie chart repository](https://github.com/grafana/piechart-panel/issues). 

Make sure that you've updated pie chart panel to the latest version.
