### ISSUE TITLE
New singlestat panel logo

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13281]
The current singlestat logo is not very descriptive of what the panel shows:
![image](https://user-images.githubusercontent.com/10999/45552514-6e67ba00-b831-11e8-8eba-d61bed148399.png)
 

I think a colored (or gradient) decimal number would make more sense. Not sure if there is room for a mini graph: 

inspiration:
![image](https://user-images.githubusercontent.com/10999/45552588-ba1a6380-b831-11e8-94fa-e90a16a275f9.png)
 

@bulletfactory any thoughts?

**Comment by bulletfactory** [comment]
I've had this in the back of my head over the weekend and will try some things out today and post them here.

**Comment by bulletfactory** [comment]
worked up an idea to be more descriptive. adding a gauge made it feel busy, but am exploring that a little more. I think this is a good start and this addition works well in the group.

![singlestat](https://user-images.githubusercontent.com/1950595/45703212-3a460f00-bb39-11e8-9b2b-9628b7136bed.jpg)

**Comment by torkelo** [comment]
updated in master!
