### ISSUE TITLE
MySQL and HAProxy closed connection issue 

### ISSUE THREAD

**Issue by odeshog** [grafana/grafana#13286]
### What Grafana version are you using?
Version 5.2.4 (commit: 0bbac5c)
### What datasource are you using?
mysql (template variables) and influxdb (metrics, performance data from Icinga2 monitoring platform)
### What OS are you running grafana on?
CentOS 6.7
### What did you do?
loaded dashboard
### What was the expected result?
template variables read from mysql datasource
### What happened instead?
got an invalid connection, reloading (or updating/testing the datasource) fixes the problem. Grafana logs only show a status 500 on debug level.
From testing with different timouts serverside, what we believe is happening is that the mysql server (or in our case, haproxy) closes the connection due to inactivity, since we only use the mysql datasource for templating. It seems grafana later tries to reuse the closed connection. 
Please let us know if we should provide any more information.

Our use case is maybe a bit special, but for storing performance data from Icinga2 it's really very convenient to use mysql/postgres for template variables later used to query e.g InfluxDB, or some other TSDB.

**Comment by torkelo** [comment]
Would it be possible to create a docker-compose setup of your ha proxy and grafana & mysql setup so we can test and try to replicate?

**Comment by odeshog** [comment]
@torkelo I recreated the error in a much simpler setup, just grafana with mysql datasource, no haproxy. The setup is:

- mysql datasource: 10.0.34-MariaDB-0ubuntu0.16.04.1, wait_timeout set to 30s for testing. I created a table with a single value for testing, but any db will do I suppose. 
- grafana 5.2.4 on ubuntu 16.04.1, default backend.
- dashboard with a single query variable from mysql datasource 

I set the template variable to refresh on dashboard load. Wait 30s, mysql server connection goes to FIN_WAIT2 and when I reload the dashboard I get invalid connection.

Unfortunately we don't really use docker (we're a backwards bunch...) but we could probably put together docker-compose for this. Do you still want that in this simpler setup or is it clear as is now?

**Comment by cbonte** [comment]
Hi @odeshog and @torkelo,
shouldn't we make a call to `engine.SetConnMaxLifetime()` here ?
https://github.com/grafana/grafana/blob/0254a29e35e9404ccc0ccfdc06af8dcac0cd508f/pkg/tsdb/sql_engine.go#L102
* with a default "small" value (as done for `SetMaxOpenConns` and `SetMaxIdleConns`
* or by providing the same value of the configuration parameter `conn_max_lifetime` (http://docs.grafana.org/installation/configuration/#conn-max-lifetime)
* or allowing datasources to tune those 3 parameters

Btw, to reproduce the issue, you can also explicitely kill the mysql connection on the server side.
As a complement : https://github.com/go-sql-driver/mysql/issues/657

**Comment by odeshog** [comment]
Yup that should do it. I guess ideally it should be configurable, but for us a default value would be fine. There is actually an issue for max open/idle connections, #11711. Sadly seems the PR for it kind of died(?), otherwise this issue could probably be solved there as well. 

> Btw, to reproduce the issue, you can also explicitely kill the mysql connection on the server side. 

Haha yeah that's true :)

**Comment by marefr** [comment]
Thanks for your clarifications. I updated #11711 to include SetConnMaxLifetime so will close this.

**Comment by marefr** [comment]
@odeshog btw that's a cool username - makes me think of a place in Sweden close to where I grow up.
