### ISSUE TITLE
Deleting provisioned dashboard folder, dashboards does not return

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13280]
After deleting a provisioned folder with dashboards (gdev-dashboards) for example it deletes the folder and the dashboards. After a few seconds the folder is restored by provisioning system but dashboards are not restored (even after grafana server restart). 

Seems the dashboards are still left in dashboard_provisioning table after deleting a folder with provisioned dashboards.

**Comment by thomasbarton** [comment]
@torkelo i ran into this same issue - how did you solve it?

**Comment by torkelo** [comment]
I removed the contents of the dashoard_provisioning table

**Comment by torkelo** [comment]
@bergquist can you find time to investigate this?

**Comment by bergquist** [comment]
I will look into this tomorrow.

**Comment by bergquist** [comment]
The problem is that the dashboard within that folder are never deleted from `dashboard_provisioning` when a folder is deleted. 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/dashboard.go#L318
