### ISSUE TITLE
Grafana V.5.4 with postgresql database

### ISSUE THREAD

**Issue by ferryferdian** [grafana/grafana#13297]
Hello 
I'm new to grafana and trying to install Grafana 5.4 on my windows 10 notebook 

trying to use postgresql database but when i start the grafana-server it shows an error : 

[31mEROR[0m[09-17|09:15:00] Server shutdown                          [31mlogger[0m=server [31mreason[0m="Service init failed: Migration failed err: pq: unexpected error: \"setting PGLOCALEDIR not supported\""

 
![image](https://user-images.githubusercontent.com/21187629/45604056-e533cb80-ba5a-11e8-872d-2e071ab5f078.png)

**Comment by marefr** [comment]
Setting PGLOCALEDIR is not supported by our third party postgres library ([reference](https://github.com/lib/pq/issues/414)).
