### ISSUE TITLE
Customize the x-axis and y-axis metrics

### ISSUE THREAD

**Issue by yaorongwang** [grafana/grafana#13299]
1.grafana version is: 5.2.2
2. The data source is: elasticsearch
3. I want to do the following:
  The x-axis is the index A, the y-axis is the index B, and the point displayed on the graph is the intersection of A and B in the specified time period.
Does grafana support?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

No that's not supported.

**Comment by yaorongwang** [comment]
I know, thank you ！！
