### ISSUE TITLE
render images for panel "zabbix triggers" dont show nothing

### ISSUE THREAD

**Issue by diegoarioza** [grafana/grafana#13290]
Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
zabbix
### What OS are you running grafana on?
ubuntu 16
### What did you do?
show image rendered png
### What was the expected result?
anexed images...
![alerta1](https://user-images.githubusercontent.com/11810798/45568343-c05d0f80-b832-11e8-8e67-c073099a65e5.PNG)
![alerta2](https://user-images.githubusercontent.com/11810798/45568344-c05d0f80-b832-11e8-91e4-478aee2fb122.PNG)
![alerta3](https://user-images.githubusercontent.com/11810798/45568345-c0f5a600-b832-11e8-9aea-26f593f36862.PNG)

**Comment by torkelo** [comment]
please open issue here, https://github.com/alexanderzobnin/grafana-zabbix
