### ISSUE TITLE
Can't log in to local postgresql database from grafana instance

### ISSUE THREAD

**Issue by alphagoh** [grafana/grafana#13308]
Hello,

I am getting the following error message when adding as a datasource.

dial tcp 127.0.0.1:5432: connect: connection refused

I am trying to connect to postgresql database on the following host: localhost:5432. I have no problem doing so from Pgadmin 4 for instance. I already reconfigured pg_hba.conf and postgresql.conf files to allow broader access to the database. 

I am finding very little ressourced online on this particular issue.

**Comment by marefr** [comment]
Please search for answers and ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
