### ISSUE TITLE
use variables to repeat lines overwrites static queries

### ISSUE THREAD

**Issue by franzbeppe** [grafana/grafana#13302]
Hello,
here some preliminar information:
* Grafana version 5.2.4
* InfluxDB (v 1.3.5) datasource
* CentOS 7.3

* **What i'm doing**: I've created a graph dashboard. The graph is composed by two queries. The query A uses a variable, the query B doesn't use the variable. I've repeated the lines using the 'Repeat by variable' options and i've created a number of lines equals to the the number of values of the variables. The query B, in every successive lines,  has a different static value which i've manually inserted.

* **Expected behavior** : every successive lines will have a new value for the variable in query A, and will have the query B as manually inserted.

* **What happens** : lines are correctly repeated for all the variable values in query A, but query B is also repeated as inserted in in the first line a the top of the page. If i change query B, (which does not contains the variable), in all the successive lines the change is not maintained. In older Grafana version the behavior was this.

**Comment by torkelo** [comment]
repeating is not done per query but the whole panel is repeated based on the "source panel" (the first panel) so whenever you reload the dashboard the source panel is going to be copied for each value in the variable you repeat by. So the source panel's query B will be used

**Comment by franzbeppe** [comment]
Hello Torkel, 
thanks for your reply, i'd like to stress the fact that in the previous versions this didn't happen.
I didn't read nothing about this matter in the change logs or am i wrong?

**Comment by torkelo** [comment]
> thanks for your reply, i'd like to stress the fact that in the previous versions this didn't happen.
I didn't read nothing about this matter in the change logs or am i wrong?

That is very strange, or close to impossible. Panel repeats have always used the complete source panel when repeating the panels. So if you modify the query on a repeated panel instance Grafana it will reset that change on next dashboard reload. There might have been some optimizations in Grafana v4 that allowed some changes to a repeated instance but keeping query changes should not have worked.
