### ISSUE TITLE
Template to cover multiple path components?

### ISSUE THREAD

**Issue by JeroenVdb** [grafana/grafana#1330]
The website performance data in receive from Graphite has the website's navigation path in the path.

Example:
```
http://jeroenvdb.be/ -> sitespeed.http.jeroenvdb.be.score.median
http://jeroenvdb.be/sports/ -> sitespeed.http.jeroenvdb.be.sports.score.median
http://jeroenvdb.be/sports/my-sports-article/ -> sitespeed.http.jeroenvdb.be.sports.my-sports-article.score.median
```

So depending on the url/page I'm testing I have additional levels or not. Is there a way I can put the components between "http" and "score" in one single template with Graphite or Grafana?

**Comment by torkelo** [comment]
Not right now, you can use a custom template variable and enter all those values. Or create a scripted dashboard that inserts those template variable options. But for the query variable, it only supports fetching options from one graphite node segment.

**Comment by torkelo** [comment]
closing this due to lack of interest
