### ISSUE TITLE
Sparse data is not always visible

### ISSUE THREAD

**Issue by ckyoog** [grafana/grafana#13310]
### What Grafana version are you using?
5.1.2

### What datasource are you using?
Prometheus (Actually I don't think it is related to a specific datasource)

### What OS are you running grafana on?
Linux

### What happened instead?
I posted [my issue](https://community.grafana.com/t/how-to-always-show-sparse-data-from-prometheus/10409) first on Grafana Community Forum as the issue-posting guide tells me. As of writing here, there's been no reply. That's why I am submitting the issue here now. I will add more details if you find that is not enough to address the problem.

**Comment by marefr** [comment]
Please have patient until we get there and please don't double-post here.
