### ISSUE TITLE
Time Range Issue with Delta option in Singlestat

### ISSUE THREAD

**Issue by anandkshitiz** [grafana/grafana#13314]
### What Grafana version are you using?
 Grafana v5.1.0 (commit: 844bdc53a)
### What datasource are you using?
Prometheus
### What did you do?
I am using the Delta Option in **Singlestat** to show the number of requests to an API in the selected time range using this query in Grafana 
**_sum(http_server_requests_seconds_count{uri="<my_end_point>"})_**
### What was the expected result?
Selected Time range  Sep 17th 00:00:00 UTC to Sep 18th 00:00:00 
Request Count at Sep 17th 00:00:00 in Prometheus - **0**
Request Count at Sep 18th 00:00:00 in Prometheus - **21**
Difference and the actual result **should** be 21-0 = **21**
### What happened instead?
Instead, while making the query, Grafana doesn't set the start time as Sep 17th 00:00:00 UTC instead it sets the start time range with 29min47secods delay. The count in Prometheus at Sep17th 00:29:47 is 3. So, the actual result shown in Grafana (which is incorrect) becomes 21-3 = 18.
FYI: Prometheus is showing the correct stats.

<img width="211" alt="screen shot 2018-09-18 at 7 42 38 am" src="https://user-images.githubusercontent.com/23467894/45660574-05c15b80-bb17-11e8-8c68-e50c2f5b4fb6.png">

**Comment by torkelo** [comment]
<img width="929" alt="screen shot 2018-09-18 at 12 47 30" src="https://user-images.githubusercontent.com/10999/45682619-138bd680-bb41-11e8-86bf-dce06a458926.png">

Unable to replicate, can you try v5.2.4 ?
