### ISSUE TITLE
Variable value getting escaped depending on Edit Mode

### ISSUE THREAD

**Issue by gaardiolor** [grafana/grafana#13313]
Hello,

I'm using grafana 5.2.4 with influxdb 1.6.2 on linux. 
I created a variable `department`, type constant, value `sales|engineering` . `Multi-value` and `Include All option` are disabled.

Now I'm trying to use the variable in my query, in the WHERE clause. At first using the query builder.
`WHERE department =~ /^$department$/`

This does not work. When going to the query inspector, I can see the `|` getting escaped: `WHERE ("department" =~ /^sales\|engineering$/)` . 

After switching to raw edit mode (where you can just type the query) it just works (after refreshing). Query inspector also shows the `|` not being escaped. `WHERE ("department" =~ /^sales|engineering$/)`

So it works in raw edit mode, but not in the default query builder mode. 

- Is this a bug ?
- I'm doing this to easily copy dashboards, not all people are allowed to see info of all departments. So my idea was to copy the dashboard, change the variable to include certain departments and give selected people access to that dashboard. Is there a better way ?

**Comment by torkelo** [comment]
If you don't want regex escaping of the value you can use `${variable:raw}` syntax
