### ISSUE TITLE
Grafana in docker - "Failed to start session"

### ISSUE THREAD

**Issue by ondrejFuchs** [grafana/grafana#13315]
Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
influxdb
### What OS are you running grafana on?
ubuntu 16.04
### What did you do?
Start granana in docker
### What was the expected result?
docker-compose:
...
grafana:
    image: grafana/grafana:5.2.4
    volumes:
     - ./grafana:/var/lib/grafana
...
In folder grafana are:
grafana.db -rwxrwxrwx , plugins drwxr-xr-x, png drwxr-xr-x, sessions drwx------

Errors:

> t=2018-09-18T07:31:24+0000 lvl=eror msg="Failed to start session" logger=context error="mkdir /var/lib/grafana/sessions/0: permission denied"
> t=2018-09-18T07:31:24+0000 lvl=eror msg="Request error" logger=context userId=0 orgId=0 uname= error="runtime error: index out of range" stack="/usr/local/go/src/runtime/panic.go:505 (0x433b48)\n/usr/local/go/src/runtime/panic.go:28

**Comment by Yakha** [comment]
hi @ondrejFuchs 

If I'm not wrong you must specify the UID of the user in your docker compose, maybe that can explain the permission issue ?

Grafana changed the UID : 
<5.1 = 104 (UID)
>=5.1 = 472 (UID)

line to add in your docker-compose :  user: "472" in your case

Which version of docker are you using ? docker , docker-ce ? Docker security check can change between docker version

Hope that can help you

best

**Comment by ondrejFuchs** [comment]
Thanks for your response. I did it. It resolvded it but I still have problem with:

> t=2018-09-18T08:57:07+0000 lvl=eror msg="Failed to change active organization" logger=context userId=5 orgId=1 uname=<myuser> error="attempt to write a readonly database"

If i sed chmod 777 to folder grafana - everything is OK, but if I sed 755, i cant switch organization. User dont have permission. I dont want to open all folder to 777. Any idea?

**Comment by torkelo** [comment]
please read the docs on docker mounts & permissions 
http://docs.grafana.org/installation/docker/#grafana-container-using-bind-mounts
http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
