### ISSUE TITLE
Legend does not occupy whole width

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#13312]
### What Grafana version are you using?

5.2.1

### What datasource are you using?

Irrelevant

### What OS are you running grafana on?

Looking at it in Google Chrome 69 on macOS.

### What did you do?

Set legend width to the same value across all panes to have aligned graphs.

### What was the expected result?

Legend would occupy whole width.

### What happened instead?

Legend only occupies minimal width.

![image](https://user-images.githubusercontent.com/89186/45648402-54bab280-ba7d-11e8-8ac1-1339db98ddf6.png)

It looks like it should if I:

* Add `width: 100%` to `graph-legend-content graph-legend-table baron baron__root`
* Remove all width properties from `graph-legend-scroll baron__scroller` inside

![image](https://user-images.githubusercontent.com/89186/45648492-98adb780-ba7d-11e8-926b-25f2e920b25f.png)

I'm fairly sure it was working as expected not that long ago.

**Comment by torkelo** [comment]
strange, I am unable to replicate it (on OSX with chrome 68), 

Can you replicate it here? 
https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

**Comment by bobrik** [comment]
Set legend width and you'll see it:

![image](https://user-images.githubusercontent.com/89186/45700786-4b375600-bb22-11e8-94a3-f0ecf2eb8d34.png)

**Comment by torkelo** [comment]
seems to have been introduced in Chrome 69,  Chrome 68 it works fine in.

**Comment by bobrik** [comment]
I hope you're not running 68 with [all these CVEs](https://chromereleases.googleblog.com/2018/09/stable-channel-update-for-desktop.html).

Firefox has the same behavior:

![image](https://user-images.githubusercontent.com/89186/45763939-6f5c6b00-bbe6-11e8-9153-e8a5b22ea0de.png)
