### ISSUE TITLE
[Bug] Grafana data proxy should drop origin header

### ISSUE THREAD

**Issue by ssozonoff** [grafana/grafana#13328]
Using Elasticsearch 5.6 the datasource (in proxy mode) passes tests and connects properly however its impossible to perform any query in a panel. Seems like Grafana proxying is POST'ing requests to ES instead of performing a GET which is causing a 502.

Grafana 5.2.2

`t=2018-09-18T20:15:03+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=1 orgid=1 username=admin datasource=elasticsearch uri=/api/datasources/proxy/2/_msearch method=POST body="{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"my_stats_2018\",\"max_concurrent_shard_requests\":256}\n{\"size\":500,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1521407703352\",\"lte\":\"1537301703352\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"business.objId:6435\"}}]}},\"sort\":{\"@timestamp\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}},\"script_fields\":{},\"docvalue_fields\":[\"@timestamp\"]}\n"
`

**Comment by MrSantamaria** [comment]
Currently using ES 6.3, my queries are also being sent as POST and they are working. It seems like the issue is with the proxy setup.

**Comment by ssozonoff** [comment]
You are right POST is permitted to ES. So I dont understand what the problem is then. Why the Datasource validates on passes the self test yet all queries fail with a 502

**Comment by msteggink** [comment]
Did it work before? What type of queries are you firing? Any hints in the ElasticSearch logging? A 502 might indicate faulty queries. Are you trying to do queries on text? You might need to use the keyword:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/fielddata.html

**Comment by torkelo** [comment]
Do you have any error returned by Elasticsearch? Open Query inspector to view request and response from elasticsearch

**Comment by ssozonoff** [comment]
Getting a 403 but dont understand why. Have a Wireshark trace and cant spot the issue yet!! As mentioned same query works in Curl. I am clearly missing something.

**Comment by marefr** [comment]
Please enable ES debugging in Grafana and check Grafana server log:

```
[log]
filters = tsdb.elasticsearch:debug,tsdb.elasticsearch.client:debug
```

**Comment by ssozonoff** [comment]
My fix for this has been to strip the Origin header in nginx.

**Comment by marefr** [comment]
@ssozonoff glad you solve it. So the problem was that you nginx proxy added the origin header?

**Comment by ssozonoff** [comment]
No the problem is the browser adds the Origin and the DS Proxy simply passes it along, which according to Grafana documentation is not what is supposed to happen in Server Mode. Documentation clearly states that using "Server Mode" avoid CORS issues... which it would if the DS Proxy would not pass on the Origin header it receives from the brower.

**Comment by marefr** [comment]
Just verified and seems Chrome include origin header even though it's not a CORS request where Firefox don't. Agree with you that the origin header should be removed in Grafana proxy.
