### ISSUE TITLE
Dashboard variable values getting shared across other dashboards

### ISSUE THREAD

**Issue by gaardiolor** [grafana/grafana#13320]
Hello,

I'm using grafana 5.2.4 with influxdb 1.6.2 on linux.
I've created 2 identical dashboards, the only difference being a variable, `department`. `Multi-value` and `Include All option` are disabled. `Hide` is set to `Variable`. 

- dashboard 1: `.*` . 
- dashboard 2: `sales|engineering`

I'm using that variable in a WHERE clause. `WHERE ("department" =~ /^${department:raw}$/)` . Different users get access to either one or the other dashboard.

Problem is that this does not work as expected. If I save the variable of dashboard 1, the users of dashboard 2 also get all departments. It looks like the dashboard variables are shared across dashboards and dashboard 1 getting a higher priority. 

Steps to reproduce:

1. Create dashboards and variables. Play around with the order in which you save the variables / dashboards and do the steps below. 
2. Go to dashboard 1
3. See that it's working as expected. Query inspector shows `.*` being used.
4. Go to dashboard 2
5. See that it's not working as expected. Query inspector shows `.*` being used.
6. Go to dashboard 2> settings > variables > $department > Update
7. Click save to save the dashboard
8. Go to dashboard 2
9. See that it's working as epected. Query inspector shows `sales|engineering` being used. 
10. Go to dashboard 1. 
11. See that it's working as expected. Query inspector shows `.*` being used.
12. Go to dashboard 2
13. See that it's not working as expected. Query inspector shows `.*` being used. 

Interestingly also users not even having access to dashboard 1 are getting the wrong variable value (of dashboard 1 instead of 2) in dashboard 2. 

Bug ? Or am I missing something ?

**Comment by torkelo** [comment]
<img width="594" alt="screen shot 2018-09-18 at 17 26 55" src="https://user-images.githubusercontent.com/10999/45698352-13eb9800-bb68-11e8-88fe-c9b948142e9f.png">

I expect you missed saving the variable value change (see checkbox in screenshot above). 

Please know that variables can be changed & overriden via url

**Comment by gaardiolor** [comment]
Hi @torkelo , I don't have that option ?

![image](https://user-images.githubusercontent.com/22920143/45710330-a26f1200-bb86-11e8-88b8-c7ecd332c963.png)

**Comment by torkelo** [comment]
You need to change a variable value for it to show up

**Comment by gaardiolor** [comment]
I did.. @torkelo 

dashboard > settings > Variables > department > changed `sales|engineering` to `.*` > update > Save > the checkbox is not there. Went back to the dashboard > save icon > checkbox is not there. I'm logged in as admin.

Since variables are not safe to use in my case I'm going to hardcode departments. But I think this variable implementation needs some work. At the very least it's confusing, and since I don't have the checkbox probably something else is wrong.

**Comment by torkelo** [comment]
> dashboard > settings > Variables > department > changed sales|engineering to .* > update > Save > the checkbox is not there. Went back to the dashboard > save icon > checkbox is not there. I'm logged in as admin.

If you change the custom variable definition that does not always update it's current value. After you changed it's definition to `.*` make sure you go back to dashboard and set that as the current value. Then save, you should now see the checkbox. 

> Since variables are not safe to use in my case I'm going to hardcode departments. 

What do you mean not safe? What will hardcoded departments do? You know that if you add a data source in Grafana any user can query any data from that data source? It's not just variables that make this possible. The frontend builds the queries, so if you have a datasource like InfluxDB any Grafana user that has access to use that data source will be able to issue any query (Technically if they know http).

**Comment by gaardiolor** [comment]
Thanks for your answer. I've made the variable hidden, because my idea was that users would not be able to alter it anyway. 

I thought grafana was handling the queries to the backend, but that's not correct. In Developer tools I can see the queries going to the Grafana api. I can indeed alter them and get data. I guess I have to find another way to get multi-tenancy.. copying databases, filtering them and create new organizations and datasources seems inefficient..
