### ISSUE TITLE
Rows deprecated or not?

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#13327]
Are rows deprecated or not? Found a mention about it in current docs 

http://docs.grafana.org/guides/basic_concepts/#row

Also http://docs.grafana.org/guides/whats-new-in-v5/#new-dashboard-layout-engine is said that rows are no longer needed but if I use them, is it okay or not then?

The Grafana UI doesn't offer any button to create them.

**Comment by msteggink** [comment]
Grafana does allow the creation of Rows, with the "Row" panel. Although not necessary to create dashboards, the rows make it very easy to group a number of panels and collapse/expand them.

**Comment by torkelo** [comment]
They are rows are no longer required to layout panels, they are there mostly for legacy reasons to not break old dashboards, and to support long dashboards with collapsable sections

**Comment by simPod** [comment]
So are they not going to be deprecated soon?

**Comment by torkelo** [comment]
no

**Comment by simPod** [comment]
Thank you
