### ISSUE TITLE
Explore: tab completion not working for all metrics

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13336]
See screenshot - I was expecting the label name and label value popup.  Was I too fast?

![qkjvik8liz](https://user-images.githubusercontent.com/444037/45744997-20bbca80-bc00-11e8-8957-ebc159676a01.gif)

(This is build Grafana v5.3.0-pre1 fe9d86c)

**Comment by davkal** [comment]
Looks like a parsing issue of the metric.
