### ISSUE TITLE
Document commands to run with grafana via node, nginx

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1333]
I'm trying various permutations of running `node sample/server.js`:
```
$ node sample/server.js
Http Server running at http://localhost:8000/
```
so far so good. When I visit `localhost:8000` via browser or `curl`, I get a 404, and the server process spits out:
```
GET / curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
404 Not Found: ./src/
```

Some more specific docs about how to point `node` (or the other servers that are supposed to work) should be added.

If you can help me resolve this I'll send some documentation PRs. Thanks!

**Comment by ryan-williams** [comment]
it seems there are some undocumented assumptions about how to set up grafana with nginx as well.
* the provided `sample/nginx.conf` specifies a `server` module that needs to be included from or wrapped in a `http` module from somewhere else?
* `server.location.root` needs to be pointed at `$GRAFANA/src`, afaict, where an `index.html` will provide a sensible default page for a user to land on?
* having made some of the above changes and run `nginx` against grafana's `nginx.conf` file, I can load `/`, but I get redirected to `/#/dashboard/file/default.json` where I am presented with a page that seems to be missing CSS:
![](http://f.cl.ly/items/3h232J0a0N1t2d1g1F2g/Screen%20Shot%202015-01-12%20at%206.54.47%20PM.png)

I needed to run it on not-port-80 as well since I am on a machine that I don't have root on.

Soliciting advice on how to get it running via nginx or node!

Meanwhile I ran the dev server via `grunt server` and the instructions [here](http://grafana.org/docs/contributing/building_from_source.html), I created some test graphs with `randomWalk` metrics, e.g.:
![](http://f.cl.ly/items/3Y123Q0D1f083z310a3z/Screen%20Shot%202015-01-12%20at%206.56.23%20PM.png)
However, the graphs are empty and have perpetual spinners in their upper-right-hand corner.

![](http://f.cl.ly/items/3h1g4508022H0u2R2s2a/Screen%20Shot%202015-01-12%20at%206.57.48%20PM.png)

Should I expect `randomWalk` graphs to show me data in this situation? Any other advice about getting some kind of "hello world" to work? Thanks..

**Comment by ryan-williams** [comment]
on the `grunt server` server, `/` redirects to `/#/dashboard/file/default.json`, and the javascript console shows it failing to find `/config.js?bust=1421109144936`. is `grunt server` supposed to be able to serve my `config.js` out of the Grafana directory (which is where I ran `grunt server` from)?

**Comment by torkelo** [comment]
I need to remove the sample/ dir it is an old directory that is not relevant any more. 

grunt dev starts the development server but you still need to specify metric datasources (graphite, influxdb or OpenTSDB) in config.js.  copy config.sample.js in /src to config.js and add your time series data base according to http://grafana.org/docs/#configuration

**Comment by torkelo** [comment]
nginx and static hosting of content is just. 

```
user www-data;
worker_processes 1;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  server_tokens off;
  server_names_hash_bucket_size 32;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  gzip on;
  gzip_disable "msie6";

  server {
    listen 80 default_server;
    server_name _;

    location / {
      root /srv/www/grafana/dist;
      index index.html;
    }
  }
}

**Comment by ryan-williams** [comment]
Interesting, thanks for clearing out `sample` if that was out of date.

I did (attempt to) specify my datasources in `config.js` (copied from `src` into the top level):
```
      datasources: {
        graphite: {
          type: 'graphite',
          url: "http://demeter-login2.demeter.hpc.mssm.edu:2003"
        },
        elasticsearch: {
          type: 'elasticsearch',
          url: "http://demeter-login2.demeter.hpc.mssm.edu:8090",
          index: 'grafana-dash',
          grafanaDB: true
        }
      },
```
I had a carbon daemon running on port 2003, and 8090 is a port I picked randomly since I couldn't bind to 80; my nginx config had appropriate references to 80 changed to 8090, accordingly.

I'll try again today with fresh eyes and see if anything from your nginx config above looks relevant / necessary for me to change.
* Is such an example config in the docs anywhere?
* What is `/srv/www/grafana/dist`? Is that where grafana is installed for you?

**Comment by torkelo** [comment]
There are example config snippets at: 
http://grafana.org/docs/#configuration

yes /srv/www/grafana/dist is the folder where I deploy a build of grafana. 

So if you want to run from master you can either create an optimized build using grunt build or grunt release (creates zip/tar file) or download from grafana.org/download

**Comment by ryan-williams** [comment]
Thanks, I've read the #configuration link a few times, but none of the `nginx.conf` you sent me above is there; do the docs live in a repo somewhere that I can send updates to?

Anyway, I'm at an impasse trying to get grafana to run locally. Here's what I've done:
* Download and run elasticsearch, verify successful `telnet` to `localhost:9200` ([gist](https://gist.github.com/ryan-williams/eef86a8245933d844cc9))
* Download/Install `carbon`, run `bin/carbon-cache.py start`, verify successful `telnet` to `localhost:2003` ([gist](https://gist.github.com/ryan-williams/95f7eb739f3d881b3656))
* Download `grafana`, fetch [this config.js](https://gist.githubusercontent.com/ryan-williams/933ff60d2f8f197aacb3/raw/b804e9eda664186c54d65ec8a43380f2d1ba7903/config.js) and [this nginx.conf](https://gist.githubusercontent.com/ryan-williams/933ff60d2f8f197aacb3/raw/df09502e08ec07918bda0cf5116b82e64690f616/nginx.conf) ([gist](https://gist.github.com/ryan-williams/3c94300b74b2653dae8c))
  * note the change to port 8080, since I don't want to run as root (this example is on my laptop, but ultimately I want to run on a cluster machine where I don't have root)
* I already have `nginx` installed (via `brew install nginx`); run it from within `grafana` directory via `nginx -c $PWD/nginx.conf`, it launches successfully..
* Open `localhost:8080` in browser, get redirected to `http://localhost:8080/#/dashboard/file/default.json`, get a page with no CSS:
![](http://f.cl.ly/items/2Z2n0Y0L3I3z083n0T3J/Screen%20Shot%202015-01-13%20at%2012.56.42%20PM.png)
* note: no errors in javascript console
* I get the same result in Safari and Chrome, so it does not appear to be an issue with my browser, cookies, etc.

Do you have any ideas why a clean install like this would silently fail to load all CSS?

**Comment by ryan-williams** [comment]
Meanwhile, if I try to build from source, per your recommendation:

```
$ git clone git@github.com:grafana/grafana.git
$ cd grafana
$ wget https://gist.githubusercontent.com/ryan-williams/933ff60d2f8f197aacb3/raw/b804e9eda664186c54d65ec8a43380f2d1ba7903/config.js -O src/config.js
$ sudo npm install -g grunt-cli
$ sudo npm install
```
([full gist](https://gist.github.com/ryan-williams/e8d88f926446ee14a1ee))

At this point, I tried running `grunt server`, which is what [the docs seem to advise](http://grafana.org/docs/contributing/building_from_source.html), only to find that `localhost:5601` is erroring because it can't find CSS files; LESS has not been compiled.

So I run `grunt build`, then `grunt server` again, and it seems like I have a working grafana...

![](http://f.cl.ly/items/2A1L3R2Y3e0Q280D0i0q/Screen%20Shot%202015-01-13%20at%201.19.53%20PM.png)

The graph is seeded with a `randomWalk`:

![](http://f.cl.ly/items/0Z3y1E0i2e3O2S0a3o2Y/Screen%20Shot%202015-01-13%20at%201.30.09%20PM.png)

However the main page just has a spinner on the graph and no data ever shows up.

![](http://f.cl.ly/items/1f2q3Z2z1u2y3N0Q0w0J/Screen%20Recording%202015-01-13%20at%2001.31%20PM.gif) :(

How can I debug this?

**Comment by ryan-williams** [comment]
oof, hypothesis: am I supposed to point grafana at a graphite-web frontend server? I assumed that I would point grafana at a carbon daemon.

**Comment by torkelo** [comment]
You should put the http url of your graphite-web instance, carbon does not have any http query api. 

Regarding the css issue, Did you download one of the zip/tars from this page: http://grafana.org/download/ ? 

It looks like you are trying to run grafana on a git clone or source copy of grafana and not a build. The git clone / source zip does not contain any css (those needs to be generated by grunt)

**Comment by ryan-williams** [comment]
* [3 comments ago](https://github.com/grafana/grafana/issues/1333#issuecomment-69788842) documented my failures trying to run with a tar download from http://grafana.org/download/
  * cf. the `wget` on [the first line of the gist](https://gist.github.com/ryan-williams/3c94300b74b2653dae8c#file-gistfile1-txt-L1) on the line that starts "Download `grafana`"
  * as you can read above, that attempt ended with the server seemingly failing to load CSS, but not reporting any errors in the JS console.
* [2 comments ago](https://github.com/grafana/grafana/issues/1333#issuecomment-69794213) documented my failures trying to build from a git clone.
  * I noticed that the `git clone`d repo needs its LESS compiled into CSS, which I also discussed in that comment, but the documentation could be clearer on this point.
* Good to know that I should be pointing at a graphite-web.
* I am happy to try to document this and other gotchas / holes in the documentation if you would let me know where I can do that.

**Comment by torkelo** [comment]
@ryan-williams Yes, any feedback on how to improve the docs would be great. 

* It looks like your web server (nginx) is not configured correctly. The css is returned with the incorrect mime types, which causes the browser to not load it. 
* The guide mentions pretty clearly that you need to compile LESS to CSS and how to do it http://grafana.org/docs/contributing/building_from_source.html

I hope you get it to work :)

**Comment by torkelo** [comment]
Oh, and the docs can be improved and in this repo, https://github.com/grafana/grafana.org
