### ISSUE TITLE
Explore: Hide time column in table view?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13335]
The time is not really important in the table view.

<img width="1462" alt="screen shot 2018-09-19 at 10 57 02" src="https://user-images.githubusercontent.com/444037/45742687-d84dde00-bbfa-11e8-99fe-e04332a23d89.png">

**Comment by tomwilkie** [comment]
Actually, they are - perhaps we should just not show time?

**Comment by davkal** [comment]
Addressed in #13712
