### ISSUE TITLE
Explore: preserve datasource when you split

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13348]
0. Have at least two prometheus datasources.
1. Open Explore (default datasource shows)
2. Change the datasource
3. Click Split

Result: split opens with default datasource.

Seen in the demo today.

**Comment by gauravk48** [comment]
Its a nice feature, do you know which update has the option to choose the datasource option? I am running v5.2.1 and I don't see that option.

**Comment by davkal** [comment]
@gauravk48 the datasource selector is available since v5.3.0-beta1.
Also, since it's a beta feature, we highly appreciate feedback. If it's a bug, just open an issue, or if you're missing something, please write to david@grafana.com

**Comment by davkal** [comment]
Already fixed.
