### ISSUE TITLE
metrics with special charachter and graphite datasource

### ISSUE THREAD

**Issue by unix196** [grafana/grafana#13345]
* Grafana version - 5.1.4
* Datasource - graphite
* OS - Debian GNU/Linux 8.6 (jessie)
We have third-party application which send metric (kafka offset lag) to graphite server. When metrics receives graphite server, it creates following directory and files:
```
ls -l /graphite/whisper/stats/kafka/

drwxr-xr-x 4 graphite graphite 46 сен 19 08:01 topic=evs-action
drwxr-xr-x 3 graphite graphite 24 сен 19 08:00 topic=evs-counter
drwxr-xr-x 3 graphite graphite 24 сен 19 08:00 topic=evs-match
...
```
```
ls -l /graphite/whisper/stats/kafka/topic\=ft-store/group\=flumechannel-ft-store/partition\=0/
-rw-r--r-- 1 graphite graphite 585292 сен 19 13:54 gauge=lag_g.wsp
-rw-r--r-- 1 graphite graphite 585292 сен 19 13:53 gauge=logSize_g.wsp
-rw-r--r-- 1 graphite graphite 585292 сен 19 13:54 gauge=offset_g.wsp
```
Many metrics have the same character `=`. 
### What did you do?
1. Then I try create graphic in grafana dashboard.
I set this query:
```
stats.kafka.topic=ft-store.*.*.*
```

### What happened instead?
In grafana web interface I receive this error:
```
Bad Request

Target              : stats.kafka.topic=ft-store.*.*.*
Parsed so far       : stats.kafka.topic
Could not parse     : =ft-store.*.*.*
```
is obtained that graphite inerpreter character **=**

2. Also I try create variable
```
$topic=stats.kafka.*
```
and using it in metric editor:
```
stats.kafka.$topic
```
but I receive the same error
3. I try using `\`, `"`, `'` characters for escaping `=`- **unsuccessfully**
```
stats.kafka."$topic".*
stats.kafka.topic\=ft-store.*.*.*
stats.kafka."topic=ft-store".*.*.*
stats.kafka.topic\\=ft-store.*.*.*
stats.kafka.'topic=ft-store'.*.*.*
```
For example error for `stats.kafka."topic=ft-store".*.*.*`:
```
Bad Request

Target              : stats.kafka."topic=ft-store".*.*.*
Parsed so far       : stats.kafka.
Could not parse     : "topic=ft-store".*.*.*
```
4. If I create this query:
```
stats.kafka.*.*.*.*
```
grafana create graph with all topics, consumer, partition ... Chart is becoming very  cumbersome. 

Is there any way to receive this metrics in chart?

**Comment by torkelo** [comment]
For Graphite (it should at least) only support metric names that contain ascii alphanumerics, underscore and periods. The error is from graphite it looks like, there is no way to escape or quote metric names with forbidden chars in graphite
