### ISSUE TITLE
Grafana: Panic when doing clean up

### ISSUE THREAD

**Issue by elunlen** [grafana/grafana#13344]
Version 5.1.2
Default Grafana container is used

Grafana is started and after that it is not used. After approximately an hour it crash with a panic "Index out of range". This happen when "func (srv *CleanUpService) Run(ctx context.Context) error" is executed.
For more information see attached log file. The log file contains a complete log from start of grafana to pod was taken down because of the crash.

Note: A possible reason for failing is that a NFS filesystem was used which does not work well with sqlite. However only one instance of grafana was running.
The actual problem that should be fixed is to not crash in an uncontrolled way.
One of these crashes resulted in a permanently locked database resulting in that grafana cannot be started anymore. Will always fail during startup.

[Grafana-Panic-IndexOutOfRange.txt](https://github.com/grafana/grafana/files/2396708/Grafana-Panic-IndexOutOfRange.txt)

**Comment by torkelo** [comment]
thanks for reporting this, think we need some length checks here:
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/login_attempt.go#L47

**Comment by max-neverov** [comment]
According to the [SQL standard](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt):
```
If AVG, MAX, MIN, or SUM is specified, then
  If TXA is empty, then the result is the null value.
```
So [`SELECT max(id) as id FROM login_attempt WHERE created < ?`](https://github.com/grafana/grafana/blob/bc2a79815834680cb0127426d44c65aa4d77b3a4/pkg/services/sqlstore/login_attempt.go#L40) query always returns null. By running query on empty table the result will be slice with one element: map{"id": nil}.   
That is why length checking is redundant. [There is also a test checking this](https://github.com/grafana/grafana/blob/bc2a79815834680cb0127426d44c65aa4d77b3a4/pkg/services/sqlstore/login_attempt_test.go#L85).   
I couldn't reproduce the bug on Grafana v.5.1.2 (docker) and v.6.0.0 on macos with Sqlite or Postgres.
There is only few migrations run according to the attached log (and even they were skipped), so no `addLoginAttemptMigrations` were run. I suspect the Sqlite DB were corrupted and adding length checking here will not save from a crash in some other place.
