### ISSUE TITLE
Single panel without header view

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1334]
Useful for iframe embedding etc.

**Comment by jamesmulcahy** [comment]
Hi Torkel,

What are your thoughts on how timespan selection would work with this approach.  Would the timespace be specifiable as part of the URL used in the iframe, or would there be a timepicker inside the single panel view?  The latter probably makes this feature easier to deploy, but is more work on your end I guess?

**Comment by torkelo** [comment]
no time picker, the views main purpose is to capture images of panels at specific time (will by done by the grafana backend via phantomjs), and be used as a widget via an iframe. the time must be specified in the url. A mini time picker and zoom out links could be added later if there is a great need for that.

**Comment by jamesmulcahy** [comment]
OK, A time picker would certainly be handy for our use case.  We use grafana for all internal operations/monitoring, but we have a few graphs which we expose to our end-users using some custom JS with flot.js.  I'd love to be able to deprecate this custom code in favour of a "view" onto a specific grafana panel (but a timepicker would be essential for this use case).

**Comment by NorthIsUp** [comment]
My use case is to embed the graph in an iframe. Ideally one would be able to control via query parameter if the nav bar, submenu, and legend were displayed.

**Comment by NorthIsUp** [comment]
if you are using relative syntax in the share url like `http://grafanaurl.whatever.com?panelId=1&fullscreen&from=now-2h&to=now` it would be nice if auto-refresh was also still an option.

**Comment by torkelo** [comment]
implemented in develop branch

**Comment by daniel-middleton** [comment]
@torkelo, when can we expect to see embedding support in master/release TAR? Thanks.

**Comment by torkelo** [comment]
@daniel-middleton not sure, it is technically already implemented in Grafana 2.0 (develop branch, beta release in 2 weeks),  just not added to the share dialog, 

This URL (used for rendering panels to PNG), can also be used in an iframe to embedd a single panel in an iframe. (login with gues/guest to try it)
http://play.grafana.org/v2/dashboard/solo/new-features-in-v18/?panelId=4&fullscreen&from=now-1h&to=now&var-summarize=1m&var-smoothing=4&var-server=backend_01&width=1000&height=500
