### ISSUE TITLE
"Failed to send alert notification email" -  i/o timeout

### ISSUE THREAD

**Issue by taniya1990** [grafana/grafana#13358]
Please include this information:
What Grafana version are you using? v5.2.2
What datasource are you using? postgresSQL
What OS are you running grafana on? Windows 7
What did you do? Test Email
What was the expected result? Send and Receive successfully
What happened instead?Failed to send alert notifications

Anyone please help me to figure out the error.
here are my config file

[smtp]
enabled = true
host = smtp.gmail.com:587
user =sendermailaddress@gmail.com
;If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password =sendermailaddresspassword
;cert_file =
;key_file =
skip_verify = true
from_address = admin@grafana.localhost
from_name = Grafana
; EHLO identity in SMTP dialog (defaults to instance_name)
;ehlo_identity = 
 
error log

t=2018-09-20T12:27:34+0530 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:8080 protocol=http subUrl= socket=
t=2018-09-20T12:27:43+0530 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/logout status=302 remote_addr=[::1] time_ms=35 size=29 referer=http://localhost:8080/alerting/notification/1/edit
t=2018-09-20T12:28:04+0530 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[receivermailaddress@gmail.com]
t=2018-09-20T12:28:14+0530 lvl=eror msg=**"Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp 64.233.184.109:587: i/o timeout"**
t=2018-09-20T12:28:14+0530 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="dial tcp 64.233.184.109:587: i/o timeout"
t=2018-09-20T12:28:14+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=[::1] time_ms=10015 size=48 referer=http://localhost:8080/alerting/notification/1/edit

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Think you need to adjust the from_address to be the same as sendermailaddress@gmail.com. I'm using skip_verify = false. Regarding password, if you have 2FA enabled you'll need to generate a specific password (somewhere in google/gmail account) to be used for smtp configuration in Grafana.

**Comment by taniya1990** [comment]
Thanks marefr
But still the same error. :/

**Comment by xiaolongli827** [comment]
are you solved the problem? I am facing the question.

**Comment by marefr** [comment]
Sounds exactly the same as #8867, i.e. you cannot reach the smtp server over network

**Comment by xiaolongli827** [comment]
My original version of grafana was 5.3.0. When I upgraded grafana to 5.4.3, the problem disappeared.

**Comment by MelakuFt** [comment]
failed to send email notification: dial tcp 142.250.147.109:587: connect: connection timed out
