### ISSUE TITLE
API query can not work for uid 

### ISSUE THREAD

**Issue by daixiang0** [grafana/grafana#13357]
I want to query by uid but failed:

```
[root@dx-app ~]# curl -sS -H "Authorization: Bearer $KEY" localhost:3000/api/search?query=aa | jq
[
  {
    "id": 25,
    "uid": "SsymwCTik",
    "title": "aa",
    "uri": "db/aa",
    "url": "/dashboards/f/SsymwCTik/aa",
    "type": "dash-folder",
    "tags": [],
    "isStarred": false
  }
]
[root@dx-app ~]# curl -sS -H "Authorization: Bearer $KEY" localhost:3000/api/search?query=Ss | jq
[]
```
I use grafana 5.2.4 on centos7.4.

It could be better if show which area can be queried in [doc](http://docs.grafana.org/http_api/folder_dashboard_search/).

**Comment by peterholmberg** [comment]
The search api does not support querying by `uid` as stated in the query parameters section in the document you are referring to.

If you want to get a dashboard by uid you can use the dashboard api instead as documented [here](http://docs.grafana.org/http_api/dashboard/#get-dashboard-by-uid).

**Comment by daixiang0** [comment]
@peterholmberg thanks, but maybe add more details about query area is better
