### ISSUE TITLE
annotation tags: Do not remove all tags with double tags

### ISSUE THREAD

**Issue by rdxmb** [grafana/grafana#13368]
Please include this information:
### What Grafana version are you using?
grafana/grafana:5.2.3 in docker
### What datasource are you using?
influxdb 1.4
### What OS are you running grafana on?
kubernetes
### What did you do?
insert a tag within annotation twice
### What was the expected result?
having two identical tags or just one tag of the two in grafana annotations
### What happened instead?
all tags where removed within grafana

### reproduce:
write annotations to influx via curl
```
curl -qsfi -XPOST 'http://10.139.0.120:30002/write?db=monitoring' --data-binary 'influxevents title="my-title",tags="tag1,tag2,tag3",text="no problem"'
curl -qsfi -XPOST 'http://10.139.0.120:30002/write?db=monitoring' --data-binary 'influxevents title="my-title",tags="tag1,tag2,tag2",text="all tags removed from grafana"'
```
check them in influx
```
 > select title,tags,text from influxevents
name: influxevents
time                title    tags           text
----                -----    ----           ----
1537459686002868657 my-title tag1,tag2,tag3 no problem
1537459686037818535 my-title tag1,tag2,tag2 all tags removed from grafana
```
show them in grafana
![screenshot_20180920_181130](https://user-images.githubusercontent.com/30314040/45831926-d66e4280-bd00-11e8-88ad-21eb000005d2.png)
![screenshot_20180920_181159](https://user-images.githubusercontent.com/30314040/45831928-d66e4280-bd00-11e8-9841-f80f51a8455e.png)
![screenshot_20180920_181215](https://user-images.githubusercontent.com/30314040/45831929-d66e4280-bd00-11e8-85c3-2951f33ffcaf.png)

**Comment by torkelo** [comment]
Can you open chrome dev tools and find the request to influxdb and show the response? Can you open chrome dev tools console and looks for recent js errors?

**Comment by rdxmb** [comment]
http://10.139.0.120:30003/api/datasources/proxy/1/query?db=monitoring&q=SELECT%20title%2Ctags%2Ctext%20from%20influxevents%20where%20time%20%3E%3D%201537459685833ms%20and%20time%20%3C%3D%201537459686181ms&epoch=ms

response:

```
{"results":[{"statement_id":0,"series":[{"name":"influxevents","columns":["time","title","tags","text"],"values":[[1537459686002,"my-title","tag1,tag2,tag3","no problem"],[1537459686037,"my-title","tag1,tag2,tag2","all tags removed from grafana"]]}]}]}
```
---

```
angular.js:14700 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tags, Duplicate key: string:tag2, Duplicate value: tag2
http://errors.angularjs.org/1.6.6/ngRepeat/dupes?p0=tag%20in%20tags&p1=string%3Atag2&p2=tag2
    at angular.js:116
    at angular.js:31449
    at r (angular.js:18121)
    at h.$digest (angular.js:18261)
    at jquery.flot.events.js:88
    at Object.a [as invoke] (angular.js:5040)
    at a (jquery.flot.events.js:79)
    at HTMLDivElement.w (jquery.flot.events.js:428)
    at HTMLDivElement.handle (jquery.js:5536)
    at HTMLDivElement.dispatch (jquery.js:5183)
```
