### ISSUE TITLE
Access to current time filter values for absolute panel links

### ISSUE THREAD

**Issue by ohTHATaaronbrown** [grafana/grafana#1336]
I'd like to access the values of the current time picker selection as templates when crafting a panel link.

Specifically, I'm trying to craft a url to send to Kibana's scriptable dashboard feature.

In the parameters box for an absolute URL I'd like something along the lines of: 
```
param1=$template1&param2=$template2&from=$from&to=$to
```

where **$from** and **$to** pull the time from the current time picker.  Grafana sort of does this automagically now, but **from=** is in a **now-period** format that Kibana doesn't understand.  I really need just the period.

Doable?

**Comment by ohTHATaaronbrown** [comment]
I could always, I suppose, rewrite the kibana scripted dashboard to recognize the format that grafana auto-magically inserts, but I'd still like access to the values in the picker in case I need to send to some other ancillary system that doesn't understand **from** and **to** :)

**Comment by ohTHATaaronbrown** [comment]
Wow, not even an explanation of why, just closed with wontfix, eh?

Color me impressed.

**Comment by torkelo** [comment]
@ohTHATaaronbrown sorry, forgot to link to this issue, https://github.com/grafana/grafana/issues/1909 

Not exactly the same but related.

**Comment by torkelo** [comment]
@ohTHATaaronbrown and it was not like this had received a flurry of +1 and comments :)

**Comment by ohTHATaaronbrown** [comment]
Fair enough :)

And, it looks like the other gets me what i want anyway.  Thank you :)
