### ISSUE TITLE
macaron session/postgres panic when DNS lookup fails

### ISSUE THREAD

**Issue by dwo** [grafana/grafana#13361]
### What Grafana version are you using?
4.6.3
### What OS are you running grafana on?
CentOS / Amazon Elastic Container Service
### What did you do?
Normal page loads
### What was the expected result?
A successful page load, with an error message about the database being unreachable.
### What happened instead?
5xx errors: Panic logged, increased CPU usage from Grafana process, hanging / exiting
 
### Details

We run Grafana in Amazon Web Services, and hit a problem with DNS queries to Amazon hostnames getting rate limited and dropped for a period of time. 

Grafana failed to load while this was happening with this in the logs, and processes were hanging and eventually exiting. 

```
t=2018-09-19T12:45:15+0000 lvl=eror msg="Request error" error="session/postgres: error checking existence: dial tcp: lookup grafana.abcdefghijk.region.rds.amazonaws.com on 127.0.0.1:53: dial udp 127.0.0.1:53: i/o timeout" stack="/usr/local/go/src/runtime/panic.go:491 (0x431e62)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/postgres/postgres.go:148 (0xb495c4)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/session.go:257 (0x832d21)
/go/src/github.com/grafana/grafana/pkg/middleware/session.go:117 (0xb9490f)
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:99 (0xb8fd6d)
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:57 (0xb969d6)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x7f19c0)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7d4863)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7d459a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)
/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb979e0)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x7f19c0)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7d4863)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7d459a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)
/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xb95571)
/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)
/usr/local/go/src/reflect/value.go:434 (0x4bf934)
/usr/local/go/src/reflect/value.go:302 (0x4bef13)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x803412)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:296 (0x7fd98b)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7f6387)
/usr/local/go/src/net/http/server.go:2619 (0x692de3)
/usr/local/go/src/net/http/server.go:1801 (0x68f09c)
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x4638c0)
```
Notes:
* Our Relational Database Service (RDS) hostname has been anonymized.
* The DNS query is to `127.0.01:53` because we run `dnsmasq` alongside Grafana to configure the use of our own DNS servers for internal hostnames.

Could Grafana catch this problem and report it in the UI rather than panicking? This is probably reproduce-able by spinning up a Grafana process and then blocking DNS lookups for a while with `iptables` or similar.

I think we may need to raise this with the Macaron project too if this error isn't recoverable.
I'm not sure how often Macaron's `session/postgres` actually needs to resolve the hostname (no caching?) and why it panics like this when a lookup fails.

**Comment by marefr** [comment]
Thanks for the thorough report. We have plans in removing the need of a session storage (#7741) so will close this in favor of that. 

If possible, I would suggest you to try a newer version of Grafana since we've updated Macaron and other 3rd party libraries since v4.6.3.

**Comment by dwo** [comment]
Given the Macaron session code [hasn't changed since 2015](https://github.com/go-macaron/session/blob/cfeedcfc391ab39e0cb7313f89bf62e6d74a44e9/postgres/postgres.go) we will probably need to wait for #7741 😄
