### ISSUE TITLE
Explore mode slate editor theme

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13375]
Not sure how easy this is to change. The current ACE editor theme we have created is a lot more vibrant and easier to read than the current dark theme for slate used in explore:

![image](https://user-images.githubusercontent.com/10999/45863523-cf821700-bd76-11e8-91b4-f17df0edecac.png)

![image](https://user-images.githubusercontent.com/10999/45863498-bb3e1a00-bd76-11e8-825c-dcc9bb605d47.png)

Is it possible to align these? 

The dark theme is defined here: 
https://github.com/grafana/grafana/blob/master/public/app/core/components/code_editor/theme-grafana-dark.js

**Comment by davkal** [comment]
Very possible to align these.
The current slate colors are based on the primary colors of the grafana styles, hence they should be more pleasant overall. It seems like the Ace styles are simply very vibrant colors for dark terminals.

I'm happy to go with the ACE colors if it helps readability.
A "problem" with the ACE styles is that identifiers, like the metric name, are not colored AFAIK.

A fix should address both of these issues.
