### ISSUE TITLE
Alerts - Template variables are not supported in alert queries

### ISSUE THREAD

**Issue by ondrejFuchs** [grafana/grafana#13376]
Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
Influxdb
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Error: Template variables are not supported in alert queries
![snimek obrazovky porizeny 2018-09-21 08-37-32](https://user-images.githubusercontent.com/34134418/45864276-cba3c400-bd79-11e8-98c1-4d04c6a4b122.png)
![snimek obrazovky porizeny 2018-09-21 08-38-19](https://user-images.githubusercontent.com/34134418/45864284-d0687800-bd79-11e8-8e1b-53957e268159.png)

And varriable looks like:
SHOW TAG VALUES FROM "cpu" WITH KEY = "host"

I read that I can't use template variables for alerting and I shoud replace it with regex. Any idea, how can I do it?

Thanks for your response.

**Comment by peterholmberg** [comment]
Please use our [community site ](https://community.grafana.com) for question like this. Issues are for bugs and/or feature requests.

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/6557
