### ISSUE TITLE
How can I access grafana via url

### ISSUE THREAD

**Issue by qinzheng** [grafana/grafana#13377]
Please include this information:
Grafana version ：4.2
OS ：docker
I created some orgs in grafana and create their api_keys   now I want access dashboard via url    Before this  I used nginx and put api_key in nginx  so I can access  but  it's too   trouble       I read the code and  find  the api_key  is fetched from request headers  and  is not easy to modified     so  is there any way  to access dashboard via url

**Comment by peterholmberg** [comment]
Please use our [community site](http://community.grafana.com) for questions such as this.

**Comment by tesfayeaguma** [comment]
How can I access grafana via url #13377
