### ISSUE TITLE
[Back button] The back to dashboard button is not intuitive

### ISSUE THREAD

**Issue by tw3rp** [grafana/grafana#13371]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Docker Container
### What did you do?
Try to click the Back button 
### What was the expected result?
Was not intuitive to find the back button
### What happened instead?
wasted several minutes

**Comment by torkelo** [comment]
There is a close in the edit tab section (x) and a big blue back button in the toolbar. But I understand your pain, your not alone, we could make it more visible. (btw, esc key and browser back button also works)

**Comment by tw3rp** [comment]
thanks for the quick response. I'll try to work with esc key.
