### ISSUE TITLE
Graphs seem to have their drawn values offset to the right

### ISSUE THREAD

**Issue by JeremyMorton** [grafana/grafana#1337]
This is more obvious when I have a series "fill below to" another series, as the fill extends beyond the right of the graph, but both lines and fills don't draw all the way to the left edge of the graph, either:

![offsetgraph](https://cloud.githubusercontent.com/assets/10471528/5731779/7d8a086e-9b3c-11e4-9cec-aa242560969f.png)

Hovering over the area to the right of the graph where the fill draws gives a tooltip.

The rightmost tooltip values do not match the "current" values in the legend, but those "current" values come onto the graph after a couple of new points get tacked onto the right.

This particular graph has "group by time" >10s, and our data comes from InfluxDB.

**Comment by torkelo** [comment]
strange, could be that the time on your local machine and your influxdb server is not fully in sync.

**Comment by JeremyMorton** [comment]
The source of the InfluxDB events writes their own timestamps instead of letting InfluxDB auto timestamp the events as they come in. I will check the clocks of all the machines involved to see if one is a couple of minutes ahead.
