### ISSUE TITLE
Tooltip with rounded values

### ISSUE THREAD

**Issue by aleholman** [grafana/grafana#1338]
Hi,
Some of my time series have double values. The graph shows decimals ok when I see it on fullscreen mode. When the graph is small, values are rounded and I understand that it happens because of the resolution. But the tooltip is showing rounded values too. 
Is there anyway to change this behaviour? I would like to see the double values in the tooltip even if the graph cannot have the resolution to show the decimals.
Thanks!

**Comment by torkelo** [comment]
This is related to this issue https://github.com/grafana/grafana/issues/1197 

Basically the smart decimal precision for the legend and the tooltip is based on the graph min/max (then a bunch of complex math to figure out the optimal decimals). Will need to seperate these and figure out optimal decimals for the legend & tooltip separately but could be cpu intensive not sure.
