### ISSUE TITLE
Can't run from Master

### ISSUE THREAD

**Issue by edum18** [grafana/grafana#13382]
### What Grafana version are you using?
Master
### What datasource are you using?
None, didn't run grafana yet.
### What OS are you running grafana on?
Windows 10
### What did you do?
Built backend and frontend.
finally, yarn start
### What was the expected result?
Grafana running on localhost:xxxx.
### What happened instead?
Shows some warnings on console and doesn't run on browser.
on localhost:3000 shows nothing.
on localhost:3333 shows a blank page with "Error occured while trying to proxy to: localhost:3333/".
 
I can't seem to run grafana from master.
Output after doing "yarn start":
https://pastebin.com/tjnm2c4a

**Comment by torkelo** [comment]
make sure you built and started the grafana-server backend, http://docs.grafana.org/project/building_from_source/#developing-grafana

**Comment by marefr** [comment]
Since you're on Windows you may have security issues using port 3000 and similar in that range. In our [installations instructions for Windows](http://docs.grafana.org/installation/windows/#configure) we recommend to use port 8080 instead. Also, instead of `yarn start` you can also use `yarn watch` to skip using webpack development server running on port 3333

**Comment by edum18** [comment]
> Since you're on Windows you may have security issues using port 3000 and similar in that range. In our [installations instructions for Windows](http://docs.grafana.org/installation/windows/#configure) we recommend to use port 8080 instead. Also, instead of `yarn start` you can also use `yarn watch` to skip using webpack development server running on port 3333

I did that, created custom.ini with port 8080 and used `yarn watch` but the output and issue is the same. I probably have to do what @torkelo said but I can't get bra command working.

**Comment by edum18** [comment]
> make sure you built and started the grafana-server backend, http://docs.grafana.org/project/building_from_source/#developing-grafana

I can't get bra command working. "bra: command not found."

**Comment by marefr** [comment]
bra is not supported on Windows and therefore reload of Grafana when backend code changes is not supported. However, instead you can run
```
go run build.go setup
go run build.go build
```

And then you should be able to start grafana-server.exe under bin directory, possibly in yet another directory called windows-x64 or similar.

**Comment by edum18** [comment]
> bra is not supported on Windows and therefore reload of Grafana when backend code changes is not supported. However, instead you can run
> 
> ```
> go run build.go setup
> go run build.go build
> ```
> And then you should be able to start grafana-server.exe under bin directory, possibly in yet another directory called windows-x64 or similar.

Starting grafana-server.exe opens and instantly closes a cmd window and it's still not running. I'm missing something.

**Comment by marefr** [comment]
Please open a command prompt and start the grafana-server.exe from there. Then you should be able to see what the problem is based on log output.

**Comment by torkelo** [comment]
you start grafana server by executing it from the command line from the project root dir as described in the docs. 

http://docs.grafana.org/project/building_from_source/#running-grafana-locally

**Comment by edum18** [comment]
Finally I got it working, thank you @marefr @torkelo !

**Comment by Saur123** [comment]
> Finally I got it working, thank you @marefr @torkelo !

How did you get it to work?? 
I am stuck in a situation where yarn watch doesnt detect changes

**Comment by edum18** [comment]
@saur123 are you able to just run grafana? The changes you made were on a .go file?  Yarn watch only detects changes on frontend

**Comment by Soyeb7** [comment]
I got it to work mate. I was running yarn start in the wrong directory lol.

**Comment by night1008** [comment]
How to detect front file change?

In master branch(8.0.0), I have run `yarn start` and `./bin/grafana-server` locally,
when I edit front file, only restart `./bin/grafana-server`, I can see the change content,
how can I see the change constantly?
