### ISSUE TITLE
Absolute time range for Singlestat panel

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#13384]
Hi,

Could you add absolute time range override for Singlestat panel? So it will be possible to "restart" panel for example at midnight everyday.

**Comment by torkelo** [comment]
yes that would be possible (to implement).  Closing this as we already have a feature request for absolute panel time overrides

**Comment by szerwi** [comment]
@torkelo will it be add in the near future or do I need to wait a few months? :D

**Comment by szerwi** [comment]
Ok. I would like to see it in Grafana so I hope you will add it as soon as possible :)

**Comment by abhijithbrao** [comment]
Any update? In previous version of Singlestat, there was option of time range. However, I am not able to see time range option in Singlestat for Grafana 6.3.3.
