### ISSUE TITLE
Panel menu fold-out submenu unreachable at right edge

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#13396]
The submenu in the panel menu is inaccessible when the panel is at the right edge of the grid:

![image](https://user-images.githubusercontent.com/345210/45927250-92618480-bf30-11e8-9976-951ae4bae66a.png)

Now, there are 4 items in the top-level menu 

```
View
Edit
Share
More
    → Duplicate
    → Copy
    → Panel JSON
---
Remove
```

I find the grouping not so logical, and I don't find the functions in the submenu less important. When building dashboards I use those functions all the time, while i never use "Share".

How about a flat menu?
```
View
Edit
Copy
Duplicate
Remove
Share
Panel JSON
```

(Using Grafana 5.3 beta)

**Comment by torkelo** [comment]
thanks for the feedback, will take it into consideration. having a flat menu might solve first issue. As a temporary workaround you can use keyboard to scroll right to get the submenu to show.
