### ISSUE TITLE
Feature request :  hide selected metric series?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1339]
I have made some dashboards with averaged response time, but we have a incident in the  de s1 / s8 apache , so it is showing very big response time. As this graph does autoscale it doesn't let me see the other apache  response times.

![image](https://cloud.githubusercontent.com/assets/5883405/5739407/898e28d0-9bf9-11e4-90e5-6eeb3c1cc30f.png)

How can I hide s1 and s8 series from the dashboard view ?

**Comment by torkelo** [comment]
shift+left click the series name hides it from the graph

**Comment by toni-moreno** [comment]
OK!!! it works!!

Could be interesting a "?" icon with a tooltip anywhere on the mainview with this basic shortcuts referenced.

**Comment by torkelo** [comment]
yes, been thinking about that. You can open a shortcut info dialog by hitting "?" on your keyboard. but have not found space for a ? icon, do not want to clutter the top menu, already so many icons, but will find a way

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/5742126/12e5ab06-9c10-11e4-8e48-d396e49f6870.png)

**Comment by torkelo** [comment]
hm.. this shortcut is not on the list :(

**Comment by toni-moreno** [comment]
The Keyboard shortcut "?" is not working to me on grafana 1.9.0 and neither on play.grafana.org

What I'm doing wrong ?

**Comment by torkelo** [comment]
Not sure, left or right shift+(+? key) should work. Works in chrome on linux and firefox. What os and browser did you test with?

**Comment by toni-moreno** [comment]
chrome and firefox on windows7 and shift + ? is not working to me...

**Comment by toni-moreno** [comment]
@torkelo 

Could I open an Issue for that problem ?

**Comment by torkelo** [comment]
Its, strange, it works for me in chrome on windows, and safari/chrome on mac osx

**Comment by torkelo** [comment]
Does shift+? work for you on github.com ? (github has the same feature)

**Comment by toni-moreno** [comment]
yes!!

![image](https://cloud.githubusercontent.com/assets/5883405/5761944/2eff1cda-9cdf-11e4-9f33-799aef2138d3.png)

**Comment by torkelo** [comment]
Please debug this yourself as I fail to replicate it on any os/browser
https://github.com/grafana/grafana/blob/master/src/app/features/dashboard/keybindings.js#L25
https://github.com/grafana/grafana/blob/master/src/app/services/keyboardManager.js

**Comment by toni-moreno** [comment]
Hi @torkelo 

this is the event generated when I press my "?" ( spanish keyboard).

![image](https://cloud.githubusercontent.com/assets/5883405/5772207/317f2ed6-9d4e-11e4-94d6-7dfc6a46bb7b.png)

**Comment by torkelo** [comment]
That is only the shift key, (keyCode: 16 = shift),
http://www.asquare.net/javascript/tests/KeyCode.html

**Comment by toni-moreno** [comment]
@torkelo , I have seen that function inside keyboardManager.bind('shift+?', function()); is never called but working good if i change 'shift+?' by 'shift+j' by example. The problem is  '?' detection.

The javascript eventkeycode for me is :

![image](https://cloud.githubusercontent.com/assets/5883405/5787976/dbfc04b0-9e1b-11e4-8470-8197ae718137.png)

what can I do to help you to fix that?

**Comment by torkelo** [comment]
Can you test this lib? https://github.com/dmauro/Keypress/ 
But looked through the code it looks like it does the same shift key mapping as I do.

**Comment by toni-moreno** [comment]
when I press my  Spanish keyboard "?"  at the demo page in:

http://dmauro.github.io/Keypress/

it show as pressed the  "}"  key at right of "P" letter.

does this library accept international keyboard layouts?

**Comment by toni-moreno** [comment]
I finally got it working by pressing "shift+{" on my keyboard ... 

![image](https://cloud.githubusercontent.com/assets/5883405/5788590/9fa0f8e4-9e3f-11e4-8fd9-d630567161f7.png)

**Comment by torkelo** [comment]
I tried searching for how to handle different keyboard layouts when dealing with keyCodes, could not find anything :(

**Comment by toni-moreno** [comment]
this project had the same problem and seems they fixed by changing the way to get character code better than keycodes by handling "keypress" events. But I haven't done any test yet

https://github.com/ccampbell/mousetrap/issues/2#issue-5450348

the main web site is:

http://craig.is/killing/mice

**Comment by toni-moreno** [comment]
I've tested it with this demo,

http://www.javascriptoo.com/Mousetrap

I've changed letters w,a,s,d by ?,=,*,- and it detected all character ok  !!!.

**Comment by toni-moreno** [comment]
Hi @torkel you could migrate from keyboardManager to mousetrap library as a workarround for this bug.

If done I will be available to test it.

**Comment by torkelo** [comment]
No, just so swamped getting grafana 2.0 (with backend) ready for preview release

**Comment by toni-moreno** [comment]
ok I will wait !!

**Comment by skfd** [comment]
I think it has stopped working again in newer versions of Mousetrap. Better check again.
