### ISSUE TITLE
More time zone options requested

### ISSUE THREAD

**Issue by Tobias007** [grafana/grafana#13395]
Read before posting: 

Is it possible to implement flexible time zone settings. (instead of Default, UTC, local time the complete time zones (UTC+1,+2,+3,+4 ...) etc.).

Example:
I'm recording data in Italy (UTC+2). Grafana runs in Italy.
When I watch the values in Singapore I have no posibilty to see the time in local Italian timezone.

When I choose local .. all is converted to Singapore time.
When I choose UTC .. all is in UTC time.
Expected time zone: UTC+2..

Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
INFLUXDB
### What OS are you running grafana on?
Ubuntu 14.04

**Comment by torkelo** [comment]
closing this as we already have a feature request for this
