### ISSUE TITLE
2nd series label not showing

### ISSUE THREAD

**Issue by BuxtonCalvin** [grafana/grafana#13390]
![image](https://user-images.githubusercontent.com/23129738/45910697-28c26880-bdc0-11e8-8e4d-fbfd1ed46a03.png)

My second series label values are not showing.  As well, is there a way to have the second series (temperature per period) show in equal scale to the primary series data (watts per period).

Grafana v5.3.0-beta1 (e05033a)
Graphite DB
Linux armbian64  Ubuntu 18.04.1 LTS

**Comment by torkelo** [comment]
Click on the colored line icon in the legend (left of series name) and it will open color picker and there you can assign the series to the right y axis. 

Please ask questions on the community site https://community.grafana.com
