### ISSUE TITLE
HTTP API intermittent errors

### ISSUE THREAD

**Issue by dan0kun** [grafana/grafana#13406]
Running the standard Grafana Docker image locally on Windows, and using the HTTP API with Grafana 5.2.4, and I have a node script to load teams and folders (and remove them) into Grafana.  The script runs very quickly, but I get only about 30% success rate on the API calls.  I have to re-run the script several times to get the remaining elements loaded or removed.  The error responses I get from Grafana seem to vary randomly.

Create Team:  
Failed to create team
Authentication error

Create Folder:
Folder not found
Basic auth failed
Authentication error
Invalid username or password

The username/password works, as it is the default (admin/admin), and 30% of the calls work properly. 
 I'm assuming the HTTP API just can't keep up with the requests, as they seem to fly by very quickly, but I was wondering if you had any guidelines on how much time Grafana needs to respond to each API request.

**Comment by torkelo** [comment]
Very strange, we have no other reports and can't replicate any issues like this. Is it only happening on your local docker setup?

**Comment by dan0kun** [comment]
That's how I fixed it.  Made subsequent requests wait on the previous request.

**Comment by dan0kun** [comment]
On a side note, can you direct me to info about running a script at user login?  I can't seem to find info about that.

**Comment by torkelo** [comment]
There is no such feature to execute script at login
