### ISSUE TITLE
Creating unique ids for notifications?

### ISSUE THREAD

**Issue by Nessaek** [grafana/grafana#13405]
Hi there,
I have a json file used to create notifications like this:

```
{
  "id": 49,
  "name": "slacks",
  "type": "slack",
  "settings": {
    "url": "{{slack_webhook|default('hooke')}}",
    "recipient": "{{channel|default('#test')}}",
    "mention": "@channel"
  }
}
```

I want to be able to identify this notification through the id.   However every time I create the dashboards/notifications, the id changes.  Is it possible to have the id remain the same?

What Grafana version are you using?
4.6.0, 4.6.4, 5.2.2, 5.2.3

What datasource are you using?
Custom

What OS are you running grafana on?
Mac OS

**Comment by marefr** [comment]
Please use the PUT endpoint for update, see http://docs.grafana.org/http_api/alerting/#update-alert-notification.

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
