### ISSUE TITLE
Dashboard for Cloud Instance

### ISSUE THREAD

**Issue by aather** [grafana/grafana#1340]
I have been playing with Grafana, Graphite and Elasticsearch (ES) lately. We run hundreds, even thousands, of instances in Amazon Cloud and have number of services (micro-service architecture) that auto-scales depending on the load. Instances are frequently recycled and replaced. Graphite is mainly used to collect high resolution (1-5 second interval) performance metrics from subset of server farm, on as needed basis, whenever performance issue is reported. We already have centralized monitoring system that collects application/system metrics on a per minute resolution. We save graphite metrics per instance and then use it to perform instance level analysis. 

I have created a template dashboard using grafana for some of the critical services and saved it on ES. Whenever, any instance need analysis, I download the service template, use "sed" utility to substitute the new instance id and then upload it to the ES via grafana. Although it works, I want to automate it so that internal teams can able to use the dashboard to analyze performance of their service. 

I am thinking to create a web page (form) where I can ask user the instance id and the service name.  Use the instance id and service name to create the dashboard from the template; populate instance metrics and save it on the ES.. all done in the background. User browser is then directed to the URL of the dashboard. 

Rather than re-inventing the wheels, I like to know if somebody has already done this and willing to share ideas.

Thanks,
Amer.

**Comment by viljemskornik** [comment]
I have a similar case that I have one dashboard for production, testing, qa, dev's own stacks. I just use builtin templating engine. Create my dashboard with templating enabled and then users can just use the drop down or via URL directly. Works great for me.

http://grafana.org/docs/features/templated_dashboards/

http://grafana.org/docs/features/templated_dashboards/

**Comment by aather** [comment]
It works like a champ! Thanks again. I love grafana!
