### ISSUE TITLE
[Bug] Dropdown Links Appear Behind Panels

### ISSUE THREAD

**Issue by Chris-Hicks** [grafana/grafana#13409]
Read before posting: 

Please include this information:
### What Grafana version are you using?
Grafana v5.2.2 but it can replicate on Grafana Play v5.3.0-beta1 
### What datasource are you using?
All
### What OS are you running grafana on?
Linux
### What did you do?
- Select a panel title of a panel which would require a drop down link to overlay over the top.
- Select the drop down
- Drop down displays behind the panel.
![grafana drop down link issue](https://user-images.githubusercontent.com/29731108/46008549-fe6cf580-c0b4-11e8-96af-9d1a9f705cf8.gif)

### What was the expected result?
- Drop down to appear in front of the panel
### What happened instead?
- Drop down appeared behind the panel

**Comment by torkelo** [comment]
think the class dropdown-menu-open is not removed when clicking outside the panel menu. this class is special hack to workaround z-index issues with the grid panels. 

Suggest adding clearing of this class in the app body click handler:

https://github.com/grafana/grafana/blob/master/public/app/core/components/grafana_app.ts#L242
