### ISSUE TITLE
Prometheus "Timestamp" annotation takes 100% of CPU

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#13414]
When I enable the new timestamps annotations in prometheus, my browser is unresponsive because it takes a huge amount of CPU. That feature does not seem to be usable.

Prometheus query used:

topk(10,process_start_time_seconds)

**Comment by torkelo** [comment]
what does your query return?

**Comment by roidelapluie** [comment]
Apparently too much data. This is because the default dashboard in grafana shows 6h by default.

Mitigation: I use 
```
topk(10,1000*process_start_time_seconds and (time() - process_start_time_seconds < 600))
```

as query and it looks better.

**Comment by torkelo** [comment]
You also have the step option to reduce number of data points

**Comment by roidelapluie** [comment]
I will put that in prod anddisable annotations by default.
