### ISSUE TITLE
imguploader: ECS credentials not being used when uploading to S3

### ISSUE THREAD

**Issue by aidan-** [grafana/grafana#13423]
### What Grafana version are you using?
5.2.4
### What datasource are you using?
N/A
### What OS are you running grafana on?
Linux
### What did you do?
Running Grafana in a container on AWS ECS (Elastic Container Service) with the required IAM permissions to upload static images to a configured S3 bucket.  The settings `external_image_storage.s3.access_key` and `external_image_storage.s3.secret_key` are not configured - which should default to using the environmental (service IAM Role) credentials.

Configured a Notification Channel using Slack as a destination with `Include Image` ticked and an alert that is going to trigger.

### What was the expected result?
Alert is sent to Slack with an attached image of the visualization that triggered.
### What happened instead?
Grafana failed to upload the visualization image to S3 with a relevant error log:
```
lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: REDACTED, host id:
```

--------
It looks like the `imguploader/s3uploader` doesn't try to use credentials provided by using the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable (if set) so it is a simple fix to add this additional 'credential provider' to the authentication chain.

I've got a PR which I will submit shortly for review.

**Comment by marefr** [comment]
Fixed by #13424
