### ISSUE TITLE
TeamPicker cannot select team if not included in initial search

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13425]
* Lower the search query limit, https://github.com/grafana/grafana/blob/master/public/app/core/components/Picker/TeamPicker.tsx#L42 
* Search for team, try to select it
* Team is not selected (unless part of the initial list)

**Comment by jschill** [comment]
We should probably bump the react-select component version to 2.x. I've tried to do it and.. eh.. they have changed quite a bit so it will take some time to have it in place. Bumping the version will affect all pickers (Team, User, Description).
