### ISSUE TITLE
Problem setting up Grafana with opentsdb and elasticsearch

### ISSUE THREAD

**Issue by energie786** [grafana/grafana#1343]
When I add a metric from Grafana, it doesn't autofill and gives me the following error:

Error: 
XMLHttpRequest cannot load http://10.10.15.5:4242/api/suggest?q=&type=metrics. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.10.15.5:8081' is therefore not allowed access.
2(index):1 XMLHttpRequest cannot load http://10.10.15.5:4242/api/suggest?q=mymetric.stock&type=metrics. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.10.15.5:8081' is therefore not allowed access.
app.496fdc2e.js:9 OPTIONS http://10.10.15.5:4242/api/query 
(index):1 XMLHttpRequest cannot load http://10.10.15.5:4242/api/query. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.10.15.5:8081' is therefore not allowed access. The response had HTTP status code 405.
app.496fdc2e.js:9 OPTIONS http://10.10.15.5:4242/api/query 405 (Method Not Allowed)
(index):1 XMLHttpRequest cannot load http://10.10.15.5:4242/api/query. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.10.15.5:8081' is therefore not allowed access. The response had HTTP status code 405.

Is the problem on Elasticsearch or apache?

ES config I added:
 http.cors.enabled: true
 http.cors.allow-origin: "*"

in httpd config:
<VirtualHost *:8081>
  DocumentRoot /var/www
  Header set Access-Control-Allow-Origin "*"
  <Location />
    Order deny,allow
    Deny from all
    Allow from all
  </Location>
</VirtualHost>

I also added the following to .htaccess
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "GET, OPTIONS"
Header set Access-Control-Allow-Headers "origin, authorization, accept"
~                                                                                

But it still upon refresh post restart of ES and httpd gives me the cors error

Any help will be greatly appreciated.

Thank you
Sal

**Comment by energie786** [comment]
After adding inside tsdb config, tsd.http.request.cors_domains = *, the metric names show up in the Grafana metrics field. However I am now seeing this one error
14(index):1 XMLHttpRequest cannot load http://10.10.15.5:4242/api/query. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

**Comment by nucleusv** [comment]
http://opentsdb.net/docs/build/html/user_guide/configuration.html
tsd.http.request.cors_headers

you need to set up such headers:

Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type'
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000

**Comment by torkelo** [comment]
http://grafana.org/docs/features/opentsdb/
