### ISSUE TITLE
Show access denied page when accessing page requiring higher role 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13431]
If you manually specify page you do not have access to the page will still load but show either an api permission error loading notice or sometimes break. 

Example: load org users page as an org editor user. 

Should show permission denied instead of broken page.

**Comment by bergquist** [comment]
https://stackoverflow.com/questions/28582830/access-denied-403-or-404

**Comment by 6d6178** [comment]
I just want to bring attention to this issue again, as we encountered it by accident today. We are planning to allow anonymous users in a org and those users are not supposed to see which users are attached/have logged in to the org.
