### ISSUE TITLE
Scrolling in edit-mode is almost entirely non-functional on mobile

### ISSUE THREAD

**Issue by hamid-elaosta** [grafana/grafana#13434]
### What Grafana version are you using?
5.2.2 and 5.2.4
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Arch Linux x86_64
### What did you do?
Create a dashboard with some graphs and single stats, open on mobile, edit one of them, try to scroll up and down the page
### What was the expected result?
The page should scroll to touch
### What happened instead?
Pages do not scroll at all unless touched on the graph itself. You can get down a long page by flinging but then it is impossible to get back to the top once no graphs are on the page to touch/scroll with.
It seems any point vertically aligned with the graph will allow you to scroll by touch, but anywhere below in the edit/query area is impossible to scroll.

**Comment by torkelo** [comment]
Editing panels is not supported on mobile right now. Mobile use cases has been pretty limited thus far as most use big computer or TV monitors to view & build dashboards. We do however want viewing dashboards to work well on mobile.
