### ISSUE TITLE
Variable does not update when changed from a table link 

### ISSUE THREAD

**Issue by henriqueschmidt** [grafana/grafana#13433]
Hello people, I have a problem, I created a dashboard of type table and I put a link in the column. And when I configure for true in "open new tab" it works perfectly, but, when I configure for false, it update the URL, but not the variable with the data.
![peek 2018-09-26 17-40](https://user-images.githubusercontent.com/30303963/46108071-82a5a280-c1b3-11e8-968e-0cdb9b85d93c.gif)

**Comment by tdjac0bs** [comment]
What happens if you hit F5 after clicking on the link?

**Comment by henriqueschmidt** [comment]
if I refresh the page, the data is updated correctly

**Comment by torkelo** [comment]
what is your table link Url option set to? I cannot see the full thing

**Comment by sergey-sergey** [comment]
In one thread I saw one workaround which works like a charm.
In URL replace name of the page, it opens the same dashboard but forces browser to reload it with new parameters.
For example, change
https://grafana/d/FSGfdgsf/**test-dashboard**/...
to
https://grafana/d/FSGfdgsf/**blah-blah**/...

**Comment by henriqueschmidt** [comment]
@sergey-sergey the workaround works correctly, but it reload all page,there is a form to reload only the dashboard?

> what is your table link Url option set to? I cannot see the full thing

**Comment by henriqueschmidt** [comment]
> In one thread I saw one workaround which works like a charm.
> In URL replace name of the page, it opens the same dashboard but forces browser to reload it with new parameters.
> For example, change
> https://grafana/d/FSGfdgsf/**test-dashboard**/...
> to
> https://grafana/d/FSGfdgsf/**blah-blah**/...

@sergey-sergey the workaround works correctly, but it reload all page,there is a form to reload only the dashboard?

**Comment by henriqueschmidt** [comment]
> what is your table link Url option set to? I cannot see the full thing

this is the link:
`/d/-kjMY5omk/blah-blah?orgId=1&from=${__cell_2}&to=${__cell_3}&var-tipo=All&var-grafico=All&var-total=${__cell_0}&panelId=24&fullscreen`

**Comment by torkelo** [comment]
Setting variables that exist on the same dashboard is currently not supported, there is another issue for that. It’s something we want to fix. On mobile right now and don’t have the other issue at hand.

**Comment by dylanmckendry** [comment]
I managed to use JavaScript to update the variable and refresh without the full browser reload. Instead of adding a URL I added the below JavaScript. The JavaScript was just a quick hack to see if it worked, I am sure there are better ways to update the variable. The JavaScript only works for a single dropdown, it would have to be updated if there were multiple dropdowns.

`javascript:$('a.variable-value-link').trigger('click'); $('span:contains(${__cell:raw})').closest('a').trigger('click');
`

**Comment by carlosoliverosmonti** [comment]
maybe this helps

javascript:window.location.href='/d/qXHtipxZz/nodos-puertos-usados-y-libres?var-no_sitio=${__cell_1}&var-no_destino=${__cell_2}&orgId=1&from=$__from&to=$__to'
![Captura de pantalla -2020-01-21 11-57-30](https://user-images.githubusercontent.com/29068197/72825515-29357280-3c45-11ea-911f-5e06fc2e7cc7.png)
