### ISSUE TITLE
Evaluate using "floating labels" for form inputs.

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#13447]
It might be a good idea to see if we should add the form input labels inside the actual element.

Example:
https://material.io/design/components/text-fields.html
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/forms/
https://css-tricks.com/float-labels-css/

This could potentially help us improve our form UX. It might also make it worse since we (probably) have to make the inputs bigger in height and we limit ourselves in label text length.

**Comment by zoltanbedi** [comment]
@jessover9000 or @sarlinska is this something you still looking for?

**Comment by jessover9000** [comment]
We updated the form styles earlier this year and didn't go in this direction, so I think we can close this issue.
