### ISSUE TITLE
Alias patterns OpenTSDB, reference tag values

### ISSUE THREAD

**Issue by kylemallory** [grafana/grafana#1344]
Allow the use of variables in aliases, etc that are expanded from tag values.  For example, it would be great to be able to reference "$host" within a series alias to give the alias/legend title the name of the host for that series.  This would be particularly useful when requesting multiple series in a single query, such as "system.cpu.load{host=*}".  Currently, series aliases are defaulted the matching metric/tag pattern (system.cpu.load{host=foo.domain.tld}.

**Comment by trixpan** [comment]
Keen to see this as well.

**Comment by kylemallory** [comment]
Submitted pull-request for this feature.  "Restricted suggestions" #1433

**Comment by amuraru** [comment]
@kylemallory @torkelo Why not using the "Series specific overrides" mech to override/set the dynamic series names. Right now the legend alias and color cannot be overriden from there but this would be the most flexible way IMO.

**Comment by torkelo** [comment]
@amuraru how does that solve using OpenTSDB tag values in alias pattern? This has to be done in the opentsdb data source when handling the response from OpenTSDB, not something to do with series styling (something that happens much later), this is about how OpenTSDB metric results should turn into good alias names using alias patterns that can reference tag values.

**Comment by amuraru** [comment]
@torkelo - hmm, not sure I understand why this would not be possible.
For a OpenTSDB metric, say, `"system.cpu.load{host=*}"` the legend is rendered to include multiple series using actual `host` values in opentsdb. Wouldn't be possible then  to use the overwrite rules and give individual series a friendly name?

**Comment by kylemallory** [comment]
@amuraru @torkelo - Is it possible to do match substitution/expansion from the override regex?  Otherwise I'd be doing a lot of aliases... If it is possible, then at first glance, I think you might be correct; and this issue isn't relevant.  Here is one example of our real-world use:  we use HAPROXY is a clustered environment to push HTTP requests around to various end-points within the cluster; one of the metrics we use is "haproxy.sessions.active{host=*, backend=*}.  We may have 3 or 4 HAproxy instances, and 10-15 backends per host.  That's 60 rows on the graph; so 60 overrides we'd have to write.  Our preferred alias is "$host : $backend".   We continually add new backends into HAproxy at the rate of about 1 per month across as many as 25 clusters.

**Comment by torkelo** [comment]
Added alias patterns (to Grafana 2.0, develop branch, soon to merged to master when beta is relased later this week or early next week). 

Alias patterns look like this: $tag_tagname or [[tag_tagname]] ,  needs to be prefixed with `tag_` in order to not conflict with template variables with the same name as a tag.

**Comment by kylemallory** [comment]
Groovy!

**Comment by garthk** [comment]
Could someone give me 2-3 bullet points on how to use alias patterns with OpenTSDB for something obvious, e.g. the `system.cpu.load` example where I'd like to quickly build graphs for different `host=` tag values?

**Comment by torkelo** [comment]
Alias patterns look like this: $tag_tagname or [[tag_tagname]] , needs to be prefixed with tag_ in order to not conflict with template variables with the same name as a tag. 

Will add a picture later

**Comment by kylemallory** [comment]
For example;  "system.cpu.load" with tag "host=serv01".  In the alias for that metric, simply specify "$tag_host" or "[[tag_host]]" in the alias.  You should also be able to specify static text, along with the variable, ie. "Host: [[tag_host]]" and the actual alias shown will be "Host: serv01"

**Comment by alexellis** [comment]
Slightly off-topic, but where is this best documented - so I can learn more about the alias patterns?

**Comment by rohit01** [comment]
"$tag_host" and "[[tag_host]]" does work in the alias. However, I see, if multiple queries are defined in a graph, the alias defined for query "A" is applied to all.
