### ISSUE TITLE
support proxies that do not preserve the url path

### ISSUE THREAD

**Issue by wu105** [grafana/grafana#13459]
### What Grafana version are you using? 4.4.3, 5.0.4

Many of the links on the grafana pages are broken if served over kubernetes apiserver proxy, which would have a url similar to the following:

https://<host>:<port>/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy

Many links on the grafana page would have a url path missing the '/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy' thus broken - e.g., https://<host>:<port>/dashboard/new/?editview=import.   Other proxy configurations that do not preserve the url path would have the same issue.

**Comment by torkelo** [comment]
Don’t understand really. As long you set root_url to the full proxy url everything should work fine

**Comment by wu105** [comment]
We used the following commands to deploy heapster with Grafana:
    git clone https://github.com/kubernetes/heapster heapster
    kubectl create -f heapster/deploy/kube-config/influxdb/
    kubectl create -f heapster/deploy/kube-config/rbac/

Should we register the issue with heapster?  If not, It would be helpful if you can specify how we should deploy it differently in order to get Grafana to work through the kubernetes apiserver proxy.

**Comment by torkelo** [comment]
Yes, please do. This is not an issue that can be fixed in Grafana as using grafana behind reverse proxy and sub path already works

**Comment by wu105** [comment]
I registered an issue with heapster: https://github.com/kubernetes/heapster/issues/2095

Still, I think the use of a root_url and require proxy to set it is not desirable.  If all the links on the page are properly specified with relative path, proxies inserting something in the path would not need to know whether the app requires setting root_url

**Comment by torkelo** [comment]
Most links are relative, the root_url is used for a million other things like redirects, oauth callback urls, links in emails etc

**Comment by wu105** [comment]
Not sure whether we are talking about the same thing.
The wrong links are the admin links like adding a data source, creating a dashboard, or the links for user added dashboards.  When moused over, the links would show something like the following:
https://<server>:<port>/datasource<https://%3cserver%3e:%3cport%3e/datasource>
https://<server>:<port>/dashboard/new<https://%3cserver%3e:%3cport%3e/dashboard/new>
https://<server>:<port>/d/ykcS910ik/cluster
missing the /api/v1/namespaces/kube-system/services/monitoring-grafana/proxy part.

Below are two screen shots.
You may want to find a kubernetes cluster with heapster installed and checkon the Grafana pages through the apiserver proxy.

mouse over +/Create -> Dashboard, compare its url displayed at the botton and the page url in the address field

[cid:image002.png@01D4590C.7D8736C0]

Mouse over user added dashboard “Cluster” (the correct url for the “Cluster” dashboard is in the address field):

[cid:image001.png@01D4590D.C5BA8810]

**Comment by torkelo** [comment]
Cannot replicate that, are you proxy doing some strange url / link rewriting ? What did you set root_url to?

**Comment by wu105** [comment]
It is standard kubernetes apiserver proxy.  https://<host>:6443<https://%3chost%3e:6443> is the standard kubernetes api endpoint with https enabled.
All we did was to deploy heapster outlined in an earlier message, following the heapster document.
I have no idea how that deployment sets up the proxy and registered an entry for ‘kubectl cluster-info’ to advertise the proxy for Grafana as well as heapster.

I have cross-referenced this issue with an heapster issue.

**Comment by torkelo** [comment]
Well sounds like an issue with how grafana is configured or something is doing url / link rewriting poorly. Not a grafana issue at least

**Comment by torkelo** [comment]
I have never heard of anyway accessing grafana via kibernetes apiserver proxy , are you sure it is designed for that? Normally you would have an ingress controller

**Comment by wu105** [comment]
The kubernetes api server provides proxy for all services running on a kubernetes cluster, see https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#discovering-builtin-services

The document does include the following: `Some web apps may not work, particularly those with client side javascript that construct urls in a way that is unaware of the proxy path prefix.`   My reading is that the problem urls are constructed in the browser after passing the proxy from the server to the browser, thus the proxy would not be able to help.  

I believe the grafana problem is with the html construction, and absolute paths are used on the problem links, see screen shot of the html source as shown in chrome developer tools.  The logo is using a relative path (red underline, no leading / on the path) and works fine, while the Create Dashboard link is using a absolute path (blue underline, with leading /).  If you simply remove the leading /, the Create Dashboard link would work just as well as the logo.  Adding the proxy path prefix is not necessary, but if you have to, the current page url (including  the proxy path prefix) is known in the browser context.

![relativevsabsolutepath](https://user-images.githubusercontent.com/17152363/46362351-06d9a900-c63e-11e8-8df1-a29c5fe806d0.PNG)

**Comment by ChenLingPeng** [comment]
have the same issue when using grafana with istio. access grafana use path /api/v1/namespaces/istio-system/services/grafana:http/proxy/ . the link path is using absolute paths shows below
![_b6cd88e6-61ce-476e-94ff-3c37ebe4a8f6](https://user-images.githubusercontent.com/1817942/47831664-71f8d580-ddcc-11e8-8956-897a0c5153cf.png)

**Comment by torkelo** [comment]
Not sure why you show search result link, it has nothing to do with data proxy

**Comment by wu105** [comment]
@torkelo 
Have you decided what to do with this issue?

The v4.4.3 of grafana renders the hrefs for Cluster/Pods selection menu in a way that the Cluster/Pods selection works behind kubernetes proxy.   Thus this can be considered a regression.   A regression test that verifies the hrefs do not have a leading / would have caught this without putting the grafana behind a kubernetes proxy in your testing environment.

Is there a reason that at least those hrefs in the newer version won't restore the old implementation?   Is there a reason that other problem hrefs cannot be improved by adopting a similar implementation?  We may want to go over the hrefs one by one.

**Comment by torkelo** [comment]
@wu105 I am not sure what you are talking about , cluster and pod selection ?

Just set grafana a root_url the full browser url for the reverse proxy and grafana should generate the correct urls

**Comment by wu105** [comment]
@torkelo After click on the Cluster here 
![image](https://user-images.githubusercontent.com/17152363/47897123-b923ac80-de46-11e8-8bdf-a98ff42108d4.png)
We can select Cluster or Pods here, the links in question:
![image](https://user-images.githubusercontent.com/17152363/47897074-8bd6fe80-de46-11e8-9b42-18023f68178c.png)
These are 4.4.3 screen shots.  These two links are working in 4.4.3 without extra configurations, but they are broken in 5.0.3 in the same kubernetes environment.  It would be nice if all the links would open their pages like these two in 4.3.3.

**Comment by torkelo** [comment]
These links are based on your root_url configuration

**Comment by torkelo** [comment]
But if more people are using ad hoc kubernetes api proxy like you and find this an issue we will investigate and try to address it, but so far it's only you

**Comment by wu105** [comment]
@torkelo ChenLingPeng just doubled the number of people who happened to expressed their wishes here :-)

This issue might be resolvable by implementing a coding standard on hrefs, e.g., doing away leading /.

**Comment by ChenLingPeng** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls

we usually access http[s] service in kubernetes by [this way](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls)
path with leading / is not working in this situation

**Comment by spyros87** [comment]
@torkelo I face the same issue here!
