### ISSUE TITLE
Deleting a row: if page is scrolled down, delete dialog doesnt position itself relative to current view

### ISSUE THREAD

**Issue by judemorrissey** [grafana/grafana#1345]
Minor issue, but I reckon UI improvements may be appreciated.

See picture below, I duplicated a singlestat panel and it didnt go in the row I was hoping it'll go in (separate ticket #1346 ), but it went into a new row. I tried to delete the row while the page is scrolled down, but as you see in the screen shot, the dialog box is obscured.

The browser I'm using is the latest Firefox, on a Mac, on Grafana 1.9.0
![screen shot 2015-01-15 at 10 44 00 am](https://cloud.githubusercontent.com/assets/5974771/5764102/5fc1b264-9ca4-11e4-8ff4-9dfff2e372ea.png)

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by torkelo** [comment]
Fixed!
