### ISSUE TITLE
v - 5.2.3

### ISSUE THREAD

**Issue by w050220238** [grafana/grafana#13454]
### What Grafana version are you using?
v5.2.3
### What OS are you running grafana on?
Linux
### What did you do?
Dashboard variable set using label_values()
### What was the expected result?
Shows all values in selection menu despite what i checked as default
### What happened instead?
The selection menu only shows "All" and the default value i selected

**Comment by torkelo** [comment]
You need to provide more detail, what does your query look like and what exactly does Prometheus return for this query? You can inspect the query and the response in chrome dev tools network tab
