### ISSUE TITLE
Graph tooltip show time range when selecting range in graph

### ISSUE THREAD

**Issue by Farfaday** [grafana/grafana#13453]
Hi,
I am searching for an easy way to measure a duration directly on a graph, but I could not find that.

The only approaching feature I could find is the regions-events http://docs.grafana.org/reference/annotations/#adding-regions-events

Idea would be to have a similar system to display the difference between the start and stop time of the selected area :)

Many thanks !

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
