### ISSUE TITLE
grafana alert notification integrations out of sync

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#13466]
we've had some issues with alerting state getting out of date in pagerduty,
somehow sometimes state changes don't make it to pagerduty.

in case of timeouts, should it not keep retrying indefinitely until a different state change for the same alert comes up?
better a late state change than an out of sync, i think

not sure exactly which version, but very recent (our ops and customer HG)

@DanCech said we don't see anything in the logs when this happens

**Comment by torkelo** [comment]
should be fixed by the work that is currently going on with alert notifications, https://github.com/grafana/grafana/pull/13440
