### ISSUE TITLE
[Docs] Add link to AD Search Syntax For Example Nested Groups

### ISSUE THREAD

**Issue by ArcticSnowman** [grafana/grafana#13465]
While researching how to setup nested search against AD via LDAP the example was confusing on the page http://docs.grafana.org/auth/ldap/#nested-recursive-group-membership

Turns out after having talked to our ITS people that look after the Windows AD box, those strange numbers in the example `1.2.840.113556.1.4.1941` are needed as AD want the OID to use the `LDAP_MATCHING_RULE_IN_CHAIN` rule.

I would suggest that you update the docs with a link to https://docs.microsoft.com/en-us/windows/desktop/adsi/search-filter-syntax that explains in better terms how to search AD

**Comment by marefr** [comment]
@ArcticSnowman would you be interested in contributing these changes by opening a pull request?

**Comment by ArcticSnowman** [comment]
PR created...
