### ISSUE TITLE
Allow nesting rows

### ISSUE THREAD

**Issue by carlpett** [grafana/grafana#13467]
If I template a row to repeat on some variable, I may get _a lot_ of rows. It would be very convenient to be able to nest them within a parent row, so I could collapse them all at once.

My use-case is having a separate row per pod on a Kubernetes node-dashboard, since it is frequently very useful to look at multiple ones at once. Sticking 20-30 series in the same graph, however, gets very busy, so it is much easier to parse visually if it is split up.

**Comment by torkelo** [comment]
This will likely not be possible, or to complex to build. Rows are messy enough as it is :)

**Comment by carlpett** [comment]
I'm not too surprised this would be (very) hard, but figured I'd raise the topic at least.
At least there is a canonical "nope" now :)
