### ISSUE TITLE
Cannot add dashboards with long names to playlist

### ISSUE THREAD

**Issue by neufeldtech** [grafana/grafana#13464]
### What Grafana version are you using? 
v5.2.4
### What OS are you running grafana on? 
Linux (CentOS)
### What did you do? 
On `/playlists/create` page, I'm attempting to add a dashboard that has a long name to a playlist
### What was the expected result? 
The 'Add to playlist' button should be clickable, and we should be able to add a dashboard to the playlist.
### What happened instead? 
The 'Add to playlist' button is not clickable when dashboards with long names are present in the current filter. 

![image](https://user-images.githubusercontent.com/8252744/46216352-fc997100-c304-11e8-97dd-74e8ec4ad508.png)

**Comment by torkelo** [comment]
think this can be fixed using css only. setting some max width, text overflow elipsis

**Comment by neufeldtech** [comment]
I'll take a crack at this, even though CSS is terrifying
