### ISSUE TITLE
Request Enable/Disable Panel Option

### ISSUE THREAD

**Issue by korishan** [grafana/grafana#13468]
Hi, I'm new to the whole Grafana scene. As such, I'm also playing around with different settings, different panels with different queries, trying various things. 
However, one thing I have noticed is there isn't a way to "disable" a panel. Just make it so that the code within doesn't run.
I'm working on a Power monitor setup, I've built the pcb, coded the arduino, and configured influxdb to received the data through a python script.
So while working with Grafana, I'm finding a need to disable panels as I'm stumbling to get things working. However, I think this would be a good function to have in general, as some panels don't "always" need to be active. 

Granted, I haven't gone through all the help files and such, but I am a fan of "Find/Search", and I haven't found a way to "disable", yet. Unless it's called something else, maybe(?)

Currently running Grafana v5.2.4 on an older laptop, a Dell Inspiron 630, unfortunately. The data will be ran on a real server later on. I just need it to be a bit mobile, atm.

Thanks for the great work you guys have done with this project. A year ago I didn't know about Grafana, but I've seen some really nice designs and data displays using it  :)

Kori

**Comment by emmanuelnk** [comment]
Is this feature being worked on? It would be very helpful!

**Comment by jeka-r** [comment]
The requested functionality is in great demand
