### ISSUE TITLE
Grafana variables intermitently changing into URL encoding due to which graphs stop populating

### ISSUE THREAD

**Issue by rhlnair87** [grafana/grafana#13462]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
 Grafana v5.2.4
### What datasource are you using?
Graphite
### What OS are you running grafana on?
RedHat7
### What did you do?
I created a variable (tried both query and custom) in Grafana and used it to query for creating graphs.

### What was the expected result?
Expected result was to populate graph without any errors.

### What happened instead?
Initially it works but while using variables some of the created graphs stop populating the data.
Also at the same time when I try to create new graph using the variable it doesnt work.

### If related to metric query / data viz:

- $datacenter and $client are the variables created

Following is metric query:
-  cactiStyle($datacenter.myapp.prod.$client.some_servers.*.connection_threads)

`In this case the variable $datacenter is getting converted into URL encoding. The same issue sometimes happen with the variable $client`

Following is the output from query inspector:
> xhrStatus:"complete"
request:Object
method:"POST"
url:"http://mydomain.com/render"
data:"target=cactiStyle(%7Bsomewhere%7D.myapp.prod.THE_CLIENT.cache_servers.*.connection_threads)&from=-48h&until=now&format=json&maxDataPoints=1024"
response:Array[0]

**Comment by torkelo** [comment]
What value did you set the variables to?

**Comment by rhlnair87** [comment]
Custom values like: instance1,instance2,instance3

**Comment by rhlnair87** [comment]
In this case, custom values like: somewhere, somewhere1, somewhere2

**Comment by rhlnair87** [comment]
As you can see in the query inspector, its rendereing the variable as "%7Bsomewhere%7D"
It was expected to be rendered as "somewhere"

**Comment by torkelo** [comment]
can you open dashboard settings / JSON Model and look at the templating section and find the variable, what is it's current value?

**Comment by rhlnair87** [comment]
Just an update: in selection options, I disabled "multivalue" and "include all options" and now the graphs seems to be rendering properly. Enabling the multivalue triggers the issue again.

Looks like this is an old issue: https://github.com/grafana/grafana/issues/2918

**Comment by rhlnair87** [comment]
> 
> 
> can you open dashboard settings / JSON Model and look at the templating section and find the variable, what is it's current value?

Value for the variable $datacenter is somewhere, somewhere1, somewhere2

**Comment by torkelo** [comment]
you must be using a very old version of Graphite that does not support the multi value glob syntax `{somewhere}`

**Comment by rhlnair87** [comment]
> 
> 
> you must be using a very old version of Graphite that does not support the multi value glob syntax `{somewhere}`

I am using Grafana v5.2.4 which is the latest one

**Comment by torkelo** [comment]
I said Graphite , not Grafana . What version of Graphite are you using?

**Comment by rhlnair87** [comment]
Ohh sorry, the graphite version used is : graphite-web-0.9.16

**Comment by torkelo** [comment]
it's very old, can you upgrade?
