### ISSUE TITLE
Duplicating a panel that should exactly fit into a row ends up making a new row

### ISSUE THREAD

**Issue by judemorrissey** [grafana/grafana#1346]
Minor issue, but I reckon UI improvements may be appreciated.

See picture below that I recycled from #1345, I duplicated my singlestat panel with a width of 2, which should fit in the row below it, however it didn't go there and it made a new row for itself.

The browser I'm using is the latest Firefox, on a Mac, on Grafana 1.9.0
![screen shot 2015-01-15 at 10 44 00 am](https://cloud.githubusercontent.com/assets/5974771/5764102/5fc1b264-9ca4-11e4-8ff4-9dfff2e372ea.png)

**Comment by torkelo** [comment]
Thanks reporting this

**Comment by torkelo** [comment]
This was actually fixed in 1.9.1, https://github.com/grafana/grafana/issues/1185

162eb4ca35d1ffe5e88ea25076bb02e7341f46df
