### ISSUE TITLE
Bug: Cannot connect to localhost, IP works

### ISSUE THREAD

**Issue by srinathganesh** [grafana/grafana#13469]
When I create a datasource via IP, then it works but when connecting to localhost it does not work

![image](https://user-images.githubusercontent.com/43715636/46253376-d0622980-c497-11e8-8cc2-413f58c3c671.png)
------------------
Using docker to connect with the latest version

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

Sounds like a docket networking issue, for localhost to work you would need host networking configured for your container
