### ISSUE TITLE
Alerts are shown on my graphs, but I have no alert rules

### ISSUE THREAD

**Issue by LouisKruger** [grafana/grafana#13460]
### What Grafana version are you using?
Grafana v5.1.5 (69ab6cb72)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Not sure

### What did you do?
I saw red marks on my graphs. I toggled the "Alerts" checkbox at the top which made them appear/disappear, so I concluded that they are alerts.
![image](https://user-images.githubusercontent.com/7338817/46199699-f5c42b80-c30f-11e8-9fbd-a4524d5f87aa.png)

![image](https://user-images.githubusercontent.com/7338817/46198500-ec858f80-c30c-11e8-85c5-616f6e4dffbb.png)

I opened up the Alert Rules from the menu on the left.

### What was the expected result?
I expected the Alert Rules to show some alert rules that would cause the alert I can see on the graphs so that I can analyse what the cause might be.

### What happened instead?
I saw no alert rules in the Alert Rules section.
![image](https://user-images.githubusercontent.com/7338817/46199247-daa4ec00-c30e-11e8-9863-cd33e739ea17.png)

### If related to metric query / data viz:
Not sure, don't think so.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
No alerts in response
![image](https://user-images.githubusercontent.com/7338817/46199502-82221e80-c30f-11e8-80c0-1a9f8e40cebf.png)

No errors in Console
![image](https://user-images.githubusercontent.com/7338817/46199531-949c5800-c30f-11e8-80fb-505b89084697.png)

**Comment by torkelo** [comment]
The alerts checkbox at the top is a checkbox for showing annotations, someone has added. It to this dashboard

**Comment by LouisKruger** [comment]
Do you mean someone added a checkbox for hiding/showing annotations and that this checkbox happens to be called "Alerts" by coincidence?

**Comment by torkelo** [comment]
Yepp
