### ISSUE TITLE
Create Dashboard API fails when folderId is non-zero

### ISSUE THREAD

**Issue by dan0kun** [grafana/grafana#13479]
Grafana 5.2.4

Using the [Dashboard API](http://docs.grafana.org/http_api/dashboard/#create-update-dashboard), POSTing the following input fails:

`{
      "dashboard": {
        "id": null,
        "uid": null,
        "title": "Test3"
      },
      "folderId": 24
}`

even though there is a folder with id = 24.  Changing the folderId to 0 works.

The API describes specifying the folderId, but it doesn't appear to be working.

**Comment by torkelo** [comment]
what is the error returned? Any error detail in grafana server log?

**Comment by dan0kun** [comment]
The error was "failed to write dashboard" but I figured out what the problem was.  I had been running a node script that removes and recreates a list of folders, and the browser window I was looking at for `http://localhost:3001/api/folders` had an old list of folders, so the folder ids were no longer valid.

Basically, user error - sorry.
