### ISSUE TITLE
Feature request: pull request / review workflow for dashboards

### ISSUE THREAD

**Issue by c-bb** [grafana/grafana#13476]
Building good dashboards is nontrivial and takes some skill. It's easy to make mistakes that are not necessarily easy to spot (e.g., you may end up being mistaken about what units a given graph shows). The more complex your queries are, the harder it gets.

In fact, building a complex dashboard is not very different to writing a program.

Programmers have figured out good workflows for peer review to minimize errors: things like GitHub pull requests and reviews.

It would be great if Grafana could support a similar pull request / review workflows for editing dashboards.

A reasonable starting point might be to build on [Scripted Dashboards](http://docs.grafana.org/reference/scripting/) and support pulling these from GitHub or a GitHub Enterprise instance. This way, we could leverage GitHub's existing pull request workflows.

**Comment by bergquist** [comment]
This is something we have been thinking about but not really sure how we want to implement it. 
We created an issue asking for feedback https://github.com/grafana/grafana/issues/13823 we will continue working on this feature from that issue so Im closing this issue.
