### ISSUE TITLE
[Feat] Enable use of SSL connections for the sql connection

### ISSUE THREAD

**Issue by dsalsbach** [grafana/grafana#13475]
### What Grafana version are you using?
v5.2.4

### What datasource are you using?
MSSQL plugin

### What OS are you running grafana on?
Ubuntu 18.04

### What did you do?
This **_nasty_** workaround
![image](https://user-images.githubusercontent.com/2862142/46289981-e13f9780-c58a-11e8-9204-f9a02722f212.png)

The database(s) we want to query for performance metrics has the requires SSL flag set. Either we have to reduce security by allowing unencrypted connections (which is not an option due to business) or use this workaround of which we do not know how long it will be supported.

The request is thus an option that allows us to use SSL encryption on the connection string.

**Comment by ramiro** [comment]
Sorry for not seeing this issue!. I reported exactly the same thing (including the nasty workaround) almost two weeks after you. It is #13629 and if was fixed in #13678

**Comment by marefr** [comment]
@ramiro Thanks for spotting this. Will add this issue to the 5.4 milestone as well.
