### ISSUE TITLE
expected closing paranthesis error

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1347]
Hi Torkel:

I keep getting this error on the query line, on grafana that is connected to graphite. Even though, chart works, I keep getting the error. Any ideas why this is?
![error](https://cloud.githubusercontent.com/assets/3009225/5779700/efc97f8a-9d72-11e4-8833-6a89dde5eed2.png)

**Comment by torkelo** [comment]
what does your query look like?

**Comment by gsaray101** [comment]
aliasByNode(sortByName(Server.dc.Guest.Resource_Utilization.server01|server02|server03|server04.PctCpuUsed), 4)

**Comment by torkelo** [comment]
Try this  instead, aliasByNode(sortByName(Server.dc.Guest.Resource_Utilization.{server01,server02,server03,server04}.PctCpuUsed), 4)

**Comment by gsaray101** [comment]
worked, thank you.
