### ISSUE TITLE
"Open original dashboard" button doesn't work after taking a snapshot

### ISSUE THREAD

**Issue by podkolzzzin** [grafana/grafana#13478]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.4 (commit: 0bbac5c)
### What datasource are you using?
PostgreSQL
### What OS are you running grafana on?
Ubuntu
### What did you do?
Take a snapshot
### What was the expected result?
Snapshot appears in a snapshot tab of grafana
### What happened instead?
Snapshot doesn't appears in snapshot tab of grafana, but dashboard was switched to Snapshot mode and "Open original dashboard" button doesn't work

**Comment by torkelo** [comment]
> Snapshot doesn't appears in snapshot tab of grafana, but dashboard was switched to Snapshot mode and "Open original dashboard" button doesn't work

Sorry, I do not understand you can you clarify? Snapshot does not appear? The issue seems to be a bout the link back to the original dashboard, here you talk about wanting to show the snapshot but it does not show.

**Comment by torkelo** [comment]
Do you have grafana under a subpath?

**Comment by podkolzzzin** [comment]
> Snapshot does not appear? 
It doesn't appears in a snapshot list. 
On the page: /dashboard/snapshots

So snapshot isn't visible in the snapshot list, but all the data on dashboard is snapshot data,dashboard is in a snapshot mode and button "Open original" doesn't do anything. 
In fact the URL of the link is the same as dashboard url.

**Comment by torkelo** [comment]
not sure what you are talking about. How did perform the snapshot? What is successful? 

![image](https://user-images.githubusercontent.com/10999/46298603-c0ce0800-c59f-11e8-8eca-f22061cea81f.png)

![image](https://user-images.githubusercontent.com/10999/46298625-d2afab00-c59f-11e8-8fdd-1656a41912b4.png)

**Comment by podkolzzzin** [comment]
I took snapshot as you showing. It was local snapshot.
Creating it lasted for too long and I cancelled it. But dashboard was already in a snapshot state and nothing helps to bring it back to live state.

**Comment by torkelo** [comment]
> Creating it lasted for too long and I cancelled it. But dashboard was already in a snapshot state and nothing helps to bring it back to live state. 

I am sorry, I do not understand you. You cancelled it? what does that mean? 

> But dashboard was already in a snapshot state and nothing helps to bring it back to live state. 
 
What does this mean?

**Comment by podkolzzzin** [comment]
![Grafana](http://imagizer.imageshack.com/img921/1790/18Stm9.png)

**Comment by torkelo** [comment]
maybe you tried to saved during the snapshot phase?

**Comment by podkolzzzin** [comment]
(Grafana)[http://imagizer.imageshack.com/img922/1833/xTqF01.png]
I just clicked somewhere during progress and popup disappered

**Comment by podkolzzzin** [comment]
> maybe you tried to saved during the snapshot phase?
I don't understand what do you mean

**Comment by torkelo** [comment]
open dashboard settings json model, remove property called snapshot or snapshotData in json . 

You must have accidentally saved dashboard during snapshot phase

**Comment by podkolzzzin** [comment]
Ok. I'll try and report whether it helps.
Should I remove snapshotData from every panel?.. It is quite difficult, a have a lot of them

**Comment by torkelo** [comment]
yes
