### ISSUE TITLE
New data source as seperate page

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13489]
Create new page where name and type are the only options.

**Comment by ryantxu** [comment]
While thinking about this, it would be helpful to have the datasource type in the URL.  I have custom panels that only work with some type of datasource and it would be great to link directly to the `create XXX datasource` datasource when one is not configured.

Perhaps related... copying an existing datasource would also be nice :)

**Comment by torkelo** [comment]
we have  search field, we could link this to URL:

![image](https://user-images.githubusercontent.com/10999/46487531-86af7100-c800-11e8-97fe-778324d654a1.png)
