### ISSUE TITLE
No data sources of type Mixed datasource found bug again

### ISSUE THREAD

**Issue by mmijatovic86** [grafana/grafana#13483]
Please include this information:
### What Grafana version are you using?
Grafana 3.1.1 and Grafana 5.3.0 beta 2

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Centos6 and Centos7

### What did you do?
On older Grafana 3.1.1 exported the dashboard with mixed sources to JSON and tried to import the dashboard to new Grafana 5.3 Beta2 

### What was the expected result?
Was hoping to have dashboard up and running on new Grafana

### What happened instead?
I was unable to import the dashboard since the import was blocked by issue

`No data sources of type Mixed datasource found` 

![mixedsource](https://user-images.githubusercontent.com/43775091/46335611-485f5980-c628-11e8-8ccd-6045b616fd36.PNG)

### If related to metric query / data viz:
I already did found couple of posts regarding this issue and taught it was fixed but avail
https://github.com/grafana/grafana/issues/6032
https://github.com/grafana/grafana/issues/10316

**Comment by marefr** [comment]
If you have an existing dashboard that was earlier imported from your exported dashboard above you should be able to do a new export on Grafana 5.3 beta2 version. That exported dashboard should then have the new format you've referenced above and you can import that. 

If you only have the exported version I'm afraid you'll have to change that manually according to the new format you've referenced above before being able to import it.
