### ISSUE TITLE
Explore: label filters can be applied multiple times

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13487]
0. Prometheus datasource, Explore mode enabled in .ini
1. Open Explore and select Prometheus datasource
2. Run query `up`
3. Click twice on a table value (filter)

Result:

![screen shot 2018-10-02 at 12 22 13](https://user-images.githubusercontent.com/859729/46343387-d3971a00-c63d-11e8-9166-cf15e61fb04c.png)

After clicking on the `prometheus` label in the table a couple of times .

**Comment by praveensastry** [comment]
I would like to work on this,  will submit a PR

**Comment by davkal** [comment]
Fixed by #13570
