### ISSUE TITLE
Support multi-master database setup

### ISSUE THREAD

**Issue by buroa** [grafana/grafana#13497]
Please include this information:
### What Grafana version are you using?
Latest
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
CentOS
### What did you do?
Running Grafana with Alerts
### What was the expected result?
No Errors?
### What happened instead?
When running Grafana in HA for MySQL, I have a multi-master setup. They are constantly bombarded with errors like: 

Error 'Duplicate entry '176030' for key 'PRIMARY'' on query. Default database: '...'. Query: 'INSERT INTO `alert_notification_journal` (`org_id`,`alert_id`,`notifier_id`,`sent_at`,`success`) VALUES (x, x, x, x, x)'

I get around this by skipping errors with a AWS RDS command, but I have so many alerts that my active nodes are out of sync by around 5 minutes.

**Comment by marefr** [comment]
By latest I suppose you mean either a nightly build or Grafana v5.3.0-beta2? We've been working on some issues regarding alert notification recently and merged to master yesterday. v5.3.0-beta3 is probably released today and I'll recommend you to try that out or the latest nightly build (if you're using that).

Please try it out and let us know if you still experience the same problems.

**Comment by buroa** [comment]
I'll take a look later today -- but I still think there will be duplicates with a multi-master mysql setup. The tables alert_notification_journal and annotations both have an auto_increment and primary key on the `id` field. This has to be turned off and fixed somehow to allow both of the active mysql servers to insert records and sync over.

**Comment by marefr** [comment]
Sorry thought you were running multiple Grafana instance with single-master and that this worked before without any issues. 

> multi-master mysql setup

Grafana doesn't support multi-master mysql setup, only single master.

**Comment by buroa** [comment]
Jag är inte säker på om det borde vara stängt. Kanske borde vi göra det till en funktion?

**Comment by marefr** [comment]
Now I'm a bit confused. Did you answer in Swedish or did Github do something here? :smile: 

You're right I was a bit too fast closing the issue there. Thanks for pointing that out and giving some more background to this.

**Comment by buroa** [comment]
Thanks! We currently have multiple master Grafana nodes on several master MySQL databases with replication. This would eliminate the need to manually/(automatically in our case) to skip errors during replication.

**Comment by martin-ostlund** [comment]
Shouldn't this be solved by setting auto_increment_offset in the two MySQL masters so they dont conflict with eachother?
https://dev.mysql.com/doc/refman/8.0/en/replication-options-master.html#sysvar_auto_increment_offset

**Comment by buroa** [comment]
> Shouldn't this be solved by setting auto_increment_offset in the two MySQL masters so they dont conflict with eachother?
> https://dev.mysql.com/doc/refman/8.0/en/replication-options-master.html#sysvar_auto_increment_offset

I'm going to take a look at this today. I use Amazon RDS, so they may or may not support this field.

**Comment by caixiachi** [comment]
In our mysql setup, auto_increment_offset /auto_increment_increment is already set in the three MySQL galarer nodes, thie issue of #17586 still exists. Are all tables of Grafana created with auto-increment option  enabled? Our mysql experts request we check if the tables are created with auto increment with reference https://mariadb.com/kb/en/library/auto_increment/ for more info.

Could anyone show the table creation scripts of grafana?

**Comment by tanuj83** [comment]
we are using influxdb as datasource, when this feature would be available? We are looking for for master:master replication support for grafana

**Comment by clushie** [comment]
I've also encountered this error message and figured out that scaling Grafana with helm/kubernetes deployment to more than one pod will result in this split brain situation and cause this error.

**Comment by vikaasbv** [comment]
Galera cluster seems to set autocommit OFF by default.  Grafana seems to assume that autocommit is set to ON in MySQL.  As a result, the outcome of DML commands do not reflect consistently across all connections.  Since DSN definition can set variables, one could try to force autocommit to ON by adjusting the database connection url in Grafana as follows

url = mysql://username:xxxx@host:port/database?autocommit=1
