### ISSUE TITLE
Missing release and release notes for v5.2.5

### ISSUE THREAD

**Issue by dghubble** [grafana/grafana#13494]
I notice a tag was pushed for Grafana v5.2.5 7 days ago, but it wasn't marked as a release on Github, it doesn't have release notes. Is it a legitimate release or a build server gone awry?

cc @torkelo @marefr

**Comment by torkelo** [comment]
It was a patch release for minor issue with the TeamPicker, an issue that one of our customers found, we just pushed a tag with the fix to get new release built, but so far no one else has encountered this bug so we decided to wait with full public release until we had more reasons to or wait for v5.3 stable
