### ISSUE TITLE
[Feature Request] Hide side menu via URL parameter

### ISSUE THREAD

**Issue by nook24** [grafana/grafana#13493]
Would be great, if it would be possible to hide the side menu via an URL parameter like `&hideSidemenu` or so. (I mean the Grafana Menu, which moved from top to left with Grafana 5)

I know that `&kiosk` exists, but this also hide the time controls.

- What OS are you running grafana on?
Grafana v5.2.4 (0bbac5c)

**Comment by torkelo** [comment]
in v5.3+  you can set &kiosk=tv to hide sidemenu and submenu controls (variables) and some other buttons like with inactive mode 
 
https://play.grafana.org/d/000000003/big-dashboard?orgId=1&kiosk=tv

**Comment by nook24** [comment]
@torkelo i noticed that at my Grafana 5.3 installation and even on the Grafana demo system, the user is still able to browse through all Dashboards, even if `&kiosk=tv` is set in URL.
![bildschirmfoto 2018-10-16 um 15 22 44](https://user-images.githubusercontent.com/9019992/47019572-af682c80-d157-11e8-91bb-bfbbcae17802.png)

Is there a way to remove all controls, except the timepicker?

**Comment by torkelo** [comment]
Well of course , the tv / kiosk mode has nothing to do about disabling features, simple esc key will take you out of the tv or kiosk mode

**Comment by nook24** [comment]
Hmm...
Is there a best practice, of how to embed grafana in an `<iframe>` where the user could not escape by just pressing ESC?
My dashboards are all named by UUIDs so, my scripts can update them automatically. But this will confuse the users if they can click on the "All dashboards drop down"

**Comment by nook24** [comment]
In Grafana 5.2 i could not leave `&kisok` by pressing esc key.

**Comment by justsans** [comment]
+1 for this feature. 

But I want to share a simple but very effective solution to do this that worked for me. 
 style="margin-left:-30px"  will hide the sidebar altogether. 

        <iframe style="margin-left:-30px" id="dashboardIframe" src="http://domain/dashboard?orgId=1&theme=light&from=1553319207005&to=1561095207008&var-domain=All&var-tribe=All&var-squad=All&var-site=All&var-self_service_type=All" class="" width="100%" height="1000px" frameborder="0"></iframe>

**Comment by JuanCAM98** [comment]
> +1 for this feature.
> 
> But I want to share a simple but very effective solution to do this that worked for me. style="margin-left:-30px" will hide the sidebar altogether.
> 
> ```
>     <iframe style="margin-left:-30px" id="dashboardIframe" src="http://domain/dashboard?orgId=1&theme=light&from=1553319207005&to=1561095207008&var-domain=All&var-tribe=All&var-squad=All&var-site=All&var-self_service_type=All" class="" width="100%" height="1000px" frameborder="0"></iframe>
> ```

Hello, in which file do I add these lines of code? what is the document path?
