### ISSUE TITLE
html/template: "index" is undefined

### ISSUE THREAD

**Issue by alevchuk** [grafana/grafana#13501]
### What Grafana version are you using?
Version 5.0.0 (commit: 4a77a62949eaef72899b036b981b03a4266dc426 )

### What datasource are you using?
prometheus

### What OS are you running grafana on?
Linux lnd-1 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux

### What did you do?
setting up grafana from scratch (first time)

Pointed browser to http://<my_public_ip>:3000

gets re-directed to `http://<my_public_ip>:3000/login`

I read the docs (e.g. http://docs.grafana.org/installation/troubleshooting/) and searched from this problem online, can't find anything that helps.

switched logs to debug mode - no useful info there

### What was the expected result?
see web UI, login, or homepage

### What happened instead?
mostly blank page, all it says is
`
html/template: "index" is undefined
`

**Comment by torkelo** [comment]
are you building your own version from an old v5.0.0 commit? why an old commit? 

Think you missed a few steps in the building from source guide. You need to build frontend as well 
http://docs.grafana.org/project/building_from_source/#building-grafana-from-source

**Comment by alevchuk** [comment]
yep that's the doc I used. I did skip "Frontend Assets". Going to try that.
 
### old version / tag

i just did `git pull` and got the latest
019d0ee179868fe0f0023ed124494073b9c00050  (5.3.0-beta3)

then re-ran:
```
cd $GOPATH/src/github.com/grafana/grafana
go run build.go setup
go run build.go build  
```

now `grafana-server -v` reports `Version 5.0.0 (commit: NA)` 

```
¯\_(ツ)_/¯ 
```

seems there is a version save problem in the build script. Should I file a different issue for that?
