### ISSUE TITLE
Time range and refresh interval settings for each graph

### ISSUE THREAD

**Issue by yalinjiang** [grafana/grafana#1350]
Hi Torkelo,
     All graphs' time range and refresh interval settings are the same in one dashboard.
Some times we want to set different  time range(TR) and refresh interval(RI)  for each graph according to metric's characteristic.
    For example,we may collect disk usage every hour or even longer,and collect  cpu usage every minute,so we may set  TR to be 1 day  and RI to be 1 hour  for disk usage,
but set  TR to be 6 hours  and RI to be 1 minute  for cpu usage. 
   3x.

**Comment by torkelo** [comment]
Yes, many have requested this, it will come eventually. Dupe https://github.com/grafana/grafana/issues/171
