### ISSUE TITLE
Can't update permissions on role 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13507]
Recent redux migration caused some issues with updating role permissions (sends the same permissions many times). 

problem line is here:
https://github.com/grafana/grafana/blob/master/public/app/features/folders/state/actions.ts#L113

**Comment by jschill** [comment]
Same thing, but with dashboards:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/actions.ts#L61
