### ISSUE TITLE
UX Mockup New DataSource page 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13505]
Design ideas for a page where you only select datasource type. 

After type is selected it will be created with a generic name based on type.

**Comment by ryantxu** [comment]
While thinking about this, it would be helpful to have the new datasource type in the URL.

I have some custom panels that only work with a type of datasources.  It it would be great to link directly to a page that can create that datasource type.

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/46432118-b9e4f800-c74d-11e8-9459-0123f2d2eae8.png)
