### ISSUE TITLE
Grafana Plugin app using REST API

### ISSUE THREAD

**Issue by satishviswanathan** [grafana/grafana#13512]
Grafana Version : 5.2.2
I have a grafana plugin type app with some pages and in one of the page I need to invoke a REST based end point to pull some information and POST it back to a different end point.

Do you have a sample app or any code that I can refer to see how this can be achieved.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You should be able to inject the angular serivce named backendSrv and checkout backend_srv.ts for documentation of what functions it exposes. In general you should be able to make a regular AJAX request without any dependency to Grafana's exposed services.
