### ISSUE TITLE
[Bug] Grafana image renderer does not render image

### ISSUE THREAD

**Issue by thanhlv93** [grafana/grafana#13516]
Please include this information:

What Grafana version are you using?
Grafana v5.2.0-pre1 (5a2cf58)

What datasource are you using?
Postgresql

What OS are you running grafana on?
Ubuntu 16.04

What did you do?
Set up alert email notifications include image.

What was the expected result?
Alert chart image is included in the email.

What happened instead?
Email arrives without image attached. Logs show:

> EROR[10-04|13:52:11] Failed to upload alert panel image.      logger=alerting.notifier error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
DBUG[10-04|13:52:11] Sending notification                     logger=alerting.notifier type=email id=1 isDefault=true
INFO[10-04|13:52:11] Sending alert notification to            logger=alerting.notifier.email addresses=[abc@gmail.com]
DBUG[10-04|13:52:12] Error { TimeoutError: waiting for function failed: timeout 30000ms exceeded logger=rendering
DBUG[10-04|13:52:12]     at new WaitTask (/home/cpu60020-local/Documents/Setup/Grafana/src/github.com/grafana/grafana/data/plugins/grafana-image-renderer-master/node_modules/puppeteer/lib/FrameManager.js:864:28) logger=rendering
DBUG[10-04|13:52:12]     at Frame.waitForFunction (/home/cpu60020-local/Documents/Setup/Grafana/src/github.com/grafana/grafana/data/plugins/grafana-image-renderer-master/node_modules/puppeteer/lib/FrameManager.js:733:12) logger=rendering
DBUG[10-04|13:52:12]     at Page.waitForFunction (/home/cpu60020-local/Documents/Setup/Grafana/src/github.com/grafana/grafana/data/plugins/grafana-image-renderer-master/node_modules/puppeteer/lib/Page.js:1036:29) logger=rendering
DBUG[10-04|13:52:12]     at Browser.<anonymous> (/home/cpu60020-local/Documents/Setup/Grafana/src/github.com/grafana/grafana/data/plugins/grafana-image-renderer-master/build/browser.js:52:28) logger=rendering
DBUG[10-04|13:52:12]     at Generator.next (<anonymous>)      logger=rendering
DBUG[10-04|13:52:12]     at fulfilled (/home/cpu60020-local/Documents/Setup/Grafana/src/github.com/grafana/grafana/data/plugins/grafana-image-renderer-master/build/browser.js:4:58) logger=rendering
DBUG[10-04|13:52:12]     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' } logger=rendering
DBUG[10-04|13:52:13] Job Execution completed                  logger=alerting.engine timeMs=57.209 alertId=3 name="Write Performance (Parse speed) alert" firing=true attemptID=1

**Comment by thanhlv93** [comment]
yeah, I'm using https://github.com/grafana/grafana-image-renderer and I tried to rendered image by click to Share ->  Direct link rendered image , it's working perfect . 

> [rendering]
    # Options to configure external image rendering server like https://github.com/grafana/grafana-image- 
    renderer
    server_url =
    callback_url =

-> Where are these settings?  I can't find in defaults.ini .

**Comment by thanhlv93** [comment]
After added into defaults.ini:

> [rendering]
server_url=http://localhost:3300/render
(I changed the default port 8081 to 3300)

and try to rendered image by click to Share -> Direct link rendered image , the image can't render. 

![screenshot from 2018-10-04 14-43-43](https://user-images.githubusercontent.com/5988002/46459732-ecd9cb00-c7e3-11e8-85c9-cbf6b8d86c88.png)

**Comment by marefr** [comment]
First of all I would recommend that you checkout this repo and [test run using docker-compose](https://github.com/grafana/grafana-image-renderer/tree/master/docker). If that's working I think you have a too old Grafana versions and would recommend trying the latest master (1a6b0adbd75b6e5b51df9d9292ac6d38fd963418).

**Comment by torkelo** [comment]
Please use 5.3 beta and include log of image plugin as well (if you run it in http mode)

**Comment by thanhlv93** [comment]
Thanks @marefr , @torkelo It's working perfect with 5.3 beta.
