### ISSUE TITLE
Metric: AWS/RDS BurstBalance don´t appear in filter

### ISSUE THREAD

**Issue by rmsys** [grafana/grafana#13513]
### What Grafana version are you using?
Grafana v4.6.0 (commit: c47f670) and Grafana v5.2.4 (commit: 0bbac5c)

### What datasource are you using?
CloudWatch Datasource - Native Plugin

### What OS are you running grafana on?
CentOS 6 (AWS AMI linux / Linux 4.9.51-10.52.amzn1.x86_64)

### What did you do?
Get metrics BurstBalance from AWS/RDS.

I have a AWS/RDS with disk volume GP2 and this metric in Cloudwatch stay in metrics directly in AWS/RDS. 

![image](https://user-images.githubusercontent.com/7168855/46417337-cc384500-c6ff-11e8-960a-a51cf90bb466.png)

Grafana show this metric when I set "AWS/EBS | BurstBalance: Stats | Average ". But in AWS/RDS the volume ID is hidden. Is different from EC2 instance

![image](https://user-images.githubusercontent.com/7168855/46417615-73b57780-c700-11e8-8df4-c17fd6e772e2.png)

### What was the expected result?
Show data

### What happened instead?
Nothing

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 No errors

**Comment by marefr** [comment]
@rmsys think that you may be able to just write `BurstBalance` in that input/drop down where `BurstBalance` is not included. At least that would be a viable workaround.

**Comment by rmsys** [comment]
I tried but it still does not display.  :(

**Comment by marefr** [comment]
@rmsys understood. Then you unfortunately have to wait for this to be implemented. Feel free to open a pull request if you want to try and fix this.

**Comment by marefr** [comment]
@mtanda guess there's no other workaround available and the only thing that fixes it is a code change?

**Comment by mtanda** [comment]
I can display RDS `BurstBalance`. The valid dimension for RDS `BurstBalance` is `DBInstanceIdentifier`.
Please check your panel setting.

![image](https://user-images.githubusercontent.com/224552/46656865-f7cc9b00-cbe9-11e8-82c7-7eb893b8ccd1.png)

**Comment by marefr** [comment]
So seems like this have been fixed in more recent version of Grafana. @rmsys please upgrade to a newer Grafana version. Closing this.

**Comment by rmsys** [comment]
Thank you so much!
