### ISSUE TITLE
Explore: table should use same filter icons as in dashboard panels

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13520]
In dashboards, the table panel has two icons (+/-) to filter for a label, allowing for `=` and `!=` filtering.

In Explore, the table panel only supports click to filter for a label (`=`). It should be replaced with the icons filtering to support both filter operations.

**Comment by torkelo** [comment]
yes, this would be nice!

**Comment by Elfo404** [comment]
@davkal If I understood the issue correctly I think this was solved by https://github.com/grafana/grafana/pull/25467
