### ISSUE TITLE
Explore: Support for built-in variables like `$__range`

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13523]
Explore does not do expansion of Grafana's built-in variables yet. This will be helpful when jumping from dashboards that use queries with variables.

Custom dashboard variables must stay expanded though.

**Comment by gabor** [comment]
we should look at the list of all global variables, find the ones we want in explore, and make sure every data source handles them.

**Comment by ivanahuckova** [comment]
I have looked trough supported global variables https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables and documented those ones, that can be used in queries (I have ignored `$__dashboard`, `$__name`, `$__org`, `$__user`  as they are not used in queries).

| Variables used in queries    | Works in Dashboard | Works in Explore | Where is it implemented                                                                                 |
|------------------------------|--------------------|------------------|---------------------------------------------------------------------------------------------------------|
| $__from and $__to            | YES                | YES              | public/app/features/templating/template_srv.ts                                                          |
| $__interval                  | YES                | YES              | public/app/core/utils/explore.ts                                                                        |
| $__interval_ms               | YES                | YES              | public/app/core/utils/explore.ts                                                                        |
| $__range                     | YES                | YES              | public/app/plugins/datasource/prometheus/datasource.ts public/app/plugins/datasource/loki/datasource.ts |
| $timeFilter or $__timeFilter | YES                | YES              | only used in SQL and implemented somewhere there (couldn't find it quickly)                             |
| $__rate_interval             | YES                | YES              | public/app/plugins/datasource/prometheus/datasource.ts public/app/plugins/datasource/loki/datasource.ts |


As documentation says `$__range` variable is currently [supported only in Prometheus](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__range). I have [created a PR](https://github.com/grafana/grafana/pull/36175) to add support for Loki. The implementation of `$__range` (as well as `$__rate_interval` variable is done on data source side (e.g. in `public/app/plugins/datasource/loki/datasource.ts` we have `getRangeScopedVars`) and if data source supports it in dashboard, it is going to support it in Explore as well. 

I have noticed that `$__rate_interval` is not documented and I'll create PR for it. Other than that, all global variables that can be used in queries are supported both - in Explore and Dashboard. Therefore I am closing this issue.
