### ISSUE TITLE
Want to hide some features to viewer role

### ISSUE THREAD

**Issue by MarkSimonovic** [grafana/grafana#13532]
### What Grafana version are you using?
5.0
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu

Hey guys! Awesome job with this beautiful I'm new using it but it's really awesome, I want to do something, I want to hide some features from "viewer role" like hide the sidebar menu for example, it's possible editing the source? where I have to look? I can disable by "display: none;" in the saas files but It not has much sense since I disable that feature for admin role too, some help here? :(

Thank you so much for this wonderful work!

**Comment by torkelo** [comment]
In contextSrv you can check user role and set side menu property to false

**Comment by MarkSimonovic** [comment]
Do u mean here? "public/app/core/services/context_srv.ts" I can't find how to do it or maybe it's here and I don't get it.. Besides may I just hide one button from the sidemenu and not all the sidemenu?

**Comment by marefr** [comment]
@MarkSimonovic yes that's where the implementation is located. If you look at the bottom of this file it register a factory for "contextSrv" which makes it possible to take a constructor argument named contextSrv in an anglar controller, see [this example](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/folder_picker/folder_picker.ts#L26-L27).
