### ISSUE TITLE
Shows Negative values in nonNegativeDerivative graphite function

### ISSUE THREAD

**Issue by ankit1987** [grafana/grafana#1354]
I am  tracking api hits in last 15 min but issue is, when my server get restarted it show negative value though I am using nonNegativeDerivative function.

function  - alias(summarize(nonNegativeDerivative(coms05.snapdeal.com.coms-publisher.com.snapdeal.coms.publisher.service.COMSPublisherStats.IPMS_PRICING_CHANNEL_STATS.CHANNEL_RESPONSE_TIME.count,0),'15min','sum'),'updates in 15min')

json response -

[{"target": "updates in 15min", "datapoints": [[825.0, 1421519400], [2044.0, 1421520300], [30287.0, 1421521200], [37582.0, 1421522100], [228.0, 1421523000], [2735.0, 1421523900], [4376.0, 1421524800], [2042.0, 1421525700], [229.0, 1421526600], [249.0, 1421527500], [229.0, 1421528400], [9448.0, 1421529300], [207.0, 1421530200], [1921.0, 1421531100], [40507.0, 1421532000], [53801.0, 1421532900], [5465.0, 1421533800], [468.0, 1421534700], [2678.0, 1421535600], [209.0, 1421536500], [359.0, 1421537400], [3514.0, 1421538300], [356.0, 1421539200], [1159.0, 1421540100], [3212.0, 1421541000], [210.0, 1421541900], [8046.0, 1421542800], [206.0, 1421543700], [352.0, 1421544600], [8887.0, 1421545500], [556.0, 1421546400], [764.0, 1421547300], [5918.0, 1421548200], [null, 1421549100], [null, 1421550000], [-1675665.0, 1421550900], [357.0, 1421551800], [12003.0, 1421552700], [627.0, 1421553600], [1032.0, 1421554500], [31260.0, 1421555400], [360.0, 1421556300], [534.0, 1421557200], [10589.0, 1421558100], [2632.0, 1421559000], [7447.0, 1421559900], [6231.0, 1421560800], [9717.0, 1421561700], [261.0, 1421562600]]}]

**Comment by torkelo** [comment]
Strange, have not experianced this.

I see you already opened an issue in the correct place for these types of issues (graphite-project), so will close this.
