### ISSUE TITLE
Generic OAuth support users without email 

### ISSUE THREAD

**Issue by zhanglijingisme** [grafana/grafana#13549]
### What Grafana version are you using?
v5.1.4
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
CentOS 7.5
### What did you do?
Do Generic OAuth with Keycloak, with no "email" set in Keycloak "User" -> "Details"
### What was the expected result?
OAuth goes correctly, forward from Keycloak auth page to Grafana
### What happened instead?
Forward to Grafana error page, with "login.OAuthLogin(get info from generic_oauth)" on UI
and, in grafana log, following error is shown,
t=2018-10-02T12:45:38+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="Error getting user info: default backend - 404"

**Comment by zhanglijingisme** [comment]
We've checked [https://github.com/grafana/grafana/blob/v5.1.4/pkg/social/generic_oauth.go] and seems email is mandatory
L185~190
`if !s.extractToken(&data, token) {
		response, err := HttpGet(client, s.apiUrl)
		if err != nil {
			return nil, fmt.Errorf("Error getting user info: %s", err)
		}
        }
`
L252~256
`email := s.extractEmail(data)
	if email == "" {
		s.log.Debug("No email found in id_token", "json", string(payload), "data", data)
		return false
	}
`
At least similar settings (data.Attributes"email:primary" or UPN) are necessary if no email is set. 

This really puzzled us. Is there any good reason for make email mandatory? If so, we hope in official document it could be explained more clearly.

**Comment by torkelo** [comment]
yes, it looks like it's mandatory.  So far you have been the first to encounter this as an issue, so it seems like a uncommon thing for an oauth system to not have emails.

**Comment by baronfel** [comment]
I ran into this today as well. We're going to work around it by adding the `email` scope to our requested scopes, but it would be nice to not require that and instead key off of the subject or something.

**Comment by Peperud** [comment]
Not only is it mandatory, but it expects it to be a single value. It also breaks if an array of emails is sent by the token server. 
Seems like it can be a little more flexible.

**Comment by pwcorbett** [comment]
I have an open PR to allow for the configuration of the email requirement (#16391).

**Comment by linkcd** [comment]
HI, i ran into the same problem that @Peperud mentioned. Due to some reason, my idp returns the id_token with email as an array:
{
...
"email": [
    "name@domain.com"
  ],
"upn":"name@domain.com"
...
}
which breaks the code: cannot unmarshal array into Go struct field UserInfoJson.email of type string"
Config "email_attribute_name" cannot help in this case.

what are the alternatives?
1. creat a PR to make configable and support array?
2. is there a way to use upn instead of email?

thx

**Comment by marefr** [comment]
Supporting email property in array is proposed to be fixed by this PR #14683

**Comment by zhanglijingisme** [comment]
@torkelo @marefr 
We are still focusing on this. Yes most user has email but this doesn't mean it should be mandatory.
Don't know what recent label "awaiting-more-evidence" means - but we really hope this could be solved in near future, as [PR](https://github.com/grafana/grafana/pull/16391) seems already OK by @pwcorbett .

**Comment by marefr** [comment]
What other unique identifier are you having in OAuth provider if you don't have any email? Cant you configure generic_oauth so that this other unique identifier is being used as email as well?

**Comment by sushukka** [comment]
Hello,
Bump for this. I'm using Nextcloud as Oauth2 provider and it send only userid back with the token. The User API itself need to be called with user parameter so hardcoding it in grafana.ini probably won't work. This is quite frustrating as the Oauth2 authentication between Grafana and Nextcloud is pretty easy to setup. Authentication works like it should, but in the final phase Grafana issues that "cannot find, unknown backend, 404" type of message because it cannot find any email addresses. I have posted a enhancement request to Nextcloud forum:
https://help.nextcloud.com/t/oauth2-userinfo-api/70556
However, it seems that there are similar needs also with another Oauth2 providers...so maybe change the generic Oauth functionality so that one could use simply the scope parameter or other to specify which field should be used for matching the users. For example if there is now user:email (use email for user identification), you could write user: userid (use userid parameter for user matching).

**Comment by MartinEmrich** [comment]
Just got bitten by this, too. Looks to me like grafana is trying to use the email field as an unique identifier for users. I am still no Oauth2/OIDC expert, but shouldn't the subject field ("sub") in the token be exactly that? 

My current workaround, as my grafana installation is only for a few people (the admins): grafana.ini supports a `email_attribute_path`, and JMESPath supports string constants: 

````
email_attribute_path = "'your_graph_reading_team@yourcompany.zz'"
````
(Note the single *and* double quotes). This maps this constant to any user logging in, and you're in!

As JMESPath is powerful, I'll next try to extract an acutal unique property (like UPN or subject) from the id_token....

**Comment by MartinEmrich** [comment]
Update: this indeed works, e.g.
````
email_attribute_path = sub
````
uses the token subject.

If I had a Microsoft ADFS oder Azure AD, I'ld add a claim transformation rule to put the UPN in the token, and use e.g.
````
email_attribute_path = upn
````
This ist still just a hacky workaround, as Grafana provisions the user profile with this value in both username and email fields.

**Comment by dalcde** [comment]
> yes, it looks like it's mandatory. So far you have been the first to encounter this as an issue, so it seems like a uncommon thing for an oauth system to not have emails.

It is common for privacy conscious users to want to minimize the amount of information shared. While it may be uncommon for an OAuth provider to not have emails, the users may not consent to sharing the email, and as such Grafana will not receive an email.

**Comment by nvtkaszpir** [comment]
looks like when you set up keycloak  +grafana auth then you user must have an email from `allowed_domains`, thought this can be totally random fqdn.

welcome in 2021.

**Comment by baites** [comment]
I am having the same problem. As per the [documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#email-address), if all fails by step five email should be set empty. However, when users are correctly authenticated, they are identified by the email in the logs. 

```
grafana_app  | logger=http.server t={timestamp} level=info msg="Successful Login" User=baites@unknown
```

I would like to know if grafana internally indexes users by email and not their login. If that is the case, it might be hard to fix the bug as "step five" might be possible to implement, i.e., having an empty email.

Following this [blog](https://community.grafana.com/t/keycloak-oauth-check-empty-users-email/82027/2), I learned you could use JMESPath to parse response JSON to extract the email by setting the query string using the config email_attribute_path in the section [auth.generic_oauth] of the config.ini.
In my case, I am using GitHub as an identity provider via OAuth2. The [GitHub /users API documentation](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user) shows its JSON response. Using the [JMESPath emulator](https://jmespath.org/) I created a query that extracts the email if present or sets a reasonable default, ex. {login name}@unknown.

In my case, I am using grafana in docker solution; therefore, I used the following env to pass the query.

```bash
GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH="contains(keys(@), 'email') && email || join('',[login,'@unknown'])"
```

I hope this help! Specially if my guess is right about grafana having a hard time to support empty emails.

**Comment by jerryguowei** [comment]
I have the same issue by using keycloak because the keycloak user may not have email, I solved the issue by add 
`email_attribute_path = @.email || @.sub`

**Comment by sjafarli** [comment]
> I have the same issue by using keycloak because the keycloak user may not have email, I solved the issue by add `email_attribute_path = @.email || @.sub`

instead of subject identifier (which is a uuid number), preferred_username can also be used here as a fallback
