### ISSUE TITLE
New datasource list page design & stats

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13546]
Ideas for data source list page remake & stats. Make this page will be accessible to Editors (maybe even Viewers) and not only to Org Admins like current data source list page. 

# Actions
* Go to explore mode with this data source
* Go to data source settings page (if have permission) 
* Go to a dashboard list with dashboards using this data source (needs new indexing)

# Stats
* Online status (checked every 5m or so)
* Number of queries in last 5m, last 1h, last day
* Number of failed queries in last 5m, last 1h, last day
* Be able to sort list by these
 
The stats are related to the meta analytics feature we have discussed before. Could be unified with a system that can also collect failed & successful queries by dashboard & user. 

# TODO
* Figure out the priority of this (in relation to v6.0 features)  
* UX Mockups
* Design doc for stat collection & storage

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
