### ISSUE TITLE
Row drag handle is shown even though editing is disabled

### ISSUE THREAD

**Issue by timyllym** [grafana/grafana#13555]
When row is collapsed it shows a drag handle on the right edge for moving row. I think this handle shouldn’t be visible when editing is disabled because it gives a wrong signal to user.

Grafana 5.2
MacOS High Sierra
Google Chrome 69.0.3497.100

**Comment by torkelo** [comment]
Here is the drag handle , and you a canEdit check above to use as reference:

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/DashboardRow.tsx#L115

**Comment by timyllym** [comment]
Ok, I can make a PR. I can't make a new branch though.

**Comment by praveensastry** [comment]
I would like to work on this

**Comment by marefr** [comment]
Fixed in #13568
