### ISSUE TITLE
Add Import-button in empty folder

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#13558]
### What Grafana version are you using?
5.2.4
### What datasource are you using?
Influx
### What OS are you running grafana on?
Debian
### What did you do?
Clicked on settings for the folder
### What was the expected result?
Possible to Import dashboard
### What happened instead?
It was only possible to Create new dashboard
I can see that there is other screen that flashes quickly. In that screen it is possible to choose Create Dashboard and Import. That screen is visible when there is at least one dashboard
Maybe it could looked something like this?
![grafana import](https://user-images.githubusercontent.com/21694965/46602865-bb1d7880-caf1-11e8-8b2e-8d22fdac8dbc.png)

**Comment by marefr** [comment]
As a workaround you can click on the plus icon in the sidebar menu and select import and then choose which folder to import to.

**Comment by flopp999** [comment]
> As a workaround you can click on the plus icon in the sidebar menu and select import and then choose which folder to import to.

Thanks, I also found that when I looked around.

**Comment by aocenas** [comment]
Seem like this discrepancy is still there.
Without dashboard:
![Screenshot from 2020-11-11 14-44-02](https://user-images.githubusercontent.com/1014802/98818852-66fdc480-242c-11eb-929d-651fc7e3d605.png)
With one dashboard:
![Screenshot from 2020-11-11 14-43-32](https://user-images.githubusercontent.com/1014802/98818855-67965b00-242c-11eb-9333-cd962b426466.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
