### ISSUE TITLE
Doubled text in annotations

### ISSUE THREAD

**Issue by Fank** [grafana/grafana#13553]
Please include this information:
### What Grafana version are you using?
Grafana v5.3.0-beta2 (c6f7ae4)
### What datasource are you using?
influxdb
### What OS are you running grafana on?
docker latest stable
### What did you do?
I hovered over the annotations to show them
### What was the expected result?
No doubled text
### What happened instead?
The "text" is shown twice
![image](https://user-images.githubusercontent.com/1900106/46584846-beb8ed00-ca68-11e8-9482-c3133e933904.png)
### If related to metric query / data viz:
![image](https://user-images.githubusercontent.com/1900106/46584817-5bc75600-ca68-11e8-9d21-afa0f7b8f2cb.png)

The data exists not twice
![image](https://user-images.githubusercontent.com/1900106/46584840-9e892e00-ca68-11e8-9a56-e1629da85232.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
I think its the best to have the source:
http://grafana.fankserver.com/d/42aGsmJmz/jagger-and-friends-restore?orgId=1&panelId=2&fullscreen&from=1538933175496&to=1538933657822

**Comment by torkelo** [comment]
that is strange, will try to replicate. Can you show the exact response from influxdb (by opening chrome dev tools network tab and toggle annotation)

**Comment by Fank** [comment]
@torkelo thats the reason why i added the link to the grafana dashboard. Don't know how to extract the information without missing something.

**Comment by torkelo** [comment]
ok, I have found the bug. 
You can work around the bug by removing column mappings for the text column the annotation definition.
