### ISSUE TITLE
Stackdriver: intellisense/autocomplete for Alias patterns

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#13560]
The alias by field in the Stackdriver query editor is currently a plain input field. This requires the user to read the help section or documentation if they want to format their legends keys. A Slate or Ace input field could provide autocomplete to make this process much simpler.

ref #13289

**Comment by sunker** [comment]
This [standard field options](https://grafana.com/docs/grafana/latest/panels/standard-options/#standard-field-options) in Grafana has in many ways replaced the need for alias mapping. For that reason, we'll not continue to invest in the alias mapping field.
