### ISSUE TITLE
Alert notifier settings documentation & validation

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#13579]
When attempting to manage alert notifiers via the API it is easy to end up with invalid configurations like incorrect types or fields in the notifier settings.

It would be very useful if these options were fully-documented on http://docs.grafana.org/alerting/notifications/ and/or http://docs.grafana.org/http_api/alerting/#create-alert-notification

In addition, it would be helpful if the notifiers could implement a function used to check the settings on create/update and reject invalid configurations.

**Comment by oddlittlebird** [comment]
This looks like two issues:

1. Update documentation with missing options.
1. Update a function to check settings.

@torkelo , @DanCech , @marefr  - Please review.

**Comment by achatterjee-grafana** [comment]
Closing, as this is an issue is related to legacy alerting.
