### ISSUE TITLE
Add basic authentication to metrics endpoint

### ISSUE THREAD

**Issue by bobmshannon** [grafana/grafana#13577]
Currently, Grafana exposes a `/metrics` endpoint that serves metrics in Prometheus text exposition format.

When running Grafana behind a reverse proxy, this results in the `/metrics` endpoint being publicly accessible without any authentication. In some cases, this may be surprising behavior and undesirable depending on one's environment's security requirements.

While it is trivial to update the reverse proxy configuration to specifically disable reverse proxying on this route, I think it would be ideal if we can instead add a basic authentication to the metrics endpoint that can be optionally enabled, for example:

```
[metrics.prometheus]
basic_auth_username=prometheus
basic_auth_password=password
```

This would allow for the reverse proxy configuration to remain simplified, while only allowing authorized clients to gather internal Grafana metrics.

**Comment by bobmshannon** [comment]
If this sounds reasonable and no one has any feedback or concerns, I could take a look at implementing this change.

**Comment by ndangarosia** [comment]
Can we use existing secret for the same?

**Comment by ndangarosia** [comment]
Also, after implementing this, /metrics endpoint we can't access from web browser. is there any way to access with credentials?
