### ISSUE TITLE
[Bug] Building from source TestData DB not working

### ISSUE THREAD

**Issue by Fajarthea5** [grafana/grafana#13582]
So recently i just installed Grafana into my directory folder using this tutorial http://docs.grafana.org/project/building_from_source/ ,but unfortunately my TestData DB is not working there's nothing appear https://imgur.com/a/vBqnr7p i just want to enabled it but there's nothing there so please can someone help me out please.

Grafana v5.3.0

Sincerely,
Fajar

**Comment by torkelo** [comment]
it does not have readme, it's not an app anymore but just a datasource (with a new plugin id), go to datasources and add new datasource, pick Test Data
