### ISSUE TITLE
Poor performance plotting on OpenTSDB rate chart with a line width > 1

### ISSUE THREAD

**Issue by trixpan** [grafana/grafana#1358]
Hi,

I am experiencing extremely low performance (i.e. around 15 20 seconds to chart) while charting 3 packet rate line charts using OpenTSDB backend data over a 2 days timespan and a line width higher than 1.

The data is generated using tcollector (default's config & plugins)  and the plot is composed by three identical queries for 3 different hostnames.

Chart can be described as:

```Metrics
metric: proc.net.packets
rate: check
tag host: server01-03

Axes & Grids:
Left Y axis
Format: none
Values / Avg

Display Styles: 
Line width 3
```

Slowness starts when I start clicking the Line width drop down box and as mentioned, plotting can take up to 16 seconds for a single graph panel.

Configuring the line witch to 1 solves the slowness.

*Note: I also did query the using openTSDB "ugly" interface (server side), and the performance is ok, reporting the following details "71522 points retrieved, 34550 points plotted in 141ms.", therefore I suspect this is either a a Grafana issue or a browser issue (results are similar on both Chrome & Firefox).*

**Comment by torkelo** [comment]
you need top specify an aggregator, more than one point per pixel is just wasting browser cpu
