### ISSUE TITLE
Hide empty does not hide from all series tooltip

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1359]
Using 1.9.1 and the 'hide empty' option to hide series with null values works correctly but if you also use the 'all series' tooltip they are still shown in the tooltip.

![image](https://cloud.githubusercontent.com/assets/917241/5816016/d02a0740-a09b-11e4-9a6d-badd9dc48228.png)

**Comment by torkelo** [comment]
thanks for reporting this, try to fix

**Comment by torkelo** [comment]
Fixed!

**Comment by maddenca** [comment]
Such a fast turnaround, top!
