### ISSUE TITLE
Change default chart library to more robust solution

### ISSUE THREAD

**Issue by brylie** [grafana/grafana#13595]
In working with Grafana, I have found various quirks and shortcomings that make it difficult to produce certain chart types (e.g. histogram, grouped bar chart, and more). In general, it seems like the Grafana charting library is somewhat ad-hoc and focused primarily on time-series data.

# Feature request
Switch to a fully-fledged, open source graphing library for default Grafana plots.

This will take some of the maintenance burden off of Grafana developers, and probably lead to a more robust user experience.

# Resources
The [Plotly.js library](https://plot.ly/javascript/) is notable for its capabilities and consistent API.

**Comment by torkelo** [comment]
we are using an open source graphing library (flot), it's very old however and no longer maintained. But we are using a number of extensions to this library as it very easy to modify. 

We are also using d3 for the heatmap panel. We have yet a good plan for the future in terms of graphing libs and how to migrate to something more modern. But it will be something we will do post react migration.
