### ISSUE TITLE
missing Image renderer on Raspbian 4.14 (Stretch) on a Raspberry Pi 3b, 

### ISSUE THREAD

**Issue by alwashe** [grafana/grafana#13598]
phantomjs is missing in the arm builds, is there a way to render images on the Pi?

**Comment by torkelo** [comment]
There’s is no phantomjs binary for arm, but you can try installing our new image renderer plugin, it requires nodejs runtime, it will install a headless chrome that I think has an arm version that will be automatically installed when you do yarn or npm install in the plugin for. Follow plugin readme for  installation docs 

https://github.com/grafana/grafana-image-renderer
