### ISSUE TITLE
Grafana table transforms stubbornly refuse to work

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#13596]
### What Grafana version are you using?

5.2.4

### What datasource are you using?

prometheus

### What OS are you running grafana on?

Debian and Ubuntu Linux

### What did you do?

Add a table and then change the "table transform" setting to something other than "Table"

### What was the expected result?

The table transform should be set to whatever I set it to.

### What happened instead?

The change has no effect, and when I switch tabs, it goes back to "Table"

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

(TODO)

**Comment by torkelo** [comment]
you need to change the Prometheus query so that it does not return Table format. The transforms in the table panel options tab is only for transforming time series into table but if your query is already set to return table data then the transform option will not have an effect.

**Comment by NotAFile** [comment]
Could this fact be documented or displayed somehow? This seems like a lot of magic to just intuitively know.
