### ISSUE TITLE
Lock versions in package.json

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#13599]
Some of the dependencies in our front end can possibly bump to new versions without our knowledge. I think it would be a good idea to lock the versions, ie remove the ^ in package.json.

I recently had a problem with webpack being upgraded and break another package, webpack-cli.  

What do you think?

**Comment by torkelo** [comment]
yes, agree!

**Comment by jschill** [comment]
Interesting! Tests failed after locking down the versions. Which means we were actually dependent on a version newer than specified in the lock-file.
