### ISSUE TITLE
New stacking mode, Stack negative and positive series separately 

### ISSUE THREAD

**Issue by imsnif** [grafana/grafana#1360]
<b>The gist of it:</b>
Negative values are decremented from positive values rather than being stacked separately.

<b>Detailed description:</b>
I've got a graph (from a graphite datasource) with multiple metrics, all of which are sometimes positive and sometimes negative.
When those metrics are stacked together, the negative values are stacked along with the positive values.

What I would expect is for the negative values to be stacked together and for the positive values to be stacked together.

This issue causes the graphs to display misleading data, as seen in this example:

Without stacking:
![without_stacking](https://cloud.githubusercontent.com/assets/795598/5816747/a833b0d6-a0ac-11e4-8900-78371b3abb32.png)

With stacking:
![with_stacking](https://cloud.githubusercontent.com/assets/795598/5816754/bece5eea-a0ac-11e4-9ef9-273d48d46c2d.png)

<b>To reproduce:</b>
Parse Graphite data that has both positive and negative values for the same two metrics.
eg:
path.to.metric_1,1421667600,1421754000,600|60.0,30.0,-50.0,-40.0,20.0,50.0
path.to.metric_2,1421667600,1421754000,600|-40.0,-20.0,30.0,-20.0,-10.0,20.0

**Comment by torkelo** [comment]
Why do expect that? That is a very strange default stacking behavior. I mean a series could be positive and negative. The stacking behavior in grafana works the same as the stack() function works in graphite.

**Comment by imsnif** [comment]
In this context, the graph is financial - so there's a significant difference between profit and loss from a certain source, and they should not be grouped.
But even if I think about other more technical aspects, such as networking tx/rx which are sometimes displayed and stacked in this way (tx as negative and rx as positive) - it makes sense not to have one decremented from the other.

With this default behaviour, we could theoretically have a (more or less) flatlined graph with a lot going on that we wouldn't know about.

**Comment by torkelo** [comment]
well stacking stacks, there is no group by feature. That would be some other stacking mode that first analyses if a series is all negative and groups them. But by default this makes zero sense for stacking to do. 

And speaking of getting a theoretical flatline, that could in theory be precisely what you want if you stack two series (one negative, one positive) and see the diff. So what I am saying is I understand your case, but I think this requires a new stacking mode. If you get support (+1 votes), and pull request I would be happy to accept it :)

**Comment by imsnif** [comment]
Fair enough. I'll take a crack at it when I get the chance. Thanks!

**Comment by misterstrogg** [comment]
:+1:  This would be great for disk and network graphs. Anything counter-based is never going to have a negative value anyway, so scaling by -1 lets us use the other half of the Y axis. 

In Drraw, the stacking mode in templates is per query, and the choices are:
Don't Stack, (N)
Stack with only my own results, (Y)
Stack on the preceding query's results (+)

A crude workaround is to sum the series and not stack them, but then the detail is lost. (It's nice to be able to pick out an aberrant host in a stack of it's fellow pool members.)

**Comment by pavleec** [comment]
+1 a must-have for in/out interface traffic presentation

**Comment by bigunyak** [comment]
+1 from me too.
Would be really cool to have this feature and be able to build stack graphs for Traffic in/out and get something similar to this: http://play.grafana.org/?panelId=11&fullscreen
I bet it would be useful in tons of other cases when people use one graph to present data on both sides of the Y-Axis.

**Comment by torkelo** [comment]
This can actually be solved today with style override stack group (define a regex for the negative series and set stack to 2 or 3). the stack option is like a stack group. 

Added a negative-Y transform to master that will negate a series without affecting the min/max of the series in the legend (or the values in the tooltip).

![image](https://cloud.githubusercontent.com/assets/10999/8145388/8284dd08-1206-11e5-892b-47b4ab606fcb.png)

![image](https://cloud.githubusercontent.com/assets/10999/8145390/903e5474-1206-11e5-8bf8-6d09e788a695.png)

**Comment by sylr** [comment]
I've just hit this issue myself.

I'm trying to graph the delta of memory used by containers to display when my containers release memory if they ever do.

This leads each metric to either be positive or negative. If we try to stack them and one of them for a single point in time is not the same sign as the other this leads to a bogus display, e.g. :

![screenshot_6](https://user-images.githubusercontent.com/153052/43123766-753eb4d0-8f25-11e8-97ad-8b990f026554.png)

On that graph you can clearly see on the hover tooltip that the value of the only positive value does not match the Y axis value.

In that case it would really be useful to have a stacking mode by values instead of metric name with which we could stack positive & negative values with each other at each point in time.

Cheers.

**Comment by senuketo** [comment]
Just hit the same problem. Want to map positive and negative flows in one stacked bar chart. Tried to work it around with 2 different queries but cannot stack them by tag

**Comment by torkelo** [comment]
you can stack them separately using a regex series override

**Comment by senuketo** [comment]
@torkelo do you mean to use series override Y-negative? If so, no need as the outflow has negative values written in the measurement.
<img width="1389" alt="Screenshot 2019-09-19 at 15 42 46" src="https://user-images.githubusercontent.com/6332118/65244998-6bfb0880-daf4-11e9-9dbe-e22f286c38e4.png">
I've used series override to set colours for each group(for example HDD1 orange, HDD2 green). But when I have 2 different queries it displays the same group separately. I need the orange ones to be one below the other, same for the greens.

**Comment by micheleferrari01** [comment]
You can define 4 different stacks. A,B,C,D
So if you define one serie for positive value and another one for negative, you can associate positive one to default stack and negative one to stack A.
![2-stacks](https://user-images.githubusercontent.com/51374275/77093002-b0675280-6a0a-11ea-94dd-efce7654f15a.JPG)

I've also associated negative values to left Y, but it is not strictly required

**Comment by hkinks** [comment]
Not sure if I am doing something wrong or stumbled on a bug, but when following the suggestions here it fails to display one of the series:
![image](https://user-images.githubusercontent.com/1926790/122109613-3ba9e080-ce26-11eb-9ff9-bcb683f25337.png)
* Positive stack is nicely shown
* From negative stack one series is shown
* Second series is hidden, but when hovering I can see it is 'there' and correctly placed, but the bars are hidden. There is no bar style override etc.

**Comment by loneept** [comment]
> 

Got the same problem, did you figure it out ? I got 2 values from transformation, and whoever I put first in the transform is shown, but never the second (the point is here, but not the bar)

**Comment by micheleferrari01** [comment]
Could you please send a screen with settings of draw model?
Have you anchor neg test 2 and test 2 on right y axis?
Have you set a different stack for them?

Michele

**Comment by loneept** [comment]
Here is the graf :
![image](https://user-images.githubusercontent.com/5434412/165540264-eef5dfd5-028d-4bdd-ac05-994a1a96ba34.png)
As you can see, below, there is only the point for "commission", and only when I hoover.

I have a stack group for my positive income, and a stack group for my negative income.

Here are the 2 overrides I had to set up : 
![image](https://user-images.githubusercontent.com/5434412/165540611-8e75ea0b-5502-4c1f-9c84-bbde4d1981e1.png)

And a screen of the 2 transforms I had to set up : 
![image](https://user-images.githubusercontent.com/5434412/165540775-64b482f7-913b-4b2b-b092-4fb1a8dbb6a7.png)

Is this all the informations you need ?

Thanks !!

**Comment by leeoniya** [comment]
i re-implemented Grafana's stacking code in https://github.com/grafana/grafana/pull/47373 with a few follow-up fixes, the latest one landed a couple hours ago (https://github.com/grafana/grafana/pull/48321) and will be released with 8.5.1 tomorrow.

we do a lot of things automatically now, which should require minimal additional config. please try v8.5.0 or v8.5.1 without any special overrides or hacks. the pos/neg and unit grouping should happen automatically.

let me know how the new implementation works (or doesnt ;)

**Comment by sylr** [comment]
@leeoniya it's improving but:
<img width="1728" alt="Fullscreen_28_04_2022_09_12" src="https://user-images.githubusercontent.com/153052/165697609-eda9da29-3005-49da-9619-34cdefc5bdfa.png">
<img width="1728" alt="Fullscreen_28_04_2022_09_14" src="https://user-images.githubusercontent.com/153052/165697915-87de3e26-be27-4170-8046-6f463355188b.png">

**Comment by leeoniya** [comment]
yeah, mixing positive and negative values in a single series won't work well. in the timeseries panel it has to work for all drawStyles (bars, lines, smooth, stepped) but this scenario is only realistically renderable for bars. e.g. i have no idea how the situation below can be rendered as stacked line/area with series randomly swapping pos/neg sides:

![image](https://user-images.githubusercontent.com/43234/165734362-b6c90d03-6231-4cba-ab98-4aacf49551b5.png)

**Comment by leeoniya** [comment]
yes, it's supposed to be fixed. please open a new issue with screenshots and your data + dashboard config.

**Comment by godcanfly** [comment]
I have report a new issue, it can fix the issue if all data is negative but not sometime it is negative sometime is postive, and all the overide method cann't handle this situaion. 
https://github.com/grafana/grafana/issues/51011
![image](https://user-images.githubusercontent.com/17425165/174246270-b0281d06-a9fb-4699-8cff-54548309db15.png)
