### ISSUE TITLE
Datasource search box does not return all matching results

### ISSUE THREAD

**Issue by m-a-leclercq** [grafana/grafana#13601]
Hi ! 

### What Grafana version are you using?
5.2.2
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
RHEL 7.1
### What did you do?
Open the Datasource page  (/datasources) and search for datasource name pattern
Try to filter by a part of the name of the datasource
### What was the expected result?
Find all datasources containing the name pattern
### What happened instead?
Only some of the datasources containing that name are showing

**We have a large number of datasources (144)**

Here is when I search using the browser for a list of datasources containing the "system" keyword
![image](https://user-images.githubusercontent.com/13354100/46745817-18f6bf80-ccae-11e8-9f70-2d75cae9b560.png)

Here is what happens when I search for "system" using the search bar in grafana : 

![image](https://user-images.githubusercontent.com/13354100/46745466-6161ad80-ccad-11e8-9fe2-88cdde240d28.png)

**Comment by torkelo** [comment]
This should be fixed in v5.3
