### ISSUE TITLE
Investigate having lines render dots when no connecting line can be made 

### ISSUE THREAD

**Issue by jsferrei** [grafana/grafana#13605]
### What Grafana version are you using?
5.3.0
### What datasource are you using?
Heroic (though problem exists for all datasources)
### What OS are you running grafana on?
Ubuntu
### What did you do?
Made a linegraph with points drawmode set to "off" with a query whose result include disjointed series. Example:
`{datapoints: {points: [null, null, 1539190559, 2, null, null, 1539190560, 1, 1539190562, 1, 1539190563, 1]`
### What was the expected result?
I would expect all of my data to be plotted. 
### What happened instead?
Because the first point is disjointed from the remainder of the points, it is not plotted. The current workarounds are to turn points drawmode "on" or to add a series override to plot null points as 0, null, or connected. This is not ideal because they both require the user to notice the point is not visible. Also, the first workaround can lead to unnecessary rendering overhead. The second solution results in a misleading display.

Missing point:
![screen shot 2018-10-10 at 1 01 38 pm](https://user-images.githubusercontent.com/905080/46753023-b640fc00-cc8c-11e8-8113-4b49bafca53e.png)
![screen shot 2018-10-10 at 1 01 50 pm](https://user-images.githubusercontent.com/905080/46753025-b8a35600-cc8c-11e8-9698-5b060ee49154.png)

**Comment by torkelo** [comment]
The is an option in graph display tab called null mode or null value , set this to connected to ignore null values. The default of showing gaps could be argued should be changed as many run into this issue, but if we default to ignore nulls then periods of missing data could missed

**Comment by jsferrei** [comment]
I think I was not clear enough in my  description -- the issue is not trying to join disjointed series or to ignore nulls. The issue is when you have a non-null point surrounded by null points before and after, it does not display unless you turn on the "Points" draw mode.

**Comment by jsferrei** [comment]
@torkelo do you have any more thoughts on this now that I've explained the issue a little better?

**Comment by torkelo** [comment]
yes!
