### ISSUE TITLE
Backend plugin response size limited is 4MB

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#13612]
Backend plugin use GRPC to return response.
And the response size limit is 4MB.

If too many time series hit for query, the response size could exceeds the limit.
https://github.com/grafana/grafana/issues/6841#issuecomment-404849188

FYI to @daniellee .

**Comment by mtanda** [comment]
Grafana core plugin doesn't use GRPC, so there is no problem.
If Azure datasource or some other datasource, start to use backend plugin, it may cause problem.

**Comment by marefr** [comment]
@briangann I know you looked into something related or did you actually fix this?

**Comment by kylebrandt** [comment]
This is the default limit in gRPC. The default limit can be increased, but this is not negotiated.

Options:
 - Implement chunking that keeps it with in the limit
 - Increase the limit (although that just moves the problem to a higher limit)

**Comment by marefr** [comment]
Should have been fixed by #19454 since it has this PR included https://github.com/hashicorp/go-plugin/pull/117
