### ISSUE TITLE
Bug: Alert Notification Mail image problem

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#13616]
### What Grafana version are you using?
v5.3.0 

### What datasource are you using?
MariaDB, InfluxDB

Bug:

- Since the new update, the images of the Graphs are not showing well in the notification emails.
- Number format of `avg` is wrong.

Version of the v.5.3.0:
![201810110959b](https://user-images.githubusercontent.com/2911588/46789464-c87a7300-cd3c-11e8-9d61-26d7a6d8a682.png)

Version of the v.5.2.0:
![201810110959a](https://user-images.githubusercontent.com/2911588/46789436-b3054900-cd3c-11e8-88a0-99f9bd5b6f5b.png)

**Comment by torkelo** [comment]
might be related to this change:
https://github.com/grafana/grafana/commit/776f55dc803a1c22c880b826a231f65fde1a14d4#diff-827c826d03182bbb91968879a2e740f2

**Comment by marefr** [comment]
Seems to only happen when legend is placed to the right as a table, not at the bottom.

**Comment by marefr** [comment]
> might be related to this change:
> 776f55d#diff-827c826d03182bbb91968879a2e740f2

Confirmed related to this change

**Comment by sanchomuzax** [comment]
Working, thank you!
