### ISSUE TITLE
gitignore confused

### ISSUE THREAD

**Issue by superbool** [grafana/grafana#13625]
In .gitignore  file 
```
/pkg/extensions

/vendor/**/appengine*
```
but actually the directory */pkg/extensions* and */vendor/golang.org/x/oauth2/google/*
![image](https://user-images.githubusercontent.com/8575470/46812711-de714d80-cda7-11e8-9040-6f55fc26065a.png)
are not empty.
It confused me.  but why?
Because when I use my own gitlib clone from https://github.com/grafana/grafana, I push files that ignore files not pushed, when others download and build, it will be error:
![image](https://user-images.githubusercontent.com/8575470/46813035-8a1a9d80-cda8-11e8-9e7d-58ccb97fef71.png)
![image](https://user-images.githubusercontent.com/8575470/46813057-943c9c00-cda8-11e8-98d5-d155b317a98e.png)

**Comment by torkelo** [comment]
not sure I understand, are you adding files to pkg/extensions ? the pkg/extensions package is where we symlink in our enterprise backend code, which is why it exists. 

Not sure about the appengine ignore. Will ask the person who added that ignore.

**Comment by superbool** [comment]
@torkelo yes I copied the *pkg/extensions/main.go*  file to my own repertory, everything to be ok.
