### ISSUE TITLE
Trickster fast-forward problem

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#13622]
### What Grafana version are you using? 
v5.3.0
### What datasource are you using? 
Thanos + Trickster AS prometheus
### What OS are you running grafana on?
docker official image

I believe a Trickster feature confuse grafana and provokes display problems: https://github.com/Comcast/trickster/issues/92

**Comment by sylr** [comment]
@torkelo I gave you a link with the data in a DM on gophers.slack.com .

Graph settings:
- step: 2m
- From: now-15m
- To now

**Comment by bergquist** [comment]
Seems like this have been solved in https://github.com/Comcast/trickster/issues/92
Ping me if im wrong and Ill reopen the issue
