### ISSUE TITLE
Variables: Prometheus: Nesting variables leads to exception and missing refresh

### ISSUE THREAD

**Issue by sbrandtb** [grafana/grafana#13628]
### What Grafana version are you using?
5.3.0

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Official Docker image

### What did you do?
Added two template variables:

* "namespace": Query: `label_values(namespace)`, refresh: "On dashboard load"
* "app": Query: `query_result(kube_pod_labels{namespace="$namespace"})`, regex `/.*label_app="([^"]+)".*/`, refresh: "On dashboard load"

### What was the expected result?
In `app` a list of applications in the according namespace, gets refreshed when `namespace` changes.

### What happened instead?
The variable list gets initialized ("preview of values" and dropdown list on dashboard) with the expected result, but:

* a Javascript exception occurs: `Template variables could not be initialized: e is undefined` in Firefox, `Template variables could not be initialized: Cannot read property 'inputEdges' of undefined` in Chromium (red error pop-up on top right)
* the list of `app` values does not get refreshed when `namespace` is changed. If one changes to "on time range change", the variable is indeed refreshed.

So, the exception is unexpected and it looks like Grafana does not understand `app`s dependency from the `namespace` variable.

**Comment by Gatses** [comment]
This error also occurs:

> Template variables could not be initialized: Cannot read property 'inputEdges' of undefined

But only in some dashboards.

**Comment by conet** [comment]
I'm also getting this in some dashboards (seems to be related to templating variables and not datasource since I encountered it using elasticsearch):
`TypeError: Cannot read property 'inputEdges' of undefined`

**Comment by conet** [comment]
> some dashboards

After a bit more debugging this seem to be every dashboard that has variables which depend on another variable.

**Comment by conet** [comment]
Seems that it was introduced by #12959.

**Comment by marefr** [comment]
@conet sbrandtb

I've setup a demo dashboard [here](https://play.grafana.org/d/PDAxhE1mz/nested-variables-13628?orgId=1) with two template variables according to issue description. But I'm not able to reproduce the error - have tried with Chrome 69.0.3497.100, Firefox 62.0 and Chromium 69.0.3497.81.

Please let me know if I've configured the demo dashboard incorrectly and/or if you're able to reproduce the error using this demo dashboard.

Please include a full dashboard JSON document where you experience this problem.

Thanks

**Comment by marefr** [comment]
Now I was able to reproduce the following error

```
TypeError: Cannot read property 'inputEdges' of undefined
    at e._linkTo (dag.ts:39)
    at e.link (dag.ts:54)
    at dag.ts:199
    at Array.forEach (<anonymous>)
    at dag.ts:198
    at Array.forEach (<anonymous>)
    at e.link (dag.ts:197)
    at interval_variable.ts:20
    at Array.forEach (<anonymous>)
    at interval_variable.ts:32
(anonymous) @ angular.js:14700
(anonymous) @ angular.js:11142
$apply @ angular.js:18528
(anonymous) @ angular.js:27346
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
```

Given the [demo](https://play.grafana.org/d/PDAxhE1mz/nested-variables-13628?orgId=1) dashboard. I went into settings -> Variables -> Changed order of the variables. Then changing job results in above error. Did you change order of your variables now or possibly did it historically?

Here's another [demo](https://play.grafana.org/d/C1SgwP1iz/nested-variables-13628-reorder-variables?orgId=1) dashboard where the order have been switched.

**Comment by conet** [comment]
Yes, that is it, I was trying to reproduce it in [this demo](https://play.grafana.org/d/1q_sUP1iz/issue-13628) without luck, then saw you last message, change the order and there it was.
And yes, I probably changed the order of the variables in my production dashboards where I saw this.

**Comment by marefr** [comment]
@conet thanks for confirming. Will look into why this happens and possible fix

**Comment by conet** [comment]
While doing that I found another error in [this demo](https://play.grafana.org/d/1q_sUP1iz/issue-13628):
```
angular.js:14700 SyntaxError: Unexpected number in JSON at position 61
    at JSON.parse (<anonymous>)
    at Object.ge [as fromJson] (angular.js:1471)
    at e.metricFindQuery (datasource.ts:445)
    at e.metricFindQuery (query_variable.ts:172)
    at query_variable.ts:141
    at angular.js:17051
    at angular.js:17095
    at c.$digest (angular.js:18232)
    at t.$apply (angular.js:18531)
    at HTMLAnchorElement.<anonymous> (angular.js:27346) "Possibly unhandled rejection: {}"
```
by opening variable `host1` and selecting tag `server"21`.

**Comment by conet** [comment]
> Will look into why this happens and possible fix
Thanks, will be looking forward for the fix, I hope it's simple enough so I can patch 5.3.0 till 5.3.1 is released 😄.

**Comment by conet** [comment]
> It was [quite simple fix](https://github.com/grafana/grafana/pull/13651/files#diff-3ee1062af1b287d918446eb1d77d92e6). Don't know how I was thinking when originally implemented #12959 😄
> 
> Hopefully we put out a v5.3.1 sometime next week.

Thanks, worked like a charm, I patched our current version (running in docker) using this command line:
```
sed -i -e 's/e.prototype.createGraph=function(){var e=this,t=new le;return this.variables.forEach(function(a){t.createNode(a.name),/e.prototype.createGraph=function(){var e=this,t=new le;this.variables.forEach(function(a){t.createNode(a.name)});return this.variables.forEach(function(a){/' /usr/share/grafana/public/build/5.770fad3a626c70250d5f.js
```

I only took from the patch the part which was essential to fix the bug.

**Comment by conet** [comment]
> this demo



> > While doing that I found another error in [this demo](https://play.grafana.org/d/1q_sUP1iz/issue-13628):
> > ```
> > angular.js:14700 SyntaxError: Unexpected number in JSON at position 61
> >     at JSON.parse (<anonymous>)
> >     at Object.ge [as fromJson] (angular.js:1471)
> >     at e.metricFindQuery (datasource.ts:445)
> >     at e.metricFindQuery (query_variable.ts:172)
> >     at query_variable.ts:141
> >     at angular.js:17051
> >     at angular.js:17095
> >     at c.$digest (angular.js:18232)
> >     at t.$apply (angular.js:18531)
> >     at HTMLAnchorElement.<anonymous> (angular.js:27346) "Possibly unhandled rejection: {}"
> > ```
> > by opening variable `host1` and selecting tag `server"21`.
> 
> Could you please open a separate issue for this? Thanks

Seems like there is already one #5314.

**Comment by marefr** [comment]
Ok great. Thanks!
