### ISSUE TITLE
JavaScript error on semicolon-separated influx SELECT queries 

### ISSUE THREAD

**Issue by spads-spads** [grafana/grafana#13623]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.3.0
### What datasource are you using?
influxdb
### What OS are you running grafana on?
Ubuntu 16.04.5 LTS
### What did you do?
created a graph with two influx SELECT statements separated by a semicolon
### What was the expected result?
both queries rendered in the same graph as a single dataset
### What happened instead?
The JS error message `o is undefined` with the following stack trace:
```javascript
1261/ur</e.prototype.query/<@https://showback.admin.canonical.com/public/build/5.770fad3a626c70250d5f.js:10:232268
l/</<@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:92198
l/<@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:92043
$digest@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:97575
$apply@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:99590
$applyAsync/r<@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:99735
h@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:33036
cn/this.$get</</i.defer/n<@https://showback.admin.canonical.com/public/build/vendor.770fad3a626c70250d5f.js:130:34396
```

**Comment by spads-spads** [comment]
I had thought this was caused by https://github.com/grafana/grafana/issues/4533 but the symptoms are different, and no amount of encoding the semicolon will help.  I saw this in both 5.2.1 and upgraded to 5.3.0 to verify it still occurs.

**Comment by marefr** [comment]
Please include the queries you're trying to use. Have you tried using two separate queries by using the `Add Query` button?

**Comment by spads-spads** [comment]
`SELECT sum("cost_usd") / 10 FROM "billed_totals" WHERE ("dept" =~ /^$Department$/ AND "month" =~ /^$Month$/ AND "resource" =~ /^$Resource$/ AND "service" = 'Disk') AND $timeFilter GROUP BY time(1d), "dept" fill(0) ; SELECT sum("cost_usd") FROM "billed_totals" WHERE ("dept" =~ /^$Department$/ AND "month" =~ /^$Month$/ AND "resource" =~ /^$Resource$/ AND "service" = 'RAM') AND $timeFilter GROUP BY time(1d), "dept" fill(0)`

The queries work when added as A/B/C etc via "Add Query", but they appear as discrete items on the graph.  I am breaking them out only so that I can separate out scaling factors (that is, RAM costs more per GB than Disk, hence the `/ 10` in the above just as a test to make it visible).  But when I do multiple queries, I don't see the totals per `$tag_dept` but rather one for each combination of query and dept value.

**Comment by marefr** [comment]
Thanks. I temporarily made a change locally so that the javascript error doesn't happen, but the result is still the same as using A/B/C queries, see screenshot.

![image](https://user-images.githubusercontent.com/1668778/46813664-6c811000-cd77-11e8-8289-fd018422a7a4.png)

What is needed is "merge" of multiple series with the same name. Unsure if the "merge" has ever worked why I'm thinking that it may be a new specific feature request instead - what's your thought? Plus this issue will target fixing the javascript bug.

**Comment by marefr** [comment]
Problem occurs at this row: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts#L94

Problem is that `data.results` (query response coming back from InfluxDB) may be of greater length than the `queryTargets` (queries defined in Grafana dashboard panel). One way of fixing this would be to check if [target](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts#L93) is valid or not and if not continue looping backwards until a valid target is found. This will then support having one query in Grafana dashboard panel that contains infinite InfluxDB queries/responses.

**Comment by spads-spads** [comment]
You're correct in that the resulting behaviour is identical to multiple queries.  I only noticed this last night when I was poking through the query explorer and spotted the semicolons in the recorded query itself!

I'll open a new request for merged data.  Thanks!

**Comment by torkelo** [comment]
is there a reason to support multiple queries in one query field? Closing this for now...
