### ISSUE TITLE
Allow treating missing data as 0 for alerts

### ISSUE THREAD

**Issue by fitzoh** [grafana/grafana#13636]
Grafana 5.2.1
Prometheus datasource
I'm attempting to alert on the following query
```
(
  (connect_services_production_uri:http_server_requests_seconds_bucket:p95rate1m
  -
  connect_services_production_uri:http_server_requests_seconds_bucket:p95rate1m offset 1d) > 0
)
/
connect_services_production_uri:http_server_requests_seconds_bucket:p95rate1m offset 1d

AND connect_services_production_uri:http_server_requests_seconds_bucket:p95rate1m > .2
```
There are some recording rules involved, but the gist of this query is that it returns the % change in p95 latency between yesterday and today (`(new-old)/old`), but the time series is filtered to only show  values where there is an increase in latency, and the current response time is > 200ms.

I'm attempting to alert with this with the following configuration (when the median percent change is > 200% for a 15 minute period):
<img width="648" alt="screen shot 2018-10-11 at 11 07 31 pm" src="https://user-images.githubusercontent.com/131809/46845701-7bcd8100-cdaa-11e8-8355-d55cb0fa3deb.png">

Unfortunately this ends up alerting given the following data:
<img width="621" alt="screen shot 2018-10-11 at 11 09 10 pm" src="https://user-images.githubusercontent.com/131809/46845747-b1726a00-cdaa-11e8-8d29-664c6fee1358.png">

Even though there is no data for the majority of the 15 minute period, an alert still triggers because the median of the values that are present are greater than the alerting threshold.

It would be nice if there was an additional knob in the alert configuration to allow treating missing data as 0's.

**Comment by torkelo** [comment]
what does Prometheus return for your query? (given the step you use). ?

**Comment by fitzoh** [comment]
Sorry for the delay, returned data:
```{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/api/v1/query_range?query=((%0A%20%20(connect_services_production_uri%3Ahttp_server_requests_seconds_bucket%3Ap95rate1m%0A%20%20-%0A%20%20connect_services_production_uri%3Ahttp_server_requests_seconds_bucket%3Ap95rate1m%20offset%201d)%20%3E%200%0A)%0A%2F%0Aconnect_services_production_uri%3Ahttp_server_requests_seconds_bucket%3Ap95rate1m%20offset%201d)%20%3E%202%0A%0AAND%20ON%20()connect_services_production_uri%3Ahttp_server_requests_seconds_bucket%3Ap95rate1m%20%3E%20.2&start=1539243075&end=1539247815&step=15"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "uri": "/dtp/alerts/"
          },
          "values": [
            [
              1539246855,
              "20.15481186535418"
            ]
          ]
        },
        {
          "metric": {
            "uri": "/opportunities/"
          },
          "values": [
            [
              1539246855,
              "287.2012685128449"
            ],
            [
              1539247305,
              "51.018267059136875"
            ],
            [
              1539247320,
              "90.17819003922831"
            ],
            [
              1539247350,
              "144.49640779838984"
            ]
          ]
        },
        {
          "metric": {
            "uri": "/opportunities/metrics"
          },
          "values": [
            [
              1539246855,
              "63.000000903123556"
            ],
            [
              1539246870,
              "63.000000903123556"
            ],
            [
              1539247320,
              "3.9620253589172023"
            ]
          ]
        }
      ]
    }
  }
}```

**Comment by davkal** [comment]
Should this be done in core?

**Comment by davkal** [comment]
As long as Prometheus has no means of sending the 0 values for the AND-ed out datapoints, this can't really be done.
