### ISSUE TITLE
http server stuck

### ISSUE THREAD

**Issue by xiejiangzhi** [grafana/grafana#13637]
### What Grafana version are you using?
docker grafana/grafana:5.3.0

### What datasource are you using?
prometheus, influxdb

### What OS are you running grafana on?
docker

### What did you do?
not do any, run grafana and wait about 1 minutes, http server is stuck.  when I send a http request, keep waiting for response. But I can get a response if I send request to /metrics. other path(include /) is stuck.

I tried send a request to localhost:3000 in container, I also cannot get a response.

### What was the expected result?
get a http response

### What happened instead?
cannot get a response when a send a http request

### Include raw network request & response: 
 
I set the log level to debug, not found any error and new request log. some `alerting.scheduler` still output. 

```
t=2018-10-12T05:41:29+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=HEAD path=/ status=302 remote_addr=10.255.0.27 time_ms=17 size=0 referer=
t=2018-10-12T05:41:30+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=HEAD path=/ status=302 remote_addr=10.255.5.51 time_ms=17 size=0 referer=
t=2018-10-12T05:41:30+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=HEAD path=/ status=302 remote_addr=10.255.5.51 time_ms=18 size=0 referer=
t=2018-10-12T05:41:31+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-10-12T05:41:41+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-10-12T05:41:51+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2018-10-12T05:42:01+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```

**Comment by torkelo** [comment]
what's the memory and cpu usage of the process? What is available on the machine (when it hangs)?

**Comment by marefr** [comment]
What version did you upgrade from or is it a fresh install of Grafana v5.3?

**Comment by xiejiangzhi** [comment]
@torkelo  it used about 10% CPU and less 200M memory. and that machine has 1G memory available.
My grafana machine is 1 core 2G.

@marefr I got this problem on 5.2.4, then I upgrade to 5.3. I still got it.

**Comment by xiejiangzhi** [comment]
Maybe we add some error information to log next version. We got a error but the log didn't output any error info.

**Comment by xiejiangzhi** [comment]
@torkelo  My db isn't sqplite3, it's postgres.

> How did you know it got an error, exit code?
I guess it is a error. in fact, I cannot get any information from log.  `alerting.scheduler` and `/metrics` still working, but other http requests always block.

**Comment by MaxDiOrio** [comment]
Hmm...I'm starting to see this with one of my K8S instances.  I was having problems with it stuck on:

10/11/2018 12:21:29 PM t=2018-10-11T16:21:29+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
10/11/2018 12:21:29 PM t=2018-10-11T16:21:29+0000 lvl=info msg="Starting DB migration" logger=migrator

Then I let it go for a couple of days and it seems to have progressed past this message.  But now it's in the same state yours is in.  I'm wondering if there is some major performance issues on the DB.  I'm working with our storage provider on a locking issue that's cropped up, but I haven't seen any performance issues in any other of my NFS hosted persistent volumes.

**Comment by torkelo** [comment]
If your using NFS drives Sqlite db is not our recommenced db of choose (assuming your using it) MySQL and Postgres is recommend

**Comment by xiejiangzhi** [comment]
@torkelo thank you very much. I think you're right. I using NFS + SQLite.  So, could we print some error info to log, maybe someone get the same problem. 
Can we get some error from SQLite for this case?

**Comment by marefr** [comment]
@xiejiangzhi now I'm confused. You said above that you didn't use sqlite and used postgres, but now you're saying that you're using sqlite.

**Comment by xiejiangzhi** [comment]
@marefr Sorry for that, it's my mistake.  it seems that the delete line didn't working. I updated it..
