### ISSUE TITLE
custom templating variable cannot contain space

### ISSUE THREAD

**Issue by czchen** [grafana/grafana#1363]
When setting possible value of custom templating variable, the UI says `Values seperated by comma`. However, if we provide the value like `a b, c`, it will set possible value as `a`, `b`, and `c` instead of `a b`, and `c`.

Current we can workaround it by exporting to JSON, modifying, importing from JSON. It would be nicer if we can set it through UI, thanks.

**Comment by torkelo** [comment]
Why are you having a space in a template variable? graphite and influxdb metric paths do not support space. I could fix it but both space and "," works and others might have taken advantage of the fact that space also works. But I would be happy to make "," the only split char but I would like to know the reason more.

**Comment by czchen** [comment]
influxdb can use white space as part of its series name, as long as it is [quoted or escaped](http://influxdb.com/docs/v0.8/api/query_language.html).

Our influxdb is solely used for grafana to display metrics for different customers. We use templating to achieve the goal. A templating variable is used to store customer name. In this configuration, If we list down all possible value of templating variable, we will have an easy to use UI menu for different customer. In order to display customer name in UI menu, we set part of the influxdb series name as customer name. Since customer name contains white space, we have series name containing white space, and templating variable containing white space, too.

**Comment by torkelo** [comment]
Fixed in master

**Comment by czchen** [comment]
@torkelo Thanks for the fix.
