### ISSUE TITLE
Time duration format

### ISSUE THREAD

**Issue by franciscocpg** [grafana/grafana#13635]
Please include this information:
### What Grafana version are you using?

Grafana v5.2.3 (commit: cf4c090) 

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Linux Antergos

### What did you do?

When I select `Unit: duration (ms)` (**Left Y** on image below):
![image](https://user-images.githubusercontent.com/3680556/46833676-a229f700-cd7f-11e8-8e32-10da8f7d0d85.png)

I see values like this:
![image](https://user-images.githubusercontent.com/3680556/46833738-d7364980-cd7f-11e8-9cd3-29df726e3a22.png)

### What was the expected result?

I want to see, for example:`23m:12s`. Is there an option currently to format like this?

### What happened instead?

I see the long `23 minutes, 12 seconds`.

### If related to metric query / data viz:

n/a

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
n/a

**Comment by torkelo** [comment]
I would recommend you use the time (ms) format it's for shorter (graph y axis) display. It will show it as 
12.2m

We dont have a middle form that does what duration does but in clock format

**Comment by franciscocpg** [comment]
Hi @torkelo 
Thanks for your response. 

I know about `time (ms)` but that is not what I'm looking for.

Can we keep this open so I can propose a PR for that?

Maybe a new Unit within `time`called `Clock (ms)`?
