### ISSUE TITLE
Valid CloudWatch percentile statistic queries not strictly of `p##.##` format throw error

### ISSUE THREAD

**Issue by apalaniuk** [grafana/grafana#13633]
### What Grafana version are you using?
5.3.0

### What datasource are you using?
AWS CloudWatch

### What OS are you running grafana on?
Windows 10

### What did you do?
After updating from 5.2.4 -> 5.3.0, some AWS percentile statistics no longer work if not of specific format `p##.##` (eg. `p99.7`) [due to strict regex](https://github.com/grafana/grafana/blob/5f69854e2a9e40fedb059f3118d7761727c39537/public/app/plugins/datasource/cloudwatch/datasource.ts#L50).

### What was the expected result?
Previously working queries would continue working.

### What happened instead?
Queries stopped working (threw `Invalid Extended Statistics` error)

**Comment by stephenliang** [comment]
@torkelo Will this change be backported to 5.3? This would prevent an upgrade from 5.2->5.3 without changing all the dashboards that reference metrics without the `.##` at the end.

**Comment by marefr** [comment]
@stephenliang we consider including it in v5.3.2
