### ISSUE TITLE
Explore: scroll wide table independently of query box and widgets?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13642]
When you do a query that returns lots of labels (try `container_cpu_usage_seconds_totalbox`) it generates a table thats very wide.  When you horizontally scroll, the query box goes off to the left:

<img width="1379" alt="screen shot 2018-10-12 at 11 37 55" src="https://user-images.githubusercontent.com/444037/46858142-4b6dfd00-ce13-11e8-94c5-b2cddb405695.png">

**Comment by davkal** [comment]
Addressed in #13712
