### ISSUE TITLE
Please display merged data sources.

### ISSUE THREAD

**Issue by spads-spads** [grafana/grafana#13645]
This is a feature request as mentioned in https://github.com/grafana/grafana/issues/13623

Please include this information:
### What Grafana version are you using?
5.3.0
### What datasource are you using?
influxdb 1.6.3
### What OS are you running grafana on?
Ubuntu 16.04.5 LTS
### What did you do?
Graphed multiple queries on the same measurement, grouped by the same tag, with aligned timestamps for both results.
### What was the expected result?
A single stacked graph with the tag-grouping shared by all queries
### What happened instead?
Multiple results for each of the tag values, one for each query. 
![Marcus Efraimsson's demonstration from 13623](https://user-images.githubusercontent.com/1668778/46813664-6c811000-cd77-11e8-8289-fd018422a7a4.png)

**Comment by spads-spads** [comment]
For reference, this was Marcus's analysis of the situation.
> What is needed is "merge" of multiple series with the same name. Unsure if the "merge" has ever worked why I'm thinking that it may be a new specific feature request instead - what's your thought? If you agree I would suggest you to open a new feature request for the "merge" of multiple series with the same name functionality.

**Comment by torkelo** [comment]
you need to do this in the query, so that the query returns a single series (if that is what you want)

**Comment by spads-spads** [comment]
Sadly, influxdb does not support this. I have no mechanism to do this in the query.

**Comment by torkelo** [comment]
ok, that's sucks, then I am sorry, but I think this should be a feature request for InfluxDB
