### ISSUE TITLE
SingelStat Divide value 

### ISSUE THREAD

**Issue by tomerikko** [grafana/grafana#1364]
hi, i have a value that comes in kb
i need it in mb
so i need to divide it by 1024, but i couldnt find the function for it.
any advise ?

![image](https://cloud.githubusercontent.com/assets/10564814/5832999/27532de8-a156-11e4-9b03-6bd14884d802.png)

Thanks, 
Tomer.

**Comment by tomerikko** [comment]
OK, So i found a function named "scale" that looks like i can tweak it to do what i need.
Do we have a better solution or should i use this ?

![image](https://cloud.githubusercontent.com/assets/10564814/5833079/6813319c-a157-11e4-9615-501ed570c10d.png)

**Comment by torkelo** [comment]
that is a good solution. In grafana 2.0 there is a new Unit selector that includes kilobytes format as well.
https://github.com/grafana/grafana/issues/1331

**Comment by tomerikko** [comment]
Great.
Thank you.
