### ISSUE TITLE
Show Timestamp of Current value in Legend

### ISSUE THREAD

**Issue by ThomasChr** [grafana/grafana#13646]
I want to have the possibility to include the timestamp of the current value in Graph panel legend. I find this feature particular usefull to see at a glance if the value really is recent. Here's an image visualizing what I want:

![current_with_timestamp](https://user-images.githubusercontent.com/13014163/46865707-c4bf1d00-ce1e-11e8-92e5-4ff2baaca638.png)
![current_with_timestamp2](https://user-images.githubusercontent.com/13014163/46867957-05bb2f80-ce27-11e8-9a03-dcf35cfc141a.png)

**Comment by marefr** [comment]
Could you please change your issue description so that it instead explains what feature you want. Basically some more context to the title needed. Now it kind of looks like a bug report. Thanks

**Comment by ThomasChr** [comment]
Hello marefr, 

I added the feature to show the timestamp of the current value in the legend. I though I need an issue to which I can link my PR.

**Comment by marefr** [comment]
@ThomasChr yes I saw that - that's perfect. I updated the issue description now.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
