### ISSUE TITLE
Temporary global annotations/crosshairs

### ISSUE THREAD

**Issue by Fank** [grafana/grafana#13654]
Please include this information:
### What Grafana version are you using?
5.3.0
### What datasource are you using?
influxdb
### What OS are you running grafana on?
docker

It would be nice to have the option to add temporary annotations or something like "freezed" crosshairs, for all graphs in the current dashboard, and this will or should disappear after reload or some other ways.

We have a have this dashboard https://grafana.com/dashboards/8208 and on the first graph "Sim Speed" we see performance issues, and to identify the issues we remember the times when something changed, than we compare the remembered time with each graph to identify the performance issue.

And it would be nice to have an option to create some temporary marker, which appears on all graphs to easily check it, this would save so much time.

And it should be able to create them for non logged in users too.

**Comment by aocenas** [comment]
@Fank I know this is old issue, but you can enable a shared crosshair  cursor in a dashboard so it will show your cursor position on timeline across all the panels. I guess that would work here. Going to close this considering that and that this is old issue without much traffic, but feel free to reopen.
