### ISSUE TITLE
Non-deterministic SimpleJson Variable queries

### ISSUE THREAD

**Issue by stevecalvert** [grafana/grafana#13658]
**What Grafana version are you using?**
Grafana v5.2.4 (0bbac5c)

**What datasource are you using?**
SimpleJson (SJ)

**What OS are you running grafana on?**
Ubuntu 17.03

**What did you do?**
Created a dashboard with 4 variables, var1..var4, with a chain of dependence between them (var1 dependent on var2 which in turn dependent on var3, etc)

**What was the expected result?**
var1 would not be evaluated until var2 query had run, which in turn would wait for response to var3 query, etc

**What happened instead?**
The behaviour does not seem to be deterministic.  Have seen out of order queries and also dependent queries being issued seemingly in parallel.  When this happens, the parameter passed to a query seems to be a string literal, so, for example, rather than evaluating the query for $var2, the actual string '$var2' is passed as the parameter for the var1 query 

The order of variables can be specified by the user on the Variables page but this appears to only affect the order in which the drop down variable selections are placed on the dashboard.  Perhaps this same ordering could be used to strictly define the ordering of SimpleJson queries? Or maybe there could be a separate control to disable parallel query requests and enforce in-order querying?

Note, I raised [a related issue](https://github.com/grafana/grafana/issues/13600), which is linked to a bug in the Regex handling for Grafana variables.  But here, the problem of non-deterministic queries is seen though even when the query parameters have the $var syntax (not $var:csv, or similar)

**Comment by torkelo** [comment]
you need to start with top level variable (the top of the dependency chain), so the variable with no dependencies should go first. 

Unable to replicate this in v5.3  (we have worked on improving the dependency resolution and reducing the number requests triggered by variable changes when the dependency graph is complex)

![image](https://user-images.githubusercontent.com/10999/46901351-25e40080-ceb2-11e8-83ab-493c042dff21.png)

https://play.grafana.org/d/U-B2aUJmk/4-variable-chain?orgId=1&var-apps=fakesite&var-servers=web_server_01&var-metrics=requests&var-metricType=count
