### ISSUE TITLE
Empty alert list when pushing dashboard with API

### ISSUE THREAD

**Issue by rnsc** [grafana/grafana#13653]
Please include this information:
### What Grafana version are you using?
5.2.3 to 5.3.0
### What datasource are you using?
influx and elasticsearch
### What OS are you running grafana on?
official grafana docker image
### What did you do?
Pushed a dashboard that contains alerts through the API.
### What was the expected result?
When calling "api/alerts?dashboardId=myDashboardUID" I'm expecting the list of alerts to be shown.
### What happened instead?
It returns "[ ]".
The panels in the dashboard have a grey heart next to the label of the panel.

Side note: If I then save the dashboard in the UI without even changing anything, then the alert list gets populated.

Am I missing something? Is this the default behavior?
If yes, will my alerts still get triggered when the state changes?
I tested this on a dashboard with recurring notifications (5.3.0) and the hearts on all panels stayed grey, it's only when I saved that I started receiving emails again.

**Comment by torkelo** [comment]
what api are you using to save the dashboard? Does the panels have ids in the json model?

**Comment by rnsc** [comment]
@torkelo I'm using this:
`/api/dashboards/import`
I'm changing the "id" to null before importing it, is that something I shouldn't do?

**Comment by torkelo** [comment]
no panels need unique ids. 

Dont use the import api, that is only for UI import workflows.

use the normal save/create dashboard api:
http://docs.grafana.org/http_api/dashboard/#create-update-dashboard

**Comment by torkelo** [comment]
it allows for full dashboard, it's the same api used by the UI when you create a new dashboard or update a dashboard. 

the import api is special as it's for importing dashboards from other systems via the UI and supports datasource selection and mapping so the importer can specify what local datasources should be used.

**Comment by rnsc** [comment]
@torkelo All right, thank you very much for the details!
