### ISSUE TITLE
Support for addition units - Weather Units

### ISSUE THREAD

**Issue by jgerschk** [grafana/grafana#1366]
With all the awesome work done with #1331, it would be nice to include Weather Units.

Degree F / Degree C
mph / knot / 
inches / millibars

**Comment by 8igO** [comment]
Any demand for energy consumption as well? We track power (W, kW) and energy consumption (kWh, MWh etc.) for our equipment and I wonder if other users might have a need for this too?

I guess similarly Voltage and Current are often sensed at the same time when metering the power supply to racks.

**Comment by TD22057** [comment]
+1.  I'm building a home energy monitor and need power (kW, kWh) and weather (deg F/C, mph) units.

**Comment by baze-** [comment]
+1
**Degrees (F/C)**, **mph**, **knot**, **km/h** and **mph** would be quite simple and I think comparable to this change https://github.com/grafana/grafana/commit/a0ab9113fc11815630856154e99aaeaf4b4207ee.
Behaviour would be "none-formatting" without any metric prefixing (milli, micro, kilo, giga)

**Comment by elnappo** [comment]
for my weather station and environmental data I need the following units:
* Degrees C
* m/s, km/s
* ppm (parts per million)
* W, kW
* kWh, Wh
* W/m²
* %H (relative humidity

**Comment by torkelo** [comment]
Added these units today (Grafana 2.0 develop branch)
* Fahrenheit (°F) 
* Celsius (°C)
* Humidity (%H)
* kW
* ppm
* watt-hour (Wh)
* kilowatt-hour (kWh)
* velocities (m/s, km/h, mpg, knot)
