### ISSUE TITLE
Panels alignment

### ISSUE THREAD

**Issue by Gas55** [grafana/grafana#13668]
Hello!

Is there any way to set panels align off grid? 

They sticks to each other ) and I want to move some cubes to footer and some to header )

(status panel plugin)

**Comment by Gas55** [comment]
And some sub-question - I got problem with diagram panel.
Got there more than 20 metrics and stuck with adding new one - when I add it - all diagram dies.

I thought there is about limit of metrics count

**Comment by Gas55** [comment]
Oh sorry - version of mine 5.2.4

**Comment by torkelo** [comment]
No, panels will always flow up, you cannot have a vertical space between panels
