### ISSUE TITLE
Grafana 5.3 sends malformed alert images

### ISSUE THREAD

**Issue by SnirX** [grafana/grafana#13665]
Hi,
I’m running Grafana 5.3.0 (upgraded today from 5.2.0) on Centos 7.4 (installed from RPM).
I’m using the datasources Elasticsearch (6.3.2) and InfluxDB(1.5).

I found that alerts on visualizations in which “to the right option” is marked are sent with malformed image (in my case it was sent to Slack channel).

I reverted back to 5.2.0 due to the issue.
Can you check it?
Thank you.

**Comment by torkelo** [comment]
it's probably this issue, https://github.com/grafana/grafana/pull/13617 ? 

fixed in latest nighly and in upcoming v5.3.1
