### ISSUE TITLE
Threshold colour based on linked dashboard

### ISSUE THREAD

**Issue by bryanchapman9999** [grafana/grafana#1367]
I'm creating a top level dashboard with links to other dashboards which have graphs and singlestat metrics displayed.
At the top level I am using a singlestat panel to link to another dashboard.
I would like the ability for the top level singlestat to be coloured dependant on the dashboard it links to. 
so the scenario would be - if the dashboard I am linking to is all green in colour then this top level singlestat would also be green.
If however, one of my metrics changed to orange, due to a threshold breech, then the top level singlestat would also change to orange. If another metric breeched even further and went red, then the top level singlestat would change to show the worst case.

Hope this makes sense and is doable.

Many thanks and great work on grafana!!

Bryan

**Comment by torkelo** [comment]
Good suggestion, would be hell to implement, and hell of a performance problem to load all those dashboards in the background (in the browser), and perform all the metric queries for a number of "in the background" dashboards.
