### ISSUE TITLE
Graphite/Grafana install, no welcome page

### ISSUE THREAD

**Issue by remrat** [grafana/grafana#1368]
Just installed Grafana, and when I load the page, all I see is a menu bar (back to dashboard, save, open, home, and config icons).  Nothing below the menu bar is showing.  If I try to click any of the buttons, nothing happens.  I have tried multiple computers and multiple browsers.  Both graphite and Grafana are on the same server.  I can access graphite, and I do see my metrics and am able to plot them.

I have also tried downgrading to the previous version with the same results.

Thoughts?

**Comment by torkelo** [comment]
What does you config.js look like?

**Comment by remrat** [comment]
I am using the default config.  I have changed my IP address to match Graphite and Elasticsearch.  Graphite is running on port 80, while elasticsearch is on 9200.  

// == Configuration
// config.js is where you will find the core Grafana configuration. This file contains parameter that
// must be set before Grafana is run for the first time.

define(['settings'], function(Settings) {


  return new Settings({

      /* Data sources
      * ========================================================
      * Datasources are used to fetch metrics, annotations, and serve as dashboard storage
      *  - You can have multiple of the same type.
      *  - grafanaDB: true    marks it for use for dashboard storage
      *  - default: true      marks the datasource as the default metric source (if you have multiple)
      *  - basic authentication: use url syntax http://username:password@domain:port
      */

      // InfluxDB example setup (the InfluxDB databases specified need to exist)
      /*
      datasources: {
        influxdb: {
          type: 'influxdb',
          url: "http://my_influxdb_server:8086/db/database_name",
          username: 'admin',
          password: 'admin',
        },
        grafana: {
          type: 'influxdb',
          url: "http://my_influxdb_server:8086/db/grafana",
          username: 'admin',
          password: 'admin',
          grafanaDB: true
        },
      },
      */

      // Graphite & Elasticsearch example setup
      /*
      datasources: {
        graphite: {
          default: true,
          type: 'graphite',
          url: "http://XXX.245.106.XXX",
        },
        elasticsearch: {
          default: true,
          type: 'elasticsearch',
          url: "http://XXX.245.106.XXX:9200",
          index: 'grafana-dash',
          grafanaDB: true,
        }
      },
      */

      // OpenTSDB & Elasticsearch example setup
      /*
      datasources: {
        opentsdb: {
          type: 'opentsdb',
          url: "http://opentsdb.server:4242",
        },
        elasticsearch: {
          type: 'elasticsearch',
          url: "http://my.elastic.server.com:9200",
          index: 'grafana-dash',
          grafanaDB: true,
        }
      },
      */

      /* Global configuration options
      * ========================================================
      */

      // specify the limit for dashboard search results
      search: {
        max_results: 100
      },

      // default home dashboard
      default_route: '/dashboard/file/default.json',

      // set to false to disable unsaved changes warning
      unsaved_changes_warning: true,

      // set the default timespan for the playlist feature

      // Example: "1m", "1h"
      playlist_timespan: "1m",

      // If you want to specify password before saving, please specify it below
      // The purpose of this password is not security, but to stop some users from accidentally changing dashboards
      admin: {
        password: ''
      },

      // Change window title prefix from 'Grafana - <dashboard title>'
      window_title_prefix: 'Grafana - ',

      // Add your own custom panels
      plugins: {
        // list of plugin panels
        panels: [],
        // requirejs modules in plugins folder that should be loaded
        // for example custom datasources
        dependencies: [],
      }

    });
});

**Comment by torkelo** [comment]
You need to uncomment the datasource section you wish to use

**Comment by remrat** [comment]
Torkelo,
That fixed it.  I cant believe I missed that!  
Thanks for your help and fast reply!
