### ISSUE TITLE
Document how and where to upgrade project dependencies

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#13689]
Some of our project dependencies are a bit more complicated to upgrade than would be ideal. This might be something we can simplify in the future, but before that happens it would be a good idea to document how to these upgrade dependencies and where to do it.

### dependencies

- golang
- nodejs
- fpm

### Example:

Upgrading Golang requires modifying these locations
- `.circleci/config.json`
- grafana/build-container
- `README.md`
- `appveyor.yml`
- ...others?

**Comment by xlson** [comment]
I've started here https://github.com/xlson/grafana/blob/docs-upgrading-tools-and-libs/UPGRADING_DEPENDENCIES.md

**Comment by torkelo** [comment]
We also have
https://github.com/grafana/grafana/blob/master/docs/sources/project/building_from_source.md 

Wonder if we should just say Latest Go & node LTS in the README building from source guides

**Comment by xlson** [comment]
That's probably a good start, two less locations to have to update each time we make a change.
