### ISSUE TITLE
Timepicker lost moving left / right with relative timespan

### ISSUE THREAD

**Issue by hahnjo** [grafana/grafana#13687]
### What Grafana version are you using?
just updated to 5.3.0

### What datasource are you using?
InfluxDB

### What OS are you running Grafana on?
CentOS 7

### What did you do?
Opened a dashboard that shows data from the last 6 hours

### What was the expected result?
Grafana 5.2.x had buttons to move left and right in time.

### What happened instead?
They are gone in version 5.3.0

Commit [154fbe2](https://github.com/grafana/grafana/commit/154fbe2413f9abe33157baa563e42fbf67e2f27b#diff-1c0b3228f2e2e7fa2fce6cea8e4f8e92) added `ng-if="ctrl.isAbsolute"`. This is unfortunate because I used moving left / right to get from the last 6 hours (relative) to an absolute time range.

**Comment by marefr** [comment]
If you click on zoom out button or use keyboard shortcuts the left and right buttons will be shown.

Keyboard shortcuts:
mod + z or t + z: zoom out time range
t + "left arrow": Move time range back
t + "right arrow": Move time range forward

**Comment by hahnjo** [comment]
Ok thanks, but that's not really obvious. Are you opposed to restoring the previous behavior?

**Comment by torkelo** [comment]
No, if more users want these to always be visible (not only on absolute ranges) then we will probably add them back

**Comment by coussej** [comment]
@torkelo I also received some feedback from end users that they found it confusing that the left/right buttons are not visible with relative timespans anymore. When they look at a dashboard for the last 24h, they'd typically want to be able to move that frame without first zooming out.

**Comment by hahnjo** [comment]
Ping, how much feedback is needed to get the buttons back? :-)

**Comment by DaveMDS** [comment]
feedback +1 
I'm really missing the always visible arrow buttons

**Comment by cameleon77** [comment]
+1, very strange, spent a lot of time trying to understand where the arrows are, nobody knows t + arrow shortcut, zoom out icon really zooms out (sic!) so this is not the same time range anymore

**Comment by umataro** [comment]
> No, if more users want these to always be visible (not only on absolute ranges) then we will probably add them back

I and about a hundred of my users definitely want it back. We only discovered by accident that zoom out displays them again. This was a very user unfriendly change.

**Comment by hendynz** [comment]
+1 would be good to have the buttons restored.

**Comment by floschmied** [comment]
+1 would be great to have this feature

**Comment by el-psycho** [comment]
+1 please add it back.

**Comment by jbretag** [comment]
+1 
Latest changes without arrows require knowledge of shortcut keys (T + Arrow) or multiple clicks of desired time range plus magnifying glass to return previously easy to use functionality. 
Please return forward and backward arrow keys for all predefined and specified time ranges.

Cheers !!

**Comment by kustodian** [comment]
Same here. All of our engineers (including myself) would like to have this back.

**Comment by johanvdb** [comment]
Myself and our NOC teams use the arrows constantly to compare the past 24 hours with the 24 hours before that and so forth. It is critical to be able to step back in time in an equal window timeframe than the relative time that you are looking at currently, so that you can get a clear view of a potential change in data. Compare apples vs apples kind of thing. +1 Please bring back the arrows.

**Comment by thomasleitner** [comment]
+1
Yes please ... when the timerange is set to „Today“ or „This month“ it would also be great to have  backward forward arrows to simply scroll back to „yesterday“ and from there to the day before yesterday and so on. Also, scrolling forward again. Similarly for months and years.

**Comment by Matze2** [comment]
+1

**Comment by kalinjul** [comment]
> +1 Yes please ... when the timerange is set to „Today“ or „This month“ it would also be great to have backward forward arrows to simply scroll back to „yesterday“ and from there to the day before yesterday and so on. Also, scrolling forward again. Similarly for months and years.

This! I'm confused why this is not a much more popular demand. I'm always showing "Today" and of course I'd like to be able to quickly show the last day.
Using the hotkeys (t+arrows) works, but it also scrolls in 12h steps.
IMHO, if I'm showing "Today", it should scoll 1d in one step, if I'm showing "This week", it should scroll a whole week.

But yes, please give us the arrows back

**Comment by wkruse** [comment]
Moving left and right always uses the half of the time range. Using the hotkeys also changes the UI Theme sometimes. Holding the `t` key and using arrows more than once doesn't work. For the end users the whole time picker pagination experience is difficult to grasp. 

Is it possible to configure the interval?

**Comment by wkruse** [comment]
Related to #21957.

**Comment by avo1kov** [comment]
+1

And also, please make the step of the arrows equal to the timerange, not half of it.
