### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by mustiyalniz** [grafana/grafana#13695]
Hello,

We have our data in influxdb and all records are in monday. So I create a query to group weekly with week starts on monday.

SELECT sum("value") FROM "Downtime" WHERE time >= 1523907785648ms GROUP BY time(1w,3d), "category" fill(0) ORDER BY time DESC

![image](https://user-images.githubusercontent.com/44211665/47042947-21ab3200-d195-11e8-8d4b-d2c795221753.png)

We want to sum downtime contributions.

So I believe I am missing something. Can you help.

Thank you

**Comment by mustiyalniz** [comment]
The issue is when I hover on the weeks it does not give me the values. It just tells the last week.

**Comment by mustiyalniz** [comment]
Also the graph has "Data points outside time range" text over the graph.

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

You can inspect what your query returns in the query inspector in The metrics tab
