### ISSUE TITLE
Variables from graphite with filters

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#13699]
Hello,

just an idea: it could be nice to be able to generate variable from graphite datasources with filters.

I mean, if I need to repeat-panel but only for my top5 metric or only for those where average is above 100...

it would be nice to be able to use filter in the variable graphite query.

I tried to do that, but I think it is actually not implementer.

Actually to create a variable from graphite we must use: `prod.servers.*`
We can use something like this: `aliasByNode(averageAbove(prod.servers.*.exec_time.mean, 100), -3)`

the important part is that the final query returns a list of string.

What do you think?

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/10242 , that is support time series queries in templating. Will modify that issue to include this case as well.

**Comment by shanson7** [comment]
#10242 was resolved. but does not handle this case. Can this be reopened? See [this comment](https://github.com/grafana/grafana/issues/10242#issuecomment-1373338818) for a more detailed explanation and [this one](https://github.com/grafana/grafana/issues/10242#issuecomment-1378059954) by @bohandley indicating this should be reopened. 

FWIW, I think the new design that allows multiple choices for the query type should make this easier to implement.
