### ISSUE TITLE
Table Panel features

### ISSUE THREAD

**Issue by JosephFY** [grafana/grafana#13698]
We relay on the Table Panel in many dashboards on different levels. There is some really helpful features that can be added that will dramatically  enhance this panel. Those features are already implemented in the Datatable panel but I think they are really useful and important to have them natively with the Table Panel.

What blocking us of not using the Datatable Panel is that it doesn't support linking cells to other dashboards which is a huge feature for us that we can't ditch. 

1. Search Feature. This is really helpful when search metrics spanning cross multiple pages in the panel with instant search of course.
![image](https://user-images.githubusercontent.com/28739923/47059283-5962ab80-d18e-11e8-9a0f-e12d9da5f98c.png)

2. Pages summary. Those can smooth browsing through different pages when you have many pages involved. Additionally, it can give an aggregated count of the metrics kinda similar to countSeries() function
![image](https://user-images.githubusercontent.com/28739923/47059220-0983e480-d18e-11e8-80e9-d28fad7514ab.png)
![image](https://user-images.githubusercontent.com/28739923/47059268-4059fa80-d18e-11e8-9b81-7aae3554a0a6.png)

What Grafana version are you using?
5.2.3
What datasource are you using?
graphite
What OS are you running grafana on?
redhat linux

**Comment by torkelo** [comment]
Thanks for this feedback, we do want to make some big improvements to table panel and there are already seperate feature request issues for all of your proposed ideas so will close this issue :)
