### ISSUE TITLE
Drill-down link menu:  Use dashboard id instead of dashboard name.

### ISSUE THREAD

**Issue by robvalca** [grafana/grafana#13704]
### What Grafana version are you using?
v5.2.4
### What datasource are you using?
Various, not related to any datasource
### What OS are you running grafana on?
Centos7
### What did you do?
Rename a dashboard contained in one graph's drill-down link menu
### What was the expected result?
The drill-down menu to still  working.
### What happened instead?
Links were broken.
-----
Hi All, 
I think that it would be be better to use dashboard's id for setting the dashboard targets in the drop-down links cause now seems to be using the dashboard name and if you rename the dashboard then the links become broken.
Thanks!

**Comment by torkelo** [comment]
this is implemented in v5.3
