### ISSUE TITLE
5.3.0 Alerting - Email graph legend aligned left

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#13701]
datasource influxdb
centos 7

cant see the graph on email alerts - legend is aligned left

![image](https://user-images.githubusercontent.com/12600004/47073329-4be20b80-d1f8-11e8-8fba-6a7c19f98ccf.png)

**Comment by torkelo** [comment]
fixed in v5.3.1 :)

**Comment by marefr** [comment]
Duplicate of #13616

**Comment by discoduck2x** [comment]
> Duplicate of #13616

sorry i should have looked harder - thanks for ur awesome attention!
