### ISSUE TITLE
Table Panel: Support fixed with column widths 

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#13703]
Dear all,

Would somebody be able to inform me if there is any table formatting available when quering from a postgress datasource.
Meaning: Currently we have 1 page with multiple panels, each having a data output. But since the length of the output changes, the layout of the tables/panels differs causing a less estethic appearance.

Grafana version: 5.4.2
Os: ubuntu 16.04 LTS

What did I do:

1) one dashboard containing 3 panels. Each panel contains a table look result based on a postgress SQL query

What do I expect: (or would like to ;-) )
See that all columns across the panels match in size showing a nice table.

![afbeelding](https://user-images.githubusercontent.com/25956116/47077174-a7b09280-d200-11e8-90b2-aab37c73d7ac.png)

**Comment by Kenith** [comment]
+1

**Comment by chook** [comment]
@torkelo any workaround you can suggest for this? something around how width is calculated

**Comment by benjdl** [comment]
Any update on this issue ?

**Comment by ramasif** [comment]
+1 - still no update? The issue is from Oct 2018..

**Comment by vicioussn** [comment]
+1

**Comment by OMSKremer** [comment]
+1

**Comment by ShadowFM** [comment]
+1

**Comment by fa1861** [comment]
+1

**Comment by lukesaint** [comment]
+1

**Comment by carloshs1993** [comment]
+1 

I'm showing data in a table and this feature would improve a lot the look-and-feel. Now, I've to use acronyms and abbreviations in my column titles because of arbitrary width :(

**Comment by dailyimprovement** [comment]
+1

**Comment by csaladenes** [comment]
*Custom workaround*

- Install [Boom Theme](https://grafana.com/grafana/plugins/yesoreyeram-boomtheme-panel)

- Add this to the custom CSS field:

`tr td:first-child{
    width:100px;
}`

**Comment by ElieLiabeuf** [comment]
+ 1

**Comment by ryantxu** [comment]
Works in the table panel for 7.0 -- it even has realizable columns!
