### ISSUE TITLE
Grafana automatic dashboard and InfluxDB non existent series

### ISSUE THREAD

**Issue by dolefi** [grafana/grafana#13709]
Hello, 
I have been using grafana with custom automatic dashboard, but after upgrade to latest version 5.3.1 (and probably all 5.X.X versions also) there seems to be some difference at how the automatic dashboard is loaded. 

I have deleted all series in InfluxDB for certain servers, I am not able to querry these series in Influx anymore and I expect grafana to stop showing these servers. But that is not the case.

in InfluxDB:
![image](https://user-images.githubusercontent.com/17765008/47084664-7cd03980-d214-11e8-901f-897e0ea18ef0.png)

but in grafana the server is still present: 
![image](https://user-images.githubusercontent.com/17765008/47084698-96718100-d214-11e8-95d0-6233a1c49d1e.png)

Can you please let me know where is the issue ? Is there some king of cache for the hosts ?

**Comment by marefr** [comment]
The value displayed in the template variable drop down is probably saved from earlier when you had data and that's why it's displayed now.
