### ISSUE TITLE
Overlaying data from e.g. 1 day ago

### ISSUE THREAD

**Issue by marcogallotta** [grafana/grafana#1371]
It would be great if we could overlay data from another time period, e.g. 1 day / 1 week ago to easily compare.

**Comment by danievanzyl** [comment]
Have you tried doing the following, for example, editing the raw query and adding the following,
```where $timeFilter - 1d```

**Comment by torkelo** [comment]
this is easy to do with graphites timeShift function. InfluxDB does not have timeshift support yet, but that will probably come.
