### ISSUE TITLE
Bug/Feature ? Grafana super admin can't be also admin of orgs

### ISSUE THREAD

**Issue by darkweaver87** [grafana/grafana#13710]
Hello,

I'm using grafana 5.3.1 on debian stretch with ldap feature. I would like all my grafana super admins be also admins (a.k.a. role "Admin") of orgs.
So I have one AD group and reading at https://github.com/grafana/grafana/blob/f2833bfd52ec6ab7f757393678b7a2d251cf46e6/pkg/login/ldap.go#L188 if I set only one Admin role on this group, it will not benefit of being super admin.

Configuration to reproduce:

[[servers.group_mappings]]
group_dn = "CN=Grafana_Admins,OU=GRAFANA,OU=APPLICATIONS,DC=xxx,DC=xx"
org_role = "Admin"
grafana_admin = true

[[servers.group_mappings]]
group_dn = "CN=Grafana_Admins,OU=GRAFANA,OU=APPLICATIONS,DC=xxx,DC=xx"
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "CN=Grafana_Admins,OU=GRAFANA,OU=APPLICATIONS,DC=xxx,DC=xx"
org_role = "Admin"
org_id = 2

So it's an open question: bug or feature ?

**Comment by torkelo** [comment]
I guess that line should be

```go
 extUser.IsGrafanaAdmin = extUser.IsGrafanaAdmin || group.IsGrafanaAdmin 
```

**Comment by darkweaver87** [comment]
Thanks for your feedback. My colleague and I are working on it :-)
