### ISSUE TITLE
Can't receive DingDing alert when alert is triggered

### ISSUE THREAD

**Issue by Yukinoshita-Yukino** [grafana/grafana#13723]
DingDing can only receive test notification.
When an actual alert is triggered, the notification is sent but cannot be received.

### What Grafana version are you using?
Grafana v5.3.1 (08c7908)
### What datasource are you using?
Elasticsearch 6.3.1
### What OS are you running grafana on?
CentOS Linux release 7.5.1804 (Core)
CentOS release 6.8 (Final)
Both got the same problem
### What did you do?
Configured a graph panel with alert sending to DingDing.
### What was the expected result?
Alert notification being received.
### What happened instead?
Nothing.
<br/>
<img width="711" alt="wx20181018-103216 2x" src="https://user-images.githubusercontent.com/3638888/47127780-1ce39c80-d2c1-11e8-8410-59562bc1b79f.png">
From /var/log/grafana/grafana.log
Above the red line is the log for sending test notification, which successfully went through.
Under the red line is the log for actual triggered alert notification. Seems like the notification has been sent, but nothing is received.
<br/>
<img width="547" alt="wx20181018-103402 2x" src="https://user-images.githubusercontent.com/3638888/47127840-59af9380-d2c1-11e8-87ff-80b201e38423.png">
This is what I got in DingDing, only the test notification.

**Comment by superbool** [comment]
Also found the problem, but I'm using 5.3.0 with webhook. So I debug the code [](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/base.go#L59) 
```
		lastNotify := time.Unix(notiferState.UpdatedAt, 0)
		if notiferState.UpdatedAt != 0 && lastNotify.Add(n.Frequency).After(time.Now()) {
			return false
		}
```
it always return false. 
so I add a log info before return:
```
log.Info("ShouldNotify","lastNotify",lastNotify,"n.Frequency",n.Frequency)
```
and the logs:
```
INFO[10-18|14:50:01] ShouldNotify%!(EXTRA string=lastNotify, time.Time=2018-10-18 14:49:07 +0800 CST, string=n.Frequency, time.Duration=1m0s) 
INFO[10-18|14:49:01] ShouldNotify%!(EXTRA string=lastNotify, time.Time=2018-10-18 14:48:06 +0800 CST, string=n.Frequency, time.Duration=1m0s) 
INFO[10-18|14:48:01] ShouldNotify%!(EXTRA string=lastNotify, time.Time=2018-10-18 14:47:06 +0800 CST, string=n.Frequency, time.Duration=1m0s) 
```
* Send reminder every 1m and Evaluate every 60s *
I don't know it's a bug or not.

**Comment by Yukinoshita-Yukino** [comment]
@superbool 
`{'errmsg': 'message param title or text is null ', 'errcode': 300001}`
This is the error message returned from Dingding server, I don't think it's related to your problem.
Maybe you should open another issue.
