### ISSUE TITLE
Can't set the maxDataPoints for a graph source

### ISSUE THREAD

**Issue by 9bryan7** [grafana/grafana#13724]
**Can't set the maxDataPoints for a graph source**

![2](https://user-images.githubusercontent.com/5178667/47129068-61256b80-d2c6-11e8-943e-dc7ca48f28f2.PNG)

![1](https://user-images.githubusercontent.com/5178667/47129062-59fe5d80-d2c6-11e8-805c-e48548e43ddc.PNG)

**How can I set the maxDataPoints? I try to set it in the dashboard.json, but it doesn't seem to work.**

![3](https://user-images.githubusercontent.com/5178667/47129217-050f1700-d2c7-11e8-8d23-9d1874ac6934.PNG)

### What Grafana version are you using?
v5.0.3
### What datasource are you using?
graph
### What OS are you running grafana on?
Linux
### What did you do?
Set the maxDataPoints
### What was the expected result?
Get maximum number of data points
### What happened instead?
Get thousand of data points

**Comment by torkelo** [comment]
Many datasource don’t have a maxDataPoints option. You have to modify the group by time 

It’s under the metrics tab the datasource row to the left you set min interval, used by the auto __interval variable in group by terms
