### ISSUE TITLE
Can't reference queries that reference queries

### ISSUE THREAD

**Issue by marcogallotta** [grafana/grafana#1372]
I want to be able to do
A) queryA
B) queryB(#A)
C) queryC(#B)

But this results in a generic error. Based on experimentation, I believe the problem is that you can't multi-nest queries. I would guess that grafana does variable replacement for the #B, but fails to the redo variable replacement, and so sends a literal #A to graphite.

**Comment by torkelo** [comment]
seems to be the case. thanks for reporting this, will try to fix.

**Comment by torkelo** [comment]
Fixed in master
