### ISSUE TITLE
[wip]Feat/Fix - Support Elasticsearch Lucene queries in template variables (Textbox)

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#13721]
Please include this information:
### What happened instead? regex slash-a-thon all over the query 
 
I (and likely anyone else using an Elasticsearch datasource) have always needed to be able to provide a Lucene Query via a Template Variable, so it could be used to update multiple panels in a single dashboard.  The value of this working properly unlocks a lot of potential for Elasticsearch data sources.

The new Textbox variable gets half the job done, but there is code that regexes (unnecessarily to my eye) the Lucene query IF it's in a template variable.  Blame seems to indicate that it was added for Jest support, but that doesn't seem right.

I've tested this many different ways, and simply removing the code (one line) fixes the issue, and gives full Lucene support to the dashboard as a Template Variable.  @torkelo may know what it is for, and if it is truly needed, or can just be removed, or I can work on something that includes a dependency that I couldn't find.

Screen shots below show:
- the Metric Query working with an inline provided Lucene query.  Query Inspector shows the proper Lucene expression passed.
- the Metric Query with the Textbox template variable.  Query Inspector shows the regexed, backslashed (unnecessarily) broken Lucene expression passed.  And the result is failure (returns all basically).
- the Metric Query with the Textbox template variable. Query Inspector shows the proper Lucene expression passed, and the proper results.

Needs review.

![elastic_1](https://user-images.githubusercontent.com/35579731/47115804-acd80680-d22d-11e8-91d2-84d7b729c59e.png)
![elastic_2](https://user-images.githubusercontent.com/35579731/47115814-b2cde780-d22d-11e8-939c-7ad27fce4bd3.png)
![elastic_3](https://user-images.githubusercontent.com/35579731/47115817-b5304180-d22d-11e8-85a9-651b4b34cc2c.png)

**Comment by davewat** [comment]
I removed the tests for the Lucene escaping, as that is what was specifically removed.  Note that both Query Template variables and Adhoc Template variables work fine as well (see with attached):

![query_works](https://user-images.githubusercontent.com/35579731/47117709-23c3ce00-d233-11e8-8e98-0bd4be45a42d.png)
![adhoc_works](https://user-images.githubusercontent.com/35579731/47117713-28888200-d233-11e8-9a08-1cfc58deb012.png)

**Comment by torkelo** [comment]
added docs to address this: https://github.com/grafana/grafana/issues/13744
