### ISSUE TITLE
Table scroll not native (Firefox)

### ISSUE THREAD

**Issue by sbatalin** [grafana/grafana#13731]
Table Panel
Grafana: 5.3.0
Data Source: InfluxDB
OS: Windows 7 Prof, Windows Server 2008 R2 Enterprise
Firefox: 62.0.3 (64-bit)
![table_scroll](https://user-images.githubusercontent.com/462916/47139913-9f6e5b00-d2c5-11e8-9605-be28ab97db6c.PNG)

Table scroll looks like a not native in Firefox (see attached pict.)

**Comment by torkelo** [comment]
that is a native firefox scrollbar (ugly as hell I know). Chrome allows some style overrides for native scrollbar so it will look better in chrome. 

We hope to switch to custom scrollbars for table panel at some point, maybe in v6

**Comment by sbatalin** [comment]
but, graph scroll (not table scroll) in firefox look as native (see attached pict). What differnce between graph scroll and table scroll? Yes, in chrome all ok. 
![graphscroll](https://user-images.githubusercontent.com/462916/47156190-3996c900-d2ef-11e8-9edb-a82d0b575abd.png)
