### ISSUE TITLE
grafana badly parses some queries wrt templates

### ISSUE THREAD

**Issue by marcogallotta** [grafana/grafana#1373]
The query
alias(transformNull(removeAboveValue(transformNull(removeBelowValue(asPercent(#A, #B), $Percent5xxToIndicateDowntime), 0), 0), 1), 'is down')

gets parsed badly. See the attached image.

![parse](https://cloud.githubusercontent.com/assets/192548/5851364/f057adfe-a1ba-11e4-9795-b98af22812d4.png)

**Comment by torkelo** [comment]
You need to split the query, you cannot have a metric segment and two parameters to asPercent in the same query. 

You can either do something like this:
![image](https://cloud.githubusercontent.com/assets/10999/5872406/7bd29714-a2eb-11e4-8c6e-53889671e0a0.png)

Or something like this:
![image](https://cloud.githubusercontent.com/assets/10999/5872422/ae588ab8-a2eb-11e4-857d-a170553b4012.png)
