### ISSUE TITLE
Explore datasource after configuring it

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13737]
It would be great if I could explore my data right after configuring it.

The current flow to look at data is:

1. Go to Datasources
2. Configure a datasource
3. Go back to Dashboards or Explore via sidemenu

The problem is that the configuration page offers only Save and Back as CTAs. Back only brings you back to the Datasources page. It would be great to have another button in addition to Save and Back that bring the user to Explore.

**Comment by tharun208** [comment]
@davkal I like to work on this
