### ISSUE TITLE
Explore: Graph and Table toggles are not obvious

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13738]
The toggles for Graph and Table are not obvious. I'd like to create a better experience.

An idea would be to not have buttons above the panels, but rather to have the panels collapsible so that in their collapsed state, the related query is not run.

**Comment by Ijin08** [comment]
Here are some quick mockups of the I guess simplest way(accordions). Did three versions.

Version 1(my personal choice):
![cleanopenopen](https://user-images.githubusercontent.com/23470681/48544042-172ea600-e8c3-11e8-842b-6a0f5bc721d4.png)
![cleanopenclosed](https://user-images.githubusercontent.com/23470681/48544056-1f86e100-e8c3-11e8-8c90-baa41bab196b.png)

Version 2: 
![blackopenopen](https://user-images.githubusercontent.com/23470681/48544072-2e6d9380-e8c3-11e8-85f4-3f3c3c127d43.png)
![blackopenclosed](https://user-images.githubusercontent.com/23470681/48544083-33324780-e8c3-11e8-8082-a398c673a572.png)

Version 3:
![orangeopenopen](https://user-images.githubusercontent.com/23470681/48544113-3f1e0980-e8c3-11e8-8eed-133c82705e3b.png)
![orangeclosedopen](https://user-images.githubusercontent.com/23470681/48544128-4513ea80-e8c3-11e8-8524-6284840fed06.png)
