### ISSUE TITLE
Add quarterly time ranges to time picker

### ISSUE THREAD

**Issue by rockaut** [grafana/grafana#13734]
Would it be possible to include yearly quartals as selections in quick ranges?

Q1 yyyy-01-01 00:00:00 to yyyy-04-01 00:00:00
Q2 yyyy-04-01 00:00:00 to yyyy-07-01 00:00:00
Q3 yyyy-07-01 00:00:00 to yyyy-010-01 00:00:00
Q4 yyyy-10-01 00:00:00 to yyyy+1-1-01 00:00:00

**Comment by lazycoder-ru** [comment]
Any progress?

**Comment by klausbadelt** [comment]
To me this means adding quarter to time units `q` - so that from `1q/q` to `1q/q` shows current quarter, from `-4q/q` to `1q/q` shows last 4 quarters etc.
