### ISSUE TITLE
Alerting with diff() not working as expected

### ISSUE THREAD

**Issue by rolatsch** [grafana/grafana#13748]
I'm trying to use the `diff()` altering function, but it doesn't behave as expected.
My application pushes infos about requests to an Influxdb when they appear. So the latest Bucket of my count series always starts with 0 and fills over time. (I am using 1m Buckets)

Now i want to detect drops in the request rate using an alert condition like this:
`WHEN diff() OF query (A, 5m, now-1m) IS BELOW -500`

My assumption is, that this condition calculates the difference between the value 5 minutes ago and the value 1 minute ago and alerts if this is below -500. But the alert fires everytime a new Bucket is started.

The metric query used looks like this:
`SELECT count("value") FROM "api_response_time" WHERE ("realm" = 'live') AND $timeFilter GROUP BY time($__interval) fill(0)`

This also applies to `percent_diff()`.

### What OS are you running grafana on? => **Ubuntu 16.04.4**

I was hoping this was fixed with 5.3.1 as there was an issue which sounded a lot like this but maybe my assumption how this should work is simply wrong.

Thanks in advance.

**Comment by marefr** [comment]
@rolatsch have you configured `Min time interval` for the datasource, i.e. write frequency? This is the lowest value `$__interval` will use.

Please use the test alert rule to verify the response.

**Comment by marefr** [comment]
@hocker that's not the same issue as reported in this issue. Original issue referred to using the `diff()` function in the when-condition and not influxdb difference function. Please open separate issue. Thanks

**Comment by marefr** [comment]
@rolatsch 

> What i don't understand is, why using diff() OF query (A, 5m, now-1m) or even diff() OF query (A, 10m, now-5m) doesn't work as expected. This should ignore the last bucket(s) to evaluate the alert condition.

I agree. Please include results/screenshots of testing alert rule, change time range of dashboard to last 4 minutes and include screenshot of panel where you've defined your alert rule. Just to verify your `Min time interval` are used try and change your query to `GROUP BY time(1m)`. Thanks

**Comment by marefr** [comment]
@rolatsch That's looks correct according to me. Do you mean that you don't receive alerts when expecting or receive too many?

**Comment by rolatsch** [comment]
@marefr I receive too many alerts. The case you see in my screenshots should not be alerting because the last point should be excluded by `now-1m`

**Comment by marefr** [comment]
Well the alert evaluation may evaluate between points, e.g. at 14:20:30, when you write metrics each minute like 14:19:00, 14:20:00 etc. So it's hard to say that the "last point should be excluded by `now-1m`". With upcoming Grafana v5.4.0 you'll be able to say that the alert condition should trigger for some time before actually alerting - that will probably help you resolve this problem.

**Comment by rolatsch** [comment]
My metrics are continuously written. At 14:20:30 there are approx half of the points already in place.
So if the alert condition is evaluated at 14:20:30 the "last point" of the graph (14:20:00 - 14:21:00) contains only data of 30s will most likely fire the alert.
My assumption was that `now-1m` would cause the evaluation would take the "second last point" of the graph (14:19:00 - 14:20:00) for evaluation which at this moment is already filled completely.

However, the 5.4.0 feature you mentioned should be another way to resolve this.

**Comment by marefr** [comment]
If the alert condition is evaluated at 14:20:30 then now-1m will be 14:19:30 and then you still have approx half of the points in place in the last point (14:19:30). Point here is that there's no logic in place which makes the alerting engine only looking at half/full minutes like 14:19:30, 14:20:00 etc - the alerting engine will use the exact time of "now" when the evaluation triggers.

**Comment by rolatsch** [comment]
Ok, this should not be a problem so far. As data comes in continuously the second of the minute where the evaluation starts should not matter. Does the alert engine use the data which is already present in Grafana or does it query the InfluxDB by itself?
If it queries the InfluxDB itself then the basic `GroupBy time` without setting the offset may not delivered the expected results.

**Comment by marefr** [comment]
> Does the alert engine use the data which is already present in Grafana or does it query the InfluxDB by itself?

Grafana doesn't store any timeseries data. Every alert evaluation will query influxdb with the timerange defined by for example `Query(A, now-5m, now)`.

**Comment by rolatsch** [comment]
Ok this explains why this doesn't work as expected. A few example queries to show what influx does:

**Basic Query with "full minute" timerange:**
```> SELECT count("value") FROM "api_response_time" WHERE time >= '2018-11-22T12:24:00Z' AND time < '2018-11-22T12:29:00Z' GROUP BY time(1m)
name: api_response_time
time                 count
----                 -----
2018-11-22T12:24:00Z 2517
2018-11-22T12:25:00Z 2582
2018-11-22T12:26:00Z 2459
2018-11-22T12:27:00Z 2383
2018-11-22T12:28:00Z 2307```
Result contains 5 Buckets starting at second 0, each containing Data of a full minute.

**Same query but timerange starts and ends at second 30:**
```> SELECT count("value") FROM "api_response_time" WHERE time >= '2018-11-22T12:23:30Z' AND time < '2018-11-22T12:28:30Z' GROUP BY time(1m)
name: api_response_time
time                 count
----                 -----
2018-11-22T12:23:00Z 1178
2018-11-22T12:24:00Z 2517
2018-11-22T12:25:00Z 2582
2018-11-22T12:26:00Z 2459
2018-11-22T12:27:00Z 2383
2018-11-22T12:28:00Z 1084```
Result contains 6 Buckets starting at second 0. The first and the last bucket only contains the data for 30 seconds. (This is what Grafana does and why i get too many alerts).

**Same as the second query but using the offset parameter of `Group by time`**
```> SELECT count("value") FROM "api_response_time" WHERE time >= '2018-11-22T12:23:30Z' AND time < '2018-11-22T12:28:30Z' GROUP BY time(1m, 30s)
name: api_response_time
time                 count
----                 -----
2018-11-22T12:23:30Z 2417
2018-11-22T12:24:30Z 2588
2018-11-22T12:25:30Z 2446
2018-11-22T12:26:30Z 2507
2018-11-22T12:27:30Z 2245```
Result is as expected. 5 Buckets each starting from second 30 and containing data of a full minute.

So maybe Grafana should include the offset parameter in the alert evaluation query to shift the preset time boundaries of the InfluxDB to avoid receiving partial buckets.

**Comment by marefr** [comment]
Thank you. Yes this pinpoint exactly the problem :+1: 

There's no way for Grafana to know that an influx query is executed due to an alert evaluation and therefore nothing that Grafana can solve. But you can define the offset by manually writing a value for the group by time in the query editor.

![image](https://user-images.githubusercontent.com/1668778/48914975-49b93f80-ee7d-11e8-86cb-237e9d499d7d.png)

**Comment by rolatsch** [comment]
Manually defining the offset is not really a solution, because it has to be dynamic based on when the query is executed. Setting it to 30s will only work when the alert query is executed at second 30 of every minute. I will check if it's somehow possible to calculate the needed offset right in place.

**Comment by rolatsch** [comment]
Seems like Influx has no function like datePart or anything else to manipulate the value returned by `now()`
