### ISSUE TITLE
Debugging queries is guess-and-check

### ISSUE THREAD

**Issue by marcogallotta** [grafana/grafana#1374]
The query
movingAverage(transformNull(removeAboveValue(transformNull(removeBelowValue(asPercent(#A, #B), $Percent5xxToIndicateDowntime), 0), 0), 1), '1day')

results in a blank graph. If the movingAverage is removed, the graph oscillates between 0 and 1. ie, it looks like the movingAverage is breaking things, but I have no idea how or why.

**Comment by torkelo** [comment]
check that the query sent to graphite is correct (via chrome dev tools, network tab and the /render request to graphite). If it looks correct, then you will probably get help in the graphite irc channel or their github repo. 

movingAverage for 1 days worth of metric might be too long for graphite, not sure what the issue can be.
