### ISSUE TITLE
Elasticsearch Datasources _mapping slow in 5.3.0

### ISSUE THREAD

**Issue by kdszh** [grafana/grafana#13743]
Hi,
   Today I upgrade grafana from 4.6.1 to 5.3.0, copy the same grafana.db  to new version dir. I found Elasticsearch Datasources _mapping ( Test datasource in datasource edit panel )in 5.3.0 is much more slower than 4.6.1

> PS: grafana 4.6.1 and 5.3.0 are in the same server

> 4.6.1 (17ms)
![461](https://user-images.githubusercontent.com/2100801/47151607-d025b300-d30c-11e8-8ca6-efed6142d748.png)
> 5.3.0 (15s)
![530](https://user-images.githubusercontent.com/2100801/47151617-d74cc100-d30c-11e8-921a-d554c12b674c.png)

_mapping url :
4.6.1:
http://localhost:10001/api/datasources/proxy/47/nw_wx-open-pro_nginx_access-*2018.10.18/_mapping

5.3.0:
http://localhost:10002/api/datasources/proxy/47/nw_wx-open-pro_nginx_access-*2018.10.18/_mapping

**Comment by marefr** [comment]
We haven't received any similar reports. You're sure this wasn't just a temporary slow response from your Elasticsearch instance?

**Comment by marefr** [comment]
@kdszh are you still having this problem?

**Comment by marefr** [comment]
Closing this for now due to no response. Will consider reopen if you respond.
