### ISSUE TITLE
Info popover React Replacement / Equivalent 

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#13745]
We have an angular component called `info-popover` which is used to show information about certain input fields. Do we want to keep this behaviour or do we want to introduce something new? It works on hovering i-icons which doesn't really work on touch devices. 

So, do we want to keep it? If yes, should we build our own component or use some lib that we're wrapping?

**Comment by torkelo** [comment]
think the work Johannes has done on popper tooltip we can close this.
