### ISSUE TITLE
CloudWatch datasource alerting not work for GetMetricData API

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#13749]
Related to https://github.com/grafana/grafana/pull/11624#issuecomment-428618084

**Comment by haizaar** [comment]
Still happens with Grafana 6.0.1. Coming from https://github.com/grafana/grafana/issues/13940 I must admit it's a very subtle bug :)

**Comment by danielmotaleite** [comment]
Same problem as #13940 , a aws/s3 query returns data without IDs, but adding IDs make it return no data:

![bytes_per_file](https://user-images.githubusercontent.com/11890049/54749811-9c0d3180-4bcd-11e9-85bd-0cb7661142a4.png)
![files_and_bytes](https://user-images.githubusercontent.com/11890049/54749812-9c0d3180-4bcd-11e9-939d-602f4d80ba36.png)

 Using Grafana v5.4.3 (commit: 6539180)

**Comment by SDA-TRT** [comment]
Same issue as 16825, id breaks alerts when Cloudwatch is used:
![example1](https://user-images.githubusercontent.com/45456163/57624920-ce625c00-758a-11e9-9506-f53c6ef624d4.png)
![example2](https://user-images.githubusercontent.com/45456163/57624926-d15d4c80-758a-11e9-9bd2-bc912ef32687.png)

Strangely, my graphs still work, it's just the alarm that breaks.

**Comment by pcolby** [comment]
> Strangely, my graphs still work, it's just the alarm that breaks.

Not surprising.  There's (at least) two bugs in the code that fetches the metrics for alerts only (one is the ID breaking the query (#13940 and #16825), the other is that dependant metrics (for compound metrics) are not included - but this can be worked-around if the first problem gets fixed).

I'm pretty sure this issue has been incorrectly categorised - its set to be `type/feature-request`, but should be `type/bug` in my opinion.

Any ETA on a fix? :pray: It's currently not possible to alert on a number of my more valuable app performance indicators.

**Comment by DevJackSmith** [comment]
concur, issue should be categorized as bug not feature-request

**Comment by kartwang** [comment]
It bug me when i monitor the AWS "direct connect" service, i need do some "expression" for traffic flow, make data match with my network device, and it need add "id" when i use "expression" fuction.

But when i get right data ,i can't get alert when the traffic flow not right. 

It should be alert when user need, even the data has after "expression" or add "id".

So please make this function work, thank you.

**Comment by MichaelMitchellM** [comment]
Is there any update on this?

**Comment by Nessworthy** [comment]
The PR was merged and is scheduled for Grafana 6.4 - The [releases](https://github.com/grafana/grafana/releases) / [6.4 milestone](https://github.com/grafana/grafana/milestone/134) pages can be used to track the progress.

**Comment by Nessworthy** [comment]
Issue still seems to be outstanding, even in 6.4.1.

**Comment by sunker** [comment]
A lot of changes have been made the cloudwatch datasource in grafana 6.5 (current released version is 6.5-beta1). One of those changes was to move away from the GetMetricStatistics API and use GetMetricData for all requests. See #20057 
It is now fully possible to add alerting rules that are based on queries that use expressions. You don't have to add an ID to the queries that use expressions - grafana will generate an ID automatically. 
However, it will not be possible to build alert rules that are based on queries that reference other queries in the panel. Say for example you have to queries. Query `a` returns SUM of CPU usage across multiple instances. Then you have query `b` that does `a * 2` in an expression. In this somewhat weird scenario, it would be possible to create an alerting rule on query `a`, but **not** for query `b`. 
Support for alerting rules on queries that reference other queries might be supported in the future when the alerting engine is rebuilt, but that is not on the road map for the near future. Closing this issue.

**Comment by LloydW93** [comment]
Is there another issue tracking the desire for CloudWatch alerting rules based on queries that reference another query? I've got a use case for it that I'd like to add on to help any future prioritisation calls.

**Comment by sunker** [comment]
No it's not. Please create a new feature request issue and add labels `cloudwatch` and ´alerting´.

**Comment by bkbwese** [comment]
It appears that there is an issue open already for the alerting functionality mentioned above: #19886
