### ISSUE TITLE
more than one LDAP group for org_role = "Viewer" possible? how?

### ISSUE THREAD

**Issue by ant0nwax** [grafana/grafana#13747]
We tried to use Grafana LDAP Auth and it is working with groups
we have one Admin Group, that is working
now we would like to configure 13 Viewer Groups
how is that possible? I did not find a solution in 4 hours of debugging. thanks

**Comment by torkelo** [comment]
yes, just add 13 rows like this 

```
[[servers.group_mappings]]
group_dn = "cn=viewer1,dc=grafana,dc=org"
org_role = "Viewer"

[[servers.group_mappings]]
group_dn = "cn=viewer2,dc=grafana,dc=org"
org_role = "Viewer"
```

**Comment by ant0nwax** [comment]
thanks m8, i did not realize that i have to repeat the
[[servers.group_mappings]] line
that was really fast, thank you and have a good ongoing day
