### ISSUE TITLE
Docs: document the new variable interpolation syntax

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13744]
* `${varname}` 
* `${varname:csv}` csv formatting for multi valued variables
* `${varname:raw}` no escaping (very useful) 

Needs to be documented in the templating doc and probably mentioned in the templating section for each data source as well.

**Comment by oddlittlebird** [comment]
Please add detail about what to add and where. I assume we want to do something more than just copying and pasting those three bullets into the docs.
