### ISSUE TITLE
Alerts option: Don't include "OK"

### ISSUE THREAD

**Issue by JosvdP** [grafana/grafana#13753]
This is a feature request.
I use alert notifications for alerting single events which are over the threshold. It is unnecessary to send an "OK" message, it just makes the chat more messy for us. Would it be a good idea to include an option to set whether to send the "OK" message or not?

Using v5.2.0
Influxdb

**Comment by JosvdP** [comment]
I see there was already a feature request for this. Sorry!
https://github.com/grafana/grafana/issues/6696

**Comment by marefr** [comment]
@JosvdP yes and a fix was recently merged and will be included in future v5.4 release.

**Comment by Siddhu1096** [comment]
When will be the update for the new version? OK alert is messing up things in alert feed. It'll be great if the new update releases soon.

**Comment by marefr** [comment]
@Siddhu1096 this was released in Grafana v5.4, see [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#540-beta1-2018-11-20).
