### ISSUE TITLE
Escaping "Custom" template variables

### ISSUE THREAD

**Issue by IntegersOfK** [grafana/grafana#13754]
Hello, I am trying to create a list of "custom" template variables and it appears I can't use a comma without it breaking my item into another selection. I've tried all kinds of escape methods I could come up with (wrapping in quotes, using backslashes, etc.), but the comma always separates.

It seems there is no way to tell Grafana that I want to keep the comma as part of my template var item.

Here is an example, I want each metric in the red circles to be part of the same selection item:
![image](https://user-images.githubusercontent.com/529833/47182742-3a7e2980-d2f4-11e8-8844-4dabe89151b8.png)

Wrapping in quotes doesn't help:
![image](https://user-images.githubusercontent.com/529833/47182853-86c96980-d2f4-11e8-95aa-92b5a86f90ca.png)

Backslash doesn't do it either:
![image](https://user-images.githubusercontent.com/529833/47182880-a2347480-d2f4-11e8-9e2b-60c78e97246e.png)

Grafana v5.2.4

**Comment by IntegersOfK** [comment]
My pull request #14405 adds this feature.
![image](https://user-images.githubusercontent.com/529833/49691427-f2b79980-fb0f-11e8-85eb-3f7201c5a2b7.png)

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/14405
