### ISSUE TITLE
grafana loses quotes when going between its parsed version and the query editor

### ISSUE THREAD

**Issue by marcogallotta** [grafana/grafana#1375]
Eg, start with something like
movingAverage('1m') in the parsed query.
This keeps its quotes when you switch to the editor, and then loses them (visually) when you switch back to the parsed query.

But then when you actually perform an edit on the parsed version of the query, the input genuinely loses its quotes, which breaks the query.

This seems likely to be related to the fact that this field (for movingAverage) can take either strings or numeric data.

**Comment by torkelo** [comment]
I fail to replicate this, no matter how much I change the movingAverage parameter in the text editor mode or in the query editor mode (trying going back and forth between number and string timespan). 

Could you explain the exact steps and replicate it on http://play.grafana.org/#/dashboard/db/grafana-play-home?panelId=2&fullscreen&edit  ? 

I know you explained the steps, but tried to follow it but could not replicate it

**Comment by marcogallotta** [comment]
Can't repro there, so I'm guessing it's fixed since the 1.9-rc1 release we're using. Thanks!
