### ISSUE TITLE
Stackdriver datasource: allow project switching in query builder

### ISSUE THREAD

**Issue by wleese** [grafana/grafana#13757]
### What Grafana version are you using?
5.3.1

### What datasource are you using?
Stackdriver

Currently there is a 1 on 1 mapping between datasource and google cloud project stackdriver metrics. In our setup we have a large amount of projects managed through an internal provisioning tool. While it would be possible to auto-create a datasource for all these projects or provide an optin mechanism, we'd prefer to use a single datasource with the ability to select the actual project in e.g. the Metrics tab of a graph.

![screenshot_20181019_150716](https://user-images.githubusercontent.com/2562645/47220149-3a902f00-d3b1-11e8-853a-a6fb3df5c423.png)

In a way the current query builder seems to imply this may be possible in the future.

**Comment by daniellee** [comment]
I think that a service account key file is required per project. This means that the Config page has to support uploading multiple key files. In the query editor, the caching would have to be extended to support multiple projects.

Including this feature request in the milestone for the Grafana 6.0, which is when Stackdriver will be marked as stable.

**Comment by wleese** [comment]
> I think that a service account key file is required per project

I could be wrong, but when I look at my IAM tab of project A I can add members from project B to Roles such as Monitoring.viewer that pertain to project A, allowing cross project permissions. 
After adding a single account to all our projects' Monitoring.viewer roles, we should be able to use the key of this single account to access all Stackdriver metrics.

But even if this was impossible somehow, there could be merit in the ability to use a single data source, to avoid having hundreds of them (we already have hundreds of google cloud projects).

**Comment by NaurisSadovskis** [comment]
> I think that a service account key file is required per project

Presuming the single service account has access to Monitoring Viewer permission on other projects, this will work. We have 500+ projects, I granted Monitoring Viewer permissions on the organisation level and hardcoded other projects [here](https://github.com/grafana/grafana/blob/v5.3.x/pkg/tsdb/stackdriver/stackdriver.go#L568) and it works with no issues. From what I understand, backend code gets project ID from the JSON secret passed during the Data Source setup, so I see no reason why this can be extended to allow either a dropdown with all available projects or a parameter within the query.

**Comment by sunker** [comment]
Seems like it's also possible to list all projects that the service account is granted access to by using the [resource manager](https://cloud.google.com/resource-manager/reference/rest/v1/projects/list) api. For that to work the service account needs to have the scope `cloudplatformprojects.readonly`. 

Possibility to switch between projects in the query editor and by using template variables will be implemented, I just don't know when yet. I'll get back to you.

**Comment by NaurisSadovskis** [comment]
@sunker I've submitted a PR with this feature. Can you have a look, please?

**Comment by sunker** [comment]
Thanks @NaurisSadovskis, I'll look into the PR next weak.

**Comment by sunker** [comment]
I've opened a new [issue](14764) describing the suggested solution for this problem.
