### ISSUE TITLE
Creating annotation when graph panel has no data points position the popup outside viewport

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#13765]
### What Grafana version are you using?
v5.3.1
### What did you do?
Created an annotation in graph panel with no data points
### What was the expected result?
Create annotation popup should be displayed under mouse cursor 
### What happened instead?
Create annotation popup is displayed in upper left corner somewhat outside viewport
![image](https://user-images.githubusercontent.com/1668778/47228046-89938f80-d3c4-11e8-95b0-b0729d694491.png)

Can be reproduced in this dashboard: https://play.grafana.org/d/tXtINb1iz/annotations-by-tag?orgId=1

**Comment by banjeremy** [comment]
I think I can help out with this.
