### ISSUE TITLE
Feature: Custom Time Ranges (user defined)

### ISSUE THREAD

**Issue by Tatranskymedved** [grafana/grafana#13766]
New feature idea: User defined "Custom Time Ranges".

This would allow either _user_ or the _dashboard_ to carry on Custom predefined values of TimeRanges. These options should be then visible next to the Quick Ranges.

Purpose:
We found several usages, where the user need to check last working shift (and some more shifts before). By creating those, user would have easy access to predefined ranges. This might have variety of usage. 

This can go even further, when the user would select predefined range and then moved by "<"/">" in either time way, it could just use previous/next value in the list.

Currently, we are working with out team on the extension and we would like to submit PR. We have several questions in mind - would this feature be accepted? Isn't there anything working/in-creation state like that already? What is all the functionality that should be covered?

Example screenshots:
![grafanacustomtimeranges_create](https://user-images.githubusercontent.com/2912979/47227662-aed3ce00-d3c3-11e8-9b97-26301d7cb88a.png)
![grafanacustomtimeranges_usage](https://user-images.githubusercontent.com/2912979/47227663-aed3ce00-d3c3-11e8-92de-773dff6cea56.png)

----

One of my first posts on Github, hopefully I pinned it at the right place. If not, please forgive me and set me on the right rails. Thanks!

**Comment by Chris-Hicks** [comment]
+1. I like the idea of this. Where grafana is being used for manufacturing monitoring/trending you may want to align with shift times i.e. 6am-2pm, 2pm-10pm, 10pm-6am

**Comment by torkelo** [comment]
nice mockup, can you post that to this issue? https://github.com/grafana/grafana/issues/2417 

Closing this as a duplicate.
