### ISSUE TITLE
TV / kiosk URL param minor discrepancy

### ISSUE THREAD

**Issue by Khord** [grafana/grafana#13764]
### What Grafana version are you using?
5.3.1
### What did you do?
Press TV mode button to get to kiosk mode
### What was the expected result?
Observed `&kiosk=1` in URL, expected that URL to function if I hyperlinked it somewhere
### What happened instead?
Hyperlink showed dashboard in normal mode instead of kiosk mode
Turns out kiosk only works if passed as `&kiosk` and not `&kiosk=1`. I feel like the latter should be made functional as well so that when people copy URLs from their browser after clicking the TV button, it reproduces the correct view. `&kiosk=tv` works as expected.

**Comment by torkelo** [comment]
thanks for reporting this, fix incoming!
