### ISSUE TITLE
Debian package should not depend on golang-go

### ISSUE THREAD

**Issue by a13xb** [grafana/grafana#13779]
Please include this information:
### What Grafana version are you using?
2.6.0

### What datasource are you using?
N/A

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
[Installed Grafana from packagecloud](http://docs.grafana.org/installation/debian)

### What was the expected result?
Successful installation

### What happened instead?
I have Go 1.11 installed using [`godeb`](https://github.com/niemeyer/godeb), which conflicts with Ubuntu's own `golang-go` (Go 1.6) package, so Go installation fails and `apt-get install` exit is not clean.

If you don't have third-party Go installations, it's benign. However, there is no reason for Grafana binary distribution to depend on Go, because it just ships a binary and doesn't seem to build anything, from what I can see in the package contents. Go binaries are statically linked and don't depend on any external runtime, so dependency on `golang-go` can be removed.

**Comment by torkelo** [comment]
Closing this as you must have accidentally created two identical issues
