### ISSUE TITLE
Debian package should not depend on Go

### ISSUE THREAD

**Issue by a13xb** [grafana/grafana#13778]
### What Grafana version are you using?
2.6.0

### What datasource are you using?
N/A

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
[Installed Grafana from packagecloud.](http://docs.grafana.org/installation/debian)

### What was the expected result?
Successful installation.

### What happened instead?
I have Go 1.11 already installed using [`godeb`](https://github.com/niemeyer/godeb), which conflicts with Ubuntu's own `golang-go` package (Go 1.6), so Go installation fails and `apt-get install` exit code is not clean.

This particular problem is niche, and if you don't have third-party Go installations, it's benign.

However, there is no reason for Grafana binary distribution to depend on Go build tools. From what I can in the package contents, it doesn't build anything and just ships a single binary. Go binaries are statically linked and don't depend on any external runtime, so `golang-go` dependency should be removed.

**Comment by torkelo** [comment]
Grafana deb package does not depend on golang-go , only on adduser and libfontconfig

**Comment by a13xb** [comment]
You are right. PEBCAK. Turns out I've got the package source wrong, and was installing the system version that does have a dependency on Go.
