### ISSUE TITLE
Feature Request: Add Table of Contents and hierarchy features for navigation

### ISSUE THREAD

**Issue by chemphill** [grafana/grafana#1378]
The ability to search for pages, graphs, and metrics is very nice, but there is a point where this will not scale well.  It would be very helpful to have an easy way to setup a hierarchy with links to pages.  For example, the ability to create parent and children pages where the links to children are auto-populated on the parent pages.  And/Or a menu at the top of the pages for navigation.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1944
