### ISSUE TITLE
Column per label in time series aggregated table panel

### ISSUE THREAD

**Issue by shakuzen** [grafana/grafana#13782]
Please include this information:
### What Grafana version are you using?
Grafana v5.3.1
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
MacOS
### What did you do?
Use Table panel, Format as Time series, Table Transform: Time series aggregations
### What was the expected result?
Labels in the time series would be columns, as they are when using "Format as Table"
### What happened instead?
One column "Metric" is displayed instead of individual columns per label like when using "Format as Table". Without columns per label, I cannot figure out how to use a label value in the Column Styles → Link Url. I also cannot sort the table by an arbitrary label's value.

**Comment by xlson** [comment]
@shakuzen Could you achieve what you are trying to do by doing the aggregations in the query to prometheus and then use the Table Transform to show the output?

**Comment by shakuzen** [comment]
@xlson Right now, it is only possible with a recording rule in Prometheus. I want to show in tables things like the max request rate or max response time per labels `(application, method, uri)` over the time range selected in Grafana. Prometheus has [\<aggregation\>_over_time() functions](https://prometheus.io/docs/prometheus/latest/querying/functions/#%3Caggregation%3E_over_time()), but they [don't work with range vector functions](https://www.robustperception.io/composing-range-vector-functions-in-promql). In the future, [sub-queries might be added](https://github.com/prometheus/prometheus/issues/1227), but they are not available now.

**Comment by habdank** [comment]
I am not sure, but I have similar problem when using Prometheus data source, 
but some differences prometheus query: 

sum without(instance, job)(rate(kafka_server_brokertopicmetrics_messagesin_total[5m]))

this ends up in map with for example 

Key: {topic="my_topic"} Value: 10.0

But chosing Timeseries aggregations  I got in Grafana UI (TS exception):

vendor.4ad1072db19f1dad74f5.js:130 TypeError: Cannot read property 'length' of undefined
    at t.isMsResolutionNeeded (time_series2.ts:362)
    at new t (time_series2.ts:165)
    at Object.transform (5.4ad1072db19f1dad74f5.js:10)
    at 5.4ad1072db19f1dad74f5.js:10
    at t.render (5.4ad1072db19f1dad74f5.js:10)
    at e.render (5.4ad1072db19f1dad74f5.js:10)
    at e.transformChanged (5.4ad1072db19f1dad74f5.js:10)
    at fn (eval at compile (vendor.4ad1072db19f1dad74f5.js:130), <anonymous>:4:184)
    at c.$eval (vendor.4ad1072db19f1dad74f5.js:130)
    at vendor.4ad1072db19f1dad74f5.js:130

Is it similar problem?

**Comment by xlson** [comment]
@habdank I'd suggest creating your own issue as what you are experience is a bug while what @shakuzen is for us to support a new feature.

**Comment by anitakrueger** [comment]
@shakuzen I've recently encountered exactly the same problem. My labels are displayed under "Metric" instead of as columns in the table when trying to use aggregations.
Have you found a workaround by any chance?

**Comment by shakuzen** [comment]
> Have you found a workaround by any chance?

I have not.

**Comment by anitakrueger** [comment]
So, I think I made this work using the aggregation over time functions from prometheus by using the `$__range` variable like this:
```
avg(avg_over_time(bytes_total{environment="dev"}[$__range])) by (username, destination, port)
```
The above query gives me username, destination and port as columns as well as the metric

**Comment by C-Duv** [comment]
@anitakrueger I am facing the same issue and tried your PromQL query `avg(avg_over_time(my_metric{label1="foo"}[$__range])) by (label2, label3, label4)` without success: I still have a single "Metric" column containing `{label2="bar",label3="qux",label4="zzz"}`.
If you have some example (eg. on https://play.grafana.org) I could manipulate I would appreciate.

**Comment by ivanahuckova** [comment]
Hello @shakuzen, since Grafana 7, we have changed the table panel and added transformations. Moreover, in Prometheus 2.7.0 release, subqueries were added. So I am wondering if you think we could close the issue or if you think this is still relevant. If it is relevant, could you please provide more information - e.g. What is the query? What is the expected result? 
Thank you!

**Comment by shakuzen** [comment]
@ivanahuckova Thanks for the follow-up. Indeed with the transformation "Labels to fields" I am able to get the behavior I wanted. So I believe this can be closed now as that solution is available on the latest versions.

**Comment by ivanahuckova** [comment]
Awesome! Thanks @shakuzen. 🙏
