### ISSUE TITLE
Give user guidance what to do with an exported dashboard

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#13792]
When exporting a dashboard there's no information how to use the exported data. We have a dead end. Maybe link to the [Export and Import](http://docs.grafana.org/reference/export_import/) in the docs?

![screenshot 2018-10-23 14 12 10](https://user-images.githubusercontent.com/224493/47359830-0462f000-d6ce-11e8-9b83-6eb91d75a6ed.png)
![screenshot 2018-10-23 14 12 53](https://user-images.githubusercontent.com/224493/47359835-0af16780-d6ce-11e8-8c7d-261f352805d2.png)

**Comment by torkelo** [comment]
Good suggestions, I think we can update this tab quite a bit with info text and an option that I outlined in this issue:

Will close this and incorporate your feedback on that issue. 

https://github.com/grafana/grafana/issues/13781
