### ISSUE TITLE
Cloudwatch using a hardcoded region when retrieving regions thru DescribeRegions

### ISSUE THREAD

**Issue by buroa** [grafana/grafana#13797]
Team,

[Related to AWS isolated regions only]

I tested the latest changes with the Cloudwatch hardcode issue (https://github.com/grafana/grafana/pull/12337). In deployment, the Grafana server automatically tries to connect to us-east-1, instead of my default region issued to my datasource, which would be us-iso-east-1. I manaully built a new version using us-iso-east-1, and it works just fine. Is there a way we can assume the client to use the datasource default region instead of using us-east-1?

This line is the issue: https://github.com/grafana/grafana/pull/12337/files#diff-1bc1bcaa896482730fda8a2d539fb247R242

Steve

**Comment by buroa** [comment]
To add onto this: 

If you deploy Grafana into an isolated region and utilize a normal region, say us-east-1, the entire grafana-server instance will come to a halt until the request timed out, and then everything will load again. Is this a known issue? I'm unaware if everything sits on the same thread.

**Comment by marefr** [comment]
@mtanda would it be possible to use the region defined for the datasource instead of hardcoded us-east-1?

**Comment by buroa** [comment]
I'm also wanting to tag this: https://github.com/aws/aws-sdk-go/issues/2219. I'm going to make a custom resolver and have a pull request here shortly, probably tomorrow.
