### ISSUE TITLE
Order in graph with X-Axis Series mode

### ISSUE THREAD

**Issue by henriqueschmidt** [grafana/grafana#13798]
How can i order by max value X-axis in series mode?

**Comment by torkelo** [comment]
Can you sort your series by max value in the query ? Most TSDBs can do that

**Comment by henriqueschmidt** [comment]
sorry for not describing better the problem, I already used the "order by" in PostgreSQL, but it did not work. See an example as shown below.
![screenshot from 2018-10-24 13-43-36](https://user-images.githubusercontent.com/30303963/47447494-07281880-d794-11e8-9204-b83ea6409f41.png)
