### ISSUE TITLE
sparklines in singlestat no longer convey trends in data.

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#13800]
https://github.com/grafana/grafana/pull/12010  introduced a change so that sparklines use auto y-axis.
This is useful for monotonically increasing counter where the counter is already large.  But this change breaks utility of the sparklines for gauges.

The purpose of the sparkline is to show trends. Without a reference scale this is no longer possible.   If a metric is mostly constant then has spike/drop it is impossible to tell the how big the change was.  A 1% and a 90% drop would both be rendered the same.

**Comment by daytonturner** [comment]
i can see the value of both methods - perhaps a toggle to go between the modes?

**Comment by alekseyl1992** [comment]
would be nice to be able to set `min` to zero and auto-scale `max`
so that RPS-like single-stats would not jump that much when there is no actual big change in the data
