### ISSUE TITLE
MySQL Generated SQL escaping problems

### ISSUE THREAD

**Issue by lucamanga** [grafana/grafana#13808]
Using Grafana 5.1.

The Metrics is:
```
SELECT   count(*) 
FROM table
WHERE Service in ($Service)
```
The problem is in $Service, that has multiple string values. It seems that Grafana doesn't escape some characters. In fact, the Generated SQL states:
```
 ... , '[IT-095] Service0001::Opere d'arte',
       '[IT-100] Service0002::Test', ....
```
The word *Opere d'arte* has a quote that is not escaped and this generates a MySQL error.

Is there any way to escape the value?

**Comment by svenklemm** [comment]
This should be fixed in any of the 5.3 versions.
