### ISSUE TITLE
wrong NODATA alert 

### ISSUE THREAD

**Issue by sonchu** [grafana/grafana#13816]
### What Grafana version are you using?
5.3.1
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Centos 7
### What did you do?
Add alert on some graphs
### What was the expected result?
Correct alert at the threshold
### What happened instead?
NODATA alert when data was available

Hi there,

I am getting a lot of NODATA alert when data is available. As far as I know, the most problem caused that issue was the time between client and server when pushing data from client to InfluxDB. But I have checked many times and time was correct. No issue with it. And in additional, the number of server under monitoring was just 20 (monitor CPU, RAM, OS metrics), not much I/O for an database (InfluxDB). I tried to config log to run as debug mode but actually there was nothing effective. 

Could you please advise me on this? 

Thanks in advance.

Son

**Comment by torkelo** [comment]
Try to increase the time range of the query in the alert. Can you show your query and result from Test Rule?

**Comment by sonchu** [comment]
Hi Torkelo,

I will try to increase the time range. But could you please explain the difference when I increase the time range? I would like to know about the case of 1m and 5m. What will happen if i specify 1m instead of 5m?

Please have a look at below screen shot with NODATA alert (A,1m,now):
https://imgur.com/a/B2zOPNr

My query is:
SELECT mean("Available_Bytes") FROM "win_mem" WHERE ("host" = '192.168.1.2') AND $timeFilter GROUP BY time(30s) fill(null)

The response is:

> firing:false
> state:"ok"
> conditionEvals:"false = false"
> timeMs:"3.627ms"
> logs:Array[2]
> 0:Object
> message:"Condition[0]: Query Result"
> data:Array[1]
> 1:Object
> message:"Condition[0]: Eval: false, Metric: Available Bytes, Value: 1237626880.000"
> data:null

Could you please advise?

Thanks in advance.

Son

**Comment by bergquist** [comment]
` NODATA alert (A,1m,now):` is a very short time window if you group by 30s. Especially if the data ingest in influx is slow at sometimes or mismatching the time range of the query. We strongly suggest that you increase the time window on your alerts to avoid false positives or use the new `FOR` setting available in grafana 5.4
