### ISSUE TITLE
Explore: tabl completition of label values fails if they contain a `/`

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13813]
Ie the completion works up to the slash, then stops.

![wjy9xx0lbj](https://user-images.githubusercontent.com/444037/47454647-b4535e80-d79d-11e8-9fc0-ee820b6378be.gif)

**Comment by davkal** [comment]
@miqh this could be interesting for you

**Comment by miqh** [comment]
@davkal, I'm fairly sure this is resolved by a previous pull request of mine (#13663). :relaxed:

Which version are you using @tomwilkie?

**Comment by tomwilkie** [comment]
Also fails for `-`.

> Which version are you using @tomwilkie?

5.3.2; add2e44 is pretty broken for me right now (will file more bugs)

**Comment by tomwilkie** [comment]
Yeah its fixed in master.
