### ISSUE TITLE
stackdriver: access token not passed to the API

### ISSUE THREAD

**Issue by kornholi** [grafana/grafana#13815]
### What Grafana version are you using?
5.3.1, 5.3.2

While trying to create a Stackdriver datasource, the validation step fails with:
> Stackdriver: 401. Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

The project and service account email show up correctly in the UI. Both APIs are enabled in the project.

The logs also show that it's trying to do the right thing:
> lvl=info msg="Got new access token" logger=data-proxy-log ExpiresOn=2018-10-24T01:31:08+0000
> lvl=info msg=Requesting logger=data-proxy-log url=https://content-monitoring.googleapis.com/v3/projects/foo-bar/metricDescriptors

cc @louisvernon @timbuktuu

**Comment by torkelo** [comment]
Have you uploaded the token in the datasource settings? 

Can you try reuploading the token?

**Comment by kornholi** [comment]
Yes, I tried both uploading and pasting in the service account several times. The metadata shows up correctly in the UI.

**Comment by sunker** [comment]
@kornholi are you still having the same problem? If so, can you please try to configure the datasource using provisioning and let us know how it went? Guide to use provisioning for Stackdriver can be found [here](http://docs.grafana.org/features/datasources/stackdriver/#configure-the-datasource-with-provisioning)
