### ISSUE TITLE
Misleading Graph is generated by Grafana when data is is missing in between range of dates  

### ISSUE THREAD

**Issue by akshattandon** [grafana/grafana#13817]
Hi All, 

There is a bug in Grafana that it generates Misleading Graph  when data is missing in between a range of dates
Eg. 
Use Case 1 
  We select Range of dates as 23rd Oct to 25 Oct and metric in DB is from 24 Oct 

Expected Output 
 Grafana shows the data from 24 Oct and, no line before that day 

Output 
  Grafana shows the correct expected output as line till date where we have the data after which no data  
  
![image](https://user-images.githubusercontent.com/3425989/47471903-01503700-d869-11e8-97cc-3f64f097be60.png)

Use Case 2
  We select Range of dates as **19 Oct to 25 Oct and metric in DB is from 24 Oct** 

Expected Output 
 Grafana shows the data till 22 Sep and after it, no line being displayed till 28 Sep and than again line on 29 sep 

Output 
  Grafana shows the line even on the days when we have no we have the data Eg for days from 22 till 28 sep no line should get displayed but it shows continuous misleading line.
  

![image](https://user-images.githubusercontent.com/3425989/47471920-1a58e800-d869-11e8-9620-3ea9dc0071ff.png)

So in all the bug seems to be 
when we select a range of dates where you have data missing in that range of date it shows data correctly but when we select a range of dates where we have data earlier and after the missing data it shows continuous line instead of a broken line. 

Please include this information:
### What Grafana version are you using? 
Grafana v5.2.2 (aeaf7b2)

### What datasource are you using?
MySQL 
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Nothing 
### What was the expected result?
Broken lines 
### What happened instead?
Continous line of data 
### If related to metric query / data viz:
Yes

**Comment by torkelo** [comment]
if you have periods of missing data Grafana will show that, but your query needs to return missing data (nulls). Most data sources support this. 

Use the $__timeGroup(dateColumn,‘5m’, NULL) macro to group by date range and fill nulls for missing groups
