### ISSUE TITLE
Confusion about what json format is supported by provisioning

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#13829]
Currently, we have two ways to export the json for a dashboard. 

1) Share -> export
2) Settings -> View json

Provisioning does only support #2 
Either we have to improve the UX/docs that it's obvious in which format a dashboard should be exported or we could support variable in provisioning. https://github.com/grafana/grafana/issues/10786

I created this issue since I don't know how we will solve this yet.

**Comment by torkelo** [comment]
I already created an issue for exactly this problem (and more) I think, like 2 days ago ;)

https://github.com/grafana/grafana/issues/13781

Combine them/close one?

**Comment by bergquist** [comment]
haha yea :)
