### ISSUE TITLE
Datasource annotation queries are not triggered/rendered

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#13821]
### What Grafana version are you using?
master 4ee79faff4acfdaf1ae5a79714aa4cb275c628ae
### What datasource are you using?
Postgres, MySQL
### What did you do?
Have a dashboard with annotation queries using Postgres/MySQL which are disabled per default and not hidden. Then in dashboard I check the annotation checkbox to enable annotations
### What was the expected result?
Annotations query should be triggered and returned data should render as annotations in graph panel.
### What happened instead?
Annotations query are not triggered

After some investigations seems like this commit 4f4bba7f8cf6eb7cc419662633917c27eeb5cce2 introduced the bug since the commit before 1d0dee189cd7ea823054063aa1d17dfeb223a8ff does not have this bug. So this is only an issue in the master branch and not in a stable release.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/commit/be6f68f341a3b10ae483236d483eafecb09a3bd1
