### ISSUE TITLE
Hole on stacked bar graph

### ISSUE THREAD

**Issue by edum18** [grafana/grafana#13832]
### What Grafana version are you using?
Grafana v5.4.0-pre1 (commit: 2c8c5098c)
### What datasource are you using?
Microsoft SQL Server
### What OS are you running grafana on?
Windows 10
### What did you do?
Created a bar graph with 2 queries to stack them together.
### What was the expected result?
Bars with stacked data.
### What happened instead?
Everything's fine except that there is a hole on a stacked bar.
Bar graph screenshot: 
https://i.imgur.com/B72qvbz.png 
I have 2 queries which one has 7 rows and the other has 6 rows. Response screenshot: https://i.imgur.com/ZzIDXJV.png
The second bar shouldn't be floating. If I enable the Percent option it works fine but it's not what I want. I tried switching options on "Null value" too.
Is this possible to fix? Maybe it's because I need to update grafana?
Thank you.

**Comment by torkelo** [comment]
Looks like you have time period with missing data for one of your series. Make sure you have null value set to 0 and you group your data by a time interval with a fill option (0 or null) 

`$__timeGroup(dateColumn,‘5m’, 0)`

**Comment by edum18** [comment]
In case of anyone with the same problem:
As torkelo said, I fixed it by replacing my date column to `$__timeGroup(datecolumn,'24h', 0)`. Since my query is based on daily data, I used an interval of 24h. After this, setting "Null value" to "null as zero" may help too.
