### ISSUE TITLE
Nested variables are not calculated in the repeated rows

### ISSUE THREAD

**Issue by 123BLiN** [grafana/grafana#13837]
### What Grafana version are you using?
5.3.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Docker official
### What did you do?
Create two templated variables var1 and var2.
var2 is depending on var1 ( var2= ....{some_label=~"$var1"}...)
Create row with the panel "Text" and place there $var2
Switch row to repeated by var1
### What was the expected result?
var2 value should be calculated based on row's var1 value for every row
### What happened instead?
var2 value in text panel is the same for all rows and equals last calculated value (for first row usually) 

I think it may be related to the #13628 but not sure

**Comment by torkelo** [comment]
Sadly this use case is not supported , query variables are not execute per repeated row.

**Comment by 123BLiN** [comment]
Thank you @torkelo ! I'm almost sure that this works with the Elasticsearch backend.
However probably you have reasons to not support the same with Prometheus.

**Comment by torkelo** [comment]
no it's not supported for any data source.

**Comment by 123BLiN** [comment]
after some thinking - yes, you are right of course - the problem is that text panel just don't make any queries, so I will just move to the table panel.

Thanks again!
