### ISSUE TITLE
Singlestat MySQL query null results show as "undefined".  Unable to set value mappings

### ISSUE THREAD

**Issue by n406c** [grafana/grafana#13838]
I am trying to map the results of a query (which are sometimes null) to a name.  The Singlestat panel will only allow me to map the value if the result is found.  If null, it will display "undefined" and not allow any value mapping.  I've read from similar posts that this was resolved by simplifying the query but I'm pretty sure I can't make it more simple than this. Below is my query:

SELECT TECH_ID
FROM whd.active_session 
WHERE TECH_ID=71

What Grafana version are you using? **Grafana v5.3.0 (c613a31)**
What datasource are you using? **MySQL**
What OS are you running grafana on? **Ubuntu 16.04**

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/47520274-08d70680-d890-11e8-9f2b-7e44d036689e.png)

What are you singlestat options ?

**Comment by n406c** [comment]
![default](https://user-images.githubusercontent.com/44477185/47520964-870ebb00-d846-11e8-96e2-e45a582ee294.png)

I am using just the default Singlestat panel with no modifications.  With my current query and the current default settings I should expect mapped value "N/A".

**Comment by n406c** [comment]
![options](https://user-images.githubusercontent.com/44477185/47522131-9a6f5580-d849-11e8-9a4d-154d55dcc7fe.png)

Yes.

**Comment by n406c** [comment]
![works](https://user-images.githubusercontent.com/44477185/47524558-c392e480-d84f-11e8-8152-b8a7b9cfef77.png)

If I change the where clause to find a value currently present in the column, then the value mapping works.

**Comment by torkelo** [comment]
and when you use query inspector what does it show your query returning?

**Comment by n406c** [comment]
**This query is with the null result.**
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1540495985278",
      "to": "1540496285278",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 2000,
          "maxDataPoints": 100,
          "datasourceId": 8,
          "rawSql": "SELECT TECH_ID\nFROM whd.active_session\nWHERE TECH_ID=71",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 0,
          "sql": "SELECT TECH_ID\nFROM whd.active_session\nWHERE TECH_ID=71"
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "TECH_ID"
              }
            ],
            "rows": []
          }
        ]
      }
    }
  }
}

**This one is with the where clause finding a present value.**
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1540496045282",
      "to": "1540496345282",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 2000,
          "maxDataPoints": 100,
          "datasourceId": 8,
          "rawSql": "SELECT TECH_ID\nFROM whd.active_session\nWHERE TECH_ID=70",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 2,
          "sql": "SELECT TECH_ID\nFROM whd.active_session\nWHERE TECH_ID=70"
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "TECH_ID"
              }
            ],
            "rows": [
              [
                70
              ],
              [
                70
              ]
            ]
          }
        ]
      }
    }
  }
}

**Comment by n406c** [comment]
I believe I have found a workaround to my problem.  If I modify the query to also include null results, I am finally able to map the values.

SELECT TECH_ID
FROM whd.active_session
WHERE TECH_ID=51 OR TECH_ID IS NULL;
