### ISSUE TITLE
Expiring GPG key at packagecloud.io

### ISSUE THREAD

**Issue by corywright** [grafana/grafana#13830]
The GPG key referenced in the [Debian/Ubuntu installation instructions](http://docs.grafana.org/installation/debian/#apt-repository) is expiring soon, on January 12, 2019:

    $ curl https://packagecloud.io/gpg.key | sudo apt-key add -
    $ apt-key list
    <...>
    pub   4096R/D59097AB 2014-01-13 [expires: 2019-01-12]
    uid                  packagecloud ops (production key) <ops@packagecloud.io>
    sub   4096R/7AD95B3F 2014-01-13 [expires: 2019-01-12]

I emailed support@packagecloud.io about this and received the following response:

> It looks like grafana has not migrated to the new unique, per-repository key that we have moved everyone to: https://blog.packagecloud.io/eng/2018/10/17/gpg-key-migration/
> 
> Might be worth reaching out to them and encouraging them to migrate their key, as it will stop working in January 2019.

**Comment by torkelo** [comment]
yes, I have received emails about this. Will migrate soon.

**Comment by gagantrivedi** [comment]
It is now [expired: 2019-01-12]

**Comment by marefr** [comment]
@gagantrivedi please refer to https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/

**Comment by xlson** [comment]
@insideClaw please refer to https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/, we are no longer using packagecloud for Grafana.

**Comment by nodakai** [comment]
@marefr @xlson Can you put a warning in red, bold text that packagecloud is no longer supported at the top of http://docs.grafana.org/installation/rpm/ ?
