### ISSUE TITLE
Can´t change login page background color and icons

### ISSUE THREAD

**Issue by F-117** [grafana/grafana#13834]
My OS: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-36-generic x86_64)
My grafana version: V5.3.1

Hi grafana developers and suporters.

I just want to change grafana's login page background color to white and delete the "grafana" text below the grafana icon.
I tried changing all the .html inside` /usr/share/grafana/public/`views searching for a way to delete the "grafana" for my company and I also changed lots of lines in all .scss and .json putting "`background-color: white;`" in every corner containing a body or the word login.
I googled this and searched in youtube too (I dont like to disturb others with this kinds of questions but im out of time).

I know it has something to do with a `<div>` called "`ng-view`"... looks empty but when i delete it, all the login page gets deleted (except the "docs, suport, comunity, grafana version, etc")

I would greatly apreciate if anyone could give a hand in how to configure those 2 things in html/css and where to find the exact line.

Thanks in advance!

**Comment by torkelo** [comment]
you will need to fork grafana repo, modify this file, https://github.com/grafana/grafana/blob/master/public/app/partials/login.html 

read the building from source guide on docs site for help on building a custom build
