### ISSUE TITLE
Direct link image generating tries to render invalid url on remote machine

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#13848]
When running on localhost macos 10.14 everything is just fine.

When running on server on debian, the Direct link for panel image rendering doesn't work. I managed to track down that it tries to render this url:

http://127.0.0.1:3000/d-solo/17beb11c006773a2f9ce8d8b75969504/db-name?render=1

However, it should try to render this url:

http://127.0.0.1:3000/render/d-solo/17beb11c006773a2f9ce8d8b75969504/db-name?orgId=1&panelId=2&from=1540547099365&to=1540633499366&width=1000&height=500&tz=Europe%2FWarsaw

It somehow fails to give the renderer valid url but I'm still not sure why it behaves differently on remote machine. Grafana somehow instead of adding `/render/` part to solo panel url and passing query parameters, it instead gives `render=1` as query parameter and overwrites the other parameters.

**Comment by torkelo** [comment]
The server side rendering works like that, publicly the api is for /render/...  that will open a phantomjs browser with the url (without /render) and grab an image. The width and other dimensions is also for the phantomjs process and not passed to the url being grabbed 

Make sure your root_url grafana ini setting is correct (The one you use in browser to access grafana). 

Grafana server log for errors.

**Comment by simPod** [comment]
I see. The settings is correct. However, on remote machine, the query params are not passed to phantomjs, the dashboard url is tried to be rendered only with `?&render=1`

Locally, it adds `?from=1540388100754&to=1540560924754&kiosk&orgId=1&panelId=2&width=1000&height=500&tz=Europe%2FPrague&render=1` I'm still trying to track it down. The weird thing is that the grafana build is the same but behaves differently.
