### ISSUE TITLE
Explore: Syntax highlight breaks

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13851]
Version add2e44

<img width="1153" alt="screen shot 2018-10-27 at 12 03 22" src="https://user-images.githubusercontent.com/444037/47606341-65493b80-d9e0-11e8-8022-2b370e1595a5.png">

It came back shortly after.

**Comment by davkal** [comment]
Syntax rules are loaded in a blocking way, some query prometheus series API and take 10s of seconds. Only then the rules are applied. This should be noticeable after a datasource switch.
