### ISSUE TITLE
y-axis decimals ignored after unit conversion

### ISSUE THREAD

**Issue by stephen-soltesz** [grafana/grafana#13850]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.3.2

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Mac OS X - docker container - viewed from Chrome

### What did you do?
I created a query on a metric that is always an integer gauge value (i.e. 9, 14, etc). I changed the "Left Y" unit to "days (d)" and the "Decimals" to "0".

### What was the expected result?
I expected the result of the unit conversion to display with zero decimals.

### What happened instead?
The Y axis has values with decimals! e.g. "1.43 week".

<img width="646" alt="screen shot 2018-10-27 at 11 07 37 am" src="https://user-images.githubusercontent.com/1085316/47605782-fcaa9080-d9d8-11e8-8aa5-92e024c9da39.png">

**Comment by torkelo** [comment]
The decimals override will only be applied to the raw unit (days), but the days unit is a scaled unit that grafana will show as weeks / months / years etc. So to do that accurately Grafana needs to add decimal precision as it make that scaling. 

If you want full control of the decimals you need to pick "none" unit as it has no scaling
