### ISSUE TITLE
Show dashboard creation time in dashboard settings

### ISSUE THREAD

**Issue by Daryes** [grafana/grafana#13858]
Version : migration from 4.6.3 to 5.3.2

Unless I'm mistaken, this information seems to be lost since the metadata tab is not visible anymore.
The "Created at :" time information should be present either in the "General" or in the "Versions" tab in the dashboard settings, if not in its own panel.

**Comment by torkelo** [comment]
I can see it in the versions view under dashboard settings:

![image](https://user-images.githubusercontent.com/10999/47615768-f4735380-dab3-11e8-94a0-190a7657fa49.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
