### ISSUE TITLE
Explore: some queries cause screen to go blank

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#13854]
https://admin-ops-tools1.grafana.net/grafana/explore?state=%5B%22now-6h%22,%22now%22,%22prometheus%22,%22sort_desc(count%20by%20(state)%20(container_network_tcp_usage_total)))%22%5D

![s0vufayxje](https://user-images.githubusercontent.com/444037/47606429-9c6c1c80-d9e1-11e8-8c85-a17b19e9cf5e.gif)

<img width="970" alt="screen shot 2018-10-27 at 12 13 30" src="https://user-images.githubusercontent.com/444037/47606443-bad21800-d9e1-11e8-9038-f0e63accf9c0.png">

**Comment by davkal** [comment]
Addressed in #13842
