### ISSUE TITLE
Adding variable support on annotations

### ISSUE THREAD

**Issue by Seraf** [grafana/grafana#1385]
Hello,

I have a dashboard with a variable named "ENV" (for environment). It allows to have a unique dashboard for all environments.
I would like to display annotations too for the deployment, but only for the selected ENV.
It seems $ENV isn't replaced by the value and just displayed as "$ENV" instead of ['dev','staging','prod'].

I would like to use this variable on Name field and Graphite event tags field.
What do you think about this ?

**Comment by torkelo** [comment]
I am not sure what you mean Name field? You should be able to use $variables in the graphite events tags query field. At least since v1.7

**Comment by Seraf** [comment]
Oh sorry, I was using a lowercase tag where my variable was uppercase.
So this feature works great on my side (maybe should work no matter the (upper|lower)case ?).

The name field is the name of the annotation : 
![grafana-variables](https://cloud.githubusercontent.com/assets/393324/5892961/38da82b6-a4d3-11e4-801d-ba6c85ad598d.png)

The annotation name is Deploy-$ENV instead of Deploy-REC

**Comment by torkelo** [comment]
you can use variable value in the query, but not in the annotation name
