### ISSUE TITLE
Docs feedback: auth/gitlab.md

### ISSUE THREAD

**Issue by sjentzsch** [grafana/grafana#13855]
1.  Set `enabled = false` (currently it is `enabled = false` for all code blocks here)
2. Last paragraph, typo: `alloed_sign_up` -> `allow_sign_up`

**Comment by torkelo** [comment]
thanks for reporting this, 

here is the file to update: 
https://github.com/grafana/grafana/blob/master/docs/sources/auth/gitlab.md
