### ISSUE TITLE
Unit selector to react

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13868]
Need to rewrite the unit selector in react, suggest trying using react-select. 

<img width="423" alt="screen shot 2018-10-29 at 09 39 36" src="https://user-images.githubusercontent.com/10999/47638374-a8c9b400-db5e-11e8-8f16-7352f38b07f9.png">

The design does not need to be a menu with typeahead like above. Think if we use custom groups in react-select and make them collapsable that could also work.

**Comment by peterholmberg** [comment]
Yes, I think we could spend some time on rethinking this component as it is quite messy now? Like how we're grouping units. Maybe add some option to hide certain units as well?

**Comment by torkelo** [comment]
A description for some units could also be nice to show

**Comment by boyskila** [comment]
Hi, lazy loading? How often those units are changed? If Unit is selected only once then I think will be good to add those li's with ul's nested inside only when input is clicked. And to remove them on select as well. No need to populate DOM with redundant elements (twice as I can see). How do you think guys?
