### ISSUE TITLE
Feature Request: Add keepLastValue to the null point option mode list

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1386]
Add keepLastValue to the null point mode list on the display styles tab.  For some use cases this might be preferable over the current choices.  It will also guarantee that all metrics will always have a data point ensuring the shared tooltip will always display properly.

**Comment by sfleiter** [comment]
For me only using null point mode "null" in combination with keepLastValue() prevents the error message "series point counts are not the same".
So maybe this option should combine both settings?

**Comment by torkelo** [comment]
This should be supported by the database. Both influxdb and graphite supports it.
