### ISSUE TITLE
Query variable not returning all of the expected values, but it will eventually do after some refreshes (REOPENING)

### ISSUE THREAD

**Issue by snwbr** [grafana/grafana#13865]
Creating a new issue since last one was closed without discussing anything. Please don’t close this one. This is not a Prometheus issue, if you pay attention to what I wrote you can see that it’s the /api/datasources endpoint in Grafana what’s not responding accordingly. If I query Prometheus directly it returns all of the data right away.

https://github.com/grafana/grafana/issues/13843

Read before posting: 

Please include this information:
### What Grafana version are you using?
v5.3.2

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
CentOS Linux 7

### What did you do?
I've created a query variable. When performing the query, not all of the results are shown, even though Prometheus is showing them all. If Grafana's GET action is replayed, intermittently all of the results appear. But it never does it the first time. I'm testing with a low ammount of results (34) but it only return 32 or 33, sometimes the 34 values.

### What was the expected result?
All of the results queried from Prometheus should appear on the GET action.

### What happened instead?
Some of the results are missing.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

GET /api/datasources/proxy/1/api/v1/series?match[]=probe_http_version&start=1540571733&end=1540571793 HTTP/1.1
Host: 10.251.172.54
Connection: keep-alive
Accept: application/json, text/plain, */*
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Referer: http://XX.XX.XX.XX/d/-P-XxhKiz/services-health-dev?editview=templating&refresh=30s&orgId=1&panelId=&fullscreen=&edit=
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,es;q=0.8
Cookie: grafana_user=admin; grafana_remember=f26b45e5c5c6e81e269d667befd08487abe322ec9a875224e23d6355d2c691812b; grafana_sess=aa4abc131abcd321

HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Date
Cache-Control: no-cache
Content-Encoding: gzip
Content-Length: 381
Content-Type: application/json
Date: Fri, 26 Oct 2018 16:36:32 GMT
Expires: -1
Pragma: no-cache

(Changed the endpoints for security reasons), but it illustrates that endpoint 33 is missing).
{"status":"success","data":[
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/1/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/2/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/3/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/4/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/5/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/6/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/7/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/8/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/9/hcheck","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/10/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/11/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/12/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/13/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/14/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/15/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/16/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/17/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/18/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/19/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/20/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/21/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/22/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/23/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/24/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/25/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/26/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/27/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/28/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/29/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/30/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/31/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/32/health","job":"blackbox"},
{"__name__":"probe_http_version","instance":"https://dev-foo.bar.com/34/health","job":"blackbox"}]}

**Comment by torkelo** [comment]
Please don’t open duplicate issues again. We read all comments to closed issues and will of course open it again if we got it wrong.

This is a request to Prometheus , the api being called is the Grafana proxy api that will just forward the call to Prometheus.

See the /api/v1/series api In Prometheus docs
