### ISSUE TITLE
Backdrop visible after closing modal

### ISSUE THREAD

**Issue by timyllym** [grafana/grafana#13874]
Grafana 5.3
MacOS 10.13.6
Chrome 70.0.3538.77

1. Create two dashboards
2. Add e.g. single-stat panel on first dashboard and put there a link to the second dashboard
3. Click on the link icon of single-stat panel, which will open up an inspector modal dialog
4. Click on the text link of the second dashboard in the inspector modal
5. Grafana opens the second dashboard, but the backdrop of the inspector modal stays visible

Expected: backdrop of the modal should be removed when opening a new dashboard.

**Comment by torkelo** [comment]
> Click on the text link of the second dashboard in the inspector modal

What link inside the inspector modal??

**Comment by timyllym** [comment]
<img width="408" alt="shot01" src="https://user-images.githubusercontent.com/13029109/47651710-9b2b2300-db8c-11e8-8a2e-9c1ff189ee4a.png">

<img width="932" alt="shot02" src="https://user-images.githubusercontent.com/13029109/47651716-9f574080-db8c-11e8-8a97-1d96eededbae.png">

**Comment by peterholmberg** [comment]
Managed to reproduce this.

**Comment by aocenas** [comment]
The UI for panel links changed in later versions and this does not seem relevant anymore.
