### ISSUE TITLE
Singlestat panel and current value return avg

### ISSUE THREAD

**Issue by angeldestroyer** [grafana/grafana#13879]
### What Grafana version are you using?
 Grafana v5.2.4 (commit: 0bbac5c)
### What datasource are you using?
alexanderzobnin/grafana-zabbix (v. 3.9.1)
### What OS are you running grafana on?
Debian GNU/Linux 8 (jessie)
### What did you do?
Singlestat panel, Stat: Current, value changed from "1" to "2".
If time interval is more than three hours (in my case) = wrong value, avg.
### What was the expected result?
The current value does not depend on the time scale.
Must be the **current** value.
### What happened instead?
Average of the last ~four values
 
![image](https://user-images.githubusercontent.com/9303266/47650183-dcc1cb00-db98-11e8-9b4c-6746a5cb0853.png)
![image](https://user-images.githubusercontent.com/9303266/47651543-f2d18a80-db9c-11e8-9c7a-32bf2636d403.png)
![image](https://user-images.githubusercontent.com/9303266/47651711-5eb3f300-db9d-11e8-96bf-d67f4c996332.png)
etc.

possibly related to #11075, #13713

**Comment by torkelo** [comment]
can you show your singlestat panel options? 

I think this is a zabbix issue. Maybe due to zabbix returning strings? Cannot replicate this with any other datasource.

**Comment by torkelo** [comment]
<img width="810" alt="screen shot 2018-10-29 at 15 05 12" src="https://user-images.githubusercontent.com/10999/47654950-3c65a980-db8c-11e8-8e42-819a1262d18a.png">

**Comment by angeldestroyer** [comment]
![image](https://user-images.githubusercontent.com/9303266/47656249-27970f00-dba8-11e8-98c1-f20719cb558c.png)


If i input: "1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,1,1,1,2" in "String Input". It's realy show me last value.
(String is too long because "error" manifests itself only with a large number of values/large time interval)

**Comment by torkelo** [comment]
To troubleshoot more I suggest open zabbix datasource source file in chrome dev tools source and check what data the zabbix plugin is returning to the panel.

**Comment by angeldestroyer** [comment]
Thanks, I opened the issue in alexanderzobnin/grafana-zabbix, because I don’t know very well JS.
The returned data in the browser dev tool is similar to the query inspector.
