### ISSUE TITLE
Grafana + Elasticsearch - how to output text on singlestat control

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#13881]
Read before posting: 

Please include this information:
# What Grafana version are you using?
- `Version 5.3.0-pre1 (commit: 0f6e5e2)`.
# What datasource are you using?
- `Elasticsearch 6.4`.
# What OS are you running grafana on?
- `Ubuntu 18.04 LTS`.
# What did you do?
- `Want to create single stat and/or charts with text data`.
# What was the expected result?
- `This should just work. It works with InfluxDB output and PostgreSQL output`.
# What happened instead?
- `Can only select numeric fields.`.

 
We're adding ES output to our tools, currently, all dashboards use PostgreSQL as a data source. New dashboards using Elasticsearch all have ' ES' suffix.
For example, this dashboard in PostgreSQL uses text data for single stat values (top left single stat). It uses text description of a value length (like 2 days 13 hours 58 seconds etc):
- https://cncf.teststats.cncf.io/d/11/issues-age?panelId=2&orgId=1 (anybody can see it, there is a read-only editor mode enabled there).
- trying to do the same for Elasticsearch seems impossible, I cannot choose text field to be used as a single stat value: https://cncf.teststats.cncf.io/d/1011/issues-age-es.
I would expect to do it in a similar way to tabular views where I can select "raw document" first and then use "JSON data" to select fields to display, just like here: https://cncf.teststats.cncf.io/d/1005/companies-summary-es?orgId=1

Am I doing something wrong, or is it really impossible?

**Comment by torkelo** [comment]
sadly you cannot select text fields for ES metric queries (ES does not support it). You can select the Raw document which will return the raw ES doc to the panel but only the table panel supports this format.

**Comment by lukaszgryglicki** [comment]
OK, thanks, I was googling & googling and finally decided to ask here...

**Comment by dprokop** [comment]
@lukaszgryglicki I believe you can now achieve what you want with Grafana 7.1+ selecting Raw Data in Elastic query editor and using Stat Panel's **Field** and **Text mode** options described here https://grafana.com/docs/grafana/latest/panels/visualizations/stat-panel/#display-options
