### ISSUE TITLE
Dashboard provisioning starred as default

### ISSUE THREAD

**Issue by jackm** [grafana/grafana#13882]
### What Grafana version are you using?
5.2.4

### What datasource are you using?
InfluxDB 1.5

### What OS are you running grafana on?
Ubuntu 18.04.1 Linux

### What did you do?
Provisioned dashboards following the official [provisioning documentation](http://docs.grafana.org/administration/provisioning/).

I want to also be able to set a provisioned dashboard to be a starred dashboard by default. I could not find any configuration setting to set a dashboard as starred. The only way that I know of starring a dashboard is to either do it manually via the web GUI or to use the HTTP API.

### What was the expected result?
After a dashboard is added via provisioning, it should also be starred.

### What happened instead?
No known method of setting a dashboard as starred via provisioning.

**Comment by bergquist** [comment]
If you want to highlight provisioned dashboard somehow I suggest you add tag to those dashboards

**Comment by jackm** [comment]
> If you want to highlight provisioned dashboard somehow I suggest you add tag to those dashboards

Is tagging something that can be done via dashboard provisioning?
I don't see any config parameters related to "tag" within the [dashboard provisioning types](https://github.com/grafana/grafana/blob/master/pkg/services/provisioning/dashboards/types.go)

**Comment by bergquist** [comment]
You would have to add the tag to the dashboard json http://docs.grafana.org/reference/dashboard/#json-fields
