### ISSUE TITLE
How to install all the plugins in the grafana docker image ? 

### ISSUE THREAD

**Issue by mangeshkaslikar** [grafana/grafana#13889]
I was going through the documentation and it mentions that we can install specific plugins by mentioning it in the ENV variables. What parameter to pass so that it installs all the plugins ? 

Thanks. 

Mangesh

**Comment by torkelo** [comment]
There is a section for this in the docs
http://docs.grafana.org/installation/docker/#installing-plugins-for-grafana

**Comment by torkelo** [comment]
list all plugins you want?

**Comment by mangeshkaslikar** [comment]
din get your question
