### ISSUE TITLE
Add possibility to load grafana width certain dashboard 

### ISSUE THREAD

**Issue by evgenyf** [grafana/grafana#1388]
Hi.
I'm interesting ti have possibility to load specific ready grafana dashboard ( already saved in InfluxDB  and available in "open dashboards" list ) when its identifier passed as parameter in grafana url.
Thank you,
Evgeny

**Comment by torkelo** [comment]
@evgenyf  I am not sure I understand, the dashboard identifier is part of the URL.

![image](https://cloud.githubusercontent.com/assets/10999/5901413/a707fa4e-a572-11e4-9bd4-c77177bb390d.png)
