### ISSUE TITLE
[Feat] Table Panel-Column Option to lookup additional data for any field

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#13890]
### What happened instead? Must add each field column (not feasible)

Feature:
To provide a convenient mechanism to allow a user to quickly examine the entire record of a row, without having to add each column individually (which could be many columns and cumbersome to do).  An added benefit of this implementation is that the same mechanism can be used to provide detailed data lookup based on any column as well.

Problem scenarios:
The use case we are utilizing is an analyst performing research against a large data-set, and needing to drill down into specific log events, but other use cases can be applied.  When viewing log data in Grafana, the Table Panel allows you to add fields to the table view as columns, thus building the table view.  When a user is viewing the data in a dashboard, they may decide it is necessary to to view additional fields from the log event.  The current process is cumbersome for a user,  especially when attempting to do quick research such as: when the specific field(s) to add is unknown (what other data is there?),  when multiple additional fields need to be viewed (perhaps dozens) and they don't realistically fit in the table view, or when it is necessary to view all fields (which could be 100 or more).

Problem example:
The user searches for matching events in an Elasticsearch index.  They now need to see additional data not in the dashboard default.  Even though they may not usually build dashboards, they must know how to manipulate the columns to add additional fields.  They will attempt to add all the fields to find the field(s)/value(s) they are needing.  Afterwards, they will clean up the view to continue searching.
![problem_example](https://user-images.githubusercontent.com/35579731/47668112-face0200-db7d-11e8-8f73-e8225b5d4192.gif)

Solution Proposal:
Add an option to the Table Panel for a Column Style that will allow "Enable value for lookup".  Using this value (or another from the row, via ${__cell}) and URL, additional data will be retrieved and shown in a hidden child row, that is displayed only when selected.

Solution example 1:
An Elasticsearch index is viewed in the Table Panel.  The dashboard creator customizes the _id column (which is the unique document ID for this document/ row), selecting "Enable value for lookup".  Any URL can be provided, here the data-source URL is provided with the cell value.  As the document ID itself does not need to be seen in this instance, the creator replaces it with the word "Details" to simplify the view for the user.  When a use clicks details, the full document is retrieved from the Elasticsearch index.  From this the user can view all the data available in this document.
![solution_example_1](https://user-images.githubusercontent.com/35579731/47668134-0ae5e180-db7e-11e8-9769-b7e51c8fdb87.gif)

Solution example 2:
An Elasticsearch index is viewed in the Table Panel.  The dashboard creator customizes the src_ip and cal columns.  The src_ip is passed to an internal API/service that responds with a reverse lookup result.  The calc column queries a public URL for additional data (just a sample in this case) and provides the results.  When a user clicks either field, the resulting details are made available.  These are provided as examples of the possibilities beyond just the raw document details made available in the initial example.
![solution_example_2](https://user-images.githubusercontent.com/35579731/47668169-1a652a80-db7e-11e8-83e8-fb12808e05d7.gif)

A WIP PR to follow to gain feedback.

**Comment by torkelo** [comment]
not sure we want to support making additional calls, but we do want to support showing full details if that is provided in the original query:
https://github.com/grafana/grafana/issues/10871

**Comment by davewat** [comment]
Thanks!  When we started, we just wanted to get the full Elasticsearch document, but then found it useful to do cross-reference lookups, for example, with an IP address field-do a reverse lookup, a username-query Active Directory for details, Threat_ID-lookup the threat details, etc.

Initially we used the 'link' option, to open in another tab the calls to our lookup services, but found integrating the lookup into the table view provided a more efficient view (a single pane of glass) and a better experience for our analysts.

Thought it was time to share the results.  Initial WIP-PR coming shortly.

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
