### ISSUE TITLE
can't change grafana admin e-mail to reset password

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [grafana/grafana#13893]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
 Grafana v5.3.2 (commit: 0d821d0) 
### What OS are you running grafana on?
centos6 - aws ami
### What did you do?
set admin e-mail in sqlite
sqlite3 /usr/share/grafana/data/grafana.db
 update user set email = 'xxxx@xxxxxx.foo.bar' where login = 'admin';
### What was the expected result?
receive a reset password email
### What happened instead?
t=2018-10-29T17:44:10-0300 lvl=dbug msg="Async sent email 1 succeed, sent emails: admin@localhost" logger=notifications

**Comment by torkelo** [comment]
The grafana db is in /var/lib/grafana try changing the email in that db

**Comment by conexaoinfraestrutura** [comment]
thx - all things run smoothly now 👍 
Soh this can be done too, to reset admin password.
sqlite3 /var/lib/grafana/grafana.db
update user set password = '59acf18b94d7eb0694c61e60ce44c110c7a683ac6a8f09580d626f90f4a242000746579358d77dd9e570e83fa24faa88a8a6', salt = 'F3FAxVm33R' where login = 'admin';

login as : admin / admin
