### ISSUE TITLE
Heatmap: Add support for Annotations

### ISSUE THREAD

**Issue by StephenOTT** [grafana/grafana#13895]
Is is possible to have the annotations overlay on Heatmap?

// Update: please add support for annotations in heatmap panel

**Comment by StephenOTT** [comment]
@peterholmberg at least add github login to the community.... having another one off login for just grafana is pretty bad community support 👎 👎

**Comment by torkelo** [comment]
we might add GitHub login to grafana.com in the future, your the first to complain about this, feedback is always appreciated.

**Comment by StephenOTT** [comment]
Given that this feature is not implemented, can we change this to a Feature request then?

**Comment by StephenOTT** [comment]
In the same way it would be great to be able to add a line graph overlay as well so things like "job executor" usage can be correlated with performance

**Comment by gelicia** [comment]
This work looks to be completed. Closing.
