### ISSUE TITLE
[Web.go:96 StartServer()] [E] Fail to start server: listen tcp: lookup '127.0.0.1': invalid domain name

### ISSUE THREAD

**Issue by karthikvee** [grafana/grafana#13898]
I couldn’t find any similar errors that end “invalid domain name”, On other servers with similar configuration grafana is running fine without errors, any help would be appreciated, thanks.

2018/10/29 11:35:14 [I] Database: mysql
2018/10/29 11:35:14 [I] Migrator: Starting DB migration
2018/10/29 11:35:14 [I] Login: Ldap enabled, reading config file: /etc/grafana/ldap.toml
2018/10/29 11:35:14 [I] Plugins: Scan starting
2018/10/29 11:35:14 [I] Listen: http://‘127.0.0.1’:8808
2018/10/29 11:35:14 [web.go:96 StartServer()] [E] Fail to start server: listen tcp: lookup ‘127.0.0.1’: invalid domain name
2018/10/29 11:49:42 [I] Starting Grafana
2018/10/29 11:49:42 [I] Version: 3.0.4, Commit: v3.0.4, Build date: 2016-05-25 08:46:55 +0000 UTC
2018/10/29 11:49:42 [I] Configuration Info
Config files:
[0]: /usr/share/grafana/conf/defaults.ini
[1]: /etc/grafana/grafana.ini
Command lines overrides:
[0]: default.paths.data=/var/lib/grafana
[1]: default.paths.logs=/var/log/grafana
[2]: default.paths.plugins=/var/lib/grafana/plugins
Paths:
home: /usr/share/grafana
data: /var/lib/grafana
logs: /var/log/grafana
plugins: /var/lib/grafana/plugins

@torkelo

**Comment by karthikvee** [comment]
This is what I've in "grafana.ini" file

[server]
http_addr = '127.0.0.1'
http_port = 8808
domain =

[database]
type = mysql
host = 172.16.72.15:3306
name = graph
user = graph
password = graph

[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml


[security]
admin_user = xxxxxxx
admin_password = yyyyyy

[analytics]
reporting_enabled=false

**Comment by torkelo** [comment]
strange, I cannot replicate this with the same settings. What OS are you trying to run grafana on?

**Comment by karthikvee** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by torkelo** [comment]
try removing the quotes around 127.0.0.1

**Comment by karthikvee** [comment]
hilarious, it's working now!

**Comment by karthikvee** [comment]
thanks for the inputs, torkelo.
