### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1389]
Hi Torkel,

Not sure is this currenly available or not. Is there any tabs on grafana? For example, If I am looking at bunch of servers and metrics. I want to be able to create tabs for each metric. Is this something you're looking at?

**Comment by torkelo** [comment]
Not sure what you mean, can you create a mock up or an image to explain what you are looking for?

**Comment by gsaray101** [comment]
![tabs_dashboard](https://cloud.githubusercontent.com/assets/3009225/5908263/f60c97ac-a573-11e4-8c7f-ed9ac90a219d.png)

On top of a current dashboard, there will also be tabs to group the metrics or anything together. If there are lots of servers with different apps, it will really be helpful  to have tabs. In this example, let's say I am on cpu tab, I will see cpu graphs. If I go to the memory tab, I will see the memory tabs etc. Any thoughts?

**Comment by gsaray101** [comment]
or tabs within the same graph panel.

**Comment by torkelo** [comment]
ok, now I understand, very similar to #322

**Comment by torkelo** [comment]
Sorry forgot to mention that this is not something that is high prio right now, but if #322 gets a lot of +1 votes it might be
