### ISSUE TITLE
Dashboard exporter doesn't add datasource template var dependency

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#13891]
When exporting a dashboard that uses a "data source" template variable, the data source type is not added to the `__requires` list in the exported JSON, which means that it doesn't get categorized correctly on grafana.com

**Comment by torkelo** [comment]
maybe we can fix this same time we fix this, https://github.com/grafana/grafana/issues/13781 which is unrelated but touching the exporter. Would like your feedback on that one actually. A lot of people having issues with the export format that is specific for sharing dashboards and not compatible with provisioning and direct dashboard save/update API usage so thinking of adding checkbox to export modal that will be called something like "For sharing on grafana.com" which will turn on the templatizing & adding of inputs & requires. This checkbox will be turned off by default.

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/pull/13990
