### ISSUE TITLE
v5 regression : dashboard creation time missing (reopened)

### ISSUE THREAD

**Issue by Daryes** [grafana/grafana#13896]
Hello again. Sorry but I'm insisting about this closed bug : #13858

Something important was missed, this setting set to 20 as defaut in grafana.ini :
````
[dashboards]
# Number dashboard versions to keep (per dashboard). Default: 20, Minimum: 1
;versions_to_keep = 20
````

As the creation metadata doesn't exist anymore, even in the JSON Model, the creation time and author are permanently lost as soon as the first version is automatically removed.
I've searched again in the dashboard information panel, but this data seems nowhere to be found.

This dashboard was created in 2017. 
![grafana-history](https://user-images.githubusercontent.com/14362813/47683492-0518ec00-dbd0-11e8-9b55-e3254c06cf08.jpg)

Obviously, after the v5.3.x migration, the older versions are removed.
No problem with that, there's no point to keep those old versions, but losing the creation metadata is another matter.

**Comment by torkelo** [comment]
Ah, sorry did not think about version clean up.

As I said in the other GitHub issue of yours GitHub allows for opening closed issues and we read comments on all issues so please post this the original issue and we will reopen it as we made a mistaking thinking this info was always there in the version list
