### ISSUE TITLE
No scrollbar in graph panel legend

### ISSUE THREAD

**Issue by diego-maravankin** [grafana/grafana#13894]
### What Grafana version are you using?
5.3.2
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Debian Linux 9, on Docker version 18.06.1-ce, official 5.3.2 image.
### What did you do?
Created a panel graph with many series.
### What was the expected result?
The legend of the graph has a scrollbar to see all the results.
### What happened instead?
No scrollbar available, so I can only see the first couple of metrics.

**Comment by torkelo** [comment]
Strange, what OS and browser are you using ?

**Comment by diego-maravankin** [comment]
@torkelo I tested in several OSs and browsers, with the same result:

- Firefox 62.0.3 (64-bit) and Google Chrome in Linux Mint.
- Google Chrome 69.0.3497.100 (64 bits) and 70.0.3538.77 (64 bits) in Windows 10.

I also tried downgrading to Grafana 5.1 and 5.2, with the same result. I did not downgrade further because I am using a panel which is compatible with Grafana > 5. 

Please let me know if you need more information or any further tests.

**Comment by torkelo** [comment]
strange, do you get a scrollbar on this graph:
https://play.grafana.org/d/Ru44Inamk/other-dash?orgId=1

You have to hover over legend and try to scroll with mouse wheel

**Comment by diego-maravankin** [comment]
I do get a scrollbar in that graph. I tried to replicate my configuration (legend formatted as table with min, max and avg values) but still get the scrollbar. I'll check to see if there is something in my installation which might be causing the issue and get back to you.

**Comment by diego-maravankin** [comment]
I'll close this issue, someone had edited /usr/share/grafana/public/build/app.770fad3a626c70250d5f.js  file in the installation which broke the scrolling ability en the graph, and I was unaware of that. 

I really appreciate your help with this issue and sorry for the inconvience.
