### ISSUE TITLE
use text label and grouped bar

### ISSUE THREAD

**Issue by Jarvis-JunZhu** [grafana/grafana#13897]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by torkelo** [comment]
You will have to write a proper feature request description, describe your use case and what problem your trying to solve and how grafana could be changed to address it. 

Closing this for now
