### ISSUE TITLE
Grafana Prometheus instantaneous query

### ISSUE THREAD

**Issue by MoSunDay** [grafana/grafana#13899]
Grafana Version:  `5.x`
OS: `Linux`

Did Grafana support Prometheus's instantaneous query? I learned from this link `https://github.com/grafana/grafana/pull/9186` that 4.6.0 was already supported, but I couldn't find the check box or drop-down box (qeury type) in the link image or the corresponding document. Did I miss something?

I tried to start grafana:4.6.0 with docker and did not find the check box in the link.

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/47712282-8fe10180-dc37-11e8-9d84-bcba33f626f4.png)

Not sure when it was added but think it was before v5

**Comment by MoSunDay** [comment]
@torkelo Thank you very much!
