### ISSUE TITLE
Icons get deleted when Grafana is using behind reverse proxy after some time.

### ISSUE THREAD

**Issue by deshmukh-abhay** [grafana/grafana#13909]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by torkelo** [comment]
We have never received a similar report so it's probably something related to your reverse proxy setup. 

Please provide much more information. What do you mean icons deleted? On disk? Not being requested by the UI or network errors? 

Please include full network request logs.

**Comment by deshmukh-abhay** [comment]
Grafana version:
Grafana v5.2.1 
What datasource are you using?
What OS are you running grafana on?
cent os.
What did you do?
set up Grafana behind reverse proxy.
What was the expected result?
All icons should be visible properly for proper functioning. 
What happened instead?
![image](https://user-images.githubusercontent.com/26044204/47773452-1ec14d00-dd10-11e8-9c48-c017be737707.png)

If related to metric query / data viz:

**Comment by deshmukh-abhay** [comment]
[grafana_har.zip](https://github.com/grafana/grafana/files/2533285/grafana_har.zip)

**Comment by deshmukh-abhay** [comment]
@torkelo Please look at image we are facing this issue from several days
![image](https://user-images.githubusercontent.com/26044204/47774474-246c6200-dd13-11e8-9147-12e22d927b40.png)

**Comment by radu-jakab** [comment]
@deshmukh-abhay did you figure this one out?
I am getting the same behavior. This happens to all SVG files, and SVG files only.

Going through the reverse proxy (does not work) I have 
HTTP 404 - https://app.xdelivery.ro/bi/public/img/icons_dark_theme/icon_alert.svg
Going directly to port (this works), I have 
HTTP 200 - http://app.xdelivery.ro:3000/bi/public/img/icons_dark_theme/icon_alert.svg
