### ISSUE TITLE
[Feature Request] Using mode() as a condition for Alerts

### ISSUE THREAD

**Issue by arriflex** [grafana/grafana#13906]
I am logging hardware devices which report their operating status as an integer. It would be nice to configure an Alert using mode() as a condition rather than the provided avg() or median() so that I can evaluate against an integer. Avg() and median() return floats that may be far away from the integer represented by the mode().

- Questions should be posted to https://community.grafana.com. https://community.grafana.com/t/using-mode-as-a-condition-for-alerts/11412

### What Grafana version are you using?
5.3.1
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Debian
### What did you do?
Tried using Avg() or Median() since Mode() is unavailable

**Comment by bergquist** [comment]
Would it make sense to use `current` instead? It only returns the last value in the serie. 

Considering no one else asked for this I'm not sure it's worth introducing.

**Comment by arriflex** [comment]
Unfortunately, current and/or last does not accomplish what I need. I would prefer the alert be triggered based on having a specific state (provided by an integer) for a substantial portion of a not necessarily contiguous period of time. 

An alternative method might be to count each integer and then alert based on the count I suppose. 

I recognize nobody else might have asked, just figured there was no harm in being the first!
