### ISSUE TITLE
Feature request: Add a support for Prometheus

### ISSUE THREAD

**Issue by bakirov** [grafana/grafana#1390]
Dear Sirs!

Can you, please, add a support for a [Prometheus](http://prometheus.github.io/) -- an open-source service monitoring system and time series database from SoundCloud, written in Go?

Thanks!

**Comment by bakirov** [comment]
[Description of a Prometheus Client Data Exposition Format.](https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit#)

**Comment by torkelo** [comment]
@bakirov no, but someone else can, then submit a PR to https://github.com/grafana/grafana-plugins  :)
