### ISSUE TITLE
User can delete view-only dashboard with JSON copy/paste workaround

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#13912]
### What Grafana version are you using?
5.3.2
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
* Copy the JSON from a dashboard in a folder in which the user only had view right.
* Create a new dashboard in folder in which the user has edit rights.
* Go to new dashoard settings > JSON
* Past de original dashboard JSON
* Save the dashboard
### What was the expected result?
* The new dashboard is a copy of the original dashboard
### What happened instead?
* Because the JSON contained the same dashboard ID, the original dashboard in de view only folder was removed (or simply moved to the new folder). This means that a user with view only rights can remove a dashboard from a folder.

**Comment by cinaglia** [comment]
@coussej I'm interested in tackling this issue but have been unable to replicate it on `v5.3.x`. Could you maybe provide a bit more details? 

- Were you using team based or individual permissions?
- Did the user have edit or admin rights on the target folder?
- Does the data source affect this in any way? (e.g. TestData DB)
- Were you doing a dashboard import or updating the JSON model in the dashboard settings page?

Feel free to add anything else you might think is relevant.

**Comment by marefr** [comment]
Tried to reproduce on current master (6c9b9b3), but I get `Access denied to save dashboard`. This seems to have been fixed. Will close this for now.

@coussej if you still can reproduce this on v6.02 I'll reopen this issue.
