### ISSUE TITLE
[Bug] Dashboard links don't update

### ISSUE THREAD

**Issue by PauloTemenos** [grafana/grafana#13917]
The Dashboard Links are not updating the "Time Range" or "Variable Values" values.

---

I have a few Dashboards which have "Dashboard Links" to other dashboards. Those links are set to include "Time range" and "Variable values".

When I open a dashboard page from, example:
`http://...?from=1540974412345&to=1540991747028&var-environment=qwerty&var-datacentre=London&var-layer=DB`
But then change the variables to, example:
`http://...?from=now-1h&to=nowvar-environment=XXX&var-datacentre=YYY&var-layer=ZZZ`
The URL of the dashboard I'm in (browser) changes,
**But** the variable payload on the Dashboard link still contains the initial set of values.

### What Grafana version are you using?
5.2.0-1 _(I had a look at change logs and didn't see any mention to this having been fixed)_

### What datasource are you using?
InfluxDB

### Browsers confirmed?
Chrome
Microsoft .. Edge or IE _(didn't quite pay attention to my colleague's browser)_
Opera

**Comment by torkelo** [comment]
Looks like this has been fixed,

Works as expected here:
https://play.grafana.org/d/rUpVRdamz/dashboard-links-with-variables?orgId=1
