### ISSUE TITLE
Scrolling disabled after dashboard import

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1391]
I observe the following:
* import dashboard from file ("Search" -> "Import" -> "Choose from file")
* wait for dashboard to load/render, so far so good
* attempt to scroll down, nothing happens.
* Click "Search" again to open that menu, then yet again to close it.
* scrolling now works.

It seems like Grafana is not correctly exiting the "Search" modal, where scrolling is disabled, after importing a dashboard.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
