### ISSUE TITLE
Icons are not visibe on grafana UI if you keep grafana UI idle for 20-25 minutes.[Reverseproxy setting]

### ISSUE THREAD

**Issue by deshmukh-abhay** [grafana/grafana#13916]
Grafana version:
Grafana v5.2.1
What datasource are you using?
What OS are you running grafana on?
cent os.
What did you do?
set up Grafana behind reverse proxy.
What was the expected result?
All icons should be visible properly for proper functioning.
What happened instead?
![image](https://user-images.githubusercontent.com/26044204/47796699-decb8b80-dd4a-11e8-9ec6-aeda2e5c13da.png)

Grafana.ini setting 
# Protocol (http, https, socket)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = 52.59.112.10

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = http://localhost:8000

# Log web requests
router_logging = true

# the path relative working path
static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path
;socket =

Network log : 
[grafana_har.zip](https://github.com/grafana/grafana/files/2534933/grafana_har.zip)

**Comment by torkelo** [comment]
Not sure what could be causing this, we have no other similar reports. Are others seeing this or is it just you ?

Maybe some browser extension? Closing this as I think you already opened an issue for this. Don’t think this is a grafana issue but something with your browser or. Check for network request failures or inspect the logo element in grafana that is now showing, inspect the browser console for errors, try replicate this in incognito mode

**Comment by deshmukh-abhay** [comment]
It is replicated in incognito mode also.
there is browser plugin that can causing this
Could you please tell me is my reverse proxy configuration is correct ?
