### ISSUE TITLE
Elasticsearch as metric in grafana

### ISSUE THREAD

**Issue by antidamage** [grafana/grafana#1392]
I'm scratching my head trying to get some apache logs into grafana. This is the approach I've tried:

Use logstash to copy log entries into elasticsearch and populate fields
Show annotations in grafana

Firstly, the docs for annotations are unclear in that they could use some good usage examples. My annotations are appearing but they're next to useless with the way I've set them up.

Secondly, what I'm having trouble doing is getting the log events from ES to show as a metric. I've googled around for a few days without much success. Any advice on what direction I should go in here?

**Comment by torkelo** [comment]
The Elasticsearch grafana datasource implementation only supports annotations (and dashboard storage), not metrics right now. If you want to query Elasticsearch and visualize logs Kibana is a great tool.  

Another option is to use logstash to parse logs and turn them into time series metrics and send them to InfluxDB or Graphite. 

I will close this as there already is a Issue to support metrics (graphs) for Elasticsearch queries. #1034
