### ISSUE TITLE
[Feature Request] Option to hide resizable-handle with Transparent graphs

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#13923]
Hi. 
It would be nice to be able to hide _resizable-handle_ with transparent graphs. 
![image](https://user-images.githubusercontent.com/1700286/47835885-24be3900-ddb7-11e8-8792-27d6ca8df50b.png)

It may appear after cursor hover, as a panel hover-hilight:
![2](https://user-images.githubusercontent.com/1700286/47835573-a7de8f80-ddb5-11e8-9d03-bedc6bf6d627.gif)

It's useful when user wants to make consistency and clean design.
Alternatively, It can be semitransparent (opacity: 0.3;) if hidden is inappropriate:
![image](https://user-images.githubusercontent.com/1700286/47835679-43700000-ddb6-11e8-9fb4-255f82deff7d.png)

![image](https://user-images.githubusercontent.com/1700286/47835846-00625c80-ddb7-11e8-83ac-0fb3f406c1ce.png)

**Comment by torkelo** [comment]
I do not like the adding a new option for this

**Comment by mammuthus** [comment]
Okay, just one more demonstration. This doesn't feel right.
![image](https://user-images.githubusercontent.com/1700286/47855470-c1073080-ddf5-11e8-9de3-3ab901b28282.png)

**Comment by torkelo** [comment]
Agree, i think the show on hover is a good idea
