### ISSUE TITLE
Can't install plugin from docker container

### ISSUE THREAD

**Issue by jeandet** [grafana/grafana#13920]
- Grafana Version: docker.io/grafana/grafana:latest (31/10/2018)
- Host os: Fedora 28
I did (removed some mail and certificate options): 
```
sudo docker run -it  -p 443:3000   --name=grafana   --user 1000   \
 -e "GF_SERVER_PROTOCOL=https" \
 -e "GF_SERVER_ROOT_URL=https://hephaistos.lpp.polytechnique.fr/grafana"  \
 -e "GF_AUTH_ANONYMOUS_ENABLED=true" \
 -e "GF_INSTALL_PLUGINS=natel-plotly-panel" \
 -v /opt/grafana:/var/lib/grafana   grafana/grafana bash
```
I get:
```
Failed to send requesterrorGet https://grafana.com/api/plugins/repo/natel-plotly-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/natel-plotly-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
```

I also tried few weeks ago and got the same result, I also tried to stop the host firewall but it didn't change anything.
I don't know what's wrong.

**Comment by davewat** [comment]
@jeandet Not a fix for your issue, but a workaround.  Mount the plugins folder to your local file system via docker volume and copy the plugin into the folder directly:
Create a docker volume:
`docker volume create --opt type=none --opt device=/path/on/local/system --opt o=bind grafana_plugins`

Add a line to your run command:
`-v grafana_plugins:/var/lib/grafana/plugins \`

Extract the plugin into the folder on your host system:
https://grafana.com/api/plugins/natel-plotly-panel/versions/0.0.4/download

And restart your docker.  You can load any other plugins this way as well.

**Comment by torkelo** [comment]
Maybe a network issue with doing outbound requests from within the container?

**Comment by jeandet** [comment]
@torkelo not sure, from running container I can do:

```
I have no name!@fc35eb322cc4:/usr/share/grafana$ curl https://grafana.com/api/plugins/natel-plotly-panel/versions/0.0.4/download
{
  "url": "https://codeload.github.com/NatelEnergy/grafana-plotly-panel/legacy.zip/df51dc99e63c781f2ddc9590b7f106e40648738d",
  "downloads": 779045
}I have no name!@fc35eb322cc4:/usr/share/grafana$ 
```

also with previously failing request:

```
I have no name!@fc35eb322cc4:/usr/share/grafana$ curl https://grafana.com/api/plugins/repo/natel-plotly-panel
{
  "id": "natel-plotly-panel",
  "type": "panel",
  "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
  "status": 1,
  "versions": [
    {
      "version": "0.0.4",
      "commit": "df51dc99e63c781f2ddc9590b7f106e40648738d",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.3",
      "commit": "371cbf41006a534a671a9582a3e24ce3cf29d9b1",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.2",
      "commit": "68947cf1d73b7bcceceebaf795c60a7b76eaec87",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.1",
      "commit": "187e7b5743f0dceb1034b03eaac62989af50d0c0",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    }
  ]
}I have no name!@fc35eb322cc4:/usr/share/grafana$ 
```

While on the same container/session I get:
```
I have no name!@fc35eb322cc4:/usr/share/grafana$ grafana-cli plugins list-remote
Failed to send requesterrorGet https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins list-remote - list remote available plugins

USAGE:
   Grafana cli plugins list-remote [arguments...]
I have no name!@fc35eb322cc4:/usr/share/grafana$ 
```

**Comment by xlson** [comment]
@jeandet It's hard to say exactly what the problem is and very strange that you are able to use `curl` but not our tooling. It does look like an issue with your network not allowing the outbound request or possibly not being able to access your dns server.

This is basically what you have done already, but you could you try running the commands like this to verify that there's nothing related to how you start the container that's causing problems in your case:

`docker run --rm --entrypoint bash grafana/grafana:5.3.2 -c "curl -vv https://grafana.com/api/plugins/repo/natel-plotly-panel"`

`docker run --rm --entrypoint bash grafana/grafana:5.3.2 -c "grafana-cli plugins list-remote"`

**Comment by jeandet** [comment]
@xlson, I agree, this is hard to debug, at first thought it was a network issue but since curl is working, I'm quite lost...

First one with curl works:
```
[adminlpp@mike ~]$  docker run --rm --entrypoint bash grafana/grafana:5.3.2 -c "curl -vv https://grafana.com/api/plugins/repo/natel-plotly-panel"
Unable to find image 'grafana/grafana:5.3.2' locally
Trying to pull repository docker.io/grafana/grafana ... 
sha256:214d44aa104b26c36b235da13c0b5ca9baa75057bcd14edcea58bbbe8b596792: Pulling from docker.io/grafana/grafana
Digest: sha256:214d44aa104b26c36b235da13c0b5ca9baa75057bcd14edcea58bbbe8b596792
Status: Image is up to date for docker.io/grafana/grafana:5.3.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 107.178.222.220...
* TCP_NODELAY set
* Connected to grafana.com (107.178.222.220) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [113 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4446 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=grafana.com
*  start date: Dec 14 00:00:00 2017 GMT
*  expire date: Mar 14 23:59:59 2019 GMT
*  subjectAltName: host "grafana.com" matched cert's "grafana.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
} [5 bytes data]
> GET /api/plugins/repo/natel-plotly-panel HTTP/1.1
> Host: grafana.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Tue, 06 Nov 2018 14:36:37 GMT
< Content-Type: application/json; charset=utf8
< Content-Length: 1200
< Connection: keep-alive
< X-UA-Compatible: IE=Edge,chrome=1
< 
{ [1200 bytes data]
* Curl_http_done: called premature == 0
100  1200  100  1200    0     0   2700      0 --:--:-- --:--:-- --:--:--  2702
* Connection #0 to host grafana.com left intact
{
  "id": "natel-plotly-panel",
  "type": "panel",
  "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
  "status": 1,
  "versions": [
    {
      "version": "0.0.5",
      "commit": "fd20e71fc45a59475fb2f1fdde687f93978bde18",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.4",
      "commit": "df51dc99e63c781f2ddc9590b7f106e40648738d",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.3",
      "commit": "371cbf41006a534a671a9582a3e24ce3cf29d9b1",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.2",
      "commit": "68947cf1d73b7bcceceebaf795c60a7b76eaec87",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    },
    {
      "version": "0.0.1",
      "commit": "187e7b5743f0dceb1034b03eaac62989af50d0c0",
      "url": "https://github.com/NatelEnergy/grafana-plotly-panel",
      "verified": false,
      "status": 1
    }
  ]
}
```

Second one with cli tool times out after few seconds, which network api does cli tool uses? libcurl?
```
[adminlpp@mike ~]$ docker run --rm --entrypoint bash grafana/grafana:5.3.2 -c "grafana-cli plugins list-remote"
Failed to send requesterrorGet https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins list-remote - list remote available plugins

USAGE:
   Grafana cli plugins list-remote [arguments...]
```

**Comment by bergquist** [comment]
it uses `net/http` from golangs SDK. 

https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-cli/services/services.go#L29

**Comment by tinproject** [comment]
I'm suffering the same issue trying to install plugins to a Grafana docker image using `GF_INSTALL_PLUGINS`

The repository where I have the issue is open on GitHub: https://github.com/tinproject/emojivending

You can reproduce it running `make setup-volumes` (creates volume folders), uncomment `GF_INSTALL_PLUGINS` on `infra/grafana/grafana.env` file so it will try to install the plugins.
And finally run `docker-compose up` or `make run` to start Grafana, along other things, and see the plugin install fail.

- Grafana docker image: `grafana/grafana:5.3.2` (also tried with 5.3.0)
- Docker version: `18.09.0`
- Host: Linux Mint 19

**Comment by tinproject** [comment]
For me the problem it's fixed using `grafana:5.4.0-beta1` container.

**Comment by jeandet** [comment]
@tinproject @bergquist this is weird, I tested today it worked on my desktop machine but not on my server.
So after MANY tests I found that forcing the use of my local DNS instead of google one did the trick, I don't know why and even less why curl is ok while golangs http api isn't.

**Comment by dynek** [comment]
The first one using Go's resolver fails but the second one using using cgo DNS resolver works.

**Comment by xlson** [comment]
@dynek Interesting, it seems you are running into an edge case where the pure Go dns resolver doesn't work properly. What os and arch are you on? And are you running selinux?

Not sure we'll be able to solve this but you could add `GODEBUG=netdns=cgo` as a workaround for now (omitting the `+1` removes the debug logging but still forces cgo resolution).

**Comment by jeandet** [comment]
Hi @xlson, 
Sorry for the delay, I tried:

With 8.8.8.8 in DNS list
```
docker run -ti --rm --entrypoint bash -e GODEBUG=netdns=go+1 grafana/grafana:5.4.0 -c "grafana-cli plugins list-remote"
```
gives:
```
go package net: GODEBUG setting forcing use of Go's resolver
Failed to send requesterrorGet https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins list-remote - list remote available plugins

USAGE:
   Grafana cli plugins list-remote [arguments...]
```
And
```
docker run -ti --rm --entrypoint bash -e GODEBUG=netdns=cgo+1 grafana/grafana:5.4.0 -c "grafana-cli plugins list-remote"
``` 
gives:
```
go package net: using cgo DNS resolver
id: abhisant-druid-datasource version: 0.0.5
id: akumuli-datasource version: 1.2.8
id: alexanderzobnin-zabbix-app version: 3.9.1
id: andig-darksky-datasource version: 1.0.0
id: ayoungprogrammer-finance-datasource version: 1.0.0
id: belugacdn-app version: 1.2.0
id: bessler-pictureit-panel version: 1.0.0
id: blackmirror1-singlestat-math-panel version: 1.1.5
id: blackmirror1-statusbygroup-panel version: 1.1.1
id: bosun-app version: 0.0.28
id: briangann-datatable-panel version: 0.0.6
id: briangann-gauge-panel version: 0.0.6
id: btplc-alarm-box-panel version: 1.0.7
id: btplc-peak-report-panel version: 0.2.3
id: btplc-status-dot-panel version: 0.2.3
id: btplc-trend-box-panel version: 0.1.9
id: camptocamp-prometheus-alertmanager-datasource version: 0.0.6
id: citilogics-geoloop-panel version: 1.1.1
id: cloudflare-app version: 0.1.3
id: crate-datasource version: 0.5.1
id: dalmatinerdb-datasource version: 1.0.5
id: ddurieux-glpi-app version: 1.3.0
id: devicehive-devicehive-datasource version: 2.0.1
id: digiapulssi-breadcrumb-panel version: 1.1.4
id: digiapulssi-organisations-panel version: 1.1.0
id: digrich-bubblechart-panel version: 1.1.0
id: fastweb-openfalcon-datasource version: 1.0.0
id: fatcloud-windrose-panel version: 0.7.0
id: fetzerch-sunandmoon-datasource version: 0.1.2
id: flant-statusmap-panel version: 0.0.3
id: foursquare-clouderamanager-datasource version: 0.9.2
id: fzakaria-simple-annotations-datasource version: 1.0.0
id: gnocchixyz-gnocchi-datasource version: 1.7.0
id: goshposh-metaqueries-datasource version: 0.0.1
id: grafana-azure-data-explorer-datasource version: 1.1.0
id: grafana-azure-monitor-datasource version: 0.3.0
id: grafana-clock-panel version: 1.0.2
id: grafana-example-app version: 1.0.1
id: grafana-influxdb-08-datasource version: 1.0.2
id: grafana-influxdb-flux-datasource version: 5.1.0
id: grafana-kairosdb-datasource version: 3.0.1
id: grafana-kubernetes-app version: 1.0.1
id: grafana-piechart-panel version: 1.3.3
id: grafana-polystat-panel version: 1.0.14
id: grafana-simple-json-datasource version: 1.4.0
id: grafana-worldmap-panel version: 0.1.2
id: gridprotectionalliance-openhistorian-datasource version: 1.0.2
id: gridprotectionalliance-osisoftpi-datasource version: 1.0.3
id: hawkular-datasource version: 1.1.1
id: ibm-apm-datasource version: 0.8.0
id: instana-datasource version: 2.0.0
id: jasonlashua-prtg-datasource version: 4.0.3
id: jdbranham-diagram-panel version: 1.4.4
id: kentik-app version: 1.3.2
id: larona-epict-panel version: 1.0.0
id: linksmart-hds-datasource version: 0.3.0
id: linksmart-sensorthings-datasource version: 1.1.0
id: marcuscalidus-svg-panel version: 0.2.0
id: michaeldmoore-annunciator-panel version: 1.0.0
id: monasca-datasource version: 1.0.0
id: monitoringartist-monitoringart-datasource version: 1.0.0
id: moogsoft-aiops-app version: 7.0.1
id: mtanda-google-calendar-datasource version: 1.0.4
id: mtanda-heatmap-epoch-panel version: 0.1.7
id: mtanda-histogram-panel version: 0.1.6
id: natel-discrete-panel version: 0.0.8-pre
id: natel-influx-admin-panel version: 0.0.5
id: natel-plotly-panel version: 0.0.5
id: natel-usgs-datasource version: 0.0.2
id: neocat-cal-heatmap-panel version: 0.0.3
id: novalabs-annotations-panel version: 0.0.1
id: ns1-app version: 0.0.7
id: ntop-ntopng-datasource version: 1.0.0
id: opennms-helm-app version: 2.0.0
id: ovh-warp10-datasource version: 2.1.1
id: percona-percona-app version: 1.0.0
id: petrslavotinek-carpetplot-panel version: 0.1.1
id: praj-ams-datasource version: 1.0.1
id: rackerlabs-blueflood-datasource version: 0.0.2
id: radensolutions-netxms-datasource version: 1.1.0
id: raintank-snap-app version: 0.0.5
id: raintank-worldping-app version: 1.2.4
id: ryantxu-ajax-panel version: 0.0.5
id: ryantxu-annolist-panel version: 0.0.1
id: satellogic-3d-globe-panel version: 0.1.0
id: savantly-heatmap-panel version: 0.2.0
id: sbueringer-consul-datasource version: 0.1.5
id: sidewinder-datasource version: 0.2.0
id: simpod-json-datasource version: 0.1.0
id: skydive-datasource version: 1.0.1
id: smartmakers-trafficlight-panel version: 1.0.0
id: sni-pnp-datasource version: 1.0.5
id: sni-thruk-datasource version: 1.0.0
id: snuids-radar-panel version: 1.4.1
id: snuids-trafficlights-panel version: 1.4.2
id: stagemonitor-elasticsearch-app version: 0.83.2
id: udoprog-heroic-datasource version: 0.1.0
id: vertamedia-clickhouse-datasource version: 1.8.0
id: vonage-status-panel version: 1.0.9
id: voxter-app version: 0.0.1
id: yesoreyeram-boomtable-panel version: 0.4.6
id: zuburqan-parity-report-panel version: 1.0.1

Restart grafana after installing plugins . <service grafana-server restart>
```

While both work with 8.8.8.8 removed from DNS list.

I hope this helps :).

**Comment by dynek** [comment]
> @dynek Interesting, it seems you are running into an edge case where the pure Go dns resolver doesn't work properly. What os and arch are you on? And are you running selinux?

The container is running on my NAS (QNAP) and doesn't have selinux.

> Not sure we'll be able to solve this but you could add `GODEBUG=netdns=cgo` as a workaround for now (omitting the `+1` removes the debug logging but still forces cgo resolution).

Will give it a try next time. In the meantime I removed the plugins cause I didn't use them anyway.

Thank you!

**Comment by marksugar** [comment]
hello @xlson 

grafana version：5.4.2

n the kubernetes, I also encountered the same problem.
```
nobody@grafana-6689854d5-9mhw4:/var/lib$ grafana-cli plugins update-all
Failed to send requesterrorGet https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins update-all - update all your installed plugins

USAGE:
   Grafana cli plugins update-all [arguments...]
```
I am running two containers on the same node.
The grafana container can't be parsed normally. I can only use the ip to access the Internet. My dns parsing may be problematic.

However, I can't install effective tools like ‘nslooup’, I can't see more information.

Will these network tools be added in the next release?

**Comment by dynek** [comment]
@marksugar have you tried adding `GODEBUG=netdns=cgo` as environment variable?
Not a fix per-se but should workaround the issue.

**Comment by snydergd** [comment]
I wanted to throw in there for those it may be helpful for, that if using straight docker without k8s at all, this solution solved my problem and might be useful to you if it's due to dnsmasq on Ubuntu.

https://askubuntu.com/questions/475764/docker-io-dns-doesnt-work-its-trying-to-use-8-8-8-8

**Comment by mrvladis** [comment]
Hi All,

So, how do we fix this issue?

I've tried to run latest grafana (including Ubuntu image) on docker (compose) , but can't get any plugins installed.

All fail with the certificate error.

I don't have any proxies at home but direct Internet Connection,

Thanks.

**Comment by mrvladis** [comment]
UpD:

**From latest grafana Ubuntu Container:**
bash-4.4# curl -vvI  https://grafana.com/api/plugins/repo/grafana-clock-panel
*   Trying 35.241.23.245...
* TCP_NODELAY set
* Connected to grafana.com (35.241.23.245) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate in certificate chain
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Alpine container doesn't have curl, but wget giving the same issue:**
bash-5.0# wget https://grafana.com/api/plugins/repo/grafana-clock-panel
Connecting to grafana.com (35.241.23.245:443)
ssl_client: grafana.com: TLS connect failed
wget: error getting response: Connection reset by peer

**Comment by xlson** [comment]
@mrvladis It looks like you have something (probably a firewall) that puts in an unsigned certificate somewhere in the chain. This won't be accepted by Grafana/curl/wget as this is not the correct certificate. Are you running this on a company network that might do this?

Using the `-k` flag on curl will accept the self-signed cert and can be used to verify that this is the only problem. That said, you should try to look into what is inserting the self signed certificate.

**Comment by mrvladis** [comment]
@xlson This is definitely not the case.
I am running it at home, where I don't have any proxies. It is only an issue with this container.

**Comment by lrosser2103** [comment]
I have the same issue, and think it may be Pi-hole muddying the waters.  Going to try removing the Pi-hole container in my docker and see if that provides any insight

**Comment by mrvladis** [comment]
@xlson 
Sorry for a  bit a delay. I have tried "-k" as per your suggestion.

Please see below. As it looks for me - certificate is yours,  but your container doesn't trust it.


`bash-4.4# curl -vvI -k https://grafana.com/api/plugins/repo/grafana-clock-panel
*   Trying 35.241.23.245...
* TCP_NODELAY set
* Connected to grafana.com (35.241.23.245) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=grafana.com
*  start date: Feb  6 00:00:00 2019 GMT
*  expire date: May  6 23:59:59 2020 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5654cdf6dcc0)
> HEAD /api/plugins/repo/grafana-clock-panel HTTP/2
> Host: grafana.com
> User-Agent: curl/7.61.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 405
HTTP/2 405
< server: nginx/1.13.9
server: nginx/1.13.9
< date: Fri, 17 Jan 2020 19:06:52 GMT
date: Fri, 17 Jan 2020 19:06:52 GMT
< allow: GET
allow: GET
< via: 1.1 google
via: 1.1 google
< alt-svc: clear
alt-svc: clear

<
* Connection #0 to host grafana.com left intact`

**Comment by mrvladis** [comment]
p.s. This is on grafana/grafana:6.5.3-ubuntu

**Comment by T0T4R4** [comment]
Got this with bitnami/grafana:latest as well...
So anyone sorted this out since last post ?

**Comment by mrvladis** [comment]
> Got this with bitnami/grafana:latest as well...
> So anyone sorted this out since last post ?

I gave up. Just installed plugin manually.

**Comment by germebl** [comment]
Still up to date in 2025 - do we get GTA6 before fixing this? (just joking)
