### ISSUE TITLE
Export to CSV removes digits of precision

### ISSUE THREAD

**Issue by MzazM** [grafana/grafana#13929]
### What Grafana version are you using?
Grafana v5.3.2 (commit: 0d821d0)
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu 18.04 LTS
### What did you do?
Values are correctly displayed in my panels. When exporting them to CSV I lose resolution. 
I save them with 6 digits resolution and the CSV file has 2 to 3 digits.

I believe in 4.x I did not have this issue but I can't be sure.

I tried with Firefox and Chrome.
I tried with and w/o aggregation functions.
I tried to increase digits in legend tab and axes tab.
The resolution of the CSV output is not affected.

### What was the expected result?
In the CSV file I expected to see the same number of significant digits that I see in the query inspector.
![image](https://user-images.githubusercontent.com/35630931/47844530-f5adc480-ddc2-11e8-822a-22e07959f5ee.png)

### What happened instead?
Values are rounded. Not all the digits are reported.
![image](https://user-images.githubusercontent.com/35630931/47844651-3279bb80-ddc3-11e8-9d26-7234b610d94b.png)

**Comment by vinicyusmacedo** [comment]
Would that work for this case? You wouldn't have a maximum value of significant digits this way. 
![image](https://user-images.githubusercontent.com/7549205/48656163-603c4280-ea08-11e8-938c-f12a903125a3.png)
