### ISSUE TITLE
Can't un-hide legend without sending it to right side first

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1393]
* Uncheck "Legend -> Show" in the "Axes & Grid" tab,
* return to dashboard,
* re-open "Axes & Grid" tab.

Toggling "Legend -> Show" on or off changes the size of the graph, but doesn't show the legend. The following sequence causes it to be shown again:

* "Legend -> Show"
* Check "Legend -> Right side"; legend appears on the right side
* Uncheck "Legend -> Right side"; legend appears correctly below the graph.

Here is a screencast demonstrating this issue: http://cl.ly/0N1N0M3W281m

**Comment by torkelo** [comment]
Thanks for reporting this, fixed in master!
