### ISSUE TITLE
In Alert no access to query

### ISSUE THREAD

**Issue by bizlevel** [grafana/grafana#13934]
I have 50 query in the graph.
And i want to add alert for all it query. And of course 50 query, and no template, because Alert no works with templates.
And main question how to add alert to last query?
Or how make Alert for all query? can i use * and min function?

P.S. All query must enumerated!
Not only to last "Z" letter! It must be like in excel, a-z, aa-az, and etc..

![q](https://user-images.githubusercontent.com/12154217/47854907-b6e03480-ddeb-11e8-8eb7-d1332f19f93e.PNG)
![select](https://user-images.githubusercontent.com/12154217/47854912-b9db2500-ddeb-11e8-8313-43aebe943062.png)

**Comment by torkelo** [comment]
Currently a limit of 26 queries per panel

Feature request for more : 
https://github.com/grafana/grafana/issues/4978
