### ISSUE TITLE
Elasticsearch Resources

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#1394]
Hi all,

I'm using graphite as data source and Elasticsearch as storage. The whole system is installed on a rather weak NAS and basically is managing just some consumption metrics of my home (water, gas electricity etc). Overall I have 3 dashboards defined, an overview being my home dash.

The ES instance is consuming a lot of memory, driving this system into swapping. I have only the default ES configuration with CORS activated. Is there anything to cut down the resources of ES or a more lightweight alternative that offers managing of some dashboards without having to load from file or specifying the dashboard in the URL?

Kind regards

**Comment by torkelo** [comment]
Not currently, you could try running InfluxDB just as dashboard storage, it might be a little more light weight than elasticsearch. For elasticsearch there is also options to turn down is memory usage, http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/heap-sizing.html

This should however be solved with the forth coming Grafana 2.0 backend, it will support an sqlite3 (embedded, no database server dependency) database that will be significantly more light weight than ES.
