### ISSUE TITLE
Grafana backend doesn't remove Referer header from request

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#13949]
When datasource is configured with _Server_ Access mode, grafana backend includes `Referer` header which was originally set by browser into request. 
Sometimes it causes some kind of unexpected behaviour, like an [issue with Splunk 7.2](https://github.com/grafana/splunk-datasource/issues/27). In that case, Splunk server returns `401 Unauthorized` if Referer set to URL different from splunk server URL, but if there's no Referer set, it works. Seems, splunk uses `Referer` as a kind of restricting cross-site request forgery. This is legal usage of `Referer`, but server should not rely on this, because this header may be absent in request.

So, it's may be helpful in some cases to remove `Referer` on the backend. I'm not sure, should it be a default behaviour, or an option in datasource config, because [RFC](https://tools.ietf.org/html/rfc7231#section-5.5.2) says

> Some intermediaries have been known to indiscriminately remove
   Referer header fields from outgoing requests.  This has the
   unfortunate side effect of interfering with protection against CSRF
   attacks, which can be far more harmful to their users.
   Intermediaries and user agent extensions that wish to limit
   information disclosure in Referer ought to restrict their changes to
   specific edits, such as replacing internal domain names with
   pseudonyms or truncating the query and/or path components.

, but I'm not sure Grafana is an _Intermediary_ in this case (I think no, because grafana not just a proxy for queries, it may invoke requests by itself, like for alerting).

Let's discuss what's a proper solution accordingly with RFC docs.
https://tools.ietf.org/html/rfc7231#section-5.5.2

**Comment by alexanderzobnin** [comment]
By the way, there're options to disable referer in some browsers:
- Chrome: run with `--no-referrers`
- Firefox: `network.http.sendRefererHeader` and `network.http.sendSecureXSiteReferrer` configs

**Comment by roidelapluie** [comment]
working on this

**Comment by Fantaztig** [comment]
This change completely broke our application as we rely on a query parameter in the referer to identify users and filter their queries based on roles.
What is the preferred way now to handle such requirements?

**Comment by marefr** [comment]
@Fantaztig maybe https://grafana.com/docs/installation/configuration/#send-user-header solves your problem?

**Comment by Fantaztig** [comment]
@marefr As our users are not authenticated with grafana this is not an option
However we managed to use a cookie instead. I'm not really sure why it was not implemented that way in the first place but it works fine!

**Comment by JimHagan** [comment]
We use this feature to identify dashboards associated with queries sent to backends like Elastic or InfluxDB (extracted via Packetbeat).  This is a powerful feature for us to map query duration (i.e., slow or expensive queries) or volume of returned data with dashboard names.  That allows us to quickly block "bad dashboards" from our ver large shared infrastructure (Wayfair)

**Comment by disfluxly** [comment]
@JimHagan - If you found an alternative, could you post it https://github.com/grafana/grafana/issues/22550 ?
