### ISSUE TITLE
[PLUGIN APP] Opennms new version 3 available but not on grafana site

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#13943]
The opennms app plugin is at v2 on the grafana site.
https://grafana.com/plugins/opennms-helm-app

but its on version 3 on their procjet page - any possibility to get v3 to be added thus installable via grafana-cli? 
https://github.com/OpenNMS/opennms-helm

**Comment by marefr** [comment]
This is not the right place to ask about a 3rd party plugin. Please open issue in https://github.com/OpenNMS/opennms-helm. What I can see they haven't tagged 3.0.0 yet so it's not ready as I see it. 

They'll probably submit a PR to our plugin repository as soon as 3.0.0 is ready. You can see existing PR's [here](https://github.com/grafana/grafana-plugin-repository/pulls?q=is%3Apr+opennms+is%3Aclosed).
