### ISSUE TITLE
Email Alerting from Grafana is not working inside the docker container

### ISSUE THREAD

**Issue by RamjiVE** [grafana/grafana#13944]
I have prometheus and Grafana in a docker-compose file.
I can visualize all the docker container metrics and host metrics in grafana.
But Email alerting is not working. I have configured the smtp configuration in defaults.ini in the Grafana.

Below is the error i'm getting when I used test alert to alert the error to my corporate mail id. SMTP server is a internal server so it can send emails internally inside the corporate.

> 2018-11-02T09:08:11+0000 lvl=eror msg="failed to send notification"
> logger=alerting.notifier id=1 error="gomail: could not send email 1:
> read tcp 172.20.0.8:42386->10.5.10.160:25: i/o timeout"

Could you tell me why my grafana container cannot send emails. I also tried prometheus alertmanager to send the mails. its not working too.

**Comment by RamjiVE** [comment]
I have prometheus and Grafana in a docker-compose file.
I can visualize all the docker container metrics and host metrics in grafana.
But Email alerting is not working. I have configured the smtp configuration in defaults.ini in the Grafana.

Below is the error i'm getting when I used test alert to alert the error to my corporate mail id. SMTP server is a internal server so it can send emails internally inside the corporate.

> 2018-11-02T09:08:11+0000 lvl=eror msg="failed to send notification"
> logger=alerting.notifier id=1 error="gomail: could not send email 1:
> read tcp 172.20.0.8:42386->10.5.10.160:25: i/o timeout"

Could you tell me why my grafana container cannot send emails. I also tried prometheus alertmanager to send the mails. its not working too.

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

GitHub is not the place for docker & smtp networking questions
