### ISSUE TITLE
Docs feedback: features/panels/table_panel.md

### ISSUE THREAD

**Issue by chrisriley** [grafana/grafana#13941]
Hello,

There appears to be some misleading information in the section titled "Merge Multiple Queries per Table". In this section it states that

> The following two results cannot be matched and will be rendered on separate rows:
```
Different time
Datapoint for query A: {time: 1, host: "node-2", job: "job-8", value: 3}
Datapoint for query B: {time: 2, host: "node-2", value: 4}

Different label "host"
Datapoint for query A: {time: 1, host: "node-2", job: "job-8", value: 3}
Datapoint for query B: {time: 1, host: "node-9", value: 4}
```
Immediately following these examples the document states:
> You can still merge both of the above cases by changing the conflicting column’s **Type** to **hidden** in the **Column Styles**.

However, this statement regarding the merging of results does not seem to be strictly true.

With respect to the first example ("Different time"), at least with v5.3.2, marking the time column's Type to hidden has no effect and the results are not merged. This appears to be true with InfluxDB 1.6.4 as the data source. If it is not possible to merge results when the time field does not match (regardless of being hidden or not), it would be nice to have a different example in place of the "Different time" example. And if this is simply an issue with InfluxDB as the data source, it would be nice if it was noted that the merge feature is not supported with InfluxDB.

Regards,
Chris

**Comment by oddlittlebird** [comment]
Content for table has been completely rewritten for 7.0.
