### ISSUE TITLE
Hard-coded limit of starred dashboards in Dashboard Dropdown

### ISSUE THREAD

**Issue by volter** [grafana/grafana#13950]
I'm on 5.3.2, but I looked this up in a current Git checkout:

`public/app/core/services/search_srv.ts` is defining a hard-coded limit of 5 "starred" results in `getStarred()`. No matter how many dashboards you "star", the Dashboard Dropdown will only show 5. The existence of a limit is not obvious to users, nor did I spot it in the documentation. Maybe this could be a per-user option and/or a global setting.

**Comment by torkelo** [comment]
Agree, maybe we should just remove this limit.

**Comment by NadMag** [comment]
Should this limit be removed for all dashboard queries such as getRecentDashboards?

**Comment by NadMag** [comment]
In addition should this limit be removed in other places such as in dashlist?
<img width="470" alt="dashlistlimit" src="https://user-images.githubusercontent.com/25124870/48368867-8cc92500-e6bd-11e8-81e5-7ae43154eee2.png">
