### ISSUE TITLE
New formatting style (separator)

### ISSUE THREAD

**Issue by chandij** [grafana/grafana#1395]
Big values on graphs (and single panels) might be hard to read: 
- 1422363539
- 12889809888 
- ...

... even when applying "short" representation: 
- 233312312 M
- 323233323 K
- ... 

What about adding **new format** with delimiter which can be one of few characters.

Separator: ","
- 1,422,363,539
- 12,889,809,888 

Separator: "  " (2 spaces)
- 1  422  363  539
- 12  889  809  888
  
  As mentioned before this can be applicable for all axis and for single stats panels.

**Comment by torkelo** [comment]
Should be pretty simple to add, PR please :)

**Comment by KiNgMaR** [comment]
+1

**Comment by jazzzz** [comment]
[`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) could do the job.

**Comment by m0nhawk** [comment]
I have made a PR, this can be closed now.

**Comment by tral** [comment]
great! "Unit" -> "none" -> "locale format" works!

**Comment by ameysd19** [comment]
> great! "Unit" -> "none" -> "locale format" works!

Hi,
I wanted comma separator in Indian format (Crores). Right now its in millions. Can you help me to solve this.
