### ISSUE TITLE
 Graphs are displayed incorrectly after changing the time zone of the system

### ISSUE THREAD

**Issue by preussal** [grafana/grafana#13957]
### What Grafana version are you using?
grafana:armhf 5.2.4
### What datasource are you using?
influxdb:armhf/stretch 1.6.4-1
### What OS are you running grafana on?
Raspian
### What did you do?
I installed the system in Germany, and then sent it to Bangkock.
after it was connected, I changed the time zone using "dpkg-reconfigure tzdata"

Current default time zone: 'Asia/Bangkok'
Local time is now:      Sun Nov  4 14:53:47 +07 2018.
Universal Time is now:  Sun Nov  4 07:53:47 UTC 2018.

The dashbords in Grafana were already created in Germany.
If I now access it via browser, the time zone will be taken from the browser.

German Firefox on PC in Germany
![german](https://user-images.githubusercontent.com/26431172/47961691-1dde3300-e010-11e8-8ab2-b2976f1e22e3.JPG)

Thai Firefox on PC in Bangkock
![thai](https://user-images.githubusercontent.com/26431172/47962037-c4c5cd80-e016-11e8-946c-ef2d7b3fb2b6.JPG)
but the day should start at 00:00, and not at 6 o'clock

And if I change the locale timezone of Germany on Thailand on my PC in Germany then I get that.
![change_timezone](https://user-images.githubusercontent.com/26431172/47961804-10c24380-e012-11e8-8251-26be4c8bd708.JPG)

The problem now is that the graphs are still starting at 00:00 German time. 
It does not matter which time zone I set locally and restart the browser.

Only in the display I get then either 
00:00 to 9: xx clock
or 
6:00 to 15: xx clock

But I need local time Bangkock 00:00 to 15: xx

The only way to properly represent the graphs.
Set the local time -6 hours
![manual time_1](https://user-images.githubusercontent.com/26431172/47961902-ce9a0180-e013-11e8-9cb3-6951f5557f1e.JPG)
but the funny thing is the display after the Apply
![manual time_2](https://user-images.githubusercontent.com/26431172/47961906-ebced000-e013-11e8-924c-e58369878d68.JPG)
all graphs will be displayed correctly.

but if you then change the time from 
2018-11-04 00:00:00 to 
2018-11-04 00:01:00. 
it will be 
2018-11-04 06:01:00
and everything is wrong again

if i only change the day then it works.

Influxdb always saves the data in UTC, so the problem would have to be in Grafana?

**Comment by xlson** [comment]
It sounds like you are running both InfluxDB and Grafana on the same server (the Raspbery PI), this is fine, but might be problematic if the timezone is something other than UTC on the server. As far as I'm aware InfluxDB expects to run on a server where the timezone is set to UTC. By this not being the case any kind of timezone conversion going on will end up being wrong.
