### ISSUE TITLE
grafana change my timestamp unreasonably from ES datasource

### ISSUE THREAD

**Issue by hectorhua** [grafana/grafana#13963]
Here is my ES data timestamp:
![image](https://user-images.githubusercontent.com/3795870/47990378-59692200-e122-11e8-9c5d-453402991029.png)

while grafana table display:
![image](https://user-images.githubusercontent.com/3795870/47990453-89182a00-e122-11e8-9723-190d04673ff5.png)

no matter I set default or local browser or UTC:
![image](https://user-images.githubusercontent.com/3795870/47990528-ac42d980-e122-11e8-9f88-7ce764a42ebf.png)

**Comment by hectorhua** [comment]
cannot grafana read timezone +8000 from ES data?

**Comment by xlson** [comment]
Could you open the query inspector in Grafana and take a screencap of the query and one of the hits? When doing a raw query for logs to ElasticSearch Grafana generally adds `"format":"epoch_millis"` to the `@timestamp` field so that we get utc time back, not sure what is happening here.

**Comment by hectorhua** [comment]
> Could you open the query inspector in Grafana and take a screencap of the query and one of the hits? When doing a raw query for logs to ElasticSearch Grafana generally adds `"format":"epoch_millis"` to the `@timestamp` field so that we get utc time back, not sure what is happening here.

in query inspector response data, the timestamp in _source is original ES timestamp, but the timestamp in fields is generated by grafana, and lost timezone +8000. So how can make timestamp in fields keep same with timestamp in _source?

![image](https://user-images.githubusercontent.com/3795870/48109308-dfe84580-e281-11e8-880f-6f8a358e66c1.png)

**Comment by torkelo** [comment]
The first is not generated by grafana , but is what ES is returning and have stored / indexed.

You should be able to fix this if you update the table panel column style rule for the time field to match the name of your ES field

**Comment by hectorhua** [comment]
> column style

yeah, work out~

![image](https://user-images.githubusercontent.com/3795870/48118793-5009c200-e2a8-11e8-967f-3d2d39353a1f.png)


@torkelo   thanks
