### ISSUE TITLE
API versions

### ISSUE THREAD

**Issue by pizzalord22** [grafana/grafana#13976]
Reading trough the release notes i noticed how the api changed over time and sometimes api breaking changes are made, Since  grafana does not have api versions at the moment (as far as i know). 

I was wondering if we could get api versions so that grafana can be updated when there is a new release without breaking current api code. This would give me and others the time to change oru code to work with new api versions while still using the latest grafana release

**Comment by torkelo** [comment]
We try to almost never do breaking api changes. So far we have not done any major breaking change. But if we do we will do some kind of versioning.

**Comment by pizzalord22** [comment]
why wait? adding /v1/ in the url would solve the problem and make the api versioning compatible even if no api versions are needed yet.
