### ISSUE TITLE
Refresh Panels on key press while typing in Text Box

### ISSUE THREAD

**Issue by slangloisde** [grafana/grafana#13972]
Similar to DataTables filtering, it would be useful to have an option to make a Text Box refresh a panel (i'm thinking Table panel) or the dashboard on "key press", so that, for filtering cases, the user can see the dashboard update while they type.   

Obviously has to be used with care, but for tables, i think it would be great.

Or maybe alternatively, have the text box added to the Table panel, to be able to filter the table data directly in the panel.  

Using Grafana 5.3.2.

**Comment by daniellee** [comment]
The new filter mode for the new table panel mostly fills this request: https://grafana.com/docs/grafana/latest/panels/visualizations/table/filter-table-columns/#filter-table-columns
