### ISSUE TITLE
Flot display problem

### ISSUE THREAD

**Issue by runningman84** [grafana/grafana#1397]
The flot (client side) output doesn't work with multiple sources. In this example I have data like

sensu.sensu.i-XXXXXXX.rabbitmq.message_stats.publish.rate
sensu.sensu.i-YYYYYY.rabbitmq.message_stats.publish.rate

So I filter like this

sensu.sensu.*.rabbitmq.message_stats.publish.rate

These hosts weren't online at the same time. The png output looks fine:

![grafana_png](https://cloud.githubusercontent.com/assets/1699128/5920689/bb6a7b0c-a63e-11e4-911b-236c0aaeebeb.PNG)

The flot output is empty:

![grafana_flot](https://cloud.githubusercontent.com/assets/1699128/5920688/ba068f62-a63e-11e4-9a26-682ba7873cdf.PNG)

If I select a single source it works in flot too:

![grafana_flot_single](https://cloud.githubusercontent.com/assets/1699128/5920710/e038ac1a-a63e-11e4-9630-12ae9a80ccb3.PNG)

**Comment by torkelo** [comment]
if you have stack enabled and your series can contain null values,  you must select null point mode to ``null as zero``, stack mode requires data for every point.
