### ISSUE TITLE
heatmap shows too small buckets

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#13978]
Please include this information:
### What Grafana version are you using?
5.3.2
### What datasource are you using?
prometheus
### What OS are you running grafana on?
no matter
### What did you do?
show heatmap by latency distribution
### What was the expected result?
visible buckets
### What happened instead?
![image](https://user-images.githubusercontent.com/289277/48062252-8e34b200-e1d2-11e8-9455-64b6bbb70d7b.png)

### If related to metric query / data viz:
```
histogram_quantile($percentile, sum(
rate(
nginx_vts_upstream_request_duration_seconds_bucket{upstream=~"$upstream", backend=~"$backend",tier="prod"}[1m]
)) by (le))
```
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
![image](https://user-images.githubusercontent.com/289277/48062276-a1e01880-e1d2-11e8-936d-df54dc7b0685.png)

 More details have @alexanderzobnin

**Comment by alexanderzobnin** [comment]
I tried to replicate this and found, that panel shows wrong bucket size if step between buckets has too high precision. For example, if series contains values `1` and `1.000000000000001`, then step will be `0.000000000000001`. If step is greater, than heatmap displays buckets with proper size, but if it's less, it works as if all values are the same. I think it's related to `float` type precision in JS.

**Comment by ryantxu** [comment]
We are working on https://github.com/grafana/grafana/issues/45495 now -- we don't have plans to fix things in version 5
