### ISSUE TITLE
Passing GF_AUTH_PROXY_HEADERS as an environment variable doesn't work

### ISSUE THREAD

**Issue by thequailman** [grafana/grafana#13989]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
grafana/grafana:5.3.2
### What datasource are you using?
N/A
### What OS are you running grafana on?
Docker image, grafana/grafana:5.3.2
### What did you do?
Passed permutations of this configuration:

```
GF_AUTH_PROXY_HEADERS='Email:x-oidc-email'
GF_AUTH_PROXY_HEADERS='{"Email":"x-oidc-email"}'
```

### What was the expected result?
Grafana would log that the config variable has been overridden, user email addresses would appear
### What happened instead?
Nothing is logged, email addresses are not being passed from auth proxy

**Comment by DanCech** [comment]
Try removing the space after `:`, then it should work.

**Comment by DanCech** [comment]
The code that handles parsing the string into `map[string][string] is here:
https://github.com/grafana/grafana/blob/4f601761dfb85499c3b566fd39143662eb25d206/pkg/setting/setting.go#L645-L651

It operates the same way whether the setting is specified in the ini file or provided via env. Locally I added this after that block:
```
	logger.Info("Auth Proxy Headers", "var", AuthProxyHeaders)
```
And confirmed that running:
```
GF_AUTH_PROXY_HEADERS=Email:test,Name:blah bin/linux-amd64/grafana-server
```
Produces the following log line:
```
INFO[11-07|14:46:33] Auth Proxy Headers                       logger=settings var="map[Email:test Name:blah]"
```

**Comment by thequailman** [comment]
I can't seem to get this to work at all using Docker (grafana/grafana:5.3.2):

`GF_AUTH_PROXY_HEADERS=Email:x-oidc-email,Name:x-oidc-username`

**Comment by thequailman** [comment]
Even running it from within the docker image:
```
GF_AUTH_PROXY_HEADERS=Email:x-oidc-email,Name:x-oidc-username grafana-server
INFO[11-07|20:21:19] Starting Grafana                         logger=server version=5.3.2 commit=0d821d0 compiled=2018-10-24T12:06:27+0000
INFO[11-07|20:21:19] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_USERS_ALLOW_SIGN_UP=false"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_USERS_AUTO_ASSIGN_ORG=true"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin"
INFO[11-07|20:21:19] Config overridden from Environment variable logger=settings var="GF_AUTH_PROXY_ENABLED=true"
INFO[11-07|20:21:19] Path Home                                logger=settings path=/usr/share/grafana```

**Comment by thequailman** [comment]
Nice find!  Thank you for looking at this.  In the meantime I'll see if I can populate that value.
