### ISSUE TITLE
Explore: design needed for StartPages

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13985]
Datasources can bring their own set of tabbed static pages to Explore (for how-tos, tutorials, references). 

Currently it's using grafana styles that are used in the admin sections. It's not looking ideal and we're hoping to improve this.

**Comment by Ijin08** [comment]
Depending on where we land with the panel editor design we might be able to get inspiration from there.

But for now here is what I have come up with so far: 
![explorelanding](https://user-images.githubusercontent.com/23470681/48501069-92994480-e83c-11e8-9d77-4e380b777ae1.png)

I will spend some more time on it tomorrow to see what else I can come up with.

**Comment by Ijin08** [comment]
Here is a version keeping the old tabs. (also tweaked query input):
![explorelanding2](https://user-images.githubusercontent.com/23470681/48547954-0afb1680-e8cc-11e8-8b93-7fe4c24030c9.png)

**Comment by bulletfactory** [comment]
My preference so far is the tab version - maybe because it's familiar.
Would love to see some more options and incorporate elements from the panel
editor designs

**Comment by Ijin08** [comment]
Here is a version inspired by the panel edit:

<img width="1440" alt="screenshot 2018-11-28 at 13 34 26" src="https://user-images.githubusercontent.com/23470681/49152268-91731780-f312-11e8-8c64-bd232a6dbf5a.png">

**Comment by torkelo** [comment]
Do we need tabs for this view? What tabs to we envision data sources will need. Maybe we should keep it simple for now and just have one info box, like:

![image](https://user-images.githubusercontent.com/10999/49378744-a7674a80-f70d-11e8-8d8d-44efd78e8406.png)

We can add tabs later when we have a clear need for it.
