### ISSUE TITLE
[Feature request] Define user name of invited user

### ISSUE THREAD

**Issue by volter** [grafana/grafana#13981]
Using 5.3.2

Invited users can choose their own user name. This does not go well with using auth.proxy, where the name is not just random. I can only define a user name or an e-mail address on the invitation form. However, no message can be sent when using a user name, as their e-mail address is of course unknown.

I understand the rationale of not allowing users to change their names once logged in (using auth.proxy), but forbidding that in his profile, while allowing to choose any name when following their invitation feels confusing.

I think the right solution when using auth.proxy might be to define a user name when creating the invitation and not let the user choose when he is following the invitation.

**Comment by volter** [comment]
I should probably add that I've got auto_sign_up turned on.

**Comment by torkelo** [comment]
The self signup feature is not designed for auth proxy. If your using auth proxy your other user system should handle sign up and invite.
