### ISSUE TITLE
MSSQL Alert values

### ISSUE THREAD

**Issue by scottbarnesbass** [grafana/grafana#13987]
Hi all,

I'm finding that the values for being used to trigger an alert don't match the values of the graph view.

![alertgraphview](https://user-images.githubusercontent.com/22676381/48134862-285c2f00-e293-11e8-85f8-a64def38b73a.png)

![alertvalues](https://user-images.githubusercontent.com/22676381/48134918-55104680-e293-11e8-9e78-0eba82f24476.png)

Ideally I want to query the 2 values preceding the most recent incomplete timeGroup.

Windows 10 running Docker
v5.1.2
MSSQL DataSource

WITH benchmark AS (
	SELECT	sum(o.Total + o.Delivery)/4 as [Total]
	,		RIGHT('0' + CAST(datepart(weekday, o.InputDate) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH, o.InputDate) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, o.InputDate ) as varchar),2),1) as [DayHourTens]
	FROM	Orders o
	where	o.InputDate > DATEADD(day, -35, getdate())
	and		o.InputDate < DATEADD(day, -7, getdate())
	GROUP BY RIGHT('0' + CAST(datepart(weekday, o.InputDate) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH, o.InputDate) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, o.InputDate ) as varchar),2),1)
) , result AS (
	SELECT  $__timeGroup(o.InputDate,'10m') as time
	  ,sum(o.Total + o.Delivery) as Revenue
	FROM Orders o
	WHERE $__timeFilter(o.InputDate)
	AND o.Status > 3
	GROUP BY  $__timeGroup(o.InputDate,'10m')
)
select	(r.Revenue / b.Total) * 100 RevenuePercent
,		r.time
from	benchmark b
join	result r on b.DayHourTens = RIGHT('0' + CAST(datepart(weekday, DATEADD(S,r.time,'1970-01-01')) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH,DATEADD(S,r.time,'1970-01-01') ) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, DATEADD(S,r.time,'1970-01-01') ) as varchar),2),1) 
order by r.time

**Comment by marefr** [comment]
Please change your timerange in dashboard to last 30 minutes. Then use the query inspector in metric tab and include the full request/response data.

**Comment by scottbarnesbass** [comment]
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1541602597440",
      "to": "1541604397440",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 1000,
          "maxDataPoints": 1920,
          "datasourceId": 5,
          "rawSql": "WITH benchmark AS (\r\n\r\n\tSELECT\tsum(o.Total + o.Delivery)/4 as [Total]\r\n\t,\t\tRIGHT('0' + CAST(datepart(weekday, o.InputDate) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH, o.InputDate) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, o.InputDate ) as varchar),2),1) as [DayHourTens]\r\n\tFROM\ttbl_YC_Orders o\r\n\twhere\to.InputDate > DATEADD(day, -35, getdate())\r\n\tand\t\to.InputDate < DATEADD(day, -7, getdate())\r\n\t\r\n\tGROUP BY RIGHT('0' + CAST(datepart(weekday, o.InputDate) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH, o.InputDate) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, o.InputDate ) as varchar),2),1)\r\n\r\n) , result AS (\r\n\r\n\tSELECT  $__timeGroup(o.InputDate,'10m') as time\r\n\r\n\t  ,sum(o.Total + o.Delivery) as Revenue\r\n\tFROM\r\n\t  Orders o\r\n\tWHERE\r\n\t  $__timeFilter(o.InputDate)\r\n\t\r\n\tAND\r\n\t  o.Status > 3\r\n\tGROUP BY\r\n\t\t  $__timeGroup(o.InputDate,'10m')\r\n\r\n)\r\n\r\nselect\t(r.Revenue / b.Total) * 100 RevenuePercent\r\n,\t\tr.time\r\nfrom\tbenchmark b\r\njoin\tresult r on b.DayHourTens = RIGHT('0' + CAST(datepart(weekday, DATEADD(S,r.time,'1970-01-01')) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH,DATEADD(S,r.time,'1970-01-01') ) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, DATEADD(S,r.time,'1970-01-01') ) as varchar),2),1) \r\norder by r.time",
          "format": "time_series"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 0,
          "sql": "WITH benchmark AS (\r\n\r\n\tSELECT\tsum(o.Total + o.Delivery)/4 as [Total]\r\n\t,\t\tRIGHT('0' + CAST(datepart(weekday, o.InputDate) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH, o.InputDate) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, o.InputDate ) as varchar),2),1) as [DayHourTens]\r\n\tFROM\tOrders o\r\n\twhere\to.InputDate > DATEADD(day, -35, getdate())\r\n\tand\t\to.InputDate < DATEADD(day, -7, getdate())\r\n\t\r\n\tGROUP BY RIGHT('0' + CAST(datepart(weekday, o.InputDate) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH, o.InputDate) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, o.InputDate ) as varchar),2),1)\r\n\r\n) , result AS (\r\n\r\n\tSELECT  CAST(ROUND(DATEDIFF(second, '1970-01-01', o.InputDate)/600.0, 0) as bigint)*600 as time\r\n\r\n\t  ,sum(o.Total + o.Delivery) as Revenue\r\n\tFROM\r\n\t  tbl_YC_Orders o\r\n\tWHERE\r\n\t  o.InputDate >= DATEADD(s, 1541602597, '1970-01-01') AND o.InputDate <= DATEADD(s, 1541604397, '1970-01-01')\r\n\t--and\t\t(Reference LIKE 'YC%' or Reference LIKE 'YM%')\r\n\tAND\r\n\t  o.Status > 3\r\n\tGROUP BY\r\n\t\t  CAST(ROUND(DATEDIFF(second, '1970-01-01', o.InputDate)/600.0, 0) as bigint)*600\r\n\r\n)\r\n\r\nselect\t(r.Revenue / b.Total) * 100 RevenuePercent\r\n,\t\tr.time\r\nfrom\tbenchmark b\r\njoin\tresult r on b.DayHourTens = RIGHT('0' + CAST(datepart(weekday, DATEADD(S,r.time,'1970-01-01')) as varchar),2) + ' ' + RIGHT('0' + CAST(datepart(HH,DATEADD(S,r.time,'1970-01-01') ) as varchar),2) + ' ' + LEFT(RIGHT('0' + CAST(datepart(MI, DATEADD(S,r.time,'1970-01-01') ) as varchar),2),1) \r\norder by r.time"
        },
        "series": [
          {
            "name": "RevenuePercent",
            "points": [
              [
                179.61,
                1541602800000
              ],
              [
                218.86,
                1541603400000
              ],
              [
                145.58,
                1541604000000
              ],
              [
                0.97,
                1541604600000
              ]
            ]
          }
        ],
        "tables": null
      }
    }
  }
}

**Comment by marefr** [comment]
@scottbarnesbass Thanks. I can see that the last point is outside the selected time range, i.e.

Timerange between Wednesday 7 November 2018 14:56:37.440 AND Wednesday 7 November 2018 15:26:37.440
Points: 
  * Wednesday 7 November 2018 15:00:00
  * Wednesday 7 November 2018 15:10:00
  * Wednesday 7 November 2018 15:20:00
  * Wednesday 7 November 2018 15:30:00

Do you get a "points outside time range warning"? Are you using local browser time or UTC as dashboard timezone?

I would suggest you to try and skip looking at the last 10 minutes in the alert rule, i.e.
`Query(A, 30m, now-10m)` or `Query(A, 40m, now-10m)`

**Comment by scottbarnesbass** [comment]
with the Query(A, 30m,now-10m) i'm getting the following

From Query Inspector

0:Array[58.54,1541605200000]
1:Array[202.61,1541605800000]
2:Array[129.31,1541606400000]
3:Array[51.35,1541607000000]

From Alert

0:Array[24.56,1541605200000]
1:Array[202.61,1541605800000]
2:Array[91.3,1541606400000]

**Comment by scottbarnesbass** [comment]
Am I right in saying the Alert is running the query over that time range  Query(A, 30m,now-10m) and alerting based on that? And i think this is maybe whats happening, maybe that's going to trim the first ten minute grouping unless the Alert is triggered exactly on the 10 minute time...

**Comment by marefr** [comment]
> Am I right in saying the Alert is running the query over that time range Query(A, 30m,now-10m) and alerting based on that?

Yes that's correct

**Comment by scottbarnesbass** [comment]
Hmmm, this may be the problem as the Baseline results are group to whole 10 minute slots and the Results are getting grouped on the fly so if the alert captures 1 minute (or anything less than 10 minutes) of a 10 minute window, the percentage will be very low triggering a false possitive. 

Is there any way to get the alert to trigger more accurately than every 10 mintes?

**Comment by marefr** [comment]
#7886 is currently being worked on and should enable you to specify that alert triggering only if triggered during a period of time.

This can also be related to #12460 which is included in v5.3.0 stable. Would recommend you to upgrade if possible since it been some changes made to both mssql datasource and alerting.

**Comment by scottbarnesbass** [comment]
Really appreaciate all your help @marefr
