### ISSUE TITLE
Can't scroll in templating menu

### ISSUE THREAD

**Issue by rsmarques** [grafana/grafana#1398]
Hello,

I have a dashboard with a lot of template variables (using InfluxDB), and it turns out I can't scroll down in the templating menu in order to edit the last variables. An example is shown bellow.

Best regards,
Ricardo Marques

![screenshot 2015-01-27 18 51 36](https://cloud.githubusercontent.com/assets/4268735/5924718/dde08480-a655-11e4-9cbf-d07a2decfb58.png)

**Comment by torkelo** [comment]
I think you are using the template feature wrongly :)  

Why a template variable with a select mean(x) query? 

Could you explain what you are using the variables for and your scenario?

**Comment by rsmarques** [comment]
I'm using these variables in a specific HTML template that I made for a dashboard. Using Javascript, I can perform operations on values from different queries, a feature still not available in InfluxDB.
