### ISSUE TITLE
UI Bug: Can't exit kiosk mode on tablet/mobile

### ISSUE THREAD

**Issue by lorenwest** [grafana/grafana#13983]
### What Grafana version are you using?
5.3.0
### What datasource are you using?
N/A
### What OS are you running grafana on?
Android / iOS (browser)
### What did you do?
Press button to enter kiosk mode (awesome!)
### What was the expected result?
Ability to go back to non-kiosk mode
### What happened instead?
Couldn't find the [ESC] key :)
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
N/A

Posted on community forum, and there appears to be no way of exiting kiosk mode when running Grafana on a tablet or mobile device. Arguably, kiosk mode serve a great purpose on a restricted size device - it looks great on a tablet!

But we need to go back in order to interact with the menus. The suggested keyboard shortcut of pressing [ESC] is incorrect when there is no [ESC] key to press :)

Suggest adding a visual method, such as a floating icon. Extra points for making it disappearing on low event activity.

**Comment by torkelo** [comment]
You should be able to use browser “go back feature” .

The whole point of kiosk mode is to not show any UI button elements, so it’s really intended for iPads :)

**Comment by torkelo** [comment]
If browser go back does not work let me know and I will reopen.

In master I have also hidden the TV button smaller screen so depending on your tablet size it might not be shown anymore , but think it was only hidden for small mobile screens

**Comment by lorenwest** [comment]
Please don't hide the features for iPads and mobile - I use iPads as wall mounted monitors, and kiosk mode is especially useful for small real estate screens. I'm not aware of any back feature for iPads - they have a single button, and unless you know how to unload the app and reload (outside of kiosk mode) you're stuck.

If anyone knows a way to perform a browser/back while in kiosk mode, please share.

**Comment by lorenwest** [comment]
Would like to keep this open until a way is found to exit kiosk mode.

**Comment by torkelo** [comment]
iPad browser (safari or chrome) has a back button

**Comment by lorenwest** [comment]
Sorry this was just me. My app embeds a browser and removes browser chrome. I'll figure out something for my app. Thanks for your time, and for the sweetest dashboard on the planet!

**Comment by lorenwest** [comment]
@torkelo - I've been trying to get the back button working on a fresh Grafana 5.3.0 install, and although the URL is changed to remove the kiosk parameter, it doesn't trigger a refresh and it stays in kiosk mode. This was reproduced on mobile, tablet, and on a laptop.

Would you mind entering kiosk mode (on any device), then seeing if the back button can get you out?

Thank you.

**Comment by lorenwest** [comment]
By the way, I'm running grafana using `docker run -p 3000:3000 grafana/grafana:5.3.0`

**Comment by jonnor** [comment]
In Grafana 7.0.1 on Chrome from Android 9.0, it does not seem that the back button exits Kiosk mode.

**Comment by RzNmKX** [comment]
Back button does not exist kiosk mode in safari iOS 16.3.1

**Comment by mpw-eng** [comment]
Please re-open this issue.  The Google Chrome (v114.0.5735.99) Back button on iOS 16.5 and Grafana v9.5.3 does not exit kiosk mode.

Also, Grafana v9.5.3 does not have multiple levels of kiosk mode.  Grafana v9.3.6 had several levels of kiosk display, one that still displayed the kebab (vertical dot-dot-dot) menu.  This allowed the dashboard variables to be hidden (nice) but the user could still access the time range selection via the kebab menu (nice).  Now in v9.5.3, it is not possible to change the time range (bad) , or exit kiosk mode (bad) on Chrome and iPhone running iOS 16.5.
