### ISSUE TITLE
integrate a plugin to existing grafana

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1399]
Hi Torkel,

I am trying to integrate dataframe plugin to existing grafana install:

I download the files to plugins/dataframe directory, I then did this:

plugins: {
      // list of plugin panels
      panels: [],
      // requirejs modules in plugins folder that should be loaded
      // for example custom datasources
      dependencies: [],
      dataframe: [],
    }
Is this right or I put dataframe on its own plugins section?

**Comment by torkelo** [comment]
no, it does not look right, dataframe plugin? do you have a link for this plugin?

**Comment by gsaray101** [comment]
https://github.com/knabben/grafana/tree/master/src/plugins/dataframe

**Comment by gsaray101** [comment]
any ideas?

**Comment by torkelo** [comment]
Try this

```javascript
plugins: {
panels: [
 'dataframe': { path: '../plugins/dataframe' }
],
dependencies: [],
}
```

**Comment by gsaray101** [comment]
Torkel, have you tried this plugin like and worked? I am getting this error:

:8080/config.js?bust=1422543067998:98 Uncaught SyntaxError: Unexpected token :
app.fea68443.js:14 Uncaught TypeError: Cannot read property 'plugins' of undefined

**Comment by torkelo** [comment]
No I have not, what version of grafana are you using?

**Comment by gsaray101** [comment]
Grafana version: 1.9.0-rc1

**Comment by gsaray101** [comment]
Just tried it with version 1.9.1 the same error:

 Uncaught SyntaxError: Unexpected token :
app.fea68443.js:14 Uncaught TypeError: Cannot read property 'plugins' of undefined

**Comment by torkelo** [comment]
I did a mistake in my suggestion, try this:

Try this

```javascript
plugins: {
panels: {
 'dataframe': { path: '../plugins/dataframe' }
},
dependencies: [],
}
```

**Comment by gsaray101** [comment]
Hi torkel,

Did u try this? Does it work for u?

**Comment by torkelo** [comment]
No I have not tried this panel
