### ISSUE TITLE
Can not run master: can't evaluate field AppNameBodyClass in type *dtos.IndexViewData

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#13997]
### What Grafana version are you using?
Master

### What OS are you running grafana on?

Linux x86_64

### What did you do?

```
make clean
make deps-js
make deps-go
make build-js
make build-go
./bin/grafana-server
```

open 127.0.0.1:3000

### What was the expected result?

grafana login page
### What happened instead?

white page with
```
template: index:26:34: executing "index" at <.AppNameBodyClass>: can't evaluate field AppNameBodyClass in type *dtos.IndexViewData
```

**Comment by roidelapluie** [comment]
My bad: server is now at bin/linux-amd64/grafana-server ... bin/grafana-server is probably old stuff

**Comment by dudumao520** [comment]
Hi,I have the same problem. How do you deal with it?@roidelapluie

**Comment by torkelo** [comment]
Rebuild frontend with npm run dev (or watch)

**Comment by roidelapluie** [comment]
@dudumao520 So the location of the server binary has changed and I was still running the old one ... check you are running the right binary.
