### ISSUE TITLE
Variables Passed To Drilldown In Wrong Format

### ISSUE THREAD

**Issue by jigpjames** [grafana/grafana#14005]
Verson: Grafana v5.2.3
Datasource: Elasticsearch 6.4.0
O/S: MacOS Mojave

What did you do: Created a Link to a drilldown dashboard, including Variables.

What was the expected result: That the Variables would pass to the drilldown dashboard in the same format that is used on the main dashboard.

What happened instead: The formatting of the Variables changed, which changed the query, which gave different results than expected.

Here is the Link on the main dashboard pointing to the drilldown dashboard:
![2018-11-08_17-10-06](https://user-images.githubusercontent.com/42621410/48230553-6f245480-e379-11e8-87cd-f2caad997125.png)

Here you can see that the there are 15 resulting rows instead of just the 2 rows I should be seeing. The format of the variables does not yield an EXACT search, but rather a LIKE search, because the quote marks and escape characters are incorrect:
![2018-11-08_16-51-31](https://user-images.githubusercontent.com/42621410/48230813-46e92580-e37a-11e8-8a38-4416dfe0193e.png)

Here is just the query text from the above screenshot:
{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"jigsawsessionattendeeassets\",\"max_concurrent_shard_requests\":256}\n{\"size\":10000,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1533934230813\",\"lte\":\"1541710230813\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"companyid:* AND hostname:Downing,\\\\ Melissa AND sessionname:MELISSA'S\\\\ PRODUCTION\\\\ TEST\\\\ SESSION AND attendeename:* AND triggertypename:*\"}}]}},\"sort\":{\"@timestamp\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}},\"script_fields\":{},\"docvalue_fields\":[\"@timestamp\"]}\n"

If I simply un-click, then re-click the exact same values from the filter dropdowns, then the formatting is correct, an EXACT match is performed, and I only get back the 2 expected rows:
![2018-11-08_16-55-37](https://user-images.githubusercontent.com/42621410/48230939-a21b1800-e37a-11e8-9d4f-3cddcaa79648.png)

Here is just the query text from the above screenshot (notice the difference in how the HostName variable is formatted):
{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"jigsawsessionattendeeassets\",\"max_concurrent_shard_requests\":256}\n{\"size\":10000,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1533934515530\",\"lte\":\"1541710515530\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"companyid:* AND hostname:(\\\"Downing,\\\\ Melissa\\\") AND sessionname:(\\\"MELISSA'S\\\\ PRODUCTION\\\\ TEST\\\\ SESSION\\\") AND attendeename:* AND triggertypename:*\"}}]}},\"sort\":{\"@timestamp\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}},\"script_fields\":{},\"docvalue_fields\":[\"@timestamp\"]}\n"

The variables are setup exactly the same on both the Main dashboard and the Drilldown. I actually did a Save-As on the Main dashboard to create the Drilldown to ensure there were no typos. Here is the variable list:
![2018-11-08_17-04-39](https://user-images.githubusercontent.com/42621410/48231008-cd056c00-e37a-11e8-9689-cf97595925d8.png)

And here is the definition of the HostName variable:
![2018-11-08_17-05-25](https://user-images.githubusercontent.com/42621410/48231030-e27a9600-e37a-11e8-8081-b709ccf45be9.png)

I have about 5 different drilldown dashboards from one main dashboard, and they all exhibit this same behavior of reformatting the variables when they are passed to the drilldown. I appreciate your help!

Thanks!
Paul

**Comment by torkelo** [comment]
Could you show the url values?

**Comment by jigpjames** [comment]
I think this is what you are asking for, please let me know if you meant something else. I opened the Chrome developer console and grabbed the entries created when I set the variables on the main dashboard, and then you can see where I clicked the link to the drill-down and the variables being passed...

![image](https://user-images.githubusercontent.com/42621410/48277707-7864fe00-e419-11e8-802f-5a4f0385932d.png)

Thanks!
Paul

**Comment by jigpjames** [comment]
In case you can't read the screenshot, here is the same in plain text...

store updating angular $location.url /d/PdYtm81ik/jigsaw-administrators-dashboard?orgId=2&var-varcompanyid=All&var-varcompanyname=All&var-varhostname=Downing%2C+Melissa&var-varsessionname=All&var-varusername=All&var-varborname=All&var-varuserrole=All
[Violation] 'setTimeout' handler took 68ms
Sending APH request...
'setTimeout' handler took 61ms
[Violation] 'load' handler took 161ms
[Violation] 'setTimeout' handler took 713ms
[Violation] Forced reflow while executing JavaScript took 64ms
store updating angular $location.url /d/PdYtm81ik/jigsaw-administrators-dashboard?orgId=2&var-varcompanyid=All&var-varcompanyname=All&var-varhostname=Downing%2C+Melissa&var-varsessionname=MELISSA'S+PRODUCTION+TEST+SESSION&var-varusername=All&var-varborname=All&var-varuserrole=All
[Violation] 'setTimeout' handler took 59ms
Sending APH request...
[Violation] 'setTimeout' handler took 82ms
[Violation] 'setTimeout' handler took 77ms
store updating angular $location.url /dashboard/db/session-assets-used?from=now-30d&to=now-1h&var-varcompanyid=All&var-varcompanyname=All&var-varhostname=Downing%2C+Melissa&var-varsessionname=MELISSA'S+PRODUCTION+TEST+SESSION&var-varusername=All&var-varborname=All&var-varuserrole=All
Sending APH request...
store updating angular $location.url /d/iUsNPpamk/session-assets-used?from=now-30d&to=now-1h&var-varcompanyid=All&var-varcompanyname=All&var-varhostname=Downing%2C+Melissa&var-varsessionname=MELISSA'S+PRODUCTION+TEST+SESSION&var-varusername=All&var-varborname=All&var-varuserrole=All
store updating angular $location.url /d/iUsNPpamk/session-assets-used?from=now-30d&to=now-1h&var-varcompanyid=All&var-varcompanyname=All&var-varhostname=Downing%2C+Melissa&var-varsessionname=MELISSA'S+PRODUCTION+TEST+SESSION&var-varusername=All&var-varborname=All&var-varuserrole=All&orgId=2

Thanks!
Paul

**Comment by jigpjames** [comment]
We have discovered a temporary workaround for this issue.

We found that the DrillDown Dashboards do not accept "var-var{parameter}" as a filter param. But, when you add "var-var{parameter}=All" to the URL, the filters work as expected. 
Example:
var-varhostname=Downing,%20Melissa   (will not filter correctly)
var-varhostname=Downing,%20Melissa&var-varhostname=All   (will filter correctly)

Our workaround is this...
We created Javascript code that examines the URLs generated for any drill-down:
1. Get query string and split by parameters
2. Check if there is a variable parameter with a value of "All"
3. If not, inserts the "All" parameter into the URL.

This workaround works for a single or multiple filters. 

Hopefully, this information will give you what you need to better debug and permanently fix the issue.

Thanks!
Paul

**Comment by sreeprathyusha6** [comment]
i am trying to render a column value $__cell_0(which is long in terms of length) so i dont want to expose that value in url , is there any way to avoid this either using variables?  if yes can you suggest me.Thanks in advance!

 @torkelo

**Comment by hugohaggmark** [comment]
@jigpjames sorry for this very late response but I'd like to know if you've upgraded to a later version of Grafana and if you're still experience this issue?

**Comment by jigpjames** [comment]
@hugohaggmark To be honest, once we implemented the workaround, we never went back. We utilize Grafana in a multi-tennant environment, so we must do a good bit of customizations to ensure data segregation for customers, and this just became part of our overall customization. We always upgrade to the newest versions, so if we have time later this summer, we will try the native route with this and I will update here. By the way, let me just say that we really love using Grafana!!! :)

**Comment by daniellee** [comment]
The data links code has been re-written since this issue was opened so closing but if this is still a bug then we can re-open.
