### ISSUE TITLE
Unauthorized error using API to export PDF

### ISSUE THREAD

**Issue by mfarook** [grafana/grafana#14018]
I had successfully setup Reporter in my local system. I tried exporting to pdf using api "http://localhost:8686/api/v5/report/4LC-RVfiz" Am getting an error error fetching dashboard 4LC-RVfiz: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/4LC-RVfiz. Got Status 401 Unauthorized, message: {"message":"Unauthorized"} . Is this because of API key issue?if so, how to create API key using Grafanna?

**Comment by daniellee** [comment]
You can create an API key via the UI: <your_grafana_url>/org/apikeys

and then you can use the API key created as a parameter to Reporter (as mentioned in its [readme](https://github.com/IzakMarais/reporter)).

**Comment by mfarook** [comment]
Thanks a lot. That worked
