### ISSUE TITLE
Grafana and Google Ads

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#14013]
Is it possible to add Google Ads to grafana page, for example on the top and the bottom of the page?

**Comment by buroa** [comment]
Edit the html

**Comment by szerwi** [comment]
@buroa but which file, where can I find it?

**Comment by bergquist** [comment]
This is not something we encourage. But since its open source, you can modify Grafana and build your own version.

**Comment by marefr** [comment]
@szerwi May I ask about the use case for this? Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You have to build grafana from source after you've modified /public/views/index-template.html.

**Comment by marefr** [comment]
@szerwi http://docs.grafana.org/project/building_from_source/#building-grafana-from-source

**Comment by szerwi** [comment]
So there is no easier way to do it, like adding html code to the specific dashboard code?

**Comment by marefr** [comment]
@szerwi If you just want to include google ads in a dashboard you should be able to use the text panel and select html mode which allows you to include custom javascript and html.

**Comment by szerwi** [comment]
@marefr I've tried to add it to the text panel, but Google can't find their code then. It should be implemented between <head> and </head> on the site. BTW, Google said that there is no valuable content on my site for their adds... :D
