### ISSUE TITLE
Grafana heatmap wrong color

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#14019]
Please include this information:
### What Grafana version are you using?
5.3.2
### What datasource are you using?
prometheus
### What OS are you running grafana on?
No matter
### What did you do?
Plot heatmap panel 
### What was the expected result?
Color scale and colors on panel have the same colors
### What happened instead?
Scale has different color than panel. But bucket size is 1 as on scale
### If related to metric query / data viz:
![image](https://user-images.githubusercontent.com/289277/48336268-fa029900-e670-11e8-91b9-356b30e16ccc.png)

**Comment by daniellee** [comment]
I am not able to recreate this easily. Could you show an example query that produces the above results? Can you also include which datasource, screenshots of the the Axes tab settings and of the Display tab settings. Thanks

**Comment by Yukinoshita-Yukino** [comment]
@daniellee 
I also got this problem.
Using metricbeat data in elasticsearch 6.3.1 as datasource.
These are my settings.

<img width="1349" alt="wx20181120-180207 2x" src="https://user-images.githubusercontent.com/3638888/48766028-7a1ea380-ecee-11e8-8703-68cc8cb47054.png">
<img width="705" alt="wx20181120-180219 2x" src="https://user-images.githubusercontent.com/3638888/48766030-7a1ea380-ecee-11e8-8d0b-aae743ae2460.png">
<img width="1192" alt="wx20181120-180230 2x" src="https://user-images.githubusercontent.com/3638888/48766031-7ab73a00-ecee-11e8-9631-4e591a25b8ae.png">
