### ISSUE TITLE
Influx metric as boolean does not trigger alert

### ISSUE THREAD

**Issue by yves-bourgeois** [grafana/grafana#14010]
Please include this information:
### What Grafana version are you using? 
version 5.3.2
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu
### What did you do?

- Created metric select on a measurement that returns a boolean value every 5 seconds.  Query simply returns the raw data from the database
- Plotted OK on the graph (with the boolean false --> 0 and true --> 1)
- Created alert on this select: value above 0.5 should trigger an alert

### What was the expected result?
When the boolean goes from false to true, an alert should have been created.  

A boolean should be regarded as a 0 or a 1, so we can use the current alert system exactly as an integer value.  Or..  extra conditions that can deal with booleans.

### What happened instead?
No alert happened.
The query (see Raw Data) seems to return null

### Raw Data
When testing the alert, the query always seems to return null, even when data is actually present in the database
firing:false
state:"no_data"
conditionEvals:"false = false"
timeMs:"10.739ms"
logs:Array[2]
0:Object
message:"Condition[0]: Query Result"
data:Array[1]
0:Object
name:"HE_Sensor_1_shadow_possible.value"
points:Array[12]
0:Array[null,1541770680]
1:Array[null,1541770685]
2:Array[null,1541770690]
3:Array[null,1541770695]
4:Array[null,1541770700]
5:Array[null,1541770705]
6:Array[null,1541770710]
7:Array[null,1541770715]
8:Array[null,1541770720]
9:Array[null,1541770725]
10:Array[null,1541770730]
11:Array[null,1541770735]
1:Object
message:"Condition[0]: Eval: false, Metric: HE_Sensor_1_shadow_possible.value, Value: null"
data:null

**Comment by sunker** [comment]
Unfortunately boolean type casts are not supported in the influx query language. See more here #12997 
Closing in favor of #8152. Implementing boolean support for influx db will fix both issues.
