### ISSUE TITLE
S3 IAM roles are not working while uploading a file

### ISSUE THREAD

**Issue by shrevani** [grafana/grafana#14017]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.2.1
### What did you do?
Trying to push alert panel image to s3 bucket
### What was the expected result?
Images should be uploaded on the bucket
### What happened instead?
Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: [...], host id: [...]

I configured an S3 bucket. Created an IAM role with Read and Write permissions over that bucket and assigned it to the server.
The IAM role is working, as I am able to Read/Write to the bucket using aws cli without using any Access Key and Secrete Key.
In grafana config i have provided bucket name and region name. But when alert is triggered we are getting below error
t=2018-11-07T23:35:09-0500 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: ........., host id: ............."
Please correct me if i am doing anything wrong.

**Comment by sunker** [comment]
There is a similar issue #12619. Are you running Grafana on EC2 or ECS? For server authentication we currently only have support for EC2 auth.

**Comment by shrevani** [comment]
We are running Grafana on EC2.

**Comment by daniellee** [comment]
@shrevani sounds like you haven't configured it correctly - can you let us know if @aidan- 's advice worked for you.

**Comment by kshcherban** [comment]
Works for me with 5.3.2, related issue #12619

**Comment by daniellee** [comment]
@shrevani how did it go with this? Did you get it working?

**Comment by shrevani** [comment]
@daniellee no still it is not working. As aidan said should try to debug it using cloud trial.

**Comment by bergquist** [comment]
Closing this since it seems to be a configuration error. Otherwise, this issue would have many more comments.
