### ISSUE TITLE
Unresponsive script when influxdb is sending -1.7976931348623157e+308 as data point

### ISSUE THREAD

**Issue by xo4n** [grafana/grafana#1402]
Because of the following bug in influxdb https://github.com/influxdb/influxdb/issues/1438 when using running max() in a series will result in the following values being returned 
 
```json
        [1422298800000, 254.204675],
        [1422300600000, -1.7976931348623157e+308],
        [1422302400000, -1.7976931348623157e+308],
        [1422307800000, -1.7976931348623157e+308],
        [1422370800000, 630.052634]
```
that causes the following while loop to iterate endless and the dashboard to become unusable 

https://github.com/grafana/grafana/blob/14e1bc870291fe24e3a2ec575e626bb5265e5cf1/src/app/components/kbn.js#L325

It might be helpful to check the conformity of that value before the while loop runs to avoid the endless loop

**Comment by torkelo** [comment]
Thanks for reporting this, will fix!

**Comment by torkelo** [comment]
Fixed in develop branch
