### ISSUE TITLE
Grafana Hourly Alert Problem - Important

### ISSUE THREAD

**Issue by cemkuleyin** [grafana/grafana#14029]
Hello everyone, 

I have a big problem with grafana alerting. We installed grafana (Grafana v5.3.2 (0d821d0)) for elasticsearch. We want to create important alert for us. But we dont understant how to create.

Basicly, we created alert of sum some field. But we want to create hourly alert of our sales. For example,

we are selling 150 ticket every hour. If our average of ticket is lower than last hour (compare 3:00 pm- 4pm and 4pm-5pm) then alert will fire. Now, i created alert on 4:16 pm. grafana controlled 4pm-4:16pm and 3:16pm - 4pm. its wrong way.

Can you explain please.

Thank you.

Cem.
Kind regards

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

And include your ES query, inspector query response, and Alert Rule Test results
