### ISSUE TITLE
Update Macaron

### ISSUE THREAD

**Issue by nicolasStevenin** [grafana/grafana#14025]
Old macaron used github.com/go-macaron/session but the repo doesn't exist anymore

Please consider to update it
Thanks.

**Comment by bergquist** [comment]
https://github.com/go-macaron/session do exist. 
they added commits a few days ago https://github.com/go-macaron/session/commits/master

**Comment by nicolasStevenin** [comment]
My bad, I looked for **github.com/go-macaron/macaron**/session and it's the project github.com/go-macaron/session...
