### ISSUE TITLE
Improve error message when parsing Prometheus template variable query

### ISSUE THREAD

**Issue by iordaniordanov** [grafana/grafana#14027]
Hello, checking if there is a plan to include functionality to allow pretty fail of the Template variables. Currently if my template variable initialization fails I get something like 
```
Templating init failed:
parse error at char 18: unexpected "}" in label matching, expected string 
```
I think it would be really useful to implement something like:
```
Config option: 
variable_pretty_fail: true/false
varible_pretty_fail_text: "No alerts firing" or "Error occured, please contact ..."
```

Thank you for the good work :)

Please include this information:

**Comment by torkelo** [comment]
Not sure an option makes sense. But maybe better error message when parsing the Prometheus variable query.

**Comment by davkal** [comment]
For syntax errors we rely on the datasource, and this is what it returns.

**Comment by iordaniordanov** [comment]
thanks, it is not big of a deal, now that I think about it, what would you say about a mechanism, providing the ability to configure a generic error substitution. Errors are useful for me when I work on something, but when the users come in, they(at least in my case) don't care what the error is, they need to know who to contact regarding the error. So a simple "An error occurred. Please contact <email>" would be more useful in some cases. What do you think about this, should I open a new ticket for it ?
