### ISSUE TITLE
Trying to get multi value selection configured for variable in Cloudwatch EC2 dashboard

### ISSUE THREAD

**Issue by meet101** [grafana/grafana#14036]
I am using Cloudwatch data source and trying to get multiple EC2 servers graph in a single panel. I am using region, instanceid and instance name as variables. Everything works fine if I have single value selection configured. it gives me specific server's graph based on instance id and/or instance name. my variables looks like,

$region regions()
$instancename ec2_instance_attribute($region, Tags.Name, {})
$instanceid ec2_instance_attribute($region, InstanceId, {"tag:Name": ["$instancename"]}) 

I am trying to configure it multi value to selected in instance name and I want to have all selected server's graph in that panel. I tried couple of things but didn't get working. This is working if I do only with instance id and region. I can select specific region and inside that region I can select multi values in instance id variables. it gives me all those instances graph. but it's not working when I choose instance name. I tried instance name alone without instance id. I can see api is getting all instances name in preview but it's not giving any data points. so I think I do need to have instance id configured as multi value enabled variables and depends on it, I need to get instance name fo reach of selected instance id. I am guessing I need regex for this? can someone please help me on this?

I tried with only instance id and it's working,
$region regions()
$instanceid ec2_instance_attribute($region, InstanceId, {}) - Multi value enabled

Now, I need to get $instancename variable with multi-value enabled. can't get it working. can someone please help?

Thanks in advance!

**Comment by sunker** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
