### ISSUE TITLE
series override regex does not work 1.9.1

### ISSUE THREAD

**Issue by chaoskcw** [grafana/grafana#1404]
Regex expressions dont work in Series Overrrides in 1.9.1

I am using a dynamic series name using template variables e.g

new / $interval

Regex expressions for series override (none work):

new
new*
new / [0-9]*

I am trying to match to changing interval descriptions

**Comment by torkelo** [comment]
you need to wrap the series override expression in `/`  characters to let grafana know you want regex matching

**Comment by chaoskcw** [comment]
Thx, I did search documentation and google, missed that. This works. I am closing this issue.

**Comment by languitar** [comment]
Maybe adding a tooltip for this would be really helpful.

**Comment by languitar** [comment]
Oh, there is...

**Comment by sbeh** [comment]
I hit this problem again and made #11164

Can't waste my time reading license agreements for open source contributions, so I guess this will disappear unnoticed.

**Comment by jdmarshall** [comment]
> Oh, there is...

I've been trained by years of using WebStorm to think of 'regex' as the pattern between the slashes, not including them. :/
