### ISSUE TITLE
Tag value to panel description

### ISSUE THREAD

**Issue by ondrejFuchs** [grafana/grafana#14045]
Hi, 
is it possible to add tag value to pannel description? For example:
state, host=dev1, location="Prague" state=1.

In grafana variable i use "Value groups/tags (Experimental feature)":
SHOW TAG VALUES FROM "state" WITH KEY = "host"

SHOW TAG VALUES FROM "state"  WITH KEY = "location"
SHOW TAG VALUES FROM "state" WITH KEY = "host" WHERE location = '$tag'

Can I use something like "$tag" variable to autogenerate description of panels (for example Sigle panel)

Thanks for the response.

**Comment by sunker** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
