### ISSUE TITLE
how to query variable  `select port as $PORT from labels where IP=$IP` via prometheus datasource 

### ISSUE THREAD

**Issue by naughtyGitCat** [grafana/grafana#14041]
how to write  `select port as $PORT from metrics where IP=$IP` in prometheus panel query

### What Grafana version are you using?
5.1.3
### What datasource are you using?
prometheus
### What OS are you running grafana on?
fedora28
### What did you do?
all metrics have label IP and label PORT
### What was the expected result?
variable PORT=$(select port  from labels where IP=$IP)
### What happened instead?
variable PORT= $(select port as $PORT from labels)

**Comment by sunker** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
