### ISSUE TITLE
Grafana 3.1.1 and Elasticsearch 5.3.0 connectivity Issue

### ISSUE THREAD

**Issue by praveenkumar-9** [grafana/grafana#14050]
Hi All,

i am using 
Grafana 3.1.1 
Elasticsearch 5.3.0
OS - Redhat Linux

i am unable to establish connection to elasticsearch and no log data displayed in dashboard.

i tried with Proxy and Direct access , even i have updated elasticsearch.yml file for CORS with 
http.cors.enabled: true
http.cors.allow-origin: "*"

but in vain.

is there any possible way to establish connection to elasticsearch using grafana 3.1.1.

Regards,
Praveen.

**Comment by sunker** [comment]
@praveenkumar-9, in order to use Elasticsearch 5.x, you need to upgrade Grafana to version 5.x.

**Comment by marefr** [comment]
Just noticed that from Grafana v4.1 Elasticsearch 5.x is supported.
