### ISSUE TITLE
some series do not get populated version 1.9.1

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1405]
I am seeing that some series on chart do not get populated. This is the error:

app.496fdc2e.js:23 

flotcharts error Error: Invalid dimensions for plot, width = 0, height = 195 {stack: (...), message: "Invalid dimensions for plot, width = 0, height = 195"}

**Comment by gsaray101** [comment]
this error shows up when there are 3 charts in the same window.

**Comment by gsaray101** [comment]
Torkel, I am seeing something definetely weird. There is definetely data in the backend. When I create charts sometimes data shows up sometimes it is not showing up. Any ideas, why some series is missing.I dont see anything other than this error:

flotcharts error Error: Invalid dimensions for plot, width = 0, height = 195
app.fea68443.js:23 flotcharts error Error: Invalid dimensions for plot, width = 0, height = 195
app.fea68443.js:23 flotcharts error Error: Invalid dimensions for plot, width = 0, height = 195
app.fea68443.js:23 flotcharts error Error: Invalid dimensions for plot, width = 0, height = 195

**Comment by torkelo** [comment]
strange. What browser & are you using? 

The flotcharts should only happen when you resize the window (or when you bring up the chrome dev console), its a strange bug in width calculation that happens directly after resize, tried a bunch of ways to eliminate that error but have not managed to eliminate it completely. But have never seen a bad effect of that error, they graph should still be drawn.

Are you saying that you see one one or more series missing from a graph? so the graph is not empty but some series are missing? Can you have chrome dev tools open when you replicate this and inspect the response from graphite or influxdb?

**Comment by gsaray101** [comment]
Torkel, It looks there is a problem with Opentsdb meta sync functionality to create trees. I think this is causing the problems.

**Comment by torkelo** [comment]
meta sync?

**Comment by gsaray101** [comment]
Yes, there is a process to create trees. There seems to be a bug. I'll let u know.

**Comment by jlming6** [comment]
Saw same error on chrome:
flotcharts error Error: Invalid dimensions for plot, width = 778, height = 0
![image](https://cloud.githubusercontent.com/assets/465602/11987067/665ebe04-a98d-11e5-90de-65ac2ba460fa.png)

If i call the src url directly, it works well. And from the network resources, it return the correct values.
