### ISSUE TITLE
Use more specific version number if using "master"

### ISSUE THREAD

**Issue by entropyfarms** [grafana/grafana#1406]
There is a nice feature to show the current grafana version by clicking the gear (settings) icon.  For installs from repo it shows only "master" (presumably just the branch name).  It should include some identifying information about the commit (maybe commit hash?).  Otherwise its difficult to remember whether we should upgrade without logging into the server and checking by git-log.

**Comment by torkelo** [comment]
when doing builds from master using "go run build.go build" you will get the correct version built into the binary
