### ISSUE TITLE
File structure under features/dashboard is a mess

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14062]
Currently it's a mess with random stuff in root folder and mix of "component" / feature folders. And most new react stuff under dashgrid folder. 

Some alternatives 

* dashboard
  * components (mix angular & react components, either flat or in component folders)
  * models (mostly for DashboardModel and PanelModel)
  * containers
  * actions
  * reducers
  * utils
  * services (for angular services)
 
Alternative
* dashboard
   * state (models & redux)
   * utils
   * services (for some angular services) 
   * panels (panel related components)  
   * grid (grid related components)
   * editing (Panel editing related components) 
   * timepicker
   * permissions 
   * exporting

Feels like this last option is  mxing feature areas and concepts folders which is not ideal. Any other alternatives?

**Comment by dprokop** [comment]
Some initial brain dump:
- `dashgrid` - not sure if it belongs to dashboard feature at all. I think it's a grafana/ui component that *enables* Dashboard feature 
- 'PanelHeader' -> grafana-ui
- As we have a mix of angular/react code there I think we should keep all dashboard'd UI component in `dashboard/components` folder. For *areas* that have single component file (e.g. DashboardPermissions) don't create subfolder.
- I opt for `state` dir for business logic, redux, models etc
- **Long term**: Not sure if all services that are in dashboard now should belong there (e.g. Explore uses `TimeSrv` from dashboard). Also, we could think about features as service agnostic components. Meaning that they could accept services as prop that is specified API compliant.
- Panel's related code (edit in particular) should not be a part of dashboard feature. I think it should belong to `panels` feature. Some of the panel's code (UI) will land in grafana/ui anyways.
