### ISSUE TITLE
Dashboard variable Tag Values based on time range?

### ISSUE THREAD

**Issue by n1nj4888** [grafana/grafana#14061]
Please include this information:
### What Grafana version are you using?

Grafana v5.2.4 (commit: 0bbac5c) - Official Grafana Docker

### What datasource are you using?

InfluxDB 

### What OS are you running grafana on?

Official Grafana Docker

### What did you do?

Is there a way to base Grafana Dashboard Variables on a time range? For example, the following variable query on the docker plugin (Docker Container Names) pulls back all of the container names that have ever run on the docker host, including some that my have been deleted a long time ago...

**"Container"** Variable
show tag values from docker_container_cpu with key="container_name"

Can this be modified in any way to say "give me the list of container names that have metrics gathered in the current Time Interval / Last 30 days etc"?

### What was the expected result?

Docker variables can be based on a time range (dashboard interval / static time frame such as "last 30 days")

### What happened instead?

Docker container name variables list all of the container names ever run on the system, including ones which are no longer running / collecting metrics.

**Comment by sunker** [comment]
Support for timeFilter in InfluxDb template query was added in Grafana version 5.3.0, so you need to upgrade for this to work. See #12598.

**Comment by marekjagielski** [comment]
I understand that this is working only for SELECT not for SHOW TAG because of https://github.com/influxdata/influxdb/issues/5668
Am I right?

**Comment by n1nj4888** [comment]
Hi @sunker,

Thanks for pointing out this had been fixed/added in 5.3 - I've now updated to Grafana v5.3.4 (commit: 69630b9) but it's not clear to me how I filter the vaules the variable can take using a time/active filter and I don't seem to be able to find an example for how to do this in the Grafana Documentation?

For example, my Docker dashboard uses the following variable which gets ALL of the docker container names:

**$Conatiner** = 
show tag values from docker_container_cpu with key="container_name"

This returns all of the container names ever seen but not sure how to change this to say "$Container should be all of the **active container names during the currently selected time interval?**

@marekjagielski - If this works only on SELECT rather than SHOW TAG queries, this seems to be an issue since my understanding was that if the value being selected was a TAG KEY (such as "container_name" in my example above), these TAG KEYS cannot be part of a SELECT query i.e. the following reformatting of the SHOW TAG query above into a SELECT query returns nothing for me:

SELECT "container_name" FROM docker_container_cpu 

Thanks!

**Comment by torkelo** [comment]
Only select supports a time filter I think , so you need to use that. But not sure how the quer looks , checked influxdb docs ?

**Comment by n1nj4888** [comment]
Yes, checked the docs but can't find any example which shows how to make a SHOW TAG VALUES variable time dependent i.e. give me only those TAG VALUES which have been active in <Time Filter>

**Comment by BushnevYuri** [comment]
Found workaround for all of those who are looking to use tags from InfluxDB with respect of timeFilter for Grafana variables templating.

https://stackoverflow.com/questions/54931888/query-tags-from-influxdb-with-respect-of-timefilter-for-grafana-variables-templa/54933003#54933003
