### ISSUE TITLE
how to enable  auth.anonymous  with http api?

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#14060]
Hi, 

     Can I enable anonymous with http api?

"auth.anonymous":{
    "enabled":"true",
    "org_name":"Main Org.",
    "org_role":"Viewer"
  },

Please include this information:
### What Grafana version are you using?
5.3
### What datasource are you using?
influxdb
### What OS are you running grafana on?
ubuntu16

**Comment by sunker** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
