### ISSUE TITLE
same time,same metric, but graph is different

### ISSUE THREAD

**Issue by dinggel** [grafana/grafana#14063]
Please include this information:
Grafana v5.1.3 (087143285)
sqlite3
centos6.7 final
### What did you do?
 Keep switching between two different graphs，then, i found that
![image](https://user-images.githubusercontent.com/22829724/48465931-560b2000-e81f-11e8-9019-e48f65181ce9.png)
![image](https://user-images.githubusercontent.com/22829724/48465937-59061080-e81f-11e8-9e10-08826e78477c.png)

**Comment by sunker** [comment]
Please provide raw request. 

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
