### ISSUE TITLE
API problems, occasional error 500

### ISSUE THREAD

**Issue by GrishaDev** [grafana/grafana#14079]
Hey,

### What Grafana version are you using?
5.3.1
### What datasource are you using?
Elasticsearch 6.3.2
### What OS are you running grafana on?
ubuntu 16 
### What did you do?
I have a node service that will do http request to /api/dashboards/db with json of the dashboard.
### What was the expected result?
to get status success and have a dashboard on grafana.
### What happened instead?
http error 500 with message "failed to save dashboard"
Now here goes the unsual part, it worked before, i never changed the code and it just started failing the request sometimes, right now 95% of time the request will fail, but sometimes still work.
So that doesn't seem to be issue with json it self, as it does work sometimes.
I tried adding timeout 10seconds option to request, but it didn't help.

I also noticed when it did save the dashboard, the included alert didn't work as expected and i got a couple mails with following errors:
tsdb.HandleRequest() error post  **elastic ip** EOF
and a picture of Rendering error: concurrent server side render limit reached.

The server is strong and there is enough disk space, ram and cpu left, i tried restarting grafana.

And i did read other similar posts about tsdb.handlerequest, didn't find any solution ;/
Thanks.

**Comment by marefr** [comment]
Please include grafana server log when this happens.

**Comment by GrishaDev** [comment]
> Please include grafana server log when this happens.

Unfortunately i can't upload the log file as it's in closed network, i noticed in the log often message 
"Database table locked, sleeping then retrying"
and the rest are a bunch of alert errors on the the very few created dashboards by API which probably are broken and result similar error(database locked)
most often message:
"failed to send notification logger=alerting.notifier id=1 error="database table is locked"

I also noticed overall grafana is using way too much ram, it used 96% of RAM, when i have 8gb.
I upgraded to 16gb now and seems to slowly consume everything again..
I restarted grafana and system a couple times.

**Comment by GrishaDev** [comment]
> how many alert rules do you have? And how often are they evaluated?
> 
> How are you authenticating the api calls?

About 70 alert rules, they evaluate every 1hour, but i also tried with just 1-3 alert rules and it's the same.
i authenticate using bearer api key, it works fine on every request, expect the POST  /api/dashboards/db
where it will fail 90% of time(and the 10% of time it does work, it will result in corrupted alert)

**Comment by marefr** [comment]
@GrishaDev how often are you sending POST request to /api/dashboards/db? If you can, please enable debug logging and then capture your grafana server log file and then email it to me (mefraimsson (at) grafana.com).

**Comment by marefr** [comment]
@GrishaDev Okay. I would recommend you to enable the following debug logger and then check the log after you've received  "Failed to save alert data" error:

```ini
[log]
filters = alerting.extractor:debug
```

**Comment by GrishaDev** [comment]
> @GrishaDev Okay. I would recommend you to enable the following debug logger and then check the log after you've received "Failed to save alert data" error:
> 
> ```ini
> [log]
> filters = alerting.extractor:debug
> ```

It outputs the same errors in log.
I added the filters in grafana.ini under [log] and catched the same errors in grafana.log after running the request.

**Comment by marefr** [comment]
Okay, then it seems like an error is happening before anything is logged. Seems like we need to add some debug statements to the code to better be able to track down why this is happening.

**Comment by GrishaDev** [comment]
> Okay, then it seems like an error is happening before anything is logged. Seems like we need to add some debug statements to the code to better be able to track down why this is happening.

Is there any potential workaround to make it work?
Does this request work for you? If so, how can i make it work for me?

**Comment by marefr** [comment]
That's an exported dashboard. You can only import that thru the import dashboard ui, not api. Please see [http api documentation](http://docs.grafana.org/http_api/dashboard/#create-update-dashboard) for reference. 

#13781, included in Grafana v5.3.4 allows you to select if you want to export a dashboard for sharing externally or not. In your case I bet you don't want to export for sharing externally.

**Comment by GrishaDev** [comment]
> That's an exported dashboard. You can only import that thru the import dashboard ui, not api. Please see [http api documentation](http://docs.grafana.org/http_api/dashboard/#create-update-dashboard) for reference.
> 
> #13781, included in Grafana v5.3.4 allows you to select if you want to export a dashboard for sharing externally or not. In your case I bet you don't want to export for sharing externally.

@marefr I see, but weird how it worked before and now stopped.
If i create a dashboard from that json with import feature and then get its json via api, will it be a correct json for creating dashboard via api?

**Comment by marefr** [comment]
> If i create a dashboard from that json with import feature and then get its json via api, will it be a correct json for creating dashboard via api?

Yes, but please note that the api returns a json model with properties `dashboard` and `meta`, but when creating/updating a dashboard you'll provide json model with properties `dashboard`, `folderId`, `overwrite`.

**Comment by GrishaDev** [comment]
> > If i create a dashboard from that json with import feature and then get its json via api, will it be a correct json for creating dashboard via api?
> 
> Yes, but please note that the api returns a json model with properties `dashboard` and `meta`, but when creating/updating a dashboard you'll provide json model with properties `dashboard`, `folderId`, `overwrite`.

@marefr  thanks! Also what about the ram usage is that normal to slowly consume the entire ram or is it some issue?

**Comment by marefr** [comment]
If you mean on Grafana server that's not normal, please open a new issue for that so that we can investigate. If you mean in the browser we've had some memory leaks that should be improved a lot in Grafana v5.4.0.
