### ISSUE TITLE
Docs - performance page points at wrong code

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1407]
This page - http://grafana.org/docs/performance/

references:
https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/views.py, and render/attime.py with https://github.com/graphite-project/graphite-web/blob/0.9.x/webapp/graphite/render/attime.py

If you do that with graphite 0.9.12 (from epel in my case) then it breaks. Using this view.py works properly:
https://github.com/gingerlime/graphite-web/blob/5b1015df91b7740a96299594a3a1727238517c20/webapp/graphite/render/views.py

Discussion here:
https://github.com/graphite-project/graphite-web/pull/334

Scott

**Comment by torkelo** [comment]
Updated performance page
