### ISSUE TITLE
grafana-cli admin password reset should get the password from stdin

### ISSUE THREAD

**Issue by vinicyusmacedo** [grafana/grafana#14076]
### What Grafana version are you using?
Grafana 1.14.6
### What did you do?
Tried to reset the admin password from the grafana-cli.

`grafana-cli admin reset-admin-password myeasypassword`

The admin password is being set on a command line [argument](https://github.com/grafana/grafana/blob/b47a4954c9b0208869298c75e97c212430565f1e/pkg/cmd/grafana-cli/commands/reset_password_command.go#L16). This command might be saved on bash history and it can be a security issue. 

We could instead get the password from stdin.

**Comment by praveensastry** [comment]
@bergquist i would like to pick this up

**Comment by didib** [comment]
It can also be useful to be able to get the password from a file, or an environment variable - see e.g. section "Pass Phrase Options" in openssl manpage for its own methods. Both of these are more secure than directly on the command line, and might be more convenient than stdin for scripting.

**Comment by didib** [comment]
Thanks!
