### ISSUE TITLE
User field blank when adding user to folder permissions

### ISSUE THREAD

**Issue by Esity** [grafana/grafana#14087]
Grafana Version: 5.3.4
Datasource: Many but primarily InfluxDB
OS: RHEL 7
Environment Details: We have 2 Grafana nodes set up in HA behind an LTM. Both point the same MySQL server. We have SSO enable with ldap.toml. Everything works as expected.
Issue: Users name doesn't stay in folder permissions field when adding new user. Appears to be a UI issue and nothing else

Steps to recreate:
1) create new folder
2) go to folder permissions
3) search for non admin LDAP user
4) Click there name/person
5) *Issue* name shows up and disappears in field box. 
6) hit save
7) user is saved with correct permission

**Comment by torkelo** [comment]
Will be fixed in v5.4 (beta out next week)
https://github.com/grafana/grafana/pull/13563
