### ISSUE TITLE
npm run build problem

### ISSUE THREAD

**Issue by tevalabrousse** [grafana/grafana#14080]
Hi, i try to build my grafana frontend with "npm run build" but nothing change on the webpage.
When i do "npm run build", i've a error on my pannel control (see bellow).
I can have help please?

### Grafana version:
5.3.2

### OS version:
ubuntu 18.04.1 LTS

###  Result :
"NPM RUN BUILD"
### Message error:

npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/labrousse/npm-debug.log

Regards
LT

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

Make sure you are in the repo root when you run that command
