### ISSUE TITLE
Integrating AWS Cloud Watch with Grafana

### ISSUE THREAD

**Issue by axp4654** [grafana/grafana#14083]
Hello I start using Grafana as the monitoring tool for my AWS infrastructure.  I have few basic questions:
- I added graph and to identify EC2 instance I had to use InstanceID.  Is it possiible to describe EC2 instance by for example tag?  The instance id may change but the name tag will be always persistent.
- What do I need to integrate Route53 health check metrics.  I don't see my healt check if I select Instance ID.
Thank you

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Please refer to [documentation](http://docs.grafana.org/features/datasources/cloudwatch/) for further information.
