### ISSUE TITLE
Multiple Variable values query

### ISSUE THREAD

**Issue by erez-rabih** [grafana/grafana#1409]
Hi,

Assuming I have the following graphite metrics tree:

a.b.a1
a.b.b1
a.b.c1

a.c.a2
a.c.b2
a.c.c2

And I want to get as variable value [a1, b1, c1, a2, b2, c2]
I need to query for a.b.* and a.c.*
It is possible to assign multiple queries for a single variable like this?

**Comment by torkelo** [comment]
No that is currently not possible, but you might be able to issue this combined query:
``a.{b,c}.*``

Should give you variables values [a1, b1, c1, a2, b2, c2]

**Comment by erez-rabih** [comment]
Thanks a lot for the tip. I've got another question is thats ok :)
Is there a way to get all metrics recursively?
Example metric tree:
a.b.MyController1
a.b.MyController2
a.b.MyController3
a.b.Admin.ArticleController
a.b.Admin.UserController

So I need a.b.* which matches the pattern *Controller

**Comment by torkelo** [comment]
a.b.{*Controller,*.*Controller}   could work

**Comment by erez-rabih** [comment]
This query returns 0 values unfortunately...
