### ISSUE TITLE
google analytics tracking only records the path, not the full URL

### ISSUE THREAD

**Issue by cloudshapes** [grafana/grafana#14091]
- Currently, the Google Analytics tracking only records the URL path of the page visited, not the full URL (see https://github.com/grafana/grafana/blob/master/public/app/core/services/analytics.ts#L29)
- As far as I can see (see https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#location), if Grafana passed `location` instead of `page`, the full URL will be recorded to Google Analytics.
- This will be helpful if same Google Analytics ID is used across sub-domains I believe.

**Comment by marefr** [comment]
Fixed by #14092
