### ISSUE TITLE
Create global user without specifying password

### ISSUE THREAD

**Issue by supercharlesliu** [grafana/grafana#14093]
Feature Needed:
* An API to create a new user with no password
* Add user providing username & email (but no password) in the configuration UI page, which is different with creating a new user through sending an invitation email.

Why do I need this:
* As users in our company use LDAP as login method, it's pointless to create a user with a password.

**Comment by supercharlesliu** [comment]
Version 5.2.4

**Comment by supercharlesliu** [comment]
I found that I need to create a user account with the same username first, then I can login with my LDAP account.

**Comment by marefr** [comment]
@supercharlesliu You don't need to create a user account for an LDAP user since the user account will be automatically created when signing in for the first time. Do you receive an error if you don't create the user account before signing in with LDAP or what?

**Comment by supercharlesliu** [comment]
@marefr I know that LDAP can create users on the fly when they login, but We still need to create users to sign roles and permissions, it happens in the initialization process before users can login.

**Comment by marefr** [comment]
Okay. Would be quite easy for you to generate random string as password since you're already assigning roles and permissions. That was just my concern.

**Comment by supercharlesliu** [comment]
@marefr Yes, that why I changed the API in pull request #14097

**Comment by torkelo** [comment]
Closing this, as it does not seem like popular feature request and there are workarounds (just generate a random password)
