### ISSUE TITLE
Datasource config hangs with Testing... message after clicking Save & Test

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#14098]
When you click on _Save & Test_ button on datasource config page it should invoke `testDatasource()` method and show testing result. But instead, a page hangs with _Testing..._ message. This bug appears only for several datasources (confirmed for DataDog, NewRelic, Zabbix). That looks strange, but only if you don't know a real reason of this bug - race condition. This bug appears after e7f6cdc625ae680ab8e2c0da0e0599c6b39cf527 commit (`Merge branch '13739/alert-to-react'`), where alertSrv was removed and notifications becomes triggered by app events. But in previous version bug was present and just was hiding by alertSrv. How? Let's take a look at the timeline before removing alertSrv:
1. Click _Save & Test_
1. _Testing..._ appears
1. _Datasource updated_ popup appears
1. _Datasource updated_ popup disappears after timeout
1. Test results appear
So as you can see, page update was triggered by closed popup. alertSrv is an Angular service which used `$timeout` for hiding popup:
https://github.com/grafana/grafana/commit/e7f6cdc625ae680ab8e2c0da0e0599c6b39cf527#diff-3c5b372d6884d10dab154c5dd8831ba0L79
so `$timeout()` triggered digest cycle and page update. You can ensure that that's a digest-related bug by changing any field, on the page, watched by angular (datasource name, for example) - this will trigger page update and results will appear.
Most of datasources work well, but I think it caused by short response time for `testDatasource()` promise and it hits current digest cycle. But if the response takes too much time, page would not be updated.

**Comment by torkelo** [comment]
Can you fix this by returning the promise from the function?

**Comment by alexanderzobnin** [comment]
Yes, it's a fix actually

**Comment by marefr** [comment]
Fixed by #14099
