### ISSUE TITLE
Alert out of context

### ISSUE THREAD

**Issue by holiiveira** [grafana/grafana#14101]
### What Grafana version are you using?
Grafana v5.3.4 (commit: 69630b9)
### What datasource are you using?
Elasticsearch 6.4.0
### What OS are you running grafana on?
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
### What did you do?
I created an alert with the rule: the average of the last 5 minutes is above 210000.
Unit: milliseconds (ms)
### What was the expected result?
Alert generated when rule occurs.
### What happened instead?
Some alerts are generated incorrectly, do not obey the rule.
### If related to metric query / data viz:
Alert Image: (last 5 minutes)
![alert_2](https://user-images.githubusercontent.com/4368491/48615822-12c4c480-e979-11e8-924d-4937dbfae921.jpg)

Rule Image:
![conditions](https://user-images.githubusercontent.com/4368491/48615199-5dddd800-e977-11e8-8e8b-a952aab88203.PNG)

Is this a bug or something wrong?

**Comment by torkelo** [comment]
Make sure you query date histogram interval and options are correct for this short time range , check alert rule test results etc.

If your problem continues to be unexplained include full ES query and results

**Comment by holiiveira** [comment]
Apparently the problem was because the ES (GMT -2) was with the time zone different from Grafana (UTC), I left both the same and did not give more problems.
