### ISSUE TITLE
Warn user when no config.js found

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1410]
On a fresh installation of Grafana there is no config.js. If the user forgets to create it and tries to load grafana they get a partial grafana interface but that just looks 'broken'. 

For new users this could be the point at which they give up. For more experienced users, it could save them some head scratching (ahem :blush: )

For better usability it would be good to display a warning to the user that the file is missing.

**Comment by scharissis** [comment]
If it makes you feel better, I too fumbled with this for a while! :)

But, FYI, Torkel's working on Grafana 2.0 in the 'develop' branch and its HEAD commit does not exhibit this issue.

**Comment by torkelo** [comment]
well if you use the backend in Grafana 2.0 there is no config.js (it is sort of generated and inserted in the the index.html)
