### ISSUE TITLE
Enable use of InfluxDB series alias in graph title

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1411]
When using InfluxDB as source, it'd be nice to be able to title a graph using the same $ notation as is supported for a metric's alias.

**Comment by torkelo** [comment]
Interesting idea, but if there are many series? 

It would be possible to use some other syntax (db source agnostic), to have the title depend on the series names in the graph. 

for example: title: $graphSeries[0]    would be replaced with the first series name, or $graphSeries would be a comma separated title with all series names.

**Comment by rmoff** [comment]
I guess in my use case all the series would be derived from the same parent that I wanted to use in the title, so taking the first series alone and applying the $ segment notation to it would suffice. 

So for example, I have a bunch of series of OS data:
```
monitoring-01.moffatt.me.os.cputotals.idle
monitoring-01.moffatt.me.os.cputotals.irq
monitoring-01.moffatt.me.os.cputotals.nice
monitoring-01.moffatt.me.os.cputotals.soft
monitoring-01.moffatt.me.os.cputotals.steal
monitoring-01.moffatt.me.os.cputotals.sys
monitoring-01.moffatt.me.os.cputotals.user
```
And I'd like to put "cputotals" in the title - in this case you could take $3 from the first series (or indeed any of them) for the same result. I know 'cputotals' isn't the longest thing to type but in my usecase I have several other much longer metric series names where typing out the title is a PITA

Your idea, if I understand it right, of `$graphSeries[0]` would be great, so long as I could then do `$graphSeries[0][3]`, for example

**Comment by torkelo** [comment]
@rmoff no that would not be possible the full series name is lost after the alias pattern is applied and is no longer available when the panel receives the series. This would require a change to the influxdb aliasing code (so it returns the full series name as well) and data contract returned by the data sources so the alias and the full series name is returned. Possible but not something I will implement unless there are a lot of +1 votes on this issue.

**Comment by rmoff** [comment]
@torkelo OK, thanks anyway.
