### ISSUE TITLE
Time of max/min point in singlestat panel

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#14112]
There is "Time of last point" option in singlestat panel. Could you also add Time of max and min point? ;)

**Comment by marefr** [comment]
Depending on what datasource/tsdb you're using it can already be supported since a lot of tsdb's supports min and max aggregation which should enable you to use the time of last point. What datasource are you using?

**Comment by szerwi** [comment]
I use influxdb but this way is not working. It shows wrong time.

**Comment by marefr** [comment]
Understood

**Comment by szerwi** [comment]
![1](https://user-images.githubusercontent.com/19311511/48722473-64dd4280-ec24-11e8-9c04-0d559cb59b98.PNG)
![2](https://user-images.githubusercontent.com/19311511/48722475-64dd4280-ec24-11e8-8d61-9c82a914ea77.PNG)

I should show 2018-10-17 14:00:00. When I switch to min value in Influxdb, the date is the same. When I choose min or max value  in "Options" tab it shows correct value. Just the time of last point is not working correctly.

**Comment by tecmatia-dp** [comment]
I think the support for this data would be good. 
But szerwi, I think that if you remove the "GROUP BY time" clause, you would get what you want.

**Comment by szerwi** [comment]
> I think the support for this data would be good.
> But szerwi, I think that if you remove the "GROUP BY time" clause, you would get what you want.

It's working, thank you! :)

**Comment by marefr** [comment]
Closing this then
