### ISSUE TITLE
Graph rendering errors after 5.3.4 upgrade

### ISSUE THREAD

**Issue by kerneljack** [grafana/grafana#14128]
Hi, we have been successfully using the external S3 based image storage for more than a year now to upload alert graphs. However, with the new 5.3.4 version, we sometimes get images with the following words in them: “Concurrent server side render limit reached”. This might be an error from Graphite, I am not sure yet. I have attached a screenshot.

The logs actually show that the image was successfully uploaded, but when you actually go and view the image, it’s just a picture with those words in it.

I have posted this on the community as well, however I wasn't sure if that's the right place for it. If you'd like me to delete the community post, let me know and I can do that, thanks.

### What Grafana version are you using?
5.3.4

### What datasource are you using?
We have lots - Graphite, Prometheus, AWS, Stackdriver, MySQL

### What OS are you running grafana on?
Docker container (Docker version 17.03.1-ce, build c6d412e)
OS: Ubuntu 16.04 

<img width="574" alt="screen shot 2018-11-17 at 23 43 10" src="https://user-images.githubusercontent.com/927623/48721756-702b7080-ec1a-11e8-91a3-5353c2a1d590.png">

**Comment by torkelo** [comment]
How many alert rules do you have? And when you see this are many alert rules firing at the same time? There is a limit now with how many server side renderings can be processed at the same time, so many alert rules fire at the same time we skip rendering and send an alert notification without the real image. Otherwise Grafana would have to wait a long time to render all images.

**Comment by kerneljack** [comment]
Ah that makes a lot of sense, thanks! We do have a large number of alert rules indeed. Is there a recommended way to proceed here? Can we bump up the number of concurrently allowed server side renderings for our use case? It used to work just fine with version 5.2.

```
mysql> select max(id) from alert;
+---------+
| max(id) |
+---------+
|    4983 |
+---------+
1 row in set (0.00 sec)
```

**Comment by kerneljack** [comment]
BTW, we have also enabled "Reminders" for the alerts - could that be causing us additional issues in this case?

**Comment by torkelo** [comment]
You can increase the concurrent render limits:
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L480

**Comment by kerneljack** [comment]
@torkelo thank you! I shall try that :-)

**Comment by kerneljack** [comment]
@torkelo I have now bumped this several times, it's now at 45 and we are still occasionally seeing the problem.

**Comment by mariaelinger** [comment]
Hi,
Do you have a recommended value for this parameter?
Thanks
