### ISSUE TITLE
Enable web proxy caching by tweaking $timeFilter and "now()"

### ISSUE THREAD

**Issue by baze-** [grafana/grafana#1412]
Hi,
Caching http queries between Grafana and InfluxDB would make Grafana **more scalable** for bigger user base and it would make **slow queries more usable** as most of the queries would be returned directly from cache.

If the following changes would be done to Grafana web proxy could be use used to speed things up:
1) **$timeFilter** would be be rounded to nearest day.
2) **now()** would be evaluated in client side and rounded up to nearest day.

After these modifications Grafana would generate queries that are reentrant and **time filter** would request **exact time windows** which would make them hit the web cache.

Ofcourse this means that Grafana will get "more data" from server than it requested, but Grafana can already discard those extra values while drawing the graph.

Cache could be implemented with 3rd party solutions like Nginx, Apache web, Squid or Varnish.

**Comment by torkelo** [comment]
I think it would be better to let InfluxDB implement a cache feature, like Graphite has support for memcache servers for this purpose.
