### ISSUE TITLE
Need a panel for table view for influxDB

### ISSUE THREAD

**Issue by karthikrev** [grafana/grafana#1413]
This is a feature request.  Have you see influxdb Admin page ? Run a query you will be able to see table and graph. 
   Can we have a table panel in (src/app/panels)?

**Comment by steverweber** [comment]
++++1

**Comment by steverweber** [comment]
https://github.com/grafana/grafana/issues/215

**Comment by torkelo** [comment]
There is already a request for a table panel, this will be the next panel to be implemented. Just need to finish up the backend features for Grafana 2.0 then more panels will come.

**Comment by torkelo** [comment]
Will close this as there is already a feature request for this, #215
