### ISSUE TITLE
Grafana bar graph panel

### ISSUE THREAD

**Issue by piyushpatil90** [grafana/grafana#14136]
Hi,

I am not able to show count on the bar graph is there any way to show numbers on each bar in graph panel.
I am using 5.2.4 version of grafana
Datasource: Elasticsearch

Thanks in advance.

**Comment by Ijin08** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

In Grafana's Bar Graph you can only show count in the legend.
