### ISSUE TITLE
Incorrect API documentation for “pause all alerts”

### ISSUE THREAD

**Issue by acdha** [grafana/grafana#14133]
The documentation suggests that token authentication is supported for pausing all alerts:

http://docs.grafana.org/http_api/alerting/#pause-all-alerts

Using v5.3.2 in curl I can see the the `Authorization: Bearer` header being sent but it will always get an HTTP 403. If I change the command to replace `-H "Authorization: Bearer $(cat grafana.key)"` with `--user "admin:$(cat grafana.password)"` the same command works.

**Comment by danielbh** [comment]
I can do this one.
