### ISSUE TITLE
Y axis rounding values to integers

### ISSUE THREAD

**Issue by irazinkov** [grafana/grafana#14141]
Running:
Grafana 5.3.4
Datasource: elasticsearch
Ubuntu 16.04.3
Trying to plot Temperature values that are logged in Kibana as floats, but they are being rounded to integers in Grafana.

![screen shot 2018-11-20 at 9 52 08 am](https://user-images.githubusercontent.com/11527799/48792902-4a4dac80-ecaa-11e8-8eb3-118d1ab7e5d9.png)
![screen shot 2018-11-20 at 9 19 22 am](https://user-images.githubusercontent.com/11527799/48792909-4f126080-ecaa-11e8-8e77-174e4bdeb860.png)

This happens randomly and for all variables being plotted on grafana (i have 20 different dashboards).

**Comment by torkelo** [comment]
Please open panel in Edit mode and metrics tab, click query inspector, it Will show ES query and response

**Comment by irazinkov** [comment]
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/1/_msearch"
data:"{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["bioreactor-2018.11.20"],"max_concurrent_shard_requests":256} {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1542738576573","lte":"1542742176573","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"beat.name: \"BioReactor-105\" AND extra.monitor_value_name:\"Temperature_BR1\""}}]}},"aggs":{"2":{"date_histogram":{"interval":"2s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1542738576573","max":"1542742176573"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"extra.measurement"}}}}}} "
response:Object
responses:Array[1]
0:Object

**Comment by irazinkov** [comment]
The rest is too long to post...how would you like me to do it?

**Comment by irazinkov** [comment]
Looks like the issue is resolved for now.

It seems that for whatever reason, when the indexes would turn over in Kibana and if the new variable value happens to be an integer, then for the rest of the index it will convert all coming in values to integers.
The way to fix it is to force the value to read as a decimal in Kibana. Please see attached screen shot.

Thank you for your help.

<img width="370" alt="screen shot 2018-11-26 at 9 51 44 am" src="https://user-images.githubusercontent.com/11527799/49032269-0141a080-f161-11e8-965c-8e0f716308e8.png">
