### ISSUE TITLE
singlestat coloring doesn't like '0' value norms?

### ISSUE THREAD

**Issue by christrotter** [grafana/grafana#1414]
We have a number of queue metrics that are usually 0.  The singlestat panel is grumpy about this, and displays its irritation by refusing to allow the 'coloring' feature to work.

![image](https://cloud.githubusercontent.com/assets/8292406/6002972/c071e7b2-aac5-11e4-9637-a0f34e273980.png)

The settings for that white singlestat...
![image](https://cloud.githubusercontent.com/assets/8292406/6002979/d3313ba0-aac5-11e4-9910-5d2b73d67ae1.png)

So it should be green if the value is zero.  We tried another metric, same behaviour.  Maybe we're doing something wrong?

Edit: Oh yeah, and I tried using the value modifiers (i.e. change 0 -> 1), but no dice.

**Comment by torkelo** [comment]
what version are you using? this was fixed https://github.com/grafana/grafana/pull/1140

**Comment by christrotter** [comment]
I'm using 1.9.0.  I'll update and report back if the issue persists.  Sorry!

**Comment by christrotter** [comment]
Definitely working now!  Lesson learned, sorry about that.

**Comment by torkelo** [comment]
@christrotter no problem!
