### ISSUE TITLE
Empty space below graphpanel when legend is not shown

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#14142]
There is empty space below graph panels even if the legend is not shown

grafana version: nightly
![gr](https://user-images.githubusercontent.com/291750/48832884-7cc6da80-ed7a-11e8-9f6b-311e62952d34.png)

**Comment by torkelo** [comment]
what browser and OS are you using?

**Comment by roidelapluie** [comment]
Firefox 62 and Linux

Indeed not reproducible on chrome

**Comment by roidelapluie** [comment]
Grafana v5.3.0-pre1 (8009bc3) was not impacted

**Comment by Ijin08** [comment]
What nightly are you using? Asking because we found a different bug in nightly where one can't hide the legend at all.

**Comment by torkelo** [comment]
Strange, can't replicate with Firefox 63 on Linux at least.

**Comment by marefr** [comment]
Testing this after #14144 was merged to master. Now legend is properly hidden even when graph has no data. However compared to v5.3.3 having a graph with no data and a visible legend takes up a few pixels more than when hidden (both firefox and chrome). 

Now in master having a graph with no data and a visible legend takes up 41 pixels (firefox) and zero pixels in chrome.

**Comment by marefr** [comment]
@roidelapluie thanks. Closing this
