### ISSUE TITLE
Max/Min values

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1415]
Torkel,

I am looking at max cpu for the last month and last week for a server. They are different, how is that possible? Is there any data smoothing taken place to display max values using graphite, just curious.

thanks,

**Comment by torkelo** [comment]
What consolidation function have selected? The default consolidation function in graphite is average. 

Try adding the function: consolidateBy(max)  

When Grafana requests metrics from graphite it only requests points for the number of pixels wide the graph is, if there are more (and there can be hundreds of thousands), graphite will need to reduce that number to the number requests (graph width in pixels). The same happens for the Graphite PNG rendering. There is help docs in the grafana metrics editor for this, click the "max data points" help link in the metrics editor tab for more info.

**Comment by gsaray101** [comment]
I am using the default values as is. When I do table, min max, avg. Then I do see max values different for monthly and weekly, it should be the same?

**Comment by torkelo** [comment]
yes, if you have consolidateBy(max) in your graphite query, otherwise the max value in the legend table will not be correct

**Comment by gsaray101** [comment]
what max values grafana is reporting?

**Comment by torkelo** [comment]
the max of the values returned from graphite. Graphite does not return series summary data (min, max, avg, total) etc (There is an open issue for this in graphite-web). 

So grafana has to calculate those values client side. But those values will not always be correct (except avg if you havent changed consolidateBy). So you cannot trust Total and Max and Min unless you specify a consolidateBy function in the graphite query, and you cannot have Max & Min always be correct at the same time. 

To solve this grafana would have to request all the data for the time period which could be mega bytes of measurements, which would hang the browser. So it has to be solved on the graphite side.
