### ISSUE TITLE
Explore: labels not propagated between views

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#14158]
![w346vlstbm](https://user-images.githubusercontent.com/444037/48900563-9cc5cf00-ee4a-11e8-82db-45884d0501fb.gif)

**Comment by davkal** [comment]
It does a check if the target datasource supports the labels and drops them otherwise. Perhaps something goes wrong there. Investigating...

**Comment by tomwilkie** [comment]
Ah yes this was when labels was returning an error. Perhaps in that case it
shouldn’t? And the error should probably be displayed somewhere in the UI.

**Comment by davkal** [comment]
Good point, will look for that.
