### ISSUE TITLE
Request to include AWS/CodeBuild namespace for Cloudwatch Datasource

### ISSUE THREAD

**Issue by spezam** [grafana/grafana#14167]
**Feature request**

Please include this information:
What Grafana version are you using?
[Ans] Version 5.2.4
What datasource are you using?
[Ans] Cloudwatch
What OS are you running grafana on?
[Ans] Ubuntu

**Request**: Please include the AWS/CodeBuild namespace

Thanks,
Matteo

**Comment by marefr** [comment]
Fixed by #14238
