### ISSUE TITLE
Annotation Icon missing

### ISSUE THREAD

**Issue by phagedorn** [grafana/grafana#1416]
Annotation Icon is missing in latest master

Or is something wrong with my event or annoation settings ?

Grafana example with graphite event:

![grafana-annotation-no-arrow](https://cloud.githubusercontent.com/assets/1391548/6006324/e811ead2-ab11-11e4-87b4-b10042f8c19c.png)

Graphite event :
![graphite-event](https://cloud.githubusercontent.com/assets/1391548/6006429/ab8f0814-ab12-11e4-878e-947c3dd86e32.png)

**Comment by torkelo** [comment]
thanks for reporting this, will fix asap

**Comment by phagedorn** [comment]
:+1:  Thanks a lot :)

**Comment by phagedorn** [comment]
Wow, that was fast :+1:  Thanks a lot
