### ISSUE TITLE
Trend line

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1417]
Hi Torkel,

What function you could use to simulate statistical linear line in grafana/graphite install?

**Comment by dbrgn** [comment]
Good question :)

**Comment by torkelo** [comment]
dont know

**Comment by torkelo** [comment]
would have top be done in graphite before point consolidation

**Comment by 5lava** [comment]
@torkelo Was this feature implemented? Just wondering why is this issue closed.

**Comment by StyXman** [comment]
Dup'ed in #7812.
