### ISSUE TITLE
ldap login issue

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14173]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by marefr** [comment]
What ldap login issue. Please include details about what problem you have. Thanks

**Comment by Siddhu1096** [comment]
t=2018-11-23T06:49:00-0600 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2018-11-23T06:49:00-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=10.96.19.172 time_ms=87 size=42 referer=http://10.96.26.54:3000/login

**This is the error I am getting if I enter my username and password**
Here goes my **ldap.toml** file

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host =  "ldap host"
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if ldap server supports TLS
use_ssl = false
# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false
# set to the path to your root CA certificate or leave unset to use system defaults
#root_ca_cert = ""
# Authentication against LDAP servers requiring client certificates
#client_cert = ""
#client_key = ""

# Search user bind dn
bind_dn = "CN=svc_wikijs_reader,OU=service accounts,DC=asd,DC=com"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = 'idk'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(cn=%s)"

# An array of base dns to search through
search_base_dns = ["dc=asd,dc=com"]

There goes my **grafana.ini** file

[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
;allow_sign_up = false

**Comment by Siddhu1096** [comment]
@marefr  Could you please find why I am getting this bug?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

There are a lot of existing topics regarding ldap in community site. Also see [documentation](http://docs.grafana.org/installation/ldap/#ldap-authentication) if you haven't already.

**Comment by Siddhu1096** [comment]
I couldn't find in that. That's why I came here

**Comment by Siddhu1096** [comment]
When I enable that, **Job for grafana-server.service failed because the control process exited with error code. See "systemctl status grafana-server.service" and "journalctl -xe" for details.** This error pops up

**Comment by marefr** [comment]
What? Please make sure that you only have one `[log]` section in grafana.ini.

**Comment by marefr** [comment]
Doesn't look like you've enabled debug logging. What you can try is to edit the [log] section and change `level = info` to `level = debug`. 

If you navigate to `http://<grafana host>/admin/settings` is ldap enabled and show similar settings like this?

![image](https://user-images.githubusercontent.com/1668778/49084324-6a074680-f24f-11e8-81bc-df7d48b44931.png)

**Comment by Siddhu1096** [comment]
Yes, I can see that.. Its the same as above, I've configured

**Comment by Siddhu1096** [comment]
t=2018-11-27T08:47:57-0600 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2018-11-27T08:47:57-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=10.96.19.162 time_ms=85 size=42 referer=http://10.96.26.43:3000/login
t=2018-11-27T08:47:58-0600 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0

**Comment by marefr** [comment]
And how about your logging config? 

![image](https://user-images.githubusercontent.com/1668778/49089725-747c0d00-f25c-11e8-8fa7-d89e68adb044.png)

Please try and enable debug logging, try and login again. Please note that you'll need to restart Grafana when configuration changes have been made.

**Comment by Siddhu1096** [comment]
It should be like that as above?

**Comment by Siddhu1096** [comment]
![log](https://user-images.githubusercontent.com/22325249/49090084-f848f000-f282-11e8-877b-8f82461f0016.PNG)

**Comment by marefr** [comment]
> Yes, I can see that.. Its the same as above, I've configured

You'll need to make sure that ldap is enabled - doesn't like that based on your log files. 

```ini
[auth.ldap]
enabled = true
```

**Comment by Siddhu1096** [comment]
![ldap](https://user-images.githubusercontent.com/22325249/49090676-30046780-f284-11e8-877c-3f783bc7c754.PNG)


I've already done that,..

**Comment by marefr** [comment]
Okay good. If you look at your grafana server log file when Grafana starts up, it should have a line similar to:

```log
INFO[11-27|16:05:21] Ldap enabled, reading config file        logger=ldap file=conf/ldap_dev.toml
```

**Comment by Siddhu1096** [comment]
Yes.. I can see that
![ldap1](https://user-images.githubusercontent.com/22325249/49092354-dc941880-f287-11e8-92e1-62b8105c256d.PNG)

**Comment by marefr** [comment]
When I successfully login using LDAP I get only the following log (debug enabled):

```
DBUG[11-27|16:43:06] Ldap User found logger=ldap info="(*login.LdapUserInfo)(0xc00038a850)({\n DN: (string) (len=41) \"cn=ldap-editor,ou=users,dc=grafana,dc=org\",\n FirstName: (string) \"\",\n LastName: (string) (len=11) \"ldap-editor\",\n Username: (string) (len=11) \"ldap-editor\",\n Email: (string) \"\",\n MemberOf: ([]string) (len=1 cap=1) {\n  (string) (len=38) \"cn=editors,ou=groups,dc=grafana,dc=org\"\n }\n})\n"
```

So I'm out of clues with your setup. What Grafana version are you using? How are you running Grafana, ubuntu/debian, centos/redhat or docker?

**Comment by Siddhu1096** [comment]
centos/redhat

**Comment by marefr** [comment]
And Grafana version?

**Comment by Siddhu1096** [comment]
5.3.1

**Comment by marefr** [comment]
Please send me your full grafana configuration file and ldap.toml and we'll take it from there. You can email me mefraimsson (at) grafana.com

**Comment by Siddhu1096** [comment]
There's some restriction for us to send it to your mail id.. Can i attach it here?

**Comment by Siddhu1096** [comment]
[grafana_ini.docx](https://github.com/grafana/grafana/files/2620885/grafana_ini.docx)

**Comment by Siddhu1096** [comment]
Done!!
Thank you so much for this support. Means a lot! :)

**Comment by Siddhu1096** [comment]
Any updates @marefr

**Comment by marefr** [comment]
The files you attached looks correct as far as I'm concern. 

You could try and disable brute force login protection, but I'm not sure that's the problem. Given you haven't tried to login since yesterday you should see a ldap debug log message when signing in now.

```ini
[security] 
disable_brute_force_login_protection = true
```

**Comment by Siddhu1096** [comment]
Yes..I'll try that now..

**Comment by Siddhu1096** [comment]
Tried.. Still the same error..

**Comment by marefr** [comment]
Do you already have a user in your Grafana database with the same username as ldap user you're trying to login with?

**Comment by Siddhu1096** [comment]
Nop. I dont..

**Comment by marefr** [comment]
Sorry but I'm out of clues. Since I have no access to your environment I would recommend you to build Grafana from source, configure LDAP on your local computer and debug what's going on.

**Comment by marefr** [comment]
You've already [built from source](http://docs.grafana.org/project/building_from_source/) and created package for redhat? You haven't installed using [official repository](http://docs.grafana.org/installation/rpm/#install-stable)?

**Comment by Siddhu1096** [comment]
Oh wait, sorry. I have installed through official repository.

**Comment by Siddhu1096** [comment]
Yes, Pardon for that. I was installed through official repo, not from the source. 
So, are you suggesting me to install and do it from scratch? We can't resolve this by repo method?

**Comment by marefr** [comment]
On second thought hopefully not needed to build from source. Looking at the code this must be a misconfiguration of your `search_base_dns`. I can see that you have multiple `DC=local` in your `search_base_dns` for example.

* What kind of LDAP server and version are you using?
* Does it make any difference if you change `search_base_dns = ["CN=APP-access,OU=EmailGroups,DC=local"]`?
* Does it make any difference if you change CN, OU, DC to lower case in `search_base_dns` and `bind_dn`?
* Can you use ldapsearch or similar tool to search for "CN=APP-access,OU=EmailGroups,DC=local,DC=local" and/or lookup your user you're trying to login with?

Example using ldapsearch: `ldapsearch CN=APP-access | grep ^member`

**Comment by Siddhu1096** [comment]
Currently we are using 6.1.7601.17514  Version for our AD which is working on windows 2018 R2 platform..
And we have tested our ldap in https://www.ldapadministrator.com/download.htm this software. And it works perfectly there.

**Comment by marefr** [comment]
Oh active directory - then you should probably follow this example configuration: http://docs.grafana.org/auth/ldap/#active-directory

**Comment by Siddhu1096** [comment]
Hey, So I followed according to that configuration and I got an ldap error now.

t=2018-11-29T05:11:56-0600 lvl=info msg="Initial bind failed" logger=ldap error="LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580"

**Comment by marefr** [comment]
Please include your new ldap.toml. Not sure if there may be ssl related, but please try `enable_ssl = false` and `port = 389`.

**Comment by marefr** [comment]
But the error message you get tells that you've invalid credentials. Do you have some special character in the password, for example # or ;?

**Comment by Siddhu1096** [comment]
Yea, exactly.

**Comment by marefr** [comment]
I'm sorry but I can't help you more. Please try and change your password to something simpler to start with and/or try and login with some other test account just to verify your configuration works as expected.

**Comment by marefr** [comment]
Great. May I ask how you solved it?

**Comment by rahuldevopsengg** [comment]
> Hey! @marefr I resolved the issue...!
> Thanks for your time!! You did a great support!

Hi Siddhu,

I'm getting same issue for LDAP authentication and using active directory credentials. Please can you help me out.

regards,
Rahul

**Comment by Siddhu1096** [comment]
What's the issue you're getting? Can you paste it here?

**Comment by Sreedharredd** [comment]
HI Siddhu,

Iam getting below error while logging in to grafana. Getting below error.

EROR[01-31|11:07:14] Cannot authentificate admin user in LDAP logger=ldap error="unable to read LDAP response packet: unexpected EOF"
EROR[01-31|11:07:14] Error while trying to authenticate user  logger=context userId=0 orgId=0 uname= error="unable to read LDAP response packet: unexpected EOF"
EROR[01-31|11:07:14] Request Completed                        logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=3.202.129.29 time_ms=38 size=53 referer=http://10.242.114.9:4040/login

**Comment by Sreedharredd** [comment]
HI Siddhu,

Getting below error while logging into grafana.

EROR[01-31|11:07:14] Cannot authentificate admin user in LDAP logger=ldap error="unable to read LDAP response packet: unexpected EOF"
EROR[01-31|11:07:14] Error while trying to authenticate user  logger=context userId=0 orgId=0 uname= error="unable to read LDAP response packet: unexpected EOF"
EROR[01-31|11:07:14] Request Completed                        logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=3.202.129.29 time_ms=38 size=53 referer=http://10.242.114.9:4040/login

**Comment by Sreedharredd** [comment]
Can anyone help on my issue please.

**Comment by Siddhu1096** [comment]
@Sreedharredd Can you paste your ldap.toml configuration here?

**Comment by rht-tasinha** [comment]
Hi guys,

I am getting similar issue while searching admin user in grafana server admin portal.

Grafana logs ---

t=2020-06-29T17:48:00+0530 lvl=info msg="LDAP enabled, reading config file" logger=ldap file=/etc/grafana/ldap.toml
t=2020-06-29T17:48:04+0530 lvl=eror msg="Cannot authentificate admin user in LDAP" logger=ldap error="Invalid Username or Password"
t=2020-06-29T17:48:04+0530 lvl=eror msg="No user was found in the LDAP server(s) with that username" logger=context userId=1 orgId=1 uname=admin error="Invalid Username or Password" remote_addr=192.168.122.1
t=2020-06-29T17:48:04+0530 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/admin/ldap/admin status=404 remote_addr=192.168.122.1 time_ms=2 size=72 referer=http://192.168.122.147:3000/admin/ldap
t=2020-06-29T17:48:22+0530 lvl=eror msg="Cannot authentificate admin user in LDAP" logger=ldap error="Invalid Username or Password"
t=2020-06-29T17:48:22+0530 lvl=eror msg="No user was found in the LDAP server(s) with that username" logger=context userId=1 orgId=1 uname=admin error="Invalid Username or Password" remote_addr=192.168.122.1
t=2020-06-29T17:48:22+0530 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/admin/ldap/test1 status=404 remote_addr=192.168.122.1 time_ms=2 size=72 referer=http://192.168.122.147:3000/admin/ldap

------------------------------------------------------------

Here it is ldap.toml file for reference 

grep -v "^#" /etc/grafana/ldap.toml 

[[servers]]
host = "192.168.122.201"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false

bind_dn = "cn=admin,dc=example,dc=local"
bind_password = """123"""

search_filter = "(cn=%s)"

search_base_dns = ["dc=example,dc=local"]


[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

**Comment by rht-tasinha** [comment]
I have configured FreeIPA (LDAP) server which tries to integrate with grafana for authentication. FreeIPA is working fine

**Comment by Siddhu1096** [comment]
Have you enabled verbose logging? @rht-tasinha

**Comment by mahesh91096** [comment]
t=2020-09-28T09:44:01+0200 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="unable to read LDAP response packet: unexpected EOF"
t=2020-09-28T09:44:01+0200 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr="172.31.139.17, 172.23.29.66" time_ms=15061 size=53 referer=http://icinga-ui.prod.lgi.obo.libgbl.biz/grafana/login
t=2020-09-28T09:44:31+0200 lvl=info msg="Initial bind failed" logger=ldap error="unable to read LDAP response packet: unexpected EOF"
t=2020-09-28T09:44:31+0200 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="unable to read LDAP response packet: unexpected EOF"
t=2020-09-28T09:44:31+0200 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr="172.31.139.17, 172.23.29.65" time_ms=15014 size=53 referer=http://icinga-ui.prod.lgi.obo.libgbl.biz/grafana/login
"grafana.log" 177L, 18765C

**Comment by mahesh91096** [comment]
My ldap.toml file
# To troubleshoot and get more log info enable ldap debug logging in grafana.ini
# [log]
# filters = ldap:debug

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "10.64.126.97"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if ldap server supports TLS
use_ssl = false
# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false
#use_tls: true
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
bind_dn = "cn=ICINGA2-UI-LG-ADMIN,ou=icinga,ou=OBO,ou=svcs,dc=upc,dc=biz"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = 'admin'
#bind_password = "${LDAP_ADMIN_PASSWORD}"
# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(cn=ICINGA2-UI-*)"

# An array of base dns to search through
search_base_dns = ["dc=upc,dc=biz"]

## For Posix or LDAP setups that does not support member_of attribute you can define the below settings
## Please check grafana LDAP docs for examples
# group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
# group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]
# group_search_filter_user_attribute = "uid"

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "ICINGA2-UI-LG-ADMIN,ou=icinga,ou=OBO,ou=svcs,dc=upc,dc=biz"
org_role = "Admin"
# To make user an instance admin  (Grafana Admin) uncomment line below
# grafana_admin = true
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
group_dn = "ICINGA2-UI-LG-RO,ou=icinga,ou=OBO,ou=svcs,dc=upc,dc=biz"
org_role = "Editor"

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"

**Comment by mahesh91096** [comment]
Can anyone help me out why I'm getting this error

**Comment by Siddhu1096** [comment]
@mahesh91096 Are you using SSL certificate? By default LDAP port is 389.

**Comment by Shravanannavajjala-gep** [comment]
Hi @Siddhu1096,

Even im facing same issue. Could you help me out in this?

**Comment by nicholaswebber** [comment]
I ran into this exact issue today and it turned out my password had expired.  Some of our systems use Azure (online and slower to update) while others use Active Directory (on-prem and up to date), so my attempts to verify credentials weren't sufficient to highlight the issue.

**Comment by deminart** [comment]
With these settings, Active Directory authorization finally took off.

/etc/grafana/ldap.toml

[[servers]]
host = "domain.name"
port = 389
use_ssl = false
start_tls = false
tls_ciphers = []
min_tls_version = ""
ssl_skip_verify = false
bind_dn = "DOMAIN\\%s"
timeout = 10
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["DC=domain,DC=name"]
[servers.attributes]
username  = "sAMAccountName"
name      = "givenName"
surname   = "sn"
email     = "mail"
member_of = "memberOf"
[[servers.group_mappings]]
group_dn = "CN=grafana-adm,OU=Share Groups,DC=domain,DC=name"
org_role = "Admin"
grafana_admin = true
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

/etc/grafana/grafana.ini
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
