### ISSUE TITLE
Problem with scrollbar in "switch organization" in Windows 10

### ISSUE THREAD

**Issue by tammytankian** [grafana/grafana#14181]
Please include this information:
### What did you do? 

In my machine with win 7 works fine, but in my machine with windows 10, doesnt matter the browser, everytime  I try to change the Org. only shows the first 6 orgs and top of 7th one and the scroll bar disapears D:

![image](https://user-images.githubusercontent.com/27218076/48982712-e7eb1680-f0c4-11e8-8112-8c4f6ba38778.png)

I have 40 organizations

**Comment by marefr** [comment]
Have tried with Microsoft Edge 42.17134.1.0 on WIndows 10 and it works as expected. The scroll bar only shows when mouse is over scrollarea (upper right of modal window) and when you scroll (drag and/or mouse wheel). 

Closing this, but will consider reopen if I misunderstood something.

**Comment by tammytankian** [comment]
Hi

I tried putting the mouse everywhere in that area. No success
And yes, I also tried in edge.

But my tests were with mousepad. All of them. You think that was the issue?

**Comment by marefr** [comment]
Just noticed I tested on Windows using Grafana v.5.4.0-pre1. However tried on our demo site (v5.3.4) using Ubunut and Chrome now and it works as expected using mouse and my touchpad on laptop:

![image](https://user-images.githubusercontent.com/1668778/49071190-b8a3e900-f22d-11e8-9993-657d1557afe7.png)

What exactly do you mean by mousepad?
