### ISSUE TITLE
Dashboard originated from 4.6 version display panel in the wrong place when using 5.x version

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#14185]
I'm using the docker version 5.3.4 but I verified the problem exists also in older 5.x versions.
OS: fedora 28

My dashboard was originally set for 4.6 and uses raws.
If possible I would like to remind 4.6 compatible for users that are still using older version of grafana.

The way we work, is we use the API to upload the dashboards.

what happens is that grafna takes one panel and places it randomly in a different place.

When working on the transition, I've notice that Grafana 5.x does not behave correctly when a row spans more than 12, so I've made sure to change that.

On 4.6
![image](https://user-images.githubusercontent.com/2118079/49005370-37861c80-f16f-11e8-849c-18adf7219ccc.png)
Notice the dashboards panel at the upper left.

On 5.3.4 it looks like that:
![image](https://user-images.githubusercontent.com/2118079/49005255-eece6380-f16e-11e8-8e9f-9467e9413b8e.png)

The "reads with no misses" panel hides the panel below. It's nos suppose to be there, it moved randomly from where it was supposed to be placed a few rows down.

I had to rename the dashboard file from json to txt so git would accept it.
[scylla-dash-per-server.master.txt](https://github.com/grafana/grafana/files/2614834/scylla-dash-per-server.master.txt)

I would be happy with a workaround.

**Comment by torkelo** [comment]
99% of 4.6 dashboard migrante to the new grid layout with minimal visible difference. Looks like you hit and edge case. No similar report so not sure what is unique about your dashboard.

The dashboard json you pasted looks strange, is that from before or after the upgrade from 4.6? It contains both parts of a v5 dashboard and v4.6 (it contains rows which make it a v4.6 dashboard)

**Comment by amnonh** [comment]
The only difference I made from the 4.6 version was the place the logo line not in a row (because of a different bug I was hitting that add a slider to it).

I don't know why you close the bug, it's definitely a bug, grafana places a panel in an arbitrary place.

**Comment by torkelo** [comment]
Can you paste the json before v5 migration?

**Comment by amnonh** [comment]
[scylla-dash-per-server.master.txt](https://github.com/grafana/grafana/files/2615418/scylla-dash-per-server.master.txt)

That's the original that looks fine on 4.6.

Regardless of any other issue grafana should not place one panel on top of another

**Comment by torkelo** [comment]
Can't replicate this, tried to import that and this is the layout i get

<img width="1280" alt="screen shot 2018-11-26 at 13 37 59" src="https://user-images.githubusercontent.com/10999/49014470-88ead780-f180-11e8-8b4f-87049a714ab8.png">

**Comment by amnonh** [comment]
note that in this case the  upper row with the scylla logo has an unwanted vertical scrawler.
Grafana will not respect a position object when added to the panel inside the row, that's why I moved it out of the rows hirarchy

**Comment by amnonh** [comment]
what Grafana version are you using?
