### ISSUE TITLE
Clickjacking security issue: Missing X-Frame-Options header

### ISSUE THREAD

**Issue by vonox7** [grafana/grafana#14189]
Grafana does not set the `X-Frame-Options` header, which makes it vulnerable to [clickjacking](https://www.owasp.org/index.php/Clickjacking).

We run a bug hunting program, and got reported this issue. Clickjacking is considered not as bad practice, but as security issue, see the same issue on [yelp](https://hackerone.com/reports/49888) or [mail.ru](https://hackerone.com/reports/261652)

Affected Grafana versions: all, see https://securityheaders.com/?q=https%3A%2F%2Fplay.grafana.org.

### Vulnerability Description

Clickjacking (User Interface redress attack, UI redress attack, UI redressing) is a malicious technique of tricking a Web user into clicking on something different from what the user perceives they are clicking on, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous web pages.

The server didn't return an X-Frame-Options header which means that this website could be at risk of a clickjacking attack. The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a <frame> or <iframe>. Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites.
This vulnerability affects Web Server.

### Steps to reproduce the vulnerability
Create a simple html file with the following content and open it in a browser:
```
<html>
 <head>
  <title>Clickjack test page</title>
 </head>
 <body>
  <p>Website is vulnerable to clickjacking!</p>
  <iframe src="https://play.grafana.org" width="1500" height="1000"></iframe>
 </body>
</html>

```

**Comment by xlson** [comment]
@torkelo seems to me like something we might want to lock down, but perhaps make configurable so that users that embed Grafana can choose to do so?

**Comment by bergquist** [comment]
Sounds like a good solution.

**Comment by marefr** [comment]
[X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) seems to be quite poorly supported, see [caniuse](https://caniuse.com/#search=x-frame-options).

Should consider also supporting configuration of [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) and/or specifically [frame-ancestors policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors). Browser support is also kind of poor here, see [caniuse](https://caniuse.com/#search=content%20security), so a mix of both may be needed.

**Comment by bergquist** [comment]
Didnt know about `frame-ancestors` but it seems like a good idea :)

**Comment by dean9** [comment]
The fix does not seem to be functional currently.  I am getting responses with header "X-Frame-Options: deny" regardless of the "allow_embedding" configuration.

I've tested this on Safari and Firefox.  Could someone please try to reproduce?

**Comment by marefr** [comment]
@dean9 just verified it works as expected in current master branch. Have heard no other reports this doesn't work. Make sure you use at least v6.2 and you have configured it correctly under correct section, see https://grafana.com/docs/grafana/latest/installation/configuration/#allow-embedding. If you still think this is a bug please open a new bug report.
