### ISSUE TITLE
Elasticsearch query editor broken

### ISSUE THREAD

**Issue by ldktta** [grafana/grafana#14191]
Please include this information:
### What Grafana version are you using?
Grafana v5.4.0-pre1 (efcbb92)
### What datasource are you using?
ElasticSeach 6.4.2
### What OS are you running grafana on?
Red Hat Enterprise Linux Server release 7.2 (Maipo)
### What happened instead?
![image](https://user-images.githubusercontent.com/14881332/49014428-dfdfb500-f15e-11e8-9c67-4aa9a532b282.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

![image](https://user-images.githubusercontent.com/14881332/49014471-01d93780-f15f-11e8-9fc2-ce4257ad07cc.png)

**Comment by marefr** [comment]
@ldktta Hey, can you include the panel json of your broken panel? Thanks

**Comment by ldktta** [comment]
Hi, This happens to me with the panels that I already have created and when I create a new one.
I give them a json with problems, but everything that uses an elastisearch database has this behavior.

Pie Chart Json:
{
  "aliasColors": {},
  "breakPoint": "50%",
  "cacheTimeout": null,
  "combine": {
    "label": "Others",
    "threshold": 0
  },
  "datasource": "NetFlow",
  "decimals": 1,
  "fontSize": "80%",
  "format": "bps",
  "gridPos": {
    "h": 8,
    "w": 9,
    "x": 0,
    "y": 0
  },
  "hideTimeOverride": true,
  "id": 2,
  "interval": "20s",
  "legend": {
    "show": true,
    "sort": "current",
    "sortDesc": true,
    "values": true
  },
  "legendType": "Right side",
  "links": [],
  "maxDataPoints": 3,
  "nullPointMode": "connected",
  "pieType": "pie",
  "strokeWidth": "0.3",
  "targets": [
    {
      "alias": "",
      "bucketAggs": [
        {
          "fake": true,
          "field": "APP.keyword",
          "id": "3",
          "settings": {
            "min_doc_count": 1,
            "order": "desc",
            "orderBy": "_term",
            "size": "0"
          },
          "type": "terms"
        },
        {
          "field": "@timestamp",
          "id": "2",
          "settings": {
            "interval": "20s",
            "min_doc_count": 0,
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "metrics": [
        {
          "field": "netflow.fwd_flow_delta_bytes",
          "id": "1",
          "inlineScript": "(_value/20)*8",
          "meta": {},
          "settings": {
            "script": {
              "inline": "(_value/20)*8"
            }
          },
          "type": "sum"
        }
      ],
      "query": "",
      "refId": "A",
      "timeField": "@timestamp"
    }
  ],
  "timeFrom": "1m",
  "timeShift": "10s",
  "title": "▲ Actual Upload",
  "type": "grafana-piechart-panel",
  "valueName": "current"
}
