### ISSUE TITLE
Missing datapoints for timerange greater than 6 hours

### ISSUE THREAD

**Issue by stephenpaul2727** [grafana/grafana#14196]
### What Grafana version are you using?
5.2.4

### What datasource are you using?
Graphite

### What OS are you running grafana on?
I am using grafana docker image. Underlying VM is running on Amazon Linux 2.

### What did you do?
aliasByNode(summarize($speedtestserver.interface.eth0.if_octets.tx, '10min', 'sum', false), 0,4) where $speedtestserver variable implies three values(speedtestserver1,speedtestserver2,speedtestserver3). I am using collectd on client machines to push network stats to graphite

### What was the expected result?
Existing Data should be shown for all the possible time ranges.

### What happened instead?
Data is missing if I set time range > 6 hours. If I use the query inspector, the response object with datapoints array is showing null values. For < 6 hours, It was returning the response object with correct datapoints according to the existing whisper data. 
[grafana-data.zip](https://github.com/grafana/grafana/files/2617453/grafana-data.zip)

### If related to metric query / data viz:
aliasByNode(summarize($speedtestserver.interface.eth0.if_octets.tx, '10min', 'sum', false), 0,4)

**Comment by torkelo** [comment]
Check your graphite schema aggregation config, closing this as it’s a Graphite config issue

Please ask questions on the community site https://community.grafana.com
