### ISSUE TITLE
Time window and refresh time interval with alignment

### ISSUE THREAD

**Issue by juise** [grafana/grafana#1419]
Hi!

When I set time window and refresh time interval by example "5 minutes ago to a few seconds ago, refresh every 5s" at 14:06:07, the refresh time interval and time window will not be time aligned as 14:06:05 (i.e (now() - now() % refresh_interval).

Will be good to add this feature as some optional parameter.

**Comment by itsystem** [comment]
++

**Comment by ioff** [comment]
++

**Comment by 13470** [comment]
++

**Comment by kipelovets** [comment]
Totally agree here. It's convenient to see zero-aligned time intervals such as 14:06:00, 14:06:05, 14:06:10, etc. It's important if the backend stores data by zero-aligned intervals, we would want to have  same intervals on Grafana's side

**Comment by hugoeld** [comment]
+1, just bumped into this issue with influxdb backend today
Also I agree with @juise that it is better to implement this feature as an optional configuration parameter.
Also it would benefit if alignment scale should be configurable as well, e.g. minute, hour, day etc.

**Comment by hugoeld** [comment]
any updates on this?
