### ISSUE TITLE
Hide empty panel

### ISSUE THREAD

**Issue by Meruem94** [grafana/grafana#14204]
Hi

It's possible to hide panel with no data ? Because I generate a lot of panel with many of them didn't have data (empty panel).

No feature to do this or maybe expected in the milestone roadmap ?

Similar issue here #4470

Regards,

**Comment by torkelo** [comment]
I don't think we will support this. We are might be adding an option to show a custom markdown description text when there is no data in the panel. But hiding the panel and causing a cascading layout change is tricky. 

We hope to solve usecases like this in the future by having a new type of scripted dashboards where queries live on the dashboard level and generate a layout.

**Comment by Meruem94** [comment]
Ok thanks.

**Comment by NeySlim** [comment]
Yes please, very interested in this option., for exactly the same purpose.

**Comment by slash-zero** [comment]
Yes please - I am using dashboards to show server status, and would like to have rows grouped in tiers.  For example:

Tier 1 (row, repeating on variable (tag) A)
- service 1 (repeating on variable B)
- service 2 (repeating on variable B)

Tier 2 (row, repeating on variable (tag) A) 
- service 3 (repeating on variable B)
- service 4 (repeating on variable B)

This would be super useful.
