### ISSUE TITLE
Integrated function docs in grafana is broken in 5.3.2

### ISSUE THREAD

**Issue by gksinghjsr** [grafana/grafana#14200]
The function docs are displayed on hover in other versions of grafana, for example 5.2.4. The functions are displayed from the '?' function control button, but not on hover.
### What Grafana version are you using?
5.3.2
### What datasource are you using?
graphite
### What OS are you running grafana on?
Centos 7
### What did you do?
Try adding a function in grafana, and hover over any function
### What was the expected result?
It would display the integrated function docs
### What happened instead?
It doesn't show the integrated function docs

**Comment by xlson** [comment]
@gksinghjsr The hover docs aren't available for all versions of Graphite. I think it might be limited to Graphite >= 1.0. For the hover docs to work you will have to set the correct version of Graphite when setting up the datasource.
