### ISSUE TITLE
Automatic cleanup of nightlies

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#14206]
# Background and Problem
Packaged releases of Grafana have been migrated from Amazon S3 to GCP Buckets and to make sure our storage bill doesn't grow too much we should automatically delete nightly builds that are older than 30 days just like we do in Amazon S3.

Releases and nightlies both reside in the same bucket on GCP and that is a problem for us since it's not possible to filter on a prefix (like the subpath for nightlies) in GCP retentions policies.

# Potential Solutions

- Move nightlies into their own bucket so that they can have their own retention policy
  - this would also force us to create a separate subdomain for nightlies since dl.grafana.com points directly to the bucket
- Setup an external job to automatically delete old nightlies

**Comment by torkelo** [comment]
think this is done on the grafana.com side now
