### ISSUE TITLE
Nested Chain not Returning memberOf parent ldap group.

### ISSUE THREAD

**Issue by provenvelocity** [grafana/grafana#14218]
Nested Chain not Returning memberOf parent ldap group causing group_mappings to no longer function as needed. 

"memberOf Chain parent group" issue has been tested in the most recent release of grafana and results in the error as I will explain below.

With a working ldap toml and the LDAP_MATCHING_RULE_IN_CHAIN turned on this is the result I get.

toml:

group_search_filter = "(&(|(mail=%s)(sAMAccountName=%s)(userPrincipalName=%s))(|(memberOf:1.2.840.113556.1.4.1941:=CN=grfana-admin,OU=Groups,OU=Managed,DC=corp,DC=company,DC=com)(memberOf:1.2.840.113556.1.4.1941:=CN=grfana-users,OU=Groups,OU=Managed,DC=corp,DC=company,DC=com)))"
search_base_dns = ["ou=Users,ou=Managed,dc=company,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=grfana-admins,OU=Groups,OU=Managed,DC=company,DC=com"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "CN=grfana-users,OU=Groups,OU=Managed,DC=company,DC=com"
org_role = "editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "viewer"

ldap data:
group: grfana-admins
⋅⋅⋅user: bill
⋅⋅⋅group: most-excellent 
⋅⋅⋅⋅⋅⋅user: ted
group: grfana-users
⋅⋅⋅user: rufus
⋅⋅⋅group: time-machine
⋅⋅⋅⋅⋅⋅user: napoleon

Ldap return in grafana with debug on.

user: bill 
⋅⋅⋅memberOf=[CN=grfana-admins,OU=Groups,OU=Managed,DC=company,DC=com]
user: ted 
⋅⋅⋅ memberOf=[CN=most-excellent,OU=Groups,OU=Managed,DC=company,DC=com]
user: rufus 
⋅⋅⋅memberOf=[CN=grfana-users,OU=Groups,OU=Managed,DC=company,DC=com]
user: rapoleon 
⋅⋅⋅memberOf=[CN=time-machine,OU=Groups,OU=Managed,DC=company,DC=com]

I can log in with all users.  wowo

user rights in grafana:
bill: admin
ted:Editor
rufus:Editor
napoleon: viewer

Not the right user rights: so not excellent 

The issue is that AD does not return the parent groups in memberOf only the last group in the chain that was used to authenticate. It is a known flaw in AD ldap and has never been fixed to the best of my knowledge. 

I wrote some code in ldap.go to take the groupDN in server group mappings and find out the group used to auth the user at login and add to the user's memberOf as follows.

same ldap data

Grafana return and result.
user: bill 
⋅⋅⋅memberOf=[CN=grfana-admins,OU=Groups,OU=Managed,DC=company,DC=com]
user: ted 
⋅⋅⋅memberOf=["CN=grfana-admins,,OU=Groups,OU=Managed,DC=company,DC=com","CN=most-excellent,OU=Groups,OU=Managed,DC=company,DC=com"]
user: Rufus 
⋅⋅⋅memberOf=[CN=grfana-users,OU=Groups,OU=Managed,DC=company,DC=com]
user: Napoleon 
⋅⋅⋅memberOf=["CN=time-machine,OU=Groups,OU=Managed,DC=company,DC=com","CN=grafana-users,OU=Groups,OU=Managed,DC=company,DC=com"]

User rights in grafana:
bill: admin
ted: admin
rufus:Editor
napoleon: editor

As said this is a known flaw with AD and I have a fix for the above issue but i want to confirm there is not a resolution i dont know of. 

_Originally posted by @provenvelocity in https://github.com/grafana/grafana/issues/2582#issuecomment-442163181_

**Comment by ArcticSnowman** [comment]
Looking at your config..  I think you might have the 'group_search_filter' wrong..    

AFIAK,  that field is used to find the groups, based on the 'members' of the group. So it starts with the group and re-curses down the chain of members until it find the matching `group_search_filter_user_attribute`.

My setup looks like this
```
group_search_filter = "((member:1.2.840.113556.1.4.1941:=%s))"
group_search_base_dns = ["OU=Groups,OU=Managed,DC=company,DC=com"]
group_search_filter_user_attribute = "distinguishedName"

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "distinguishedName"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=Grafana-Admin,OU=App-Groups,OU=Groups,OU=Managed,DC=company,DC=com"
org_role = "Admin"
grafana_admin = "true"

[[servers.group_mappings]]
group_dn = "CN=Grafana-Editors,OU=App-Groups,OU=Groups,OU=Managed,DC=company,DC=com"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

```

**Comment by provenvelocity** [comment]
My Search work and even a more basic version of it still works and the user
is authenticated and allowed in. I also have the search filtering just the
groups I want to allow access to control and keep anyone from even getting
through the door. My problem is after group search and what is happening
with memberOf. The group search works and only people in the groups can log
in, but their memberOf does not have all the parent groups of the nested
groups.

**Comment by darxriggs** [comment]
@provenvelocity is this still an issue?

**Comment by provenvelocity** [comment]
I fixed it my code and have ment to get it back to the community but I left
the company..... I will check the latest code and see if it’s still and
issue and commit my code if it is. But if the ldap has not changed I bet it
still is an issue.
