### ISSUE TITLE
using time.RFC3339Nano instead of time.RFC3339

### ISSUE THREAD

**Issue by vinnitu** [grafana/grafana#14211]
Hello!

Can we change from-to times from seconds to seconds with fractional?

https://github.com/grafana/grafana/blob/bc3b7357bd13ca75974c6319835a0fbf49ff9b6d/pkg/tsdb/sql_engine.go#L199

![image](https://user-images.githubusercontent.com/432168/49141739-f709d880-f2ff-11e8-8d9a-1eae3ad4339f.png)

if replace with microsecond value it is ok

![image](https://user-images.githubusercontent.com/432168/49141868-45b77280-f300-11e8-8a27-97b74ffbff87.png)

&from=1540899236658&to=1540899237298&tab=metrics
must be converted to 
 tt between "2018-10-30 11:33:56.658" and "2018-10-30 11:33:57.298"
but now only
 tt between "2018-10-30 11:33:56" and "2018-10-30 11:33:57"

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
