### ISSUE TITLE
UX - if auto-refresh is enabled, graph editing gets frustrating

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1421]
With auto-refresh enabled, any menus open as part of a graph edit dialog get closed when the refresh happens. With a refresh of 5s this makes editing rather frustrating. 

Example of the problem is when building regex for a InfluxDB metric; a list of series is returned in a menu  for the user to choose from, but if the refresh happens whilst the menu is open all matching options get added to the graph

Suggest disabling auto-refresh when in edit panel (or make it a configurable option to do so).

**Comment by xneo64** [comment]
+1

**Comment by torkelo** [comment]
This should not be a big problem anymore. If it is, just disable auto refresh.
