### ISSUE TITLE
Variable regex not matching date from datetime

### ISSUE THREAD

**Issue by mbbxAdam** [grafana/grafana#14213]
### What Grafana version are you using?
4.0
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Tried to use the regex feature of query variables
### What was the expected result?
The regex `/\d{4}-\d{2}-\d{2}/` should match `2018-11-27` from `2018-11-27T00:00:00.000Z`
### What happened instead?
It doesn't match. See https://regex101.com/ to test it.

**Without regex:**
![image](https://user-images.githubusercontent.com/30151503/49143708-8230a180-f2f3-11e8-8a5c-4d787015d082.png)

**With regex:**
![image](https://user-images.githubusercontent.com/30151503/49143835-d0de3b80-f2f3-11e8-8437-0092c4108b95.png)

**Comment by torkelo** [comment]
what browser are you using? Can you try latest Grafana?

**Comment by mbbxAdam** [comment]
I'm using Firefox 63.0.3 and yes I've tried the latest Grafana version. I do actually get the following error in the developer console:
![image](https://user-images.githubusercontent.com/30151503/49790669-b8741500-fd26-11e8-88b5-4734635b7e09.png)

**Comment by bergquist** [comment]
Hi @mbbxAdam Grafana 4.0 is over two years old. please upgrade to a newer version. 

I'm closing this since we dont provide community support for such old versions.
