### ISSUE TITLE
Needs to logout from grafana

### ISSUE THREAD

**Issue by contactsagarkate** [grafana/grafana#14210]
Hello All,

I  have used nodejs express module as prosy server, I have also use other api  oauth2 for authentication user. So what I want is like, I want to logout from grafana when my nodejs express session got expired.
So currently when session got expired, I have redirect the response to logout page. even I have seen in the network tab that logout url got executed and it receives 200 status but in the UI, its not reflecting anything and I am getting "unexpexted error" message.

So Do you have any idea about it?

Thank you,

**Comment by xlson** [comment]
This is more of a community question and I notice that you have posted it there as well so I will close this.
