### ISSUE TITLE
Feature Request: Add support for CloudWatch Insights Queries

### ISSUE THREAD

**Issue by jleeh** [grafana/grafana#14217]
With AWS' new Insights feature for CloudWatch it would be fantastic to be able to specify these queries in Grafana and create visualisations.
https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-logs-insights-fast-interactive-log-analytics/

This would be fantastic, removing the need to build glue code that publishes these queries as custom metrics to build alerting/visualisations for, managing it all in Grafana instead.

**Comment by mweiden** [comment]
I'd like to surface this as a high priority data source. I imagine many AWS users (and there are a lot of those) would be more likely to use Grafana if this existed.

**Comment by mtanda** [comment]
My work for this feature.
https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource/pull/6

**Comment by schanjr** [comment]
@torkelo @aocenas @jschill . Would love to have your grace in reviewing if possible. This is a top wanted feature...

**Comment by Sytten** [comment]
Any progress on getting this merged?

**Comment by vinodhkrishnaraju** [comment]
Any updates on getting this merged?

**Comment by vinodhkrishnaraju** [comment]
Any progress?

**Comment by codingtony** [comment]
This is a really neat feature to add to Grafana, Cloudwatch Insights are awesome, being able to use this data source in Grafana would be very appreciated

**Comment by nickychow** [comment]
Hey guys, I'd also like to second this as a high priority feature request. I would be awesome if we can have this in Grafana then we can remove the need of the AWS console access for support desk guys.

**Comment by carloshgaray** [comment]
+1

**Comment by lachlanbb** [comment]
+1 Need this feature, Or I might have to use Kibana *screams*

**Comment by cavallos** [comment]
+1 :)

**Comment by kapralVV** [comment]
+1

**Comment by rostyslav-dyiak** [comment]
+1

**Comment by rparashchak** [comment]
+1

**Comment by HJEGeorge** [comment]
+1

**Comment by spezam** [comment]
+1

**Comment by Poaz** [comment]
+1

**Comment by Ivanov-Alexander** [comment]
+1

**Comment by orangr1989** [comment]
+1

**Comment by eliassv** [comment]
+1

**Comment by babakgh** [comment]
+1

**Comment by JohnLennonNA** [comment]
+1

**Comment by aocenas** [comment]
Closing this as this was implemented in https://github.com/grafana/grafana/pull/23566 and will be released in 7.0 next week.

For anybody interested here is also list of existing bugs that still need to be fixed https://github.com/grafana/grafana/issues/24333.

**Comment by viper25** [comment]
Is there any documentation for this? I haven't seen any examples of how to do CW Insights query using Grafana and can't figure out how to too.

**Comment by aocenas** [comment]
@viper25 we are bit late with the docs update. Here is a draft that hopefully will be merged soon https://github.com/grafana/grafana/pull/23651

**Comment by viper25** [comment]
I know this is closed, but where exactly are the CW Insights docs? I still don't see how to setup a Insights Grafana dashboard

**Comment by viper25** [comment]
I've done that but I've never got it to work nor seen a single example or screenshot where it does work. 
![image](https://user-images.githubusercontent.com/327990/84332952-ef97e080-abc0-11ea-8605-63382c4d8631.png)
All I get is a "Metric Request Error". The same when I try in "Explore" as well.
![image](https://user-images.githubusercontent.com/327990/84333065-384f9980-abc1-11ea-9da4-4d98ddd96974.png)
I don't see what I'm doing wrong - am following the docs. Is there something obvious I'm missing?

**Comment by aocenas** [comment]
@viper25 hmm not sure, I mean definitely not clear from the screenshot, seems like we swallow any useful error message there. Can you create a bug report, and add there any browser console errors or if you have access to that any server side grafana logs?

**Comment by aocenas** [comment]
@viper25 hmm one thing though it is a bit quirky in the sense that you have to match a bit the query type with the output you want. In first example you have query `filter @message` but not saying what fields you actually want, not sure if it is valid query. In second case in Explore you are in Metrics mode but your query is `fields @message` which will give you messages but that is not timeseries data so that should work in Logs mode (I know this is bit confusing and we are working on removing the need to switch modes in future releases). If you want to return timeseries data you can use something like `stats count() by bin(10m)` that should give you count in 10 minutes buckets. So maybe try different Explore mode or query whether that gives you any relevant results. If not then please file the bug report.

**Comment by viper25** [comment]
`filter @message` might not be appropriate, but I did try with working queries and it still didn't work. It was working in CloudWatch Insights console but not Grafana. I'll open a bug report with my details

Also in Explore I have selected Logs mode as you can see below, but the Metrics button seems to be enabled (that's another bug but I didn't highlight that)

![image](https://user-images.githubusercontent.com/327990/84456302-3d304e00-ac92-11ea-847f-a9617bd8405f.png)

Will log a bug report

**Comment by shilnew** [comment]
Using `filter @message` in Grafana and it returns different results every time it is refreshed (re queried). And this is always less than the results returned in Cloudwatch Insights console. Also, saving the dashboard does not seem to work, as the view (log groups) selected is lost. There is another minor issue where we are not able to see the complete list of log groups in the dropdown, but not critical as we can type up the same.
