### ISSUE TITLE
Exported JSON files are not including the __inputs section

### ISSUE THREAD

**Issue by orojina** [grafana/grafana#14216]
### What Grafana version are you using? 
Grafana v5.3.4 (69630b9)

### What datasource are you using? 
Prometheus, ElasticSearch & Cloudwatch

### What OS are you running grafana on? 
Linux

### What did you do?
I exported a dashboard to a json file using the [export/import feature](http://docs.grafana.org/reference/export_import/)

### What was the expected result? 
See the **__inputs** section at the top of the JSON document. This section was present in a previous version of Grafana but after an upgrade to v5.3.4 its no longer included in the json file.

### What happened instead?
The JSON file was generated but it doesnt contain the __inputs section, which is causing us to do some extra manual work when we move dashboards across environments

**Comment by torkelo** [comment]
The export modal has new checkbox for sharing for external use (other instances), so you see this checkbox and did you check it?

**Comment by orojina** [comment]
@torkelo Sorry we just didnt noticed the new checkbox. I just checked it and now I can see the __inputs section in the json file.
