### ISSUE TITLE
matching parenthesis and curly braces are hard to see in dark theme

### ISSUE THREAD

**Issue by baiwfg2** [grafana/grafana#14223]
### What Grafana version are you using?  5.2

![image](https://user-images.githubusercontent.com/5157680/49198826-0a847480-f3d0-11e8-9133-558817702cd8.png)

Just like above images, I place my cursor on rightmost parenthesis, and I can only see the obvious matching symbol like a rectangle when zooming in browser greatly. But it still not friendly visible under dark theme.  I really hope it'd be fixed. 

Thanks.

**Comment by torkelo** [comment]
Closing this, as the Explore prometheus editor will solve this
