### ISSUE TITLE
unit calculation with kg is incorrect

### ISSUE THREAD

**Issue by SexyCatGirls** [grafana/grafana#14226]
Im running Grafana 5.3.4 on a debian server and use it to analyze machines at work,
yesterday i started collecting the kg's of the troughput and show it via a singlestat,
in this case its:
19385 kg

now if i put the unit to mass -> Kg
it displays as 
18.4 Mg
but it should be 18.4 Tons instead of milligrams

**Comment by xlson** [comment]
Hi, Mg stand for mega-gram, not milligram.
