### ISSUE TITLE
UI - Make legend table collapsable

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1422]
The Legend table option is superb - really adds a great touch to dashboards. 
What would be nice is if it could be toggled, similar to how rows can be. Then users can see more graphs at a glance, and expand out the legend to see min/max/current values etc as required (without having to navigate to another dashboard)

**Comment by torkelo** [comment]
The legend can be toggled from the panel menu, not so easy to find this toggle though

**Comment by rmoff** [comment]
It’s be great for usability if this could be made an option from the dashboard, without having to go into the panel. Maybe make it dependent on having the legend table & values enabled, and then in the natural frame that the table creates put a toggle icon in the top left, somewhere like this: 

![image](https://cloud.githubusercontent.com/assets/3671582/6040810/e8ee5aaa-ac6d-11e4-8915-94045dfa6713.png)

**Comment by torkelo** [comment]
You can toggle the legend using the panel menu.
