### ISSUE TITLE
Enhancement - AWS Timestream data source

### ISSUE THREAD

**Issue by mgravlin** [grafana/grafana#14224]
[AWS Timestream](https://aws.amazon.com/timestream/) time-series database was announced today. Support for AWS Timestream as a data source.

**Comment by torkelo** [comment]
We will 
https://grafana.com/plugins/grafana-timestream-datasource

**Comment by schickling** [comment]
Any update on this @torkelo?

**Comment by daniellee** [comment]
This has been released: https://grafana.com/grafana/plugins/grafana-timestream-datasource

https://github.com/grafana/timestream-datasource
