### ISSUE TITLE
Add support for EC2/API cloudwatch 

### ISSUE THREAD

**Issue by KVInventoR** [grafana/grafana#14233]
What Grafana version are you using?
v5.3.2

What datasource are you using?
Cloudwatch

What OS are you running grafana on?
CentOS7

What did you do?
While Templating, namespaces() Won't list the AWS/EC2/API namespace.
Error Message from Log ""Unable to find namespace AWS/EC2/API"".

What was the expected result?
List Available API metrics

What happened instead?
Error Message from Log ""Unable to find namespace AWS/EC2/API"".

AWS Provided additional monitoring for CloudWatch EC2 API Calls:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/monitor.html

it can be turned on though AWS Support, but it doesn't support by grafana

**Comment by davkal** [comment]
Related: #14231
