### ISSUE TITLE
Series specific overrides - exclude from Legend

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1423]
It'd be nice to be able to exclude a series from the legend, by adding this as an option to series specific overrides. 
For values that are fixed through the duration (eg a configured capacity value against which one is graphing actuals) it is not much use to show it in the legend (especially legend table) taking up pixel space, but still very useful to include in a graph itself.

**Comment by torkelo** [comment]
Good suggestion, should be pretty simple to implement.

**Comment by ryan-williams** [comment]
+1!

**Comment by torkelo** [comment]
Fixed in 2.1
