### ISSUE TITLE
Add support for AWS/Neptune Cloudwatch AWS

### ISSUE THREAD

**Issue by a8j8i8t8** [grafana/grafana#14231]
### What Grafana version are you using?
v5.3.0
### What datasource are you using?
Cloudwatch
### What OS are you running grafana on?
Amazon Linux AMI
### What did you do?
While Templating, namespaces() Won't list the AWS/Neptune namespace.
Error Message from Log ""Unable to find namespace AWS/Neptune"".
### What was the expected result?
List Available Neptune cluster metrics.
### What happened instead?
Error Message from Log ""Unable to find namespace AWS/Neptune"".

**Comment by davkal** [comment]
Looks like [these metrics](https://docs.aws.amazon.com/neptune/latest/userguide/cloudwatch.html#cw-metrics) need to be added to cloudwatch's metric lookup.
