### ISSUE TITLE
UI - "group by time" repeated label but different meanings

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1424]
When creating an InfluxDB metric there are two instances of the label "group by time" which is ambiguous. My understanding is the first is an explicit hard group by, the second is a soft lower-bound?

![image](https://cloud.githubusercontent.com/assets/3671582/6040532/eea5c47c-ac6a-11e4-8d2a-34da7661b345.png)

Maybe relabel the second one as "minimal time grouping" or something like that?

**Comment by torkelo** [comment]
yea, I understand that this could be confusing, the group by time that is on the query is for that query only. 

The one below the queries is if you want to set it for all queries, or set a lower limit for the auto group by time
