### ISSUE TITLE
Explore: Logging graph should show when limit was reached

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14244]
In Logging we always query with a limit of 1000 rows. When the limit is reached, there is a cutoff in the graph. It would be great if we could somehow mark the cutoff in the graph with a message that the limit was reached there, and that if you want to see more data you need to filter more or click left on the time picker.

Ideas:
- message below graph
- inject that message as graph annotation (vertical line)
- graph annotation but as a gray area instead of a line (not sure if we have flot plugin that supports this)

**Comment by aocenas** [comment]
Should be solved by changing the graph to show only existing data.
