### ISSUE TITLE
Explore: Logging graph bars are not properly stacked

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14247]
They are not stacked (should be 4 stacked, not 3 green + 1 orange hidden)
![screenshot 2018-11-30 at 11 14 29](https://user-images.githubusercontent.com/859729/49283124-2bf96500-f491-11e8-88fb-5743f38ae9a6.png)

Perhaps it's just a config issue.
Worst case: it's related to #9294

**Comment by gouthamve** [comment]
New artifacts found:

![image](https://user-images.githubusercontent.com/7354143/49639839-07256480-fa32-11e8-8ae5-776060018be9.png)

![image](https://user-images.githubusercontent.com/7354143/49639918-2fad5e80-fa32-11e8-8c8c-d681907293b0.png)

Not able to reproduce them though....
