### ISSUE TITLE
Explore: quickly graph distribution of labels or structured logging fields

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14252]
Use case 1:

Selectors like `{app="cassandra"}` show lines from multiple streams since the app runs on multiple instances. A quick proxy to check if all instances are healthy is to see if they roughly log the same. The instance is available as a label, so by hovering over a label value `instance-1`,  we could show how often a particular label is represented in the range compared to the other values' occurences of that label: 
```
  instance 3 ****************
> instance 1 **************
  instance 2 ****
```

Use case 2:

Apply the same to fields in structure logs, e.g. prometheus:

```
level=info ts=2018-11-30T09:00:12.888343924Z caller=compact.go:352 component=tsdb msg="compact blocks"
```

We could show the distribution of `component` values.

Use case 3:

Plot latencies as a proper line chart, as from the structured `duration` field:
```
level=info ts=2018-11-30T09:00:07.848766011Z caller=head.go:535 component=tsdb msg="WAL checkpoint complete" low=4659 high=4662 duration=3.390738494s
```

This should all be done in-browser, with the results shown (we're showing up to 1000, so you get enough datapoints).

**Comment by marefr** [comment]
@davkal this can be closed right since the PR is merged?

**Comment by davkal** [comment]
Have not implemented No. 3 yet. But that's fine.
