### ISSUE TITLE
Add pagination to alert list page

### ISSUE THREAD

**Issue by APenketh** [grafana/grafana#14269]
### What Grafana version are you using?
5.3.4
### What OS are you running grafana on?
CentOS 7.4
### What did you do?
When creating alerts and reviewing them in the alert rules page, they are all displayed as one long page. When creating hundreds or thousands of alerts it causes the performance of this page to suffer.
### What was the expected result?
Alerts are split up into multiple pages to make loading and searching quicker.
### What happened instead?
All alerts are displayed on one page.

**Comment by orojina** [comment]
@APenketh  In case you find this useful, and as a temporary solution,  I created a script to list  alerts with their statuses and the dashboard they belong to. Listing several alerts can be done with:

`grafana-cli alerts | grep -i <your_filter_cliteria>` 

Adding the watch command into the mix will give you and your team an auto-refreshed view of your alerts

https://github.com/orojina/grafana-cli

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
