### ISSUE TITLE
Select All key press doesn't work

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1426]
Grafana 1.9.1
Mac OS / Chrome Version 40.0.2214.94 (64-bit)

On the graph panel query editor pressing ⌘-A  (Cmd-A) doesn't work. Other ⌘ shortcuts (eg ⌘-C) to copy works fine.

Workaround is to use ⌘← to go to the beginning of the text box, and then ⌘⇧→ to select to the end of the text box.

**Comment by toni-moreno** [comment]
what keyboard layout do you have  ( what country ) ?

There is already  an issue related to that  question https://github.com/grafana/grafana/issues/1362

**Comment by rmoff** [comment]
British
