### ISSUE TITLE
[Feature request] Allow to specify Prometheus datasource additional GET/POST parameters

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#14261]
Hi, this issue is mainly targeting the Prometheus datasource focusing on possibility of Thanos project which implements the Prometheus query API but adds additional functionality of automatically down-sampling data. This feature can be enabled/disabled using additional GET parameter of the datasource query request.

If the Prometheus datasource plugin would allow specifying additional GET/POST data which would be added to the request it would provide possibility for user to control this feature-switch right from Grafana.

I know there could be issues with overriding colliding params  and it's pretty specific request but it would be nice feature for Thanos users I suppose.

**Comment by FUSAKLA** [comment]
Solution could be to add possibility to enable/disable downsampling using HTTP headers to Thanos.
That could be done when https://github.com/grafana/grafana/issues/12779 is implemented.

**Comment by povilasv** [comment]
To add to @FUSAKLA  I would love to have an ability to show Thanos warnings

Right now we show them in Thanos WEB UI (similiar to Prometheus Web UI)

![2019-04-14-092012](https://user-images.githubusercontent.com/22289110/56089118-a225c380-5e96-11e9-87a7-ee56a840c14d.png)

Also it would be great if we could configure the same parameters on the Datasource level. I.e. all the queries going to `Thanos LTS` datasource would have automatic down sampling enabled.

**Comment by davkal** [comment]
Done in #19121.
