### ISSUE TITLE
Ungraceful Handling Of A Large Number Of Tags In Dashboard Header

### ISSUE THREAD

**Issue by APenketh** [grafana/grafana#14268]
### What Grafana version are you using?
5.3.4
### What OS are you running grafana on?
CentOS 7.3
### What did you do?
Add multiple tags to a single dashboard.
### What was the expected result?
The excess tags are hidden from view if they go over a certain number

![image](https://user-images.githubusercontent.com/18573773/49351238-6e1ee280-f6ed-11e8-8ad2-c5cdab7630ac.png)

### What happened instead?
The title of the dashboard is hidden from view because of the tags

![image](https://user-images.githubusercontent.com/18573773/49351272-927abf00-f6ed-11e8-88fc-c35be1eb4e95.png)

**Comment by torkelo** [comment]
don't think this is very reasonable :) why have so many tags? would be nice sure. but can't be a super common problem.
