### ISSUE TITLE
Grafana data points timestamps are not aligned with actual Prometheus timestamps

### ISSUE THREAD

**Issue by rnachire** [grafana/grafana#14270]
we are using prometheus as a data source for grafana to visualise. Prometheus has the timestamp of actual message when it got. 
But, when we plot a graph on Grafana: we are not seeing the actual timestamp of message on each datapoint. Data points are getting replicated in because of step interval and resolution. Though we set 1 sec as scraping interval on grafana and 1/1 as resolution with 1sec as step interval. But when we look at data points, its showing every second through there are few dropped or missed collection from networking device(which is streaming the data). Basically, it is happening for all kinds of data which we store it on prometheus.

The no.of data points on prometheus console and grafana are different for the same query it is because of step interval and resolution.

Attached the prometheus and grafana query results.

[grafana_result.txt](https://github.com/grafana/grafana/files/2638057/grafana_result.txt)
[influx_result.txt](https://github.com/grafana/grafana/files/2638058/influx_result.txt)

Can you please help us to get only the actual timestamped data points on grafana.

Regards,
Rajesh

**Comment by torkelo** [comment]
not sure Prometheus can do this for range queries. 

If you want to look at the last data, you can use the table panel and Prometheus instant queries (check the instant checkbox in the prometheus query editor)

**Comment by DanCech** [comment]
To get multiple data points with their corresponding timestamps in the table panel, you need to use the "Instant" option in the query editor together with a Prometheus range query.  If you want to see the data points for the last 10 minutes, add `[10m]` to the end of your query like `name{label1=value1}[10m]`.
