### ISSUE TITLE
Explore UI: viewers can't access when `viewers_can_edit` is enabled

### ISSUE THREAD

**Issue by BertHartm** [grafana/grafana#14281]
### What Grafana version are you using?
5.4.0
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
running the grafana/grafana container from docker hub
### What did you do?
1) enabled the `viewers can edit` setting via an environment variable
2) enabled the explore ui setting via an environment variable
3) Logged in as a view only user (who has edit access to a folder already)
### What was the expected result?
To be able to access the /explore path and see the explore icon on the left
### What happened instead?
I can't access the /explore path or see the icon
### If related to metric query / data viz:
n/a
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
n/a

Maybe it''s not a bug, but I would expect the explore ui to be available if I can create / edit dashboards (even if I can't save them).

**Comment by torkelo** [comment]
think your right, if viewers_can_edit is on explore access should be granted.
