### ISSUE TITLE
folder name appears misleadingly when using viewers_can_edit

### ISSUE THREAD

**Issue by BertHartm** [grafana/grafana#14282]
Please include this information:
### What Grafana version are you using?
5.4.0
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
grafana/grafana:5.4.0 docker image
### What did you do?
1) enable viewers_can_edit
2) log in as a view only user, who has edit access to a folder (named `foo`)
3) view a dashboard in the `general` folder
4) click on settings (which lets me "save as" to the "foo" folder)
5) exit settings without doing anything else
### What was the expected result?
I should just see the dashboard name, with nothing preceding it, at the top
### What happened instead?
I saw `foo/dashboard_name`, making it seem like I was looking at a copy of the dashboard in the `foo` folder.
Note that a refresh cleared that state, and that the `foo` folder remained empty.
### If related to metric query / data viz:
n/a
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
n/a

**Comment by daniellee** [comment]
> What was the expected result?
> I should just see the dashboard name, with nothing preceding it, at the top

This doesn't sound like the expected result to me. You wrote: `I saw foo/dashboard_name, making it seem like I was looking at a copy of the dashboard in the foo folder.` That sounds like the expected result. If you choose save as then you are making a copy of the dashboard.

That last point however sounds strange: `Note that a refresh cleared that state, and that the foo folder remained empty.` Can you explain more?

When I followed your steps, a copy of the dashboard was saved in the `foo` folder. It is still there after refreshing.

**Comment by BertHartm** [comment]
Hey Daniel,

I never hit the save button, only opened and closed the menu. I confirmed
no copy was saved.

**Comment by daniellee** [comment]
@BertHartm aha, now I see what you mean. Yes, this is a bug.
