### ISSUE TITLE
stackdriver: fix selecting metrics with identical display names

### ISSUE THREAD

**Issue by kornholi** [grafana/grafana#14293]
### What Grafana version are you using?
5.4.0

There are several metrics with identical display names. For example, `container/cpu/core_usage_time`, `node/cpu/core_usage_time`, and `node_daemon/cpu/core_usage_time` show up as `CPU usage time`. Although all of them appear in the UI dropdown, they all refer to the first metric unless you explicitly enter the full metric name (e.g. `kubernetes.io/node_daemon/cpu/core_usage_time`). It would also be nice to see which exact metric you are choosing.

**Comment by arthurk** [comment]
I have the same problem with Memory Usage

<img width="450" alt="screenshot 2018-12-12 at 16 01 27" src="https://user-images.githubusercontent.com/23406/49858331-33245980-fe27-11e8-9ebe-088621a9ac18.png">
