### ISSUE TITLE
Make dashboard JSON editable

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1429]
It would be good if the dashboard JSON could be editable in place through the JSON view, in the same way that a panel's JSON can be viewed and editted. At the moment workflow is export JSON -> modify -> import.

**Comment by torkelo** [comment]
Just interested to know, what you want to edit, (so I understand the use case, and maybe find a better solution)

**Comment by rmoff** [comment]
I wanted to quickly clone another dashboard that I had open for editing in another window, without save -> open -> save as new name.

**Comment by xneo64** [comment]
+1

**Comment by bhattchaitanya** [comment]
+1

Example use case: if a dashboard needs to be updated with influxdb query which affects several dozen panels then it becomes a nightmare to do it manually. Having the ability to search and replace the json string externally and then saving it back to the dashboard would be enormously empowering. 

Note: This feature is available in other monitoring and anlaytics tools like Splunk.

**Comment by WinuxNomacs** [comment]
+1
Use case: update multiple panels at the simultaneously in place via add/modify/remove stats or graphite target queries.

Thank you and Grafana is truly awesome :)

**Comment by Dieterbe** [comment]
+1. use case: i have multiple annotations configured in a dashboard and want to copy the annotation settings to another dashboard.

**Comment by bergquist** [comment]
@Dieterbe I guess https://github.com/grafana/grafana/issues/4795 would solve your problem?

**Comment by Dieterbe** [comment]
yes that would for sure be even nicer than editing json. thanks.

**Comment by IvanVas** [comment]
+1

**Comment by kalidasya** [comment]
definitely +1, I just wasted some time on upgrade a huge dashboard...

**Comment by ezraroi** [comment]
+1

**Comment by dlukman** [comment]
+1

**Comment by prontog** [comment]
+1

**Comment by markkrj** [comment]
+1

**Comment by zp-markusp** [comment]
+1

**Comment by mattttt** [comment]
Now with the addition of Dashboard Version History, it'd make it very easy to roll back if you did anything to break the dashboard. Previously, if we introduced this feature and someone broke even the smallest thing, there'd be trouble.

**Comment by torkelo** [comment]
they would still be in trouble as you have to be able to open dashboard to access dashboard history :(

**Comment by zp-markusp** [comment]
Hi @torkelo, just to give you some background why I'm missing this feature:
We have a setup in which we run a completely dedicated stack for DEV and PROD. So, dedicated influx, grafana instance etc. DEV teams are pushing metrics from their applications in DEV stage to our DEV stack. As soon they deploy to PROD, metrics are going into PROD stack.
We are developing our dashboard on the DEV stack and as soon they are working the way we expect, we are applying the changes to PROD.
In the current setup, without being able to copy dashboard content from one to the other this a a huge nightmare... 
Sure, you apply the same changes in Dashboard UI on both dashboards - but you always have double work and dashboards will drift apart from each other. 
Sure you can delete the dashboard on PROD and create a new one. But also this is difficult to sell to others and you loose the changelog (which I really like).

I'm open for any proposals to improve the workflow. For me the straightforward approach would be to just replace the raw json of a dashboard ;-)

regards, Markus

**Comment by aprasolova** [comment]
+1

**Comment by anhlqn** [comment]
Being able to edit dashboard JSON directly on grafana would be very helpful for me. Having to export, edit, and reimport like others are doing is quite painful. I often have to make changes across multiple panels:
- Change threshold settings
- Change min max on Axis
- Change legend settings
- Clone from a dashboard template to 4 organization
- Update data source
- Update query per panel

and lots of other config changes

**Comment by akhiltak** [comment]
+1

This helps in making changes to multiple panels in one go. Most of the important use cases are covered above.

**Comment by hbh7** [comment]
+1
Just encountered this issue, would love to see it added!

**Comment by GrantPalmerTamr** [comment]
+1

**Comment by razvanm** [comment]
I bump into issues having to change the font size from 170% to 100% for 30 singlestat panels.

**Comment by felixge** [comment]
If this is difficult to implement for some reason, I think another thing that would be helpful in the meantime is to make the "View JSON" text editor field read-only. I just spend 10 minutes editing and re-saving my dashboard JSON, wondering why my changes were not working (v5.0.4).

**Comment by wetterfrosch** [comment]
+1

**Comment by torkelo** [comment]
No need to upvote or plus 1 it after it has been implemented and is available in nightly builds :)

**Comment by CraigAck** [comment]
What are possible reasons that I cannot edit **threshold** settings on v8.3.3?

If I edit them on JSON then they reset automatically.

They are disabled on the graph view as well.

Is there any other way?
