### ISSUE TITLE
Allow Time Region configuration per dashboard

### ISSUE THREAD

**Issue by keithf4** [grafana/grafana#14309]
Really like the new Time Region feature that was introduced in 5.4.0. Only thing is it has to be set on a per-graph basis. A feature to apply a time region to an entire dashboard would be really nice.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
