### ISSUE TITLE
Light theme has dark submenu

### ISSUE THREAD

**Issue by achennuru** [grafana/grafana#14302]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.3.2
### What was the expected result?
The menu should be light
### What happened instead?
The menu shows same as dark theme.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Actual: 
![image](https://user-images.githubusercontent.com/6034277/49445495-05447280-f7a0-11e8-9960-96d9c75eb29d.png)
Expected:
![image](https://user-images.githubusercontent.com/6034277/49445578-3b81f200-f7a0-11e8-8c4e-fb8276e6ede9.png)

**Comment by torkelo** [comment]
this is by design
