### ISSUE TITLE
Allow ignoring 0 same as null in graph.

### ISSUE THREAD

**Issue by gajarajkalburgi** [grafana/grafana#14318]
Please include this information:
**What Grafana version are you using?**
Grafana v5.3.1

**What datasource are you using?**
Prometheus

**What OS are you running grafana on?**
MacOS

**What did you do?**
Data collection through micrometer and scapped to prometheous.
But, max request latency is decayed to 0 when no request comes.
So minimum of max latency becomes 0 in graph and also in lagend table).

**Example**
<img width="1346" alt="Http Latency" src="https://user-images.githubusercontent.com/13781122/49484525-b4557c80-f87a-11e8-9b8b-3bef997cb965.png">

**What was the expected result?**
 There should be way to ignore 0, same as we can ignore null, consider null as 0.

**Contribution**
I would like to contribute for above issue. Other solutions are also welcome.

**Comment by torkelo** [comment]
You should be able to do this in your query

**Comment by gajarajkalburgi** [comment]
Hello @torkelo,
Thank you for your response. 
I realized that we can filter results by query and avoid above situation.
`max(http_server_requests_seconds_max{application=~"$application" }) by (method,uri) > 0`
