### ISSUE TITLE
Grafana trying to use sql instead of postgres for database

### ISSUE THREAD

**Issue by jpilisuk** [grafana/grafana#14312]
### What Grafana version are you using?
5.4.0
### What datasource are you using?
postgres
### What OS are you running grafana on?
Alpine
### What did you do?
I am deploying with a helm chart in kubernetes and overwriting the config with a secret (edited the default grafana.ini with a custom one and saved that as a secret) I changed the database section to use postgres and I put in my database information.
### What was the expected result?
it would take my new database as a source to stare backend data
### What happened instead?
grafana went start and when I check the logs I get the following error
`lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: unable to open database file\n"`

**Comment by torkelo** [comment]
The database needs to exist
