### ISSUE TITLE
Postgres datasource should include a configurable default timeColumn name (vs hardcoded 'time')

### ISSUE THREAD

**Issue by cloud-rocket** [grafana/grafana#14310]
Our time column in postgres is not  called `time`.

It would be really helpful to be able to reconfigure default hardcoded `time` column name to something else. So queries like `select *` will work without explicitly stating which column is the time column.

Please include this information:
* What Grafana version are you using? 5.3.4
* What datasource are you using? Postgres
* What OS are you running grafana on? Kubernetes
* What did you do? `select *` query to display all signals
* What was the expected result? Should detect time column automatically
* What happened instead? You can't really do `select *` unless timeColumn name is `time`

**Comment by torkelo** [comment]
you can have any query be the time column. 

select * queries is not recommended, we recommend you use the macros or query editor
