### ISSUE TITLE
Large text in a cell not rendered correctly upon changing table-panel size

### ISSUE THREAD

**Issue by saurabh3896** [grafana/grafana#14329]
### What Grafana version are you using?
5.1.3
### What datasource are you using?
PostgreSQL
### What OS are you running grafana on?
Linux (Ubuntu 18.04.1)
### What did you do?
Display data from a database with columns having large amount of text.
### What was the expected result?
Upon reducing table-panel size, large text in a cell should automatically rearrange (increase the height of a cell if its width is decreased).
### What happened instead?
When the table size is reduced horizontally, the text in a cell does not wrap in the sense that the height of a particular CELL does not increase to account for displaying complete text when its width is decreased (due to shrink in size, reducing the width of table-panel).

Original size, shows two columns.

![screenshot from 2018-12-05 18-32-40](https://user-images.githubusercontent.com/13899504/49504640-72015f00-f8bd-11e8-8168-57858bd9af39.png)

 When reduced, the second column is hidden and text isn't rendered correctly (cuts the text).

![screenshot from 2018-12-05 18-39-32](https://user-images.githubusercontent.com/13899504/49504741-b0971980-f8bd-11e8-92f0-1f7de07d5fd5.png)

**Comment by torkelo** [comment]
unless there is a whitespace in the text mass browser won't wrap it (break it). 

We will probably improve handling of large text in a future version of the table panel. Closing this as we already have other issues that cover this.

**Comment by sreeprathyusha6** [comment]
Can we render a column value as variable in url(to avoid display the values in url)?
