### ISSUE TITLE
UX - when window is too narrow there should be an indication that the toolbar has been dropped

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#1432]
Currently when the window is too narrow, even just by a few pixels, the whole timepicker and save/open toolbar gets dropped

![image](https://cloud.githubusercontent.com/assets/3671582/6051839/8d9dedf4-acc3-11e4-9f67-525f4a2ad407.png)

There should be *some* visual indication that the window is too narrow. Maybe a red exclamation mark (like is used on the metrics panel when a query is invalid) in the very top-right with tooltip explaining to widen the window? 
In the long run, it would be good if the toolbar gracefully degraded as the window shrank so that things like the open/save icons were always shown in favour of the verbose and horizontally-expensive description of the time frame ("15 minutes to a few seconds ago") - which is very nice but not essential.

**Comment by torkelo** [comment]
Solved in 2.6

![image](https://cloud.githubusercontent.com/assets/10999/12449730/9a1be4da-bf7f-11e5-8fbe-3f2d45efd7cc.png)
