### ISSUE TITLE
Feature Request: Parse Json data from PostgreSQL 

### ISSUE THREAD

**Issue by Sunil84** [grafana/grafana#14321]
I am using PostgreSQL datasource to connect PostgreSQL database to grafana UI components like Graph, HeatMap, Pie Chart etc. The data type of the posted data is of type "JSON". The UI components For ex: Pie Chart(plugin) requires numeric type for values. The JSON type object contains columns information. Each column is again of type JSON containing metric and values in the form of JSON strings. Currently there is no functionality to parse JSON type data in query builder or Edit SQL(raw) for UI components.

Grafana version: Grafana v5.3.4 (69630b9)
OS are you running grafana on: Windows 7 Ultimate

**Comment by marefr** [comment]
If you use the raw query mode it should work to select and filter from jsonb column, i.e. something like this?

```sql
SELECT <time column>, metadata->>'value' as value, metadata->>'key' as metric FROM <table>;
```

**Comment by Sunil84** [comment]
**For this query:**
SELECT
  NOW() AS "time",
  *
FROM asset_dashboard
WHERE
  groupid = $$all$$

Format as: Table

**This is the response in query Inspector:**
response:Object
results:Object
A:Object
refId:"A"
meta:Object
series:null
tables:Array[1]
0:Object
columns:Array[17]
0:Object
text:"time"
1:Object
text:"groupid"
2:Object
text:"os"
3:Object
text:"systemmanufacturer"
4:Object
5:Object
6:Object
7:Object
8:Object
9:Object
10:Object
11:Object
12:Object
13:Object
14:Object
15:Object
16:Object
rows:Array[1]
0:Array[17]
0:1544001348974.43
1:"all"
2:"[["Win 7",349],["Win 8",292],["Win 8.1",125],["Win XP",28],["Win 10",38],["others",2]]"
3:"[["Acer",545],["Dell ",173],["IBM",72],["HP",15],["System manufacturer",12],["Others",16]]"

**When I try this query:**
SELECT
  NOW() AS "time",
  os->>'value' as value, 
  os->>'key' as metric
FROM asset_dashboard
WHERE
  groupid = $$all$$

Format as: Time series

**I get the following error message in red:**
Column metric must be of type UNKNOWN, TEXT, VARCHAR, CHAR. metric column name: metric type: TEXT but datatype is <nil>

**Comment by marefr** [comment]
> Column metric must be of type UNKNOWN, TEXT, VARCHAR, CHAR. metric column name: metric type: TEXT but datatype is nil

Please convert your selected value to numeric data type and convert selected metric to string.

**Comment by Sunil84** [comment]
Thanks for your reply.
Do I need to do the conversions in the raw query?
OR 
Do I need to do the conversions in the postgreSQL database table?

**When I try to cast in raw query, I get again an error message in red**
SELECT
  NOW() AS "time",
  CAST(os->>'value' AS int) AS value,  
  CAST(os->>'key' AS CHAR) AS metric
FROM asset_dashboard
WHERE
  groupid = $$all$$

Column metric must be of type UNKNOWN, TEXT, VARCHAR, CHAR. metric column name: metric type: BPCHAR but datatype is <nil>

**Comment by marefr** [comment]
I thought that doing it in the query should work.

How about

```sq
SELECT
NOW() AS "time",
CAST(os->>'value' AS int) AS value,
os->>'key'::text AS metric
FROM asset_dashboard
WHERE
groupid = $$all$$l
```

**Comment by Sunil84** [comment]
I tried using text or varchar conversion.
**I get the following error message in red:**
Column metric must be of type UNKNOWN, TEXT, VARCHAR, CHAR. metric column name: metric type: TEXT but datatype is '<nil>'

**Comment by Sunil84** [comment]
We modified the Postgres database table schema to suit our requirement. Now we are able to parse data without error.
Thanks for your support.
