### ISSUE TITLE
grafana SSO with apache reverse proxy

### ISSUE THREAD

**Issue by rakshith-b91** [grafana/grafana#14330]
Read before posting: 

### What Grafana version are you using?
5.3
### What datasource are you using?
inflxudb
### What OS are you running grafana on?
freebsd

 
Hi,

I’m using apache as reverse proxy for grafana 5. i have generated a api token for user. i want to login to grafana from my web application using this token key with out prompting the user for entering username and password. How can i use api token to login. or how can i use SSO so that i can login to my web application and authenticate grafana.

**Comment by rakshith-b91** [comment]
Hi,

I’m using apache as reverse proxy for grafana 5. i have generated a api token for user. i want to login to grafana from my web application using this token key with out prompting the user for entering username and password. How can i use api token to login. or how can i use SSO so that i can login to my web application and authenticate grafana.

**Comment by torkelo** [comment]
http://docs.grafana.org/auth/auth-proxy/#auth-proxy-authentication
