### ISSUE TITLE
Anonymous auth signs out the signed in user

### ISSUE THREAD

**Issue by charkost** [grafana/grafana#14335]
### What Grafana version are you using?

5.5.0-85ffd831pre1

### What OS are you running grafana on?

debian

### What did you do?

1) Enabled anonymous auth
2) Restarted grafana
3) Logged in as admin
4) Closed the browser (chromium v70.0.3538.110)
5) Re-opened the browser

### What was the expected result?

To be logged in as admin. 

### What happened instead?

I was viewing grafana as an anonymous user.

When i disable the anonymous auth, i continue to be logged in as admin after browser restarts.

**Comment by charkost** [comment]
Basic auth, default settings.

**Comment by charkost** [comment]
This happens in chromium. In firefox i get the expected result.

**Comment by Ijin08** [comment]
Confirmed. I was able to recreate in Chromium.

**Comment by torkelo** [comment]
@marefr maybe this is fixed with new token auth?

**Comment by marefr** [comment]
Fixed by #7741
