### ISSUE TITLE
Mysql datasource does not show all variables

### ISSUE THREAD

**Issue by mikezsin** [grafana/grafana#14346]
>>Another option is a query that can create a key/value variable. The query should return two columns that are named __text and __value. The __text column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allows you to have a friendly name as text and an id as the value. An example query with hostname as the text and id as the value

if __value column value is not unique, then the first value is used. Cant use like:
_text name1.srv __value:1.2.3.4
_text name2.srv __value:1.2.3.4
_text name3.srv __value:1.2.3.4

only name1.srv will be shown

**Comment by torkelo** [comment]
yes,text & value needs to be unique
