### ISSUE TITLE
Unable to view button "Add To Team" if Email and/or Login too long

### ISSUE THREAD

**Issue by lekpamartin** [grafana/grafana#14341]
I'm unable to view button "Add To Team" if Email and/or Login is very long. See screenshots below.

**Comment by marefr** [comment]
Could you please include some more information, login and email example and if possible include screenshot of the problem. Thanks

**Comment by lekpamartin** [comment]
Button 'Add to Team' is visible
![grafanaok](https://user-images.githubusercontent.com/6328239/49520166-eed30f80-f8a2-11e8-99cd-d7ce205a5ded.PNG)

Button 'Add to Team' below the fields
![grafana1](https://user-images.githubusercontent.com/6328239/49520164-ee3a7900-f8a2-11e8-9409-0ea52aa8d535.PNG)
![grafana2](https://user-images.githubusercontent.com/6328239/49520165-ee3a7900-f8a2-11e8-9321-703cd5a39523.PNG)

When the field size change the butoon don't move.

**Comment by jschill** [comment]
@lekpamartin Thanks for reporting this 👍
