### ISSUE TITLE
Setting up OAuth2 with AAD not working

### ISSUE THREAD

**Issue by Ilanak** [grafana/grafana#14357]
### What Grafana version are you using?
Grafana v5.4.0 (69c5191)

### What datasource are you using?
Azure Data Explorer but this is not relevant for the issue.

### What OS are you running grafana on?
ubuntu 18.04

### What did you do?
I'm trying to set up oauth2 with Azure Active Directory but finding same issue described [here](https://github.com/grafana/grafana/issues/12114)
This is my Auth config:
```
[auth.generic_oauth]
enabled = true
name = OAuth
allow_sign_up = true
client_id = <id>
client_secret = <secret>
scopes = user:email,read:org
auth_url = https://login.microsoftonline.com/<directory-id>/oauth2/authorize
token_url = https://login.microsoftonline.com/<directory-id>/oauth2/token
;api_url =
;team_ids =
;allowed_organizations =
;tls_skip_verify_insecure = false
;tls_client_cert =
;tls_client_key =
;tls_client_ca =

```
### What was the expected result?
The expected behaviour is signing in using AAD oauth2 authentication process.

### What happened instead?
Instead i'm getting an error:
![image](https://user-images.githubusercontent.com/13463870/49576898-efc17b00-f94e-11e8-9862-0fefec56c0de.png)
and the logs from the server are:
t=2018-12-06T09:52:48+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="Error getting user info: Get : unsupported protocol scheme \"\""

**Comment by marefr** [comment]
Have you read the [grafana documentation](http://docs.grafana.org/auth/generic-oauth/#set-up-oauth2-with-azure-active-directory) about oauth and azure active directory carefully? Seems like your scopes for example are different than in documentation.

**Comment by nitinjain999** [comment]
@marefr i have the same problem

**Comment by marefr** [comment]
@nitinjain999 have you read referenced documentation? Please post you're config (strip any sensitive information) for us to be able to help you further and/or check out our community site.

**Comment by zzarkouna** [comment]
how to match grafana roles with azureactiveDirectory
can't find grafana role ids!
