### ISSUE TITLE
heatmap panel

### ISSUE THREAD

**Issue by luluprat** [grafana/grafana#1435]
Hello,
i would like to create for multiple series in a tag a "heatmap" panel. 
in place of the y axis i will colarize the straight line.
i repeat it for every line which goes along the y axes .
do you think it's possible to integrate in graphana panel ?
any directive or help to begin would be apriciate .

thanks

**Comment by torkelo** [comment]
You can take a look at this PR: https://github.com/grafana/grafana/pull/797
