### ISSUE TITLE
Add a paremeter to add X axis on rendered PNG

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#14354]
### What Grafana version are you using?

master

### What datasource are you using?

prometheus

### What OS are you running grafana on?

linux

### What did you do?

render panel as png

### What was the expected result?

I would like to have a GET parameter show_x=true that would allow to show the X axis on rendered PNG.

**Comment by torkelo** [comment]
Graph style settings needs to set in the panel your rendering. 

We have another open feature request to provide full panel json via url , so closing this
