### ISSUE TITLE
how do you show raw cpu usage data in terms of % in grafana

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1436]
Hi Torkel:

If cpu data in opentsdb is as below:

proc.stat.cpu 1423234765 15645058 type=user
proc.stat.cpu 1423234765 856 type=nice
proc.stat.cpu 1423234765 883208 type=system
proc.stat.cpu 1423234765 32865961 type=idle
proc.stat.cpu 1423234765 72686 type=iowait

Is it possible to show this data in term of % in grafana

**Comment by torkelo** [comment]
@gsaray101 not sure what those values mean, 15645058 ? does not look like a percentage, Grafana leaves most metric calculation and analytics to the metric store backend

**Comment by luisdalves** [comment]
@gsaray101 did you find the way to draw these values?

**Comment by gsaray101** [comment]
No
