### ISSUE TITLE
Users unable to see query for graph without 'edit' permission

### ISSUE THREAD

**Issue by dzbarsky** [grafana/grafana#14373]
### What Grafana version are you using?
5.2.2

### What datasource are you using?
Custom one

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
Set permissions on some dashboards to make them uneditable

### What was the expected result?
There is still a way to view the query that generates the graph. As far as we know the only way is to click 'edit' to pop open the datasource UI. Is there a different nice way to view the query? Another possibility would be to allow 'edit' but disallow 'saving'

### What happened instead?
'edit' is not allowed, no other way to see the query.

### If related to metric query / data viz:
not relevant

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
not relevant

**Comment by torkelo** [comment]
use the viewers_can_edit setting to make it possible for viewers to make transient edits (they can't save still)
http://docs.grafana.org/installation/configuration/#viewers-can-edit
