### ISSUE TITLE
Missing Cloudwatch ES KibanaHealthyNodes Metric

### ISSUE THREAD

**Issue by markuman** [grafana/grafana#14376]
### What Grafana version are you using?

Version 5.3.4 (commit: 69630b9)

### What datasource are you using?

AWS/ES

### What OS are you running grafana on?

Debian GNU/Linux 9 (stretch)

### What did you do?

Try to use the `KibanaHealthyNodes` metric

### What was the expected result?

That I find and select `KibanaHealthyNodes` metric

### What happened instead?

`KibanaHealthyNodes` metric is not listed

In AWS CloudWatch Console it's in "Metrics -> ES -> Per-Domain-Per-Client Metrics -> Metric Name = `KibanaHealthyNodes`"

**Comment by mtanda** [comment]
Added in https://github.com/grafana/grafana/pull/16102 .
