### ISSUE TITLE
hour avg on a month worth of data returning 2 hourly average

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1437]
Hi Torkel,

There seems to be a problem with summary() function. I am trying to get hourly avg for one month of data for some servers. I am getting 2 hours averages instead of 1 hour.

this is the query:

aliasByNode(sortByName(summarize(consolidateBy(cloud.Guest.Resource_Utilization.{server1,server2,server3,server4}.PctCpuUsed, 'max'), '1h', 'max', false)), 4)

output is this:

server1;2015-01-01T06:00:00.000Z;5.4287499487400055
server1;2015-01-01T08:00:00.000Z;1.5004166762034097
server1;2015-01-01T10:00:00.000Z;1.6670833329359689
server1;2015-01-01T12:00:00.000Z;1.6462499996026358
server1;2015-01-01T14:00:00.000Z;1.6879166662693024
server1;2015-01-01T16:00:00.000Z;1.7816666662693024
server1;2015-01-01T18:00:00.000Z;2.1258333424727125
server1;2015-01-01T20:00:00.000Z;1.7091666758060455

Any ideas why this may be happening?

**Comment by torkelo** [comment]
strange, no I am not sure what that is happening, better open an issue in the graphite project repository, https://github.com/graphite-project/graphite-web

**Comment by gsaray101** [comment]
Actually, when pick data for a day or week, hourly average shows. If the range is one month or above, it now goes to 2 hours. Do you think this is still graphite issue?

**Comment by gsaray101** [comment]
I just tried your http://play.grafana.org/#/dashboard/db/templated-graphs and picked 1 months, I see hourly data as expected. what version of graphite are you using on that site?

**Comment by torkelo** [comment]
It is probably caused the your graphite schema config, maybe you have a 2h roll up period after a certain  time range?

**Comment by gsaray101** [comment]
I am using the defaults that are provided:


[default_1min_for_1day]
pattern = .*
retentions = 60s:1d
~

**Comment by torkelo** [comment]
That can't be right then you'd only have one day of data

**Comment by gsaray101** [comment]
would you mind sharing your config, I'm not able to get this work.
