### ISSUE TITLE
MySQL: Support caching_sha2_password

### ISSUE THREAD

**Issue by apapsch** [grafana/grafana#14370]
I'm using Grafana 5.4.0 with a MySQL 8 datasource on Fedora 28. I installed Grafana from the RPM and configured the MySQL datasource. Then I started the service via systemctl.

Expected result: Grafana should start successfully.
Actual result: Grafana failed with message "Service init failed: Migration failed err: this authentication plugin is not supported".

This problem hints at an old version of the Go MySQL driver, which doesn't support the new default authentication plugin in MySQL 8. See https://github.com/go-sql-driver/mysql/issues/785 for details. Support was added in [1.4.0](https://github.com/go-sql-driver/mysql/releases/tag/v1.4.0). In Grafana the dependency is locked at 2cc627a from Jan 13, while 1.4.0 is from Jun 3.

All Startup messages:

´´´
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Starting Grafana" logger=server version=5.4.0 commit=69c5191 branch=HEAD compiled=2018-12-03T11:17:42+0100
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="App mode production" logger=settings
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=14867
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Initializing HTTPServer" logger=server
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Initializing SqlStore" logger=server
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=info msg="Starting DB migration" logger=migrator
Dez 06 17:30:36 x grafana-server[14867]: t=2018-12-06T17:30:36+0100 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: this authentication plugin is not supported"
´´´

**Comment by apapsch** [comment]
I'm building the server with a newer Go MySQL driver version. If all goes well I'll send a PR for the `Gopkg.toml`.

**Comment by marefr** [comment]
@apapsch FYI you can still use MySQL 8 with Grafana if you enable legacy authentication in MySQL and set `allowNativePasswords=True` in connectingstring.

**Comment by apapsch** [comment]
True, I considered that but then I remembered the mountain of legacy at work. The less legacy the better :-) Luckily the change required to get rid of the legacy was very small.

**Comment by marefr** [comment]
Fixed by #16017
