### ISSUE TITLE
Problem with Repeat

### ISSUE THREAD

**Issue by ecraven** [grafana/grafana#14371]
### What Grafana version are you using?
v5.3.4 (docker grafana/grafana:5.3.4)
### What datasource are you using?
prometheus v2.5.0, (docker prom/prometheus:v2.5.0)
### What OS are you running grafana on?
Arch Linux (inside docker containers)
### What did you do?
Create a variable host as `label_values(probe_success, instance)`
![var-host](https://user-images.githubusercontent.com/215510/49607276-c841d100-f995-11e8-9fbe-0cb76bc9481e.png)
(I tried various variations of the settings multi-select and include all, see below)
Create a singlestat panel, set it to repeat horizontally for `$host`.
Set the metric to `probe_success{instance="$host"}`
Set the title to $host
### What was the expected result?
See a number of panels with correct metrics and titles.
### What happened instead?
- If neither multi-select nor include all is set:
  The first panel is missing (entry for the first host), everything else works fine
- If include all is set:
  All panels are shown, but all show "no data"
- If multi-select is set:
  All panels are shown, but all show "no data"

It seems that for some reason $host in the metric is not correctly interpreted as the single host setting for the panel. If I manually change $host to the actual name of a single host, then all panels show the same data correctly. The titles always show $host correctly.

~~I'd guess that this is a prometheus-specific problem with $host, but I'm not sure how to look at the expanded metric queries before they are sent to prometheus :-/~~

**Comment by ecraven** [comment]
Further investigation with the query inspector shows the following:
Correct query:
```
"url": "api/datasources/proxy/1/api/v1/query_range?query=probe_success%7Binstance%3D%22https%3A%2F%2Ffoo.example.com%2Fexample%22%7D&start=1544040000&end=1544127300&step=900"
```
Incorrect query:
```
"url": "api/datasources/proxy/1/api/v1/query_range?query=probe_success%7Binstance%3D%22https%3A%2F%2Ffoo%5C%5C.example%5C%5C.com%2Fexample%22%7D&start=1544040000&end=1544127300&step=900"
```
%5C is \ (backslash)
So it seems some incorrect escaping is happening somewhere, which then ends up in the URL, making it incorrect.

**Comment by torkelo** [comment]
Grafana will use regex escaping, so probe_success{instance=~"$host"} should work, or probe_success{instance="${host:raw}"}
