### ISSUE TITLE
Templating init failed,Datasource named Prometheus was not found

### ISSUE THREAD

**Issue by simpson9527** [grafana/grafana#14380]
when i added the data-sources of prometheus
![image](https://user-images.githubusercontent.com/30716233/49641728-f84bab80-fa4b-11e8-9069-6fd8f97a4b3a.png)
tested the data-source also ok
![image](https://user-images.githubusercontent.com/30716233/49641782-1fa27880-fa4c-11e8-8b76-3de1add679c0.png)

but when i select the dash-bord,an error occured
![image](https://user-images.githubusercontent.com/30716233/49641638-b458a680-fa4b-11e8-86a2-54cc47b49026.png)

**Comment by marefr** [comment]
Your datasource is named prometheus and not Prometheus - notice the casing.
