### ISSUE TITLE
Impossible to sort raw_document with elasticserch datasource

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#14387]
### What Grafana version are you using?
> 5.2.3
### What datasource are you using?
> Elasticsearch
### What OS are you running grafana on?
> Linux server + Windows client
### What did you do?

I store some slow query logs (via logstash) in elasticsearch.
I have a dashboard table panel based on a raw_document elasticsearch query but when I sort by a numerical column it doesnt' work

![image](https://user-images.githubusercontent.com/6534850/49647351-7eeb9300-fa22-11e8-91ce-57816b6275ec.png)

As you can see, **1.31M** is lower ranked than **359.21K**

When I check the query inspector it tells:

![image](https://user-images.githubusercontent.com/6534850/49647408-b8bc9980-fa22-11e8-927f-ba6bbaa26703.png)

Despite I clicked on `query_rows_eximaned` you can see notice a 

`"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"fields":["*","_source"],"script_fields":{},"fielddata_fields":["@timestamp"]}`

Is it a normal behaviour? could we remove the default timestamp sorting?

**Comment by torkelo** [comment]
fixed in v5.3+
https://github.com/grafana/grafana/pull/12362
