### ISSUE TITLE
"Could not find query part column" InfluxDB error

### ISSUE THREAD

**Issue by 423967mv** [grafana/grafana#14394]
### What Grafana version are you using?
Grafana v5.4.0

### What datasource are you using?
InfluxDB v1.7.1

### What OS are you running grafana on?
Ubuntu 14.04.5 LTS

### What did you do?
I added an InfluxDB datasource using following settings:
![image](https://user-images.githubusercontent.com/10938112/49659537-c97e0700-fa44-11e8-909b-db17afb176e7.png)

After clicking "Save & Test" it shows "Data source is working".

### What was the expected result?
Selectable metrics in the graph edit view.

### What happened instead?
Grafana shows this piece of code:
`{{ctrl.target.refId}} ({{ctrl.target.datasource}})`

![image](https://user-images.githubusercontent.com/10938112/49659704-1661dd80-fa45-11e8-9678-92f5a87f5f84.png)

Pressing the Query Inspector shows an ongoing spinner (never stops):
![image](https://user-images.githubusercontent.com/10938112/49659859-6a6cc200-fa45-11e8-9d65-121f8817638b.png)

On the dashboard the following error message is shown:
![image](https://user-images.githubusercontent.com/10938112/49659955-aef85d80-fa45-11e8-852f-dfd4945e3a64.png)

Grafana and InfluxDB are running on the same Ubuntu server and the Influx data looks fine in the CLI.
(The data used to generate the MySQL-graph in the panel below also originates from the same server I'm testing both DBMS in Grafana. )

**Comment by torkelo** [comment]
Do your changing an existing mysql graph to an influxdb graph? Try removing the queries before changing datasource type.

**Comment by 423967mv** [comment]
No I'm testing both DBMS in Grafana, each in their respective panel, MySQL works fine but InfluxDB doesn't. There are no queries in the "Influx panel" because Grafana doesn't allow me and shows me that piece of code instead.

**Comment by torkelo** [comment]
What does the browser error console say?

**Comment by torkelo** [comment]
So when you get this error you get this on completely new panels?

**Comment by 423967mv** [comment]
The console shows this:

![image](https://user-images.githubusercontent.com/10938112/49685203-bcfabc80-fadf-11e8-8390-f9f40875eb58.png)

Meanwhile I found that this only happens using MySQL and InfluxDB in the same dashboard. When I create a new dashboard it works.

![image](https://user-images.githubusercontent.com/10938112/49685315-eb799700-fae1-11e8-98a4-ca23079a68f1.png)

**Comment by joshhopkins** [comment]
I'm also getting this with InfluxDB data source, after using Postgres data source.
