### ISSUE TITLE
Allow Graphite functions to be used Templating Variable values query

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1439]
As of 1.9.1 the value in the Templating variable values query appear to only accept wildcard strings and not Graphite functions.  If it could accept functions it would open up new capabilities such as: exclude(servers*.instance*.threads.busy,"server02")
grep(servers*.instance*.threads.busy,"server02")

or maybe even
highestAverage(server*.instance*.threads.busy,5)

Maybe the user would also need to wrap with an aliasByNode or aliasByMetric to get a short name as you get today. It could also remove the need for the current regex field.

**Comment by torkelo** [comment]
@maddenca this is not possible in the graphite metric query find api on in the render api

**Comment by maddenca** [comment]
I suppose we could use the render api and discard the values.  I'm not sure if that has other advantages/disadvantages, but it would give us uber control about the instance list
