### ISSUE TITLE
Explore: Jumping to Explore keeps target options like labelFormat

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14393]
1. Prometheus datasource, Explore enabled
1. Create dashboard panel with prometheus query `promhttp_metric_handler_requests_total`
1. Set a label format: `{{code}}`
1. Notice the nicely formatted legend labels
1. Jump to Explore via the panel menu
1. Notice how the formatted labels are preserved
1. Change query to `up`

Result: legend label is now `code`, which makes no sense.

**Comment by peterholmberg** [comment]
removing needs investigation since there seems to be a PR for this.
