### ISSUE TITLE
[Bug Report] Query switch to "toggle edit mode" without notice

### ISSUE THREAD

**Issue by jeanduporte** [grafana/grafana#14419]
Hi,

I got a little bug on my dashboard. I'm doing some template for my dashboard but in the queries I have to not select a metric for the moment. Sometimes when I put an alias to the query and go away from the dashboard when I come back the query switched to "Toggle Edit Mode" and it is impossible to switch to "Automatic Mode".

Is there anything that I'm doing wrong or is it a bug?

Here is an example:
<img width="1233" alt="capture d ecran 2018-12-10 a 10 01 33" src="https://user-images.githubusercontent.com/28293036/49721566-d11af700-fc62-11e8-906c-e2ec88c60f00.png">

Then when I put an alias and come back to the dashboard, the query is like that and impossible to switch from the Toggle Edit Mode:
<img width="1233" alt="capture d ecran 2018-12-10 a 10 02 14" src="https://user-images.githubusercontent.com/28293036/49721669-20f9be00-fc63-11e8-8a7a-12e20a580d8b.png">

**Comment by torkelo** [comment]
the variables are not matching a real metric, so you have a "select metric" part the end. Remove that part in the manual mode, then you might be able to switch to editor mode again

**Comment by jeanduporte** [comment]
Thank you!
