### ISSUE TITLE
Prometheus Timezone  issue

### ISSUE THREAD

**Issue by dominicqi** [grafana/grafana#14415]
https://github.com/grafana/grafana/blob/1f7fece802ac3aedf0a87ddbe7fe757fc01f8e83/public/app/plugins/datasource/prometheus/datasource.ts#L17

I'm in Shanghai, China。when i use graph panel step is 1d  .this function will query data from yesterday 8AM to today 8AM. i think this function should consider timezone from dashbord setting.

**Comment by torkelo** [comment]
not sure this is correct, alignRange will only align based on the step size. there is nothing timezone related here
