### ISSUE TITLE
CSRF Token validation for POSTs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1441]

**Comment by jmcarp** [comment]
Is this open for contribution? I'd be happy to send in a patch if so.

**Comment by torkelo** [comment]
That would be great

**Comment by Cbryndum** [comment]
Just as an FYI the NVD raised the base score of this type of vuln to 7.5.
https://nvd.nist.gov/vuln-metrics/cvss/v2-calculator?version=2&vector=(AV:N/AC:L/Au:N/C:P/I:P/A:P/E:U/RL:OF/RC:C)

**Comment by vdravid** [comment]
Hi @torkelo We are very happy to use grafana as our dashboard. While this issue is being incorporated, is there any other to mitigate CSRF with grafana ? I tried to look through the available documentation and configuration options for 4.4.0 and this issue is the one which I could find.

**Comment by hiscal2015** [comment]
+ 1, any progress on this?

**Comment by reddyalready** [comment]
What does this need? Is there a CSRF token generated anywhere and simply not validated or does it need creation of the token as well?

**Comment by torkelo** [comment]
We need to generate the token as well.

**Comment by reddyalready** [comment]
Ok, thanks, and how does Grafana persist data? We would want to persist the token I assume because otherwise they're lost on server reboot/clustering scenarios.

**Comment by torkelo** [comment]
it does not need to be persisted I think, only signed

**Comment by torkelo** [comment]
and it can be stored in a cookie

**Comment by torkelo** [comment]
not sure what the current best practice for CRSF tokens are right now, was 5 years since I worked on on such a feature. I know that there is a new browser feature that does this protection for your now but it is not yet wildly supported.

**Comment by marefr** [comment]
@torkelo Seems like `SameSite` cookie attribute could be used for solving this problem. [OWASP](https://www.owasp.org/index.php/SameSite)

**Comment by torkelo** [comment]
sort of, the browser support is not great. At least when I last checked. Looks better now:
https://caniuse.com/#feat=same-site-cookie-attribute

**Comment by marefr** [comment]
Yes. This cookie setting came up during auth token work and there's a PR open right now

**Comment by marefr** [comment]
Fixed by #15191 basically using the SameSite cookie attribute
