### ISSUE TITLE
The chinamap panel plugin for grafana

### ISSUE THREAD

**Issue by sunnut** [grafana/grafana#14418]
Github: [grafana-chinamap-plugin](https://github.com/sunnut/grafana-chinamap-panel)

## Examples
![Screenshot](https://github.com/sunnut/grafana-chinamap-panel/blob/master/img/map-ex1.png?raw=true "China")

**Comment by torkelo** [comment]
Nice! 

Closing this as we do not add community plugins to core grafana but add them to: https://github.com/grafana/grafana-plugin-repository

**Comment by daniellee** [comment]
Hi @sunnut 

Can you open a PR in the plugins repo instead as Torkel says. 

Also before you submit the PR, can you change the plugin id to sunnut-chinamap-panel in the [plugin.json](https://github.com/sunnut/grafana-chinamap-panel/blob/master/src/plugin.json#L4).

Plugin review guidelines: http://docs.grafana.org/plugins/developing/plugin-review-guidelines/#plugin-json
