### ISSUE TITLE
Update dashboard link when templating variable changes

### ISSUE THREAD

**Issue by renatoram** [grafana/grafana#14420]
Hi, 
I'm trying Dashboard Links, and for our use-case it would be very useful if the link name/target URL could be templated like the rest of the dashboard.

For example, it could contain a variable (and this already works, with the [[ ]] syntax), and when the variable changes upon user selection of a new value, the link should update. 

This would allow for example:
* Linking to an external resource using the variable value as part of the url/query string
* Manipulating a variable (for example with a regexp), then using THAT new value as part of the url

My setup:
* Grafana 5.4.0-1
* RedHat Enterprise Linux 7.4
* Zabbix datasource

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
