### ISSUE TITLE
Filtering tag names broken in dashboard search

### ISSUE THREAD

**Issue by cdanis** [grafana/grafana#14437]
### What Grafana version are you using?
5.4.0; also reproducible on play.grafana.org
### What datasource are you using?
Prometheus and Graphite; also reproducible on play.grafana.org
### What OS are you running grafana on?
Debian Stretch; also reproducible on play.grafana.org
### What did you do?
Attempted to type a tag name into the "Filter by" "Tags" dropdown
### What was the expected result?
Typing in a tag name or substring should cause the list of tags to be filtered.
### What happened instead?
Typing tag names into the dropdown does not affect anything.

Here is a screen recording showing my browser version and also the bug behavior on play.grafana.org:
https://giant.gfycat.com/EasyVapidAfricanmolesnake.webm

I did not see any errors in the browser JS console when reproducing this.

**Comment by cdanis** [comment]
I just saw in the 5.4.1 release notes: "Dashboard Search: Fixed filtering by tag issues."

I will try that version on my install.

**Comment by cdanis** [comment]
Okay, re-tested on my install of 5.4.1.

Clicking on a tag name displayed in the list of dashboards works now.

However, typing in the tag filter dropdown box still does not cause anything to happen.

**Comment by torkelo** [comment]
Typing? The list of tags does not filter , or you can’t select tag

**Comment by daniellee** [comment]
The list of tags does not filter:

![image](https://user-images.githubusercontent.com/434655/49791817-861be500-fd31-11e8-83c3-77b89e06848a.png)
