### ISSUE TITLE
Unable to set auth.oauth_auto_login via environment variable

### ISSUE THREAD

**Issue by sbrandtb** [grafana/grafana#14435]
### What Grafana version are you using?
5.4.{0,1}

### What OS are you running grafana on?
Official Docker image on Kubernetes

### What did you do?
Set environment variable `GF_AUTH_OAUTH_AUTO_LOGIN` to `true`.

### What was the expected result?
* Grafana redirects to our oauth provider instead of the login page.
* Admin settings panel shows `true` for the variable auth -> `oauth_auto_login`

### What happened instead?
* Grafana still shows login page
* Admin settings panel shows `false`

### Further information
We are configuring all other settings with environment variables as well and it works, e.g. for SMTP from address:

```console
~ $ kubectl exec -it grafana-55c76cbf79-lhj6r -- sh -c 'echo $GF_SMTP_FROM_ADDRESS'
admin@forfriday.de
~ $ kubectl exec -it grafana-55c76cbf79-lhj6r -- sh -c 'echo $GF_AUTH_OAUTH_AUTO_LOGIN'
true
```

Judging from the code in #12029 I don't see a reason why this would not work (because it's using the standard settings constructor) and no reason why the code should switch the setting to `false` due to side conditions, so I would expect that it shows `true` under any circumstances.

**Comment by torkelo** [comment]
Thanks for reporting this, classic mistake on our end, forgot to add this setting to the defaults file
