### ISSUE TITLE
Grafana LDAP authentication against IPA fails

### ISSUE THREAD

**Issue by jarttori** [grafana/grafana#14432]
### What Grafana version are you using?
grafana-5.3.0

### What datasource are you using?
Irrelevant

### What OS are you running grafana on?
Red Hat Enterprise Linux Server release 7.5 (Maipo)

### What did you do?
Update IPA from 4.5.4 -> 4.6.4

### What was the expected result?
LDAP authentication would proceed as normal

### What happened instead?
Trying to authenticate via LDAP:

```lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 2 \"Protocol Error\": "```

Search request seen from IPA:

```
[05/Dec/2018:10:50:10.160459643 +0200] conn=84119 fd=338 slot=338 SSL connection from XXX.XX.X.XXX to XXX.XX.X.XXX
[05/Dec/2018:10:50:10.165958341 +0200] conn=84119 TLS1.2 256-bit AES-GCM
[05/Dec/2018:10:50:10.167109254 +0200] conn=84119 op=0 BIND dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd" method=128 version=3
[05/Dec/2018:10:50:10.167750466 +0200] conn=84119 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0007013470 dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
[05/Dec/2018:10:50:10.168907397 +0200] conn=84119 op=1 SRCH base="(null)" scope=2 asdlter="(uid=asdf)", invalid attribute request
[05/Dec/2018:10:50:10.168943337 +0200] conn=84119 op=1 RESULT err=2 tag=101 nentries=0 etime=0.0000119809
[05/Dec/2018:10:50:10.170213905 +0200] conn=84119 op=-1 fd=338 closed - B1
```

As you can see SRCH base is null. Debuggin tcpdump and testing ldap authentication. Bind works fine but search gives out null

grafana:

```
30 76 02 01 02 63 71 04
```

go-ldap (5.3.0 source code) / perl(Net::LDAP) / python(ldap), these are working:

```
30 78 02 01 02 63 73 04
```

As you can see 2nd and 7th bytes from hexa differ from other requests. Maybe grafana LDAP implementation is adding/modifying something to the request?

From go-ldap it seems this block is responsible for the search requests, which seems to be failing in grafana:

```
searchRequest := NewSearchRequest(
"dc=example,dc=com", // The base dn to search
ScopeWholeSubtree, NeverDerefAliases, 0, 0, false,
"(&(objectClass=organizationalPerson))", // The filter to apply
[]string{"dn", "cn"}, // A list attributes to retrieve
nil,
)
```

Grafana:

```
func (a *ldapAuther) searchForUser(username string) (*LdapUserInfo, error) {
var searchResult *ldap.SearchResult
var err error

for _, searchBase := range a.server.SearchBaseDNs {
searchReq := ldap.SearchRequest{
BaseDN: searchBase,
Scope: ldap.ScopeWholeSubtree,
DerefAliases: ldap.NeverDerefAliases,
Attributes: []string{
a.server.Attr.Username,
a.server.Attr.Surname,
a.server.Attr.Email,
a.server.Attr.Name,
a.server.Attr.MemberOf,
},
Filter: strings.Replace(a.server.SearchFilter, "%s", ldap.EscapeFilter(username), -1),
}
```

From LDAP error codes:

==============================
‣2 
‣ LDAP_PROTOCOL_ERROR 
‣ Indicates that the server has received an invalid or malformed request from the client.
\==============================

ldap.toml:

```
verbose_logging = true

[[servers]]
host = "foobar.asd.asd.asd"
port = 389
use_ssl = false
ssl_skip_verify = true

# Search user bind dn
bind_dn = "uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
bind_password = 'asd'

search_filter = "(uid=%s)"
search_base_dns = ["cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"]

[servers.attributes]
name = "displayName"
username = "uid"
member_of = "memberOf"

[[servers.group_mappings]]
group_dn = "cn=sw_perfdb_grafana_admins_asd,cn=groups,cn=accounts,dc=asd,dc=asd,dc=asd"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
```

**Comment by jarttori** [comment]
https://pagure.io/389-ds-base/issue/49969 maybe related?

**Comment by daniellee** [comment]
Did this LDAP config work with IPA v4.5.4 and then broke after upgrading IPA? Or was it an upgrade of Grafana that caused the problem?

I don't know much about IPA/FreeIPA so investigating if there are any differences in the syntax or if it is something we are doing with go-ldap that is the problem.

**Comment by jarttori** [comment]
Yes, this config worked with IPA 4.5.4 (and still works, we got another cluster using the earlier version) and broke after upgrading IPA, this isn't an issue of the configuration of the ldap.toml.

Testing the ldap with the underlying go-ldap and various other languages works, so the issue shouldn't be with the IPA either.

What we suspect is that some variable/class is messing the encoding (asn1) the message to binary and thus making the search request malformed.

This is correct one:

```
Extended Response Protocol Op
    01111000     0x78
Search Result Reference Protocol Op
    01110011     0x73
```

Grafana is sending this:

```
Search Result Reference Protocol Op
0111 0110    0x76
Search Result Reference Protocol Op
0111 0001 0x71
```

Checking release notes from IPA v4.6.4 we found out atleast one item which could have caused this, which was linked, basically to deny malformed request or order to protect IPA from DOS attack.

**Comment by daniellee** [comment]
Wonder if it might be this, I think we always send an empty array of Controls: 

https://github.com/go-ldap/ldap/issues/162#issuecomment-389100477

It is fixed in the v3 of go-ldap which has just recently been released (which we have been waiting for). Upgrading to v3 might fix your issue.

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/issues/14548

**Comment by daniellee** [comment]
@jarttori can you test against the nightly build of Grafana (otherwise you will have to wait until the next major release of Grafana)? Not 100% sure it fixes your issue but hopefully.

**Comment by jarttori** [comment]
@daniellee i'll try to dedicate some time for it.

**Comment by jarttori** [comment]
Tested against 
```
[root@perffev01t gtenauja]# grafana-server -v
Version 5.5.0-pre1 (commit: b798a54, branch: master)
```

Still gives the same error
```
Dec 27 16:35:42 perffev01t grafana-server: t=2018-12-27T16:35:42+0200 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 2 \"Protocol Error\": "
```

IPA
```
[27/Dec/2018:16:38:15.727533829 +0200] conn=2177713 fd=279 slot=279 connection from asd.asd.asd.asd to asd.asd.asd.asd
[27/Dec/2018:16:38:15.728143523 +0200] conn=2177713 op=0 BIND dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd" method=128 version=3
[27/Dec/2018:16:38:15.728821418 +0200] conn=2177713 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0000994572 dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
[27/Dec/2018:16:38:15.730196410 +0200] conn=2177713 op=1 SRCH base="(null)" scope=2 filter="(uid=gtenauja)", invalid attribute request
[27/Dec/2018:16:38:15.730223666 +0200] conn=2177713 op=1 RESULT err=2 tag=101 nentries=0 etime=0.0000101198
[27/Dec/2018:16:38:15.733942535 +0200] conn=2177713 op=-1 fd=279 closed - B1
```

tcpdump:
```
0x0040:  bb11 3076 0201 0263 7104 2d63 6e3d 7573  ..0v...cq.-cn=us
```

Still sending same malformed request 30 76 0201 0263 7104

**Comment by daniellee** [comment]
@jarttori I'm stuck with this one. This is not an obvious bug for me as it seems to work fine with openldap. 

I don't understand how `SRCH base="(null)" scope=2 filter="(uid=gtenauja)"` can have a null base. The base variable should come from the `search_base_dns` setting in your toml file.

The only issue I could find that seems similar is this and that might give a clue is: https://github.com/nextcloud/server/issues/12086

It is fully possible that Grafana [sends empty attributes](https://github.com/grafana/grafana/blob/master/pkg/login/ldap.go#L280-L303).

I have added a debug statement for the ldap search request: ce50e9331ab50d2a1946e3f4a95287c7a1989621

Can you test again with the latest nightly build of Grafana with the log level set to `ldap:debug` in your ini file:

```ini
[log]
mode = console
filters = ldap:debug
```

**Comment by jarttori** [comment]
@daniellee Sorry for the delay, I was on vacation.

Here's the debug, failing with the same error:

```Jan  7 10:31:19 perffev01t grafana-server: t=2019-01-07T10:31:19+0200 lvl=dbug msg="Ldap Search For User Request" logger=ldap info="(ldap.SearchRequest) {\n BaseDN: (string) (len=45) \"cn=users,cn=accounts,dc=asd,dc=asd,dc=asd\",\n Scope: (int) 2,\n DerefAliases: (int) 0,\n SizeLimit: (int) 0,\n TimeLimit: (int) 0,\n TypesOnly: (bool) false,\n Filter: (string) (len=14) \"(uid=gtenauja)\",\n Attributes: ([]string) (len=5 cap=5) {\n  (string) (len=3) \"uid\",\n  (string) \"\",\n  (string) \"\",\n  (string) (len=11) \"displayName\",\n  (string) (len=8) \"memberOf\"\n },\n Controls: ([]ldap.Control) <nil>\n}\n"
```

**Comment by jarttori** [comment]
Something funky, after messing around with the requests, I got it working with:

```
func ExampleConn_Bind() {
        l, err := ldap.Dial("tcp", fmt.Sprintf("%s:%d", "asdasd", 389))
        if err != nil {
                log.Fatal(err)
        }
        defer l.Close()

        err = l.Bind("uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd", "asdasd")
        if err != nil {
                log.Fatal(err)
        }
                //      searchRequest := ldap.NewSearchRequest(
                // "cn=users,cn=accounts,dc=asd,dc=asd,dc=asd",
                // ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
                // "(uid=gtenauja)",
                // []string{"uid", " ", " ", "displayName", "memberOf"},
                // nil,
                searchBase := "cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
                username := "gtenauja"
                Username := "uid"
                //Surname := ""
                Email := ""
                Name := "displayName"
                MemberOf := "memberOf"
                SearchFilter := "(uid=username)"
                searchReq := ldap.SearchRequest{
                        BaseDN:       searchBase,
                        Scope:        ldap.ScopeWholeSubtree,
                        DerefAliases: ldap.NeverDerefAliases,
                        Attributes: []string{
                                Username,
                //              Surname,
                                Email,
                                Name,
                                MemberOf,
                        },
                        Filter: strings.Replace(SearchFilter, "%s", ldap.EscapeFilter(username), -1),
                }
         fmt.Println(searchReq)

        sr, err := l.Search(&searchReq)
        if err != nil {
                log.Fatal(err)
        }
```

As you can see I only removed Surname from the attribute field:

```
[root@dnsv02t ~]# go run testildap.go 
{cn=users,cn=accounts,dc=asd,dc=asd,dc=asd 2 0 0 0 false (uid=gtenauja) [uid  displayName memberOf] []}
uid: gtenauja
cn=admins,cn=groups,cn=accounts,dc=asd,dc=asd,dc=asd
```

From IPA:

```
[07/Jan/2019:18:28:01.445831394 +0200] conn=3212186 fd=227 slot=227 connection from asdasd to asdasd
[07/Jan/2019:18:28:01.446317430 +0200] conn=3212186 op=0 BIND dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd" method=128 version=3
[07/Jan/2019:18:28:01.447018125 +0200] conn=3212186 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0000958548 dn="uid=readgroup,cn=users,cn=accounts,dc=asd,dc=asd,dc=asd"
[07/Jan/2019:18:28:01.448601446 +0200] conn=3212186 op=1 SRCH base="cn=users,cn=accounts,dc=asd,dc=asd,dc=asd" scope=2 filter="(uid=gtenauja)" attrs="uid  displayName memberOf"
[07/Jan/2019:18:28:01.449629158 +0200] conn=3212186 op=1 RESULT err=0 tag=101 nentries=1 etime=0.0001091756
[07/Jan/2019:18:28:01.457722444 +0200] conn=3212186 op=-1 fd=227 closed - B1
```

It didn't actually matter which attribute field I removed, it still worked. However the hexa code is still wrong:

```
0x0040:  e0ba 3074 0201 0263 6f04 2d63 6e3d 7573

3074 0201 0263 6f04
```

**Comment by daniellee** [comment]
Ha, just saw your comment now. Not sure why it is ok to send one empty attribute but not two. But I think it is connected to that IPA security fix that you linked to earlier.

**Comment by jarttori** [comment]
I can confirm, after adding "email" to server.attributes, the ldap authentication works.
