### ISSUE TITLE
Graph disappears after setting time($__interval) in group by clause

### ISSUE THREAD

**Issue by 423967mv** [grafana/grafana#14430]
### What Grafana version are you using?
Grafana v5.4.0

### What datasource are you using?
InfluxDB v1.7.1

### What OS are you running grafana on?
Ubuntu 14.04.5 LTS

### What did you do?
Added a time interval in the group by clause. ($__interval variable)

### What was the expected result?
A reduced number of data points in the graph.

### What happened instead?
The graph disappeared.

![image](https://user-images.githubusercontent.com/10938112/49735465-8fe90e00-fc87-11e8-8150-aaca3c3769d8.png)

![image](https://user-images.githubusercontent.com/10938112/49735908-df7c0980-fc88-11e8-9300-48472bf5fe58.png)

I tried the global setting for min time interval as wel but Grafana still uses the full (1m) resolution.

![image](https://user-images.githubusercontent.com/10938112/49735697-3f25e500-fc88-11e8-9603-9390e21a1559.png)

**Comment by torkelo** [comment]
you need a aggregation function in select clause when you have a group by clause. (for example max or sum function)
