### ISSUE TITLE
Text editor should wrap 

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#14442]
### What Grafana version are you using?

5.0.0. Issue can be reproduced at https://play.grafana.org and at https://grafana.wikimedia.org/.

This is a regression from Grafana v4.

### What did you do?

Edit a text panel.

### What was the expected result?

The user should be able to see all text that is rendered in the editable content area.

### What happened instead?

Each paragraph is squished onto a single line, requiring vertical panning to find a word, which is highly unusual. I assume this is unintentional.

![capture](https://user-images.githubusercontent.com/156867/49769177-1973fc80-fcd7-11e8-9c76-ddfb0605c4d9.png)

**Comment by daniellee** [comment]
It looks like it wraps now so closing this issue.
