### ISSUE TITLE
Explore: Logs dedup strategy is not included in url state

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14445]
When refreshing page or sending link the dedup strategy option is lost.

**Comment by dprokop** [comment]
Is it only dedup strategy that should be persisted in URL? What about timnestam, labels and local time switch values?

**Comment by davkal** [comment]
#13852 is relevant too, and possibly more important. But the mechanism should be versatile enough to accommodate ExploreItem-wide state, as well as result panel specific state (eg. Logs dedup strategy)
