### ISSUE TITLE
Row name renders with incorrect variable value

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#14443]
### What Grafana version are you using?

v5.0.0. Reproducible at https://play.grafana.org/ and https://grafana.wikimedia.org/.

This is a **regression** from Grafana v4.

### What did you do?

Click on a variable and change its value.

### What was the expected result?

All places that depend on the variable should update. In particular: Row titles and panel titles.
 
### What happened instead?

From what I can see most things update, but as of Grafana 5, the row title is broken. It only changes after manually collapsing and re-expanding the row (which forces a re-render).

In Chrome at <https://play.grafana.org/d/000000153/repeat-rows>, it initially shows variable "server" set to "backend_01 + backend_02", and shows two rows:  "backend_01 - sub" and "backend_01 - sub".

When choosing a different the "server" option (e.g. "webserver_01" only), the panel updates, but the row remains titles "backend_01 - sub".

![capture](https://user-images.githubusercontent.com/156867/49772928-f6e9df80-fce6-11e8-863b-541dbe3dea5f.png)

**Comment by Zauxst** [comment]
I have the same issue ever since I've upgraded to version 5.4.0.
**Current Version:**  Grafana v5.4.1 (commit: 308c818)

I have a row which repeats depending on a Prometheus label.
Only the first row does not change, the row does display the correct information.
 
**If I refresh the page then everything is fine.** The row will update.

**Comment by cbonte** [comment]
Still true in 5.4.4.
Toggling/Untoggling the first row will update the title to the correct value.

From what I observe, updating a variable :

1. calls `dashboard.startRefresh()` (https://github.com/grafana/grafana/blob/v5.4.x/public/app/features/templating/variable_srv.ts#L136)
2. which performs a `panel.refresh()` (https://github.com/grafana/grafana/blob/v5.4.x/public/app/features/dashboard/dashboard_model.ts#L212)

while toggling/untoggling will result in a `render()` call, which also recompute the row title (https://github.com/grafana/grafana/blob/v5.4.x/public/app/features/dashboard/dashgrid/DashboardRow.tsx#L77)

**Comment by torkelo** [comment]
is fixed in later versions of grafana (v6 or v6.1)

**Comment by cbonte** [comment]
> is fixed in later versions of grafana (v6 or v6.1)

Indeed! So, should the issue be closed with a **wontfix** status for grafana <= 5.4.x and **fixed** in grafana >= 6.x (any version to tag as a fix ?)

**Comment by torkelo** [comment]
Ah, sorry should be closed.
