### ISSUE TITLE
Clarify elastic search annotations usage

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#1444]
From the documentation (_If your elasticsearch document has a timestamp field other than @timestamp you will need to specify that._), I understood that you do not need to specify anything, if you stick to the default @timestamp field name.

![elastic search annotations](https://cloud.githubusercontent.com/assets/8266640/6105641/24c1f62a-b062-11e4-9f66-d6f60c08711a.PNG)

This is the wrong conclusion, @timestamp must be specified. I can see how this might be obvious to others given the final sentence. _Tags and text are optional_, implying timestamp is not optional. 

However, I still believe this sentence would be clearer if it were reworded as:

"Specify the timesamp field name for your elasticsearch document (if your data comes from logstash, this should be @timestamp). "

**Comment by torkelo** [comment]
This was a bug, the default value was not applied correctly

**Comment by torkelo** [comment]
Oh, and thanks for reporting this!
