### ISSUE TITLE
[Feature request] Null as zero on alerts

### ISSUE THREAD

**Issue by gaizeror** [grafana/grafana#14458]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.4.1
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
CentOS7
### What did you do?
Tried to add alert with null values expected
### What was the expected result?
Treat null as zero at alerts
### What happened instead?
Null values wasn't taken in consideration when Grafana calculated the alert result.
### If related to metric query / data viz:
`((rabbitmq_queue_messages{job="rabbitmq_exporter"} > 0 and on(queue, instance) (rate(rabbitmq_queue_messages_delivered_total [1m]) == 0) and on(queue, instance) rate(rabbitmq_queue_messages_ack_total [1m]) == 0))`

The query checks if there is a queue with more than 1 message, and in addition, there was no deliverd/acknowledged task for the last 1 minutes.

I want the alert to fire when there is a result for X minutes, The problem is that the query in a good state returns null value, when configuring AVG/MIN alert, I get too many false positive alarms because the AVG/min of any number with null, is the number.

![screen shot 2018-12-12 at 9 45 58](https://user-images.githubusercontent.com/18627927/49854445-d4dd8380-fdf2-11e8-982f-3c0cd1ec6261.png)

For example, in such query (image above), the result of AVG/MIN over 5 minutes, with and without the new FOR function, is 6 (the query result), but I want to check if its consistent over the 5 minutes, so "Null As Zero" on the alert configuration will solve it.

Hope to see that feature soon

**Comment by bergquist** [comment]
There are two ways to solve this with grafanas alerting.

1) Add a second condition with `count_non_null` > x. Making sure there are at least x datapoints in the timerange.
2) Use `sum` > x. Checking the total sum during the duration

Another idea would be to use `count()` in promql to count the number of series with more then one message. 

Im closing this issue but if neither solution works for you Im happy to reopen it
