### ISSUE TITLE
Grafana Dashboard Alias patterns $tag_yourTagName not working for CloudWatch plugin tag yourTagName="db_instance_identifier"

### ISSUE THREAD

**Issue by XQZ-Bitglass** [grafana/grafana#14454]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
$ grafana-server -v
Version 5.4.0 (commit: 69c5191, branch: HEAD)

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
$ uname -vrio
3.13.0-158-generic #208-Ubuntu SMP Fri Aug 24 17:07:38 UTC 2018 x86_64 GNU/Linux

### What did you do?
Using Telegraf cloudwatch plugin to pull metrics from AWS:

[[inputs.cloudwatch]]
    region = "us-west-2"

    period = "1m"
    delay = "1m"
    interval = "1m"
    namespace = "AWS/RDS"
    ratelimit = 200

[[inputs.cloudwatch.metrics]]
   names = ["WriteThroughput","DatabaseConnections","ReadThroughput","WriteLatency","SwapUsage","BurstBalance","FreeStorageSpace","CPUUtilization","FreeableMemory","NetworkTransmitThroughput","ReadLatency","ReadIOPS","DiskQueueDepth","BinLogDiskUsage","WriteIOPS","CPUCreditUsage","CPUCreditBalance","NetworkReceiveThroughput"]

  [[inputs.cloudwatch.metrics.dimensions]]
     name = "DBInstanceIdentifier"
     value = "*"

### What was the expected result?
** Report metrics say "CPUUtilization", "DatabaseConnections" as graphs/charts in Grafana dashboard. 
** AWS/RDS instances Metrics data was pulled from AWS into InfluxDB as:
>>
> SELECT cpu_utilization_sum, database_connections_sum,  db_instance_identifier   FROM "cloudwatch_aws_rds"   order by time DESC  limit 4
name: cloudwatch_aws_rds
time                 cpu_utilization_sum database_connections_sum db_instance_identifier
----                 ------------------- ------------------------ ----------------------
2018-12-11T22:22:00Z 7.16666666674428                             AWS-RDS-db1
2018-12-11T22:22:00Z                     491                                     AWS-RDS-db1
2018-12-11T22:22:00Z 0.604166666665454                            AWS-RDS-db2
2018-12-11T22:22:00Z                     87                       AWS-RDS-db2
>>>>>  So far so god.

** Dashboard query as:
>>
SELECT mean("database_connections_sum") as Avg_Conn FROM "cloudwatch_aws_rds" WHERE  ("db_instance_identifier" =~ /^$server$/ )  AND $timeFilter GROUP BY time(1m)  fill(null)

"ALIAS BY $tag_db_instance_identifier: $col"

>>>>> Got data from the query

** According to influxdb measurement cloudwatch_aws_rds",  that "db_instance_identifier" is tag key
> show tag keys from cloudwatch_aws_rds
name: cloudwatch_aws_rds
tagKey
------
db_instance_identifier
host
region
unit

** Expect:  "ALIAS BY $tag_db_instance_identifier: $col"  should report the multiple charts/graphs based on each "db_instance_identifier" values, but only one chart/graph was displayed in Grafana Dashboard  

### What happened instead?
** Expect:  "ALIAS BY $tag_db_instance_identifier: $col"  should report the multiple charts/graphs based on each "db_instance_identifier" values, but only one chart/graph was displayed in Grafana Dashboard. See screen snapshot for detail:

<img width="1056" alt="screen shot 2018-12-11 at 2 28 47 pm" src="https://user-images.githubusercontent.com/45802961/49835504-40244880-fd54-11e8-935d-1a72cb952013.png">

**Comment by XQZ-Bitglass** [comment]
$server=SHOW TAG VALUES FROM cloudwatch_aws_rds WITH KEY=db_instance_identifier, the results:
> SHOW TAG VALUES FROM cloudwatch_aws_rds WITH KEY=db_instance_identifier
name: cloudwatch_aws_rds
key                    value
---                    -----
db_instance_identifier   AWS_RDS_DB1
db_instance_identifier   AWS_RDS_DB2

**Comment by daniellee** [comment]
`db_instance_identifier is not in your group by` so there is no tag for Grafana to interpolate in the alias by field. 

Your query should be:

```sql
SELECT mean("database_connections_sum") as Avg_Conn FROM "cloudwatch_aws_rds" WHERE ("db_instance_identifier" =~ /^$server$/ ) AND $timeFilter GROUP BY time(1m), "db_instance_identifier" fill(null)
```
