### ISSUE TITLE
Playlist name can be viewed by any user/group

### ISSUE THREAD

**Issue by coelh0** [grafana/grafana#14469]
hello, an admin user assigned to a team just created a playlist selecting graphics from his team. Other users outside the team (other groups / teams) can read the playlist name created by this administrator. We separate the projects by companies, so one company can not see the other's IDs (data is protected, but the name of the playlist is viewed by all). Is it possible to create a playlist filter for groups / teams?

Please include this information:
What Grafana version are you using? -- 5.2.2
What datasource are you using? -- Cloudwatch/Zabbix
What OS are you running grafana on? -- Ubuntu 4.15.0-1025-azure
What did you do? -- I have created 2 teams (companies) and 2 users (1 admin / 1 viewers) in each team.
What was the expected result? -- playlist created within a team needs to be viewed only within the team, open to other viewers only by configuration (if possible).
What happened instead? -- one of the administrators created a playlist for their own company and the user of the other company / team was able to see the name of that playlist.

**Comment by torkelo** [comment]
Yes, playlist are global (per org level) so visible to all users in one org. 

If you need to isolate playlist you need to use multiple Grafana organizations. 

We hope to add the posibility to save a playlist to an organization in the future: 
https://github.com/grafana/grafana/issues/11978

**Comment by excedra** [comment]
+1
