### ISSUE TITLE
grafana-server tcp to 52.173.36.210:443

### ISSUE THREAD

**Issue by colben** [grafana/grafana#14462]
# Environment
Running grafana-server in CentOS7.5
 
# ISSUE
Today grafana created a tcp connection to 52.173.36.210:443, is there likely someting wrong ?

**Comment by sunker** [comment]
@colben we need more details. Please respond to all of these questions:
What Grafana version are you using?
What datasource are you using?
What OS are you running grafana on?
What did you do?
What was the expected result?
What happened instead?
If related to metric query / data viz:
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by ryantxu** [comment]
just guessing... is that the the reporting to stats.grafana.org

http://docs.grafana.org/installation/configuration/#reporting-enabled
