### ISSUE TITLE
Grafana 2.0 User admin, create/edit/delete, set password

### ISSUE THREAD

**Issue by phagedorn** [grafana/grafana#1446]
Hi,
how can i set the gui password for a new user if 
```
disable_user_signup = true
```

I only see the api key:
![grafana-2 0-account-info](https://cloud.githubusercontent.com/assets/1391548/6109577/0a199674-b07c-11e4-9c40-02e7c7aa9a9c.png)

**Comment by torkelo** [comment]
Its not implemented yet, it will be a view under admin. Under Account > Users you can only add existing users to an account (IE give permissions etc). 

The user admin features are not done yet, will be top prio in the coming days/weeks. 

A temporary option is to enable user signup and disable the single account mode, then you or users themselvs can signup, they will get their own account (all dashboards, data sources, etc are tied to an account). You can then add these users to the main account with the permission you wish.

**Comment by phagedorn** [comment]
Thanks a lot :+1:

**Comment by phagedorn** [comment]
Permissions per Dashboard would be nice. 
Usecase: Each customer can only view there own dashboard.

**Comment by torkelo** [comment]
@phagedorn but if the dashboards are on the same account they will share data sources, which means they will be able to access the same data, so what is the point of them having their own dashbords? In that case they need separate accounts and data sources

**Comment by akashnimare** [comment]
@tmack0 Can you tell me how do I disable user sign up and how can I let other people view my dashboard without login?

**Comment by torkelo** [comment]
Sure! 

http://docs.grafana.org/installation/configuration/#allow_sign_up

http://docs.grafana.org/installation/configuration/#authanonymous

**Comment by akashnimare** [comment]
allow_sign_up = false
auth.anonymous=true
I want to include above settings in my grafana. Though I am using docker I
am not able to find grafana.ini . Do you have any idea where it is located?

**Comment by torkelo** [comment]
@akashnimare it is located at /etc/grafana/grafana.ini 

For docker you can also set these options using command line arguments to docker, that specifies environment variables:

```
docker run -d -p 3000:3000 \
    -v /var/lib/grafana:/var/lib/grafana \
    -e "GF_USERS_ALLOW_SIGN_UP=true  \
    -e "GF_AUTH_ANONYMOUS_ENABLED=true  \
    grafana/grafana:develop
```

**Comment by akashnimare** [comment]
No If you install grafana with docker there will not be grafana.ini.

**Comment by torkelo** [comment]
@akashnimare No??? Its should be at `/etc/grafana/grafana.ini` inside the docker container. 

But I suggest using env variables and dockers -e flag

**Comment by akashnimare** [comment]
Yeah I should use env variables.But the problem is I have run this command
sudo docker run -d -p 80:3000 \
-v /data/grafana:/var/lib/grafana \
-e "GF_SECURITY_ADMIN_USER=myuser" \
-e "GF_SECURITY_ADMIN_PASSWORD=MY_SUPER_STRONG_PASSWORD" \
--name grafana \
--restart="always" \
grafana/grafana

Now If i add this in above command

-e "GF_USERS_ALLOW_SIGN_UP=true  \
-e "GF_AUTH_ANONYMOUS_ENABLED=true  \

It throws an error saying port 3000 is already allocated. How do I
solve this problem? Should I stop the images and run it again?

**Comment by torkelo** [comment]
yes, type `docker ps` to see running docker containers. `docker kill` kills a container, `docker rm` removes a container. If you are unfamiliar with docker I suggest going through one of the getting started guides on docs.docker.com

**Comment by akashnimare** [comment]
Thanks I am able to add those new settings in grafana.
But when I login to grafana and goes to see the dashboards i.e.
http:myurl/dashboard/db/webpagetest It shows authentication required and
then I have to add the user pass again. Do you have nay idea about this
problem?
 I am attaching the error page.
