### ISSUE TITLE
[FeatureRequest] Dashboards: Add real time share instead of snapshot

### ISSUE THREAD

**Issue by vonox7** [grafana/grafana#14473]
Snapshots are great to provide a "snapshot" of a dashboard. But with the current implementation, sharing dashboards e.g. with a limited set of key customers or key partners requires regularly generate new up-to-date dashboard snapshots to include the data of the recent days.

**Grafana should have a way of creating realtime shares with live data**: The shared dashboard should have no time limit and query the data live from the datasource. Of course this only works only on datasources that have server access mode enabled to make request from the Grafana server directly. So there is no need to expose the query to the user/browser, as the Grafana server knows which queries are "shared" and which are not shared (no leak of possible sensitive data).

By sharing a read-only dashboard with an external user it would be even more ideal to create also Grafana-users that have read-only access of selected "shared" dashboard.

The following (closed and not implemented) issues also requested that use-case, but didn't show a solution as explained above to the "authentication problem": 
 * https://github.com/grafana/grafana/issues/2133: I don't see a security issue or implementation issue like discussed: The permissioning should happen inside the Grafana-server and not inside a Datasource. The query should also made from the Grafana-server, the client/browser never has to receive the query. The only thing the client can change is the time-interval.
 * https://github.com/grafana/grafana/issues/12031 (closed feature request without discussion about implementation)
 * https://github.com/grafana/grafana/issues/5547: @torkelo there stated "data is actually requested from the data source then the user will have to access the data source". I disagree with it, the data can be also be requested by the Grafana-server, the only parameter the user can change is the start/end time of the query.

**Comment by stefan-muc** [comment]
I would also like to see such a feature (and a litte bit better access rights handling in Grafana - making new dasboards viewable by every per default user is not a good security practise)!

For the time being I found a workaround using a reverse proxy like [nginx](http://nginx.org), so just in case you need that right now: https://community.grafana.com/t/how-to-make-one-live-dashboard-public/12819

**Comment by vonox7** [comment]
The proposed solution by @stefan-muc makes in fact every configured data-source in grafana publicly available. Thats exactly the security issue I described that should be mitigated by properly handling the shared dashboard logic by Grafana-server. I do not recommend to use the solution from https://community.grafana.com/t/how-to-make-one-live-dashboard-public/12819. 
Instead maybe the Grafana team could priorize this issue, as users clearly need it and start creating security loopholes in Grafana.

**Comment by torkelo** [comment]
> Of course this only works only on datasources that have server access mode enabled to make request from the Grafana server directly. So there is no need to expose the query to the user/browser, as the Grafana server knows which queries are "shared" and which are not shared (no leak of possible sensitive data).

Sadly this is not possible with how queries work. They are built dynamically by the frontend (containing dynamic parts like variables that are interpolated by the frontend). So it's close to impossible to validate the query by the server. 

To do this we would have to turn off some dynamic query features (templating) and issue queries to the backend by just specifying the dashboard & panel id. Would require a pretty major rewrite. Something we might look into someday to provide better query / data isolation and security.

**Comment by vonox7** [comment]
@torkelo I understand that the queries are built by the frontend. But when "sharing" the dashbord, why not build all current queries and just save them at the Grafana-server? I guess something similar also takes place when creating alerts.

**Comment by stefan-muc** [comment]
@torkelo Just for clarity: When you give some user read/view access to a Grafana Dasboard, he then (trough API) has full access to every datasource that's configured in Grafana, maybe even write access?

That's not what I would have expected - I would have expected a restriction at least to the data sources the Dashboards/Panels have access to, maybe even a restriction to the tables and table fields.
It's a basic security measure not to trust user input - queries from frontend would have to be handled like that for a secure system.

**Comment by torkelo** [comment]
Yes, if you give a user view access they get query access to ever datasource in the organization. They can issue any query. Depending on datasource type, some support user permissions to lock down access to only specific tables, the viewer user will then be restricted to the user specified in the datasource settings.

**Comment by depasseg** [comment]
What about some way to utilize the local snapshots function but auto-refresh the snapshot data?

Don't snapshots strip out the sensitive stuff and exposure to the datasources?  If so, and there was a way to auto refresh the snapshot once every X minutes, this might be a start.

**Comment by stegenfeldt** [comment]
For my use, I'd be perfectly happy with a "snapshot" that refreshes itself in the background. 

I don't really need the user to be able to adjust the timeframe, but I do need to give customers and application owners a read-only snapshot of a relative timeframe. SquaredUp does something similar with their "open access" dashboards. When you define a dashboard, you also set a default timeframe, like "last 6h". When sharing it through their "Open Access" you get a unique link that requires no login, but also don't allow for any interaction with the data. The server will auto-update the data based on the set timeframe when needed, with some leeway for caching. If you set a 6hr data window and 5 min aggregation, the data will only be updated at most every 5 minutes, and only if a user visits the page. 

That may be much more advanced than a self-updating shapshot, with all the caching and stuff, but I thought I'd provide it as food-for-thought. 
I'm perfectly fine with setting a relative timefram when creating the snapshot, and everytime the page is loaded, it will show up-to-date data. Interaction is optional.

**Comment by Xavier59** [comment]
> Yes, if you give a user view access they get query access to ever datasource in the organization. They can issue any query. Depending on datasource type, some support user permissions to lock down access to only specific tables, the viewer user will then be restricted to the user specified in the datasource settings.

This should be more publicized I think.
Most grafana users that have public dashboard don't know that anyone is able to execute any query they want on their database just by having the viewer role. Hopefully, I noticed the queries on going in the network requests otherwise any competitor could have easily extracted all the data I collected.
And if the db administrator didn't create a specific grafana user with read-only rights, any attacker can also drop the whole database or store illegal things on your db.
Even with read-only and considering I don't care about my data being stolen or that I only keep the minimum on my db, any attacker can still very easily execute heavy cpu-intensive query in order to DOS you.

**Comment by adinhodovic** [comment]
Since this is not moving, would it be possible to start of by having the option to add a key in the UI for creating predictable URLs. The API currently has it which makes it less of a headache refreshing(remove/recreate) any snapshots since the URL remains the same. This would especially make it easier for embedded panels since the URL remains the same.  #16876 mentions this and I assume the change is not huge (adding parameters to the POST snapshot API request).

**Comment by lenusch** [comment]
We would love to have a snapshot Feature aswell.

**Comment by Bias313** [comment]
Looking for exactly this too!

**Comment by vonox7** [comment]
@torkelo I guess this feature request can now be closed, as it is implement by public dashboards https://github.com/grafana/grafana/discussions/49253 in Grafana 9.1.

**Comment by torkelo** [comment]
yes, public dashboards still need many more iterations to fully solve the need (some level of support for template variables, dynamic time ranges)
