### ISSUE TITLE
Explore: Unexpected behavior when adding label for metrics which contains colon symbol

### ISSUE THREAD

**Issue by aylei** [grafana/grafana#14475]
When using the new `Exploration` feature, I found that adding label selector (by clicking table cell) to PromQL which contains colon symbol and label selector would result in bad expression.

Before:
```
sum(rate(hunter_api_response_duration_seconds:optimized_sum{pdl="user-growth"}[5m])) by (owt, pdl, service, cluster, instance) / sum(rate(hunter_api_response_duration_seconds:optimized_count{pdl="user-growth"}[5m])) by (owt, pdl, service, cluster, instance)
```

After:
```
sum(rate(hunter_api_response_duration_seconds:{service="userservice"}optimized_sum{pdl="user-growth",service="userservice"}[5m])) by (owt, pdl, service, cluster, instance) / sum(rate(hunter_api_response_duration_seconds:{service="userservice"}optimized_count{pdl="user-growth",service="userservice"}[5m])) by (owt, pdl, service, cluster, instance)
```
![grafana-explore](https://user-images.githubusercontent.com/18556593/49920651-ebb0d280-fee5-11e8-841a-f450042119cf.gif)

Information:

* Grafana version: v5.5.0-pre1 (8e00bb3)
* Datasource: Prometheus 2.3.2
* OS: MacOS mojave
* Browser: Goole Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by jschill** [comment]
This regexp doesnt play well with the colons:
https://github.com/grafana/grafana/blob/c243e789139f6a44f7b6c48f6abcd993f7b0c057/public/app/plugins/datasource/prometheus/add_label_to_query.ts#L18

**Comment by tolwi** [comment]
#16760
