### ISSUE TITLE
How to create Drop Down list metrics 

### ISSUE THREAD

**Issue by raperumain** [grafana/grafana#14474]
I am using the following Query ,

select collection_date AS time , count(cpu) AS “payment”
from host
where host_name=‘payment’
group by collection_date
order by 1

++ Using Add Query , i have added same query 10 time with different host_name

The graph os showing perfectly with 10 lines , But i want metrics should be in Drop-Down list , so that i can select what ever server i want and ‘ALL’ option if required.

Note:
I am using Postgres as a DataSource.

Thanks in Advance

**Comment by sunker** [comment]
Hi @raperumain. Questions should be posted in the [community site](https://community.grafana.com/). Github is for issues and feature requests.
