### ISSUE TITLE
missing series results in splitting

### ISSUE THREAD

**Issue by baiwfg2** [grafana/grafana#14479]
Hi. I met with a situation. See below,

![image](https://user-images.githubusercontent.com/5157680/49924921-75ff3380-fef2-11e8-9a1d-02dc288d041b.png)

I use prometheus. I seldom see this series splitting before. Is it normal or a bug ?

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by sunker** [comment]
@baiwfg2 this is not a bug in Grafana. If there's a gap (null value) in your timeseries, there will be a gap in the graph. However you can configure this in the panel. If you don't want the gaps, use `connected` mode. See [docs](http://docs.grafana.org/features/panels/graph/#display-styles)

**Comment by baiwfg2** [comment]
@sunker  Thanks for replying. But the server process never crashes. How could my timeseries have gap(null value) ? As far as I'm supposed,  it'a either zero or some number as long as the server is alive, right ?  Unless  promethesus fetches metrics but got no response, then prometheus deems it dead for that moment, is it possible ?

**Comment by baiwfg2** [comment]
And pay attention that in my graph, only index metric has gap, others don't
