### ISSUE TITLE
Explore: Autocomplete misbehaving

### ISSUE THREAD

**Issue by ventris** [grafana/grafana#14478]
### What Grafana version are you using?
grafana:master docker image
### What datasource are you using?
Loki
### What OS are you running grafana on?
Debian
### What did you do?
Explore the explore ui

When using the autocomplete for Loki one can select a log label from the button to the left.
Example:
```{__filename__="/var/log/auth.log"}```

When one manually edits the labels to something else the autocomplete dropdown pops up. If I instead of select something in the dropdown edit the string to what I want such as:
```{__filename__="/var/log/auth.log.1"}```

If you press enter here to search for the new string the autocomplete will select the first suggestion in the list and edit the string to:
```{__filename__="/var/log/auth.log.1""}```

The thing here is that the autocomplete does not take in to account what the current string is but it will add the whole filename with correct quotation marks even though there is still a quotation mark at the end.

**Comment by ventris** [comment]
I would prefer not to have autocomplete selection on the same button as search. Maybe use TAB as the select autocomplete value.

**Comment by ventris** [comment]
Thanks for the update. 

To clarify the double " issue.
I have this to start with
```{__filename__="/var/log/auth.log"}```

and remove the /var/log/auth.log so the string becomes
```{__filename__=""}```

If I select something from the autocomplete here the first " stays the same but the autocomplete adds an " at the end of the filename even though there is a " there.

I'll try to recreate this and record it.

**Comment by davkal** [comment]
Can repro. Thanks for providing the details.

**Comment by aocenas** [comment]
Should be already fixed but feel free to reopen if you still see issue with the autocomplete
