### ISSUE TITLE
Warning state for Panels

### ISSUE THREAD

**Issue by akindr** [grafana/grafana#14487]
**Feature Proposal**: Warning state for panels.

### Problem Statement
There are certain scenarios where a dashboard is sluggish due to a few bad queries. These queries are not invalid, but rather they are expensive and usually can be simplified. Users typically have no idea why a dashboard is slow because there's no feedback mechanism for this.

Similarly, a datasource may return some metadata in the response indicating a query is incomplete. For example, maybe the user queries for a month of data but anything over 2 weeks old is downsampled. There's no great way to surface this to the user as well.

I'd like a way to give user feedback without throwing an error.

### Current Solutions
As it stands, Grafana supports showing an error message if an exception occurs, or showing the panel description. Neither of these capture my use-case. 

### Solution
I propose adding a mechanism for a datasource to return some kind of `warning` state, which can be consumed by the panel. 

I prototyped this locally and here's how it might look:

<img width="506" alt="screen shot 2018-12-13 at 10 40 26 am" src="https://user-images.githubusercontent.com/10089534/49950623-29056800-fec6-11e8-82d2-7acd0921d9bc.png">

If this seems reasonable, I can open a PR to discuss further.

**Comment by daniellee** [comment]
Yes, this seems like a good idea. I will discuss with the core team about how the UX should work and what it should look like.

**Comment by akindr** [comment]
Hey @daniellee I opened a PR for the feature.

The API is really simple - a datasource can attach a `warning` field to the `result` object. It accepts markdown, so users can format the message.

Let me know what you think.
