### ISSUE TITLE
Label cannot be formatted as date

### ISSUE THREAD

**Issue by dhewg** [grafana/grafana#14484]
### What Grafana version are you using?
Grafana v5.4.0 (69c5191)
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Linux arm64
### What did you do?
Add metrics to a table which have a label containing an epoch value (in unit 'seconds', but tried 'milliseconds' as well). Set column style type to 'Date'
### What was the expected result?
Epoch value converted to date
### What happened instead?
Got "Invalid date"

It sounds like #13334 just for prometheus.

Another user has this issue too: https://community.grafana.com/t/invalid-date-when-using-epoch-string-label/7690

**Comment by dhewg** [comment]
Same happens with singlestat when trying to format the epoch value as date, just that it prints the raw value instead of "Invalid date"

**Comment by daniellee** [comment]
You don't show any data but the basic problem is Prometheus epochs are in seconds and Grafana expects millisecond epochs. Grafana does a conversion for the timestamp automatically but maybe not for labels.

In your query, what value have you chosen for your "Format as" field? It should probably be `Table`.

There are some tricks when it comes to working with Timestamp metrics. I don't know what metrics you are working with but section 4 in this guide might be useful: 

https://www.digitalocean.com/community/tutorials/how-to-query-prometheus-on-ubuntu-14-04-part-2

**Comment by daniellee** [comment]
@dhewg this change will be included in the next major release of Grafana.

**Comment by dhewg** [comment]
@daniellee nice, thanks!

**Comment by dhewg** [comment]
Does this fix the issue for singlestats too?

**Comment by dhewg** [comment]
Just tested a nightly build, and it works on tables now! Thanks!

**Comment by dhewg** [comment]
Doesn't fix the issue for singlestats!
