### ISSUE TITLE
Tags filter dropdown selector is not scrollable

### ISSUE THREAD

**Issue by cdanis** [grafana/grafana#14486]
Using Grafana 5.4.1* running on Debian Stretch.

In the dashboard finder UI (obtained by clicking the top nav bar), the tags filter dropdown list is not scrollable -- there's no scrollbar, and mouse wheel doesn't do anything either.  We have many tags, so between this and #14437, it's basically impossible to select any tag aside from the first few.

![image](https://user-images.githubusercontent.com/1160935/49944603-cce81700-feb8-11e8-9b75-e747ad078d53.png)

*: Just saw that 5.4.2 is released and about upgrade to it -- thanks for the quick fix on #14437!

**Comment by daniellee** [comment]
Confirmed. Thanks for reporting this (again!).

**Comment by jschill** [comment]
Hey! This is fixed in master per https://github.com/grafana/grafana/commit/7e0bc8f30db34c92dcc9ba8cd525903b6504419b

We could (should) cherry pick it if a 5.4.3 is released.

**Comment by jschill** [comment]
Closing. Thanks for reporting!

**Comment by marefr** [comment]
@jschill given a lot of refactorings have been made to the react select drop down in master, is it really a matter of cherry picking that commit or is it more changes needed?

**Comment by marefr** [comment]
Hmm okay. Sure

**Comment by jschill** [comment]
Well, we could of course skip it and have it in 5.5 instead if we think it's a mess cherry picking.
