### ISSUE TITLE
Problem in sorting column style in date format on table

### ISSUE THREAD

**Issue by ptitou** [grafana/grafana#14488]
### What Grafana version are you using?
Grafana v5.3.0 (c613a31)
### What datasource are you using?
Influxdb( v1.6.3) datasource
### What OS are you running grafana on?
CentOS Linux release 7.2.1511 (Core)
Linux xxxxxxxxxxx 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### What did you do?
Get string fields from influxdb containing a date (default unix format date without timezone)
![image](https://user-images.githubusercontent.com/16797555/49952412-2e7da500-fefc-11e8-89fb-a52f927502f5.png)

Put them in a table in grafana and change column style to print it in Date format
![image](https://user-images.githubusercontent.com/16797555/49952491-540aae80-fefc-11e8-9985-51a439b95c3f.png)

### What was the expected result?
I want to sort this column by date ascending or descending. I like to see date sorted !

### What happened instead?
The sort is done on original string field
View without changing column style (default view, sort desc, sorted asc)
![image](https://user-images.githubusercontent.com/16797555/49953140-c039e200-fefd-11e8-861b-b4ac82a0423c.png)
View after changing column style (default view, sort desc, sorted asc)
![image](https://user-images.githubusercontent.com/16797555/49953179-d2b41b80-fefd-11e8-913e-9e7790f7da50.png)

I wonder if it's normal that sorting is only available on original fields, or if it's a bug because changing column style can interpret date and change format, but cannot sort it.

Thanks.

**Comment by daniellee** [comment]
Can you explain your use case more? I think you might be trying to solve a problem in a way that InfluxDB does not really support. Tag and field values don't support a date type and there is nothing in Grafana that will automatically convert from every existing datetime format. 

An event saved in InfluxDB gets a timestamp (in the epoch format) automatically so I wonder why you have an extra `install_date` field?

**Comment by ptitou** [comment]
Every night we get some informations from our server in order to follow evolution during all his life.

This extrafield in our case concerned the installation date of a server. 

After that in grafana we want to sort list of server by install date and as grafana recognizes the string field as a date, I thank it can also sort ir like a date

**Comment by daniellee** [comment]
This is actually not that easy to fix with the way the code is written. The sorting on the table data is done first and then a render function is called for each cell that converts the value according to the column style. 

If the underlying data type was an epoch or an ISO date then this would work - so this is an edge case.

**Comment by hreidar** [comment]
Hi, I'm seeing similar things, table sort not working on date info which is transformed using a Date type rule. The original data is coming from a Prometheus label. I'm using Grafana 6.5.2.

**Comment by torkelo** [comment]
should be fixed in new table
