### ISSUE TITLE
Dashboard links do not update when time range changes

### ISSUE THREAD

**Issue by alebsack** [grafana/grafana#14493]
### What Grafana version are you using?

Version 5.4.1

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Linux

### What did you do?

I upgraded from 5.3.4 to 5.4.1

### What was the expected result?

Dashboard links that are configured with current variables and time range should be updated when variables and/or time range changes.  Version 5.3.4 did this properly, but version 5.4.1 does not.

### What happened instead?

When changing the time range, links are not updated with the new time range.

**Comment by daniellee** [comment]
I just did a quick test and changing the time range and/or a variable is updated in the link for me.

I made an example dashboard on the play site with a dashboard link: https://play.grafana.org/d/z_HJIQEiz/14493-dashboard-link-updates-querystring?orgId=1&from=now-3h&to=now

Have you got an example dashboard you can share?

**Comment by torkelo** [comment]
that dashboard did not have any dashboard links daniel, only panel links :) 

I can replicate it with dashboard links. will investigate.

**Comment by eugenekropotkin** [comment]
I've just found this bug but you allready fixed it ;)
Thanx!
(In 5.4.3-1 all already fine)
