### ISSUE TITLE
Prometheus source 

### ISSUE THREAD

**Issue by PeterBortas** [grafana/grafana#14495]
### What Grafana version are you using?
5.4.2 (d812109) just installed via debs from the official repo

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
Started Grafana, added a single Prometheus data source with the URL pointing to a Ceph server and then added dashboard 7056 from grafana.com

### What was the expected result?
Graphs showing Ceph things

### What happened instead?
All graphs fail to load and Firefox console is full of CORS errors. Seemingly Grafana is trying to get my browser to fetch the data despite "Access" being set to "Server".

Config and error (which also shows up when pressing "Save & Test") here: http://i.imgur.com/sq70NkX.png

Things tried with no effect:
1. Switched to Browser access mode and then back to Server again on the data source
2. Deleted the originally created data source and make a new one against the same URL
3. Opened the sqlite db and verified that "access" is set to "proxy" in the data_source table
4. Restarted Grafana

**Comment by daniellee** [comment]
@PeterBortas correct me if I'm wrong but ceph is not a prometheus server. You have a ceph endpoint that can be scraped by a prometheus server. Grafana does not know what to do with a Prometheus exporter endpoint.

See the ceph prometheus module docs [here](http://docs.ceph.com/docs/mimic/mgr/prometheus/)

**Comment by PeterBortas** [comment]
You are absolutely correct. For some reason I read the documentation as if it would provide the Prometheus functionality in the Ceph plugin. Setting up a Prometheus server and fetching the data from it solves my problem.

I still don't understand why using the Ceph statistics endpoint in the configuration led to CORS errors of all things, but I'll leave it up to the development team to decide if that's a bug or not.

Many thanks!
