### ISSUE TITLE
Dashboard list panel

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1449]
A new panel has been implemented for the Grafana 2.0 release that can list starred dashboards (for the current user) and dashboards based on search query or dashboard tag. 

![image](https://cloud.githubusercontent.com/assets/10999/6124223/d482d148-b10b-11e4-9b55-503acebb0caa.png)

Feedback on this panel would be great, is there anything else that could be good to add to this panel?

**Comment by phagedorn** [comment]
:+1:
