### ISSUE TITLE
[Feature Request] (Re)store dashboards to/from external providers

### ISSUE THREAD

**Issue by mgomersbach** [grafana/grafana#14498]
Currently we can export/import dashboard json files through an API. Which is great and works.
However it would be very helpful to be able to store these in online storage/providers for provisioning.

There is code to push Grafana generated images to these providers.
Would it be possible to leverage the same code to store/restore json files?

There is a related issue about provisioning dashboards here : https://github.com/grafana/grafana/issues/13823
And as never programmed in Go before don't take my fork/mock too seriously, this is just to explain what I would try to achieve with this: https://github.com/mgomersbach/grafana/tree/add-json-uploader

**Comment by torkelo** [comment]
yes, we will likely integrate with Git services to provide something like this (https://github.com/grafana/grafana/issues/13823) . If it's just about syncing files to disc to from blob storage, I think that can be handled by other tool outside Grafana.
