### ISSUE TITLE
elaticsearch timepicker date field

### ISSUE THREAD

**Issue by cosmos78** [grafana/grafana#14497]
When using elasticsearch datasource it seems the timefield for the timepicker is hardcoded to @timestamp
I have some data with multiple date fields.

When I choose a different time field than @timestamp in a date histogram it becomes clear that the timepicker is still fixed to @timestamp even when the @timefield in the datasource is not @timestamp.

Is it possible to make the date picker timefield configurable in the datasource configuration ?

**Comment by marefr** [comment]
Duplicate of #7582
