### ISSUE TITLE
Customizing Login Page

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14504]
I'm using Grafana in CentOS 7 and I've installed grafana from https://grafana.com/grafana/download?platform=linux this link. 
Now I need to customize login page ,like to add new text and images. I tried editing /usr/share/grafana/public/app/partials/login.html  but it does not show any result.
Any comments?

**Comment by torkelo** [comment]
You will have to read the building from source guide in readme or docs. 

To make changes to the login page you need to rebuild Grafana

**Comment by Siddhu1096** [comment]
ok
