### ISSUE TITLE
Stackdriver data source expects distributions' lower bounds to be int64

### ISSUE THREAD

**Issue by manugarg** [grafana/grafana#14509]
Please include this information:
### What Grafana version are you using?
5.3.4 (But, version doesn't really matter, I see the problematic code even now.)

### What datasource are you using?
Stackdriver with GCE.

Adding a stackdriver distribution metric that has float lower-bounds results in an error:
"json: cannot unmarshal number 0.01 into Go struct field .bounds of type int64"

Here is the code that's causing this problem:
https://github.com/grafana/grafana/blob/9773a2d41959385b338e97eb2f9b3b61c1b7f8c3/pkg/tsdb/stackdriver/types.go#L29

I can attempt fixing it. Please let me know.

**Comment by daniellee** [comment]
@manugarg please do attempt a fix. Also it would be great if you could a unit test for it. Thanks!

**Comment by sunker** [comment]
@manugarg 

The fix should be simple. Just change the datatype of `Bounds` from []int64 to []float64 on this line that you pointet out:
https://github.com/grafana/grafana/blob/9773a2d41959385b338e97eb2f9b3b61c1b7f8c3/pkg/tsdb/stackdriver/types.go#L29

Unfortunately we don't have any data in Stackdriver for any of the metrics that results in distributions value type, so we can't test it. Would you mind providing a fix and test it thoroughly?

**Comment by manugarg** [comment]
I'll work on the fix. Holidays got in the way. I have a setup to test this.

**Comment by sunker** [comment]
thanks! 👍

**Comment by daniellee** [comment]
I could recreate this - fix coming up. I want to get this into 6.0.

**Comment by torkelo** [comment]
updating milestone as this was not cherry picked for 6.0 will be in 6.0.1
