### ISSUE TITLE
Grafana 2.0 user  new ( page not found) 

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1451]
First time I try to create a user the page load is failing 

![image](https://cloud.githubusercontent.com/assets/5883405/6129565/a20559be-b13f-11e4-9494-5d56e1fcc0b4.png)

After navigate to "settings" options finally the user form appears.

![image](https://cloud.githubusercontent.com/assets/5883405/6129627/14b34bf6-b140-11e4-8f65-6764c55f2dfa.png)

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
