### ISSUE TITLE
Explore: Line Graphs missing

### ISSUE THREAD

**Issue by negbie** [grafana/grafana#14516]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
grafana:master docker image.
### What datasource are you using?
loki.
### What OS are you running grafana on?
linux arch.
### What did you do?
Doing lots of batch inserts every 5-30 minutes.
### What was the expected result?
See Line Graphs with the correct number for each batch insert in the selected timeframe.
### What happened instead?
You can see a Line Graph for latest batch (picture 1) insert but not the one 10 minutes earlier despite matching timeframe. They will only show up when you select them without the latest one (picture 2)

picture 1:
![screenshot_2018-12-16 grafana - home 1](https://user-images.githubusercontent.com/20154956/50055560-e5725e80-0150-11e9-8c24-68d903154a2d.png)

picture 2:
![screenshot_2018-12-16 grafana - home 2](https://user-images.githubusercontent.com/20154956/50055562-f6bb6b00-0150-11e9-8d3e-d0b050964ae1.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
Host: localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:3000/explore?state=%5B%22now-3h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22heplify-server%5C%22%7D%22%7D%5D
X-Grafana-Org-Id: 1
DNT: 1
Connection: keep-alive
Cookie: grafana_sess=c3a9ab2f70f7bdf9; grafana_user=admin; grafana_remember=2d8b761205fcd8ccb81f5a2ce08b56347feda223c6ebf435b2fbabbb7c23c20ddb

HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: text/plain; charset=utf-8
Date: Sun, 16 Dec 2018 15:49:22 GMT
Expires: -1
Pragma: no-cache
Server: Caddy
Transfer-Encoding: chunked

**Comment by torkelo** [comment]
your hitting the 1000 rows (log events) limit, which means the graph will only show those events.

**Comment by negbie** [comment]
@torkelo Thank you for the clarification. I didn't know that the 1000 rows limitation applies to the stacked graphes aswell. Wouldn't it make sense to indicate at least that there were former events? Following example. Application1 sends more than 1000 logs due to an error. Some time later another application2 did this too. How will you know about Application1 when you don't see a stacked graph for that time?

**Comment by torkelo** [comment]
We will add a feature to highlight the row limit on the graph. 

To view log trends over long time ranges without returning millions of log lines to Grafana Loki will probably make it possible to turn log lines into metrics (time series) stored in Prometheus/Cortex etc

**Comment by torkelo** [comment]
here is an issue in loki for this: https://github.com/grafana/loki/issues/115
