### ISSUE TITLE
any support on  server side paging in table panel?

### ISSUE THREAD

**Issue by aximo** [grafana/grafana#14517]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
mysql
### What OS are you running grafana on?
window 7 64bit
### What did you do?
paging for a big table in table panel
### What was the expected result?
i want grafana do a server side paging but it seems to be a client paging

I notice that grafana do a query using /api/tsdb/query and return all the datas,and than paging in brower, however,it will be some problem in those tables which have too many records.

so  any suggestion about this?

**Comment by torkelo** [comment]
We can't really do this, as the dashboard time range sets the range for the query and pagination would have to be implemented differently for each TSDB / data source, many data sources do not support it. So do not think we will do this.

**Comment by nbingham1** [comment]
Is it possible to stand up a "page" variable that is linked to the displayed table that we can use in a limit/offset query? Whenever the user goes to a new page in the table, the page variable is updated and the query is run with the new page value. That way we could at least implement our own server side paging
