### ISSUE TITLE
[Feature request] datasource down alert

### ISSUE THREAD

**Issue by gaizeror** [grafana/grafana#14515]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.4.1
### What datasource are you using?
Prometheus, influxDB
### What OS are you running grafana on?
Centos7
### What did you do?
Restarted Prometheus
### What was the expected result?
1 alert of "Datasource Down"
### What happened instead?
Every alert related to prometheus fired, and spammed PD and Slack
 
I know there is an option "If execution error or timeout", but I want it to fire on single execution error of this alert, not when a Datasource is down.

Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
