### ISSUE TITLE
[Bug] InfluxDB Admin plugin error

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#14513]
### What Grafana version are you using?
5.4.2
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Linux AMI

Since the upgrade to newest Grafana version the InfluxDB admin plugin doesn't show stats and throws this exception: "Cannot read property 'raw' of undefined"

**Comment by torkelo** [comment]
Can you open an issue with the admin plugin author / repo?
