### ISSUE TITLE
Add blood glucose level units mg/dL and mmol/L

### ISSUE THREAD

**Issue by kjedamzik** [grafana/grafana#14519]
Can you please add the units **mg/dL** and **mmol/L**

The international standard way of measuring **blood glucose levels** is in terms of a molar concentration, measured in mmol/L (millimoles per litre; or millimolar, abbreviated mM). In the United States, Germany and other countries mass concentration is measured in mg/dL (milligrams per decilitre).

**Comment by marefr** [comment]
I don't know what kind of unit this is, please update issue description and also include what kind of measurement you're using this for.

This is not prioritized by core team. If you want to try and contribute and open a PR, here's an example PR of adding some other (radiation) units: https://github.com/grafana/grafana/pull/11000

**Comment by marefr** [comment]
Fixed by #14605

**Comment by sunny12568** [comment]
Blood glucose levels are typically measured in two different units: milligrams per deciliter (mg/dL) and millimoles per liter (mmol/L). These units are used in different parts of the world, with mg/dL being more common in the United States, while mmol/L is used in many other countries, including Canada, the United Kingdom, and most of Europe. 

**Here's a conversion between the two units:**

1 mg/dL = 0.0555 mmol/L
1 mmol/L = 18 mg/dL

For example, if you have a blood glucose level of 90 mg/dL, it can be converted to mmol/L as follows:
90 mg/dL * 0.0555 mmol/L = 4.995 mmol/L (rounded to 5.0 mmol/L)

Conversely, if you have a blood glucose level of 10 mmol/L, you can convert it to mg/dL as follows:
10 mmol/L * 18 mg/dL = 180 mg/dL

These conversions are important for individuals with diabetes, as they may need to monitor their blood glucose levels and interpret readings from different sources. Always be sure to know which unit is being used in your specific situation to interpret your blood glucose levels correctly.
you can used blood sugar converter - [mg/dl to mmol/l calculator](https://www.calculatorway.com/mg-dl-to-mmol-l-calculator/)
