### ISSUE TITLE
[Bug] - Graph panel with alert shows status gray until manual dashboard refresh

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#14514]
What Grafana version are you using?
5.4.2

What datasource are you using?
InfluxDB

What OS are you running grafana on?
Linux AMI

Since the upgrade to newest Grafana version when I navigate to dashboard with Graph panel with alerts, the status shows gray color, and after refreshing manually it turns to green.
During the time when it's gray it doesn't show alert history in the graph.

Before manually refreshing:
![image](https://user-images.githubusercontent.com/24862189/50054844-13ef3a00-014f-11e9-8ece-3ce9c638de35.png)

After manually refreshing the dashboard:
![image](https://user-images.githubusercontent.com/24862189/50054850-31bc9f00-014f-11e9-9dab-e6d956ad5e12.png)

**Comment by torkelo** [comment]
strange, unable to replicate here: 
https://play.grafana.org/d/000000074/alerting?orgId=1

**Comment by torkelo** [comment]
closing due to lack of updates. 

Maybe you saved the dashboard with an absolute time range? then no alert status is fetched, only on relative to now time ranges.
