### ISSUE TITLE
Grafana2.0: dashboard reload over localhost

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1452]
After importing a dashboard I've closed session. 

![image](https://cloud.githubusercontent.com/assets/5883405/6129858/8bf1a9e6-b141-11e4-8d9a-e1691cb998f1.png)

When I click over the dashboard it redirects over localhost

![image](https://cloud.githubusercontent.com/assets/5883405/6129832/6d85a796-b141-11e4-93de-65466e2f6887.png)

**Comment by torkelo** [comment]
you need to override root_url https://github.com/grafana/grafana/blob/develop/conf/grafana.ini#L7 

If you are using the docker image, I guess I need to add way to override add a custom config file that one. If you are building it yourself you can add a grafana.custom.ini and add it to the conf dir and override the setting.
