### ISSUE TITLE
Explore: button toolbar looks messy in split view

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14522]
The toolbar wraps around on narrow screens or in split view and looks messy.

<img width="1063" alt="screenshot 2018-12-16 at 22 25 39" src="https://user-images.githubusercontent.com/859729/50070094-97c21a00-0181-11e9-83ab-cbdf115c714d.png">

Ideas:

- keep Run button together with timepicker and other buttons and wrap together
- provide slim versions of all buttons in narrow/split view

**Comment by torkelo** [comment]
Was also thinking about how to improve this when playing with explore over the weekend 😀

**Comment by Ijin08** [comment]
An idea is to have the split button in the middle and push everything down:
<img width="1440" alt="screenshot 2019-01-11 at 13 44 15" src="https://user-images.githubusercontent.com/23470681/51034483-338b4e00-15a7-11e9-9e86-4f3db7639500.png">
<img width="1440" alt="screenshot 2019-01-11 at 13 44 31" src="https://user-images.githubusercontent.com/23470681/51034495-3c7c1f80-15a7-11e9-8e42-b3929c211cdf.png">

@davkal

**Comment by davkal** [comment]
Over the last week, I've come to realize that it might be quite good to be able to close either left or right, and not just right by default. This would allow a great flow that just keeps going right (by closing left, splitting right).
I'm also playing with the idea of splitting each Explore again, so you can have more than 2 columns.

**Comment by Ijin08** [comment]
Slimmed down two of the buttons. Clear all doesn't have an icon so difficult to make smaller.

<img width="1440" alt="screenshot 2019-01-11 at 15 18 36" src="https://user-images.githubusercontent.com/23470681/51038756-58d28900-15b4-11e9-8a28-953d66a1fb42.png">
<img width="1440" alt="screenshot 2019-01-11 at 15 18 56" src="https://user-images.githubusercontent.com/23470681/51038758-58d28900-15b4-11e9-9033-202924d349d9.png">

**Comment by davkal** [comment]
This looks great. What does the toolbar look like when there is enough space? I think we should fit it all on one row when there is enough space.

**Comment by Ijin08** [comment]
My thought was to separate the close view button should be separate from the rest of the toolbar. Maybe it shouldn't be a button and just an x: 
<img width="1440" alt="screenshot 2019-01-14 at 13 20 54" src="https://user-images.githubusercontent.com/23470681/51112544-4009e380-17ff-11e9-9bf7-cc00145d2e5e.png">

**Comment by Ijin08** [comment]
Adding an icon for to the Split button makes it possible have a slim version:
<img width="214" alt="screenshot 2019-01-14 at 14 05 35" src="https://user-images.githubusercontent.com/23470681/51114445-a72a9680-1805-11e9-9860-d985705de071.png">
