### ISSUE TITLE
Unable to create new datasource if already exist one with the same name.

### ISSUE THREAD

**Issue by marcoscartes** [grafana/grafana#14536]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
 5.4.1
### What datasource are you using? 
graphite
### What OS are you running grafana on? 
alpine on docker
### What did you do?
I want to create a new graphite datasource, but it conflicts with a existen one with the name "graphite"
### What was the expected result?
New datasource created
### What happened instead?
409 error conflict
![screenshot from 2018-12-17 16-35-00](https://user-images.githubusercontent.com/45944716/50097246-bd026700-0219-11e9-9da6-46aaf620c9a7.png)

**Comment by torkelo** [comment]
Fixed in v5.4.2  :)
