### ISSUE TITLE
REST api

### ISSUE THREAD

**Issue by mkwiczalayandex** [grafana/grafana#1453]
Hi,

Do you plan to provide REST api for grafana?

I created "scripted_templated_dashboard.js?param1=param1&param2=param2&from=...&to=..."
with saveDashboard inside. It works fine but I can not easy automate this through terminal. To execute saveDashboard from "scripted_templated_dashboard.js" I have to load js in web browser...

Regards,
Mariusz

**Comment by torkelo** [comment]
yes, a REST api is implemented in the forth coming Grafana 2.0 backend. 
https://github.com/grafana/grafana/tree/develop
