### ISSUE TITLE
Bug: View only user can query whole database and only his graphs

### ISSUE THREAD

**Issue by zisisp** [grafana/grafana#14533]
### What Grafana version are you using?
 Grafana v5.2.2 (aeaf7b2) 
### What datasource are you using?
InfluxDb 1.6.0
### What OS are you running grafana on?
Ubintu 16.04.6 
### What did you do?
-I created an organization (let's call it O1) and in it, I create one graph (let's call it G1) with a specific query from InfluxDb.
-I created a view user (let's call him U1) and gave him this organization (O1).
-I logged in with that user (U1) and whet to the dashboard and graph (G1)  I created
-I took the request URL query that was used to generate this graph (G1) (using chrome devtools or whatever)
-Changed the request url influxdb query, to display another set of data. Lets say from graph 2 (G2)
-Without logging out of the user (U1) 
-Do that URL request, and get the data that the influxdb query requested. 
### What was the expected result?
I would expect that the view user can only see that graph data that he is allowed to.
### What happened instead?
I could query the whole InfluxDB.

**Comment by torkelo** [comment]
Viewer role is only about not being able to modify / create dashboards, datasources etc. To view a dashboard they need to issue queries. Query can be very dynamic in Grafana (built in the frontend using dynamic variables), so there is no way to verify that a query is part of a dashboard the user has access to. 

http://docs.grafana.org/permissions/overview/#datasource-permissions

If you need to isolate data you need to isolate the data in your data sources (separate InfluxDB databases for example)

**Comment by zisisp** [comment]
Since the queries pass through the Grafana API, I would not be so fast at closing this issue. You can control the queries that pass through by storing them and then not allowing them to change at all. (thats one easy solution)
Another solution is to store the data query and the time parameters in different variables and only allow (or not) for the time variable to change/
