### ISSUE TITLE
Support ICQ as alert notifier

### ISSUE THREAD

**Issue by nolequen** [grafana/grafana#14538]
https://en.wikipedia.org/wiki/ICQ

**Comment by nolequen** [comment]
hi @torkelo @bergquist
how about pluggable notifiers feature? is there any progress?

**Comment by bergquist** [comment]
We made some progress on backend plugins but no progress on making alert notifiers pluggable yet.

**Comment by nolequen** [comment]
@bergquist thanks!
Is there any information about dates when pluggable notifiers will be available?

**Comment by nolequen** [comment]
hi, @bergquist! are pluggable notifiers available already?

**Comment by zmeykagorinich** [comment]
Hello, I came across an interest in this opportunity. I hope it will appear, because ICQ has become in demand.

**Comment by KaplanSarah** [comment]
Please propose this to the prometheus alert manager first.  https://github.com/prometheus/alertmanager
