### ISSUE TITLE
Hover tooltip unreadable in worldmap with light theme

### ISSUE THREAD

**Issue by apetzo** [grafana/grafana#14542]
Please include this information:
### What Grafana version are you using?
5.42

### What OS are you running grafana on?
linux

### What did you do?
I've created a worldmap panel. It works fine, except that the hover tools tips are almost unreadable when I use the light theme

![image](https://user-images.githubusercontent.com/6966501/50117425-3c5d5e00-024d-11e9-84a2-e6e79ef70cae.png)

When using the dark theme the hover tooltips are readable.

### What was the expected result?
readable hover tooltip

### What happened instead?
almost unreadable hover tooltip

**Comment by torkelo** [comment]
Is this a new issue after v5.4 upgrade? 

please open an issue in the worldmap repo: https://github.com/grafana/worldmap-panel/issues

**Comment by remusmp** [comment]
I think this bug reappeared in version 7.0.3:
![Screenshot from 2020-06-18 15-09-59](https://user-images.githubusercontent.com/3688493/85024571-90187280-b176-11ea-94ea-2be37a132279.png)

**Comment by 2271hatlen** [comment]
> I think this bug reappeared in version 7.0.3: ![Screenshot from 2020-06-18 15-09-59](https://user-images.githubusercontent.com/3688493/85024571-90187280-b176-11ea-94ea-2be37a132279.png)

Agreed. Even in 8.1.5 this is an issue. This issue should be re-opened and fixed again.
