### ISSUE TITLE
Feature Request: Select Multiple Template Variables

### ISSUE THREAD

**Issue by Jhors2** [grafana/grafana#1454]
Hello,
I have quite a few situations where it would be nice to select multiple template variables that are matching a query to have them represented on the same series of graphs.  Imagine a situation where a template returns WebServer1 and WebServer2 as two viable choices.  However, you'd like to quick return both of those without having to cycle through them.  

Ideally, it would be nice to have a checkbox next to all matching template variables and be able to select 2.  This would of course have to be translated to something like: (WebServer1|WebServer2) for regex matching (InfluxDB in my instance) in order for the query to work.  Glob should also be a choice for some users of course.

I can do this by manually typing in the hostnames today, but it requires an intimate understanding of Grafana and Influx to be able to do so, this feature would make the UI more usable.

**Comment by torkelo** [comment]
@Jhors2 you can sort of, you can enter the value manually, 

![image](https://cloud.githubusercontent.com/assets/10999/6134042/a09850d0-b15e-11e4-882b-150b70bf9c9e.png)

**Comment by Jhors2** [comment]
I have done this as a workaround for my purposes.  However, we have some people in our team as well as business folks who would like to use this without understanding regex or glob.  Maybe this can just be a UI usability feature?
Thanks!

**Comment by torkelo** [comment]
implemented in 2.1 https://github.com/grafana/grafana/issues/1144#issuecomment-97428387

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1922#issuecomment-98624398
