### ISSUE TITLE
Switching Org Results in ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#14543]
### What Grafana version are you using?

`5.4.2` (since `5.3`)

### What OS are you running grafana on?

`CentOS`

### What did you do?

Switch betweens organizations, after received this message in the browser:

`ERR_TOO_MANY_REDIRECTS`

I had to press many times the `F5` (or `CTRL+F5`) button to be good...

I tried to delete all cookies, change browsers, change users, access from domain or from server IP ...

I couldn't found errors in the logs.

What is the problem? How can I debug it?

**Comment by sanchomuzax** [comment]
I can login normally, without problem.
Only happens when I change org with the org switcher or with a shortcut from bookmarks / shortcut whitch linked to other orgs.

**Comment by gagansam** [comment]
I am also facing this issue (recently migrated to 5.4.2 from 5.2.x). The issue is quite frequent and occurring 1 out of 3 times. While investigating, it seems that the newly switched org Id is not set in the middleware context object. So, there is mismatch between passed org (query) and current context org which forces the redirection (302).

**Comment by torkelo** [comment]
I can replicate when use a link with a different (from current) orgId, but not when using the org switcher in menu or profile. Can't find any obvious place where it goes wrong. Needs further investigation!

**Comment by gagansam** [comment]
The issue exits in the menu and profile as well but without redirection. 
**Actual issue**: The current org does not switch to target org. 
If you will look closely, you can see that while switching org via profile, sometimes source org does not change to target org (but it does not cause redirection as it never reaches to redirection code).  
 
`func OrgRedirect() macaron.Handler {
	return func(res http.ResponseWriter, req *http.Request, c *macaron.Context) {
		orgIdValue := req.URL.Query().Get("orgId")
		orgId, err := strconv.ParseInt(orgIdValue, 10, 32)

        // org Id is always 0 for profile switch so no redirection
		if err != nil || orgId == 0 {
			return
		}

		ctx, ok := c.Data["ctx"].(*m.ReqContext)
		if !ok || !ctx.IsSignedIn {
			return
		}

        // org Id does not match with the current code and hence go to redirection code
		if orgId == ctx.OrgId {
			return
		}

		cmd := m.SetUsingOrgCommand{UserId: ctx.UserId, OrgId: orgId}
		if err := bus.Dispatch(&cmd); err != nil {
			if ctx.IsApiRequest() {
				ctx.JsonApiErr(404, "Not found", nil)
			} else {
				ctx.Error(404, "Not found")
			}

			return
		}
        
        // redirection code
		newURL := setting.ToAbsUrl(fmt.Sprintf("%s?%s", strings.TrimPrefix(c.Req.URL.Path, "/"), c.Req.URL.Query().Encode()))
		c.Redirect(newURL, 302)
	}
}`

**Comment by marefr** [comment]
Hey @sanchomuzax @gagansam what database are you using? Are you running multiple instances of Grafana, high availability setup (ha)?

**Comment by marefr** [comment]
Following seems to fix the problem when using a link with other org id. Will open a PR

```diff
diff --git a/pkg/services/sqlstore/user.go b/pkg/services/sqlstore/user.go
index a3ccb93..719416d 100644
--- a/pkg/services/sqlstore/user.go
+++ b/pkg/services/sqlstore/user.go
@@ -357,6 +357,7 @@ func (ss *SqlStore) GetSignedInUserWithCache(query *m.GetSignedInUserQuery) erro
                return err
        }
 
+       cacheKey = fmt.Sprintf("signed-in-user-%d-%d", query.UserId, query.Result.OrgId)
        ss.CacheService.Set(cacheKey, query.Result, time.Second*5)
        return nil
 } 
```

**Comment by sanchomuzax** [comment]
> Hey @sanchomuzax @gagansam what database are you using? Are you running multiple instances of Grafana, high availability setup (ha)?

I'm using MySQL for Grafana database, because the sqlite3 not too stable...

. And connect Data Sources to a lot of types as same as InfluxDB, MariaDB, PostgreSQL, Microsoft SQL Server.
