### ISSUE TITLE
Grafana subfolder

### ISSUE THREAD

**Issue by Nemmesis82** [grafana/grafana#14559]
Good morning

You need to know if subfolders can be created within a created folder.

Its possible?

My version of grafana is v5.3.4

Thank you

Regards

**Comment by torkelo** [comment]
no, dashboard folders cannot be nested currently. But there is an open feature request for that so will close this

**Comment by schoofsc** [comment]
Hey @torkelo 

can you please post a referenz to the feature request. 

Thank You!

**Comment by hackery** [comment]
Feat request: Nested folder #10339
