### ISSUE TITLE
[Feauture Request] Multiple alert windows per graph

### ISSUE THREAD

**Issue by majkinetor** [grafana/grafana#14552]
Some metrics follow the dynamic alerting patterns. For example, I want to create several alerts for logins to application. Its typical that users have login patterns:

* 00-06 - 00-02 users/min
More than 5 is some kind of problem
* 06-16 - 30-100 users/min
Less than 10 and above 120 is some kind of problem
* 16-24 - 05-10 users/min
More than 20 is some kind of problem.

This could be supported by a feature, just add additional attribute time range apart from the definition.

**Comment by torkelo** [comment]
Similar to this issue: 

https://github.com/grafana/grafana/issues/7832
