### ISSUE TITLE
Microsoft Teams Integration

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14567]
I am not able to integrate Teams with Grafana.
Should I configure anything on grafana.ini?
Currently I have just added the link in alert channel on grafana 

Please include this information:
### What Grafana version are you using?
Grafana v5.4.2 
### What datasource are you using?
Graphite
### What OS are you running grafana on?
CentOS 7

**Comment by Siddhu1096** [comment]
Kindly mark it as urgent and please help me out!!

**Comment by Siddhu1096** [comment]
![asd](https://user-images.githubusercontent.com/22325249/50161756-a5eb7400-0302-11e9-9eef-64bd92093e89.PNG)
Its getting sent, But i am not receiving alert on teams.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Inspect the grafana server log for information. Based on your screenshot seems like you have an url encoded url specified, maybe that's the issue I don't know.

**Comment by Siddhu1096** [comment]
Ive asked then same question. But no one responded. 
Here goes the link https://community.grafana.com/t/microsoft-teams-integration/12944 .
Please respond @marefr

**Comment by Siddhu1096** [comment]
t=2018-12-18T08:51:58-0600 lvl=eror msg="failed to send notification" logger=alerting.notifier id=0 error="Webhook response status 404 Not Found"
This is the log @marefr

**Comment by Siddhu1096** [comment]
@marefr Please mark it as an urgent issue.,

**Comment by timlharrison** [comment]
Not sure if you ever got a response to this @Siddhu1096 but I was encountering the same problem and resolved it by adding the WebHook to the Teams channel and using the URL it provided.  You can't use the direct link to the Team channel.  The one I got the 404 looked like yours teams.microsoft.com/... but the one that worked provided by the WebHook was outlook.office.com/...

Hope it helps someone else in the future.
