### ISSUE TITLE
Changes on pannel are not saved

### ISSUE THREAD

**Issue by ninispagnol** [grafana/grafana#14566]
Hello,

### What Grafana version are you using?
5.4

### What datasource are you using?
Opentsdb

### What OS are you running grafana on?
Centos 6

### What did you do?
I imported in grafana 5.4 an existing dashboard from grafana 4.6. I tried to change the threshold settings of the table pannel, saved it but when I refreshed the web page, my settings weren't saved.

I set debug mode on Grafana to look if there were any errors in logs but all were fine, no error.

Any changes on the dashboard are not saved.

### What was the expected result?
I expected to have my changes saved.

### What happened instead?
My changes were not saved.

This is the dashboard that I work on 
[Global monitoring.txt](https://github.com/grafana/grafana/files/2690737/Global.monitoring.txt)
 
Feel free to  ask me for further information

Regards,
Eléni

**Comment by marefr** [comment]
Since you're using repeated rows and panels you can only edit the first row from the top in repeat sequence and the first panel at the top left.
