### ISSUE TITLE
Prometheus datasource with direct/browser access + auth basic + POST does not work

### ISSUE THREAD

**Issue by hekmon** [grafana/grafana#14561]
Hello,

We encountered a bug with Grafana when using a prometheus data source with direct/browser access and POST configuration.

Pre-flight request works fine but during the actual request the xmlhttprequest use a wrong content type `application/json;charset=UTF-8` which prevents prometheus to decode the query as the body is a form url encoded.

For now, our workaround is to intercept the query within our reverse proxy to rewrite the "content-type" header (with `application/x-www-form-urlencoded`) before it is actually sent to prometheus.

### What Grafana version are you using?
Grafana v5.4.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
-> Grafana Cloud
### What did you do?
Configure Prometheus data source with `Browser` (direct) access and `POST` HTTP method.
### What was the expected result?
A working datasource. xmlhttprequest preflight request is OK but actual request should have a `application/x-www-form-urlencoded` `content-type` instead of `application/json;charset=UTF-8` given the body is url form encoded.
### What happened instead?
The content-type is set to `application/json;charset=UTF-8` which prevents Prometheus to parse the body correctly. The error returned was:
```
{"status":"error","errorType":"bad_data","error":"parse error at char 1: no expression found in input"}
```
### Include raw network request

```
# General
Request URL: https://<prometheus_proxy>:9091/api/v1/query
Request Method: POST
Status Code: 400 
Remote Address: <prom_proxy_ip>:9091
Referrer Policy: no-referrer-when-downgrade

# Response headers
access-control-allow-credentials: true
access-control-allow-origin: https://<inst>.grafana.net
content-encoding: gzip
content-length: 103
content-type: application/json
date: Tue, 18 Dec 2018 11:32:37 GMT
status: 400
vary: Origin

# Request headers
Provisional headers are shown
Accept: application/json, text/plain, */*
Authorization: Basic <redacted>
Content-Type: application/json;charset=UTF-8  <-- issue is here
Origin: https://<inst>.grafana.net
Referer: https://<inst>.grafana.net/datasources/edit/29
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

# Request payload
query=1%2B1&time=1545132757.317
```

This behavior can simply be simulated with a curl command:
```
curl -X POST -H "content-type: application/json" -d "query=1%2B1&time=1545132757.317" "http://localhost:9090/api/v1/query"
{"status":"error","errorType":"bad_data","error":"parse error at char 1: no expression found in input"}
```

**Comment by marefr** [comment]
That's very weird. Tried against a local prometheus v2.2.0 using Browser access mode and POST. My request Content-Type header is properly sent. I would suggest you to open a support ticket with Grafana Cloud.

**Comment by hekmon** [comment]
Something is definitely wrong:
* tried with Chrome & Firefox on grafana cloud: issue is present
* tried with Chrome & Firefox on grafana on premise v5.4.2: issue is present
* during my tests I also caught the grafana cookies being sent as well while the "with credentials" was not checked

I also tested with a local vanilla local prometheus and issue is indeed not present :/

I see 4 differences from our setup and the vanilla test:
* https
* custom port
* auth basic
* rewritten CORS headers (prometheus forces CORS headers to hard coded values, mostly Origin: *,  so we had to intercept and rewrite them entirely).

I will update this post as soon as we pinpoint the issue origin.

**Comment by hekmon** [comment]
So I think I have narrowed down the issue and how to reproduce it accurately.

This seems to be linked to the `Auth Basic` option. By default prometheus CORS headers allow Origin `*` which is incompatible with sending credentials. This means you can not test this issue directly to a vanilla prometheus. You must go thru a reverse proxy which will rewrite prometheus CORS headers in order to allow creds to be sent.

I wrote a really simplified reverse proxy which allows to test this issue (and fix it on the fly with a simple flag):
https://gist.github.com/hekmon/dbc446d054c508cd370904978cb031cb

Once auth basic is activated and used with `POST` for a prometheus data source:
* Grafana sends a preflight (`OPTIONS`) request, which succeed with the reverse proxy sending valid CORS headers that allows both a single origin not being `*` (needed to send creds) and a validation that creds can be sent (`Access-Control-Allow-Credentials: true`)
* Grafana sends the actual (`POST`) request, which fails because the request sent by Grafana has the `Content-Type` header set to `application/json;charset=UTF-8` with a body actually in a `application/x-www-form-urlencoded` format.
* Prometheus answers `400 Bad Request` as it should with the following body:
```
{"status":"error","errorType":"bad_data","error":"parse error at char 1: no expression found in input"}
```

I can provide screenshots (grafana data source edit + developper console) of the different tests if needed/you can not run the reverse proxy yourself.

**Comment by hekmon** [comment]
Updated the title to include the "auth basic" parameter.

**Comment by torkelo** [comment]
not sure what else Grafana can do (ie where the bug is), we set the header correctly. Maybe it's in angular HTTP service or in the browser

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L108

**Comment by hekmon** [comment]
I guess it is up to the grafana team to tell :)

**Comment by aloababa** [comment]
It seems this problem does not appear anymore in grafana 6.6.2.

**Comment by aocenas** [comment]
@hekmon thanks for the proxy code, that helped a lot with testing this but seems like this issue is fixed already (probably not surprising considering it was created few years ago). So going to close this now.
