### ISSUE TITLE
Singlestat links don't work on iOS

### ISSUE THREAD

**Issue by lorenwest** [grafana/grafana#14568]
### What Grafana version are you using?
5.3.4

### What OS are you running grafana on?
Server: Docker, Client: iOS (tested on iPad and iPhone)

### What did you do?
Added a link to another dashboard from a Singlestat panel

### What was the expected result?
Clicking the Singlestat panel navigates to the linked dashboard

### What happened instead?
The hover text is displayed, but the click handler isn't invoked, and no navigation occurs

ps: A similar issue was addressed in #5597 / #5598 but iOS appears to have a different issue with the click event not being processed. It may be related to [general iOS click events not working](https://www.google.com/search?q=ios+click+event+not+working&rlz=1C5CHFA_enUS713US714&oq=ios+cli&aqs=chrome.0.69i59j0j69i57j69i59j69i60j0.1496j0j7&sourceid=chrome&ie=UTF-8), but this seems to be isolated to the singlestat panel. Maybe due to it being a canvas?

**Comment by daniellee** [comment]
Seems to work now when testing on iOS 14. Not very smooth UX but one click opens the link hover and a second click opens the link.
