### ISSUE TITLE
Generic OAuth client does not work with some providers

### ISSUE THREAD

**Issue by tdabasinskas** [grafana/grafana#14562]
### What Grafana version are you using?
v5.4.2
### What datasource are you using?
N/A
### What OS are you running grafana on?
Docker
### What did you do?
Configure `auth.generic_oauth` with a custom provider provider, which does not `client_id`/`client_secret` passed via Basic Auth HTTP header.
### What was the expected result?
`client_id` and `client_secret` are passed as part of POST body payload, allowing to successfully authenticate using this OAuth provider.
### What happened instead?
Authentication fails with `login.OAuthLogin(NewTransportWithCode)` error message in GUI and `oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_client\"}` error in logs.
### If related to metric query / data viz:
N/A
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
N/A

**Comment by buroa** [comment]
```send_client_credentials_via_post = true```

This would use POST instead of building the Authorization: Basic header.
