### ISSUE TITLE
Named colors in color picker

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14579]
Think we need to extend color picker to also provide named colors.

I am thinking especially for threshold colors it would aid in making singlestat/gauges/graphs more consistent. Also gives us an opportunity to tweak colors so they adapt to the current dark/light theme. 

For example would be nice to have in new thresholds component, have named colors for ok, warning & critical. Like we do graph thresholds. Will aid in migrating the graph thresholds (eventually)

**Comment by FUSAKLA** [comment]
This would be great also from the accessibility point of view. As a colorblind labels with name would be great on hover over the predefined colors.

**Comment by roidelapluie** [comment]
We use the same dashboards for internal (dark theme) and customers facing (light theme) grafana's. I was thinking about using jsonnet/grafonnet-lib for this but having it in grafana sounds great!

**Comment by Ijin08** [comment]
<img width="388" alt="screenshot 2019-01-14 at 13 55 26" src="https://user-images.githubusercontent.com/23470681/51113961-228b4880-1804-11e9-95e7-cf6ed4033df6.png">

**Comment by dprokop** [comment]
https://casesandberg.github.io/react-color this one could be useful for custom spectrum picker. It has multiple components available, that we can compose our picker from.

**Comment by CrashLaker** [comment]
Hi, 

How can I convert back from named colors to hex?
![image](https://user-images.githubusercontent.com/4432491/106227192-8b657380-61c7-11eb-92c2-39b0a6ea86e7.png)
