### ISSUE TITLE
Export CSV data format inconsistent

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#14578]
Grafana version: 5.4.0
Datasource: Influxdb 1.7.1

The graph being exported has a single line on it. The graph is correct. The influxdb query is as follows:

SELECT non_negative_derivative(sum("bytesrx"), 10s) FROM "net" WHERE (("instance" = 'instance2' AND "type" = 'ifstats' AND (type_instance =~ /rxdata/ )) OR ("instance" = 'instance1' AND "type" = 'ifstats' AND (type_instance =~ /^rxdata/))) AND $timeFilter GROUP BY time(1h) OFFSET 1

When I do a CSV export of the panel I want to view, I get this:

"Series";"Time";"Value"
"[[tag_host]]";"2018-12-12T12:00:00+11:00";1,721,992,142.283
"[[tag_host]]";"2018-12-12T13:00:00+11:00";2,042,607,538.558
"[[tag_host]]";"2018-12-12T14:00:00+11:00";2,648,544,223.564
"[[tag_host]]";"2018-12-12T15:00:00+11:00";3,009,894,877.375
"[[tag_host]]";"2018-12-12T16:00:00+11:00";3,084,997,922.153
"[[tag_host]]";"2018-12-12T17:00:00+11:00";3,115,924,369.636
"[[tag_host]]";"2018-12-12T18:00:00+11:00";1,930,515,179.667
"[[tag_host]]";"2018-12-12T19:00:00+11:00";1,844,105,498.419
"[[tag_host]]";"2018-12-12T20:00:00+11:00";2,215,151,491.086
"[[tag_host]]";"2018-12-12T21:00:00+11:00";2,070,038,877.511
"[[tag_host]]";"2018-12-12T22:00:00+11:00";2,169,796,893.275
"[[tag_host]]";"2018-12-12T23:00:00+11:00";2,583,357,480.2
"[[tag_host]]";"2018-12-13T00:00:00+11:00";2,209,055,283.617
"[[tag_host]]";"2018-12-13T01:00:00+11:00";1,482,083,011.4
"[[tag_host]]";"2018-12-13T02:00:00+11:00";1,397,321,214.953
"[[tag_host]]";"2018-12-13T03:00:00+11:00";1,040,369,228.947
"[[tag_host]]";"2018-12-13T04:00:00+11:00";708,001,144.183
"[[tag_host]]";"2018-12-13T05:00:00+11:00";460,799,125.342
"[[tag_host]]";"2018-12-13T06:00:00+11:00";828,392,568.419

Some rows have 5 columns, some rows have 4 columns.

**Comment by yellowpattern** [comment]
From the query inspector:

0:Array[1544594400000,3115924369.6361113]
1:Array[1544598000000,1930515179.6666667]
2:Array[1544601600000,1844105498.4194446]
3:Array[1544605200000,2215151491.086111]
4:Array[1544608800000,2070038877.511111]
5:Array[1544612400000,2169796893.275]
6:Array[1544616000000,2583357480.2]
7:Array[1544619600000,2209055283.616667]
8:Array[1544623200000,1482083011.4]
9:Array[1544626800000,1397321214.9527779]
10:Array[1544630400000,1040369228.9472222]
11:Array[1544634000000,708001144.1833333]
12:Array[1544637600000,460799125.34166664]

**Comment by torkelo** [comment]
Can you try Grafana nightly? Might have been fixed by a PR I just merged:
https://github.com/grafana/grafana/pull/14113

**Comment by yellowpattern** [comment]
Sorry, not easy to test a nightly but this definitely looks related.
