### ISSUE TITLE
MySQL Query Builder: critical query for large mysql instances

### ISSUE THREAD

**Issue by irgendwer112** [grafana/grafana#14575]
The new query builder uses information_schema queries for supporting the editor.

But: this query is killing large MySQL instances with some 100.000 tables.

<<<
// query that returns first table found that has a timestamp(tz) column and a float column
const query = `
SELECT
table_name as table_name,
( SELECT
column_name as column_name
FROM information_schema.columns c
WHERE
c.table_schema = t.table_schema ...
>>>

Result is a very long running locking query with "checking permissions" state. Mysql information_schema still has some problems with large installations, so most utilities allow to disable usage of information_schema.

This would be a nice config option in grafana too, even by removing support for the query editor or allow a more granular configuration for some databases with usage of "SHOW TABLES FROM %database" instead of information_schema.

**Comment by irgendwer112** [comment]
Yes: limit table_schema to current database should improve the query.

**Comment by hackalot805** [comment]
I was bit by this yesterday.  It caused our replication slave to eat up swap pages and slowed the replication queries to crawl.  Any plans to optimize this soon?

**Comment by marefr** [comment]
The fix of adding `table_schema = DATABASE()` needs to be implemented in this query:
https://github.com/grafana/grafana/blob/6fbca90269a0fe17f4e5ab7dac608b71ddd94db6/public/app/plugins/datasource/mysql/meta_query.ts#L29-L74

Anyone interested in testing if query works better with schema constraint and/or contributing a fix?
