### ISSUE TITLE
Unable to use multi_field in Grafana query

### ISSUE THREAD

**Issue by ryanjohara** [grafana/grafana#14573]
I've been able to use a not_analyzed, multi-field in a raw Elasticsearch query, however, when I try to use it in the Grafana (Lucene) query, it fails.

Is this possible?

We are using Grafana 5.1.0 and have a template set up like:

...
 "port_name": {
 "type": "multi_field",
 "fields": {
 "port_name": { "type": "string" },
 "untouched":{ "type": "string", "index": "not_analyzed"}
 }
 }
...

I was hoping to do something like this:

Query: program_name:'ABC' AND sentry_name:'SENTRY1' AND port_name.untouched:'PORT-A_B_C'

instead of this:

Query: program_name:'ABC' AND sentry_name:'SENTRY1' AND port_name:'PORT-A_B_C'

Thanks in advance for the help!

**Comment by torkelo** [comment]
Not sure how what Grafana needs to do differently to support this. We just send the lucene query to elasticsearch. 

Can you view the request sent to ES and review the ES query api, does there needs to be something new in the query as well?

**Comment by ryanjohara** [comment]
I reviewed the request in the Grafana Query Inspector to no avail.

After adding our multi_field reference (ie port_name.untouched) to the Metrics Query, I do see it in the Query Inspector, but the graph is blank, when it should have data :(

Furthering the raw ES example, executing the following command:

curl -XGET 'http://HOST/lvv-2018.01.07/_search' -s -d '{"aggs":{"aggs1":{"terms":{"field":"sentry_name.untouched","size":1000},"aggs":{"aggs2":{"terms":{"field":"program_name.untouched","size":1000},"aggs":{"aggs3":{"terms":{"field":"port_name.untouched","size":1000}}}}}}}}' > group_by_count.out

I get a nicely formatted result set (with port_name 'PORT-A_B_C' and NOT two separate 'PORT' and 'A_B_C' entries).

This guy's problem was similar (https://community.grafana.com/t/how-do-i-search-nested-elements/2748/4) as mine, but I think he was forgetting the quotes (and he was doing nested where I'm doing multi-field).

I don't know where to go from here. My only other thought is to explode the port_name string on non-alphanumeric characters and use the chunks in a Lucene field grouping in the scripting dashboard... but that seems like total overkill considering this is the reason why not_analyzed fields exist in Elasticsearch.

<img width="656" alt="screen shot 2019-01-07 at 2 43 30 pm" src="https://user-images.githubusercontent.com/6422012/50789585-ac7a6500-128a-11e9-8d98-884ffcaa1dc9.png">

Thanks for the response and time - happy new year!

**Comment by ryanjohara** [comment]
For anyone else having the same issue, you can use Lucene Field Groupings to accomplish expected behavior.

![image](https://user-images.githubusercontent.com/6422012/50906274-bdde8100-13f2-11e9-8b73-d00a33bcda44.png)
