### ISSUE TITLE
Dropdown unreachable when moved to right

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#14588]
In grafana 5,

The dropdown menu is not clickable when moved to left (by small screen size):

![probmenu](https://user-images.githubusercontent.com/291750/50215203-96137480-0382-11e9-8fda-dc47ee8db67d.png)

**Comment by daniellee** [comment]
Seems to be fixed:

![image](https://user-images.githubusercontent.com/434655/98866680-9da7ff00-246d-11eb-914c-adc8b08ec1ed.png)
