### ISSUE TITLE
grafana 5.4.1 Service init failed:Migration failed err:disk I/O error

### ISSUE THREAD

**Issue by zzabc007** [grafana/grafana#14584]
I run grafana through docker and the data is persisted to nfs. When updating from 5.1.0 to 5.4.1, restarting docker images fails. Thank you very much for any help.

The docker configuration is as follows:
Grafana:
Privilege: Real
Mem_limit: 4294967296
Photo: grafana / grafana: 5.4.1
    surroundings:
GF_PATHS_CONFIG: /var/lib/grafana/conf/defaults.ini
GF_PATHS_DATA: / var / lib / grafana
GF_PATHS_HOME: / usr / share / grafana
GF_PATHS_LOGS: / var / lib / grafana / logs
GF_PATHS_PLUGINS: / var / lib / grafana / plugins
GF_PATHS_PROVISIONING: / var / lib / grafana / provisioning
GF_SECURITY_ADMIN_PASSWORD: Password
GF_SERVER_ROOT_URL: http://grafana.test.com
Stdin_open: Yes
Volume:
- nfs-libgrafana:/ var / lib / grafana
Tty: Yes.
Label:
Io.rancher.container.pull_image: Forever

Log output:
t=2018-12-19T09:30:15+0000 lvl=info msg="Starting Grafana" logger=server version=5.4.1 commit=308c818 branch=HEAD compiled=2018-12-10T14:08:32+0000
t=2018-12-19T09:30:15+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-12-19T09:30:15+0000 lvl=info msg="Config loaded from" logger=settings file=/var/lib/grafana/conf/defaults.ini
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/lib/grafana/logs"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/var/lib/grafana/provisioning"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/lib/grafana/logs"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=http://grafana.sre.youguoquan.com"
t=2018-12-19T09:30:15+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
t=2018-12-19T09:30:15+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-12-19T09:30:15+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-12-19T09:30:15+0000 lvl=info msg="Path Logs" logger=settings path=/var/lib/grafana/logs
t=2018-12-19T09:30:15+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-12-19T09:30:15+0000 lvl=info msg="Path Provisioning" logger=settings path=/var/lib/grafana/provisioning
t=2018-12-19T09:30:15+0000 lvl=info msg="App mode production" logger=settings
t=2018-12-19T09:30:15+0000 lvl=info msg="Initializing HTTPServer" logger=server
t=2018-12-19T09:30:15+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2018-12-19T09:30:15+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2018-12-19T09:30:15+0000 lvl=eror msg=ShowSQL logger=sqlstore.xorm show=show
t=2018-12-19T09:30:15+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-12-19T09:30:15+0000 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 3.000774ms" logger=sqlstore.xorm
t=2018-12-19T09:30:15+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: disk I/O error"

**Comment by torkelo** [comment]
Looks like an issue with write permissions:

Read this upgrade guide for upgrading from v5.1 or earlier 
http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later

**Comment by zzabc007** [comment]
Thank you for your reply。
The above is the operation of this document. 
In addition, New start a default grafana/grafana: 5.4.2, everything works fine.
but mount nfs disk to /var/lib/grafana. The same error reappears.
"Service init failed: Migration failed err: disk I/O error"

**Comment by zzabc007** [comment]
New start a default grafana/grafana: 5.4.2, everything works fine. 
I mount nfs to a non-used directory /data, open the container, enter the system, the current user is grafana, then operate /data directory to write files, delete Files are fine.
But mounting this nfs to /var/lib/grafana is an error.
