### ISSUE TITLE
Move Azure Monitor into Grafana

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#14586]
The goal is to support the 3 major clouds in core Grafana. Support for Azure will be added by moving the external Azure Monitor datasource plugin into core Grafana. 

The Azure Monitor supports 4 different API's and their datasource logic needs to be ported to Go to support alerting.

The Azure Monitor Log Analytics support uses the Monaco editor for writing code. This is a very large dependency so need to decide if we should keep it. We could port it to Slate and rebuild the Kusto language intellisense ourselves. Or we could try and reduce the size of the dependency.

**Comment by torkelo** [comment]
closing this as it already moved into Grafana core
