### ISSUE TITLE
Ability to configure Alert on histogram based on variable

### ISSUE THREAD

**Issue by craph** [grafana/grafana#14596]
Hello,

I would like to know if it is possible to configure the condition of an Alert when my histogram graph is based on a dynamic datasource ? 

I would like to have different Alert in function of the datasource.

Best regards,

**Comment by torkelo** [comment]
no this is not supported

**Comment by craph** [comment]
@torkelo  Why you close this issue ? it's may be an improvment !

I have a dynamic histogram based on dynamic datasource and I want to have alert.

**Comment by torkelo** [comment]
Because we already have an issue for this that I linked to

**Comment by craph** [comment]
Can you make an update about this issue ?

**Comment by torkelo** [comment]
no update, it's not on any roadmap, very unlikely that it will be ever implemented
