### ISSUE TITLE
Top-level return scripted dashboard

### ISSUE THREAD

**Issue by TomasSchlepers** [grafana/grafana#14598]
Good afternoon,

At the moment I am implementing the scripted dashboards feature of Grafana in our own application by making them visible through an iFrame.

The scripted dashboard is an asynchronous variant and as such, I have used the scripted_async.js example to build upon.

However, when trying to perform some babel on my own scripted dashboard file I get the error that the 'return' statement is outside of a function. Which is true, as the declaration is:

return function(callback) {
 ....
 callback(dashboard)
}

The question I have is, why this is made this way, and if there is any possibility to change this to another form with the same functionality but babel compliant.
I have the following specs: 

Grafana v5.3.4

and am using the following packages for browserify/babelify:
 "@babel/core": "^7.2.0",
 "@babel/preset-env": "^7.2.0",
 "babelify": "^10.0.0",
 "browserify": "^16.2.3",

If this is not possible that's also OK, but as I've read, these top-level return statements are, apparently, not compliant with ES6?
I'm terribly sorry if this is a dumb question by the way.

**Comment by torkelo** [comment]
babel is not supported in scripted dashboards. Scripted dashboards is a deprecated feature we want to retire and replace by something else. Until then I recommend building the dashboard programmatically and use the dashboard provisioning feature.
