### ISSUE TITLE
No favorites listed when creating playlists in demo for 2.0a preview.

### ISSUE THREAD

**Issue by rafrey** [grafana/grafana#1460]
Please see subject and attached image (this is on the new live demo site). Thanks.

![image](https://cloud.githubusercontent.com/assets/9465135/6142730/65627de0-b179-11e4-8b8c-fa082fc48057.png)

**Comment by torkelo** [comment]
Thanks for reporting this, have not updated the playlist to use the backend stars api.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/6184033/213ba96c-b35d-11e4-88a4-d5ea7171fcda.png)

Fixed this and added a search field so you can add non starred dashboards to dashboards as well. Default (with empty search field) it will list starred dashboards.
