### ISSUE TITLE
Incorrect timestamp on alert history

### ISSUE THREAD

**Issue by brad-plumewifi** [grafana/grafana#14607]
### What happened instead? The timestamps on the state change history are showing from 1970.  Server time and Grafana/dashboard time(s) are all set to UTC.  Every other grafana component (dashboard, panel, etc) is displaying accurate timestamps. 

![image](https://user-images.githubusercontent.com/29928973/50254508-1e097680-03a3-11e9-9367-66e133f617a1.png)

**Comment by torkelo** [comment]
we might be able to solve this when doing this: https://github.com/grafana/grafana/issues/14388

**Comment by marefr** [comment]
Fixed in #14388
