### ISSUE TITLE
Add option to filter out null values from CSV export

### ISSUE THREAD

**Issue by afuggetta** [grafana/grafana#14604]
### What Grafana version are you using?
Using v5.3.4, tested also on v5.5.0-pre1

### What datasource are you using?
Elasticsearch

### What OS are you running grafana on?
CentOS, MacOS

### What did you do?
Exported CSV from dashboard

### What was the expected result?
Not seeing null values in the report. Export was including dates where I have no data.

### What happened instead?
Rows with null data were included, cluttering the report

 
I have forked the repo and added a fix that works for me. But wanted to open an issue to check if this is some mistake on my part.

Thank you,
Andrea

**Comment by torkelo** [comment]
We want export to not modify & hide data by default, but adding an option to filter out null values could be an option.

**Comment by afuggetta** [comment]
Agreed @torkelo, I have created a PR (#14606) for this.

Thank you

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
