### ISSUE TITLE
Table - Column Styles - Highlighting issues

### ISSUE THREAD

**Issue by JoshWisniewski** [grafana/grafana#14601]
### What Grafana version are you using? 
v5.3.2
### What datasource are you using? 
MariaDB through MySQL DataSource
### What OS are you running grafana on? 
x86 Linux, Red Hat I think
### What happened instead?

I've had a world of trouble using the highlight feature in the table panel.  Near as I can tell, it only highlights if all values in the column are between 0 and 100.  It's not obvious I can't have ranges like .4,.7 with my range between .01 and .99 or etc.  That was easy enough to work around, I normalized my data to a 100 scale.  But I still see weird behaviors.  For example, I have a range of 40,60 on column D and things work fine highlighting the cell:

![image](https://user-images.githubusercontent.com/44438838/50229538-90189600-0378-11e9-9930-716a2ce91b28.png)

But for column T, I have a range of 12,24, a row clearly has a value in the middle range, and it doesn't highlight.

![image](https://user-images.githubusercontent.com/44438838/50229635-c48c5200-0378-11e9-9f72-bd7371d27e9e.png)

At times, I think convince myself it only highlights based upon the right most column.  I've tried switching things around, different numeric scales, no numbers to the right of the decimal and other iterations.  I don't see a way of diagnosing what's gone wrong.  Any help is greatly appreciated.

Here's the request results.  Let me know if you require other diagnostics.  Thanks!
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1541437978861",
      "to": "1541438188137",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 200,
          "maxDataPoints": 960,
          "datasourceId": 4,
          "rawSql": "If 'Reactive'=\"Reactive\"\nTHEN  \n  CALL tpf_agg_corr_table_builder('MsgTypeMsgCntCPUCor',$__timeFrom(),$__timeTo(),60,1,10,\"\",'ToCorr');\nELSE\n  CALL tpf_agg_corr_table_builder('MsgTypeMsgCntCPUCor',$__timeFrom(),$__timeTo(),48,15,10,\"\",'ToCorr');\nEND IF;",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 4,
          "sql": "If 'Reactive'=\"Reactive\"\nTHEN  \n  CALL tpf_agg_corr_table_builder('MsgTypeMsgCntCPUCor','2018-11-05T17:12:58Z','2018-11-05T17:16:28Z',60,1,10,\"\",'ToCorr');\nELSE\n  CALL tpf_agg_corr_table_builder('MsgTypeMsgCntCPUCor','2018-11-05T17:12:58Z','2018-11-05T17:16:28Z',48,15,10,\"\",'ToCorr');\nEND IF;"
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "MsgType"
              },
              {
                "text": "FromCoef"
              },
              {
                "text": "ToCoef"
              },
              {
                "text": "CoefDelta"
              },
              {
                "text": "FromPctTrf"
              },
              {
                "text": "ToPctTrf"
              },
              {
                "text": "PctTrfDelta"
              },
              {
                "text": "T"
              },
              {
                "text": "D"
              }
            ],
            "rows": [
              [
                "Shopping",
                "0.15",
                "0.75",
                "0.60",
                "90.27",
                "91.97",
                "1.70",
                "19.9",
                57
              ],
              [
                "Booking",
                "0.06",
                "0.05",
                "-0.00",
                "9.13",
                "7.86",
                "-1.27",
                "0.0",
                0
              ],
              [
                "Checkin",
                "-0.11",
                "-0.11",
                "-0.00",
                "0.60",
                "0.16",
                "-0.44",
                "0.0",
                1
              ],
              [
                "UltraRareMsg",
                "0.00",
                "0.00",
                "0.00",
                "0.02",
                "0.02",
                "-0.00",
                "0.0",
                0
              ]
            ]
          }
        ]
      }
    }
  }
}

**Comment by torkelo** [comment]
strange, works here: https://play.grafana.org/d/FqhDdVsmz/table-panel-issue?panelId=2&fullscreen&edit&orgId=1&tab=column%20styles

Looks like the T column returns strings not numbers as the D column returns. Can you cast the column to a number in your query?

**Comment by JoshWisniewski** [comment]
[face palm]  Yup, I was using the MariaDB FORMAT which returns a string. Might be nice to have some diagnostics on the column styles tab....like "hey dummy, this column is full of of strings not numbers!"

 Thank you very much for the help.
