### ISSUE TITLE
Page 404 error

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14602]
I am getting Page 404 error when I click manage option.
PLease help me out.
![thi](https://user-images.githubusercontent.com/22325249/50231215-452c6c00-03d4-11e9-800b-a8afd6eff955.PNG)

**Comment by marefr** [comment]
You have to provide more detailed information. What version of Grafana? What commit? Are you using a reverse proxy, if so have you read [documentation](http://docs.grafana.org/installation/behind_proxy/#running-grafana-behind-a-reverse-proxy)? Which reverse proxy are you using? What does the reverse proxy configuration look like together with Grafana proxy specific config?

**Comment by Siddhu1096** [comment]
Grafana v5.4.2 (commit: d812109)
No I'm not using reverse proxy

**Comment by torkelo** [comment]
Where are you clicking???

**Comment by torkelo** [comment]
closing due to lack of updates
