### ISSUE TITLE
Piechart panel render png image take long time

### ISSUE THREAD

**Issue by yekaifeng** [grafana/grafana#14618]
It takes 60s to render a pie chart png image which is too long. It might cause server timeout.

![image](https://user-images.githubusercontent.com/17564158/50329349-e11fba00-0531-11e9-9886-8f3c9e1ed381.png)

### What Grafana version are you using?
v5.3.1
### What datasource are you using?
TestData DB
### What OS are you running grafana on?
Utunbu in Docker
### What did you do?
- spin up grafana docker image, mount the plugin volume to external host volume
~~~
# mkdir /dockermnt
# chmod 777 /dockermnt
# docker run -d --name=grafana5 -p 3000:3000 -v /dockermnt:/var/lib/grafana grafana/grafana:5.3.1
~~~

- install piechart plugin in grafana5 docker
~~~
# docker exec -it grafana5 /bin/bash
# grafana-cli plugins install grafana-piechart-panel
# exit
# docker restart grafana5
~~~

- open the grafana UI and create data source with "TestData DB"
![image](https://user-images.githubusercontent.com/17564158/50328652-e596a380-052e-11e9-8d56-b192aee13a61.png)

- create dashboard test panel with Pie Chart
![image](https://user-images.githubusercontent.com/17564158/50329272-753d5180-0531-11e9-8b53-0adb81c8bb70.png)

- share the pie chart in png 
![image](https://user-images.githubusercontent.com/17564158/50328843-bc2a4780-052f-11e9-8eb9-1d382165e0f4.png)

- open "Direct link rendered image"
![image](https://user-images.githubusercontent.com/17564158/50328879-dbc17000-052f-11e9-88e4-2efe97b75d02.png)

### What was the expected result?
Expect the image open in several seconds

### What happened instead?
Actually it takes 60 seconds. The performance index from chrome is up above showed.

### If related to metric query / data viz:
- the grafana logs in docker is below
![image](https://user-images.githubusercontent.com/17564158/50329111-b2edaa80-0530-11e9-9e19-233871a32c42.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![image](https://user-images.githubusercontent.com/17564158/50329379-03193c80-0532-11e9-8587-3c1be91397e1.png)

**Comment by torkelo** [comment]
thanks for reporting this, I just pushed a new version of the pie chart panel 1.3.4 that should fix this, https://grafana.com/plugins/grafana-piechart-panel
