### ISSUE TITLE
login.OAuthLogin(NewTransportWithCode) UAA Bad Credentials

### ISSUE THREAD

**Issue by Murugan2all** [grafana/grafana#14613]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
v5.2.4
### What OS are you running grafana on?
14.04.1-Ubuntu
### What did you do?
Upgrading Prometheus from 21.1 to 23.3
### What was the expected result?
Upgrade successful but UAA not working.
### What happened instead?
Not able to authenticate with UAA

When authenticate using UAA, getting the below error:

login.OAuthLogin(NewTransportWithCode)

In Grafana log,
t=2018-12-20T09:49:42+0000 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"unauthorized\",\"error_description\":\"Bad credentials\"}"

I deployed the Prometheus using Github URL: https://github.com/bosh-prometheus/prometheus-boshrelease.

**Comment by torkelo** [comment]
Looks like a credentials / setup issue. 

Verify your oauth settings. 

Please ask questions on the community site https://community.grafana.com

**Comment by Murugan2all** [comment]
Please find the config details below.

[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = grafana
client_secret = hello123!
scopes = openid
auth_url = https://login.system.*.com/oauth/authorize
token_url = https://login.system.*.com/oauth/token
api_url = https://login.system.*.com/userinfo
name = Cloud Foundry
tls_client_ca = /var/vcap/jobs/grafana/config/generic_oauth_tls_client_ca.pem
tls_client_cert = /var/vcap/jobs/grafana/config/generic_oauth_tls_client_cert.pem
tls_client_key = /var/vcap/jobs/grafana/config/generic_oauth_tls_client_key.pem
tls_skip_verify_insecure = true
