### ISSUE TITLE
Grafana 2.0 - Save Unknown Error

### ISSUE THREAD

**Issue by damm** [grafana/grafana#1461]
Hi,

I was playing with grafana in the `develop` branch and it works great (except for saving).  I'm at commit 8d130421c4a4910da718ce9a74c991d827dae9f0 for the record.

I started using it and it was working just fine but after a few hours running it seems some functions are timing out.  Save sometimes gives an Unknown error; and sometimes I get connection timeouts.

I think I'll run it under docker using your Dockerfile in the future; but that's kind of annoying.

P.S. I did try enabling Debug in `grafana.ini` but it did not seem to give more output when I restarted `grafana web`.

Really outstanding work thank you so much for your hard work.

**Comment by torkelo** [comment]
@damm that is strange. I have not seen that on the instance running on play.grafana.org/v2 ,
never seen timeout issues, where the timeouts on the data source proxying or on a regular api request? 

What I have seen are strange 401 (access denied) errors that seem to come up very rarely, did try to run a ab (apache benchmark tool) to run 200000 and 100 concurrent requests to see if I could replicate any strange behavior, so far failed. If you get an error (like unknown error in the UI), there should be rror details in the log output to the console, the file logging stuff is not implemented yet (mostly a config setup issue that is not done)

**Comment by damm** [comment]
@torkelo I avoided proxying as everything is direct.  I suspect it might have been something strange with my host (or it could be sqlite3 blocking requests).

I'll dig in a little more today to get you more information.  Just had problems getting debug mode up.

**Comment by akamanocha** [comment]
Did you get anything on the same? I am having same issue. All local, graphite and grafana and I can see the graphite-web dashboard but cannot get the datasource on grafana.

One thing though that what should be given in datasource? May be a graphite question but whether its should graphite-web url like localhost:8080 or something else graphite port?

**Comment by damm** [comment]
I actually switched to a mysql backend as I suspected sqlite3 to be the cause of it.

Kinda shocking as my root device is SSD so sqlite3 should be blazing.  

I suspect this ticket could be closed as this is fairly old and the context is pretty much lost to me already.
