### ISSUE TITLE
Postgres won't generate sub second queries

### ISSUE THREAD

**Issue by antiquechrono** [grafana/grafana#14614]
### What Grafana version are you using?
5.4.2

### What datasource are you using?
Postgres10/Timescale

### What OS are you running grafana on?
Linux/MacOSX

Grafana won't generate any queries that go below a second and this is causing disappearing data and dashboards that aren't filled out on the right hand side.

If I zoom in on a graph so only a few seconds are visible it generates a query like the following

SELECT
  time_bucket('0.05s',"time") AS "time",
  avg(value) AS "value"
FROM table
WHERE
   "time" BETWEEN '2018-12-20T08:52:50Z' AND '2018-12-20T08:52:54Z'
GROUP BY 1
ORDER BY 1
 
The where clause above should have millisecond resolution. Both the data source and the query are set to 1ms minimum resolution.

**Comment by torkelo** [comment]
@svenklemm can you investigate this?

**Comment by svenklemm** [comment]
I'll take a look, might get lost somewhere
