### ISSUE TITLE
Stackdriver Custom Metrics not rendering any data values in Grafana

### ISSUE THREAD

**Issue by michaelsmithhx** [grafana/grafana#14622]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.3.4

### What datasource are you using?
Stackdriver

### What OS are you running grafana on?
Linux

### What did you do?
Created a test custom metric and used the stackdriver api to create timeseries values

Our grafana admin has already enabled stackdriver integration and I see other stackdriver metrics (names and values) appearing in grafana. For the custom metric only the metric name appears (chart do no render any data)

Initial test was with a DOUBLE stackdriver metric, but have also tried a separate INT64 metric.

### What was the expected result?
Creating a dashboard with a panel attached to the custom metric should show the same values as reported in stackdriver UI.

### What happened instead?
Metric name appears when searching, but no data values are rendered

### If related to metric query / data viz:
Discussed enabling Explore with our Grafana admin to see if I can eyeball the imported data, but that wont happen until mid Jan now.

**Comment by michaelsmithhx** [comment]
![image](https://user-images.githubusercontent.com/21198230/50342419-e58ca880-051a-11e9-9542-e4a8c9844b96.png)

![image](https://user-images.githubusercontent.com/21198230/50342431-ede4e380-051a-11e9-81c8-cec93515e56b.png)

**Comment by flaviu-toader** [comment]
I am experiencing the same symptoms on Grafana 5.4.2.

**Comment by sunker** [comment]
@michaelsmithhx can you please provide the network response? 

Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by theninj4** [comment]
@sunker this should help:

Raw request:
```
{
  "from": "1546579942070",
  "to": "1546601542070",
  "queries": [
    {
      "refId": "A",
      "datasourceId": 24,
      "metricType": "custom.googleapis.com/airflow_task_duration_test",
      "primaryAggregation": "REDUCE_NONE",
      "groupBys": [],
      "view": "HEADERS",
      "filters": [],
      "type": "timeSeriesQuery"
    }
  ]
}
```
Raw response:
```
{
  "results": {
    "A": {
      "refId": "A",
      "meta": {
        "alignmentPeriod": 60,
        "groupBys": [],
        "metricLabels": {},
        "rawQuery": "aggregation.alignmentPeriod=%2B60s&aggregation.crossSeriesReducer=REDUCE_NONE&aggregation.perSeriesAligner=ALIGN_MEAN&filter=metric.type%3D%22custom.googleapis.com%2Fairflow_task_duration_test%22&interval.endTime=2019-01-04T11%3A32%3A22Z&interval.startTime=2019-01-04T05%3A32%3A22Z&view=HEADERS",
        "resourceLabels": {},
        "resourceTypes": null
      },
      "series": null,
      "tables": null
    }
  }
}
```
Breaking down the `rawQuery` in the response and comparing it with a working standard metric, the request from the browser looks legit:
```
aggregation.alignmentPeriod=+60s
aggregation.crossSeriesReducer=REDUCE_MEAN
aggregation.perSeriesAligner=ALIGN_INTERPOLATE
filter=metric.type="custom.googleapis.com/airflow_task_duration_test"
interval.endTime=2019-01-04T11:26:35Z
interval.startTime=2019-01-04T05:26:35Z
view=FULL
```
vs
```
aggregation.alignmentPeriod=+60s
aggregation.crossSeriesReducer=REDUCE_MEAN
aggregation.perSeriesAligner=ALIGN_INTERPOLATE
filter=metric.type="agent.googleapis.com/agent/memory_usage"
interval.endTime=2019-01-04T11:29:51Z
interval.startTime=2019-01-04T05:29:51Z
view=FULL
```

**Comment by sunker** [comment]
@theninj4 I still can't reproduce this. Have created a similar custom metric like the one you described. Timeseries are displayed as expected in grafana. 

There might be an issue parsing the data in the backend. Could you check the Grafana server log for error?

**Comment by marefr** [comment]
Closing this due to lack of response. Will consider reopen if you come back with more information, like Grafana server log as @sunker requrested.

**Comment by miames** [comment]
You probably need to go to Panel > Edit > Advanced Options

Set Aligner to mean or anything other than Interpolate
