### ISSUE TITLE
Firefox & New Panel Edit UX Height Bug

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#14620]
Please include this information:
### What Grafana version are you using?

Lastest Nightly v5.5.0-pre1 (2325c5d)

### What datasource are you using?

Mixed + Prom

### What OS are you running grafana on?

Linux

### What did you do?

Change overrides of a panel

### What was the expected result?

Graph is shown

### What happened instead?

Graph height goes to 0

![color](https://user-images.githubusercontent.com/291750/50335020-51b2e080-050a-11e9-831e-2d636028261d.png)

**Comment by torkelo** [comment]
What browser are you using ?

**Comment by roidelapluie** [comment]
![grafana2-1545417367 png-fixd](https://user-images.githubusercontent.com/291750/50357933-f6a7da80-0557-11e9-89d5-4a44412f4562.png)
![grafana2-1545417369 png-fixd](https://user-images.githubusercontent.com/291750/50357934-f6a7da80-0557-11e9-99f5-159a2a81c06d.png)
![grafana2-1545417373 png-fixd](https://user-images.githubusercontent.com/291750/50357936-f6a7da80-0557-11e9-9674-b41b7102f8c4.png)
![grafana2-1545417375 png-fixd](https://user-images.githubusercontent.com/291750/50357937-f6a7da80-0557-11e9-95d7-475cc210a22f.png)
![grafana2-1545417378 png-fixd](https://user-images.githubusercontent.com/291750/50357939-f7407100-0557-11e9-8dd0-d0bfc0904e4b.png)
![grafana2-1545417380 png-fixd](https://user-images.githubusercontent.com/291750/50357940-f7407100-0557-11e9-9884-607dd7f3e25d.png)
![grafana2-1545417389 png-fixd](https://user-images.githubusercontent.com/291750/50357946-f8719e00-0557-11e9-97a9-4846914753d5.png)



I use Firefox

**Comment by torkelo** [comment]
Can you replicate it in chrome?

**Comment by roidelapluie** [comment]
No. Works fine in chrome.

**Comment by torkelo** [comment]
thanks for reporting this, seems to be an issue with firefox only :(

**Comment by roidelapluie** [comment]
I will take this opportunity to congratulate the team on the new editor!! It is awesome!!

**Comment by torkelo** [comment]
Thanks! Come to GrafanaCon to see all the mockups and experiments that we tried before arriving at this :)
