### ISSUE TITLE
Can not display dashboard in playlist with autofit

### ISSUE THREAD

**Issue by olivierboudet** [grafana/grafana#14621]
Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Docker on GKE on Ubuntu Linux 
### What did you do?
I have a playlist created on Grafana 5.2.4 which include the mongodb dashboard (https://grafana.com/dashboards/2583).
### What was the expected result?
I can see the panels when I open the dashboard manually and I can see the panels when the dashboard is played in a playlist.
### What happened instead?
When I play the playlist in TV mode or in Kiosk mode **with autofit**, the panels on this dashboard are not displayed (it is OK without autofit).
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

There is a javascript error : 
```

Error: Invalid dimensions for plot, width = 1198, height = 0
    at n.resize (jquery.flot.js:180)
    at new n (jquery.flot.js:159)
    at jquery.flot.js:1369
    at new a (jquery.flot.js:759)
    at Function.t.plot (jquery.flot.js:549)
    at f (module.ts:39)
    at g (module.ts:73)
    at s.<anonymous> (Gauge.tsx:131)
    at s.emit (index.js:150)
    at t.emit (IndicatorsContainer.tsx:15) "Possibly unhandled rejection: {}"

```

**Comment by torkelo** [comment]
Strange, can you share you dashboard json?

**Comment by daniellee** [comment]
Seem to render ok for me (though have no data obviously) on Chrome on Ubuntu. What browser and OS are you using?

Can you see which panel is the problem panel or is it all of them?

**Comment by olivierboudet** [comment]
I am using Chromium (Version 71.0.3578.98 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits))

As shown in the screenshot below, the issue happens for all panels of this particular dashboard.

![image](https://user-images.githubusercontent.com/857205/51101584-7fbed400-17db-11e9-821a-02dd5a0e9378.png)

**Comment by daniellee** [comment]
I uploaded your dashboard to play.grafana.org and created a playlist (14621-troubleshooting): https://play.grafana.org/playlists/play/11?kiosk&autofitpanels

And it looks like this for me in Chromium (there is no data but the panels are rendered):

![image](https://user-images.githubusercontent.com/434655/51105089-4fc9fd80-17e8-11e9-85df-b510925194ad.png)

Does the dashboard have data in your case? Does it make a difference which time interval you choose or if you turn off the refresh? Any other info you could provide to help us troubleshoot this?

**Comment by torkelo** [comment]
closing this for now, the autofix feature is an experimental feature so might not always work. And we are unable to replicate your specific bug.
