### ISSUE TITLE
Grafana 2.0 : light theme not loaded on import dasboard

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1462]
As you can see in the following picture , the light theme is not working, even after changing to dark save and light after and reload it..

![image](https://cloud.githubusercontent.com/assets/5883405/6147343/a59e3a0c-b1f6-11e4-8993-805d1aa9a08e.png)

**Comment by torkelo** [comment]
Thanks for reporting this, fixed in develop, however the light theme does not look good currently in develop branch. I opened another issue for that (https://github.com/grafana/grafana/issues/1465)
