### ISSUE TITLE
since 5.4.1  "dashboard links" does not get correct "Current time range" and "Template variables"

### ISSUE THREAD

**Issue by konvergence** [grafana/grafana#14632]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?  
5.4.1 or 5.4.2
### What datasource are you using? 
prometheus, elasticsearch 

### What OS are you running grafana on?
Ubuntu 16.04, Docker image

### What did you do?
links beween dashboard

### What was the expected result?
pass selected time range and templating value to the other dashboard

### What happened instead?
the linked dashboard get always the 1st values of the source dashboard

**Comment by torkelo** [comment]
thanks for reporting this! but someone already has, https://github.com/grafana/grafana/issues/14493 

will be investigating this asap
