### ISSUE TITLE
singlestat, short time-frame and daily metric

### ISSUE THREAD

**Issue by loopping** [grafana/grafana#1463]
Hello,
I have a metric updated once a day with a retention of 1d:1y in graphite.
I have a dashboard where I created a singlestat for this metric.
If I choose a time-frame like "last 15 min", the metric is shown as N/A which is what it should be.
How can I have a value for the metric when using last 15 min for a singlestat ?
When using a "graph" I can use "Override relative time" but it is not available for singlestat.
Is there a trick I haven't noticed ?
Regards

**Comment by torkelo** [comment]
Not currently, the override relative time option will be added to the singlestat panel, just not sure how to visualize that the panel is not using the dashboard time range, 

The override relative time option is part of this issue #171 , which is not closed yet as I requested some feedback on how to handle this for the singlestat panel. Any ideas?
