### ISSUE TITLE
Explore: Logging dedup tooltip gets in the way

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14634]
Try hovering over the dedup options from left to right in the Loki UI. The tooltip gets in the way.

![loki-interface](https://user-images.githubusercontent.com/859729/50376195-4cd55600-060a-11e9-864a-67d114a251ec.gif)

**Comment by torkelo** [comment]
Strange , what browser are you using ? For me it shows above

**Comment by davkal** [comment]
I'm on Chrome. This was reported and screengrabbed by @briangann though
