### ISSUE TITLE
Feature Request: ElasticSearch as db backend for Grafana 2.0 instead of sqlite3

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1464]
We are running with Grafana 1.9 + Elasticsearch on 2 servers ( in active/active mode)  each server has one ElasticSearch instance and are  working in cluster.

I like the automatic clustering and replication features in elasticsearch but when migrating Grafana 1.9 to Grafana 2.0 , I will lose database automatic  replication features with sqlite3.

Could be  possible  add ElasticSearch ( or other similar backend) as database?

**Comment by torkelo** [comment]
no, do not think so, Elasticsearch is not really suitable as a regular db (not data security, transactions, etc) and not really suitable for storing users, accounts, data source config etc. 

If you want db replication for the grafana 2.0 database the only option currently is mysql or postgres (in a master/slave setup)
