### ISSUE TITLE
Dashboard importing does not work on 5.*.* and 5.4.0

### ISSUE THREAD

**Issue by andloh** [grafana/grafana#14643]
FYI. 

Dashboard imports (all kinds) does not work on 5.*.* and 5.4.0
Is works on 5.3.0

When you import a dashboard, non of the graphs shows up.

**Comment by torkelo** [comment]
Strange, can’t replicate and no other reports like this. Can you share the dashboard json you are trying to import?

**Comment by torkelo** [comment]
Strange, works here: 

<img width="823" alt="screen shot 2018-12-24 at 06 13 17" src="https://user-images.githubusercontent.com/10999/50391308-41d21100-0743-11e9-9720-da529c12416f.png">

After this I get to view the dashboard. 

What error do you see in the web browser console (chrome dev tools)
