### ISSUE TITLE
Bar graph reset at 01:00

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#14640]
What Grafana version are you using? 5.4.2
What datasource are you using? Influxdb
What did you do? I made bars graph and group the data by 1 day.
What was the expected result? New bar should be created everyday at 00:00
What happened instead? New bar is being created everyday at 01:00
![przechwytywanie](https://user-images.githubusercontent.com/19311511/50379116-6e513480-0640-11e9-8853-477252207512.PNG)

**Comment by torkelo** [comment]
This is due to InfluxDB uses UTC timezone when grouping by day. 

We just merged support for influxdb timezone clause https://github.com/grafana/grafana/pull/14627

You can try latest nightly build and add a tz clouse by using the plus button after fill (null)
