### ISSUE TITLE
Explore: metric name is not clickable

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#14654]
### What Grafana version are you using?

Nightly from this morning (5.5)

### What datasource are you using?

Prometheus

### What did you do?

type `{job="broker"}` in explore

### What was the expected result?

I can then click on metric name and see `metric_name{job="broker"}` in the search.

### What happened instead?

Metric name is not clickable in the table

![reco](https://user-images.githubusercontent.com/291750/50400704-fb9fa080-0788-11e9-8782-79a167d18c02.png)

**Comment by davkal** [comment]
I have that issue too. Will work on this
