### ISSUE TITLE
Failed to create team

### ISSUE THREAD

**Issue by sslupsky** [grafana/grafana#14650]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.4.2

### What datasource are you using?
Influx

### What OS are you running grafana on?
Amazon Linux 2

### What did you do?
Attempted to create a team

### What was the expected result?
Team created.

### What happened instead?
Received "Failed to create team" error message.
I inspected grafana.log and noticed the following error:
t=2018-12-23T20:15:37+0000 lvl=eror msg="Failed to create Team" logger=context userId=3 orgId=277 uname=<myuserid> error="pq: null value in column \"id\" violates not-null constraint"

**Comment by torkelo** [comment]
strange, do you get this all the time? Creating from the UI? 

what browser are you using?

**Comment by torkelo** [comment]
closing due to lack of replication details

**Comment by sslupsky** [comment]
Apologies, I was away during the Christmas break.

I am using Safari.

I am creating the user from the UI.

**Comment by sslupsky** [comment]
This is the first time I attempted to create a team.

**Comment by sslupsky** [comment]
@torkelo I updated the issue with some additional details.

I note that the error message says the there is a null value for the id.  However, it doesn't say which table it is attempting to write to.  I assume its the team table but perhaps it is a different table?  As mentioned earlier, at the moment the Team table is empty.

**Comment by torkelo** [comment]
What Postgres version are you using?

**Comment by sslupsky** [comment]
I am using Amazon RDS.  The engine version is 10.4.

**Comment by sslupsky** [comment]
Hi @torkelo, apologies, I think because this issue is closed you may not have seen my earlier reply:

I am using Amazon RDS. The engine version is 10.4.

**Comment by pva** [comment]
We have same problem. Please, reopen issue.

**Comment by seanhoughton** [comment]
Same issue with my group on `v7.4.3 (010f20c1c8)` with the same error listed in the initial report. We're using the GCP Cloud DB backend.

Here's what's failing:

```
ERROR: null value in column "id" violates not-null constraint
DETAIL: Failing row contains (null, my-team, 1, 2021-03-19 17:00:47, 2021-03-19 17:00:47, sean.houghton@foo.com).
STATEMENT: INSERT INTO "team" ("org_id","name","email","created","updated") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
```
