### ISSUE TITLE
Explore: promql: Label is added in by () clause

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#14655]
### What Grafana version are you using?

Nightly from this morning

### What datasource are you using?

Prometheus

### What did you do?

In explore, create a sum by () query,
then click on a label in the bottom.

### What was the expected result?

Label is applied only on the metric

### What happened instead?

Label is applied on the metric and the by() clause, making the query failed.

![reco2](https://user-images.githubusercontent.com/291750/50400820-11619580-078a-11e9-8d97-3c93d2d63d08.png)

**Comment by aocenas** [comment]
This does not seem to be happening anymore. Closing this but feel free to reopen if it happens again.
