### ISSUE TITLE
Docs feedback: reference/templating.md

### ISSUE THREAD

**Issue by kalanithiM** [grafana/grafana#14653]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by kalanithiM** [comment]
How to use the Variable values in sql queries for grafana dashboard

**Comment by torkelo** [comment]
http://docs.grafana.org/features/datasources/mysql/#using-mysql-in-grafana
