### ISSUE TITLE
5.2.3 to 5.4.2 open-falcon variables query failed

### ISSUE THREAD

**Issue by ning1875** [grafana/grafana#14663]
### What Grafana version are you using?
v5.4.2 
### What datasource are you using?
open-falcon
### What OS are you running grafana on?
debian 8.10
### What did you do?
After upgrading from 5.2.3 to 5.4.2, the request is redirected by 301 when the open-falcon data source variable is queried, and an error is reported: Templating
Template variables could not be initialized: Not found. I compared the request uris of versions 5.2.3 and 5.4.2, which are the same: /api/datasources/proxy/21/metrics/find/?query=n1%2B, The 5.2.3 version can query the results normally, but the error is 5.4.2.

But the data query is OK, the chart can be displayed normally, is there any problem?
My code is based on tag v5.4.2 and incorporates some of my own changes, which are limited to judging user roles when sso logs in.
My upgrade process is: replace the compiled binary, and find a grafana_5.4.2_amd64.deb package for a machine that has not installed grafana, copy the /usr/share/grafana folder scp to the machine to be upgraded. Replaced the front-end file inside the folder### What was the expected result?

**Comment by ning1875** [comment]
The latest test: I found a grafana_5.4.2_amd64.deb package for a machine that has not installed grafana, and installed the open-falcon data source. The test results are the same, indicating that the new version 5.4.2 supports open-falcon data source. has a problem
![qq 20181227111552](https://user-images.githubusercontent.com/20356568/50463893-12ccd100-09c9-11e9-9756-dae011f91775.jpg)

**Comment by torkelo** [comment]
please open an issue with the open falcon plugin repo: https://github.com/open-falcon/falcon-plus

**Comment by ning1875** [comment]
> please open an issue with the open falcon plugin repo: https://github.com/open-falcon/falcon-plus
no no,This is not an open-falcon problem, this is the problem caused by the grafana upgrade.

**Comment by torkelo** [comment]
It looks like an open falcon issue (it’s returning 404)

**Comment by ning1875** [comment]
> It looks like an open falcon issue (it’s returning 404)

![image](https://user-images.githubusercontent.com/20356568/50469475-82ea4f80-09e7-11e9-8838-b64e0afe2b0e.png)

It didn't request for falcon's api at all. It was directly redirected by 301 to the uri of grafana api
from /api/datasources/proxy/2/metrics/find/?query=.*  to  /api/v1/grafana/metrics/find?query=.*
