### ISSUE TITLE
Able to see user password in dev tools 

### ISSUE THREAD

**Issue by razahasan1984** [grafana/grafana#14664]
When I enter username and password in login page I can see password is appearing in browser devtools. Is there is a way to encrypt it before submit credential ?

Following message appears in browser  DevTool

---angular.js:12837 POST https://grafanatest/login 401
(anonymous) @ angular.js:12837
g @ angular.js:12564
u @ angular.js:12312
u @ angular.js:17145
(anonymous) @ angular.js:17193
$digest @ angular.js:18331
$apply @ angular.js:18628
(anonymous) @ angular.js:27456
dispatch @ jquery.js:5206
g.handle @ jquery.js:5014

-----angular.js:14794 Possibly unhandled rejection: {"data":{"message":"Invalid username or password"},"status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"login","data":{"user":"admin","email":"","password":"addmin"},"retry":0,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"complete"}

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by torkelo** [comment]
Yes , if you use https (SSL) , you can set that up in grafana or a reverse proxy .

You will still be able to view this in chrome dev tools yourself but over the network all the traffic will be encrypted.

In the database grafana stores passwords hashed and salted (so not even storing the original)
