### ISSUE TITLE
table panel treats string columns as numbers

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#14660]
Please include this information:
### What Grafana version are you using?
 Grafana v5.3.4 (commit: 69630b9) 
### What datasource are you using?
clickhouse
### What OS are you running grafana on?
debian 9
### What did you do?
display query results using table
### What was the expected result?
query result is displayed fully as a string
### What happened instead?
the result was treated as a number and rounded after a certain point

![screen shot 2018-12-26 at 14 13 33](https://user-images.githubusercontent.com/4352719/50445683-fc673c80-0918-11e9-9d21-cfe160932339.png)

![screen shot 2018-12-26 at 14 14 27](https://user-images.githubusercontent.com/4352719/50445690-012bf080-0919-11e9-9dfd-2ee72d398d3b.png)

**Comment by torkelo** [comment]
Think this is not the table panel doing this but maybe the clickhouse data source that tries to cast the string to number so what the table panel is seeing is not a string. 

Coiuld not replicate the issue: 
<img width="1414" alt="screen shot 2018-12-27 at 06 42 29" src="https://user-images.githubusercontent.com/10999/50467319-a4751800-09a2-11e9-8c0d-9fc3b2269117.png">
