### ISSUE TITLE
Add support for PostgreSQL scram-sha-256 authentication 

### ISSUE THREAD

**Issue by jacks33** [grafana/grafana#14662]
Read before posting: 

Hello,

Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
PostgreSQL 11
### What OS are you running grafana on?
centos 7.5
### What did you do?
Test a datasource connection to postgres with password "scram-sha-256" authentification.
### What was the expected result?
connexion ok
### What happened instead?
error:  pq: unknown authentication response: 10
### If related to metric query / data viz:
NO
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
{alertingEnabled: true, alertingErrorOrTimeout: "alerting", alertingNoDataOrNullValues: "no_data",…}
alertingEnabled: true
alertingErrorOrTimeout: "alerting"
alertingNoDataOrNullValues: "no_data"
allowOrgCreate: true
appSubUrl: ""
authProxyEnabled: false
buildInfo: {buildstamp: 1544705363, commit: "d812109", env: "production", hasUpdate: false, isEnterprise: false,…}
datasources: {,…}
-- Grafana --: {meta: {type: "datasource", name: "-- Grafana --", id: "grafana",…}, name: "-- Grafana --",…}
meta: {type: "datasource", name: "-- Grafana --", id: "grafana",…}
name: "-- Grafana --"
type: "datasource"
-- Mixed --: {meta: {type: "datasource", name: "-- Mixed --", id: "mixed",…}, name: "-- Mixed --",…}
PostgreSQL: {id: 1, jsonData: {postgresVersion: 1100, sslmode: "disable", timescaledb: false},…}
id: 1
jsonData: {postgresVersion: 1100, sslmode: "disable", timescaledb: false}
postgresVersion: 1100
sslmode: "disable"
timescaledb: false
meta: {type: "datasource", name: "PostgreSQL", id: "postgres",…}
name: "PostgreSQL"
type: "postgres"
url: "/api/datasources/proxy/1"
defaultDatasource: "PostgreSQL"
disableLoginForm: false
exploreEnabled: false
externalUserMngInfo: ""
externalUserMngLinkName: ""
externalUserMngLinkUrl: ""
googleAnalyticsId: ""
ldapEnabled: false
panels: {alertlist: {baseUrl: "public/app/plugins/panel/alertlist", hideFromList: false, id: "alertlist",…},…}

response/

{results: {,…}, message: "pq: unknown authentication response: 10"}
message: "pq: unknown authentication response: 10"
results: {,…}
tempvar: {error: "pq: unknown authentication response: 10", refId: "tempvar", meta: {sql: "SELECT 1"},…}
error: "pq: unknown authentication response: 10"
meta: {sql: "SELECT 1"}
refId: "tempvar"
series: null
tables: null

Thank you

**Comment by torkelo** [comment]
We need to update the golang postgres lib, https://github.com/go-pg/pg/blob/master/CHANGELOG.md 

they added support for scram-sha-256 recently

**Comment by SamuelToh** [comment]
@torkelo I was looking at this issue for a bit and realised that Grafana is actually using _/lib/pq_ as its database driver.  

Reference:
https://github.com/grafana/grafana/blob/master/Gopkg.toml#L120

Not sure Grafana is using _go-pg_ or not. Tried `grep`'ing around but couldn't find any trace.

Unfortunately _/lib/pq_ does not have support for SCRAM authentication yet. So I think this is blocked until [**this**](https://github.com/lib/pq/issues/817) is resolved.

**Comment by RobAtticus** [comment]
Just an update, if Grafana is using lib/pq, they added scram-sha-256 support as of 1.1:
https://github.com/lib/pq/releases/tag/v1.1.0

(PR here https://github.com/lib/pq/pull/833)
