### ISSUE TITLE
Can't create external snapshot

### ISSUE THREAD

**Issue by LonelyDude** [grafana/grafana#14675]
Grafana version: Grafana v4.6.4 (commit: 1ad5b02).
Datasource: InfluxDB.
OS: Ubuntu.

Issue:
I tried to create external snapshot with API. But Grafana returned me 
local snapshot. (i passed "external" param and i have default external snapshot url as railtank).
I expected that i would get "url" field in json like "https://snapshot.raintank.io/dashboard/snapshot/lolkekcheburek" but instead i had "https://analytics.amazinghiring.com/dashboard/snapshot/lolkekcheburek". And even this local snapshot didn't work. Also i need datapoints when i pass dashboard scheme in json to create snapshot but i have no idea how to get it with public API.

**Comment by bergquist** [comment]
Snapshots cannot be created using the API directly. You need to create it from within Grafana so the frontend can get all the data points your currently viewing and post them to the backend.

**Comment by LonelyDude** [comment]
Yeah, but what is this http://docs.grafana.org/http_api/snapshot/
