### ISSUE TITLE
Graph Tooltip, Single mode show all overlapping points 

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#14676]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
ElasticSearch 6.5.4
### What OS are you running grafana on?
Debian 9.5.0
### What did you do?
Making graph for alerting purpose in Grafana.
I activate Single value in Hover tooltip.
### What was the expected result?
Display only the value when you hover over it. 
### What happened instead?
When there is multiple values overriding each over, you can't see the over value who are hiding behind.
I have to activate all series in hover tooltip but this can result in a massive "block" displaying in the screen especially when i got a lot of data into the graph.
### If related to metric query / data viz:
There is what i see in single mode :

![image](https://user-images.githubusercontent.com/33425208/50510369-b4b3f280-0a89-11e9-801b-9e2c5d66e689.png)

But at this specific moment i got 2 value. But i can only see 1 value when i hover it :

![image](https://user-images.githubusercontent.com/33425208/50510330-9b12ab00-0a89-11e9-9047-1a005c23c03f.png)

There is the other value :

![image](https://user-images.githubusercontent.com/33425208/50510162-ed9f9780-0a88-11e9-8c53-2d1a25f72f53.png)

But if i activate All series, it's just to massive to clearly read which data you are looking to.

It would be great if we can have the option to display the value overrinding each over at the moment you are hovering it like the Single mode. But it will display every value at this moment, including multiples values who override each over like in the screens i include in ths post.

This has been already describe as a request but the other post just get closed because it was similar to the All series feature already existing. The thing i describe is a bit different from what i read on others post.

**Comment by DrMerlin** [comment]
++

**Comment by MichaelTendoSsemwanga** [comment]
+1

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by kipavy** [comment]
+1

**Comment by kipavy** [comment]
> We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team.
> 
> Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).
> 
> As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

Hello, I just saw you're [moving feature requests back to issues](https://github.com/grafana/grafana/discussions/73424) so please reopen this issue, I also have multiple points of same series real close to each other and grafana can't even show each tooltip when hovering, please fix.
