### ISSUE TITLE
Singlestat panel shows N/A instead of true or false values from InfluxDB

### ISSUE THREAD

**Issue by James00001** [grafana/grafana#14673]
### What Grafana version are you using?
5.4.2

### What datasource are you using?
InfluxDB 

### What OS are you running grafana on?
Linux (Centos 7)

### What did you do?
I have a measurement which only contains true/false values. According to SHOW FIELD KEYS in InfluxDB's console, the fieldType is "boolean"

I am trying to display this field in a SingleStat panel in Grafana.

### What was the expected result?

The expected result is a singlestat that says either "true" or "false"

### What happened instead?

I always see "N/A" no matter what the actual value is.

I can see that my query is correct in Grafana's Query inspector. I can see under the "response Object" that I am actually getting the correct true or false value back, the SingleStat just won't display it.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

http://localhost:3000/api/datasources/proxy/1/query?db=zssa&q=SELECT%20last(%22sparse%22)%20FROM%20%22lun_info%22%20WHERE%20(%22name%22%20%3D~%20%2F%5Eozma%24%2F%20AND%20%22lun%22%20%3D~%20%2F%5Etestlun_alpha%24%2F)%20AND%20time%20%3E%3D%20now()%20-%206h&epoch=ms
 
{"results":[{"statement_id":0,"series":[{"name":"lun_info","columns":["time","last"],"values":[[1545941760000,true]]}]}]}

**Comment by torkelo** [comment]
What format have you specified the query should return (In metrics tab) there is format as dropdown that has Time Series to Table. 

Try changing this to table and in the options tab select the column. Time series does not support boolean values.

**Comment by James00001** [comment]
Hello, torkelo.

Thank you for that information. I was not aware of that limitation. I changed the format from Timeseries to Table and now I get "NaN.nfinity" for false, and "1.0" for true. This is a small improvement, since now I am actually getting two distinct values for true/false.

Unfortunately, "NaN.nfinity" doesn't seem to work for the "Value mappings" feature.

Is there any reason why boolean doesn't work in time series format? I see that all the other data types, float, integer, string, all seem to work fine.

Is there some other workaround that allows me to display a boolean in a singlestat?
