### ISSUE TITLE
question about k8s dashboard repo

### ISSUE THREAD

**Issue by daixiang0** [grafana/grafana#14677]
Now anyone maintain this [repo](https://github.com/grafana/kubernetes-app) ?

The dashboard for k8s is wonderful for users i think.

**Comment by bergquist** [comment]
I think its deprecated. But I'm not sure. If it is, we should archive it so its clear for people stumbling upon it.

**Comment by daixiang0** [comment]
@bergquist thanks for quick reply.
Could you share repo url about it?

**Comment by torkelo** [comment]
think it's maintained, will make sure the PR gets a response soon

**Comment by daixiang0** [comment]
I am happy to get a response.
@torkelo maybe close this after ensure.

**Comment by daixiang0** [comment]
@bergquist @tobio still no response ...

**Comment by daixiang0** [comment]
@torkelo @bergquist  still no response ...

**Comment by daixiang0** [comment]
@torkelo @bergquist @daniellee oops, this repo no input ...
