### ISSUE TITLE
Cross-referrenced templating variables

### ISSUE THREAD

**Issue by mezhov** [grafana/grafana#14670]
### What did you do?
I had a few templating variables in dashboard of type query. One of them was linked to another. That worked just fine. E.g. variables a,b
a = show values with type = 'type_a'
b = show values with type = 'type_b' where field_a =~ /$a/

Then I decided to make a link from a to b as well, so that only those values a selected which correspond to already selected b. E.g. variables a,b
a = show values with type = 'type_a' where field_b =~ /$b/
b = show values with type = 'type_b' where field_a =~ /$a/

It worked just fine in editor and when I closed templating dialogue.
However, when I saved the dashboard and tried opening it in a new window it came completely blank (not even header panel).

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
No query for a,b appeared. 

Summary, 2 issues:
1. If it crashes, it doesn't provide any recovery means
2. It crashes on circle reference of variables

**Comment by torkelo** [comment]
circular / recursive dependencies are not supported. 

the crash is fixed in v5.3
