### ISSUE TITLE
Alert for the chinese char

### ISSUE THREAD

**Issue by BlackCodes** [grafana/grafana#14685]
My English so bad, So Pls use google translation to the english. 
我觉得Grafana是一个非常不错的graph,我们的团队都很喜欢他，最近在做使用报警功能的时候，发现出现了很多的问题；
1）对中文支持不友好，经常出json marshal错误，原因是某些字符串在格式化出错； 
2）仪表盘不支持报警功能；
3）dingtalk不支持自定义消息格式，看不到快照图表；
目前就这些，希望grafana团队，照顾一下中国朋友~

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
