### ISSUE TITLE
Weird log level "eror" in Grafana server output

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14686]
seen in loki logs:
```
t=2018-12-31T08:15:26+0000 lvl=eror msg="Server shutdown" logger=server reason="System signal: terminated"
```

line gets classified as "unknown"

**Comment by davkal** [comment]
Hmm, looks like this is due to github.com/inconshreveable/log15, who prefer log levels to be 4 chars long.

**Comment by torkelo** [comment]
yea, also a bit annoyed by this. Think its to keep things aligned in output (so all levels are 4 chars).

**Comment by davkal** [comment]
I dont see us fixing this from a spelling point of view. PR opened to accommodate these level short forms.
