### ISSUE TITLE
Grafana crashes because of max_prepared_stmt_count

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#14680]
Please include this information:
### What Grafana version are you using?
5.4.2

### What datasource are you using?

MySQL & Prometheus

### What OS are you running grafana on?

official docker image on kubernetes

### What did you do?

I created a new dashboard with a MySQL data source, added various graphs which perform queries. The database grew while I was working on it. At some point Grafana kept crashing even though I haven't even opened the dashboard anymore. The grafana logs show me:

```
t=2018-12-28T16:00:13+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"
```

What can I do to get my Grafana back up again? Even though something may be wrong with the dashboard itself, it shouldn't crash my grafana replicas.

**Comment by torkelo** [comment]
This does not look like a crash but a failure to start due to some limit hit in your MySQL server  (max_prepared_stmt_count ). 

Strange, this is the first time we have seen this reported. So something might be unique with your setup somehow.

**Comment by weeco** [comment]
We haven't touched the Grafana setup itself for a very long time, All I did today was working on a Dashboard with a new MySQL datasource (as described above). It's the only MySQL data source too.

I could only guess that it's trying to evaluate alert rules / dashboard metrics where it fails because the dashboard queries to the SQL backend exceeds the max prepared statement count size of the SQL server (CloudSQL server at Google Cloud).

What information do you want me to provide since this is being marked as needs investigation?

**Comment by weeco** [comment]
I figured out it was a second application hitting the limit in the SQL server. Therefore Grafana couldn't start up again. Sorry for creating the issue here!
