### ISSUE TITLE
Add legend value option/stat: Last non null

### ISSUE THREAD

**Issue by loopping** [grafana/grafana#1468]
Grafana 1.9.1
1 - I have some metrics that behave like this:
Every 5 minutes I receive in graphite a batch of 5 values to fill a 1 minute of retention metric.
So, sometimes I have the last 4m where the graph is empty, so is the "current" legend value when using "Null point mode" to "null".
Is it possible to add a "last" legend value?

2 - When using "Null point mode" to "null", the min legend value is empty

**Comment by torkelo** [comment]
you could use keepLastValue function if you use Graphite, hm.. maybe a legend value option like "Last non null" could be worth considering.

**Comment by loopping** [comment]
I'm using "KeepLastValue" for now, but it draws a constant line from the last value to the current time for the missing interval.
I could also use "Null point mode" in connected mode, but then I loose the "All Series" Tooltip when metrics comes from different OS and series points count are different.
The best would be to add a "Last non null" as you mentioned.

As for the second item, (When using "Null point mode" to "null", the min legend value is empty)
do I have to open a new issue ?

**Comment by torkelo** [comment]
hm.. yes, that sounds like a bug, mean 5 is less than null, so if there are any values (and some null) the min values should not be empty

**Comment by loopping** [comment]
Hello,
In file src/app/components/timeSeries.js, change
```javascript
 if (currentValue < this.stats.min) {
this.stats.min = currentValue;
}
```
to
```javascript
 if (currentValue !== null && currentValue < this.stats.min) {
this.stats.min = currentValue;
}
```
Will it do the trick ? because (null < 5) is true

**Comment by loopping** [comment]
Hello,
I have created a PR https://github.com/grafana/grafana/pull/1546 to address "last non null" and "min legend".
I can report it to the develop branch if needed

**Comment by loopping** [comment]
When calculating a max legend, if all values are negatives and some are null, the legend is empty
When calculating a min legend, if all values are positives and some are null, the legend is empty
Quick fix in src/app/components/timeSeries.js line 94 (works for version 1.9.1 and 2.0)
```
      if (currentValue !== null && currentValue > this.stats.max) {
        this.stats.max = currentValue;
      }

      if (currentValue !== null && currentValue < this.stats.min) {
        this.stats.min = currentValue;
      }
```

**Comment by torkelo** [comment]
Thanks @loopping , fixed in develop branch!
