### ISSUE TITLE
how to create user in 5.4.2  not invite

### ISSUE THREAD

**Issue by LongShengWen** [grafana/grafana#14684]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.4.2 
### What datasource are you using?
Prometheus for redis 
### What OS are you running grafana on?
Linux

**Comment by torkelo** [comment]
Go to Server Admin > Users > Add new user
