### ISSUE TITLE
Feature request: Custom values for the graph table

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#1469]
As of today the table below a graph can show min / max / average / current / total value.

It would be great if the values could be customized much like a single value dashboard. The idea is to introduce the same syntax as you would use for querying the data source but as a value in the table.

This would offer great opportunities like showing the current values in the graph and e.g. a "average metric per hour" reading in the table.

**Comment by torkelo** [comment]
not sure I understand what you mean, could you describe in more detail how the time series request and response would be processed to get the table rows you would like?

**Comment by Sineos** [comment]
Sorry for not being precise in the first place.
Today the "Legend Values" are statically defined as Min, Max, Average, Current, Total.

My proposal would be to allow for dynamic Legend Values, e.g. I define a "Legend Column" called "Cache Hits" and assign them a value of [scale(apps.backend.backend_01.counters.requests.count, 0.1)] while the graph above shows [groupByNode(apps.backend.backend_01.counters.requests.count, 2, 'sum')]

So this would kind of be the best of the "Singlestats" and regular Graphs.

Hope I could make myself clear now

**Comment by kpweiler** [comment]
+1

the ability to include percentiles in the legend would be incredibly useful (from Influx). Basically, your legend value would be a query that returns 1 value (like a percentile query from influx).

**Comment by torkelo** [comment]
Solved by singlestat panel
