### ISSUE TITLE
Add support of Cube as datasource 

### ISSUE THREAD

**Issue by ncoussemacq** [grafana/grafana#147]
As far as I understand, Cube (http://square.github.io/cube/) does almost the same as graphite and offers the same kind of api to perform queries. The main difference is that cube allows to store user-defned metada for each metric value and let use those metada to filter out metrics.

I think it would be great to support Cube as a datasource and let the user filter a metrics based on the associated metada in cube.

**Comment by nucleusv** [comment]
@Krylon360, you may try to use MariaDB with its Cassandra engine for HIstory and Trends tables
