### ISSUE TITLE
How to use annotations on Graphite metrics

### ISSUE THREAD

**Issue by swissdave** [grafana/grafana#1470]
Hi - I'm trying to use annotations with Graphite metrics to achieve something similar to drawAsInfinite.  Previous issues have suggested that can be done with annotations but it's not really clear to me how these work with metrics.  It looks like they draw an annotation for any point where the expression evalutates to non-zero or non-null - is that correct?  The fact that the Graphite expression builder is not used on that page makes me wonder if it supports more content.  I'm trying to do something e.g. where value > 0.5 on a number of data series.

**Comment by torkelo** [comment]
@swissdave any graphite metric query is usable, and yes any point returned will be drawn as infinite marker line. 

If you need only values > 0.5 you need to add graphite functions to filter out those values, for example removeBelowValue

**Comment by torkelo** [comment]
And sorry, it should use the graphite metric query builder, just not had time to make that work yet.

**Comment by swissdave** [comment]
Ah - right - got it.  Thanks very much.  Awesome bit of software btw :-)

**Comment by torkelo** [comment]
@swissdave thanks!
