### ISSUE TITLE
/var/log/grafana empty

### ISSUE THREAD

**Issue by AliNjie** [grafana/grafana#14708]
### What Grafana version are you using?
5.4.0

### What OS are you running grafana on?
![image](https://user-images.githubusercontent.com/38862494/50597474-d35e2300-0ea7-11e9-986c-69c04daa6a39.png)

### What did you do?
Configured Grafana to log both to console and file

### What was the expected result?
To see a logfile in /var/log/grafana

### My Issue
I've configured the following in the defaults.ini Grafana configuration file and would expect Grafana to output the same logs, outputted in the console, to a file locate in /var/log/grafana.
The issue is that the logfile is not created and the folder is completely empty. Console logging works just fine.

Any errors in my configuration or any other suggestions?

#################################### Paths ###############################
[paths]
######### Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
data = data

########## Temporary files in `data` directory older than given duration will be removed
temp_data_lifetime = 24h

########## Directory where grafana can store logs
logs = data/log

########## Directory where grafana will automatically scan and look for plugins
plugins = data/plugins

########## folder that contains provisioning config files that grafana will apply on startup and while running.
provisioning = conf/provisioning

#################################### Logging ##########################
[log]
########### Use space to separate multiple modes, e.g. "console file"
mode = console file

########### Either "debug", "info", "warn", "error", "critical", default is "info"
level = info

**Comment by torkelo** [comment]
you seem to have changed the default log paths:

```
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
;data = /var/lib/grafana

# Temporary files in `data` directory older than given duration will be removed
;temp_data_lifetime = 24h

# Directory where grafana can store logs
;logs = /var/log/grafana

# Directory where grafana will automatically scan and look for plugins
;plugins = /var/lib/grafana/plugins

# folder that contains provisioning config files that grafana will apply on startup and while running.
;provisioning = conf/provisioning
```

this is from the default config file where the default values are shown (commented out). The log paths are set via systemd/initd startup params, but can be overriden id you set them in you ini file like youy have.

How did you install Grafana and how did you start it?

**Comment by AliNjie** [comment]
I see. So if I understand correctly, I am able to set the value of "logs" in defaults.ini to /var/log/grafana.
I've tried this, but the log file still does not appear.

The Grafana instance is running via Docker in Openshift.

**Comment by AliNjie** [comment]
Never mind my last comment.

Seems like uncommenting in the grafana.ini config file solved the issue. Thanks
