### ISSUE TITLE
State Filter on Alerts Panel on a Dashboard for the mode "Recent State Change" (Request)

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#14704]
Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
ElasticSearch 6.5.4
### What OS are you running grafana on?
Debian 9.5.0
### What did you do?
Add an Alert List panel on a dashboard and display my alerts. I wanted to filter and display only all the alerting state alerts on the panel.
### What was the expected result?
Display every alerting state registered by Grafana for the defined time in the dashboard (Last 30 minutes here).
### What happened instead?
I can't display every alerting state in the panel registered by grafana. I can only display the current state of the alert or display every Recent State Changes
### If related to metric query / data viz:
As you can see here i got some alerts :
![image](https://user-images.githubusercontent.com/33425208/50586847-a85dda00-0e7b-11e9-85e6-fd9be043c4a8.png)

But in the Alert List Panel, i can't display every alerting state in the time range selected. I can only display the current state of every recent state change :

Current status :
![image](https://user-images.githubusercontent.com/33425208/50586891-d4795b00-0e7b-11e9-8ab2-bd906a8a6dac.png)

Recent State Change :
![image](https://user-images.githubusercontent.com/33425208/50586908-e65afe00-0e7b-11e9-9adb-ed064cd72e95.png)

It would be great if we can add filter to the Recent State Change. This way, you can only display every alerting status or Pending status unstead of every status. The same filter like the Current state mode.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
