### ISSUE TITLE
Incorrect index pattern padding in alerting queries

### ISSUE THREAD

**Issue by hrr888** [grafana/grafana#14706]
### What Grafana version are you using?
5.4.2
### What datasource are you using?
elasticsearch, index pattern set to 'weekly'
### What OS are you running grafana on?
Linux
### What did you do?
Create simple alert for datasource type elasticsearch with weekly pattern
### What was the expected result?
Working alert ;)
### What happened instead?
When click 'Test rule' button,  returned results are empty:
```
...
logs:Array[4]
  0:Object
    message:"Condition[0]: Query Result"
    data:Array[0]
  1:Object
    message:"Condition: Eval: false, Query Returned No Series (reduced to null/no value)"
    data:null
...
```

Sniffing packets send to elasticsearch from grafana revelaed, that query was send with wrong name of the index. With defined weekly pattern expected suffix should be `2019.01`, but `2019.1' is used instead. This is happening only when alerts are checked. Graphs using exactly the same datasource have no issues.

**Comment by torkelo** [comment]
Proabably an easy thing to fix here: 
https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/index_pattern.go#L125

**Comment by marefr** [comment]
@sandlis please open a PR and we gladly assist/continue the discussion there.

You probably need to add/update a few tests as well:
https://github.com/grafana/grafana/blob/b58261100429b5b1751fc9dbbcb07d9fc606658c/pkg/tsdb/elasticsearch/client/index_pattern_test.go#L139-L193

**Comment by sandlis** [comment]
@marefr I have sent a PR.
My changes should not impact other data sources, I don't remember why I thought it might impact other data sources.
I have added test case for same.

**Comment by sandlis** [comment]
@marefr I have sent a PR.
My changes should not impact other data sources, I don't remember why I thought it might impact other data sources.
I have added test case for same.
