### ISSUE TITLE
[Bug] Singlestat can not autofit in Safari.

### ISSUE THREAD

**Issue by wangdaners** [grafana/grafana#14715]
### What Grafana version are you using?
Grafana v5.2.1
### What datasource are you using?
Elastisearch/MySql/influxdb
### What OS are you running grafana on?
CentOS
### What did you do?
Safari version: 12.0.2 (14606.3.4)
Normal:
![image](https://user-images.githubusercontent.com/40197767/50626999-724c5300-0f6c-11e9-9217-dfd41081b5c0.png)
When I change the window size:
![image](https://user-images.githubusercontent.com/40197767/50627046-a162c480-0f6c-11e9-9cfd-fa086cc5f6c7.png)
And this Bug only happens in Safari.

Because my English is poor, so the description is not very clear,I am sorry.

**Comment by wangdaners** [comment]
Will this issue be fixed in the next version?

**Comment by wangdaners** [comment]
Will this issue be fixed in the next version?

**Comment by wangdaners** [comment]
If I don't upgrade to the latest version.What should I do?

**Comment by torkelo** [comment]
Closing this as it's fixed in new stat panel
