### ISSUE TITLE
Explore UI is very slow and keeps hanging

### ISSUE THREAD

**Issue by tdabasinskas** [grafana/grafana#14718]
I know **Explore UI feature** is still in in a Preview state, but I was not able to find similar issues yet, while it seems to be almost unusable for us in its current state. I guess it might be related to us using [Thanos](https://github.com/improbable-eng/thanos)), but think large number of series should still not hang the UI completely.

### What Grafana version are you using?
v5.4.2

### What datasource are you using?
Prometheus (with [Thanos](https://github.com/improbable-eng/thanos))

### What OS are you running Grafana on?
Docker

### What did you do?

1. Enable Grafana Explore UI
1. Open Explore UI page
1. Select a metric from `Metrics` button menu or start typing a new PromQL query

### What was the expected result?
See the list of available metrics. Either instantly or with a minimal delay.

### What happened instead?

- Chrome v73.0 freezes
- Firefox v64.0 freezes or sometimes the whole tab crashes.

**Comment by torkelo** [comment]
Can you try to capture the query sent to Thanos and the response from Thanos?

**Comment by tdabasinskas** [comment]
Hi @torkelo,

Not sure if that helps but this is what I see happening when opening Explore UI:

![image](https://user-images.githubusercontent.com/7723360/50680451-6d40df80-1010-11e9-9df3-99e3ab3e76d0.png)

`values` endpoint returns 52MB of data, while series query by regexp `{le!=""}` never completes. Waiting about a minute causes **Firefox** tab to crash.

As for **Chrome**, Explore UI tab loads initially and I'm able to write 1 or 2 queries, but writing something else hangs (network queries looking the same as for Firefox), hanging the whole browser:

![image](https://user-images.githubusercontent.com/7723360/50680686-420ac000-1011-11e9-994b-0c8769f4730c.png)

**Comment by bwplotka** [comment]
Looks like this query is gettting ALL series except histograms, which means you are retrieving potentially labelsets of X milions of series in same time, and storing them in your browser. 

Assumming average labelset (single series) is 200B you have 200 * X millions of bytes in your browser and 0.5x on the wire. For biggest singleton Prometheus setups it could be up to 4-5 mlns, giving you 1GB response easily. Wonder how many series you have in your setup especially for Thanos.

I heard https://github.com/prometheus/prometheus/pull/4835 is planned to be used instead in Grafana?

Anyway, for both cases, limiting those to single cluster/tenant etc label you want would be awesome. So, someway to customise this `series?match[]={$custom_filter}` you care about to limit cardinality. 

This means also that https://github.com/prometheus/prometheus/pull/4835 is not suitable for that as it does not allow label matching. I guess we could extend that. But not sure how to inject this cardinality limit (e.g tenant or cluster) into `series` in Explore UI in Grafana.

**Comment by torkelo** [comment]
Closing this for now, maybe open a feature request to add a Prometheus data source setting to limit series lookups

**Comment by bwplotka** [comment]
What about:

> I heard prometheus/prometheus#4835 is planned to be used instead in Grafana? That would reduce the size enourmously.

Is that true? (:
