### ISSUE TITLE
Graph Legend & Tooltip value decimals should only consider min/max for relevant y-axis 

### ISSUE THREAD

**Issue by sbraz** [grafana/grafana#14713]
Hello,
I'm using grafana 5.4.2 with an InfluxDB backend and I'm running into a rounding issue:
* the left axis is used for integer values (temperature)
* the right axis is used for small float values (voltage)

Whenever I hover over the voltage values, they are rounded to the nearest integer. If I duplicate the panel and disable the temperature metrics, I see the float value (as I should).

Here are screenshots of both panels which clearly demonstrate the problem:
![image](https://user-images.githubusercontent.com/4833332/50619106-902ba080-0ef7-11e9-8191-eb89851431ef.png)
![image](https://user-images.githubusercontent.com/4833332/50619109-93269100-0ef7-11e9-924e-1320aaddd963.png)

 
I've looked at the query inspector and the values are not rounded there:
```
Array[1546474374000,1.19]
```

**Comment by torkelo** [comment]
The legend & tooltip does take into account different y axis values when figuring out the auto decimals. You can work around this limitation by setting a manual decimals override in the y axis settings.

**Comment by dprokop** [comment]
@sbraz I believe this issue is now fixed in Grafana v7.
