### ISSUE TITLE
Applying local Timezone to Hour Conversion (Postgres)

### ISSUE THREAD

**Issue by rymoore** [grafana/grafana#14721]
I'm writing a query to display in a Pie Chart to show the most popular hours that an event has occurred. This works great, except that all of the hours display as UTC (which is how they're stored in my Postgres DB). I'd like them to display in the timezone of the user. Is this possible?

```
SELECT
  $__time(start_time),
  to_char(start_time, 'HH') || to_char(start_time, 'am') || '-' || to_char(start_time + interval '1h', 'HH') || to_char(start_time + interval '1h', 'am') as outcome,
  COUNT(*) as "measurement"
FROM sessions
WHERE 
  $__timeFilter(start_time)
group by start_time, outcome
ORDER BY outcome DESC
```

**Comment by torkelo** [comment]
Not if you do your time conversion & generate the string to show in your query that executed by postgres. 

Please ask questions on the community site https://community.grafana.com
