### ISSUE TITLE
Auto-Refresh still not working

### ISSUE THREAD

**Issue by karlbeecken** [grafana/grafana#14723]
### What happened instead? This: ![screenshot](https://screenshotscdn.firefoxusercontent.com/images/d9ac8b34-9fd8-484e-99ff-232280dfa0d9.png)

I saw that some issues were closed with the information it should be fixed in release x.y.z, but I have this error still.

**Comment by karlbeecken** [comment]
Okay, I found out that i won't refresh never but very irregular, see pic:
![sreenshot](https://screenshotscdn.firefoxusercontent.com/images/37a4fe9a-084a-453a-b412-c5e1117a9846.png)
(I never reloaded/F5 the page)

**Comment by torkelo** [comment]
Strange, unable to replicate the issue. Can you investigate networks requests and responses?  any errors?

**Comment by karlbeecken** [comment]
Yes, very strange, it seems it happens irregular, sometimes it just never refreshes.

**Comment by daniellee** [comment]
@karlbeecken can you open the Chrome Developer Tools and check for errors. Are there any JavaScript errors? If there are no errors, what does the network tab say?

For my iframe test, with a ten second refresh, it looks like this and new calls get added to the list every refresh:

![image](https://user-images.githubusercontent.com/434655/50758429-8345de80-1262-11e9-8f37-3f83027c73b4.png)

When it doesn't work, what does your network tab look like?

**Comment by karlbeecken** [comment]
I see three grafana-related errors, the first both in Firefox and Chromium, the second and third only in Chromium. Chromium Debug Output: ![chromium](https://i.imgur.com/LXdoGr9.png)
In the network tab it looks like this, every time the refresh wheel in the iframe starts spinning: ![network tab](https://i.imgur.com/UgeTkiA.png)
Maybe it's an issue with the slowness of the pi running the grafana server?

**Comment by daniellee** [comment]
@karlbeecken looks like it could be authentication issues with your mysql database or something related to your pi. Are there any additional errors in the Grafana server logs?

**Comment by karlbeecken** [comment]
@daniellee where do I find them?

**Comment by SamuelToh** [comment]
@karlbeecken 
Unless you have a customised Grafana configuration, for Linux OS logs are generally stored at `/var/log/grafana`.

**Comment by karlbeecken** [comment]
This is a log from a day where the error occured:

`pi@magnesium:~ $ sudo cat /var/log/grafana/grafana.log.2019-01-04.001 
t=2018-12-07T08:09:14+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2018-12-07T08:09:14+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=196.52.43.62 time_ms=51 size=29 referer=
t=2019-01-03T13:47:15+0100 lvl=info msg="Starting Grafana" logger=server version=5.1.4 commit=a5fe24f compiled=2018-06-19T12:54:57+0200
t=2019-01-03T13:47:15+0100 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2019-01-03T13:47:15+0100 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2019-01-03T13:47:15+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2019-01-03T13:47:15+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2019-01-03T13:47:15+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2019-01-03T13:47:15+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2019-01-03T13:47:15+0100 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2019-01-03T13:47:15+0100 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2019-01-03T13:47:15+0100 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2019-01-03T13:47:15+0100 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2019-01-03T13:47:15+0100 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2019-01-03T13:47:15+0100 lvl=info msg="App mode production" logger=settings
t=2019-01-03T13:47:15+0100 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=2439
t=2019-01-03T13:47:15+0100 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2019-01-03T13:47:15+0100 lvl=info msg="Starting DB migration" logger=migrator
t=2019-01-03T13:47:15+0100 lvl=info msg="Starting plugin search" logger=plugins
t=2019-01-03T13:47:17+0100 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2019-01-03T13:47:17+0100 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2019-01-03T13:47:17+0100 lvl=info msg="Initializing Stream Manager"
t=2019-01-03T13:47:17+0100 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2019-01-03T13:47:23+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T13:47:23+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/ILbsDszgk/temp-humi status=302 remote_addr=91.64.170.235 time_ms=66 size=29 referer=http://karl-beecken.de:8088/ctrl/
t=2019-01-03T13:47:23+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T13:47:36+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T13:47:38+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T14:09:35+0100 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2019-01-03T14:09:35+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T14:09:35+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=91.64.170.235 time_ms=178 size=26 referer="http://karl-beecken.de:3000/d-solo/ILbsDszgk/temp-humi?refresh=30s1&panelId=2&from=now-1h-10m&to=now-10m&theme=dark&orgId=1"
t=2019-01-03T14:41:19+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-01-03T14:46:26+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-01-03T14:46:26+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2019-01-03T14:51:36+0100 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2019-01-03T14:51:36+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T14:51:36+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=91.64.170.235 time_ms=90 size=26 referer="http://karl-beecken.de:3000/d-solo/ILbsDszgk/temp-humi?refresh=30s1&panelId=2&from=now-1h-10m&to=now-10m&theme=dark&orgId=1"
t=2019-01-03T15:09:37+0100 lvl=info msg="Starting Grafana" logger=server version=5.1.4 commit=a5fe24f compiled=2018-06-19T12:54:57+0200
t=2019-01-03T15:09:37+0100 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2019-01-03T15:09:37+0100 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2019-01-03T15:09:37+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2019-01-03T15:09:37+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2019-01-03T15:09:37+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2019-01-03T15:09:37+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2019-01-03T15:09:37+0100 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2019-01-03T15:09:37+0100 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2019-01-03T15:09:37+0100 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2019-01-03T15:09:37+0100 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2019-01-03T15:09:37+0100 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2019-01-03T15:09:37+0100 lvl=info msg="App mode production" logger=settings
t=2019-01-03T15:09:37+0100 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=748
t=2019-01-03T15:09:37+0100 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2019-01-03T15:09:37+0100 lvl=info msg="Starting DB migration" logger=migrator
t=2019-01-03T15:09:38+0100 lvl=info msg="Starting plugin search" logger=plugins
t=2019-01-03T15:09:39+0100 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2019-01-03T15:09:39+0100 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2019-01-03T15:09:40+0100 lvl=info msg="Initializing Stream Manager"
t=2019-01-03T15:09:40+0100 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2019-01-03T15:09:41+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T15:09:41+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/ILbsDszgk/temp-humi status=302 remote_addr=91.64.170.235 time_ms=133 size=29 referer=
t=2019-01-03T15:09:41+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T15:09:42+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=91.64.170.235 time_ms=815 size=139 referer=
t=2019-01-03T15:16:08+0100 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2019-01-03T15:16:08+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T15:16:08+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=91.64.170.235 time_ms=292 size=26 referer="http://karl-beecken.de:3000/d-solo/ILbsDszgk/temp-humi?refresh=30s1&panelId=2&from=now-1h-10m&to=now-10m&theme=dark&orgId=1"
t=2019-01-03T15:23:40+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-01-03T15:56:09+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-01-03T17:57:05+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-01-03T18:01:45+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T18:01:45+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/ILbsDszgk/temp-humi status=302 remote_addr=91.64.170.235 time_ms=38 size=29 referer=
t=2019-01-03T18:01:45+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T18:01:54+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T18:01:56+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T18:02:16+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-01-03T18:34:10+0100 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2019-01-03T18:34:10+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T18:34:10+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=91.64.170.235 time_ms=137 size=26 referer="http://karl-beecken.de:3000/d-solo/ILbsDszgk/temp-humi?refresh=30s1&panelId=2&from=now-1h-10m&to=now-10m&theme=dark&orgId=1"
t=2019-01-03T18:59:56+0100 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2019-01-03T18:59:56+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T18:59:56+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=91.64.170.235 time_ms=292 size=26 referer="http://karl-beecken.de:3000/d-solo/ILbsDszgk/temp-humi?refresh=30s1&panelId=2&from=now-1h-10m&to=now-10m&theme=dark&orgId=1"
t=2019-01-03T19:05:12+0100 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2019-01-03T19:05:12+0100 lvl=eror msg="Anonymous access organization error: 'fll-view': Organization not found"
t=2019-01-03T19:05:12+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/annotations status=401 remote_addr=91.64.170.235 time_ms=442 size=26 referer="http://karl-beecken.de:3000/d-solo/ILbsDszgk/temp-humi?refresh=30s1&panelId=2&from=now-1h-10m&to=now-10m&theme=dark&orgId=1"
t=2019-01-03T20:54:12+0100 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0`

**Comment by daniellee** [comment]
This log is full of errors - the main ones being:

- `Anonymous access organization error: 'fll-view': Organization not found`
- `lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"`

Does the fll-view org exist? And does the admin user (I'm assuming admin has id 1) have access to that org? 

To see which orgs a user belongs to, go the Server Admin section in Grafana and click on the user, the list of orgs the user belongs to is at the bottom.

Not sure if these are related to your issue though. Depending on the hardware, I suppose the problem could be performance related too.

**Comment by torkelo** [comment]
Closing this, might be the slowness of your PI or something else related
