### ISSUE TITLE
[bug] time range override - panel settings not passed to query

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#14726]
### What Grafana version are you using?
grafana_5.5.0-f94e6a56pre1_amd64.deb

### What datasource are you using?
influxdb

### What did you do?
override time range in table panel

### What happened instead?

ignored panel override, query inspector instead shows dashboard time range was used
however panel does show override selection in top right corner

### Last working version:
grafana_5.5.0-e88e9866pre1_amd64.deb

**Comment by dprokop** [comment]
Could not reproduce so far. Can you please try latest master?

**Comment by marefr** [comment]
@dprokop I can reproduce. Save a dashboard with a panel with relative time override different than dashboard time range. Reload that dashboard and the relative time override is not applied.
