### ISSUE TITLE
Grafana creates session files for 401 responses

### ISSUE THREAD

**Issue by ojarva** [grafana/grafana#14720]
### What Grafana version are you using?

5.3.4

### What OS are you running grafana on?

Fedora

### What did you do?

Dashboard is open with 5s refresh interval, and session was timed out.

### What was the expected result?

Browser would be redirected to login screen.

### What happened instead?

Browser continued refreshing the dashboard by making requests to `/api/datasources/proxy/11/query` for every single graph on the open dashboard, which gets 401 response every time.

These create new session files, causing a flood of files being created. As the cleanup interval seems to be 24h, this means hundreds of thousands of session files are being created per day.

It is really weird to create new session files when Grafana responds with 401 Unauthorized, as that means just spamming publicly available Grafana instance with unauthorized queries will cause a DoS with a large number of sessions being created (unless for example Redis with eviction policy is used, in which case this will just cause DoS by evicting legitimate sessions from Grafana).

**Comment by torkelo** [comment]
Strange, what are you using for auth ?

**Comment by ojarva** [comment]
Default authentication backend from sqlite3 database. Relevant parts from config file (with details replaced with placeholder values):

```
[auth.anonymous]
enabled=false
[security]
admin_password=passwordhere
admin_user=username
cookie_remember_name=ourprefix_grafana_remember
cookie_username=ourprefix_grafana_user
login_remember_days=7
[users]
allow_org_create=false
allow_sign_up=false
auto_assign_org=false
auto_assign_org_role=Viewer
```

**Comment by torkelo** [comment]
This shoud be be fixed in v6 with the new token auth (removed need for session storage)
