### ISSUE TITLE
LDAP: Disable check/error for removing last org admin when syncing external user orgs

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#14724]
I'm using Grafana 5.4.1 on a CentOS 7 system using docker and ldap and after not using Grafana for a week I suddenly no longer can log into it using my regular user. All I get is the message "Cannot remove last organization admin" in the log. I can still log into Grafana as the admin user but I have no idea what that message is supposed to mean or what to change to make the login work again.

What is Grafana trying to tell me?

**Comment by jblaine** [comment]
@dennisjac I have the same issue. Could you let me know what you found?
