### ISSUE TITLE
Grafana 2.0 : Configuration options via ENV variables

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1473]
Currently the Grafana 2.0 backend is configured via the grafana.ini config file in the ./conf dir the working directly of grafana process. 

Grafana 2.0 backend will also look for a grafana.dev.ini and grafana.custom.ini for overrides, so you should not make changes to the grafana.ini file, it only contains defaults. grafana.custom.ini is not included in releases (to make upgrades safe). 

Specifying options via ENV variables could also be useful, especially for docker setups when config files are more of a hassle. 

Config file snippet
```ini
[security]
admin_user = admin
admin_password = admin

[account.single]
enabled = true
```

I implemented a post process after config files are loading all sections and keys are looped through to inspect if they are overridden via an ENV variable. 
Proposed syntax is: ``GF_<SectionName>_<KeyName>`` so for example: 
```
export GF_ACCOUNT_SINGLE_ENABLED="true"
```

So section name is all upper case, dots are replaced with underscore, same for key name. The question is if I should change the naming of the ini file to make them match closer the ENV names (that is upper case and no dots for the section name and key).

Feedback?

**Comment by phagedorn** [comment]
Sounds good, do we have a init.d script allready (not for docker but for debian or similar)?

**Comment by torkelo** [comment]
no, init.d scripts and deb & rpm packaging is something that needs to be done before beta, will create an issue for that.
