### ISSUE TITLE
Enhancement : Clickable Folder name in Dashboard Title

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#14739]
We now have dashboard titles with the folder name. This is great.  However in many cases I would like to view the other dashboards that are in the folder.  It would be userful if the folder name in the dashboard title was click-able and takes me to the list of dashboards in that folder.

Please include this information:

**Comment by torkelo** [comment]
implemented by https://github.com/grafana/grafana/pull/16790

Now when you click anywhere in dashoard title (or folder name) the search will open with "folder: current" in search query that will filter the search by the current folder
