### ISSUE TITLE
Feature Request: Add add support for Log Insight opaque token authorization in ds_auth_provider

### ISSUE THREAD

**Issue by tomdantuit** [grafana/grafana#14738]
### What Grafana version are you using?
Grafana v5.3.1

### What datasource are you using?
Developing a Log Insight plugin

### What OS are you running grafana on?
RHEL 7.6

### What did you do?
Following guide from [the documentation](http://docs.grafana.org/plugins/developing/datasources/) to build a [Log Insight API](https://vmw-loginsight.github.io/#Getting-started-with-the-Log-Insight-REST-API) datasource plugin.

### What was the expected result?
Grafana attempts to do an OAuth flow to obtain a JWT.

### What happened instead?
The OAuth flow is not supported by Log Insight, so the data source's test fails with an unauthorized request.

### Suggestion
Currently [Grafana's ds_auth_provider](https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_auth_provider.go) doesn't support Log Insight's flow to obtain an opaque bearer token. Would like to create a opaque_token_provider similar to the [access_token_provider.go](https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/access_token_provider.go) that could then be used in the `ds_auth_provider`. The auth provider would be modified to use the `access_token_provider` if `authenticationType="jwt"` or `opaque_token_provider` if `authenticationType="opaque"`.

**Comment by tomd8451** [comment]
Going to pick this one up and work on it [here](https://github.com/8451/grafana/tree/14738-loginsight-auth). Will issue a PR tomorrow if not later today.

**Comment by marefr** [comment]
Following up from the related pull request that was closed. Would suggest implementing a [backend plugin](https://grafana.com/docs/grafana/latest/developers/plugins/backend/) to support this use case.
