### ISSUE TITLE
Issues with direct link render

### ISSUE THREAD

**Issue by marksie1988** [grafana/grafana#14733]
Please include this information:
### What Grafana version are you using? 
latest 
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
CentOS 7 Docker
### What did you do?
Go into dashboard share a panel click direct link rendered image
### What was the expected result?
expected to see chart data
### What happened instead?
see a blank chard with an ! in and orrange triangle at the top left 
### Include raw network request & response:
no errors are shown in chrome, no errors are shown in the debug logs
```
t=2019-01-04T14:22:35+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2019-01-04T14:22:35+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2019-01-04T14:22:35+0000 lvl=info msg=Rendering logger=rendering path="d-solo/xiZsmtUmz/homeassistant?orgId=1&panelId=2&width=1000&height=500&tz=Europe%2FLondon"
t=2019-01-04T14:22:36+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=1 orgId=1 uname= dashId=1 action=View
t=2019-01-04T14:22:36+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=1 orgId=1 uname= dashId=1 action=Edit
t=2019-01-04T14:22:36+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=1 orgId=1 uname= dashId=1 action=Edit
t=2019-01-04T14:22:36+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=1 orgId=1 uname= dashId=1 action=Admin
t=2019-01-04T14:22:39+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: http://localhost:3000/d-solo/xiZsmtUmz/homeassistant?orgId=1&panelId=2&width=1000&height=500&tz=Europe%2FLondon&render=1 status: success 60000\n"
t=2019-01-04T14:22:39+0000 lvl=dbug msg="Image rendered" logger=rendering path=/var/lib/grafana/png/deG8mz5NjSnQI9EJaxdA.png
```

![server power](https://user-images.githubusercontent.com/159166/50692572-4b555600-102c-11e9-8e37-f88929d97aa7.PNG)

**Comment by torkelo** [comment]
How are you accessing InfluxDB? Server or Direct? Can grafana-server access your influxdb server? 

You say your using latest grafana, lastest docker?

**Comment by marksie1988** [comment]
Hi @torkelo 

I have it setup as:

- URL: http://serverip:8086
-  Access: Browser

I tried to use "Server (default)" but kept getting bad gateway with the same URL

yes latest docker image

**Comment by torkelo** [comment]
Make sure grafana (from inside the container) can access your influxdb server
