### ISSUE TITLE
Graph Visualization issue when mixing different queries

### ISSUE THREAD

**Issue by dali99** [grafana/grafana#14732]
I'm using Grafana 5.4.2 with an influxdb source, running in docker.

I tried making a CPU+Memory graph:
https://pastebin.com/JD2C3KXq

I expected each metric to be displayed but instead my cpu information glitches out when I enable the memory metric.

Without memory:
![2019-01-04-131421_1811x510_scrot](https://user-images.githubusercontent.com/990767/50687755-d0d40880-1022-11e9-86db-dfd6dbeb539c.png)

With memory
![2019-01-04-131438_1819x515_scrot](https://user-images.githubusercontent.com/990767/50687757-d29dcc00-1022-11e9-8f1a-72659bdda62c.png)

Changing the max percentage on the Y axis reveals the cpu graph is now showing up as >60000000000%
![2019-01-04-131506_1818x627_scrot](https://user-images.githubusercontent.com/990767/50687761-d3cef900-1022-11e9-9d10-6b6194e5395e.png)

Request:
https://pastebin.com/cMWsVk9d

Response:
https://pastebin.com/1Y2qX1ZY

I don't have a lot of experience with grafana, so maybe I'm doing something wrong, but I don't see anything in the responses

**Comment by torkelo** [comment]
is stacking enabled? try disabling it or put the memory series in another stack group (using series override)

**Comment by dali99** [comment]
wow yeah that was it, sorry, I event did this earlier!

Thanks
