### ISSUE TITLE
Cannot get title from influx category

### ISSUE THREAD

**Issue by wz2b** [grafana/grafana#14734]
I am trying to load annotations from an InfluxDB mesurement (table) that contains
   tags:  id, category
   fields: time, text
and I want to use 'id' as the 'title' but I don't seem to have the option of mapping that.  Annotations show up on graphs just fine, but with no Title.

In the table view (using Table Transform: Annotations) I can query the id column but even if I add a specific Column Style for it, it never shows up.  The query I am using to get the data is:
    `SELECT 'id', 'category, 'text' FROM events WHERE $timeFilter`
category and text both show up in the table but not the id.  I want the id to map to Title.

I have not found any documentation that suggests that annotation titles don't work with InfluxDB so I'm calculating that something is wrong.

Grafana 5.4.2
Data source  InfluxDB 1.7.1
Ubuntu 18.04

**Comment by torkelo** [comment]
what is your annotation settings? Did you specify id in fields mappings for the text field?

there is no title in annotations, only text & time
