### ISSUE TITLE
[Feature Request] Filter out weekends or off work hours in graphs

### ISSUE THREAD

**Issue by sekhavatosan** [grafana/grafana#14741]
This issue is highly related to https://github.com/grafana/grafana/issues/5930#issuecomment-449867613. I have added a comment below the issue, but it seems that closed issues are not being watched.

Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Linux
### What did you do?
Add time region for holidays in `Display`/`Time regions` section.
### What was the expected result?
A checkbox to "filter out" the time region from graph (i.e. removing the whole graph area in those time intervals and not only the datapoints, so that the x-axis is contracted into a zero-width point in those intervals)
### What happened instead?
I can only highlight time regions
### If related to metric query / data viz:
As described in https://github.com/flot/flot/issues/513#issuecomment-20669253, it seems that "filter out" feature can be implemented by explicitly passing `ticks` as array, instead of passing it as integer (count), to flot: https://github.com/grafana/grafana/blob/513434cadaea15d6df3bdbf7d26af49d254a7a8c/public/app/viz/Graph.tsx#L73-L80

**Comment by sekhavatosan** [comment]
I have just found that https://github.com/grafana/grafana/issues/9454 and https://github.com/grafana/grafana/issues/6757 are feature requests for the "filter out" feature, and not the "highlight" feature, both marked as a duplicate of https://github.com/grafana/grafana/issues/5930. However, https://github.com/grafana/grafana/issues/5930 has only implemented the "highlight" part.

**Comment by torkelo** [comment]
please vote for https://github.com/grafana/grafana/issues/2418, it can be reopened if we enough people are interested in it. 

No plans yet, it could be very tricky implement with our current graph lib so not sure this will ever be done.
