### ISSUE TITLE
Legend on Graph Panel shown partially on Firefox

### ISSUE THREAD

**Issue by MachEleven** [grafana/grafana#14744]
### What Grafana version are you using?
grafana_5.5.0-400a18e7pre1

### What datasource are you using?
influxdb
### What OS are you running grafana on?
ubuntu 16.04

### What did you do?
I added legend to a graph panel using Visualization/Legend/Show on a desktop Firefox Version 64.0 (64-bit) browser.
![image](https://user-images.githubusercontent.com/28393146/50735833-efbed000-11c5-11e9-8141-f1b6b5d69cf6.png)

### What was the expected result?
Legend to be visible as a whole under the chart area

### What happened instead?
Legend is only partly visible vertically on Firefox browser.
Legend is shown correctly on Chrome browser. 

On Firefox
![image](https://user-images.githubusercontent.com/28393146/50735998-1251e880-11c8-11e9-879a-01db1af7f0c7.png)

On Chrome
![image](https://user-images.githubusercontent.com/28393146/50736057-0286d400-11c9-11e9-9cc2-034b93ebb192.png)

**Comment by torkelo** [comment]
Try latest nightly builds, should be fixed now!  thanks for reporting this!
