### ISSUE TITLE
Multiple tags in annotations using graphite event

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#1474]
It seems graphite event support multiple tags by separating them using a space or a comma. Would it be possible for grafana to parse this and display them as separated tags ?

**Comment by torkelo** [comment]
yes, this would be pretty easy to add.

**Comment by Akeru** [comment]
Great, thanks !

**Comment by Akeru** [comment]
Not sure I should fill a new issue, but would there be also a way to have a match all/any option for this ? 

Currently, each checkboxes generate a query, meaning "macth any". A "match all" would create a single query with all the selected tags separated by a space.

**Comment by torkelo** [comment]
@Akeru I do not know what the graphite tags api support, do you?

**Comment by Akeru** [comment]
@torkelo not really but after some trials it seems to work. Create an annotation that match "event1, event2" and you will only get events tagged using both events.

**Comment by ernoaapa** [comment]
The Graphite event api is implemented little bit stupid way.
The event have "tags" which is not array, it's string. But you can store there values by space separated or "," separated.

So for example:
Send event with "tags" value: "deploy,stage,started"
Send event with "tags" value: "deploy,production,started"

To filter in Grafana "deploy started" events, write to the tags field "deploy stage" and it will return both events. Note that it must be space in between the tags.

What would be cool tho is that Grafana would split that "tags" field value by space and ",". Now in the UI it shows the "deploy,stage,started" as one tag which doesn't look nice.
![screen shot 2015-05-27 at 11 05 35 am](https://cloud.githubusercontent.com/assets/662535/7831549/56c5aa34-0460-11e5-8598-35a5e8edd11a.png)

**Comment by torkelo** [comment]
Working on this now, 

![image](https://cloud.githubusercontent.com/assets/10999/7834642/8edb17b8-0471-11e5-8ad2-04a9089b8ec6.png)

**Comment by Akeru** [comment]
Woohoo ! :+1:

**Comment by ernoaapa** [comment]
Sweet F**! How quickly! Thanks @torkelo ! :+1:

**Comment by kylemallory** [comment]
Any chance this will support Annotations from TSDB?  I have working code 
I can share if you like...

--Kyle

**Comment by torkelo** [comment]
@kylemallory the tags display on annotations will work with any data source as long as they return an annotation object with a tags property that is either an array of strings, comma seperated string, or space seperated string.

**Comment by sndl** [comment]
Hi, is it possible to create annotation that will be displayed only if all tags are present - something like AND operator? I tried different combinations, but no luck so far.

**Comment by torkelo** [comment]
@sndl not sure the Graphite api support that

**Comment by ernoaapa** [comment]
@sndl sadly the Graphite API is really bad but I find out that you can use multiple tags like this:
<img width="256" alt="screen shot 2015-08-31 at 8 36 50 pm" src="https://cloud.githubusercontent.com/assets/662535/9585509/186b5e80-5020-11e5-92ef-897ff8e5bbfe.png">

But there is few things:
Graphite returns only events what contains all the tags `foobar`, `error`, `production` as expected **but** if doesn't find one of them, for example `foobar`, it returns all events what have `error` and `production`.

This causes kinda strange annotations sometimes because we use `$server` templating variable in the tag list and if it's new server and there is no events relating to it, it shows all events from all servers.

**Comment by torkelo** [comment]
@ernoaapa I see, sounds like a bug in Graphite :(

**Comment by sndl** [comment]
@ernoaapa that's better than nothing. Thanks a lot for this workaround and for the warning about $server variable, because that's exactly what I'm trying to do.

**Comment by obfuscurity** [comment]
Note that since https://github.com/graphite-project/graphite-web/pull/1627 (itself based on https://github.com/graphite-project/graphite-web/pull/636), Graphite correctly serializes and returns event tags as an array.

**Comment by obfuscurity** [comment]
I've opened a PR to add support for alternative set types (e.g. union vs intersection) in Graphite event searches: https://github.com/graphite-project/graphite-web/pull/1643

**Comment by orende** [comment]
Did this ever get fixed? If so, what's the syntax for selecting multiple tags to show in an annotation tooltip?
