### ISSUE TITLE
Explore: Use CustomScrollbar for this whole page

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14752]
When executing query whole page changes width as the logs panels is cleared of times then filled again, so for a period the page has scrollbar (that takes up widht) and then it has not , and then it has it again. 

Using the CustomScrollbar will add a overlay scrollbar (for OSs that do no support native overlay)  

Open question: Should any part of the page be fixed (like header), like it is in dashboard?

**Comment by davkal** [comment]
> Should any part of the page be fixed (like header), like it is in dashboard?

IMO there is nothing important enough to be shown at all times.
