### ISSUE TITLE
[bug ?] problem with averages 

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#14756]
### What Grafana version are you using?
Grafana v5.4.2 (commit: d812109)

### What datasource are you using?
Elasticsearch

### What OS are you running grafana on?
Debian 9

### What did you do?

Our customers complains about averages shown in Grafana. I checked it and it looks like there is following problem with calculation of averages in Grafana. Please see picture and data:

![screenshot from 2019-01-07 14-40-35-x](https://user-images.githubusercontent.com/17564930/50771379-c74cd980-128a-11e9-969a-b8df0a1b9064.png)

Looks like problem is with numbers taken into consideration. Time range for the graphs is from `now-12d` to `now-1d` - this gives 11 data points in graphs. But looks like Grafana calculates average from 12 data points - it even exports as first data point value 0 for previous day which is not show (and of course in reality this value is not 0).

First graph shows average 13,37% but taken from data average should be 14,58%

Time | Value
-- | --
2018-12-27T01:00:00+01:00 | 13.219
2018-12-28T01:00:00+01:00 | 14.622
2018-12-29T01:00:00+01:00 | 15.72
2018-12-30T01:00:00+01:00 | 14.286
2018-12-31T01:00:00+01:00 | 14.619
2019-01-01T01:00:00+01:00 | 13.34
2019-01-02T01:00:00+01:00 | 16.797
2019-01-03T01:00:00+01:00 | 16.57
2019-01-04T01:00:00+01:00 | 13.317
2019-01-05T01:00:00+01:00 | 14.722
2019-01-06T01:00:00+01:00 | 13.261
average | 14.5884545454545

(average with additional first data point 0 = 13,3728%)

Similar with second graph:

overall rate:

Series | Time | Value
-- | -- | --
overall rate | 2018-12-27T01:00:00+01:00 | 10.742
overall rate | 2018-12-28T01:00:00+01:00 | 19.226
overall rate | 2018-12-29T01:00:00+01:00 | 17.87
overall rate | 2018-12-30T01:00:00+01:00 | 18.984
overall rate | 2018-12-31T01:00:00+01:00 | 20.362
overall rate | 2019-01-01T01:00:00+01:00 | 12.281
overall rate | 2019-01-02T01:00:00+01:00 | 13.523
overall rate | 2019-01-03T01:00:00+01:00 | 11.032
overall rate | 2019-01-04T01:00:00+01:00 | 15.271
overall rate | 2019-01-05T01:00:00+01:00 | 13.838
overall rate | 2019-01-06T01:00:00+01:00 | 13.393
  | average | 15.1383636363636

desktop:

desktop | 2018-12-27T01:00:00+01:00 | 14.286
desktop | 2018-12-28T01:00:00+01:00 | 20.679
desktop | 2018-12-29T01:00:00+01:00 | 20.216
desktop | 2018-12-30T01:00:00+01:00 | 16.34
desktop | 2018-12-31T01:00:00+01:00 | 21.788
desktop | 2019-01-01T01:00:00+01:00 | 15.029
desktop | 2019-01-02T01:00:00+01:00 | 14.646
desktop | 2019-01-03T01:00:00+01:00 | 13.889
desktop | 2019-01-04T01:00:00+01:00 | 19.415
desktop | 2019-01-05T01:00:00+01:00 | 18.095
desktop | 2019-01-06T01:00:00+01:00 | 18.919
  | average | 17.5729090909091

mobile:

mobile | 2018-12-27T01:00:00+01:00 | 9.182
mobile | 2018-12-28T01:00:00+01:00 | 18.239
mobile | 2018-12-29T01:00:00+01:00 | 16.732
mobile | 2018-12-30T01:00:00+01:00 | 20.537
mobile | 2018-12-31T01:00:00+01:00 | 19.392
mobile | 2019-01-01T01:00:00+01:00 | 10.882
mobile | 2019-01-02T01:00:00+01:00 | 12.698
mobile | 2019-01-03T01:00:00+01:00 | 9.023
mobile | 2019-01-04T01:00:00+01:00 | 11.801
mobile | 2019-01-05T01:00:00+01:00 | 10.865
mobile | 2019-01-06T01:00:00+01:00 | 9.989
  | average | 13.5763636363636

Our customers have real problem with this situation because technically they have to manually export all data, correct them by removing first 0 data points and calculate averages on their own. 

Thank you for looking at it.

**Comment by torkelo** [comment]
What does your query return ? Open Query inspector in metrics tab. Grafana calculates averages on all data points returned by your ES query. 

What does your ES query look like? Any derivative or pipeline metric?

**Comment by torkelo** [comment]
unable to replicate any issue

**Comment by machytkafitanalytics** [comment]
Uh-oh, you are right - 0 data point is really returned by ES due to aggregations used in query. Mea culpa... 
Thanks.
