### ISSUE TITLE
 block login attempts after several unsuccessful ones

### ISSUE THREAD

**Issue by Bart-Ver** [grafana/grafana#14755]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.2.2
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Unix
### What did you do?
N.A. 
### What was the expected result?
N.A. 
### What happened instead?
N.A.
### If related to metric query / data viz:
N.A.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
N.A.

Grafana doesn't block you from attempting to login with incorrect credentials. Does anyone know if there is a way to block login attempts after several unsuccessful ones? Right now it's even exposed to simplest way of deciphering like bruteforce or ddos for completely breaking the servers.

**Comment by torkelo** [comment]
if you fail to login 5 times during 5 minutes then you will be blocked (so max 5 failed attempts during every 5min window)

**Comment by daniellee** [comment]
Are you saying that the brute force protection is not working? It should work like Torkel says. Code [here](https://github.com/grafana/grafana/blob/master/pkg/login/brute_force_login_protection.go).

**Comment by Bart-Ver** [comment]
Indeed, brute force doesn't seem to work. We can try as many times as we want. If you want I can provide you with a link to test, but I'd prefer to give it in a private message.

**Comment by torkelo** [comment]
And you have not disabled brute force protection in ini file ?

What are you ini options? DB, auth etc

**Comment by Bart-Ver** [comment]
Which parameter would disable the brute force protection in the ini file? For most settings we use the default. 

The only setting which are not default below. 

Also the grafana DB is the default one. 



app_mode = production

[security]
admin_user = ****
admin_password = ****
login_remember_days = 0

[users]
allow_sign_up = false
allow_org_create = false

[dashboards.json]
enabled = true
path =****

[smtp]
enabled = true
host = ****
;user = ****
;password =
;cert_file =
;key_file =
;skip_verify = false
from_address = ****
[emails]
welcome_email_on_sign_up = true
templates_pattern = ****


[server]
# Protocol (http or https)
protocol = https

**Comment by marefr** [comment]
Setting the `disable_brute_force_login_protection` parameter to `true` will disable the brute force login.

Default is:
```ini
[security]
disable_brute_force_login_protection = false
```

Please note that the brute force login only applies when entering a wrong password for an existing username.

**Comment by torkelo** [comment]
closing this, if you have more info on how to replicate we can open it

**Comment by ShirgoskiKristijan** [comment]
If the bruteforce login only applies for testing passwords for existing usernames, then you can figure out which usernames already exist. Isn't that something which you normally don't want to allow?
