### ISSUE TITLE
[Feature request] Axis unit - data rate (IEC)

### ISSUE THREAD

**Issue by PauloTemenos** [grafana/grafana#14757]
When specifying the unit for the Y1/Y2 axis, we have these options for data amounts:
- data (IEC), 1K = 1024; 1M = 1024K, etc.
- data (Metric), 1K = 1000; 1M = 1000K, etc.

However, for data **rates**, we only have the option of "data rate" _(which appears to be 1K = 1000)_.

Change Request - rename "data rate" unit type to "data rate (Metric)".
Feature Request - add the option for IEC data rates.

**Comment by jonathaneichelberger** [comment]
+1
