### ISSUE TITLE
how do you use constantLine(value)

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1475]
Hi Torkel,

Were you able to use graphites constantLine(value) functiion in grafana. I cannot get to work. Is this supported?

I have it like this:

constantLine(averageSeries(cloud.dc1.web.*.*.PctCpuUsed), 30)

**Comment by torkelo** [comment]
what version of graphite do you use? You are probably hitting this graphite bug, https://github.com/graphite-project/graphite-web/issues/375

**Comment by gsaray101** [comment]
I am using version 
WEBAPP_VERSION = '0.10.0-alpha'

**Comment by torkelo** [comment]
ok, do you get an error from graphite? open the chrome dev tool and network tab and inspect the graphite response for the /render request
