### ISSUE TITLE
Grafana 2.0: deb & rpm packaging and init.d scripts

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1476]

**Comment by torkelo** [comment]
This is now available for testing:

http://grafana.org/download/builds

 On Ubuntu or Debian download the .deb file and execute this command

```
sudo dpkg -i grafana_[the version you downloaded].deb
```

On Redhat or Centos download the .rpm file and execute this command

```
sudo rpm -Uvh grafana_[the version you downloaded].rpm
```

The install will do the following
- Install binaries and frontend files under `/opt/grafana/versions/<version>`
- Symlink dir `/opt/grafana/current` to `/opt/grafana/versions/<version>`
- Symlink `/etc/init.d/grafana` to `/opt/grafana/current/scripts/init.sh`
- Add config file to `/etc/opt/grafana/grafana.ini` , this is where you specify your config settings
- Default configuration is in `/opt/grafana/current/conf/defaults.ini`, do not modify that file
- The default configuration specifies log file at `/var/log/grafana/grafana.log`
- The default configuration specifies sqlite3 db at `/opt/grafana/data/grafana.db`
- Start grafana by `sudo service grafana start`
- This will start grafana process as the `grafana` user (created in .deb install)
- Default http port is `3000`

There is also a generic linux tar file which you can extract and run grafana directly
from the folder it extracts to.  This file does not contain any setup scripts (for init.d, etc).

**Comment by FlorinAndrei** [comment]
(the quotes are actually from your email to the list)

> I have been working on .deb and rpm packaging recently and would like some feedback.

Very nice, thanks.

> * Install binaries and frontend files under /opt/grafana/versions/<version>
> * Symlink dir /opt/grafana/current to /opt/grafana/versions/<version>

This is not necessary with packages. The whole point of using packages is avoiding doing tricks with symlinks pointing at versions (which is what you'd normally do when installing from tar).

> * Add config file to /etc/opt/grafana/grafana.ini , this is where you specify your config settings

If you add things in /etc, don't bother with opt/. Just put everything in /etc/grafana

Alternatively, keep all configs in /opt/grafana/conf or similar. This is also acceptable - some would say it's preferred if you store your app in /opt, but it's a matter of taste.

Any location is ultimately fine, as long as you make it very obvious in the init file, via a variable such as CONF_FILE or something.

An even nicer way would be to store such runtime variables in a definition file such as /etc/sysconfig/grafana (on Red Hat) or /etc/defaults/grafana (on Debian), and have the init script source that file at the beginning. Another variable that typically goes there is OPTS or PARAMS or SWITCHES, allowing admins to tweak command-line options without having to hack the init script.

> Is it ok to hard code install location to /opt/grafana  ?

It definitely goes against the various filesystem layout standards, but these standards are rather more advisory than mandatory. Some people feel that having a working package is better than nothing at all, even if the layout is not followed to the letter.

**Comment by torkelo** [comment]
@FlorinAndrei thanks for your feedback! 

I have changed the config path to `/etc/grafana/grafana.ini`. 

Right now there is no `/etc/defaults/grafana` file to override OPTS/PARAMS in init script, but that can be easily added soon.

**Comment by torkelo** [comment]
I also added grafana_latest_amd64.deb , grafana-latest-1.x84_64.rpm  to make it easier to find the latest build in the list of builds, also removed the git sha from the file name.

**Comment by markusr** [comment]
Could you please also add packages for i386? I have some hosted root servers that still run under i386,

**Comment by kifj** [comment]
I've build the package for i386 (on Fedora 22) according to the instructions (more or less straightforward from the instructions given) - if still in need, you findit here: http://johannes-beck.name/binary/grafana-2.0.2-1.i686.rpm
