### ISSUE TITLE
Repeat panel and split into rows

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#14765]
I came up with a case when I render hunders of panels using Repeat Panel by Variable feature. The problem is that when I render such amount of panels, DOM tree is huge and dashboard then behaves very choppy (after it loads that takes one minute on high tier laptop).

My case is that there's one panel and a dashboard variable that fetches data from datasource and that panel is then repeated by it so the number of panels is dynamic.
 
I was thinking that rows might be a solution because they can be collapsed but the problem is that panels are repeated dynamically in this case so I cannot define for example one row per 50 panels, initially collapsed because there's not such feature in Grafana. Only thing I can now do is encapsulate all repeated panels into a row but that is not a solution.

I stumbled upon this thread where people have similar issue https://community.grafana.com/t/pagination-in-grafana-any-plans/4795/12.

Wondering whether extending Repeat By feature by splitting panels into rows by predefined number would make sense to you. Something similar

![image](https://user-images.githubusercontent.com/327717/50827967-4bad6400-1340-11e9-83a3-f763ddc83128.png)

Please include this information:
### What Grafana version are you using?
master, living on the bleeding edge

**Comment by ravikanth39** [comment]
+1

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
