### ISSUE TITLE
How to show current process running in grafana?

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14760]
Tried various ways to list process that are currently running. All are resulting in error.
Please help me in fixing this,!

Thanks in advance!
Siddharth

**Comment by daniellee** [comment]
What do you mean by process running in Grafana? Do you mean queries?

**Comment by Siddhu1096** [comment]
Yes, I've added graphite as datasource. And I need to see what all processes are running in my server through grafana.

**Comment by torkelo** [comment]
you usually don't use graphite for this. 

But read the docs for the collectd plugins your using to collect process metrics, it should list what metrics are recorded. 

Please ask questions on the community site https://community.grafana.com
