### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by LesterDong** [grafana/grafana#14761]
I got an error when use the pie chart,here is the stack:
TypeError: Cannot read property 'length' of undefined
    at t.isMsResolutionNeeded (http://localhost:3000/public/build/app.dfabdd44b3be44288eac.js:1:165399)
    at new t (http://localhost:3000/public/build/app.dfabdd44b3be44288eac.js:1:162236)
    at PieChartCtrl.seriesHandler (http://localhost:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:175:26)
    at Array.map (<anonymous>)
    at PieChartCtrl.onDataReceived (http://localhost:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:168:36)
    at s.emit (http://localhost:3000/public/build/vendor.dfabdd44b3be44288eac.js:86:11360)
    at t.emit (http://localhost:3000/public/build/app.dfabdd44b3be44288eac.js:1:181443)
    at PieChartCtrl.e.handleQueryResult (http://localhost:3000/public/build/app.dfabdd44b3be44288eac.js:22:485969)
    at http://localhost:3000/public/build/vendor.dfabdd44b3be44288eac.js:130:92198
    at http://localhost:3000/public/build/vendor.dfabdd44b3be44288eac.js:130:92295

And i use the latest plugin version( V1.3.4), but the pie is worked fine on Kibina,here is the response of elasticsearch:

  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1/_msearch",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"trade_info\",\"max_concurrent_shard_requests\":256}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"createTime\":{\"gte\":\"1537240072264\",\"lte\":\"1537293973068\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"2\":{\"terms\":{\"field\":\"merId\",\"size\":10,\"order\":{\"1\":\"desc\"},\"min_doc_count\":1},\"aggs\":{\"1\":{\"sum\":{\"field\":\"orderAmt\"}}}}}}\n"
  },
  "response": {
    "responses": [
      {
        "took": 3,
        "timed_out": false,
        "_shards": {
          "total": 5,
          "successful": 5,
          "skipped": 0,
          "failed": 0
        },
        "hits": {
          "total": 176638,
          "max_score": 0,
          "hits": []
        },
        "aggregations": {
          "2": {
            "doc_count_error_upper_bound": -1,
            "sum_other_doc_count": 129547,
            "buckets": [
              {
                "1": {
                  "value": 5367610771
                },
                "key": "929000095022319",
                "doc_count": 28431
              },
              {
                "1": {
                  "value": 1336861082
                },
                "key": "929000000000030",
                "doc_count": 94
              },
              {
                "1": {
                  "value": 826134238
                },
                "key": "929030000084035",
                "doc_count": 1993
              },
              {
                "1": {
                  "value": 816355698
                },
                "key": "929000000000017",
                "doc_count": 1411
              },
              {
                "1": {
                  "value": 700609508
                },
                "key": "929000095023982",
                "doc_count": 2137
              },
              {
                "1": {
                  "value": 684607153
                },
                "key": "929000095024067",
                "doc_count": 2576
              },
              {
                "1": {
                  "value": 684258329
                },
                "key": "929000095025226",
                "doc_count": 3882
              },
              {
                "1": {
                  "value": 680390156
                },
                "key": "929000095023983",
                "doc_count": 2768
              },
              {
                "1": {
                  "value": 677006425
                },
                "key": "929000095024069",
                "doc_count": 2685
              },
              {
                "1": {
                  "value": 651594621
                },
                "key": "929040095022686",
                "doc_count": 1114
              }
            ]
          }
        },
        "status": 200
      }
    ]
  }
}

**Comment by torkelo** [comment]
sadly you need to return time series (date histogram) for the pie chart to work
