### ISSUE TITLE
Global ErrorBoundary to catch errors

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#14776]
We have a generic ErrorBoundary component, we should use it for react-container as a top level catch of react render errors.

**Comment by jschill** [comment]
One finding after debugging another issue with the current ErrorBoundary is that it doesn't catch async errors. So the ErrorBoundary is not a holy grail, we still need custom error handler for async actions.

@peterholmberg might have input re this.

**Comment by aocenas** [comment]
What would be the fallback view in case of error? If it was top level, there would be no UI by default. We would need to provide some separate UI for user to navigate somewhere safe (home for example) or some message what to do, refresh in this case could just trigger the error again if the URL has some persisted state.

Also I think it would make sense and be low effort/maintenance to have top level routes also wrapped. That way if there is serious bug in settings we could still keep the navigation and user could just go elsewhere, while the message could be just very generic.

**Comment by torkelo** [comment]
The sidemenu would still be there, as it's outside the route container
