### ISSUE TITLE
Ability to make series visible/invisible from a template parameter

### ISSUE THREAD

**Issue by shadow000fire** [grafana/grafana#1477]
When you edit a panel, you can set a particular series to be visible or invisible without deleting the expression.  If would be nice to have a template parameter that could be set to true/false and have that parameter control a series is visible or not.

Some simple boolean logic like !showAverages or showAverages | showFunctions would be an added bonus!

**Comment by torkelo** [comment]
now sure template variables is suitable for this.

**Comment by torkelo** [comment]
But interesting idea :)
