### ISSUE TITLE
Query construction for grafana does not make parenthesis requirement obvious

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#14777]
Grafana version: 5.4.2

Using the query builder for grafana, a user can easily build up a query like this:

host =~ [ $Host ] AND type = [typeA] AND type_instance = [instb] AND instance =~ [ $instgroupA ] OR instance =~ [ $instgroupB ]

and walk away thinking that the graph will show both instgroupA or instgroupB from $Host. What I expect it to do is to translate the query into:

host =~ [ $Host ] AND type = [typeA] AND type_instance = [instb] AND ( instance =~ [ $instgroupA ] OR instance =~ [ $instgroupB ] )

This is of course wrong.

The "OR" denotes the start of a new query. What is required is:

host =~ [ $Host ] AND type = [typeA] AND type_instance = [instb] AND instance =~ [ $instgroupA ] OR host =~ [ $Host ] AND type = [typeA] AND type_instance = [instb] AND instance =~ [ $instgroupB ]

If the "OR" was forced to be either the "END" or a line or "START" of a line maybe this would be clearer? I know, it performs correct for "math logic" but users aren't logical.

The interface here does not help the user from making "simple" mistakes.

Is there anything that can be done to help?

**Comment by torkelo** [comment]
You can switch to text edit mode if you want to add parenthesis to your complex where clause, otherwise Grafana will use the default InfluxDB operator binding rules (constructing a query without any parenthesis)
