### ISSUE TITLE
Table Panel: Sort puts `-` as "largest" number

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#14782]
I'd like to interpret the missing values as low, not high.

<img width="117" alt="screenshot 2019-01-09 at 10 47 16" src="https://user-images.githubusercontent.com/444037/50894751-f2a30600-13fb-11e9-9cf0-e6fe9e3b0293.png">

/cc @bergquist

**Comment by torkelo** [comment]
strange, we had a PR that fixed this, https://github.com/grafana/grafana/pull/12362 must have been a regression recently

**Comment by tomwilkie** [comment]
I could be running a version without that fix, let me check on master.

**Comment by tomwilkie** [comment]
Still happens on master (96759e3) AFAICT

**Comment by fernandrone** [comment]
This is still relevant. Running Grafana v6.6.2 (3fa63cfc34):

![image](https://user-images.githubusercontent.com/7269710/79799163-6be41500-8330-11ea-8b4c-e391a5df0c62.png)

I'll open an issue for it.

**Comment by baldmaggots** [comment]
Still an issue on Version 6.6.2 (3fa63cfc34)

**Comment by speakyourcode** [comment]
I'm also having issues when sorting negative numbers. Looking at the code I can see that Grafana uses [react-table](https://github.com/tannerlinsley/react-table), which by default sets `sortType` to `alphanumeric` and Grafana doesn't change it:

https://github.com/grafana/grafana/blob/277aee864269753d45a2a2e725998aac59f592e9/packages/grafana-ui/src/components/Table/utils.ts#L54-L63

Shouldn't `sortType` change based on the query return type? For example to `basic` if the query returns numbers...

**Comment by dprokop** [comment]
This is now fixed with https://github.com/grafana/grafana/pull/25421 (Grafana 7.0.4)
