### ISSUE TITLE
Table Panel: Numeric columns are sorted alphabetically

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#14781]
<img width="138" alt="screenshot 2019-01-09 at 10 44 17" src="https://user-images.githubusercontent.com/444037/50894645-a952b680-13fb-11e9-8c4b-1ac4d0930d2a.png">

/cc @bergquist

**Comment by GithubUser5462** [comment]
Any news regarding this issue?

**Comment by burcsade** [comment]
This has been bothering us for quite a while. Sorting numerical columns alphabetically serves no purpose. It would be great to have an option to switch sorting between alphabetically and numerically.

**Comment by torkelo** [comment]
What does your query return? strings or numbers? can you show raw result in query inspector?

**Comment by tomwilkie** [comment]
Here is a link to one of our dashboards (from the kubernetes mixin) that has the issue:

https://admin-ops-tools1.grafana.net/grafana/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?panelId=2&edit&fullscreen&orgId=1&refresh=10s&var-datasource=1-ops-tools1&var-cluster=ops-tools1&var-namespace=cortex-ops

And here is the result of the query from the query inspector:

https://gist.github.com/tomwilkie/de63eb15806d6ac97e075ac351b280f8

HTH!

**Comment by burcsade** [comment]
Here is the query result from InfluxDB using the beta connector.

> ,result,table,_start,_stop,network,filled,impressions,requests
,_result,0,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,AC,76803,5028,723297
,_result,1,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,AM,1452667,287740,5024671
,_result,2,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,CB,134675,10203,220272
,_result,3,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,FB,186880,94170,4425789
,_result,4,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,IS,34596,1541,826744
,_result,5,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,MO,52292,29626,2284616
,_result,6,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,TJ,31821,5930,101539
,_result,7,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,UA,282618,30391,355660
,_result,8,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,VU,483570,23201,695960

![image](https://user-images.githubusercontent.com/820929/74853361-1e522880-533e-11ea-9d68-6d29eb3fc51d.png)

**Comment by burcsade** [comment]
Here is the query result from InfluxDB using the beta connector.

> ,result,table,_start,_stop,network,filled,impressions,requests
,_result,0,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,XX,76803,5028,723297
,_result,1,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,YY,1452667,287740,5024671
,_result,2,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,ZZ,134675,10203,220272
,_result,3,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,AA,186880,94170,4425789
,_result,4,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,BB,34596,1541,826744
,_result,5,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,CC,52292,29626,2284616
,_result,6,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,DD,31821,5930,101539
,_result,7,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,EE,282618,30391,355660
,_result,8,2020-02-18T23:00:00Z,2020-02-19T22:59:59.999Z,FF,483570,23201,695960

![image](https://user-images.githubusercontent.com/820929/74853823-bd772000-533e-11ea-8581-a5dcbfc04831.png)

**Comment by burcsade** [comment]
Any news regarding this issue?

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/25421
