### ISSUE TITLE
Table panel: can I specify a default column sort for dashboard load?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#14787]
/cc @bergquist

**Comment by torkelo** [comment]
Click on column header to specify sort order, then save dashboard:

persisted via this panel property, where col is the column index
```
 "sort": {
    "col": 2,
    "desc": false
  },
``

**Comment by tomwilkie** [comment]
Thanks!

**Comment by sirajshe** [comment]
is it possible to somehow sort by multiple columns ie., _order by col1, col2_

**Comment by orena1** [comment]
Not sure it works with grafana 7

**Comment by jbwaclawski** [comment]
Yeah, I'm running 7.0.0 and can't get this method of default sort to work.

Anyone else have any other luck?

**Comment by steenstra** [comment]
Sorting the table by clicking on the column name and saving the dashboard doesn't work anymore with tables created in Grafana 7.

It does work with the tables created before Grafana 7, since they have a different format:
"type": "table-old"

**Comment by torkelo** [comment]
Upgrade to 7.0.3

**Comment by mmotoszko** [comment]
In Grafana v8.5.6 sorting by clicking the column name to sort, then saving the dashboard worked.

in panel properties this is represented as:
```
  "options": {
    "sortBy": [
      {
        "desc": false,
        "displayName": "my_column_name"
      }
    ]
  },
```

**Comment by protekshen** [comment]
Guys, sometimes it's not workin

But you can change it manually in JSON

just click on panel options => Inspect => Panel JSON 

then try to find "sortBy" or add it by yourself

Then save your dashboard. => should works, good luck!

<img width="300" alt="Screenshot 2023-05-12 at 16 10 47" src="https://github.com/grafana/grafana/assets/13870417/f01fa1ed-2904-45ae-9cfa-d5e37337267d">

<img width="300" alt="Screenshot 2023-05-12 at 16 10 54" src="https://github.com/grafana/grafana/assets/13870417/fd1fd0b6-63b8-4884-aff7-df8ee6214ce9">
