### ISSUE TITLE
Is it possible to manually save different dashboards using the JS code?

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#1479]
We just got grafana up and running and so far are pretty happy with it but we are running into one issue.  We don’t have or use ES currently.  We are looking into it but it would simplify things if we could just manually create dashboards and then same them locally somewhere on the server that is hosting grafana.  Is that possible?  I’ve been able to export the JS from a dashboard I created however I can’t figure out a way to save that.

Thanks,
Dan

* I tried to use your mailing list but was unable to sign up

**Comment by torkelo** [comment]
Just export the dashboard to json files and export them via the UI, then put the json files in the app/dashboards folder. 

you can then load them using the URL syntax ``#/dashboard/file/my_dash.json``

**Comment by danfinn** [comment]
Ok, thanks.  I was kind of hoping that they would show up in the saved dashboard section and they could be viewed and selected from the GUI.  I"ll play with this and see if I can get it to work.
Thanks,Dan 

     On Thursday, February 12, 2015 11:19 PM, Torkel Ödegaard <notifications@github.com> wrote:
   

 Just export the dashboard to json files and export them via the UI, then put the json files in the app/dashboards folder. you can then load them using the URL syntax #/dashboard/file/my_dash.json—
