### ISSUE TITLE
Custom Panel Import Problem, Colors and Annotations not loaded

### ISSUE THREAD

**Issue by josefkorbel** [grafana/grafana#14799]
Run into issue while using custom chart panel (Actually it is forked version of grafana panel that I need to modify) but two paths are returning 404 for me. Those are (logs from grafana-server):
- `path=/public/app/core/utils/colors status=404`
- `path=/public/app/features/annotations/all status=404`

I am using `app/**/**` all over the place but only those two are returning 404.

Example imports that works normally:
- `import { tickStep } from 'app/core/utils/ticks';`
- `import { appEvents, coreModule, updateLegendValues } from 'app/core/core';`
- `import config from 'app/core/config';`

Two imports that are failing:
- `import colors from 'app/core/utils/colors';`
- `import { EventManager } from 'app/features/annotations/all';`

### What Grafana version are you using?
> 5.4.2
### What datasource are you using?
> Default Random Walk (None)
### What OS are you running grafana on?
> Ubuntu 18.04.1 LTS
### What did you do?
> Built grafana from source, added copy of grafana panel to `data/plugins`, added Gruntfile, package.json and other files needed for building that panel. Plugin built. Grafan Built. Frontend Assets Built, Grunt ran..
### What was the expected result?
> No 404 in console (loading colors and annotations)
### What happened instead?
> 404 status when accessing those files
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Request: 
`http://localhost:3000/public/app/core/utils/colors?_cache=1547047767088`
 
Respone:
HTML page saying
>If you're seeing this Grafana has failed to load its application files

**Comment by torkelo** [comment]
Those imports are not available to external plugins

**Comment by josefkorbel** [comment]
Hello @torkelo , is there a way to make this work? I am struggling with documentation really, I am just trying to extend the current grafana panel, I doubt I am the first one.

**Comment by torkelo** [comment]
Copying the graph panel to an external plugin is not supported

**Comment by josefkorbel** [comment]
There has to be way. I can solve the colors, those are easy, but annotations have alot of recursive imports which will require me to copy alot of grafana code. Could you please colaborate a little bit more than basically sayting it is undoable? I believe a template for customizing default grafana panel would be widely appreaciated.

**Comment by josefkorbel** [comment]
That sounds very promising! Do you have any aproximate release date? I've found this [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md) from 2018-08-07 which states that React Panels should theoretically be already done since october-december, any progress news on this @torkelo ?
