### ISSUE TITLE
Ad-hoc filters with prometheus and joins doesn't work

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#14802]
Started off with this query in a table

```
max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared"})
  * on(id) group_right(org_id, org_name, type, name)
sum by (id) (grafanacloud_instance_created_date)
  * 1000
```

Selected "filter for value type=prometheus" and Grafana produce the following (incorrect) query:

```
max by (org_id, org_name, id, name, type) (grafanacloud_instance_info{type=~"prometheus|graphite|graphite-shared",type="prometheus"})
  * on(id{type="prometheus"}) group_right(org_id, org_name, type, name{type="prometheus"})
sum by (id) (grafanacloud_instance_created_date{type="prometheus"})
  * 1000
```

**Comment by baozuo** [comment]
We met a similar issue with `offset`:

Original query:
```
max(druid_datasource_last_segment_rows) by (name) /
max(druid_datasource_last_segment_rows offset 1h) by (name) - 1
```

After selecting `name="abc"`, the filter got applied incorrectly:
```
max(druid_datasource_last_segment_rows{name="abc"}) by (name) / 
max(druid_datasource_last_segment_rows{name="abc"} offset{name="abc"} 1h{name="abc"}) by (name)
```

**Comment by akaoj** [comment]
Hi, same issue with a simple `and` join; i.e: with a `env` filter:
```
sum(
  kube_pod_container_resource_requests{resource="cpu"}
  and on (env,namespace,job,pod)
  (kube_pod_status_phase{phase="Running"} == 1)
) by (node)
```
becomes:
```
sum(
  kube_pod_container_resource_requests{env="prod",resource="cpu"}
  and{env="prod"} on (env,namespace,job,pod)
  (kube_pod_status_phase{env="prod",phase="Running"} == 1)
) by (node)
```
(Grafana 6.1.6, no Grafana backend)

**Comment by ivanahuckova** [comment]
This issue https://github.com/grafana/grafana/issues/26029 is similar to this, but in that case **Ad-hoc filters with prometheus and template variables don't work**

**Comment by aocenas** [comment]
Sort of related to https://github.com/grafana/grafana/issues/19008 so good idea to solve it together.

**Comment by dykow** [comment]
Hi there!
Do you have information when it's going to be fixed?
@aocenas

**Comment by belm0** [comment]
I mentioned it in #19008 (which is really an issue of any `${}` variable access), but I'll repeat here since it's specific to Prometheus syntax:

Substitution is wrong for Prometheus subquery syntax `[foo:bar]` when `bar` is elided:

```
avg(rate((my_metric{instance="foo"} > 0)[3h:])) by (device)
```

```
"avg(rate((my_metric{goversion="go1.13.8",instance="foo"} > 0)[3h{goversion="go1.13.8"}:])) by (device)"
```
