### ISSUE TITLE
Set Grafana OAuth state string to static

### ISSUE THREAD

**Issue by ManivannanMurugavel** [grafana/grafana#14806]
Hi,
Now i have to implement with grafana generic oauth2 login with aws coginito login. Its worked with directly integrated with generic oauth login using random state string. But i need static state string. How can i set static state string.

Please help me.

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by torkelo** [comment]
we provide no way to set the state string to a static value
