### ISSUE TITLE
My template variables don’t work in Prometheus query.

### ISSUE THREAD

**Issue by Davis8988** [grafana/grafana#14809]
I am using a dashboard with two template variables:
Name: SingleInstanceVar , Type: Query, Data Source: Prometheus , Refresh: Never, Query: label_values(wmi_os_time{group="MyTestGroup"},instance) , Sort: Alphabetical (asc).  
Name: MultipleInstanceVar , Type: Query, Data Source: Prometheus , Refresh: Never, Query: label_values(wmi_os_time{group="MyTestGroup"},instance) , Sort: Alphabetical (asc) , Selection Options: Multi-value.  
  
My vars gets populated properly with a number of instances that have the format: name:port.  All my instances have IP addresses instead of a name.
  
I have a Singlestat graph and I am trying to query according to a selected variable.  
My query: sum(wmi_process_start_time{group="MyTestGroup",instance="$I_PUT_MY_VAR_HERE",process="devenv"})  –  which should return 1 if the target is running “devenv.exe”.  
And I set the Repeat: For each value of: ="$I_PUT_MY_VAR_HERE  

I am trying to use the Repeat for each value of $MultipleInstanceVar to generate Singlestat graphs.
  
So when I am using the var: $SingleInstanceVar (in the repeat and the query) it works fine, for each instance I choose from the list I get the correct result if it is running devenv.exe or not.  
But when I am using $MultipleInstanceVar (in the repeat and the query) it doesn’t work.  
  
I inspected the query and I can clearly see the differences between the URLs:  
1 = url:"api/datasources/proxy/1/api/v1/query?query=sum(wmi_process_start_time%7Bgroup%3D%22MyTestGroup%22%2Cinstance%3D%2235.1.187.41%3A9662%22%2Cprocess%3D%22devenv%22%7D)%20%25%2010&time=1547104144"   
2 = url:"api/datasources/proxy/1/api/v1/query?query=sum(wmi_process_start_time%7Bgroup%3D%22MyTestGroup%22%2Cinstance%3D%2235%5C%5C.1%5C%5C.187%5C%5C.41%3A9662%22%2Cprocess%3D%22devenv%22%7D)%20%25%2010&time=1547104125"
   
URL 1 is using the var $SingleInstanceVar in the query  
URL 2 is using the var $MultipleInstanceVar in the query.  

The same between them: “url:"api/datasources/proxy/1/api/v1/query?query=sum(wmi_process_start_time%7Bgroup%3D%22MyTestGroup%22%2Cinstance%3D%2235”  
And the differences between them starts right after that with the signs: “%5C%5C” in the instance’s IP.  
Besides that everything else in the query url is the same as well.  
  
This behavior occurs even if I select only 1 instance in the var $MultipleInstanceVar.  
Aside from that I also use the vars in the Title attribute of the graph it works as expected and generates Singlestat graphs for each instance and put the instance name in the title of the graph.
But for some reason it doesn’t put the instance name in the query. It adds these signs: %5C%5C.  
  
I am using Grafana v5.3.2 (commit: 0d821d0) running on Linux.

**Comment by torkelo** [comment]
for the multi var use regex syntax, example `instance~="$I_PUT_MY_VAR_HERE"  or `instance="${I_PUT_MY_VAR_HERE:raw}" disable regex escaping
