### ISSUE TITLE
tls renegociation problem in Notification channel (webhook)

### ISSUE THREAD

**Issue by fredbcode** [grafana/grafana#14800]
Grafana v5.4.2

I think there is a tls renegociation problem in Notification channel (webhook) the same that datasources before https://github.com/grafana/grafana/pull/9236/commits/cffbcb504d884022f41fc48a6099d15018e01863

At each test I have "local error: tls: no renegociation" in grafana logs, but with firefox the webhook works well

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/14836
