### ISSUE TITLE
Form & Input components for @grafana/ui

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#14812]
Now most of the panel options are wrapped in quite a lot of layout markup, e.g.

```jsx
<div className="section gf-form-group">
  <h5 className="section-heading">Gauge</h5>
  <div className="gf-form">
    <Label width={8}>Min value</Label>
    <input type="text" className="gf-form-input width-12" onChange={this.onMinValueChange} value={minValue} />
    </div>
   ...
```

We could implement option's layout basic components for hiding the markup complexity.

Basic components to implement:
- `FormGroup`
- `FormGroupHeading` (could wrap more abstract Heading component)
- `FormItem` (to wrap Label + input/select/you name it)

**Comment by torkelo** [comment]
yes!

**Comment by torkelo** [comment]
this looks like it can replace https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/DataSourceOption.tsx which looks very much like a wrapper for label + input

**Comment by peterholmberg** [comment]
Looking at FormGroup

**Comment by peterholmberg** [comment]
Looking at `Input.tsx`

**Comment by torkelo** [comment]
The FormField I think might need a rethink so it can be used with other form inputs than just text input as the form-field class is copy of the gf-form styles which represents a "form label+some kind of input pair", so feels wrong to duplicate this for say a Select input. Maybe have FormField be just the container, and then have FormFieldInput and FormFieldSelect? but the props for FormFieldSelect are huge so not sure that is the way to go. Or make FormField have an optional children and if there are children then skip render the input. (for of like FormField has default text input but can be overriden using children prop)

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/FormField/FormField.tsx

**Comment by torkelo** [comment]
Closing this until we know exactly what form components we need and how they should look, we have some basics there but think we need a bit more
