### ISSUE TITLE
Gauge is getting cropped when resizing the panel

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#14815]
![image.png](https://images.zenhubusercontent.com/5c332a288332e72a247d9d08/82c03ce9-e8ed-4a6e-ae50-96fdc4548430)

The broken state is persistent across reloads.

Reporoduced on:
- Chrome
- Safari
- Firefox

**Comment by torkelo** [comment]
ok, strange, with the old angular singlestat panel I could replicate this only on safari, 
https://github.com/grafana/grafana/issues/14715

but if you can replicate this on chrome & firefox it might be another issue that is specific to the react gauge.
