### ISSUE TITLE
Add labels in Time series to support "Pivot by labels" feature in table view. 

### ISSUE THREAD

**Issue by saisantosh** [grafana/grafana#14814]
### Requirement 
Our requirement is to represent time series data pivoted by labels in table view.

For example, if we have 2 time series with labels A, B. The Pivot By representation for A, B as pivots, should transform A, B as table columns along with column operations chosen for each series. Please view the attached screen shots.
Similar to  feature request made in #7169

### Proposed Solution 

For a generic implementation that enables Pivot by feature for core data sources, the response objects returned by these data sources need to have labels information. 

We also propose adding labels as first class property to TimeSeries object. This enhancement will enable "pivot by labels" and also has potential to support other features such as faceted search experience in Explore page and interactive filtering, search by labels in graph panel.

We have a functional, user configurable solution for Elastic Search, Prometheus. To enable this, we have enhanced the response object returned by data sources of Elastic Search, Prometheus to return labels. 
Kindly review our pull request and provide your feedback.

To use "Pivot By Label" for other data sources, the expectation is that the response returned by the data source contains labels(object); 

### Limitations
Usage of  "alias/legend" functionality is suggested to have meaningful column names rather than default alias.

### Single query View
![pivot_single_query](https://user-images.githubusercontent.com/2002995/50963190-0c267980-14f2-11e9-9340-031670e9b3d1.PNG)

### UI configurable View
![pivot_configurable_ui](https://user-images.githubusercontent.com/2002995/50963216-1e081c80-14f2-11e9-90bf-9855e6b7439d.png)

**Comment by saisantosh** [comment]
@marefr  @torkelo Would be good to know your feedback on this feature and the PR.

**Comment by marefr** [comment]
I can see that there are use cases for this, but if table panel should have this it need to support all datasources for starters. Will leave this open for a while and see if it gets more upvotes/more users want/need this.

Seems to me the [Boom Table plugin](https://grafana.com/plugins/yesoreyeram-boomtable-panel) already has support for this, refer to Prometheus guidelines.

**Comment by kalman5** [comment]
The issue here is that some time we don't know in advance how many series we have, at the moment what I'm doing is adding several queries like this:

q1) SELECT t, value FROM test WHERE name = 'A';
q2) SELECT t, value FROM test WHERE name = 'B';
q2) SELECT t, value FROM test WHERE name = 'C';

to have data plot on the same graph, the ideal whould be to have a single query:

SELECT t, value, name FROM test;

and let graphana plot multiple curves for each different value of 'name'

**Comment by torkelo** [comment]
Can this be implemented as a transformation? (new 7.0 concept)

**Comment by scroodj** [comment]
+1

**Comment by zoltanbedi** [comment]
Looks like this is already solved so I'm going to close this issue.
