### ISSUE TITLE
Non Negative Derivative not used for every time frame

### ISSUE THREAD

**Issue by Soulou** [grafana/grafana#14828]
### What Grafana version are you using?

v5.4.0

### What datasource are you using?

InfluxDB

### What OS are you running grafana on?

Linux amd64

### What did you do?

Created a graph using `sum(), non_negative_derivative(1m)`

### What was the expected result?

Have the derivative whatever is the time frame

### What happened instead?

* When time frame is at 30min, the derivative is not computed:

![screenshot from 2019-01-10 18-16-35](https://user-images.githubusercontent.com/329969/50985760-6aa92300-1505-11e9-89b2-96742809a1eb.png)

* When time frame is at 1h, the derivative is correctly computed

![screenshot from 2019-01-10 18-16-10](https://user-images.githubusercontent.com/329969/50985789-7694e500-1505-11e9-9770-3130fa08e2c0.png)

We added an alert on this graph, and we observed the same issue, and reduced the change of behavior between 37 and 38 minutes 

![screenshot from 2019-01-10 18-17-32](https://user-images.githubusercontent.com/329969/50985845-975d3a80-1505-11e9-8a90-f38932cae767.png)

(37m) ^ Here we can see the result used by the alert is a sum

![screenshot from 2019-01-10 18-17-56](https://user-images.githubusercontent.com/329969/50985887-ac39ce00-1505-11e9-8429-fa6efebdb5c1.png)

(38m) Here the alert is ok, the value is 68k, which looks right according to what we're querying.

The query:

```
SELECT non_negative_derivative(sum("count"), 1m) FROM "httpjson_logs_stats" WHERE $timeFilter GROUP BY time($__interval) fill(none)
```

The data:

Growing integers, we're looking to read the diff to display the value.

**Comment by torkelo** [comment]
please open an issue with the InfluxDB project, the non_negative_derivative function is performed by the InfluxDB server

**Comment by Soulou** [comment]
Thanks a lot @torkelo
