### ISSUE TITLE
[Feature Request] A checkbox for Postgres data source to hide partitioned "child" tables

### ISSUE THREAD

**Issue by kmoppel** [grafana/grafana#14827]
### What Grafana version are you using?
Version 5.4.2

### Feature proposal
To add a checkbox to Postgres Data Source page that, when checked, will result in showing only the non-partitioned or partitioned "top level" tables in the Query Builder. 

### Background
If doing some more serious metric storage in Postgres (and other generic RDBMS systems, that are not designed for Time-Series Data) one cannot get around using partitioning features as one can save a lot of IO so. Partitions though, are (mostly) meant to be "invisible" though, so that users will continue to work only with the top level tables. But currently in Grafana, when having enough partitions, the Query Editor will look messy, when only actually a couple of top level tables are used and wanted.
![screenshot from 2019-01-10 19-02-57](https://user-images.githubusercontent.com/346788/50985009-ea39f080-150b-11e9-8765-67c7f9c4c47e.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
