### ISSUE TITLE
Support Doc value fields for Elasticsearch

### ISSUE THREAD

**Issue by flyrev** [grafana/grafana#14829]
### What Grafana version are you using?
5.4.2

### What datasource are you using?
ElasticSearch: Version 6.0+

The actual Elasticsearch version running is 6.5, although this applies to version 6.4 as well.

### What OS are you running grafana on?
Docker image found on https://hub.docker.com/r/grafana/grafana

### What did you do?
Added a datasource with Elasticsearch version 6+ and performed a simple query.

### What was the expected result?
That the `"docvalue_fields"` field would be according to https://www.elastic.co/guide/en/elasticsearch/reference/6.5/search-request-docvalue-fields.html

In my case
```
{
    "field": "@timestamp",
    "format": "epoch_millis" 
}
```
would have been good, since I also already have `"format": "epoch_millis"` inside `query.filter.range.@timestamp`.

### What happened instead?
The query contained `"docvalue_fields":[{"field":"@timestamp"}]`, and I also received a lot of warnings in the Elasticsearch logs saying
`There are doc-value fields which are not using a format. The output will change in 7.0 when doc value fields get formatted based on mappings by default. It is recommended to pass [format=use_field_mapping] with a doc value field in order to opt in for the future behaviour and ease the migration to 7.0: [@timestamp]`

### Possible solution
A good starting point seems to be adding another case in `query_builder.ts` (see lines 127-131).
```
if (this.esVersion ...) {
    query.docvalue_fields = { field: this.timeField, format: 'use_field_mapping' };`
}
```

An additional choice of "version" would be required, since this was introduced in Elasticsearch version 6.4.

A way of specifying this through the UI would be useful.

**Comment by ifrost** [comment]
`docvalue_fields` was removed in https://github.com/grafana/grafana/pull/20290 so the error should not happen with newer versions of Grafana.
