### ISSUE TITLE
Chore: Remove usage of withSize/sizeMe

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14822]
Used here: 
https://github.com/grafana/grafana/blob/3efaf52049ece500a75028dbd15ee0b02966fa4d/public/app/features/dashboard/dashgrid/DashboardGrid.tsx#L64

and here: 
https://github.com/grafana/grafana/blob/66a13b281cd1054e5a742a14e5b31693caa51790/public/app/features/explore/Graph.tsx

Replace with using AutoSizer from react-virtualized. 
https://github.com/grafana/grafana/blob/3efaf52049ece500a75028dbd15ee0b02966fa4d/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L91

It is using render props and it fixed some issues that I had with sizeme and it feels like we should only have one lib that does this.

**Comment by davkal** [comment]
#14821 removes usage in Explore

**Comment by torkelo** [comment]
Great! , then it should only be DashboardGrid which should be super quick.

**Comment by jschill** [comment]
I'm not sure if you were talking about the same thing, but we're still using `withSize` in Graph.tsx. I'll remove it...
