### ISSUE TITLE
~5s delay when switching organisations via API 

### ISSUE THREAD

**Issue by Celos** [grafana/grafana#14826]
### What Grafana version are you using?
5.4.2
### What datasource are you using?
influxdb
### What OS are you running grafana on?
windows/centos
### What did you do?
attempted to switch the active organisation for a user via API
### What was the expected result?
the active organisation is changed
### What happened instead?
there is a 5 second delay

We’re trying to automate creating/updating all the data (users, orgs, dashboards etc) via APIs. Every time we change the freshly created user’s active organisation, the action seems to actually take effect about 5 seconds after issuing the command. Seems there’s a cache somewhere that isn’t getting updated fast enough.

I’ve created a quick and dirty test case (requires java & docker): [GrafanaTest.java](https://gist.githubusercontent.com/Celos/bb215d3ec4643dd1e9c97a7fd8656d96/raw/41a2cb2f8e193fbed6565040cd0b077b6a99c88d/GrafanaTest.java).

It runs grafana via docker, creates two organisations and starts switching the admin user’s active organisation between them. Then it waits until /api/org returns the correct id.
The user in question is admin for simplicity, could be any user.

Output:

```
It took 4834 ms to change the active organization to 2
It took 5016 ms to change the active organization to 3
It took 5000 ms to change the active organization to 2
It took 5013 ms to change the active organization to 3
It took 5012 ms to change the active organization to 2
It took 5014 ms to change the active organization to 3
It took 5014 ms to change the active organization to 2
It took 5005 ms to change the active organization to 3
It took 5019 ms to change the active organization to 2
It took 5019 ms to change the active organization to 3
Took 4994 ms on average
```

This seems like a regression in 5.4.2. Tested with 5.3.4 and the results are quite different.

**Comment by torkelo** [comment]
If you switch org id a lot you can work around the caching of user info by setting org Id via a http header: X-Grafana-Org-Id

if you set id with that header you do not have to change active org
