### ISSUE TITLE
Frontend dev code style guide

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14820]
Need to have write down our frontend code style guide. 

For the most part we have just referred to and tried to follow the airbnb style guide:

https://github.com/airbnb/javascript/tree/master/react 

the most important things to include: 

* File naming
* Folder naming
* Prop naming (events onClose and bools isEnabled etc)
* Callback function naming  (onClose no handleClose for example) 
* how we should organize code 
* Redux guides (fat actions vs small) 

 This should be written in a markdown in repo root

**Comment by marefr** [comment]
Some related wiki content here https://github.com/grafana/grafana/wiki/Frontend:-Code-structure,-architecture-and-plans-for-the-future

**Comment by oddlittlebird** [comment]
We have https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md, so can we close this?

**Comment by marefr** [comment]
@torkelo ?
