### ISSUE TITLE
Feebdack on testing 2.0

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#1483]
I'm currently playing around with 2.0 and you have my full respect. Great job!

Some things I noticed:
- A freshly added data source needs a reload before it shows up for using in a new graph
- When adding a new data source there is no indication if the data source is really available and ready
- The icons like "share" "settings" etc could use some tooltips
- The space between the left hand menu and the green new panel button is very small so you can easily hit a menu item instead of the intend function (see screenshot 1)
- When the left hand menu is open you can have some graphical glitches making it impossible to return to dashboard (see screenshot 2)
- When the quick-select "tile-menu" is open it would be nice to close it when clicking outside of the menu are. As of now another click on the tile-button is needed. You can even generate funny things with it (see screenshot 3)
- The bottom end of the left hand menu creates another graphic glitch. See screenshot 4

I added 3 datasources (Graphite, InfluxDB 0.8.8 and openTSDB) and all worked out of the box. Especially no CORS hassle with openTSDB. All in all I'm really enthusiastic about this new version.

![v2_add_panel](https://cloud.githubusercontent.com/assets/4459312/6194270/04619b6a-b3c3-11e4-971a-44198f449e54.png)
![v2_glitch](https://cloud.githubusercontent.com/assets/4459312/6194269/045db8b0-b3c3-11e4-90b8-b5e6d30f7ca7.png)
![v2_tile_menu](https://cloud.githubusercontent.com/assets/4459312/6194268/045c33aa-b3c3-11e4-830e-7b4b13818e67.png)
![v2_end_of_lh_menu](https://cloud.githubusercontent.com/assets/4459312/6194271/0463e1a4-b3c3-11e4-93ec-4d5cded15be9.png)

**Comment by Sineos** [comment]
- Is the Edit Tab in Data Sources a feature yet to come?
![v2_datasource_edit](https://cloud.githubusercontent.com/assets/4459312/6194492/3c9e328e-b3c5-11e4-9242-93659bf6399a.png)

- A Cancel Button in Edit User would be nice
![v2_cancel_button](https://cloud.githubusercontent.com/assets/4459312/6194493/3ca3f282-b3c5-11e4-827a-29b3bb97a2d9.png)

**Comment by Sineos** [comment]
- Data Sources and Account have different tab / usage philosophy
![v2_ui_account](https://cloud.githubusercontent.com/assets/4459312/6194627/52d5fc3e-b3c6-11e4-8158-9229a90835dc.png)
![v2_ui_data_source](https://cloud.githubusercontent.com/assets/4459312/6194628/52d61fac-b3c6-11e4-8836-9839cd84192c.png)

**Comment by torkelo** [comment]
Thank you so much for taking the time to write down and submit your feedback, we will try to address them asap!

**Comment by Sineos** [comment]
I have to thank you for this great product.

Another thing I noticed:
- Currently I run grafana via "bra run"
- In the gocodez/src/github.com/grafana/grafana/conf/grafana.ini I set "domain = 192.168.178.8"

Console output shows:
2015/02/13 20:13:22 [I] Listen: http://0.0.0.0:3000

lsof also states: TCP *:3000 (LISTEN)

**Comment by torkelo** [comment]
domain is not currently used right now, hm.. should probably removed. http_addr is the option to specify specific IP to bind to

**Comment by Sineos** [comment]
Domain setting is needed currently but the logic behind it is a bit confusing:

[server]
protocol = http
domain = 192.168.178.8
root_url = %(protocol)s://%(domain)s:%(http_port)s/
http_addr = 192.168.178.8
http_port = 3000

- If I set http_addr grafana will correctly bind to it
- If domain is not set to the same IP, then the dashboards etc. stop working because the URL constructor "root_url" will point to the wrong address

The domain setting certainly has its use in some scenarios but may I suggest the following:
- Rename "domain" to "hostname" and make it optional
- Rename "http_addr" to "bind_addr" and apply following logic: If hostname = "" use bind_addr for root_url else use hostname for root_url
- Rename "http_port" to "bind_port"

I think this would make the logic more conforming to the expectations of a "general linux user" ;-)

**Comment by Sineos** [comment]
Descending sort icon is broken (tested in FF and Chrome):
![v2_sort](https://cloud.githubusercontent.com/assets/4459312/6203850/34d5d364-b536-11e4-9785-8d523c253f5e.png)

**Comment by torkelo** [comment]
I am not sure renaming domain to hostname is correct as the option is used only to construct the public facing url, and in that it is used for the domain part, hostname denotes a single server name to me. 

And if I make hostname optional then I would have to make bind_addr required (if that is supposed to be the fallback). And I am not sure http_addr and http_port are better renamed to bind_ it might be a little clearer I agree but grafana might need to bind to more ports in the future, so only having bind_addr is not so good I think. 

I updated grafana.ini with some comments to make the settings more understandable and reordered them:

```ini
[server]
; protocol (http or https)
protocol = http
; the ip address to bind to, empty will bind to all interfaces
http_addr =
; the http port  to use
http_port = 3000
; The public facing domain name used to access grafana from a browser
domain = localhost
; the full public facing root url (used to generate URLs from the api among other things)
root_url = %(protocol)s://%(domain)s:%(http_port)s/
```

**Comment by Sineos** [comment]
Fine for me but one issue still will confuse people:

- Lets say you access a headless Grafana server from within your LAN
- Grafana Server LISTENs to 192.168.178.8:3000
- Domain is set to localhost

With the current root_url construct you will not be able to access any dashboards because Grafana will serach them under: http://localhost:3000/.....

The only way to successfully use Grafana in this case is to set domain = 192.168.178.8 as well. 
This is why I wrote above:

If hostname = "" use bind_addr for root_url else use hostname for root_url

**Comment by costimuraru** [comment]
I've also encountered issues with dashboards redirecting to localhost:3000. After setting the domain to the right value, I got it to work to the point where I changed the docker port mapping. The main page was http://domain:8080 but the dashboards were linking to http://domain:3000. So I had to manually set the root_url to the right value.

One question: Why do we need to use absolute paths when constructing the dashboard urls?
Wouldn't using relative paths (eg. /dashboard/db/grafana instead of http://host:port/dashboard/db/grafana) save us the need for the root_url variable?

**Comment by torkelo** [comment]
the root_url is needed for oauth (need to specify an absolute callback url). And if you have a reverse proxy in front of grafana which adds a subpath, lets say you have an nginx infront whichs proxies requests to /mygrafana to an internal grafana server. 

The absolute urls are generated by the search api, will try to fix this. root_url should only be required in the above scenarios.

**Comment by torkelo** [comment]
I removed the use of absolute urls from dashboard search and dashlist panel. root_url is now optional (only required if you use oauth or proxy grafana under suburl)

**Comment by costimuraru** [comment]
That's awesome @torkelo! Thanks for the quick help.

**Comment by costimuraru** [comment]
Regarding "Testing the 2.0":

1) If you set an invalid Elasticsearch data source (wrong host or port), the Import does not fail with an error. In fact, when you click Import it seems that nothing happens. In the background an HTTP request is made and fails. It would be nice to display an error: "Unable to contact server. Connection refused / Unknown host / etc."

![tt](https://cloud.githubusercontent.com/assets/952836/6235005/c2036d84-b6e7-11e4-9f53-55f9a9e3acd4.png)

**Comment by Sineos** [comment]
Agree on the missing save button but reordering Home works for me. When saving on the "Unsaved Changes" Dialogue it automatically generated a new Home (with the tiles in front instead of the little house)
![image](https://cloud.githubusercontent.com/assets/4459312/6235883/1d3ffc8c-b6e6-11e4-82ff-c0d10d1dd582.png)

**Comment by costimuraru** [comment]
Oh yeah, indeed. The same happened for me, a new Home dashboard was created. On the second attempt however I received the error.
However, my intention was not to have a *new* Home dashboard, but to update the initial one. :D

**Comment by Sineos** [comment]
Yes and on a second thought this does not make much sense at all because it creates kind of a dead second Home screen as a dashboard with which you cannot do anything.

**Comment by torkelo** [comment]
I wanted to have user specific home dashboards (per account), that could be modified/saved/updated. 

But have yet add the save/load feature, right now it is only generated. You can save it CTRL+S (have yet to remove/stop that).

**Comment by Sineos** [comment]
Ah, k. Verfified that it is indeed bound to the user. Maybe "Add Row" should be useable here as well, since there is no way back once you deleted rows and saved.

**Comment by torkelo** [comment]
I think all of the points raised in the main issue (except the green row icon being hard to hit when sidebar is open) have been solved, so will close. Please open another issue if you find more problems, unituitive things, or ideas for improvement.
