### ISSUE TITLE
InfluxDB interactive metrics query editor with regular expression

### ISSUE THREAD

**Issue by mjiderhamn** [grafana/grafana#14837]
Please include this information:
### What Grafana version are you using?
5.4.2 (d812109)

### What datasource are you using?
InfluxDB

### What did you do? / What was the expected result? / What happened instead?

In the interactive mode metrics query editor for InfluxDB, there is no support for regexp conditions (`=~` and `!~`). If entering such conditions in the raw mode and then toggling edit mode, the query will be messed up.

For an example of this, go to
https://play.grafana.org/d/AAy9r_bmk/influxdb-server-monitoring?panelId=1&fullscreen&edit&orgId=1
Strangely this does contain a query that is displayed correctly in the interactive mode.
However if you 
* Toggle to raw mode
* Copy the query string (`SELECT mean("value") FROM "logins.count" WHERE ("datacenter" =~ /^$datacenter$/ AND "hostname" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), "hostname"`)
* Add a query B
* Paste the exact same query into the raw editor
* Toggle back to interactive

the problem will manifest.

**Comment by torkelo** [comment]
You can use regex operators conditions in the editor mode. 

Changes you do in the raw text edit mode will never be carried over to the UI editor as Grafana does not have a full InfluxDB query parser.

**Comment by mjiderhamn** [comment]
For future reference: regexp operators are indeed available/allowed, but only ***after*** entering a regexp value (i.e. surrounded by `/`) into the "`select tag value`" box.

Trying to use `=~` or `!~` with "`select tag value`" still visible, or a regular value in the box, will fail.
