### ISSUE TITLE
Build docker image failed: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by leikao** [grafana/grafana#14835]
Please include this information:
### What Grafana version are you using?
The latest version from master branch.

### What OS are you running grafana on?
linux x86_64

### What did you do?
I'm building the docker image, I get the following errors while executing `make build-docker-dev`:
> Step 1 : ARG BASE_IMAGE=debian:stretch-slim
> Please provide a source image with `from` prior to commit
> make: *** [build-docker-dev] Error 1

### Solution
The version of docker engine on the build environment is out of date (`Docker version 1.11.2, build fb3463e`) which is not support the most recently `Dockerfile` spec. Docker engine **v17.06** supports the ARG instruction occur before the first FROM.
So I suggest to declare the docker dependency in the `README`.

**Comment by leikao** [comment]
> So is this a request to update the documentation?

Yes, I wanna to update the documentation, add docker version dependency.

**Comment by marefr** [comment]
@leikao would you mind open a pull request with change of https://github.com/grafana/grafana/blob/master/README.md then?

**Comment by leikao** [comment]
@marefr No, I'll submit my PR later. 
One of my PR is stilling pending #14866, I'll open a PR to update the `README.md` after it's merged.

**Comment by marefr** [comment]
Cool. Will close this issue for now since a PR for minor docs update doesn't need an issue.
