### ISSUE TITLE
Dynamic SQL & conditional WHERE conditions 

### ISSUE THREAD

**Issue by Dog-Lee** [grafana/grafana#14839]
Please include this information:
### What Grafana version are you using?
The latest version from master branch.
### What datasource are you using?
MySQL
### What OS are you running grafana on?
Mac OS X
### What was the expected result?

I think it will be helful to using dynamic SQL just like Metabase. for example 
```sql
SELECT count(*)
FROM products
[[WHERE category = {{cat}}]]
```
if the cat variable is empty then exec `select count(*) from products`.

```sql
SELECT count(*)
FROM products
WHERE True
  [[AND id = {{id}}]]
  [[AND category = {{category}}]]
```

the metabase doc is https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
