### ISSUE TITLE
Feature request for the Table panel

### ISSUE THREAD

**Issue by mtbakerguy** [grafana/grafana#14833]
It's natural for someone building a table to create derived statistics from the table columns.  While the f(x) capability seems like it should support that operation, it doesn't do so.  Imagine metrics like the following:

`
------------------------------------------------------------------------
 **Identifier**      **2XXCount**  **5XXCount**    **Total**  **Reliability** 
------------------------------------------------------------------------
 Low Volume                999             1                        1000            99.90 
 High Volume             9998             2                     10000            99.98 
------------------------------------------------------------------------
 Aggregate              10997              3                      11000            99.97 
------------------------------------------------------------------------
`

If the datastore only contains the four metrics-- [HL]-2XXCount and [HL]-5XXCount--it appears you can't create the table above.  The (unsatisfying) workaround is to use another panel that does single statistic math.  It would be elegant to add a derived metrics to the table that would be referenced in the following way:

> #A + #B (Low Volume Total) :: (1 - (#A/(#A + #B)) (Low Volume Reliability))*100
> #C + #D (High Volume Total) :: (1 - (#C/(#C + #D)) (High Volume Reliability))*100

I'm assuming there's already a way to specify precision but one should be added if there isn't.

**Comment by torkelo** [comment]
not sure the table panel is the right way to do math and further analytics on your data. 

This should be done mostly in your query or if not supported there maybe in with a feature like this https://github.com/grafana/grafana/issues/3677 

We hope to someday provide a way to to build dyanmic scripted dashboards, that could support code that generates visualizations, which could also solve this.
