### ISSUE TITLE
Alert remain in pending state.

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14830]
Hi Team,

I tried setting up alerts in my dashboard, but it says in pending state rather than ok.
Please mark it as an urgent issue. Also see the screenshots. Also, there is not any error in log file.
![1](https://user-images.githubusercontent.com/22325249/50989641-eb801300-1535-11e9-9603-88c884233c96.PNG)
![2](https://user-images.githubusercontent.com/22325249/50989642-ec18a980-1535-11e9-9480-10c685746fdf.PNG)

**Comment by bergquist** [comment]
The timeserie return by the query is higher than the threshold so it's not supposed to be `OK`.
when `firing` is set to true the condition is met. 

It's in a pending state for 5m before its going into alerting state and sends a notification. 

This is working as expected.

**Comment by michael-will** [comment]
I have a system where it is in pending state for 3 months now, and the actual alert and alert history it links to is empty and all values are well below threshhold.

**Comment by uchihaitachi24** [comment]
Any solution to this? Alerts are always in pending state.
