### ISSUE TITLE
GB is showing as EB on graph

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14847]
Hi team,

I have added the metrics for total memory used.  I need to show in GB format. But, in the graph it shows EB.
PLease help to solve this case
![asdasdasda](https://user-images.githubusercontent.com/22325249/51077155-582b1700-16c8-11e9-8105-2cff7f8f4cd9.PNG)

**Comment by torkelo** [comment]
What is the value your query returns? The unit you specify should represent the value as returned by your query. If your query returns bytes you should select bytes, if your query returns megabytes then select megabytes. 

Is your metric recording values in gigabytes?

**Comment by Siddhu1096** [comment]
Its showing in GB. Take a look at graphite , which is taken as data source
![asdasd](https://user-images.githubusercontent.com/22325249/51077214-3ed69a80-16c9-11e9-89b7-402a53b54e49.PNG)

**Comment by Siddhu1096** [comment]
So, the data is coming in GB. @torkelo

**Comment by torkelo** [comment]
just because the graphs shows a G does not mean that, it can just mean your query returns 1000000000 and the unit is bytes.  Can you show the result of the query in query inspector?

**Comment by Siddhu1096** [comment]
![zxzxz](https://user-images.githubusercontent.com/22325249/51077423-b5c16280-16cc-11e9-9f36-7152425c4dd3.PNG)
There you go. You're right, iT's shows in Bil

**Comment by torkelo** [comment]
So grafana was right, 1 billion gigabytes is 1 Exabyte (EB)

**Comment by Siddhu1096** [comment]
So how can I show to say  13GB here

![asaas](https://user-images.githubusercontent.com/22325249/51077449-105abe80-16cd-11e9-8f97-0fb874412efe.PNG)

**Comment by Siddhu1096** [comment]
> So how can I show to say 13GB here in "total"
> What changes should I do in Axes or anywhere?
> 
> ![asaas](https://user-images.githubusercontent.com/22325249/51077449-105abe80-16cd-11e9-8f97-0fb874412efe.PNG)

**Comment by torkelo** [comment]
You can’t, currently units is not supported in alert notifications

**Comment by Siddhu1096** [comment]
Okay . thanks for your time.

**Comment by Siddhu1096** [comment]
Issue is solved.
