### ISSUE TITLE
Grafana2.0: admin dashboards for certain users/accounts ??

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1484]
Sorry @torkelo I'm not able to understand this  account / user model.

I'm too used to admin  users/groups and permissions and I'm not able to understand how can I show / hide dashboards per user  or account, with your UI, I'm completely lost.

As admin I've created 3 things.

1) different users with I can log in.

![image](https://cloud.githubusercontent.com/assets/5883405/6198910/40429a2c-b421-11e4-84ad-03952ecc0da8.png)

2) different accounts ( after created I'm not able to change them or delete them... how can do it?)

There is no way to detele "toni" account... ??

![image](https://cloud.githubusercontent.com/assets/5883405/6198917/adc220f4-b421-11e4-8392-de8fe5605aaa.png)

3) some dashboards.

![image](https://cloud.githubusercontent.com/assets/5883405/6198924/e828ecb4-b421-11e4-8bbc-a627d5de1955.png)

After that I would like only account  dash_group_1 can view/edit dashboards dash_4_group_1*  , and account_dash_group_2 can only view/edit dashboards dash_4_group_2*

how can I tie this dashboards these accounts?
How can I link user1 or user3 to accounts dash_group_1 and dash_group_2 ? There is nothing related to users/accounts into the dashboard editor... 

After log in as user1 I can see all dashboards !! but this is a security flaw isn't it?

![image](https://cloud.githubusercontent.com/assets/5883405/6198934/dc96d1e4-b422-11e4-9598-c4f7e445370a.png)

I'm also not be able of changing roles from users...( error shown in the picture)

![image](https://cloud.githubusercontent.com/assets/5883405/6198956/4b10b04e-b424-11e4-9084-1144ef6904de.png)

and in the log

```
2015/02/14 08:37:34 [account_users.go:33 AddAccountUser()] [E] Could not add user to account: UNIQUE constraint failed: account_user.account_id, account_user.user_id
2015/02/14 08:37:34 [I] Completed /api/account/users 500 Internal Server Error in 4.115639ms
```

Can you give me a hint on how can I administrate the dashboards visibility per users or accounts ?

**Comment by Sineos** [comment]
I just came across the same issue. Thanks for saving me to create the screen-shots ;)

Maybe my interpretation is wrong but I understand "Accounts" like user groups.

So the logical work-flow for me would be:
- As administrative user: Add Accounts
- As administrative user: Assign an Role to an Account
- As administrative user: Create Users
- As administrative user: Assign Users to given Account 
- As administrative user: Create and assign API keys to a given Account (which kind of would make  the relation between API key and Role obsolete, because it is given via the relation of Account and Role)

![v2_user_table](https://cloud.githubusercontent.com/assets/4459312/6199241/be0555d8-b437-11e4-9b1f-f4a9aba54f1f.png)
The "Admin" column in the User table could be replaced by "Role" and maybe the Account information be added

In addition this would allow a permission system between Dashboard Groups and Accounts

**Comment by Sineos** [comment]
As an additional comment: The Import function under Accounts is misplaced IMHO
As it is an administrative task, I suggest to move it to Admin and rename to "Import Dashboards"

**Comment by torkelo** [comment]
ok, so we understand that the admin, account & user model is confusing we will try to rework / refine / rename this to make it more clear. 

But as it says in the readme, Grafana 2.0 uses a multi tenant account model. Dashboards and data sources are directly linked to accounts. Users (logins) are tied to an Account via a Role. 

The admin on the sidenav is not account admin, it is "Grafana super duper admin" where you can view grafana server settings, manager user logins etc. 

Imports need to be under account because they import dashboards to the current account. Each user is linked to one or more accounts but only one can be active at a time. So you cannot see dashboards from multiple accounts at the same time in Dashboard search. User A might be a contractor for two companies, he as access two both those accounts but only one can be chosen (active) at any time. 

For single company setups with only one time series store there is only need to a single account, maybe some users are added to this account only with Viewer role, maybe some with Editor (can save and edit Dashbords), and some as Admin (can edit data sources). 

There are no user groups or permissions on individual dashboards.

**Comment by Sineos** [comment]
If I did understand you correctly the workflow would look like:

- As Super-Admin: Add Account "Company_A"
- As Super-Admin: Add Account "Company_B"
- As Super-Admin: Add User "Admin_Company_A"
- As Super-Admin: Add User "Admin_Company_B"
- As Super-Admin: Assign User "Admin_Company_A" to Account "Company_A" with the Role "Admin"
- As Super-Admin: Assign User "Admin_Company_B" to Account "Company_B" with the Role "Admin"

Now User "Admin_Company_A" logs in:
- As Admin_Company_A: Create User "Editor1" and assigns the Role "Editor"
- As Admin_Company_A: Create all other needed users

Now all actions from either "Admin_Company_A" or "Editor1" are only valid in the Account-context of "Company_A", e.g. each User created by this local admin are only valid in this account. In addition all Graphs/Dashboards created by such users are only accessible by members of this Account.

Did I understand this correctly?

**Comment by torkelo** [comment]
No it s more like, 

Grafana Admin (super admin), creates user AdminCompany_A,  and AdminCompany_B. 

Login in as AdminCompany_A and rename the account to Company_A (if single account mode is true AdminCompany_A user will be automatically be assigned Editor role for the main account, so depending on if you disabled single  account mode you might need to create an account under profile page).

Now for any user that signed up,  AdminCompany_A can now give them access in Account > Users. 

Account admins cannot create users, Users are global (can have access to multiple accounts), Account admins can create account user links (with role).

**Comment by Sineos** [comment]
Thanks for the clarification.
Personally I would have chosen an approach more like the group / users approach with permissions.

E.g. 
- Super Admins can do anything and are the only ones that can create Accounts
- Users that are created or have signed up need to be assigned to an Account, where again the Super Admin can assign to any Account and "Account Admins" can only assign to their account
- Role is always bound to the Account, since User_A can be an Editor in Account_A but only a Viewer in Account_B

This could even work for "nested accounts", which could be an interesting approach for a constellation like:

=> Grafana Cloud Instance (governed by Super Admins)
==> Company_A (with Company_A Admin)
===> Company_A Sales Deparment  (with Sales Admin)
===> Company_A Finance Department (with Finance Admin)
==> Company_B (with Company_B Admin)
===> Company_B Sales Deparment  (with Sales Admin)
===> Company_B Finance Department (with Finance Admin)

This would be a more intuitive approach IMHO but for sure I now understand the concept and respect your design decision.

**Comment by torkelo** [comment]
We will make it more intuitive and easy to understand. But the account must support a multi tenant saas setup, so we started with that (the account and user model is pretty much the same as google uses for Google analytics). 

User groups and permissions might be added in the future, but not sure what the use case if for that, need to know more. The time series stores does not have any per metric series auth so it would be only to filter the dashboards visible in search.

**Comment by torkelo** [comment]
Just read your comment again, role is always bound to an account. so a single user can be Editor for company A and viewer for company B,

**Comment by Sineos** [comment]
I have understood the Account and SAAS idea and I really appreciate it. What I wanted to point out is the workflow of managing it and I tried to bring across my idea of how it could work.

My proposal would be:
- Creating an Account is done via "Add Account" under the Account settings but only visible when logged in as Super Admin
- All existing Accounts are listed similar to the way it is done in "Data Sources" for single Data Sources
- Creating Users is also moved to Accounts and also only visible to the Super Admin
- Each Account in the listing has an Edit Button. Under this Edit Button options like renaming the Account, adding metadata (Company, Addresses, Contact Information etc) could be offered. Also a functionality is given to add Users to this account alongside with their respective role

When an "Account Admin" is logged in the menu could look the same as when the Super Admin is clicking the Edit Button in his complete listing (as mentioned above)

For me the advantage would be, that the Super-Admin can do all from his Role as Super-Admin without the need of switching the "Account context" (I think this makes the system hard to understand as of now).

Lets assume, I want to the Account Admin of Company_A:
- I "Sign Up" to create my user
- I inform my Super Admin (SA) about my new user
- The SA goes to the Account Setting and clicks Edit on Account Company_A
- The SA adds my user as Admin on this Account
- Meanwhile my "Company_A" Editor colleague has signed up as well
- I log in as Account Admin go to the Account setting and add my colleague as Editor

**Comment by toni-moreno** [comment]
Hi @torkelo and @Sineos. 

I 've been outside all weekend and I'm now  reading all  your interesting comments, thank you very much to both for that.

I will test Grafana2.0 again treating to adapt our needs to these new user mode, I will  begin to work on the workflow in  https://github.com/grafana/grafana/issues/1484#issuecomment-74420157. 

I will give you some feedback  again after

**Comment by toni-moreno** [comment]
Hi @torkelo and @Sineos , first of all, I should say that I've never worked before with google Analitics and I'm completely ignorant on this kind of multitenant user model. 

As first test I will deactivate Single Account mode in " conf/grafana.custom.ini"
```
[account.single]
enabled = false
account_name = main
default_role = Editor
[security]
disable_user_signup = true
```

# The Goal.

My goal is configure Grafana2.0 to enable 3 different users  from ( CompanyA ) with different roles.

*  AdminCompany_A
*  EditorCompany_A
*  ViewerCompany_A

Access to their 2 dashboards

* DashBoardCompany_A_1
* DashBoardCompany_A_2

And 3 different users users from CompanyB 

* AdminCompany_B
* EditorCompany_B
* ViewerCompany_B

access to their other dashboards.

* DashBoardCompany_B_1
* DashBoardCompany_B_2

To do it ,  I will try following the workflow on https://github.com/grafana/grafana/issues/1484#issuecomment-74420157

#### test 1: Create user and Login ( single account mode disabled)

1.- As Grafana Admin (super admin), I've created user AdminCompany_A, and AdminCompany_B. ( in the Admin -> Users section) 

![image](https://cloud.githubusercontent.com/assets/5883405/6208936/1f254830-b5c0-11e4-8734-4a66688cbe5c.png)

2.- I've tried to Login in as AdminCompany_A , but I can not do it.

![image](https://cloud.githubusercontent.com/assets/5883405/6211472/99f56c10-b5da-11e4-8c57-36211a9342df.png)


At this point I'm really frustrated since I'm unable to create a single user and log in as this user.

If  I  test with single Account mode.

```
[account.single]
enabled = True
account_name = main
default_role = Admin
[security]
disable_user_signup = true
```

#### test2: Create user and Login ( single account mode enabled )
 

1.- As in the previous test, as Grafana Admin (super admin), I've created user AdminCompany_A, and AdminCompany_B. ( in the Admin -> Users section).

After that , in this case appears automatically 2 new entries in the account -> users section

![image](https://cloud.githubusercontent.com/assets/5883405/6211161/81e612da-b5d7-11e4-8653-0076cfb0be67.png)

Now I will Log In as AdminCompany_A, but I can not do it again.

![image](https://cloud.githubusercontent.com/assets/5883405/6211411/bdb591bc-b5d9-11e4-9249-26cc84cb76b8.png)


As you can see I can not log In as any user different than "admin" . I won't continue with this test if I can not create users.

¿ What I'm doing wrong ?

**Comment by torkelo** [comment]
@toni-moreno strange, running into the same issue, will investigate. Thanks for reporting this!

**Comment by Sineos** [comment]
This works for me. I have created some test users and I can log in with them.

If you want to create an Admin user e.g. for Company_A you have to first add this account in the under your Super Administrator, then switch your Super Admin to this account and then add your newly created user as Admin for this account.
Using default settings here and this worked for me.

I also have verified that Data Sources and Dashboards are both unique to a given account. So even if you would like to access them as Super Admin you have to "switch Account context" before

**Comment by toni-moreno** [comment]
I'm working with last develop commit 83d798dbad046af968a878175e8451d55a2029af.

And I've updated and  rebuild  it in this way

```
cd $GOPATH/src/github.com/grafana/grafana
git pull.
go run build.go setup
godep restore
go build .
npm install
npm install -g grunt-cli
grunt
go get github.com/Unknwon/bra
bra run
```

**Comment by Sineos** [comment]
I currently run f6c07fd which is two days old and I followed the instructions in the readme including the npm steps and also use bra to run.

I just tried again following these steps:

![v2_acc1](https://cloud.githubusercontent.com/assets/4459312/6217181/86812930-b611-11e4-8a82-4e1822b8f36f.png)
- I'm logged in as Super Admin in the "main" Account
- I created the Account "another_test"
- I also created the User "another_test_user"
- Please note: I renamed the first account "main" to "Administrators". Some steps down I will point to a bug


![v2_acc2](https://cloud.githubusercontent.com/assets/4459312/6217182/86835976-b611-11e4-81f3-523066843a0c.png)
- Context for the Super Admin switched to Account "another_test"


![v2_acc3](https://cloud.githubusercontent.com/assets/4459312/6217183/8685b5c2-b611-11e4-88e5-7b761d895d0b.png)
- Within the Account-context of "another_test" I added the User "another_test_user"


![v2_acc4](https://cloud.githubusercontent.com/assets/4459312/6217184/868a60b8-b611-11e4-8603-d9e46e4b5187.png)
- Logged out as Super Admin and logged in as "another_test_user"
- Now to the bug I mentioned above: Grafana automatically added this user to the "main" Account as Editor. This account does no longer exist in my setup since I renamed it to "Administrators"

![v2_acc5](https://cloud.githubusercontent.com/assets/4459312/6217307/ea337446-b612-11e4-9adf-82282846648a.png)
- Now I have added a Sub-Account (nested account) "sub_account_of_another_test" in the Account "another_test"
- This may be a bug or by design: The Super Admin does not have access (in fact cannot even see) this nested account

**Comment by Sineos** [comment]
Just tried again with 83d798d and also here creating users, assigning to an account and logging in works for me

**Comment by torkelo** [comment]
@toni-moreno there are not nesting of accounts, you can only see accounts that you have a permission for (a role link). 

The Grafana system admin only sees accounts that he has permissions for, have not yet added system admin views for all accounts. 

@toni-moreno the reason the main account was added automatically to the new user is probably because single account mode is enabled in the config file. This option is to make it easier to handle single account setups. You can in the config file specify an account that should be automatically assigned to new users. 

```ini
[account.single]
; Enable this feature to auto assign new users to a single account, suitable for NON multi tenant setups
enabled = true
; Name of default account
account_name = main
; Default role new users will be automatically assigned
default_role = Editor
```

**Comment by toni-moreno** [comment]
@torkelo finally I could log in as AdminCompany_A and AdminCompany_B but only if done with e-mail not with username.

![image](https://cloud.githubusercontent.com/assets/5883405/6229377/328c4282-b6b7-11e4-9cae-fcba2db865e2.png)

![image](https://cloud.githubusercontent.com/assets/5883405/6229389/53ed1604-b6b7-11e4-8d6a-b44bdd43bafa.png)

I can now follow with my test at https://github.com/grafana/grafana/issues/1484#issuecomment-74498017


![image](https://cloud.githubusercontent.com/assets/5883405/6229417/9f5722f6-b6b7-11e4-854e-be93e9ec1628.png)

**Comment by Sineos** [comment]
I tried with an upper-case user name as well and it fails just like above. Lower-case user names work fine here. Maybe a misplaced "ToLower"?

**Comment by torkelo** [comment]
@Sineos @toni-moreno  Fixed the issue with login by username, you can now have uppercase letters in a username. I had a ToLower on the username, not sure why. Now the case needs to match on both email and username (which ever matches). 

Thank you both for your feedback! I have updated the docker image, will add an automatic docker image build & push to the wercker CI build (hopefully today) so the docker image is always up to date.

**Comment by toni-moreno** [comment]
After fixed this issue I've resumed the previously proposed test. 

First of all I would like to congratulate you for the great work you've done in grafana 2.0

@torkelo I will put questions or unexpected behavior or errors I've detected in bold letters, while doing the test, and at the end a conclusion section with some more questions.

### The chosen config

 I will deactivate Single Account mode in " conf/grafana.custom.ini"
```
[account.single]
enabled = false
account_name = main
default_role = Editor
[security]
disable_user_signup = true
```

### The Goal.

I would like remember everybody that my goal is configure Grafana2.0 to enable 3 different users  from ( Company_A ) with different roles.

*  AdminCompany_A
*  EditorCompany_A
*  ViewerCompany_A

Access to their 2 dashboards

* DashBoardCompany_A_1
* DashBoardCompany_A_2

And 3 different users users from Company_B 

* AdminCompany_B
* EditorCompany_B
* ViewerCompany_B

access to their other dashboards.

* DashBoardCompany_B_1
* DashBoardCompany_B_2


### Test 1:  Accounts and Users administration ( as Super Admin )

To do that I've done the following  .

1. Log in  as Super Admin User (admin)

2. Create 2 accounts that will act as a kind of "group"  in the "admin" profile 

* Account: Company_A
* Account: Company_B

![image](https://cloud.githubusercontent.com/assets/5883405/6247549/1471aad4-b776-11e4-8386-3cd246084094.png)

Now Admin will have  2  accounts where to add users.

![image](https://cloud.githubusercontent.com/assets/5883405/6247575/62fa4d64-b776-11e4-963a-d9366724ff46.png)

__* questions: there is no way to modify/delete this accounts after created ?__

3. Create users.

At this point we will be able to  create all Users ( with no associated account yet) with the admin -> Users -> Create User Form.

![image](https://cloud.githubusercontent.com/assets/5883405/6247691/bd64807a-b777-11e4-867a-f8f8a95e844c.png)


4. Assign users to their company

Change current Account to "Company_A" 

![image](https://cloud.githubusercontent.com/assets/5883405/6247711/01b49a94-b778-11e4-8431-a215809ed320.png)

__* question: there is any way to see anywhere in the screen wich is the active account ?__

Assign users from Company_A to  current Account in the Account -> Users Form

![image](https://cloud.githubusercontent.com/assets/5883405/6247770/b106ae38-b778-11e4-866e-5d21d2fa2d32.png)

Now I have all Company_A users assigned

![image](https://cloud.githubusercontent.com/assets/5883405/6247780/d3a16532-b778-11e4-93d8-d57847cb97c6.png)

In the same way I've switched to "Company_B" account and assigned all Company_B users to active account.

###  Test 2: Log in and Work as Admin Role 

1.- Log in as AdminCompany_A

After log in we can see 2 Accounts assigned to this user we should switch to Company_A previous to any administrative task

![image](https://cloud.githubusercontent.com/assets/5883405/6247976/06ddd3b6-b77b-11e4-8814-81a26965c0b5.png)

__* question:  there is any way to avoid this "phantom" account that I don't need and as Super Admin I've not created ?__
__* question:  there is any way to select the "default" account when a user has more than one  to avoid always switch from the "phantom" account to the selected ?__

After switch account we can work for Company_A account.

![image](https://cloud.githubusercontent.com/assets/5883405/6248101/2a21054a-b77c-11e4-9665-9394c59fde63.png)

2.- Create Resources for Company_A

First Datasource and dashboards for Company_A 

![image](https://cloud.githubusercontent.com/assets/5883405/6248151/c456d61c-b77c-11e4-9645-aae5b563c0f2.png)

![image](https://cloud.githubusercontent.com/assets/5883405/6248215/73e28720-b77d-11e4-9965-b1d6b93ecba1.png)


After that we will try to create a dashboard from this datasource but this not appears in the datasource selector.

![image](https://cloud.githubusercontent.com/assets/5883405/6248196/4a263b84-b77d-11e4-9898-9b9c83c9c4f5.png)

__* question: why can not see the previously created datasource?__

I've had to log out and log in again to see the previous created datasource, at this point we will create a test dashboard

![image](https://cloud.githubusercontent.com/assets/5883405/6248383/58a4c5f2-b77f-11e4-8cf3-1e6b96818b3c.png)

### Test 3: Log in and Working as Editor Role

1. After log in no dashboards can be selected because of the current Account is not "Company_A" yet, this is a undesired behavior. 

But most surprising thing is __this "Editor" user is Also "ADMIN" of his "phantom" Account__ and can himself:
- create Accounts
- create datasources
- Assign users to his previously created accounts.

![image](https://cloud.githubusercontent.com/assets/5883405/6248523/cc49fce2-b780-11e4-87f1-94259484f901.png)

From the Administrative point of view it can be a security flaw, as a Super Admin I don't want let users create their own dashboards from not controlled datasources

__* question: how can avoid any user to be admin of his own "phantom" account?__
__* question: how can avoid any user can create other accounts?__

After switch the active account to Company_A I can edit dashboards as well as Admin and this is OK

### Test 4: Log in and Work as Viewer Role

As the previous one, the Viewer is also "Admin" of an "phantom"  account, after switch to "Company_A"  , I can see Dashboards from Company_A

I will try to edit And as you can see I can do it !!
I can add metrics, change title, view datasources, and view other metrics, and the only thing is it can not save the current dashboard, but in the meanwhile he can see other non desired metrics!!

![image](https://cloud.githubusercontent.com/assets/5883405/6248724/cf36b8d0-b782-11e4-8e95-66fbe6d57e92.png)

![image](https://cloud.githubusercontent.com/assets/5883405/6248868/70aeec32-b783-11e4-9741-3818db9ee557.png)

__* question: how can avoid a viewer can change graphs or view other metrics?__


1.- About user Administration model.

I have been able to create a kind of "group" with the account model , and It seems that we  can use Grafana 2.0 for our purposes. But there is some "security" things that I suggest to consider (all in previous questions ).

3.- About usability

Another thing to discuss is how can I share  resources among accounts. ( where resources could be both datasources/ dashboards), If I understood , resources are created per account, and only usable/visible under this account.

In our case, we have designed  dashboards for certain products ( Linux, Windows, Apache , WebLogic, WebSphere, Oracle, mysql  , etc) these products are independent of any company ( or group) .

If I have 400 accounts , should I import 400 dashboards for all products to all accounts ?, what happens If I should modify one product Dashboard ? should I do it 400 times , one for each account ?

**Comment by torkelo** [comment]
@toni-moreno thanks, great feedback. 

I have fixed the issue where you have to reload the page (or login/logout) before being able to use a datasource. 

Test 1)
We will try to find a way to show which account is active. 

Test 3)
When account mode single is disabled a new user automatically gets its own account (and is made admin for this account). I agree that there should be an option to disable this. 

Do you have separate graphite servers for your different companies? Remember that the account model is not really designed for access/permissions groups for dashboards within one organisation. Within one organisation you can use account roles (Admin, Editor, Viewer) to control user permissions. Neither Graphite nor InfluxDB or OpenTSDB has permissions on a per series basis so neither have Grafana. A user with an account role Viewer can view all metrics exposed via Graphite. The only thing that is locked is creating/updating dashbords and adding/modifying data sources. 

2.- About usability)
If you have 400 accounts with the same dashboard? Why have 400 accounts. Again accounts are not designed to create user groups, they are designed for distinct organizations (with different data sources, etc). 

User groups and permissions could be added to filter down dashboards in the search, and so you are only allowed to modify dashboards within your group. But felt that this not top prio as none of the big SaaS solutions for metrics (librato, datadog etc) have user group permissions.

**Comment by toni-moreno** [comment]
Hi @torkelo . 

In my organization we are divided by group of people who works over the same group of servers , as an example ( sales_group, financial_group, intranet_group,  security_group),   and we have several graphite servers each one with metrics from one or more servers groups.

all metrics names begins by their group name.

by example:

```` 
sales.datacenter1.databases.salesserver24.oracle1.db_time
sales.datacenter1.webservers.salesserver25.apache_sales.hits
security.datacenter2.webservers.secserver123.apache_sales.hits
````

We have designed common dashboards for everybody  ( product based dashboards as I explained before). 

But each group has  also their own metrics: by example:  sales, stocks, money , detected intrusions, and a lot of other measurable things.

In this context , we need shared dashboards That a "Super Editor Admin" could modify for everybody  and each group could have their own dashboards. 

It is mandatory that each group can only access to their own and shared dashboards ( previously assigned by a super Admin)  and could be interesting/desirable each group has something like a metric name filter ( assigned by the super super admin  also) , by example:

````
sales_group  "^sales\."
financial_group  "^financial\."
intranet_group  "^intranet\."
````

About sizing (aprox):

* 50 different products aprox
* 1000 users
* 500 groups
* At least 2 o 3 dashboard per group + shared dashboards.

I would like to use accounts as "groups" but I don't like the idea of replicate shared dashboards and shared datasources to each account  on each dashboard modification.

How can do it?

**Comment by torkelo** [comment]
Well sharing dashboards and metric data between account is not going to be in Grafana 2.0, maybe not even 2.1. 

I would like to keep the account and user model as simple as possible to begin with.

**Comment by Sineos** [comment]
Would it be possible to this via the CLI?
I could imagine with two simple hash list of data sources vs. account and users vs. account. This would even tremendously ease up things in case of updates.

**Comment by toni-moreno** [comment]
@torkelo 

regarding this sizing , could be interesting super super admin could list (and export perhaps as CSV, excel ) a complete table with all user / accounts pairs and if are active or not :
```
TABLE 1 {
varchar user_id
varchar account_id
boolean current_active
}
```
And resources also
```` 
TABLE2 {
varchar dashboard_id
varchar accout_id
}
TABLE {
varchar datasource_id
varchar accout_id
}
````

In this way could be easy review all configurations from "super super admin" account

**Comment by torkelo** [comment]
@toni-moreno yes, could be an extensions to the existing CLI commands (https://github.com/grafana/grafana/pull/1486) 

Oh, and regarding your idea for permissions on a per metric / series basis. This does not really work. It has to be done in Graphite. 

Let say user is a Viewer in an Grafana account with a Graphite datasource, this datasource has these restrictions: 
```
sales_group  "^sales\."
financial_group  "^financial\."
intranet_group  "^intranet\."
```

A query like `alias(*.server1.logins.count, 'logins)`  will get metrics outside those restrictions without Grafana ever having the chance to impose those restrictions. So there is very little likelihood that those level of security features is going to be added to the Grafana & Graphite integration unless some new features is added to Graphite. 

For now all Viewers will be able to view all metrics exposed by a datasource.

**Comment by toni-moreno** [comment]
Indeed a kind of "flexible" metric Filtering could be done : 

Consider the following use case:

As Editor  user I have defined my metrics names with templated variables.

````
aliasByMetric($group.$production_mode.$datacenter.$site.$host.system.cpu.percent-user)
````

And we have defined in my dashboard the following variables

![image](https://cloud.githubusercontent.com/assets/5883405/6267447/56e74db4-b844-11e4-8a4c-5ad55e520e5f.png)

could be possible (as a new feature) to add a metric filter per account if you can add a filter in the variable editor ( as in the next picture).

![image](https://cloud.githubusercontent.com/assets/5883405/6267533/1d3533aa-b845-11e4-9fe0-209f7832de88.png)

but instead of adding a static Filter we can add a variable filter.( as in the next picture)

![image](https://cloud.githubusercontent.com/assets/5883405/6267587/8976026a-b845-11e4-9d09-1d0b009601b2.png)

And ( as new feature) we could define variables per account ( as in the next picture )

![image](https://cloud.githubusercontent.com/assets/5883405/6267738/029a7e4a-b847-11e4-8e86-0026b580f4ab.png)

As viewer user , you won't be able to change variables or filters and you won't be able to see other values in group variable than those whose begin with "^sales\.".

These two new features are not really a "security" feature but can help a lot on sharing dashboards , and give us flexible way to filter metrics per account

**Comment by torkelo** [comment]
@toni-moreno interesting idea, but it would only work for variable values, not for metrics. A query like 
`alias(*.server1.logins.count, 'logins')` would still circumvent any filter.

**Comment by toni-moreno** [comment]
@torkelo I agree.

But Admins and Editors are responsible on build a good  dashboard design which  to allow us metric filters. 

Administrators and Editors can "restrict" metrics to viewers, with these two new features  .
With these two new features Admin and Editors can "restrict" metrics to viewers.

**Comment by torkelo** [comment]
@toni-moreno it will only be a very limited restriction, like for what is visible options in variables etc. And probably inventive ways to work around the restriction. Anyway, I am sorry, it is not something that will be implemented in Grafana anytime soon, unless graphite implements some feature like this. Or if there is a a huge demand for weak (ie not for security) filtering like this.

**Comment by torkelo** [comment]
There has been some big updates that relates to this, 

Account has been renamed to Organization, and you can now see your active organization and switch between orgs in the sidebar. 

![image](https://cloud.githubusercontent.com/assets/10999/6446567/3a2a1e60-c10c-11e4-88e9-ff7e689da4d5.png)

The Grafana server admin views (with global user admin etc) has gotten its own sidenav to make it more clear that you are now in doing global server administration. 

![image](https://cloud.githubusercontent.com/assets/10999/6446599/716bd9a4-c10c-11e4-84e5-6e8ebf4b2de3.png)

**Comment by systems1** [comment]
if there are multiple users who have admin/editor access 
where are the updates to graphs/dashboards saved 
could be email account or ldap login (linux server)

**Comment by torkelo** [comment]
@systems1 what do you mean? 

| "where are the updates to graphs/dashboards saved"

Dashboards are saved in the Grafana database

**Comment by ashu-rawat** [comment]
Hi torkelo,

I am still looking out for this functionality of having dashboard level user restrictions. Right now, when i am creating a new dashboarding and populating the data from influx. It's being visible to all the users instantly. I wanted to have some restriction on dashboards, So when everything is ready. i can make it visible to selected users.

Please suggest if there is any solution for it.
