### ISSUE TITLE
Long time to load list of Dashboards

### ISSUE THREAD

**Issue by podkolzzzin** [grafana/grafana#14840]
We have lots of long SQL queries on the main grafana dashboard.
The problem is that we can't view the list of available dashboards until all sql queries will be executed. So we have to wait around 20minutes while everything will be executed, to view the list of dashboards.
As I understand data about dashboards is stored in grafana's local database which is completely different from DataSource, so queries to it can be executed independently.

Please include this information:
Grafana v5.2.4 (commit: 0bbac5c) 
Pg Data Source
Ubuntu

**Comment by torkelo** [comment]
it's related to max number of requests to the same server, a browser limitation:

closing this as we have an issue to track this problem already:
https://github.com/grafana/grafana/issues/5361
