### ISSUE TITLE
Error 500 on unexisting /api/alert-notification/<id>

### ISSUE THREAD

**Issue by szkopinskig** [grafana/grafana#14841]
### What Grafana version are you using?
Grafana v5.4.2

### What datasource are you using?
N/A

### What OS are you running grafana on?
Debian GNU/Linux 9 (stretch)

### What did you do?
get on /api/alert-notifications/3 to request alert-notification 3

### What was the expected result?
This alert-notification ID doesn't exist, so Error 404

### What happened instead?
Error 500 :
 lvl=eror msg="Request error" logger=context userId=0 orgId=1 uname= error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:513 (0x434ed8)\n/usr/local/go/src/runtime/panic.go:82 (0x43402d)\n/usr/local/go/src/runtime/signal_unix.go:390 (0x44adc1)\n/go/src/github.com/grafana/grafana/pkg/api/dtos/alerting.go:58 (0xee8406)\n/go/src/github.com/grafana/grafana/pkg/api/alerting.go:215 (0xf535a6)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x814a73)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8143d9)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0xf97ffd)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x814a73)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8143d9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x830600)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x83051e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xb2b2fc)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x814a73)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8143d9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x830600)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x83051e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xb2ac17)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x814a73)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8143d9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x830600)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x83051e)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:15 (0xb2b601)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x814a73)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8143d9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x830600)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x83051e)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 (0xb2ab30)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x8304a0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x814760)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x8144cb)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x830600)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x83051e)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xb2849d)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x814a73)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8143d9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x830600)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x840d44)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x83b54e)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x834ac1)\n/usr/local/go/src/net/http/server.go:2741 (0x6b124a)\n/usr/local/go/src/net/http/server.go:1847 (0x6ad605)\n/usr/local/go/src/runtime/asm_amd64.s:1333 (0x465220)\n"

lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/alert-notifications/3 status=500

**Comment by daniellee** [comment]
Confirmed. Thanks for reporting this.
