### ISSUE TITLE
Failed to start docker container: exec user process caused "permission denied"

### ISSUE THREAD

**Issue by leikao** [grafana/grafana#14854]
### What Grafana version are you using?
Latest version, the mater branch.

### What OS are you running grafana on?
Fedora

### What did you do?
Git clone grafana's latest code from github, then `sudo make build-docker-dev` to build a docker image.
When running the docker image I got the following error:

>     $ docker run -it -p 3000:3000 grafana/grafana:dev 
>     standard_init_linux.go:207: exec user process caused "permission denied"

File permision details:
>     $ docker run -it --user root --entrypoint sh grafana/grafana:dev 
>     # ls -l /run.sh
>     -rwxr-x---. 1 root root 3350 Jan 13 14:57 /run.sh

**Comment by daniellee** [comment]
Why did you use sudo when running `make build-docker-dev`? If you try building it without sudo does it work?

Also, if you are looking to make a custom docker image then maybe [this on the docs site](http://docs.grafana.org/installation/docker/#building-a-custom-grafana-image-with-pre-installed-plugins) will be useful.

**Comment by leikao** [comment]
I found the root cause, the file-creation mask (aka *umask*) in my build environment is **`077`**, so the file mode of `packaging/docker/run.sh` is `-rwx------.` after I git clone it from the repo. The file mode in docker image inherited from my build environment.

### HOWTO fix it?
Change the file bit mode of `packaging/docker/run.sh`, then build and run docker image again.
There may be more faults if the file mode is incorrect, *grafana* user in docker container may has no permission to access to `/etc/grafana` also. So I suggest to change umask to *022* temporarily, git clone the code from repo, then build and run again.

> Why did you use sudo when running make build-docker-dev? If you try building it without sudo does it work? It worked without sudo for me running on Ubuntu.

I MUST run it with `sudo`, because I have no permission to access docker files (such as /var/run/docker.sock and /var/lib/docker/...). Surly I can run it without sudo (run as root user or add my account to *docker* user group), but the same error finally.

**Comment by torkelo** [comment]
not sure this an issue that we need to solve. Maybe if more encounter it.

**Comment by kshitijyad** [comment]
I seem to have the exact same issue

**Comment by drinkcor** [comment]
meet the same question in docker start docker-mysql: standard_init_linux.go:228: exec user process caused: permission denied
