### ISSUE TITLE
All the panels can't update each time but just updated once per day 

### ISSUE THREAD

**Issue by fkhodamoradi** [grafana/grafana#14858]
Hi guys, all of the panels in all dashboard just updated once per day (for example 2019-1-14 3:30:000) but I want to see the latest updated panels:

Grafana version: 5.3.2
data source: Postgresql
OS: Ubuntu 16 

<img width="1604" alt="screen shot 2019-01-14 at 11 58 58 am" src="https://user-images.githubusercontent.com/14139012/51102341-d506df80-17f3-11e9-8803-6c16574bdc13.png">

and when I set the time to today the panel just show me the data until 3:30:00

<img width="1639" alt="screen shot 2019-01-14 at 11 59 51 am" src="https://user-images.githubusercontent.com/14139012/51102395-05e71480-17f4-11e9-9b56-f76b7f964ae3.png">

**Comment by marefr** [comment]
Would need more details here. Please include the query you're using and use the query inspector and include the request/response.

**Comment by fkhodamoradi** [comment]
@marefr 
`SELECT
  count(*) as count,
  created_at::Date as time,
  'All' as metric
FROM
  users
WHERE
  status != 'signup'
  AND
  $__timeFilter(created_at)
GROUP BY time
ORDER BY time`

**Comment by marefr** [comment]
@fkhodamoradi please use query inspector and include request/response, see [how to](https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630). 

You probably have some timezone issue. If `created_at` are stored with proper date time type the timezone conversion should happen automatically and give you correct result.

**Comment by torkelo** [comment]
closing this, as this does not look like a bug
