### ISSUE TITLE
[Feature request] Allow passing variables to SimpleJSON request

### ISSUE THREAD

**Issue by denisidoro** [grafana/grafana#14850]
As of now, when adding a query, we can only select between timeserie/table + a tag-value.
It would be nice to send more variables as well, per query. Passing a JSON would suffice.
Please note that ad-hoc variables apply to the whole dashboard, not a single query inside a single panel.
In particular, I've created a query variable but apparently there's no way to use it in a SimpleJSON request.

**Comment by denisidoro** [comment]
As a workaround, I'm sending a JSON as a tag-value and handling it accordingly in the backend. It's not elegant but I managed to implement what I had in mind

Feel free to close the issue if it makes sense

**Comment by daniellee** [comment]
There is a community fork of the SimpleJSON plugin that adds some more advanced features (and plans to add more):

https://grafana.com/plugins/simpod-json-datasource
