### ISSUE TITLE
Loki data for existing dashboard panels

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14860]
Loki data is currently only available in Explore. We should make it available for existing dashboard panel types.
This issue aims to derive numbers or timeseries from log lines, to be displayed in existing panel types. There is a separate issue to develop a new panel type that shows the actual log lines: #14576.

So far, the datasource only returns a logs model, while the dashboard panels require either a time series or a table model. Here is a rough list of what is needed:

- Before Loki can be used for dashboard panels, it needs a query controller for the Loki plugin
- The query controller needs to render a query field, and a result format dropdown (optional: a limit field to limit responses)
- The datasource query function needs to be extended to return other models (timeseries, table) based on the `format` option
- The logs model has some logic already that turns a logs model into a timeseries, that can be reused

See influx or Prometheus datasources on how results are transformed to other models.

TODO:
* [x]  Basic query editor (same as in explore)
* [x]  Time series resultFormat is working 
* [ ]  Figure out how to get query errors to query editor
* [ ] Support table format
* [ ] Toggle to not group by level so query can always return single series (total)

**Comment by torkelo** [comment]
Speaking to @tomwilkie today and Loki is not ready for dashboards type of queries it seems to we are putting this on hold and should add placeholder query editor with message saying loki is not supported in dashboards yet.

**Comment by prg3** [comment]
Speaking with @davkal on Slack today so adding a use case here:

I want to have a dashboard for the various clusters I run with some canned queries so that the end users do not need to know or understand the underlying Loki queries. This is what we already do with graphs, so it would be very handy to give them a "tail -f" on various applications or containers. Of course with variables and selections.

**Comment by davkal** [comment]
> This is what we already do with graphs, so it would be very handy to give them a "tail -f" on various applications or containers. Of course with variables and selections.

This should be in #14576, moving this there.

**Comment by yutakatay** [comment]
ref: https://github.com/grafana/loki/issues/340#issuecomment-516007720

**Comment by aocenas** [comment]
@davkal with this #18709 merged I think some of the TODOs can be checked thought not exactly sure that I understand them.
> Support table format

At least this I assume can be checked as you can show logs in table panel now.

In general Loki is available with all panels now, but most won't show anything because there is not transform for time series format.

**Comment by davkal** [comment]
I've tried adding a table viz to a Loki query and it worked. I'd consider this done now. 
We should wait for community feedback to see if e.g., single stat or line graphs make sense as viz for a loki query result (log lines).

**Comment by aocenas** [comment]
> We should wait for community feedback to see if e.g., single stat or line graphs make sense as viz for a loki query result (log lines).

I think the grand plan here is to eventually use the transformations in some way so you could transform the logs into counts for example and show that in any visualisation.

**Comment by Rayyis** [comment]
I tried a panel with table visualization and Loki data source, very nice!
I couldn't find a way to make it respect the selected timeframe though.

**Comment by aocenas** [comment]
Hey @Rayyis, thanks for trying this out already. Can you elaborate a bit about the problem? I tried just now and it seems to correctly show only the logs for the associate time range:
<img width="925" alt="Screenshot 2019-09-09 at 18 00 46" src="https://user-images.githubusercontent.com/1014802/64547019-08225400-d32c-11e9-81ef-4a567379c90d.png">

Maybe one thing to not is that there is still max number of lines setting in Loki datasource config that is applied here so by default it will only give you 1000 lines same as explore right now.

Also if you toggle the Live option the logs will be live whatever you set in the dashboard time range (we will need to work on a better UI for this).

**Comment by Rayyis** [comment]
It showed all logs regardless of the selected time range when I tested it the first time. But you're right I tested it just now and it works.
I know I'm not giving you much to work with so pay no attention to this. Thanks for the response!

**Comment by bonovoxly** [comment]
> > We should wait for community feedback to see if e.g., single stat or line graphs make sense as viz for a loki query result (log lines).
> 
> I think the grand plan here is to eventually use the transformations in some way so you could transform the logs into counts for example and show that in any visualisation.

This is a killer feature and I'm pretty excited at the thought of it. Being able to graph a specific log event (count/sum!) on the same graph as some other metric, be it CPU spike, event (HTTP status!)...

My goodness that's a pretty intriguing setup.
