### ISSUE TITLE
Cannot modifiy dashboard name

### ISSUE THREAD

**Issue by TonyFrancis** [grafana/grafana#1487]
I cannot find field to modify dashboard name. I was trying to create similar dashboard

**Comment by torkelo** [comment]
Its under dashboard settings, in the first Tab, there is a field "Title"

**Comment by torkelo** [comment]
Or you can use the save dropdown and change the title there before saving

**Comment by TonyFrancis** [comment]
is this in grafana 2.0

with regards
*Tony*
