### ISSUE TITLE
[Bug] faulty large time range drawing 

### ISSUE THREAD

**Issue by ASAP842** [grafana/grafana#14889]
Hey guys, I think I've ran into a bug when the time range is a few hundred years...

### What Grafana version are you using? 
Grafana v5.4.2 (d812109)

### What datasource are you using? 
MSSQL 2012

### What OS are you running grafana on?
Ubuntu 16.4

### What did you do?
Using a workaround (feature request: #7158) to customize the x-axis, so it's easier for our users to read the days off the timeline.

### What was the expected result?
It should draw correctly, no matter what time range is present.

### What happened instead?
The graph glitches badly - like an overflow problem:
![grafana bug](https://user-images.githubusercontent.com/46710082/51176461-39da3c80-18bd-11e9-8789-d233f9ca135e.PNG)

I've included a [sample.json](https://github.com/grafana/grafana/files/2759334/grafana.bug.txt).

Hope this helps!

**Comment by marefr** [comment]
May be an issue with epochs before 1970? Can you please use the query inspector and include the full request/response here? Thanks

**Comment by ASAP842** [comment]
> May be an issue with epochs before 1970? Can you please use the query inspector and include the full request/response here? Thanks

Here's the query inspector output - negative numbers starting at array index 53...

[QueryInspectorOutput.txt](https://github.com/grafana/grafana/files/2760367/QueryInspectorOutput.txt)

**Comment by marefr** [comment]
The data are returned out of order, starting point at year 2000, then eventually year 2260, then year 1680 and lastly year 1915. Seems like the data are ordered by value from 0 to 100. Don't quite understand what your query does, do you have a database table called nums as well? If you execute the query in management studio what is the result? If you manage to return the time from 1680, then 1915, then 2000 and last 2260.

**Comment by ASAP842** [comment]
I just picked this up as an example; our use-case would include a range from about 150 to 400 days. 

The query I've included here, will only generate numbers from 0 to 100 and these get added as years to '2000-01-01'. 
And since MSSQL Server does not like more than 100 recursive calls for that and I wasn't particularly fond of abusing system tables, I had to come up with a way to just scale it up a bit - hence the nums.value * [x] within the DATEADD function.

The query output in datagrip/SQLManagement Studio deliver the expected results.
So I've just tried the same with PostgreSQL - with literally the same outcome.

Here's the adjusted query I've used on our pg database: 
`WITH nums AS (SELECT generate_series(0, 100) as value)
SELECT '2000-01-01'::date + interval '1y' * (nums.value * 5) as time,
       'foobar' as metric,
       nums.value as value
FROM nums
ORDER BY time;`

Hope this helps!

**Comment by torkelo** [comment]
Make sure you order by time asc

**Comment by ASAP842** [comment]
> Make sure you order by time asc

I've just added the default mode "asc" to the PG-query, which was already included in my MSSQL sample.

The problem persists, so please reopen the ticket.

**Comment by torkelo** [comment]
Maybe something else in your query that makes time ordering not to work? Somehow your query returns datapoints out of order

**Comment by ASAP842** [comment]
Hi, I've already checked that multiple times - the order is correct.
For the example all I do is generate 100 5y intervals on the fly (to work around mssql server's 100 recursive calls limitation).

And since it's a lot easier to do in PostgreSQL, I've just fiddled around and found out that 263 (1y intervals) is the number where it starts behaving weirdly.

If I crank it up even higher, let's say 2000 then this happens:
![image](https://user-images.githubusercontent.com/46710082/51266926-cf102a80-19bc-11e9-9076-d50b43dfd88c.png)

**Comment by torkelo** [comment]
It seems like sql cannot sort the result correctly with this style of query

**Comment by ASAP842** [comment]
But then, wouldn't SQLManagement Studio or datagrip also provide me with some weird output? 

That's just not happening, so my bet is still on some weird integer/double overflow...

**Comment by torkelo** [comment]
Yes, you cannot have dates before 1970

**Comment by torkelo** [comment]
Not sure what the max date is for millisecond epochs

**Comment by ASAP842** [comment]
Hmm, according to that, it should be plenty:
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.1

On the other hand I just found out there might be a year 2038 bug - for 32 bit integer dates; 
but then 2200 is also out of range there and working...

Might be a combined issue... integer cast to double, double gets the overflow

**Comment by ASAP842** [comment]
Well that's expected when you use the query inspectors output - but it's output is absolutely wrong.

So I fiddled around and extracted the epoch from 6 dates - each 100 years apart, using 3 different queries - using only bigints as time.
![image](https://user-images.githubusercontent.com/46710082/51316516-34175f00-1a55-11e9-8b55-0ba3fc913d8a.png)

With these results:
![image](https://user-images.githubusercontent.com/46710082/51316587-61640d00-1a55-11e9-9127-5f64bfbc5126.png)

And here are the queries:
`
WITH nums AS (SELECT generate_series(0, 5) as value)

SELECT extract(epoch from ('2000-01-01'::timestamp + interval '100y' * (nums.value))) as "time",
       nums.value as value
FROM nums
ORDER BY "time" ASC;
`

Here I only extracted stuff directly, as you did in your union all query:
`
SELECT EXTRACT(epoch FROM TIMESTAMP '2000-01-01') as "time", 0 as value UNION ALL
SELECT EXTRACT(epoch FROM TIMESTAMP '2100-01-01') as "time", 1 as value UNION ALL
SELECT EXTRACT(epoch FROM TIMESTAMP '2200-01-01') as "time", 2 as value UNION ALL
SELECT EXTRACT(epoch FROM TIMESTAMP '2300-01-01') as "time", 3 as value UNION ALL
SELECT EXTRACT(epoch FROM TIMESTAMP '2400-01-01') as "time", 4 as value UNION ALL
SELECT EXTRACT(epoch FROM TIMESTAMP '2500-01-01') as "time", 5 as value
ORDER BY "time" ASC;
`

For the 3rd query I actually used Query 2's DataGrip output:
![image](https://user-images.githubusercontent.com/46710082/51316652-9bcdaa00-1a55-11e9-972b-d4232db0148a.png)

`
SELECT 946684800 as "time", 0 as value UNION ALL
SELECT 4102444800 as "time", 1 as value UNION ALL
SELECT 7258118400 as "time", 2 as value UNION ALL
SELECT 10413792000 as "time", 3 as value UNION ALL
SELECT 13569465600 as "time", 4 as value UNION ALL
SELECT 16725225600 as "time", 5 as value
ORDER BY "time" ASC;
`

So, just to be sure, I compared query 2+3 in DataGrip - the same output. 
But compare those numbers with the points the QueryInspector delivers - index 1 + 2 are totally out of whack - 3 extra digits - how!?

**Comment by marefr** [comment]
You'll need to multiply epoch with 1000 to get epoch milliseconds:

![image](https://user-images.githubusercontent.com/1668778/51318221-fd901300-1a59-11e9-9cf2-9c0836611fa5.png)

**Comment by ASAP842** [comment]
Ok, I get the idea of calculating milliseconds from seconds, but what I don't get is why the output was multiplied at 1+2 only?

And also what I'm still trying to wrap my head around - why is it I cannot use the timestamps directly, but instead have to resort to that hacky extract epoch * 1000 approach?

**Comment by marefr** [comment]
Probably due to [this code](https://github.com/grafana/grafana/blob/master/pkg/tsdb/time_range.go#L116-L129), i.e. it only handles seconds to millisecond conversion when there are values made up of 10 numbers.

**Comment by ASAP842** [comment]
Good to know, I'm just not sure if that's a good way to do it - or if it's even needed at all... ;)

Anyway thanks a bunch for helping out - with this workaround I can even draw up years starting at 0001-01-01!
