### ISSUE TITLE
prevent saving dashboards that are not editable. instead offer to clone the dashboard

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#1488]
Dashboards can be configured with 'editable=false' which prevents rows being added.  However i feel that this option should prevent users from being able to commit changes to the dashboard.

I suggest that we extend the save() function to prompt the user to 'clone' a dashboard when it is marked with 'editable=false'.  The new copy of the dashboard should have the 'editable' attribute reset to true.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/6245024/9befa662-b75a-11e4-9ea2-07900f281a17.png)

![image](https://cloud.githubusercontent.com/assets/10999/6245044/bb9460a2-b75a-11e4-87a4-af96e6c32b1f.png)

The only thing I am not sure about is if this feature should be named "Clone dashboard" or "Save as" or "Save copy as"
