### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by JsBergbau** [grafana/grafana#14895]
I've followed this http://docs.grafana.org/project/building_from_source/ docs and building for Linux.
Works till step
[quote]Build the Frontend Assets

For this you need nodejs (v.6+).

npm install -g yarn
yarn install --pure-lockfile
yarn watch
[/quote]
I've done sudo apt install yarn
Then `~/grafana/src/github.com/grafana/grafana $ yarn install --pure-lockfile`
gives
`yarn: error: no such option: --pure-lockfile`
Somewhere I've read --pure-lockfile is old and not needed anymore, so I've left this option away
`~/grafana/src/github.com/grafana/grafana $ yarn install`
gives
`ERROR: [Errno 2] No such file or directory: 'install'`
Running grafana and Entering login Page gives
`html/template: "index" is undefined`
Somewhere I've read this is because front end is not build and thats where I'm stuck now.

**Comment by torkelo** [comment]
install yarn via "npm install -g yarn"

**Comment by JsBergbau** [comment]
I've done, but no success

`sudo npm install -g yarn
(node:425) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
yarn@1.13.0 /usr/local/lib/node_modules/yarn
`

`/grafana/src/github.com/grafana/grafana $ which yarn
/usr/local/bin/yarn
`

`/grafana/src/github.com/grafana/grafana $ yarn install --pure-lockfile
Usage: yarn [options]

yarn: error: no such option: --pure-lockfile
`

**Comment by torkelo** [comment]
What version of node are you using ?
