### ISSUE TITLE
Convert string to integer

### ISSUE THREAD

**Issue by Meruem94** [grafana/grafana#14891]
Hi,

I use Influxdb database. I want to know if it's possible to convert specific string to integer in grafana graph.

For exemple I need to know the status of my Apache server. In my influxdb database, we have for exemple "Apache service  is working" or "Apache service is inactive". The first data will return 1 and the last data will return 0. And with that I can make a graph.

How I can obtain this result ?

Regards

Regards

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

See https://github.com/influxdata/influxdb/issues/2911. If Influx query language support it you can use it in Grafana even though you may need to use the raw query mode.
