### ISSUE TITLE
Build image v5.4.3 for docker

### ISSUE THREAD

**Issue by Krisfanfan** [grafana/grafana#14901]
Hi, Could someone help to build images v5.4.3 for docker. We need this version docker image to make sure that the goLang version is the latest 1.11.4. 
I tried `docker pull grafana/grafana:v5.4.3` with the response 
 `Error response from daemon: manifest for grafana/grafana:v5.4.3 not found`
From download page https://grafana.com/grafana/download?platform=docker, seems the latest version is v5.4.2

**Comment by SamuelToh** [comment]
`v5.4.3` was only released yesterday which could explain why the image was not uploaded to`docker-hub` yet.

You should be able to build the image yourself by checking out the 5.4.x branch then run the [build script](https://github.com/grafana/grafana/tree/master/packaging/docker).

**Comment by Krisfanfan** [comment]
@SamuelToh Thanks for your quick response,  do you have any plan to upload the image `v5.4.3` to `docker-hub` in this month.

**Comment by SamuelToh** [comment]
@Krisfanfan I don't work for Grafana Labs so I don't have an answer. 

However I suspect it should be available pretty soon since , shouldn't have to wait till the end of month.

**Comment by Krisfanfan** [comment]
@SamuelToh Thanks a lot. Have a good day
