### ISSUE TITLE
Escape issue when trying to select value for series

### ISSUE THREAD

**Issue by kenzodeluxe** [grafana/grafana#1490]
When trying to select values from series that contain a / in the name, it appears escaping is wrong. An example request looks as follows:
http://example.com:8086/db/database/series?p=abc123&q=select+*+from+%2Fsomeseries%2F1.2.3.4%2F+limit+1&u=someone
which results in 
syntax error, unexpected TABLE_NAME, expecting $end
select * from /someseries/1.2.3.4/ limit 1
                                    ^^^^^^^^^^^^^

When changing 
(b="/"+b+"/"),this._seriesQuery("select * from "+b+" limit 1")
to
(b="\""+b+"\""),this._seriesQuery("select * from "+b+" limit 1")
in app.js it works as expected.

**Comment by torkelo** [comment]
This is fixed in master :)
https://github.com/grafana/grafana/pull/1296 
https://github.com/grafana/grafana/commit/d4c3463f689eabe624df36e89750579d0c5ea096
