### ISSUE TITLE
[Feature request] Support Apache Kudu or Impala

### ISSUE THREAD

**Issue by archenroot** [grafana/grafana#14900]
I am designing new project where all time series data will be stored in Apache Kudu (distributed SQL engine).

Do you plan such stuff?

Optionally there might be possibility to query Kudu via Impala, but I didn't check if its supported or not at moment.

Thx for response.

**Comment by marefr** [comment]
Will close this for now since this would not be added to core Grafana. So either there may be plugins available or you may need to implement one yourself.

A quick google search on Grafana and apache kudu result in for example https://github.com/danburkert/kudu-ts
