### ISSUE TITLE
Add missing AWS SWF metrics

### ISSUE THREAD

**Issue by peter-banks** [grafana/grafana#14904]
### What Grafana version are you using?
v5.4.3

### What datasource are you using?
CloudWatch/SWF

### What OS are you running grafana on?
Docker - grafana/grafana

### What did you do?
Try to use the following metrics from SWF (Simple Workflow)
ProvisionedBucketSize, ConsumedCapacity and ProvisionedRefillRate

### What was the expected result?
Metrics available

### What happened instead?
Metrics not available

I assume needs to be added here: https://github.com/grafana/grafana/blob/6dc050d01e7dcd9221fff96d168d48b25d133d41/pkg/tsdb/cloudwatch/metric_find_query.go#L110

https://docs.aws.amazon.com/amazonswf/latest/developerguide/cw-metrics.html#cloudwatch-swf-metrics

**Comment by jishf** [comment]
Hi - had the same issue @peter-banks, managed to get it working by adding the following to the metricMap for CloudWatch:
* PendingTasks 
* ConsumedCapacity 
* ProvisionedBucketSize 
* ProvisionedRefillRate 
* ThrottledEvents

and APIName to the dimensionsMap.

<img width="2032" alt="Screenshot 2019-03-25 at 14 31 57" src="https://user-images.githubusercontent.com/26412325/54927833-db5bbb00-4f0a-11e9-8f17-851ffab8b2fb.png">

Happy to submit a PR this afternoon 😄

**Comment by jishf** [comment]
Looks like this has been fixed in #16137

**Comment by marefr** [comment]
Fixed by #16137
