### ISSUE TITLE
Security Issue with filled forms and passwords for data sources

### ISSUE THREAD

**Issue by david-strejc** [grafana/grafana#14911]
When I connect to Grafana as admin and than proceed to MySQL datasource server returns prefilled password field with password for grafana user at MySQL server I am getting data from.

In case of security issue - when let's say someone takes control of grafana instance as someone other forgets to change default credentials admin/admin, person who has admin permissions is than able to proceed with attack by taking control of MySQL instance.

I know this is not only grafana issue - but when someone than creates user with '%' as permitted host in MySQL I can directly connect to MySQL.

Is it necessary for grafana to return password filed (when changed in HTML to input="text" displays as regular password) filled with regular password of mysql user?

Isn't is possible to just place **** characters into text field and only update password field when it was actually changed?

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/2557
