### ISSUE TITLE
Grafana Variables 

### ISSUE THREAD

**Issue by NarendraN2019** [grafana/grafana#14916]
At Variables > Edit
In  Query Options, added probe_success with Name ProS, Label = Instances
In Preview of values, I can see total 6 values.
Now on Grafana dashboard,  I can see Instances with said 6 values in the drop-down fashion.
![image](https://user-images.githubusercontent.com/46757969/51269850-21375880-1989-11e9-9098-5a070b195da1.png)

How can assign name to each of these 6 values/instances?
e.g. Instance1 = Apache , Instance2 = API, etc.

So can use those names in the Metrics QUERY ?

Please advice.

**Comment by torkelo** [comment]
There is no feature in grafana to change names in variable drop down, you can a legend format field in the query editor that allow you to change the names in the graph legend

**Comment by NarendraN2019** [comment]
Thank you 👍
