### ISSUE TITLE
Changing Quick ranges in grafana

### ISSUE THREAD

**Issue by NarendraN2019** [grafana/grafana#14915]
**Objective :** Add “15days” in “Quick ranges” by modifing Grafana’s main dashboard   
**Action:** Tried to import updated json , where in "time_options" added "15d".
![image](https://user-images.githubusercontent.com/46757969/51268008-9bb1a980-1984-11e9-89b1-0ca3a692be07.png)

**Issue:** Still cannot see " Last 15days" option in "Quick ranges"
![image](https://user-images.githubusercontent.com/46757969/51268091-cf8ccf00-1984-11e9-8cbb-28b283a5c2fd.png)

Please advise on the solution.

**Comment by Ijin08** [comment]
Hi,

Sorry to tell you that at the moment you can't change the Quick ranges. Time options in json is a relic from older Grafana versions. There isn't a decision on if/when this will be implemented again. 

Please create a feature request for it.

**Comment by NarendraN2019** [comment]
Thank you Patrick 👍

**Comment by tracetechnical** [comment]
This appears to have regressed in the latest docs
