### ISSUE TITLE
Docs feedback: http_api/data_source.md

### ISSUE THREAD

**Issue by Willis0826** [grafana/grafana#14910]
### What Grafana version are you using?
v5.2.4
### What datasource are you using?
CloudWatch
### What OS are you running grafana on?
macOS
### What did you do?
Create a CloudWatch datasource with `access & secret key` via HTTP API. The `secret key` is base64 encoded.
### What was the expected result?
The datasource should be able to perform a query.
### What happened instead?
The grafana server return `500 Metric request error`.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![2019-01-16 7 54 34](https://user-images.githubusercontent.com/10431078/51247611-a55d0080-19c8-11e9-99a8-773392aa3376.png)

I create the CloudWatch datasource by following the [HTTP API Document](http://docs.grafana.org/v5.2/http_api/data_source/#create-data-source) and it turns out that I created the datasource with base64 encoded AWS `secretKey` will lead to the error. However, if I create the datasource with unencoded AWS `secretKey`, everything works fine. 

Not sure whether this is a document problem. Thank you.

**Comment by marefr** [comment]
I can see that this change was introduced in #11635

I cannot really see why that change was introduced. Updating a cloudwatch datasource in Grafana gives me the following payload and there's no base 64 encoding added of the secretKey:

```json
{
  "id": 122,
  "orgId": 1,
  "name": "CloudWatch-1",
  "type": "cloudwatch",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": { "timeField": "@timestamp", "authType": "keys", "defaultRegion": "us-west-1" },
  "secureJsonFields": {},
  "version": 1,
  "readOnly": false,
  "secureJsonData": { "accessKey": "abc", "secretKey": "def" }
}
```

@ohadbenita could you add some explanation to your change in #11635? Thanks

**Comment by torkelo** [comment]
reverted this docs change in https://github.com/grafana/grafana/pull/15013/files
