### ISSUE TITLE
Metric inputs are misaligned

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#14917]
### What Grafana version are you using?

Grafana v5.4.3 (6539180) on play.grafana.org

### What datasource are you using?

Prometheus

### What did you do?

Added a bunch of metrics

### What was the expected result?

Collapsed metrics are nicely aligned

### What happened instead?

![image](https://user-images.githubusercontent.com/89186/51272899-3e1b5e00-1980-11e9-8e09-eaeba84324ef.png)

**Comment by Ijin08** [comment]
related issue(that will probably solve this): #14886

**Comment by torkelo** [comment]
fixed by new query editor design in v6
