### ISSUE TITLE
Add Timerange navigation sliders

### ISSUE THREAD

**Issue by teo96** [grafana/grafana#1491]
I often need to navigate through the time range : 
- go xx minutes before the current time range
- go xx minutes after the current time range (if not last xx minutes)

Today, I have to use the zoom out feature (once or several times) and then Zoom In using the mouse. It works but generates unusefull work (on the graphite server and grafana app) and extra time.

Would be nice to add 2 sliders icons around the current time range : 
<< Current Time Range >>

A click on a slider button will go xx mn before or after the current time range
Duration of the time range do not have to be modified
If click on 'before', 
new start time = current start time - half of current time range duration
new end time = current end time - hal of current time range duration

Example :
Current Time range = last 30 mn = 12:00 to 12:30
Click on 'before' slider will jump to 11:45 to 12:15
after' slider is disable because it's last 30mn

**Comment by torkelo** [comment]
Good suggestion, just tricky where to put these actions without cluttering the topnav.

Will close this as it is very similar to this issue: pretty similar to this one, https://github.com/grafana/grafana/issues/119
