### ISSUE TITLE
Alert 10 sec not working

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14923]
Hi,

I have added an alert , and i want that to execute in 10s. But it says “no data” .
And , It’s working perfectly for every other conditions, ie, 5m,10m , etc…
![aaaaaaa](https://user-images.githubusercontent.com/22325249/51310510-cecf6800-1a6c-11e9-87d3-25546812e300.PNG)
![ssss](https://user-images.githubusercontent.com/22325249/51310530-d7c03980-1a6c-11e9-8017-450da5010f0d.PNG)

Please help. Thanks in advance.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You don't have any data point in last 10s - modify your query and/or look at a greater timerange in `OF`
