### ISSUE TITLE
Add time range duration

### ISSUE THREAD

**Issue by teo96** [grafana/grafana#1492]
It's easy to know that current time range lasts 30mn when you choose last 30 mn as a time range.

I often need to change the time range using zoom out / zoom in feature and i have to know the duration of the new time range

Today i have to check timestamp of last and first events and then calculate the difference.
Not always easy on big time range or when midnight comes to play (04:43 am - 22:35 pm = ??)

Add the duration of the choosen time range in the top panel near 'Zoom Out' and 'Current Time Range'
Example :
![image](https://cloud.githubusercontent.com/assets/3731213/6227335/72293396-b69e-11e4-9e31-374d7185f3b1.png)

**Comment by torkelo** [comment]
Maybe better to have this in the hover tooltip (when you hover over the time range dropdown)

**Comment by teo96** [comment]
Hum, just discovered this tooltip ...  yes of course this is the perfect place.

**Comment by torkelo** [comment]
Sorry will close this for now, seems to not have any +1 votes for some time 

(Trying to clean up issues a little, and remove some)
