### ISSUE TITLE
CloudWatch: Support region selection for expression query (metric math)

### ISSUE THREAD

**Issue by wizzu** [grafana/grafana#14933]
### What Grafana version are you using?
Grafana v5.3.4 (69630b9)
### What datasource are you using?
CloudWatch
### What OS are you running grafana on?
Debian GNU/Linux
### What did you do?
Used CloudWatch metric math using Expression in Grafana query without specifying a region (region was 'default') due to region selection UI widget not being visible. The source metric for the metric math was in a different region.
### What was the expected result?
Get metric math query result.
### What happened instead?
No metric math query result, query error due to region mismatch. When using metric math, the region for the metric math query must be the same as for the queries which are used in the metric math expression.
 
The problem here is that when using the Expression field for CloudWatch queries (metric math feature in CloudWatch), the UI hides the AWS region selection widget. This leads the user to believe that the region field is not important, and user doesn't realise to pay any attention to it. In order to specify metric math query correctly when using non-default regions, the user needs to select first the region, then enter the query expression (which will hide the region selector), which is not good UI.

For users with data only from a single AWS region there is likely no issue, as the default region value will likely be correct.

**Comment by marefr** [comment]
To add some more context. Same problem in master (af8425d).

Going from this:
![image](https://user-images.githubusercontent.com/1668778/51329807-8d43ba80-1a76-11e9-939c-0773552ec488.png)

To this:
![image](https://user-images.githubusercontent.com/1668778/51329817-92a10500-1a76-11e9-9392-dc4e4f84b841.png)

@mtanda any specific reason for not allowing region selection when using math expressions?

**Comment by wizzu** [comment]
Note, the rest of the fields (namespace, metric, stats, and anything on Dimensions) are not relevant for metric math expressions as far as I understand, so hiding them is good UI behaviour. It's just that region is relevant, so shouldn't be hidden together with the rest.

**Comment by mtanda** [comment]
Sorry, no special reason to hide the region.

I only use a single region for each AWS account.
And I didn't consider about the case, the query doesn't refer id.

**Comment by utkarshcmu** [comment]
How about this kind of a change? Does this looks ok?

If yes, I have a PR ready for it!

<img width="1133" alt="Screen Shot 2019-05-22 at 10 27 52 PM" src="https://user-images.githubusercontent.com/1019609/58227724-e3549300-7ce0-11e9-89cd-b20064eae480.png">
