### ISSUE TITLE
[Feature Request] Allow copying a panel from a dashboard I don't have permissions to modify

### ISSUE THREAD

**Issue by dmagliola** [grafana/grafana#14931]
Scenario: I'd like to add a panel to my dashboard, and there's another dashboard that has pretty much what I want. I'd like to duplicate that panel into my dashboard.
I don't have, however, permissions to modify that other dashboard.

There seem to be two options for doing this:
a) When clicking on the title of a panel, under `More`, there's `Copy`, which I can then use to Paste into my dashboard. However, the `Copy` button doesn't show up for a dashboard that I don't have modify permissions for. 
b) I can also get the Panel's JSON, but I don't see how to apply that JSON to a new panel in my dashboard.

It'd be excellent if we could `Copy` panels from dashboards, even if we don't have modify permissions for them.

Please include this information:
### What Grafana version are you using?
Grafana v5.3.4 (69630b9)

### What did you do?
Click on the title for a panel in a dashboard I don't have access to, and then clicked `More`

### What was the expected result?
A `Copy` menu item was expected to be in the menu, which does happen for dashboards I can modify

### What happened instead?
There was no `Copy` menu item

**Comment by tragiclifestories** [comment]
Related: It would also be nice to have the option of read-only access to the Edit panel of panes in order to see at a glance how certain visualisations have been achieved without the risk of breaking them ...

**Comment by marefr** [comment]
You probably want to enable the `viewers_can_edit` setting, see [documentation](http://docs.grafana.org/installation/configuration/#viewers-can-edit).

**Comment by tragiclifestories** [comment]
@marefr the more you know ... that looks useful, thanks.

**Comment by dmagliola** [comment]
That looks like exactly what we need. Thank you!
