### ISSUE TITLE
Migration from Elasticsearch to Grafana 2.0

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1493]
Is there any way to migrate existing configuration stored in Elasticsearch to Grafana 2.0?

**Comment by costimuraru** [comment]
Oops, found it.
I first had to add a Data Source for Elasticsearch.
I then went to Account -> Import. The newly created data source was not in the list. I had to reload the page (Cmd + R). The data source appeared and managed to do the import.

A few suggestions to ease up the workflow:
1) It would be much easier if instead of pointing to the Elasticsearch server, you could point to an existing grafana server. That implies having a way of reading the configuration used by grafana 1.0 through an API or something and then automatically use the information retrieved in order to do the import in grafana 2.0.
2) I think having to reload the page in order to see newly created data sources is a bug.

**Comment by torkelo** [comment]
yes, the reload thing is a bug. Its a little tricky to fix without forcing a reload though. Need to think about how to solve it :) 

The import process could be improved, good suggestions :)

**Comment by torkelo** [comment]
Fixed the need to reload after new/updated datasource, added error handling to data source import.

**Comment by torkelo** [comment]
Btw, Thanks for the feedback!

**Comment by costimuraru** [comment]
Nice job @torkelo . I can confirm the two bugs are fixed.
