### ISSUE TITLE
Gitlab Oauth2 enable

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#14947]
### What Grafana version are you using?
5.4.3
### What OS are you running grafana on?
Debian

If I use the example code that I need to copy into Grafana.ini it will not work, since the example says enable = false.

http://docs.grafana.org/auth/gitlab/#enable-gitlab-in-grafana

**Comment by marefr** [comment]
Good point. Thanks for pointing that out. Any interest in opening a PR? Otherwise we'll try and fix this.

**Comment by flopp999** [comment]
I can open a PR

**Comment by marefr** [comment]
Fixed by #14951 and #14953
