### ISSUE TITLE
Please document the check_for_updates flag

### ISSUE THREAD

**Issue by mitchellrj** [grafana/grafana#14940]
This flag appears to control the update checker. Please document it, how frequently it checks for updates and what it talks to to try to find updates.

**Comment by marefr** [comment]
There's some documentation in the [defaults.ini file](https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L154-L159). Is that enough?

**Comment by marefr** [comment]
Opps this should be closed. Was fixed by #15014

**Comment by daniellee** [comment]
Added some more details: #15252
