### ISSUE TITLE
Add time shift does not work

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#1494]
Graph --> Time Range --> Add time shift does not work on FF and Chrome. FF 35.0.1 even crashes here after some seconds

**Comment by Sineos** [comment]
Additional Information:
Only happens when no time unit (e.g. h) is given for the value, otherwise it works. Same is true for 
"Override relative time"
![image](https://cloud.githubusercontent.com/assets/4459312/6235631/3bf10614-b6e4-11e4-9ddc-7a7c62998cca.png)

**Comment by torkelo** [comment]
I have added validation, both when the user inputs the timespan and when it is used. Not sure what hangs chrome, but should not be able to get to that state now with all the validation.
