### ISSUE TITLE
AzureMonitor: convert Azure Log Analytics API to Go

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#14943]
The Azure Monitor datasource plugin integrates against 4 Azure API's. 

To support alerting for the Azure Log Analytics service, the [datasource class](https://github.com/grafana/grafana/blob/azure-monitor/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts) for the Azure Log Analytics API needs to be converted from TypeScript to Go.
 
It should be structured in a similar way to Stackdriver: https://github.com/grafana/grafana/blob/master/pkg/tsdb/stackdriver/stackdriver.go

**Comment by daniellee** [comment]
Ref to old alerting issue in the plugin repo: https://github.com/grafana/azure-monitor-datasource/issues/11

**Comment by otm1** [comment]
Any update on date on this? Grafana is working greate for log analytics but we are not able to use it due to missing alerting support.

**Comment by fhlippinio** [comment]
I would like to see this feature as well.

**Comment by terjegjose** [comment]
+1 for this feature!

**Comment by christertime** [comment]
+1 for this feature!

**Comment by maxilampert** [comment]
we're also interested in using alerting for Log Analytics. Any news on the progress of this topic?

**Comment by terjegjose** [comment]
Hi @daniellee 
Are there any news on this issue?
Kind regards.

**Comment by RicardoCostaPS** [comment]
Hi, Any update on this issue ?

**Comment by holly79** [comment]
We are using Grafana for our Monitoring and we are using Log Analytics for the most of our Dashboards. So  we would like to use alerts for this one. So do you have any update?

**Comment by cbijonalliance** [comment]
Hello,

Any news about it ? we need it too please !

Best Regards,

Charles

**Comment by kishorebasisth** [comment]
We need this very badly as well. Any update on this is very much appreciated!!
