### ISSUE TITLE
[BUG] Problem with "constructor" as a value of the templated variable

### ISSUE THREAD

**Issue by alchuk** [grafana/grafana#14961]
When a dashboard variable of the query type resolves to "constructor", Grafana looks confused and prints "function Object() { [native code] }" instead of its value. The graphs are not plotted as well.
Replacing the variable with a statically defined node (a.b.$host.ccc -> a.b.constructor.ccc) resolves the issue.

Grafana 5.4.2.
Graphite with graphite-api are used as a backend.

**Comment by torkelo** [comment]
Can you share you dashboard json?

**Comment by alchuk** [comment]
<details><summary>that's what it looks like for me</summary>
![image](https://user-images.githubusercontent.com/12322967/51470933-55928680-1d86-11e9-8c0b-893531e2986c.png)
</details>

**Comment by torkelo** [comment]
thanks, the bug is here:
https://github.com/grafana/grafana/blob/master/public/app/features/templating/template_srv.ts#L241 

the lookup in the index for grafanaVariables is a success for the property "constructor" (returns a native function).

**Comment by alchuk** [comment]
Looking forward for new releases having this bug fixed. Thank you.

**Comment by miroswan** [comment]
@torkelo I have a fix for this bug but I don't have permissions to push to my feature branch to create a PR. Should I fork instead?

**Comment by torkelo** [comment]
Yes, fork and create PR from your fork

**Comment by miroswan** [comment]
https://github.com/grafana/grafana/pull/15018
