### ISSUE TITLE
Updating a region annotation via the API does not work

### ISSUE THREAD

**Issue by DavidVentura** [grafana/grafana#14978]
Please include this information:
### What Grafana version are you using?
Grafana v5.4.0 (69c5191)
### What datasource are you using?
influxdb, but irrelevant.
### What OS are you running grafana on?
Debian
### What did you do?
POST
```
{'text': 'test-region', 'tags': ['network'], 'isRegion': True, 'time': 1548105095000}
```
reply:
```
{"endId":1225,"id":1224,"message":"Annotation added"}
```
PUT to `/api/annotations/1225`

```
{'text': 'test-region', 'time': 1548105095000, 'isRegion': True, 'timeEnd': 1548105105000, 'tags': ['network']}
```

Reply
```
{"message":"Failed to update annotation for region end time"}
```

### What was the expected result?
Proper update
### What happened instead?
Update failed

[Docs say you should pass `isRegion: true` to the PUT request](http://docs.grafana.org/http_api/annotations/#update-annotation)

Failing to provide the `isRegion` field in the put makes the region show up like a single point.

I believe it might be related to #12546 where it is dropping the `isRegion` value as it is not provided

**Comment by marefr** [comment]
Closing this due to lack of response and I think I've given you the solution to your problem. Will consider reopen if you come back with a response.
