### ISSUE TITLE
Playlist crashing browser

### ISSUE THREAD

**Issue by sandstheman** [grafana/grafana#1497]
Hi I'm having an issue when running a playlist on our screens.  After a few hours it seems to crash either the entire browser (Firefox) or the window that was running the playlist (Chrome).  Had a look at the chrome task manager and could see the window running the playlist using nearly 500MB of memory vs a window that had a single dashboard using approx 75MB.

Suspect memory is leaking somewhere meaning 2-3 times a day my displays show error pages and i need to reload and restart the playlist.  My playlist is rotating through 8 dashboards.

**Comment by torkelo** [comment]
thanks for reporting this, will investigate!

**Comment by normano** [comment]
Can we get this fixed for 1.9 as well? I don't believe some of us will move over to 2.0 for awhile since we just starting deploying.

**Comment by torkelo** [comment]
fixed in master and in develop branch (Grafana 2.0)

**Comment by normano** [comment]
I do not think this has been fixed given that memory is still leaking in all browsers when you switch dashboards.

**Comment by pondohva** [comment]
Hello. We have similar problem and don't want to use 2.0 or master branch in production grafana right now. Could you please create 1.9.2 release with this fix?

**Comment by torkelo** [comment]
@pondohva if you want to build a release from master (it would be the same if I did 1.9.2 release), http://docs.grafana.org/v2.0/project/building_from_source/

**Comment by pondohva** [comment]
I did small fork for grafana installation with puppet - https://github.com/pondohva/puppet-grafana. If you'll create release, I'll change version in my hiera, after that puppet will do magic, otherwise I should find place for tar.gz :)

it's not a big problem, but I don't want to change workflow. (btw, link for grafana 2.0, I read documentation from README already, thx).

**Comment by druchoo** [comment]
@torkelo any update on this? We're seeing this issue on 2.0.2.

**Comment by torkelo** [comment]
@druchoo oh, thats bad, though it was fixed. Any details on how long, and what kind of dashboards? anything special about them?

**Comment by druchoo** [comment]
Seems that this was just affecting epiphany on Raspian. We switched to Chromium and problem went away. Nothing special about the dashboards. They are pretty generic.

**Comment by nobbe** [comment]
@torkelo We're having problems with crashing firefox while using playlist. Our version of grafana is v 2.0.0-beta3 and we're using a few panels with iframe.

**Comment by torkelo** [comment]
@nobbe i suggest you upgrade

**Comment by nobbe** [comment]
Upgraded to 2.0.2 yesterday, still having memleak problems. Aug  4 22:53:06 drift-desktop kernel: [51340.369964] Out of memory: Kill process 2343 (firefox) score 57 or sacrifice child

**Comment by enric-sinh** [comment]
I am still seeing this problem in version: 2.0.2, commit: v2.0.2, build date: 2015-04-22 17:51:50. The dashboards are simple 6h queries from influx 0.8.8. The client is Iceweasel on a Raspberry Pi 2. After about 1-2h of playlist (4 dashboards), the "Script not reponding" message appears because the RAM is full.

**Comment by torkelo** [comment]
@enric-sinh thats a old version, try upgrading

**Comment by cong-trinh** [comment]
Seem like it might be a bug. I am running the latest version of Grafana (2.6) in playlist mode and the playlist seems to be continuously consuming memory.

Tested on:
Ubuntu Desktop:
Chrome
Firefox

Raspberry pi2 
Iceweasel
Epiphany

**Comment by 1Jesper1** [comment]
Has this been fixed yet? We are also experiencing Chrome crashes with PI3 and Chrome.
