### ISSUE TITLE
Explore: refactor initial & modified queries 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14982]
The separation between initial and modified queries in explore adds a ton of unnecessary complexity. 

Changing the QueryField component props to take a query, and a onChange event instead, and a change event that is not called every keypress will solve the issue in a much simpler fashion. 

working on React query editor support and the component interfaces for that and trying to align that with Explore more so there is less duplication & less ways to do the same thing. #14749

**Comment by hugohaggmark** [comment]
I'm gonna hold this until after Beta 1 release
