### ISSUE TITLE
Kibana Timestamp issue

### ISSUE THREAD

**Issue by piyushpatil90** [grafana/grafana#14980]
Hello 

we are facing issue with timestamp in Kibana. there are two datetime fields one is default i.e "@timestamp"(data loading time in ElasticSearch) an 2nd one is coming from the source file i.e **"file_date"**.

Now here problem is when we set dateformat to "browser" that time "@timestamp" is show correctly but "**file_date**" field showing data +5:30hrs.

and when we set dateformat to "UTC" from kibana browsing setting then "**file_date**" shows correct time but "@timestamp" filed showing data -5.30hrs, **but we want both the fields show data correctly.**

can anybody please help us out from this issue.Thank you in advance.
please find below screenshot.

**Source File**
![source_file](https://user-images.githubusercontent.com/45197765/51517493-eded4180-1e40-11e9-9ac5-b216df4b4b80.PNG)

**dateFormat:tz ="Browser"** **Kibana (Advance Setting)**
![kibanasnap_by_default_browser_set](https://user-images.githubusercontent.com/45197765/51517651-723fc480-1e41-11e9-9b06-e7cc752b2bfc.PNG)

**dateFormat:tz ="UTC"** **Kibana (Advance Setting)**
![utc_kibana](https://user-images.githubusercontent.com/45197765/51517797-feea8280-1e41-11e9-9129-df692bf2e810.PNG)

**Comment by torkelo** [comment]
You should open this in the Kibana project repo :)
