### ISSUE TITLE
Explore: Do not clear old transaction (data) when starting new queries

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14986]
Currently Explore clears current data and re-renders empty graphs & tables when starting new query which creates a very turkey / jumpy experience between every query execution, expecially in logs mode where the page scrollbar is shown, then hidden when log lines is cleared, then shown again as they are re-rendered (with new data).

Also would like to change the current loading indicator to the spinner we use in dashboard panels to align the UX a bit more.

**Comment by davkal** [comment]
> Also would like to change the current loading indicator to the spinner we use in dashboard panels to align the UX a bit more.

The UX is different: Dashboards are results and viz oriented, so the spinner should be less intrusive. But Explore is about quick query iteration, and that needs a more visible indicator that a query is happening. IMO the spinner is not enough, and the UX is different enough to warrant a separate loading indicator.
As a sidenote: the loading indication on dashboard panel edit mode lacks similar feedback. If anything that should be more prominent too.
