### ISSUE TITLE
[Feature request]: Status panel customize text when warning/critical status

### ISSUE THREAD

**Issue by ShirgoskiKristijan** [grafana/grafana#14993]
Hello,

The Status Panel at the moment doesn't support customization of the text it displays when the thresholds indicate a warning or a critical state. I need to have meaningful text or get rid of the text completely and just display colors based on the thresholds. 
Could we please get that functionality added to the Status Panel plugin?

![feature request grafana](https://user-images.githubusercontent.com/11635300/51539815-37e02280-1e55-11e9-84a3-5ed18ad05c7c.png)

Thanks in advance!

**Comment by Theoooooo** [comment]
Are you using a plugin for this Status Panel ?

**Comment by torkelo** [comment]
The status panel is an external plugin: https://github.com/Vonage/Grafana_Status_panel
