### ISSUE TITLE
[Feature Request] Icon within UI to indicate dashboard is provisioned

### ISSUE THREAD

**Issue by Xopherus** [grafana/grafana#14994]
I'm not sure if anyone else has a need for this, but on my team we have a mix of provisioned and non-provisioned dashboards. Ideally we'd like to move as many dashboards to version control as possible so we can roll out updates to all of our environments without having to make the same duplicate changes. Is there some sort of indicator we can include within the UI to clearly indicate when a dashboard is being provisioned? That would really help us identify the remaining ones, as well as inform the rest of the team that they need to make sure that new dashboards they create follow the same process.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
