### ISSUE TITLE
JS error: "Uncaught TypeError: Cannot read property 'data' of undefined"

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1499]
Occasionally, on graphs that have no data but have loaded successfully, all `mouseover` (or `mousemove`?) events trigger a JS error like:

![](https://s3.amazonaws.com/f.cl.ly/items/2A2U181t1E061Z1e1p1L/Screen%20Shot%202015-02-19%20at%201.50.15%20PM.png)

I am observing this right now on a panel that seems normal other than being set to a time window where the underlying metrics have no data (presumably all `null`s in Graphite); screengrab:

![](https://s3.amazonaws.com/f.cl.ly/items/163j0L1V2L3c3U0U1n3Q/Screen%20Shot%202015-02-19%20at%201.52.02%20PM.png)

When I open up that panel in "edit" mode, I see the same behavior. When I change the "Null point mode" from "connected" to "null" or "null as zero", the errors stop; when I change back to "connected" they resume again.

So it seems like this may be specific to null-point-"connected" panels with only `null`s in the viewed time window.

**Comment by torkelo** [comment]
fixed in develop branch along with another improvement to the shared tooltip, https://github.com/grafana/grafana/issues/978  (Shared tooltip now works with many series with different resolution/interval between points).
