### ISSUE TITLE
When using LDAP do not store clear text username in grafana_user 

### ISSUE THREAD

**Issue by redbarnnobrakes** [grafana/grafana#14996]
Having the username stored as a cookie is flagged as a vulnerability by some enterprise security scanning software (HPE Fortify for example). To satisfy this vulnerability flag, it would be ideal to either:

1. Have an option in Grafana's config to not store the grafana_user cookie value when LDAP is configured.
2. Use a hashed or encrypted value for the username in cookie grafana_user.

**Comment by marefr** [comment]
This will be removed in Grafana v6 by #7741 so closing this.
