### ISSUE TITLE
Hide empty panel/graph

### ISSUE THREAD

**Issue by AniGunner** [grafana/grafana#14990]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What did you do?
![grafana](https://user-images.githubusercontent.com/44370229/51536766-a4b5e580-1e72-11e9-9772-f03187d51961.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

I am not able to find the suppress if empty option.

**Comment by torkelo** [comment]
I don't think we will support this. We are might be adding an option to show a custom markdown description text when there is no data in the panel. But hiding the panel and causing a cascading layout change is tricky.

We hope to solve usecases like this in the future by having a new type of scripted dashboards where queries live on the dashboard level and generate a layout.
