### ISSUE TITLE
Y-axis not aligning on 5.4.3 with multiple series

### ISSUE THREAD

**Issue by tehlers320** [grafana/grafana#15001]
Please include this information:
### What Grafana version are you using?
5.4.3
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Server(linux), Client(Chrome 71.0.3578.98)
### What did you do?
Tried to display 2 percents
### What was the expected result?
That they match their correct location on the lines
### What happened instead?
The second series does not align correctly to the Y-axis
### If related to metric query / data viz:
When you initially open:
![screen shot 2019-01-22 at 5 17 38 pm](https://user-images.githubusercontent.com/16598119/51572131-0faeee80-1e6a-11e9-9fc6-49e145a9d089.png)

You can fix it by changing the X-axis to something other than Time, then change it back.
![screen shot 2019-01-22 at 5 18 04 pm](https://user-images.githubusercontent.com/16598119/51572124-0cb3fe00-1e6a-11e9-856f-7984f5237b55.png)

**Comment by torkelo** [comment]
have you stacking enabled? Can you show response from query inspector? Can you replicate this always?

**Comment by tehlers320** [comment]
Ah neat... sorry should have caught this. Changing the X-axis unchecks stacking...
