### ISSUE TITLE
Obsolete "current" value remains in force for constant variable

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#15006]
We observe unexpected behavior in a new dashboard under construction. This dashboard was a created by Save As of another dashboard, after which it was modified.

There is a variable with type constant - a hardcoded value. Yet somehow in the dashboard JSON I can see that it also has a "current" value that is not the constant value now assigned but instead a value from the distant past. On load, the invalid "current" value is used. After some fiddling, the proper value starts being used.

I do not know how this happened but I would expect Grafana to never have the wrong value for constant variables.

![image](https://user-images.githubusercontent.com/9914262/51603093-6ae7ec00-1f11-11e9-9574-d6b708b82650.png)

Grafana 5.4.3 with Prometheus. Initial dashboard used as template was created 6+ months ago with some unknown older version.

**Comment by torkelo** [comment]
Maybe someone unhid it and specified a custom value in the variable input (on the top of dashboard).

The only way I can replicate this is to unhide it and change the value from the variable input

**Comment by torkelo** [comment]
When you save a dashboard there is a checkbox to also save the current value of variables, I think you must have missed checking this checkbox, it also affects constants.
