### ISSUE TITLE
Support for range values of template variables

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1500]
In addition to the "All" option that the current "query" template var creation flow allows for setting up, it would be nice to allow the user to hardcode some additional value ranges ([cf. Graphite docs](http://graphite.readthedocs.org/en/latest/render_api.html#paths-and-wildcards)) that they could select from in the variable's drop-down.

For example, specifying `0[0-9][0-9],1[0-9][0-9],2[0-9][0-9]` might add the values `0[0-9][0-9]`, `1[0-9][0-9]`, and `2[0-9][0-9]`, which would allow the user to view disjoint chunks of 100 metrics at a time from a numerically-valued "node" (segment of a metric name).

Let me know if that makes sense, it's a little tricky to describe. Thanks!

**Comment by torkelo** [comment]
can be solved by custom template variable, or using query template variable with value groups / tags
