### ISSUE TITLE
Fail gracefully when "custom" template var is missing "query" field

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1501]
While working on a scripted dashboard, I was seeing a confusing JS error: `TypeError: Cannot read property 'indexOf' of undefined`:

![](http://f.cl.ly/items/362d2l233V3X2E3u3H3r/Screen%20Shot%202015-02-19%20at%206.30.05%20PM.png)

I bisected and futzed with my dashboard's JSON for a while, and came to realize that the culprit was a missing `query` field on a "custom" template variable. Adding an empty-string, i.e. `query: ""`, to the template-variable's JSON fixes it; the "custom" variable has no use for a "query" string, AFAIU.

On one hand this is my fault because I've been dropping various fields while porting raw dashboard- and panel-JSON into more minimally-defined versions inlined in my scripted dashboard, but some better error messaging or, even better, covering up of this error (if custom template variables indeed don't do anything with the "query" value) could be nice in this situation!

**Comment by torkelo** [comment]
Thanks for reporting this, fixed in #develop branch
