### ISSUE TITLE
Can Grafana get data from Elastic via API?

### ISSUE THREAD

**Issue by jrplusone** [grafana/grafana#15019]
Can Grafana get the data from Elastic via API? Cant find this answer anywhere at all.

**Comment by torkelo** [comment]
yes, Grafana can fetch data and visualize data from elasticsearch:
https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1

**Comment by jrplusone** [comment]
> yes, Grafana can fetch data and visualize data from elasticsearch:
> https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1

I know grafana can fetch data and visualize data from elasticsearch, what i am asking is can it do so VIA API?? what we have now is a http connection to the elasticsearch host directly and not via API right? Can you understand the ask before you close the thread ahead of you?
