### ISSUE TITLE
Missing Time Region when first day not in graph

### ISSUE THREAD

**Issue by Jean-Daniel** [grafana/grafana#15010]
### What Grafana version are you using?
Grafana 5.4.3

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu Bionic

### What did you do?
Display a graph for the `Last 7 days` with a time region `From Monday to Friday` (without any hour settings). 
At least when displaying the graph on Wednesday, only days from the current week are highlighted. 
Thursday and Friday of the previous week are not highlighted.

<img width="848" alt="capture d ecran 2019-01-23 a 16 26 26" src="https://user-images.githubusercontent.com/304649/51617397-71d02800-1f2c-11e9-877c-3a01115a3013.png">

### What was the expected result?

I expect that all weeks days are highlighted and not only the current week days.

### What happened instead?

See picture above.

**Comment by ashharrison90** [comment]
hi @Jean-Daniel 👋 

thanks for raising this!
can confirm it's definitely a bug. however, given the graph panel is deprecated and we're only really fixing major bugs with it, i'm going to close this as `wontfix`.

i've added it to the issue we're using to track implementing time ranges in the time series panel [here](https://github.com/grafana/grafana/issues/30564) (to make sure we don't reimplement the same bug! 😅 ), so hopefully the functionality will be available in the time series panel very soon.

hope that makes sense.
