### ISSUE TITLE
Explore for viewers

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#15026]
We have two kind of Grafana servers:
 internal and  external.

All of them are «read only». However, thanks to an issue I created months ago, /explore is no longer accessible by viewers.

For the internal grafana servers, this would be useful. For the external ones, this is not desirable.

Propositions:
- Add a config parameter: explore_min_rights = viewers
- Add an «explorer» role.

Thanks.

**Comment by torkelo** [comment]
you can enable viewers_can_edit to make explore available to users with Viewer role. They will then also be able to make transient (not savable) edits in dashboards.

**Comment by roidelapluie** [comment]
awesome!!

**Comment by ogxd** [comment]
Hello! Sorry to anwser to this old issue, but `viewers_can_edit` is now marked as "deprecated" [in the documentation](https://github.com/grafana/grafana/blob/main/docs/sources/setup-grafana/configure-grafana/_index.md?plain=1#L982). It is advised to use RBAC instead, however RBAC is not available for self hosted Grafana. Is there a possibility that this feature gets completely removed in the future without alternative for OSS users?

**Comment by shellwhale** [comment]
Yes it's going to be removed

**Comment by dit-darius** [comment]
What's the alternative then to grant query-only permissions to Viewer users? For OSS self-hosted deployments.
