### ISSUE TITLE
[Feature request] ASAP smoother

### ISSUE THREAD

**Issue by msiebuhr** [grafana/grafana#15022]
From using Datadog, I've come to find their `autosmooth()`-function *very* handy when dealing with "spiky" data series.

Their implementation ([blog post](https://www.datadoghq.com/blog/auto-smoother-asap/)) is inspired by the ASAP smoother (Automatic Smoothing for Attention Prioritization; [homepage](http://futuredata.stanford.edu/asap/), [PDF paper](https://arxiv.org/pdf/1703.00983.pdf)).

While it is not perfect for every use-case, I have found it to work extremely well compared to hand-tuning some "average over X minutes" until a pattern actually emerges, yet it doesn't hide actual spikes.

Example from the ASAP homepage:

![screenshot 2019-01-14 at 11 37 05](https://user-images.githubusercontent.com/330611/51107932-c4089f00-17f0-11e9-8405-e38771a4e4d2.png)

Re-post from https://github.com/prometheus/prometheus/issues/5094

Seems related to #3920 and #3677

**Comment by torkelo** [comment]
this should be implemented in the database (TSDB) before aggregation, not client side by Grafana.

**Comment by psmgeelen** [comment]
Can we reopen this? It does not make sense to smooth on a DB level. That is just a poor way of duplicating data. These smoothing algorithms are executable on JS level. The ASAP algorithm has already been written in JS, so whats the big deal? My organisation intends to use Grafana for a large-scale role-out. Could you support this developement or support the OS community how to implement this? Regards

**Comment by torkelo** [comment]
no this make no sense to do in the UI, it's backend query transformation

moving average style transforms are standard TSDB query functions

**Comment by psmgeelen** [comment]
Hi Torkelo, 
"Moving average style" is not what is being discussed here.. Think more Savitzky-Golay, ASAP, Exponential Smoothing etc. The issue is that there might be intermediate regressions, residues and other memomry related issues that are required. To add, this is fundamental for reading signal-data properly, and therefore belongs in the visualisation engine. So I make a difference in querying (where data is retrieved in a certain format), processing (where the data is transformed and can be recalculated, like SG-filter) and rendering. How "open" is the aggregation section anyways? Why cant it run, e.g. basic python?

**Comment by torkelo** [comment]
Can be implemented as a Grafana 7.0 transformation  (they are UI only)

but this feels a normal backend transformation function and not something that belongs to viz layer. For example if you want to alert on the smoothed data you would not be able to do that.

**Comment by psmgeelen** [comment]
Could you share an implementation of an SG-filter? If the aggregation toolkit supports that, than that already would be something :)

**Comment by danieldonoghue** [comment]
> Can be implemented as a Grafana 7.0 transformation (they are UI only)
> 
> but this feels a normal backend transformation function and not something that belongs to viz layer. For example if you want to alert on the smoothed data you would not be able to do that.

since grafana allows mixed datasources and transformations across them, such as row reduction, it is not always possible to do this in the back end. a smoothing transformation would definitely be a big plus
