### ISSUE TITLE
Support of InfluxDB continuous queries

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#1502]
It would be nice if Grafana could be configured to automatically use InfluxDB continuous queries when zooming graphs.

E.g.:
- High precision shard with 1s resolution and 7d retention: my.values.1s
- Continuous query source 1 with 1 min and 30d retention: my.values.1m 
- Continuous query source 2 with 10 min and 1y retention: my.values.1y

When now zooming within 7d Grafana should use my.values.1s. When zooming out to a time range >7d AND <=30d Grafana would automatically switch to my.values.1m etc.

This could be done in the Graph Edit pane e.g. by adding a new tab. Possible ways to identify the different sources would be:
- Mapping between metric name and time range fields
- Mapping between tags (InfluxDB 0.9) and time range fields

**Comment by torkelo** [comment]
@Sineos good idea, I would like to implement something like this. Will wait until InfluxDB 0.9 is released, it will require a big change for the influxdb metric editor, maybe something like this can be implemented as well. 


Will close this as there already is a similar issue, #420
