### ISSUE TITLE
When connect to prometheus,the grafana log show:http proxy error getsockopt:connection refuse

### ISSUE THREAD

**Issue by ldd91** [grafana/grafana#15020]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 I install the grafana and the prometheus in kubernetes(version:1.11) pod.I set the prometheus url:http://prometheus:9090 and the Access:proxy,when i exec the grafana Date&Test  it shows Success,however when i deployment the node-exporter it shows HTTP Error Bad Gateway and Success.

**Comment by torkelo** [comment]
Some network configuration issue with your deployments? 

Please ask questions on the community site https://community.grafana.com
