### ISSUE TITLE
Submenu (Template variables & Annotations) slight redesign

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1503]
I feel that with the changes to the topmenu makes the submenu where the template variables and annotations are a little too cluttered. There is just too much going on in that region. 

![image](https://cloud.githubusercontent.com/assets/10999/6284666/e78f9a98-b8f2-11e4-9d03-75897810f78c.png)

A potential improvement would be to make the submenu transparent and push it down a little bit from the top navbar. This makes it feel a little more part of the dashboard and creates some space between it and all the icons in the top navbar. 

Example:
![image](https://cloud.githubusercontent.com/assets/10999/6284693/28e639ac-b8f3-11e4-906f-a5950fdef93f.png)

Added a "Variables:" label, and small carets to indicate that there is a dropdown with alternative options. Feedback please :)

**Comment by toni-moreno** [comment]
Hi @torkelo , I like this change .

I suggest also to add a "Label"  field on the variable editor to change the "real" variable name for something more readable , mostly for "Viewer" users that don't know nothing about "$" sign in variables.

In your example:

variable : $app => Label: "Application ID" 
variable : $server => Label : "Server ID"
variable : $interval => Label : "Consolidation Interval"

**Comment by torkelo** [comment]
@toni-moreno good suggestion, not sure I will be able to find time to do that in time for Grafana 2.0, but a good idea,
