### ISSUE TITLE
A security problem of the fixed salt

### ISSUE THREAD

**Issue by sunnut** [grafana/grafana#15035]
/pkg/setting/cbccrypt.go

func getrootkey(rootkey string) []byte {

	password, err := base64.StdEncoding.DecodeString(rootkey)
	if err != nil {
		panic(errors.New("rootkey can not unbase64"))
	}

        // how can i change this to random?
	salt := []byte{0xba, 0xb0, 0xba, 0x6c, 0xf5, 0x90, 0x91, 0xfc, 0x2a, 0x7e, 0xfd, 0x77, 0xfc, 0xfe, 0xfc, 0xc0}

	out := pbkdf2.Key(password, salt, 1000, 16, sha1.New)
	return out
}

**Comment by marefr** [comment]
We don't have a file named /pkg/setting/cbccrypt.go in master (c7b556c0e40f7f2318b87b217a06dcfb560cef4e) so I'm closing this. Will consider reopen if you provide more information.
