### ISSUE TITLE
Y-axis set to auto does not auto set for the time range selected when using a influx datasource

### ISSUE THREAD

**Issue by HelenaZheng** [grafana/grafana#15036]
I have my graph getting its data from a influx datasource, and I have the y-max setting for the y-axis set to “auto”, but it seems to auto scale for all the data brought back my the influx select statements, instead of taking into account the timeframe specified in the top right. so, if I had a really high value a year ago, my scale will forever take that into account, even if I am only looking at the last 6 hours.

**Comment by torkelo** [comment]
Make sure you have a time range filter in your query so you do not return data for all of history
