### ISSUE TITLE
Panel Query Editor Issue when default data source does not support metrics 

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15049]
0. Loki datasource as default, plus one other datasource, e.g., Prometheus
1. Add a dashboard and save it
2. Add a panel
3. Click Edit panel

Result: 
<img width="526" alt="screenshot 2019-01-24 at 15 37 00" src="https://user-images.githubusercontent.com/859729/51685114-ec14b100-1fed-11e9-9529-d66b5867e5a5.png">

After switching datasources back and forth, the edit component loads fine.

**Comment by torkelo** [comment]
Strange, unable to replicate this.

**Comment by davkal** [comment]
Still happens for me after a fresh `yarn install` and `yarn start`. Will check if it's a build issue.

**Comment by davkal** [comment]
Happens when Loki is default datasource. Updated description.

**Comment by torkelo** [comment]
ah, ok.

**Comment by ivanahuckova** [comment]
Loki works fine now (as it supports metrics queries), but I was able to reproduce this with Jaeger which I guess is not supported in dashboards as we don't have tracing panel. 
1. Set Jaeger as default data source
2. Add a dashboard 
3. Add a panel
4. Click Edit panel

We get the `Data source plugin does not export any Query Editor component` message, but the selected data source is Loki (Jaeger is not in data source list), which has Query Editor component. 

![image](https://user-images.githubusercontent.com/30407135/99791259-abbce600-2b25-11eb-8fe9-2a601ecf2777.png)
