### ISSUE TITLE
Reloading unsaved panel leads to empty screen

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15048]
1. Create a dashboard
2. Add a panel and stay in edit view and don't save the dashboard
3. Reload browser window

Result: Empty screen
Expected: Edit view of empty panel

It's hard to escape from there: no Grafana icon, no side bar (related: #15008)
There is a back-to-dash arrow at the top left, but it's hard to see, and it does not work.

**Comment by torkelo** [comment]
Yes, this has been a problem for a long time and is worse in v6, needs a fix!
