### ISSUE TITLE
Graf jump randomly 

### ISSUE THREAD

**Issue by zyriuse75** [grafana/grafana#15047]
Dear all 

i try to monitor my container with grafana and prometheus and cadvisor . 
Unfortunately i dont understand why but the graf is jumping randomly and during few seconds until the next refresh i can like a zoom of the first graph . and also is missing a part of the graph at the end and i dont understand why .

do i've to do something with refresh params on the right of the top ?

below a screenshot of the missing part of the graph 
https://ufile.io/h1ekt

jump graf : https://ufile.io/pmdkr 
Normal  graf : https://ufile.io/ghupf

grafana: 5.2.2
prometheus : 2.3.2

**Comment by marefr** [comment]
What's your scrape interval? What does you're query looks like and what settings do you have for the datasource/query like scrape interval, min step and resolution?

Please use the [query inspector](https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630) and include request/response here.

**Comment by marefr** [comment]
Closing this due to lack of response. Will consider reopen if you come back with a response.

We've done a few improvements regarding Prometheus and step calculation since your Grafana version so I would suggest to upgrade to the latest version of Grafana.
