### ISSUE TITLE
Some docker blocks docker-compose.yaml are invalid

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15043]
0. Recent docker-compose, e.g., 1.23.1
1. cd devenv/docker/blocks/elastic6
2. docker-compose up

Result:
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for fake-elastic6-data: 'network_mode'
```

It looks like the missing `version` field is now treated as compose file format version 1, which does not have the `network_mode`.

Some blocks have `version: '2'`. Should we set this to 2 for all blocks? 3 is the most recent.

**Comment by davkal** [comment]
Should we harmonize the blocks though? Some have `version`, e.g. (elastic5) and some do not (elastic6).

**Comment by marefr** [comment]
That's probably a good idea :+1:

**Comment by marefr** [comment]
Don't actually know if the version adds anything besides that docker-compose probably can say that you'll need to upgrade to a newer version.
