### ISSUE TITLE
Unknown Alert state.

### ISSUE THREAD

**Issue by dobeeisfree** [grafana/grafana#15056]
Hello, I got some issue about `[Unkown]` Alert state.
is it normal??

Please include this information:
### What Grafana version are you using?
v5.4.2

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
CentOS 7 (redhat)

### What did you do?
create graph with alert that data point not come in.

### What was the expected result?
no alerting until some data come in and some conditions triggered.

### What happened instead?
[Unknown] + "alert name" email alert triggered

### If related to metric query / data viz:
this is my Alert Config

* Conditions  
  * `WHEN` count() `OF` query(A,1m,now) `IS ABOVE` `20`

* if no data or all values are null `SET STATE TO ` Keep Last State
* if execution error or timeout `SET STATE TO ` Keep Last State

* Notifications  
  * channel email

Other notification rules are normal (OK).

**Comment by marefr** [comment]
Probably because "if no data or all values are null SET STATE TO Keep Last State" since the last state is unknown. Please change to "if no data or all values are null SET STATE TO Alerting" - at least for the first alert to trigger.
