### ISSUE TITLE
Difficult to see lower options in query builder dropdowns

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15052]
0. Elastic datasource (Graphite might work too)
1. Add dashboard
2. Add panel
3. Edit panel
4. Select Elastic datasource
5. Resize your screen so that only a query row height is free under the current query row
6. Click on the Metric dropdown
7. Try to select "Raw document"

Result: The dropdown ends right at the edge of the window, sometimes the status bar in Chrome overshadows the last options. If the window is only slightly shifted off-screen, it's hard to tell that there are more options. I also had to scroll the internal query row container to see the lower options.

<img width="291" alt="screenshot 2019-01-24 at 16 09 42" src="https://user-images.githubusercontent.com/859729/51687275-7ced8b80-1ff2-11e9-9613-53f1d5550640.png">

**Comment by torkelo** [comment]
I can scroll down to see the lower options. If the OSX option for native scrollbars set to always hide it can be hard to see that there is a scrollbar. 

if you're on a small screen you can resize the panel and get more space for the query editor view.

Do you have any ideas how to address this?

**Comment by davkal** [comment]
I think what tripped me was a very small margin that governs the window expansion. Perhaps increase that one? It's difficult to see the last item because of the status bar:

![screenshot 2019-01-28 at 12 51 44](https://user-images.githubusercontent.com/859729/51834763-96951880-22fb-11e9-8ec5-c116ae94fe3e.png)

**Comment by torkelo** [comment]
Is that not a browser behavior we cannot control?
