### ISSUE TITLE
Feature request: Add help text in charts

### ISSUE THREAD

**Issue by swissdave** [grafana/grafana#1505]
I'd like to be able to add a bit of help text to explain what is going on in any given chart - this would be useful for e.g. support staff to help them understand the data.  Perhaps showing it by an (i) or (?) icon near the chart title or in a top corner of a chart would work.

I know it's possible to add text panels which could serve this purpose but they use up valuable screen space for those who don't need it.

Thanks!

**Comment by maddenca** [comment]
+1

**Comment by sanga** [comment]
+1

**Comment by addshore** [comment]
+1

**Comment by amuraru** [comment]
:+1:

**Comment by utkarshcmu** [comment]
+1

**Comment by utkarshcmu** [comment]
Implemented in #3691 , Here is a screenshot:

<img width="1425" alt="screen shot 2016-01-09 at 4 28 34 am" src="https://cloud.githubusercontent.com/assets/1019609/12216044/b565914a-b689-11e5-9c39-910ac6e25f69.png">

This helper text is completely optional. If there is no helper text in the text box, there will be no help icon in the Title. :)

**Comment by swissdave** [comment]
Fantastic - thanks very much

**Comment by utkarshcmu** [comment]
Some more screenshots and scenarios:

* 1st and 4th panels have help text.

<img width="1427" alt="screen shot 2016-01-09 at 12 23 29 pm" src="https://cloud.githubusercontent.com/assets/1019609/12218159/e99513d6-b6cb-11e5-93e5-afaaa610ccf9.png">

* If no help text is provided, the title remains as it is. Like in 2nd and 3rd panel above.
<img width="1418" alt="screen shot 2016-01-09 at 12 23 37 pm" src="https://cloud.githubusercontent.com/assets/1019609/12218163/099ee38c-b6cc-11e5-9fbb-625b178b1a04.png">

**Comment by torkelo** [comment]
Having panel description text that only appear on mouse over (like tooltip) is not something that feels like a good idea. If the information is important then it should be visibile all the time.

Closing in favor of something like this
https://github.com/grafana/grafana/issues/1168

**Comment by utkarshcmu** [comment]
Its OK if we do not want to include this feature in Grafana, I can always have it in my fork, no worries. :)

But in my opinion, text will take a lot of space on the dashboards and not many would want to compromise space with texts on a dashboard which is useful only to read once. Once read, people know what the graphs represent. Even what is suggested in #1168 is great but I think having the text hidden somewhere is a better than having it visible at all times. Just my opinion. :)

**Comment by swissdave** [comment]
+1 to that.. some of our charts are quite technical and need quite some text to explain.  People familiar with the data don’t want their screen space take up with lots of explanatory text, but to be able to pull it up quickly when needed is ideal..

**Comment by utkarshcmu** [comment]
@swissdave Merged #3691 in my fork. https://github.com/justforkit/grafana

**Comment by bhaskark2015** [comment]
@utkarshcmu I tried your changes but the tooltip is not triggered are we missing initialisation in the code?
