### ISSUE TITLE
When using a reverse proxy with a sub path, returned cookies have incorrect path

### ISSUE THREAD

**Issue by danielnelson** [grafana/grafana#15069]
### What Grafana version are you using?

Grafana 5.4.3

### What OS are you running grafana on?

Linux

### What did you do?

I am attempting to run behind a lighttpd reverse proxy.

I setup my Grafana instance with these settings:
```
[server]
domain = "example.org"
root_url = "https://example.org/grafana/"
```

I also setup lighttpd with this configuration to proxy the /grafana/ path and rewrite the /grafana prefix in the request headers:
```
$HTTP["url"] =~ "^/grafana/" {
	proxy.server = ( "" => ( "grafana" => ( "host" => "127.0.0.1", "port" => 3000 ) ) )
	proxy.header = ( "map-urlpath" => ( "/grafana/" => "/" ) )
}
```

### What was the expected result?

Can browse to Grafana instance and use it.

### What happened instead?

Browsing to Grafana works but logged out immediately after successful login; refreshing the page will result in being logged out.

### Investigation...

After a little poking around I found that the response of the login transation has an incorrect Path for the cookies: `/grafana/grafana/`.  This results in the cookies not being sent with subsequent queries because they target only `/grafana`.
```
POST /grafana/login HTTP/1.1

{
    "password": "admin",
    "user": "admin"
}

HTTP/1.1 200 OK
Set-Cookie: grafana_user=admin; Path=/grafana/grafana/; Max-Age=604800
Set-Cookie: grafana_remember=5f3b559aa7ec33c175b05badb628ecbb3230ae134fd0fcda7b87d2ceb04629bc95; Path=/grafana/grafana/; Max-Age=604800
Set-Cookie: grafana_sess=80590bc9e040fb49; Path=/grafana/grafana; HttpOnly

{
    "message": "Logged in"
}
```

I also found [this issue][2880] on the lighttpd issue tracker that exactly describes what is happening with a different webapp.  Lighttpd is adding back the prefix to the returned urls to restore the external path, but Grafana has also done this based on the value of root_url.

The lighttpd team believes this is an defect with the webapp, which should be returning `/` as the path.

[2880]: https://redmine.lighttpd.net/issues/2880

One final side note, I did find https://github.com/grafana/grafana/issues/4181, but this method uses an older method for proxying with lighttpd which requires you to run two lighttpd instances to double proxy.  This is further described in [this issue](https://redmine.lighttpd.net/issues/164#note-9) but I'd rather avoid running multipel lighttpd instances.

**Comment by torkelo** [comment]
is probably something with your lighttpd setting that is causing the duplicate grafana subpath, grafana only adds one.

**Comment by torkelo** [comment]
We have a few working reverse proxy examples here: http://docs.grafana.org/installation/behind_proxy/#running-grafana-behind-a-reverse-proxy

**Comment by torkelo** [comment]
When using a reverse proxy dont rerite headers or body , only the http request url . That is what the example of nginx and Apache does that I linked to.
