### ISSUE TITLE
"Series value as timestamp" annotations should be deduplicated

### ISSUE THREAD

**Issue by free** [grafana/grafana#15064]
### What Grafana version are you using?
5.4.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Linux
### What did you do?
Created a Prometheus query-based annotation that had the "Series value as timestamp" option checked (see #11789). The annotation was supposed to display a marker for every instance restart.
### What was the expected result?
I was expecting to see a couple of markers for the 2 restarts that happened during the past 24 hours, after a second or two of loading.
### What happened instead?
Visually I got the expected result, but loading took minutes rather than seconds and AFAICT there was one marker per sample returned by Prometheus (all drawn on top of each other, in the 2 locations) rather than only 2 markers. This caused the Chrome tab to peg the CPU at 100% for minutes and the tab was unresponsive for the duration.

Ideally, for annotations with "Series value as timestamp" checked, the values would first be de-duplicated and only then turned into markers on the graph. There is no good reason to draw 1k markers with the exact same title, tags and text, on top of each other.

**Comment by free** [comment]
I disagree with this being designated a feature request. Right now Grafana becomes totally unresponsive for minutes at a time when this happens. To the point that even hitting the reload button in the browser or pressing Ctrl-Shift-R doesn't do anything.

I was going to say that the only workaround is to close the tab and reopen it, but I just tried now and the tab doesn't close. I had to go into Chrome's task manager and kill the process.

This looks to me very much like a bug.

**Comment by torkelo** [comment]
it all depends on your step option, it controls how many data points Prometheus returns. Prometheus time series not ideal for this use case in the first place.

**Comment by free** [comment]
Fair enough, but:

(a) the step is fixed while my dashboards can (usefully) show anywhere from half an hour to a month of data; and
(b) I am already having this issue with a 30s step and a 1 day range (i.e. about the same number of samples that a graph at 1/1 resolution on a decent screen would request).
