### ISSUE TITLE
Annotations not updated when switching dashboards

### ISSUE THREAD

**Issue by free** [grafana/grafana#15063]
### What Grafana version are you using?
5.4.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Linux
### What did you do?
Opened dashboard A, with a Prometheus query-based annotations. Annotation was loaded correctly.

Then, by clicking on the dashboard title, selected a second dashboard, B, with different Prometheus query-based annotations.
### What was the expected result?
The annotations for dashboard B would load correctly.
### What happened instead?
The annotations for dashboard A were displayed on top of dashboard B, title, tags and all. No API request (whether to Grafana's `/annotations` or the relevant Prometheus query) was issued, according to Chrome's network inspector.

Doing a full page reload (Ctrl-Shift-R) will correctly load the annotations.

**Comment by marefr** [comment]
Confirmed bug in v5.4.2 and v5.4.3 and current master (684b5881265ed7f563c2c631f17dfff4e0edb8e0). 

Easy to reproduce using builtin Grafana annotations:
1. Create a dashboard
2. Add a panel with grafana testdata datasource
3. Save dashboard
4. Add annotations to the panel
5. Save the dashboard as 
6. Redirected to new dashboard
  - expected annotations not to be shown here, but they are
7. Refresh dashboard 
  - removes the annotations
8. Navigate to initially saved dashboard
  -  expected annotations to be shown here, but they are not
9. Refresh dashboard 
  - annotations are shown
