### ISSUE TITLE
Auth token improvements

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#15067]
- [x] Delete auth token when logging out
- [x] Investigate having a token in cookie that have been removed in database. When reloading a dashboard, calling ping should return 401 unathorized and redirect to login page
- [x] Use [SameSite](https://www.owasp.org/index.php/SameSite) for cookies? 
- [x] Move middleware parts from UserAuthTokenService to api middleware package to make it easier to write tests for it
- [x] clean up job should be configured to run on certain schedule and delete all expired tokens
- [x] Basic docs/configuration comments

**Comment by marefr** [comment]
Fixed by #15170, #15181, #15191, #15239
