### ISSUE TITLE
Feature: Alertmanager notifier label support

### ISSUE THREAD

**Issue by wleese** [grafana/grafana#15079]
While we now have support for sending notifications to alertmanager (https://github.com/grafana/grafana/pull/8644), they're sufficiently limited due to the lack of label support that semi large environments cannot benefit from this notification path.

In Prometheus an alerts labels (not to be confused with the metric labels) are present in the alert that alertmanager creates and are used for routing alerts to the relevant party.

In our case we use a special label which alertmanager propagates to our alerting system. This label contains the name of an alerting workflow (e.g. send alert to personA in TeamB, if not acknowledged within 30min, send alert to PersonB, etc, etc).

Some way of being able to specify labels on an alert level would make the alertmanager notifier a lot more useful.

**Comment by mambax** [comment]
@wleese did you find any way around this?
Also did you find out (I did not) if you can use template variables inside rule tags?

**Comment by chancez** [comment]
You can specify "taqs" in your alerts which will get sent to alertmanager when the Grafana alert fires. Doesn't that achieve what you want?

**Comment by mambax** [comment]
@chancez Sadly this does not scale as we have this setup:

Helm Chart per Cluster:
- Notifier
--- Here also tags needed

Dashboard as Code, same for each cluster
- Alert with Tags

So, putting tags on the alert will end up having the same tags for all clusters which does not work. For alert routing we need to know the cluster hence we would need tags in the notifier definition :S

**Comment by chancez** [comment]
Ah yeah, that's a bit annoying. I don't have any recommendations for that. Grafana team might, but I suspect it's probably not a problem limited to alerts, but dashboards and datasources as well, and I suspect the answer is something like "template the configs/dashboards/etc".

**Comment by mambax** [comment]
Yeah templating and stuff is definitely on my list.
But you know if you have 1300 graphs you do not add "Grafonnet" easily :D
