### ISSUE TITLE
Explore Log lines component does not handle long labels very well

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15073]
For cassandra there is really long label value `/var/log/pods/3cf9d90d-ed04-11e8-a6ea-42010a8000cc/cassandra/0.log` not sure if this is a bug in loki or not but seems like something the log lines visualization should handle. 

Ideas
* Set a max width for label values
* Remove  white-space: nowrap from .log-labels , does not fully fix it just happens to improve it since the log file path includes a dash so will cause a line break. 
* Set max width for labels column 
* hide labels in split view?  (or at least have a lower max width)? I guess there is  toggle for it so this might not be needed.

@davkal any other ideas?

<img width="1680" alt="screen shot 2019-01-26 at 16 14 01" src="https://user-images.githubusercontent.com/10999/51789071-9d9a1a80-2185-11e9-8a66-1b9be93f74e1.png">

**Comment by davkal** [comment]
Label length has diminishing returns. IMO we can limit individual labels to, say, 20ems with ellipsis.
Re labels in general, I'm more and more in favor of not showing them by default. Leaves more room for the message itself.

**Comment by steven-sheehy** [comment]
This should be fixed via my PR #15737, but please confirm. Main issue was missing `overflow: hidden` and not having a fixed size causes it to never ellipsis-ize. Note that it also fixed it in the panel options too if you were add that long label to your filter.

I do agree though that labels column shouldn't be shown by default.

**Comment by davkal** [comment]
This is indeed fixed. Thanks @steven-sheehy for your contribution 🎉
