### ISSUE TITLE
I have set alerts for Disk usage and now I want set alerts for Memory usage but I am not able to set it is giving error FAILED TO TEST RULE.

### ISSUE THREAD

**Issue by Abhijeet-BK** [grafana/grafana#15074]
I tried to set alert for grafana but it is giving error as mentioned is subject.
 
if anyone want more details then you can find on below link -   https://stackoverflow.com/questions/54346722/i-am-not-able-to-set-alert-for-grafana-graph

**Comment by torkelo** [comment]
What does your query look like and what does the server grafana log say when you get that test rule error?

**Comment by torkelo** [comment]
looks like a network connection issue between Grafana server and your Prometheus server
