### ISSUE TITLE
Remove the Dockerfile in project root in favor of using existing containers/scripts

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#15083]
# Backstory

Last Friday @bergquist noticed that `make build-docker-full` was broken. When I looked into it I found that recent changes to our folder structure meant that not all necessary files were included in the build. The root directory `Dockerfile` is nice because it allows anyone with Docker to build a custom Grafana Docker image of their current work dir. At the same time it is pretty fragile, as it is a separate way to build Grafana that has nothing to do with the builds we use daily.

# Possible solution

We should be able to replace this Dockerfile with scripts that runs our build container to build Grafana and then uses our main Dockerfile to generate an image. This would make it possible to build a Docker image for Grafana locally, with minimal tooling. It would widen the scope of necessary tools for the usage, to `make` or `bash` (both?).

**Comment by xlson** [comment]
I'm not entirely sure what we should do here. One on hand the root Dockerfile is extremely easy to use if any of our users wants to create their own Docker images to test their changes. But at the same time its existence means that any changes we do to the build environment or our main Dockerfile needs to be mirrored in it, which makes it both fragile and problematic from a maintenance standpoint.

**Comment by seanlaff** [comment]
I noticed today curl was in the packaging dockerfile, but not the root dockerfile- threw me for a loop for a bit :P

**Comment by seanlaff** [comment]
My hack was to just add another build stage at the beginning of the prod dockerfile (running the scripts from the `build` stage in circle-ci) that handles creating the grafana tar that the rest of the docker build expects to have. Obviously not a *real* solution to this issue, but incase anybody else wanted to try something similar, here's what it looks like https://gist.github.com/seanlaff/f037041177e174682e78127c4cf574b4

**Comment by xlson** [comment]
@seanlaff Sorry for not responding to this earlier. What you describe is pretty similar to what I think we should do, with the exception that we will most likely start the first container manually instead of using a multistage build. While multistage would be cleaner it means we have to duplicate the logic for the Dockerfile.

**Comment by autoric** [comment]
👋  Hello! Curious if this issue is still relevant, as I see `make build-docker-full` is still broken.

> it allows anyone with Docker to build a custom Grafana Docker image of their current work dir. 

This is me! I would like to build a custom Grafana Docker image with some changes I made locally. It seems like the root dockerfile does not work. What is the best path forward? Can I leverage the existing build scripts? There's a lot here so it's not totally clear to me what the right scripts would be. 

Any guidance is appreciated!
