### ISSUE TITLE
Publish snapshots accessible only via organisation/folder

### ISSUE THREAD

**Issue by MikeTaylorTen10** [grafana/grafana#15085]
Feature request to add the ability to publish a snapshot which is only viewable to members of an organisation, or to allow the saving of snapshots to a specific folder where access can be controlled.

There are two reasons for requesting this:

1. Complex dashboards can take a considerable time to render (for example, we currently have over 100 panels on one of our more complex dashboards).
2. One of our datasources is Cloudwatch. Over time, the Cloudwatch statistics will disappear (for example when old instances are terminated). If we ever need to go back to old dashboards generated weeks or months ago, the AWS Cloudwatch data may have gone. Publishing snapshots is an easy way to get around this.

The big disadvantage of dashboards is that they are publicly visible to anyone who has the URL. Is it possible to add a facility to restrict access to the snapshot either via Organisation or Folder?

Grafana version 5.2.1
Datasources: InfluxDB and AWS Cloudwatch
OS: Ubuntu 16.04

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
