### ISSUE TITLE
//grafana.org/assets/img/logo_transparent_200x75.png

### ISSUE THREAD

**Issue by scopenco** [grafana/grafana#1509]
Hello, if i enable https for grafana dashboard, i see that grafana logo is not accessible, because https://grafana.org/assets/img/logo_transparent_200x75.png show error. Can you fix this?

**Comment by torkelo** [comment]
It was fixed in 1.9.1 #881 , https://github.com/grafana/grafana/commit/d22d8c4905ba8f8479ce4d59266c946b300e5d30

**Comment by allaire** [comment]
@torkelo should the image now point to `public/img/` now? Because the image if 404 broken for me on the latest version

**Comment by torkelo** [comment]
@allaire what version of Grafana are you using?

**Comment by allaire** [comment]
@torkelo Grafana v4.4.1 (commit: 6a9f8ca) !

**Comment by torkelo** [comment]
And where do you see the image that is failing?

**Comment by allaire** [comment]
@torkelo The top image (`img/logo_transparent_200x.png`)

![2017-07-11 at 7 30 am](https://user-images.githubusercontent.com/304461/28066434-e6df7196-660a-11e7-99c1-f85c87f1eeba.png)

**Comment by torkelo** [comment]
That is not the default home dashboard, looks like a custom home dashboard based on a very old home dashboard from old version of Grafana

**Comment by allaire** [comment]
@torkelo Ah, well it looks like the default dashboard on master is pointing to the wrong path as well `https://github.com/grafana/grafana/blob/8f4c797399fcd94baf9f5f5c3c330ea9c0265ecb/public/dashboards/default.json`

The image is located there `https://github.com/grafana/grafana/blob/8f4c797399fcd94baf9f5f5c3c330ea9c0265ecb/public/img/logo_transparent_200x.png`

Maybe I'm missing something?

Thanks for your time

**Comment by torkelo** [comment]
that json file has not been used in years :) Will remove
