### ISSUE TITLE
Explore: no way to retry testDatasource failure

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15096]
Continuation of the problems found in #14976 

Not sure why Explore does a testDatasource call and why this stops the data source switch process from completing. 

It leaves you in a broken state with no way to retry. You only option is to go another page or select another data source then back again. The failure could have been caused by temporary network glitch or network/wifi issue. 

There is no query editor loaded (due to datasourceError stopping the query editors from rendering so easy to fix). But that fix is not enough,  and a lot of the properties that are set in loadDatasourceSuccess action should I think be set when changing datasource and not be dependant on the "test data source flow".  

![2019-01-28_16-46-21_screenshot](https://user-images.githubusercontent.com/10999/51847699-88a3bf80-231c-11e9-9a13-f7196f6f78df.png)

**Comment by hugohaggmark** [comment]
I've taken a short look at this and I think we should decide on how this should be designed before moving forward:
- Should we silently retry for x amount of time and then show reconnect button
- Should we silently retry for x amount of times and then show reconnect button
- Should we just show the message and a reconnect button
![image](https://user-images.githubusercontent.com/562238/54919492-3ab4cd80-4f01-11e9-90c0-287c58bffe76.png)
- Other alternatives

**Comment by Ijin08** [comment]
<img width="1440" alt="Screenshot 2019-03-25 at 13 40 42" src="https://user-images.githubusercontent.com/23470681/54920478-9d0ecd80-4f03-11e9-9dee-78a0112bac83.png">
