### ISSUE TITLE
On a graph, the right Y axis don't show values

### ISSUE THREAD

**Issue by topsurfer** [grafana/grafana#15116]
Please include this information:
### What OS are you running grafana on? Linux

Hello,
I find out that on the right graph no values are shown,  I only see the label-name.
If I switch the (two) datasources, same behaviour:
Now on the left I see the values, and the data source (before fully correct shown on the leyt y axis)  is now on the right; but without values  (label (KWh) is displayed).

In my thread [here ](https://community.grafana.com/t/on-a-graph-right-y-scale-without-values-left-works-fine/13932 )another guy confirm this issue, so it seems like a bug.

![wasser-kwh-right-axis-missing](https://user-images.githubusercontent.com/47141686/51912969-cf092500-23d5-11e9-8a1a-fc9e7671d587.jpeg)

**Comment by marefr** [comment]
Works as expected [here](https://play.grafana.org/d/696nyo_mz/multiple-series-right-y-axis?orgId=1) so will close this.

**Comment by avrhack** [comment]
@marefr I have this issue too - it should not be closed as it is definitely a bug. The right axis is shown on some of my panels but not others, despite assigning series specifically to the right axis.

**Comment by marefr** [comment]
@avrhack added your panel to https://play.grafana.org/d/696nyo_mz/multiple-series-right-y-axis?orgId=1 and modified query and series override. Works as expected for me. Seems you have an error in your series override, if you want to use regex you should write `/value-here/` - it's important to start and end with a slash.

**Comment by avrhack** [comment]
I didn't change the series override - that came straight from what the Grafana did by clicking the colour bar of the series and changing 'left' to 'right'. Nothing more. So this is a serious defect and nothing to do with me using regex as I didn't!

**Comment by marefr** [comment]
@avrhack Thanks. Are you also on version 5.4.3? Out of curiosity is your series returned from datasource as `/data1` or `data1`? Basically what is displayed in the legend for your series. Screenshot would be appreciated.

**Comment by marefr** [comment]
@avrhack please see #11780. There's an open pull request to resolve issue with series name beginning with `/`.

**Comment by avrhack** [comment]
@marefr Brilliant! That's the missing piece; series beginning with '/' is the answer. In this case the data returned from the data source is just data1 to use the example you quoted above, but I then Alias a '/' in front with the Alias you can see in the JSON of '/[[tag_instance]]'.

Always feel happier with these irritating "doesn't always happen" bugs when there's an explanation of the trigger - that way we can be sure it's fixed. Good detective work and thanks for the super-quick responses :)
