### ISSUE TITLE
Docker Build gets stuck on task 21

### ISSUE THREAD

**Issue by mitchhanks** [grafana/grafana#15124]
Please include this information:
### What happened instead? 
Step 21/37 : RUN ./node_modules/.bin/grunt build
 ---> Running in 5469b3be6fac
Version 6.0.0-pre1
Running "clean:release" (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "phantomjs" task

Running "copy:phantom_bin" (copy) task
Copied 1 file

Running "exec:webpack" (exec) task
Starting type checking service...
Using 1 worker with 2048MB memory limit

### Stuck here for 5 minutes or so then:

 Killed
 Exited with code: 137.
 Error executing child process: Error: Command failed: node ./node_modules/webpack/bin/webpack.js --config scripts/webpack/webpack.prod.js
 Killed
Warning: Task "exec:webpack" failed. Use --force to continue.

Aborted due to warnings.
The command '/bin/sh -c ./node_modules/.bin/grunt build' returned a non-zero code: 3

**Comment by mitchhanks** [comment]
Fixed by doing npm install -g yarn and also restarting docker.

**Comment by jimmyjimmykuo** [comment]
Sorry, can you describe more specifically?
I had a same situation when building customized docker image.
Should I rewrite the Dockerfile to install yarn?
Thanks!

**Comment by alanbccoe** [comment]
After wasting all day on this, it can be fixed by using a newer version of the node image to build from - node:12.16 works.

**Comment by Doorer** [comment]
I hava The same situation
[root@83963c28e716 app]# ./node_modules/.bin/grunt build
Version 6.6.2
Running "clean:release" (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "phantomjs" task

Running "copy:phantom_bin" (copy) task
Copied 1 file

Running "exec:webpack" (exec) task
Starting type checking service...
Using 1 worker with 2048MB memory limit
>> /usr/src/app/node_modules/source-map/lib/array-set.js:109
>>   throw new Error('No element indexed by ' + aIdx);
>>   ^
>> 
>> Error: No element indexed by undefined
>>     at ArraySet_at [as at] (/usr/src/app/node_modules/source-map/lib/array-set.js:109:9)
>>     at BasicSourceMapConsumer.<anonymous> (/usr/src/app/node_modules/source-map/lib/source-map-consumer.js:147:67)
>>     at Array.map (<anonymous>)
>>     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/usr/src/app/node_modules/source-map/lib/source-map-consumer.js:146:14)
>>     at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/src/app/node_modules/source-map/lib/source-node.js:86:24)
>>     at SourceMapSource.node (/usr/src/app/node_modules/webpack-sources/lib/SourceMapSource.js:32:25)
>>     at ReplaceSource.node (/usr/src/app/node_modules/webpack-sources/lib/ReplaceSource.js:82:27)
>>     at CachedSource.node (/usr/src/app/node_modules/webpack-sources/lib/CachedSource.js:18:24)
>>     at /usr/src/app/node_modules/webpack-sources/lib/ConcatSource.js:59:50
>>     at Array.map (<anonymous>)
>>     at ConcatSource.node (/usr/src/app/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
>>     at ConcatSource.proto.map (/usr/src/app/node_modules/webpack-sources/lib/SourceAndMapMixin.js:16:15)
>>     at CachedSource.map (/usr/src/app/node_modules/webpack-sources/lib/CachedSource.js:72:47)
>>     at annotateFile (/usr/src/app/node_modules/ng-annotate-webpack-plugin/index.js:36:33)
>>     at Array.forEach (<anonymous>)
>>     at /usr/src/app/node_modules/ng-annotate-webpack-plugin/index.js:53:19
>>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
>>     at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1311:36
>>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>>     at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1307:32
>>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>>     at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
>>     at Compilation.seal (/usr/src/app/node_modules/webpack/lib/Compilation.js:1244:27)
>>     at /usr/src/app/node_modules/webpack/lib/Compiler.js:624:17
>>     at _done (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
>>     at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:56:22)
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1095:12
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1007:9
>>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: node ./node_modules/webpack/bin/webpack.js --config scripts/webpack/webpack.prod.js
>> /usr/src/app/node_modules/source-map/lib/array-set.js:109
>>   throw new Error('No element indexed by ' + aIdx);
>>   ^
>> 
>> Error: No element indexed by undefined
>>     at ArraySet_at [as at] (/usr/src/app/node_modules/source-map/lib/array-set.js:109:9)
>>     at BasicSourceMapConsumer.<anonymous> (/usr/src/app/node_modules/source-map/lib/source-map-consumer.js:147:67)
>>     at Array.map (<anonymous>)
>>     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/usr/src/app/node_modules/source-map/lib/source-map-consumer.js:146:14)
>>     at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/src/app/node_modules/source-map/lib/source-node.js:86:24)
>>     at SourceMapSource.node (/usr/src/app/node_modules/webpack-sources/lib/SourceMapSource.js:32:25)
>>     at ReplaceSource.node (/usr/src/app/node_modules/webpack-sources/lib/ReplaceSource.js:82:27)
>>     at CachedSource.node (/usr/src/app/node_modules/webpack-sources/lib/CachedSource.js:18:24)
>>     at /usr/src/app/node_modules/webpack-sources/lib/ConcatSource.js:59:50
>>     at Array.map (<anonymous>)
>>     at ConcatSource.node (/usr/src/app/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
>>     at ConcatSource.proto.map (/usr/src/app/node_modules/webpack-sources/lib/SourceAndMapMixin.js:16:15)
>>     at CachedSource.map (/usr/src/app/node_modules/webpack-sources/lib/CachedSource.js:72:47)
>>     at annotateFile (/usr/src/app/node_modules/ng-annotate-webpack-plugin/index.js:36:33)
>>     at Array.forEach (<anonymous>)
>>     at /usr/src/app/node_modules/ng-annotate-webpack-plugin/index.js:53:19
>>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
>>     at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1311:36
>>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>>     at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1307:32
>>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>>     at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
>>     at Compilation.seal (/usr/src/app/node_modules/webpack/lib/Compilation.js:1244:27)
>>     at /usr/src/app/node_modules/webpack/lib/Compiler.js:624:17
>>     at _done (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
>>     at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:56:22)
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1095:12
>>     at /usr/src/app/node_modules/webpack/lib/Compilation.js:1007:9
>>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
Warning: Task "exec:webpack" failed. Use --force to continue.

Aborted due to warnings.

**Comment by CptPicard** [comment]
I've got the exact same problem and did what fixed the issue for the OP. Does not seem to work for my case... trying to build the Dockerfile with Grafana 6.7.4.

**Comment by babaMar** [comment]
Same problem here building in AWS, builds fine on local though
