### ISSUE TITLE
Grafana Windows Complied Successfully but not accessible

### ISSUE THREAD

**Issue by mitchhanks** [grafana/grafana#15126]

**Comment by torkelo** [comment]
Did you start the backend?

**Comment by mitchhanks** [comment]
> Did you start the backend?

I followed the instructions at: Run from master

Building the backend
go get github.com/grafana/grafana
cd $GOPATH/src/github.com/grafana/grafana
go run build.go setup
go run build.go build

Frontend
npm install -g yarn
yarn install --pure-lockfile
yarn watch

Also tried: yarn start

It doesn't seem to clearly say how to start the backend?

**Comment by w4tsn** [comment]
After I ran the go build command there is a binary under `./bin/linux-amd64/grafana-server ` which spins up the backend. I'd suppose you'll find something similar on your windows machine. This is not stated in the instructions though and should be state there for new developers not familiar with go-servers.
