### ISSUE TITLE
X-Grafana-Org-Id not works in all concerned requests

### ISSUE THREAD

**Issue by throrin19** [grafana/grafana#15139]
Normally, If I use the header `X-Grafana-Org-Id` in a request using the current org, the request must use the header orgId.

In this requests, the header is simply ignored : 

- /api/folders
- /api/folders/:folderId/permissions

I don't try this in others requests but I think they are not the only ones.

**Comment by marefr** [comment]
Works for me on current master (a21f677): 

```bash
curl http://admin:admin@localhost:3000/api/folders --header "X-Grafana-Org-Id:7" 
```

What Grafana version are you using and how are you sending your request?

**Comment by throrin19** [comment]
The version is the 5.4.2.

But after tests, the problem is in my code. I fix my code and now it works fine :)

Sorry about that
