### ISSUE TITLE
Add weathermap feature to dashboard

### ISSUE THREAD

**Issue by Copse** [grafana/grafana#1513]
We use http://network-weathermap.com/ and it works great but feels about as modern as Windows 98.

I would LOVE a drag and drop weathermap feature. I.E have a couple of interface graphs, add two dummy devices and tie a link between the two, all with fancy colors depending on load and whatnot =)

**Comment by jwhited** [comment]
Check out https://github.com/otm/networkmap.js
Looks to be abandoned but lots of potenetial

**Comment by torkelo** [comment]
Yes, this would be pretty cool to have. 

There already is an issue for this, so will close this one, https://github.com/grafana/grafana/issues/188
