### ISSUE TITLE
ThemeProvider needs to be available from external plugins

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15137]
Theme provider is not in @grafana/ui so external plugins cannot use it. 

Any plugin panel that uses the new named colors will need theme, wonder what the easiest way to provide that is. Maybe we just add theme to PanelProps so not every panel plugin needs to use ThemeProvider ?

**Comment by dprokop** [comment]
According passing theme to plugins, I think this should be injected to very plugin as you suggest. There is a `Themeable` interface already availabll, I'm gonna update it when I'm done with variables migration.
