### ISSUE TITLE
orgId in All API request instead of current org

### ISSUE THREAD

**Issue by throrin19** [grafana/grafana#15138]
Hello,

I think this demand is an important feature for grafana API.

Actually, if you want use the api to create dashboard, change specific org, ... inside your own API, You should use the `/api/user/using/:orgId` before this requests.

In my case, I have an API with *API users* to interact with grafana inside our environment.
this constraint is really blocking if I have concurrent access to the API on different organizations.

The solution, for me, is to pass the orgId to all *current org* request to force specific org instead of current session org.

Of course, the standard case will always be available and the operation will change depending on the desired use.

**Comment by torkelo** [comment]
you can use the header `X-Grafana-Org-Id`

**Comment by throrin19** [comment]
Thanks for this information, I can't see that in all the documentation

**Comment by throrin19** [comment]
After tests, this header not works in this requests : 

- /api/folders
- /api/folders/:folderId/permissions

Is it normal ?
