### ISSUE TITLE
Problem with sum result queries 

### ISSUE THREAD

**Issue by mmarinmartin** [grafana/grafana#15142]
Hi everyone,

I'm trying to make a simple query to sum three subqueries result and calculate a median but I can't get any result, I suppose I'm doing something wrong. This is the SUM query:

**SELECT SUM** ((mean("usage_idle") FROM "cpu") + (mean("load1") FROM "system") + (mean("used_percent") FROM "mem")) **WHERE** ("host" = 'hostname01') AND $timeFilter GROUP BY time($__interval) fill(none)

And the original queries (which are now working) are the next:

#A: SELECT 100-(mean("usage_idle")) FROM "cpu" WHERE ("host" = 'hostname01') AND $timeFilter GROUP BY time($__interval) fill(none)

#B: SELECT mean("load1") FROM "system" WHERE ("host" = 'hostname01') AND $timeFilter GROUP BY time($__interval) fill(none)

#C: SELECT mean("used_percent") FROM "mem" WHERE ("host" = 'hostname01') AND $timeFilter GROUP BY time($__interval) fill(none)

All of them are queries to a InfluxDB.

Many thanks.

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
