### ISSUE TITLE
[Feature Request] Allow more than 2 values for variables

### ISSUE THREAD

**Issue by MikeKulls2** [grafana/grafana#15147]
Currently I can create a variable with a display value and hidden value underneath with some SQL like this (assuming MySQL source):

SELECT FilterName AS __value, DisplayName AS __text  FROM TSDB.IPVersion

This is a REALLY useful feature but it is limited to 2 different values and I have no control over which value will be used where. For example __text is used in the graph title but oddly __value is used in the graph description (tooltip). The __value is also used in the filters which is expected.

What would be an awesome feature is to be able to put as many columns as I liked into the SQL and be able to determine where to use them using syntax like this (assuming my variable is called IPVersion) ${IPVersion:SomeColumn}. This would give complete control as I could use any of the pieces of data in any location.

Reasons this would be useful:
Variables that have a long name, short name and filter
Variables that just have different names for different places in the gui, eg title, tooltip, row title etc
Cases where I need to use the value in more than 1 filter, eg regex, wildcard, etc
Cases where I have a specific value for URLs
Variable values that apply to multiple filters. Eg I have a variable called Region which needs to apply a filter of State and Geographical Area

Note, it would be handy if this applied to custom variables as well as MySQL and other sources.

Answers to relevant questions

**Comment by hugohaggmark** [comment]
Small remark or though: when using this feature then variables shouldn't be able to store options in the Dashboard JSON because that might become huge.

**Comment by maemigh** [comment]
This would be useful for using with repeated panels. For example, with the columns appname:host:service, a single repeated panel would enable me to put appname in the panel title, while the other two are needed for grabbing metrics.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
