### ISSUE TITLE
Created alert won't send mail with problem

### ISSUE THREAD

**Issue by mmarinmartin** [grafana/grafana#15143]
Hi everyone,

I'm trying to generate some alerts which can send e-mails when the condition is accomplished. For example, when I configure a host which has more than 60% CPU load, I want to send an e-mail to a single address with the problem, but after it is generated, it doesn't send any mail.

I've created a "**Testing**" channel in **Notification Channels** with "Email" type and checked all boxes "Send on all alerts", "Include Images"and "Send reminders" every 15min to a single e-mail address.

In "Alert Rules" I see that the testing condition is OK and I see the alert in the panel, but I don't receive any email, so it is not working. Moreover, I get a message with this meesage: 
**CPU Usage alert
NO DATA for a minute
Query returned no data**

Could anyone tell me why it isn't working, please?

Thanks!

**Comment by xlson** [comment]
Hi, could you please add screenshots showing our alert log, and the configuration for your alert?

**Comment by torkelo** [comment]
closing this due to lack of updates
