### ISSUE TITLE
separator for DrillDown variables

### ISSUE THREAD

**Issue by PaulQL** [grafana/grafana#1514]
Hello,

   What separator character should be used while passing multiple variables to a dashboard as “parameters” using “Drilldown/Detail link”?
   (I tried “space”,”coma”,”semi-column”,etc., but everything after first var-varName= seems to be understood to be a value of the first variable)

Thank you for your help,
Paul

**Comment by torkelo** [comment]
use the standard seperator for url query parameters `&`
