### ISSUE TITLE
Explore: context for loki log lines

### ISSUE THREAD

**Issue by CitySim** [grafana/grafana#15140]
### What Grafana version are you using?
Grafana v5.5.0-pre1 (commit: b05e7aa)

### What datasource are you using?
loki

### What OS are you running grafana on?
hosted cloud / loki preview

### What did you do?
check out logs in explore, looking for an error in a specific method. Grafana showed the matching rows correctly. But the error details are logged on the previous rows, so it would have been useful click/select the row to show the context of that row.
like doing `grep -C 10`

**Comment by davkal** [comment]
Thanks for this feature request. This use case has come up before and we're considering it for an upcoming version of Loki. We're currently in the design doc phase and will request comments soon.

**Comment by marefr** [comment]
Fixed by #17097
