### ISSUE TITLE
Feature request: allow table sort on Grafana users last seen.

### ISSUE THREAD

**Issue by olsonnn** [grafana/grafana#15148]
Feature request: allow table sort on Grafana users last seen.

Would be nice to see which users are online.... and its hard to see now...

**Comment by r0yce** [comment]
This would be a nice feature.

I'd also like to request adding a count of those who are logged in as part of this feature as well

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by olsonnn** [comment]
Bummer, such an easy change / request
