### ISSUE TITLE
Row properties problem after 6.0 Beta1 upgrade

### ISSUE THREAD

**Issue by jmgonzalezp** [grafana/grafana#15157]
### What Grafana version are you using?
6.0.0 Beta1
### What datasource are you using?
N/A
### What OS are you running grafana on?
SUSE Linux Enterprise Server 11
### What did you do?
Upgrade from 5.4.0 to 6.0.0-beta1
### What was the expected result?
Open de options for configuring the Row
### What happened instead?
It shows no options, just grey screen
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
rror: [$compile:tpload] Failed to load template: public/app/features/dashboard/partials/row_options.html (HTTP status: 404 Not Found)
http://errors.angularjs.org/1.6.6/$compile/tpload?p0=public%2Fapp%2Ffeatures%2Fdashboard%2Fpartials%2Frow_options.html&p1=404&p2=Not%20Found
    at angular.js:116
    at angular.js:20254
    at angular.js:17051
    at angular.js:17095
    at l.$digest (angular.js:18232)
    at l.$apply (angular.js:18531)
    at angular.js:18832
    at h (angular.js:6362)
    at angular.js:6642

**Comment by torkelo** [comment]
thanks for reporting this! fix incoming!

**Comment by gitgia** [comment]
It seems, that the problem isn't solved, I am using Grafana 6.0.0 Stable with InfluxDB and still can't edit the row properties.

angular.js:14700 Error: [$compile:tpload] Failed to load template: public/app/features/dashboard/partials/row_options.html (HTTP status: 404 )
http://errors.angularjs.org/1.6.6/$compile/tpload?p0=public%2Fapp%2Ffeatures%2Fdashboard%2Fpartials%2Frow_options.html&p1=404&p2=
    at angular.js:116
    at angular.js:20254
    at angular.js:17051
    at angular.js:17095
    at l.$digest (angular.js:18232)
    at l.$apply (angular.js:18531)
    at angular.js:18832
    at h (angular.js:6362)
    at angular.js:6642
