### ISSUE TITLE
time window offset current time 'now' by X value, ex: now-5m

### ISSUE THREAD

**Issue by jwhited** [grafana/grafana#1515]
With multiple targets summed on a single graph the current timeslot of data can look quite skewed until all metrics are collected. This can cause confusion, especially in a NOC environment.

![screen shot 2015-02-23 at 7 40 57 pm](https://cloud.githubusercontent.com/assets/10344482/6341088/9f6390fe-bb94-11e4-8eb8-412ac59c0e75.png)

Support for an offset on the current time can resolve this issue

**Comment by torkelo** [comment]
This is already implemented in master , and will also of course be included in Grafana 2.0 , https://github.com/grafana/grafana/issues/374#issuecomment-71373569
