### ISSUE TITLE
Convert Azure Application Insights datasource to Go

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#15153]
The Azure Monitor datasource plugin integrates against 4 Azure API's.

To support alerting for the Azure Application Insights service, the [datasource](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana-azure-monitor-datasource/app_insights/app_insights_datasource.ts) class for the Azure Application Insights API needs to be converted from TypeScript to Go.

It should be structured in a similar way to Stackdriver: https://github.com/grafana/grafana/blob/master/pkg/tsdb/stackdriver/stackdriver.go

**Comment by kpfaulkner** [comment]
Out of interest, has anyone started this? Tempted to dip my toes into the grafana source code (Go specifically, couldn't Typescript my way out of a paper bag).

**Comment by daniellee** [comment]
@kpfaulkner I have started it on. Aiming to get it into the 6.3 release at the end of June.

**Comment by daniellee** [comment]
Ref to old alerting issue in the plugin repo: https://github.com/grafana/azure-monitor-datasource/issues/11

**Comment by kpfaulkner** [comment]
Started to look at this a while ago. The Azure-sdk-for-go project wasn't (at the time) handling authentication via the API key (in an easy fashion). One of the guys on the team got a way around it but still sounded like it wasn't ready. Started to roll my own calls to the App Insights REST endpoint.   Are you also going that direction?  (merely curious)

**Comment by kpfaulkner** [comment]
If I can help with anything (Go yes, typescript, no) please let me know.

**Comment by kyschouv** [comment]
Is this likely to make 6.3? And will that be launching soon? We'd like to use this for our app insights alerting, but are likely to have to use another method for alerting if this isn't delivered soon.

**Comment by daniellee** [comment]
@kyschouv I started on this but have discovered that Microsoft are changing the API (from the App Insights Public API format to the Azure Monitor API format) which changes the format of the request urls. 

Ref #17880 for an example of the old and new formats.

So this change means we might push this to 6.4 as I'm not sure we want to implement both formats for alerting.

**Comment by kpfaulkner** [comment]
Ahh good to know. Was there any timeline mentioned by MS about the API consolidation?

**Comment by kyschouv** [comment]
What's the timeline for 6.4? This might create extra work for our scenarios...

Although, if you're considering moving to one service principal for access, it'd be nice to be able to use a managed service identity on the Grafana instance to access Azure Monitor (and Data Explorer).

**Comment by daniellee** [comment]
6.4 will be released around the middle of August. Going to be talking more to MS this week and will hopefully find out more about the API consolidation then.

This is now definitely not being released in 6.3 as the beta release for 6.3 is today.

**Comment by kpfaulkner** [comment]
@daniellee thanks for the update

**Comment by kyschouv** [comment]
Is this still looking on track for 6.4?

**Comment by kyschouv** [comment]
Also, would this support alerting on custom queries? Currently about half of our alerts are built on custom queries in app insights.

**Comment by stebet** [comment]
We are eagerly waiting for alerting support for Application Insights as well. Any news on this @daniellee?

**Comment by fhlippinio** [comment]
We would be very happy about that feature too.

**Comment by kyschouv** [comment]
Any update on date on this?

**Comment by ChadNedzlek** [comment]
Hate to pile on the train here, but I'm also curious for any sort of update. It's in the 6.4.0-beta1 milestone, which says it's going to release 9/18, which is a week away. Is this really going to get fixed for then?

My team makes heavy use of Application Insights for monitoring, so without it, we can't use Grafana, though it's a very promising looking solution.

**Comment by kyschouv** [comment]
I'm really disappointed to see this miss 6.4, after missing 6.3. Is this going to be a priority for 6.5, or should we expect it to miss again?

**Comment by sethbacon** [comment]
Agree, this is a blocker for many of us. @torkelo could you at least give us some understanding of the scope of the problem? Perhaps if we understand how much work needs to get done and of what kind, someone in the community might be able to pitch in and help.

**Comment by ChadNedzlek** [comment]
I actually think I've got most of it done in this branch.  https://github.com/ChadNedzlek/grafana/tree/application-insights-backend  It's based off of the existing monitor code. I've got to write up some more tests and do some more verification, but I think the bulk of the work is done.  I'm hoping to update this thread/create a PR in a few days.

**Comment by torkelo** [comment]
That is great @ChadNedzlek :heart: looking forward to PR!

**Comment by ChadNedzlek** [comment]
My work is blocked by: https://github.com/grafana/grafana/issues/19330.

I'm also concerned that https://github.com/grafana/grafana/issues/18668 is going to reset me back to square one.
