### ISSUE TITLE
The first loading page is slow

### ISSUE THREAD

**Issue by erduoxiangshang** [grafana/grafana#15151]
In the latest version, the first time you open the grafana page, the loading time will be long, and the js generated by the front-end package is larger. Is there an optimization solution? Thank you

**Comment by ntting** [comment]
+1

**Comment by zhoumin8023** [comment]
+1

**Comment by torkelo** [comment]
Strange, when I do a full page reload of a Grafana server running in the US it takes about 1s to fully load and show a dashboard. 

What network connection do you have? Grafana builds are optimized, and js is not very large for what Grafana is: 
![image](https://user-images.githubusercontent.com/10999/52042580-ce8b9e00-253d-11e9-96b7-6a8b54ea5f59.png)

**Comment by torkelo** [comment]
if you can provide more detail on what is large & is taking time we might be able to identify your issue.

**Comment by erduoxiangshang** [comment]
Thank you, but in the process of compiling, the command used is yellow watch, the generated app.js file size is 15M, if deployed in the environment, it will load very slowly, is there any other compilation method in the process of deployment? .

![image](https://user-images.githubusercontent.com/29893194/52099658-fb869200-25cb-11e9-8759-0e071884c0b7.png)

![image](https://user-images.githubusercontent.com/29893194/52099605-cbd78a00-25cb-11e9-95d5-4894aed0545d.png)

**Comment by torkelo** [comment]
That is probably a dev build, use npm run build to create an optimized build

**Comment by erduoxiangshang** [comment]
Thank you, the problem is solved.

**Comment by YakobovLior** [comment]
Hello @torkelo, @yening-zy,
I know it's been a while now, but it seems that we have the same issue with Grafana 7.0.1.

![image](https://user-images.githubusercontent.com/33580144/88824297-da0d6300-d1ce-11ea-9305-044d5d5e0736.png)

Can you explain please what do you mean by running **npm run build**?
Where/how should I run it in order to create optimized build for Grafana?
I might be missing something here, but we have installed Grafana with RPM.

Thanks,
Lior

**Comment by torkelo** [comment]
If you download our official builds they are already optimized. Enable gzip could help

**Comment by amankhare94** [comment]
I was facing the same issue. After I enabled gzip from grafana.ini there is a significant improvement.

**Comment by zhoumin8023** [comment]
> If you download our official builds they are already optimized. Enable gzip could help

Probably from what official version to solve this problem?

**Comment by Mokaffe** [comment]
+1

**Comment by lannierose** [comment]
I just upgraded from 6.4.3 to 7.2, both official Docker containers, and 7.2 is much slower - 30 seconds to a minute of bouncing logo before it opens. It is a good thing I like the bouncing logo. I hope my users do too.

**Comment by nadavl-next** [comment]
@lannierose were you able to resolve the slow load login page?
I am also using official docker images

**Comment by lannierose** [comment]
@nadavl-next No.
