### ISSUE TITLE
Grafana 2.0 - Adding a new Datasource can take a long time?

### ISSUE THREAD

**Issue by damm** [grafana/grafana#1516]
Hi,

I built a grafana docker image based off your build.sh (thanks btw!) and got it working however there seems to be a delay when adding a datasource.

When adding my InfluxDB server and clicking Add there was no movement in the ui to acknowledge this.  So I got a few of these in the console log

Adding more Data Sources seems to cause the same glitch but occasionally it just works right and you get the popup that adding the data source was successful and returns you back to the data sources list.  (So it's intermittent)

```
2015/02/24 03:27:15 [datasources.go:96 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.account_id, data_source.name
2015/02/24 03:27:15 [I] Completed /api/datasources 500 Internal Server Error in 1.091088ms
2015/02/24 03:27:22 [datasources.go:96 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.account_id, data_source.name
```

**Comment by torkelo** [comment]
Strange, the error seems to indicate you are adding the the same data source twice. hm..

**Comment by damm** [comment]
@torkelo indeed I did.  I clicked add and it didn't move anywhere; I noticed it looked like the button depressed but with nothing in the console (errors)

So I clicked add a few times; it eventually timed out and tried to load the datasources page and got a timeout as well.  It recovered on it's own after about 90s

**Comment by torkelo** [comment]
@damm very strange, never seen this on http://play.grafana.org/v2  or local 

Have you seen this more than once?

**Comment by damm** [comment]
Yes unfortunately there seems to be some kind of lag.  It's strange as my root is SSD and it's nowhere using a lot of CPU usage.  No high await nothing strange :(

**Comment by damm** [comment]
```text
angular.js?bust=1425430861593:9732 PUT http://localhost:3000/api/datasources net::ERR_TIMED_OUT
angular.js?bust=1425430861593:11496 Object {data: null, status: 0, headers: function, config: Object, statusText: ""}
angular.js?bust=1425430861593:11496 Object {message: "Unexpected error", severity: "warning"}
```

**Comment by damm** [comment]
@torkelo so i moved the backend from sqlite3 to mysql and there's no lag or issues now.  Do you use SQLite3 in production too?

**Comment by torkelo** [comment]
well we are not going to use sqlite3 for large SaaS installs. But it should be fine for 10-50 users, I have used Graphite with sqlite3 in such scenarios in production. 

Very strange, I mean  http://play.grafana.org/v2 is using sqlite3 and have not seen any timeouts. Did you only get it when adding data sources?

**Comment by damm** [comment]
I get timeouts all over to be quite honest; I think it's because I'm using SQlite3 as the session store too... might be locking each other? 

My SQLite3 voodoo is forgotten but i'll take a look at this later tonight and see if I can figure out more.

**Comment by torkelo** [comment]
@damm the session is not stored in sqlite3, either file, redis, memory or mysql

**Comment by torkelo** [comment]
Do have some proxy infront of grafana? What linux distro/version and what cloud provider (if any?),

**Comment by damm** [comment]
@torkelo no proxy or anything, it's a Gentoo Server running at home running Docker (running this in a container (your Dockerfile also))

Go 1.4.1 fresh gopath when I built it so I don't think I have any old go dependencies.

When using SQLite3 adding a datasource or saving Dashboards can be dicey; 1 out of 5 saves works.  Using MySQL I get an occasional unexpected error when trying to save; but not often.

**Comment by torkelo** [comment]
any news on this issue? It is strange, no one else has reported similar behavior

**Comment by damm** [comment]
I've been using MySQL since without an issue.  So if I find anything more concrete other than Database issues I will open another ticket if that sounds good?

**Comment by torkelo** [comment]
ok :)
