### ISSUE TITLE
Replace session storage with distributed cache

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#15161]
To support a setup using Auth proxy and LDAP we need some kind of cache to avoid flooding the LDAP server. Previously the session storage has been used for that but since we want to remove that we should be able to use a distributed cache instead and use the username header as cache key. We should write up and design doc for how to introduce an distributed cache.

Once this has been implemented we should remove all configuration and docs for the old session solution.

**Comment by torkelo** [comment]
related to https://github.com/grafana/grafana/issues/10816 

The biggest challenges with building a caching service is having a workable fallback for setups that single instance & smaller HA setups.

**Comment by bergquist** [comment]
I think I have a reasonable idea for this. Will write up in the design doc later.
