### ISSUE TITLE
Documentation: installation instructions wrong for debian

### ISSUE THREAD

**Issue by pvdh** [grafana/grafana#15162]
The documentation at http://docs.grafana.org/installation/debian/ does not work on debian jessie or ubuntu xenial.

See problem and discussion here:
https://community.grafana.com/t/grafana-moving-to-packages-grafana-com-doesnt-support-architecture-i386/13480/4
https://rainer.sokoll.com/?p=4468
https://askubuntu.com/questions/741410/skipping-acquire-of-configured-file-main-binary-i386-packages-as-repository-x

Please update the documentation accordingly.

**Comment by torkelo** [comment]
Strange, we have not been able to replicate this issue ubuntu 18. Ubuntu downloads the correct amd64 version. 

very strange.

**Comment by torkelo** [comment]
do you have anymore info on this?

**Comment by pvdh** [comment]
I'm not sure I can provide better explanation than the discussion I referenced: https://askubuntu.com/questions/741410/skipping-acquire-of-configured-file-main-binary-i386-packages-as-repository-x

> ROOT CAUSE : Google dropped support for 32-bit Chrome on Linux triggering an error when updating apt in 64-bit systems (with multi arch enabled) ... details here : http://www.omgubuntu.co.uk/2016/03/fix-failed-to-fetch-google-chrome-apt-error-ubuntu
> 
> To confirm you are using 64 bit ubuntu with multiarch enabled issue
> 
> dpkg --print-foreign-architectures
> if it says
> 
> i386
> then you have added 32 bit support, this will list your native arch ... issue
> 
> dpkg --print-architecture 
> if you are native 64 you will see this output so do SOLUTION shown above
> 
> amd64
> 

But don't hesitate to ask specific questions.

**Comment by torkelo** [comment]
so the problem is multi arch enabled? Just not sure what to do, your the only person who have reported this problem. So not sure if's a general problem or not yet (unable to replicate it)

**Comment by ScrewLooseDan** [comment]
I just had the same issue.  The same work-around worked as well.  Ubuntu 18.04 LTS.

```
$ uname -a                                                                                                                                        
Linux drcnuc 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux       
                                              
$ lsb_release -a                                                                                                                                  
No LSB modules are available.                                                                                                                                 
Distributor ID: Ubuntu                                                                                                                                        
Description:    Ubuntu 18.04.2 LTS                                                                                                                            
Release:        18.04                                                                                                                                         
Codename:       bionic    
```
Error message when updating repositories:
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 
 https://packages.grafana.com/oss/deb stable InRelease' doesn't support architecture 'i386'
```

```
$ dpkg --print-foreign-architectures                                                                                                              
i386 
                                                                                                                                                         
$ dpkg --print-architecture                                                                                                                       
amd64        
``` 

This worked around the problem:
```
$ cat /etc/apt/sources.list.d/grafana.list                                                                                                        
deb [arch=amd64] https://packages.grafana.com/oss/deb stable main  
```
I don't remember enabling multi arch, but I guess it's possible. Perhaps a note or hint in the documentation would help for those of us that stumble upon it would help?
