### ISSUE TITLE
Grafana Login to authenticate PHP pages

### ISSUE THREAD

**Issue by Sunil84** [grafana/grafana#15164]
Hello Grafana Team,

Firstly you guys are doing a great job. Grafana is a fantastic tool for visualization and we love it.

We want to combine our newly built Grafana dashboard with our existing PHP dashboard pages. 
In the process of doing so, we have a requirement for user login from grafana login page and authenticate the PHP pages with the same authentication as that of logged in grafana user.

Additionally, we need to store login user data into PostgresDB.

Please suggest the best way to meet this requirement in grafana.

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.2.4 (0bbac5c)
### What datasource are you using?
PostgreSQL
### What OS are you running grafana on?
Freebsd

Thanks,
Sunil

**Comment by torkelo** [comment]
to have single sign on between grafana and your other site use Auth Proxy feature: 
http://docs.grafana.org/auth/auth-proxy/#auth-proxy-authentication

**Comment by Krylanc3lo** [comment]
Hello Sunil,

did you find a way to do so ?

Thank you!
