### ISSUE TITLE
Right scale 

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#15174]
Please include this information:
### What Grafana version are you using?
5.4.3
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Debian
I have wrote on the community but no answer, so I try here
https://community.grafana.com/t/right-axis-get-scale-from-left-axis/13440

Right scale gets its scale from the left.
https://snapshot.raintank.io/dashboard/snapshot/OacRyux1T0XmS4YvTC9Cbnc8ZjIP330F
Anyone seen this before?
Have I made a mistake in the query or setup?
Click on Temp so only temp will be visible, then you will get the correct scale on right side

**Comment by torkelo** [comment]
disable stacking
