### ISSUE TITLE
Stackdriver: no reducers available for distribution type

### ISSUE THREAD

**Issue by AttwellBrian** [grafana/grafana#15179]
Stackdriver distribution types are supported in the heatmap. But there is no way to plot a distribution's P99, P95 or other PXXs like you can in the stackdriver console. The following is a very common use case for us in Stackdriver.

![screen shot 2019-01-31 at 3 41 14 pm](https://user-images.githubusercontent.com/549900/52093044-a8322680-256e-11e9-9000-872f987af2a5.png)

But doesn't seem like it is possible in Grafana since there is no "reducer" option in the grafana stackdriver Graph plugin. :(

**Comment by torkelo** [comment]
Can you describe more what it you want? a reducer in the graph panel? what would it do? is it a stackdriver query api feature we are not supporting?

**Comment by AttwellBrian** [comment]
> Can you describe more what it you want? a reducer in the graph panel? what would it do? is it a stackdriver query api feature we are not supporting?

When you create a graph for a distribution, there are no Aggregators or Reducers. I specifically care about using the P50, P95 and P99 reducers.

**Comment by daniellee** [comment]
The Aggregation field is the same as the Reducer field - we should update the label name to match Stackdriver's UI. There are definitely options there for the percentiles:

![image](https://user-images.githubusercontent.com/434655/52229898-4f3bf880-28b6-11e9-94b9-fb52c3e18bfd.png)

**Comment by daniellee** [comment]
Should mention we have no support for Secondary Aggregations - they are not exposed in the public API for Stackdriver.

**Comment by torkelo** [comment]
So we can close this?

**Comment by daniellee** [comment]
Just want to make that @AttwellBrian can see percentiles in the Aggregation dropdown first.

**Comment by AttwellBrian** [comment]
I don't see the aggregation dropdown :(

Below is the same metric that I graphed above in stackdriver

<img width="1244" alt="screen shot 2019-02-12 at 5 23 07 pm" src="https://user-images.githubusercontent.com/549900/52679743-e7576480-2eea-11e9-9a95-ce4089586b5c.png">

**Comment by daniellee** [comment]
@AttwellBrian and what does it look like in the Stackdriver UI on GCP? 

Any errors in the Grafana server logs or any JavaScript errors in the Chrome console?

Also, which version of Grafana are you using?

**Comment by AttwellBrian** [comment]
> @AttwellBrian and what does it look like in the Stackdriver UI on GCP?

It works great. When I plot it in stackdriver UI I can get dashboard from my first post.

![screen shot 2019-01-31 at 3 41 14 pm](https://user-images.githubusercontent.com/549900/52093044-a8322680-256e-11e9-9000-872f987af2a5.png)

> Any errors in the Grafana server logs or any JavaScript errors in the Chrome console?

I don't see any errors in either.

> Also, which version of Grafana are you using?

I am using `Grafana v5.4.1 (commit: 308c818)`

**Comment by daniellee** [comment]
Can recreate this - will try and get a fix into 6.0.

**Comment by daniellee** [comment]
We have a mapping (which we made through testing as this stuff is not very well documented) but we seemed to have missed Distribution types with metric kind: cumulative. And that seems to be commonly used by OpenCensus.

An example of an incorrect mapping: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/stackdriver/constants.ts#L111-L116

Should be easy to fix if I can figure out what the mapping should be...

**Comment by torkelo** [comment]
updating milestone as this was not cherry picked for 6.0 will be in 6.0.1
