### ISSUE TITLE
Grafana 2.0 unable to add admin

### ISSUE THREAD

**Issue by damm** [grafana/grafana#1517]
So trying a different user I noticed I cannot make that user an admin; thus making me open 2 browsers as I wanted the dashboards in a user; and had to configure the datasources.

:(

![screen shot 2015-02-23 at 7 42 31 pm](https://cloud.githubusercontent.com/assets/1010/6342860/2b3b18aa-bb94-11e4-9b3f-14ad922bc6c9.png)
![screen shot 2015-02-23 at 7 42 35 pm](https://cloud.githubusercontent.com/assets/1010/6342859/2b3abf86-bb94-11e4-9c34-80d9702708f0.png)

**Comment by torkelo** [comment]
Yea, this is missing from the system admin edit user view. Will add soon :)
