### ISSUE TITLE
Multiple options in constant parameter are not passed to query upon dashboard load

### ISSUE THREAD

**Issue by ajohnsonDcntx** [grafana/grafana#15177]
Using Grafana v5.2.4, Prometheus for a data source, and the Amazon Linux 2 AMI for OS.

For a constant variable, tried to include multiple options by using a pipe | :
![image](https://user-images.githubusercontent.com/46452280/52083991-3d78ef00-255e-11e9-94ac-d834c5101447.png)

Expected the query to look for "serviceone" or "servicetwo". But when the dashboard first loads, it only includes the first option (ie service_name = serviceone):
http://grafana:3000/api/datasources/proxy/1/api/v1/query_range?query=sum(container_memory_usage_bytes%7Bjob%3D~%22cAdvisor%22%2C%20service_name%3D~%22serviceone%22%2C%20client%3D~%22Company%22%2Cenvironment%3D~%22prod%22%2C%20host%3D~%2210%5C%5C.9%5C%5C.0%5C%5C.33%7C10%5C%5C.9%5C%5C.0%5C%5C.79%22%7D)%20by%20(instance)&start=1548953355&end=1548964170&step=15

But, if I go back into Variables and select Update for that constant (without changing anything else), both options are used (ie service_name = serviceone OR servicetwo):
http://grafana:3000/api/datasources/proxy/1/api/v1/query_range?query=sum(container_memory_usage_bytes%7Bjob%3D~%22cAdvisor%22%2C%20service_name%3D~%22serviceone%7Cservicetwo%22%2C%20client%3D~%22Company%22%2Cenvironment%3D~%22prod%22%2C%20host%3D~%2210%5C%5C.9%5C%5C.0%5C%5C.33%7C10%5C%5C.9%5C%5C.0%5C%5C.79%22%7D)%20by%20(instance)&start=1548953520&end=1548964335&step=15

How do I get it to load both constant options upon the dashboard load, so manually refreshing the parameter every time isn't necessary?

**Comment by torkelo** [comment]
constant does not support multiple values, if you want multi-valued variable use the custom one, not constant. 

The custom supports multi value defined via csv, then you can select all/some in the dropdown
