### ISSUE TITLE
Stackdriver: Template variables in filters not working

### ISSUE THREAD

**Issue by fastest963** [grafana/grafana#15182]
We're running Grafana 5.4.3. I created a variable $device that I want to use to filter all of the graphs on the dashboard by a particular device. I set up the template variable as so:
![image](https://user-images.githubusercontent.com/112555/52102436-6cb74c80-25ae-11e9-97cb-5610b0a8b078.png)

I thought I could then do:
![image](https://user-images.githubusercontent.com/112555/52102289-bc494880-25ad-11e9-950e-e114238caa74.png)

But the graph shows no data points. It looks like it's sending the variable with `{}` around it:
```
{"from":"1548983617008","to":"1548994417008","queries":[{"refId":"A","intervalMs":10000,"datasourceId":3,"metricType":"compute.googleapis.com/instance/disk/throttled_write_ops_count","primaryAggregation":"REDUCE_MEAN","perSeriesAligner":"ALIGN_DELTA","alignmentPeriod":"stackdriver-auto","groupBys":["metric.label.device_name"],"view":"FULL","filters":["metric.label.device_name","=~","{william-mongo-sessions-ssd}"],"aliasBy":"{{ metric.label.device_name }}","type":"timeSeriesQuery"}]}
```
Specifically: `["metric.label.device_name","=~","{william-mongo-sessions-ssd}"]` when I believe it should just have been `["metric.label.device_name","=~","william-mongo-sessions-ssd"]`

Finally, are variables supported in the template queries? We typically have a hierarchy as so:
![image](https://user-images.githubusercontent.com/112555/52102403-41ccf880-25ae-11e9-8ee2-5b06707964f6.png)
Where selecting zone will filter instances and devices. Selecting an instance will filter devices. I don't see a way in the template query page to add a filter.

**Comment by torkelo** [comment]
Looks like the format is not specified in the replace (interpolation) call: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/stackdriver/datasource.ts#L43 

There is a 3rd optional argument to replace that controls how multi-valued variables will be interpolated. Looks like for filters it should be  `regex` and not the default glob syntax.

**Comment by daniellee** [comment]
Also, it is possible to change how multi variables are concatenated. Docs [here](http://docs.grafana.org/reference/templating/#advanced-formatting-options). In your case it would be:

${device:regex}

But fix coming up that changes the default to be regex for filters.
