### ISSUE TITLE
Panels missing in 6.0.0-beta1

### ISSUE THREAD

**Issue by inmotini** [grafana/grafana#15185]
### What Grafana version are you using?

6.0.0-beta1

### What datasource are you using?

InfluxDB

### What OS are you running grafana on?

Ubuntu 16.04

### What did you do?

Created new dashboard and tried to add panels

### What was the expected result?

Expected to see default panels like in previous version (5.4.2) E.g. clock

### What happened instead?

No panels were available

I installed v5.4.2 again and i saw all the panels correctly

**Comment by torkelo** [comment]
If you click Edit Panel, then go to Visualization tag (panel type selection), then click the dropdown for Visualisation type and specify the clock. 

We hope to improve this workflow so if your not interested in a metrics panel you can jump directly to the visualisation selection tab.

**Comment by inmotini** [comment]
Ah ha. Thanks @torkelo
