### ISSUE TITLE
Missing default postgresql port

### ISSUE THREAD

**Issue by speede05** [grafana/grafana#15189]
### What Grafana version are you using?
6.0.0-beta1
### What datasource are you using?
CloudWatch, ElasticSearch, Azure, MetaQueries
### What OS are you running grafana on?
Ubuntu
### What did you do?
Deploy the new 6.0.0-beta1 image.
### What was the expected result?
It should be updated without any issue with the previous IaC.
### What happened instead?
We got an errormessage regarding the postgresql port:
`t=2019-02-01T09:43:53+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Fail to connect to database: address xyz1234.rds.amazonaws.com: missing port in address"`

After I changed the Grafana config to set up the port numbera after the host (xyz1234.rds.amazonaws.com:5432), it started without any issue.

**Comment by torkelo** [comment]
Can you show your exact config before upgrade? (the db settings)

**Comment by speede05** [comment]
`[database]
max_idle_conn = 2 
max_open_conn = 300 
type = postgres
host = xyz.rds.amazonaws.com
name = dbname
user = dbuser
password = dbpassword`

after the change I added the `:5432` after the host url
