### ISSUE TITLE
Debian armel package fails to install on raspian

### ISSUE THREAD

**Issue by chawkinsuf** [grafana/grafana#15209]
I realize official builds for armv6 is very new, but I have not found any other reports of this issue so I figured I would open one here. I was unable to get it installed using the .deb on a raspberry pi model b (and I assume this is what most people want an armv6 build for).

I think the issue (at least with the dep) is that it's looking for `libfontconfig:armel` but the raspbian repo uses `armhf` as it arch rather than `armel`. In other words, I have `libfontconfig:armhf` installed as armv6 and `libfontconfig:armel` is not available.

Please include this information:
### What Grafana version are you using?
6.0.0 beta 1

### What datasource are you using?
Can't install

### What OS are you running grafana on?
raspbian stretch armv6

### What did you do?
I first simply tried installing the .deb file and encountered an error:
```
pi@raspberrypi:~ $ sudo dpkg -i grafana_6.0.0-beta1_armel.deb
Selecting previously unselected package grafana:armel.
(Reading database ... 80783 files and directories currently installed.)
Preparing to unpack grafana_6.0.0-beta1_armel.deb ...
Unpacking grafana:armel (6.0.0-beta1) ...
dpkg: dependency problems prevent configuration of grafana:armel:
 grafana:armel depends on libfontconfig.

dpkg: error processing package grafana:armel (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (232-25+deb9u8) ...
Errors were encountered while processing:
 grafana:armel
```

However, that package is already installed:
```
pi@raspberrypi:~ $ sudo apt-get install libfontconfig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
libfontconfig1 is already the newest version (2.11.0-6.7).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 grafana:armel : Depends: libfontconfig:armel but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

I tried just ignoring the error using `--force-depends` and the installation completed. However, when trying to run grafana it seg faults:
```
pi@raspberrypi:~ $ grafana-server
Segmentation fault
```

### What was the expected result?
The installation to succeed and the program to run.

### What happened instead?
The installation fails and the program seg faults.

**Comment by xlson** [comment]
@chawkinsuf I think there are two different things going on here. 

## armel vs armhf

Raspbian uses armhf for armv6, but from what I've understood armhf should technically be armv7. I'm not sure what we should do about this. We could do what raspbian does but that would mean that anyone on armv7 would also get the armv6 binaries.

## armv6 not working on raspberry pi model b

I'm guessing his is a compiler issue. Will look into this soon. Would you be willing to retest the binaries after I've made changes?

https://github.com/xlson/grafana/blob/db8f9869078a18ef6fa67a697e5ac22a3c017a18/scripts/build/build-all.sh#L11

**Comment by chawkinsuf** [comment]
Yeah, I can give it a test when you have a new build. I've done a little more reading about the armel vs armhf since my first post. The raspbian builds are called armhf because even though it's armv6, it's a special flavor that has floating point support ARMv6+VFP2. I am a little worried out floating point performance in your builds even if we get them working because they will be missing the +VFP2 part. I'm not even sure if it would be possible to include that with go builds.

Theoretically it should be possible to mix debian armel with raspbian armhf, but it is not a recommended setup. As far as the dependency issue, I am not sure if you can set a requirement for the armel or the armhf package. Otherwise I might be able to install the debain armel version of the dependency. I think I will stick with the binary distribution for now though.

**Comment by xlson** [comment]
Thanks for looking into it. Not sure how to solve armv6, I did try to do an armv5 build instead. Could you check if that works on rpi1? It's only the binaries, so you will have to extract the armv6 tar-ball and then replace the binaries with these [armv5 binaries](https://drive.google.com/file/d/1jHoHl4av6N6IlKqFf6WlSyK7dZe07mQx/view?usp=sharing)

Quite unsure about how to solve the armel vs armhf issue, but can we at least get the binaries working that will be a good start.

**Comment by chawkinsuf** [comment]
That build seems to work fine. I was able to start it up and add a datasource and see some graphs. Theoretically a standard armv6 build should work too. I don't really know what is lost by using armv5 vs armv6.

I'm not too familiar with go or how it compiles, but I did find the c compiler flags that the raspbian builds use to enable hard floating point support with armv6, if you had any interest in trying to make a build specifically for the pi1/pi0 at some point (assuming it's possible).

```
-march=armv6
-mfpu=vfp
-mfloat-abi=hard
```

**Comment by xlson** [comment]
Thank you. It should be possible to further configure the build, I will see what I can do with armv6 build and those flags.

**Comment by chawkinsuf** [comment]
Cool, let me know if you need me to test out new builds. I will note that the armv5 build is running fine. I haven't setup large dashboards though (3 or 4 graphs) and am loading data directly from influxdb, so I am not sure how much I am exercising floating point operations.

**Comment by xlson** [comment]
@chawkinsuf You you try running [this](https://drive.google.com/file/d/1UKusAv2Kz7WRAz9MwY0klRzVEq9NuNx5/view?usp=sharing) build on your raspberry pi? It's built with those arguments you supplied for armv6.

**Comment by chawkinsuf** [comment]
No luck, I get an immediate segmentation fault like I did with the other one.

**Comment by chawkinsuf** [comment]
I could try to load it up in gdb if you wanted to make a debug build, and maybe get more info on where it's crashing. Or maybe an armv5 version will have to suffice.

**Comment by xlson** [comment]
I think the armv5 version might have to be enough for now. While it would be nice to get this right I don't really think there are that many users that really need an armv6 build at this point.

Perhaps I'm proven wrong and in that case we will take another look, or we are lucky and someone who knows more about building for armv6 will take a stab at it.

**Comment by ajaybnl** [comment]
if you got error for dependency error, install the 6.2.2 version. i've problems installing 6.3.3 on rpi4

**Comment by iORichy** [comment]
hi @xlson I just wonder if there are people requested about this issue?
I just run into the same problem: following your tutorial https://grafana.com/tutorials/install-grafana-on-raspberry-pi/#3 but when it comes to install I just get this error
`pi@raspberrypi:~ $ sudo apt-get install -y grafana
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 grafana : Depends: libfontconfig1 but it is not installable
E: Unable to correct problems, you have held broken packages.`

crazy that it does not seem to be possible to install libfontconfig1 at all:
`pi@raspberrypi:~ $ sudo apt-get install libfontconfig1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libfontconfig1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libfontconfig1' has no installation candidate`

is this something (really) needed by Grafana?

I was able to download and install directly via
`curl -o grafana-7.4.0.linux-armv7.tar.gz https://dl.grafana.com/oss/release/grafana-7.4.0.linux-armv7.tar.gz` and start via ./bin/grafana-server but I'm unsure about installation-scripts and system service registration etc.

Thanks for some thoughts and please let me know, if it's just a too stupid comment, so I will delete for sure…

**Comment by xlson** [comment]
@iORichy could you please create a new issue about this problem instead of posting on a closed and unrelated issue? It makes it a lot easier for us to track and hopefully solve it.

As to the need for `libfontconfig1`, I'm not entirely sure to be honest. Let's discuss/dig into it it in the new issue.
