### ISSUE TITLE
request : leaflet dash 

### ISSUE THREAD

**Issue by tecbea** [grafana/grafana#1520]
Hi,
a panel with maps like leaflet will be cool

best

**Comment by mattttt** [comment]
I like the idea of maps a lot. When I envision the data being overlaid, the first thought is some kind of heat map. What other use cases come to mind?

**Comment by JorgeGT** [comment]
Good idea! You could also easily show GPS locations as markers for example (a query that reads `lat = 12.34; lon = 3.141` and then just `var marker = L.marker([lat, lon]).addTo(map);`

**Comment by torkelo** [comment]
Dupisch of https://github.com/grafana/grafana/issues/1088
