### ISSUE TITLE
[BUG] Variable not evaluated when Testing an Alarm Rule

### ISSUE THREAD

**Issue by kalman5** [grafana/grafana#15204]
### What Grafana version are you using?
    5.4.1
### What datasource are you using?
    postgresql
### What OS are you running grafana on?
    linux
### What did you do?
    Run "Test Rule" from an alert
### What was the expected result?
    Query being executed with variables evaluated
### What happened instead?
    Postgresql engine got a query with the variable $test still to be evaluated
\

**Comment by torkelo** [comment]
variables are not supported in alerting queries: https://github.com/grafana/grafana/issues/6557
