### ISSUE TITLE
webdav storage renders public_url  wrong

### ISSUE THREAD

**Issue by chuegel** [grafana/grafana#15213]
Please include this information:
### What Grafana version are you using?
`5.4.3`
### What datasource are you using?
`prometheus node_exporter`
### What OS are you running grafana on?
Ubuntu Bionic
### What did you do?
configured webdav as an external image store
```
url = https:/example.com/Public/prometheus/
public_url = https://example.com/d/1cb7ca2fc4df4af491a4/files/?p=/
username = prometheus
password = *******
```
### What was the expected result?
Expected rendered  `url="https://example.com/d/1cb7ca2fc4df4af491a4/files/?p=/Ag5VVk3n4zW5n3YzcPmu.png" `
### What happened instead?

URL gets rendered to: `url="https://example.com/d/1cb7ca2fc4df4af491a4/files/Ag5VVk3n4zW5n3YzcPmu.png?p=/"`and fails

**Comment by huegelc** [comment]
https://github.com/grafana/grafana/issues/9351#issuecomment-460067328

**Comment by daniellee** [comment]
Missing docs for this option. But this should work:

`public_url = https://example.com/d/1cb7ca2fc4df4af491a4/files/?p=/${file}`

If you add `${file}`, it will insert the filename there instead of at the end of the url.

**Comment by daniellee** [comment]
Closing this but can reopen if that does not fix your problem.

**Comment by huegelc** [comment]
Thanks for your reply.
Well, I already did that. Here´s my config:

```
[external_image_storage.webdav]
url = https://example.com/webdav/Public/prometheus/
public_url = https://example.com/d/1cb7ca2fc4df4af491a4/files/?p=/${file}
username = someuser
password = ****
```
The images are uploaded fine.
Here´s the log output of the alert
```
msg="New state change" logger=alerting.resultHandler alertId=6 newState=alerting prev state=unknown
lvl=info msg=Rendering logger=rendering path="d-solo/NN4z1__iz/node-exporter-full?panelId=281"
lvl=info msg="uploaded screenshot of alert to external image store" logger=alerting.notifier url="https://example.com/d/1cb7ca2fc4df4af491a4/files/sW5Lf05w8oM6xLuS33jq.png?p=/"
lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=6 notification=Slack
```

**Comment by daniellee** [comment]
Did you restart your Grafana server after making the config file change? (Sorry have to ask).

**Comment by huegelc** [comment]
;) yes sure

**Comment by daniellee** [comment]
After testing this locally, the ${file} syntax does not work - it is stripped out when reading from the config file. Not sure if it ever worked or if this is a security fix that was implemented recently.

**Comment by pingooz** [comment]
Issue still exist in Grafana v6.5.2. Can't use ${file} in the public_url

**Comment by MarcBrendel** [comment]
The issue still exists in Grafana v7.5.6 (5fdad5bfe4). The variable is set via the environment using `GF_EXTERNAL_IMAGE_STORAGE_WEBDAV_PUBLIC_URL` with the parameter **`$${file}`**. Logging shows that the setting is definitely applied:

```
lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_WEBDAV_PUBLIC_URL=https://<FQDN>/subfolder/subfolder/?p=${file}"
```

The filename is still just appended after the last `/` as if `${file}` was not configured at all.

Unfortunately I am not a (Go) Developer and cannot provide a fix myself. Using an URL parameter for direct file access is not that uncommon and quite a few cloud storage systems (Nextcloud, ownCloud, Seafile) are offering access via WebDAV. It would be awesome if this issue could be resolved by someone with the necessary Go skillset.

**Comment by daniellee** [comment]
The bug is due to the expansion of environmental variables when loading the config files.

1. `${file}` matches the [regex](https://github.com/grafana/grafana/blob/main/pkg/setting/expanders.go#L45) for an enviromental variable but there is no env var that is named `file` so [this code](https://github.com/grafana/grafana/blob/main/pkg/setting/expanders.go#L122) returns an empty string.
2. The `public_url` config string then has `${file}` [replaced by empty string](https://github.com/grafana/grafana/blob/main/pkg/setting/expanders.go#L107)
