### ISSUE TITLE
Permalink for Playlist

### ISSUE THREAD

**Issue by timtrinidad** [grafana/grafana#1521]
It would be nice to have a permalink for a playlist that can be bookmarked. 

We currently have a TV which has a 4-dashboard playlist - every once in a while, the browser or computer crashes, and it's a task to reload the dashboard, click on open, click on "playlist", and click on "start playlist" every time.

**Comment by torkelo** [comment]
Will be implemented in Grafana 2.1 or 2.2, 

Will close this one as there already is a very similar issue, https://github.com/grafana/grafana/issues/1137
