### ISSUE TITLE
Add panel dialog causes dashboard layout to be broken

### ISSUE THREAD

**Issue by mortenlein** [grafana/grafana#15224]
### What Grafana version are you using?
Grafana v6.0.0-beta1 (d7f81c4) and Grafana 5.4

### What datasource are you using?
N/A
### What OS are you running grafana on?
Docker image (grafana/grafana:6.0.0-beta1)
### What did you do?
Adding a new panel to a dashboard
### What was the expected result?
The Add panel dialog should not move all panels in the dashboard
### What happened instead?
The add panel dialog pushes all the panels below down and then pushes all panels to the right of the dialog up, messing with the layout of the dashboard

I was really hoping this would be adressed in 6.0, as it has a high impact on the Dashboards abilities to be edited without it causing alot of extra steps to get the dashboard back to its original layout.

I've search through the Github issues and the community forum posts, but no other mentions has been found of this annoying bug. This could probably be solved by making the add panel a modal or toying with some css ie. position and z-index which makes it float above the dashboard.

**Additional Info:**

## Browsers with the issue
- Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Microsoft Edge 40.15063.674.0
- Mozilla Firefox Quantum 65.0 (64-bit)
## OS
Windows 10 15063.1563
## Screenshots of bug in this issue

![grafana-1](https://user-images.githubusercontent.com/3304457/52206636-1c284380-287b-11e9-8c0f-18e98837cc86.png)
Dashboard before using the "Add Panel" button

![grafana-2](https://user-images.githubusercontent.com/3304457/52206649-25191500-287b-11e9-8acc-340de6b2b8cb.png)

Dashboard after using the "Add panel" button

Please note that these screenshots have been edited to remove any sensitive information and the panels are not blank in original screenshots.

If any more information is needed, please let me know and i will provide whatever is required.

**Comment by bloodbank** [comment]
On further inspection of this bug you can see that the "add panel" action causes most of the panels to get a bump on the "top:" value in their inline css, but the four panels on the right side stays at "top: 0px;" even after the "Add Panel" is called. If all panels would be included in this function to push everything down accordingly with the show "Add Panel" function you'd fix this issue.

Possible fix would be to make the "Add Panel" be 100% width, pushing all content down while its active and then adding a new panel above everything else, which would not cause the dashboard layout to be skewed.

**Comment by torkelo** [comment]
This is not new bug but a bug that I think has existed in since v5. One of the remaining grid collision issues. 

Could try upgrade grid framework, if that does not work we could modify the way add panel widget is added, so that it is added to the top and manually push position of top row down (modify row position) and everything else down.

**Comment by bloodbank** [comment]
Thanks for the feedback, I suspect as you do, that this could be fixed with some minor tweaks and hopefully you'll find the time to do so in the 6.0 beta.

**Comment by mortenlein** [comment]
Any updates regarding this? Would appreciate it very much if it was found worthy of a future release, thank you.

**Comment by torkelo** [comment]
Action for anyone wanting to investigate this. Try upgrade https://github.com/STRML/react-grid-layout to latest version and see if that helps. If not then we need to modify how we add the "add panel" widget. When we do this we need to move the row & everything else down.

**Comment by tralston** [comment]
Any progress on this issue? Grafana is in v6.3.5 (commit: 67bad72), and it's still a problem.
