### ISSUE TITLE
Error "Panel not found" for panels with id 0

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#15229]
Dashboard is generated by our jsonnet; it displays nicely though.

JSON https://gist.github.com/tomwilkie/7a9551d72149da6209622d47c307f789

**Comment by tomwilkie** [comment]
Only happens for the top-left panel.

**Comment by tomwilkie** [comment]
Grafana v6.0.0-prebeta2 (eb8dfef)

**Comment by tomwilkie** [comment]
Confirmed this is happened for the first panel on all my dashboards.

**Comment by torkelo** [comment]
yea, your dashboards have invalid start value for the panel id. 

This will only affect generated (jsonnet etc) dashboards with a faulty start value for panel id. 

Will try find a migration or correction for faulty models like this so that Grafana can handle them like before.

**Comment by jschill** [comment]
This will be null on panelId 0:
https://github.com/grafana/grafana/blob/310ee5674f4c072bd6dc51d652c4dc81ade22bce/public/app/features/dashboard/services/DashboardViewStateSrv.ts#L48
