### ISSUE TITLE
regex in search query

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1522]
Hi Torkel:

I'm trying to use regex to retrieve hosts from grafana:

I tried this {dc?server[1-6]}, nothting came up.

Any ideas?

**Comment by torkelo** [comment]
I don't think graphite supports regex, it support a glob syntax

**Comment by torkelo** [comment]
or are you talking about Grafana dashboard  search? it does not support regex

**Comment by gsaray101** [comment]
what is glob syntax?

**Comment by torkelo** [comment]
http://en.wikipedia.org/wiki/Glob_%28programming%29
