### ISSUE TITLE
Explore cut & paste adds newline before and after selection.

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#15223]
When cutting and pasting queries in the explore, newlines seem to be added before and after:

![l2hfqicazx](https://user-images.githubusercontent.com/444037/52206253-905de980-2871-11e9-8c48-44513e66fdfd.gif)

Not sure if this happens on cut or paste.

**Comment by torkelo** [comment]
Strange, some weird bug with slate (they text editor component Explore uses)

**Comment by tomwilkie** [comment]
Grafana v6.0.0-prebeta2 (eb8dfef)

**Comment by hugohaggmark** [comment]
It's a bug in Slate, could fix it by upgrading slate to 0.35.0 where I couldn't repro this problem. How do we do with upgrades to dependencies like this?
