### ISSUE TITLE
login username and password verification through postgres database

### ISSUE THREAD

**Issue by mousumipaul** [grafana/grafana#15221]
I am quite new to grafana. I have created some dashboards in grafana. I have a postgres datasource. Now I want to create the authentication part where user will enter username and password and then click on submit button. I have a user table in postgres and I want when user enter the login credential then grafana should check whether those credentials exists in the database. If exists then only it should allow to the dashboards. Like for normal web pages we create the login page and writes the query to check the credentials. In grafana How I can do that???

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Use postgres as Grafana database, see [documentation](http://docs.grafana.org/installation/configuration/#database).
