### ISSUE TITLE
Panel menu items hidden under panel below.

### ISSUE THREAD

**Issue by europemaster** [grafana/grafana#15227]
This is a front-end issue i got on Firefox on Ubuntu 18.04. Haven't seen any similar issue, behaviour didn't change when upgrading from 5.4.1 to 5.4.3

### What Grafana version are you using?
5.4.3
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu
### What did you do?
Open the pop-up menu of singlestat.
### What was the expected result?
To be visible.
### What happened instead?
Singlestat below is placed over the menu, making only view and edit options reachable. See screenshot for clarification. Making the panel below non-transparent does not change anything.

![1](https://user-images.githubusercontent.com/9307783/52208641-9d82d480-2881-11e9-98c9-fb135bed0a1c.png)

 
![3](https://user-images.githubusercontent.com/9307783/52208751-f7839a00-2881-11e9-910b-118161d49e59.png)

**Comment by torkelo** [comment]
Fixed in master / v6
