### ISSUE TITLE
Datasource prometheus doesn't connect (Error 403 or CORS)

### ISSUE THREAD

**Issue by Asgoret** [grafana/grafana#15225]
Hi guys! 

The error is very simple. If you want add datasource as prometheus which work in OKD/Kuber you can't do it because before connect to prom you must logging in OAuth proxy which stays before prometheus....and you can'y do it) Because there is CORS too) So...in version 4.7 there was proxy mode with token, but in 5.0+ there is no proxy and no token...So you can't connect to prom) If you haven't got installation of OKD or Kuber you can use https://github.com/pyToshka/openshift-vagrant for experimentation platform.

I find some workaround but it doesn't work with docker...because if docker reloaded all data will be erased and it's harcode way. (https://community.grafana.com/t/use-bearer-token-to-scrape-prometheus/6794/6) 

Ralaited issues and PR:
https://github.com/grafana/grafana/issues/11391
https://github.com/grafana/grafana/pull/15205
https://github.com/grafana/grafana/issues/14738
https://github.com/grafana/grafana/issues/12556

And some members:
@marefr @DanCech @torkelo @xlson @Hadlock @bergquist @seanlaff 

Github of OAuth:
https://github.com/openshift/oauth-proxy

**Comment by torkelo** [comment]
please open a feature request instead and describe what you want Grafana to do. 

> Datasource prometheus doesn't connect

is not very helpfull

**Comment by Asgoret** [comment]
@torkelo here is PR (https://github.com/grafana/grafana/pull/15205). In old grafana version there was proxy access mode. In version 5.0+ there is no such access mode. Without this option you can't connect new grafana versions to prometheus from OKD or Kubernetes. 

So, the main line of this issue is plz bring back OAuth proxy back or include PR (https://github.com/grafana/grafana/pull/15205) in nearest release.

**Comment by torkelo** [comment]
We have not removed the proxy access mode, it is still there and it is the default mode. Just renamed it to "Server", as many did not understand what was meant by the word "proxy"

**Comment by Asgoret** [comment]
@torkelo ok, then where i need put token? There is no any value named like so

**Comment by torkelo** [comment]
Token? Grafana never had a token datasource setting.

**Comment by Asgoret** [comment]
@torkelo and what is this? From: https://www.redhat.com/en/blog/how-gather-and-display-metrics-red-hat-openshift
![image](https://user-images.githubusercontent.com/30697011/52226379-cf199100-28bd-11e9-97dd-cf57cf40b39f.png)

**Comment by torkelo** [comment]
It’s a setting added in a fork of grafana

**Comment by daniellee** [comment]
Duplicate of #12556 - basically and as this there is a PR for it hopefully we will have this in Grafana soon. Another option would be to use the [Auth Proxy](http://docs.grafana.org/auth/auth-proxy/) feature.

**Comment by Asgoret** [comment]
@torkelo @daniellee 

If you want connect Grafana to Prometheus inside OKD/Kuberenetes (last version deployed as prometheus operator).

Datasource:
```
{
"name": "okd",
"type": "prometheus",
"typeLogoUrl": "",
"access": "proxy",
"url": "https://{prometheus_url}",
"basicAuth": false,
"withCredentials": false,
"jsonData": {
    "tlsSkipVerify":true,
    "httpHeaderName1":"Authorization"
},
"secureJsonData": {
    "httpHeaderValue1":"Bearer {service_account_token}"
}
}
```
Create command:
```
curl --insecure -H "Content-Type: application/json" -u admin -p "http://localhost:3000/api/datasources" -X POST -d "@oauth.json"
```

**WORK ONLY ON 5.4.3**

Date: 04.02.2019
