### ISSUE TITLE
Zooming in by dragging and zooming out farther than 30 minutes breaks graph

### ISSUE THREAD

**Issue by jbondhus** [grafana/grafana#1523]
See video at below link. The graph doesn't display anything after if I zoom in by dragging to select a time range, or if I zoom out by specifying a time range of greater than 30 minutes.

https://dl.dropboxusercontent.com/u/85485311/Persistant/2015/02%20-%20February/Zooming%20Problem.mp4

**Comment by torkelo** [comment]
What version of Grafana are you using and what time series database (graphite, influxdb)?

You seem to be using a really old version of Grafana, please upgrade to 1.9.1. 

In the version you are using you need to set timezoneOffset to correct timezone difference between graphite server and your browser. This was solved by using unix epoch time stamps when sending dates in Grafana 1.7

**Comment by jbondhus** [comment]
Aha. Yes, that's right - I didn't realize it, but apparently the version I installed was from a forked repo. Thanks! That was stupid of me...
