### ISSUE TITLE
Grafana alerts to be scheduled only on weekdays

### ISSUE THREAD

**Issue by deepaakella** [grafana/grafana#15238]
Hi Grafana support Team,

 I am trying to set up alerts for dashboards that I had created to monitor the application parameters only on weekdays from 9-9 and skip the monitoring / alerting on weekends. Can you let me know the process for the same.

Below are the details of the Grafana tool that my application is using :

**Comment by bergquist** [comment]
dupe of https://github.com/grafana/grafana/issues/6592
