### ISSUE TITLE
Show users realname

### ISSUE THREAD

**Issue by hoerup** [grafana/grafana#15230]
Grafana user create has the ability to enter realname / displayedname. And a user may modify it's own name - but that is currently not used anywhere.

In Configuration->Users grafana lists login and email (but not users real name)
In Configuration->Teams->Members grafana lists Login/username and email (but not realname)

Suggestion:
In user list add a column for the user's real name and add the posibility to search on name - and do the same for team members

**Comment by daniellee** [comment]
Totally agree - this would be a good improvement to the admin section of Grafana. We would accept PR's implementing this but let us know first if you are taking this on and we can talk about how the UX should be implemented.

**Comment by khalibartan** [comment]
@daniellee Hi I want to work on this issue.  Can you help me getting started on this one?

**Comment by daniellee** [comment]
@khalibartan that's great!

There is another place where the user name could be searched for: 

Configuration -> Server Admin -> Users

Actually, looking at this, I think the UX for this change will be quite simple. The search field would remain the same but we would need to add another column for the Name in the table as you say in your suggestion.

Any thoughts @Ijin08? This page is not very responsive and does not look great on a mobile. Should we add another column (which will make it worse) or do something else?

![image](https://user-images.githubusercontent.com/434655/52808800-10185f00-308f-11e9-98dc-4b4af75bea11.png)

**Comment by Ijin08** [comment]
I don't think one more column is a problem. The problem with columns not fitting on small screens won't be solved by squeezing them together so the amount of columns doesn't matter. 
Currently login name column in Team members list is simply named Names. Should then probably be renamed to Login to be consistent. 

So go ahead and add that column!

**Comment by woodsaj** [comment]
currently only the "grafana Admin" api calls (`/api/users/*` ) return the `name` field.  I think it should be returned for all user api calls.  eg
`/api/org/users`

**Comment by eleijonmarck** [comment]
@woodsaj @ljin08 made a first draft of handling `/api/org/users/` let know you if we should continue or we can put it on hold
