### ISSUE TITLE
Graphite Query editor breaks queries when editing (using graphite with tags)

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#15237]
Please include this information:
### What Grafana version are you using?
v5.3.4 but reproduced on v6.0.0-beta1

### What datasource are you using?
Graphite

### What OS are you running grafana on?
RHEL 7.3

### What did you do?

Add a function as #A and use the `group` function in #B. Continue adding functions (like aliasByTags). 

### What was the expected result?

Query continues to work and generates the right text:

![expected_graphic](https://user-images.githubusercontent.com/5024860/52230859-724eb400-2886-11e9-8957-23ff1ab28bd0.png)
![expected_text](https://user-images.githubusercontent.com/5024860/52230861-724eb400-2886-11e9-9121-cfd71bfb6e08.png)

### What happened instead?

The #A text gets moved into the `seriesByTag` expression, instead of into the `group` expression. `group` expression in graphical mode loses it's #A (e.g. `group(#A)` becomes `group()`)

![actual_graphic](https://user-images.githubusercontent.com/5024860/52231057-ebe6a200-2886-11e9-9164-8111ff1ddf37.png)
![actual_text](https://user-images.githubusercontent.com/5024860/52231056-eb4e0b80-2886-11e9-8e34-06e6733e7cfc.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Query that gets sent shows the nested `seriesByTag` calls: 
```
"target=aliasByTags(group(seriesByTag(seriesByTag('namespace%3Dos'%2C%20'cluster%3Dlxfsrv'%2C%20'name%3Dcpu.percent.idle.g')%2C%20'namespace%3Dos'%2C%20'cluster%3Dlxfsrv'%2C%20'name%3Dcpu.percent.nice.g'))%2C%202%2C%20'host')&from=-6h&until=now&format=json&maxDataPoints=826"
```

**Comment by torkelo** [comment]
fixed in upcoming v6.1
