### ISSUE TITLE
Creating Cell Hyperlink based on Data

### ISSUE THREAD

**Issue by Ajaysrndpt** [grafana/grafana#15248]
It would be very nice if the hyperlink feature in grafana is extended  based on the data set.

For Example:

A regex can be provided to only create hyperlink for the dataset which has match to certain criteria.

Example if the Data set has Three records

Column A
A1
A2
A3 

Then hyperlink should only be applied to A1 and A3 based on Regex or conditions
Please include this information:

**Comment by bergquist** [comment]
You can create links based on the data in the table panel. 

ex  https://play.grafana.org/d/000000031/table-panel-showcase?panelId=10&fullscreen&edit&orgId=1&tab=column%20styles

We dont support only rendering links that matches a regex and I dont see us supporting such niche feature either. Any chance you can filter away rows that you dont want links for in the query?

Closing this issue for now.
