### ISSUE TITLE
Gauge multi series mode

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15244]
If the gauge panel gets multiple series it should repeat itself (the gauge) in a horizontal or vertical direction. 

New options
* Multi series mode: Repeat or combine

Repeat mode
* Direction: auto, vertical or horizontal. 

In repeat mode, each gauge will need a title (series name) above the gauge. 

The thinking here is that this multi-series/repeat behavior & options is going to be the same for singlestat, gauge, bar gauge, traffic light (or some other single stat viz)

**Comment by kentchung** [comment]
SingleStat works with this and Gauge does not currently, which looks like a bug?

**Comment by torkelo** [comment]
No, singlestat does not support multiple series
