### ISSUE TITLE
grafana dashboard time interval is always minimal 15s instead of 5s

### ISSUE THREAD

**Issue by stephencheng** [grafana/grafana#15242]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.3.2
### What datasource are you using?
prometheus
### What OS are you running grafana on?
OSX using docker
### What did you do?
Use a gauage metric and I generate a metric every 5s
### What was the expected result?
I am expecting there is a data point in grafana every 5s, even I use auto refresh every 5s, grafana still shows 3 bars of data, that is 15s instead
### What happened instead?
grafana still shows 3 bars of data, that is 15s instead
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![image](https://user-images.githubusercontent.com/1396675/52256309-4c9adb00-296a-11e9-8f68-292364f1d1c8.png)

**Comment by daniellee** [comment]
Can you show your Prometheus query - it sounds like you might have an incorrect [range vector selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#range-vector-selectors).

**Comment by torkelo** [comment]
or your prometheus scrape interval settings is not set, the data source settings page in grafana  It defaults to 15s

**Comment by storenth** [comment]
@torkelo right) I faced with the same issue: prom's scrape_interval and grafana's refresh was set to 10s but dashboard still auto refreshed in 15s. So, I put `interval` under grafana's dashboard and its work!
<img width="1312" alt="Screenshot 2024-07-02 at 21 53 08" src="https://github.com/grafana/grafana/assets/18244131/00dd88eb-eaa4-4173-88fa-646bb58c9123">
