### ISSUE TITLE
Enhancement - Finding / Managing Large numbers of Dashboards

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#15257]
Our company has 3,000+ dashboards in over 500 folders.  When users try to find a dashboard that will help them identify the root cause of a problem they are basically out of luck.  For example, they know the names of the business or product area which is having a problem.  Mapping that to one or more dashboards that are relevant is basically impossible because the product area is not part of the name of the dashboard or folder.  In addition, the proliferation of copies of dashboards, with slightly different names or the same name but different folder makes finding the official version of dashboards very, very hard.

What we are proposing is to use meta-data/attributes of the dashboard to facilitate identification of dashboards that are relevant using autocomplete and searching with ranked results based on the information available.

The following defines some of the attributes that we believe should part of the ranking system, and where appropriate visible to the end-user. In the search results.

1. Dashboard Name
2. Dashboard Folder
3. Dashboard Description - this should also be visible, in some way, when one loads the dashboard.  It could be a tool-tip, etc.
4. Tags associated with the Dashboard - Tags should only be copied if the user confirms that they want to copy them.  By default tags should not be copied.  Copying them simply diminishes the value in scoring the search results.
5. Panel Names - potentially helpful meta-data for specific info being displayed
6. Row Names - potentially helpful meta-data for specific info being displayed
7. Hits / Usage of the Dashboard - the number of times that dashboard was loaded, don't count auto-refreshes.
8. Last Updated date - an indication that the dashboard is being maintained
9. State - Dashboards should have an explicit state (separate from tags) to help with the rank search results (e.g. DEV, TEST, BETA, PRODUCTION).  By default, when first creating a new dashboard or cloning a dashboard (save as) - the DEV state should be set.  This should be clearly visible on the dashboard when viewing it.  Production dashboards are far more important than the others.
10. Official indicator - with so many dashboards, even with the Production State, we will still have challenges.   We would like to have an Administrator only setting where we can indicate that this is an Official dashboard which will set it apart and clearly identify it.  For example we have a service infrastructure that publishes generic metrics for all applications that use the framework (~10,000 different apps).  We have a generic dashboard that can be used to display the metrics for any service.  Many teams clone this dashboard (there are 100s of copies) and either tweak the display or hard-code the template variables to suit their needs.  Each of the clones are Production from their point of view... But there is only one official copy.

We would propose the following:

Attribute | Part of Search | Visible to End-User
-- | -- | --
Dashboard Name | Phase 1 | Yes
Dashboard Folder | Phase 1 | Yes
Tags | Phase 1 | Yes
State | Phase 1 | Yes
Official Indicator | Phase 1 | Yes
Description | Phase 2 | Yes
Hits / Usage | Phase 2 | No
Panel Names | Phase 3 | No
Row Names | Phase 3 | No
Last Update Date | Phase 3 | No

**Comment by bergquist** [comment]
Thank you for a great write up. 
Lots of great ideas on how to improve this experience.

**Comment by shalstea** [comment]
After thinking about the problem of dashboard copying (e.g. save as).. it really is broader in scope in that one should prevent (or make optional) the automatic copying of fields that drive the meta data in search.  Looking the proposed list of fields above I would then suggest:

1. Tags - copy only if user explicitly say copy
2. State - set to DEV for the copy
3. Official Indicator - make sure this is NEVER set on the copy
4. Description - copy only if user explicitly says copy (blank otherwise)

Given this one might change the Save As workflow to allow the user to see not just choose the directory name and file name, but also to copy over or add tags (by default cleared) and copy/edit the description.

**Comment by sgupta250** [comment]
These make a lot of sense - I agree, we should ask users to carefully consider whether they really need to copy a dashboard or not. We really need to investigate why people are copying so many dashboards without seemingly making many changes to them. 

I have not researched this issue (copying) directly. However, I think two of my other findings are related, and might be why people are copying so many dashboards without modifying them much (this is all conjecture btw)

1. People have been asking for a playground to test changes
This may be one reason they copy - they might be scared of making changes to an official dashboard and messing it up for others, so they make a copy. 

2. People find it very hard to find dashboards
People might be making copies to organize dashboards in their grafana folders? Or maybe they put in some keywords or tags that they can remember to search by next time. 

If we address some of the underlying problems, we might solve this issue indirectly. I will include this in my next round of research.

**Comment by torkelo** [comment]
Thanks for submitting this. Some really great suggestions here ranging from easy to very hard (& requiring special search db's / indexing)

**Comment by bergquist** [comment]
I wonder if it would make sense to allow Grafana to use alternative search engines. Solving this for large setups is very different from smaller or medium-sized ones.

**Comment by shalstea** [comment]
Maybe this effort should be split into three, parts.  The first part (and hopefully simpler) would be adding some basic dashboard management improvements and this would include:

1. Showing the dashboard description in your search and as a tooltip on the dashboard
1. Supporting a dashboard state (dev, test, and prod).  Always default to dev.
1. Supporting an official indicator.
1. Not copying tags, description, state or official indicator on copy/save-as.

What this would do is make the current system better, with more accurate data.  

Phase 2 would be to build the search tool, bootstrap with elastic with basic text search on title, folder, tags and description, rank by official indicator and state.  

Then phase 3 make utilize hits and more sophisticated rankings, more data integrated into it.

My 2-cents on an approach.  Getting phase 1 out would be very helpful for us.

**Comment by sgupta250** [comment]
Here's a link to the design explorations file I showed in the conference call on 2/14
https://www.figma.com/file/cQnW0w6ZaUcCOVFe6THM9fSE/Grafan-Discovery-Ideas?node-id=0%3A1

This is a live link and will be up to date with any design changes

**Comment by torkelo** [comment]
Something that has not come up before that could be useful, not sure where & how to present it but to save the original uid when you save a copy of a dashboard. That will give Grafana some info that a dashboard is a copy of another. And present (somewhere) a link the original, even show some tree of the full heritage.

**Comment by shalstea** [comment]
The history / versions could be sufficient.  I don't know if it is that important or not but it would probably be nice to have in the audit-trail.

**Comment by shalstea** [comment]
I want to think about this a bit more but I believe we can fold in the official setting into the dashboard state.  So you can have a single attribute. Here are some details, in order of precedence on searches.  Dev being lowest, Official being the highest.

1. **Dev** - default state, in development.  Would be lowest priority for matches.  All save as operations would be marked Dev.
2. **Test** - implies that the dashboard is being worked on with the intention of being moved to prod once reviewed and tested.
3. **Production** - implies that the dashboard is in production and should be considered as important.
4. **Official** - this is the master copy of a production dashboard.  Only admins should be able to set this.  This is to differentiate the multiple production dashboards with similar names/attributes.

**Comment by shalstea** [comment]
I split off the dashboards states into a separate issue, as one could deliver this without addressing all the other issues.  See https://github.com/grafana/grafana/issues/15721

**Comment by amy-super** [comment]
Hello Grafana community! I'm investigating design improvements to folder management and navigation in Grafana and I would love your help. [Schedule 30 minutes with me](https://ethn.io/38442) to share your feedback and see some early design ideas.
