### ISSUE TITLE
Limit the length of labels in the Loki table view

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#15264]
We always include the filename, which tends to dominate the screen.

Perhaps limit the length, and truncate the front part off, with a tooltip for the whole label?

<img width="1392" alt="screenshot 2019-02-05 at 19 50 38" src="https://user-images.githubusercontent.com/444037/52300369-93df9680-297f-11e9-978f-3bfdc8376a0d.png">

**Comment by torkelo** [comment]
I already created an issue for this last week :) 
https://github.com/grafana/grafana/issues/15073
