### ISSUE TITLE
pq: invalid input syntax for integer: \"true\"

### ISSUE THREAD

**Issue by qhartman** [grafana/grafana#15267]
### What Grafana version are you using?
5.4.3
### What datasource are you using?
Graphite, Cloudwatch
### What OS are you running grafana on?
Linux
### What did you do?
Migrated from sqlite to postgres using sequel tool. No errors were reported. 
### What was the expected result?
Everything would work with no new errors
### What happened instead?
Everything seems to work, but the logs are getting loaded with frequent errors like:
```
t=2019-02-05T21:28:44+0000 lvl=eror msg="Failed to get system stats" logger=metrics error="pq: invalid input syntax for integer: \"true\""
```

I see another person saw this late last year: https://community.grafana.com/t/migration-sqlite-to-postrgessql/10393/2

But no solutions have been presented.

**Comment by qhartman** [comment]
Just dug this error out of the postgres logs that would seem to correlate:
```
2019-02-05 21:48:44 UTC:10.0.1.34(51096):grafana@grafana:[6682]:ERROR: invalid input syntax for integer: "true"
2019-02-05 21:48:44 UTC:10.0.1.34(51096):grafana@grafana:[6682]:STATEMENT: SELECT (SELECT COUNT(*) FROM "user") AS users,(SELECT COUNT(*) FROM "org") AS orgs,(SELECT COUNT(*) FROM "dashboard") AS dashboards,(SELECT COUNT(*) FROM "data_source") AS datasources,(SELECT COUNT(*) FROM "star") AS stars,(SELECT COUNT(*) FROM "playlist") AS playlists,(SELECT COUNT(*) FROM "alert") AS alerts,(SELECT COUNT(*) FROM "user" where last_seen_at > $1) AS active_users,(SELECT COUNT(id) FROM "dashboard" where is_folder = $2) AS folders,(
SELECT COUNT(acl.id)
FROM "dashboard_acl" as acl
inner join "dashboard" as d
on d.id = acl.dashboard_id
WHERE d.is_folder = $3
) AS dashboard_permissions,(
SELECT COUNT(acl.id)
FROM "dashboard_acl" as acl
inner join "dashboard" as d
on d.id = acl.dashboard_id
WHERE d.is_folder = $4
) AS folder_permissions,(SELECT COUNT(id) FROM "dashboard_provisioning") AS provisioned_dashboards,(SELECT COUNT(id) FROM "dashboard_snapshot") AS snapshots,(SELECT COUNT(id) FROM "team") AS teams
```

**Comment by qhartman** [comment]
oh, actually, login is broken. It just seemed to work because I had valid session cached it seems...

**Comment by qhartman** [comment]
Ok, it looks like when the sequel tool migrated the data it needed to cast some data types to booleans but did bigint instead. I'm going to have to start this over and see if I can come up wit ha process. If anyone knows a way to get this going correctly, I'd love to hear about it.

**Comment by bergquist** [comment]
I suggest you follow https://0x63.me/migrating-grafana-from-sqlite-to-postgresql/

Im closing this issue since its not related to a bug/feature of grafana.
