### ISSUE TITLE
Enhancement Request: Support grouping values into columns on tables by matching tags in graphite

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#15279]
See https://github.com/grafana/grafana/pull/10050

That seems like support is almost there, but not for the graphite datasource. 

### What Grafana version are you using?
v5.3.4 and v6.0.0-beta1

### What datasource are you using?
Graphite (via MetricTank), with tags

### What OS are you running grafana on?
RHEL 7.3

**Comment by shanson7** [comment]
Trying to use the grafana 7 beta "Transforms" to do this. 

Something like:
|User  | Num Requests | Request Duration|
|---|---|---|
|user1 | 35      | 14.15 s |
|user2 | 334        | 2.99s |

I have MDP set to 1, so that I get a single datapoint per series already. The request/response looks like this:
https://gist.github.com/shanson7/ec5245bc8e4f705737f3330a5142a5ec

I've tried using labels to fields and outer join on `userName` but it seems that the labels/tags with the same names (`name` and `Value`) are conflicting.

**Comment by torkelo** [comment]
that example does not include a group by, on a call you mentioned having data center and server (I think), and wanting to group by multiple columns and then get the max value. Can you provide an example for that scenario as well?

**Comment by shanson7** [comment]
> that example does not include a group by

It is grouped by `User`. This request isn't for grafana to do a SQL like "Group By" calculation, but to allow multiple *independent* metrics be represented in a column joined on 1 or more "labels" to form a row key.

**Comment by torkelo** [comment]
So this is what the current labels to fields transform results in 

![Screenshot from 2020-08-20 12-17-38](https://user-images.githubusercontent.com/10999/90758355-2e43c880-e2df-11ea-97d6-85ef1f71be18.png)

Not sure how a group by get's what your after. Looks like you want label values to be fields (column headers), which I not sure I understand how that can work. 

@ryantxu any ideas for a transform that can do this? 

The data looks like this
DataFrame:1
Time
Value (Name="Num Requests", userName="user1")

DataFrame:2
Time
Value (Name="Num Requests", userName="user2")

DataFrame:3
Time
Value (Name="Request Duration", userName="user1")

DataFrame:4
Time
Value (Name="Request Duration", userName="user2")

Tricky to get this to: 

|User  | Num Requests | Request Duration|
|---|---|---|
|user1 | 35      | 14.15 s |
|user2 | 334        | 2.99s |

**Comment by torkelo** [comment]
Think some kind of pivot operation is what we need?

**Comment by shanson7** [comment]
I can tell you how it works with the BoomTable. In the boom table you can define a key per pattern (based on delimiter-node indexing, but would prefer label names). Then it  joins all the patterns into columns where the key matches.

**Comment by torkelo** [comment]
and also related to #14814

**Comment by torkelo** [comment]
Merged the PR, you can test this in nightly builds. 

Will create a follow up PR with refinements and docs
