### ISSUE TITLE
Can't reach a folder's page with a uid only link anymore. 

### ISSUE THREAD

**Issue by MachEleven** [grafana/grafana#15270]
Please include this information:
### What Grafana version are you using?
6.0-prebeta2

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
On dashboards I have links directing the users to the parent folder of the dashboard where they can find other relevant dashboards.
For links only the folder uid is used without a slug for the reason that the folder name may change. 
An example link: 

> /dashboards/f/301xflymk/

### What was the expected result?
Uid only links used to work until 5.4.3 for folders without the slug.  

### What happened instead?
Uid only links now returns an empty page.

**Comment by bergquist** [comment]
I can confirm that this is not working on 0be43948e2cab8685714e9ee93d085fc069e0501
