### ISSUE TITLE
Cannot play a playlist

### ISSUE THREAD

**Issue by ARH-Digital** [grafana/grafana#15273]
What Grafana version are you using? 5.4.3

What datasource are you using? Cloudwatch

What OS are you running grafana on? Debian Stretch

What did you do? Created 2 similar dashboards and attempted to make a playlist with them

What was the expected result? Playlist should cycle between dashboards at the specified interval

What happened instead? When starting a playlist, the screen is blank, apart from navbar and footer

Include raw network request & response: Two responses are obtained 

1: ``` {"id":1,"name":"OSE","interval":"1","items":[{"id":5,"playlistid":1,"type":"dashboard_by_id","title":"Campdraft","value":"4","order":1},{"id":6,"playlistid":1,"type":"dashboard_by_id","title":"Louenhide","value":"7","order":2}]}```

dashboards: ```[{"id":4,"slug":"campdraft","title":"Campdraft","uri":"db/campdraft","order":1},{"id":7,"slug":"louenhide","title":"Louenhide","uri":"db/louenhide","order":2}]```

Console
 ````
Error: Invalid interval string, expecting a number followed by one of "Mwdhmsy"
    at Object.describe_interval (kbn.ts:196)
    at Object.interval_to_ms (kbn.ts:207)
    at panel_header.ts:24
    at angular.js:17051
    at angular.js:17095
    at l.$digest (angular.js:18232)
    at l.$apply (angular.js:18531)
    at angular.js:18832
    at h (angular.js:6362)
    at angular.js:6642 "Possibly unhandled rejection: {}"

````

**Comment by torkelo** [comment]
Specify a time interval in the playlist, like 5m to switch dashboard every 5 minutes, or 30s to switch every 30 seconds

**Comment by ARH-Digital** [comment]
Apologies, I had missed the unit off the end I thought I had checked this :(
