### ISSUE TITLE
Different customizable timerange for dashboard and panel view

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#15274]
It would be nice to be able to define the Quick ranges of the Timerange and be able to have one set of Quick ranges for the Dashboard view and one for Panel view.

The reason for this is that with dashboards with a certain amount of panels or if some panels have query which fetches a lot of metrics you can easily overload your datasource and crash it if the Timerange set is too large (happens a lot with prometheus).

With this I'd like to be able to configure narrow Quick ranges for the dashboard view (and disable the custom range) and a wider ones for the panel view so that if a user require more timerange he needs to switch to panel view.

### What Grafana version are you using?
5.4.3
### What datasource are you using? 
Prometheus

**Comment by torkelo** [comment]
closing as it's similar to ttps://github.com/grafana/grafana/issues/2417

**Comment by sylr** [comment]
@torkelo Not really, I need to enforce a list of Quick Ranges not add Custom Ranges like in #2417

Also I would need to have different Quick Ranges deending on the view.
