### ISSUE TITLE
Re-work theme variables 

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#15276]
Currently we use component specific variables in our theme variables files. 
The variables are also used quite liberally. For example $panel-bg is for all sorts of backgrounds and borders. 

The idea is to use fewer high level variables. This will be easier to maintain and also easier 

To do:

- [x] Remove unused variables and align the theme files. 
- [ ] Create and implement a limited amount of variables for backgrounds that will replace the old component variables.
- [ ] Create and implement a limited amount of variables for borders that will replace the old component variables.
- [ ] Create and implement a limited amount of variables for text color that will replace the old component variables.
  
More to come...

**Comment by dprokop** [comment]
Related to #15235. See https://github.com/grafana/grafana/pull/15235/files#diff-23c6d0f810463303e37f751e4a8ba653 for `GrafanaTheme` type v1.

**Comment by torkelo** [comment]
Closing this as no one is currently working on this
