### ISSUE TITLE
Going to Explore from Dashbord panel keeps step & legendFormat

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15281]
When going from dashboard panel to explore for a prometheus query the legendFormat & step options are kept but there is no options for that in the QueryField in explore so after changing the query the legend will be wrong (Say you change the group by label). 

Replicate: 
1. Dashboard panel with query that groups by label AAA, and legendFormat `{ AAA }`
2. Go to Explore via panel menu, change query group by to something else, legend now all say AAA for every series name. 

Think we should clear step & legendFormat somehow in Explore for prometheus. Question is where, can we do it in PromQueryField?

**Comment by tomwilkie** [comment]
I think the page title is also kept.

**Comment by jschill** [comment]
We could strip these two parameters from the explore-url by modifying `getExploreState()`. That will not touch any other datasources than prometheus.
https://github.com/grafana/grafana/blob/5b1cf9c94fdcd4a73a2f47ad2d36d95c582acc47/public/app/plugins/datasource/prometheus/datasource.ts#L393

Something like this:

```
const expandedQueries = queries.map(query => ({
  ...query,
  expr: this.templateSrv.replace(query.expr, {}, this.interpolateQueryExpr),

  // null out values we don't support in Explore yet
  legendFormat: null,
  step: null,
}));
```
