### ISSUE TITLE
Place reasonable limits on number of panels and series

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#15285]
### What Grafana version are you using?
Grafana v5.4.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Debian 9

### What did you do?
Accidentally mistype a query inside the graph panel or dashboard variable with repeating panels, returning many more series than anticipated.

### What was the expected result?
Grafana places a reasonable limit on the number of panels or series, giving me an error message and saving my day.

### What happened instead?
My browser locked up and computer fan started roaring because grafana tried to draw ~10k panels. Since I can't easily load the dashboard again to fix my mistake, I need to delete my beautiful dashboard and recreate it.

**Comment by torkelo** [comment]
yea, panel & row repeats should probably limit to 100 panels .

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
