### ISSUE TITLE
Tags are not being added to OpenTSDB Requests

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#1528]
![image](https://cloud.githubusercontent.com/assets/1692624/6386501/7a15a062-bd47-11e4-9241-9d523d02ba79.png)

![image](https://cloud.githubusercontent.com/assets/1692624/6386509/a06491b0-bd47-11e4-97b4-196d74b7e3bb.png)

**Comment by torkelo** [comment]
Sorry :( The OpenTSDB metric editor is not so great, will be improved in Grafana 2.0. 

You have to hit the plus icon a second time to add the tag to the query. Super unintuitive I know!  

I slighly improved OpenTSDB editor in Grafana 2.0 (in develop branch), 
![image](https://cloud.githubusercontent.com/assets/10999/6387450/a3af628e-bd8b-11e4-860a-e632fba2a08f.png)

After you hit the plus icon, an "add tag" link is shown to help (a little) to make it clear you need to click it to "commit" the tag to the query.
