### ISSUE TITLE
Browser freeze when graphite annotations endpoint returns unexpected data

### ISSUE THREAD

**Issue by Peter-Sh** [grafana/grafana#15283]
### What
Browser is freezed for a long time (~30 seconds and more) while loading dashboard page in grafana if data source for annotations returns unexpected data. 

### Description

I've hit a problem with dashbord loading in grafana while testing grafana with carbonapi backend.
Grafana begin to heavilly eat cpu and page is freezed for a long time (over 30 seconds) while graphs are loading.
Long story short is that problem is related to annotations. carbonapi does not support /events/ endpoint, it returns a simple text page with available endpoints when requesting /events/.
When you have a dashboard with about 20+ graphs and with annotation from "graphite" source, but you use carbonapi as a source you will get the freeze.
I've made as minimal example as I can.
A dashbord with 20 empty graphs (without any metrics in them) and with about 5 annotations from graphite.

### How to reproduce

Tested on Grafana versions 5.3, 5.4.3

- Create a data source named freeze like in example.
- Start nginx server with a config as above (or any other server that will return about 100 bytes page for any url starting with /events/).
- Create a dashboard from freeze-dashboard.json.
- Open a dashboard and enjoy the freeze.

##### Data source configuration

<img width="440" alt="freeze-data-source" src="https://user-images.githubusercontent.com/11922623/52362035-b5f51980-2a50-11e9-8dc5-88152ee4e79e.png">

##### Dashboard json

[freeze-dashboard.zip](https://github.com/grafana/grafana/files/2837596/freeze-dashboard.zip)

##### Stub config for nginx (data source emulation)

Here is a stub config for nginx that emulates incorrect /events/ behaviour of datasource
```
server {
    listen 30081;

       location /events/ {
           return 200 "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz";
    }
}
```

### Conclusion

It is of course not normal to have dashboards with broken events, but one can have a hard time investigating what is the root of the problem when evaluating or migrating on carbonapi like I did or when there is some configuration error that leads to same behaviour of data source for /events/ URL.

**Comment by daniellee** [comment]
Thanks for documenting all the steps needed to recreate the issue. Much appreciated!

I could recreate the issue using the steps above - need to dig into the code and see what's going on.
