### ISSUE TITLE
Custom Time Range is always using browser timezone for database query

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#15284]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.4.3  http://play.garafana.com
### What datasource are you using?
Infuxdb but true for all datasources.
### What OS are you running grafana on?
Mac OS
### What did you do?
Selected custom time period  [From: now/d-2h, To: now ]  with UTC time zone and refreshed dashboard.

### What was the expected result?
Database query time filters should respect configured UTC time zone while converting the selected custom time period. 

### What happened instead?
Noticed that, panel is showing correct timeline as per UTC time zone on x-axis but data is being fetched only for the selected period converted to browser time zone. It's really odd and confusing because, panel shows a partial time period data on the screen. It reflects as data is not available for the full selected period. Database query time period is not being converted correctly as per UTC time zone. 

![image](https://user-images.githubusercontent.com/9439420/52368362-13627980-2a03-11e9-8152-a12733913839.png)

This is easily reproducable on http://play.grafana.com

**Comment by torkelo** [comment]
Can you show the query sent to your InfluxDB? (query inspector)

**Comment by digrich** [comment]
SELECT count("tid") FROM "autogen"."fxTrade" WHERE ("cptyA" =~ /^@_broker$/ OR "cptyB" =~ /^@_broker$/) AND time >= 1549432800000ms GROUP BY time(30m), "status" fill(0)

**Comment by digrich** [comment]
Hi @torkelo - Do you have any update on this?

**Comment by marefr** [comment]
Confirmed bug using UTC timezone and any timerange not starting with `Last ...`
