### ISSUE TITLE
Grafana 6-beta1 doesn't start anymore

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#15295]
### What Grafana version are you using?

6.0.0-beta1

### What datasource are you using?

Prometheus primarily.
Stackdriver, MySQL, elasticsearch for some dashboards too

### What OS are you running grafana on?

I am using the docker container provided via dockerhub

### What did you do?

I can not access grafana anymore. They are marked as ready pods, however the responses are very slow or don't come at all anymore. Here are the complete logs of all my instances after killing them:

**Replica 1:**

```
t=2019-02-07T09:27:08+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers
```

**Replica 2:**

```
t=2019-02-07T09:27:00+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers
t=2019-02-07T09:34:47+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-02-07T09:34:47+0000 lvl=dbug msg="Sending webhook" logger=notifications url="https://hc.*********QwRTCkbf5S4ZmJ24j" http method=
t=2019-02-07T09:35:32+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-02-07T09:35:32+0000 lvl=dbug msg="Sending webhook" logger=notifications url="https://hc.r******QwRTCkbf5S4ZmJ24j" http method=
```

Replica 3:

```
t=2019-02-07T09:27:00+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers
```

### What was the expected result?

When Grafana pods mark themselves as ready they are usually very responsive and work without any issues. 

### What happened instead?

Grafana was either very slow or didn't respond in time at all.

**Comment by marefr** [comment]
@weeco  What version did you upgrade from?

**Comment by weeco** [comment]
I upgraded from 5.4.x (I can figure out the build version if necessary). All my 3 instances are unresponsive after they ran for some time. No additional logs are being produced if this happens though, and they are still marked as "ready" pods.

**Comment by marefr** [comment]
Based on "Can't read alert notification provisioning files from directory" seems like you don't have access to that directory.

**Comment by marefr** [comment]
Oh wait. alert notification provisioning files. Thought it was dashboard provisioning.

**Comment by marefr** [comment]
Confirmed bug. Will be fixed in 6.0-beta2 release scheduled for February 11th.

**Comment by aditya-konarde** [comment]
Still seeing this on 6.0.1

**Comment by aditya-konarde** [comment]
@bergquist @marefr ^

**Comment by aditya-konarde** [comment]
Nevermind, it was some other container in the pod crashing. I must be blind :)

Also, I created an emptydir volume to add a `notifiers` directory. In case that helps anyone in the future.

**Comment by bossjones** [comment]
This comment by @aditya-konarde ( thank you ! ) here https://github.com/grafana/grafana/issues/15295#issuecomment-472412321 combined w/ upgrading to grafana 6.0.2, fixed everything for me. Just leaving a note for others who stumble upon this by accident.
