### ISSUE TITLE
XSS: Option to disable or sanitize html source in some panels

### ISSUE THREAD

**Issue by noasand** [grafana/grafana#15293]
#### Grafana is vulnerable to XSS vulnerability because the panels included in the description below can contain html. Therefore, the option to disable or filter the html source must be provided.

> [Affected Component]
> #Grafana(5.3.1)
> Dashboard > Text Panel
> 
> [Attack Vectors]
> 1. Grafana(5.3.1) Launch
> 2. Access to any dashboard
> 3. Add Panel > Text
> 4. Edit Text Panel
> 5. Set Options -> Mode(html) & Content(<script>alert('XSS');</script>)
> 
> ------------------------------------------
>
> [Affected Component]
> #Grafana(5.3.1)
> Dashboard > Table Panel
> 
> [Attack Vectors]
> 1. Grafana(5.3.1) Launch
> 2. Access to any dashboard
> 3. Add Panel > Table
> 4. Edit Table Panel
> 5. Set Column Styles
> : Check Render value as link
> : set Url(javascript:alert('XSS')) 
> 
> ------------------------------------------
> 
> [Affected Component]
> #Grafana(5.3.1)
> Dashboard > All Panels > General
> 
> [Attack Vectors]
> 1. Grafana(5.3.1) Launch
> 2. Access to any dashboard
> 3. Dashboard Settings
> 4. Set dashboard name(TEST<script>alert('XSS')</script>
> 5. Save dashboard and go back to dashboard home
> 6. Edit any panel
> 7. Add link, in General 
> 8. Write the 'TEST' on the dashboard blank
>

**Comment by noasand** [comment]
This issue is associated with https://github.com/grafana/grafana/issues/4117.

**Comment by torkelo** [comment]
Yes, which we fixed in upcoming v6 (out in beta). From now on html will be. Sanitized by default in text panel

**Comment by noasand** [comment]
Please check whether the above three vulnerabilities have been fixed in v6.

**Comment by noasand** [comment]
Hello. I have confirmed that the first vulnerability has been fixed. Please let me know if the other two are corrected.
