### ISSUE TITLE
Series name autocomplete not showing all entries

### ISSUE THREAD

**Issue by ousysadmin** [grafana/grafana#1529]
I'm not sure if there's too many metrics on one server, but when I go to create a new graph now I click on series name and the list isn't showing all of the metrics from InfluxDB. It used to work.

![grafana_series_name_list](https://cloud.githubusercontent.com/assets/11213879/6394817/bc790c26-bd99-11e4-9e97-863b808913d6.png)

I've verified the browser is getting the full list of metrics through the response from Grafana, Grafana just isn't showing all of them. This one host has 447 metrics associated with it.

I've verified this same behavior with both Firefox v35 and Chrome v40.

**Comment by torkelo** [comment]
There is limit in the auto complete set to 100 items. you can filter the list by typing in part of the series name. 

The InfluxDB query editor for InfluxDB 0.8.x will not see any more updates or fixes as it is being totally rewritten for InfluxDB 0.9

**Comment by ousysadmin** [comment]
Is that hardcoded in the app.ae1e5ed0.js file somewhere?

**Comment by torkelo** [comment]
yes
