### ISSUE TITLE
Replace remember me cookie solution for Grafana's builtin, LDAP and OAuth authentication with a solution based on short-lived tokens

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#15303]
Epic for tracking removal of remember me cookie solution and replace it with short-lived token solution for Grafana's builtin, LDAP and OAuth authentication.

**Comment by torkelo** [comment]
Is this not what the auth token PR did? Is the remember me cookie still there?

**Comment by marefr** [comment]
Closed by #1441, #13032, #14912, #14995, #15067, #15170, #15191, #15239, #15287, #15288, #15300, #15308, #1536

**Comment by bergquist** [comment]
![Fuck yea](https://media.giphy.com/media/5xaOcLLyNsTBTjfM5DG/giphy.gif)
