### ISSUE TITLE
Percentile function in metric not providing correct result

### ISSUE THREAD

**Issue by jvanderaa** [grafana/grafana#15309]
Please include this information:
### What Grafana version are you using?

5.4.3

### What datasource are you using?

InfluxDB

### What OS are you running grafana on?

Linux

### What did you do?

I created the query of the 95th percentile from a source that already had the network octets shifted into bits with a non-negative-derivative and the appropriate math. This is getting into the database just fine. When I apply the _SingleStat_ panel I get wrong information back.

```
SELECT percentile("inbitspersec", 95) FROM "autogen"."bandwidth" WHERE ("hostname" =~ /^$host$/ AND "ifDescr" =~ /^$Interface$/) AND $timeFilter GROUP BY time(5m) fill(null)
```

I exported the data from the time period of the data and put this into Excel. Excel calculates the percentile just fine. I did notice in the data there are some blank/non entry fields. I'm curious if this maybe something possible in the way as well. 

### What was the expected result?

Get the 95th percentile

### What happened instead?

Not sure what number I got back. The number was lower than what the actual calculation showed it to be.

**Comment by torkelo** [comment]
This function is processed by influxdb not Grafana so if there is an issue it might be there, it could also be the time interval used in the group by
