### ISSUE TITLE
t.replace is not a function (with Zabbix Api source)

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#15319]
### What Grafana version are you using?
It was Grafana v5.4.2 (commit: d812109) but updating to Grafana v5.4.3 (commit: 6539180) didn't fix the issue

### What datasource are you using?
Zabbix api (Zabbix plugin by Alexander Zobnin, Version 3.9.1) @alexanderzobnin

### What OS are you running grafana on?
CentOS Linux release 7.6.1810 (Core)
Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
I try to create new dashboard with widget or add new widget (Table for example) in existing board.

### What was the expected result?
Creating new board and adding new widget

### What happened instead?
I get an arror after choosing "zabbix api" in Data Source section: **t.replace is not a function**

Pic 1: normal situation with "Grafana" datasource:
![image](https://user-images.githubusercontent.com/1700286/52476734-a1c82e00-2bb0-11e9-9f56-3da3fddeb50a.png)

Pic 2: error after switching to "zabbix api" source
![image](https://user-images.githubusercontent.com/1700286/52476763-c15f5680-2bb0-11e9-9c27-d5320d120275.png)

Pic 3: try to create Graph widget and getting the same error. Adding more queries after that:
I can create B and C etc queries, but A is broken
Hide and Remove buttons dont' work with A query
![image](https://user-images.githubusercontent.com/1700286/52477292-6af31780-2bb2-11e9-8f43-aec8e279a29b.png)

Pic 4: Open already existing widget with zabbix source, made ~3 mouths ago, all is OK:
New queries creates OK too
![image](https://user-images.githubusercontent.com/1700286/52477701-ec977500-2bb3-11e9-8ae0-3761bd9657a1.png)

Pic 5: Zabbix datasource config:
![image](https://user-images.githubusercontent.com/1700286/52477423-e05ee800-2bb2-11e9-90a2-a70e099f5d8a.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![image](https://user-images.githubusercontent.com/1700286/52477114-da1c3c00-2bb1-11e9-8ba6-326f24578b7f.png)

**Comment by torkelo** [comment]
Can you open this with in the zabbix issue repo? https://github.com/alexanderzobnin/grafana-zabbix
