### ISSUE TITLE
[Bug] Really long decimal values in elastic histogram (graph) panel?

### ISSUE THREAD

**Issue by KaranTrivedi** [grafana/grafana#15314]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab. 
 
![grafana bug](https://user-images.githubusercontent.com/19409558/52458645-a815c600-2b2e-11e9-8cf3-a11a8d48e00d.png)

**Comment by torkelo** [comment]
Can you please provide details on your ES query and the response from ES? (View in query inspector in metrics tab)

**Comment by KaranTrivedi** [comment]
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/5/_msearch"
data:"{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"index1"} {"size":0,"query":{"bool":{"filter":[{"range":{"event_time":{"gte":"1547306476814","lte":"1549898476815","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"closed_user.keyword:(\"user9\" OR \"user8\" OR \"user7\" OR \"user6\" OR \"user5\" OR \"user4\" OR \"user3\" OR \"user2\" OR \"user1\" OR \"Woo,\\ Derek\\ M\") AND closed_teams.keyword:team1"}}]}},"aggs":{"4":{"histogram":{"interval":0.05,"field":"entropy","min_doc_count":1},"aggs":{"3":{"date_histogram":{"interval":"30d","field":"event_time","min_doc_count":0,"extended_bounds":{"min":"1547306476814","max":"1549898476815"},"format":"epoch_millis"},"aggs":{}}}}}} "
response:Object
responses:Array[1]
0:Object
took:230
timed_out:false
_shards:Object
total:5
successful:5
failed:0
hits:Object
total:2019
max_score:0
hits:Array[0]
aggregations:Object
4:Object
buckets:Array[7]
0:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:4
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:328
key:0.15000000000000002
doc_count:332
1:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:15
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:833
key:0.2
doc_count:848
2:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:6
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:633
key:0.25
doc_count:639
3:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:2
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:78
key:0.30000000000000004
doc_count:80
4:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:0
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:18
key:0.35000000000000003
doc_count:18
5:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:0
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:18
key:0.4
doc_count:18
6:Object
3:Object
buckets:Array[2]
0:Object
key_as_string:"1544832000000"
key:1544832000000
doc_count:3
1:Object
key_as_string:"1547424000000"
key:1547424000000
doc_count:81
key:0.45
doc_count:84
status:200

This is the query I am running. Is there any other info I can provide? I wonder if there is anything in the query I can tune to reduce the decimals elastic is returning. I guess this is not necessarily a grafana bug?

**Comment by KaranTrivedi** [comment]
Any thoughts so far? I am sure you are very busy

**Comment by torkelo** [comment]
Looks correct, you have a histogram interval, and elastic is returning a lot of decimals for each bucket key

**Comment by KaranTrivedi** [comment]
Is there any way to override the x axis data? I will massage the data as much as I can. Thanks.
