### ISSUE TITLE
Stackdriver: Add ability to use proxy to reach google APIs

### ISSUE THREAD

**Issue by scathatheworm** [grafana/grafana#15317]
### What Grafana version are you using?
Grafana version 5.4.3
### What datasource are you using?
Stackdriver
### What OS are you running grafana on?
CentOS 7
### What did you do?
Trying to add stackdriver as a datasource
### What was the expected result?
To be able to fetch metrics from stackdriver
### What happened instead?
Traffic is blocked because our grafana infrastructure is behind firewalls that forbid direct internet access
### If related to metric query / data viz:
No
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
```t=2019-02-05T13:38:39+0100 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp [****************]:443: connect: network is unreachable"```
Our grafana servers are located in our own datacenter space, and we want to be able to use Google StackDriver as datasource to monitor the increasing number of services from GCP we plan on using. When trying to add GCP StackDriver as a data source per http://docs.grafana.org/features/datasources/stackdriver/ we notice that we can't get connectivity because of internal network firewall rules. We do have proxies that would allow us to do this, but there's nowhere we can configure the stackdriver datasource to use one. It would be ideal if this can be done easily with configuration.

**Comment by daniellee** [comment]
I think that our answer when have received this type of request previously has been to use a proxy like Nginx or Apache (or IIS in Windows) in front of Grafana rather than building proxy functionality into Grafana.

Would that work in your case?

**Comment by azhiltsov** [comment]
Different datasources might have different list of endpoints. 
Stackdriver seems have a hardcoded endpoint which is unavailable for configuration for the end-user.
Cloudwatch from Amazon uses regions, which is not translated directly to the hostname. 
Configuring localproxy for every such thing will easily become a tedious work, where you would have to look into datasource plugin, figure list of possible endpoints, hack /etc/hosts to intercept a traffic and at the end hope that next release of datasource plugin won't change anything.
Proxy setting per datasource seems to be a logical solution. 
Here is another ticket about this: https://github.com/grafana/grafana/issues/15045

**Comment by sunker** [comment]
Thanks for creating this issue @scathatheworm. 

We're not going to make something that is custom to the CloudMonitoring data source. However, it feels like this issue should be/could be resolved by [this](https://github.com/grafana/grafana/issues/15045) feature request. I'll close this issue now.
