### ISSUE TITLE
Expose range prop on fake panelCtrl to angular query editors

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15315]
Some angular query controllers expect there to be a range prop on the fake panelCtrl we setup here: 
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/panel_editor/QueryEditorRow.tsx#L53

**Comment by alexanderzobnin** [comment]
Some links to datasources which use this:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/query_ctrl.ts#L68
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/query_ctrl.ts#L114
