### ISSUE TITLE
email_attribute_name not working

### ISSUE THREAD

**Issue by ysiivan** [grafana/grafana#15311]
### What Grafana version are you using?
5.4.3
### What OS are you running grafana on?
docker image (latest & 5.4.3) on Ubuntu 18.04.01 host
### What did you do?
```
[auth.generic_oauth]
enabled = true
name = Test
client_id = my-test-client-id
client_secret = my-test-client-secret
scopes = openid
auth_url = https://my-test-server/yAuth2/identity/connect/authorize
token_url = https://my-test-server/yAuth2/identity/connect/token
api_url = https://my-test-server/yAuth2/identity/connect/userinfo
email_attribute_name = yName
```
### What was the expected result?
To have Grafana pick the the user email from the **yName** attribute in **id_token**.
As specified in the documentation http://docs.grafana.org/auth/generic-oauth
### What happened instead?
Grafana failed to retrieve the email from the **yName** attribute.
From the logs (note that the **yName** claim is present):
```
t=2019-02-07T20:20:07+0000 lvl=dbug msg="No email found in id_token" logger=oauth.generic_oauth json="{\"iss\":\"https://my-test-server/yAuth2/identity\",\"aud\":\"my-test-client-id\",\"exp\":1549570927,\"nbf\":1549570807,\"iat\":1549570807,\"sid\":\"a32997b1b97a4a81641625bc2b87d8fe\",\"sub\":\"116027d8-eeab-4e19-adfe-cd706655c5e4\",\"auth_time\":1549569063,\"idp\":\"idsrv\",\"yName\":\"Joe.Blow@my-test-domain.com\",\"amr\":[\"password\"]}" data="&{Name: DisplayName: Login: Username: Email: Upn: Attributes:map[]}"
```

**Comment by DanCech** [comment]
that setting is a little confusing, it actually tells grafana to look in `attributes[yName]`, you'll want to make sure the email is available in `email` or `upn`.

**Comment by Peperud** [comment]
@DanCech 
So, ```attributes``` is assumed to be an array/dictionary claim returned by the user info endpoint?
Interesting...Not that it matters much, but I don't recall ever seeing this. I have seen few cases though where the email is stuffed in a top-level claim that's not ```email```. Usually in systems where the (unique) username is an email and it gets added to the identity token by default.

**Comment by DanCech** [comment]
@Peperud yes, that is correct.  The whole thing is somewhat confusing imho, you can read more about it in the original PR #13006
