### ISSUE TITLE
Changing Visualization issues

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15326]
Using master grafana...  when I change the Visualization, it requires two clicks:

First click changes the display:
![image](https://user-images.githubusercontent.com/705951/52501561-76841580-2b95-11e9-8c08-64dc1d70563b.png)

Another click to close the list of options:
![image](https://user-images.githubusercontent.com/705951/52501608-94ea1100-2b95-11e9-8e6f-cf5b901f9178.png)

In v5, I really liked that you could add a panel by:
 1. click 'add panel'
 2. type 'di'
 3. hit `enter`

I also think the search text should be cleared after selecting a Visualization -- its a little weird to have your old search there when you are trying a few options

**Comment by torkelo** [comment]
the point of staying open is so you change visualizations without having re-open. We plan to have Singlestat, Gauge & Bar Gauge with same option models so you change between then and have the thresholds and options persist. 

Not sure what the best way to solve both use cases. 

Recently updated the Add panel widget so you can go directly to visualization selection.

**Comment by torkelo** [comment]
created a new issue for the search clearing issue, https://github.com/grafana/grafana/issues/15328 

closing this for now, but will see if other feedback is similar to you about whishing viz picker auto closing after one click
