### ISSUE TITLE
Add back panel plugin horizontal option tabs

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15324]
In grafana 6, the plugin options have kinda moved to sidebar buttons, and the other tabs get added to a list under Visualization.

Before this gets too baked in, would you consider either:
* adding tabs under Visualization
* adding an sidbar icon for each tab added with `this.addEditorTab(...`

In most of the plugins, I used the tabs to highlight the key options and sections, but the key options are now kinda lost in v6.

v5:
![image](https://user-images.githubusercontent.com/705951/52498468-bb0bb300-2b8d-11e9-90ba-cdf96350849d.png)

v6:
![image](https://user-images.githubusercontent.com/705951/52498437-a5968900-2b8d-11e9-9284-1340a34d253e.png)

Maybe consider:  if there is only one `this.addEditorTab(`, don't show tabs, otherwise, something like:
<img src="https://user-images.githubusercontent.com/705951/52499263-dbd50800-2b8f-11e9-9735-ac1909bffec5.png">

**Comment by ryantxu** [comment]
Even for the standard graph panel, I would rather see tabs for the key options:

![image](https://user-images.githubusercontent.com/705951/52500680-7420bc00-2b93-11e9-936b-3f2c9e1162c9.png)

rather than having them inline below.

I understand an argument that there are too many settings hidden deep in the guts.  If that is the case, maybe buttons at the top that scroll down to the right place?  I'm really looking for a way to make `Examples` a top level option without it going first :)

**Comment by torkelo** [comment]
The problem with those tabs are that they did not really work great, was not clear where setting could be found. Tabs hide settings & force a categorization that is not always clear and intuitive.

And having 3 core tabs that Grafana control (Queries & Visualization & Advanced) we felt made it a lot easier to navigate and reason about, especially for new users. Having many plugin tabs mixed in here with somewhat random groupings (like Options tab for general options and some Column Styles for column styles, but some column selection is on Options, for table panel). 

Having nested tabs like we had in some tabs (like Graph Display tab with a sidemenu) was also really bad. So we feel like a single tab, scrolling, and collapsible sections (we have yet to add the collapsing behavior to the boxes) 

As you can see with the Gague panel, react panels will also have some more options for layout of the panel options. 

But we are open to making changes and welcome feedback. So far the feedback has been very small so we will wait with more before making any actions. 

But really appreciate the feedback here.

**Comment by ryantxu** [comment]
I totally agree with the motivations for dropping tabs and think the direction is good.  For sure the nested tabs with more nested sidebar was really not great.

But this change has lots of impact on external plugins that do not get to easily support different UX for 5x vs 6x, and have used `addEditorTab(..` to call out the key sections, not have them fall way, way, way down the page.

To make that transition less painful, can we consider keeping tabs for the angular based plugins, but pick something better as things migrate to React?  

Maybe a button to 'show all' that would convert the tabs into a long list?  (maybe dumb)

**Comment by ryantxu** [comment]
Or maybe add the tab headings as anchor links at the top?  (brainstorming)
<img src="https://user-images.githubusercontent.com/705951/52506337-1c8a4c80-2ba3-11e9-9a4c-0db998c9d435.png">

**Comment by timurb** [comment]
It might not be very intuitive in the previous UI of which tab to choose but I was able to click through all of the tabs in 3 seconds and quickly find the parameter I seek.
Now I have to scroll through the long list of parameters and it's not so easy to remember in which order were the fields so I have to scroll up and down a few times before I find the parameter I need.

Also I'm working on a 13" laptop with not the very best touchpad and I find it really painful to use editor in Grafana 6.0 with very long scroll and no shortcuts to the parameters I seek.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
sorry ryan closing this :)
