### ISSUE TITLE
[Docs] Configuration documentation missing: Server.enable_gzip

### ISSUE THREAD

**Issue by brunorey** [grafana/grafana#15322]
I found that Grafana was taking too long to load (5 minutes in an incognito window with a not-so-good connection) so I investigated what could be done. I noticed it wasn't sending compressed content and the JS files where about 4~5 Mb. 

I noticed there's a config item in the `[server]` section named `enable_gzip`, before enabling it I wanted to be sure of what it does but found no information in [the documentation](http://docs.grafana.org/installation/configuration/#server)

For anyone interested in that config item, you can see [this search](https://github.com/grafana/grafana/search?q=EnableGzip&unscoped_q=EnableGzip) and find that in the file `pkg/api/http_server.go` will add a `Gziper()` middleware if it is set to true.

### What Grafana version are you using?
Version 5.4.3 (commit: 6539180, branch: HEAD)

### What datasource are you using?
InfluxDB 1.6.4

### What OS are you running grafana on?
$ uname -a
Linux nexus-system-devel 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
$ cat /etc/debian_version 
buster/sid

### What did you do?
Read configuration files, found "enable_gzip" and searched documentation for it.

### What was the expected result?
To find the description of the field and what it does

### What happened instead?
No documentation found, had to read source code.

**Comment by daniellee** [comment]
I use this setting all the time and it can make a huge difference in certain situations (for example when loading plugins with large files). It should be documented - don't know how this slipped through.

**Comment by dprokop** [comment]
@daniellee is there any reason why gzip isn't opt-out setting, rather than the other way around?

**Comment by daniellee** [comment]
@dprokop it causes problems in some setups so we couldn't turn it on per default. But we should recommend that people do.
