### ISSUE TITLE
Change vis icon highlight after selection

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15329]
follow on to ##15326

While playing with the new vis-picker, it feels like a bug that the selections do not change after you select one.

Perhaps changing the highlight after selection would help.  It looks like the properties are getting set, but since the mouse is still over it stays in the `:hover` style?

Maybe disable `:hover` for `-current`?

**Comment by torkelo** [comment]
thoughts @Ijin08 ?

**Comment by ryantxu** [comment]
much better @torkelo -- now it feels intentional :)

**Comment by Ijin08** [comment]
Great improvement!
