### ISSUE TITLE
bs-tooltip styling (v6 plugin migration)

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15325]
super minor... but I'll submit here anyway :)

Plugin code:
```
<div class="gf-form" >
  <span class="gf-form-label width-9">
    Response
    <info-popover mode="right-normal" position="top center">
      Useful when loading images<br/>
      or other non-text content
    </info-popover>
  </span>
  <div class="gf-form-select-wrapper width-9">
    <select class="gf-form-input" ng-model="ctrl.panel.responseType" ng-change="ctrl.onConfigChanged()">
      <option value="text">Text</option>
      <option value="blob">Blob</option>
      <option value="document">Document</option>
      <option value="json">JSON</option>
      <option value="arraybuffer">Array Buffer  (for images)</option>
    </select>
  </div>
  <span bs-tooltip="'See documentation at:<br/>https://developer.mozilla.org/'"> &nbsp; <a href="https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType" target="_blank"><i class="fa fa-question-circle"></i></a></span>
</div>
```

In v5 this shows:
![image](https://user-images.githubusercontent.com/705951/52500069-e7c1c980-2b91-11e9-83f1-e746db764dd1.png)

In v6 it is top aligned:
![image](https://user-images.githubusercontent.com/705951/52500086-f5774f00-2b91-11e9-977d-819d6380f604.png)

**Comment by torkelo** [comment]
it's not inside a gf-form-label or gf-form-input element, so it's not a usecase I think where grafana use tooltips, gf-form was fixed to have align-items: flex-start so that labels are aligned to the top when paired with  higher text-area / query editor inputs.

Is having classes span with icon inside a gf-form normal use case in plugins you think?

**Comment by torkelo** [comment]
closing this for now as it seems like an edge case usage of the tooltip component, will reopen if there are more issues related to the change of align-items
