### ISSUE TITLE
Panel not found behavior in v6

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15327]
In master, if you:
1. install a plugin
2. start grafana
3. delete the plugin folder

You will get:
- nothing displayed
![image](https://user-images.githubusercontent.com/705951/52502828-949f4500-2b98-11e9-9b51-5d6399845e44.png)

- console errors:
![image](https://user-images.githubusercontent.com/705951/52502781-72a5c280-2b98-11e9-8f2a-62460313421a.png)

I think the catch for plugin errors has been lost in the shuffle :)

**Comment by torkelo** [comment]
thanks for reporting this! The PanelNotFound handling must have stopped working, will investigate

**Comment by ryantxu** [comment]
> thanks for reporting this!

I am submitting everything I find now -- seems good to have external eyes give you some feedback before release.  But obviously ignore anything that seems too nit-picky
