### ISSUE TITLE
Wrong value in tooltip

### ISSUE THREAD

**Issue by hpirila** [grafana/grafana#15336]
When hovering mouse over point in wide zoom of graph, incorrect timestamp value is shown.

<img width="146" alt="1" src="https://user-images.githubusercontent.com/37920282/52529353-ad3b6680-2d22-11e9-89d3-bac0825f984d.png">

Only when zooming in to the graph, correct value is shown.

<img width="147" alt="2" src="https://user-images.githubusercontent.com/37920282/52529356-c217fa00-2d22-11e9-980e-61eea146fd67.png">

InfluxDB rows near that point, the point in question in bold:

2019-02-09T21:08:31Z 5.64
**2019-02-09T21:09:32Z 5.57**
2019-02-09T21:13:08Z 5.34

Note: Timezone +7

To further clarify, there is no such point in DB where timestamp is 2019-02-09T21:09:30Z, but grafana still shows that timestamp value (first picture). It makes difficult to find the corresponding row from database using sql.

What Grafana version are you using? Grafana v5.4.3 (6539180)
What datasource are you using? InfluxDB
What OS are you running grafana on? Linux
What did you do? Hover mouse on point of graph
What was the expected result? Show the point timestamp as in influx database
What happened instead? A rounded timestamp value was shown

**Comment by torkelo** [comment]
Whats your InfluxDB query and the influxDB response? Please check query inspector in metrics tab, it shows raw response from influxdb. 

If you have a group by time ($__interval) in your query InfluxDB will group data into time interval buckets.

**Comment by hpirila** [comment]
You are right. It is $_interval and the results are 

608:Array[1549746570000,5.57]
440:Array[1549746572000,5.57]

respectively.
