### ISSUE TITLE
Singlestat: Gauge using wrong colors

### ISSUE THREAD

**Issue by sewi-cpan** [grafana/grafana#15334]
Singlestat has three colors: Below threshold 1, above threshold 1, above threshold 2. The number correctly switches between them as the value travels through the thresholds.
The gauge graph exchanges color1 and color2 both for the markers circle and the gauge itself.

![bildschirmfoto von 2019-02-09 10-18-40](https://user-images.githubusercontent.com/2063104/52518964-228c3600-2c54-11e9-8aac-dd3877eb8b07.png)
The sample should be green|yellow|red. The number is below 50k and green, which is correct. The gauge is yellow instead of green and shows green as the middle color which should be yellow.

### What happened instead? Gauge replaced color 1 and 2
 
Different to #5515

**Comment by flopp999** [comment]
you have wrote 50000, 10000
missing a zero(0)?
maybe it should have been 50000, 100000

**Comment by sewi-cpan** [comment]
Sorry, my fault. Read it a dozen times but never recognized the missind zero :(
