### ISSUE TITLE
Stacked Graph Cumulative Display not per stack

### ISSUE THREAD

**Issue by lydon42** [grafana/grafana#15338]
Using Grafana 5.3.2, influx, debian.

I have an aggregate interface graph which adds up traffic from multiple interfaces. Four series are defined: in, out, in_95, out_95 (first two are mean, last two are 95th percentile).

I stack them using series override into four stacks (A,B,C,D).

In display options I have selected stacked and cumulative display.

The hover shows cumulative values, but they are not separated by the individual stacks. So it adds up in, then adds the outs to it, adds in_95 and last but not least adds out_95.

It would be nice to have the option to select "cumulative per stack" For Hover Tooltip/Stacked Value in the Draw Options.
![stack-example](https://user-images.githubusercontent.com/16632479/52536933-02966880-2d61-11e9-8cef-8bdbdc0f1e26.png)

**Comment by torkelo** [comment]
The stack cumulative mode does not currently support stack groups

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
