### ISSUE TITLE
Missing series

### ISSUE THREAD

**Issue by khushil** [grafana/grafana#1533]
I have a large number, over 100 series, in my InfluxDB.

A list series shows all of them in InfluxDB.

When I go to find them in grafana however, it only outputs a selected list but I can't detect a pattern on how it selects which ones to show?

If I copy paste a series out of InfluxDB that isn't shown, that data is pulled in so it seems as if the autocomplete doesn't show all series?

**Comment by torkelo** [comment]
the auto complete limits to 100 series. If you type in the beginning of a series it will filter the results. 

I can remove this limit but the InfluxDB query editor is going to be completely revamped for InfluxDB 0.9 so we are not doing any changes the existing query editor. 

But to work around this 100 series limit you can type in the beginning or use a regex to limit the series search to explore and find the series you want.

**Comment by torkelo** [comment]
It any case the autocomplete cant really show all results, many users have hundreds of thousands or millions of series
