### ISSUE TITLE
Does Grafana License Allow Changing Logo and Title?

### ISSUE THREAD

**Issue by vasuems** [grafana/grafana#15349]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Search for license, for example
https://community.grafana.com/t/license-question/1316
https://community.grafana.com/t/how-many-do-we-have-to-remove-grafana-trademarks/12244
