### ISSUE TITLE
Expose redux and connectWithReduxStore

### ISSUE THREAD

**Issue by bpl3** [grafana/grafana#15341]
### What Grafana version are you using?
v6.0.0-beta1

Can you please expose "**redux**" and "**app/core/utils/connectWithReduxStore**" to external plugins, in order for them to use the Redux store?

**Comment by torkelo** [comment]
not sure we want to expose this to plugins. What is it you want to do?

**Comment by bpl3** [comment]
I want to use the Redux store in my React-based plugins. Importing Redux myself (via webpack) does not work unfortunately.

**Comment by peterholmberg** [comment]
fixed in https://github.com/grafana/grafana/pull/18501
