### ISSUE TITLE
feature request: separate panel for a legend

### ISSUE THREAD

**Issue by JoshiiSinfield** [grafana/grafana#1535]
When using a templated dashboard we've often got the same legend across multiple graphs.

We can obviously just hide the legend on all the graphs but it would be a nice feature to have a shared legend. All the graphs seem to share the same colours for each legend element anyway.

Cheers,
Josh

**Comment by ohTHATaaronbrown** [comment]
+1

I'd go so far as to request a "Table" panel, which consists of the values that graph panels currently put into their legends.

**Comment by cstroe** [comment]
+1

**Comment by torkelo** [comment]
table panel solves this
