### ISSUE TITLE
Indistinguishable colors on the stacked chart

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#15357]
Please include this information:
### What happened instead? *The same color for 1st and 3rd series*

See [US and China](https://linux.teststats.cncf.io/d/50/countries-stats?orgId=1&from=now-8y&to=now&var-period_name=Year&var-countries=All&var-repogroup_name=All&var-metric=rcommitters&var-cum=countries)
![screenshot 2019-02-11 at 14 19 51](https://user-images.githubusercontent.com/2469783/52565781-206ad880-2e08-11e9-9fd8-b7e59355536f.png)

Is it possible to configure those colors somewhere?

**Comment by torkelo** [comment]
I don't know if there is much we can do here. You have many series and a custom sorting of the series. The color will not change based on sorting (which would be very confusing as you changed sorting). So, in this case, it'a fluke that given your sorting two series got the same color. 

You have to manually assign colors in this case. 

Or do you have an idea for how to fix this?

**Comment by lukaszgryglicki** [comment]
Hmmm: how can I do it manually? Eventually, why not assign colors in the same order as sort, for example: red, green, blue, cyan, ... etc. Just thinking about options I have.

**Comment by torkelo** [comment]
Click the colored line icon to the left of the series name opens the color picker.

Having the colors change as you change sort would be quite confusing as it would be hard to keep track of series. If you can sort series in you query the same as as In legend then you can eliminate this problem

**Comment by lukaszgryglicki** [comment]
Great, thanks. I think we can close it then.

**Comment by lukaszgryglicki** [comment]
One more question @torkelo - is it possible to have those selected custom colors stored in a `stateful URL`?

**Comment by torkelo** [comment]
no, they are only stored in panel json model

**Comment by lukaszgryglicki** [comment]
Panel JSON but not a dashboard's JSON, right? I mean can I save it somehow or make it persistent for a given dashboard?

**Comment by torkelo** [comment]
of course, panel json is part of the dashboard json

**Comment by lukaszgryglicki** [comment]
Ok thanks.

**Comment by lukaszgryglicki** [comment]
Ok Saved that in dashboard JSON - works perfectly, thanks again.
