### ISSUE TITLE
group by time behavior

### ISSUE THREAD

**Issue by brunoleon** [grafana/grafana#1536]
As indicated in the docs, when querying influxdb with derivative() and using fill(0) function, you must set a minimal group by time statement such as:
`group by time >10s`
So that your query resolution is higher than the frequency at which your data are sent to influxdb.

This translates for exemple:
`select derivative(value) from /staging.index.(06298a8c|9727d847|ae8d0ee5|c258f55c).*interface.*octets.tx.*/ where time > now() - 1h group by time(10s) fill(0) order asc`

Actually, this result in always 0 value result, because my collectd (it could be anything) is sending data every 10s exactly. If you set group by time >11s then results are fine.

The contextual help is a bit misleading then, because either group by time>10 should litteraly mean 10+1, or help message should indicate that you must seth the group by higer and not equal to your data resolution.

Hoping this makes sense...

**Comment by torkelo** [comment]
Strange, could be an influxdb bug, it worked last time I tested. I always that that the derivative  function to be a little strange In influxdb.

**Comment by torkelo** [comment]
if you collectd is always sending data every 10s you should not need the fill(0), maybe that is causing the issue?

**Comment by brunoleon** [comment]
You're right about the fill(0) is not needed but my point was more about "group by time > 10s" in gf interface should not translate into "group by time(10s)" in influxdb query.
This is behaving as if I entered "group by time" myself in the query area, but this is not the case, I just specified below the query area "group by time >10"

Actually I understand it as grafana interprets > as an = sign, which should not be the case when specifying a minimum grouping interval, it should be "a bit higher than".
