### ISSUE TITLE
Unable to query when using variable

### ISSUE THREAD

**Issue by tcho16** [grafana/grafana#15365]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.2.3
### What datasource are you using?
Influx
### What OS are you running grafana on?
Centos
### What did you do?
Added a variable to get away from hardcoded values in my current query.
### What was the expected result?
The graph would display the results as usual.
### What happened instead?
The graph does not display any results. It says `No data points found.`. 
This was my query whilst it was hardcoded which works(query inspector):
`"SELECT non_negative_difference(max("ltmVirtualServStatClientBytesOut")) FROM "f5_serverstats" WHERE ("ltmVirtualServStatName" =~ /hosty.com/ AND "environment" =~ /^prod2$/) AND time >= now() - 6h GROUP BY time(30s) fill(null)"
`
I then created a variable of type custom and added the value `hosty.com` to the variable. Upon looking at the query inspector then, this is what came out:
`"SELECT non_negative_difference(max("ltmVirtualServStatClientBytesOut")) FROM "f5_serverstats" WHERE ("ltmVirtualServStatName" =~ /^hosty\.com$/ AND "environment" =~ /^prod2$/) AND time >= now() - 6h GROUP BY time(30s) fill(null)"
`

I don't know if its normal but there seems to be a \ before the `.com`. Even when I omit the `.com` in the variable value and simply write `hosty`, it still doesn't print out and this is what comes in the query inspector:
`"SELECT non_negative_difference(max("ltmVirtualServStatClientBytesOut")) FROM "f5_serverstats" WHERE ("ltmVirtualServStatName" =~ /^hosty$/ AND "environment" =~ /^prod2$/) AND time >= now() - 6h GROUP BY time(30s) fill(null)"`.

**Comment by torkelo** [comment]
since your using the variable in an influxdb regex expression Grafana will escape the regex characters `.`

you have `$` in at the end of the regex operation, that means the ltmVirtualServStatName needs to be an exact match, so the value needs to be start with hosty and end there (^ mean start of string). Remove the ^ and $ at the end of the variable to only search for values containing the value. 

example: `("ltmVirtualServStatName" =~ /$server/`   (see I remove ^ before variable and $  at the end

**Comment by tcho16** [comment]
@torkelo Oh okay I understand that but when I am creating the variable, I am giving it a value of `hosty.com` and it seems like grafana is automatically putting the `^` and `$` signs in the query inspector so how would I be able to removed the `^` and `$` signs?

**Comment by torkelo** [comment]
By typing in something different or selecting the current value. Grafana suggests that as exact matches is usually what users want

**Comment by tcho16** [comment]
Got it working. Didn't realise you could literally type into the field rather than just click on it. Thanks for the help.

**Comment by tcho16** [comment]
@torkelo Quick question. If I've got a value of `Random-hosty.com` in one of my custom type variables, Would I be able to use this variable by stripping out the `Random-` and be able to use the `hosty.com` in my query through regex? 
so something like `("ltmVirtualServStatName" =~ /[-]+$server/)` should basically query `ltmVirtualServStatName =~ hosty.com`?

**Comment by torkelo** [comment]
Eh, how would that possibly work?
