### ISSUE TITLE
Sane defaults for login duration

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#15361]
In pre Grafana v6.0 there was a setting named `login_remember_days` with a default value of 7, i.e. a user can be logged in for a maximum of 7 days. See [code](https://github.com/grafana/grafana/blob/v5.4.x/conf/defaults.ini#L176).

With #15303 we've replace `login_remember_days` with two new settings:
* `login_maximum_inactive_lifetime_days`, default 7
* `login_maximum_lifetime_days`, default 30 days

`login_maximum_inactive_lifetime_days` is sliding so it will be extended with 7 days on each token rotation (per default each 10 minutes).
`login_maximum_lifetime_days` is similar to the old `login_remember_days` as it tracks the maximum time a user can be logged in since login time.

Given the old behavior of `login_remember_days` have we set sane defaults for the new settings?

**Comment by bergquist** [comment]
It's great that you raise these discussions on github.

I think those are sensible defaults but Im happy to be proven wrong. Let keep this issue open for a while and see if anyone objects. Otherwise, I think we can close this within a few weeks after GrafanaCon.

**Comment by marefr** [comment]
Additionally, in the old solution you could set `login_remember_days` to zero and you would basically only get a session cookie valid for 24 hours, see [code](https://github.com/grafana/grafana/blob/v5.4.x/pkg/api/login.go#L172-L176). Currently this is sort of supported by configuring `login_maximum_inactive_lifetime_days` to 1, but could probably be improved.

**Comment by bergquist** [comment]
Hmm. We could us hours instead.
And maybe use float instead of an int. So it’s possiblr to set it to 0,1
hours or something like that.

**Comment by bergquist** [comment]
I've been thinking more about this and there seem to be lots of ways we can solve this but I'm not sure its a real problem. I suggest we wait and see what people think. 

If people use that in their setups we can easily fix this in `6.0.1` or `6.1`

**Comment by aocenas** [comment]
I moved this from To Do to Backlog as it does not seem there is anything to do right now about it.

**Comment by marefr** [comment]
Great :+1: We can probably close it soon, but lets keep it open for some more time if there should be anyone having issues with this.

**Comment by L3Ru** [comment]
In Grafana v5.x.x I used this parameter 'login_remember_days' to logout a user on browser close by setting it to zero. It would be great to have some simular behavior in Grafana v6.x.x
