### ISSUE TITLE
"hover tooltip -> stacked value" option doesn't appear when using stack groups

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#15376]
What's up my dear colleagues,
using Grafana v5.4.0 (69c5191) (ops)

I notice that the option "hover tooltip -> stacked value" does not appear when using stack groups in series overrides.
This left us with the tooltip showing cumulative values in the tooltip, which we did not want.
The only way to be able to see, and control, the option is enable the global stack option.

So as a workaround, we enable the global stack option, change stacked value to individual, then disable the global stack again. then we can save the dashboard and get on with our day

**Comment by Dieterbe** [comment]
cc @robert-milan

**Comment by torkelo** [comment]
the hover tooltip cumulative mode does not support stack groups (https://github.com/grafana/grafana/issues/15338). 

Strange, the default value is individual for the hover tooltip, so somehow you must have enabled stack before and changed the value to cumulative and disabled stack.

Closing as it's similar to https://github.com/grafana/grafana/issues/15338
