### ISSUE TITLE
second based intervals in time picker broken for influxDB

### ISSUE THREAD

**Issue by fsauer65** [grafana/grafana#1537]
If you add for example 30s interval to the time picker the $timeFilter added to the influxDB query is broken:

instead of where time > now() - 30s it adds: where time > 30s and time < now()

The reason is this code in 
https://github.com/grafana/grafana/blob/master/src/app/features/influxdb/datasource.js : 

    function getTimeFilter(options) {
      var from = getInfluxTime(options.range.from);
      var until = getInfluxTime(options.range.to);
      var fromIsAbsolute = from[from.length-1] === 's';

      if (until === 'now()' && !fromIsAbsolute) {
        return 'time > ' + from;
      }

      return 'time > ' + from + ' and time < ' + until;
    }

If I remove && !fromIsAbsolute it works as intended, but I am unclear whether that is the right fix or not? what was the rationale behind that other where clause? What if fromIsAbsolute checks if it contains (or perhaps even starts with) the word 'now', would that work?

**Comment by torkelo** [comment]
That change will break absolute time ranges, I can fix this. The absolute time check need to be it looks for a trailing s because get Influx Time returns epochs with a trailing s for absolute dates

**Comment by fsauer65** [comment]
this appears to work - but feels like a hack:

    function getTimeFilter(options) {
      var fromIsAbsolute = !_.isString(options.range.from) || options.range.from.indexOf('now') === -1
      var from = getInfluxTime(options.range.from);
      var until = getInfluxTime(options.range.to);

      if (until === 'now()' && !fromIsAbsolute) {
        return 'time > now() - ' + from;
      }

      return 'time > ' + from + ' and time < ' + until;
    }

**Comment by torkelo** [comment]
fixed in master I think
