### ISSUE TITLE
Sqlite migrates to MariaDB not succeed

### ISSUE THREAD

**Issue by lm123** [grafana/grafana#15379]
### What Grafana version are you using?
5.2.4

### What datasource are you using?
Sqlite3, MariaDB

### What OS are you running grafana on?
CentOS 7.x

We use the following shell script to dump data in sqlites into SQL files:

#!/bin/bash

#Use it like sqlitedump.sh grafana.db > grafanamysql.sql to create the script to insert data into the MySQL database.
#mysql grafana < grafana.sql
#todo:try
DB=$1
TABLES=$(sqlite3 $DB .tables | sed -r 's/(\S+)\s+(\S)/\1\n\2/g' | grep -v migration_log)
for t in $TABLES; do
    echo "TRUNCATE TABLE $t;"
done
for t in $TABLES; do
    echo -e ".mode insert $t\nselect * from $t;"
done | sqlite3 $DB

But after import the SQL into MariaDB, some dashboards cannot work.
What else shall we do after migration data?

**Comment by torkelo** [comment]
please include any errors from grafana server or browser.

**Comment by lm123** [comment]
There is no obvious error reporting after migration. But the dashboard existing before migration cannot be displayed correctly, "No content" will exposed, and API to access dashboard will return the wrong result. 

The correct result to invoke API to access the dashboard after migration:(https://10.75.125.219/grafana/api/dashboards/uid/GYCCRpwiz)

{"meta":{"type":"db","canSave":true,"canEdit":true,"canAdmin":true,"canStar":true,"slug":"import-test","url":"/grafana/d/GYCCRpwiz/import-test","expires":"0001-01-01T00:00:00Z","created":"2019-01-16T02:43:30Z","updated":"2019-01-16T02:43:30Z","updatedBy":"admin","createdBy":"admin","version":1,"hasAcl":false,"isFolder":false,"folderId":0,"folderTitle":"General","folderUrl":"","provisioned":false},"dashboard":{"annotations":{"list":[{"builtIn":1,"datasource":"-- Grafana --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations u0026 Alerts","type":"dashboard"}]},"editable":true,"gnetId":null,"graphTooltip":0,"hideControls":false,"id":6,"links":[],"panels":[{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"cpro","fill":1,"gridPos":{"h":9,"w":12,"x":0,"y":0},"id":2,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"nullPointMode":"null","percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"go_memstats_alloc_bytes","format":"time_series","intervalFactor":1,"refId":"A"}],"thresholds":[],"timeFrom":null,"timeShift":null,"title":"Panel Title","tooltip":{"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}}],"schemaVersion":16,"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"now-6h","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"timezone":"","title":"import-test","uid":"GYCCRpwiz","version":1}}

The wrong result to access the dashboard existing before migration is as following:
(https://10.75.125.219/grafana/api/dashboards/uid/8PSf_U-ik)
{"meta":{"type":"db","canSave":true,"canEdit":true,"canAdmin":true,"canStar":true,"slug":"kubernetes-all-nodes","url":"/grafana/d/8PSf_U-ik/kubernetes-all-nodes","expires":"0001-01-01T00:00:00Z","created":"2019-01-16T02:01:03Z","updated":"2019-01-16T02:01:03Z","updatedBy":"admin","createdBy":"admin","version":1,"hasAcl":false,"isFolder":false,"folderId":0,"folderTitle":"General","folderUrl":"","provisioned":false},"dashboard":{"id":2,"uid":"8PSf_U-ik","version":1}}

The dashboard part miss much content for those migrated dashboards.

**Comment by lm123** [comment]
Some information is already attached.

any progress on this issue?

**Comment by marefr** [comment]
Clearly something is wrong with your migration scripts. I would recommend you to have a look at https://community.grafana.com/t/migrating-grafana-data-to-new-database/2454 and continue discussion there so closing this for now. Would consider reopen if this clearly is a problem in Grafana itself.
