### ISSUE TITLE
Grafana v6-beta1 - React Panels (Gauge) can't set decimal threshold

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#15372]
### What Grafana version are you using?
6.0.0-beta1

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu 18.04 in Docker

### What did you do?
Define a gauge which is calculated by dividing 2 queries that result in a value between 0 and 1. Try to define threshold for 0.2 and 0.7.

### What was the expected result?
Decimals are accepted in the thresholds

### What happened instead?
Can't input anything with a decimal in the threshold, even if I have a value > 0 set for the Decimals values property.

**Comment by torkelo** [comment]
thanks for reporting this!
