### ISSUE TITLE
Add panel only supports Graph plugin?

### ISSUE THREAD

**Issue by michaeldmoore** [grafana/grafana#15370]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by torkelo** [comment]
By default it will add Graph panel, but if you go to visualization tab then you can change to any panel plugin type. 

in beta2 we have updated the add panel widget to look like this:
![image](https://user-images.githubusercontent.com/10999/52577552-a1cf6480-2e22-11e9-8227-2fb612296de4.png)


So you go directly to visualization tab
