### ISSUE TITLE
Make the basic time units millisecond (ms), seconds (s) support plurals for hours and days

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#15375]
The time units that are designed for y-axis user millisecond (ms), seconds (s)  do not have plurals for day and hour. Maybe these should be just `h` and `d` instead or `hours` and `days`. 

so 0.7 days feels ok, but 1 days will look strange.

**Comment by daenney** [comment]
This also affects graph legends.

**Comment by torkelo** [comment]
this has always been the case for these units, so there is no change. There are alternative units called "duration (s)" that can print more human-friendly time ranges that is specifically designed for single stat. 

seconds (s) is meant for y-axis unit, so ms, min, hour, day etc, non have plural versions.

**Comment by dietah** [comment]
Hi, in the new `stat ` panel in 6.7 I am showing a counter that contains the number of days in the database. Even though the unit dropdown says "days (s)", the counter displays the unit as "day" if the number is more than 1. Which does feel a bit weird. I can't change the duration to seconds as the number is stored in influx as days. (same behavior in `singlestat`, so I guess this is a shared component)

Is there a chance this can be fixed or maybe I can look into making a PR somewhere?

Also, I know it is still in beta, the `stat `panel is missing the pre and postfix options. I fixed my dashboard by using the `singlestat `and setting the label "days" as a postfix, as it will only be wrong 1 day a month.

Thanks

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
