### ISSUE TITLE
Allow option to turn off ad-hoc filters in the table panel

### ISSUE THREAD

**Issue by IshaGirdhar** [grafana/grafana#15386]
### What Grafana version are you using?
5.4.3
### What datasource are you using?
Elasticsearch

### Description
Currently for our table panel, we could see ad-hoc filters "Filter for value" and "Filter out vaue" for each column. We don't want to see adhoc-filter popped up when mouse is hovered on our cloumns in our table panel as we dont want to filter for our use case. There should be a way to turn them on and off.

**Comment by kevinclark3** [comment]
Has there been any updates here?

**Comment by amehmoodcapsi** [comment]
This will be a really good option.

**Comment by MrCartoon** [comment]
+1

**Comment by sabir-piludiya** [comment]
Is there any updates regarding this issue?

**Comment by binhvcom** [comment]
+1

**Comment by meishd** [comment]
+1

**Comment by Shawcs** [comment]
+1

**Comment by zoltanbedi** [comment]
This is already possible by adding a field override option with Ad-hoc filterable set to false.
