### ISSUE TITLE
Allow arbitrary pieces of dashboard JSON to be template-able

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1538]
My immediate use case: I'd like a template variable that toggles whether the legends are shown on some or all of my panels. I naively tried adding a template variable to my dashboard that could function as a boolean:

```
      {
        type: "custom",
        name: "showLegends",
        query: "",
        options: [
          { text: "true", value: true },
          { text: "false", value: "false" }
        ],
        current: { text: "true", value: true }
      }
```

and then setting `legend { show: "$showLegends" }` and `legend { show: $showLegends }` but, of course, neither works; the former is a strings that evaluates as a boolean to `true`, and the latter is not a valid `JSON` or javascript object.

I rolled [my own simple JSON templating / string-interpolation functions](https://github.com/hammerlab/grafana-spark-dashboards/blob/330ff7bd18f173039a1751e9cc23c7fac9b8957a/scripts/make-dashboard-json#L79-L103) when generating some Grafana dashboards recently, before I stumbled across Grafana's scripted-dashboards functionality; I wonder if a convention around parsing strings like "${showLegends}" in a dashboard model as referring to a template variable called `$showLegends` would make sense...?

Also relevant to my use case here is #1423

**Comment by torkelo** [comment]
can be solved by using scripted dashboards, or generating dashboards and updating via HTTP  api
