### ISSUE TITLE
Grafana Table data color

### ISSUE THREAD

**Issue by hariravella** [grafana/grafana#15388]
Please include this information:
### What Grafana version are you using?
V5.3.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Linux
### What did you do?
Table Panel Dashboard in light theme
### What was the expected result?
I have threshold color to turn red for few rows. while row-background turns red, the row data should be dark for all the rows 
### What happened instead?
the data in each row turns white and background theme is white, So the table turns blank as the background and data color are same. This works fine Dark theme

**Comment by torkelo** [comment]
think this is fixed in v5.4 (and v6 beta2)

**Comment by hariravella** [comment]
I upgraded to v5.4.2, Issue still persists in light theme

**Comment by torkelo** [comment]
Can you show screenshot? And include panel json and query response?

The text (data) should be white for all cases of when background color to make it readable , you say it turns blank? Is your threshold background color white???

**Comment by hariravella** [comment]
I have some business sensitive information in my dashboard. So i cannot put it here. I simulated the same situation in Grafana Play portal.click on the below link & sort on time & try to find the blank rows in the table.

https://play.grafana.org/d/FqhDdVsmz/table-panel-issue?orgId=1&theme=light&panelId=5&fullscreen

**Comment by marefr** [comment]
Thanks @hariravella confirmed bug. Works as expected in dark theme, but text doesn't render with black text in light theme when threshold doesn't apply (null value returned from datasource).

**Comment by hariravella** [comment]
Do we have a workaround for time-being?

**Comment by marefr** [comment]
@hariravella at the moment the alternative is to use the dark theme or sort by value column having null values so that they appear as the first rows in table.

**Comment by peterholmberg** [comment]
@hariravella is this still an issue in 6.0.1, running on the play site? I don't understand what's wrong?

**Comment by torkelo** [comment]
Try with null values in the table
