### ISSUE TITLE
Prometheus step alignment issue 

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#15385]
### What Grafana version are you using?

6 beta 1

### What datasource are you using?

prometheus

### What did you do?

loog at graph

![inco](https://user-images.githubusercontent.com/291750/52625002-54013d80-2eb0-11e9-98d1-d4c9deb07c78.png)

Last range is partly in the future so we have the impression the rate drops

### What was the expected result?

I should see a warning that the range is partly in the future:

![inco2](https://user-images.githubusercontent.com/291750/52625051-709d7580-2eb0-11e9-9a3e-7c8aa787d7f5.png)

**Comment by roidelapluie** [comment]
Note: picture is ugly ofc. these is probably way better ways to do this.

**Comment by torkelo** [comment]
Can you describe more? I do not understand what the scenario is, what your query returns, and what you wish Grafana to do and why.

**Comment by roidelapluie** [comment]
Related to https://github.com/prometheus/prometheus/issues/4966
 and https://github.com/grafana/grafana/pull/10434

With the query step alignment, we now have queries ending in the future. It is very confusing in dashboards.

**Comment by torkelo** [comment]
It is? The fact that the last datapoint is a bit lower because it might not be complete (all data collected) is a problem for most datasources (query step alignment or not). Not sure this is confusing, maybe because I am used to it with graphite and other push based TSDBs.

The area you marked in the graph has data, so Prometheus is returning data.

Not sure we want to mark ranges in all of Prometheus graphs. Do you think we should remove step and range  alignment ?

**Comment by bcohee** [comment]
It is pretty confusing as it appears to indicate that there is currently a dropoff in stats occurring.  Since our transition to Prometheus 2.x and Grafana 5.x I had to explain to upper management when touring the NOC that we are not currently entering / experiencing an outage - thats just how our graphs look.

I am not so sure the warning mark range suggested by OP would help my case any.  I just wanted to point out that it is indeed confusing as compared to the view on Grafana versions prior to https://github.com/grafana/grafana/pull/10434.

We have been able to mitigate the visual issue (on graph panels and single stat panels with spark lines) by utilizing the `offset $__interval` work-around from https://github.com/grafana/grafana/issues/13419 - but that does put all of our graphs "back-in-time" between 1-15 minutes.

**Comment by torkelo** [comment]
Does anyone have any suggestions for solutions?

**Comment by bcohee** [comment]
I would suggest that the Grafana and Prometheus teams get together to agree on a solution.

From https://github.com/prometheus/prometheus/issues/4966 @brian-brazil mentioned:

> I'd suggest that Grafana not request data from the future.

then later in the thread:

> One thing we (Prometheus team) could maybe do is return back the maximum timestamp currently in the tsdb as an additional piece of information in queries.

**Comment by torkelo** [comment]
I was always opposed to the step alignment feature , thinking it should be handled in Prometheus. So would would be happy to remove it

**Comment by tomwilkie** [comment]
/cc @bergquist @davkal 

Have we considered aligning the end step with the most recent aligned time that isn't in the future?  Ie end/step, not end/step + 1.  Reading the code, this is what it seems to do: https://github.com/grafana/grafana/pull/10434/files#diff-a59431ca1f1f94cdb3ae176c50a585b2R110, so why are we fetching points in the future?

> I was always opposed to the step alignment feature , thinking it should be handled in Prometheus. So would would be happy to remove it

Having steps aligned makes query results cacheable. I'd prefer we didn't remove it.

**Comment by torkelo** [comment]
> Having steps aligned makes query results cacheable. I'd prefer we didn't remove it.

That is good to know! Thanks for the feedback here @tomwilkie .

> Have we considered aligning the end step with the most recent aligned time that isn't in the future?

Yes that might be a way to go. @davidak was this considered when implementing this?

**Comment by bergquist** [comment]
I think you pinged the wrong David :) /cc ping @davkal

> Have we considered aligning the end step with the most recent aligned time that isn't in the future?

I think it would make sense to implement that in the Prometheus datasource.

Another solution would be to always clamp the timerange within Grafana. I know we talked about doing that for other datasources to enable better caching. I'll see if I can find the old issues and create a new issue for that discussion. Regarding this issue. I think it's fine to solve this only for the Prometheus datasource initially.

**Comment by roidelapluie** [comment]
I would be super happy if the step alignement could be deactivated, maybe per query or at the datasource level.

**Comment by roidelapluie** [comment]
The reason we fetch points in the future is because otherwise we have an empty part in the graphs. It would also impact looking at graphs in the past.

**Comment by beorn7** [comment]
It is also an attempt to get the freshest results despite the step alignment. Perhaps that's not that important, after all. (It's only "one unit of resolution" we are talking about here.)

But note that for simple queries, the strategy currently used in Grafana works fine. It gets problematic with more complex queries as explained in https://github.com/grafana/grafana/issues/13419#issuecomment-444123809 .

The easiest solution for now is probably to change the step alignment such that the latest point is still not in the future and accept that some of the freshest data (less old than "one unit of resolution") won't be queried.

**Comment by roidelapluie** [comment]
that would not be good. How much time would it take to realize that the data is really not there anymore?

**Comment by brian-brazil** [comment]
That's the purpose of alerts, not graphs.

**Comment by roidelapluie** [comment]
Should we then throw all our graphes in the trash bin?

**Comment by roidelapluie** [comment]
The best option might be Prometheus computing result at:

(NOW = 36s, step = 10s)
10s 20s 30s

AND between 30 and 36s

Would that be possible?

**Comment by brian-brazil** [comment]
From the Prometheus standpoint, that'd be two queries. You'd only be able to safely cache stuff that's a few hours old, as older timestamps may come in.

**Comment by bergquist** [comment]
If we avoid asking for the last data point there will be a gap in the graph when Grafanas time range doesn't align with the query sent to Prometheus. Which is more correct but it will definitely be confusing for many users. 

I'm, not a big fan of introducing an option for step alignment in the query editor. I think that would be a too advanced feature to expose for most users. People are already struggling with `min step` and `resolution`. 

Right now the only solution I like would be a combination of avoiding having an end date in the future and extend [Grafanas time range](http://docs.grafana.org/reference/timerange/#time-units) feature to enable smart clamping for the whole dashboard. 

`from: now-30m, to: now/15s`

**Comment by roidelapluie** [comment]
Maybe an option like this but to align dashboard to step?
![now](https://user-images.githubusercontent.com/291750/54417543-c741dd80-4702-11e9-894b-f4bff19fc9f0.png)

**Comment by forkbomber** [comment]
Ability to use `$__interval` variable within dashboard's `Now delay now-` field and/or panel's `Add time shift` field would be a practical solution to keep alignment and ensure range's end is never in the future.

Currently (Grafana v5.4.3) `$__interval` variable is ignored entirely in dashboard's `Now delay now-` field while using it in panel's `Add time shift` field results in `invalid timeshift`error.

**Comment by davkal** [comment]
Let me summarize:
Grafana's current alignment feature for Prometheus has the goal of including the data provided by the last scrape that happened between now and the latest aligned point in time. The utility of that is questioned by both bjoern and brian. However, ignoring that point and hard-aligning on the latest point in time will leave a gap as pointed out by Carl. Tom likes the cacheability of aligned data.

The uninformed viewer will find issues with both approaches: user looking at the "same" unaligned query data on multiple dashboards will see different results; users looking at aligned data will see an alarming drop or gap at the end of the graph.

Let's look at solutions:

1) Ending on the last aligned step in the past will leave a gap on the right hand side. This seems like the least desirable option. 

2) Introducing an alignment option would leave it to the dashboard maintainer to choose the compromise, either get the drop or varying graph lines. This should probably be done on a datasource level. (Could this become problematic if within an organization both options are being used?)

3) The datasource plugin could request the last aligned step in the past, plus run an instant query to get the latest datapoint (similar to [Trickster's fast-forward](https://github.com/Comcast/trickster#3-fast-forward)). This would need 2 queries per query row, but the range query could be cached.

4) Prometheus could serve already aligned data with the first and last datapoint to be potentially misaligned. This would provide exactly the data we need, but it would not be cacheable though.

Anyone see any other options?

**Comment by brian-brazil** [comment]
I'd go for 1, and it's what I've seen many other monitoring systems do without much complaint.

**Comment by roidelapluie** [comment]
FYI: What elasticsearch is doing: ![es](https://user-images.githubusercontent.com/291750/54445093-620edc00-4744-11e9-8a81-73af386dc5fe.png)

**Comment by beorn7** [comment]
FTR: I have described the work-around currently used at SoundCloud [here](https://github.com/grafana/grafana/issues/13419#issuecomment-444186213). It is clearly worse than (1), but still better than the current state.

If we go for (1), we could avoid the gap cosmetically by letting the right side of the graph coincide with the aligned time stamp. Once the next aligned time stamp has reached the present, the graph would “jump” one unit of resolution.

(3) is probably the cleanest of all options. The instant query should be so fast compared to the range query that the overhead shouldn't matter that much.

It could also be a mixed solution where (3) is only applied if the final time stamp is sufficiently far away from the most recent aligned time stamp. (It's not really worth the effort if you only render something half a pixel to the right of the most recent aligned time stamp.)

I initially liked (4), too (see idea (3) in https://github.com/prometheus/prometheus/issues/4966 ), but it comes with a lot of caveats, as can be seen by the points @brian-brazil came up with in https://github.com/prometheus/prometheus/issues/4966 . It would go against a number of existing assumptions. (We could, of course, only switch on that behavior on demand via a query parameter.)

**Comment by torkelo** [comment]
Don’t think 3 is reasonable, Prometheus lacking batch query api is already
a problem resulting in too many separate network requests being made.

Only think option 1 is a valid option ,or keep as is, or let everything be
handled in Prometheus (it could handle internal step alignment to facility
caching and make sure the last data was included etc).

/T

fre 15 mars 2019 kl. 22:52 skrev Björn Rabenstein <notifications@github.com

**Comment by beorn7** [comment]
If Prometheus lacking query batching is actually a problem for Grafana, we should solve that part anyway. If it is a problem already now, it is a problem either way. It should not keep us from picking the best solution here.

From the Prometheus point of view, adding batch queries is probably much easier and much more organic to add than any kind of step alignment or caching facilitation. The latter doesn't really gel well with Prometheus's execution model, and query results are only really cacheable after the grace period during which “samples from the past” are still accepted. (Not even talking about the recently added backfilling capabilities… but at least, it's quite obvious that caches have to be invalidated once you backfill.) We had a larger discussion around this when Trickster came along.

**Comment by beorn7** [comment]
“Keep as is” is not really an option IMHO. https://github.com/grafana/grafana/issues/13419#issuecomment-444123809 explains how bad this will end. Please also think about SingleStat or pie charts. If not crafted carefully, they will easily display arbitrarily reduced values (and not just an easy to ignore drop at the end of the graph). It has already caused a lot of confusion at SoundCloud, and not everybody has as much bundled Prometheus competence as we to troubleshoot…

**Comment by davkal** [comment]
Going a head with 1.
It's the combines the cache and comparability benefits while not introducing too much complexity.

**Comment by bergquist** [comment]
@davkal SGTM 

Let's see how the gap looks at different time ranges.

**Comment by davkal** [comment]
PR is ready. The visual gap with a dynamically calculated step is not noticeable. But when you specify a big step manually, you'll get a gap up to step-length. I'm happy with this.
Would be good for others in the thread to take a look at this PR: #16110
