### ISSUE TITLE
On Explorer with Loki not show labels on log list

### ISSUE THREAD

**Issue by lfdominguez** [grafana/grafana#15393]
### What Grafana version are you using?
Master v6.0.0-pre3 (e38cfc1)

### What datasource are you using?
Loki

Hello I'm testing Loki with fluentd and code an addon to the fluentd loki ingestor to add support for dynamic labels (get the value from the message). I'm currently use Docker Swarm in my infra with fluentd docker log driver. All works great, but in the explorer UI are showed the labels on the menu of labels, but when i active to show labels on the logs list not show me nothing, are these labels hardcoded?

![image](https://user-images.githubusercontent.com/5604131/52636133-c155a400-2e99-11e9-9aa9-5d31c4045f02.png)

Here you can see how the label `test` exists and the query if for label `ueb`, but in the logs panel not show me any label.

**Comment by torkelo** [comment]
thanks for reporting this, we will fix asap!

**Comment by dprokop** [comment]
@lfdominguez Thanks for your report.

Labels displayed in the explore's logs list are those that are unique to a given log entry in a logs stream. Can you please provide us with a response you get for a given query?

@davkal Can you take a look at this, please?

**Comment by davkal** [comment]
I'm suspecting loki as well. Would be great to get a screenshot of the query response from the browser dev tools. 
Another thing you can try is using [logcli](https://github.com/grafana/loki/blob/master/docs/logcli.md) to check if loki returns correct labels. It's my feeling that the labels will be empty.

**Comment by davkal** [comment]
It would be great to get verification via logcli. And if no labels are returned, then we should open an issue in the loki repo.

**Comment by lfdominguez** [comment]
ok will go to print screen

**Comment by lfdominguez** [comment]
yeap, response from Loki without labels

![image](https://user-images.githubusercontent.com/5604131/52648185-156d8200-2eb4-11e9-927e-110942897be2.png)

**Comment by davkal** [comment]
Issue moved to [grafana/loki #322](https://github.com/grafana/loki/issues/322) via [**ZenHub**](https://www.zenhub.com/)

**Comment by davkal** [comment]
Thanks for verifying. we've migrated this issue to grafana/loki

**Comment by lfdominguez** [comment]
With the last version of loki, now is sending the labels to grafana, but grafana not show them...

![image](https://user-images.githubusercontent.com/5604131/52664994-6f803e80-2ed8-11e9-97ce-333d14c21482.png)

**Comment by lfdominguez** [comment]
can be reopened the Issue please?

**Comment by torkelo** [comment]
It’s still a bug in Loki as it’s only returning one stream

**Comment by lfdominguez** [comment]
> It’s still a bug in Loki as it’s only returning one stream

No, already is sending the labels....

**Comment by torkelo** [comment]
yes, for one stream. And grafana is showing them in your screenshot (see Common labels). The log lines table only shows labels if there are more more than one value for one label name

**Comment by lfdominguez** [comment]
ohh let me check

**Comment by lfdominguez** [comment]
Can check that always send the labels of the first log.... i will send some logs with differents sets of labels and is showed on list, but Loki not send to back....

![image](https://user-images.githubusercontent.com/5604131/52811930-51474980-3064-11e9-84b8-252af007cb39.png)
