### ISSUE TITLE
iframes no longer work in HTML Text panel - 6 Beta

### ISSUE THREAD

**Issue by Andysimcoe** [grafana/grafana#15392]
### What Grafana version are you using?
Grafana v6.0.0-beta1 (d7f81c4)

### What datasource are you using?
HTML iframe

### What OS are you running grafana on?
Official Docker container - tag v6.0.0-beta1

### What did you do?
Text panel, select HTML. Add an iframe, eg:
<iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=53.775&lon=-3.252&zoom=5&level=surface&overlay=wind&menu=&message=true&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=55.952&detailLon=-3.196&metricWind=mph&metricTemp=%C2%B0C&radarRange=-1" frameborder="0"></iframe>

### What was the expected result?
To display the iframe - above is a working example for 5.x

### What happened instead?
The <iframe> tag isn't recognised as HTML, the output is just the text as above.

**Comment by dprokop** [comment]
@Andysimcoe this is related to the breaking changes introduced in 6.0: 

> The text panel does no longer by default allow unsantizied HTML. #4117. This means that if you have text panels with scripts tags they will no longer work as before. To enable unsafe javascript execution in text panels enable the settings disable_sanitize_html under the section [panels] in your Grafana ini file, or set env variable GF_PANELS_DISABLE_SANITIZE_HTML=true.

https://github.com/grafana/grafana/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by Andysimcoe** [comment]
Ah thanks, I thought I'd checked the change log. 

Cheers,
