### ISSUE TITLE
Refactor Select Interfaces

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#15390]
`CommonProps` and `SelectProps/AsyncSelectProps` interfaces are always used together (i. e. `CommonProps & Select Props`). Can we refactor those:

* `CommonProps` -> `BasicSelectProps` (CommonProps don't say much when reading code)
* `SelectProps` -> `extends BasicSelectProps { ... }`
* `AsyncSelectProps` -> ` extends BasicSelectProps { ... }`

**Comment by torkelo** [comment]
this is marked as in progress, anyone working on this?
