### ISSUE TITLE
Create a window size store/reducer

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15403]
We have some components and pages that care about page width (DashboardGrid & Explore). 

Would be nice to have this in redux, and have a single window resize event listener (with some debounce). 

Thinking of having two props, windowWidth, and  pageWidth (windowWith - sidemenu if open). So need to listen to sidemenu hide/show as well. Then we could actually remove the need for AutoSizer in Explore and react-sizme in DashboardGrid.

**Comment by dprokop** [comment]
Closing this one, we haven't found a need for this in long months. May be re-opened if we feel like this is necessary
