### ISSUE TITLE
A way to Refresh Loki Labels in labels dropdown 

### ISSUE THREAD

**Issue by lfdominguez** [grafana/grafana#15402]
### What Grafana version are you using?
Master v6.0.0-pre3 (e38cfc1)

### What datasource are you using?
Loki

On explorer view, how is updated the list of `Log labels` because when i put any new label on Loki, then Grafana not show me the new labels, i need to refresh the browser tab to see the new labels on the menu. This is related to grafana/loki#322 ???

**Comment by torkelo** [comment]
@davkal any ideas if this is a bug or by design?

**Comment by davkal** [comment]
There is no refresher in place, so this is more of a feature request.

**Comment by torkelo** [comment]
@davkal do you have UX idea for this? where / when to do the refresh?

**Comment by dprokop** [comment]
@torkelo I was thinking about two solutions here actually
1. Refetch the labels every time user opens the labels selectoe
or
2. Do basically the same thing, but use short term cache like(i.e. 1min) not to do too many requests.

I think this could be a good first iteration of nailing this issue.

**Comment by davkal** [comment]
The label request takes 100ms on small systems and up to 1000ms on big systems. Initially I was thinking of having a timer do regular refreshs. But on demand with a 1 minute throttle sounds good too, and is more intentional than an timer.

**Comment by davkal** [comment]
There needs to be some logic to refresh the value lists too.
