### ISSUE TITLE
Tooltip does not render strings with line break

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#15421]
I can not get the Tooltip to render a string with line breaks correctly. I've tried with these alternatives

```
`Query error
      status: ${err.status}      
      message: ${err.statusText}`
```
and 

```
'Query error \n' + 'status: ' + err.status + '\n' + 'message: ' + err.statusText
```

but still the Tooltip renders these as on line.

**Comment by torkelo** [comment]
Closing this as I think for linebreaks we need to use markup content
