### ISSUE TITLE
Remove Hipchat notifier

### ISSUE THREAD

**Issue by leonallen22** [grafana/grafana#15426]
Hipchat & Stride are being phased out due to Atlassian's new partnership with Slack.
According to the FAQs:
```
The end-of-life dates for each products are below:

    Stride: February 15th, 2019
    Hipchat Cloud: February 15th, 2019
    Hipchat Data Center (v3.0): June 22nd, 2019
    Hipchat Data Center (v3.1): September 26th, 2019
    Hipchat Server (v2.1): December 8th, 2018
    Hipchat Server(v2.2): May 30th, 2019 
    Hipchat Server (v2.4): June 30th, 2020
```
The EOL for the most recent version of Hipchat Server is not until next year, but it might be a good time to consider removing hipchat integration and timing for release. More info at:
 https://www.atlassian.com/partnerships/slack/faq#faq-dd86cc59-c2f0-42ef-a2fe-ad5c2f475da9

**Comment by armandgrillet** [comment]
Might become a higher priority due to https://github.com/grafana/grafana/pull/47156#issuecomment-1094995320

**Comment by armandgrillet** [comment]
I am closing this as Hipchat is [not supported in the new alerting system](https://github.com/grafana/grafana/blob/fe3a27a2ab2505dea03c57839e8d61c2b0b8b68f/docs/sources/alerting/unified-alerting/opt-in.md#L44) and this issue will thus go away once legacy alerting is deprecated.
