### ISSUE TITLE
Exposing Grafana via Kubernetes Proxy results to side menu broken links

### ISSUE THREAD

**Issue by spyros87** [grafana/grafana#15422]
### What Grafana version are you using?
Version 5.4.3 (commit: 6539180, branch: HEAD)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Whatever image the Docker container `grafana/grafana:5.4.3` has.

### What did you do?
I am using Grafana as part of Prometheus Operator on Kubernetes. As I would like to expose Grafana board via the native `kubectl proxy`, I stumbled upon a weird issue where the links of side menus are completely messed up.

To be exact:
Grafana UI is available via `http://localhost:8001/api/v1/namespaces/monitoring/services/http:test-prometheus-operator-grafana:service/proxy/` which shows the `Home Dashboard` as expected.

### What was the expected result?
By choosing to navigate to a specific dashboard (e.g. k8s-compute-resources-cluster) the link would have redirected me to the intended one having a ulr like `http://localhost:8001/api/v1/namespaces/monitoring/services/http:test-prometheus-operator-grafana:service/proxy/d/efa86fd1d0c121a26444b636a3f509a8/k8s-compute-resources-cluster` (which works manually).

### What happened instead?
However, when I tried to navigate to the aforementioned dashboard, the routing of the dashboard was broken and linked to `http://localhost:8001/d/efa86fd1d0c121a26444b636a3f509a8/k8s-compute-resources-cluster` instead. This link obviously does not exist.

### If related to metric query / data viz:
No, metrics work fine

**Comment by spyros87** [comment]
Related to issue #13459

**Comment by marefr** [comment]
Dup of #15422

**Comment by marefr** [comment]
Have you tried setting grafana [root_url](http://docs.grafana.org/installation/configuration/#root-url) to your k8s proxy address?

**Comment by spyros87** [comment]
@marefr The `root_url` must be defined inside `grafana.ini` file or in different configuration for the proxy?

**Comment by marefr** [comment]
Just follow the root_url link in my earlier comment and you see that I mean grafana.ini.

**Comment by spyros87** [comment]
@marefr Thank you for your assistance and time. Have a great day!
