### ISSUE TITLE
Client side JS is not GZIPed

### ISSUE THREAD

**Issue by cypressious** [grafana/grafana#15425]
### What Grafana version are you using?
Grafana v5.4.2
### What did you do?
Inspect the Network Explorer in my browser for any Grafana related JS file, e.g. https://dashboards.gitlab.com/public/build/vendor.dfabdd44b3be44288eac.js
### What was the expected result?
The transferred JS files should be GZIPed
### What happened instead?
The uncompressed files were transmitted

![grafik](https://user-images.githubusercontent.com/1191816/52724446-a1b09f80-2faf-11e9-9844-efec947ea510.png)

**Comment by marefr** [comment]
You can enable gzip in Grafana. We have an open issue to document this setting https://github.com/grafana/grafana/issues/15322

**Comment by brunorey** [comment]
This has been added to the documentation: http://docs.grafana.org/installation/configuration/#enable-gzip
