### ISSUE TITLE
Can We use maths scripts in grafana similar to Kibana's visual builder?

### ISSUE THREAD

**Issue by UKSFM99** [grafana/grafana#15433]
### What Grafana version are you using?
Grafana 6.0.0 beta 2
### What datasource are you using?
Elasticsearch 6.6.0
### What OS are you running grafana on?
Ubuntu

Now that grafana 6.0.0 has support for bucket script aggs, is it possible to do the same for maths aggregation functions that Kibana's visual builder includes? 

This is purely because within the maths agg in visual builder, there is a variable called "params._interval", which returns the data historgram bucket window in milliseconds. This is very useful for generating EPS (Events per second) charts.

Is there any plan to support this feature, or, is there a way in Grafana, that im not aware of, by which we can take a count metric and get the 'count per second' average?

**Comment by marefr** [comment]
You can use Grafana's builtin variable `$__interval_ms` in the script field of the bucket script aggregation. Is that enough for you? Reference http://docs.grafana.org/reference/templating/#the-interval-ms-variable

**Comment by UKSFM99** [comment]
This works.
Thanks. Ill remeber to read the documentation first :+1:
