### ISSUE TITLE
[Feature Request] Variable Lables

### ISSUE THREAD

**Issue by soloam** [grafana/grafana#15437]
Hello, it would be nice to allow lables to the variables, for example:

![image](https://user-images.githubusercontent.com/11949987/52782520-33b7b700-3047-11e9-9c5a-4f2f3044fa5f.png)

It would be nice to allow a way to say that:
air_conditioner => Air Conditioner 
dishwasher => Dishwasher
main => Main Power
washing_machine => Washing Machine

Thank you

**Comment by marefr** [comment]
If you're asking about generic support for key/value in variables of type query or custom there's already an open feature request for that in #3478 so I'm closing this as a duplicate.

But I should mention that it's sort of already supported, but depends on which datasource you're using, for example the SQL datasources you can define and return key/values in query, see for example http://docs.grafana.org/features/datasources/mysql/#query-variable.
