### ISSUE TITLE
Slack Alerts URL are directing to the "edit dashboard" URL 

### ISSUE THREAD

**Issue by AvnerCohen** [grafana/grafana#15439]
Please include this information:
### Grafana Version
Grafana version 5.4.1
### What did you do?
Set up alert via slack channel with image.
### What was the expected result?
Alert URL should point to  a *view* link of the grafana dashboard
### What happened instead?
An *edit* view was created

Happy to provide a PR for that, just want to make sure it makes sense.

1. When the slack notifications is sent, the URL is retrieved via `evalContext.GetRuleUrl()`:
https://github.com/grafana/grafana/blob/a8b8af9742ae3b3b9be5af6d28cc1aede3f32f42/pkg/services/alerting/notifiers/slack.go#L146

2. `GetRuleUrl` in turn hard codes the format of the dashboard:
https://github.com/grafana/grafana/blob/862815d18de44d23d2cc58b9ddb6d97a8940664c/pkg/services/alerting/eval_context.go#L107

 With `edit=true`, which should not be added in this case.

Options I see to solve:
1. Create a new GetNonEditableRuleUrl().
2. Updated the url and remove "edit=true" inside Notify()
3. Allow passing a param (editable?) and control that.

Happy to help with impl.

**Comment by marefr** [comment]
Related to #12176

**Comment by AvnerCohen** [comment]
@marefr Actually from what I see, the hard coded formatted url already have fullscreen=true, so not 100% sure it's the same thing (the title of #12176 is `Option to have fullscreen graph URL`)
But if the direction is to "make it configurable", then I guess it is related.

What I am suggesting however is a quick bug fix before the feature, it makes no sense to send alert to the edit view. The exact format of the end point graph and its customization is probably another feature, that I assume, is more complex to implement.

**Comment by marefr** [comment]
The referenced issue is basically fullscreen panel without edit mode as I understand it. I would say we  don't want to have this configurable.

**Comment by AvnerCohen** [comment]
Any thoughts about direction for a PR on this I can contribute? happy to help just want to make sure I implement something that is inline with project direction.

**Comment by marefr** [comment]
@bergquist you may have important input on this one?

**Comment by bergquist** [comment]
The reason we link to the alert tab in edit mode is to show all settings for an alert. Which is useful for understanding why it triggered. 

Only showing the graph panel is not always useful data depending on the metric query.

**Comment by AvnerCohen** [comment]
Thanks @bergquist.
> Only showing the graph panel is not always useful data depending on the metric query.

I think the key here is "not always", sometimes it *is* helpful without (actually in our case it's always, but can totally see there are other valid scenarios).
I guess when more than one working option is possible, this is where configuration becomes a valid option?

btw - not sure, but would that even work if the slack notification is sent to someone without "edit" privileges ?

**Comment by bergquist** [comment]
Since this has only been requested once it does not warrant a configuration. We are very restrictive about introducing new settings. We are currently looking into how we want to redesign alerting in Grafana. Hopefully, this will be partially solved in the next generation of grafanas alerting. 

Viewers can see the definitions but not save it.
