### ISSUE TITLE
Any way to change Y-axis's MAX and MIN Value for one graph panel?

### ISSUE THREAD

**Issue by haibuo1981** [grafana/grafana#15431]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Refer to documentation: http://docs.grafana.org/features/panels/graph/#axes
