### ISSUE TITLE
Feature request: Use formulas instead of constants for the coloring of singlestats panel

### ISSUE THREAD

**Issue by jeromegit** [grafana/grafana#1543]
Right now the coloring (typically: green, orange, red) of singlestats panel is based on 3 CSV constant thresholds. It would be nice to be able to specify formulas instead such as:
 * green if over avg for the past 30 days
 * orange if between 25-50 percentile for the values in the past 30 days
 * red if below 25 percentile for the values in the past 30 days

Thanks.

PS: Thanks again for creating such an awesome tool!

**Comment by torkelo** [comment]
Those formulas would require other metric queries and time ranges. But sounds awesome :) 

Things like this is better accomplished with some alerting and continuous query framework (something that we will work on soon)

**Comment by bbinet** [comment]
+1
And it would also be great to be able to assign custom colors to discrete values.

**Comment by jeromegit** [comment]
Thanks for the prompt response, Torkel.
I was thinking about using timeStack() and min/average/maxSeries() to
achieve that goal.
Look forward to the new features of 2.0 also!

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
