### ISSUE TITLE
row title not updated correctly when referencing variable

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#15447]
Operating System: CentOS 6
Grafana Version: 4.5.2
Backend: influxdb 1.7.2

In one dashboard I have a "host" variable that allows "All" and "Multi-option" for selecting hosts based on this query:
SHOW TAG VALUES FROM mysql WITH key = "host"

There is one row for the dashboard. The "Title" field of the row is "$host" and "Repeat for" is "host". All of the graphs in the row use $host in their title.

Lets say that when I go to this dashboard it always shows me a single row for host A. When I click on the "host" variable drop down, "host A" is not selected - even though results for it are being displayed. If I now unselect host A and choose host B and host C from the variable drop down, I have two rows:
row 1 has a title of "host A" but all of the graphs include "host B" in the title.
row 2 has a title of "host C" and all of the graphs include "host C" in their title.

If I click on the settings wheel for row 1, it shows "Title $host". If I then click "update", the row gets the correct title.

**Comment by marefr** [comment]
You're using a very old version of Grafana. Please upgrade to the latest version. I should add that we've fixed a v5.4.3 bug (#15133) similar to this and that fix will be included in Grafana v6.0 stable (nightly builds  and beta2 available now).
