### ISSUE TITLE
feature request: group by time - calendar intervals

### ISSUE THREAD

**Issue by mluedke** [grafana/grafana#1544]
It would be nice to have the ability to group by time based on calendar week or month or day.  My use case is that I am graphing daily costs, but would like the ability to view month over month costs. E.g. what were the total costs in January and what is the total cost so far this month.  This is not the same as group by time 30d.

**Comment by torkelo** [comment]
@mluedke you need to request this feature from InfluxDB  (I guess that is the time series database your are using). This cannot be implemented in Grafana.   (and it is already implemented in Graphite)
