### ISSUE TITLE
Enable support for custom s3 like endpoints for external image storage

### ISSUE THREAD

**Issue by gksinghjsr** [grafana/grafana#15445]
Grafana supports s3 as a datasource for external image storage. However, it does not support custom S3 like storages, which are AWS S3 compatible.

**Comment by marefr** [comment]
> like sotrages

Don't know exactly what you mean. Can you update the description with some more information? Thanks

**Comment by gksinghjsr** [comment]
@marefr updated the description.

**Comment by marefr** [comment]
Duplicate of #8157
