### ISSUE TITLE
v6.0.0-beta2 - Gauge loses precision

### ISSUE THREAD

**Issue by Paul-Reed** [grafana/grafana#15459]
### What did you do? 
Added a 'new' Gauge to a dashboard, in Visualization set Units to Watt(W) & Decimals to 2.
### What was the expected result?
I expected that the precision would remain at 2 decimal places throughout it's range, which it does up until the power reading reaches 1000W - 1kW.
![999w](https://user-images.githubusercontent.com/973580/52862044-1c062e80-312c-11e9-91b1-e16e7dcfc21b.png)

### What happened instead?
When the power reading reached 1140W, the Gauge displayed `1kW` instead of `1.14kW`, so I have lost all precision.
When the power reading reached 1600W, instead of displaying `1.60kW` it displayed `2kW`
![2kw](https://user-images.githubusercontent.com/973580/52862064-23c5d300-312c-11e9-9418-583c430a64d6.png)

**Comment by marefr** [comment]
Testing now in master and seem to have been resolved so closing this. Fix will be included in upcoming beta3 release.
