### ISSUE TITLE
Rendered dashboard failded after add ROWs

### ISSUE THREAD

**Issue by Cloudox** [grafana/grafana#15451]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
V5.0.0

### What datasource are you using?
zabbix

### What OS are you running grafana on?
centOS

### What did you do?
add some rows for my dashboard‘s panels

### What was the expected result?
rendered dashboard success by this url：
http://xxx.xxx.com/render/d/uid/dbname?from=1549848134800&to=1549898859961&var-datasource=ds&width=1500&height=700&tz=UTC%2B08%3A00

PS: Before adding rows, I can get dashboard png success.

### What happened instead?
url request timeout, get image failed

### If related to metric query / data viz:
no

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Thanks for answer!

**Comment by torkelo** [comment]
Can you upgrade to latest stable? Your running a very old version of Grafana, and this issue has been resolved (likely in v5.1))
