### ISSUE TITLE
Make configuration/admin pages more mobile friendly

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#15456]
### Motivation

Currently the configuration pages and server admin pages aren't very responsive. In mobile view the content is too wide and clickable objects too small(buttons, inputs and dropdowns). A lot of the content are tables with multiple columns. Some of the columns have actions in them such as remove or change role. 

### Suggested solution

To improve the mobile experience we should make sure the content fits the screen. The big issue are the tables. Here we should hide some of the content. We keep the columns with the avatar and the login name. We also show the most important of the rest of the columns and make it changeable to any of the other columns. We also always show the column with delete button. 

We must also make it easier to click objects. Here we simply make them bigger. Recommended min width and height for clickable objects are 44px so I think we should stick with that. 

<img width="1440" alt="screenshot 2019-02-15 at 13 24 39" src="https://user-images.githubusercontent.com/23470681/52856583-21ac4600-3125-11e9-9029-eee7a96dc441.png">

<img width="1440" alt="screenshot 2019-02-15 at 13 24 47" src="https://user-images.githubusercontent.com/23470681/52856595-2b35ae00-3125-11e9-978f-ea672dac9029.png">

### Actions

- [ ] Create a button style for mobile devices
- [ ] Create table dropdown to change columns
- [ ] Create table style for mobile devices

**Comment by torkelo** [comment]
moving this from ToDo column, not sure this is a top prio right now.
