### ISSUE TITLE
No plugin gets listed on dashboard

### ISSUE THREAD

**Issue by gmailkrpavithra** [grafana/grafana#15460]
Read before posting: 

Please include this information:
### What Grafana version are you using?
v6.0.0-beta1

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Redhat
### What did you do?
Upgrade from version 4.2.0 to v6.0.0-beta1

### What was the expected result?
Plugins that are installed in the server should be listed on the dashboard page as options to create panels

### What happened instead?
Plugins get listed correctly when i list it in the server
t=2019-02-15T15:35:45+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2019-02-15T15:35:45+0000 lvl=info msg="Registering plugin" logger=plugins name="Bubble Chart"
t=2019-02-15T15:35:45+0000 lvl=info msg="Registering plugin" logger=plugins name=Multistat
t=2019-02-15T15:35:45+0000 lvl=info msg="Registering plugin" logger=plugins name=Histogram
When i create a new dashboard and try to create a new panel, it does not list me any option. By default, it creates only panel of type Graph.
I tried removing all the other plugins and kept the list to the above minimum to check if the plugins that are due for update give the issue. However, that did not help.
There is no error in grafana.log
The plugins list are picked up right from my custom path
I checked this link https://github.com/jdbranham/grafana-diagram/issues/19 which is similar and tried clearing the cache. But no help. That does not work in any of the browsers

**Comment by gmailkrpavithra** [comment]
The option seems to be different from the screenshot that i viewed on the dashboard features of v5. 
I got around it by creating a new panel and then go to Visualization and change the type. 
Is this the way to create a panel of specific type ? If so, you may close this request.

**Comment by torkelo** [comment]
Try beta2, it makes it easier to get the visualization selection. You can change panel type in the visualization tab.

**Comment by gmailkrpavithra** [comment]
Thank you, will definitely upgrade.
