### ISSUE TITLE
PNG export stops working with latest docker image

### ISSUE THREAD

**Issue by BenGig** [grafana/grafana#15469]
With the latest docker image (Feb. 15, 2019 04:53 PM), sharing of PNG images does not work anymore. The log shows a timeout message. With image 6.0.0-beta2, the rendering works fine.

Call: 
wget -q -O test.png --no-check-certificate "https://mygrafana:3000/render/d-solo/FZXReO_mk/regen?orgId=2&panelId=2&from=now-24h&to=now&width=600&height=310&tz=Europe%2FZurich"

Server error log:
t=2019-02-16T11:26:03+0000 lvl=info msg=Rendering logger=rendering path="d-solo/Vq7OgKlmk/temperatur?orgId=2&panelId=2&from=now-24h&to=now&width=600&height=310&tz=Europe%2FZurich"
t=2019-02-16T11:26:05+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-02-16T11:26:05+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=2 uname= error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-02-16T11:26:05+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=2 uname= method=GET path=/render/d-solo/Vq7OgKlmk/temperatur status=500 remote_addr=192.168.6.20 time_ms=62002 size=1782 referer=

**Comment by BenGig** [comment]
Correct call was:
wget -q -O /tmp/grafana.png --no-check-certificate https://mygrafana:3000/render/d-solo/Vq7OgKlmk/temperatur?orgId=2&panelId=2&from=now-24h&to=now&width=600&height=310&tz=Europe%2FZurich

**Comment by torkelo** [comment]
What panel type & json do you have? How long does the query for that panel take?

**Comment by BenGig** [comment]
Time for a PNG render with 6.0.0-beta2 (no measurements for 'latest', queries never return successfully):

real    0m0.949s
user    0m0.005s
sys     0m0.004s

I export 3 different panels, the one I provide information for is the most complex (still a simple one I think). They all render in 0.9 - 1s, all are Graph panels with 2 - 6 data queries, approx. 5 - 20 min interval for the data points, 12h render interval.

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "fill": 0,
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "interval": "",
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "paceLength": 10,
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {
          "alias": "aussen",
          "color": "#5195ce",
          "fill": 1
        },
        {
          "alias": "Wohnzimmer",
          "color": "#f2c96d"
        },
        {
          "alias": "Atelier",
          "color": "#e24d42"
        },
        {
          "alias": "Taupunkt",
          "color": "#bf1b00"
        },
        {
          "alias": "Feuchte Wohnzimmer",
          "color": "#629e51",
          "dashes": true,
          "yaxis": 2
        },
        {
          "alias": "Feuchte aussen",
          "color": "#806eb7",
          "dashes": true,
          "yaxis": 2
        }
      ],
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "alias": "Wohnzimmer",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "6m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "temperature",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "max"
            }
          ],
          "query": "sensor:ardu_192.168.6.194",
          "refId": "C",
          "timeField": "@timestamp"
        },
        {
          "alias": "aussen",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "15m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "temperature",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "max"
            }
          ],
          "query": "sensor:HM_Wetterstation",
          "refId": "A",
          "timeField": "@timestamp"
        },
        {
          "alias": "Atelier",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "25m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "temperature",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "max"
            }
          ],
          "query": "sensor:EnO_Temp01",
          "refId": "B",
          "timeField": "@timestamp"
        },
        {
          "alias": "Taupunkt",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "20m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "dewpoint",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "max"
            }
          ],
          "query": "",
          "refId": "D",
          "timeField": "@timestamp"
        },
        {
          "alias": "Feuchte Wohnzimmer",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "6m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "humidity",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "max"
            }
          ],
          "query": "sensor:ardu_192.168.6.194",
          "refId": "E",
          "timeField": "@timestamp"
        },
        {
          "alias": "Feuchte aussen",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "20m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "humidity",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "max"
            }
          ],
          "query": "sensor:HM_Wetterstation",
          "refId": "F",
          "timeField": "@timestamp"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Temperatur / Feuchtigkeit",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "celsius",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "decimals": null,
          "format": "percent",
          "label": null,
          "logBase": 1,
          "max": "100",
          "min": "0",
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 17,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "Temperatur",
  "uid": "Vq7OgKlmk",
  "version": 2
}

**Comment by BenGig** [comment]
Ok, I just went to 'latest' again (Feb . 16): it's working fine now.
