### ISSUE TITLE
Dashboard not populating the data for dockers

### ISSUE THREAD

**Issue by amirakhan** [grafana/grafana#15461]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What did you do? We have installed docker and containers running influxdb, telegraf mapped with each host & grafana it is working perfectly fine on ubuntu which is connected to the internet however when we try to run the same images on influxdb, telegraf & grafana it is specifically not working for dashboard 1150, the exact same config works fine for ubuntu with internet connectivity however does not work for red hat which is offline 
verified the connectivity and all other dashboard like 1138 works fine
verified all docker related inputs have been enabled in telegraf agent
### What happened instead? it does not show the data
<img width="341" alt="working" src="https://user-images.githubusercontent.com/45394063/52871598-67423080-3170-11e9-8d10-c84ef48a9284.PNG">
<img width="218" alt="non working" src="https://user-images.githubusercontent.com/45394063/52871607-6c9f7b00-3170-11e9-8195-519520132da3.PNG">

**Comment by torkelo** [comment]
This looks like support question.

Please ask questions on the community site https://community.grafana.com
