### ISSUE TITLE
graph panel toggle

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15467]
What Grafana version are you using?
5.4.3
What datasource are you using?
InfluxDB
What OS are you running grafana on?
Windows 10
Is there a way to toggle(show/hide) panels in a grafana dashboard?
If there is, do let me know, otherwise it would be a nice addon.

**Comment by torkelo** [comment]
There is not, there is a row "panel" that you can add which allows you to hide many panels (collapse the row)
