### ISSUE TITLE
Populate multiple panels from single query

### ISSUE THREAD

**Issue by anayrat** [grafana/grafana#15472]
### What Grafana version are you using?

5.4.3

### What datasource are you using?

PostgreSQL

### What OS are you running grafana on?

Linux

### What was the expected result?

I have an expensive query which returns many columns. So I can't display all of them on one panel. I have no choice to repeat my query and select column for each panel. It is not efficient at all.

I would be great if it is possible to populate multiple panel from one query.

**Comment by torkelo** [comment]
we building a multi series feature for new react panels that will allow them to repeat for each series / row your query returns 
https://github.com/grafana/grafana/pull/15294
