### ISSUE TITLE
Gauge panel missing auto decimals logic

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15474]
New gauge panel does not handle auto decimals logic like single stat. 

* [ ] Determine auto decimals
* [ ] Round value based on decimals and use this for threshold calculation. (see single stat for reference) 

For this need to:
* Copy getDecimalsForValue and tests from ticks.ts file from the PR linked below
* Update singlestat module.ts to use this method instead of it's internal function

https://github.com/grafana/grafana/pull/12620/files#diff-595dd3f3300bbf2eaa7a1b6749d6ffb7R154

**Comment by peterholmberg** [comment]
waiting to see if #15925 resloves this

**Comment by torkelo** [comment]
does not seem like it that PR made a difference
