### ISSUE TITLE
Grafana 6.0 beta-2 - Alerting not supported for Application Insights

### ISSUE THREAD

**Issue by felipecruz91** [grafana/grafana#15484]
### What Grafana version are you using?
Grafana 6.0.0-beta2
### What datasource are you using?
Azure Monitor (Application Insights)
### What OS are you running grafana on?
Running the Docker image `grafana/grafana:6.0.0-beta2` in Linux containers.
### What did you do?
1. Created an API key with permissions to read application telemetry from Application Insights.
2. Add the Azure Monitor data source to Grafana.
3. Created a new rule and clicked on "Test Rule" button.

### What was the expected result?

The alert to be saved successfully without any error message.

### What happened instead?

The following error message appeared: 

![image](https://user-images.githubusercontent.com/15997951/52913708-0aa25b00-32c1-11e9-90ea-69fcd54a401a.png)

![image](https://user-images.githubusercontent.com/15997951/52913760-87cdd000-32c1-11e9-8463-b61b591489f3.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Network request:

Request URL: http://localhost:3001/api/alerts/test
Request Method: POST
Status Code: 200 OK

Network response:

{"firing":true,"state":"pending","conditionEvals":" = true","timeMs":"0.251ms","error":"tsdb.HandleRequest() error Alerting not supported for Application Insights"}

**Comment by torkelo** [comment]
Application insights does support alerting yet. Maybe in a future release

**Comment by felipecruz91** [comment]
I thought release 6.0.0-beta2 (2019-02-11) included AI alerting support because of the following release notes:

New Features

AzureMonitor: Enable alerting by converting Azure Monitor API to Go #14623

Sorry for the misunderstanding.

**Comment by avishnyakov** [comment]
Same here. 

@torkelo, would it be on the roadmap at some point?

**Comment by marefr** [comment]
Please refer to #15153. I don't think it will land in 6.2 since we haven't started working on it. Maybe 6.3?

**Comment by avishnyakov** [comment]
@marefr thanks. It seems there is no ETA or plans in  #15153

In theory, does it make any difference with paid Grafana option?

**Comment by marefr** [comment]
There's no difference with paid Grafana. The referenced issue is on our backlog and in 6.2 milestone so it will happen short term, but cannot give you an exact release/date. Let me get back here when I know more.

**Comment by aimar-worth** [comment]
Can you guys suggest some good workaround for this until the feature will be available?

**Comment by KrothuTheCoder** [comment]
It would be good to know if this is on a road map, we are evaluating monitoring and alerting right now and would help with our planning. Do we go with Grafana knowing some of our services will be logging into Application Insights? Or do we go else where.

Especially as the alerting to Slack otb is a real winner!

**Comment by daniellee** [comment]
@KrothuTheCoder it is on our backlog. It was originally planned for 6.2 but it got pushed back. Aiming for either 6.3 or 6.4 - it is not a huge task but we have some other Azure Monitor related issues that are prioritized higher right now.

**Comment by KrothuTheCoder** [comment]
Thanks its good to know. We are very keen Grafana and would be happy to help test any changes around Azure Monitor

**Comment by PaulSells** [comment]
Hi is there any update on progress with this, is there any timeframe by which we are likely to see  Alerting for supported for Azure Log Analytics?

Thanks

**Comment by Daemon739** [comment]
Is there any update on this issue. This feature will be very helpful in creating custom alerting using Application insights.

**Comment by TylorMayfield** [comment]
Is there an ETA on this? This is a hard stop for us to not use Grafana as a single pane of glass solution for monitoring.

**Comment by aimarjs** [comment]
I have been waiting for this almost a half a year. It's getting harder and harder to justify using Grafana to my customers who are using azure.
