### ISSUE TITLE
Grafana redirect to localhost using Apache Reverse Proxy

### ISSUE THREAD

**Issue by dhyata** [grafana/grafana#15497]
Hi

I have a Grafana instance that sits behind an Apache reverse proxy.
I am accessing my Grafana instance using an FQDN.

When doing a manual refresh using one account accessing dashboards from multiple organisations it does a redirect to localhost:3000.

The grafana log shows that there is no referrer and the apache log shows an error code of 408.

I would like to find out how do I stop this from happening.

Kind Regards
Dhyata Sookmungal

**Comment by bergquist** [comment]
what version of Grafana are you using?

**Comment by torkelo** [comment]
Did you specify root_url in grafana.ini ? It should be the public url you use in your browser (ie the reverse proxy domain name and port)
