### ISSUE TITLE
Embedded panel triggers scroll to element again

### ISSUE THREAD

**Issue by sni** [grafana/grafana#15493]
Seems like the bug from #12075 has been reintroduced. It worked fine with 5.3.0 and somewhere later slipped in again. I can reproduce the error with v5.4.2, but havent tried earlier releases in between.

Please include this information:

### What Grafana version are you using?

 - v5.4.2, but can be reproduced with 5.4.3 as well

### What datasource are you using?

 - influxdb, but should be unrelated.

### What OS are you running grafana on?

 - centos 7 / ubuntu / debian, should be unrelated

### What did you do?

 - embed a panel via iframe at the bottom of a page

### What was the expected result?

 - page should not scroll on load

### What happened instead?

 - page scrolls down to the embedded panel

### How to reproduce

Start grafana, ex.:

```
  %> docker run -d --name=grafana -p 3000:3000 grafana/grafana 
```
Create an example dashboard, a graph with the default example datasource is sufficent.

create a test page somewhere and replace the url with the one from Share -> Embed:
```html
<html>
<body>
<div style="height: 300%; color: orange;">placeholder...</div>
<iframe src="http://hostname:3000/d-solo/id/test?orgId=1&panelId=2" width="450" height="200" frameborder="0"></iframe>
</body>
</html>
```

If you open the page, it scrolls down to the bottom. Tested in Firefox 65 and Chrome 72. You don't even have to be logged into grafana.

**Comment by torkelo** [comment]
Can you try v6.0-beta2 ?

**Comment by sni** [comment]
oh great, it works well with v6.0-beta2

**Comment by torkelo** [comment]
great
