### ISSUE TITLE
Grafana 2.0 Alpha

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1549]
Hi Torkel:

I saw that you're integrating login screen. Is the idea how ever creates the dashboard, owner of the dashboard, no one can edit or delete it other than the owner.

I need to do something like that to ensure the dashboards are protected.

**Comment by torkelo** [comment]
@gsaray101 

Kind of, right now you cannot have permissions on individual dashboards. Dashboards are tied to Organizations, Users can be linked to one or more organizations via a role (Admin, Editor or Viewer). A user who is only a Viewer cannot save/update dashboards  (nor create new ones for themselves). 

Not sure if this solves your case. So there will not be any individual dashboard owner/permissions, but that will likely be added in a future release. That and version-ed dashboards (so you can revert a change)
