### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-5.5.12.tgz: ESOCKETTIMEDOUT".

### ISSUE THREAD

**Issue by ashokreddy2** [grafana/grafana#15501]
Tried couple of times (office network) and getting the same error.

Attached log file.
[yarn-error.log](https://github.com/grafana/grafana/files/2875461/yarn-error.log)

**Comment by torkelo** [comment]
looks like yarn is having an issue right now, will probably resolved soon
