### ISSUE TITLE
grafana mail alert - send multiple mail if result is above 50 

### ISSUE THREAD

**Issue by glardz** [grafana/grafana#15509]
hi,

i set an alert rule and work only one time after that doesn't work, i want to know why and what is the best practice.

![image](https://user-images.githubusercontent.com/20502721/52966117-c4bfc280-33a6-11e9-8eb0-1cfcaa09e544.png)
![image](https://user-images.githubusercontent.com/20502721/52966168-e91b9f00-33a6-11e9-9d48-b77146802b91.png)

**Comment by torkelo** [comment]
You can configure a reminder option in the notification channel settings if you want to keep getting notified even when the alert rule state has not changed.

**Comment by glardz** [comment]
i updated grafana 5.4.2 to grafana 6.0 and now image are not send sing alert rules @torkelo
