### ISSUE TITLE
display point summary when clicked on it in the graph

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15507]
What Grafana version are you using? v5.4.3
What datasource are you using? InfluxDB
What OS are you running grafana on? Windows 10

I want to see the full detail of a point pushed in a table when i click on that particular point on the graph. Is there a way to do it?

**Comment by torkelo** [comment]
full detail? can you describe what that would be? Does your query return more data for the point?

**Comment by debmalyapan53** [comment]
it is showing exactly the field I queried for. But I want to push all the info (fields+tags) associated with that particular point into a table when I click on it. Is it possible?

**Comment by torkelo** [comment]
no it's not possible. Maybe in a future far away :)=
