### ISSUE TITLE
type error in Thresholds

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#15505]
In ThresholdsEditor::renderInput we assign 'Base' to value which is typed as number in Threshold type.

Not sure why this doesn't throw a type error when compiling? 

![screenshot 2019-02-18 at 15 35 12](https://user-images.githubusercontent.com/946275/52957840-fdee3780-3392-11e9-99a5-d1e97705071b.png)

**Comment by torkelo** [comment]
this looks like related to https://github.com/grafana/grafana/issues/15477 and should be fixed in master

**Comment by torkelo** [comment]
yea, input of type number should not be used when trying to show the 'Base' label text .

**Comment by hugohaggmark** [comment]
my bad, introduced this when fixing other bug with not being able to enter decimal values in thresholds
