### ISSUE TITLE
grafana building from source

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15512]
What OS are you running grafana on? Ubuntu 18.04
What did you do?
Got the source code and tried building the backend.

What happened instead?

```
go run build.go setup
Version: 6.0.0-pre3, Linux Version: 6.0.0, Package Iteration: 1550054244pre3
go get -v github.com/golang/dep
go install -v ./pkg/cmd/grafana-server
github.com/grafana/grafana/pkg/setting
# github.com/grafana/grafana/pkg/setting
pkg/setting/setting.go:225:35: undefined: http.SameSite
exit status 2
exit status 1
```
Any reason why?

**Comment by marefr** [comment]
You'll need Go 1.11

**Comment by jstrong-tios** [comment]
@marefr this solved my issue, I had been searching for which golang version to use for a while until I found it. It would be helpful to document preferred or required golang versions in README.md. I would submit pull request, but I'm not confident what the answer is, other than 1.11.
