### ISSUE TITLE
Image rendering timing out after upgrade

### ISSUE THREAD

**Issue by MachEleven** [grafana/grafana#15513]
### What Grafana version are you using?
6.0.0-beta2 (amd64 deb package from dl.grafana.com)

### What datasource are you using?
Influxdb

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
Upgraded an instance to 6.0.0-beta2 from 6.0.0-beta1

### What was the expected result?
Notifications including images to be sent via already setup notification channels(email, slack, telegram) 
Notifications with images works as expected on 6.0.0-beta1.

### What happened instead?
Notifications started to be sent without images.
I checked the logs. 

> t=2019-02-17T17:04:31+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=2 newState=alerting prev state=ok
t=2019-02-17T17:04:31+0000 lvl=info msg=Rendering logger=rendering path="d-solo/ckPK9g9mk/alarmtest1?panelId=2"
t=2019-02-17T17:05:00+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-02-17T17:05:00+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"

Then I tried to create a rendered image using the browser. 
Panel/Share/Direct link rendered image

> https://xxxxxx.com/render/d-solo/ckPK9g9mk/alarmtest1?orgId=2&from=1550498253711&to=1550519853711&refresh=1s&panelId=4&width=1000&height=500&tz=Europe%2FBerlin

This was  also unsuccessful. Returns 504 timeout error.

Switched back to 6.0.0-beta1 with same config. Images are rendered. Notifications includes images.

**Comment by torkelo** [comment]
Strange, if you try to click the panel and share modal, then Direct link to the rendered image, does this timeout as well? 

How long does the graph query take?

**Comment by torkelo** [comment]
Can you try beta3 ?

**Comment by MachEleven** [comment]
At my first upgrade to 6.0.0-beta2 after looking at the logs for troubleshooting and seeing the error, I checked Direct link to the rendered image. Just to be sure, I checked it couple of times with different panels on different dashboards. I tried it on Firefox and Chrome. I tried it after restarting Grafana. All of my try outs resulted with time out. Then I downgraded to 6.0.0-beta1. 
After seeing your reply I re-upgraded to 6.0.0-beta2 to check how long the query takes at the right version. I also gave a second shot at Direct link to the rendered image. Strangely it didn't time out this time. I also tried the notifications with images. However without success. Same error on the logs.

> t=2019-02-19T12:31:51+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=2 newState=alerting prev state=ok
t=2019-02-19T12:31:51+0000 lvl=info msg=Rendering logger=rendering path="d-solo/ckPK9g9mk/alarmtest1?panelId=2"
t=2019-02-19T12:32:08+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-02-19T12:32:08+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-02-19T12:32:08+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xx@xxxxxx.com]

The query takes ~ 82-128 ms according to Chrome Dev Tools.

I upgraded to 6.0.0-beta3 as you suggested. Direct link to the rendered image works; but image render for notifications doesn't seem to work with same error on the logs.

**Comment by MachEleven** [comment]
I downgraded to 6.0.0-beta1.
Notifications with images works.
Log results;

> t=2019-02-19T16:44:16+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=2 newState=alerting prev state=ok
t=2019-02-19T16:44:16+0000 lvl=info msg=Rendering logger=rendering path="d-solo/ckPK9g9mk/alarmtest1?panelId=2"
t=2019-02-19T16:44:17+0000 lvl=info msg="uploaded screenshot of alert to external image store" logger=alerting.notifier url=https://s3.eu-central-1.amazonaws.com/xxxxxx/ErDWT4A8KPDh0GLj9Wfq.png
t=2019-02-19T16:44:17+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xx@xxxxx.com]

**Comment by torkelo** [comment]
Are you using s3 to store images ?

**Comment by MachEleven** [comment]
Yes I use s3.

**Comment by MachEleven** [comment]
Would you like me to provide further info on this? I tried 6.0.0-beta1, beta2 and beta3 and then beta1 on another instance. Same error on beta2 and beta3 and works on beta1. I forgot to mention that grafana is behind nginx reverse proxy. I checked my config ini if anything is misplaced. My setup is quite ordinary except reverse proxy. I also tried local image storage instead of s3. Same results.

**Comment by MachEleven** [comment]
I investigated further. I looked into debug logs. I removed and added the notification channels without changing channel configurations. And after this action notification image render started work. I believe this is an issue related to my own setup. I thought it was a general issue related to a bug. I'm very sorry for taking your time at a very busy time.

**Comment by MachEleven** [comment]
I want to share the possible root cause and how I resolved the issue in my own setup. I believe it might help others having a similar problem.
If the below error is listed in the logs: 
`eror msg="Phantomjs exited with non zero exit code"`
This is most probably caused by running in a container or instance without enough RAM for phantomjs. 
This had been stated couple of times by Grafana Team as reply to similar issues. My trial instances had only 1gb ram. And this was the most probable suspect in this case. So migrating to an instance with better RAM or converting to the [image grafana-image-renderer plugin](https://github.com/grafana/grafana-image-renderer) from phantomjs resolved the problem.
