### ISSUE TITLE
Grafana 2.0 Alpha - FF and IE Input text not working

### ISSUE THREAD

**Issue by syepes** [grafana/grafana#1551]
Hello,

Just to let you know that the input text fields on FF and IE are not working correctly, when typing in any of the fields the text is actually written but its invisible.

![txt](https://cloud.githubusercontent.com/assets/333081/6458239/d48a97d0-c181-11e4-9b85-bae367220484.png)

Tested versions:
Chrome: 40.0.22 (Works)
FireFox: 35.0.1 (Not Working)
IE: 11.0.9 (Not Working)

**Comment by torkelo** [comment]
thanks for reporting this, must have been broken recently (usually test with firefox once in a while)

**Comment by torkelo** [comment]
fixed!
