### ISSUE TITLE
Clicking on panel error doesn't do anything

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#15517]
### What Grafana version are you using?
master
### What did you do?
Tried to load a panel with an offline datasource
### What was the expected result?
Panel error is displayed and I can hover the panel error and get a tooltip and being able to click on the panel error to bring up a modal with details.
### What happened instead?
Panel error is displayed and I can hover the panel error and get a tooltip, but I'm not able to click on the panel error to bring up a modal with details. However, a link cursor is shown when hovering the panel error icon. Tried to use the query inspector instead but that doesn't work (Forever spinner Loading query inspector... )
 
6.0.0-pre
![image](https://user-images.githubusercontent.com/1668778/52979932-28aeaf00-33d8-11e9-8861-f89c1ba9fff0.png)

On 5.4.3 I could click alert panel error and bring up a model and see details similar to this:
![image](https://user-images.githubusercontent.com/1668778/52979985-572c8a00-33d8-11e9-9744-4c6f1c5e68a5.png)

**Comment by torkelo** [comment]
The modal is gone in v6, using query inspector is recommended until we create figure out another way. The modal and query inspector show muck of the same thing and the error modal was such a messy angular hack so removed it infavor of query inspect that wrongs for both angular and react panels.

Not great I know, specially an issue for viewer users.  But don’t want duplicate features as well. But might need it back in some form in the future

**Comment by marefr** [comment]
@torkelo the big problem is that the query inspector don't work with errors. As I wrote above:

> Tried to use the query inspector instead but that doesn't work (Forever spinner Loading query inspector... )

**Comment by torkelo** [comment]
that sounds like a big bug (Query inspector not working for errors)
