### ISSUE TITLE
[Feature request] Multi-tenancy support for Prometheus

### ISSUE THREAD

**Issue by maoyuanh** [grafana/grafana#15519]
We have the request that metrics from the specified tenant in Prometheus shall be accessible by the users belonging to that tenant on Grafana. 
On the side of Grafana, it supports Organization concept which can be used for purpose of tenancy. One Organization will map to one tenancy. 
I think we need following enhancements:
1. •	In Org structure, add two fields (Tenantlabel and Tenantvalue)
2. •	Add proxy handling when invoking api/v1/query and api/v1/queryrange against Prometheus, the matching label '$Tenantlabel=$Tenantvalue' will be added into query parameter. The $Tenantlable and $Tenantvalue are getting from Org table via OrgID.
3. •	Grafana frontend and restapi will be enhanced also.

**Comment by maoyuanh** [comment]
We have done these changes based on grafana 5.2.4, but seems grafana does not accept old release contribution. Could we enhance this in latest grafana code then contribute back?

**Comment by CsatariGergely** [comment]
@maoyuanh you mean implement this to the main branch and port it back to 5.2.4?
@torkelo @marefr is it possible to port back features to 5.2.4?

**Comment by maoyuanh** [comment]
@CsatariGergely 
Yes, we have done this based on 5.2.4. 
If it it not possible to port back to 5.2.4, we will do this based on latest version.

**Comment by marefr** [comment]
We normally don’t backport features and enhancements. New features should always be based on the master branch and target master branch to be merged to. If you then want to backport this and maintain a fork you're free to do that.

**Comment by venkatbvc** [comment]
@marefr  We will make the changes to the latest Grafana branch and post the changes.

**Comment by aocenas** [comment]
Hey @venkatbvc was there any PR targeting this feature request?

**Comment by vhurtevent** [comment]
Hello @venkatbvc, we are also interested by the feature. How could we collaborate ?
Having Organizations and label tenant value in a directory could be a great thing too.
