### ISSUE TITLE
Gauge panel created prior to 93e8edfdddebc1bdf3ecd2d192afc94b2d113b60 will have their Thresholds reversed

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#15522]
Any Gauge panels created before 93e8edfdddebc1bdf3ecd2d192afc94b2d113b60 will look like this
![image](https://user-images.githubusercontent.com/562238/52995798-f626a580-341b-11e9-88d6-537214c5c732.png)

And the Gauge will look reversed as well
![image](https://user-images.githubusercontent.com/562238/52995875-2a01cb00-341c-11e9-884c-caaab3820f8d.png)

**Comment by peterholmberg** [comment]
@torkelo has some fancy migration script I think.

**Comment by hugohaggmark** [comment]
👍
