### ISSUE TITLE
Allow positioning variables at top, between and/or right side of dashboard

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15520]
It would be nice if we are able to reposition the templated filters in the dashboard.

**Comment by marefr** [comment]
You can already do that using up/down arrows in the list of variables: http://docs.grafana.org/reference/templating/#adding-a-variable

**Comment by debmalyapan53** [comment]
I wasnt referring to that. I am asking if some sort of drag-handle could be given so that filters could be placed at the top/ in between/ at right side in the dashboard.
