### ISSUE TITLE
CTA for adding a datasource when going to explore

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#15533]
![2019-02-19-124725_524x130_scrot](https://user-images.githubusercontent.com/114937/53012977-c770f500-3444-11e9-82c5-7749d4e363f8.png)

> As a user I would like to be able to click a link/button to go directly to go to the "Add datasource" view

**Comment by torkelo** [comment]
@davkal any thoughts on this?

**Comment by davkal** [comment]
I'd aim for consistency in button use, and style it similar to panel adding in an empty dashboard.
Otherwise no additional thoughts.
