### ISSUE TITLE
Loki query editor doesn't work as expected

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#15538]
### What Grafana version are you using?
Grafana 6.0.0-beta3 and master (88a46e6)
### What datasource are you using?
Loki
### What did you do?
Had the following query `{job="grafana"}` and then I wanted to add another label filter so auto-complete gave me suggestions for the label `filename`. 

![image](https://user-images.githubusercontent.com/1668778/53027174-b46e1d00-3464-11e9-839c-5328f7c395a2.png)

Instead of selecting one of the suggested values I inserted `~""` and tried to add a `^`-character after the first quote-character.
### What was the expected result?
Being able to filter label using regex writing `=~"^"`
### What happened instead?
The `^`-character was added outside the query, i.e. `{job="grafana", filename=~""}^`. 

Extra: Trying to remove the trailing `^`-character only worked using the delete key and not the backspace. Then moving cursor in between the quotes and tried to write something, all the characters was put outside the query similar to what happened to `^`-character before.

Seems something weird happens when you write a `"`-character somewhere in Loki query editor.

**Comment by hugohaggmark** [comment]
No repro as this was caused by an external Chrome plugin
