### ISSUE TITLE
Document the way ad-hoc filters can be specified in URL parameters

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [grafana/grafana#15535]
Hello

It took me so long to find out that if I want to specify an ad-hoc filter through a URL parameter, I have to write "key|operator|value". I only found it because I finally stumbled upon this issue:

https://github.com/grafana/grafana/issues/8056

It would be great if this could find its place somewhere in the documentation for future searchers not to waste too much time.

**Comment by oddlittlebird** [comment]
Does this address the issue? https://grafana.com/docs/grafana/latest/variables/url-variables/

**Comment by daniellee** [comment]
It does not belong under dashboard search. I found a section that refers to them but only in the very specific context of data links. It feels a bit hidden and is hard to search for as the term `query string parameter` is not in the text: https://grafana.com/docs/grafana/latest/linking/data-link-variables/#template-variables

There must be tons of integrations that dynamically build Grafana urls to link to dashboards. So maybe should be here: https://grafana.com/docs/grafana/latest/dashboards/share-dashboard/ What do you think @oddlittlebird ?

## Query string parameter format

Here is an example of a dashboard url with three variables - datacenter, host and adhoc. 
https://play.grafana.org/d/000000002/influxdb-templated?orgId=1&var-datacenter=America&var-host=All&var-summarize=1m&var-adhoc=datacenter%7C%3D%7CAmerica

The only Grafana-specific part of building the [query string](https://en.wikipedia.org/wiki/Query_string#:~:text=A%20query%20string%20is%20a,part%20of%20an%20HTML%20form.) is the format of the variable name and the value format for ad hoc variables.

The variable name format is: `var-`_variable name_
The variable value format is html encoded. E.g  variable `host` with value `server/7` would be: `var-host=server%2F7`
The ad hoc variable value format is: `key|operator|value` and when html encoded it is: `key%7Coperator%7Cvalue`

**Comment by oddlittlebird** [comment]
I am still not clear on what needs to be done to address this issue.

@achatterjee-grafana , this might be relevant to our discussion on the sharing features.

**Comment by GrafanaWriter** [comment]
This issue hasn't had activity in more than six months. In another week, I will close it.

If you comment or otherwise update it, we'll reset the clock.

**Comment by samjewell** [comment]
I'd also like to see more documentation here.
I was going to simply add my 👍, but realised I should comment to keep this issue open. There have been some staff members change at Grafana, so maybe that's why this was in danger of going stale and getting closed ...
