### ISSUE TITLE
Import with http_api, issues with dashboard-id. 

### ISSUE THREAD

**Issue by defenestration** [grafana/grafana#15540]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.4.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
CentOs7
### What did you do?
Attempted to export and import a dashboard via http_api to a new grafana install of the same version.
### What was the expected result?
Imported dashboard
### What happened instead?
404 
{
    "message": "Dashboard not found",
    "status": "not-found"
}

This took a while for me to narrow down.  I realized I could import the example at http://docs.grafana.org/http_api/dashboard/#create-update-dashboard without this issue so modified my json to be able to import.  

I found that removing the 'id' key in the 'dashboard' section allowed me to import the dashboard. Setting it to 'null' seems to work as well.

Ideally, i'd just like to see the dashboard import.  But sending an error saying that it can't due to the ID would be helpful as well.

**Comment by defenestration** [comment]
I was able to import the same Json via the web interface, though it did forget the 'Name' (which should be 'title' from the json) at the next Import screen.

**Comment by defenestration** [comment]
Json that can reproduce this
```
{
  "dashboard": {
    "id": 1234,
    "uid": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
  },
  "folderId": 0,
  "overwrite": false
}
```

**Comment by torkelo** [comment]
Remove the id property

**Comment by defenestration** [comment]
Can we get an error returned from the API when this issue arises?

**Comment by torkelo** [comment]
That is exactly what you got (404 not found error) because a dashboard with that is was not found

**Comment by defenestration** [comment]
It was unclear that the ID was causing this issue though. And the intent was to create a new dashboard.
