### ISSUE TITLE
value mapping for graph panel

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15549]
What Grafana version are you using? v5.4.3
What datasource are you using? InfluxDB
What OS are you running grafana on? Win10

I understand Grafana doesnt trigger alert for boolean values fetched from InfluxDB. Also, boolean values arent displayed in the graph as well.
It would be nice if there is a value mapping feature for graph panels.

**Comment by ortegafernando** [comment]
@debmalyapan53 Hi, why did you close it? Did you find any solution for value mapping in graph panel? Thanks.
