### ISSUE TITLE
Provide option to set visibility of template variables in kiosk mode

### ISSUE THREAD

**Issue by tktr** [grafana/grafana#15546]
Release `v5.3` introduced a breaking change making template variables invisible in Kiosk mode (#13025).

In our setup, we're exposing dashboards through a third party application. In the past, kiosk mode came in handy for this purpose hiding navbars which are needless in this case. However, with the current releases > 5.3, those exposed dashboards are rendered unusable as users are no longer able to change the variables.
 
Apart from that, as it was already pointed out in #7691, it might be sometimes preferred to have a visual context of the graphs shown in the current view. 

That being said, I can understand that the use cases for kiosk mode are diverse and it's difficult to cover them all. But wouldn't it make sense to have another option allowing to set the visibility of variables?

**Comment by torkelo** [comment]
Hard to have options for every possible scenario and use case. 

Closing this for now but we other can upvote this and we can reopen if there is a large demand for this.

**Comment by deckn** [comment]
This breaking change is indeed quite annoying. For a 24/7 view, you often need the visual context that the variables provide. Wouldn't it be a valid option to add a setting parameter, while creating the variable, if it should be displayed in tv and/or kiosk mode? In my opinion, this could be a very flexible solution, which should cover, in combination of the tv and kiosk mode, most of the possible scenarios. 

The FR #7691, which seems to me to be the initial request for this change, was for a specific scenario, for which a workaround already exists  

>I know that we can set the variable values through the URL but having it in the GUI is more user friendly.

In my opinion this not a valid argument to introduce a breaking change.
An while reading your own comments, I guess you had the same feeling:

> so new breaking change of kiosk mode (to hide submenu (ie variables)), would implement this FR #7691
> I don't like introducing a breaking change, really hard to judge the impact this breaking change will have.

However I also understand that you don't want to reopen the same topic over and over again.

**Comment by Paul-Reed** [comment]
I also would like to see the submenu visible in kiosk node, not only for the template variables, but also for Dashboard Links which 'users' can use to navigate between different dashboards.

Currently for this reason, I am unable to use kiosk node which is a shame as it's a nice feature...

**Comment by mindfuucker** [comment]
For all who are affected by this, I found/made a workaround to keep things functional.

1. Make a dashboard with a variable (eg. foo) using a query
2. Insert a Table Panel with exactly the same query
3. Table Panel Settings -> Visualisation -> Column Styles -> Link -> Url:
`/d/<dashboard_giberisch>/${__cell_0}?var-foo=${__cell_0}&kiosk=tv`
4. [Make sure to insert a variable between the last / and ? ](https://github.com/grafana/grafana/issues/13433)
5. (optional) Create a Text Panel with the variable $foo for feedback about the active variable.

**Comment by nitinguptadr-dori** [comment]
We release dashboards to customers in kiosk mode - but now there is no way to have them select from a pull down menu that we used to expose via variables. Thus the user cannot choose different options which would refresh various charts.

**Comment by krazykow** [comment]
Any update on this?
This seems like the most common use case you just chose to destroy

**Comment by phxnsharp** [comment]
We also would like to embed Grafana inside another app using an iframe. Inside the iframe we would like variables and time controls, but nothing else. No ability to edit, switch dashboards, change view mode, etc. Thank you!

**Comment by breu** [comment]
In my opinion @torkelo https://github.com/grafana/grafana/issues/7691 was the breaking change and removed functionality that existed previously.   It looks like others have the same opinion too

**Comment by torkelo** [comment]
Open for a PR that adds more control over this

**Comment by sbstnpl** [comment]
We're embedding some dashboards/widgets in kiosk mode as iframe into other sites and therefore it would be great to have the option to use editable variables :)

**Comment by xuhrc** [comment]
it's too bad that can not have variables in tv mode, maybe we can make this an option in preferences

---
grafana just hide the template variables in the web page.
I found a solution for this issue
1. find the grafana.dark/light.xxxxxxxxxxxxxxxx.css
2. append `.view-mode--tv .submenu-controls{display: flex}` to the end of the two css files

then you'll get template variables shown in tv mode

**Comment by nuKs** [comment]
> 2\. .view-mode--tv

+1,

also works for kiosk mode:
`.view-mode--kiosk .submenu-controls{display: flex !important}`

**Comment by gbnj2004** [comment]
> it's too bad that can not have variables in tv mode, maybe we can make this an option in preferences
> 
> grafana just hide the template variables in the web page.
> I found a solution for this issue
> 
> 1. find the grafana.dark/light.xxxxxxxxxxxxxxxx.css
> 2. append `.view-mode--tv .submenu-controls{display: flex}` to the end of the two css files
> 
> then you'll get template variables shown in tv mode

thanks a lot, I find a way to resolve this trouble for  a long time, now I can have a good time.

**Comment by gbnj2004** [comment]
> it's too bad that can not have variables in tv mode, maybe we can make this an option in preferences
> 
> grafana just hide the template variables in the web page.
> I found a solution for this issue
> 
> 1. find the grafana.dark/light.xxxxxxxxxxxxxxxx.css
> 2. append `.view-mode--tv .submenu-controls{display: flex}` to the end of the two css files
> 
> then you'll get template variables shown in tv mode

希望国内的小伙伴能看到这个解决方案，这个以及楼下的回复都是解决如何在grafana的kiosk模式下自定义隐藏或显示global variable、其他组件的方法。希望百度能爬到这条信息方便国内小伙伴解决烦恼。

**Comment by gbnj2004** [comment]
share my kiosk config which append to the end of the two css files  as what xuhrc said above：
.view-mode--kiosk .submenu-controls,.view-mode--kiosk .navbar{display:flex !important}
.view-mode--kiosk .navbar-buttons--tv,.view-mode--kiosk .sidemenu,.view-mode--kiosk .navbar-page-btn{display:none !important}
.view-mode--kiosk .navbar:before {content:"陕重汽-信息技术部Zabbix监控";font-size:3vw;margin:auto;}

**Comment by bob454522** [comment]
> I found a solution for this issue
> 
> 1. find the grafana.dark/light.xxxxxxxxxxxxxxxx.css
> 2. append `.view-mode--tv .submenu-controls{display: flex}` to the end of the two css files

This is a great mod,  thanks for posting!  i am making use of this, but for showing VARs dropdown while in KIOSK mode.
**It should be noted that making this change could (will?) very likely be overwritten by a future update**,  so it may disappear (and have to be re-modified by end user,  post grafana update)

> also works for kiosk mode:
> .view-mode--kiosk .submenu-controls{display: flex !important}

**(would be GREAT to have this feature built into grafana, for the update issue referenced above).**
thanks,
LOVE GRAFANA!

**Comment by meyerder** [comment]
I am having a really hard time getting this to work....   What version(s) is this working on?  And or if anyone could post the file I would replace with the proper filename on my end...

**Comment by DasDepp** [comment]
Hi all,
thanks for all the information. 

also works for kiosk mode:
.view-mode--kiosk .submenu-controls{display: flex !important}

But I also want to show the time range settings in the kisok mode. Would be great if somebody know what I have to change in the .css file.

Thanks!

**Comment by DonatoD** [comment]
With Grafana 8.0.3 this solution of adding the code at the and of the dark/light css doesn't seem to work anymore. Please Grafana team, add this feature. In the meantime what could be the workaround?
Thanks

**Comment by jflatby** [comment]
Would also like this. 
Same use case, embedded grafana dashboard in iframe, in which users should not be able to navigate around grafana, but they should be able to change the template variables on the dashboard they are viewing.

Turning off kiosk mode is not a solution because it suddenly looks like you are viewing the entirety of grafana and not one dashboard

The suggested workaround here is not an option for me either, since we run the grafana docker image and can't change the source code.

**Comment by DonatoD** [comment]
Could you please post an example on what you're getting? at the end  what I need is to eliminate the left bar bust still having dashboard links and variables dropdown

**Comment by jflatby** [comment]
That is basically what I need as well.

I don't have the code/app here, but I don't really have anything to show anyway. I just have a normal non-kiosk grafana dashboard with a sidebar and variables, embedded in an <iframe> with a dashboard url.

One sort of(but not really) workaround is to set "marginLeft: -60px" on the iframe containing the dashboard, and turning off kiosk mode.

That way the left sidebar will be hidden off screen, and it looks very similar to kiosk mode, just with template variables.

But this is not a viable workaround either, since when opening the page on mobile, the sidebar will not be there. There will be a button to open the menu at the top instead. So then the "-60px" will be way off and it looks wrong on mobile/other smaller screens.

**Comment by mayouzi** [comment]
> With Grafana 8.0.3 this solution of adding the code at the and of the dark/light css doesn't seem to work anymore. Please Grafana team, add this feature. In the meantime what could be the workaround?
> Thanks

+1

**Comment by stanxing** [comment]
> With Grafana 8.0.3 this solution of adding the code at the and of the dark/light css doesn't seem to work anymore. Please Grafana team, add this feature. In the meantime what could be the workaround?

Same problem.

**Comment by msit11125** [comment]
> With Grafana 8.0.3 this solution of adding the code at the and of the dark/light css doesn't seem to work anymore. Please Grafana team, add this feature. In the meantime what could be the workaround?

Really want global variable dropdown exist in kiosk mode.

**Comment by msit11125** [comment]
> With Grafana 8.0.3 this solution of adding the code at the and of the dark/light css doesn't seem to work anymore. Please Grafana team, add this feature. In the meantime what could be the workaround?

issue solved using kiosk=full

**Comment by DonatoD** [comment]
no, you don't solve the problem. WE already know that is possible add this on the url. This is the problem, you can just cancel it and be back.
We need a way to set a kiosk mode without possibility to go out by the viewer

**Comment by PPACI** [comment]
We would like to see this implemented as well.

We're using grafana in Microsoft Teams tab.
The kiosk mode is perfect. But right now, we have to create one tab for each combination of parameters (set through the URL).

Ideally, an additional kiosk mode like `tv-template` would be perfect.

**Comment by meyerder** [comment]
Add me to this as well...

**Comment by cugykw** [comment]
I found a solution for this issue.(It's not elegant, but it solves our scenario)
`            <div className={styles.dashboardContent}>
              {initError && <DashboardFailed />}
              {showSubMenu && (
                <section aria-label={selectors.pages.Dashboard.SubMenu.submenu}>
                  <SubMenu dashboard={dashboard} annotations={dashboard.annotations.list} links={dashboard.links} />
                </section>
              )}

              <DashboardGrid dashboard={dashboard} viewPanel={viewPanel} editPanel={editPanel} />
            </div>
`
change into
`            <div className={styles.dashboardContent}>
              {initError && <DashboardFailed />}
              {true && (
                <section aria-label={selectors.pages.Dashboard.SubMenu.submenu}>
                  <SubMenu dashboard={dashboard} annotations={dashboard.annotations.list} links={dashboard.links} />
                </section>
              )}

              <DashboardGrid dashboard={dashboard} viewPanel={viewPanel} editPanel={editPanel} />
            </div>
`

**Comment by meyerder** [comment]
Any Chance you could mention which file this is done on?  or where to do
this edit?

**Comment by cugykw** [comment]
@meyerder sorry i didn't notice. i have modified

**Comment by Igorgro** [comment]
`kiosk=full` stopped working after updating to 8.5.0

**Comment by Sulomus** [comment]
+1

Could you please implement this? It is a simple thing yet so many people would love this!

**Comment by bob454522** [comment]
+1 i too am still looking for this feature:
Namely - i have some like to share a kiosk URL + give the anonymous visitor Variable drop-down menu access (but NO sidebar).

Im aware this is not secure, and the user can still get to the sidebar links,  however our grafana sites are internal access only and users access via a VPN.  

(we need this feature to make the UI the "most simple",  ie: we have users get confused by the sidebar.  However kiosk mode + variables drop-down only,  is such a clean, simple UI).
@torkelo :
Also now that we can alter the Interval via a variable (ie a dropdown ) , this allows even the time-picker to be removed (as it is in kiosk mode) - thus all that is needed is kiosk mode + variable dropdown menus (and ALOT of easy, clean functionality is provided).

thanks,
LOVE GRAFANA!

**Comment by gbnj2004** [comment]
When the grafana updated，the css file  also  has  been changed( In the most cases， only  the web elements of the  class  name which have been changed  have  an  effect  on  the  kiosk mode )，so we must find the new  class name  and  write  them  append  to  the  css files. Share my kiosk config which append to the end of the two css files  with  grafana  v7.5.16:
.view-mode--kiosk .sidemenu,.view-mode--kiosk .css-1bpq4j8,.view-mode--kiosk .css-1cgkl47 .toolbar-button{display:none !important}.view-mode--kiosk .page-toolbar,.view-mode--kiosk .css-1cgkl47 .button-group .toolbar-button,.view-mode--kiosk .submenu-controls{display:flex !important}.view-mode--kiosk .page-toolbar:before {content:"信息技术部-Prometheus监控";font-size:2vw;margin:auto;}

here  is  the   result：
![image](https://user-images.githubusercontent.com/10908748/179892289-5a49e575-bc44-4370-a362-84f9e2354c63.png)

below is the version compare：
![image](https://user-images.githubusercontent.com/10908748/179893186-e4b83e6a-802e-4d2f-a102-f3ad159774a3.png)
![image](https://user-images.githubusercontent.com/10908748/179893482-6b2efc18-8413-4c4b-b2b5-d26561f6bee8.png)

hope  that  helps.

**Comment by svet-b** [comment]
@bob454522 I believe the source code change suggested by @cugykw in https://github.com/grafana/grafana/issues/15546#issuecomment-1103886212 does still work for v9 (tried on v9.0.4 specifically).

**Comment by DonatoD** [comment]
So, could someone please summarize the correct change to do in grafana 9? I need thise two option:
1) kiosk mode that shows only variable, without time filter
2) kiosk mode that shows both, variable and time filter
Thanks

**Comment by vinnyo** [comment]
@svet-b How did you get it to work on v9.0.4? I tried modifying the file as per the comment and restarted grafana-server service but it didn't work. Did you had to do an extra step? (i.e. running some script/build?)

**Comment by svet-b** [comment]
@vinnyo yes you need to build from source. It mostly comes down to running the `RUN` lines in the [Dockerfile](https://github.com/grafana/grafana/blob/main/Dockerfile)

**Comment by vinnyo** [comment]
Ah, Thanks for your input @svet-b

**Comment by Abuu001** [comment]
+1

**Comment by iamyeka** [comment]
> We also would like to embed Grafana inside another app using an iframe. Inside the iframe we would like variables and time controls, but nothing else. No ability to edit, switch dashboards, change view mode, etc. Thank you!

+1

**Comment by 11phc** [comment]
+1

**Comment by UttamAaseri** [comment]
+1

**Comment by erlendsommer** [comment]
+1

**Comment by moonkop** [comment]
+1

**Comment by coste082** [comment]
+1

**Comment by rohit-innodeed** [comment]
+1

**Comment by nouman-zeb-snkeos** [comment]
+1

**Comment by kertpjatkin** [comment]
+1

**Comment by 11phc** [comment]
ok so the good news is that I think I have bodged this successfully (in my case for grafana 9.3.2), along the lines of @cugykw 's changing "showSubMenu" to "true".  You have to edit this file (on my Ubuntu):  /usr/share/grafana/public/build/DashboardPage.6caad1b9debc78679fb9.js

**Comment by 11phc** [comment]
ok so the good news is that I think I have bodged this successfully (in my case for grafana 9.3.2), along the lines of @cugykw 's changing "showSubMenu" to "true". You have to edit this file (on my Ubuntu): /usr/share/grafana/public/build/DashboardPage.6caad1b9debc78679fb9.js  and search for the string "m&&(" in the render() function and change it to "true&&("

**Comment by saif-ahmed786** [comment]
for grafana docker container, I have followed @xuhrc and @11phc instructions and finally, i can see the template variable in my grafana v8.5, thank you

**Comment by Project-Exhale** [comment]
The trick from @11phc doesnt work for me.

When i de-minify the line states 
"const showSubMenu = !editPanel && !kioskMode && !this.props.queryParams.editview;"

this results in
g=!s&&!p&&!this.props.queryParams.editview,

Changing it to g=true had no effect.

**Comment by JiiAndddy** [comment]
Hello, Is there a solution for this problem in version 9.3.0?

**Comment by dc-orz** [comment]
https://github.com/grafana/grafana/issues/20176#issuecomment-1814286375

**Comment by NWYLZW** [comment]
> Hello, Is there a solution for this problem in version 9.3.0?

You can try cherry pick [these commits](https://github.com/NWYLZW/grafana/commits/feature/control-nav).

<img width="673" alt="image" src="https://github.com/grafana/grafana/assets/51358815/cd778dcb-9036-4eac-94d0-82ed02dfd044">

**Comment by 11phc** [comment]
> ok so the good news is that I think I have bodged this successfully (in my case for grafana 9.3.2), along the lines of @cugykw 's changing "showSubMenu" to "true".
> 
> You have to edit this file (on my Ubuntu): /usr/share/grafana/public/build/DashboardPage.6caad1b9debc78679fb9.js and search for the string "m&&(" in the render() function and change it to "true&&("
> 
> Basically the first character “m” is the minified variable “showSubMenu” as per the source file DashboardPage.tsx in the GitHub source, which needs setting permanently to true.
> 
> If you can’t find this string in your version of grafana try using https://sokra.github.io/source-map-visualization/#custom to un-minify the /usr/share/grafana/public/build/DashboardPage.6caad1b9debc78679fb9.js and DashboardPage.6caad1b9debc78679fb9.js.map files and search for showSubMenu in there to see where it is in the minified version. (N.B. this will obviously not persist after grafana upgrade)



--UPDATE for 10.2.3 ---

You now need to edit the file on your grafana webserver :
 /usr/share/grafana/public/build/DashboardPageProxy.09c251be22926bffde87.js

and search for 
!r&&**!u**&&!this.props.queryParams.editview,

and change the **!u** minified variable to **true**
(replaces !kioskMode ... u = kioskMode minified)

thus giving:
!r&&**true**&&!this.props.queryParams.editview,

and save and reload etc.

**Comment by alecks68** [comment]
I am on 10.2.3 and it does not work for me. My file is named DashboardPageProxy.1aade9b945f5e0bb6ff0.js.
I exchanged !u with true and rebootet.
If I click on Kiosk mode everything is gone. In the navigation bar I see '&kiosk' being appended. If I now press the back key in the browser only! the variables and links appear again and I see what I would like to have in the first place and I can even navigate without loosing this. However, if the page is refreshed, I am back to normal mode.
Is there anything else to do as you write "save and reload etc."

**Comment by alecks68** [comment]
Update: The solution of 11phc works now on my 10.23, thanks for this patch!! The problem was with the browser, after complete reset of the cache it worked. For chrome you press F12 to enter DevTools mode, then right click on the refresh icon (left to the navigation bar) and choose the 3rd option to empty and refresh the cache.

**Comment by cyqx13** [comment]
I'm now on latest version 11.1.4
Still no chance to have links visable in kiosk mode and above mentioned workaround does not work anymore.
Is there a new workaround or will it be implemented to have links in kiosk mode in new version?

**Comment by laurantines** [comment]
I'm now in 11.2.0 version, we need display variable filters in kiosk mode. I don't understand why viewer role can see alerts, share, lateral menu... We only want to see dashboard and filters, nothing else. Please, consider adding this, thanks.

**Comment by ederparaiso** [comment]
Same need here... all this years...

**Comment by carlocea9** [comment]
Still surprised this issue is not "reopened" yet.

**Comment by B1F030** [comment]
We really need `kiosk=full`:cry:, hope this can be back in future release.
