### ISSUE TITLE
[Feature Request] Math operations on single stat output 

### ISSUE THREAD

**Issue by KaranTrivedi** [grafana/grafana#15544]
Please include this information:
I am running grafana V5.4 on RHEL 7 with elasticsearch as the data source.
I have created some single stat widgets with doc count/unique count etc. values and need to do a percentage between them. 

E.g. unique count of closed alerts and unique count of total alerts. etc. 

And I would like to show (unique count of total alerts)/(unique count of total alerts) in a new single stat panel. Is there a way of doing this? Can the outputs of queries be loaded into vars for math?

**Comment by torkelo** [comment]
Math operations should be handled in the query

**Comment by torkelo** [comment]
Sorry for closing after short comment, we hope to solve this for data sources that do not support math operations

**Comment by KaranTrivedi** [comment]
Thanks for the update, there is simply no way of doing this at the moment for me!

**Comment by KaranTrivedi** [comment]
Is it possible to track the updates on a timeline ? Do you guys know when this maybe implemented?

**Comment by torkelo** [comment]
Search for an open issue named meta queries, it’s been open for about 3 years, hopefully it won’t be 3 more years until we implement it :)
