### ISSUE TITLE
UI: Navigation and Subnavigation

### ISSUE THREAD

**Issue by bulletfactory** [grafana/grafana#1554]
### Main Navbar
I've designed some incremental enhancements that may add to the usablility of the navigation schema.

![grafana_dashboardnavbar](https://cloud.githubusercontent.com/assets/1950595/6472836/1ccb88d8-c1c3-11e4-9cf2-2c638afd9cb5.png)

##### Logo
* The collapsable side-menu adds a lot of clarity and organization to Grafana 2.0. The circular icon in the top-left works well as the menu trigger to open/close the sidebar, but when open, we should take advantage of this blank space. I've added the Grafana word-mark to make it feel more branded.

##### Dashboard Dropdown
* The dashboard dropdown button works well for selecting your saved dashboards. I kept clicking on the dashboard name, but it wouldn't open the list. Increasing the hit area, by containing the dashboard name in the button feels like it would make this behavior more clear.

##### Zoom
* Currently a text link "Zoom Out" incrementally increases the graph timeline. I designed some simple icons which have the same style as the clock icon to the right. I also added a zoom in icon, thinking being able to incrementally decrease the graph timeframe may also provide value.

### Annotations
![grafana_annotation_toggles](https://cloud.githubusercontent.com/assets/1950595/6472915/b3d2129c-c1c3-11e4-83f8-0fa6303aecb1.png)
The annotation toggles in v1.9 feel more like buttons, however in an effort to reduce the number of containers (boxes) in v2.0, the button feel has been removed. The addition of checkboxes serve as an immediate context clue that they can be toggled on/off. This does, however increase horizontal space - depending on number of annotations and templates added. totally open for discussion. May be a non-issue.

In an effort to make the annotations feel more connected to the graph, and not a subnav of the top navbar, I've doubled the amount of padding-top, and reduced the padding-bottom by half as well (I've aligned the annotations with the baseline of the first item in the sidebar).

##### Annotations Overview/Edit
![grafana_annotations_order](https://cloud.githubusercontent.com/assets/1950595/6473499/bb8b41f8-c1c7-11e4-8375-8930e28b07d3.png)
When viewing/adding/editing annotations, the settings functionality appeared between the graph and the annotations. It felt more natural to try and place them just below the main navbar, above both the annotations and graph. This keeps the annotations married to the graph and doesn't split them up.

##### Ordering
![grafana_annotations_add_edit](https://cloud.githubusercontent.com/assets/1950595/6473225/183f9fc2-c1c6-11e4-8ed9-b12df2640d32.png)
The up/down arrows that allow you to reorder the annotations (and other elements throughout) is great functionality, but thought the were a bit confusing at first. I am suggesting grippers allowing you to grab the area and drag a row into a new position. Would be really valuable w/ a larger number of rows.

##### Close Panel Button
The close icon felt a bit small, so I enclosed it in a button w/ a label to give it more weight but not feel like a primary CTA (shown below)

#### Putting it all Together
![grafana_annotations_open](https://cloud.githubusercontent.com/assets/1950595/6473651/bac63362-c1c8-11e4-9b7c-71b44d506f41.png)

## Settings
Settings follows the same general conventions set forth for the annotations submenu.
![grafana_settings_open](https://cloud.githubusercontent.com/assets/1950595/6473710/25a3bcb8-c1c9-11e4-8570-e49fff4d9853.png)
Instead of making the Hide Controls, Shared Crosshair and Editable checkboxes stretch horizontally, I stacked them vertically. This allows for more visual organization and easier scanability

## Share
Following the same conventions as above, I stacked multiple checkboxes for organization. We're reusing typography size, and style from the in-page settings to maintain hierarchy. I simplified the modal significantly to all be the same color and removed some lines.
![grafana_share_modal](https://cloud.githubusercontent.com/assets/1950595/6473816/da0818de-c1c9-11e4-919e-566cbd04b599.png)
I added a "copy to clipboard" button to the right of the link, and a more descriptive direct link below. I've increased the padding to make it feel lighter and more airy.

**Comment by torkelo** [comment]
awesome! Great work!

**Comment by bulletfactory** [comment]
### Confirmation Modal
I wanted to take a look at the hierarchy in confirmation actions. Currently, all of the buttons have the same weight, so I wanted to make the preferred CTA more prominent to avoid a possibly catastrophic mistake. This mockup also established a general look and feel that could be more widely used for modals:
* icon centered at top
* headline
* supporting text
* CTA

![grafana_confirm_modal](https://cloud.githubusercontent.com/assets/1950595/6508462/f3c01fca-c326-11e4-8b43-7726670b1e3a.png)

Any feedback is greatly appreciated!
