### ISSUE TITLE
How to manual trigger metricFindQuery function in developing datasource plugins

### ISSUE THREAD

**Issue by ZengTianShengZ** [grafana/grafana#15547]
How to manual trigger metricFindQuery function in developing datasource plugins.

`host` variable should change by `message` variable, but I can't manually trigger `metricFindQuery` function anyway。
`metricFindQuery` function will trigger in application initiation. How to manual trigger `metricFindQuery` function update `host` variable

![image](https://user-images.githubusercontent.com/15622519/53083270-89a1c880-3539-11e9-8802-ea488b0754b4.png)

grafana version 5.3

**Comment by torkelo** [comment]
If you use $message in your host query variable it will update after updating message variable
