### ISSUE TITLE
CloudWatch DataSource Alias is ignored

### ISSUE THREAD

**Issue by tarekbecker** [grafana/grafana#15562]
### What Grafana version are you using?
5.4.3
### What datasource are you using?
CloudWatch
### What OS are you running grafana on?
Linux
### What did you do?
I added a CloudWatch query with an expression
### What was the expected result?
The alias should be used
### What happened instead?
The alias is ignored

The CloudWatch datasource ignores the alias. If an alias is defined, the `formatAlias` method is skipped.

https://github.com/grafana/grafana/blob/653918056c594d7f56a65771b2c9681bdf8a3b9a/pkg/tsdb/cloudwatch/cloudwatch.go#L520-L523

Is this behavior intended? If yes, the alias input field should be removed. If no, I would propose removing this check and using the `queryId` only as a fallback.

I can create a PR but wanted to check whether this is a bug or not.
 
Thanks!
Tarek

**Comment by xlson** [comment]
This seems like a bug to me, but I don't know the code well enough to be sure. It could be that the alias functionality doesn't work well with the expressions.

The alias field will still work for other types of queries that don't use expressions so we can't just remove it.

@mtanda do you know if this is a bug?
