### ISSUE TITLE
Variable dropdown does not update current value after parent variable trigger change

### ISSUE THREAD

**Issue by ramivis** [grafana/grafana#15566]
**What Grafana version are you using?**
v6.0.0-beta2 (6a71b19)

After upgrade to version 6 the template variables not refresh automatically when another dependent variable was changed.

Eg. variable1 with list of groups and variable2 with list of hosts based on selected item on variable1, but when new row was selected in variable1 the value in variable2 not refresh more, I need click on variable2 to refresh the values . In oldest version its OK
 
obs: in template the refresh method is "on dashboard load" same that last version that works

Tks.

**Comment by torkelo** [comment]
Strange, unable to replicate this. Can you open chrome dev tools network tab and change a variable? Do you see any network requests that correspond to your your other template variable?

**Comment by ramivis** [comment]
Strange, unable to replicate this. Can you open chrome dev tools network tab and change a variable? Do you see any network requests that correspond to your your other template variable?

Yes, when I change the new values are loaded under the variable but the last value (old) is displayed with selected (not refreshed with the new values). When I click on variable the new values are displayed.

Obs: even if the values of the variable are not updated on the screen, the graphs update based on the values already loaded by hidden

![image](https://user-images.githubusercontent.com/47853421/53169168-4720d000-35bb-11e9-9f63-abff0728dbb1.png)

**Comment by torkelo** [comment]
thanks for reporting this and providing the detail, have fix incoming!
