### ISSUE TITLE
Variable under user account?

### ISSUE THREAD

**Issue by ramivis** [grafana/grafana#15568]
What Grafana version are you using?
6.0beta2

I have a lot of dashboards, each dashboard work with variables but not everyone can see all values returned in variables so i have a LIKE clause in variable. For each person i need duplicate the dashboard, change the variable with LIKE clause with what person can see and change the permission for the person not change the variable LIKE value.

Its is possible define a variable under the user account that just a administrator user can change and the variable can be used in template variable in clause LIKE? so I dont need to duplicate the dashboard every time and to change manualy the query in variable. Just fix a variable value under the user account and the template dynamicaly use it in LIKE clause.

If in this moment not it possibly, maybe in future? Its possible to add in grafana roadmap? Its a very usefull feature.

thank you

**Comment by torkelo** [comment]
No this is not possible, we have an open feature request for variables that can be used/shared
https://github.com/grafana/grafana/issues/1959
