### ISSUE TITLE
"explore" feature: change target refid to letters like in dashboards

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#15573]
### What Grafana version are you using?
6.0.0-beta3

### What datasource are you using?
custom datasource as described [here](http://docs.grafana.org/plugins/developing/datasources/#query)

### What did you do?
Right now I'm using the latest stable 5.4.3 build with a custom datasource. The datasource identifies the queries by their _targets refid's_ as described [here](http://docs.grafana.org/plugins/developing/datasources/#query):
```
{
  "range": { "from": "2015-12-22T03:06:13.851Z", "to": "2015-12-22T06:48:24.137Z" },
  "interval": "5s",
  "targets": [
    { "refId": "B", "target": "upper_75" },
    { "refId": "A", "target": "upper_90" }
  ],
  "format": "json",
  "maxDataPoints": 2495 //decided by the panel
}
```
While trying the new 6.0.0-beta3 I noticed that all dashboards still work, but the new "explore" feature doesn't. This is being caused by the different query behaviour: instead of using **letters** (A and B in the above example), the _target refid's_ are now incremented **numbers**:
```
...
    { "refId": 1, "target": "upper_75" },
    { "refId": 2, "target": "upper_90" }
...
```
Our custom datasource makes use of the _target refid's_ and **does not accept numbers** here.

### What was the expected result?
I expect the refid's to be named the same way, regardless of the use case ("explore" or dashboards/panels).

### What happened instead?
The refid's are numbers in the "explore" feature and letters in dashboards/panels.

**Comment by torkelo** [comment]
yes, refId should not be assigned a number. This is a bug
