### ISSUE TITLE
Inherith GraphCtrl 404 not found

### ISSUE THREAD

**Issue by matbord** [grafana/grafana#15577]
##### What happened instead? It works all fine at compile time but when I run it in the localhost browser it gives me a 404 error

I would like to know how to inherith GraphCtrl from Grafana source code.  I saw a lot of samples extending MetricsPanelCtrl and PanelCtrl but never a GraphCtrl.  I tried to extends my home class with this code: 

      import {GraphCtrl} from "grafana/app/plugins/panel/graph/module";

       class BayesianGraphCtrl extends GraphCtrl{
          /** @ngInject*/
          constructor($scope, $injector, annotationsSrv) {
              super($scope, $injector, annotationsSrv);
          }
      }    

It works all fine at compile time but when I run it in the localhost browser it gives me a 404 error not found, like this:

    Plugin component error Error: "Fetch error: 404 Not Found
    Instantiating http://localhost:3000/public/app/features/dashboard/dashboard_import_ctrl
    Loading http://localhost:3000/public/plugins/dreamcorp-app/module.js
    Loading plugins/dreamcorp-app/module"

    rt system.js:4 

    Unhandled promise rejection Error: "Fetch error: 404 Not Found
    Instantiating http://localhost:3000/public/plugins/dreamcorp-app/panel/module.js
    Loading plugins/dreamcorp-app/panel/module"

    rt system.js:4 

Why can't I import any other classes there are not in Grafana sdk?

**Comment by torkelo** [comment]
This is not possible, in our new react panel architecture and plugin support you will be able to reuse our core visualizations
