### ISSUE TITLE
Use sum to generate no alarm

### ISSUE THREAD

**Issue by xiaoqge** [grafana/grafana#15578]
### What Grafana version are you using?
Grafana v5.4.3 
### What datasource are you using?
promethues
### What OS are you running grafana on?
ubuntu
### What did you do?
Add an alarm
### What was the expected result?
Generate an alarm
### What happened instead?
No alarm occurred
### If related to metric query / data viz:
sum({coin="test",direction="All"})

I hope to get some help, I spent a few days, thank you very much.
I added an alert but did not generate an alert as expected. I used prometheus to query the rule `sum({coin="test",direction="All"})`

![image](https://user-images.githubusercontent.com/8544686/53180676-0d8aac00-3631-11e9-90b5-d267df1b1995.png)

My log：
`lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=2.964 alertId=2 name="test alert" firing=false attemptID=1`

I have been searching for a long time, I don't understand why I can't get an alarm, and my test mail can be sent normally.

**Comment by xlson** [comment]
From the screenshot you posted it looks like you have set the alarm to go off when it's below the red level and from what I can tell your metrics values are now above that level. What happens when you raise the alarm level?

**Comment by xiaoqge** [comment]
The problem is closed, use sum_over_time instead of sum to solve the problem because my data is crawled once in 20 minutes.
