### ISSUE TITLE
Browser datasource 401 Unauthorized should allow redirect to login page

### ISSUE THREAD

**Issue by runejuhl** [grafana/grafana#15575]
I'm currently playing around with datasources using browser access. I've got a setup where a user can authenticate on a site which sets a session cookie and the datasource backend uses this session cookie to authenticate requests. That all works fine.

The issue is that after you log out of the site (thus killing the session/deleting the cookie), or the session expires due to inactivity, all requests to the datasource backend result in 401s which the user doesn't see.

It would be nice if it was possible for datasources using browser access to redirect to an arbitrary URL if it receives a 401 response to a query request. That would give me a way to redirect my users to a login site while still making use of the same session cookie across services.

I tried poking around at the source to see how hard it'd be to implement this feature but didn't get very far. If I can get a pointer for I can find the code responsible for handling the metrics response I'd be glad to look a bit closer myself.

### What Grafana version are you using?
Grafana v5.4.2 (d812109)

### What datasource are you using?
InfluxDB using browser access

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
