### ISSUE TITLE
Remove date from X-Axis

### ISSUE THREAD

**Issue by dry4ng** [grafana/grafana#1558]
When I set graph span to 4, it shows dates next to time labels. If the span is above 4 there is no dates. Is there a way to remove date labels? The dates makes it a little less readable.
In this example the graph data shows last 6 hours, which doesn't include previous day. But the dates are still added:
![001](https://cloud.githubusercontent.com/assets/7841788/6482583/04ee4ad6-c270-11e4-9ce6-587176115653.PNG)

**Comment by torkelo** [comment]
Strange, will investigate, thanks for reporting this!
