### ISSUE TITLE
Explore: Not cleaning logs when change of duplicate method

### ISSUE THREAD

**Issue by lfdominguez** [grafana/grafana#15588]
### What Grafana version are you using?
Grafana v6.0.0-pre3 (commit: cdac119)

### What datasource are you using?
Loki

### What OS are you running grafana on?
Docker image (:master)

### What did you do?
On `Dedup` option (in `None`) select another of the Options, ex. `Signature`

### What was the expected result?
That all logs is cleaned and grouped by signature.

### What happened instead?
All logs is grouped by signature, but no cleaned the old ones.

![deepin-screen-recorder_select area_20190221132028](https://user-images.githubusercontent.com/5604131/53192388-56fcdc00-35dc-11e9-8c1b-5694d837b63d.gif)

The problem is from `None` to another one.

**Comment by dprokop** [comment]
@lfdominguez thank you for you report, we are investigating this problem ATM!

**Comment by dprokop** [comment]
@lfdominguez Can you please provide us with the log's JSON that is used in the recorded example? You can do it by extracting the `data` prop from `Logs` component using React dev tools or sending us backend's response to the query.

**Comment by lfdominguez** [comment]
Sorry (i'm full with work gg) and thanks for fixing....
