### ISSUE TITLE
Grafana multiple instances of panel classes

### ISSUE THREAD

**Issue by davide97g** [grafana/grafana#15587]
I'm currently facing an issue regarding multiple instances, inside the same dashboard, of some costum classes inheriting from MetricsPanelCtrl.
The folder situation is this:
```
plugin-id/src/
	- appCtrl.js
	- panels/
		- mypanel1/
			- myPanel1.js
			- plugin.json 
		- mypanel2/
			- myPanel2.js
			- plugin.json

```
These are the files and their structure

```
//***** AppCtrl.js file

class AppCtrl{
	constructor(){
		console.info("AppCtrl");
		this.unique = 0;
	}
	test(){
		this.unique++;
		console.info("calling"+this.unique);
	}
}

export {AppCtrl};

```

```
//***** MyPanel1.js file

import {MetricsPanelCtrl} from 'grafana/app/plugins/sdk'; 
import {AppCtrl} from '../../appCtrl';
class MyPanel1 extends MetricsPanelCtrl{
	/**@ngInject*/
	constructor($scope, $injector){
		super($scope, $injector);
		console.info("MyPanel1");
		appCtrl.test();
	}
}

```
```
//***** MyPanel2.js file

import {MetricsPanelCtrl} from 'grafana/app/plugins/sdk';
import {AppCtrl} from '../appCtrl';
class MyPanel2 extends MetricsPanelCtrl{
	/**@ngInject*/
	constructor($scope, $injector){
		super($scope, $injector);
		console.info("MyPanel2");
		appCtrl.test();
	}
}

```
```
//TEST in browser when creating MyPanel1 and then MyPanel2 inside the same dashboard

	AppCtrl
	MyPanel1
	1
	AppCtrl
	MyPanel2
	1

```
```
// EXPECTED OUTPUT

	AppCtrl
	MyPanel1
	1
	MyPanel2
	2

```

I would like to have a "controller" class that can send and receive messages from other panel classes.
This controller class (AppCtrl) is just a logical class, not a panel. 

I wish I could share just one instance of this class (AppCtrl) between different istances of the other panel classes (MyPanel1 & MyPanel2 in this example).
The aim is to have a central control in order to comunicate data.

The problem is, when I try to import this AppCtrl class inside other panel classes, they always create a new instance the first time: the comunication is impossibile now, because the two instances are not linked.

The thing I don't understand is that multiple instance of the same class only instanciate one AppCtrl per type (same class, one instance).
Instead, every different class, when you import the AppCtrl class, instanciate its own.

How can I make this AppCtrl class unique so that I can share/send messages between those panel classes?
Maybe my solution to this comunication problem between classes it's not the right one and there's another more elegant solution.
How Grafana comunicate between panel, dashboard and other part of the application? 
I saw in the code that it use "eventemitter3" to send signal and listen to them, but how about implementing one unique instance that is able to listen to signal e respond them?

Thanks in advance for the help.

**Comment by torkelo** [comment]
you can use appEvents or your own global instance. 

import appEvents from 'app/core/app_events'; 

remember to unsubscribe on panel tear down 

please use community site developer category to post plugin dev questions

**Comment by davide97g** [comment]
Thanks for the answer. But what is my global instance? 
How can I access that? Is there any import required?

**Comment by torkelo** [comment]
Just create one yourself and import it

**Comment by davide97g** [comment]
Isn't equal to have a definition like 'AppCtrl'?
I am not able to figure out how to code an instance to be global for every import.

**Comment by torkelo** [comment]
just export an instance instead of the class

export const myApp = new AppCtrl();

**Comment by davide97g** [comment]
Ok great! Thanks for all the extra replies.
