### ISSUE TITLE
drag-handles to external links

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15586]
What Grafana version are you using? v5.4.3
What datasource are you using? InfluxDB
What OS are you running grafana on? Win10

Please provide drag-handles to links so that it can be repositioned anywhere in the dashboard.

**Comment by torkelo** [comment]
links are not part of the dashboard grid, if you want a link you can reposition use the text panel (not exactly the same but...) 

Will keep this in mind but closing for now
