### ISSUE TITLE
Improve Graphite function editor experience

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#15596]
Ref https://github.com/grafana/grafana/pull/15510

**Comment by dprokop** [comment]
Great job! This is working. I think a better option than showing it in a tooltip would be showing it in a help box at the top (where we show data source help / query inspector box):

![image](https://user-images.githubusercontent.com/10999/53082347-f5197500-34fc-11e9-8e62-3bf5653bb10c.png)

But would require a lot of new plumbing and hooks.

_Originally posted by @torkelo in https://github.com/grafana/grafana/pull/15510#issuecomment-465502420_

**Comment by dprokop** [comment]
I'm not sure if that is the best place to show the function docs. Some of the docs can be quite elaborate, what will make the UI experience jumpy. I personally think that in this case we should take inspiration from IDEs approach, where docs are simply shown on hover, instead of on click. I guess this can be the most natural interaction for majority of people.

Then, the other thing is functions reordering, which, as @jschill  already suggested, can be solved by drag and drop. 

So, the last thing that would then stay in the tooltip is function remove button. I have two ideas how to solve this and get rid of the tooltip:
1. Make the remove button always visible, left to the function name:
![image](https://user-images.githubusercontent.com/2376619/53228664-253e5080-3682-11e9-88eb-788228410319.png)
2. Utilise drag and drop and create "removal" area that's visible when user starts dragging the function. So, when user drops the function in this area, it would automatically be removed.

@torkelo @Ijin08 ^^

**Comment by torkelo** [comment]
yes, on hover is probably best.

**Comment by Ijin08** [comment]
I agree with Torkel. Especially drag and drop. But then we need an indication that it is possible:
<img width="780" alt="screenshot 2019-02-22 at 09 39 04" src="https://user-images.githubusercontent.com/23470681/53229938-cda1e400-3685-11e9-90e9-a75272197a07.png">

**Comment by jschill** [comment]
Always visible on touch screens?

**Comment by Ijin08** [comment]
I guess the drag icon need to be always be visible on touchscreen and indication where one can drag be shown while grabbing it.

**Comment by dprokop** [comment]
Good point Patrick!

One note to your mockup above is that I'm not sure if we can have the (X) removal button on the right, as people can edit function arguments there as well. On the other hand, having it on the left can conflict with the drag handle/indicator.

I think we will have to experiment with the placement of the button, which one feels more natural.

**Comment by Ijin08** [comment]
Thinking a removal area isn't such a bad idea. Could work better on smaller touch screens. 

But yes this needs some experimenting to get right.

**Comment by jschill** [comment]
> I'm not sure if we can have the (X) removal button on the right, as people can edit function arguments there as well.

Can you screenshot this? I'm not sure I follow.

**Comment by Ijin08** [comment]
@jschill 
<img width="362" alt="screenshot 2019-02-22 at 12 37 28" src="https://user-images.githubusercontent.com/23470681/53240317-b3283480-369e-11e9-9bed-c79978ef9e8a.png">

This is how it would be with removal button:
<img width="223" alt="screenshot 2019-02-22 at 12 37 40" src="https://user-images.githubusercontent.com/23470681/53240354-d05d0300-369e-11e9-8e21-a6ea5f4f7ed3.png">
