### ISSUE TITLE
[Feature Request] Enhance Google Hangouts Chat notifications with images and non-https links

### ISSUE THREAD

**Issue by TunaYagci** [grafana/grafana#15597]
Google Chat is added with 6.0.1-beta. It works really well and I need 2 more things:  
- Image is not supported (although it is added here, I don't understand why it's not working on me  https://github.com/grafana/grafana/pull/11410/files)
- Every link is https. I think this is done by Google, as @bergquist mentioned in: https://github.com/grafana/grafana/pull/11410#issuecomment-420967466 If there is any way to prevent it, it'd be super cool.

A proxy from webhook to Google Chat is a no-brainer but I don't want to hassle with that 😋 

Grafana version: 6.0.3-beta. Running on MacOS Mojave in a Docker. 
Datasource: Prometheus

**Comment by xlson** [comment]
Have you configured an image store? http://docs.grafana.org/alerting/notifications/#external-image-store

**Comment by TunaYagci** [comment]
@xlson oh I didn't see that one, sorry! Closing this one. If it still doesn't work I'll open another issue.
