### ISSUE TITLE
provide checkbox

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15594]
What Grafana version are you using? v6.00beta-3
What datasource are you using? InfluxDB
What OS are you running grafana on? Win10 & Ubuntu

I want a checkbox feature such that when it is checked the graph panels would display points and when unchecked, the graphs will not read data from datasource. 

[Also, the new react panel editor has got some bugs when I ran on Ubuntu. 
When clicked on query/visualization or any other tab, edit options sometimes doesnt show up.
I tried inspect element once, and the panel froze. Hope the release version will be free from such bugs.]

**Comment by torkelo** [comment]
you can use a row to collapse panels (ie hide them). 

> Also, the new react panel editor has got some bugs when I ran on Ubuntu. When clicked on query/visualization or any other tab, edit options sometimes doesnt show up. I tried inspect element once, and the panel froze

That is strange, we have 1 other similar report but been unable to replicate. what Browser & version are you using? CPU (might be timing issue)?

**Comment by debmalyapan53** [comment]
@torkelo actually row would just collapse panels and i dont want to hide them. i need a checkbox (probably templated) which would enable/disable the graph to read from datasource.

Regarding the other issue, i was using firefox v65. Also, maybe u are right, could be a cpu/memory issue.
