### ISSUE TITLE
When setting up multiple queries in a graph, clicking "Rate" on second query affects DOM elements from first query

### ISSUE THREAD

**Issue by PeterGrace** [grafana/grafana#1559]
Using docker container from grafana/grafana:develop
Version: Grafana version: 2.0.0-alpha, commit: 45a03a4-dirty, build date: 2015-03-02 06:56:40

As stated in subject, when trying to affect the "Rate" of the second query, the first query's dom objects are changed as a result of clicking the second query's Rate checkbox.

100% duplication across chrome and IE, url to try it out here: http://tb-docker.vsix.me:3000/dashboard/db/aws?panelId=2&fullscreen&edit -- login is currently default admin/admin

**Comment by torkelo** [comment]
Thanks for reporting this, fixed in develop branch and pushed an updated docker image to docker repository.

**Comment by torkelo** [comment]
havent pushed the docker image yet, docker registry is giving me a timeout when I tried to push right now, so maybe in a few minutes
