### ISSUE TITLE
Data Sources / OSIsoft-PI

### ISSUE THREAD

**Issue by nasaheers** [grafana/grafana#15609]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 

I have looked for related Issues and most of them talk about changing the security to Basic for PI Web API. this has been tested already and it is still failing.

![image](https://user-images.githubusercontent.com/37409641/53253260-6cc6db80-3686-11e9-99a7-7c3f1b9d82fa.png)

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

Looks like Grafana server cannot reach the URL you have specified
