### ISSUE TITLE
Grafana not decompresssing gzip stream from Graphite host

### ISSUE THREAD

**Issue by SamuelMarks** [grafana/grafana#1560]
I am using Grafana + Graphite + ElasticSearch (as per your setup documentation).

However, nothing loads on the graph, and I get a little `!` saying that there's a problem with the connection.

Taking a look with Firebug, I found a `200 OK` and the following equivalent cURL:
```
curl 'http://localhost/render' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.5' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Host: localhost' -H 'Origin: http://grafana' -H 'Pragma: no-cache' -H 'Referer: http://grafana/' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0' --data $'target=randomWalk(\'random%20walk\')&from=-6h&until=now&format=json&maxDataPoints=1841'
```

Running it gives me a bunch of garbage, which I recognised as binary. Putting `--compressed` on the end of that `curl` gave me:
```
[{"target": "random walk", "datapoints": [[0, 1425511388], 

… etc …

]}]
```

Removing this argument also made it work:
```
-H 'Accept-Encoding: gzip, deflate'
```

**How do I get Grafana to decompress the Graphite stream?**

**Comment by SamuelMarks** [comment]
Closing issue (this is a Graphite problem)

**Comment by torkelo** [comment]
decompression is done by the browser, not grafana! 

What is the result of your graphite request in chrome (dev tools / network tab)

**Comment by SamuelMarks** [comment]
Yeah, seems to be a problem with the headers graphite is sending over. The data payload isn't displayable in the network->data tab, as it's binary. Also I've configured Graphite and Grafana under Apache Web Server 2, so maybe I can change a setting there?
