### ISSUE TITLE
Explore split makes comparing times hard

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#15610]
Looking at correlating blips in lines, split makes it hard as the graphs are side-by-side and not stacked.

Don't have to stack, could have a common cursor between both panels.  Just an idea.

**Comment by davkal** [comment]
We're looking into shared cursors for this, even for logs. Some work exists, but might need to be adapted due to new graph panel work. 

CC @dprokop and @leeoniya : graphs should support shared cursors.

**Comment by ifrost** [comment]
> We're looking into shared cursors for this, even for logs. Some work exists, but might need to be adapted due to new graph panel work.
> 
> CC @dprokop and @leeoniya : graphs should support shared cursors.

Ongoing work for communication between panels that we will need for this feature: https://github.com/grafana/grafana/pull/30374

**Comment by ivanahuckova** [comment]
@ifrost I see that it already working on the master. Can we close the issue?

**Comment by ifrost** [comment]
> @ifrost I see that it already working on the master. Can we close the issue?
> 

Yes! 🏆

**Comment by tomwilkie** [comment]
Thank you! 🥇
