### ISSUE TITLE
Toggling "stack" should not refresh data

### ISSUE THREAD

**Issue by jsferrei** [grafana/grafana#15611]
This is a similar issue to https://github.com/grafana/grafana/issues/15202
Please include this information:
### What Grafana version are you using?
 6.0.0
### What OS are you running grafana on? 
MacOS
### What did you do? 
Toggled stack on/off
### What was the expected result?
 Display would change
### What happened instead? 
Display changed after requerying my TSDB

**Comment by jschill** [comment]
PR merged (https://github.com/grafana/grafana/pull/15612)
