### ISSUE TITLE
Calculating avg/min/max

### ISSUE THREAD

**Issue by kenzodeluxe** [grafana/grafana#1561]
Hi;
I am wondering what I am doing wrong here or what's happening. I am getting very weird results for the legend in Grafana (both current stable/development version and both in Firefox/Chrome).
Here's an example:
![screen1](https://cloud.githubusercontent.com/assets/6376222/6506463/8be2cd38-c34b-11e4-8379-b165ce7d2fa2.png)

As you can see, the actual maximum is around 150, not 63; the average is _always_ zero, whatever I do. Zooming further into this view I get the following:
![screen2](https://cloud.githubusercontent.com/assets/6376222/6506468/93d1fafa-c34b-11e4-8bf5-d44ad31dd68e.png)

Now the value for Max is correct, the average still is 0.
What am I missing here?
Thanks!

**Comment by torkelo** [comment]
What version of Grafana are you using?

**Comment by kenzodeluxe** [comment]
1.9.1 and grafana/grafana:develop (pulled today).

**Comment by torkelo** [comment]
What data source are you using? Can you open chrome dev tools and inspect the metric request? Would like to look at the values returned by Graphite/InfluxDB (or what ever db your are using)

**Comment by kenzodeluxe** [comment]
It's Influx, and this is a sample output (not exactly the one I am referring to above, but the problem is the same in all view):
[{"name":"dns/blah","columns":["time","distinct"],"points":[[1425560530000,"63"],[1425560545000,"0"],[1425560560000,"0"],[1425560575000,"0"],[1425560590000,"0"],[1425560605000,"0"],[1425560620000,"162"],[1425560635000,"0"],[1425560650000,"62"],[1425560665000,"0"],[1425560685000,"124"],[1425560700000,"0"],[1425560715000,"0"],[1425560730000,"0"],[1425560745000,"101"],[1425560760000,"0"],[1425560775000,"15"],[1425560790000,"0"],[1425560805000,"0"],[1425560820000,"0"],[1425560835000,"63"],[1425560850000,"0"],[1425560865000,"63"],[1425560880000,"0"],[1425560900000,"0"],[1425560915000,"0"],[1425560930000,"121"],[1425560945000,"0"],[1425560960000,"151"],[1425560975000,"0"],[1425560990000,"143"],[1425561005000,"0"],[1425561020000,"0"],[1425561035000,"0"],[1425561050000,"14"],[1425561065000,"0"],[1425561080000,"14"],[1425561095000,"0"],[1425561110000,"0"],[1425561130000,"0"],[1425561145000,"15"],[1425561160000,"0"],[1425561175000,"224"],[1425561190000,"0"],[1425561205000,"0"],[1425561220000,"0"],[1425561235000,"0"],[1425561250000,"0"],[1425561265000,"106"],[1425561280000,"0"],[1425561295000,"61"],[1425561310000,"0"],[1425561325000,"0"],[1425561345000,"0"],[1425561360000,"101"],[1425561375000,"0"],[1425561390000,"112"],[1425561405000,"0"],[1425561420000,"0"],[1425561435000,"0"],[1425561450000,"0"],[1425561465000,"0"],[1425561480000,"113"],[1425561495000,"0"],[1425561510000,"90"],[1425561525000,"0"],[1425561545000,"0"],[1425561560000,"0"],[1425561575000,"100"],[1425561590000,"0"],[1425561605000,"65"],[1425561620000,"0"],[1425561635000,"13"],[1425561650000,"0"],[1425561665000,"1"],[1425561680000,"0"],[1425561695000,"62"],[1425561710000,"0"],[1425561725000,"17"],[1425561740000,"0"],[1425561755000,"0"],[1425561775000,"0"],[1425561790000,"14"],[1425561805000,"0"],[1425561820000,"0"],[1425561835000,"0"],[1425561850000,"0"],[1425561865000,"0"],[1425561880000,"216"],[1425561895000,"0"],[1425561910000,"64"],[1425561925000,"0"],[1425561940000,"0"],[1425561955000,"0"],[1425561970000,"14"],[1425561985000,"0"],[1425562005000,"64"],[1425562020000,"0"],[1425562035000,"0"],[1425562050000,"0"],[1425562065000,"101"],[1425562080000,"0"],[1425562095000,"63"],[1425562110000,"0"],[1425562125000,"0"],[1425562140000,"0"],[1425562155000,"61"],[1425562170000,"0"],[1425562185000,"119"],[1425562200000,"0"],[1425562220000,"0"],[1425562235000,"0"],[1425562250000,"0"],[1425562265000,"0"],[1425562280000,"63"],[1425562295000,"0"],[1425562310000,"0"],[1425562325000,"0"],[1425562340000,"0"],[1425562355000,"0"],[1425562370000,"66"],[1425562385000,"0"],[1425562400000,"0"],[1425562415000,"0"],[1425562430000,"0"],[1425562450000,"0"],[1425562465000,"130"],[1425562480000,"0"],[1425562495000,"108"],[1425562510000,"0"],[1425562525000,"0"],[1425562540000,"0"],[1425562555000,"14"],[1425562570000,"0"],[1425562585000,"64"],[1425562600000,"0"],[1425562615000,"0"],[1425562630000,"0"],[1425562645000,"15"],[1425562660000,"0"],[1425562680000,"107"],[1425562695000,"0"],[1425562710000,"0"],[1425562725000,"0"],[1425562740000,"0"],[1425562755000,"0"],[1425562770000,"61"],[1425562785000,"0"],[1425562800000,"0"],[1425562815000,"0"],[1425562830000,"0"],[1425562845000,"0"],[1425562860000,"14"],[1425562875000,"0"],[1425562890000,"0"],[1425562910000,"0"],[1425562925000,"122"],[1425562940000,"0"],[1425562955000,"113"],[1425562970000,"0"],[1425562985000,"0"],[1425563000000,"0"],[1425563015000,"0"],[1425563030000,"0"],[1425563045000,"63"],[1425563060000,"0"],[1425563075000,"0"],[1425563090000,"0"],[1425563105000,"0"],[1425563125000,"0"],[1425563140000,"15"],[1425563155000,"0"],[1425563170000,"0"],[1425563185000,"0"],[1425563200000,"0"],[1425563215000,"0"],[1425563230000,"14"],[1425563245000,"0"],[1425563260000,"0"],[1425563275000,"0"],[1425563290000,"112"],[1425563305000,"0"],[1425563320000,"63"],[1425563335000,"0"],[1425563355000,"0"],[1425563370000,"0"],[1425563385000,"0"],[1425563400000,"0"],[1425563415000,"63"],[1425563430000,"0"],[1425563445000,"101"],[1425563460000,"0"],[1425563475000,"0"],[1425563490000,"0"],[1425563505000,"0"],[1425563520000,"0"],[1425563535000,"127"],[1425563550000,"0"],[1425563570000,"0"],[1425563585000,"0"],[1425563600000,"0"],[1425563615000,"0"],[1425563630000,"235"],[1425563645000,"0"],[1425563660000,"14"],[1425563675000,"0"],[1425563690000,"0"],[1425563705000,"0"],[1425563720000,"45"],[1425563735000,"0"],[1425563750000,"113"],[1425563765000,"0"],[1425563785000,"0"],[1425563800000,"0"],[1425563815000,"0"],[1425563830000,"0"],[1425563845000,"13"],[1425563860000,"0"],[1425563875000,"0"],[1425563890000,"0"],[1425563905000,"0"],[1425563920000,"0"],[1425563935000,"15"],[1425563950000,"0"],[1425563965000,"0"],[1425563980000,"0"],[1425563995000,"101"],[1425564015000,"0"],[1425564030000,"63"],[1425564045000,"0"],[1425564060000,"132"],[1425564075000,"0"],[1425564090000,"0"],[1425564105000,"0"],[1425564120000,"118"]]}]

**Comment by torkelo** [comment]
Ok, I see the problem, you are writing strings to InfluxDB not numbers, Grafana only handle numbers has metric values. Please update the agent sending values to InfluxDB to send values as number and not strings.

**Comment by kenzodeluxe** [comment]
Yikes! Thanks for the heads up; works fine now. Much appreciated!
