### ISSUE TITLE
Add option to make header 'floating'

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1562]
On dashboards with lots of panels it would be useful to be able to select a different template instance or change the timespan without scrolling to the top of the page.  Request is to add an option that would make the header 'floating'.

So for example this portion of the Grafana UI would always be shown regardless of your scroll location in the page:
![image](https://cloud.githubusercontent.com/assets/917241/6507350/d99ed7b4-c351-11e4-82cd-9afea091cb06.png)

**Comment by torkelo** [comment]
not sure about this
