### ISSUE TITLE
Return empty query result for each query & generated SQL 

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#15625]
Generated SQL Randomly Disappears

Example:

![image](https://user-images.githubusercontent.com/3651746/53302414-d92f0f80-382b-11e9-98e4-3feb9950130d.png)

Unsure when exactly.

**Comment by daniellee** [comment]
It happens when no result is returned as the generated sql is part of the result - we could maybe fix the backend to always returned the generated sql. 

But could also be something to with the conversion to React - the error handling has just been changed.

**Comment by PeterZaitsev** [comment]
Well...  If I get empty result set this is exactly when I can see Generated Query so I can see what is wrong :)

Empty result is the most typical "unexpected query result" which one needs to debug :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
