### ISSUE TITLE
v6.0.0-beta1: Cannot assign axis in series override

### ISSUE THREAD

**Issue by andig** [grafana/grafana#15621]
In Grafana v6.0.0-beta1 (d7f81c4) it is not possible to assign a series to a different axis. After selecting the series from the respective dropdown menu, it is not displayed in the editor:

<img width="691" alt="screenshot 2019-02-24 at 10 17 32" src="https://user-images.githubusercontent.com/184815/53297330-8b130f80-381d-11e9-918e-5486105c15ac.png">

**Comment by daniellee** [comment]
Confirmed. Think it is the same problem as in this issue: #14871. Will get a fix for this into 6.0.

**Comment by andig** [comment]
Quite possible- I‘ll double check using docker:master. Thank you!

**Comment by daniellee** [comment]
@andig just to be clear - it is not fixed in master. Fixing it now - so should be merged later today (probably tomorrow for you as I'm in LA today).
