### ISSUE TITLE
Image rendering broken for slack alerts on 6.0.0-beta2 and 6.0.0-beta3

### ISSUE THREAD

**Issue by tonidas** [grafana/grafana#15631]
### What Grafana version are you using?
6.0.0-beta3 (Official Docker Image https://hub.docker.com/r/grafana/grafana/tags)
### What datasource are you using?
AWS
### What OS are you running grafana on?
debian:stretch-slim
### What did you do?
Upgraded from 6.0.0-beta1 to 6.0.0-beta3
### What was the expected result?
The alert image on slack integration should be working
### What happened instead?
If configured to send the images directly to slack, It shows the default image (The same that It shows on the alert testing) below the alert message.

![screen shot 2019-02-24 at 5 03 37 pm](https://user-images.githubusercontent.com/548878/53304633-3f308c80-3856-11e9-8e18-fc8f7f1448c3.png)

If configured to send the images to S3, It shows just the alert message.
### Additional information from my analysis
I've tried to reproduce the whole rendering flow, and it seems that the problem occurs on phantomjs. It seems that it can't render the image from the chart url that grafana sends to.

The grafana logs show messages saying that the rendering timed out:

```
t=2019-02-24T01:08:23+0000 lvl=info msg="Initializing RenderingService" logger=server
t=2019-02-24T01:17:05+0000 lvl=info msg=Rendering logger=rendering path="d-solo/AKdfCKLmz/application-metrics-exchange-roadrunner?panelId=4"
t=2019-02-24T01:17:34+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-02-24T01:17:35+0000 lvl=info msg=Rendering logger=rendering path="d-solo/aS71smbik/aws-overview?panelId=2"
t=2019-02-24T01:18:04+0000 lvl=info msg="Rendering timed out" logger=rendering
```

So i've debugged the phantomjs calls with a custom grafana that I've build (with ethernal renderKeys)

```
./phantomjs --ignore-ssl-errors=true --web-security=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/AKdfCKLmz/application-metrics-exchange-roadrunner?panelId=4\&render=1 png=/var/lib/grafana/png/CxMpbtan2HtNxMjHeZg7.png width=1000 height=500 domain=localhost timeout=27 renderKey==XXXXXXXXX
```

And it seems that phantomjs is unable to load the chart:

```
Loading a web page: http://localhost:3000/d-solo/AKdfCKLmz/application-metrics-exchange-roadrunner?panelId=4&render=1 status: success 27000
ERROR: TypeError: undefined is not an object (evaluating 'container[0].getBoundingClientRect')
TRACE:
 -> undefined: 6
 -> : 7

  phantomjs://code/render.js:48 in onError
TypeError: null is not an object (evaluating 'bb.width')

  phantomjs://code/render.js:68 in checkIsReady
```

It waits very long for the panel to be rendered, but it never gets rendered.

https://github.com/grafana/grafana/blob/6a71b199ca8da8f488540861d6a5a8e32f46d088/tools/phantomjs/render.js#L52-L55

So it enters on the render.js finalization and raises the error

https://github.com/grafana/grafana/blob/6a71b199ca8da8f488540861d6a5a8e32f46d088/tools/phantomjs/render.js#L57-L73

From the grafana app perspective, the timeout was already reached and it doesn't matter the js error.

I've tried to access the same route that phantomjs is trying to reach (http://localhost:3000/d-solo/AKdfCKLmz/application-metrics-exchange-roadrunner?panelId=4&render=1) and in the first time that chromes load the page, nothing gets rendered, except a message:

![screen shot 2019-02-24 at 4 40 30 pm](https://user-images.githubusercontent.com/548878/53304635-51aac600-3856-11e9-8da6-f55d09ec2adc.png)

If I hit refresh, the page loads fine. I'm supposing that it's the same problem that phantomjs is facing.

Oddly enough, on the first load on chrome, there is a log on the console, showing something about updating angular $location.url:

```
store updating angular $location.url /d-solo/AKdfCKLmz/application-metrics-exchange-roadrunner?orgId=1&panelId=2&render=1%20width%3D1000
```

When I refresh the page, this log doesn't appear anymore.

I guess it's related to the React -> Angular sync of the location:

https://github.com/grafana/grafana/blob/6a71b199ca8da8f488540861d6a5a8e32f46d088/public/app/core/services/bridge_srv.ts#L42-L56

I've also tried the version 6.0.0-beta2, and it seems that the problem started on that version.
Doing a quick diff between the releases 6.0.0-beta1 and 6.0.0-beta2 I've got something that caught my attention:

```
~/w/g/grafana ❯❯❯ git diff v6.0.0-beta1..v6.0.0-beta2 -- public/app/core/services/bridge_srv.ts                                                                                              ⏎
diff --git a/public/app/core/services/bridge_srv.ts b/public/app/core/services/bridge_srv.ts
index 37f719463..8bb828310 100644
--- a/public/app/core/services/bridge_srv.ts
+++ b/public/app/core/services/bridge_srv.ts
@@ -46,6 +46,10 @@ export class BridgeSrv {
       if (angularUrl !== url) {
         this.$timeout(() => {
           this.$location.url(url);
+          // some state changes should not trigger new browser history
+          if (state.location.replace) {
+            this.$location.replace();
+          }
         });
         console.log('store updating angular $location.url', url);
       }
```

I guess that the problem resides there, but I don't have enough knowledge of the code to make that affirmation.

For now I've downgraded to 6.0.0-beta1 and It's working fine.

**Comment by marefr** [comment]
Thank you for the great bug report! 

I think it's related to the `Loading & initializing dashboard` which sort of is triggered from https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/initDashboard.ts#L130-L134

**Comment by seriych** [comment]
The same problem on 6.0.0 stable / Windows Server 2016.
`t=2019-02-26T09:50:31+0500 lvl=info msg="Rendering timed out" logger=rendering
t=2019-02-26T09:50:31+0500 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-02-26T09:50:31+0500 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=209 notification=alert_slack_webhook
t=2019-02-26T09:50:32+0500 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
t=2019-02-26T09:50:32+0500 lvl=eror msg="Failed to upload slack image" logger=alerting.notifier.slack error="context deadline exceeded" webhook=file.upload
t=2019-02-26T09:50:32+0500 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000004 error="context deadline exceeded"`
![gr6](https://user-images.githubusercontent.com/15708872/53389300-90549380-39b0-11e9-98a2-e6402d21ef29.png)

**Comment by A-styler** [comment]
Same problem, 6.0.0 official docker image

**Comment by ulrichSchreiner** [comment]
same here. 6.0.0 official docker image but my slack notifications are now missing the images.

**Comment by mchesler** [comment]
I’m having the same issue. 6.0.0 running on Ubuntu 14.04 installed over 5.2.4 with deb packages

**Comment by dcorto-eu** [comment]
Updated to 6.0.0 and the Telegram bot has no images. Worked fine on 5.x

**Comment by genofire** [comment]
It does not make problem in alert alone, it is generic with all graph to image rendering ...

At:
 `http://localhost:8080/render/d-solo/000000001/globals?panelId=2&from=now-7d&width=650&height=350&theme=light`

We receive `Timeout error. You can set timeout in seconds with &timeout url parameter`

**Comment by M-M-M-M** [comment]
I have the same issue on Centos 7.6.1810 using grafana 6.0.0 package on email alerting. Since the upgrade to 6.0.0 the image are anymore attached to email despite they are generated on /var/lib/grafana/png.

**Comment by NotSqrt** [comment]
The rendering of solo panels in iframes (embed) is also stuck on `Loading & initializing dashboard`.

**Comment by torkelo** [comment]
@NotSqrt that looks unrelated, and not something I can replicate.

Tested this:

```html
<iframe src="https://play.grafana.org/d-solo/000000012/grafana-play-home?orgId=1&from=1551687324454&to=1551694524454&panelId=2" width="450" height="200" frameborder="0"></iframe>
```

And it loads fine.

**Comment by genofire** [comment]
Nice it works @ play.grafana.org:
For me it looks also like a really old cache:
 ![upstream](https://play.grafana.org/render/d-solo/000000012/grafana-play-home?orgId=1&from=1551687324454&to=1551694524454&panelId=2)

**Comment by NotSqrt** [comment]
@torkelo You're right. I had old urls pointing to embedded panels, so the browser followed HTTP redirects to get to the proper panel. After updating the urls, it works.

**Comment by torkelo** [comment]
When you get these timeouts, is the query for that alert slow? Are you missing images on all panels? 

Been trying to replicate this but unable to get timeout even with queries take 25s I get an image uploaded to s3 and included in slack. 

Will try the slack upload feature next. 

For poeple who have this issue please include any more info you can think of that could be relevant.

**Comment by genofire** [comment]
@torkelo No - same problem with webhook with local-provider (for my xmpp-alert replace) it has the same problem -> it does not depend to s3 or slack

**Comment by marefr** [comment]
@genofire @tonidas @seriych @A-styler @ulrichSchreiner @M-M-M-M @mchesler could you please enable phantomjs debug log and router logging and report the output from Grafana server log when you get the timeouts:

```ini
[server]
router_logging = true

[log]
filters = rendering:debug
```

or if you're using docker use environment variables: 
`GF_SERVER_ROUTER_LOGGING=true`
`GF_LOG_FILTERS=rendering:debug`

Here's a snippet from Grafana server log when I'm forcing a timeout to happen:
```
INFO[03-05|19:18:26] Rendering                                logger=rendering path="d-solo/RMfOo-riz/slow-query?orgId=1&from=1551788305066&to=1551809905066&panelId=2&width=1000&height=500&tz=Europe%2FStockholm"
INFO[03-05|19:18:26] Request Completed                        logger=context userId=1 orgId=1 uname= method=GET path=/d-solo/RMfOo-riz/slow-query status=200 remote_addr=127.0.0.1 time_ms=7 size=14763 referer=
INFO[03-05|19:18:27] Request Completed                        logger=context userId=1 orgId=1 uname= method=GET path=/api/dashboards/uid/RMfOo-riz status=200 remote_addr=127.0.0.1 time_ms=1
size=963 referer="http://localhost:3000/d-solo/RMfOo-riz/slow-query?orgId=1&from=1551788305066&to=1551809905066&panelId=2&width=1000&height=500&tz=Europe%2FStockholm&render=1"
INFO[03-05|19:18:27] Request Completed                        logger=context userId=1 orgId=1 uname= method=GET path=/api/annotations status=200 remote_addr=127.0.0.1 time_ms=0 size=30 referer="http://localhost:3000/d-solo/RMfOo-riz/slow-query?orgId=1&from=1551788305066&to=1551809905066&panelId=2&width=1000&height=500&tz=Europe%2FStockholm&render=1"
INFO[03-05|19:18:28] Rendering timed out                      logger=rendering
EROR[03-05|19:18:28] Timeout error. You can set timeout in seconds with &timeout url parameter logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
EROR[03-05|19:18:28] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/RMfOo-riz/slow-query status=500 remote_addr=[::1] time_ms=2029 size=799 referer="http://localhost:3000/d/RMfOo-riz/slow-query?orgId=1"
INFO[03-05|19:18:32] Request Completed                        logger=context userId=1 orgId=1 uname= method=POST path=/api/tsdb/query status=200 remote_addr=127.0.0.1 time_ms=5052 size=8192
referer="http://localhost:3000/d-solo/RMfOo-riz/slow-query?orgId=1&from=1551788305066&to=1551809905066&panelId=2&width=1000&height=500&tz=Europe%2FStockholm&render=1"
```

Thanks

**Comment by ulrichSchreiner** [comment]
hi,
i added the settings to the docker environment and created an alert, here are the logs:
~~~
t=2019-03-06T05:45:09+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=35 newState=alerting prev state=ok
t=2019-03-06T05:45:09+0000 lvl=info msg=Rendering logger=rendering path="d-solo/N94IMQqzz/site-availability?panelId=1"
t=2019-03-06T05:45:09+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/d-solo/N94IMQqzz/site-availability status=200 remote_addr=127.0.0.1 time_ms=1 size=27096 referer=
t=2019-03-06T05:45:10+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/dashboards/uid/N94IMQqzz status=200 remote_addr=127.0.0.1 time_ms=5 size=31186 referer="http://localhost:3000/d-solo/N94IMQqzz/site-availability?panelId=1&render=1"
t=2019-03-06T05:45:10+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/dashboards/uid/N94IMQqzz status=200 remote_addr=127.0.0.1 time_ms=4 size=31186 referer="http://localhost:3000/d-solo/N94IMQqzz/site-availability?orgId=1&panelId=1&render=1"
t=2019-03-06T05:45:10+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/dashboards/uid/N94IMQqzz status=200 remote_addr=127.0.0.1 time_ms=4 size=31186 referer="http://localhost:3000/d-solo/N94IMQqzz/site-availability?orgId=1&panelId=1&render=1&refresh=30s"
t=2019-03-06T05:45:38+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-03-06T05:45:38+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-03-06T05:45:38+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xxxx]
t=2019-03-06T05:45:38+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=35 notification=Protegear-Slack
~~~

**Comment by AutomationEngineer** [comment]
> @NotSqrt that looks unrelated, and not something I can replicate.
> 
> Tested this:
> 
> ```
> <iframe src="https://play.grafana.org/d-solo/000000012/grafana-play-home?orgId=1&from=1551687324454&to=1551694524454&panelId=2" width="450" height="200" frameborder="0"></iframe>
> ```
> 
> And it loads fine.

Hi!

Don't know wether it is related to this issue or another, but when I select a time period to zoom by mouse, I get the same "Loading & initializing dashboard", reloading page however shows zoomed selection.

Im testing:
https://play.grafana.org/d-solo/000000012/grafana-play-home?orgId=1&from=1551687324454&to=1551694524454&panelId=2
without iframe, and with iframe - same behaviour, and the same with my local installation of 6.0.0

**Comment by torkelo** [comment]
For people who are having this timeout can you include a screenshot of the graph & maybe panel json (remove any sensitive data before).  Maybe there is a specific graph option that causes this.

**Comment by torkelo** [comment]
So was able to track this down from the logs, I found repeat loads of the dashboard via the api. and the added url param refresh. So was able to replicate this by adding auto refresh to the dashboard with the alert rule and saving dashboard. 

Fix incoming in PR #15818

**Comment by richerlariviere** [comment]
When using Grafana 6.0.1, I am still having the issue:

```
t=2019-03-18T15:38:10+0000 lvl=dbug msg="Phantomjs output" logger=rendering out=
t=2019-03-18T15:38:10+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
t=2019-03-18T15:38:10+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
t=2019-03-18T15:38:10+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="signal: killed"
t=2019-03-18T15:38:10+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification="Grafana Slack notification"
t=2019-03-18T15:38:11+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack 
```

**Comment by tonidas** [comment]
Hi @richerlariviere, my problems disappeared on 6.0.1.
By your logs it seems that the PhantomJS process is being killed. How much memory are you reserving for him?

**Comment by richerlariviere** [comment]
I'm deploying on Azure Kubernetes using grafana helm chart. In the values.yaml I uncommented the following part (I'm not sure if this is what you want to know):

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

**Comment by richerlariviere** [comment]
When I add more memory (I actually doubled it), I can confirm the creation of the blob in Azure.

**Comment by tonidas** [comment]
I think that 128Mi is too low, try something like 512Mi :)

On my tests the PhantomJS consumes like 130Mi for a single render, but imagine that multiple renderings are ocurring at the same time..

You can also set a limit of concurrent renderings to ensure that the memory limit will be surpassed. http://docs.grafana.org/installation/configuration/#concurrent-render-limit

**Comment by erayalakese** [comment]
If you still have this issue, try installing dependencies as explained here :

https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshoot-image-rendering
