### ISSUE TITLE
Grafana add up metrics from same source but different dimensions - Netdata

### ISSUE THREAD

**Issue by flippy1345** [grafana/grafana#15638]
Hi,
I have the problem that metrics from the same source but with different dimensions can't be added up, subtracted or ...etc.

```
netdata_system_ram{chart="system.ram",family="ram",dimension="used"}
+netdata_system_ram{chart="system.ram",family="ram",dimension="free"} 
```
Can't be processed, while something like:

```
netdata_system_ram_used{chart="system.ram",family="ram"}
+netdata_system_ram_free{chart="system.ram",family="ram"}
```
would work.

Both statements would result in a single metric with 1 value.

```
netdata_system_ram{chart="system.ram",family="ram",dimension="used"}

netdata_system_ram_used{chart="system.ram",family="ram"}
```
I have attached an image, with the top not being able to be added up and the bottom being able to be added up.

![image](https://user-images.githubusercontent.com/26430962/53330766-a3ebf580-38ef-11e9-9427-6406a4dc5a55.png)

**Comment by xlson** [comment]
Hi, GitHub is for issues, not support. You could ask this question on our community forum https://community.grafana.com or try a Prometheus specific site.
