### ISSUE TITLE
Heatmap: data/units on Y-axis are in wrong order

### ISSUE THREAD

**Issue by zstyblik** [grafana/grafana#15637]
### What Grafana version are you using?

5.4.3

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Grafana running from official Docker Image.

### What did you do?

Created heatmap with: 
* query`rate(mongodb_mongod_op_latencies_histogram{instance="$host",type="read"}[10m])`
* legend format `{{micros}}` which is prom label eg. `micros="8"`
* format as heatmap
* data format "time series as buckets"
* unit "microseconds".

Data are pre-bucketed and are in "micros" which I took for microseconds.

### What was the expected result?

Buckets on Y-axis are in correct order. That is, from bottom to top, nano, micro, milli, seconds etc.

### What happened instead?

Nano, micro and milliseconds are all mixed up.

![heatmap_unit_order](https://user-images.githubusercontent.com/6183869/53328345-08a45180-38ea-11e9-9c36-b87ffc8d8628.png)

This might be related to https://github.com/grafana/grafana/issues/14781 and/or https://github.com/grafana/grafana/issues/14059. At least those are the most related issues I've found.

**Comment by alexanderzobnin** [comment]
@zstyblik could you post data returned by prometheus? Looks like labels are not recognized as a valid numbers, so it were sorted alphabetically.

**Comment by zstyblik** [comment]
@alexanderzobnin sure, no problem. [Here](https://github.com/grafana/grafana/files/2905980/prom_response.txt) it is. Hope it helps. My naive thinking is, labels are converted to respective units first and sorted later leading to wrong order. But then, I'm not familiar with source code ... at all.

If there is anything else, let me know.

Thanks.

**Comment by alexanderzobnin** [comment]
@zstyblik Are you sure query format (_Format as_) is a `Heatmap`? Looks very similar to `Time series`. Could you post your panel json and query editor screenshot?

**Comment by zstyblik** [comment]
@alexanderzobnin It's possible I've missed something, because I don't keep this panel around(hmm, maybe I've specified min step before for whatever reason?). However, I've checked current data V. previous data and they look more or less same. Anyway, here goes panel definition:

```
{
  "type": "heatmap",
  "title": "Panel Title",
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 9
  },
  "id": 91,
  "datasource": "$datasource",
  "targets": [
    {
      "expr": "rate(mongodb_mongod_op_latencies_histogram{instance=\"$host\",type=\"read\"}[10m])",
      "intervalFactor": 10,
      "format": "heatmap",
      "refId": "A",
      "legendFormat": "{{ micros }}"
    }
  ],
  "heatmap": {},
  "cards": {
    "cardPadding": null,
    "cardRound": null
  },
  "color": {
    "mode": "spectrum",
    "cardColor": "#b4ff00",
    "colorScale": "sqrt",
    "exponent": 0.5,
    "colorScheme": "interpolateOranges"
  },
  "legend": {
    "show": false
  },
  "dataFormat": "tsbuckets",
  "yBucketBound": "auto",
  "xAxis": {
    "show": true
  },
  "yAxis": {
    "show": true,
    "format": "µs",
    "decimals": null,
    "logBase": 1,
    "splitFactor": null,
    "min": null,
    "max": null
  },
  "xBucketSize": null,
  "xBucketNumber": null,
  "yBucketSize": null,
  "yBucketNumber": null,
  "tooltip": {
    "show": true,
    "showHistogram": false
  },
  "highlightCards": true,
  "links": []
}
```

And here goes screenshot(I'm not sure if this is what you've asked for): 
![grafana](https://user-images.githubusercontent.com/6183869/53431824-a5054b80-39f1-11e9-96f6-6ad9181963e8.png)

**Comment by zstyblik** [comment]
It is or was according to http://docs.grafana.org/features/panels/heatmap/ . Also, I've checked again, and even with min-step specified(just to be sure), response looks the same to me :|

**Comment by alexanderzobnin** [comment]
@zstyblik Does it work with Unit set to `none` or `short`?

**Comment by zstyblik** [comment]
@alexanderzobnin I've just checked and the answer is no. It looks to be the same, but when Unit is set to `none` then the sort order is like: 9xxx, 8xxx, 8, 65xxx, 64, 61xx etc.

**Comment by alexanderzobnin** [comment]
@zstyblik Ok, looks very strange - labels are valid numbers, all options are set. I'll try to replicate this and investigate why it happens.

**Comment by zstyblik** [comment]
This is present in 6.x(just stating, probably not surprising) with addition of graphical glitch. I did look at JS related to histogram, but I have no idea what's going on in there. Sorry :(

**Comment by alexanderzobnin** [comment]
@zstyblik Got it. This bug caused by sorting prometheus result by `le` label only. If any other label is used, bug appears. So proper solution - sort transformed result by series alias.

**Comment by zstyblik** [comment]
Thank you @alexanderzobnin :)

**Comment by vilinski** [comment]
what about influxdb v2 source?

grafana: v9.1.6
saved opentelemetry data from a dotnet process into influxdb v2

have the same problem, using this flux query:

```flux
from(bucket: r.bucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "http.client.duration" and r._field =~ /\d+/)
  |> keep(columns: ["name", "_time", "_value", "_field"])
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")
```

looks like this:
![grafik](https://user-images.githubusercontent.com/259479/208477504-57dd0b0e-cd5a-402f-81ee-6ed7514ef92f.png)

**Comment by leeoniya** [comment]
please open a new issue with a debug snapshot of this panel (it will have the raw response data embedded in it so we can investigate further)

https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#panel-help-menu

![image](https://user-images.githubusercontent.com/43234/200391751-ca1c338a-460b-46de-b881-87ea81e55f5d.png)
