### ISSUE TITLE
Dashboard name cannot be the same as folder

### ISSUE THREAD

**Issue by cassianoleal** [grafana/grafana#15642]
This seems to be a very deliberate behaviour but it's not clear to me why. Folders and dashboards are very different entities with their own IDs and as such shouldn't need to be named differently.

### What Grafana version are you using?

> Grafana v5.1.5 (69ab6cb72)

### What datasource are you using?

N/A

### What OS are you running grafana on?

Debian Stretch 9.4

### What did you do?

- Create a folder called `foo`
- Tried to save a dashboard `foo` in the folder

### What was the expected result?

A folder/dashboard structure like `foo/foo`

### What happened instead?

An error message:
> Dashboard name cannot be the same as folder

**Comment by xlson** [comment]
Internally Dashboards and folders share the same database table and some of the same code. This will be changed in the future, but for now, this creates limits like this.

**Comment by tomwilkie** [comment]
@xlson any chance we can revisit this now?

**Comment by mikewyer** [comment]
For anyone reading this in 2023:
Grafana still prevents you from adding a dashboard with the same name as an existing folder,
BUT it will let you rename a folder to be the same as an existing dashboard.

So to workaround this, temporarily rename the folder, add the dashboard, rename the folder back again.
