### ISSUE TITLE
[Bug] Alert on singlestat panel?

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15646]
What Grafana version are you using? v6.00 built from source
What datasource are you using? InfluxDB
What OS are you running grafana on? Win10
What did you do? Clicked on alert tab on graph panel and then clicked on edit on singlestat panel

As far as I know, there is no alert tab on singlestat...
![image](https://user-images.githubusercontent.com/35651463/53360525-bd2a8b80-395b-11e9-9ce5-4649c5723874.png)

**Comment by Paul-Reed** [comment]
Not a bug - just not developed yet.
See - http://docs.grafana.org/alerting/rules/#rule-config

**Comment by xlson** [comment]
Could you describe in a bit more detail how you managed to come to the alert view for a singlestat panel? What do you mean by "Clicked on alert tab on graph panel"

**Comment by debmalyapan53** [comment]
What I meant was that after adding an alert rule, I exited the panel editor of the graph panel and went to the panel editor of the singlestat panel. Then I saw the alert tab there..
