### ISSUE TITLE
HTML is not working in Text panel using Grafana 6

### ISSUE THREAD

**Issue by ortizleo** [grafana/grafana#15647]
Hello.

HTML stop work after update do Grafana 6. Its is not interpreted by grafana that only show the code.

Example attached. This code works on Grafana 5.x, it should display an image.

<img src="http://address/sap.png" align="right" style="margin: 0; padding: 0; border: none; width:60%; position:relative; top:-8px; overflow:hidden; margin-bottom: -70px;" </img>

![image](https://user-images.githubusercontent.com/17042298/53368862-9d2da480-3928-11e9-9918-867a650e1edd.png)

**Comment by dprokop** [comment]
@ortizleo this is related to the breaking changes introduced in 6.0: 

> The text panel does no longer by default allow unsantizied HTML. #4117. This means that if you have text panels with scripts tags they will no longer work as before. To enable unsafe javascript execution in text panels enable the settings disable_sanitize_html under the section [panels] in your Grafana ini file, or set env variable GF_PANELS_DISABLE_SANITIZE_HTML=true.

https://github.com/grafana/grafana/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by slim-bean** [comment]
Anybody else who's ended up here googling this may want to use this link:

https://github.com/grafana/grafana/blob/v6.0.0/CHANGELOG.md#breaking-changes-1

Which is pinned to the tag and should get you in the right place.
