### ISSUE TITLE
SQL: Variables should be shown in the auto-completion list in the SQL data source query editors

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#15644]
Hi,

Grafana 6.0.0 release fixed what $__interval_ms works in SQL data source. However it is still not showing up in the auto-completion list which I as a user will show all available variables

![image](https://user-images.githubusercontent.com/3651746/53360194-e66afd80-3902-11e9-8743-7bf109d7f426.png)

**Comment by hugohaggmark** [comment]
Confirmed this in Grafana 7.3.1.

**Comment by marefr** [comment]
As far as I know this have never worked why labeled as a feature request.

**Comment by hugohaggmark** [comment]
> As far as I know this have never worked why labeled as a feature request.

My bad, I saw the feature-request label you added @marefr and just edited the title.
