### ISSUE TITLE
Can't compile sass (missing package.json)

### ISSUE THREAD

**Issue by dagord** [grafana/grafana#15655]
Hello,
I downloaded the Docker version of Grafana 5.4.3
Now, I need some little CSS customization (let's say: changing color background), so I edited the public/sass/_variables.light.scss file.
But I can't compile the assets (I installed nodejs, npm, yarn and go).
When I run
`yarn start`

I get this error message:
`Couldn't find a package.json file in "/usr/share/grafana"`

What I am missing?
By the way, since I'm working in a testing environment, there's a way to run Grafana without compiling assets? Forcing the development mode doesn't seem to help.

**Comment by xlson** [comment]
The Docker container has everything needed to run Grafana, but not develop it. I'd suggest taking a look at our [Building from source](http://docs.grafana.org/project/building_from_source/) guide.
