### ISSUE TITLE
Grafana playlists doesn't seem to work in v6.0.0

### ISSUE THREAD

**Issue by kaspernissen** [grafana/grafana#15656]
### What Grafana version are you using?
v6.0.0

### What datasource are you using?
Test data from Grafana - random walk

### What OS are you running grafana on?
Debian

### What did you do?
Steps to reproduce: 

Run the official docker image:
```
docker run -p 3000:3000 grafana/grafana:6.0.0
```

1. Sign-in and create two random dashboards, give both dashboards the same tag. 
2. Go to Playlists and create a new playlist.
3. Select the tag you choose before and start the playlist

No dashboard is shown, just a blank screen. Same result for all modes.

![screenshot 2019-02-26 at 08 59 42](https://user-images.githubusercontent.com/4429108/53396535-f76c4b00-39a4-11e9-896b-6dd93d756669.png)

No errors in the Console of the Browser.

### What was the expected result?
Tagged dashboards to be rotated.

**Comment by xlson** [comment]
Thanks for a clear bug report. We will look into it.

I tested it and it's only playlists based on tags that are affected, manually created playlists work as normal.
