### ISSUE TITLE
Different execution-user not used in rc.init

### ISSUE THREAD

**Issue by enexusde** [grafana/grafana#15652]
Please include this information:
### What Grafana version are you using?
grafana -v gives: Version master (commit NA)
### What OS are you running grafana on?
Puppy Linux
### What did you do?
Installed Grafana, influxdb, telegraf
Tried to start server.
### What was the expected result?
chown must be called with the credentials set in the /etc/init.d/grafana .
### What happened instead?
chown has been called with default credentials grafana:grafana

![image](https://user-images.githubusercontent.com/6880636/53394238-e7ea0380-399e-11e9-85e8-0bfe58f6467e.png)

**Comment by xlson** [comment]
It's very hard to help you figure out what went wrong without seeing the rest of `/etc/init.d/grafana`.

Can you share the rest of your init script?
How did you install Grafana?
Do you by any chance have any other init system installed (like upstart or systemd)?
What happens if you run the init script manually? `/etc/init.d/grafana start`

**Comment by enexusde** [comment]
1. Its part of the package.
`#!/bin/sh                                                                                                                                                                                                                                       `
`                                                                                                                                                                                                                                                `
`# chkconfig: 2345 80 05                                                                                                                                                                                                                         `
`# description: Grafana web server & backend                                                                                                                                                                                                     `
`# processname: grafana                                                                                                                                                                                                                          `
`# config: /etc/grafana/grafana.ini                                                                                                                                                                                                              `
`# pidfile: /var/run/grafana.pid                                                                                                                                                                                                                 `
`                                                                                                                                                                                                                                                `
`### BEGIN INIT INFO                                                                                                                                                                                                                             `
`# Provides:          grafana                                                                                                                                                                                                                    `
`# Required-Start:    $remote_fs $syslog                                                                                                                                                                                                         `
`# Required-Stop:     $remote_fs $syslog                                                                                                                                                                                                         `
`# Default-Start:     2 3 4 5                                                                                                                                                                                                                    `
`# Default-Stop:      0 1 6                                                                                                                                                                                                                      `
`# Short-Description: Start grafana at boot time                                                                                                                                                                                                 `
`# Description: Grafana - feature rich metrics dashboard and graph editor                                                                                                                                                                        `
`### END INIT INFO                                                                                                                                                                                                                               `
`                                                                                                                                                                                                                                                `
`NAME=grafana                                                                                                                                                                                                                                    `
`DESC="Grafana Server"                                                                                                                                                                                                                           `
`DEFAULT=/etc/default/$NAME                                                                                                                                                                                                                      `
`                                                                                                                                                                                                                                                `
`GRAFANA_USER=fido                                                                                                                                                                                                                               `
`GRAFANA_GROUP=users                                                                                                                                                                                                                             `
`GRAFANA_HOME=/usr/share/grafana                                                                                                                                                                                                                 `
`CONF_DIR=/etc/grafana                                                                                                                                                                                                                           `
`WORK_DIR=$GRAFANA_HOME                                                                                                                                                                                                                          `
`DATA_DIR=/var/lib/grafana                                                                                                                                                                                                                       `
`LOG_DIR=/var/log/grafana                                                                                                                                                                                                                        `
`CONF_FILE=$CONF_DIR/grafana.ini                                                                                                                                                                                                                 `
`MAX_OPEN_FILES=10000                                                                                                                                                                                                                            `
`PID_FILE=/var/run/$NAME.pid                                                                                                                                                                                                                     `
`DAEMON=/usr/sbin/$NAME                                                                                                                                                                                                                          `
`umask 0027                                                                                                                                                                                                                                      `
`if [ `id -u` -ne 0 ]; then                                                                                                                                                                                                                      `
`	echo "You need root privileges to run this script"                                                                                                                                                                                             `
`	exit 1                                                                                                                                                                                                                                         `
`fi                                                                                                                                                                                                                                              `
`                                                                                                                                                                                                                                                `
`. /lib/lsb/init-functions                                                                                                                                                                                                                       `
`                                                                                                                                                                                                                                                `
`if [ -r /etc/default/rcS ]; then                                                                                                                                                                                                                `
`	. /etc/default/rcS                                                                                                                                                                                                                             `
`fi                                                                                                                                                                                                                                              `
`                                                                                                                                                                                                                                                `
`# overwrite settings from default file                                                                                                                                                                                                          `
`if [ -f "$DEFAULT" ]; then                                                                                                                                                                                                                      `
`	. "$DEFAULT"                                                                                                                                                                                                                                   `
`fi                                                                                                                                                                                                                                              `
`                                                                                                                                                                                                                                                `
`DAEMON_OPTS="--pidfile=${PID_FILE} --config=${CONF_FILE} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.logs=${LOG_DIR}"                                                                                                                  `
`                                                                                                                                                                                                                                                `
`# Check DAEMON exists                                                                                                                                                                                                                           `
`test -x $DAEMON || exit 0                                                                                                                                                                                                                       `
`                                                                                                                                                                                                                                                `
`case "$1" in                                                                                                                                                                                                                                    `
`  start)                                                                                                                                                                                                                                        `
`                                                                                                                                                                                                                                                `
`	log_daemon_msg "Starting $DESC"                                                                                                                                                                                                                `
`                                                                                                                                                                                                                                                `
`	pid=`pidofproc -p $PID_FILE grafana`                                                                                                                                                                                                           `
`	if [ -n "$pid" ] ; then                                                                                                                                                                                                                        `
`		log_begin_msg "Already running."                                                                                                                                                                                                              `
`		log_end_msg 0                                                                                                                                                                                                                                 `
`		exit 0                                                                                                                                                                                                                                        `
`	fi                                                                                                                                                                                                                                             `
`                                                                                                                                                                                                                                                `
`	# Prepare environment                                                                                                                                                                                                                          `
`	mkdir -p "$LOG_DIR" "$DATA_DIR" && chown "$GRAFANA_USER":"$GRAFANA_GROUP" "$LOG_DIR" "$DATA_DIR"                                                                                                                                               `
`	touch "$PID_FILE" && chown "$GRAFANA_USER":"$GRAFANA_GROUP" "$PID_FILE"                                                                                                                                                                        `
`                                                                                                                                                                                                                                                `
`  if [ -n "$MAX_OPEN_FILES" ]; then                                                                                                                                                                                                             `
`		ulimit -n $MAX_OPEN_FILES                                                                                                                                                                                                                     `
`	fi                                                                                                                                                                                                                                             `
`                                                                                                                                                                                                                                                `
`	# Start Daemon                                                                                                                                                                                                                                 `
`	start-stop-daemon --start -b --chdir "$WORK_DIR" --user "$GRAFANA_USER" -c "$GRAFANA_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS                                                                                                `
`	return=$?                                                                                                                                                                                                                                      `
`	if [ $return -eq 0 ]                                                                                                                                                                                                                           `
`	then                                                                                                                                                                                                                                           `
`	  sleep 1                                                                                                                                                                                                                                      `
`                                                                                                                                                                                                                                                `
`    # check if pid file has been written two                                                                                                                                                                                                    `
`	  if ! [[ -s $PID_FILE ]]; then                                                                                                                                                                                                                `
`	    log_end_msg 1                                                                                                                                                                                                                              `
`	    exit 1                                                                                                                                                                                                                                     `
`	  fi                                                                                                                                                                                                                                           `
`                                                                                                                                                                                                                                                `
`		i=0                                                                                                                                                                                                                                           `
`		timeout=10                                                                                                                                                                                                                                    `
`		# Wait for the process to be properly started before exiting                                                                                                                                                                                  `
`		until { cat "$PID_FILE" | xargs kill -0; } >/dev/null 2>&1                                                                                                                                                                                    `
`		do                                                                                                                                                                                                                                            `
`			sleep 1                                                                                                                                                                                                                                      `
`			i=$(($i + 1))                                                                                                                                                                                                                                `
`      if [ $i -gt $timeout ]; then                                                                                                                                                                                                              `
`			  log_end_msg 1                                                                                                                                                                                                                              `
`			  exit 1                                                                                                                                                                                                                                     `
`			fi                                                                                                                                                                                                                                           `
`		done                                                                                                                                                                                                                                          `
`  fi                                                                                                                                                                                                                                            `
`  log_end_msg $return                                                                                                                                                                                                                           `
`	;;                                                                                                                                                                                                                                             `
`  stop)                                                                                                                                                                                                                                         `
`	log_daemon_msg "Stopping $DESC"                                                                                                                                                                                                                `
`                                                                                                                                                                                                                                                `
`	if [ -f "$PID_FILE" ]; then                                                                                                                                                                                                                    `
`		start-stop-daemon --stop --pidfile "$PID_FILE" \                                                                                                                                                                                              `
`			--user "$GRAFANA_USER" \                                                                                                                                                                                                                     `
`			--retry=TERM/20/KILL/5 >/dev/null                                                                                                                                                                                                            `
`		if [ $? -eq 1 ]; then                                                                                                                                                                                                                         `
`			log_progress_msg "$DESC is not running but pid file exists, cleaning up"                                                                                                                                                                     `
`		elif [ $? -eq 3 ]; then                                                                                                                                                                                                                       `
`			PID="`cat $PID_FILE`"                                                                                                                                                                                                                        `
`			log_failure_msg "Failed to stop $DESC (pid $PID)"                                                                                                                                                                                            `
`			exit 1                                                                                                                                                                                                                                       `
`		fi                                                                                                                                                                                                                                            `
`		rm -f "$PID_FILE"                                                                                                                                                                                                                             `
`	else                                                                                                                                                                                                                                           `
`		log_progress_msg "(not running)"                                                                                                                                                                                                              `
`	fi                                                                                                                                                                                                                                             `
`	log_end_msg 0                                                                                                                                                                                                                                  `
`	;;                                                                                                                                                                                                                                             `
`  status)                                                                                                                                                                                                                                       `
`	status_of_proc -p $PID_FILE grafana grafana && exit 0 || exit $?                                                                                                                                                                               `
`    ;;                                                                                                                                                                                                                                          `
`  restart|force-reload)                                                                                                                                                                                                                         `
`	if [ -f "$PID_FILE" ]; then                                                                                                                                                                                                                    `
`		$0 stop                                                                                                                                                                                                                                       `
`		sleep 1                                                                                                                                                                                                                                       `
`	fi                                                                                                                                                                                                                                             `
`	$0 start                                                                                                                                                                                                                                       `
`	;;                                                                                                                                                                                                                                             `
`  *)                                                                                                                                                                                                                                            `
`	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"                                                                                                                                                                           `
`	exit 3                                                                                                                                                                                                                                         `
`	;;                                                                                                                                                                                                                                             `
`esac                                                                                                                                                                                                                                            `

2. I installed Grafana using the "Puppy Package Manager".
3. Nope
4. Same problem

By the way, I have found a workaround, I added: 
`set GRAFANA_USER=fido                                                                                                                                                                                                                         
 `
`set GRAFANA_GROUP=users                                                                                                                                                                                                                        `
And it worked.

**Comment by xlson** [comment]
Glad to hear it worked out.

Can you check if you have a file called `/etc/default/grafana`? If so, that should be used for overrides.
