### ISSUE TITLE
[docker] image for non-root

### ISSUE THREAD

**Issue by asiekkowa** [grafana/grafana#15653]
Secure and reusable Docker images should not expect to be run as root (due to for example security reasons).

P.S. Current, official docker images don't work in OpenShift.

**Comment by xlson** [comment]
The Grafana docker image does not expect to be run as root since version 5.1. What version are you running?

It would be helpful to get a bit more detail on what you are having problems with when running Grafana on OpenShift so that we can figure out if there is anything we can do.
