### ISSUE TITLE
SingleStat and Graph panels using DataMetric unit "bits" now displayed as Gd,Md,Kd,d

### ISSUE THREAD

**Issue by MegaMaxs11** [grafana/grafana#15664]
### What Grafana version are you using?
Grafana v6.0.0 (34a9a62)
### What datasource are you using?
influx, mysql
### What OS are you running grafana on?
Red Hat Enterprise Linux Server 7.6 
### What did you do?
Updated Grafana to v6.0.0 Stable
### What was the expected result?
I was expecting no changes
### What happened instead?
All my SingleStat and Graph panels are set to DataMetric unit 'bits' (as they should) but the values are now displayed as d,Kd,Md,Gd instead of b,Kb,Mb,Gb

**Comment by peterholmberg** [comment]
I can reproduce for bits (d)

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/valueFormats/categories.ts#L128
