### ISSUE TITLE
Editor downgraded to viewer should not be able to Update JSON on a panel.

### ISSUE THREAD

**Issue by Payden-Pringle** [grafana/grafana#15667]
Found this old issue while googling for a solution: #3874 

### What Grafana version are you using?
Version 5.4.3 (commit # 6539180 ) & 5.2.4 have been tested.

Tested in Version 6.0.0 (commit: 34a9a62). Still an issue.

### What datasource are you using?
MySQL

### What OS are you running grafana on?
Linux Kernel 3.10.0-957.1.3.el7.x86_64

### What did you do?
0. Start with Fresh Grafana Installation.
1. Create Dashboard.
2. Create Test User.
3. Giver Test User Viewer permissions on Dashboard.
4. Create Panel on Dashboard using MySQL datasource.
5. View Dashboard as Test User.
6. Open the Test Panel's Panel JSON.
7. Edit the SQL Query.
8. Click Update.

### What was the expected result?
Update on the Panel JSON should not be there and should not apply changes even if shown.

### What happened instead?
Update on the Panel JSON window was visible and updated the JSON. This allows running SQL Queries as a User with Viewer permissions.  For example, say if I would normally see my own statistics and wished to see my Supervisor's while knowing his ID in the database.

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

The attached .TXT file is a .HAR that covers the following actions:
1. Opening the Dashboard as the Test User.
2. Opening the Test Panel JSON as the Test User.
3. Updating the JSON by clicking Update after editing it, as the Test User.

It was created on version 5.4.3 in an Incognito Chrome Window. I verified that commit 14952de 's change exists within 5.2.4 and 5.4.3 in `json_editor_ctrl.ts`.

`viewers_can_edit` is set to `false` during my testing.
 
[grafana.domain.com.txt](https://github.com/grafana/grafana/files/2906709/grafana.domain.com.txt)

**Comment by xlson** [comment]
What browser are you using? I've been trying to reproduce the issue on my local machine but I can't get the update button to show (I'm on Chromium).

As a side note, even when the update button is not there it is possible for a viewer to query the database as long as they can figure out Grafana's API. The viewer role limits the users ability to edit dashboards in Grafana but not querying.

**Comment by Payden-Pringle** [comment]
> What browser are you using? I've been trying to reproduce the issue on my local machine but I can't get the update button to show (I'm on Chromium).

I used Chrome Version 72 in Incognito mode for all testing.

After reading this question, I tried it in Microsoft Edge InPrivate browsing and can still see the Panel JSON Update button.

I checked `/admin/settings` to make sure `viewers_can_edit` is set to `false`, and it is.

Entry for Test User in Grafana DB:
```
id | version | login | email | name | password | salt | rands | company | org_id | is_admin | email_verified | theme | created | updated | help_flags1 | last_seen_at
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
23 | 0 | dummy@domain.com | dummy@domain.com | dummy |   | <salt> | <rands> |   | 2 | 0 | 0 |   | 2/21/2019 20:08 | 2/25/2019 14:50 | 0 | 2/27/2019 16:49
```

Entry to org_user for above user:
```
id | org_id | user_id | role | created | updated
37 | 2 | 23 | Editor |2019-02-21 20:09:53 | 2019-02-21 20:09:53
```

## And I see the issue now. 

After switching the user's Role to Viewer for the Organization, the Update button on the Panel JSON window is gone. 

This is odd to me because I removed all permissions from the Test Dashboard except for Admin (since you can't) and manually added the individual test user as a Viewer Role.

This is what I currently see on the Test Dashboard:
![image](https://user-images.githubusercontent.com/4104557/53508633-b8f78e80-3a7f-11e9-8f78-e27e40bcac01.png)

Whereas this is what a new Dashboard gets by default:
![image](https://user-images.githubusercontent.com/4104557/53508682-d62c5d00-3a7f-11e9-8acd-1d0c4616b3fb.png)

### I guess I misunderstood removing the Editor Role's entry for a Dashboard as removing an Organization Editor's ability to edit said board?

### That seems counter-intuitive.

> As a side note, even when the update button is not there it is possible for a viewer to query the database as long as they can figure out Grafana's API. The viewer role limits the users ability to edit dashboards in Grafana but not querying.

That's good to know, thanks.

**Comment by xlson** [comment]
No misunderstanding, you are quite right, an Editor that has had his Editor permission removed should not be able to Update the JSON of the Dashboard.
