### ISSUE TITLE
SingleStat value is wrong color

### ISSUE THREAD

**Issue by netdisciple** [grafana/grafana#15662]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What happened instead? red color was displayed for the font color of the value

Please see the image. Is this configuration wrong?
![screen shot 2019-02-26 at 6 45 28 am](https://user-images.githubusercontent.com/163948/53421486-8fad0480-3992-11e9-8ada-f6b35df5b346.png)

**Comment by netdisciple** [comment]
HTH
![screen shot 2019-02-26 at 8 55 18 am](https://user-images.githubusercontent.com/163948/53430990-7a40d600-39a4-11e9-8e56-9d1f08028e7a.png)

**Comment by jschill** [comment]
I tried to reproduce without luck.
![screenshot 2019-02-28 08 18 31](https://user-images.githubusercontent.com/224493/53548312-79897a80-3b31-11e9-924c-ee0aa3c13bbb.png)

@peterholmberg Do you have any ideas whats happening here?

**Comment by netdisciple** [comment]
I purged the image and rebuilt the container and this is not happening anymore, perhaps i had a layerfs that contained something that caused this.
