### ISSUE TITLE
Request Panel : graph as a function of values in tag

### ISSUE THREAD

**Issue by luluprat** [grafana/grafana#1566]
Hello,
we have graph as a function of time for different values of tags.
But i am interested in a graph as a function of different value in a tag.
i have  a tag name frequency where values go from 0 to 512 in integer.
every second i have 512 values.
i would like to have a graph that display every second values as a function of frequency.

Do you think that is possible to work on ?

Thanks

**Comment by torkelo** [comment]
I guess you are using OpenTSDB? I think this type of feature would be best implemented in OpenTSDB

**Comment by luluprat** [comment]
yes i am using opentsdb.
I would like to have all graph in grafana.
is it possible ?

**Comment by torkelo** [comment]
yes, but currently the graphs only work/expect time as x-axis, and I am not sure this works with the OpenTSDB api.
