### ISSUE TITLE
Feature request: Singlestat font sizes

### ISSUE THREAD

**Issue by bengoa** [grafana/grafana#15666]
Hello folks,

Since a while, users like me are dealing with Font sizes config limitations through CSS tweaks using a Text/HTML panel. Despite the title, it is not specifically related to Singlestat panel. Some examples are here[1] and here[2].

Apparently, since Grafana 6 it stopped to work, and I didn't find yet a way to work around it anymore. 

Are you guys planning to provide a more flexible way to set font sizes? I guess would be really nice to allow custom values instead of just allowing to select from a limited number of options.

If not, could you guys suggest a way to work around it?

[1] - https://github.com/grafana/grafana/issues/1875
[2] - https://github.com/grafana/grafana/issues/12227

Tks,
Alberto

Please include this information:
### What Grafana version are you using?
6

### What datasource are you using?
InfluxDB, MySQL.

### What OS are you running grafana on?
Centos 7.

**Comment by torkelo** [comment]
you can set font sizes. And if you want to specify custom html in text panel you can disable the sanitization in the ini file (search config docs for sanitize)

**Comment by bengoa** [comment]
Hello Torkel,

Thanks for your answer. I found out this option yesterday on a thread at the Grafana Community. After disabling the sanitization it's working again.

I still believe that having a proper option to set font sizes is worth, especially considering that to keep this workaround working we need to give up the new security improvements on XSS.

Thanks for your attention in any way.
