### ISSUE TITLE
Explore: Disabling log options doesn't collapse space on Firefox

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/grafana#15673]
Please include this information:
### What Grafana version are you using?
6.0.0
### What datasource are you using?
Loki
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
Browsing Loki logs in Explore mode, I disabled all the log panel options so I could make more room for the application log output.

### What was the expected result?
The columns for timestamp, local time and labels would fully disappear and there would be no whitespace, maximizing application log real estate.
### What happened instead?
The columns for timestamp, local time and labels did not fully collapse, leaving leftover whitespace:

![image](https://user-images.githubusercontent.com/17552371/53447536-f0602f80-39da-11e9-83d1-93c9ffc728bd.png)

 (Ignore the extra timestamps in the app logs, I submitted a Loki [enhancement](https://github.com/grafana/loki/issues/358) to support containerd's log format)

**Comment by davkal** [comment]
Do you have a solid repro for the issue? I cant reproduce.

What I have seen occasionally was some rows not being removed on reconciliation, usually accompanied by react key errors in the console. Those rows were then left over, and if they had other column counts than the newly added rows, that threw off the table rendering.

**Comment by steven-sheehy** [comment]
@davkal I just noticed it's only reproducible on Firefox, Chrome seems to work fine. MacOS if that makes a difference.

Also, the PR also addresses the labels never truncating with ellipsis (both in rows and in panel options), which is reproducible in both browsers with a long label like `__filename__: /var/log/pods/3de8bd9a-372c-11e9-a076-00505691cd09/edge-worker/0.logedge-worker-786cb94cf-zccnn`
