### ISSUE TITLE
Add support for teams or orgs in Azure AD OAuth

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#15670]
Teams and orgs (`team_ids` and `allowed_organizations`) don't work with Azure AD (confirmed by @DanCech ). We'd likely need to make a specific OAuth module to get that going.

Docs: http://docs.grafana.org/auth/generic-oauth/#set-up-oauth2-with-azure-active-directory

**Comment by nitinjain999** [comment]
What roles and permission should be assigned to Azure Service Principal ?

**Comment by tfanhaUK** [comment]
same here, any feedback about this ? is AzureAD will be able to map to Teams and Orgs, or that will be only via old LDAP and on Grafana Enterprise only ?!

tks

**Comment by 486** [comment]
@adeverteuil We are managing permissions through groups in the Azure Active Directory. Is this feature allowing to restrict access to certain groups? We are a paying Grafana Cloud customer and I'd like if this issue fits our feature request.

**Comment by lwiedenhoeft** [comment]
Any update about this? Pure authentication via generic OAuth works create, but we cannot sync Grafana teams and orgs with Azure AD Groups.

**Comment by Jguer** [comment]
Closing this issue as implemented

`allowed_domains` and `allowed_groups` allow this https://grafana.com/docs/grafana/next/setup-grafana/configure-security/configure-authentication/azuread/#configure-allowed-groups

team mapping is supported through teamsync https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#team-sync-enterprise-only

org mapping has been discussed in https://github.com/grafana/grafana/issues/23473. From what I've seen there is a still ongoing discussion how to best support this usecase
