### ISSUE TITLE
root_url path is ignored in Grafana 6.0 datasource page 'Back' button

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#15679]
Please include this information:
### What Grafana version are you using?
6.0
### What datasource are you using?
InfluxDB, true for other data sources also. 
### What OS are you running grafana on?
darwin
### What did you do?
upgraded to Grafana 6.0. On any datasource page, clicked on Back button to see the list of configured datasources.
### What was the expected result?
It should come to datasource list page.
### What happened instead?
It did not consider root_url path and took the page to the root domain.

**Comment by dprokop** [comment]
@digrich Thank you for your report.

I've quickly tested it and it seems I cannot reproduce described issue. Can you provide us with more information about your OS and browser?

**Comment by marefr** [comment]
@dprokop if you use a reverse proxy like nginx or apache with grafana under a sub path, e.g. http://site.com/grafana/

**Comment by dprokop** [comment]
@marefr Thanks! I have actually set up reverse proxy, but the problem is I have used browser's Back button, instead of ours, thus I couldn't reproduce. Now I can :)
