### ISSUE TITLE
Drilldown links not shown on repeating panels

### ISSUE THREAD

**Issue by johnhtodd** [grafana/grafana#15675]
Please include this information:
### What Grafana version are you using?
Grafana v5.4.0 (69c5191)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
CentOS

### What did you do?
Created a set of repeating graphs with drilldown links in the panels

### What was the expected result?
Each panel should have had a separate drilldown link 

### What happened instead?
Only the first panel shows a drilldown link icon.

### If related to metric query / data viz:
n/a

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
n/a

Long form:
Screenshot attached.  

The first panel drilldown link works perfectly. I would expect that when I create a drilldown/link for a panel, that each subsequent repeating panel below the first would contain the same link model, but with changed variables based on the repeating data.  However, no drilldown link appears at all on the repeated panels.

![screen shot 2019-02-26 at 1 24 28 pm](https://user-images.githubusercontent.com/9668137/53447715-a5d6b700-39ca-11e9-8708-2baf247ac8bd.png)

**Comment by marefr** [comment]
This sort of works for me. However seems that I have to update variable selection of the variable being repeated for the panel to be refreshed with drill down links.

**Comment by johnhtodd** [comment]
> This sort of works for me. However seems that I have to update variable selection of the variable being repeated for the panel to be refreshed with drill down links.

This isn't my case, so I can't even kludge it to work - the variable being repeated is hidden, and dynamically generated from a query.   ("Show the top 10 users of foo resources with specifications X, Y, and Z, and graph the quantity of foo that they use")

**Comment by torkelo** [comment]
You need to reload or retrigger repeat after making change to the source panel (first panel).

Since your variable was hidden and can’t be changed you need to reload dashboard for changes to source panel to be propagated to repeated clones
