### ISSUE TITLE
[Feature Request] Add Prefix / Postfix Text to Clock panel plugin

### ISSUE THREAD

**Issue by thrashsoul** [grafana/grafana#15672]
I am using the Clock panel to display clocks for a few different time zones on my Grafana dashboards. It would be nice if there is a prefix / post fix text similar to the single stat panel so that I can add a text to the panel to show the timezone or location. 

This would eliminate having to make a separate text panel for a label and keep my panels better organized.

**Comment by xlson** [comment]
Could you please open an issue [here](https://github.com/grafana/clock-panel/issues) instead.
