### ISSUE TITLE
Template Variable "Name" autocomplete dropdown not hiding

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#15674]
### What Grafana version are you using?
Grafana v6.0.0 ([34a9a62](https://github.com/grafana/grafana/commit/34a9a621b6b6f14d9ad15690d0a38047905b5423))

### What datasource are you using?
Any

### What OS are you running grafana on?
Windows

### What did you do?
Added a template variable in Edge browser

### What was the expected result?
Expected it would work as normal

### What happened instead?
Instead the autocomplete dropdown for the template variable name refuses to go away. Clicking to focus other textboxes on the page does not hide the dropdown for Name. This blocks the user's view of the other text fields on that page. Even worse, the dropdown will often persist after backing out to the template variable list.

The way autocomplete in Edge works for textboxes in Grafana has always been a little iffy, but this is a regression. 

This is not an issue in Chrome.

**Comment by marefr** [comment]
Tried to reproduce using Microsoft Edge 42.17134.1.0 and this [dashboard](https://play.grafana.org/d/000000015/elasticsearch-templated?orgId=1&var-source=All&var-host=All
) but it works as expected for me. Will close this for now, but consider reopen if provide more information like screenshots/animations showing there's a problem.
