### ISSUE TITLE
Min time interval not displayed in V6.0.0

### ISSUE THREAD

**Issue by Yukinoshita-Yukino** [grafana/grafana#15682]
Please include this information:
### What Grafana version are you using?
Grafana v6.0.0 (34a9a62)
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
Centos
### What did you do?
Just config some panel with `min time interval` and the change to any other tab then change back, the panel is still showing data with pre configured value but the `min time interval` box will be empty. 
### What was the expected result?
Min time interval displayed correctly.

<img width="1675" alt="wx20190227-143443 2x" src="https://user-images.githubusercontent.com/3638888/53470531-d8e97b00-3a9c-11e9-8c99-89e6a38f8b83.png">

**Comment by torkelo** [comment]
thanks for reporting this!  will fix!
