### ISSUE TITLE
centos6 repo

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#15687]
grafana/signature                                                                                              |  836 B     00:00
Retrieving key from https://packagecloud.io/gpg.key
Importing GPG key 0xEBFF1218:
 Userid: "packagecloud ops (production key) <ops@packagecloud.io>"
 From  : https://packagecloud.io/gpg.key
Is this ok [y/N]: y
Retrieving key from https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
grafana/signature                                                                                              | 1.0 kB     00:02 ...
https://packagecloud.io/grafana/stable/el/6/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for grafana
Trying other mirror.

**Comment by Yukinoshita-Yukino** [comment]
They have stopped using packagecloud. 
If you visit https://packagecloud.io/grafana/stable you should see the information.

**Comment by xlson** [comment]
@f1-outsourcing as was mentioned, we have moved away from packagecloud. Check the [docs](http://docs.grafana.org/installation/rpm/#install-via-yum-repository) for info on our new repo.
