### ISSUE TITLE
timeInterval setting missing from UI for Prometheus datasource

### ISSUE THREAD

**Issue by diamondo25** [grafana/grafana#15688]
### What Grafana version are you using?
6.0.0 (34a9a62)
### What datasource are you using?
Prometheus, configured through UI
### What OS are you running grafana on?
Debian 9.5
### What did you do?
Due to old prometheus datasources having the 'timeInterval' unset/default to 0, it glitches out the UI:
`Templating init failed Invalid interval string, expecting a number followed by one of "Mwdhmsy"`.

So tried to set the 'timeInterval' setting (like you would through the provisioning file) on the datasource configuration UI.

### What was the expected result?
That there is a field for this like there is for Postgres or other datasources
### What happened instead?
Its not there, cannot change the value.

**Comment by diamondo25** [comment]
Also, the error got fixed after i changed the scrape interval from '10' to '10s' and saved it, I think.

**Comment by xlson** [comment]
Not exactly sure I follow, did you upgrade to 6.0 from an older version of Grafana and ended up with a Scrape Interval of 0? And, if so, what version did you upgrade from?

I think Scrape Interval fills the same functionality for prometheus as time interval does for the other data sources, but I could be wrong.

**Comment by diamondo25** [comment]
I updated from 5.2 to 5.4, then from 5.4 to 6.0. That update, as far as i could tell, broke the "node exporter" template, using a prometheus backend, with the error that the interval was incorrect. I could not change the interval anywhere of the datasource.

Op 27 feb. 2019 15:42 schreef Leonard Gram <notifications@github.com>:

Not exactly sure I follow, did you upgrade to 6.0 from an older version of Grafana and ended up with a Scrape Interval of 0? And, if so, what version did you upgrade from?

I think Scrape Interval fills the same functionality for prometheus as time interval does for the other data sources, but I could be wrong.

**Comment by xlson** [comment]
I thought you said the problem was fixed when you changed the "Scrape interval" to 10s on the Prometheus datasource config page?

**Comment by xlson** [comment]
Is that a Dashboard template that you are using, if so, can you link to it?

**Comment by diamondo25** [comment]
Seems to have correctly defaulted the value, but i cannot find where these settings are saved.

Op 27 feb. 2019 16:01 schreef Leonard Gram <notifications@github.com>:

I thought you said the problem was fixed when you changed the "Scrape interval" to 10s on the Prometheus datasource config page?

**Comment by diamondo25** [comment]
https://grafana.com/dashboards/405

Op 27 feb. 2019 16:01 schreef Leonard Gram <notifications@github.com>:

Is that a Dashboard template that you are using, if so, can you link to it?

**Comment by xlson** [comment]
Was your issue fixed when you set the scrape interval on the datasource configuration page?

**Comment by diamondo25** [comment]
I think so, yes. That was set on '10' where a different  datasource had the 's' appended to it, so i made it '10s'

**Comment by xlson** [comment]
Thank you. I will close this issue as I think we have identified the problem but open a new one regarding input validation for that field (so that you get an error if it says 10, instead of 10s).

**Comment by diamondo25** [comment]
Also, thanks you guys for fixing the z-indexing on the dropdown menus, it was driving me mad...
