### ISSUE TITLE
Some bugs and potential improvements with heatmap panel

### ISSUE THREAD

**Issue by Yukinoshita-Yukino** [grafana/grafana#15683]
Please include this information:
### What Grafana version are you using?
Grafana v6.0.0 (34a9a62)
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
Centos
### What did you do?
Setup a heatmap to display CPU load for multiple hosts over time.
Here are my configurations.
<img width="960" alt="wx20190227-144237 2x" src="https://user-images.githubusercontent.com/3638888/53470891-01be4000-3a9e-11e9-98c1-e83bbc33508a.png">
<img width="1288" alt="wx20190227-150027 2x" src="https://user-images.githubusercontent.com/3638888/53471682-74c8b600-3aa0-11e9-8aac-1b89c230c11b.png">
### What was the expected result?
I was expecting something like this. 
This is taken from Kibana (sorry for the bad writing, I'm writing with a touch pad)
<img width="2321" alt="wx20190227-144650 2x" src="https://user-images.githubusercontent.com/3638888/53471116-a0e33780-3a9e-11e9-8753-05c508477341.png">
<br>
<br>
### 1. The heatmap panel in Grafana is displaying items in wrong order
The configuration used is Top 10 by CPU load, but the panel shows the one with the highest load at the bottom at the graph.
<img width="1739" alt="wx20190227-145107 2x" src="https://user-images.githubusercontent.com/3638888/53471307-236bf700-3a9f-11e9-8ea0-052410bb7b1f.png">
<br>
<br>
### 2. The legend is showing wrong color
Same as #14019 I think.
Pretty clear it's wrong.
<img width="1220" alt="wx20190227-145323 2x" src="https://user-images.githubusercontent.com/3638888/53471411-780f7200-3a9f-11e9-90a1-595e5d4f05bf.png">
<br>
<br>
### 3. The cell in heatmap doesn't show metric in query
It just shows some "count", which is not very useful I think.
<img width="1719" alt="wx20190227-145521 2x" src="https://user-images.githubusercontent.com/3638888/53471513-ce7cb080-3a9f-11e9-9c74-0ad8c0139101.png">
<br>
<br>
### 4. It would be nice to have a "middle" option for bucket bound
The only options are "Upper" and "Lower" for now, which is not very good for time series buckets in my opinion.
<img width="765" alt="wx20190227-145730 2x" src="https://user-images.githubusercontent.com/3638888/53471574-1996c380-3aa0-11e9-96fb-b15d4d784264.png">

**Comment by torkelo** [comment]
@alexanderzobnin can you try to find time to investigate some of these issues?

**Comment by alexanderzobnin** [comment]
Yes, sure.

**Comment by alexanderzobnin** [comment]
@Yukinoshita-Yukino The first 3 is pretty clear for me. But could you explain 
__4. It would be nice to have a "middle" option for bucket bound__ ?
Now if result contains, for instance, bucket bounds [1,2,3], it may mean:
1. Lower: bound is a lower bound, so buckets are [`1-2`, `2-3`, `3-+inf`]
2. Upper: bound is an upper bound, so buckets are [`-inf-1`, `1-2`, `2-3`]

So I'm not sure how `middle` should work.

**Comment by Yukinoshita-Yukino** [comment]
@alexanderzobnin When you use time series buckets and group by host name, each line of the heatmap is actually for one specific server. 
There's no such thing as "upper bound" or "lower bound" for them.
For example the first row of the heatmap is just the data for "server 10", the second row is just for "server 9" etc.
So the bucket bound option only affects where the bucket name is displayed. 
It's either on the top of the row or the bottom of the row.
Maybe just cancel the bucket bound option for time series buckets and just place the bucket name center would be a better idea?
<img width="308" alt="wx20190301-095350 2x" src="https://user-images.githubusercontent.com/3638888/53611052-1880a600-3c08-11e9-8249-1430a5be109a.png">

**Comment by kcgthb** [comment]
I strongly support that request: having a "non-bucket" approach (and thus a `middle` centered layout option) for single-value buckets would be awesome!

**Comment by alexanderzobnin** [comment]
Ok, understand.

**Comment by alexanderzobnin** [comment]
Some updates and topics for discuss:
**1. The heatmap panel in Grafana is displaying items in wrong order**
Panel doesn't do any data sorting for Elasticsearch, because it assumes data is already sorted on the ES side. It should be possible to set asc/desc sort order in ES query, but I didn't find this option in grafana. Any thoughts, @torkelo ? 

**2. The legend is showing wrong color**
Fixed

**3. The cell in heatmap doesn't show metric in query**
Heatmap panel works with timeseries data, so data coming from datasource is just a set of series with labels. There's no additional information about 'metric' or whatever. In this case it's set of series `['server 1', 'server 2', ...]`. It's might be possible to add alias for `count` field in tooltip I think, but you have to set it manually, it's not possible to fill it from returned data.
Any thoughts, @torkelo ? 

**4. It would be nice to have a "middle" option for bucket bound**
Added. @torkelo what do you think, is `middle` option name clear enough?

![Screenshot from 2019-03-11 13-05-13](https://user-images.githubusercontent.com/4932851/54115793-52b72800-43fe-11e9-98d8-f75985e7c252.png)

**Comment by Yukinoshita-Yukino** [comment]
@alexanderzobnin 
### 1. The heatmap panel in Grafana is displaying items in wrong order
If you check the html these server are actually in the correct order (and in query inspector as well).
So I think ES has already sorted them correctly.
<img width="612" alt="WX20190311-182525@2x" src="https://user-images.githubusercontent.com/3638888/54117211-439a9f00-442b-11e9-95de-5ca470205b3d.png">
<img width="505" alt="WX20190311-183254@2x" src="https://user-images.githubusercontent.com/3638888/54117586-1c909d00-442c-11e9-9839-43561e8a95e3.png">

But the heatmap panel are just showing them in the wrong order.
I don't know frontend much so I can't dig deeper but I guess the problem is caused somewhere in heatmap panel.
<img width="606" alt="WX20190311-182637@2x" src="https://user-images.githubusercontent.com/3638888/54117283-557c4200-442b-11e9-9de3-173370d90643.png">

**Comment by alexanderzobnin** [comment]
@Yukinoshita-Yukino It's by design - first series at the bottom, last - at the top. I didn't take into account this kind of data when implemented heatmap, because usually, Y labels are numbers represented bucket bounds. I will investigate this problem and will try to find a way how to solve it. I have to keep in mind that other data sources may return data in different order.

**Comment by alexanderzobnin** [comment]
I've found that Kibana always uses "first at the top" buckets order. It looks strange for numeric Y axis - values placed in reverse order:

![Screenshot from 2019-03-11 17-28-50](https://user-images.githubusercontent.com/4932851/54131742-0383ee00-4424-11e9-8cdb-7c92a8be2de2.png)

So maybe an option for reverse sorting should help to take control over it:

![Screenshot from 2019-03-11 17-37-39](https://user-images.githubusercontent.com/4932851/54132041-93299c80-4424-11e9-8c65-6c9213a2b234.png)

**Comment by Yukinoshita-Yukino** [comment]
I am on Kibana 6.3.1 and in this version they actually has an option for order, which can be Descending or Ascending.
Not sure if this can give you some idea about this :)
![微信截图_20190311233730](https://user-images.githubusercontent.com/3638888/54136459-d00e8700-4456-11e9-9d50-45a384fe9ff6.png)
![微信截图_20190311233758](https://user-images.githubusercontent.com/3638888/54136460-d13fb400-4456-11e9-9cf1-8e10e19daefa.png)

**Comment by alexanderzobnin** [comment]
@Yukinoshita-Yukino it works a little bit different. This is like "sort series by given field and get first 25 sereis". So it's pre sort. Grafana has this option (Top/Bottom) as well. But in your case you need a post-sort which can be achieved only with additional option.

![Screenshot from 2019-03-11 19-33-49](https://user-images.githubusercontent.com/4932851/54140519-da1f8e00-4434-11e9-8543-40292d0f5586.png)
