### ISSUE TITLE
Link on each column to navigate to its respective logs in bar graph

### ISSUE THREAD

**Issue by sridattasp** [grafana/grafana#15699]
Grafana: 5.4.2
Datasource: Influxdb
Grafana running on: Windows

I have a graph panel which renders data from influx db and show in graph panel with bar-graphs. 

Requirement or expected behavior:
1. Now the requirement is to click on each column of bar graph to navigate to its respective logs in influxdb. 
2. In table view I see the option in  'column style'. Something similar to that we are expecting in graph panel where each column will be provided a link either to drill down or open related data in new tab.

In below image clicking on hyperlink opens an html(screenshot is only for reference). We are expecting similar action from each 'column' of bar-graph in grafana

![image](https://user-images.githubusercontent.com/47819830/53546623-d8132080-3b52-11e9-8cdd-5aa5b1f99463.png)

**Comment by xlson** [comment]
That's an interesting idea. I will link your issue to the Drilldown link redesign #15130.

**Comment by torkelo** [comment]
we will partly solve this via extending the drildown link feature,https://github.com/grafana/grafana/issues/1232
