### ISSUE TITLE
Support View Changes in the Panels

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#15693]
One feature I'm missing in the Grafana for creating great dashboards is to be able to have different "views" in the different panel.     Of course I can create different  panels or use different dashboard for drilldown but it is not as convenient. 

Here is some examples where it can be useful 

- Imagine I want to see the Temperature in Celsius of Fahrenheit , it would be great to have the way to switch the view on the panel with single link.

- More operational use case - often looking at the CPU usage or disk IO utilization I like to see aggregated data but if it is the problem I would love to be able to switch to between "Aggregated" and "Detailed" views in the single view. 

From user experience standpoint I'd see it as 2 different panel configurations which are configured separately but use the same "space" and user can switch between them.

**Comment by torkelo** [comment]
interesting idea, sounds a bit similar to this: https://github.com/grafana/grafana/issues/13261  (not well described issue). Thought we had an old feature request for something similar but could not find it

**Comment by PeterZaitsev** [comment]
Yes.  It is similar. The difference though it would require to have full width even if I only use one panel. 

This however brings another idea.  We could have panel repeat with different variable but instead of populating different panels  provide such variable value as "tab" for easy single click   drilldown.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
