### ISSUE TITLE
refresh problem in playlists

### ISSUE THREAD

**Issue by scaarup** [grafana/grafana#15691]
Please include this information:
### What Grafana version are you using?
6.0.0
### What datasource are you using?
Elasticsearch, Zabbix, MySQL
### What OS are you running grafana on?
CentOS 7
### What did you do?
Upgraded from 5.4
### What was the expected result?
The playlists would work
### What happened instead?
When starting a playlist, in any mode, the first dashboard which have autorefresh set, will set this on the rest of the dashboards in the playlist. It seems like the get-parameter "refresh=Xs" is inherited. I discovered this because one of my dashboards have 0.5s refresh set, and since this is then set on my other dashboards, my screens are killed/unable to handle 0.5s.

**Comment by torkelo** [comment]
thanks for reporting this! We will investigate and fix
