### ISSUE TITLE
[Feature Request] Support mixed type plugin for backend

### ISSUE THREAD

**Issue by Gauravshah** [grafana/grafana#15696]
Trying to port https://github.com/GoshPosh/grafana-meta-queries to backend so that alerting is supported.

Mixed plugins behave differently as in they require access to all queries in the dashboard and respective datasources.

Mixed data source gets all the queries & datasource of a given dashboard:
https://github.com/grafana/grafana/commit/b30dfcf28a92d770e02c007dc67b309acb287cef
and is used like : https://github.com/GoshPosh/grafana-meta-queries/blob/master/src/datasource.js#L43

But the same thing is not achievable on backend plugins.
Backend plugins get call to 
```
func (t *DruidDatasource) Query(ctx context.Context, tsdbReq *datasource.DatasourceRequest) (*datasource.DatasourceResponse, error) {
```

which has access to current query only. Tried digging through the code 
https://github.com/grafana/grafana/blob/master/pkg/plugins/datasource/wrapper/datasource_plugin_wrapper.go#L61
sends only the current query and datasource

Digging a little further
the single query is saved within the alert table of grafana database and hence has no information to the dashboard.

Unsure how to proceed

Included information:
### What Grafana version are you using?
grafana 5 & 6
### What datasource are you using?
https://github.com/GoshPosh/grafana-meta-queries
with druid
### What OS are you running grafana on?
mac & linux
 
relates to  https://github.com/grafana/grafana/issues/6841

**Comment by Gauravshah** [comment]
if there is a planned direction we can try creating contributing to a PR. Looking at current code, from our understanding, it requires considerable changes.  
I am not sure if we should make dashboardCache available to the plugin and also unsure if we should store entire dashboard within the alert.
The other issues is getting all the dataSources and issue queries to them from the mixed plugin

**Comment by bergquist** [comment]
I'm not sure this is something we want to support in the backend plugins. I might have to think about this a little bit more...

**Comment by Gauravshah** [comment]
I can share more details about the use case.
Meta-queries-plugin has been super helpful in dealing computations not only with single datasource but across multiple.  One thing that is missing from our existing system is to be able to support alerts on computed metrics for eg when shares per active user goes down is an alert for business health.
Also if the data is across multiple dashboards, then things like if our spends increased by 50% from previous week did our orders increase in a similar fashion.

**Comment by Gauravshah** [comment]
@bergquist or would it make more sense to move this plugin inside grafana source. I am aware that we are trying to move plugins away into its own repo but this one being a special case.

**Comment by Gauravshah** [comment]
relates to https://github.com/grafana/grafana/issues/6593

**Comment by torkelo** [comment]
This would be quite a big task to re-engineer backend query executions & batching, so do not expect this any time soon :)

**Comment by Gauravshah** [comment]
Wouldn't it be simpler if we send across all queries to the plugin and let it decide how to deal with it ? will send in a PR soon, we have some hack working, With some guidance it should be cleanable.

**Comment by Gauravshah** [comment]
@bergquist as https://github.com/grafana/grafana/issues/15696 is done. Are there any thoughts on how this can be supported ?

**Comment by Gauravshah** [comment]
@bergquist Do you have any direction that can help metaqueries work as backend ?

**Comment by bergquist** [comment]
https://github.com/grafana/gel-app but it's not very active at the moment.

**Comment by Gauravshah** [comment]
@bergquist since the gel-app is moved into grafana, this seems no longer an option.
I couldn't find the reason on PR as to why it was moved into grafana in the first place. Keeping it outside would enable others to develop on it. The whole idea of grafana plugins.
Transformations are helpful but don't have everything that we want. Not sure how to move forward at this point

**Comment by Gauravshah** [comment]
as per slack conversation, we will try extending `expressions` . It seems it is no longer an option to build it as an external plugin.
