### ISSUE TITLE
Documentation for implementing required explore ui methods in custom datasource

### ISSUE THREAD

**Issue by RestfulBlue** [grafana/grafana#15697]
Currently, looks like documentation about how to implement explore ui staff in custom datasource is missed :(

**Comment by oddlittlebird** [comment]
Does this topic fix this issue: https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-explore-queries/

**Comment by davkal** [comment]
This is amazing @oddlittlebird It does cover it completely. 

Just letting you know that #25890 did away with the Explore mode. There is now a new property that `PreferredVisualisationType` that inform Explore what to render (graph vs table vs logs vs traces). Perhaps @kaydelaney can help with changing the docs.

**Comment by oddlittlebird** [comment]
Hey @marcusolsson ! ^^
