### ISSUE TITLE
ARM package not compatible with Raspberry Pi Zero

### ISSUE THREAD

**Issue by Majkl578** [grafana/grafana#15695]
### What Grafana version are you using?
6.0.0

### What datasource are you using?
~

### What OS are you running grafana on?
Raspbian buster/sid

### What did you do?
Installed grafana from repo. The service won't launch.

### What was the expected result?
Running Grafana?

### What happened instead?
Crash:
```
Illegal instruction
```

---------

Grafana server doesn't run on Raspberry Pi Zero (W). These devices use `armhf` on ARMv6 processors.

This renders official Grafana packages unusable on these awesome devices.

**Comment by Majkl578** [comment]
Note that you need to build with:
```
GOOS=linux GOARCH=arm GOARM=6
```
in order to build valid binary for Raspberry Pi Zero (along with A, A+, B, B+).
ref: https://gobot.io/documentation/platforms/raspi/
ref: https://github.com/golang/go/wiki/GoArm

**Comment by xlson** [comment]
We have an armv6 [build](https://dl.grafana.com/oss/release/grafana-6.0.0.linux-armv6.tar.gz ) using those settings, but it isn't working, unfortunately. I'm not sure if we need to use a different compiler or if there are other settings that need to be added as well. 

If you (or anyone else) wants to try to get it working I'd be happy to point you to the right parts of our build infrastructure.

**Comment by Majkl578** [comment]
Out of curiosity tried running the package you provided. What I get there is a segfault instead of illegal instruction:
```
Program received signal SIGSEGV, Segmentation fault.
0x000610d4 in runtime.traceGoStart ()
(gdb) bt
#0  0x000610d4 in runtime.traceGoStart ()
#1  0x000133d4 in runtime/internal/atomic.Storeuintptr ()
```
So this .tar.gz outcome looks similar to https://github.com/grafana/grafana/issues/15209#issuecomment-460061042.

I am not a Go dev but I use other Go software on Pi Zero, notably InfluxDB and Telegraf (from their ofic. repository), and they work fine, so there must it's indeed possible _somehow_ (Telegraf [discussion](https://github.com/influxdata/telegraf/issues/708) and [PR](https://github.com/influxdata/telegraf/pull/779)).

Maybe this is some discrepancy between native Go compiler and GCC compiler (which you seem to use)?

**Comment by chrisys** [comment]
@xlson are you saying between this and #15209 that a build for armv5 will work on the Pi Zero? I found the link to some binaries in Google Drive but is the armv5 build available officially anywhere as a complete package?

**Comment by xlson** [comment]
@chrisys Yes, an armv5 build should work on pi zero. There isn't an official build for armv5 right now but we might add one in the future if there is a lot of requests for it.

**Comment by Majkl578** [comment]
Note that I don't use Go nor know how it's build process works, but in case of Rust this is a matter of _just_ using different linker: the program is compiled with standard arm-unknown-linux-gnueabihf gcc cross compiler and then the linker is taken from [raspberrypi/tools](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf).

**Comment by Majkl578** [comment]
I was able to successfully compile Grafana 6.0.1 for Raspberry Pi Zero.
I followed the steps from Circle CI configuration and used a slightly modified `scripts/build/build.sh` in order to produce build.
1. First, you will need the abovementioned raspberrypi/tools, clone it to /tmp: `git clone https://github.com/raspberrypi/tools.git rpi-tools --depth=1`
2. Second, you need to modify the `build.sh` script to use the RPi-specific linker:
```diff
diff --git a/build.go b/build.go
index ebe240d..80c8260 100644
--- a/build.go
+++ b/build.go
@@ -242,10 +242,8 @@ type linuxPackageOptions struct {
 
 func createDebPackages() {
        previousPkgArch := pkgArch
-       if pkgArch == "armv7" {
+       if pkgArch == "armv7" || pkgArch == "armv6" {
                pkgArch = "armhf"
-       } else if pkgArch == "armv6" {
-               pkgArch = "armel"
        }
        createPackage(linuxPackageOptions{
                packageType:            "deb",
diff --git a/scripts/build/build.sh b/scripts/build/build.sh
index 5f42744..defd861 100755
--- a/scripts/build/build.sh
+++ b/scripts/build/build.sh
@@ -8,6 +8,7 @@ set -e
 
 EXTRA_OPTS="$@"
 
+CCARMV6=/tmp/rpi-tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
 CCARMV7=arm-linux-gnueabihf-gcc
 CCARM64=aarch64-linux-gnu-gcc
 CCX64=/tmp/x86_64-centos6-linux-gnu/bin/x86_64-centos6-linux-gnu-gcc
@@ -28,8 +29,8 @@ fi
 
 echo "Build arguments: $OPT"
 
-go run build.go -goarch armv6 -cc ${CCARMV7} ${OPT} build
-go run build.go -goarch armv7 -cc ${CCARMV7} ${OPT} build
+go run build.go -goarch armv6 -cc ${CCARMV6} ${OPT} build
+#go run build.go -goarch armv7 -cc ${CCARMV7} ${OPT} build
 go run build.go -goarch arm64 -cc ${CCARM64} ${OPT} build
 
 CC=${CCX64} go run build.go ${OPT} build
@@ -51,7 +52,7 @@ source /etc/profile.d/rvm.sh
 echo "Packaging"
 go run build.go -goos linux -pkg-arch amd64 ${OPT} package-only
 go run build.go -goos linux -pkg-arch armv6 ${OPT} -skipRpm package-only
-go run build.go -goos linux -pkg-arch armv7 ${OPT} package-only
+#go run build.go -goos linux -pkg-arch armv7 ${OPT} package-only
 go run build.go -goos linux -pkg-arch arm64 ${OPT} package-only
 
 go run build.go latest
```
(Note that I replaced the armv7 build target as it was the easiest way to avoid conflicts with multiple armhf packages.)

To reproduce the build with my steps, you will have to use Docker and run the `grafana/build-container:1.2.3` container (`docker run --rm -it grafana/build-container:1.2.3`), then execute the following steps:
```
mkdir  -p /go/src/github.com/grafana/grafana
cd /go/src/github.com/grafana/grafana
git clone https://github.com/grafana/grafana --branch=v6.0.1 --depth=1 .
/tmp/bootstrap.sh 
git clone https://github.com/raspberrypi/tools.git /tmp/rpi-tools --depth=1
apt-get update && apt-get install nano
nano scripts/build/build.sh # here you need to modify the file to use RPi linker, see the patch
./scripts/build/build.sh
```
Now your artifacts are present in `/go/src/github.com/grafana/grafana/dist`, both `.tar.gz` and `.deb`.
You can use `docker cp` to copy them from the container to your host system and ultimately scp/rsync them to your Raspberry Pi Zero.

Confirmed this to be working on my Raspberry Pi Zero W which is currently running on the Grafana 6.0.1 produced by the above:
```
root@meteopi:~# grafana-cli -v
Grafana cli version 6.0.1
root@meteopi:~# uname -a
Linux meteopi 4.14.98+ #1200 Tue Feb 12 20:11:02 GMT 2019 armv6l GNU/Linux
```

If you want me to provide the built packages, let me know.

@xlson This guide should be enough for you to know what changes you need on your side, if you need anything else or guide through PRing the change, let me know.

**Comment by nyulaszi** [comment]
@Majkl578 can you please share your built 6.0.1 grafana `.deb` package for Raspberry Pi Zero?
I'm trying to install/run it, what I found on grafana site, with no success (armv6-armv7 problems...)
Thank you in advance!

**Comment by Majkl578** [comment]
GitHub wouldn't allow me to attach such a large file so I created a repo instead until Grafana provides official builds: https://github.com/trashware/grafana-rpi-zero

**Comment by nyulaszi** [comment]
Thank you so much, @Majkl578 !
I've successfully installed, and ran the server on my Pi Zero with the following 3 commands:
`wget https://raw.githubusercontent.com/trashware/grafana-rpi-zero/master/grafana_6.0.1_armhf.deb`
`sudo apt-get install adduser libfontconfig`
`sudo dpkg -i grafana_6.0.1_armhf.deb`
Best regards, Norbert

**Comment by xlson** [comment]
I've started working on incorporating the changes into our build. Could you verify this build for me?

- [grafana_6.1.0-pre_armhf.deb](https://drive.google.com/file/d/1BdKvb9NrQs703uEgUBnc7DiOKuW0_Zqe/view?usp=sharing)
- [grafana-6.1.0-pre.linux-armv6.tar.gz](https://drive.google.com/file/d/1-NaK2l_wrisTYPSrKuPmGaRrs3KxI0Df/view?usp=sharing)

**Comment by Majkl578** [comment]
@xlaon .deb package works for me. 👌

**Comment by xlson** [comment]
@Majkl578 Great. Thanks for testing it!

**Comment by elirnyk** [comment]
Hi @xlson!  

I have installed packages you posted on rpi1, works flawlessly. The only issue I have noticed - packaged phantomjs binary is x86-64 executable. Any chance it is just side effect of temporary build ?

**Comment by xlson** [comment]
We will not bundle Grafana with phantomjs for arm as there is no official build for it. Currently we're working on replacing phantomjs and we might support arm then but we haven't decided yet.

**Comment by Majkl578** [comment]
FWIW PhantomJS is dead & obsolete technology, not sure what you use it for and especially not sure why you bundle it but Chrome headless is usually better option.

**Comment by xlson** [comment]
@Majkl578 Yes. This is why it is being replaced with Headless Chrome. PhantomJS is used to generate images of graphs.

**Comment by sbrl** [comment]
Just run into this issue myself. I installed grafana from the repo repo on an old Raspberry Pi 2, and found that I got max cpu usage and it didn't do anything (no error messages or anything).

Is there an apt repository I can use for armv6 builds for my Raspberry Pi 2?

**Comment by xlson** [comment]
@sbrl can you please create a new issue as this is likely a different problem.

**Comment by sbrl** [comment]
Sure, @xlson. I've found Grafana to be quite complicated to use though and I've installed Chronograf instead - so I'll only open an issue if I ever decide to switch back.

**Comment by Arszilla** [comment]
Apologies to revive an old issue, but I've noticed that there is no documentation of `armel`/Pi Zero (or 1) being unsupported in Docs etc. and in [this](https://grafana.com/tutorials/install-grafana-on-raspberry-pi/) and [this](https://grafana.com/grafana/download?platform=arm) page, the methods are not really applicable for Pi Zero (in my instance).

Not sure if that `grafana_6.1.0-pre_armhf.deb` is any good, especially after 2-3 years.

Can I ask for you to enlighten this situation a bit?

Thanks!
