### ISSUE TITLE
Mysql reconnect error with Grafana 6.0

### ISSUE THREAD

**Issue by eloo** [grafana/grafana#15707]
Hi,

i've just upgraded my Grafana from 5.4.x to 6.0 and now i'm unable to start Grafana because of the 
`Service init failed: Migration failed err: Error 1193: Unknown system variable 'reconnect'`error.
It looks like the problem is the configuration i'm using, because i set the connection url for mysql direct as url with the suffix ?reconnect=true.
I managed to fix it by changing my config to connect without this variable but know i see different error with the connection to my db sometime.

In the logs i can find now the following error message 
`  2019-02-28T10:48:03.86+0100 [APP/PROC/WEB/0] ERR [mysql] 2019/02/28 09:48:03 connection.go:141: write tcp xx.xx.xx.xx:xxxxx->xx.xx.x.xxx:3306: write: broken pipe`
This results sometimes (every few minutes) to a needed relogin to grafana.

So the question is how can i provide the reconnect variable again? Or how can i get rid of the broken pipe error?

Grafana version: 6.0
Datasource: Prometheus
OS: Linux
What did i do? Try to start/upgrade my grafana
Expected result: Grafana starts without errors
What happened instead: Grafana startup failed with `Service init failed: Migration failed err: Error 1193: Unknown system variable 'reconnect'`

**Comment by xlson** [comment]
I don't think you need to set reconnect. My guess would be that Grafana tries to reuse a connection after it has been closed by MySQL. You need to configure `conn_max_lifetime` to something lower than `wait_timout` in your mysql server, if that is the issue. http://docs.grafana.org/installation/configuration/#conn-max-lifetime

**Comment by eloo** [comment]
@xlson Ah good point.. I will try it

**Comment by eloo** [comment]
Okay i've checked the wait_timeout of our database and its set to 8 hours.. so the double as the conn_max_lifetime default (which is 4)
so do you still recommend to decrease the conn_max_lifetime?

**Comment by xlson** [comment]
No, then it seems something else might be causing it. Could there be some network issue that causes the connection between grafana and the mysql server to be lost?

**Comment by eloo** [comment]
@xlson yes that could be the case.. we are on a cloud foundry cluster and i've just seen that the port is changing in the error message like this:
```
write tcp 11.11.11.11:12345->22.22.22.22:3306: write: broken pipe
write tcp 11.11.11.11:23456->22.22.22.22:3306: write: broken pipe
write tcp 11.11.11.11:34567->22.22.22.22:3306: write: broken pipe
```
maybe this is a problem? or what port is this?

**Comment by xlson** [comment]
The port that is changing is the outgoing port, which is expected to change.

Can you see any errors in your database log that would explain why the connection is being broken?

**Comment by eloo** [comment]
@xlson sadly i have no access to the database logs

**Comment by marefr** [comment]
I have never heard of any reconnect server variable in MySQL and couldn't find any when searching for it. Make sure to configure [conn_max_lifetime](https://grafana.com/docs/installation/configuration/#conn-max-lifetime). Closing this since we haven't received any other reports of this problem.

**Comment by bbodenmiller** [comment]
I am getting same error as @eloo with `?reconnect=true` at end of MySQL connection string.

@eloo how did you get PCF to give you connection string without `?reconnect=true`? I'm using https://github.com/bbodenmiller/cf-grafana/tree/patch-1 but still gives error because of `?reconnect=true`.

**Comment by eloo** [comment]
@bbodenmiller i'm not creating the url based on host, port and db name. 
so im not using the predefined url
