### ISSUE TITLE
Bytes/sec data rates label inconsistency

### ISSUE THREAD

**Issue by ciranor** [grafana/grafana#15709]
In the set of "Data Rates" as an axis unit, there's a difference in the way that the various *bytes/sec units are displayed depending on what units are picked.

Selecting "Bytes/sec" displays as "B/s", whereas choosing "kilobytes/sec", "megabytes/sec" and "gigabytes/sec" display as "Bs" without a forward slash, which is inconsistent.

**Comment by xlson** [comment]
Thanks for reporting this bug.

**Comment by Genae** [comment]
Isn't Bs something different than B/s? If you want to remove the slash it should be named Bps instead. Bs is Bytes * Seconds, not Bytes / second.

**Comment by mueslo** [comment]
Why is this closed? This issue still persists in Grafana 7!

**Comment by gjcarneiro** [comment]
Indeed, can we please reopen this bug?  bytes per second should be written as either "Bps" or "B/s".

Bs or MBs makes zero sense in terms of units.
