### ISSUE TITLE
Copy Panel No Longer Retains Size - v6.0.0

### ISSUE THREAD

**Issue by APenketh** [grafana/grafana#15700]
### What Grafana version are you using?
v6.0.0

### What datasource are you using?
N/A

### What OS are you running grafana on?
CentOS 7.3

### What did you do?
Copy a panel and attempt to paste it

### What was the expected result?
As per pre-v6 if you copied a panel and pasted it into the dashboard it would retain its sizing

### What happened instead?
Sizing is no longer retained, small panel in the original size and the larger one is the pasted size.

![image](https://user-images.githubusercontent.com/18573773/53547624-7d85be80-3b6a-11e9-8c53-d21eb31f67ad.png)

**Comment by xlson** [comment]
Not sure if this is an intentional change or not. @peterholmberg @torkelo
