### ISSUE TITLE
Input validation for Scrape Interval in the Prometheus Datasource Config

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#15703]
If the Scrape Interval field in the Prometheus Data Source config page contains an incorrect input (10, instead of 10s, for example) any query to that data source will fail, but no errors will be given when clicking Save & Test.

This leads to bad user experience, as a user will make an incorrect config on one page without the UI telling him about it and then suffering the consequences of that error on a completely different page.

Related to #15688

**Comment by aocenas** [comment]
Looking at the code there does not seem to be much validation. There is some validation for dashboards in https://github.com/grafana/grafana/blob/master/pkg/services/dashboards/dashboard_service.go#L81. So I wonder what approach to validation do we have (or if we have any). At least there should be a way to propagate validation errors from the API to the frontend and be able to show them on proper place. The same validation but with different output should happen when provisioning. Is there any example in the code base that I should follow or is this an open question at this point? Also similar issue was raised [here](https://github.com/grafana/grafana/pull/16690#issuecomment-488237928) cc @bergquist @marefr

**Comment by marefr** [comment]
@aocenas if an API call errors (non-200 http status basically) in `backend_srv.ts` and the response payload contains a message property, that message will automatically be shown in error toaster to the user.

**Comment by aocenas** [comment]
@marefr But I wonder should this be defined on the server? I mean in this instance if we just want to fix this than probably yes but long term as datasources are plugins they are mostly JS only so seems like that should be the place for datasource specific validation (this particular field is in jsonData where anything can go).

In case of backend validation that would also be datasource specific, so it seems like having a:
```
if datasource.type == "prometheus" {
  if !validate(datasource.jsonData["timeinterval"]) {
    return Error(500, "Failed to query datasources", err) 
  }
}
```
in API handler is not long term solution.

Also the `test` part of the datasource comes into play here. In general that is probably a good enough (or maybe even better) validation. But this particular setting does not seem to be used by the test query. Also not being able to test connection does not prevent saving the datasource (maybe just DB is down and will be back up later) so not exactly the same thing I would say.

So I can add the validation `if` in the API for this issue I feel like we will have to create some better, possibly extensible solution.

**Comment by marefr** [comment]
Yeah that's good points. For now just adding some validation in the client should be a good start. Solving the backend validation is hard for datasources not having a backend part as you say.
