### ISSUE TITLE
Shortcut t + arrow not working in explore

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#15704]
In grafana, pressing t + arrow changes the timeframe of the panel.

It would be awesome to have that in Explore too, especially because loki only fetches 1000 lines so we need to move a lot.

**Comment by davkal** [comment]
For Loki, it's not deterministic which 1000 you will get next, since the time is relative (and there is no pagination API for loki). But I do like the idea in general for metrics.

**Comment by gelicia** [comment]
This and the other time range shortcuts are asked for in #32404 - so I am going to close this ticket and do the work in the other one just to consolidate things. Thanks!
