### ISSUE TITLE
Grafana 2.0: HTTP Client & CLI

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1570]
The current CLI commands are built into the main binary and requires the internal runtime & config & context (data access etc) witch makes them less useful than they could be. 

They need to be rewritten in an external cli client that uses the HTTP api. Propose creating a node-http-client lib and a a grafana cli tool (also written in node). Why nodejs? Quick to write json http clients in, good portability and distribution via npm. 

Related to #1556, and #1486

**Comment by bergquist** [comment]
Will this be a separate repo?

**Comment by torkelo** [comment]
Yes, I think so

**Comment by toni-moreno** [comment]
Hi @torkelo I've installed grafana-2.1.0-pre1.x86_64, but I can see  only /usr/sbin/grafana-server binary.


But I haven't found  any cmd line available on it.

```
> /usr/sbin/grafana-server --help
Usage of /usr/sbin/grafana-server:
  -config="": path to config file
  -homepath="": path to grafana install/home path, defaults to working directory
  -pidfile="": path to pid file
```

Where can I look for these CLI tool?

**Comment by torkelo** [comment]
@toni-moreno there are none yet, that is why this issue is still open

**Comment by kportertx** [comment]
@torkelo a bit related, is there a way to configure an API key via the command line? Basically I am trying to automate the configuration of Grafana but I don't see a trivial way around the manual step of creating an API key for the automation.

**Comment by torkelo** [comment]
@kportertx yes, in Grafana 2.1 (upcoming release, released VERY soon) you can authenticate via basic auth, so you could add an api key with a single curl command

**Comment by kportertx** [comment]
```
[dashboards.json]
;enabled = false
;path = /var/lib/grafana/dashboards
```

Awesome :+1: Exaxtly what I needed.
