### ISSUE TITLE
Incomplete documentation on API: "Get single user by Username(login) or Email"

### ISSUE THREAD

**Issue by Frakenz** [grafana/grafana#15715]
Please include this information:
### What Grafana version are you using?
5.4.2
### What OS are you running grafana on?
CentOS 7
### What did you do?
python36
import requests
requests.get('http://admin:admin@localhost:3000/api/users/lookup?loginOrEmail=admin').json()
### What happened ?
```
{
  "email": "user@mygraf.com"
  "id":1,
  "name": "admin",
  "login": "admin",
  "theme": "light",
  "orgId": 1,
  "isGrafanaAdmin": true
}
```
### What does the documentation say?
```
{
  "email": "user@mygraf.com"
  "name": "admin",
  "login": "admin",
  "theme": "light",
  "orgId": 1,
  "isGrafanaAdmin": true
}
```

### What should it be like?
The documentation should say that the response includes the requested user's ID.
Getting the `id` this way is useful when for me because I only have saved the `login` my provisioning script's files.

**Comment by xlson** [comment]
Thanks for reporting this.
