### ISSUE TITLE
Scroll stops working at bottom of a dashboard with 30+ panels

### ISSUE THREAD

**Issue by scottrpoulin** [grafana/grafana#15712]
Please include this information:
### What Grafana version are you using?
v 6.0.0
### What datasource are you using?
influxdb
### What OS are you running grafana on?
CentOS
### What did you do?
I created a dashboard script of about 50 different panels. Two panels per column pulling the last 24 hours and refreshes every hour. Scrolled to the bottom of the dashboard to view the other panels. 
### What was the expected result?
That I am able to scroll up if I reach the bottom
### What happened instead?
The dashboard does not scroll if I reach the bottom of the page.

**Comment by torkelo** [comment]
Strange, unable to replicate and no other reports. What panel types do you have?

**Comment by scottrpoulin** [comment]
I am using the graph panel. I did create the dashboard originally in v5.4.0 and I recently updated to v6.0.0.

**Comment by lukesilvia** [comment]
I have the same issue on v6.0.0. I use Google Chrome for macOS (version 72.0.3626.119).
Maybe I think you can check this issue with following sample dashboard.

[#15712 test-1551408804315.txt](https://github.com/grafana/grafana/files/2917777/15712.test-1551408804315.txt)
(Sorry, I uploaded dashboard json file as txt file because uploading json file is prohibited.)

**Comment by Naumis1** [comment]
Hi, I have the same issue. V6.0.0. Tried on Firefox 60.5.1esr (64-bit) and Chrome Version 72.0.3626.109 (Official Build) (64-bit). Problem occurred, then I generated graph panel with vertical repeat and got about 70 graphs. When I scroll all the way down, I am no longer able to scroll up.

**Comment by scottrpoulin** [comment]
Don't know if it is helpful or not but I have
Chrome Version 72.0.3626.96 (Official Build) (32-bit)
Firefox Version 60.5.1esr (32-bit)

**Comment by scottrpoulin** [comment]
I started to play with the browser settings related to scrolling. I disabled smooth scrolling and autoscrolling; when I try to reproduce the issue the window acts as if it is still being told to scroll down to the bottom and the window jitters up and down. It is acting as if other scroll actions occur it will try to perform that then scroll immediately to the bottom.

**Comment by scottrpoulin** [comment]
It doesn't occur on dashboards with 30 or less panels.

**Comment by torkelo** [comment]
thanks for reporting this! found the issue!
