### ISSUE TITLE
oAuth authentication through an iFrame for a shared Panel throws a server error

### ISSUE THREAD

**Issue by Payden-Pringle** [grafana/grafana#15714]
### What Grafana version are you using?
6.0.0 (commit: #34a9a62)

### What datasource are you using?
MySQL

### What OS are you running grafana on?
Linux 3.10.0-957.1.3.el7.x86_64

### What did you do?
Attempted to log into Grafana through an iFrame using oAuth with Microsoft Azure AD.

### What was the expected result?
A successful login followed by the panel being displayed. This is the result when using version 5.4.3 (commit: #6539180).

### What happened instead?
I am met with a 500 Internal Server error.

See image:

![image](https://user-images.githubusercontent.com/4104557/53577345-1b619500-3b3b-11e9-8657-1e5d8b6e921e.png)

Though this error implies to me that the actual issue is a lack of accessing save state data through iFrames correctly rather than something specific to oAuth.

From Console:
```
grafana.domain.com/login/generic_oauth?code=<Long-Code-ID>&state=<state-id>%3d&session_state=<session-state-id>:1 

GET https://grafana.domain.com/login/generic_oauth?code=<Long-Code-ID>&state=<state-id>%3d&session_state=<session-state-id> 500 (Internal Server Error)
```

Changing Grafana's version back to 5.4.3 (commit: #6539180) causes oAuth authentication to work fine through iFrames.

Attempting to pre-login through the main site then accessing the iFrame shows the login page implying session cookies/states aren't being accessed or acknowledged correctly.

Server Logs from a restart to testing this issue:
```
t=2019-02-28T16:24:47+0000 lvl=info msg="Initializing Stream Manager"
t=2019-02-28T16:24:47+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=https subUrl= socket=
t=2019-02-28T16:24:57+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.244.1.1 time_ms=37 size=364 referer=https://grafana.domain.com/login
t=2019-02-28T16:24:57+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=10.244.1.1 time_ms=1 size=1742 referer=https://grafana.domain.com/login
t=2019-02-28T16:25:04+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/bMGDHX9ik/process-adoption status=302 remote_addr=10.244.1.1 time_ms=0 size=29 referer=https://www.otherdomain.com/
t=2019-02-28T16:25:04+0000 lvl=info msg="OAuth auto login enabled. Redirecting to /login/generic_oauth"
t=2019-02-28T16:25:04+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=307 remote_addr=10.244.1.1 time_ms=38 size=56 referer=https://www.otherdomain.com/
t=2019-02-28T16:25:04+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.244.1.1 time_ms=0 size=364 referer=https://www.otherdomain.com/
t=2019-02-28T16:25:04+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=10.244.1.1 time_ms=0 size=1742 referer=https://www.otherdomain.com/
```

**Comment by marefr** [comment]
@Payden-Pringle could you try and change security settings. Please read 
http://docs.grafana.org/installation/upgrading/#upgrading-to-v6-0 and 
http://docs.grafana.org/installation/configuration/#cookie-samesite. 

Please change cookie_samesite to none and cookie_secure to true if you're using https and let us know how that works out.

**Comment by Payden-Pringle** [comment]
> and let us know how that works out.

That solved the issue. Thanks!

**Comment by deanlennox** [comment]
Login iframe displays logged in and immediately returns to login screen
Grafana v7.1.3
cookie_samesite = disabled (None wont work on chrome)
allow_embedding = true
Not sure if HTTPS required? Only able to run as http

**Comment by SugandhaDuhan** [comment]
setting to cookie_samesite = none doesn't work. It asks for additonal secure attribute which in turn asks grafana to be served over https.
Hence, none of the solutions worked for me.

**Comment by raziza** [comment]
Facing the same issue here. Tried everything that suggested here. Nothing helped. 
Setting enabling `auth.anonymous ` works but it is not what we want.. 
Any news since last September ?

**Comment by fachrisdakbar** [comment]
> @Payden-Pringle could you try and change security settings. Please read
> http://docs.grafana.org/installation/upgrading/#upgrading-to-v6-0 and
> http://docs.grafana.org/installation/configuration/#cookie-samesite.
> 
> Please change cookie_samesite to none and cookie_secure to true if you're using https and let us know how that works out.



> @Payden-Pringle could you try and change security settings. Please read
> http://docs.grafana.org/installation/upgrading/#upgrading-to-v6-0 and
> http://docs.grafana.org/installation/configuration/#cookie-samesite.
> 
> Please change cookie_samesite to none and cookie_secure to true if you're using https and let us know how that works out.

 i've change cookie_samesite = none and cookie_secure to true but it's not work, after i login not redirect to home dashboard grafana in my iframe website. What i should i do?
