### ISSUE TITLE
Horizontal scroll option for graph panel in series mode

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15710]
There should be a **horizontal scroll** for the graph panel when x axis is in series mode. Otherwise, the labels are getting overwritten. 
![image](https://user-images.githubusercontent.com/35651463/53568633-90a78700-3b88-11e9-8603-a1f1702e9550.png)

Although, i know that the x-axis labels can be fixed by aliasing for a small bar graph, but as my graph can grow big in future, a scroll could be useful in that case.

**Comment by torkelo** [comment]
you will need shorter series names, or make the graph wider.
