### ISSUE TITLE
Grafana 2.0: Documentation overhaul

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1571]
I am have been looking at a lot of different documentation systems recently (like read the docs, mkdocs etc). 

I think I like dockers documentation (statically generated with mkdocs, but has search, hosted on s3). Question should the docs live in this main repo or in a seperate repo? Worried that the docs will need lots of images which will bloat the main repo. Of course these could be seperated and not included in the main repo and hosted elsewhere but that will make the process of creating docs a little more painful.

**Comment by torkelo** [comment]
Work in progress on new docs site & system. http://docs.grafana.org/

Only contains the old docs right now, will start writing new documentation for 2.0 and updating the old and restructuring things.

**Comment by nucleusv** [comment]
Will in new docs detailed description of datasource and datasource editor API?

**Comment by torkelo** [comment]
@nucleusv not sure, its not top prio, first prio is detailed install and config instructions, then feature and UI docs
