### ISSUE TITLE
Removing files for provisioned folders and dashboards does not delete them from Grafana's database

### ISSUE THREAD

**Issue by Frakenz** [grafana/grafana#15716]
### What Grafana version are you using?
5.4.2
### What datasource are you using?
InfluxDb and MySQL
### What OS are you running grafana on?
CentOS 7
### What did you do?
Provisioned dashboards using providers on `/etc/grafana/provisioning/dashboards` and creating the directories with JSON files inside them on the path configured in the YAML.
Restarted Grafana
Opened Grafana and saw that the dashboards were correctly provisioned.
Deleted the YAML file on `/etc/grafana/provisioning/dashboards` and the files on the configured path.
Restarted Grafana.
### What was the expected result?
Dashboards and folders are no longer in Grafana
### What happened instead?
They were still there.

**Comment by xlson** [comment]
This was out of scope for the initial implementation of provisioning, but it is definitely something that should be added. As it currently stands, you will have to delete the dashboards before removing the provisioning files, but that will still leave the folders, I think.

**Comment by torkelo** [comment]
I agree this should be fixed, there is a feature request for this already here: https://github.com/grafana/grafana/issues/12875

**Comment by torkelo** [comment]
Sorry, this was about dashboards not datasources

**Comment by Nexucis** [comment]
By the way as a workaround, if you first remove the dashboards on the FileSystem before removing the configuration, dashboard will be completely removed.

**Comment by tiger-seo** [comment]
is there any workaround to remove provisioned dashboard ? currently Grafana does not allow to do this manually, so the only way is to remove Grafana's database and configure everything again

**Comment by Nexucis** [comment]
* When Grafana is running, remove the json file of the provisioned dashboard. You should then see that the dashboard disappear in Grafana.
* Then remove the yaml configuration file and restart Grafana

* If it doesn't work after removing configuration and json file, you can still delete directly from the Grafana UI

**Comment by tiger-seo** [comment]
@Nexucis no, Grafana does not allow to delete those dashboards, there's a popup stating that dashboard was created from provision, so i cannot remove it

**Comment by turchanov** [comment]
Same problem here. I removed both privisioning configuratuion and dashboard json-s. But I cannot remov dashboard from UI for the reasons stated above: "Dashboard cannot be deleted because it was provisioned"

**Comment by gfinocchiaro** [comment]
The only way I found for removing a provisioned dashboard is as follows:

1. Stop Grafana
2. Remove the dashboard file
3. Restart Grafana

Hope this helps.

**Comment by everythings-gonna-be-alright** [comment]
grafana v6.5.1
Same issue

**Comment by loint** [comment]
Same issue

**Comment by midorinet** [comment]
I manually removed it from grafana's database table

**Comment by Zauxst** [comment]
Version 6.6.2 still an issue... come on....

**Comment by aliasmee** [comment]
+1

**Comment by Coreeze** [comment]
Yep... the problem it's still here...

**Comment by ititandev** [comment]
Same issue

**Comment by omerlin** [comment]
same issue also

**Comment by eesperi** [comment]
Also facing this issue, while trying to get foldersFromFilesStructure to work.

**Comment by desser-code** [comment]
Same issue

**Comment by eesperi** [comment]
Removing UID from .json files helped me resolve my issue.

**Comment by ayankhamza** [comment]
Same issue.

**Comment by AronllStone** [comment]
Same issue on Grafana 7.1.1 and MySQL

**Comment by Neru007** [comment]
Facing same issue while using Grafana Latest along with MySQL

**Comment by Ashutoshc07** [comment]
This issue still present with Grafana 7.3.1 , any quick work around will be highly appreciated thanks in advance!

**Comment by chylex** [comment]
So this is why my dashboards are disappearing :) is there any way to detach a provisioned dashboard, so that I can delete the files but keep the dashboard? Manually editing the database file and wiping `dashboard_provisioning` seems to have worked, but I didn't see an obvious way to do this in the UI.

**Comment by wbrowne** [comment]
@chylex yes there is a way 😄   The section `Making changes to a provisioned dashboard` under https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards gives more detail

**Comment by Aracki** [comment]
We all ended up manually removing rows from `dashboard_provisioning` table. Just use sqlite3 to modify database:
```
sqlite3 /var/lib/grafana/grafana.db
```

**Comment by Hassanzadeh-sd** [comment]
this solved my same issue, change your container to root access:
in compose file add this line : 
```
...
services:
    grafana:
        build: .
        user: root
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
...
```
and run again, remove your dashboards, and change this access to normal user.

**Comment by peter-crist** [comment]
These manual approaches work great when you have access to the grafana pod. This works terribly if you have a grafana pod in a production cluster that you don't have write-access to. 

This is still an issue. We need a native way to delete provisioned dashboards.
Something similar to `deleteDatasources` but `deleteDashboards`.

**Comment by hakula139** [comment]
This issue still exists in v11.1.4 with exactly the same behavior (`foldersFromFilesStructure` is enabled in my case). I think this issue needs to be reopened.
