### ISSUE TITLE
QueryEditor should expose onQueryChange to angular plugins

### ISSUE THREAD

**Issue by jsferrei** [grafana/grafana#15718]
Please include this information:
### What Grafana version are you using? 
6.0.0
### What datasource are you using? 
https://github.com/spotify/heroic-grafana-datasource
### What did you do? 
Enabled explore for our datasource connector
### What was the expected result?
Explore would be functional
### What happened instead?
Explore does not work. We've intentionally set our plugin up to not automatically re-query the database when the query changes to reduce unneeded load on our database when users are building queries. This means that in explore mode, onQueryChange is never called, because panelCtrl.refresh is not called. I propose that public/app/features/explore/QueryEditor.tsx expose onQueryChange in scopeProps, so that plugins set up like this are able to use explore. 

Alternatively, the Run Query button could call onQueryChange when clicked.

**Comment by jsferrei** [comment]
@torkelo should this be closed since https://github.com/grafana/grafana/pull/15807 was merged?

**Comment by torkelo** [comment]
Yes
