### ISSUE TITLE
Reexpose dataList to queryCtrl

### ISSUE THREAD

**Issue by jsferrei** [grafana/grafana#15719]
Please include this information:
### What Grafana version are you using?
6.0.0
### What datasource are you using?
https://github.com/spotify/heroic-grafana-datasource
### What did you do?
Tested an upgrade to 6.0.0
### What happened?
While the plugin works, the alias formatting functionality we built in does not. We had implemented our alias formatting in such a way that the plugin did not requery the datasource (since alias changes are really just UI changes and should not require a DB query). Instead, it would bypass requery by accessing panelCtrl.dataList, applying alias's to data.target, and emit a data-received.

I propose that dataList be made available to plugins again. Alternatively, I could see the SDK including an interface to change aliases in this same way, but the former seems like an easier fix.

**Comment by torkelo** [comment]
panelCtrl.dataList is not a common property currently that all metrics panels set, only graph panel has it that I can find

**Comment by jsferrei** [comment]
@torkelo Ahhhh got it. Its actually only necessary to access it in graph panels anyways, since those are where aliasing happens and where we've focused on this optimization

**Comment by torkelo** [comment]
you can access last query response by subscribing to data-received events on the panel event emitter
