### ISSUE TITLE
UI: allow read-only dashboard to show metrics in the 'view' View

### ISSUE THREAD

**Issue by miekg** [grafana/grafana#15729]
This is with Grafana 5.2.4

If a dashboard is marked as read-only (edit = false) you can't (obvisouly) click the edit button, however the information you see there. I.e. what metrics are being graphed in the panel(s) is only available there. It would be nice if the 'View' view would also show those metrics regardless of `edit` state of the dashboard.

Is there any appetite to allow such feature?

**Comment by miekg** [comment]
alternatively we could make our dashboards read/write

**Comment by xlson** [comment]
What information is it that is missing in regards to the metrics, when you log in as a Viewer?

**Comment by miekg** [comment]
this is what we have
~~~
[auth.anonymous]
enabled = true
org_role = Viewer
org_name = Main Org.
~~~
i.e. bog standard. 

If dashboard are read-write things works as expected. But I want to show the some information is a dash is read-only.

I'll update the issue to reflect this.

**Comment by torkelo** [comment]
you can enable the ini feature viewser_can_edit to make viewers be able to access edit mode and make transient changes.
