### ISSUE TITLE
We need the api to add panel

### ISSUE THREAD

**Issue by shallwe** [grafana/grafana#15725]
I use grafana to display my vpses.
I show all my vps cpu/network/mem/disk in one dashboard.

Once I add several vps(about 10 vps), I have to copy panel one by one and change the hostname.
It is useless job to waste my time.

I develop my own system to list my vps and add vps, If your grafana api have the ability to add panel in one dashboard, It will be very useful for me.

I need it very much, thank you!

I notice the grafana and api last year, but one year later, your api still can not do this.

**Comment by xlson** [comment]
You can solve this in multiple different ways. I would suggest looking into:
- using template variables to repeat panels
- scripting the creation of your dashboard json document and updating the dashboard using the api
  - This tool can be used to simplify json generation https://github.com/grafana/grafonnet-lib

If you want further help I'd suggest askin on the [community forum](https://community.grafana.com).
