### ISSUE TITLE
DS Proxy network error can result in panic and logged stacktrace

### ISSUE THREAD

**Issue by gkelekov** [grafana/grafana#15728]
Type of issue?
Question

What Grafana version are you using?
6.0.0 Docker 

What datasource are you using?
Graphite

What OS are you running grafana on?
Ubuntu 16.04LTS / Docker 18.03.1-ce

What did you do?
Upgraded docker image from 5.4.3 -> 6.0.0

What was the expected result? What happened instead?
Upgrade to 6.0.0 went well, without any errors. Few hours after upgrade a few handler errors occur.
We had network problems during that time, so I believe it is network related, but it is little puzzling why handler would call panic on 500 error.
I might be wrong, but still wanted to share this logs with you.

Log export:
08:26:30.000  info t=2019-02-28T08:26:30+0100 lvl=eror msg="Request error" logger=context userId=3 orgId=1 uname=xxx error="net/http: abort Handler" 
stack="/usr/local/go/src/runtime/panic.go:513 
	(0x435098)\n/usr/local/go/src/net/http/httputil/reverseproxy.go:284 
	(0xabb577)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:99 
	(0xd0f66c)\n/go/src/github.com/grafana/grafana/pkg/api/dataproxy.go:35 
	(0xfed2b2)\n/go/src/github.com/grafana/grafana/pkg/api/api.go:258 
	(0x1020d03)\n/usr/local/go/src/runtime/asm_amd64.s:522 
	(0x46385a)\n/usr/local/go/src/reflect/value.go:447 
	(0x4c1223)\n/usr/local/go/src/reflect/value.go:308 
	(0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 
	(0x7966d3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 
	(0x796039)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 
	(0x7b2330)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 
	(0x7b224e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 
	(0xa4f16c)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46385a)\n/usr/local/go/src/reflect/value.go:447 
	(0x4c1223)\n/usr/local/go/src/reflect/value.go:308 
	(0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 
	(0x7966d3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 
	(0x796039)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 
	(0x7b2330)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 
	(0x7b224e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 
	(0xa4ea87)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46385a)\n/usr/local/go/src/reflect/value.go:447 
	(0x4c1223)\n/usr/local/go/src/reflect/value.go:308 
	(0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 
	(0x7966d3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 
	(0x796039)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 
	(0x7b2330)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 
	(0x7b224e)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 
	(0xa4e9a0)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 
	(0x7b21d0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 
	(0x7963c0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 
	(0x79612b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 
	(0x7b2330)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 
	(0x7b224e)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 
	(0xa4c1ed)\n/usr/local/go/src/runtime/asm_amd64.s:522 
	(0x46385a)\n/usr/local/go/src/reflect/value.go:447 
	(0x4c1223)\n/usr/local/go/src/reflect/value.go:308 
	(0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 
	(0x7966d3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 
	(0x796039)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 
	(0x7b2330)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 
	(0x7c2b27)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 
	(0x7bd29e)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 
	(0x7b67f1)\n/usr/local/go/src/net/http/server.go:2741 
	(0x6b379a)\n/usr/local/go/src/net/http/server.go:1847 
	(0x6afb35)\n/usr/local/go/src/runtime/asm_amd64.s:1333 
	(0x465570)\n"
08:26:30.000 info t=2019-02-28T08:26:30+0100 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname=xxx method=POST path=/api/datasources/proxy/1/render status=500 remote_addr=xxx.xxx.xxx.xxx time_ms=941 size=57150 referer="http://grafana.xxx.xxx/d/DGWfLJ1mk/community?orgId=1&from=now-30d&to=now&refresh=5s"

**Comment by xlson** [comment]
It sounds like your networks errors would be the cause for the panic. Did Grafana exit or was it just a few render requests that failed? If Grafana did not crash it looks like things are in order, possibly except for the fact that we shouldn't get the whole stacktrace logged.

**Comment by gkelekov** [comment]
Grafana did not crash, just a few rendered requests failed during this time.
I'm writing this more as info, because I believe that there is no need for full stacktrace in log.

**Comment by xlson** [comment]
Agreed, this should not result in a stacktrace ending up in the log. Thanks for clarifying.

**Comment by torkelo** [comment]
Not sure if this is trivial to solve, as the golang proxy lib has really poor error handling (ie control over how errors are handled and logged) so not logging this error & stacktrace could hide very important stack traces.

**Comment by matheusnicolas** [comment]
any update about this error?

**Comment by xlson** [comment]
This was incorrectly tagged as stale, only pull requests should be handled by the stale-bot at this time.
