### ISSUE TITLE
Keybinding to toggle all legends on a dashboard

### ISSUE THREAD

**Issue by jsferrei** [grafana/grafana#15720]
One thing our users have been asking for is the ability to toggle legends on and off for all panels in a dashboard. I've implemented such a feature, but wanted to open a ticket here first before submitting for review, to see if this is something that would be considered.

**Comment by xlson** [comment]
I think that's an interesting idea. I'll check with the rest of the team. @grafana/grafana-labs-core-devs

**Comment by Dieterbe** [comment]
Nifty idea. I often have panels with legends disabled but sometimes i do want to see them, and editing the panels just for this is annoying.
I will say that often "just enabling" is not enough, as i'll find that after enabling it's not readable enough at which point i typically enable table view or "on the right side of the panel" (but that may take up too much space if the entries are long)

**Comment by Ijin08** [comment]
@Dieterbe I think with this will be ok if the user set the legend the way they want(right side, table etc) and tries out how it will look. The toggle would only be for show legend.

**Comment by jsferrei** [comment]
Cool, I'm going to open up a pull request for review for this, then

**Comment by davkal** [comment]
👍 Legends are a major performance drain. Would be great to display them on demand.

**Comment by Dieterbe** [comment]
thanks @jsferrei !
