### ISSUE TITLE
Templating with opentsdb

### ISSUE THREAD

**Issue by luluprat** [grafana/grafana#1572]
i would like to use automatique templating with opentsdb backend.
when i try to fill metric in the field there is a javascript error and no value are found

Variable values query 
metric.name

Templating
Failed to run query for variable values: undefined is not a function

**Comment by torkelo** [comment]
Yea, this is not supported. And the OpenTSDB api is not very good for this either, but can be worked around. Will try to add this in the future. 

Will close this issue as there is one already.

**Comment by torkelo** [comment]
dupe, #1250
