### ISSUE TITLE
Build failed on macbook: yarn start 

### ISSUE THREAD

**Issue by zsdevX** [grafana/grafana#15724]
WARNING in ./public/app/types/index.ts 17:0-769
"export 'AppNotification' was not found in './appNotifications'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'AppNotificationsState' was not found in './appNotifications'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'DashboardAcl' was not found in './acl'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'DataQuery' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'DataQueryOptions' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'DataQueryResponse' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'TimeRange' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'TimeSeries' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'TimeSeriesStats' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'TimeSeriesVM' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/types/index.ts 17:0-769
"export 'TimeSeriesVMs' was not found in './series'
 @ ./public/app/features/api-keys/ApiKeysPage.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts

WARNING in ./public/app/core/actions/index.ts 4:0-97
"export 'UpdateNavIndexAction' was not found in './navModel'
 @ ./public/app/features/alerting/AlertRuleList.tsx
 @ ./public/app/routes/routes.ts
 @ ./public/app/app.ts
 @ ./public/app/dev.ts
 @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts
Child html-webpack-plugin for "../views/index.html":
     1 asset
    Entrypoint undefined = ../views/index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./public/views/index-template.html] 15 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Compiled with warnings.

**Comment by xlson** [comment]
Have you updated your dependencies? `yarn install --pure-lockfile`

**Comment by torkelo** [comment]
Closing this as it's probably fixed by running a yarn install --pure-lockfile (or update node to LTS)
