### ISSUE TITLE
Grafana 5.x Broke all Alerts because of $interval 

### ISSUE THREAD

**Issue by valcryst** [grafana/grafana#15727]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.4.3
### What datasource are you using?
MySQL, InfluxDB, PostgreSQL
### What OS are you running grafana on?
Debian
### What did you do?
Upgrade from 4.x to 5.x
### What was the expected result?
Alerts still working
### What happened instead?
All Alerts are broken, they still Alert but they vanished on the Dashboards.
If i try to add them again, i get the Message that iḿ using Template Variables wich i dont!

**Comment by xlson** [comment]
Could you post your dashboard json document?

**Comment by torkelo** [comment]
>  they vanished on the Dashboards.
what do you mean?

**Comment by torkelo** [comment]
closing due to lack of updates
