### ISSUE TITLE
Import dashboard from any url, not just Grafana.net

### ISSUE THREAD

**Issue by jordo1138** [grafana/grafana#15722]
### What OS are you running grafana on? debian/docker

This "dashboard not found" is expected behavior for someone entering a dasbboard URL that isn't matching dashboards/dashboardID format from what I can see here in the DashboardImportCtrl.ts

https://github.com/grafana/grafana/blob/5e1a3c9ee2f39127def594876affc077a95af03c/public/app/features/manage-dashboards/DashboardImportCtrl.ts
<img width="1217" alt="gnet" src="https://user-images.githubusercontent.com/8525512/53602437-a5bdef00-3b63-11e9-9eaa-34891ffab482.png">

My question is, for those managing dashboard versioning in git, would simply allowing a url from any host  to a dashboard json file that holds the dashboard be helpful for users and saves having to upload the json file or pasting the raw json?

Any thoughts?

In the long term it may make sense to import/sync many dashboards and dashboard folders from a git repo in bulk
I also considered this could be better handled from a Jenkins plugin that could just post the dashboard to the existing Grafana api and it could trigger on repo commit to the json...

**Comment by xlson** [comment]
It could be added. We are looking at the whole workflow for managing dashboards here #13823 and will take this into account.

In regards to importing dashboards automatically, have you looked at provisioning from [disk](http://docs.grafana.org/administration/provisioning/#dashboards)?

**Comment by jordo1138** [comment]
I’ll review #13823 and add comments there thanks

**Comment by adamkgray** [comment]
Is there any update on this? Two years later and the only way to load dashboards is from disk or grafana.com.
Hosting and centralising dashboard json in a CDN would be extremely helpful for my team as we develop across multiple grafana instances

**Comment by hpl002** [comment]
Any news on this? 
Is there really no other way to share private dashboards? Fumbling json files is not user-friendly?
