### ISSUE TITLE
Enhancement - Dashboards states to help manage large numbers of Dashboards

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#15721]
This is an offshoot from the topic on https://github.com/grafana/grafana/issues/15257 

We believe that the state of a dashboard is very meaningful to search results.  However it will be difficult to predict the long term usage.  In addition, what we want may not match the needs of what other firms/customers want.  Therefore, at the cost of some additional complexity, we have come up with the following recommendation.

1. Every dashboard will have a new field (level) - numeric value.  This will be used to help score dashboards for searching. 
1. The Grafana administrator will be able to configure Grafana and define the list of levels available starting with 1.  A level of 1 is mandatory and is the default value for new dashboards.  With each level the administrator can define a label, e.g.
 
   - Level 1 - Development (default value)
   - Level 2 - Production
   - Level 3 - Official

1. The larger the level number the more important the dashboard is in the search results.
1. Renaming the Levels should be supported
1. In addition for each level there would be a setting to indicate that the level is settable by a Grafana admin only.  By default anyone can set a dashboard level.
1. The level label should be displayed on the dashboard, when opened, and configured in the Settings.  An admin only level should be grey'ed out for non-admins.
1. Levels are reset to the default (Level 1) during a copy.
1. Deletion of a level should be blocked if the level value is still in use on a dashboard.
1. It would be useful if we can allow users to define levels with gaps in the values so that one could add a new level in the future without having to update every dashboard.  For example you might start with
   - Level 1 - Development
   - Level 5 - Production
   - Level 10 - Official
     Later you find that you want to add new levels but because you left gaps in the numbering you can define this without having to make updates to all the dashboards due to re-numbering, e.g. 
   - Level 1 - Development
   - Level 3 - Test
   - Level 5 - Production
   - Lever 7 - Group Master
   - Level 10 - Official

If you were to implement this, then every customer could easily come up with their own conventions.

**Comment by yesoreyeram** [comment]
Instead of level what if the dashboards are sorted based on popularity or view count?

**Comment by shalstea** [comment]
yesoreyeram - see master ticket : https://github.com/grafana/grafana/issues/15257 which has that as well.  When want both the state and hits.

**Comment by shalstea** [comment]
I am withdrawing this, and replacing with https://github.com/grafana/grafana/issues/18075
