### ISSUE TITLE
Graph panel hold and drag the mouse over the graph for some time, then release it, the section is changed.but how to recover before dragging？

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#15726]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
 5.3.2
### What datasource are you using?
default
### What OS are you running grafana on?
win10
### What did you do?
In the graph panel, hold and drag the mouse over the graph for a while, then release it to show that the segment has changed, and then hold and drag it for a period of time.
The initial state：
![image](https://user-images.githubusercontent.com/34366341/53627522-a29a3000-3c43-11e9-8902-6ab6a837d222.png)
The state after the drag：
![image](https://user-images.githubusercontent.com/34366341/53627590-cfe6de00-3c43-11e9-9ebf-f419d0d54cd4.png)

### What was the expected result?
how to recover before dragging？
### What happened instead?
Hopefully there's a way to get back to where you were before you dragged

**Comment by xlson** [comment]
Back in your browser should take you back to before dragging. You could also click the time range selector in the top right corner to re-select your previous range.
