### ISSUE TITLE
Automatically enable annotations when first annotation is added

### ISSUE THREAD

**Issue by alenkacz** [grafana/grafana#1573]
It is really misleading that you have to add annotation to the dashboard - then think why it is not shown on dashboard and THEN realize, that there is another menu, where you have to turn on the annotation feature for the whole dashboard.

I would prefer if annotations were enabled for dashboard when first annotation is added

**Comment by torkelo** [comment]
This is fixed in Grafana 2.0 (the feature toggles for annotations, and templating are removed). When ever there is annotation or template variable the submenu for annotations / template variables are shown.
