### ISSUE TITLE
Datasource API should be able to expose schema info

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15733]
A key challenge with writing visualisation plugins that are not time series is understanding what options are possible given the data.  While the new APIs are under design, I think we should consider how the datasource can expose more schema info.  

I like the structure and style of:
http://app.rawgraphs.io/

The parallel to the v6 UI is clear.  This adds a nice `Map your Dimensions` section.  I would love to see that become a core grafana concept rather than each plugin needing to handle it differently.  

It would be great to have an API that given a query you get back more info about that fields for example:
 - name (what we currently get)
 - title? human readable display name
 - type:  date|string|int|float|number?
 - range? min/max possible value
 - description?
 - units (kbn lookup key)
 - color? appropriate default color?

The values could be obtained from the backend datasource and|or saved as properties in the datasource settings.  The default implementation could just inspect the first few results

This would be a great step towards making grafana a viable alternative to [Tableau](https://www.tableau.com/)

**Comment by torkelo** [comment]
Like a core data source that allowed mapping any json response to a time series format? Maybe an extension to https://github.com/grafana/simple-json-datasource but with custom mapping ability and generic query UI?

**Comment by ryantxu** [comment]
My goal here is not a specific datasource, it is to extend the common datasource API to allow any datasource to expose more robust type/schema info to the system.

As we add more visualisation options, the shape of data is important to understand what reasonable values are.  The datasource seems like a reasonable place to say the variable "speed" is in "velocityms" and should usually be yellow.  

I don't have a specific proposal yet -- just raising this as something to consider as we update the datasource API.

**Comment by torkelo** [comment]
Oh I understand. TimeSeries type already include unit, could also add color & description & range & displayName or something along those lines. 

For table column we have:
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/types/data.ts#L56

**Comment by ryantxu** [comment]
Yup -- what exists is kinda ad-hoc :)  TimeSeries and TableData each have their own props (supporting the the specific visualisation needs)  I would like to see these somehow merged/shared with a better distinction between the data model and the view model.

**Comment by ryantxu** [comment]
I'll close this in favor of #15804, it goes a ways to help
