### ISSUE TITLE
Cannot upgrade grafana from 4.6.5 to 5.4.3 with error mysql database

### ISSUE THREAD

**Issue by nnsaln** [grafana/grafana#15732]
Please include this information:
### What Grafana version are you using? 
4.6.5

### What datasource are you using?
mysql

### What OS are you running grafana on?
Debian 9

### What did you do?
upgrade grafana from 4.6.5 yo 5.4.3

### What was the expected result?
should upgrade successfully

### What happened instead?
Failed to start service 

Log:
```
t=2019-03-01T20:08:20+0700 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
t=2019-03-01T20:08:20+0700 lvl=info msg="Starting DB migration" logger=migrator
t=2019-03-01T20:08:20+0700 lvl=info msg="Executing migration" logger=migrator id="Update dashboard title length"
t=2019-03-01T20:08:20+0700 lvl=eror msg="Executing migration failed" logger=migrator id="Update dashboard title length" error="Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'created' at row 1"
t=2019-03-01T20:08:20+0700 lvl=eror msg="Exec failed" logger=migrator error="Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'created' at row 1" sql="ALTER TABLE `dashboard` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, MODIFY `title` VARCHAR(189) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ;"
t=2019-03-01T20:08:20+0700 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'created' at row 1"
```

 Do I need some adjustment to my mysql?
Thanks

**Comment by xlson** [comment]
What version of MySQL are you using?

**Comment by nnsaln** [comment]
MySQL 5.7

**Comment by marefr** [comment]
@nnsaln does not really know why this is happening. Maybe due to an older bad Grafana migration? 

Could you try and manually update your dashboard table using the following?

```sql
update dashboard set created='1970-01-01 08:00:00' where created='0000-00-00 00:00:00'
```

or 

```sql
update dashboard set created=now() where created='0000-00-00 00:00:00'
```

Then try and start Grafana again. Thanks

**Comment by nnsaln** [comment]
Finally I can upgrade to grafana 5.4.3, but after that I cannot send any alerts.
![image](https://user-images.githubusercontent.com/6915219/54514791-a640ed00-498d-11e9-9898-2047ef2df1fc.png)

Alert state: "pending"

And at grafana log I got this error log.
```
Mar 18 14:54:29 vm-prometheus-1 grafana-server[20845]: t=2019-03-18T14:54:29+0700 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="arg silenced as bool: strconv.ParseBool: parsing \"60\": invalid syntax"
```

Any idea?
Thanks

**Comment by torkelo** [comment]
Pending is natural if you have a For attribute in the alert rule, says firing true focus on that

**Comment by nnsaln** [comment]
I try to update gradually,
grafana version:
5.0 can send alert
5.0.1 can send alert
5.0.2 can send alert
5.0.3 cannot send alert with error
```
t=2019-03-19T17:41:03+0700 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="arg silenced as bool: strconv.ParseBool: parsing \"60\": invalid syntax"
```
5.0.4 cannot send alert with same error
