### ISSUE TITLE
Reconsider react props naming conventions (onInterpolate, etc)

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15734]
The new react props API needs to find a way to cleanly expose system features to plugins.  The first example of this does not feel quite right:

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/types/panel.ts#L15
```
export interface PanelProps<T = any> {
  ...
  onInterpolate: InterpolateFunction;
}
```

I would expect the **onXxx** functions to be how we handle events, not how we request processing.  For properties like this where I expect the dashboard to do something (interpolate variables in the string), what about **handleInterpolate** or  **doInterpolate**?

Likewise the editor also uses [**props.onChange(...**](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/gauge/GaugePanelEditor.tsx):
```
onThresholdsChanged = (thresholds: Threshold[]) =>
    this.props.onChange({
```
I would rather these used **handleX** or **doX** rather than **onX**

I like the convention:
```
<MyComponent onClick={handleClick} />
```

I know there is no right answer, but we should make sure to define a clear strategy before the number of prop functions grows!

**Comment by dprokop** [comment]
@ryantxu I totally resonate with that. Since the API ain't set yet, we can introduce this convention. I also tend to call the named functions that are passed via props using `handleXXX` naming. I think we can try enforcing this strategies using linter. 

I remember you having some thoughts in that as well @torkelo, right?

**Comment by ryantxu** [comment]
looks like there is a linter rule for this:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md

**Comment by torkelo** [comment]
Not sure i agree, the onChange naming is the most comon naming pattern for callbacks that I have seen and is the one used by React itself

**Comment by ryantxu** [comment]
I may be wrong (and often am!), but the typical semantics of standard react `onChange()` callback is that something changed in a child and you need to handle the results.  In the panel plugin use of `props.onChange()`, we have a plugin that is asking the parent to change the properties.  That feels like we want different name.  Also using the standard name `onChange()` for this specific action seems to invite confusion.  Consider the common practice of passing all props to a child with `<div {...props}>`

Likewise if feels weird (but we all get used to much worse things!) to replace variables in a string by calling:
```
  const title = this.props.onInterpolate( this.props.panel.title ) 
```
In this case there is no event triggered or anything, just a utility function that knows more context.  This gets more important when we add functions where we expect side effects: `ChangeTimeRange`, `LoadDashboard`, `SetVariable` -- adding the prefix **on** to all these cases seems to miss something.

> Not sure i agree

😃 reasonable people will disagree, and this kind of discussion leads to bikeshedding.  However given that the API is so new and in still in development, I think it is worth the effort to think about it and work towards something.  If the conclusion is that we prefix everything with **on** that is fine.

In trying to write a few plugins, there are a few kinds of functions we will need to expose soon:
- Plugin asking to change the query:
  * change the time range
  * set variables 
  * list variables
- Utility functions that require context
  * replace variables in a string (currently: onInterpolate)
- Plugin asking to update the PanelModel
  * change settings in the editor (currently: onChange)
- Plugin asking for access to system resources
  * [getBackendSrv()](https://github.com/grafana/grafana/pull/15268)
  * get access to the datasource that made the query

Unclear if these are best done done via props or redux

**Comment by dprokop** [comment]
Personally, I like to think about prop functions as intents, thus I tend to use the `handleXXX` convention. The verb `handle` is a intention fulfilment carrier (at least in my mind as non-native English speaker), if you understand what I mean.

Also, semantic wise, I think it's somehow easier to reason about the code, if there is an intent and the handler separation. Especially in situation when props are passed deeper than one level only. It's then clear that what we are passing down is actually a proxied version of the originally passed prop.

I hope ^^ makes any sense to you guys.

**Comment by torkelo** [comment]
Yes, but i dont think we are discussing the handlar names but the prop names. The prop names should be onChange etc , is it’s a component that wants to communicate events / changes to its parent. So that is why I think onChange is named correctly as it PanelEditor is exactly like a big input component that updates a settings object instead of a single input value (like a select or input has a onChange callback).

There is a common pattern to name handlers handleXXX but Airbnb Jsx guide suggested this was bad, and handlers should be named the same to aid search and navigation, which I have found super useful, super easy to navigate from handler to where prop is set etc

**Comment by torkelo** [comment]
But onInterpolate is a bit different and not sure how to view that one. The reason I went with similar naming here was to have consistencity in all function callback props start with onXXX

**Comment by dprokop** [comment]
You are right @torkelo, I slightly drifted from the props. So, talking props, not internal handlers of a class:

When thinking about the function prop names I see these two types of handlers:
- responding to an event (the `onXXX`)
- requesting a processing (the `doXXX`) (i.e. dispatching redux action)

My mental model for distinguishing the above so far is to use `[verb]XXX` when requesting processing(in scenario above I would most probably name the prop `interpolateString`). If the prop name starts with verb, I clearly know this is a processing request, when it starts with `on` then it's a response to an event.

I don't feel like there is a need to specify a common verb like `do` or `handle` for such scenarios, as the verb itself is self describing and identifies type of processing at a glance. Also, I think this approach is commonly used when mapping dispatch to props in Redux.

**Comment by torkelo** [comment]
> My mental model for distinguishing the above so far is to use [verb]XXX when requesting processing(in scenario above I would most probably name the prop interpolateString). If the prop name starts with verb, I clearly know this is a processing request, when it starts with on then it's a response to an event.

I agree, this sounds like the way to go.

**Comment by ryantxu** [comment]
me too!

So does that mean we should change `onInterpolate` to `doInterpolate` or perhaps `doReplaceVariables`?

**Comment by ryantxu** [comment]
I split this into two concrete pull requests.  Each one has different things to consider.  I'll close this one and we can discuss the two cases independently.
