### ISSUE TITLE
Example dashboard - enabled that level customization. 

### ISSUE THREAD

**Issue by chiddekel** [grafana/grafana#15730]
Open Street Map with live monitoring target.
https://demo.thingsboard.io/dashboard/3d0bf910-ee09-11e6-b619-bb0136cc33d0?publicId=963ab470-34c9-11e7-a7ce-bb0136cc33d0

**Comment by xlson** [comment]
I don't understand what you are trying to say, is this a feature request, and if so, for what? I'm closing this for now but we can reopen it if you explain in more detail what you want.
