### ISSUE TITLE
grafana-server not starting on alpine aarch64

### ISSUE THREAD

**Issue by DerKnerd** [grafana/grafana#15740]
Please include this information:
### What Grafana version are you using?
Grafana 6.0.0
### What OS are you running grafana on?
Alpine Linux aarch64
### What did you do?
Try to start grafana
### What was the expected result?
That grafana runs and I can use it
### What happened instead?
This error message:
```
grafana-server:~$ /usr/local/share/grafana/bin/grafana-server
Error relocating /usr/local/share/grafana/bin/grafana-server: __memcpy_chk: symbol not found
Error relocating /usr/local/share/grafana/bin/grafana-server: __vfprintf_chk: symbol not found
Error relocating /usr/local/share/grafana/bin/grafana-server: __memset_chk: symbol not found
Error relocating /usr/local/share/grafana/bin/grafana-server: __fprintf_chk: symbol not found
```

I have the following packages installed that should have fixed the issue but didn't: `glib libc6-compat`.  
After a bit of research, I found out that the symbols are related to a binary function inside the glibc. Would it be possible to compile a binary that works without them? I couldn't manage to.

**Comment by xlson** [comment]
You could try looking at the alpine docker image PR #14913 for hints on how to solve this.

**Comment by DerKnerd** [comment]
@xlson, thank you. I think installing the glibc into alpine would kind of break the purpose of alpine. So I decided to take Raspbian. But still, this issue really is sticky, cause Raspbian uses a good load more resources than Alpine...

**Comment by marefr** [comment]
@DerKnerd Grafana's docker images are since Grafana v6.4 based on Alpine. Closing this. But let me know if you still have problems and I'll reopen.
