### ISSUE TITLE
Increase timeout and retries number for alerting

### ISSUE THREAD

**Issue by SnirX** [grafana/grafana#15746]
Hi,
We upgraded to Grafana v6.0 from Grafana v5.3.2 on Centos 7.3 machines.
We want to increase alerting timeout and retries number (datasources are Elasticsearch and InfluxDB) due to Slack connectivity issues.
Currently we miss alert notifications from time to time.
At this ticket I was told that upgrading to v6.0 will fix the issue and if its still reproduces to notify you:
https://github.com/grafana/grafana/issues/15211#event-2117847628

Can you please assist?

Thank you!

**Comment by torkelo** [comment]
Can you show grafana-server log output for when you missed an alert notification?

**Comment by bergquist** [comment]
The current timeout for Slack is 30 seconds.

Have you tried turning of images for the notifier? rendering the image and uploading it could be timeconsuming.

**Comment by SnirX** [comment]
Hi,
From it really looks like rendering the image and upload can be time consuming.
Can we increase timeouts and retries?
Sometime when it cannot render the image it sends the default test image, are you familiar with that?

These are the logs:
{"error":"Timeout error. You can set timeout in seconds with \u0026timeout url parameter","logger":"alerting.notifier","lvl":"eror","msg":"Failed to upload alert panel image.","t":"2019-03-04T01:02:36.660400227+02:00"}
{"error":"context deadline exceeded","logger":"alerting.notifier.slack","lvl":"eror","msg":"Failed to upload slack image","t":"2019-03-04T01:02:37.635154696+02:00","webhook":"file.upload"}
{"error":"context deadline exceeded","logger":"alerting.notifier","lvl":"eror","msg":"failed to send notification","t":"2019-03-04T01:02:37.635301821+02:00","uid":"000000010"}
{"error":"Timeout error. You can set timeout in seconds with \u0026timeout url parameter","logger":"alerting.notifier","lvl":"eror","msg":"Failed to upload alert panel image.","t":"2019-03-04T03:03:36.106960272+02:00"}
{"error":"context deadline exceeded","logger":"alerting.notifier.slack","lvl":"eror","msg":"Failed to send slack notification","t":"2019-03-04T03:03:37.081481666+02:00","webhook":"Slack - TC alerts"}
{"error":"context deadline exceeded","logger":"alerting.notifier","lvl":"eror","msg":"failed to send notification","t":"2019-03-04T03:03:37.081777113+02:00","uid":"000000010"}
{"error":"Timeout error. You can set timeout in seconds with \u0026timeout url parameter","logger":"alerting.notifier","lvl":"eror","msg":"Failed to upload alert panel image.","t":"2019-03-04T05:04:36.433222385+02:00"}
{"error":"context deadline exceeded","logger":"alerting.notifier.slack","lvl":"eror","msg":"Failed to send slack notification","t":"2019-03-04T05:04:37.408252747+02:00","webhook":"Slack - TC alerts"}
{"error":"context deadline exceeded","logger":"alerting.notifier","lvl":"eror","msg":"failed to send notification","t":"2019-03-04T05:04:37.40843025+02:00","uid":"000000010"}
{"error":"Timeout error. You can set timeout in seconds with \u0026timeout url parameter","logger":"alerting.notifier","lvl":"eror","msg":"Failed to upload alert panel image.","t":"2019-03-04T07:05:36.658663665+02:00"}
{"error":"context deadline exceeded","logger":"alerting.notifier.slack","lvl":"eror","msg":"Failed to send slack notification","t":"2019-03-04T07:05:37.634972168+02:00","webhook":"Slack - TC alerts"}
{"error":"context deadline exceeded","logger":"alerting.notifier","lvl":"eror","msg":"failed to send notification","t":"2019-03-04T07:05:37.635188325+02:00","uid":"000000010"}
{"error":"Timeout error. You can set timeout in seconds with \u0026timeout url parameter","logger":"alerting.notifier","lvl":"eror","msg":"Failed to upload alert panel image.","t":"2019-03-04T09:06:36.175000041+02:00"}
{"error":"context deadline exceeded","logger":"alerting.notifier.slack","lvl":"eror","msg":"Failed to upload slack image","t":"2019-03-04T09:06:37.149079184+02:00","webhook":"file.upload"}
{"error":"context deadline exceeded","logger":"alerting.notifier","lvl":"eror","msg":"failed to send notification","t":"2019-03-04T09:06:37.149238032+02:00","uid":"000000010"}

**Comment by SnirX** [comment]
Update:
I disabled images in the alert and the issue was resolved.
Attaching the image together with the alert message is very useful, can we increase timeouts and retries?
Thanks.

**Comment by torkelo** [comment]
They are quite long & large already (30 seconds)
