### ISSUE TITLE
Cannot perform bucket script on moving average/derivative aggregations

### ISSUE THREAD

**Issue by rnd-ash** [grafana/grafana#15741]
Please include this information:
### What Grafana version are you using?
6.0.0
### What datasource are you using?
Elasticsearch 6.6.1
### What OS are you running grafana on?
Ubuntu
### What did you do?
Because grafana renders so many points on a chart (Kibanas default maximum is 200 data points per chart (time wise), visulizations that have very fast changing counts are hard to interpret as their lines become very messy within grafana (I do not want to change the minimum time interval within each chart). I also want to perform a 'count per second query' with some data using the new bucket script agg that finally became available within grafana 6.0.0.

With Kibana, as shown below, I can solve both of these by doing a moving average of count, then performing a bucket script on the moving average in order to get a smoother events per second graph:
![image](https://user-images.githubusercontent.com/14551965/53687892-b1134500-3d32-11e9-88f8-b857374e7488.png)
However, in grafana, the bucket script does not allow a moving average to become a variable:
![image](https://user-images.githubusercontent.com/14551965/53687901-d4d68b00-3d32-11e9-93c8-89f3fc7fbed3.png)

**Comment by prokopenkopn** [comment]
May I add here that the same problem is with the derivative type metrics. Grafana does not allow to set the bucket script variable to derivative:
![image](https://user-images.githubusercontent.com/40295718/53721279-df4c6e00-3e73-11e9-8096-2bbdb4a4e24c.png)
Possibly, other types of metrics also need to be checked.

**Comment by rolandjitsu** [comment]
I'm having a similar issue. It actually doesn't show any metric when I try to select field.

![Screenshot 2019-04-24 18 14 55](https://user-images.githubusercontent.com/1479737/56652087-0fb6c880-66bd-11e9-8f14-0d3e9359e60b.png)

**Comment by marefr** [comment]
@rolandjitsu I think you misunderstood how bucket script aggregation works. You'll need to add another metric like max(field) and then it will show up in the drop down for variables.

**Comment by rolandjitsu** [comment]
I probably did 😄 I'm actually trying to implement a formula: `log(mean(I.^2)/mean(I)^2)`; so I thought that I could use the bucket script aggregation 😕

**Comment by aurimasplu** [comment]
I have the same problem, but I managed to make it work with derivative. First I created and saved graph with two variables in bucket script and then I went to dashboard JSON and edited it to have derivative aggregation IDs in variables.
As I see it Grafana need ability to "translate" all aggregations within bucket for bucket script aggregation. Bucket script aggregation does not care about other aggregations types as log they are in same bucket.

**Comment by UKSFM99** [comment]
Any update on this? Im on 6.3.0 nightly and still Can't perform bucket scripts on derivatives

**Comment by prashanth-iyengar** [comment]
I would like to perform bucket scripts on std_deviation field derived from extended stats aggregation. Assuming it is related to the same issue here

**Comment by UKSFM99** [comment]
Any update on this?

**Comment by lasselj** [comment]
+1

**Comment by schwatvogel** [comment]
@aurimasplu solution work, but you cant pick the `bucket_path` value as needed:
if using normalized derivatives( Option `unit` in the derivative metric):
```
"1":{
  "max":{
    "field":"http.requestCount"}},
"3":{
  "derivative":{
    "buckets_path":"1",
    "unit":"1s"}},
```
The elasticsearch aggregation result contains two values: `value` and `normalized_value` which is the displayed (in my case as requests per second) in grafana:
```
{
  "key_as_string" : "1567754440000",
  "key" : 1567754440000,
  "doc_count" : 8,
  "1" : {
    "value" : 343912.0
  },
  "3" : {
    "value" : 381.0,
    "normalized_value" : 19.05
  },
``` 
When using a Bucket script to get a non negative derivative with request per second, yo need to adress the `normalized value`:
```
"4":{
  "bucket_script":{
    "buckets_path":{
      "var1":"3.normalized_value"},
    "script":"if (params.var1 >0 ){return params.var1}"}
    }
```
But when editing the Panel Json and adding 
```
{
  "type": "bucket_script",
  "field": "select field",
  "id": "4",
  "settings": {
    "script": "if (params.var1 >0 ){return params.var1}"
  },
  "meta": {},
  "pipelineVariables": [
    {
      "name": "var1",
      "pipelineAgg": "3.normalized_value"
    }
  ],
}
```
The resulting elastic query contains an empty `bucket_path`

**Comment by karln-star** [comment]
+1
