### ISSUE TITLE
Use variable labels in Legend format

### ISSUE THREAD

**Issue by evescorp** [grafana/grafana#15743]
Information:
### What Grafana version are you using?
Grafana v5.4.3 (6539180)
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
I created a Pie chart graph. The metric used in the query has a label which is an identifier of product and I set a query with just the name of the metric because I want to show all the products
Example Prometheus metric: 

> sells_total{productId="1000"} 15.0
> sells_total{productId="2000"} 32.0

Example Query in Grafana: 

> sells_total

### What was the expected result?
A pie chart with 2 slices was drawn by Grafana, which is fine.
Now I want the Legend format to be the name of the product. In order to do that I want to use the information collected by a variable called 'product' that I set up (using a MySQL datasource) in Grafana where I associate labels to the productIds in order to use them in some other panels.
Example Variable set up in Grafana:

> SELECT name AS __text, id AS __value from ProductInfo

### What happened instead?
In Legend format input I place {{productId}} which shows the legends for every slice as "1000" and "2000" respectively, but I cannot find the way to use the variable 'product' for showing the corresponding label. For example I want them to appear as "Product A" and "Product B" using conversion between productId and the corresponding label value stored in the variable 'product'.

Is there a way to do that instead of getting the product name directly as a label in the Prometheus metric?

**Comment by torkelo** [comment]
This is a duplicate feature request to this old issue, https://github.com/grafana/grafana/issues/1153
