### ISSUE TITLE
Gauges are interpolated

### ISSUE THREAD

**Issue by skorokithakis** [grafana/grafana#1574]
Unless I'm misunderstanding something, there's a small bug. I have a gauge that's binary (0/1), and adding it to the dashboard with the "current" value setting produces intermediate values. I.e. whenever it changes from 0 to 1, I get intermediate values like 0.31, 0.68, 0.96 etc until it goes to 1.

**Comment by torkelo** [comment]
what time series store are you using? If InfluxDB, what aggregation function have you selected? 

If Graphite, what does your query look like? if there are more points than there are pixels in the graph, then graphite will apply  consolidation, which by default is done using average function (can be changed using graphite function `consolidateBy`

**Comment by torkelo** [comment]
also if you have a gauge that is binary, and use graphite, depending on you graphite aggregation rules, the rollups could be done using average function (by default all metrics that do not end in .count are rolled up using average)

**Comment by skorokithakis** [comment]
I'm not sure, I use https://github.com/kamon-io/docker-grafana-graphite (I wanted a quick way to set it up). It sounds like it uses graphite, I just straight-up display the points, which aren't very dense (one a minute). It may be my aggregation rules, I just wanted to make sure it wasn't a bug, thank you.
