### ISSUE TITLE
Make Drill-down link easier to reach

### ISSUE THREAD

**Issue by swehner** [grafana/grafana#1575]
I think the drill down links are *very useful*, but a bit hard to reach in the graph panels.
You have to click the titlebar, click the "burger menu" button and find drill down links at the bottom mixed with more internal features like "Export CSV" and "Panel JSON". 
Most people don't find the drill-down links in there.

How about making a separate menu with drill down links accessible from the "panel-links" icon, similar to what I'm showing in this mockup?

![image](https://cloud.githubusercontent.com/assets/273236/6557613/955b4628-c676-11e4-951f-b534624ee759.png)

**Comment by torkelo** [comment]
Yea, I agree, the drilldown links need to be reached in a better & easier way. Your suggestion is a big improvement! Will try to find time to implement this for v2.1 or v2.2

**Comment by costimuraru** [comment]
:+1 I'd love to see this implemented

**Comment by liyichao** [comment]
:+1:

**Comment by torkelo** [comment]
![drilldown](https://cloud.githubusercontent.com/assets/10999/9976491/58765064-5ee6-11e5-8fa2-69b9e7def545.gif)

ping @mattttt

**Comment by mattttt** [comment]
I responded on slack, but this was left handing. I think it's a big step forward in making those drilldown links accessible. 

I was playing around with including the amount of links one can expect when they click it. Unnecessary? Super useful? Undecided on whether it's clear that the number relates to the drilldown links and not something in the panel header. 

![screenshot 2015-09-28 15 52 20](https://cloud.githubusercontent.com/assets/2886187/10146861/f1164b4e-65f8-11e5-894a-b518f036803e.png)
