### ISSUE TITLE
Cannot use Testdata datasource in 6.0.0: error "Validation failed"

### ISSUE THREAD

**Issue by diafour** [grafana/grafana#15751]
Please include this information:
### What Grafana version are you using?
docker run --rm -it grafana/grafana:6.0.0

### What datasource are you using?
testdata

### What OS are you running grafana on?
ubuntu 16.04

### What did you do?
1. Go to datasources page
2. Add datasource "testdata db"
3. Press "Save & Test"

### What was the expected result?
Green message "Datasource updated"

### What happened instead?
Red alert "Validation failed" is apperead.

### Additional information

Browser: Chrome Version 72.0.3626.109 (Official Build) (64-bit), Firefox 58.0.2 (64-bit)

Error in console:

![2019-03-04-104507-1301x677](https://user-images.githubusercontent.com/1055474/53717925-bd022280-3e6a-11e9-9261-63891da2d23d.png)

Images grafana/granafa:5.4.3 and grafana/grafana:5.4.1 works well.

**Comment by torkelo** [comment]
You can still use it, it's just a bug in the Save & Test flow.

**Comment by diafour** [comment]
@torkelo oh! It really works, but i need to restart grafana to testdata datasource becomes available in a query source dropdown.

BTW i got the same error for Simple Annotations plugin.
