### ISSUE TITLE
graphite holtWintersForecast function

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1576]
Hi Torkel:

I realized that graphite does not allow forecasting into the future. Do you think, if I modified the holtWintersForecast function, grafana will be able to show the results? Have you every came up with the request? Before I start, I need to know if this is doable?

**Comment by torkelo** [comment]
no, there are no others that have requested that. Right now there is no way besides absolute time ranges where you can view the future. But is it doable

**Comment by gsaray101** [comment]
Is it doable by modifying the holtwintersforecast function in graphite?

**Comment by torkelo** [comment]
@gsaray101 regarding that I have no idea

**Comment by gsaray101** [comment]
U said its doable?

**Comment by torkelo** [comment]
@gsaray101 I was only commenting on grafana can show metrics in the future

**Comment by fuqqer** [comment]
I've been begging for this feature too. It's not really a forecast if it's not actually predicting future values.

**Comment by d0t101101** [comment]
+1 - baselines/predictions/forecasting would be an immensely useful feature addition for all.  I hope to see it in the future!

**Comment by davidak** [comment]
:+1: 

@gsaray101 this would be a nice feature. any progress here?

**Comment by bbczeuz** [comment]
+1
Not sure if this should be a feature of Grafana, or the underlying DB. Maybe Kapacitor of InfluxDB could do the job?

**Comment by Kshitij-Redmart** [comment]
https://roidelapluie.be/blog/2015/05/13/r-and-graphite/
