### ISSUE TITLE
Viewers cannot open /explore by path

### ISSUE THREAD

**Issue by BertHartm** [grafana/grafana#15773]
### What Grafana version are you using?
6.0.0 (docker image aa7706222b78)
### What datasource are you using?
prometheus
### What OS are you running grafana on?
linux
### What did you do?
went to http://my-grafana:port/explore as a view only user
(I was trying to figure out how to link pre-built queries for alerting purposes)

#### easier to reproduce
1) login to a grafana with `viewers_can_edit` with a viewer account
2) navigate to /explore via the menu
3) reload the page via f5 or by clicking in the url bar and hitting enter

### What was the expected result?
The explore ui would show up (like it does for admin users)
### What happened instead?
I was redirected to the home page, but could still navigate to explore via the menu
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
It's a `302 found` with `Location: /`

**Comment by torkelo** [comment]
might be missing a index route for explore, https://github.com/grafana/grafana/blob/master/pkg/api/api.go#L33

**Comment by torkelo** [comment]
oh, and thanks for reporting this!
