### ISSUE TITLE
Data is shown 1 hour later from Mysql

### ISSUE THREAD

**Issue by glsf91** [grafana/grafana#15777]
Please include this information:
### What Grafana version are you using?
5.4.3
### What datasource are you using?
Mysql
### What OS are you running grafana on?
Ubuntu 16.04.3 LTS
### What did you do?
I want to graph the result of data in Mysql. I have the same data also in influxdb but want to move to Mysql.
### What was the expected result?
Show the data at the right time.
### What happened instead?
The data from example 19:00 is shown in Grafana at 20:00. Same data from influxdb is shown at 19:00.

I think there is something going on with timezone stuff. I have read already #13769 but could not find a solution for my problem.

I use local time in dashboard. I'am on UTC +1 (=CET). Server Mysql and server Grafana is on CET. Both Ubuntu.

Graph as an example:
![image](https://user-images.githubusercontent.com/33393611/53765287-dee1c080-3ecf-11e9-94b5-f471305a01dd.png)
Right is mysql and left is influxdb. So mysql is showing data 1 hour later. It is now 22:50 local time.
(there is a little bit difference in the last data of Mysql;don't pay attention to it.)

Looks like something is mixing up the timestamps in the result.

On the mysql server cli:
(query from the generated SQL from Grafana; only changed last time stamp and time in timer)
 SELECT   stamp AS "timer",  unix_timestamp(stamp) as unixtime, usage2 FROM P1SmartMeter WHERE   stamp BETWEEN FROM_UNIXTIME(1551722400) AND FROM_UNIXTIME(1551722464) ORDER BY stamp;
+---------------------+------------+--------+
| timer               | unixtime   | usage2 |
+---------------------+------------+--------+
| 2019-03-04 19:00:04 | 1551722404 |    464 |
| 2019-03-04 19:00:35 | 1551722435 |    467 |
| 2019-03-04 19:01:04 | 1551722464 |    470 |
+---------------------+------------+--------+

Timer is in Mysql of datatype Timestamp which is always UTC. Timer is indeed local time (UTC+1) 19:00:04. Timezone of session is CET (UTC+1).

mysql> set time_zone='UTC';
mysql> SELECT   stamp AS "timer",  unix_timestamp(stamp) as unixtime, usage2 FROM P1SmartMeter WHERE   stamp BETWEEN FROM_UNIXTIME(1551722400) AND FROM_UNIXTIME(1551722464) ORDER BY stamp;
+---------------------+------------+--------+
| timer               | unixtime   | usage2 |
+---------------------+------------+--------+
| 2019-03-04 18:00:04 | 1551722404 |    464 |
| 2019-03-04 18:00:35 | 1551722435 |    467 |
| 2019-03-04 18:01:04 | 1551722464 |    470 |
+---------------------+------------+--------+

Now showing timer in UTC which is correct.

In Grafana:
![image](https://user-images.githubusercontent.com/33393611/53763750-cff90f00-3ecb-11e9-9e1a-ad7186928a9b.png)
Only Query B (same as in CLI above) is active. So it is showing in Grafana also 19:00:04 but then with Z added, compared with cli.

Now this in cli (new session):
mysql> SELECT now(),UTC_TIMESTAMP,TIMEDIFF(NOW(), UTC_TIMESTAMP),@@session.time_zone,FROM_UNIXTIME(1551722400) ;
+---------------------+---------------------+--------------------------------+---------------------+---------------------------+
| now()               | UTC_TIMESTAMP       | TIMEDIFF(NOW(), UTC_TIMESTAMP) | @@session.time_zone | FROM_UNIXTIME(1551722400) |
+---------------------+---------------------+--------------------------------+---------------------+---------------------------+
| 2019-03-04 22:27:38 | 2019-03-04 21:27:38 | 01:00:00                       | SYSTEM              | 2019-03-04 19:00:00       |
+---------------------+---------------------+--------------------------------+---------------------+---------------------------+

Now the same in Grafana (query C):

![image](https://user-images.githubusercontent.com/33393611/53764181-d63bbb00-3ecc-11e9-96f5-f20d6225ed26.png)
It is the same but 'Z' is added on all 3. But Grafana Mysql session timezone looks like the same as in cli (=CET; UTC+1).

Both are carried out at about 22:28 local time, 21:28 UTC.
My browser is in localtime, so I expect the result 2019-03-04T22:28:14 for now() (without Z).
I think this is the reason why Grafana want to plot this point on 23:28:14, which is in the future and is indeed 2019-03-04T22:28:14Z).

What is happening ?

**Comment by torkelo** [comment]
For the graph query what is the MySQL Query and what is the response? check in query inspector.

**Comment by marefr** [comment]
> Server Mysql and server Grafana is on CET

Think there's you're problem. Recommendation to use UTC for Grafana server.

**Comment by glsf91** [comment]
> > Server Mysql and server Grafana is on CET
> 
> Think there's you're problem. Recommendation to use UTC for Grafana server.

That will not be possible. Also other stuff is running on this server.
Also a little bit strange. Influxdb is also stores timestamps (as far as I known) in UTC  format. This is working well (using same Grafana instance)
I don't know if it is possible to use a different timezone only for the Grafana process.
Also the MSQL cli is running on a server with the same timezone as the Grafana server and works fine.

**Comment by glsf91** [comment]
> For the graph query what is the MySQL Query and what is the response? check in query inspector.

Query inspector:
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1551740400000",
      "to": "1551826799999",
      "queries": [
        {
          "refId": "B",
          "intervalMs": 120000,
          "maxDataPoints": 926,
          "datasourceId": 6,
          "rawSql": "SELECT   stamp AS \"timer\",  unix_timestamp(stamp) as unixtime, usage2 FROM P1SmartMeter WHERE   stamp BETWEEN FROM_UNIXTIME(1551722400) AND FROM_UNIXTIME(1551722464) ORDER BY stamp;  ",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "B": {
        "refId": "B",
        "meta": {
          "rowCount": 3,
          "sql": "SELECT   stamp AS \"timer\",  unix_timestamp(stamp) as unixtime, usage2 FROM P1SmartMeter WHERE   stamp BETWEEN FROM_UNIXTIME(1551722400) AND FROM_UNIXTIME(1551722464) ORDER BY stamp;  "
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "timer"
              },
              {
                "text": "unixtime"
              },
              {
                "text": "usage2"
              }
            ],
            "rows": [
              [
                "2019-03-04T19:00:04Z",
                1551722404,
                464
              ],
              [
                "2019-03-04T19:00:35Z",
                1551722435,
                467
              ],
              [
                "2019-03-04T19:01:04Z",
                1551722464,
                470
              ]
            ]
          }
        ]
      }
    }
  }
}

**Comment by glsf91** [comment]
Additional a wireshark dump captured on the Grafana server with the same query:
![image](https://user-images.githubusercontent.com/33393611/53828679-a4832c80-3f7e-11e9-8c3e-e4d43ee3ba85.png)

Here you can see MySQL is giving back local time (UTC+1). Which is logical because session is Timezone System which is CET (UTC+1). Same as I saw in CLI with CET timezone.

So Mysql says "2019-03-04 19:00:04". Grafana is telling "2019-03-04T19:00:04Z" in inspector.

**Comment by glsf91** [comment]
@torkelo Do you need more information?
Just ask.

**Comment by torkelo** [comment]
I can’t see anything wrong, when you query returns a Unix timestamp is shows up correctly in Grafana. If you query dates MySQL will tranfsform them to local timezone but Grafana will treat them as UTC so that could be your problem. Try in your query transform timer to a Unix timestamp

**Comment by glsf91** [comment]
@torkelo 

If I change: 
`SELECT   stamp AS "time",  usage1Wh FROM P1SmartMeterElectra WHERE   $__timeFilter(stamp) ORDER BY stamp`

into 

`SELECT  unix_timestamp(stamp) AS "time",  usage1Wh FROM P1SmartMeterElectra WHERE  $__timeFilter(stamp) ORDER BY stamp`

it is indeed working fine.
Unfortunately I cannot use the query builder afterwards anymore (because it overwrites the query).

This means (if I understand correctly) Grafana always see the dates as UTC, regardless of the timezone used on the Grafana server. Looks like the timezone in the Grafana MySQL session is now defined by timezone on the Grafana server.
If this is the case, it maybe better to set into the session (set time_zone='UTC';) always by Grafana when it makes a connection to Mysql. Then Grafana always get UTC back from MySQL which is expected by Grafana.
Can I set this somewhere?

**Comment by glsf91** [comment]
I have found a workaround without using unix_timestamp().
I use the user grafana to connect to mysql.
In /etc/mysql/my.cnf on the Mysql server I added en restarted Mysql:

`[mysqld]
init_connect="SET SESSION  time_zone = IF( CURRENT_USER() = 'grafana@%', 'UTC', @@session.time_zone);"`

Now it is working as expected. The timezone for the session for only user grafana is set to "UTC".

I still think it is advisable to Grafana to:
- add an option to the configuration of the datasource where timezone can be defined 
or
- Grafana always set the session timezone to UTC.

**Comment by glsf91** [comment]
I have found a workaround without using unix_timestamp().
I use the user grafana to connect to mysql.
In /etc/mysql/my.cnf on the Mysql server I added en restarted Mysql:

[mysqld]
 init_connect="SET SESSION time_zone = IF( CURRENT_USER() = 'grafana@%', 'UTC', @@session.time_zone);"

Now it is working as expected. The timezone for the session for only user grafana is set to "UTC".

I still think it is advisable to Grafana to:

add an option to the configuration of the datasource where timezone can be defined
or
Grafana always set the session timezone to UTC.

**Comment by torkelo** [comment]
ok, yea Grafana & MySQL timezone handling can be improved. It's super tricky with MySQL and how it behaves so differently to other DB's

**Comment by grafanauser** [comment]
I had the same issue and found no solution with google. Finally by browsing the CLOSED topics here, I found the unix_timestamp solution which works as a work around for now. I hope you can improve that in the future. I am not sure why it is closed. The issue still exists for everybody who tries out mySQL as data source.

**Comment by dakipro** [comment]
I am facing the exact same problem when grafan is showing data. 
Grafana is generating this query against database set on my timezone (CET)
`SELECT datetime AS "time", message AS metric, priority AS "priority" FROM messages WHERE datetime BETWEEN FROM_UNIXTIME(1553022959) AND FROM_UNIXTIME(1553627759) ORDER BY datetime DESC`

and when I run the same code from my pc via phpMyAdmin it is showing data in proper time, f.eks.
2019-03-26 20:14:29 | Data here
but when run from grafana it returns 
1553631269000 | Data here
This timestamp looks like it is already off by 1h, thus when converted to date results in
2019-03-26 21:14:29 | Data here

And suggestion from @glsf91 to write the query manually like 
`SELECT unix_timestamp(datetime)  AS "time"`
fixes the correct time. But it disables the query builder

**Comment by glsf91** [comment]
> And suggestion from @glsf91 to write the query manually like
> `SELECT unix_timestamp(datetime) AS "time"`
> fixes the correct time. But it disables the query builder

If you carry out my last post, you still can use the query builder.

**Comment by dakipro** [comment]
I did that just now thanks, but then the selected data is back one hour :(
I never get data in the last hour

**Comment by glsf91** [comment]
> I did that just now thanks, but then the selected data is back one hour :(
> I never get data in the last hour
> I see this query generater
> `SELECT datetime AS "time", message AS metric, priority AS "priority" FROM messages WHERE datetime BETWEEN FROM_UNIXTIME(1553024459) AND FROM_UNIXTIME(1553629259) ORDER BY `time` DESC`
> 
> and when I run it from Grafana, last hour is missing (same query works fine in phpMyAdmin)

Did you restart grafana after the change?
Did you use the user grafana in the MySQL datasource in grafana?

Are you sure that query is made with the query builder. I expect something like this:
SELECT
  stamp AS "time",
  device AS metric,
  temperature
FROM Temperature
WHERE
  $__timeFilter(stamp)
ORDER BY stamp

So not using FROM_UNIXTIME

**Comment by dakipro** [comment]
I do use grafana user in mysql, query is as you show it, when I refresh data I get "Generated query", there it contains from_unixtime. 
However, after restarting both mysql and grafana docker containers, this fix now stopped working completely. I am back to having data displayed AND queried one hour in the past. So now I have double error :) 
I might just live with it for the moment being, since I do not have that much data in mysql. Hoping for a better, integrated solution in grafana itself. 
Thanks for helping me by the way.

**Comment by torkelo** [comment]
Check the timezone inside your container

**Comment by glsf91** [comment]
> I do use grafana user in mysql, query is as you show it, when I refresh data I get "Generated query", there it contains from_unixtime.
> However, after restarting both mysql and grafana docker containers, this fix now stopped working completely. I am back to having data displayed AND queried one hour in the past. So now I have double error :)
> I might just live with it for the moment being, since I do not have that much data in mysql. Hoping for a better, integrated solution in grafana itself.
> Thanks for helping me by the way.

You can check if the setting on the session is working by doing the following query in Grafana:
SELECT @@session.time_zone;
(add a table and make sure Format as table). You should see UTC. If not , you did something wrong :-)
You can of course also start a CLi session to MySQL with the user grafana. Query should give the same result: UTC.
If it says SYSTEM then the init_connect is not done.

**Comment by mahadi** [comment]
> 
> 
> I had the same issue and found no solution with google. Finally by browsing the CLOSED topics here, I found the unix_timestamp solution which works as a work around for now. I hope you can improve that in the future. This is not how it should be implemented in grafana. I am not sure why this issue is closed. The issue still exists for everybody who tries out mySQL as data source. Everybody will face this bug.

Are there plans to solve this issue in general for all users without these workarounds? I am not sure if this is difficult, but as @grafanauser said, this probably affects many people (including me).

**Comment by docbender** [comment]
> I have found a workaround without using unix_timestamp().
> I use the user grafana to connect to mysql.
> In /etc/mysql/my.cnf on the Mysql server I added en restarted Mysql and Grafana:
> 
> [mysqld]
> init_connect="SET SESSION time_zone = IF( CURRENT_USER() = 'grafana@%', 'UTC', @@session.time_zone);"
> 
> Now it is working as expected. The timezone for the session for only user grafana is set to "UTC".
> 
> I still think it is advisable to Grafana to:
> 
> * add an option to the configuration of the datasource where timezone can be defined
>   or
> * Grafana always set the session timezone to UTC.

I have MariaDB 10.1 and I have to modify my init_connect this way:
```
[mysqld]
init_connect="SET time_zone = IF( CURRENT_USER() LIKE 'grafana@%', '+00:00', @@session.time_zone);"
```

**Comment by lalmeida** [comment]
Thanks for the workaround. It worked for me, but i had to make a couple of small modifications for it to work with MySQL 5.7:

```
[mysqld]
init_connect="SET SESSION time_zone = IF( CURRENT_USER() = 'grafana@localhost', '+00:00', @@session.time_zone);"
```

**Comment by Yeaminul** [comment]
Hello Guys,

Has there been any update regarding the Grafana & MySQL timezone handling issue? I've been facing the issue in grafana version - 8.4.4. I'm using a managed mysql instance as my data source, so changing configuration of that managed instance would be cumbersome. As it can be seen from the screenshots, the data is coming from the query but not being shown in dashboard.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/48090089/164399490-854d84d8-b85f-406b-bffe-2508d2385d12.png)

**Comment by BrayanTheloveend** [comment]
really i don't get anything, i just wanna know how to set defintively  TImestamp mysql  by  the current time
