### ISSUE TITLE
Dashboard Links not visible in Kiosk mode

### ISSUE THREAD

**Issue by Paul-Reed** [grafana/grafana#15776]
Could the decision 'not implemented' in [this closed issue](https://github.com/grafana/grafana/issues/15546) please be reviewed.

It seems very unfortunate that users cannot use **kiosk mode** and **Dashboard links** at the same time.
Both are great features, and using kiosk mode on a large monitor looks great, but cannot be used because the Dashboard links are hidden, and therefore viewers cannot select alternative dashboards.

It's worth mentioning that the original request made in https://github.com/grafana/grafana/issues/7691 was for an **optional feature** to be added to hide the menu in kiosk mode, and not to hide it in all circumstances.

**Comment by torkelo** [comment]
kiosk mode was not really designed for interactivity, which is why menus, panel resize, dashboard header is hidden. 

But please vote up this issue: https://github.com/grafana/grafana/issues/15546

**Comment by Paul-Reed** [comment]
Such a shame, but thanks for reconsidering...

**Comment by torkelo** [comment]
sorry :( 

maybe we can have a viewstate between kiosk=tv and full kiosk mode but afraid that is too many for one button .

**Comment by Paul-Reed** [comment]
Couldn't it be an option in `Dashboard Settings > Panel Options > Kiosk Mode = Show Variables`
Then users would have the option.

**Comment by lormey** [comment]
Since I upgraded from an old version, I really miss the Links in kiosk mode.
Would be graet, if this option will be reimplemented.

**Comment by muutech** [comment]
@torkelo we are using touch-screen TVs for our dashboards, where this option would be needed, so people can interact with dashboard without the menu :) Thanks!

**Comment by xuhrc** [comment]
it's too bad that can not have variables in tv mode, maybe we can make this an option in preferences

**Comment by Nemecsek** [comment]
@xuhrc trick works, thank you!
But the issue should be addressed anyway. Removing features that people are using is never a good idea.

**Comment by gbnj2004** [comment]
> Could the decision 'not implemented' in [this closed issue](https://github.com/grafana/grafana/issues/15546) please be reviewed.
> 
> It seems very unfortunate that users cannot use **kiosk mode** and **Dashboard links** at the same time.
> Both are great features, and using kiosk mode on a large monitor looks great, but cannot be used because the Dashboard links are hidden, and therefore viewers cannot select alternative dashboards.
> 
> It's worth mentioning that the original request made in #7691 was for an **optional feature** to be added to hide the menu in kiosk mode, and not to hide it in all circumstances.


1.append `.view-mode--kiosk .panel-info-corner--links{	display: flex !important}`  to the end of grafana.dark/light.xxxxxxxxxxxxxxxx.css
2.restart grafana, then  you can see Dashboard links  in kiosk mode

**Comment by DonatoD** [comment]
With Grafana 8.0.3 this solution of adding the code at the and of the dark/light css doesn't seem to work anymore. Please Grafana team, add this feature. In the meantime what could be the workaround?
Thanks

**Comment by jackysupit** [comment]
I can't believe that someone made a decision to remove a feature that is being used by many people, without any alternative solution for it. What a same 👎

**Comment by gbnj2004** [comment]
> I can't believe that someone made a decision to remove a feature that is being used by many people, without any alternative solution for it. What a shame -1

look at this  issue #15546  .  I  try  the  solution  of  adding  the  code at  the  end  of  css file  with  grafana  v7.15.6 ， It  does  work.
