### ISSUE TITLE
[UI]: Datasource edit page - URL tooltip overlaps user input

### ISSUE THREAD

**Issue by m-a-leclercq** [grafana/grafana#15771]
### What Grafana version are you using?
6.0.0 but is true for older versions of Grafana also
### What datasource are you using?
ElasticSearch 
### What OS are you running grafana on?
RHEL 7.1
### What did you do?
View Grafana Datasource
### What was the expected result?
Being able to read correctly a long url ending with a specific port number
### What happened instead?
the last portion of the URL is hidden behind the `fa-info-circle` icon

Hi,
First of all thank you for bringing this amazing software to us. 

I have a few suggestions for the datasource UI that could improve it in my opinion. 

The `fa-info-circle` icon location in some fields can be problematic.

ex: We use a proxy in front of several Es clusters and route the datasource to the correct cluster using the same URL but a different port. Whenever I'm looking at the URL field, what I'm really interested in is the port used, and since our URLs are quite long, the port number overlaps with the question mark. 

![image](https://user-images.githubusercontent.com/13354100/53746879-63b5e580-3ea2-11e9-996c-a0b5131f3cc1.png)

This makes it quite difficult to read. 

I've also noticed the location is inconsistent between fields. Sometimes they are in the `gf-form-label` and other times they are in the `gf-form-input`. I understand this was done  to prevent the mouseover tooltip from hiding other fields and text. If you don't want to move it to the label maybe it could be moved outside of the  form-input to avoid my predicament :) 

Thank you !

**Comment by torkelo** [comment]
thanks for reporting this!
