### ISSUE TITLE
First step to improve search

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#15772]
### Motivation
This issue can be seen as a first step to improve the dashboard search(see #15257). 
Currently the search has two search inputs: one for name and one for tags. This is not optimal and makes it more complicated to find a dashboard. If one writes the name of a tag in the find by name input it won't find dashboards with that name.
The search also returns its result in their folders which leads to a weird order of the result.  

### My suggested solution
Simply have one search input with a list of the most popular tags under it. The tags list will be filtered when one uses the search input. The search result should only be listed dashboards. 
I also suggest we remove add new dashboard and having search focused on changing dashboard. 
Lastly we should show dashboard description when hovering item. This will make it easier for users with many dashboards with similar names. 

<img width="1440" alt="screenshot 2019-03-04 at 17 41 33" src="https://user-images.githubusercontent.com/23470681/53748124-00798280-3ea5-11e9-8e32-5bdf03241178.png">

<img width="1440" alt="screenshot 2019-03-04 at 17 42 54" src="https://user-images.githubusercontent.com/23470681/53748144-0a9b8100-3ea5-11e9-991f-e3ef49caa86d.png">

<img width="1440" alt="screenshot 2019-03-04 at 17 43 03" src="https://user-images.githubusercontent.com/23470681/53748158-125b2580-3ea5-11e9-99e4-33fbd1023243.png">

**Comment by torkelo** [comment]
Can you link it to the big search issue & add some labels?

**Comment by torkelo** [comment]
related to this https://github.com/grafana/grafana/issues/15257

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)
