### ISSUE TITLE
Shared Cross Hair - Show tooltip on all graphs

### ISSUE THREAD

**Issue by JoyceBabu** [grafana/grafana#1578]
It would be a useful addition to have an option to show display tooltips on all graphs when shared cross hair is enabled. This is a feature available in NewRelic dashboard and I find it extremely useful. This feature can help in
- Analysing relation between events (anomalies) in different graphs. For example, how did an increase in requests/second affect server memory usage and CPU load
- Comparing similar graphs. For example, I have a graphs comparing performance of different CDN services. Currently to compare the performance of 2 different services at a particular time, I have to hover over both graphs one after the other.

**Comment by toni-moreno** [comment]
:+1

**Comment by torkelo** [comment]
good suggestion

**Comment by wilshire461** [comment]
:+1:

**Comment by cboggs** [comment]
:+1:

**Comment by marinonjalsson** [comment]
:+1: 
Very usefull.

**Comment by Dieterbe** [comment]
+1

**Comment by mtanda** [comment]
+1

**Comment by sbarale** [comment]
+1

**Comment by Dieterbe** [comment]
shared crosshairs are supported now. not sure if anything left to do here (did you mean tooltips as in crosshair, or did you mean annotations, @JoyceBabu ?)

**Comment by JoyceBabu** [comment]
Thank you @Dieterbe. By tooltips I meant crosshair.

**Comment by Dieterbe** [comment]
going to close this then. in dashboard settings there's an option to enable shared crosshairs. you can also just press control-o at any time in any dashboard and it'll toggle the setting. try it out! :)
you may need to upgrade to the latest 2.5 release though.

**Comment by toni-moreno** [comment]
Hi @Dieterbe , I think you don't understand what @JoyceBabu is asking for.

He means to a way to show all tooltips following the mouse time line at once while crosshair is enabled ( perhaps by pressing shift or ctrl , while moving mouse over one panel, not only show the cross-hair also enable all tooltip values at once.

I suggest reopen this issue.

**Comment by Dieterbe** [comment]
i see.

**Comment by gbrian** [comment]
Hi,
Is anybody working on? I'd like to help or try myself if not, I really need this.

Also I'd like to add multiple tooltips to be able to freeze the tooltip on different points and compare.
Maybe by pressing "Ctrl+...." key while showing tooltip it can keep an snapshot so you can move to another point and compare values. Pressing same combination will clear out.

**Comment by gbrian** [comment]
Testing first version. 
Will work only with "All series" tooltips.

![image](https://cloud.githubusercontent.com/assets/767180/12371243/628708ec-bc2d-11e5-8a1f-7c481157ae9b.png)

**Comment by utkarshcmu** [comment]
+1

**Comment by marinonjalsson** [comment]
+1


On Sat, Jan 16, 2016 at 7:49 AM, Utkarsh Bhatnagar <notifications@github.com

**Comment by torkelo** [comment]
This is now merged to master via this PR https://github.com/grafana/grafana/pull/6274, with some changes. 

The feature is using the sharedCrosshair option (renamed in UI to Shared tooltip), and the same shortcut (CTRL+O, or CMD+O)

**Comment by towolf** [comment]
@torkelo this does not work for me. Shared crosshair worked for me. But with really *dense* dashboards, I get overlapping tooltips all over the place, and browser performance is crap, when they pop up all over the place, it's almost grotesque :crying_cat_face: 

Please revise this to pop only with a key modifier only.

**Comment by gbrian** [comment]
Hi,

What about been able to "pin" thos values you are interested on?
This option will be available when you move over the tooltip.

![image](https://cloud.githubusercontent.com/assets/767180/20956187/ae31f7a4-bc48-11e6-8969-66281fa79e36.png)

**Comment by RichiH** [comment]
A modal tooltip which can itself be mouse overed is an absolute UX no go.

Richard

Sent by mobile; excuse my brevity.

**Comment by Dieterbe** [comment]
@gbrian what exactly would the pinning do?

**Comment by gbrian** [comment]
@Dieterbe 
This is taken from code editors that allows you to fix variable values while debugging.
When you move over the tooltip, with the reference value, a "pin" icon appears allowing you to keep this pinned with the name of the reference and its value always visible.
In case of comlex objects you can pin main reference on internal ones indiviadually so you keep focus on what's your interest.
You have to "unpin" when you are done.

I think same approach can help as you will be able to pin whole tooltip or metrics.
Maybe is agood idea to pin everything into same tooltip instead having multiple tooltips but not sure. Maybe some mockups can help on answering.

Hope this helps.

**Comment by RichiH** [comment]
So what happens when I move the mouse cursor to the right while I am
following the graph and mouse over the tooltip? Do I have to move the
mouse back over graph and around the tooltip?

**Comment by gbrian** [comment]
@RichiH The pinned window can be positioned. On the case of code editor its independant from the tootips, so can you put on side, top, down, ... and close when not needed. 

In the picture:
* Overview of the current value (gray tooltip)
* Pinned values (yellow window)

![image](https://cloud.githubusercontent.com/assets/767180/20975175/ec6a2bd0-bc9e-11e6-85e6-c7d40886740e.png)

**Comment by aleksandr-vin** [comment]
+1 for "to pop up only with a key modifier"

**Comment by ariofrio** [comment]
This keyboard shortcut doesn't work on Safari. Cmd-O is always "File > Open File...". Can a different shortcut key be used on Macs?
