### ISSUE TITLE
Refactoring error handling during dashboard creation

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#15788]
We could probably simplify this by refactoring in usage of interfaces. Not sure we want to do that though considering we don't use it anywhere else in the code yet.

https://github.com/grafana/grafana/blob/1711622effe003db26a2ace3a93578253ecffdea/pkg/api/dashboard.go#L236-L247

**Comment by torkelo** [comment]
yes, could maybe be done with the generic ValidationError type that is used in a few places (Alerting I think)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by bergquist** [comment]
It's a good idea. But I wonder if we should keep issues like this open? 

I dont want to discourage people to write down potential improvements to the code base. I want to encourage it. But unless we fix them I feel like its... just information overload that doesn't help us. I'm torn. @xlson @torkelo how do you feel about it?

**Comment by xlson** [comment]
I think you have a point, it definitely makes sense to close issues like this after a while. I labeled this as beginner friendly, which I think makes it worth keeping open.
