### ISSUE TITLE
Error message not shown in error popup

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#15782]
In Grafana 6.0, only the error title is shown in the error message toast (popup). This is due to a refactoring bug [here](https://github.com/grafana/grafana/blob/dd0afd0a0beae53d0bdaa8232811862cf17d49da/public/app/core/utils/errors.ts#L14) where the function returns null if the error message is a string.

**Comment by torkelo** [comment]
Good catch, my fault :(
