### ISSUE TITLE
Grafana 2 - Drill down is not working in graph panel

### ISSUE THREAD

**Issue by JoyceBabu** [grafana/grafana#1579]
I have installed Grafana 2 using the docker container. I have imported all my dashboards and it is working correctly. I like it better than Grafana 1.

The dill down option is not working when clicking on the link in the drop down menu. The link is correct and if I open the link in a new window it works. But clicking on the link takes me to another url.

**Comment by torkelo** [comment]
@JoyceBabu Thank you so much for opening this issue, will fix it later today!

**Comment by torkelo** [comment]
fixed, and docker container updated!

**Comment by JoyceBabu** [comment]
Thank You.
