### ISSUE TITLE
Add the ability to apply rules on values returned for template variable

### ISSUE THREAD

**Issue by vijaykas** [grafana/grafana#15809]
This is not a bug but a feature request.

I would like the ability to apply rules on values returned for template variables, similar to what we have in "Column Styles" option in Table panel.

Example:
My dashboard has a template variable with query to retrieve tag values from a bucket (using Flux data source). Values coming from the query looks like,

urn:RegionInfo:5e9e776a-e78d-4a40-9f43-0fe719fja6ga_52wa5e5c-4784-4640-a935-0f61d24887ed_Region_EU-1
urn:RegionInfo:7e69776a-e88d-4a00-9f43-0fe719lka6ga_52wa8o5c-4484-4690-a915-0f61d24887ed_Region_EU-2
urn:RegionInfo:5e3h776a-e68d-8a40-5f63-0fye719fjj6ga_62waye5c-4h84-4940-a775-0f61d24887ed_Region_EMEA-1
.
.
etc

I would like to retain these values as I need them in my queries to filter stats in panels but change the display to something meaningful to the user of dashboard, something like change "urn:RegionInfo:5e9e776a-e78d-4a40-9f43-0fe719fja6ga_52wa5e5c-4784-4640-a935-0f61d24887ed_Region_EU-1" to "Finland"

Regex in Query Options provides ability to filter the results but I would like Styling option by applying rules to template variable.

Please include this information:
### What Grafana version are you using?
v5.3.3
### What datasource are you using?
Flux
### What OS are you running grafana on?
Windows

**Comment by torkelo** [comment]
think your looking for something like this https://github.com/grafana/grafana/issues/1153 , a way to map ids to display text.

**Comment by vijaykas** [comment]
Thanks looking in to this. I search more for relevant issue, what I was looking for is this #1032
