### ISSUE TITLE
Setting AWS Credentials for CloudWatch through env variables not doing anything

### ISSUE THREAD

**Issue by tinaboyce** [grafana/grafana#15813]
I tried to run a Docker container with a command similar to http://docs.grafana.org/installation/docker/#configuring-aws-credentials-for-cloudwatch-support hoping it will add a CloudWatch datasource but when logging in for the first time, the web interface acts like I don't have any datasource and have to manually add my own.

Is this link I have referred to above meant to be to create a datasource? or does it serve a different purpose?

### What Grafana version are you using?
Docker grafana/grafana:latest

### What datasource are you using?
CloudWatch

**Comment by torkelo** [comment]
that docs article is only about adding credentials to the container so that cloudwatch SDK can authenticate against AWS, you still have to add the Cloudwatch data source.
