### ISSUE TITLE
Create keyboard shortcut to scroll through template variables

### ISSUE THREAD

**Issue by deepakhj** [grafana/grafana#1581]
We have some template variables that are a long list and it's tedious to click on the drop down and select them one by one via the mouse. Maybe a way to select the drop down and when you scroll via the keyboard, the graph updates as well. There's about 50 values in one of the template selectors.

I suggested creating a scripted dashboard as a workaround.

**Comment by torkelo** [comment]
You can use the keyboard arrows already to select the template variables. But I do not think updating the whole dashboard when an template variable is highlighted in the dropdown list, that will make navigating the list very slow and slugish
