### ISSUE TITLE
Grafana accepting two different passwords for a single user

### ISSUE THREAD

**Issue by saurabh3896** [grafana/grafana#15817]
Please include this information:
### What Grafana version are you using?
5.1.3
### What datasource are you using?
Not related
### What OS are you running grafana on?
Linux Ubuntu 18.04
### What did you do?
Configured Grafana to accept users by specifying an LDAP configuration file (ldap.toml). Then, tried changing (updating) the password of a user using the Admin API (sent a simple curl PUT request).
### What was the expected result?
Password should have been updated.
### What happened instead?
Instead, allows both old and new password.
 
Note: Another similar issue is that I am not able to update the role (change it from Viewer to Admin) using the GUI (http://grafana.server.com/org/users). Once I log out from the target account, the role switches back to Viewer from Admin automatically. Updates are not being retained.

**Comment by torkelo** [comment]
When configuring LDAP , the role is updated based on your ldap group to role settings. See this FR to change this: https://github.com/grafana/grafana/issues/6907 

Enabling LDAP does not disable Grafana user password login. Grafana will first try to login a user using user & password stored in Grafana's DB, if that does no succeed LDAP is tried.  

You cannot change LDAP password via Grafana.
