### ISSUE TITLE
Support zoom / time range selection for panels with timeshift

### ISSUE THREAD

**Issue by gbalbinot** [grafana/grafana#15829]
### What Grafana version are you using? 
6.0.0

### What datasource are you using?
POSTGRESQL 10 with TIMESCALEDB

### What OS are you running grafana on?
CENTOS 7.1

### What did you do?
I set TIMESTAMP preferences to UTC both in the user preferences and in the dashboard settings. The time is displayed correctly in regards to what is on the database. Everything is fine. I use the mouse to select a slice, then it shows 3h before. For example, there is data from 08:00 am to 11:00 am, then I select 09:00am to 10:am, it then shows 06:00am to 07:00am.

### What was the expected result?
That the slice selected would correspond to the initial selecion.

### What happened instead?
The period selected is 3h ealier, which is exactly the timeshift I selected.

Step by step
![1](https://user-images.githubusercontent.com/23661922/53889260-6a6d6580-4026-11e9-9288-15623c2ab97f.PNG)
![2](https://user-images.githubusercontent.com/23661922/53889259-69d4cf00-4026-11e9-8760-b4d6dcc399f2.PNG)
![3](https://user-images.githubusercontent.com/23661922/53889258-69d4cf00-4026-11e9-8b92-21d7307bd9f5.PNG)

Configuration: 
![4](https://user-images.githubusercontent.com/23661922/53889435-bae4c300-4026-11e9-9843-57e98a63105c.PNG)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
