### ISSUE TITLE
Time picker for the charts

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1582]
Hi Torkel:

Is it curently possible to set each charts time span refresh type differently so that they don't all update all the time and on some charts I may want to look at longer historical data than others on the same dashboard. 

If this is not available, how much work would it be to make this work?
![time_picker](https://cloud.githubusercontent.com/assets/3009225/6588497/19ce3a44-c769-11e4-8ee1-98c5af6a8fc2.png)

**Comment by gsaray101** [comment]
Custom Time Range for each chart?

**Comment by torkelo** [comment]
This already possible (to a limited extend in Grafana 2.0 (develop branch), https://github.com/grafana/grafana/issues/171

You can override relative time on each panel, and set a timeshift as well. You cannot override dashboard refresh interval, or set absolute time.
