### ISSUE TITLE
Support selecting all filtered values of multi-value variable 

### ISSUE THREAD

**Issue by aurimasplu** [grafana/grafana#15821]
Hi,
When using Multi-value variable we need option to select all displayed variables.
For example in variable drop down I write some string to display matching variables and when I would like to select all displayed variables by one click (not one by one as it is now). 
Its not a problem when I can filter to for example three variables, but the need to select one by one 20 or more variables it gets problematic.
Interesting enough, deselecting all works now just fine.

![image](https://user-images.githubusercontent.com/33485896/53879321-d3e57800-4016-11e9-8f59-5f17052238a2.png)

**Comment by torkelo** [comment]
There is an option int the variable option to include an "All" option. 

![image](https://user-images.githubusercontent.com/10999/53899897-84fe0980-403b-11e9-9992-a949a6039520.png)

**Comment by marefr** [comment]
No this is for when you have filtered results then `All` is not shown.

**Comment by torkelo** [comment]
ah, sorry misunderstood

**Comment by agtinternational** [comment]
Would be really nice !
