### ISSUE TITLE
Instead of displaying 'Shared tooltip error' text failback to default per-metric tooltip display

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1583]
Anyone building dashboards with shared tooltips has most likely seen:
![image](https://cloud.githubusercontent.com/assets/917241/6592245/7417a21c-c7cb-11e4-98ea-9b59c77aae8b.png)

Modifying null point mode is oftentimes undesired, especially if it is a sporadic issue (like last data point for some metric is coming 2 seconds later). 

How about just failing back to the default per-metric tooltip instead of throwing the error?

**Comment by torkelo** [comment]
this is already fixed in Grafana 2.0 (develop branch), there the shared tooltip feature works even when metric series are of different resolution (different point counts)
