### ISSUE TITLE
Support ad-hoc filters in Prometheus

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#15831]
As of Grafana 6.0.0  Ad-Hoc Filters are not supported in Prometheus, while they can be quite useful in large environments and it looks like there is already a lot of work done in Explore UI to help to discover available labels etc. 

![image](https://user-images.githubusercontent.com/3651746/53892515-704d5180-3ffa-11e9-9a80-0dd858d167c6.png)

I can currently simulate some of such ad-hoc filtering by adding some additional Text Box variable but I have to make it quite user unfriendly to work:

![image](https://user-images.githubusercontent.com/3651746/53892657-b2769300-3ffa-11e9-9849-17bc0be036fd.png)

I either require user to start with the coma or need to have default expression in text box which is always true.

**Comment by mtanda** [comment]
@PeterZaitsev Hi, It will be supported in v6.1.
https://github.com/grafana/grafana/pull/15290

**Comment by daniellee** [comment]
As @mtanda says, closed by #15290.
