### ISSUE TITLE
Max and Average value of a metric differs between Graph and Singlestat

### ISSUE THREAD

**Issue by anandkshitiz** [grafana/grafana#15843]
Please include this information:
### What Grafana version are you using?
Grafana v5.2.1 (2040f61)
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
MacOS Mojave
### What did you do?
I am trying to calculate average latency of server requests.
### What was the expected result?
Average value should match between Graph and Singlestat
### What happened instead?
Singlestat shows incorrect average value.
I think it is because Singlestat is querying very less data points. 
I tried to modify the number of data points collected by going to Singlestat's metric -> right side -> Options -> (default 30m) changed it to 2m. But it doesn't work as the query still uses the default 3m step.

<img width="1618" alt="screen shot 2019-03-07 at 6 31 01 am" src="https://user-images.githubusercontent.com/23467894/53924688-0e94f200-40a3-11e9-9380-27378d20c4a5.png">
<img width="1595" alt="screen shot 2019-03-07 at 6 33 57 am" src="https://user-images.githubusercontent.com/23467894/53924689-0e94f200-40a3-11e9-90b2-5f5d5716fc0a.png">

**Comment by torkelo** [comment]
Yes singlestat usually requests less data points (for a gauge it only needs 1 really). 

Avg is calculated by
