### ISSUE TITLE
Grafana Error 1040: Too many connections

### ISSUE THREAD

**Issue by darrengeek** [grafana/grafana#15844]
### What Grafana version are you using?
Grafana 5.4.3
### What datasource are you using?
Prometheus 2.3.2
Grafana stores：MySQL 5.6
### What OS are you running grafana on?
Docker

### What happened instead?
`t=2019-03-07T09:47:06+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=3 error="Error 1040: Too many connections"

t=2019-03-07T09:47:06+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=13 error="Error 1040: Too many connections"

t=2019-03-07T09:47:06+0800 lvl=eror msg="Failed to save state" logger=alerting.resultHandler error="Error 1040: Too many connections"
....
`
### Part of the grafana.ini file, sensitive information is indicated by *:
`
[server]
    ;protocol = http
    ;http_addr =
    ;http_port = 3000
    domain = grafana.****.com
    ;enforce_domain = false
    root_url = %(protocol)s://%(domain)s/
    ;router_logging = false
    ;static_root_path = public
    ;enable_gzip = false
    ;cert_file =
    ;cert_key =

    [database]
    type = mysql
    host = ***********************
    name = grafana-prod
    user = grafana
    password = *************
    max_open_conn = 250

`

### Issue?
Grafana stores：MySQL 5.6  max_open_conn is set to 250，Observe that the number of mysql connections is usually around 15 and does not exceed the set value of 250.
Why is the error 1040: Too many connections, is the connection limit of grafana and other places, such as the number of panels, etc.
How to solve it? Thank you

**Comment by bergquist** [comment]
Might be due to peaks. Are you storing session data in MySQL as well?
Do you have many alert rules with very aggressive interval?

In 6.0 we rewrote the auth to be more performant but only rely on the database. Any chance you can try it out?

**Comment by darrengeek** [comment]
I have upgraded grafana: 6.0.0, but the problem persists.
Yes. The session is also in the database. We have this situation after adding hundreds of monitoring panels.

sensitive information is indicated by *
`[session]
    provider = mysql
    provider_config = grafana:****@tcp(*****:3306)/grafana-prod
    cookie_name = grafana_sess
    cookie_secure = false
    session_life_time = 86400`

There is still a problem Grafana Error 1040: Too many connections But the panel monitors the alarm but does not receive any alarm messages. This should be after grafana gives an error and no alarm to the panel.
`t=2019-03-08T14:19:04+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=3 error="Error 1040: Too many connections"

t=2019-03-08T14:33:18+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=13 error="Error 1040: Too many connections"

t=2019-03-08T14:43:20+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=8 error="Error 1040: Too many connections"

t=2019-03-08T14:43:20+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=3 error="Error 1040: Too many connections"

t=2019-03-08T14:52:12+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=8 error="Error 1040: Too many connections"

t=2019-03-08T14:52:12+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=8 error="Error 1040: Too many connections"

t=2019-03-08T14:52:12+0800 lvl=eror msg="Could not get notification state." logger=alerting.notifier notifier=23 error="Error 1040: Too many connections`

**Comment by marefr** [comment]
@darrengeek if you have a different `wait_timeout` than the default please change `conn_max_lifetime` according to [documentation](http://docs.grafana.org/installation/configuration/#conn-max-lifetime). You may also want to try configure [max_idle_conn](http://docs.grafana.org/installation/configuration/#max-idle-conn)

**Comment by darrengeek** [comment]
@marefr  The Mysql wait_timeout and conn_max_lifetime settings are both 86400.
After I adjusted max_idle_conn to 30, Grafana Error 1040: The number of times has decreased a lot and will be further observed.
Is the number of connections to grafana connected to mysql a connection with one panel?

`
  [database]
    type = mysql
    host = *******:3306
    name = grafana-prod
    user = grafana
    password = ******
    max_idle_conn = 30
    max_open_conn = 250
`

**Comment by torkelo** [comment]
No, but if you have many alert rules then it could be a reason. How often are alert rules evaluated?

Closing this for now until we have more info, does not currently look like problem in Grafana but as there has been no other reports about this.

**Comment by Ivan-Strahovsky** [comment]
I had the issues but the problem was not in Grafana config but in MySQL config. MySQL also has config for max allowed connection https://dev.mysql.com/doc/refman/8.0/en/too-many-connections.html https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_connections. If you have max allowed connection in Grafana set to for example 10 and at the same time have only 5 max connections on the database you will get this error.
