### ISSUE TITLE
InfluxDB templating query always returns timestamp

### ISSUE THREAD

**Issue by fsauer65** [grafana/grafana#1584]
When performing a single column select like 

    select col from series where time > now() - 10s limit 1

or any other query I'm guessing, the result seems to always be the timestamp because the template queries are executed using the InfluxDatasource.prototype.metricFindQuery which does this:

      return this._seriesQuery(interpolated)
        .then(function (results) {
          return _.map(results[0].points, function (metric) {
            return {
              text: metric[1],
              expandable: false
            };
          });
        });

always returning the second column from the result which in this case is a timestamp, not the column requested. I changed this to:

      return this._seriesQuery(interpolated)
        .then(function (results) {
          return _.map(results[0].points, function (metric) {
            return {
              text: metric[metric.length -1],
              expandable: false
            };
          });
        });

to always return the last column value from the result and this not only works, it doesn't seem to break anything else either... I also define a lot of variables using 'list series /someregex/' queries and those still work as well.

**Comment by torkelo** [comment]
You should use something like this: 
```
select distinct(col) from series
```

**Comment by fsauer65** [comment]
thanks, that works
