### ISSUE TITLE
Add timeout option for snapshot creation via HTTP API

### ISSUE THREAD

**Issue by ipasic** [grafana/grafana#15855]
I think it would be helpful to have "timeout" option also when creating snapshot using HTTP API, not only via grafana GUI.  Any plans on that one ?

**Comment by torkelo** [comment]
does not make any sense to have on in the api. as the capturing (that takes  time) is done in the browser. The api is only for saving the snapshot captured in the browser and take no time.

**Comment by ipasic** [comment]
How do you mean it doesn't make any sense? It definitely make sense. I need to generate snapshot urls on the fly programmatically and retrieve URL back to the client. Without timeout this snapshots (which have complex queries behind) are useless because anonymous user (client) would get lot of 401 unauthorized requests when he opens the urls as part of the dashboard couldn't be prepared.
If i generate snapshot of same dashboard within browser (with setting timeout to e.g. 4sec) then when i open the URL it's ok and there are no 401 errors.

I can understand if you want to say you won't implement this feature but you can't say it doesn't make sense. Sharing possiblities for programmatic implementation within custom web apps are limited anyway and this is just one more of those limitations.
