### ISSUE TITLE
Grafana alert not sending images

### ISSUE THREAD

**Issue by erikoffereins** [grafana/grafana#15857]
**What happened**:
The alert rule is sending a default image with it

**What you expected to happen**:
We expected the image of the concerning graph 

**How to reproduce it (as minimally and precisely as possible)**:
Since the latest version it happened

**Anything else we need to know?**:
/

**Environment**:
- Grafana version:
6.0.0
- Data source type & version:
InfluxDB
- OS Grafana is installed on:
Linux
- User OS & Browser:
Windows 10
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
please try latest v6.0.1 it contains a fixe for alert image rendering
