### ISSUE TITLE
Application Insights (Azure Monitor) plugin not showing "Toggle text edit mode" button for first query

### ISSUE THREAD

**Issue by y325A** [grafana/grafana#15858]
**What happened**:
Using the Azure Monitor data source, change the service to Application Insights.

First query is not showing the "Toggle text edit mode" button as below. After duplicating the query, the icon shows on the second query.

![image](https://user-images.githubusercontent.com/33149737/53962776-d6fa6a00-40e3-11e9-99ed-f9529cc39e13.png)

**What you expected to happen**:
Be able to toggle edit mode on the first query.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a new dashboard
2) Use the Azure Monitor data source
3) Change the Service to Application Insights
4) Attempt to toggle the edit mode

**Anything else we need to know?**:
Was previously using the plugin before it became a 1st class plugin.

**Environment**:
- Grafana version: 6.0.1 (0c44a04)
- Data source type & version: Azure Monitor (Shipped with Grafana)
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows 10, Chrome latest & Firefox

**Comment by torkelo** [comment]
We plan to remove this toggle mode so do not plan to fix this. In the meantime switch tab and the pen icon will appear.

**Comment by JamesHealey94** [comment]
> We plan to remove this toggle mode so do not plan to fix this. In the meantime switch tab and the pen icon will appear.

What's the motive behind removing the toggle mode? I find it very useful to write KQL queries (or copy them from existing ones in the Azure Portal)

**Comment by kutny** [comment]
@JamesHealey94 Same question here. Why do you plan to "remove this toggle mode"? I also use KQL queries a lot...

**Comment by sponnaz82** [comment]
@torkelo - We're using enterprise Grafana Version and need this toggle mode. Grafana doc still states to leverage toggle mode to write queries (https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/#writing-analytics-queries-for-the-application-insights-service) however it doesn't render query mode when the pen icon is clicked.

**Comment by torkelo** [comment]
Ok, we will investigate, might have been wrong in my judgment.

The problem is that azure is like 4 different datasources in one, only some services support the raw edit mode. And t

**Comment by kutsyk-neocles** [comment]
Hello,

We are using Grafana to monitor our Kubernetes resources and as we have part of old infra on Azure SaaS, we would like to merge our dashboards into Grafana. So after connecting Application Insight as a data source in Grafana v 6.7.4 I was expecting to be able to write Kusto queries and build a cool dashboard.
But as a result I can't find the "Toggle edit mode" button.

![image](https://user-images.githubusercontent.com/61271706/87426593-b5669800-c5df-11ea-816b-2b4087cb3c3f.png)

The pencil button at the top right corner doesn't show change anything.

Grafana version: 6.7.4
Azure monitor plugins version: 0.3.0
