### ISSUE TITLE
Explore url does not keep query

### ISSUE THREAD

**Issue by Hipska** [grafana/grafana#15862]
**What happened**:
When copying the URL generated by Explore and loading the page, the query field is empty.

**What you expected to happen**:
The query field should be filled with the query retrieved from the url

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to Explore
2. Select Graphite datasource
3. Build query
4. Hit refresh (browser)

**Environment**:
- Grafana version: 6.0.0
- Data source type & version: Graphite 0.9.16
- OS Grafana is installed on: CentOS 7.5
- User OS & Browser: MacOS Safari

**Comment by torkelo** [comment]
yes, was able to replicate this! Thanks for reporting this!
