### ISSUE TITLE
Avoid second as default unit for alerting interval since it can be confusing when using invalid duration units.

### ISSUE THREAD

**Issue by tehlers320** [grafana/grafana#15866]
**What happened**: Users have entered several variants of of frequency including but not limited to
* 6hr
* 24hr
<img width="856" alt="screen shot 2019-03-07 at 3 58 33 pm" src="https://user-images.githubusercontent.com/16598119/53992208-e2549200-40f1-11e9-9ba6-accdd08f79fe.png">

This then sets these alerts to run at "6" second intervals and "24" second intervals creating havok on your backend. 

**What you expected to happen**:
Grafana rejects invalid time or the admin has the ability to set a default if the time doesn't match a valid one. 

**How to reproduce it (as minimally and precisely as possible)**:
create any alert and fill in "6hr" on the alert frequency

**Anything else we need to know?**:
Even if the UI accepts only correct data a hard setting of maximum query frequency is still valuable. Some users do not understand time series send intervals and often try to alert faster than actual data comes in.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: any
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by bergquist** [comment]
The supported unit for hours is `h` so use `6h` and `24h` instead.

**Comment by bergquist** [comment]
Keeping this issue open since we can provide better "error" handling for this.

**Comment by marefr** [comment]
I confirm this is still a problem on version 7.x / master (f7d079c0a54aebf020d5da767900a6cdb64b6332)
