### ISSUE TITLE
cannot find package "github.com/facebookgo/inject"

### ISSUE THREAD

**Issue by seenyea** [grafana/grafana#15869]
**What happened**:
![image](https://user-images.githubusercontent.com/46433320/54002127-88eb7200-4188-11e9-998a-defa54d2db4a.png)

**What you expected to happen**:
can start the go project

**How to reproduce it (as minimally and precisely as possible)**:
1. git clone https://github.com/grafana/grafana.git
2. cd grafana
3. go run build.go setup

**Environment**:
- Grafana version: 6.1.0-pre
- OS Grafana is installed on: Unbutu 16.04

**Comment by bergquist** [comment]
what version of golang are you using?

**Comment by bergquist** [comment]
Seems like you are trying to build grafana outside your GOPATH which won't work at the moment since we depend on dep.

Once we migrated to go modules this will go away. https://github.com/grafana/grafana/pull/15556
Closing this since we won't address anything specific in this issue.
