### ISSUE TITLE
[Bug] strange drawing of large time range

### ISSUE THREAD

**Issue by genofire** [grafana/grafana#15861]
**What happened**:
![a](https://user-images.githubusercontent.com/6905586/53971172-abd04480-40fc-11e9-930c-e579b1a4add9.png)

**What you expected to happen**:
No strange shadow

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
at this area there a less datapoints

**Environment**:
- Grafana version: grafana 6.0.0
- Data source type & version: influxdb 1.7.4-1
- OS Grafana is installed on: debian
- User OS & Browser: Vivaldi
- Grafana plugins:-
- Others: -

**Comment by torkelo** [comment]
looks like your query did not return data properly sorted. What does your query look like and what is the response from InfluxDB?

**Comment by genofire** [comment]
Nope, it is sorted by date correctly:
https://pastebin.com/TAfnthQX

**Comment by torkelo** [comment]
was not able to replicate with the data you sent:

Can you consistently replicate this?

**Comment by genofire** [comment]
Okay, today it works with the timerange of the pastebin.

But yes, i could it reproduce it.
Try it at you own (but please do not DDoS): https://grafana.bremen.freifunk.net/d/000000001/globals?orgId=1&fullscreen&panelId=2&from=1224900825125&to=1541696441027

**Comment by torkelo** [comment]
closing this as there has been no other reports, and must have been something strange with ordering of data.
