### ISSUE TITLE
Changing the order of rows no longer possible

### ISSUE THREAD

**Issue by passing** [grafana/grafana#15860]
**How to reproduce it**:
run docker containers with different versions of grafana
```
docker run -d -p 3004:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Editor grafana/grafana:4.2.0
docker run -d -p 3005:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Editor grafana/grafana:5.4.3
docker run -d -p 3006:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Editor grafana/grafana:6.0.0
```
access grafana:
- Grafana 4: http://localhost:3004
- Grafana 5: http://localhost:3005
- Grafana 6: http://localhost:3006

create a dashboard with multiple rows

only in Grafana 4 you can change the order of rows:
![image](https://user-images.githubusercontent.com/8142186/53964847-5b52ea00-40f0-11e9-84cc-543161ae8bbc.png)

with Grafana 5 & 6 this option has somehow disappeared

**Comment by torkelo** [comment]
collapse row then use drag handle to move it :)

**Comment by passing** [comment]
@torkelo thanks for the quick clarification.
It would be nice if you could improve the visibility / contrast of the drag handle in "dark mode" a bit ... on a cheap TN panel screen it is almost invisible  ;)
