### ISSUE TITLE
Update Dashboard Version History documentation

### ISSUE THREAD

**Issue by aerickson** [grafana/grafana#15863]
http://docs.grafana.org/reference/dashboard_history/

I'm using grafana v6.0.0 (commit: 34a9a62) and the UI looks different from this screenshot. I've searched the UI for a link to dashboard versions and can't find it... where is it now?

Thanks :)

**Comment by marefr** [comment]
@aerickson since Grafana v5.0 you'll find the dashboard versioning by entering dashboard settings and then **Versions** in the left side menu: 

![image](https://user-images.githubusercontent.com/1668778/54017906-b4ba2800-4187-11e9-8231-fb24c9c07b2c.png)
