### ISSUE TITLE
Add a bulk panel management page

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15879]
It would be great to be able to bulk manage multiple panels at once.  With 4x, you could edit the titles all together -- that was great.

I made an angular version #10390, but would need lots of work to get into react.  Here are screenshots to get an idea of possible features: 

![image](https://user-images.githubusercontent.com/705951/34202089-0f9ed284-e577-11e7-9ca1-4f14422dfd28.png)
![image](https://user-images.githubusercontent.com/705951/34202140-2d872332-e577-11e7-80c6-7135d29f8bb2.png)
![image](https://user-images.githubusercontent.com/705951/34202165-3e2d729a-e577-11e7-8b88-74ed1af5eced.png)
![image](https://user-images.githubusercontent.com/705951/34202213-5d9d7a8a-e577-11e7-92ec-0213e1e3810b.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
