### ISSUE TITLE
Azure Monitor Variables $__from and $__to are returning number instead of datetime

### ISSUE THREAD

**Issue by pfritschi** [grafana/grafana#15871]
**Description**
After the upgrade form Grafana 5.4.3 to 6.0.1, some of the panels that are using Azure Monitor as data source stopped working. 

After some research I found out that the variables `$__form` and `$__to` are returning a number and Azure Log Analytics cannot convert that to a datetime. A possible workaround was to replace all `$__from` variables with `datetime_add('Millisecond',$__from,todatetime('1970-01-01T00:00:00')` in the query editor.

Is it possible that the new global `$__from` and `$__to` are overwriting the local variables?

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce the problem simply replace in a working query, eg.
```
Perf
| where ObjectName == "Processor" and CounterName == "% Processor Time" 
| where $__timeFilter(TimeGenerated)
| summarize avg(CounterValue) by Computer, bin(TimeGenerated, 10s)
| order by ComputerName asc,TimeGenerated asc
```
the `$__timeFilter(TimeGenerated)` with `TimeGenerated >= $__from`. This should, in theory, give you the same result (tested under Grafana 5.4.3) but it returns the error message `Arithmetic expression cannot be carried-out between I64 and TimeSpan` in Grafana 6.0.1.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Azure Monitor Datasource (Azure Log Analytics)
- OS Grafana is installed on: Ubunut 18.04
- User OS & Browser: Windows 10 & Chrome/Firefox/Edge
- Grafana plugins:
  - AJAX Panel
  - Multistat Panel
  - Pie Chart Panel
  - Zabbix
  - worldPing
  - Azure Monitor (before Upgrade)

**Comment by torkelo** [comment]
$__from and $__to are global grafana variables that currently only support formatting to unix epoch milliseconds. Useful if you want to generate links to other dashboards or systems that do support this format.
