### ISSUE TITLE
Default/original grafana files output weird stuff (and not the basic dashboards)

### ISSUE THREAD

**Issue by jmakucka** [grafana/grafana#1587]
Installed grafana on one of my droplets (by pointing nginx to the grafana src folder where the index.html files are stored). I haven't modified any of the grafana files, however when I navigate to the website, it outputs some weird stuff: a button appears with alert.title underneath and if you wait a few seconds, it then changes to the following page:
![screenshot](https://cloud.githubusercontent.com/assets/615930/6607165/14c82442-c813-11e4-9997-bea4007fe9b4.PNG)

**Comment by torkelo** [comment]
src folder? The release packages here http://grafana.org/download/  do not contain a src folder. 

Have you just cloned the repository?  

Please read the install & config instructions :)
http://docs.grafana.org/installation/

And if you are running from master (the source and not a release package), then you need to read the instructions for how to run from master: 
http://docs.grafana.org/project/building_from_source/ 

Cheers!
