### ISSUE TITLE
Grafana lost Datassources and all dashboards allready setup

### ISSUE THREAD

**Issue by awiltschek** [grafana/grafana#15888]
Tried to config smtp and restarted grafana servicem which wasnt successfull as no mail was end out.

Suddenly grafana doesnt show up with datasource tab any more and all dashboards have been deleted.
I am logged in as admin.
even reinstallation of grafana doesnt change anything. So server is now dead for me.

Version 5.4.3 on a raspi with influxdb config worked fine until i tried to make smtp work.

![Zwischenablage02](https://user-images.githubusercontent.com/30444269/54073257-62f7c780-4285-11e9-97e7-625bb356c1d9.jpg)

**Comment by torkelo** [comment]
How did you run / install grafana? What’s your config and what grafana db did you use? (SQLite/MySQL/Postgres) any backup of the db? 

Any grafana server logs from her you restarted Grafana?

**Comment by awiltschek** [comment]
i solved the problem by totally deleting everything which contains grafana in its filename from the harddisk. afterwards it was clean installed successfully again.
so your uninstallation is not realy successfull. the config was somehow vilolated. and i dont know which db grafana uses. it connected grafana with influxdb where my data is stored.
