### ISSUE TITLE
HTML mode shows up error

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#15883]
Hi Team,

I've been using grafana for like more than 5 months and it works amazingly well.
I have recently updated the grafana to v6.0.1 and HTML mode shows up some error. 
The same was working well in v5 of the grafana.

Here are the images of v5 and v6 

This is version 5
![v5](https://user-images.githubusercontent.com/22325249/54044519-2a101200-41f5-11e9-940e-c4a8cbd030d7.PNG)

This is version 6.0.1
![v6](https://user-images.githubusercontent.com/22325249/54044553-3eeca580-41f5-11e9-9dbe-5b0474af9e0d.PNG)

**Comment by torkelo** [comment]
Html mode in text panel is sanitized by default as allowing any html and scripts is very insecure (if you do not trust your users).

You can disable sanitizer in the server config file. Search docs for sanitize and you will find config option (or the v6 changelog / release notes)

**Comment by Siddhu1096** [comment]
Thanks my life saver!! @torkelo
