### ISSUE TITLE
Links in annotations?

### ISSUE THREAD

**Issue by hwangroman** [grafana/grafana#1588]
Hello,

I'm curious if links have been already implemented in annotations?
I see that it was mentioned here: https://github.com/grafana/grafana/issues/394#issuecomment-49548937 , but I could not find any other information regarding it.

Thanks
Roman

**Comment by torkelo** [comment]
No they havent :(  I would love to add this. But need to tweak the tooltip lib or exchange it to make the tooltips stick so you can hover over them.

**Comment by hwangroman** [comment]
Ok, thanks for update. Will look forward for that functionality.

**Comment by mtanda** [comment]
+1

**Comment by einsiedlerkrebs** [comment]
hi, 

first a short: "thanks for grafana"

sencondly a +1.

cause i would also love to have a clickable link in the annotations. 

Thanks

**Comment by m4dc4p** [comment]
+1

**Comment by akrus** [comment]
+1

**Comment by torkelo** [comment]
Finally now have much better tooltip/popover lib that can handle this scenario!

Merged to master
![annotation_links](https://cloud.githubusercontent.com/assets/10999/13244830/928ab8a0-da09-11e5-8ce9-676ee55bcce8.gif)

**Comment by mtanda** [comment]
Nice work! :+1: :+1: :+1:

**Comment by hwangroman** [comment]
Awesome, thanks

**Comment by einsiedlerkrebs** [comment]
YES!. Nice thanks a lot!

**Comment by m4dc4p** [comment]
@torkelo Can you reference the PR containing this update?

**Comment by volter** [comment]
Can you explain how the hyperlink is created?

**Comment by torkelo** [comment]
Its a simple link / anchor element in the annotation description field

**Comment by volter** [comment]
So, this is a place where HTML is interpreted then?

**Comment by torkelo** [comment]
@volter no, that is handled by the browser

**Comment by volter** [comment]
I should have said, it's not sanitized or escaped, like it was discussed for #3673.

Thank you for clarifying it!

**Comment by torkelo** [comment]
It is sanitized by grafana

**Comment by deepujain** [comment]
I could not find the way to test link with Annotation on 3.0 beta 1 released during April

**Comment by torkelo** [comment]
? 
Try having an annotation with text containing an anchor

**Comment by chigurupati** [comment]
Hello @torkelo 

I don't no how to add link with Annotations in 3.0 beta during april.

What do you mean by "annotation with text containing an anchor"? Do you mean while giving name to the annotation? 

Moreover when I click on the new to create a new annotation it gives me the below error.
![capture](https://cloud.githubusercontent.com/assets/11277338/14426161/25c157a6-ffed-11e5-9acd-18281920c29d.JPG)

Thanks,
Amar.

**Comment by torkelo** [comment]
do you have any data sources defined? Are any of them marked as default?

**Comment by chigurupati** [comment]
yes, I do have influxdb data sources but none are set as default.

**Comment by torkelo** [comment]
please set one as default, this is required (but not enforced in the UI / backend, which it should be)

**Comment by chigurupati** [comment]
ok thanks. I have set the default DS. 

Now that the plugin is cleared, where do I add the link in annotations? 

![capture](https://cloud.githubusercontent.com/assets/11277338/14431406/ce09d2ea-0005-11e6-85ad-56529cfdabb7.JPG)
