### ISSUE TITLE
Legends overflow but no scrollbar

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#15895]
**What happened**:
A graph has a legend with a very wide column. The content is clipped by the right edge of the panel.

**What you expected to happen**:
A horizontal scrollbar appears so I can see the full contents of the legend.

**How to reproduce it (as minimally and precisely as possible)**:
Define a graph with a legend that ends up pretty wide. Size the graph panel to be smaller than the width necessary to fully display the legend.

![Screenshot from 2019-03-10 22-55-28](https://user-images.githubusercontent.com/569574/54092038-4344ca00-437f-11e9-8b5e-6c083c2b3ee8.png)

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: Ubuntu 18.04 & Docker CE 18.09.3
- User OS & Browser: Arch Linux & Firefox 65
- Grafana plugins: Cloudflare, Worldmap
- Others:

**Comment by torkelo** [comment]
This scenario is not supported, we have a feature request to support horizontal scrollbars, https://github.com/grafana/grafana/issues/8291   but the demand has not been very high
