### ISSUE TITLE
Page Up/Down & Home/End don't behave as expected

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#15894]
**What happened**:
I pressed the "end" key on my keyboard, the page moved a few pixels down. Pressed End more, moved down by a few pixels, but more than the first time. Pressing End again and again scrolls down and seems to accelerate towards the middle of the page and then decelerates towards the end of the page.

The acceleration/deceleration is mostly random, and very often results in stuttering. It appears related to graphs entering/exiting the view. However, it consistently decelerates when one is nearing the top or bottom of a page.

Home, Page Up and Page Down exhibit the same behaviour.

**What you expected to happen**:

1. When pressing End, it should jump to the bottom of the page
2. When pressing Home, it should jump to the top
3. When pressing Page Up/Down it should move the page by the same amount every time, roughly half the screen.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard that's bigger than what fits on your screen, for example the Prometheus Node Exporter dashboard and expand a few sections.
2. Use any of the keys as described above.

**Anything else we need to know?**:

Without clicking outside of a graph, but inside of a dashboard the first time around, Home/End and Page Up/Down don't work at all. I would expect them to be bound to `.scroll-canvas .scroll-canvas--dashboard` and work when a dashboard is loaded without additional fidgeting from my side.

I filed this as a bug as I consider this behaviour to run counter to how Home/End and Page Up/Down normally behave in any app. The scrolling acceleration/deceleration is particularly annoying from my point of view b/c it forces me to mash on my keys a bunch. Scrolling using the mouse is unaffected.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: Ubuntu 18.04 LTS, Docker CE 18.09.3
- User OS & Browser: Arch Linux & Firefox 65
- Grafana plugins: Cloudflare, Worldmap

**Comment by torkelo** [comment]
Yea, need to fix this. You can work around by clicking anywhere on the page (under header). To make it get focus. then the page up / down & end will work.

**Comment by daenney** [comment]
Once you get the focus right the keys will start to react, but they still behave weirdly. Home/End don't jump to top and bottom and you get the acceleration/deceleration feature as you're nearing the top/bottom of the dashboard.
