### ISSUE TITLE
Time regions description 

### ISSUE THREAD

**Issue by sysrek** [grafana/grafana#15898]
**What would you like to be added**:
- Adding description field to each Time window. This Description should be displayed on the chart panel. 

**Why is this needed**:
There is possibility to mark time region, but there is no possibility to describe what was happen during this time slot.  Information will be helpful to better chart description. 
Sample descriptions: Maintenance, Upgrade, Backup time,

**Comment by torkelo** [comment]
Are you talking about annotations? Region annotations can have a description & tags.

**Comment by torkelo** [comment]
you can hold down shift and mark/drag a time region on any graph, then you can specify description & tags.

**Comment by sysrek** [comment]
Annotations are something different from time regions. 
I use it in automation and clicking on the chart is impossible. 
I create dashboard from CLI with preparing JSON file.

**Comment by sysrek** [comment]
I am talking about something like this. 
![TimeRegionsDescription](https://user-images.githubusercontent.com/48356350/54128782-1939e900-440d-11e9-8202-3c28b2385501.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
