### ISSUE TITLE
Playlists not working in grafana2?

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1589]
Playlists do not work for me in grafana 2 (Grafana version: 2.0.0-prebeta1, commit: fa2e074, build date: 2015-03-10 14:52:53)

Steps to reproduce:
1. Select Playlist in the dashboards drop down menu
2. Select desired dashboards (query or star dashboards)
3. Click "Start"

Result:
The controls presented in the image below appear, but nothing else happens (dashboards are not being displayed and/or rotated).

![image](https://cloud.githubusercontent.com/assets/952836/6617384/ce1e2c68-c8c0-11e4-99ba-5294e148a268.png)

**Comment by torkelo** [comment]
strange, works for me. What interval did you enter in the Timespan between dashboard change field? 
Can you open chrome dev tools and inspect the console for js errors?

**Comment by costimuraru** [comment]
I've used 1m and 10s.

Here's the js error I'm receiving:
![image](https://cloud.githubusercontent.com/assets/952836/6618304/7b60ede4-c8ca-11e4-8279-b04ce91a77ff.png)

**Comment by torkelo** [comment]
Very strange, it must be some caching or weird thing. Cant explain why you get this error. Should work with the version you have.

**Comment by costimuraru** [comment]
Hmm strange indeed. I've retried using Firefox (instead of Chrome) and switched to http://play.grafana.org/v2/dashboard/db/graphite-carbon-metrics

The same behavior, although slightly different js error.

![image](https://cloud.githubusercontent.com/assets/952836/6619758/24b3b804-c8d5-11e4-8661-2bdd7de4b058.png)

**Comment by torkelo** [comment]
could you just double check if you can replicate this again on http://play.grafana.org/v2  open chrome dev tools and disable caching and hit CTRL+F5 to refresh , just want to make sure it is not a caching issue (js files are revisioned/hashed so it should not be any)

**Comment by costimuraru** [comment]
@torkelo, I've tried both disabling caching and Ctrl + F5 with the same result.
I've also asked a colleague to try on his laptop and the exact same behavior occurred to him as well (OS X with Safari and Firefox).

**Comment by costimuraru** [comment]
I've also reproduced this on a Windows machine with Chrome:

![win](https://cloud.githubusercontent.com/assets/952836/6735645/2feb374a-ce68-11e4-8823-1ba86611010d.jpg)

**Comment by torkelo** [comment]
@costimuraru I know what is wrong now, you are trying to start a playlist without selecting any dashboards :) 

I need to add some info/error message for this (and disable the start button).

**Comment by costimuraru** [comment]
@torkelo using the latest grafana version and testing on play.grafana.org I can still replicate this issue. Tested on a smart tv and the same behavior occured: The previous/stop/forward controls appear, but nothing else happens (dashboards are not being displayed and/or rotated).

**Comment by torkelo** [comment]
@costimuraru works great on play.grafana.org, are you SURE you are selecting any dashboards before starting the playlist? You the search field, enter `pla`, you should see some dashboard appear in the results,  hit the right arrow button to add them to the playlist, then hit start.

**Comment by costimuraru** [comment]
@torkelo you are right, I was not pressing the right arrow.
I was relying (just like in grafana 1.0) to automatically play the bookmarked dashboards.

The playlist feature works well now, although a few improvements would be much appreciated:
- make the playlist creation process more accessible - something like making the right arrow more colorful would help (I completely missed it)
- You talked about the info/error message when starting a playlist with no dashboard selected - was this added (because I can't see)?
- support playlist with templating variables (issue #773) :-)

**Comment by nopzor1200** [comment]
Just some quick feedback here. I was trying to document this feature so this is fresh in my mind.

1. Agree that the right arrow is something that's easy to miss - I completely missed it too! I had to puzzle over why my Playlist wasn't working for a couple of minutes before I figured it out.

2. Agree that it'd be nice to save a Playlist. Along those lines it'd be great to have multiple/different named Playlists.

**Comment by torkelo** [comment]
@costimuraru @nopzor1200 

The playlist view will need a big update in a future release, especially when playlists will support template variables, and saving playlists. 

But for 2.0 release I did a small UI change to make it more easy to understand:

![image](https://cloud.githubusercontent.com/assets/10999/7227358/4e14e3f0-e750-11e4-98ff-4ccb5b099c84.png)

**Comment by costimuraru** [comment]
Thanks @torkelo I think the improvement is great.
I look forward to seeing the other improvements as future versions roll out.
