### ISSUE TITLE
Dynamic Grid Threshholds

### ISSUE THREAD

**Issue by anguswilliams** [grafana/grafana#159]
Could Grid thresholds be fed dynamically as well? We feed some of our thresholds into graphite at work, it'd be useful to set the thresholds based on those metrics.

Cheers!

**Comment by mtanda** [comment]
+1

**Comment by The-Nik** [comment]
+1 for thresholds-queries :+1: 

In my case I need to read the current influxdb tag value

**Comment by zorkus** [comment]
+1 from me too. I want to read current influxdb tag value like TechniclabErdmann

**Comment by fhdummy** [comment]
Any news on this? I would really need this feature, that would be really cool.

**Comment by yves-vogl** [comment]
I'd like to use this feature as well. The main aspect is that thresholds are displayed only when a metric is near to its value. Using regular metrics for thresholds (e.g. from InfluxDB) needs to make additional use of a additional Y-axis legend to prevent the other values from beeing too tiny (as the graph is scaled to fit all metrics).

**Comment by k29** [comment]
Any updates on this?

**Comment by duhow** [comment]
Maybe querying the value as Templating and call it on the threshold options?
For example with MySQL, having **$THRESH_MIN_GRAPH_LOGINS** as `SELECT LEAST(1, MIN(value) - 5) AS __value FROM logins WHERE $__timeFilter(date)`, then on edit graph, write the variable name; or as proposed, being able to write this query inside of the threshold tab.

**Comment by gonzoj74** [comment]
+1

**Comment by rakhadityap** [comment]
up
i'd like to have this too for mysql graph and every other panel with threshhold

**Comment by jengstro2** [comment]
+1 for dynamic threshold setting with datasource 'syntax' (pretty much same as you define variables with datasource)

**Comment by Cyyking** [comment]
+1

**Comment by Great-Li-Xin** [comment]
Please, do every one a favor.

**Comment by arianofaoms** [comment]
How is this not implemented after 5 years? It's quite a key feature...

**Comment by wimoMisterX** [comment]
+1

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by AntoninJcb** [comment]
Any news about this feature request ? As v6.6 added dynamic max bar values, it would be nice to have dynamic threshold too ! (Or % of max relative)

**Comment by meersjo** [comment]
And another potential user of this :-)
I'm using the (beta) flux plugin to do aggreggations out of Influx data, and would like to be able to set tresholds based on [ max(series) - fixed_value] - for what I'm currently graphing, a threshold that warns if total VMWare memory usage exceeds total cluster memory - 1TB; as that is about the point when we get into the danger zone when losing a host.

So, for me, calculations on an alias would work nicely :-)

**Comment by chris2k20** [comment]
This feature would be very useful to interpret data. So please define threshholds variables from datasource.

**Comment by wesleycastilho95** [comment]
+1

**Comment by Kovah** [comment]
Any news on this? Currently have a situation where I could need it.

**Comment by lucanello** [comment]
I'd also love to see it implemented!

**Comment by vivekdsr** [comment]
+1

**Comment by BassTester** [comment]
+1

**Comment by kyjanond** [comment]
+1

**Comment by Mimmi511** [comment]
+1

**Comment by vodkabuaa** [comment]
Today is the first that I am using Grafana and I need this feature too. Then I think it should be key feature.

**Comment by Klarkin2** [comment]
Definitely would love to see this feature as well

**Comment by chrisngene** [comment]
Been day dreaming about this too, would love to see it added

**Comment by R-Studio** [comment]
Any news on this?

**Comment by gothicfann** [comment]
any news??

**Comment by gothicfann** [comment]
does anyone even work ok this???

**Comment by caraar12345** [comment]
Hello! I'm here to put a +1 on this 😄 

It would be infinitely useful in the world of customer service. We have an in-house chat system which feeds into Prometheus and I'm looking into using Grafana as a more permanent solution for queue monitoring. As a result, being able to set the colour of the queue depth (how many chats we have) based on the 'waiting longest' time would be _amazing_!

**Comment by a-vogel-tappert** [comment]
A threshold based on a query would be great.
Please enter that feature :-)

**Comment by ChristianKlass** [comment]
It would also be good to just get the threshold from another column in the same table, I think that would be extremely useful. :D

**Comment by PaulCorbeau** [comment]
Clearly required.
For exemple the threshold could be usefull with the stddev function. To be able to draw +- 1,2,3 sigma values as threshold :)

**Comment by torkelo** [comment]
So in v8.1 we are adding two new transforms that will allow you to extract config like min, max, unit and thresholds from a normal query:

[Config from query results](https://grafana.com/docs/grafana/next/panels/transformations/config-from-query/)
[Rows to fields](https://grafana.com/docs/grafana/next/panels/transformations/rows-to-fields/) 

We are soon switching to Github discussions for feature requests, will create an issue there next week to collect feedback on these new transforms

**Comment by Kortenbach** [comment]
@torkelo Interresting subject. 
However: Both the links appear to be dead(?)

**Comment by torkelo** [comment]
@Kortenbach 
https://grafana.com/docs/grafana/latest/panels/transform-data/transformation-functions/#config-from-query-results 
https://grafana.com/docs/grafana/latest/panels/transform-data/transformation-functions/#rows-to-fields

**Comment by Kortenbach** [comment]
@torkelo Thank you for the update! Does this also work for unified alerting? Maybe you know if any examples for this? I've been busting my head trying to get it to work. Any help would be highly appreciated!

**Comment by torkelo** [comment]
Unified alerting? 

No, but you could write two queries (one return threshold) the other the data and using a server side expression you can write an expression that uses the result of the first query so check against the data query, so the query you alert on only return data over the threshold returned by query 1

**Comment by Kortenbach** [comment]
That's what I tried to do, but Grafana is very picky when it comes to the
format if the query results. I cannot get it to work properly.

Op vr 29 jul. 2022 15:28 schreef Torkel Ödegaard ***@***.***>:
