### ISSUE TITLE
Annonations not working in grafana2?

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1590]
I've used a graphite query in order to generate some annotations, but it does not work in grafana 2 (no annonations appear). The same settings work fine in grafana 1.0.

By the way, is there a demo website for grafana 2? Similar to play.grafana.org.

![image](https://cloud.githubusercontent.com/assets/952836/6617491/de6f72f6-c8c1-11e4-9dba-4d80175b2649.png)

**Comment by torkelo** [comment]
@costimuraru strange, this also works for me. Any js errors?

Yea there Grafana 2 is running on http://play.grafana.org/v2  (login as guest/guest)

http://play.grafana.org/v2/dashboard/db/annotations

**Comment by costimuraru** [comment]
Hmm, I can see the annonations on http://play.grafana.org/v2/dashboard/db/annotations. Is the page using graphite queries?

I've tried using a custom graphite query in order to generate annonations, but no luck. It works though in grafana 1.0.

![image](https://cloud.githubusercontent.com/assets/952836/6618505/0fa87d9a-c8cc-11e4-8eb1-68a2b5fc0b89.png)

![image](https://cloud.githubusercontent.com/assets/952836/6618498/fe111a1a-c8cb-11e4-8341-4a05269efb0c.png)

And here's grafana 1.0 (http://play.grafana.org/#/dashboard/db/graphite-carbon-metrics)
![image](https://cloud.githubusercontent.com/assets/952836/6618616/c671cc8e-c8cc-11e4-862b-e17e3b84c69e.png)

**Comment by torkelo** [comment]
Very strange, I updated the annotations dashboard to your query (for the deploy annotation). And it works.
http://play.grafana.org/v2/dashboard/db/annotations

What browser and OS are you using?

**Comment by costimuraru** [comment]
Maybe I'm crazy, but I can view your updated annonations on http://play.grafana.org/v2/dashboard/db/annotations, however when I go to http://play.grafana.org/v2/dashboard/db/graphite-carbon-metrics and add the exact same annonation it does not work there.

I'm using Chrome Version 41.0.2272.76 (64-bit), Mac OS X Yosemite 10.10.2 (14C1510)

**Comment by costimuraru** [comment]
I exported the two dashboards and I can see one crucial difference :-) :
```
  "annotations": {
    "enable": false,
```

**Comment by torkelo** [comment]
Ah, fixed this now. That flag is not used any more (now the annotation feature is enabled as soon as there are any annotations added to the dashboard)

**Comment by torkelo** [comment]
btw, Thanks for reporting this !

**Comment by costimuraru** [comment]
Thanks @torkelo! Would it be possible to update the docker image?
I'm doing a demo tomorrow on grafana to the team and want to use the latest version :)

**Comment by torkelo** [comment]
@costimuraru updated!
