### ISSUE TITLE
iFrame in Grafana now working after GF_PANELS_DISABLE_SANITIZE_HTML=tru

### ISSUE THREAD

**Issue by David-SpreenICT** [grafana/grafana#15908]
Hello all,

I have found the bug fix for the <iframe>  not working.
- First of all, I dont have the [Panel] section in my grafana.ini
- Secondy, when I either add "disable_sanitize_html" and manualy create the [Panels] section it does not work or add "GF_PANELS_DISABLE_SANITIZE_HTML=true" (at the end the Ini file) and restart Grafana the issue still occurs in my grafana.

Grafana build: Grafana v6.0.1 (0c44a04)

Any help would be appreciated

**Comment by torkelo** [comment]
Strange. It has worked for everyone else. 

If you have an old install and upgrade /etc/grafana/grafana.ini will not be updated with new sections as we do not want to modify your config file. You need to add the [panels] section yourself. 

I have tried the setting via ini file
```
[panels]
disable_sanitize_html = true
```

and via env variable, example:

docker run --rm -p 3022:3000 -e GF_PANELS_DISABLE_SANITIZE_HTML=true grafana/grafana:6.0.1

Both worked fine and allowed me to to add iframe or script to the text panel

**Comment by David-SpreenICT** [comment]
Issue is fixed, I coppied the ";" from the above settings and thats probably what didn't work
