### ISSUE TITLE
Alert are not triggering for count() condition

### ISSUE THREAD

**Issue by milindk0404** [grafana/grafana#15902]
**What happened**: Alert did not trigger

**What you expected to happen**: Expecting to trigger alert email

**How to reproduce it (as minimally and precisely as possible)**: On certain type of exception count, it should trigger an email.

**Anything else we need to know?**:

**Environment**: production
- Grafana version:5.4.3
- Data source type & version: graphite
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Unable to replicate: 

![image](https://user-images.githubusercontent.com/10999/54116889-fea54700-43ef-11e9-8b36-64135d63798d.png)

Please provide info on the query & query response, & test rule results etc.
