### ISSUE TITLE
Support $__from and $__to in seconds 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#15903]
When linking to other tools it's good to support passing the current time range you are using in Grafana. 
Which is why we have `$__to` and `$__from`. But those are in milliseconds and some expect them to be in seconds. 

## Just add another variable
One solution for this would be to add `$__to_s` and `$__from_s`. The downside to this would be that we might end up adding more units down the road. Ex `$__to_date_us` Upside being that its a tiny change. 

## Templating interpolation with datesupport 
An other solution would be to add support for transforming this value using the [templating interpolation feature](http://docs.grafana.org/reference/templating/#pipe). ex `${__to:format:epoch:seconds}` `${__to:format:HHmmss}`
The downside for this solution is that it's far more work and in one of our most complex areas of the  codebases. It's also a matter of how far we would like to push such a feature. I think there are tons of good string manipulations we could add on top of this. 

We most likly have an issue for the second solution allready. The reason I wrote up this is because Im not sure if we should go with the first or the second solution to solve the original request :)

**Comment by torkelo** [comment]
I think I prefer

`${__from:format:epoch:seconds}`

**Comment by bergquist** [comment]
I agree. I'm just afraid that we won't get around to working on that for a long time. Making sure it's possible to link from Grafana to other tools seems very critical to me since it reduces cognitive load for the person dealing with an incident.

**Comment by torkelo** [comment]
think that syntax should be quick to implement

**Comment by bergquist** [comment]
Perhaps I'm overestimating because I want to see so many other things implemented at the same time :)

Scoping it down to solve this use case in a smart way might be quick enough. 

What I would like to enable on a longer perspective is simple string/number operations on template variables and even legend values. Ex `replace()`, `toPercent()`, `dateFormat()`, `subtract()`, `add()`, `multiple()`, `trim()`

Some advanced examples that I would like to support in templating interpolation. 

`${var1.replace('server', 'node')}` //things like this could be really helpful in some environments
`${__interval:multiple(1000)}` // alternative to format:epoch:seconds
`${__interval:divide(1000)}` 
`${var1.trim()}`

Im not saying we have to support all of these. But I think manipulating templating fields could be a great enabler. Esp for datasources/plugins that we dont work on. 

Maybe I'm overthinking this.

**Comment by mtanda** [comment]
I want to convert `from timestamp` to `offset from now`. I'll use it for controlling panel's timeShift.

**Comment by dev-e** [comment]
It should also support RFC 3339 for generating correct links for Kibana

**Comment by ryantxu** [comment]
What are the backend requirements for this?  

From the frontend, we could "easily" add a format function that would allow anything like:

* `${__from:format:X}` Unix Timestamp: 1360013296
* `${__from:format:x}` Unix Millisecond Timestamp: 1360013296123
* `${__from:format:YYYY MM DD}` 2019 03 12

**Comment by dev-e** [comment]
@ryantxu I suppose it would be lovely to have something like this:
`${__from:format:YYYY-MM-DDTHH:mm:ss.fffZ}` 2019-03-12T10:17:12.451Z

**Comment by Miller-STGT** [comment]
Meanwhile you can convert manually.
TSQL example to convert $__from to a timestamp:

declare @fromTS bigint
set @fromTS = $__from

select dateadd(ms, @fromTS%(3600*24*1000), 
    dateadd(day, @fromTS/(3600*24*1000), '1970-01-01 00:00:00.0')
)

**Comment by mtanda** [comment]
Related to https://github.com/grafana/grafana/issues/20262 .
I want to convert `$interval` to seconds.

**Comment by cykl** [comment]
Thanks for the link. While our use cases differ, they likely requires a similar variable conversion feature. I created a naive PR for my very specific needs but would be happy to join this effort. @ryantx question, "_What are the backend requirements for this?_", got no answer. Could someone clarify this?

**Comment by dcastanier** [comment]
Related to #20533 
Current variable templating support:
`$var_name`
`[[var_name]]` or `[[var_name:option]]`
`${var_name}` or `${var_name:option}`
But could be extend to support a parameter like :
`$var_name`
`[[var_name]]` or `[[var_name:option]]` or `[[var_name:option:parameter]]`
`${var_name}` or `${var_name:option}` or `${var_name:option:parameter}`

In addition of current option (lucene,pipe,csv,json,...) we could add a new one datetime to manage datetime transformation:
- `${__from}` Unix Millisecond Timestamp: 1574420579322
- `${__from:datetime}`  format with default datetime format: 2019-11-22 12:02:59
- `${__from:datetime:YYYY-MM-DD}`  format using moment lib: 2019-11-22
- `${__from:datetime:epoch_s}`  Unix Second Timestamp: 1574420579

Could also works with any variable in Unix Millisecond Timestamp:
- `${__interval_ms:datetime:epoch_s}`  interval in second: 21600

**Comment by suikast42** [comment]
+1

**Comment by cykl** [comment]
Is someone still working on this? Multiple PR have been created by me, @mtanda  and @dcastanier but none got merged. Could we agree on transformations and start addressing specific needs? Beyond syntax, what are the difficult areas?

**Comment by sbason** [comment]
Just bumping this - we need a way to access in $__interval_ms in seconds for Cloudwatch as this is all that it supports. What is the progress?

**Comment by nabelekt** [comment]
Is this capability documented anywhere? They only place I am able to find references to it are here and in forum posts.

**Comment by Impact123** [comment]
Do you mean this?
- <https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__from-and-__to>
- <https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__interval_ms>

The site's own search is kinda bad but you can simply [search in the docs for it on github](https://github.com/search?q=org%3Agrafana+path%3Adocs+%22__from%22&type=code).
