### ISSUE TITLE
Grafana 6.0.1 whites screens related to the escape key

### ISSUE THREAD

**Issue by gmr** [grafana/grafana#15913]
**What happened**:

When editing a graph on a dashboard, clicking the back button results in a whitescreen/non-rendered dashboard.

Reproducible in both Chrome and Safari, but not on all dashboards.

**What you expected to happen**:

Clicking back renders the dashboard with the changed graph.

**How to reproduce it (as minimally and precisely as possible)**:

Screen capture of the behavior:
![Whitescreen when editing](https://user-images.githubusercontent.com/49469/54129837-89347900-43e5-11e9-86d0-a72f35731902.gif)
Also worth noting using the Esc key results in the same behavior.

**Anything else we need to know?**:

Errors in the console:
![Screen Shot 2019-03-11 at 10 05 25 AM](https://user-images.githubusercontent.com/49469/54129854-90f41d80-43e5-11e9-8fd9-f6b8e64a3fe5.png)

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Graphite 0.9.12
- OS Grafana is installed on: Ubuntu 14.04
- User OS & Browser: MacOS Chrome  && Safari
- Grafana plugins: bessler-pictureit-panel,briangann-gauge-panel,camptocamp-prometheus-alertmanager-datasource,digiapulssi-breadcrumb-panel,grafana-clock-panel,grafana-kubernetes-app,grafana-piechart-panel,grafana-simple-json-datasource,grafana-sensu-app,grafana-worldmap-panel,jdbranham-diagram-panel,mtanda-heatmap-epoch-panel,mtanda-histogram-panel,natel-plotly-panel,novalabs-annotations-panel,xginn8-pagerduty-datasource,goshposh-metaqueries-datasource,sbueringer-consul-datasource,yesoreyeram-boomtable-panel

**Comment by torkelo** [comment]
what plugins did you have on this particular dashboard?

**Comment by torkelo** [comment]
Do you get this on all dashboards?

**Comment by gmr** [comment]
I do not see it on all dashboards, and I do not use any of the plugins on this dashboard, nor are there any alerts. Attached the dashboard export in case that would be helpful.

If there's a way to capture helpful info from the UI In dev-tools or something, please let me know.

[dashboard.json.zip](https://github.com/grafana/grafana/files/2953461/dashboard.json.zip)

**Comment by torkelo** [comment]
was able to replicate with your dashboard! will investigate.
