### ISSUE TITLE
Stackdriver: Legend reports latest values (instead of current) when Hoover tooltip set to 'All series'

### ISSUE THREAD

**Issue by NaurisSadovskis** [grafana/grafana#15911]
**What happened**: When Visualization pane Hoover tooltip set to `All Series`, Grafana legend reports latest value. This is OK if viewing single time-series, but quickly become misleading with 100+ time-series where legend becomes critical to understanding values at a specific point in time. 

**What you expected to happen**: As I'm moving the mouse across the timeline, I expect Grafana to show only values that happened at/around the time.
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a custom Stackdriver metric 
2. Create first time-series (label: `metric.label.test`=`a`) with 5 datapoints between 09:00 - 09:05 
3. Create second time-series (label: `metric.label.test`=`b`) with 5 datapoints between 10:00 - 10:05
4. Create third time-series (label: `metric.label.test`=`b`) with 5 datapoints between 11:00 - 11:05
5. Create a Grafana dashboard using custom metric and group data by `metric.label.test`
6. In visualization panel, set Hover tooltip to `All Series`.
7. If you put your mouse cursor at any point after when the last datapoint was created (for example, 11:06), legend will show both timestamp and table of data with latest values for datapoint. 

**Anything else we need to know?**: This might not be a bug, but a feature. It is certainly behaving as intended if you need to see **latest values** for all of your metrics, however, in cases where different instances (timeseries) generate data sporadicly, this representation can be misleading. 

**Environment**:
- Grafana version: 6.0.1 (also present in 5.4.3)
- Data source type & version: Stackdriver
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: Chrome on MacOSX (10.13.6)
- Grafana plugins: N/A
- Others: N/A

Let me know if you need more information.

**Comment by torkelo** [comment]
@daniellee does stack driver insert null values for missing data points?

**Comment by torkelo** [comment]
you referring to legend in issue title but the description only tooltip, legend does not change when you move the tooltip so a bit confusing issue title & description.

**Comment by torkelo** [comment]
closing this as I think it's a general complaint about the tooltip, we have an open issue for / change request for that already

**Comment by NaurisSadovskis** [comment]
Thanks! Do you have a link for it?

**Comment by torkelo** [comment]
Sorry, was on mobile (still is). Search for issue with tooltip over closest or something song those lines :)
