### ISSUE TITLE
Should we move react plugin panels to @grafana/ui?

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15920]
The @grafana/ui package is great.  It makes a clear reusable library of components.  

It would be great to design the new plugin panels in a way that make it easy to plop them into any react app.  

The downsides I see are:
* library bloat.  esoteric dependencies may find there way into grafana/ui
* I don't really care that the editor is in the component library, but I don't see how to avoid that and that will require exposing more things sooner.  See: https://github.com/grafana/grafana/pull/15268

**Comment by torkelo** [comment]
My thinking is that some of the core visualizations that have a clear reusability story (in Grafana and in possibly many panel plugins) should be in grafana/ui, so the Gauge & Graph, Table etc should be in @grafana/ui . But not as "Panel" components but rather dump visualizations that can be used from panels. The distinction between panel & visualization could in many cases maybe be rather fine, but for me it's a more isolation from the runtime &, dashboard, "dumber" (no to very little data pre-processing).

**Comment by ryantxu** [comment]
ya -- I see the distinction, and I don't think there is a rush to do this.  However it is something we should keep in mind since it would make for a clear/reproducible way to include grafana panels.  IE, tag + Panel JSON + data JSON

It may be I just like storybook :) and it has a good way to articulate the options with default data.  

I'll close this for now, and we can keep it in mind
