### ISSUE TITLE
Gauge crashes when query has timeSeries and tableData

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15924]
The gauge assumes if the first result is time series, so are the rest.  But that is not always true:

![image](https://user-images.githubusercontent.com/705951/54158776-89923b80-4408-11e9-969a-ac3db17d1abd.png)

This will be fixed by #15864

**Comment by torkelo** [comment]
Does any panel handle this? (I mean with a good error)

**Comment by ryantxu** [comment]
hymm -- it looks like the only ones that does is the plotly panel :)  For that, we join data across two queries.  One is table and one is series.  Most of the mess in the plotly panel is dealing with the transformation to their data model  😱 

regardless this would all be solved with #15864
