### ISSUE TITLE
Make it possible to add username to the datasource request in the data proxy.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#15931]
It should be possible to opt-in to pass username of the logged in user to the datasource when using server mode proxy. I think this could be a global setting in `grafana.ini`

ex
`X-Grafana-User: bergquist`

Sounds related to #6359 we should spend some time investigating if we can solve both at the same time.

**Comment by torkelo** [comment]
Dupe / similar to https://github.com/grafana/grafana/issues/6359

**Comment by torkelo** [comment]
ah, see you also identified that one :)
