### ISSUE TITLE
Handle data source not found better in v6.0 

### ISSUE THREAD

**Issue by Fredrik-Petersson** [grafana/grafana#15933]
**What happened**:
Created a new Microsoft SQL Server datasource. Created a new dashboard with some tables and graphs using the added Microsoft SQL Server datasource. Everything works at this point and I have some nice Tables and Graphs.

Changed the name of the Microsoft SQL Server datasource. This causes all Tables and Graphs using the datasource start using the first datasource in avaliable list (not default but first in order from top) in my case to a AWS Cloudwatch Datasource.  This changed the type of "Graph/Table/Query" to AWS Cloudwatch and remove the working SQL Query entirely. Changing to the new datasource does not bring the working query back so you have to manually add the query back. Visualizations and customization appear to remain intact.

**What you expected to happen**:
Get an error about datasource not found in Graph/Table but the typ should still be SQL and the query remaining.

**How to reproduce it (as minimally and precisely as possible)**:
Create Microsoft SQL Server datasource. Create Table/Graph with the Microsoft SQL Server datasource. Add working Query. Change name of the Microsoft SQL Server datasource. Reload Dashboard with the Table/Graph.

**Anything else we need to know?**:
This may be due to having multiple Datasources. If only using Microsoft SQL Server datasources then the type of Graph/Table will likely remain over name changes of Datasource.

**Environment**:
- Grafana version: 6.01 self-hosted
- Data source type & version:  Microsoft SQL Server datasource, version included in Grafana 6.01
- OS Grafana is installed on: Windows Server 2016 on AWS
- User OS & Browser: Windows 10, Firefox 65.0.2 (64 bit)
- Grafana plugins: Pie Charts, Azure Monitor, 
- Others:

**Comment by torkelo** [comment]
sort of duplicate of an old issue in Grafana, https://github.com/grafana/grafana/issues/1664  (Grafana does not handle Datasource renames)

But its a bit worse I think in v6 as when you into edit mode if the data source is not found it will just take the first one instead, which clears the old query (if different data source type).

**Comment by torkelo** [comment]
This was improved recently in v7 I think 

still https://github.com/grafana/grafana/issues/1664 is not solved
