### ISSUE TITLE
multiple selections in legend value

### ISSUE THREAD

**Issue by nicolasStevenin** [grafana/grafana#15949]
Hi,
**What would you like to be added**:

I have a metric with different labels value and I need sometimes to see all, just one or multiple labels value. As you can see below, I can see just one or all labels value but not 2 of them for exemple.

![qos](https://user-images.githubusercontent.com/17617687/54219719-51febe80-44f0-11e9-9e80-aba0bc8259c1.PNG)
![qos2](https://user-images.githubusercontent.com/17617687/54219722-51febe80-44f0-11e9-808a-590ec37d2a5d.PNG)

Is that possible to add it ?

Thanks

**Comment by torkelo** [comment]
hold down shift key
