### ISSUE TITLE
epoch time conversion no longer working

### ISSUE THREAD

**Issue by pizzalord22** [grafana/grafana#15945]
**What happened**:
Time conversion macro that worked in earlier versions stopped working with message: " Unknown macro __unixEpochTo "

**What you expected to happen**:
Like the help mentions:
$__unixEpochTo() ->  1492750877

**How to reproduce it (as minimally and precisely as possible)**:
I have this script (that was working), that stopped working in V6
`
SELECT UNIX_UTC_00 AS time,
GasSupplyPressureHydrogen_P021Val
FROM machine_data_15  WHERE 
 CASE 
 when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<86400/*1*/ THEN  id%1=0 
 when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<259200/*3*/ THEN  id%3=0 
when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<518400/*6*/ THEN  id%6=0 
  when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<2160000/*25*/ THEN  id%30=0 
   when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<13824000/*180*/ THEN id%200=0 
  when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<31104000/*360*/ THEN id%360=0 
  when ( $__unixEpochTo(UNIX_UTC_00) - $__unixEpochFrom(UNIX_UTC_00))<62208000/*720*/ THEN  id%720=0 
   END and $__unixEpochFilter(UNIX_UTC_00) 
ORDER BY UNIX_UTC_00 ASC
`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.0.1 (latest version at moment of writing)
- Data source type & version: (MYSQL, 5.7)
- OS Grafana is installed on:  VM
- User OS & Browser: Debian Stretch
- Grafana plugins: none
- Others:

**Comment by rjboer** [comment]
Have this as well :S:S

**Comment by torkelo** [comment]
Strange unable to replicate. Do you get this for all queries with __unixEpochTo?

**Comment by rjboer** [comment]
I have this for all of them (over all dashboards)

**Comment by torkelo** [comment]
It looks like your using it wrong, try removing the arguments to the macro , it does not accept args, if still error, then try remove the paranthesis
