### ISSUE TITLE
root_url does not work AWS ALB

### ISSUE THREAD

**Issue by nqbao** [grafana/grafana#15959]
**What happened**:
I'm using AWS ALB to run Grafana under a subpath, it does not seem to work. I'm getting the screenshot as below

<img width="813" alt="Screenshot 2019-03-12 22 04 51" src="https://user-images.githubusercontent.com/177742/54254901-e417be80-4512-11e9-84ba-4d5a3be7b0e5.png">

**What you expected to happen**:

Grafana to work correctly under subpath

**How to reproduce it (as minimally and precisely as possible)**:

* Start grafana in docker in 1 instance

```
docker run \
  -d \
  -p 3000:3000 \
  --name grafana \
  -e GF_SERVER_ROOT_URL=https://mydomain/grafana \
  grafana/grafana:6.0.1
```

If I remove the subpath it works correctly under `/`

* Register the instance under a [Target group](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html)

* Configure LB to forward using listener rules as below

<img width="1216" alt="Screenshot 2019-03-12 21 58 51" src="https://user-images.githubusercontent.com/177742/54254876-cc403a80-4512-11e9-99bb-7224eb5e54fc.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
You also need to rewrite the URL (remove the /grafana in requests between loadbalance and Grafana). 

Not sure AWS LB supports this (unlike nginx / apache, haproxy etc)

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
