### ISSUE TITLE
Integration with anomaly detectors

### ISSUE THREAD

**Issue by mlowicki** [grafana/grafana#1595]
[Skyline](https://github.com/etsy/skyline) provides machinery for detecting anomalies within metrics. Its webapp is rather poor and it's basically another dashboard to look at. Grafana is the place where most of our dashboards are created, we have there release annotations (and many others) etc. so maybe it's a good place to mark anomalies as well. Opinions?

**Comment by torkelo** [comment]
We will be working on integration with alerting in Grafana v2.1 and 2.2, looking at Bosun and others and Grafana itself will probably get some basic alerting features as well.

**Comment by luluprat** [comment]
Hello
i am testing grafana 2.1 early release.
Are anomaly detectors inside this version or are they going to be on next : 2.2 or after ?
thanks

**Comment by torkelo** [comment]
They are not. maybe in 2.2 or 2.3
