### ISSUE TITLE
Embed generic dashboards into another dashboard

### ISSUE THREAD

**Issue by unaiur** [grafana/grafana#15955]
**What would you like to be added**:
A new panel type that allows to embed a dashboard into another. The new panel must allow to wire the variables of the inner and outer dashboards (or use constants for the inner dashboard variables).

**Why is this needed**:
It will allow to develop generic dashboards that can be embeded in final dashboard. For example:
* A dashboard for an AWS/SQS queue that shows the pending messages, the maximum age and the number of messages in the associated DLQ.
* A dashboard for an AWS/DynamoDB table that shows the capacity and usage of a table.
* A dashboard for a load balancer that displays all the relevent statistics
* A dashboard for a host fleet that shows CPU, memory and disk usage

We are currently using a wiki page in front of Grafana to build something similar, but variable wiring is a mess.

**Comment by ryantxu** [comment]
Check #15620 -- this has a way to reuse a single *panel* in another dashboard.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
