### ISSUE TITLE
mention compatibility with graphite-api

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#1596]
http://graphite-api.readthedocs.org/en/latest/

grafana just as well talks to this as to graphite-web. today somebody in graphite irc channel was confused about this. maybe make this a bit more explicit.

**Comment by torkelo** [comment]
where is a good place to mention this? I can mention it on the About docs page, and the Graphite docs page, and maybe in the features pages and main README.md ?

**Comment by pauzed** [comment]
I personally check Readme first.  +1 to README.md Maybe features/graphite.md but that may not alleviate this confusion.
