### ISSUE TITLE
Gauge visualisation lose focus on 'min/max value field' 

### ISSUE THREAD

**Issue by azhiltsov** [grafana/grafana#15960]
**What happened**:
Active Input field changes from 'Min value' or 'Max value' to 'Visualisation'

**What you expected to happen**:
keep focus in the same field

**How to reproduce it (as minimally and precisely as possible)**:
Create a new Panel
change type to gauge
Start changing 'Min value' or 'Max value'
Notice that focus of input field changes to 'Visualisation' preventing you from filling a right field

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: ARM Raspberry PI
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
This is fixed in master and will be included in next release, https://github.com/grafana/grafana/pull/15802
