### ISSUE TITLE
Shortcut to reset the view to saved dashboard value

### ISSUE THREAD

**Issue by hardoverflow** [grafana/grafana#15964]
**What would you like to be added**: Shortcut to reset the view to saved dashboard value

**Why is this needed**: We worked daily in several dashboards and we need a shortcut to reset the view.

**Comment by torkelo** [comment]
CTRL+R ? (reload page)

**Comment by hardoverflow** [comment]
CTRL + R isn't the solution, because the zoom level is retained.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
