### ISSUE TITLE
Move delete button in Dashboard settings

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#15965]
### Motivation

Currently users are deleting Dashboards by mistake in Dashboard settings. This is very bad since one can't restore dashboards. (see #9235)

### Solution

We should simply move the Delete button to the general tab and rename it to Delete Dashboard. The button is more hidden and clearer so no one deletes their dashboard by mistake.

**Comment by torkelo** [comment]
please label & move to right pipeline
