### ISSUE TITLE
Feature Request: Compare different panels

### ISSUE THREAD

**Issue by SimonXming** [grafana/grafana#15976]
Users could select two(or more) panels and compare them. The ideal scenario would be a popup window with two panels at the same timeline, like a temporary virtual dashboard. 
It would be very helpful if users want to investigate the underlying relation between two metrics/panels.

**Comment by torkelo** [comment]
For ad hoc comparisons I would suggest using the new explore feature. Where you can go and compare. You can go to explore with the queries from one panel, but not two.

**Comment by SimonXming** [comment]
New explore feature is pretty cool, could we support compare from existing panels instead of input the queries every time using `explore`. That's would great helpful. 😄

**Comment by SimonXming** [comment]
New explore feature is pretty cool, could we support compare from existing panels instead of input the queries every time using `explore`. That's would great helpful. 😄

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
