### ISSUE TITLE
Theme generation stops working after upgrade to ts-node 8.0.3

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#15974]
**What happened**:
Tried bump ts-node from 8.0.2 to 8.0.3 - theme generation stops working.

**How to reproduce it (as minimally and precisely as possible)**:
Change ts-node to `8.0.3` in packages.json, `yarn install`, `yarn themes:generate`

**Error message**:
```
TypeError: Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `dark.ts`.
```

**Anything else we need to know?**:
~~New in ts-node 8.0.3:
`Fall back on resolving relative TypeScript packages (normal resolution is from working directory, these two things can be the same in the case of locally installed packages)`
Commit: https://github.com/TypeStrong/ts-node/commit/655c43b77fdc9784caac0bc3120455afe5e0cb8d~~

Update: https://github.com/grafana/grafana/issues/15974#issuecomment-492599797

**Comment by torkelo** [comment]
is this still the case?

**Comment by jschill** [comment]
> is this still the case?

Tried upgrading now to ts-node 8.1.0 - same problem. Downgraded to 8.0.2 and then went from commit to commit until it stopped working on https://github.com/TypeStrong/ts-node/commit/c21569372e0d8ba79c059771929d18568a910c77

**Comment by jschill** [comment]
It's an open issue over at ts-node: https://github.com/TypeStrong/ts-node/issues/797

I tried setting `preserveSymlinks` to `true` in my tsconfig as [suggested](https://github.com/TypeStrong/ts-node/issues/797#issuecomment-492239440) and that actually solved this.
