### ISSUE TITLE
goconvey tests are failing on golang 1.12

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#15971]
As mentioned by @xlson on our slack channel

it's not possible to run tests in Grafana on golang 1.12

https://github.com/smartystreets/goconvey/issues/561

**Comment by torkelo** [comment]
looks like it's fixed in goconvey master (not sure if latest release?)

**Comment by bergquist** [comment]
pinning to a git commit in master would be fine for now.

**Comment by xlson** [comment]
I tested the latest master yesterday and that didn't work. Didn't test the actual merge commit though, might work better.
