### ISSUE TITLE
Panels broken after grafana 6.0.1 upgrade due to `aliasColors` attribute

### ISSUE THREAD

**Issue by rdsubhas** [grafana/grafana#15979]
# What happened

* We upgraded from Grafana 5.4.2 to 6.0.1
* Some panels were broken, saying `e.indexOf` is not a function:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/1570745/54282977-6b117900-459d-11e9-969f-ef1d4a5d0613.png">

* Console error:

```
Panel data error: TypeError: "e.indexOf is not a function"
    f namedColorsPalette.ts:164
    timeSeriesHandler axes_editor.ts:20
    getSeriesList data_processor.ts:147
    getSeriesList data_processor.ts:146
    onDataReceived module.ts:40
    emit index.js:129
    emit actions.ts:46
    handleQueryResult metrics_panel_ctrl.ts:239
    Angular 7
        c
        c
        $digest
        $apply
        r
        h
        n
metrics_panel_ctrl.ts:178:11
```

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Graphite
- OS Grafana is installed on: Official docker image
- User OS & Browser: All on MacOS (Firefox, Chrome and Safari)
- Grafana plugins:

# Resolution/Workaround

If we use the exact same query in a fresh new panel, it worked out of the box. So we compared the new panel JSON with old panel JSON.

There was an attribute in the panel JSON called `aliasColors`, which I don't know how it got there or what feature it belongs to, but that was the root cause.

We edit the Panel JSON and remove this `aliasColors` attribute:

![image](https://user-images.githubusercontent.com/1570745/54283222-d8250e80-459d-11e9-8131-e61388a1a8ac.png)

![image](https://user-images.githubusercontent.com/1570745/54283626-b24c3980-459e-11e9-9cc2-e2f92b65131c.png)

And then it works like a charm.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/1570745/54283329-0f93bb00-459e-11e9-95be-2c909d3fb389.png">

I'm just raising an issue for awareness and if possibly anyone ran into this problem. Maybe this needs a migration, or maybe not.

**Comment by torkelo** [comment]
those alias colors looks super strange. Grafana would not set alias colors to numbers (1, 224) , how did you end with those alias colors?

**Comment by rdsubhas** [comment]
I'm sorry I don't have enough knowledge about grafana internals to know which grafana frontend functionality would set that JSON attribute. What I can say is, those labels look like legend colors. We could have clicked and changed the legend color through normal Grafana UI some months back.

**Comment by torkelo** [comment]
never seen alias colors like that. Super strange.

**Comment by torkelo** [comment]
when I use the color picker I get colors like this:

```
"aliasColors": {
    "web_server_01": "#70dbed",
    "web_server_02": "#5195ce",
    "web_server_03": "#0a50a1",
    "web_server_04": "rgb(22, 92, 217)"
  },
```

**Comment by rdsubhas** [comment]
yep, super weird, I think we can close this as a freak occurrence until anyone else reports anything similar. wdyt? :)
