### ISSUE TITLE
Data source -> back button does not respect subpath

### ISSUE THREAD

**Issue by nqbao** [grafana/grafana#15986]
**What happened**:

I deployed a grafana under subpath (/grafana/) with nginx rewrite.
Everything works fine except when you edit a data source, the back button redirects you to the wrong url

**What you expected to happen**:

Back button should return me to /grafana

**How to reproduce it (as minimally and precisely as possible)**:

* Deploy grafana using docker under /grafana. Nginx rewrite is configured properly
* Create a datasource (postgres)
* Then edit the datasource
* Click on the back button, you will be redirect to root url

![Screenshot 2019-03-13 12 06 38](https://user-images.githubusercontent.com/177742/54307302-9047bc80-4588-11e9-9c17-099927c3d3f6.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.1
- Data source type & version:
- OS Grafana is installed on: docker
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed in master, and will be fixed in next patch release: https://github.com/grafana/grafana/pull/15759

**Comment by nqbao** [comment]
Thanks, glad to know that this is fixed already.
