### ISSUE TITLE
React editors should update the display more often

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#15988]
In the angular panel editors, there is an immediate feedback when things change -- with the react version, it is less clear.

It would be great to re-render when:
 * query changes
 * query is added
 * hit 'enter' in any field... or on keypress?  (like angular)

right now it is weird that stuff only changes when you select out of the field you just typed (and hit enter!)

**Comment by torkelo** [comment]
Not sure I understand. The react query editors have the same way decide this as angular panels do. 

```ts
export interface QueryEditorProps<DSType extends DataSourceApi, TQuery extends DataQuery> {
  datasource: DSType;
  query: TQuery;
  onRunQuery: () => void;
  onChange: (value: TQuery) => void;
}
```

The query editor gets to decide what changes should trigger a new query execution. Much like the angular query editors get's to decide when to call panelCtrl.refresh()

**Comment by ryantxu** [comment]
This is not a question of *if* it is possible... it is an observation that it should do it more often 😄 

In angular many of the two-way-binding features made this update on each key-press regardless of calls to 'refresh'.  

I liked the quick response in v5... in v6 i find myself needing to explicitly hit refresh to get the display to update.

**Comment by torkelo** [comment]
What react query editor are you using? There is none in core Grafana currently. Not sure I understand you still :)

**Comment by torkelo** [comment]
Closing this for now as I am not sure what you mean, is there a specific data source that does not call refresh when it should?
