### ISSUE TITLE
cloudwatch clusterid shows all nodes in clusters

### ISSUE THREAD

**Issue by nikoalch** [grafana/grafana#15984]
**What happened**:
clusterid in cloud watch datasource shows individual nodes in region vs cluster names
**What you expected to happen**:
should show cluster name/group  
**How to reproduce it (as minimally and precisely as possible)**:
Select clusterID from dimension, shows individual nodes in all clusters in that region

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: cloud watch
- OS Grafana is installed on: Hosted

**Comment by torkelo** [comment]
Can you check via query inspector that the clusterId dimension is sent to cloudwatch in the query? If so, sounds like a Cloudwatch bug or usage issue (sometimes you need two filter dimensions)

**Comment by mtanda** [comment]
I guess, the namespace is "AWS/ElastiCache".
If so, you need to select `CacheClusterId` and `CacheNodeId`.

https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/CacheMetrics.DimensionsAndSets.html
The document says,
> Each metric is published under a single set of dimensions. When retrieving metrics, you must supply both the CacheClusterId and CacheNodeId dimensions.

**Comment by benholtz** [comment]
Hello @torkelo and @mtanda , Wondering if in the case we cannot get the cloudwatch to respond as we desire, if there is some way we can get this with a work-around by getting the ARN by tag, then resolving the ARN to the CacheClusterId and CacheNodeId?  Sorry, I'm a bit new to grafana, but this is a huge priority for us because we do not currently have consistent node-id's within our clusters (CacheCluster) so it makes a regex not simple)possible with our 40+ clusters.

**Comment by mtanda** [comment]
@benholtz Sorry, I can't imagine the output what you want.
You want to create graph panels for each CacheClusterId and CacheNodeId pair?

**Comment by mtanda** [comment]
If specifying CacheNodeId first, it might be wrong.
To get correct CacheNodeId, specify CacheClusterId first, then specify CacheNodeId.

related code.
https://github.com/grafana/grafana/blob/v6.0.2/public/app/plugins/datasource/cloudwatch/query_parameter_ctrl.ts#L114-L121

**Comment by benholtz** [comment]
@mtanda Essentially we want an aggregated Cluster (master and slave nodes) Metric.  The problem as it stands now is the CacheClusterId is actually the Node's Name, not the cluster's name (i'm assuming this is from cloudwatch)..  It appears that CacheClusterId and CacheNodeId are both associated with the node, not the cluster as a whole..

**Comment by benholtz** [comment]
@mtanda To give some context, here is a screenshot from AWS Console
![image](https://user-images.githubusercontent.com/231303/55426743-5855e880-553a-11e9-906c-335330e4915a.png)
and from our grafana hooked up to the same AWS Account
![image](https://user-images.githubusercontent.com/231303/55426806-7f141f00-553a-11e9-9839-59d7ee59b275.png)

**Comment by mtanda** [comment]
I may understand your issue. It is UI issue.
Actually, I already notice the issue, but I didn't understand why it is not work.
I investigate the issue, and send PR to master.
https://github.com/grafana/grafana/pull/16356

I guess, you add query like following steps.
1. set `CacheNodeId` = `it-general-redis-001`
2. change `CacheNodeId` to `CacheClusterId`
3. try to set dimension value for `CacheClusterId`, but it doesn't show valid list for `CacheClusterId`

The workaround is removing all dimensions, and add its again.
Please try the workaround in your env.

**Comment by benholtz** [comment]
> I may understand your issue. It is UI issue.
> Actually, I already notice the issue, but I didn't understand why it is not work.
> I investigate the issue, and send PR to master.
> #16356
> 
> I guess, you add query like following steps.
> 
> 1. set `CacheNodeId` = `it-general-redis-001`
> 2. change `CacheNodeId` to `CacheClusterId`
> 3. try to set dimension value for `CacheClusterId`, but it doesn't show valid list for `CacheClusterId`
> 
> The workaround is removing all dimensions, and add its again.
> Please try the workaround in your env.

Hello @mtanda ,
There was a bug you fixed, however I not sure it solves my problem, I am in need of combined { `it-general-redis-001`, `it-general-redis-002` } metric, it seems  `CacheClusterId` is Node Name i.e. `it-general-redis-001`, not Cluster Name `it-general-redis`.  I hope this helps.

**Comment by mtanda** [comment]
hmm, I check AWS web console, and notice that.
The console show Node name as `<cache cluster id>-001`, but in CloudWatch, the Node id is 001.
The console shows `Node name`, CloudWatch use `Node id`.
If my understanding is correct, you should specify `001` to `CacheNodeId`.

To investigate more detail, would you share following command result?
```
aws cloudwatch list-metrics --namespace "AWS/ElastiCache" --metric-name CPUUtilization
```

Anyway, I believe there is no bug in Grafana, because I can display ElastiCache metrics in my env.

**Comment by benholtz** [comment]
@mtanda I agree, there may be no bug, I think Grafana is seeing what Cloudwatch sends back.  I'm seeking help getting the whole cluster though, possibly searching by AWS Tag to get the `CacheClusterId`?  Hoping you can help me with a work around.
Cloudwatch CLI output:
>         {
>             "Namespace": "AWS/ElastiCache",
>             "MetricName": "CPUUtilization",
>             "Dimensions": [
>                 {
>                     "Name": "CacheClusterId",
>                     "Value": "lt-general-redis-001"
>                 },
>                 {
>                     "Name": "CacheNodeId",
>                     "Value": "0001"
>                 }
>             ]
>         },
>         {
>             "Namespace": "AWS/ElastiCache",
>             "MetricName": "CPUUtilization",
>             "Dimensions": [
>                 {
>                     "Name": "CacheClusterId",
>                     "Value": "lt-general-redis-002"
>                 },
>                 {
>                     "Name": "CacheNodeId",
>                     "Value": "0001"
>                 }
>             ]
>         }

**Comment by mtanda** [comment]
hmm, it seems correct to set `CacheClusterId` = `lt-general-redis-001`.
So your query editor screenshot is not wrong, it is correct `CacheClusterId`.
https://github.com/grafana/grafana/issues/15984#issuecomment-479135241

Would you try to set `CacheClusterId` = `lt-general-redis-001` and `CacheNodeId` = `0001`.

Anyway, I think this is CloudWatch usage question, not Grafana.
And I'm not full time Grafana developer or support team.

@nikoalch @torkelo Would you help him?

**Comment by torkelo** [comment]
@mtanda sure, and thanks for the support you have already provided. 

It looks to be fixed now. When I select a CacheClusterId, and then a CacheNodeId I only get the NodeIds for the selected cache cluster. 

@benholtz We can update your instance today to latest stable Grafana 6.1.0 that includes this Cloudwatch fix.
