### ISSUE TITLE
Grafana 1.9.1 : Time series data request error during first time dashboard load from scripted dashboard

### ISSUE THREAD

**Issue by shankarramshivram** [grafana/grafana#1598]
Hi,

I am seeing the time series data request error every time i load the dashboard created using scripted dashboard. After the first load if i change the time picker or edit something in the dashboard the panel now loads with information. 

First load :- 
![scripted_dashboard](https://cloud.githubusercontent.com/assets/2964526/6630302/96a1d672-c8d4-11e4-96df-2a1918d50ce9.JPG)

After changing time picker or editing somethign in the dashboard panel 

![grafana_after_load](https://cloud.githubusercontent.com/assets/2964526/6630319/d0719e28-c8d4-11e4-8f1b-806db53706f5.JPG)

code snippet from my scripted dashbord js file --
https://gist.github.com/shankarramshivram/fde64c4b33bf7c038cd9#file-snippet-scripted-dashboard

**Comment by torkelo** [comment]
is that everything? Need to have the full scripted dashboard. You could also open chrome dev tools and inspect the js console for errors.

**Comment by KaiPierre** [comment]
I just expect the same kind of error with an async scripted dashboard and a moving average function : 
first time I load the dashboard I've got an error because a graphite /render call fail with : 
```
in movingAverage
    bootstrapSeconds = max([s.step for s in seriesList]) * int(windowSize)
ValueError: max() arg is an empty sequence.
```

the query is like : ```alias(movingAverage(metric.path, 5), 'my metric')```

but like shankarramshivram if I make any action on dashboard, everything become right.

**Comment by torkelo** [comment]
Yes, template variables current value needs to be valid when the dashboard loads. 

Related to this issue: 
https://github.com/grafana/grafana/issues/1255

I hope to solve this dashboard sync issue in Grafana 2.1 or 2.2 (it is very tricky)

**Comment by KaiPierre** [comment]
After test I can say that : It's working directly if template variables are initialized by url parameters ```var-XXX=value```

and we can init templated values computing options in the script calling ```datasource.metricFindQuery()``` and playing with services.$q angular promises.
