### ISSUE TITLE
Internationalization (I18N) support ?

### ISSUE THREAD

**Issue by zzj1213** [grafana/grafana#1599]
Any plan to add I18N support ?

**Comment by torkelo** [comment]
No plans, would love to support it but there has been no time. Now with the Backend coming in Grafana 2.0 there are at least some good ways to do it without affecting frontend performance.

**Comment by pygillier** [comment]
As a french speaking user and trying to push graphite/grafana to my team, I18N support is really needed. I also can help in translating into french.

**Comment by toni-moreno** [comment]
I can do translations to catalan and spanish also !!

**Comment by sqbing** [comment]
I can also help in translating into Chinese.

**Comment by hepin1989** [comment]
yeah,seems good.I could use the help too,for Chinese:)

**Comment by bergquist** [comment]
dup #448

**Comment by krongk** [comment]
How about Grafana localize now?

**Comment by Ruffianjiang** [comment]
How about Grafana localize now?

**Comment by Zuckonit** [comment]
any progress?

**Comment by kemperor001** [comment]
5 years, nothing happened.

**Comment by suess-ecbm** [comment]
Looks like there are preparations for i18n going on! Great job!
https://github.com/grafana/grafana/pull/41827
