### ISSUE TITLE
Annotations query problem with interval var

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#15994]
**What happened**:

I've just migrated to grafana 6.0.1 and I have a problem with annotations query using prometheus source with range_vector
my query looks like `delta(azeaze[$delta])` and the step of the query is `$delta` (edited) 
it used to work well in 5.2
now I have the following error

```
Annotation Query Failed
Invalid interval string, expecting a number followed by one of "Mwdhmsy"
```
`$delta` is a type interval var (edited) 

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Make sure the value of $delta is a time range `5s`, `10s` etc,  you cannot use this in a step parameter, as it expects a plain number (in seconds)

**Comment by sylr** [comment]
@torkelo that's an unpleasant breaking change, it worked well in v5.x

**Comment by sylr** [comment]
And it's uncoherent with the step parameter of panels metrics.

**Comment by sylr** [comment]
I tested and the step parameter of annotations does require the unit, I think the problem is that vars are not interpreted anymore in the step parameter, which is a regression.

**Comment by torkelo** [comment]
Ok, will investigate again, thanks for the update. There should not be a regression here, if so it’s a bug

**Comment by torkelo** [comment]
Found a feature request related to this issue: https://github.com/grafana/grafana/issues/12452
