### ISSUE TITLE
Explore: Prometheus series and labels hinting kills Prometheus instance

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#15992]
**What happened**:
Opened explore mode of any panel with Prometheus datasource which took down the Prometheus instance (or Thanos cluster).
On opening explore mode it always sends request to `/api/v1/series?match[]={le!=""}` to provide possibility to hint series names and labels. Unfortunatelly if the prometheus instance has hundreds of thousands of time series than listing of all those data is enormous load.

In version 5.x it was possible to disable explore mode so I had a way to avoid this but now there is no feature toggle. No way to stop user from doing this.  

I know that maybe it should by implemented as a limit on the Prometheus side but this situation is unfortunate. Maybe disabling hinting in explore so I don't have to forbit users to use explore at least?

**What you expected to happen**:
Explore not to overload my datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Start Prometheus instance with large number of mterics ( e.g. hundrets of thousands) and with web console enabled open explore and see how long it takes to load the `/api/v1/series?match[]={le!=""}` request.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Prometheus 2.6.1

**Comment by FUSAKLA** [comment]
Edit:
Looking at the code it's related just to the histograms
https://github.com/grafana/grafana/blob/efcbb92b3fef79ab0b497a649d7e23a328cc9d74/public/app/plugins/datasource/prometheus/language_provider.ts#L17

I'd be great to at least be able to disable the hinting in sake of the datasource health.

**Comment by davkal** [comment]
I'd make this a datasource setting: "Prevent metrics prefetching" and then you can disable this.

**Comment by FUSAKLA** [comment]
Hmm this would work just for the explore or also for suggestions in regular panel query editing?
Because there it works just fine. I's just this one unfortunate query I'm describing causing all this issues.

But even this would be great now I'm just hoping nobody opens the explore mode or I have to add proxy to forbid this one exact query

**Comment by TimSimmons** [comment]
fetching "all timeseries" for anything in Prometheus, especially for "all the histograms" is in general not a great thing. Prometheus queries that return more than a few thousand timeseries are advised against by the maintainers.

I'm probably wrong, but this looks to me like it is only looking for the names of histogram metrics:
https://github.com/grafana/grafana/blob/efcbb92b3fef79ab0b497a649d7e23a328cc9d74/public/app/plugins/datasource/prometheus/language_provider.ts#L307

When in reality it is returning every timeseries for every histogram, which will probably be 1000s of times larger than the number of actual histogram metric names, it also has to process every timeseries to see if it has or doesn't have that label. Perhaps something like
```
api/v1/label/__name__/values
```
and filter for the ones called `*_bucket`. Would be better.

Right now for me anytime someone opens explore mode and triggers this query it causes a cascading failure across multiple Prometheus instances. The latest ones went from 8GB -> 32GB of memory usage and were OOMKilled in a matter of seconds on three different instances behind my proxy.

**Comment by FUSAKLA** [comment]
Great, I tested it and looks like the issue is resolved nicely. Thanks!

**Comment by FUSAKLA** [comment]
One additional thing. The `/api/v1/series` endpoint allows to query series from some particular time range, but when not specified it uses min and max timestamp according to the code.
https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers

In our case when we are using Thanos this means it still searches in whole year of data just for hinting. 
Could we set the `start` and `end` based on the grafana selected time range?

**Comment by davkal** [comment]
@FUSAKLA yes that make sense. Do you mind opening an issue for this?

**Comment by FUSAKLA** [comment]
Sure @davkal , here it is https://github.com/grafana/grafana/issues/16844
