### ISSUE TITLE
Login in iframe not working on Grafana 6.0

### ISSUE THREAD

**Issue by ThomasVdBerge** [grafana/grafana#15991]
I updated Grafana to 6.0.1 and noticed that, when I login to it via Iframe, I get the Login Successful green popup, but the page stays on the login page.

This works fine for grafana/grafana:6.0.0-beta1.

**Comment by torkelo** [comment]
Strange, not sure we have done anything that could have caused that.

**Comment by jorkzijlstra** [comment]
We are experiencing the same iframe problem and we also can't login on 
Raspbian Stretch 8.0 using Chromium 56.0.2924.84 Build on Ubuntu 14.04

**Comment by jorkzijlstra** [comment]
It seem we are loosing the cookie after login again:

Login Request

```
Request URL: https://{host}/login
Request Method:POST
Status Code:200 
Remote Address: {host ip}:443
```

Response Headers
```
content-length:23
content-type:application/json
date:Thu, 14 Mar 2019 14:57:06 GMT
set-cookie:grafana_session=8b74476abfcdaef042b42e9bd6bd106d; Path=/; Max-Age=2595600; HttpOnly; SameSite
status:200
```

Redirect
```
Request URL: https://{host}/
Request Method:GET
Status Code:302 
Remote Address: {host ip}:443

```

Request headers
```
:authority: {host}
:method: GET
:path: /
:schema: https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding:gzip, deflate, sdch, br
accept-language:en-GB,en-US;q=0.8,en;q=0.6
referer:https://{host}/login
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.84 Safari/537.368%2
```

**Comment by Jean-BaptisteJ** [comment]
Same here with Grafana 6.0.0 on Firefox 65.0.2 and Google Chrome 72.0.3626.121

**Comment by marefr** [comment]
Same problem/solution as 
https://github.com/grafana/grafana/issues/15714#issuecomment-468953515 ?

**Comment by scthi** [comment]
The above works! Thanks a lot.

**Comment by deanlennox** [comment]
Login iframe displays logged in and immediately returns to login screen
Grafana v7.1.3
cookie_samesite = disabled (None wont work on chrome)
allow_embedding = true
Not sure if HTTPS required? Only able to run as http

**Comment by thomascrha** [comment]
I'm seeing the same problem as @deanlennox - where you able to fnd a solution ?

**Comment by tongtie** [comment]
> I'm seeing the same problem as @deanlennox - were you able to find a solution ?

when I had set cookie_samesite = none.

It worked when I changing to firefox.

**Comment by MatejVeic** [comment]
I had the same problem. After logging in, I'd get a green popup but was returned to the login screen again. After trying everything that was suggested, we solved it by modifying org_name parameter in grafana.ini.

[auth.anonymous]
      enabled = true
     org_name = [your_org_name]
      org_role = Viewer

[your_org_name] has to be equal to previously configured org_name of Grafana.

**Comment by Quelklef** [comment]
Using `cookie_samesite = none` worked for me to allow embeds of panels. However, `cookie_samesite` is how Grafana protects against CSRF, as per https://github.com/grafana/grafana/issues/1441. Does this mean that one must choose between having working iFrame logins and having CSRF protection?

**Comment by Quelklef** [comment]
Looks like possibly Grafana has CORS set up in such a way to allow embeds via iFrames but disallow arbitrary CSRF

**Comment by hterik** [comment]
Since 9.1 you can use JWT to authenticate iframes without cookies. 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/
