### ISSUE TITLE
Non-metric panel fails dashboard to load in master

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#15993]
I'm trying to load a dashboard containing Problems panel from Zabbix plugin. Dashboard fails to load with error:
![Screenshot from 2019-03-14 12-29-13](https://user-images.githubusercontent.com/4932851/54346067-73c58600-4655-11e9-922f-8de3b31e8b2f.png)
```
TypeError: Cannot read property 'refId' of undefined
    at PanelModel../public/app/features/dashboard/state/PanelModel.ts.PanelModel.ensureQueryIds (PanelModel.ts:130)
```
Grafana built from `master` at 4bbd6ab79cc3b023a8e671eb8fe21f007a492639

Panel has option `"dataFormats": [],` in the `plugin.json` file, so in this case `PanelModel` shouldn't validate queries:
https://github.com/grafana/grafana/blob/9e7d1f42753495254c7a9220161b0818decbf58a/public/app/features/dashboard/state/PanelModel.ts#L122

**Comment by torkelo** [comment]
Does your panel have a property called targets? 
there is a check there for:
 if (this.targets) {

**Comment by alexanderzobnin** [comment]
It's a little bit unusual, but `targets` is an object:
```js
targets: {
  datasource_name_1: {},
  datasource_name_2: {},
...
}
```

**Comment by alexanderzobnin** [comment]
I can switch to another schema I think, using `targets` name causes problems in Grafana 6.

**Comment by alexanderzobnin** [comment]
Just found that it's tricky - `PanelModel` checks targets before plugin can do anything. So migration to another name in plugin doesn't solve this - dashboards are broken still.
