### ISSUE TITLE
Microsoft Teams is not loading Graph Images.

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#15997]
**What happened**:
Hi Team,

I've been using Grafana for like 6 months and It's working perfectly. The only Bug I'm seeing is that the graph image is not loading on Microsoft Teams unless we click "View Graph" button

![graph](https://user-images.githubusercontent.com/22325249/54355038-1134b000-467e-11e9-818a-a02864565dd7.PNG)

I tried making changes in external_image_storage to local and we don't have permission to add s3,webdav,gcs or azure_blob. 

![local](https://user-images.githubusercontent.com/22325249/54355164-5e188680-467e-11e9-9716-4ef3253a80cf.PNG)

I thought when I updated Grafana to v6  the issue will solve, but still I'm getting that same bug.

Also thanks team for providing us with a great platform for viewing dashboard! It's really cool! 

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Graphite
- OS Grafana is installed on: CentOS

Please hep me fix this,
Thanks in advance!

Best,
Siddharth

**Comment by torkelo** [comment]
> I tried making changes in external_image_storage to local and we don't have permission to add s3,webdav,gcs or azure_blob.

you need to in order to see images

**Comment by Siddhu1096** [comment]
@torkelo , In order as in ?

**Comment by torkelo** [comment]
Sorry, you need to configure an external image store.

**Comment by Siddhu1096** [comment]
@torkelo , So you're saying external_image_store = local won't work? We need to configure in azure/webdav/s3?

**Comment by torkelo** [comment]
yes

**Comment by Siddhu1096** [comment]
Okay Thanks for your time! 
Good day!

**Comment by arifaboobaker** [comment]
Does it worked .. ? Alerting from grafana to microsoft teams ?

**Comment by Siddhu1096** [comment]
Nope. @arifaboobaker  Are you facing the same issue?

**Comment by arifaboobaker** [comment]
I can’t even get notifications on Microsoft teams channel.

**Comment by Siddhu1096** [comment]
Make sure you've connected your webhook properly with Grafana

**Comment by Siddhu1096** [comment]
Alerting works for me. But the image of the alert is not popping up.

**Comment by arifaboobaker** [comment]
I have got the teams channel url and updated it in the alert notification. But am getting any alert. If I change it to email and update it with teams channel mail I’d am getting mail notification of teams channel.
How did u manage to get alert notification to teams channel .. any config changes?

**Comment by Siddhu1096** [comment]
Normal url of the channel linking with Grafana alerts won't work.

**Comment by Siddhu1096** [comment]
You need to connect it using some connector for example Webhook.

**Comment by arifaboobaker** [comment]
Okay, 1st I need to configure webhook on teams channel ?

**Comment by Siddhu1096** [comment]
Yup. Do a link will generate. That link to be added on Grafana alerts.

**Comment by arifaboobaker** [comment]
Okay I will test it on Monday and update you.

**Comment by arifaboobaker** [comment]
Hi,
I have configured webhook. Now am able tor receive notifications but images are getting displayed.

**Comment by marefr** [comment]
@arifaboobaker you need to configure an external image store as Torkel mentioned above

**Comment by Siddhu1096** [comment]
@arifaboobaker "But images are getting displayed?? " Then what is the real problem?

**Comment by arifaboobaker** [comment]
Oops typo .. images are not getting displayed .. its just post the notification with a blank image

**Comment by arifaboobaker** [comment]
> @arifaboobaker you need to configure an external image store as Torkel mentioned above

So how should i do this .. should i edit the config file from back end ?

**Comment by marefr** [comment]
http://docs.grafana.org/installation/configuration/#external-image-storage-s3 and below you find other alternatives.

**Comment by arifaboobaker** [comment]
Thanks @marefr .

@marefr @Siddhu1096 Do you have a working config to show me as an example.

**Comment by Siddhu1096** [comment]
external_image_storage = local won't work for Microsoft Teams.

**Comment by arifaboobaker** [comment]
yeah i have tried that. Now creating a container in storage account of azure and trying to add it.
If you have a working config please share it.

**Comment by arifaboobaker** [comment]
I have done the below on and still no luck.

#################################### External Image Storage ##############
#[external_image_storage]
# You can choose between (s3, webdav, gcs, azure_blob, local)
#provider = local

[external_image_storage.azure_blob]
account_name = ihggraphing
account_key = bajkdbasjkda8q0wbjdabskd392q3n232320454sdasdasdasd
container_name = grafanaimages

#[external_image_storage.local]
# does not require any configuration

**Comment by Siddhu1096** [comment]
Remove that # in front of external image storage and provider.

**Comment by Siddhu1096** [comment]
If you're using azure, provider = azure_blob

**Comment by arifaboobaker** [comment]
Yes, it worked. 

Thanks Everyone 👍

**Comment by ZealousMacwan** [comment]
@Siddhu1096 @torkelo 
Hi,

I just started with grafana notification, How to write customized message body, and How to add screenshot,current value, threshold that raised alert in MSFT notification. I am also not getting view graph button.

Thanks,
 
![image](https://user-images.githubusercontent.com/22982363/68944660-63613e80-07d4-11ea-85d1-528647012166.png)

**Comment by marefr** [comment]
@ZealousMacwan Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

For reference, see Microsoft Teams [here](https://grafana.com/docs/alerting/notifications/#all-supported-notifiers) it only supports external images (publicly available). More information about how to setup publicly available images, see https://grafana.com/docs/alerting/notifications/#external-image-store. 

View graph button should be displayed when image is publicly available.
