### ISSUE TITLE
Column headers in a table not visible in IOS

### ISSUE THREAD

**Issue by jimnagy** [grafana/grafana#16005]
**What happened**:
The column headers in tables are not visible in IOS, although you can still click them to sort.

**What you expected to happen**:
Column headers to be visible.

**How to reproduce it (as minimally and precisely as possible)**:
Load any dashboard with a table panel on an iphone or ipad, for example:
https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1

**Anything else we need to know?**:
If you click on the panel title and click view, the column headers are there, but if you click edit then they are not.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: All of them I think
- OS Grafana is installed on: Kubernettes
- User OS & Browser: IOS/Safari
- Grafana plugins:
- Others:

**Comment by Gauravshah** [comment]
I checked on grafana 5.x and problem exists from an older version. Seems like something do with absolute position of headers

**Comment by Gauravshah** [comment]
its related to `overflow:scroll` on `table-panel-scroll`.  it hides the element occupying space outside its context

**Comment by daniellee** [comment]
Tested now on iOS 14 and can see the column headers in edit mode. Can also click on them to sort. This is with the new React table panel and not the old AngularJS panel which this issue refers to. Closing but can re-open if there are still issues.
