### ISSUE TITLE
Postgres' $__timeFilter()/$__timeFrom()/$__timeTo() don't respects local timezone

### ISSUE THREAD

**Issue by living42** [grafana/grafana#16003]
**What happened**:

I am select time range from '2019-03-13 00:00:00' to '2019-03-13 23:59:59'. then i saw the  macro `$__timeFilter(dt)` translate to `dt BETWEEN '2019-03-12T16:00:00Z' AND '2019-03-13T15:59:59.999Z'`. Even i'm setting the timezone to my locale, which is PRC

**What you expected to happen**:

macro `$__timeFilter(dt)` translate to `dt BETWEEN '2019-03-13T00:00:00Z' AND '2019-03-13T23:59:59.999Z'`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set you browser environment to PRC timezone
2. Open Grafana site, go to some graph, select time range
3. Check the generated sql

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Postgres
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by living42** [comment]
Some source code reading, i found that these macros will always replaces to UTC time

**Comment by torkelo** [comment]
that is correct these expect time variables to be in UTC
