### ISSUE TITLE
Option to synchronize time ranges in Explore Split

### ISSUE THREAD

**Issue by davidhao3300** [grafana/grafana#16009]
**What would you like to be added**:
Add an option to synchronize the time ranges between the two panels in Explore Split. When a user changes the time range on one side, either by using the date picker or highlighting a time range in the graph, the change is reflected on the other side as well.

**Why is this needed**:
Seems like a time-saving thing to have when trying to examine metrics in one panel and looking at corresponding logs in the other panel.

Didn't see this feature mentioned in the roadmap (https://github.com/grafana/grafana/issues/15999)

**Comment by sauldhernandez** [comment]
Would love to see this implemented. Simple to implement and it would save plenty of time.
