### ISSUE TITLE
quotation marks usage in grafana log

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#16000]
Hi everyone,

I'm currently try to write some grok filters for the grafana.log
I noticed that quotation marks are only used, when the text has a whitespace in it and on some conditions in the referer.
So you can actually have:

referer="https://localhost:9443/d-solo/000000454/test?panelId=4"
referer=https://localhost:9443/d/000000033/test
referer=

msg="Request Completed"
msg=rendering

Is there a specific reason that not all outputs can have quotation marks? Even if no string is given?

Best regards,
Patrick

**Comment by torkelo** [comment]
you can switch to json output for a more parse friendly format.
