### ISSUE TITLE
A Grafana session related question

### ISSUE THREAD

**Issue by sunnut** [grafana/grafana#16018]
1. The version is 6.0.0

2. At login page, when I save something not nil in session by c.Session.Set, but cannot get it by c.Session.Get , the result is nil

**Comment by bergquist** [comment]
`c.Session` is about to be deprecated. It's only used for auth proxy right now but we are removing it completely soon.

**Comment by sunnut** [comment]
Oh，@bergquist but how can i save something such as verify code in the back-end now?

**Comment by bergquist** [comment]
Using the remotecache service.
Ill soon write PR giving more details about how to use it.

Depending on what your doing you could also use cookies. For OAuth logins we use cookies and hash values + salt for validation.

**Comment by sunnut** [comment]
@bergquist Thinks. I want to add the verification code ability to the login page.

**Comment by sunnut** [comment]
Hi, @bergquist Could you tell me how to use it in short words now? I need it recently.Thanks.

**Comment by sunnut** [comment]
@bergquist help^_^

**Comment by sunnut** [comment]
@bergquist when will you push PR?
