### ISSUE TITLE
OpenTSDB panel - Incorrect target for plotted curve

### ISSUE THREAD

**Issue by saurabhagrawal-fk** [grafana/grafana#1601]
If an openTSDB graph panel with multiple metrics is created, and the openTSDB datasource returns a data set smaller than the number of queried metrics, then the panel's legend and tooltips are incorrect.

Assume that the openTSDB's HTTP POST endpoint */api/query* is hit with payload 
```javascript
{
    "start": 1356998400,
    "end": 1356998460,
    "queries": [ Q1, Q2 ]
}
```
The response will typically look like: { [ R1, R2 ] }, which contains 2 data series - R1 corresponding to Q1, and R2 corresponding to Q2. 

However, if openTSDB has no data corresponding to Q1, but has data for Q2, then the response would be { [ R2 ] }. Grafana does not handle this case well. It plots the resultant data R2, but labels it wrongly with Q1's alias, instead of Q2's alias. This can result in very misleading dashboards.

**Comment by torkelo** [comment]
To solve this all queries need to be issued one at a time, or is there a fool proof way to correlate query to response? OpenTSDB need to implement that I think

**Comment by saurabhagrawal-fk** [comment]
See http://opentsdb.net/docs/build/html/api_http/query/index.html#response
To correlate the response to query, OpenTSDB response body contains the "metric" and "tags" fields. Therefore, there is no fix required in OpenTSDB.

**Comment by torkelo** [comment]
If I have two queries like
1) metric: cpu, tags: host=*
2) metric: cpu, tags: host=my_server

I think your code does not handle scenario 1, and if you have both 1 & 2 there is not good way to correlate them

**Comment by saurabhagrawal-fk** [comment]
> I think your code does not handle scenario 1

Good catch. But I've considered these scenarios, and more as well. 
For example, the query like - 
metric: cpu, tags: host=my_server | other_server
is not handled either.

> and if you have both 1 & 2 there is not good way to correlate them

Yes, in that case, metric data for host=myserver will be returned twice, and therefore, there is no perfectly correct way of correlation. 

However, I believe this change https://github.com/grafana/grafana/pull/1605 is an improvement over the current implementation because:
- The mapping function in change 1605 never returns a false positive, and hence never creates a misleading dashboard.
- As correctly pointed out in the previous comment by Torkel, the mapping function in change 1605 may return false negatives (due to the strict equality comparisons of tags and metrics), but the only downside of it is that the whole metric like "cpu {host=my_server}" will be displayed in the legend and tooltip, instead of an alias.
- Most importantly, **the current implementation may return false positives** because it always maps metric[i] to target[i], which can lead to misleading dashboards. For example, say I have two queries:
  - metric = errorRate, tags: host=host1 (alias is "host1 errors")
  - metric = errorRate, tags: host=host2 (alias is "host2 errors").
  If there is no data for the first query (i.e. there were no errors on host1 in the queried time period), then the current  implementation would plot the data for the second query, but wrongly label it as "host1 errors".  In fact, this is happening in our dashboards, and that's how I discovered this bug.

**Comment by kylemallory** [comment]
Consider this: #1344 and #1434.  I do have an issue open with OpenTSDB to implement a queryId that can be used to reference time series responses back to the request.  There is no ETA on implimentation though (per my comments in #1434).

**Comment by torkelo** [comment]
The only option I think I would be ok with is to issue one opentsdb request per query. This error prone matching of query to returned series just seems like to much complexity and asking for bug reports.

**Comment by saurabhagrawal-fk** [comment]
The originally reported problem of wrong label for a plotted metric is extremely severe, and IMO, requires a fix ASAP.  The severity of this issue can be justified because it may result in misleading dashboards, and wrong diagnosis of "on call" problems.

- One openTSDB request per target metric is obviously a fool proof solution, but I'm not sure of the performance impact it would have. Any inputs on this?
- Now that we're aware of this mapping problem, consider the number of bugs that could be reported in the current implementation. I'm quite sure this change would fix at least some of them.

**Comment by kylemallory** [comment]
I agree with Saurab.  I don't see this as an "inconvienience"...   The option of only doing a single query isn't realistic either; the nature of TSDB queries is that you can, by design, formulate requests that result in multiple time-series; you're essentially breaking significant functionality on the TSDB side.  It's you're project, Torkelo, but if the solution is to limit a single response to a single query, I'll have to stop using Grafana; Many of my dashboards have too many time-series on them to try and manually recreate them, one query at a time.

**Comment by torkelo** [comment]
@kylemallory it would require a change like that, it would just be the OpenTSDB datasource that had to issue multiple requests (one per query row in the metric editor tab). I agree this this needs to be solved somehow (soon). I am currently on focus week with the Raintank team complete a few remaining issues for Grafana 2 release. I will try to look into this next week when I am back home. 

I think the main issue here needs to be solved by the OpenTSDB team, but a temporary work around needs to be implemented soon in Grafana.

**Comment by kylemallory** [comment]
Agreed.  Solve it in TSDB, but work around it until then...

**Comment by torkelo** [comment]
Added simple matching, on metric name and tag keys (not tag values). 

OpenTSDB query api does not seem to support having multiple queries with same metric name and different tag filters (just returns a single series for me). 

This is how the matching logic looks like:
```javascript
function mapMetricsToTargets(metrics, targets) {
      return _.map(metrics, function(metricData) {
        return _.findIndex(targets, function(target) {
          return target.metric === metricData.metric &&
            _.all(target.tags, function(tagV, tagK) { return metricData.tags[tagK] !== void 0; });
        });
      });
    }
```

**Comment by torkelo** [comment]
Also added alias patterns, see #1344 for more details
