### ISSUE TITLE
Alert notification channel has empty `uid` field.

### ISSUE THREAD

**Issue by titosand** [grafana/grafana#16012]
**What happened**:
A Grafana notification channel's UID is not visible from the `/api/alert-notifications/<uid>` endpoint. uid's are visible from the `/api/alert-notifications` endpoint.

**What you expected to happen**:
I would expect a Grafana notification channel's UID to be visible from the `/api/alert-notification/<uid>` endpoint. You see something like this 

`{"id":1,"uid":"" ....}`

**How to reproduce it (as minimally and precisely as possible)**:
Create a new alert notification channel and compare the two endpoints mentioned above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Any
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser:N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
not sure why, looks like a bug here https://github.com/grafana/grafana/blob/master/pkg/models/alert_notifications.go#L28 

should not be "-" in the json attribute.

**Comment by titosand** [comment]
Hrm this is also worse than I thought, it appears that looking up a notification channel using `/api/alert-notifications/<uid>` _always_ returns the notification channel with `id:1`.  I didn't even notice that as I was describing the other issue. Almost certainly these two are very related. :(

**Comment by marefr** [comment]
@titosand have opened a PR with fix for your initial problem and other enhancements regarding alert notification channels http api. 

> it appears that looking up a notification channel using /api/alert-notifications/<uid> always returns the notification channel with id:1

This has also been fixed in PR, but please note that before my PR is merged the alert notification channels http api doesn't support getting a notifcation channel by uid.

**Comment by titosand** [comment]
Thank you!
