### ISSUE TITLE
Add possibility to see events details

### ISSUE THREAD

**Issue by Nihn** [grafana/grafana#1602]
Now only way to see event's details in grafana is to move mouse cursor over it. But it I want to copy something from it (e.g. latest git hash added to deploy event data) there is now way to do so.
It would be nice go get separate window or something like that with events details (name, tags and data) when clicking on it on chart.

**Comment by torkelo** [comment]
I would like to do this, but the current tooltip impementation does not allow it :(

https://github.com/grafana/grafana/issues/1588

**Comment by mlowicki** [comment]
@torkelo are you open for either investigate if it's possible with current implementation and if not to maybe replace it with something else? I guess we could work (together with @Nihn ) on preparing some pull request.

**Comment by torkelo** [comment]
I did investigate moving to qtip2 but it was too slow, and did not have time to investigate why. Maybe better option is to find a way to make hovering on the the current tooltip implementation would be easier. And any help is welcomed

**Comment by toni-moreno** [comment]
Hi @torkelo , I and my colleague @ricardmestre did fork with qtip2 only for Dashboard and graph descriptions. 

https://github.com/ricardmestre/grafana/commits/add_dash_description_ES_Influx ( not PR yet)

This work could  be good for event details also.

qtip2 could be used for slow things and old tooltip for plots.

What do you thing about?

**Comment by ricardmestre** [comment]
+1!
