### ISSUE TITLE
phantomjs: timeout for invalid panel (security issue)

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#16028]
**What happened**:
On requesting a direct rendered image with an invalid panelld the requests hang until timeout.

**What you expected to happen**:
On detecting the panelId was invalid and error should be raised.

**How to reproduce it (as minimally and precisely as possible)**:
Use the share -> direct rendered option and then edit the URL to an invalid panelID.

**Anything else we need to know?**:
One issue notices was that the onError handler does call: `phantom.exit();` so even with a timeout the process just hangs.

Suggested fixes:
* Allow the timeout to be configured
* Add `phantom.exit();` to `render.js` `page.onError` handler.
 https://github.com/grafana/grafana/blob/29f1c9259a572106d7b8e17d7f122cb0a89d7de4/tools/phantomjs/render.js#L48
* Detect no panels or invalid panelId and return before timeout with an error.

It should be noted that this could be used as a DoS vector to any grafana instance, hence flagging as a security issue too.

**Environment**:
- Grafana version: 5.2.3
- Data source type & version: Influx
- OS Grafana is installed on: docker container on ubuntu
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
how is this a DoS issue?

**Comment by stevenh** [comment]
A user can submit requests which will always timeout, during which time its using those resources, and hence can use this fact to consume all of the hosts resources.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by aknuds1** [comment]
I made a corresponding [issue](https://github.com/grafana/grafana-image-renderer/issues/158) in the image renderer.

**Comment by aknuds1** [comment]
Closing in favour of image renderer issue, since it should be fixed there.
