### ISSUE TITLE
"Relative time" in panels does not work when dashboard is shared

### ISSUE THREAD

**Issue by rdsubhas** [grafana/grafana#16024]
## Given

We have a panel with `Relative Time: -1h` set:

![image](https://user-images.githubusercontent.com/1570745/54433585-89f24580-472c-11e9-84b6-c2f4237e26d1.png)

The panel correctly shows `Last 1 hour` when I use *ANY* relative time in the dashboard, like `Last 3 hours`, or even `from now-2d to now-1d`.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/1570745/54428840-05e59100-471f-11e9-9078-aa1db95d55f5.png">

## **What happened:**

With the exact same dashboard above, with the panel showing `Last 1h` and everything working correctly, we click `Share dashboard` and share this with another grafana user.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1570745/54428938-5fe65680-471f-11e9-90fe-404f4465f16f.png">

BUT - when the other user opens this, they **don't see** `Last 1h` in the panel. **All panels where relative time `-1h` is used are showing VERY different numbers.**

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/1570745/54429095-de42f880-471f-11e9-8d0f-3af4b02ffb2c.png">

## **What you expected to happen:**

We expected that, if we share dashboard, panels with `Last 1 hour` would remain `Last 1 hour`.

## **How to reproduce it (as minimally and precisely as possible)**:

* Create a panel with any data source or query, with `Relative Time: 1h` set
* See that it shows `Last 1 hour`
* Click `Share dashboard`
* Open the shared link
* `Last 1 hour` disappears

## **Environment**:
- Grafana version: 6.0.1
- Data source type & version: tested with ElasticSearch & Graphite
- OS Grafana is installed on: Linux (official docker image)
- User OS & Browser: Firefox, Chrome, Safari
- Grafana plugins: None

## **Anything else?**:

We use a lot of `Overview` panels with `Last 1 hour` (relative time) in Grafana. Every time we share dashboards, all those overview panels show way different numbers, and this causes confusion. It's hard to spot the missing "Last 1h" in the top.

We thought hard whether to classify it as an "Enhancement" or "Bug". Since this breaks Grafana's dashboard sharing functionality (different behavior for a shared dashboard), and because it gives rise to very different metrics reported in grafana for the *exact same time range*, we decided to file it as a bug. Please let us know if any other information needed...

**Comment by rdsubhas** [comment]
Update: We checked the official docs: http://docs.grafana.org/reference/timerange/

> The panel relative time override is only active when the dashboard time is also relative.

So it's quite clear about the feature. What it doesn't look to cover is the ability to share dashboards. Basically any dashboard with `Relative Time` will have different numbers when shared. If you think this is not a bug, could you please evaluate it as an enhancement :)

**Comment by torkelo** [comment]
you have to disable the "current time range" checkbox so that the share link will include the relative time range instead of the absolute time range. It's a bit unintuitive I know.
