### ISSUE TITLE
0 value causes Cannot read property 'length' of undefined error on gauge visualization

### ISSUE THREAD

**Issue by braunreyes** [grafana/grafana#16027]
**What happened**:

Created a gauge single stat in grafana 6.0.1 using postgres data source.

Using a query that results in value of zero is causing an 'Cannot read property 'length' of undefined' error.

Easy way to recreate is create a single state gauge using a query of:

select 0 as "value";

![image](https://user-images.githubusercontent.com/11067272/54443302-5accdb80-470e-11e9-8e80-84090c96e707.png)

**What you expected to happen**:

I would expect a gauge with zero value

**How to reproduce it (as minimally and precisely as possible)**:

add a postgres datasource
create new dashboard with new gauge visualiztion
set query type to table
add query:
select 0 as "value";
should trigger the error

**Anything else we need to know?**:

I had to set zero values to 0.001 to get it to work

select 0.001 as "value";

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: postgres 10.6
- OS Grafana is installed on: using official docker image for 6.0.1
- User OS & Browser: OSX and Chrome
- Grafana plugins: gauge
- Others:

**Comment by torkelo** [comment]
The gauge panel does not support table data yet, needs a better error handling for it :) https://github.com/grafana/grafana/issues/14554

**Comment by dudusakharovich** [comment]
@braunreyes, @torkelo  - Hey,

Sorry to bother you, I also tried to add Postgressql data source (Actually Amazon RDS service) version 10.6, but for some reason always receiving error "unexpected EOF" - Do you know what is wrong with my configuration ?

![image](https://user-images.githubusercontent.com/24862189/54882475-0094ee80-4e63-11e9-9a2c-298c36684a13.png)

**Comment by braunreyes** [comment]
@dudusakharovich try setting ssl mode to require

**Comment by dudusakharovich** [comment]
@braunreyes - Now it throws a different error:

![image](https://user-images.githubusercontent.com/24862189/54883245-810c1d00-4e6c-11e9-93aa-be8904d40b8c.png)

**Comment by torkelo** [comment]
This should be fixed in 6.1

**Comment by braunreyes** [comment]
confirmed it works!  new thresholds are dope as well!
