### ISSUE TITLE
General Backend Roadmap

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#16026]
This roadmap issue has now morphed into a project board https://github.com/grafana/grafana/projects/15

**Comment by alexanderzobnin** [comment]
Datasource plugin has only one method now - `Query()`
https://github.com/grafana/grafana-plugin-model/blob/84176c64269d8060f99e750ee8aba6f062753336/go/datasource/service.go#L11
I think it's might be helpful to have some other methods. Example: I want to implement caching proxy for plugin, but don't want to completely rewrite plugin as a backend plugin. In this case method like `Proxy()` would be very helpful. This method should takes HTTP request from plugin and be able to modify it. Something like:
```go
type DatasourcePlugin interface {
	Query(ctx context.Context, req *DatasourceRequest) (*DatasourceResponse, error)
	Proxy(ctx context.Context, req *DatasourceHTTPRequest) (*DatasourceHTTPResponse, error)
}
```
Datasource will use method like this:
```go
func (plugin *MyDatasource) Query(ctx context.Context, httpReq *datasource.DatasourceHTTPRequest) (*datasource.DatasourceHTTPResponse, error) {
	// Check if response cached and return cached result
	resultFromCache := getFromCache(httpReq)
	if resultFromCache != nil {
		return resultFromCache, nil
	}

	// Do something with request payload
	httpReq.body = injectRequestData(httpReq.body)

	// Make query through Grafana
	return grafanaBackend.request(httpReq)	
}
```

**Comment by bergquist** [comment]
Hm. I'm kinda reluctant to this. 
Caching proxy sounds like a good idea but wouldn't it be better if that was managed within the `Query` function?

**Comment by alexanderzobnin** [comment]
My motivation is
1. Be able to cache and proxy queries without reimplementing the whole query engine on the backend.
2. Zabbix plugin security problems (move authentication to the backend). Zabbix uses auth tokens that should be a part of query payload (it's not possible to use basic auth or HTTP headers), so I have to inject auth token into the query body on the backend side.

**Comment by torkelo** [comment]
Not sure either, but maybe, it would be like a different type of backend plugin, a "proxy" plugin.

**Comment by marefr** [comment]
Closing this in favor of #20740
