### ISSUE TITLE
Plugin Table - Query Mode: Triggers - Select groups

### ISSUE THREAD

**Issue by moisesreis** [grafana/grafana#16032]
I can not select just one group in the filter: 

Example: http://play.grafana-zabbix.org/d/000000088/system-status-dashboard?orgId=2

Select only one group:
![image](https://user-images.githubusercontent.com/9301720/54453576-5fa58580-4736-11e9-8a71-81c13807fe3c.png)

Exhibition:
![image](https://user-images.githubusercontent.com/9301720/54453686-94194180-4736-11e9-9362-d19fe572baef.png)

**Environment**:
- Grafana version: Grafana v5.4.3
- Data source type & version: alexanderzobnin/grafana-zabbix 3.10.1
- OS Grafana is installed on: CentOS 7
- User OS & Browser:
- Grafana plugins: Table

**Comment by torkelo** [comment]
please open in Zabbix plugin repo: https://github.com/alexanderzobnin/grafana-zabbix
