### ISSUE TITLE
Make label rendering optional for labels that don't exist on metrics in Prometheus

### ISSUE THREAD

**Issue by acedrew** [grafana/grafana#16041]
**What would you like to be added**: Currently if a metric is missing a label that you've included in the legend format, 
# Current Behavior
Series with labels {'label1": "value1, "label2": "value2", "label3": "value3"}
Template string: "Readable Label: {{ label1 }} - {{ label2 }} - {{ label3 }}"
Rendered Result "Readable Label: value1 - value2 - value3

Series with labels {'label1": "value1, "label3": "value3"}
Template string: "Readable Label: {{ label1 }} - {{ label2 }} - {{ label3 }}"
Rendered Result "Readable Label: value1 - label2 - value3

# Proposed Change

Series with labels {'label1": "value1, "label3": "value3"}
Template string: "Readable Label: {{ label1 }} {{ - || label2 }} {{ label3 }}"
Rendered Result "Readable Label: value1 - value3

**Why is this needed**:
Sometimes you may want to show values for mixed cardinality metrics in the same visualization, and still maintain readable and friendly legend formats, this feature allows additional flexibility to the user in that situation. 
However, this does have the potential to be precedent setting for other datasources, so it's worth consideration to make sure it's at the right abstraction level. My goal in this implementation was to leave all existing legend formats unaffected with no breaking changes.

**Comment by acedrew** [comment]
Proposed PR is #14523

**Comment by Hixon10** [comment]
@torkelo hello! Can we implement this feature? I mean, what should I do to have this feature in master branch 😃 

I like @acedrew proposal syntax, but would you like to propose something else, or we can use it?

**Comment by torkelo** [comment]
We could just render empty string for labels that do not exist ? PR is welcome

**Comment by Hixon10** [comment]
@torkelo I have one question. Someone wants to have empty string for labels that do not exist, someone else wants to have current behavior. How we should configure render algorithm for labels that do not exist?

**Comment by torkelo** [comment]
why would you want the current behavior?

**Comment by Hixon10** [comment]
@torkelo I don't 😃  I want to have empty string, as you proposal. I worry about other users.

**Comment by Hixon10** [comment]
Proposed PR is https://github.com/grafana/grafana/pull/22355

**Comment by Hixon10** [comment]
@torkelo hello, could you help with review of this PR?
