### ISSUE TITLE
Grafana Search API

### ISSUE THREAD

**Issue by deepaksundar** [grafana/grafana#16049]
**What happened**:
I have around 7500 dashboards in an grafana org, but when I use the /search api to get the list of all dashboards, it is responding with only 3400 dashboards. I've also tried by increasing the LIMIT parameter to 50000, but still it doesn't work.

**What you expected to happen**:
It should have returned all the 7500 dashboards available

**How to reproduce it (as minimally and precisely as possible)**:
Create 7500+ dashboards in an org and try listing out dashboards using /search api

**Anything else we need to know?**:

**Environment**:
- Grafana version: v5.4.0
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What backend SQL data source do you use? Do you use any folders?

**Comment by deepaksundar** [comment]
We use postgres db as a backend

**Comment by azhiltsov** [comment]
Is it about the same?
https://github.com/grafana/grafana/issues/12582
