### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#16044]
There is Google Tag Manager ID in /conf/defaults.ini file on github, but I cannot find it in /etc/grafana/grafana.ini. How can I configure Google Tag Manager?

**Comment by torkelo** [comment]
you might have an installation from before it was added (Grafana upgrades do not overwrite / update your existing config file). 

Just add 
google_tag_manager_id = YOUR_TAG_ID 

under [analytics] section

**Comment by szerwi** [comment]
> you might have an installation from before it was added (Grafana upgrades do not overwrite / update your existing config file).
> 
> Just add
> google_tag_manager_id = YOUR_TAG_ID
> 
> under [analytics] section

Ok, thank you. BTW, should I type contener ID here or account ID?
