### ISSUE TITLE
Elasticsearch Alias processes once, does not update legend when template variable changes

### ISSUE THREAD

**Issue by acedrew** [grafana/grafana#16040]
**What happened**: Using a $var in an elasticsearch alias, as soon as you finish typing it replaces it with the interpolated value. If you exit the query editor and change the value of the referenced variable, the legend retains the statically interpolated value.

**What you expected to happen**: Interpolation on legend values should happen at query time, so that changes to the template variables are reflected in the legend

**How to reproduce it (as minimally and precisely as possible)**:
Create an elasticsearch query based on a template variable, input the template variable in the alias field, return to dashboard and update template variable value

**Anything else we need to know?**:

**Environment**: Chrome 72.0.3626.121
- Data source type & version: Elasticsearch 6.5.4
- OS Grafana is installed on: Ubuntu 18.04 Grafana 6.01
- User OS & Browser: Chrome 72.0.3626.121
- Grafana plugins: N/A
- Others: Related to #4075 #6143 and #14804

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by acedrew** [comment]
@torkelo found today that template variables in the "Script" field of Elasticsearch queries are never processed, you want to include in this issue or should I create a separate one?

**Comment by marefr** [comment]
@acedrew please open a separate issue for this since it's a new feature. Thanks
