### ISSUE TITLE
Share row panel

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#16042]
**What would you like to be added**:
The row is a kind of panel. It would be nice to be able to also share the whole row with its panels inside.

This Share option is currently only available for every panel except row.

![image](https://user-images.githubusercontent.com/327717/54493174-1b002280-48cd-11e9-91da-ecf032d3691c.png)

**Why is this needed**:

Row usually groups panels that go together. For example I usually specify the main name as a row title and then the panels within have only metric name as a title.

Take this group as an example. I have row title with datacenter name and then two panels within. First one shows traffic, the second shows packets.

<table>
  <tr>
    <td colspan="2"><i>DataCenter name</i></td>
  </tr>
  <tr>
    <td>Traffic</td>
    <td>Packets</td>
  </tr>
</table>

Now, I cannot share it as a whole group. I can only share single panels. When the single panel is shared, the title is "Traffic". So there's also no way to recognize from which datacenter the traffic comes from. And repeating datacenter name for each panel is kind of clumsy.

If it was possible to share the whole group, the row title would satisfyingly describe panels within. Also complete view on the whole datacenter metrics would be shareable as a whole piece instead of having share each panel alone.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by milinpatel13298** [comment]
Was this feature request ever re-submitted in the Discussions area? I am not able to find it. I would like to follow this request, if it already exists.
