### ISSUE TITLE
Consider a switch from tslint to eslint

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#16053]
**What would you like to be added**:
I would like us to consider a switch from from tslint to eslint

**Why is this needed**:
Given the recent posts from tslint (https://github.com/Microsoft/TypeScript/issues/29288) and eslint (https://eslint.org/blog/2019/01/future-typescript-eslint) teams it might be time to switch?

As an additional perk we can consider to integrate prettier as an eslint rule as well (https://prettier.io/docs/en/eslint.html), so we could use `eslint --fix` for all the things

**Comment by stevenvachon** [comment]
Yup, the new standard way is to use [eslint-plugin-tslint](https://npmjs.com/eslint-plugin-tslint) (with ESLint) instead of [tslint](https://npmjs.com/tslint) directly.
