### ISSUE TITLE
DisplayName in function components

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#16051]
As we use more and more function components in React there is an issue with `displayName`. By default they won't have display name if they are defined as arrow functions:
```javascript
const MyComp = () => {}
```
The possibilities when it works is:
```javascript
// Add display name explicitly
const MyComp = () => {}
MyComp.displayName = 'MyComp'

// It is inferred from function name with old school function declaration
function MyComp() {}

// This will give you `Memoized(MyComp)` or similar depending on the wrapper
const MyComp = memo(function MyComp() {})

// This will give you just `MyComp`
const MyComp = memo(function MyComp() {})
MyComp.displayName = 'MyComp'
```

Not a critical issue but makes life much easier when debugging in chrome or checking Jest snapshot (otherwise everything is `<Component />`). With babel there are some plugins that could add it automatically but I did not find anything for Typescript. Maybe babel could be chained after TS to make this work without explicit `displayName`. If not maybe we should should have it as part of style guide that `displayName` needs to be set explicitly or to use classic function declaration.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by dprokop** [comment]
@aocenas I think I'm gonna close this. We are not going to use snapshots anymore and they should be organically removed whenever we encounter one. When it comes to dev experience I see the function component names are shown correctly in the React Dev Tools regardless of the displayName being set or not. As a matter of convention, I'm proposing to introduce react eslint rules as of #29053
