### ISSUE TITLE
Auto refresh not working 

### ISSUE THREAD

**Issue by SiddhantRoutray** [grafana/grafana#16050]
**What happened - Auto refersh not working 

**What you expected to happen-  Auto referesh expected after 1 sec as I modified in settings

**Anything else we need to know?

 I used Influxdb  to store time series data and the graph was plotted,but whenever I selected last 1h or last 30 min data would not be visible.Graph was only plotted after I selected Today from time date setting,but again here graph donot auto refresh

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: InfluxDB  ,version- 1.7.4
- OS Grafana is installed on: CentOS
- User OS & Browser: CentOS ,Google Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
in the time picker you find the auto refresh options. We have no other reports that auto refresh is not working in v5.4.2 so it's probably something wrong with your query. Use query inspector in metrics tab to troubleshoot the issue, there you find the query Grafana send to InfluxDB and the response from InfluxDB
