### ISSUE TITLE
Move panel/row to top of dashboard if alert condition triggered

### ISSUE THREAD

**Issue by ehfeist** [grafana/grafana#16062]
**What would you like to be added**:
It would be useful to have a mechanism to allow a panel or row to "bubble" up to the top of a dashboard to highlighting current infrastructure problems. When a particular threshold (or maybe an existing "alert" threshold) is hit, that panel or row displays on the top of the dashboard instead of its normal position, in order to highlight the issue.

**Why is this needed**:
This would allow for better focus on current issues with infrastructure that are monitored using Grafana. Most of the time, my team and myself are not interested in seeing things when they are working correctly, but only if there is an issue, at which point it should be the focus until it is resolved.

**Comment by torkelo** [comment]
We are about to disconnect the alert rules from the dashboard (so you define alert rules separately). So not sure this will make sense after that. Scenarios like you describe we hope to address with new form of scripted / dynamic dashboard
