### ISSUE TITLE
Conditional alert notifications based on query data

### ISSUE THREAD

**Issue by sebastiaopf** [grafana/grafana#16060]
**What would you like to be added**:
Would be nice to have a feature that enables an alert to notify different channels based on some data from the query results. Preferably it would let me use data directly from the query (like a hidden metric) to choose the notification target. For example, I could return an email field from the query and use it as the recipient for the emails.

**Why is this needed**:
Suppose I have a dashboard that monitors several (many) websites, each of which has a team in charge of keeping it online and functional. I have dashboards monitoring response time, error codes, etc, based on an Logstash/Elasticsearch backend. Today I have two options for alerts: a) I can notify every team on every alert triggered, but that results on teams receiving lots of alerts on websites that don't concern them. Or b), I can create individual dashboards/alerts for each website, each one of them notifying the corresponding team, but this makes it difficult to keep track of the dashboards/alerts and is hard to mantain for a large number of websites (e.g. above 100).

If I'm missing an existing feature that could be used for this, please advise.

**Comment by Nkmol** [comment]
@torkelo is this something that falls in the v8.0 alert revamp? It would be great if we could assign a specific alert channel to a query.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
