### ISSUE TITLE
all the pods are not displayed in the search labels of loki in grafana ui

### ISSUE THREAD

**Issue by soum1234** [grafana/grafana#16065]
I have extracted the logs from various microservices into grafana using promtail.
and in Grafana UI , i have added the loki datasource.When i click on explore , i can give the pod name of various applications in my cluster and do a log search but before that i could not see some pods listed in the UI. only if i manually enter the pod name i can see the logs but i would like to see the pod list prepopulated in the UI so that it will be easy to access logs.
@soum1234

**Comment by torkelo** [comment]
Not sure what you mean, in the labels menu it did not show? Even after reloading browser?

**Comment by torkelo** [comment]
closing due to lack of details, but it sounds like it will be fixed by this https://github.com/grafana/grafana/pull/16131  in v6.1 (out in beta)
