### ISSUE TITLE
Docs and guides for developing backend plugins

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#16066]
- [ ] How hashi corps plugins lib work.
   - [ ] How do we use it within Grafana
   - [ ] Mixing frontend and backend content
   - [ ] An example in Go. Backend version of simplejson might be a good idea.

**Comment by tomisaacson** [comment]
Any idea when this might be completed, or at least had enough done to be usable?

**Comment by bergquist** [comment]
Some initial work has been done in https://github.com/grafana/grafana/pull/16631 
We are currently working on an example backend plugin.

**Comment by tomisaacson** [comment]
Yes, I saw https://github.com/grafana/simple-json-backend-datasource/. I'm just wondering when that'll be in a state to use as an example?

**Comment by SamuelToh** [comment]
Very keen in this as well!

**Comment by oddlittlebird** [comment]
What is the status of this?

@marcusolsson, might be relevant to you.

**Comment by bergquist** [comment]
The docs for backend plugins could be divided into these different categories.

Godoc for the plugin-SDK
Godoc for dataframes
Concept docs on grafana.com/docs for backend plugins. Healthcheck? metrics?
Concept docs on grafana.com/docs for alerting on backend plugins
Concept docs on grafana.com/docs for dataframes

**Comment by bergquist** [comment]
Lots of docs/tutorials on its way but there are still much to improve so we keep this open and move it to 7.1

**Comment by bergquist** [comment]
https://grafana.com/docs/grafana/latest/developers/plugins/
https://grafana.com/tutorials/
