### ISSUE TITLE
Only 32 data can be displayed when I create a chart using a single graph

### ISSUE THREAD

**Issue by lx668** [grafana/grafana#16064]
**Only 32 data can be displayed when I create a chart using a single graph**:

**I want to see more than 32 pieces of data displayed in one chart

**I collected an indicator cpu load, more than 50 machines, I aggregated this data in a chart, but the browser can only display 32 data**:

**Environment**:
- Grafana version: v5.4.2
- Data source type & version: influxdb 1.2.2
- OS Grafana is installed on: centos7
- User OS & Browser: Browser
- Grafana plugins: influxdb
- Others: nothing

**Comment by torkelo** [comment]
Please include the query and the query response? (View this in query inspector)
