### ISSUE TITLE
graph panel left Y auto decimals bug

### ISSUE THREAD

**Issue by 314926481** [grafana/grafana#16068]
Hello,
I'm using grafana 6.0.1 with an prometheus backend and I'm running into a rounding issue:
    The value of the left Y axis looks a little bit too many digits.
Here is screenshots of  panels which clearly demonstrate the problem:
![image](https://user-images.githubusercontent.com/48713296/54594502-c47d1a80-4a6b-11e9-9cdb-c14f784754d1.png)

I looked at the query checker, where the values are:
     Array[1552986030,1030184960]

I want to display the value of the left Y axis at 1.02 or 1.03 digits.
Thanks!

**Comment by torkelo** [comment]
looks like the decimals override does not fully override the auto decimals logic anymore.
