### ISSUE TITLE
No grafana 6.0.0 rpm in the yum repo

### ISSUE THREAD

**Issue by brtj** [grafana/grafana#16070]
Does anybody know when grafana >6.0.0 will be available in rpm repo?

Both repos:
https://packagecloud.io/grafana
https://packages.grafana.com/oss/rpm

Could you support?

**Comment by torkelo** [comment]
check the install docs, the rpm repository has changed:

http://docs.grafana.org/installation/rpm/
https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/

**Comment by brtj** [comment]
@torkelo but repo is empty:

```
pkgsack time: 1.175
Repo-id      : grafana
Repo-name    : grafana
Repo-status  : enabled
Repo-revision: 1551884921
Repo-updated : Wed Mar  6 15:08:45 2019
Repo-pkgs    : 0
Repo-size    : 0
Repo-baseurl : https://packages.grafana.com/oss/rpm/
Repo-expire  : 60 second(s) (last: Tue Mar 19 11:41:21 2019)
  Filter     : read-only:present
Repo-excluded: 93
Repo-filename: /etc/yum.repos.d/grafana.repo

repolist: 0
```

Config:
```
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=0
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

**Comment by torkelo** [comment]
no, it's not empty, I just tried to install it on centos 7 and yum intalled grafana 6.0.1

**Comment by torkelo** [comment]
Repo-id      : grafana
Repo-name    : grafana
Repo-revision: 1551884921
Repo-updated : Wed Mar  6 15:08:45 2019
Repo-pkgs    : 57
Repo-size    : 2.6 G
Repo-baseurl : https://packages.grafana.com/oss/rpm/
Repo-expire  : 21,600 second(s) (last: Tue Mar 19 12:24:08 2019)
  Filter     : read-only:present
Repo-excluded: 36
Repo-filename: /etc/yum.repos.d/grafana.repo
