### ISSUE TITLE
security, backend, proxys

### ISSUE THREAD

**Issue by tecbea** [grafana/grafana#1608]
Hi,
in terms of visualizartion grafana is awesome;

but, or i did miss something, but security has not been worked;

for instance, the config js with passwords can be verified at www fronteend;
the rest interface to influxdb is accessed directly from webbrowser; 

well, dont know if can use this for some use cases, even in intranet, when acess control to series shall be applied...

any ideas? 

-- 
Filipe

**Comment by torkelo** [comment]
Grafana 2.0 (beta release within one week), comes with a host of user authentication options, and a data source proxy feature, where data source metric requests are proxied through the backend (and authenticated), the InfluxDB database, user and password is in this case hidden from the the browser. 
http://docs.grafana.org/v2.0/guides/changes_in_v2/

But per series permissions will not be implemented, all series in an influxdb database will be exposed. If you want per series permissions you need to open an issue with InfluxDB.
