### ISSUE TITLE
Vertical scroll on dashboard page doesn't work when mouse over scrollbar

### ISSUE THREAD

**Issue by morozovsk** [grafana/grafana#16086]
**What happened**:
Vertical scroll on dashboard page doesn't work when mouse over scrollbar.

**How to reproduce it (as minimally and precisely as possible)**:
Open any dashborad with vertical scrollbar. 
Move mouse to the right side over scrollbar.
Turn mouse wheel.

**Anything else we need to know?**:
Mouse wheel works in any part of page except vertical scrollbar.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser: kubuntu 18.04 & chrome 63.0.3239.132 
- Grafana plugins:
- Others: It was working in grafana 5.4.3.

**Comment by torkelo** [comment]
for the mouse wheel to work you do not need to hover over the scrollbar. The scrollbar on the right side you click and drag.

**Comment by torkelo** [comment]
related to this issue: https://github.com/malte-wessel/react-custom-scrollbars/issues/72

**Comment by morozovsk** [comment]
>for the mouse wheel to work you do not need to hover over the scrollbar

So I need move mouse from scrollbar if I need use mouse wheel for scrolling?

Page has pannels. Pannels have own scroll. Why do I need search place on page where scrolling works for page? It isn't "sapper" game.
![screen295](https://user-images.githubusercontent.com/1822063/54620436-d14f3d80-4a6e-11e9-958b-047916a478e8.png)

It is working on any site in chrome except grafana.
The scrollbar was created for scrolling but you replaced browser scrolling with your broken one.

Now I lose a lot of time and patience for searching place where I can use mouse wheel to scroll the page.

**Comment by morozovsk** [comment]
@torkelo
please reopen it.

> for the mouse wheel to work you do not need to hover over the scrollbar. The scrollbar on the right side you click and drag.

because it was working before but now it's broken.
moreover, this behavior is on all sites except yours.
so that "what you have" is an unexpected behavior, i.e. bug.
it breaks standard chrome browser behavior.
so please reopen it or I need to create another ticket?

**Comment by torkelo** [comment]
We need to use an overlay scrollbar for a few reasons, if your OS supports overlay (OSX and windows if you enable it in chrome) you will get a native overlay scrollbar.

**Comment by morozovsk** [comment]
are you sure?
>Google Removes Overlay Scrollbar Flag From Chrome

https://appuals.com/chrome-overlay-scrollbar/
