### ISSUE TITLE
Internet Explorer 11 & Screenly graphics display problem

### ISSUE THREAD

**Issue by ckirnak** [grafana/grafana#16097]
**What happened**:
I'm using Internet Explorer 11. My resolution is 1366x768. I share the panel and open the link on the internet explorer.
The scroll bar appears on the page and the graphs are below.
The same problem in Screenly application.I don't see the problem when I open the same link in the Chrome app.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:v6.0.1 (0c44a04).
- Data source type & version: MySQL
- OS Grafana is installed on: Centos7
- User OS & Browser: Internet Explorer 11 or Screenly 
![Grafana Error](https://user-images.githubusercontent.com/12850732/54670797-83d1df80-4b05-11e9-8368-b298a2cfd4c9.png)

- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
We have an issue here https://github.com/grafana/grafana/issues/15754 to gauge interest in continued support for IE11
