### ISSUE TITLE
Grafana uses illegal characters in requests to Prometheus

### ISSUE THREAD

**Issue by sorahn** [grafana/grafana#16090]
**What happened**:
Requests to prometheus (and others) that use the `/api/v1/series` URLs have `[` and `]` in the URL, but these characters are illegal with out being escaped.

**What you expected to happen**:
`[` & `]` characters should be encoded to `%5B` and `%5D`
see [here](https://github.com/grafana/grafana/blob/fe1c204d4addbbdd37ba7b6bdb30794a9768b8fc/public/app/plugins/datasource/prometheus/metric_find_query.ts#L135) and [here](https://github.com/grafana/grafana/blob/fe1c204d4addbbdd37ba7b6bdb30794a9768b8fc/public/app/plugins/datasource/prometheus/metric_find_query.ts#L72).

**How to reproduce it (as minimally and precisely as possible)**:
Use a Tomcat server to forward requests to prometheus.
Tomcat will reject urls with invalid characters.

**Anything else we need to know?**:
I tested the requests directly to prometheus with `series?match%5B%5D=blah blah blah` and it works as expected.

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: prometheus
- OS Grafana is installed on: macOS
- User OS & Browser: macOS & Chrome
- Grafana plugins: None
- Others: None

**Comment by BhartiAgrawalNvidia** [comment]
I would like to work on this please.

**Comment by BhartiAgrawalNvidia** [comment]
I am not able to push my branch to this repo. I get a 403 error how do i fix that?

**Comment by marefr** [comment]
@BhartiAgrawalNvidia You have to fork the Grafana repository to your personal Grafana repository. Then you'll push your branch to your forked personal Grafana repository and open a PR for that.

**Comment by BhartiAgrawalNvidia** [comment]
ok let me do that thanks

**Comment by BhartiAgrawalNvidia** [comment]
Hi what is the process to get my PR reviewed?

**Comment by rmie** [comment]
I had an httpd in front of an authentication proxy that was affected by this issue.
The httpd config snippet below worked for me:

```
RewriteCond %{QUERY_STRING} ^match\[\]=(.*)$
RewriteRule "^/grafana/api/datasources/proxy/2/api/v1/series$" "/grafana/api/datasources/proxy/2/api/v1/series?match\%5B\%5D=%1" [PT]
```

**Comment by BhartiAgrawalNvidia** [comment]
I have submitted the PR here https://github.com/grafana/grafana/pull/21447 thanks. Sorry it took so long.

**Comment by BhartiAgrawalNvidia** [comment]
Hi, I am not able to assign this issue to myself for some reason.
