### ISSUE TITLE
Consider switch from golint to revive

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#16109]
**What would you like to be added**:
Consider replacing golint with revive - https://github.com/mgechev/revive

**Why is this needed**:
Since we don't really like some of the golint rules that cannot be disabled

**Comment by bergquist** [comment]
I think this makes sense. With revive, we can choose which rules we want to enforce and enforce it for different parts of the codebase which makes it easier to improve the code over time. 

:+1:

**Comment by torkelo** [comment]
Where we even using golint before? Thought we only used gometalinter
