### ISSUE TITLE
Anonymous access feedback

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1610]
I think the problem was that the org_name specified in the config did not exist:
`2015/03/18 00:02:41 [middleware.go:81 func·004()] [E] Anonymous access organization error: 'Company': Organization not found`
After creating the organization, I hit another issue:
 - I was using http://localhost:3000/login and was expected to be logged-in automatically and redirected to the main page. However, that was not the case - I was prompted with the login form, which incorrectly made me think that the anonymous access mode was still not working. After some time I thought I should give http://localhost:3000/ a try and indeed that worked as expected (got anonymous access).

Therefore I guess a few things could be improved when anonymous access is enabled:
1. Auto-create the organization specified in auth.anonymous : org_name, if it doesn't exist.
2. Automatically redirect from /login to the main page, when auth.anonymous is enabled (although this begs the question: what happens when you try to login as admin)
3. It is unable to star a dashboard in anonymous mode. This makes it impossible to create a playlist with the desired dashboards.
4. When anonymous access is enabled, I can see a drop down with "+ New organization" - see picture below. I think this shouldn't appear (we're running in a standalone mode, with no other organizations). Moreover, when I try to create an organization when anonymous access is enabled, I receive an "Access denied" error.

![image](https://cloud.githubusercontent.com/assets/952836/6698612/aeb7f69c-cd02-11e4-873c-1d47021a851d.png)

![image](https://cloud.githubusercontent.com/assets/952836/6698646/087e54a0-cd03-11e4-850b-863b3fa27b63.png)

**Comment by torkelo** [comment]
Some comments: 

Login should still be possible when anonymous access is enabled. Otherwise it would be hard to login as grafana admin, and also enabled hybrid mode where some users can use the anonymous access and those who want can signup or have logins created for them. 

I agree the New organization option should not be there (the backend righly does not allow you to create an org if you are not authenticated), have yet to hide this option for users who are unauthenticated. Not sure I want to auto create this org and this org should be setup before hand by a grafana admin (add data soures etc)

**Comment by costimuraru** [comment]
Yes, thinking more about it, it makes sense to still have the login even when anonymous access is enabled.

If we are not going to create the org automatically (although I don't see why :-)), we should at least surface the `Anonymous access organization error: 'Company': Organization not found` error in the UI. Otherwise it's really hard to understand what's happening.

**Comment by salsa-dev** [comment]
Hi, is there a way to modify the main page to put some graphs on it ?
This is a nice to have for anonymous access.

**Comment by rabun788** [comment]
Im getting a login page with anonymous access turned on in v2.5.
```
My Dockerfile looks like this:
FROM grafana/grafana:latest

MAINTAINER name

RUN apt-get -qq update
RUN apt-get -qq -y install curl

COPY conf/ldap/ldap.toml /etc/grafana/ldap.toml

ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_ANONYMOUS_ORG_NAME="myorg"
ENV GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
ENV GF_AUTH_LDAP_ENABLED=true
ENV GF_DATABASE_HOST=myhost:31006
ENV GF_DATABASE_NAME=docker
ENV GF_DATABASE_PASSWORD=docker
ENV GF_DATABASE_TYPE=postgres
ENV GF_DATABASE_USER=docker
ENV GF_SECURITY_ADMIN_PASSWORD="pass"
ENV GF_SECURITY_ADMIN_USER="admin"
ENV GF_USERS_ALLOW_ORG_CREATE=false
ENV GF_USERS_ALLOW_SIGN_UP=false
```

**Comment by torkelo** [comment]
@rabun788 make sure "myorg" exists

**Comment by rabun788** [comment]
Is that something that i set on the UI or is that an additional parameter is the Dockerfile?

**Comment by torkelo** [comment]
@rabun788 it's something you set in the UI (or HTTP api), default name is `Main Org.`

**Comment by rabun788** [comment]
Cool thanks. 

```curl -i -H "Accept: application/json" -X PUT -d "name=myorg" http://admin:pass@localhost/api/orgs/1```

That worked.
