### ISSUE TITLE
Document the blocks of devenv

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#16107]
**What would you like to be added**:
Documentation for the devenv blocks and `create_docker_compose` script

**Why is this needed**:
We have a pretty neat concept with devenv "blocks" it seems it might be cool to document workflow of it, should be much easier for the contributors and stuff

**Comment by torkelo** [comment]
yes, wonder where it makes most sense to mention. Readme (contains a lot of the dev env setup stuff already).

**Comment by dprokop** [comment]
Readme and http://docs.grafana.org/project/building_from_source/#developing-grafana

README works better as this will most probably be the first point of contact with the repo.

**Comment by markelog** [comment]
SGTM, we can start with the readme and move it somewhere else if there is a need for it :)
