### ISSUE TITLE
LDAP attribute group_search_filter_user_attribute shall be additionally retrieved 

### ISSUE THREAD

**Issue by mkusagani** [grafana/grafana#16103]
**What would you like to be added**:
The user's attribute defined in group_search_filter_user_attribute shall be retrieved from LDAP as (potential) additional attribute for the cases where isMemberOf is not possible.

**Why is this needed**:
Currently, only the LDAP attributes mapped to Username, Surname,, Email, Name, and MemberOf are retrieved from the Ldap User.
In case a technical attribute is necesssary for the search with group_search_filter within group_search_base_dns, one **must**  assign it to one of the [server.attributes] properties.
Which might makes the displayed profile in the Grafana GUI weird.

(Besides, the content of member_of is actually **not** a user's attribute but an attribute of the group searched with memberOf or group_search_base_dns and is hence not neccesseraily to be retrieved as User's attr).

e.g. in our User's attribute, we have an attribute called principalPtr (being a DN to the user0s details), which is to be used to search in group_search_base_dns with a specific filter

This gives the following settings
```
group_search_filter = "(&(objectClass=xxxRole)(uniquemember=%s))"
group_search_base_dns = [...]
group_search_filter_user_attribute = "principalPtr"

[servers.attributes]
...
surname = "principalPtr"
...

There is no other way to retrieve the correlation/search filter attribute principalPtr, without displaying it in the user's profile
As the content of group_search_filter_user_attribute is free configurable, its content should also be included in the retrieved attributes in login.searchForUser
```

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
