### ISSUE TITLE
markdown support for panel descriptions

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#16108]
**What would you like to be added**:
Support markdown in panel descriptions, so that a mouse over the panel *i* is nicely formatted.

**Why is this needed**:
Some of our panels are complicated and we have long descriptions.  It would be really useful to support markdown on the descriptions so that the formatting can be clear.  Also HTML links would be simpler to view/read.

**Comment by torkelo** [comment]
Not sure I understand, this has been supported for probably ~2 years, https://play.grafana.org/d/O4ZDtAqmk/markdown-in-panel-description?orgId=1

**Comment by shalstea** [comment]
My mistake
