### ISSUE TITLE
Nested Rows 

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#16113]
**What would you like to be added**:
Currently rows are collapsible. I need nested rows so that I can further collapse inside a row

**Comment by torkelo** [comment]
this is not very likely, maybe something like this https://github.com/grafana/grafana/issues/10916 will eventually be made

**Comment by salahmedamin** [comment]
3 years now, has it been made dev team?

**Comment by zcmartian** [comment]
4 years now

**Comment by shasankmaturi** [comment]
5 years now

**Comment by riuvshyn** [comment]
5 years and +1 more week ☝🏽

**Comment by AymenLagha1** [comment]
5 years and +2 week

**Comment by jan2893** [comment]
I have implemented this in my own Grafana fork. It's actually a fairly easy and clean with just ~40 lines changed.
I'd be happy to create an MR if this of contribution would be welcome in the upstream.

I have made a separate ticket for it: https://github.com/grafana/grafana/issues/93256

**Comment by Radttal** [comment]
> I have made a separate ticket for it: [#93256](https://github.com/grafana/grafana/issues/93256)

I'd love having this feature
