### ISSUE TITLE
Add option to invert multi-select variable options

### ISSUE THREAD

**Issue by jeremygurr** [grafana/grafana#16125]
**What would you like to be added**:
An option after the "All" option to invert the selection of options of a variable.

**Why is this needed**:
Consider a variable that filters a dashboard. It is multiselect and has hundreds of choices. I can tell from the dashboard that there's a problem, and there's a lot of noise in the data. I want to strip away a few of the more noisy choices so that I can more clearly see what's going on. So I'd like to just select the one or two choices I'd like to skip, and then click invert, and have all selected but my choices. Otherwise, I have to click one at a time, hundreds of choices, to keep the ones I want and exclude the ones I don't.

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by viktorcseppento** [comment]
Would be awesome if it were implemented. Now we have an extra variable (with true/false values) whether to invert a variable selection and the SQL query executes the appropriate logic. It would much easier if there were an invert selection checkbox or something.

**Comment by smit-modi** [comment]
@torkelo  Can this be reopened now and prioritized?

**Comment by iambingoNJU** [comment]
I want to implement this feature through another template variable which controls whether query condition use NOT. Is this possible?
