### ISSUE TITLE
Delete provisioning Dashboards from the page so that they do not automatically recover

### ISSUE THREAD

**Issue by aimuz** [grafana/grafana#16129]
**What would you like to be added**:

Delete provisioning on the page so that it does not automatically re-add

**Why is this needed**:

I think the essence of deletion should be to let him delete, not to scan and restore it after deletion?
If `disableDeletion` cannot be deleted, the definition of this attribute is meaningless. By the time of the next scan, he will add it again. I think it's against the definition of attributes.

The migration of large monitoring charts is painful, and I think interface Dell authenticity should also be preserved through provisioning imports. Instead of deleting files only by deleting them

**Comment by torkelo** [comment]
disableDeletion is for disabling auto-deletion of dashboards when the json file is missing/removed. 

Opened an issue to fix the issue that the delete button is visible & works for a provisioned dashboard: https://github.com/grafana/grafana/issues/16130
