### ISSUE TITLE
Legend values and Tooltip values swicth from float to int randomly

### ISSUE THREAD

**Issue by sainio** [grafana/grafana#1612]
Tooltip and legend values switch from float to integers randomly in 1.9.1, works ok in 1.8.1 (stays in float):

![farin](https://cloud.githubusercontent.com/assets/8513998/6726679/cb83b916-ce22-11e4-8376-d7cb5d034fa5.png)
![balin](https://cloud.githubusercontent.com/assets/8513998/6726678/cb6c3a0c-ce22-11e4-95e5-148c3fa8b611.png)

**Comment by torkelo** [comment]
The reason for this is that the auto decimal precision logic is based the max / min of the graph and the number of steps on the y-axis (basically how many decimals are required for the y-axis tick labels). This auto precision works well for the y-axis but on some edge cases it does not work well for the legend or tooltip. Hand having a auto decimal precision per series on the legend is too expensive. 

To solve this i have added a decimal override for the legend and tooltip where you can provide a fixed number of decimals. 
https://github.com/grafana/grafana/issues/1253#issuecomment-78561547

This is only implemented in develop branch (grafana 2.0, beta release with ~1 week)
