### ISSUE TITLE
[Bug] Variable repeated graphs changes are ignored when saving

### ISSUE THREAD

**Issue by WoLpH** [grafana/grafana#16133]
**What happened**:
When attempting to save a repeated graph (not the first one) using variables, Grafana doesn't save the changes.

**What you expected to happen**:
Changes to be saved to the "main" graph so it applies for all variants of the repeated graph.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard
2. Add a variable
3. Add a graph
4. Set "Repeat for each value of <variable>"
5. Edit anything but graph 0 of the repeated set of graphs
6. Save
7. Reload, your changes are gone

**Anything else we need to know?**:

It works just fine when editing the main/first graph of the repeated set.

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: Elasticsearch 6.0+
- OS Grafana is installed on: Ubuntu 16.04 LTS
- User OS & Browser: Windows 10, Google Chrome 72.0.3626.121 
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Repeated panels, you need to edit panel 0, (the source panel), we should disable editing on on the clones, think there is an issue for that

**Comment by WoLpH** [comment]
I couldn't find an issue for it so I created this. Personally I think having all editable wouldn't be bad either, as long as it saves.

**Comment by WoLpH** [comment]
In the case this occurred I was interested in editing the 3rd graph so having only the first one editable would result in an extra step to first select that variable.

So when it comes down to it, all editable would be better I think
