### ISSUE TITLE
Proxy does not work with subpath

### ISSUE THREAD

**Issue by wpcata** [grafana/grafana#16135]
**What happened:**
We've set up a Grafana Server in our Azure-VN and made it accessible over a Web-Application-Firewall (reverse proxy).

Settings:
`root_url = https://mydomain.com:443/`

The WAF is responsible for the SSL termination and it works fine, unless we use a subpath.
With
`root_url = https://mydomain.com:443/grafana/`
all we get is:

```
If you're seeing this Grafana has failed to load its application files
1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath
3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
4. Sometimes restarting grafana-server can help
```

Log:
```
t=2019-03-21T11:51:12+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/grafana socket=
t=2019-03-21T11:51:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/grafana/ status=404 remote_addr=myIP time_ms=68 size=26847 referer=
t=2019-03-21T11:51:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/grafana/public/build/grafana.light.8ec106c095469ac98ef1.css status=404 remote_addr=myIP time_ms=34 size=26847 referer=https://mydomain.com/grafana/
t=2019-03-21T11:51:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/grafana/public/build/vendor.8ec106c095469ac98ef1.js status=404 remote_addr=myIP time_ms=29 size=26847 referer=https://mydomain.com/grafana/
t=2019-03-21T11:51:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/grafana/public/build/grafana.app.8ec106c095469ac98ef1.css status=404 remote_addr=myIP time_ms=53 size=26847 referer=https://mydomain.com/grafana/
t=2019-03-21T11:51:22+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/grafana/public/build/app.8ec106c095469ac98ef1.js status=404 remote_addr=myIP time_ms=358 size=26847 referer=https://mydomain.com/grafana/
```

We've tested it with different settings e.g. root_url set to Grafana server IP and connecting to it directly without any proxy. But it's always the same result:
It does work until we use a subpath.

**What you expect to happen:**
Having a working proxy to Grafana using a subpath.

**How to reproduce it (as minimally and precisely as possible):**
- Set up a VM in Azure
- Install Grafana
- Set up a root_url with a subpath

**Anything else we need to know?:**
It seems as if Grafana doesn't even try to load anything if a subpath is set:
We renamed the public-directory with the css-files Grafana couldn't find, but the result was the same. (Without a subpath a 500-error is logged in this case)

**Environment:**
- Grafana version: 6.0.2
- Data source type & version: Prometheus 1.5.2
OS Grafana is installed on: Debian 9 "Stretch"
User OS & Browser: Windows 10, Google Chrome 72.0.3626.121
Grafana plugins:
Others:

Yes, I know there are already similar issues, but the solutions didn't work for us or were not applicable.

**Comment by torkelo** [comment]
root_url  (grafana) options should be the final url you use in the browser (including subpath)

**Comment by wpcata** [comment]
> root_url (grafana) options should be the final url you use in the browser (including subpath)

It is set to the final url.

We have **tested** it set to the local IP (and connected to it over VPN).

**Comment by wpcata** [comment]
Maybe I was not clear enough:

It is still not working.

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
