### ISSUE TITLE
View permissions for explore page

### ISSUE THREAD

**Issue by mlushpenko** [grafana/grafana#16146]
**What would you like to be added**: Allow accessing Explore page for users with View permissions

**Why is this needed**: Currently, only users with Edit permissions can go to Explore page which is weird as that page is actually used to viewing data only.

**Comment by torkelo** [comment]
if you enable viewers_can_edit option in ini file you can make viewers have access to explore

**Comment by mlushpenko** [comment]
Thanks @torkelo, that's not clear from the documentation, will give it a try

**Comment by gbloquel** [comment]
> if you enable viewers_can_edit option in ini file you can make viewers have access to explore

@torkelo Thank you for your reply.
But this option is global for all users which have the viewer role.
Why  viewer role cannot access to the Explore page without having `viewers_can_edit` ?
My need is to use Loki and I don't want my user(s) to be able to edit dashboard even if they cannot save.

**Comment by torkelo** [comment]
Because it’s very similar ad-hoc query capability, explore is similar to a transient editor (viewer that can edit dashboards but not save) 

We have plans on custom Grafana roles that can be mapped to user access / actions later this year (likely a Grafana Enterprise feature)
