### ISSUE TITLE
druid datasource

### ISSUE THREAD

**Issue by RestfulBlue** [grafana/grafana#16141]
Hey guys, if i will create pull request with almost fully featured druid plugin( alerting/variables/adhoc/etc) will it be merged at some point?

Previously there was a talk about not submitting new datasources. But it looks like many new datasources was arrived lately.

Plugin is fully based on sql and we was using it in production for long time.  But sadly we have internal network without any golang infrastructure and every time when we need to update grafana we got a lot of pain :( 

i think druid is perfect candidate to be in core. Its perfectly handle time based data, providing sql and executing queries with low latency and surpasses all analogs
Comparing to othery datasources :
1) Druid provide realtime pre aggregation at ingestion time( not only query time). For example Opentsdb cant preaggregate data, elastic require data to be aggregated somethere else, for example logstash. Such approach almost kill realtime data updates.
2) Druid perfectly handle time based data. Data in druid divided into blocks and retention rules just drop old segments.In opentsdb, elasticsearch, solr data deletion performed during merges, which require a lot of additional work. As i know, to avoid it with elastic/solr collection should be created by some interval and then dropped. In transactional databases it much worse
3) Druid provide indexes, making filtering really fast with random combination of columns in query. For example, last 4 millions of queries performed 80ms in average. 
4) Druid has cloud native, linear scalability. For example we use cloudera for manage druid cluster and adding new node is just a click of button. No manul repartition or balancing required. I think scale prometheus without losing sleep is impossible.
5) Fast data ingestion. In our stress testing cluster druid simply handle 1 millions rows per second on 3 large nodes. For data we use our JMX metrics, every row contains of 5 string fields and 10 long fields.
6) Druid has SQL. Most of ts storages uses native query language which is not friendly for analitycs.
7) Queries only scan data in query time range, without any overhead and looking around 
8) he is fully opensource and have 8k stars on github. Also, currently druid is incubating into apache projejct.

**Comment by torkelo** [comment]
Data sources in the core repo get official support from Grafana Labs, and taking on support for this data source is not something we want to do. This is the reason we have a plugin system, so additional data sources can be maintained and supported by third parties. 

We have backend plugin system as well so it's possible to add support for alerting for external plugins, but the system is not fully documented and officially supported yet. 

see backend roadmap for progress on documenting backend plugins: 
https://github.com/grafana/grafana/issues/16026

**Comment by liyichao** [comment]
@RestfulBlue Can you open source the druid datasource plugin ? The https://github.com/grafana-druid-plugin/druidplugin is not working on grafana 6.x

**Comment by ottomata** [comment]
Wikimedia would love to have an up to date Grafana Druid datasource plugin!

**Comment by fstolba** [comment]
+1 @RestfulBlue I'm sure your releasing the plugin would be highly appreciated by a lot of folks.

**Comment by tvberlin** [comment]
+1 as well. @RestfulBlue any chance to re-open this or allow for an exception?

**Comment by jbguerraz** [comment]
@RestfulBlue Hello!

Since April, 3 of us got maintainership permissions on `grafana-druid-plugin` (see https://github.com/grafana-druid-plugin/druidplugin/issues/91) so we now have a way to move it forward.

We would be (more than) happy to join forces in order to revamp https://github.com/grafana-druid-plugin/druidplugin (probably even rewrite it for Grafana 7).

It gonna be our focus in the next months. So we'll be very active, it's probably a good time to create some team, some community, and give it some traction :)

**Comment by jbguerraz** [comment]
See https://github.com/grafana-druid-plugin/druidplugin/issues/107
