### ISSUE TITLE
Refactor auth proxy

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#16147]
The main method of auth proxy is pretty hard to understand:
https://github.com/grafana/grafana/blob/46a75099d83a8b670df6292d8b9959c3864b73af/pkg/middleware/auth_proxy.go#L23

Needs restructuring so that we can keep working on this code in the future. I would break it out into a few methods and try to restructure it so that it is easier to follow.

Things it does:
- uses the remote cache (wip pr)
- syncs with ldap
- lookup for user in db
- sign in user

**Comment by markelog** [comment]
Note: we would have reintroduce some of the tests removed in https://github.com/grafana/grafana/pull/16114
