### ISSUE TITLE
Different data in graph tooltip

### ISSUE THREAD

**Issue by eliperelman** [grafana/grafana#1614]
In a particular graph I have a few data points for each time:

![graph](https://cldup.com/-5FQCrfju--2000x2000.png)

When using the tooltips, I always get an accumulation of the values for that entry, but I was wondering if I instead could supplement the existing single value tooltip with additional data from the entry:

![tooltip](https://cldup.com/wkTNK8Db7Q-2000x2000.png)

So instead of just showing the value from the `visuallyLoaded` series, I could also pull in the data from a couple columns also related to that series's entry. For example, here is a column from InfluxDB:

![influx column](https://cldup.com/izgx_nvpn7-2000x2000.png)

There are 2 columns I am interested in, gaiaRevision, and geckoRevision. For a given `$timeFilter`, the gaiaRevision and geckoRevision are the same. I would like to be able to display these values in the tooltip along with the value if possible. So the tooltip could say:

__visuallyLoaded: 1.297s__
__gaiaRevision: db606a5f411c3817cc2f81369310f9ece559a0ad__
__geckoRevision: 29c79b8b0b69df81087ad8641e6263de041cf907__

**Comment by torkelo** [comment]
This is not likely something that is going to implemented any time soon, would be complex to setup and implemented and would make the hover feature very slow.

**Comment by torkelo** [comment]
It is a good idea, but might be better handled in some other way through table tables etc that can show meta data or annotations etc.

**Comment by eliperelman** [comment]
Ah ok, interesting. Do you have an example of how an annotation could display those 2 column names with a value?

**Comment by eliperelman** [comment]
I guess I'm not sure how this equates to annotations:

![](https://cldup.com/a5fspQy_pe-3000x3000.png)

**Comment by torkelo** [comment]
just put gaiaRevision and geckoRevision in title tags or text and you should see annotations markers on the graph where ever there are values for this influxdb series.

**Comment by CVTJNII** [comment]
I'm looking for this functionality as well.  As the concensus here is that the annotation will not support extra data and a table panel should be used, is the suggestion dependent on https://github.com/grafana/grafana/issues/215?

@eliperelman Which version are you on and how did you get to the column mappings settings you screenshotted?  I can find it in 2.1.3, are you running a dev branch?

**Comment by eliperelman** [comment]
@CVTJNII the column mappings has been there since at least 1.9, and it's still there as of 2.1+. If you look at the [play dashboards](http://play.grafana.org/dashboard/db/annotations?editview=annotations) and click on edit on the "puppet apply" annotation, you can see the column mappings. If you click on the other annotation you won't see the column mappings as it is a graphite datasource and not an InfluxDB source.

If you're curious, you can see how I'm loading annotations[1] and in action[2].

https://github.com/mozilla-b2g/raptor-dashboards/blob/master/public/dashboards/src/annotations.js
https://raptor.mozilla.org/dashboard/script/measures?var-device=flame-kk&var-memory=319&var-branch=master&var-test=cold-launch&editview=annotations

**Comment by torkelo** [comment]
? No, not other than what alternatives I mentioned.

**Comment by debmalyapan53** [comment]
I too want to display some more info on the tooltip. Any update on this?
