### ISSUE TITLE
[Feature request] Ability to filter out null/zero values for CloudWatch datasource

### ISSUE THREAD

**Issue by alvinlin123** [grafana/grafana#16164]
**What would you like to be added**:

Be able to not show null/zero in a table for CloudWatch data source. 

I have been searching the internet but couldn't really figure out a way to do this. 

**Why is this needed**:
Here is my use case. I have a lot of EC2 instances that emits a metric of value of 1 if X happened. I would like to have a table view of all the EC2 instance that emit that metrics for a given timeframe. X does not happen often. 

Currently I achieved this by having a variable, which has "Include All option" enabled, with query `dimension_values(us-east-1,MyCustomNameSapce,X,InstanceId)`

In a graph, I have a table with "Time series to rows". However, since X happens occasionally, the table is filled with a lot of rows with "-" as value, which is very noisy. It would really help to be able to remove those rows. 

This request is somewhat similar to https://github.com/grafana/grafana/issues/8325. But I am hoping that we can do that at the query level. For example, can we have an option to filter all all the time series data point that has value of 'null' on the response of CloudWatch's "GetMetricData" API?

**Comment by Natalique** [comment]
+1 
same issue with prometheus

**Comment by andkuha** [comment]
+1
same issue with prometheus

**Comment by munchkinbob** [comment]
+1
I also face the same issue with prometheus

**Comment by sunker** [comment]
This does not sound like a cloudwatch nor a datasource problem, but more like a table feature. Do you agree @torkelo?

**Comment by torkelo** [comment]
Yes, we Will be able to do this with an upcoming transformation feature.

Closing this as we already have a feature request for this for the table panel

**Comment by alvinlin123** [comment]
@torkelo  can you kindly link this issue to the feature request you mention? So that people landed on this thread will be able to track the feature request. Thanks!
