### ISSUE TITLE
CloudWatch: Reordering queries does not affect graph order or color

### ISSUE THREAD

**Issue by alecxvs** [grafana/grafana#16161]
**What happened**:
Given two CloudWatch queries A and B, if the order in the edit panel is [B, A], the graph still shows query A first (green) and query B second (yellow). It seems to still use the alphabetical order of the query identifiers [A, B].

**What you expected to happen**:
Query B should be first (green) and query A should be second (yellow)

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph panel with two CloudWatch queries. Reorder them, and observe no change in the graph ordering.

**Anything else we need to know?**:
Moving these queries up and down only affect their ordering in the query editor.

This does work as expected with other datasources, so it seems that the Cloudwatch datasource doesn't honor the order specified in Grafana.

**Environment**:
- Grafana version: 5.3.4
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker/Linux
- User OS & Browser: Chrome MacOS X
- Grafana plugins: N/A
- Others: N/A

**Comment by mtanda** [comment]
The CloudWatch datasource send all targets to backend by once.
And backend response is indexed by refId, it doesn't keep order.
https://github.com/grafana/grafana/blob/v6.1.0/pkg/tsdb/models.go#L23

So, need to restore order in frontend code.
