### ISSUE TITLE
Make it easier to run go linting in development

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#16160]
## Background
We have a bash-script (`./scripts/gometalinter.sh`) for running gometalinter in CI that is used to make sure that our code conforms to our code standards. I would like to be able to easily run linting in my dev environment, the bash script is not great for that.

## Proposed solution
For most parts of the build process we use our own homegrown build system, therefore it would be really nice no move the linting from the bash script to build.go so that we easily could install the dependencies needed and run linting in the development environment.

Current script: `./scripts/gometalinter.sh`

- [ ] `go run build.go setup` should install the necessary dependencies for linting
- [ ] `go run build.go lint` should run linting
- [ ] make the bash script use these methods

**Comment by bergquist** [comment]
We have https://github.com/grafana/grafana/blob/master/Makefile#L115 
I think that's enough. what do you think @xlson ?

**Comment by xlson** [comment]
Yeah, this is done.
