### ISSUE TITLE
Request: Split series names by underscore as well as dot for aliasing

### ISSUE THREAD

**Issue by cboggs** [grafana/grafana#1616]
I'm pushing metrics from gmond into InfluxDB, and all the series names come in with underscores as delimiters instead of dots. As an example, disk stats look like 'diskstat_sda_writes'. When I try to graph aggregates for all disks on a system, I query against all series names matching /diskstat_.*_writes/, but I can't alias against $0-$9 since it only breaks things up with dots. Being able to break on underscores as well would let me more easily alias things from gmond without having to manually alias them or hack all the gmond modules to output with dots... :-)

**Comment by torkelo** [comment]
InfluxDB 0.9 is a complete rewrite and is now tag based, so there will be no more development on the influxdb 0.8 query editor, the 0.9 editor will require a lot of work (when InfluxDB 0.9 has reached some stability which might take some time)
