### ISSUE TITLE
Home shortcut not working v6.0.2

### ISSUE THREAD

**Issue by Paul-Reed** [grafana/grafana#16163]
**What happened**:
I am unable to assign a 'Home' dashboard

**What you expected to happen**:
If I select 'Home' from the side menu, that the assigned dashboard should be displayed.

**How to reproduce it (as minimally and precisely as possible)**:
Assign a dashboard to be the 'Home' dashboard.

**Anything else we need to know?**:
See the animated gif below.

**Environment**:
- Grafana version: v6.0.2
- Data source type & version: Influxdb
- OS Grafana is installed on: Raspbian
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: Worldping, Singlestat, Multistat.

![home](https://user-images.githubusercontent.com/973580/54841559-6ea4ae80-4cc7-11e9-841f-47a35c04ae84.gif)

**Comment by torkelo** [comment]
Unable to replicate, setting home dashboard works on both, org level, team level and user profile level when testing this in 6.0.2. 

Make sure your user has is not part of a team that has set home dashboard, or that you have not specified a home dashboard on user profile level. Both of those override the org level home dashboard setting.
