### ISSUE TITLE
Linked dashboards

### ISSUE THREAD

**Issue by saurabhagrawal-fk** [grafana/grafana#1617]
**Feature request:**

A panel should be configurable such that clicking on a metric should take the user to another pre-configured dashboard.

**Use case:**

I have a dashboard for monitoring health of a cluster consisting of multiple hosts. Looking at this dashboard, I can identify any misbehaving host in the cluster. Now, for further diagnosis, I'd like to view another dashboard that shows me system level metrics of a particular host. As of today, I need to type in the url of my 2nd dashboard in the browser. It would be very convenient if I could configure my 1st dashboard to open the 2nd dashboard in a new browser tab, on a mouse click action. 

This should probably be generic enough to link to ANY url, not just to another grafana dashboard.

**Comment by torkelo** [comment]
Yea, this would be good. Others have suggested it as well (even a PR for something like this). 

How would you configure this? Any good ideas, ui mock ups? A graph can contain many series (usually from one or many queries).

**Comment by saurabhagrawal-fk** [comment]
IMO, the URL should be configurable per query, just like the "alias" field.

**Comment by toni-moreno** [comment]
Hi @torkelo and @saurabhagrawal-fk .

I think you are talking something like this other issue (https://github.com/grafana/grafana/issues/1232)

I've proposed some weeks ago a link per metric

![image](https://cloud.githubusercontent.com/assets/5883405/5437451/e7439758-8470-11e4-813d-185daf23a67d.png)

In my issue I asked for adding a variable for each metric also ....

**Comment by torkelo** [comment]
It cant be done qwith per metric query (not possible to know which series came from which query) , needs to be done per with a different kind of drilldown link, a legend link feature, so the link needs to be the same template expression for all series in the legend

**Comment by torkelo** [comment]
close this in favor of continuing discussion in https://github.com/grafana/grafana/issues/1232
