### ISSUE TITLE
Clause based evaluation of alert queries

### ISSUE THREAD

**Issue by serioushaircut** [grafana/grafana#16178]
**What would you like to be added**:
In #6438 the serial evaluation of alert queries has been introduced after some discussion. This serial evaluation does not allow for any clause based alert rule (con-/disjunctive normal forms). We'd love to see a non serial evaluation, i.e. one that allows for 'setting parentheses' to define clauses. 

**Why is this needed**:
We have many use cases where we like to apply boolean logic which is not expressible in serial evaluation `((A & B) || C) & D)`. 

The following is a very common use case to set up an alert:
We have a peaky traffic over day and define almost all alerts sensitive to the time of day per time zone (which we feed in from one our services as a time series to use it in alert queries - to have a 'day of time' already present in Grafana would be another feature request but first things first). 
So, suppose A is our service level indicator (SLI) and T is the day of time in CET/UTC/whatever. For nearly every single SLI we have peak hours with different alert thresholds.
In short: there is a panel with this : 
Between 8am and 10am alert when A exceeding 1M (Clause 1) OR between 6pm and 7pm when A exceeding 500k (Clause 2), or alert when exceeding 10k otherwise (Clause 3).

`Alert if (B > 1M &&  T in [8am, 10am]) || (B > 500k && T in [6pm, 7pm]) || (B > 10k && T not in [you get the idea])`

Our workaround:
For now we build at least three identical panels per SLI only differing in their 'time condition' of their clause. We have to put those on a dashboard nobody actually looks at b/c there are hundreds of them and they are repetitive and not helpful except from their 'alerting part'. We add drilldown links to all of them to permit a paged engineer to quickly navigate from the 'workaround panels' to the real dashboards with all the context and correlation info.

By the way, #7832 is not the same but would also help a bit, but being able to just define a disjunctive normal form would be great.

[Context: I work at a company with hundreds of services, a multitude of data sources, 100s of millions requests per day in mainly two timezones with a clearly identifiable healthy traffic pattern in the course of a working/non-working day.]

When anyone has a better workaround for what we're doing, I'm all ears. Our teams struggle hard in our panel heavy approach! We would be really thankful for any better idea.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
