### ISSUE TITLE
Consider renaming TableData to SeriesData

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16181]
We have migrated react plugins to use TableData[] for everything -- this is a big improvement, but as we look at how to use this in the UI, some of the names don't feel right.

In particular, we will need some way to refer to operations on tables/columns.  repeat all numeric columns in all series, etc.  What template variables names do we use to pick an appropriate title?

I propose changing:
> TableData to SeriesData
> TableData.column > SeriesData.field

I think this leads to more reasonable template variable names and UI elements that match the data model.  For exampe, the title to each repeating vis may be:
```
${field.name} (${series.name})
```
or maybe
```
${field.name} (${series.tags.queryRefId})
```

This will also lead to building a `Series` selector component and a `Field` selector component that feels more natural than a Table/Column selector.

The one conflict is that "Series" kinda means the traces on the graph panel now, so we should move towards calling them `Traces` but I don't think the confusion is too big since Series === Trace when the data is timeseries

**Comment by torkelo** [comment]
yes, agree, this makes a ton of sense.

**Comment by torkelo** [comment]
Might be a bit confusing queries like this: 

```sql
SELECT
  $__timeEpoch(<time_column>),
  <value column> as value,
  <series name column> as metric
FROM
  <table name>
WHERE
  $__timeFilter(time_column)
ORDER BY
  <time_column> ASC
```

This is how you currently return time series data from a table query. here the series name is actually a field / column.

**Comment by ryantxu** [comment]
> Might be a bit confusing

for sure, but I think as long as we have a clear process to construct titles/labels it won't be too bad
