### ISSUE TITLE
everyone can see the influxdb username and password

### ISSUE THREAD

**Issue by thetcc** [grafana/grafana#1618]
I found a very terrible thing, if you open the browser developer tools, when you request grafana, you will find that a request like this:

    http://play.grafana.org/influxdb/db/graphite/series?p=grafana&q=select+mean(0+-+value+-+100)+from+%22apps.backend.backend_04.counters.requests.count%22+where+time+%3E+now()+-+1h+group+by+time(10s)+fill(0)+order+asc&u=grafana

This shows that anyone using a browser to access your grafana, can see any username and password of your config.js. 
Also, request is direct from the browser to the influxdb or Graphite, and then parse the returned json data back and show to the interface.

If request the url:
    http://play.grafana.org/config.js
you will see everything.How can I protect this.

**Comment by torkelo** [comment]
You can put it behind basic auth and https but that will not stop authenticated users from viewing config.js. Grafana 1.x is a frontend application where everything is done from your browser so there is no way to secure this. 

Grafana 2.0 comes with a backend server that enabled a host of new features, one of those is a data source proxy feature where the influxdb requests are proxied via the grafana backend, the backend will then add the username and password (so they will never be exposed to the browser)
