### ISSUE TITLE
Panel Image Renderer timeout when using Unix Socket

### ISSUE THREAD

**Issue by jplitza** [grafana/grafana#16180]
**What happened**: Timeout error when rendering panel as image.

**What you expected to happen**: The image to appear.

**How to reproduce it (as minimally and precisely as possible)**: Configure Grafan behind some sort of reverse proxy (Apache here) using a Unix socket instead of a TCP port on localhost.

**Anything else we need to know?**: Relevant code: https://github.com/grafana/grafana/blob/4520962ac2a59375daca935aa09fd09435f8dabb/pkg/services/rendering/rendering.go#L129

**Environment**:
- Grafana version: 6.0.2 (but also under version 5)
- Data source type & version: All
- OS Grafana is installed on: Debian 9.8
- Grafana plugins: None

**Comment by torkelo** [comment]
yes, for this to work Grafana itself needs to be accessible via http as PhantomJS (or Headless chrome) needs to be able to access Grafana. 

You can work around this by setting up an external rendering server:
Run this https://github.com/grafana/grafana-image-renderer in standalone server mode and configure it's url in your ini file 

```ini
[rendering]
server_url = your_running_grafana-image-renderer_server
callback_url = your_grafana_http_endpoint
```

**Comment by jplitza** [comment]
Then you might want to mention this limitation in the docs, e.g. for the [protocol option](http://docs.grafana.org/installation/configuration/#protocol).
