### ISSUE TITLE
Consider to use shellcheck for bash lint 

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#16198]
**What would you like to be added**:
We have a good number of shell scripts used for various tasks. According to github stats it's 1.1% (currently) of our source. 

It seems it might be a good idea to lint that logic?

**Why is this needed**:
Implement [shellcheck](https://www.shellcheck.net/) as a part of your CI run (and it would be cool if you could run it locally of course)

**Comment by torkelo** [comment]
Good idea :)
