### ISSUE TITLE
Save in table panel edit

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#16202]
**What happened**:
I clicked save while in panel edit mode in the visualisation tab for a table panel. Nothing happened. Then when I clicked something else like a button the save modal appears. After clicking save in the modal I am sent back to the dashboard. Sometimes chrome asks me if I want to leave the page. 

**What you expected to happen**:
The save modal to show up when I clicked save.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel. Add a query. Go to visualisation tab. Hit save and then some button in the panel editor. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Latest master
- Data source type & version: 
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Try again with latest master , think this was fixed by react angular wrapper fix merged today

**Comment by Ijin08** [comment]
Now works as it should.
