### ISSUE TITLE
Grafana 2.0 - When protocol = https redirect http accesses to https

### ISSUE THREAD

**Issue by syepes** [grafana/grafana#1620]
When the Grafana Backend is configure to listen to https, it would be nice that when http is accessed it redirects us to the https.

**Comment by torkelo** [comment]
Yes, good feedback! Will try to fix!

**Comment by torkelo** [comment]
This will require grafana to listen to two ports, (port 80 and 443), think if you want this it is better handled by nginx proxy infront
