### ISSUE TITLE
Table panel visualization tooltip is always to the right of a link column

### ISSUE THREAD

**Issue by chook** [grafana/grafana#16217]
**What happened**:
If I have a link+tooltip cell on a Table panel, the tooltip opens to the right, while I expected it to open to the left, or make a better effort in showing the data in less lines.

**What you expected to happen**:
The tooltip should float either outside of the widget (like the graph does) 
and/or open to the left of the cursor (like the graph does).

**How to reproduce it (as minimally and precisely as possible)**:
1. Open https://play.grafana.org/d/000000031/table-panel-showcase?tab=visualization&orgId=1&fullscreen&edit&panelId=10
2. Add the @message column again and again
3. Change the @message tooltip to "this is a very long tooltip, this is a very long tooltip".
4. Refresh and hover over the far right @message value
5. You see how it breaks to multiple lines, while sticking to the right of the column

**Anything else we need to know?**:
No

**Environment**:

play.grafana.org (6.0.1 as of Mar 25th)

- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Ijin08** [comment]
Currently:
<img width="1440" alt="Screenshot 2019-03-26 at 07 54 19" src="https://user-images.githubusercontent.com/23470681/54977732-849fc100-4f9e-11e9-8156-d186c374985e.png">
Should be: 
<img width="1440" alt="Screenshot 2019-03-26 at 08 09 02" src="https://user-images.githubusercontent.com/23470681/54977753-8e292900-4f9e-11e9-9265-e4727e4eedca.png">

**Comment by chook** [comment]
@torkelo is the label means this is benched? 
does help wanted means the community is suggested to work on it?

**Comment by torkelo** [comment]
yes

**Comment by daverted** [comment]
I opened PR #17621 to make this configurable.

<img width="540" alt="Screen Shot 2019-06-17 at 4 57 04 PM" src="https://user-images.githubusercontent.com/896958/59642173-3f180d80-9121-11e9-9578-ef6b92df2615.png">

**Comment by torkelo** [comment]
This fixed in v7.0 table panel

**Comment by thisisobate** [comment]
Hi @chook 
We've removed support for tooltip in the new table datalinks. If you think this is a very important feature, please feel free to open a feature request.

Thanks!
