### ISSUE TITLE
same metric and configuration, same time, but different results

### ISSUE THREAD

**Issue by ggggsc** [grafana/grafana#16218]
**What happened**:
I want to display a data in two different graphs,same metric, same data source, but I found the result totally different, something wrong?

**What you expected to happen**:
shouldn't they display  a same result?

![1](https://user-images.githubusercontent.com/47072644/54964324-00057080-4fa7-11e9-80cb-530f1ab2a79b.png)
![2](https://user-images.githubusercontent.com/47072644/54964331-07c51500-4fa7-11e9-97e6-814bc7c4b8ac.png)

**Environment**:
- Grafana version:  v6.0.2
- Data source type & version: zabbix 3.4.9
- OS Grafana is installed on: centos
- User OS & Browser: windows & chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
It can depend on the max data points, and your aggregation, what stat is selected in the options.

**Comment by Ijin08** [comment]
Is the gauge panel showing Last(current) as value?

I can't replicate:
<img width="1438" alt="Screenshot 2019-03-26 at 10 36 27" src="https://user-images.githubusercontent.com/23470681/54986664-59739c80-4fb3-11e9-9dad-9bdee8548004.png">

Can you take a screen shot from the dashboard where the panels are next to each other and the dashboard has been refreshed?

**Comment by ggggsc** [comment]
Here's details of panels,just refreshed
![21](https://user-images.githubusercontent.com/47072644/55042807-407bf180-506e-11e9-8643-9b1b26e4baee.png)
![22](https://user-images.githubusercontent.com/47072644/55042812-44a80f00-506e-11e9-9aed-18da27bfa015.png)
![23](https://user-images.githubusercontent.com/47072644/55042814-470a6900-506e-11e9-9012-152f5224b132.png)

**Comment by torkelo** [comment]
You will have to ask zabbix about how they process queries, there is no aggregation function selected, the singlestat (gauge) panel requests fewer data points than the graph. What stat is selected in panel options?

**Comment by Ijin08** [comment]
It looks like the gauge panel is showing avg not current:
![issue](https://user-images.githubusercontent.com/23470681/55057079-6dc5a100-5068-11e9-957d-15c6c381abd4.png)

Go to the visualisation tab and change the value:
<img width="1333" alt="Screenshot 2019-03-27 at 08 20 32" src="https://user-images.githubusercontent.com/23470681/55057384-5a670580-5069-11e9-9d8a-547b4b70d622.png">

**Comment by ggggsc** [comment]
> It looks like the gauge panel is showing avg not current:
> ![issue](https://user-images.githubusercontent.com/23470681/55057079-6dc5a100-5068-11e9-957d-15c6c381abd4.png)
> 
> Go to the visualisation tab and change the value:
> <img alt="Screenshot 2019-03-27 at 08 20 32" width="1333" src="https://user-images.githubusercontent.com/23470681/55057384-5a670580-5069-11e9-9d8a-547b4b70d622.png">

Thank you all of you!
as ljin08 mentioned ,the default value is average, not current! it is ok now!
