### ISSUE TITLE
Support for json/jsonb operators with postgres (in graphical query editor)

### ISSUE THREAD

**Issue by saurabhnanda** [grafana/grafana#16220]
**What would you like to be added**:

Support for json/jsonb Postgresql operators like `@>` `?` `?|`, etc. in the graphical query editor.

**Why is this needed**:

Dumping logs into a jsonb column and need a way to query them using the query builder, eg.

```
json_message @> '{"status": 200}'
```

**Comment by marefr** [comment]
@saurabhnanda are you referring to support when using the graphical query editor? If you use the raw query mode you can already use those operators.

**Comment by saurabhnanda** [comment]
@marefr correct. This is wrt to the graphical query editor.

**Comment by Simonefardella** [comment]
Any news about that?

**Comment by Simonefardella** [comment]
Guys, this graphical support will be added soon?

**Comment by Simonefardella** [comment]
BUMP

**Comment by Simonefardella** [comment]
Hi guys @dprokop, @aknuds1 is there any progress on this issue?

**Comment by Alexander1972** [comment]
Wondering about the progress as well? Or I should turn to kibana not as nice UI but very functional and supports json format as a charm

**Comment by Simonefardella** [comment]
> Wondering about the progress as well? Or I should turn to kibana not as nice UI but very functional and supports json format as a charm

They seems very unresponsive on that...totally disappointed

**Comment by dko21** [comment]
As there hasn't been any updates in this thread for a year I take it this might be far off in the roadmap - If it's in the roadmap at all. Still, figured I'd bump it :+1:

**Comment by zoltanbedi** [comment]
We are going over some old issues. Is this something that people are interested in?
