### ISSUE TITLE
Migrate Button component to @grafana/ui

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#16221]
**What would you like to be added**:
- [x] Migrate button variants (primary, secondary, danger, inverse, transparent, link)- [ ] Migrate disabled button styles
- [ ] Migrate outline buttons
- [ ] Migrate toolbar buttons
- [x] Migrate button sizes (xs, sm, md, lg, xl)
- [x] Button with icon
- [ ] Button animations (loading)
- [ ] Implement stories
- [ ] Move simple LinkButton & Button instead of ExtraLargeButtoin, SmallButton components etc 

**Why is this needed**:
To enable https://github.com/grafana/grafana/issues/15533 and few other things in the future

**Comment by torkelo** [comment]
closing this for now as most is done here, and we can create new issues for specific things we want to add / need in @grafana/ui
