### ISSUE TITLE
'Unkown' spelling mistake - or is it? 

### ISSUE THREAD

**Issue by Andysimcoe** [grafana/grafana#16225]
**What happened**:
Using explore tab and Loki logs which aren't labelled as a stream (debug, info etc) are 'unkown'.

**What you expected to happen**:
Word should be 'unknown'

**Environment**:
- Grafana version: 6.0.2

I searched the repo and see more than one reference to 'unkown' so I'm now not actually sure if this is a bug and for some reason intentional or if it's just been copy+pasted?

![Capture](https://user-images.githubusercontent.com/42643041/54995692-4070e880-4fbf-11e9-805f-1d48979ffde5.PNG)

**Comment by torkelo** [comment]
yes, but does not look it's in Grafana, that level is taken from the log line itself , could not find the word unkown in the logs code.

**Comment by Andysimcoe** [comment]
It's not in the logs. I do see some references to unkown in the repo - https://github.com/grafana/grafana/search?q=unkown&unscoped_q=unkown
