### ISSUE TITLE
Support NaN values in Postgres query responses

### ISSUE THREAD

**Issue by rolanddb** [grafana/grafana#16230]
**What happened**:
Trying to build a graph based on a Postgres table. When I add a column that contains only null values, the API call returns with a status code 500 and no graph is shown.

Grafana server logs:
```
t=2019-03-26T15:14:37+0000 lvl=eror msg="body json marshal" logger=context userId=1 orgId=1 uname=grafanaadmin error="json: error calling MarshalJSON for type null.Float: invalid character 'N' looking for beginning of value"
t=2019-03-26T15:14:37+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=grafanaadmin method=POST path=/api/tsdb/query status=500 remote_addr=<ip> time_ms=34 size=31 referer="https://host.com/d/-3m8WCqiz/letsgrow?tab=queries&orgId=1&from=1553518154379&to=1553560745929&var-greenhouse_id=1&var-compartment_id=3&fullscreen&edit&panelId=4"
```

**What you expected to happen**:
Graph is still shown for the other columns that do contain valid data.

**How to reproduce it (as minimally and precisely as possible)**:
Create table with timestamp column and two other columns, with one column containing only null values.

**Anything else we need to know?**:
I tried `coalesce(columnname, 0)` but the same API error is returned.
TimescaleDB extension is installed on PG, but this table is not a hypertable, no TSDB functionality is used.

**Environment**:
- Grafana version: Grafana v6.0.0 (34a9a62)
- Data source type & version: Postgres 10 + TimescaleDB extension
- OS Grafana is installed on: Docker image `grafana/grafana:6.0.0`
- User OS & Browser: Mac, Firefox
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
@svenklemm any ideas?

**Comment by tamer-hassan** [comment]
Also experiencing this issue on Grafana v6.0.1 (commit: 0c44a04) with Postgres 11 + TimescaleDB v1.2.

I believe this is caused by Prometheus sometimes storing 'NaN' in value column

**Workaround**, click "Edit SQL" on your query builder, and add something like this to you WHERE query to avoid NaN in your value column
`trim(value::text,'0123456789.e+') = '' AND ...`

This basically allows to assert that the returned values can only contain numbers, floats, or scientific notation.

related to: https://github.com/prometheus/prometheus/issues/860

**Comment by rolanddb** [comment]
While looking into this again, it seems that it does work for NULL values but not for NaN. I changed our ETL to write NULL and the dashboard works now.

**Comment by marefr** [comment]
@rolanddb did you write `NaN` before switching to `null`. Didn't knew that postgres supported the concept of `NaN` - if that's the case this should be converted to a feature request for supporting `NaN` returned from postgres.

**Comment by rolanddb** [comment]
@marefr Yes, I was writing `NaN` (this is a dump from a Pandas Dataframe, so it converted to NaN without me knowing about it). In https://www.postgresql.org/docs/9.3/datatype-numeric.html it is noted that float and numeric data types support NaN.

**Comment by kylebrandt** [comment]
When we switch our internal SQL datasources to use data.Frame, any json marshalling errors of NaN should be resolved. JSON doesn't support NaN/InF as per its specification (even though javascript does). But with data.Frame, everything is encoded into Apache Arrow, which supports rich types.

To have NaN, it will to be a float or a nullable float in the frame (generally only floats have NaN in computing).

The next possible challenge would be based on what the Go driver returns, and if we might need some [sqlutil.StringFieldReplacer](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/data/sqlutil?tab=doc#StringFieldReplacer) to take them from string/bytes to a float.

As an aside to @rolanddb , Pandas Dataframes can become arrow tables, and many arrow tables can become Grafana dataframes.  Nothing user space friendly yet really, but if integration of data frames with R and Pandas interests you, we have made the data frame type inspired by these - so hopefully you will be seeing more data science tools and grafana integration down the road.

**Comment by zoltanbedi** [comment]
It looks like this is already supported. Tried it out in current main v9.5.0-pre (d73fdcfc11)
![Screenshot 2023-03-28 at 10 39 46](https://user-images.githubusercontent.com/13729989/228179715-60d99098-f2d9-49a1-ac39-13d9c150cf21.png)
