### ISSUE TITLE
Make alertTimeout and alertMaxAttempts configurable in the config file

### ISSUE THREAD

**Issue by kobehaha** [grafana/grafana#16240]
In my usage scenario, I need resultHandleTimeout, alertTimeout is configurable, and it will be more flexible for the entire project, Can I change some code and to  pull request ?

code may change blew:

https://github.com/grafana/grafana/blob/master/pkg/services/alerting/engine.go

```
var (
	unfinishedWorkTimeout = time.Second * 5
	// TODO: Make alertTimeout and alertMaxAttempts configurable in the config file.
	alertTimeout        = time.Second * 30
	resultHandleTimeout = time.Second * 30
	alertMaxAttempts    = 3
)

```

**Comment by marefr** [comment]
@kobehaha sure you can change code and submit PR :+1: 

The most straightforward way would be to add new settings here:
https://github.com/grafana/grafana/blob/0e2d279e3a5c72a9a1af1f282d3b6885ab5b7d53/pkg/setting/setting.go#L175-L180

Initialize additional settings here: 
https://github.com/grafana/grafana/blob/0e2d279e3a5c72a9a1af1f282d3b6885ab5b7d53/pkg/setting/setting.go#L756-L761

Same defaults as today should be used.

Update https://github.com/grafana/grafana/blob/master/conf/defaults.ini and https://github.com/grafana/grafana/blob/master/conf/sample.ini

Update documentation for new settings in https://github.com/grafana/grafana/blob/master/docs/sources/installation/configuration.md#alerting

**Comment by kobehaha** [comment]
thanks, I update this pr
