### ISSUE TITLE
Grafana 2.0: Spacing on Variable Sub-Menu in Dashboards

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#1624]
Currently when multiple variables appear in a row, the equal spacing of labels and variables makes it a bit hard to discern which is which. 

![screenshot 2015-03-21 13 56 54](https://cloud.githubusercontent.com/assets/2886187/6766208/570ff966-cfd3-11e4-95a6-3e0e081a1acd.png)

I propose that the spacing/margin be adjusted to better couple the label with the variable, like so:

![screenshot 2015-03-21 14 00 49](https://cloud.githubusercontent.com/assets/2886187/6766209/6eaa70d8-cfd3-11e4-8873-9aca51baeffc.png)

This is just a quick mockup (padding-left:10px on label, margin-left: -6px on variable) and needs to be refined, but even this helps reduce cognitive load.

**Comment by torkelo** [comment]
Fixed in the template multi select / panel & row repeat branch
