### ISSUE TITLE
Grafana 2.0: "order asc" in query results in InfluxDB 0.9.x error

### ISSUE THREAD

**Issue by salsa-dev** [grafana/grafana#1625]
Hi!

I'm testing Grafana 2.0 (latest code from develop branch) with InfluxDB 0.9.x (master branch) .
When making a query in Grafana it gives an "InfluxDB Error".
The Inspector shows the full query which is simple:
select mean(value) from "sin" where time > now() - 6h group by time(10s) order asc 

I found out that editing the line
`src/app/plugins/datasource/influxdb/queryBuilder.js +47`
to 
`    query += " order by asc";`
makes it work.

Could you please look into it and if possible apply a fix to change queryBuilder.js.

Thanks!

**Comment by torkelo** [comment]
only raw queries are tested right now, did you switch to editor mode? Thought I removed it. The query editor and data source needs big updates to support the totat rewrite that influxdb 0.9 is, right now only raw queries work, not sure when an editor will be made, InfluxDB 0.9 needs to more stable and it will take time to do a good editor for 0.9, maybe in Grafana v2.1 or v2.2
