### ISSUE TITLE
"An unexpected error happened." when adjusting the timerange on explore

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#16257]
<img width="1098" alt="Screenshot 2019-03-27 at 14 55 13" src="https://user-images.githubusercontent.com/444037/55086743-d2045700-50a0-11e9-8776-9986682266fe.png">

I changed `From` to `now - 7d` and `To` to `now`.

Version Grafana v6.1.0-pre (00a07c8)

**Comment by marefr** [comment]
@tomwilkie not able to reproduce this locally nor on https://admin-ops-tools1.grafana.net. Could you please more information (steps) if you can reproduce this. Thanks

**Comment by tomwilkie** [comment]
I had to use this query `histogram_quantile(0.95, sum by (le) (rate(cortex_request_duration_seconds_bucket{namespace="dev", job="dev/ingester", route="/cortex.Ingester/QueryStream"}[5m])))` and explicitly click `Apply`:

![tlixY2ZOA2](https://user-images.githubusercontent.com/444037/55111576-a732f680-50d2-11e9-8ecc-e4215921f063.gif)

This was in the console:

```
react-dom.production.min.js:198 TypeError: Cannot read property 'toString' of undefined
    at Object.m (SlideDown.tsx:35)
    at t.<anonymous> (TimePicker.tsx:179)
    at ta (react-dom.production.min.js:190)
    at na (react-dom.production.min.js:191)
    at Mo (react-dom.production.min.js:170)
    at Fo (react-dom.production.min.js:180)
    at Va (react-dom.production.min.js:232)
    at qa (react-dom.production.min.js:233)
    at Ls (react-dom.production.min.js:249)
    at As (react-dom.production.min.js:248)
```

**Comment by marefr** [comment]
Ohh now I understand. Thanks a lot. You have to write `now-7d` without spaces. In dashboard you get a validation error if you're writing `now - 7d` in timepicker, but in Explore you don't. 

We have ongoing work of  unifying timepicker in Grafana so the same component are used in both dashboard and explore. @jschill I suppose above reported problem wouldn't happen in the new component?

**Comment by kaydelaney** [comment]
Did a bit of digging and it looks like the issue lies with `parseDateMath()` in `datemath.ts`. Specifically, whitespace isn't stripped from `mathString`, so when parsing `mathString` for math operators it sees the whitespace and immediately returns undefined.

**Comment by got2bollABB** [comment]
Hello, 
I am currently having the same problem, I see there seem to be some kind of fixes but I don't know how to apply them on my installation ? CAn anyone help please ?
Am I supposed to change some code ? What files should I edit ?  
BR
