### ISSUE TITLE
Singlestats Responsive Sizing

### ISSUE THREAD

**Issue by tehdirector** [grafana/grafana#16254]
Currently Singlestats which are sized specifically for a panel size will not scale appropriately when the browser size is changed.

**What would you like to be added**:
Add the option to apply the size percentage to the responsive panel. If you choose this option it will fit your stat at the percentage size of the panel and adjust as the panel grows or shrinks.

In addition it would be nice to have left/center/right justify for singlestats. This is currently lacking and prohibits some basic design functionality that would help to make much cleaner dashboards.

**Why is this needed**:
When viewing at different resolutions, screen sizes, and devices the intended visual becomes distorted and data can become hidden due to being too large for the new panel size. This will allow for better **mobile** use and scale the single stats in the similar manner to how graphs are scaled.

**Comment by torkelo** [comment]
This is what we did with the new Gauge panel so we will definitely do it with the new react singlestat panel (rewrite of the panel) we are working on.

**Comment by tehdirector** [comment]
Music to my ears! Can you add the ability to justify the text as well? This is something that can make all the difference in properly formatting a dashboard to guide the eye where it needs to go.

**Comment by torkelo** [comment]
You mean to left or right? What text, the big singlestat value should not be centered?

**Comment by tehdirector** [comment]
Yes, the singlestat value and ideally the option for either left, center, or right. Centered doesn't work for everything and having the option to justify the stat to one side or the other can allow for much better dashboards visually.

**Comment by torkelo** [comment]
Can you mock-up some examples when left or right aligned value would be appropriate?

**Comment by ryantxu** [comment]
![image](https://user-images.githubusercontent.com/705951/55267289-8c7d9080-523e-11e9-8651-bc45b1245963.png)

**Comment by tehdirector** [comment]
Perfect example above. It's really just a matter of styling but can help when trying to tie a singlestat metric to a graph. In the example above you could have a graph to the left of those stats and it's more clear that the two are connected visually.
