### ISSUE TITLE
Reuse data from graph chart in singlestat panel

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#1626]
Performance wise it would be good to have the `singlestat` chart re-using data from the graph panel and thus allowing a combined `graph-with-summary-stats` panel:
![image](https://cloud.githubusercontent.com/assets/728853/6766798/4b6f06de-d01d-11e4-970e-c39854089c05.png)

Also I think it's useful to have the singlestat panel able to display multiple summary metrics and have it "multi-stat" ?

**Comment by torkelo** [comment]
this would require a too big rewrite of how panels and metric queries are fetched. Better to handle it in a new panel, (like a multi stat panel)

**Comment by torkelo** [comment]
But I do like the idea of a graph & multistat combo panel. hm...
