### ISSUE TITLE
after success login show last successful/unsuccessful login time for particular user

### ISSUE THREAD

**Issue by lm123** [grafana/grafana#16268]
**What would you like to be added**:
after success login show last successful/unsuccessful login time for particular user

**Why is this needed**:
DFSEC requirement

**Comment by marefr** [comment]
Can you please elaborate a bit on this. You want to be able to see audit trail of successful/unsuccessful logins?

Today you can see per user their last activity:
![image](https://user-images.githubusercontent.com/1668778/55130197-8c9d6380-514c-11e9-848d-f72785830690.png)

We have an ongoing issue to track the feature of allowing listing and revoking of auth tokens (#15250) where HTTP API support of that will be included in upcoming v6.1 stable release, for reference http://docs.grafana.org/http_api/admin/#auth-tokens-for-user where you at least can retrieve information of when a user logged in (createdAt).

**Comment by lm123** [comment]
When v6.1 is ready?

**Comment by marefr** [comment]
No definite release date yet, but beta1 have been released so if everything goes well with that 6.1 stable should be ready in a couple of weeks..

**Comment by marefr** [comment]
So besides my explanation of existing features is there still any point of having this issue open?
