### ISSUE TITLE
Add DynamoDB datasource support for templating

### ISSUE THREAD

**Issue by farzadpanahi** [grafana/grafana#16265]
**What would you like to be added**:
Add DynamoDB datasource to be used in templating. 

**Why is this needed**:
I want to create a template with variables where the values are coming from DynamoDB. The values are not time series values. It is bunch of configuration values stored in DynamoDB. 

I think the support for non time series no-sql databases like DyndamoDB or MongoDB is useful in templating.

**Comment by marefr** [comment]
Highly unlikely that this is something we want to add to core Grafana. I'm going to close this, but it doesn't mean that we cannot reopen it if we see a lot of people requesting this. 

For mongo there's an existing datasource plugin: https://github.com/JamesOsgood/mongodb-grafana
I'm not aware of a datasource plugin for dynamodb but guess it can be implemented as a plugin using for example https://aws.amazon.com/sdk-for-browser/

**Comment by kevinashaw** [comment]
Why would this not be included?  To me, it seems like a critical feature.  Databases are an excellent place to store statistics. -K

**Comment by k3vl4rAtAirside** [comment]
I add to the sentiment of @kevinashaw, dynamodb is huge for aws, anything big for aws should be important to grafana.

**Comment by nitobosch** [comment]
+1

**Comment by yassineselmi** [comment]
+1

**Comment by Jessen94** [comment]
+1

**Comment by Goldich** [comment]
@marefr can we please reopen this feature request? I would even pay for that feature in the Enterprise version.

**Comment by trend-ouki-wang** [comment]
+1

**Comment by DavidKristensson** [comment]
+1
Has anyone figured out a workaround for this in the meantime?

**Comment by scottlepp** [comment]
You can use the [Sqlyze](https://grafana.com/grafana/plugins/grafana-odbc-datasource/) datasource with an [ODBC driver for DynamoDB] (https://www.cdata.com/drivers/dynamodb/odbc/).

**Comment by scottlepp** [comment]
We've published a beta release of the [DynamoDB datasource plugin](https://grafana.com/grafana/plugins/grafana-dynamodb-datasource/).
