### ISSUE TITLE
Rename alert rule diff reducer to absDiff or diffAbs 

### ISSUE THREAD

**Issue by jmgonzalezp** [grafana/grafana#16270]
**What happened**: diff calculation in alerts returns absolute values

**What you expected to happen**: negative values when actual values is higher than the compared one

**How to reproduce it (as minimally and precisely as possible)**: create an alert with diff calculation

**Anything else we need to know?**: I think that it was working before 6.0.0 upgrade

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: graphite
- OS Grafana is installed on: Red Hat 7
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/22073040/55139999-57d2e180-5137-11e9-9872-d0a1533fc1c8.png)

**Comment by jmgonzalezp** [comment]
Hello, think you mean that the rule is correct but not the name, are you planning then to include a real diff rule for alerts?

**Comment by ArmedChef** [comment]
+1

It'd be great for us to have both sets of functions (one for the real value and one for the absolute values).

**Comment by webhalla** [comment]
Hi all, 
I would like to take this issue and create a PR for it. 
But before starting, I want to align .. please give me some feedback before I go ahead

Firstly, I will fix the issue https://github.com/grafana/grafana/issues/16270 and 
* rename the current reducer "diff" and "percent_diff" to "diff_abs" and "percent_diff_abs"

Secondly, I will fix teh issue https://github.com/grafana/grafana/issues/10129 and 
* provice a new reducer "diff" and "percent_diff" which is comparable to "diff_abs" and "percent_diff_abs" but return the signed differences

**Comment by webhalla** [comment]
Hi all, 
I would like to take this issue and create a PR for it. 
But before starting, I want to align .. please give me some feedback before I go ahead

Firstly, I will fix the issue https://github.com/grafana/grafana/issues/16270 and 
* rename the current reducer "diff" and "percent_diff" to "diff_abs" and "percent_diff_abs"

Secondly, I will fix teh issue https://github.com/grafana/grafana/issues/10129 and 
* provice a new reducer "diff" and "percent_diff" which is comparable to "diff_abs" and "percent_diff_abs" but return the signed differences

**Comment by martinbruntsch** [comment]
Hi all, 
I would like to take this issue and create a PR for it. 
But before starting, I want to align .. please give me some feedback before I go ahead

Firstly, I will fix the issue https://github.com/grafana/grafana/issues/16270 and 
* rename the current reducer "diff" and "percent_diff" to "diff_abs" and "percent_diff_abs"

Secondly, I will fix teh issue https://github.com/grafana/grafana/issues/10129 and 
* provice a new reducer "diff" and "percent_diff" which is comparable to "diff_abs" and "percent_diff_abs" but return the signed differences

**Comment by vikkyomkar** [comment]
@martinbruntsch have you started working on fixing this issue? ..if not then can I take this up ?

**Comment by danieldistler** [comment]
It seems diff actually returned negative values before 28eaac3a9c7082e8c496005c1cb66b4b70a4f82f which changed when the implementation of diff and percent_diff were extracted to a common function. So using v5.4.3 might be a workaround to be able to use diff with negative values until this issue is fixed.

**Comment by danieldistler** [comment]
Another possible workaround:
Add the difference transformation to the select clause of the query and use the sum reducer in the query condition. The sum of all differences is the same as the difference of the first and the last value.

For the percent case: Add a second condition and check if the difference is below 0.
