### ISSUE TITLE
Datapoints out of time range

### ISSUE THREAD

**Issue by MikeMester** [grafana/grafana#1627]
Hello,

I am having an issue with grafana 1.9.1 with graphite 0.9.13 and InfluxDB  

When i run my queries for the graph i get "datapoints out of time range".  I can run the same query from the cli and get values back.  I am able to run these queries locally.  

select mean(value) from Disk_Usage where host = '$host_name' and metric = 'sensu.$host_name.boot.used_percentage' 

where $host_name is a variable tied to a host.  Changing it to a name instead of a variable doesnt change the graph error.  

I have looked around the forums and havent seen some mentions to similar issues but not exactly.  I have checked the timezone on both the graphite server and the influxDB.  They are the same and are set by ntp.  

Thanks

**Comment by torkelo** [comment]
did you include where $timeFilter in your query?
