### ISSUE TITLE
Loki search preview highlighting is broken

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#16277]
**What happened**:

When changing search terms in Explore/Loki, the found terms are no longer highlighted.

**What you expected to happen**:

If I modify a search term, I want a preview of the matches.

**How to reproduce it (as minimally and precisely as possible)**:

0. Explore + Loki
1. Select a stream that returns some logs
2. Add a search term to the query, something that would produce a match, but dont run the query
Result A: there is no preview of a search match in the results
3. Run the query, now results are highlighted
4. Change the search term slightly so that it would match a different term
Result B: The new term is not highlighted

Note that when you run a query, the highlight preview happens quickly (you can tell a preview match apart from a normal match by its dotted underline), but is replaced quickly with the results of the query (and the preview highlighting disappears).

This used to work, and the main purpose of the feature is to test regexps matching on the existing results before actually running the query.

I've noticed this regression while reviewing #15948, but the regression happened already before that.

**Comment by steven-sheehy** [comment]
Ah, I noticed this too but didn't know what the expected functionality since it's never worked for me 😄

**Comment by torkelo** [comment]
would this not be very expensive to re-render the log rows for every keypress?

**Comment by steven-sheehy** [comment]
It only does it for the first 100 rows, according to the [code](https://github.com/grafana/grafana/blob/e6d9a524b4f974f37a7001a776d1d4e408f8b6b0/public/app/features/explore/Logs.tsx#L187)

**Comment by davkal** [comment]
Yup, was quite performant. Limited to first 100 rows and quite a [high debounce interval](https://github.com/grafana/grafana/blob/e6d9a524b4f974f37a7001a776d1d4e408f8b6b0/public/app/features/explore/QueryRow.tsx#L88)

**Comment by hugohaggmark** [comment]
This stopped working when we decided to not run queries on each keypress as this [issue](https://github.com/grafana/grafana/issues/14982) states. 

Do we want to go back to executing queries at every keypress or is there a way in between, that only highlights words?

**Comment by davkal** [comment]
Queries should not be run on every keypress, only on Return and button clicks.
The highlighting works separately from queries and applies the regex to the results of the last query run in-browser. The highlight evaluation should happen on a debounced keypress.
