### ISSUE TITLE
Crash if `grafana-server` is started with a malformed entry in `/etc/grafana/grafana.ini`

### ISSUE THREAD

**Issue by timvandermeij** [grafana/grafana#16283]
First of all, thank you for your work on Grafana!

**What happened**: The `grafana-server` process crashes with a segmentation fault if it is started with a malformed entry in `grafana.ini`.

**What you expected to happen**: The `grafana-server` process should not crash with a stack trace but show a user-friendly error message instead saying that the entry is malformed.

**How to reproduce it (as minimally and precisely as possible)**:

- Install Grafana 5.4.2 on Debian Jessie (or any other OS since it's not OS-specific).
- Use the default configuration file in `/etc/grafana/grafana.ini` and change the `root_url` line from `;root_url = http://localhost:3000` to `root_url = %(protocol)s://%(domain)s:%(port)s/grafana/`. Using `port` here is invalid.
- Execute `grafana-server -config /etc/grafana/grafana.ini -homepath /usr/share/grafana` and notice the message `panic: runtime error: invalid memory address or nil pointer dereference` with a stack trace.

**Anything else we need to know?**: It looks very similar to #6731, so it's either a different scenario or it regressed in a later version of Grafana.

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Graphite
- OS Grafana is installed on: Debian Jessie
- User OS & Browser: Ubuntu 18.04 LTS, Firefox 66.0
- Grafana plugins: n/a
- Others: n/a

**Comment by Hofls** [comment]
I am on it.

**Comment by timvandermeij** [comment]
Thank you for fixing this!
