### ISSUE TITLE
Support using avatar from AD/LDAP

### ISSUE THREAD

**Issue by greenpau** [grafana/grafana#16281]
**What would you like to be added**:

Active Directory have user attribute: `thumbnailPhoto`. It is basically base64 encoded image.
Please add the option of using it as avatar for LDAP-authenticated users.

**Why is this needed**:

Improve user experience.

**Comment by clorch** [comment]
My organization has the attribute `photo` that contains a URL to a JPEG file with the person's photo. If the feature will be considered for implementation I would propose to add also support for avatar images references by URL.

**Comment by Michuelnik** [comment]
I would love to see this feature implemented.
We are using the good old LDAP `jpegPhoto` attribute.
I do not want to force my grafana users to use gravatar. Especially since they maintain personal pictures in our LDAP which most of them would not want to use publicly.

**Comment by chris-est** [comment]
Is this implemented or is there another reasen why this was closed? 
I think it would be a great addition to Grafana, we also use the jpegPhoto ldap attribute in our organization.

**Comment by helmut72** [comment]
Because I want to use 2 different Grafana instances for different usage (one for users, one for logs only), using one instance with OIDC and one with LDAP auth, I have opened a new discussion/feature request here: https://github.com/grafana/grafana/discussions/57881
