### ISSUE TITLE
Getting error "Cannot read property length of undefined" on grafana dashboards

### ISSUE THREAD

**Issue by suresh447** [grafana/grafana#16289]
**What happened**:
On grafana dashboard after adding "Terms" in the query along with count it is showing below error

![image](https://user-images.githubusercontent.com/33586664/55220165-a4202f00-51d4-11e9-9837-aa29c1758615.png)
  

**What you expected to happen**:
I want to add Terms group by to view my pods on the dashboard 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Ubuntu
- User OS & Browser: windows and Chrome
- Grafana plugins: world Ping
- Others:

**Comment by torkelo** [comment]
What is your query returning ? Check query inspector. 

Also try upgrading to latest Grafana.

**Comment by suresh447** [comment]
I didn't made any changes but it is working fine now thanks for your response.
