### ISSUE TITLE
Zoom in on time shifted graphs selects wrong time

### ISSUE THREAD

**Issue by girishjk** [grafana/grafana#16280]
Happens with Grafana 6.0.2 (3f4c2e7), InfluxDB source. 
I have a few time shifted graphs with 24h time shift, ~~with Relative time of 30d~~. When I zoom into this graph to see points around specific time range, I end up with graph / dashboard zoomed into that specific time minus the time shift (24h)
For instance, when I want to look into this Monday's data, I'll ve shown Sunday's data instead because of the time shift.(although the original graph has correct X axis)
I'm able to reproduce this on play.grafana.org

**Comment by girishjk** [comment]
Looks like it is expected behavior of time shifted graphs. Apologies

**Comment by marefr** [comment]
There's an open feature request of this functionality #15829
