### ISSUE TITLE
Use SeriesData format for loki/logging

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16287]
We recently added SeriesData class that represents both TimeSeries and TableData equally well.  It would be great if the logs datasource used the same structure.  This would make it very easy for any datasource to implement the logs interface `SELECT time as ts, line FROM table` and would make loki usable in other visualisation panels without any other changes.

HUGE caveat, I have not used loki and don't know what I am talking about!  The demos look cool and I would love to be able to use explore logging with stuff that does not go through loki.

In #16285, I explored if SeriesData could transfer everything you need -- I think it can.  Check:
 * [logStreamToSeriesData](https://github.com/grafana/grafana/blob/ad1320b492038f82aed0eb803aef8c193e94ce6d/public/app/plugins/datasource/loki/result_transformer.ts#L112)
 * [seriesDataToLogStream](https://github.com/grafana/grafana/blob/ad1320b492038f82aed0eb803aef8c193e94ce6d/public/app/plugins/datasource/loki/result_transformer.ts#L126)

Ideally, loki could output standard SeriesData[] like:
```
{
    labels: {
      foo:'bar'
    },
    fields: [
      { name: 'ts', type: FieldType.time }, 
      { name: 'line', type: FieldType.string }
    ],
    rows: [
      ['1970-01-01T00:00:00Z','WARN somethign'],
      ['1970-01-01T00:00:00Z','INFO more'],
    ]
  };
```

Then the explore logs viewing component would take any SeriesData[] result (from loki/SQL/influx, whatever) and process it for use in the explore UI.  Maybe it converts to/from LogStream or maybe directly from SeriesData#row > LogRowModel.  Maybe we don't need LogRowModel, but just add more fields to SeriesData so you have everything you need

Essentially I am suggesting that a lot of what happens in loki datasource should happen in the view component, not the datasource.  Then we could use any datasource to load data without changing too much.

**Comment by torkelo** [comment]
Yes! makes so much sense. This is something I have been thinking about as well, was about to start this next week when the explore team will start working on adding more Explore logging support to other data sources. 

The LogStream type is one I have never liked, was originally (before SeriesData work) thinking of returning LogsModel directly. But think SeriesData makes more sense. Might need some more meta data for it. 

Also want to support log queries that can return a full time series histogram and log lines (would be in two different SeriesData I think). As Elasticseach can do this easily (not Loki currently)

**Comment by davkal** [comment]
This is a very welcome effort that we've been putting off. The logs model was clearly written with Loki in mind. It existed to complement the timeseries and table models. It does contain some Loki-isms that are worth pointing out: 

1) Loki returns a set of streams. Each stream is identified by a unique set of labels. The streams need to be merged by grafana to be properly sorted by time.
2) Loki does not return a timeseries to indicate log volume. It's calculated on the fly by grafana and added to the logs model.

**Comment by ryantxu** [comment]
1. Can the streams (SeriesData) be merged by the visualisation, not the datasource?  This matches the model of how the standard graph puts things in order visually regardless of how the datasource returns them.

2. Similarly, can the log volume series be calculated outside the datasource?  Essentially scans a set of SeriesData and add another one, or maybe add additional fields/columns to the series.

This points to a general process for transforming SeriesData[] that could be structured in a way that it is either user configurable, and/or applied by visualisations.  For example:
 * read field[line], extract LogLevel, and add field[LogLevel]
 * Scan all SeriesData[] and generate a histogram based on activity, return SeriesData
 * Add a new field based on math to other values in the row.

I think this breaks down into high level process that look like:
```
 transform(SeriesData[], options):SeriesData[]
```
We may want different concept for things that intend to replace/modify existing stuff vs returning new data based on the input.  (add column vs generate histogram)

Rather than building new models for each process, it would be great to try to use the same one (SeriesData) so that the results can easily be passed to other panels with less domain knowledge.  To support this, we will need to improve the possible metadata attached to SeriesData/Fields.
