### ISSUE TITLE
Alerting: No Data should take "For" setting into account

### ISSUE THREAD

**Issue by azhiltsov** [grafana/grafana#16290]
**What happened**:
Alert notification send immediately after "No Data" condition
**What you expected to happen**:
Alert notification should be delayed the same way as for "Alerting" condition obeying "For" setting
**How to reproduce it (as minimally and precisely as possible)**:
Create alert rule
set 'If no data or all values are null' to "No Data"
set For "5m"
simulate "No Data" condition from the data-source side
Receive notification immediately

**Anything else we need to know?**:

**Environment**:
- Grafana version:
5.4.3
- Data source type & version:
carbonapi (graphite 0.12 compatible)
- OS Grafana is installed on:
Linux Centos 7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
I think the logic in `pkg/services/alerting/eval_context.go` > `GetNewState() / `getNewStateInternal()` nees to change. `GetNewState()` will return on a `no_data` since it is no `AlertStateAlerting` , and this happens before the For logic could determine `AlertStatePending`.

**Comment by marefr** [comment]
Re-labeled this as a feature request since the For feature was not built with No Data in mind.

**Comment by patricktokeeffe** [comment]
In current releases (e.g. 6.4.3), the default alert rule contains both
* For: 5m
* *and* If no data or all values or all &rarr; No Data

At the same time, documentation notes: 
> Do not use `For` with the `If no data or all values are null` setting set to `No Data`. The triggering of `No Data` will trigger instantly and not take `For` into consideration. This may also result in that an OK notification not being sent if alert transitions from `No Data -> Pending -> OK`.

Because 'No data' is about handling errors for a rule and "For" applies to the rule evaluation (not the conditions/query), I think the `type/bug` label was appropriate.

**Comment by marefr** [comment]
@patricktokeeffe thanks. I agree and your comment make sense. Changed to bug.

**Comment by Martchus** [comment]
We see the same issue on our instance - except that it happens with DatasourceError. Strangely, it worked at some point and only ceased to work recently. When it worked and when it ceased to work we were using version 9.4.7. Switching to 9.5.1 didn't help. We've been using the new alerting system for a while now. Just for additional context, that's the issue we're tracking this on our side: https://progress.opensuse.org/issues/128870

**Comment by manojm321** [comment]
I see a similar issue with 10.1.1

![Screenshot from 2023-10-16 11-22-49](https://github.com/grafana/grafana/assets/2082506/0e960b72-2c0c-4cc9-b566-11d1938659b0)

Alert settings:

![image](https://github.com/grafana/grafana/assets/2082506/d280cdeb-ae93-479b-a90c-b11c88e6d5a4)


**For** is set to 5min and eval to 1m

[Documentation](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#configure-no-data-and-error-handling) states: 
```
Alert rules that are configured to fire when an evaluation returns no 
data or error only fire when the entire duration of the evaluation 
period has finished. This means that rather than immediately firing when
 the alert rule condition is breached, the alert rule waits until the 
time set as the For field has finished and then fires, reducing alert noise and allowing for temporary data availability issues.
```

But from he logs it's clear it fire immediately on error without waiting for 5min.

04:25:06 state=Normal
04:26:08 DataSourceError
04:26:08 Sending alert..

**Comment by jdverman** [comment]
We experience the same issue with AWS managed Grafana 9.4: DatasourceNoData immediately sending an alert instead of waiting for the 5 minute evaluation period. Please look into this!

**Comment by KaplanSarah** [comment]
The new 'Keep Last State' option as of 10.4 will respect the 'for' period.

**Comment by JohnnyQQQQ** [comment]
We now have https://github.com/grafana/grafana/pull/65574 merged, that does fix this. We also have now keep last state which can be used to not directly alert on flapping conditions. Closing this, feel free to open a new issue if you see any bugs with it.
