### ISSUE TITLE
Text Query Editor in explore mode in grafana v6

### ISSUE THREAD

**Issue by sbenzakountradelab** [grafana/grafana#16293]
**What would you like to be added**: 
I would like to have the possibilty to write influxdb request with the text editor in the explore mode. Currenlty it is not possible to switch to the editor mode. 

**Why is this needed**: 
I would like to aggregate different metrics together. for example this kind of request:
_select sum("field1")/sum("field2) from "my_measurement" group by time(1d) where time > now() - 30d fill(0)_

Thank you

**Comment by kaydelaney** [comment]
Closed by https://github.com/grafana/grafana/pull/17870
