### ISSUE TITLE
Broken editing of Graphite panels

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#16291]
**What happened**:

When Graphite queries are edited the changes do not stick.

Error in console about **`Cannot read property 'regex' of undefined'`**

![image](https://user-images.githubusercontent.com/345210/55224613-2f1f1a80-5211-11e9-9f40-14f564edcb7b.png)

**How to reproduce it (as minimally and precisely as possible)**:

Add a field like this and apply, observe error in console

![image](https://user-images.githubusercontent.com/345210/55224652-4827cb80-5211-11e9-85e2-2f19dfe06aea.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.0-ce613c58pre

**Comment by towolf** [comment]
Downgrade to 6.0.2 helps.

**Comment by torkelo** [comment]
thanks for reporting this, will investigate!
