### ISSUE TITLE
Browser search is not working properly with built-in JSON editor

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#16294]
**What happened**:
It's not possible to use browser search with built-in JSON editor (and this is not problem of browser search).
As you can see, it ignores everything below bottom line of _gf-form_ div container. 
Found: 0/0

![2](https://user-images.githubusercontent.com/1700286/55227691-34885f00-5229-11e9-9332-62bd7e6a00bf.gif)

**What you expected to happen**:
Of course browser search should have access to all code inside editor container.

**How to reproduce it (as minimally and precisely as possible)**:
Create dashboard with some widgets.
Open JSON Model page.
_If JSON is long enough, you can see a scrollbar, so some code obviosly is hidden._
Open browser searchbar with CTRL+F hotkey.
Type any hidden code to find it.

**Tested with Chrome latest and Firefox 66.0.2 - the same behavior.** 

**Environment**:
- Grafana version: Grafana v6.0.2 (commit: 3f4c2e7)
- Data source type & version: Zabbix Source
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome latest
- Grafana plugins: Zabbix Source plugin

**Comment by torkelo** [comment]
Strange, works for me in Chrome & Ubuntu

**Comment by mammuthus** [comment]
> Strange, works for me in Chrome & Ubuntu

Tried it with Chrome/Firefox & Windows 7 SP1 
with some old stuff like Chrome 49 & Windows Server 2003
with Chromium 71 & Fedora
the same :(

**Comment by torkelo** [comment]
Works for me in Firefox as well. Make sure your focus is outside the text area (the text area cannot have focus)

**Comment by mammuthus** [comment]
> Works for me in Firefox as well. Make sure your focus is outside the text area (the text area cannot have focus)

Yes, focus is outside 
(when focus is inside, no search bar appears at all when I press CTRL+F)

**Comment by mammuthus** [comment]
Also I have some errors in debug console after reloading page and two errors after pressing CTRL+F with **inside** focus, may be it can be helpfull?
![image](https://user-images.githubusercontent.com/1700286/55230697-99e04e00-5231-11e9-9e75-96dbc91ac6f1.png)

**Comment by daniellee** [comment]
I can recreate it - I can't search for anything that is not visible on screen in the json model modal.

**Comment by mammuthus** [comment]
Seems like only I have that issue :(
I think I can close it, unless I try it on fresh installation
