### ISSUE TITLE
Support react based Datasource Config pages

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16307]
While working on #16282, I found that the Datasource config page still needs to be defined in angular.  It would be great to have the option to do this in react.

**Comment by torkelo** [comment]
it would be a huge amount of work I think, except to be usable by most data sources we also need to port https://github.com/grafana/grafana/blob/master/public/app/features/datasources/partials/http_settings.html to react

**Comment by torkelo** [comment]
This is is kind of done in: https://github.com/grafana/grafana/pull/16748 

The biggest remaining work is to port the http settings directive to react and have it available to react & angular data sources.

**Comment by ryantxu** [comment]
Yes, this works!  I just converted from angular to react in #16856
