### ISSUE TITLE
React QueryEditors should support getCollapsedText()

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16308]
The angular based QueryCtrl can set the collapsed text using: `getCollapsedText()`, The react version should be able to do something similar.

I found this while working on #16282

**Comment by torkelo** [comment]
why did you close this? is it done, or no need?

**Comment by ryantxu** [comment]
`getQueryDisplayText` was added to `DataSourceApi`, so not needed directly in QueryEditor:

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/types/datasource.ts#L173
