### ISSUE TITLE
Docs: Link to Youtube video in time range controls page no longer available

### ISSUE THREAD

**Issue by linceaerian** [grafana/grafana#16302]
Hello,

Due to the copyreich, the youtube video link of " when will then be now?"
https://www.youtube.com/watch?v=VeZ9HhHU86o was removed.

I propose either to replace it by "not a video youtube" ex: https://imgur.com/gallery/TFaFbpb
Or just add a quote caption with a wiki link.

Regards

**Comment by marefr** [comment]
Thanks for the feedback. I suggest we simply remove `Users often ask, when will then be now?` .
