### ISSUE TITLE
Elasticsearch no hits. {"size": 0} on query

### ISSUE THREAD

**Issue by ValeryNo** [grafana/grafana#16309]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Closing this due to lack of information
