### ISSUE TITLE
v2 alpha: aliases do not apply correctly to metrics when preceding metric has multiple tags

### ISSUE THREAD

**Issue by alienth** [grafana/grafana#1630]
Bit confusing, I'm sure. This occurs with opentsdb metrics. Haven't tried to test on any other backends.

Here is how to repro:

1. Add a metric which has multiple tags. Break those tags into separate lines by setting "tagName = *". 

1. Add a metric below that metric, and set an alias on it.

The alias set on the second metric will instead apply to the second line from the *first* metric, when looking at a tooltip.

**Comment by torkelo** [comment]
yea, will try to fix soon, Same as #1601
