### ISSUE TITLE
Autorenewal of cert data for InfluxDB datasource

### ISSUE THREAD

**Issue by vmario89** [grafana/grafana#16304]
Hi, i am using latest Grafana 6.0.2 and have three InfluxDB datasources. Because my datasources communicate by SSL, i have to deploy cert, key and CA cert in grafana datasource config. This needs to be done manually every 90 days because i use lets encrypt. is there any way to automate that cert update in Grafana with some kind of console query?
![grafik](https://user-images.githubusercontent.com/5631071/55245519-96ee5900-5243-11e9-9183-c62321ce5f8b.png)

regards, Mario

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You could update the datasources using Grafana's HTTP API.
