### ISSUE TITLE
ProvisioningService error in custom Docker container

### ISSUE THREAD

**Issue by k00p** [grafana/grafana#16305]
**What happened**:

Received errors docker service logs pertaining to ProvisioningService after building custom docker container as suggested in [documentation](http://docs.grafana.org/installation/docker/#building-a-custom-grafana-image-with-pre-installed-plugins):

```
t=2019-03-29T15:30:06+0000 lvl=info msg="Initializing ProvisioningService" logger=server
t=2019-03-29T15:30:06+0000 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=/etc/grafana/provisioning/datasources error="open /etc/grafana/provisioning/datasources: permission denied"
t=2019-03-29T15:30:06+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: permission denied"
t=2019-03-29T15:30:06+0000 lvl=info msg="Initializing TracingService" logger=server
t=2019-03-29T15:30:06+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/etc/grafana/provisioning/dashboards error="open /etc/grafana/provisioning/dashboards:
permission denied"
```

**What you expected to happen**:

Some graceful failure is expected here - it appears that the ProvisioningService error stops the initialization process and initialization messages are not received from TracingService and Stream Manager. If the ProvisioningService fails to start, it should not block subsequent service starts, or their logging.

**How to reproduce it (as minimally and precisely as possible)**:

Build a docker container from the default Dockerfile (grafana/packaging/docker/custom/Dockerfile):

```
ARG GRAFANA_VERSION="latest"

FROM grafana/grafana:${GRAFANA_VERSION}

USER grafana

ARG GF_INSTALL_PLUGINS=""

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi
```

**Anything else we need to know?**:

Remediation:

Creating the provisioning paths and setting permissions in the Dockerfile resolves the issue:
```
ARG GRAFANA_VERSION="latest"

FROM grafana/grafana:${GRAFANA_VERSION}

USER root

# Build provisioning paths
RUN mkdir -p /etc/grafana/provisioning/notifiers && \
    mkdir -p /etc/grafana/provisioning/datasources && \
    mkdir -p /etc/grafana/provisioning/dashboards && \
    chmod -R 755 /etc/grafana/provisioning

# Assert permissions
RUN chown -R grafana:grafana /etc/grafana/ 

USER grafana

ARG GF_INSTALL_PLUGINS=""

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi
```

**Environment**:
- Grafana version: grafana:6.0.2
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: Rancher OS & N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment]
@k00p mind opening a PR with your fixes?

**Comment by k00p** [comment]
OK PR submitted - very happy to help.

**Comment by xlson** [comment]
Have you by any chance changed the filemask on your system? Those paths exist in the docker container (they are created in the `grafana/grafana` image) but are owned by root. This is fine on most systems as the default permissions for everyone is `r-x`, but if you have changed the filemask that will not be the case.

**Comment by k00p** [comment]
@xlson interesting - I will have to test this when I get some time.  If the intention is for the grafana/grafana image to have the proper paths in existence, then the PR should be closed/rejected in favor of resolving what is going on with those paths. Can you confirm that those paths exist in the image for 6.0.2 and `latest` (6.1.0 right now)? I am setting up a new testing environment currently and it will take some time to get to a position where I can pull the image.

**Comment by k00p** [comment]
OK, I can confirm that the directories are there in a fresh image (I checked `latest` as well):

```
$ docker run --rm -it --entrypoint bash grafana/grafana:6.0.2
Unable to find image 'grafana/grafana:6.0.2' locally
6.0.2: Pulling from grafana/grafana
f7e2b70d04ae: Pull complete 
a0d6f8d6b78d: Pull complete 
f6dfdd9a4cc9: Pull complete 
a47b02586edb: Pull complete 
ac3d2f7cc2e4: Pull complete 
857ef2887ebc: Pull complete 
Digest: sha256:8b48efe9ecb04ba1165531a59ef6c6a9d4f4c299ab621175f7d3c0a8bf1c5bdf
Status: Downloaded newer image for grafana/grafana:6.0.2
grafana@3d14ffb6969e:/usr/share/grafana$ ls -ltra /etc/grafana
total 44
drwxr-xr-x. 5 root root  4096 Mar 19 13:42 provisioning
-rw-r--r--. 1 root root  2269 Mar 19 13:42 ldap.toml
-rw-r--r--. 1 root root 16456 Mar 19 13:42 grafana.ini
drwxr-xr-x. 3 root root  4096 Mar 19 13:42 .
drwxr-xr-x. 1 root root  4096 Apr  3 20:01 ..
```

Closing this issue and the related pull request - it must have been something specific to my production build environment.

**Comment by xlson** [comment]
Let me know how it works out with your custom image.

**Comment by k00p** [comment]
@xlson it is working well - building a custom image has been helpful because of "corporate proxy reasons".  I have the Grafana image built by an on-premise GitLab instance using GitLab CI, stored in the GitLab Docker repository, and then pulled and deployed to a Docker Swarm. With the custom image, I get consistent deployment to multiple environments.

I still am not 100% sure how I clobbered that `provisioning` directory, but I'm happy it's not a problem for the public project.

**Comment by xlson** [comment]
I'm glad to hear it's working out for you. Thanks for sharing your use case!
