### ISSUE TITLE
Направление текста по оси x

### ISSUE THREAD

**Issue by iiiparadoxxxiii** [grafana/grafana#16316]
Привет! 
Очень хотелось бы менять направление текста в подписи оси Х. т.к. все метрики не влазят. Может быть уже кто-то это уже делал? (гугл не помог)
Вот что у меня получается на данный момент. 
![image](https://user-images.githubusercontent.com/13498781/55286734-1fdad100-53b9-11e9-9ffa-1f9cf8f6acce.png)

А так же задавать формат времени  оси х
![image](https://user-images.githubusercontent.com/13498781/55286795-c7580380-53b9-11e9-8390-b70c972861ab.png)
например DD.MM или DD.MM.YY

**Comment by torkelo** [comment]
Issues needs to be in english. Are you using graph histogram feature and the series names are too many and to long?
