### ISSUE TITLE
Missing data after removing one source

### ISSUE THREAD

**Issue by henkye** [grafana/grafana#1631]
Hello, hope I'm not duplicating something.

When removing one server (data source) from graph, it seems to also removes some other. Pictures says more than a words:
Pic1 – server removed at marked time (note number of bars (colours) before and after)
Pic2 – longer time range of what happened
![grafana](https://cloud.githubusercontent.com/assets/4472325/6798760/ae8db888-d210-11e4-8d8c-244f3597f63e.png)
![grafana2](https://cloud.githubusercontent.com/assets/4472325/6798766/b42ab70a-d210-11e4-8303-3c0d73367817.png)
![grafana3](https://cloud.githubusercontent.com/assets/4472325/6798768/b8f0052e-d210-11e4-983d-b55a6c249612.png)

**Comment by torkelo** [comment]
yepp, that is how stacking works (all series needs a value), please change null point mode to null as zero, or connected

**Comment by henkye** [comment]
null as zero helped, thank you very much.
Just a note: connected was already there.
