### ISSUE TITLE
testDatasource() reject should not trigger a save

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16310]
While working on #16282, I stumbled into this edge case...

if your `testDatasource()` call fails, it still saves ☹️ 

![image](https://user-images.githubusercontent.com/705951/55258953-8fb65380-5221-11e9-91d6-977431e739fa.png)

The 2x was just trying to get a screenshot!

**Comment by torkelo** [comment]
The way the backend data proxy works Grafana needs to save a datasource in order to test the connection as the dataproxy only works works / loads saved datasources

**Comment by torkelo** [comment]
Which is why the save button saves "Save & Test" .
