### ISSUE TITLE
Share button icon is not shown in the dashboard view?

### ISSUE THREAD

**Issue by SeppPenner** [grafana/grafana#16314]
**What happened**:

The share button icon is not shown in the dashboard view.

**What you expected to happen**:

The share button icon should be shown in the dashboard view.

**How to reproduce it (as minimally and precisely as possible)**:

Nothing special.

**Anything else we need to know?**:

Nope.

**Environment**:
- Grafana version: Grafana v6.0.2 (3f4c2e7)
- Data source type & version: MySQL (MariaDB 10.3.7-0051)
- OS Grafana is installed on: Raspian 9:

```bash
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

- User OS & Browser: Windows 10, Mozilla Firefox 66.0.2 (64-Bit)
- Grafana plugins: MySQL data source plugin
- Others:

![grafik](https://user-images.githubusercontent.com/9639361/55282171-53791500-533f-11e9-9728-a6d2d0b699ed.png)

**Comment by torkelo** [comment]
Do you get this all the time? Unable to replicate this with Firefox 66. Can you replicate on https://play.grafana.org?

**Comment by torkelo** [comment]
Do you get this in Chrome as well? And please report if you get this on https://play.grafana.org as well so we know if it's an issue with your install or a general browser issue.

**Comment by SeppPenner** [comment]
@torkelo Thank you for your reply. I will test this as soon as possible and give you feedback.

**Comment by SeppPenner** [comment]
@torkelo Ok, I've tested this.

I get this error with Firefox every time (at least as far as I can say) on the local instance and as well on play.grafana.org.

![grafik](https://user-images.githubusercontent.com/9639361/55420464-670ec080-5577-11e9-9823-08048dd5bc4f.png)

With Chrome, I get an error on my local instance and on play.grafana.org:

```bash
If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath

3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build

4. Sometimes restarting grafana-server can help
```

In the debug window in Chrome I can see:

```bash
alertDef.ts:29 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at e.exists (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:159831)
    at e.getBool (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:159253)
    at new e (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:185719)
    at Object.<anonymous> (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:185641)
    at o (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:518)
    at Object.<anonymous> (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:40661)
    at o (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:518)
    at Module.<anonymous> (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:22:435480)
    at o (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:518)
    at n (https://play.grafana.org/public/build/app.d3fff3b4305980ef147d.js:1:387)
(index):1 Unchecked runtime.lastError: The message port closed before a response was received.
```

In the debug window in Firefox, I don't see anything.

**Comment by SeppPenner** [comment]
Okay, I found the issue, I guess. This issue is caused by the Adblock Plus plugin...
