### ISSUE TITLE
Please implement or document a way to do prebucketed SQL heatmap queries

### ISSUE THREAD

**Issue by narc-Ontakac2** [grafana/grafana#16318]
Doing a heatmap with prebucketed data from an SQL query could be pretty straight forward. A SELECT with a GROUP BY interval (lower bound) and bucket (lower bound) that COUNTs the entries should do it.

However I can't get this to work and I can't find any documentation on it.

**Comment by torkelo** [comment]
Think the only requirement is that the query returns a time series for each bucket, the time series name needs to be numeric (to represent the upper or lower bound for the bucket)

**Comment by torkelo** [comment]
http://docs.grafana.org/features/panels/heatmap/#pre-bucketed-data

**Comment by narc-Ontakac2** [comment]
It is actually possible with postgresql, but really hacky to do. 

The first thing is a query variable that generates a column list with generate_series. This is included with ${column_list:csv} to avoid quoting. The actual query is wrapped with crosstable.

Once again the database is a friend.

**Comment by Alkarex** [comment]
@narc-Ontakac2 I have the same need. If you still have it, would you mind posting your example of solution with PostgreSQL?

**Comment by narc-Ontakac2** [comment]
This is what I did:

The constant, that holds the column llist:

$heat_cols | SELECT string_agg('"'\|\|x::TEXT\|\|'" INT', ', ') FROM generate_series(0, $top_bucket) s(x);

The query that uses crosstab:

SELECT * FROM crosstab(
$$
SELECT $__timeGroup(l.request_time, $interval),
       (l.request_duration_micro/100000) AS bucket,
       COUNT(1)
FROM logs l
WHERE $__timeFilter( l.request_time)
AND l.status_code < 300
GROUP BY bucket, time
$$,
$$
SELECT * FROM generate_series(0,$top_bucket)
$$) AS t(time INT, ${heat_cols:csv})

**Comment by narc-Ontakac2** [comment]
Actually heat maps turned out to be less useful the I initially thought for visualizing performance. By now I use the postgres statistical functions STDDEV_POP and PERCENTILE_CONT (for a measurement that can be understood by end users).

**Comment by Alkarex** [comment]
@narc-Ontakac2 Thank you very much. Very helpful!
