### ISSUE TITLE
Elasticsearch: Support group only by "Geo Hash Grid" in table panel

### ISSUE THREAD

**Issue by ValeryNo** [grafana/grafana#16311]
**What happened**:
No data is displayed when trying to setup WorldMap widget or a Table with Elastic datasource when Grouped By - Geo Hash Grid. 

I checked that field is indeed indexed as geoip in elastic and there are data samples, but nothing shows up in Grafana when that aggregation is used.
Checked with a table widget to make sure it's not just WorldMap problem.
Seems to be specific for that type of aggregation - "Geo Hash Grid".

**What you expected to happen**:
>0 items is returned by generated Elastic query and data is displayed on the WorldMap / Table.

**How to reproduce it (as minimally and precisely as possible)**:
Have an Elastic index with a geoip filed. Make sure it has a correct type.
Example `{
  "nginx": {
    "access": {
      "referrer": "-",
      "response_code": "400",
      "remote_ip": "36.152.65.206",
      "geoip": {
        "continent_name": "Asia",
        "country_iso_code": "CN",
        "location": {
          "lon": 113.7266,
          "lat": 34.7725
        }
      },
      "method": "GET",
      "user_name": "-",
      "http_version": "1.1",
      "body_sent": {
        "bytes": "150"
      },
      "remote_ip_list": [
        "36.152.65.206"
      ],
      "url": "/",
      "user_agent": {
        "original": "-",
        "os": "Other",
        "name": "Other",
        "os_name": "Other",
        "device": "Other"
      }
    }
  },
  "read_timestamp": "2019-03-29T17:22:04.353Z",
  "@timestamp": "2019-03-29T17:22:04.000Z"
}`

Add a Table widget in grafana, specify elastic search index.
Lucene query: `kubernetes.container.name:"external-proxy-server" AND _exists_:nginx.access.geoip.location.lon`
Select group by - geo hash grid and enter nginx.access.geoip.location as a field name. Set precision to 4.

**Anything else we need to know?**:
There is a ticket opened on [WorlMap github](https://github.com/grafana/worldmap-panel/issues/82) which seemed to be pointing out where a root cause it. It suggests that a problem is in using `{"size": 0}` which doesn't work on ElasticSearch > 5.0.
**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Elastic 6.x. 
- OS Grafana is installed on: Cloud Hosted Grafana via Grafana.net
- User OS & Browser: Mac OS / Chrome
- Grafana plugins: Default for hosted instance on Grafana.net
- Others: Elastic server version 6.6

**Comment by marefr** [comment]
You need to group by date histogram. Grouping only by geo hash grid is not currently supported.

**Comment by aocenas** [comment]
@marefr Are you saying this works and they just need to add also date histogram group by in addition to the geo hash? Is there any issue with the behavior that we should fix in that case or is this just a UX annoyance.

**Comment by marefr** [comment]
@aocenas Just tried in latest master and it seems to work with the new panel panel without date histogram:
![image](https://user-images.githubusercontent.com/1668778/91290873-7c037980-e794-11ea-92c7-f2050c3dce65.png)

Confirmed also works with worldmap panel:
![image](https://user-images.githubusercontent.com/1668778/91290970-a6553700-e794-11ea-9a00-f525feccbb47.png)

**Comment by zoltanbedi** [comment]
Thanks for confirming @marefr. I'm going to close this as it seems to work now.
