### ISSUE TITLE
Unable to type in the Prometheus query field, under Variables

### ISSUE THREAD

**Issue by cybervedaa** [grafana/grafana#16329]
**What happened**:
When i try creating a dashboard variable of type=query, datasource=prometheus, i am unable to type in the "Query" text field, under "Query Options"

**What you expected to happen**:
I should be able to type a query in the "Query" text field, under "Query Options"

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new dashboard
2. Create a new dashboard variable
3. Under "General", select "Type" = "Query"
4. Under "Query Options", try to type a query in the "Query" text field. You will be unable to.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.0-beta1 (944e526)
- Data source type & version: Prometheus 2.4.2
- OS Grafana is installed on: Centos 7
- User OS & Browser: macOS High Sierra. Browser = Safari and Chrome
- Grafana plugins: No plugins installed
- Others: 
![image](https://user-images.githubusercontent.com/744605/55354862-a1933300-547b-11e9-85c4-9545cda1b8f9.png)

**Comment by passing** [comment]
I have noticed the same issue, but it seems to apply to any datasource type (checked for Grafana, InfluxDB and Elasticsearch)

Reproduced using docker (grafana/grafana:6.1.0-beta1)
The issue does not exist in the latest stable release (grafana/grafana:6.0.2)

**Comment by torkelo** [comment]
This is fixed in latest nightly and will be fixed in 6.1 stable (released today or tomorrow).

https://github.com/grafana/grafana/pull/16299
