### ISSUE TITLE
Use $GRAFANA_USER (env) when installing plugins 

### ISSUE THREAD

**Issue by Paul-Reed** [grafana/grafana#16320]
**What happened:**
Using 'user' ownership, installing a plugin fails, when using the Grafana-cli.
```
$ grafana-cli plugins install digiapulssi-breadcrumb-panel
Error: ✗ Could not create /var/lib/grafana/plugins/digiapulssi-breadcrumb-panel. Permission denied. Make sure you have write access to plugindir
```
**What you expected to happen:**
I expected that the plugin would be installed

**How to reproduce it (as minimally and precisely as possible):**
Install a plugin via the grafana-cli

**Anything else we need to know?:**
If I use 'root' to install a plugin, for example;
`$ sudo grafana-cli plugins install digiapulssi-breadcrumb-panel`
the plugin is installed, but has `root:root` ownership instead of `grafana:grafana`
See screenshot below.

**Environment:**
Grafana version: v6.0.2
Data source type & version: Influxdb
OS Grafana is installed on: Raspbian
User OS & Browser: Windows 10, Google Chrome
Grafana plugins: Worldping, Singlestat, Multistat.

![root](https://user-images.githubusercontent.com/973580/55294151-4d923b00-53f6-11e9-82c3-951dd1b7372e.PNG)

**Comment by torkelo** [comment]
yes, you need to "sudo" the plugins install, if root owns it will still be fine. as long as grafana user can read it. 

Grafana will change the ownership next time you install (which is why the older plugins have grafana owner)
