### ISSUE TITLE
Snapshot to raintank.io stop working after update to 6.x from 5.x (PROXY ISSUE)

### ISSUE THREAD

**Issue by lbsou** [grafana/grafana#16326]
Snapshot to raintank.io stop working after update to 6.x from 5.x

**How to reproduce it (as minimally and precisely as possible)**:

Create a snapshot to raintank.io with any dashboard will fail with the error "Failed to create external snaphost". Even a simple dashboard with text only. Local snapshot work without problem.

Chrome debug : 

VM14:1 POST https://xxx:3000/api/snapshots 500 (Internal Server Error)
(anonymous) @ VM14:1
(anonymous) @ angular.js:12759
(anonymous) @ angular.js:12492
(anonymous) @ angular.js:12244
(anonymous) @ angular.js:17051
(anonymous) @ angular.js:17095
$digest @ angular.js:18232
$apply @ angular.js:18531
(anonymous) @ angular.js:20448
h @ angular.js:6362
(anonymous) @ angular.js:6642
setTimeout (async)
i.defer @ angular.js:6640
a @ angular.js:20438
e.createSnapshot @ AdHocFiltersCtrl.ts:87
fn @ VM131:4
i @ angular.js:27341
$eval @ angular.js:18423
$apply @ angular.js:18523
(anonymous) @ angular.js:27346
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
angular.js:14700 {message: "Failed to create external snaphost"}
(anonymous) @ angular.js:14700
(anonymous) @ angular.js:11142
(anonymous) @ angular.js:20443
h @ angular.js:6362
(anonymous) @ angular.js:6642
setTimeout (async)
i.defer @ angular.js:6640
a @ angular.js:20438
(anonymous) @ backend_srv.ts:131
(anonymous) @ angular.js:17051
(anonymous) @ angular.js:17095
$digest @ angular.js:18232
$apply @ angular.js:18531
(anonymous) @ angular.js:18832
h @ angular.js:6362
(anonymous) @ angular.js:6642
setTimeout (async)
i.defer @ angular.js:6640
$applyAsync @ angular.js:18831
(anonymous) @ angular.js:12544
w @ angular.js:12785
y.onload @ angular.js:12702
load (async)
(anonymous) @ angular.js:12685
(anonymous) @ angular.js:12492
(anonymous) @ angular.js:12244
(anonymous) @ angular.js:17051
(anonymous) @ angular.js:17095
$digest @ angular.js:18232
$apply @ angular.js:18531
(anonymous) @ angular.js:20448
h @ angular.js:6362
(anonymous) @ angular.js:6642
setTimeout (async)
i.defer @ angular.js:6640
a @ angular.js:20438
e.createSnapshot @ AdHocFiltersCtrl.ts:87
fn @ VM131:4
i @ angular.js:27341
$eval @ angular.js:18423
$apply @ angular.js:18523
(anonymous) @ angular.js:27346
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
angular.js:14700 Possibly unhandled rejection: {"message":"Failed to create external snaphost"}

**Environment**:

Grafana v6.1.0-beta1 (944e526)
CentOS Linux release 7.6.1810 (Core)
Windows 7 on Chrome 73.0.3683.86 (64 bits)

- Grafana plugins:
Alert List
Annotation Panel
Azure Monitor
CloudWatch
Dashboard list
Datatable Panel
Diagram
Elasticsearch
Gauge
Getting Started
Graph
Graphite
Heatmap
InfluxDB
Loki
MetaQueries
Microsoft SQL Server
MySQL
Network Map
OpenTSDB
PNP
PRTG
Pie Chart
Plotly
Plugin list
PostgreSQL
Prometheus
Radar Graph
SimpleJson
Singlestat
Stackdriver
Table
TestData DB
Text
WindRose

Thank you!

LB

**Comment by torkelo** [comment]
Strange, unable to replace this.

**Comment by lbsou** [comment]
Can I do some more debug to help?

**Comment by lbsou** [comment]
Bump!

**Comment by archspangler** [comment]
We have the same issue.   We are running Grafana v6.1.3 (9504db8).

**Comment by marefr** [comment]
Works perfectly fine for me. Just took a snapshot of https://play.grafana.org/d/000000003/big-dashboard?orgId=1 with timeout 30 seconds and published it to snapshot.raintank.io. Also tried from latest master and that works as well. 

Maybe you're trying to snapshot a dashboard that contains a certain panel plugin that's not installed on snapshot.raintank.io?

**Comment by lbsou** [comment]
Hi,

I just tried to create a snapshot to raintank with two simple Graph. Before I tried, I deleted all plugins and restarted the service.

SNAPSHOT NAME : TEST
EXPIRE : 1H
TIMEOUT (seconds) : 30

Tested with : Grafana v6.1.3 (9504db8) and Grafana v6.1.6 (cf9cb45)

Here is the JSON of the dashboard :

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 2,
  "id": 86,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": true,
      "dashLength": 10,
      "dashes": false,
      "datasource": "RTR",
      "fill": 5,
      "gridPos": {
        "h": 8,
        "w": 22,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "legend": {
        "alignAsTable": true,
        "avg": true,
        "current": true,
        "max": true,
        "min": true,
        "rightSide": false,
        "show": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 2,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {
          "alias": "ECART",
          "color": "#FADE2A"
        },
        {
          "alias": "ECART",
          "color": "#FADE2A"
        }
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "format": "time_series",
          "group": [],
          "metricColumn": "none",
          "rawQuery": false,
          "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  ECART\nFROM SYSLOG_STATS\nWHERE\n  $__unixEpochFilter(TIMESTAMP)\nORDER BY TIMESTAMP",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "ECART"
                ],
                "type": "column"
              }
            ]
          ],
          "table": "SYSLOG_STATS",
          "timeColumn": "TIMESTAMP",
          "timeColumnType": "int",
          "where": [
            {
              "name": "$__unixEpochFilter",
              "params": [],
              "type": "macro"
            }
          ]
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transparent": true,
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": "0",
          "show": true
        },
        {
          "decimals": null,
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": "0",
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "aliasColors": {},
      "bars": true,
      "dashLength": 10,
      "dashes": false,
      "datasource": "RTR",
      "fill": 5,
      "gridPos": {
        "h": 9,
        "w": 22,
        "x": 0,
        "y": 8
      },
      "id": 2,
      "legend": {
        "alignAsTable": true,
        "avg": true,
        "current": true,
        "max": true,
        "min": true,
        "rightSide": false,
        "show": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 2,
      "links": [],
      "nullPointMode": "connected",
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {
          "alias": "EPS",
          "color": "#FADE2A"
        }
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "format": "time_series",
          "group": [],
          "metricColumn": "none",
          "rawQuery": false,
          "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  EPS AS \"EPS\"\nFROM SYSLOG_STATS\nORDER BY TIMESTAMP",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "EPS"
                ],
                "type": "column"
              },
              {
                "params": [
                  "EPS"
                ],
                "type": "alias"
              }
            ]
          ],
          "table": "SYSLOG_STATS",
          "timeColumn": "TIMESTAMP",
          "timeColumnType": "varchar",
          "where": []
        }
      ],
      "thresholds": [
        {
          "colorMode": "ok",
          "fill": false,
          "line": true,
          "op": "gt",
          "value": 40000,
          "yaxis": "left"
        }
      ],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "EPS",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transparent": true,
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "5s",
  "schemaVersion": 18,
  "style": "dark",
  "tags": [
    "INFRA"
  ],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-2d",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "SYSLOG",
  "uid": "3-g784RZk",
  "version": 23
}

**Comment by archspangler** [comment]
Are there any proxy configurations within grafana that is necessary?  We have to proxy our traffic to get to the internet.   

This is the only plugin that I have..  

/var/lib/grafana/plugins/praj-ams-datasource

**Comment by lbsou** [comment]
Hi,

Just did some more testing.

I installed version 5.4.4 on another server with a restoration of the database before migration to 6.x (the same database of the Grafana instance wich is problematic)

I upgraded to every Grafana release to 6.1.6 without problem. Snapshot worked at every version.

Then, I restored the current database (6.1.6) and it is working too.

It seems the issue is related to the environement...

I tried to remove the Grafana package on the server wich is problematic, delete /var/lib/grafana/ then reinstall it but I got the same error.

t=2019-05-01T15:30:34-0400 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=xx method=POST path=/api/snapshots status=500 remote_addr=xx time_ms=230 size=48 referer="https://xx:3000/d/zmorUIoiz/bw_orion?orgId=1"
t=2019-05-01T15:31:12-0400 lvl=eror msg="Failed to create external snaphost" logger=context userId=2 orgId=1 uname=maayas01 error="Post https://snapshots-origin.raintank.io/api/snapshots: EOF"

Any ideas?

**Comment by lbsou** [comment]
Forgot to restore the grafana.ini and provisionning stuff. Just tested it and got the same problem.

**Comment by lbsou** [comment]
Got it!

Just add the following int /etc/sysconfig/grafana-server : 

http_proxy=http://proxyadd:8080
https_proxy=http://proxyadd:8080

Then restart the service. You can check that the variable are there in the Grafana environment by getting the PID with ps aux | grep grafana and then using the pid to get the content of the environ

cat /proc/<pid>/environ

Have a great day!

**Comment by archspangler** [comment]
I tried your suggestion and I am still have zero luck with publishing the dashboard.  I am not seeing the proxy stuff in the pid environment either..   I did restart grafana-server after maching the changes to /etc/sysconfig/grafana-server.

# cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.10 (Santiago)

# grep proxy /etc/sysconfig/grafana-server
http_proxy=http://proxy-web.xxx.com:80
https_proxy=http://proxy-web.xxx.com:80
no_proxy=.xxx.com,xxx.com,localhost,127.0.0.1

# ps -ef| grep grafana
grafana   3821     1  0 09:45 ?        00:00:00 /usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini --packaging=rpm cfg:default.paths.provisioning=/etc/grafana/provisioning cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins

# cat /proc/3821/environ
SHELL=/bin/shTERM=linuxUSER=grafanaPATH=/sbin:/usr/sbin:/bin:/usr/bin_=/usr/bin/nohupPWD=/usr/share/grafanaLANG=en_US.UTF-8HOME=/usr/share/grafanaSHLVL=3LOGNAME=grafana

Archie

**Comment by lbsou** [comment]
You can try to put "export" before the variable declaration :

export http_proxy=http://proxy-web.xxx.com:80
export https_proxy=http://proxy-web.xxx.com:80
export no_proxy=.xxx.com,xxx.com,localhost,127.0.0.1

**Comment by archspangler** [comment]
Excellent...

I see the proxy information in the pid environment now..

# cat /proc/17616/environ
SHELL=/bin/shTERM=linuxUSER=grafanahttp_proxy=http://proxy-web.xxx.com:80PATH=/sbin:/usr/sbin:/bin:/usr/bin_=/usr/bin/nohupPWD=/usr/share/grafanaLANG=en_US.UTF-8https_proxy=http://proxy-web.xxx.com:80HOME=/usr/share/grafanaSHLVL=3no_proxy=.xxx.com,xxx.com,localhost,127.0.0.1LOGNAME=grafana

Furthermore, I can now publish successful without the error.

Thank you for you assistance!

-archie

**Comment by lbsou** [comment]
My pleasure @archspangler, thanks for pointing out the proxy ;)

The issue is resolve, I will close it.
