### ISSUE TITLE
RFC: Enable query export from Explore to Dashboard

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#16325]
**What would you like to be added**:

As an Explore user I want to be able to save my query to a dashboard.

**Design document open for comments:**
https://docs.google.com/document/d/1s8GWsFyA2h1kDis6VlzCLbLZ6Yf4qWEkTV1PGQazSeA/edit?usp=sharing

**Comment by pikrzysztof** [comment]
Are there any updates on this?

**Comment by aocenas** [comment]
@kay I assume you already implemented and we can close this right?

**Comment by aocenas** [comment]
This is already implemented https://grafana.com/docs/grafana/latest/features/explore/#navigating-between-explore-and-a-dashboard
