### ISSUE TITLE
Cloudwatch custom namespace multi-option query variable not removing {}

### ISSUE THREAD

**Issue by lukerosser** [grafana/grafana#16324]
**What happened**:

When using a query variable to pass data through to a custom namespace query the surrounding {} aren't being removed/split. This stops any data being returned as it's searching for `{value}` instead of `value`

**What you expected to happen**:

Multi-option variable separated into the query as it is when using the default namespace.

Using multi-option variables on AWS/EC2 namespace and passing through multiple instance IDs these are separated and graphed individually. This doesn't happen on custom namespace metrics with multiple dimensions.

**How to reproduce it (as minimally and precisely as possible)**:

Set a variable on the dashboard using a query, for example:

`ec2_instance_attribute(eu-west-1, InstanceId, { "tag:Name": [ "tag" ] })`

Select more than one of the resulting instances.

Configure a graph to use a custom cloudwatch namespace and pass through the relevant dimensions including the instances. The instances are passed through as a single object (e.g. {i-03e3f38db5dd11e81,i-04c6a3d0accec1350}) instead of being separated and graphed individually as they would be when using a standard Cloudwatch namespace.

**Environment**:
- Grafana version: v6.0.2
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Debian 9

**Comment by lukerosser** [comment]
More information:

If I enable multi-value on a variable and only select a single instance it still returns `{instance-id}` and fails to display data. If I disable multi-value and select a single instance it displays fine.

However, enabling the 'All' option has the same problem with or without multi-value enabled which prevents displaying multiple instances/metrics on a single graph through a custom namespace.

**Comment by lukerosser** [comment]
I've tested this further. The problem seems to be with ordering of dimensions in the configuration.

My example graph has four dimensions: InstanceID, ImageId, InstanceType and AutoScalingGroup. InstanceID is the only multi-value option.

If I re-order the dimensions when configuring the graph so that InstanceID is first in the list then the data shows correctly, splitting up the multi-value variable. Any other order and the data doesn't show. Unfortunately this isn't a workaround as reloading the dashboard forces the dimensions back into alphabetical order.

**Comment by marefr** [comment]
@mtanda this sounds more like a bug than a feature request don't you think?

**Comment by mtanda** [comment]
@marefr I believe https://github.com/grafana/grafana/pull/16405 will fix the issue.
