### ISSUE TITLE
generic_oauth error  about email

### ISSUE THREAD

**Issue by carsonlm** [grafana/grafana#16339]
**What happened**:
    OAuth2 login
error log ：   "Login provider didn't return an email address"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
our own OAuth server，and we defined [ apiUrl+"/emails" ]  api  in the Oauth server
But does not carry an access_token when accessing the API
Whether additional configuration is required ？？

 [auth.generic_oauth]  ：
enabled = true
name = OAuth
allow_sign_up = false
client_id = ntHXpshSv1fsFB8kwXXXX
client_secret = iM5mZeiU10CipS0Hph9XXXXX
scopes = super
auth_url = http://XXXX:7000/oauth2.0/authorize
token_url = http://XXXX:7000/oauth2.0/token
api_url = http://XXXXX:7000/api/users/getInfo
send_client_credentials_via_post = true

--------------grafana\pkg\login\social\generic_oauth.go-------------------Source code

func (s *SocialGenericOAuth) FetchPrivateEmail(client *http.Client) (string, error) {

	response, err := HttpGet(client, fmt.Sprintf(s.apiUrl+"/emails"))

**Environment**:  Windows
- Grafana version: 6.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
What payload is returned in token when authenticating? Please [enable debug logging](http://docs.grafana.org/installation/configuration/#level) and include grafana server log here (remove any sensitive information).

**Comment by carsonlm** [comment]
The returned information shows no email, but we defined [apiUrl+"/emails"] API in the Oauth server like GitHub

**Comment by marefr** [comment]
Closing this due to lack of response
