### ISSUE TITLE
在同一幅图中显示不同时间值的比较

### ISSUE THREAD

**Issue by lengrongfu** [grafana/grafana#16332]
1、都需要在同一幅图中。
2、同一个查询条件，另一条线需要显示昨天同一时刻的数据。

**Comment by xbsura** [comment]
emmm...

why close with no any comment?

**Comment by gpBlockchain** [comment]
Duplicate a dataset and then use an `offset` to achieve the goal of comparing different time values.
#### example
<img width="1262" alt="image" src="https://github.com/grafana/grafana/assets/32102187/7b7bfbdf-ee13-4716-b3c4-45fbcd4d61e9">
