### ISSUE TITLE
Embed Panel broken after upgrade to 6.0.2

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#16330]
**What happened**:
After upgrade to Grafana 6.0.2 sharing graphs as *Embed Panel* stop working (it was working on 5.4.3). 
the Embed Panel feature generates iFrame codes that can be easily used in other applications. After upgrading to 6.0.2 the links in the iframe show only the login-page (even after successful login).

**What you expected to happen**:
I expected the iFrame to present the graph after successful login.

**How to reproduce it (as minimally and precisely as possible)**:
* in Grafana 6.0.2, share a panel with Embed Panel feature.
* copy-paste the iframe code to some html file 
* try to run / access the html file
* see that the html file only show the login page inside the iframe

**Anything else we need to know?**:
* setting _anonymous access_ , as suggested in the documentation, does not work as well.
  - the login page is there and the log have this line : _"Anonymous access organization error: 'Main Org.': Organization not found"_

* the workaround i found to solve this, is by disabling the CSRF protection (added in 6.x).
  - setting `cookie_samesite = none` seems to workaround the problem (i use this grafana instance in our internal lab, so i can disable CSRF)

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: Prometheus
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Win 10, Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
yes, you need to disable cookie_samesite to allow browsers to send cookies for iframed domains that do no match the outer domain.

> setting anonymous access , as suggested in the documentation, does not work as well.

This should work with cookie_samsite enabled, make sure the org you specified for anonymous access in the ini file matches the name of the org you want to use. Looking at the error it seems you did not update the org name to use for anonymous access

**Comment by yarix** [comment]
thanks @torkelo 
please check the PR. it modifies the documentation (for faster troubleshooting).
