### ISSUE TITLE
Want to filter "OK" Alert from alerting. 

### ISSUE THREAD

**Issue by suresh447** [grafana/grafana#16338]
**What happened**: I am receiving OK and "No Data" Alerts from grafana. i want to filter these alerts

**What you expected to happen**: I want to filter unwanted alerts

**Environment**: 
- Grafana version: 5.4.2
- Data source type & version: Elasticsearch and Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows and Chrome
- Grafana plugins: Worldping
- Others:

**Comment by torkelo** [comment]
check Disable Resolve Message on the notification channel
