### ISSUE TITLE
Qeury field in "Variables" settings not available for editing

### ISSUE THREAD

**Issue by cyplenochek** [grafana/grafana#16347]
**What happened**:
After upgrade from Grafana 5.3. to Grafana v6.1.0-beta1 the Query type variables become not available for editing. 

**How to reproduce it (as minimally and precisely as possible)**:
1) On the Dashboard view click on "Dashboard settings" on the top of the page
2) Chose the "Variables" section
3) Clock on "New" 
4) Fill the fields Name and Label.
5) Choose the type Query from drop-down menu 
6) Choose Data source InflxDB
7) In the field "Query" try to type - Nothing appears. 

**Anything else we need to know?**:
The same behaviour is I try t modify existing query type variables

**What you expected to happen**:

at the point 7) I wish be able to see my taping and modify the query for Variable

**Environment**:
- Grafana version:

- Data source type & version:
Grafana v6.1.0-beta1 (944e526
InfluxDB
- OS Grafana is installed on:
CentOS 7
- User OS & Browser:
Windows, Chrome

**Comment by torkelo** [comment]
This is fixed in latest nightly and will be fixed in 6.1 stable (released today or tomorrow).

#16299
