### ISSUE TITLE
Regressions on PNG rendering

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#16345]
**What happened**:

6.1.0-7dced5e3pre

![insflowv2-6](https://user-images.githubusercontent.com/291750/55398140-159b0d00-5548-11e9-9866-5058c7dc7e24.png)

Title not centered, black margin

**What you expected to happen**:

6.0.0

![insflowv2-6 (1)](https://user-images.githubusercontent.com/291750/55398152-1af85780-5548-11e9-9f27-e14e915f8cd6.png)

**How to reproduce it (as minimally and precisely as possible)**:

Render a graph panel with latest nightly

**Anything else we need to know?**:

**Environment**:
- Grafana version: master 6.1.0-7dced5e3pre

**Comment by daniellee** [comment]
Thanks @roidelapluie for finding and reporting this.
