### ISSUE TITLE
Azure AD Integration not accepting grant consent

### ISSUE THREAD

**Issue by cbbba18** [grafana/grafana#16353]
**What happened**:
When logging in with Azure AD, AD is saying that Grafana app registration needs permissions granted. Our Azure admin said that consent has been granted, but Grafana does not recognize it.
Error:
An administrator has set a policy that prevents you from granting Grafana the permissions it is requesting. Contact an administrator who can grant permissions to this application on your behalf.

**What you expected to happen**:
Login successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

**Comment by torkelo** [comment]
It's a bit tricky to know if this is a bug or not. We have no other reports of Azure AD not working, so it's likely a config issue. 

Please give is more info you think this is a bug, full settings used & logs etc.

http://docs.grafana.org/auth/generic-oauth/#set-up-oauth2-with-azure-active-directory

**Comment by dash042** [comment]
I currently have a similar issue - my accounts are working (after I consented as a user).
But my colleagues can not login because a "admin consent" is required - even though it is most definitely not requited.
