### ISSUE TITLE
Graph Tooltip missing series name randomly for some series

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#16359]
![image](https://user-images.githubusercontent.com/444037/55467544-71719e80-55f9-11e9-9ae7-529dc1ce9406.png)

This is build Grafana v6.1.0-pre (5aea77f)

**Comment by tomwilkie** [comment]
It intermittently comes and goes as you move the mouse around.  IIRC its the "bold" series thats missing.  You can repro on this dashboard: https://admin-ops-tools1.grafana.net/grafana/d/592b1d6e7d5e37707fea5b0aba0c33ca/cortex-reads?orgId=1&var-datasource=ops-tools1&var-cluster=ops-tools1&var-namespace=cortex-ops

Browser is Chrome Version 72.0.3626.119 (Official Build) (64-bit) on Mac.

**Comment by marefr** [comment]
Can reproduce on that dashboard, but not locally using Grafana test datasource. Guessing this is prometheus related, but not sure.

**Comment by lukasertl** [comment]
Same thing happens with InfluxDB datasource.
