### ISSUE TITLE
"World Ping" plugin service is not able discover our application end-points

### ISSUE THREAD

**Issue by suresh447** [grafana/grafana#16368]
**What happened**: World Ping plugin is not able discover our application end-points which are publicly accessible. It is throwing the below error

![image](https://user-images.githubusercontent.com/33586664/55491805-c6aeaf80-55fb-11e9-8b07-ab4098b25999.png)

**What you expected to happen**: World Ping has to discover our application end points 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Elasticsearch & Prometheus
- OS Grafana is installed on: Ubuntu 16
- User OS & Browser: Windows & chrome
- Grafana plugins: world Ping
- Others:

**Comment by torkelo** [comment]
Strange. Are they publicly available?

**Comment by suresh447** [comment]
Yes,They are publicly available.

**Comment by torkelo** [comment]
Closing this, if you continue to have issues, please contact worldping support at support@grafana.com
