### ISSUE TITLE
Grafana uses same internal variables as plugin Azure Monitor

### ISSUE THREAD

**Issue by rerime** [grafana/grafana#16365]
Grafana has two built in time range variables in $__from and $__to. They are currently always interpolated as epoch milliseconds. These variables are only available in Grafana v6.0 and above.

http://docs.grafana.org/features/datasources/azuremonitor/#azure-log-analytics-builtin-variables

**Comment by torkelo** [comment]
that is unfortunate, we need to rename those azure monitor macros I think.

**Comment by afscrome** [comment]
Are there any workarounds for this - any alternative variable names that can be used?

Best work around I've come up with for now is to define a function to convert to Azure datetime formats, but it's ugly having to put this in every location, and all the queries may well break depending on how this is fixed going forward.

```
let fromGrafanaTime = (t:long){ 
   datetime(1970-01-01) + t * 1ms
};
...
    | make-series value=dcountif(instance, isBroken) default=0
        on timestamp from fromGrafanaTime($__from) to fromGrafanaTime($__to) step $interval
        by endpoint
```
Then wrapping calls to `$__from` and `$__to` with this function.

**Comment by rerime** [comment]
Temp fix
```
todatetime($__from*10000+621355968000000000) to todatetime($__to*10000+621355968000000000)
```
