### ISSUE TITLE
Editing query Graphite javascript error

### ISSUE THREAD

**Issue by straccio** [grafana/grafana#16367]
**What happened**: When adding or editing a function the javascript console give me an error and the query doesn't update. 
Here the error
```
TypeError: e.replace is not a function
    at e.replace (template_srv.ts:284)
    at graphite_query.ts:223
    at gfunc.ts:1036
    at Qt (lodash.js:639)
    at Function.Ja [as map] (lodash.js:9555)
    at e.render (gfunc.ts:1034)
    at graphite_query.ts:222
    at tn (lodash.js:683)
    at Function.hr.reduce (lodash.js:9683)
    at e.updateModelTarget (graphite_query.ts:230)
```

**What you expected to happen**: Update the query

**How to reproduce it (as minimally and precisely as possible)**: Simple edit any existing graphite query

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: graphite
- OS Grafana is installed on: docker
- User OS & Browser: Mac Chrome/Safari
- Grafana plugins:
farski-blendstat-panel @ 1.0.1
grafana-clock-panel @ 1.0.2
grafana-piechart-panel @ 1.3.6
mxswat-separator-panel @ 1.0.0
snuids-trafficlights-panel @ 1.4.2
- Others:

**Comment by torkelo** [comment]
Are you sure you not running 6.1.0-beta1 ? There is a fix for this error in v6.1.0 (stable released today).

**Comment by straccio** [comment]
I have used the docker image grafana:latest
```
$ grafana-cli
NAME:
   Grafana cli

USAGE:
   grafana-cli [global options] command [command options] [arguments...]

VERSION:
   6.1.0

AUTHOR:
   Grafana Project <https://github.com/grafana/grafana>
....
```

**Comment by wziww** [comment]
This happened while doing query to ES datasource and click the button of「 filter for value 」
`version 6.1.0`

**Comment by straccio** [comment]
With graphite that happen only with functions and after the first function.

**Comment by straccio** [comment]
I have a test case.
```
aliasByNode(aliasSub(carbon.agents.*.cpuUsage, 'carbon', 'smit'), 0, 3)
```

In this query i can't add function.

**Comment by straccio** [comment]
@torkelo sorry, you need more details?

**Comment by marefr** [comment]
Confirmed bug. When adding the `aliasByNode(2)` I receive same error as reported:

![image](https://user-images.githubusercontent.com/1668778/55564288-e0352180-56f7-11e9-92da-655d991fc21d.png)

**Comment by straccio** [comment]
Thank you!
