### ISSUE TITLE
Docs: Postgres datasource & pg_prometheus example queries missing

### ISSUE THREAD

**Issue by tamer-hassan** [grafana/grafana#16366]
Towards the end of https://docs.timescale.com/v1.2/tutorials/prometheus-adapter
There exists a few PromQL to SQL adaptation examples.
However, they are very limited, and also the docs of the postgres datasource in grafana doesn't offer any similar examples.

it was a bit of a learning curve while searching through issues reported here on github to find out how to accomplish a simple task such as the below:
![grafana_sql](https://user-images.githubusercontent.com/512891/55484584-093ab100-5629-11e9-94d4-616fcaaa8842.png)

**Comment by tamer-hassan** [comment]
please note, the where expression `value != 'NaN'` was also required to workaround bug in prometheus sometimes filling value column with 'NaN' and apparently Grafana 6.0.1 chokes with "Json Body marshal" error.

**Comment by marefr** [comment]
timescale or pg_prometheus is not maintained by Grafana project. Please request timescale to document this better in their documentation.
