### ISSUE TITLE
Slack Notification channel with different Image ico url

### ISSUE THREAD

**Issue by tatototino** [grafana/grafana#16370]
When a configure two slack notification channel with different with different Icon URL I get only  messages with only one images ico and (no both). I have configured two chart and a notification  channels for each one.

**ow to reproduce it (as minimally and precisely as possible)**:
Send any alarms through both channel and  see in the slack if you get both alarms from the differents charts with differents image ico

image ico url used:

https://openforumevents.co.uk/media/1121/cherwell.png
https://cloud-elements.com/wp-content/uploads/2014/03/zendesk-logo-01.png

**Environment**:
- Grafana version: grafana-6.0.0-1.x86_64
- Data source type & version:  mysql
- OS Grafana is installed on: Centos 7
- User OS & Browser: windows Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Maybe you have specified an icon when creating the slack webhook?

**Comment by tatototino** [comment]
Hi Torkelo,

Thank you for answering.

I use the same slack webhook for both channel notification ( I just modify the ico url) .When I setup both together with ico url setup just one works. If I setup one of them works as well the problem is when setup both of them.

**Comment by tatototino** [comment]
Follow the screenshot showing the behavior:

![bug-grafana](https://user-images.githubusercontent.com/10597278/55883578-f79f5f00-5b7c-11e9-82a6-96b77808d072.png)

If we get cherwel alarm first we can get cherwel logo and we cannot get zendesk logo and vice-versa

**Comment by msoni2805** [comment]
@tatototino 

How have uh configure graph img on slack can provide me the steps
