### ISSUE TITLE
influxdb 0.9 change "order asc" to "order by [key] asc"

### ISSUE THREAD

**Issue by huhongbo** [grafana/grafana#1637]
Influxdb 0.9 has change a lot sql parse
https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md
influxdb 0.9x support still use "order asc",but influxdb will report parse error
order_by_clause = "ORDER BY" sort_fields .

**Comment by torkelo** [comment]
InfluxDB 0.9 support is not yet done, please provide feedback through the issue: #1525
