### ISSUE TITLE
Forcing decimal precision in singlestat panel doesn't work

### ISSUE THREAD

**Issue by paulfantom** [grafana/grafana#16373]
**What happened**:
Singlestat panel stopped rounding number to specified decimal precision.

**What you expected to happen**:
singlestat panel respects specified precision

**How to reproduce it (as minimally and precisely as possible)**:
Create a singlestat panel and change decimal precision from "auto" to some number.

**Anything else we need to know?**:

What I got:
![wrong](https://user-images.githubusercontent.com/3531758/55511706-8bdf6280-5661-11e9-886b-8e9f9eb98852.png)

What happens after setting precision to auto:
![okayish](https://user-images.githubusercontent.com/3531758/55511737-97cb2480-5661-11e9-8faf-5833e5e4e294.png)

In previous Grafana version it was showing correctly rounded value.

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Prometheus (version 2.8.1)
- OS Grafana is installed on: official docker container deployed on fedora 29 server
- User OS & Browser: Fedora 29, Chrome 73.0.3683.86
- Grafana plugins: same as in official docker image, nothing added
- Others: Tested on following dashboard: https://grafana.com/dashboards/1860

**Comment by thomas-netric** [comment]
I got the same issue for data source: mysql

**Comment by djg2002** [comment]
We amended the offending panels to '0' decimal places but they now show 2 decimal places.  If we set any other (positive) integer it always shows 9 decimal places.

* Grafana version: 6.1.0  (upgraded from 6.0.2)
* Datasource: Elasticsearch 6.3.1 (configured as 6.0+ in datasource)
* OS Grafana is installed on: official docker container, Debian
* OS / Browser: Windows 10, Linux Ubuntu, MacOS / Chrome

**Comment by thomas-netric** [comment]
I just upgraded to 6.1.2 and I'm still experiencing the same issues.

**Comment by torkelo** [comment]
Damit I missed part of the fix :(

Opening new PR with the next part of the fix asap.
