### ISSUE TITLE
Value missing when export from panel to csv

### ISSUE THREAD

**Issue by hxu-lift** [grafana/grafana#16371]
**What happened**:
Value missing when export from panel to csv.  As shown in the attached screenshots, values on 03-29 presents in the Grafana panel but is missing in the exported csv file:

<img width="814" alt="Screen Shot 2019-04-03 at 1 45 21 PM" src="https://user-images.githubusercontent.com/45943572/55502004-a857ac80-5619-11e9-9307-000b569b0425.png">
<img width="389" alt="Screen Shot 2019-04-03 at 1 46 45 PM" src="https://user-images.githubusercontent.com/45943572/55502243-2451f480-561a-11e9-9360-0326a008393a.png">

**What you expected to happen**:
I expect the exported csv to match the values shown in the graphical panel.

**How to reproduce it (as minimally and precisely as possible)**:
Create graph panel with postgreSQL database as datasource, select bar chart with stack.
Export data from panel to csv.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.3.2
- Data source type & version: PostgreSQL  
- OS Grafana is installed on: Ubuntu Linux 16.04
- User OS & Browser: MacOS10.14.3 Safari
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
please include the response from the query inspector as well (the raw result of your query), and the whole csv file as well so we can compare.

**Comment by torkelo** [comment]
closing this due to lack of inactivity / more info
