### ISSUE TITLE
Heatmap panel content vanishes if panel is too narrow

### ISSUE THREAD

**Issue by mstud** [grafana/grafana#16378]
**What happened**:
since the update to Grafana 6.1.0, the Heatmap panel does not show data anymore in some of our dashboards where the panel width is really narrow

**What you expected to happen**:
it to show data like it did before

**How to reproduce it (as minimally and precisely as possible)**:
place a heatmap, add some datasource and then change the width of the panel, making it really narrow

**Anything else we need to know?**:
it appears to be a rendering issue, this did not happen before 6.1.0 where the panel rendered just fine even if very narrow

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Graphite 1.1.2
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: Linux, Firefox 65.0.2
- Grafana plugins: none
- Others: -

**Comment by DirtyCajunRice** [comment]
To add on: mine is full width of the screen but "short" not narrow. and it still doesn't render the bar. Just the legend. It also completely ignores visualization settings (the pic of 6.1.0 top left should be bits/s and 1 decimal place)

6.0.2:
https://media.discordapp.net/attachments/517760683916394506/563395618295250947/unknown.png?width=1364&height=101
6.1.0:
https://media.discordapp.net/attachments/517760683916394506/563394700799770634/unknown.png?width=1364&height=261

**Comment by torkelo** [comment]
@alexanderzobnin any ideas?

**Comment by mstud** [comment]
It seems to depend on the number of datapoints that are to be displayed. If it is more than pixels available (or some factor of that), it doesn't render any thing at all anymore.
That's why for @DirtyCajunRice the bar is empty even though it is not really narrow, but he seems to have many data points. Selecting a shorter time window will make the data visible again, because it reduces the number of data points to be drawn.

**Comment by roffe** [comment]
Got the same issue on all my heatmaps after upgrading from 6.0.2

**Comment by roffe** [comment]
it doesn't seem to be related to narrowness though. even if i expand them the heatmaps doesn't show data

**Comment by meersjo** [comment]
Same issue, upgraded from 5.4.2 to 6.2.1. 

I have 4 heatmaps next to each other on the canvas. Displays up to 16 days now, as soon as the timerange becomes 17 days the content doesn't render. Content has 6 datapoints per hour; minimum interval is set to 1h.

On 5.4.2, default timerange was set to 90 days, displayed without problems. I just tested; 2y timerange still displays normally (although there is only 1y of data, so may not be accurate test).

**Comment by meersjo** [comment]
There appears to be a possible calculation error (or a new default?) in the value grouping - for 90d view, on 5.4.2, the scale is calculated to 144 max (at 6 datapoints/hour that makes 24h per display unit); on 6.2.1 the scale max is only 18.

**Comment by alexanderzobnin** [comment]
@torkelo It's definitely a bug introduced by 57f48f17a0d8d81db7462a4d3d7da843623fd85d
I have to find more careful way to hide cut cards on the left and right sides of heatmap.
