### ISSUE TITLE
v2 alpha: "timeseries data request error" tooltip will stick around if it was displayed when error cleared

### ISSUE THREAD

**Issue by alienth** [grafana/grafana#1638]
If you hover over timeseries error icon, and an autorefreshing graph results in the error going away, the tooltip will hang around despite the icon being gone, like so:

![image](https://cloud.githubusercontent.com/assets/218431/6820768/cc8222fe-d286-11e4-8e6f-cc19e47be25a.png)

**Comment by torkelo** [comment]
InfluxDB 0.9 support is not yet done, please provide feedback through the issue: #1525

**Comment by torkelo** [comment]
sorry, commented on wrong issue

**Comment by torkelo** [comment]
Would love a PR that solved this, I have solved most of these issues, but this one is too tricky, and should be very uncommon (basically the only way to solve it is to constantly chech for left over tooltips)
