### ISSUE TITLE
Auto Bucket points on a line graph for different time ranges

### ISSUE THREAD

**Issue by bp32795** [grafana/grafana#16388]
**What would you like to be added**:

Some form of auto bucket or manual bucket for line graphs with lots of data points that can be activated when you zoom out the time range (i.e. when you go from 1hr to 24hrs). 

**Why is this needed**:

I noticed some of my data points do not get displayed depending on the time range. For example, I have a 15s scrape in Prometheus that shows every point when I am at the last 1hr view, but when I switch to the last 24hrs view, it shows points at every minute, but it does not account for the points at every 15s. That means, if I have a spike at *:*:45s, I do not see that point on the graph, but instead see the points at :00 and 1:00. I have looked around, and I do not see any other way to work around this problem, outside of setting the min step and time vector for my query, but I would really like to be able to have that done automatically at all time ranges so I do not visually lose data. [This gif shows the problem.](https://i.imgur.com/3XFkocW.gif)

*Also, this is my first type of post like this ever, so please let me know if anything is inappropriate or if something needs to be clearer. Thanks!

**Comment by torkelo** [comment]
This is a simple prometheus query scenario, you have to select the correct function & aggregation. 

Try max_over_time(query[$__interval])

$__interval will be time range dependant and increase when you zoom out, not go lower than scrape interval

**Comment by bp32795** [comment]
Wow, that sounds like exactly what I want. Don't know how I missed that. I will play around with it. Thanks!
