### ISSUE TITLE
Default "Min Step" value no longer being rendered in query builder

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#16389]
Here's the behavior from v5.4 on the prometheus query builder. If you don't override the value, the input is filled with the min step that grafana has determined based of the time range.

![Screen Shot 2019-04-04 at 1 04 21 PM](https://user-images.githubusercontent.com/3194832/55574410-5591f980-56da-11e9-9f34-7b10eef5a852.png)

In v6 and master, this default value is no longer displayed, yet it is still used under the hood when the data request is made.
![Screen Shot 2019-04-04 at 1 07 54 PM](https://user-images.githubusercontent.com/3194832/55574566-b1f51900-56da-11e9-9788-578c8dbd1802.png)

**Comment by torkelo** [comment]
With the refactoring and separation of the editor UI from the actual panel, this information is not as easily accessible anymore. So will be a bit tricky to get this info as it's calculated on demand in the query execution phase.

**Comment by seanlaff** [comment]
Still think this is a useful ux since it gives the user an idea of where the step currently is set before they tweak it further. Does the new architecture preclude reviving the 5.4 behavior?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
