### ISSUE TITLE
Unable to enable TestData DB plugin

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#16386]
**What happened**:

I want to enable the TestData DB plugin. I go to the plugin settings page to enable it. The Enable button is not visible.

![screenshot 2019-04-04 1153](https://user-images.githubusercontent.com/3270755/55570314-2cb93680-56d1-11e9-9812-095e0bd969ce.png)

**What you expected to happen**: 

According to the docs, the TestData DB plugin is built-in Grafana but must be enabled.
http://docs.grafana.org/features/datasources/testdata/

**How to reproduce it (as minimally and precisely as possible)**:

1. `docker run -p 3000:3000 grafana/grafana:6.0.2`
2. Navigate to http://localhost:3000/plugins/testdata/edit

**Anything else we need to know?**:

n/a

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: n/a
- OS Grafana is installed on: Docker
- User OS & Browser: Fedora 29, Firefox 66.0
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
It's just a normal datasource now, goto datasources -> add datasource
