### ISSUE TITLE
Sending Unwanted Data as Alerts in grafana

### ISSUE THREAD

**Issue by suresh447** [grafana/grafana#16399]
**What happened**: I am using prometheus to scrap the metrics of AKS cluster and i configured an alert by giving condition if nodes is lessthan 6 it has to send me an alert that nodes unavailable alert. I am using the query below to alert

![image](https://user-images.githubusercontent.com/33586664/55607873-d97fcc00-5742-11e9-8437-a97d91a16660.png)

Alert condtion

![image](https://user-images.githubusercontent.com/33586664/55607935-fcaa7b80-5742-11e9-8ffa-35ead5829a88.png)

But i am getting alert notification like below
![image](https://user-images.githubusercontent.com/33586664/55608004-282d6600-5743-11e9-8ae9-da1f66c0deeb.png)

After getting this alert i check nodes status in aks cluster but they are running fine

**What you expected to happen**:
I want to get alert if the condition satisfied and it has to match with nodes running on AKS cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Elasticsearch and Prometheus
- OS Grafana is installed on: Ubuntu 16
- User OS & Browser: Windows 10 and Chrome
- Grafana plugins: Worldping
- Others:

**Comment by marefr** [comment]
What happens when you run the test alert rule in the alert tab? Have you configured prometheus datasource to use Access=Browser?

**Comment by suresh447** [comment]
Hi Marcus,

After running the Alert rule it is showing the below error and yes i
configured prometheus Datasource to use browser access.

[image: image.png]

Please help me in this regard

Thanks
Suresh

**Comment by marefr** [comment]
You need to make sure that Grafana server can connect to your prometheus instance for alerting to work so you should use Access=proxy instead.

**Comment by suresh447** [comment]
But i dont find any Proxy option while adding prometheus datasource. i have
server option if i select server access i am getting http bad request error

[image: image.png]

**Comment by marefr** [comment]
Sorry I meant **Server**. It was renamed from proxy to server a while back. You need to make sure that you can connect to your prometheus from Grafana server. Since you can connect when access=browser you probably have more network access than your grafana server.

**Comment by suresh447** [comment]
Ok but in my architecture grafana server is running on VM in one
subscription and prometheus is running on AKS cluster on another
subscription in Azure.Due to this only connectivity issue is there i think
so.Could you please suggest me if am wrong.

Thanks for your quick response.I really appreciate your help.

**Comment by marefr** [comment]
That's not something Grafana can handle for you. If you want that architecture you must configure it so Grafana can access your prometheus in AKS cluster. Maybe set up a proxy/vpn - I don't know. Or install a grafana isntance in AKS cluster

**Comment by suresh447** [comment]
Thank you so much Marcus.One more thing i want to stop No-Data Alerts from
grafana is there any way to filter No-Data Alerts

**Comment by marefr** [comment]
Change setting of "If no data or all values are null" to keep last state or OK.
