### ISSUE TITLE
switch component should allow optional info-popup

### ISSUE THREAD

**Issue by RangerRick** [grafana/grafana#16392]
**What would you like to be added**:

An optional attribute on the `<gf-form-switch>` directive to give it an `<info-popover>`.

**Why is this needed**:

Currently I needed to do some ugly CSS hacks with `float:right` and manual padding to get things to line up in another bug fix I'm working on.

Example with CSS hacks:

```
<style>
.gf-form-help-icon {
  &--onms-refresh {
    float: right;
    padding-top: .5rem;
    padding-right: 1rem;
  }
}
</style>
<info-popover mode="onms-refresh">
  Pause refresh when you have navigated away from the first
   page of results.
</info-popover>
<gf-form-switch class="gf-form" label-class="width-8" switch-class="max-width-7" label="Pause refresh" checked="editor.panel.pagingPausesRefresh" on-change="editor.render()"></gf-form-switch>
```

![switch with info popover](https://user-images.githubusercontent.com/89252/55579713-e7076880-56e6-11e9-9aee-da476a11d44d.png)

Without the CSS hacks:

```
<info-popover mode="right-normal">
  Pause refresh when you have navigated away from the first
   page of results.
</info-popover>
<gf-form-switch class="gf-form" label-class="width-8" switch-class="max-width-7" label="Pause refresh" checked="editor.panel.pagingPausesRefresh" on-change="editor.render()"></gf-form-switch>
```

![switch with default popover](https://user-images.githubusercontent.com/89252/55579720-e969c280-56e6-11e9-8970-7af210f54eb6.png)

Ideally, there would be an `info-popover=""` argument to the directive that would just place a popover next to the switch.

**Comment by RangerRick** [comment]
Actually, since `<info-popover>` has so many options of its own, can it just be embedded inside the `<gf-form-switch>` instead? Something like:

```
        <gf-form-switch class="gf-form" label-class="width-8" switch-class="max-width-7" label="Pause refresh" checked="editor.panel.pagingPausesRefresh" on-change="editor.render()">
            <info-popover>
                Pause refresh when you have navigated away from the first
                page of results.
            </info-popover>
        </gf-form-switch>
```

I tried doing this, but it doesn't work.  I don't know React enough to figure out how to make it happy.

**Comment by torkelo** [comment]
Use tooltip prop on the directive. 

```
<gf-form-switch class="gf-form" label-class="width-8" switch-class="max-width-7" label="Pause refresh" checked="editor.panel.pagingPausesRefresh" on-change="editor.render()" tooltip="Pause refresh when you have navigated away from the first page of results.">
</gf-form-switch>
```

**Comment by RangerRick** [comment]
Aha!  That's what I get for assuming that would just make hover-text, not an actual icon.  Thanks!
