### ISSUE TITLE
Rendering images does not work

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#16407]
**What happened**:

When Grafana sends an alert it used to send an image of the Graph along with the message.

**What you expected to happen**:

I expected Grafana to render an image of the alerting graph, uploading it to my external storage (Google Cloud bucket) and linking it in the alert message.

**How to reproduce it (as minimally and precisely as possible)**:

I am running 3 (pretty much identical) Kubernetes deployments of Grafana (each stage has one deployment with 3 replicas). All of them can not render images. To reproduce the behaviour I click on a graph's panel title and click "Direct link rendered image" in the popped up modal.

This opens a new tab, which loads for roughly 15 seconds until a "Grafana / Server Error" page appears which says "Rendering failed. Check the Grafana server logs for the detailed error message". 

**Anything else we need to know?**:

The Grafana server error logs:

```
t=2019-04-05T09:24:19+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
t=2019-04-05T09:24:19+0000 lvl=eror msg="Rendering failed." logger=context userId=56 orgId=5 uname=martin.schn@company.com error="signal: killed"
t=2019-04-05T09:24:19+0000 lvl=eror msg="Request Completed" logger=context userId=56 orgId=5 uname=martin.schn@company.com method=GET path=/render/d-solo/0BVsKYrmkk/kafka-minion status=500 remote_addr=redacted time_ms=48501 size=1722 referer=https://grafana.service.prd.company.com/
t=2019-04-05T09:28:36+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
t=2019-04-05T09:28:36+0000 lvl=eror msg="Rendering failed." logger=context userId=56 orgId=5 uname=martin.schn@company.com error="signal: killed"
t=2019-04-05T09:28:36+0000 lvl=eror msg="Request Completed" logger=context userId=56 orgId=5 uname=martin.schn@company.com method=GET path=/render/d-solo/0BVsKYrmkk/kafka-minion status=500 remote_addr=redacted time_ms=34187 size=1722 referer=https://grafana.service.prd.company.com/
```

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Prometheus 2.7.2
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: Mac OS & Google Chrome
- Grafana plugins: vonage-status-panel, grafana-worldmap-panel, grafana-piechart-panel, grafana-kubernetes-app, dbranham-diagram-panel
- Others:

**Comment by marefr** [comment]
Any specific panel type that doesn't work? How much memory have you assigned to your Grafana containers? PhantomJS demands quite a lot of memory.

**Comment by weeco** [comment]
@marefr I just tried a graph, I haven't tried any other graph types. I had each instance configured to 256MB RAM, after your response however I assigned 1Gig RAM. It took quite long (roughly 10s) to render the image, but this time with 1 Gig RAM it actually worked.

Is that a common render time or can I optimize that? Time range was last 3h, with labels every 10s

**Comment by marefr** [comment]
It can take quite some time. Can depend on amount of data points as well.
