### ISSUE TITLE
Make sure dl.grafana.com doesn't incorrectly cache 404's

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#16401]
We have had problems with fastly caching 404's which has lead to some packages being unavailable after releases.

Cache setting should be updated so that it only caches 200 OK responses.

**Comment by xlson** [comment]
Added a cache condition to the fastly configuration so that only 200 ok responses are cached.

**Comment by torkelo** [comment]
:+1:

**Comment by xlson** [comment]
Did the same for packages as well.
