### ISSUE TITLE
heatmap buckets not ordered

### ISSUE THREAD

**Issue by d4n-7** [grafana/grafana#16410]
**What happened**:
Heatmap values are not ordered based on bucket values

**What you expected to happen**:
Heatmap values should be ordered according to bucket values asc

**How to reproduce it (as minimally and precisely as possible)**:
Create a heatmap panel using bucket values as described in http://docs.grafana.org/features/panels/heatmap/

**Anything else we need to know?**:
![](https://raw.githubusercontent.com/d4n-7/Res/master/Screenshot%20from%202019-04-05%2013-38-59.png)

![](https://raw.githubusercontent.com/d4n-7/Res/master/Screenshot%20from%202019-04-05%2013-38-31.png)

Query snapshot:

Element | Value
-- | --
{le="0.2048"} | 9362.722607407433
{le="0.0001"} | 56.286785185185195
{le="0.0512"} | 9040.932118518536
{le="0.1024"} | 9248.02500740743
{le="3.2768"} | 9395.645066666693
{le="5e-05"} | 53.10074074074075
{le="0.0004"} | 56.286785185185195
{le="0.0064"} | 4703.663614814816
{le="0.0016"} | 61.59685925925927
{le="0.0032"} | 782.7049185185177
{le="0.0128"} | 8336.816296296296
{le="0.0256"} | 8841.273333333345
{le="0.8192"} | 9395.645066666693
{le="1.6384"} | 9395.645066666693
{le="+Inf"} | 9395.645066666693
{le="0.0002"} | 56.286785185185195
{le="13.1072"} | 9395.645066666693
{le="26.2144"} | 9395.645066666693
{le="6.5536"} | 9395.645066666693
{le="0.0008"} | 56.286785185185195
{le="0.4096"} | 9387.148948148175

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Prometheus (version 2.7.2)
- OS Grafana is installed on: Ubuntu 18.04.1 LTS
- User OS & Browser: Ubuntu 18.04.2 LTS, Firefox Quantum 66.0.2
- Grafana plugins: original, nothing new
- Others: -

**Comment by torkelo** [comment]
you need to use ``{{le}}`` in Legend format I think so that only the numeric le label value is used
