### ISSUE TITLE
Imported dashboard loses query for variables when unknown data source

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#16428]
**What happened**:
1. Import a dashboard from another instance of grafana that uses a datasource not present
2. Go to the "Settings" of the dashboard
3. Click on "Variables". Observe the query and variable name.
4. Click on the variable. The query is now blank.

**What you expected to happen**:
When I click on the query to change its datasource, it should still be present.

**How to reproduce it (as minimally and precisely as possible)**:
Follow steps 1-4.

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: Influxdb 1.7.4
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS Chrome
- Grafana plugins: None.

**Comment by torkelo** [comment]
thanks for reporting this, we will investigate!

**Comment by hugohaggmark** [comment]
Closing this issue because I can't repro this issue. We can always reopen this issue later if the need arises.

All the best
