### ISSUE TITLE
Display title instead of id for a previously deleted dashboard

### ISSUE THREAD

**Issue by cristizafiu** [grafana/grafana#1642]
When deleting a dasboard a prompt appears telling that it was deleted. Is there any way I can display the dashboard title instead of dashboard id for this prompt?
![dash_delete](https://cloud.githubusercontent.com/assets/11646948/6824150/02a56730-d2f8-11e4-884b-d91e6d3f8249.jpg)

**Comment by torkelo** [comment]
Fixed in Grafana 2.0 (develop branch, beta to be released soon)
Pre beta builds and docs can be found here:
http://docs.grafana.org/v2.0/installation/
http://grafana.org/download/builds
