### ISSUE TITLE
API keys: Support API tokens for users as well (PAT)

### ISSUE THREAD

**Issue by steviecoaster** [grafana/grafana#16424]
**What would you like to be added**:
Some API endpoints require passing username:password as part of the URL to the endpoint. This should be refactored to follow the standard `Bearer $token` method of the other endpoints

Example endpoint requiring basic auth: GET /api/orgs/name/:orgName
 
**Why is this needed**:
Standardize to one method to make working with the API much more reliable and easy to do.

**Comment by torkelo** [comment]
Changed name to be about adding support for user level api keys

**Comment by Tepew** [comment]
Without this functional we can`t disable users via API.

**Comment by eleijonmarck** [comment]
adding this to our service account implementation where we will be able to assign apikeys to service accounts

**Comment by eleijonmarck** [comment]
This should not be closed, we have discussion on how this should work - https://github.com/grafana/grafana-enterprise/discussions/2655

**Comment by eleijonmarck** [comment]
Linked this to our internal discussion about how to implement PAT
