### ISSUE TITLE
Microsoft Teams Android App - Messages empty

### ISSUE THREAD

**Issue by darox** [grafana/grafana#16434]
When grafana sends alerts towards Microsoft Teams, the messages are empty on the Android App. 

Messages are displayed correctly in the Andorid App. 

Setup Microsoft Teams for Grafana and generate an alert towards it. 

**Anything else we need to know?**:

On the Desktop client, messages are displayed correctly. I don't know if it's a Microsoft or Grafana issue. 

**Environment**:
- Grafana version: v6.0.0 (commit: 34a9a62
- Data source type & version: Influxdb
- OS Grafana is installed on: centos-release-7-6.1810.2.el7.centos.x86_64 / docker 18.09.2
- User OS & Browser: - 
- Grafana plugins: - 
- Others: -

**Comment by mmrazik** [comment]
I tried with Grafana 6.3.3 and latest Teams Desktop/Android app but could not repro. Both Android and Desktop (Windows) render the message the same way.
Given it was available on the desktop app, it is IMHO quite unlikely the problem is on Grafana side.

**Comment by darox** [comment]
I can confirm, that it's now ok.

**Comment by darox** [comment]
It's working
