### ISSUE TITLE
Color resets in Graph

### ISSUE THREAD

**Issue by aratnikovmxmgt** [grafana/grafana#16437]
**What happened**: Color resets in Graph with multiple queries. Every metric use last chosen color.

**What you expected to happen**: Each metric keep their color in Graph.

**How to reproduce it (as minimally and precisely as possible)**: Add new graph with several (3 for me) queries. After that try to change color for each metric. Save dashboard and open it again - you will see, that all metric have the same color.
Link to video recording: https://ufile.io/zst3h

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.1.0 (commit: 03346b6) and Grafana v6.1.1 (commit: eff01d2)
- Data source type & version: Zabbix 3.10.1
- OS Grafana is installed on: Debian 9.8
- User OS & Browser: Windows 10 Mozilla Firefox 66.0.2 (x86)
- Grafana plugins: Zabbix, PRTG

**Comment by torkelo** [comment]
Unable to replicate, either you have a style override regex rule that overrides the color for all series (check graph options). Or it's an issue in Zabbix overriding the color (not sure that is possible). 

Can you check your graph options and if you cannot find a style override, please paste the panel json here.

**Comment by aratnikovmxmgt** [comment]
Here it is:
`{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 10,
  "links": [],
  "panels": [
    {
      "aliasColors": {
        "Packing duration": "blue"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "fill": 3,
      "gridPos": {
        "h": 8,
        "w": 8,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "legend": {
        "avg": false,
        "current": true,
        "max": true,
        "min": false,
        "show": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 2,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "application": {
            "filter": ""
          },
          "functions": [],
          "group": {
            "filter": "WMS"
          },
          "host": {
            "filter": "vsrv8"
          },
          "item": {
            "filter": "Packing duration"
          },
          "mode": 0,
          "options": {
            "showDisabledItems": false,
            "skipEmptyValues": false
          },
          "refId": "A",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        },
        {
          "application": {
            "filter": ""
          },
          "functions": [],
          "group": {
            "filter": "WMS"
          },
          "host": {
            "filter": "vsrv9"
          },
          "item": {
            "filter": "Packing duration"
          },
          "mode": 0,
          "options": {
            "showDisabledItems": false,
            "skipEmptyValues": false
          },
          "refId": "B",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        },
        {
          "application": {
            "filter": ""
          },
          "functions": [],
          "group": {
            "filter": "WMS"
          },
          "host": {
            "filter": "emx-wmsbeta"
          },
          "item": {
            "filter": "Packing duration"
          },
          "mode": 0,
          "options": {
            "showDisabledItems": false,
            "skipEmptyValues": false
          },
          "refId": "C",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "fill": true,
          "line": true,
          "op": "gt",
          "value": 1500,
          "yaxis": "left"
        }
      ],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Packing Duration",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transparent": true,
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "30s",
  "schemaVersion": 18,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "WMS SLA",
  "uid": "qDiufggWk",
  "version": 10
}`

**Comment by aratnikovmxmgt** [comment]
Everything work well - it was my problem. 
Thanks!

**Comment by aratnikovmxmgt** [comment]
Nope, still problem:
I have 3 different host: (vsrv8, vsrv9, emx-wmsbeta), but Item's name is the same (Packing duration).
Grafana thinks that they are equal and make only one aliasColors:
```
      "aliasColors": {
        "Packing duration": "blue"
									 
									   
      },
```

**Comment by torkelo** [comment]
If series names are the same you cannot assign different colora
