### ISSUE TITLE
Same values for X axis are not stacked on top of each other

### ISSUE THREAD

**Issue by pkaramol** [grafana/grafana#16436]
**What happened**:
Same values for X-axis are being displayed seperately

**What you expected to happen**:
Same values for X-axis should be stacked on top of each other

**How to reproduce it (as minimally and precisely as possible)**:
Create a mysql graph diagram with either two distinct mysql queries resulting with same X-axis values (using `series`) __or__ a composite (using for example `inner join`) single query with same effect.

The images below show the results when using both the above approaches

![image](https://user-images.githubusercontent.com/2778429/55702574-b1f95f80-59df-11e9-8dc0-bdcf138207eb.png)

![image](https://user-images.githubusercontent.com/2778429/55702641-e2d99480-59df-11e9-9a08-8317b1307c6d.png)

In both cases the `X-axis` values are being duplicated.

**Environment**:
- Grafana version: `Grafana v5.4.3 (6539180)`
- Data source type & version: `mysql 5.7`
- OS Grafana is installed on: running on docker
- User OS & Browser: Ubuntu 18.04.02 LTS / Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The histogram view will show each series as it's own bar, no matter if the series is named the same. 

Think your looking for this feature request: https://github.com/grafana/grafana/issues/7158 

Sadly the graph panel is not great for table data yet (coming later this year I hope)
