### ISSUE TITLE
No scroll bar when opening the search menu

### ISSUE THREAD

**Issue by cristizafiu** [grafana/grafana#1644]
When opening the dasboard search menu, panels from the bottom of the page are no longer visible and there is no scroll bar to scroll down to them. This is reproduced with the latest version, 1.9.1 both for chrome and firefox. I've attached a screenshot of the issue.
![dash_search](https://cloud.githubusercontent.com/assets/11646948/6824688/096cfc5e-d2fd-11e4-970c-165432d1bea4.jpg)

**Comment by torkelo** [comment]
Fixed in Grafana 2.0 (develop branch, will be merged to master later this week, beta soon)
