### ISSUE TITLE
Legend decimals default to 0 for auto but should be 3 (Graphite)

### ISSUE THREAD

**Issue by soulgalore** [grafana/grafana#16448]
**What happened**:
Upgrading from Grafana 5.4.3 to 6.x (I tried the first 6 release and today 6.1.2 and its the same) changes the number of the decimals in the legend. The legend decimals is set to auto. In 5.4.3 the legend showed 3 decimals, in 6.x it shows 0 decimals.

In 5.4.3 it looks like this:
<img width="727" alt="5 4 3" src="https://user-images.githubusercontent.com/540757/55726652-978baa00-5a10-11e9-929d-37107cc7bba0.png">

And in 6.1.2:
<img width="733" alt="6 1 2" src="https://user-images.githubusercontent.com/540757/55726664-a4100280-5a10-11e9-8b33-1b0efe62612e.png">

**What you expected to happen**:
I expect the legend to keep 3 decimals.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
If it would help, I can give you access to admin or whatever is best. https://dashboard.sitespeed.io/d/000000044/page-timing-metrics?panelId=2&fullscreen&orgId=1

**Environment**:
- Grafana version: 6.1.2
- Data source type & version: Graphite 1.1.5
- OS Grafana is installed on: Ubuntu through Docker
- User OS & Browser:
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by thiell** [comment]
We had to revert to 6.0.2 today after trying 6.1.x due to problems with Legend decimals too, but for us, the Legend decimals option was not taken into account at all and many decimals were shown in Singlestat for example, even with Legend decimals set to a specific number.
