### ISSUE TITLE
lost 'Legends' from rendered image

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#16443]
The following bug occurred with version 6.1.0. It was good for version 6.0.2.

The 'Legends' will no longer appear on the graph if its content is too large (or other reason) on the **rendered image**.

**Version 6.1.0 (wrong):**
![image](https://user-images.githubusercontent.com/2911588/55719637-006a2680-59ff-11e9-8ab6-0125cd02fa4a.png)

**Version 6.0.2 (good):**
![image](https://user-images.githubusercontent.com/2911588/55719586-e3355800-59fe-11e9-944a-48588c66934a.png)

I tried several image sizes and database types, each with a similar error.

**Comment by torkelo** [comment]
thanks for reporting this! We will investigate.

**Comment by sanchomuzax** [comment]
Solved in v6.1.3, tnx!
