### ISSUE TITLE
Sidebar cannot be hidden

### ISSUE THREAD

**Issue by RedSpid3r** [grafana/grafana#16449]
**What happened**:
Since upgrading to `v6.1.1` (from 5x) it seems you can no longer hide the sidebar by clicking the Grafana logo in the top-left of the window.

**What you expected to happen**:
Left clicking the Grafana logo in the top-left of the window hides the sidebar

**How to reproduce it (as minimally and precisely as possible)**:
- Open any dashboard
- Left click on the Grafana icon in the top-left

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.1
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10 x64 | FireFox Quantum 66.0.2 x64
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
We removed this feature in 6.1, you can now only hide the sidemenu by going into TV / kiosk mode (use TV button on dashboard)

**Comment by cmur2** [comment]
Very unpractical for users with smaller screens since there is now less space available for what actually matters: the dashboards.
