### ISSUE TITLE
All files in Grafana

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#16442]
Hi Team,

Currently, I'm using the latest version of Grafana. I want to add all the folders and sub-folders in my dashboard. The data source I use is Graphite. 

Thanks,
Siddharth

**Comment by torkelo** [comment]
>  I want to add all the folders and sub-folders in my dashboard. 

What? Can you describe with more detail?

**Comment by Siddhu1096** [comment]
Yes, @torkelo , Currently I've added 6 servers on my Grafana dashboard, Graphite is my data source.
But I can see only one folder in each of the servers. Is there a way to add all the folders and subfolders in Graphite and display them in Grafana?
![123](https://user-images.githubusercontent.com/22325249/55713892-37e0cf00-5a0f-11e9-8daf-06add7d712e1.PNG)

**Comment by Siddhu1096** [comment]
Thoughts? @torkelo @marcv81

**Comment by torkelo** [comment]
I dont really understand what your talking about. When you create a Graphite query the dropdowns don't show all your Graphite metrics?

**Comment by Siddhu1096** [comment]
Yeah. It only shows nciwin folder.
