### ISSUE TITLE
Singlestat metric is stopping work after reload tab. 

### ISSUE THREAD

**Issue by ultimator123** [grafana/grafana#16446]
**What happened**:
When i reload the tab in which i opened Grafana some of my Singlestat-Metrics show "no value".
When i try to inspect the Query with the Query Inspector, the Query Inspector just loads a really long time. 

**What you expected to happen**:
It should reload and show all the data

**How to reproduce it (as minimally and precisely as possible)**:
Open the affected dashboard and reload the tab (F5).

**Anything else we need to know?**:
It happens only on one dashboard and there it doesn`t happen to all the Singlestat-Metrics.
It affects alwys the same Singlestat Metrics
The Dashboard contains 36 Metrics (33 Singlestats, 3 Graphs) 

**Environment**:
- Grafana version: 6.1.2
- Data source type & version: Zabbix datasource 3.10.1
- OS Grafana is installed on: SLES 12
- User OS & Browser: Windows & Chrome
- Grafana plugins: zabbix-datasource 3.10.1
- Others: apache 2.2, php5

**Comment by torkelo** [comment]
Any error in the brower js console?

**Comment by paddif** [comment]
Im writing for ultimator123:
at Chrome JS Console we're getting the following messages:
![image](https://user-images.githubusercontent.com/4719545/55776967-b173ce00-5a9e-11e9-93f2-4c14456a9b4e.png)

**Comment by paddif** [comment]
Any Updates on this?

**Comment by torkelo** [comment]
Can you show the network requests when you reload the page? The queries for the singlestat, anything that looks wrong? Any error / empty response from zabbix?

**Comment by ultimator123** [comment]
We were able to fix the bug by replacing all the requests in which we requested the data for the Singlestat Metric with the Query Mode ItemID. Instead we are now using the Query Mode Metric. 
Furthermore we are now using the Direct DB Connection the Zabbix-Plugin for Grafana offers so we have a better performance when we request data from zabbix.
