### ISSUE TITLE
Feature Request: Ability To Move Variables Around Dashboard

### ISSUE THREAD

**Issue by timlharrison** [grafana/grafana#16452]
**What would you like to be added**:
I would like to have the ability to move variables around a dashboard.  For instance, if I wanted variables to be vertically left-aligned or right-aligned, etc. rather than just lined up horizontally across the top.

**Why is this needed**:
My use case is that I want to create a series of user inputs to generate a dashboard and without having the ability to line up the variables the way I want to, it is confusing and cluttered at the top of the dashboard.

**Comment by JamesHealey94** [comment]
+1:  It'd be nice to change the layout of these - I have some dashboards where the top row might be overviews, then the second row is filtered with a variable - Having the variables below the first row would make that clearer

Example of how a dashboard would look at the minute:
![image](https://user-images.githubusercontent.com/633125/55861119-a2a81c80-5b6d-11e9-85ba-f4d5a8da0d72.png)

The dropdown here might not change the first panel, which can be made more obvious if we were able to move the variables similarly to how we currently move rows.

**Comment by abhishekmangudkar** [comment]
+1
It'll be useful to keep variable beside respective dashboard

**Comment by lester289** [comment]
+1
This feature would be very usefull for my dashboard.

**Comment by AayushNagpal** [comment]
+1

**Comment by wichan1** [comment]
+1

**Comment by scottRob12** [comment]
+1

**Comment by FideriaJT98** [comment]
+1

**Comment by munhozdiego** [comment]
+1

**Comment by MauroVicic** [comment]
+1

**Comment by sticks221** [comment]
+1

**Comment by fa1861** [comment]
+1

**Comment by karln-star** [comment]
+1

**Comment by nunks** [comment]
Maybe move the variable box logic to a kind of panel? I like to have lookup tables in some dashboards dinamically filtered by variables, and putting the variable box next to the table would be aesthetically better.
+1, btw

**Comment by salvq** [comment]
In my use case is about ergonomy and also aesthetically. I would like to keep control drop down lists on one place (kind of control panel) i.e. before looking at the graph set all the necessary variables.

**Comment by Francesco-30** [comment]
+1, it just make more sense to have the variables spatially related to the panel that takes advantage of them! By the way, thanks grafana developer for the terrific job!

**Comment by amandagmsd** [comment]
+1

**Comment by xtrimf** [comment]
+1

**Comment by gilberthdez** [comment]
+1

**Comment by GuilhermeDaniluski** [comment]
+1

**Comment by Anand25021998** [comment]
+1

**Comment by ChrisGet** [comment]
+1

**Comment by sinusen** [comment]
+1

**Comment by DanilovKostya** [comment]
+1

**Comment by AranScope** [comment]
+1

**Comment by atulmodi-akamai** [comment]
+1

**Comment by matiasba** [comment]
Variables should really be inside their own panel type. The current implementation looks like a stop gap measure.

**Comment by aqos156** [comment]
+1

**Comment by avilsmeier** [comment]
Pretty Please? :D

**Comment by SteffenEnz** [comment]
+1

**Comment by ivonutar** [comment]
+1

**Comment by rzk91** [comment]
+1 :D
I think, something akin to rows would be just fine, too.

**Comment by tanzeelrana** [comment]
it would be nice to be able to put the variables drop down in grafana dashboard header, it will help in user experience that when I have scroll down in a dashboard I dont need to scroll back up to change a selected variable.

**Comment by HanHoRang** [comment]
+1

**Comment by GeorgeBowers** [comment]
+1

**Comment by edumaciel** [comment]
+1
It would be very useful!

**Comment by dheeruymv** [comment]
+1 It would be useful to group them into rows

**Comment by jaredleitner** [comment]
+1

**Comment by brianschwind** [comment]
+1

**Comment by Amit-Modi** [comment]
+1

**Comment by DanilaCharushin** [comment]
+100500 pls
push me when add

**Comment by akononen** [comment]
+1

**Comment by meshiruff** [comment]
+1

**Comment by AnSche3** [comment]
+1

**Comment by Dongzhenpu** [comment]
+1

**Comment by alexkingibm** [comment]
+ 1

**Comment by dodo217** [comment]
+1

**Comment by Jordhan-Carvalho** [comment]
My friend Gabriel Fialho made an amazing dashboard, the only problem is that he can't move the location of variables inputs, which makes him very sad... Please make my friend happy again.

**Comment by SaigaGentil** [comment]
+1

**Comment by lxkaka** [comment]
+1

**Comment by rappzons** [comment]
+1

**Comment by fabioleite0** [comment]
+1

**Comment by SiavashCS** [comment]
+1

also links

**Comment by dabaooline** [comment]
+1

**Comment by bujos** [comment]
any update?

**Comment by laumarf3** [comment]
+1!! :)

**Comment by bode689** [comment]
+1

**Comment by sian789** [comment]
+1

**Comment by SBolo** [comment]
+1

**Comment by abin-tiger** [comment]
+1

**Comment by lizztheblizz** [comment]
+1

**Comment by ZYFZYF** [comment]
+1

**Comment by armant** [comment]
+1

**Comment by aeshaynes** [comment]
+1

**Comment by hebinongyi** [comment]
+1

**Comment by OldStarFox** [comment]
+1

**Comment by samputer** [comment]
+1

**Comment by riquinhuw** [comment]
+1

**Comment by mkrakowitzer** [comment]
+1

**Comment by alexander-minchin** [comment]
+1

**Comment by ZiemniakPL** [comment]
+1

**Comment by ppalyafari** [comment]
+1

**Comment by tam5** [comment]
+1

**Comment by mimarcos** [comment]
+1

**Comment by morrisdirector** [comment]
+1

**Comment by vashafaris** [comment]
+1!!

**Comment by naiemeh** [comment]
+1

**Comment by naiemeh** [comment]
This feature will be very useful for different type of graphs and dashboards.

**Comment by woutkonings** [comment]
+1

**Comment by Leviathan09** [comment]
+1 for dashboards with multiple sections, being able to have variables right above each section would be amazing

**Comment by gpinkos** [comment]
Still being requested as of Oct 2022...

https://community.grafana.com/t/how-to-freeze-variables-pane/75096

**Comment by hajdukda** [comment]
Bump - it would be super useful to be able to at least define variables PER ROW

**Comment by agatherer** [comment]
At the risk of stating the obvious, You can order your variables in the list by dragging using the right hand side 6 dot thing in the variables list. If it was possible to force a newline in the list then you would be well on your way to variables per row

**Comment by itsnull12** [comment]
+1 need this feature

**Comment by bigHave** [comment]
+1

**Comment by ghoss39** [comment]
+1

**Comment by mourya92** [comment]
+1

**Comment by PoloB12** [comment]
+1

**Comment by jarmstrongst** [comment]
+1

**Comment by saymeowmeow** [comment]
+1 Waiting for this feature!

**Comment by IgorSteps** [comment]
+1, would really love to see this implemented

**Comment by ossayenko** [comment]
+1 Good to have even just freeze for variables, it's hard to deal with multiple Grafana pages

**Comment by Bhautik-Gajera-6050** [comment]
+1

**Comment by epgodoy** [comment]
+1

**Comment by wkneewalden** [comment]
+1

**Comment by miller-cntr** [comment]
+1

**Comment by farmboy-dev** [comment]
+1

**Comment by leo-remitly** [comment]
+1

**Comment by VikranthNarla** [comment]
+1

**Comment by ppalyafari** [comment]
Hi All, since we've been waiting for quite a while now, I thought I'd share what I created for myself as a workaround for now. I've created a plugin which simply creates a drop-down in a panel, and it offers the options of the existing template variable that is set in the panel settings. It doesn't support multi-value selection for now.

https://github.com/ppalyafari/grafana-movingtemplatevariables

**Comment by LucBerge** [comment]
+1

## Problem

The top of my dashboard are general KPI and the bottom of my dashboard are filtered KPI. The variables used for filter are at the top. This is problematic for multiple reasons:
- I don't want to reverse my dashboard because general KPI are more important and must be at the top for fast reading
- Everytime I want to apply a new filter I have to go up, change the filter and go down
- A user who don't know the dashboard will change the filter without seeing any changes

## Solution

I would like my variable selection to be between the two sections. I want to be able to move my variables !

**Comment by fschlimb** [comment]
+1

**Comment by derekb137** [comment]
how many +1s this gonna take

**Comment by derekb137** [comment]
for reals tho how many +1s this gonna take - lets goooo

**Comment by itsnull12** [comment]
Good news! This feature available on Grafana Plugin. Created by Volkov Labs. 
https://github.com/VolkovLabs/volkovlabs-variable-panel

**Comment by gauravpandeydotdev** [comment]
> Good news! This feature available on Grafana Plugin. Created by Volkov Labs.
> https://github.com/VolkovLabs/volkovlabs-variable-panel

Just tried this, thanks for sharing. Really well made @mikhail-vl & @asimonok!

**Comment by mdvictor** [comment]
We're not planning on doing anything around this area for now, so I will close this issue for now. We are currently migrating to a new architecture that will allow us more flexibility in what we develop, so this might be touched later on. In the meantime, you can use the [variable panel](https://github.com/VolkovLabs/volkovlabs-variable-panel).

Thank you for opening this issue.

**Comment by gotoworld** [comment]
+1

**Comment by rrhodes** [comment]
+1

**Comment by fisherwei** [comment]
+1

**Comment by mahklah** [comment]
+1
