### ISSUE TITLE
Search API v2

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#16457]
The backend search API requires a breaking change in order to support paging as it currently only returns the list of items directly so no way to return page count. 

Might need a design doc with different approaches. 

* Make a /api/search-v2/
* Introduce a new dashboard specific api search route? 

How to deprecate, log calls to old api?

**Comment by marefr** [comment]
Is the paging needed for Grafana UI or API usage to retrieve "all" dashboards and folders?

**Comment by torkelo** [comment]
related to issue, https://github.com/grafana/grafana/issues/16049

**Comment by torkelo** [comment]
@marefr long term I think both, short term I think only for api. It feels bad to not have a way to list all dashboards in the api.

**Comment by marefr** [comment]
As a first step it would be quite straight forward to implement the route `/api/dashboards/`.
