### ISSUE TITLE
Graphs truncated (Grafana 1.9.1 & InfluxDB 0.8.8)

### ISSUE THREAD

**Issue by msylla** [grafana/grafana#1645]
First of fall, thanks for this great product that we've recently discovered and are evaluating as part of our monitoring system solution.

We're having those graphs truncated, i've noticed that when i've inserted some SingleStats panel, but not sure that this is the root cause...

Anyone has encountered this issue and resolved it ? Thanks in advance.

**Comment by torkelo** [comment]
Truncated?

**Comment by msylla** [comment]
![truncated_graphs](https://cloud.githubusercontent.com/assets/6760754/6830709/f7e39370-d31b-11e4-9fe7-d3ee9d95300b.png)

Sorry the attached file didn't go... here it is

**Comment by torkelo** [comment]
It is probably a timing issue between your influxdb machine and your local browser machine, since you are viewing last 5 minutes, looks like a difference in 1 min

**Comment by msylla** [comment]
Any clues on where to check ? You believe it is a network latency issue ?

**Comment by torkelo** [comment]
@msylla no I think the clock on you influxdb server and the clock (date & time) on your local browser machine are slightly off, you are only requesting "last 5min" from influxdb, which to your browser might be from 18:10 but for the influxdb server it is 18:11

**Comment by msylla** [comment]
Thanks, that was actually the case !
