### ISSUE TITLE
Cannot get past login screen when using http since 6.0.0

### ISSUE THREAD

**Issue by danhallin** [grafana/grafana#16465]
**What happened**:
I get returned to /login after successful login in 6.0.0 and 6.1.2 over a http-connection.
(does not happen in 5.4.3 and not in identical 6.1.2-instance over https)

**What you expected to happen**:
In the other instance (running behind https being the only difference I am aware of) I get transferred to /?orgId=1

**How to reproduce it (as minimally and precisely as possible)**:
docker-compose.yml:
```
version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      # sudo chown 472:472 ./grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    user: "472"
```

/etc/apache2/sites-enabled/000-default.conf
```
<VirtualHost *:80>
  ServerName grafana

  ProxyPreserveHost On

  ErrorLog  "/var/log/apache2/grafana_error.log"
  CustomLog "/var/log/apache2/grafana_access.log" common

  <Location />
    <RequireAny>
      Require ip 10.8.2.0/24
      Require ip 10.8.4.0/24
      Require ip 192.168.101.0/24
    </RequireAny>
  </Location>

  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/

</VirtualHost>
```

**Anything else we need to know?**:

Debug output:

Going to login screen:

t=2019-04-09T10:59:32+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=200 remote_addr=10.8.4.200 time_ms=3 size=22026 referer=

When logging in:

t=2019-04-09T11:00:05+0000 lvl=dbug msg="user auth token created" logger=auth tokenId=8 userId=1 clientIP=10.8.4.200 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0" authToken=a7347abfa371d0df36d4c57f0ad749c5a168544bdc4a9e7453c370ddbb2d2194
t=2019-04-09T11:00:05+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=200 remote_addr=10.8.4.200 time_ms=52 size=41 referer=http://10.8.4.1:3000/login
t=2019-04-09T11:00:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.8.4.200 time_ms=0 size=29 referer=http://10.8.4.1:3000/login
t=2019-04-09T11:00:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=200 remote_addr=10.8.4.200 time_ms=2 size=22026 referer=http://10.8.4.1:3000/login

**Environment**:
- Grafana version: 6.1.2 and 6.0.0
- Data source type & version: docker image
- OS Grafana is installed on: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-143-generic x86_64)
- User OS & Browser: Tested in Firefox / Chrome
- Grafana plugins: -
- Others: Docker version 18.09.4

**Comment by marefr** [comment]
What url are you using when logging in and what root_url have you configured Grafana to use? Maybe similar problem as https://github.com/grafana/grafana/issues/15714#issuecomment-468953515?

**Comment by danhallin** [comment]
I have tried using
http://grafana and http://10.8.4.1:3000

I now configured https instead and I can then login successfully on https://grafana

/etc/apache2/sites-enabled/default-ssl.conf

<VirtualHost *:443>
  ServerName grafana

  SSLProtocol all -SSLv2
  SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM

  SSLEngine on

  ErrorLog  "/var/log/apache2/grafana2_error.log"
  CustomLog "/var/log/apache2/grafana2_access.log" common

  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/

</VirtualHost>

**Comment by marefr** [comment]
Please include your grafana.ini file. For `http://grafana` you'll need to configure [root_url](http://docs.grafana.org/installation/configuration/#root-url) to `http://grafana`.

**Comment by danhallin** [comment]
```
[security]
admin_user=someuser
admin_password=somepassword
; tried both
cookie_secure=true / false

[server]
protocol=http
router_logging=true

[session]
session_life_time=86400
; tried both
cookie_secure = true / false

[log]
level=debug

**Comment by danhallin** [comment]
Changing to this did not solve the problem:
```
[server]
protocol=http
root_url=http://grafana
```

**Comment by torkelo** [comment]
are you accessing grafana via http://grafana ? the logs say differently:

The referer says, you should use this in your root_url
`http://10.8.4.1:3000/login`

**Comment by SugandhaDuhan** [comment]
setting to cookie_samesite = none doesn't work. It asks for additonal secure attribute which in turn asks grafana to be served over https.
Hence, none of the solutions worked for me.

**Comment by marefr** [comment]
@SugandhaDuhan I'm guessing you're using Chrome 80+ version and things have happened lately in regards to the cookie same site attiribute from Chrome's perspective. Please read [our upgrade notes ](https://grafana.com/docs/grafana/latest/installation/upgrading/#important-changes-regarding-samesite-cookie-attribute) and make sure to use Grafana v6.6 at least, but preferably the latest stable version

**Comment by SugandhaDuhan** [comment]
@marefr ... Thanks for your reply... 
After researching on this issue... following worked for me:
protocol = https
cookie_samesite = none
cookie_secure = true

and serving grafana over https...

I had kept my certificates in the following path and updating the same in garafana.ini file:

cert_file = /etc/grafana/cert.pem
cert_key = /etc/grafana/key.pem

**Comment by fachrisdakbar** [comment]
> @marefr ... Thanks for your reply...
> After researching on this issue... following worked for me:
> protocol = https
> cookie_samesite = none
> cookie_secure = true
> 
> and serving grafana over https...
> 
> I had kept my certificates in the following path and updating the same in garafana.ini file:
> 
> cert_file = /etc/grafana/cert.pem
> cert_key = /etc/grafana/key.pem

protocol is not http? why we changed ?
