### ISSUE TITLE
custom datasource: add ability to define "custom actions" for queries

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#16464]
**What would you like to be added**:
Each datasource provides a set of _actions_ for each query in the editor mode of panels (you know, the "toggle edit mode", "move up/down" and so on):
![grafik](https://user-images.githubusercontent.com/11644606/55794724-40481100-5ac6-11e9-9ba7-ae0e7522b216.png)
Right now, the only thing that is customizeable here is the "has-text-edit-mode" button, which can be controlled like this:
`<query-editor-row has-text-edit-mode="true" [...]>`
What I'd like to see is the possibility to **customize** the actions even more. Especially **adding new custom actions** is missing, IMHO.

**Why is this needed**:
I'd like to improve my custom datasource by adding some new actions regarding queries, for example:
* copy query to clipboard
* link to another website, using the query as payload

I don't like the idea of adding buttons for these actions somewhere else (within the editor itself). IMHO, the current _actions_ are the right place to add custom actions.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
