### ISSUE TITLE
Docs feedback: installation/docker.md recommended volume mount obscures pre-installed plugins

### ISSUE THREAD

**Issue by tve** [grafana/grafana#16474]
The docker installation first describes how to pre-install plugins (https://grafana.com/docs/installation/docker/#building-a-custom-grafana-image-with-pre-installed-plugins) and then proceeds to recommend a volume for persistent storage (https://grafana.com/docs/installation/docker/#grafana-container-with-persistent-storage-recommended) however, the persistent storage mount obscures the pre-installed plugins and the user is left to wonder why the pre-installed plugins don't show up in the UI.

**Comment by torkelo** [comment]
thanks for the feedback!

**Comment by tve** [comment]
FYI, the way I solved it is by installing into /var/lib/grafana-plugins in the Dockerfile:
```
FROM grafana/grafana:6.1.2

USER 0:0
RUN mkdir /var/lib/grafana-plugins; chown 1000:1000 /var/lib/grafana-plugins

USER 1000:1000

ARG GF_INSTALL_PLUGINS="natel-plotly-panel,vonage-status-panel,natel-discrete-panel,fetzerch-sunandmoon-datasource"

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir /var/lib/grafana-plugins plugins install ${plugin}; \
    done; \
fi
```
And then setting GF_PATHS_PLUGINS accordingly when launching the container.
A (cleaner) official solution would be welcome...

**Comment by marefr** [comment]
@oddlittlebird reopen this since I think this was mistakenly closed?

**Comment by oddlittlebird** [comment]
Yes, thank you!
