### ISSUE TITLE
Rendered graph: not auto decimals in legend values

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#16476]
The rendered graph legend didn't get the correct auto decimals for avg values.

On the rendered image is wrong:

![image](https://user-images.githubusercontent.com/2911588/55830904-47950c00-5b12-11e9-91e4-6f7d366eefcc.png)

On the web graph is ok:

![image](https://user-images.githubusercontent.com/2911588/55830887-3d730d80-5b12-11e9-8451-5e5ac518f787.png)

Decimal settings:

![image](https://user-images.githubusercontent.com/2911588/55831022-7ca15e80-5b12-11e9-9118-8a20e7a3ef0f.png)

Tested on v6.1.3

**Comment by torkelo** [comment]
what version of Grafana are you uising?

**Comment by sanchomuzax** [comment]
v6.1.3

**Comment by sanchomuzax** [comment]
v6.1.3

**Comment by torkelo** [comment]
This should be fixed in later releases, try latest stable 6.2.1

**Comment by sanchomuzax** [comment]
Unfortunately, it remains unchanged. 😢 

Grafana v6.2.1 (commit: 9e40b07)

Rendered image:
![image](https://user-images.githubusercontent.com/2911588/58460731-8288e880-812e-11e9-8fef-0526b9c047ad.png)

**Comment by torkelo** [comment]
Ah, sorry you mean the PNG image. 

Try our new PNG image rendering plugin, 
https://github.com/grafana/grafana-image-renderer

**Comment by sanchomuzax** [comment]
I couldn't install it. :(

Isn't this part of the whole Grafana system? Why?
