### ISSUE TITLE
Improve the Tab <> Dropdown responsive behavior

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16475]
Currently, the tabs switch to dropdown more aggressively than needed.  For example:

![image](https://user-images.githubusercontent.com/705951/55821290-fa814d80-5ab1-11e9-8157-0f7f3180e968.png)

vs

![image](https://user-images.githubusercontent.com/705951/55821308-053be280-5ab2-11e9-8b83-1bc5205198c8.png)

On datasources it is pretty weird since there is only ever one option: Settings

It would be nice if the switch to dropdown:
 * only happens when > 1 entry
 * maybe add up the #of characters in all tabs and pick the switch px based on that?

**Comment by torkelo** [comment]
> On datasources it is pretty weird since there is only ever one option: Settings

Some data sources have a dashboards tab (they come bundled with dashboards)

**Comment by torkelo** [comment]
but yes, the responsive switch could be more dynamic and depend on many tabs there actually are.
