### ISSUE TITLE
Building Container Results in "grunt: not found"

### ISSUE THREAD

**Issue by swtch1** [grafana/grafana#16478]
**What happened**:
When trying to build the container I received
```
Step 21/37 : RUN ./node_modules/.bin/grunt build
 ---> Running in 60ba2c70ed81
/bin/sh: 1: ./node_modules/.bin/grunt: not found
The command '/bin/sh -c ./node_modules/.bin/grunt build' returned a non-zero code: 127
```

**What you expected to happen**:
The container to build successfully.

**How to reproduce it (as minimally and precisely as possible)**:
```
go get github.com/Unknwon/bra
~~~
npm install -g yarn
~~~
go get github.com/grafana/grafana
cd $GOPATH/src/github.com/grafana/grafana
docker build -t grafana/grafana:dev .
```

**Anything else we need to know?**:

**Environment**: Windows and Windows WSL
- Grafana version: latest
Also I increased the Docker memory to 4GB but no change, which I did not expect but the docs mention it.

**Comment by daniellee** [comment]
This worked fine for me on Ubuntu (without having to increase Docker memory) - will have to test on Windows to see if there is something specific to Windows that is causing this issue.

**Comment by swtch1** [comment]
This appears to be related to the corporate network I'm on and the odd certificate errors we see.  If you can build I'm content to close this and find a workaround for my network.  Thank you for looking.
