### ISSUE TITLE
Docs: Performance guide

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#16487]
Hardware requirements for Grafana have always been very low due to low resource consumption. With alerting and PhantomJS memory consumption it would be nice to have some information about this in relation to [installation instructions](https://grafana.com/docs/installation/).

Related to #8520 but we should only focus on giving some pointers here regarding spec.

**Comment by bergquist** [comment]
I'm just not sure how we can make a sensible recommendation.

**Comment by ryantxu** [comment]
ha!  it depends :)

One of the reasons I will keep lobbying for the `direct / Browser` datasource access is that it can shift the load away from grafana and can use _super_ minimal resources on small systems.

I do think it is reasonable to point out the features in grafana that do consume resources:
* server side rendering 
* alerting
* proxy

**Comment by bergquist** [comment]
A performance guide describing which features that require more resources would make sense.

**Comment by marefr** [comment]
Yes this was my initial thought. Badly written title I suppose.
