### ISSUE TITLE
Share query results across panels

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16480]
**What would you like to be added**:
I would like to have one query that can get displayed in multiple ways without needing to repeat the query.  Essentially be able to show a graph and table for the same query (without executing multiple times!)

**Why is this needed**:
It is pretty common to build a dashboard from results that can be easily queried in one pass.  The graph legend kinda helps with this since you can show things like `current` / `last` value, but it would be great to display that with a singlestat.

This will be pretty important for a streaming sources ;)

-------

There are many ways to do it, perhaps with a cache -- or I think a simple approach could be:

1. Add a buildin pseudo datasource like `-- Dashboard --`
![image](https://user-images.githubusercontent.com/705951/55841720-3a155d00-5ae5-11e9-96d2-238d249dd5e4.png)

2. This would show a picker for the other panels on the same dashboard -- something like the proposal in:  https://github.com/grafana/grafana/pull/15620
![image](https://user-images.githubusercontent.com/705951/55841817-b445e180-5ae5-11e9-88dd-f3ad823c11c4.png)
The UI would also show a readonly summary of what the queries are.

3. in DashboardPanel#componentDidUpdate (or similar) it would check for changes and register  listener, something like:
```
    if(panel.targets && panel.datasource === '-- Dashboard --') {
      for(const query of panel.targets) {
        const ref = dashboard.getPanelById(query.panelId);
        if(ref) {
          ref.addQueryResultListener(panel); // TBD
        }
      }
    }
```

4. In DataPanel and MetricsPanelCtrl, after you get query results, it would also notify any listeners, and remove any that are no longer pointing to the right place.  Not sure the details there, but likely calling `events.emmit(` and/or `setState`

**Comment by torkelo** [comment]
I have been thinking about this scenario a lot last year or so. The long term ways I planned to address this was via

* Separating visualizations from panels so it will be easier to create combo panels that combine different visualizations (graph + gauge or graph + 2 singlestats for example). 
* Make panels only take in data and not handle any query execution.  To to allow the point above and also the point below.
* Create a new type of scripted dashboards where queries live on the dashboard level and generate a dashboard & panel layout based on the query results (so same query can be piped into multiple panels). 

But how to solve this for the current type of dashboard and panels is not something I have spent a lot of time thinking about solving.
