### ISSUE TITLE
Ad-hoc filters don't work with logical operators in formulas

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#16486]
**What happened**:
Ad-hoc filtering isn't working if operator OR is used in a formula.

**How to reproduce it (as minimally and precisely as possible)**:
It was tested on next formulas
OK: grafana_info
![Screenshot_20190410_130147](https://user-images.githubusercontent.com/25184101/55870355-0f80de00-5b91-11e9-9123-19e577402aff.png)

Failed: grafana_info or go_info
![Screenshot_20190410_130219](https://user-images.githubusercontent.com/25184101/55870360-14459200-5b91-11e9-84eb-11a46738ed65.png)

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by PeterZaitsev** [comment]
I would just add one comment referenced in #16568  -  ad-hoc queries do not seem to be integrated with preview correctly. I would expect to be able to provide more technical information about how query formatting goes wrong but prometheus query link does not include any adhoc filters.

**Comment by aocenas** [comment]
There is also more general issue https://github.com/grafana/grafana/issues/14802 but as this is mentioning just subpart of that this specific instance could be easier to fix so going to leave this open.
