### ISSUE TITLE
remote_cache 6.1.x redis configuration

### ISSUE THREAD

**Issue by AlbertasG** [grafana/grafana#16488]
**What happened**:
We were using 5.3.2 with Redis as Session provider successfully. Once upgrading to 6.1.0 and switching to Remote Cache with Redis, we dont see any attempts from Grafana side to store anything to Redis cluster.  tcpdump does not show any traffic towards Redis cluster at all.

Anyone with something similar? Does some load/performance/memory condition needs to be met first for Grafana to start caching remotely?

Nothing was changed except Grafana version bump.
Redis version: 3.2.4

**What you expected to happen**:
Grafana to store/cache some data into Redis on login,loading graphs, etc.

**How to reproduce it (as minimally and precisely as possible)**:
Redis version: 3.2.4

[remote_cache]
type = redis
connstr = addr=redis.grafana.svc,pool_size=100,db=grafana,password=abcd12345

we tried using remote route/direct IP for 'addr' as well.

everything else is default from 6.1.0

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Prometheus,OpenTSDB,Elastic
- OS Grafana is installed on: RHEL 7.5
- User OS & Browser: Win10/Chrome/FF
- Grafana plugins:
- Others:

**Comment by bergquist** [comment]
We started migrating away from using session storage in 6.1+ We only use an auth token which we store in the database instead so Redis is currently not needed anymore. The only place that still uses session storage in 6.1 is auth_proxy. In 6.2 we removed session storage completely.

**Comment by AlbertasG** [comment]
@bergquist maybe i communicated not clearly enough. We are trying to use the newly introduced  #10816 **remote_cache**, not the session storage. 

What i meant that Grafana does not try to do any connections to that new remote_cache Redis.

**Comment by bergquist** [comment]
@AlbertasG the remove_cache is not used yet :) it will be used in 6.2 when using auth_proxy and ldap. We will start using it more eventually.

**Comment by AlbertasG** [comment]
@bergquist Thanks for clarifying :)

CHANGELOG.md and new grafana.ini configuration was the reason for confusion.

**Comment by Optimusbumble** [comment]
Is this feature available now in latest release ? @AlbertasG Can you please tell me if your successfull in implementing this feture in remote_cache.

**Comment by marefr** [comment]
@Optimusbumble yes, if you use Grafana v6.2+ and auth proxy and ldap as @bergquist explains above.

**Comment by tpispirigkos** [comment]
@bergquist I tried on Grafana v6.3.3 and neither redis nor memcached seem to work (no items are inserted in the dbs).  
1) The restriction of proxy and ldap does it still apply for this version too and for memcached? 
2) Also is this restriction applicable for type=database ?
3) if I use [auth.ldap] can I have the the sessions stored in any type of db?

**Comment by marefr** [comment]
@tpispirigkos please read https://grafana.com/docs/installation/upgrading/#session-storage-is-no-longer-used

3. There are no session storage in Grafana since v6.2

**Comment by mosesBD** [comment]
i am confused 
my grafana version is 6.4.3 
can i use **remote_cache** (this link --> https://grafana.com/docs/installation/configuration/#remote-cache) to offload login session data to redis.
if so do i need to configure anything other than remote_cache or use any type of special authentication aside from basic auth?  
i tried using these 2 env variables but no data is sent to redis
GF_REMOTE_CACHE_TYPE=redis
GF_REMOTE_CACHE_CONNSTR=addr=ADDR:PORT

**Comment by ajinkya14feb** [comment]
Can i use remote_cache to store session using redis with grafana 7.0.3?

**Comment by svet-b** [comment]
Similar to the above, I'm curious as to what the status is as of v7.5/v8.0. Under what circumstances is the Redis cache actually used?

We have a Grafana instance backed by a Postgres database, and use Grafana's built-in auth. The Grafana server appears to fire off quite a large number of session verification requests to Postgres. We're keen to ease that load - and naively, it seemed that introducing a Redis cache would serve this purpose. But a quick test indicates that the cache isn't actually being used.

Am I right to assume the cache is not used for Grafana's built-in auth?
