### ISSUE TITLE
Explore: Interval not updated when time range changes

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#16485]
**What happened**:
While zooming out from initial 6 hours over 2 days to 90 days for example in explore view, a step-parameter of 707 is used when requesting the 90day-data from (in this case) a prometheus/thanos backend. Only after a full page reload a step-parameter of 3600 (1h) is used, which seems more appropriate for a 90 day range.

**What you expected to happen**:
For a given time range, always the same step-width should be used.

**How to reproduce it (as minimally and precisely as possible)**:
Start exploration of some data at a 2 days timeframe, select 90 days and take a look at the step-parameter used to fetch the data. Reload the same page and watch the step-parameter again.

**Anything else we need to know?**:
While using thanos as storage backend, this seems to lead to wrong selection of compacted segments (the 1h resolution should be picked).

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: prometheus (using thanos)
- OS Grafana is installed on: debian stretch 9.11
- User OS & Browser: Linux, Chrome 73.0.3683.103 (Official Build) (64-bit)
- Grafana plugins: Pie Chart
- Others:

**Comment by torkelo** [comment]
Sounds like a bug!

Can see that step is not recalculated, and that other data sources do not get correct interval or maxDataPoints parameter.
