### ISSUE TITLE
Dashboard PNG Rendering Issues in v6.1

### ISSUE THREAD

**Issue by deedrah** [grafana/grafana#16495]
**What happened**:
Rendering a dashboard with phantomjs in kiosk mode returns a narrow image with height 16px since version 6.1.x

**What you expected to happen**:
Height of the rendered image should respect `height` parameter as in 6.0.2. Or at least behave like non-kiosk mode.

**How to reproduce it (as minimally and precisely as possible)**:
Run official docker image and try renderer any dashboard in kiosk mode. A TestDataDb datasource and one simple graph panel should be enough.

6.0.2 in kiosk
![6_0_2_kiosk](https://user-images.githubusercontent.com/422802/55885531-6b0b9580-5baa-11e9-8dd0-2d9197506111.png)

6.1.3 in kiosk
![6_1_3_kiosk](https://user-images.githubusercontent.com/422802/55885559-7494fd80-5baa-11e9-83b6-b79bfe86d763.png)

(url: http://localhost:3000/render/d/t7fL14gZk/new-dashboard-copy?orgId=1&kiosk)
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.x
- Data source type & version: any
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dreik** [comment]
Got nearly the same without kiosk mode as well

**Comment by torkelo** [comment]
can't replicate this issue but have issues getting an image with the height I specify

**Comment by deedrah** [comment]
I was playing with grafana and found out that this part in `render.js` cause my problem
https://github.com/grafana/grafana/blob/f8393fb3393e9d02189a052abf765c4f9198adcf/tools/phantomjs/render.js#L58-L70
It is not clear for me how should `height` parameter really behave.
The height of `dashboard-container` is 16px in kiosk mode. This is likely bug in prebuild phantmojs. And it looks like height of `dashboard-container` now depends on height of the screen and not the panels inside.

I am now using grafana with this changes https://github.com/deedrah/grafana/commit/c15f1125daf77840cd4d6824265c905442ea58c2 . The with and height parameters are always respected but if height is omitted, then I will get image with complete dashboard. Maybe another parameter `max_height` could be added to limit image bounds.

**Comment by kjetilmjos** [comment]
I'm having the same problem in the 6.2 release. Changing the height parameter in the URL when rendering a dashboard does not affect the height of the rendered picture.

**Comment by hailong1004** [comment]
I encountered the same problem in version 6.2.5, no matter how to change the height is invalid.

**Comment by torkelo** [comment]
try this plugin https://github.com/grafana/grafana-image-renderer

**Comment by kjetilmjos** [comment]
Tested the plugin now. Rendering works fine with that, I'm able to set height parameter again. Very neat to make it into a docker container :)

**Comment by torkelo** [comment]
ok, closing this, we are removing the built in phantomjs rendering in v6.4 and moving to optionally installed plugin, https://github.com/grafana/grafana-image-renderer

**Comment by diwakar-s-maurya** [comment]
Had trouble setting height until I used grafana-image-renderer. Thanks @torkelo.
