### ISSUE TITLE
Grafana 2.0, API not working correctly with /render/ routes

### ISSUE THREAD

**Issue by guyht** [grafana/grafana#1649]
The API is great, but I am having issues with trying to get a rendered image of a graph.  According to the code, the following should work:

    curl -vvv -H "Authorization: Bearer XXXXX” http://example.com/render/dashboard/solo/dash\?panelId\=3\&fullscreen\&from\=now-2d\&to\=now\&width\=1000\&height\=500

However, it always returns the following, regardless of what route I use.  The API key is correct, if I use different API endpoints (not /render/), then I get the correct data.

![i](https://cloud.githubusercontent.com/assets/385091/6873563/71dcf236-d46e-11e4-960c-fc4b2a2e6c39.png)

The only other clue I can give is that the logs are very slightly different when accessing the url via a browser (authentication via cookie) and issuing a curl command (auth via api key).

Via browser (works, image of graph is displayed) : 

    grafana_1 | 2015/03/27 17:36:04 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard/solo/dash?panelId=3&fullscreen&from=now-2d&to=now&width=1000&height=500
    grafana_1 | Loading a web page: http://localhost:3000/dashboard/solo/dash?panelId=3&fullscreen&from=now-2d&to=now&width=1000&height=500

Via curl (image of login screen returned):

    grafana_1 | 2015/03/27 17:36:21 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard/solo/dash?panelId=3&fullscreen&from=now-2d&to=now&width=1000&height=500
    grafana_1 | 2015/03/27 17:36:21 [I] Completed /dashboard/solo/dash 302 Found in 765.754us
    grafana_1 | Loading a web page: http://localhost:3000/dashboard/solo/dash?panelId=3&fullscreen&from=now-2d&to=now&width=1000&height=500

Note that the curl request result in the extra log line, which appears to suggest a redirect going on somewhere.

**Comment by torkelo** [comment]
hm.. need to test the render api with api token, have not tested that. Thanks for the feedback!

**Comment by guyht** [comment]
Thanks.  I took a look at the code, but Go is new to me so got lost pretty quickly

**Comment by guyht** [comment]
@torkelo thanks!
