### ISSUE TITLE
Grafana should not infer local timezone in MySQL queries results

### ISSUE THREAD

**Issue by herbertdeborba** [grafana/grafana#16497]
I've got this relatively simple SQL query, which only brings up a counter of events and in which day it happened, as shown below:

![GrafanaSQL21h-02](https://user-images.githubusercontent.com/34314852/55899552-76a39000-5b9b-11e9-8816-66e2066ac23b.png)

The issue is that when I port it to Grafana it insists to convert the time field to my local time, UTC-3, which is annoying since I don't even specify the hour in the query. The time field is a full day.

![GrafanaSQL21h-01](https://user-images.githubusercontent.com/34314852/55898992-2415a400-5b9a-11e9-8cdd-4c190111d60a.png)

So, instead of displaying the occurrences on the day it happened, as the results of the query show in the first image, Grafana displays it as if it happened the day before, by 21:00:00.

If I use $___timeGroup() the result is even worse, because it messes the counter:

![GrafanaSQL21h-03](https://user-images.githubusercontent.com/34314852/55899001-2841c180-5b9a-11e9-9cb2-9d186a69bcb1.png)

I think it should not convert anything. If MySQL gives you a date, just print it on the graph. The timezone is already treated there, why should Grafana bother?

Am I missing anything? Is there a way I can solve this?

By the way, you made a great software, keep improving it! Thank you.

**Comment by torkelo** [comment]
It’s MySQL that does this conversation, you have to set your MySQL server timezone to match the timezone of your data (preferably UTC) 

Regarding the time, grafana works with timestamps on a millisecond resolution , and will show you hours as well if the time range and graph width makes that suitable.

**Comment by herbertdeborba** [comment]
In my concern, MySql server timezone is already the same as the data. I cannot set it to UTC since it will mess the user app.

![GrafanaSQL21h-04](https://user-images.githubusercontent.com/34314852/55902337-a9508700-5ba1-11e9-8145-539eab0fb9bc.png)

Also, I don't got the point. On the second image I sent, the query explicitly formats the date without the hour, I guess this way the hour is set to midnight. The issue is that Grafana subtracts the timezone from it, bringing the date to the day before.

On the first image, from mysql-workbench, you can see the results MySql answer for the query, with the date without the hour. These are the correct results. Are you sure is not Grafana that's doing the subtraction?

**Comment by torkelo** [comment]
try wrapping your date in unix_timestamp(yourtime_column) 

See this thread for more info on MySQL timezone issues.

**Comment by jstrong-tios** [comment]
@torkelo I believe you omitted a link to the thread with other mysql timezone issues - could you update with it? dealing with the same issue and came across this first. Thanks!

**Comment by herbertdeborba** [comment]
The @torkelo proposed solution worked out.
Here's the results with it implemented on the query:

![GrafanaSQL21h-05](https://user-images.githubusercontent.com/34314852/55980894-dff2d400-5c6b-11e9-8e17-a0fa7fa8ff78.png)

Thank you and best regards.
