### ISSUE TITLE
Grafana wants to create /usr/share/grafana/data/

### ISSUE THREAD

**Issue by melak** [grafana/grafana#16492]
**What happened**:

Grafana having been installed from https://packages.grafana.com/oss/deb on an Ubuntu 18.04/amd64 host and AppArmor being active with the following profile:

```
#include <tunables/global>

/usr/sbin/grafana-server {
  #include <abstractions/base>
  #include <abstractions/nameservice>

  network inet tcp,

  @{PROC}/sys/net/core/somaxconn r,

  /usr/sbin/grafana-server ix,

  /usr/share/grafana/conf/defaults.ini r,
  /usr/share/grafana/public/** r,
  /usr/share/grafana/phantomjs/** r,

  /var/lib/grafana/ r,
  /var/lib/grafana/** rwk,
  /var/log/grafana/ r,
  /var/log/grafana/** rwk,

  /etc/mime.types r,
  /etc/grafana/** r,
  /{var/,}run/grafana/grafana-server.pid rwk,
}
```

and the following Grafana configuration:

```
$ grep ^[^#] /etc/default/grafana-server
GRAFANA_USER=grafana
GRAFANA_GROUP=grafana
GRAFANA_HOME=/usr/share/grafana
LOG_DIR=/var/log/grafana
DATA_DIR=/var/lib/grafana
MAX_OPEN_FILES=10000
CONF_DIR=/etc/grafana
CONF_FILE=/etc/grafana/grafana.ini
RESTART_ON_UPGRADE=true
PLUGINS_DIR=/var/lib/grafana/plugins
PROVISIONING_CFG_DIR=/etc/grafana/provisioning
PID_FILE_DIR=/var/run/grafana

$ egrep '^(data|logs|path) = /var/' /etc/grafana/grafana.ini
data = /var/lib/grafana
logs = /var/log/grafana
path = /var/lib/grafana/grafana.db
```

upon starting Grafana (`systemctl start grafana-server`), the following AVC denial is logged:

```
node=myhostname type=AVC msg=audit(1554899542.070:405897): apparmor="DENIED" operation="mkdir" profile="/usr/sbin/grafana-server" name="/usr/share/grafana/data/" pid=37613 comm="grafana-server" requested_mask="c" denied_mask="c" fsuid=122 ouid=122 FSUID="grafana" OUID="grafana"
```

That is, despite the data directory having been explicitly specified in all sorts of manners, Grafana still wants to create the directory at the (presumably built-in default) `${GRAFANA_HOME}/data` directory.

**What you expected to happen**:

Grafana not trying to create the default `${GRAFANA_HOME}/data` directory when the configured data directory is different from the default, and also exists. Note that despite not being able to create this directory, Grafana in general works as expected, so the directory seemingly is not needed for proper operation.

**How to reproduce it (as minimally and precisely as possible)**:

On a Linux host supporting AppArmor, apply the profile above, enable AppArmor, start the `grafana-server` service, and observe the system audit log.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: N/A
- OS Grafana is installed on: Linux (Ubuntu 18.04) amd64 with AppArrmor enabled
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
what the content of your systemd service file? have you modified it?

it will use the DATA_DIR env variable.

**Comment by melak** [comment]
No, it has not been modified:

```
# systemctl cat grafana-server
# /usr/lib/systemd/system/grafana-server.service
[Unit]
Description=Grafana instance
Documentation=http://docs.grafana.org
Wants=network-online.target
After=network-online.target
After=postgresql.service mariadb.service mysql.service

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/sbin/grafana-server                                                  \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}  


LimitNOFILE=10000
TimeoutStopSec=20
UMask=0027

[Install]
WantedBy=multi-user.target
```

**Comment by melak** [comment]
I might add that I don't remember this having been a problem in Grafana 5.x (installed from debs off packagecloud.io).

**Comment by torkelo** [comment]
Not sure what is going on for you. I tested the latest deb package on Ubuntu 18, and could not replicate any of your issues.  I tried changing DATA_DIR and it used that new dir, I check in GRAFANA_HOME no data dir created there either. 

Try re-installing?

**Comment by melak** [comment]
Of course there is no dir **created** there, it has no permissions to **actually create** the directory in /usr/share/grafana. The point is, **it does try** doing that, thus polluting the logs.

I have just upgraded to 6.1.4, lo and behold, problem is still there.

```
node=myhostname type=AVC msg=audit(2019-04-16_13:48:57.420:42664): apparmor="DENIED" operation="mkdir" profile="/usr/sbin/grafana-server" name="/usr/share/grafana/data/" pid=18275 comm="grafana-server" requested_mask="c" denied_mask="c" fsuid=122 ouid=122FSUID="grafana" OUID="grafana"
```

On the off chance there is a miscommunication, is the concept of what AppArmor is and what sort of things it does and logs in what circumstances entirely understood?

**Comment by torkelo** [comment]
Can you show the complete grafana log where it shows all configured paths?

**Comment by melak** [comment]
Not a bad direction:
```
t=2019-04-16T13:48:57+0200 lvl=info msg="Starting Grafana" logger=server version=6.1.4 commit=fef1733 branch=HEAD compiled=2019-04-16T11:04:07+0200
t=2019-04-16T13:48:57+0200 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2019-04-16T13:48:57+0200 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2019-04-16T13:48:57+0200 lvl=info msg="App mode production" logger=settings
t=2019-04-16T13:48:57+0200 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=18275
t=2019-04-16T13:48:57+0200 lvl=info msg="Initializing HTTPServer" logger=server
t=2019-04-16T13:48:57+0200 lvl=info msg="Initializing SqlStore" logger=server
t=2019-04-16T13:48:57+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2019-04-16T13:48:57+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2019-04-16T13:48:57+0200 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2019-04-16T13:48:57+0200 lvl=info msg="Initializing SearchService" logger=server
t=2019-04-16T13:48:57+0200 lvl=info msg="Initializing PluginManager" logger=server
t=2019-04-16T13:48:57+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2019-04-16T13:48:57+0200 lvl=eror msg="Failed to create plugin dir" logger=plugins dir=/usr/share/grafana/data/plugins error="mkdir /usr/share/grafana/data: permission denied"
```

Notably, `msg="Failed to create plugin dir" logger=plugins dir=/usr/share/grafana/data/plugins error="mkdir /usr/share/grafana/data: permission denied"`

So it's not the data directory it's trying to create, it's the plugin directory it's trying to create:

```
msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
```

However, the debs install a plugin directory as `/var/lib/grafana/plugins`. So, it looks like either the debs should actually ship the `/usr/share/grafana/data/plugins` directory, or the plugin path should be changed to `/var/lib/grafana/plugins` (or even better, the debs should ship `/usr/share/grafana/data/plugins`, and Grafana should consider both locations when searching for plugins - for (perhaps future) plugins shipped as well as locally-installed ones).

**Comment by torkelo** [comment]
It's strange, it's like you have modified grafana.ini and the plugins path there. 

I am unable to replicate your problem. grafana.ini has the correct path:

```
#################################### Paths ####################################
[paths]                
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
;data = /var/lib/grafana       
                                            
# Temporary files in `data` directory older than given duration will be removed
;temp_data_lifetime = 24h                
                              
# Directory where grafana can store logs
;logs = /var/log/grafana                       
                                        
# Directory where grafana will automatically scan and look for plugins
;plugins = /var/lib/grafana/plugins   
                                                      
# folder that contains provisioning config files that grafana will apply on startup and while running.
;provisioning = conf/provisioning  
``` 
From a fresh deb install ^, everything is commented out. 

default/grafana-server
```
❯ sudo cat /etc/default/grafana-server 
GRAFANA_USER=grafana
GRAFANA_GROUP=grafana
GRAFANA_HOME=/usr/share/grafana
LOG_DIR=/var/log/grafana
DATA_DIR=/var/lib/grafana2
MAX_OPEN_FILES=10000
CONF_DIR=/etc/grafana
CONF_FILE=/etc/grafana/grafana.ini
RESTART_ON_UPGRADE=true
PLUGINS_DIR=/var/lib/grafana/plugins
PROVISIONING_CFG_DIR=/etc/grafana/provisioning
# Only used on systemd systems
PID_FILE_DIR=/var/run/grafana
```

PLUGINS_DIR is correct, and it seems to be correct for you as well as your log says

`t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"  `

But still:
```
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
```

The only way I can replicate that is if you uncomment the plugins path in grafana.ini and change the path there.

**Comment by melak** [comment]
That is not what I get:

```
root@host:/tmp/grafana# apt-get clean
root@host:/tmp/grafana# cat /etc/apt/sources.list.d/grafana.list
deb https://packages.grafana.com/oss/deb stable main
root@host:/tmp/grafana# apt-get -d install --reinstall grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 56.8 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://packages.grafana.com/oss/deb stable/main amd64 grafana amd64 6.1.4 [56.8 MB]
Fetched 56.8 MB in 17s (3,307 kB/s)          
Download complete and in download only mode
root@host:/tmp/grafana# dpkg -x /var/cache/apt/archives/grafana_6.1.4_amd64.deb .
root@host:/tmp/grafana# ls -l etc/grafana/
total 0
root@host:/tmp/grafana# grep plugins usr/share/grafana/conf/defaults.ini
# Directory where grafana will automatically scan and look for plugins
plugins = data/plugins
# for new versions (grafana itself and plugins), check is used
```

A freshly downloaded deb from packages.grafana.com *does* have `plugins = data/plugins` set in `conf/defaults.ini`.

```
root@host:/tmp/grafana# sha256sum /var/cache/apt/archives/grafana_6.1.4_amd64.deb 
1ce4d2cfaaee4f152a56788d7c3edf09dca177a0393f7cb5eaf5963ef0304335  /var/cache/apt/archives/grafana_6.1.4_amd64.deb
```

**Comment by torkelo** [comment]
those defaults are not used, overriden by the systemd / initd script:

t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"

**Comment by melak** [comment]
But then why is it still trying to create it?

```
# grep plugins /var/log/grafana/grafana.log
t=2019-04-16T13:48:57+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2019-04-16T13:48:57+0200 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
t=2019-04-16T13:48:57+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2019-04-16T13:48:57+0200 lvl=eror msg="Failed to create plugin dir" logger=plugins dir=/usr/share/grafana/data/plugins error="mkdir /usr/share/grafana/data: permission denied"
# 
```
First, config overridden from command line, then plugin path = /usr/share/grafana/data/plugins, then trying to create the latter.

Is the override not taking effect then?

**Comment by torkelo** [comment]
> Is the override not taking effect then?

Exactly. Can you check your `/etc/grafana/grafana.ini`  , is the plugin path modified there? If that is the case it would override the override, uncomment if that is the case. 

For me it's working, and no one else has reported anything similar, so very strange if you ini file is unchanged.

**Comment by melak** [comment]
But that's what I'm saying - /usr/share/grafana/conf/default.ini **does have plugins = data/plugins set**. Straight off the deb, see above. From what you are saying I gather it **shouldn't**, but it **does**. My /etc/grafana/grafana.ini is based on /usr/share/grafana/conf/default.ini (what else would it be based on), therefore it also has *plugins = data/plugins* set.

So no, my grafana.ini does not modify the plugin path *from what is shipped by the package*, but apparently, what is shipped by the package is wrong then?

**Comment by torkelo** [comment]
> But that's what I'm saying - /usr/share/grafana/conf/default.ini does have plugins = data/plugins set. 

yes, so does mine. That is the default. It is correct. But in an installed package that default is overriden using the command line.

```
ExecStart=/usr/sbin/grafana-server                                                  \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}  
```

your /etc/grafana/grafana.ini  should not be based on defaults.ini, in official packages it's based on  https://github.com/grafana/grafana/blob/master/conf/sample.ini 

that has everything commented out. Why is your based on something else? did you manually change / copy it there?

**Comment by melak** [comment]
The official package does not ship an /etc/grafana/grafana.ini, again see above:

```
root@host:/tmp/grafana# dpkg -x /var/cache/apt/archives/grafana_6.1.4_amd64.deb .
root@host:/tmp/grafana# ls -l etc/grafana/
total 0
```

So I based mine on defaults.ini. I'm starting to get that I should instead have based it on /usr/share/grafana/conf/sample.ini? If it's all commented out by default, why not ship it as /etc/grafana/grafana.ini, marked properly as a config file?

**Comment by torkelo** [comment]
Debian package installs get `/etc/grafana/grafana.ini`  you are the first who has had an issue :) 

The debian package post install will copy it there: 
https://github.com/grafana/grafana/blob/master/packaging/deb/control/postinst#L29

**Comment by melak** [comment]
Maybe because I had upgraded from 5.x, so I already had one file present? Mind you, with this in mind, this error of mine starting off of defaults.ini has apparently had a very long tail.

Also, this is not how you handle config files :) [This is how you handle config files](https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html#automatic-handling-of-configuration-files-by-dpkg). It needs to be marked as a config file in the packaging control scripts, and then dpkg will DTRT.

Anyhow, rebasing my grafana.ini on sample.ini did indeed make for a clean startup without the AVC denial.
Thanks for having kept with me,  much appreciated.

**Comment by torkelo** [comment]
That is how we used to handle config files (still so for default environment file and other files). But it has a ton of problems during upgrades and overwriten config files that we opted for this very common approach to copy it there if missing , which has improved upgrade experience  and reduced questions a ton.
