### ISSUE TITLE
Alert was not sent by email when transitionned from No Data to OK with a FOR statement

### ISSUE THREAD

**Issue by Touchedegris** [grafana/grafana#16496]
**What happened**:
Alert was not sent by email when transitionned from No Data to OK with a FOR statement.  Looks like the alerting was triggered at the Pending state instead of the OK as documented.

**What you expected to happen**:
Grafana should not fire the alert at the Pending state and wait for the next transition Pending to OK.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert rule with no data returned.
Receive the No Data alert
Start sending data to the database

**Anything else we need to know?**:
Worked when transitionned to No Data

Extract from logs:
```
t=2019-04-10T14:18:44+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=16 newState=pending prev state=no_data

t=2019-04-10T14:18:44+0000 lvl=info msg=Rendering logger=rendering path="d-solo/8N3RPmRZz/alerts?orgId=3&panelId=2"

t=2019-04-10T14:18:46+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xyz@abc.com]

t=2019-04-10T14:18:46+0000 lvl=eror msg="Alert Panic" logger=alerting.engine error="**Unknown rule state for alert pending**" stack="[engine.go:175 asm_amd64.s:522 panic.go:513 eval_context.go:77 eval_context.go:90 email.go:77 notifier.go:67 notifier.go:107 notifier.go:112 notifier.go:58 result_handler.go:100 engine.go:218]"

t=2019-04-10T14:19:36+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=16 newState=ok prev state=pending
```

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: Ubuntu 18.04.2
- User OS & Browser: Firefox

**Comment by bergquist** [comment]
Looks like a bug. Could you please share more info about the alert rule configuration?

**Comment by bergquist** [comment]
According to the logs the rule went from `no_data` to `pending` which should not send any email. 

The logs contain a panics that I dont know why it was raised so I'm looking into that.

**Comment by bergquist** [comment]
Closing this since the panic have been removed and this issue seems to be about the confusion about when notifications are sent. If you think I misunderstood you, please ping me and I will reopen
