### ISSUE TITLE
_labelnames() function unavailable in v6.1 for prometheus

### ISSUE THREAD

**Issue by vacheli** [grafana/grafana#16507]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vacheli** [comment]
v6.1 document apear _labelnames() _labelvalues(label) and so on is invailabel for prometheus.

----------------------------------------------------------------
error info as below:
Templating
Template variables could not be initialized: parse error at char 12: could not parse remaining input "()"...

**Comment by daniellee** [comment]
This is a docs issue - the formatting has been messed up on our site for some reason. Here is the markdown file with the correct function names: https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/prometheus.md

![image](https://user-images.githubusercontent.com/434655/55947222-5c76ba00-5c4e-11e9-91f0-8163fd851016.png)

**Comment by daniellee** [comment]
Due to this change that changed asterisks to underscores in the markdown: 9008fcc790605d20b85db2b4d11d35fa87e0c5b3

**Comment by anvarich** [comment]
killed couple of hours to find what is wrong with _labelvalues and when it was changed from label_values.

**Comment by daniellee** [comment]
Published the fix: https://grafana.com/docs/features/datasources/prometheus/#query-variable
