### ISSUE TITLE
The time region doesn't work in my timezone

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#16508]
The time region function doesn't work for timezones that change offset like PT which changes from example +1 to +2 or +7 to +8.

This is a bug, not a feature request. Please, see the comment in the closed #14400 issue.

Europa uses this setting for at least two years. In addition, the function is also malfunctioning because the time axis of the graph is not UTC but local time (I note: correctly).

**Comment by torkelo** [comment]
reopened #14400 

Agree that for this feature to work properly it should have timezone support. But not sure when we can rework this feature, so it will be UTC only for a while.
