### ISSUE TITLE
Problem with single quote escaping

### ISSUE THREAD

**Issue by thall** [grafana/grafana#16503]
**What happened**:
I have problem with showing `CodeHeap 'non-nmethods'`, seems like a double escaping is happening of `'`. I can see the data in the actuator/prometheus `jvm_memory_used_bytes{application="thall.zc-event-exit-point",area="nonheap",id="CodeHeap 'profiled nmethods'",} 1.7169536E7`.  When i URL decoded the query in the graph i get
```
api/datasources/proxy/1/api/v1/query_range?query=jvm_memory_max_bytes{application="thall.zc-event-exit-point", instance="10.1.0.51:8080", id="CodeHeap \\'profiled nmethods\\'"}&start=1554472920&end=1554473250&step=30"
```
When i replace the variable `$jvm_memory_pool_nonheap` with `CodeHeap 'non-nmethods'` the graph works.
![grafana-nonheap](https://user-images.githubusercontent.com/102452/55934393-b4062d00-5c30-11e9-928d-20c1160c1f7d.png)
**What you expected to happen**:
It should be able to fetch the data

**How to reproduce it (as minimally and precisely as possible)**:
`openjdk:11.0.2-jre-slim`
`spring-boot:2.1.3.RELEASE`
`micrometer-registry-prometheus:1.1.1`
Dashboard https://grafana.com/dashboards/4701

**Anything else we need to know?**:
Previous discussions https://micrometer-metrics.slack.com/archives/C662HUJC9/p1554473716047800

**Environment**:
- Grafana version: grafana/grafana:5.3.4
- Data source type & version: quay.io/prometheus/prometheus:v2.4.3
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Firefox 66
- Grafana plugins: 
- Others: Dashboard https://grafana.com/dashboards/4701

**Comment by torkelo** [comment]
Make sure the variable does not use multi value or all value. If these options are enabled you must use the variable in a regex operator context ( =~)

**Comment by mweirauch** [comment]
Thanks for looking into this. I am not sure if this should be considered a regression or not, but with Grafana `4.6.4` the promql works just fine. Going to update the dashboard nevertheless.

**Comment by juliofalbo** [comment]
I have the same issue and the multi-value or all value options are not enabled.

I'm using Grafana 6.4.3.
