### ISSUE TITLE
Query inspector stuck waiting to show results, while query already failed

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#16512]
`Grafana v6.1.2 (de8f6ac)`

Using graphite queries,
when a query fails, i get the red error icon upper left.
Then i go to query inspector, expecting it to tell me the error.
Instead what happens, is it keeps waiting with the spinner icon.
Yet, when i go to chrome dev tools, i can see the render request failed (it was a 500 or 503), but the UI just keeps spinning and waiting and doesn't show anything about the query.

**Comment by torkelo** [comment]
thanks for reporting this. Missed a case when converting query inspector to React. Fix incoming

**Comment by Dieterbe** [comment]
woop woop thanks for the quick turnaround <3
