### ISSUE TITLE
Heatmaps panels in embedded dashboard make browser to crash

### ISSUE THREAD

**Issue by ChrsMark** [grafana/grafana#16515]
Hello,

I'm facing an issue with embedding a dashboard as `iframe` in an AngluraJS application.
The problem is that every dashboard that contain a Heatmap panel makes the browser to hang and finally crash. This happens only with dashboards that contain Heatmaps with Prometheus as Datasource. The same dashboard is loaded normally in Grafana UI, and the problem is only when embedding it as `iframe`.
 Is this normal? Any suggestions regarding what I could investigate?

### What Grafana version are you using?
 Grafana v5.2.4 (0bbac5c) 

cc: @anastop @gpanouts

**Comment by bergquist** [comment]
Embedding Grafana in an iframe is not something we support but we do support iframing panels. 
https://grafana.com/docs/reference/sharing/#share-panel If that doesnt work with heatmap, then its a bug.

**Comment by ChrsMark** [comment]
Hey @bergquist , I embed a Dashboard using the same approach and it works perfect, ie:

`<iframe sandbox="allow-same-origin allow-scripts allow-forms" id="myiframe" src="http://192.168.1.13:3000/d/MkMS_HgZz/m1-22-d2heatmap?refresh=5s&orgId=3&kiosk" width="100%" height="2000" frameborder="0"></iframe>`

Using this frame in an empty html page works again smoothly.

The problem occurs when this is embedded in the AngularJS application, so I guess the combination of heatmap panel in and a heavy app is the problem? :thinking:

**Comment by torkelo** [comment]
Ok, maybe. Closing this then.
