### ISSUE TITLE
$__interval_ms always set to auto-value, even on fixed-interval graphs

### ISSUE THREAD

**Issue by Tatsu-Kishi** [grafana/grafana#16511]
**What happened**:
$__interval_ms is set to the autocalculated value even if a fixed interval is specified in the query (elasticsearch datasource).

**What you expected to happen**:
$__interval_ms to reflect actual used interval for query.

**How to reproduce it (as minimally and precisely as possible)**:
On a Date Histogram query where value=0 use script `_value + $__interval_ms` and change group by interval.

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: Elasticsearch 5.0.0
- OS Grafana is installed on: official docker container
- User OS & Browser: Xubuntu 18.10, Firefox 66.0.2

**Comment by bergquist** [comment]
`$__interval_ms` is expected to scale.
If you want to hardcode an interval you need to create an interval template variable and use that instead.
