### ISSUE TITLE
Docs feedback: features/datasources/azuremonitor.md

### ISSUE THREAD

**Issue by fhlippinio** [grafana/grafana#16526]
https://grafana.com/docs/features/datasources/azuremonitor/#azure-log-analytics-builtin-variables

This does not work anymore. I think since v6.0 global variables overrides the variables. So the use of the variable returns miliseconds and not daytime.

Related to this bug.
https://github.com/grafana/grafana/issues/16365

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/16365
