### ISSUE TITLE
Enable "per datasource" alerting configuration

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#16522]
Currently the alerting feature is an "all or nothing", either alerting is enabled for all supported datasources, or it's disabled completely. It would be very helpful if you could configure which datasources (or class of datasources - like Graphite, ES ,etc...) would be enabled for alerting.

While alerting in Grafana is incredibly helpful, In our production environment we have some datasources that we would like to not be a able to alert on. Mostly due to the load that the alert queries put on the datasource.

**Comment by AnandDevan** [comment]
I am exploring ways to implement this (I work in the same company as @agaon )

I realize that setting `"alerting": false` in [public/app/plugins/datasource/elasticsearch/plugin.json](https://github.com/grafana/grafana/blob/v6.1.4/public/app/plugins/datasource/elasticsearch/plugin.json#L20-L21)

@bergquist , others:  Do you have suggestions on how I can generalize this so it can be included in global configuration. If it is doable, I would like to submit a PR

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
