### ISSUE TITLE
label_names() function unvailable in v6.1 for prometheus

### ISSUE THREAD

**Issue by vacheli** [grafana/grafana#16538]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vacheli** [comment]
It has happened error when use label_names() function
error message as bleow:
    Templating
    Template variables could not be initialized: undefined
-----------------------------------------------------------
<img width="1334" alt="图片" src="https://user-images.githubusercontent.com/5040231/56011764-b8f3db00-5d1b-11e9-8553-fbb058ccd8e3.png">

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/pull/15290

**Comment by bergquist** [comment]
This feature requires prometheus 2.6.0+
Any chance you are running an older version?

**Comment by vacheli** [comment]
Very thank, it's has resolved after upgrade prometheus to 2.8

**Comment by vacheli** [comment]
> This feature requires prometheus 2.6.0+
> Any chance you are running an older version?

Very thank, it's has resolved after upgrade prometheus to 2.8
