### ISSUE TITLE
Force time span on SingleStat

### ISSUE THREAD

**Issue by refaelos** [grafana/grafana#1653]
Hey,

Is it possible to force a time span on a SingleStat inside a dashboard?
I mean, I have the total number of event that I want to show for "all-time" so it'll ignore the selected time span for the entire dashboard.

**Comment by torkelo** [comment]
no, but in Grafana 2.0 you can change any panels relative time (and add a time shift). You cannot set an absolute time yet. But for your case you should be able to put in `365d` in the relative time override:
https://github.com/grafana/grafana/issues/171#issuecomment-71444087
