### ISSUE TITLE
How to fetch folder details?

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#16547]
Hi Team,

I am using Grafana as InfluxDB as the data source and I use telegraf to fetch the data. My requirement is to fetch the folder details which resides in a specific location say, /var/lib/details. I need to show the folders inside this location in Grafana. What should I do? Thanks in advance.

Best,
Siddharth

**Comment by torkelo** [comment]
Grafana is not a file explorer :) 

You will need a data collector writes this file/folder details into a data source that Grafana can query.

**Comment by Siddhu1096** [comment]
I am using telegraf for that. That does not work? @torkelo

**Comment by Siddhu1096** [comment]
[[inputs.file]]
  ## Files to parse each interval.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   /var/log/**.log     -> recursively find all .log files in /var/log
  ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
  ##   /var/log/apache.log -> only read the apache log file
  files = ["/var/log/apache/access.log"]

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"


[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", "/tmp/metrics.out"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "influx"

$ telegraf --config /etc/telegraf/telegraf.conf --input-filter filestat --test
* Plugin: filestat, Collection 1
> filestat,file=/tmp/foo/bar,host=tyrion exists=0i 1507218518192154351
> filestat,file=/Users/sparrc/ws/telegraf.conf,host=tyrion exists=1i,size=47894i,modification_time=1507152973123456789i  1507218518192154351

How can I view this on Grafana?

**Comment by Siddhu1096** [comment]
Okay, Thanks @torkelo 
I did it.
