### ISSUE TITLE
logins always redirect to home page

### ISSUE THREAD

**Issue by daldoyle** [grafana/grafana#16552]
**What happened**:
If I click the "Login" button, the redirect provided is always to the root url, in my case "/grafana/" as I am proxying the result through apache. 

Example -
While on the URL https://myhost/grafana/d/uuid/my_dashboard?orgId=2

Inspecting the login link shows:
<a href="login?redirect=%2Fgrafana%2F" class="sidemenu-link" target="_self"

And sure enough, if I login I get sent back to the home page upon completion.

**What you expected to happen**:
After logging it, the user should be returned to where they were when they clicked the Login button. Same dashboard, same organization.

**How to reproduce it (as minimally and precisely as possible)**:
Allow anonymous access to grafana. Access grafana anonymously, go to a particular dashboard. Then login.

**Anything else we need to know?**:
This used to work prior to 5.3.0 and was implemented here - https://github.com/grafana/grafana/issues/3312

Possibly a regression unless it was removed for a technical reason. I scanned the changelog and didn't see anything that seemed relevant however. Looking at the tags in github it looks like 5.3.0 may have been when the sidebar was reactified and this maybe got lost then.

**Environment**:
- Grafana version: starts in 5.3.0, still present in 6.1.3
- Data source type & version: NA
- OS Grafana is installed on: CentOS7
- User OS & Browser: OSX, Chrome v73
- Grafana plugins: NA
- Others: NA

**Comment by torkelo** [comment]
thanks for reporting this!
