### ISSUE TITLE
Support viewing loki logs in reverse order

### ISSUE THREAD

**Issue by dguendisch** [grafana/grafana#16555]
**What would you like to be added**:
According to a slack discussion loki already supports a direction parameter, but grafana currently hardcodes to descending order (newest logs on top).
Would be great if I could toggle the ordering in grafana.

**Why is this needed**:
Background: I have logs from a bunch of smaller job pods, they are more natural to be read in chronological order, that is from oldest at the top to newest at the bottom, just like the logs would read directly on the filesystem.

Obviously there's a similar issue #16037 which got closed.

**Comment by jonathancrone** [comment]
Our organization is quickly moving into a k8s version of our product, using Loki to aggregate the logs.  This default "newest first" presentation of the logs is creating a lot of difficulty in debugging.  "Natural" human order when looking at logs, when you're coming from a realm of using a text editor, pager (Less/More),  awk, grep, tail, whatever, is that the "older"logs are at the top of the screen, and the "newer" logs are at the bottom of the screen.  This 'hard coded' setting for the logs means that years of experience in how to read text, to grasp technical detail quickly, is completely thrown away.   
To provide an analogy, try going to your favourite blog and start reading from the bottom of the page going upwards. 

I'm honestly astonished that this particular issue has persisted for 8 months:   as a very senior (ok, old :) ) performance test engineer, I was stunned at how slow it was to work through a set of logs using Loki with the 'wrong' UI presentation for the log information i was attempting to work through.  A bug that I could have filtered down to a reable bit of log information using 'traditional' tools (Linux command line)  in 5 minutes or so took 2 hours to write up.

**Comment by davkal** [comment]
> I'm honestly astonished that this particular issue has persisted for 8 months

As an OSS project, we rely on feedback. No feedback, no change.

That being said, we hear you. Also worth mentioning is that sort ordering got a lot of discussion early on and we decided to do things as they are now. Obviously, things can be improved, and you can actively help by describing the use cases like you have done above. That's the kind of feedback that we can turn into action.

**Comment by davkal** [comment]
Related: #20394 which deals with the start point of the limit query. Currently the limit counts from the end time. When sort order is ascending, I'm assuming that you want forward search, but this might not necessarily be true (e.g., ascending ordering but still wanting latest lines).

**Comment by jonathancrone** [comment]
Thanks for the feedback. 

Another interesting nuance:   I received feedback from a member of the dev team in our organization about looking at logs via loki.  The dev team member was complaining about the Jira I'd raised against the component:   they couldn't understand what had happened in the log because the time order was "wrong"  and initially refused to consider the bug.   It wasn't until I showed the situation with loki's behaviour,  that because the pod had already died when the bug was found, that Loki was the only solution to find the log information that they understood.  They then issued some 'choice editorial language' about loki and we wrote a three line script in python to reorder the log in the "natural" reading order.

**Comment by jgehrcke** [comment]
With all these observability systems that we build we sometimes don't try hard enough to put ourselves into the position of those people that will then actually have to do debugging using these systems. I find it rather obvious: trained humans can be **extremely** fast skimming through logs, reasoning about problems as logs fly by, especially if they know the component that emits the log they are viewing, and the structure of that log, from prior experience. Viewing logs in inverted order diminishes a lot of that.

Not sure if that was discussed, but we also could have a reverse button in the UI that only affects the displaying behavior.

**Comment by zutnop** [comment]
After having spent 19 years reading the logs in ascending order, it now takes me an order of magnitude more time to grasp the situation in my head when looking at the Grafana Loki logs window in the wrong order. Almost a deal breaker :).

**Comment by timothyjlaurent** [comment]
It would be awesome to get this working -- I shouldn't have to switch to live tailing to be able to read tables we print to logs.
Please add a button.

**Comment by p0pr0ck5** [comment]
+1. This is possible to do from a log panel in grafana, but not from "Explore" it seems.

**Comment by Sharathmk99** [comment]
`+1`

**Comment by evilezh** [comment]
I'm just wondering, why would someone choose to do reverse order on logs ? And then ask for use cases to put it back as normally we read.
We read books from top to bottom, computer logs from top to bottom. That's how it happens. And now we ask for "feature" to make it read like we usually do. No offense great product (in metrics part) - but I find some similarity to apple products :) Guys .. we have a new mega feature .. now you can copy and paste .. :)
You do not have much feedback, likely because not many people really consider loki as alternative, it is really hard to do reverse and we logically turn to other products, and leave only metrics for grafana.
We was going to do Loki, like an interface for cloudwatch, but it was refused after we couldn't find a way to reverse log ordering.

**Comment by davkal** [comment]
We're working on this in the next minor release. Anyone willing to try out a prototype?

**Comment by p0pr0ck5** [comment]
@davkal we’d be happy to!

**Comment by dguendisch** [comment]
If there's an image available I'd happily try out as well!

**Comment by overcookedpanda** [comment]
> We're working on this in the next minor release. Anyone willing to try out a prototype?

I'd also like to try this if possible :)

**Comment by avkonst** [comment]
How can I try it?

**Comment by avkonst** [comment]
Funny thing, influxdb guys replicated this "feature" too :)

**Comment by avkonst** [comment]
I have found the logging panel for a dashboard with visualisation settings. It can do ascending ordering. Helps a lot thanks.

Here are the remaining issues:

1. The panel, which I configure, can not do "Live" mode as Explore tab can do:
![image](https://user-images.githubusercontent.com/3971413/87108384-4a9f1f00-c2b6-11ea-992b-e148959f946f.png)
The only options is to turn on refreshing every 5s, which I think is not optimal.

2. The Explore tab can do Live mode but still does not have the toggle for Ascending order.
![image](https://user-images.githubusercontent.com/3971413/87108498-9a7de600-c2b6-11ea-889e-8312172df853.png)

3. Automated refreshing for the logging panel (let's say every 5 seconds), changes the order for labels for each line. It makes the impressing like the log lines are moving, but in fact they are not. It is better to have the same order for tags for each refresh.

4. Auto refresh does not have an option to automatically scrolling down, like Live view mode in the Explorer tab (but maybe we can say it is a part of the problem 1.)

5. I have not found a way to parameterise the logging panel. Let me explain: our logs are coming from containers deployed across a set of hosts. I would like my logging panel to have a dropdown checkbox, where I could choose what hosts and what containers to include into the logging panel. Different people are interested in looking into different subsystems. Configuring similar panels with variation of filters is possible but not optimal. Hope it makes sense. 

Hope this feedback helps. And thank you very much for progressing this issue. I am advocating to switch to Loki / Grafana across many deployments we have got, and things like this ticket make it a bit difficult to convince others.

**Comment by jonathancrone** [comment]
@ivanahuckova 
Thank you for taking action on this:

**Comment by midnightconman** [comment]
For anyone else searching through this issue, the new toggle is a button on the right called `Flip results order`. I found it in version 7.2.0.

![image](https://user-images.githubusercontent.com/1736251/94469333-c94f7e00-017a-11eb-80f3-1d8a3fcd5aa9.png)

**Comment by AndiDog** [comment]
Nowadays it's here:

![Image](https://github.com/user-attachments/assets/e65118bf-a3c6-43c0-a0b5-52cced6eed81)
