### ISSUE TITLE
Old Value is displayed in the graph instead of no data

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#16569]
**What happened**:

As you can see from this graph we have flat line QPS for most of the graph.  If we mouse over the values we see data is shown from completely different time - in this case I mouse over around 1:30  but I'm shown in the mouse over  17:05 from the previous day.

![image](https://user-images.githubusercontent.com/3651746/56084648-f3d13e00-5e03-11e9-8329-ca14f72a37e8.png)

The graph is configured to show "null as null" so I would expect when no data is available no data is displayed 

**What you expected to happen**:

The graph is configured to show "null as null" so I would expect when no data is available no data is displayed 

**How to reproduce it (as minimally and precisely as possible)**:

Run the query which covers period when no data is available

**Anything else we need to know?**:

**Environment**:
- Grafana version:

6.1.3

- Data source type & version:

This is ClickHouse data source however I observed same behavior with MySQL data Source too

- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you specify another value for "null" value in graph display option it will, but looks like you have connected on and in that case it will show the nearest point. You can also switch to single mode for the graph tooltip, then it only shows the tooltip when you hover over values.

**Comment by PeterZaitsev** [comment]
Thanks Torkel!

I double checked it is set to "null" in my case and also  changing value to connected, null, null as zero does not have impact on the graph in this case.  It with similar gap in the data in Prometheus data source as an example

![image](https://user-images.githubusercontent.com/3651746/56093544-04cb8f00-5e98-11e9-9746-e0d65d46cbab.png)

**Comment by torkelo** [comment]
strange, tested this with a prometheus query today and could not replicate, with null value set to null. And missing data I get a gap in the graph and no values in the tooltip. 

What does your query return? 

![image](https://user-images.githubusercontent.com/10999/56190797-4f314500-602b-11e9-89bd-154f08c7c9f5.png)

**Comment by PeterZaitsev** [comment]
Hi,  I just re-read my message and I was not super clear.  It does work correctly with Prometheus data source but it looks like it has problems with SQL Data Sources - I seen it with MySQL and now see with ClickHouse 

Yes the query returns.

**Comment by torkelo** [comment]
For MySQL you need to use $__timeGroup(dateColumn,‘5m’, NULL)  So that null values get's inserted for periods without any data.

Not sure if clickhouse has something similar.
