### ISSUE TITLE
Consider renaming ReactPanelPlugin to VizPanelPlugin

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16578]
`AngularPanelPlugin` is ok, since it points out a technology that is getting deprecated... ReactPanelPlugin seems kinda clunky and i think will feel dated pretty soon.  It is obviously react, and the name does not need to point that out :)

I think `VizPanelPlugin` makes sense because it points out a key huge difference between the new plugins and the old ones -- the new plugins are only a way to visualize results, they no longer have control of the whole query lifecycle as they did with MetricPanelCtrl

**Comment by torkelo** [comment]
:+1:
