### ISSUE TITLE
Unlike Timeseries plots, for histogram and heatmap plots, it doesnt show the measurement information on the plots

### ISSUE THREAD

**Issue by subodh100** [grafana/grafana#16572]
Trying to plot timeseries data on "histogram" plot, but don't find anyway to see what this plot is about. The "legend" only show min, avg and total for count.

![image](https://user-images.githubusercontent.com/13319431/56089032-e3739e80-5ea9-11e9-8e6e-4c987dbc6b49.png)

when compare this to a timeseries plot, where i see the Legend showing what data is being plotted:

![image](https://user-images.githubusercontent.com/13319431/56089019-8f68ba00-5ea9-11e9-8135-98c13be7fdb1.png)

**Environment**:
- Grafana version: v6.0.1
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac/Chrome

**Comment by torkelo** [comment]
the histogram will only show value distribution (ie number of measurements that fall into different buckets). 

If you want a histogram split per series you have to enable stacking in the graph options

**Comment by subodh100** [comment]
Thanks .. worked with "stack" option set.
