### ISSUE TITLE
Alerting: Allow configuring the amount of fields sent to Slack

### ISSUE THREAD

**Issue by EugeneKrapivin** [grafana/grafana#16575]
Hey!
I've noticed that we are limiting the amount of fields sent over to Slack:

https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/slack.go#L153

This line seems to limit the amount of sent fields via the slack notifier to 4 (why 4?).
Could we externalize this parameter so it could be easily configurable in the slack notifier configurations?

As per the slacks documentation we can send up to 20 attachments before getting an error.
https://api.slack.com/docs/message-attachments

Thanks,
Eugene!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
