### ISSUE TITLE
X-axis values for histogram is unreadable

### ISSUE THREAD

**Issue by subodh100** [grafana/grafana#16573]
X-axis values for histogram is unreadable when high time range is used.

![image](https://user-images.githubusercontent.com/13319431/56089137-db1c6300-5eab-11e9-832b-b80e6fe7a405.png)

a better way would be to auto adjust the x-axis prints and space them properly.

**Environment**:
- Grafana version: v6.0.1
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac and Chrome/Firefox

**Comment by torkelo** [comment]
what unit and bucket size do you have?

**Comment by subodh100** [comment]
this was set to "auto" bucketing.

**Comment by torkelo** [comment]
And what unit?

**Comment by torkelo** [comment]
Looks like the bucket range values are to high, might need to manually reduce the bucket size

**Comment by subodh100** [comment]
>
> And what unit?
>

unit in billions.

>
> Looks like the bucket range values are to high, might need to manually reduce the bucket size
>

Thanks. At lower time range, this works good. if possible to skip printing some points on x-axis for higher time range, it may appear better.

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/56190235-12188300-602a-11e9-9114-59e98d275979.png)

Unable to replicate this in 6.1
