### ISSUE TITLE
[FeatureRequest] Variables - Add template variable type

### ISSUE THREAD

**Issue by hagen1778** [grafana/grafana#16582]
**What would you like to be added**:
Custom meta-variable with ability to interpolate it's content.

**Why is this needed**:
Building dashboards for a service is usually requires to filter metrics by the same label set.
We create `query` variables to fetch these labels and then do filtering via dropdowns. Then we build panels and copy-pasting the same filter to each query:
`up{region=~"$region", instance=~"$instance"}`

This method is error-prone, especially when you need to update filter, which requires to edit every single query on dashboard. Instead of doing that, I'd prefer to use meta-variable as filter in queries: `up{$filter}`

**Comment by torkelo** [comment]
interesting idea!

**Comment by valyala** [comment]
Great idea!
[The PR](https://github.com/grafana/grafana/pull/16694) simplifies writing and managing complex queries and dashboards by moving repeated parts into meta-variable. There is no need in error-prone query editing for each repeated part during dashboard modifications - just change a single meta-variable. This is really cool!
