### ISSUE TITLE
Graph with multiple queries problem

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#16580]
**What happened**:
I have graph with 3 queries. The first query is at the back of the graph, so queries B and C cover it when they have the same value.

![Adnotacja 2019-04-14 150117](https://user-images.githubusercontent.com/19311511/56097381-7be24100-5ef3-11e9-9d66-e3a18aff0ae1.jpg)

**What you expected to happen**:
I suppose query A which is on the top of the legend should be also on the top of the graph, so query A will cover B and C.

**How to reproduce it (as minimally and precisely as possible)**:
Add at least 2 queries to the graph with the same value.

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Influxdb 1.6.4
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: Influx Admin, Radar Graph, D3 Gauge, WindRose

**Comment by torkelo** [comment]
Temperature is the first series that will be rendered, and the series below will be rendered on top. You can enable stacking if you do not want series to be covering each other

**Comment by szerwi** [comment]
@torkelo how does the stacking work? As I can see, it changes values of the query on the graph so they don't cover each other?
