### ISSUE TITLE
Include an alpha app plugin in master

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16585]
**What would you like to be added**:

Grafana should have an app somewhere in its core code.  It does not need to be exposed.

**Why is this needed**:

Apps are currently all external and it is easy to break support for them if there is nothing in the code base that uses existing APIs.  It would be great to have something in core to make sure apps get considered while APIs change.

**Comment by torkelo** [comment]
closing this as the example as was merged in #16528
