### ISSUE TITLE
Unable to login throught the domain

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#16581]
**What happened**:
I have a domain xyz.com which redirects traffic in a frame to my server with IP xx.xx.xx.xx. When I open a Grafana through a domain, I cannot login to any user in Grafana. I click login button, type correct username and password and after clicking "Log In" I am getting redirected to home page, but I am not logged into my account. I can log in when I open site directly by a IP address xx.xx.xx.xx.

**What you expected to happen**:
Logging in through a domain was working correctly before 6.0 version

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Influxdb 1.6.4
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: Influx Admin, Radar Graph, D3 Gauge, WindRose

**Comment by torkelo** [comment]
If you want to login inside an iframe check your cookie_samesite setting I grafana ini

**Comment by torkelo** [comment]
or sounds like the root_url grafana option is not correct (this should be the full root url you use in browser to access Grafana)

**Comment by szerwi** [comment]
> If you want to login inside an iframe check your cookie_samesite setting I grafana ini

Changing cookie_samesite from lux to none helped, thank you for help.
