### ISSUE TITLE
issue with drilldown links

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#16589]
Datasource: InfluxDB

I have a template variable that returns 3 values.
My objective is to assign this variable to another variable while drilldown.
So, in drilldown link, when I am trying to do `var-SWITCH=$WORST_SWITCH` by passing it as url parameter, I am seeing only the first value is being passed.

Need help on this.

**Comment by debmalyapan53** [comment]
Also, if my template variable returns 3 values, can we access them via index or something?

**Comment by torkelo** [comment]
drilldown links can only link to another dashboard currently, not update variables on current dashboard

https://github.com/grafana/grafana/issues/15130 

> Also, if my template variable returns 3 values, can we access them via index or something?

No
