### ISSUE TITLE
Add specific persons to Slack notification

### ISSUE THREAD

**Issue by erikoffereins** [grafana/grafana#16591]
**What would you like to be added**:
An option for slack notifications. So you can add specific people for some alerts.
**Why is this needed**:
For some temperature alerts we need one or two specific persons to notify. The other persons at the channel do not have to be notified.
For now if you place the @ at the message it is not working

![alerting issue](https://user-images.githubusercontent.com/11329955/56118112-ea61e600-5f69-11e9-9d8b-fe8786a3f9b0.jpg)

**Comment by Lusitaniae** [comment]
You need to specify the userid instead of username

https://stackoverflow.com/a/36463098/634577

**Comment by erikoffereins** [comment]
@Lusitaniae That's not working unfortunately.
He still sends the @ in plain text

**Comment by andreykaipov** [comment]
Hi @erikoffereins - unfortunately I can't reproduce what you're seeing. The tag seems to work on both the mention field of the notification channel and on the message body of the alert for me. 

![image](https://user-images.githubusercontent.com/9457739/57339847-3d5e3180-7101-11e9-9ea1-2889e5604171.png)

Maybe you have a hidden whitespace character or something like that preventing Slack from tagging the person correctly? Can you try creating a separate notification channel for your users and tag them in the mention field to see if that works?

**Comment by erikoffereins** [comment]
Heey @andreykaipov,
May I ask you how you send the tag?
With just the name of the person? Or the UserID

**Comment by andreykaipov** [comment]
We just use the usernames @erikoffereins. 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/9457739/57407562-72c25800-71b1-11e9-97c9-b369b0f58ea6.png">

Slack's API recognizes both.

**Comment by erikoffereins** [comment]
@andreykaipov  Thanks for that!
But my idea was to put some people at the "Mention" field.
And for some alerts, specific people at the message field.
![Annotation 2019-05-17 085341](https://user-images.githubusercontent.com/11329955/57908897-8b9dce00-7881-11e9-8c14-c22fbb2f7b2f.jpg)

But in the message field everything is plain text

**Comment by aleks73337** [comment]
@erikoffereins, pleese write how you made it. I need it too)

**Comment by erikoffereins** [comment]
Because of no reply's I closed the ticket.
We made multiply notification channels for specific messages as workaround

**Comment by aleks73337** [comment]
Ok, thank you!

**Comment by fourirakbar** [comment]
hi @erikoffereins , is the problem not been able to mention the people in Slack been solved or not? bcs I also got this issue

**Comment by erikoffereins** [comment]
No it is not solved but the crew of Grafana ignored this ticket so we have a workaround and made more notification channels

**Comment by nandubatchu** [comment]
It worked for me (inside the alert body) when you use: 
```
<@MemberID>
```
instead of 
```
@username
```

**Comment by npepinpe** [comment]
`<@MemberID>` doesn't work for me in the alert body. Putting the ID in the notification channel's mention does however. I'd be interested if anyone knows how to add it on the message however (note that we're on the latest Grafana 7, so maybe this is fixed in 8?).

**Comment by NikhilShaw** [comment]
<@MemberID> in summary works for me. **make sure there's no new line in summary.** MemberID you can get from slack profile section

**Comment by Cosmicoppai** [comment]
https://api.slack.com/reference/surfaces/formatting#mentioning-groups
