### ISSUE TITLE
Label editing in legend

### ISSUE THREAD

**Issue by MMAThijssen** [grafana/grafana#16598]
Hello, 

I am working with Grafana using Postgres. I would like to manually rename the labels in the legend. I expected to do so using the alias/regex in add series overwrite, but this is not an option. This would be a useful function to me as I can't rename the labels in another way without having to do a great deal of work. 

Best,

**Comment by torkelo** [comment]
You do this using the alias field in the query view

**Comment by MMAThijssen** [comment]
I want to rename each separate label in the legend. This cannot be done with the alias field in the query view.

**Comment by torkelo** [comment]
no, that you need to do in the query
