### ISSUE TITLE
Grafana 2.0 - Icons don't seem to work

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#1659]
It would seem the icons (fontawesome icons I believe) are not working for me.  I have seen similar behavior in the past with glyph icons and it seems like this is almost always related to a missing mime type.  However, since this provides a standalone web server, I'm not sure if that's the case.  I installed using the .rpm on CentOS 6.5.

![screen shot 2015-03-30 at 10 54 45 am](https://cloud.githubusercontent.com/assets/1132262/6901665/00642894-d6cc-11e4-92a8-82495991a0b6.png)

**Comment by calebcall** [comment]
Looks like this is specific to Safari.  Just tested in Chrome and Firefox and they both work fine.

**Comment by torkelo** [comment]
Strange, what version of safari? The icons look fine on Safari 8.04 on mac.

Do you get the same when you test http://play.grafana.org ?

**Comment by torkelo** [comment]
Can you double check that safari is able to access the woff font file? (enable safari develop menu)

**Comment by calebcall** [comment]
Hmm, weird.  I can see play.grafana.org no problem.  It's Safari 8.0.4.  Using the inspector, I don't even see a request for the .woff file.  However, looking in Firebug or Chrome Tools, I do see it there.  My Web Inspector doesn't report any errors or warnings.

Not sure if it means anything, but I just changed my user agent to Firefox - Mac while in Safari and the icons work fine.  I also see the .woff file in the inspector being requested and served fine.  I wonder if this is something to do with Safari serving that file over port 3000?  Let me see if I change that if it makes a difference.

**Comment by calebcall** [comment]
Yep, I changed it to run on port 8080 and now the icons work fine.  I've seen other things like this, Safari is trying to be too secure :) Weird it would serve some content over 3000 but not all, in the past when I've seen this, it's been that it wouldn't serve any content over the non-standard port.  This is because it thinks port 3000 is supposed to be hbci (whatever hbci is???) which isn't supposed to be web content.

**Comment by torkelo** [comment]
It is strange, I just tried this on mac with the default port 3000 in safari and the icons worked. Some plugin or security setting you have?

**Comment by phil-cci** [comment]
I'm having the same issue with the latest beta and Safari, change the port to something other than 3000 and the icons show up, 3000 they do not.   I can't find any specific settings in Safari which would affect this.

**Comment by torkelo** [comment]
change the port

**Comment by garthk** [comment]
I was still seeing this with ports 3001 or 8000, Safari 8.0.6, and Grafana 2.1.0-pre1. Disabling the AdBlock extension fixed the problem.

**Comment by huhongbo** [comment]
safari 8.0.6 has the same problem, seems disable evernote extension and AdBlock works fine

**Comment by pgraluk** [comment]
Hello Guys, can Grafana can be integrated on an existing Apache server or it works just as standalone on port 3000?

**Comment by calebcall** [comment]
I'm sure you could use proxy pass and front this with Apache.

**Comment by AlekSi** [comment]
Just happened with me. Disabled all extensions, cleared cached, reloaded – icons showed up. Enabled all extensions, cleared cache, reloaded – icons still there. Cleared, restarted, etc. – they are still there.
¯\_(ツ)_/¯
