### ISSUE TITLE
expose current org_name as a dashboard variable

### ISSUE THREAD

**Issue by mxk1235** [grafana/grafana#16606]
**What would you like to be added**:

I would like to be able to show org_name in Dashboard and Panel titles, and possibly in text panels.  I think you could expose it via a builtin variable, e.g. [[__orgName]]

**Why is this needed**:

currently we can only tell the current organization by looking at the Switch orgs menu, and if the user is a member of only one, the org name isn't shown at all.  It's inconvenient and not apparent what org the user is looking at.

**Comment by anirudh-ramesh** [comment]
+1

**Comment by torkelo** [comment]
added inn 6.7 , ${__org.name}
