### ISSUE TITLE
Republish @grafana/ui npm package

### ISSUE THREAD

**Issue by chrnorm** [grafana/grafana#16608]
I'm experimenting with developing React Grafana plugins. The latest version of @grafana/ui on npm is `6.0.1-alpha.0`, but there are some breaking changes in Grafana 6.1 concerning plugin panel types and interfaces. Publishing @grafana/ui v6.1.x should fix this.

**Comment by ypli0629** [comment]
+1

**Comment by tinder-ubhatnagar** [comment]
Any news on this?

**Comment by tinder-ubhatnagar** [comment]
`6.2.0-alpha.0 • Public • Published 3 days ago`

**Comment by tinder-ubhatnagar** [comment]
I think this can be closed now!

**Comment by chrnorm** [comment]
Closing as 6.2.0-alpha.0 has been published on npm!
