### ISSUE TITLE
Labels disappear in 6.1 with default dimension and no alias

### ISSUE THREAD

**Issue by sethbacon** [grafana/grafana#16605]
**What happened**:
Upgraded from 6.02 to 6.1.1 and Default Dimension labels disappeared from graph.

**What you expected to happen**:
No change

**How to reproduce it (as minimally and precisely as possible)**:
Query Inspector:
`{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1555279698031",
      "to": "1555366098031",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 120000,
          "maxDataPoints": 960,
          "datasourceId": 17,
          "type": "timeSeriesQuery",
          "dimensions": {
            "LoadBalancer": "app/ProdawsbrutoDMZ/blahblahblahA"
          },
          "expression": "",
          "highResolution": false,
          "id": "",
          "metricName": "RequestCount",
          "namespace": "AWS/ApplicationELB",
          "period": "60",
          "region": "us-east-1",
          "returnData": true,
          "statistics": [
            "Sum"
          ],
          "alias": ""
        },
        {
          "refId": "B",
          "intervalMs": 120000,
          "maxDataPoints": 960,
          "datasourceId": 17,
          "type": "timeSeriesQuery",
          "dimensions": {
            "LoadBalancer": "app/Prod-DigitalMarine-WebDMZ/blahblahblahB"
          },
          "expression": "",
          "highResolution": false,
          "id": "",
          "metricName": "RequestCount",
          "namespace": "AWS/ApplicationELB",
          "period": "60",
          "region": "us-east-1",
          "returnData": true,
          "statistics": [
            "Sum"
          ]
        },
        {
          "refId": "C",
          "intervalMs": 120000,
          "maxDataPoints": 960,
          "datasourceId": 17,
          "type": "timeSeriesQuery",
          "dimensions": {
            "LoadBalancer": "app/albe-track-pro-app-use1/blahblahblahC"
          },
          "expression": "",
          "highResolution": false,
          "id": "",
          "metricName": "RequestCount",
          "namespace": "AWS/ApplicationELB",
          "period": "60",
          "region": "us-east-1",
          "returnData": true,
          "statistics": [
            "Sum"
          ]
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {},
        "series": [
          {
            "name": "",
            "points": [
              [
                0,
                1555279680000
              ],
              [
                ..... truncated
              ],
              
            ],

            "tags": {
              "LoadBalancer": "app/albe-track-pro-app-use1/blahblahblah"
            }
          }
        ],
        "tables": null
      }
    }
  }
}`
**Anything else we need to know?**:
Issue Present in 6.1.1, 6.1.2, and 6.1.3
**Environment**:
- Grafana version: 6.1.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 10 1809 Chrome
- plugins: 
briangann-datatable-panel
grafana-clock-panel
grafana-piechart-panel
grafana-polystat-panel
grafana-worldmap-panel
natel-plotly-panel
raintank-worldping-app
simpod-json-datasource
sni-pnp-datasource
snuids-trafficlights-panel
![image](https://user-images.githubusercontent.com/14307877/56170469-e8664a00-5f9e-11e9-8cb2-4bbd5385eed3.png)
![image](https://user-images.githubusercontent.com/14307877/56170495-0af86300-5f9f-11e9-95db-0b29c4818033.png)

**Comment by torkelo** [comment]
@mtanda any ideas?

**Comment by mtanda** [comment]
@torkelo may be this?
https://github.com/grafana/grafana/pull/15685

**Comment by utkarshcmu** [comment]
Let me try to replicate the issue and see whats the underlying rootcause this issue in the PR #15685

**Comment by andrewmcgilvray** [comment]
Looks like we have lost the default alias that used to be set here : https://github.com/grafana/grafana/pull/15685/files#diff-ed5cc68bef51197743c5863b078db25bL500

**Comment by sethbacon** [comment]
This is breaking our series overrides, otherwise it would be a minor annoyance.

**Comment by utkarshcmu** [comment]
I think this above PR should fix the issue!
