### ISSUE TITLE
json-tree does not render in versions >=6.1.0

### ISSUE THREAD

**Issue by SzeMengTan** [grafana/grafana#16607]
**What happened**:
When running the Echo Service example included with the AJAX panel plugin, which uses the \<json-tree\> directive, nothing is rendered on the panel when the Display Mode is set to JSON Tree. The panel renders correctly with other display modes such as Preformatted Text. 

**What you expected to happen**:
The JSON associated with the echo request should have been rendered as an interactive tree.

**How to reproduce it (as minimally and precisely as possible)**:
Install AJAX panel plugin, add it to a dashboard and run the second example (Echo Service) with the default Display Mode. Panel will be blank. Verify that changing the display mode to Preformatted Text works as expected.

**Anything else we need to know?**:
This behavior started with version 6.1.0

**Environment**:
- Grafana version: 6.1.0, 6.1.1, 6.1.2, 6.1.3
- Data source type & version: None
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 running Virtual Box 5.2.26 and Chrome 73.0.3683 (64 bit)
- Grafana plugins: ryantxu-ajax-panel 0.0.6
- Others:

**Comment by torkelo** [comment]
Thanks for reporting this, we did not know this was used by external plugins. It was not being used internally by Grafana as we had moved all uses of it to React. Will try to add it back in include this in a patch release.

**Comment by torkelo** [comment]
strange, we did not remove that directive, so not sure why it's not working. 

@ryantxu any ideas?

**Comment by bergquist** [comment]
do we know why? Would be nice to include a patch in 6.2-beta1

**Comment by bergquist** [comment]
ping @ryantxu

**Comment by ryantxu** [comment]
I'm stumped on how to fix it -- I think it is something deep in webpack :(

The class still exists in our build, but the behavior is reproducible in any angular control
