### ISSUE TITLE
Grafana 2: Ability to limit google-authenticated users by email address or domain

### ISSUE THREAD

**Issue by ohTHATaaronbrown** [grafana/grafana#1660]
I'd like to use google OAuth to secure my grafana 2 installation, but only want to allow users from my google apps domain.  I don't see a means of limiting *which* google auth users can access grafana.  Without this capability, the grafana 2 google oauth support is largely useless to me.

I'd like to be able to specify something like this in the `auth.google` section, and then have grafana only allow authenticated users from google whose email addresses are within one of the listed domains:

```
## Google Apps Domains to allow authentication for (could default to * to allow any email address)
 google_apps_domains = [
     "mydomain.com"
 ]
```

The bitly google_auth_proxy which I use to secure my existing grafana 1/graphite install does this well.  https://github.com/bitly/google_auth_proxy

**Comment by torkelo** [comment]
@ohTHATaaronbrown I ment to add this, but forgot / ran out of time. But should be quick. Will add fix this for RC1 (or beta2 depening on number of issues in beta1)

**Comment by ohTHATaaronbrown** [comment]
:+1: Cool!

**Comment by torkelo** [comment]
```
[auth.google]
enabled = false
client_id = some_client_id
client_secret = some_client_secret
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
allowed_domains = mycompany.com othercompany.com
```

**Comment by ohTHATaaronbrown** [comment]
@torkelo awesome!

Is that a space-delimited list?

**Comment by torkelo** [comment]
yes
