### ISSUE TITLE
Grafana not sending alerts even test rule is firing true

### ISSUE THREAD

**Issue by NaveenKumarp1539** [grafana/grafana#16618]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by NaveenKumarp1539** [comment]
![image](https://user-images.githubusercontent.com/40016139/56201804-48bcc080-605f-11e9-891a-212dbef5935c.png)

Dashboard

![image](https://user-images.githubusercontent.com/40016139/56201947-95080080-605f-11e9-94bc-b3691d778215.png)


State is pending even after 3m

**Comment by SillyHenry** [comment]
meet the same issue

**Comment by torkelo** [comment]
Test rule does not trigger notifications, only for showing the firing: true/false state, and how that result was calculated

**Comment by dreamleilei** [comment]
meet same issue ,

**Comment by huaphuoctruong** [comment]
But the alert task should raise the notification at the time the test rule is met @torkelo
