### ISSUE TITLE
Apache 2.4 ProxyPass seems to break Grafana 2.0B1

### ISSUE THREAD

**Issue by bcatubig** [grafana/grafana#1661]
Hi,

I'm trying to setup ProxyPass with Grafana. Here is my Apache config and the output I get from the web browser.

I am running the deb binary on Ubuntu 14.04

<pre>
ProxyRequests Off
ProxyPass /stats http://localhost:3000/
ProxyPassReverse /stats http://localhost:3000/
</pre>

I get the following when trying to access the application. Am I doing something wrong? Thanks!
![grafana](https://cloud.githubusercontent.com/assets/1383904/6903985/77d0b80e-d6e3-11e4-941e-b459df82ae8c.PNG)

**Comment by torkelo** [comment]
If you use a reverse  proxy and put grafana behind a subpath  you need to change root_url  config. Read the configuration guidedocsmore details

**Comment by bcatubig** [comment]
Hey Torkelo,

Saw that note right as I posted this. Was able to get it working in apache.

I just did a 301 redirect - /stats/ seemed to work while /stats didn't. Here is my configuration.

#### Grafana.ini
    root_url = %(protocol)s://%(domain)s:%(http_port)s/stats/

#### Apache config
<pre>
 Redirect 301 /stats http://server1.example.com/stats/
        <Location "/stats/">
          ProxyPass http://server1.example.com:3000/
          ProxyPassReverse http://server1.example.com:3000/
        </Location>
</pre>
