### ISSUE TITLE
Evaluate alert rule on historical data

### ISSUE THREAD

**Issue by k-meister** [grafana/grafana#16616]
**What would you like to be added**:
It would be nice, if you could evaluate alert rule on historical data, to see points in time when it would have gone to ALERTING/OK states, have you set it up current way earlier

**Why is this needed**:
In general, it will help not to wait for an outages to make sure you have an alerts that catch them :)
For example, the feature would be helpful in situations when you survived some outage, and monitoring didn't do well at the right time. So you come to grafana to tune/create an alert to catch this up next time.
Having such a feature, you could make sure alert will work on similar issue next time.
Also, when trying to make alert not flap, it would be very handy to try different rule conditions on a same noisy pattern to make the best choice.

Sorry if I missed some feature request or way to do this with existing functionality,
Thanks for a great product!

**Comment by ewenerlal** [comment]
has this ever been implemented?

**Comment by armandgrillet** [comment]
An implementation will start in the coming weeks: https://github.com/grafana/grafana/issues/53443
