### ISSUE TITLE
Grafana public/ folder is 404 when root_url is used

### ISSUE THREAD

**Issue by kesor** [grafana/grafana#16613]
**What happened**:
Grafana is configured with `root_url` other than `/` and it fails to find the javascript and css files in its `public/` folder.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start Grafana
```
docker run -ti --rm --name=grafana -e GF_SERVER_ROOT_URL='%(protocol)s://%(domain)s/app/grafana' -p 3000:3000 grafana/grafana
```

2. Access using a browser `http://0.0.0.0:3000/app/grafana`

**Environment**:
- Grafana version: 6.1.3

Relevant logs:
```
INFO[04-16|08:00:50] HTTP Server Listen                       logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/app/grafana socket=
INFO[04-16|08:00:56] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/app/grafana status=404 remote_addr=172.20.0.1 time_ms=2 size=22016 referer=
INFO[04-16|08:00:56] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/app/grafana/public/build/grafana.dark.d10a9a685fb17efa4c7b.css status=404 remote_addr=172.20.0.1 time_ms=2 size=22016 referer=http://0.0.0.0:3000/app/grafana
INFO[04-16|08:00:56] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/app/grafana/public/build/vendor.d10a9a685fb17efa4c7b.js status=404 remote_addr=172.20.0.1 time_ms=2 size=22016 referer=http://0.0.0.0:3000/app/grafana
INFO[04-16|08:00:56] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/app/grafana/public/build/app.d10a9a685fb17efa4c7b.js status=404 remote_addr=172.20.0.1 time_ms=2 size=22016 referer=http://0.0.0.0:3000/app/grafana
INFO[04-16|08:00:57] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/app/grafana/public/build/vendor.d10a9a685fb17efa4c7b.js status=404 remote_addr=172.20.0.1 time_ms=3 size=22016 referer=http://0.0.0.0:3000/app/grafana
INFO[04-16|08:00:57] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/app/grafana/public/build/app.d10a9a685fb17efa4c7b.js status=404 remote_addr=172.20.0.1 time_ms=1 size=22016 referer=http://0.0.0.0:3000/app/grafana
```

**Comment by torkelo** [comment]
You need to use reverse proxy to use a sub path

**Comment by kesor** [comment]
@torkelo why wouldn't you fix this? there are dozens of people who got bit by this bug, and to all of them you have the same answer: "Ah, you don't use a reverse proxy? You **must** get one."

Grafana does "work", its just the public assets are broken because these do not respect the `subUrl` provided in `root_url`.

All the other people suffering from the same thing:
- https://github.com/grafana/grafana/issues/16135
- https://github.com/grafana/grafana/issues/15959
- https://github.com/grafana/grafana/issues/13955
- https://github.com/grafana/grafana/issues/13707
- https://github.com/grafana/grafana/issues/13459
- https://github.com/grafana/grafana/pull/8208
- https://github.com/grafana/grafana/issues/5478
- https://github.com/grafana/grafana/issues/4305
- https://github.com/grafana/grafana/issues/2340
- https://github.com/grafana/grafana/issues/2066
- https://github.com/grafana/grafana/issues/1998
- https://github.com/grafana/grafana/issues/1930

**Comment by torkelo** [comment]
Is there a use case to use a subpath without a reverse proxy? 

> @torkelo why wouldn't you fix this?  

Time is a limited resource and no pull requests for a new subpath feature has been opened or even a feature request proposed. 

But the docs do mention this but could be made more clear I think:
https://grafana.com/docs/installation/configuration/#root-url

**Comment by kesor** [comment]
@torkelo the problem is not a reverse proxy, the problem is the mandatory requirement for *rewrite rules* in the reverse proxy. I would expect that if `root_url` is set to a value that includes a subpath, like `localhost:3000/grafana` then Grafana would "just work" and not mandate to install another component into the mix (a reverse http proxy) to make it to work.

Explained in simple terms - I am naturally using a proxy that adds multiple applications, each on its own path - and one of them happens to be Grafana. All the other applications do not need rewrite rules, only Grafana requires the proxy to rewrite - and this means that I must add yet another reverse proxy behind the existing proxy we are already using.

The actual technical problem I have, is that we are using a Kubernetes Nginx Ingress rule to combine multiple applications, and all of them can be configured without rewrite rules with except Grafana.

**Comment by kesor** [comment]
In short, I would expect the OP to "just work" and not 404 on css and javascript.

`docker run -ti --rm --name=grafana -e GF_SERVER_ROOT_URL='%(protocol)s://%(domain)s/app/grafana' -p 3000:3000 grafana/grafana`

**Comment by torkelo** [comment]
ok, please open a feature request for a subpath setting then, first time I have heard of this feature requests. All other web apps I have used required a rewrite for sub path in a reverse proxy setting.

**Comment by torkelo** [comment]
But thanks for the feedback! think it makes sense but think it might require a new setting and some complex logic to be backward compatible
