### ISSUE TITLE
Elasticsearch datasource alerting does not return the alias anymore

### ISSUE THREAD

**Issue by buroa** [grafana/grafana#16624]
We send all alerts from Grafana to our HA Alertmanager cluster. We used to be able to group these alerts by the alias on the graph, but now it's not sending and all we get is the metricId ... which is not what we want to group by since most of the time it's just 1.

Can this please be fixed?

**Comment by torkelo** [comment]
Can you show the Elasticsearch query and the response from your Elasticsearch query? Did you upgrade Elasticsearch recently?

**Comment by buroa** [comment]
I figured it out, but ran into yet another issue.

https://github.com/prometheus/alertmanager/issues/1839

I think this can be solved by adding `k = strings.Replace(k, ".", "_", -1)` to https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/alertmanager.go#L97

**Comment by buroa** [comment]
I can confirm this does fix the issue.

**Comment by bergquist** [comment]
@buroa any chance you want to open a pull request with that change? 

You should have the credit for finding the problem and solution :)
