### ISSUE TITLE
Allow Grafana to be served with a URL path prefix, without a requirement for a rewriting proxy like nginx

### ISSUE THREAD

**Issue by kesor** [grafana/grafana#16623]
**What would you like to be added**:
Allow Grafana to run using a real subpath, without the requirement for a mandatory path-rewriting proxy. https://github.com/grafana/grafana/issues/16613

**Why is this needed**:

* First, so that this would work - `docker run -ti --rm --name=grafana -e GF_SERVER_ROOT_URL='%(protocol)s://%(domain)s/app/grafana' -p 3000:3000 grafana/grafana`

* In some settings, like for example Ingress in Kubernetes, it is useful to not force the proxy to become a rewriting proxy but rather allow each application have its own path prefix and simply serve all its content from that path.

**Comment by jan25** [comment]
@torkelo would you know if someone is already working on this issue? Otherwise i can take a look into this

**Comment by torkelo** [comment]
No one is working on it, any help is appreciated

**Comment by cupen** [comment]
en... I meet the same problem, this is really strangely.
I think this feature(fix it) is GOOD!  @jan25  Do you working for it? if not, I will have a try on this weekend.

**Comment by cupen** [comment]
@jan25  oh, yes.  I get the PR, thank you.

**Comment by djuarezg** [comment]
This is nice, but some URLs are not fixed, such as when adding a datasource. It omits the sub_path.

**Comment by marefr** [comment]
@djuarezg would you please open a new bug report for this including details of how to reproduce it, thanks.

**Comment by prathamesh-gharat** [comment]
From other guides I have noticed that when you want to serve Grafana from a sub-directory you also need to set `serve_from_sub_path = true` .. I didn't notice the OP using a similar syntax.

Did a search on the Grafana repo and found [this](https://github.com/grafana/grafana/blob/4e3ff19689963bcf1e980a851ebc142b913675d8/devenv/docker/blocks/traefik/docker-compose.yml
).
So the OP also needs to try adding the following to the `docker run` command?
```
-e `GF_SERVER_SERVE_FROM_SUB_PATH=true`
```

**Comment by tbernacchi** [comment]
Using this [stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) my environment I did this:

```
kubectl set env deployment/my-kube-prometheus-stack-grafana -n monitoring GF_SERVER_SERVE_FROM_SUB_PATH=true
kubectl set env deployment/my-kube-prometheus-stack-grafana -n monitoring GF_SERVER_ROOT_URL=/grafana
```

And on my Ingress I just kept `path: /grafana` without `rewrite-target`.

Works well for `https://mydomain.com/grafana` =)
