### ISSUE TITLE
Windows builds?

### ISSUE THREAD

**Issue by kpfaulkner** [grafana/grafana#16620]
Hi

Just wondering if there are some tips for getting this to build in Windows. Any particular gcc version etc?

Although tempted to just build in WSL, I'd prefer to do native if possible. 

Thoughts?

Ken

**Comment by torkelo** [comment]
you can see a bit here in our old windows CI script:
https://github.com/grafana/grafana/blob/v6.0.0/appveyor.yml#L15

you need Go, node etc, and to build the go backend you need mingw64  in order to compile the go modules that have C code
