### ISSUE TITLE
[QUESTION]Get a list of PanelID which belongs to a dashboard

### ISSUE THREAD

**Issue by RASAMIZANANY** [grafana/grafana#16628]
Is there an API or a way to get all the panelId value from a dashboard? I have read the documentation but not able to find any except the API api/alerts which returns the value of panelId but it has to possess an alert.
Thank you

**Comment by torkelo** [comment]
Get dashboard by id 
https://grafana.com/docs/http_api/dashboard/#get-dashboard-by-uid 

in the dashboard json you find panels array that contains the panel ids
