### ISSUE TITLE
Grafana 2.0: CentOS 7: failed to write pid file

### ISSUE THREAD

**Issue by KuchenKerze** [grafana/grafana#1663]
Hi,

I am getting the following error after install the latest rpm file:
Failed to write pidfile%!(EXTRA *os.PathError=open /var/run/grafana.pid: permission denied)

/var/run is handled by systemd. Is this just a problem on my system?

**Comment by torkelo** [comment]
Strange, it works in a docker centos7 container. I have yet to add any support for systemd, but should not init.d scripts be backward compatible?

**Comment by torkelo** [comment]
I just spun up clean digital ocean centos7 droplet and tried the rpm package. Installed via `rpm -Uvh ...` and it worked, the pid file was created etc. 

Is systemd enabled by default in centos7 or are there special builds for centos7 with systemd?

**Comment by KuchenKerze** [comment]
My system is hosted on DigitalOcean. I will spend some time this evening to find out what is happening there.

**Comment by KuchenKerze** [comment]
The daemon is starting when I change the pidfile to another directory (e.g.. /tmp/grafana.pid).
But even then I systemd thinks that grafana is not running:
Loaded: loaded (/etc/rc.d/init.d/grafana)
   Active: failed (Result: resources) since Tue 2015-03-31 19:59:00 CEST; 4s ago
  Process: 13892 ExecStart=/etc/rc.d/init.d/grafana start (code=exited, status=0/SUCCESS)

But it is running and I can access the web ui:
Listen: http://0.0.0.0:3000

Strange...

**Comment by torkelo** [comment]
And this is a vanilla centos 7 digital ocean image, have you installed any extra packages or upgrades?

**Comment by KuchenKerze** [comment]
I just tried this on a complete new and fresh DigitalOcean CentOS 7 installation. With the exact same result: http://pastebin.com/fsPePk1c

**Comment by torkelo** [comment]
@KuchenKerze ok, I used `service grafana start` which works. It is when using the `systemctl start grafana` that it does not work. Not sure why.

**Comment by torkelo** [comment]
Fixed in  #1758
