### ISSUE TITLE
Prometheus data-source HTTP Access mode Server (default) not being respected

### ISSUE THREAD

**Issue by clebergeru** [grafana/grafana#16633]
**What happened**:

I've tried to configure a new Prometheus Datasource using the HTTP access mode as `Server (Default)` pointing to a Prometheus server that has an IP origin restriction. I've configured the Prometheus only to accept connections from Public IP of the server where Grafana runs. When I tried to save it, I got a 403 Error. I've found on the logs that the IP source was from my office and not from the Grafana server. It was like the requests are made from my browser. If I remove the blocking rule, it works.

**What you expected to happen**:
Requests to the Prometheus Datasource made through the Grafana and not from my Browser.

**How to reproduce it (as minimally and precisely as possible)**:

1 - A Prometheus data source with IP restrictions
2 - A Grafana server running  from where you had allowed on Prometheus
3 - Trying accessing Grafana from a different IP and adding the Prometheus data source in mode `Server ( Default )`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.1.4
- Data source type & version: Prometheus 
- OS Grafana is installed on: Grafana Docker container `grafana/grafana:6.1.4`
- User OS & Browser: Ubuntu 18.04 / Google Chrome 
- Grafana plugins: 
```
jdbranham-diagram-panel,grafana-clock-panel,grafana-piechart-panel,grafana-simple-json-datasource,vertamedia-clickhouse-datasource,fzakaria-simple-annotations-datasource,grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel,novalabs-annotations-panel,raintank-worldping-app,alexanderzobnin-zabbix-app,percona-percona-app,cloudflare-app,raintank-kubernetes-app
```

**Comment by torkelo** [comment]
Can you open chrome dev tools network tab and try to find a request to prometheus? What is the url? 

We have no other reports that this setting is not doing what it should so it's probably something with your config / setup.

**Comment by clebergeru** [comment]
@torkelo Yes! off course. 

URL: https://prometheus.k8s-xxxx.xxxx.xxxx.xxxx (It is a valid public FQDN)

This is my Ingress annotation (I use Nginx-Ingress on Kuberbetes):
```nginx.ingress.kubernetes.io/whitelist-source-range: 54.87.58.248/32,18.235.98.121/32,18.235.30.208/32,177.81.210.92/32``` 

The last IP address is from my office. When I add it on the rule it works.

Testing without my office IP on the rule:
![403](https://user-images.githubusercontent.com/40580433/56290420-7d7d5600-60f9-11e9-9a0e-8b5923a9cab2.jpeg)

Testing with the IP:
![200](https://user-images.githubusercontent.com/40580433/56290433-840bcd80-60f9-11e9-9b6c-a9b607deedf5.jpeg)

Nginx log of the request:
```
Apr 17 09:53:25 nginx-ingress-controller-7877c56bb5-jmp86 nginx-ingress-controller 177.81.210.92 - [177.81.210.92] - - [17/Apr/2019:12:53:25 +0000] "GET /api/v1/query?query=1%2B1&time=1555505604.399 HTTP/1.1" 403 184 "https://xxxxx.xxxxx.xxxx.xxx/datasources/edit/25" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" 806 0.000 [monitoring-prometheus-k8s-9090] - - - - 39548c7c9336e7ba140d2fe198de855e
```

**Comment by torkelo** [comment]
As you can the request is not going directly to your prometheus `https://prometheus.k8s-xxxx.xxxx.xxxx.xxxx/`

But is going to the grafana server api proxy route, which will then forward (proxy) the request to your prometheus url 

The proxy will set the X-Forwarded-For header, so your nginx might look at that and use that as client IP
https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by mohsen0** [comment]
Relevant to this case: https://stackoverflow.com/questions/36268272/nginx-allowing-origin-ip

**Comment by edijsdrezovs** [comment]
Having completely the same issue. `X-Forwarded-For` header is being used on ingress nginx side. Any ideas?

**Comment by naughtyGitCat** [comment]
So is there any configuration entry in grafana server ini file or frontend datasource config editor, to set the datasource do not forward client IP,  and using the grafana server IP  send to the datasource service?

Currently, we can do nasty work to set XFF header with the grafana server IP  in datasource config editor, but this is inconsistent and fragile.  When the grafana server changes host or changes IP, the frontend page will crash on data fetching

@torkelo
