### ISSUE TITLE
Repeat singlestat drilldown from sql query doesn't pass current panels variable

### ISSUE THREAD

**Issue by mikelindsay** [grafana/grafana#16634]
****What happened**:**
When clicking the single stat it redirects you to the correct drill down dashboard but passes the entire variable instead of just the variable for that one specific panel

variable name is servers with a sql query pulling server names
theres a repeating single stat panel for each server that has another query that returns 0,1,2 for current status

**What you expected to happen**:
When attempting to go into the drill down it passes all the servers instead of  just the one for that one panel.

var-servers=server1,server2,server3

**How to reproduce it (as minimally and precisely as possible)**:
try passing multiresult variables from SQL in a single stat panel

**Anything else we need to know?**:
n/a

**Environment**:
- Grafana version: 5.2.1
- Data source type & version: SQL Server 2016
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, Chrome
- Grafana plugins: n/a
- Others:n/a

**Comment by torkelo** [comment]
Please upgrade to grafana v6.1 ( or latest v5.4) this should be fixed there

**Comment by mikelindsay** [comment]
I confirmed this was the resolution
