### ISSUE TITLE
Make LegendTable header fixed when scrolling

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#16630]
Graph legend component is wrapped with custom scrollbar. When scrolling long list of series in legend it would be good to make the table header fixed, so that the information about what is the value in a given column is accessible.

![image](https://user-images.githubusercontent.com/2376619/56226439-7f9cd180-6073-11e9-8f9f-35b4cf00d575.png)

**Comment by peterholmberg** [comment]
@dprokop how do you want handle this with graph ng coming along?

**Comment by dprokop** [comment]
@peterholmberg maybe, it depends on how we approach the legend in general in the visualizations. I will close this for now as I have not seen any complaints about current behavior.
