### ISSUE TITLE
[Bug] Template variable on row panels dont update on time range change

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#16639]
Grafana v.5.4.3
Datasource - InfluxDB

![image](https://user-images.githubusercontent.com/35651463/56267494-98a59100-610c-11e9-98c5-dcdae4a14534.png)

I am using the same template variable. Why is the row value not getting updated?

**Comment by torkelo** [comment]
are you using a template variable in the row title?  Is the variable configured as Refresh on time range change? 

Try upgrading to v6.1 we have fixed a few issues with template variables in row titles since v5

**Comment by debmalyapan53** [comment]
Thanks @torkelo, the issue seems to be resolved in v6.1+
