### ISSUE TITLE
login.OAuthLogin(get info from google)

### ISSUE THREAD

**Issue by danielvll** [grafana/grafana#16636]
**What happened**:
Google OAuth from Grafana has broken.

Trying to login shows:
"Server side error :(
login.OAuthLogin(get info from google)"

**What you expected to happen**:
Login is working as before.

**How to reproduce it (as minimally and precisely as possible)**:
Try to login using Google OAuth.

**Anything else we need to know?**:
Log lines:
t=2019-04-16T17:34:12+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/google status=302 remote_
addr=127.0.0.1 time_ms=0 size=470
t=2019-04-16T17:34:13+0000 lvl=dbug msg="OAuthLogin Got token" logger=context userId=0 orgId=0 uname=
t=2019-04-16T17:34:13+0000 lvl=eror msg="login.OAuthLogin(get info from google)" logger=context userId=0 orgId=0 uname= error="invalid character '<
' looking for beginning of value"
t=2019-04-16T17:34:13+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/google status=500 remote_
addr=127.0.0.1 time_ms=492 size=734

**Environment**:
- Grafana version: 4.3.2
- Data source type & version:
- OS Grafana is installed on: Ubuntu 14.04
- User OS & Browser: Ubuntu 14.04, Chromium 65.0.3325.181
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Please upgrade to a newer version of Grafana (v6.1 or v5.4),  

Works in v6.1 at least;
https://play.grafana.org/login 

and we have no reports of it not working in v5.4
