### ISSUE TITLE
Docs: Update images in getting started 

### ISSUE THREAD

**Issue by ZhuQinglei** [grafana/grafana#16642]
[Adding & Editing Graphs and Panels] Section, the screenshot displayed for editing graph is different from actual UI, the actual UI looks like this: 
![image](https://user-images.githubusercontent.com/16860302/56276493-2d23e980-6135-11e9-8a0b-5ff83e4c3960.png)

**Comment by oddlittlebird** [comment]
This is on the list

**Comment by oddlittlebird** [comment]
Fixed when we rewrote the Getting started section.
