### ISSUE TITLE
extremely slow scroll speed with firefox and "smooth scrolling" enabled

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#16647]
### !Update: this problem only occurs with Firefox Versions 65 and below, see comments!

**What happened**:
When browsing Grafana 6.x.x, I noticed that scrolling is extremely slow, like 1 pixel every mousewheel turn. More specifically, scrolling within a dashboard and scrolling in the "edit panel" mode are nearly unusable. Other scroll bars like the one in the dashboard list are working fine.

&rarr; Eventually, I found the reason: this only happens when the firefox setting "**smooth scrolling**" is enabled. When I disable this setting, everything works just fine.

**What you expected to happen**:
Scrolling everywhere should work normally everywhere, even with "smooth scrolling" setting enabled. This setting was enabled by default when I installed and updated firefox, so this really is an issue.

**How to reproduce it (as minimally and precisely as possible)**:
Enable "smooth scrolling" setting on firefox and scroll on dashboards or within the "edit panel" mode of a panel. The scrolling experience should be next-to-unusable. Disable the setting and scrolling should work fine again.

**Anything else we need to know?**:
The described bug appears on [play.grafana.org](http://play.grafana.org) as well so this is a general problem, not one of our Grafana installation.
I noticed this bug in firefox 63, 64 and 65.0.1. Trying the Chrome browser, I did not have any problems, even with the setting enabled, so this seems firefox-related.

**Environment**:
- Grafana version: 6.1.2
- Data source type & version: x
- OS Grafana is installed on: Red Hat Enterprise Linux 7
- User OS & Browser: Ubuntu 16.0.4 LTS, Firefox 65.0.1
- Grafana plugins: x
- Others: reproducable on play.grafana.org as well

**Comment by torkelo** [comment]
Do you get this on other sites? Firefox 66 & smooth scrolling on ubuntu 18 works fine

**Comment by sspieker** [comment]
@torkelo , I've had no problems so far on other sites with this option enabled.
Btw: I can confirm that **everything's working perfectly** with Firefox **66**.0.1 !
I don't know if this is something you're willing to investigate further... I'd think that there's a bunch of people who are still on Firefox 65 or even below.

Anyway, I'll edit this issue to reflect this new informations regarding the Firefox version.
Thank you so far!

**Comment by BenLutin** [comment]
Hello 
I have exactly the same issue as described by @sspieker. 
with Firefox ESR : 52.5.0 (32-bit) 

Noted just after Grafana upgrade from ver 5.2.2 to 6.1.4

But cannot upgrade Firefox as it's a corporate managed browser :-(  ...

**Comment by becon-cmichel** [comment]
Hey, I have the same problem with:
- Grafana 6.2.0-91846ebepre amd64
- Firefox 66.0.3 (64-bit) 
- Ubuntu 16.04.6 LTS.

If you need more info, just let me know.
Thanks

**Comment by torkelo** [comment]
We fixed an issue related to for Edge browser, can someone test this on latest stable 6.2.1 ?

**Comment by MadEngineX** [comment]
Hello! I had lags in Grafana. My solution was to put JavaScript addons and JavaScript-Java Bridge. 
Hope this helps someone.
