### ISSUE TITLE
Templating: Adding a regex or a whitelist of metrics to Ad hoc filters

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#16653]
**What would you like to be added**:
I would like to limit list of metrics in the ad-hoc dropdown list. 
![Screenshot_20190417_190032](https://user-images.githubusercontent.com/25184101/56303145-f86b5e80-6143-11e9-9962-b76c3b0f0565.png)

**Why is this needed**:
It would allow to replace bunch of variables by only one ad -hoc variable.

**Comment by Gauravshah** [comment]
I would think its a new variable filter type that allows you to force apply on all queries. Rather than limit ad-hoc.
For example I want a filter called "host" on 10 of my dashboards, want "country" as a filter but do not want to go in and update each of dashboards

**Comment by belm0** [comment]
Is the feature request more accurately:  "I would like to limit the list of *labels* in the ad-hoc dropdown list"?

**Comment by hugohaggmark** [comment]
Interesting, the RegEx would have to work on all levels(_`see picture below for what I mean by levels`_) of an ad hoc filter then, right? 
Is that very practical, to be honest that seems a bit hard for a user to understand and the tags need to be aligned/similar on all levels? Perhaps I'm not fully understanding the issue.

![image](https://user-images.githubusercontent.com/562238/98945130-5b74d100-24f2-11eb-85ae-abdffc76b775.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
