### ISSUE TITLE
Grafana playlist displays wrong annotations

### ISSUE THREAD

**Issue by tfortunatov** [grafana/grafana#16650]
My playlist has 2 dashboards.
The 1st one displays annotation for one service, the 2nd displays annotations for a different service.
If I start the playlist I see that the annotations don’t change no matter which dashboard is being displayed.
If I stop the playlist and go to the 2nd dashboard directly, I can see the correct annotations. Kindly suggest how I can see the correct annotations for each service during play run. 
Thanks

**Environment**:
- Grafana version: 5.4.2/6.1.4
- OS Grafana is installed on: CentOS 6
- User OS & Browser: MacOS Mojave 10.14.3, Safari/Firefox, Windows 10 IE

**Comment by torkelo** [comment]
Strange, unable to replicate. Can you show your annotation config. Also network requests being issued as the dashboard changes / loads.

**Comment by tfortunatov** [comment]
I created a playlist where we can reproduce this problem.
It has 2 dashboards, one with annotations to display deploys of a service called 1, and another with annotations for deploys of a service called 2.
However, once I start the playlist, both dashboards display the same annotations:
![screenshot-1](https://user-images.githubusercontent.com/11662296/56571671-1dd5ed80-65c6-11e9-910f-f3cd82e04db2.jpg)
![screenshot-2](https://user-images.githubusercontent.com/11662296/56571691-29c1af80-65c6-11e9-94ae-a217d5d6e984.jpg)

If I open the 2nd dashboard directly (without using the playlist), it displays the correct annotations:

![screenshot-3](https://user-images.githubusercontent.com/11662296/56571840-7907e000-65c6-11e9-846d-eedd6ad6bdd1.jpg)

**Comment by torkelo** [comment]
Can you try latest stable 6.2.1? think this has been fixed
