### ISSUE TITLE
Using the "Today" time view causes Prometheus to return empty result for instant queries

### ISSUE THREAD

**Issue by jranson** [grafana/grafana#16661]
**What happened**: When changing Grafana to the "Today" view, Prometheus returns the following response to all "instant" queries:
```
{"status":"success","data":{"resultType":"vector","result":[]}}
```
Which results in Grafana errors:
<img width="600" alt="Screen Shot 2019-04-17 at 6 09 05 PM" src="https://user-images.githubusercontent.com/883928/56329638-a45f7a80-6141-11e9-84b0-587afc8ffed2.png">

**What you expected to happen**: Prometheus should return a "good" value for instant queries when the time range in Grafana is set to Today, as shown in this "Last 12 Hours" view:
<img width="600" alt="Screen Shot 2019-04-17 at 6 08 45 PM" src="https://user-images.githubusercontent.com/883928/56329637-a45f7a80-6141-11e9-8b35-8ff0224a1817.png">

**How to reproduce it (as minimally and precisely as possible)**:  Create a chart that uses instant queries to Prometheus, such as the one in the screen shots, and then change the view to "Today" in the time range selector. In my example case, the instant query is `prometheus_build_info` populating a Singlestat with "version" selected for the column. The label, which normally displays the Prometheus version, will show "N/A" when in Today view.

**Anything else we need to know?**: When I use the Today view, Grafana is adding a time parameter onto all instant queries with an epoch time representing midnight my local time tomorrow, which at the time of this report is just over 5 hours into the future. Since Prometheus doesn't have data for the future, the returned result set is _always_ empty. You should use the current epoch timestamp for the instant `time` parameter (as is done with the relative-from-now views) instead of midnight tomorrow when in the Today view.

**Environment**:
- Grafana version: 6.1.4 (fef1733)
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: coreos? (Official Docker Container: grafana/grafana:6.1.4)
- User OS & Browser: MacOS 10.14.4, Chrome 73
- Grafana plugins: None
- Others: None

**Comment by jranson** [comment]
Awww yes a 5-digit palindrome issue id!

**Comment by torkelo** [comment]
Might be related to this line
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L150 

the end maybe should be query.end ?  Anyone want's to investigate?

**Comment by csesanram** [comment]
Does anyone have a solution for this issue?

**Comment by SuperQ** [comment]
> Prometheus should return a "good" value for instant queries when the time range in Grafana is set to Today.

I disagree with this statement. Prometheus and Grafana are doing exactly as requested. The difficulty is that you're selecting an instant query to get a single value, without providing any "over time" aggregation.

In the example, you're asking for the time range of "Today", but expecting to get only one value of "current". This is a mismatch between the reality of what you're asking and expecting.

If I request "Today", and want to know the Prometheus version, I have to think about if I want the current version, or the average version of the the day, or some other function. This needs to be solved in carefully selecting PromQL to return the expected results for any time range to be displayed for a dashboard view.

**Comment by jranson** [comment]
@SuperQ I am not sure that your view necessarily comports with how everyone might build and utilize dashboards, so hopefully I can add some perspective. It is not uncommon to have dashboards that include both time series sections, and real-time instantaneous data sections, such that the real-time sections are well-known to the dashboard users to always indicate the newest data,  irrespective of the time series range selected. Information like how many servers in the pool right now, # of concurrent connections, time since last key roll, # callers on hold, etc. That is a perfectly legitimate use case which is quite common. 

With respect to "Today" however, consider when you ask Alexa how is the weather today; the first word she responds with is "Currently".  Likewise, when I go to a dashboard and choose Today, how things are doing "Currently" is certainly the information i want and expect to have populated in the instant fields of my dashboard, especially when those fields populate just fine with this data in _every other view_.

So the final point is really about consistency. Any time I choose _any_ time range _except_ Today, the instant variables on my dashboard provide the latest real-time data by setting the time parameter to Now(). It is only when choosing Today that $time is set to Tomorrow@Midnight and breaks the view. Certainly every time range option should function the same way with respect to how it handles setting the instantaneous $time var?

**Comment by SuperQ** [comment]
> Certainly every time range option should function the same way with respect to how it handles setting the instantaneous $time var?

No, IMO, if you ask for the future, N/A is a valid answer. :smile: Snapping back instant queries is for sure the wrong thing to do, because it's inconsistent with the rest of the dashboard behavior, and very much unexpected when you use instant queries for the use case of producing graph-wide aggregations.

**Comment by davkal** [comment]
Here are some workarounds: 

For queries that guaranteed return only one timeseries, a query like  `avg_over_time(prometheus_build_info[$__range])` works fine as an instant query with a timepicker setting of `Today`.

If your query returns multiple series in a `over_time` query like above, you can use the new SingleStat (react) panel that can handle multiple series. (Need enable alpha panels in grafana ini.)

**Comment by davkal** [comment]
I'm closing this issue, since Grafana is doing the right thing, even though the it might not neatly fit all use cases. Let me know how the workarounds work for you.
