### ISSUE TITLE
Grafana 2.0b1 - 401 Unauthorized

### ISSUE THREAD

**Issue by renatoornelas** [grafana/grafana#1667]
I'm using a dashboard with 10s autoreload. 

After some time, I get that red indicator on every graph and this on the console:

Completed /api/datasources/proxy/1/render 401 Unauthorized

If I reload the browser, it starts working again for about 5 minutes.

**Comment by torkelo** [comment]
Ok, that is not good. Did you change any config around session management? Will investigate, but any info can be relevant in replicating.

**Comment by renatoornelas** [comment]
No changes to any config file.

I'm using the .deb in a Ubuntu 14.04 fully updated. 

I'm running ./grafana web (because the startup script isn't working, will open another ticket)

**Comment by renatoornelas** [comment]
Reinstalled the .deb pkg.. Will update if the error persists

**Comment by renatoornelas** [comment]
Same error as before:

2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 342.858µs
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 10.96366ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 20.704309ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 30.45315ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 46.114086ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 46.292496ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 31.483205ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 49.492839ms
2015/03/31 17:11:31 [I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 40.102786ms

No customizations to any config file.

**Comment by renatoornelas** [comment]
I'm capturing the traffic flowing between grafana and graphite.

When the error begins, I cannot see any request from grafana being forwarded to the graphite backend

**Comment by torkelo** [comment]
do you get this on a tv screen's computer or on your local computer? I did test a dashboard with 5s refresh for hours yesterday without replicating, but the experiment might have been disturbed by me starting stopping backend a few times during the day. have setup play.grafana.org dashboard on a seperate computer to refresh every 5s to see if I can replicate.

**Comment by renatoornelas** [comment]
I'm using safari, chrome on my computer and chromium on a raspberrypi 2. All browsers show the same behaviour

**Comment by renatoornelas** [comment]
When the error occurs, if I try to save the dashboard, I got an access denied too.

If you want, I can create an user for you on this server.

**Comment by torkelo** [comment]
Yes, please do, and send it to my github email, or pm me on irc.

**Comment by renatoornelas** [comment]
Email sent

**Comment by torkelo** [comment]
@calle if you can replicate this, can you check for any js errors in the chrome dev console?

**Comment by torkelo** [comment]
sorry, wrong issue

**Comment by jgerschk** [comment]
Don't see much of an update here -- however, I just started playing around with 2.0 b1, and I also can see the same errors in the logs as mentioned in the bug here.  Granted mine is coming from /api/datasources/proxy/1/series 401 Unauthorized, but seem related.

At one point, the whole working dashboard stopped working and as described above, just red icons.

In each case, if I hit F5 to refresh the browser it will work fine for a bit.

Replicate on IE 11, Chrome.

Still playing, if I find more data points will update, unless I see this issue closed by then.

**Comment by jgerschk** [comment]
I think you asked if there are any JS Error, while this is not a screenshot of that, as there is nothing in the JS Error tab, so I assume no error -- but this is what is being passed.  Nevertheless, it's a valid query because it works other times.

![04-01-2015 - 401 unauthorized a](https://cloud.githubusercontent.com/assets/7864285/6954348/46eb5e88-d896-11e4-99c7-f5acfb40a3d8.png)

**Comment by 12f-techops** [comment]
Also seeing this issue in 2.0.0b1.  Chome devtools:

TypeError: undefined is not a function
    at g (app.8ae07506.js:25)
    at Object.fn (app.8ae07506.js:25)
    at l.$digest (app.8ae07506.js:12)
    at l.$apply (app.8ae07506.js:12)
    at app.8ae07506.js:9
    at Object.e [as invoke] (app.8ae07506.js:9)
    at h (app.8ae07506.js:9)
    at Object.$ [as bootstrap] (app.8ae07506.js:9)
    at HTMLDocument.<anonymous> (app.8ae07506.js:17)
    at k (app.8ae07506.js:5)app.8ae07506.js:10 (anonymous function)
Failed to load resource: the server responded with a status of 401 (Unauthorized)
Failed to load resource: the server responded with a status of 401 (Unauthorized)
app.8ae07506.js:10 Objectconfig: Objectdata: Objectheaders: function (c){if(b||(b=db(a)),c){var d=b[Oc(c)];return void 0===d&&(d=null),d}return b}status: 401statusText: "Unauthorized"__proto__: Objectapp.8ae07506.js:10 (anonymous function)
app.8ae07506.js:10 Objectmessage: "Access denied"severity: "warning"__proto__: Object

**Comment by torkelo** [comment]
I think I have solved the biggest cause for this (Session timeout). Now when there is a 401 the frontend will in the background call /api/login/ping which will login/create a new session from the remember me cookie, it will then retry the data source request one more time. So there should not be any visible error icons in the dashboard (not even for one refresh interval). I have tried this for a number data source types (just set a refresh and remove the session cookie, and it seems to work). 

A new build of beta2 should appear on this page shortly, please let me know if this has solved your issues:
http://grafana.org/download/builds

**Comment by 12f-techops** [comment]
Appears fixed for me, thanks!

**Comment by jgerschk** [comment]
I second that -- been running for 12+ hours and not had an issue on the front-end.  I think this is expected based on the how the solution was implemented, the 401 errors do show up in the backend logs, but the client frontend is still drawing the graphs and not having the errors as it did before.

**Comment by imkarthikk** [comment]
This is still happening for me. But I get this in my logs:

```console
2015/04/21 00:10:25 [I] Completed / 302 Found in 340.273µs
2015/04/21 00:33:47 [I] Completed / 302 Found in 323.061µs
2015/04/21 03:34:15 [I] Completed /api/dashboards/db/ 401 Unauthorized in 699.199µs
2015/04/21 03:34:16 [I] Completed /api/dashboards/db/ 401 Unauthorized in 751.264µs
```
I upgraded from Grafana 2.0B3 to the stable release.

**Comment by ruslan-k** [comment]
I have this problem with 4.4.3 version. After some time ghaps show datapoints outside time range.
```
t=2017-08-28T16:06:23+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/datasources/proxy/3 status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/dashboard/db/main
t=2017-08-28T16:06:23+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/datasources/proxy/3 status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/dashboard/db/main
t=2017-08-28T16:06:23+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/datasources/proxy/3 status=401 remote_addr=194.186.207.104 time_ms=1 size=26 referer=https://gazer.rbsgate.com/grafana/dashboard/db/main
t=2017-08-28T16:06:25+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/datasources/proxy/3 status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/dashboard/db/main
t=2017-08-28T16:06:25+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/datasources/proxy/3 status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/dashboard/db/main
t=2017-08-28T16:06:26+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/dashboard/db/main
t=2017-08-28T16:06:34+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/dashboards/home status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/
t=2017-08-28T16:06:37+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/dashboards/home status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/
t=2017-08-28T16:12:10+0300 lvl=info msg="Request Completed" logger=context userId=5 orgId=5 uname=s.vasilev method=GET path=/logout status=302 remote_addr=194.186.207.104 time_ms=2 size=37 referer=https://gazer.rbsgate.com/grafana/profile
t=2017-08-28T16:12:10+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/user status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/profile
t=2017-08-28T16:12:10+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/user/orgs status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/profile
t=2017-08-28T16:12:10+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/user/preferences status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/profile
t=2017-08-28T16:12:10+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/search status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/profile
t=2017-08-28T16:12:11+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=194.186.207.104 time_ms=0 size=26 referer=https://gazer.rbsgate.com/grafana/profile

```
