### ISSUE TITLE
Unauthenticated users can query sensitive data

### ISSUE THREAD

**Issue by covrig** [grafana/grafana#16671]
**What happened**:
The application is does not verify user permissions before serving some contents which are supposed to be protected.
```
GET /api/org/users HTTP/1.1
```
```
HTTP/1.1 200 OK
```
```
[{"orgId":1,"userId":1,"email":"xxxxxxxxxx","avatarUrl":"/avatar/e4ea6467888d87d5143dcee3d3d43f2b","login":"admin","role":"Admin","lastSeenAt":"2019-04-17T13:13:57Z","lastSeenAtAge":"2m"},.......
```
**What you expected to happen**:
Refuse connection.

**How to reproduce it (as minimally and precisely as possible)**:
```
GET /api/org/users HTTP/1.1
```
**Anything else we need to know?**:
Enabled anonymous access.
This shouldn't be allowed since it exposes credentials to malicious actors.

**Environment**:.
All
- Grafana version:
6.1.4 and older

**Comment by torkelo** [comment]
There is no credentials there, and this is not exposed to unauthenticated users unless you have enabled anonymous access.

**Comment by covrig** [comment]
Indeed I have enabled anonymous access. I updated my post to mention this.
However, anonymous users shouldn't be able to perform such queries especially when the package is exposed to the internet. Is there a way to prevent these queries? I consider information like email address and user account a bit sensitive.
Thanks.

**Comment by covrig** [comment]
Not to mention that unauthenticated users can send write commands to secured databases (e.g. influxdb) linked to Grafana.

**Comment by torkelo** [comment]
> Not to mention that unauthenticated users can send write commands to secured databases (e.g. influxdb) linked to Grafana.

You need to setup a InfluxDB user with only query access. 

> Indeed I have enabled anonymous access. I updated my post to mention this.
However, anonymous users shouldn't be able to perform such queries especially when the package is exposed to the internet. Is there a way to prevent these queries? I consider information like email address and user account a bit sensitive.

Anonymous users have same access as Viewer or Editor (depending on what you specifed), and they can view other users in the org (to able to assign permissions , etc)

**Comment by covrig** [comment]
In my case anonymous users are have ```org_role = Viewer```. 
They can't do much more than view data with this role. Considering this, I honestly think they should see user accounts and other sensitive information (can they see more than ```api/org/users```?). Maybe this is a small window open for brute force attacks.
The colleagues from ICT ask me to remove this feature. Is there a way except disabling anonymous access? Thanks.

**Comment by torkelo** [comment]
You can disable anonymous access (it is disabled by default so it must be enabled)

But I think your right that this api is not needed for anonymous users, it is needed from logged in users who are viewers

**Comment by covrig** [comment]
My use case requires to keep anonymous access enabled (I have a lot of data that I would like to share with the general public), however the ICT colleagues ask me to disable the API for anonymous users. I need to see how can I do that. Maybe I can filter some commands it in the firewall.

Thanks for the InfluxDB read only tip. I forgot about the read only option.

**Comment by bergquist** [comment]
If you want more control of what anonymous users can see you could create a separate org for those users but then you have to duplicate all dashboards and datasources.

**Comment by covrig** [comment]
It's not about duplicating dashboards it's about the exposed login/contact information.

I would say that Anonymous access is a nice feature to have for some use cases - e.g. sharing a chart with live data  on a website (solar generation, weather data etc.). I would say it isn't a good idea to force a login for this (opening the sign-up page).
Internally or externally, it is never a good idea to display personal login/contact information.

In my case I blocked access to the sensitive information in the firewall, however this is just a silly workaround.

**Comment by torkelo** [comment]
Created new issue to track this https://github.com/grafana/grafana/issues/17318
