### ISSUE TITLE
[Feature Request] Add ability to use replacealias variables in url link in a table panel

### ISSUE THREAD

**Issue by analogfire2** [grafana/grafana#16677]
**What would you like to be added**:
add the ability to reference the variables created using the 'replacealias' function in the table panel query in the visualization column link URL field. Currently I can reference the entire column variable using ${__cell} but not the individual alias vars created by the split feature. This would use something like ${__cell(1)} to match on the variables parsed out from the replacealias.

**example using data from Zabbix**
**Field value** - test router: Operational status Bundle-Ether1.1:Test Interface
**Data query function** - replaceAlias(/(.*): Operational status (.*):(.*)/,$1 - $2 $3)
**result** - "test router - Bundle-Ether1.1 Test Interface"

**URL Link Format** - "http://grafana.test.com/d/osd3if1/example-page?from=now-1h&to=now&orgId=1&var-Device=${__cell(1)}&var-Alias=${__cell(2)}
**URL Result** - http://grafana.test.com/d/osd3if1/example-page?from=now-1h&to=now&orgId=1&var-Device=test%20router&var-Alias=Bundle-Ether1.1

**Why is this needed**:
This would allow for multi value URL creation and redirection to a different dash to pass these parameters through.

**Comment by torkelo** [comment]
Not sure I understand,  you can reference column values using `${__cell_1} ` syntax. Not sure what replace alias feature or split feature your talking about or what it does. It must be a zabbix feature?

**Comment by bergquist** [comment]
Thank you for opening this issue but I'm closing this due to lack of response.
