### ISSUE TITLE
Support Loki LogQL in explore UI

### ISSUE THREAD

**Issue by Kuqd** [grafana/grafana#16686]
**What would you like to be added**:

Due to work here https://github.com/grafana/loki/pull/492 the loki api has changed, the explore Loki section is passing anything after the label match query as a `regexp` query string but now we support queries as describe here: https://github.com/grafana/loki/blob/8ae30428933841b6f35b2a77669f24fbf35638eb/docs/usage.md#filter-expression

Some queries sample :
```
{job="mysql"} |= "error"
{name="kafka"} |~ "tsdb-ops.*io:2003"
{instance=~"kafka-[23]",name="kafka"} != kafka.server:type=ReplicaManager
```

**Why is this needed**:

We want to support the new Loki query language and get regular expression working as it is currently.

**Comment by Kuqd** [comment]
Also https://github.com/grafana/grafana/issues/14697 seems to explain the needs for it, but the design and PR on Loki side was not existing.

**Comment by steven-sheehy** [comment]
There's a draft PR for this already: https://github.com/grafana/grafana/pull/16674

**Comment by Kuqd** [comment]
Nice !
