### ISSUE TITLE
Template variables are not supported in alert queries

### ISSUE THREAD

**Issue by lig** [grafana/grafana#16681]
What is the state and plans for this one?
https://github.com/grafana/grafana/issues/6557

It is obvious that the entire community of Grafana users uses variables heavily, at least with the Prometheus source. It is a common practice to use variables to make a single dashboard for several environments/hosts/etc, which results in having those variables end up in queries.

There should be an easy way to create an alert for a currently selected variable value at least.

the current behavior is confusing, annoying and looks completely abandoned by the Grafana development team.

Thank you and keep up the good work!

**Comment by torkelo** [comment]
>  It is a common practice to use variables to make a single dashboard for several environments/hosts/etc, which results in having those variables end up in queries.

Yes, variables are used to create dynamic dashboards that allow you to filter / change the scope of what your looking at on a dashboard. They do not translate well for defining predictable easy to reason about alerting rules. 

We are sorry that we have not improved alerting and found another solution for the templating problem. Users need something to help make more generic alerting rules that is clear and Gafana has failed to deliver that. But using dashboard variables that are designed for interactive dashboard filtering is not the solution and would make the alerting engine incredibly complex and unpredictable. 

We are gearing up to make substantial alerting improvements and one of those is separating alerting rules from the dashboard & graph panel. Making alerting rules a standalone entity that you define separately from the dashboard & graph workflow. This will not directly solve the problem of generic alerting rules but will be an important foundation. We hope to share more about the future of Alerting in Grafana soon.

**Comment by lig** [comment]
@torkelo I see that some UX tuning could kinda solve the issue. Some improvement which could help:

- blocking the ability to create an alerting rule with ambiguous variable values
- creating the rule using the currently selected variable values
- explicitly showing which variables are used in the rule

The UI itself is in-place but it lacks some tweaks which could make it reasonable

**Comment by mcamou** [comment]
> > It is a common practice to use variables to make a single dashboard for several environments/hosts/etc, which results in having those variables end up in queries.
> 
> Yes, variables are used to create dynamic dashboards that allow you to filter / change the scope of what your looking at on a dashboard. They do not translate well for defining predictable easy to reason about alerting rules.
> 
> We are sorry that we have not improved alerting and found another solution for the templating problem. Users need something to help make more generic alerting rules that is clear and Gafana has failed to deliver that. But using dashboard variables that are designed for interactive dashboard filtering is not the solution and would make the alerting engine incredibly complex and unpredictable.
> 
> We are gearing up to make substantial alerting improvements and one of those is separating alerting rules from the dashboard & graph panel. Making alerting rules a standalone entity that you define separately from the dashboard & graph workflow. This will not directly solve the problem of generic alerting rules but will be an important foundation. We hope to share more about the future of Alerting in Grafana soon.

Any approximate ETA on this, or at least an idea of how long it might take?

**Comment by zmailloux** [comment]
+1 @torkelo  Hey! Any update regarding the development of the planned Alerting options?

**Comment by agilob** [comment]
>Any approximate ETA on this, or at least an idea of how long it might take?

:eyes:

**Comment by maitrungduc1410** [comment]
+1 on this

**Comment by delsaranbigglesworth** [comment]
+1

**Comment by wsj31013** [comment]
+1

**Comment by jb7959** [comment]
+1
