### ISSUE TITLE
Create a docker image for armv6

### ISSUE THREAD

**Issue by mhansen** [grafana/grafana#16689]
**What happened**:
Went to https://hub.docker.com/r/grafana/grafana-arm32v6-linux
Run $ docker run grafana/grafana-arm32v6-linux
docker: Error response from daemon: manifest for grafana/grafana-arm32v6-linux:latest not found.

**What you expected to happen**:
Images present, images run

**How to reproduce it (as minimally and precisely as possible)**:
$ docker run grafana/grafana-arm32v6-linux

**Anything else we need to know?**:
Looks like this should be working from https://github.com/grafana/grafana/pull/14950/files, see the line `docker push "${repo}-arm32v6-linux:${tag}"`

**Environment**:
N/A

See also Issue #13008

**Comment by torkelo** [comment]
It was removed because the arm v6 build was not working properly, think it's fixed now and we can add it back. 
https://github.com/grafana/grafana/commit/caa9a90bfd941a2e19f2d21476c826f59656cbc9 

@xlson am I right in understanding that the above commit could be reverted?

**Comment by xlson** [comment]
There's that, but the biggest reason why this was removed is that the base image we use doesn't exist for armv6. We will have to find another base image to get it working.

**Comment by threiner** [comment]
is there a solution to this yet ?

**Comment by aknuds1** [comment]
@threiner We don't have any solution for it yet, sorry.

**Comment by mendhak** [comment]
Would appreciate if this got some attention, the [other comment has some +1s](https://github.com/grafana/grafana/issues/13008#issuecomment-415342856) against it too. 

I'm also here from the new Raspberry Pi Zero, which is arm32v6 - I have tried unsuccessfully to create my own docker image by using arm32v6/alpine, and downloading the "Standalone Linux Binaries(ARMv6)"  from your downloads page. 

Unfortunately the -cli and -server executables just result in a not found error message. 

>/ # ./grafana-6.7.3/bin/grafana-server
/bin/sh: ./grafana-6.7.3/bin/grafana-server: not found

**Comment by pskowronek** [comment]
Would be nice to have a docker image for armv6, RPi Zero is quite nice platform for IoT :)

**Comment by ezickler** [comment]
@xlson Are you sure that arm32v6 is (still) unsupported by the base image? 
I don't know much about docker or grafana but from the dockerfile i figured the base image should be [this](https://hub.docker.com/_/node) node image. They state it supports arm32v6. 

Am i missing something or should a grafana arm32v6 image be possible then?

**Comment by xlson** [comment]
@ezickler We are using two different base images, ubuntu and alpine. It looks like there is a base image for alpine (I haven't tried it though) but not an official one for ubuntu. 

@marefr @aknuds1 does it make sense to look into this again? If the alpine image works we could theoretically use it.

**Comment by aknuds1** [comment]
@xlson The main issue is all the extra effort it will take to support another Docker image variant, not whether it can be done. We would have to analyze in depth whether it's worth the risk/time.

**Comment by pskowronek** [comment]
Any conclusions? :)

**Comment by Washee** [comment]
Will there be an arm6 docker image of grafana?

**Comment by wentzel** [comment]
+1 on this one!

**Comment by zoqueton99** [comment]
Also interested!
