### ISSUE TITLE
Grafana 2.0: Import from elasticsearch: test-series-0

### ISSUE THREAD

**Issue by arnaudmm** [grafana/grafana#1669]
Hello,

After import from ES, some graph got their metrics replace by one metric : test-series-0

It's like random I guess, but I go more test-series bug than ok import.

Example : http://screen.infomee.fr/aff57038de2330a3a2f1418d904f4fc0.png

**Comment by torkelo** [comment]
Have you marked a datasource as default? the test series is the grafana test data source that is generating. Go into data sources and mark your data source as default and it should be fine.

**Comment by arnaudmm** [comment]
Same result with graphite source set as default

2015-03-31 10:46 GMT+02:00 Torkel Ödegaard <notifications@github.com>:

**Comment by arnaudmm** [comment]
Forget what I said, it seems ok! thank you
