### ISSUE TITLE
Blank PNG using "Direct link rendered image"

### ISSUE THREAD

**Issue by RedSpid3r** [grafana/grafana#16699]
**What happened**:
Following upgrade to 6.1.3 "Direct link rendered image" now always shows a blank png

I see this when enabling debug logging

```
`t=2019-04-21T13:06:21+0000 lvl=info msg=Rendering logger=rendering path="d-solo/Cv0dVhvik/nexus-app-health?orgId=1&from=1555765303376&to=1555851703376&var-interval=%24__auto_interval_interval&panelId=25&width=1000&height=500&tz=Europe%2FLondon"`

`t=2019-04-21T13:06:21+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url=https://localhost:8443/d-solo/Cv0dVhvik/nexus-app-health?orgId=1&from=1555765303376&to=1555851703376&var-interval=%24__auto_interval_interval&panelId=25&width=1000&height=500&tz=Europe%2FLondon&render=1 width=1000 height=500 png=/var/lib/grafana/png/7r3xveCKzxBUlYOb4V8o.png domain=localhost timeout=60 renderKey=oIvDPOHTXTMeIYZhzbcUu3ea5O0Wylta]" timezone=Europe/London`

`t=2019-04-21T13:06:25+0000 lvl=dbug msg="Image rendered" logger=rendering path=/var/lib/grafana/png/7r3xveCKzxBUlYOb4V8o.png`
```
**What you expected to happen**:
Graph is rendered as a PNG

**How to reproduce it (as minimally and precisely as possible)**:
Open any dashboard, click share, click Direct link rendered image

**Anything else we need to know?**:
Upgrading 6.1.4 did not fix

**Environment**:
- Grafana version: v6.1.4 (commit: fef1733)
- Data source type & version: MySQL | Server version: 8.0.15
- OS Grafana is installed on:  Ubuntu 16.04.6 LTS 
- User OS & Browser: Win10x64 | FireFox 66.0.3x64
- Grafana plugins: 
- Others:

![image](https://user-images.githubusercontent.com/12657277/56470554-4ed7e600-643f-11e9-87d0-0af00434463c.png)

**Comment by darfij** [comment]
same problem on ubuntu 18.04 and influxdb
.png is 0 bytes

**Comment by RedSpid3r** [comment]
Updated to Grafana v6.1.6 (commit: cf9cb45), still can't render images but now I get this:

![image](https://user-images.githubusercontent.com/12657277/57970468-71471b80-7979-11e9-8729-5c6e7f8d64bf.png)

**Comment by RedSpid3r** [comment]
Issue still present on v6.2.5 (commit: 6082d19)
Any update/ETA on a fix for this?

**Comment by marefr** [comment]
@RedSpid3r @darfij We've had similar reports historically, but not in latest versions. Could you please include the content of dashboard json denoting problematic panel id and/or panel json? Please remove any sensitive information.

What result do you get if you do a Direct link rendered image. And then remove the `/render` part from the url and browse that? Proper panel rendered? Any errors logged in console (chrome developer tools)?

Thanks

**Comment by RedSpid3r** [comment]
Hi @marefr,

This happens when trying to share **any** panel from **any** dashboard. 

Removing the `/render` from the Direct Link URL causes the panel to be rendered correctly and without issue. The only error in the console is:

`window.controllers/Controllers is deprecated. Do not use it for UA detection. index.js:1362`

Thanks

**Comment by marefr** [comment]
@RedSpid3r can you please try and enable phantomjs debug logging?

```
[log]
filters = rendering:debug
```

**Comment by RedSpid3r** [comment]
@marefr this is what i had in the logs after adding the requested:

```
t=2019-08-06T22:11:32+0000 lvl=info msg=Rendering logger=rendering path="d-solo/XPsQAr7ik/dashboard-name-redacted?orgId=1&refresh=5m&from=1565049600000&to=1565129491278&panelId=2&width=1000&height=500&tz=Europe%2FDublin"
t=2019-08-06T22:11:32+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=https://localhost:8443/d-solo/XPsQAr7ik/dashboard-name-redacted?orgId=1&refresh=5m&from=1565049600000&to=1565129491278&panelId=2&width=1000&height=500&tz=Europe%2FDublin&render=1 width=1000 height=500 png=/var/lib/grafana/png/CBTSmqaFaumVzCT5rXJI.png domain=localhost timeout=60 renderKey=9YwxYDywCYTlmaZg4RWqArfJsk2h5WWV]" timezone=Europe/Dublin
t=2019-08-06T22:12:34+0000 lvl=dbug msg="Phantomjs output" logger=rendering out=
t=2019-08-06T22:12:34+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
t=2019-08-06T22:12:34+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-08-06T22:12:34+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=********** error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-08-06T22:12:34+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=********** method=GET path=/render/d-solo/XPsQAr7ik/dashboard-name-redacted status=500 remote_addr=***.***.***.*** time_ms=62626 size=760 referer="https://***************.com:8443/d/XPsQAr7ik/dashboard-name-redacted?orgId=1&refresh=5m"
```

**Comment by marefr** [comment]
Do you have enough free memory on the machine where Grafana runs? PhantomJS can require quite a lot of memory.

Can you access this link, https://localhost:8443/d-solo/XPsQAr7ik/dashboard-name-redacted?orgId=1&refresh=5m&from=1565049600000&to=1565129491278&panelId=2&width=1000&height=500&tz=Europe%2FDublin, properly? Looks a bit weird that it's https.

**Comment by RedSpid3r** [comment]
@marefr seems that memory was the issue! When PhantomJS was running the server was reaching only ~84mb free RAM. 

Seems that MySQL was hogging 65% of the RAM, and after resolving that rendered images are working again :) 

![image](https://user-images.githubusercontent.com/12657277/63386339-b7f24a80-c39a-11e9-9a2a-ac560ea8436f.png)
