### ISSUE TITLE
Line always connected

### ISSUE THREAD

**Issue by aratnikovmxmgt** [grafana/grafana#16698]
**What happened**: If there is no data, grafana still connects line between values. 
![grafana_lines](https://user-images.githubusercontent.com/43950354/56469404-1be32180-6442-11e9-9222-ddfaa3e818df.PNG)
**What you expected to happen**: 
![zabbix](https://user-images.githubusercontent.com/43950354/56469405-1be32180-6442-11e9-83d3-a1578fa38ea0.PNG)
Draw lines like in Zabbix or connect lines only between values with set time span.
![grafana_dots](https://user-images.githubusercontent.com/43950354/56469406-1c7bb800-6442-11e9-85bb-40c9b1772369.PNG)
For example if gap between values is more than 1 minute - do not draw.

**Environment**:
- Grafana version:  Grafana v6.1.4 (commit: fef1733) 
- Data source type & version: Zabbix 4.0.3
- OS Grafana is installed on: Debian 9
- User OS & Browser: Windows 10 Mozilla Firefox
- Grafana plugins: Zabbix, PRTG

**Comment by torkelo** [comment]
You have full control over this i the graph display option named null value, also check that your query return nulls for the missing points
