### ISSUE TITLE
Grafana 2.0: links to file based dashboards

### ISSUE THREAD

**Issue by dvenza** [grafana/grafana#1670]
I have some scripts that generate json dashboards dynamically. Unfortunately these cannot be made with templates. In Grafana 2 I can reach file based dashboards under the /dashboard/file/ path, but I would like to have them visible from the dashboard list somehow.
The possibilities I see are:

1. let me manually add URLs/files to the dashboard list
2. create an external command line tool to add/update/remove dashboards in the db given a json file
3. I modify the db directly (argh!)
4. Let me add a text widget in the Home dashboard (or set an arbitrary dashboard as the Home)

**Comment by torkelo** [comment]
I think having an external tool that can sync a directory with json files and push them to the http api would be best

**Comment by noroute** [comment]
I'd suggest that having a simple way to enable keeping dashboards in version control is an important use case (it is for us). That can be achieved by having file based dashboards in Git repos and pushing to them. No need to keep them in the database.

This would probably lead to just listing file-based dashboards in the dashboard list. Or is there a fundamental problem with that?

**Comment by sknolin** [comment]
I'd like file based dashboards to appear in the list somehow too. In my use case for scripted dashboards.

**Comment by kerush** [comment]
@torkelo 

"I think having an external tool that can sync a directory with json files and push them to the http api would be best"

What is the HTTP API that you're referring to? It sounds like a viable option here.

**Comment by torkelo** [comment]
see the grafana docs site, under reference

**Comment by iangkent** [comment]
We are working on a docker container image for grafana. We want the image to contain pre-created dashboards stored in json files. This works now with Grafana 2.0 put the dasboard .json files are not loaded into db and therefore not listed in dashboard list. These file stored dashboards cannot be starred or tagged either. What would be the recommended approach to getting these dashboards loaded into db.
Would we need to run a script on initial container startup to load these dashboards from json file into db using Grafana API?

**Comment by torkelo** [comment]
I would like to have a very easy to use CLI tool for this, but it is not done yet :(  But you can use the HTTP api to import json files, http://docs.grafana.org/reference/http_api/
