### ISSUE TITLE
POST not being used for /metric/find and /tags request

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#16707]
We are seeing an issue in grafanacloud graphite, Grafana v6.1.4 (fef1733)
but TBH we've been seeing it for a long time even with older grafana versions

Upon load of a dashboard that has template variables defined (see "tsdb-gw 0.9" dashboard in our internal ops instance), when the dashboard loads, we immediately get a red error popup that fills up half of the screen (and even that is not enough to fully show the error)

The error looks like:
```
{"err":{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/32/metrics/find","params":{"query":"tsdb-gw.stats.{FOO,BAR,BAZ}.api.request.*","from":1555845978,"until":1555932498},"inspect":{"type":"graphite"},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"},"cancelled":true}
```
![devtools](https://user-images.githubusercontent.com/20774/56499033-30402080-650d-11e9-84b2-24503fa05427.png)

`{FOO,BAR,BAZ}` is actually a huge list with hundreds of entries. lots of text

Chrome network tab shows that an xhr request to /find failed, without a status code, so it looks like the request was not made or did not return.

When i look for more information, there's no timing information (says the request stalled) (https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation) .
![timing](https://user-images.githubusercontent.com/20774/56499040-39c98880-650d-11e9-8b2e-1fd7fa2db4bd.png)

no response or preview is available, and the headers look like this:
(abridged)
```
https://redacted/api/datasources/proxy/32/metrics/find?from=1555845978&query=tsdb-gw.stats.%7BFOO,BAR,BAZ%7D.api.request.*&until=1555932498
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: application/json, text/plain, */*
Referer: https://redacted/d/DSd3POZiz/tsdb-gw-0-9?orgId=1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
X-Grafana-Org-Id: 1
from: 1555845978
query: tsdb-gw.stats.{FOO,BAR,BAZ}.api.request.*
until: 1555932498
icon_explore.svg	icon_alert.svg	icon_cog.svg	icon_question.svg	data:image/png;base…	collect?v=1&_v=j73&aip=1&a=316810956&t=pageview&_s…58328364-6&_gid=1608825132.1555924889&z=576751083	find?from=1555845978&query=tsdb-gw.stats.*&until=1555932498	find?from=1555845978&query=tsdb-gw.stats.%7Bus-wes…ka-test-1-kafkaupgradetest1%7D.*&until=1555932498	find?from=1555845978&query=tsdb-gw.stats.%7Bus-wes…dd967fd68-wzsx6%7D.api.request.*&until=1555932498	icon_add_panel.svg	data:image/svg+xml;…	annotations?dashboardId=488&from=1555846040522&to=1555932440522	
```

My guess is probably the generated URL is too long and it cancels the request? even though it's vague.

I think we should:
1) make sure people cannot shoot themselves in the foot (e.g. fall back to post bodies if url would be too long), to the extent possible
2) provide clearer errors. ellipsize long url's and have clearer error messages

**Comment by marefr** [comment]
@Dieterbe Can you try out the suggestion [here](https://stackoverflow.com/a/17696015) for getting more information about why it gets cancelled? 

How long is the url in use? Chrome's url length limit should be more than 10000 characters I think.

**Comment by marefr** [comment]
Need to verify first that /metric/find and /tags supports POST requests.

**Comment by marefr** [comment]
@DanCech do you have any input on this regarding Graphite API support?

**Comment by DanCech** [comment]
graphite-web supports both GET and POST for both of those endpoints, not sure about any other implementations of graphite (graphite-api, carbonapi, etc)

**Comment by marefr** [comment]
Thanks. But in Grafana POST are always used for /render so thinking that /metric/find also should support that. Maybe @torkelo have any input?

**Comment by bergquist** [comment]
seems like a frontend issue?

**Comment by bergquist** [comment]
@daniellee backend team can fix it. 

@aocenas perhaps you can @papagian could take a look on this?

**Comment by aocenas** [comment]
@bergquist How urgent is this? I see milestone is not for patch release so I assume we can finish what we have in progress right now?

**Comment by papagian** [comment]
> Thanks. But in Grafana POST are always used for /render so thinking that /metric/find also should support that. Maybe @torkelo have any input?

[`/metrics/find`](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/metrics/views.py#L56) supports POST but [`/tags`](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/tags/views.py#L81) does not

**Comment by papagian** [comment]
Unable to reproduce it: I select all for env variable (Tsdb-gw 0.10.0 dashboard) but I get "414 Request-URI Too Large" error instead of no response (as described).

I have tested it with:

- [ ] Chrome Version 75.0.3770.100
- [ ] Firefox 67.0.4 (64-bit)
- [ ] Safari Version 12.1.1 (14607.2.6.1.1)

BTW Should 414 response status be handled in someway?

**Comment by marefr** [comment]
@papagian I selected All for env variable using (tsdb-gw 0.10.0 dashboard) and get a cancelled error message in the console using Chrome version 75.0.3770.90:

Possibly unhandled rejection:
```json
{
  "err": {
    "data": null,
    "status": -1,
    "config": {
      "method": "GET",
      "transformRequest": [null],
      "transformResponse": [null],
      "jsonpCallbackParam": "callback",
      "url": "api/datasources/proxy/32/metrics/find",
      "params": { "query": "", "from": 1561383197, "until": 1561386917 },
      "inspect": { "type": "graphite" },
      "retry": 0,
      "headers": { "X-Grafana-Org-Id": 1, "Accept": "application/json, text/plain, */*" }
    },
    "statusText": "",
    "xhrStatus": "error"
  },
  "cancelled": true
}

```

**Comment by marefr** [comment]
Let's focus on fixing /metric/find with post
