### ISSUE TITLE
template: index:83:19: executing "index" at <.MainNavLinks>: can't evaluate field MainNavLinks in type *dtos.IndexViewData

### ISSUE THREAD

**Issue by jonnythebard** [grafana/grafana#16701]
**What happened**:
I am trying to upgrade grafana using yum from 4.6.3 to 6.1.3 but following error occurs:
`template: index:83:19: executing "index" at <.MainNavLinks>: can't evaluate field MainNavLinks in type *dtos.IndexViewData`
error log prints as following:
```
t=2019-04-22T11:29:50+0900 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=500 remote_addr=192.168.1.3 time_ms=1 size=123 referer=
t=2019-04-22T11:29:50+0900 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=500 remote_addr=192.168.1.3 time_ms=1 size=123 referer=http://192.168.1.13:3000/login
```

**What you expected to happen**:
I am expecting to see login page.

**How to reproduce it (as minimally and precisely as possible)**:
I am afraid I don't really know l how to reproduce it. I am working on a server that someone else has worked on. The update would work fine in my machine.

**Anything else we need to know?**:
It seems that updating grafana from 4.x.x to 5.x.x is not working for me as well.
Updating grafana within 4.x.x versions works fine though.
I checked dependancies and updated them to right versions but still not working.

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: influx 1.7.5-1
- OS Grafana is installed on: CentOS Linux release 7.4.1708 (Core)
- User OS & Browser:
- Grafana plugins: default plugins
- Others:

Sorry for lack of details. Is there any way I can resolve it?

**Comment by torkelo** [comment]
make sure your starting latest binary, it was renamed ~1 year ago, or rebuild. check you bin folder

**Comment by jonnythebard** [comment]
thanks for the reply. turns out it was problem with `static_root_path` in grafana.ini. it was pointing at old static data.

**Comment by hoanganh9610** [comment]
> thanks for the reply. turns out it was problem with `static_root_path` in grafana.ini. it was pointing at old static data.

Do you can share me your fix?
