### ISSUE TITLE
Log Real Http Port

### ISSUE THREAD

**Issue by mhmdhsenkamal** [grafana/grafana#16709]
**What would you like to be added**:
When using a dynamic port for grafana server, the real port should be printed to the logs instead of 0. Setting the http port to 0 in the custom.ini file means the port will be dynamically allocated. The problem is that instead of logging the real port allocated, 0 is logged.

**Why is this needed**:
This is needed for a more reliable and cross-platform way to get the port of the running grafana server.

https://github.com/grafana/grafana/blob/532abe2fc2301ce8d87f5625e94316cbc779fedb/pkg/api/http_server.go#L81

**Comment by mhmdhsenkamal** [comment]
Any updates on this?

**Comment by marefr** [comment]
It's labeled as a feature request. Core team have no intent to work on this unless there are a lot of people upvoting this feature. We may accept a PR for it if you're interested in contributing.

**Comment by mhmdhsenkamal** [comment]
But isn't this more of a bug fix than a feature request? I mean if I want to use a dynamic port and the port being logged is not the one allocated, would not this sound a bit inconsistent?

**Comment by marefr** [comment]
Sure. Changed this to a bug instead of feature request.

**Comment by marefr** [comment]
If anyone interested in contributing here the first part is investigating whether the port is possible to retrieve from an `http.Server` instance or what would be needed to fix this.
