### ISSUE TITLE
Default data source doesn't seem to take effect (v 2.0.0-beta1)

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1671]
Setting a datasource to default:
![image](https://cloud.githubusercontent.com/assets/917241/6917868/01c6b692-d7a9-11e4-8b2a-b29bc8b40156.png)

Doesn't appear to actually make it the default when adding a graph or singlestat:
![image](https://cloud.githubusercontent.com/assets/917241/6917892/33ad3f6e-d7a9-11e4-9f8d-72265ad5e574.png)

**Comment by torkelo** [comment]
strange, and this on a newly added panel? Try doing a full page refresh (f5), should not be required, but just want to know if that solves it.

**Comment by torkelo** [comment]
could replicate this, but it is fixed with a full page refresh, but that should not be required. It was working before without that. Will fix, thanks for reporting this!
