### ISSUE TITLE
when state change from alerting to ok,there's no alert sent sometimes.

### ISSUE THREAD

**Issue by B1ur** [grafana/grafana#16717]
**What happened**:
I'm using webhook notification.When state change to alerting,notification can be sent.but when state change to OK, I cannot  receive it. In state history tab,I can see every state change. 

I would be very grateful if someone can solve this problem or provide ideas for solving the problem.

**What you expected to happen**:
when the state change,from alerting to ok,or from ok to alerting ,notification works fine. 
**How to reproduce it (as minimally and precisely as possible)**:
I dont know it yet,some of my alert are always working fine，but few of them are not.
**Anything else we need to know?**:
my alerting config is below:

Evaluate every 1m For 5m
WHEN last() OF query(B, 10m, now) IS BELOW 50
If no data or all values are null
SET STATE TO OK
If execution error or timeout
SET STATE TO Keep_Last_State

**Environment**:
- Grafana version:5.4.3
- Data source type & version:influxdb
- OS Grafana is installed on:SUSE 12
- User OS & Browser:chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Any information in the Grafana server log when you expect a notification to be sent? Have you unchecked the "Disable Resolve Message" in notifier configuration?

**Comment by B1ur** [comment]
Yes,the "Disable Resolve Message" is unchecked.
For log config, I changed the mode to file,and level to info,nothing else.Cause I want to output all the logs to files.
When i checked the logs,I found there was something like "name="my alert" changing state to=ok/keep_state",or something query error.I cannot find anything about alerting or notice request.but all of my alerting state notification was received, ok state was't.
I don't know what I can do now for this.I have no idea.

**Comment by B1ur** [comment]
> Any information in the Grafana server log when you expect a notification to be sent? Have you unchecked the "Disable Resolve Message" in notifier configuration?

Yes,the "Disable Resolve Message" is unchecked.
For log config, I changed the mode to file,and level to info,nothing else.Cause I want to output all the logs to files.
When i checked the logs,I found there was something like "name="my alert" changing state to=ok/keep_state",or something query error.I cannot find anything about alerting or notice request.but all of my alerting state notification was received, ok state was't.
I don't know what I can do now for this.I have no idea.

**Comment by B1ur** [comment]
> Any information in the Grafana server log when you expect a notification to be sent? Have you unchecked the "Disable Resolve Message" in notifier configuration?

Is sending a notification related to the alert configuration? 
Will it send a notification always when the state changes between alerting and ok?

**Comment by bergquist** [comment]
Alert notifications will only be sent on state changes. 

You need to attach alert notifiers to alert rules or configure alert notifiers to be used for all alert rules on the alert notification configuration page.

**Comment by jkarneges** [comment]
We are seeing the same problem with Grafana 6.2.0 on Ubuntu 16.04.6. We have set up Slack and webhook notifications for an alert. They get sent when the alert goes to an error state, but not when the alert state returns to ok state.

From the logs:

```
t=2019-05-23T05:23:39+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=9 name="Latency / Delivery - sfo2 alert" changing state to=no_data
t=2019-05-23T05:23:39+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=9 newState=no_data prev state=ok
t=2019-05-23T05:23:39+0000 lvl=info msg=Rendering logger=rendering path="d-solo/000000002/production?orgId=1&panelId=5"
t=2019-05-23T05:23:41+0000 lvl=info msg="uploaded screenshot of alert to external image store" logger=alerting.notifier url=https://s3.us-west-1.amazonaws.com/xxxx.png
t=2019-05-23T05:23:41+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=9 notification="Slack #ops"
t=2019-05-23T05:23:41+0000 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
t=2019-05-23T05:24:18+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=9 name="Latency / Delivery - sfo2 alert" changing state to=no_data
t=2019-05-23T05:25:36+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=9 name="Latency / Delivery - sfo2 alert" changing state to=no_data
t=2019-05-23T05:26:15+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=9 name="Latency / Delivery - sfo2 alert" changing state to=no_data
t=2019-05-23T05:27:33+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=9 name="Latency / Delivery - sfo2 alert" changing state to=no_data
t=2019-05-23T05:28:12+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=9 name="Latency / Delivery - sfo2 alert" changing state to=no_data
t=2019-05-23T05:29:30+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=9 newState=ok prev state=no_data
```

Notably, neither the Slack nor webhook notifications are sent when the state returns to ok, so perhaps this is not a webhook-specific problem.

**Comment by torkelo** [comment]
Unable to replicate this. 

<img width="424" alt="Screen Shot 2019-05-28 at 11 29 41" src="https://user-images.githubusercontent.com/10999/58467433-ee258280-813b-11e9-89d3-b99ae17124a2.png">

Make sure Disable Resolve Message is unchecked.

**Comment by jkarneges** [comment]
From me, this may have been a false alarm. I didn't realize the `no_data` notification sort of exists outside the normal alerting cycle. There is no `ok` notification when data resumes. At least this is the case by default, if the configuration for handling no data is set to No Data.

However, if the state goes to `alerting`, then as expected there is an `ok` notification afterwards.
