### ISSUE TITLE
Prometheus datasource provisioning: direct access not working

### ISSUE THREAD

**Issue by dichque** [grafana/grafana#16719]
**What happened**:
I am provisioning Grafana using prometheus as datasource using following configuration:
`    
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: prometheus
        orgId: 1

    datasources:
    - name: prometheus
      type: prometheus
      access: direct
      orgId: 1
      url: http://prometheus-operated:9090
      isDefault: true
      jsonData:
        timeInterval: 15s
        severity_critical: "4"
        severity_high: "3"
        severity_warning: "2"
        severity_info: "1"
      version: 1
      editable: true
`
**What you expected to happen**:
Post login to grafana dashboard access is set to Browser instead of Server.

**How to reproduce it (as minimally and precisely as possible)**:
Provision Grafana using Prometheus as data source using above configuration.

**Anything else we need to know?**:

**Environment**: dev
- Grafana version: 6.0.0
- Data source type & version: Prometheus & 1
- OS Grafana is installed on: Kubernetes
- User OS & Browser: MacOS Mojave & Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- Grafana plugins: 
- Others:

**Comment by marefr** [comment]
Works as expected for me. Please make sure to restart Grafana instance after you've made changes to your dashboard provisioning configuration. Alos, the deleteDatasources section looks weird since you're adding a new datasource below with the same name.
