### ISSUE TITLE
Advanced formatting options for variables in panel title doesn't work

### ISSUE THREAD

**Issue by okondrashin** [grafana/grafana#16711]
**What happened**:
[Advanced Formatting Options](https://grafana.com/docs/reference/templating/#advanced-formatting-options) for template variables don't work with panel title.

**How to reproduce it (as minimally and precisely as possible)**:
It works fine for *Text* field like:
<img width="754" alt="Screenshot 2019-04-22 at 22 25 20" src="https://user-images.githubusercontent.com/25942465/56522826-73bb7e80-654f-11e9-8d51-42e5e52c1338.png">

But it don't work with *panel title*:
<img width="754" alt="Screenshot 2019-04-22 at 22 25 43" src="https://user-images.githubusercontent.com/25942465/56523158-cf860780-654f-11e9-8280-fe0b7894d4b6.png">

**What you expected to happen**:
For this case it should be something like this:
<img width="754" alt="Screenshot 2019-04-22 at 22 25 43" src="https://user-images.githubusercontent.com/25942465/56523295-f93f2e80-654f-11e9-8fd4-e67af20c9865.png">

**Environment**:
- Grafana version: v6.1.4

**Comment by girishjk** [comment]
Also, the nested variables that work in the query are not resolved in title.
${varA${varB}} becomes "varAB" in the title if $varB = B

**Comment by torkelo** [comment]
nested variables are not supported, anywhere

**Comment by girishjk** [comment]
I did read that somewhere, but ${varA${varB}} works fine for InfluxDB queries!

**Comment by hugohaggmark** [comment]
Closing this issue as I can't repro it on Grafana v7.3.1 (6668161a88) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
