### ISSUE TITLE
Grafana UI do not load any data

### ISSUE THREAD

**Issue by viharikrishna** [grafana/grafana#16715]
I've the Prometheus UI loading data and also data source with in Grafana working. But for some reason Grafana UI doesn't load any data.
Any suggestions on where to look for?

**Comment by marefr** [comment]
I don't understand what you mean. What is the difference between " data source with in Grafana working" and "Grafana UI doesn't load any data". Please provide more information for us to be able to help you.

**Comment by viharikrishna** [comment]
Hello marefr

Setup we have is Istio, gRPC running on GKE for handling Millions of RPS.
We are using Isito’s build-in monitoring framework with Prometheus, Grafana and following instructions as mentioned in https://istio.io/docs/tasks/telemetry/metrics/querying-metrics/ and https://istio.io/docs/tasks/telemetry/metrics/using-istio-dashboard/

Prometheus version - image: docker.io/prom/prometheus:v2.3.1
Grafana - I don’t see it in the UI anywhere
Istio - 1.1.1

Prometheus seems to be working fine.. All the targets are up

![image](https://user-images.githubusercontent.com/23062111/56599401-561c0280-65ab-11e9-8286-e7179b327c97.png)

![image](https://user-images.githubusercontent.com/23062111/56599458-72b83a80-65ab-11e9-85a6-208cd15ae3e2.png)


￼However, Grafana doesn’t load any data.
￼
![image](https://user-images.githubusercontent.com/23062111/56599474-78ae1b80-65ab-11e9-9b44-47de652e2eb0.png)

￼
![image](https://user-images.githubusercontent.com/23062111/56599479-7c41a280-65ab-11e9-9dc5-97b3592c0f9f.png)


Datasource is valid here and says it’s working
￼
![image](https://user-images.githubusercontent.com/23062111/56599489-819eed00-65ab-11e9-932d-c9cc3882f6a9.png)

**Comment by marefr** [comment]
In Prometheis UI you're looking at the last 1 hour of data. In Grafana you're looking at last 5 minutes - change time range in the upper right corner of dashboard).
