### ISSUE TITLE
AzureMonitor: Support multiple subscriptions per datasource

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#16721]
It is common to have multiple subscriptions for Azure Monitor and the current way to handle that in Grafana would be to create a datasource per subscription. A better way to handle this would be a dropdown for subscriptions to the the query editor.

This will require some changes to the config page:

- Subscription becomes ‘Default subscription’ (mandatory, at least one subscription needs to be provided).
    - Move it down to be the last one in the config list, right below the Client Secret.
    - In the ‘info’ icon, state: ```This is just the default subscription. Grafana will access all subscriptions the Active Directory app will have reader level access to.```
- Users provides the Grafana AAD app reader level access to all the subscriptions they care about. Will need to add instructions on how to do this.

Changes to the query editor:
- The query editor then can use the credentials supplied to query all the available subscriptions it has reader access to and must cache it.
    - Subscriptions do not change often so can add a cache and have a way to refresh it manually.
- A new dropdown with the list of subscriptions, the default value is set from the default chosen on the config page. It is is the first dropdown and is chained to the rest.

**Comment by yesoreyeram** [comment]
Reader access or Monitoring Reader access?
