### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by josefkorbel** [grafana/grafana#16722]
Hello Grafana Team, I've been dealing with issue of grafana disconnecting users for a long time, with no luck.

**What happened**:
Periodical querying of Grafana API results to 
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mygrafanadns.com', port=443): Max retries exceeded with url: /api/alerts/134/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7be80a4390>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
**What you expected to happen**:
`200` 

**How to reproduce it (as minimally and precisely as possible)**:
Query Grafana API multiple times per minute.

**Environment**:
- Grafana version:
**6.0.0**
- Data source type & version:
**InfluxDB**
- OS Grafana is installed on:
**Ubuntu 18.04 LTS**
- User OS & Browser:
**Ubuntu 18.04 & Google Chrome**
- Grafana plugins:
**None**

Is there a way to increase those limits? How to prevent grafana from disconnecting users when the I/O is sufficient?

**Comment by marefr** [comment]
Please change your code to use some time backoff to not overload Grafana server. https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url

**Comment by josefkorbel** [comment]
That is not a solution more like a workaround, it has very far to heavy load.

**Comment by marefr** [comment]
We haven't received any similar reports so I think there must be something with your code. Please include the code you're using then.

**Comment by josefkorbel** [comment]
Because the alerting engine is very limited, and we want to send custom emails / sms messages we had to write our service which is fetching grafana Alerts API every minute and forwards them if any new alert is detected. So we are doing really only around 20 requests per minute if there is alot of new alerts, which does not seems to me as alot for grafana internals to handle. Calls in my code are just simply `requests` get calls in Python.

**Comment by torkelo** [comment]
Maybe your not closing connections?

**Comment by josefkorbel** [comment]
Hello @torkelo , I am not opening any, just using regular `requests.get(url)` from python `requests`. We just discovered another issues with InfluxDB, it might be related.

**Comment by aboughan** [comment]
Hello, @josefkorbel 
I have similar issue with my grafana. have you got the solution ? can you share it please?
