### ISSUE TITLE
Switch user context to "other" organization when old one is no longer available

### ISSUE THREAD

**Issue by anthraxn8b** [grafana/grafana#16728]
**What happened**:
A user is member of the default org.
The user logs in (context is now default org).
The user logs out.
I add the user to another org.
I remove the user from the default org.
The user logs in (context is not the new org).
The user has no chance to switch to the new org.

**What you expected to happen**:
The administrator should be able to set the current org (context) for every user.
The users context should automatically switch to the next (and maybe only) org that is available for him when he logs in - if the current org is no longer there or available for him.

**How to reproduce it (as minimally and precisely as possible)**:
Described above.

**Anything else we need to know?**:
Leads to misunderstandings for grafana noobs.
Admin has to know what will happen.
Admin has to manually (API) switch the context for the respective user(s)...

**Environment**:
- Grafana version: 6.1.1
- Data source type & version: prometheus - not required here
- OS Grafana is installed on: windows server 2012 r2
- User OS & Browser: ff 66.0.3
- Grafana plugins: some...
- Others:

**Comment by torkelo** [comment]
Agree this should be handled better!

**Comment by marefr** [comment]
Hmm I thought we had fixed this. #12263 for v5.2. I guess apparently not.

**Comment by mildwonkey** [comment]
Alrighty! Took a while, but I walked through this running Grafana on the windows server 2022 and confirmed there's no longer an issue. We can always reopen, but I am going to close this one for now 😃
