### ISSUE TITLE
Need to add read github organization information and create logins automatically, Instead of setting mail as an organization

### ISSUE THREAD

**Issue by lvyingde51** [grafana/grafana#16723]
**What would you like to be added**:

Need to add read github organization information and create logins automatically,
Instead of setting mail as an organization

**Why is this needed**:

Why is the organization's name e-mail when you log in with github's account?
Ideally, the organization name that reads the GitHub account is my organization  (rnd-it), not xxxx@email.com.

Thanks very much!!!

![image](https://user-images.githubusercontent.com/12809742/56581081-b68c5d80-6606-11e9-9142-a776f52f000b.png)

![image](https://user-images.githubusercontent.com/12809742/56580854-382fbb80-6606-11e9-8e5a-8590894be11e.png)

![image](https://user-images.githubusercontent.com/12809742/56581799-5991a700-6608-11e9-80ad-bd7e4d4c97e2.png)

**Comment by torkelo** [comment]
you must have disabled auto_assign_org so Grafana tries to create a new org for your user. 

Currently we only read name & email from Github. If you want GitHub users who share an org to also share an org in Grafana you need to enable auto_assign_org and in your config specify the allowed orgs:
https://grafana.com/docs/auth/github/#enable-github-in-grafana

**Comment by lvyingde51** [comment]
Thank you very much for your reply !

But there are some questions that need to be answered.
Question about github Enterprise Edition login.
Does grafana provide this feature?
If yes, how do I need to modify the configuration file?
If no, when will this feature be added?

Suppose admin has created organizations named RnD-IT1 and RnD-IT2 and RnD-IT3.
What do I need to do to enable User 1 and User 2 and User 3 to log in to Grafana and automatically add to the organization name corresponding to Github Enterprise Edition?
User 1's organization is (RnD-IT1), user 2's organization is (RnD-IT2)...
It's not an organization with its own mailbox name.

Here is my configuration.

![image](https://user-images.githubusercontent.com/12809742/56709196-7d610400-6752-11e9-9658-610b8874357c.png)
![image](https://user-images.githubusercontent.com/12809742/56709215-9b2e6900-6752-11e9-97c1-831796233dd7.png)
![image](https://user-images.githubusercontent.com/12809742/56709285-05470e00-6753-11e9-8a6a-f251b339e4b5.png)
![image](https://user-images.githubusercontent.com/12809742/56710178-6e308500-6757-11e9-8640-48630f4ceaca.png)
![image](https://user-images.githubusercontent.com/12809742/56710296-f7e05280-6757-11e9-927e-d45031462ad9.png)
