### ISSUE TITLE
how to export a complex dashboard to a  scripted dashboard template ?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1672]
Hi @torkelo .

I would like to build a new scripted dashboard from an already existing dashboard ( which has a lot of complex panels and templated variables)  and after add some customized code.

There is any easy way to do that?

Thank you very much!

**Comment by torkelo** [comment]
export it to json, then copy paste that json into your javascript code. json should be valid javascript (if assigned to a variable)

**Comment by toni-moreno** [comment]
Hi @torkelo , thank you for your fast response.

I've assigned the script to a variable and now it is loading ok.

But I need also to add some hook functions to check templated variable values before refreshing the dashboards .

something like that.

```
function on_variable_change(variable, new_value){
   if (variable='my_test' && new_value='25'){
        foreach (dashboard.rows.panels.targets) {
          change_target()
       }
   } 
}

function on_before_reload(){
  alert('reloading !!')
}
```

how can I do that?

Sorry

**Comment by toni-moreno** [comment]
Sorry @torkelo . 

I need only know if there is such  (similar) feature in scripted dashboards, if not I will create a Feature Reqüest  to add hook functions to most important viewer user interactions.

- on_dboard_change_variable()
- on_dboard_end()
- on_dboard_init()
- on_dboard_before_refresh()
- on_dboard_after_refresh()
- on_dboard_time_windows_change()
- on_dboard_zoom()
- on_dboard_hotkey()

**Comment by torkelo** [comment]
There are no hooks at the moment.
