### ISSUE TITLE
Graph between two labels for prometheus datasource

### ISSUE THREAD

**Issue by sivalearn12** [grafana/grafana#16733]
Hi,
i want the graph between two labels (timestamp , status) for the metric generated by pushgateway . timestamp in x-axis and status in y axis  in grafana for prometheus datasource

statistics_log_proxy_requests_execution{timestamp="2019-04-11 15:56:15",endpointname="Integration",status="started",cuid="ea868906-9258-43f2-8818-4fcc25c76a5e", job="prometheustech"}	2

statistics_log_proxy_requests_execution{timestamp="2019-04-11 15:56:15",endpointname="Integration",status="completed",cuid="ea868906-9258-43f2-8818-4fcc25c76a5e", job="prometheustech"}	4

please help

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
