### ISSUE TITLE
add dashboard ID to grafana's prometheus metrics

### ISSUE THREAD

**Issue by miekg** [grafana/grafana#16737]
**What would you like to be added**:

We would like to see the latency of dashboard on a per dashboard (actually per metric, but this will provide a good proxy) basis. Currently the exported (prometheus) metric has:

~~~
http_request_duration_milliseconds{handler="/uid/:uid",method="get",statuscode="404",quantile="0.9"}
~~~
`handler`, `method` and `statuscode`. It would be nice to tie this to an actually dash board being loaded.

**Why is this needed**:

We want to signal expensive dashboard to plot the `topk(10, ...)` of these.

Of course the number of dashboards is (in theory) unbounded, so this may fall down on label cardinality exploding.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
