### ISSUE TITLE
Enhancement request: Display / series override opacity control

### ISSUE THREAD

**Issue by apexskier** [grafana/grafana#16730]
**What would you like to be added**:

I'd like to be able to control opacity in my series overrides. Right now I can control color, which has opacity, but that doesn't work for me because it'll make all matches that color or I'll have to create an override for each line and set colors manually.

![Screen Shot 2019-04-23 at 11 04 33 AM](https://user-images.githubusercontent.com/329222/56604762-984b4100-65b7-11e9-96cb-201611d1174b.png)

**Why is this needed**:

This will let me highlight a primary metric in a graph dashboard. (There are plenty of other ways to do this, but I'd use opacity if it were available)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
