### ISSUE TITLE
Templete Variable is not supporting for Alerting in graph panel

### ISSUE THREAD

**Issue by suresh447** [grafana/grafana#16735]
**What happened**: I am trying to set the alerts for AKS cluster using template variables but it is showing grafana does not support alerts suing template variables

**What you expected to happen**: I want to configure alerts for my AKS cluster nodes CPU,Memory and disk space utilization is increases using template variables.Is there any way to send alerts with out hard coding the IP address manually.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Prometheus & 2.0.0
- OS Grafana is installed on: Ubuntu 16
- User OS & Browser: Windows 10 & 
- Grafana plugins: Winlogbeat
- Others:

**Comment by torkelo** [comment]
There already is a feature request for this (https://github.com/grafana/grafana/issues/6557) 

> Is there any way to send alerts with out hard coding the IP address manually.

I suggest you use wildcards instead of variables. Variables are for dynamic & interactable dashboards and are not designed for alerting rules.
