### ISSUE TITLE
Millisecond data point confusion

### ISSUE THREAD

**Issue by mengxuexue** [grafana/grafana#16734]
hi,I'm sorry I didn't find the relevant issue.
**What happened**:
I configured resolution is millisecond ,my dashboard‘s  zigzag chart is confused.（Data processed by the server can not guarantee that the data is orderly.but I configured resolution is second ,Discounts don't mess up.）
![image](https://user-images.githubusercontent.com/23066891/56630904-aff0fb00-6685-11e9-9666-001d69c57416.png)
![image](https://user-images.githubusercontent.com/23066891/56630932-c434f800-6685-11e9-8950-f44b3f71af9c.png)
![image](https://user-images.githubusercontent.com/23066891/56631032-137b2880-6686-11e9-9578-42b070de7f99.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mengxuexue** [comment]
My version is 3.1.0~

**Comment by torkelo** [comment]
OpenTSDB needs to return data points in order, strange that it does not in this case.

**Comment by torkelo** [comment]
Maybe a new bug in OpenTSDB 3.1 ?

**Comment by mengxuexue** [comment]
> OpenTSDB needs to return data points in order, strange that it does not in this case.

Do you remember that there is a sort of DPS data returned in that code?

**Comment by mengxuexue** [comment]
> Maybe a new bug in OpenTSDB 3.1 ?

I found that the 4.1 version also has this problem.

**Comment by mengxuexue** [comment]
> OpenTSDB needs to return data points in order, strange that it does not in this case.

but, why when i configured resolution is second,The returned data is unordered, but the data points are connected without confusion.

**Comment by mengxuexue** [comment]
@torkelo

**Comment by torkelo** [comment]
Maybe an opentsdb bug?

**Comment by torkelo** [comment]
Use query inspector to view open TSDB response
