### ISSUE TITLE
Grafana 2.0b: init.d script will say it started ok, but it did not! 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1674]
Example: using port 80 when permission is denied (already used for example),

**Comment by floppy84** [comment]
i got same issue on centos 6.6 Final  start script return : 

[root@mrs-mgt-shinken-3 sources]# /etc/init.d/grafana start
Starting the process grafana [ OK ]
start-stop-daemon: unrecognized option '--chdir'
Try `start-stop-daemon --help' for more information.
grafana process was started [ OK ]

but processus won't start, i use port 80 in default.ini and no process other process listen on it.
I tried with default port 3000 same issue.

i have to start with ./grafana web

**Comment by erikankrom** [comment]
I tested modification of the init script to run the service as the root user and it resolved the issue.  Logs indicated permission denied for grafana user binding to a port under 1024.

**Comment by floppy84** [comment]
Many thanks ! The version 2 is awesome. Félicitation for your work. 

Florian cavaillou

**Comment by torkelo** [comment]
@floppy84 thank you!

**Comment by JorgeGT** [comment]
I had the same problem with linux reserved ports (those under 1024). Ended up setting a port redirect rule with iptables =)

**Comment by erikankrom** [comment]
I suppose you could recommend using iptables forwarding or fronting with a proxy like nginx.  That would likely be the best practice, rather than mucking with kernel configs or granting root access.

**Comment by JorgeGT** [comment]
Pretty easy even! 

    $ sudo iptables -t nat -A PREROUTING -p tcp --dport 1000 -j REDIRECT --to-port 3000
    $ sudo apt-get install iptables-persistent

**Comment by torkelo** [comment]
Fixed via, #1758

**Comment by claenjoy** [comment]
how to redirect localhost:3000 to grafana.host.com ,  you can do that with apache2.4 ?
