### ISSUE TITLE
Multi-value select dropdown don't tolerate data having null values from PostgreSQL

### ISSUE THREAD

**Issue by ikkala** [grafana/grafana#16744]
**What happened**:

Narrowing the dropdown content fails when writing characters to dropdown input box if database query that populates the dropdown returns null values.

Browser console shows the following error:
<pre>
TypeError: Cannot read property 'toLowerCase' of undefined
    at value_select_dropdown.ts:250
    at Jt (lodash.js:582)
    at Function.hr.filter (lodash.js:9174)
    at e.queryChanged (value_select_dropdown.ts:249)
    at fn (eval at compile (angular.js:15551), <anonymous>:4:168)
    at l.$eval (angular.js:18423)
    at angular.js:26308
    at Object.<anonymous> (angular.js:29160)
    at k (angular.js:410)
    at Object.$$writeModelToScope (angular.js:29158)
</pre>

**What you expected to happen**:

UI should not fail and should show the narrowed dropdown content, the null values as empty strings for example (or, perhaps null is different than empty string in some case of some data sources)

**How to reproduce it (as minimally and precisely as possible)**:

Create Multi-value (and Include All option) variable of type "Query" and query for example from PostgreSQL by "select null". Open dropdown and start writing to the dropdown box.

**Anything else we need to know?**:

The $window.document.body of valueSelectDropdown contains `text: undefined` because of null values coming from database:
https://github.com/grafana/grafana/blob/5ff44bdbcf680958a87a60d3420bebbdd9b148a7/public/app/core/directives/value_select_dropdown.ts#L249

Maybe this can be fixed in more generic way than just patching what comes from PostgreSQL or other relational database.

**Environment**:
- Grafana version: 6.1.4
- Data source type & version: PostgreSQL 10
- OS Grafana is installed on: Docker container
- User OS & Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Grafana plugins: None
- Others: N/A

**Comment by hugohaggmark** [comment]
Confirmed in Grafana v7.3.1 (6668161a88).

**Comment by kumbasar** [comment]
With the latest build [2a21f06](https://github.com/grafana/grafana/commit/2a21f067b71979c5c4a45296dcd5781766229133), I wasn't able to reproduce this `toLowerCase` issue.

It seems that the now, the current  issue is the  below `TypeError`:

```
TypeError: undefined is not an object (evaluating 'frame.fields.length')
```

Also, see below screenshot.

![Screen Shot 2021-01-24 at 08 36 05](https://user-images.githubusercontent.com/7557299/105622090-6ebfe900-5e1f-11eb-9f28-f43c6d23350f.png)
