### ISSUE TITLE
Need new Unit in Energy: kWh & MWh

### ISSUE THREAD

**Issue by mircsicz** [grafana/grafana#16747]
I'ld need kWh and MWh as a sub of the Energy Menu

I want to plot the energy-consumption in kWh but only kW (for Power) is available...

**Comment by marefr** [comment]
kWh is already supported named Kilowatt-hour (kWh), see https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/valueFormats/categories.ts#L171

Maybe you have an old Grafana version?

**Comment by mircsicz** [comment]
Argghhh, Screen Res on my Laptop didn't show the full list :-(
