### ISSUE TITLE
Unable to add Flux Datasource in Grafana V6.0

### ISSUE THREAD

**Issue by ajayanaj** [grafana/grafana#16746]
**What happened**: Unable to add Flux datasource in Grafana version 6.0, I'm getting Network Error (500) and Network Error (504). I have an another Grafana instance version 5.4.2, which working fine as expected. 

![image](https://user-images.githubusercontent.com/45065725/56662160-fd3e8e00-66c0-11e9-8d03-b3a490739445.png)

![image](https://user-images.githubusercontent.com/45065725/56662543-dd5b9a00-66c1-11e9-9b7d-d2615e96f4bb.png)

**What you expected to happen**: It should be added without any errors

**How to reproduce it (as minimally and precisely as possible)**: Add datasource>> Update credentials >> Save and test

**Anything else we need to know?**:

**Environment**:
- Grafana version: V6.0
- Data source type & version: InfluxDB(Flux) datasource and version: 5.2.9
- OS Grafana is installed on: Ubuntu 14
- User OS & Browser: MAC and Chrome
- Grafana plugins: 
- Others:

**Comment by marefr** [comment]
Please open an issue in the plugin repository: https://github.com/grafana/influxdb-flux-datasource

**Comment by ajayanaj** [comment]
@marefr Thanks for pointing this, will post the issue in flux-datasource repo.
