### ISSUE TITLE
react panel export from reactPanel to just plugin 

### ISSUE THREAD

**Issue by ypli0629** [grafana/grafana#16758]
Is there any plan to publish new @grafana/ui

**Comment by torkelo** [comment]
yes, we hope to do this soon. 

Would like to rename react panel export from reactPanel to just plugin before publish next version.

**Comment by ypli0629** [comment]
ok,3ks

**Comment by Ilshidur** [comment]
Hello @torkelo 

Is there a scheduled date for the next publish of the [`@grafana/ui`](https://www.npmjs.com/package/@grafana/ui) package ? 😄

**Comment by adrianromanko** [comment]
+1
Latest Grafana v6.1.6 release doesn't support sdk 6.0.1-alpha.0

**Comment by vrunda-thacker** [comment]
Hi @torkelo 

I tried using the react-plugins-examples, while the panel does get registered and I can see it in the visualizations, but when I select it, I get the error as below:
Failed to import plugin module TypeError: c.ReactPanelPlugin is not a constructor
(After the change done to rename ReactPanelPlugin to PanelPlugin, when trying to import PanelPlugin from @grafan/ui, the intellisense says there is not exported member as PanelPlugin)

Please help.

Note: I faced the same issue while using the Grafana master and v6.2.0-beta1 and grafana/ui @ 6.0.1-alpha.0
