### ISSUE TITLE
Grafana 2.0b: Turning on gzip compression breaks Graphite proxying

### ISSUE THREAD

**Issue by manacker** [grafana/grafana#1675]
When I set enable_gzip=true in grafana.ini using Graphite in proxy mode doesn't work anymore. Chrome reports "net::ERR_CONTENT_DECODING_FAILED". Without enable_gzip it works fine.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master, and in daily builds: 
http://grafana.org/download/builds
