### ISSUE TITLE
grafana inbuilt global variable for refresh

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#16751]
**What would you like to be added**:
Is there any global inbuilt variable for refresh? If not, can this be a feature-request?

**Comment by marefr** [comment]
What do you mean, default value for refresh in dashboards? Please explain in detail.

**Comment by debmalyapan53** [comment]
Currently there is a refresh frequency which can be set e.g 5s,10s etc. If that refresh value could be obtained as a variable, it would serve my purpose.
