### ISSUE TITLE
Data source ignoring "Content-Encoding: gzip" header

### ISSUE THREAD

**Issue by mozai** [grafana/grafana#16755]
**What happened**:
Grafana is trying to parse garbage when getting data from a Prometheus-type data source.  The query browser shows raw still-encoded bytes instead of the proper response.

**What you expected to happen**:
Grafana sees the "Content-Encoding: gzip" header and gunzips the data before trying to use it

**How to reproduce it (as minimally and precisely as possible)**:
- Trickster 1.0.4 as a Prometheus-type data source
- set the data source to "Access" = "Server" not "Browser"

**Anything else we need to know?**:
- Trickster 1.0.4 is also sending "Content-Type: application/x-gzip" which I know is a mistake on their part, but I expect to see the gunzip-decoded response in Grafana's query browser, instead i see the still-content-encoded raw bytes.  (I used tcpdump to make sure it wasn't gzip encoded version of a gzipped file -- the bytes in tcpdump and query inspector are the same.)
- a co-worker has the same problem but only when using Firefox, not Chrome -- despite the "Access" = "Server" setting for the datasource, so our browsers are no speaking directly to Trickster. (are Grafana datasources with access=server re-using headers from the webbrowser?  why?)
- sending the same query to Trickster using `curl --compressed` gets the same answer... but curl will respect the "Content-Encoding: gzip" and decode it before sending to stdout.

**Environment**:
- Grafana version: Grafana v5.4.3 (commit: 6539180)
- Data source type & version: Trickster 1.0.4
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Firefox (v63.0 and v54.0)
- Grafana plugins: Prometheus data source
- Others:

**Comment by torkelo** [comment]
Grafana does not look at the body, just forwards it, which explains why the tcpdump is the same as what you see in Query inspector.  Not sure what else you want Grafana to do? it seems like this header / encoding is not working with your browser?

**Comment by mozai** [comment]
the tcpdump isn't exactly the same: http headers are different.  I believed this meant the http body was also processes, or supposed to be processed.  That was an assumption on my part.
