### ISSUE TITLE
Repeated Gauge with InfluxDB issue 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#16762]
Results in error: 

undefined is not iterable (cannot read property Symbol(Symbol.iterator)) on the 2nd+ panels.

**Comment by torkelo** [comment]
now unable to replicate this in master :(

**Comment by andrewsav-datacom** [comment]
Copying from https://github.com/grafana/grafana/issues/15880:

**How to reproduce it (as minimally and precisely as possible):**

1. Navigate to https://play.grafana.org/d/000000054/repeated-rows?orgId=1
2. Select a single "server" variable ("backend_01" for example)
3. In "Row1" configuration, set "Repeat for" to blank
4. In the "backend_01" graph panel editor, change the visualization type to Gauge
5. In the "backend_01" graph panel editor, set "Repeat" to "server"
6. Return to dashboard
7. Select "all" option for the "server" variable
8. All four gauges briefly flash a "Query Error" red triangle, then all four gauges incorrectly display the same value.

This seems to be 100% reproducible on the current v6.1.4 at `play.grafana.org` as of the time of writing.

This is what it looks like:

![gra000](https://user-images.githubusercontent.com/27190911/56002775-be4f2680-5d17-11e9-80a7-f4e6244b1972.png)

**Comment by andrewsav-datacom** [comment]
This seems to be fine now on the current playground 6.2.0-beta2
