### ISSUE TITLE
Adding datasource is not working

### ISSUE THREAD

**Issue by uzfarid** [grafana/grafana#1676]
Tried to add 2 datasources in graylog 2.0, but none of them seems working.

- I cannot use them for importing
- I cannot use them for displaying graphs

Giving the folowing urls in datasource:

http://IP:8083/ influxdb url, access: direct

db: grafana, username/pw: root/root

Is there some issue or am I doing something wrong`?

**Comment by torkelo** [comment]
8083 is not the api port for influxdb, 8086 usually is the api port

**Comment by uzfarid** [comment]
Well I tried 8086 too.

**Comment by torkelo** [comment]
Strange, just try to do a complete page refresh (F5) after you made those changes (should not be required, but there was a bug with marking a data source as default that required a full page reload for it to take effect, fixed in master). 

Also open chrome dev tools and inspect the network requests to InfluxDB. When you try to import, do you get nothing in the dropdown for data sources:
![image](https://cloud.githubusercontent.com/assets/10999/6922298/6e629ebc-d7ca-11e4-91f9-82c315cacec3.png)

When you add a graph on a new dashboard what does the datasource selector say, do you see your datasource there? When you specify a influxdb metric name or query do you get a time series request error (red triangle to the right), check the error.

**Comment by uzfarid** [comment]
Hi

I did reload pages but no affect.

When I try to import I do not get anyhing in dropdown.

When I try to add new graph to dashboard yes I see those added data sources but queries them does not seem work. 

Attaching screen shots:

![grafana_2_edit_source](https://cloud.githubusercontent.com/assets/11738550/6938229/7d41beae-d86a-11e4-8ce4-a068abf939f0.JPG)

![grafana_2_datasources](https://cloud.githubusercontent.com/assets/11738550/6938233/89386370-d86a-11e4-9f37-c3399523627d.JPG)
![grafana_2_dashboard_import](https://cloud.githubusercontent.com/assets/11738550/6938237/918d5c06-d86a-11e4-906c-c330b91c4db0.JPG)
![grafana_2_newdashboard_sourcelist](https://cloud.githubusercontent.com/assets/11738550/6938242/9d85953c-d86a-11e4-94c8-7acae19a46b9.JPG)
![grafana_2_newdashboard_query](https://cloud.githubusercontent.com/assets/11738550/6938252/a8fd82bc-d86a-11e4-87d9-8470ee939135.JPG)

I will check more from chrome dev tools.

**Comment by uzfarid** [comment]
Hi

From devtools , i see method not allowed error:

![influxrequest_error](https://cloud.githubusercontent.com/assets/11738550/6938362/80990250-d86b-11e4-8f49-356b5c523f34.JPG)

**Comment by uzfarid** [comment]
Should request be like http://192.168.2.217:8086/db/jmeter/series?p=root&q=list+series+%2Fjmete%2F&u=root this?

**Comment by torkelo** [comment]
Please change to influxdb 0.8,  0.9 is not supported for importing dashboards from, are you using influxdb  0.9?

and that query is not valid InfluxDB 0.9 query (InfluxDB 0.9 is radically different, new api and query language)

**Comment by torkelo** [comment]
And by change, I mean go into the data source edit view and change datasource type to InfluxDB 0.8.x

**Comment by uzfarid** [comment]
Grafana 1.0 is working fine with Influxdb 0.9. Seems with Grafana 2 and influxdb 0.9 it is not possible to add new graphs. Will there be support for influx 0.9 later on?

**Comment by torkelo** [comment]
grafana 1.x does not work at all will influxdb 0.9.x,  it had new api that is not backward compatible. are you sure you are using influxdb 0.9?

**Comment by uzfarid** [comment]
Hi

You are right, i had influx 0.8. I thought by default it installs latest version.

I also made graph working. I had wrong url in datasource. "http://192.168.2.217:8086" is correct and i had "http://192.168.2.217:8086/db"

Only issue left now is grafana datasource not showing up in Import page. Will double check again to see if i did something wrong

thanks

**Comment by uzfarid** [comment]
Hi

You are right, i had influx 0.8. I thought by default it installs latest version.

I also made graph working. I had wrong url in datasource. "http://192.168.2.217:8086" is correct and i had "http://192.168.2.217:8086/db"

Only issue left now is grafana datasource not showing up in Import page. Will double check again to see if i did something wrong

thanks

**Comment by uzfarid** [comment]
I had to re-add grafana datasource as Influxdb 0.8 type then import worked. thanks
