### ISSUE TITLE
no data when time is 0-8

### ISSUE THREAD

**Issue by gavinage** [grafana/grafana#16765]
my version is  5.4.2

my location is china , timezone is +8

for example when 2:00am,  there is no data on  00:00-2:00
 because the index is yesterday  

that:
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["argus-metric-2019.04.24"]}

but now time is  2019.04.24  2:00  
so，it is a bug ?

**Comment by gavinage** [comment]
but now time is 2019.04.25 2:00

**Comment by torkelo** [comment]
Elasticsearch index names always use UTC time, make sure when you create your index name you use UTC

**Comment by gavinage** [comment]
ok  ，3q，  so I  find some method to solution it.
if i  look chart at 2:00am  , i can change the 'Custom range' to  now+6h

**Comment by panghuangzhiquan** [comment]
> ok ，3q， so I find some method to solution it.
> if i look chart at 2:00am , i can change the 'Custom range' to now+6h

I have the same problem, could you tell me how to fix it ?
