### ISSUE TITLE
reset_password_command issue with non id 1 admin account

### ISSUE THREAD

**Issue by babs** [grafana/grafana#16769]
**What happened**:

In https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-cli/commands/reset_password_command.go : assumption be is made that first account is id 1 and breaks reset-password-command if not 1.

It happens when using clustered database servers like mysql multimaster or galera

**What you expected to happen**:

Use the admin username instead of assuming it's id is 1.

**How to reproduce it (as minimally and precisely as possible)**:

Configure a mysql server with my.cnf

```
[mysqld]
auto_increment_increment = 2
auto_increment_offset  = 1
```

Start grafana against it, try to reset the password.

You can edit the row, change the is back to 1, try the reset, it works.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.1.0 (03346b6)
- Data source type & version: mysql 
- OS Grafana is installed on: Debian
- User OS & Browser: N/A
- Grafana plugins: None
- Others:

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
