### ISSUE TITLE
Grafana Demo - Direct Link Render Image Error

### ISSUE THREAD

**Issue by Dormanator** [grafana/grafana#16776]
**What happened**:
When attempting to use the Grafana demo (https://play.grafana.org) to render an image of a panel (https://play.grafana.org/render/d-solo/000000012/grafana-play-home?orgId=1&from=1556223897249&to=1556231097250&panelId=2&width=1000&height=500&tz=America%2FLos_Angeles) a server error "Rendering Failed." is returned.

**What you expected to happen**:
An image is rendered and returned for the panel in question.

**How to reproduce it (as minimally and precisely as possible)**:
Visit https://play.grafana.org/render/d-solo/000000012/grafana-play-home?orgId=1&from=1556223897249&to=1556231097250&panelId=2&width=1000&height=500&tz=America%2FLos_Angeles

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: Demo
- Data source type & version: Demo
- OS Grafana is installed on: Demo
- User OS & Browser: Windows 7, Chrome 
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
thanks for reporting this! 

@jimnagy any ideas why image rendering is not working on the new site? Is it using the new rendering service?

**Comment by jimnagy** [comment]
Yeah, it looks like play did not have access to the render service on the new cluster after it was migrated.  I have fixed this and verified it's working now.  Thanks for bringing this to our attention!
