### ISSUE TITLE
2.0b1: Editing a dashlist does not update the display of the dashlist automatically

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1677]
If you edit a dashlist the display does not update when focus leaves the input field as is typical in Grafana.  Further, if you close and go 'Back to dashboard' it doesn't update either.  If you click edit json, update, close, it does update.

**Comment by torkelo** [comment]
It seems this problem is only for the `Limit number to` option, all the other options causes a refresh. Will add a auto refresh when you change limit option, thanks for reporting this!
