### ISSUE TITLE
[FeatureRequest] Plugins - Better cache-busting on plugin assets

### ISSUE THREAD

**Issue by dzbarsky** [grafana/grafana#16771]
**What would you like to be added**:
I would like to run the server with an environment variable/flag containing an ID to be used for cache busting, rather than using `Date.now()` on the client as seen in https://github.com/grafana/grafana/blob/7aeae84c523fda5f694758d2eb6aac6053809c81/public/app/features/plugins/plugin_loader.ts#L35-L39

**Why is this needed**:
The current implementation ensures that nothing is ever in the cache, while in reality we could use a content hash/git commit hash/etc. to do much better. This needlessly slows down grafana (in our case by hundreds of milliseconds as our users of our Grafana setup are spread out across US and Europe).

I can provide a patch if you give some pointers as to how you'd like to see this implemented.

**Comment by torkelo** [comment]
This is for external plugins, one way would be to use plugin version somehow.
