### ISSUE TITLE
LDAP - New users are not fully created, breaks login for "next new user"

### ISSUE THREAD

**Issue by willnx** [grafana/grafana#16775]
**What happened**:
I setup LDAP auth and noticed that after 1 user signed in, all subsequent users would get an "Error while trying to authenticate user" upon login.

While tailing the logs, I saw this (which looks similar to https://github.com/grafana/grafana/issues/8024):
```
grafana_1        | t=2019-04-25T21:29:34+0000 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.email"
```
After a bit of poking around, I noticed that the user was blank on the configuration page:
![image](https://user-images.githubusercontent.com/12264343/56769866-5234df80-6767-11e9-9adc-7d0fbcb80982.png)

If I deleted the user, the next user could login, but same issue would happen for the "next next" user 😅 
If I had the user click on an invisible button in the bottom-left and fill in their username, name, email and save it, then the next user was able to successfully login via LDAP.
![image](https://user-images.githubusercontent.com/12264343/56770057-de470700-6767-11e9-840a-036e91ab56fb.png)

**What you expected to happen**:
The _auto signup_ feature pulls the information from LDAP and fills it in, or the user fails to be logged in (like, if grafana can't pull this data from my LDAP server) and no account is 1/2 created.

**How to reproduce it (as minimally and precisely as possible)**:
Log into my Grafana server as an LDAP user, but don't fill in your user-details `¯\_(ツ)_/¯`

**Anything else we need to know?**:
Grafana is a wonderful product!
Also, here's what my `ldap.toml` looks like:
```
[[servers]]
host = *REDACTED*
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = true
bind_dn = *REDACTED*
bind_password = *REDACTED*
search_filter = "(sAMAccountName=%s)"
search_base_dns = *REDACTED*

[server.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"
```
And here's the LDAP section in my `grafana.ini`
```
#################################### Auth LDAP ###########################
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
```

**Environment**:
- Grafana version: 6.1.4
- Data source type & version: Influxdb 1.7
- OS Grafana is installed on: Ubuntu 18.04 _vis-a-vis_ Docker image
- User OS & Browser: Windows 10, Chrome, Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
your ldap config attributes must be not matching the attributes used by your ldap server

```toml
[server.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"
```

Specifically username & email seem to not return any values from your ldap server,   check your ldap server what attribute names Grafana should read

**Comment by willnx** [comment]
Hi @torkelo

You know, I thought the same thing too, but when I query my LDAP server, I get answers for `mail` and `sAMAccountName`:

```
In [9]: conn.search(search_base=base, search_filter='(&(objectclass=User)(sAMAccountName=willhn))', attributes=['mail', 'samaccountname',])
Out[9]: True

In [10]: conn.entries
Out[10]: 
[DN: CN=Willhite\, Nicholas,OU=Customer Service,OU=WA Seattle,OU=US Users,DC=corp,DC=emc,DC=com - STATUS: Read - READ TIME: 2019-04-26T09:04:57.471261
     mail: Nicholas.Willhite@emc.com
     sAMAccountName: willhn]
```

I upped the logging for ldap to debug in the `grafana.ini`, and all I see are the results, which as you figured, are empty:
```
grafana_1        | t=2019-04-26T16:13:02+0000 lvl=dbug msg="Ldap Search For User Request" logger=ldap info="(ldap.SearchRequest) {\n BaseDN: (string) (len=21) \"DC=corp,DC=emc,DC=com\",\n Scope: (int) 2,\n DerefAliases: (int) 0,\n SizeLimit: (int) 0,\n TimeLimit: (int) 0,\n TypesOnly: (bool) false,\n Filter: (string) (len=23) \"(sAMAccountName=willhn)\",\n Attributes: ([]string) {\n },\n Controls: ([]ldap.Control) <nil>\n}\n"
grafana_1        | t=2019-04-26T16:13:02+0000 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc0008c45b0)({\n DN: (string) (len=90) \"CN=Willhite\\\\, Nicholas,OU=Customer Service,OU=WA Seattle,OU=US Users,DC=corp,DC=emc,DC=com\",\n FirstName: (string) \"\",\n LastName: (string) \"\",\n Username: (string) \"\",\n Email: (string) \"\",\n MemberOf: ([]string) {\n }\n})\n"
```

Is there some sort of trace logging for grafana? I'm not really sure why I can pull that data via the Python [ldap3](https://ldap3.readthedocs.io/) lib, but Grafana cannot.

However, this still feels like a valid bug to me.
The happy path works, but the behavior when encountering an error is unexpected. 
Like, if Grafana needs those attributes to create a user account, and to login you have to have a user account, then to me, if it cannot pull those attrs via LDAP, then it should fail the login/auto-create-account, right? 

So the issue isn't in the happy path working/not working in my eyes. The issue is in how the application handles the error.

Again, thanks for taking the time to listen/help a derp like me :)

**Comment by DanCech** [comment]
I tend to agree that we shouldn't allow creation of a user with an empty username, since it will almost always indicate a configuration problem.  One option might be to automatically use the user's email address for their username in this case.  The reason it causes such a problem is that there is a unique index on the username column, so the database will only ever allow a single user with an empty username to exist.  Thus the behavior you describe where one person can log in, but subsequent users cannot because they have "duplicate" (empty) usernames.
