### ISSUE TITLE
Oauth login with keycloak

### ISSUE THREAD

**Issue by aaktaev** [grafana/grafana#16772]
`msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="Post : unsupported protocol scheme \"\"" `

**What happened**:

Added to grafana.ini:

```
      GF_AUTH_GENERIC_OAUTH_ENABLED:                   true
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID:                 grafana
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:             fd4d74e2-379f-4ba6-891b-7c26dc3826c5
      GF_AUTH_GENERIC_OAUTH_SCOPES:                    openid email name
      GF_AUTH_GENERIC_OAUTH_AUTH_URL:                  https://auth.domain/auth/realms/ldap/protocol/openid-connect/auth
      GF_AUTH._GENERIC_OAUTH_TOKEN_URL:                https://auth.domain/auth/realms/ldap/protocol/openid-connect/token
      GF_AUTH_GENERIC_OAUTH_API_URL:                   https://auth.domain/auth/realms/ldap/protocol/openid-connect/userinfo
      GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE:  true
      GF_SERVER_DOMAIN:                                <set to the key 'hostname' in secret 'kube-prometheus-grafana'>  Optional: false
      GF_SERVER_ROOT_URL:                              https://grafana.domain
      GF_AUTH_ANONYMOUS_ORG_NAME:                      grafana.domain
      GF_USERS_ALLOW_SIGN_UP:                          true
```

**What you expected to happen**:
Logined successfully.

For OAuth was used keycloak

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: gke
- Grafana version: 5
- Data source type & version:
- OS Grafana is installed on: gke
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by auzieman** [comment]
Me too,

I suspect its this funny issue when behind proxies and in things like docker and the inside port is not the same as the outside port.. Root Url should be sufficient but in auth I think its a combination of domain, port and path

Anyone else seen this?  KeyCloak actually includes grafana as part of their test suite but seems using the two together for auth isn't well documented (ie by example).

**Comment by aaktaev** [comment]
Found typo in vars. All works.

**Comment by besteinert** [comment]
For everyone's information, the typo is in line 6:
"GF_AUTH**.**_GENERIC_OAUTH_TOKEN_URL:"

The dot shouldn't be there.

**Comment by DikshaTomar101** [comment]
can anyone tell me how can i integrate graphana to keycloak

**Comment by aaktaev** [comment]
You need to use https://grafana.com/docs/grafana/latest/auth/generic-oauth/#generic-oauth-authentication
