### ISSUE TITLE
able to get the list of entries from ES to be queried in mysql and display as label

### ISSUE THREAD

**Issue by vamshi8** [grafana/grafana#16777]
Hi everyone,

I have a feature request if it is not already there.
I have ES, I was able to project the graph, I have a requirement where the plot entries(example an ID), should make another query to mysql for its entry for equivalent name and display it as a label instead of the ID from ES output.

**Comment by marefr** [comment]
Duplicate of #1153

**Comment by marefr** [comment]
Grafana already supports Elasticsearch and MySQL as datasources. I'm afraid the only solution to this currently is to store both id and label in Elasticsearch.
