### ISSUE TITLE
Anonymous access to dashboards redirects back to login if auto-refresh is used

### ISSUE THREAD

**Issue by Malvineous** [grafana/grafana#16780]
**What happened**:

After enabling anonymous logins, and disabling the login page, dashboards can be opened directly from a URL without logging in as expected.  However if the dashboard is set to automatically refresh, then upon the first refresh it redirects the browser back to the login page.

Reloading the URL often displays the dashboard (with data) for a split second before redirecting back to the login page.

**What you expected to happen**:

The dashboards should show updated data upon refresh, and not redirect anywhere else.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start in Docker
```
docker run \
        -d \
        --rm=true \
        -p 3000:3000 \
        -v "/srv/docker/grafana/data:/var/lib/grafana" \
        -e "GF_AUTH_DISABLE_LOGIN_FORM=true" \
        -e "GF_AUTH_ANONYMOUS_ENABLED=true" \
        -e "GF_AUTH_ANONYMOUS_ORG_NAME=Main Org." \
        -e "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer" \
        grafana/grafana
```
2. Create a dashboard, set auto refresh to 10 sec.
3. Open a new private/incognito window, paste dashboard URL in
4. Observe data shows up initially, but after 10 seconds to 5 minutes, the browser will get redirected to the login page.

**Anything else we need to know?**:

When loading the dashboard, the last request is an XHR one to `query?db=xxx` which succeeds (200 OK).  10 seconds later the same request is issued again, but this one fails (401 Unauthorized).

The server properties page (and the `docker logs` output) shows that the `GF_AUTH` environment variables are being picked up as expected.

Manually refreshing the dashboard appears to work, it's only the auto-refresh that seems to trigger a redirect to the login page.

**Environment**:
- Grafana version: `latest` from Dockerhub (v6.1.4 (commit: fef1733))
- Data source type & version: Influx
- OS Grafana is installed on: Docker image
- User OS & Browser: Firefox
- Grafana plugins: None in addition to what comes in the Docker image

**Comment by marefr** [comment]
Not able to reproduce this. Please use chrome developer tools/network tab and check preserve log to get all the requests happening and include request/response generating the redirect. Also check Grafana server log for any related messages.

**Comment by Malvineous** [comment]
Nothing in the Grafana server log (by which I assume you mean `docker logs` as there's nothing in `/var/log/grafana/` inside the container).

Which web requests would you like?  Here's the last successful one:

```
GET /api/datasources/proxy/1/query?db=stats&q=SELECT%20last(%22data_rate%22)%20%20%2F%201000000%20FROM%20%22dsl%22%20WHERE%20(%22dir%22%20%3D%20%27up%27)%20AND%20time%20%3E%3D%20now()%20-%207d%20GROUP%20BY%20time(2h)%20fill(null)&epoch=ms HTTP/1.1
Host: localhost:8085
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8085/d/K0cne2kZk/gik?orgId=1&refresh=10s
X-Grafana-Org-Id: 1
DNT: 1
Connection: keep-alive
Cookie: redirect_to=%252Fd%252FK0cne2kZk%252Fgik%253ForgId%253D1

HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Encoding: gzip
Content-Type: application/json
Date: Fri, 26 Apr 2019 07:43:55 GMT
Expires: -1
Pragma: no-cache
Request-Id: 0b55ae91-67f7-11e9-8637-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.6.1
X-Request-Id: 0b55ae91-67f7-11e9-8637-000000000000
Content-Length: 409
```
And here's the failure 10 seconds later, no other requests in between:
```
GET /api/datasources/proxy/1/query?db=stats&q=SELECT%20last(%22data_rate%22)%20%20%2F%201000000%20FROM%20%22dsl%22%20WHERE%20(%22dir%22%20%3D%20%27up%27)%20AND%20time%20%3E%3D%20now()%20-%207d%20GROUP%20BY%20time(2h)%20fill(null)&epoch=ms HTTP/1.1
Host: localhost:8085
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8085/d/K0cne2kZk/gik?orgId=1&refresh=10s
X-Grafana-Org-Id: 1
DNT: 1
Connection: keep-alive
Cookie: redirect_to=%252Fd%252FK0cne2kZk%252Fgik%253ForgId%253D1

HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Expires: -1
Pragma: no-cache
Date: Fri, 26 Apr 2019 07:44:05 GMT
Content-Length: 26
```
After this failure, the web page tries `/api/login/ping` which also returns 401, then it goes to `/logout` (302) and then ends up at `/login`.

**Comment by Malvineous** [comment]
I've investigated this further, and I'm unable to reproduce the issue on another machine, but the first one continues to give me problems.

Looking at the server settings something odd is happening.  When the container is first started, all the settings coming from environment variables (like `GF_AUTH_DISABLE_LOGIN_FORM=true`) show in the logs as being picked up, and indeed the 'server settings' UI panel shows `auth/disable_login_form` as `true`.  However if I give it a few minutes and reload the page, all the values have returned to their defaults and `auth/disable_login_form` is now showing `false`.  However it only remains this way for a few seconds, but this is long enough for the auto refresh to send me back to the login page.  Watching this further, every few minutes the settings revert back to the defaults for just a few seconds.

This appears to explain the problem, however the new question is why would these server settings spontaneously change every five minutes or so, and only for a few seconds?

Looking inside the container and listing the environment variables shows that they are all still set, and it's the same container the whole time (i.e. it's not a situation where the old container dies and a new one is launched with different settings.)  Inside the container the PID of the Grafana executable doesn't change, so it's not being restarted inside the container either.

Continuing to investigate this further, I have found something very odd.  If I continually refresh the server settings page, and compare the correct settings with the incorrect ones, the footer on the page is different.  When the settings are correct the footer reads `Grafana v6.1.4 (commit: fef1733)` however when the incorrect settings become active, the footer instead reads `Grafana v6.1.3 (commit: 9504db8)`.

This can't be an issue with the browser cache because I can Shift+Reload the page, use incognito/private mode, and even connect from a different PC and still get the same behaviour.  In fact, when another PC viewing the dashboard gets redirected to the login screen, it even says `6.1.3` on the bottom of the login page.

Using `curl` however, I only ever get the older version, I've run it in a loop for a while and it will never come back saying `6.1.3`.  Running `curl` inside the Docker container also shows the older version:
```
$ curl -s http://localhost:8085/login | fold | grep latestVersion
"production","hasUpdate":false,"isEnterprise":false,"latestVersion":"6.1.3","ver
$ docker exec ff56 cat VERSION
6.1.4
$ docker exec ff56 curl -s localhost:3000 | fold | grep latestVersion
"production","hasUpdate":false,"isEnterprise":false,"latestVersion":"6.1.3","ver
```
So now I'm really confused.  Which version am I running and why does it keep alternating between two different versions!?
```
$ docker pull grafana/grafana
Using default tag: latest
latest: Pulling from grafana/grafana
Digest: sha256:3b0036ac89b165101e922847257ac0beeffef762161ee1fcea5466b45248dc9e
Status: Image is up to date for grafana/grafana:latest
```

**Comment by Malvineous** [comment]
Ok, pretty sure this is a Docker issue now.  If I grep the home page for the version number, both inside and outside the container, then the `subTitle` field consistently shows `6.1.4` inside the container, but from outside the container it periodically alternates between `6.1.4` and `6.1.3`.

When the web page sends an XHR request for the server settings, it returns the 'instance name' which in this case translates to the container name.  When the wrong settings/version come back, the instance name also changes.  In this case the wrong settings are attached to a Docker container that was terminated a day ago during a Docker daemon restart, but it failed to terminate cleanly and was forced to exit.  I can't find any trace of it on my system, but apparently it periodically comes back to life when this new Grafana container is running.  (It doesn't come to life if the new Grafana container has been stopped - `curl` never returns any responses.)  Terminating the new container also suspends the zombie container.

I have tried using `docker rmi` to delete the image attached to the previous version in the hope that this might help, but alas it did not.  I also tried changing the port mapping so that I was connecting to the new Grafana version on a port I hadn't used for anything before, but alas the old zombie version kept taking over the new port too.  I guess since restarting the Docker daemon doesn't fix the problem it might take a reboot to properly terminate this zombie container.

Sorry for the noise, but I guess if you have any odd issues in the future that randomly come and go, and the user is running Grafana inside Docker, you might suggest a reboot or at the least polling the version to see if it changes when the issue surfaces.

**Comment by Malvineous** [comment]
Well just for the sake of completeness, the problem did indeed end up being an old Docker container hanging around that the Docker CLI was unable to see.  I found it by running `ps aux | grep runc` and looking for any containers that weren't in the list shown with `docker ps`.  Sure enough there was a single extra container and it matched the instance name reported by the wrong Grafana version.

A simple `kill` command later and Grafana is now working as intended.
