### ISSUE TITLE
Docker build from master broken

### ISSUE THREAD

**Issue by sysrun** [grafana/grafana#16789]
Tried to build the current master in docker:

`Step 3/37 : COPY Gopkg.toml Gopkg.lock ./
COPY failed: stat /var/lib/docker/tmp/docker-builder185434499/Gopkg.toml: no such file or directory`

Gopkg.toml is not in the master branch (but in dev)

**Comment by daniellee** [comment]
@sysrun how did you try to build it? I tried `make build-docker-dev` and it worked for me (on Linux).

**Comment by sysrun** [comment]
i checked out the current master and tried like its described [here](https://github.com/grafana/grafana#building-anywhere-slower).

The point is: The Gopkg.toml file is missing in the master branch

**Comment by sysrun** [comment]
`make build-docker-dev` is not working for me as i don't have the dev env (go etc.) installed.
As far as i understand, the way descibed in the docs, it should be possible to build an image without a running dev env: 

> There are two different ways to build a Grafana docker image. If your machine is setup for Grafana development and you run linux/amd64 you can build just the image. **Otherwise, there is the option to build Grafana completely within Docker.**

So the options are:
`make build-docker-full` or `docker build -t grafana/grafana:dev`

Both are failing because the master branch is missing the "Gopkg.toml" which is needed by the Dockerfile -> `COPY Gopkg.toml Gopkg.lock ./`

**Comment by KevinYeti** [comment]
> `make build-docker-dev` is not working for me as i don't have the dev env (go etc.) installed.
> As far as i understand, the way descibed in the docs, it should be possible to build an image without a running dev env:
> 
> > There are two different ways to build a Grafana docker image. If your machine is setup for Grafana development and you run linux/amd64 you can build just the image. **Otherwise, there is the option to build Grafana completely within Docker.**
> 
> So the options are:
> `make build-docker-full` or `docker build -t grafana/grafana:dev`
> 
> Both are failing because the master branch is missing the "Gopkg.toml" which is needed by the Dockerfile -> `COPY Gopkg.toml Gopkg.lock ./`

Thanks god you have open this issue. I have tried to check my problem for a whole day.

I have the same problem with you. I had checked the file which is absolutely not at it's right position.
I had my both two laptops cloned the master branch with one had the development environment while the other not. But none worked for me .

**Comment by bergquist** [comment]
Works fine locally if you build it before since that step is cached. with `--no-cache` this is reproducible. PR incoming.
