### ISSUE TITLE
Support new Loki labels query

### ISSUE THREAD

**Issue by Kuqd** [grafana/grafana#16788]
**What would you like to be added**:

Loki labels endpoint `/api/prom/labels` will change and now will accept a time range so that we can fetch labels from storage, currently it default to 6 hours if nothing is passed.

example:

```
label names -> /api/prom/labels?start=1556265056101000000&end=1556286656101000000
label values -> api/prom/label/{name}/values?start=1556265056101000000&end=1556286656101000000
```

**Why is this needed**:

This fixes an issue on Loki explore where labels would disappear after ingestion was flushed since labels where only queried from ingestors.

see: 
https://github.com/grafana/loki/issues/453
https://github.com/grafana/loki/pull/521

**Comment by marefr** [comment]
@Kuqd talked with @davkal about this. Since Loki is still beta it should be fine introducing a breaking change. I asked David to reach out to you, but maybe he haven't had time for that yet so writing here instead.

**Comment by kaydelaney** [comment]
@Kuqd Just to clarify: Is the endpoint being changed from `/api/prom/label` to `/api/prom/labels`, or is that a typo in your original post? Thanks!

**Comment by Kuqd** [comment]
no the path doesn't change, its a typo sorry.

**Comment by Kuqd** [comment]
We still haven't deployed it also, @gouthamve is supposed to do the review.
