### ISSUE TITLE
Set home dashboard on user and org level

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#1678]
I would like to edit the Home dashlist but there is no 'save' button:
![image](https://cloud.githubusercontent.com/assets/917241/6922404/2b66b944-d7cb-11e4-999b-ea4456e8a9ea.png)

If you click away you get the unsaved dialog warning, and if you choose to save it actually creates one in the db:
![image](https://cloud.githubusercontent.com/assets/917241/6922368/e8fea580-d7ca-11e4-9dc1-6a63cae3d572.png)

Still, this one in the db is not the default page when you login and I can't find anyway to make it the default [like you could in 1.9.1].  My preference would be that each user can have their default home page from the db, which if unconfigured could use the read-only 'Home' like it appears we have today.

**Comment by torkelo** [comment]
This was one feature that was left on the cutting room floor for 2.0, Might have time to implement it for 2.0  but it might be pushed to 2.1

**Comment by jlwise** [comment]
Hey @maddenca a temporary fix, you can go into the public/dashboards folder and edit the home.json and manually edit them until the feature is added.

**Comment by tmonk42** [comment]
+1 on being able to edit the "Home" dashboard

**Comment by Akeru** [comment]
+1

**Comment by pavleec** [comment]
+1

**Comment by phrend** [comment]
I'd like to customize this page as well - thanks to @jlwise for the tip on how to hack the file manually in the meantime.

**Comment by OliverKuhn** [comment]
+1 very useful feature with a big installation while users have totally different focus on the data.

**Comment by hanej** [comment]
+1

**Comment by dforste** [comment]
+1

**Comment by tamarintech** [comment]
+1

**Comment by syabro** [comment]
+1

**Comment by mordaha** [comment]
+1

**Comment by Slach** [comment]
+1

**Comment by AlekSi** [comment]
+1

**Comment by eliperelman** [comment]
As a workaround, you can redirect the user to the desired dashboard in home.json by using something similar to this in `rows`:

```json
"rows": [
    {
      "height": "50px",
      "panels": [
        {
          "id": 1,
          "span": 12,
          "type": "text",
          "mode": "html",
          "title": "Initializing...",
          "content": "<script>window.location = 'dashboard/script/home';</script>"
        }
      ]
    }
  ],
```

**Comment by sc0rp10** [comment]
@eliperelman so dirty 😄

**Comment by eliperelman** [comment]
@sc0rp10 yep, hacks!

**Comment by xiaoping378** [comment]
+1, i found the play demo site is OK, but the master code can't do that --- custom the home page

**Comment by tuxinaut** [comment]
+1

**Comment by damm** [comment]
+1

**Comment by s80275** [comment]
+1

**Comment by hmilkovi** [comment]
+1

**Comment by pasancario** [comment]
+1 It will be really usefull to create a Main Dashboard with Tag Filtering as a primary view. In actual configuration, is really basic to have a complete view of existent dashboards in an Organization.

**Comment by damm** [comment]
I kinda wanted to nest it; one large custom dashboard leading to several mini dashboards... if you have a lot it kinda gets messy and I love having everything on a single page without scrolling.

**Comment by kivlara** [comment]
+1

**Comment by venkatdba64** [comment]
I am using whisper db where can i find the saved dashboards in whisper. (OR)  where does it store

Thanks

**Comment by torkelo** [comment]
Grafana does not store dashboards in whisper. Grafana saves users and dashboards in it's own database (/var/log/grafana/grafana.db if you use sqlite3, or in mysql or postgres is you configured that)(

**Comment by synthead** [comment]
+1

**Comment by m0nikasingh** [comment]
+1 :)

**Comment by oiooj** [comment]
+1

**Comment by alvaromunoz** [comment]
+1

**Comment by utkarshcmu** [comment]
Started some work in #4251

**Comment by hugoren** [comment]
I look at the above all the answers, but I still don't understand

**Comment by torkelo** [comment]
Understand what?

**Comment by hugoren** [comment]
oh, how to set the "Home page"

**Comment by hugoren** [comment]
grafana'version is 2.6

**Comment by hugoren** [comment]
I see your vedio on YouTube too. You are very greate!
https://www.youtube.com/watch?v=sKNZMtoSHN4&index=7&list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2

**Comment by torkelo** [comment]
Implemented and merged to master, will be included in 3.0 stable (or 3.0 beta2 if that happens) 

![image](https://cloud.githubusercontent.com/assets/10999/14232930/005e8c98-f96e-11e5-9675-9728cfdc6262.png)

![image](https://cloud.githubusercontent.com/assets/10999/14232929/f768b3f2-f96d-11e5-8447-3cca8ab3819f.png)

**Comment by commarla** [comment]
:+1: Thanks!

**Comment by synthead** [comment]
Wow, this is great.  Thanks a lot!

**Comment by jaegr** [comment]
I can only select "Default" (using beta3).

**Comment by utkarshcmu** [comment]
@jaegr i guess you need to star the dashboard which you need to make as home page. Then you will be able to select it instead of default.

**Comment by torkelo** [comment]
Will a tooltip to help describe the fact that the dropdown only shows starred dashboards

**Comment by bienkma** [comment]
@utkarshcmu thanks a lot!

**Comment by utkarshcmu** [comment]
@bienkma Its @torkelo we all should thank for this great tool and its lightening fast development. :)

**Comment by hailthemelody** [comment]
Pardon the necrobump: what is the rationale behind the home Dashboard needing to be starred before it shows up in `Profile > Preferences > Home Dashboard`? Personally, I would rather see a list of all available options. I would be happy to add this functionality if it's the consensus.

**Comment by torkelo** [comment]
It's a simple select drop down, thousands of dashboards would not be nice there,  so limit to only starred.  Why is this a problem?

**Comment by uhriap** [comment]
You can't star dashboard stored on disk. For db boards "star, change config, unstar" is not very pleasant way too.

**Comment by willneumob** [comment]
This doesn't seem to show up in 4.0 at all. I cannot see it on the Org Management screen or User Management screens.

**Comment by torkelo** [comment]
It's there.  Sure your on 4.x?

Should be a preferences section, where one option is Home dashboard

**Comment by willneumob** [comment]
Sorry, found it, I just got "Org Settings" and "Org Preferences" mixed up. Thanks!

**Comment by sbcdave** [comment]
+1 to being able to edit the home dashboard. Using the new default for the Org lets me create a new dashboard to serve as home, but it also means that the new dashboard "pseudo-home" is now in my dashlist, which I don't like. Thanks for all you guys do.

**Comment by trent** [comment]
+1 to editing Home dashboard without requiring creating a new dashboard and setting that as the new default for user or org.

**Comment by ageis** [comment]
This still doesn't work. I tried setting the Organization default dashboard id through the API, the request was accepted but it didn't stick. In the dropdown under org preferences, nothing appears other than 'Default'.

**Comment by torkelo** [comment]
@ageis strange, we have no reports on this failing. What was the command you sent? does it work when you change it from the UI ?

**Comment by ageis** [comment]
@torkelo sorry, I now set it through the UI after having to "star" it. (I missed or misread that hint...) however, the API call should've worked... it was like this.
```
curl -XPUT -H "Authorization: Bearer redacted" localhost:3000/api/org/preferences -d@org.json
```

org.json:
```
{
  "theme": "dark",
  "homeDashboardId":3,
  "timezone":"utc"
}
```

**Comment by torkelo** [comment]
Try setting content type header

**Comment by calmh** [comment]
We're pushing a setup through ansible with a dashboard as JSON. There seems to be no way to set this (only, apart from "Home") dashboard as the default, because it comes from on disk JSON?

**Comment by joaogvmoura** [comment]
![image](https://user-images.githubusercontent.com/37338311/41064568-4eefd3b0-69b2-11e8-84f4-b680d0f90ead.png)

Only "Default" dashboard available in the field even if I follow the tip to start the dashboard and try after.

Grafana 5.0

**Comment by fake-name** [comment]
Ok, it's been 3 years, this issue is marked as "fixed", but it's **still** present.

Either the default home dashboard needs to be *not editable*, or you need to be able to save changes you make to it.

This issue needs to be re-opened.

**Comment by torkelo** [comment]
You can set a custom home dashboard in org or profile settings. You can save changes to the default home dashboars using the save as feature in the dashboard settings view.

**Comment by ramato-procon** [comment]
@torkelo is it possible to provision the default dashboard for the default org? My grafana installation runs without persistence in a container, so users will be deleted at container recreation (linked with github they are recreated at sign in automatically).

**Comment by torkelo** [comment]
Not currently, we need to add org & user provisioning for that

**Comment by kahootali** [comment]
hey @torkelo , Is there a way we can create any other dashboard as home dashboard e.g. I want to set `cluster status`, so whenever a user signs in, he sees that rather than the home page. The method mentioned above using Preferences needs manual  intervention, I want it to be automatic, isn't there any flag or variable that can be set?

**Comment by torkelo** [comment]
You can set it in Organization preferences, it will be used for all users who have not defined their own home dashboard

**Comment by kahootali** [comment]
I would have to open dashboard for it, I don't want that rather I want when I am setting up grafana through the grafana.ini config, at that point is there any way to edit it?

**Comment by gilescope** [comment]
Makes your product look bad when you have an edit button that doesn't have a save. Disable edit or add save *please*.

**Comment by torkelo** [comment]
What? There is a save button

**Comment by fake-name** [comment]
The point is the save button *doesn't work*. Either it should work (and save the home page), or the home page should not be editable.

Having something be editable, and have a save button, only to have the save button just throw your changes away is actively user-hostile.

**Comment by sbcdave** [comment]
Agreed


George "Dave" Goldsmith
KWH Data Acquisition Lead
ECE | Veteran | Pilot | Medic
425.268.1938 | dave@kilowattsforhumanity.org

**Comment by torkelo** [comment]
> The point is the save button doesn't work. Either it should work (and save the home page), or the home page should not be editable.

We have not reports that there is save button that does not work, can you open a new issue for that and detailed instructions on how to replicate?

**Comment by sbcdave** [comment]
I think he's indirectly reporting the same thing I did, and the same thing
others have, that the home page is not editable, but he's also mentioning
what I failed to, it seems like it is editable, but when you save the
changes don't persist.


George "Dave" Goldsmith
KWH Data Acquisition Lead
ECE | Veteran | Pilot | Medic
425.268.1938 | dave@kilowattsforhumanity.org

**Comment by torkelo** [comment]
So nothing to do with this issue. It is editable and you can save it using save as button. Will create a new dashboard that you can set as your new home dashboard (either on org or profile level)

**Comment by sbcdave** [comment]
I haven't tried it in a while and haven't upgraded to 5 yet, but I recall
there being a save button when I was "editing" the home page, that
basically did nothing because it didn't persist, and was frustrating.
That's why I related to this comment and agreed.


George "Dave" Goldsmith
KWH Data Acquisition Lead
ECE | Veteran | Pilot | Medic
425.268.1938 | dave@kilowattsforhumanity.org

**Comment by torkelo** [comment]
Strange, we have never had a save button on the default home dashboard.

**Comment by umeshabhat** [comment]
+1

**Comment by marefr** [comment]
@umeshabhat why are you +1 this? It's already been implemented long time ago.

**Comment by umeshabhat** [comment]
@marefr I've scoured the internet and still haven't found a solution :(

Although I do appreciate the suggestions to update the organization details through the API
- http://docs.grafana.org/http_api/org/#organization-api
- https://community.grafana.com/t/change-home-dashboard/7441/13

We would still appreciate provisioning in this regard. It would be nice to include it in a configuration that we may execute during our `docker-compose` builds.

Do let me know if I tagged the wrong issue and point me in the right direction. **Much Appreciated**.

**Comment by umeshabhat** [comment]
Also looking into this at the moment http://docs.grafana.org/tutorials/api_org_token_howto

**Comment by marefr** [comment]
@umeshabhat then it's the following feature request, #10266, you're interested in. Please always use the "Pick your reaction" when upvoting/showing interest in issue instead of writing +1. Everyone subscribed to an issue will get a notification when someone adds a +1 comment, but will not when using the "Pick your reaction" function.

**Comment by umeshabhat** [comment]
Alright, removed my +1.
