### ISSUE TITLE
Permission denied during installing a plugin

### ISSUE THREAD

**Issue by mfarag2409** [grafana/grafana#16782]
> grafana-cli plugins install grafana-worldmap-panel
> installing grafana-worldmap-panel @ 0.2.0
> from url: https://grafana.com/api/plugins/grafana-worldmap-panel/versions/0.2.0/download
> into: /var/lib/grafana/plugins
> 
> 
> Error: âœ— Could not create /var/lib/grafana/plugins/grafana-worldmap-panel. Permission denied. Make sure you have write access to plugindir
> 
> NAME:
>    Grafana cli plugins install - install <plugin id> <plugin version (optional)>
> 
> USAGE:
>    Grafana cli plugins install [arguments...]

**Environment**:
- Grafana version: 6.1.4
- Running on RPI3

**Comment by marefr** [comment]
You're probably trying to install plugin using a user which don't have write access to the plugins dir. Change your permissions or use sudo.
