### ISSUE TITLE
Can auth.anonymous work together with other auth provider?

### ISSUE THREAD

**Issue by cauwulixuan** [grafana/grafana#16798]
**What happened**:
`[auth.anonymous]` not working when I enabled `auth.anonymous` and `auth.generic_oauth`.

Here is my use case:

1. setup auth.anonymous for anonymous user, they can just view the dashboards in Main Org.
2. setup auth.generic_oauth for SSO reason, for these users, they have admin permission in their own org.

my issue is:
1. http://grafana.com:3000/login/generic_oauth/ just works fine (redirect to SSO server for authentication and login).
2. http://grafana.com:3000/ not work,  it redict to uri: http://grafana.com:3000/login, the login form showed up, so I cant just access dashboards as anonymous user withou login. And I find some error log in grafana.log:
```
lvl=eror msg="Anonymous access organization error: 'Main Org.': Organization not found"
```

So, is there possible that `auth.anonymous` work together with other auth provider? Or did I miss anything? Or is that a bug? Any suggestions ? Thanks.

**What you expected to happen**:
anonymous user can access grafana dashboards without login when I enabled both  `auth.anonymous` and `auth.generic_oauth`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Here is my `grafana.ini` :
```
[auth.anonymous]
enabled = true

[users]
auto_assign_org = false
default_theme = light

[paths]
logs = /var/log/grafana

[auth.generic_oauth]
enabled = true
name = keycloak
allow_sign_up = true
client_id = grafana
client_secret = uuidxxx
auth_url = http://my.domain.com/auth/realms/keycloak/protocol/openid-connect/auth
token_url = http://my.domain.com/auth/auth/realms/keycloak/protocol/openid-connect/token
api_url = http://my.domain.com/auth/auth/realms/keycloak/protocol/openid-connect/userinfo
```
**Environment**:
- Grafana version: v4.6.5
- Data source type & version: Prometheus v1.8
- OS Grafana is installed on: 
`CentOS Linux release 7.3.1611 (Core)`

**Comment by marefr** [comment]
You're using a quite old version of Grafana so would suggest trying out a newer version. We have anonymous and oauth setup at our [demo site](https://play.grafana.org/) and that works as expected. Maybe you have to use `auto_assign_org = true`?

**Comment by MrMegaMango** [comment]
my oauth google logged in account is treated as auth.anonymous Main Org Viewer
