### ISSUE TITLE
Grafana 2.0b1 MySQL  datasource error

### ISSUE THREAD

**Issue by painz0r** [grafana/grafana#1679]
I've tried to use new MySQL data source option today and it seems adding SQL DB isn't working ? 

I have a couple of DBs defined both local and remote. All return the same JS error in console when selected:
Chrome:
![mysql_error_chrome](https://cloud.githubusercontent.com/assets/1032845/6923121/88af1f62-d7d8-11e4-83dc-e38711f21c68.png)
Firefox:
![mysql_error_firefox](https://cloud.githubusercontent.com/assets/1032845/6923139/9516efe6-d7d8-11e4-98a0-455becefc2f8.png)

If the support for MySQL data source is not implemented yet, then please disregard this issue.

Thanks.

**Comment by torkelo** [comment]
this data source is not ready for use, sorry, that should be made more clear.

**Comment by painz0r** [comment]
No worries, thanks for the update.
