### ISSUE TITLE
align y-axes logically (e.g. 0° Celsius != 0° Fahrenheit

### ISSUE THREAD

**Issue by azrdev** [grafana/grafana#16795]
**What would you like to be added**:
Following  #10994 it is possible to "align y-axes", which AIUI sets their 0 value to the same. However, when using e.g. one axis on degree Celsius and the other on degree Fahrenheit, this doesn't make sense, because the units can be translated into each other, but are offset.

**Comment by torkelo** [comment]
you can set one to 0, and then specify manually the min value for the other (using min/max)
