### ISSUE TITLE
Unable to scroll in MS Edge

### ISSUE THREAD

**Issue by philippegirard** [grafana/grafana#16796]
**What happened**:
I am unable to scroll in a Grafana dashboard in MS Edge on Windows 10.

**What you expected to happen**:
I expected scrolling to work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard longer than your screen. Try to scroll.

**Anything else we need to know?**:
Works fine on Chrome.

On MS Edge the only way to scroll is to click on the grafana scroll bar and drag it. 

Is there any known work around?

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Postgres 10
- OS Grafana is installed on: Amazon T3.micro (ubuntu 16.04 I think)
- User OS & Browser: 
Windows 10 Home 10.0.17763
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
- Grafana plugins: Standard plugins

**Comment by Alethebat** [comment]
<grafana_install_dir>/data.
Mysql:
backup: 
>mysqldump-v root -p grafana-backup.sql 
restore: 
>mysql-v root -p grafana 
grafana-backup.sql

**Comment by marefr** [comment]
Tried Microsoft Edge 42.17134.1.0 on Windows 10 and browsing dashboards on both v6.1.3 and https://play.grafana.org (currently v6.1.6). I can scroll using the mouse wheel, even though it feels kind of sluggish, but it works.

@philippegirard any more information you can provide? Any errors logged in console by opening the developer tools?

**Comment by philippegirard** [comment]
Hi @marefr,

I forgot to specify that scrolling does not work on a trackpad (with two fingers). 

Scrolling with a trackpad on https://play.grafana.org/ does **not** work on my computer under Microsoft Edge 44.17763.1.0.

Scrolling with a mouse on https://play.grafana.org/ works on my computer under Microsoft Edge 44.17763.1.0.

My computer : 
Dell XPS 15 9750.

Here is a screenshot of the console in the developer tools : 
![image](https://user-images.githubusercontent.com/8143308/57202125-a6ae3b00-6f6f-11e9-9816-c505064e7385.png)

**Comment by marefr** [comment]
@philippegirard hard for me to try trackpad behavior since I'm running Windows in a virtual machine. Are you sure you have focus in dashboard container? Click between first and second panel and then scroll? Play are running v6.2-beta1 now so please try that out as well.

**Comment by Alethebat** [comment]
#####|@alethebat

**Comment by philippegirard** [comment]
Thank you for taking the time to dig a bit more into this issue.

Here my video experience using trackpad scrolling with a Dell XPS : https://girardlariviere.box.com/s/3jjrwwokrps7vzfwulwse7y7xofog4gt

**Comment by philippegirard** [comment]
Thank you for taking the time to dig a bit more into this issue :) 

scrolling works fine for me on : https://malte-wessel.com/react-custom-scrollbars/

Here is a video of me scrolling with a trackpad with a dell XPS on https://play.grafana.org/ and https://malte-wessel.com/react-custom-scrollbars/  : https://girardlariviere.box.com/s/i8pyara133q78bpvhpndpoahlvl9ndt7
