### ISSUE TITLE
Grafana 2.0b: Admin user gets recreated when renamed

### ISSUE THREAD

**Issue by manacker** [grafana/grafana#1680]
I renamed the default admin user to my username. And after restarting grafana a new admin user turned up, probably with the default password, which has security implications.

**Comment by torkelo** [comment]
hm.. yes, not sure what the best way to solve this is, probably check skip the admin user creation if there already exists one admin user in the database already?

**Comment by manacker** [comment]
I'd propose to don't create any user at all if there exists already one in the database, and maybe allow an override in the ini file to prevent a complete lockout.

**Comment by torkelo** [comment]
I did as you proposed, the admin user specified in the config file is only created if there no users in the database.
