### ISSUE TITLE
Support Elasticsearch for visualizing logs in Explore

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#16812]
Add Elasticsearch support for visualizing logs in Explore.

**Comment by dineshj17** [comment]
@marefr, Is there any estimated time for this feature complete?

**Comment by marefr** [comment]
@dineshj17 We hope to have something included in at least v6.3 stable.

**Comment by iamdinesh** [comment]
@marefr Is there any approximate date for 6.3 Stable? Because I don't see any date in grafana milestone.

**Comment by torkelo** [comment]
beta end of june , stable early july
