### ISSUE TITLE
Organization switching redesign

### ISSUE THREAD

**Issue by nmerdan** [grafana/grafana#16824]
**What would you like to be added**:
Remove popup and add back filtering for organization switching, like in older versions of Grafana.

**Why is this needed**:
When you have hundreds of organizations, the search becomes cumbersome (as you need to use in-browser search, which is not a good fit). Plus you need to move the mouse from the left side to the middle for the popup, as well as wait for the popup to load.

IMO, the old way of switching organizations was way faster and more intuitive, where a sidebar would pop out with a list of organizations and the filtering field.

**Comment by campi01** [comment]
Agreed, would love to see the old style organization switching back, which was a much better solution than the current one.

**Comment by marefr** [comment]
If you have screenshots available showing the difference old vs new that would be great to include.

**Comment by nmerdan** [comment]
Sure, so this is the old way, on the left side of the screen you get this with a filter:
![grafana-old](https://user-images.githubusercontent.com/2940768/57015139-7e42db80-6c13-11e9-862d-4d8e189acc2b.png)

The new way first requires you to click on the bottom left of the screen:
![grafana-new-1](https://user-images.githubusercontent.com/2940768/57015137-7daa4500-6c13-11e9-85d7-1cbf236ea72a.png)

Then in the middle of the screen you get a popup with the list, for which there is no filter.
![grafana-new-2](https://user-images.githubusercontent.com/2940768/57015138-7e42db80-6c13-11e9-9310-0ea7fbba8917.png)

The popup is extremely painful if the underlying page has mentions of the term you are trying to search for. For example you have a dashboard named 'foo' and you are on the dashboard page, and you open the popup and try to search 'foo' to find an organization named foo. It will first display results on the underlying page.
