### ISSUE TITLE
Ability to customize grafana internal metrics

### ISSUE THREAD

**Issue by dyanneo** [grafana/grafana#16828]
**What would you like to be added**:
Ability to customize internal metrics to get specific datasources and other objects - for example:
we can get this info: http_request_total{handler="/datasources/proxy/:id/*",method="get",statuscode="200"} 
Is it possible to get something like this: http_request_total{handler="/datasources/proxy/:id/123",method="get",statuscode="200"} http_request_total{handler="/datasources/proxy/:id/456",method="get",statuscode="200"} etc?

**Why is this needed**:
We are attempting to provide more granular metrics about the services my team provides - we have many orgs and datasources that we would like to report on independently. In the example above, it may be possible that datasource id 123 is returning statuscode 200, but datasource 456 is returning statuscode 401.

**Related community topic**:
https://community.grafana.com/t/customize-internal-metrics-eg-get-http-codes-for-each-datasource/16795

**Comment by bergquist** [comment]
This could be problematic from a cardinality perspective. If we add support for it, it should be disabled by default.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
