### ISSUE TITLE
2.0b1 - Snapshot delete function does not work

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1682]
I created a local snapshot with 1hr retention and was shown this dialog including a delete link:
![image](https://cloud.githubusercontent.com/assets/917241/6925946/6e6f4856-d7e3-11e4-914d-65dbee4a6227.png)

Access the snapshot works if I follow the link.  But if I click the delete link I get this response instead of a dialog box:
![image](https://cloud.githubusercontent.com/assets/917241/6925887/fab28946-d7e2-11e4-9fbf-783bb561bcdd.png)

And, if I still access the snapshot link it has not actually been deleted.  I tried the same with a snapshot to raintank with the same results, but maybe the CDN comment is why it's not actually purged yet.

Probably something that just isn't quite finished yet but I wanted to report it for tracking purposes.

**Comment by torkelo** [comment]
Yes, that should be a dialog. Will fix. 

Snapshots currently get a cache header of one hour, so they can still be in the browser cache, or for snapshot.raintank.io in the CDN cache. We will try to add some integration so we can have a hook and purge from the CDN cache in the future. And maybe also remove the cache-control header, but it will make the snapshots less fast to load which is kind of sad as they are basically static and could possible be cached for ever, but if a mistake is made it is nice to be able to delete them quickly. But if the URL is not shared no one will ever see it. 

We will add later (before 2.0 stable release) a view where all snapshots can be listed (local and external), when publishing snapshots to snapshot.raintank.io a reference to this snapshot is stored in the local instance along with a delete key. But this view has yet to be implemented.
