### ISSUE TITLE
Webhook notification channel error 400 (both text and markdown cannot be empty)

### ISSUE THREAD

**Issue by Fraeco** [grafana/grafana#16826]
**What happened**: Received error 400 from configured Webhook notification channel

**What you expected to happen**: A message to be send to an external service using the webhook notification channel

**How to reproduce it (as minimally and precisely as possible)**:
Create a new notification channel of type webhook
Enter the URL and http Method Post
Click the Send Test button

**Anything else we need to know?**:
```
t=2019-04-30T12:49:20+0000 lvl=dbug msg="Webhook failed" logger=notifications statuscode="400 Bad Request" body="{\"message\":\"Both text and markdown cannot be empty in the same request.\",\"errors\":[{\"description\":\"Both text and markdown cannot be empty in the same request.\"}],\"trackingId\":\"ROUTER_5CC8444F-88BA-01BB-0057-D52711BA0057\"}"
t=2019-04-30T12:49:20+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.webhook error="Webhook response status 400 Bad Request" webhook="Webex Teams"
t=2019-04-30T12:49:20+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=7JJsxQzZz error="Webhook response status 400 Bad Request"
```
I tried curling the POST directly from the server. This works just fine. It's when Grafana tries to send the message that it fails. 
The failure is not only on sending test messages, but also on normal alerts. 
I'm using the webhook from Cisco Spark 
https://apphub.webex.com/integrations/incoming-webhooks-cisco-systems

**Environment**:
- Grafana version: 6.1.6
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10 - Chrome 73
- Grafana plugins: praj-ams-datasource (1.2.0) & Blendstat (1.0.1)

**Comment by marefr** [comment]
[This is the payload](https://grafana.com/docs/alerting/notifications/#webhook) sent by Grafana, if your receiver don't support this you'll need to setup your own webhook handler which converts payload and forward to your specific webhook integration.

**Comment by marefr** [comment]
There's an open feature request for supporting custom json payload #6956
