### ISSUE TITLE
Docs: Clarify page parameter version support for folder/dashboard search

### ISSUE THREAD

**Issue by dgl** [grafana/grafana#16827]
https://grafana.com/docs/http_api/folder_dashboard_search/ mentions the "page" parameter, and at the top right says it applies to "Grafana v6.1 (current)".

It looks like the "page" parameter was implemented in pull #16458, which according to the milestone that is tagged with will be available with 6.2. Please consider making it clear when a feature isn't yet available, I just spent a little while wondering why our Grafana instance (running 6.1) wasn't understanding `page=`

**Comment by marefr** [comment]
Thanks. Will fix
