### ISSUE TITLE
2.0b1, Organization account users table lists only Email address which is not a required field

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1683]
Creating a new user does not require an email address (2nd row in table):
![image](https://cloud.githubusercontent.com/assets/917241/6926637/f5e89478-d7e7-11e4-9616-2fa5767cf06b.png)

But that gets confusing if you later give that user access within an organization because the table only includes Email address resulting in a blank line:
![image](https://cloud.githubusercontent.com/assets/917241/6926677/330c1cc6-d7e8-11e4-829c-e5ee594cae38.png)

Update:  I tried to create another user without an email and got this error:
![image](https://cloud.githubusercontent.com/assets/917241/6926923/1b1bc9a2-d7ea-11e4-8308-b1be793729b1.png)

So it seems the solution is to make email address a required field in the new user create dialog.

**Comment by torkelo** [comment]
thanks for reporting this, will fix!

**Comment by torkelo** [comment]
Added Login to the list, I am not sure I want to make email required as I want to support LDAP authentication and I cannot guarantee an email exists for that (well, usually should).

![image](https://cloud.githubusercontent.com/assets/10999/6991969/4a8ed316-dab3-11e4-8a2c-f3f460d470e4.png)
