### ISSUE TITLE
Docker: grafana user cannot write to default provisioning directory

### ISSUE THREAD

**Issue by wmedlar** [grafana/grafana#16830]
**What happened**: Permission denied while attempting to write out a datasource provisioning file to `/etc/grafana/provisioning/datasources` (`$GF_PATHS_PROVISIONING/datasources`) in the provided docker container.

**What you expected to happen**: File to be written out to desired path.

**How to reproduce it**: Attempt to create a file in the container's `$GF_PATHS_PROVISIONING` directory, e.g.,:

```shell
$ docker run --rm --entrypoint touch grafana/grafana:6.1.6 /etc/grafana/provisioning/file
touch: cannot touch '/etc/grafana/provisioning/file': Permission denied
```

**Anything else we need to know?**: Most Grafana directories are [chown'd to the grafana user](https://github.com/grafana/grafana/blob/fe20dde5db4debbe0399eece5c88c628bb214550/packaging/docker/Dockerfile#L49-L50) prior to dropping permissions from the root user. `$GF_PATHS_PROVISIONING` likely needs to be in this list.

**Environment**:
- Grafana version: 6.1.6 (docker)
- Data source type & version: prometheus
- OS Grafana is installed on: debian?
- User OS & Browser: macOS, Chrome
- Grafana plugins: none
- Others: Docker version 18.09.2, build 6247962

**Comment by xlson** [comment]
This is not a bug per se. Grafana does not need to write to the provisioning folder, so it's not able to. Most users that want to use provisioning with the docker image will use volume mapping or k8s config maps to get the files into the container and sidestep any issue with being able to write to the folder.

What is your workflow? Why do you need to write to the folder from within the container?

**Comment by wmedlar** [comment]
I template datasources so the same files are applicable both locally and in deployed environments. Those templates are packaged into a container and rendered as part of its entrypoint, allowing me to follow the stateless deployment model of Grafana with only a single deployable artifact.

**Comment by xlson** [comment]
Does this mean that you build a new docker image based on ours? If that is the case, you should be able to change the permissions of the provisioning folder while building the image.

That said, perhaps we should just change the permissions of all the folders used by Grafana to avoid these kinds of issues. Will have to think about it.

**Comment by wmedlar** [comment]
Yes, I use the official Grafana image as a base and modify the permissions of the provisioning directory.

```Dockerfile
FROM grafana/grafana
USER root
RUN chown -R grafana:grafana "$GF_PATHS_PROVISIONING" && chmod 777 "$GF_PATHS_PROVISIONING"
USER grafana
[...]
```

This is just a workaround though, I would expect that directory to be writable by default.

**Comment by bergquist** [comment]
While your setup sounds interesting I'm not sure that's something our Docker container should support since it's side Grafanas zone. Supporting this kind of setups with the default container is endless feature creep and very hard for us to change. 

Your current solution is IMO much better since we solve how grafana should be operated and you solve the problems for your infra.
