### ISSUE TITLE
Query variables race condition

### ISSUE THREAD

**Issue by Karnich** [grafana/grafana#16839]
**What happened**:
tried to get this behavior:
```
set @sum := 0;
SELECT aggre.userDate as time_sec, (@sum := @sum + aggre.dateValue) as value
...
```
But without luck. I then found out that i could save `set @sum := 0;` in template query variable named `set_sum` and then do the following to get the expected result:
```
$set_sum
SELECT aggre.userDate as time_sec, (@sum := @sum + aggre.dateValue) as value
...
```

This works fine the first time viewing the board. But if i use a refresh interval on the dashboard and set the variable to "On Time Range Change"
Then everything works, sometimes. I experience race conditions between setting the variable to 0 and running the select statement. Which means my graph sometimes increments to twice or even 3 times the size depending on who wins the race condition.

**What you expected to happen**:
I expect the query variable to be set before any of my select statements run after a refresh 

**How to reproduce it (as minimally and precisely as possible)**:
a MySQL select statement that counts occurences by date like this:
```
$set_sum
SELECT aggre.userDate as time_sec, (@sum := @sum + aggre.dateValue) as value
FROM (
    SELECT COUNT(*) as dateValue, Date(User.createdAt) as userDate
    FROM User 
	GROUP BY date(User.createdAt)
    ) as aggre;
```
where `$set_sum`is a variable of type Query, Data source is MySQL, Refresh is On Time Range Change and the Query is: set `@sum := 0;`

**Anything else we need to know?**:
Datasource: MySQL
Grafana 6.1.4

**Comment by torkelo** [comment]
Can you show network traffic where the execution order is wrong?

**Comment by Karnich** [comment]
@torkelo good call i didnt think of that. But as i guess you expected my query variables are actually run before the query itself. So what im seeing is some kind of server lag?

**Comment by torkelo** [comment]
not sure, Keeping state in a SQL variable like this have I think never been used before and seems very sketchy. Is a variable defined like this
```
set @sum := 0;
```

global to all SQL sessions or just one session? Grafana will not share session between different backend query executions so not sure how this keeping state, or if it is how other users of this dashboard wont mess with that. 

Anyway if you see that the order of requests are in the wrong order as there might be some kind of bug and I will re-open this.
