### ISSUE TITLE
Plugin icons need some style help

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16833]
In master, the icons on plugins seem off:

http://localhost:3333/plugins

<img  alt="plugin-icons" src="https://user-images.githubusercontent.com/705951/56996921-f13c4b80-6b5a-11e9-828c-7c42d85dd9c6.png">

**Comment by torkelo** [comment]
Ha! I noticed that yesterday as well , love that I am not the only one :)

**Comment by fgkramer** [comment]
@torkelo, I can take this if you don't mind

**Comment by torkelo** [comment]
@fgkramer i do not think @Ijin08 has started yet, if you want to fix this that would be much welcomed!

**Comment by fgkramer** [comment]
@torkelo thank you, I'll get to it

**Comment by Ijin08** [comment]
@fgkramer a solution here could be to simply remove the icons since they don't really add so much and some of the icons are legacy icons.

**Comment by fgkramer** [comment]
@Ijin08 ok, I initially added an extra rule on css targeting the `.gicon` class under `.card-item-type` (to change it's opacity and add some margin as the svg icon doesn't have any extra space as the legacy icons) but I'm not familiar on how to target the right theme. I'll remove the icons if you think it's the right approach.

**Comment by Ijin08** [comment]
what do you think @torkelo ?

**Comment by torkelo** [comment]
I don’t think the icon adds much , feels cleaner without it
