### ISSUE TITLE
Breadcrumb not handling variables on top level correctly

### ISSUE THREAD

**Issue by emerson-github** [grafana/grafana#16842]
**What happened**: Top breadcrumb level only gets variables on the url querystring parameters after level 1, ex:  

Top > Level 1 > Level2

mouse over : 
Top on main dashboard -> http://localhost:3000/d/qhEn6r9iz/menu?orgId=1
Top on Level1                  -> http://localhost:3000/d/qhEn6r9iz/menu?orgId=1
Top on Level2                 -> http://localhost:3000/d/qhEn6r9iz/menu?orgId=1?var-x=1
Navigate back to level1 
Top on Level1                  -> http://localhost:3000/d/qhEn6r9iz/menu?orgId=1?var-x=1

**What you expected to happen**:
Scoped variables should exist in the Top level breadcrumb since Level1 above

**How to reproduce it (as minimally and precisely as possible)**:
Create 3 pages with some variable, use drill down to go from top level page to bottom level page. Check Top level parameters behavior.

**Anything else we need to know?**: 

**Environment**: Linux 16.04 
- Grafana version:Grafana 6.1.3  
- Data source type & version: simpo-json
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome/Firefox/Safari
- Grafana plugins: Text, SingleStat, AnnotationsTable
- Others:

**Comment by torkelo** [comment]
Sorry, don't understand your issue description. 

* What do you mean by "Top on"
* How are you defining your variables? What options are used? (refresh option etc)
* What data source are you using what does your variable queries look like? 
* Can you inspect network traffic and review queries sent as you change template variable? Please include relevant requests & responses.

> Scoped variables should exist in the Top level breadcrumb since Level1 above

What do you mean by this??

**Comment by emerson-github** [comment]
Hi, 

Forget about "top" and levels. Say that you have 3 dashboards with several panels  on each dashboard.

Dashboard1 
Dashboard2 
Dashboard3 

Now all dashboards have a scoped variable named $accountGroup, labeled as "Account",  defined with a value from the datasource and selected on Dashboard1:

Account: #1231231

The breadcrumb on Dashboard1 page is:

Dashboard1

Next you go on and click some panel on Dashboard1 with a drilldown that carries the accountGroup variable to the next dashboard (Dashboard2).

The Breadcrumb on Dashboard2 is something like:

Dashboard1 > Dashboard2

Mouse over "Dashboard1" shows no "var-accountGroup" variable, just the link to the Dashboard1.

Next you go on and click in some drilldown link on some panel on Dashboard2 that takes you to Dashboard3

Your breadcrum on Dashboard3 is now:

Dashboard1 > Dashboard2 > Dashboard3

Mouse over Dashboard1 now shows the accountGroup variable correclty
Mouse over Dashboard2 shows the same accountGroup variable correctly too
Mouse over Dashboard3 shows the same accountGroup variable correctly too

I was expecting the scoped var to exists in the Dashboard2's breadcrumb in all links (Dashboard1 > Dashboard2).  If it working as designed, then why the link appears on the first link (Dashboard1) after you go to sub-dashboard ? To be consistent, it should be there right after you drilldown from Dashboard1 to Dashboard2 or never be present at all for the first Dashboard no matter how many pages you go "down" (dashboard3, dashboard4 etc). I prefer the former.


Regards, Emerson

**Comment by torkelo** [comment]
Breadcrumbs? Grafana dashboards has no breadcrumbs. Are you using the panel plugin called breadcrumbs?

**Comment by emerson-github** [comment]
Yes, I'm using the plugin breadcrumbs available at Grafana.com website:
https://grafana.com/plugins/digiapulssi-breadcrumb-panel. If extends
Grafana and it is distributed by Grafana official web site it is part of
Grafana.

**Comment by torkelo** [comment]
Ok, please reach out to the plugin developer: https://github.com/digiapulssi/grafana-breadcrumb-panel
