### ISSUE TITLE
 Prometheus: Incorrect variable results when label value contains pipe

### ISSUE THREAD

**Issue by Limess** [grafana/grafana#16840]
## What happened:

Variables are not escaped correctly in Prometheus queries when they contain `|`.

## What you expected to happen:

Expects grafana to escape `|` as `//|`.

## How to reproduce it (as minimally and precisely as possible):

Add a timeseries, say `up` with a label, say `instance` with value `some-prefix|some-text`, use this as a Grafana variable, again let's say `instance`.

Use this in a query:

`up{instance=~"$instance"}`

The query sent to Prometheus is:

```
api/datasources/proxy/60/api/v1/query_range?query=up%7Binstance%3D~%22some-prefix%7Csome-text%22%7D&start=1556704005&end=1556725605&step=15"
```

i.e.

```
up{instance=~"some-prefix|some-text"}
```

It should be sent as 

```
up{instance=~"some-prefix\\|some-text"}
```

## Environment:

    Grafana version: v5.4.2 (d812109)
    Data source type & version: prometheus 2.9.2
    OS Grafana is installed on: Amazon Linux
    User OS & Browser:OSX Mojave 10.14.4 (18E226)
    Grafana plugins:None
    Others:

**Comment by marefr** [comment]
@Limess if you switch to using POST instead of GET does it work as expected? You can change this when configuring the datasource in Grafana.

**Comment by Limess** [comment]
Nope. The pipe (`|`) character is still unescaped in the query.

```json5
data: {
    query:"up{instance=~"some-prefix|some-text"}",
    ...
}
```

**Comment by Limess** [comment]
From what I can tell this is just a missing escape here? https://github.com/grafana/grafana/blob/b07d0b1026753dea12acbf2272e6bfb14a41d8e6/public/app/plugins/datasource/prometheus/datasource.ts#L559

I may look into fixing this and adding tests to ensure that variable queries are still split correctly by `|` if I have the time (probably not this week then...).
