### ISSUE TITLE
Add cubic meter per hour as a unit in flow category

### ISSUE THREAD

**Issue by rajibgupta** [grafana/grafana#16843]
**Flow rate unit - cubic meter per hour**:

**It's an industry standard unit for measuring flow**:

**Comment by marefr** [comment]
Needs to be added in the similar manner as Cubic meters/sec here:
https://github.com/grafana/grafana/blob/7194c6d9bfff74f93ab74eee7a7ea9ce2f71a4f8/packages/grafana-ui/src/utils/valueFormats/categories.ts#L187-L197

**Comment by hugohaggmark** [comment]
You can use custom units instead: `suffix: m³/h` to solve this, so unfortunately I'm going to close this issue. Thank you for reporting this.

See https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#custom-units

**Comment by woutkonings** [comment]
while custom units is a nice options, I would suggest to still as m3/h as a default unit. I would think custom units are for uncommen units, but m3/h is quite common.
