### ISSUE TITLE
Annotations displayed in all dynamic rows without respecting the query

### ISSUE THREAD

**Issue by JNuno007** [grafana/grafana#16847]
**What happened**:
Annotation using a query with a dynamic variable (representing issues) is displaying all issues in every dynamic row displayed

**What you expected to happen**:
Expecting to see the annotations that represents the variable for the specific row.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a simple annotation in the dashboard settings
2. Wrote this query
`SELECT * FROM "test_performance" WHERE ("testName" =~ /^$testName$/) and $timeFilter`

3. Checked the output in the dashboard and this was the result
![imagem](https://user-images.githubusercontent.com/20671298/57072178-b5c58c80-6cd4-11e9-9ac1-25e250c40f6f.png)

4. I'm getting annotations from another row

**More informations**
I can see that annotation is respecting the value of the selected value, when I select the "All" option, it should show the respective annotations in the right row.

**Environment**:
- Grafana version: **6.0.1**
- Data source type & version: **InfluxDB** 
- OS Grafana is installed on: **Ubuntu 16.04**
- User OS & Browser: **Ubuntu Mate 16.04 LTS** / **Firefox 66.0.3**
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
annotations are queried on the dashboard level and results shared for each panel so you cannot use a scoped (repeated) variable and expect Grafana to issue an annotation query for each repeated panel/row

**Comment by JNuno007** [comment]
Thanks for the reply, I now understand that. Is there any plans to develop a feature for this? I think is important. I'm sorry for any written mistake or any kind of misunderstanding.

**Comment by torkelo** [comment]
No there is no plan for this
