### ISSUE TITLE
2.0b1 - Dashboard list does not appear to be alphabetically sorted

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1685]
In 1.9.1 the dashboard list was sorted alphabetically.  In 2.0b1 it appears to be sorted in the order of dashboard creation which is not nearly as useful/intuitive.  Request is to sort this list matching the 1.9.1 behavior.

**Comment by torkelo** [comment]
yes, been irritated by this as well. Will fix asap.

**Comment by torkelo** [comment]
fixed! daily builds can be found here if you want to update before beta2 or rc1 (not sure what the next release will be), http://grafana.org/download/builds

**Comment by maddenca** [comment]
Awesome, just updated and indeed fixed!  Thanks!
