### ISSUE TITLE
Fix systemd script in RPM package when used with MySQL

### ISSUE THREAD

**Issue by davtex** [grafana/grafana#16850]
Hello,

As per [Pull 3105](https://github.com/grafana/grafana/pull/3105), following line has been added to grafana-server.service in both DEB and RPM packages:
> After=postgresql.service mariadb.service mysql.service

According to [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/using-systemd.html):

> Support for systemd includes these files:
> 
> mysqld.service (RPM platforms), mysql.service (Debian platforms): systemd service unit configuration file, with details about the MySQL service.

This means that the correct line for RPM package should look like this (at least when it comes to Mysql):
> After=postgresql.service mariadb.service mysqld.service

Without this little change in place, grafana-server is started prior to mysqld, which leads to grafana failing to start.

**Comment by torkelo** [comment]
thanks for reporting this! Can you submit a PR to fix it? Otherwise we will fix it :)
