### ISSUE TITLE
Add MQTT as an notification channel

### ISSUE THREAD

**Issue by psyciknz** [grafana/grafana#16858]
What would you like to be added:
Sending notifications to an MQTT broker something like grafana/<item>/<state>

Why is this needed:
Would be a great feedback loop for home automation systems, or mqtt based alerting (eg mqttwarn)

**Comment by plutec** [comment]
+1

**Comment by rollyaponte** [comment]
+1

**Comment by E5tian** [comment]
+1

**Comment by spieter** [comment]
+1

**Comment by brauhausdc** [comment]
+1 This would allow Grafana Alerts to signal a physical system to take action to correct an alert. A specific example - Flow rate data from a pump gets pulled into Prometheus and displayed with Grafana, if it drops below a certain value, Grafana could fire an alert to shut down the pump to prevent damage if there is a catastrophic leak in the system.

**Comment by philmale** [comment]
+1 and allow really easy integration with a whole stack of other platforms and services

**Comment by homeseer666** [comment]
+1

**Comment by woifes** [comment]
+1

**Comment by Papyruse** [comment]
+1

**Comment by tablatronix** [comment]
Wow just adding contact points and there is no mqtt!

**Comment by BuxtonCalvin** [comment]
+1

**Comment by detece** [comment]
+1

**Comment by whc2001** [comment]
+1
I see Apache Kafka is listed as one of the supported notification endpoints but it's quite heavy and personally I don't have a lot of experience on that compared to MQTT. Being able to connect to the already deployed and operational local MQTT broker instance is a huge advantage.

**Comment by tablatronix** [comment]
Yeah I am using nodered http endpoints to relay to mqtt

**Comment by KaplanSarah** [comment]
We will review PRs from the community for this.   We will add it to our backlog but there is no ETA for implementation.

**Comment by alexander-akhmetov** [comment]
Released in 11.3: https://grafana.com/docs/grafana/latest/alerting/configure-notifications/manage-contact-points/integrations/configure-mqtt/
