### ISSUE TITLE
Transform null to zero not working with azure monitor datasource for Graph visualization

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#16852]
**What happened**:
Transform null to zero not working with azure monitor datasource for Graph visualization.

My assumption is that the query missing null records. If no data found for a time bucket, no record returned.

**What you expected to happen**:
If set null to zero, it should replace 0 in graph.

**How to reproduce it (as minimally and precisely as possible)**:

Sample query

```
Syslog
| where $__timeFilter(TimeGenerated)
| where SeverityLevel in ("emerg","crit","alert","err")
| summarize count() by Computer, bin(TimeGenerated, 1m )
| order by TimeGenerated asc
```

- Grafana version: 5.4.4
- Data source type & version: Azure Monitor 0.3.0
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
Can you use Query inspector to check what Azure returns? Does it return nulls for time buckets without data?

**Comment by yesoreyeram** [comment]
Azure doesn't return any row for those time buckets if there is no data.it doesn't return null.

**Comment by torkelo** [comment]
@yesoreyeram ok, then it's probably a feature request for the Azure team to have the bin(TimeGenerated, 1m) function return null for time buckets with no values
