### ISSUE TITLE
Datasource update API not working

### ISSUE THREAD

**Issue by rmdat2003** [grafana/grafana#16865]
**What happened**:
Grafana update datasources API is not updating certain data, such as username and password for elasticsearch datasource.

**What you expected to happen**:
Should be able to update all datasource details via the HTTP api.

**How to reproduce it (as minimally and precisely as possible)**:
I use the datasource API to update an existing elastic datasource for an organization - changing the username and password. If I go to the Datasources panel for the organization within Grafana and view the datasource, the updated username and password are not shown. If I instead use the HTTP /datasources/api to see the datasources for the organization, I see the correctly defined username and password.  If I use the datasource as a query in a panel, I can confirm the username and password is not being used.

There seems to be discrepancy with what is updated, and what Grafana believes is the current datasource state. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6
- Elasticsearch:
- Ubuntu 18:
- Mac OSX, Chrome:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you try reloading your browser page? 

> Datasources panel

What is this? Do you mean a graph panel? 

> I use the datasource API to update an existing elastic datasource for an organization - changing the username and password

If you use the API you only change the backend value. If you use data source server access (proxy) then that should be enough as only the backend will access the username/password. 

But it sounds like your not user "server" access (access: proxy in config props),but access direct (browser). In this case you need to reload your browser page for this setting to take affect
