### ISSUE TITLE
multiple domain configuration

### ISSUE THREAD

**Issue by priyankamondalairtel** [grafana/grafana#16866]
HI,

I have requirement to integrate grafana with our two domain, my ldap.toml configuration is looking like:

**[[servers]]
  host = "10.5.200.20"
  port = 389
  bind_dn = "CN=tickuser,OU=ABC,DC=india,DC=XYZ,DC=itm"
  bind_password = "Password"
  [servers.attributes]
  # stuff
  [[servers.group_mappings]]
  # mappings
[[servers]]
  host = ["10.5.100.101" "10.5.100.102"]
  port = 389
  bind_dn = "CN=tickuser,OU=ABC,DC=india,DC=XYZ,DC=itm"
  bind_password = "Password"
  [servers.attributes]
  # stuff
  [[servers.group_mappings]]
  # mappings**

though if I remove one domain configuration, another one is working, two domain at the same time is not working. can you please check and let me know what I am missing.
grafana version:grafana-5.0.4
server where grafana hosted: Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Comment by torkelo** [comment]
So when you have two servers configured does any of them work? any errors? what does the logs say?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
