### ISSUE TITLE
global dashboard filter

### ISSUE THREAD

**Issue by williamjoy** [grafana/grafana#1687]
Hello grafana,

Is it possible to add a global filter field on dashboard page to filter metrics applying to each graph.

For example you have 100 servers and each server have 20 metrics.
In each graph only contains one kind of metric, if there is feature to filter by server name if would be very helpful to troubleshooting a designated server and check metrics ,

Thanks!

**Comment by torkelo** [comment]
the templating feature should work perfectly for this? 
Graphite example: http://play.grafana.org/dashboard/db/templated-graphs-nested
InfluxDB example: http://play.grafana.org/dashboard/db/influxdb-templated-queries

**Comment by williamjoy** [comment]
Thanks @torkelo , this is what I want :)
