### ISSUE TITLE
resolve message [OK] without query

### ISSUE THREAD

**Issue by FMMTG** [grafana/grafana#16878]
**What happened**: 

I have monitored some devices, with different query (A, B, C...) in a unic Graph, and I have set alerts of theses queries, so when I receive email of those alerts, in the first email of alerting I can see the devices that are down (just below of Metric Name) , but in the email of resolved or OK, I cannot see what device is recovered or is up again, I only receive the name of the group of devices. 

![image](https://user-images.githubusercontent.com/50230912/57155724-797d5380-6ddc-11e9-9522-68a742cbeda5.png)

![image](https://user-images.githubusercontent.com/50230912/57155770-9a45a900-6ddc-11e9-9077-d2338da110b2.png)

**What you expected to happen**:

The name of the queries recovered, in a resolved email or message of OK, after being down in a Graph with many devices or many queries

![image](https://user-images.githubusercontent.com/50230912/57157216-5d7bb100-6de0-11e9-9aac-a65060e66a70.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Prometheus 2.8.1
- OS Grafana is installed on: Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This is related to this feature request https://github.com/grafana/grafana/issues/6041 

We cannot currently provide this info in the OK message, see above issue
