### ISSUE TITLE
Heatmap: Add Default Bucket/Box Limit that rejects rendering the heatmap

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#16875]
**What would you like to be added**:
A default limit on the number of squares that will be rendered in a heatmap. For example, if your input/settings would result in a large number of buckets, instead of attempting to render the heatmap, you get a "too many buckets" error or something like this.

**Why is this needed**:
When creating heatmaps, if you enter to small values for time and or bucket size then the browser/DOM overloads and the browser locks up (this is pretty easy to do since this is X*Y, and for example a small bucket size with a large range of values can quickly generate too many items).

This would protect against that unless you intentionally raise the limit to push what a browser can render.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
