### ISSUE TITLE
Detail error does not show up in Grafana 6.x

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#16879]
**What happened**:
Since upgraded to Grafana v6.1.6, when query give out the error, clicking the red triangle on error doesn't show the error pop up anymore. Hovering just says "Request Error", detail error can only be seen by open the "Query Inspector".

**What you expected to happen**:
Similar behavior like Grafana v5.x, when hover over the red triangle at the top left of the panel it will show the reason of the error rather than just "Request Error".

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: We are upgrading from v5.3.4 top v6.1.6

**Environment**:
- Grafana version: v6.1.6
- Data source type & version: Metrictank
- OS Grafana is installed on: RHEL 7.x
- User OS & Browser: Chrome/MacOS
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
This modal was removed in v6 as most of that functionality is already covered better by the Query Inspector. 

There are still some use cases for random & transient errors where the old error modal has some uses so we will likely add something like it back in the future

**Comment by shanson7** [comment]
Yes, the problem is that opening the query inspector fires the query again *and* is only accessible from the panel edit screen. 

Additionally, I think it's natural to expect error indicators to have information about errors.
