### ISSUE TITLE
add yarn gui:build to the CI process

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16889]
Right now if you try to make the @grafana/ui build, it gets:

```
yarn run v1.15.2
$ ts-node --project ./scripts/cli/tsconfig.json ./scripts/cli/index.ts gui:build
Running @grafana/ui build task
  Building @grafana/ui (package.json version: 6.0.1-alpha.0)
✔ Cleaning
✖ Error: Command failed: tsc -p ./tsconfig.build.json

src/components/Portal/Portal.tsx:29:3 - error TS2742: The inferred type of 'render' cannot be named without a reference to 'react-dom/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.

29   render() {
     ~~~~~~


Found 1 error.


error Command failed with exit code 1.
```

We should add that to  the CI process.  Likely we should also add something to check that we don't includes stuff from grafana core.  like [dateMath](https://github.com/grafana/grafana/pull/16505#discussion_r280987874) etc

**Comment by ryantxu** [comment]
While looking at the build setup, we should also have it avoid referencing `@grafana/ui` from within grafana-ui packages

**Comment by torkelo** [comment]
@dprokop can you investigate why @grafana/ui build is failing?

**Comment by dprokop** [comment]
@torkelo already started, but no success yet. I mean there is a quick way by just wrapping React.createPortel into fragment: `<>{React.createPortal...}</>` but it seems like there is sth wrong with the types resolution.

That's one part of the problem. The other part is that rollup has problem resolving types in the later stage so I need to spend some more time in the morning on that.

**Comment by dprokop** [comment]
Build fix: https://github.com/grafana/grafana/pull/16913
Introducing grafana/ui build step to ci pipeline coming next

**Comment by ryantxu** [comment]
this is old
