### ISSUE TITLE
Row editor

### ISSUE THREAD

**Issue by logicall** [grafana/grafana#1688]
Hello!
"Row editor" does not work. I can not change the name and other parameters.
![default](https://cloud.githubusercontent.com/assets/222279/6936539/030d41a2-d85c-11e4-8171-a081e73fdb8d.JPG)
This can be seen in the version 2.0-Beta1

**Comment by torkelo** [comment]
Strange, is this using an download offical package? It works on all instances of Grafana 2 I run, like here http://play.grafana.org/dashboard/db/templated-graphs-nested  

Can you open chrome dev tools (F12) and look for javascript error or network request issues?

**Comment by calle** [comment]
Also seeing the same behavior on my local installation (grafana-2.0.0_beta1-1.x86_64.rpm) but not on the dashboard you liked above.

It seems like "dashboard.editable" is false since the "+ Add Row" button is also missing from my dashboards. Displaying the "+ Add Row" button (by removing ng-hide from container) allows me to click it and everything works as it should.

**Comment by torkelo** [comment]
@calle if you can replicate this, can you check for any js errors in the chrome dev console?

**Comment by calle** [comment]
@torkelo Nope, only thing I see is a warning:
> The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.

If I create a new dashboard I get a valid "Row editor" if I click "Row editor" in the dropdown list for the row. But if I click dashboard settings, then "Rows" and while that pane is visible click the "Row editor" in the dropdown list I get an empty editor.

That scenario is actually reproducible in your example dashboard above.

**Comment by logicall** [comment]
@torkelo 
Sorry.
Who tried again and it worked.
![default](https://cloud.githubusercontent.com/assets/222279/6959687/2ba8af3e-d924-11e4-90fe-861dbe0e40f4.JPG)
Maybe in the cache was something ....

Package I downloaded from the official website. grafana-2.0.0_beta1-1.x86_64.rpm

I think you can close the gaps.

**Comment by torkelo** [comment]
ah, I could replicate it when I tried to open row editor from dashboard settings time picker tab, then I was quickly able to locate the issue and fix it :)
