### ISSUE TITLE
BarGauge: Add manual width options for series name & value

### ISSUE THREAD

**Issue by paregupt** [grafana/grafana#16883]
Thank you for making bar gauge panel a reality. I have been looking for something like that for months. Torkel's blog on this new capability made me try it out. I know this is still in beta but here is some feedback. It would be great to have this in official 6.2 release

Today, the text size, the height of bar gauge and width of bar gauge are set automatically. See image for reference:
![grafana-bar-gauge-feedback](https://user-images.githubusercontent.com/8773072/57180702-25a45600-6e40-11e9-8f68-183ab03c5480.png)
(This is coming from monitoring stats on a network switch. I love it)

**What would you like to be added**:
1. Notice how the text is trimmed like (1/01...)
2. Also, the values are forced contracted. Look at the 3rd column, 1/08.
3. Adjusting the width of the bar gauge will help in a the above point. 
4. The text size of values is very small while the height of the bar gauge is a bit more. This would look better if height of the gauge can be reduced by a few points while the height of the text can be increased by  a few.

I guess, I am looking for capability to adjust the height and width of items. I have seen something like this in other panels.

**Why is this needed**:
The biggest value of a horizontal bar gauge is the capability to display tens or hundreds of items in a tabular format. This won't look well with the existing circular gauge (in singlestat panel). Due to this reason, it is important to adjust the size of the items so that they can fit nicely in a scaled environment.

PS: Apologies if this is not the right forum for this kind of feedback. I am just a user (not contributor). Torkel's blog pointed here for providing feedback.

Thanks
Paresh

**Comment by paregupt** [comment]
I photoshopped what I am looking for to convey the point. See the image below.
![grafana-bar-gauge-feedback-1](https://user-images.githubusercontent.com/8773072/57181399-f1349800-6e47-11e9-8a50-2e4a251e40ea.png)

It may look like a trivial ask for as I write before, with hundreds of rows, having clarity on text is very important.

Thanks

**Comment by torkelo** [comment]
The max width of the series name & value is a fixed percentage of the panel width, so you have to make the panel a bit wider. 

We do not currently have any plans introduce more manual options here but maybe if there is enough demand for this use case we will add manual width options for series name & value.

**Comment by paregupt** [comment]
Torkelo, Thank you for the response.

**Comment by paregupt** [comment]
Hi Torkelo

Here is another observation after few days of usage:

I am monitoring ports on a network switch. I set the height and width of the panel to accommodate the number of ports. Here is the output which looks nice
![grafana-bar-gauge-feedback-2](https://user-images.githubusercontent.com/8773072/57390969-56eb9180-7172-11e9-8e99-d72451019362.png)

Later, I added another network switch using variables. This network switch has more number of ports. That means more number of entries in the same panel. The end result is more number of ports are squeezed within the same height and width. Everything gets smaller and hard to read. See below:

![grafana-bar-gauge-feedback-3](https://user-images.githubusercontent.com/8773072/57391078-91edc500-7172-11e9-88c6-669605cf3111.png)

As I wrote above, the biggest value proposition of this new enhancement is to show multiple items together because the circular guage in singlestat panel is not intuitive to repeat so many times. Capability to show them nicely is critical.

**Comment by torkelo** [comment]
But how when your panel is so small?

**Comment by paregupt** [comment]
The panel is long. In the pictures, there are two panels next to each other. I just copy-pasted a portion of the panels. All entries in the panel are equally squeezed. Is that what you asked? I can record a gif and share if that helps.

**Comment by torkelo** [comment]
But they get squeezed in height so just make the panels higher so all the items fit better? What would you like Grafana to do? Auto expand height of the panel?

**Comment by paregupt** [comment]
Adjusting the height works for a single entity (a network switch in this example). It may look nice with 20 data points (or network ports). But another entity (or another network switch) may have 40 data points(or network port). Essentially, there would be no one size that could fit all.

I am not best placed to throw solutions out there. I am just a user, with little insights into the internal design. Just sharing this as an observation for now, in case something creative can be done for it without much of a heavy lifting. Appreciate your responses....

**Comment by cula09** [comment]
How About this, 
Pict 1 : if i was use filters and the result get data only 1, the label not showing 
Pict 2 : if i was use filters and the result get data more than 1 , the label is showing
Pict 3 : without filters
the detail can see at the picture below

![image](https://user-images.githubusercontent.com/44761926/60087605-862c8100-9767-11e9-9c27-8488eb454af7.png)
![image](https://user-images.githubusercontent.com/44761926/60087611-89277180-9767-11e9-94be-6e43dfd0e2bf.png)
![image](https://user-images.githubusercontent.com/44761926/60087614-8af13500-9767-11e9-906a-feca765e7778.png)

Thanks

**Comment by fishpenguin** [comment]
> How About this, i have a similiar issue.
> Pict 1 : if i use filters and the result data only 1, the label not showing
> Pict 2 : if i use filters and the result data more than 1 , the label is showing
> Pict 3 : without filters
> the detail can see at the picture below
> 
> ![image](https://user-images.githubusercontent.com/44761926/60087605-862c8100-9767-11e9-9c27-8488eb454af7.png)
> ![image](https://user-images.githubusercontent.com/44761926/60087611-89277180-9767-11e9-94be-6e43dfd0e2bf.png)
> ![image](https://user-images.githubusercontent.com/44761926/60087614-8af13500-9767-11e9-906a-feca765e7778.png)
> 
> Thanks

How can I change the title of every bar such as Atack Blocked or Inconclusive in your last picture.

**Comment by cula09** [comment]
Hi,

you can change the title at general setting then you can see the title option like the pict below. 

![image](https://user-images.githubusercontent.com/44761926/62854782-8afac380-bd1a-11e9-8535-5397ca27e627.png)

**Comment by torkelo** [comment]
This should be fixed in 6.6 (not measured textwidth)

**Comment by nikicat** [comment]
Sorry, but how is it fixed? I can't find this setting.
