### ISSUE TITLE
New Form Styles

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#16887]
The current form styles use vertical space really well but are otherwise quite poor, non standard, tricky to layout. 

New Form Style Proposal:
<img width="1680" alt="Screen Shot 2019-05-03 at 15 19 20" src="https://user-images.githubusercontent.com/10999/57196567-71e5b800-6f5e-11e9-9ff9-eb3dec05df58.png">
 
Main things
* Label above input
* Optional Input description below label (Will replace most uses of tooltips)
* Space to show what form element has non-default value & reset
* Show required & error, ok states  
 
How to migrate proposal:
* [ ] Create new css classes that can be used from react & angular
* [ ] Update form components so they can opt in to new styles 

The tricky thing here is how to do this transition smoothly without breaking old form layouts of internal pages, plugins as well as external plugins. This is why I propose we create new css classes so we can migrate angular & react pages to new styles. Question is how to avoid creating duplicate components like FormField, Switch etc. FormField is new and I think can be the basis for the transition, not used externally yet as well.

**Comment by ryantxu** [comment]
As discussed a few weeks back....

I like this direction, but it uses a lot of space (good!) and does not work well with our existing horizontal layout (bad!)

I think this structure could work if we switch to a 3 pane layout like:
<img src="https://user-images.githubusercontent.com/705951/59799720-d1dbb800-9299-11e9-9981-99b5a0d937fd.png">

<img src="https://user-images.githubusercontent.com/705951/59799732-d43e1200-9299-11e9-9bd7-5720977995dc.png">

**Comment by marefr** [comment]
Interesting. Somehow this feels like something I've seen somewhere else :smile:

**Comment by Ijin08** [comment]
@ryantxu yeah, this is basically the first step moving in that direction. So it might make sense not to implement new form styles in panel edit until the layout design for it is done.
