### ISSUE TITLE
Support Timeslice function

### ISSUE THREAD

**Issue by mtrebi** [grafana/grafana#1689]
It would be nice to Grafana to support Graphite's Time Slice function. I do not understand why it is not supported yet because in my opinion this function can very useful. Maybe there is another way to do what I want to do.
In my case I need this function to get the growth of my metrics. For example, I have a metric that is the visits of my web page. With time slice function I could get the visits of the last month and the visits of the previous of the last month and compare them to get the growth in that month.

**Comment by torkelo** [comment]
Will look into it, should be possible to add. In the mean time you can use timeShift to get a similar effect

**Comment by torkelo** [comment]
I am not sure this function is supported by the json api, can you verify this? How does the function work? I cannot really understand it from the graphite docs description.

**Comment by AlaaKh94** [comment]
Hi,
I need this function (timeslice) to work with, 
The **timeslice**(**metrics**,**start**,**end**) function is showing a **metric** between **start** and **end** , does grafana supported this function now? or any alternative? 
thanks
