### ISSUE TITLE
Proxy support for outgoing requests from datasources

### ISSUE THREAD

**Issue by ageis** [grafana/grafana#16895]
There are a multitude of tickets that request support for proxies. There are even a few open PRs. Proxies are still utilized in all kinds of IT infrastructure, often internal and corporate. It would be advantageous for Grafana to support basic HTTP and SOCKS5 proxies when connecting to a datasource.

The reason I need this is because I want to host my Prometheus datasource as a Tor hidden service (one of the easiest and most convenient ways to bypass NAT, doesn't require registering a domain name or having a public IP address with an open firewall). There are ways I can hack around your source code or launch Grafana under a torsocks/torify wrapper in order to make it happen, but in general I'm not able to easily do that without basic proxying support.

If you could also use this feature please put a thumbs up!

**Comment by ageis** [comment]
This gets a little bit more into the Tor side of things... But the aforementioned hacks to get things working with Tor often require some fiddling with DNS. For an *.onion address, Tor's DNSPort will supply you with a fake IPv4 address. However, Grafana tries to resolve this and connect to it, so it doesn't work. But I _do_ have proxies that will transparently "torify" the TCP traffic. So it's the only way I can host my remote datasource this way.
```May 06 00:50:10 redacted.example.com grafana-server[28863]: 2019/05/06 00:50:10 http: proxy error: dial tcp 172.92.156.110:9090: connect: connection refused```

**Comment by bergquist** [comment]
Go supports configuring proxy for all outgoing requests with environment variables. https://stackoverflow.com/questions/10383299/how-do-i-configure-go-command-to-use-a-proxy

Might be missing from Grafana docs. Would this work for you?
Im not sure this will solve the dns issue

**Comment by ageis** [comment]
I'll give it a shot and check if HTTP_PROXY is honored, defining it in /etc/default/grafana-server. Will report back.

**Comment by ageis** [comment]
Awesome, that works! I would recommend adding something to the documentation about how to do this.

Again, only relevant to Tor, but because applications will often attempt to resolve DNS and fail on a special-use TLD before passing it to the proxy, there's something extra when it comes to Go programs; you also need to use CGO instead of Go's built-in resolver. So in addition to HTTP_PROXY I set these environment variables (pretty sure only the first two are relevant, the third I think is only relevant for builds):
```
CGO_ENABLED=1
GODEBUG="netdns=cgo+1"
GOFLAGS="-tags=netcgo"
RES_OPTIONS="debug"
```

**Comment by oddlittlebird** [comment]
So, what needs to change in the docs? And are doc changes the only thing that need to change for this issue?

**Comment by roidelapluie** [comment]
The issue with go env variable is that it would be used for all the requests. There is no easy way to just say "please use the proxy for this particular ds". You would need to exclude All the URLS, including grafana pinbacks urls, from that. It would also mean that  you can only use one proxy.

**Comment by GrafanaWriter** [comment]
This issue hasn't had activity in more than six months. In another week, I will close it.

If you comment or otherwise update it, we'll reset the clock.

**Comment by GrafanaWriter** [comment]
Given the age of this issue, and the lack of response, I will close this issue.
