### ISSUE TITLE
grafana alerts not showing up at wider zoom level

### ISSUE THREAD

**Issue by bpri** [grafana/grafana#16908]
**What happened**:
When zoomed out to 2-days not all alerts are being displayed in graph.  A short alert of 30 seconds occured  on 5/5 around 11:45am.  

Here is the view at a 2 day zoom where the 5/5 alert is NOT showing:
https://www.dropbox.com/s/kfant90bqny02uf/Screen%20Shot%202019-05-06%20at%201.21.19%20PM.png?dl=0

If you then zoom in to 5/5 11:45am  the alert appears:
https://www.dropbox.com/s/0xl7ho7gpqdiz9p/Screen%20Shot%202019-05-06%20at%201.22.18%20PM.png?dl=0

**What you expected to happen**:
Alerts should be shown at any zoom level so that they may be investigated.

**How to reproduce it (as minimally and precisely as possible)**:
Have a short (30second) alert.  zoom out to 2 days.   alert disappears.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.1.6 (cf9cb45)
- Data source type & version: prometheus 1.8.2
- OS Grafana is installed on: RHEL6
- User OS & Browser: osx 10.14.2  Chrome 73.0.3683.103
- Grafana plugins: 
- Others:

**Comment by bergquist** [comment]
Any chance you can include the network requests from your browser? This seems weird to me :/

**Comment by bpri** [comment]
[prometheus-hars.zip](https://github.com/grafana/grafana/files/3152531/prometheus-hars.zip)
prometheus-2day.har is the capture of the long view that it does NOT show up in. 
prometheus-zoom-in.har is the capture of the zoomed in view where it DOES show up.

**Comment by aroundthecode** [comment]
hi @bergquist any update on this bug? 
We are experiencing the very same behaviour on Grafana v6.2.1 and Prometheus v2.6.1
depending on the time windows single event alarms seems to disappear.

**Comment by fischerman** [comment]
By default, the step resolution is 1s for annotation queries. However, when you zoom out, eventually the resolution is reduced. If the step duration is longer then the alert it might not show up, because the latter completely happens between two steps.

**Comment by fischerman** [comment]
A possible workaround (haven't tested) is `max_over_time(ALERTS[5m])`. This will show any alerts that happened in the last 5 minute (relative to each step). 5m can be adjusted according to the zoom level. The downside is that the result is now inaccurate by 5m even if you zoom in. Unfortunately, there is no variable substitution similar to `$__interval` for annotation queries. The latter is a possible fix for this issue.
