### ISSUE TITLE
Add documentation for @grafana/ui react components

### ISSUE THREAD

**Issue by warmwaffles** [grafana/grafana#16910]
**What would you like to be added**: Documentation on how to use the new react components.

**Why is this needed**: Currently there are no docs / examples on how to utilize the react components. https://grafana.com/docs/guides/whats-new-in-v6-0/

**Comment by dprokop** [comment]
@warmwaffles thank you for your request. At the moment we are focusing mainly on making the grafana/ui's APIs stable and meaningful for the developers. Since @grafana/ui is still in alpha, we haven't made much progress in documentation area. 

We'll keep you updated, thank you for your patience!

**Comment by oddlittlebird** [comment]
@dprokop, has this been addressed?

**Comment by dprokop** [comment]
@oddlittlebird to some extent yes.

@warmwaffles you can find grafana/ui documentation available at developers.grafana.com/ui . The documentation is not complete yet, but we are working on it :)
