### ISSUE TITLE
Grafana 2.0b https_proxy environment configuration

### ISSUE THREAD

**Issue by srfraser** [grafana/grafana#1691]
Using grafana 2.0b on Ubuntu 14.04, the initial symptom was that Google OAuth failed with a timeout. Our servers sit behind a web proxy, and launching Grafana with 'service grafana start' fails to inherit http_proxy and https_proxy environment variables. Current workaround is to use `/etc/init.d/grafana {start|stop}` which inherits the launching user's environment (proxy details are in /etc/environment)

Could proxy options be added to grafana.ini to make them independent of the method used to start the service?

**Comment by torkelo** [comment]
hm.. not sure what the right way to to do this is, feels weird to have this in the config file when it would be better to have this handled by the init.d script, or whatever launches grafana, maybe if the init script had included /etc/default/grafana (if that file exists), where you can set env variables or override init.d variables. 

I am not sure how other server systems handle this.

**Comment by srfraser** [comment]
For the moment I've added the variables to /etc/init.d/grafana, but those aren't picked up when using 'service'. /etc/default/grafana would be a good place, as well as including /etc/init/grafana.conf in the deb. 

However, I've now noticed that Grafana is using the web proxy for everything - including getting all its data from the backends. Since it's all internal (and on my test system Grafana is on the same server as InfluxDB), this isn't an ideal load to add to the proxy. 

Could there be an authentication-only http(s)_proxy setting?

**Comment by torkelo** [comment]
@srfraser Grafana has no code or special case for using http proxy, it must be done by the OS, or lower level Go standard library http client. Is there no way to exclude certain ip ranges from using the http_proxy , I am not an export how http proxies work on linux. Would prefer to keep this complexity out of grafana if that is possible.

**Comment by torkelo** [comment]
Also, what do you mean including /etc/init/grafana.conf in deb? /etc/grafana/grafana.ini is included, do you mean a systemd spec file should be included in deb? Strange that setting environment variables in the init.d script is not taking effect when you use `service grafana start`

**Comment by srfraser** [comment]
Setting no_proxy does work. The complexity is kept out of grafana and shifted to something outside the service, which makes maintenance and deployment less self-contained, but I can see your reasoning. 

I've not tested whether setting the variables in an upstart configuration file in /etc/init/ would work, but that was my suggestion - apologies for not being clearer. sysvinit scripts are processed by a compatibility layer in upstart, but the environment is very restricted. I can add http_proxy and https_proxy to /etc/init.d/grafana, run 'service grafana start' and /proc/X/environ does not contain the proxy settings. 

Adding the following to /etc/init/grafana.conf ensures upstart's method works, and I'm sure the rest of the environment variables could be set in /etc/default/grafana and imported with defaults the same way:

    description "Grafana"
    start on (filesystem and net-device-up)
    stop on runlevel [06]
    
    respawn
    
    # Ensure these are set in case /etc/environment is empty
    env http_proxy=""
    env https_proxy=""
    
    pre-start script
        . /etc/environment
        # ... or /etc/default/grafana
        export http_proxy
        export https_proxy
    end script 
    
    env DAEMON_USER="grafana" 
    env DAEMON_PATH="/opt/grafana/current/grafana"
    env DAEMON_OPTS="--config=/etc/grafana/grafana.ini web"
    env DAEMON_LOG="/var/log/grafana/grafana.log"
    
    setuid grafana
    chdir /opt/grafana/current
    nice 0
    
    script
        exec "${DAEMON_PATH} ${DAEMON_OPTS}"
    end script

**Comment by jbehrends** [comment]
I'm running into this issue as well.   All traffic to outside destinations (google auth) needs to go through a proxy.

+1 to any official fix/resolution.

**Comment by srfraser** [comment]
Setting no_proxy for internal domain suffixes in the grafana process's environment works for me, if you're able to maintain that list.

**Comment by torkelo** [comment]
Cant this be solved by setting env variables in /etc/default/grafana (or /etc/sysconfig/grafana on rhel)

**Comment by jbehrends** [comment]
Ok, on CentOS 6 I've got this working..

Added the following to: /etc/sysconfig/grafana-server
export no_proxy=internal.domain,127.0.0.1
export http_proxy=http://proxy.domain:3128/
export https_proxy=http://proxy.domain:3128/

Restarted grafana-server

Grabbed the PID for grafana-server

Validated it was i the process's environment: sudo cat /proc/<PID>/environ

Then did a fresh login using google auth while tailing the proxy logs and saw it reach out to "www.googleapis.com:443" via the proxy.

**Comment by renatoram** [comment]
Word of warning for people finding this solution in more recent times: on more modern distributions the "export " prefix doesn't work. 

This is the correct solution on Centos 7:
Add to file: /etc/sysconfig/grafana-server
> http_proxy=http://proxy.domain:3128/
> https_proxy=http://proxy.domain:3128/
> no_proxy=internal.domain,127.0.0.1

**Comment by eslerm** [comment]
The systemd service contains a variable which sets a file for environmental variables.
```
$ cat /usr/lib/systemd/system/grafana-server.service | grep EnvironmentFile
EnvironmentFile=/etc/default/grafana-server
```
Setting the proxy, as described by @renatoram, in `/etc/default/grafana-server` resolved this on Ubuntu 18.04

**Comment by balamrg77** [comment]
Worked for me on RHEL 8.1 by adding the http_proxy and https_proxy environment variable without export keyword in /etc/sysconfig/grafana-server.

**Comment by jacobneroth** [comment]
what is the solution for windows ?

**Comment by bongbk** [comment]
> Word of warning for people finding this solution in more recent times: on more modern distributions the "export " prefix doesn't work.
> 
> This is the correct solution on Centos 7:
> Add to file: /etc/sysconfig/grafana-server
> 
> > http_proxy=http://proxy.domain:3128/
> > https_proxy=http://proxy.domain:3128/
> > no_proxy=internal.domain,127.0.0.1

it works, you save my day

**Comment by jvalley19** [comment]
Hi Folks - where should I set the HTTP_proxy variables in debian 10.7 Grafana environment? I do not see these files/folders. are the variables: http_proxy=http://proxy.domain:3128 or http_proxy=http://proxy.<grafanaserverip>:3128 
Thank you
