### ISSUE TITLE
Graph's legend values (min/max/avg) are not recalculated after changing time interval

### ISSUE THREAD

**Issue by riverhead013** [grafana/grafana#16924]
**Environment:**
grafana-6.1.6
MSSQL 2017
Windows 10

**Description:**
Is it expected behaviour that legend values (min/max/avg) are not recalculated after zooming/changing time interval?

![Screen Shot 2019-05-07 at 16 25 33](https://user-images.githubusercontent.com/11230919/57303145-5fe25180-70e5-11e9-8312-cd3f283f5f05.png)
![Screen Shot 2019-05-07 at 16 25 46](https://user-images.githubusercontent.com/11230919/57303149-61137e80-70e5-11e9-8ba8-0574effe9ded.png)

**Comment by torkelo** [comment]
strange unable to replicate, maybe the max & avg was the same for these two time regions? 

Can you include the result of query inspector (raw query response) and the legend, and show that they are not matching?

**Comment by riverhead013** [comment]
Ok, this is my query 

**Query:**
SELECT
$__timeGroup([TimeStamp], '5s', NULL) as time,
([ResponseTime]) "login.aspx"
  FROM [LoadTest2010].[dbo].[LoadTestPageDetail]
  Group By $__timeGroup(TimeStamp, '5s', NULL), ResponseTime

**Query Inspector result (before zooming):**
Object
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1557153629840"
to:"1557153990138"
queries:Array[1]
0:Object
refId:"A"
intervalMs:60000
maxDataPoints:1920
datasourceId:2
rawSql:" SELECT
 $__timeGroup([TimeStamp], '5s', NULL) as time,
 ([ResponseTime]) "login.aspx"
 FROM [LoadTest2010].[dbo].[LoadTestPageDetail]
 WHERE PageId = 0
 Group By $__timeGroup(TimeStamp, '5s', NULL), ResponseTime"
format:"time_series"
response:Object
results:Object
A:Object
refId:"A"
meta:Object
rowCount:48460
sql:" SELECT
 FLOOR(DATEDIFF(second, '1970-01-01', [TimeStamp])/5)*5 as time,
 ([ResponseTime]) "login.aspx"
 FROM [LoadTest2010].[dbo].[LoadTestPageDetail]
 WHERE PageId = 0
 Group By FLOOR(DATEDIFF(second, '1970-01-01', TimeStamp)/5)*5, ResponseTime"
series:Array[1]
0:Object
name:"login.aspx"
points:Array[50400]
tables:null

**Query Inspector result (after zooming):**
Object
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1557153720317"
to:"1557153870192"
queries:Array[1]
0:Object
refId:"A"
intervalMs:60000
maxDataPoints:1920
datasourceId:2
rawSql:" SELECT
 $__timeGroup([TimeStamp], '5s', NULL) as time,
 ([ResponseTime]) "login.aspx"
 FROM [LoadTest2010].[dbo].[LoadTestPageDetail]
 WHERE PageId = 0
 Group By $__timeGroup(TimeStamp, '5s', NULL), ResponseTime"
format:"time_series"
response:Object
results:Object
A:Object
refId:"A"
meta:Object
rowCount:48460
sql:" SELECT
 FLOOR(DATEDIFF(second, '1970-01-01', [TimeStamp])/5)*5 as time,
 ([ResponseTime]) "login.aspx"
 FROM [LoadTest2010].[dbo].[LoadTestPageDetail]
 WHERE PageId = 0
 Group By FLOOR(DATEDIFF(second, '1970-01-01', TimeStamp)/5)*5, ResponseTime"
series:Array[1]
0:Object
name:"login.aspx"
points:Array[50400]
tables:null

![Screen Shot 2019-05-07 at 16 50 47](https://user-images.githubusercontent.com/11230919/57304615-50b0d300-70e8-11e9-929c-a225e2d9ca09.png)


I could not open Array[50400] because browser is not responding after trying to expand the array.

**Comment by riverhead013** [comment]
Ok, adding $__timeFilter(TimeStamp) macros to where clause fixed the issue.
