### ISSUE TITLE
Influxdb HTTP method undefined

### ISSUE THREAD

**Issue by SibrenVasse** [grafana/grafana#16929]
**What happened**:
After upgrading grafana to v6.2.0-beta1 my influxdb data source stopped working. The panels in the interface had little red errors and no data was being displayed.
The server returned HTTP 400 to requests to query?db=x&q=y, because the HTTP method was 'undefined'. In the influxdb settings 'GET' was selected in the dropdown.
After saving the settings of the connection the data source started working again. I could not find any required upgrade changes in the release/upgrade notes.

I'm guessing this was introduced by #16690? Is an initialization of the HTTP Method setting to a default value when upgrading missing?

**How to reproduce it (as minimally and precisely as possible)**:
1. Previously configured influxdb data source (with <=6.1.6).
2. Upgrade to 6.2.0-beta1.
3. Data source stops working.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.2.0-beta1 (9d877d6)
- Data source type & version: influxdb 1.7.3
- OS Grafana is installed on: archlinuxarm
- User OS & Browser: Archlinux - Firefox 68.0a1
- Grafana plugins: InfluxDB

**Comment by bergquist** [comment]
@aocenas could you please look into this? sounds related to https://github.com/grafana/grafana/pull/16690

**Comment by StephenSorriaux** [comment]
@bergquist @aocenas 
I can confirm the bug, I submitted a PR to fix this issue.

**Comment by bergquist** [comment]
Once the build is done you can install master with this fix. Might be a few other commits in master as well but very few since we branched of yesterday. 

https://grafana.com/grafana/download/6.3.0-c568c445pre
https://hub.docker.com/r/grafana/grafana-dev/tags
