### ISSUE TITLE
proxy error: context canceled

### ISSUE THREAD

**Issue by ishockwave** [grafana/grafana#16923]
**What happened**:
Getting a timeout after exactly 60s requesting some data from a modified simple-json-datasource. The datasource gets its information from a middleware programmed in python using the bottle webserver.

**Anything else we need to know?**:
Already downloaded the source, changes a few places that made the most sense for me in terms of 60 seconds timeout. No luck. Also tried the solutions in the other similar tickets

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: Simple-json-datasource
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome
- Grafana plugins: -
- Others:
Here is the full debug output of the request arriving and being dropped.

```
INFO[05-07|15:09:03] Proxying incoming request                logger=data-proxy-log userid=0 orgid=1 username= datasource=grafana-simple-json-datasource uri=/api/datasources/proxy/1/query method=POST body="{\"timezone\":\"browser\",\"panelId\":14,\"dashboardId\":231,\"range\":{\"from\":\"2019-05-05T13:09:03.591Z\",\"to\":\"2019-05-07T13:09:03.591Z\",\"raw\":{\"from\":\"now-2d\",\"to\":\"now\"}},\"rangeRaw\":{\"from\":\"now-2d\",\"to\":\"now\"},\"interval\":\"5m\",\"intervalMs\":300000,\"targets\":[{\"target\":\"Interface Report\",\"metric\":\"Interface Report\",\"filter\":\"*\",\"refId\":\"A\",\"type\":\"table\"}],\"maxDataPoints\":636,\"scopedVars\":{\"__interval\":{\"text\":\"5m\",\"value\":\"5m\"},\"__interval_ms\":{\"text\":300000,\"value\":300000}},\"adhocFilters\":[]}"
DBUG[05-07|15:09:05] Scheduling update                        logger=alerting.scheduler ruleCount=0
DBUG[05-07|15:09:15] Scheduling update                        logger=alerting.scheduler ruleCount=0
DBUG[05-07|15:09:25] Scheduling update                        logger=alerting.scheduler ruleCount=0
DBUG[05-07|15:09:35] Scheduling update                        logger=alerting.scheduler ruleCount=0
DBUG[05-07|15:09:45] Scheduling update                        logger=alerting.scheduler ruleCount=0
2019/05/07 15:09:54 error garbage collecting session files: lstat /usr/share/grafana/data/sessions/4/2/42bee87cc00ded60: no such file or directory
DBUG[05-07|15:09:54] Session GC                               logger=session
DBUG[05-07|15:09:55] Scheduling update                        logger=alerting.scheduler ruleCount=0
2019/05/07 15:10:03 http: proxy error: context canceled
INFO[05-07|15:10:03] Request Completed                        logger=context userId=0 orgId=1 uname= method=POST path=/api/datasources/proxy/1/query status=502 remote_addr=212.144.118.141 time_ms=60060 size=0 referer="http://x.x.x.x/grafana/d/fHC3iDQmk/scaltel-interface-report?orgId=1&from=now-2d&to=now"
```

**Comment by bergquist** [comment]
Have you tried configuring https://grafana.com/docs/installation/configuration/#timeout ?

**Comment by ishockwave** [comment]
Yes via the config file and hardcoded, no luck there

**Comment by marefr** [comment]
See related issue #15258 (I think).

**Comment by ishockwave** [comment]
> See related issue #15258 (I think).

Thanks, already found that issue although I found it quite odd that mine timed out at 60s vs 30s in the given issue. 
I cant really wrap my head around it as I see the response on the Python webserver after around 70s so that is working. Could it be the datasource itself?
I looked again but didn't find any information

**Comment by ishockwave** [comment]
I just did some more testing and replaced the 'gevent' addon in bottle with the dwefault. In thios case all requests were processed as they received and not asynchronous.
I then created a dashboard with multiple panels quering that datasource and got similar behaviour.
For example
* Panel A (loading time ~14 seconds) - Finished
* Panel B (loading time ~15 seconds) - Finished after exactly 29 seconds
* Panel C (big query ~ 70 seconds) - Failed after exectly 60 seconds viewing the chrome devloper menu

**Comment by bergquist** [comment]
Thank you for providing all the details. 

Since the proxy doesn't supply a `http.Transport` the default transport. 
https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go#L74

```go
// DefaultTransport is the default implementation of Transport and is
// used by DefaultClient. It establishes network connections as needed
// and caches them for reuse by subsequent calls. It uses HTTP proxies
// as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and
// $no_proxy) environment variables.
var DefaultTransport RoundTripper = &Transport{
	Proxy: ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
		DualStack: true,
	}).DialContext,
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}
```

So to increase the timeout in the proxy we need to increase timeout for the dialer as well. I guess we need to increase KeepAlive as well.

**Comment by ishockwave** [comment]
> ```go
> var DefaultTransport RoundTripper = &Transport
> ```

Thank you for the clarification. Could you provide an example on where to implement this in the goven source code? I have nearly no experience in Go and don't know where to start

**Comment by bergquist** [comment]
Turns out I was wrong :) 
We set the transport a few lines below. https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go#L79

https://github.com/grafana/grafana/blob/master/pkg/models/datasource_cache.go#L43

Any chance you could try to set the KeepAlive to something higher? https://github.com/grafana/grafana/blob/master/pkg/models/datasource_cache.go#L63

**Comment by ishockwave** [comment]
I will try that and report back, although I think I already increased that by factor 10 for testing earlier on.

**Comment by ishockwave** [comment]
I checked again on the sourcecode I compiled and indeed I already bumped those settings up quite a lot for testing.
```go
transport := &http.Transport{
    TLSClientConfig: tlsConfig,
    Proxy:           http.ProxyFromEnvironment,
    Dial: (&net.Dialer{
        Timeout:   600 * time.Second,
        KeepAlive: 300 * time.Second,
        DualStack: true,
    }).Dial,
    TLSHandshakeTimeout:   10 * time.Second,
    ExpectContinueTimeout: 1 * time.Second,
    MaxIdleConns:          100,
    IdleConnTimeout:       90 * time.Second,
}
```
These were the values I used and they gave the same exact behaviour as if I installed grafana using the precompiled version.

**Comment by ishockwave** [comment]
Just to add some details. Both grafana and the webserver responsilbe for collection the report data run in differents docker containers, I dont think that should make a difference but I did not mention up until now.

**Comment by ishockwave** [comment]
Do you require any moer details about the problem? Or were you able to reproduce it?

**Comment by bergquist** [comment]
We have plenty of people who had problems with docker networking regarding timeouts. Are you running any networking services between grafana and the datasource? I would definitely start looking into the docker setup since its problem with timeouts and docker have been reported multiple times.

**Comment by ishockwave** [comment]
Alright I will look into that, is there any related issue regarding the docker timeout and maybe a solution on where to increase that timeout in the config?

**Comment by Enternalcode** [comment]
@ishockwave 
Have you found a way to solve the problem? :)
I had the same problem.

**Comment by marcoboffi** [comment]
news about this?
I have same problem....

**Comment by bergquist** [comment]
We added more logging in 6.6.2. If your running older versions you might be able to get more info by upgrading.

**Comment by ishockwave** [comment]
@marcoboffi  @Enternalcode Not really, i worked around it by building a middleware that does the long request every 10 minutes and caches it in a database with timestamps. Grafana then queries that middleware and gets the result from the database

**Comment by marcoboffi** [comment]
I 'm trying with Grafana 7 and it seems problems is disappeared

**Comment by marefr** [comment]
@marcoboffi thanks. Closing this for now since it seems to have been resolved. Will consider reopen if you still have this problem on latest Grafana version.
