### ISSUE TITLE
Misaligned Text in repeated singlestat panel

### ISSUE THREAD

**Issue by garceri** [grafana/grafana#16931]
**What happened**:
Text is aligned (and clipped) to the bottom in Singlestat panel in 6.2.0-5c501327pre nightly
See:
![image](https://user-images.githubusercontent.com/10517648/57334763-0c78ff00-70f7-11e9-8bf5-4f3c9ccf1842.png)

**What you expected to happen**:
It was working OK in 6.2.0-308d1bd2pre
See:
![image](https://user-images.githubusercontent.com/10517648/57334776-1ac71b00-70f7-11e9-8481-3028e08d8164.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create Singlestat panel repeated (i'm using 12 panels per row)
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.0-5c501327pre
- Data source type & version: Prometheus 2.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome Windows latest version
- Grafana plugins: None
- Others:

**Comment by bergquist** [comment]
Thank you for trusting us enough to run Grafana nighly/master :) Your feedback/testing is very valuable for us.

**Comment by torkelo** [comment]
I can confirm that this is a css bug, but likely one that has existed in Grafana for a long time, not new in 6.2 . But can fix in 6.2

**Comment by garceri** [comment]
Thanks @torkelo , wonder why the old 6.2 (no more than a couple weeks old) nightly i was using displayed the panels OK....
