### ISSUE TITLE
Notification Message move to CUSTOM DETAILS for Pagerduty notifications

### ISSUE THREAD

**Issue by bbfoto** [grafana/grafana#16930]
**What would you like to be added**: 
I would like grafana's "Notification Message" to be displayed in pager-duty "CUSTOM DETAILS" instead of in the PD Summary.

**Why is this needed**:
If I want to add a short paragraph of info related to this alert (as Grafana's Notification Message text entry box suggests), and include link to a runbook for example, I'd rather not see all that in the PD alert headline/summary. I'd rather it be in the CUSTOM DETAILS.  

looks like it would be fairly simple change, moving `+evalContext.Rule.Message` on line 87 of pkg/services/alerting/notifiers/pagerduty.go to line 94

**Comment by AndrewBurian** [comment]
Necro bump, but I also would _very_ much would like this, and am willing to write the code for it if it would be accepted.

The custom details currently have the graph's legend:value pairs in the custom details. While they could be used for automation, they're not the friendliest format so I don't think there'd be much risk breaking downstream dependancies.

I would probably leave the existing generated values at the top, add a blank line after them to deter any automation parsing beyond that point, then add the notification message at the bottom.

@bergquist any objections or thoughts?

**Comment by bergquist** [comment]
Moving the alert message to custom details makes sense. 

> I would probably leave the existing generated values at the top, add a blank line after them to deter any automation parsing beyond that point, then add the notification message at the bottom.

I think that sounds good. The real solution here would be templating support for the custom details (that can render series names and values if desired) but I think this would be a good enough solution for now.
