### ISSUE TITLE
No way to remove datasource from removed plugin

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16937]
If you add some a datasource with some plugin, then remove the plugin, it no longer loads (not surprising!), but there is also no way to delete it:

![image](https://user-images.githubusercontent.com/705951/57347724-266f0d80-7108-11e9-8ca9-c2dc9d24687b.png)

**Comment by nzrunner** [comment]
I have the same issue. In my case, I moved the Grafana DB to a new Grafana server and didn't install the Strava plugin on the new server (deliberately, as the plugin was faulty).

Now I cannot delete the Strava datasource.

Any suggestions on how I can delete the datasource reference?

**Comment by annelaurefroment** [comment]
When the plugin has been removed it is possible to delete the datasource using the API: 
https://grafana.com/docs/grafana/latest/http_api/data_source/#delete-an-existing-data-source-by-id
