### ISSUE TITLE
When there is no data from metrics ..how can i show my service is down instead of NA or some other info in the services. 

### ISSUE THREAD

**Issue by skokkira** [grafana/grafana#16939]
STOP -- PLEASE READ!

GitHub is not the right place for questions and support requests.

Please ask questions on our community site: [https://community.grafana.com/](https://community.grafana.com/)

**Comment by bergquist** [comment]
Please ask questions on our community site [https://community.grafana.com/](https://community.grafana.com/)

We want issues on github to be about bugs and features requests.
