### ISSUE TITLE
Add a clock widget to our dashboards

### ISSUE THREAD

**Issue by pskerrett** [grafana/grafana#1693]
Feature Request:

It would be nice to include a native clock widget we can integrate into our dashboards. This is just a nice-to-have feature. Most of us use this application on a large-screen public LCD display & having a clock integrated into the dashboard would be a nice touch., and make the overall suite more user-friendly. 

Great work so far, I am loving the 2.0 alpha!!

**Comment by torkelo** [comment]
good idea!

**Comment by pskerrett** [comment]
Thanks :) 
I forgot to add, having a configuration method to set the timezone of the clock also would be helpful, so that it is not necessarily getting local machine time. This would help out folks like me who run their systems log stamps on GMT, but do not live in GMT. Having a big GMT clock integrated into our excellent Grafana dashboard would make things easier.

**Comment by jgerschk** [comment]
+1

**Comment by mxk1235** [comment]
It looks like we can add our own HTML in a text panel.  I tried using a simple HTML time widget (e.g. http://time.is/widgets ) for this purpose, but it looks like the <script> tag trips it up.

**Comment by damajor** [comment]
Custom widget is a solution.

In case a clock widget is added to Grafana, here are my suggestions:
- clock display (digital or analog)
- mapped alerts with visual effect for notification
- some flags to enable/disable all the features

Just to clarify some topics about the alerts:
- settings just like the annotations
- can be mapped to SQL or ES
- only future events
- setting: refresh time
- setting: limit the time period used to fetch the alerts

This features is very important to many NOC / SOC / OSS ... teams.

**Comment by Luzifer** [comment]
+1 on a native widget.

However a simple (temporary) solution for only displaying the time could be this one: https://jsfiddle.net/ap85k13v/ 
Built this for one of my dashboards and it nearly looks like a native widget…

![screen shot 2015-07-02 at 20 58 21](https://cloud.githubusercontent.com/assets/20142/8485322/200a298e-20fd-11e5-8b77-886cbb634028.png)

**Comment by damajor** [comment]
Nice

**Comment by s1m0** [comment]
I have a set of very simple html panels showing the time in different cities of interest to our company. 
I discovered that the html ids and script function names have to be unique across the panels. I also discovered that the onload event of the script tag wasn't getting triggered so, for now, I have to rely on the user mousing-over the panel to trigger the clock to start!

Any suggestions for improvements gratefully received....

Here's the code I'm using for my UTC clock panel:-

```html
<div id="utc-time" style="text-align:center;color:red;font-size:30px;" onmouseover="startUTCTime()">Mouse Me!!</div>
<script  onload="startUTCTime()">
function startUTCTime() {
    var today=new Date();
    var h=today.getUTCHours();
    var m=today.getMinutes();
    var s=today.getSeconds();
    h = checkTime(h);
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('utc-time').innerHTML = h+":"+m+":"+s;
    var t = setTimeout(function(){startUTCTime()},800);}
function checkTime(i) {
    if (i<10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;}
</script>
```
and another for Denver:-
```html
<div id="den-time" style="text-align:center;color:green;font-size:30px;" onmouseover="startDENTime()">Mouse Me!!</div>
<script  onload="startDENTime()">
function startDENTime() {
    var utc_offset = -6;
    var today=new Date();
    var h=today.getUTCHours() + (utc_offset);
    if (h>23) {h=h-24};
    if (h<0) {h=h+24};
    var m=today.getMinutes();
    var s=today.getSeconds();
    h = checkTime(h);
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('den-time').innerHTML = h+":"+m+":"+s;
    var t = setTimeout(function(){startDENTime()},800);}
function checkTime(i) {
    if (i<10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;}
</script>
```

**Comment by cemo** [comment]
+1

**Comment by torkelo** [comment]
https://grafana.net/plugins/grafana-clock-panel
