### ISSUE TITLE
2.0b1 - Can not run on port 80

### ISSUE THREAD

**Issue by jtyr** [grafana/grafana#1694]
I'm not able to run Grafana v2.0.0-beta1 on port 80. This is how I configure it:

```
[server]
cert_file = 
cert_key = 
domain = localhost
enable_gzip = false
http_addr = 
http_port = 80
protocol = http
root_url = %(protocol)s://%(domain)s:%(http_port)s/
router_logging = false
static_root_path = public
```

This is the error message in the log:

```
[I] Listen: http://0.0.0.0:80
[web.go:116 runWeb()] [E] Fail to start server: listen tcp 0.0.0.0:80: bind: permission denied
```

There is nothing running on the port 80:

```
# netstat -ntl | grep 80
#
```

Any idea what could be wrong?

**Comment by torkelo** [comment]
top bind to ports below 1024 you need to run grafana as root. The deb/rpm packages creates a grafana user the initd script starts grafana under this user, 

You can redirect port 80 to the grafana port using iptables:
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3000.  Will add this to the docs

**Comment by jtyr** [comment]
Or this works as well:

```
setcap 'cap_net_bind_service=+ep' /usr/bin/grafana
```

as per: http://stackoverflow.com/a/414258

**Comment by elnappo** [comment]
There is no error reported when started with: 

     $ service grafana-server start

Would be nice if the init script outputs this as an error.

**Comment by torkelo** [comment]
@elnappo it does, 

I get this in the log file:
015/04/21 13:41:38 [web.go:88 StartServer()] [E] Fail to start server: listen tcp 0.0.0.0:80: bind: permission denied

And the init.d script cannot start , [fail]

**Comment by elnappo** [comment]
Yap youre right i missed that, sorry. btw in this case return code is 0
I've found another case (ubuntu):
* install grafana
* start grafana
* change port to 80
* restart grafana

or 

* install grafana
* change port to 80
* start grafana (fails)
* start grafana

--> endless loop of: 
Starting Grafana Server [fail] [fail] [fail] [fail] [fail]...

**Comment by torkelo** [comment]
opened another issue with the problem of the init.d script looping like that, #1837

**Comment by maddenca** [comment]
FYI, because of the rename of grafana to grafana-server you can use this to use a priv port:
```
 setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
```

**Comment by Hyperxnoia** [comment]
I face the same problem. The following step can resolve.
1. modify the grafana.ini, open its 80 port
# The http port  to use
http_port = 80
2. execute setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server 
3. restart grafana service
Good luck .

**Comment by claenjoy** [comment]
notice that it needs this command again after update from 3.1.0 to 3.1.1

` setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server`

**Comment by venupaccha** [comment]
worked ..thanks

**Comment by kilteer** [comment]
Going from 4.1.2 to 4.2.0 needed to run the setcap command again. 
`setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server`

**Comment by BasvanH** [comment]
Is there a way to make this permanently even after updating?

**Comment by yesman82** [comment]
> Is there a way to make this permanently even after updating?

It doesn't even stay, when i restart.

**Comment by BasvanH** [comment]
I found a way to make it somewhat permanently. Add this line directly below `# Start Daemon` in file `/etc/rc.d/init.d/grafana-server`. This will stay until an update replaces this file. Perhaps this could be added permently by the Grafana team?

`/sbin/setcap 'cap_net_bind_service=+ep' $DAEMON`

**Comment by MediaMaquina** [comment]
`setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server`
Failed to set capabilities on file `/usr/sbin/grafana-server' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

What is it saying?

**Comment by jkosharek** [comment]
Seems to still be an issue with version 7

**Comment by MediaMaquina** [comment]
Iptables solution worked for me https://github.com/grafana/grafana/issues/1694#issuecomment-88517560

**Comment by BinaryPaean** [comment]
> `setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server`
> Failed to set capabilities on file `/usr/sbin/grafana-server' (Invalid argument)
> The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
> 
> What is it saying?

It sounds like it is trying to tell you that setcap in that usage is only valid for a binary application, not a script or symlink. I would expect that path to be your "real" installation location, but verify it is not a symlink in your case.

**Comment by Alternating** [comment]
running this 'setcap cap_net_bind_service=+ep' /usr/sbin/grafana-server'   Broke my server and I cannot for the life of me figure out why.  Uninstalling and reinstalling fixes this

systemd[2142]: grafana-server.service: Failed to execute command: Operation not permitted
systemd[2142]: grafana-server.service: Failed at step EXEC spawning /usr/sbin/grafana-server: Operation not permitted
systemd[1]: grafana-server.service: Main process exited, code=exited, status=203/EXEC

**Comment by stanleyondrus** [comment]
I experienced the same issue.
Running `setcap cap_net_bind_service=+ep' /usr/sbin/grafana-server` broke everything, 
but I could revert it using `setcap -r /usr/sbin/grafana-server`

**Comment by danwalkeruk** [comment]
I encountered this issue when updating a long overdue install of 6.3.4 to 8.3.4.

Previously, running the `setcap cap_net_bind_service=+ep' /usr/sbin/grafana-server` would fix our post-update issues, however, this time it stopped the service from starting with no useful logs.

Adding the following

```
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateUsers=false
```

To the systemd file under the `[System]` heading has fixed the issue.

**Comment by SNoof85** [comment]
> I encountered this issue when updating a long overdue install of 6.3.4 to 8.3.4.
> 
> Previously, running the `setcap cap_net_bind_service=+ep' /usr/sbin/grafana-server` would fix our post-update issues, however, this time it stopped the service from starting with no useful logs.
> 
> Adding the following
> 
> ```
> CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> AmbientCapabilities=CAP_NET_BIND_SERVICE
> PrivateUsers=false
> ```
> 
> To the systemd file under the `[System]` heading has fixed the issue.

Saved me ! But it took me a while before realize I must also `setcap -r /usr/sbin/grafana-server` !

**Comment by ronakraj** [comment]
> This fix should go to the top of the post.
> 
> > I encountered this issue when updating a long overdue install of 6.3.4 to 8.3.4.
> > Previously, running the `setcap cap_net_bind_service=+ep' /usr/sbin/grafana-server` would fix our post-update issues, however, this time it stopped the service from starting with no useful logs.
> > Adding the following
> > ```
> > CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> > AmbientCapabilities=CAP_NET_BIND_SERVICE
> > PrivateUsers=false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To the systemd file under the `[System]` heading has fixed the issue.
> 
> I still get the same error. Can you elaborate on how +ep translates to what you added please?

For me running 8.4.4, the ``iptables`` command above was the only thing that worked.

**Comment by listenquiet** [comment]
> I encountered this issue when updating a long overdue install of 6.3.4 to 8.3.4.
> 
> Previously, running the `setcap cap_net_bind_service=+ep' /usr/sbin/grafana-server` would fix our post-update issues, however, this time it stopped the service from starting with no useful logs.
> 
> Adding the following
> 
> ```
> CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> AmbientCapabilities=CAP_NET_BIND_SERVICE
> PrivateUsers=false
> ```
> 
> To the systemd file under the `[System]` heading has fixed the issue.

it works in 9.0.3，thanks

**Comment by VladislavGatsenko** [comment]
For adding this parameters:
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateUsers=false

You need to edit service file of grafana-server:
/lib/systemd/system/grafana-server.service

End add this strings to end of [Service] section:
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateUsers=false

Then need to reload system services: sudo systemctl daemon-reload

After that conf in /etc/grafana/grafana.ini (where http_port = 80 or else (<1024)) will be work fine

System Debian 11.5, installed grafana via .deb file.

**Comment by resmo** [comment]
Don't edit `/lib/systemd/system/grafana-server.service` it will get overwritten by the next package update. Better extend it (it will be written to `/etc/systemd/system/grafana-server.service.d/override.conf`):
```
systemctl edit grafana-server
```
add
```
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateUsers=false
```
save and restart service
```
systemctl restart grafana-server.service 
journalctl -fu grafana-server
```

**Comment by damianharouff** [comment]
> Better extend it (it will be written to `/etc/systemd/system/grafana-server.service.d/override.conf`):

And in usual systemd fashion, this doesn't work at all, likely because it puts it as a chunk at the top so there's now two `service` blocks, whereas `systemctl edit` explicitly states that it's going to be additive.

```
root@grafana:/home/damian# cat /etc/systemd/system/grafana-server.service.d/override.conf
[Service]
# Give the CAP_NET_BIND_SERVICE capability
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE

# A private user cannot have process capabilities on the host's user
# namespace and thus CAP_NET_BIND_SERVICE has no effect.
PrivateUsers=false
root@grafana:/home/damian# cat /lib/systemd/system/grafana-server.service
[Unit]
Description=Grafana instance
Documentation=http://docs.grafana.org
Wants=network-online.target
After=network-online.target
After=postgresql.service mariadb.service mysql.service influxdb.service

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/share/grafana/bin/grafana server                                     \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}

LimitNOFILE=10000
TimeoutStopSec=20
CapabilityBoundingSet=
DeviceAllow=
LockPersonality=true
MemoryDenyWriteExecute=false
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=full
RemoveIPC=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native
UMask=0027

[Install]
WantedBy=multi-user.target
root@grafana:/home/damian#
```
```
root@grafana:/home/damian# cat /lib/systemd/system/grafana-server.service
[Unit]
Description=Grafana instance
Documentation=http://docs.grafana.org
Wants=network-online.target
After=network-online.target
After=postgresql.service mariadb.service mysql.service influxdb.service

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/share/grafana/bin/grafana server                                     \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}

LimitNOFILE=10000
TimeoutStopSec=20
CapabilityBoundingSet=
DeviceAllow=
LockPersonality=true
MemoryDenyWriteExecute=false
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=full
RemoveIPC=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native
UMask=0027

[Install]
WantedBy=multi-user.target
root@grafana:/home/damian#
```

**Comment by luanbalbi** [comment]
Here is my 2 cents:

Thanks @resmo! This one worked for me (Just not sure if this config will really stay there after an update in Grafana). I executed **systemctl edit grafana-server** and opened nano editor. When saving, just need to save in temp override.conf file. The override.conf will be created automatically.
> Don't edit `/lib/systemd/system/grafana-server.service` it will get overwritten by the next package update. Better extend it (it will be written to `/etc/systemd/system/grafana-server.service.d/override.conf`):
> 
> ```
> systemctl edit grafana-server
> ```
> 
> add
> 
> ```
> CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> AmbientCapabilities=CAP_NET_BIND_SERVICE
> PrivateUsers=false
> ```
> 
> save and restart service
> 
> ```
> systemctl restart grafana-server.service 
> journalctl -fu grafana-server
> ```

I needed to add those 3 lines in a specific place, just like this:
_PS: I must added a line with [Service] before them, otherwise the service fails to start. It showed me this error message when running systemctl status grafana-server:
systemd[1]: /etc/systemd/system/grafana-server.service.d/override.conf:1: Assignment outside of section. Ignoring._

```
### Editing /etc/systemd/system/grafana-server.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

[Service]
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateUsers=false

### Lines below this comment will be discarded

### /usr/lib/systemd/system/grafana-server.service
```


@damianharouff  When I edited the service, it shows on Nano all line commented. I put those 3 lines as I said before, save it and when I cat the override.conf, it shows only those lines I've added
> And in usual systemd fashion, this doesn't work at all, likely because it puts it as a chunk at the top so there's now two `service` blocks, whereas `systemctl edit` explicitly states that it's going to be additive.
> 
> ```
> root@grafana:/home/damian# cat /etc/systemd/system/grafana-server.service.d/override.conf


After that, it's running perfectly on port 80 for me.
Running Grafana 12.0 at Oracle Linux 9.5
