### ISSUE TITLE
How to achieve session effects in Grafana 6

### ISSUE THREAD

**Issue by sunnut** [grafana/grafana#16948]
As we know, the grafana remove the session feature.
But now I need a feature that session support. When I did not do any thing within the specified time such as 10 min，I hope the system exit.How can I get it in Grafana 6?

**Comment by bergquist** [comment]
Need it how? For your fork?

**Comment by sunnut** [comment]
1. Not for my fork.
2. I just need it to implement the function that the system keep the signed state when user always didnot do anything.

**Comment by torkelo** [comment]
There is no way to this, if you use auth proxy you must proxy all requests (add the proxy header)

**Comment by sunnut** [comment]
@torkelo thanks, There is no session in grafana 6.0? The session_life_time also doesnot work.Can I make session automatic timeout by modify the source code.

**Comment by torkelo** [comment]
If you login you get a session token that you can set the lifetime off, but auth proxy users get no auth token currently

**Comment by sunnut** [comment]
@torkelo, In grafana version 6, Is there a method making the user automatic quit when they didnot do any thing within the specified time?

**Comment by torkelo** [comment]
yes, check docs: https://grafana.com/docs/auth/overview/#login-and-short-lived-tokens

login_maximum_inactive_lifetime_days = 7
login_maximum_lifetime_days = 30

**Comment by sunnut** [comment]
@torkelo, I have tried that. But the two settings will make the user exit whether user dispatch actions or not.
