### ISSUE TITLE
Include user list in copy in email notifications

### ISSUE THREAD

**Issue by RestfulBlue** [grafana/grafana#16954]
Hey there, in our company we have internal email server, which can send sms notifications based on received emails.

In such case we can send letter to sms-server@host with users added to copy. When sms server receive such letter, he will determine phone number based on ldap and send sms.

But currently grafana send one letter for each address, and does not include list of users in copy.
On other words, sms server will receive letter which will contain only sender email, without users list.

Will be beatiful if email notification will have an option to send one letter with receiver and adding all users to copy. In such case grafana will send email to SMS server and add all users in copy.

**Comment by jan25** [comment]
@torkelo would you know if someone is already working on this? Otherwise i'm happy to pick it up.

The idea would be to add a custom content field when 'Email' is selected as notification channel in create/edit channel area. Suggestions are welcome!

**Comment by torkelo** [comment]
No one is working on this.

Custom content field ?

**Comment by jan25** [comment]
The channel form will have a additional field to input custom content to append to email body. As here:

<img width="608" alt="Screen Shot 2019-05-11 at 09 28 51" src="https://user-images.githubusercontent.com/12004246/57566621-6582b480-73cf-11e9-90bc-e2ac46ab074c.png">

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
