### ISSUE TITLE
Graph has the wrong stack when using Azure Monitor data source

### ISSUE THREAD

**Issue by silencev** [grafana/grafana#16969]
**What happened**:
`403 (blue line)` and `404 (orange line)` doesn't have data at the time. (please compare with stack disabled screenshot)
and it still have the "stack bar"
![Provision_Set_Resources_-_Grafana](https://user-images.githubusercontent.com/24366323/57426355-773e4d80-7251-11e9-946f-7bf714f06090.png)

Visualization settings
![Provision_Set_Resources_-_Grafana](https://user-images.githubusercontent.com/24366323/57426311-42ca9180-7251-11e9-8cff-de4149ef8875.png)

Stack is disabled and click points
![Provision_Set_Resources_-_Grafana](https://user-images.githubusercontent.com/24366323/57426507-06e3fc00-7252-11e9-84f6-27c8faac8bd7.png)

**What you expected to happen**:
Using the same query in Log Analytics, it shows:
![epas-oms-ws-pro1_-_Analytics](https://user-images.githubusercontent.com/24366323/57426426-b1a7ea80-7251-11e9-9613-c058706f83c9.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud (6.1.6)
- Data source type & version:
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Mac OSX & Firefox
- Grafana plugins: n/a
- Others: n/a

**Comment by torkelo** [comment]
Stacking with irregular data points can be very hard to visualize correctly, Grafana tries it best and interpolates and some times that can go wrong. 

To have stacking work properly you need to group your data into time buckets and have 0 values for missing time buckets.  (or nulls that Grafana can turn to zeros with the null value option in graph panel)

**Comment by yesoreyeram** [comment]
In the case, you may need to use make-series instead summarize function. https://docs.microsoft.com/en-us/azure/kusto/query/make-seriesoperator

**Comment by silencev** [comment]
@yesoreyeram thanks for your information
