### ISSUE TITLE
Feature Request: Add Legend to Gauge Panel

### ISSUE THREAD

**Issue by Trebla7th** [grafana/grafana#16960]
**What would you like to be added**:
Ability to add a legend and/or labels on a "Gauge" panel

**Why is this needed**:
Currently gauge panel supports multiple gauges.  But these gauges cannot be differentiated from each other (so I've been advised on stackoverflow here: https://stackoverflow.com/questions/56043571/add-labels-to-gauge-panel-in-grafana) with labels.  

In this instance, we are polling logged in users across all servers being monitored by prometheus, would like to put these into a single gauge so we can quickly see number of logged in users on each server.  This can easily be represented in a graph, but is much easier to read in a gauge.

**Comment by torkelo** [comment]
The gauge shows the series name (or field / coluimn) for each visualization, please try v6.2 beta for this feature:
https://play.grafana.org/d/ZvPm55mWk/new-features-in-v6-2?orgId=1

**Comment by Trebla7th** [comment]
Fantastic, thank you
