### ISSUE TITLE
Breaking change introduced for plugins when moved datemath to @grafana/ui

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#16962]
Seems like we introduced a breaking change when moving datemath to `@grafana/ui`. It broke the zabbix plugin at least. Plugin loader now exposes the following:
https://github.com/grafana/grafana/blob/1ef15283a462ba8c6040264bc2bbfe3f1250bfe7/public/app/features/plugins/plugin_loader.ts#L109

Think this still should be reverted to be backward compatible?
`exposeToPlugin('app/core/utils/datemath', datemath);` 

See report in comment for further details at https://community.grafana.com/t/after-upgrade-from-grafana-5-to-6-dashboard-keeps-logging-out/14931/36?u=mefraimsson

**Comment by torkelo** [comment]
That is probably just a mistake
