### ISSUE TITLE
Graphs and Tables are not coherent in the way they handle time when browser timezone differs from UTC

### ISSUE THREAD

**Issue by pmouawad** [grafana/grafana#16964]
**What happened**:

Using Grafana I get strange results with Graphs if timezone of browser differs from UTC timezone.

**What you expected to happen**:

I am testing from a Timezone that differs from original one GMT-6 (Chicago)
Initally everything was working fine , both Tables and Graphs data were aligned.
When switching to Chicago Timezone, I notice that:
- Table data and Single Stats are still ok
- But graph shows nothing, only when I go back in past does it show data.

If I change my computer time to match the initial timezone , then it works again.

**How to reproduce it (as minimally and precisely as possible)**:

Use for example this dashboard with InfluxDB and JMeter:
- https://grafana.com/dashboards/5496

Run a simple test adding data and try to visualize.

**Anything else we need to know?**:

Other people seem to be facing same issues:

https://community.grafana.com/t/graphs-does-not-show-the-data-correspoding-to-current-time-zone/16097
https://community.grafana.com/t/different-behavior-between-table-and-graph/6711

**Environment**:
- Grafana version: v6.1.5 (commit: b40b7d2)
- Data source type & version: InfluxDB 1.7.6
- OS Grafana is installed on:

Linux XXXX 4.18.0-1014-azure #14~18.04.1-Ubuntu SMP Mon Mar 18 16:15:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- User OS & Browser:
Mac OSX 10.11.6 (15G22010)
Chrome Version 73.0.3683.103 (Official Build) (64-bit)

- Grafana plugins:
None
- Others:

**Comment by torkelo** [comment]
The Graph will only show the time range selected, so if you query returns data outside this change the graph will be empty. This is not true for other visualizations (table & singlestat).

**Comment by torkelo** [comment]
The scenario you describe sounds strange, like your data is not stored in UTC properly. Please store the data in UTC then you can query it in any timezone

**Comment by pmouawad** [comment]
Hello I understand what you write, but how do you explain that table gets data for time range and not graphs ?

What information do you need me to provide to check this ? 
I really think there is a problem.


Regards

**Comment by marefr** [comment]
@pmouawad please use query inspector for graph panel and table panel and include full request/response to prove that there are an actual bug. Also, include the json of the graph and table panel would be helpful. Thanks

**Comment by torkelo** [comment]
It’s very strange , usually influx handled timezone a without issue , no other reports on issues like this. It’s like your data / influx timezone is not in UTC
