### ISSUE TITLE
Grafana v6: second parameter in new groupByTags() function not selectable

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#16961]
**What happened**: In Grafana v6, after adding a new groupByTags() function, the second parameter is not selectable. (if there is value at second parameter already, then it's selectable)

**What you expected to happen**: Able to fill in second parameter in new groupByTags() function

**How to reproduce it (as minimally and precisely as possible)**: as above

**Anything else we need to know?**: No

**Environment**:
- Grafana version: v6.1.6
- Data source type & version: Metrictank
- OS Grafana is installed on: RHEL 7.x
- User OS & Browser: Chrome or Safari
- Grafana plugins:  N/A
- Others:

**Comment by hamelg** [comment]
Issue still here with gafana v6.3.3.

**Comment by shanson7** [comment]
Interestingly, If the `/functions` query fails, then the function autocomplete sticks a sentinel `tags` value in that allows it to work. Only when the `/functions` query works does the function autocomplete seem to make this unclickable

**Comment by shanson7** [comment]
This is still broken in 6.5.1, any ETA here?

**Comment by torkelo** [comment]
Testing this in master (v6.6) this looks fixed, not by what commit. 

Can you test if this is working in v6.6 (stable tomorrow). The second param should get a default value (which you can select and change)

**Comment by shanson7** [comment]
Are you sure that you aren't seeing the behavior described in https://github.com/grafana/grafana/issues/16961#issuecomment-542376126 ? We can check 6.6 to make sure it works even when `/functions` request succeeds

**Comment by torkelo** [comment]
Yes, tested with both latest graphite and metrictank, with a successful call to /functions  , but still unsure as I do not know what we have done to fix it

**Comment by fyang13** [comment]
This seems still broken in v6.6 (v6.6.0 build 5c11bbdfb4)

**Comment by fyang13** [comment]
@torkelo This should be reopened?

**Comment by torkelo** [comment]
Yea, can still see in play site, but cannot replicate it in master , need to debug more fire out why

**Comment by torkelo** [comment]
Been able to replicate this and found a fix, opened PR , hope to include in next patch release.

**Comment by kogaba** [comment]
I have this Issue with aliasSub aliasQuery on debian. Grafana v6.6.0
