### ISSUE TITLE
Discord notification support with mentions

### ISSUE THREAD

**Issue by george-vieira** [grafana/grafana#16967]
Discord additon to grafana is great but sometimes I don't see the notification in the channel (we have many) or I've logged off the desktop but if I had a mention, my mobile would ping me that I've been mentioned and can see there's an alert. Without the mention it just sits there until someone (only I watch this) notices a problem.

**Comment by jan25** [comment]
@george-vieira Thanks for raising this issue. Could you share few more details on your channel and how you would like the mention to work?

RE [Slack channel settings](https://grafana.com/docs/alerting/notifications/#slack), there seems to be mention a feature available to provide when setting up a channel in grafana. It allows to input what goes after `@` for a mention

**Comment by george-vieira** [comment]
My channel is merely used for chatting but no one is noticing the bot dying. Grafana alerts the "alarms" channel but only the admins can see that channel which not all are available or keeping watch. So with mentions, even if you have discord on your mobile but not actively using it, it will beep a notification of a message which mentions you. pretty sure slack is similar.

At the moment, If we could specify within the discord notification a user id field to notify would suffice for me, buy for the wider community they may want multiple users.

My python discord bot in python that I wrote, I can make it send a notification as below:
<@373#######96290> bot heartbeat timeout, check bot health.

When I post that, I get the notification on any device discord is running on. Just a normal message and all I get is a highlight on the channel someones posted a message, which doesn't help

hope that helps.

**Comment by jan25** [comment]
@george-vieira thanks! I've not used discord before, so had to read up a bit on that. I opened a PR to address this. All kinds of mentions should work with this PR.

Re user specific mention, you may still have to provide `<@373#######96290>` in Mention field in 
 discord channel settings, and this field can hold multiple mentions with space separated.

**Comment by george-vieira** [comment]
"you may still have to provide <@373#######96290> in Mention field"
that's a good start, I think it should just be the integer value though and the plugin handle wrapping that with the <@###> formatter for the message, I'm cool with that thanks.
