### ISSUE TITLE
Per user setting for using flot vs png

### ISSUE THREAD

**Issue by mattrobenolt** [grafana/grafana#1697]
Now with user accounts, it'd be super nice to have a user preference to view all graphs as png vs flot.

Some of our users don't want to waste all their precious CPU cycles rendering flot graphs everywhere, especially over larger time spans. But right now, you have to switch every graph to png for that graph itself, enforcing it on everyone. Makes sense to have this a user specific switch.

**Comment by torkelo** [comment]
large time spans are as quick as short ones.

client side rendering usually only takes 400m for 10
heavy dense graphs. Are you running graphite 0.9.12? that would 
explain it, it does not support maxDataPoints which can result in Grafana being slow over large time spans, but that is easy to fix.

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/performance/

**Comment by torkelo** [comment]
meant 400ms, or faster, just tested a time range of 1 year with 10 graphs with many series, rendered under 500ms, so it is most likely that you are using Graphite version without maxDataPoints feature, or InfluxDB without any aggregation (which could result in millions of data points returned to grafana per graph)

**Comment by mattrobenolt** [comment]
Upgrading to 0.9.13 helped, but it's still not as fast as actual pngs. :) No matter what, flot will be slower than actual images, and no matter how well that's optimized, it's just a fact. Your browsering rendering a png will be cheaper than some crazy JavaScript rendering interactive graphs.

**Comment by mattrobenolt** [comment]
So fwiw, I still thing this is a valid issue.
