### ISSUE TITLE
the datasource does not support alerting queries for PNP4Nagios Plugin

### ISSUE THREAD

**Issue by gintisaurabh** [grafana/grafana#16973]
Hi,

I am using grafana Version 5.4.2 (commit: d812109, branch: HEAD).

I have configured PNP plugin for Nagios->PNP4Nagios->Grafana Integration.

I am able to see the graphs but not able to configure the alerting for the same getting "the datasource does not support alerting queries"

Any Help? Thanks!

**Comment by bergquist** [comment]
Only core datasources support alerting in Grafana. 

Once https://github.com/grafana/grafana/issues/6841 is complete plugin auhtors can add support for alerting
