### ISSUE TITLE
Anonymous access organization error: 'org': pq: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by sebastianfuss** [grafana/grafana#16977]
**What happened**:
Got a lot of HTTP 401 Response from Grafana Backend, shown as "Unexpected error" at the Grafana UI.
I think the reason of the HTTP 401 is:
`t=2019-05-09T12:58:59+0000 lvl=eror msg="Anonymous access organization error: 'org': pq: remaining connection slots are reserved for non-replication superuser connections"`

**What you expected to happen**:
New, updated Data should be shown.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The described error occurs after update grafana from 6.1.3 to 6.1.6.
The db.t3.micro supports up to 75 connections. To be honest I am not sure exactly. The access is anonym with the viewer role.

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: Prometheus 2.6.1
- OS Grafana is installed on: AWS ECS with AWS RDS Postgres 9.6.11-R1 @ db.t3.micro
- User OS & Browser: Safari, Chrome with MacOS
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel,vonage-status-panel
- Others:

**Comment by bergquist** [comment]
There are some connection improvements in 6.2.0 but you can always configure https://grafana.com/docs/installation/configuration/#max-open-conn if you want to specify a max and Grafana will pool connections better.
