### ISSUE TITLE
panels in collapsed rows are not loaded on mobile when uncollapsed

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#16978]
**What happened**:

Panels that belongs to a row are not shown in mobile when the row uncollapsed.

**What you expected to happen**:

Panels are shown.

![Screenshot_20190509-173106](https://user-images.githubusercontent.com/291750/57466300-a61fe800-7280-11e9-844f-b19d3106a1f5.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create a dashboard with panels ahd hide them in a collasped row. Uncollapse row in mobile.

**Anything else we need to know?**:

Might be related to lazy loading?

**Environment**:
- Grafana version: 6.3.0-e0511f4apre
- User OS & Browser: Chrome on Android

**Comment by roidelapluie** [comment]
Reproducible on play:

![image](https://user-images.githubusercontent.com/291750/57470741-dae46d00-7289-11e9-9049-c20cb53b72c0.png)


https://play.grafana.org/d/O8-0TJiWz/gh-16978-collapsed-rows?orgId=1

**Comment by torkelo** [comment]
thanks for reporting this! we will try to fix for the 6.2 stable release!
