### ISSUE TITLE
Search: impossible to scroll over the dashboards list on mobile

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#16981]
**What happened**:

I wanted to test #16978 on my manager's smartphone but he counl not scroll to the correct dashboard on mobile in the dashboard list dropdown.

**What you expected to happen**:

The dashboard list dropdown is scrollable on mobile.

**How to reproduce it (as minimally and precisely as possible)**:

Search for a dashboard and try to scroll.

Note: reproducable on play.grafana.org

![image](https://user-images.githubusercontent.com/291750/57468449-c487e280-7284-11e9-8c51-e3002975e2ef.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.0-e0511f4apre

- User OS & Browser: chrome on mobile

**Comment by torkelo** [comment]
Strange, what mobile? Works on iphone + chrome

**Comment by roidelapluie** [comment]
Chrome on android. tested on two phones.

**Comment by jschill** [comment]
Can be reproduced in chrome on osx.
