### ISSUE TITLE
Graph: Only sort series in legend table mode

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#16980]
**What happened**:
sortByName() appears to be broken in Grafana 6.1.6

**What you expected to happen**:
We run a query to get back host, filename metrics.  We do an aliasByTags(host, fileSystem) and then sortByName(true, false)

We can use the query inspector to confirm that the data is properly sorted in the result set, however the legend in Grafana is not sorted.

**How to reproduce it (as minimally and precisely as possible)**:

Here is our MT query:
sortByName(aliasByTags(consolidateBy(seriesByTag('namespace=os', 'name=fileSystem.bytes.used.g', 'cluster=~${my_cluster:regex}', 'fileSystem=$my_fileSystem'), 'max'), 'cluster', 'host', 'fileSystem'), true, false)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: MetricTank
- OS Grafana is installed on: Linux
- User OS & Browser: Windows, Chrom
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Strange, unable to replicate. Maybe you have table legend with a sort specified on one of the columns?

**Comment by shalstea** [comment]
The only Legend setting I have on is "Show".  If I start with a new dashboard, same query it works.

This dashboard was written prior to the upgrade.  Do you think the upgrade of Grafana had any side effect on an older dashboard? 

I can try and have them rewrite the dashboard as a work-around

**Comment by torkelo** [comment]
Check panel json, legend options, any sort there?

**Comment by shalstea** [comment]
I see:
  "legend": {
    "alignAsTable": false,
    "avg": false,
    "current": false,
    "hideEmpty": true,
    "hideZero": true,
    "max": false,
    "min": false,
    "rightSide": false,
    "show": true,
    "sort": "max",
    "sortDesc": true,
    "total": false,
    "values": false
  },

But in the UI sort max is off

**Comment by shalstea** [comment]
I should say, show max is off.  But when I do show it, I can see it is sorted by max and not name

**Comment by shalstea** [comment]
To fix this, I am guessing I would need to remove the "sort" : "max" row ?

It would be nice if the sort legend option was visible / editable at the UI level.

**Comment by torkelo** [comment]
It is, in table mode , then show max , you should see a caret down indicating sort order and clicking on table header toggles sort or disables it

**Comment by shalstea** [comment]
It is not disabling in table mode. 

However I was able to fix this by:
1. Turning on table mode.
2. Showing max
3. Click on the max sort to clear it
4. Hide max
5. Undo table mode.

The fact that there is a hidden sort is not good.  I would like that to be visible table mode on or off.

**Comment by torkelo** [comment]
> Turning on table mode.
Showing max
Click on the max sort to clear it
Hide max
Undo table mode.

Yes that was what I tried to suggest :) 

This is definitely a bug the sorting should only be applied in table mode when you can see/change the sorting.
