### ISSUE TITLE
Loki: Selecting time range shows error

### ISSUE THREAD

**Issue by agolomoodysaada** [grafana/grafana#16986]
**What happened**:

After making a Loki log search, I tried narrowing down the time window by selecting and highlighting a range in the graph using drag and drop. Instead of seeing logs in that time window. I got this error

```
TypeError: v.from is undefined
```
<img width="369" alt="Screen Shot 2019-05-09 at 6 58 45 PM" src="https://user-images.githubusercontent.com/29459870/57491851-81317200-728c-11e9-8181-311b0b656c48.png">

**What you expected to happen**:

To see logs in that time window.

**How to reproduce it (as minimally and precisely as possible)**:

Enter query like this `{release="crawlers"} storageexception` in the Explore tab using a Grafana Loki source. Then, highlight part of the graph that has some logs.

**Anything else we need to know?**:

Nothing shows up in the network tab in the browser.

I also noticed the range on top right changed to this

<img width="318" alt="Screen Shot 2019-05-09 at 6 59 42 PM" src="https://user-images.githubusercontent.com/29459870/57491988-0e74c680-728d-11e9-8f00-a7c6ea9339fa.png">

**Environment**:
- Grafana version: 6.2.0-beta1
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Firefox 66

**Comment by agolomoodysaada** [comment]
I was able to reproduce on Chrome as well

**Comment by torkelo** [comment]
Thanks for reporting this! will fix in upcoming 6.2 stable!
