### ISSUE TITLE
Streaming: Update streaming in supported plugins 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#16988]
With this https://github.com/grafana/grafana/pull/16659 MetricsPanelCtrl now use the new PanelQueryRunner that is using a slightly different streaming mechanism. 

We have some plugins (think only Splunk) that uses the old streaming method, need to investigate how we can support both for a period.

**Comment by torkelo** [comment]
So we decided to try to update splunk instead, but what we could do is show a nice error when a subscription is returned that informs about this change.

**Comment by xlson** [comment]
@alexanderzobnin How's the work on this one going? Trying to get a feel for if we can do a beta2 release tomorrow.

**Comment by alexanderzobnin** [comment]
Splunk plugin was updated, so I'm closing this since it's the only plugin that uses streaming now.
