### ISSUE TITLE
2.0b2 - Grafana version on settings page is not resolving correctly

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1699]
![image](https://cloud.githubusercontent.com/assets/917241/6953422/8c2cd2f0-d8c9-11e4-866a-01fcbdc9468f.png)

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master

**Comment by maddenca** [comment]
FYI, with the fix you now get an upgrade advice!
![image](https://cloud.githubusercontent.com/assets/917241/6973041/25fb9a56-d988-11e4-9a84-3c587a15fb7f.png)
