### ISSUE TITLE
Wrong spacing for singlestat panel in 6.2 Beta1

### ISSUE THREAD

**Issue by michael-doubez** [grafana/grafana#16998]
**What happened**:

I upgraded to 6.2 Beta1 version (in order to test the fix on ElasticSearch 7).
All my SingleStat panels, the value displays are lower in the panel.

**What you expected to happen**:

No change of position of value in SingleStat panel.

**How to reproduce it (as minimally and precisely as possible)**:

- With previous version, display a SingleStat panel keeping it at a minimal height for displaying the value.
- Update to 6.2Beta1
- The value is clipped at the bottom.

**Anything else we need to know?**:

I suspect it is a side effect of the feature for removing the panel header  #16884 because when removing the panel header, I recover the previous positioning of the value.

**Environment**:
- Grafana version: Grafana v6.2.0-beta1 (9d877d6)
- Data source type & version: Prometheus 2.8.1
- OS Grafana is installed on: Linux RHEL7
- User OS & Browser: Windows 10
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
I assume your panel is very small (short), should be fixed in next beta/stable
https://github.com/grafana/grafana/pull/16944

**Comment by michael-doubez** [comment]
Fixed in beta2.
Thanks
