### ISSUE TITLE
Column Support

### ISSUE THREAD

**Issue by ProTip** [grafana/grafana#170]
I would be really nice to have support for the "column" panel type in Kibana :)

**Comment by torkelo** [comment]
closing due to lack of interest, might be solved with better grid/layout system in the future

**Comment by waqark3389** [comment]
+1

**Comment by tompoch** [comment]
+1

**Comment by jfragoulis** [comment]
+1

**Comment by torkelo** [comment]
this is not really needed with the new v5 grid https://www.youtube.com/watch?v=BC_YRNpqj5k&t=36s

**Comment by SamuelmAsh** [comment]
+1 for a grid/column system. This would be particularly helpful for using text panels as titles and centring them neatly
