### ISSUE TITLE
Provide feedback to user while updating template variables

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#17005]
Currently, there is no way to know if grafana is currently updating drop-down lists of template variables. This is especially a problem when a variable depends on the another: user selects var1, then var2 list gets updated but user can select outdated elements from var2

**Comment by hugohaggmark** [comment]
Grand news, we have implemented this feature in #27917. 

Thank You to you for taking the time to create this issue!

**Comment by faxm0dem** [comment]
I just realised this after (accidentally) installing 7.3.1.
It's awesome exactly what I was hoping for :-)))))))))))))

THANKS

**Comment by hackery** [comment]
This is excellent for visibility. We're constantly finding that when a dashboard loads slowly (generally Elasticsearch) it's because the variable queries are stalling, rather than the panel queries. (_Refresh: On Dashboard Load_ often helps us, but isn't ideal for our data)
