### ISSUE TITLE
Do not strip inline styles from panel

### ISSUE THREAD

**Issue by Ekimik** [grafana/grafana#17001]
**What would you like to be added**:
It would be nice if inline styles remain in HTML.

**Why is this needed**:
I have certain specific datasources and I need to load some metrics from these datasources to Grafana. So I develop simple app, which creates HTML snippet with desired content, which is then loaded to Grafana by [this](https://grafana.com/plugins/ryantxu-ajax-panel) plugin. I also add inline styles to my template. My app creates HTML snippet similar to
```html
<div style="color: #d8d9da; height: 100%;">
<div style="display: flex; align-items: center; height: 100%;font-size: 2.5rem;color:#299c46">
    <div style="flex-grow: 1; text-align: center;">
        <div style="font-weight: 500; margin: 4px;">0</div>
        <div style="font-weight: 500;"></div>
    </div>
</div>
</div>
```
But result in Grafana after rendering is 
```html
<div>
<div>
    <div>
        <div>0</div>
        <div></div>
    </div>
</div>
</div>
```

**Comment by torkelo** [comment]
if your refering to the html panel you need to disable sanitizing: 
https://grafana.com/docs/installation/configuration/#disable-sanitize-html

**Comment by Ekimik** [comment]
Does `disable_sanitize_html` option affect also inline styles? As documentation says 
> If set to true Grafana will allow script tags in text panels
If so, it would be nice to update documentation.

Wouldn't it be better (or more secure at least) to allow inline styles as they are safe (or at least I don't see any way, how can I make some kind of attack using styles)? I don't want to enable potential vulnerability only becaouse I want to show simple HTML.

**Comment by Ekimik** [comment]
I finaly found some time to try solution suggested by @torkelo
> if your refering to the html panel you need to disable sanitizing:
> https://grafana.com/docs/installation/configuration/#disable-sanitize-html

But it seems it doesn't help. I try it in Docker image `grafana/grafana:6.1.6`
> `docker run --rm -p 3333:3000 -e GF_PANELS_DISABLE_SANITIZE_HTML=true -e GF_INSTALL_PLUGINS=ryantxu-ajax-panel grafana/grafana:6.1.6`

Above command should start Grafana with suggested sanitize setting and with one plugin installed for serving content to panel in Grafana. But output is still the same as described in [first issue comment](https://github.com/grafana/grafana/issues/17001#issue-442691658).

It is worth to mention, that I am not sure if sanitize setting was applied at all. I can see following line, when starting container
> `t=2019-05-24T09:07:06+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PANELS_DISABLE_SANITIZE_HTML=true"`

but when I open config file `/etc/grafana/grafana.ini` in container, I see
```
...

[panels]
;enable_alpha = false
# If set to true Grafana will allow script tags in text panels. Not recommended as it enable XSS vulnerabilities.
;disable_sanitize_html = false

...
```
I cannot tell if this is correct or not.

**Comment by keremispirli** [comment]
I have the same problem. In a Tabel Panel, inline style attributes I add are stripped during rendering. Setting "disable_sanitize_html" to "true" in the .ini file does not change this behavior.
