### ISSUE TITLE
Bar Guage: Support for scroll bar

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#17008]
**What happened**:
When we have so many series, the graph is not rendered properly. 
**What you expected to happen**:
It could have an auto scroll bar on the panel.
**How to reproduce it (as minimally and precisely as possible)**:
Any query returning a large number of series.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2-beta
- Data source type & version: Influx
- OS Grafana is installed on: Mac
- User OS & Browser: Chrome
- Grafana plugins: Bar Guage
- Others:

<img width="388" alt="Screen Shot 2019-05-10 at 2 32 05 PM" src="https://user-images.githubusercontent.com/9439420/57558154-8694c800-7331-11e9-97be-7b309e444527.png">

**Comment by paregupt** [comment]
I felt a need of something similar while reporting #16883. IMO, relatively slim graph and larger font size (by default) will also help.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
