### ISSUE TITLE
v6.2 is not available on debian

### ISSUE THREAD

**Issue by rolandjitsu** [grafana/grafana#17010]
**What happened**:
I just tried to update to the latest version on Ubuntu, which I assume is `v6.2.0`, using:
```
sudo apt-get update
sudo apt-get install grafana
```
But I'm still at `v6.1.6`.

**What you expected to happen**:
I would have expected to get the latest version.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
6.2 is only out in beta, have you added the beta repository? 
https://grafana.com/docs/installation/debian/#apt-repository

**Comment by rolandjitsu** [comment]
I see, nope I don't have it. I wonder if it would break the existing installation if I add the beta repo and update?

**Comment by rolandjitsu** [comment]
Nevermind, I upgraded anyway and it seems to be ok (so far).
