### ISSUE TITLE
ES data source throws no date field found

### ISSUE THREAD

**Issue by rolandjitsu** [grafana/grafana#17011]
**What happened**:
I'm trying to add a new elasticsearch data source, but it throws an error:
```
No date field named @timestamp found
```

**What you expected to happen**:
I'd expect it to work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
These are the settings for ES in Grafana:

![Screenshot 2019-05-11 15 07 42](https://user-images.githubusercontent.com/1479737/57566405-a0e8a780-73fe-11e9-984e-6231fe86637a.png)

Looking at the network for `_mapping`, I can see the following response:
```json
{
  "encoder-000001": {
    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "center_pos_": {
          "type": "long"
        },
        "datetime": {
          "type": "date"
        },
        "encoder_0_angle": {
          "type": "float"
        },
        "encoder_0_position": {
          "type": "long"
        },
        "encoder_0_starting_angle": {
          "type": "float"
        },
        "encoder_1_angle": {
          "type": "float"
        },
        "encoder_1_position": {
          "type": "long"
        },
        "encoder_1_starting_angle": {
          "type": "float"
        },
        "errnum": {
          "type": "long"
        },
        "event": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "hostname": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "is_x": {
          "type": "long"
        },
        "msg": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "starting_angle_": {
          "type": "float"
        },
        "use_defaults": {
          "type": "long"
        }
      }
    }
  }
}
```

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: Elasticsearch 7
- OS Grafana is installed on: Ubuntu 18.04 LTS
- User OS & Browser: macOS 10.14.3, Chrome
- Grafana plugins:
- Others:

**Comment by rolandjitsu** [comment]
It seems that this was due to incompatible ES versions. After upgrading to Grafana v6.2, I could select ES 7+ and it works.

**Comment by keomabrun** [comment]
I am using Grafana 6.7.3 (in Debian buster) and Elastic Search 7.4 (AWS) and I get the same issue.

**Comment by charinduedirisuriya** [comment]
@keomabrun same scenario as you, please do let me know if you found a workaround

**Comment by keomabrun** [comment]
Removing the `@` sign did the trick for me. I am an elasticsearch newbie so I am not sure that this is the right way to do it.

**Comment by jackzhangsir** [comment]
i  am the same problem

**Comment by rsahay408** [comment]
I am facing the same issue, ES and grafana both versions are 7+,
I am following this article https://dzone.com/articles/jmeter-elasticsearch-live-monitoring

**Comment by bijaykanshinew** [comment]
Leaving pattern field blank solve my issue.
screenshot =>
https://ibb.co/jbdmpqg
