### ISSUE TITLE
Multiple instances do not overwrite datasources but share dashboards

### ISSUE THREAD

**Issue by ev1lm0nk3y** [grafana/grafana#17013]
**What would you like to be added**:
Ability to specify a data source for individual grafana deployments, but share dashboards across all of them.

**Why is this needed**:
There's a common database across multiple cloud projects to share dashboards, but the data source is individual to the cloud project.
```
          local prometheus             
grafana---<
          db of dashboards
```

Sharing the same DB overwrites the datasource across multiple grafana instances.

**Comment by torkelo** [comment]
> Sharing the same DB overwrites the datasource across multiple grafana instances.

yes. Sharing DB shares everything, it's for HA setups. 

You can use data source & dashboard provisioning (ie setup from files), read the docs. It would enable some level of sharing between separate instances.

**Comment by ev1lm0nk3y** [comment]
I understand the HA setup, but grafana instances do not associate DB tables with cloud projects, or any other configuration metric.

here's the use-case: (i've read the docs, read the debugging output, and i'm asking for a feature)

I have multiple cloud projects utilizing helm charts to deploy prometheus and grafana. I want to share dashboards across projects utilizing a database but their data source is project dependent.

Example:
grafana-prj1 datasource is local prj1-prometheus
grafana-prj2 datasource is local prj2-prometheus

Their dashboards are exactly the same, and should be shared across projects (the need for separate projects are a biz need) but they have different datasources. When they connect to the shared DB, grafana overwrites the datasource and the dashboards fail. This shouldn't happen.

**Comment by torkelo** [comment]
Not sure what you mean overwrite the datasource, when does Grafana do this?

**Comment by ev1lm0nk3y** [comment]
If there is a shared database across multiple grafana instances, one of those instances will overwrite the data source table for every other grafana instance. If I gave 2 grafana instances different data sources, but the same database configuration, one of the grafana instances will not show the dashboards correctly.

If you need more data on this, I can totally show you where this happens. What I would like is the ability to tell grafana (explicitly) where to find the data source and not have it overwritten by some database. If I'm developing a HA grafana instance, I'm pretty sure that I'm telling it what data source to pull from and then can use a single point of reference (aka a database) to provide me with dashboards.

**Comment by ev1lm0nk3y** [comment]
BTW Grafana actually does this pretty early on in the logs that I've found. If you configure an off-host DB, that might be shared across multiple grafana instances, the last one to be started with a specific configuration actually overwrites DB entries for the data source DB.

We've resolved it by having multiple DBs, 1 for each grafana instance (even in a HA setup), and copy the dashboards into each DB, but that is... stupid. Couldn't there be an extra field in the data source table that describes the source?

**Comment by torkelo** [comment]
> If there is a shared database across multiple grafana instances, one of those instances will overwrite the data source table for every other grafana instance. If I gave 2 grafana instances different data sources, but the same database configuration, one of the grafana instances will not show the dashboards correctly.

Would not call this overwriting, more like a regular update?? If you hit save it will save the change to DB, not doing that would be a bug. 

If you have multiple instances of Grafana with separate data sources you need separate Grafana databases (or use multiple Grafana orgs). 

You can use provisioning to share dashboard as json files between instances or use the api to sync dashboards between instances.
