### ISSUE TITLE
Grafana 2 - Default theme for anonymous user

### ISSUE THREAD

**Issue by heitormotta** [grafana/grafana#1701]
How do I select which is the default theme for anonymous access? I couldn't find any info about it in the conf files, nor in the docs.

Also, can I choose the theme for embedded graphs, maybe by an URL parameter?

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/6959392/c5ee8016-d918-11e4-9bb2-9a46b3ae5334.png)

**Comment by torkelo** [comment]
You can now override theme via url parameter (?theme=light), and added theme option to share link and embed tabs in share modal, very useful also when rendering panel to png. 
![image](https://cloud.githubusercontent.com/assets/10999/6959480/d5adf49a-d919-11e4-8333-2d81d86e3273.png)

**Comment by torkelo** [comment]
If you do not want to wait for next beta/RC1, recent builds from master can be found here, http://grafana.org/download/builds
