### ISSUE TITLE
Bad request (Error 400) on embedded dashboard

### ISSUE THREAD

**Issue by xolom** [grafana/grafana#17012]
### My setup
System: Debian stretch on Rockpro64
DB: InfluxDB 1.7.6
Grafana version: 6.1.6
Browser used: Chrome and Safari (same behavior)

### The problem
I use some dashboards embedded in the visualization for ioBroker. The page wos gettingsslower and slower until i found out that the console is flooded with error messages like this:
![Screen Shot 2019-05-11 at 8 56 45 AM](https://user-images.githubusercontent.com/1269774/57566458-1176d080-73cd-11e9-8eb5-d0de928d3e14.png)
Taking a closer look at the error gives me following information:
![Screen Shot 2019-05-11 at 9 02 41 AM](https://user-images.githubusercontent.com/1269774/57566465-2a7f8180-73cd-11e9-97d9-58ed7e62684b.png)
Luckily the query is also there:
![Screen Shot 2019-05-11 at 9 03 50 AM](https://user-images.githubusercontent.com/1269774/57566468-3408e980-73cd-11e9-8e5a-3b2312bae67d.png)

If i use the embedded url and open it alone, there are no errors at all. Only if i use it in combination with iobroker.

**Comment by schreda** [comment]
Ok setting the GROUP BY value to something else that $__interval solves the issue.
Where is $__interval set?

**Comment by marefr** [comment]
@xolom when you embed the dashboards which generates errors vs open embedded url alone are you using the exaxt same url, i.e. the `http://<hostname>/d-solo/...` url? In what way are the value of duration different when error occurs vs when you open embedded url alone?

You can read about the `$__interval` global variable [here](https://grafana.com/docs/reference/templating/#the-interval-variable).

Thanks

**Comment by xolom** [comment]
Ticket can be closed.
This issue didn't came from Grafana, but from the interface where it's embedded.
