### ISSUE TITLE
Mobile: not able to set auto refresh

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#17014]
**What happened**:
I opened a dashboard on mobile and am unable to:

Refresh a dashboard without refreshing the whole page
Set auto refresh interval

**What you expected to happen**:
Refresh/auto refresh button to appear/ even if it could be back in time picker for mobile

**How to reproduce it (as minimally and precisely as possible)**:

Open Play grafana on mobile 

![Screenshot_20190511-172705](https://user-images.githubusercontent.com/291750/57571780-73a5f480-7412-11e9-878b-66bfdd3142c8.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2 beta1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Android chrome
- Grafana plugins:
- Others:

**Comment by flopp999** [comment]
on my iPhone the refresh-button appear when I turn the phone 90 degrees

**Comment by positron96** [comment]
Same here: in 6.0.0 the button was there, but it's gone in 6.4. Considering that Time range is also not visible in the bar, there is plenty of space to fit that refresh button.
This is 6.0.0
![IMG_20191116_171527](https://user-images.githubusercontent.com/2095278/68991789-142f1280-0895-11ea-9a5a-66f84218afe7.jpg)

This is 6.4
![IMG_20191116_171600](https://user-images.githubusercontent.com/2095278/68991797-1f823e00-0895-11ea-8214-3fe4b05f4966.jpg)

**Comment by daniellee** [comment]
I can see the refresh button and auto refresh options on iOS 14. Still looks a bit rough but seems usable.

Can re-open if this is still a problem.
