### ISSUE TITLE
Splunk Plugin Feature request - New Additional Advanced Formatting Option for Splunk

### ISSUE THREAD

**Issue by EduSpencer** [grafana/grafana#17028]
**New Additional Advanced Formatting Option for Splunk:**

For multi select variables this implementation is needed to improve filtering before the first pipe or in the where clause:

servers = ['test1.', 'test2']

String to interpolate: '${servers:splunk}'

Interpolation result: '(servers="test." OR servers="test2")'

**Comment by torkelo** [comment]
Can you open this in the splunk plugin repo instead?
