### ISSUE TITLE
RFE - Don't throw the 'unsaved changes' dialog on minor dashboard changes

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1702]
While viewing a dashboard it is quite common to change the timespan, or change the selected item in a template, both of which cause the 'unsaved changes' dialog to be thrown if you try to browse to a different dashboard.  My suggestion is to not throw the warning dialog if the changes are minor such as:
* timespan
* chosen template item
* expand or contracted state of row
* selected items state or sort in a graph

If other items change (like edit a panel contents) do throw the warning, just don't on minor changes.

**Comment by torkelo** [comment]
timespan and template item was already ignored by unsaved changes feature. Added row collapse state and graph legend sort to the list of ignored properties.
