### ISSUE TITLE
Splunk Plugin Feature Request - Masking special characters in Panel Splunk Query:

### ISSUE THREAD

**Issue by EduSpencer** [grafana/grafana#17029]
In Splunk you can do table transformation with the fallowing command:

Index=xy|eval {field}=field1  => takes field as columnname and field1 as value
As {} is already used for Grafana variables this Splunk query is not working.

 Is there a possibility to mask the {} so I can use this characters in the Splunk query for transforming data?

**Comment by torkelo** [comment]
Can you open this in the splunk plugin repo instead?
