### ISSUE TITLE
Feat req: Elastic search / Table panel diff queries support

### ISSUE THREAD

**Issue by deborahlow97** [grafana/grafana#17024]
Hello,

I am using Grafana v6.0.0 (commit: 34a9a62) and elasticsearch data sources.
I am trying to place a `Count` metric for 2 different queries to be shown in 2 different columns. However in the table, only **1 column** is shown with `Count`, as they **combined/merged** both columns with `Count` together.
Case 2 shows the problem I'm currently facing.

Case 1: 1 query (no issues with this)
![grafana1](https://user-images.githubusercontent.com/22865538/57604907-fa380e80-7597-11e9-99ba-fd9d67bfaf05.png)

Case 2: 2 queries (count columns merged)
![Grafana](https://user-images.githubusercontent.com/22865538/57598167-bab3f700-7584-11e9-9b9e-7caf28bd51bf.png)

I initially thought that this was a duplicate of #4709 but I realised as there isn't a `field` property for the Metric `Count`, hence I'm still experiencing the same problem as reflected in that issue.

**What would you like to be added**:
To be able to have multiple columns of `Count` in table, where the different `Count's` are from different queries.

**Why is this needed**:
If this is supported for other Metrics such as `Sum`, `Average`, `Max`, I feel that it should be supported for `Count` as well.

Thanks,
Deborah

**Comment by aocenas** [comment]
I think this should be possible to do with transformation at this moment and also the default merging behavior changed for tables, needs to be checked.

**Comment by aocenas** [comment]
Seems like the new behavior should fix this, by default you see a selector in the table to show one of the queries and then you can use a merge transform to put it into single table with two `Count` columns.
