### ISSUE TITLE
2.0b2 - Don't throw the 'unsaved changes' dialog for a user with viewer role

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1703]
A user with the viewer role is not allowed to save dashboard changes and therefore does not need to be informed about 'unsaved changes' since he can't save anyway.  Request is to not throw this 'unsaved changes' dialog to users with the viewer role.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master, you can find hourly pre releases of next beta release here:
http://grafana.org/download/builds
