### ISSUE TITLE
6.2.0-beta1 Azure Monitor Data Source - Application Insights UI does not show

### ISSUE THREAD

**Issue by JamesHealey94** [grafana/grafana#17040]
**What happened**:

Updated to 6.2.0-beta1

Created panel with Azure Monitor data source

**What you expected to happen**:

Application Insights UI available

**Comment by JamesHealey94** [comment]
![image](https://user-images.githubusercontent.com/633125/57639797-9833d500-75a8-11e9-8f07-a471e1c01e62.png)

**Comment by marefr** [comment]
@JamesHealey94 what version did you upgrade from? Any errors logged in the console (use chrome developer tools for example)?

**Comment by daniellee** [comment]
Confirmed. Think I messed up an ng-show when adding multiple subscription report. Fix on the way.
