### ISSUE TITLE
Proof Key for Code Exchange: PKCE Challenge in Authorization_Code flow

### ISSUE THREAD

**Issue by RoopGuron** [grafana/grafana#17046]
**What would you like to be added**:
PKCE challenge for authorization_code flow for auth.generic

**Why is this needed**:
Certain Identity Managers like OKTA use the PKCE challenge in Authorization_Code flow in place of Client_Secret for Single Page Applications.
  We need to set up a SSO with OKTA for Grafana 'Single page react app' deployment.

**Comment by DanCech** [comment]
What is the specific problem you're trying to solve?  You should not be using the same oauth client id between your Grafana instance and a separate react app.

**Comment by RoopGuron** [comment]
Dan, 
 I have edited the description. Grafana is being referred to as the Single page react App.

**Comment by DanCech** [comment]
To set up Okta with Grafana you should use the instructions here: https://grafana.com/docs/auth/generic-oauth/#set-up-oauth2-with-okta and configure it as a standard web application.

The login flow goes through the Grafana server, it is not handled client-side which is what the "single page app" Okta profile is for.

**Comment by RoopGuron** [comment]
Dan Thanks for the Clarification.

**Comment by VictorioBerra** [comment]
Auth-Code + PKCE is not just for SPA applications. Works great even for clients that can be trusted with a secret. Its simpler than hybrid flow.
