### ISSUE TITLE
Alerting: Support $__range in queries used by alerting 

### ISSUE THREAD

**Issue by alastairs** [grafana/grafana#17058]
**What happened**:
I created an alert on the following Prometheus query:
```prometheus
sum(rate(
    http_request_duration_seconds_sum{controller="MyController", kubernetes_namespace="production"}[$__range]))
/
sum(rate(
    http_request_duration_seconds_count{controller="MyController", kubernetes_namespace="production"}[$__range]))
```

The alert is set to trigger when the median of this query over the last 5 minutes exceeds 0.5. The state history indicates that it has been alerting since 30 April, with the error `Error: tsdb.HandleRequest() error bad_response: bad response code 400`. However, looking at the query in Chrome DevTools, I see that the query actually returns 200 OK. 

**What you expected to happen**:
The alert is triggered as defined. Server-side errors are successfully recovered. 

**How to reproduce it (as minimally and precisely as possible)**:
Hopefully the above steps serve as sufficient reproduction.

**Anything else we need to know?**:
I've compared with the existing (closed) issues featuring this error message #8944 and #10321, and my situation does not match them. 

**Environment**:
- Grafana version: 6.1.6 (cf9cb45)
- Data source type & version: Prometheus 2.8.0
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 10, Chrome 74
- Grafana plugins: Kubernetes, Azure Monitor.
- Others: N/A

**Comment by torkelo** [comment]
And if you use Test Rule, what is the result?

**Comment by alastairs** [comment]
Thanks @torkelo. Same as with the alert in general:

```
Object
  firing:true
  state:""
  conditionEvals:" = true"
  timeMs:"96.754ms"
  error:"tsdb.HandleRequest() error bad_response: bad response code 400"
```

**Comment by torkelo** [comment]
and what is your alert rule & query config (especially time range and panel min interval / datasource min interval)

**Comment by alastairs** [comment]
Sorry, I'm not entirely sure which numbers you mean. This is the alert rule:

![image](https://user-images.githubusercontent.com/52957/57701470-f8338580-7653-11e9-998f-2e215907a473.png)

The dashboard is set to "Last 24 hours Refresh every 1m". The query is configured as follows:

![image](https://user-images.githubusercontent.com/52957/57701636-506a8780-7654-11e9-98c9-8a4600944a15.png)

And the panel as a whole has no time overrides set (min time interval: 0, relative time: <blank>, time shift: <blank>)

**Comment by torkelo** [comment]
what's the value for min interval in the panel metrics tab (bottom) or the your data source settings page

**Comment by alastairs** [comment]
Do you mean "Min time interval" on the panel? That's blank, per my last comment. The data source has a "scrape interval" set to blank too, although I see this is recommended to be set to the Prometheus global scrape interval value, which is 1m on our server. I think it's currently defaulting to 15s based on the placeholder value in the input field.

**Comment by torkelo** [comment]
Try setting this to 1m (in datasource settings). 

Also can you try and remove $__range from you query and hard code this to 5m or 1m instead to see if that makes a difference?

**Comment by alastairs** [comment]
Thanks @torkelo. 
> Try setting this to 1m (in datasource settings).

Per my previous comment:
> Update: changing the scrape interval to 1m on the data source didn't change anything on the alert.

However...
> can you try and remove $__range from you query and hard code this to 5m or 1m instead to see if that makes a difference?

This did fix it; I now see the following output:
```
Object
  firing:false
  state:"ok"
  conditionEvals:"false = false"
  timeMs:"103.827ms"
  logs:Array[2]
    0:Object
      message:"Condition[0]: Query Result"
      data:Array[1]
    1:Object
      message:"Condition[0]: Eval: false, Metric: Average (mean), Value: 0.288"
      data:null
```

Please could you elaborate a bit further about why that made a difference?

**Comment by aocenas** [comment]
@torkelo from what I understand this is more of a general alerting issue that these variables does not work there right? Like what would the $_range be in the context of the alerting?

Changing this to alerting label and platform project, let me know if that's right or not.

**Comment by AlexGustafsson** [comment]
@aocenas Would it make sense to support specifying values for `$__range` and `$__interval` under the alert pane? That way one can still use the variables for the graphs when viewed on a dashboard, but have them behave the intended way when they're used in an alert. Also, this might be somewhat out of scope for this issue, but until variables are supported for alerts - is there any way we could receive better error messages? Right now I get an error like `tsdb.HandleRequest() error bad_data: 1:29: parse error: missing unit character in duration` which I assume has to do with the variable not being substituted to anything meaningful before Prometheus received the query.

**Comment by marefr** [comment]
@aocenas you would have to "generate" the `$_range` in the backend. Similar to how `$_interval` and `$_interval_ms` is supported for elasticsearch or influxdb as examples

https://github.com/grafana/grafana/blob/298ff3ea012f1e3a0e999aed5186920d3ed0dd8e/pkg/tsdb/elasticsearch/client/client.go#L144-L146
https://github.com/grafana/grafana/blob/298ff3ea012f1e3a0e999aed5186920d3ed0dd8e/pkg/tsdb/influxdb/query.go#L36-L37

This has to be done for Prometheus explicitly since it's in the context of Prometheus you know the format of the query model and what variables it supports. I would argue this is a Prometheus issue
