### ISSUE TITLE
2.0b1 - Annotation datasource selection error

### ISSUE THREAD

**Issue by greglook** [grafana/grafana#1705]
I've been testing out the latest Grafana release and it seems like the annotations dropdown is broken. When I try to add an annotation the select field does not show any entries, and a JS error pops up in the browser console:

![screen shot 2015-04-02 at 12 25 52](https://cloud.githubusercontent.com/assets/3128434/6972009/a357b1ea-d935-11e4-9829-65ccc8b8db8b.png)

![screen shot 2015-04-02 at 12 26 02](https://cloud.githubusercontent.com/assets/3128434/6972014/a8f0d2da-d935-11e4-91b2-4f3b4b9c5106.png)

I currently only have an InfluxDB 0.9.x data source defined, and it's set as the default.

**Comment by greglook** [comment]
More info - this occurs on all of the following browsers:
- Chrome 41.0.2272.89 (original report)
- Firefox 36.04
- Safari 7.1.4

**Comment by torkelo** [comment]
@greglook sorry, InfluxDB support is very experimental and far from complete at this point, hope to get to work on it more soon as InfluxDB 0.9 matures and gets closer to release. 

Please submit feedback to the InfluxDB 0.9 issue: https://github.com/grafana/grafana/issues/1525
