### ISSUE TITLE
Zabbix server plugin is not supporting to grafana 6.1 and not able to configure zabbix server.

### ISSUE THREAD

**Issue by NitishRayar** [grafana/grafana#17056]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you will need to provide more information, what is not working, any errors? what's you setup, config, logs (browser & server)

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
