### ISSUE TITLE
Unable to Save Dashboard which contain Text Panel in html mode with <script> tag

### ISSUE THREAD

**Issue by fatima-rashid-confiz** [grafana/grafana#17053]
I'm unable to save and share the dashboard which contain Text Panel in html mode with <script> tag. Not even able to remove that panel. Also can't revert to older versions as well. Nothing happens when I clicks on these controls.

In one dashboard (say dashboardA), I added a text panel and added javascript in it (enabled disable_sanitize_html in default.ini), Since then this issue is happening. This issue even happen on other dashboards when i open them right after try saving the dashboardA. However after reloading the other dashboard, save works for them (not for dashboardA).

When I inspected, I found the following error:
react-dom.production.min.js:21 Uncaught TypeError: r.modal is not a function
    at t.c.<computed> (angular-strap.js:191)
    at e.showModal (util_srv.ts:67)
    at s.emit (index.js:150)
    at e.emit (actions.ts:34)
    at l.n.appEvent (GrafanaCtrl.ts:246)
    at e.showSaveModal (editor_ctrl.ts:22)
    at e.saveDashboard (DataSourcePicker.tsx:19)
    at n.onSave (index.ts:1)
    at Object.<anonymous> (react-dom.production.min.js:14)
    at f (react-dom.production.min.js:15)

Grafana version: 6.2.0-beta1 and 6.1.6
Data source type: MSSQL
OS Grafana is installed on: Windows
Browser: Chrome

**Comment by torkelo** [comment]
no other reports, must be something in you javascript you added in the text panel. What does that javascript look like?

**Comment by fatima-rashid-confiz** [comment]
Its quite simple 
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body >
    <button onclick="myFunction()">Click me</button>
    <p id="demo"></p>
    <p id="result"></p>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>

**Comment by torkelo** [comment]
Why add jquery?

**Comment by fatima-rashid-confiz** [comment]
I added this to make ajax call, isn't it supported?

**Comment by fatima-rashid-confiz** [comment]
i removed jquery and used XMLHttpRequest instead, now its working

**Comment by fatima-rashid-confiz** [comment]
Is there any future plans to support jquery or bootsrap in text panel? I think it caused conflict with grafana jquery and bootstrap files and thats why not didn't worked.

**Comment by fatima-rashid-confiz** [comment]
Interestingly when i add bootstrap link (  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script> )
 along with jquery, it work fine.
