### ISSUE TITLE
Job name is displayed in the alert message

### ISSUE THREAD

**Issue by SteveYf** [grafana/grafana#17051]
I am currently monitoring some apis with prometheus and grafana，There is a job in the PromQL data format. Is there any way to have the job name appear in the alert message?  In DingDing, it would be better if you could send different alerts to different people.  I checked the documentation and it seems that I have not found the relevant configuration I mentioned. Can anyone help me? Thanks.

**Comment by xlson** [comment]
I would like to direct you to our [community site](https://community.grafana.com/) where we try to answer general questions about how to use Grafana. Issues are mainly for bugs and feature requests.
