### ISSUE TITLE
Docs feedback: http_api/org.md

### ISSUE THREAD

**Issue by danlindow** [grafana/grafana#17067]
Section: Add User in Organization
```
POST /api/orgs/1/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "loginOrEmail":"user",
  "role":"Viewer"
}
```
loginOrEmail should be "LoginOrEmail"

current error when interacting with the API:
```
[{"fieldNames":["LoginOrEmail"],"classification":"RequiredError","message":"Required"}]
```

**Comment by danlindow** [comment]
I believe the API still takes it either way, its just a naming discrepancy between the docs and the API response.

**Comment by torkelo** [comment]
No lowercase `loginOrEmail` is correct, 
This is what the UI sends 

```
{"name":"asdasd","role":"Editor","loginOrEmail":"user2"}
```

The validation error sadly always uses the go model capital names.
