### ISSUE TITLE
2.0b2 - Custom height displays incorrectly until you save and refresh dashboard

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1706]
Create a new row with height 100px and then add 4 panels, then adjust each to a custom height as indicated in the titles:
![image](https://cloud.githubusercontent.com/assets/917241/6973821/c8921b0a-d98d-11e4-92f1-a2c11e63f59b.png)

Observe the heights are incorrect for the 200px custom height.

Click save, and refresh the page (browser F5):
![image](https://cloud.githubusercontent.com/assets/917241/6973833/e2fd46ae-d98d-11e4-967f-a38176171a8c.png)

Observe it displays correctly.

If you add a graph with custom height of 200 (when default is 100) it looks like this:
![image](https://cloud.githubusercontent.com/assets/917241/6973894/7566b2f0-d98e-11e4-900d-5d50b1a060ed.png)

After a save and reload it then looks like this:
![image](https://cloud.githubusercontent.com/assets/917241/6973905/88476ea0-d98e-11e4-9818-358cf5e99923.png)

So while the end result is all good, if editing dashboards you can really confuse yourself!

**Comment by torkelo** [comment]
The custom height on individual panels is not really that useful right now, it was added more as a test to try to stack to panels on top of each other (with a high panel to the left).

Tried to replicate this, but failed:
![image](https://cloud.githubusercontent.com/assets/10999/6991929/a470ae4c-dab1-11e4-94e5-5a680caaf2fd.png)

**Comment by torkelo** [comment]
that is after no save/reload dashboard, what browser are you using?

**Comment by maddenca** [comment]
After your comment about not being able to reproduce I checked my dashboards and noticed the row has a height of ###px whereas the panels is simply an empty field in which I had put ###.  Once I edited to ###px and closed the panel it resized correctly in dashboard view.  So it seems like the evaluation of this field is different on full page load vs. load after panel edit.  After seeing this I also put other values (like 'a') and noticed they were accepted even though that would effectively remove the panel contents after a F5 refresh.  So maybe the fix here is to put a validation check on the field, or make it a drop down, or validation check for digits + adding 'px' if the user forgets.

P.S.  You mentioned the feature wasn't very useful yet but I disagree!  In some dashboards I make use of a lot of rows, with many panels inside each, that are default minimized.  You then open the ones you want as you need them.  And sometimes in some row I want a mix of singlestat and graphs with different heights and utilize this feature.

Here's is an example:
![image](https://cloud.githubusercontent.com/assets/917241/6998020/7a0419fa-dbd3-11e4-87ab-b28a15935755.png)

**Comment by torkelo** [comment]
I see your use case now :) I hope to improve the grid system in the future (with drag handles to set height, better alignment options to get panels to align with the same height etc)
