### ISSUE TITLE
Too much escaping when typing in a variable input

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#17060]
**What happened**:

I've a dashboard variable which is populated by a prometheus query.

**What you expected to happen**:

If I were to not choose an item of the list and type a regexp like input, the var value used in the query has too much escaping, e.g. :

Dashboard URL generated by typing `prometheus-.*` in the k8spod var:
```
/d/b8cThx0mk/k8s-pods-thanos?orgId=1&...&var-k8spod=prometheus-.*&...
```
Prometheus query in dashboard
```
sum(
  label_replace(
    container_memory_usage_bytes{env=~"$k8senv",k8s_cluster=~"$k8scluster",namespace=~"$k8snamespace",instance=~"(?i:$k8snode)",container_name!~"(|POD)",pod_name!~"(|POD)",pod_name=~"($k8spod)(-[0-9a-f]{7,10})?-([a-z0-9]{5})"},
    "pod_name",
    "$1",
    "pod_name",
    "([a-zA-Z0-9-]+?)(-[0-9a-f]{7,10})?-([a-z0-9]{5})"
  )
) by (pod_name)
```
API url decoded:
```
api/datasources/proxy/61/api/v1/query_range?query=sum(
  label_replace(
    container_memory_usage_bytes{env=~"infra",k8s_cluster=~"k8s2-euw-infra",namespace=~"monitoring",instance=~"(?i:.+)",container_name!~"(|POD)",pod_name!~"(|POD)",pod_name=~"(prometheus-\\.\\*)(-[0-9a-f]{7,10})?-([a-z0-9]{5})"},
    "pod_name",
    "$1",
    "pod_name",
    "([a-zA-Z0-9-]+?)(-[0-9a-f]{7,10})?-([a-z0-9]{5})"
  )
) by (pod_name)&start=1557749640&end=1557836040&step=120&timeout=15s
```

Note the `prometheus-\\.\\*` instead of `prometheus-.*`

Using `${k8spod:raw}` fixes this problem but then it does not work anymore when I'm only selecting items in the var list because `pod_name=~"(prometheus-123456)(-[0-9a-f]{7,10})?-([a-z0-9]{5})"}` becomes `pod_name=~"({prometheus-123456})(-[0-9a-f]{7,10})?-([a-z0-9]{5})"}`.

**Environment**:
- Grafana version: 6.1.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
You need to use :${varname:raw} syntax if you want to use regex inside the variable value. There is no way for Grafana to know when to escape or not to escape. It needs to escape otherwise label values like "my\prom" would not work as the backslash would need to be escaped.

**Comment by marefr** [comment]
Tried to create a dashboard to reproduce this [here](https://play.grafana.org/d/S4rvqjiZz/17060-prometheus-query-variable-manual-regex-input?orgId=1) which runs v6.2 beta1 but there it works as expected. So either this only happen with a really advanced query like you're using or else this have been fixed after v6.1.3. 

Possible for you to try the dashboard in my demo in v6.1.3 and/or later version?

**Comment by marefr** [comment]
@torkelo he have tried the raw-syntax but then it doesn't work when selecting a single pre-existing value. See my demo link - is it a bug in 6.2-beta1 then since it not escaping?

**Comment by marefr** [comment]
@sylr now I got some more information. If you have a variable with multi values enabled (which I suppose you have) Torkel's comment regarding "you need to use `${varname:raw}` syntax if you want to use regex inside the variable value" applies. My demo dashboard uses a variable without multi value then no escaping are done so it seems like that would work, but if you have a variable value with a special character that requires regex escape the regex will fail. 

It's sort of a chicken or egg problem that we currently don't have any good solution for.

**Comment by sylr** [comment]
Indeed my vars are using multi-values.
