### ISSUE TITLE
2.0b1 - unsaved_changes_warning missing

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#1707]
Previously in 1.9.1 I was able to edit unsaved_changes_warning to false within config.js to disable the save prompts and, "Are you sure" questions that happens throughout the site.  Currently I am using scripted dashboards and becomes fairly annoying to users while closing tabs.

This may be somewhat related to #1686 as the setting was also set within the config.js.

As a side enhancement it may be useful to have this setting on a per dashboard option within the json instead of globally set.

**Comment by torkelo** [comment]
Pushed some enhancements to unsaved changes, they are now ignored for scripted dashboards, json file based dashboards, snapshots (and if user role is viewer)

**Comment by gerrickw** [comment]
Great I'll test it out on the next deb, thanks Torkelo!

**Comment by gerrickw** [comment]
This works great now.  Thanks!
