### ISSUE TITLE
plugin install

### ISSUE THREAD

**Issue by NitishRayar** [grafana/grafana#17078]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Please update issue title and description with information, I will reopen it when we know what this issue is about :)
