### ISSUE TITLE
bra run not working

### ISSUE THREAD

**Issue by NitishRayar** [grafana/grafana#17077]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Do you get any errors? Just tested latest bra with latest Go release and works fine.
