### ISSUE TITLE
InfluxDB query editor always adds double quotes around field name

### ISSUE THREAD

**Issue by dpslavov** [grafana/grafana#17074]
InfluxDB query editor always adds double quotes around field name, even if it's a regular expression.

**What happened**:
![Capture](https://user-images.githubusercontent.com/3389600/57728140-d5c55a80-769b-11e9-845e-d778360b9378.PNG)
![Capture2](https://user-images.githubusercontent.com/3389600/57728141-d5c55a80-769b-11e9-885e-b30a7e1134c0.PNG)

**What you expected to happen**:
No double quotes around the regular expression.

**How to reproduce it (as minimally and precisely as possible)**:
Add regular expression as field name.

**Anything else we need to know?**:
None.

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: InfluxDB 1.7.6
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome 74
- Grafana plugins: none
- Others: none

**Comment by torkelo** [comment]
Yes Grafana need to do this to support field with regex characters, otherwise they would generate errors. 

If you need to use regex in your field value you need to switch to text editor mode. 

related to this issue: https://github.com/grafana/grafana/issues/6754
