### ISSUE TITLE
Explore: Click on prometheus table result to filter does nothing

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#17071]
**What happened**:

Tried to filter a prometheus query by clicking on a table cell.

**What you expected to happen**:

Clicked label to be added to the query.

**How to reproduce it (as minimally and precisely as possible)**:

0. Prom datasource in Explore
1. query `up`
2. Click on a label value in the result table.

Result: query is not changed.

**Anything else we need to know?**:

This used to work.

**Comment by torkelo** [comment]
Can you test on play as well so we know if it affects 6.2 beta as well

**Comment by torkelo** [comment]
This seems to impact 6.2 as well so adding this to 6.2 stable milestone
