### ISSUE TITLE
Unable to create React panel plugin after new version of Grafana

### ISSUE THREAD

**Issue by vrunda-thacker** [grafana/grafana#17080]
I tried using the react-plugins-examples, while the panel does get registered and I can see it in the visualizations, but when I select it, I get the error as below:
Failed to import plugin module TypeError: c.ReactPanelPlugin is not a constructor
(After the change done to rename ReactPanelPlugin to PanelPlugin, when trying to import PanelPlugin from @grafan/ui, the intellisense says there is not exported member as PanelPlugin)

Please help.

- Grafana version: master and v6.2.0-beta1 
- @grafana/ui version - 6.0.1-alpha.0

**Comment by dprokop** [comment]
@vrunda-thacker thanks for reaching out. The interface is now renamed to `PanelPlugin` and we missed `react-plugins-example` update, sorry about that! I'm gonna push an update soon.

**Comment by torkelo** [comment]
yes, and we need to push an update for @grafana/ui as well

**Comment by WaleedNaveed** [comment]
@torkelo are you done with required updates ? Actually, i am also having the same issue.
The versions which i am using are:

Grafana Version: 6.3.5
Grafana ToolKit: @grafana/toolkit@6.4.0-alpha.2
Grafana UI: @grafana/ui@6.3.2

When i build the plugin i get the error :  TS2305: Module '"../node_modules/@grafana/ui"' has no exported member 'PanelPlugin'.

Any help would be much appreciated.
