### ISSUE TITLE
Docs feedback: features/datasources/azuremonitor.md

### ISSUE THREAD

**Issue by DeeGeeGit** [grafana/grafana#17086]
In the documentation we talk about running the create-for-rbac command in azure shell, I think it'd also be nice to show the error message you get if you don't do that, along with the imho better fix of allocating the reader role against the object id.

This approach is described in the latter comments in this thread https://community.grafana.com/t/error-when-adding-azure-monitor-data-source/3732/2 

@daniellee in the thread you even mention adding it to the docs ;o)

**Comment by devdil** [comment]
@torkelo can I pick up this?

**Comment by marefr** [comment]
@devdil sure

**Comment by achatterjee-grafana** [comment]
@devdil, are you still planning on working on this issue? Thanks for any update!

**Comment by ssbrandt** [comment]
Hi. Is this issue up for grabs? If so, I'm up for tackling it.

**Comment by achatterjee-grafana** [comment]
@ssbrandt, it is yours! Thank you!

**Comment by joshhunt** [comment]
We've since reworked the documentation and we no longer include specific instructions for creating credentials, instead linking out to the Azure documentation for this.
