### ISSUE TITLE
YAxis Unit cannot be set in case of AWS/ApplicationELB metric

### ISSUE THREAD

**Issue by IstvanPeter** [grafana/grafana#17089]
**What happened**:
I created a chart for AWS/ApplicationELB -> Targetresponsetime.
In the Visualisation the Unit is "Seconds" by default and it cannot be changed.
The chart shows wrong values on the Yaxis.

![image](https://user-images.githubusercontent.com/37807551/57769284-c7178b80-770d-11e9-8991-2db158f6b1c8.png)

**What you expected to happen**:
I would be able to set other values e.g. : millisec or nanosec also.

**How to reproduce it (as minimally and precisely as possible)**:
Create a chart and set AWS/ApplicationELB metric.

![image](https://user-images.githubusercontent.com/37807551/57769390-0ba32700-770e-11e9-8a6e-6250e5cc03ca.png)

Try to set the "YAxis / Unit" to any other Unit value as seconds.

**Anything else we need to know?**:
If I try to update the unit in the Panel Json then the chart does not visible and after a refresh the "Seconds" unit is in the field again.

**Environment**:
- Grafana version: 6.1.6 (cf9cb45)
- Data source type & version: AWS/Cloudwatch
- OS Grafana is installed on: AWS ECS AMI (docker)
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: None on the Dashboard
- Others: -

**Comment by torkelo** [comment]
The unit is from AWS Cloudwatch api and currently there no way to override it, releated to this issue https://github.com/grafana/grafana/issues/13733
