### ISSUE TITLE
Grafana graphs extremely slow for long time periods even on 1.9.1

### ISSUE THREAD

**Issue by philovivero** [grafana/grafana#1708]
I'm getting extremely poor performance (10-20 seconds/graph) when doing large time periods (24-48 hours). It feels exactly like when I was running old pre-0.9.12 versions without the maxDataPoints fix. I'm definitely running Grafana 1.9.1.

```
[root@mach100 05:09:32 /var/www/html/grafana-1.9.1] # head -1 app/app.js
/*! grafana - v1.9.1 - 2014-12-29
```

If I choose a 36-hour view, Firefox will pop up the "script is frozen, kill it?" dialog every time. Any clues for me how to proceed? Every issue/web page I find on this seems to indicate it was mostly solved in the 0.9.12 era, which doesn't help much.

**Comment by torkelo** [comment]
What version of graphite do you use, vanilla 0.9.12  does not contain maxDataPoints feature, that requires a manual patch, try upgrading to graphite 0.9.13  , you can also ope  chrome dev tools ,check network tab and verify that the graphite render calls send maxDataPoints

**Comment by torkelo** [comment]
the maxDataPoints parameters has been sent in every Grafana release (from v1.0), so it is most likely a problem with graphite not recognizing the parameter, or something that is causing the parameter to be sent to Graphite (no one else has reported issues with this though).

**Comment by philovivero** [comment]
Aha! Graphite, not Grafana versions. Sorry for the confusion.

```
ii  graphite-carbon                        0.9.12-3                            all          backend data caching and persistence daemon for Graphite
ii  graphite-web                           0.9.12+debian-3                     all          Enterprise Scalable Realtime Graphing
```

So I'm using Graphite 0.9.12 and need to upgrade to Graphite 0.9.13. Thank you so much for the clarification, and sorry for the noise.
