### ISSUE TITLE
Stretched out of proportion the Chart in Explorer

### ISSUE THREAD

**Issue by IstvanPeter** [grafana/grafana#17090]
**What happened**:
If I open a chart as "view" in explorer then lot of empty rows are at the top of the page.

**What you expected to happen**:
The chart is visible at the top of the page as in Chrome.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open a Dashboard in Explorer
2. Select "view" in a chart
3. Result: The half page is empty.

**Anything else we need to know?**:
- 
**Environment**:
- Grafana version: 6.1.6 (cf9cb45)
- Data source type & version: any chart
- OS Grafana is installed on: AWS ECS AMI (Docker)
- User OS & Browser: Windows 10 explorer and Edge
- Grafana plugins: - 
- Others: -

**Comment by torkelo** [comment]
Grafana does not support internet explorer (https://github.com/grafana/grafana/issues/15754)

What version of Edge did you test with, do you get the same in Edge?

**Comment by IstvanPeter** [comment]
No, in Edge is working as well.

**Comment by torkelo** [comment]
ok, closing this then
