### ISSUE TITLE
Graphite - alias family are reordered, breaking queries

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#17099]
**What happened**:

Using the graphite query editor, trying to use `aliasByTags` and then `sortByName`, `aliasByTags` is automatically put after `sortByName` and breaks the sorting. Needs to be fixed every time I edit the query.

**What you expected to happen**:

Grafana would respect the explicit ordering I give my functions

**How to reproduce it (as minimally and precisely as possible)**:

Add function `aliasByTags` to query. Then add `sortByName`. The query will be reordered. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.X
- Data source type & version: Graphite 1.1.X
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by shanson7** [comment]
Note, this can also break `groupBy*` queries that rely on the name format.

**Comment by xlson** [comment]
Thanks for reporting this.

**Comment by torkelo** [comment]
Fixed and fix coming in v6.3 (beta soon, stable in ~2 weeks)
