### ISSUE TITLE
Grafana alert for webhook

### ISSUE THREAD

**Issue by momoco530** [grafana/grafana#17104]
Hi
   I use webhook to alert
   send test is ok, but no data can be received after setting alarm thresholds
   "t=2019-05-16T11:53:20+0800 lvl=info msg="New state change" logger=alerting.resultHandler alertId=15 newState=alerting prev state=unknown"

**Comment by torkelo** [comment]
Did you add it to your alert rule? or check the "send on all alerts"? We have no other report that this is not working. Any more logs you can show?
