### ISSUE TITLE
Explore: Replacing a selected Prometheus label via typeahead adds extra " 

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#17108]
**What happened**:

Tried to replace a label value in the prometheus typeahead in Explore and when accepting a suggestion, an additional `"` was added.

**What you expected to happen**:

Keep the outside `"`, and don't add a third `"`.

**How to reproduce it (as minimally and precisely as possible)**:

0. Explore with prometheus
1. Write a query starting with `up{}` and add a label.
2. Try to change the label value by selecting only the `value` in `key="value"`, delete the value, and then accept a new suggestion.

Notice how an extra `"` was added.

**Anything else we need to know?**:

Could be related to #16213

**Comment by marefr** [comment]
Some additional information:
- Grafana version: 6.1.6
- Browser: Chrome

I cannot reproduce this issue on master (9bf577d), however there seems to be a different issue on master where auto complete between two quotes don't work.
