### ISSUE TITLE
Provide tooling to encrypt datasource secrets.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#17107]
Since we introduced password encryption for datasources without migrating all current datasources we need an easy way of migrating all current datasources for all our customers in our hosted services to use encrypted passwords. 

Right now I think the best solution for this is to add an operation to the CLI to invoke an update if needed. Having this operation in the CLI means we have access to the secret key that we need access to and we can reuse the functions used for encrypting that we already have in place. This migration should not be included in the normal flow due to reasons discussed in https://github.com/grafana/grafana/pull/16175 but we could enable operators to run this themselves.

This could be a database migration but right now I dont see any good reasons for not allowing the operator to run this multiple times. 

@torkelo I know you dislike DB access in the CLI but I think this is one of the advantages over regular scripts.

**Comment by xlson** [comment]
@bergquist Do we use the "add to changelog" label on issues?
