### ISSUE TITLE
Missing drilldown links on gauge panel

### ISSUE THREAD

**Issue by anumpatel** [grafana/grafana#17103]
**What happened**: Not able to see drilldown links on gauge panel

**What you expected to happen**: Expected to see drilldown links on gauge panel just like what we see on singlestat panel - a link icon and/or tooltip

**Anything else we need to know?**: Not sure, but maybe its because of ongoing migration from singelstat to gauge ? - https://grafana.com/docs/guides/whats-new-in-v6-0/#gauge-panel

**Environment**:
- Grafana version: v6.0.1
- Data source type & version: Elasticsearch
- User OS & Browser: Mac, Chrome

**Comment by torkelo** [comment]
yes, we have some features in the singlestat that have yet to be added to the gauge panel: https://github.com/grafana/grafana/issues/14554

**Comment by torkelo** [comment]
the link icon and tooltip is there but the whole panel does not become clickable with tooltip, only in header
