### ISSUE TITLE
[Alert] What is meaning of alert query(*,10s,now)? 

### ISSUE THREAD

**Issue by iowtis** [grafana/grafana#17106]
I have many queris A,B,C…,H.
I want to alert on these queries.
query(A,5m,now)
query(B,5m,now)
query(C,5m,now)
.
.
.
query(H,5m,now)

Is there anything can try the above expression?
ex) query(*,5m,now)

**Comment by torkelo** [comment]
you cannot use a wildcard, each query condition can only refer to one query
