### ISSUE TITLE
Singlestat - allow select which query to use

### ISSUE THREAD

**Issue by ceinmart** [grafana/grafana#17114]
Singlestat panel support to show a single item, that's ok , but the automatic restriction when have more than one queries become a problem.

Add a option to choose which query should be used/display 

I have a value to put in the dashboard , which is the our network link quality, but the data is % of loss, but for the users who will watch the dashboard that number could be not clarify, so I need to invert it , show the quality where 0% of loss should be 100% of quality (source = Zabbix). 
For that I'm using the MetaQueries to calculate the data (see the screenshot below) with "100 - A" , but for that I need to use two queries where I want to show the result of one them only...  

That can be easly solved if there is a option to select which query should be displayed, query A , B , ...

![image](https://user-images.githubusercontent.com/7062410/57853357-f389e100-77bb-11e9-810a-a68bcdd6a47b.png)

**Comment by torkelo** [comment]
I think this is a feature for the meta queries data source, a way to specify which query to return series for.

**Comment by ceinmart** [comment]
Hi @torkelo  , 

I forgot to mention , the error is : Multiple Series Error .
As far I understand, that occurs because was included two queries/metrics , isn't ? 
Because even if I add one more metric from Zabbix, this same error occur , so do not appear to be a specific problem for the meta queries data source. 
It's a Singlestat limitation. 

In the [documentation already mentioned this error](https://grafana.com/docs/features/panels/singlestat/#multiple-series-error) :  "Grafana 2.5 introduced stricter checking for multiple-series on singlestat panels."

**Comment by torkelo** [comment]
It is an error that only relates to having more than 1 series returned, so you should be able to hide one of the queries using the eye and it will work

**Comment by ceinmart** [comment]
This solution do not work with Meta Queries data source , because they objective is do an aritimetic value over other series/metric/query , if I disable the original series , they do not have data to calculate and  show, than nothing work. 
The eye button was made with very wrong concept, because it enable/disable the query, not hide/show . 
Should be have a enable/disable button and a hide/show button....
