### ISSUE TITLE
Alias for series from InfluxDB 0.9

### ISSUE THREAD

**Issue by mkabischev** [grafana/grafana#1711]
Hi. 

I'm migrating from grafana 1.9 to 2.0, it's really awesome, thank you. Also i've started experiments with storing data in InfluxDB 0.9 instead of graphite. When using graphite it's possible to make an alias for series by selected node. 
Can i do same with InfluxDB source? For example i have series ```queue_ack_rate``` with tags:
```json
{
    "queue" : "queue_name",
    "node" : "192.168.0.1"
}

{
    "queue" : "queue_name2",
    "node" : "192.168.0.1"
}
etc
```
And i want to have aliases "queue_name" and "queue_name2".

Also i have problems with query editor. After finish editing i reload page and see only "select metric" but query exists and works.

**Comment by torkelo** [comment]
The InfluxDB 0.9 support is very incomplete, please redirect feedback here, https://github.com/grafana/grafana/issues/1525  

I hope to work on 0.9 support more soon.
