### ISSUE TITLE
Create Grafana Dashboard via Python with json

### ISSUE THREAD

**Issue by martinwimpff** [grafana/grafana#17117]
I am trying to create a Grafana Dashboard via Python using json. I worked out how to add a Data Source via Python and now I want to do the same with dashboards.

`datasources_put = session.post(
   os.path.join(grafana_url, 'api', 'datasources'),
   json_data,
   headers={'content-type': 'application/json'})`
This works fine.

Now I tried this:
`dashboards_put = session.post(
   os.path.join(grafana_url, 'api', 'dashboards'),
   json_data,
   headers={'content-type': 'application/json'})`
which gave me the error code 404-Dashboard version not found.

The json_data is directly copied from a working Grafana Dashboard(using the UI).

**Comment by torkelo** [comment]
https://grafana.com/docs/http_api/dashboard/#create-update-dashboard
