### ISSUE TITLE
Explore: Use log label from stream when present

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#17122]
Loki will have server-based log-level extraction soon, which will add a `level` label to the streams. But the extraction logic is highly configurable, and may miss some level values for certain streams. If a stream has a `level` label, you can assume that extraction works. When the label is absent, we should run the level parser in Grafana.

**Comment by marefr** [comment]
If we only need to support Loki we can check if labels include a label named `level` when creating `LogRowModel` and if so, skip the parsing of log level and use the label value instead.
https://github.com/grafana/grafana/blob/9bf577d1257e6dbb910515211885492e710588af/public/app/core/logs_model.ts#L447

To support any datasource we need to also check if row has field named `level` and if so, skip the parsing of log level and use the column value instead.
