### ISSUE TITLE
Home dashboard has menu bar

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#17130]
When hovering over the Home dashboard title, the a bar shows up and blocks the title. I'm guessing this is for the menu. Do we need the menu? The bar looks like something is broken.

![Screenshot 2019-05-17 at 11 25 54](https://user-images.githubusercontent.com/859729/57918335-dece4b80-7896-11e9-90be-30c9dba69845.png)

**Comment by torkelo** [comment]
We need the panel header to move the panel and to trigger the panel menu, that the panel header is overlayed on top of the panel content is the compromise / solution for having panels without titles be able to utilize the full space. Not sure of a better alternative. Any ideas?

**Comment by torkelo** [comment]
Been thinking about showing something to the left of the panel menu caret down icon when there is not title (only on hover) as the caret down by itself looks strange

**Comment by torkelo** [comment]
One solution that I have not tested but wanted to test for about two years is to have a panel header bar shown absolutely positioned above the panel with space to grab and drag as well as quick action icons and menu icons. No idea how well that will work though

**Comment by mrwacky42** [comment]
Yes, Mr. Stale bot, this is still the case with Grafana 6.6.0
