### ISSUE TITLE
No color picker shown when clicking on legend in a pie chart

### ISSUE THREAD

**Issue by mydevnull** [grafana/grafana#17139]
**What happened**:

I clicked on a legend in a pie chart:

![no-color-picker](https://user-images.githubusercontent.com/12687098/57940560-b3e5f680-789a-11e9-857e-36c617e6fa61.png)

**What you expected to happen**:

I expected to see a color picker:

![color-picker-graph](https://user-images.githubusercontent.com/12687098/57940918-864d7d00-789b-11e9-8ca8-9ad98225312b.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create a pie chart with legend values, click the color line in the legend

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana Enterprise v6.1.6 (cf9cb45)
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser: Windows (Chrome), MacOS (Safari)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Are you running latest version of pie chart

**Comment by mydevnull** [comment]
The version I'm using is 1.3.0 (the latest is 1.3.3 I believe)

**Comment by torkelo** [comment]
Ok, then please upgrade:)
