### ISSUE TITLE
Histrogram draw error - ignoring x-max

### ISSUE THREAD

**Issue by v1dlak** [grafana/grafana#17141]
**What happened**:
Historgram ignores x-max value in graph.

**What you expected to happen**:
X-max is max value in x axis of graph.

**How to reproduce it (as minimally and precisely as possible)**:
Set x-min and x-max and minimal bucket size
![Screenshot(21)](https://user-images.githubusercontent.com/15999901/57946006-95ecb600-78db-11e9-96ab-7aa974bf4917.png)

**Environment**:
- Grafana version:6.1.6
- Data source type & version: Trickster1.0-beta5,Thanos0.4.0,Prometheus2.9.2 (same values)
- OS Grafana is installed on:Docker image from dockerhub
- User OS & Browser:Linux Mint 19.1, Firefox66.0.2, Chromium73.0.3683.86
- Grafana plugins:camptocamp-prometheus-alertmanager-datasource,grafana-kubernetes-app,grafana-piechart-panel
- Others:

**Comment by leeoniya** [comment]
this works correctly in the Histogram panel
