### ISSUE TITLE
HTML formatting in singlestat prefix/postfix fields

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#17146]
**What happened**:
Grafana 6.1.6 and previous versions allowed the use of HTML in the singlestat panel for prefix/postfix to modify text formatting. 6.2-beta2 breaks this functionality and breaks the layout.

**How to reproduce it (as minimally and precisely as possible)**:
Enter HTML in the postfix/prefix fields and include line break tags:
![image](https://user-images.githubusercontent.com/1184220/57957531-84fc6e80-78f4-11e9-8697-19740635fa8e.png)

**Environment**:
- Grafana version: 6.2-beta2
- Data source type & version: All
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10/Chrome 74

**Comment by ryantxu** [comment]
eeeep -- that is bound to break something

For the color, can you just use the color settings to change the color?

**Comment by bhozar** [comment]
Probably can use the colour settings, but haven't tried. The line break tag is really helpful though, otherwise I just get a very long box to fit the text in so it is readable.

**Comment by torkelo** [comment]
line breaks (<br>) is still working.  style attributes are not supported. Sorry if this is a minor breaking change.

**Comment by jonah-nestrick** [comment]
@torkelo The <br> tag doesn't seem to be working in 6.2.0. 

Grafana v6.2.0 (5d16da7)
<img width="309" alt="Screen Shot 2019-05-24 at 5 00 45 PM" src="https://user-images.githubusercontent.com/38331049/58361693-7f97aa80-7e45-11e9-8803-231edefeb43a.png">

**Comment by marefr** [comment]
@jonah-nestrick #17237
