### ISSUE TITLE
Bar gauge resets min/max when changing unit

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#17153]
**What happened**:

If you change the unit of a bar gauge after having configured min/max values they get reset to 0, 100.

**What you expected to happen**:

Leave my min/max alone.

**How to reproduce it (as minimally and precisely as possible)**:

Create a bar gauge, set min or max to something else than its default, change the unit.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.0-beta2
- Data source type & version: Prometheus 2.9.2
- OS Grafana is installed on: Ubuntu 18.04 (Docker)
- User OS & Browser: Arch Linux, Firefox 68.0a1
- Grafana plugins: Cloudflare, World Map, Alertmanager data source
- Others:

**Comment by dprokop** [comment]
@daenney thanks for reporting this. Unfortunately I couldn't reproduce this one. 

FYI, in #17174 I have changed the behaviour of options inputs in response to issue #17154 you have reported. In that work I also haven't seen the behaviour you report here.
