### ISSUE TITLE
Gauges and line graphs are fuzzy in Firefox

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#17152]
**What happened**:

If you look at gauges or bar graphs in Firefox the (out)lines are fuzzy/not well defined.

Firefox:
![grafana-firefox](https://user-images.githubusercontent.com/569574/57980623-5332f700-7a1d-11e9-9ff7-f51121d555c2.png)

Chrome:
![grafana-chrome](https://user-images.githubusercontent.com/569574/57980627-5b8b3200-7a1d-11e9-8c41-a7972a0eed5b.png)

**What you expected to happen**:

Not fuzzy/blocky outlines, but sharp like in Chrome.

**How to reproduce it (as minimally and precisely as possible)**:

Open up a graph in Firefox.

**Anything else we need to know?**:

I've observed this bug for ages in Grafana, so it's unrelated to the current Grafana or current browser version. I just never got around to filing a bug for it before.

**Environment**:
- Grafana version: 6.2.0-beta2
- Data source type & version: Prometheus 2.9.2
- OS Grafana is installed on: Ubuntu 18.04 (Docker)
- User OS & Browser: Arch Linux, Firefox 68.0a1
- Grafana plugins: Cloudflare, Alertmanager Data source, World map
- Others:

**Comment by torkelo** [comment]
Unable to replicate on Firefox on OSX or windows, so might be some rendering setting you have or specific thing for firefox on linux. Not sure Grafana can do anything here. Please experiment and report if you find anything more.

**Comment by daenney** [comment]
Sigh. I was afraid of that. Go ahead and close it. I'll see if I can trace anything and if I do file a bug with Mozilla instead.
