### ISSUE TITLE
2.0b2 - Greater than 26 or Z metrics are repeated

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#1715]
When adding greater than 26 metrics, the 27th+ will repeat based on the last metric.  The repeated metrics will be passed onto graphite when looking at the url params.  Looks like it previously repeated at O in 1.9.1. 

![repeated](https://cloud.githubusercontent.com/assets/656611/6991049/1de6ba56-da34-11e4-88ea-db23ca929094.png)

Hopefully not too much spam - JSON of panel to reproduce on play.grafana.org:
{
  "title": "no title (click here)",
  "error": false,
  "span": 12,
  "editable": true,
  "type": "graph",
  "id": 1,
  "datasource": null,
  "renderer": "flot",
  "x-axis": true,
  "y-axis": true,
  "y_formats": [
    "short",
    "short"
  ],
  "grid": {
    "leftLogBase": 1,
    "leftMax": null,
    "rightMax": null,
    "leftMin": null,
    "rightMin": null,
    "rightLogBase": 1,
    "threshold1": null,
    "threshold2": null,
    "threshold1Color": "rgba(216, 200, 27, 0.27)",
    "threshold2Color": "rgba(234, 112, 112, 0.22)"
  },
  "lines": true,
  "fill": 0,
  "linewidth": 1,
  "points": false,
  "pointradius": 5,
  "bars": false,
  "stack": false,
  "percentage": false,
  "legend": {
    "show": true,
    "values": false,
    "min": false,
    "max": false,
    "current": false,
    "total": false,
    "avg": false
  },
  "nullPointMode": "connected",
  "steppedLine": false,
  "tooltip": {
    "value_type": "cumulative",
    "shared": true
  },
  "timeFrom": null,
  "timeShift": null,
  "targets": [
    {
      "target": "alias(randomWalk('randomWalk'), '001')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '002')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '003')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '004')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '005')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '006')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '007')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '008')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '009')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '010')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '011')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '012')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '013')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '014')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '015')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '016')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '017')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '018')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '019')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '020')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '021')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '022')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '023')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '024')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '025')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '026')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '027')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '028')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '029')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '030')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '031')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '032')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '033')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '034')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '035')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '036')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '037')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '038')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '039')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '040')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '041')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '042')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '043')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '044')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '045')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '046')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '047')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '048')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '049')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '050')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '051')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '052')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '053')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '054')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '055')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '056')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '057')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '058')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '059')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '060')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '061')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '062')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '063')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '064')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '065')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '066')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '067')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '068')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '069')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '070')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '071')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '072')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '073')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '074')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '075')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '076')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '077')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '078')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '079')"
    },
    {
      "target": "alias(randomWalk('randomWalk'), '080')"
    }
  ],
  "aliasColors": {},
  "seriesOverrides": []
}

**Comment by torkelo** [comment]
Seems to be a graphite limitation or bug, get the same when using graphite native PNG rendering:
![image](https://cloud.githubusercontent.com/assets/10999/6991882/8b962f62-daae-11e4-96b4-063d266f6f65.png)

**Comment by gerrickw** [comment]
That is what I was attempting to mention, but looks like I failed to explain well.  If you look at the request that grafana is sending to graphite, it includes the alias of 80s so grafana is incorrectly sending the wrong values to graphite so graphite will of course send the same alias that grafana requested in the rendered image.

This should be re-opened.

**Comment by torkelo** [comment]
Sorry,  missed that part.

**Comment by torkelo** [comment]
I see the cause of this, A-Z naming of queries (using queries inside other queries feature for complex graphite queries). 

Just curious do you really have the need for more than 26 queries for a single graph? Is there not a better way to formulate your query using wildcars/glob expressions?

**Comment by gerrickw** [comment]
I do agree it is fairly silly to have so many individual metrics defined in one graph, so you could fix the problem by providing some hard cap limit or possibly adjustable later than repeating the last value.

Currently based on my current metric layout I do not see a good way.  Was hoping to use averageSeriesWithWildcards, but only works if you are wildcarding between two dots.  In my case I have colo.pool.row-column.metric.  Where I am attempting to graph a series of lines showing an average trend within one graph averaging all rows, so colo.pool.row_num-*.metric and a 2nd with colo.pool.*-column_num.metric.

Workarounds on my side I could separate colo.pool.rows.columns.metric, or create some aggregation rules.  If too complex on your side to allow more metrics within one graph I have other workarounds to go down.

Either way was a bit confusing when things started repeating so better to throw an error for a limit cap or adjustable for users somewhere.

Love the new 2.0 dashboard by the way.  Great job. :)

**Comment by gerrickw** [comment]
I am curious, is it  expected functionality to repeat the last metric sent to the server after 26?

**Comment by williamjoy** [comment]
I met same issue too,

**Comment by husseincoder** [comment]
I faced this issue as well

**Comment by jaimegago** [comment]
Still a problem with 4.x. @torkelo  IMHO if more than 26 targets is not supported properly (and I think we can agree that repeating the last ones is not proper support) then users should get an error message when trying to add a 24th target (instead of Googling and landing in this issue like I just did). I think this should be reopened as it'd be faire game for any users that hits this to see it as a bug.

**Comment by dmitrychait** [comment]
still exists in Grafana v5.4.2 (d812109) - why is this closed?
