### ISSUE TITLE
Update Lo-Dash to 4.17.11 or newer

### ISSUE THREAD

**Issue by dirkmueller** [grafana/grafana#17151]
**What happened**:

Running the Lighthouse scanner against a grafana 6.1.6 installation gives the high severity security warning about Lo-Dash.

**What you expected to happen**:

No warnings about lo-Dash.

**How to reproduce it (as minimally and precisely as possible)**:

See https://snyk.io/vuln/npm:lodash?lh=4.17.4&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

Please update to 4.17.11, 4.17.4 is not considered secure.

**Comment by marefr** [comment]
Already fixed in #16645 and will be included in v6.2 stable. Currently included in v6.2-beta.
