### ISSUE TITLE
X value in Tool tip for Histogram 

### ISSUE THREAD

**Issue by macd2** [grafana/grafana#17159]
**What would you like to be added**:
When using the X-Axis Mode histogram it would be very useful if there where an option to include the X value in the tooltip 

**Why is this needed**:
When having a dense X-Axis than its very hard to see which X-Value (Bucket) the current bar belongs to. 

![histo](https://user-images.githubusercontent.com/30157354/57986575-cb79d680-7a76-11e9-9dc9-fb9ff01a3680.png)

**Comment by vivekdsr** [comment]
+1

**Comment by ArcherThompson** [comment]
+1

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
