### ISSUE TITLE
Custom Graph Y-axes ticks

### ISSUE THREAD

**Issue by riobard** [grafana/grafana#17164]
**What would you like to be added**:

In Visualization[Graph]/Axes/Left Y and Right Y settings, add Y-Step setting (default to auto with current behavior). For example, with Y-Min=20, Y-Max=40, Y-axis would have three ticks at 20/30/40 with Y-Step=10, or five ticks at 20/25/30/35/40 with Y-Step-5, or eleven ticks at 20/22/24/26/28/30/32/34/36/38/40.

**Why is this needed**:

Custom stepping allows greater control of the granularity. For example, we might not care if the temperature is below or above 24 as long as it is within the range of 20~25. In this case, Y-Step=5 is better than Y-Step=2. In general, it's better to use coarsest step to reduce information overload.

**Comment by Robospecta** [comment]
Continuing discussion from #25171.

**What would you like to be added**:
I would like to be able to adjust the spacing between ticks for the y-axes in the options menu.
Additionally, I would also like the option to explicitly set the values for the y-axes, and for these to allow a custom mapping to a different label.

**Why is this needed**:
Allowing us to explicitly specify the tick spacing provides a higher degree of control over the granularity of our ticks and the subsequent density. Secondly, an option to map ticks explicitly is useful for when you want the labels of the ticks on the y-axes to differ from the underlying data. 

A good example of this is given in the images below, where our data source is providing forecast and measured data for wind direction. It's very useful to be able to map this into North, South, East, and West directions for display on the y-axes. I can imagine other scenarios where this might be useful to provide context for data making it easy to digest. An example of this might be graphing a performance metric, and mapping tick values onto labels Low, Fair, Good, Excellent or similar. You can also specify just the tick values as a comma separated list, without mapping them to different labels. Mapping is done currently using a comma separated list with each element in the list mapped using the text value=label. I imagine the look and feel of this could be improved on and I have a few ideas.

I have a working cut of this in Grafana v6. I would be happy to adapt and move this into v7 and submit a pull request. I also acknowledge there might be a better spot in the ui to situate the form inputs for this functionality, and a better way to lay this out.

Image 1: Explicit tick values mapped to different labels
![tick_size](https://user-images.githubusercontent.com/14093903/83096403-eef34a80-a0e8-11ea-8857-840874344b12.png)

Image 2: No explicit ticks mapped and no tick spacing
![tick_size2](https://user-images.githubusercontent.com/14093903/83096423-f87cb280-a0e8-11ea-9f22-38af7d3e7a77.png)

Image 3: No explicit ticks mapped but with tick spacing set
![tick_size3](https://user-images.githubusercontent.com/14093903/83096434-fe729380-a0e8-11ea-9e3e-1b586076adbd.png)

**Comment by jpmeijers** [comment]
I would also love to see this feature. Our use case is also wind direction.

**Comment by Nessworthy** [comment]
Adding a use case for this - AWS Elastic Beanstalk Elastic Search health values (0, 5, 10, 15, 20, 25, each denoting a health level)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
