### ISSUE TITLE
Grafana v6.1.6 no login in iframe

### ISSUE THREAD

**Issue by mboehm21** [grafana/grafana#17162]
Hi,

since we updated to Grafana v6.1.6 we are unable to login on our NOC-Screen which is using a static html-file where Grafana with its default webserver is embedded in an iframe.

After typing the credentials it says "Logged ln" but in the same moment we are redirected to the login page again.

How can we troubleshoot and solve this issue? Is this a bug in the new version?

**Comment by torkelo** [comment]
new security setting https://grafana.com/docs/installation/configuration/#allow-embedding

**Comment by mboehm21** [comment]
Hi, thanks for showing me the setting. I tried it but there is still no login possible. Same behaviour. What else can I try out?

**Comment by marefr** [comment]
@mboehm21 wrong security setting was referenced, however the allow embedding would be something that you'll need to configure as soon as you upgrade to Grafana v6.2 (not yet released).

The security setting in question is https://grafana.com/docs/installation/configuration/#cookie-samesite. You'll configure that to `none`, but be aware of the implications this may have on security.

**Comment by mboehm21** [comment]
cookie_samesite did the trick, thanks! I'll look into it regarding security.
