### ISSUE TITLE
Right Y-Axis stepping and ticks should match grid lines

### ISSUE THREAD

**Issue by riobard** [grafana/grafana#17165]
**What would you like to be added**:

Automatically calculated min/max values of right y-axis should be slightly adjusted so that the ticks and stepping matches the grid line (which is determined by left y-axis). For example in the following graph

<img width="721" alt="image" src="https://user-images.githubusercontent.com/22984/58008461-08010d00-7b1f-11e9-9fae-6bcf45399caf.png">

Left y-axis makes the grid 8 ticks, but right y-axis assumes 7 ticks. It's much better if right y-axis min/max is 40/75 or 45/80 (prefer the one with smaller delta from actual min/max) so it can match the grid line.

**Why is this needed**:

It's very difficult to read mismatched ticks and grid lines

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
