### ISSUE TITLE
Datasource UID

### ISSUE THREAD

**Issue by alter** [grafana/grafana#17163]
Hello,
**What would you like to be added**:
I think it would be a nice idea to add UID for datasources, like you already did it for dashboards.

**Why is this needed**:
B/c sometimes people may need to switch datasource name, but it's impossible if you have a lot of dashboards which use it.

**Comment by marefr** [comment]
Duplicate of #1664

**Comment by marefr** [comment]
This can be a solution to referenced issue, but please continue discussions in that issue.
