### ISSUE TITLE
Can create empty Dashboard Names →Infinite Redirects

### ISSUE THREAD

**Issue by sbrandtb** [grafana/grafana#17168]
**What happened**:

Create a dashboard with a non-empty name that is not sluggable. Easiest way and the only one I tried because I didn't want to DoS our Grafana instance: 🌈

It happily saves it, but when trying to access the page, the Browser creates an inifinite redirect loop between `https://grafana.example.com/d/abcdefghij` and  `https://grafana.example.com/d/abcdefghij/` (with trailing `/`) and the console is spammed with angularJS redirect messages.

I guess it is safe to say that empty Dashboard names might create strange behaviour in other places as well, see #7339

**What you expected to happen**:

Either that Grafana tells me this name is invalid or it just works.

**How to reproduce it (as minimally and precisely as possible)**:

Create a dashboard with name 🌈, store it and try to access it.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: irrelevant
- OS Grafana is installed on: Docker image
- User OS & Browser: Ubuntu/Firefox
- Grafana plugins: irrelevant

**Comment by jessabe** [comment]
Could not recreate this in version 7x. Going to close this for now, but if you are still having issues please let us know and we can re-open if needed! Thanks!
