### ISSUE TITLE
Qualys scan reports security issue with med level

### ISSUE THREAD

**Issue by maoyuanh** [grafana/grafana#17161]
What Grafana version are you using?
Grafana version 5.2.4

What datasource are you using?
Sqlite3

What OS are you running grafana on?
Redhat 7.5

The following security issue is reported during qualys scan:
Clickjacking - Framable Page

Threat
The web page can be framed. This means that clickjacking attacks against users are possible.
Impact
With clickjacking, an attacker can trick a victim user into clicking an invisible frame on the web page, thereby causing the victim to take an action they did not intend to take.
Solution
Common clickjacking prevention mechanisms include: X-Frame-Options: This is an HTTP response header that is used to prevent framing of the web page.Framekiller JavaScript code: Special JS code can be used to prevent a malicious user from framing the page. This method is less reliable than using X-Frame-Options.

Any plan to fix them?

**Comment by torkelo** [comment]
this is fixed in v6.2 (out in beta now and stable tomorrow)
https://github.com/grafana/grafana/issues/14189
