### ISSUE TITLE
Annotations: quick entry of annotation (notes about incidents)

### ISSUE THREAD

**Issue by jancolpaert** [grafana/grafana#1716]
Feature request:

Annotations are great, but seem to expect that an external source generates them in the database (InfluxDB in my case). We often need to add notes (stored as annotations) when looking at the graphs, in order to document various incidents that are visible in the graphs).
Such a note would need to relate to one or multiple (all) series visible in the dashboards (an incident often affects multiple data series, so adding a note to all individual series is not feasible).

One way of implementing could be to create a panel type for entry of note annotations, where the current zoom factor (time period) determines the start and end of the incident to which the note applies.

With this feature, the grafana tool could be a very graphical documentation channel for communication between members of an operational team. 

Maybe this feature already exists, but I do not see it in the documentation
Thanks for this impressive tool !

**Comment by torkelo** [comment]
Yes, this would be great, been wanting to implement this for a long time, just never had time. Already an issue for this though: #1286
