### ISSUE TITLE
Add support for bulk updates to users similar to UpsertUser 

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#17172]
**What would you like to be added**:
Function to `sqlstore` module which would allow bulk updates of users. It should take `[]*ExternalUserInfo` as argument, implement transaction (or do it one SQL request)

**Why is this needed**:
For active LDAP sync

**Comment by marefr** [comment]
Isn't this already supported by xorm? Or does this track the feature of adding bulk update for ldap sync, if so please update the title and add appropriate labels (ldap? admin/users?). Should this be in a project/milestone?

**Comment by markelog** [comment]
> Isn't this already supported by xorm?

I don't know, in any case we would need sqlstore to support it

> Or does this track the feature of adding bulk update for ldap sync

It it triggered by the active ldap sync feature, but it should be useful in other places as well

>  if so please update the title and add appropriate labels (ldap? admin/users?)

What kind of labels do you think would be appropriate here?

> Should this be in a project/milestone?

Currently, we haven't added projects or milestones to the tickets like this. Not sure about the projects, but 6.3 milestone should be sufficient it seems.

@xlson what do you think

**Comment by xlson** [comment]
@markelog I changed the title to make it a clearer what we are trying to accomplish.
