### ISSUE TITLE
Support changing plugin ids

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17186]
I am hoping to migrate some published plugins from an existing org (with id) to a new org, this will take some changes.

Everything that was:
*  https://grafana.com/plugins/ryantxu-annolist-panel
Should migrate to the internal
* now internal [annopanel](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/annolist/plugin.json)

To support this, I think we need to add:
```
 alias?: string[];
```
to https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/types/plugin.ts#L17

then something in `plugin_loader.ts` to check aliases if the initial id fails.

Out plugin system publishing system will also require changes

**Comment by sjoeboo** [comment]
+1 would like this, we've got a plugin we'd like to take over/re-publish:

"old" unsupported: https://grafana.com/grafana/plugins/udoprog-heroic-datasource

"new"/official we'd like to get published:

**Comment by rozetko** [comment]
hey @wbrowne @ryantxu!
are there any estimates on this?
would really like this feature
