### ISSUE TITLE
Docs feedback: installation/mac.md

### ISSUE THREAD

**Issue by kenjura** [grafana/grafana#17183]
This document should say where the public (static asset) folder is, namely:

- /usr/local/Cellar/grafana/(version)/share (if using Homebrew)

Also, the reference to "the root install directory" should be clarified, as nowhere in the document is it explained which folder is "the root install directory".

**Comment by marefr** [comment]
I think the root install directory sort of depends how you have configured home brew, see our [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/grafana.rb). If you have knowledge of this and/or would like to contribute changes we would love that. Thanks
