### ISSUE TITLE
html/template: "index" is undefined

### ISSUE THREAD

**Issue by alsonkemp** [grafana/grafana#1718]
I'm still having some trouble getting Grafana to run.  Using 2b2 in a Docker container on Debian Jessie and get the following on page load:

URL: http://x.y.z.a:33301/login

Body:

    html/template: "index" is undefined

Command line:

    # /opt/grafana/current/grafana --config /app/grafana.ini web    
    2015/04/07 01:16:42 [I] Starting Grafana
    2015/04/07 01:16:42 [I] Version: 2.0.0-beta2, Commit: 382f706, Build date: 2015-04-06 12:46:06 +0000 UTC
    2015/04/07 01:16:42 [I] Config: Loaded from /app/grafana.ini
    2015/04/07 01:16:42 [I] Database: sqlite3, ConnectionString: file:/opt/grafana/data/grafana.db?cache=shared&mode=rwc&_loc=Local
    2015/04/07 01:16:42 [I] Migrator: Starting DB migration
    2015/04/07 01:16:42 [I] Listen: http://0.0.0.0:33301

Any hints?

**Comment by torkelo** [comment]
the working when starting the binary must be /opt/grafana/current , https://github.com/grafana/grafana-docker/blob/master/Dockerfile

**Comment by jonyrock** [comment]
non-built frontend assets also can cause this

**Comment by vikbert** [comment]
apply `yarn install --pure-lockfile && ~/go/bin/bra run`, then go to `localhost:3000`, everything fine.
