### ISSUE TITLE
Grafana 2.0b1: Elasticsearch as data source for annotations

### ISSUE THREAD

**Issue by abravorus** [grafana/grafana#1719]
Hello,

Grafana 2.0 doesn't use Elasticsearch for storing of dashboards' configuration anymore.
Does it mean that Elasticseach could not be used now as a datasource for Annotations?
If so, it's a pitty, for us that was a very convinient way to combine time data from Graphite and events annotations from Elasticsearch.

Alexandr

**Comment by torkelo** [comment]
Of course you can use Elasticsearch for annotations, I hope to be able to use Elasticsearch for metrics and more in the future
