### ISSUE TITLE
Import from graphite to translate 'secondYAxis' function to right yaxis in Grafana

### ISSUE THREAD

**Issue by sanga** [grafana/grafana#172]
Small enhancement request. I just noticed that when importing from graphite metrics which have 'secondYAxis' are still plotted on the first y axis (and retain secondYAxis in their metric name). If you feel like this is an edgecase or is more complicated to implement than worth it, I would not complain about that.

**Comment by ecneladis** [comment]
+1

**Comment by lsiudut** [comment]
+1

**Comment by knowak** [comment]
+1

**Comment by zytek** [comment]
much graphite dashboards to import. such pain.
