### ISSUE TITLE
2.0b1 floatcharts error

### ISSUE THREAD

**Issue by kotopes** [grafana/grafana#1720]
flotcharts error Error: Invalid dimensions for plot, width = 0, height = 195
app.8ae07506.js:34

version latest (2.0.beta)
http://puts.sh/2015/04/07/367a08d20ebb67eec888366fe3039961.png

chrome 41.0.2272.118 m  (win 7x64) js 1.8.0.40

**Comment by torkelo** [comment]
its an error flot generates sometimes when the timing sizing elements is not complete, have not been able to get rid of this error completly, happens sometimes on window resize, but should not have any negative side effects.
