### ISSUE TITLE
Can we access raw data from grafana for alerting?

### ISSUE THREAD

**Issue by sacdpathade** [grafana/grafana#17215]
Can we get access to raw data imported from various data sources to create own custom alerts, given that Grafana alerts are not supporting variable based queries? We have azure based dashboards which expects to select resource group, then namespace and then actual resource to be monitored. Now, imagine creating dashboard with all,it will be very complex and won't be useful from monitoring perspective.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
