### ISSUE TITLE
AzureMonitor: Translate units from Azure Monitor response to Grafana units

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#17217]
The Azure Monitor REST API and the Application Insights API returns the metric's unit as metadata in their responses. This is not used at the moment. This should be translated to a Grafana unit and set automatically when the user chooses a metric.

This issue is ported from the now deprecated plugin repo: https://github.com/grafana/azure-monitor-datasource/issues/3

**Comment by secustor** [comment]
This is partly already implemented, but not fully. https://github.com/grafana/grafana/blob/master/pkg/tsdb/azuremonitor/azuremonitor-datasource.go#L410
Grafana has not a concept of cores and ByteSeconds. 

This issue imho should be re scoped to implementing this units in Grafana or be closed.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
