### ISSUE TITLE
SQL Friendly Variable Formatting in Interpolation

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#17210]
**What would you like to be added**:

Interpolating of the Variables  values which are easy to use in the SQL Query Generation

https://grafana.com/docs/reference/templating/

For multi-value selection in SQL we need a format  

 variable_name IN ("val1","val2")  

If multiple values are selected or

1

If one   have chosen "all" in the dropdown

**Why is this needed**:

This allow to get simple queries constructed which have both filter applied or not,  

I could write a query with something like   SELECT * FROM TBL WHERE  ${servers:sql}  which would   produce

SELECT * FROM TBL where server in  ("val1","val2") 

or 

SELECT *FROM TBL where 1

Which are both correctly formed SQL

**Comment by DanielGnzlzVll** [comment]
I like this feature,
I just want to clarify that it should not be the default interpolation method, since this would be a backward break.

this break back would occur in cases in which the variable does not represent all the values that the column may have and with this new interpolation no filter would be made.

**Comment by PeterZaitsev** [comment]
Of course.  The page I mentioned references multiple formatting choices, This could be one of them

Ie example:

servers = ['test1.', 'test2']
String to interpolate: '${servers:pipe}'
Interpolation result: 'test1.|test2'

**Comment by Lectem** [comment]
This would be a nice feature, I encountered the same problem where I would like to have a specific formatting or even request based on whether a filter is applied or the "ALL" value is chosen.
@PeterZaitsev Did you find a workaround ? I think it might be possible to define a hidden variable that does this.

**Comment by torkelo** [comment]
this is already implemented , for example https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#singlequote

**Comment by marefr** [comment]
No, I think you misunderstood. They want to be able to write a `where column in($value)`and if some values are selected for variable it should render `where column in('value 1', 'value 2')`, if "All" is selected though they want "`where 1=1` or similar to be rendered. Problem is if you have thousands of values and you select all values in variable the where column in(values) will A) render a huge query and B) perform bad

**Comment by ahlaw** [comment]
> EDIT: Easiest solution I found yet
> 
> value for ALL
> 
> ```
> null) OR (true
> ```
> 
> Which turns the following query part
> 
> ```
> WHERE value IN ($your_variable)
> ```
> 
> into
> 
> ```
> WHERE value IN (null) OR (true)
> ```

I tested the above workaround of setting `null) OR (true` as the custom ALL value, and it seems like a preferable approach since it doesn't modify the query outside of the variable during interpolation.

**Comment by baldm0mma** [comment]
Thanks @ahlaw and @Lectem for posting a workaround. Since this workaround functions as needed, I'm going to close this issue.
