### ISSUE TITLE
Dependent templates

### ISSUE THREAD

**Issue by juise** [grafana/grafana#1721]
Hi!

Will be great to have Grafana support dependent templates. I suggest to use dependent templates in the following manner by example: I have template $A and template $B; template $A contains the list of publishers and template $B contains the list of feeds. Relation between publishers and feeds is one-to-many (1-to-N), and between feeds and publishers is also one-to-many (1-to-N). So, when I select some value-A (e.g. publisher) from template $A, the selected value-A substitute into 'query' (maybe?) in template $B, and I automatically select all values-B (feeds) that contain or relate with (by example logically related, not only via metric name) value-A. And will be great to have the ability do it in reverse order. The value-B selects all related values-A.

**Comment by torkelo** [comment]
Isnt this exactly like what these dashboards do? 
Graphite example of nested template variables (template variables used inside another template variable query)
http://play.grafana.org/dashboard/db/templated-graphs-nested

InfluxDB example: 
http://play.grafana.org/dashboard/db/influxdb-templated-queries

**Comment by torkelo** [comment]
dependent template variables has been supported since Grafana v1.5 or 1.6 I think

**Comment by juise** [comment]
Hi @torkelo! It's awesome. Thanks a lot.
