### ISSUE TITLE
AzureMonitor: Can select multiple metrics in a query

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#17218]
Currently to select multiple metrics, the user has to make multiple queries. The AzureMonitor and App Insights API do not support wildcards so it is not possible to choose multiple metrics by using wildcards for metric namespace or resource group (or the other metadata fields) but Azure Monitor supports returning multiple metrics (if the resource group, metric definition and resource name are the same) and Application Insights supports returning multiple aggregations for the same metric (sum, avg etc.).

Ported from the now deprecated plugin repo: https://github.com/grafana/azure-monitor-datasource/issues/5

**Comment by jstaffans** [comment]
@joshhunt in which release was this issue fixed? I'm struggling to find a commit that would reference this issue.
