### ISSUE TITLE
AzureMonitor: Support for raw editor in azure monitor queries

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#17225]
**What would you like to be added**:

We would llike to see a raw editor for Azure monitor data type.  When toggle to raw mode, query should turn in to raw query something like
`/subscriptions/xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx/resourceGroups/MYRESOURCEGROUP/providers/Microsoft.EventHub/namespaces/MYRESOURCENAME/providers/microsoft.insights/metrics?aggregation=Total^&metricnames=ServerErrors`

**Why is this needed**:

When copy pasting the panels, my intention was just to change the resource name. But when we change the resource name, rest of the drop downs disspapear.

**Comment by daniellee** [comment]
We could absolutely show the raw query. I will get that into 6.3 - I have this PR which returns the raw query as meta data: https://github.com/grafana/grafana/pull/17198 so I can add this to the query editor.

As regards "But when we change the resource name, rest of the drop downs disspapear." I also find this annoying and I made an attempt to change it but it didn't work out and I reverted it: https://github.com/grafana/grafana/pull/17212

Think the solution might be to instead not clear the chained dropdowns if a template variable is chosen.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
