### ISSUE TITLE
AppInsights: Add a rename metric option

### ISSUE THREAD

**Issue by corneliutusnea** [grafana/grafana#17228]
Hi,
I'm trying to add to a graph two values of the same metric:
`request/count > avg` and `request/count > max`
But they both appear in the graph as `request/count`

I can't differentiate them and I can't use the Legend to set different colours for the two metrics.

Would be nice for the name of the metric in the graph to be reported as `request/count/avg` and `request/count/max` or have a way to rename them so I can apply different colours.

**Comment by espenrl** [comment]
I second this. The events are often technically named and the dashboards would look more professional with an alias.

**Comment by sunker** [comment]
Thanks for reporting this! We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics). I'm closing this issue now, but feel free to reopen if you feel the need to.
