### ISSUE TITLE
AzureMonitor: {{resourceName}} alias should not be just the last segment of the Azure Resource ID

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#17222]
The calculation of the {{resourceName}} alias should not be just the last segment of the Azure Resource ID. It should be the concatenation of every odd segment after providers/{providerName}.

For example, an Azure Resource ID will look as follows:

/subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}/providers/{providrrName}/{type1}/{name1}/{type2}/{name2}/...

The {resourceName} alias should be set to {name1}/{name2}/...

An example which illustrates this problem is metrics on Microsoft.storage/storageaccounts/blobservices. If you have multiple storage accounts, the {resourceName} alias will always be 'default' and you can't tell which storage account is which one.

If the Azure Resource ID is the following:

/subscriptions/{subscriptionId}/resourcegroups/{resourcegroup}/providers/microsoft.storage/storageaccounts/{storageaccountname}/blobservices/default

The {resourceName} alias should be {storageaccountname}/default

This issue is ported from the now deprecated plugin repo: https://github.com/grafana/azure-monitor-datasource/issues/30

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
