### ISSUE TITLE
Document LDAP config reload

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#17221]
**What would you like to be added**:
Recently, we landed dynamic LDAP config reload https://github.com/grafana/grafana/pull/15470.
But not yet documented it...
**Why is this needed**:
Add documentation... somewhere :)

**Comment by marefr** [comment]
@markelog Guess somewhere [here](https://grafana.com/docs/http_api/admin/#reload-provisioning-configurations) where reload of provisioning configs are documented?

**Comment by markelog** [comment]
Makes sense to me!

**Comment by marefr** [comment]
@markelog why closed?

**Comment by markelog** [comment]
Oh, missed the right button

**Comment by marefr** [comment]
I'm removing the assignees. General backend team will fix this.
