### ISSUE TITLE
AzureMonitor: Log analytics $__from and $__to macros doesn't honour time overrides

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#17224]
**What happened**:

In the log analytics query, we have $__from and $__to fields in a graph and set some time overrides in the query.  Instead of considering override time, log analytics macros considering dashboard level from and to timings.

**Environment**:
- Grafana version: any 6.x ( probably in earlier versions as well )
- Data source type & version: Azure monitor recent
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome

- Others:

Query with from and to macros

```
app('$AI_SearchAPI').exceptions
| make-series value=count() default=0
    on timestamp 
    from (datetime(1970-01-01) + $__from * 1ms)
    to (datetime(1970-01-01) + $__to * 1ms)
    step 1m    
    by operation_Name
| mv-expand timestamp to typeof(datetime), value to typeof(int)
| order by timestamp asc, operation_Name asc
```

Same query without the from and to macros

```
 app('$AI_SearchAPI').exceptions
| where $__timeFilter(timestamp)
| summarize count() by bin(timestamp,1m), operation_Name | order by timestamp asc;
```

Both resulting in different time range..

![image](https://user-images.githubusercontent.com/153843/58164210-4a406080-7c7d-11e9-9e1b-b154907ff192.png)

![image](https://user-images.githubusercontent.com/153843/58164432-bf139a80-7c7d-11e9-8fb6-be468693a544.png)

**Comment by marefr** [comment]
Is this possible a duplicate or a result of #16365?

**Comment by daniellee** [comment]
Duplicate and fix on the way.

**Comment by yesoreyeram** [comment]
this is not duplicate issue.  but related issues.
