### ISSUE TITLE
2.0-beta1 https protocol

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1722]
I'd like to use https, but with the grafana-provided web service not sure how to do that.

I see the "protocol" entry in the ini file, suggesting you can use http or https - changing it to https doesn't really work. And if it did, where's the cert set up?

Help document - http://docs.grafana.org/installation/configuration/ - leaves out the 'protocol' setting entirely. Is it not implemented yet?

Thanks,
Scott

**Comment by torkelo** [comment]
```
[server]
; protocol (http or https)
protocol = https
; the ip address to bind to, empty will bind to all interfaces
http_addr =
; the http port  to use
http_port = 443
; The public facing domain name used to access grafana from a browser
domain = localhost
; the full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/
router_logging = false
; the path relative to the binary where the static (html/js/css) files are placed
static_root_path = public
; enable gzip
enable_gzip = false
; https certs & key file
cert_file = /path/to/cert
cert_key = path/to/key
```

Will update the documentation, forgot these settings

**Comment by sknolin** [comment]
Fantastic, thanks!

Probably should also get added to the default ini files, as people look there first sometimes.
