### ISSUE TITLE
Singlestat garbled text 6.2.0

### ISSUE THREAD

**Issue by girishjk** [grafana/grafana#17237]
**What happened**: Upgrading from 6.1.6 to 6.2.0 renders the exact same data in singlestat panel unreadable. 

![6 2 0](https://user-images.githubusercontent.com/18491567/58196925-4c181d00-7c99-11e9-9b67-ce91cb5093c0.PNG)

**What you expected to happen**: Singlestat to show same text as 6.1.6:
![6 1 6](https://user-images.githubusercontent.com/18491567/58197007-65b96480-7c99-11e9-88f8-32fad12005f4.PNG)

**How to reproduce it (as minimally and precisely as possible)**: Create a small singlestat that shows normal text on multiple lines

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: influxdb
- OS Grafana is installed on: rhel6
- User OS & Browser: windows 7 / chrome 74
- Grafana plugins: NA
- Others: NA

**Comment by ThomasRunting** [comment]
I have the same

**Comment by torkelo** [comment]
thanks for reporting this! fix incoming
