### ISSUE TITLE
Multi-value variables are only partially interpolated in templated annotations queries

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#17234]
**What happened**:

I have configured an annotations query using the native Grafana datasource and a tag query that references a template variable like: `my-var:${var}`

If I select multiple values (X, Y) for the variable `var`. This is transformed into an annotations query with the following query params:

```
tags: my-var:X
tags: Y
```

**What you expected to happen**:

I expected the template expression to be interpolated for all selected values, e.g.:

```
tags: my-var:X
tags: my-var:Y
```

I am also interested in the what the expected behavior is when there are multiple variables, e.g. `my-var:${var1}:${var2}`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a multi-value template variable (any datasource).
2. Create an annotations query that references that template variable as a substring (see example).
3. Select multiple values for the template variable.

**Anything else we need to know?**:

This seems to be a consequence of the logic here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana/datasource.ts#L63-L72

which renders multi-value template variables joined with an arbitrary `__delimiter__` and then splits on that delimiter. But this leads to the above strange behavior if the template variable is part of a larger string expression.

**Environment**:
- Grafana version: v6.1.6 (cf9cb45)
- Data source type & version: Grafana (native annotations)
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: macOS 10.14.5, Safari 12.1.1
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
For multi-valued variables used in the annotation tags filter we only support a full tag value. so `my-var:${var}` won't work.
