### ISSUE TITLE
how to access dashboards stored in /app/dashboards/<some_folder>

### ISSUE THREAD

**Issue by raghvendra-iiita-work** [grafana/grafana#1723]
i am unable to access dashboards as localhost:5601/#/dashboard/file/some_folder/my_dash.json 

Is the url i am using correct for dashboards stored in a folder inside /app/dashboards/

**Comment by torkelo** [comment]
what version of grafana are you using?

**Comment by raghvendra-iiita-work** [comment]
its 1.6.0 as listed in package.json

**Comment by torkelo** [comment]
oh, that is a really old version, upgrade! :) 

But the path looks correct, check chrome dev tools (f12), network tab and inspect the request to fetch the json file, have not tried subpaths within the dashboard folder but that should work.

**Comment by raghvendra-iiita-work** [comment]
if anyone is able to do this please reply

**Comment by torkelo** [comment]
Did you look at the chrome dev tools? It would be helpful to know request the browser is sending. Do you get a "Not found" (404) from your web server?. Please give me more info so I can help.

**Comment by raghvendra-iiita-work** [comment]
yeah the request was going to /app/dashboards/some_folder?some_number

i think it should go to /app/dashboards/some_folder/my_dash.json?some_number

**Comment by raghvendra-iiita-work** [comment]
i found the way grafana currently uses . for / to access dashboards in subfolder 
resulting working url: localhost:5601/#/dashboard/file/some_folder.my_dash.json
