### ISSUE TITLE
BarGauge: Variable with multiple values

### ISSUE THREAD

**Issue by ulrichSchreiner** [grafana/grafana#17231]
hi,

i tried the new Bar Gauge and it looks great. When i have variables in my dashboard, i can reference the selected value. 

But if my varaible has an "All" option i expected the bar gauge to repeat over the variables. The only option i see is to repeat the panel, but this looks really ugly, as there are multiple panels and not one panel with multiple gauges.

it would be great if the bar gauge has an option to iterate over a variable which is defined in the dashboard.

**Comment by torkelo** [comment]
The BarGauge repeats for every series or field your query return, no need to repeat the whole panel. 

Just use your variable in such a way so that if you specify All the query returns many series

**Comment by ulrichSchreiner** [comment]
i tried it with a simple constant list. i can repeat the panel, but the gauge does not repeat

**Comment by torkelo** [comment]
does your query repeat multiple series? You need to use the variable in your query and your query needs to return multiple series (or fields)

**Comment by ulrichSchreiner** [comment]
hm, not sure if i understand you :-)

i have a variable "myserver" of type "Constant" with values "server1,server2,server3,server4" and enabled the "All" option.

in the gauge query i use the variable "$myserver" and this only works, if i select "server1" or "server2", but not if i select "All".

**Comment by torkelo** [comment]
Ok, but then it's unrelated to the gauge panel but your metric query? What TSDB are you using, what does your query look like? Does it support multi-valued variables?

**Comment by ulrichSchreiner** [comment]
ah, ok. i'm using prometheus and use the $myserver as a label-selector. i think this query does not support multie-valued variables.

i will take a deeper look into my query. thanks for the hint.

**Comment by torkelo** [comment]
use regex operator to support multiple values `label=~"$myvar"`
