### ISSUE TITLE
grafana 2.0b proxy url documentation

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1724]
The option to use grafana to proxy the datasource is fantastic. I had to sort of snoop around with a javascript console to figure out how to access the url for my scripted dashboard ajax query. This would be a good one to add a documentation entry for I think.

How I understand it:

http(s)://your.grafana.url:3000/api/datasources/proxy/1/ 

Is the first data source? That's my guess for the /1/

Love this feature.

Scott

**Comment by torkelo** [comment]
great, will try to document this when I do the HTTP Api docs
