### ISSUE TITLE
Homebrew upgrade issue to 6.2.0

### ISSUE THREAD

**Issue by chenrui333** [grafana/grafana#17242]
Relates to https://github.com/Homebrew/homebrew-core/pull/40176
Workaround is by bumping `node-sass` to `4.12.0`.

**Comment by marefr** [comment]
Grafana only support node with status [Active LTS](https://github.com/nodejs/Release) which currently is version 10.x. Please use version 10.x when installing Grafana through homebrew. We'll open our own 6.2 PR for homebrew shortly.
