### ISSUE TITLE
Datasource Host default value not used

### ISSUE THREAD

**Issue by joeheaton** [grafana/grafana#17253]
**What happened**: Datasource default value not used in Host field

**What you expected to happen**: The faded text "localhost:5432" (PostgreSQL example) to be used if the user hasn't populated the field

**How to reproduce it (as minimally and precisely as possible)**: Add new datasource, set Name, Database, User, Password; Click "Save & Test".

**Anything else we need to know?**:

This instance is using SQLite as a backend.

Grafana returns the error "Metric request error" which is unhelpful, it would be better to at-least change this to "Unable to save datasource". I suspect the error comes from the schema of the data_source table where "\`url\` TEXT NOT NULL", which means Grafana isn't trying to save this default value.

The debug log says "dbname is empty", which is confusing since that field is populated, even in the SQL when I inspected it!

Resolution was to set the host manually to "localhost:5432".

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: PostgreSQL 10 (Connecting to PostgreSQL 11)
- OS Grafana is installed on: CentOS 7
- User OS & Browser: RHEL 7 & Firefox 60
- Grafana plugins: None
- Others:

**Comment by danbob** [comment]
I just encountered this bug while adding an InfluxDB data source. In that case, the error was "Network Error: Bad Gateway(502)". The logs said `http: proxy error: unsupported protocol scheme ""`.

**Comment by cr1cr1** [comment]
I confirm this bug trying to add the simplest prometheus datasource.

Grafana 6.7.3 is deployed in a standard K8S cluster.
Runs under transparent proxy (Kong), set up to work under a different domain.

I have set the following vars to activate genric oauth login and run grafana under a different domain than the host is deployed (a K*S pod):

- GF_AUTH_GENERIC_OAUTH_ENABLED
- GF_AUTH_GENERIC_OAUTH_CLIENT_ID
- GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
- GF_AUTH_GENERIC_OAUTH_SCOPES
- GF_AUTH_GENERIC_OAUTH_AUTH_URL
- GF_AUTH_GENERIC_OAUTH_TOKEN_URL
- GF_AUTH_GENERIC_OAUTH_API_URL
- GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
- GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
- GF_AUTH_OAUTH_AUTO_LOGIN
- GF_AUTH_SIGNOUT_REDIRECT_URL
- GF_SERVER_DOMAIN
- GF_SERVER_ROOT_URL
- GF_LOG_LEVEL
