### ISSUE TITLE
crateDB display milliseconds

### ISSUE THREAD

**Issue by AngeloIapichino** [grafana/grafana#17252]
Hi guys, 
I have some time series data on crateDB having the timestamp in ms and i need to display some variables with millisecond resolution.
I read https://github.com/grafana/grafana/issues/728 and https://github.com/grafana/grafana/issues/714 but i didn't get what i have to do!

Is this feature supported only by influxDB? CrateDB can support it?

What are the right steps in order to reach this goal?

Thanks in advance

**Comment by torkelo** [comment]
What is not working? Can you describe your result? Is it about graph x-axis ticks?

**Comment by AngeloIapichino** [comment]
if i put data sampled under the second (in my case 4.2 ms) i have this result.
![image](https://user-images.githubusercontent.com/12069840/58267468-fe2c1380-7d83-11e9-9586-f8aedac09550.png)

**Comment by torkelo** [comment]
And your sure this is not a crateDB problem? What does query inspector show ? It shows the raw response from crateDB

**Comment by AngeloIapichino** [comment]
Yeah, it's a crateDB problem. it saves the timestamp in ms but don't use the last 3 digits (milliseconds).
My bad.
Thank you for the answers!
