### ISSUE TITLE
dashboard sharing - snapshot.raintaink.io fails with https

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1725]
Testing dashboard sharing, sharing to snapshot.raintank.io works with my grafana instance using http, but with https it just hangs and never completes.

I am using a self-signed cert. Do not see any error messages in the log.

**Comment by torkelo** [comment]
ok, good to know, waiting for a SSL cert for snapshot.raintank.io , should be under https shortly

**Comment by sknolin** [comment]
I should have looked at my javascript console - indeed it's the cross-site complaint as your comment suggests.

...(site).. was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://snapshots-origin.raintank.io/api/snapshots'. This request has been blocked; the content must be served over HTTPS.

Thanks

**Comment by nopzor1200** [comment]
snapshot.raintank.io should have a valid SSL as of several days ago. Thanks for reporting this!

**Comment by tristanbes** [comment]
Same for me

`Mixed Content: The page at 'https://xxx.com/dashboard/db/system' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://snapshots-origin.raintank.io/api/snapshots'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ app.6e379bdb.js:10`

**Comment by torkelo** [comment]
this should work now
