### ISSUE TITLE
unable to get report data more than 12 hr

### ISSUE THREAD

**Issue by ThakurBaba** [grafana/grafana#17250]
Hello,

I'm unable to get report data more than 12hr. If I select last 24hr or yesterday anything else more than 12 hour I'm getting No data show.
It give error Internal server error.

Can anyone help me to fix this though the data is available and data source available.

Regards,
Iftikhar

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
