### ISSUE TITLE
Add "negotiate" auth-scheme to elasticsearch data source for kerberos authentication

### ISSUE THREAD

**Issue by jamesmooneybodleian** [grafana/grafana#17269]
**What would you like to be added**:
To add negotiate auth-scheme to data sources (especially elasticsearch). Allow kerberos authentication.

**Why is this needed**:
The negotiate auth-scheme would be required to allow for kerberos authentication.

**Comment by jamesmooneybodleian** [comment]
I'm not exactly sure how the elastic search datasource connects to Elasticsearch, but suspect it's like a http curl request. So an example kerberos curl request would be setup like:

1. Set Kerberos packet: 
for Ubuntu/Debian:
apt install krb5-user

for RHEL/CentOS:
yum install krb5-workstation

2. Configure Kerberos configuration file (see MIT documentation for details)
cat /etc/krb5.conf 
[libdefaults]
	default_realm = EXAMPLE.COM

# The following krb5.conf variables are only for MIT Kerberos.
	kdc_timesync = 1
	ccache_type = 4
	forwardable = true
	proxiable = true

[realms]
	EXAMPE.COM = {
	}

[domain_realm]
	.example.com=EXAMPLE.COM
	example.com=EXAMPLE.COM

3. Create Kerberos ticket for user 'grafana'
kinit grafana 

4. curl command:
curl -v --negotiate -u : http://example.com

**Comment by jamesmooneybodleian** [comment]
Interested to know if adding kerberos authentication to elastic search data source could be a piece of paid for development. Let me know!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
