### ISSUE TITLE
Bar graph Elasticsearch term aggregation

### ISSUE THREAD

**Issue by rnd-ash** [grafana/grafana#17264]
## Description
When I try to do a series term aggregation using elasticsearch, the bars all get given the same name, rather than the name of the series. Take for instance the following query:
![image](https://user-images.githubusercontent.com/14551965/58324141-edc87700-7e1d-11e9-9bb6-5dbfe21d3cfb.png)
What I would expect here is a bar where each bar is named after the process name. But instead, the bar chart looks like this:
![image](https://user-images.githubusercontent.com/14551965/58324463-d5a52780-7e1e-11e9-866c-8dfbc370d2f4.png)

Comparing that to Kibana (how I was hoping for this to look like):
![image](https://user-images.githubusercontent.com/14551965/58324531-0dac6a80-7e1f-11e9-8c0f-a4262a690040.png)

Any idea as to how the series names can be formatted as the aggregation terms name?

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by torkelo** [comment]
You can fix this yourself by specifying a field title like: (in Field settings in the bar gauge settings) 

$__cell_0 $__field_name
