### ISSUE TITLE
Gauge Panel Font Size

### ISSUE THREAD

**Issue by CitySim** [grafana/grafana#17261]
**What happened**:
![image](https://user-images.githubusercontent.com/109395/58314094-172dd680-7e0f-11e9-8798-44904c0e1675.png)
using the "Gauge"-Panel the font size is quite small and difficult to read if displayed on a wall mounted TV for example.

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/109395/58313907-ebaaec00-7e0e-11e9-8199-97dcfdb5c4b0.png)
Using the "Singlestat"-Panel you can manually adjust the font size. It should be automatically scaled or manually adjustable again.

**How to reproduce it (as minimally and precisely as possible)**:
use a Gauge-Panel to display an percent value.

```json
{
  "datasource": "<--->",
  "gridPos": {
    "h": 3,
    "w": 3,
    "x": 6,
    "y": 9
  },
  "id": 23,
  "links": [],
  "options": {
    "fieldOptions": {
      "calcs": [
        "last"
      ],
      "defaults": {
        "max": 1,
        "min": 0,
        "unit": "percentunit",
        "decimals": 0
      },
      "mappings": [],
      "override": {},
      "thresholds": [
        {
          "color": "green",
          "index": 0,
          "value": null
        },
        {
          "color": "#EAB839",
          "index": 1,
          "value": 0.3
        },
        {
          "color": "red",
          "index": 2,
          "value": 0.8
        }
      ],
      "values": false
    },
    "orientation": "auto",
    "showThresholdLabels": false,
    "showThresholdMarkers": true
  },
  "pluginVersion": "6.2.0",
  "repeatIteration": 1558605055169,
  "repeatPanelId": 18,
  "repeatedByRow": true,
  "scopedVars": {
    "prom": {
      "selected": false,
      "text": "<--->",
      "value": "<--->"
    }
  },
  "targets": [
    {
      "expr": "sum(container_memory_usage_bytes{id=\"/\"}) / sum(machine_memory_bytes)",
      "format": "time_series",
      "instant": true,
      "intervalFactor": 1,
      "legendFormat": "Usage",
      "refId": "A"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "transparent": true,
  "type": "gauge"
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: `Grafana v6.2.0 (5d16da7)`
- Data source type & version: Prometheus
- OS Grafana is installed on: docker image on ubuntu host
- User OS & Browser: Chrome 75.0.3770.51 (beta), Firefox 67.0 on macOS 10.14.5
- Grafana plugins: none
- Others: -

**Comment by torkelo** [comment]
yea, it can be tweaked a bit I think.

**Comment by DanielGnzlzVll** [comment]
Something similar happens with the new bar-gauged panel,
@torkelo  could you look at it?
![image](https://user-images.githubusercontent.com/22230373/58369257-84984080-7ebd-11e9-9d94-50c5975148db.png)
