### ISSUE TITLE
panel sharing - 'direct link to rendered image' fails on https

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1726]
For sharing just a panel and the direct link option, this fails on https.  I don't see any error in the javascript console, I just get a blank tab.

I assume the 'iframe embed' code would also fail, but have not tested it.

Local snapshots work fine.

**Comment by torkelo** [comment]
does it work for you when you switch to http? (just want to understand that it really the https that is breaking it)

**Comment by sknolin** [comment]
Yes, it works fine on http. Since I've been switching back and forth anyway I figured I'd test every share function.
