### ISSUE TITLE
Gauge threshold markers not displaying correctly

### ISSUE THREAD

**Issue by c-def** [grafana/grafana#17277]
After updating to Grafana v6.2.0 (5d16da7), the gauge threshold markers are not displaying correctly. Previously the base value was on the left and max value was on the right. This has been reversed and not all of the thresholds are being displayed.

See the linked screenshot: [https://imgur.com/a/AwP0ngr](https://imgur.com/a/AwP0ngr)

**Comment by torkelo** [comment]
Strange, unable to replicate this. 

What version did you upgrade from? What is your dashboard.json?

**Comment by c-def** [comment]
I'm not sure which version I upgraded from. I generally keep it up to date using the Ubuntu repositories.

Here is the JSON model for this dashboard. I can't seem to attach files, get an error that something went wrong every time.

`{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "panels": [
    {
      "cacheTimeout": null,
      "datasource": "Temperature",
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "links": [],
      "options": {
        "fieldOptions": {
          "calcs": [
            "last"
          ],
          "defaults": {
            "decimals": 2,
            "max": "110",
            "min": "30",
            "unit": "farenheit"
          },
          "mappings": [],
          "override": {},
          "thresholds": [
            {
              "color": "red",
              "index": 0,
              "value": null
            },
            {
              "color": "#EAB839",
              "index": 1,
              "value": 70
            },
            {
              "color": "light-green",
              "index": 2,
              "value": 80
            },
            {
              "color": "green",
              "index": 3,
              "value": 85
            },
            {
              "color": "red",
              "index": 4,
              "value": 102
            }
          ],
          "values": false
        },
        "orientation": "auto",
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "6.2.0",
      "targets": [
        {
          "format": "time_series",
          "group": [],
          "metricColumn": "none",
          "rawQuery": true,
          "rawSql": "SELECT\n  $__time(timestamp_ts),\n  temperature_n as Temperature\nFROM\n  pool_temps_t\nWHERE\n  $__timeFilter(timestamp_ts)\nORDER BY 1",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "id_n"
                ],
                "type": "column"
              }
            ]
          ],
          "table": "pool_temps_t",
          "timeColumn": "timestamp_ts",
          "timeColumnType": "timestamptz",
          "where": [
            {
              "name": "$__timeFilter",
              "params": [],
              "type": "macro"
            }
          ]
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Current Pool Temperature",
      "transparent": true,
      "type": "gauge"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Temperature",
      "decimals": 2,
      "fill": 1,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 8
      },
      "id": 2,
      "legend": {
        "alignAsTable": true,
        "avg": true,
        "current": true,
        "max": true,
        "min": true,
        "show": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "options": {},
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "format": "time_series",
          "group": [],
          "hide": false,
          "metricColumn": "none",
          "rawQuery": true,
          "rawSql": "SELECT\n  $__time(timestamp_ts),\n  temperature_n as Temperature\nFROM\n  pool_temps_t\nwhere\n  $__timeFilter(timestamp_ts)",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "id_n"
                ],
                "type": "column"
              }
            ]
          ],
          "table": "pool_temps_t",
          "timeColumn": "timestamp_ts",
          "timeColumnType": "timestamptz",
          "where": [
            {
              "name": "$__timeFilter",
              "params": [],
              "type": "macro"
            }
          ]
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Pool Temperature History",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "farenheit",
          "label": "Temperature",
          "logBase": 1,
          "max": "100",
          "min": "30",
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": false
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "30m",
  "schemaVersion": 18,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "Pool",
  "uid": "NlqV3zzZk",
  "version": 15
}`

**Comment by torkelo** [comment]
The problem is your json 

somehow you have strings in the min/max values:

```
 "defaults": {
            "decimals": 2,
            "max": "110",
            "min": "30",
            "unit": "farenheit"
          },
```

If you use the editor and just modify the min & max (and then change back) Grafana will correct the type 

not sure how you have you got these string there. No other similar report. Did you build this json manually at some point?

**Comment by c-def** [comment]
That did the trick, but no I never built or edited the json manually. I simply upgraded Grafana through apt and afterwards it was doing this.
