### ISSUE TITLE
how to start server

### ISSUE THREAD

**Issue by lfender6445** [grafana/grafana#1727]
I have run 

```
cd $GOPATH/src/github.com/grafana/grafana
go run build.go setup            (only needed once to install godep)
godep restore                    (will pull down all golang lib dependecies in your current GOPATH)
go build 
```

then when i get to `bra` command , this appears at the end: 
```
15-04-07 19:24:50 [ WARN] Fail to execute command [go build -o ./bin/grafana]
```
there is no bin folder in the repo - how do I start the server? there doesn't appear to be a bin directory in `$GOPATH/src/github.com/grafana/grafana`

following instuctions here: http://docs.grafana.org/v2.0/project/building_from_source/ on mac osx

**Comment by torkelo** [comment]
do you get any error? what is the result from "go build".

**Comment by lfender6445** [comment]
hard to tell if these are errors: 

```
in grafana/ 
› go build
# github.com/lib/pq
../../lib/pq/buf.go:6: import /Users/lfender/Code/go/pkg/darwin_amd64/github.com/lib/pq/oid.a: object is [darwin amd64 go1.1 X:none] expected [darwin amd64 go1.4.2 X:precisestack]
# github.com/Unknwon/macaron
../../Unknwon/macaron/context.go:36: import /Users/lfender/Code/go/pkg/darwin_amd64/github.com/Unknwon/macaron/inject.a: object is [darwin amd64 go1.1 X:none] expected [darwin amd64 go1.4.2 X:precisestack]
```

**Comment by torkelo** [comment]
strange, did you do a `godep restore` before building?

**Comment by lfender6445** [comment]
yes I did

**Comment by lfender6445** [comment]
fixed by running `go build -a ` per http://stackoverflow.com/questions/27497705/how-to-rebuild-all-library-after-upgrading-go-1-4 -  in retrospect, should have just googled this to begin with  but thank you for your time torkelo

**Comment by torkelo** [comment]
np, great that you solved it!
