### ISSUE TITLE
Failed to start grafana.service with Result: 'exit-code'

### ISSUE THREAD

**Issue by TheOneWhoKnocks96** [grafana/grafana#17273]
**What happened**:
Can't start grafana.service.
**What you expected to happen**:
Should start succesfsully.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Here's the log:

grafana.service - Starts and stops a single grafana instance on this system
   Loaded: loaded (/lib/systemd/system/grafana.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-05-24 16:15:53 WEST; 6s ago
     Docs: http://docs.grafana.org
  Process: 21802 ExecStart=/usr/sbin/grafana --config=${CONF_FILE} cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR} (code=exited,
 Main PID: 21802 (code=exited, status=1/FAILURE)

mai 24 16:15:53 raspberrypi systemd[1]: Started Starts and stops a single grafana instance on this system.
mai 24 16:15:53 raspberrypi systemd[1]: grafana.service: Main process exited, code=exited, status=1/FAILURE
mai 24 16:15:53 raspberrypi systemd[1]: grafana.service: Unit entered failed state.
mai 24 16:15:53 raspberrypi systemd[1]: grafana.service: Failed with result 'exit-code'.

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: default
- OS Grafana is installed on: Debian Strecth
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Please check the output in grafana's own log file /var/log/grafana/grafana.log 

Probably some permission issue.
