### ISSUE TITLE
Grafana 2.0.0-beta1: `Invalid API Key` message after logging out

### ISSUE THREAD

**Issue by imkarthikk** [grafana/grafana#1728]
Here's what I did:
- Logged in as admin/admin
- Changed the username and password of admin
- Logged out

Expected:
Should have logged me out without any issue and taken me to the login page

Actual:
Instead, this is what it did:
![grafana2-bug](https://cloud.githubusercontent.com/assets/973265/7045280/6032341e-de1a-11e4-87b1-31108fb6f510.png)

Not sure if you know this already. :)

**Comment by torkelo** [comment]
strange, never seen that before

**Comment by imkarthikk** [comment]
Will some logs help you?

**Comment by torkelo** [comment]
can you replicate this? maybe some logs /var/log/grafana/grafana.log can help.

**Comment by imkarthikk** [comment]
This is what happened:
```shell
2015/04/08 11:57:40 [I] Completed / 302 Found in 2.058926ms
2015/04/08 11:58:19 [I] Starting Grafana
2015/04/08 11:58:19 [I] Version: 2.0.0-beta1, Commit: fb0629a, Build date: 2015-03-30 13:45:02 +0000 UTC
2015/04/08 11:58:19 [I] Config: Loaded from /opt/grafana/current/conf/defaults.ini
2015/04/08 11:58:19 [I] Config: Loaded from /etc/grafana/grafana.ini
2015/04/08 11:58:19 [I] Database: sqlite3, ConnectionString: file:/opt/grafana/data/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/04/08 11:58:19 [I] Migrator: Starting DB migration
2015/04/08 11:58:19 [I] Listen: http://0.0.0.0:3001
2015/04/08 11:58:35 [I] Completed /fonts/fontawesome-webfont.woff 206 Partial Content in 145.825µs
2015/04/08 11:58:36 [I] Completed /fonts/fontawesome-webfont.woff 206 Partial Content in 316.800452ms
2015/04/08 12:06:00 [I] Completed /app/app.8ae07506.js 206 Partial Content in 125.505µs
2015/04/08 12:06:03 [I] Completed /app/app.8ae07506.js 206 Partial Content in 2.848432089s
2015/04/08 12:17:42 [I] Completed /logout 302 Found in 1.896432ms
2015/04/08 12:17:44 [middleware.go:51 func·004()] [E] Invalid API key: Invalid Api Key
2015/04/08 12:17:44 [I] Completed /login 401 Unauthorized in 422.082µs
2015/04/08 12:18:23 [I] Completed /favicon.ico 404 Not Found in 684.606µs
2015/04/08 13:09:51 [I] Completed / 302 Found in 413.917µs
2015/04/08 13:10:14 [I] Completed /login 401 Unauthorized in 45.52997ms
2015/04/08 13:10:16 [I] Completed /login 401 Unauthorized in 44.415233ms
ubuntu@optimus:~$ 
```

**Comment by torkelo** [comment]
Are you having some basic auth proxy infront of grafana? Fixed an issue that resembles this recently. 

Try the latest beta 2 build (http://grafana.org/download/builds)

**Comment by imkarthikk** [comment]
@torkelo Nope. I don't have anything in front of Grafana. I'll give it a go now. :)

**Comment by LennyCastaneda** [comment]
Has this issue been resolved because I'm getting similar "Invalid Api Key" errors in the logs that is preventing the Basic OAuth from working properly.

**Comment by alallier** [comment]
I'm getting this as well with the Keycloak Gatekeeper in front of Grafana. Any thoughts?

**Comment by wann-ap** [comment]
> I'm getting this as well with the Keycloak Gatekeeper in front of Grafana. Any thoughts?

Did you fix this?

**Comment by gauravkadlag** [comment]
same here....I'm also getting the same issue with Keycloak Gatekeeper with grafana 6.7.0

t=2020-04-23T08:13:05+0000 lvl=eror msg="Invalid API key" logger=context error="Invalid Api Key"
t=2020-04-23T08:13:05+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path= status=401 remote_addr=10.230.71.29 time_ms=0 size=29 referer=

**Comment by alallier** [comment]
The solution is to strip the Authorization header before proxying to Grafana. Gatekeeper puts it there and then Grafana looks at it for API authentication. Pulled out my hair here for a long time on this.

**Comment by y0zg** [comment]
@alallier  Please confirm `enable-authorization-header=false` is the workaround

**Comment by alallier** [comment]
@y0zg I just made sure there wasn't an authorization header present with a value.

**Comment by net47** [comment]
If someone is using NGINX as reverse proxy for Grafana, you can also use the not-so-nice hack and just delete the authorization header before directing the request to Grafana:

`proxy_set_header authorization "";`
