### ISSUE TITLE
update defaults.ini - update smtp server

### ISSUE THREAD

**Issue by esxi1979** [grafana/grafana#17288]
Team
i did exec into the gafana container, i see smtp is not updated, i tried nano, vi , vim not preset

also files are owned by root, tried sudo not prsent too

i can not install anything 

su - , tried grafna etc no luck 

when i do invite i get the url but that does not work. i removed localhost in that url already. 

grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$ grep -i smtp defaults.ini
#################################### SMTP / Emailing #####################
[smtp]
grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$

grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$ pwd
/usr/share/grafana/conf
grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$ ls
defaults.ini  ldap.toml  provisioning  sample.ini
grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$
grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$
grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$ ls -l
total 48
-rw-r--r-- 1 root root 17644 Apr 29 13:44 defaults.ini
-rw-r--r-- 1 root root  2269 Apr 29 13:44 ldap.toml
drwxr-xr-x 5 root root  4096 Apr 29 13:58 provisioning
-rw-r--r-- 1 root root 17122 Apr 29 13:44 sample.ini
grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana/conf$

how can i fix this without kubectl cp .. that is my last option , thanks

**Comment by torkelo** [comment]
setting config via ENV variables does not modify ini files on disk , if you read the config docs you would learn that config files are not stored at /usr/share/grafana/conf (only defaults and examples), user config is at /etc/grafana/  but since you are in a container that should not matter. 

Did you set SMTP settings via ENV variables?

**Comment by esxi1979** [comment]
I know what you mean , thanks,  https://grafana.com/docs/installation/configuration/, i will give it a try. So you mean no way to edit the stmp from inside container ?

i do not see vi or vim or nano inside 

grafana@monitoring-grafana-55f9478564-hc8qj:/usr/share/grafana$ cd /etc/grafana/
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$ ls
grafana.ini  ldap.toml  provisioning
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$ vi grafana.ini
bash: vi: command not found
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$ nano
bash: nano: command not found
grafana@monitoring-grafana-55f9478564-hc8qj:/etc/grafana$
