### ISSUE TITLE
Gauge or Bar Gauge do not display "last" stat

### ISSUE THREAD

**Issue by collinsl03** [grafana/grafana#17286]
**What happened**:
Gauge/Bar Gauge do not display "last" or "current" stats - gauges display no value at all and bar gauges go "off the scale"

**What you expected to happen**:
Gauges from the singlestat will display the "current" stat but the Gauge or Bar Gauge visualisations don't.

**How to reproduce it (as minimally and precisely as possible)**:
Set up a Gauge or Bar Gauge to display "last (current)" stats.

**Anything else we need to know?**:

Mean calculations work fine, so do singlestat visualisations with the gauge option on or off.

Asking the Gauge or Bar Gauge visualisation to display "All Values" instead of "Calculation" shows that all but one of the values are coming back as "Null". The actual recorded value which appears most of the time (not all the time) is never the last value.

Changing the "Group by" "time interval" on the query will alter how many of the "all values" display the actual data recorded, but the last two are always null so the stat never works. 

**Environment**:
- Grafana version: 6.2.0-1
- Data source type & version: InfluxDB, 1.7.6-1
- OS Grafana is installed on: CentOS 7.6.1810
- User OS & Browser: Win 8.1 with Firefox 66.0.5, also Fedora 30 with Firefox 66.0.5-1
- Grafana plugins: default only
- Others: N/A

**Comment by torkelo** [comment]
Have you tried the option named  Last in the calculation, that shows the last value returned by your query. Can you show the raw response from your query?

**Comment by ryantxu** [comment]
![image](https://user-images.githubusercontent.com/705951/58435972-e69ca580-8077-11e9-8352-0435c55db457.png)

**Comment by ryantxu** [comment]
reading this more... I wonder if "last" is returning null because of grouping.

If you can modify your query, can you just change it to `SELECT LAST(value) ...` (or equivolent in your database)

Alternatively, we may need to add a ''Last not null value" or something like that

**Comment by szerwi** [comment]
I have the same issue. I've chosen "Last" in "Queries" tab as well as in "Visualization" tab. The value in the gauge sometimes gets displayed and sometimes not.

**Comment by ryantxu** [comment]
@szerwi / @collinsl03 -- can you guys try queries that do not use grouping and see if that fixes things?  I'm guessing you are querying data that gets grouped and the final value is sometimes null.

We should probably change our `last` calculation to be `last not null` or add a new calculation that does that

**Comment by szerwi** [comment]
@ryantxu it seems to be working when I removed "Group by" parameters in "queries" tab :)

**Comment by collinsl03** [comment]
Same for me, if I remove the group by it works fine.

**Comment by EdisonRobertoJr** [comment]
Hi everyone,

Same here, but im using Centreon/Graphite to receive data. Sometimes show de value, usually not.

![image](https://user-images.githubusercontent.com/49328470/59642187-6b8c5380-913a-11e9-85b8-68818997568e.png)

**Comment by torkelo** [comment]
We have added a new Calc option "Last non-null value"
