### ISSUE TITLE
Add hosted domain support for google.

### ISSUE THREAD

**Issue by radu-creanga** [grafana/grafana#1729]
Would be great to enable configuring a hosted domain for Google auth: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param.

**Comment by torkelo** [comment]
I recently added domain filtering to google oauth: https://github.com/grafana/grafana/issues/1660

But using the hd parameter is a good idea also.

**Comment by Dinoshauer** [comment]
Hi, just downloaded beta3 and wanted to try the `allowed_domains` but I get this message when I try to start the server with it in the configs:

`2015/04/13 11:05:37 [log.go:75 Fatal()] [E] Unknown config key allowed_domains defined in section auth.google, in file%!(EXTRA string=/etc/grafana/grafana.ini)`

**Comment by torkelo** [comment]
oh, shit, been doing a lot of refactoring of the config system and how configs are loaded / overloaded. A quick way for you to fix the problem is uncommenting line 155 (156) in /etc/usr/share/grafana/conf/defaults.ini

**Comment by Dinoshauer** [comment]
That seems to work! Thanks :)

**Comment by tehnomaag** [comment]
I hit the same thing, used sed to replace it in my docker build script:

`sed -i -e "s/; allowed_domains/allowed_domains/g" /usr/share/grafana/conf/defaults.ini`
