### ISSUE TITLE
Adding datasource prometheus in grafana HTTP Error Not Found

### ISSUE THREAD

**Issue by sachinar** [grafana/grafana#17300]
Hi Team,

We are having grafana instance which is running outside of kubernetes.
And we are having prometheus which is running inside kubernetes as a deployment.
The problem is when we are trying to add datasource we are getting HTTP Error Not Found.
What is the solution for this.
We already searched in community didn’t found anything.
One more thing we are having prometheus instances outside of kubernetes cluster where we are able to add them in same grafana.

**Comment by torkelo** [comment]
Closing this as it seems like a kubernetes networking issue 

Please ask questions on the community site https://community.grafana.com
