### ISSUE TITLE
Import does not honour dashboard's datasource

### ISSUE THREAD

**Issue by al4** [grafana/grafana#1730]
First of all thanks for grafana 2 - it's looking amazing!

I have a couple of issues though, running head of master at time of posting.

On my previous installation I had defined several datasources for testing (for example graphite, influxdb). It seems though, that even though I tried to redefine the datasources exactly as they were in my previous 1.x config, that the import defaults to a data source called "grafana", which has no data, and thus results in all my dashboards being replaced with random test series data.

In the underlying database I see the panel has ```"datasource":null```
Thus to fix each panel with the UI, I would have to edit the graph and select the correct datasource. This happens despite there being an datasource by the same name as the previous dashboards, and it being set as default.

I believe the dashboard import should preserve the datasource defined in the dashboard, and if it does not exist as named, use the configured default.

While I don't know any Go, I've whipped together a quick python script to set the datasource for dashboards if anyone else runs into the same problem: https://gist.github.com/al4/14ef99d72c1a5db5961e

**Comment by torkelo** [comment]
Have you marked your default data source as default in the data source edit view?

**Comment by torkelo** [comment]
there is a bug in beta1 so that when marking a data source as default in the data source edit view you need to refresh grafana (F5) for the "marked as default" option to take effect. (fixed in beta2 builds, http://grafana.org/download/builds)

**Comment by al4** [comment]
On first import I didn't have a default set, but when the import went bad I realised that setting a default would probably help, so I did delete * from dashboard and re-ran the import. This is all running against master (so should incorporate all fixes from beta2?)

**Comment by al4** [comment]
That refesh bug may have been it, I can't be certain that I refreshed after the imports. I'll re-test tomorrow and get back to you. :)
