### ISSUE TITLE
Support restricted access to Grafana instance with GitHub Team Membership

### ISSUE THREAD

**Issue by dewski** [grafana/grafana#1731]
With GitHub OAuth enabled it would be nice to be able to lock down the grafana instance by requiring the user to have team access to one of the defined teams in `auth.github.team_ids` or `GF_AUTH_GITHUB_TEAM_IDS`.

Example, say you have an ops team with the ID of 1500 and a security team with the ID of 3000. If you set the `team_ids` config it will deny access to Grafana unless the authenticated user is a member of one or more of those teams.

```
[auth.github]
team_ids = 1500,3000
```

```
GF_AUTH_GITHUB_TEAM_IDS=1500,3000
```

When a user attempts to register or login the backend would check the [team membership API](https://developer.github.com/v3/orgs/teams/#get-team-membership) for each of the defined teams in the configuration until it finds an `active` membership.

```
GET /teams/1500/memberships/dewski => 404
GET /teams/3000/memberships/dewski => 200
```

If the constraint isn't matched it will redirect back to the homepage, if it passes the user is logged in or created.

**Comment by torkelo** [comment]
Good idea! sounds pretty simple. PR please? :)

**Comment by dewski** [comment]
> Good idea! sounds pretty simple. PR please? :)

I'd be more than happy to once I can get my go env in a good place :sweat_smile: https://github.com/grafana/grafana/issues/1710#issuecomment-89640402
