### ISSUE TITLE
Bar Gauge: different font sizes for different values

### ISSUE THREAD

**Issue by seriych** [grafana/grafana#17315]
**What happened**:
Different font sizes for different values on a single Bar Gauge panel: small fontsize for three-digit values, medium fontsize for two-digit values, and big fontsize for single-digit values. it doesn't look very good.
![gauge_fontsize4](https://user-images.githubusercontent.com/15708872/58452816-29bb4f00-8132-11e9-8099-06ce1941642c.png)

**What you expected to happen**:
Same font sizes for values of the same type on a single panel. For example, calculate min font size for all values and choose this size for all values.

**How to reproduce it (as minimally and precisely as possible)**:
{"datasource":"SQL","description":"","gridPos":{"h":4,"w":7,"x":9,"y":17},"hideTimeOverride":false,"id":56,"links":[],"options":{"displayMode":"lcd","fieldOptions":{"calcs":["last"],"defaults":{"max":130,"min":30,"title":"$__series_name","unit":"celsius"},"mappings":[],"override":{},"thresholds":[{"color":"green","index":0,"value":null},{"color":"yellow","index":1,"value":90},{"color":"red","index":2,"value":100}],"values":false},"orientation":"horizontal"},"targets":[{"refId":"A","policy":"default","resultFormat":"time_series","orderByTime":"ASC","tags":[],"groupBy":[{"type":"time","params":["$__interval"]},{"type":"fill","params":["null"]}],"select":[[{"type":"column","params":["UserID"]}]],"format":"time_series","timeColumn":"Timestamp","metricColumn":"none","group":[],"where":[{"type":"macro","name":"$__timeFilter","params":[]}],"rawQuery":true,"rawSql":"select UNIX_TIMESTAMP(1559021987) as time, 285 as v1, 85 as v2, 5 as v3","table":"actions_data","timeColumnType":"timestamp"}],"timeFrom":null,"timeShift":null,"title":"test","type":"bargauge"}

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: MySQL 5.7
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10, Chrome 74.0.3729.169
- Grafana plugins: Bar Gauge
- Others:

**Comment by torkelo** [comment]
Currently this is not possible as each bar gauge is it's own visualization and it tries to optimize the font size it's value length. 

But with some refactoring / preprocessing step for the visualization repeater to pass in the max value length font sizes could be aligned.

**Comment by torkelo** [comment]
This should be fixed in 6.2+
