### ISSUE TITLE
Mix Auth Proxy & Grafana login tokens (sessions)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#17316]
In v6.0 we removed the old session store & session cookies and replaced them with a much more secure auth token scheme. 

This changed how auth proxy worked for some scenarios as the auth tokens are skipped in the auth proxy scenario. 

This issue is track interest in auth proxy scenario that mixes Auth Proxy & Auth tokens. Meaning the auth proxy header is only sent on some auth requests and not all.

**Comment by mryiiiii** [comment]
hi, this feature would really be helpful to build SSO mechanisms in some use cases (use of nginx as rp). thanks a lot if you can make it happened!

**Comment by Alives** [comment]
Is there a workaround in the meantime? What is everyone doing to get this to work in v6?

**Comment by kim0** [comment]
Hi @torkelo .. Could you please clarify the "some scenarios" that are currently broken ? I'm playing the auth_proxy and cannot get a basic `curl -H "X-WEBAUTH-USER: kamal"  http://localhost:8000/api/users` to work. 

Not sure if the auth_proxy support is totally broken in 6.x, so it would be great if you can clarify what works now and what doesn't (and any available workarounds if possible)

Thanks

**Comment by jakubvojacek** [comment]
Anyone managed to find some workaround, please?

**Comment by SvenMuc** [comment]
Any workaround for this issue? Have the same trouble with Grafana v6.3.2

**Comment by mn567** [comment]
> Any workaround for this issue? Have the same trouble with Grafana v6.3.2

This is working for us:
The proxy can save the userName as an encrypted cookie on the first request and then read the cookie in all subsequent requests and pass in the header.

**Comment by SvenMuc** [comment]
> The proxy can save the userName as an encrypted cookie on the first request and then read the cookie in all subsequent requests and pass in the header.

I‘m a newby on NGINX and its configuration. Could you explain it a bit more detailed how to forward the credentials via the header?

**Comment by mn567** [comment]
> > The proxy can save the userName as an encrypted cookie on the first request and then read the cookie in all subsequent requests and pass in the header.
> 
> I‘m a newby on NGINX and its configuration. Could you explain it a bit more detailed how to forward the credentials via the header?

In our proxy server setup, we have an IIS server and ASP.NET HTTP module. We had to write some code to achieve this functionality such as encrypting the cookie and setting an expiry to avoid cookie hijacking.

I am not sure if this can be achieved by NGINX configuration.

**Comment by SvenMuc** [comment]
**WORKAROUND:**
If I bind Grafana to an fixed IP address by e.g. `http_addr=192.168.1.200` in the grafana.ini file I can access (login) correctly to the dashboard by `192.168.1.200:3000`. Nevertheless, the full domain name (FQDN) still fails.

**Comment by rvanteru** [comment]
@torkelo  Any ETA when this auth proxy issue will be fixed?

**Comment by torkelo** [comment]
no ETA or plan to work on this.

**Comment by nielsmeima** [comment]
I also require the functionality where the auth token is set on every auth request going to the proxy. 
@torkelo if I would want to to work on implementing this feature, how would I start process and where would I begin so that it could later be merged back?

**Comment by iDrops** [comment]
> In v6.0 we removed the old session store & session cookies and replaced them with a much more secure auth token scheme.
> 
> This changed how auth proxy worked for some scenarios as the auth tokens are skipped in the auth proxy scenario.
> 
> This issue is track interest in auth proxy scenario that mixes Auth Proxy & Auth tokens. Meaning the auth proxy header is only sent on some auth requests and not all.

Any advice on how to reset the old session store & session cookies or the auth tokens? My problem is that - upgrading from Grafana 5.x to 6.x - I run into issues when login in with the browser originally used (macOS Safari). Using a different browser (e.g. Firefox) works w/o an issue.

**Comment by marefr** [comment]
@iDrops please read https://grafana.com/docs/installation/requirements/#known-issues
