### ISSUE TITLE
Bar Gauge: clickable links template

### ISSUE THREAD

**Issue by astorath** [grafana/grafana#17310]
**What would you like to be added**:
- a template to form links that open another dashboard on click on bar / name
- a tooltip on hover over bar to show full series name and some other stuff maybe

**Why is this needed**:
- this is de facto standard for these kinds of visualization panels, e.g.: https://grafana.com/plugins/grafana-polystat-panel
- this feature is already present in Grafana graph panel
- usually these types of  visualizations is used for an arbitrary number of similar entities (like hosts or apps) and these and entities may have some detailed dashboard that shows evolution of metrics shown

**Comment by slangloisde** [comment]
+1 for sure.

**Comment by tdehesse** [comment]
+1 for us also

**Comment by SirAlexey** [comment]
+1

**Comment by Uladik** [comment]
+1

**Comment by ryantxu** [comment]
This is included in 6.4beta1 -- see [DataLinks](https://grafana.com/docs/guides/whats-new-in-v6-4/#data-links-improvements)
