### ISSUE TITLE
If Host HTTP header mismatches from server.domain setting redirect to server.domain

### ISSUE THREAD

**Issue by dewski** [grafana/grafana#1732]
I have an instance of Grafana up and running on Heroku, but every Heroku instance is accessable by the `appname.herokuapp.com` domain. It would be nice if the proxy host wasn't accessible given the `Host` and `server.domain` config setting don't match. If the app checks the request's `Host` HTTP header and detects a mismatch, it should redirect to the expected domain defined in `server.domain`.

#### Configuration

```
[server]
domain = grafana.company.com
```

#### Current Behavior

```
$ curl -I https://company-grafana.herokuapp.com/
HTTP/1.1 200 OK
```

#### Expected Behavior

```
$ curl -I https://company-grafana.herokuapp.com/
HTTP/1.1 301 Moved Permanently
Location: https://grafana.company.com
```

**Comment by torkelo** [comment]
Added an option to enable this (disabled by default).

```ini
# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false
```
