### ISSUE TITLE
Explore: Refresh does not use updated time range when refreshing data

### ISSUE THREAD

**Issue by nkristianto** [grafana/grafana#17322]
**What happened**: 
send log to loki and show log from grafana dashboard. the application send the log, but grafana explorer dashboard does not refresh the log data

**What you expected to happen**:
every selected $__interval on dashboard, log data will refresh with the newest

**How to reproduce it (as minimally and precisely as possible)**:

1. Started loki, promtail, and grafana using docker-compose.yaml that provided on the README file
2. Send log to loki url with the app
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/afiskon/promtail-client/promtail"
)

const (
	source_name = "test_application"
)

func main() {
	quitChan := make(chan os.Signal, 1)
	signal.Notify(quitChan, syscall.SIGINT, syscall.SIGUSR1, syscall.SIGUSR2)

	labels := fmt.Sprintf(`{source="%s", job="log", job_name="run_log"}`, source_name)
	conf := promtail.ClientConfig{
		PushURL:            "http://localhost:3100/api/prom/push",
		Labels:             labels,
		BatchWait:          1 * time.Second,
		BatchEntriesNumber: 1000,
		SendLevel:          promtail.INFO,
		PrintLevel:         promtail.INFO,
	}

	loki, err := promtail.NewClientJson(conf)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for {
		select {
		case <-quitChan:
			loki.Warnf("caught terminating signal")
			os.Exit(1)
		case <-time.After(1 * time.Second):
			tstamp := time.Now().String()
			loki.Infof("source = %s, time = %s\n", source_name, tstamp)
		}
	}
}

```
**Anything else we need to know?**:

**Environment**:
- Grafana version: latest 
- Data source type & version: loki, latest version
- OS Grafana is installed on: Mac OS
- User OS & Browser: Google Chrome Version 74.0.3729.169 
- Grafana plugins: Loki
- Others: 
log from application :
https://user-images.githubusercontent.com/4598339/58469888-aec25a80-816a-11e9-8a4c-a8fd539e0335.png

log at grafana dashboard:
https://user-images.githubusercontent.com/4598339/58469914-be41a380-816a-11e9-9b5f-8f32647a95e8.png

**Comment by nkristianto** [comment]
hi @marefr , 
i try the latest build of grafana, for refresh by interval, that was great.
but i think, the live option, is still has a bug

i chose to show log with live option, and i send the log data from my app every 1s, but i didn,t getlog for every second

![image](https://user-images.githubusercontent.com/4598339/58580960-8de82b00-8278-11e9-87fe-5bc39402e295.png)

**Comment by mizeng** [comment]
@nkristianto what build of grafana? are you saying latest docker image of grafana?

**Comment by hugohaggmark** [comment]
Hi @nkristianto, we currently throttling messages every 1ms but we're also working on improving that algorithm in the upcoming iterations of live tailing. If you're pushing data in a steadily pace of 1s I think it should work better then the screenshot shows.
Could you please create a separate issue for this if you haven't already. 

Thanks

**Comment by nkristianto** [comment]
@mizeng , yes i use docker image with tag master from grafana

**Comment by nkristianto** [comment]
hi @hugohaggmark , sure. I'll create another issue for this

**Comment by nkristianto** [comment]
hi @hugohaggmark , this is the issue https://github.com/grafana/grafana/issues/17378

**Comment by hugohaggmark** [comment]
@nkristianto thanks!
