### ISSUE TITLE
Added extra // to variables in query

### ISSUE THREAD

**Issue by VatslauX** [grafana/grafana#17323]
**What happened**:
I added a part on query search in variables as text/constant to reuse in query and concatenate long queries

Example applicationType:"XXX" AND userActions.internalApplicationId:"YYYY" 
But in the inspector, I see that added extra escaping

Form query text OK: `"applicationType:\"XXX\" AND userActions.internalApplicationId:\"MOBILE_APPLICATION-YYYY\"`

From varibles NOK: ` "applicationType\\:\\\"XXX\\\"\\ AND\\ userActions.internalApplicationId\\:\\\"MOBILE_APPLICATION\\-YYYY\\\" `

This affect searches results (Used elasticsearch)
**What you expected to happen**:
No additional \\ should be added to the query
Form query text OK: "applicationType:\"MOBILE_APPLICATION\" AND userActions.internalApplicationId:\"MOBILE_APPLICATION-87D6CDFAD0A74652\"

**How to reproduce it (as minimally and precisely as possible)**:
Add any variable with "" and reuse in graphic
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6x
- Data source type & version: Elastic search
- OS Grafana is installed on: Unix
- User OS & Browser: Chrome
- Grafana plugins: not matter
- Others: not matter

**Comment by torkelo** [comment]
use ${variableName:raw} if you want to disable all variable lucene escaping
