### ISSUE TITLE
Default Org settings ignored

### ISSUE THREAD

**Issue by langebe** [grafana/grafana#17326]
When I deploy a new instance and perform a GET /api/org/preferences it's showing that it's using homeDashboardID 0.

When I change the uid of my (only) dashboard to this value  (and restart grafana-server) nothing seems to happen.

Once I modify the Org settings with a HTTP PUT request, the homedashboard is being used, even if the ID is not matching.
Is there any reason for this behavior?

Also is there a difference between ID and UID for the dashboard?
In the json file it's UID, but the the org configuration requires an ID.
(Probably related to this https://github.com/grafana/grafana/issues/14152)

**Comment by torkelo** [comment]
id is the DB persistance id that is generated on save. 

> When I deploy a new instance and perform a GET /api/org/preferences it's showing that it's using homeDashboardID 0.

that means it's unassigned (using default).

Closing this as it's probably related to this: https://github.com/grafana/grafana/issues/14152

**Comment by langebe** [comment]
When I set homeDashboardID 0 (like the default) it's working as well.
How can we check if this is still at default values, or if has been set and 'activated' already?
I'd expect something like NA or NULL if the value is being ignored at this point.
