### ISSUE TITLE
The version does not seem to be updated when upgrading from version 6.1.6 to 6.2.1.

### ISSUE THREAD

**Issue by SeppPenner** [grafana/grafana#17334]
**What happened**:
Updated Grafana from 6.1.6 to 6.2.1 on an armhf system. The version does not seem to be updated. Still 6.1.6. 

**What you expected to happen**:
The version needs to be updated to 6.2.1.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install 6.1.6 on ARM.
2. Update to 6.2.1 using
```bash
wget https://dl.grafana.com/oss/release/grafana_6.2.1_armhf.deb
sudo dpkg -i grafana_6.2.1_armhf.deb
```

**Anything else we need to know?**:
Nope.

**Environment**:
- Grafana version: 6.1.6. (commit: cf9cb45)
- Data source type & version: Irrelevant for the issue.
- OS Grafana is installed on: `Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux`
- User OS & Browser: Firefox Quantum 67.0.
- Grafana plugins: None.
- Others: Nothing.

**Comment by torkelo** [comment]
Did you  try restarting grafana-server? 

It usually restarts automatically when upgrading via apt install. But maybe a special case with using dpkg -i manually on ARM?

**Comment by SeppPenner** [comment]
> Did you try restarting grafana-server?
> 
> It usually restarts automatically when upgrading via apt install. But maybe a special case with using dpkg -i manually on ARM?

I restarted the grafana-server several times. How does it even work over `apt install`? I have updated Grafana using:

```bash
dpkg -r grafana
wget https://dl.grafana.com/oss/release/grafana_6.2.1_armhf.deb
sudo dpkg -i grafana_6.2.1_armhf.deb
```

**Comment by SeppPenner** [comment]
Rebooting the device does not help either.

**Comment by SeppPenner** [comment]
@torkelo Just for reference. The version is again correct when installing the latest version (6.2.5). Maybe there was a temporary error on my Raspberry...
