### ISSUE TITLE
Docker Image : Windows Docker Error 

### ISSUE THREAD

**Issue by arunprasathv** [grafana/grafana#17338]
Trying to Install Grafana Image but receiving this error on Windows 10,

docker: error during connect: Post 

http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create?name=grafana: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

**Comment by torkelo** [comment]
This looks like windows docker networking issue unrelated to Grafana specifically 

Please ask questions on the community site https://community.grafana.com
