### ISSUE TITLE
Templating init failed with 'all option' having long query string (6.2.1)

### ISSUE THREAD

**Issue by steveum0105** [grafana/grafana#17335]
**What happened**:
3 types of nested Variables have a lot of items. When I call them for 'all', I failed to load like below.
When I tried to delete random items from long long query string, then it works fine.

I use only one prometheus datasource.
 
<img width="1670" alt="a" src="https://user-images.githubusercontent.com/36035905/58504545-cf6bce00-81c5-11e9-833c-779432f45652.png">
<img width="1130" alt="b" src="https://user-images.githubusercontent.com/36035905/58504549-d1ce2800-81c5-11e9-9d5b-83ef35ec7584.png">

**What you expected to happen**:
Success to load dashboard with all option

**How to reproduce it (as minimally and precisely as possible)**:
nested variables with many long items, and run

**Anything else we need to know?**:
This is my guess.

With templating init failed, I cannot load last nested variable like this.
<img width="487" alt="c" src="https://user-images.githubusercontent.com/36035905/58505005-e5c65980-81c6-11e9-903c-d9b32e999336.png">

Once I success to load the dashboard with few items (by decreasing time interval), and then I can load 'all' with many items(by increasing time interval) which I have failed before.
However, the first try with many items leads the fail to load nested variable at the panel, then I fail everything. 

I attach my nested variables.
<img width="1044" alt="d" src="https://user-images.githubusercontent.com/36035905/58505709-8701df80-81c8-11e9-95ea-c8bacd66550f.png">

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: prometheus
- OS Grafana is installed on: centos7 - k8s
- User OS & Browser: MacOS safari, chrome
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
If you have variables with a lot of values and use the "All" feature, specify a custom all value like .* to match everything.
