### ISSUE TITLE
Remove extra padding when a title exists

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17339]
I think there is too much space at the top of each panel.  Can we remove the padding between the body and header?
<img src="https://user-images.githubusercontent.com/705951/58518219-1e344c00-8163-11e9-94e1-e8de05c2f2af.png">

![image](https://user-images.githubusercontent.com/705951/58518255-4fad1780-8163-11e9-914d-d16f87fd1fc5.png)

Here a graph from v5 -- there is still some padding, but I think less:
![image](https://user-images.githubusercontent.com/705951/58518361-c8ac6f00-8163-11e9-870e-7d4d0b89ffac.png)

**Comment by torkelo** [comment]
Yes , this was fixed when working on panels with no title. And it simplified the logic a great deal to have symmetrical padding and looked better for many panels , have non symmetrical padding looked off for many panels

**Comment by torkelo** [comment]
I agree that it looks a tiny bit too much for Graph panels but for text panels, gauges, bar gauges, etc no top padding looked worse.

**Comment by ryantxu** [comment]
Ya, it depends on the panel what looks best.  This is v5 with the discrete panel:
![image](https://user-images.githubusercontent.com/705951/58568773-ae1cd900-81e9-11e9-8b7b-31d069f9f193.png)

Looks better with even spacing around the title.
