### ISSUE TITLE
Use configured HTTP Method for meta data requests

### ISSUE THREAD

**Issue by erez-rabih** [grafana/grafana#17342]
**What happened**:
None of the panels loaded the requested data

**What you expected to happen**:
All panels should have loaded the data

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up a prometheus datasource
2. Define a variable with a large cardinality (I'm using 380 pod names)
3. Use automatic ALL value on the variable
4. Build a query which embeds the variable in it
5. Panels do not load data

seems to be exactly as https://github.com/grafana/grafana/issues/8109 but for prometheus rather than influxDB

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/813024/58535686-3786d800-81f7-11e9-97d1-81dd76722cc7.png)

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Prometheus 2.8
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOSx Mojave
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
If you have variables with a lot of values and use the "All" feature, specify a custom all value lie `.*` to match everything.

**Comment by erez-rabih** [comment]
@torkelo I know that, but using .* requires you to filter by other means
I have a multi variable dashboard where each variable is dependent on the other:
1. deployment | label_values(kube_deployment_created, deployment)
2. replicaset | label_values(kube_replicaset_owner{owner_name="$deployment"}, replicaset)
3. pod | kube_pod_info{owner="$replicaset"}

so I have all pods of a deployment by using other variables in the template
now for example I want a graph of accumulated cpu usage:
sum(rate(container_cpu_usage_seconds_total{pod_name=~"$pod"}[5m]))

This works only because I use the regular expression (pod1|pod2|...) and not the .* version of the all value
If I used .*, I'd just get all pods usage rather than that specific deployment

I really don't understand the urge to close this without giving some attention to the issue

**Comment by torkelo** [comment]
The metadataRequests are not using the configured httpMethod setting 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L122 

So we already have setting for using POST but it's not being used for the meta data api requests and it looks like the prometheus api supports this.

**Comment by torkelo** [comment]
Except the docs say only GET for this request: 
GET /api/v1/label/<label_name>/values 

https://prometheus.io/docs/prometheus/latest/querying/api/ 

But could be a mistake in the docs or that this is not fully supported in Prometheus.

**Comment by marefr** [comment]
@torkelo see my comment here https://github.com/grafana/grafana/pull/16520#pullrequestreview-232512394

**Comment by erez-rabih** [comment]
From going through the docs it seems both GET and POST verbs are interchangeable :

![image](https://user-images.githubusercontent.com/813024/58556365-90b93080-8224-11e9-9965-c8480ab5cc52.png)

**Comment by erez-rabih** [comment]
@torkelo would you be kind to post some leads pointing to where the changes should be made?
I'd be happy to submit a PR for this

**Comment by mrraj470** [comment]
Is there any way we can configure grafana to use POST method to query the datasource?
Of course I can do this in the UI but, I want to automate it in the deployment.

An option to configure this in the `provisioning/datasources/__datasource_1__.yaml` would be nice.

**Comment by marefr** [comment]
@erez-rabih see my https://github.com/grafana/grafana/pull/16520#pullrequestreview-232512394  for a suggested solution that's backward compatible with older Prometheus versions.

**Comment by marefr** [comment]
@mrraj470 Normally I would advice asking questions on our community site, but I noticed that we lack some documentation about `HTTP Method` and other options [here](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/#prometheus-settings) and [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources).

You can normally find the expected `jsonData` properties/fields here: https://github.com/grafana/grafana/blob/d3a23a617ff85d399e223a8a3bdae402dcc6c370/public/app/plugins/datasource/prometheus/datasource.ts#L93-L106

Provisioning example for `HTTP Method`:
```yaml
apiVersion: 1

datasources:
  - name: gdev-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      httpMethod: POST
```

If anyone is interested in contributing some documentation updates that would be helpful.

**Comment by aocenas** [comment]
There is also external PR trying to solve this https://github.com/grafana/grafana/pull/16520
