### ISSUE TITLE
Refresh dropdown shows all options when refresh is disabled

### ISSUE THREAD

**Issue by bsmarcosj** [grafana/grafana#17341]
**What happened**:
Refresh dropdown shows all options when refresh is disabled

**What you expected to happen**:
The dropdown should have only the "off" option.

**How to reproduce it (as minimally and precisely as possible)**:
Empty the "Auto-Refresh" text box in Settings/General/Time Options.

![image](https://user-images.githubusercontent.com/6134894/58534008-5c288300-81ea-11e9-8ab2-ea220b81a5c4.png)
![image (3)](https://user-images.githubusercontent.com/6134894/58534785-7bc0ab00-81ec-11e9-9ec6-98caab46ccff.png)

**Environment**:
- Grafana version: 6.2.1
- User OS & Browser: Ubuntu - Chrome

**Comment by davkal** [comment]
Removing bug label, because it's not entirely clear that an empty setting disables all options.

**Comment by dehrax** [comment]
It explicitly says in the code that it is supposed to fallback on default values when the auto-refresh intervals is empty. 
https://github.com/grafana/grafana/blob/406ef962fc113091bb7229c8f3f0090d63c8392e/packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx#L51
Easy to fix, just a question about which option is preffered.

**Comment by torkelo** [comment]
If the interval last array is empty then show no options, if the intervals array is undefined show defaults
