### ISSUE TITLE
how can we debug grafana golang code with IDE goland?

### ISSUE THREAD

**Issue by Zuckonit** [grafana/grafana#17346]
```
how can we debug grafana golang code with IDE goland?
```

(sorry, I know its not a good place for asking question. I tried so many methods, still failed. so I ask a related question many months ago at community, but got no response yet.  that's why I put it again here. thanks for comprehending)

**Comment by torkelo** [comment]
It should just work? Ask in goland forum maybe?

**Comment by Ahsan-Aziz-Ishan** [comment]
Did you find a way ?

**Comment by Ahsan-Aziz-Ishan** [comment]
Ok seems like, I've figured it out .


Here is the complete guideline on how to setup debugger on GoLand:

[Debug-Grafana-Backend-On-GoLand](https://github.com/Ahsan-Aziz-Ishan/Debug-Grafana-Backend-On-GoLand)
