### ISSUE TITLE
ReadOnly datasource property returned incorrectly when querying by datasource name via API

### ISSUE THREAD

**Issue by philly86** [grafana/grafana#17347]
**What happened**:
It appears that _readOnly_ property of an already created datasource is returned incorrectly when the one datasource is queried by it's name using HTTP API. At the same time, when a list of all datasources is requested via HTTP API, the property is displayed correctly.

![grafana_datasource_querying](https://user-images.githubusercontent.com/22811188/58549425-26988f80-8214-11e9-9c64-737d13479fa7.png)

**What you expected to happen**:
_readOnly_ property value should be consistent regardless of how the datasources config is retrieved.

**How to reproduce it**:
1. Run Grafana in Docker:
```
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=grafana-azure-monitor-datasource" grafana/grafana
```` 
3. Create a datasource by posting a JSON:
```
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json"  http://admin:admin@localhost:3000/api/datasources -d @./grafana_env/g
rafana_datasources/test.json
```
Content of the sample config file:
```
{
  "orgId": 1,
  "name": "ai-devops-tst",
  "type": "grafana-azure-monitor-datasource",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "/api/datasources/proxy/4",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "appInsightsAppId": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx",
    "azureLogAnalyticsSameAs": true,
    "clientId": "xxxxxxxx-xxx-xxx-xxxxx-xxxxxxxxxx",
    "cloudName": "azuremonitor",
    "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx"
  },
  "secureJsonFields": {
    "appInsightsApiKey": "111111111",
    "clientSecret": "11111111111111111111111"
  },
  "readOnly": false
}
```

4. Observe discrepancy between results of readOnly property as displayed on the screenshot above

**Environment**: Docker Grafana 
- Grafana version: v6.1.6 (cf9cb45)
- Data source type & version: Azure Monitor  0.3.0 
- OS Grafana is installed on: Host: Windows 10; Docker:Debian GNU/Linux 9
- User OS & Browser: NA
- Grafana plugins:  Azure Monitor  0.3.0 
- Others:

**Comment by torkelo** [comment]
This looks a bit buggy, you should not be able to create a readOnly data source via the API (as it can only be removed via provisioning). 

Think the json prop here should be removed:
https://github.com/grafana/grafana/blob/master/pkg/models/datasource.go#L142 

(and on the update command). 

This logic where it is set to true seems very strange:
https://github.com/grafana/grafana/blob/master/pkg/api/datasources.go#L234

pring @bergquist

**Comment by philly86** [comment]
@torkelo thanks for a prompt response.
I think I was able to set readOnly property to 'true' when setting up the datasource via JSON. 
I couldn't, then, remove the datasouce. But I was able to update the datasource via API setting readOnly property to 'false'. This allowed me to remove the datasouce.

**Comment by bergquist** [comment]
Yea that json prop should be removed from create and update command. 

https://github.com/grafana/grafana/blob/master/pkg/api/datasources.go#L234 does look weird. But the only usage I can find of `/api/datasources/name` is in load tests files.
