### ISSUE TITLE
grafana daily logrotate 

### ISSUE THREAD

**Issue by kube04** [grafana/grafana#17345]
I enabled logrotate boolean true but its not rotate on log daily basis  

**What happened**:
cannot rotate log daily basis 
**What you expected to happen**:
how to rotate log daily basis
**Environment**:
- Grafana version: 6.1.6
- Data source: prometheus
- OS Grafana is installed on: Ubuntu 18
- Grafana plugins: None
- Others:

**Comment by kube04** [comment]
my Logging configuration settings

**Comment by torkelo** [comment]
strange, works here. Can you show your log config?

**Comment by kube04** [comment]
**[log]**
**# Either "console", "file", "syslog". Default is console and file**
**# Use space to separate multiple modes, e.g. "console file"**
**mode = console file**

**# Either "debug", "info", "warn", "error", "critical", default is "info"**
**level = info**

**# optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug**
**filters =**

**# For "console" mode only**
**[log.console]**
**level =**

**# log line format, valid options are text, console and json**
**format = console**

**# For "file" mode only**
**[log.file]**
**level =**

**# log line format, valid options are text, console and json**
**format = text**

**# This enables automated log rotate(switch of following options), default is true**
**log_rotate = true**

**# Max line number of single file, default is 1000000**
**max_lines = 1000000**

**# Max size shift of single file, default is 28 means 1 << 28, 256MB**
**max_size_shift = 28**

**# Segment log daily, default is true**
**daily_rotate = true**

**# Expired days of log file(delete after max days), default is 7**
**max_days = 7**

The above lines are my logging configuration settings

**Comment by torkelo** [comment]
Still unable to replicate, the logs rotate daily for me and no other reports so closing this
