### ISSUE TITLE
[2.0.0 beta1] When dashboard not found, it can not be deleted

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#1734]
I click to a dashboard, it displays 404, but I find no where to delete the dashboard

**Comment by torkelo** [comment]
delete a dashboard  that does not exist???

**Comment by liyichao** [comment]
The dashboard title starts with Chinese words, When I click it from dashboard list, a page with a big "Page Not Found 404" shows. The dashboard was imported from 1.9.x with influxdb.
