### ISSUE TITLE
If a value of my graph is not normal, how can I use a different color to distinguish it with normal use with grafana

### ISSUE THREAD

**Issue by lwd426** [grafana/grafana#1735]
If a value of my graph is not normal, how can I use a different color to distinguish it with normal use with grafana?

**Comment by torkelo** [comment]
You can set graph thresholds, and you can change series colors, but the color of a series can currently no be dynamic (based on some value in the series)

**Comment by lwd426** [comment]
Thank you,torkelo.I meant to fill the unnormal bar with a different color(such as red).Do I have to use javascript?

**Comment by torkelo** [comment]
@lwd426 yes, you have to do some pretty big modifiations to the grafana and graph library source to do that.
