### ISSUE TITLE
Docs feedback: features/datasources/index.md

### ISSUE THREAD

**Issue by DeeGeeGit** [grafana/grafana#17350]
At the bottom of the list of datasources we should have a link that says something along the lines of "if you're looking for other datasources like Datadog or Dynatrace please check out our Grafana Enterprise offering" with a link to https://grafana.com/docs/enterprise/#grafana-enterprise

**Comment by torkelo** [comment]
the index page is not really accessible or linked to, how did you find it? I know it's there but only to have a node in the menu tree :) 

Will try to find a way to get the enterprise plugins into the data source list
