### ISSUE TITLE
Stackdriver: Google Default Credentials authentication method

### ISSUE THREAD

**Issue by NaurisSadovskis** [grafana/grafana#17353]
**What would you like to be added**: Hello there. It would be great to have [Google Default Credentials authentication method](https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials) for Stackdriver plugin. 

This method ultimately can replace [existing method for GCE authentication](https://github.com/grafana/grafana/blob/v6.2.x/pkg/api/pluginproxy/ds_auth_provider.go#L65-L77).

**Why is this needed**: This is useful is most useful when user/instance has authenticated using `gcloud` or have set `GOOGLE_APPLICATION_CREDENTIALS` environment variable.

Example scenarios: 
1. Not possible to use GCE Metadata API - instance running outside GCP. 
2. Not feasible to use JSON service account key - Grafana running on GKE via [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity))

**Comment by marefr** [comment]
@NaurisSadovskis 

> It would be great to have [Google Default Credentials authentication method](https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials) for Stackdriver plugin.

Reading on existing method used `DefaultTokenSource`: DefaultTokenSource returns the token source for "Application Default Credentials". **It is a shortcut for FindDefaultCredentials(ctx, scope).TokenSource.**. See source code: https://github.com/golang/oauth2/blob/master/google/default.go#L54

So to me it seems this is already supported don't you agree?

**Comment by NaurisSadovskis** [comment]
@marefr well spotted, my bad!

When Running some tests, I found that project ID was not being populated when using the [second function](https://github.com/golang/oauth2/blob/master/google/default.go#L87-L93) in `FindDefaultCredentials`. This lead to queries failing despite having valid credentials - verifiable via `gcloud auth list`. SDK actually specifies that `ProjectID` [_might be empty_](https://godoc.org/golang.org/x/oauth2/google#Credentials). 

This could be handled in multiple ways:
1. Return an error if project ID fetched from credentials is empty (this alerts, but does not provide any additional functionality)
2. Allow user to input a project ID if default project ID is not found. @sunker opened [an issue](https://github.com/grafana/grafana/issues/14764) about this a while ago.

Let me know how you think this would be implemented best.

**Comment by marefr** [comment]
Not sure I have enough experience with Stackdriver to have any good input on how to handle an empty project id. For starters I don't understand how the project id can be empty but you still can select other project id's - sounds to me like a configuration issue? Isn't the idea with #14764 that besides the default project would allow you to select other projects. 

Think we'll need some input from @daniellee here.

If you have an idea how to solve this and you want to explore that, you're very welcome to open a (draft) PR where we can discuss this further. We try to encourage people to open PR's early in implementation so that we can provide early feedback on if suggested change is something that we could accept.

**Comment by NaurisSadovskis** [comment]
@marefr: thanks for providing clarity on this. I'll see what can be implemented and how. 

I think it's not so much a Stackdriver issue than Google itself. Almost all resources are scoped to the project, so there is little to no data that can be retrieved outside that scope. I believe there could be a simpler way to check the validity of the credentials without invoking any 'test' GCP API calls. This would allow us to ignore the project value and implement something that would allow the user to choose the value himself. 

I'll take a stab at pre-populating projects via `gcloud projects list` API equivalent and see if something comes out of it!

**Comment by torkelo** [comment]
Ok, so seems unrelated to this issue so closing

**Comment by cmcga1125** [comment]
Hello, did anything happen with support to authenticate to stack driver using the default SA on a pod in GKE (workload identity)? or did the focus of this request simply get split into the ability to access multiple with one SA?  It'd be super nice not to have a jwt we have to manage / rotate.

**Comment by cmcga1125** [comment]
hello me again, It seems we had a piece of workload identity misconfigured (misspelled a SA name).  

Can confirm that the GCE Default Service Account works with GKE's Workload Identity.

**Comment by virtuman** [comment]
> hello me again, It seems we had a piece of workload identity misconfigured (misspelled a SA name).
> 
> Can confirm that the GCE Default Service Account works with GKE's Workload Identity.

Can you tell what Permissions you gave to the Service account? monitoring viewer doesn't seem sufficient in my case

**Comment by cmcga1125** [comment]
My grafana account has the following predefined roles assigned:
`roles/monitoring.viewer` 
`roles/iam.workloadIdentityUser`

what are the errors/issues you're seeing?

**Comment by NaurisSadovskis** [comment]
to add to @cmcga1125's post, I suggest you verify that:
1) Google SA <-> Kubernetes SA configuration has been done correctly (follow [Step 7 & 8](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to) in the docs)
2. Once confirmed that you're authenticating with a Google SA via Kubernetes SA, I would verify that your Grafana deployment is mapping the correct [service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) within the pod.

If you're not using Workload Identity and/or running in a GCE VM, running `gcloud auth list` should be enough to check if you have relevant credentials configured.
