### ISSUE TITLE
Automatic query execution in explore can lock up browser

### ISSUE THREAD

**Issue by cstyan** [grafana/grafana#17360]
**What would you like to be added**:
It would be nice to, within the Explore UI, have the option to disable automatic execution of queries.

**Why is this needed**:
As an example, sometimes I use the auto complete to find the name of a series I want to query for. When the auto complete fills in the series name for me, the query is executed before I have a chance to add any label matchers that I know I want. The query name itself loads a high amount of unique series into the page and locks up my browser. If possible I would like to be able to have queries executed only when I explicitly click the button.

This may be Prometheus specific?

cc @davkal

**Comment by davkal** [comment]
Already fixed.

**Comment by GitHamburg** [comment]
How to disable
