### ISSUE TITLE
`root_url` not honored on plugin page

### ISSUE THREAD

**Issue by RangerRick** [grafana/grafana#17362]
**What happened**:

I configured `nginx` on Mac to proxy Grafana.  When I attempt to click any tabs or plugin-related links from a plugin detail page I get a 404 not found.

**What you expected to happen**:

The links are clickable and navigate properly.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure Grafana and nginx using the [sub path](https://grafana.com/docs/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-grafana) directions in the Grafana documentation.  (`nginx` installed with Homebrew runs on port 8080 by default)

`nginx.conf`:
```

location /grafana/ {
    proxy_pass http://localhost:3000/;
}
```

`grafana.ini`:
```
[server]
domain = localhost
root_url = http://localhost:8080/grafana/
```

2. browse to http://localhost:8080/grafana/ and log in
3. go to `Configuration -> Plugins` and click any plugin with multiple tabs from a README and/or dashboards (like OpenNMS Helm)
4. click `Readme` or `Dashboards` or the `Plugins` breadcrumb at the top of the page

<img width="985" alt="grafana-bad-links" src="https://user-images.githubusercontent.com/89252/58592362-4476ec00-8236-11e9-873a-6fb58eb9afb6.png">

If you hover over the links you'll see they're missing the `/grafana/` prefix.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: N/A
- OS Grafana is installed on: Mac OS X, also seen on CentOS 7
- User OS & Browser: Mac OS X, Firefox 67
- Grafana plugins: OpenNMS Helm plus defaults
- Others:

**Comment by torkelo** [comment]
thanks for reporting this!
