### ISSUE TITLE
[REST API] Missing User information for different API calls (/api/users , /api/users/:id , /api/users/lookup)

### ISSUE THREAD

**Issue by DRashmi30** [grafana/grafana#17373]
**What would you like to be added**: The User object returned by different API (as mentioned in the subject) should return same data elements. User properties like lastSeenAt, lastSeenAtAge, OrgId, Theme are not returned as a part of User object across different API calls.

**Why is this needed**: This will help to ensure that the same set of properties for User object is retrieved, unlike in the current implementation.

**Comment by DRashmi30** [comment]
[Grafana_API_Details.docx](https://github.com/grafana/grafana/files/3236649/Grafana_API_Details.docx)

**Comment by torkelo** [comment]
These api's serve different use cases, (list api vs detail apis) are designed for what the UI needs right now, which also are different for each
