### ISSUE TITLE
Docs feedback: plugins/developing/development.md

### ISSUE THREAD

**Issue by cr4zyc4t** [grafana/grafana#17370]
I write a plugin support bundle panel plugin for Grafana, basically it like a fork of official react-scripts but output as Grafana plugin. I'm glad if you add as an example for build plugin for Grafana 6
https://www.npmjs.com/package/grafana-plugin-scripts

Example:
https://github.com/cr4zyc4t/grafana-plugin-template

**Comment by torkelo** [comment]
This will be part of the new @grafana/ui doc we also plan to create "create plugin" cli tool that creates a boilerplate. 

We also have these https://github.com/grafana/react-plugin-examples
