### ISSUE TITLE
Request count for internal loadbalancer

### ISSUE THREAD

**Issue by kaiattewell** [grafana/grafana#17371]
**What would you like to be added**:
A way of counting requests for internal TCP loadbalancers on GCP.
**Why is this needed**:
Getting information from the external load balancer can be very vague as it shows how much traffic you are receiving, but knowing where this traffic is going is equally as important from a monitoring point of view.

**Comment by torkelo** [comment]
This seems like a request to Stackdriver API? not related to Grafana?
