### ISSUE TITLE
failed to store user in cache" error="pq: duplicate key value violates unique constraint \"cache_data_pkey\""

### ISSUE THREAD

**Issue by gjcarneiro** [grafana/grafana#17375]
**What happened**:

Users randomly getting server errors

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Seeing quit a lot of these errors, in the logs:

```
grafana-6b94c79d76-r5c9k grafana t=2019-05-30T14:23:13+0000 lvl=eror msg="auth proxy: failed to store user in cache" logger=context message="failed to store user in cache" error="pq: duplicate key value violates unique constraint \"cache_data_pkey\""
grafana-6b94c79d76-r5c9k grafana t=2019-05-30T14:23:13+0000 lvl=eror msg="failed to store user in cache" logger=context error="pq: duplicate key value violates unique constraint \"cache_data_pkey\""
```

This sounds like get-insert SQL race condition.  We have two replicacas of grafana running in parallel (Kubernetes) writing to the same DB.  This function doesn't look race-free:

```go
// Remember user in cache
func (auth *AuthProxy) Remember(id int64) *Error {
	key := auth.getKey()

	// Check if user already in cache
	userID, _ := auth.store.Get(key)
	if userID != nil {
		return nil
	}

	expiration := time.Duration(-auth.cacheTTL) * time.Minute

	err := auth.store.Set(key, id, expiration)
	if err != nil {
		return newError(err.Error(), nil)
	}

	return nil
}
```

**Environment**:
- Grafana version: 6.2.1 (official docker image)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others: using postgresql 11.2

**Comment by gjcarneiro** [comment]
Ah, this might be a DUP of #17079.  If so, #17079 should be reopened, this is definitely not fixed.

**Comment by tuliodesouza** [comment]
We are experiencing the same error in versions 6.2.0 and 6.2.1 after upgrading from grafana 6.0.2. We use mysql with two instances of grafana running.

**Comment by tuliodesouza** [comment]
BTW, I have just tested running a single instance of grafana but the error persists, indicating that the race condition also affect concurrent requests within the same instance.

**Comment by tudorbarascu** [comment]
Hello,
First of all thanks a lot for grafana, it is amazing.
Hats off..

I also get this on docker 6.2.1. How to reproduce in my case, I have a shared panel embedded in another page that is refreshing at each 5 minutes.

![image](https://user-images.githubusercontent.com/3179646/58793385-a781cd80-85fe-11e9-9e00-66861d46c191.png)

Exactly at the refresh time (after 5 minutes exactly) I get the same error on the panel (``500 Internal Server Error``).
I am using the auth_proxy part with nginx as reverse proxy.

In the pg logs I see:
```
12:47:23.015  [5431] grafana@grafana ERROR:  duplicate key value violates unique constraint "cache_data_pkey"
2019-06-03 12:47:23.015  [5431] grafana@grafana DETAIL:  Key (cache_key)=(auth-proxy-sync-ttl:tudorsusername) already exists.
2019-06-03 12:47:23.015 [5431] grafana@grafana STATEMENT:  INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES($1,$2,$3,$4)
```
and in the grafana logs there's:
```
... lvl=eror msg="Request Completed" logger=context userId=19 orgId=2 uname=tudorsusername method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.1 time_ms=15 size=768 referer="https://......orgId=2&refresh=5m&from=now-6h&to=now&panelId=8"

```
I can provide access to the deployment if necessary.

**Comment by fyang13** [comment]
We just upgraded from Grafana v6.1.6 to v6.2.2, we are start seeing this error right after upgrade:
"auth proxy: failed to store user in cache" logger=context message="failed to store user in cache" error="Error 1062: Duplicate entry 'auth-proxy-sync-ttl:userXYZ' for key 'PRIMARY'"
