### ISSUE TITLE
Single stat "current" value incorrect when missing data from range.

### ISSUE THREAD

**Issue by aknobloch** [grafana/grafana#17376]
**What happened**:
When creating a single stat panel, indicating to show the "current" value, and extending the range of data shown to a time where the metric for the given query is not available, the single stat value shown is not accurate.

**What you expected to happen**:
The "current" value shown should remain consistent.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a metric and push data for it, over some time range.
2. Create a single stat panel for the metric, and set the "visualization > stat" option to "current." 
3. View the panel in an appropriate time range (if you pushed various values for the metric over 5 days, select a time range within those 5 days). The value should be correct (the last pushed value). 
4. View the panel in an inappropriate time range (for instance, if you pushed various values for the metric over the last 5 days, view instead for the last 6 days so there is missing data).  The value is no longer correct, and instead shown something else.

**Anything else we need to know?**:
An image of the correct expectation (with a valid last 7 days time range) is here:
![here](https://user-images.githubusercontent.com/9557120/58640967-3e315000-82c8-11e9-87d2-ed10aad6c112.png) 

An image of the incorrect value (when extending to the last 14 days, which is missing data) is here:
![here](https://user-images.githubusercontent.com/9557120/58641052-6caf2b00-82c8-11e9-8969-3d8a81abedac.png)

In the latter screenshot, we should expect that the value displayed is still the "current" value, which should be 33%

**Environment**:
- Grafana version: v6.1.3 (commit: 9504db8) 
- Data source type & version: Prometheus, 2.10.0
- OS Grafana is installed on: Linux (CentOS)
- User OS & Browser: MacOS Mojave 10.14.4 and Chrome Version 73.0.3683.103 
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
Grafana shows the last value returned by your query, prometheus queries change if you change the time range, things like step can affect that and your prometheus query vector range and functions can also affect that. 

Read the prometheus query docs for more detail. Can't find a "last" aggregation so not sure how you get prometheus to aggregate and pick the last value in a range vector. but maybe max_over_time or some other migration could work if you want the max over a range vector.
