### ISSUE TITLE
FR: Sparkline threshold coloring for Singlestat

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#17372]
**What would you like to be added**:
Adding Sparkline threshold coloring setting for Singlestat widget.

Off:
![Off](https://user-images.githubusercontent.com/1700286/58620922-ee0abb80-82d0-11e9-99dd-6de8a132c98d.png)

On:
![On](https://user-images.githubusercontent.com/1700286/58620928-f4993300-82d0-11e9-9a35-9d660adbf426.png)

**Why is this needed**:
If we have Background, Value, Prefix and Postfix coloring, why Sparkline can not be colored with Threshold coloring option?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
