### ISSUE TITLE
Annotation support for large text

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#17379]
I would like to contain lots of information in an annotation.

for us, a deployment is represented by a large text file containing diffs of json data.
here's an example (note: deployments are often much more text than this)
```
--- ConfigMaps: statsd-config-12574-ops ---
--- Old
+++ New
 {
+ "kind": "ConfigMap",
+ "apiVersion": "v1",
  "metadata": {
   "namespace": "metrictank",
-  "selfLink": "/api/v1/namespaces/metrictank/configmaps/[[ name ]]",
-  "uid": "abc5ea2a-467f-11e9-ac58-42010a96006f",
-  "resourceVersion": "81722021",
-  "creationTimestamp": "2019-03-14T17:36:16Z",
+  "creationTimestamp": null,
   "labels": {

--- deployments: carbon-relay-12574-ops ---
--- Old
+++ New
        "limits": {
-        "memory": "2000Mi"
+        "memory": "1000Mi"
        },
        "requests": {
-        "cpu": "32m",
-        "memory": "400Mi"
+        "cpu": "50m",
+        "memory": "200Mi"
        }

--- deployments: mt-query-12574-medium-ops-a, mt-write03-12574-medium-ops, mt-write02-12574-medium-ops, mt-write01-12574-medium-ops, mt-write00-12574-medium-ops, mt-read03-12574-medium-ops-a, mt-read02-12574-medium-ops-a, mt-read01-12574-medium-ops-a, mt-read00-12574-medium-ops-a ---
--- Old
+++ New
       "hostPath": {
-       "path": "/var/metrictank/",
-       "type": ""
+       "path": "/var/metrictank/"
       }
```

if we post this as an annotation it looks like so:
![annotation](https://user-images.githubusercontent.com/20774/58654889-99436100-8321-11e9-973b-602394534860.png)

note:
* much too narrow. too much text wrapping
* newlines not respected
* text and labels are cut off at the bottom.
* font is not mono-space, making the diff hard to read

this means we can't really use annotations to show deployment details.
if these things were fixed, and the annotation would support large structured text files better, we would be able to use annotations.

**Comment by torkelo** [comment]
You can have links in annotations that are great for usescase like this, just link another system that has this info (GitHub commit maybe?).

**Comment by Dieterbe** [comment]
we don't have another system that tracks this info. we would have to have to either commit them to a private github repo or run our own pastebin style service. seems simpler and better for everyone if grafana could just support this.

**Comment by torkelo** [comment]
Not sure this amount of info fits Annotations that are designed for small messages & links to other systems.  Maybe in the future, if we Grafana had a "deployments" feature to track the info & history of deployments.

**Comment by voiprodrigo** [comment]
I second this request, although my use case is slightly different. I use info from git pulls as annotations, but no diffs. It contains commit id's, messages, authors and changed files. Even for this the annotation panel is just too narrow, and many times there's not even enough vertical space because of that. Just making the box wider would be a great improvement.
