### ISSUE TITLE
legend value sometimes missing (min, current)

### ISSUE THREAD

**Issue by wk66** [grafana/grafana#1737]
Grafana version: 1.9.1
Datasource: graphite
Feature: "min" and "current" value in the legend

In some cases the _min_ value is missing from the legend table. (For my example screenshot I am using metrics hat can be found on any graphite server). You see also in the screen shot, that the _current_ value is missing from the legend table.

![legend values not shown](https://cloud.githubusercontent.com/assets/1059572/7066578/56c48454-dec4-11e4-9e5f-644ecbc9ad7d.png)

**Comment by torkelo** [comment]
Fixed in Grafana 2.0 I think, cant find the issue right now
