### ISSUE TITLE
annotation pattern/keyword search

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#17385]
If would be nice if annotations supported a slightly more advanced search.
Not necessarily full text search like elasticsearch, but I'm thinking of:

1) look for keywords/substrings in the main message (e.g. mentions of a term)
2) look for substrings or patterns in tags. for example if I have a tag like `chan:metrictank-ops` i would like to find these by searching using a tag pattern like `%metrictank%` or just a substring search

1 seems most useful.
2 I can live without. but i would like to know if there's any interest in implementing it. If not, I should probably add support to https://github.com/grafana/memo to add some mapping rules (e.g. if a memo is created in #metrictank-ops slack channel, it should get tag `metrictank`)

**Comment by torkelo** [comment]
Not sure we can do this without adding an indexed backend for Annotations (like Elasticsearch or custom lucene thing)

**Comment by Dieterbe** [comment]
Substring should be doable using the `%` operator in SQL. Will put a bit more load on the database but I think we should empower users :)

**Comment by t-rwe** [comment]
Is it possible anywhere to see which annotations exist in the space of custom (Built-In) Annotations in the UI? Or would that be feasible to add?

Not sure how far that's directly related to this ticket, but I'm frequently struggling to even have an idea on what annotations there are, and/or which tags exist in that space. The feature to add custom annotations is very useful in my view, but as soon as several people as using it, some central view of 'what does even exist, or what's a good tag to use?' is missing to me.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
