### ISSUE TITLE
Support "Table" display for Application Insights query

### ISSUE THREAD

**Issue by silencev** [grafana/grafana#17387]
**What would you like to be added**:
Azure Monitor - Application Insights can support `Table` formatting when switch to "query" mode
![SQL_DB_size_distribution_-_Grafana](https://user-images.githubusercontent.com/24366323/58692048-5be1e080-83c0-11e9-94e8-2c922fb85181.png)

**Why is this needed**:
just like Log Analytics, can be shown as Table.
![SQL_DB_size_distribution_-_Grafana](https://user-images.githubusercontent.com/24366323/58692261-d6126500-83c0-11e9-9cf0-6783d3ce1a64.png)

I know it can display Table right now by switch "Visualization" to "Table".
but it limits the columns number and not easy to use.
Application Insights uses the same query language and should be able to support the Table display

**Comment by tobiaswest83** [comment]
@silencev you're able to get around this limitation by using a [Cross Workspace Query](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/cross-workspace-query), took a bit of faffing around to work out the way to suffix your query, but here's an example of an AI query from traces.

`app('/subscriptions/{{YOURSUBSCRIPTION}}/resourceGroups/{{RESOURCEGROUP}}/providers/microsoft.insights/components/{{APPLICATIONINSIGHTSRESOURCENAME}}').traces
| where severityLevel >= 3
| where message  startswith "Caught exception at service interface method" 
| where timestamp >= ago(120m) 
`

Pleased to say this does exactly what I'd need from having an AI 'Format as Table' option

**Comment by kylebrandt** [comment]
As of 7.1 Application Insights Analytics is now its own service, and the editor is like the one for Log analytics. So there is now the same "format as table" which returns the Kusto table response as is, or "Time Series".
