### ISSUE TITLE
Datasource follows relative redirect relatively to the grafana server

### ISSUE THREAD

**Issue by roflmao** [grafana/grafana#17383]
**What happened**:
Upgrading the backend of a datasource made the enabling a relative Location: instead of absolute. This is part of the plugin https://github.com/sni/grafana-pnp-datasource

**What you expected to happen**:
Follow the url specified in the URL of the datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Setup datasource URL: https://monitoring.X.us/site001/check_mk/ + With Credentials. Press Save&Test and i can see this url in the inspector:
``` http://grafana.x.us:3000/site001/check_mk/login.py?_origtarget=/site001/pnp4nagios/index.php/api```
This should have been
``` https://monitoring.X.us/site001/check_mk/login.py?_origtarget=/site001/pnp4nagios/index.php/api```
**Anything else we need to know?**:
Looks like this is the check_mk commit that changed to relative Location: https://github.com/tribe29/checkMK/commit/856cc3f66f02bb297bb6a9e0dbe884e6a1931882
**Environment**:
- Grafana version: 5.4.3/6.2.1
- Data source type & version: grafana-pnp-datasource: 1.05
- OS Grafana is installed on: Docker
- User OS & Browser: Linux, Chrome

**Comment by torkelo** [comment]
this a problem with your data source, not Grafana

**Comment by torkelo** [comment]
Sorry, was a bit quick. Think the problem is that there is a redirect here. Looks like the your TSDB auth setup is not working
