### ISSUE TITLE
Remove team permissions when user is deleted

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#17392]
Team permissions were added in 6.1. Making it possible for non-admins to control teams. When implementing this we forgot to add cleanup, these permissions will not be deleted when a user is deleted.

https://github.com/grafana/grafana/blob/60ddad8fdbb1345cfb93022e3eb27760beed8fe2/pkg/services/sqlstore/user.go#L522-L541

**Comment by kylebrandt** [comment]
@xlson You know what table these stored in ? There is a permissions row on the team_member table, not seeing any other tables where this information might be, but not very familiar with the schema yet.... `user_auth_token` maybe?
