### ISSUE TITLE
[Feature Request] Metric name split on tables

### ISSUE THREAD

**Issue by josepiratilla** [grafana/grafana#17399]
**What would you like to be added**:
The option to split, based on the metric name, the column of the metric name in the "Table" component. Thus, If selecting the split, and do the split by ".", seting the column headers as "Datacenter", "Server", "metric" and the metrics are:
DC01.server01.CPU: 30
DC01.server07.CPU: 20
DC02.server01.CPU: 25
DC02.server02.CPU: 30
Then the displayed table would be
Datacenter     |  Server    |       Metric       |                Value
DC01 | server01  |       CPU   |                   30
DC01 | server07   |      CPU    |                  20
DC02  |              server01      |   CPU           |           25
DC02   |             server02      |   CPU          |            30

**Why is this needed**:
This would help in creating cleaner tables, and will allow the funcionality to order the table by the node we want. So in the previous example we could order by datacenter, server or metric name easily.

**Comment by yesoreyeram** [comment]
[Boom Table](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel)plugin already does this.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
