### ISSUE TITLE
Cloudwatch datasource with arn authentication not working properly

### ISSUE THREAD

**Issue by gocho1** [grafana/grafana#17396]
**What happened**:
I configured a datasource that I give to Grafana at startup.
```datasources:
  - name: Cloudwatch
    type: cloudwatch
    isDefault: true
    jsonData:
      authType: arn
      assume_role_arn: arn:aws:iam::<account>:role/<rolename>
      defaultRegion: eu-west-1
```
My instance has assumeRole properly set up.
To be sure, I get this role arn with the following during startup of the instance (user_data) : 
```
# get instance Role ARN 
role_name=$(curl http://169.254.169.254/latest/meta-data/iam/security-credentials)
role_arn=$(aws iam get-role --role-name=$role_name | jq .Role.Arn -r)

# sed delimiters are deliberately changed to "#" as the role arn value contains "/"
sed \
    -e "s#<role_arn>#$role_arn#g" \
    /etc/grafana/provisioning/datasources/datasources.yml.src > /etc/grafana/provisioning/datasources/datasources.yml
```
The result is as expected like the conf given above.

When I go to the configuration page : 
- Auth provider and Default region are filled correctly
- ARN is not filled with the value I provided (it is empty)

Test the datasource end up with 
![image](https://user-images.githubusercontent.com/29728596/58717360-5938b880-83cb-11e9-986b-c7a274611932.png)

This issue seems to have been referenced [here](https://github.com/grafana/grafana/issues/16725) but closed with a workaround only (yes, with credentials instead of arn, it works, but that is not the point)

**What you expected to happen**:
When Grafana is started, ARN should be filled with the value provided and testing datasource should be OK

**How to reproduce it (as minimally and precisely as possible)**:
You should have a Grafana set up on AWS, with correct permissions to Cloudwatch (as stated [here] (
(https://grafana.com/docs/features/datasources/cloudwatch/)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.2.1 (commit: 9e40b07)
- Data source type & version: Cloudwatch
- OS Grafana is installed on: AWS amazon ami
- User OS & Browser: Ubuntu, both Chrome/Firefox
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
The property is named assumeRoleArn  

```yaml
 isDefault: true
    jsonData:
      authType: arn
      assumeRoleArn: arn:aws:iam::<account>:role/<rolename>
      defaultRegion: eu-west-1
```

**Comment by gocho1** [comment]
Hi, 
Thanks for your comment, but that should not be closed.
I fixed the parameter name, now the datasource is configured properly in the UI, but I'm still getting the same error during testing.
And dashboard using cloudwatch metrics can not be refreshed.

**Comment by nicholas-santos** [comment]
Having the same problem with Grafana version: Grafana v6.2.2

**Comment by nicholas-santos** [comment]
Figured out a workaround when saving through the UI
1. Set actual role (not assume role) on UI and save, and same on ec2
2. Switch the "Auth Provider" in UI to Credentials file (leave value blank)
3. Save and Enjoy!

**Comment by agguzman** [comment]
I'm having the same issue as @gocho1 , running Grafana 6.2.0 and deployed with helm chart. Grafana is logging this when making a request to test the connection: `lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="AccessDenied: Access denied\n\tstatus code: 403`.

**Comment by Gauravshah** [comment]
@nicholas-santos thanks your trick does work, I am not sure why the issue itself is closed

**Comment by Nuru** [comment]
> Figured out a workaround when saving through the UI
> 
> 1. Set actual role (not assume role) on UI and save, and same on ec2
> 2. Switch the "Auth Provider" in UI to Credentials file (leave value blank)
> 3. Save and Enjoy!

@torkelo Please add this to the documentation somewhere/somehow. I wasted a lot of time on it

**Comment by gocho1** [comment]
For the record, I "reopened" this issue (https://github.com/grafana/grafana/issues/19173) in the hope it will be fixed
