### ISSUE TITLE
[Feature Request] Allow using label_values in query legend

### ISSUE THREAD

**Issue by boxcee** [grafana/grafana#17394]
**What would you like to be added**:
I would love to have the possibility to use `label_values(node_uname_info{instance="{{ instance }}"}, nodename)` in the legend field of a query.

**Why is this needed**:
The prometheus node-exporter for example exports all metrics with the instance as IP address. I don't think this very readable and it would be better to have a name instead of an IP. The metric however has no reference to the name.

By using a query like above, I could map the IP address to another metrics which exports are more human readable name.

**Comment by torkelo** [comment]
Not sure we can support this, Legend can't issue another query, it can only be an expression to use label values your query returns

**Comment by torkelo** [comment]
here is a feature request that I think relates to this general problem https://github.com/grafana/grafana/issues/1153

**Comment by boxcee** [comment]
Thanks
