### ISSUE TITLE
Grafana prometheus pushgateway integration

### ISSUE THREAD

**Issue by sivalearn12** [grafana/grafana#17401]
Hi,
i created custom metric using pushgateway which exposed in URL(http://172.16.15.100:9091/metrics) and also defined targets in prometheus server (http://172.16.15.100:9090).  Later i have configured prometheus datasource pointing to (172.16.15.100:9090/metrics) and defined panel with graph. 

i have deleted the created custom metric from pushgateway. On querying in prometheus , custom metric is not visible. Where as in grafana , custom metric is available eventhough corresponding metric is not available in promethues as well as in pushgateway metric url (http://172.16.15.100:9091/metrics).

what needs to be done to resolve this issue. If the metric is not available in pushgateway means how is it visible in grafana dashboard.

please guide me

Regards,
Ranjani.S

Sorry to ask in github. Unable to  ask questions on our community site: [https://community.grafana.com/](https://community.grafana.com/)  URL is not working.

**Comment by torkelo** [comment]
You need to remove data from your prometheus server. 

Google "Prometheus delete data" 

https://www.robustperception.io/deleting-time-series-from-prometheus

**Comment by sivalearn12** [comment]
Thanks for your support. i have deleted via curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]=metricname" also.. After 5 mins , deleted record available in pushgateway  as well as in prometheus .. 

But grafana always display the deleted record.

**Comment by torkelo** [comment]
Well Grafana does not store it anywhere it just queries Prometheus, so some problem with your delete

**Comment by sivalearn12** [comment]
Might be you are correct. Command used for deleting "curl -X DELETE http://172.16.15.100:9091/metrics/job/vertsim".  . After executing this command , metric not available in pushgateway and prometheus URL. But grafana dashboard show graph with data.

**Comment by Hussain-Ruhullah** [comment]
same here
