### ISSUE TITLE
Template Variables get hide in kiosk mode

### ISSUE THREAD

**Issue by KaveriKrishnaKumar** [grafana/grafana#17419]
I have grafana version 6.1.6...I am embedding grafana chart in my application using iframe...When I give      ?&kiosk or &kiosk=tv in url ,template variable which are above the graph become hidden.. How to hide side and top menu bar without hidding template variables?

**Comment by torkelo** [comment]
vote for this feature request: https://github.com/grafana/grafana/issues/15546
