### ISSUE TITLE
Instrumentation: Add dashboard UID to traces. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#17410]
The Graphite and Prometheus datasource adds the dashboard ID to OpenTracing. Since we introduced UID for dashboards in Grafana we should add that to tracing as well.

**Comment by nicolastakashi** [comment]
Hey Peeps!
Any news about that?
Should be nice if we have the dashboard id being propagated in the baggage so that we can ensure that it will be passed to the upstream services.
