### ISSUE TITLE
clicking on buttons is not working

### ISSUE THREAD

**Issue by MayankSainiTk20** [grafana/grafana#1741]
I am new to Grafana 

I have configured grafana with apache but now clicking on links doesn't reproduce any results.

The URL to the project is http://130.211.152.52/

![untitled](https://cloud.githubusercontent.com/assets/8155434/7074924/c5a37b44-df1b-11e4-8de0-93ced5c63580.png)

**Comment by torkelo** [comment]
added data sources to your config.js ? read 1.9 install and config doc

**Comment by MayankSainiTk20** [comment]
Thanks
 
I worked I have configured the data sources but they are commented out
