### ISSUE TITLE
Graphite query auto-complete breaks when using Graphite without tags

### ISSUE THREAD

**Issue by navops29** [grafana/grafana#17429]
**What happened**:
We have a Graphite datasource with tags feature disabled. This breaks the auto-complete feature in the query editor. Note that this only affects the first part of the metric name. If that's filled out manually, the remaining parts auto-complete as expected. It appears that this is happening because the call to `/tags` endpoint fails.

![image](https://user-images.githubusercontent.com/16399189/58877388-2d307680-86ee-11e9-9e31-79fe25a308c2.png)

**What you expected to happen**:
I expected the auto-complete to show all the top-level metric names in graphite even if the graphite tags are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
Use Graphite DS  that has tag feature disabled. Create a graph in Explore window or in a regular dashboard and click on the metric auto-complete dropdown. The auto-complete will not populate.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: Graphite, 1.1.x
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Chrome/Windows
- Grafana plugins: -
- Others: -

**Comment by PhantomPhreak** [comment]
Having the same issue with grafana 7.3.1 and graphite 1.1.4

**Comment by kwarunek** [comment]
I've hit the same issue with the 7.4.1, the latest working version for me is 7.3.7.

**Comment by ifrost** [comment]
Have you migrated Graphite DB with `django-admin.py migrate`? Please check https://github.com/graphite-project/graphite-web/issues/2356 for more details. 

@kwarunek - default version of Graphite has changed in 7.4.0 (from 0.9 to 1.1). What might be happening in your case is that you're using Graphite 0.9 but after upgrading Grafana to 7.4.1 it's now somehow defaulting 1.1. Could you please check datasource settings if they match the Graphite version you're using?

**Comment by kwarunek** [comment]
@ifrost Thanks, that's the case. Setting 0.9.0 solved problems.

**Comment by PhantomPhreak** [comment]
Tags is an optional feature of graphite, it may be enabled or disabled. Switching graphite version from 1.1.x to 1.0.x or 0.9.x disabling tags feature support and make datasource working, but it also disabling other graphite 1.1.x features, like new functions:
> This option controls what functions are available in the Graphite query editor.

Thus, absence of optional graphite functionality should not affect it's core functionality (metrics retrieving), and decreasing graphite version in datasource settings should be considered as a workaround only.

**Comment by ifrost** [comment]
@PhantomPhreak - yes, the version in data source configuration should match the one you're using. @kwarunek is probably using 0.9 (without tags support) but after the upgrade Grafana incorrectly assumed it as 1.1 (with tags support).

Your case seems to be different, though. You're on 1.1 but graphite-web `/tags` endpoint throws an error suggesting that the database hasn't been migrated. How did you disable tags, btw? By setting `ENABLE_TAGS = False`? Grafana is not aware of that configuration and always queries `/tags` endpoint when version is set to 1.1. This endpoint should not fail however when the database is migrated correctly.

**Comment by PhantomPhreak** [comment]
@ifrost i set  `ENABLE_TAGS = FALSE` in carbon.conf and `TAGDB = None` in local_settings.py, and now `/tags` giving HTTP/200 with empty response, in this case auto-complete works fine. With just `ENABLE_TAGS = FALSE` in carbon.conf we're still getting HTTP/500 and auto-complete breaks.

If by any reason `/tags/autoComplete/tags` responding with HTTP/500, graphite datastorce doesn't show anything in auto-complete, which may be not correct, since tags are optional.

I'm also wondering why tags was enabled in graphite 1.1 by default.

**Comment by ifrost** [comment]
> If by any reason /tags/autoComplete/tags responding with HTTP/500, graphite datastorce doesn't show anything in auto-complete, which may be not correct, since tags are optional.

@PhantomPhreak - just to double check. Have you migrated you database when you upgraded to 1.1? (even though you don't use tags). Looking at https://github.com/graphite-project/graphite-web/issues/2356#issuecomment-420873216 it seems like the database has to be migrated anyway, otherwise the /tags enpoint will fail.
