### ISSUE TITLE
Docs feedback: index.md

### ISSUE THREAD

**Issue by jpietras** [grafana/grafana#17431]
Accessing https://grafana.com/docs with FF v67.0 from Ubuntu/Neon-plasma does not work.
Using chrome from the same machine works.
On FF the "overlay" with "Edit this page", "Request doc changes" and so on is positioned over the documentation, is not movable and makes the page unreadable / unnavigateable.
![Screenshot_20190604_083312](https://user-images.githubusercontent.com/11431160/58883172-80c9a280-86a3-11e9-8559-616bfc81f5dc.png)

**Comment by torkelo** [comment]
Strange, unable to replicate using Firefox 67 on ubuntu 16.
