### ISSUE TITLE
Timeline datepicker 

### ISSUE THREAD

**Issue by kyrianae** [grafana/grafana#17438]
**What would you like to be added**:
a timeline on the bottom of the page with a global time window, and capbility o move the current time window inside
it could be a graph but with fixed time window even if date picker change

**Why is this needed**:
data analysis could be more easy with that, to follow eventmore easy to move on activity time window
it would be

**Comment by torkelo** [comment]
Can you show an example?

**Comment by torkelo** [comment]
A mockup? and describe more why this is useful?

**Comment by kyrianae** [comment]
![Capture d’écran de 2019-06-14 20-44-15](https://user-images.githubusercontent.com/25452007/59537193-6aaeb400-8ee5-11e9-8d11-aca7055eaaa7.png)

functionality seen in jaeger


a graph could have fixed time window (maybe with a switch in the configuration, overriding the time window of the dashboard)
in order to keep a complete view of the situation
selection of time window inside this one will change the time window of the dashboard
> if the timewindow overriding permits you to define complete time window for exaple now() to now() - 
7d
you would habe capability to show events or alerts on the system and zoom only on a part showing other graph and you will be able to move to others events
 this could be very efficient with loki for log analysis too

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
