### ISSUE TITLE
TablePanel: Call rest API when clicking cell link

### ISSUE THREAD

**Issue by kyrianae** [grafana/grafana#17441]
**What would you like to be added**:
define an url to call REST API definig the method GET POST....
and the payload in json with capability to use data of the line (as in url link)
the call could be proxyfied 

**Why is this needed**:
it could add interaction with data and system in order to answer to a recommandation or to fix some errors

**Comment by ryantxu** [comment]
@kyrianae -- This seems interesting, but the details will be a bit complicated to figure out.  I like the idea of configuring a set of "actions" that can be called with parameters similar to how the notification channels get setup.

**Comment by kyrianae** [comment]
2 plugin do what i want but outside table
https://github.com/speakyourcode/grafana-button-panel
https://github.com/cloudspout/cloudspout-button-panel
in table it could able to use cell data for templating and control things via a REST API, it will offer new opportunity in grafana use

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
