### ISSUE TITLE
Are scripted Dashboards still available in Grafana 2.0? 

### ISSUE THREAD

**Issue by dforste** [grafana/grafana#1744]
After looking at the docs. I cannot get scripted dashboards to load anywhere? Have these features been deprecated in the 2.0 release?

**Comment by sknolin** [comment]
They still work, but documentation isn't updated yet.

What I found is you have to put them in the dashboard directory - for centos 6 (and I think others) - /opt/grafana/current/public/dashboards

If you do ajax calls and use the proxy for graphite, do something like this: http://your.grafana.url:3000/api/datasources/proxy/1/

The url to reference is
http://your.grafana.url:3000/dashboard/script/scripted.js
