### ISSUE TITLE
[Cloudwatch] Missing region ap-east-1 (Hong Kong)

### ISSUE THREAD

**Issue by rayvbr** [grafana/grafana#17448]
**What happened**:
Tried to add Cloudwatch monitoring for some elements in ap-east-1. However, the region is missing from the list

**What you expected to happen**:
Be able to select ap-east-1 from the dropdown menu

**Environment**:
- Grafana version: 6.2.1 as well as git HEAD

**Comment by mtanda** [comment]
It would be appeared in list, AWS add the region to their region list.
```
$ aws ec2 describe-regions | jq -r '.Regions[].RegionName' | sort
ap-northeast-1
ap-northeast-2
ap-south-1
ap-southeast-1
ap-southeast-2
ca-central-1
eu-central-1
eu-north-1
eu-west-1
eu-west-2
eu-west-3
sa-east-1
us-east-1
us-east-2
us-west-1
us-west-2
```

**Comment by rayvbr** [comment]
ap-east-1 (Hong Kong) works slight different than other AWS regions, in the sense that it first needs to be enabled, see https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-hong-kong-region/. After it's been enabled on your account, it shows up in `describe-regions`

That said, doesn't the Cloudwatch plugin use a hardcoded list of AWS regions in `public/app/plugins/datasource/cloudwatch/config_ctrl.ts`?

**Comment by mtanda** [comment]
If `describe-regions` show `ap-east-1`, it should be displayed in Grafana.
https://github.com/grafana/grafana/blob/v6.2.2/public/app/plugins/datasource/cloudwatch/config_ctrl.ts#L75

Grafana needs to has a privilege to call "ec2:DescribeRegions".
https://github.com/grafana/grafana/blob/v6.2.2/docs/sources/features/datasources/cloudwatch.md

**Comment by rayvbr** [comment]
The problem is that ap-east-1 is a special region in that it is only listed with `describe regions` if `--region ap-east-1` is passed. 

In other words, calling `aws ec2 describe-regions` will not list it, will calling `aws ec2 describe-regions --region ap-east-3` will. The only exception is people who've set ap-east-1 to be their default region in their awscli config.

See also this issue in the Packer repo, discussing the same issue: https://github.com/hashicorp/packer/issues/7590

**Comment by mtanda** [comment]
hmm, I understand.
To avoid hard coding, I try to generate the region list from `ec2:DescribeRegions` result.
https://github.com/grafana/grafana/pull/12337

But, it doesn't work for the new regions. Need to continue hard coding.
(The situation is little similar for gov regions like `us-gov-east-1`, I already hard code it.)

Would you try to make a PR for the new region?
You need to edit following two places.

https://github.com/grafana/grafana/blob/v6.2.2/pkg/tsdb/cloudwatch/metric_find_query.go#L284-L286
https://github.com/grafana/grafana/blob/v6.2.2/public/app/plugins/datasource/cloudwatch/config_ctrl.ts#L45-L68
