### ISSUE TITLE
Incorrect blank query sent to Elasticsearch when using Text box

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#17442]
**What happened**:
An empty Query is set via the Text Box field variable (via {Textbox:raw} in the Query field). Grafana sends an empty string to Elasticsearch, which will always respond with no matches.

**What you expected to happen**:
An empty query should always send an "*" to Elasticsearch.  This can be observed working properly when using the Query field directly.  When the Query field is empty, Grafana sends an "*" for the Elasticsearch Query_String/Query setting, which results in all documents being returned (no filter).  If a Textbox variable is being used to set the Query field, and it is also empty, the same behavior should occur.

**How to reproduce it (as minimally and precisely as possible)**:
Add a Text Box variable to a Dashboard (name it 'Lucene'), with a Table, using an Elasticsearch 6+ Datasource that has valid documents that will match your current Time Range.

With a refresh, documents will be returned.  Note that the Query field is empty, and the Query Inspector shows an "*" is sent for the Elasticsearch query.

Now set the Query field to ${Lucene:raw}.  With the Text Box empty, refresh your dashboard.  Instead of receiving the same results, no results will be received.  The Query Inspector shows that a "" is sent for the Elasticsearch query.

**Anything else we need to know?**:
Attached screenshots showing the difference in behaviors.

**Environment**:
- Grafana version:  6+ (valid since Text Box was added in 5.x?)
- Data source type & version: Elasticsearch 6+
- OS Grafana is installed on: CentOS 7
- User OS & Browser: NA
- Grafana plugins: NA
- Others:
![ESQuerySuccess](https://user-images.githubusercontent.com/35579731/58912431-03745100-86e8-11e9-9ffd-539973238fd8.jpg)
![ESQueryFailed](https://user-images.githubusercontent.com/35579731/58912446-096a3200-86e8-11e9-974f-61bcafb267bd.jpg)

**Comment by davewat** [comment]
@marefr any chance this could make it into the 6.2.4 release?  Thanks.

**Comment by marefr** [comment]
@davewat unfortunately not. Will add it to 6.2.5 milestone and will be included in that release if we do a v6.2.5. Otherwise v6.3 beta will happen in a couple of weeks which will include this.
