### ISSUE TITLE
Add Amixr as native Notification Channel 

### ISSUE THREAD

**Issue by sisakov** [grafana/grafana#17440]
Dear Grafana team,

**What would you like to be added**:
Please add Amixr native support for alerting. The existing Webhook channel does not allow image uploading. There is a workaround with S3 which is not as straightforward.

**Why is this needed**:
Started using Amixr.io with my Grafana with WebHook but it's not easy to upload images from S3. Native integration could solve the problem.

Thank you,
Stas

**Comment by a37h** [comment]
I am totally signing up for this!

**Comment by aplinxy9plin** [comment]
Nice, I will wait it

**Comment by ohld** [comment]
Since I am the user of Amixr.io and Grafana, I'd like to have this native support. Can't wait for the PR!

**Comment by bergquist** [comment]
We dont want to support more alert notifiers in Grafana unless they are proven very popular. So a PR for adding support for Amixr have a small chance if getting merged right now.

**Comment by codeserfer** [comment]
Anyway I signing up for this issue because integration using webhooks is a big pain

**Comment by sisakov** [comment]
> We dont want to support more alert notifiers in Grafana unless they are proven very popular. So a PR for adding support for Amixr have a small chance if getting merged right now.

Thank you Carl, I also contacted Amixr team according to this feature

**Comment by Matvey-Kuk** [comment]
Long story short:

Amixr.io was acquired by Grafana Labs and became grafana plugin.
Amixr.io was renamed to Grafana OnCall.
Alerting merged integration with Grafana OnCall: https://github.com/grafana/grafana/pull/72021

We could close the issue, thank you!
