### ISSUE TITLE
Dashboard has null uid after upgrade

### ISSUE THREAD

**Issue by robshep** [grafana/grafana#17455]
After upgrade from 4.2.0 to 6.2.1 I have a problem with one single dashboard.
Maybe irrelevant but it happens to be the last one created before upgrade.
Maybe irrelevant but it happens to be the only one with an ampersand '&' in the title.

**What happened**:
Click menu item for dashboard and get "Page Not Found": 404 screen.
 
**What you expected to happen**:
Show that dashboard

**How to reproduce it (as minimally and precisely as possible)**:
TBC

**Anything else we need to know?**:
1. The dashboard link has a path element missing.
    `http://localhost:8002/grafana/d//um3070-ssi-temp-and-pressure`

2. The dashboard has a null uid in the dashboard table. 
```
sqlite> select id,version,slug,title,case when uid is null then '<<NULL>>' else uid end from dashboard;
1|7|bin-sensors-via-st-asaph-server|Bin Sensors (via St Asaph server)|000000001
3|22|office-road-surface-temperature|Office Road Surface Temperature|000000003
5|21|housing-c02|Housing C02|000000005
6|9|42-llanwern-road|42 LLANWERN ROAD|000000006
7|8|2-gloucester-court|2 GLOUCESTER COURT|000000007
8|11|5-gloucester-court|5 GLOUCESTER COURT|000000008
9|8|north-wales-housing|North Wales Housing|000000009
10|9|24-llanwern-road|24 LLANWERN ROAD|000000010
11|1|elt-ultrasonic|ELT Ultrasonic|000000011
12|1|um3070-ssi-temp-and-pressure|UM3070 SSI Temp & Pressure|<<NULL>>
```

**Environment**:
- Grafana version: 6.2.1 from 4.2.0 in docker
- Data source type & version: influxdb
- OS Grafana is installed on: docker
- User OS & Browser: mac chrome
- Grafana plugins: NR
- Others:

**Comment by robshep** [comment]
as a local workaround I set the uid manually, which works

`update dashboard set uid = '000000012' where id = 12;`

**Comment by torkelo** [comment]
Did you have v4 instance running while upgrading one instance to v6? If it was created in v4 after upgrade that could be the problem. 

That is the only other case where we have seen this

**Comment by robshep** [comment]
I'm 99% sure it was down as the version upgrade was done through docker compose image version. 

It was created in v4 last week before upgrade to v6.

**Comment by robshep** [comment]
Sorry, this is our fault. 
After applying this to staging it looks like it has been upgraded before, then downgraded back to v4, (but not restored from backup) as it has evidence in the migration log of E.g. uid generation.
