### ISSUE TITLE
Explore not loading instance data unless you press enter

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#17457]
If you enter the explore view from a panel, or if you click the "run" button in the top right, instance data is not loaded.

It is only loaded if you press enter in the text box:

![o6fBPhPDgv](https://user-images.githubusercontent.com/444037/58969825-2563e700-876d-11e9-889a-b80355c22e80.gif)

Version Grafana v6.3.0-pre (ad744be)

**Comment by kaydelaney** [comment]
@tomwilkie Is this only with Prometheus or does it effect other data sources as well?
