### ISSUE TITLE
"Embed panel" iframe snippet does not work in default configuration

### ISSUE THREAD

**Issue by RalfJung** [grafana/grafana#17458]
**How to reproduce it (as minimally and precisely as possible)**:
* Go to the menu of some panel, selected "share".
* Go to the "embed" tab and copy-pased the HTML snippet.
* Paste that into some other website and load it.

**What happened**:
The iframe does not work, it remains empty.

**What you expected to happen**:
The iframe should load.

**Anything else we need to know?**:
The reason it does not load is that Grafana sets `X-Frame-Options: deny`.
Seems that can be solved with `allow_embedding = true` in the `[security]` section, but the web UI I described above does not say that this will not work unless the admin changes the settings.

**Environment**:
- Grafana version: 6.2.2
- OS Grafana is installed on: Debian
- User OS & Browser: Debian, Firefox
- Grafana plugins:
- Others:

**Comment by ariallyp** [comment]
i hava also this problem ,did you solved this?

**Comment by marefr** [comment]
Please read the v6.2 upgrade notes, there's a new configuration setting regarding embedding Grafana: https://grafana.com/docs/installation/upgrading/#embedding-grafana

**Comment by RalfJung** [comment]
I'm aware, and mentioned that in the issue. But that's very bad UX: as a user of some Grafana installation, I will be offered the "embed" functionality without any indication that it does not work. Then I will wonder for some time why a literal copy-paste of exactly the thing Grafana told me to do does not work. And then I will have to contact my admin to please change the settings.

Basically, the Grafana UI currently tells people to do things that it could know are broken, and that are broken *per default* in every existing and new installation. I think that is a bug.

**Comment by jojoaddison** [comment]
Hi,
I think the allow_embedding config should be set true by default and allow security frightfuls to set to false.

**Comment by baffioso** [comment]
Managed to get this working with the information provided by @marefr 

Since our Grafana is running on https we needed addtional configuration in order to enable users to login through the iframe as described her: https://github.com/grafana/grafana/issues/15714#issuecomment-468953515

Here's is a snippet of our config:
```ini
[security]
allow_embedding=true
cookie_secure=true
cookie_samesite=none
```

**Comment by chewcw** [comment]
for future reference, apart from above settings, we also need this setting:
```ini
[panels]
disable_sanitize_html = true
```
