### ISSUE TITLE
grafana 2.0 - scripted dashboards and updates

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1745]
When updating grafana 2.0beta1 to beta2, I noticed the scripted dashboards don't get moved. 

They are still there in the old version directory /opt/grafana/versions/2.0.0-beta1/public/dashboards so not hard to move.

But it would be better if they appeared in the new one automatically.

**Comment by torkelo** [comment]
Good point did not think about that, this will be solved shortly in beta3,  
I am reworking the rpm and deb packages to better follow HFS (how packages places their files), 
I am going to skip the /opt/versions/  stuff and do as most other packages do, place the binary in /usr/bin , the frontend assets will be in /usr/share/grafana
