### ISSUE TITLE
Gut check on a 'allow oauth signup' PR

### ISSUE THREAD

**Issue by alienth** [grafana/grafana#1746]
I'd like to allow any users coming in via OAuth on my allowed domains to be auto created. However I *don't* want to enable global signup. As such, I'd like to add an option to the oauth settings to allow autosignup for anyone coming in via oauth.

Is this something worth sending a PR for, or are there existing plans to address this type of thing?

**Comment by alienth** [comment]
Changes were pretty simple, and can be found [here](https://github.com/alienth/grafana/commit/51e0f685c3d1b20f1586037e91b11abf5f4c7bf9).

If desired I can clean it up a bit and submit a pull req. Otherwise feel free to close this issue.

**Comment by torkelo** [comment]
Looks good, a PR would be nice
