### ISSUE TITLE
FR: Staircase mode for singlestat sparklines

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#17465]
**What would you like to be added**:
Staircase mode for singlestat sparklines.

**Why is this needed**:
It looks inconsistent when using sparklines with staircase graphs around. So there must be an option to transform "classic" sparkline to staircased sparkline.

![image](https://user-images.githubusercontent.com/1700286/59027139-e44cff00-8860-11e9-97d5-a9109fa76cda.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
