### ISSUE TITLE
Grafana and org admin deleting its current org leaves admin with non-existent current org and unable to set org roles

### ISSUE THREAD

**Issue by padelt** [grafana/grafana#17464]
**What happened**:
Grafana Admin `admin`creates a new organization `neworg1`. That org is now its "Current" org. This user now deletes `neworg1`, then logs out of grafana and logs in again.
`admin` now cannot change org roles despite being Grafana Admin and seeing the users in the org. The column for selecting the user roles for the organization is simply missing.

Looking at `grafana.db` in table `user`, `admin` still has the `org_id` of the now-deleted organization.

**What you expected to happen**:
Either deleting the organization should be prohibited (not preferred) or the admin should be assigned to another (the default?) organization.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Environment**:
- Grafana version: 6.1.4
- Data source type & version: Elasticsearch 6
- OS Grafana is installed on: Ubuntu in Docker
- User OS & Browser: macos, Firefox
- Grafana plugins: -
- Others: AuthProxy with auto signup enabled

**Comment by RyanW8** [comment]
Seems this issue has been open for a while with no movement. Do we know when it'll be picked up?

**Comment by torkelo** [comment]
no eta does not seem to affect that many users so prio has been low from the core team
