### ISSUE TITLE
What frontend files are needed for deployment?

### ISSUE THREAD

**Issue by sunnut** [grafana/grafana#17461]
where is the location of app/plugins directory after build?

**Comment by torkelo** [comment]
All typescript gets built into public/build

**Comment by sunnut** [comment]
@torkelo I also think so. But grafana start error after removing the public/app because of the plugins in it.

**Comment by torkelo** [comment]
yes, it scans it for plugin.json (plugin description files)

**Comment by sunnut** [comment]
@torkelo en, I just didnot want to add the source code in deployment.
