### ISSUE TITLE
FR: Option to move panels between different dashboards

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#17467]
**What would you like to be added**:
"Move to board" option

**Why is this needed**:
Sometimes it may be necessary to move or clone a panel to the other dashboard. It can be done with manual JSON copy-paste, but it will be much more convenient with a special option. 

![image](https://user-images.githubusercontent.com/1700286/59029288-8b806500-8866-11e9-8790-ffbcf18a17e4.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
