### ISSUE TITLE
"Add Panel" button not available for viewers with "viewer_can_edit"

### ISSUE THREAD

**Issue by BertHartm** [grafana/grafana#17475]
**What happened**:
Logged in as a user with viewer rights and viewed an (editable) dashboard. I couldn't use the "Add panel" button as it didn't appear.

**What you expected to happen**:
"Add Panel" button would be there, as I can other wise manipulate / duplicate panels

**How to reproduce it (as minimally and precisely as possible)**:
Enable viewers_can_edit, log in as viewer, look at the top bar

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana v6.1.6 (commit: cf9cb45) 
- Data source type & version: Prometheus / N/A
- OS Grafana is installed on: Linux (grafana published docker container)
- User OS & Browser: Mac / Firefox
- Grafana plugins: None
- Others:

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
