### ISSUE TITLE
meta=true toggle for graphite datasource

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#17472]
for the rollup indication feature, carl requested a metadata toggle on the graphite datasource
(https://github.com/grafana/grafana/issues/11700#issuecomment-498267239)

the rollup indicator data is not available yet in metrictank, but we already started exposing performance stats along with render responses, which uses the same mechanism.

so we need to add the meta=true flag. see https://github.com/grafana/metrictank/pull/1344 for more details

**Comment by torkelo** [comment]
is this expensive, can we always add it in edit mode?

**Comment by Dieterbe** [comment]
not expensive. i would suggest setting it as a datasource config option, so it can be enabled once and left enabled for all queries.

**Comment by Dieterbe** [comment]
it turns out that graphite seems to ignore this flag if it provided.
so after discussing with @daniellee , seems we can simply hardcode to always use it (without any config options), as long as grafana can support both the old format as well as the new format used by MT (see link above)

**Comment by Dieterbe** [comment]
This is now fixed as part of 6.5, we have a type selector with metrictank option, which sets meta=true.
So this can be closed. @ryantxu
