### ISSUE TITLE
Add A way for save, load, sync All panel source

### ISSUE THREAD

**Issue by amirarsalan** [grafana/grafana#17476]
I like to add a new feature that we can add a git repository or ... to grafana and then grafana load or save automatically panel on that. when we edited a panel automatically push to git repository.

We need this feature because we have been the 20-30 panel our monitoring server failed and burn storage then I force to create all 20-30 with json exports by separately! so we can use this feature for any reason.

**Comment by torkelo** [comment]
checkout the dashboard provisioning: https://grafana.com/docs/administration/provisioning/#dashboards 

Otherwise checkout this feature request that includes direct Git integration: 
https://github.com/grafana/grafana/issues/13823
