### ISSUE TITLE
Add Drill Down Support to Gauge and Bar Gauge Panel

### ISSUE THREAD

**Issue by Trebla7th** [grafana/grafana#17473]
**What would you like to be added**:
Drill Down Link support on gauge panels.

I apologize if this is there already, and I'm just missing it.  Asked on SO and got no responses after a few days.  When I add a drill-down link to a gauge panel, it doesn't appear to attach to the panel anywhere.  If I change the visualization of the panel to a graph, a small icon appears in the upper left with the link, but when I switch it back to a gauge visualization, this goes away and the link appears to be inaccessible.

**Why is this needed**:
We have some gauge panels that we'd like to be able to link directly to other dashboards.  This would be quite convenient.

**Comment by afernando79** [comment]
I can see the option to add the "Drilldown Links" is available for the panel's "General" tab, but as the OP states, it does not appear in the upper left of the panel. This facility is extremely useful and reduces the amount of work an individual would need to do when searching for relevant detailed info.

**Comment by troyskigit** [comment]
Same issue here. I'd love to use the drill-down with bar gauge, but the link does not appear. Works ok with singlestat gauge.

**Comment by noliverio** [comment]
I found a workaround for this, if you add any description and the info icon will appear. Add a whitespace and the drill down links will be the only thing to render.

With that in mind this should be reclassified as  type/bug, not type/feature-request.

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/18918
