### ISSUE TITLE
iPad keyboard works poorly in expression field

### ISSUE THREAD

**Issue by kbreit** [grafana/grafana#17478]
**What happened**: While trying to type in a new graph’s expression text field, I noticed the on-screen and external keyboards work poorly. It is a mixture of slow text input and an inability to navigate using the arrow keys. The cursor move shortcuts using the on-screen keyboard seem to work poorly as well.

**What you expected to happen**: Keyboard works as well as any other application.

**How to reproduce it (as minimally and precisely as possible)**: Create new graph, enter expression editor text field, try to type.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: n/a
- OS Grafana is installed on: Docker on Linux
- User OS & Browser: iOS on 12.3.1, iPad Air 2
- Grafana plugins: None that I know of.
- Others: n/a

**Comment by torkelo** [comment]
What data source & expression field do you mean?

**Comment by kbreit** [comment]
I should say it's the query editor. The data source is Prometheus.
