### ISSUE TITLE
Grafana iframe return a refreshed 'from' and 'to' values after zoom in/zoom out of graph x axis

### ISSUE THREAD

**Issue by denisb411** [grafana/grafana#17482]
Is there a way I can do it with the latest version of Grafana?

**What would you like to be added**:
Grafana return from/to values after applying any king of zoom on an iframe graph.

**Why is this needed**:
I have 2 graphs being displayed on screen and I want them x axis synced

**Comment by torkelo** [comment]
You can control time range in the url you use when you load the iframe. 

Syncing across different iframes is something you will have to build yourself

**Comment by denisb411** [comment]
@torkelo 

I am aware of this, but there's no way I can read the updated from/to values after user perform clicks. There isn't any html tag being updated. Not event the 'src' attribute from iframe.

Currently my iframe is:

`http://146.250.180.213/grafana/dashboard-solo/script/script_graph.js?scenario_id=cell_avail&cell_id=ESICAS23C_ESICAS23&refresh=5s&orgId=1&panelId=2&from=1555045266010&to=1555168469864&var-cell_id=ESICAS23C_ESICAS23&var-scenario_id=ESICAS23C_ESICAS23`

Is this wrong?

**Comment by denisb411** [comment]
@torkelo 

I didn't get the 'you have to build yourself' thing as I researched and am almost sure there's no way to do without modding Grafana.

It's not fair you just simply ignore and close this feature request without making sure that it's clearly possible with current latest version.

**Comment by mario-donnarumma** [comment]
I'm looking for a solution too. @denisb411 did you manage to solve your issue?

**Comment by denisb411** [comment]
@mario-donnarumma Yes! But I really don't know if it's the righest way of doing it.
I used windows.postmessage() for a cross-window communication. I had to differenciate the different types of clicks (rapid or click and drag for zoom in/out).

It's a little annoying to explain... check this:
https://gist.github.com/denisb411/87dfb3d094d5abd3dbe50619c604aaa7

**Comment by carlosaxpires** [comment]
There is a simple solution for this:

- considering this: https://stackoverflow.com/questions/56496342/how-to-get-iframes-refreshed-src-after-interacting
- considering we can detect events inside Grafana iframe by subscribing iframeDocument.body

We can simply use mouseup as the trigger and access iframe.contentWindow.location.href which contains the updated url (even if href doesn't change), by doing this:

`this.iframeDocument.body.addEventListener('mouseup', (e) => {`
`                setTimeout(() => {`
`                    const updatedUrl = iframe.contentWindow.location.href;`
`                   // Do something with updatedUrl `
`                });`
`             });`
