### ISSUE TITLE
Reverse proxy with django

### ISSUE THREAD

**Issue by mindfuucker** [grafana/grafana#17484]
All the guides and tutorials found about this topic are made for versions <6. I cant get it working. I got different results by changing X-WEBAUTH-USER to X-WEBAUTH-APP-USER, both of the results are here below:

django: 123.234.123.234:1112
grafana: 123.234.123.234:3000

**grafana.ini**
[server]
protocol = http
http_addr =
http_port = 3000
domain = localhost
;enforce_domain = false
root_url = %(protocol)s://%(domain)s:%(http_port)s/

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
;header_name = X-WEBAUTH-APP-USER
header_property = username
auto_sign_up = true
ldap_sync_ttl = 60
whitelist = 127.0.0.1
;headers = Email:X-User-Email, Name:X-User-Name

django view:
 
    class GraphanaProxyView(ProxyView):
        upstream = 'http://localhost:3000/d/'

        def get_proxy_request_headers(self, request):
            headers = super(GraphanaProxyView, self).get_proxy_request_headers(request)
            headers['X-WEBAUTH-USER'] = request.user.username
            print(headers)
            print(self.upstream)
            return headers

**What happened**:
When reaching for http://123.234.123.234:1113/graf/Z6jsNEGZz/landing-page

![image](https://user-images.githubusercontent.com/5075692/59109153-d7054280-893c-11e9-969c-80f4e6d05f3f.png)
![image](https://user-images.githubusercontent.com/5075692/59109831-141e0480-893e-11e9-9b8a-ac094d40cc09.png)

![image](https://user-images.githubusercontent.com/5075692/59109199-e8e6e580-893c-11e9-80df-4a6970a91e5e.png)

**What you expected to happen**:
An embedded dashboard to appear. 

**How to reproduce it (as minimally and precisely as possible)**:
Followed this guide: [link](https://gist.github.com/feroda/c6b8f37e9389753453ebf7658f0590aa)

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: PostgreSQL 11
- OS Grafana is installed on:Ubuntu 18.04
- User OS & Browser: Firefox
- Grafana plugins: None
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this but we currently don't have any other reported issues with the reverse proxy so this might be specific to Django. Please look in our [community site](https://community.grafana.com/) and see if you can get any help there or in the official Slack channel: grafana.slack.com.
