### ISSUE TITLE
Grafana and Supervisord

### ISSUE THREAD

**Issue by Herezad** [grafana/grafana#1748]
I try to run the Grafana by a supervisord, but I got error:
[setting.go:286 initLogging()] [E] Unknown log mode: console

My supervisord grafana conf:
[program:grafana]
command=/opt/grafana/current/grafana --config /etc/grafana/grafana.ini web
autorestart=true
startretries=10

How can I run properly Grafana by Sypervisord?

**Comment by torkelo** [comment]
set working directory to /opt/grafana/current

**Comment by Herezad** [comment]
It work now perfectly.
Thank you very much.
