### ISSUE TITLE
Influx: Add a start page for logs in explore

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17499]
**What would you like to be added**:
Add a start page (cheat sheet) about what to do to get started (select measurement, then select field) when mode `Logs` have been selected and there are no measurement or field selected.

**Why is this needed**:
To guide the user in how to visualize logs.

**Comment by kaydelaney** [comment]
@marefr To clarify: Do we only want the cheat sheet for the `Logs` mode?

**Comment by marefr** [comment]
@kaydelaney that's a good questions. I actually came to think about that after opening this issue. Currently there are only a startpage used by Prometheus and Loki datasources and they only has Metrics or Logs as mode, not both.

Think it's weird to show the start page for the influx datasource metrics mode since it's using the existing angular query editor. We probably want to be able to have one start page for logs and one for metrics, but we can definitely start with showing the same startpage for both metrics and logs.

We should probably create a new issue for the below stuff:

Think we need a similar solution as we did for query fields. You can use `setExploreQueryField` or `setExploreMetricsQueryField` or `setExploreLogsQueryField`. Depending on what mode is active it will try to use a query field for that mode, if that doesn't exist it will try the general query field and if that don't exist it will use the angular query editor. For reference:
https://github.com/grafana/grafana/blob/fcd2fb8b04a9baeba7a50e4f5645a00c7865d5d6/public/app/features/explore/QueryRow.tsx#L122-L128

Influx datasource plugin export using `setExploreLogsQueryField` example:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/module.ts#L34
