### ISSUE TITLE
Explore: Enhance adding a new filter in the adhoc filter field

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17498]
**What would you like to be added**:
When adding a new filter in the adhoc filter field it would be nice if it worked similar to existing adhoc filters in dashboards, i.e. operator and value fields are not displayed until the selection before have been made, see animation below for example.

![Peek 2019-06-10 15-18](https://user-images.githubusercontent.com/1668778/59198073-2ba1fb00-8b93-11e9-97ba-2a983b2f8c81.gif)

**Why is this needed**:
Makes a better user experience.

**Comment by aocenas** [comment]
Hey, @marefr will need a bit more details here or maybe this is just too old? Not sure what is meant by adhoc filter in explore. Did we have something like that before?

**Comment by marefr** [comment]
@aocenas this was created with Influxdb logs query field in mind. 

Current logs query field renders three drop downs when clicking +/add:
![image](https://user-images.githubusercontent.com/1668778/72799770-3a32b380-3c46-11ea-997e-34ca9df66330.png)
