### ISSUE TITLE
Share Panel Direct link rendered image function missing legend

### ISSUE THREAD

**Issue by tuxinaut** [grafana/grafana#1749]
If I use the **Share Panel Direct link rendered image** function the complete legend will not displayed.

Grafana Version: **v 2.0.0-beta2**

![error](https://cloud.githubusercontent.com/assets/722482/7089433/01b2c72c-df9c-11e4-8065-c439759ea4a4.png)

**Comment by torkelo** [comment]
fixed!

**Comment by tuxinaut** [comment]
Nice thank you :smile:
