### ISSUE TITLE
Explore: Enhance adhoc filter field behavior when measurement and field have been selected

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17497]
**What would you like to be added**:
When a measurement and field have been selected, it should be enough to only display the plus-button and not the "choose, choose, choose" as it currently works.
![image](https://user-images.githubusercontent.com/1668778/59196818-052e9080-8b90-11e9-9a19-910bcaee0eff.png)

**Why is this needed**:
To optimize for visualizing logs without inviting the user to think that filtering by tags is a requirement and this should also make it more user friendly.

**Comment by davkal** [comment]
Good idea, should add label to say what user is adding when clicking Plus
