### ISSUE TITLE
Grafana with My SQL with left inner join not working?

### ISSUE THREAD

**Issue by groyee** [grafana/grafana#17503]
I am trying to do some super easy, query two tables:
1. Fusion_Users (contains only one column of email)
2. Fusion_OUT (contains the email column from the previous table + more columns, like vacation dates)

All I want to do is show a basic graph of user with and without vacation. For users with no vacation it should show 9. for others I should show 9 minus the amount of day they took off.

In SQL it took me 10 seconds. 

Here are I am trying for the last 3 days with all possible permutations, nothing seems to be working.

I get only users that have date off.

Is there a bug?

This is my last version"

![image](https://user-images.githubusercontent.com/194016/59203450-ce28a100-8bc8-11e9-827b-33b60b3aae4e.png)

Here is another version:

![image](https://user-images.githubusercontent.com/194016/59204964-febe0a00-8bcb-11e9-88cd-77ee00374011.png)

**Comment by torkelo** [comment]
Looks like your query returns nil for the time_sec column , this is not supported for a time series query

**Comment by groyee** [comment]
That's for left inner joins for, right? What am I missing?
