### ISSUE TITLE
List or regex to exclude items from template queries

### ISSUE THREAD

**Issue by ohTHATaaronbrown** [grafana/grafana#1750]
In the template variable editor, I'd like to have the ability to have a query like `stats.gauges.mycompany.instance.*` and then another textbox to have either a regex (or at least a value list) to identify items i'd like to **exclude** from the variable's selection list

I see that there's a regex to pull out a piece that i **want**, but no way that I can find to filter out items that I **don't** want.

**Comment by torkelo** [comment]
if your using graphite cant you do that with a glob expression?

**Comment by ohTHATaaronbrown** [comment]
Hmm... I thought globs were only for positive matching, not for excluding.  Am I missing something there?

**Comment by torkelo** [comment]
not sure either

**Comment by ohTHATaaronbrown** [comment]
Nope, doesn't look like it.  I can only glob positively:

I can do something like `stats.gauges.dovetail.instance.*{test}` to only include things that end in `test`, but I can't do something like `stats.gauges.dovetail.instance.*!{test}` to **exclude** things that **end** in `test`.

**Comment by gerrickw** [comment]
Not sure if you have tried this, but have you tried using exclude or grep on the graphite side?

http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.exclude

**Comment by ohTHATaaronbrown** [comment]
Yeah. That's in the render API, and it works great down in chart panels.

However, I'm talking about the template variable queries that produce the template value dropdowns in the top section of a dashboard.

Those don't go through the render API, so you can't use exclude.

**Comment by dgarbus** [comment]
I also tried to use a negative lookahead without success and subsequently found this issue. I'd really like to see a way to exclude certain things from the list when using templating.

**Comment by lancehunt** [comment]
I just ran into this same issue with negative lookahead regex using Graphite backend.

**Comment by apriendeau** [comment]
So in the regex field, why can't you do something like this `/^(?!.*foo$).*$/`

**Comment by aidylewis** [comment]
I have tried this, which passes in my regex tester, but fails in Grafana (InfluxDB backend)
/gatling.+(?!allRequests).+all.percentiles50-0/

**Comment by lancehunt** [comment]
As @ohTHATaaronbrown mentioned above, negative look aheads dont seem to be respected.  They don't error, they just dont work.

**Comment by ohTHATaaronbrown** [comment]
@torkelo ping.

**Comment by torkelo** [comment]
I use regular javascript regex expressions so anything that works with that should work

**Comment by ohTHATaaronbrown** [comment]
but it doesn't.  that's what i said in the first place.  no error, but **no filtering, either**

**Comment by torkelo** [comment]
@ohTHATaaronbrown then please fix it :)
https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateValuesSrv.js#L223

**Comment by ohTHATaaronbrown** [comment]
OK, I think I finally figured out the problem, and it's operator-headspace.

this regex filters out everything that ends in `test`:

```regex
/^(?:.{0,3}|.*(?!test).{4})$/
```

regex is easy to get to match, but **hard** to get to **not** match.
