### ISSUE TITLE
Annotation  API PATCH fails for 5.4

### ISSUE THREAD

**Issue by gclair** [grafana/grafana#17508]
**What happened**:
HTTP API Annotation doesn't work, fails to update annotation.

**What you expected to happen**:
200 OK or more detailed failure message 

**How to reproduce it (as minimally and precisely as possible)**:
CURL - Update with PUT to show valid Annotation ID
`curl -H "Authorization: Bearer eyJrIj....<Is Valid>...iOjF9" -H "Content-Type: application/json" -d '{"timeEnd":1560176061249}' -X PUT "https://<GrafanaHost>/api/annotations/69"
{"message":"Annotation updated"}% `

Curl with PATCH attempt 

`curl -H "Authorization: Bearer eyJrIj....<Is Valid>...OjF9" -H "Content-Type: application/json" -d '{"timeEnd":1560176061249}' -X "PATCH" "https://<GrafanaHost>/api/annotations/69"
{"message":"Not found"}%`    

Always a 404, logs don't show anything other than a 404 was issued to the request.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v5.4.3 (6539180)
- Data source type & version: InfluxDB
- OS Grafana is installed on: Centos 7.6.1810
- User OS & Browser: Linux/CURL
- Grafana plugins: None
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this. The Patch VERB was introduced with #15197 so there is no Patch VERB for v5.4.3 of Grafana and unfortunately the documentation for v5.4 of Grafana doesn't mention this.

**Comment by gclair** [comment]
![Grafana-annotation-5 4-doc](https://user-images.githubusercontent.com/5864402/59269292-19709d00-8c25-11e9-9cbb-a53c86232394.png)

au contraire mon frère ..

**Comment by hugohaggmark** [comment]
Sorry about that I was unclear in my response, I meant to say that unfortunately the documentation for v5.4 of Grafana doesn't mention that this is only working from version #15197.
