### ISSUE TITLE
Influx: Adhoc filter keys/values is not filtered by measurement in explore logs field

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17507]
**What happened**:
Used the adhoc filter in the influx logs query field and got tag keys suggestion from all measurements.

**What you expected to happen**:
To only get suggestion of tag keys from selected measurement.

**How to reproduce it (as minimally and precisely as possible)**:
1. Navigate to explore
2. Select influx as datasource
3. Select logs as mode
4. Select measurement and field
5. Choose tag and noticed the query to influx is made without the selected measurement

**Comment by digrich** [comment]
Can this feature be available to dashboard adhoc filter (under template variables) also ?

**Comment by hugohaggmark** [comment]
> Can this feature be available to dashboard adhoc filter (under template variables) also ?

Hi @digrich , we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/) You might also file your question as a Feature Request with a detailed description on how that is expected to work.

All the best
