### ISSUE TITLE
Influx: Clear All doesn't reset/clear explore logs field

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17506]
**What happened**:
Clicked on Clear All in Explore using Influx and mode logs and the logs visualization got cleared.

**What you expected to happen**:
That the query field is reset/cleared together with logs visualization getting cleared.

**How to reproduce it (as minimally and precisely as possible)**:
1. Navigate to explore
2. Select influx as datasource
3. Select logs as mode
4. Select measurement and field and click on Run Query
5. Click on Clear All

**Environment**:
- Grafana version: master 4121b5d

**Comment by davkal** [comment]
Same for the row clear button (x)
