### ISSUE TITLE
"Previous Month" time range not showing previous month's data

### ISSUE THREAD

**Issue by JamesHealey94** [grafana/grafana#17502]
**What happened**:
I have a graph with one value each day (midnight).
I set the Grafana time range to "Previous month".

Expected: Values for 1st to 30th of May are shown. Total would be the month's total.

Actual: Values for 2nd May to 1st June are shown (although last value is only visible when hovering, so hard to spot visually). Total is different to May's total.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: Graphite 1.1.5
- User OS & Browser: Windows 10, Chrome

**Comment by JamesHealey94** [comment]
![image](https://user-images.githubusercontent.com/633125/59203215-082c7f80-8b96-11e9-8fa2-21c8ab615a36.png)

**Comment by torkelo** [comment]
unable to replicate, when UI try "Previous month" the time range is may1 to may31

**Comment by torkelo** [comment]
https://play.grafana.org/d/KaH58WnWz/prev-month?orgId=1

**Comment by JamesHealey94** [comment]
Experimented a little more on this:
I had the browser time to 'UTC' which produced the strange results. I was expecting 'from' to be inclusive and 'until' to be exclusive.
When I set the timezone to Local browser time (UK time) - It works as expected. Problem solved.
