### ISSUE TITLE
HTTP Server Default Response Headers

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#17509]
We need to add these headers to the default headers:

* X-XSS-Protection   (might need option for this, not sure yet)
* X-Content-Type-Options
* Strict-Transport-Security (If https is enabled)

add them here: 
https://github.com/grafana/grafana/blob/master/pkg/middleware/middleware.go#L235

**Comment by kylebrandt** [comment]
Notes:
  * Docs on Strict-Transport-Security: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
 * X-Content-Type-Options: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
 * X-XSS-Protection: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

Response headers seem to be added in the middlware at https://github.com/grafana/grafana/blob/master/pkg/middleware/middleware.go#L235

**Comment by kylebrandt** [comment]
Question to answer: Do we want HSTS preload on Strict-Transport-Security?

**Comment by kylebrandt** [comment]
TODO: Make new setting to enable/disable these headers.

**Comment by bergquist** [comment]
> Strict-Transport-Security (If https is enabled)
I'm not sure we should default to using that if https is enabled. 

The other two can be enabled by default I think. So the setting should be to disable them. Ex. `disable_x-xss-protection`

I prefer default values for bools to be false. That gives them a default purpose even if misconfigured. https://dave.cheney.net/2013/01/19/what-is-the-zero-value-and-why-is-it-useful

**Comment by DanCech** [comment]
No preload for hsts I think, unless we want to make it a configurable option

**Comment by kylebrandt** [comment]
Also for Transport-Security, there is an include subdomains, that something enterprise customers might use?

**Comment by kylebrandt** [comment]
@bergquist Do you have a specific reason for not enabling transport security by default. I'm not sure a practice of default values being false is the right thing to do when it comes to security.

**Comment by bergquist** [comment]
behavior can be enabled by default. settings can be used to disable default behavior.
Ex https://github.com/golang/go/blob/go1.12.5/src/crypto/tls/common.go#L526

**Comment by DanCech** [comment]
Honestly I think that inverting the setting to make the default value false just creates confusion because you end up with a double-negative. There are a lot of situations where I find myself needing to check the docs every time to figure out whether I want true or false, and this seems like something we should discuss and form a consistent policy around for new settings. It sounds like for the hsts header it should be a text setting so the user can specify whether they want preload, subdomains, etc

**Comment by torkelo** [comment]
Agree that having these settings be inverted feels wrong, I know we have already some "disable" named settings where the default is false. 

But in this case we have a default behavior (adding security headers), so the setting can be enabled by default, and to disable it you set the feature to false. 

Is there a strong argument to not have bool settings that are default true?

**Comment by bergquist** [comment]
**TLDR**; I'm not gonna die on this hill for configuration settings as we use `.MustBool(true)` for all the values. Default values for configurations might also change over time. E.g. `[alerting]enabled`. 

For internal structs that have bool fields, let's use false as the default behavior. 
By not setting the value it fallback to the default behavior. 

```go
tr := &http.Transport{
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}
```
If the `tls.Config` had a bool with true as default behavior. E.g
```go
tr := &http.Transport{
    TLSClientConfig: &tls.Config{VerifySSLCert: false},
}
```
Forgetting to set that value now have a significant impact as you might be vulnerable to man in the middle attack without knowing it. The default value for bool is `false` hence, the default value for security settings should be `false`.  

https://github.com/grafana/grafana/blob/master/pkg/middleware/middleware.go#L33 is a good example of `false` as a default value. `false` is not just uninitialized, it has a purpose even if unset. 

> creates confusion because you end up with a double-negative

Totally agree. In most cases, it means that we need to spend some extra time on the variable name. But its not always possible to get right. I dont think 
```go
DisableXSSProtectionHeader         bool
DisableContentTypeProtectionHeader bool
``` 
are hard to understand. But they arent good either.
