### ISSUE TITLE
No way to add data source in Grafana 2

### ISSUE THREAD

**Issue by alexnederlof** [grafana/grafana#1751]
I'm running the Grafana v 2.0.0-beta2 in the provided docker container, but I cannot find the described way to add data sources in the menu. Because there's also no HTTP documentation, I'm kinda stuck now :stuck_out_tongue_closed_eyes: . 

Am I missing something? Or is it just not possible *yet*.

BTW :heart: Grafana 2. Finally allows us to have a better, more secure set-up. Keep up the good work!

**Comment by torkelo** [comment]
Can you open the sidemenu, you should have a Data Sources option there. You open the sidemenu by clicking on the grafana icon in the top right of the header.

**Comment by alexnederlof** [comment]
AH now I see. Thanks!

**Comment by alexnederlof** [comment]
That's the data import. I have no link to the data sources page.

However, from the the JavaScript I extracted that I can add datasources from `/datasources` url so I went there. Immediately I get a `401` on `/api/datasources` and I am not able to select new datasources to add because I also get a `401` on `api/datasources`. 

So my problem is twofold:

1. There's no button to go to the `/datasources` dashboard. Also searched the HTML, cannot find it.
2. Cannot add datasources because I get a 401, even though I'm a Grafana Admin.

So probably this has something to do with authorization. Here's what I've done since running the docker image.

1. Logged in as admin
2. Changed the password
3. Added myself as a new user
4. Made myself admin
5. Deleted the original admin

**Comment by torkelo** [comment]
what is you organization role? hm.. depending on your server config,  the new user you created probably got added as a viewer to the default organization. 

Hmm not sure really what happen, need to run through your scenario, you could fix it by creating a new organization (using the side menu or drop down )

**Comment by alexnederlof** [comment]
Thanks! I'll try that this weekend
