### ISSUE TITLE
Clarify dashboard provisioning name

### ISSUE THREAD

**Issue by sni** [grafana/grafana#17516]
It seems like the dashboard provisioner name must be unique, but no word about that in the example configuration or in the logfiles when you use the same name multiple times.

```
apiVersion: 1

providers:
  # <string> provider name
- name: 'default'
```

The example `default` does not look like you need to change it.

What happens if you use the same name multiple times is a bit random. Sometimes the provisioned dashboards appear, but if you open them you get a "dashboard not found" error. Sometimes after multiple reloads they finally load.

**Suggestions**
1. Either remove the "name" parameter completly. Right now, it does not look like it adds any value.
2. at least log an error if the same name is used twice.

**Comment by hugohaggmark** [comment]
Thank you for reporting this, we'll try to update the documentation.
