### ISSUE TITLE
Current value in legend isn't updated when unit is changed in edit mode

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#17518]
**What happened**:

I was configuring a panel:
* Enabled table legend, right hand side, show current, it showed values like 0.025
* Changed unit to second

The current value did not change to reflect the new unit, only after I disabled and re-enabled show current.

**What you expected to happen**:
* Current values are updated in the preview to reflect the new unit

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: Prometheus 2.10.0
- OS Grafana is installed on: Ubuntu 18.04 (Docker)
- User OS & Browser: Arch Linux, Firefox 69.0a1

**Comment by torkelo** [comment]
Might need to add y-axis units to legend prop to make sure it re-renders:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts#L117

**Comment by dprokop** [comment]
@daenney Thanks for opening this issue. The problem is now solved with Grafana 7.1.x
