### ISSUE TITLE
Question re: Azure AD

### ISSUE THREAD

**Issue by jtpryan** [grafana/grafana#17529]
I asked this in the Community but got no response back.

I set up Grafana with our security people to authenticate against Azure AD. They gave me the following pieces of information:

directory id:
appid: (oauthid)
objid:
oauthkey:
a URL. " http://grafana.company.com/login/generic.oath"

In the grafana.ini file I am supposed to (according to Grafana help) modify the following section:
{auth.generic.oauth}
;enabled = false
;name = OAuth
;allow_sign_up = true
;client_id = some_id
;client_secret = some_secret
;scopes = user:email,read:org
;auth_url =
;token_url =
;api_url =
;team_ids =
;allowed_organizations =
;tls_skip_verify_insecure = false
;tls_client_cert =
;tls_client_key =
;tls_client_ca

Other then the appid being correlated to the client ID I don’t know where to put in the rest of the info that was provided to me and that I assume I will need. Can anybody assist as to where to go from here?

**Comment by hugohaggmark** [comment]
Thanks for reporting this. Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by jtpryan** [comment]
I have asked this on the community site with no answers.  Is there anyway to open a ticket or get help from Grafana?
