### ISSUE TITLE
Evalute multiple alert conditions per series

### ISSUE THREAD

**Issue by urusha** [grafana/grafana#17520]
**What happened**:
Influxdb query with multiple series and multiple alert conditions, like this:
![image](https://user-images.githubusercontent.com/1746504/59267248-38792a00-8c39-11e9-81dd-3debbbc01e18.png)
Get firing alert when one series meets the first condition and another series meets the second.

**What you expected to happen**:
Get alert when a particular series meets booth conditions.

**How to reproduce it (as minimally and precisely as possible)**:
See what happened.

**Anything else we need to know?**:
If the current behavior is a feature, then consider this issue as a feature request - Implement multiple alert conditions per series within the same query (or even across all the queries), evaluating conditions for every series with the same name separately.
A partial workaround is using `WHEN` statement https://github.com/grafana/grafana/issues/2674 , but this doesn't support aggregation functions ( https://github.com/influxdata/influxdb/issues/5266 ), also alert's and query's intervals / aggregate functions could differ.
This could also be related to https://github.com/grafana/grafana/issues/7832 since this feature could be a part of the brand new alerts design (hope we'll get it).

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: influxdb 1.7.6
- OS Grafana is installed on: debian 9, amd64
- User OS & Browser: linux, firefox
- Grafana plugins:
- Others:

**Comment by bergquist** [comment]
We are currently in an early phase of designing the next generation of Grafana alerting. So we won't implement this in the current version of Grafana alerting. I'm not sure how we will solve the issue like this but we will make sure to solve the underlying problem. I'm leaving this open as a reminder for us.

**Comment by gaeldb** [comment]
Hi @bergquist 
Any move on this?

**Comment by johntdyer** [comment]
@bergquist  are you guys still designing the next generation of monitoring ?  Do you have any timeline on when we might see that ?

**Comment by valerii-vorobiov** [comment]
Hey @dergquist 
do you have any updates on that?
we have the same problem on Grafana version v8.2.3 (fb85ed6912)

**Comment by armandgrillet** [comment]
This is possible in Grafana Alerting using classic conditions.
