### ISSUE TITLE
unable to install grafana 2.0 beta rpm

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1752]
Hi Torkel:

I am getting these errors:

rpm -Uvh grafana-2.0.0_beta1-1.x86_64.rpm
Preparing...                ########################################### [100%]
   1:grafana                ########################################### [100%]
insserv: warning: script 'K01esmrc' missing LSB tags
insserv: warning: script 'esmrc' missing LSB tags
insserv: script netbackup.01-27-15.12:25:15: service netbackup already provided!
insserv: Service network is missed in the runlevels 4 to use service vxpbx_exchanged
grafana                   0:off  1:off  2:on   3:on   4:on   5:on   6:off
chown: invalid group: `grafana:grafana'
chown: invalid group: `grafana:grafana'
error: %post(grafana-2.0.0_beta1-1.x86_64) scriptlet failed, exit status 1

I've created the grafana user. Any ideas?

**Comment by gsaray101** [comment]
I've added the group, installation did not give any error but when I try to start:

service grafana start

I get this:

service grafana start
Starting the process grafana [ OK ]
start-stop-daemon: unrecognized option '--background'
Try `start-stop-daemon --help' for more information.
grafana process was started [ OK ]

ps -ef | grep -i grafana is not showing

**Comment by gsaray101** [comment]
sorry, for all these notes. I was able to start it it. In which file you point grafana to graphite? I dont see config.js like on the previous versions.

**Comment by gsaray101** [comment]
I don't see datasources in the side menu
![datasources](https://cloud.githubusercontent.com/assets/3009225/7093729/ba00f456-df89-11e4-9945-36b6508991c8.png)

**Comment by torkelo** [comment]
what os and version?

**Comment by gsaray101** [comment]
Suse 11.3
