### ISSUE TITLE
How do you define plugins in grafana 2.0

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1753]
I had a pie plugin in grafana 1.9 and I had to include it in config.js as this:

plugins: {
      // list of plugin panels
      //panels: [],
      panels: {
             'pie': { path: '../plugins/pie' },
             'R': { path: '../plugins/R' }
              },

How could I insert pie plugin in grafana 2.0?

**Comment by torkelo** [comment]
panel plugins has yet be implemented, will probably come in v2.1

**Comment by gsaray101** [comment]
great, thank you
