### ISSUE TITLE
Backend: Upgrade to golang 1.12.6

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#17533]
https://groups.google.com/forum/#!msg/golang-announce/dNU0sAdX65I/3psx7_OqAQAJ

more info about how TBD

**Comment by kylebrandt** [comment]
Note: Reference commit for doing this: https://github.com/grafana/grafana/pull/16545/files (The Go changes were due to a govet thing)

**Comment by kylebrandt** [comment]
Should be ready once `circleci/golang:1.12.6` is available. New build image 1.2.7 has been pushed to dockerhub.
