### ISSUE TITLE
Build: Update Base Image

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#17548]
Our Dockerfile in `scripts/build/ci-build` is version `14.04` which hit End of Standard Support in April 2019 (https://wiki.ubuntu.com/Releases).  

It also seems to take a rather long time. I'm wondering if we might be able to leverage the Golang Docker images to reduce the complexity of the Dockerfile and build.

If there are certain blockers for using the golang image, or a newer ubuntu image, do we know what they are?

CC @xlson

**Comment by xlson** [comment]
The build container is a bit of a mess and this definitely needs to be improved. The main reason for running an old version of ubuntu is to be able to build with an old version of GLIBC (2.4 I think) which makes sure Grafana runs on centos 6.

The reason that we need GLIBC is to be able to build sqlite support into Grafana.

**Comment by xlson** [comment]
Our build image has been updated by @aknuds1 to Ubuntu 18.04.
