### ISSUE TITLE
Unable to receive data from opentsdb with grafana 2.0

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1754]
I am trying to connect to OpenTSDB using grafana 2.0.

I do have this set on the opentsdb end:

tsd.http.request.cors_domains = *

however, I cannot get data from opentsdb, any ideas?

I get this error:

Object {data: Object, status: 500, headers: function, config: Object, statusText: "Internal Server Error"}config: Objectdata: Objectheaders: function (c){if(b||(b=db(a)),c){var d=b[Oc(c)];return void 0===d&&(d=null),d}return b}status: 500statusText: "Internal Server Error"__proto__: Object
app.8ae07506.js:24 Panel data error: Object {data: Object, status: 500, headers: function, config: Object, statusText: "Internal Server Error"}config: Objectdata: Objectheaders: function (c){if(b||(b=db(a)),c){var d=b[Oc(c)];return void 0===d&&(d=null),d}return b}status: 500statusText: "Internal Server Error"__proto__: Object

**Comment by gsaray101** [comment]
what is the name of the apache conf file name for grafana web? I think I need to put this in there to make opentsdb cors enabled:


Header set Access-Control-Allow-Origin "*"

**Comment by torkelo** [comment]
@gsaray101 grafana 2.0 does not use apache, you need to set that for your opentsdb database, but that should not be needed if you use the Proxy access method when you add your opentsdb data source.

**Comment by gsaray101** [comment]
thanks, that worked.
