### ISSUE TITLE
Explore: Unable to remove most recently added filter in InfluxDB logs mode

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#17544]
![filter_chooser](https://user-images.githubusercontent.com/45561153/59349770-5feff580-8d12-11e9-98b2-298d38b2f9d1.gif)

Currently there doesn't seem to be any way to remove the most recently added filter in the InfluxDB logs mode in Explore, so if a user adds a second filter but then decides they don't want it, rather than removing that filter, you need to remove one of the previously added filters instead, which isn't ideal.

**What would you like to be added**:
Add a `-` button before the `+` button on the row representing the most recently added filter, which would remove the most recently added filter.

**Why is this needed**:
Current behavior is somewhat cumbersome and unintuitive as mentioned above.

**Comment by marefr** [comment]
One idea we discussed earlier today and sort of temporary solution was to add a remove filter to the key drop down and skip showing the minus-icon/button. Very similar to how adhoc filters behaves in dashboards today.

Example: https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1&var-Filters=@hostname%7C%3D%7Cserver%2020 
Click on @hostname and you see that you can select `-- remove filter --`
