### ISSUE TITLE
Y-Auto value too high

### ISSUE THREAD

**Issue by Logicman111** [grafana/grafana#17557]
I make graphs from an MS SQL database which normally returns 8 values below 30k, but when I put the graph on Y-Auto, it makes a scale (linear) that goes up to 500K which make the graph look empty as all the lines are at the bottom.

I have another graph with the same kind of queries but with values up to 3 millions, and the graph scale up to 6 millions which is a little better but still to high.

But this doesn't happens when I takes values from Zabbix databases, it scale up perfectly.

Any ideas? Thanks.

- Grafana version: 6.2.2
- Data source type & version: MS SQL 
- OS Grafana is installed on: Centos 7
- User OS & Browser: Edge
- Grafana plugins: Zabbix
- Others:

**Comment by hugohaggmark** [comment]
Hi @Logicman111 and thanks for taking the time to report this. 

I'm having a hard time trying to reproduce this. Can you please provide more details about the specific 8 values below 30k? Is it any 8 values below 30k for instance? Are there any null values during this time period for instance?

![image](https://user-images.githubusercontent.com/562238/59415969-d0574f00-8dc4-11e9-9dad-843f0863ba18.png)

**Comment by Logicman111** [comment]
Hi,

This is the MS SQL query used for the data (only the name of the fields were changed):

SELECT
SUM(value1) AS value1,
SUM(value2) AS value2,
SUM(value3) AS value3,
SUM(value4) AS value4,
SUM(value5) AS value5,
SUM(value6) AS value6,
SUM(value7) AS value7,
SUM(value8) AS value8,
SUM(value9) AS value9,
unixtime as time
FROM
  datatable
  GROUP BY unixtime
ORDER BY
  unixtime ASC

There can't be any null value since it's a sum but there are many at 0. The only difference that I could think of is that with Zabbix it's from a MySQL and this is from a Microsoft SQL.

![graph](https://user-images.githubusercontent.com/11447136/59429300-7dbe6880-8dad-11e9-9e24-765ca41068c9.png)

Thanks for looking at this.

**Comment by torkelo** [comment]
Can you show all the values returned by your query? Use query inspector in panel edit mode

**Comment by Logicman111** [comment]
Here:

[graphdata.txt](https://github.com/grafana/grafana/files/3286389/graphdata.txt)

**Comment by hugohaggmark** [comment]
So I think I figured it out, let me know if this works for you? There was no difference between MSSql and MySql with the same data and query.
```sql
SELECT
$__unixEpochGroup(unixtime,'60m', 0) as time,
SUM(value1) AS value1,
SUM(value2) AS value2,
SUM(value3) AS value3,
SUM(value4) AS value4,
SUM(value5) AS value5,
SUM(value6) AS value6,
SUM(value7) AS value7,
SUM(value8) AS value8,
SUM(value9) AS value9
FROM
metric_values
WHERE $__unixEpochFilter(unixtime/1000)
GROUP BY $__unixEpochGroup(unixtime,'60m', 0)
ORDER BY
1 ASC
```

**Comment by Logicman111** [comment]
Hi,

I've tried it and it doesn't return any values; I get series:null and tables:null in Query Inspector.

**Comment by hugohaggmark** [comment]
Even if you change the column names to the "real" ones as supplied in the graphdata.txt?

**Comment by Logicman111** [comment]
I did changed the columns name before testing it. But I don't understand why manipulating the time (X data) would impact the Y auto scaling?

**Comment by hugohaggmark** [comment]
I think otherwise the graph would take the complete dataset under consideration when calculating the zoom.

**Comment by hugohaggmark** [comment]
This is running a subset of the data from `graphdata.txt` in MSSql.

![17557](https://user-images.githubusercontent.com/562238/59511984-fe698b80-8eb7-11e9-9d40-fca1e2d826ee.gif)

**Comment by Logicman111** [comment]
My problem is not with the zoom (which I didn't even know existed but very nice) but with the Y auto scaling for the whole graph so I still not understand the impact the grouping the X values.

And the edited request is:
SELECT
$__unixEpochGroup(unixtime,'60m', 0) as time,
SUM(spam) AS spam,
SUM(custom) AS custom,
SUM(blacklist) AS blacklist,
SUM(reject) AS reject,
SUM(unknown) AS unknown,
SUM(virus) AS virus,
SUM(greylist) AS greylist,
SUM(accepted) AS accepted,
SUM(whitelist) AS whitelist
FROM
  smtp_hourly
WHERE $__unixEpochFilter(unixtime/1000)
GROUP BY $__unixEpochGroup(unixtime,'60m', 0)
ORDER BY
1 ASC

Query inspector:

{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1560452728751",
      "to": "1560472571984",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 850,
          "datasourceId": 2,
          "rawSql": "SELECT\n$__unixEpochGroup(unixtime,'60m', 0) as time,\nSUM(spam) AS spam,\nSUM(custom) AS custom,\nSUM(blacklist) AS blacklist,\nSUM(reject) AS reject,\nSUM(unknown) AS unknown,\nSUM(virus) AS virus,\nSUM(greylist) AS greylist,\nSUM(accepted) AS accepted,\nSUM(whitelist) AS whitelist\nFROM\n  smtp_hourly\nWHERE $__unixEpochFilter(unixtime/1000)\nGROUP BY $__unixEpochGroup(unixtime,'60m', 0)\nORDER BY\n1 ASC\n\n  ",
          "format": "time_series"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 0,
          "sql": "SELECT\nFLOOR(unixtime/3600)*3600 as time,\nSUM(spam) AS spam,\nSUM(custom) AS custom,\nSUM(blacklist) AS blacklist,\nSUM(reject) AS reject,\nSUM(unknown) AS unknown,\nSUM(virus) AS virus,\nSUM(greylist) AS greylist,\nSUM(accepted) AS accepted,\nSUM(whitelist) AS whitelist\nFROM\n  smtp_hourly\nWHERE unixtime/1000 >= 1560452728 AND unixtime/1000 <= 1560472571\nGROUP BY FLOOR(unixtime/3600)*3600\nORDER BY\n1 ASC\n\n  "
        },
        "series": null,
        "tables": null
      }
    }
  }
}

**Comment by hugohaggmark** [comment]
Just to doublecheck, if you remove the where clause do you see any data then?

**Comment by Logicman111** [comment]
If I remove the Where clause I get the data correctly but I still have the same problem with the Y auto scaling.

**Comment by daniellee** [comment]
If you have no where clause then the query must be returning data points outside of the time range. The y-axis autoscaling is then scaling the y-axis based on the maximum value of all points in your smtp_hourly table. You should have a where clause as otherwise you will both break the zooming in Grafana, the y-axis scaling and eventually you will have performance problems due to returning more data than you need.

**Comment by Logicman111** [comment]
With or without the where clause, the Y auto scaling doesn't work properly for some reasons; the values return by the query don't exceed 30k but the Y axis goes up to 500k in auto mode with make the graphic almost useless. And all this is not related with the zooming since I don't use it.

**Comment by daniellee** [comment]
@Logicman111 your query result does exceed 30K. I just did a quick search through the data you linked to and found a value for 402688 (and lots of other values over 100k):

```json
[
  402688,
  1549958400000
],
```

so the y-axis scaling is working exactly as it should and you need to figure out how to get the where clause to work. Maybe you don't need to divide by a 1000. Does `WHERE $__unixEpochFilter(unixtime)` work instead?
