### ISSUE TITLE
Error: tsdb.HandleRequest() error elasticsearch version=70 is not supported

### ISSUE THREAD

**Issue by Ivan-Strahovsky** [grafana/grafana#17558]
**What happened**:
In alert state history I see errors: 
![image](https://user-images.githubusercontent.com/51758236/59382422-4dca8300-8d23-11e9-9c80-75cdc70d31bc.png)

**What you expected to happen**:
No error with alerts.

**How to reproduce it (as minimally and precisely as possible)**:
It is happen after migration to Grafana 6.2.2 and ElasticSearch 7.1.1. I tried to recreate dashboard, alerts, datasource - result always the same.

**Anything else we need to know?**:
If I execute rule with Test Rule button it work fine.
![GrafanaAlertTest](https://user-images.githubusercontent.com/51758236/59383346-5459fa00-8d25-11e9-99e8-df91fd6e33da.png)

DataSource configuration:
![image](https://user-images.githubusercontent.com/51758236/59435257-cfb5bd00-8db2-11e9-8e1d-200104f3826b.png)

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: ElasticSearch 7.1.1
- OS Grafana is installed on: AWS Linux
- User OS & Browser: MacOS FireFox

**Comment by marefr** [comment]
Can you please include a screenshot of your datasource configuration (edit datasource in Grafana)? Thanks

**Comment by Ivan-Strahovsky** [comment]
@marefr,  add screen shot to description. I also tried set index without pattern like index-name-*.

**Comment by marefr** [comment]
@Ivan-Strahovsky I don't understand how you can get this behavior. Looking at the code:
https://github.com/grafana/grafana/blob/07540dfdce75cc66b5e9be95a14693d72a19f42c/pkg/tsdb/elasticsearch/client/client.go#L67-L79

Only way your error can be triggered is if you've configured a string version instead of integer version or if you get some sort of name collision with another datasource.

Have you tried changing version, then save, then changing back and then save? Have you tried saving the dashboard again? Do you have multiple datasources with the same name in your Grafana instance and/or in different organizations? 

Can you include your dashboard/panel of the problematic panel json? 

Thanks

**Comment by marefr** [comment]
One more question, are you running multiple instances of Grafana in a HA setup (one shared database, many grafana instances)?

**Comment by Ivan-Strahovsky** [comment]
>Have you tried changing version, then save, then changing back and then save? Have you tried saving the dashboard again? Do you have multiple datasources with the same name in your Grafana instance and/or in different organizations?

I tried to create new datasource with different name, new dashboard, I don't see any duplicated data sources. Here is example of freshly created dashboard with newly created datascource, I create it using Grafana UI `{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 14021,
  "links": [],
  "panels": [
    {
      "alert": {
        "conditions": [
          {
            "evaluator": {
              "params": [
                70
              ],
              "type": "gt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "A",
                "15m",
                "now-5m"
              ]
            },
            "reducer": {
              "params": [],
              "type": "avg"
            },
            "type": "query"
          }
        ],
        "executionErrorState": "alerting",
        "for": "5m",
        "frequency": "1m",
        "handler": 1,
        "name": "Panel Title alert",
        "noDataState": "keep_state",
        "notifications": [
          {
            "uid": "000000005"
          }
        ]
      },
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "hub2-metric-es7",
      "fill": 1,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {},
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "bucketAggs": [
            {
              "fake": true,
              "field": "metricData.Hub/PerContainer/.ContainerStackName.dimension.Container.keyword",
              "id": "3",
              "settings": {
                "min_doc_count": 1,
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            },
            {
              "field": "timeStamp",
              "id": "2",
              "settings": {
                "interval": "auto",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "metricData.Hub/PerContainer/.ContainerStackName.metrics.MemoryUtilization.Average",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "avg"
            }
          ],
          "query": "delivery:\"hub2-na\" AND environment:\"prod\"",
          "refId": "A",
          "timeField": "timeStamp"
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "fill": true,
          "line": true,
          "op": "gt",
          "value": 70
        }
      ],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 18,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "ES7Test",
  "uid": "m9mx5D7Wk",
  "version": 2
}`

> One more question, are you running multiple instances of Grafana in a HA setup (one shared database, many grafana instances)?

Yes, we run two instances of Grafana.

**Comment by marefr** [comment]
Dashboard json looks fine in a first glimpse. 

> Yes, we run two instances of Grafana.

And what database are you using, mysql or postgres? Any replication of database(s) so that instances are not completely synced with each other/master?

Would suggest trying with one Grafana instance first to verify that it's working as expected and then try with one additional instance. Closing this for now, but will reopen given this is not a HA/database configuration problem.
