### ISSUE TITLE
Convert 'login_maximum_inactive_lifetime_days' to duration

### ISSUE THREAD

**Issue by stang** [grafana/grafana#17554]
**What would you like to be added**:
Currently, `Grafana` supports `login_maximum_inactive_lifetime_days` setting that defines the number of days a user can stay inactive before they have to login again.

I'd like to convert this to `login_maximum_inactive_lifetime_duration`, which would accept any standard string duration compatible with golang's [`time.ParseDuration()`](https://golang.org/pkg/time/#ParseDuration).

Default value should be `168h` in order to match the current `7` days.

**Why is this needed**:
We are running `grafana` with a `auth.generic_oauth` provider, `oauth_auto_login = true` and the `oauthPassThru` feature for our datasources (which are exposed behind `keycloak-gatekeeper`).

Our oidc provider is issuing refresh tokens that are valid for `30m` only.

Currently, the shortest `login_maximum_inactive_lifetime_days` we can set is `1`, so there is a timeframe where a user can come back to grafana, have a valid `auth_token` but its `oauth_refresh_token` has expired.
In which case, when trying to access a datasource configured with the `oauthPassThru`, it will try to refresh the token with a `refresh_token` that is no longer valid.

Lowering the `login_maximum_inactive_lifetime_duration` to match our `refresh_token` TTL would ensure that we never end up in that situation.

---
Is that the correct approach to take? If there is anything I missed, please let me know.

Otherwise, I'd be happy to submit a PR.

**Comment by bergquist** [comment]
Seems like https://github.com/grafana/grafana/issues/12131 is the correct solution to this.

**Comment by stang** [comment]
@bergquist - I agree, from a semantical POV, #12131 makes more sense for my current use case.

That said: this PR doesn't seem to make things worst while it brings more flexibility around the `login_maximum_inactive_lifetime_duration` so I'd still be keen to have it merged and use it as a temporary workaround if you have no objections.

If not, please feel free to close it.

**Comment by tlindhardt** [comment]
Any update to this?

**Comment by vsenapathy** [comment]
any update on this?

**Comment by faxm0dem** [comment]
> I think #12131 is the correct solution to this.

I don't see any solution it the mentioned issue, only the problem
