### ISSUE TITLE
Links in ElasticSearch sourced annotations

### ISSUE THREAD

**Issue by nfx** [grafana/grafana#17556]
**What would you like to be added**:
![](https://grafana.com/docs/img/docs/v46/annotations.png)

It would be very nice to show a link somewhere instead of plain text of a tag. e.g. including tag name to other dashboard or a link to knowledge base search

**Comment by hugohaggmark** [comment]
Hi @nfx and thanks for taking time and creating this issue. Have you tried to use HTML Anchors in the Text field? Let me know if that works out for you.

**Comment by nfx** [comment]
Hi @hugohaggmark i've tried something with it, but either it was not really working, or i didn't find any good documentation out there.

Given: 
* Grafana 6.x
* ElasticSearch (6.x) source 
* `event.label` field in ElasticSearch to describe the alert
* `event.id` field in ElasticSearch that i'd want to use to link it to other system

Desired:
* click somewhere in alert and open url constructed with `event.id` in new tab. it could either be html formatted text, or clickable annotation (ideally). doesn't really matter for MVP of functionality i'm building.

I have tried to put `<a href="http://foo/bar?goto=${event.id}">${event.subject}</a>`, but i did not get it working for some reason. Please point me to correct way.

**Comment by hugohaggmark** [comment]
Hi @nfx, I would checkout our [community site](https://community.grafana.com/) to see if someone else has already solved this or can help you with this. 
Github is mainly for feature requests and bug reports so I will close this issue now but we can always reopen the issue when needed later.
