### ISSUE TITLE
2.0b2 - No 'back to dashboard' button in view full mode

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1756]
There is no longer a 'back to dashboard' button from the view mode of a panel.  You can hit escape to go back, or can double-click the dashboard title again to go back, but there should be an obvious single click way to return to the dashboard view

**Comment by NickCraver** [comment]
+1 to this, I find the navigation back to the full dashboard very non-obvious in the latest beta. If it's a real-estate issue, perhaps an up icon in the top bar that appears when drilled down would suffice?

**Comment by torkelo** [comment]
yea, it was a realestate issue, will try to add it back.
