### ISSUE TITLE
plugins  of  panel or app have appeared on Data source list

### ISSUE THREAD

**Issue by susiezhao** [grafana/grafana#17575]
**What happened**:
![image](https://user-images.githubusercontent.com/13827192/59437739-b0577800-8e24-11e9-9adc-518e04bb0213.png)

**What you expected to happen**:
The Configuration of Data Source has a lot of plugins which type is panel or app.  I expect that only the plugin which type is datasource can appear
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  6.1.0-pre
- Data source type & version:
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Your on a old nightly build, can you upgrade to latest stable?
