### ISSUE TITLE
Dashboard is not refreshing when datasource variable use change datasource.

### ISSUE THREAD

**Issue by sachinar** [grafana/grafana#17587]
**What happened**:
We have multiple prometheus datasources , we added datasources in grafana When we are creating dashboards we added datasource variable in dashboard.
We are able to see datasources, but when we are changing datasources the grafana panels are not updating with selected datasources 

**What you expected to happen**:
When we select datasource it should change the panels with reference to which datasources selected & show values of that datasource.

**Environment**:
- Grafana version: 6.2.2 & 6.1.6 
- Data source type & version: Prometheus 
- OS Grafana is installed on: its in docker using official image
- User OS & Browser: ubuntu & chrome

**Comment by torkelo** [comment]
Are you using the variable as the selected datasource in the panel query options?

**Comment by sachinar** [comment]
yes

**Comment by hugohaggmark** [comment]
Hi @sachinar, I'm trying to reproduce this without success as you can see in the small movie below. Can you copy the panel JSON for one of your panels and paste it here without any sensitive data?

![prom](https://user-images.githubusercontent.com/562238/59510766-d7f62100-8eb4-11e9-8d4d-ba5ec8ea2639.gif)

**Comment by sbhushankr** [comment]
Hi,

I am facing the same issue. Like we have created the dashboard with Prometheus data source and created the variable as Data source and when we selecting the data source in variable but dashboard is updating and even panel query showing old selected data source there.
<img width="534" alt="Capture2" src="https://user-images.githubusercontent.com/44037104/172985849-74a16aea-0747-49ca-a2ba-e4ca3130cc40.PNG">

**Comment by sbhushankr** [comment]
Hi,
Can anyone faced this issue and have any solution then please share it here. I am using common grafana for many datasource and because of this issue we need to create the separate dashboard for each datasource. This become a big concern to manage so many dashbaord for same type of requirement.

Regards,
Shashi

**Comment by Muthuraj647** [comment]
Hi @sbhushankr me also facing this issue. I tried to find this root cause but can't find, did you find any solution for this, if yes can you share here please.
