### ISSUE TITLE
rendering graphs with phantomjs failed on Debian "buster"

### ISSUE THREAD

**Issue by cultcom** [grafana/grafana#17588]
icingaweb2-module-grafana could not render graphs using the "/render" URL. It always resulted in a 500 server error.

```
t=2019-06-14T12:07:55+0200 lvl=info msg=Rendering logger=rendering path="d-solo/0HKdptnWz/icinga2-default...
t=2019-06-14T12:07:55+0200 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/0HKdptnWz/icinga2-default?..." timezone=
t=2019-06-14T12:07:55+0200 lvl=dbug msg="Phantomjs output" logger=rendering out=
t=2019-06-14T12:07:55+0200 lvl=dbug msg="Phantomjs error" logger=rendering error="exit status 1"
t=2019-06-14T12:07:55+0200 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="exit status 1"
t=2019-06-14T12:07:55+0200 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=xxx error="exit status 1"
t=2019-06-14T12:07:55+0200 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=xxx method=GET path=/render/d-solo/0HKdptnWz/icinga2-default status=500 remote_addr=2001:638:812:100:b8c5:3e62:99c5:7af4 time_ms=19 size=1730 referer=https://admon.beuth-hochschule.de/icingaweb2/dashboard
```

After trying to run phantomjs manually I got this:
```
root@icinga:/opt/icingaweb2/modules/grafana# /usr/share/grafana/tools/phantomjs/phantomjs 
Auto configuration failed
140594119331456:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
140594119331456:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140594119331456:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140594119331456:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
```

I could fix this by adding this line to "/etc/default/grafana-server":
```
OPENSSL_CONF=/etc/ssl
```

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10 (buster)
- User OS & Browser: LinuxMint, Firefox and Chrome

**Comment by hugohaggmark** [comment]
Hi @cultcom, thanks for reporting this. 
Are you running a docker image with grafana, building it yourself or using the prebuilt?

**Comment by cultcom** [comment]
I am using the prebuilt debian packages.

**Comment by xlson** [comment]
Newer openssl is not compatible with PhantomJS. We are in the process of replacing phantomjs (#13802) with headless chrome and should hopefully have to ready for the 6.3 release of Grafana. This should solve you issue.

**Comment by cultcom** [comment]
for not being compatible it works fine with my workaround.

**Comment by xlson** [comment]
Bad wording on my part. We want to replace phantomjs and while the workaround works we're not sure what other implications it may have. The currently preferred solution to your problem is to replace phantomjs.

**Comment by RolandRosenfeld** [comment]
The workaround solved the issue for me, too.
It may be a good idea to add this to packaging/deb/default/grafana-server (if it doesn't trigger problems on non-buster systems). Since Debian buster was released yesterday, many users may run into this issue soon and it took me some time to find this issue and the workaround...

**Comment by xlson** [comment]
The question is what, if any, side effects this has on SSL in Grafana as a whole. We might be able to do the same thing but only for PhantomJS though.

**Comment by juloko** [comment]
**In docker using Debian Buster:**

Before build the docker:
1. Add to Dockerfile, `ENV OPENSSL_CONF=/etc/ssl/ `.
4. And build the docker image. 


On docker running:

1. Add to `.bashrc` add inside this file ` export OPENSSL_CONF=/etc/ssl/`. 
2. And restart the docker image.
