### ISSUE TITLE
New DEB & RPM package layout, init scripts, and binary name change, systemd file

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1758]
**RPM / DEB Package changes (to follow HFS)**
- binary name changed to grafana-server
- does not install to `/opt/grafana` any more, installs to `/usr/share/grafana`
- binary to `/usr/sbin/grafana-server`
- init.d script improvements, renamed to `/etc/init.d/grafana-server`
- added default file with environment variables,
  - `/etc/default/grafana-server` (deb/ubuntu)
  - `/etc/sysconfig/grafana-server` (centos/redhat)

- added systemd service file, tested on debian jessie and centos7
- config file in same location `/etc/grafana/grafana.ini` (now complete config file but with every setting commented out)
- data directory (where sqlite3) file is stored is now by default `/var/lib/grafana`
- no symlinking current to versions anymore
- For more info see [Issue #1758](https://github.com/grafana/grafana/issues/1758).

**Config breaking change (setting rename)**
- `[log] root_path` has changed to `[paths] logs`

the initd script or systemd service file will start grafana using these parameters:
``
DAEMON_OPTS="--pidfile=${PID_FILE} --config=${CONF_FILE} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.logs=${LOG_DIR}"
``
By default DATA_DIR is now `/var/lib/grafana`, 

The deb and rpm packages have dependencies on font libs (required by the server side rendering of panels to png via phantomjs). 

So when installing via dpkg saying you have unmet depdencies. To fix run: 
`$ sudo apt-get install -f`

**Comment by maddenca** [comment]
I just tried to update from b2 to b3 but it throws a bunch of warnings:

root@sdt-graphite:/tmp# dpkg -i grafana_latest_amd64.deb.4
(Reading database ... 158855 files and directories currently installed.)
Preparing to replace grafana 2.0.0-beta2 (using grafana_latest_amd64.deb.4) ...
Unpacking replacement grafana ...
dpkg: warning: unable to delete old directory '/opt/grafana/versions/2.0.0-beta2': Directory not empty
dpkg: warning: unable to delete old directory '/opt/grafana/versions': Directory not empty
dpkg: warning: unable to delete old directory '/opt/grafana': Directory not empty
dpkg: warning: unable to delete old directory '/opt': Directory not empty
Setting up grafana (2.0.0-beta3) ...
Installing new version of config file /etc/grafana/grafana.ini ...
root@sdt-graphite:/tmp# service grafana-server start
[FAIL] Starting Grafana Server: failed!
. ok 

I then accessed the GUI but it is a fresh install (default password, apparently accessing a fresh/empty sqlite db) whereas I had expected it to upgrade as usual. It also said it failed to start, but then also ok, and it was running.  I did another stop/start straight thereafter without any error, so maybe it just happens on the very first start after upgrade.

Anyway, I had a look at the grafana.ini file and saw the location of the db changed, so I copied mine into the expected location:

root@sdt-graphite:/var/lib/grafana# service grafana-server stop
[ ok ] Stopping Grafana Server:.
root@sdt-graphite:/var/lib/grafana# cp /opt/grafana/data/grafana.db /var/lib/grafana/grafana.db
root@sdt-graphite:/var/lib/grafana# service grafana-server start
[ ok ] Starting Grafana Server:.
root@sdt-graphite:/var/lib/grafana# 

Now things load correctly.  Maybe you can copy the db as part of the dpkg upgrade?

**Comment by torkelo** [comment]
@maddenca  thanks for the feedblack, will try to do a an upgrade step that moves the grafana.db file
