### ISSUE TITLE
alert state history "flip flop" effect

### ISSUE THREAD

**Issue by cicciopizza** [grafana/grafana#17591]
**What happened**:
I have a data series on influxDB that returns all values ​​= 0
I configured a simple Alert: when avg() query A last 5m is below 50 > Alert
And I  configured: If no data or all values are null > No Data (default configuration)
The rule is evaluated every 5 sec.
![Selezione_009](https://user-images.githubusercontent.com/26459829/59528620-11438680-8edf-11e9-8dfb-b9f1f4dd68e7.png)

if I repeatedly click on test rule, the result is ALWAYS the expected one: Alerting:
![Selezione_010](https://user-images.githubusercontent.com/26459829/59528899-c7a76b80-8edf-11e9-97c1-5f0800e14090.png)

But if I look in "State History" I see a "flip flop" between: Alert and "No data":
![Selezione_011](https://user-images.githubusercontent.com/26459829/59529048-3d133c00-8ee0-11e9-9a9a-b0d535288c97.png)

IMPORTANT !!!
Using graphana v5.3.4 (69630b9) on the same server and same datasource, it works correctly !!!
![Selezione_013](https://user-images.githubusercontent.com/26459829/59529224-bd39a180-8ee0-11e9-8368-7f8fe98ae722.png)
![Selezione_012](https://user-images.githubusercontent.com/26459829/59529230-c165bf00-8ee0-11e9-9593-986c394a2bff.png)

**What you expected to happen**:
The same behavior of graphana v5.3.4

**How to reproduce it (as minimally and precisely as possible)**:

I have already written above how to reproduce the problem:
a series of data at 0 (but I have the same effect even when there are different data)
The problem seems to be the configuration of the parameter;

> If no data or all values are null > No Data 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: influxdb 1.7.6
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser: Chrome
- Grafana plugins: Native Panel Graph
- Others:

**Comment by marefr** [comment]
@cicciopizza Sorry for this has taken longer time for me to look into than I initially planned. Are you still having the same problem? Can you show me the Influx query you're using? Do you have any [min interval](https://grafana.com/docs/features/datasources/influxdb/#min-time-interval) set on panel or datasource?

Thanks

**Comment by marefr** [comment]
@cicciopizza Closing this due to lack of response. Will consider reopen if you provide us the information requested.

**Comment by cicciopizza** [comment]
Sorry for my long absence.

I Have updated to Grafana v6.2.5 (6082d19) but I still have the same problem.

I tried with a new, simpler data set:

This is the influx query:
![Selezione_025](https://user-images.githubusercontent.com/26459829/61575992-0e3a4800-aad4-11e9-995a-16d22b41a7ac.png)


```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/34/query",
    "params": {
      "db": "ufficio_tecno",
      "q": "SELECT mean(\"ACPWF3\")  / 100 FROM \"nemo_5\" WHERE time >= now() - 15m GROUP BY time(1m)",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "nemo_5",
            "columns": [
              "time",
              "mean"
            ],
            "values": [
              [
                1563608040000,
                16354.2
              ],
              [
                1563608100000,
                16434.04
              ],
              [
                1563608160000,
                14123.64
              ],
              [
                1563608220000,
                14542.26
              ],
              [
                1563608280000,
                15585.12
              ],
              [
                1563608340000,
                13867.05
              ],
              [
                1563608400000,
                14508.87
              ],
              [
                1563608460000,
                13731.6
              ],
              [
                1563608520000,
                14451.27
              ],
              [
                1563608580000,
                13042.08
              ],
              [
                1563608640000,
                14410.65
              ],
              [
                1563608700000,
                15194.61
              ],
              [
                1563608760000,
                13691.46
              ],
              [
                1563608820000,
                11059.86
              ],
              [
                1563608880000,
                9808.77
              ],
              [
                1563608940000,
                10985.68
              ]
            ]
          }
        ]
      }
    ]
  }
}

```

The strange thing is this:


![Selezione_026](https://user-images.githubusercontent.com/26459829/61576023-64a78680-aad4-11e9-8eba-d826643e0bea.png)

The data in Influx comes every 15 sec. about
I set :
`query (A, 1h, now-5m)`

to make sure I take a full interval to evaluate the alarm.

![Selezione_027](https://user-images.githubusercontent.com/26459829/61576180-b224f300-aad6-11e9-9eaa-89183175ef49.png)


but it is as if the evaluation of "No data" does not consider this.

it seems as if evaluating the precise instant in which the check is made to decide whether to activate a "No Data"
(sorry for my english but help me with google translator)

**Comment by cicciopizza** [comment]
Finally I managed to understand the problem:
my graphana installation is based on a mysql database (instead of the default sqlite) and on this database there was a problem that triggered the "Filip Flop" anomaly

**Comment by marefr** [comment]
@cicciopizza what exactly was that problem if I may ask?

**Comment by cicciopizza** [comment]
I try to explain better:
- I have 2 grafana installation on two different servers
- Both installations use mysql as a configuration database (instead of sqlite which is the default one)
- The two databases are automatically synchronized

the goal is to have 2 identical grafana installations: same dashboards, same users, same datasource, etc.

Unfortunately it happened that a datasource (influxdb) of an instance was not fed correctly, and therefore the grafana alarm engine generated a "no data".
The other instance instead worked correctly and generated a: OK and so this created the "flip flop" effect.

this happened because the mysql database of the 2 grafana was (at the logical level) the same DB !!!

At the moment I have turned off 1 instance of grafana and everything works correctly.

**Comment by marefr** [comment]
Gotcha. Thanks. Glad you solved it.
