### ISSUE TITLE
New Panel's remove button removes every previous row or panels before clicking it actually removes the New Panel panel

### ISSUE THREAD

**Issue by GGG-KILLER** [grafana/grafana#17592]
**What happened**:
When attempting to remove a "New Panel" placed after any other panel (or inside a row), it removed the parent row or the previous panel (in that order).

**What you expected to happen**:
Only the "New Panel" gets removed when the `X` button is clicked.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new dashboard (it also happens on existing ones)
2. Add a text panel to the dashboard (it also happens with any other panel and rows as well)
3. Click on the "Add Panel" button again
4. Drag the "New Panel" panel to the right of the text panel (also happens when placing it inside rows or under panels)
5. Press the `X` button
6. The text panel gets removed

**Anything else we need to know?**:
I don't think so, but please let me know if you do.

**Environment**:
- Grafana version: Grafana v6.2.2 (07540df)
- Data source type & version: Not applicable(?)
- OS Grafana is installed on: Windows Server 2016 Standard
- User OS & Browser: Windows 10 Pro 1809 (build 17763.503) and Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Grafana plugins:
    - Alert List
    - Azure Monitor
    - Bar Gauge
    - CloudWatch
    - Dashboard list
    - Elasticsearch
    - Gauge
    - Getting Started
    - Graph
    - Graphite
    - Heatmap
    - InfluxDB
    - Loki
    - Microsoft SQL Server
    - MySQL
    - OpenTSDB
    - Pie Chart
    - Plugin list
    - PostgreSQL
    - Prometheus
    - Singlestat
    - Stackdriver
    - Table
    - TestData DB
    - Text
- Others:

**Comment by torkelo** [comment]
quick fix here: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/AddPanelWidget/AddPanelWidget.tsx#L63

**Comment by torkelo** [comment]
@dehrax when you want to break from typescript any issues you fix this bug :)
