### ISSUE TITLE
Add alerting option: last value of query older than X minutes

### ISSUE THREAD

**Issue by cbtsgithub** [grafana/grafana#17593]
When a the result of an echo request (ping) is older than X minutes, it means the site/equipment is unavailable/down or something else.

Is it possible to add in the alert conditions something like:

When last() of querry A is older than X seconds/minutes
The set alert state to alerting.

Thanks in advance to take into consideration this feature request.
Chris

**Comment by aocenas** [comment]
Hey, we have a way to set specific state of an alert when there is no data:
<img width="859" alt="Screenshot 2019-06-17 at 15 26 28" src="https://user-images.githubusercontent.com/1014802/59608044-d2971180-9114-11e9-9b26-ca406a1208cc.png">

I think that could help.
