### ISSUE TITLE
Add dashboard name as a global variable

### ISSUE THREAD

**Issue by groyee** [grafana/grafana#17598]
**What would you like to be added**:

I think it would be nice to have the current folder and/or dashboard name as a global variable. Something like $dashboard_name and $folder_name

**Why is this needed**:

This will allow users to duplicate dashboards that are different only by their name. For instance each team can have it's own dashboard. All my queries can include a filter: name:$dashboard_name.

Once a team duplicates a dashboard with it's own name, all queries will be automatically adjusted to that team.

**Comment by hugohaggmark** [comment]
Glorious news, we implemented this feature in Grafana 7.1.0.
https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#global-variables

Thank You to you for taking the time to create this issue!
