### ISSUE TITLE
Disabling mobile version

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#17597]
**What would you like to be added**:
It would be nice to have a feature to disable mobile version of Grafana, so it will look the same on PCs and mobiles.

**Why is this needed**:
In my view mobile version of Grafana looks bad. There is only one panel per row.

Mobile version:
![Screenshot_2019-06-15-11-11-49-321_com android chrome](https://user-images.githubusercontent.com/19311511/59552272-0ba07c00-8f85-11e9-9ab7-dbe8abdd7e60.png)

PC version on mobile (I forced PC version in browser options):
![Screenshot_2019-06-15-11-12-01-171_com android chrome](https://user-images.githubusercontent.com/19311511/59552273-178c3e00-8f85-11e9-89f8-fcce48d84b7c.png)

**Comment by cbtsgithub** [comment]
I do agree with szerwi. It is a very good idea.

**Comment by Atem18** [comment]
@szerwi To me, that should be done with your browser like you did, not at Grafana level.

If the mobile interface of grafana renders bad, then those bugs should be fixed (providing a better mobile interface of Grafana).

**Comment by szerwi** [comment]
@Atem18 I am sharing my dashboard with other people and I want that they will see PC version of the page without doing anything

**Comment by Atem18** [comment]
@szerwi Basically, you want to block to a PC version that dashboard ?
Why not just put your mobile in landscape to see more things ? I am pretty that if you use a tablet big enough, it will display like a pc in landscape mode.
Or you can wait for IOS13 as Safari will request desktop page by default for iPad.

**Comment by szerwi** [comment]
@Atem18 yes, I want to block it to PC version. Many people have access to my dashboard and I want that they will open PC version straight after opening the page.

**Comment by torkelo** [comment]
Not sure this request is feasible or something we will do 
<img width="284" alt="Screen Shot 2019-06-19 at 21 21 03" src="https://user-images.githubusercontent.com/10999/59794026-47ff0f80-92d8-11e9-98a6-f2845f0516a9.png">

We will try to improve mobile experiance but using the PC layout for mobile will 90% look horrible and be unusable for most panels types and layouts

**Comment by szerwi** [comment]
@torkelo I think you showed mobile version on the screen. In my situation PC version looks good on mobile.

**Comment by torkelo** [comment]
? 

This is the Desktop layout on a mobile size screen, exactly what you ask for

**Comment by szerwi** [comment]
@torkelo but you have a "mobile button" in top left corner. Why the PC layout looks much better on my screen than on yours?

**Comment by torkelo** [comment]
Your screen looks like iPad i horizontal orientation?

**Comment by torkelo** [comment]
Also looks zoomed out , maybe that is what your browser setting did? Horizontal width Looks way to wide for a mobile

**Comment by szerwi** [comment]
No, it is 6" screen in vertical orientation. I've only enabled PC version in Google Chrome.

**Comment by szerwi** [comment]
@torkelo is there maybe a way to disable mobile version using Google Tag Manager? I think it should be possible, but I don't know how to do it.

**Comment by hunble** [comment]
@torkelo can we do something so that if desktop version of some panel is small enough, Instead of expanding that to whole screen, we keep staking next panel in the same horizontal row, unless there is a bigger panel or not more space left in the row.

Or we can also let users configure their mobile views separately. Instead of scaling the desktop versions.

**Comment by szerwi** [comment]
@hunble it will be available in v7.0 https://grafana.com/blog/2020/04/23/grafana-v7.0-is-coming-soon-check-out-this-sneak-peek-of-the-auto-grid-layout/

**Comment by torkelo** [comment]
that is a specific feature for gauge & stat panels (when they include multiple internal sub visualizations)

**Comment by szerwi** [comment]
Seems like from some time it is possible to disable dashboard's mobile view by providing viewport config in Grafana's config file:
```
# Limit the maximum viewport width, height and device scale factor that can be requested.
rendering_viewport_max_width = 0
rendering_viewport_max_height = 0
rendering_viewport_max_device_scale_factor = 1.0
```

Tested on 9.4.0-beta1 - works well :)
