### ISSUE TITLE
CloudWatch metric math broken in mixed source mode

### ISSUE THREAD

**Issue by roberth-k** [grafana/grafana#17601]
**What happened**: 
When configuring a panel with mixed sources, the hidden queries of the individual sources become disabled even if the corresponding plugin declares `hiddenQueries: true`. In our case, this breaks panels that display CloudWatch math queries sourced from multiple AWS accounts.

**What you expected to happen**:
Hidden queries should be passed to the CloudWatch plugin in mixed source mode.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel backed by a specific CloudWatch data source.
2. Set up a math query with a source ("A") and a math expression ("B"). Confirm that both plots are visible.
3. Hide query A. Confirm that plot B is still visible.
4. Switch the panel source to "Mixed". Plot B will disappear.
5. Un-hide query A. Plots A and B will both appear.

**Anything else we need to know?**:
- Bug not present in 6.1.x.
- Relates to https://github.com/grafana/grafana/pull/17124

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: Mixed sources using the CloudWatch plugin.
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: Safari 12.1 and Chrome 74.
- Grafana plugins: default

**Comment by marefr** [comment]
@ryantxu haven't we done additional work on handling of hidden queries since  #17124 and/or 6.2.0?

**Comment by sunker** [comment]
This was fixed in 6.4
