### ISSUE TITLE
Singlestat panel value is shown over Polystat tooltip

### ISSUE THREAD

**Issue by ulikl** [grafana/grafana#17610]
**What happened**:

When combining Singlestat and Polystat panels and the Polystat tooltip overlaps with the Singlesstat text, the SingleStat panel value is shown on top. So not all data of the tooltip can be seen.
E.g.
![grafik](https://user-images.githubusercontent.com/40604083/59601774-5517d500-9105-11e9-84d5-4a8c89191e56.png)

**What you expected to happen**:

I expect the tooltip to be shown also on top of all other overlapped panels.
This does for example not happen with the Polystat tooltip overlapping panels from the plugins Graph and natel-discrete-panel.

**How to reproduce it (as minimally and precisely as possible)**:

I can produce it with this simple dashboard using a Prometheus datasource with basic metrics:
[SingleStatText_over_PolystatTooltip_json.txt](https://github.com/grafana/grafana/files/3296787/SingleStatText_over_PolystatTooltip.json)

**Anything else we need to know?**:
  None.

**Environment**:
- Grafana version: 6.2.2 

- Data source type & version:
   reproduced with Prometheus and InfluxDB (preinstalled plugin from Grafana version )

- OS Grafana is installed on:
  Grafana docker image grafana/grafana:6.2.2

- User OS & Browser:
  Firefox 67.0.1
  Windows 10

- Grafana plugins:
   Polystat 1.0.16
   SingleStat preinstalled from grafana 6.2.2 (no version number shown)

- Others:
  None.

**Comment by torkelo** [comment]
you need to open this in the https://github.com/grafana/grafana-polystat-panel repo.
