### ISSUE TITLE
404 error, event_manager and stream not found

### ISSUE THREAD

**Issue by Etzku** [grafana/grafana#17626]
I am trying to copy the grafana graph to a plugin so I can make some modifications to it.

When I go to select the plugin in "Visualization" I get the following errors:
![image](https://user-images.githubusercontent.com/50619212/59664729-43443980-91ba-11e9-8541-91c45d25621a.png)

![image](https://user-images.githubusercontent.com/50619212/59664753-50612880-91ba-11e9-9c1d-22c947def595.png)

and the panel looks like this:
![image](https://user-images.githubusercontent.com/50619212/59665214-29efbd00-91bb-11e9-8472-420b517afe56.png)

I'm using the 6.1.6 version of Grafana.

I have changed the imports, declerations and the plugin id, and the plugin compiles without errors.

I imagine this might not be enough information to know what exactly is wrong, but I also do not know what kind of information you would need. I am happy to provide whatever information someone would need to help me.

**Comment by torkelo** [comment]
Copying an internal plugin like this is not supported

In your new react panel plugin architecture you can import or graph component and use that

**Comment by Etzku** [comment]
Okay, I did see #15577 but I figured I could inherit the metricPanelCtrl as with a normal plugin and then just copy the graph on that with minimal changes.

If I could get a little clerification, the graph component I should import is this: https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts ?

Either way, thanks!
