### ISSUE TITLE
Replace Remarkable with alternative package that is maintained

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#17627]
Remarkable depends on packages that have known vulnerabilities. Since it's a package that's not maintained anymore it would be wise to consider alternatives:

- https://github.com/markedjs/marked
- https://github.com/showdownjs/showdown
- https://github.com/markdown-it/markdown-it

**Comment by dehrax** [comment]
The major difference I can see between the three alternatives is package size. Showdown has GCP and Meteor as users, so definitely an incentive to keep maintaining the package.

Marked has no dependencies. That's nice. Almost 2 million weekly downloads.

Markdown-it has a very similar README to remarkable. Might be related? Over 600k weekly downloads on npm if that means something.

I would probably go for Marked personally.
