### ISSUE TITLE
Oauth with oauth_auto_login = true can get into redirect loop

### ISSUE THREAD

**Issue by caarlos0** [grafana/grafana#17623]
**What happened**:

I deployed grafana using the helm chart and added github auth, as well as a domain.

I've set the following environment variables:

```
      GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: my-org
      GF_AUTH_GITHUB_ENABLED: 'true'
      GF_AUTH_BASIC_ENABLED: 'false'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_GITHUB_CLIENT_ID: 'fake'
      GF_AUTH_OAUTH_AUTO_LOGIN: 'true'
      GF_SERVER_DOMAIN: grafana.foo.bar
      GF_SERVER_ROOT_URL: https://grafana.foo.bar/
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: Admin
      GF_AUTH_GITHUB_CLIENT_SECRET: fakefakefake
```

if I log in with an user under the allowed org, it work as expected.
Otherwise, it keeps on a redirect loop instead of showing a "not allowed" error or something.

**What you expected to happen**:

Show the user is not allowed access.

**How to reproduce it (as minimally and precisely as possible)**:
The envs above should do the trick.

**Anything else we need to know?**:
none.

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: irrelevant
- OS Grafana is installed on: irrelevant
- User OS & Browser: irrelevant
- Grafana plugins: none
- Others: none

**Comment by aocenas** [comment]
The issue seems to be in `GF_AUTH_OAUTH_AUTO_LOGIN: 'true'`. Due to code [here](https://github.com/grafana/grafana/blob/2d03815770b67950671df090c01f419fa045dc48/pkg/api/login.go#L65) the login page tries to login user automatically, if that fail it [redirects](https://github.com/grafana/grafana/blob/2fff8f77dcdc90ab9a4890eeed95d8f3dced370b/pkg/api/login_oauth.go#L145) to login at which point it starts again.

**Comment by aocenas** [comment]
@caarlos0 Probably not ideal for you but you could set `OAUTH_AUTO_LOGIN: 'false'` until this is fixed. Would mean users will have to click the github login button and with `GF_AUTH_DISABLE_LOGIN_FORM: 'true'` the login page looks bit weird but would remove the redirect loop.

**Comment by torkelo** [comment]
Would query param like auto-login-error be a good solution to stop the redirect loop & show error?

**Comment by marefr** [comment]
Would probably work
