### ISSUE TITLE
Changed to new locations break dockerfile

### ISSUE THREAD

**Issue by noelmcgrath** [grafana/grafana#1762]
Dockerfile has the following
ENTRYPOINT ["/opt/grafana/current/grafana", "--config", "/etc/grafana/grafana.ini", "web"]
but this no longer works as I believe the locations have changed
Dockerfile needs to be updated to reflect changes

**Comment by torkelo** [comment]
yes! Will fix!

**Comment by torkelo** [comment]
updated docker file https://github.com/grafana/grafana-docker/commit/0ada1c1f743b5761a1ab81810e6e07b57d3a0977  and pushed new image to docker hub

**Comment by noelmcgrath** [comment]
http://docs.grafana.org/v2.0/installation/ should be updated too
volumes are now as follows
VOLUME ["/var/lib/grafana"]
VOLUME ["/var/log/grafana"]
VOLUME ["/etc/grafana"]

**Comment by torkelo** [comment]
thanks, updating now
