### ISSUE TITLE
Feature Request (Grafana 2.0): Simple external SSO

### ISSUE THREAD

**Issue by thomaspurchas** [grafana/grafana#1763]
[Discourse](http://www.discourse.org/) offers a very simple form of [external SSO](https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045?u=thomaspurchas), which uses HMAC-SHA256 signatures and simple payloads to allow an external site to authenticate people and provide user details.

Having something similar in Grafana would be fantastic for integrating Grafana with login systems that people have already built, and allows people to then build their own proxies to allow authentication using any method imaginable.

**Comment by jlming6** [comment]
This is really awesome, looking for it.

**Comment by mflamm** [comment]
I'm also interested in this. Are there any news?

**Comment by lakshmanvvs** [comment]
Is this feature request still open? or is anyone working on it?

**Comment by torkelo** [comment]
Still open, no one working on it

**Comment by walterdolce** [comment]
I'm looking forward to seeing this feature spring to life. Do you guys have a public roadmap that users can have a look to see what's going to be shipped in upcoming releases?

**Comment by sw-yx** [comment]
recommend closing since generic oauth is available now
