### ISSUE TITLE
[Feature request] Value mapping support in tables for null/empty values

### ISSUE THREAD

**Issue by dataviruset** [grafana/grafana#17638]
**What would you like to be added**:
I'd like to map my empty values to 0 instead of having them show up as an empty value or "-" in my tables. Can't use FILL(0) because I have two InfluxDB queries. Needed for doing timeshift using influxdb-timeshift-proxy.

![Screenshot from 2019-06-18 21-50-09](https://user-images.githubusercontent.com/1078018/59690136-76ff7d80-9213-11e9-81cf-b0545c109479.png)

**Why is this needed**:
It would make it easier to show whatever value you want to show up instead of empty value or "-“.
It also makes sorting much nicer. Right now it seems "-" shows up at the top of a descending sorting as seen in my screenshot.

**Comment by aocenas** [comment]
Seems like we have mapping of values to string if the type of column is string but that works only as exact mapping or ranges to specific value so not something that could be used for this use case. It is probably more similar usecase to `Null value`setting in line graph.

**Comment by marefr** [comment]
Hmm this may or should be covered by this open feature request https://github.com/grafana/grafana/issues/11418

**Comment by aocenas** [comment]
@marefr I do not see the null value handling directly mentioned there, seems like it is more about coloring rather than rewriting/formatting the actual values in the cells. Should I add it to the list of the linked issues in there anyway? I mean looks reasonable close to me, just not sure if we wan't to chunk this together.

**Comment by marefr** [comment]
Yeah I was probably too fast there. I thought that issue included support for more general value mappings as well. As a workaround you may be able to change the column styles from number to string and do a null to 0 value mapping. Don't guarantee that works for the sorting scenario etc but worth a shot.

**Comment by ryantxu** [comment]
In the new react stuff there is a LOT of effort going into standard processing/mapping of values -- I think this is already supported there, if not it should be :)

**Comment by dataviruset** [comment]
> As a workaround you may be able to change the column styles from number to string and do a null to 0 value mapping. Don't guarantee that works for the sorting scenario etc but worth a shot.

Tried both with Value to text and Range to text, none of them seems to work. Still shows up as "-" in the table.

![image](https://user-images.githubusercontent.com/1078018/59834209-2f473600-937a-11e9-93a0-51e9a68178b6.png)

![image](https://user-images.githubusercontent.com/1078018/59834263-47b75080-937a-11e9-9667-46efe84709fd.png)

**Comment by dprokop** [comment]
@dataviruset this is now addressed with Grafana 7 new Table panel
