### ISSUE TITLE
OpenID unique user identifier

### ISSUE THREAD

**Issue by schanzen** [grafana/grafana#17635]
**What happened**:
I can use two _different_ user accounts from my OAuth2/OpenID Connect server to login to the _same_ grafana account if they have the same email address.
According to the standard (https://openid.net/specs/openid-connect-core-1_0.html, Section 5.7):
"
The sub (subject) and iss (issuer) Claims, used together, are the only Claims that an RP can rely upon as a stable identifier for the End-User, since the sub Claim MUST be locally unique and never reassigned within the Issuer for a particular End-User, as described in Section 2. Therefore, the only guaranteed unique identifier for a given End-User is the combination of the iss Claim and the sub Claim.

All other Claims carry no such guarantees across different issuers in terms of stability over time or uniqueness across users, and Issuers are permitted to apply local restrictions and policies. For instance, an Issuer MAY re-use an email Claim Value across different End-Users at different points in time, and the claimed email address for a given End-User MAY change over time. Therefore, other Claims such as email, phone_number, and preferred_username and MUST NOT be used as unique identifiers for the End-User.
"

**What you expected to happen**:

I should be able to log in to two distinct accounts at grafana as well.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two user accounts at any of your configured OAuth2/OpenID IdPs with the same email address (this is not prohibited in general, maybe will not work for Facebook/Google as they require emails to be unique but Section 5.7 still applies for the RP).
2. Initial login with user 1
3. Logout
4. Login with user 2
5. Observe that you are logged into the account of user 1

**Anything else we need to know?**:

You should either use the "sub" claim from OpenID or map the "sub" claim to a local UID, taking also "iss" into account. "sub" is only unique locally to the issuer.

**Environment**:
- Grafana version: any
- Data source type & version: any
- OS Grafana is installed on: any
- User OS & Browser: any
- Grafana plugins: any
- Others: any

**Comment by schanzen** [comment]
I would like to add that I disagree with the label "feature-request" for this issue.
Due to the fact that -- for example -- the admin login could have the same email address as a normal user account this is at least a bug if not a security issue.
Authentication requirements between the normal user account and the admin account may differ greatly. What could happen is that an attacker could target the lesser-privileged, easier to hack normal user account of the individual which happens to also be the admin and use it to gain admin access.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by schanzen** [comment]
I am sorry but this is not a feature request, it is a (security) bug. I do not know if this was fixed in the meantime or otherwise mitigated, but silently (re)moving it does not fix the problem.

**Comment by schanzen** [comment]
I never posted there because I do not see a need to discuss anything. It is not a feature request. This is (was?) an obvious bug and writing it up with pointer to spec was out of courtesy, I do not have a stake in Grafana anymore. So yeah... maybe @pkolyvas can comment.
