### ISSUE TITLE
markdown table in notifications.md is broken

### ISSUE THREAD

**Issue by sellersj** [grafana/grafana#17654]
**What happened**:
Table under heading "All supported notifiers" under docs/sources/alerting/notifications.md needs to be fixed. I think that the it just needs an extra space pipe space

https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md#all-supported-notifiers
https://grafana.com/docs/alerting/notifications/#all-supported-notifiers

**What you expected to happen**:
The table to be properly formated

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marcusolsson** [comment]
Thanks for the heads-up @benpatterson! It looks indeed like we can close this.
