### ISSUE TITLE
Add support for auto-complete of InfluxDB metrics with template variables

### ISSUE THREAD

**Issue by PRI-mcallen** [grafana/grafana#1765]
I'm using Version: 2.0.0-beta1, Commit: fb0629a, Build date: 2015-03-30 06:45:02 -0700 PDT

When adding metrics to a graph from an InfluxDB datasource, a metric that has a template variable in it does not have auto-complete support.  For example, $session_id.foo.bar does not autocomplete, where $session_id is the template variable.

Regular InfluxDB metrics have autocomplete and it works great.  This would be a very valuable feature for my use case where there are many metrics and several template variables that drive them.

**Comment by cemo** [comment]
+1

**Comment by PRI-mcallen** [comment]
If you can provide some general guidance on where to find the hooks for this, I can take a look at making the fix.  I took a brief look but it was not immediately obvious (as someone who is not a go expert).

**Comment by janceChun** [comment]
+1

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by gabor** [comment]
@PRI-mcallen @cemo @janceChun this feature request happened a long time ago, i'd like to refresh the discussion, could you please describe how exactly this should work? like a step-by-step reproduction of what should happen? thanks!

**Comment by aocenas** [comment]
Closing this as there wasn't much interest lately for this. Reopen if this is still relevant for someone and please add more info about how this should work.
