### ISSUE TITLE
Document generic oauth example using OpenOTP

### ISSUE THREAD

**Issue by perttulaurila** [grafana/grafana#17658]
Hi, we would like to suggest a new integration configuration instructions:

Set up OAuth2 with OpenOTP:
Create a new Client Policy for Grafana in WebADM with a descriptive name, like "grafana", this should match your client_id below.

Edit the Application Settings in the new client policy, under OpenID & SAML Provider, define a "Client Secret", which should match the client_secret below.

Configure Grafana as follows:
[auth.generic_oauth]
enabled = true
name = OpenOTP
allow_sign_up = true
client_id = grafana
client_secret = secret
scopes = openid profile email
auth_url = https://<openotp_server>/webapps/openid/index.php
token_url = https://<openotp_server>/webapps/openid/index.php
api_url = https://<openotp_server>/webapps/openid/index.php

**Comment by marefr** [comment]
Thank you for suggesting this, this will probably be helpful for others using OpenOTP. I haven't heard of it before and not sure how many actually uses that so lets keep this issue open and see if there are many others that wants this to be included in documentation. 

In general, we try to not add additional maintenance unless it's very popular integrations.

**Comment by oddlittlebird** [comment]
Do we want to add a tutorial to address this?

**Comment by marefr** [comment]
Closing this due to lack of response. No others have shown interest in this.
