### ISSUE TITLE
there exists security about SQL injection attacks

### ISSUE THREAD

**Issue by AryTing** [grafana/grafana#17656]
**What happened**: using burp scanner to scan the grafana, it reports a high level severity. 
the detail messages are as follows:
`Issue detail
The core parameter appears to be vulnerable to SQL injection attacks. The payload ' was submitted in the core parameter, and a database error message was returned. You should review the contents of the error message, and the application's handling of other input, to confirm whether a vulnerability is present.
The database appears to be PostgreSQL.` 

**Request:** 
`GET /grafanating/api/plugins?core=0'&embedded=0 HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://127.0.0.1/grafanating/?orgId=3
X-Grafana-Org-Id: 3
Cookie: grafana_session=85449c200df1517e5abc90d3754f27ef
Connection: close
Cache-Control: max-age=0`

**Response:**
`HTTP/1.1 200 OK
Date: Mon, 17 Jun 2019 09:47:41 GMT
Content-Type: application/json
Connection: close
Vary: Accept-Encoding
Cache-Control: no-cache
Expires: -1
Pragma: no-cache
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 13357

[{"name":"Alert List","type":"panel","id":"alertlist","enabled":true,"pinned":false,"info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"Shows list of alerts and thei
...[SNIP]...
panel/pluginlist/img/icn-dashlist-panel.svg"},"screenshots":null,"version":"","updated":""},"latestVersion":"","hasUpdate":false,"defaultNavUrl":"/grafanating/plugins/pluginlist/","state":""},{"name":"PostgreSQL","type":"datasource","id":"postgres","enabled":true,"pinned":false,"info":{"author":{"name":"Grafana Project","url":"https://grafana.com"},"description":"PostgreSQL Data Source for Grafana","links":nu
...[SNIP]...`

**What you expected to happen**:  no this issue

**How to reproduce it (as minimally and precisely as possible)**: use burp scan tool

**Anything else we need to know?**: 

**Environment**: 
- Grafana version: v6.2.2
- Data source type & version: 10.3.15-MariaDB
- OS Grafana is installed on: k8s
- User OS & Browser:  firefox
- Grafana plugins: no 
- Others:

**Comment by torkelo** [comment]
> Issue detail The core parameter appears to be vulnerable to SQL injection attacks. The payload ' was submitted in the core parameter, and a database error message was returned. You should review the contents of the error message, and the application's handling of other input, to confirm whether a vulnerability is present. The database appears to be PostgreSQL.

There must be a mistake in the scanner tool.

GET /grafanating/api/plugins?core=0'&embedded=0

This API does not even create a SQL query as plugins are in memory. Secondly, there was no error message returned as the scanner reports.

**Comment by AryTing** [comment]
Thanks for your reply.
