### ISSUE TITLE
{{name.keyword}} not working in Alias in v6

### ISSUE THREAD

**Issue by trevorndodds** [grafana/grafana#17664]
**What happened**: I've been using {{name.keyword}}-{{field}} in my Alias field to display the severname when hovering over a graph
![image](https://user-images.githubusercontent.com/10899305/59767456-5dd8ea00-9270-11e9-98ab-4515ded80fac.png)

**What you expected to happen**: shows the name keyword value

**How to reproduce it (as minimally and precisely as possible)**: use a elastichsearch Terms as an alias

**Anything else we need to know?**: this was working on previous versions < 6

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Elasticsearch v6
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome / Windows
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
what does you query return? check query inspector

**Comment by trevorndodds** [comment]
Thanks, I see my problem. I was using a static custom variable (name.keyword) in Group By (Which used to work)
![image](https://user-images.githubusercontent.com/10899305/59771476-c4153b00-9277-11e9-9d20-9884282bd8b3.png)
if I replace that with name.keyword then the Alias {{name.keyword}} works fine.
