### ISSUE TITLE
Frontend performance in Explore

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#17663]
Currently there is a fair bit of lag when entering text into a QueryField and logs are displayed. I did a little bit of digging and it seems like the main culprit is the Logs element, which is re-rendering whenever QueryField changes (i.e. on keypress)

Profile:
<img width="1365" alt="Screenshot 2019-06-19 at 13 21 06" src="https://user-images.githubusercontent.com/45561153/59765669-778d2800-9296-11e9-80f8-0f42c8532233.png">

Elements re-rendered on keypress are highlighted:
<img width="1619" alt="Screenshot 2019-06-19 at 13 25 17" src="https://user-images.githubusercontent.com/45561153/59765696-87a50780-9296-11e9-8542-2310a7fa8c27.png">

One approach that might improve performance is reimplementing `shouldComponentUpdate` for `Logs.tsx` so that it only re-renders when some subset of props change. (Maybe `this.props.loading`?)

**Comment by marefr** [comment]
May be related to this change I made https://github.com/grafana/grafana/pull/16793/files#diff-41a0c07d4ace9d7b762563c546be3f89R253, basically using log row index as key instead of "sort of unique key" of log line.

**Comment by kaydelaney** [comment]
> May be related to this change I made https://github.com/grafana/grafana/pull/16793/files#diff-41a0c07d4ace9d7b762563c546be3f89R253, basically using log row index as key instead of "sort of unique key" of log line.

This would make sense. From React docs:

> We don’t recommend using indexes for keys if the order of items may change. This can negatively impact performance and may cause issues with component state. Check out Robin Pokorny’s article for an in-depth explanation on the negative impacts of using an index as a key. If you choose not to assign an explicit key to list items then React will default to using indexes as keys.

A link to the article mentioned: https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by marefr** [comment]
The problem though is making a unique key for log lines for some datasources, e.g. Loki and Influx which doesn't have a unique identifier. Elasticsearch have unique identifiers of each document. For Loki we used a combination of nanosecond timestamp and labels, but still that wasn't unique.

**Comment by kaydelaney** [comment]
> The problem though is making a unique key for log lines for some datasources, e.g. Loki and Influx which doesn't have a unique identifier. Elasticsearch have unique identifiers of each document. For Loki we used a combination of nanosecond timestamp and labels, but still that wasn't unique.

I think using packages like `uuid` or `shortid` for generating unique keys is fairly common practice in the React world (it's suggested in the article linked above for example), unless there's some reason we can't go that route?
