### ISSUE TITLE
2.0b3 - Improve error message when connection from client to server is flaky

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1766]
I was in an area with marginal wifi while using the dashboard received this error a few times:

![image](https://cloud.githubusercontent.com/assets/917241/7110711/4c868e70-e1b6-11e4-9ac3-6e962f585eaa.png)

I assume Grafana is generating it?  If true, how about something like "Communication error with Grafana server.  Please try again later."

**Comment by torkelo** [comment]
no that is NOT a grafana error :)

**Comment by maddenca** [comment]
Thanks.  I saw this again today and traced it back to the vSphere client.  I'll open a bug with those 'enterprise' software guys...:-)
