### ISSUE TITLE
Consider renaming SeriesData to DataFrame

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17670]
We have recently merged `TimeSeries` and `TableData` into `SeriesData` -- this was a name that felt like a good compromise between the two.

Before it gets set in stone and I think we should remove "Series" from the name since it does not necessarily represent "Series".  TableData would be a find name, but that would be too hard to support the legacy variations.

`DataFrame` is a named used in other libraries to support this same idea:
* http://www.r-tutor.com/r-introduction/data-frame
* https://pandas.pydata.org/pandas-docs/stable/reference/frame.html 
* https://arrow.apache.org/docs/js/interfaces/dataframe.html

We should remove Series from the name so that it still feels like a natural choice for data like: histograms, lists of things, logs, or anything you may put in Excell

**Comment by ryantxu** [comment]
The description in pandas is pretty close to what we have:

> Two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns).

The only thing that makes our SeriesData a bit different is that it has `labels` and `meta` in addition to the rows+columns

**Comment by torkelo** [comment]
> The only thing that makes our SeriesData a bit different is that it has labels and meta in addition to the rows+columns

yes, but close enough :)
