### ISSUE TITLE
Add mips64el build archive

### ISSUE THREAD

**Issue by LizZzxx** [grafana/grafana#17679]
**What would you like to be added**:

**Why is this needed**:

**Comment by aocenas** [comment]
Hey @LizZzxx, please add a bit more info what is the issue you have.

**Comment by LizZzxx** [comment]
I need a mips package , will you build one for me?Thanks a lot!




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/21/2019 00:31, Andrej Ocenas wrote:

Hey @LizZzxx, please add a bit more info what is the issue you have.

**Comment by aocenas** [comment]
I don't think this is on our backlog right now but you should be able to build grafana for mips from source.

**Comment by marefr** [comment]
I don't think this currently is something that the Grafana project will be able to maintain. Will close this for now, but consider reopen if a lot of users upvotes this feature.

**Comment by LizZzxx** [comment]
ok thanks a lot！


| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/22/2019 20:18, Marcus Efraimsson wrote:

I don't think this currently is something that the Grafana project will be able to maintain. Will close this for now, but consider reopen if a lot of users upvotes this feature.

**Comment by LizZzxx** [comment]
Hello,
How to get the Chinese package for grafana!  

Thanks




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/24/2019 14:03, 张学霞 wrote:
ok thanks a lot！


| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/22/2019 20:18, Marcus Efraimsson wrote:

I don't think this currently is something that the Grafana project will be able to maintain. Will close this for now, but consider reopen if a lot of users upvotes this feature.

**Comment by qiyongxiao** [comment]
> ok thanks a lot！ | | 张学霞 邮箱：15562592336@163.com | 签名由 网易邮箱大师 定制 On 06/22/2019 20:18, Marcus Efraimsson wrote: I don't think this currently is something that the Grafana project will be able to maintain. Will close this for now, but consider reopen if a lot of users upvotes this feature. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

你已经编译好龙芯平台上的grafana了吗？我编译出错
```
GOOS=linux GOARCH=mips make build-go                                   19-08-02 21:14
build go files
GO111MODULE=on go run build.go build
fork/exec /var/folders/_l/496nf5g13h10jw_9919kr8fm0000gn/T/go-build805541314/b001/exe/build: exec format error
make: *** [build-go] Error 1
```

**Comment by Doorer** [comment]
> > ok thanks a lot！ | | 张学霞 邮箱：[15562592336@163.com](mailto:15562592336@163.com) | 签名由 网易邮箱大师 定制 On 06/22/2019 20:18, Marcus Efraimsson wrote: I don't think this currently is something that the Grafana project will be able to maintain. Will close this for now, but consider reopen if a lot of users upvotes this feature. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 你已经编译好龙芯平台上的grafana了吗？我编译出错
> 
> ```
> GOOS=linux GOARCH=mips make build-go                                   19-08-02 21:14
> build go files
> GO111MODULE=on go run build.go build
> fork/exec /var/folders/_l/496nf5g13h10jw_9919kr8fm0000gn/T/go-build805541314/b001/exe/build: exec format error
> make: *** [build-go] Error 1
> ```
I compile 6.6.2
go build -ldflags -w -X main.version=6.6.2 -X main.commit=3fa63cf -X main.buildstamp=1582200229 -X main.buildBranch=heads/v6.6.2 -mod=vendor -o ./bin/linux-mips64le/grafana-cli ./pkg/cmd/grafana-cli
