### ISSUE TITLE
Graph legend tables: Pin value column(s) to right for fixed widths

### ISSUE THREAD

**Issue by Khord** [grafana/grafana#17671]
**What would you like to be added**:
It would be nice, when set to fixed width, if side legend tables kept the value column pinned to the right and truncated any text in the name column

**Why is this needed**:
With fixed width, long names cause all the values to be pushed past the bound box (right panel in screenshot with fixed width 250). Auto width makes the graph laughable to look at (left panel in screenshot)

<img width="1336" alt="Screen Shot 2019-06-19 at 3 19 35 PM" src="https://user-images.githubusercontent.com/21085666/59796097-c0e77280-92aa-11e9-83b8-0001c9ad44fa.png">

**Comment by aocenas** [comment]
@Khord with fixed width the legend should be separately scrollable, so the values are still accessible in a way. Would that be enough or do you think that having an option to truncate the names would still be preferable?

**Comment by Khord** [comment]
I think it's beneficial to truncate the names with fixed widths, as dashboards are often sitting refreshing on monitors without any user interaction and people would like to see the top numbers without interaction.

Even if not for that use case, it's not a nice user experience to have to scroll left and right repeatedly to read the table and mentally line the values up with the names.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
