### ISSUE TITLE
Investigate load test errors "socket: too many open files"

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#17680]
**What happened**:
The load test log contains records like the following:

`t=2019-06-11T18:19:14+0200 lvl=eror msg="Failed to log in as user, specified in auth proxy header" logger=context error="dial tcp 127.0.0.1:3306: **socket: too many open files**"
t=2019-06-11T18:19:14+0200 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/2/api/v1/query_range **status=500** remote_addr=127.0.0.1 time_ms=1 size=36 referer=`

I have used MySQL database but I think the same errors occur with the other databases too.

**How to reproduce it (as minimally and precisely as possible)**:

setup MySQL (or other database) and run the load tests.

**Anything else we need to know?**:

maybe irrelevant but when I run the tests I had the auth proxy enabled too.

**Environment**:
- Grafana version:
6.2.2
- OS Grafana is installed on:
mac os x 10.14.5

**Comment by aocenas** [comment]
@papagian wasn't this the issue with max open file setting or is this something else?

**Comment by marefr** [comment]
I don't reckon I've seen this error.

**Comment by marefr** [comment]
Will close this for now since it seems related to environment/setup.
