### ISSUE TITLE
Interval variables should also be exposed as milliseconds

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#17682]
**What would you like to be added**:

Interval variables are currently exposed as an human readable string, eg. 5m, 1h, 1d and data sources convert this value to a number where needed. I had like to have this interval variable exposed in milliseconds (like `$__interval_ms` exists for built-in `$__interval`).

**Why is this needed**:

My goal is to graph request rate rather than request count using an Elasticsearch data source. Rate can be computed by dividing request count by the interval. However because interval variables are only exposed as human readable string there is no way to feed the right value to the bucket script.

![image](https://user-images.githubusercontent.com/1764725/59833091-a2828500-9345-11e9-9b73-00b232eef4d5.png)

I assume this could be useful for other data source and use cases too.

**Comment by cykl** [comment]
Rather than using a `_ms` suffix, would it make sense to add a new variable formatting option, ie. `${myinterval:toMillis}` ? Adding a new formatting option also seems easier to implement, like ~3 LOCs in `template_srv` to invoke `kbn.interval_to_ms`.

**Comment by Aa-aron** [comment]
Is there a macro possibly available for this?

**Comment by mtanda** [comment]
This is similar discussion for `$__from` and `$__to` .
https://github.com/grafana/grafana/issues/15903

**Comment by grovecai** [comment]
it's a very useful feature, we want this too, but the pull request still not accepted

**Comment by cykl** [comment]
@grovecai While not exactly what I was looking for, 7.0 introduced https://grafana.com/docs/grafana/latest/panels/queries/#query-options. I was able to replace many interval variables by panel query options and use __interval and __interval_ms. 

It does not address all use cases, and I still think think this RFE is valid, but situation got better since 7.0 release.
