### ISSUE TITLE
Save dashboard modal is shown when dashboard was scrolled

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#17684]
**What happened**:
I'm testing grafana 6 with my existing grafana 5 dashboards.
If I scroll a dashboard and then switch to another dashboard it would ask me if I want to save my changes (even no changes where made)

**What you expected to happen**:
Nothing, if nothing changed no need to ask if to save the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
For me it was consistent, use a dahboard (read from disk maybe it matters) scroll down a bit switch to a different dashboard.

**Anything else we need to know?**:
Dashboards are loaded from file

**Environment**:
- Grafana version:
6.2.2 and 6.2.4

**Trying to identify the problem, in Grafana version 6.1.6 this does not happen**

- Data source type & version:
prometheus
- OS Grafana is installed on:
docker over fedora
- User OS & Browser:
fedora/chrome
- Grafana plugins:
prometheus, alertmanager, piechart, 
- Others:

**Comment by aocenas** [comment]
@amnonh thanks for the report. Is it possible for you to share the dashboard json? Could be some specific panel/layout that triggers the issue.

**Comment by amnonh** [comment]
I can attach a few of the dashboards, but it was consistent on all dashboards

[scylla-dash.master.json.txt](https://github.com/grafana/grafana/files/3317522/scylla-dash.master.json.txt)
[scylla-dash-per-server.master.json.txt](https://github.com/grafana/grafana/files/3317523/scylla-dash-per-server.master.json.txt)

**Comment by dprokop** [comment]
@amnonh thanks for sending those over. I was able to reproduce the issue with the dashboards you sent. Seems like the dashboard save model is being updated when dashboard is scrolled. Let us take a look at how to fix that!

**Comment by amnonh** [comment]
Is there a future release for the fix?

**Comment by torkelo** [comment]
If you get this is means panel migrations (new defaults) are being applied as the panels load when you scroll, just scroll to the bottom and save the dashboard and this should no longer happen again.

**Comment by amnonh** [comment]
It's not applicable for dashboards that are loaded from file

**Comment by torkelo** [comment]
Sure it is, just have to view json model and update the file

**Comment by perfectayush** [comment]
Shouldn't this migration happen when updating grafana via a batch command?

**Comment by amnonh** [comment]
This makes it unusable for automatic systems.

It's a resent change, the same dashboard works in 6.1

**Comment by torkelo** [comment]
It's due to panels being loaded as you scroll, and panels, when they load, can apply new defaults and schema migrations. The unsaved changes tracker will store the original 1-2 seconds after dashboard load to compare against. 

We need to rethink how changes are detected in order to fix this, no easy fix solution that I can see.

**Comment by rscot231** [comment]
I am encountering similar behavior with provisioned dashboards. Has there been any work toward a fix?

**Comment by torkelo** [comment]
rolling into this issue: https://github.com/grafana/grafana/issues/24663
