### ISSUE TITLE
Unable to Display Graphs

### ISSUE THREAD

**Issue by MayankSainiTk20** [grafana/grafana#1768]
Hi 

I am trying to display Graphs in grafana but I am not able to do the same

I have hosted the grafana over this IP: http://130.211.152.52/grafana. And added two datasource influxdb and grafana.

There is a database of name jmeter under influxdb and i am able to get data from the sin series which is under test database by running the following command 
curl -G 'http://localhost:8086/db/grafana/series?u=**&p=**' --data-urlencode "q=select * from sin"

Please let me know if i am missing something or please tell me how to add datasources from ui in Grafana

**Comment by torkelo** [comment]
try using your ip on the grafana config file, you cannot use localhost in config.js because influxdb is accessed directly from the browser.

**Comment by MayankSainiTk20** [comment]
Yes I have used my ip but still no luck 

My config.js is this 
 
// == Configuration
// config.js is where you will find the core Grafana configuration. This file contains parameter that
// must be set before Grafana is run for the first time.

define(['settings'], function(Settings) {


  return new Settings({

      /* Data sources
      * ========================================================
      * Datasources are used to fetch metrics, annotations, and serve as dashboard storage
      *  - You can have multiple of the same type.
      *  - grafanaDB: true    marks it for use for dashboard storage
      *  - default: true      marks the datasource as the default metric source (if you have multiple)
      *  - basic authentication: use url syntax http://username:password@domain:port
      */

      // InfluxDB example setup (the InfluxDB databases specified need to exist)
      datasources: {
        influxdb: {
          default: true,
          type: 'influxdb',
          url: "http://130.211.152.52:8086/db/jmeter",
          username: '**',
          password: '**',
        },
        grafana: {
          type: 'influxdb',
          url: "http://130.211.152.52:8086/db/grafana",
          username: '**',
          password: '**',
          grafanaDB: true
        },
      },


      // Graphite & Elasticsearch example setup
      /*
      datasources: {
        graphite: {
          type: 'graphite',
          url: "http://my.graphite.server.com:8080",
        },
        elasticsearch: {
          type: 'elasticsearch',
          url: "http://my.elastic.server.com:9200",
          index: 'grafana-dash',
          grafanaDB: true,
        }
      },
      */

      // OpenTSDB & Elasticsearch example setup
      /*
      datasources: {
        opentsdb: {
          type: 'opentsdb',
          url: "http://opentsdb.server:4242",
        },
        elasticsearch: {
          type: 'elasticsearch',
          url: "http://my.elastic.server.com:9200",
          index: 'grafana-dash',
          grafanaDB: true,
        }
      },
      */

      /* Global configuration options
      * ========================================================
      */

      // specify the limit for dashboard search results
      search: {
        max_results: 100
      },

      // default home dashboard
      default_route: '/dashboard/file/default.json',

      // set to false to disable unsaved changes warning
      unsaved_changes_warning: true,
     // set the default timespan for the playlist feature
      // Example: "1m", "1h"
      playlist_timespan: "1m",

      // If you want to specify password before saving, please specify it below
      // The purpose of this password is not security, but to stop some users from accidentally changing dashboards
      admin: {
        password: ''
      },

      // Change window title prefix from 'Grafana - <dashboard title>'
      window_title_prefix: 'Grafana - ',

      // Add your own custom panels
      plugins: {
        // list of plugin panels
        panels: [],
        // requirejs modules in plugins folder that should be loaded
        // for example custom datasources
        dependencies: [],
      }

    });
});

**Comment by torkelo** [comment]
http://130.211.152.52:8086/ does not seem to be accessible, have you opened these ports in the firewall ?

**Comment by MayankSainiTk20** [comment]
I have opened the ports but I am not able to access it but able to access with localhost
I think i am missing something

**Comment by torkelo** [comment]
well Grafana 1.9.1 must access it from the browser, so maybe your port opening didnt work?

Btw,  Grafana 2.0 which comes with its own backend can access data sources via localhost as it supports a proxy feature.
