### ISSUE TITLE
Bar Gauge missing label in case theres only one metric

### ISSUE THREAD

**Issue by Alexul** [grafana/grafana#17683]
**What happened**:
<img width="231" alt="Screen Shot 2019-06-20 at 12 21 47" src="https://user-images.githubusercontent.com/10867201/59837580-217fb980-9356-11e9-9926-bb849ab368bb.png">
Label disappeared when there's only one metric
**What you expected to happen**:
<img width="229" alt="Screen Shot 2019-06-20 at 12 21 57" src="https://user-images.githubusercontent.com/10867201/59837628-38261080-9356-11e9-840e-c55070da1f5d.png">
Always show legend
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.3
- Data source type & version: any
- OS Grafana is installed on: debian
- User OS & Browser: safari/chrome
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
Hey @Alexul this is the default behaviour, do not show label if not set, if multiple series show title by default so you are able to tell them apart. If you want series label to show explicitly even for single series you can set the label like this:
<img width="362" alt="Screenshot 2019-06-21 at 16 02 17" src="https://user-images.githubusercontent.com/1014802/59928119-55cea500-943e-11e9-874e-e361bc56cd0c.png">

**Comment by kcentralsquare** [comment]
@aocenas $__series_name doesn't work for me.
![image](https://user-images.githubusercontent.com/67913256/89546117-36c1dc80-d7d2-11ea-9e6a-c6d3e99ba74e.png)

**Comment by evertmulder** [comment]
> @aocenas $__series_name doesn't work for me.

This worked for me: `${__series.name}`

**Comment by aocenas** [comment]
Ah sorry yeah probably had a typo in the name (underscore instead of comma) but I think both `${__series.name}` and `$__series.name` should work.

**Comment by 2opremio** [comment]
I have the same issue, but unfortunately the `${__series.name}` trick doesn't help because I am displaying numeric values and the title is composed by the non-numeric field values.

**Comment by 2opremio** [comment]
It seems I can use `$__cell_{N}` but it doesn't respect the unit `time:` overrides I applied

**Comment by nmummau** [comment]
None of these  things worked for me on 
But `${__field.name}` did work. Hope this helps someone else. Grafana v9.0.5

![image](https://user-images.githubusercontent.com/10524529/231584110-33d6ffbe-f358-4879-b0bc-cd585a770405.png)

**Comment by sheilahu** [comment]
I tried all the above but none of them is giving me a valid name according to the legend I specified. `${__series.name}` does work but it's showing `Series (A)` which doesn't mean anything. Still looking for a fix.
