### ISSUE TITLE
Graphite Query editor breaks queries when editing (using graphite with tags)

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#17696]
Very similar to #15237 but with template variables instead of series refs.

**What happened**:

Using a variable in the `highestMax` function for the `limit` parameter breaks the query (it gets moved into the `seriesByTag` expression). 

**What you expected to happen**:

It leaves it where it was defined and interpolates the value at query time. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Define a variable `Limit` with value like `10`. 
1. Construct a graphite tagged query, add the function `highestMax($Limit)` (in the query builder UI, not the text-based).
1. Toggle to text-based and see that `$Limit` has moved into the `seriesByTag` function

Example input (built, not typed) / expected output:
`highestMax(seriesByTag( 'name=requests.out.max'), $Limit)`

Actual result:
`highestMax(seriesByTag($Limit, 'name=requests.out.max'))`

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Enterprise v6.2.3 (8a30e47
- Data source type & version: Graphite w/ tags (Running Metrictank underneath)
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: Mac OSX / Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed and fix coming in v6.3 (beta soon, stable in ~2 weeks)
