### ISSUE TITLE
[2.0 beta2] values rounded in the 'tooltip' when there's big differences in metrics min and max

### ISSUE THREAD

**Issue by jraby** [grafana/grafana#1769]
This is kind of a usability problem for us.
For graphs with similar values, the tooltip shows values with a few decimal precision, which is great:
![image](https://cloud.githubusercontent.com/assets/2365261/7117919/deed5b0a-e1c9-11e4-926e-7756b0494def.png)

However, it seems that when there a big difference between the min and max values of metrics represented in the graph, the values are rounded:
![image](https://cloud.githubusercontent.com/assets/2365261/7117943/0863831a-e1ca-11e4-85b8-8f4d27cbcd3e.png)

![image](https://cloud.githubusercontent.com/assets/2365261/7117809/36f9c74e-e1c9-11e4-8400-a75cec10ec2d.png)

This makes the graph less useful than it could be since in this particular case I'm really interested in the decimal part of the small number.

I find this behaviour counter intuitive, but I'm not sure what would be best,  make the number of decimal shown configurable per graph, per metric?  sounds like a lot of knobs that won't be used that often.
In any case, I don't think grafana should round the values as this behaviour is surprising and shows wrong values.

**Comment by torkelo** [comment]
for cases like this you have to override the auto decimal precision (which is based around min/max for all series), you can override the decimal precision for the tooltip and legend values in the graph editor > Axis & Grid  tab

**Comment by jraby** [comment]
Yeah I just saw that.  Isn't that a bit strange that the 'auto' algorithm would decide to round values ?
I mean it is pretty rare that you get exact values in real life...

What's more, the rounding doesn't seem to occur in the 'edit view'

for example:
edit view:
![image](https://cloud.githubusercontent.com/assets/2365261/7118311/4bbd0346-e1cc-11e4-9fd5-11106d2f4bd2.png)

dashboard view:
![image](https://cloud.githubusercontent.com/assets/2365261/7118319/5c13b29e-e1cc-11e4-8c3c-9549e781fb8d.png)

**Comment by torkelo** [comment]
well the rounding is based on the max/min and the grid steps for the graph (it is used to calculated the exact needed decimals for the y-axis ticks), this works really well for the ticks but not always for the legend and tooltip.

**Comment by jraby** [comment]
Is there a way to set a default/global decimal value or do I have to set it for all graphs?

**Comment by torkelo** [comment]
So when you enter edit mode the graph might become higher (so more space between y-axis ticks), that is why the decimals might change when you enter edit mode, or zoom in / out on the graph. 

No there is no global option for this.

**Comment by jraby** [comment]
Alright thanks.
still it seems counter intuitive even if there's a technical reason behind the behaviour.

**Comment by torkelo** [comment]
@jraby the other way would be to have forced decimals always even when they would not be needed, I have tried to update the auto decimal code to handle as many cases as possible (it uses some pretty sophisticated math and number theory), but it is to expensive to use per series & per value for the legend and tooltip displays.

**Comment by jraby** [comment]
I understand, thanks for the detailed explanation, I'll just add something to set the decimals for all our graph.
