### ISSUE TITLE
Can't delete API-KEY.

### ISSUE THREAD

**Issue by fog1985** [grafana/grafana#17690]
**What happened**:
I am creating API-KEY using curl and HTTP/API. All is good and it's created.
But when I try to delete it I get the message that it has been deleted but in fact, it stays untouched and present.

**What you expected to happen**:
API-KEY is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create key:
curl -s -L -XPOST http://100.68.19.96:80/api/auth/keys -H "Content-Type: application/json" --user "admin:PASS" --data '{"name": "prod_deployment_annotations", "role": "Editor"}'

Delete key:
curl -L -XDELETE -H "Authorization: Bearer eyJrIjoiWllrZFMyb...JvZF9kiaWQiOjF9" -H "Content-Type: application/json" http://100.68.19.96:80/api/auth/keys/prod_deployment_annotations
OR
curl -s -L -XDELETE -H "Content-Type: application/json" --user "admin:PASS" http://100.68.19.96:80/api/auth/keys/prod_deployment_annotations

And I get a response as follow:
```{"message":"API key deleted"}```

**Anything else we need to know?**:
nope

**Environment**:
- Grafana version: v6.2.0
- Data source type & version: not sure what to be provided here.
- OS Grafana is installed on: Debian GNU/Linux 9 (stretch)
- User OS & Browser: Attach to Docker container. Hence the same.

**Comment by marefr** [comment]
The delete api token only supports deleting by id and not by name, see [documentation](https://grafana.com/docs/http_api/auth/#delete-api-key) for reference.

**Comment by fog1985** [comment]
> The delete api token only supports deleting by id and not by name, see [documentation](https://grafana.com/docs/http_api/auth/#delete-api-key) for reference.

Hi @marefr ,
Thanks for the quick reply. I have seen it (documentation).
But how do I find out api-key's id?

**Comment by marefr** [comment]
The only current supported way is [listing all api keys](https://grafana.com/docs/http_api/auth/#api-keys).

**Comment by marefr** [comment]
Let me know if you would like this issue to be a feature request of better api support for api tokens and I'll reopen this and cleanip the title and description.
