### ISSUE TITLE
Inconsistent Panel ID between GUI and API for 6 out of 135 graphs

### ISSUE THREAD

**Issue by maestrx** [grafana/grafana#17693]
**What happened**: 
Inconsistent Panel ID between GUI and API for 6 out of 135 graphs

**What you expected to happen**: 
to have same IDs as with all other graphs

**How to reproduce it (as minimally and precisely as possible)**: 
I can reproduce this situation on those 6 graphs anytime

**Anything else we need to know?**:
I’m not sure what can cause it, but I’ve different panel ID between GUI and (API & DB). I’ve done restart of the grafana service as well to be sure. This is happening for 6 out of 135 graphs/panels.

In GUI, I click view on the relevant graph and check the value of the panelId variable. Its different from the “ïd” of the API data returned for the same graph. Ive got the content of the grafana.db sqlite db and I can find the “id” for the graph corresponding to the API version. The GUI panelID is not present anywhere in the API output or sqlite dashboard output.

**Environment**:
- Grafana version: Grafana v5.4.2 (d812109)
- Data source type & version:  N/A
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Win7 Firefox
- Grafana plugins: 
- Others:

**Comment by marefr** [comment]
Sure you're not have repeated rows/panels defined? Then it will explain the panel id inconsistencies. Please include example data that underlines the inconsistencies.

**Comment by maestrx** [comment]
Can you please describe the use case that will explain the inconsistency? Not sure how to put it here, but I'll try to give you more data...

**Comment by maestrx** [comment]
`          {
            "aliasColors": {
              "openDJ 19981": "#967302"
            },
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": "ES_metricbeat",
            "fill": 0,
            "gridPos": {
              "h": 7,
              "w": 6,
              "x": 18,
              "y": 91
            },
            "height": "",
            "id": 294,
            "legend": {
              "alignAsTable": false,
              "avg": true,
              "current": false,
              "max": true,
              "min": false,
              "rightSide": false,
              "show": true,
              "sideWidth": null,
              "total": false,
              "values": true
            },
            "lines": true,
            "linewidth": 1,
            "links": [],
            "minSpan": 1,
            "nullPointMode": "null",
            "percentage": false,
            "pointradius": 5,
            "points": false,
            "renderer": "flot",
            "repeat": null,
            "repeatDirection": "h",
            "repeatIteration": 1558644038330,
            "repeatPanelId": 35,
            "scopedVars": {
              "hostnamewls": {
                "selected": false,
                "text": "eef19003-ofrintapp4-10058188",
                "value": "eef19003-ofrintapp4-10058188"
              }
            },
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": true,
            "targets": [
              {
                "bucketAggs": [
                  {
                    "fake": true,
                    "field": "system.process.name",
                    "id": "3",
                    "settings": {
                      "min_doc_count": 1,
                      "order": "desc",
                      "orderBy": "1",
                      "size": "0"
                    },
                    "type": "terms"
                  },
                  {
                    "fake": true,
                    "field": "system.process.pid",
                    "id": "4",
                    "settings": {
                      "min_doc_count": 1,
                      "order": "desc",
                      "orderBy": "1",
                      "size": "0"
                    },
                    "type": "terms"
                  },
                  {
                    "field": "@timestamp",
                    "id": "2",
                    "settings": {
                      "interval": "10s",
                      "min_doc_count": 0,
                      "trimEdges": 0
                    },
                    "type": "date_histogram"
                  }
                ],
                "dsType": "elasticsearch",
                "metrics": [
                  {
                    "field": "system.process.memory.rss.bytes",
                    "id": "1",
                    "meta": {},
                    "settings": {},
                    "type": "avg"
                  }
                ],
                "query": "metricset.name:\"process\" AND fields.customer:[[customer]] AND fields.country:[[country]] AND fields.env:[[env]]  AND beat.hostname:\"[[hostnamewls]]\"",
                "refId": "A",
                "timeField": "@timestamp"
              }
            ],
            "thresholds": [],
            "timeFrom": null,
            "timeRegions": [],
            "timeShift": null,
            "title": "Memory RSS per process [[hostnamewls]]",
            "tooltip": {
              "shared": true,
              "sort": 0,
              "value_type": "individual"
            },
            "transparent": false,
            "type": "graph",
            "xaxis": {
              "buckets": null,
              "mode": "time",
              "name": null,
              "show": true,
              "values": []
            },
            "yaxes": [
              {
                "format": "bytes",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": "0",
                "show": true
              },
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": false
              }
            ],
            "yaxis": {
              "align": false,
              "alignLevel": null
            }
          },`

**Comment by maestrx** [comment]
[https://ibb.co/fdVcgmm](url)

**Comment by maestrx** [comment]
In the API dump and screenshot you can see the same graph. In the JSPON you can see id=294 and in teh GUI you can see panelId=467.

Just to make the things complete: I'm writing a script that will iterate through all graphs and render all of them and generates a custom (HTML/PDF/EMAIL) report using various timeframes. So in this case, I fail to generate those renders as the rendering of panels with "non existent" ID timeouts...

**Comment by marefr** [comment]
You have repeated panels enabled `"repeatPanelId": 35,`.
