### ISSUE TITLE
Datasource: Azure Monitor Relative Alerting

### ISSUE THREAD

**Issue by lygris** [grafana/grafana#17700]
**What would you like to be added**:
Trigger alerts based on a metric relative to another metric.
**Why is this needed**:
It would be nice when monitoring our azure application to be able to alert on 400 errors returning but relative to the number of total requests coming in.

We have had malicious attacks that trip the 400 errors alert which is intended, but we also have a lot of regular users that mistype passwords/etc.

During periods of expected high requests, the 400 errors alerts trips but it is expected due to the amount of requests we are receiving. So for example, if i could alert on 400 errors being over 10% of all request traffic, it would trigger the alert.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
