### ISSUE TITLE
Bar Gauge graph external rendering does not match expected output  

### ISSUE THREAD

**Issue by bhaskarguthalu** [grafana/grafana#17701]
Hi There ,
I m using Grafana v6.2.1 (9e40b07) in the dashbord the bar gauge looks fine ,but when use "Direct link rendered image" the images data looks scattered ,please find the attached image for the reference 
![image](https://user-images.githubusercontent.com/51289174/59921937-ee6c2180-944c-11e9-8eb7-b004488a88bf.png)

**What you expected to happen**: look  should be same as dashboard 

**How to reproduce it (as minimally and precisely as possible)**

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.2.1 (9e40b07)
- Data source type & version: Elastic search 7
- OS Grafana is installed on:CentOS Linux release 7.6.1810 (Core)
- User OS & Browser: win 10 Google Chrome Version 75.0.3770.100 (Official Build) (64-bit) and IE 11
- Grafana plugins:
- Others:

**Comment by hamzamaal** [comment]
I am having the same issue. On-screen the panel looks fine:
![image](https://user-images.githubusercontent.com/32955591/65665658-562d9c00-e03c-11e9-87a1-1b9de1b54ad0.png)

however, when I do a render I get this:

![image](https://user-images.githubusercontent.com/32955591/65665696-70677a00-e03c-11e9-9627-710a4d81af89.png)

I have also tried using the iframe embed in my webpage, it displays fine on screen:

![image](https://user-images.githubusercontent.com/32955591/65666031-1a470680-e03d-11e9-9520-9a063cd7b75a.png)


but in print preview, the graph disappears leaving only the writing, this is the only grafana iframe which does this, all other pie and graphs iframes work fine.

![image](https://user-images.githubusercontent.com/32955591/65666146-5a0dee00-e03d-11e9-8c3f-7f038f123252.png)

Environment:

Grafana version: v6.3.6 (fdd2117)
Data source type & version: InfluxDB
OS Grafana is installed on:CentOS Linux release 7.7.1908 (Core)
User OS & Browser: Mac OS & Windows server 2016 Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Grafana plugins: Bar Gauge

**Comment by torkelo** [comment]
For this panel to render properly use the new image rendering plugin:

https://grafana.com/grafana/plugins/grafana-image-renderer

The built-in phantomjs (deprecated) rendering method does not render properly for some of these new panels.
