### ISSUE TITLE
grafana Bad -c option

### ISSUE THREAD

**Issue by manjotsc** [grafana/grafana#17706]
I am running grafana on FreeBSD, and it was working fine for few days and it’s failing to start :“Starting grafana.
Bad -c option
/usr/local/etc/rc.d/grafana: WARNING: failed to start grafana”

**Comment by marefr** [comment]
We don't maintain any official freebsd distribution besides tarballs so you'll have to ask for help  on our [community site](https://community.grafana.com/) or elsewhere. Github are mainly for feature requests and bug reports.
