### ISSUE TITLE
Failed to share/render to png dashboard panel on Grafana 6.2.4

### ISSUE THREAD

**Issue by aloababa** [grafana/grafana#17703]
**Grafana setup**:

Our Grafana is behind a reverse proxy (for HA).

Config (on both instance):

```
[server]
domain = example.com
enable_gzip = true
enforce_domain = true
http_port = 3000
protocol = http
root_url = https://%(domain)s/
```

**What happened**:

When using the direct render link the phantomjs process gets killed every time.
I got the following logs in Grafana:

```
Jun 21 14:19:25 myhost grafana-server[24198]: t=2019-06-21T14:19:25+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/XXXXXXXXXXXX/my-dash?orgId=1&refresh=15s&panelId=36&from=1561123164542&to=1561126764542&width=1000&height=500&tz=Europe%2FParis&render=1 width=1000 height=500 png=/grafana/data/png/j31L1XbDQWpKpLRIDP6J.png domain=localhost timeout=60 renderKey=someK3y]" timezone=Europe/Paris
Jun 21 14:20:25 myhost grafana-server[24198]: t=2019-06-21T14:20:25+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: http://localhost:3000/d-solo/XXXXXXXXXXXX/my-dash?orgId=1&refresh=15s&panelId=36&from=1561123164542&to=1561126764542&width=1000&height=500&tz=Europe%2FParis&render=1 status: success 60000\n"
Jun 21 14:20:25 myhost grafana-server[24198]: t=2019-06-21T14:20:25+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
Jun 21 14:20:25 myhost grafana-server[24198]: t=2019-06-21T14:20:25+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
Jun 21 14:20:25 myhost grafana-server[24198]: t=2019-06-21T14:20:25+0000 lvl=eror msg="Rendering failed." logger=context userId=8 orgId=1 uname=user@example.com error="signal: killed"
Jun 21 14:20:25 myhost grafana-server[24198]: t=2019-06-21T14:20:25+0000 lvl=eror msg="Request Completed" logger=context userId=8 orgId=1 uname=user@example.com method=GET path=/render/d-solo/XXXXXXXXXXXX/my-dash status=500 remote_addr=*.*.*.* time_ms=60005 size=722 referer="https://mygrafana.com/d/XXXXXXXXXXXX/my-dash?orgId=1&refresh=15s&fullscreen&edit&panelId=36"
```

And weird thing when an alert notification is triggered i got the following:

```
Jun 21 14:36:04 my-host grafana-server[24254]: t=2019-06-21T14:36:04+0000 lvl=info msg=Rendering logger=rendering path="d-solo/XXXXXXXXXXXXXX/my-dash?orgId=1&panelId=36"
Jun 21 14:36:04 my-host grafana-server[24254]: t=2019-06-21T14:36:04+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/XXXXXXXXXXXXXX/my-dash?orgId=1&panelId=36&render=1 width=1000 height=500 png=/grafana/data/png/Y9gEKEC9HYwZbtonLRUV.png domain=localhost timeout=10 renderKey=somek3y]" timezone=
Jun 21 14:36:15 my-host grafana-server[24254]: t=2019-06-21T14:36:15+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: http://localhost:3000/d-solo/XXXXXXXXXXXXXX/my-dash?orgId=1&panelId=36&render=1 status: success 10000\n"
Jun 21 14:36:15 my-host grafana-server[24254]: t=2019-06-21T14:36:15+0000 lvl=dbug msg="Image rendered" logger=rendering path=/grafana/data/png/Y9gEKEC9HYwZbtonLRUV.png
```

So the render seems to work but the generated image is just a black background with the panel title:

![nYRuRu3inll3cMVFpNnS](https://user-images.githubusercontent.com/8696292/59933296-7e0fd100-9449-11e9-8a8a-8da905fad6cb.png)

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Any
- OS Grafana is installed on: Ubuntu 18.04.2 LTS
- User OS & Browser: Ubuntu 18.10, Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by briangann** [comment]
There is a timeout involved with rendering, which it appears you are hitting. External rendering will spawn phantomjs and if the datasource is slow (or the grafana server itself is overloaded), the time to render will be exceeded (60 seconds).

This results in the process being killed, and an empty png.

You can increase the default timeout to a higher value in grafana.ini:

```
[alerts]
evaluation_timeout_seconds = 120
```

We've seen this in our alerting also where a query took 65-70 seconds to respond and was automatically killed resulting in blank graphs.

**Comment by aloababa** [comment]
Already tried to increase that value but the problem is somewhere else. It seems the phantomjs process enters in an infinite loop because no matter what value i set it always reach the timeout.

**Comment by torkelo** [comment]
Think this error could be related to little memory for phantomjs, is this run in a container with low memory limit?

**Comment by aloababa** [comment]
It's not running in a container.

I made a free -m while phantomjs was running:

```
root@host:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           1955         328         221           0        1406        1453
Swap:             0           0           0
```

So it seems the memory is fine.

**Comment by sairam0903** [comment]
Same issue happening to me as well. I have upgraded my grafana to 6.2.3v and the Direct link render image link is not working as expected.

**Comment by marefr** [comment]
Can you browse one of your grafana instances using http://localhost:3000? If not, you probably have a reverse proxy configuration issue. Instead try this config and enforce domain in your reverse proxy instead:

```
[server]
domain = localhost
enable_gzip = true
enforce_domain = false
http_port = 3000
protocol = http
root_url = https://example.com/
```

**Comment by RalphSu** [comment]
See the same issue after update my grafana. Is there an conclusion of root cause ?

**Comment by justClouds** [comment]
Same for me. No rendering anymore and PhantomJS times out with the same error message as stated by OP.
Any updates on this?

**Comment by suprememoocow** [comment]
We're seeing this problem too. If I run `phantomjs` with the same parameters as Grafana uses, but set `debug=true`, I see the following output:

```console
$ /usr/share/grafana/tools/phantomjs/phantomjs --ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js 'url=http://localhost:3000/d-solo/alerts-sat_cpu/alerts-cpu-saturation-detail?orgId=1&from=1578016135214&to=1578037735214&var-PROMETHEUS_DS=Global&var-environment=gprd&var-type=web&var-stage=main&panelId=2&width=1000&height=500&tz=UTC&render=1' width=1000 height=500 png=/var/lib/grafana/png/S35HdGi7BawqxQ5y2DE6.png domain=localhost timeout=60 renderKey=SECRET

2020-01-03T08:01:18 [DEBUG] CookieJar - Saved "renderKey=SECRET; domain=.localhost; path=/"
2020-01-03T08:01:18 [DEBUG] CookieJar - Rejected Cookie "renderKey=SECRET; domain=localhost"
2020-01-03T08:01:18 [DEBUG] WebPage - updateLoadingProgress: 10
2020-01-03T08:01:18 [DEBUG] WebPage - updateLoadingProgress: 50
2020-01-03T08:01:18 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(AuthenticationRequiredError) ( "Host requires authentication" ) URL: "http://localhost:3000/d-solo/alerts-sat_cpu/alerts-cpu-saturation-detail?orgId=1&from=1578016135214&to=1578037735214&var-PROMETHEUS_DS=Global&var-environment=gprd&var-type=web&var-stage=main&panelId=2&width=1000&height=500&tz=UTC&render=1"
```

So, it appears that the `renderKey` cookie being used for authentication is not sufficient for performing authentication, and the web page returns a 401 `AuthenticationRequiredError`. 

After that `phantomjs` just loops around, evaluating whether the page is loaded by checking `document.querySelectorAll('plugin-component').length > 0`, which will always return zero (since the page returned a 401)

Cross-reference: https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8836

**Comment by felskrone** [comment]
Any update here? I am having the exact same issue running with grafana 6.6.0 in a docker container with 512M of Ram assigned. Current Ram usage ist just around 30MB though, so its definitely not a Ram problem.

The panel im trying to access through the api renders within seconds in web interface. Going through the api or running phantomjs manually does not make a difference. Neither does increasing the timeout.

A manual exec in the container always shows this output

```bash
bash-5.0$ /usr/share/grafana/tools/phantomjs/phantomjs \
> --ignore-ssl-errors=true \
> --web-security=true \
> --local-url-access=false \
> --debug=false \
> /usr/share/grafana/tools/phantomjs/render.js \
> url="http://localhost:3000/traffic-per-device/db/traffic-per-network-device?orgId=1&panelId=17&from=1582027200&to=1582030800height=500&render=1" \
> width=800 \
> height=400 \
> png=/var/lib/grafana/png/FRN4PZoegWGNHOa4TMfW.png \
> domain=localhost \
> timeout=60 \
> renderKey="ChIhPzjd7vdH3gRMqWo42oVNz1n08NXb]" \
> debug=true \
> timezone=
Loading a web page: http://localhost:3000/traffic-per-device/db/traffic-per-network-device?orgId=1&panelId=17&from=1582027200&to=1582030800height=500&render=1 status: success 60000



ERROR: TypeError: undefined is not an object (evaluating 'container[0].getBoundingClientRect')
TRACE:
 -> undefined: 6
 -> : 7

  phantomjs://code/render.js:48 in onError
TypeError: null is not an object (evaluating 'bb.width')

  phantomjs://code/render.js:68 in checkIsReady
```

**Comment by justClouds** [comment]
I moved away from PhantomJS, which is deprecated anyway, and now run the separate [grafana-image-renderer](https://hub.docker.com/r/grafana/grafana-image-renderer) container provided with headless Chrome-based rendering. Works like a charm with Grafana 6.4 and 6.6 so far.

**Comment by hekmon** [comment]
> I moved away from PhantomJS, which is deprecated anyway, and now run the separate [grafana-image-renderer](https://hub.docker.com/r/grafana/grafana-image-renderer) container provided with headless Chrome-based rendering. Works like a charm with Grafana 6.4 and 6.6 so far.

This. All good on our side too. I think this issue could be closed @aloababa ?

**Comment by felskrone** [comment]
Awesome, will try that. Thanks!

**Comment by felskrone** [comment]
What version are you running? latest, 1.0.10 and 1.0.9 fail to start with

```bash
internal/modules/cjs/loader.js:796
    throw err;
    ^
 Error: Cannot find module '/etc/grafana/build/app.js'
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
     at internal/main/run_main_module.js:17:11 {
   code: 'MODULE_NOT_FOUND',
   requireStack: []
}```

**Comment by aloababa** [comment]
All good for me.
