### ISSUE TITLE
Setting pending user team

### ISSUE THREAD

**Issue by gmistick** [grafana/grafana#17708]
**What happened**:
I added a user , it is pending invite. Then i wanted to add the user to specific team but failed to do so. (The user was not in the user list to add to the team)
**What you expected to happen**:
I expect that pending and non-pending users can be added to teams.

**How to reproduce it (as minimally and precisely as possible)**:
Just add new team
 create new user
don't accept invite yet
 try to add it to team.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.4.0
- Data source type & version: NA
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome, Linux.
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Good feedback. Sadly an invite is not the same as a created user. 

You can create a user instead in the server admin section.

**Comment by muffl0n** [comment]
Same as #18292?

**Comment by marefr** [comment]
Duplicate of #18292

**Comment by marefr** [comment]
Thanks @muffl0n
