### ISSUE TITLE
PromQueryEditor: Start/End awareness if metadata queries

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#17711]
The one piece of functionality we're missing over the existing editor is start/end awareness of metadata queries (when requesting labels, `start` and `end` from the visible range should be sent as well). We should add this in a follow-up PR.

_Originally posted by @davkal in https://github.com/grafana/grafana/pull/15364#issuecomment-504012183_

**Comment by marefr** [comment]
Need input from @davkal. Is this issue suppose to add `start` and `end` for all metadata queries and/or is there additional things thought of to be included?

**Comment by davkal** [comment]
This was fixed by #16851
