### ISSUE TITLE
Update urls for docs site to match the new static url

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#17716]
**What happened**:
We've put all static files in the website in the `static` directory so we need to update paths in the doc site to match that one. Now there are 404's.

**What you expected to happen**:
Show images and videos correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Build docs site locally.

**Anything else we need to know?**:
Might need to be fixed in @adeverteuil's project as well.

**Comment by oddlittlebird** [comment]
@DanCech , please take a look at this. Has this been done? Is it still relevant?

**Comment by DanCech** [comment]
My understanding is that this is out of date now.
