### ISSUE TITLE
UID not unique across organizations in one grafana install

### ISSUE THREAD

**Issue by josefkorbel** [grafana/grafana#17712]
**What happened**:
Multiple dashboards from different organizations have same UID, seems like the seed is always the same.

**What you expected to happen**:
From the docs `"The unique identifier (uid) of a dashboard can be used for uniquely identify a dashboard between multiple Grafana installs"` - I expect UID to be unique across grafana installation.

**How to reproduce it (as minimally and precisely as possible)**:
Create Few Dashboards in different organisations, observe the UIDs.

**Environment**:
- Grafana version: 6.0.0
- OS Grafana is installed on: Ubuntu 16.04

**Comment by dprokop** [comment]
@josefkorbel thank's for reporting this. It actually works as intended, as dashboard is uniquely identified by UID and organisation ID combo.

**Comment by josefkorbel** [comment]
Thanks for the info @dprokop, is this really intended?

We ran into very weird bugs because we were parsing dashboards by UID regex. What about using the orgId as seed? Feels like wasting the 40-character space when two dashboards created after each other in different organisations have the exact same UID.

**Comment by torkelo** [comment]
Do you have examples of 2 ids generated in two different orgs that are identical? We have no other reports like it and cannot replicate it.

**Comment by marefr** [comment]
We intentionally designed it using org id and uid as unique combo so that you could for example import the same dashboards from grafana.com to different organizations and/or use provisioning to different organization using the same dashboards.

**Comment by josefkorbel** [comment]
@torkelo sure.

```

https://example.com/d/1pCZpEPiz/kd-1?orgId=9
https://example.com/d/1pCZpEPiz/sl-1?orgId=2


https://example.com/d/dNrdOwoiz/vc-1?orgId=5
https://example.com/d/dNrdOwoiz/intens?orgId=7

```

**Comment by torkelo** [comment]
can you re-create this using api on a fresh Grafana install? 

Do you have multiple grafana servers setup in HA? 

Can you describe the steps you take to create these dashboards? Are they created new from scratch or imported?

**Comment by josefkorbel** [comment]
@torkelo 
> can you re-create this using api on a fresh Grafana install?

I can as soon as I will have some time to do so.
>Do you have multiple grafana servers setup in HA?

No, single instance

> Can you describe the steps you take to create these dashboards? Are they created new from scratch or imported?

Most of the dashboards we use are created from a json template. After reading through the exported dashboard I've found this:
```
"iteration": 1561455980678
```

Which is, after dividing by 1000, timestamp corresponding to today.
```python
>>> datetime.utcfromtimestamp(1561455980678/1000).strftime('%Y-%m-%d %H:%M:%S')
'2019-06-25 09:46:20'
```  

Is it possible that this value is used as seed, thus the duplicate UIDs?
