### ISSUE TITLE
Position of alert on a graph accords to the event time

### ISSUE THREAD

**Issue by lessenko** [grafana/grafana#17727]
Hi,
I tried to place a alert point on a graphic according to the event time.
The code changing is  on github.com/lessenko/grafana/  in branch: alert-position-on-graphic. 
The screenshorts are appended here.
Thanks.

![Screenshot_20190621_130152](https://user-images.githubusercontent.com/40150500/60021601-f6b99c00-969a-11e9-9b0e-366eb011ba25.png)

![Screenshot_20190621_130715](https://user-images.githubusercontent.com/40150500/60021623-03d68b00-969b-11e9-93e0-647ad20c4754.png)

**Comment by lessenko** [comment]
It's suggested to use **real** time of event for the alerts.

**Comment by lessenko** [comment]
Currently (for **query(A, 11m, now-10m)** for example) position of alert (on graph) is different from true on **10 minutes**.

**Comment by lessenko** [comment]
Currently  the alerts are shifted in regard to events. The screenshot is for illustration of this problem.
Sorry for the long description.
![Screenshot_20190625_083926](https://user-images.githubusercontent.com/40150500/60072634-c7e90780-9726-11e9-9ea6-0888ee46288e.png)

**Comment by dprokop** [comment]
@lessenko thanks for reporting. Are you referring to the alert marks not being aligned with the data points on the graph?

**Comment by lessenko** [comment]
Thanks. Yes, you are right.
 
My solution is on  
https://github.com/lessenko/grafana/ in branch: alert-position-on-graphic.

**Comment by dprokop** [comment]
Thank you, can you please create PR with your solution so that we can review it?

**Comment by lessenko** [comment]
Thank you, you can review it. I have to read (little) about creating PR. Sorry.
