### ISSUE TITLE
Sorting option is needed in variable output [Datasource type]

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#17722]
Sir, 

I have added few data source Grafana server,  and named according to their location

There are few server are busy, and some are most of time ideal.

I would like to sort them based on type of load, Example
instead of ascending (default sort), i need custom sort, say Haifa would be first and Boston should be last.

There are no way to sort.

Let me know if I am missing anything 

Regards, 

Vijay Panchal
![grafana1](https://user-images.githubusercontent.com/52157263/60013697-b8bd7780-969c-11e9-9179-bf9a33b12a88.png)
![grafana1](https://user-images.githubusercontent.com/52157263/60013710-bf4bef00-969c-11e9-9a70-0ca01e3ef003.png)

Attach image has 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vpanchal72** [comment]
my apology, same image uploaded twice

**Comment by dprokop** [comment]
@vpanchal72 thanks for asking. Currently there is no way of sorting those values and they appear according to alphabetical order.

**Comment by vpanchal72** [comment]
Thanks a lot
