### ISSUE TITLE
Table header is missing while there is no data to show.

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#17721]
I have sql statement, which shows failed information of last one hour data, 
most of cases, statement returns value zero. in this case, Grafana table panel shows  "No data to show "

At least, it has to show headers

If same statement has been run on shell window (sql terminal), it shows header.

Option is needed to show header, let me know if I am missing something

Thanks in advance

Regards,

Vijay Panchal
![grafana1](https://user-images.githubusercontent.com/52157263/60008582-f668d300-9691-11e9-90c9-eeb5da7a8c4e.png)
![grafana1](https://user-images.githubusercontent.com/52157263/60008713-2c0dbc00-9692-11e9-9073-4492e9692f3e.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
