### ISSUE TITLE
Graphite PNG graphs do not refresh properly

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#1773]
Summary:
When a dashboard uses server rendered graphs the action of refreshing does not cause the server rendered graphs to update.  This can be done by clicking the upper right refresh icon or control+r.

Steps to Reproduce:
1. (Think this will work) http://play.grafana.org/dashboard/snapshot/f6nSnrfwuDWcOY1kVFcbHOirgVSl11RQ
1a. If above link disappears, change any of the graphs on play.grafana.org to server rendered.
2. Change to last hour.
3. Click refresh or control+r.
4. Notice: flot graphs update, but server rendered graphs are not updated.

**Comment by torkelo** [comment]
Dashboard Snapshots does not work with Graphite rendered pngs.

**Comment by torkelo** [comment]
On a normal dashboard it works. But snapshots are all about embedding the metric data into the dashboard so create a standalone dashboard that can be viewed without any access to any real time series store.

**Comment by gerrickw** [comment]
On a normal dashboard on play.grafana.org it does not work.  I was thinking providing a snapshot link would make it easier to show it is not working, but appears to have caused confusion.

Steps to Reproduce on play.grafana.org:
1. Browse to http://play.grafana.org/
2. Click on the menu for any of the graphs.
3. Edit
4. Click on Display Styles tab
5. Click Graphite PNG radio button
6. Click Back to dashboard
7. Press control+R or the upper right refresh icon.
8. Notice: All flot graphs refresh, but the modified graph to use png fails to update.
9. The same occurs if using auto-refresh from the time range selection in the upper right.

This fails on dashboards and not my intention to relate this to the snapshot view.

Thanks

**Comment by gerrickw** [comment]
Not sure of the normal ticket process here.  Should I create a new ticket when the orginal summary was misunderstood and marked closed?

**Comment by torkelo** [comment]
Sorry, reopened now
