### ISSUE TITLE
grafana-cli: Improve user experience 

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#17735]
**What would you like to be added**:

The `grafana-cli` could do with a few tweaks to improve the user experience:

- [ ] Whenever a default configuration is not set (`homepath` or path to a config) add a confirmation step to indicate the user whenever proceeding is allowed.

- [ ] Reduce the output noise from logging. Leveraging the `filters` configuration within Grafana, conditionally set the logging of the `migrator` to only output when using the `--debug` flag. 

- [x] ~~Move the real `grafana-cli` binary into a `/bin` directory within the Grafana home folder (`/usr/share/grafana`). This clearly signals that the files inside are binaries.~~

- [ ] Add a windows/bat version of the wrapper

**Comment by marefr** [comment]
Please read this [section](https://github.com/grafana/grafana/blob/master/ISSUE_TRIAGE.md#3-categorizing-an-issue) of how we categorize issue. This issue should probably have a `type/feature-request` or `type/refactor` label. If you want to use the `beginner friendly` label please read this [section](https://github.com/grafana/grafana/blob/master/ISSUE_TRIAGE.md#5-requesting-help-from-the-community) how we usually request help from the community using the label `beginner friendly`.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
