### ISSUE TITLE
Release CLI tasks: Improvements and next steps

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#17734]
**What would you like to be added**:

- [ ] Make `scripts/tasks/utils/githubClient.ts` encapsulate everything related to Github. HTTP calls, functions for styling responses as markdown, etc.

There are several tasks that use the GitHub API within our release process. A list of files from where to extract GitHub interaction is: 

- [ ] `scripts/cli/tasks/changelog.ts`  - get a list of issues/PRs by state, label and/or milestone [GitHub API](https://developer.github.com/v3/issues/#list-issues)
- [ ] `scripts/cli/tasks/changelog.ts`  - transform an `Issue` [GitHub API](https://developer.github.com/v3/issues/#list-issues) into a markdown line
- [ ] `scripts/cli/tasks/cherrypick.ts`  - get a list of issues/PRs by state and label (ideally, same implementation as the previous instance of list searching) 
- [ ] `scripts/cli/tasks/cherrypick.ts`  - get details for an issue [GitHub API](https://developer.github.com/v3/issues/)
- [ ] `scripts/cli/tasks/close-milestone.ts`  -  get a list of issues/PRs by state, label and, milestone (ideally, same implementation as the previous instance of list searching) [GitHub API](https://developer.github.com/v3/issues/milestones/)
- [ ] `scripts/cli/tasks/close-milestone.ts`  - get details for a milestone [GitHub API](https://developer.github.com/v3/issues/milestones/)
- [ ] `scripts/cli/tasks/close-milestone.ts`  - remove label from an issue [GitHub API](https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue)
- [ ] `scripts/cli/tasks/close-milestone.ts`  - close a milestone [GitHub API](https://developer.github.com/v3/issues/milestones/#update-a-milestone)

At the time of writing these are the files that interact with the API, there could be more added in the future so the actual list might diverge by the time this is implemented. 

**Why is this needed**:

Helps us keep encapsulated all GitHub API related logic within one file. Making it easier to test and manta-in.

**Comment by marefr** [comment]
@gotjosh Please read this [section](https://github.com/grafana/grafana/blob/master/ISSUE_TRIAGE.md#5-requesting-help-from-the-community) how we usually request help from the community using the label `beginner friendly`. For this issue it should probably be labeled `type/refactor` or `type/chore`.

**Comment by gotjosh** [comment]
Thanks @marefr for pointing me in that direction - that was quite helpful! if I understand correctly, those two aren't mutually exclusive, right? I agree that the correct type should be chore or refactor but do think this is a good issue for beginners as the scope is well defined.

I'll update the issue to give out a bit more detail on which files should be changed.

**Comment by gotjosh** [comment]
To anyone following along, we at Grafana would love to get this issue done. Sadly, we have other priorities at the moment and are struggling to fit this one in. Feel free to pick this issue up and if any help is needed don't hesitate to reach out. I'd be happy to help!

**Comment by Russiancold** [comment]
I would like to work on this

**Comment by Russiancold** [comment]
@gotjosh Since I'm not experienced with TS, I want to be sure if it's the right way to implement the client API? Should add some interfaces(e.g `Issue`, `PR`...) to let the caller know what to expect in response? Or this variant is fine?

**Comment by gotjosh** [comment]
Apologies for my late response @Russiancold. That is indeed a great first step and it appears to go in the right direction.

Regarding the interfaces, I'd say yes for the reasons you mentioned. Make sure we add tests to the implementation.

Thank you for contribution ❤️ - I have assigned you to this issue and please let me know if you'd like to continue working on this.

**Comment by Russiancold** [comment]
@gotjosh Hi! How would you recommend me to test this? And how to deal with authentication?)

**Comment by Russiancold** [comment]
@gotjosh Also, github tells that we expect 204 code on deleting an issue https://developer.github.com/v3/issues/labels/#delete-a-label However we expect 200
https://github.com/grafana/grafana/blob/4e29357d15dc1ece6ddda0d43fc5139d5c7c27c0/packages/grafana-toolkit/src/cli/tasks/closeMilestone.ts#L51-L56

**Comment by gotjosh** [comment]
@Russiancold something very similar to [this](https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/cli/utils/githubClient.test.ts) as a test.

I'm not sure which of the two is correct. I'm guessing GitHub in this case, would you mind opening a PR with the status code change? Thanks again!
