### ISSUE TITLE
Bar gauge: Add scrolling support 

### ISSUE THREAD

**Issue by walterdolce** [grafana/grafana#17736]
Hi all. I know you are working on it and that this is a new visualisation type currently on beta. I thought I would share this with you sooner rather than later, hoping it is an issue easy enough to fix before the visualisation type goes GA.

Disclaimer: this was my very first time I used the bar gauge, if you think I am using the visualisation incorrectly (i.e. wrong query, wrong approach to visualising the data in question, etc), please let me know and advise. 

I was trying to visualise Kafka consumer lags for topics within Grafana using the bar gauge. I thought it would be nice to have multiple bars visually highlighting which topic has the most lag, given a time frame set.

After configuring the query, this is what I could see:
<img width="1246" alt="Screenshot 2019-06-24 at 16 44 23" src="https://user-images.githubusercontent.com/6195629/60033526-a5aca680-96a0-11e9-8968-b15227ef1d0a.png">

Text as well as the bar and the number on the right become completely unreadable. 

The query I used is as follows:
```
SELECT mean("rep_lag") FROM "kafka_consumer_group" WHERE ("project" = '{{project}}' AND "service" = '{{service-name}}') AND $timeFilter GROUP BY time($__interval), "name" fill(null)
```

The data source used is InfluxDB and the data is coming out of a Kafka instance running on Aiven. Aiven themselves provide a nice line graph using the same query which produces the following visualisation:
<img width="707" alt="Screenshot 2019-06-24 at 16 51 33" src="https://user-images.githubusercontent.com/6195629/60033703-fcb27b80-96a0-11e9-9e69-79c7330d0508.png">

**Steps to reproduce**:
- Get a Kafka instance up and running on Aiven, backed by an InfluxDB instance containing Kafka metrics (also on Aiven)
- Create the InfluxDB data source within Grafana so that it can pull the data from the InfluxDB instance running in Aiven
- Create the bar gauge visualisation using the query above

**Actual Result**:
Please see screenshots above

**Expected Result**
Text, bars and numbers should be readable

**Relevant WCAG Criteria:** [1.4.4](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#resize-text)

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: InfluxDB
- User OS & Browser: macOS, Chrome
- Others:

**Comment by torkelo** [comment]
The bar gauge is not designed for scrolling, 

see example here:
https://play.grafana.org/d/vmie2cmWz/bar-gauge?orgId=1&refresh=10s

**Comment by walterdolce** [comment]
Sure. But some of the graphs in the play area highlight the same problem. The first and last two ones, specifically.

**Comment by ryantxu** [comment]
I think @torkelo's point is that it was not designed with scrolling in mind.  Currently it just divides the space by the number of results and gives each bar that much space.  We could add a mode where you explicitly ask for XX pixels for each result, and get a scrollbar when the data overflows

**Comment by walterdolce** [comment]
I see. I might have naively assumed that the panel could automatically generate scrollable content the same way it does when on a line graph you have the legend in table mode with many line items

**Comment by ivanvalencia** [comment]
I have the same problem trying to render a list of items which don't fit into the graph space. Do you know if this issue is going to be fixed in a short term? Thanks in advance.

**Comment by mykllterry** [comment]
Piling on - I'd like a scrolling horizontal bar chart also.

**Comment by marek-bocian** [comment]
I think that the horizontal scrolling bar is necessary.
When you have a large set of data sources for (vertical) bar guages, some of guages fall hidden outside the panel and the only way to view them is to zoom-out the dashboard which is exteremely inconvenient.
Any developings in that matter? Perhaps some kind of woraround?
