### ISSUE TITLE
Alerting: Improve alert rule testing for all core datasources

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17746]
**What would you like to be added**:
#16286 added support for a debug flag when testing alert rules to indicate that datasource can/should return debug related meta data to be shown in test alert rule ui. That PR specifically improved testing alert rule using the elasticsearch datasource since that one is one of the most hard ones to debug in alerting scenarios.

All the SQL datasources already per default returns query meta data. 

This issue aims to improve alert rule testing for rest of core datasources so that they return query meta data (when debug flag is set):
- Graphite
- Prometheus
- InfluxDB
- CloudWatch
- Azure Monitor
- Stackdriver
- OpenTSDB

**Why is this needed**:
To make it easier for users to understand why their alert rule doesn't work as expected when testing the alert rule.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
