### ISSUE TITLE
Template variable for server/client rendering?

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#1774]
As an improvement it would be nice to use a template variable to switch between png/flot.

Was hoping I could use a custom template variable of $render with {flot,png}, then add "renderer": "$render", but doesn't appear to work.

**Comment by torkelo** [comment]
why would you want this?

**Comment by gerrickw** [comment]
Sometimes users prefer the customization of an image than javascript when rendering of a graph.

Benefits:
 * Speed. Browser is single threaded and auto refreshing every 10-30 seconds when having 30-40+ graphs puts stress on the browser while using flot.  Images are quick.
 * User can quickly right click on a graph and copy the image to throw in an email.  Menu -> Share Link -> Copy image URL -> Adjust size of image in url params -> Copy image to email is a number of steps to explain to users.
 * Users would like the flexibility of javascript graph rendering to highlight issues, but switch to server rendering when wanting a quicker response for a number of graphs.

**Comment by torkelo** [comment]
The browser is usually faster at rendering graphs than graphite rendered images, which is not surprising as a browser is a incredibly optimized rendering machine, compared to the graphite python rendering. 

Do you use Graphite 0.9.12 (un patched without maxDataPoints feature)? I suggest you upgrade to Graphite 0.9.13, then client side graphs will be as fast or faster then the server side images. 

Just compared PNG graphs vs client side graphs on http://play.grafana.org , the javascript graphs refresh a lot fast,  the graph that is configured to use graphite PNG comes in dead last (even when having 30 graphs). 

In Grafana 2.0 you can use the new share dialog to capture an image of any panel (not just the graph panel). Great for sharing. This does not use graphite, it uses Grafanas backend (spins up a phantomjs browser that captures and image that looks the same as the frontend graphs)
