### ISSUE TITLE
Legend max value not accurate with different time ranges

### ISSUE THREAD

**Issue by bunghi** [grafana/grafana#17749]
**What happened**:
When displaying a 30 days period graph panel with min/max/av/current legend the max value is different than a period of time zommed in from this 30 days period. It seems that is an average of max values of that period and not a single stat max value point of the interval.

**What you expected to happen**:
Max value data point of the interval.

**How to reproduce it (as minimally and precisely as possible)**:
Select 30 days period and check max value in the legend. In this example is 22.50:
![image](https://user-images.githubusercontent.com/31234197/60083261-12c24980-973e-11e9-8e3f-8eb154638897.png)

Zoom in a period with max peak and check max value in the legend. In this example i zoomed in day 29/05 and max value is 26.00
![image](https://user-images.githubusercontent.com/31234197/60083361-44d3ab80-973e-11e9-9146-e7ac4b0c53cb.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v5.4.2
- Data source type & version: InfluxDB v1.7.6
- OS Grafana is installed on: Debian Linux 9.9
- User OS & Browser: Google Chrome Version 75.0.3770.90 (Official Build) (64-bit)
- Grafana plugins:
bessler-pictureit-panel @ 1.0.0
flant-statusmap-panel @ 0.0.4
grafana-clock-panel @ 0.0.8
grafana-groupedbarchart-panel @ 1.0.0
grafana-piechart-panel @ 1.1.4
grafana-worldmap-panel @ 0.1.2
larona-epict-panel @ 1.1.0
michaeldmoore-multistat-panel @ 1.2.1
mxswat-separator-panel @ 1.0.0
simpod-json-datasource @ 0.1.4
vonage-status-panel @ 1.0.9
- Others:

**Comment by dprokop** [comment]
@bunghi the max value is calculated based on the data from query response. In order to get accurate max value you should change your query to use Influx's max function.

**Comment by bunghi** [comment]
Thanks @dprokop but can you explain me what does "the max value is calculated based on the data from query response" mean exactly? 

Is there any way to override legend max value with Influx's max function?

**Comment by dprokop** [comment]
> Thanks @dprokop but can you explain me what does "the max value is calculated based on the data from query response" mean exactly?

When you send a query to InfluxDB the results are grouped by default by the specified interval: 

![image](https://user-images.githubusercontent.com/2376619/60097076-e06f1700-9752-11e9-976e-a7884e9de2b0.png)


This means that the data is pre-aggregated into interval buckets. So, the max value calculation (or other calculations in the legend) is performed on the data that does not represent every single datapoint in InfluxDB. And this means, that the values are not accurate min/max values.

> Is there any way to override legend max value with Influx's max function?

No, there isn't. What you can do is to use `max` function in your query to get the accurate max values per bucket.

**Comment by bunghi** [comment]
Thanks @dprokop ! That solved my problem. ;)

**Comment by DjangoPeng** [comment]
Same issue . 
Is there a solution or work around on MySQL?
