### ISSUE TITLE
Setting custom time range results in different data compared to the same predefined range

### ISSUE THREAD

**Issue by thallesferraz** [grafana/grafana#17743]
Good afternoon, I have a problem with the search time of the dashboard, where a period of 1 month  is set(custom time range), it shows the same information for the indicator, and if you set a default time of grafana for 1 month for example show the correct values.

I found the same problem in community :

https://community.grafana.com/t/time-range-override-relative-time/11721

![dash](https://user-images.githubusercontent.com/52176159/60049204-2ae58a80-96a4-11e9-884e-e6f55e80446b.png)

**Comment by dprokop** [comment]
@hallesferraz thanks for reporting. Can you please share the data requests payloads for both situations? From my investigation it seems like the time stamps (from & to) sent with request are the same in both cases (which means that this might be an issue on the datasource side). 

Btw - what datasource are you using?

**Comment by thallesferraz** [comment]
Hi dprokop , the datasource is Zabbix ,  payloads would that ? 

Time default 1 mouth:
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/30",
    "data": {
      "jsonrpc": "2.0",
      "method": "trend.get",
      "params": {
        "output": "extend",
        "trend": "0",
        "itemids": [
          "1834811",
          "1834779",
          "1834938",
          "1834831",
          "1834793",
          "1834973",
          "1834911",
          "1834873",
          "1834840",
          "1834886",
          "1834855",
          "1834803",
          "1834776",
          "1834935",
          "1834829",
          "1834791",
          "1834962",
          "1834872",
          "1834838",
          "1834884",
          "1834849",
          "1834775",
          "1834933",
          "1834825",
          "1834790",
          "1834961",
          "1834802",
          "1834867",
          "1834836",
          "1834883",
          "1834847",
          "1834905",
          "1834932",
          "1834824",
          "1834788",
          "1834944",
          "1834801",
          "1834773",
          "1834834",
          "1834881",
          "1834845",
          "1834902",
          "1834866",
          "1834927",
          "1834823",
          "1834786",
          "1834942",
          "1834800",
          "1834746",
          "1834880",
          "1834844",
          "1834901",
          "1834865",
          "1834925",
          "1834818",
          "1834784",
          "1834941",
          "1834799",
          "1834744",
          "2140758",
          "1834878",
          "1834843",
          "1834900",
          "1834863",
          "1834815",
          "1834782",
          "1834940",
          "1834796",
          "1834742",
          "2024854",
          "1834923",
          "1834876",
          "1834842",
          "1834899",
          "1834861",
          "1834813",
          "1834781",
          "1834939",
          "1834833",
          "1834795",
          "1834740",
          "2024668",
          "1834922",
          "1834874",
          "1834841",
          "1834898",
          "1834859"
        ],
        "sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1556668800,
        "time_till": 1559347200
      },
      "id": 1,
      "auth": "0ddbaf071e712e3bb4d2085da03a3c52"
    }
  },
  "response": {
    "jsonrpc": "2.0",
    "result": [
      {
        "itemid": "1834740",
        "clock": "1556668800",
        "num": "1",
        "value_min": "100.0000",
        "value_avg": "100.0000",
        "value_max": "100.0000"



Time custom :

"xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/30",
    "data": {
      "jsonrpc": "2.0",
      "method": "trend.get",
      "params": {
        "output": "extend",
        "trend": "0",
        "itemids": [
          "1834811",
          "1834779",
          "1834938",
          "1834831",
          "1834793",
          "1834973",
          "1834911",
          "1834873",
          "1834840",
          "1834886",
          "1834855",
          "1834803",
          "1834776",
          "1834935",
          "1834829",
          "1834791",
          "1834962",
          "1834872",
          "1834838",
          "1834884",
          "1834849",
          "1834775",
          "1834933",
          "1834825",
          "1834790",
          "1834961",
          "1834802",
          "1834867",
          "1834836",
          "1834883",
          "1834847",
          "1834905",
          "1834932",
          "1834824",
          "1834788",
          "1834944",
          "1834801",
          "1834773",
          "1834834",
          "1834881",
          "1834845",
          "1834902",
          "1834866",
          "1834927",
          "1834823",
          "1834786",
          "1834942",
          "1834800",
          "1834746",
          "1834880",
          "1834844",
          "1834901",
          "1834865",
          "1834925",
          "1834818",
          "1834784",
          "1834941",
          "1834799",
          "1834744",
          "2140758",
          "1834878",
          "1834843",
          "1834900",
          "1834863",
          "1834815",
          "1834782",
          "1834940",
          "1834796",
          "1834742",
          "2024854",
          "1834923",
          "1834876",
          "1834842",
          "1834899",
          "1834861",
          "1834813",
          "1834781",
          "1834939",
          "1834833",
          "1834795",
          "1834740",
          "2024668",
          "1834922",
          "1834874",
          "1834841",
          "1834898",
          "1834859"
        ],
        "sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1554163200,
        "time_till": 1556668800
      },
      "id": 1,
      "auth": "4c23dda9b73d170c087d4b35e0ef28de"
    }
  },
  "response": {
    "jsonrpc": "2.0",
    "result": [
      {
        "itemid": "1834740",
        "clock": "1554163200",
        "num": "1",
        "value_min": "100.0000",
        "value_avg": "100.0000",
        "value_max": "100.0000"

**Comment by alexanderzobnin** [comment]
Hm, looks strange:
```
Time default 1 mouth:
"time_from": 1556668800,  (01 May 2019 00:00:00 GMT)
"time_till": 1559347200  (01 Jun 2019 00:00:00 GMT)

custom time range
"time_from": 1554163200,  (02 Apr 2019 00:00:00 GMT)
"time_till": 1556668800  (01 May 2019 00:00:00 GMT)
```

**Comment by thallesferraz** [comment]
alexanderzobnin , i set custom time to 1 month  - 01 may to 01 jun

![image](https://user-images.githubusercontent.com/52176159/60205492-b3d8ff00-9827-11e9-8c19-e8ee40d169f5.png)


"sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1556668800,
        "time_till": 1559347200

**Comment by thallesferraz** [comment]
Folks , i found in the documentation that is a feature .

![image](https://user-images.githubusercontent.com/52176159/60296913-7d6db380-98fd-11e9-9bef-07893467bbe2.png)

**Comment by alexanderzobnin** [comment]
@thallesferraz So do you have overrides on your panel? Could you provide panel json?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
