### ISSUE TITLE
Grafana DB Error - packets.go:36: unexpected EOF

### ISSUE THREAD

**Issue by APenketh** [grafana/grafana#17751]
**What happened**:
Upon upgrade to Grafana v6.2.0+ we noticed errors within the MySQL database, specifically an increasing amount of Handshake errors which directly corresponded to the following error message from Grafana logs:
[mysql] 2019/06/25 08:29:32 packets.go:36: unexpected EOF
The main issue is that when there are a high successive number of these errors the server hosting Grafana is blocked in MySQL until a flush host cache is performed leading to downtime of Grafana if all web servers are blocked.

Originally I attempted an upgrade to 6.2.3, then 6.2.4 as that version has come out. When these both had the same symptoms I attempted 6.2.0 which also acted the same. 

**What you expected to happen**:
These errors should not occur.

**How to reproduce it (as minimally and precisely as possible)**:
Grafana running on 6.1.6 and connecting to MySQL Database 5.7.18, upgrade to any version above or on 6.2.0. Behavior shows that COUNT_HANDSHAKE_ERRORS increases and the unexpected EOF lines are printed within Grafana logs.

**Anything else we need to know?**:
conn_max_lifetime is set to default
wait_timeout in MySQL is set to 28800
currently there are just over 3700 alerts setup within Grafana which looks like it leads to alot of DB calls
upon turning on DB logging I noticed some queries taking over a second to complete. 

> t=2019-06-25T09:19:15+0000 lvl=info msg="[SQL] SELECT `id`, `org_id`, `version`, `name`, `type`, `access`, `url`, `password`, `user`, `database`, `basic_auth`, `basic_auth_user`, `basic_auth_password`, `with_credentials`, `is_default`, `json_data`, `secure_json_data`, `read_only`, `created`, `updated` FROM `data_source` WHERE `id`=? AND `org_id`=? LIMIT 1 []interface {}{30, 1} - took: 3.061090819s" logger=sqlstore.xorm

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: N/A
- OS Grafana is installed on: CentOS Linux release 7.3.1611
- User OS & Browser:N/A
- Grafana plugins: 
_Boom Table v1.0.0
Clock v1.0.2
Datatable Panel v0.0.6
Pie Chart v1.3.6
Status Panel v1.0.9
Trend Box v0.1.9
Worldmap Panel v0.2.0_
- Others:

**Comment by marefr** [comment]
@APenketh there's an issue in the go-sql repository that suggest different ways to solve this, here's the issue for reference: https://github.com/go-sql-driver/mysql/issues/674

For example configure the [conn_max_idle](https://grafana.com/docs/installation/configuration/#max-idle-conn) to 0 (zero) which denotes that no idle connections are retained. Grafana's default is 2.

From the database/sql package:
> // If MaxOpenConns is greater than 0 but less than the new MaxIdleConns,
// then the new MaxIdleConns will be reduced to match the MaxOpenConns limit.
//
// If n <= 0, no idle connections are retained.
//
// The default max idle connections is currently 2.
