### ISSUE TITLE
Wrong current value and maybe wrong value on mouseover?

### ISSUE THREAD

**Issue by dtriphaus** [grafana/grafana#1775]
Hi, 

i am using Beta3 of grafana 2.0.0 (and influxdb 0.8.8) and I am facing wrong values in my graph. Made a screenshot to help explaining it. 

it seems as if the current value of graphs is always the FIRST value in the time-period shown and not the real current value.  

Also I am confused by the value shown when moving the mouse on the graph. It always shows the current value and not (what I thought would make sense) the value in the graph "selected" by the crosshair.

Hope the screenshot is attached correctly.

![image](https://cloud.githubusercontent.com/assets/3583268/7131993/54c36ff2-e285-11e4-91be-3b734ce9c80d.png)

**Comment by torkelo** [comment]
What data source are you using and what does your metric query look like? If you use InfluxDB it must end with "order asc"

**Comment by dtriphaus** [comment]
Thanks a lot for the quick answer, my fault, was not using "order asc". Seems to solve both problems for me! Current value is correct now and mousover shows value selected by crosshair!

Thank you!
