### ISSUE TITLE
Loki: Filter by level no longer works

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/grafana#17769]
**What happened**:
Filtering by log levels in the Loki graph legend does not change the log row output. It does change the graph, however. This worked fine in 6.2.4.

**What you expected to happen**:
Log row output filtered according to log level label selected.

**How to reproduce it (as minimally and precisely as possible)**:
![grafana-loki-level-bug](https://user-images.githubusercontent.com/17552371/60131886-00590780-9760-11e9-82d3-4424bdeb35d7.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.3.0-pre (5aa13ee)
- Data source type & version: Loki 0.1.0
- OS Grafana is installed on: Uubntu 18.04
- User OS & Browser: Firefox on MacOS
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Totally get that this used to work. Just not sure that this is the proper way of filtering by log level. Think having a label `level` on loki stream allows you to use the labels feature and filter by log level.

**Comment by steven-sheehy** [comment]
Right, I think that's the ideal endgame, but Loki currently does not provide out of the box level labels so Grafana was guessing them locally. You can see in the image that this level is already associated with the log row entry by coloring it appropriately in the far left column. I don't see why if the log levels are already there they can't be filtered the same way they were in 6.2 until Loki provides a level label.

**Comment by steven-sheehy** [comment]
Looking at the code, this is supposed to work. [`onToggleSeries`](https://github.com/grafana/grafana/blob/5aa13eeb76c0b3c2045cfa5791216e3341777492/public/app/features/explore/Logs.tsx#L220) of the graph calls `onToggleLogLevel` of the `LogsContainer` to adjust the `hiddenLogLevels` which is used to [filter](https://github.com/grafana/grafana/blob/a07296bf24856bb66b2103929af179ee627f8985/public/app/core/logs_model.ts#L176) log rows. This might have regressed with the new logic in `LogsContainer.shouldComponentUpdate()` not taking into account re-rendering do to series toggling.

**Comment by kaydelaney** [comment]
> Looking at the code, this is supposed to work. [`onToggleSeries`](https://github.com/grafana/grafana/blob/5aa13eeb76c0b3c2045cfa5791216e3341777492/public/app/features/explore/Logs.tsx#L220) of the graph calls `onToggleLogLevel` of the `LogsContainer` to adjust the `hiddenLogLevels` which is used to [filter](https://github.com/grafana/grafana/blob/a07296bf24856bb66b2103929af179ee627f8985/public/app/core/logs_model.ts#L176) log rows. This might have regressed with the new logic in `LogsContainer.shouldComponentUpdate()` not taking into account re-rendering do to series toggling.

I looked a bit into this, and while `onToggleSeries` is indeed passed down as a prop from `LogsContainer` to `Graph`, `Graph` doesn't actually seem to make use of the prop at all, instead making use of its own `onSeriesToggle` method, which has its own internal state representing which labels are hidden/selected, hence why the graph updates despite `LogsContainer.shouldComponentUpdate()` not including `hiddenLogLevels` in its logic.

Did this ever actually work? I tried finding a commit where it did, but came up empty. Maybe someone else has an idea?

**Comment by steven-sheehy** [comment]
@kaydelaney Yes, it worked in 6.2.4. Just tested again

Grafana v6.2.4 (ee01897)

**Comment by kaydelaney** [comment]
@steven-sheehy Thanks, I'll look a bit more into it

**Comment by kaydelaney** [comment]
Spent a bit more time `git bisect`-ing to figure out when the problem was introduced. It seems like the following PR is where it started: https://github.com/grafana/grafana/pull/17027
I'll spend a bit more time tomorrow looking into how it can be remedied.

**Comment by marefr** [comment]
Great investigate @kaydelaney I have a fix incoming (I think).
