### ISSUE TITLE
Loki: Add annotation support

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#17762]

**Comment by ryantxu** [comment]
I am hoping we can replace the special annotation query with any query that returns:
```
{
time
text
endTime?
tags?
userInfo?...
}
```
Details still need worked out :)

**Comment by lorenwest** [comment]
Upvoting as we would prefer storing immutable system generated events/annotations in Loki than the mutable Grafana Annotations API

**Comment by aocenas** [comment]
Taking a stab at this. @davkal does it make sense to use label values as tags automatically for the annotations?

**Comment by aocenas** [comment]
@ryantxu 
> I am hoping we can replace the special annotation query ...

Would make sense imho, but I think right now with all the other changes going on with datasource API I will do this the old way and we can change it later on.

**Comment by davkal** [comment]
Yeah, i'm happy with label values being the tags in the annotation.

**Comment by ryantxu** [comment]
If we are fine replacing the work soon (hopefully 6.5) than I am +1 for trying

**Comment by lorenwest** [comment]
Thank you all for your work on this!
