### ISSUE TITLE
Improve CSV data export

### ISSUE THREAD

**Issue by gauthd** [grafana/grafana#1777]
It would be great to be able to customize the way data is exported as CSV: when we click on CSV export button, a dialog window could be opened (as share panel) with the query editor available  (group by time, fill - no fill) so that we can customize the actual query to export CSV. 

![issue](https://cloud.githubusercontent.com/assets/9574005/7140376/3c2916b8-e2cb-11e4-8a3c-183c5bb14c49.JPG)

Thanks for this awesome tool !!!

**Comment by torkelo** [comment]
Good idea, but this will most likely be very far down the prio list, so will close this for now.

**Comment by gauthd** [comment]
For the record, solving this issue will allow us to be able to extract data with low resolution (1s to 30s) over a large period (months to year) in order to do post-treatment which very interesting for all scientific data treatment. Right now, with this kind of request, it's easy to crash your web browser.

**Comment by tomerikko** [comment]
Good Idea, will love to see that as well.
Tomer.

**Comment by bbinet** [comment]
+1 it would be helpful to be able to extract raw data (or grouping by time 1s so that we get high resolution data)

**Comment by lbardelli** [comment]
@all 
Any update about that ?

10x

**Comment by HorstBort** [comment]
Would love to see this implemented! Looking at a time series with low resolution in the browser and downloading full resolution data for further processing would greatly improve our workflow.

**Comment by blancmatter** [comment]
+1, It would be good to get a raw output to CSV of the values (i.e better than 1s resolution if the data exists for this)
