### ISSUE TITLE
Alert is not activated with at current time

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#17779]
SQL statement is 
======================================
SELECT
  date_trunc('m', created_at_utc  at time zone '-6:30') AS time, 
  farm AS metric,
  buildfailin6hrs
FROM rtc_history_log_table
WHERE
  $__timeFilter(created_at_utc) AND FARM IN ('Pune','Boston','Haifa','Herzeliya')and created_at_utc is not null
ORDER BY 1,2
======================================
Which is printing graph 
![grafa1](https://user-images.githubusercontent.com/52157263/60177544-c7d82d00-9836-11e9-8e18-cdb4f5ea3987.png)

My Alert rules are 
![2](https://user-images.githubusercontent.com/52157263/60177650-0c63c880-9837-11e9-9e1e-af981ec672c1.png)

Test rules shows 
![2](https://user-images.githubusercontent.com/52157263/60177722-3e752a80-9837-11e9-961f-956828f817a4.png)

As per Test rules 
Values are Boston:0, Haifa:1, Herzeliya:2, Pune:1 and state is okay
But as per graph
![2](https://user-images.githubusercontent.com/52157263/60177868-9f9cfe00-9837-11e9-9702-ec3bb00ee767.png)
Values are Boston:0, Haifa:13, Herzeliya:19, Pune:4 

Let me know if I am doing some thing wrong

Thanks, 

Vijay Panchal

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
if you set the same time range in the time picker (from: 10m, to: now-3m) then what does the graph look like?=

**Comment by vpanchal72** [comment]
Graph disappears if I set time now-10m to now-3m, to view current time graph, atkeast i need to set time to 7h

![2](https://user-images.githubusercontent.com/52157263/60239408-3b2b7e80-98cb-11e9-9b7b-b5ad9a14960e.png)

**Comment by torkelo** [comment]
ok, if graph disappear, the alert query will also get the same.

Your query intervals might not support such a small time window
