### ISSUE TITLE
Error: "Cannot read property 'then' of null" on snapshot with annotations

### ISSUE THREAD

**Issue by Fiery-Fenix** [grafana/grafana#17783]
**What happened**:
Error `Cannot read property 'then' of null` on chart panel on snapshot.
Stack trace:
```
Panel data error: TypeError: Cannot read property 'then' of null
    at t.issueQueries (app.e019a5d81a66edfe4d30.js:formatted:34048)
    at angular.js:17051
    at angular.js:17095
    at l.$digest (angular.js:18232)
    at angular.js:18462
    at h (angular.js:6362)
    at angular.js:6642
```

**What you expected to happen**:
Chart panel displays data

**How to reproduce it (as minimally and precisely as possible)**:
1. Create dashboard with chart panel
2. Add annotation that will return empty set in defined time range
3. Create snapshot
4. View created snapshot

**Anything else we need to know?**:
Error happens here: https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/module.ts#L183
Property `annotationsSrv.datasourcePromises` can be `null` in case of snapshot definition contains annotation with empty set.
Root cause is here: https://github.com/grafana/grafana/blob/master/public/app/features/annotations/annotations_srv.ts#L114
In case when property `annotation.snapshotData` contains empty array `[]`, property `annotationsSrv.datasourcePromises` will not be set at all and by default it is initialized with value `null` which causes error in this bug report.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: vertamedia-clickhouse-datasource, 1.8.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Chrome 75

**Comment by dprokop** [comment]
@Fiery-Fenix thanks for reporting. I've tried to reproduce according to the steps you have described, and indeed, this is a bug.

**Comment by mnehad** [comment]
No news regarding the correction of this bug? 
It is really annoying for us because we use a lot snapshots / annotations to share our metrics and it's always broken in 6.5.2...
![grafana_bug](https://user-images.githubusercontent.com/1503632/77753474-d489eb80-7029-11ea-8c3c-de7af0eae77d.png)

**Comment by ashharrison90** [comment]
hi @Fiery-Fenix @mnehad 👋 

apologies for the super slow response on this. i've tried recreating in Grafana v8.1.4 and it seems the problem has been fixed. if i've made a mistake or you're still seeing the issue please feel free to leave a comment and we'll reevaluate.

thanks! 😄
