### ISSUE TITLE
Feature request: add jump forward/backward time buttons

### ISSUE THREAD

**Issue by PRI-mcallen** [grafana/grafana#1778]
It would be very handy if there was a "step forward" and "step backward" button that would move the time range forward/back by the current x-axis extent.  This would make it much easier to browse datasets while zoomed in to observe detail, without having to click "zoom out" or do a bunch of clicking.  I often find myself wishing for this when searching for an anomaly signature in a large data set.

**Comment by torkelo** [comment]
good idea, already an issue for this though, #119
