### ISSUE TITLE
Map does not load

### ISSUE THREAD

**Issue by huangyuan666** [grafana/grafana#17796]
**What happened**:Map does not load

**What you expected to happen**:Map loading normally

**How to reproduce it (as minimally and precisely as possible)**:
Map does not load
This is when the map cannot be loaded.
![image](https://user-images.githubusercontent.com/24352334/60253893-7f387680-98ff-11e9-8377-53a52f561915.png)
The following map is normal loading, how can I recover?
![image](https://user-images.githubusercontent.com/24352334/60253994-ad1dbb00-98ff-11e9-8307-869342ad1a35.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on: ubuntu
- User OS & Browser:google chrome
- Grafana plugins:
- Others:

**Comment by ryantxu** [comment]
what do you see in the console output?  Are the tile requests failing?

**Comment by huangyuan666** [comment]
The console output did not report an error, but it did not load!

**Comment by dprokop** [comment]
@huangyuan666  thanks for reporting. I've just checked and I wasn't able to reproduce the issue. Are you still encountering it? 

Also, what Grafana version are you using?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
