### ISSUE TITLE
constant variable with single quote appears with double times.

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#17790]
part of my sql statement is 
WHERE $__timeFilter(created_at_utc) AND FARM IN ('Pune','Boston','Haifa','Herzeliya')

I have created constant variable called Farms with value as 'Pune','Boston','Haifa','Herzeliya'
Refer attached image 

now using this parameter in sql statement as 
WHERE  $__timeFilter(created_at_utc) AND FARM IN ($Farms)

Generated sql is 
WHERE created_at_utc BETWEEN '2019-06-26T06:48:35.379Z' AND '2019-06-27T13:48:35.379Z' AND FARM IN (''Pune'',''Boston'',''Haifa'',''Herzeliya'')

now look at the parameter value ''Pune'',''Boston'',''Haifa'',''Herzeliya''
all single quote are appears twice........because of this, it fails ...... is the BUG

Let me know, it there is any work around  or am i doing some thing wrong ?

Regards, 

Vijay Panchal

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@vpanchal72 have you tried using variable values without single quotes?

**Comment by torkelo** [comment]
you have to use variable syntax `${variabe:raw}` to disable all quoting or ecsaping

**Comment by vpanchal72** [comment]
Thank you Very much, it is started working

**Comment by vpanchal72** [comment]
Yes, it is working without any problem
Thanks
