### ISSUE TITLE
Feature request: jump to first data point ability

### ISSUE THREAD

**Issue by PRI-mcallen** [grafana/grafana#1779]
For sparse data sets, it would be convenient to be able to jump to the first actual data point.

**Comment by torkelo** [comment]
how?

**Comment by torkelo** [comment]
Or rather what do you mean, "jump to first data point", do you want grafana to query the whole series (for all time) and then align the time range to the first time point found in the series?

**Comment by PRI-mcallen** [comment]
You could do something like this for influxdb:
select * from myseries order asc limit 1
To get the first data point, and then zoom to that section of the time series.
It would also be nice to say "jump to the datapoint closest in time to my current time window" but I didn't see an efficient way to do that in influxdb.  I think jumping to the first point would be sufficient.

**Comment by dmakhno** [comment]
@torkelo, sorry if this is outdated.
I think I feel the need in this feature too.
We use grafana in CI for performance testing (grafana+prometheus if its metter)
When CI complete, grafana is alive for a while. If I jump in the next morning to the dashboards, I do need accurate search to find the beginning. Would be nice if I can move the "from" to the first data.
