### ISSUE TITLE
table panel with more rows or pages or scroll bars renders (share) incorrect

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#17792]
**What happened**:
I created a table panel (real table mode) and show something like 500 rows using psql datasource. In default visualisation I can scroll it and have pages working. When I (share -> image) render it I get a png with incorrect size and scroll bars. When I navigate to page 2 of the table and render (share -> image) it I get still page 1. When I disable scroll in visualisation pages get also disabled. When I render it the png size is still incorrect and the table cropped.

**What you expected to happen**:
bug list:
1) scroll disable should not disable pages - those things should be independent
2) rendering a table with scroll enabled should not render the scroll bar and not pages navigation
3) rendering a table should respect the size used in the dashboard and not use some default size which just cropps the table
4) render url (for tables) without given size should guess a useable size (e.g. width with all columns visible, height with all rows visible)
5) it should be possible to render/share (get png of) the other pages of a table

**How to reproduce it (as minimally and precisely as possible)**:
create a psql table with a few hundret rows (and optinally something like 30 columns or wide columns). create a table panel, set it to table transform: table. query with something like "select * from table_name". Try to get a png rendered of table page 2.

**Anything else we need to know?**:
The general idea is to use it together with: https://github.com/IzakMarais/reporter
Sometimes a table makes more sense then a graph - especially in a report.

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: psql (db version 9.4)
- OS Grafana is installed on: debian/ubuntu
- User OS & Browser: chrome
- Grafana plugins: pie chart
- Others: https://github.com/IzakMarais/reporter

**Comment by torkelo** [comment]
PNG rendering of tables will only show you page 1, you have to adjust the height of the image (using height url param) if you want to capture a more rows. 

> 1. scroll disable should not disable pages - those things should be independent

Yea, that is strange. Think we will solve this in our new table panel (will have infinite scroll and no paging).

> 2. it should be possible to render/share (get png of) the other pages of a table

Not sure we will support this. 

> 3. rendering a table should respect the size used in the dashboard and not use some default size which just cropps the table

PNG rendering does not respect this, you can control height & width using url params for the final size of the image. 

> 4. render url (for tables) without given size should guess a useable size (e.g. width with all columns visible, height with all rows visible)

We currently does not support this as for rendering we need to define width & height of image before panel rendering. 

> 5. it should be possible to render/share (get png of) the other pages of a table

This is not currently supported, have to increase page & image height instead.
