### ISSUE TITLE
Support watch for datasource files

### ISSUE THREAD

**Issue by jwendell** [grafana/grafana#17804]
Currently datasource files are read at the startup, and if they change during the execution, then those changes will be ignored.

In a scenario where those files come from a Kubernetes ConfigMap, for example, if the user changes the config map, the file is updated automatically, but Grafana is not aware of that. The workaround is to restart the pod.

**Comment by torkelo** [comment]
if you hit this api you can trigger a reload without a restart:

https://grafana.com/docs/http_api/admin/#reload-provisioning-configurations

**Comment by Duologic** [comment]
This looks very similar to #12878.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
