### ISSUE TITLE
Feature Request: Option for Alert Marks on Graph

### ISSUE THREAD

**Issue by lessenko** [grafana/grafana#17801]
I would like to suggest the option for marking of alert on graph.

Currently “alert annotations events  are not directly linked to when **data points** that triggered the alert happened, but when the alert fired".  So it is not very clear  on graph where the parameters are out from permissible conditions (alert reason).

The option is useful to  find  more easy these **data points**. 

It's more actual, if query has time range  (for example) as 10m, now-2m 

Following figures illustrate different logic  for same data and query.

Thanks.

Fig_1-current_logic 

![Fig_1-current_logic](https://user-images.githubusercontent.com/40150500/60269087-77280900-98f6-11e9-98c1-105795e12805.png)

Fig_2-option_logic

![Fig_2-option_logic](https://user-images.githubusercontent.com/40150500/60269109-7e4f1700-98f6-11e9-8797-358d5b013e9f.png)

Fig_3-query

![Fig_3-query](https://user-images.githubusercontent.com/40150500/60269123-84dd8e80-98f6-11e9-8bd2-e3c9c9acc581.png)

**Comment by dprokop** [comment]
@lessenko let me summarise to make sure we are on the same page here. You would like additional marks on the graph panel, that would highlight the data, that actually triggered the alert?

We already have an annotation feature that allows you to do that manually, please see docs for reference: https://grafana.com/docs/reference/annotations/

Closing this for now. If you feel like annotations is not something that is useful for you and you would like to reopen this feature request, just let us know!

**Comment by lessenko** [comment]
No, it is option to do the marks with Grafana (not manually). 
Torkelo commented yesterday:
"Can you open a feature request for that option so we can gauge how many users are interested in that option? "

**Comment by torkelo** [comment]
just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by lessenko** [comment]
Thank you. Sorry for the trouble. 
Best regards.
