### ISSUE TITLE
Bug in filter in table visualisation prometheus

### ISSUE THREAD

**Issue by AlexDexsoon** [grafana/grafana#17805]
**What happened**:
When i use filter in table visualisation, i have error Prometheus query.
Example query:

```topk(10,sum(sum_over_time(success_cheques_last_1_min{ exported_job=\~"$env", group_code=\~"$group_code" }[10m]))by(group_code))```

**What you expected to happen**:
In table must view only one string, without error.

**How to reproduce it (as minimally and precisely as possible)**:
Example query:

```topk(10,sum(sum_over_time(success_cheques_last_1_min{ exported_job=\~"$env", group_code=\~"$group_code" }[10m]))by(group_code))```

In inspector:

```
url:"api/datasources/proxy/16/api/v1/query?query=topk(10%2Csum(sum_over_time(success_cheques_last_1_min%7Bexported_job%3D~%22prod%22%2Cgroup_code%3D~%22magicshopv4-atol-ru_5501%22%2Cgroup_code%3D%22magicshopv4-atol-ru_5501%22%7D%5B10m%5D))by(**group_code%7Bgroup_code%3D%22magicshopv4-atol-ru_5501%22%7D**))&time=1561663751"
```
In section "by(group_code)" add filter string
 
**Anything else we need to know?**:
If add space in left and right "by", it works:

```
"topk(10,sum(sum_over_time(success_cheques_last_1_min{ exported_job=\~"$env", group_code=\~"$group_code" }[10m])) by (group_code))"
```

In inspector:

```
api/datasources/proxy/16/api/v1/query?query=topk(10%2Csum(sum_over_time(success_cheques_last_1_min%7Bexported_job%3D~%22prod%22%2Cgroup_code%3D~%22magicshopv4-atol-ru_5501%22%2Cgroup_code%3D%22magicshopv4-atol-ru_5501%22%7D%5B10m%5D))%20by%20(**group_code**))&time=1561663786
```
**Environment**:
- Grafana version: v6.2.2 (07540df)
- Data source type & version: Prometheus 2.10.0 
- OS Grafana is installed on: Centos 7
- User OS & Browser: ElementaryOS(Ubuntu), Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Not sure what you mean by this issue? Sounds like you had a syntax issue with prometheus? When you corrected the syntax (space) it works, and when you had wrong syntax Prometheus returned an error? Can you explain why this is a Grafana bug?

**Comment by AlexDexsoon** [comment]
Hello, in Prometheus query there is no requirement to use spaces in construction with "by".
If I use queries without spaces then the filter in the tables does not work.

**Comment by torkelo** [comment]
> If I use queries without spaces then the filter in the tables does not work. 

what filter? 

Can you show the error you get? (does Prometheus return an error? what is it what) 

Closing this as I looks like a Prometheus syntax issue
