### ISSUE TITLE
Dashboard List Panel: Show expand / collapsable folder structure 

### ISSUE THREAD

**Issue by danielarkins** [grafana/grafana#17812]
**What would you like to be added**: the ability to add a panel that displays my grafana folder structure and allows users to drill down (similar to what is seen when i go to manage dashboards, i see my folders and can expand them to browse to the dashboards.

**Why is this needed**: home dashboard with starred and recent dashboards provides no ability to organize dashboards into folders by group

**Comment by torkelo** [comment]
related https://github.com/grafana/grafana/issues/13995

**Comment by amadeuszkryze** [comment]
Is there any progress in this topic? I really see lack of this feature in my project where I have multiple areas of monitoring and every area has its overall and it looks like that:
![image](https://user-images.githubusercontent.com/37712172/66648182-2cbf6380-ec2b-11e9-9dec-62239cd59554.png)
Can we add some soft of shadowed folder structure before dashboard names like (even as configurable dashboard option): 
```
<shadowed>AWS /</shadowed> Overall
<shadowed>DJANGO /</shadowed> Overall
...
```
to have it like this:
![image](https://user-images.githubusercontent.com/37712172/66648558-18c83180-ec2c-11e9-9cba-a18f3e017a23.png)

Simple `<span style="opacity: 0.6">FOLDERNAME /</span>` would be enough :)

**Comment by amadeuszkryze** [comment]
@torkelo can You check?

**Comment by torkelo** [comment]
check what? is there a PR?

**Comment by amadeuszkryze** [comment]
Unfortunately no, I have not enough knowledge about go and grafana implementation to implement this feature but myself , but I was wondering if this could be transformed to task or add this to roadmap for some future release.

**Comment by naturalbeau** [comment]
This feature will be very useful. Hope it can be implemented soon.

**Comment by amy-super** [comment]
Hello Grafana community! I'm investigating design improvements to folder management and navigation in Grafana and I would love your help. [Schedule 30 minutes with me](https://ethn.io/38442) to share your feedback and see some early design ideas.
