### ISSUE TITLE
Build: fix System.js webpack issue

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17810]
Since #17655, the build says:

![image](https://user-images.githubusercontent.com/705951/60307053-bf93f680-98f7-11e9-92b8-14c7aaf1ef58.png)
```
[Webpack] WARNING in ./node_modules/systemjs/dist/system.src.js 3870:22-33
[Webpack] Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
[Webpack]  @ ./packages/grafana-runtime/src/utils/plugin.ts
[Webpack]  @ ./packages/grafana-runtime/src/index.ts
[Webpack]  @ ./public/app/core/config.ts
[Webpack]  @ ./public/app/app.ts
[Webpack]  @ ./public/app/index.ts
```

**Comment by ryantxu** [comment]
@dprokop -- any ideas, I have tried a few things without luck

**Comment by dprokop** [comment]
Ryan, I think we can assume in `grafana/runtime` that system.js is global (that's from typescript view) and externalise it in rollup. Have you tried that?

**Comment by ryantxu** [comment]
the issue is with webpack, not rollup.

In rollup it should be external for sure

**Comment by dprokop** [comment]
Yah, sorry, I meant webpack of course. Early morning. 

So for internal build I can't see any solution that would allow importing systemjs and not having this issue. I think we can take a similar approach we took with services by exposing seter and getter for systemjs instance, that would be created on app bootstrap.

Then all references to systemjs would go through `getSystemJS()`, and it feels like it's actually runtime where the systemjs service should belong. WDYT?

**Comment by torkelo** [comment]
Is this fixed?

**Comment by torkelo** [comment]
Is this fixed? not seeing this anymore
