### ISSUE TITLE
@grafana/toolkit - implement common tooling for plugin developers

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#17819]
The work started in: https://github.com/grafana/grafana/pull/17445

TODO: 
- [x] Enable building app/plugin using shared rollup config
- [x] If there is more than one module.ts entry then add manual chunks
- [x] Enable running tests on app/plugin
- [x] Introduce common tsconfig
- [x] Introduce common tslint config
- [x] Do not expose internal cli commands 
- [x] Validate plugin name/org
       - OK for plugins in grafana repo to skip the org 
- [x] Run typecheck before linting 
- [x] Add watch option to enable easy development (rollup watch, plugin:[dev|watch])

### Plugin development tasks
- [x] `grafana-toolkit plugin:test` - performs tests for a given plugin
- [x] `grafana-toolkit plugin:dev` - runs plugin in development mode, meaning that Rollup is run in `watch` mode
- [x] `grafana-toolkit plugin:build` - prepares plugin distribution package
  - [x] Runs linter
  - [x] Runs tests
  - [x] Bundles plugin
- [x] `grafana-toolkit plugin:create` - creates plugin seed from a template (https://github.com/grafana/grafana/issues/18506)

### Testing plugin
- [x] Make sure toolkit allows working with enzyme/react-testing-library
- [x] Enable custom Jest config (via package.json file as a start)
- [x] Enable running test task in watch mode (https://github.com/grafana/grafana/pull/18137)
- [x] run a single test from command line (@briangann) (https://github.com/grafana/grafana/pull/18137)

### Linting / Prettier
- [x] Enable linting plugin via `tslint`
  - [x] Enable lint fix in `plugin:dev` (https://github.com/grafana/grafana/pull/18131)
- [x] Enable custom tslint config
- [x] Prettier (https://github.com/grafana/grafana/pull/17964)
  - [x] Enable Prettier check in 'plugin:build'
  - [x] Enable Prettier write in 'plugin:dev' (https://github.com/grafana/grafana/pull/18131)

### Bundling plugin
- [x] Verifies if plugin follows common practices 
  - [x] Check if plugin.json naming follows naming convention (#17975)
- [x] Bundles plugin using Webpack
- [x] CSS generation
- [x] Show webpack stats after build is finished (both `plugin:dev` and  `plugin:build`) (https://github.com/grafana/grafana/pull/18138)

~~### Documentation~~
- ~~generate docs from `/docs` folder~~
 a different task should do this

### CircleCI helpers
package a plugin in circleci.  this will be super helpful for backend plugins.

See: #17967

### Plugin stylesheet (#17938)
- [x] Add support for common conventions:
  - [x] Single css/scss file (used via import)
  - [x] Separate files for themes (used via loadPluginCss)
  - [x] Emotion
- [x] Enable PostCSS
- [x] Verify SASS setup

With new react panels, we should push for emotion.  However we still need to support old/existing panels that tend to either just [import a .css file](https://github.com/grafana/clock-panel/blob/master/src/clock_ctrl.ts#L5), or use: [loadPluginCss](https://github.com/grafana/kubernetes-app/blob/master/src/module.ts#L10)
```
loadPluginCss({
  dark: 'plugins/grafana-kubernetes-app/css/dark.css',
  light: 'plugins/grafana-kubernetes-app/css/light.css'
});
```

## v2 backlog:
- [ ] Make Enzyme a default test tool in toolkit
- [x] `plugin:ci` - gather stats from webpack task

## Current (known) problems to be figured out
1. **How to handle imports from core?** `import XXX from 'app/plugins/sdk'`
This problem surfaced in k8s and ajax panel. Can't see any clear path how to fight this one. Problem is that those plugins import implementations from core (indirectyl, via pligins/sdk). It's not about interfaces anymore but about actual implementations being extended by apps/plugins. Thing is that we possibly could extract app/plugins/sdk to a separate package, i.e. `@grafana/plugin-sdk`, but it's super hard because of app/plugins/sdk referencing core modules.... Crap 

Toolkit wishlist:
* prettier fix (in dev)
* test <single test file> ask @brian.gann
* external/lib support.  Include, but don't compile:
  https://github.com/grafana/grafana-polystat-panel/blob/use-toolkit/src/d3wrapper.ts#L1
* enzyme out-of-the-box

**Comment by dprokop** [comment]
@ryantxu could you please update `Check if plugin.json naming follows naming convention` above? I remember you had an idea about plugin naming convention in regards to org name and plugin name

**Comment by ryantxu** [comment]
rollup vs webpack?  so I originally though rollup was a good path because it makes nicer bundles... but having tried this with a bunch of plugins, I think it is going to be more difficult that in is worth :(

rollup seems to be much stricter about how it imports and packages libraries.  This is likely more "correct", but I am struggling to find something that works.

I think we should consider webpack.  @dprokop, could you take a stab a matching this [webpack.config.js](https://github.com/ryantxu/ajax-panel/blob/master/webpack.config.js) -- If you get close, I can poke on the details till it works with a few of the plugins

**Comment by dprokop** [comment]
@ryantxu sure, as we talked on friday, we gonna try with webpack here.

**Comment by dprokop** [comment]
@ryantxu webpack related work: https://github.com/grafana/grafana/pull/17850

**Comment by ryantxu** [comment]
Current Status:

✅ https://github.com/ryantxu/ajax-panel
❌ https://github.com/ryantxu/grafana-graphql-datasource:  fails with `@grafana/data`
✅ https://github.com/NatelEnergy/grafana-discrete-panel
✅ https://github.com/grafana/kentik-app
✅ https://github.com/grafana/kubernetes-app
❌ https://github.com/grafana/simple-json-datasource/pull/129 fails with:

![image](https://user-images.githubusercontent.com/705951/60749708-9bb55e00-9f52-11e9-9c86-2f58561a62de.png)


I think the next priorities should be:

1. prettier --fix? 
   * `yarn dev` -- auto fix prettier and lint errors
   * `yarn build` -- failes if prettier or lint fails

   Alternativly we could add an explicit call with `--fix`, but I think fewer options is better


2. `@grafana/data` build/publish?

**Comment by dprokop** [comment]
@ryantxu me need to publish @grafana/data in order to make those ^^ problems disappear(grapgql ds and simple-json ds).

**Comment by dprokop** [comment]
@ryantxu the grafana-graphql-datasource plugin should build correctly with https://github.com/grafana/grafana/pull/18005 applied and @grafana/data added as dependency

**Comment by briangann** [comment]
Currently the toolkit doesn't watch .html files, which are common in plugins for the query editors/datasource configuration.

It would be great to have 'yarn dev --watch' detect changes to these files and drop them into dist, just like the rest of the process.

The "hack" i've used so far is to add htmlwebpackplugin, though it leaves an artifact 'index.html' that never gets used, but does detect and copy the partials/* correctly.

**Comment by torkelo** [comment]
Anything left for this issue? Maybe close this and create an issue for remaining issues

**Comment by dprokop** [comment]
@torkelo yup, closing this one. Other toolkit tasks are tracked in separate issues.
