### ISSUE TITLE
Alerting annotation of NoData=null is unclear

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#17817]
I can assume this means the query returned no data, but it's really unclear.

![nodata-null](https://user-images.githubusercontent.com/20774/60332326-4059fd80-999f-11e9-8f10-fa2dbcd470f9.png)

**Comment by flopp999** [comment]
That your query didn't get any data.

**Comment by Dieterbe** [comment]
@marefr can this be clarified? using words that humans can understand? :) or is this for @bergquist 's list...

**Comment by armandgrillet** [comment]
Closing as legacy alerting only which is deprecated.
