### ISSUE TITLE
Trailing / in alertmanager url breaks notifications

### ISSUE THREAD

**Issue by ernst-123** [grafana/grafana#17816]
**What happened**: 
We used alert notifications that were sent to prometheus-alertmanager but alert manager did not receive them, and no errors were logged.

**What you expected to happen**:
Alertmanager should have received the notifications and processed them or Grafana should have logged at least a warning/error to indicate that the requested operation was not performed.

**How to reproduce it (as minimally and precisely as possible)**:
Run alertmanager with --web.route-prefix=/alertmanager or with --web.external-url that includes a sub path. In Grafana set up an alert notification for Prometheus-Alertmanager and include a trailing /. Send a test, alertmanager will not receive anything.

**Anything else we need to know?**:
Grafana will send a request with a double / in the URL path, alertmanager (I use version 0.17.0) will respond with a 301 (Moved Permanently) and a Location where the double / is trimmed down to 1 /, however Grafana will ignore this.

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:
  Alertmanager version 0.17.0 (also checked with 0.16.2)

**Comment by marefr** [comment]
Investigate further to reproduce the bug

**Comment by marefr** [comment]
This seems to have been fixed in Grafana v7.1 via #24196 so I'll close this.

Fixed by #24196
