### ISSUE TITLE
Grafana not pulling latest data when using "current" stat instead of "instant"

### ISSUE THREAD

**Issue by aknobloch** [grafana/grafana#17829]
**What happened**:
We have a singlestat panel which utilizes spark lines to show a time series. When querying Prometheus and setting the query to "instant," we receive the latest data available on Prometheus. However, this removes our sparklines. When not setting the "instant" flag, but instead using "current" as the stat option, we do not receive the latest data available on Prometheus. We believe this is due to the way Grafana queries in this case, such as:

`"api/datasources/proxy/2/api/v1/query_range?query=my_query%7Bjob%3D%22My_Job%22%7D&start=1561125600&end=1561730400&step=7200"`

It seems like either the step parameter or the end parameter are not being set correctly, causing data loss for some time.

**What you expected to happen**:
Time series graphs set to "current" stats should receive the latest data available, and not be inconsistent with the data retrieved from "instant" queries.

**How to reproduce it (as minimally and precisely as possible)**:
Create a single stat panel on Grafana with spark lines, tied to a simple query available on Prometheus. Post a new update to Prometheus for that data point. When "instant" is set on the Grafana query, that data is available immediately. When "instant" is not set, we cannot retrieve that information.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.2.1 (9e40b07)
- Data source type & version: Prometheus 2.10.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac Mojave 10.14.4 (18E226) / Chrome Version 75.0.3770.100
- Grafana plugins: Pie Chart
- Others:

**Comment by torkelo** [comment]
For latest data you need to use the instant. 

For time time range queries Prometheus can be very sensitive to what the start/end values are, and how they relate to step & rate queries. 

For the full discussion on start/stop step alignment:
https://github.com/grafana/grafana/issues/15385
