### ISSUE TITLE
Missing prometheus data points in Grafana

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#17823]
**What happened**:

I am using a **single** prometheus instance as data source for Grafana. I queried a couple Graphs over a timerange of 3 hours. Some of these graphs are incomplete (they only show datapoints from the recent 1h or so), even though the data for the full time range is existent. On each dashboard refresh, there's a chance that this happens. For instance one graph frequently changes between these two states on dashboard reloads:

<img width="1649" alt="Screenshot 2019-06-28 at 14 30 38" src="https://user-images.githubusercontent.com/23424570/60345176-aef78500-99b8-11e9-904e-7d19978331ae.png">
<img width="1643" alt="Screenshot 2019-06-28 at 14 28 43" src="https://user-images.githubusercontent.com/23424570/60345192-b9b21a00-99b8-11e9-9772-88fff4a06d75.png">

**What you expected to happen**:

The query inspector shows that there are missing datapoints in the returned array. On the complete graph I get roughly 300 data points on the incomplete one I only get about 60 items in that array. In the prometheus UI however the complete graph always loads and has no gaps at all (I sent tons of requests for the same promql query):

<img width="1602" alt="Screenshot 2019-06-28 at 15 26 37" src="https://user-images.githubusercontent.com/23424570/60345376-2f1dea80-99b9-11e9-9a35-9374099dd96a.png">

**How to reproduce it (as minimally and precisely as possible)**:

I am not sure, I just setup a new prometheus instance, pushed data to it and used that as data source in Grafana.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: Prometheus v2.10.0
- OS Grafana is installed on: Docker / Kubernetes
- User OS & Browser: Mac OS & Google Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
If the query inspector shows missing data in some requests, that is very strange, is there anything else that change in the query? for example start / end? 

if the request is the same but the result is randomly missing a range, think it might be a bug in Prometheus. Can you investigate more how this query differes from the query you execute in the native UI?

**Comment by weeco** [comment]
It is a very simple PromQL query, which I used 1:1 in the prometheus UI:

```
prometheus_remote_storage_pending_samples{kubernetes_namespace="monitoring"}
```

I can confirm that the request in the query inspector is the same. As far as I know Grafana acts as proxy between prometheus and the Grafana UI, hence I suspected Grafana as well. Again: The prometheus UI shows the Graph perfectly fine, which is why I believe Prometheus members will ask me again to submit an issue in this repository.

Is there a way to figure out which component (Prometheus or Grafana) is causing the missing datapoints?

**Comment by torkelo** [comment]
is the step param your using in the both UIs the same? and time range? 

The proxy does not read or modify the response, simple reverse proxy, and we have no similar reports like this.

**Comment by weeco** [comment]
Yes time range and step/resolution is the same in Prometheus / Grafana. I'll submit a Prometheus issue and add a reference to this issue there. Thank you for the quick responses

**Comment by vc12345679** [comment]
Met the same issue. No operations other than auto/manual refresh, the panel could randomly show the expected curve or 'No data point'.
Grafana v6.2.4, MySQL v5.5.53

**Comment by marefr** [comment]
Is still a problem? Using Grafana 6.3.2? Lastest prometheus etc?

**Comment by torkelo** [comment]
closing this as we have no other similar reports and grafana does not modify the prometheus response body so it seems unlikely
