### ISSUE TITLE
Graph: Staircase mode, do now draw line segment from zero when drawing null values as null

### ISSUE THREAD

**Issue by bschick** [grafana/grafana#17838]
**What would you like to be added**:

When I select "null" as the setting for "Null value" it doesn't work as expected. When a series with data stops getting values, the line drawing does stop as expected. But when values resume, the line is drawn from the origin as if the first value was zero. There should be a way to simply not draw null values without extra artifacts. 

**Why is this needed**:

Currently it looks like the series is resuming at zero since it is drawn that way regardless of the actual first value. The "null as zero" setting works as expected in that it draws a line to, along, and from zero. "Connected" also works as expected by just continuing the last value. I had hoped that "null" would only draw points that had values, but it doesn't work that way and instead adds an extra segment to a value the never existed.

**Why is this needed**:

Using Grafana 6.2.4 atop Prometheus 2.10.0. Time series are gauges
<img width="937" alt="grafana_example" src="https://user-images.githubusercontent.com/238462/60400479-06b4fe00-9b29-11e9-8ff1-55f4b89dd702.png">

**Comment by torkelo** [comment]
Can you show the data returned by Prometheus? (Use query inspector in panel edit mode)

**Comment by bschick** [comment]
Attached text file with json. Note that there are no zeros values, but a jump in the time between the points:
2019-06-25 19:04:00 11872.28
2019-06-25 22:00:00 12438.27
[pp.txt](https://github.com/grafana/grafana/files/3348676/pp.txt)

**Comment by torkelo** [comment]
Can you disable step option? Think it’s caused by that option being enabled

**Comment by bschick** [comment]
Yup, if I disable "staircase" option then it behaves as expected. I'll do this for now, but would prefer to have step enabled and not have the extra segment.

**Comment by StephanThonig** [comment]
Regarding the supposed fix in the new Time series panel, it appears as it still doesnt draw the stair-case interpolation correctly.
See as follows (its a mockup from the playground with the CSV Metric Values [20,90,30,null,5,0,10]):

**How the Step-After interpolation is drawn currently:**

![StepAfter_Default](https://user-images.githubusercontent.com/68914026/109674557-4d1cf480-7b77-11eb-9424-0d570f3a6727.png)

**How the Step-After interpolation should look like:**

![StepAfter_Fixed](https://user-images.githubusercontent.com/68914026/109674561-4d1cf480-7b77-11eb-8a40-940b6072bb8c.png)

**How the Step-Before interpolation is drawn currently:**

![StepBefore_Default](https://user-images.githubusercontent.com/68914026/109674564-4db58b00-7b77-11eb-89a2-11571fd20588.png)

**How the Step-Before interpolation should look like:**

![StepBefore_fixed](https://user-images.githubusercontent.com/68914026/109674566-4db58b00-7b77-11eb-87b4-897d45bd9fe1.png)

**Comment by leeoniya** [comment]
> it appears as it still doesnt draw the stair-case interpolation correctly.

this is a tough one. i'm not sure there's existing consensus on how to "correctly" draw interpolations across explicitly-defined gaps. i certainly see your version as _one_, of several options that make sense. currently, the behavior across all interpolations is uniform: everything on _both_ sides `null` is clipped out (the fact that the ascenders and descenders are not erased in the stepped interpolation is a bit of a nuance in the way the entire path shape must be drawn). likewise, in linear and smooth modes you won't get a line interpolated up until the `null` value...the entire segment gets erased to both sides of the `null`.

we'll give this some more internal discussion...

**Comment by StephanThonig** [comment]
Thank you very much for your quick replay and insight!
I do get your point regarding the consistency with the other interpolation types.
Although i still personally think the above examples are representing the idea of step-after/before more accurate.
In my mind a Time-Value-Pair always consists of 1 horizontal and 1 vertical line + a dot (if it should be drawn).
And for null values exactly these 2(3) elements are just erased.
Anyways thanks again for taking a look into this and i hope that at least the unconnected vertical lines will disappear in the future, because then i can fake the rendering by just adding one more value right before/after the null. :P

**Comment by leeoniya** [comment]
> Anyways thanks again for taking a look into this and i hope that at least the unconnected vertical lines will disappear in the future, because then i can fake the rendering by just adding one more value right before/after the null. :P

this is probably the right balance. i've changed the default stepped pathBuilder in uPlot to clip out any ascenders/descenders adjacent to null runs: https://leeoniya.github.io/uPlot/demos/line-paths.html.

this will get merged into Grafana at some point before 8.0.
