### ISSUE TITLE
Enhanced toggle button(radio button)

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#17830]
The reason for changing the toggle button is that we have multiple variants and to make it consistent with new forms design. Should also be used more in forms replacing drop-downs with few items.  

Currently we have three version that are should be replaced with one: 
<img width="299" alt="Screenshot 2019-06-28 at 15 13 08" src="https://user-images.githubusercontent.com/23470681/60348335-a5255000-99bf-11e9-9009-1221d131c7fa.png">
<img width="781" alt="Screenshot 2019-06-28 at 15 12 57" src="https://user-images.githubusercontent.com/23470681/60348353-ace4f480-99bf-11e9-9880-23e8b93e1d53.png">
<img width="321" alt="Screenshot 2019-04-25 at 15 33 33" src="https://user-images.githubusercontent.com/23470681/60348469-e3bb0a80-99bf-11e9-9290-7dbbd831f0eb.png">

- Only one item can be chosen. 
- Only first and last item should have border radius(2px). First item on left side and last item on right side.  
- Keyboard control: Tab to toggle button and use arrow keys and enter to choose like the dropdown menu.
- Can have label if used in forms

<img width="1440" alt="Screenshot 2019-09-03 at 14 41 21" src="https://user-images.githubusercontent.com/23470681/64174136-f424b100-ce58-11e9-98df-d745c6850e39.png">

Either creating new component from scratch or use one of the old ones to build upon is fine.

**Comment by torkelo** [comment]
This is the component that I think can be used as a base (and refactored/restyled)

https://github.com/grafana/grafana/blob/master/public/app/core/components/ToggleButtonGroup/ToggleButtonGroup.tsx

Look at the new Button components in @grafana/ui for rerference on how to work with emotion (style in code)

**Comment by dehrax** [comment]
How would we want to initialize the keyboard control? When one button has been clicked, and we consider the button group to be in focus?

**Comment by torkelo** [comment]
tab should shift focus, enter press?

**Comment by dehrax** [comment]
So basically native browser behavior?

**Comment by torkelo** [comment]
yes

**Comment by dehrax** [comment]
What's the reasoning behind only one item being chosen? I can definitely see value in being able to chose multiple. For the use cases where you only want one chosen, you'll have to implement that logic via `onChange` or some other way. Is that a reasonable thought? Another option could be to have a prop on `ToggleButtonGroup` called `selectSingle` or something.

**Comment by dprokop** [comment]
@dehrax I think that long term the buttons you implement should support both single and multiple select. 

---
I think we take a slightly wrong approach calling the component a ToggleButtons. `ToggleButton` should be a specific button component that enables, well, toggling. Meaning it has `pressed` or sth similar state.

---

In the end, what we are implementing here is a group of a specific type of a button, so i suggest changing the naming a little bit:
- `ToggleButtonsGroup` - enabling group of `ToggleButton` components that are visually connected, multiple selection allowed
- `RadioButtonsGroup` - same as above, but allowing only single `ToggleButton` being pressed at given point of time. 

At some point we will also need a simple component called `ButtonsGroup` that would be a group of regular buttons rendered as a group.
