### ISSUE TITLE
Support API to pull data for forecasting and other detection needs 

### ISSUE THREAD

**Issue by lihan** [grafana/grafana#17834]
**What would you like to be added**: Would like to have APIs to pull data points from all Grafana supported data sources.

**Why is this needed**: Would like to have means to pull data into another service to generate some data intelligence (forecasting) and display back onto Grafana. (This can be added into another data source and display it along side with the original diagram)

I can add support to all the data sources (Prometheus, SQL), however, it would require the support to all data sources so a much better way to do it is to use Grafana to pull data from already supported data source via API.

**Comment by lihan** [comment]
@torkelo A feature like this will be extra awesome https://github.com/apache/incubator-superset/pull/6555 Is there a way to implement this either with plugin or app?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
