### ISSUE TITLE
Explore: Show the details of a log message

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17831]
**What would you like to be added**:
Possibility to show the details of a log message in Explore.

**Why is this needed**:
Currently there are only a timestamp, log message and log level shown for each log row. However, some datasources may have more detailed meta data like additional fields and labels that would be nice to be able to show in a detailed view of log message. Further, the detailed view may also  allow to ease filtering of log messages since all information about a log message is shown.

**Comment by Ijin08** [comment]
We place an arrow icon that will function as a toggle to open log message details.
<img width="1440" alt="Screenshot 2019-09-13 at 13 15 05" src="https://user-images.githubusercontent.com/23470681/64859044-75cec880-d629-11e9-9c4e-d82b14923ad3.png">
The log details will be shown as a table where one can check their distribution in all the log rows and in case of labels/fields/tags also filter on them.
<img width="1440" alt="Screenshot 2019-09-13 at 13 15 16" src="https://user-images.githubusercontent.com/23470681/64859045-75cec880-d629-11e9-92fe-cc406e794b96.png">
The distribution will be shown the same way as is now.
<img width="1440" alt="Screenshot 2019-09-13 at 13 15 25" src="https://user-images.githubusercontent.com/23470681/64859046-75cec880-d629-11e9-8b3b-7950ec325880.png">

[Explore Log message details in figma](https://www.figma.com/file/iQYVTrFSPOtUCPVvxVojUM/Log-message-details?node-id=146%3A460)

**Comment by ivanahuckova** [comment]
Closed with #20034
