### ISSUE TITLE
Query Data fail, if Grafana is located behind a reverse proxy

### ISSUE THREAD

**Issue by MarcelT0815** [grafana/grafana#1784]
Hi there, 

we try Grafana 2 Beta3 behind an apache reverse proxy 

configured with: 
ProxyPass /grafana/ http://localhost:3000/

in grafana.ini:
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

now we can create some dashboards and charts. We also get the suggestions for series from our tsdb. But if selected, the query for the timeseries fails. While debugging i see Grafana is posting the query to /grafana/grafana/api/datasources/proxy/1/api/query

wich results in a 404. If i remove one of the /grafana manually, it works. Always the same for OpenTSDB and Influx08.

Is this a bug or misconfiguration?

Thanks 
Marcel

**Comment by torkelo** [comment]
Fixed, pushing out a prebuild of rc1, should appear here shortly : http://grafana.org/download/builds.html
