### ISSUE TITLE
Feature Request: Ignore invalid https certificates

### ISSUE THREAD

**Issue by syepes** [grafana/grafana#1785]
Hello,
I am migrating over to Grafana 2.0 and my Graphite is running with a self signed cert.
Now I want to use the proxy functionality of Grafana but I am getting the folloing error:

    http: proxy error: x509: certificate is valid for xxx.yyy.com, not localhost

Would it be possible to add an option so Grafana ignores invalid certs?

**Comment by torkelo** [comment]
yes, would be possible :)  (PR?)

**Comment by syepes** [comment]
I have looked around and it looks like the option "InsecureSkipVerify" should resolve the issue. Unfortunately I am not a Go Guru ;-(

**Comment by syepes** [comment]
This is my temporarily hack:

```
diff --git a/pkg/api/dataproxy.go b/pkg/api/dataproxy.go
index 81318cd..8bea8c9 100644
--- a/pkg/api/dataproxy.go
+++ b/pkg/api/dataproxy.go
@@ -3,6 +3,7 @@ package api
 import (
        "net/http"
        "net/http/httputil"
+       "crypto/tls"
        "net/url"
 
        "github.com/grafana/grafana/pkg/bus"
@@ -56,5 +57,6 @@ func ProxyDataSourceRequest(c *middleware.Context) {
 
        proxyPath := c.Params("*")
        proxy := NewReverseProxy(&query.Result, proxyPath)
+       proxy.Transport = &http.Transport{ TLSClientConfig: &tls.Config{InsecureSkipVerify: true} }
        proxy.ServeHTTP(c.RW(), c.Req.Request)
 }```

**Comment by williamjoy** [comment]
Maybe config `direct` connect in datasource to graphite? :)

**Comment by syepes** [comment]
@williamjoy I am doing this because I don't want Graphite to be accessible other then through Grafana.

**Comment by williamjoy** [comment]
@syepes ah, make sense. Let grafana be the interface to users.
