### ISSUE TITLE
Bar Chart Tooltip Count Changes by Switching Stack Option

### ISSUE THREAD

**Issue by rshejnberg** [grafana/grafana#17853]
**What happened**:

While making a fairly basic bar chart where in I wanted to show counts over time grouped by another field called status so one series would appear for each status. 

Query used (for a mysql connection) looked like this:

```
SELECT unix_timestamp(created_at) as time_sec, my_table.status, count(my_table.id)
FROM my_table WHERE $__timeFilter(my_table.created_at)
GROUP BY 1,2
```

The resulting dataset looked like this:
![Screen Shot 2019-07-01 at 11 27 48 AM](https://user-images.githubusercontent.com/2775280/60452040-45af8600-9bf3-11e9-9f53-11bd04af180a.png)

The problem I encountered is that when values are null they are substituted with the closest relevant entry. For example on 6/14 the tooltip shows 1 "open" entry even though the entry its referring to actually happened on 6/18

![Screen Shot 2019-07-01 at 3 39 16 PM](https://user-images.githubusercontent.com/2775280/60465321-71903300-9c16-11e9-94b7-c4b4700890cc.png)

This problem can be solved by toggling the "Stack" option in the Visualization tab. However, this leads to some peculiar behavior...

![Screen Shot 2019-07-01 at 3 40 00 PM](https://user-images.githubusercontent.com/2775280/60465416-a43a2b80-9c16-11e9-88ad-cd21cda25922.png)
![Screen Shot 2019-07-01 at 3 40 16 PM](https://user-images.githubusercontent.com/2775280/60465426-ab613980-9c16-11e9-885c-53c02fc26c59.png)

Toggling the stack option on and the off again does not revert the counts to what they were initially. Refreshing the page will revert them but this can be very misleading.

**What you expected to happen**:

I would have expected turning the "Stack" option off to revert the counts shown in the tooltip to what they were prior to me turning it on

**How to reproduce it (as minimally and precisely as possible)**:

- Create a MySQL bar chart with a query similar to the one shown above or at least one where there are multiple series but one (or both) series has missing entries on some days where the other does 
- Verify that counts don't seem to line up in tooltip
- Toggle stack option on and off
- Verify that tooltip counts appear to line up now

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: MySQL 5.6
- OS Grafana is installed on: OSX10.15.6
- User OS & Browser: OSX10.15.6, Chrome
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment]
for non-continuous time series graphs like this, I would switch the tooltip from "All Series" to single mode. Or add a group by time to your query (that can fill in null for missing time buckets) to help Grafana understand that there is missing data between data points. 

Enabling and disabling stack should of course not have this affect so there is some kind of bug here . as well :)

**Comment by torkelo** [comment]
Is this still a problem in 7.0?
