### ISSUE TITLE
Ability to adjust time graph range to event selected in table panel

### ISSUE THREAD

**Issue by abezgam** [grafana/grafana#17859]
Hi, I am using Grafana 6.2.5 and have a dashboard with a few time graphs and a table panel with events. The events table has 2 columns, time and event name. My users need to analyze what was happening in the graphs around the time of the event. I am looking for a way to select a row in the events table and adjust the time window of the remaining graphs.  

Is there a any way to achieve this? I looked through the documentation but couldn't find a way to connect the tables to the graphs.

**Comment by torkelo** [comment]
Not right now, really cool feature though. 

similar to this, so closing this, https://github.com/grafana/grafana/issues/8310
