### ISSUE TITLE
Dashboards Always Save Time Range Even Without Box Checked

### ISSUE THREAD

**Issue by rshejnberg** [grafana/grafana#17855]
**What happened**:

Time range being saved on dashboards even when checkbox not marked

**What you expected to happen**:

The time range not to be updated when the checkbox is left unchecked

**How to reproduce it (as minimally and precisely as possible)**:

Create new dashboard with some range specified, 6 hr in this case
![Screen Shot 2019-07-01 at 11 52 37 AM](https://user-images.githubusercontent.com/2775280/60453482-e784a200-9bf6-11e9-880b-3177d82855c3.png)

Change time range to last year and save but do not check box for saving current time range
![Screen Shot 2019-07-01 at 11 52 53 AM](https://user-images.githubusercontent.com/2775280/60453520-f9fedb80-9bf6-11e9-86fc-f3d2fa2e1bef.png)

Verify that it was changed in JSON despite not checking box
![Screen Shot 2019-07-01 at 11 53 08 AM](https://user-images.githubusercontent.com/2775280/60453632-49dda280-9bf7-11e9-9b54-314296b83b9e.png)

**Environment**:
Grafana version: 6.1.6
Data source type & version: MySQL 5.6
OS Grafana is installed on: OSX10.15.6
User OS & Browser: OSX10.15.6, Chrome
Grafana plugins: None
Others: None

**Comment by torkelo** [comment]
This works as intended, 

The time range change will always modify the current json model, the checkbox is only for the save to DB action, not the current working definition.
