### ISSUE TITLE
Table panel: How to get a Column Name in table panel

### ISSUE THREAD

**Issue by arulmuruganas** [grafana/grafana#17857]
**What would you like to be added**:
How to get a Column Name in table panel?

**Why is this needed**:
This is required while creating URL for cell value :)

**Comment by torkelo** [comment]
> How to get a Column Name in table panel?

it's show in the table header? or your query? not sure what you mean. 

> This is required while creating URL for cell value :)

It is? how / where? think cell links that refer to columns only use column index (like $__cell_2 )
