### ISSUE TITLE
Frontend:  a 404 request to "/{{team.avatarUrl}}"

### ISSUE THREAD

**Issue by pandaren89** [grafana/grafana#17866]
When accessing "/profile", there's a request to `/{{team.avatarUrl}}`  which always ends in not found 404. This is causing the backend to log this request every time, therefore polluting the logs. 

**CAUSE**:
in `/public/app/features/profile/partials/profile.html`
The angular part of `/profile` page is trying to reference an avatar image, but the syntax to 
add source in an `<img>` tag is to use `ng-src` not `src`. 

**What happened**:
When accessing `/profile`, there is a 404 request to `%7B%7Bteam.avatarUrl%7D%7D` 

**What you expected to happen**:
The request should be accessing the actual `team.avatarUrl`'s value not the string `"{{team.avatarUrl}}"`

**How to reproduce it (as minimally and precisely as possible)**:
Browser go to `/profile`, check browser console, check backend log.
```console
INFO[07-02|15:36:24] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/{{team.avatarUrl}} status=404 remote_addr=[::1] time_ms=3 size=25538 referer=http://localhost:3000/profile
```

**Anything else we need to know?**:
this fixes the issue: 
```diff
diff --git a/public/app/features/profile/partials/profile.html b/public/app/features/profile/partials/profile.html
index 461946dcf..544d32adb 100644
--- a/public/app/features/profile/partials/profile.html
+++ b/public/app/features/profile/partials/profile.html
@@ -39,7 +39,7 @@
       </thead>
       <tbody>
         <tr ng-repeat="team in ctrl.teams">
-          <td class="width-4 text-center"><img class="filter-table__avatar" src={{team.avatarUrl}}></td>
+          <td class="width-4 text-center"><img class="filter-table__avatar" ng-src={{team.avatarUrl}}></td>
           <td>{{team.name}}</td>
           <td>{{team.email}}</td>
           <td>{{team.memberCount}}</td>

```
**Environment**:
- Grafana version: v6.3.0-pre (commit: 364f1f2e5)
- Data source type & version: None
- OS Grafana is installed on: Fedora 30
- User OS & Browser: Fedora 30 & Chromium
- Grafana plugins: None
- Others:

**Comment by marefr** [comment]
Thanks for reporting this. Should be fixed for 6.3 stable and hopefully soon in master.
