### ISSUE TITLE
Generic OAuth : Set Username to Custom Field in API Response

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#17868]
**What would you like to be added**: Set the username to a custom field returned by the api profile JSON.

**Why is this needed**: I need to store one of the returned values as the username (it is like a unique ID), but the username is set to be the same as the retrieved email.

Here is a (formatted and stripped) example of the response as it appears in the debug log:
`{
	"requiredField": "bdixon123",
	"name": "Dixon, Brandon ",
	"email": "Brandon_Dixon@site.com",
	"other_fields" .....
}`

What is marked as _requiredField_ is what I need to set the username to.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
