### ISSUE TITLE
Use randomly generated IDs for React list keys

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#17867]
So, currently there are quite a few places in the codebase where we use array indices or labels as list keys, which can cause a number of issues. In light of this I was wondering if perhaps we should make a push towards using randomly generated keys using [shortid](https://github.com/dylang/shortid), or [uuid](https://github.com/kelektiv/node-uuid), which, as I understand it, is considered a generally robust solution.

Some reading with regards to keys and indices:
- https://reactjs.org/docs/lists-and-keys.html#keys
- https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by marefr** [comment]
FYI I was the one switching to array indices from log message unique id for log messages. Basically loki timestamp + labels was used as unique identifier, but this wasn't always unique so created some issues/errors in console. @davkal had issues with getting array indices as keys working before so therefore he used the loki timestamp + labels as key solution.

I guess we re-render for example all log rows anyway in Explore so currently does it really make a difference?

For log rows I guess the ultimate solution would be if the datasource could provide unique id's. Elasticsearch can do that for example, but not Loki. So maybe if datasource not provide unique id, we can randomly generate it?

**Comment by kaydelaney** [comment]
Right, I think that makes the most sense. If the item that's being listed has some kind of unique id already attached then there shouldn't be any need to generate another one

**Comment by marefr** [comment]
@torkelo @dprokop @ryantxu @davkal any additional input here?

**Comment by aocenas** [comment]
Interestingly, right now for liveTail we use both timestamp and index https://github.com/grafana/grafana/blob/6402391638d2dedb3be24e38f5ebb1e389124621/public/app/features/explore/LiveLogs.tsx#L66

Honestly seems weird to me as on every change the IDs will change the same way if it was always random.

Is there a reason not to use the nanosecond precision string timestamp with the labels? I think I heard that should be unique.

**Comment by aocenas** [comment]
I think we can close this as this should not be an issue any more.
