### ISSUE TITLE
Align graph panels with legend in table mode

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1786]
Graph panels that use legend in table mode could often get panels that did not align: 

![image](https://cloud.githubusercontent.com/assets/10999/7158867/5157de62-e37e-11e4-8d6a-f9956a5bcedc.png)

This was due to the fact that when calculating the height of the graph canvas area only a single row legend is assumed. With this issue the legend height calculation will include the table header and ALL rows. So when using the legend in table mode the are reserved for the canvas graph will be reduced, so in order to restore the look you had for dashboards in v1.9 you need to increase the height for the Row. 

After change: 
![image](https://cloud.githubusercontent.com/assets/10999/7158907/ab7d161e-e37e-11e4-800a-48addf303220.png)

This change not only does it align panels, it also solves this issue: #1749

**Comment by maddenca** [comment]
I loaded 2.0.1 and horror, ugliness!  I use templates heavily and often have a varying amount of items to graph depending on the choice of some template item.  A simple example is a template item "top resources" which then shows the top X metrics in panels.  So the autosizing on overflow (old behavior) worked well; I would set the row height to the minimum I wanted it, put panels in a row that would all grow by the same count of graph items, and then if needed the rows would show with a greater height ensuring the graph was always visible.

Example of top 1:
![image](https://cloud.githubusercontent.com/assets/917241/7247145/70aeb880-e806-11e4-856d-0bc2b56c4013.png)

And then top 4, as in 2.0.1:
![image](https://cloud.githubusercontent.com/assets/917241/7247150/7e9cfee8-e806-11e4-9a23-81d8dcef3169.png)

Or previous to 2.0.1:
![image](https://cloud.githubusercontent.com/assets/917241/7247162/97a43fb4-e806-11e4-8681-d2ae30514c39.png)

Any ideas on how I can workaround when my # of items to graph varies?  Or a code change/feature that could accomodate when a user wants 'fixed' or 'minimum + autosize' heights?

Especially when using templates [that will result in variable metric counts] I think many users will hit issues with this change.

**Comment by torkelo** [comment]
You can change the row height so that you can see the graph even with a lot of series. I can understand that some edge cases this change can cause problems. Will listen to feedback and see if a work around or new option is required. 

Btw, on a other note, I see you are showing "max" and "avg" legend values at the same time for the same series. You know this can be misleading? That max and avg cannot be totally accurate at the same time? It depends on how your query looks and what aggregation is used to reduce the number of data points.

**Comment by lagndoy** [comment]
Is there a new issue to track this?  We have the same issue and our templating will result in 1 to 20+ records.  This makes having to change the row height to accommodate for it, very inefficient.  Workaround would be to not use a table in the legend but the table is just so much cleaner, it's used in about every graph/dashboard.  I wouldn't say that this is an edge case.

**Comment by torkelo** [comment]
@lagndoy there are already 3 issues that have reported that problem, and lucky for you it is already solved in https://github.com/grafana/grafana/issues/1832#issuecomment-94812687

Will release a patch release 2.0.2 later today to tomorrow, in the mean time there are nightly builds with the fix here: http://grafana.org/download/builds    (version is the 2.0.2-pre1)

**Comment by maddenca** [comment]
Tested using nightly build and my existing dashboards with metric count that varies and works for me.  Thanks!

**Comment by torkelo** [comment]
thats great
