### ISSUE TITLE
[Question] Username cookie needed

### ISSUE THREAD

**Issue by asefd** [grafana/grafana#17864]
Hi
I've upgraded to 6.2.5 version from 5.4.2
With the 5.4.2 I've been using the grafana cookies (grafana_user) that would allow me to run another application on the server and use this cookie to identify users.
I see that this has been removed now.
I've been searching how to add this to currently running version (6.2.5) but not able to find it.
Do you think that it is still possible?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

There's a new setting that will send the username as a HTTP header: https://grafana.com/docs/installation/configuration/#send-user-header
