### ISSUE TITLE
customize alert panel style

### ISSUE THREAD

**Issue by holiiveira** [grafana/grafana#17879]
**What would you like to be added**:

The possibility of customizing the alert panel style, for example, increasing the font size:

from:
![2](https://user-images.githubusercontent.com/4368491/60534427-2fc7c100-9cd8-11e9-9626-68aa76ef9694.PNG)

to:
![1](https://user-images.githubusercontent.com/4368491/60534429-2fc7c100-9cd8-11e9-9bae-df33bbe3545a.PNG)

**Why is this needed**:

We use Grafana to monitor all infrastructure and operational services, thank you for being possible, we have several panels that are monitored by operations staff, these panels are shown on several TVs, it would be great to be able to change the size of the source, to that the visualization was easier on the part of the operator.

Alternatively, I'm editing directly in the css file, for example:

`/usr/share/grafana/public/build/grafana.light.xxxx.css`

**Comment by torkelo** [comment]
Thanks for the feedback! 

We are not going to have a font size option for this I think. If you need to make things bigger for TVs the best way is to just use browser zoom. I know that might not be ideal or usable solution always. 

Will take this feedback into account if we ever redesign this panel / list. In the meantime, you could create a custom panel plugin that showed alert rules the way you prefer.
