### ISSUE TITLE
Add 'Send test alert notification' functionality within alert creation window

### ISSUE THREAD

**Issue by toinbis** [grafana/grafana#17873]
**What would you like to be added**:
In the panel's alert creation window, add 'send test alert notification' button.

**Why is this needed**:
It's common case that you need to test how alert settings are working, how pager duty is performing certain action after (if) receiving the alert, i.e. sending sms.
Currently you can only test the notification channel, but not specific alert. 
For instanst pingdom allows you to send test message to specific integration, and it works really well. Now instead I change the rule from 'below' to above, chamge '1..5min' to '1..2m', save and wait for few minutes. Very inconvenient...

Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
