### ISSUE TITLE
Grafana dashboard panel is showing Request Error

### ISSUE THREAD

**Issue by muhsinmp** [grafana/grafana#17889]
I am using Azure instance of Grafana, and i am trying to setup monitoring for Azure databricks using grafana dashboards. I have used the link : https://docs.microsoft.com/bs-latn-ba/azure/architecture/databricks-monitoring/dashboards to setup the grafana and its dashboard. But when i completed the setup, the panels in the Grafana dashboard is showing “Request Error” on top it. When i looked in to the query of the panel, its showing "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) as error.
![Grafana](https://user-images.githubusercontent.com/10824070/60570217-b939ca80-9d8e-11e9-8624-e73bb33f036d.jpg)

**Comment by torkelo** [comment]
What version of Grafana is this, and what browser version & OS are you using?

**Comment by muhsinmp** [comment]
Grafana v6.2.4 (ee01897) is the version i could see from the web UI, 
Linux (debian 9.9) is the OS version in the VM deployed in Azure
I am using Chrome browser Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by torkelo** [comment]
Looks like your query has syntax errors, but a bug in Grafana is making the error unreadable

**Comment by muhsinmp** [comment]
The query was generated using the steps mentioned in the microsoft link : https://docs.microsoft.com/bs-latn-ba/azure/architecture/databricks-monitoring/dashboards#create-the-dashboard
And support engineer from Microsoft said its Grafana issue not microsoft's, could you please help me here to understand what exactly we should do to fix this

**Comment by torkelo** [comment]
in the screenshot in the error in the browser console it has "The request has some invalid properties" can you expand that row?

**Comment by muhsinmp** [comment]
![grafana browser error](https://user-images.githubusercontent.com/10824070/60588785-7fc88580-9db5-11e9-94e7-c6289147a39e.JPG)

**Comment by torkelo** [comment]
as you can see it's a syntax error from Azure's service

**Comment by muhsinmp** [comment]
I have raised same with microsoft, and their support engineer said that the query generate step was from grafana and it should be supported by grafana, which one should i pick here

**Comment by torkelo** [comment]
But the query you entered is something you provide? And the error looks like a syntax error in the query you have written. But could be something that grafana does to the query before sending it

**Comment by muhsinmp** [comment]
The query was generated from the step provided here : https://docs.microsoft.com/bs-latn-ba/azure/architecture/databricks-monitoring/dashboards#create-the-dashboard
we have not generated any query for creating the dashboard.

**Comment by torkelo** [comment]
Maybe maybe a bug in their dashboard gen tool? 

The error is query semantic error: 
```
'extend' operator: Failed to resolve scalar expression named 'Properties_spark_metric_namespace_s'
```

I can see that your query contains that, and the query body (and formatting) is up to the user and it looks like a syntax error with this particular query. 

the script that generated this dashboard is probably generating/containing a query with syntax errors. 

Do any other panels work?

**Comment by muhsinmp** [comment]
Some panels are not showing error but showing nothing, most of the panels are having this error. What should be the resolution, who should be supporting this , can you help here to understand

**Comment by torkelo** [comment]
Can you make any query work? You should contact the person creating this dashboard/query and send them the complete query & the error `'extend' operator: Failed to resolve scalar expression named 'Properties_spark_metric_namespace_s'`

**Comment by muhsinmp** [comment]
As i said earlier, this dashboard query was created using the steps here : https://docs.microsoft.com/bs-latn-ba/azure/architecture/databricks-monitoring/dashboards#create-the-dashboard. And the Microsoft Support engineer said its supported by Grafana, i have no idea on the query which was created automatically by following the steps in above link

**Comment by torkelo** [comment]
I would open an issue in the repo where the dashboard is:  https://github.com/mspnp/spark-monitoring/blob/master/perftools/dashboards/grafana/SparkMonitoringDashTemplate.json

And describe the query semantic error that this dashboard generates: 

```
'extend' operator: Failed to resolve scalar expression named 'Properties_spark_metric_namespace_s'
```
