### ISSUE TITLE
singlestat: add HH:mm Date & Time format

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#17882]
**What would you like to be added**:
I'd like the ability to not have the YYYY-MM-DD part displayed in a singlestat, so a Date & Time unit of HH:mm:ss. Or perhaps a Time unit of HH:mm:ss (the duration unit isn't usable for this).

**Why is this needed**:
I have a few metrics that express a single point in time, like sunrise and sunset, per day. This is in seconds since epoch, but is always relative to today (the values update after a day change occurred for the specified long/lat we're calculating sunrise and sunset for). To that end I'd like to be able to display just the time, without the date.

**Comment by ryantxu** [comment]
In 6.6, you can put in whatever time you want... just type in the unit section:
`time:HH:mm`
