### ISSUE TITLE
app_tls_skip_verify_insecure is ignored at Grafana startup

### ISSUE THREAD

**Issue by sknigh** [grafana/grafana#17881]
**What happened**:

Grafana container exits with an error code when `GF_INSTALL_PLUGINS` is set

```
Failed to send request: Get https://grafana.com/api/plugins/repo/raintank-worldping-app: x509: certificate signed by unknown authority
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/raintank-worldping-app: x509: certificate signed by unknown authority
NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>
USAGE:
   Grafana cli plugins install [arguments...] 
``` 

**What you expected to happen**:

TLS should be ignored when `app_tls_skip_verify_insecure` is set in grafana.ini

```
[plugins]
app_tls_skip_verify_insecure = true
```

**How to reproduce it (as minimally and precisely as possible)**:

Reproducing this issue requires a proxy server with SSL interception. 

**Anything else we need to know?**:

I also tried setting `GF_APP_TLS_SKIP_VERIFY_INSECURE=true` with the same result. Ideally there would have a way to add a site certificate to the bundle, but I can't find a way to do that with the container as it's currently configured.

**Environment**:
- Grafana version: grafana/grafana:6.2.5 container
- OS Grafana is installed on: Kubernetes environment
- Grafana plugins: raintank-worldping-app

**Comment by torkelo** [comment]
that setting is for something else, it's for app proxy calls

**Comment by tp-jssk** [comment]
I am running into same issue in Grafana 9.x version. Anyone has fix for it?

**Comment by DanielCaminoss** [comment]
I have the same issue. Any fix?
