### ISSUE TITLE
[FeatureRequest] DashExport- Always remove repeated rows/panels in dashboard save model 

### ISSUE THREAD

**Issue by JohannesRudolph** [grafana/grafana#17887]
**What happened**:
I have a dashboard with template variables filled by a query. Say I have one repeated panel which is repeated 10 times (my variable query returns 10 values). 

When using Share -> Export -> Save to File the generated json file has 10 panel entries, one for each variable. Each panel entry has the template variables filled in, like so 

```json
      "repeatedByRow": true,
      "scopedVars": {
        "myvar": {
          "selected": false,
          "text": "x",
          "value": "x"
        },
```

This needlessly blows up the size of the export and makes diffs impossible when used together with grafana provisioning. 

When selecting Share -> Export -> Export for Sharing externally the panels are not repeated. The export is therefore much shorter, however I'm unsure whether I can dashboards templated this way with grafana provisioning?

**What you expected to happen**:

"Normal" exports should not include repeated panel "instances", it's sufficient if they include the panel definition.  

**How to reproduce it (as minimally and precisely as possible)**:

Use this gist: https://gist.github.com/JohannesRudolph/95ec2bf0d1a236931f386bc900e77381
It has a panel repeated over a variable with 4 static values. The export contains 4 panels, but should only contain 1 (the panel definition). 

My "production issue" is with variables made from queries, but it reproduces with static values too which were easier to make a repro sample of. 

**Anything else we need to know?**:

**Environment**:
- Grafana version:v6.1.6 (cf9cb45)

**Comment by JohannesRudolph** [comment]
My workaround for now is to export using "export for sharing" option, manually remove the `__inputs` and `__requires` keys from the template, then search and replacing the `${DS_PROMETHEUS}` variables with my datasource name. This dashboard then works with grafana auto-provisioning.

**Comment by torkelo** [comment]
Agree the repeated elements should probably always be removed, not sure if there is a good argument to keep them. Except for dashboard snapshots (that also use dashboard.getSaveModel)

**Comment by philomory** [comment]
The workaround noted above no longer works: even in "export for sharing externally" mode, I still get the repeated panel instances in my exported JSON, with all my variable values listed as `scopedVars` for each panel.
