### ISSUE TITLE
expose variables.dark|light.generated.scss to plugins

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17886]
Currently plugins that want to use .scss for theming, jump through some big hoops to use the variables.  See the kentik app:

1. Download grafana source in prebuild.sh
https://github.com/grafana/kentik-app/blob/master/build/prebuild.sh

2. Reference the scss:
https://github.com/grafana/kentik-app/blob/master/src/sass/kentik.dark.scss 

It would be nice to have these scss files in the @grafana/ui package

**Comment by ryantxu** [comment]
Looks like we are adding some docs on how to use some variables...  https://github.com/grafana/grafana/pull/17876/files#diff-e5edf937d349057d50a03e84514f6df9R21

but I'm not sure

**Comment by torkelo** [comment]
This is going to be very tricky, we will have to ship the theme with the toolkit or have toolkit depend on @grafana/ui and then add the template generation that generates sass files from template files (how we do it now with yarn start)

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/themes/dark.ts

The theme is available for new react plugins so the question is if it's worth spending time and complicating the plugin build to support this for legacy plugins . 

Another alternative that might be easier would be to copy generaterd variables.scss and the dark/light files into the toolkit during npm publish

**Comment by ryantxu** [comment]
>  copy generaterd variables.scss and the dark/light files into the toolkit during npm publish

I was thinking @grafana/ui, but @grafana/toolkit make make more sense as a "make this possible, but not the best way"

**Comment by dprokop** [comment]
@ryantxu @torkelo in long run we should strive to remove the scss files from the toolkit at all and make people use JS theme. For now the solution Ryan proposed in https://github.com/grafana/grafana/pull/17888 is ok.

Let's start with scss available via toolkit, and in later versions we gonna deprecate that and make people either switch to Emotion, or handle the variable files by themselves. WDYT?
