### ISSUE TITLE
Run End-to-End tests for release builds

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17897]
**What would you like to be added**:
Run End-to-End tests for release builds (tags).

**Why is this needed**:
We currently only run End-to-End tests for the master branch workflow, see [circleci config](https://github.com/grafana/grafana/blob/master/.circleci/config.yml#L689), and we want to run this for the [relases workflow](https://github.com/grafana/grafana/blob/master/.circleci/config.yml#L697) to get some automated verification of releases.

**Comment by xlson** [comment]
The end to end tests (in their current iteration) depends on the grafana docker image being available from docker hub (the one we are verifying). This makes it weird to stop a release if the end to end tests fail as we have already started deploying resources to run them. It's probably best to start off by doing something similar for the release builds: have the end to end tests just for verification. We can rearchitect them later to run before any resources have been deployed.
