### ISSUE TITLE
Docs feedback: tutorials/ha_setup.md

### ISSUE THREAD

**Issue by DeeGeeGit** [grafana/grafana#17892]
The diagram on this page shows the HA setup having a single load balancer in-front of the grafana instances, this is bad practice, there should be at least two load balancers in either active/active or active/passive configuration. 

Please update the diagram with a pair of load balancers up front and showing each of them connected to eachother and also both connected to the underlying grafana instances.

**Comment by torkelo** [comment]
not sure that is part of the scope of that article, how many load balancers is not the point article, but that having multiple grafana servers and what that means for Grafana and settings you need consider

**Comment by DeeGeeGit** [comment]
I disagree pretty strongly here, if that is the case then we shouldn't show any load balancer in front of the environment and leave it as an exercise up to the reader (which I also feel is a terrible idea btw).

I'm not saying we need to include load balancer configuration, but we should at least indicate a nod towards the best practices.

**Comment by torkelo** [comment]
Sure agree it would be better if it was plural in the image, feel two would just complicate the image from the overall point of the article (having multiple Grafana servers behind a load balancer). How you configure your load balancer(s) is out of scope. Maybe as footnote to the article? :) 

Closing this as trying to keep issue count down, but PR would be welcomed.
