### ISSUE TITLE
Changing the 'dashboard' variable on a scripted dashboard doesn't apply changes

### ISSUE THREAD

**Issue by denisb411** [grafana/grafana#17902]
Currently I have an iframe being rendered on an Angular application that has a contentWindow.postMessage button to send a message for Grafana, which will change the graph's configuration (like enabling/disabling visualization of bars, lines, points.. etc).

When the message comes into the script I modify the 'dashboard' variable, but it doesn't apply any changes to my visualization. I wanted something like when you are on the Grafana dashboard page, click on edit of the panel and starts tapping configs, which applies **instantly** to the graph visualization. **Is it possible to reach this behavior?**

The only other way I found for a solution is to re-render the iframe passing the configs into the url parameters, but it causes the iframe to reload (tooks about 3secs) and impacts negatively the user experience.

Currently on the scripted dashboard I am doing something very simple:

```
function changeGraphConfig(event) {
  console.log(dashboard.rows[0].panels[1]);
  dashboard.rows[0].panels[1].bars = !dashboard.rows[0].panels[1].bars
  console.log('message received');
  console.log(dashboard.rows[0].panels[1]);
}
window.addEventListener("message", changeGraphConfig, false);
```
The complete dashboard:
https://gist.github.com/denisb411/df83200eba7d06b41fb4f0ec8fe00171

**Comment by torkelo** [comment]
This type of backdoor state modifications are not supported

**Comment by torkelo** [comment]
We will have to add support for this via a supported API but there is no concrete plan/roadmap for that yet. Any ideas for how to support that are welcome

**Comment by Hardu2203** [comment]
Suggestion: Every time you change the state through the Iframe.  A postMessage() gets fired form Grafana with the new state.  So the client with the Iframe can just listen for the message and handle the state change.
