### ISSUE TITLE
Plugins page accessible by viewers/editors even though not included in side menu

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17906]
**What happened**:
Navigated to `http://localhost:3000/plugins` and got access to the page, but the header says Page not found, 404 error and I can still browse all of the plugins: 

![image](https://user-images.githubusercontent.com/1668778/60608723-6aa52400-9dc0-11e9-9f07-7df4e51c4d24.png)

**What you expected to happen**:
To not be able to access the page since this page is not included in the side menu.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login as user with viewer or editor org role
2. Navigate to `http://localhost:3000/plugins`

**Anything else we need to know?**:
Tricky part is that we per default have a home dashboard that shows the list of plugins and all authenticated users can access every plugin:
![image](https://user-images.githubusercontent.com/1668778/60609093-28c8ad80-9dc1-11e9-90ec-b7d0689aacec.png)

You can also add the plugin list panel to any dashboard.

There shouldn't be any problem with any authenticated can access a plugin except for app plugins since they usually have a config and dashboards tab. If the app haven't properly implemented decryption of sensitive settings the users will be able to see these. 

One idea would be to hide the config/dashboards tabs for viewers/editors so that viewers/editors only can browse the plugin readme tab (which all plugin types have). Additionally, making the plugins page available in side menu for authenticated users.

**Comment by torkelo** [comment]
One option is to remove the plugin list panel (not sure it makes that much sense), and improve the plugin list view.
