### ISSUE TITLE
Elasticsearch: Lucene syntax highlighting in logs query field in Explore 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17907]
**What would you like to be added**:
Would be nice to have Elasticsearch logs query field in Explore highlighting the lucene syntax.

**Why is this needed**:
Makes it hopefully easier to see either what query you're using or either if the query is not properly formatted.

It was discussed/thought of a bit initially when implementing #17605 so adding this so that we can see if others are interested in this feature.

**Comment by kaydelaney** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html
Worth taking a look at for whoever ends up implementing this.
