### ISSUE TITLE
grafana rpm is unsigned

### ISSUE THREAD

**Issue by dialt0ne** [grafana/grafana#1790]
If you generate official grafana rpm gpg keys, you just need to add the `--rpm-sign` option to fpm to sign the package and the following to your .rpmmacros file:

```
%_signature gpg
%_gpg_name  <grafana key name>
```

See also: https://systembash.com/simple-guide-to-signing-rpms-with-fpm/

**Comment by torkelo** [comment]
Dam tricky to sign rpms in a automated way. But seems to work now, 
https://grafanarel.s3.amazonaws.com/builds/grafana-2.0.0_rc1-1.x86_64.rpm
https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

**Comment by dialt0ne** [comment]
Nice! Thank you!

$ sudo rpm --import RPM-GPG-KEY-grafana 
$ rpm --checksig  grafana-2.0.0_rc1-1.x86_64.rpm
grafana-2.0.0_rc1-1.x86_64.rpm: rsa sha1 (md5) pgp md5 OK

**Comment by deathsoverture** [comment]
The instructions under "YUM Repository" should be updated to reflect this change.  I modified two lines in my yum configuration to verify packages:
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

**Comment by torkelo** [comment]
@deathsoverture thanks, will do!
