### ISSUE TITLE
Annotations API : Support dashboard Uid

### ISSUE THREAD

**Issue by seuf** [grafana/grafana#17901]
**What would you like to be added**:
Allow posting annotations on dashboard with API with a dashboard UID instead of a dashboardId which can be different between two grafana instances : 

```
POST /api/annotations HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "dashboardUid": "1n1_XJVWz",
  "panelId":1,
  "time":1507037197339,
  "isRegion":true,
  "timeEnd":1507180805056,
  "tags":["tag1","tag2"],
  "text":"Annotation Description"
}
```

**Why is this needed**:
I have multiple grafana instance (for different staging environment) with dashboard provisionned automatically with the same `uid`.
I want to create annotations on dashboards with the API on new deployments, but I can't because the `id` will not be the same in all grafana instances.

**Comment by Lusitaniae** [comment]
Also seems to affect
https://grafana.com/docs/grafana/latest/http_api/dashboard_permissions/

Basically, looks like permissions API are not consistent

I can manage folder level permissions using uid, but annotations and dashboards can't (something else too maybe?)

https://grafana.com/docs/grafana/latest/http_api/folder_permissions/

PITA, given that the ansible modues for Grafana only return uid
