### ISSUE TITLE
Grafana performance degrades massively after sqlite->postgresql migration 

### ISSUE THREAD

**Issue by lsitzmann** [grafana/grafana#17913]
**What happened**:
I was running grafana in Azure in a kubernetes cluster using local sqlite based storage and had gread performance.
To reduce persistend state in our cluster we migrated the grafana-db to a hosted Azure postgresql database.
After migration the performance was about much worse than before.
A simple dashboard that rendered in sqlite based setup in less than a second takes up more than 10 seconds to render.

**What you expected to happen**:
Same performance as local sqlite.

**How to reproduce it (as minimally and precisely as possible)**:
Install the current stable grafana helm chart in a Azure kubernetes cluster and confiure it to work with an PostgreSQL-Service.

**Anything else we need to know?**:
Details also posted here: https://community.grafana.com/t/grafana-performance-degrades-massively-after-sqlite-postgresql-migration/18862 
**Environment**:
- Grafana version: 6.2.4
- Data source type & version: InfluxDB
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Windows, Chrome 
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
Sorry to hear this. We have no similar reports so maybe something specific with the postgresSQL service. 

Can you open chrome dev tools network tab and open a few pages under configuration (data source list, user list, etc), dashboard search. What is the performance like for those api requests? then open a dashboard, what is taking a long time? Reading the dashboard from the api or querying for data?

**Comment by lsitzmann** [comment]
Thanks for the response. Currently I can't because we rolled back the migration and enjoy the great performing grafana-influx-stack based on sqlite again.
But I can redo this migration on our dev-stage later today.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
