### ISSUE TITLE
Gauge Bar Query Naming Not Transferring to Graph (Elasticsearch)

### ISSUE THREAD

**Issue by smjaques** [grafana/grafana#17910]
**What happened**
I added multiple queries to bar gauge, and added their names in each under the alias. However, when I change their metrics (I am using extended stats) The query name does not take under each bar. Instead it says: Series[0], Series[1], ... 

**What you expected to happen**
I expected the query name to be below its bar. It shows up in the beginning with the basic metrics, but when those are changed so is the name.

**How to reproduce it (as minimally and precisely as possible)**
Create new bar gauge. Add specific query. Name query. Change metrics: Extended Stats (deselect all). Group by: Histogram (@timestamp), Then by: SelectDataField (Repeat with second query to get Series[1]).

**Anything else we need to know?**: Elasticsearch datasource.

**Environment**:
- Grafana version: 6.2
- Data source type & version: Elasticsearch 6.8.0
- OS Grafana is installed on: linux
- User OS & Browser: Mac 10.14.05, Chrome
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
Can you show your queries and panel settings? and what your query returns?

**Comment by smjaques** [comment]
There are errors when I try to upload files/photos. See here for them https://community.grafana.com/t/bar-gauge-alias-naming-not-showing-in-dashboard/18975

**Comment by torkelo** [comment]
the date histogram should be last.

**Comment by smjaques** [comment]
No data shows up when I set the metrics like that. (Group by: Terms -> field. Then by: date histogram)

**Comment by smjaques** [comment]
And the bars still aren't showing the name I gave them from the alias

**Comment by torkelo** [comment]
<img width="903" alt="Screen Shot 2019-07-04 at 09 39 08" src="https://user-images.githubusercontent.com/10999/60648151-a16e4f00-9e3f-11e9-8c06-7c02a2877a1f.png">

You should have Date histogram for time series results

**Comment by smjaques** [comment]
<img width="1380" alt="Screen Shot 2019-07-05 at 12 58 03 PM" src="https://user-images.githubusercontent.com/26877615/60743026-8fb2a780-9f24-11e9-8a12-860b44a35be0.png">

Yes, I have tried that and it never displays anything... despite the data being there when I look at the raw document metric.

**Comment by smjaques** [comment]
<img width="1358" alt="Screen Shot 2019-07-05 at 1 12 40 PM" src="https://user-images.githubusercontent.com/26877615/60743464-993d0f00-9f26-11e9-8c5d-97224800512b.png">
But it does display something with different metric selections... BUT not the name of alias

**Comment by smjaques** [comment]
It would be an easy fix if there was a way to set the Field Title (in vizualization tab) as $alias from the queries tab...? I just don't know what else to try... @torkelo
