### ISSUE TITLE
Explore: Support for additional operators in adhoc query field

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17916]
**What would you like to be added**:
Support for additional operators in adhoc query field.

**Why is this needed**:
Currently the adhoc query field supports equals and not equals operators, but would be nice to add support for regex equals and not equals to make it on pair with the adhoc filter support in dashboards.

**Comment by aocenas** [comment]
@marefr again not sure if the code changed or maybe this was meant for dashboards only?

**Comment by marefr** [comment]
Influxdb logs query field. Earlier on there was an idea that multiple datasources could use this query field, but I guess it should be labeled for influxdb:
![image](https://user-images.githubusercontent.com/1668778/72799906-85e55d00-3c46-11ea-8884-eaef39281285.png)

**Comment by gabor** [comment]
the ui changed a lot since this feature request, and after discussing with @marefr we decided to close this issue.
