### ISSUE TITLE
Align Query component interfaces & UI

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#17922]
Do not think all these interfaces should be specific to explore and should be aligned. 

Think we need to align these interfaces to single interface (QueryEditor) and having explore specific components here feels very messy. Maybe a property to pass in what mode the editor is shown in and the component can choose to hide/show parts. 

```ts
export interface DataSourcePluginComponents {
...
QueryEditor?: ComponentType<QueryEditorProps<DSType, TQuery, TOptions>>;
ExploreQueryField?: ComponentClass<ExploreQueryFieldProps<DSType, TQuery, TOptions>>;
ExploreMetricsQueryField?: ComponentClass<ExploreQueryFieldProps<DSType, TQuery, TOptions>>;
ExploreLogsQueryField?: ComponentClass<ExploreQueryFieldProps<DSType, TQuery, TOptions>>;
```

Also think we need to align the UI for query rows, having two UIs for the same thing feels very inconsistent. 

Exactly what should be different and how to solve some of this alignment still needs to be figured :)

**Comment by davkal** [comment]
The problem is less acute these days: the logs/metrics unification does away with the multiple fields, and there is a mechanism to use Explore-specific components only if they exist, otherwise fallback to standard editor.
