### ISSUE TITLE
Long Values double on gauge

### ISSUE THREAD

**Issue by 7Horizon** [grafana/grafana#17920]
**What happened**:
If the value on a gauge is too long, it is written twice with a minimal offset:
![2019-07-04_08h35_45](https://user-images.githubusercontent.com/7934441/60645761-e1cace80-9e39-11e9-978a-6af48785c2d1.png)

**How to reproduce it (as minimally and precisely as possible)**:
Make the value on gauge longer with prefix or postfix.

**Anything else we need to know?**:
Bug seems to be present since Version 6.1.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: InfluxDB 1.7.6
- OS Grafana is installed on: Ubuntu 18.04 LTS
- User OS & Browser: Windows 10, Chrome 75
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Looks like your using the singlestat panel, can you switch to the new Gauge panel?

**Comment by 7Horizon** [comment]
It looks fine on the new Gauge panel. Will you fix this error or is the gauge on the singlestat panel going to be deprecated?

**Comment by torkelo** [comment]
yes, it's going to be deprecated

**Comment by 7Horizon** [comment]
Ok, thanks for the info
