### ISSUE TITLE
$__interval is not correctly replaced with the range value

### ISSUE THREAD

**Issue by vlucian** [grafana/grafana#17924]
**What happened**:

I'm trying to use sum(increase(metric[$__interval])) type of queries inside a Singlestat or a Graph; instead of desired values I only get strange numbers (using Chrome devtools I could see instead of 12h calculated value was 5m  (for the Singlestat ) and 2m (for the Graph ); 24h was translated into 15m (Singlestat ) and remained 2m for Graph.

**What you expected to happen**:

$__interval should be replaced with the value calculated based on time range selected (formula is (from - to) / resolution )

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.2.5 (6082d19)
- Data source type & version: Prometheus 2.10.0
- OS Grafana is installed on:RHel
- User OS & Browser: Win7, Chrome
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
the resolution depends on how wide the panel is (pixels wide). 

Just did some tests and it seems to be working for me. 

24h = 60*60*24 = 86400 seconds

graph 1099 pixels wide, prometheus query resolution set to 1/1, 86400 / 1099 = 78s, rounded up to 2m, which is what Grafana sets $__interval to. 

If I change resolution to 1/2 (basically means double the step), means the interval is now 4m (240s)

**Comment by vlucian** [comment]
Then I guess I misunderstood some things there. I should just use $__range instead.
thanks!
