### ISSUE TITLE
Update SystemJS to latest version

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#17926]
Currently we use SystemJS@0.20.19. It would be good to try updating to the latest version (4.0.0 as of 2019, Jul 4th, and 6.10.0 as of 6th of October) as this is a core dependency we rely our plugin system on.

Some ref: https://github.com/grafana/grafana/pull/17927

**Comment by adrianromanko** [comment]
Agreed.
SystemJS 0.2.0 cannot transpile ES libs imported into grafana apps/panels.
Would be very helpful if upgraded to v6.x

**Comment by ryantxu** [comment]
I think we should consider this for 6.6

**Comment by tolzhabayev** [comment]
Closing in favour of pursuing federated modules https://github.com/grafana/grafana/issues/39961

If we decide to not go the federated modules direction we can revive this.

**Comment by jackw** [comment]
I'm going to reopen this issue. With the recent work on plugin CDN and the ongoing sandboxing project [module federation](https://github.com/grafana/grafana/issues/39961) doesn't look like the right tool for us without creating a lot of extra work.
