### ISSUE TITLE
Issue Quering Data from ElasticSearch

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#17923]
**What happened**:
Using ElasticSearch and Grafana together for quiet a long time but i never seen this issue before.
I setup correctly Data Sources and ElasticSearch indices mapping to gather metrics from computers with an agent (Telegraf).
Then i setup some quick monitoring dashboards to dsplay the metrics i gather and something pick my interest.

From the metrics i export, i display the system load of my computers. But the Load1 and the load5 are always at 0 for some agents. And i know for sure these computers are always working sometimes so these load can't be at 0 everytime.

If i look at the kibana i also setup i see all these metrics properly :
![image](https://user-images.githubusercontent.com/33425208/60652309-4db43380-9e48-11e9-9e33-6dfa8022fe09.png)

But when i make the query from Grafana, it just always display 0 :
![image](https://user-images.githubusercontent.com/33425208/60652416-7dfbd200-9e48-11e9-9f2e-68ed4dd94ce0.png)

And i'm sure grafana still gather message from the datasource : 
![image](https://user-images.githubusercontent.com/33425208/60652785-16925200-9e49-11e9-9b33-e032353fc152.png)

Configuration of the DataSource :
![image](https://user-images.githubusercontent.com/33425208/60652512-a8e62600-9e48-11e9-8ac6-76b576a0d467.png)

**What you expected to happen**:
Query that should return the correct metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Setup ElasticSearch 7.2.0,
Setup Grafana last stable version 6.2.5 (i also test this with the last nightlybuild 6.3.0-612b76ecpre )
Setup Telegraf 1.11.1 on other computers 
Config file on every computers of Telegraf :
```
[agent]
        interval                =       "15s"
        flush_interval          =       "15s"
        hostname                =       "ModSecurity"
        round_interval          =       true

[[inputs.cpu]]
        percpu                  =       true
        totalcpu                =       true

[[inputs.disk]]
        ignore_fs               =       ["tmpfs","udev","devtmpfs"]

[[inputs.mem]]

[[inputs.system]]

[[inputs.net]]
        interfaces              =       ["ens*"]

[[outputs.elasticsearch]]
        urls                    =       ["http://x.x.x.x:9200"]
        timeout                 =       "30s"
        health_check_interval   =       "30s"
        index_name              =       "local_modsecurity-%Y-%m-%d"
```

**Anything else we need to know?**:
That's the first time i see an issue like that. If you need any information about this issue like.

There is an exemple of a query send by Grafana that should return something different than 0 :
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["local_modsecurity-2019-07-04"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1562219740470","lte":"1562230540470","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"2":{"date_histogram":{"interval":"1m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1562219740470","max":"1562230540470"},"format":"epoch_millis"},"aggs":{"1":{"sum":{"field":"system.load1","script":{"inline":"_value"}}}}}}}
```
If i loook myself into Kibana, i can clearly see values :
![image](https://user-images.githubusercontent.com/33425208/60653536-7dfcd180-9e4a-11e9-9345-7897cc8c8628.png)

I don't really know if it is an issue with Grafana or not, but if i can see my values correctly from Kibana, i guess it's coming from Grafana ... Maybe ?

**Environment**:
- Grafana version: 6.2.5 and 6.3.0-612b76ecpre 
- Data source type & version: ElasticSearch 7.2.0
- OS Grafana is installed on: CentOS7 Minimal 1807
- User OS & Browser: Windows10 LTSB and Chrome
- Grafana plugins: Graph, Table, SingleStat

**Comment by torkelo** [comment]
your looking at the raw data in Kibana, so it's not looking at the same thing. In Grafana your looking at a Elasticsearch metrics query with a date histogram and a max aggregation. 

If you opened Query inspector you would see that Elasticsearch returned what Grafana shows. 

What you could try doing a graph date histogram query with max aggregation in Kibana. 

not sure what could cause this, try changing the date histogram interval, sure your looking at the same index?

**Comment by Theoooooo** [comment]
I'm sure i'm looking at the same index if i look the query send by Grafana. And it's acting strange because it also hapenning to other indices i got in my Elasticsearch but not all of them. And i setup every indices the same way.
Even if i looked at the raw_documents, i can see the values correctly but when they are processed, it's not returning the correct values. I can't really setup a lower interval because Telegraf only send data every 15 seconds. :
![image](https://user-images.githubusercontent.com/33425208/60655275-c4076480-9e4d-11e9-8a35-70a7c888984f.png)

So that should maybe not being an issue from Grafana but from Elasticsearch ? I see what's going on here on the result given by Elasticsearch, i get the point where the values are to low and the interval playing on the result but with heavy load on the system, the value of system.load1 vary a lot and should not return 0

**Comment by torkelo** [comment]
Maybe an index mapping issue?

**Comment by Theoooooo** [comment]
Oh man you made my day :
![image](https://user-images.githubusercontent.com/33425208/60656233-66741780-9e4f-11e9-97a9-f796757b1f49.png)
 That's why maybe xd. I didn't setup the mapping manually and the first time a value came in the index, Elasticsearch set the type to long because it was 0 i think.
Thanks for the reply and sorry for the inconveniance.
Have a nice day

**Comment by torkelo** [comment]
np, glad I could help!
