### ISSUE TITLE
feedback on login UI with github/google oauth

### ISSUE THREAD

**Issue by williamjoy** [grafana/grafana#1792]
I asked people to test github oauth login, looks like it might lead people input there github account and password in grafana. And someone refuse to test because he think grafana is stealing their github credential :)

Could you make some changes to the UI ?

![screen shot 2015-04-16 at 10 26 38](https://cloud.githubusercontent.com/assets/3284451/7173004/3fcae874-e423-11e4-9e77-f0178323927d.png)

**Comment by torkelo** [comment]
yes, thanks for your feedback

**Comment by ohTHATaaronbrown** [comment]
Along this route: I want the ability to completely disable the existing in-app login and sign-up pages and *only* allow login via google oauth.

**Comment by torkelo** [comment]
great idea, will close this for now. Just trying to clean up 2.1 milestone issues, this did not get many +1 votes to closing it. Might revist the login view in a later release
