### ISSUE TITLE
Missing docs for provisioning > jsonData > queryTimeout

### ISSUE THREAD

**Issue by victorhaggqvist** [grafana/grafana#17935]
**What happened**:

“Query timeout” (`queryTimeout`) for Prometheus is not listed in the “Json Data” table in 
https://github.com/grafana/grafana/blob/57c220c93d8d0db5f98a9ce9ef798b0febc7de5b/docs/sources/administration/provisioning.md#json-data. Setting `queryTimeout` however appears to work, so I’m guessing its just missing.

**What you expected to happen**:
Doc for “Query timeout” (`queryTimeout`) to be listed in the table https://github.com/grafana/grafana/blob/57c220c93d8d0db5f98a9ce9ef798b0febc7de5b/docs/sources/administration/provisioning.md#json-data

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Prometheus

**Comment by nicolastakashi** [comment]
Hi @torkelo how I can help add it?

**Comment by ninkaninus** [comment]
I have just tried this, without any luck:
`spec:
  datasources:
  - access: proxy
    isDefault: true
    jsonData:
      queryTimeout: 300s
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    type: prometheus
    url: http://PROMETHEUS_URL:9090
    version: 1`
    
    Any ideas why that could be?
    
    Small note is that I am using Bitnami's helm chart for Grafana operator

**Comment by arajkumar** [comment]
+1

**Comment by logston** [comment]
+1

**Comment by logston** [comment]
From what I can tell, the frontend UI uses `queryTimeout` but the backend server uses `timeout`.

FE UI: 
https://github.com/grafana/grafana/blob/v8.5.1/public/app/plugins/datasource/prometheus/datasource.tsx#L110

BE Server:
https://github.com/grafana/grafana/blob/v8.5.1/pkg/services/datasources/service/datasource_service.go#L425

**Comment by muffl0n** [comment]
This works for me:
```
        - name: xxx-loki
          type: loki
          url: https://loki.xxx/
          access: proxy
          jsonData:
            timeout: 60
```

**Comment by GrafanaWriter** [comment]
@gguillotte-grafana - Let's add to the backlog for the next phase of the Admin work.

**Comment by GrafanaWriter** [comment]
Given the age of this issue, and the lack of activity, I will close. Please reopen if the issue is still valid.
