### ISSUE TITLE
table plugin html sanitize ignoring colours declaration

### ISSUE THREAD

**Issue by pedro-andrade** [grafana/grafana#17936]
**What happened**:
After enabling the "Sanitize HTML" option of the Table plugin, parts of my HTML was not properly render. For example `<br>` was displayed correctly but `<font style="color: green;">` was not.

**What you expected to happen**:
The text within the HTML font tag to render in the correct colour.

**Environment**:
- Grafana v6.2.0
- InfluxDB v1.5
- CentOS 7.5
- Ubuntu 18.04

**Comment by torkelo** [comment]
font tags are not supported, 

https://docs.angularjs.org/api/ngSanitize/service/$sanitize
