### ISSUE TITLE
Add support for Dgraph database

### ISSUE THREAD

**Issue by joshhopkins** [grafana/grafana#17933]
**What would you like to be added**:

Dgraph query and monitoring support.

**Why is this needed**:

[Dgraph](https://dgraph.io) is a great open source database.

**Comment by dprokop** [comment]
@joshhopkins thanks for your suggestion! We don't plan to add support for Dgraph at the moment, so I will close the issue for now. Let's see what the community interest is, and if this issue will be upvoted we will consider adding it in the future.

**Comment by mickep76** [comment]
+1 support for dGraph

**Comment by LockedThread** [comment]
I second that there should be support for dgraph
