### ISSUE TITLE
n is undefined

### ISSUE THREAD

**Issue by simple-snow** [grafana/grafana#1793]
Hello!
I simply add an annotation config like
![_047](https://cloud.githubusercontent.com/assets/3039558/7174242/cd4c865e-e41d-11e4-8fde-21c22477550a.png)
and than have the error and annotations don't visible
![_046](https://cloud.githubusercontent.com/assets/3039558/7174265/3d060506-e41e-11e4-8ad3-8c37d3785f88.png)
is my configuration wrong? i using the same elasticsearch for both dashboards and annotations save
PS. When i disable and enable annotation tag lines became visible

**Comment by torkelo** [comment]
not sure, whats the response from elasticsearch?

**Comment by simple-snow** [comment]
response eg 
curl server:9200/events/_search ?

**Comment by torkelo** [comment]
Yea, in you screenshot I can see the request to elasticsearch, and an error occurs while processing that response.

**Comment by simple-snow** [comment]
![_050](https://cloud.githubusercontent.com/assets/3039558/7177681/fe6fe158-e441-11e4-8513-6c87ce27e1ca.png)
Maybe becouse i send empty tags in POST to elastic?

**Comment by torkelo** [comment]
No that is not it,I do not see a _timestamp field in the response

**Comment by simple-snow** [comment]
ok
it seems that I did not attribute mapping
now re-create the index and all works

**Comment by torkelo** [comment]
great
