### ISSUE TITLE
Using 'today' or 'this week' as range in combination with variables that use query_result returns empty responses

### ISSUE THREAD

**Issue by Br0mZ** [grafana/grafana#17941]
**What happened**: 
When selecting 'today' or 'this week' as a time range in combination with a variable that uses query_result, the variable is empty. When inspecting the network traffic, you can see that the timestamp being passed to the Prometheus query API is exactly the end of 'today' of 'this week' resulting in the response being empty.

**What you expected to happen**: 
I expect now() to be the biggest possible timestamp to pass to the instant query API, as it otherwise doesn't return data. A timestamp in the future will never return data.

**How to reproduce it (as minimally and precisely as possible)**: 
Create a new dashboard, create a variable which uses query_result (in my case query_result(kube_pod_info{}) ), inspect the timestamp passed with developer tools or any other monitoring tool. Then change the time range of the dashboard to today and see what happens, the response is empty and the timestamp corresponds with the end of today.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Prometheus 2.2.1
- OS Grafana is installed on: Official Docker Container
- User OS & Browser:
- Grafana plugins: none
- Others: none

Might be related to https://github.com/grafana/grafana/issues/16661

**Comment by dprokop** [comment]
Duplicate #16661
