### ISSUE TITLE
grafana-cli encrypt-datasource-passwords fails with sql error

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#17948]
Tried to encrypt datasource passwords with grafana-cli. It didnt work.

```
/usr/sbin/grafana-cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin data-migration encrypt-datasource-passwords cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana
t=2019-07-04T21:22:48+0000 lvl=warn msg="[Removed] Session setting was removed in v6.2, use remote_cache option instead" logger=settings
t=2019-07-04T21:22:48+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
t=2019-07-04T21:22:48+0000 lvl=info msg="Starting DB migration" logger=migrator

Error: failed to select column: basic_auth_password: sql: Scan error on column index 2, name "secure_json_data": unsupported Scan, storing driver.Value type <nil> into type *string

NAME:
   Grafana cli admin data-migration encrypt-datasource-passwords - Migrates passwords from unsecured fields to secure_json_data field. Return ok unless there is an error. Safe to execute multiple times.

USAGE:
   Grafana cli admin data-migration encrypt-datasource-passwords [arguments...]
```

I believe that this error is happening as some data_sources in the DB have 'secure_json_data' currently set to NULL.  The mysql schema as the column default set to NULL so this should be allowed.  But looks like the code is expecting the column to contain '{}' instead.

**Comment by woodsaj** [comment]
after running `update data_source  set secure_json_data = "{}" where secure_json_data is NULL;`  directly in the DB, the encrypt-datasource-passwords command now works.

**Comment by marefr** [comment]
For reference of the applied fix, there may be some other special cases left to handle: https://github.com/grafana/grafana/pull/18014#discussion_r301993430
