### ISSUE TITLE
Incorrect error for the first time during auth of disabled user

### ISSUE THREAD

**Issue by markelog** [grafana/grafana#17947]
**What happened**:
If user connected to LDAP and authenticated in Grafana, would be removed from LDAP, then during the first authentification attempt in grafana we will show "Incorrect user or password" error, for next attempts "User is disabled" error will be shown. But only if background LDAP sync did not happened between LDAP removal and user authentification in grafana actions.

**What you expected to happen**:
To show "User is disabled" after the first incorrect attempt to authentificate

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: from master

**Comment by marefr** [comment]
Is there any risk of account information leakage here or is "User is disabled" shown only when correctly entered username/password? If there are any risk, I would suggest always show "Incorrect user or password" and log the actual error.

**Comment by markelog** [comment]
Yeah, it's seems there is a bigger issue, since the `User is disabled` shown even if password is incorrect

**Comment by xlson** [comment]
The original intent was for the "user is disabled" message to be shown when a user logged in with the correct credentials only. Unfortunately, that is not possible if the user is disabled due to no longer being available in LDAP. I think the best behavior is what @marefr suggests, to always show "Incorrect username or password" and log an error.

**Comment by markelog** [comment]
Yep, exactly :)

**Comment by xlson** [comment]
@markelog Could you work on this or are you busy with other things? Would like to get this solved by early next week so that we can aim for a stable release next week.

**Comment by markelog** [comment]
Can do!
