### ISSUE TITLE
Scripted dashboard - get default datasource.

### ISSUE THREAD

**Issue by KaiPierre** [grafana/grafana#1794]
I'm currently working on the portability of our scripted dashboards on Grafana v2 environment.
I'm using a datasource in js, retrieved using : 
```js
var datasource = services.datasourceSrv.default;
```
and used in script like that : 
```js
datasource.metricFindQuery(...)
```
but in my browser console i get this error :
```
Uncaught TypeError: Cannot read property 'metricFindQuery' of undefined
```
I have a graphite datasource declared as default configurated.

Is it a bug or does something change in the v2 ?

(I have installed Grafana using the APT repository on packagecloud perhaps it's not the last version avaliable)

**Comment by torkelo** [comment]
I need to update the example for that (and the docs). 

datasources are treated as plugins and fetched async. 
services.datasourceSrv.get(dsName).then(function(datasource) {

});

dsName = null you will get the default one.

**Comment by luizsoares** [comment]
I apologize if this is not the best place to ask this question, but where are these examples? I'm trying to get my feet wet with scripted dashboards, but the examples supplied in the default distribution are very simple, and don't include how to grab a registered datasource, for instance.
Any pointers would be appreciated.

Cheers!
