### ISSUE TITLE
Make it possible to disable OAuth users

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#17955]
This is the next step after #11188
Now it's possible to disable/enable (from admin UI) only internal grafana users. LDAP users can't be disabled from the UI, but user will be disabled during the login process if it is not found in LDAP. Also, LDAP users can be disabled/enabled automatically with active sync feature (available in Enterprise version).

For users who signed in with OAuth this feature doesn't work completely. OAuth has its own [login handler](https://github.com/grafana/grafana/blob/315177fad78b281ff1e45d087b7cff65463562fd/pkg/api/login_oauth.go#L38) and we don't check user for `isDisabled` flag there. So maybe it makes sense to allow this feature for OAuth users.

There's a vulnerability thus - Grafana user who was disabled by admin can create OAuth account with the same login/email and sign in without any problem.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
