### ISSUE TITLE
Ability to apply user defined functions on series

### ISSUE THREAD

**Issue by gobwas** [grafana/grafana#1796]
Hello! 

Is there any ability to define user functions for series in user interface, or some other place?

At now, I see these for InfluxDB (that maps to the native functions of storage):

![clip](https://s3.amazonaws.com/f.cl.ly/items/2J372E0Q1Q3o130Q0Z1q/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-04-16%20%D0%B2%2013.20.00.png)

How can I add some custom function? As an idea, it could be, applied to the already fetched set.

**Comment by torkelo** [comment]
You need to add them in InfluxDB before aggregation, not in Grafana

**Comment by gobwas** [comment]
Did u mean I must save calculations to Influx, and then simply visualize
it?


Чт, 16 апр. 2015 г. в 18:08, Torkel Ödegaard <notifications@github.com>:

**Comment by torkelo** [comment]
No I mean your custom functions needs to be implemented/executed in InfluxDB during aggregation, if they are applied after aggregation they are very much less useful. Like you cannot apply a movingAverage function or holt winters forcast on already aggregated data.

**Comment by gobwas** [comment]
Got this. Thanks!
