### ISSUE TITLE
Robust Circle CI configuration for plugins

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17967]
With the new `@grafana/toolkit` we should make plugin end-to-end development and testing super easy and clear.

The toolkit should automatically produce a config that supports something like:
![image](https://user-images.githubusercontent.com/705951/61164471-505afc80-a4ca-11e9-8b25-b3508c3660de.png)

**build** runs a build task on any number of platforms and puts results in `dist` folder along with other build metadata (like coverage etc) in job folder in the workspace.  There is an optional **build-docs** step that will take everything in `/docs` and convert it into an html site.

**bundle** takes all the `ci/job/{job}/dist` folders and zip it into file.  If `docs` exists, that will also be zipped up as its own .zip file.  This task will also prepare a test environment from these artifacts.  It will *unzip* the files and set up provisioning directories

**test** Integration tests run from various versions of grafana.  Each platform will save screenshots and check e2e tests

**report** Look at all the artifacts and build a report that includes status for each version

**publish** For release branches, this can checkin the 'dist' folder and run `ghr` tool

----------

We should investigate using [orbs](https://circleci.com/orbs/), or perhaps more likely generating the circleci config based on some config file.

**Comment by dprokop** [comment]
@ryantxu is this something we can already close?

**Comment by torkelo** [comment]
Can we close?
