### ISSUE TITLE
dashboard link fails the first time a user in a different org uses it

### ISSUE THREAD

**Issue by lankester5** [grafana/grafana#17961]
**What happened**:
Given that a dashboard link is sent to another person, 
When that person is logged in to a different org than the one the dashboard is in
Then the link fails the first time it is used.

If you allow the link to timeout and then reclick the link it works and successfully changes the org of the person.

The link in question ends with the following:
/d/QNmRt87Zz/test?orgId=2

**What you expected to happen**:
I expect that when a person clicks on a link in that form then grafana should change their org as appropriate to present the dashboard first time round.

**How to reproduce it (as minimally and precisely as possible)**:
Set up 2 test dashboards in different orgs. record the URL from both dashboards.
attempt to use the link to one dashboard whiles logged in to the other Org.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.2.5 (6082d19)
- Data source type & version: N/A
- OS Grafana is installed on: OEL7
- User OS & Browser: MacOS Mojave -  Google Chrome
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
strange, tested this and unable to replicate. How is Grafana setup? (multiple instances behind load balancer? what SQL server?)

**Comment by lankester5** [comment]
I will need to double check on the load balancer situation, something I realise now that i failed to mention is that the browser was open and in session in a different org.
This was because the 'real world' scenario would be an ops person monitoring some dashboards, then getting an email which contained a link to a dashboard in another org to alert them of a problem. They would then click on this link, the default behaviour of chrome for me was the opening of a new tab. This would then result in the page not loading, needing to be closed and then the link reclicked on for it work. During this time the original tab is open with a dashboard open.

From my testing it appears that if I close all browser tabs then clicking the link works first time.
People do need to be logged in with a user account that is part of the relevant orgs in order to access the links, this why its likely that the users of this will be logged in to an account and org already in another tab.

I will reply again when I have some concrete facts on the grafana setup.

Thanks, Aron

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
