### ISSUE TITLE
disable_sanitize_html = true does not work in custom.ini

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17969]
I was trying to allow raw HTML in text panel... I tried setting 

```
[plugins]
enable_alpha = true
disable_sanitize_html = true
```

This did not change anything.

When I changed the setting in `defaults.ini` the setting seems to work

**Comment by torkelo** [comment]
where did you make the change? you have to copy sample.ini to conf/custom.ini for it to be read

**Comment by ryantxu** [comment]
user error... missing the [panels] section :(
