### ISSUE TITLE
Grafana can't load plugin CSS files

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#17965]
This happens after 428134482de3372ceec3498b3aa85a258c273b09
When I'm loading zabbix plugin (or any plugin with CSS imported with `loadPluginCss()` function) styles isn't loaded and I see an error in console:
```
system.src.js:1470 GET http://localhost:3000/css 404 (Not Found)
system.src.js:80 Uncaught (in promise) Error: Fetch error: 404 Not Found
```
But CSS defined properly:
```js
loadPluginCss({
  dark: 'plugins/alexanderzobnin-zabbix-app/css/grafana-zabbix.dark.css',
  light: 'plugins/alexanderzobnin-zabbix-app/css/grafana-zabbix.light.css'
});
```
This caused by changes in this line:
https://github.com/grafana/grafana/blob/428134482de3372ceec3498b3aa85a258c273b09/packages/grafana-runtime/src/utils/plugin.ts#L4
which previously was
https://github.com/grafana/grafana/blob/428134482de3372ceec3498b3aa85a258c273b09/public/app/features/plugins/plugin_loader.ts#L2
So after changing this back to `import System from 'systemjs/dist/system.js';` all works fine.

**Comment by torkelo** [comment]
Fixed in  https://github.com/grafana/grafana/pull/17927

**Comment by alexanderzobnin** [comment]
Ah, that's bleeding edge troubles :)
