### ISSUE TITLE
Legend drilldown links

### ISSUE THREAD

**Issue by sgmiller** [grafana/grafana#1797]
It would be great if we could click on a legend value and jump to a defined drilldown link, using the legend name and possibly value as get parameters.

Our specific use case:  We have a graph of the top 5 errors by error code, and want to link to our log search tool (Loggly) with the search populated with that error code so we can investigate.

**Comment by toni-moreno** [comment]
Hi @sgmiller , I did a similar request some weeks ago.  https://github.com/grafana/grafana/issues/1232. 

Could my approach also be useful on your use case?

Thank you very much!

**Comment by sgmiller** [comment]
Yes, I think my proposal is essentially the same as yours, and would be really useful for rapidly identifying issues from Grafana graphs and investigating them.

**Comment by torkelo** [comment]
Closed in favor of https://github.com/grafana/grafana/issues/1232
