### ISSUE TITLE
limit dashboard access for anonymous user 

### ISSUE THREAD

**Issue by RazaHasan84** [grafana/grafana#17979]
**What would you like to be added**:
we want to use anonymous user to display chart on TV. But anonymous user have access to all the dashboard. Is there any way to restrict this? following is our configuration
#################################### Anonymous Auth 
[auth.anonymous]
# enable anonymous access
;enabled = false

# specify organization name that should be used for unauthenticated users
;org_name = Main Org.

# specify role for unauthenticated users
;org_role = Viewer

#################################### Github Auth 
**Why is this needed**:
to push restriction on dashboard access

**Comment by dprokop** [comment]
@RazaHasan84 thanks for opening the issue. If I understand correctly, you want the anonymous user to be a Viewer for only some of the dashboards in your organisation.

You can achieve that by removing the Viewer permissions from the dashboards that you want to be hidden from anonymous users. To do so, go to  dashboard settings -> Permissions and remove the Viewer role:

![image](https://user-images.githubusercontent.com/2376619/60802795-08f70800-a17a-11e9-91e7-4138909bc421.png)

Also, please note, that all of the users in your organisation that have Viewer role, will loose access to those dashboards as well.

**Comment by RazaHasan84** [comment]
@dprokop really appreciate your quick turn around. but Users dont have permission button on left pane! however it is only visible when I login as "admin" user

**Comment by prostohant** [comment]
> @RazaHasan84 thanks for opening the issue. If I understand correctly, you want the anonymous user to be a Viewer for only some of the dashboards in your organisation.
> 
> You can achieve that by removing the Viewer permissions from the dashboards that you want to be hidden from anonymous users. To do so, go to dashboard settings -> Permissions and remove the Viewer role:
> 
> ![image](https://user-images.githubusercontent.com/2376619/60802795-08f70800-a17a-11e9-91e7-4138909bc421.png)
> 
> Also, please note, that all of the users in your organisation that have Viewer role, will loose access to those dashboards as well.

We are deploying  Grafana by ansible. By default, anonymous user can view all dashboards, but in our configuration should see only one.
IMHO manage permissions from each dashboard on several servers is not good idea.
is there any way to manage dashboard  permissions from config file?
