### ISSUE TITLE
beta: All-series tooltip can result in unexpected timestamp

### ISSUE THREAD

**Issue by alienth** [grafana/grafana#1798]
![image](https://cloud.githubusercontent.com/assets/218431/7191145/d2452f02-e437-11e4-8e0b-b3d38ece54a9.png)

As you can see from above, my cursor is higlighted above the 1100 mark, yet the timestamp displayed in the tooltip is 1044. I believe this is due to a metric which lacked datapoints after the 1044 mark.

This is not exactly a bug, but more of a minor annoyance. Makes it tricky to closely read how a set of datapoints changed over time via the tooltip. It might be better to display the latest metric's timestamp rather than the earliest?

**Comment by torkelo** [comment]
tricky if the tooltip date should show the point of the red line, or the point of the closest matching data point. (Now it looks like it shows the datetime for the first matching data point)

**Comment by torkelo** [comment]
related to this issue, https://github.com/grafana/grafana/issues/3063
