### ISSUE TITLE
Give the /metrics endpoint it's own port (optionally)

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#17987]
Make it possible to put the Prometheus `/metrics` endpoint on a separate port so that access to the metrics endpoint can be easily separated out so that only internal infrastructure can access it.

This came up in a discussion with the hosted team (@DanCech @woodsaj).

**Comment by bLiGM** [comment]
Hi Grafana folk,

My organisation is interested in this use case - in particular having a separate HTTPS user interface and a plain HTTP metrics interface. We'd would be up for working on it in our upcoming sprint. Do you have any pointers for a sensible design for this (assuming unfamiliarity with the Grafana codebase)?

**Comment by jessabe** [comment]
You can do this with Nginx, going to close for now.
