### ISSUE TITLE
Parameter in subject line in Alert mail is not working

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#17983]
Good Morning, 

I have created Alert rule for my graph, and in the Name Field in the Alert Tab, Used Parameter
[[server]] [[$__to]] ::  4 >= builds failures in past 6 hour

It is sending mail with 
[Alerting] [[server]] [[$__to]] ::  4 >= builds failures in past 6 hour

I was Expecting It should send value of these parameter.

Let me know if I am doing anything wrong 

Thanks in Advance 

Regards, 
Vijay Panchal

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@vpanchal72 we don't support that. There is an open feature request for that, that you can upvote: https://github.com/grafana/grafana/issues/7121
