### ISSUE TITLE
Cannot query App Insights dimensions that have a space in the name

### ISSUE THREAD

**Issue by Marsgate** [grafana/grafana#17989]
**What happened**:
When using app insights to query any metric, if I group by a custom dimension with a space in the name, Grafana returns the error "Something went wrong while running the query" 

**What you expected to happen**:
I expected for the query to run successfully and return some data that is grouped by my custom dimension.

**How to reproduce it (as minimally and precisely as possible)**:
Create a metric with a dimension that has a space in the name using app insights and query that metric using Grafana.

**Anything else we need to know?**:
Using the query inspector, it appears that the url is not properly encoding spaces for the dimension,

This is what we got:
`[...snip]customMetrics/Queue%20Message%20Processed?timespan=2019-07-08T11:21:58Z/2019-07-08T17:21:58Z&aggregation=avg&segment=customDimensions/Message Type&interval=PT1M`

This is what we expected:
`[...snip]customMetrics/Queue%20Message%20Processed?timespan=2019-07-08T11:21:58Z/2019-07-08T17:21:58Z&aggregation=avg&segment=customDimensions/Message%20Type&interval=PT1M`

**Environment**:
- Grafana version:  v6.2.1
- Data source type & version: Azure v6.2.1
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Google Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by kylebrandt** [comment]
I'm not sure, at least as of version 7.1, that this is Grafana and not Azure's API. (It is hard to check, because at least for me the API site for dev, https://dev.applicationinsights.io/quickstart/, seems to have cert problems and HSTS enabled.

But Grafana logs the following when I try customEvents/count with customDeimension/Page Title:
```
st URL="https://api.applicationinsights.io/v1/apps/DEMO_APP/metrics/customEvents/count?aggregation=sum&interval=PT1M&segment=customDimensions%2FPage+Title&timespan=2020-07-15T13%3A12%3A31Z%2F2020-07-15T19%3A12%3A31Z"
DBUG[07-15|15:12:31] Request failed                           logger=tsdb.azuremonitor status="500 Internal Server Error" body="{\"error\":{\"message\":\"Unexpected error occurred\",\"code\":\"InternalServerFault\",\"innererror\":{\"code\":\"InternalServerFault\",\"message\":\"Something went wrong while running the query\",\"correlationId\":\"6517968b-53bb-4278-996b-c60692c02fdf\"}}}"
```

In the above example, the space is encoded as a `+`, but even with curl and changing it to `%20` I get an error:

```
curl -H 'X-api-key: DEMO_KEY' https://api.applicationinsights.io/v1/apps/DEMO_APP/metrics/customEvents/count\?aggregation\=sum\&interval\=PT1M\&segment\=customDimensions%2FPage%20Title\&timespan\=2020-07-15T12%3A57%3A47Z%2F2020-07-15T18%3A57%3A47Z          
{"error":{"message":"Unexpected error occurred","code":"InternalServerFault","innererror":{"code":"InternalServerFault","message":"Something went wrong while running the query","correlationId":"4203e9a3-9429-48f8-8fcb-9971ed1f0668"}}}
```

**Comment by kylebrandt** [comment]
One might be able to work around it with Insights Analytics in 7.1, with the following as an analytics query:

```kusto
customEvents 
 | where timestamp >= $__timeFrom() and timestamp <= $__timeTo()
 | extend dp = todynamic(customDimensions)
 | summarize count() by bin(timestamp, $__interval), EventName = tostring(dp["EventName"])
 | order by timestamp asc
```

Except replace EventName in quotes to your property, when I try it with "Page Title" it doesn't complain, but my data doesn't seem to have that.

**Comment by sunker** [comment]
Thanks for reporting this! We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics). I'm closing this issue now, but feel free to reopen if you feel the need to.
