### ISSUE TITLE
Singlestat and Table alert

### ISSUE THREAD

**Issue by AnderCrafter** [grafana/grafana#17992]
Hello, it would be wonderful if we would be able to create Alerts for Singlestats and Tables

or when is this going to be implemented?
"Currently only the graph panel supports alert rules but this will be added to the Singlestat and Table panels as well in a future release."
https://grafana.com/docs/alerting/rules/

**Comment by torkelo** [comment]
We currently have no plans to do this, the current plan is to make alerts standalone entity that is not defined as a part of a dashboard panel

**Comment by rbagu** [comment]
When is the expected delivery date for the standalone alerts entity?  I'm also interested in setting up alerts for multiple non-graph panels.

**Comment by torkelo** [comment]
Hopefully later this year

**Comment by steenstra** [comment]
Is there an issue we can subscribe to so we can get notified when this is implemented?

**Comment by Skieski** [comment]
Ditto, would really like to know when this is implemented.

**Comment by torkelo** [comment]
Never, we plan to move alert rules out of dashboard / panels and make them a standalone entity with its own UI and workflow.

We will make it possible to link to 1+ panels (any type) from an alert rule

**Comment by johntdyer** [comment]
@torkelo Not entirely sure I can visualize what that would look like but I am excited never the less.  I would like to know if this new workflow will enable users to have multiple thresholds a single measurement ? Kinda like what is being requested in #7832 ?

**Comment by ggiinnoo** [comment]
Is there still a change this feature will come soon?

**Comment by steenstra** [comment]
> Never, we plan to move alert rules out of dashboard / panels and make them a standalone entity with its own UI and workflow.

@torkelo 
Is there an issue we can subscribe to so we can get notified when this is implemented?

**Comment by dvernon38** [comment]
Is there an update to when alert rules will become a standalone entity.

**Comment by GabrielGhe** [comment]
Interested in this feature as well.

**Comment by hamzash9500** [comment]
any update?!

**Comment by pjbc** [comment]
Hi there, any update?
