### ISSUE TITLE
Bar Gauge displaying different values (only sometimes...)

### ISSUE THREAD

**Issue by smjaques** [grafana/grafana#17990]
**What happened**:
I am using the bar gauge graph to show used memory from different csv files. They are all in the exact same format and their columns are configured in one .conf file. Their metrics are also all the same. However, sometimes a random (I say this because I don't know where it comes from) value shows as the value of a bar or two. Sometimes they shift around. And sometimes they are all the values they should be...

**What you expected to happen**:
I expected the memory date point to show up on the graph that I specify. And to be the last value added to the file (the current). And for them to not randomly display a very large number that is not in the memory column in the csv.

**How to reproduce it (as minimally and precisely as possible)**:
Configure elasticsearch with .csv files. Set the query to be the name of one specific .csv in the directory configured. 
Metric: max (hidden) I did not select a field. 
Group by: histogram --> @timestamp. 
Then by: Terms --> memory.

**Anything else we need to know?**:
YES, previously not solved: the bars aren't being named what I set them to be in the alias. And setting date histogram to last does not solve the problem (it leads to a "no data" message/empty graph)

Visualization tab is set to 
show: calculation 
calc: last

**Environment**:
- Grafana version: 6.2
- Data source type & version: Elasticsearch 6.8.0
- OS Grafana is installed on: linux, ubuntu
- User OS & Browser: mac mojave, chrome
- Grafana plugins: none
- Others:

**Comment by smjaques** [comment]
![7825648E-9200-488F-81A0-1BE8CDA4C518](https://user-images.githubusercontent.com/26877615/60831064-86684b80-a16d-11e9-85b3-9a025f212826.png)

**Comment by torkelo** [comment]
you have to include your panel settings and the response from you query, so we can analyze and see that the visualization is not showing what ES returns .

**Comment by smjaques** [comment]
![8D748877-64EC-4980-B757-D30A97AE4F4C](https://user-images.githubusercontent.com/26877615/60839088-309d9e80-a181-11e9-9cc3-8bb26e40616b.png)
![A10EA152-8252-4264-A8A2-D294547E48D9](https://user-images.githubusercontent.com/26877615/60839089-309d9e80-a181-11e9-942f-eb55e8ec1d8a.png)

**Comment by smjaques** [comment]
Is this enough information?

**Comment by torkelo** [comment]
Please use query inspector to show what Elastic is returning from your metric & histogram query. 

Why are you having a histogram on timestamp? if you are creating a time series query you should have a date histogram and it should be last.

**Comment by smjaques** [comment]
I have tried that, but it returns no data. Here is the query inspector when I try the date histogram last
![75E3BB17-BB99-48E0-ABC0-6F8AE5F893D3](https://user-images.githubusercontent.com/26877615/60840210-d94cfd80-a183-11e9-9a25-0175e09e753e.png)
 with one query:

**Comment by smjaques** [comment]
And here is the query inspector with the histogram query 
![53CA460B-3A1C-42E3-B9A2-F88432FA4C8C](https://user-images.githubusercontent.com/26877615/60840250-ea960a00-a183-11e9-9b72-58a023565d62.png)

**Comment by smjaques** [comment]
It has normal, correct data now but that changes often and shows a random false one very often (like I mentioned in original post)

**Comment by torkelo** [comment]
if date histogram does not work, maybe something strange with your timestamp? or index mapping?

**Comment by torkelo** [comment]
Anyway, I think this has nothing to do with Bar Gauge but something is not right with your query. You would not get any graph lines either with your query. 

See working example here:
https://play.grafana.org/d/VzxU55SWk/elasticsearch-bar-gauge?panelId=1&edit&fullscreen&orgId=1

**Comment by smjaques** [comment]
in that link, when I select when I change the display panel settings to calculate the LAST / Current value. it does not show a value on them...
