### ISSUE TITLE
401 Unauthorized -- Grafana 2.0.0-RC1 build 4/15/2015 @ 08:49 am

### ISSUE THREAD

**Issue by jgerschk** [grafana/grafana#1799]
In the latest build ( Ubuntu/Debian (64bit) .deb package grafana_latest_amd64.deb ‎4‎/‎15‎/‎2015‎ ‎8‎:‎49‎:‎12‎ ‎AM ), this problem has come back to the point where it is not functional again.

The symptoms are the same in the log

2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 238.1Âµs
2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 218.7Âµs
2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 239.3Âµs
2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 236.9Âµs
2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 235.2Âµs
2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 392.4Âµs
2015/04/16 16:21:21 [I] Completed /api/datasources/proxy/1/series 401 Unauthorized in 242Âµs
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 670.5Âµs
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 4.1152ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 280.3Âµs
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 6.5772ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 6.6854ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 6.7688ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 5.9354ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 238Âµs
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 16.9332ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 17.204ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 15.2974ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 17.2733ms
2015/04/16 16:21:21 [I] Completed /api/login/ping 401 Unauthorized in 15.4326ms
 

Reference issue #1667.

![auth issues again](https://cloud.githubusercontent.com/assets/7864285/7191675/0c5a142e-e455-11e4-992d-f6ff60e11983.png)

**Comment by torkelo** [comment]
are you sure you did not just have multiple tabs open and logged out or cleared cookies? 

The fix for #1667 still works (try removing the grafana_sess cookie while on a dashboard with refresh and the session will be renewed).

**Comment by jgerschk** [comment]
@torkelo, nope no multiple tabs opened.

Now having said that, I've left it running since refreshing that page, and re-logging because the session expired there, and it has not done it again.  

I'm starting to wonder if it might have been related to the issues and problems I had going from B1 - RC1. 

I think for now we can close it and I'll keep a watch on it on my end, and see if it comes back again.

Apologies for the false alarm.
