### ISSUE TITLE
Problem graph with Grafana 6.2.5 and Elastic Search 7.2.0

### ISSUE THREAD

**Issue by S0ulHunt3r** [grafana/grafana#17991]
**What happened**:
Selecting last two days now gives the error "Unkown elastic error response".
On elastic search log "elasticsearch_deprecation.log" i only see this error:
[2019-07-08T18:30:53,498][WARN ][o.e.d.s.a.b.h.DateHistogramAggregationBuilder] [xxxxx] [interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future.

**What you expected to happen**:
Seeing data painted on the graph for the last  two days.

**How to reproduce it (as minimally and precisely as possible)**:
Just select "last 2 days"

**Anything else we need to know?**: 
I have this option working with the same grafana version but with elastic 6.7.1.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Elasticsearch 7.0+
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- User OS & Browser: Windows 10 with Chrome last version

**Comment by marefr** [comment]
Deprecation notice for Elasticsearch v7.2: https://www.elastic.co/guide/en/elasticsearch/reference/7.2/search-aggregations-bucket-datehistogram-aggregation.html#_calendar_and_fixed_intervals

If anyone is interested in working on this changes needs to be made in both frontend and backend with included tests and should be backward compatible with Elasticsearch 2.x-7.1.x. I haven't had time to read up on what the actual changes means so I cannot suggest a suggested solution of changes for this.

**Comment by willemdh** [comment]
For me Grafana 6.2.5 with Elastic 7.2 backend is still working. The only think that does not work anymore is executing a query with multiple values selected. When 1 value (for example a hostname or processname) is selected, everyhting works fine.

**Comment by srclosson** [comment]
I've tried to reproduce this with Elastic 7.2 and Grafana 6.3.5 and everything seemed to work fine, even with multiple values selected. My elasticsearch is being populated by Telegraf and it's primarily host data (uptimes, cpu, diskio stats etc). 

Elastic is running in docker.

Perhaps it's not a problem anymore?

**Comment by daleckystepan** [comment]
I'm still experiencing this issue. Grafana 6.3.5 (official docker image) and elastic 7.3.1 (rpm on centos 7).

**Comment by willemdh** [comment]
The issue was related to the max buckets elasticsearch directive. Things work fine atm

**Comment by S0ulHunt3r** [comment]
Hi, with grafana 3.2.5 and elastich 7.3.1 i only have to work with search.max_buckets propertie.
The error that i observed no longer appears.
