### ISSUE TITLE
Complete Graphite Dashboard import

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18]
The import feature is not really completed. Just a prof of concept at this stage.

**Comment by fanis** [comment]
I'm getting the below when attempting List dashboards:

TypeError: undefined is not a function
    at l.b.listAll (http://10.10.5.81:3000/app/app.8ae07506.js:24:18783)

Got graphite working as a source to grafana, can write and display metrics in dashboards having set the graphite data source with access=proxy.

**Comment by torkelo** [comment]
@fanis seems to be a bug in Grafana 2.0 beta1 and graphite dashboard import. Fixed in master.

**Comment by fanis** [comment]
Thanks @torkelo

**Comment by phrend** [comment]
I just installed 2.0.2-1 on CentOS, added 3 Graphite Data Sources (they are older v0.9.10 Graphite servers, which I hope to upgrade soon), and when I click the "List dashboards" button for any of these 3 Data Sources, nothing happens.

I tried modifying /etc/grafana/grafana.ini to include:

    [log]
    mode = file
    level = Debug

then restarted grafana, and tried again, but nothing is output to `/var/log/grafana/grafana.log` after:

    2015/05/19 19:43:28 [I] Listen: http://0.0.0.0:3000

**Comment by torkelo** [comment]
The graphite dashboard import is not working if you have data source proxy mode (due to the fact that the graphite url for searchin dashboards is weird and non standard, switch data source access to direct

**Comment by phrend** [comment]
@torkelo Thanks for the reply! I tried setting my data sources to direct, but when trying to import, I'm getting:

    Failed to load dashboard list from graphite
    Error

I am able to access all of my graphite servers using the same URLs as set in the Data Sources directly in my browser. (one still has the CORS stuff still set up from when I was testing 1.x Grafana on it)

The logs on my graphite server (the one with the CORS config) show the following (IPs and hostnames altered):

direct (generates the above error):

    xxx.xxx.xxx.xxx - - [20/May/2015:00:10:30 -0700] "GET /dashboard/find/?query= HTTP/1.1" 200 1608 "http://grafana.server.blah:3000/dashboard/import" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"

proxy (no error, but nothing happens):

    yyy.yyy.yyy.yyy - - [20/May/2015:00:11:07 -0700] "GET /dashboard/find?query= HTTP/1.1" 200 1003 "http://grafana.server.blah:3000/dashboard/import" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"

If I browse to http://graphite.server.blah/dashboard/find/?query= manually in my browser, I do see the JSON list of my dashboards.

The behavior is exactly the same for a graphite server that does not have the CORS stuff set up.

Any idea what's going wrong? (thanks!)

**Comment by torkelo** [comment]
When you enable direct mode you get an error, can you open chrome dev tools (f12) and inspect what error graphite returns?

**Comment by phrend** [comment]
My graphite apache vhost currently includes the following (the origin was more specific, but I changed it to * to see if that had anything to do with it - doesn't seem to have been the problem):

    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET, OPTIONS"
    Header set Access-Control-Allow-Headers "origin, authorization, accept"

The error I'm getting in my browser, when my data source is set to direct, and I try to list the dashboards is:

    XMLHttpRequest cannot load http://graphite.server.blah/dashboard/find/?query=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://grafana.server.blah:3000' is therefore not allowed access.

**Comment by torkelo** [comment]
try adding `content-type` as allowed header, and also POST in the allowed-methods

**Comment by phrend** [comment]
I tried deleting one of my data sources, and it took over a minute to refresh the page (the pop-up saying it was deleted appeared right away)... so I tried deleting all of my data sources, which took a few min. I then went to the dashboard view, then back to the data sources view, and all of my data sources were back again. Seemed funky, so I uninstalled grafana, manually removed everything from `/var/lib/grafana/` and re-installed. This time, I only added one data source, configured it as direct, and left my CORS config as it was (did not add the options you suggested above), and the list dashboards button is working now! So, I'm not sure what happened, but hopefully it was some kind of data corruption in sqlite3 that won't come back!

@torkelo Thanks for your suggestions - I'll post if I run in to anything like this again.

**Comment by drocsid** [comment]
I had the same issue, an XMLHttpRequest error. I'm also running 0.9.10 graphite servers. I removed the data sources without any issues. Then adding Header set Access-Control-Allow-Origin "*" on my graphite server virtual host file resolved my issue.

Thanks!

**Comment by djandreau** [comment]
Hello, I am very new to getting this system setup. Where exactly is the graphite nginx file located? Thank you.

**Comment by torkelo** [comment]
closing for lack of interest / PR
