### ISSUE TITLE
Influxdb mutiple urls support in server access mode

### ISSUE THREAD

**Issue by gavinesl** [grafana/grafana#18001]
**What would you like to be added**:
When we create an influxdb datasource, we can set [http]URL field mutiple influxdb urls  like: "http://10.0.0.1:8086,http://10.0.0.2:8086"

**Why is this needed**:
For "HA" reason, we set 2 or more influxdb instances, so we wish mutiple influxdb urls were supported (like telegraf), but when input mutiple urls  , grafana report an error:
**Network Error: Bad Gateway(502).**
Additional, I found influxdb datasource impl (https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts) already supports mutiple urls(split with ","), so, is this feature  coming soon?

**Comment by dprokop** [comment]
@gavinesl thank's for reporting. @torkelo could you please take a look at this one?

**Comment by ryantxu** [comment]
@gavinesl -- it looks like the HA mode only works if you are using direct access browser mode:
![image](https://user-images.githubusercontent.com/705951/60997568-f4e31000-a30b-11e9-8162-48f9ddc9f8b1.png)

In proxy mode I get the same 502 error you see.

**Comment by voiprodrigo** [comment]
This would be great to have!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
