### ISSUE TITLE
Packages: add cross references to package.json before publishing to npm

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#18009]
Another issue we need to deal with is how packages depend on one another.
```
runtime -> depends on -> ui -> depends on -> data
```
BUT we don't want the deps in main package.json since that is suppored via workspaces

In our publish scripts, can we add the dependency with the right version (since they will all share version at release)

_Originally posted by @ryantxu in https://github.com/grafana/grafana/pull/17985#issuecomment-509304154_

**Comment by ryantxu** [comment]
We also want to force/encourage a label either `next` or `latest` when publishing.  I just ran:
```
3. Run `packages:publish` to publish new versions
   - add `--dist-tag next` to publish under `next` tag
```
with out any labels and now v38 is in the history:
![image](https://user-images.githubusercontent.com/705951/60910637-30130f80-a236-11e9-9e7a-777934962912.png)

**Comment by torkelo** [comment]
not sure I understand what the task is in this issue. is it that @grafana/ui 6.4.2 does not depend on @grafana/data 6.4.2 ?

**Comment by dprokop** [comment]
@torkelo closing this one as it's not longer relevant. Dependencies version is synced by lerna when preparing npm release.
