### ISSUE TITLE
Alert notification images do not timeout but contains no series

### ISSUE THREAD

**Issue by peay** [grafana/grafana#18024]
**What happened**:

I have a graph from InfluxDB with a point every minute:

![image](https://user-images.githubusercontent.com/7261177/60970127-9759be00-a321-11e9-9063-a46abd87eba3.png)

I have configured an alert (tried different settings, all lead to the same result - say evaluate every minute for 5m, firing when avg query(A, 1m) is greater than a threshold). In the UI, the plot takes a second or so to render.

When the alert should fire, I can confirm the job is running:

```
lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=15.247 alertId=5 name="Disk usage (TSM filestore) alert" firing=true attemptID=1
```

Note `timeMs` which seems to confirm the query is rather fast. Next, in the logs, PhantomJS ran and no error is visible:

```
t=2019-07-10T08:03:12+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=https://localhost:3000/d-solo/6SjRYhIWz/influxdb-2?orgId=1&panelId=15&render=1 width=1000 height=500 png=/var/lib/grafana/data/png/WloifPR1TEfckmp8xGE6.png domain=localhost timeout=60 renderKey=xxxx]" timezone=
t=2019-07-10T08:04:13+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: https://localhost:3000/d-solo/6SjRYhIWz/influxdb-2?orgId=1&panelId=15&render=1 status: success 60000\n"
t=2019-07-10T08:04:13+0000 lvl=dbug msg="Image rendered" logger=rendering path=/var/lib/grafana/data/png/WloifPR1TEfckmp8xGE6.png
```

This is a bit slow (a minute, I set `GF_ALERTING_EVALUATION_TIMEOUT_SECONDS=60` as otherwise it tends to time out before 30s), but it says it worked.

However, this is the image included in the notification (I removed some of the tags):

![image](https://user-images.githubusercontent.com/7261177/60970195-bce6c780-a321-11e9-8c57-32cd796a48e9.png)

Now... it is suspicious that it takes almost exactly 60s when I have set `GF_ALERTING_EVALUATION_TIMEOUT_SECONDS`. However, setting that to 60s, I do not see

```
t=2019-07-10T07:23:42+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
t=2019-07-10T07:23:42+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-07-10T07:23:42+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter" 
```

that I had with the default of 30s.

To make sure, I have increased `GF_ALERTING_EVALUATION_TIMEOUT_SECONDS` to 600s, and the timeout message was back after 600s:

```
t=2019-07-10T08:20:48+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=https://localhost:3000/d-solo/6SjRYhIWz/influxdb-2?orgId=1&panelId=15&render=1 width=1000 height=500 png=/var/lib/grafana/data/png/USkfr3V2oBtMpgYfUb0U.png domain=localhost timeout=600 renderKey=xxxx]" timezone=
t=2019-07-10T08:30:48+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: https://localhost:3000/d-solo/6SjRYhIWz/influxdb-2?orgId=1&panelId=15&render=1 status: success 600000\n"
t=2019-07-10T08:30:48+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
t=2019-07-10T08:30:48+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-07-10T08:30:48+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
```

In summary:

- At the default to 30s timeout, the timeout fires and the notification is not sent.
- Increasing the timeout to 60s, the timeout does not fire, but rendering takes exactly 60s, and the notification image has no series.
- Increasing the timeout to 600s, the timeout fires and the notification is not sent.

Whenever the timeout fires, there are no additional errors or debug messages that would help with troubleshooting why it did timeout (in spite of `--debug=true` correctly being passed to phantomjs)

**What you expected to happen**:

- For 60s timeout, the timeout should fire instead of producing a notification image without series.
- At general debug log level, more information should be available to troubleshoot why the rendering is stuck.

**How to reproduce it (as minimally and precisely as possible)**:

Not quite sure. I am using:

- `GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=local`
- `GF_ALERTING_NOTIFICATION_TIMEOUT_SECONDS=600`
- Web auth proxy, HTTPS

I have tried a dozen different times, and the output is always the same. For timeout=60s, this affects both the OK and ALERT graphs.

I have added `rendering:debug` to `GF_LOG_FILTERS`, and set `GF_LOG_LEVEL` to `debug`.

Running as a container on kubernetes. The CPU/memory limits are never close to being reached. Configuration is:

```yaml
  requests:
    memory: 512Mi
    cpu: 500m

  limits:
    memory: 1500Mi
    cpu: 2000m
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.2.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: Official docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peay** [comment]
Additional information: my dashboard does not have auto-refresh (not sure if that's relevant)

**Comment by aocenas** [comment]
Hey @peay I am looking into this but it is not something to easily reproduce (no luck so far). What you see in the output are 2 different ways a timeout can happen as there is one implemented in JS code and one on Go side. As they are not exact (in JS we just do setTimeout and periodically check what was rendered) they can overlap in way that at one point you get JS timeout (which at this moment means no error and you just get uncomplete web page) or Go which will log error. Not great but as we are trying to get rid of phantomJs probably not something we will be fixing right now.

So the issue you have seems to be with the panel itself in some way, or with how it is rendered for the alert. `Loading a web page: https://localhost:3000/d-solo/6SjRYhIWz/influxdb-2?orgId=1&panelId=15&render=1 status: success 600000\n"` this the url that is opened, it is a bit special for the purpose of generating the image, can you open it directly and verify there isn't some error and that it loads in reasonable time (ideally at the same time trying the image rendering to make sure this wasn't something transient)?

**Comment by peay** [comment]
Thanks for the context @aocenas. Seems like aside from that slight timeout inconsistency, this may just be an issue with the way my Grafana is setup.

I can access that page and see the panel from my browser, but it seems to still fail from PhantomJS. I use a reverse proxy and Grafana (hence PhantomJS) won't be able to access that public URL directly (both for auth and networking reasons). I did not see anything relevant to alert notifications at https://grafana.com/docs/installation/behind_proxy/ though, am I missing something? Should `--debug` with PhantomJS produce more logs?

**Comment by aocenas** [comment]
Hmm I am not sure if the proxy is the problem. The URL itself is localhost (`https://localhost:3000/d-solo/6SjRYhIWz/influxdb-2?orgId=1&panelId=15&render=1`) and we do authentication based on special token injected into the cookies before loading. Also the image you attached shows actual panel output (legend and header) just without the graph (or even space for the graph as would be if the query completed and no data were returned).

Based on that I would say the problem is in the data query, and that the query runs ok when you access the panel from the browser but either errors out (not sure right now if there should be error output or not) or just never returns for some reason.

Can you try creating some simple query with the same datasource and render it (you can do the same rendering when you click panel header -> Share -> Direct link rendered image)? If it is not possible to render any panel with the datasource (meaning the rendering will either timeout or return just panel without any content) it is probably some issue with how the datasource is setup (some another proxy between grafana server and the datasource or some auth setup on the datasource).

Also sharing the datasource setup from grafana could help if you can share it.

**Comment by peay** [comment]
After building with

```diff
diff --git a/pkg/services/rendering/phantomjs.go b/pkg/services/rendering/phantomjs.go
index 35389fe79..5e714353d 100644
--- a/pkg/services/rendering/phantomjs.go
+++ b/pkg/services/rendering/phantomjs.go
@@ -75,7 +75,7 @@ func (rs *RenderingService) renderViaPhantomJS(ctx context.Context, opts Opts) (

        rs.log.Debug("executing Phantomjs", "binPath", binPath, "cmdArgs", cmdArgs, "timezone", timezone)

-       out, err := cmd.Output()
+       out, err := cmd.CombinedOutput()

        if out != nil {
                rs.log.Debug("Phantomjs output", "out", string(out))
```

I can see all the debug logs correctly as I believe was originally intended:

```
2019-07-15T12:07:13 [DEBUG] Phantom - execute: Starting normal mode
2019-07-15T12:07:13 [DEBUG] WebPage - setupFrame \"\"
2019-07-15T12:07:13 [DEBUG] FileSystem - _open: \":/modules/fs.js\" QMap((\"mode\", QVariant(QString, \"r\")))
2019-07-15T12:07:13 [DEBUG] FileSystem - _open: \":/modules/system.js\" QMap((\"mode\", QVariant(QString, \"r\")))
2019-07-15T12:07:13 [DEBUG] FileSystem - _open: \":/modules/webpage.js\" QMap((\"mode\", QVariant(QString, \"r\")))
2019-07-15T12:07:13 [DEBUG] CookieJar - Saved \"renderKey=xxx; domain=.localhost; path=/\"
2019-07-15T12:07:13 [DEBUG] CookieJar - Rejected Cookie \"renderKey=xxx; domain=localhost\"
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 10
2019-07-15T12:07:13 [DEBUG] Network - SSL Error: \"The host name did not match any of the valid hosts for this certificate\"
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 30
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 35
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 40
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 43
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 45
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 47
2019-07-15T12:07:13 [DEBUG] Network - SSL Error: \"The host name did not match any of the valid hosts for this certificate\"
2019-07-15T12:07:13 [DEBUG] WebPage - setupFrame \"\"
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 49
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 54
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 59
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 63
2019-07-15T12:07:13 [DEBUG] WebPage - updateLoadingProgress: 100
Loading a web page: https://localhost:3000/d-solo/6SjRYhIWz/influxdb-read-only-copy?orgId=1&panelId=15&render=1 status: success 60000
2019-07-15T12:07:13 [DEBUG] WebPage - setupFrame \"\"
2019-07-15T12:07:13 [DEBUG] WebPage - evaluateJavaScript \"(function() { return (function () {\
          var panelCount = document.querySelectorAll('plugin-component').length;\
          return window.panelsRendered >= panelCount;\
        })(); })()\"
2019-07-15T12:07:13 [DEBUG] WebPage - evaluateJavaScript result QVariant(bool, false)
2019-07-15T12:07:13 [DEBUG] WebPage - evaluateJavaScript \"(function() { return (function () {\
          var panelCount = document.querySelectorAll('plugin-component').length;\
          return window.panelsRendered >= panelCount;\
        })(); })()\"
...
```

where the last two lines repeat thousands of time until the timeout, so these logs are unfortunately not very informative.

**Comment by peay** [comment]
I have just tried a dummy InfluxDB query, as well as with the default 'Test data: random walk' data (i.e., not even a real data source) and the result is the same (times out, same PhantomJS logs).

**Comment by peay** [comment]
I have also added

```js
    page.onResourceReceived = function(response) {
      console.log('Receive ' + JSON.stringify(response, undefined, 4));
    };
```

to `render.js` (plus a similar handler for `page.onConsoleMessage`). The last log is

```json
{
    "contentType": "application/json",
    "headers": [
        {
            "name": "Cache-Control",
            "value": "no-cache"
        },
        {
            "name": "Content-Type",
            "value": "application/json"
        },
        {
            "name": "Expires",
            "value": "-1"
        },
        {
            "name": "Pragma",
            "value": "no-cache"
        },
        {
            "name": "X-Frame-Options",
            "value": "deny"
        },
        {
            "name": "Date",
            "value": "Mon, 15 Jul 2019 13:55:49 GMT"
        },
        {
            "name": "Transfer-Encoding",
            "value": "chunked"
        }
    ],
    "id": 11,
    "redirectURL": null,
    "stage": "end",
    "status": 200,
    "statusText": "OK",
    "time": "2019-07-15T13:55:49.979Z",
    "url": "https://localhost:3000/api/tsdb/testdata/random-walk?from=1531662947588&intervalMs=43200000&maxDataPoints=500&to=1563198947588"
}
```

The console handler is never called. After that, the numerous `window.panelsRendered >= panelCount` logs appear.

**Comment by aocenas** [comment]
Thanks for digging into this, really appreciated. Yes the output handling is wrong, there is `cmd.Stderr = cmd.Stdout` line but both are nil at that point so it does not do what is intended. When I did your modifications to the logging I get the same output, but get the rendered image. Also as you get `"statusText": "OK"` from the data response it is weird that it does not get/render the data after that. Only thing I could think of right now is if you could try this with http instead of https (`Network - SSL Error: \"The host name did not match any of the valid hosts for this certificate\"` this is only thing I do not see so it is worth a shot, although I would assume the other requests would also fail if that was a problem).

I will also try to figure out how to debug it some more.

**Comment by aocenas** [comment]
Tried with https and getting the same `Network - SSL Error: \"The host name did not match any of the valid hosts for this certificate\"` but still the image is rendered so thats probably not the cause of this.

**Comment by aocenas** [comment]
Could you check response size in the grafana server log? It seems strange that the responses in the PhantomJS output do not have any content length header. You can set 
```
[server]
router_logging = true
```
to see the logs like this:
```
INFO[07-17|11:46:36] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=200 remote_addr=[::1] time_ms=1 size=227 referer="http://localhost:3000/d/7MeksYbmk/alerting-with-testdata?orgId=1&fullscreen&edit&panelId=4"
```

You should see one for the `https://localhost:3000/api/tsdb/testdata/random-walk` request and the `size` is what interests me in this case.

**Comment by aocenas** [comment]
Also while keeping the `page.onConsoleMessage` handler you can add a log [here](https://github.com/grafana/grafana/blob/96ba32d0c87198adc32019b6f27925f9a59c3cde/public/app/core/services/backend_srv.ts#L196) like: `console.log("response: ", JSON.stringify(response.data));` which should also give you actual data that makes it to the panel.

**Comment by peay** [comment]
I see the following requests:

```
t=2019-07-17T12:22:13+0000 lvl=info msg=Rendering logger=rendering path="d-solo/xHm2AjIWz/influxdb-read-only-copy?orgId=1&from=1563344532228&to=1563366132228&panelId=21&width=1000&height=500&tz=Europe%2FParis"
t=2019-07-17T12:22:13+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=https://localhost:3000/d-solo/xHm2AjIWz/influxdb-read-only-copy?orgId=1&from=1563344532228&to=1563366132228&panelId=21&width=1000&height=500&tz=Europe%2FParis&render=1 width=1000 height=500 png=/var/lib/grafana/data/png/bALRTgU1rYu61umjcGsC.png domain=localhost timeout=60 renderKey=eokwx44h30RCQoT8VgXs1VrlU0u7zgz9]"
t=2019-07-17T12:22:13+0000 lvl=info msg="Request Completed" logger=context userId=16 orgId=1 uname= method=GET path=/d-solo/xHm2AjIWz/influxdb-read-only-copy status=200 remote_addr=127.0.0.1 time_ms=2 size=30505 referer=
t=2019-07-17T12:22:14+0000 lvl=info msg="Request Completed" logger=context userId=16 orgId=1 uname= method=GET path=/api/dashboards/uid/xHm2AjIWz status=200 remote_addr=127.0.0.1 time_ms=3 size=22718 referer="https://localhost:3000/d-solo/xHm2AjIWz/influxdb-read-only-copy?orgId=1&from=1563344532228&to=1563366132228&panelId=21&width=1000&height=500&tz=Europe%2FParis&render=1"
t=2019-07-17T12:22:14+0000 lvl=info msg="Request Completed" logger=context userId=16 orgId=1 uname= method=GET path=/api/annotations status=200 remote_addr=127.0.0.1 time_ms=0 size=1164 referer="https://localhost:3000/d-solo/xHm2AjIWz/influxdb-read-only-copy?orgId=1&from=1563344532228&to=1563366132228&panelId=21&width=1000&height=500&tz=Europe%2FParis&render=1"
t=2019-07-17T12:22:14+0000 lvl=info msg="Request Completed" logger=context userId=16 orgId=1 uname= method=GET path=/api/tsdb/testdata/random-walk status=200 remote_addr=127.0.0.1 time_ms=1 size=24813 referer="https://localhost:3000/d-solo/xHm2AjIWz/influxdb-read-only-copy?orgId=1&from=1563344532228&to=1563366132228&panelId=21&width=1000&height=500&tz=Europe%2FParis&render=1"
```

Keeping

```js
    page.onConsoleMessage = function(msg, lineNum, sourceId) {
      console.log('Console: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
    };
```

in `render.js`, I have made the following change:

```diff
diff --git a/public/app/core/services/backend_srv.ts b/public/app/core/services/backend_srv.ts
index 96e7a2cc2..eb329e553 100644
--- a/public/app/core/services/backend_srv.ts
+++ b/public/app/core/services/backend_srv.ts
@@ -192,9 +192,12 @@ export class BackendSrv {
         if (!options.silent) {
           appEvents.emit('ds-request-response', response);
         }
+        console.log("response: ", JSON.stringify(response));
         return response;
       })
       .catch((err: any) => {
+        console.log("error: ", JSON.stringify(err));
+
         if (err.status === this.HTTP_REQUEST_CANCELED) {
           throw { err, cancelled: true };
         }
@@ -235,6 +238,7 @@ export class BackendSrv {
         throw err;
       })
       .finally(() => {
+        console.log("finally");
         // clean up
         if (options.requestId) {
           this.inFlightRequests[options.requestId].shift();
```

I do see those logs when loading a dashboard using my browser, but I do not see anything either:

- in the PhantomJS logs
- when manually browsing to the `d-solo/....` URL.

This makes me suspect that this `BackendSrv` is used when showing dashboards, but it is not used when rendering the panel for alerting or for sharing. Using an XHR breakpoint on `random-walk` at `d-solo/...`,  I can see it break when showing dashboards but not at `d-solo/...` so that I think it really isn't called.

**Comment by aocenas** [comment]
@peay I did not notice you are using the `-- Grafana --` datasource. Can you try it with `TestData DB` datasource? You may need to add it from the datasources configuration.

<img width="991" alt="Screenshot 2019-07-18 at 00 36 16" src="https://user-images.githubusercontent.com/1014802/61416473-18055500-a8f4-11e9-9a1a-1986fceec212.png">


Should not be much difference (both work for me) but this one goes through the backend_srv.ts so you should see the logs with it.

**Comment by peay** [comment]
Ah, you're right. I tested with InfluxDB again, and I see the logs. The data looks fine:

```json
{"data":{"results":[{"statement_id":0,"series":[{"name":"database","tags":{"database":"_internal"},"columns":["time","numMeasurements"],"values":[[1563411720000,12],[1563411780000,12],[1563411840000,12],[1563411900000,12],...]}]}]},"status":200,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/1/query","params":{"db":"_internal","epoch":"ms"},"data":"q=SELECT%20max(%22numMeasurements%22)%20AS%20%22numMeasurements%22%20FROM%20%22database%22%20WHERE%20time%20%3E%3D%201563411732493ms%20and%20time%20%3C%3D%201563433332493ms%20GROUP%20BY%20time(1m)%2C%20%22database%22%20fill(null)","precision":"ms","inspect":{"type":"influxdb"},"headers":{"Content-type":"application/x-www-form-urlencoded","X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"},"retry":0},"statusText":"OK","xhrStatus":"complete"} 
```

The error handler is not called, only the main `then` and `finally`. No other console logs. 

This is very odd - no errors, the data is received correctly but yet the chart does not get rendered.

**This seems to be specific to the graph visualization**: changing to gauge, heatmap or table works fine (i.e., 'share' renders the panel in a couple seconds correctly). This seems to be the case both on the dummy 'random walk' data and on data from InfluxDB.

**Comment by aocenas** [comment]
Hey @peay sorry for the late response, we are stretched a bit thin this summer. Having data but no error message anywhere is weird. I do not have a good answer still, but one thing that could help right now is if you could try using this plugin https://github.com/grafana/grafana-image-renderer . The installation is a bit involved and manual (we are working on making it easier) but if this is an issue with PhantomJS (or seems in your case some combination of PhantomJS + some line graph JS code + some config maybe) this could help.

**Comment by peay** [comment]
Thanks - I will give this a go. I was also planning to redeploy after added more instrumentation to the UI codebase to understand where the ball is being dropped after the data has been received, but I've been moving slow as I am not familiar with the codebase itself. I'll update here once I know more.

**Comment by hugohaggmark** [comment]
Hi @peay, how is this issue coming along?

**Comment by peay** [comment]
I've had to shelf this for a few weeks due to lack of time - I want to get back to it ASAP and try @aocenas's suggestion

**Comment by hugohaggmark** [comment]
Hi @peay, how is this issue coming along?

**Comment by peay** [comment]
I was not able to invest more time to try the external renderer yet. I'll close this issue for now and will update if I manage to make progress on that. Thanks!
