### ISSUE TITLE
Snapshots require login

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#1802]
I'm trying out the snapshot feature of grafana and I'm having troubles with it...

I open up a dashboard -> Share dashboard -> Snapshot sharing -> Set 'Expire' to '1 day' and click 'Local snapshot'.

Grafana return the URL and when I copy/paste it to another browser, I'm welcomed with a login screen and have to login to see the dashboard.

In logs I see:
`grafana-server: 2015/04/17 07:15:23 [I] Completed /dashboard/snapshot/EQzIFlyh75hU66OLKnMMa3RJfn7byJHg 302 Found in 436.752µs`

In browser:
1st request:
```
***Reponse***
Remote Address:1.2.3.4:3000
Request URL:http://hostname.com:3000/dashboard/snapshot/EQzIFlyh75hU66OLKnMMa3RJfn7byJHg
Request Method:GET
Status Code:302 Found

***Response Headers***
Content-Length:29
Content-Type:text/html; charset=utf-8
Date:Fri, 17 Apr 2015 05:15:23 GMT
Location:/login
Set-Cookie:redirect_to=%252Fdashboard%252Fsnapshot%252FEQzIFlyh75hU66OLKnMMa3RJfn7byJHg; Path=/

***Request Headers***
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:redirect_to=%252Fdashboard%252Fsnapshot%252FYl3Q3i0Zc7tUVMWccCh67iEVd8bDpKeS; grafana_sess=b00c8a0b14d91cb5
DNT:1
Host:hostname.com:3000
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36
```

2nd request:
```
***Reponse***
Remote Address:1.2.3.4:3000
Request URL:http://ostname.com:3000/login
Request Method:GET
Status Code:200 OK

***Response Headers***
Content-Length:1954
Content-Type:text/html; charset=UTF-8
Date:Fri, 17 Apr 2015 05:15:23 GMT

***Request Headers***
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:grafana_sess=b00c8a0b14d91cb5; redirect_to=%252Fdashboard%252Fsnapshot%252FEQzIFlyh75hU66OLKnMMa3RJfn7byJHg
DNT:1
Host:ostname.com:3000
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36
```

I have anonymous access disabled, as well as signup.
If I enable anonymous access, then I can see dashboard, but I can also see all other dashboards with all sensitive data.

What is the correct way to enable snapshot sharing? I want grafana to be accessible only to users, but anyone can see snapshots.

Matej

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/1780, if you want a recent build with the fix use rc1, http://grafana.org/download/builds.html   (Will release Grafana 2.0 - stable on monday)

**Comment by matejzero** [comment]
I did a search on issues, but forgot to uncheck 'closed' and missed that one.

I see graph legend in png was also fixed, so 2 bugs that annoyed me are fixed. Nice!
Will wait for RC1 release.

**Comment by spacertechie** [comment]
The issue this duplicates is closed, and refers to this..
