### ISSUE TITLE
Standalone & Reusable panels across dashboards

### ISSUE THREAD

**Issue by billchen** [grafana/grafana#1803]
Hi all,
In Kibana 4 , there is a saved search feature which is very convenient for the user to create a new dashboard based on the saved query, here is the detail:
https://www.timroes.de/2015/02/07/kibana-4-tutorial-part-3-visualize/  (refer to the "Saving and Loading" section)

To introduce the same feature in Grafana, here are some suggestions:
1) add a Saved KPI Graph List page - list all the user-defined KPI Graph here
2) When the user creating a new dashboard, he/she can 
     a) select the saved KPI Graph to add it into current dashboard
     b) create a new KPI Graph just like the current solution

This will be a huge benefit for the customer to customize their own dashboard, they can now just select and reuse the existing KPI Graph rather than define the KPI Graph by their own again and again.

Thanks!

**Comment by torkelo** [comment]
Not sure I understand what you mean. Are you talking about a saved reusable panel (graph)? So you can quickly reuse and share the same panel across dashboards?

**Comment by billchen** [comment]
Yes, exactly :)

**Comment by bhattchaitanya** [comment]
Torkelo, adding to BillChen's request it would also be very intuitive if Panel queries had an auto-suggest and auto-complete feature which would save time for engineers when they are creating dashboards with panels that are already present in another dashboard.

**Comment by biancalana** [comment]
+1

**Comment by baconalot** [comment]
+1

**Comment by cemo** [comment]
+1

**Comment by mtanda** [comment]
+1

**Comment by addshore** [comment]
+1

**Comment by fzakaria** [comment]
I'd love the ability just to save single panel/graph without ownership of a dashboard -- something similar to a pastebin I imagine.

I find myself wanted to explore my dataset of metrics and share some interesting graphs without attaching them to a dashboard quite yet.

+1

**Comment by Exocomp** [comment]
+1

**Comment by scrumpresident** [comment]
+1

**Comment by jgoldschrafe** [comment]
Logging my +1. Would be awesome to be able to compose panels so that, for example, a database server might have general host information available as well as database-specific stuff.

**Comment by danielsd** [comment]
+1

**Comment by bobrik** [comment]
Any chance this can be prioritized? People want to have overview of their service on a single dashboard, but currently they have to manually copy change and graphs into their dashboards. It'd be great if they can still reuse readily available high-quality graphs (probably even supported by other teams) and just plug in their variables.

Think container resources (memory, cpu, network, io), log throughput and Kafka tracking. These parts can easily be used by lots of services.

Going through hundreds of dashboards and changing them all in a very unique way when you tweaked basic metric (container cpu for example) is very time consuming.

**Comment by scraly** [comment]
+1

**Comment by celiovasconcelos** [comment]
+1

**Comment by mbrgm** [comment]
For everyone +1-ing: Please simply use thumbs up on the OP instead of creating a comment, which justs bloats the discussion and makes it hard to read. Thank you! :-)

**Comment by joca-bt** [comment]
+1

**Comment by shalstea** [comment]
Also want to share, Text panels!

**Comment by mtanda** [comment]
I hope https://github.com/grafana/grafana/pull/15620 merge to v6.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by tfylling** [comment]
I would very much like this as well, but also for entire [repeated] rows where both containing panels and layout is mirrored. I maintain a growing number of large full overview dashboards for serveral server classes. Here many sections, such as system stats , disk stats, interface stats, ipmi stats etc. should look the same while there are extra rows for stuff like postgres, apache, zfs, pf, whatever for the individual server classes. Currently doing any sort of maintainance on this is an absolute nightmare and can take hours. So either some sort of inheritance/templating/composite dashboards or some way of hiding panels and rows based on variables or empty data sets would be of tremendous help and vastly improve the speed and ease of creating new dashboards.

**Comment by jessover9000** [comment]
Hi everyone who is interested in this feature, super happy to see your feedback. We are tackling this feature, and I'm the UX designer working on it. In order to make the feature the best it can be, would any of you be willing to talk about your experience in a 30-minute interview? If yes, you can schedule a time slot here: https://calendly.com/jessdesigns/grafana-your-experience Thanks in advance 🙏

**Comment by liorgorb** [comment]
@jessover9000 could you please update about the current status?

**Comment by natellium** [comment]
Hey @liorgorb sorry for the radio silence. We released [Library Panels](https://grafana.com/docs/grafana/latest/panels/library-panels/) a while ago and updating this issue prob fell through the cracks. There are some limitations at the moment re. template variables as they're not well supported. We hope to tackle this eventually but we don't have an ETA. Hope this meets your needs!  

Will now close this issue.
