### ISSUE TITLE
Packages: versioning and releases

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#18038]
Issue to track progress and ideas about packages releases

### Alpha/Beta/Stable releases
In `Prepare release branch` part of our release workflow
1. Update lerna.json version to be the version being released `lerna version <version> --force-publish`. `--forcePublish`  will make all packages to be versioned, no matter whether or not any changes were introduced to any of the packages

When the release is tagged following things need to happen on Circle
- [ ] run `yarn packages:build` - we assume lerna.json version was updated (1 above), so package.json should be now in sync with grafana
- [ ] run `yarn packages:publish`

Questions
1. What should be the version of packages _between_ Grafana releases? Grafana's package.json is updated after release to be `<NEXT_VERSION>-pre`. Should we also do that in lerna.json file? The `-pre`suffix seems not to be consistent with semver, maybe we should start using `-alpha` instead?
2. Should alpha/beta releases publish packages under `next` tag on npm?

### Nightly releases
Runs on a nightly basis using Circle scheduling (https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow)
Workflow:
1. `lerna ${VERSION_FROM_LERNA_JSON}-${CIRCLE_JOB_ID} --no-git-tag-version --no-push --force-publish -y` - this will update package.json files for all packages no ignoring lack of changes in packages. Also, the version update in lerna.json will not be checked in to the repo. 
2. `npm run test`
3. `npm run packages:build` - prepares dist for all packages
4. `lerna publish from-package --contents dist --dist-tag next -y`

### Manual releases
In some cases we probably want to release `next` tag to npm without waiting for nightly build to be released. For this to be solved I see couple of paths:
1. npm scripts that will run workflow similar to Nightly build. This script would be performed manually from local environment. This introduces inconsistency though, as we can use Circle's job id. We could use commit sha as version mark ${VERSION_FROM_LERNA_JSON}-${COMMIT_SHA}
2. Manually triggering the nightly build workflow for a given commit directly from CircleCi
3. Introduce a label in github that would trigger a CircleCI build when added to PR

**Comment by ryantxu** [comment]
I think all releases should still have `-alpha` suffix.  The API is getting better, but still a lot we want to move/improve before committing to it.

After we remove `-alpha` from everything, we should keep it for nightly and manual releases

**Comment by dprokop** [comment]
Note: If we decide to perform nightly on `master` only, then I think we can use git SHA isntead of Circle's job ID.

**Comment by ryantxu** [comment]
Rather than nightly release, we could check if anything under `packages` has changed after each commit and then release.  That seems like it won't be too much unnecessary stuff and is more consistent/predictable than nightly+manual

**Comment by dprokop** [comment]
Short update on this one, as the issue description is not accurate ATM, but rather is a brain dump of possible solutions.

So, starting with de705229ba3257e04d9590750e80fd50a6664192 every commit to master is a subject of a potential packages release. **If changes in `packages` directory between two consecutive commits are detected**(https://github.com/grafana/grafana/blob/master/scripts/circle-release-next-packages.sh#L23), we will release **all** packages to npm under a version that follows convention:

`<lerna.json version>-<COMMIT_SHA>`

Those packages will be released under `next` tag.

**Comment by dprokop** [comment]
@torkelo @ryantxu I went through Github's Package Registry(https://github.com/features/package-registry) docs to see if we can use it for publishing the packages which are now published to npm via `next` tag, as described in previous comment. The thing I don't like about current workflow is that we create loads of versions on npm, which I think we should use for "stable" releases only. And by "stable" I mean releases that are associated with Grafana release. 

All is pretty straightforward there and wouldn't change the workflow significantly. Two major things worth noticing are: 
1. Publishing to Github Package Registry will create a tag and a GH release associated with the packages release (vide https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#publishing-multiple-packages-to-the-same-github-repository). This means that we would probably need to update our CircleCI config to ignore those tags, as they will trigger `release` workflow. Also, I'm not sure we want the GH releases to be created for every publish. Haven't found anything in the docs, so I'm awaiting response from GH support about that.
2. When testing `next` releases against Grafana plugins, one would have to make sure she uses Github as registry for packages scoped under @grafana/*. It's a matter of using `@grafana:registry=https://npm.pkg.github.com/` in `.npmrc` (https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#installing-a-package)

Any thoughts?

**Comment by dprokop** [comment]
fixed :)
