### ISSUE TITLE
Inconsistent build packages due to the use of ubuntu:latest base image

### ISSUE THREAD

**Issue by hassanfarid** [grafana/grafana#18046]
**What happened**:
In the latest beta release, we have made changes to docker image files to take ubuntu:latest ad base image.
This was initiated from #14182 and changes are merged using #17066 .

**What will happen?**

I think this can lead to inconsistent resultant image based on when grafana docker image is built. If in the future, ubuntu:latest moves to a newer version, this will change environment for builds.

**What should happen?**

It is general industry standard to use specific version label instead of label, so that the artifacts of build process are always predictable.

I suggest that we replace `ubuntu:latest` with `ubuntu:18.04` at places that are effected by #17066 .

**Environment**:
- Grafana version: v6.3.0-beta1 (2019-07-10)

**Comment by xlson** [comment]
Yes, I agree. We will make that change for the stable release.

**Comment by hassanfarid** [comment]
Can I pick this up?

**Comment by marefr** [comment]
@hassanfarid sure, that would be helpful.

**Comment by torkelo** [comment]
I thought we had a PR that fixed this? But maybe confused it with another

**Comment by hassanfarid** [comment]
@torkelo - here goes the PR : https://github.com/grafana/grafana/pull/18224
