### ISSUE TITLE
Migrate backend_srv from angular to fetch

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18049]
HTTP request to the backend currently all go though the angular $http client.  We should move that to something based on [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

We could also consider a client like [axios](https://github.com/axios/axios), but I don't see any big advantage of using their abstraction since we will already abstract the details behind the [BackendSrv](https://github.com/grafana/grafana/blob/master/packages/grafana-runtime/src/services/backendSrv.ts) interface

**Comment by torkelo** [comment]
Yes!

**Comment by hugohaggmark** [comment]
I'm gonna stick my neck out here but wouldn't 'RxJs' also simplify a lot of the cancelation logic here? But maybe that's another PR.
