### ISSUE TITLE
Azure Monitor: Refactor to use common QueryField component instead of custom one

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#18057]
Currently the azure monitor datasource makes use of `public/app/plugins/datasource/grafana-azure-monitor-datasource/editor/query_field.tsx` rather than `public/app/features/explore/QueryField.tsx`. It would be nice to refactor so that the previous file isn't needed anymore.

**Comment by joshhunt** [comment]
I don't think we use this any more, so it should be cleaned up and deleted
