### ISSUE TITLE
Improve provisioned datasources edit page experience

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18050]
Currently when you add a provisioned datasource it adds a note at the top of the edit page:
![image](https://user-images.githubusercontent.com/705951/60996120-dfb8b200-a308-11e9-96bb-63e8ce5eccc4.png)

but you are still able to edit and test things.  I was messing with a datasource for a while before I understood that it the results were not saved with the normal 'save and test' button.

There are many ways we could improve this, I don't know the best :)

Maybe:
* disable all form fields?  (but plugins make them... so maybe complicated?)
* add a transparent overlay that captures all clicks and adds a warning tooltip?
* add more text at the bottom 'test' button:
![image](https://user-images.githubusercontent.com/705951/60996402-5f468100-a309-11e9-8be3-cac406fd93d3.png)

Rather than [test] [delete (disabled)] [back]

We could have:
[Test Provisioned Datasource] [back]

and then when you click test, add the same warning message about how you save changes, but put it below the buttons?

**Comment by torkelo** [comment]
There a lot of complicated parts to this

* Messy / tricky to disable all input fields as some are owned by plugins
* No way to Test settings without saving first (requires a big refactoring to accomplish this). Current reason for this is that the data proxy and backend tsdb code all require a data source id (and reading current settings from db). 
* The best way for Save button for provisioned data source would be to show the yaml config

**Comment by torkelo** [comment]
Also not very happy with ux around the warning (the provisioned warning box)
