### ISSUE TITLE
Elasticsearch datasource tests fail on master

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18054]
I think this has something to do with timezones....  Running at 6pm PST I get:

```
Running "exec:jest" (exec) task
>> FAIL public/app/plugins/datasource/elasticsearch/specs/datasource.test.ts
>> ● ElasticDatasource › When testing datasource with index pattern › should translate index pattern to current day
>>
>>     expect(received).toBe(expected) // Object.is equality
>>
>>     Expected: "http://es.com/asd-2019.07.11/_mapping"
>>     Received: "http://es.com/asd-2019.07.10/_mapping"
>>
>>       79 |
>>       80 |       const today = toUtc().format('YYYY.MM.DD');
>>     > 81 |       expect(requestOptions.url).toBe('http://es.com/asd-' + today + '/_mapping');
>>          |                                  ^
>>       82 |     });
>>       83 |   });
>>       84 |
>>
>>       at Object.<anonymous> (public/app/plugins/datasource/elasticsearch/specs/datasource.test.ts:81:34)
>> PASS public/app/features/plugins/plugin_loader.test.ts
```

**Comment by dehrax** [comment]
What was the time of day when this was run?

**Comment by dehrax** [comment]
Can't seem to reproduce. Changed timezone to UTC+12 (which is now in tomorrow), yet the test doesn't fail.

**Comment by ryantxu** [comment]
Reproduced in circleci:
https://circleci.com/gh/grafana/grafana/124586
![image](https://user-images.githubusercontent.com/705951/61268137-71804f00-a74f-11e9-9cc9-f45c194af1f6.png)

**Comment by dprokop** [comment]
@dehrax can we just mock today's date in this test?

**Comment by ryantxu** [comment]
This is still happening every day....

**Comment by marefr** [comment]
@ryantxu think it's related to https://github.com/grafana/grafana/blob/e5e7bd315357d7b6ea016e1098a1acbdc3b35d66/public/app/plugins/datasource/elasticsearch/datasource.ts#L86

**Comment by dprokop** [comment]
@ryantxu are you still experiencing this?
