### ISSUE TITLE
InfluxDB ad-hoc filters do not apply interpolation on value field

### ISSUE THREAD

**Issue by kvc-code** [grafana/grafana#18051]
**What happened**:
I have a Query variable filled from a PostgreSQL data source which I would like to reference from an ad-hoc filter and thereby inject into all InfluxDB queries on the dash. This works with ElasticSearch and, from quick code inspection, I believe it works with Prometheus. Unfortunately variable interpolation is not applied to InfluxDB ad-hoc filters making this impossible.

For example:
Given an ad-hoc filter such as `my_id = $selected_id` where `$selected_id` currently contains the value `foo` Grafana generates an InfluxDB query with a `where` clause of the form:
`SELECT ... WHERE ... AND "my_id" = '$selected_id' ...`

**What you expected to happen**:
Query variable value used as the ad-hoc filter value, resulting in generated query:
`SELECT ... WHERE ... AND "my_id" = 'foo' ...`

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with:
- a variable named `selected_id` whose value can be set to `foo`
- an ad-hoc filter
- a panel with a query against an InfluxDB data source

Populate the ad-hoc filter's value with the string `$selected_id`

Edit the panel and open the Query Inspector to confirm that variable interpolation has not been applied and `'$selected_id'` has been used as the filter value.

**Anything else we need to know?**:
It appears that the InfluxDB data-source code is preventing interpolation. Other data-source plugins that support ad-hoc filters allow it. The following change seems to resolve this difference:
```
oss-projects/grafana ((v6.2.5) *) $ git diff
diff --git a/public/app/plugins/datasource/influxdb/influx_query.ts b/public/app/plugins/datasource/influxdb/influx_query.ts
index 3ee9d703c..84bd91caa 100644
--- a/public/app/plugins/datasource/influxdb/influx_query.ts
+++ b/public/app/plugins/datasource/influxdb/influx_query.ts
@@ -265,7 +265,7 @@ export default class InfluxQuery {
 
   renderAdhocFilters(filters) {
     const conditions = _.map(filters, (tag, index) => {
-      return this.renderTagCondition(tag, index, false);
+      return this.renderTagCondition(tag, index, true);
     });
     return conditions.join(' ');
   }
```

**Environment**:
- Grafana version: v6.2.5 (also fails on master as of last week)
- Data source type & version: InfluxDB 1.7
- OS Grafana is installed on: Linux
- User OS & Browser: Mac OS 10.14.5 / Safari 12.1.1
- Grafana plugins: influxdb data source
- Others:

**Comment by dprokop** [comment]
@kvc-code would you mind opening a PR with the change proposed above? Thanks!
