### ISSUE TITLE
Table Panel won't grow in heigth to display all rows when scroll is disabled

### ISSUE THREAD

**Issue by abmaymic** [grafana/grafana#18065]
**What happened**:
We have several dashboards with Table Panels. For these panels the scroll switch is turned off. 
The panels won't grow in heigth, when more rows are available than would fit into the initial size of the panel. Instead, content is cut on the panels boundary.

**What you expected to happen**:
According to documentation https://grafana.com/docs/reference/table_panel/ the panel should grow in size to have all rows displayed, when scroll is disabled. This worked in Grafana 5, but not in Grafana 6.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a Table panel to display the averages for several graphite metrics. Have a template variable control the number of lines in the panel - e.g. by using the highestCurrent()-function.

**Anything else we need to know?**:

**Environment**:
- Grafana version: tested with 6.2.2, 6.2.5 and 6.3.0-beta1
- Data source type & version: Graphite 1.1.5
- OS Grafana is installed on: Docker on Ubuntu 18.04 LTS
- User OS & Browser: Ubuntu 16.04 & Chromium, Windows 10 & Firefox
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
We can't support that, this is remnant from Grafana prior to v5. So we should just default to scroll enabled.

**Comment by torkelo** [comment]
created issue to remove scroll option, https://github.com/grafana/grafana/issues/18066
