### ISSUE TITLE
AzureMonitor: Support retrieval of resource names by namespace

### ISSUE THREAD

**Issue by chelnak** [grafana/grafana#18063]
**What would you like to be added**:
Azure monitor queries should support the retrieval of resource names by namespace. Currently ResourceNames() supports the following parameters:

* subscriptionId, resourceGroupName, metricName
* resourceGroupName, metricName

The resource manager API supports queries of resources at a subscription level using the filter parameter of the API e.g.

```
https://management.azure.com/subscriptions/xxxxxx/resources?$filter=resourceType EQ 'Microsoft.Insights/components'&api-version=2018-05-01
```

Allowing us to use a query that is formatted like the example below:

```
ResourceNames(Microsoft.Insights/components)
```

**Why is this needed**:
This feature would allow users of the Azure Monitor data source to query resources of a similar type across multiple resource groups in a subscription.

An example of this would be to look at failed requests across multiple app insights instances.

**Comment by kylebrandt** [comment]
Had done this with Bosun's Azure support at https://github.com/bosun-monitor/bosun/blob/exprCleanup/cmd/bosun/expr/tsdbs/azure/azure.go#L383 , just slurped all the objects into a cache.

Since each query from a filtered list ends up being an individual HTTP request in the Azure Monitor case, need to watch rate limiting and only query what you need (so filter before query).

**Comment by chelnak** [comment]
Good to know.

We actually talked about adding a name parameter to the PR to reduce the amount of results that are returned..

Will have a look and see if we can add any improvements

**Comment by kylebrandt** [comment]
@chelnak Oh, I'm sorry - I didn't see that there was a PR attached to this, so what just leaving a general comment on the idea of multi-query.

**Comment by yesoreyeram** [comment]
I have submitted https://github.com/grafana/grafana/pull/18629, to use [Azure Resource Graph](https://azure.microsoft.com/en-gb/features/resource-graph/) [API](https://docs.microsoft.com/en-us/rest/api/azureresourcegraph/resources/resources). This will help to pull any resource properties with custom query.

**Example**: Query `ResourceGraph(where  type == "microsoft.cache/redis" | project name)`  will return all the redis caches across all the subscriptions. You can also add more filters based on the need.

 I hope this will solve the usecases like this.

**Comment by chelnak** [comment]
Amazing! This looks great. Can’t wait to give it a spin.

**Comment by joshhunt** [comment]
I'm going to close this issue in favor of improvements to template variables we're discussing in https://github.com/grafana/grafana/discussions/39970. Thanks for raising this!
