### ISSUE TITLE
Issue with grafana email alert

### ISSUE THREAD

**Issue by shivcena** [grafana/grafana#18078]
> What Grafana version are you using?
    6.2.4

> What datasource are you using?
    prometheus

> What OS are you running grafana on?
    linux

> What did you do?
    Trying to send test mail to my gmail account, enabled smtp for gmail account(login gmail 
    account->settings->Forwarding and POP/IMAP->IMAP enabled)
    Also configured the smtp settings in grafana default.ini file

   [smtp]
   enabled =true
   host =smtp.gmail.com:465
   user =xx@gmail.com
    If the password contains  or ; you have to wrap it with triple quotes. Ex """password;"""
   password =xx!
  skip_verify =true
  from_address =xx@gmail.com
  from_name =Grafana

> What was the expected result?
    Receive grafana test mail to mentioned gmail account

> What happened instead?
    Error thown like lvl=eror msg="failed to send notification" logger=alerting.notifier uid= 
    error="read tcp X.X.X.X:12701->74.125.195.108:465: read: connection timed out"

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

For reference, here's my gmail config which works as expected:

**Please note if you have Google Mail 2FA enabled you need to generate a new “App Password” in Google Mail and then enter that as PASSWORD, not your usual gmail password…**

```ini
[smtp]
enabled = true
host = smtp.gmail.com:587
user = <user>@gmail.com
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password = <pwd>
cert_file =
key_file =
skip_verify = false
from_address = <user>@gmail.com
from_name = Grafana
ehlo_identity =
```
