### ISSUE TITLE
Docs cannot be rebuilt: grafana/website repository missing

### ISSUE THREAD

**Issue by jdexposito** [grafana/grafana#18076]
**What happened**:

I am trying to build Grafana from scratch, including docs.

The docs README.md says:

_Prepare the Docker Image:

Git clone grafana/website repo.[..]_

But the grafana/website repository either does not exist or is not public.

**What you expected to happen**:

grafana/website to be available

**How to reproduce it (as minimally and precisely as possible)**:

Try to visit https://github.com/grafana/website in a browser

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@jdexposito grafana/website is a private repo

**Comment by torkelo** [comment]
To help contribute / improve docs I would assume. Think we made a mistake making it private before the new docs site is ready.

**Comment by hackery** [comment]
> To help contribute / improve docs I would assume.

Well yes. It's one of the entry points to contribution headlined at the [Contributing to Grafana](https://grafana.com/grafana/contribute) page.

![image](https://user-images.githubusercontent.com/308470/65227727-12c5b180-dac1-11e9-998e-b0f22636e324.png)
