### ISSUE TITLE
Graph no data display when using function like maxSeries

### ISSUE THREAD

**Issue by litao-buptsse** [grafana/grafana#1807]
I am using grafana to display online servers metrics. I met a problem when aggregating data like maxSeries. 

For example, I have 5 servers, and one server crash at 12:00 am. 
1. If the time range before 12:00 am, have 5 servers, maxSeries is OK to display;
2. If the time range after 12:00 am, have 4 servers, maxSeries is OK to display too;
3. But If the time range across 12:00 am:
        a. before 12:00 am, maxSeries is OK to display;
        b. after 12:00 am, maxSeries can't display any data.

Anything I can do with the case3? 
I don't know grafana inner implements. I think if before 12:00 am maxSeries apply for the 5 servers, and after 12:00 am maxSeries apply for the 4 servers, it would be nice for me.

**Comment by torkelo** [comment]
I guess you are using InfluxDB?

**Comment by torkelo** [comment]
or are you talking about the maxSeries graphite function? In that case I think you need to open an issue with graphite-web project

**Comment by litao-buptsse** [comment]
@torkelo I am using Graphite as the datasource.

**Comment by torkelo** [comment]
the maxSeries is a graphite function.

**Comment by litao-buptsse** [comment]
OK, I got it.
