### ISSUE TITLE
Regression in CloudWatch data source support for templating

### ISSUE THREAD

**Issue by johnewing1** [grafana/grafana#18087]
There has been a regression introduced into the CloudWatch data source in version 6 which breaks graphs which use the `all` option in a variable.

**What happened**:

Using a templated variable with the CloudWatch data source stopped work after upgrading to version 6.x

Selecting `all` causes the dashboard to fail with the following error

 "InvalidParameterValue: The parameter Dimensions.member.1.Value must be shorter than 257 characters. status code: 400"

**What you expected to happen**:

The dashboard to render correctly as it did it version 5.x

**How to reproduce it (as minimally and precisely as possible)**:

Create a variable which gets a list of ec2 instance ids by querying cloudwatch
```
ec2_instance_attribute($region, InstanceId, {"tag:aws:autoscaling:groupName": ["MY_ASG"]})
``` 
Check the `include all option` check box.

Create a CloudWatch query which uses this variable
```
      "targets": [
        {
          "alias": "{{InstanceId}}",
          "dimensions": {
            "InstanceId": "$instanceid"
          },
          "expression": "",
          "highResolution": false,
          "id": "",
          "metricName": "CPUUtilization",
          "namespace": "AWS/EC2",
          "period": "",
          "refId": "A",
          "region": "$region",
          "returnData": false,
          "statistics": [
            "Sum"
          ]
        }
      ],

```

Select the `all` option from the variable drop down.

**Anything else we need to know?**:

Looking at request that generated in v5 it looks like this
```
{
    "from": "1562641907672",
    "to": "1562663507673",
    "queries": [
        {
            "refId": "<redacted>",
            "intervalMs": 30000,
            "maxDataPoints": 627,
            "datasourceId": 66,
            "type": "timeSeriesQuery",
            "alias": "",
            "dimensions": {
                "InstanceId": "i-<redacted>"
            },
            "expression": "",
            "highResolution": false,
            "id": "",
            "metricName": "CPUUtilization",
            "namespace": "AWS/EC2",
            "period": "300",
            "region": "eu-west-1",
            "returnData": true,
            "statistics": [
                "Average"
            ]
        },
        {
            "refId": "<redacted>",
            "intervalMs": 30000,
            "maxDataPoints": 627,
            "datasourceId": 66,
            "type": "timeSeriesQuery",
            "alias": "",
            "dimensions": {
                "InstanceId": "i-<redacted>"
            },
            "expression": "",
            "highResolution": false,
            "id": "",
            "metricName": "CPUUtilization",
            "namespace": "AWS/EC2",
            "period": "300",
            "region": "eu-west-1",
            "returnData": true,
            "statistics": [
                "Average"
            ]
        },
.....
]
```

In v6 it looks like this

```
{
    "from": "1562641767334",
    "to": "1562663367334",
    "queries": [
        {
            "refId": "A",
            "intervalMs": 20000,
            "maxDataPoints": 894,
            "datasourceId": 1,
            "type": "timeSeriesQuery",
            "dimensions": {
                "InstanceId": "{i-<redacted>,i-<redacted>,........}"
            },
            "expression": "",
            "highResolution": false,
            "id": "",
            "metricName": "CPUUtilization",
            "namespace": "AWS/EC2",
            "period": "300",
            "region": "eu-west-1",
            "returnData": true,
            "statistics": [
                "Average"
            ],
            "alias": ""
        }
    ]
}
```

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @johnewing1 and thanks for reporting this. We'll look into this more.

**Comment by marefr** [comment]
@mtanda any input here. I was under the impression that CloudWatch datasource doesn't work with multiple template variable values due to limitation in cloudwatch api?

**Comment by torkelo** [comment]
There was some limited support to expand multi-valued variables (which I disliked as it was using a hacky method to duplicate whole queries instead of interpolating strings).

**Comment by mtanda** [comment]
@johnewing1 If you don't set `Multi-value` at templating, please set.
I tested v6.3.3, it seems to work with `Multi-value` set. But, if I unset `Multi-value`, same issue is happen.

![image](https://user-images.githubusercontent.com/224552/63314370-5a321400-c342-11e9-9cd4-24a5ffdf3a22.png)

**Comment by marefr** [comment]
So seems to be a bug related to when Multi-value is disabled?

**Comment by mtanda** [comment]
`Multi-value` = `off` && `Include All option` = `on` is valid combination?

**Comment by torkelo** [comment]
Looks a bit strange, in first versions of Grafana all value was always just a value (like wildcard)

**Comment by johnewing1** [comment]
@mtanda Switching on the multi value fixes it in 6.x for me

**Comment by torkelo** [comment]
We can support this use case when Cloudwatch supports multi-value support for the region attribute. The way it worked before is not something we can do anymore. Templating can only interpolate variables to strings not cause whole json object blocks to duplicate.

**Comment by sunker** [comment]
Multi value support for region is not something that is in the road map for AWS at the moment, hence this cannot be fixed at our end.
