### ISSUE TITLE
Grafana 6.25 stamp the http: superfluous response.WriteHeader error randomly

### ISSUE THREAD

**Issue by akilaw** [grafana/grafana#18082]
**What happened**:
When grafana 6.2.5 started with SSL enabled it sometimes gives following error randomly.
2019/07/04 23:44:54 http: superfluous response.WriteHeader call from github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*responseWriter).WriteHeader (response_writer.go:59)

**What you expected to happen**:
Grafana should not give any errors

**How to reproduce it (as minimally and precisely as possible)**:
Start grafana 6.2.5 with SSL enabled open a dashboard from a web browser. The error should appear randomly after that.

**Anything else we need to know?**:
There is a similar issue in the caddyserver https://github.com/caddyserver/caddy/issues/2537

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: PostgreSQL data source from Grafana
- OS Grafana is installed on:
USE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3

- User OS & Browser: Ubuntu 18.04 and Chrome Version 75.0.3770.100 (64 Bit)
- Grafana plugins: No plugins
- Others:

**Comment by kylebrandt** [comment]
I seem to be having trouble reproducing this. 

I checkout 6.2.5 with the devenv postgres block, enabled SSL, and then tried to load up multiple instances of our `Datasource tests - Postgres` dashboard and keep refreshing.

It seems to be that here are multiple calls to `WriteHeader` somewhere in a request, but I'm not seeing it anywhere obvious via grep, and can't seem to trigger it.

Are they any other options you might have enabled, or any ideas on a more specific situation that might be triggering it?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
