### ISSUE TITLE
Add a metric for notification failed to be sent

### ISSUE THREAD

**Issue by koorgoo** [grafana/grafana#18086]
There is the `grafana_alerting_notification_sent_total` metric for amount of sent notifications using the `type` label to specify.

The code says this metric counts all notifications including ones with errors:
https://github.com/grafana/grafana/blob/d8736a2/pkg/services/alerting/notifier.go#L59

**What would you like to be added**:
I suggest to add a new metric for amount of notifications failed to be sent.

The metric may be called `grafana_alerting_notification_failed_total`.

I insist on a new metric, because adding a label to the existing metric to specify success of sending will break existing rules already run in production.

**Why is this needed**:
This metric will allow to expose problems with channels. 

Currently, there are log records containing `failed to send notification`, but extra work is required to build an alert on it.

**Comment by koorgoo** [comment]
Let me know whether the idea looks good. I would like to implement it.

**Comment by torkelo** [comment]
your PR is merged!

**Comment by koorgoo** [comment]
Thank you, @torkelo !
