### ISSUE TITLE
Sharing a full screen link on Firefox 60.8.0esr squashes graph

### ISSUE THREAD

**Issue by phil-or** [grafana/grafana#18080]
**What happened**:
Same problem as here  #16296
We also use Firefox ESR (60.8.0esr) in our environment and still have this problem with Grafana 6.2.5

**Environment**:
- Grafana version: 6.2.5
- OS Grafana is installed on: Centos7
- User OS & Browser: Firefox 60.8.0esr

**Comment by dprokop** [comment]
@phil-or can you please provide us with console output? Thanks!

**Comment by phil-or** [comment]
Sure, here's the console output:
![image](https://user-images.githubusercontent.com/36534023/61432780-ba8ff900-a931-11e9-92d4-7be7b0268402.png)

**Comment by serresident** [comment]
Good day, a similar problem occurs on chrome / firefox browsers of all versions that were compatible with windows xp

**Comment by hugohaggmark** [comment]
Can't repro this with latest FireFox version on MacOS or Windows 10 so I will close this issue.
MacOS:
![image](https://user-images.githubusercontent.com/562238/84367272-49ee6c80-abd4-11ea-8048-81ccf582f21a.png)
Windows:
![image](https://user-images.githubusercontent.com/562238/84367893-25df5b00-abd5-11ea-869b-de09768aec9b.png)
