### ISSUE TITLE
Switch docker base image to buster or alpine

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#18084]
As soon as PhantomJS have been removed from Grafana code base, we should be able to switch the base image to buster or alpine or something else. That would remove vulnerabilities found in our current docker image.

**Comment by DanCech** [comment]
buster has a large number of known vulnerabilities, we're likely to be better off with alpine.

**Comment by Sytten** [comment]
This is a big breaking change for a lot of people who build on top of your images. I wish the grafana team had advertise this change more... Many tools are missing in alpine or behave differently, not to mention the use of musl which can lead to strange runtime bugs.

**Comment by marefr** [comment]
@Sytten thanks for the feedback, but we added a breaking change notice in the [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#docker) - something you always should read before upgrading. We'll see what happens moving forward, but we may consider adding one additional image type with a different base image than alpine. What tools are missing in alpine for example?

**Comment by Sytten** [comment]
Ha I missed it... So many changelogs its hard to keep track.
I personally avoid alpine as the plague since they use a lot of custom stuff. I hit a problem with `xargs` which is compiled without the `-d` parameter in alpine vs all other distributions. I also used curl (that was added in the previous image manually but removed in the switch), but that's fine I did a multistage build instead.

**Comment by J0WI** [comment]
> I hit a problem with `xargs` which is compiled without the `-d` parameter in alpine vs all other distributions.

ot: @Sytten I think you just missed the GNU `findutils` package. The `-d` parameter is not part of the POSIX standard and therefore not supported in the `busybox` implementation of `xargs`.

**Comment by marefr** [comment]
Thanks for the feedback. We've listen and decided to build and publish an additional Ubuntu-based image, see #20178.
