### ISSUE TITLE
Bad graphite queries on --Mixed-- Datasource with series as parameters.

### ISSUE THREAD

**Issue by hamelg** [grafana/grafana#18088]
On this simple graph panel :

```
Query: -- Mixed --
Series A [Datasource graphite 1] : my.series.aa.value1
Series B [Datasource graphite 1] : asPercent(my.series.bb.value1, #A)
```

If I hide Series A ("hide": true) , Grafana doesn't handle the parameter #A and the query fails.

Here is how grafana sends the query to graphite.

When Series A is not hidden ("hide": false), the query is correct. Graphite returns the data with HTTP 200.

```
target	[…]
0	my.series.aa.value1
1	asPercent(my.series.bb.value1, my.series.aa.value1)
from	-6h
until	now
format	json
maxDataPoints	960
```

When Series A is hidden ("hide": true), the query fails. Graphite doesn't understand the query and responds with HTTP 500. .

```
target	asPercent(my.series.bb.value1, #A)
from	-6h
until	now
format	json
maxDataPoints	960
```

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: --Mixed-- + graphite
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 / Firefox 67
- Grafana plugins: None
- Others:

**Comment by hamelg** [comment]
I would like to show you the issue on a test dashboard at play.grafana.org, but unfortunately I have not the permission to save or create a dashboard. I've found a near similar issue https://github.com/grafana/grafana/issues/12977, so it seems it is not fully fixed.

**Comment by briangann** [comment]
if you have a panel.json to share that will work also. the behavior of "hide" differs between datasources, but this sounds like a bug.

**Comment by hamelg** [comment]
Here are the json files : 
\*ok* => it works
\*ko* => the bug happens

[panel-ko.txt](https://github.com/grafana/grafana/files/3405756/panel-ko.txt)
[panel-ok.txt](https://github.com/grafana/grafana/files/3405757/panel-ok.txt)
[query-ko.txt](https://github.com/grafana/grafana/files/3405758/query-ko.txt)
[query-ok.txt](https://github.com/grafana/grafana/files/3405759/query-ok.txt)

**Comment by hamelg** [comment]
Bug is still present in 6.3.3

**Comment by hamelg** [comment]
This issue was introduced in v6.2.0, v6.1.6 works fine. I suspect this PR https://github.com/grafana/grafana/pull/16409. Please, attach the tags type/bug and datasource/Mixed on my issue.

**Comment by hamelg** [comment]
duplicate of https://github.com/grafana/grafana/issues/18801
