### ISSUE TITLE
Graphs sometimes mis-color non-continuous lines and points when there are multiple series and you have stacking on

### ISSUE THREAD

**Issue by siebenmann** [grafana/grafana#18091]
**What happened**:

Some of our graphs involve non-continuous data (where a line/point/etc is only present some of the time). We have a persistent long-term issue where every so often, lines and points will be colored incorrectly when there are multiple series and they aren't continuous. The pattern we see is that later series incorrectly use the color for an earlier series. Toggling off the display of the earlier series will reveal the correct color for later series.

After some experimentation, this appears to only happen if we have stacking on for a particular graph; toggling stacking off and on will make the problem disappear and reappear. Also, if we turn on draw mode 'Bars', the bars are rendered in the correct color (although any points and lines aren't). Unfortunately we need stacking for this particular situation.

**What you expected to happen**:

Each series is always colored in its legend color.

**How to reproduce it (as minimally and precisely as possible)**:

This doesn't consistently happen, but when it happens for a particular graph over a particular time range it is repeatable; returning to the graph at that time range will always show the incorrect colors (and it happens regardless of the window size).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5, but this has been an issue for many versions
- Data source type & version: Prometheus 2.11.1, but this has been an issue for many versions of Prometheus
- OS Grafana is installed on: Ubuntu 18.04 LTS
- User OS & Browser: currently Firefox 68 on Fedora Linux, but this also happens in Chrome on Fedora and in prior versions of Firefox.
- Grafana plugins: flant-statusmap-panel @ 0.1.1, natel-discrete-panel @ 0.0.9, neither being used by this graph
- Others: The graph settings we use on graphs that have this happen to them are draw modes Lines & Points, line width 1, point radius 1 (usually), stacking on (required to make the bug manifest), legend shown. A particular query involved is ``count(our_metric == 0) by (host)``, with the display legend being ``{{host}}``.

I've attached a typical screenshot of this happening, where you can see a very minimal example; the second set of lines and points should be green (for ``ntp2.torix.ca``), not yellow (for ``time.nrc.ca``).

![Screenshot_2019-07-12 CSLab Global view - Grafana](https://user-images.githubusercontent.com/865382/61141318-4d94e300-a49b-11e9-8ded-201126839f41.png)

**Comment by marefr** [comment]
Are you referring to that you have multiple series with same name? Can't you Since you're using prometheus you should be able to resolve this in query I think. Let me know if I misunderstood and will reopen.

**Comment by siebenmann** [comment]
This is with distinct series with different names and label sets (from the same query), as visible in the screen shot. The legend shows two series with different colors, but the graph shows only one color.

**Comment by marefr** [comment]
Are

**Comment by marefr** [comment]
Can you open query inspector, copy to clipboard and include here. Thanks

**Comment by siebenmann** [comment]
Here is the query inspector result for more or less the same graph as in the screenshot above (I didn't get exactly the same time ranges, but I included the two data points). The labels are a bit different because we changed some things in the graph since then.

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/api/v1/query_range?query=count(cslab_sntp_query_status%20%3D%3D%200)%20by%20(cshost%2Cipaddr)&start=1562937390&end=1562941185&step=15"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "cshost": "ntp2.torix.ca"
          },
          "values": [
            [
              1562940855,
              "1"
            ],
            [
              1562940870,
              "1"
            ],
            [
              1562940885,
              "1"
            ],
            [
              1562940900,
              "1"
            ]
          ]
        },
        {
          "metric": {
            "cshost": "time.nrc.ca"
          },
          "values": [
            [
              1562938275,
              "1"
            ],
            [
              1562938290,
              "1"
            ],
            [
              1562938305,
              "1"
            ],
            [
              1562938320,
              "1"
            ]
          ]
        }
      ]
    }
  }
}
```

**Comment by torkelo** [comment]
There is not much grafana can do when the same lines occupy the same space

**Comment by siebenmann** [comment]
In this case, the lines aren't occupying the same space. The last time stamp for the time.nrc.ca series is well before the first time stamp for ntp2.torix.ca (1562938320 versus 1562940855, a gap of 2535 seconds on a graph that has more than enough resolution for a wide space between them).
