### ISSUE TITLE
Grafana integration with Postgresql V10

### ISSUE THREAD

**Issue by chandertechavidity** [grafana/grafana#18106]
**What happened**:
Trying to configure Postgresql with Grafana, Unable to do the required task.

**What you expected to happen**:
Grafana should be configured withPostgresql, but server failed to start.

**How to reproduce it (as minimally and precisely as possible)**:

Configure Grafana wth Postgresql with 10.9 or 11

**Anything else we need to know?**:
Grafana V6.2.5 and V6.3.0 Both versions are failing.

**Environment**:
Ubuntu 18 Bionic LTS

- Grafana version: V6.2.5/V6.3.0

- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: Error is pasted in the forum.

**Comment by chandertechavidity** [comment]
t=2019-07-14T05:24:34+0000 lvl=info msg="[SQL] INSERT INTO \"migration_log\" (\"migration_id\",\"sql\",\"success\",\"error\",\"timestamp\") VALUES ($1, $2, $3, $4, $5) RETURNING \"id\" []interface
{}{\"Update user table charset\", \"ALTER TABLE \\\"user\\\" ALTER \\\"login\\\" TYPE VARCHAR(190), ALTER \\\"email\\\" TYPE VARCHAR(190), ALTER \\\"name\\\" TYPE VARCHAR(255), ALTER \\\"password\\
\" TYPE VARCHAR(255), ALTER \\\"salt\\\" TYPE VARCHAR(50), ALTER \\\"rands\\\" TYPE VARCHAR(50), ALTER \\\"company\\\" TYPE VARCHAR(255), ALTER \\\"theme\\\" TYPE VARCHAR(255);\", false, \"pq: rela
tion \\\"UQE_user_login\\\" already exists\", \"2019-07-14 05:24:34\"} - took: 1.470891ms" logger=sqlstore.xorm
t=2019-07-14T05:24:34+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: pq: relation \"UQE_user_login\" already exists"


Tested Grafana 6.2.5 and 6.3.0 Beta. Both are having the same issue.

OS: Ubuntu 18.04.2 LTS
Grafana: 6.2.5 and 6.3.0
Postgresql:  PostgreSQL 10.9

**Comment by chandertechavidity** [comment]
Tested Postgresql V11 also. Having the same issue.

Either Grafana (V6.2.5 or V6.3.0 Beta) does not work with Postgresql V10.9 and V11.x.

**Comment by markelog** [comment]
You haven't filled the issue description points, would you mind doing that? It will help us better asses the issue

**Comment by chandertechavidity** [comment]
Filled all the details. Please do let me know if you need more info.

**Comment by markelog** [comment]
Thanks! :)

**Comment by markelog** [comment]
Okay, so it seems this is actually a postgres issue - https://www.postgresql.org/message-id/flat/28827.1561082086%40sss.pgh.pa.us#df2287bd7481153984bef6bab40af0db.

@chandertechavidity as a quick fix, you can just run the different version of postgres, like postgres 9.6.14 (9.6.13 also affected btw), 10.8 or 11.2, something like that.

On our side, we can do one of two things (at least how I see it):
1. Execute alter table calls separately, we fail only when there is multiple alter table calls bulk together
1. Document that we do not support aforementioned postgres versions 

/cc @torkelo, @xlson

**Comment by chandertechavidity** [comment]
@markelog  Thanks for the update. Tested with Postgres 11 version also. having the same issue.

**Comment by sasadangelo** [comment]
Hi all,

I have a docker image based on Ubuntu 16. I installed PostgreSQL 9.5 and today I got the same problem. The strange thing is that it worked until yesterday. The only thing that could be changed is that Ubuntu uploaded a new fix version of PostgreSQL 9.5.

Anyone can help?

**Comment by sasadangelo** [comment]
This fix worked fine https://github.com/grafana/grafana/issues/17771#issuecomment-510407530

You need to start Grafana, let it fails, then apply the fix and start again.

**Comment by markelog** [comment]
See my response to that workaround - https://github.com/grafana/grafana/issues/17771#issuecomment-516112130.

We talked about it internally and decided to not change the schema, but treat this as documentation issue, since postgres already landed a fix for it.

However, if we there would be a lot of confusion or if there would be great need to use grafana with these postgres versions we might reconsider. 

But for now, we just document unsupport postgres versions
