### ISSUE TITLE
Run Grafana as a subfolder on domain using CentOS and Apache Alias?

### ISSUE THREAD

**Issue by drsprite** [grafana/grafana#1810]
Love grafana, but want to be able to run it in a subdirectory in my Apache setup. Something like http://server/stats.  I read the Config guide and it mentions ProxyPass and the like, but I can't get that to work. So I tried for an Alias. I've made more progress with an Alias, but I'm stuck. 

I've made the changes below to get http://server/stats working, but all I see is a directory listing, not the website. Is there something I'm missing? Or example of a proper `ProxyPass`?

Installed using `rpm -Uvh https://grafanarel.s3.amazonaws.com/builds/grafana-2.0.0_beta3-1.x86_64.rpm`

Then,
`chown -R apache:apache /usr/share/grafana/`

In httpd.conf:

```
<VirtualHost *:80>

        Alias /stats /usr/share/grafana
        <Directory /usr/share/grafana>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

</VirtualHost>
```

In `/etc/grafana/grafana.ini`, I've tried changing all kinds of options here, but nothing seems to be working. From the IP of the `domain`, to the `port` to 80 to setting the `root_url`, I can't figure out the right options here. 

Instead, all I see is a directory listing of `/usr/share/grafana` when I go to `http://server/stats`

Here's the output from my log:

```
2015/04/17 21:24:37 [I] Starting Grafana
2015/04/17 21:24:37 [I] Version: 2.0.0-beta3, Commit: 41777c0, Build date: 2015-04-12 15:31:35 -0400 EDT
2015/04/17 21:24:37 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/04/17 21:24:37 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/04/17 21:24:37 [I] Migrator: Starting DB migration
2015/04/17 21:24:37 [I] Listen: http://0.0.0.0:3000
```

**Comment by torkelo** [comment]
Grafana is its own webserver, you do not need apache or nginx (unless you want to reverse proxy grafana). 

If you want to host grafana on port 80 along with other things you need to configure apache to reverse proxy requests to grafana's webserver (by default, as you can see in your log it is listening on port 3000). 

I do not know the config for apache to reverse proxy, only for nginx but should be pretty simple. 

Also an important thing to do is update root_url in /etc/grafana/grafana.ini , since you want to expose grafana through /stats url, you need to update root_url and add /stats to the end.

**Comment by torkelo** [comment]
```
<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass /stats http://0.0.0.0:3000/
    ProxyPassReverse /stats http://0.0.0.0:3000/
</VirtualHost>
``` 

This is just an example, from googling how to do reverse proxies in apache.  but as I said it is important to add /stats to root_url grafana config if you put grafana behind a subpath

**Comment by drsprite** [comment]
Thanks. I've tried that, got some errors. So I disabled SELinux. Now I'm getting timed out errors trying to connect to grafana. Chrome reports `ERR_CONNECTION_TIMED_OUT`

Do I need to include port 3000 or 80 in the `root_url` grafana config?

I don't see any other errors in Apache or grafana logs. Not sure why it's timing out.

**Comment by torkelo** [comment]
Not sure I can help you, not an apache expert. make sure apache can speak to grafana. no root url does not the internal port, only the external that users will see in browser

**Comment by drsprite** [comment]
Thanks, making progress, but not quite there now. When I load up http://server/stats, I get this below:

`{{alert.title}}`

My `root_url` has the /stats/ at the end of it: `root_url = %(protocol)s://%(domain)s:%(http_port)s/stats/`

Thoughts?

**Comment by torkelo** [comment]
dis you restart grafana-server after making the config change?

**Comment by drsprite** [comment]
Yes I did.

**Comment by torkelo** [comment]
open chrome dev tools and inspect what files do not load, also check the base href element in html head

**Comment by drsprite** [comment]
Looks very similar to the log file I pasted above:

404 on grafana.dark.min.1dc11bb8.css
404 on app.5e82909b.js

In HTML head I see `<base href="/stats/">`

**Comment by torkelo** [comment]
looks correct, must be some issue with how apache reverse proxy is configured, what are the requests to grafana? 

It looks like there is trailing slash to many in the apache config.

Try this:
```
<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass /stats http://0.0.0.0:3000
    ProxyPassReverse /stats http://0.0.0.0:3000
</VirtualHost>
```

See I removed the trailing `/` from the ProxyPass lines

**Comment by drsprite** [comment]
Ah, found it! I had the trailing `/` after the port. Removed that and now grafana loads, but now I have a datasource error. 

Looks like it's inserting too many `/stats/` in the graph request?

From the Inspector, under the Request tab, I see this: `Url	/stats/stats/api/datasources/proxy/1/api/query`

For my datasource, I'm using OpenTSDB, and it works when going to `http://192.168.0.219:4242` manually. 
Thoughts?

**Comment by torkelo** [comment]
@drsprite yea, that is a bug in beta3, fixed in rc1, http://grafana.org/download/builds.html

You can either upgrade or change "access" mode in data source edit to "direct"

**Comment by drsprite** [comment]
Fantastic. I changed it to direct access and it didn't work. I upgraded using the RPM and everything is working great. 

Thanks for all the help on this one! Much appreciated.

**Comment by torkelo** [comment]
@drsprite that is great! yea "direct" mode only works if you have OpenTSDB configured to allow Cross origin resource sharing, that is why the proxy mode is so useful (lets you skip CORS issues)
