### ISSUE TITLE
Variables do not protect against self-reference when using ${var_name:option} syntax

### ISSUE THREAD

**Issue by CRBarber3** [grafana/grafana#18105]
**What happened**:

I accidentally created a variable that referenced itself using `${var_name:option}` syntax. 
This causes the dashboard to get stuck loading if you attempt to open it with the self-referencing variable. (loading wheel)Services 

The real issue is that I don't see any way to recover the dashboard if this occurs. (from the frontend at least)

**What you expected to happen**:

There appears to be protection from self-referencing variables if you just directly put `$var_name` in the query. I would expect this protection to extend to the `${var_name:option}` syntax.

i.e. I would expect to see this:
![image](https://user-images.githubusercontent.com/14188213/61163347-6f15bf00-a4db-11e9-8615-c81e40062964.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create new dashboard
2. Dashboard Settings
3. Variables > Add Variable
    Name: test
    Type: Query
    Data source: --Grafana--
    Query: `SELECT ${test:csv}`
4. Add
5. Save (give it a name)
6. Save

**Anything else we need to know?**:

This is a user issue but I feel the protection is important because the dashboard appears unrecoverable (at least as far as I can tell, from the front end).

**Environment**:
- Grafana version: Grafana v6.2.5 (6082d19)
- Data source type & version: PostgreSQL (and the default possibly all)
- OS Grafana is installed on: Windows 7/10
- User OS & Browser: Windows 7/10
- Grafana plugins: none
- Others:

**Comment by hugohaggmark** [comment]
We have introduced this check, not sure in which version of Grafana but I can't repro it on Grafana v7.4.0-pre (db637a3630). This check will only work for data sources that represent their query with a string. This will check will not work for data sources that represent their query with complex objects. 

Thank You to you for taking the time to create this issue!
