### ISSUE TITLE
The "Back" button is overlapped by the title in kiosk mode

### ISSUE THREAD

**Issue by xr0m** [grafana/grafana#18114]
**What happened**:
The "Back" button is overlapped by the dashboard title in _kiosk_ mode

![Monitoring - CPU](https://user-images.githubusercontent.com/4132250/61208202-0b7cd300-a721-11e9-8c8f-b2d248ccc4e1.png)

**What you expected to happen**:
I would like to see the same button position as without `kiosk` mode

![Monitoring - CPU_fixed](https://user-images.githubusercontent.com/4132250/61208416-9067ec80-a721-11e9-83de-374d34158ec8.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Open dashboard in `kiosk=tv` mode
2. Switch any panel to me maximized view by clicking on the _panel header -> View_ menu item
3. See the "Back" button is overlapped by the dashboard title

**Environment**:
- Grafana version: v6.2.5 (6082d19)
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10, Firefox 60.8.0, Chrome 75.0.3770.100

**Comment by briangann** [comment]
Verified, I have seen this also.
