### ISSUE TITLE
Wrong “latest dashboard” version is selected when using browser-option “restore last session”

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#18117]
**What happened**:
After a user saves some changes in a dashboard and afterwards restarts the browser (browser setting "restore last session" checked), the dashboard is shown in a version **before** the last save. This is highly confusing, especially because it happens to the user who just saved a new dashboard version…
Fortunately, this is not a permanent problem, as it can be solved simply by reloading the tab. **But still**: you have to know about this or you’ll find yourself constantly restoring the dashboard to the “real” latest version unnecessarily… In fact, this is what’s happened in my company several times now: users restore the “real latest version” and thus create a new version… Only because they think someone reset the dashboard to an earlier version or something…

**What you expected to happen**:
Saving a dashboard and closing/opening the browser should point to the latest version.

**How to reproduce it (as minimally and precisely as possible)**:

0. (setup browser to “restore last session” when starting)
1. create a new dashboard and save it
2. change something and save again, effectively creating a second version
3. close browser and start it again
4. the initial dashboard version will be shown
5. check the dashboard versions and recognize the wrong “latest” version

The following screenshot has been made at step 5:

![ad2a173f5885e9bf9a2e69afdb8070f914744d0c_2_690x291](https://user-images.githubusercontent.com/11644606/61214799-2f341f00-a709-11e9-8016-9917b609eb8d.png)

**Anything else we need to know?**:
This happens only if the browser is configured to reopen “last sessions”, so the Grafana tab will be opened instantly when the browser (re-)starts. Also, a simple reload of the tab solves the problem.
Nevertheless, IMHO this should be investigated because it’s a confusing behaviour.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version:
- OS Grafana is installed on: Red Hat Enterprise Linux 7.x
- User OS & Browser: Ubuntu 16 LTS & latest Firefox/Chrome
- Grafana plugins: -
- Others: MySQL Backend

**Comment by briangann** [comment]
Definitely not the behavior we want, it should be fairly easy to duplicate.

**Comment by sspieker** [comment]
FYI, I'm still experiencing this bug in Version 6.5.0. I'm aware of the longterm priority; any plans to tackle this problem?
