### ISSUE TITLE
http://play.grafana.org/dashboard/db/influxdb doesn't load the chart. Chart panel returns HTTP 504 error

### ISSUE THREAD

**Issue by bhattchaitanya** [grafana/grafana#1811]
Please take a look at the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/7585681/7214516/5e6826e2-e564-11e4-88c3-1f5c8dc4fa41.png)

**Comment by torkelo** [comment]
Fixed, thanks for reporting it.
