### ISSUE TITLE
MySQL Timezone/Grafana Interface Issue

### ISSUE THREAD

**Issue by jmsieglaff** [grafana/grafana#18120]
I'm unsure if the best place to place this is bug reports or feature enhancements.  There are numerous similar issues like my problem, but I do not think I've found one that exactly addresses my issue.

My Grafana dashboard is set to UTC.  I have data in MySQL database, with a column named 'time' that is datetime type--which implies UTC.  The server that hosts Grafana is linux and set to UTC.  The server that hosts MySQL is linux and set to local time (Central US).  I have found a variety of help posts say to set MySQL server to UTC--but I cannot do this, the MySQL DB server is used by many others and I've been told it needs to stay in local time.

**What:  A way to have grafana correctly display data when the MySQL server is set to local time and all other pieces are set to UTC.**

Why:  Otherwise current data is not displayed or incorrect data is not displayed.

More info:
My grafana query looks like this:
`SELECT
  time as time_sec,
 ...
WHERE $__timeFilter(time) AND ...
ORDER BY time ASC;`

When I run this the data displayed is shift back from current 5 hours (my UTC offset, I  know MySQL is returning it as such).  One solution I have found involves setting the MySQL session time zone, which if I go into MySQL and do this before I do my query that works, but grafana only allows 1 line of MySQL to be executed, so this is not option--perhaps adding the ability to execute multiple lines of MySQL would be a solution?

I've also found in some thread to wrap time with unix_timestamp().  When I do this, the data _looks_ to display correctly, but it is incorrect.  If I change the end time from now to now+6h, I see the data goes out 5 hours into the 'future' (my current UTC offset) and the data for the current time is actually data from 5 hours previous.

If this problem has been solved and I just have been unable to find the solution, I apologize, but I've have spent multiple work days trying to find a solution and still do not have a solution.  I appreciate any insights.

**Comment by briangann** [comment]
Two approaches (both will require changes):

1) We can add a datasource option to shift results by an arbitrary zone as part of the query editor.
2) Have the datasource configuration page have a timezone setting (defaulting to UTC)

**Comment by jmsieglaff** [comment]
Thank you very much, I appreciate your team's attention to this matter.

I would think option #2 above is ideal.  By having a timezone setting, daylight savings issues are accounted for automatically.  With option 1 above, if I understand what you mean by arbitrary shift, you would need to shift the correct number of hours based on your timezone relative to UTC, which changes with daylight savings time.

What kind of timeline is reasonable for this to be implemented and available for testing?

**Comment by jmsieglaff** [comment]
One further comment that might be helpful describing what I'm seeing.

Using the time picker GUI with Grafana to say display Last 6 Hours of data.

Data displayed is offset by my current UTC offset (-5 hours).  So for example at 1426 UTC, my Grafana display shows the most recent available data as 0926 UTC.  The data displayed matches what is in the database at 0926 UTC, so basically the query is not fetching the most recent 5 hours (current UTC offset).

If I modify my SELECT from `time as time_sec` to `unix_timestamp(time) as time_sec` (as some threads have suggested) my Grafana display shows data at 1426 UTC, but the data is NOT the data from 1426 UTC, but rather 0926 UTC.  If I change my time selector from Now-6h->Now to Now-6h->Now+6h, I see the current data (for 1426 UTC) displayed at 1926 UTC.

**Comment by jmsieglaff** [comment]
Hello,

Are there any updates about the possibility of these changes being made to the Grafana code base?

Thank you,
Justin Sieglaff

**Comment by aocenas** [comment]
This should me marked also for other DBs with time columns without timezone.
Issue for PG: https://github.com/grafana/grafana/issues/18289

**Comment by jmsieglaff** [comment]
I would like to see a solution to this problem implemented as I feel it should be supported.

In the meantime, I have found an acceptable work around, in addition to the UTC date/time stored in my DB for the data, I’ve added a timestamp variable to the DB that is autopopulated (and due our center’s MySQL time setting to local time, it is also in local time).

In my Grafana MySQL query, I retrieve the UTC date/time but the where clauses operates on the timestamp variable. Not ideal but I’ve at least been able to display current data correctly.

e.g.,
`SELECT
  time as time_sec,
  data as data
FROM myDataBase
WHERE $__timeFilter(time_stamp)`

**Comment by ziezo** [comment]
Maybe it helps to force the connection to use UTC time in the connect string:

Change grafana/pkg/tsdb/mysql/mysql.go
```
cnnstr := fmt.Sprintf("%s:%s@%s(%s)/%s?collation=utf8mb4_unicode_ci&parseTime=true&loc=UTC&allowNativePasswords=true",
```
to
```
cnnstr := fmt.Sprintf("%s:%s@%s(%s)/%s?collation=utf8mb4_unicode_ci&parseTime=true&loc=UTC&allowNativePasswords=true&time_zone=%27%2B00%3A00%27",
```
this should add ```SET time_zone='+00:00'``` to the mysql session.

**Comment by rohoog** [comment]
Or use the convert_tz mysql function while querying the time. Like:
select convert_tz(time,@@SESSION.time_zone,'GMT') as "time", ....

This is the workaround I use now.

**Comment by Bubbu17** [comment]
> 
> 
> Two approaches (both will require changes):
> 
>     1. We can add a datasource option to shift results by an arbitrary zone as part of the query editor.
> 
>     2. Have the datasource configuration page have a timezone setting (defaulting to UTC)

I hav the similar issue, an i'd prefere the first solution because I am also unable to change the server settings nor change the old database entries from the past therefor the only solution to me is to profide a Shift option in the Querymanager of Grafana.

**Comment by hello-world-2021** [comment]
There is issue in grafana where it checks time as UTC time but when in interval comparison or group by it checks time as local and only converting interval time to UNIX .

Solution - You should add one more column to table which should contains UNIX equivalent time of your timestamp and pass that in time column and everything will work.

Eg.
Local Browser Time - 2020-05-31 17:21:05 (It is UTC + 5:30)
UNIX_TIMESTAMP - 1590945665

**Comment by leiyangyou** [comment]
made do with something like this

```
  ( $__timeGroup(created_at+'8 hours'::interval, $interval) ) - 28800 "time",
```
