### ISSUE TITLE
How to import TimeSeries into a panelCtrl.ts

### ISSUE THREAD

**Issue by Jiajun-Deng** [grafana/grafana#18122]
Guys, I have trouble in importing the TimeSeries class into my panelCtrl.ts.
I'm working on develop a panel in typescript. I installed @types/grafana 4.6.3(unofficial declaration files by Glory team.)
This is the syntax of the declaration file:
```
declare class TimeSeries {
  datapoints: any;
  id: string;
  label: string;
  alias: string;
  color: string;
  valueFormater: any;
  stats: any;
  legend: boolean;
  allIsNull: boolean;
  allIsZero: boolean;
  decimals: number;
  scaledDecimals: number;
  hasMsResolution: boolean;
  isOutsideRange: boolean;
  lines: any;
  bars: any;
  points: any;
  yaxis: any;
  zindex: any;
  stack: any;
  nullPointMode: any;
  fillBelowTo: any;
  transform: any;
  flotpairs: any;
  unit: any;
  constructor(opts: any);
  applySeriesOverrides(overrides: any): void;
  getFlotPairs(fillStyle: any): any[];
  updateLegendValues(formater: any, decimals: any, scaledDecimals: any): void;
  formatValue(value: any): any;
  isMsResolutionNeeded(): boolean;
  hideFromLegend(options: any): boolean;
}

declare function updateLegendValues(data: TimeSeries[], panel);


export { TimeSeries as default, updateLegendValues };
```

This is the way I imported:
`import TimeSeries from "grafana/app/core/time_series2";`

This is how I use the class to create an object:
`let series = new TimeSeries({
      datapoints: seriesData.datapoints,
      alias: seriesData.target
    })`

This is the error I got:
![Screen Shot 2019-07-15 at 11 35 59 AM](https://user-images.githubusercontent.com/46533014/61232809-c478e880-a6f4-11e9-8a4e-6953ffa15162.png)

Please help me check this out. I think it is the issue of how I import the .d.ts file.

**Comment by ryantxu** [comment]
Check:
https://github.com/grafana/simple-angular-panel

that is a good starting place for new angular panel development. 

If you have more trouble, try asking on the community site first:  https://community.grafana.com/

**Comment by Jiajun-Deng** [comment]
I checked this issue on the community already, seems no solution yet.
