### ISSUE TITLE
Import of dashboards from custom app broken.

### ISSUE THREAD

**Issue by Krolken** [grafana/grafana#18124]
**What happened**:
When importing dashboards at App enable a Type error is thrown. 
```
config.js:33 Uncaught (in promise) TypeError: this.appEditCtrl.importDashboards is not a function
    at UtilitarianAppConfigCtrl.postUpdate
```

**What you expected to happen**:
The dashboards to be imported.

**How to reproduce it (as minimally and precisely as possible)**:
I use the suggested code at: https://grafana.com/docs/plugins/developing/apps/#developing-an-app-plugin. 
Mounting a minimalistic app in docker container should do it with the code in the link in the config.js.

**Anything else we need to know?**:
I tried several version and the error seems to starts in 6.1.0 and and is present in the latest release.

I added angular as import in config.js since the Sensu plugin did the same. Didn't change anything.

It could be related to #16586. The loading was rewritten in React. Maybe there is a new way of doing it that is not updated in the documentation?

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: custom app
- OS Grafana is installed on: docker from grafana/grafana
- User OS & Browser: Mac, Chrome
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment]
This hook is no longer needed / required. The backend will import them automatically.

If you add your dashboards to plugin.json they should get imported

**Comment by Krolken** [comment]
Removed the code and error is gone. But I still don't see my dashboards. Menu items appear as they should but get "Dashboard not found". Dashboards are not present in the application.

They show up under Dashboards in the plugin settings, but I also get error if I try to import from there.

```
POST http://localhost:3000/api/dashboards/import 500 (Internal Server Error)

angular.js:14700 Possibly unhandled rejection: {"data":{"message":"Failed to import dashboard"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/dashboards/import","data":{"pluginId":"utilitarian-grafana-app","path":"dashboards/utilitarian_overview_for_import.json","overwrite":false,"inputs":[]},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Internal Server Error","xhrStatus":"complete"}

Possibly unhandled rejection: {"message":"Failed to import dashboard"}
```

I have used the export feature of dashboards that I created, both as external and internal. 

Plugin.json

```json
"includes": [
    {"type": "dashboard", "name": "Utilitarian Overview", "path": "dashboards/utilitarian_overview.json", "addToNav": true, "defaultNav": true},
    {"type": "dashboard", "name": "Meter Device Overview", "path": "dashboards/utilitarian_meter_device_overview.json", "addToNav": true},
    {"type": "dashboard", "name": "Utilitarian Overview Test", "path": "dashboards/utilitarian_overview_for_import.json", "addToNav": true},
    {"type": "dashboard", "name": "Meter Device Overview Test", "path": "dashboards/utilitarian_meter_device_overview_for_import.json", "addToNav": true},

    {"type": "page", "name": "Test Page", "component": "TestPageCtrl", "role": "Viewer", "addToNav": true}

  ],
```
They need a postgres datasource. Same behaviour if I have the datasource set up before enable or not. Can I provision datasources on app enable?

Should this be a separate issue?

**Comment by marefr** [comment]
@Krolken what does your Grafana server log say when above error happens?

**Comment by Krolken** [comment]
Hi. Sorry for late response, was on vacation. 

I opened up another issue, #18205, and it was resolved by @torkelo
