### ISSUE TITLE
A new dashboard panel for table data

### ISSUE THREAD

**Issue by bhattchaitanya** [grafana/grafana#1812]
It would be awesome if table data with values such as min,max,avg,total for a set of related columns could be viewed in a dashboard panel in a tablular fashion. This is similar to the Graph legend table but with properties of SingleStat panel were users can click on a particular table row that would probably link to another dashboard were detailed graphs are available. 

The reason why i think this is a critical is because Dashboard real estate is very expensive, especially for  large distributed systems (example: 10000 servers with over 300 apps) .Having all the graphs in a single dashboard would not only make the dashboard slow but also not practically possible to view all the important metrics in single view.

**Comment by torkelo** [comment]
Just so you know, min, max, avg, and total cannot be shown at the same time (as they are not accurate / correct at the same time). It depends on your metric query, if you use mean aggregation, total, max and min are not going to be correct for example. This is true for Graphite, InfluxDB and OpenTSDB

**Comment by torkelo** [comment]
already an issue for this, #215
