### ISSUE TITLE
Heatmap Legend Incorrect

### ISSUE THREAD

**Issue by hrobertson** [grafana/grafana#18139]
When using the Heatmap visualisation it is possible to set custom min and max values for the Color Scale. This works correctly in the heatmap chart itself, but the legend is incorrect.

**Auto Color Scale min and max** (Works correctly)
Chart: The coolest colour represents the min value in the data and the hottest represents the max value in the data. :heavy_check_mark:
Legend: Numbers span from the min to the max. :heavy_check_mark:
Legend: Colour spectrum spans from min to max. :heavy_check_mark:

Screenshot showing correct behaviour of auto values:
![heatmap-auto](https://user-images.githubusercontent.com/497286/61297753-cf0aaf00-a7d4-11e9-9b36-1a7531ce0063.png)

**Custom Color Scale min and max** (Broken)
Chart: The coolest colour represents the custom min value and the hottest represents the custom max value. :heavy_check_mark:
Legend: Numbers span from the custom min to the custom max. :heavy_check_mark:
Legend: Colour spectrum spans from min value in the data (not the custom min) to the max value in the data (not the custom max). :x:

Screenshot showing incorrect legend with custom min and max:
![heatmap-custom](https://user-images.githubusercontent.com/497286/61298656-881db900-a7d6-11e9-8daf-ab1b8af57e92.png)

Screenshot showing mock-up of what the legend should look like with custom min and max:
![heatmap-custom-mock](https://user-images.githubusercontent.com/497286/61299458-0f1f6100-a7d8-11e9-9ef3-2d240923d264.png)

Of note is that my histogram values are actually percentages so I know they will always be between 0 and 100. I chose -20 and 75 purely to illustrate the bug.

**Environment**:
- Grafana version: Grafana v6.1.6 (cf9cb45) (grafana/grafana:6.1.6 Docker image)
- Data source type & version: Prometheus Histogram
- User OS & Browser: Arch Linux & Chromium

**Comment by maxvonroden** [comment]
We've recognized the same. Maybe it's worth to mention, that the used min and max values (inside of the custom range) are added to the legend. 
![Heatmap_Legend](https://user-images.githubusercontent.com/59958042/72518193-0bd36380-3855-11ea-9fd5-c16541e0b8ca.png)
In our use case the custom legend was -15 to 35, but in the example chart only values from 3 to 29 are in the buckets, so the legend range "shrinked" and min/max marker were added. Maybe this isn't always useful and can be made confgurable, while fixing the coloring-bug?
