### ISSUE TITLE
new timepicker widget in 6.3.0 too clunky to use 

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#18135]
In v6.3.0-beta1 there is a new date/time /timeframe selector widget...

dieter 11:05 AM
why did the grafana dashboard time selector change from a well organised panel, to a 1-dimensional list that i have to scroll through any time i want to see more than 24h of data?
11:05 AM
the amount of scrolling and lack of organisation is quite annoying in the new version
￼
torkelo 11:12 AM
I found it faster to find the one I need, the 3 side by side lists where harder to scan I found. But we will add search and make it higher so you can see more, could add section headings to the list as well but no clear sections really
11:15 AM
Definitely room for improvements
￼
dieter 11:28 AM
search? oh god no i don't want to do even more work to find what i need
11:29 AM
it should simply be 1 click on the button upper right, it expands, use your eyes to spot which one you want, click on it
11:29 AM
no searching, no scrolling, and no iterating over 1 dimensional lists
11:30 AM
based on what you said, it seems the better solution would be to take what we had, and organize it a bit better / more clearly, so it's easy to spot the option you need

**Comment by torkelo** [comment]
Not sure posting internal chat discussions on public Github is a great thing to do. 

If you have time please add your improvement / feedback to this existing issue:
https://github.com/grafana/grafana/issues/17802
