### ISSUE TITLE
x-Axis change from day to Month name

### ISSUE THREAD

**Issue by bahmanfarid** [grafana/grafana#18136]
hi , i would ask about custom-date-format in multibar gragh panel plugin , which give A-axis an extra option to change from day to month.
![custom-date-format](https://user-images.githubusercontent.com/51912313/61288016-8ba94400-a7c6-11e9-828d-9189ec7c8128.png)

**Comment by torkelo** [comment]
Hi, 

This is an external (community) plugin. Please open issue with in the author repo
