### ISSUE TITLE
Grafana is not persisting template variable in dashboard url after login

### ISSUE THREAD

**Issue by adigov** [grafana/grafana#18149]
**What would you like to be added**: Sign In URL must preserve template variables if present

**Why is this needed**:
1. Let's say user is not logged-in but has a URL for dashboard. That URL has a template variable name and corresponding value to it.
2. Dashboard loads fine.
3. Now user wants to Sign In, and clicks the login link.
4. That Sign In URL is doesn't have template variable information, only has until dashboard ID

Fix is in `SignIn.tsx` where `loginUrl` is calculated. Code change could be something like

```
const loginUrl = `login?redirect=${encodeURIComponent(window.location.pathname + window.location.search)}`;
```

**Comment by sairam0903** [comment]
Small but makes user life convenient by preserving the template variables.

**Comment by torkelo** [comment]
We have an issue for this already (redirect after sign in)
