### ISSUE TITLE
when checking the countries option ,the panel is running error,what problem is it ?

### ISSUE THREAD

**Issue by huangyuan666** [grafana/grafana#18155]
**What happened**:
when checking the countries option ,the panel is running error,what problem is it ?
![image](https://user-images.githubusercontent.com/24352334/61367553-73b4eb80-a8be-11e9-92d0-4b4e4c044ce8.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What is the error? And what is your query response? Open chrome dev tools console, show error details there as well

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
