### ISSUE TITLE
t + arrow shortcut are not working anymore

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#18159]
**What happened**:

![tr](https://user-images.githubusercontent.com/291750/61373556-6b4ab980-a89a-11e9-8a3d-5faca65c7155.png)

those shortcut do not work anymore

**What you expected to happen**:

pressing the keys would still work

**How to reproduce it (as minimally and precisely as possible)**:

try to use the key shortcuts

**Anything else we need to know?**:

no

**Environment**:
- Grafana version: 6.4.0-61ac3b34pre
- User OS & Browser: chrome and firefox on linux and windows

**Comment by briangann** [comment]
t-z works (zoom), t-arrows do not. Verified with v6.2.5

Also, the docs are missing the arrows: 

https://grafana.com/docs/features/shortcuts/#time-range
