### ISSUE TITLE
custom timerange form is not in a box in firefox and chrome

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#18158]
**What happened**:

![ffox](https://user-images.githubusercontent.com/291750/61373371-ebbcea80-a899-11e9-81f0-ba8133bd64c0.png)

**What you expected to happen**:

a clean time picker (with a solid background that covers it)

**How to reproduce it (as minimally and precisely as possible)**:

Open custom time picker in firefox (I use 65.0) or chrome

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.0-61ac3b34pre
- User OS & Browser: firefox and chrome on linux and windows

**Comment by davkal** [comment]
Can't repro on both Chrome 75.0.3770.142 and Firefox 67.0.3 on Ubuntu 19.04 64-bit.

**Comment by torkelo** [comment]
I can reproduce in osx in Chrome, when running from latest master docker build. 

Maybe something that only happens in prod build? 

<img width="686" alt="Screen Shot 2019-07-23 at 20 48 50" src="https://user-images.githubusercontent.com/10999/61738793-5b940f00-ad8b-11e9-92a6-72d985a3a22d.png">

**Comment by roidelapluie** [comment]
I reproduced on

- firefox on Linux
- chrome on Linux
- chrome on Windows

**Comment by davkal** [comment]
Found the issue (div layering in time picker must have changed, now a flex direction is misguided). Easy fix. Investigating more important issue: how did this differ in dev vs prod...
