### ISSUE TITLE
Reset Admin pass

### ISSUE THREAD

**Issue by BenJule** [grafana/grafana#1815]
I was changing my pass! But now, the new Password isnt working! How can i reset it?

**Comment by torkelo** [comment]
yea, this feature is not yet implemented :(

**Comment by torkelo** [comment]
what database do you use for grafana? Sqlite ? I can walk you trough or give you a script that resets it

**Comment by BenJule** [comment]
@torkelo yes im using sqlite!

**Comment by ntmggr** [comment]
i am using mysql, any chance you can post the instructions here.

**Comment by steve--d** [comment]
Also need admin password reset for mysql.

**Comment by torkelo** [comment]
Update the password and salt columns in the user table:
update user set password = '59acf18b94d7eb0694c61e60ce44c110c7a683ac6a8f09580d626f90f4a242000746579358d77dd9e570e83fa24faa88a8a6', salt = 'F3FAxVm33R' where login = 'admin'

if its mysql you need to escape user, like  `` `user` ``

**Comment by torkelo** [comment]
The above will set password back go admin/admin

**Comment by steve--d** [comment]
Thanks.

user table needs to be in quotes for postgres ie: update "user" set ...

**Comment by Qtax** [comment]
+1

**Comment by vahidm** [comment]
I tried the given solution, and when I logged in with admin user after a little while (less than a minute) it kicked me out to login page. Now I can not login and when I set password again it does not have any effect.

**Comment by LB5000** [comment]
@torkelo apologies for opening up an old thread. Can you tell me what type of hash value grafana uses and how you would create a salt value? I'm new to password hashing in general and wish to automate the creation of grafana users via mysql within my Puppet setup.

Any info you can provide would be appreciated.

Cheers,
L.

**Comment by KarnG** [comment]
@Qtax .. this is great trick.

**Comment by aphawk** [comment]
1. stop `grafana` 
2. setup admin `user` and `password` in `grafana.ini`
3. delete `/var/lib/grafana/grafana.db`
4. restart 

I did reset password this way, but all previous dashboard data is lost.

**Comment by randyrue** [comment]
How about for an influxdb back end?

**Comment by miodrag-zivkovic-shiftplanning** [comment]
Which hashing algorithm do you use, how to generate some other password?
thanks.

**Comment by daniellee** [comment]
@miodrag-zivkovic-shiftplanning We use [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2) from the [golang package](https://godoc.org/golang.org/x/crypto/pbkdf2). For login, we also do a check for time based attacks: https://github.com/grafana/grafana/blob/master/pkg/login/auth.go#L60

**Comment by eoekun** [comment]
why [grafana-cli admin reset-admin-password admin](http://docs.grafana.org/administration/cli/) docments not working? It's told me 
**Admin password changed successfully ✔**
thanks for [Qtax](https://github.com/Qtax)

**Comment by daniellee** [comment]
@eoekun So you changed the password but it still does not work (with username `admin`)?

**Comment by eoekun** [comment]
@daniellee Use the grafana-cli does not work so I execute the sql statement.

**Comment by bergquist** [comment]
http://docs.grafana.org/administration/cli/#reset-admin-password

@eoekun what version are you running? grafana-cli-admin reset-admin-password works fine for me in 4.5.2

**Comment by xdfil** [comment]
1. edit `/etc/grafana/grafana.ini`
set `admin_user` and `admin_password` in the `[security]` section
2. stop the grafana service
3. delete the admin user from the db:
`# sqlite3 /var/lib/grafana/grafana.db`
`sqlite> delete from user where login = 'admin';`
4. start the grafana service
5. login with the admin user/pass you put in `/etc/grafana/grafana.ini`

**Comment by gvreddym** [comment]
Team, We are running grafana in kubernetes container. I forgot the admin password and try to reset the password with below command. but no luck.
grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" newpass

Can you please suggest how to i reset the admin@localhost/admin password on grafana container

**Comment by bergquist** [comment]
This is broken due to the service graph refactoring. 

The cli does not init the transaction manager and the bus itself.

**Comment by devnull1170** [comment]
>     1. edit `/etc/grafana/grafana.ini`
>        set `admin_user` and `admin_password` in the `[security]` section
> 
>     2. stop the grafana service
> 
>     3. delete the admin user from the db:
>        `# sqlite3 /var/lib/grafana/grafana.db`
>        `sqlite> delete from user where login = 'admin';`
> 
>     4. start the grafana service
> 
>     5. login with the admin user/pass you put in `/etc/grafana/grafana.ini`

Worked for me thanks using  v5.3.4 in a lxd  container!

**Comment by gusutabopb** [comment]
@xdfil's solution worked for me but only after deleting ALL users, not just admin.
