### ISSUE TITLE
$scope returns empty dataSourceResponse object

### ISSUE THREAD

**Issue by Optimusbumble** [grafana/grafana#18156]
**What happened**:  Query Editor displays results of the query correctly, but it is not picked up by _MetricsCtrlPanel.ts_

**What you expected to happen**: $scope variable should pick results from query response. i.e, **this** object in Module.ts picks the queryresponse till v6.1.6 whereas it is empty post v6.0

**How to reproduce it (as minimally and precisely as possible)**: It works till v6.1.6 but this breaks post v6.2.0

**Anything else we need to know?**:
This is my custom plugin that works till 6.1.6 version

**Environment**:
- Grafana version: v6.2.5
- Data source type & version: Neo4j , Custom plugin
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & chrome
- Grafana plugins: NA
- Others:

**Comment by torkelo** [comment]
Can you show your code? We have no other reports of 6.2 breaking panel plugins

**Comment by Optimusbumble** [comment]
Please have a look here..

https://github.com/CognizantOneDevOps/Insights/tree/master/PlatformGrafanaPlugins/Panels/insightsCharts2.0

**Comment by torkelo** [comment]
Can you show a debug session where on data received event is not including data?

**Comment by torkelo** [comment]
You’re overriding issueQueries for not reason, not sure that is related

**Comment by Optimusbumble** [comment]
![6 1 6-Expected output](https://user-images.githubusercontent.com/51743150/61458287-a9f37900-a959-11e9-9d54-de02d0e920db.png)
![6 2 5](https://user-images.githubusercontent.com/51743150/61458288-a9f37900-a959-11e9-972a-fb24b12d604a.png)


I have attached the debug sessions for both versions where i get datasourceresponse object in 6.1.6 highlighted

**Comment by torkelo** [comment]
That property is not a core property that Grafana sets, you have to check what the data received event payload is, that is the hook the framework provides

**Comment by Optimusbumble** [comment]
I think i did not express in correct way. Panel object is empty in $scope in data-received event .Meaning i am not getting the required panel data from the hook.

![image](https://user-images.githubusercontent.com/51743150/61510938-8c1f2600-a9e4-11e9-93b6-bb8420484a55.png)

From the above image i have compared the [this] object of both the versions when EventEmitter(eventemitter3/index.js ) executes data-received event .

Please find the attachment below for the difference in properties and data is empty in 6.2.5

I see a major difference in **Plugin** property and **insightsPanelData** property(panel data)

[Grafana-Migration.docx](https://github.com/grafana/grafana/files/3409554/Grafana-Migration.docx)

**Comment by torkelo** [comment]
Not sure I understand, there is no $scope involved at all in the emitting or handling of the data received event.

**Comment by Optimusbumble** [comment]
Ah..ok. Let me re-phrase a little bit so that i try to make you understand the problem .

I am not getting the Panel query responses in data-received event . Meaning the query is giving me results in queryInspector whereas this results are missing in the InsightsPanelData object  as you can see in the attachment above.

The error i get after loading is **_e.data.map_** **is not a function** and i face issue in **MetricCtrlPanel.ts** in the line below.


    // load datasource service
    this.datasourceSrv
      .get(this.panel.datasource, this.panel.scopedVars)
      .then(this.updateTimeRange.bind(this))
      .then(this.issueQueries.bind(this))
      .then(this.handleQueryResult.bind(this))
      .catch(err => {
        // if canceled  keep loading set to true
        **if (err.cancelled) {**
          console.log('Panel request cancelled', err);
          return;
        }


All these are available as a result in $scope. I guess that might have misled and confused you. 
Also, Please suggest me if i can elaborate in some other way.

**Comment by Optimusbumble** [comment]
I think i have zeroed down to the code that breaks this .

My custom datasource plugin was not able to send data to my custom panel plugin , since the data format expected now is either timeseries or table.

In **metrics_panel_ctrl.ts** under **handleQueryResult()** , below code is added in 6.2 version which it throws error before _emitting the data_ thus breaking the panel.

**from 6.2**

   ```
 // Make sure the data is TableData | TimeSeries
    const data = result.data.map(v => {
      if (isSeriesData(v)) {
        return toLegacyResponseData(v);
      }
      return v;
    });
```

Fortunately this code was again _**removed in v6.3.0-beta1**_ but now custom datasource plugin was not able to execute any queries in queryselector making browser non-responsive. Browser non-responsive is throughout this version in many actions, Waiting for a stable release now since i am experiencing the same issue in _**most recent nightly builds**_ as well. Meantime if someone could tell me how to build grafana older verion(6.2.5) by modifying this piece of code to make custom plugin work. Because i am able to get docs only for new version(master) to build.
Appreciate any response.

**Comment by hugohaggmark** [comment]
Hi @Optimusbumble, have you been able to move forward on this issue or are you still stuck?

**Comment by torkelo** [comment]
closing this for now

**Comment by Vijay757943** [comment]
@hugohaggmark sorry for late reponse . Yes i have build grafana source and commented the code for legacyresponse in metricspanelctrl.ts .
It is working fine now in v6.2.5
