### ISSUE TITLE
query error warning icon no longer appears

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#18169]
6.3.0-beta1, graphite datasource

when you are editing a functioning panel, but edit the query such that it'll trigger a http500 in graphite (for example, use the groupByNodes function with a non-existing aggregation method such as 'mean') the spinner just keeps running, no data appears, and no red warning icon appears to warn about the failed query. the only way to see the query failed is by going to query inspector.

furthermore I'ld also like to bring up that having the loading icon and the warning icon on different sides of the panel is a bit annoying. perhaps we should have 1 place to indicate the status of the panel (loading vs loaded vs failed)

**Comment by davkal** [comment]
Can repro. Graphite returns html that embeds an error message. Did this ever work?

**Comment by davkal** [comment]
The error seems to arrive successfully at `metrics_panel_ctrl`, but then is not displayed.

**Comment by davkal** [comment]
The error is shown in view mode, but not in edit mode.

**Comment by davkal** [comment]
Looks like there is no digest being run after `processDataError` sets the error.

**Comment by Dieterbe** [comment]
> Graphite returns html that embeds an error message while most of the code seems to expect JSON. Did this ever work?

I don't think grafana ever did anything clever (such as parsing out the interesting bits) with the html returned by graphite, though i'm pretty sure in some places it sometimes shows the full html response as an error message

**Comment by Dieterbe** [comment]
thanks David!

**Comment by Dieterbe** [comment]
this is happening again in Grafana v6.3.4 (a557646)

see above ticket for reproduction instructions

**Comment by Dieterbe** [comment]
actually, seems like this is the 3rd time i ran into this issue (after it's been fixed 2 times). see
https://github.com/grafana/grafana/issues/16512

:?

**Comment by Dieterbe** [comment]
this is so easy to reproduce, using the instructions in OP.
here's a video of the bug in action again, this time on Grafana v6.3.6 (fdd2117)
https://youtu.be/A9X3eaeRbKc

**Comment by torkelo** [comment]
This is fixed in 6.4,  and was a bit tricky to replicate in 6.3 as it only happend with Graphite and graph panel in some scenarios (it shows it you switch tab, or in dashboard view), it's a timing thing with angular panels. 

Sorry for not fixing this earlier.
