### ISSUE TITLE
Fetch text/html from external source for text panels

### ISSUE THREAD

**Issue by luttikhouse** [grafana/grafana#1816]
I have an external database with detailed information about each server. I would like to dynamically fetch text/html into an text panel.

Adding two options to " edit text > mode" would do the trick: GET and POST.

**Comment by papersackpuppet** [comment]
This can be done with some basic javascript in an HTML text panel. As Jquery is already available on the page, you can use it to fetch the data and display it like so:

    <script type="text/javascript">
      $(document).ready(function() {
        $.ajax({url: "example.org/data"}).done(function(data) { $("myresult").text(data) } ) ;
      });
    </script>
    <span id="myresult" /> 

The only thing I'm unsure on at this point is if the text panels will refresh on the auto-refresh interval. If not, is there a way to capture the event and force a refresh in the script above?

**Comment by papersackpuppet** [comment]
Ok, I have the automatic refresh working in the text panel now. You have to hook into the angular scope on the dashboard and subscribe to the refresh event.

    <div id="myTextPanel" class="ng-scope">
        <script type="text/javascript">
          
          function refreshMyPanel() {
            $.ajax({url: "example.org/data"}).done( 
              function(data) { 
                $("#myResult").text(data) 
              } 
            );
          }
        
          $(document).ready(function() {
          
            refreshMyPanel(); // For the initial load of data
            
            // Refetch data every time the "refresh" event is broadcast
            angular.element($("#myTextPanel")).scope().$on("refresh", function() {
              refreshMyPanel();
            });
          });
          
        </script>
        <span id="myResult" /> 
    </div>

One small gotcha with this I've run into is if you have multiple text panels using this method, you will need to rename the ids of the elements, variables, and functions above to be unique for each panel.

**Comment by sslupsky** [comment]
+1

Would be very nice if there was a query tab in the text panel to query the text from elasticsearch.  Similarly, if you could query text for a table panel that would be helpful as well.

**Comment by s5unty** [comment]
+1

I am trying to show a Zabbix topological diagram in the text panel.
All well done except auto-refresh.
If you could have the automatic refresh working in the text panel that would be very helpful.

**Comment by mihino** [comment]
I used this script in text HTML panel to show current weather condition (temperature, wind, sunsire, sunset). Data are based on [yahoo.com/weather](https://developer.yahoo.com/weather/).

```
<script>
  var callbackFunction = function(data) {
    var wind = data.query.results.channel.wind;    
    //alert(wind.chill);
    $("#myWindspeed").text(wind.speed) ;

   var astronomy= data.query.results.channel.astronomy;
    $("#mySunrise").text(astronomy.sunrise) ;
    $("#mySunset").text(astronomy.sunset) ;

   var condition = data.query.results.channel.item.condition; 
   $("#myTemperature").text(condition.temp) ;
  };
</script>
<script src="https://query.yahooapis.com/v1/public/yql?q=select item, condition, wind, astronomy from weather.forecast where woeid = 818717 and u='c'&format=json&callback=callbackFunction"></script>
Temperature: <span id="myTemperature" /> &deg;C</br>
Sunrise: <span id="mySunrise" /> </br>
Sunset:  <span id="mySunset" /> </br>
Wind Speed:  <span id="myWindspeed" /> km/h
 
```

You can search your locationID: woeid  here: http://woeid.rosselliot.co.nz/
result is simple:
![image](https://cloud.githubusercontent.com/assets/7362918/14079974/2f7a225a-f502-11e5-9dc2-41a5013cd5f2.png)

**Comment by Will-Beninger** [comment]
@papersackpuppet
Was trying out your code above to get an image being polled regularly. Has a new version of Grafana broken it now? I'm an absolute JS noob so I spent a few hours tweaking it but really had no idea what I was doing.

No other text panels and it's an empty dashboard w/ only one row.

When I directly copy+paste your code above and substitute in a real server, I'm seeing the following error:

> TypeError: Cannot read property '$on' of undefined


Would appreciate any advice you have!

**Comment by yesoreyeram** [comment]
@papersackpuppet @torkelo Any suggestions for the issue stated above?

**Comment by inselbuch** [comment]
@mihino that script is truly wonderful... now how do i do that for an arbitrary website... e.g., i want to produce my own json results and display on grafana... i can produce the json, but i cannot get the callback to work. I think I need something else on my web server but I cannot figure it out. :-(

**Comment by jezhalford** [comment]
@yesoreyeram @Will-Beninger @papersackpuppet 

I've found a solution to the - 
    
> TypeError: Cannot read property '$on' of 

problem.

Instead of 
```javascript
// Refetch data every time the "refresh" event is broadcast
angular.element($("#myTextPanel")).scope().$on("refresh", function() {
  refreshMyPanel();
});
```

use - 

````javascript
// Refetch data every time the "refresh" event is broadcast
angular.element('#myTextPanel').injector().get('$rootScope').$on('refresh', function() {
  refreshMyPanel();
});
````

I *think* this is down to a change between versions of angular, but I'm no angular expert so I'm not entirely sure.

**Comment by torkelo** [comment]
closing this as this can be implemented in a panel plugin

**Comment by linar-jether** [comment]
Created an HTML panel plugin, html can be fetched either by using an iframe or AJAX calls
It is also possible to pass the time range and template variable to the data source

https://github.com/jether-energy/grafana-html-panel

**Comment by maxreb** [comment]
> @yesoreyeram @Will-Beninger @papersackpuppet
> 
> I've found a solution to the -
> 
> > TypeError: Cannot read property '$on' of  undefined
> 
> problem.
> 
> Instead of
> 
> ```js
> // Refetch data every time the "refresh" event is broadcast
> angular.element($("#myTextPanel")).scope().$on("refresh", function() {
>   refreshMyPanel();
> });
> ```
> 
> use -
> 
> ```js
> // Refetch data every time the "refresh" event is broadcast
> angular.element('#myTextPanel').injector().get('$rootScope').$on('refresh', function() {
>   refreshMyPanel();
> });
> ```
> 
> I _think_ this is down to a change between versions of angular, but I'm no angular expert so I'm not entirely sure.

this doesn't work anymore with Grafana 5.4.1. With Grafana 5.3.1 everything worked properly. I didn't found anything on the changelog which could explain this, does anyone know if the refresh event, or something, has changed under the hood?

tia

**Comment by josharrington** [comment]
There is an Ajax plugin now that may fit your needs.

https://grafana.com/plugins/ryantxu-ajax-panel

**Comment by dav1dwa** [comment]
> > @yesoreyeram @Will-Beninger @papersackpuppet
> > I've found a solution to the -
> > > TypeError: Cannot read property '$on' of  undefined
> > 
> > 
> > problem.
> > Instead of
> > ```js
> > // Refetch data every time the "refresh" event is broadcast
> > angular.element($("#myTextPanel")).scope().$on("refresh", function() {
> >   refreshMyPanel();
> > });
> > ```
> > 
> > 
> > use -
> > ```js
> > // Refetch data every time the "refresh" event is broadcast
> > angular.element('#myTextPanel').injector().get('$rootScope').$on('refresh', function() {
> >   refreshMyPanel();
> > });
> > ```
> > 
> > 
> > I _think_ this is down to a change between versions of angular, but I'm no angular expert so I'm not entirely sure.
> 
> this doesn't work anymore with Grafana 5.4.1. With Grafana 5.3.1 everything worked properly. I didn't found anything on the changelog which could explain this, does anyone know if the refresh event, or something, has changed under the hood?

I got it working by using

```javascript
angular.element('grafana-app').injector().get('dashboardSrv').dash.events.on('refresh', function () {
   refreshMyPanel() 
});
```
I'm not a frontend developer, so got no idea what exactly I did here.

**Comment by NateZimmer** [comment]
So in Grafana 4, script from the default HTML panel would work. Looks like now script in the Grafana 6 panel does not work. This is unfortunate because having the script functionality allowed for infinite potential. =(

**Comment by ebm539** [comment]
@NateZimmer see https://github.com/grafana/grafana/issues/15647#issuecomment-467188187

**Comment by hayesey** [comment]
> > > @yesoreyeram @Will-Beninger @papersackpuppet
> > > I've found a solution to the -
> > > > TypeError: Cannot read property '$on' of  undefined
> > > 
> > > 
> > > problem.
> > > Instead of
> > > ```js
> > > // Refetch data every time the "refresh" event is broadcast
> > > angular.element($("#myTextPanel")).scope().$on("refresh", function() {
> > >   refreshMyPanel();
> > > });
> > > ```
> > > 
> > > 
> > > use -
> > > ```js
> > > // Refetch data every time the "refresh" event is broadcast
> > > angular.element('#myTextPanel').injector().get('$rootScope').$on('refresh', function() {
> > >   refreshMyPanel();
> > > });
> > > ```
> > > 
> > > 
> > > I _think_ this is down to a change between versions of angular, but I'm no angular expert so I'm not entirely sure.
> > 
> > 
> > this doesn't work anymore with Grafana 5.4.1. With Grafana 5.3.1 everything worked properly. I didn't found anything on the changelog which could explain this, does anyone know if the refresh event, or something, has changed under the hood?
> 
> I got it working by using
> 
> ```js
> angular.element('grafana-app').injector().get('dashboardSrv').dash.events.on('refresh', function () {
>    refreshMyPanel() 
> });
> ```
> 
> I'm not a frontend developer, so I'm not really sure what I did here.

Further to this, in Grafana 6.5.1, the following has worked for me:

```
angular.element('grafana-app').injector().get('dashboardSrv').getCurrent().appEvents.on('refresh', function () {refreshMyPanel()})
```

It should be noted that I am also not a frontend developer and I am new to Grafana (and just using it to test some things).

**Comment by MaesterZ** [comment]
> ```js
> angular.element('grafana-app').injector().get('dashboardSrv').getCurrent().events.on('refresh', function () {refreshMyPanel()})
> ```

Grafana `8.4.x`: tested with a Text panel in HTML mode and `disable_sanitize_html` set to true in configuration

Works out, thanks a lot @hayesey
