### ISSUE TITLE
Plugins: backend plugins should report the architectures they support

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18165]
As we add support for backend plugins, we need to somehow advertise what platforms are supported in the plugin.zip

In particular, there will be two kinds of backend plugin packages:
* single architecture -- like the renderer plugin for win/osx/linux.  Each platform is 50+MB
* multi-architecture -- some plugins, (like oracle) add many small binaries

I think this should be saved in `plugin.json` so we can easily inspect it.  Maybe rather than:
```
  "backend": true,
  "executable": "your-plugin",
```

We could do:
```
 "executable": {  // maybe:  native, platform, or backend?
    "windows-amd64": "somthing_windows-amd64.exe",
    "linux-amd64": "somthing_linux-amd64",
    "linux-x86": "somthing_x86",
 }
```

And maybe eventually:
```
 "executable": { 
    "any": "java --jar something.jar"
 }
```
```
 "executable": { 
    "windows": "somethign.exe" // .NET universal 
 }
```

With this information, the CLI could verify that your architecture is supported when trying to install.

Alternatively we could make the binaries follow some naming convention -- but that would require inspecting the bundle to know what platforms it supports.

**Comment by torkelo** [comment]
The naming convention for the binary is already implemented (enforces a platform suffix) but requires inspection of package files for CLI to determine , so not ideal.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
