### ISSUE TITLE
Update grafana on CentOS7

### ISSUE THREAD

**Issue by logicall** [grafana/grafana#1817]
Hello!
Today I tried to to upgrade your graphane, but at me not came of it.
At me installed
>rpm -qa | fgrep grafana
>grafana-2.0.0_rc1-1.x86_64

When upgrading getting error
>rpm -Uhv grafana-2.0.0-1.x86_64.rpm
>warning: grafana-2.0.0-1.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 3dd18bdd: NOKEY
>Preparing...                          ################################# [100%]
>        package grafana-2.0.0_rc1-1.x86_64 (which is newer than grafana-2.0.0-1.x86_64) is already installed

OS: CentOS7

**Comment by torkelo** [comment]
@logicall nothing I can do about that now, RPM does not support semver, it thinks rc1 is newer. So you have to force it to install. I will try to set rpm versions like this for future release candidates: "2.1.0-0.1rc1" then RPM can compare correctly, even though the version is ugly.

**Comment by torkelo** [comment]
I will push 2.0.1 packages instead, hope that will solve this.

**Comment by logicall** [comment]
Thank you!
