### ISSUE TITLE
Version 6.3.0-beta1 Breaks Pie Chart Plugin

### ISSUE THREAD

**Issue by briangann** [grafana/grafana#18172]
Reported issue via community site

**What happened**:

piechart panel is not rendering in current beta

**Environment**:
- Grafana version: 6.3.0-beta1
- Grafana plugins: grafana-piechart-panel

![image](https://user-images.githubusercontent.com/7364245/61457648-6cc5c180-a92e-11e9-8a86-a81e0a49781b.png)

**Comment by briangann** [comment]
verified issue with 6.3.0-beta1 and piechart-panel v1.3.6

**Comment by briangann** [comment]
error thrown: metrics_panel_ctrl.ts:223 Panel data error: TypeError: Cannot read property 'length' of null

```Panel data error: TypeError: Cannot read property 'length' of null
    at I (csv.ts:90)
    at csv.ts:115
    at Array.map (<anonymous>)
    at P (csv.ts:109)
    at f (sort_by_keys.ts:11)
    at PanelQueryState.ts:302
    at angular.js:17051
    at angular.js:17095
    at l.$digest (angular.js:18232)
    at l.$apply (angular.js:18531)
```

**Comment by torkelo** [comment]
@ryantxu any ideas?

**Comment by ryantxu** [comment]
The main issue is that importing `jquery.flot.pie` is failing.  My guess is that the grafana webpack tree shaking is dropping it -- we could update grafana so it does not drop this lib.

@briangann has also done some work to migrate to toolkit and use typescript.  See https://github.com/grafana/piechart-panel/pull/182, this fixes the issues with pie chart panel.

I don't think we need to change anything in grafana core to fix this

**Comment by torkelo** [comment]
If grafana if removing jquery.flot.pie from optimized build bundle how can this be fixed in plugin?

**Comment by xlson** [comment]
What is the status on this issue? Trying to figure out if we can do a beta2 release tomorrow.

**Comment by torkelo** [comment]
The latest plugin works, but I get some strange issue with plugin icon image

**Comment by ryantxu** [comment]
It looks like the latest release includes src and artifacts in the distribution:

![image](https://user-images.githubusercontent.com/705951/61804841-7e551080-ade9-11e9-909f-65e501fc025d.png)

this should be updated to only have this dist folder.

@xlson -- the fix for this will be in a plugin, not grafana.  so it should not block any beta release

**Comment by torkelo** [comment]
tested last version and works now
