### ISSUE TITLE
6.3.0-beta1 custom timeranges does not seem to respect UTC

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#18170]
custom timerange doesn't seem to respect UTC. dashboard has UTC set, but when i select an UTC timerange, it seems to select the timerange in local time. (because the UTC times shown are wrong)
![huh](https://user-images.githubusercontent.com/20774/61450011-6ea37b00-a956-11e9-80cd-e7fd4ecc160c.png)

**Comment by davkal** [comment]
@Dieterbe disaggregated issues. Second one is in #18178

**Comment by davkal** [comment]
can repro. setting the time in the custom range fields applies the utc values as local time, offsetting the query by 2h (for me)

**Comment by davkal** [comment]
Checked time picker input and popover, they both seem to work as expected and emit a UTC moment with the correct time.
