### ISSUE TITLE
Region annotation with source prometheus

### ISSUE THREAD

**Issue by merryjane** [grafana/grafana#18174]
We can create a region annotation via web-interface (https://grafana.com/docs/reference/annotations/#adding-regions-events) or grafana API (https://grafana.com/docs/http_api/annotations/) by parameter "isRegion":true.

If we use data source prometheus we cannot make region annotation. 
On web intarface "Annotations > Edit" for "Data source" prometheus we add search expression with bool value like "increase(updater{job="our-job"}[60s]) == bool 0" and our expression true for a long time we get sequence of single annotations with step specified on the same web-interface. It's look a little noisy.

It will be great if in annotation web-interface for "Data source" prometheus  will be added a check box like "isRegion". If "isRegion" is active then sequence of single annotations (points) while the expression is true convert to region annotation.

**Comment by ti-mo** [comment]
This would indeed be great to have! To give a visual example of the data returned by `bool`:

![image](https://user-images.githubusercontent.com/3214460/68288587-f687cf00-0084-11ea-8825-08b5a390c233.png)

This causes many `0` values to be returned from the query, though, which is inefficient for larger queries.

It would be nice if this feature would behave like alertmanager does, eg. **any** consecutive datapoints returned by the query count towards the window. Any datapoints that should not count towards the window need to be dropped by the query with `> 0`, like so:

![image](https://user-images.githubusercontent.com/3214460/68289223-09e76a00-0086-11ea-9f91-e6e035a3d72d.png)

A region can then be drawn on the graph from approx. 12:36 until 12:57. Any gaps in the series would cause separate regions to be drawn.

**Comment by secustor** [comment]
@davkal  I'm considering to look into this feature as we need here too.    
Would a PR from our side be considered to be merged?

**Comment by davkal** [comment]
@secustor  That sounds like a great feature for a contributor! I recommend sharing an outline of your implementation here first. Once that's in shape it's almost guaranteed to be merged.

**Comment by secustor** [comment]
@davkal 

The modification would happen in this file:    
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L573

The basic idea is to check if the gap between timestamps is bigger than the step of the query therfore a annotation has to be created. 

This in pseudo code:
```typescript 
annotationList: annotationEvent[ ] = [ ]

metrics.foreach( timeseries => {
const lengthOfTimeseries = timeseries.length()

if(lengthOfTimeseries <= 1) {
annotationList.push(handleAsOfNow())
} else {

var timeBlockStartIndex = 0
for( int i = 1; i < lengthOfTimeseries, i++ ) {
  // if the timeseries gap is greater than the step OR it is the last data point create an annotation
  if((timeseries[ i - 1] + step) > timeseries[ i ]  || ( i == ( lengthOfTimeseries - 1 )) {
  // create new AnnotationEvent
    var annotationEvent = new AnnotationEvent  = {
       // set values as right now.
     };
    if (( i - timeBlockStartIndex) > 1 ) {
     annotationEvent.time = timeseries[ timeBlockStartIndex ]
     annotationEvent.endTime = timeseries[ i - 1 ]
    } else {  
     annotationEvent.time = timeseries[ i - 1]
    }
   annotationList.push(annotationEvent)
   timeBlockStartIndex = i 
  }
}}})

return annotationList

```
