### ISSUE TITLE
Unclear validation error when trying to save an alert without a threshold

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#18184]
**What happened**:
When saving an alert, got a validation error that prevents the save:

![Tooltip_059](https://user-images.githubusercontent.com/1692624/61478675-fb066b80-a95f-11e9-94d4-d1588e3e21dd.jpg)

**What you expected to happen**:
The dashboard to save.

**How to reproduce it (as minimally and precisely as possible)**:
On a dashboard (dashboard has been saved), create a new panel with a data query. Then go to the alert area and create an alert. Then hit save, and the validation error happens.

**Anything else we need to know?**:
I assume this is because the panel has not been saved, and something blocks both the panel and alert saving at the same time.

**Environment**:
- Grafana version: e47546d52
- Data source type & version: testdata

**Comment by torkelo** [comment]
Think this is just a bad validation message (error is that the threshold condition is missing a value )
