### ISSUE TITLE
grafana 2 - preserve home.json on upgrade 

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#1818]
If I make a custom home.json file, on upgrade it is removed (at least from beta versions to stable)

This should be preserved similar to customized ini files. 

Better would be perhaps some kind of scheme where you can point grafana at a custom home file of your own making.

This is prett important of you make scripted dashboards, since they don't show up in the search we need to put them in a custom home with urls.

Scott

**Comment by torkelo** [comment]
@sknolin yea, this will come in Grafana 2.1 , where you can each user or organization can customize their home dashboard.

**Comment by torkelo** [comment]
for now have an post upgrade script that copies back the home.json file (that is how I solved it for play.grafana.org),  I know this is not a good solution, I really want home dashboards to be something users can specify or edit them selves (or inherit from org level), but that feature was pushed to 2.1.

**Comment by sknolin** [comment]
No problem at all, grafana is developing really nicely.
