### ISSUE TITLE
influxDB relational operators and numeric field values

### ISSUE THREAD

**Issue by jwwilhelm** [grafana/grafana#18182]
Some fields in our InfluxDB database have values of -1, 0, or 1.  I am trying to add conditional clauses to include only data where FieldValue = 1 (or 0, or -1, or any other number).  Queries including this WHERE clause do not return any data even when the value is in fact equal to the criteria entered for many entries over the queried time period.  I can make it evaluate to true by using FieldValue > 0 (or > any real number between 0 and 1), but this workaround will not suffice for all situations. Queries including the "does not equal" operator also return no data regardless of what criteria is entered.  This issue has been observed at least when the values are stored as real numbers.

**Environment**:
- Grafana version: v6.2.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: Red Hat 7
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
There's an open feature request for filtering by values using the query editor #2674 You should be able to use the raw query editor mode. If it still doesn't work this should be an influxdb issue so closing this.
