### ISSUE TITLE
DataLinks: A way to access series tags/labels in link url

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18187]
* [ ] For data sources that support tags/labels the data source should return them on the DataFrame object. 
  * [ ] Graphite
  * [ ] InfluxDB
  * [ ] Prometheus 
* [ ] Add interpoalation variable to access the tags/labels

**Comment by imageslr** [comment]
Hi, has this feature been implemented? 

I want to pass series' tag values as query params in their datalink. However currently I can only access `${__field.name}`.
