### ISSUE TITLE
CSV export first data column has a sinlgle quote ' symbol

### ISSUE THREAD

**Issue by MarkoBursic** [grafana/grafana#18196]
"Time";"Struja";"Napon";"Frekvenca"
"2019.19.07 14:48:00";"'-0.065";"0.52";"74.4"

It's diffucult to note, but excel does not parse correctly, so the exported CSV line is like this:
" time " ; " ' column1 " ; " column2 " ; " columnn3 " ; .....

See, the first column starts with double quote, then one another single quote, text , double quote.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: influxdb
- OS Grafana is installed on: Raspberry Pi3

**Comment by torkelo** [comment]
Does your column name has a quite char in the column name? 

Can you try 6.3 beta? this might be fixed

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by MarkoBursic** [comment]
Changed to version Grafana v6.3.6 (fdd2117). Problem still present
It adds a single quote when number is negative, only.

sep=;
"Time";"Struja";"Napon";"Frekvenca"
"2019.29.09 17:30:00";"'-0.007";"0.46";"96.5"
"2019.29.09 17:15:00";"'-0.007";"0.48";"102.8"
"2019.29.09 17:00:00";"'-0.006";"0.51";"94.7"

**Comment by eliotfoster** [comment]
I'm having the same issue except all the negative values have the leading apostrophe.
