### ISSUE TITLE
Grafna Table & Influxdb  order is inverted

### ISSUE THREAD

**Issue by MarkoBursic** [grafana/grafana#18190]
When I make the table with Influx database the displayed table inverts the time order:

"By default, InfluxDB returns results in ascending time order; the first point returned has the oldest timestamp and the last point returned has the most recent timestamp. ORDER BY time DESC reverses that order such that InfluxDB returns the points with the most recent timestamps first."

I get always ordered by time descending, there is no option to get the order by time ascending.

**Comment by torkelo** [comment]
Click on the time colum to change sort order
