### ISSUE TITLE
Alerting: Acknowledgement with Comment

### ISSUE THREAD

**Issue by m5b7** [grafana/grafana#18193]
**What would you like to be added**:

The possibility to acknowledge an alert and comment on it, so that others know it is being taken care of.

**Why is this needed**:

Having firing alerts without any kind of information if anyone is already taking care, might increase indifference about alerts in general.

**Comment by adeweever** [comment]
any updates on this request?

**Comment by broferek** [comment]
I'm interested to know how people deal without it ? Any possible workaround within Grafana or is it mandatory to implement an external tool to manage things like acknowledgements, manual resolution of alerts  ?

**Comment by armandgrillet** [comment]
> All alerts are then sent to the new Grafana Oncall where I can not only acknowledge but also review my persistent alerts easily.

Yes, this is how we expect people to do this.
