### ISSUE TITLE
6.2.5: remote cache redis is parsing connstr wrong and leaks password plaintext to log

### ISSUE THREAD

**Issue by mblaschke** [grafana/grafana#18199]
**What happened**:
When `connstr` contains a password with a `=` char (eg password used in Azure Redis PaaS instances) the parsing fails and also leaks the password in plain text to the container logs.
This even happens when the environment variables are used. Trible quotes are also not working.

**What you expected to happen**:
Parsing works and the password is NOT leaked to the log in case of failure.

**How to reproduce it (as minimally and precisely as possible)**:

```
[remote_cache]
type = redis
connstr = addr=127.0.0.1:6370,pool_size=100,password=foobar=
```

**Anything else we need to know?**:

The parsing is just too simple by splitting by `=` char:
https://github.com/grafana/grafana/blob/master/pkg/infra/remotecache/redis_storage.go#L25

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: not needed
- OS Grafana is installed on: Docker container on Kubernetes on Ubuntu
- User OS & Browser: Win 10, latest Chrome
- Grafana plugins: not needed
- Others:

**Comment by gotjosh** [comment]
For the future, we don't need to add the label `cherry-pick needed` to issues 😄
