### ISSUE TITLE
how do you center single panel in the page

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1819]
Hi Torkel:

I am trying to insert a html row in a dashboard and like to center the the panel in the page. I tried something like this:

<p>
<img border="0" alt="ggplot" src="img/overall.png" width="800" height="400" align="center">
</a>
</p>

Still the panel is left aligned. Is this doable, given single panel in a row?

**Comment by torkelo** [comment]
you screenshot is not working

**Comment by gsaray101** [comment]
sorry, I was able to figure out by <center> tag.thanks
