### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when login using  SSO with signup set to false and user not present in database

### ISSUE THREAD

**Issue by mvkarthikeyan** [grafana/grafana#18192]
**What happened**:
I have setup login using SSO with oauth auto login to true and allow signup for oauth false . when I tried to login using using username which is not present in grafana. It goes to ERR_TOO_MANY_REDIRECTS

**What you expected to happen**:
I wanted to error page that user is not present in grafana. if possible should redirect to signout url . If the error page is configurable that would be great . 

**How to reproduce it (as minimally and precisely as possible)**:
Step 1 :  setup generic oauth 
Step 2 :  set allow signup as true and oauth auto login as true
Step 3 : try to login using user which is not present in grafana . it will try to authorize multiple times and fail . 

**Anything else we need to know?**:
If a user is already logged in he will not be prompted for login page in the oauth implementation which i am using .  

**Environment**:
- Grafana version: 5.4.4
- Data source type & version: --
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10 & Chrome 75
- Grafana plugins:  --
- Others: --

**Comment by torkelo** [comment]
fix is already in v6.3-beta https://github.com/grafana/grafana/issues/17623
