### ISSUE TITLE
Explore: Add data source CTA should be centered

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18206]
The current CTA would look better if it was centered and with some top margin

<img width="1679" alt="Screen Shot 2019-07-21 at 09 32 58" src="https://user-images.githubusercontent.com/10999/61588369-a4d13c80-ab9a-11e9-97c6-3201d918070a.png">

**Comment by devdil** [comment]
@torkelo that sound's like a good suggestion. I am willing to work on this issue.

**Comment by devdil** [comment]
@torkelo I just build a new version of master currently at Grafana v6.4.0-pre (commit: 64828e017),
it looks the issue is fixed .

![Screen Shot 2019-07-28 at 11 00 00 PM](https://user-images.githubusercontent.com/5098875/62010683-959a5200-b18b-11e9-8f11-e821b983dadf.png)
