### ISSUE TITLE
Panels only load as you scroll down the page, doesnt fully load in chroium headless for pdf export

### ISSUE THREAD

**Issue by raymondfeliz** [grafana/grafana#18203]
Is there a way to enable a dashboard to fully load all of its values upon loading the page like previous versions?

**What happened**: Updated to 6.2.5 , this version now only loads panels as you scroll down the page, which makes for a better user experience in the web ui, but I couldnt find a flag or option to disable this feature, as when I attempt to load a chromium headless session to generate a pdf im unable to load the full page

**How to reproduce it (as minimally and precisely as possible)**: 

Load 6.2.5 with a long dashboard of 15+ vertical panels. Wait 10 seconds and then start scrolling down, you will see the panels start to load, when previously they would load upon reaching the page.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Zabbix + elasticsearch
- OS Grafana is installed on: Centos 7.6
- User OS & Browser: Chromium Headless + Chrome
- Grafana plugins: Stock plugins

**Comment by torkelo** [comment]
ok, we try to find a way to fix this soon, we will work on reporting soon and then we will add official support for full dashboard png/pdfs:

https://github.com/grafana/grafana/issues/9883
