### ISSUE TITLE
/etc/init.d/grafana-server on Ubuntu 14.04

### ISSUE THREAD

**Issue by srfraser** [grafana/grafana#1820]
Using grafana_2.0.1_amd64.deb installed on Ubuntu 14.04,

    # /etc/init.d/grafana-server start
     * Starting Grafana Server  
                                                                         [fail]
                                                                         [ OK ]

grafana-server is not started. 

Running grafana-server manually works, specifying the pidfile and config that the init.d script does, and that populates the pidfile. When using init.d/grafana-server the pidfile is always empty.

In addition, when the pidfile is stale (for example, starting grafana-server by hand, then killing it), the init.d script loops endlessly: 

    # cat /var/run/grafana-server.pid 
    9862# ps -ef | grep 9862
    # 
    # /etc/init.d/grafana-server start
    * Starting Grafana Server                                   
                                                                         [fail]
                                                                         [fail]
                                                                         [fail]
                                                                         [fail]
                                                                         [fail]
                                                                         [fail]
                                                                         [fail]
                                                                         [fail]

**Comment by torkelo** [comment]
not endlessly it will time out after a while :) 

To troubleshoot why it wont start, edit the init.d script: 
Line 81:
start-stop-daemon --start -b --chdir "$WORK_DIR" --user "$GRAFANA_USER" -c "$GRAFANA_USER

Remove the -b line   

or you can see if you have any logs in /var/log/grafana 

It is probably some permission thing. Is this an upgrade from a previous beta, or a clean install, any config changes?

**Comment by srfraser** [comment]
Good call with -b, that allowed the error messages through. 

I'd removed a beta version of grafana.  I used `dpkg -r grafana`, `rm -fr` the relevant directories _including_ /var/log/grafana - I just double checked my history to make sure, and the command is there. Nevertheless, it was owned by root:root and grafana couldn't write to it. 

Changed those permissions and now it starts. Thank you!

**Comment by torkelo** [comment]
Great that you solved it so quickly!
