### ISSUE TITLE
Docs feedback: auth/generic-oauth.md

### ISSUE THREAD

**Issue by mbrugger** [grafana/grafana#18207]
allow_sign_up should be explained in the documentation, initially I set it to false as it was not clear to me that this has to be set to true otherwise no new user (only existing in the idp) could log in using oauth

**Comment by ClintyB** [comment]
https://github.com/grafana/grafana/issues/18207#issue-470754593

**Comment by marti1125** [comment]
Hi I am interesting in this issue. Could you tell me more, where I have to modify, please ?

**Comment by mythtargaryen** [comment]
i am fresh

**Comment by marcusolsson** [comment]
I believe he refers to the documentation on [Generic OAuth](lhttps://github.com/grafana/grafana/blob/master/docs/sources/auth/generic-oauth.md).

**Comment by mbrugger** [comment]
Hi, sorry for the late response. Yes I was talking about the documentation. It does not explain the function of this parameter anywhere. (and imho the whole parameter does not make much sense in combination with oauth)

**Comment by marcoboffi** [comment]
> allow_sign_up should be explained in the documentation, initially I set it to false as it was not clear to me that this has to be set to true otherwise no new user (only existing in the idp) could log in using oauth

Sorry I don't understand meaning of _"only existing in the idp"_.   If allow_sign_up=false, should  I pre-create user manually?

**Comment by rodrigocastrillon** [comment]
> > allow_sign_up should be explained in the documentation, initially I set it to false as it was not clear to me that this has to be set to true otherwise no new user (only existing in the idp) could log in using oauth
> 
> Sorry I don't understand meaning of _"only existing in the idp"_. If allow_sign_up=false, should I pre-create user manually?

Hello. No, you just need to set allow_sign_up=true. This will allow Grafana to automatically create the user accounts locally when they're authenticated against the provider.

**Comment by mbrugger** [comment]
> > > allow_sign_up should be explained in the documentation, initially I set it to false as it was not clear to me that this has to be set to true otherwise no new user (only existing in the idp) could log in using oauth
> > 
> > 
> > Sorry I don't understand meaning of _"only existing in the idp"_. If allow_sign_up=false, should I pre-create user manually?
> 
> Hello. No, you just need to set allow_sign_up=true. This will allow Grafana to automatically create the user accounts locally when they're authenticated against the provider.

@rodrigocastrillon sorry for not getting back sooner. yes this is exactly what the documentation should say. Even if you use an external identity provider this flag (allow_sign_up) needs to be configured to true and this is counter intuitive to me at least.
I would expect this flag to do what it says -> allow new users to sign up themselves which I actually do NOT want especially if I am using an external identity provider.

**Comment by achatterjee-grafana** [comment]
Looking at the https://grafana.com/docs/grafana/latest/auth/generic-oauth/ topic, the "allow_sign_up" property is always shown as set to true. Is there anything more needed @mbrugger? If not, we can close the issue. Thanks!
