### ISSUE TITLE
Shorten names in legend when using aggregate functions

### ISSUE THREAD

**Issue by tharris104** [grafana/grafana#18202]
**What would you like to be added**:
Either an option to hide the function being used in the legend or remove it completely. This was sort of requested previously.. But the answer there is only for graphite.. I am using influx as storage and when using the $col alias, I am getting the really long "non_negative_difference_metric_name" for every stat. 
> https://github.com/grafana/grafana/issues/464

![Screenshot at 2019-07-19 14-07-21](https://user-images.githubusercontent.com/17254429/61555944-8cdcaa00-aa2e-11e9-9eed-28d725ae2639.png)
![Screenshot at 2019-07-19 14-01-23](https://user-images.githubusercontent.com/17254429/61555893-67e83700-aa2e-11e9-960a-0f7a95f9cbd4.png)

**Why is this needed**:
Legend is too big and I can't think of a use case where I would want the function as part of the name :D

**Comment by torkelo** [comment]
This currently a limitation in InfluxDB where I appends the function before the measurement , you can use the AS xxx syntax to change this name.

**Comment by beingyash** [comment]
I have the same issue of long legend names in case of elsaticsearch datasource. Can't seem to find a way to trim/interpolate the aggregation series name.

**Comment by beingyash** [comment]
Found a weird workaround for a specific case of Bar Gauge panel. In visualization options in bar gauge panel, the 'title' accepts the ${__series.name} system variable, which somehow supports the syntax ${__series.name[x]}. Here 'x' is the positional parameter you pass for your metric name string's alphabet. So, concatenating multiple ${__series.name[x]} variables gives you your metric name but there's a challenge involved. If there are two series names with different alphabet cound in their names, then once the name with less alphabets is completed, if you add more ${__series.name[x]} variables in that title box to complete the other series name, the shorter series name starts to display the raw variable ${__series.name[x]}.

Hence, this doesn't even feel like a workaround, and it completely useless except when you have metric names with exact alphabet counts.
