### ISSUE TITLE
gzip compression breaks dashboard import

### ISSUE THREAD

**Issue by bitc** [grafana/grafana#18208]
This is similar to older issues: #1675 #5952 #9464 #9476
But this still happens in latest version of Grafana (2.6.5)

Running grafana behind nginx reverse-proxy, with grafana setting `enable_gzip = true`

When trying to import a dashboard, the following shows up in nginx error.log:

```
2019/07/21 16:42:35 [error] 12352#12352: *2013 upstream prematurely closed connection while reading upstream, client: 123.45.123.45, server: grafana.example.com, request: "GET /api/gnet/dashboards/1860 HTTP/2.0", upstream: "http://127.0.0.1:3000/api/gnet/dashboards/1860", host: "grafana.example.com", referrer: "https://grafana.example.com/dashboard/import"
```

(and Chrome gives an error `Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR`)

All other grafana functionality (besides dashboard import) seems to work. When I set `enable_gzip = false` then the bug goes away

**Environment**:
- Grafana version: 6.2.5
- OS Grafana is installed on: Ubuntu 18.04
- Others: nginx 1.14.0

**Comment by torkelo** [comment]
if you have gzip enabled and access Grafana directly (without going through nginx) does it still give same error?

**Comment by apple-fan-pl** [comment]
> if you have gzip enabled and access Grafana directly (without going through nginx) does it still give same error?

Accessing directly meaning filesystem, so via SSH. So there is no f* way ssh (console/text) displays webpage, as SSH is not webbrowser......

**Comment by torkelo** [comment]
???

Your using nginx , what if you access directly grafanas http server without going through your nginx proxy

**Comment by bitc** [comment]
> if you have gzip enabled and access Grafana directly (without going through nginx) does it still give same error?

No error. If I access Grafana directly from chrome then dashboard import works (with `enable_gzip = true`)

So the problem is with the communication between grafana and nginx.

- Either grafana has a bug and is returning a slightly malformed response that nginx chokes on.
- Or nginx has a bug and is choking on a valid (but unusual) response from grafana.

**Comment by apple-fan-pl** [comment]
@torkelo 

NO nginx will contaminate my MacBook, sorry

**Comment by torkelo** [comment]
? 

Closing this as it looks to be a nginx config issue

**Comment by pythonwood** [comment]
thanks this issue.  I got this error if both nginx gzip and grafana gzip enable.
so doc should take care about it.
