### ISSUE TITLE
Filtering Options

### ISSUE THREAD

**Issue by mahima2112** [grafana/grafana#18209]
On selection of one option from a dropdown in Grafana, can we query in such a way that the other dropdown options filter out suitably? Like a key value pair thing.

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: InfluxDB
- User OS & Browser: Ubuntu and Google Chrome respectively

**Comment by torkelo** [comment]
yes, you can use variables in the query of other variables (nest them, and create a hierarchy)

Example; 
https://play.grafana.org/d/000000002/influxdb-templated?orgId=1
