### ISSUE TITLE
Statistics for Plugins/Datasources

### ISSUE THREAD

**Issue by mstaalesen** [grafana/grafana#18200]
**What would you like to be added**:
It would be very nice to have statistics for how many dashboards are using a given plugin or datasource in Grafana. 

**Why is this needed**:
To ensure that datasources or plugins are being used, and by how many dashboards. This makes it easier to know when / if a datasource or plugin can be upgraded (or removed) without affecting anyone.

**Comment by daniellee** [comment]
The Usage Insights feature in Grafana Enterprise will include this feature so no plans to add this to open source Grafana in the near term but it might get added in the future.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
