### ISSUE TITLE
Admin: Audit log for important changes 

### ISSUE THREAD

**Issue by mstaalesen** [grafana/grafana#18201]
**What would you like to be added**:
It would be vey nice if we could have logs for the changes that an admin has done. Example: In our org, one of the administrators changed the name of a data source. This lead to all alerts faulting because the datasource was no longer there. It took some time to determine who that person was, because nothing appeared in the logs.
**Why is this needed**:
Troubleshooting who did what is quite painful right now.
Also, if an admin user where to be compromised, there is no way to check that right now.

**Comment by apple-fan-pl** [comment]
> Also, if an admin user where to be compromised, there is no way to check that right now.
In this case there always is a way to check whats going on...... its '/var/log' :)

**Comment by mstaalesen** [comment]
> > Also, if an admin user where to be compromised, there is no way to check that right now.
> 
> In this case there always is a way to check whats going on...... its `/var/log` :)

While I agree to some extent, parsing /var/log when running grafana in high availability makes it a bit harder to determine what happened on what server. Of course you could use ELK or Splunk to aggregate the logs, but I don't think Grafana should rely on other tools for audit logging.

**Comment by sriharshabm** [comment]
Support for audit log is required feature. Could you please help us in implementing this feature.
