### ISSUE TITLE
Embed snippet offered in UI even when embedding is disabled

### ISSUE THREAD

**Issue by tiberiuana** [grafana/grafana#18219]
Even when embedding in an `<iframe>` is disabled (by `allow_embedding = false`), the UI still offers the option and generates a broken snippet that does not work.

How to reproduce it (as minimally and precisely as possible):

Go to the menu of some panel, selected "share".
Go to the "embed" tab and copy-pased the HTML snippet.
Paste that into some other website and load it.
What happened:
The iframe does not work, it remains empty.

What you expected to happen:
The iframe should load.

Anything else we need to know?:
The reason it does not load is that Grafana sets X-Frame-Options: deny.
Seems that can be solved with allow_embedding = true in the [security] section, but the web UI I described above does not say that this will not work unless the admin changes the settings.

Environment:

Grafana version: 6.2.2
OS Grafana is installed on: Debian
User OS & Browser: Debian, Firefox
Grafana plugins:
Others:

**Comment by torkelo** [comment]
The UI should have an info message about this setting. On mobile now so can’t check. Can you check Ui again?

**Comment by tiberiuana** [comment]
I don't have a local instance handy, so I've tried this on Grafana Cloud -- this is what the Embed dialog looks like. No mention of iframes not being supported.

https://i.imgur.com/CZbLJ2G.png

**Comment by torkelo** [comment]
Your right there is no mention of this there.

**Comment by koshisan** [comment]
I wish this was the same for me... I am on Grafana 7.5.2, have enabled the allow_embedding = false option, but I am missing the tab in the GUI and there seems to be no setting to enable it...
(Only seen it on screenshots)
