### ISSUE TITLE
@timestamp issues

### ISSUE THREAD

**Issue by szymQL** [grafana/grafana#18210]
I'm using Logstash Elasticsearch Grafana stack to watch for my logs, but Grafana shows bad timestamps on graph. When i check in elastic i can see every document has my desired timestamp taken from log file, but still grafana uses time of logs thrown into elastic by logstash. When i'm monitoring older files (which were monitored continously), it's ok, because time of stashing is  almost the same as logtime. But when i want to use new file with for example 500 logs already written ( with new .conf, filter etc.) i see peak of 500 logs with time of logstash start, and later it's fairly ok, because as with older files, stashing time is same as logtime. If someone had this problem or know what i'm doing wrong, please help. (There is no other timestamp field in my elasticsearch mapping)
![image](https://user-images.githubusercontent.com/48645607/61614503-32c52a00-ac64-11e9-8d9c-26a6ef6b3932.png)
Yellow line is peak what i mentioned. Older logs from file get thrown with one timestamp on graph.
![image](https://user-images.githubusercontent.com/48645607/61614574-5a1bf700-ac64-11e9-8e0c-1814f49eec13.png)
Logstash v7.2.0, ElasticSearch v6.4.0, Grafana v5.3.4

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
