### ISSUE TITLE
Graph: Bar placement option to have it placed before data point

### ISSUE THREAD

**Issue by fxmiii** [grafana/grafana#18220]
**What happened**: Bars are displayed on the wrong side of the data point on a prometheus query with the rate() or increase() functions.
![barsOnWrongSide](https://user-images.githubusercontent.com/51002364/61648446-72e4d680-ac7d-11e9-848b-fbfcb126b1a2.PNG)
In the Image above both panels have the same query: 'increase(myPrometheusCounter[$__interval])’. The top panel has no ‘min step’ so it shows with each spike a tick-up increase in the counter.
The bottom has a ‘15m’ min step and is set to ‘bar’ and not ‘line’ graph. Notice how the queried data points from Prometheus are at 10:00, 10:15, 10:30 etc. Counter increases that happened between 11:15-11:30 are at the 11:30 datapoint. And that bar sits from 11:30-11:40.5

**What you expected to happen**: Bar to sit within the time interval that the data came from

**How to reproduce it (as minimally and precisely as possible)**: Use increase() or rate() on a prometheusCounter[$__interval] and use a large 'min step' to make large intervals to make it easy to see.

**Anything else we need to know?**:

[From Docs](https://prometheus.io/docs/prometheus/latest/querying/basics/#range-vector-selectors)
> Range vector literals … select a range of samples back from the current instant. Syntactically, a range duration is appended in square brackets ([]) at the end of a vector selector to specify how far back in time values should be fetched for each resulting range vector element.

So my ‘increase(myPrometheusCounter[15m])’ will return the counter delta from each datapoint back 15 minutes.

**Environment**:
- Grafana version: v6.2.4, v5.4.3

- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu and Docker on Ubuntu
- User OS & Browser: Windows and Ubuntu Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Currently, the bar graph rendering places the bar to the right of the data point and there is no option to align the bar to the left side of the data point.

**Comment by torkelo** [comment]
Changed title and marked this a feature request for a new graph option

**Comment by fxmiii** [comment]
Am I correct that Prometheus being 'past-aligned'(intervals of data get timestamp of the end of the interval) is the reason for this?

I realize that not all databases return results that are  'past aligned'/'right-aligned' (Is there a term for this?) and that more SQL-like query languages like influx should be the other way around where the interval of data will have a timestamp (and thus datapoint) at the start of the interval.

So if this is true wouldn't one not need a new feature to select but instead always want Prometheus bars to be displayed on the left side of the datapoint? 

Thanks

**Comment by fxmiii** [comment]
I do realize that the graph panel is used across datasources and this might not be trivial to accomplish.

**Comment by valyala** [comment]
There is a workaround - to add offset matching the value in square brackets:
```
increase(myPrometheusCounter[15m] offset 15m)
```

**Comment by DrJosh9000** [comment]
> There is a workaround - to add offset matching the value in square brackets:
> 
> ```
> increase(myPrometheusCounter[15m] offset 15m)
> ```

That's not a workaround - using offset shifts the bars on the graph further to the right, and PromQL deliberately does not support negative offsets.

**Comment by dprokop** [comment]
This is now supported in our new time series panel that will be released in 7.4- it will be possible to configure the line interpolation mode.

**Comment by leeoniya** [comment]
@torkelo @dprokop so this looks like a temporal histogram ro me.

the bars pathbuilder in uPlot 1.6 now has an `align` option which can be used to get an effect similar to stepBefore/stepAfter, see bottom 2 demos here: https://leeoniya.github.io/uPlot/demos/line-paths.html

we don't currently expose the bar width option, but if set to 100%, i think may then solve this case?

the one issue with aligning bars to either left or right, is that either the first or last bar will be completely clipped off by the chart edge. if the scale range is not properly expanded to accommodate.

**Comment by dprokop** [comment]
@leeoniya I'll experiment with this later this week

**Comment by ruuda** [comment]
#30499 now allows us to fix this for bar charts, but histograms still suffer from the same issue. If you have a query like `increase(metric_bucket[$__interval])`, sampled at time _t_, it returns the increase over a window of time with duration `$__interval` that ends at time _t_. But then when Grafana displays this, it renders the histogram cell as a rectangle of duration `$__interval` _starting_ at time _t_. Adding a time shift in the query settings, or `offset` in the query, doesn’t work because the time shift would need to be negative. Would it be possible to change this in the histogram renderer?
