### ISSUE TITLE
New measurement not found with query 

### ISSUE THREAD

**Issue by juliaschell** [grafana/grafana#18225]
I have a Grafana board tracking an InfluxDB database for a while now (untouched for a few months). I'm trying to get it up and running again and add a new dashboard, so I added a test measurement, tag, and value using the InfluxDB CLI and it shows up when I query for it: 

curl -u "usr:psw" -G 'https://my.endpoint.com:8086/query?pretty=true' --data-urlencode "db=MY_DB" --data-urlencode "q=SHOW MEASUREMENTS"

has my new measurement "test" in the list and 

curl -u "usr:psw" -G 'https://my.endpoint.com:8086/query?pretty=true' --data-urlencode "db=MY_DB" --data-urlencode "q=SELECT * FROM test"

shows 

{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "test",
                    "columns": [
                        "fieldKey",
                        "fieldType"
                    ],
                    "values": [
                        [
                            "val1",
                            "float"
                        ]
                    ]
                }
            ]
        }
    ]
}

When I go to add a query for this new measurement to a new grafana dashboard, however, the new "test" measurement does not appear on the list (though all the old ones are there) and is not getting any results via the grafana UI 

**Environment**:
- Grafana version: v6.0.0
- Data source type & version: InfluxDB 
- OS Grafana is installed on: MacOS
- User OS & Browser: Safari 
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
maybe a different Influx database name configured in the data source settings page? 

You can inspect the query grafana sends an influx response. Grafana has no caching and is returning what Influx is returning, so this is likely just a config issue
