### ISSUE TITLE
CloudWatch - Problem using Credentials file with IAM Role

### ISSUE THREAD

**Issue by motobeats** [grafana/grafana#18223]
**What would you like to be added**:
Support for Switching to an IAM Role for the CloudWatch datasource
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html
**Why is this needed**:
How our AWS is administered. I log in as a user then switch roles to read/write/etc.. 
For aws cli this takes the form below which requires the use of the `config` file in addition to the `credentials` file:
    `aws cloudwatch list-metrics --profile <profile name>`

**Comment by torkelo** [comment]
IAM role is already supported, what more do you need?

**Comment by motobeats** [comment]
From the logs when using the Credentials File option.

`t=2019-07-22T14:32:37-0400 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Failed to call cloudwatch:ListMetrics, AccessDenied: User: arn:aws:iam::<my account>:user/<my user name> is not authorized to perform: cloudwatch:ListMetrics\n\tstatus code: 403, request id: ..."`

My intent is not for Grafana to make the aws request with my credentials but rather switch to a role to make the request. Example details used by aws cli are contained in the config file.
>  [profile default]
> output = json
  region = us-east-1
  role_arn = arn:aws:iam::"my account":user/"my user name"
  [profile lab]
  output = json
  region = us-east-1
  role_arn = arn:aws:iam::"account":role/"role name"
  source_profile = default

So for this example from the cli it would be `aws cloudwatch list-metrics --profile lab` for the cli to use my credentials to authenticate and then make the request as the assumed role in the lab profile.

**Comment by johnewing1** [comment]
Have you specified the role Arn in the data source config ?
If you want to do this the EC2 / ECS container you are running grafana in needs to have permission to assume the role ( e.g. `lab` )  you are using for Cloudwatch access.

**Comment by motobeats** [comment]
This is for a use case of Grafana server being outside of AWS. So `ARN` option wouldn't apply. For us the access key in `credentials` only provides a login to AWS. To actually do anything need to switch to a role as defined in the `config` file. Access keys cannot be created by our roles so they cannot be used to directly authenticate to AWS. AWS CLI handles our weirdo (secure?) setup with the `--profile` switch.

I don't see how Grafana could use this style of access to AWS without needing a `config` file with the profile details (and I've tried). 

For our Grafana on an EC2, I use the `ARN` without issue.

**Comment by johnewing1** [comment]
When configuring with the credentials file provider, did you enter `lab` as the credentials profile name ?

**Comment by motobeats** [comment]
I tried 'lab' as well as the arn for the IAM role to use.

But from grafana.log I see that the request is being made as my IAM user. So the datasource code is not switching to the role contained in the `lab` profile prior to hitting the CloudWatch API.

This is what AWS calls cross-account roles. My IAM user is part of one account but the role is in another.

**Comment by torkelo** [comment]
Maybe this is not supported in the AWS sdk lib when using credentials file?

**Comment by motobeats** [comment]
Correct. SDK looks for supporting info in the `config` file when `--profile` option is invoked. I tried adding the extra info to the `credentials` file but it didn't get used. Request to AWS was still made with my IAM user account and not the role defined in the `config` profile.

**Comment by heflin** [comment]
Same issue here, and I was confused by the wording on the datasource panel. I assumed that the `Credentials profile name` field was just the spot to enter which profile I wanted. I also tried specifying the profile via the `AWS_PROFILE` environment variable, but that failed as well.

**Comment by rkno82** [comment]
I've also invested some time into debugging this issue and finally found that open issue.
Could we, atleast, make a note into the documentation that was config/ credential file support for switching roles is not supported currently?

**Comment by sunker** [comment]
Role switching is not supported. Docs updated

**Comment by rkno82** [comment]
Do you plan to support this in the future? Because the #19706 will close that issue?

**Comment by sunker** [comment]
Not at the moment @rkno82.
