### ISSUE TITLE
second alert same dashboard

### ISSUE THREAD

**Issue by holiiveira** [grafana/grafana#18222]
**What happened**:

No alerts have been issued.

**What you expected to happen**:

That an alert be issued.

**How to reproduce it (as minimally and precisely as possible)**:

Set an alert for a chart that I have at least two series, do a series trigger the alert (alert occurs), then make another series trigger the alert (not occur).

**Anything else we need to know?**:

Example:

![example](https://user-images.githubusercontent.com/4368491/61656204-9e27ef80-ac96-11e9-8a32-ae24dc34eaf5.PNG)

If any value is `<1 or >2` the alert occurs.
In this example the series (in blue) was the first that generated alert (all right), the second (in green) should have generated the alert.

This would be a bug or a feature of the system?

**Environment**:
- Grafana v6.2.5 (commit: 6082d19)
- Elasticsearch 7.0.0
- Server: Ubuntu 18.04 LTS
- Client: Windows 10 Enterprise - Google Chrome 75.0.3770.142

**Comment by kylebrandt** [comment]
Alerting is not currently per series (see [Multiple Series in Alerting documentation](https://github.com/grafana/grafana/issues/17520)).

This would be a nice feature to have - https://github.com/grafana/grafana/issues/17520
