### ISSUE TITLE
Zabbix plugin problem with Direct DB connection

### ISSUE THREAD

**Issue by LukyGregor** [grafana/grafana#18226]
Hi, I created MySQL as a data source. It was tested successfully. Then, I configured the Zabbix plugins with a direct DB connection. I enabled the direct connection and chose MySQL as a data source. Then, I saved it and it wrote notice: " Zabbix API version: 3.4.15". When I refresh the page or open configuration Zabbix plugin, Direct DB connection is disabled. It writes none the error.

Grafana 6.2.5
Zabbix version: 3.4.15
Zabbix plugin: 3.10.2

Thanks.

**Comment by torkelo** [comment]
can you report that here. https://github.com/alexanderzobnin/grafana-zabbix
