### ISSUE TITLE
Rendering: Configureable concurrent render limits

### ISSUE THREAD

**Issue by JulianHelms** [grafana/grafana#18230]
**What would you like to be added**:
It is possible to change the hard coded concurrent_limit of 30 to a configureable limit via grafana.ini?
https://github.com/grafana/grafana/pull/13401

File:
pkg/api/render.go:
53         ConcurrentLimit: 30,

**Why is this needed**:
i do not need to fork grafana to change this value. 
I do not use the alerting/notifier functions and have to render more than 30 images simultaneously. A Grafana Cluster with RR is way to oversized for my deployment. If i have to render like 120 images i need a cluster of at least 5 nodes to handle the requests "maybe" without errors.

Another problem is the http return value if the api requests run in that limit. It does not result in "HTTP/1.1 200 OK". So there is no chance to get rid of the "bad" images.

best regards
Julian

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
