### ISSUE TITLE
Change Default Org

### ISSUE THREAD

**Issue by dahendel** [grafana/grafana#1823]
Is it possible to change the default org users are assigned to when they create accounts? I am sure it is trivial and I may have overlooked it in docs, but I could not find a way to do it.

**Comment by torkelo** [comment]
No, right now that is always the organization with orgId = 1.

**Comment by torkelo** [comment]
Is there are reason for wanting to change it?

**Comment by whisk3y** [comment]
I made an Org and some dashboards and realized that for every user I had signup I would have to go in and manually assign them to that Org. It isn't a huge deal I can just import my dashboards into the default one and problem solved. Again just curious.

**Comment by agilgur5** [comment]
+1, especially since the organization with orgId = 1 is created by default by Grafana ("Main Org."). Also #2068 is a duplicate of this

**Comment by jcmartins** [comment]
+1, I have this problem with Google Authentication. Maybe you can incluse a Organization in the google auth link anonymous

**Comment by pokemane** [comment]
+1.  Annoying when making use of several orgs with even low rates of member turnover

**Comment by dekhtyarev** [comment]
+1

**Comment by olivermc1** [comment]
+1

**Comment by daveselan** [comment]
We could do with the ability to change the default Org to another orgid other than 1 for new users. Over time, we have several older orgids, but now our "main" orgid for new users is 6 (in our case). We use ldap and have many new users logging in and orgid 1 is only used by a handful of original developers.
This would be a great if simple feature to have!

**Comment by jcmcken** [comment]
Similar use case here. We originally created an 'admin' dashboard at orgId = 1. Now we want new OAuth users to sign in and be sent to a generic, high-level dashboard (not the admin dashboard). There doesn't seem to be a simple way of accomplishing this.

**Comment by erniek** [comment]
+1

**Comment by dleutnant** [comment]
+1

**Comment by jcmcken** [comment]
@dleutnant I don't think it's a duplicate. The referenced issue seems to be about autogenerating an organization on Grafana setup without having to configure one yourself. This issue is about setting the auto-assign org to a specific org that already exists (instead of just setting it to orgId = 1)

**Comment by dleutnant** [comment]
@jcmcken Agreed. Eventually _related_ is more precise (instead of _duplicated_).

**Comment by carlislk** [comment]
Any updates on this issue? I have a similar use case as mentioned above and this feature would make managing users much easier.

**Comment by marefr** [comment]
Fixed by #12401
