### ISSUE TITLE
Grunt unable to do webpack:dev build step

### ISSUE THREAD

**Issue by mtanatwine** [grafana/grafana#18232]
**What happened**: Receiving the following error when running grunt to build the assets:
Running "webpack:dev" (webpack) task
Warning: Cannot read property 'options' of undefined Use --force to continue.

**What you expected to happen**: Successfully complete the step.

**How to reproduce it (as minimally and precisely as possible)**: Build using fpm-cookery on CentOS 7.5.1804 inside Docker. It's quite a niche build environment, so I can provide as much information as possible as needed.

**Anything else we need to know?**: We've been using this build process since 4.5.1 and it's been working up to and including 6.0.1. Since attempting to build 6.2.5, we've been getting this error and are unable to build it. This is our build step in fpm-cookery:
`safesystem "export GOPATH=`pwd` && go get github.com/grafana/grafana ; cd $GOPATH/src/github.com/grafana/grafana && git checkout tags/v#{VERSION} && go run build.go setup && go run build.go build && sudo npm install -g yarn && yarn install --pure-lockfile && sudo npm install -g grunt-cli && grunt"`

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: CentOS 7.5.1804, node v8.16.0, grunt-cli v1.3.2, fpm-cookery v0.32.0 (fpm v1.10.2), Docker 18.09.0, build 4d60db4

**Comment by torkelo** [comment]
thanks for reporting this, have fix in this PR https://github.com/grafana/grafana/pull/18242 that removes the webpack build completely from grunt. The grunt default task is no longer the way to build frontent, use "yarn dev" or yarn "yarn start" (start will launch in watch mode), for dev builds
