### ISSUE TITLE
invalid memory address or nil pointer dereference OpenShift

### ISSUE THREAD

**Issue by jesusmah** [grafana/grafana#18231]
**What happened**:

When deploying Grafana to my OpenShift 3.11 cluster it does not work with the container outputting the following log:

```

panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c99a7]
  |  
  | goroutine 1 [running]:
  | github.com/grafana/grafana/vendor/gopkg.in/ini%2ev1.(*Section).GetKey(0x0, 0x17b8d48, 0x7, 0x3, 0x4, 0x4)
  | /go/src/github.com/grafana/grafana/vendor/gopkg.in/ini.v1/section.go:110 +0x37
  | github.com/grafana/grafana/vendor/gopkg.in/ini%2ev1.(*Section).Key(0x0, 0x17b8d48, 0x7, 0x4)
  | /go/src/github.com/grafana/grafana/vendor/gopkg.in/ini.v1/section.go:170 +0x43
  | github.com/grafana/grafana/pkg/log.ReadLoggingConfig(0xc0004a9790, 0x1, 0x1, 0xc00012a920, 0x12, 0xc000179d90)
  | /go/src/github.com/grafana/grafana/pkg/log/log.go:201 +0x55b
  | github.com/grafana/grafana/pkg/setting.(*Cfg).initLogging(0xc0004b2800, 0xc000179d90, 0x7fff8bb2d965, 0x12)
  | /go/src/github.com/grafana/grafana/pkg/setting/setting.go:1026 +0x1f4
  | github.com/grafana/grafana/pkg/setting.(*Cfg).loadConfiguration(0xc0004b2800, 0xc0004e3c78, 0x149b280, 0x1, 0x2d08438)
  | /go/src/github.com/grafana/grafana/pkg/setting/setting.go:520 +0x4d4
  | github.com/grafana/grafana/pkg/setting.(*Cfg).Load(0xc0004b2800, 0xc0004e3c78, 0x1aa80d8, 0xc0004e3c28)
  | /go/src/github.com/grafana/grafana/pkg/setting/setting.go:581 +0x61
  | main.(*GrafanaServerImpl).loadConfiguration(0xc000527570)
  | /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:172 +0xe0
  | main.(*GrafanaServerImpl).Run(0xc000527570, 0x184b1e8, 0xc000527570)
  | /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:72 +0x43
  | main.main()
  | /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:95 +0x316


```

**What you expected to happen**:

Grafana would deploy and run.

**How to reproduce it (as minimally and precisely as possible)**:

Well, I've just deployed grafana (`master` and `latest`) to an OpenShift 3.11 cluster and it didnt work. 

**Anything else we need to know?**:

Im attaching the yaml file I've used to deploy in case it is of any help.
[grafana.txt](https://github.com/grafana/grafana/files/3421150/grafana.txt)
Im following this blog post: https://blog.sakuragawa.moe/deploy-granafa-with-prometheus-and-oauth2-on-openshift/

**Environment**:
- Grafana version: `master` and `latest`
- Data source type & version:
- OS Grafana is installed on: OpenShift
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This shows you have modified the defaults.ini file which should never be done this is the definition file for all settings. 

The link you showed is doing something bad:

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: grafana-config
    namespace: "${NAMESPACE}"
  data:
    defaults.ini: |-
      [...content of the configuration...]

Not sure what image they are using, or how Grafana i started, but Grafana has two config files, one where defaults are defined (which users should not modify), and one where all settings are commented out (that can be empty and only contain changed settings)
