### ISSUE TITLE
Alert occurs error: could not find alertid

### ISSUE THREAD

**Issue by B1ur** [grafana/grafana#18245]
**What happened**:
I received an alerting msg,but no ok msg received in a long time.
**What you expected to happen**:
I should have received an ok msg after a few time,because the data looks fine,and I press the button test rule,it return ok state.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
First,I search in grafana sqlite,the table named alert,and I find the state of that alert is always ok. 
so I look into grafana's logs,and I see below:
`t=2019-07-23T22:53:51+0800 lvl=info msg="New state change" logger=alerting.resultHandler alertId=4791 newState=alerting prev state=ok`
that means the alerting event happened,and it works fine cause I receiveed the msg.
but there is an another log:
`t=2019-07-23T22:53:52+0800 lvl=eror msg="Failed to save state" logger=alerting.resultHandler error="Could not find alert"`
so,looks like the state was failed to save into sqlite,but it sended alert successfully.
Next,I check the source code of grafana:
``` 
if has, err := sess.ID(cmd.AlertId).Get(&alert); err != nil {
	return err
} else if !has {
	return fmt.Errorf("Could not find alert")
}
 ```
the var 'cmd.AlertId' is accurate,cause the value is correct in first log above.
I dont konw what happend here.
**Environment**:
- Grafana version:5.4.2
- Data source type & version:influxdb
- OS Grafana is installed on:centos
- User OS & Browser:chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you try to upgrade? We have done some improvements to sqlite DB error handling, and how we update alert state .

**Comment by B1ur** [comment]
> Can you try to upgrade? We have done some improvements to sqlite DB error handling, and how we update alert state .

emm,I will think about this .I wonder what could be the cause of this problem and is there a way to avoid this?

**Comment by hugohaggmark** [comment]
Have you tried to upgrade or have you found another solution?

**Comment by hugohaggmark** [comment]
Closing this issue for now, we can reopen it later if needed.
