### ISSUE TITLE
Keyboard shortcuts shouldn't work on the login screen.

### ISSUE THREAD

**Issue by bLiGM** [grafana/grafana#18243]
**What happened**:
Keyboard shortcuts work on the login screen, causing generally bad UI/UX as UI panels appear but the user is unauthorised to do anything with them.

**What you expected to happen**:
Keyboard shortcuts should not open any panels that require authorisation to use/Keyboard shortcuts should not work on the login screen at all.

**How to reproduce it (as minimally and precisely as possible)**:
While on the login screen with e.g. Local authentication and logged out.

Deselect the text boxes. Type "f" to invoke the search UI -- this causes the the following screen to appear:

![image](https://user-images.githubusercontent.com/8700124/61784763-2e367800-ae02-11e9-8900-a46dfef1c2b2.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 
v6.2.5
- Data source type & version:
N/A
- OS Grafana is installed on:
Centos 7
- User OS & Browser:
Centos 7:
Firefox Quantum 60.3.0esr

Windows 10:
Chrome Version 75.0.3770.142
Firefox Quantum 68.0

- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by eleijonmarck** [comment]
@bLiGM took a shot at it, which checks that the user should be loggedin.
