### ISSUE TITLE
Proxy error while building the front end 

### ISSUE THREAD

**Issue by Sarlken** [grafana/grafana#18254]
I would like to integrate a custom thema to grafana. To do that, I cloned the code from grafana library. As far as I understood from the documentation on GitHub, It is enough to run `yarn start` or `yarn start:hot` to be able to see the grafana. 

When I run yarn start, I don't get any error but also don't see anything on the browser.

But when I run the yarn start:hot, when I try to connect localhost:3333 I'm getting an error message below:

[Dev server] [HPM] Error occurred while trying to proxy request / from localhost:3333 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[Dev server] [HPM] Error occurred while trying to proxy request /favicon.ico from localhost:3333 to http://localalhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

Any help will be appreciated!

**Comment by torkelo** [comment]
You need to run backend as well, see readme for instructions

**Comment by Zemelia** [comment]
Hello, I have the same issue. backend is running, and "yarn start" command as well
![image](https://user-images.githubusercontent.com/2741024/119631990-14f51d00-be19-11eb-8bbf-da0cea0b5dcd.png)
