### ISSUE TITLE
variable ${__series_name} in Data Links is returned with prefix "series="

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#18250]
**What happened**:
The variable ${__series_name} is passed with prefix "series=".

**What you expected to happen**:
It should be provided just as a value.

**How to reproduce it (as minimally and precisely as possible)**:
![Screenshot_20190724_144806](https://user-images.githubusercontent.com/25184101/61791229-15d65580-ae22-11e9-96ee-f1812a015bfd.png)

![Screenshot_20190724_144430](https://user-images.githubusercontent.com/25184101/61791180-f0494c00-ae21-11e9-8152-9d5f412f2453.png)

**Environment**:
- Grafana version: 6.3.0-beta1
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS Linux 7
- User OS & Browser: Ubuntu 18.04.2 & Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by torkelo** [comment]
thanks for reporting this. 

Fix incoming
