### ISSUE TITLE
Docs feedback: reference/export_import.md

### ISSUE THREAD

**Issue by Gelob** [grafana/grafana#18261]
Please update the /img/docs/v50/export_modal.png picture to one representing the current modal in grafana. This way users better understand how to export for sharing externally as referenced.  

https://grafana.com/docs/reference/export_import/#exporting-a-dashboard

Current:
![](https://grafana.com/docs/img/docs/v50/export_modal.png)

Proposed:
<img width="752" alt="Screen Shot 2019-07-24 at 10 33 27 PM" src="https://user-images.githubusercontent.com/422752/61843943-468aaf00-ae63-11e9-981d-eba8ae447242.png">

**Comment by Gelob** [comment]
Yes this is still relevant.

**Comment by torkelo** [comment]
Sorry, miss configured state bot
