### ISSUE TITLE
Legend format breaks heatmap

### ISSUE THREAD

**Issue by Gambler13** [grafana/grafana#18264]
**What happened**:
I created a heatmap panel in grafana 5.4.3 which worked fine. After I upgraded Grafana to 6.2.5, my panel is broken. The bucket values don't correlate with the heatmap Y-Axis.
After some try and error I realized that the Legend is the problem.

You can see the Problem in the screenshots below

This one is without a legend. The heatmap values corrensponding with the Y-Axis. But the ordering of the bucket is horrible.
![chrome_ooWyAlRGcA](https://user-images.githubusercontent.com/24626221/61869073-12eb6b80-aedb-11e9-952d-cf9f49773e36.png)

I tried to fix the ording with `{{le}}` as legend format. Now the bucket ordering is correct, but messes up the heatmap values. (For example the +Inf bucket is empty/0, but the query inspector return me a value of ~0.25)
![chrome_rfSiOdYSfP](https://user-images.githubusercontent.com/24626221/61869072-12eb6b80-aedb-11e9-8fb1-b1e8b0f7fe90.png)

Query inspector output:
```
Object
    xhrStatus:"complete"
    request:Object
        method:"GET"
        url:"api/datasources/proxy/1/api/v1/query_range?query=sum(rate(igate_http_request_duration_bucket%7Bsvc%3D%22atma%22%7D%5B5m%5D))%20by%20(le)&start=1564039575&end=1564039575&step=15"
    response:Object
    status:"success"
    data:Object
        resultType:"matrix"
        result:Array[7]
            0:Object
                metric:Object
                    le:"+Inf"
                values:Array[1]
                    0:Array[1564039575,0.24998020990004954]
            1:Object
                metric:Object
                    le:"100"
                values:Array[1]
                    0:Array[1564039575,0.01666534732666997]
            2:Object
                metric:Object
                    le:"1000"
                values:Array[1]
                    0:Array[1564039575,0.24998020990004954]
            3:Object
                metric:Object
                    le:"200"
                values:Array[1]
                    0:Array[1564039575,0.19998416792003965]
            4:Object
                metric:Object
                    le:"300"
                values:Array[1]
                    0:Array[1564039575,0.2458138730683821]
            5:Object
                metric:Object
                    le:"400"
                values:Array[1]
                    0:Array[1564039575,0.24998020990004954]
            6:Object
                metric:Object
                    le:"500"
                values:Array[1]
                    0:Array[1564039575,0.24998020990004954]
```

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Prometheus histogram
- OS Grafana is installed on:  Official Docker image

**Comment by torkelo** [comment]
@alexanderzobnin any ideas why +inf is not working?

**Comment by alexanderzobnin** [comment]
@Gambler13 You say
>Now the bucket ordering is correct, but messes up the heatmap values. (For example the +Inf bucket is empty/0, but the query inspector return me a value of ~0.25)

But prometheus uses a [cumulative](https://prometheus.io/docs/concepts/metric_types/#histogram) histogram values. Your returned values look like (after sorting by bucket):
```
le:"+Inf" 0.24998020990004954
le:"1000" 0.24998020990004954
le:"500"  0.24998020990004954
le:"400"  0.24998020990004954
le:"300"  0.2458138730683821
le:"200"  0.19998416792003965
le:"100"  0.01666534732666997
```
As you can see, all buckets above `400` have the same value `0.24...`. That means, its real value is `0`, so heatmap looks correct.
cc @torkelo

**Comment by torkelo** [comment]
The Prometheus heatmap format expects data returned from histogram_quantile prometheus queries. 

You can try normal Time Series format in your Prometheus query and in heatmap panel options time series buckets as the data format. But don't think we support Inf in that mode however.
