### ISSUE TITLE
Table panel: No data in query editor when streaming is enabled

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#18265]
**What happened**:
In query editor I see _No data to show_ and empty panel after panel refresh.

**What you expected to happen**:
Data should be displayed when it became available.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable streaming in Splunk plugin.
2. Create new table panel
3. Add query to get some data

**Anything else we need to know?**:
This only happens in the query editor (on the dashboard it works as expected). Data appears when you start to type in query editor or do any other action with inputs, so I think it's related to angular digest (probably, digest does not happen after receiving data from observable).

**Environment**:
- Grafana version: 6.3 (master)
- Data source type & version: Splunk

**Comment by torkelo** [comment]
Strange when I try the test data source (gdev-testdata) and the Streaming scenario it shows in edit mode. 

But I did get what you describe when I tried to show annotations in the table panel.

**Comment by torkelo** [comment]
Can we close this?

**Comment by zoltanbedi** [comment]
I've tried this out with the test datasource and it worked there. I'm going to close this.
