### ISSUE TITLE
Add query param ignore_throttled to Elasticsearch datasource

### ISSUE THREAD

**Issue by aurimasplu** [grafana/grafana#18277]
**What would you like to be added**:
Add query param ignore_throttled to Elasticsearch datasource
 https://www.elastic.co/guide/en/elasticsearch/reference/current/searching_a_frozen_index.html

**Why is this needed**:
This param is needed then in newer Elasticsearch version frozen indices is used. This is especially useful with time series data.
https://www.elastic.co/guide/en/elasticsearch/reference/current/frozen-indices.html

**Comment by davkal** [comment]
We have datasource-level query params in Prometheus, for inspiration.

**Comment by Elfo404** [comment]
We decided to revert https://github.com/grafana/grafana/pull/27472 as this feature is only available in `X-Pack` and we would like to keep the plugin purely based on OSS Elasticsearch.

We are going to solve this by allowing custom query parameters to be appended to the search URL via a datasource setting.
