### ISSUE TITLE
documentation: document usage of 'mixed' datasource

### ISSUE THREAD

**Issue by aerickson** [grafana/grafana#18274]
**What would you like to be added**: 

I'd like the docs to mention usage of this feature. Particularly, how you set the source for a query. It must be done at creation time and can't be changed for existing queries.

**Why is this needed**:

This was very confusing to me and I couldn't (easily) find any mention of how to do it. I had to resort to scanning github issues and found a bug where someone described how it worked before it broke in the past.

**Comment by aocenas** [comment]
I agree that it would be great to have it documented in some way (we would love a PR for that if you have time).
