### ISSUE TITLE
Incorrect PNG URL when running docker image with port forwarding option

### ISSUE THREAD

**Issue by ma-sattari** [grafana/grafana#18278]
Hi there,

**What happened**:
Run Grafana's Docker image with port forwarding option: 
`docker run ... -p 4000:3000 ...`

Set the external_image_storage provider to local in grafana.ini to store png in local disk.
Set the  **domain** in **grafana.ini** to **monitor.mydomain.com:4000**

The rendered PNG for alert created in local disk but URL was:
`http://monitor.mydomain.com:4000:3000/public/img/attachments/mEkdqU2Lku3rK8YaKDBH.png`

**What you expected to happen**:
The generated URL should be:
`http://monitor.mydomain.com:4000/public/img/attachments/mEkdqU2Lku3rK8YaKDBH.png`

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana's Docker image with port forwarding option:
`docker run ... -p 4000:3000 ...`
And set the external_image_storage provider to local.

**Anything else we need to know?**:
Original port and docker forwarded port are both attached to image URL, only 4000 port
should be attached to the URL.

**Environment**:
- Grafana version:
 docker tag:6.2.5
- Data source type & version:
Prometheus
- OS Grafana is installed on:
Docker daemon runs on Ubuntu 18
- User OS & Browser:
Windows 10 - chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
can you show all your server options?

**Comment by hugohaggmark** [comment]
Hi @ma-sattari, I'm going to close this issue for now because of inactivity but we can always reopen it if needed. Thanks for contributing.
