### ISSUE TITLE
Support for decimal points in gauge's minimum and maximum fields

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#18285]
**What happened**:
I have a panel displaying the frequency of an electricity grid on a gauge. The minimum is 49.5 Hz and the maximum is 50.2 Hz. Measurements have 2 decimal points. The gauge correctly displays figures with 2 decimal points, but, rounds off the minimum to 49 Hz and the maximum to 50 Hz. Therefore, this also affects the colour scheme of the displayed figure.

**What you expected to happen**:
The gauge's minimum must have been marked at 49.5 and the maximum must have been marked at 50.2, regardless of units or having to multiply all figures by a factor e.g. 100, in this case, to eliminate fractions.

**How to reproduce it (as minimally and precisely as possible)**:
Use any figure having fractional minimum and maximum fields on the gauge.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: v6.2.1 (commit: 9e40b07)
- Data source type & version: PostgreSQL v11
- OS Grafana is installed on: Ubuntu 18.04.2 LTS
- User OS & Browser: Ubuntu 19.04 & Chromium Version 75.0.3770.90 (Official Build)
- Grafana plugins: nil
- Others: nil

**Comment by torkelo** [comment]
think this should be easy to fix, 

Should be here somewhere: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Gauge/Gauge.tsx

**Comment by Russiancold** [comment]
@torkelo It seems to me that actually it's here https://github.com/grafana/grafana/blob/3063ef6c2a16b81dd97b432a5302fe8a768dc755/packages/grafana-ui/src/components/SingleStatShared/FieldPropertiesEditor.tsx#L64
But I'm not sure if it's ok to just put there `toFloatOrUndefined`

**Comment by ryantxu** [comment]
@Russiancold -- see #18368, I added a `toFloatOrUndefined` function :)

**Comment by Russiancold** [comment]
@ryantxu Are you sure that  `toInteger` was there by accident? `toFloat` now will work for every dash with min and max props. Maybe it can break smth.

**Comment by ryantxu** [comment]
I'm pretty sure the integer constraint got added by accident when this component was converted to use react hooks
