### ISSUE TITLE
Timezone changes when choosing different time ranges

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#18289]
**What happened**:
I have a data source representing timestamps without a timezone, and these use Indian Standard Time (IST = UTC+5:30). I have a panel on the dashboard plotting measurements against those timestamps. My local browser time is also IST. Therefore, database timezone = local browser timezone.

The behaviour is as follows:
1.1. Dashboard time option = UTC, panels' time range = today: Last time instant plotted is shown in IST, which, therefore, matches the local time.
1.2. Dashboard time option = UTC, panels' time range = today so far: Last time instant plotted is shown in UTC, which is -5:30 and, therefore, does not match local time.
1.3. Dashboard time option = UTC, other panel time ranges that do not match local time: Last x minutes/hours (or) This week/month/year _so far_.
2.1. Dashboard time option = Local browser time, panels' time range = today: Last time instant plotted is shown in local browser time +5:30 = IST+5:30 = UTC+11:00, which is incorrect. In this case, some measurements are reported as occurring in the following day, or "tomorrow" for real-time data, for which there is no mechanism to view.
2.2. Dashboard time option = Local browser time, panels' time range = today so far: Last time instant plotted is marked at the local browser time, but the corresponding measurements are 5h 30m prior, which is incorrect.

**What you expected to happen**:
If dashboard time option in 'Dashboard settings' is local browser time, Grafana should mark database timezone as local browser time and use the same for 'so far' time ranges and 'last x minutes/hours'.
If dashboard time option in 'Dashboard settings' is UTC, Grafana should mark database timezone as UTC and use the same for 'so far' time ranges and 'last x minutes/hours'.

**How to reproduce it (as minimally and precisely as possible)**:
Use a data source featuring timestamps with no timezone, and a browser not configured with UTC. Set up a panel querying the same data source, and change the dashboard timezone setting and the time range setting one at a time ceteris paribus.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: v6.2.1 (commit: 9e40b07)
- Data source type & version: PostgreSQL v11
- OS Grafana is installed on: Ubuntu 19.04
- User OS & Browser: Ubuntu 19.04 & Chromium Version 75.0.3770.90 (Official Build)
- Grafana plugins: nil
- Others: nil

**Comment by aocenas** [comment]
Duplicate: https://github.com/grafana/grafana/issues/18120

@anirudh-ramesh Seems like this is very similar to the existing issue (even though it is for Mysql). Will close this issue as such, but if you think this is something different, feel free to reopen.
