### ISSUE TITLE
drill-down feature enhancements

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#18282]
Based on use of  v6.3.0-beta1

1. Currently one can only have a single drill-down link.  We should be able to specify more than one.
1. We currently have annotations disabled.  So the only action on a line would be drill down.  It would be nice if the mouse changed shape when a drill down was specified and one was hovering over a data point.
1. If I have an alias on my queries, the "__series_name" variable only includes what's shown on the legend. It's not the actual series as it came in to grafana.  So when we make the query, to get the cpu idle information for all hosts in a cluster
   - aliasByTags(seriesByTag('namespace=os', 'name=cpu.percent.idle.g', 'parentCluster=tstrad'), 'host') the __series_name is the host name - metric tank returns that tag / key value pairs in the response object and we want access to that as per 4 below.
1. Even though we are able to get the complete series series_name variable (if we don't use aliases) in the new dashboard, we need access to the underlying set of tags key/value pairs, returned, for example: 
   - namespace=os,name=cpu.percent.idle.g,parentCluster=tstrad,host=m1234
   - We want the ability to just pass down in the URL the series[host] value, e.g. m1234
1. If the target of a drill down is a Grafana dashboard then we need to be able to specify the from and to values as being the __value_time.  The use case being that we want to populate a table of values extracted using that exact time.  This currently doesn't work.  This is related to https://github.com/grafana/grafana/issues/11472

More detailed example use case.

Raw time Series:

Metric  : svc.numRequests
Tag Key : Host
Tag Key : Cluster
Tag Key : SvcName
Tag Key : RequestType

Query1:
groupByTags(seriesByTag('namespace=ns1', 'name=svc.numRequests', 'cluster=cluster1'), 'sum', 'host') across T0 - Tn
The above query would show me one line per host in 'cluster1' for the number of requests for a service.
Let's say 'host1' showed up with a high value at time T1. We would like to click on T1 for Host: host1 and run a different query:

Query2:
seriesByTag('namespace=ns1', 'name=svc.numRequests', 'Cluster=cluster1', 'Host=host1') ONLY for T1
I should be able to pick out all TAG k/v pairs resulting from Query 1 and plug them into Query 2 as I choose to. If I plug the Host=host1 k/v here, this query would give me all the other tags 'SvcName' and 'RequestType' for that one timestamp where the spike happened. I want to put these series in a grid and be able to sort them on the metric value.

**Comment by torkelo** [comment]
1) Think multiple drill-down links should be possible. What is the use case for multiple? 
2) How did you disable the built-in annotation creation? 
3) This is currently impossible, if you use aliasByTags or any aliasing Graphite will return that as the series name and we will Grafana will not know the original series name as that is lost in when usin the alias function. 
4) We might have to extend the interpolation engine to support something like ${__series.labels.namespace}
5) Any preferred strategy for creating a time range from a single data point time?

**Comment by shalstea** [comment]
1.  The multiple drill-down links are useful as we can use the point in time to look up in an external system both the list of processes running at that time, and log information in splunk.. so two different links.  For the team that wants details on a table in Grafana, that would potentially be 3 links.
1. I was mistaken - Annotations are not disabled.
1. OK - we will have to not use aliases if we need the underlying series attributes

For #4 and #5 above I don't know if we have an opinion on it.  I will have Sean and Vikrant review.

**Comment by torkelo** [comment]
3) even if you do not use alias the series name is not returned in a pure form, the whole query expression with functions are returned as series name (target). So would have to extend graphite return format somehow to return the list of series names that the query read from. But not sure that works with Grafana data model that only support a single series name per series

**Comment by shanson7** [comment]
Re (3): The 'name' tag will still exist. So I think that (4) will be sufficient for that.

Re (5): In our case, being able to specify a one second bump (e.g. from=123&to=124) would be sufficient, provided #11472 is fixed.

**Comment by Dieterbe** [comment]
Torkel, do we have a design doc for the drill down feature as a whole? or the original problem description somewhere? i couldn't find it. thx.

**Comment by dprokop** [comment]
@Dieterbe it's here https://docs.google.com/document/d/16ydL-yUYUSIrNyOlBQ3Y6kcQys9u-CREcwrDk5eNSU4/edit#heading=h.kzjhoxxlnrzr but the final UI changed significantly.

**Comment by torkelo** [comment]
implemented by https://github.com/grafana/grafana/pull/18918
