### ISSUE TITLE
Legend as table overlaps the graph (Grafana 2.0, Chrome 42).

### ISSUE THREAD

**Issue by golovnin** [grafana/grafana#1828]
I have a legend with many series (more than 20). And when I select in the tab "Axes&Grid" the legend option "Table", then the legend fully overlaps the graph. When I deselect the option "Table", then the legend is displayed under the graph without any problem. It worked in Grafana 1.9.

**Comment by arnaudmm** [comment]
Same here with Firefox. Issue happens only when displaying as table.

**Comment by matejzero** [comment]
+1

It looks like if row height is set to 250px, it will show full legend and, in the space left, there will be graph. If I toggle legend off and on, it comes back overlapping the graph.

**Comment by torkelo** [comment]
Yea, this was a bug in Grafana 1.9 where the legend table mode could extend the max height set for the row. This caused unaligned panels, and also caused other issues.

But I do release that this fix can cause problems, it can be solved easily in some cases by just increasing the height for the row but in other cases that might not be feasily so will likely introduce some solution to that.

**Comment by matejzero** [comment]
Ok, thanks.

I will change row heights and disable legends on graphs where I don't need them.

**Comment by arnaudmm** [comment]
But why behaviour is different when your are not in table mode ?

2015-04-21 13:05 GMT+02:00 Matej Zerovnik <notifications@github.com>:

**Comment by arnaudmm** [comment]
If anyone interested in a workaround, just add a min-height to
.histogram-chart css class

2015-04-21 14:33 GMT+02:00 Arnaud M <arnaudmm@gmail.com>:

**Comment by torkelo** [comment]
Discussion fix here https://github.com/grafana/grafana/issues/1832#issuecomment-94812687
