### ISSUE TITLE
CPU 100% at panel page.

### ISSUE THREAD

**Issue by gogoods** [grafana/grafana#18296]
- Grafana version:
Grafana/6.2.0-pre
- Data source type & version:
es 5.6
- OS Grafana is installed on:
centos
- User OS & Browser:
win10, chrome
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/3422759/62125934-1cbd0680-b301-11e9-8e33-f39c70cb363d.png)

```
could not find field in annotation:  tags
```

when  open a panel's page, the cpu goes high, and chart cannt rendered. It seems like something in page goes wrong.

![image](https://user-images.githubusercontent.com/3422759/62126019-57bf3a00-b301-11e9-8d00-5979f66c9291.png)

**Comment by torkelo** [comment]
Do you have an Elasticsearch annotation query? What is the response from this query?

**Comment by hugohaggmark** [comment]
Hi @gogoods, we're closing this issue for now because of lack of activity. It can be reopened again later if needed.
All the best
