### ISSUE TITLE
Allow default "right-y" as primary y-axis instead of "left-y"

### ISSUE THREAD

**Issue by Alives** [grafana/grafana#18291]
The most current data is on the right side, so it makes it easier to see current values if the axis is labeled on the right instead of the left.  I set all my graphs to "right-y" for this reason, but then the legend is filled with ".* (right-y)" which gets cluttered.

It would be easier to be able to specify which side the y-axis labels should be on by default so that "left-y" would require labeling in the legend instead since it would be more rare.

**Comment by aocenas** [comment]
Hey @Alives sorry but I am not exactly sure what you mean. Could you provide a picture of what your graph looks like now?

**Comment by Alives** [comment]
Here's the default view with y-axis labels on the left:
<img width="291" alt="Screen Shot 2019-07-30 at 12 32 54 PM" src="https://user-images.githubusercontent.com/565994/62148142-2295f600-b2c7-11e9-8f4f-0e7e74768f3b.png">

Here's what I've been doing, using "right-y" for my default axis labels and assigning /.*/ to right-y which makes it very easy to see what the current value is without having to put "current" as a value in the legend:
<img width="288" alt="Screen Shot 2019-07-30 at 12 32 22 PM" src="https://user-images.githubusercontent.com/565994/62148218-4822ff80-b2c7-11e9-82a3-700180cf9dde.png">

I'd like to be able to make the graph in yellow (second one with "right-y") the default for the graph or even the whole dashboard if possible.

**Comment by ryantxu** [comment]
closed by accident

**Comment by aocenas** [comment]
Right got it, probably makes sense especially in case when left-y isn't even visible.

**Comment by ryantxu** [comment]
This is now supported in the new timeseries panel
