### ISSUE TITLE
Show folder name along with dashboard name in team settings

### ISSUE THREAD

**Issue by jpmeijers** [grafana/grafana#18293]
**What would you like to be added**:
Under team settings one can choose the home dashboard. If you have multiple dashboards with the same name in multiple folders it is a guessing game which one to choose. Please show the folder name in which the dashboard is located too.

![image](https://user-images.githubusercontent.com/948278/62114799-a5af5000-b2b7-11e9-8452-201eac935c2b.png)

**Why is this needed**:
![image](https://user-images.githubusercontent.com/948278/62115046-10f92200-b2b8-11e9-859c-be918959a1e9.png)

It is unclear which "Weather station" dashboard is the correct one for this team.

**Comment by Russiancold** [comment]
Want to work on this. This will also fix same issue in organization settings

**Comment by Russiancold** [comment]
Is it ok if I will only display folder for duplicate dashboards?

**Comment by torkelo** [comment]
no, show Folder name / dash name

**Comment by Russiancold** [comment]
What If the dashboard doesn't belong to any folder? Should I omit it?

**Comment by torkelo** [comment]
Yes
