### ISSUE TITLE
Bar Guage Does not Show Drilldown Links

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#18301]
**What happened**: The bar guage element does not render drilldown links.

**What you expected to happen**: The element should display drilldown links on the top left, similar to other elements

**How to reproduce it (as minimally and precisely as possible)**: Create a bar guage element and add one or more drilldown links.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, Chrome & Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
It’s not implemented yet, there already is an issue for this

**Comment by BrandonQDixon** [comment]
Can you please link to it?  I cannot find this other issue.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/17473

The title only mentioned Gauge panel so updated title so it’s easier to find
