### ISSUE TITLE
Open new window when exploring pane metrics

### ISSUE THREAD

**Issue by marcosnils** [grafana/grafana#18308]
**Steps to reproduce**:

Go to any pane and use the `explore` option.

**Actual Result**:

Grafana will switch the to the explore view with the current values in the current tab and it'll make back navigation a very difficult to do.

**Expected Result**

Allow to set (optionally?) this behavior to open the explore view in a new window.

**Environment**:
- Grafana version: Grafana v6.2.0 (5d16da7)
- Data source type & version: Prometheus
- User OS & Browser: Chrome 
- Others:

If this is something that It can be done, it's believed to be useful and doesn't present any primary problems I can give it a try to craft a PR.

**Comment by aocenas** [comment]
Hey @marcosnils, there was an issue for how explore url works (and breaks back button) https://github.com/grafana/grafana/issues/17030 which is already fixed in 6.3.x (now in beta). If you still think having explore open in new tab as some option is valuable you can reopen this.

**Comment by marcosnils** [comment]
hey @aocenas thanks for replying so promptly. I do believe this feature would be useful in my particular case. The way that I use explore sometimes is that I go into a dashboard and I want to start playing around with the metric to get the expected output that I'm looking for. I find it a bit frustrating that the explore view just opens in the same tab as I what I end up doing is manually copying the original dashboard URL and open it in a separate pane so I don't have to go back to where I was before. 

Seems like I can't reopen this issue. If you still believe it's a valid use-case I'd like to give it a shot.

**Comment by aocenas** [comment]
@marcosnils I see now that the link to explore actually isn't a link (it is an `a` tag but does not have href and the url change is done programatically). So you cannot really do cmd-click to open it in new tab which isn't great. Reason I am reluctant to have it as some option somewhere is that first I am not sure where to put it (user preferences maybe) and second there are other "links" in the dropdown that would either work differently or would need separate option or you would open panel editor always in separate window.

To me the ideal thing would be to change them to normal links so they behave in a way people are used to and can just open it in new tab if they want to. That may be harder though as that drop down is still old angular code I think and there may be some issues with that. Will need to check whether such change makes sense at this time.

**Comment by marcosnils** [comment]
SGTM @aocenas. Shall we leave this open for the sake of visibility and prioritization?

**Comment by aocenas** [comment]
@marcosnils Yes will keep this open for now and will try to let you know whether it makes sense to do this now. Lots of us are on vacation right now so things move a bit slower right now so bear with us :)

**Comment by marcosnils** [comment]
:+1: anytime. Thanks again for such amazing stuff you're building.

**Comment by aocenas** [comment]
Hey @marcosnils sorry this took longer, I am not working on frond that that much lately so needed other opinion on this. But it seems the explore link is something we can/should fix. In current menu we actually handle [items with href correctly](https://github.com/grafana/grafana/blob/master/public/app/features/panel/panel_header.ts#L34) but the explore link is created specially [here](https://github.com/grafana/grafana/blob/269c1fb10767e1ca67670f357e3236f5f649359f/public/app/features/panel/metrics_panel_ctrl.ts#L244) the issue now is that the URL creation is async. But maybe this won't be such a problem as the menu is created after click (so already evented) and the reason it is async is it needs datasource config which is loaded from server but seems to be cached and so the promise should most of the time resolve instantly.

So if you wan't to take a look at this that would be great. If you have any questions just ping me in a comment.
