### ISSUE TITLE
endpoint name is abnormal

### ISSUE THREAD

**Issue by bfqymmt** [grafana/grafana#18311]
**What happened**:
Decimal change #
![Snipaste_2019-07-31_10-21-20](https://user-images.githubusercontent.com/12575427/62178861-153b4300-b37d-11e9-90d7-da2e4cc3470e.png)
![Snipaste_2019-07-31_10-21-58](https://user-images.githubusercontent.com/12575427/62178868-1a988d80-b37d-11e9-96b9-013e14db198a.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:grafana 6.2.5
- Data source type & version: open-falcon 0.2
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:open-falcon
- Others:

**Comment by torkelo** [comment]
Open falcon is an community plugin , please consults its authors (it’s GitHub repo).

Looks like dots is not allowed in metric names

**Comment by aocenas** [comment]
Closing this as it seems like issue with 3rd party plugin.
