### ISSUE TITLE
Enhanced href link to explore tab

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#18316]
I'm testing this in Grafana v6.3.0-beta2 and with both ElasticSearch 7.2.0 and Kibana 7.2.0 

**What would you like to be added**:
If would be great if for exemple:

1. I make a simple query in a table and i display only 3 informations to have a clear view of my logs: The timestamp, the id of my log and the description

2. I format my Table panel and i add a "render as a link" to a specific cell in my table in the "id" row.

3. I open in a second tab the Explore menu on the specific datasource i want to redirect to and write the query i need. I wrote a query with a specific log id just to check if i can found it correctly in my explore tab.

4. I copy/paste the url link from the explore tab into the "Render as a link" and replace the value of my query by the value present in the cell in the Table panel. I basicaly replace the id in the query by the content present on the "id" row in my Table panel "${__cell_0}"

5. If i click the id of the message, it redirect smoothly to the Explore menu with the query already crafter by the link generated in the Table Panel. This way you can visualise every value contain in the log that cannot be displayed in a simplified table.

BUT, if the query you are being redirected to is not the last query you write and send out in the explore tab, it will redirect you to the default Explore page without using the crafter query send out in the url link. 
It's already related to the orgID and if someone from a different orgID try to open the link it also redirect to the default page of the Explore Menu.

If i try to do this in kibana, there is no link or cookie verification because all users are in the same environment. So if i do the same manipulation but redirect to kibana with a special crafter link unstead of Grafane Explore, it's working properly. But for user experience and security, i can't let them access kibana without any user authentication (I setup it anyway but i don't want to create a user for each user who want to see the full log they want to see).

**Comment by aocenas** [comment]
This is something we are already working on as an internal linking between datasources. One current example is ability to specify internal link from loki logs to tracing datasource. We will expand this further in the future.

**Comment by davkal** [comment]
Repurposing this as a bug for now to investigate the redirect to default explore by mistake (could be related to URL format changes between Grafana versions). Might revisit this in the future for internal linking.

**Comment by aocenas** [comment]
Trying to reproduce this but don't seem to happen for me. There are few possibilities to check if this still happen:
- In case the URL itself is not parseable by explore we just throw it away and initialize with some default state. Would have to see the specific URL to check that. In that case just copy pasting the URL in a new tab should do the same thing. There isn't any mechanism that would check the last executed query or anything like that.
- You don't have to specify orgId in the url, the users orgId should be injected, if those users are from different orgIds than the question is whether they have access to the target datasource in question.
- There could have been some bug that is already fixed so please try with newer version.
