### ISSUE TITLE
Unable to add variables- Template variables could not be initiated: Cannot read property "targets" of null. 

### ISSUE THREAD

**Issue by HariPrasath7** [grafana/grafana#18314]
**What happened**: Not able to add the variables in the dashboard. While trying to add the variables in the facing the error "Template variables could not be initiated: Cannot read property "targets" of null ", 

**What you expected to happen**: Add the variables

**How to reproduce it (as minimally and precisely as possible)**: 1) Select datasource 2) select type as query 3) type the query 4) 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.2.2
- Data source type & version: Neo4j 
- OS Grafana is installed on: RHEL
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This is probably a problem with the Neo4j data source and not Grafana
