### ISSUE TITLE
@grafana/toolkit build light.scss and dark.scss failed in windows

### ISSUE THREAD

**Issue by peterhpchen** [grafana/grafana#18317]
@grafana/toolkit build `dark.scss` and `light.scss` failed in Windows OS.

It's similar to #18294 . Because the path separator is `\` in Windows, `dark.scss` and `light.scss` would be executed by multiple rules. It caused build failed.

https://github.com/grafana/grafana/blob/294eabda5be8e99a16d735b3e36b6145b45e6895/packages/grafana-toolkit/src/config/webpack/loaders.ts#L95-L112

**What happened**:
`dark.scss` and `light.scss` build failed.

**What you expected to happen**:
`dark.scss` and `light.scss` build success.

**How to reproduce it (as minimally and precisely as possible)**:
Executed @grafana/toolkit for `dark.scss` or `light.scss` in Windows.

**Environment**:
- @grafana/toolkit version: **6.4.0-alpha.42**
- User OS & Browser: **Windows 10**

**Comment by aocenas** [comment]
cc @ryantxu

**Comment by ryantxu** [comment]
@peterhpchen, can you try with @grafana/toolkit@6.4.0-alpha.44 and let me know what happens?

https://github.com/grafana/grafana/pull/18189/commits/bb33007d54e6bca9ed790c89315567836598102d

I am traveling and do not have easy access to a windows machine.  Next week, I will try to get this setup to run CI on a windows machine also

**Comment by peterhpchen** [comment]
@ryantxu , it works fine with **@grafana/toolkit@6.4.0-alpha.44** in **Windows** machine.

Thank you very much.
