### ISSUE TITLE
change the sidemenu

### ISSUE THREAD

**Issue by Yuvanjar** [grafana/grafana#18327]
**Environment**:
- Grafana version:5.4.3
- User OS & Browser:Chrome

I want to change the language of Grafana，everything is ok，but how can I change the sidemenu‘s word？to modify the .html ; .ts ; .tsx or .go?
please help me，I just wanna a little tips to help me to find the file.

**Comment by torkelo** [comment]
Change the tsx, read the building from source guide

**Comment by alisenyanyan** [comment]
> **Environment**:
> 
> * Grafana version:5.4.3
> * User OS & Browser:Chrome
> 
> I want to change the language of Grafana，everything is ok，but how can I change the sidemenu‘s word？to modify the .html ; .ts ; .tsx or .go?
> please help me，I just wanna a little tips to help me to find the file.

Can you tell me how you do this?thank you!

**Comment by Yuvanjar** [comment]
> > **Environment**:
> > 
> > * Grafana version:5.4.3
> > * User OS & Browser:Chrome
> > 
> > I want to change the language of Grafana，everything is ok，but how can I change the sidemenu‘s word？to modify the .html ; .ts ; .tsx or .go?
> > please help me，I just wanna a little tips to help me to find the file.
> 
> Can you tell me how you do this?thank you!

I change the .go file to change the sidemenu.The index.go，you can search the file and modify it. Hope it can help you.

**Comment by alisenyanyan** [comment]
> > > **Environment**:
> > > 
> > > * Grafana version:5.4.3
> > > * User OS & Browser:Chrome
> > > 
> > > I want to change the language of Grafana，everything is ok，but how can I change the sidemenu‘s word？to modify the .html ; .ts ; .tsx or .go?
> > > please help me，I just wanna a little tips to help me to find the file.
> > 
> > 
> > Can you tell me how you do this?thank you!
> 
> I change the .go file to change the sidemenu.The index.go，you can search the file and modify it. Hope it can help you.

I  tried modify this file and buit the fontend and restart grafana,but still no change.

I am not familiar with go,should I build the backend code?

Thanks for reply so quickly!!

**Comment by Yuvanjar** [comment]
> > > > **Environment**:
> > > > 
> > > > * Grafana version:5.4.3
> > > > * User OS & Browser:Chrome
> > > > 
> > > > I want to change the language of Grafana，everything is ok，but how can I change the sidemenu‘s word？to modify the .html ; .ts ; .tsx or .go?
> > > > please help me，I just wanna a little tips to help me to find the file.
> > > 
> > > 
> > > Can you tell me how you do this?thank you!
> > 
> > 
> > I change the .go file to change the sidemenu.The index.go，you can search the file and modify it. Hope it can help you.
> 
> I tried modify this file and buit the fontend and restart grafana,but still no change.
> 
> I am not familiar with go,should I build the backend code?
> 
> Thanks for reply so quickly!!
yeah you‘re right ，you need to  use " go run build.go build   "to build the backend code,then run zhe "npm run build" to enter your grafana.

**Comment by alisenyanyan** [comment]
> > > > > **Environment**:
> > > > > 
> > > > > * Grafana version:5.4.3
> > > > > * User OS & Browser:Chrome
> > > > > 
> > > > > I want to change the language of Grafana，everything is ok，but how can I change the sidemenu‘s word？to modify the .html ; .ts ; .tsx or .go?
> > > > > please help me，I just wanna a little tips to help me to find the file.
> > > > 
> > > > 
> > > > Can you tell me how you do this?thank you!
> > > 
> > > 
> > > I change the .go file to change the sidemenu.The index.go，you can search the file and modify it. Hope it can help you.
> > 
> > 
> > I tried modify this file and buit the fontend and restart grafana,but still no change.
> > I am not familiar with go,should I build the backend code?
> > Thanks for reply so quickly!!
> > yeah you‘re right ，you need to  use " go run build.go build   "to build the backend code,then run zhe "npm run build" to enter your grafana.

Thank you very much!
