### ISSUE TITLE
2.0.1 Row height autosizing

### ISSUE THREAD

**Issue by cristicalin** [grafana/grafana#1832]
In version 1.9.x the label section scales separately from the graph itself. in 2.0.1 the row scales together with the graph and the labels, this leads to a situation where you can have lots of metrics on a single graph and the labels completely overlap the graph.
![row-height](https://cloud.githubusercontent.com/assets/6627509/7252714/3b4a5a7a-e840-11e4-9066-59d8483c3426.png)

Please bring back the old behavior.

**Comment by torkelo** [comment]
working on fix (or compromise)

**Comment by torkelo** [comment]
So what do you think if the graph itself never goes below 50% height of the row height. So legends beyond that will push the row height beyond what it is configured for.

![image](https://cloud.githubusercontent.com/assets/10999/7254288/6148a46e-e842-11e4-995c-e0eedd9ea669.png)

The reason for the fix (besides getting panels to align), is to get rendered panels (via serverside phantomjs) to include the legend. With many series the legend gets clipped. 
http://localhost:3000/render/dashboard/solo/db/big-nice?panelId=5&fullscreen&from=1429043869862&to=1429045131206&width=1000&height=500

**Comment by maddenca** [comment]
Tested using nightly build and my existing dashboards with metric count that varies and works for me.  Thanks!
