### ISSUE TITLE
[Elasticsearch] Derivative of metric cannot be selected as variable in bucket script

### ISSUE THREAD

**Issue by cpmoore** [grafana/grafana#18325]
For my use case I want to show inbound and outbound network traffic on the same panel.  Inbound as a positive number, outbound as a negative number.  
I need to use a bucket script to convert the derivative of outbound traffic to a negative value.
However the derivative does not show up as an available metric in the selection box.

![image](https://user-images.githubusercontent.com/22562764/62259619-9245d700-b3d4-11e9-949c-fa6fe510ab03.png)

I would expect to be able to select the derivative in the bucket script.  Additionally the same seems to apply to the bucket script itself as well.  Meaning you cannot chain two bucket scripts together either.

- Grafana version: 6.2.5
- Data source type & version: Elasticsearch 7.2
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: Chrome

**Comment by cpmoore** [comment]
I was able to work around the issue.  I converted it to a negative number with a script on the original metric itself.  
I went the original approach because I was copying the way the graph was configured in Kibana, didn't think about this alternative originally.
![image](https://user-images.githubusercontent.com/22562764/62331728-6f71fc00-b482-11e9-80ed-d697b2261d82.png)

IMO the derivative value should still be selectable in later aggregations though.

**Comment by torkelo** [comment]
Each query is a separate elastic query (batched together) but ES cannot reference aggregations across queries

**Comment by cpmoore** [comment]
@torkelo 

I'm not referring to referencing aggregations across queries.
I want to use the derivative in a later bucket script grouping in the same query.

The elasticsearch request should end up looking something like 
```json
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "now-15m",
              "lte": "now"
            }
          }
        },
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "event.dataset: system.network"
          }
        }
      ]
    }
  },
  "aggs": {
    "10": {
      "terms": {
        "field": "system.network.name",
        "size": 10,
        "order": {
          "_key": "desc"
        },
        "min_doc_count": 1
      },
      "aggs": {
        "2": {
          "date_histogram": {
            "fixed_interval": "10s",
            "field": "@timestamp",
            "min_doc_count": 0
          },
          "aggs": {
            "max_packets": {
              "max": {
                "field": "system.network.out.packets"
              }
            },
            "derivative_of_max_packets": {
              "derivative": {
                "buckets_path": "max_packets"
              }
            },
            "negative_derivative": {
              "bucket_script": {
                "buckets_path": {
                  "var1": "derivative_of_max_packets"
                },
                "script": "params.var1*-1"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by torkelo** [comment]
what you write there is a single ES query

**Comment by cpmoore** [comment]
Right, it's a single query with the derivative being used in the bucket script.


Here's the same thing in the multiquery format. 
The first query is the inbound which would be positive, then the second query has the derivative used in a later aggregation.

```json
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"metricbeat-*"}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1564767219299","lte":"1564769019299","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host.name: \"hqeslapd01a.corp.fin\" AND event.dataset: system.network"}}]}},"aggs":{"10":{"terms":{"field":"system.network.name","size":10,"order":{"_key":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"10s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1564767219299","max":"1564769019299"},"format":"epoch_millis"},"aggs":{"11":{"max":{"field":"system.network.in.packets"}},"12":{"derivative":{"buckets_path":"11"}}}}}}}}
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"metricbeat-*"}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1564767219299","lte":"1564769019299","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host.name: \"hqeslapd01a.corp.fin\" AND event.dataset: system.network"}}]}},"aggs":{"10":{"terms":{"field":"system.network.name","size":10,"order":{"_key":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"10s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1564767219299","max":"1564769019299"},"format":"epoch_millis"},"aggs":{"11":{"max":{"field":"system.network.out.packets"}},"12":{"derivative":{"buckets_path":"11"}}}}}}}}}

```

The elasticsearch query works fine.
The datasource just will not let you select the derivative in the bucket script var selection.

**Comment by fjmacagno** [comment]
Seconding this issue, it seems to be impossible to select a derivative metric (or moving average) from another metric in the Grafana UI, like https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-derivative-aggregation.html#_second_order_derivative says should be possible.

**Comment by simianhacker** [comment]
The fix for this is quite simple, looking at the `getPipelineAggOptions()` function in `public/app/plugins/datasource/elasticsearch/query_def.ts`, if you remove the `if` statement that prevents the pipeline aggregations from being listed as `bucket_path` fields then it allows the user to select pipeline aggs a the path. The list of metrics (fields) should exclude any previous pipeline aggs in the chain (and it's self) to avoid recursion. To exclude the parent/self pipeline aggs, we can replace the `if` statement mentioned above with an `Array.filter` to only show Metric aggs and pipelines that won't cause a recursion. The labels for the pipeline aggs (listed in the field dropdown) could be cleaned up a bit to make them easier to decipher.

This would mimic the behavior in Kibana's TSVB visualization and expose the full power of Elasticsearch's pipeline aggregations in Grafana.
