### ISSUE TITLE
API access via Basic Auth forbidden before /login request

### ISSUE THREAD

**Issue by toomasp** [grafana/grafana#18329]
**What happened**:

Tried using the API via HTTP Basic auth. Which failed even though the credentials were valid.

````bash
$ curl -vk -u "$USERNAME:$PASSWORD" https://grafana/api/datasources
* Server auth using Basic with user 'toomasp'
> GET /api/datasources HTTP/1.1
> Host: grafana
> Authorization: Basic REDACTED
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Cache-Control: no-cache
< Content-Type: application/json; charset=UTF-8
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Date: Thu, 01 Aug 2019 06:41:15 GMT
< Content-Length: 31

$ curl -vk -H 'Content-Type: application/json' -X POST -d '{"email": "","password": "REDACTED","user":"toomasp"}' https://grafana/login
> POST /login HTTP/1.1
> Host: grafana
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 66
> 
* upload completely sent off: 66 out of 66 bytes
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Expires: -1
< Pragma: no-cache
< Set-Cookie: grafana_session=5df9e5908fc5a46dad1f263f34b7b28e; Path=/; Max-Age=2595600; HttpOnly; SameSite=Lax
< X-Frame-Options: deny
< Date: Thu, 01 Aug 2019 06:45:44 GMT
< Content-Length: 23
< 
{"message":"Logged in"}

$ curl -vk -u "$USERNAME:$PASSWORD" https://grafana/api/datasources
> GET /api/datasources HTTP/1.1
> Host: grafana
> Authorization: Basic REDACTED
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Date: Thu, 01 Aug 2019 06:52:06 GMT
< Transfer-Encoding: chunked
````

**What you expected to happen**:

I expected the first request to succeed. Instead, I get an authentication failure. Which disappears once I've gone through the /login POST request. Afterwards, basic auth works as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Authenticaton backend is LDAP. Use an existing LDAP user that has *NOT* logged into Grafana.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 6.2.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS Linux release 7.6.1810 (Core)

**Comment by aocenas** [comment]
@markelog Can you take a look at this?

**Comment by torkelo** [comment]
This is due to we doing a GetUserByLogin before the login command, not sure why:

https://github.com/grafana/grafana/blob/master/pkg/middleware/middleware.go#L166

**Comment by aocenas** [comment]
@torkelo Hmm yes I assume the user is not in DB before we auth with LDAP in this case. Does not seem to be doing anything else than just giving a different error message.
