### ISSUE TITLE
Text Panel not  render image the left or right the same line text

### ISSUE THREAD

**Issue by mrhernandes** [grafana/grafana#18322]
**What happened**:
The Text Panel not  render image the left or right the same line text

**The HTML Code**:
<div style="padding-right: 10px;">
<img src="https://www.trzcacak.rs/myfile/detail/504-5044944_grafana-logo-curse-media.png" align="left"  height="40px" wieght="40px" />
</div>
<div style="padding-right: 10px;">
<img src="https://www.trzcacak.rs/myfile/detail/504-5044944_grafana-logo-curse-media.png" align="right"  height="40px" wieght="40px" />
</div>

<div style="width: 100%; background-color:rgb(255,255,255); padding: 1px 0; text-align: center;">
<span style="font-size: 34px; color:rgb(0, 66, 98);;"><b>Internet link</b> </span>
</div>

** ***
**Before**
Grafana Version:  Grafana v5.4.2 (commit: d812109) 
Data source type & version: Zabbix - Version 3.9.1
OS Grafana is installed on: CentOS 7
Browser: Chrome,Firefox,Opera

![image](https://user-images.githubusercontent.com/12343987/62221608-4b31f480-b388-11e9-8b3f-d8951be2135a.png)

**After Upgrade Version**
Grafana Version: Grafana v6.2.2 (commit: 07540df)
Data source type & version: Zabbix - Version 3.10.2
OS Grafana is installed on: CentOS 7
Browser: Chrome,Firefox,Opera

![image](https://user-images.githubusercontent.com/12343987/62221818-ae238b80-b388-11e9-8a81-bd4a1a220a6e.png)

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce insert code in the text panel on HTML mode.

**Comment by torkelo** [comment]
New security setting you need to disable
https://grafana.com/docs/installation/configuration/#disable-sanitize-html
