### ISSUE TITLE
CloudWatch metric math broken when using variables

### ISSUE THREAD

**Issue by jcpetruzza** [grafana/grafana#18337]
**What happened**:

When defining a panel using CloudWatch and metric math, nothing is displayed if the metric is defined using some variable.

**What you expected to happen**:

Using variables to define metrics shouldn't affect metric math.

**How to reproduce it (as minimally and precisely as possible)**:

  1. Create a new dashboard, with a CloudWatch datasouce.
  1. Add a query, pick a metric (without using variables), set `a` as "Id"; wait for it to render.
  1. Add a query, set `2*a` as "Expression" and `b` as "Id", wait for it to render.
  1. Add a dashboard variable `x`, with the dimension value of the metric of `a`.
  1. Modify  the definition of `a` to use `$x` as dimension value. Now both series disappear and we get "No data points".
  1. Delete `b`, now `a` appears again.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: CloudWatch
- OS Grafana is installed on: Running on EKS, provisioned via helm charts
- User OS & Browser: Ubuntu 18.04, Chromium 75
- Grafana plugins: default

**Comment by levilovelock** [comment]
Also experiencing this. From what I've seen the `id` has some sort of a hash added to it based on the value of the variable in the dimension.

**Comment by jpmontez** [comment]
@sunker Seeing something similar to this in Grafana 6.6.2. Using a variable within a CloudWatch query and setting an `id` causes data points to not fetch.

**Comment by ariofrio** [comment]
Still seeing this on Grafana 7.0.0. Here's the panel JSON:

```
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "$datasource",
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "fill": 0,
  "fillGradient": 0,
  "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 10
  },
  "hiddenSeries": false,
  "id": 23,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "hideEmpty": false,
    "hideZero": false,
    "max": true,
    "min": true,
    "rightSide": false,
    "show": true,
    "sort": "avg",
    "sortDesc": true,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "connected",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "alias": "",
      "dimensions": {
        "DBInstanceIdentifier": "*"
      },
      "expression": "",
      "id": "m1",
      "matchExact": true,
      "metricName": "CPUCreditUsage",
      "namespace": "AWS/RDS",
      "period": "300",
      "refId": "A",
      "region": "$region",
      "statistics": [
        "Sum"
      ]
    },
    {
      "alias": "",
      "dimensions": {},
      "expression": "m1",
      "id": "",
      "matchExact": true,
      "metricName": "",
      "namespace": "",
      "period": "",
      "refId": "B",
      "region": "default",
      "statistics": [
        "Average"
      ]
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "CPU Credit Usage",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "transformations": [],
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "$$hashKey": "object:1194",
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "$$hashKey": "object:1195",
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```

When I replace "$region" with "default", the query works again.
