### ISSUE TITLE
Add support text-type metrics of Elasticsearch datasource

### ISSUE THREAD

**Issue by gnh1201** [grafana/grafana#18339]
## Feature request
When I use value of text columns in Elasticsearch data rows, the `Table` visualization could be show text-type columns on the dashboard with metric option `Raw Document`. but, many public plugins of Grafana, it can not parse text in columns of raw document in rows. Can I have alternatives?

## Prerequisites
When I use plug-ins like `SingleStat`, `Status Panel`, `PolyStat` or similar plugins, I was not find how to show value text-type columns in panel. this plugins aren't support parse raw document of each rows. so, I have to find alternatives.

## Links
- https://grafana.com/docs/features/panels/singlestat/
- https://grafana.com/grafana/plugins/vonage-status-panel
- https://grafana.com/grafana/plugins/grafana-polystat-panel

## Related issues
- Grafana + Elasticsearch - how to output text on singlestat control #13881

**Comment by torkelo** [comment]
we are working on improving universal support for non time series data

**Comment by gnh1201** [comment]
Thanks for your comment. I am looking for an appropriate stack to use text-type metrics in time series data on Grafana. Can I get any helpful information at this time?

**Comment by cpmoore** [comment]
I'm not sure about the `Status Panel` and `PolyStat` panels as I haven't used them, but as for plain text data being displayed in the `SingleStat` panel, you can do something like this

![image](https://user-images.githubusercontent.com/22562764/62407469-90b81280-b57e-11e9-9a8f-ee8181880f84.png)

I have just an empty bucket script returning a static value, then I group by `@timestamp` and only return 1 document ordered by the term value.  This ensures only the newest document matching your query in the selected time range is returned, then group by whatever term you wish to display.

Now on the panel options it will switch from value to columns and you can select your column to display
![image](https://user-images.githubusercontent.com/22562764/62407493-fc9a7b00-b57e-11e9-9ab6-ef82e5bdbc60.png)

And voilà, it works
![image](https://user-images.githubusercontent.com/22562764/62407497-12a83b80-b57f-11e9-8e9c-ce23475821ba.png)

Is this what you were trying to do?

**Comment by peterholmberg** [comment]
Closing this since it the same issue is reported in the related issue, https://github.com/grafana/grafana/issues/13881
