### ISSUE TITLE
Can not add Visualization of Guage and BarGuage

### ISSUE THREAD

**Issue by Sorarinu** [grafana/grafana#18330]
**What happened**:
I get a blank screen when I try to add Guage's visualization to a dashboard.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The following information is output to Console of Chrome developer tool.

```
TypeError: Cannot read property 'length' of undefined
```

**Environment**:
- Grafana version: Grafana v6.3.0-beta2 (c8740d9)
- Data source type & version: anything
- OS Grafana is installed on: Docker on CentOS 7.6
- User OS & Browser: Google Chrome 75.0.3770.142
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What does your query return ?

**Comment by Sorarinu** [comment]
I have selected Visualization before entering a query.
There is no problem in selecting a visualization such as a table.

![スクリーンショット 2019-08-01 17 46 24](https://user-images.githubusercontent.com/16132069/62279173-87e31600-b484-11e9-89f7-d351c9724edf.png)
![スクリーンショット 2019-08-01 17 46 46](https://user-images.githubusercontent.com/16132069/62279185-8d406080-b484-11e9-8234-a75478eae6ea.png)

**Comment by nmocean** [comment]
I have this same issue. Whether adding a new Gauge or Bar Gauge visualization to a dashboard or trying to modify an existing one I get a black screen with only the left menu bar visible. 
I also noticed that if I start with a query, enter in the appropriate information, and then move to setup the type of visualization I get the same black screen upon clicking on Gauge or Bar Gauge.

**Comment by torkelo** [comment]
What is your  default data source?

**Comment by Sorarinu** [comment]
The default data source is Prometheus.
