### ISSUE TITLE
DashLinks: Unable to add non-HTTP/S external links to dashboards

### ISSUE THREAD

**Issue by zumipin** [grafana/grafana#18338]
**What happened**:
I added a link-type Link to a dashboard, with a URL value that pointed at an SSH-protocol target. When the link was rendered in the dashboard, there was no `href` property, and the resulting link was non-functional.

**What you expected to happen**:
I expected the rendered link to open the app associated with SSH in my browser, and attempt to connect to the given URI.

Links that are created with a Url property that uses `http://`, `https://`, or no specified protocol, will function as expected after creation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new dashboard
2. Navigate to `Dashboard Settings` -> `Links`
3. Create a new link-type Link with the `Url` property set to `ssh://some.valid.hostname.tld`
4. Save changes and view the Dashboard
5. The new Link will be visible, but will lack an `href` property, causing it to be non-functional

**Anything else we need to know?**:
I was able to recreate the issue across several different up-to-date browsers:
- Safari
- Chrome
- Firefox Dev. Edition

The Dashboard JSON includes the links and Url values intact, it is just the rendered dashboard that fails to include the Url string.

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: No datasource required to recreate this issue
- OS Grafana is installed on: Centos 7.5
- User OS & Browser: macOS 10.14.6; Safari 12.1.2; Chrome 75.0.3770.142; Firefox Dev Edition 69.0b8
- Grafana plugins: Boom Table v1.0.0; Statusmap v0.1.1
- Others: n/a

**Comment by torkelo** [comment]
This looks to be due the angular link sanitization.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
