### ISSUE TITLE
More scalling functions for the Y axis

### ISSUE THREAD

**Issue by zar3bski** [grafana/grafana#18333]
**What would you like to be added**: Out of the box grafana for time series graphs allows to choose between a **linear** scale and various **log** (2 -> 1024) scales for the Y axis. It would be nice if there were other functions like `tan` (`Y/100*pi-pi/2`) or, even better, the possibility to integrate UDF.

**Why is this needed**:
Some time series with very dissimilar values (say, market trends) are difficult to read on the same graph. If the Y follows a **linear scale** low values series are stuck on the bottom of the graph. **Log scaling** allows to compare series more easily but tend to flatten them all. This issue is usually handled by choosing the "*right non linear scaling function*"  -- i.e. the one that evenly distributes all the series across the Y axis

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
