### ISSUE TITLE
Docker Images grafana db location

### ISSUE THREAD

**Issue by sstarcher** [grafana/grafana#1833]
I have pulled both latest and 2.0.1 tags and I see the grafana DB location
in /usr/share/grafana/data instead of what the documentation says should be /var/lib/grafana

grafana/grafana                        2.0.1               d4eab9aa5f3a        26 hours ago        188.9 MB
grafana/grafana                        latest              392548749d30        26 hours ago        188.9 MB

**Comment by torkelo** [comment]
thanks will fix

**Comment by torkelo** [comment]
fixed in latest images (2.0.1 and latest)
