### ISSUE TITLE
build for mips

### ISSUE THREAD

**Issue by qiyongxiao** [grafana/grafana#18340]
Hi, authors:
  I am recently build the sourcecode for mips64le platform.  And I make it on amd64 or Darwin, it makes successful. But I make it on mips64le, meet some errors like this:
```
[root@master1 grafana]# GOARCH=mips64le make build
build go files
GO111MODULE=on go run build.go build
fork/exec /tmp/go-build621720869/b001/exe/build: exec format error
make: *** [build-go] Error 1
```
Could help me?

**Comment by torkelo** [comment]
if you want to do cross platform builds, it's best to do the build in our build container 
https://github.com/grafana/grafana/tree/master/scripts/build/ci-build

**Comment by qiyongxiao** [comment]
> if you want to do cross platform builds, it's best to do the build in our build container
> https://github.com/grafana/grafana/tree/master/scripts/build/ci-build

Could I run make on linux or Darwin? Here isn't have internet

**Comment by qiyongxiao** [comment]
> if you want to do cross platform builds, it's best to do the build in our build container
> https://github.com/grafana/grafana/tree/master/scripts/build/ci-build

I use your build container, still make error like the top errors.
