### ISSUE TITLE
LDAP Users still able to login without matching any LDAP group

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#18342]
**What happened**:
I configured LDAP authentication though SSO with a Apache configured in the front.
I then setup LDAP in the grafana.ini and modify the ldap.toml to fit my AD structure.
I then setup my "[[servers.group_mappings]]" to setup permissions for specific organisation.
But when i'm trying to connect with a LDAP user that does not belong to any group i configured, he is still able to connect and Grafana create a new Organisation with the user inside with Admin permission on this new organisation.

ldap.toml :
```
[[servers]]
host = "LDAP_SERVERS"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
allow_sign_up = true

bind_dn = "CN=SA_grafana,OU=Users,DC=exemple,DC=for,DC=github"
bind_password = 'BIND_PASSWORD'

search_filter = "(|(sAMAccountName=%s)(displayName=%s))"

search_base_dns = ["DC=exemple,DC=for,DC=github"]

group_search_filter = "(member:1.2.840.113556.1.4.1941:=CN=%s,OU=Test,OU=Users,OU=Cyres,DC=exemple,DC=for,DC=github)"
group_search_base_dns = ["OU=ACL,OU=Groups,DC=exemple,DC=for,DC=github"]
group_search_filter_user_attribute = "displayName"

[servers.attributes]
name = "displayName"
#surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=GS_Org2_Grafana_RO,OU=ACL,OU=Groups,DC=exemple,DC=for,DC=github"
org_role = "Viewer"
org_id = 2
```

**Anything else we need to know?**:
Appart of isolating the user with ``` group_dn = "*" ``` for the group search filter, is there any way to setup this ? 
I don't know if it's a bug or a misconfiguration from me, we will see

**Environment**:
- Grafana version: 6.3.0 beta 2
- OS Grafana is installed on: CentOS 7

**Comment by torkelo** [comment]
can you show "[[servers.group_mappings]]" mappings?

**Comment by Theoooooo** [comment]
@torkelo Oh sorry i forgot to add it in the exemple. Updating in a minute

**Comment by torkelo** [comment]
I tested this and could not replicate it, I get "Invalid Username or Password" when trying to login with a user that does not belong to a group specified in the group_mappings

And this server log error. 
EROR[08-02|10:22:25] user does not belong in any of the specified LDAP groups logger=ldap username=ldap-editor groups="[cn=editors,ou=groups,dc=grafana,dc=org]"

**Comment by torkelo** [comment]
To troubleshoot ldap issues it helps enabling debug logging in main grafana ini file

```
[log]
filters = ldap:debug
```

**Comment by Theoooooo** [comment]
i'm testing it and i will return with more info. I will tag you.

**Comment by Theoooooo** [comment]
Ok so after several testing with different [[group_search_filter]] and [[servers.group_mappings]] it seems like i don't have any problems anymore.

There was still something really strange but when i add OR condition to [[group_search_fitlter]] unstead of setting multiples [[servers]] it stopped acting weirdly.
I've just follow the doc : https://grafana.com/docs/auth/ldap/#nested-recursive-group-membership

@torkelo I'm not really sure what was causing the issue but thanks for the help anyway ^^
