### ISSUE TITLE
New Prometheus query editor and multi-line queries

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18341]
No way to create multi-line queries with new Prometheus editor. 

Getting reports that the new editor has some issues compared to the previous one. Supporting multi-line queries seems to me the biggest one. 

* Shift+enter to create a new line only works some times and never within functions. 

@davkal

**Comment by kaydelaney** [comment]
maybe i'm misunderstanding, but i seem to be able to use shift+enter to create a new line, even within functions:
![promeditor](https://user-images.githubusercontent.com/45561153/62369997-4f494800-b529-11e9-9234-97c551471020.gif)

**Comment by torkelo** [comment]
Strange, does not work for me in Linux

**Comment by torkelo** [comment]
Works if I escape between ever enter press to hide the auto complete box

**Comment by kaydelaney** [comment]
right, yes, me too. Think it's just an issue of the autocomplete box eating the key event. ideal behavior would be for it to go to a new line even if autocomplete box is visible, right?

**Comment by torkelo** [comment]
Yes that would work

**Comment by kaydelaney** [comment]
@torkelo https://github.com/grafana/grafana/pull/18362 Quick fix. Let me know if this works for you or if i've missed something.

**Comment by towolf** [comment]
There are so many issues with the new editor. I really love Grafana, and it pains me to complain, but the Prom editor is really unusable now. It makes me want to tear my hair out.

**Comment by towolf** [comment]
I pasted some comments into the closed PR, of course that is a bad place for feedback:

https://github.com/grafana/grafana/pull/17660#issuecomment-507294817

**Comment by towolf** [comment]
I found another problem, in addition to the above.

When I copy and paste from the top to the bottom, then the newlines are stripped:
![image](https://user-images.githubusercontent.com/345210/62493058-71182880-b7d0-11e9-8831-fc10815fb8d3.png)
