### ISSUE TITLE
Gauge / BarGauge panels cannot handle empty query response

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18351]
Both panels error with the gdev-testdata no data points scenario. 

![image](https://user-images.githubusercontent.com/10999/62362818-1f487780-b51e-11e9-85b5-ca74d282cd11.png)

**Comment by torkelo** [comment]
@ryantxu think this might be related to the move of thresholds to field

**Comment by aocenas** [comment]
@torkelo isn't this also fixed with https://github.com/grafana/grafana/pull/18353 ?

**Comment by torkelo** [comment]
Sadly not

**Comment by aocenas** [comment]
@torkelo Should be 6.3.0-beta4 then right? Is somebody working on this right now?

**Comment by fadjar340** [comment]
This issue occured again in version 6.6.0 (5c11bbdfb4) that I used...
