### ISSUE TITLE
Documentation of schema for dashboard, panels, etc. + schemaVersion for a given Grafana version

### ISSUE THREAD

**Issue by victoriaalee** [grafana/grafana#18367]
**What would you like to be added**:
Documentation for schemas for dashboard, row, graph, etc. Documentation for the latest `schemaVersion` for the latest Grafana version.

**Why is this needed**:
I have been needing to play with the Grafana UI to create dummy dashboards to see what the JSON for various components look like. I have also had to do the same just to find out what schema version my version of Grafana (5.0.0) supports.

From my searching in the documentation and some source code in this repo, I wasn't able to find anything that easily gave me this information.

If this documentation doesn't exist, I'd be would be willing to help out with it if someone could point me in a good direction for relevant files I'd need to look at.

**Comment by ryantxu** [comment]
I don't think there is much documentation on the actually internal settigns.  The migration to typescript & react is helping this a LOT.  Many of the angular panels have settings without any docs or types, in the newer react panels, things tend to have their options defined clearly in the `types.ts` file:

* https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/gauge/types.ts
* https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/piechart/types.ts

For the dashboard and panel, check:
* https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/DashboardModel.ts
* https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/PanelModel.ts


I'll close this for now, unless you have a concrete proposal or set of things that we should do (beyond improving the typing etc)

**Comment by victoriaalee** [comment]
@ryantxu The links are very helpful. Thanks for the reply!

As clarification - is there not documentation or a source code file to view to get the default dashboard `schemaVersion` number for a given Grafana version? I can look at `DashboardModel` for the fields that the current `schemaVersion` includes but don't see a version number corresponding to it.

To be concrete about my use case and why I think this documentation/info would be useful - I'm interested in comparing the exact differences between `schemaVersion` 12 and 18 for the dashboard, as I am hoping to update some JSON generation scripts to support the newer `schemaVersion`.

**Comment by saminzadeh** [comment]
I agree with @victoriaalee, this would be great. Speaking from a company that has been running Grafana for 5+ years from v2 to v7, we have over 35,000 dashboards (many of which have been created with different schemaVersions) and its hard to tell which dashboards are going to break when we upgrade. Our current process is upgrading Grafana then using trial and error to see what changes need to be made. This results in slow, painful migrations and falling behind in Grafana updates. I would happy to help out here as well.

**Comment by atz** [comment]
It is weird for the UI to present a "JSON Model" of a dashboard, but not have a concrete schema against which to validate that model.  

Among other things, with a schema, I wouldn't need to go to [these incomplete docs](https://grafana.com/docs/grafana/latest/dashboards/json-model/#annotations) (they link to an anchor of a section that does not exist) trying to find the definition of the annotations list.  A schema for the whole document would be the first and last place I needed to look (and there are tools to auto-generate documentation from the schema!).
