### ISSUE TITLE
Bar Guage : Color By Metric : Series Override

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#18364]
**What would you like to be added**: There should be a series override to allow the user to color different bars by label name / metric, analogous to the Graph plugin when set to series.

**Why is this needed**: This is a basic use case that is totally absent from Grafana when dealing with horizontal bar charts (this is present in vertical bar charts via Graph plugin).

**Comment by ryantxu** [comment]
This feature -- or more accurately, set of features -- is super important, but does not have a quick/easy fix.  In general, I am aiming to move most common settings (min/max/color/mappings/etc) from a single panel setting to something based on the field.  See #16912

In general, these settings could/should be set from:
* the datasource directly (SQL knows the real range)
* the datasource settings (some common way to configure field across *all* panels)
* panel -- defaults for any field (this is the current behavior)
   * overrides for some fields, maybe by name, type or other

**Comment by torkelo** [comment]
Not sure this feature request makes any sense , we should add a better bar graph panel/visualizations instead, the bar gauge is not a bar graph but a specific gauge visualization where all bars share same min/max and thresholds think mixing min/max and thresholds in same visualizations will be confusing and easy to misinterpret

**Comment by BrandonQDixon** [comment]
That's a good point, it probably would be better in its own visualization.  I posted this here because the bar gauge is currently the closest thing Grafana has to a horizontal bar chart, and the thing I'm using to get the functionality of a horizontal bar chart in my reports.

**Comment by torkelo** [comment]
implemented in v7
