### ISSUE TITLE
"Test notification sent" is alway displayed no matter whether it's possible or not

### ISSUE THREAD

**Issue by krichter722** [grafana/grafana#18373]
**What happened**:
Sending a test email configured as notification channel confirmed "Test notification sent" even though that's impossible due to missing mail server setup. In case of types where the unavailability of the connection is less transparent, like Telegram, I might spend hours debugging a problem that exists in grafana, which I assume is some else because grafana works based on its feedback.

If you don't consider this a bug, please don't close it right away, but inform me and I'll open a feature request. I opened a bug because this behaviour is faulty and bad UX.

**What you expected to happen**:
If no configuration to be able to send a mail has been made, the option to send a notification should be disabled (preferred) or the confirmation should be a failure message instead.

**How to reproduce it (as minimally and precisely as possible)**:
* Start grafana with `docker run -p 3000:3000 grafana/grafana`
* Open http://localhost:3000, login with admin:admin and set the new admin password to admin
* Open http://localhost:3000/alerting/notification/new and create a channel of type Email with name Email and enter your email address into the list. Click "Send test"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5 (6082d19)
- Data source type & version: ./.
- OS Grafana is installed on: Docker on Ubuntu 19.04
- User OS & Browser: Ubuntu 19.04 Firefox and Chrome
- Grafana plugins: (default)
- Others: ./.

**Comment by zuchka** [comment]
researched this:
appears fixed with better error messages on 7.0.0+:

![CleanShot 2022-02-05 at 12 22 02@2x](https://user-images.githubusercontent.com/37156449/152660929-eb0866ad-32fe-46e5-bb47-1d1f50e769f0.png)

also checked unified alerting on 8.3.4:

![CleanShot 2022-02-05 at 12 24 10@2x](https://user-images.githubusercontent.com/37156449/152660986-11e7b714-3a7d-480d-9ef3-6bfc35511d83.png)
