### ISSUE TITLE
alert image not have any lines

### ISSUE THREAD

**Issue by gavinage** [grafana/grafana#18378]
**What happened**:
alert email image  is  not have any line , only black 

**What you expected to happen**:
have lines

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:  centos6.7
- Grafana version:  5.4.2
- Data source type & version:  es & 5.6
- OS Grafana is installed on: centos 6.7 
- User OS & Browser:  chrome
- Grafana plugins:  
- Others:

emails  image:
![image](https://user-images.githubusercontent.com/5218047/62441155-a5b2c280-b785-11e9-8320-c142a1450521.png)

my chart line
![image](https://user-images.githubusercontent.com/5218047/62441185-bbc08300-b785-11e9-95da-a05c053d7245.png)

**Comment by torkelo** [comment]
If you use the "share panel" selection in the panel menu, then hit the "Direct link rendered image" link. 

Does this work for you? Any errors in the server console?

**Comment by gavinage** [comment]
tks for you anwser, 
but
there is no that item .

like this:
![image](https://user-images.githubusercontent.com/5218047/62441402-87999200-b786-11e9-9726-dec5274bc0ab.png)

**Comment by torkelo** [comment]
that is not he panel share menu

**Comment by gavinage** [comment]
oh  sorry , now  i find  the panel share modal  
 like this :

http://192.168.12.20:8081/render/d-solo/5GsFzZIZz/guan-jian-zi?orgId=2&panelId=2&from=1564964619475&to=1564986219476&width=1000&height=500&tz=Asia%2FShanghai

![image](https://user-images.githubusercontent.com/5218047/62443157-b87cc580-b78c-11e9-8d6c-91970f352c85.png)

and the console log is here:
t=2019-08-05T14:25:17+0800 lvl=info msg=Rendering logger=rendering path="d-solo/5GsFzZIZz/guan-jian-zi?orgId=2&panelId=2&from=1564964619475&to=1564986219476&width=1000&height=500&tz=Asia%2FShanghai"

**Comment by gavinage** [comment]
i  open the log level to debug. 
i found this:
```
t=2019-08-06T10:48:32+0800 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: http://localhost:8081/d-solo/5GsFzZIZz/guan-jian-zi?panelId=2&render=1 status: success 15000\n"
t=2019-08-06T10:48:32+0800 lvl=dbug msg="Image rendered" logger=rendering path=/var/lib/grafana/png/WIJI40cd1T6yk3k5pUUo.png
```
and  i download the pic , it is only a black image

**Comment by gavinage** [comment]
now  I  upgrade it to  lastest  6.2.5 , that is ok
![image](https://user-images.githubusercontent.com/5218047/62513145-75cef200-b84d-11e9-96ed-de506db300a1.png)
3ks for your answer
