### ISSUE TITLE
Footer on login page is hard to read on hover

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#18382]
the login screen has a footer where the items are hard to read when the mouse is over the item.

<img width="586" alt="Screenshot 2019-08-05 at 11 29 25" src="https://user-images.githubusercontent.com/859729/62454419-91b29500-b774-11e9-817a-158d4a16c063.png">

After fixing this, it should still look good in light theme.

**Comment by sarlinska** [comment]
hey @davkal I cannot replicate the issue – what browser are u using?

**Comment by davkal** [comment]
Fixed indeed.
