### ISSUE TITLE
Login: Password change Skip info icon is too close to word

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#18383]
This screen appears after logging in for the first time. The word Skip is too close to the info icon.

<img width="359" alt="Screenshot 2019-08-05 at 11 34 53" src="https://user-images.githubusercontent.com/859729/62454740-2917e800-b775-11e9-972f-f1246db4e59a.png">

**Comment by Ijin08** [comment]
The labels should probably also be moved out of the inputs.
