### ISSUE TITLE
Add note to proxy docs about using variable in proxy_pass

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#18380]
**What would you like to be added**:

Add a note to the [docs on setting the proxy](https://grafana.com/docs/installation/behind_proxy/) about using variable in `proxy_pass` instead of a literal path (see https://github.com/grafana/grafana/issues/18299#issuecomment-517270816).

**Why is this needed**:

This was raised in https://github.com/grafana/grafana/issues/18299. Will probably help prevent some confusion for users which are not proficient in Nginx but still need to do some customisation.

**Comment by oddlittlebird** [comment]
@aocenas , do you have time to help me nail down what change needs to happen to this content to fix this issue?

**Comment by aocenas** [comment]
@DanCech may be more suited to give some suggestion as he basically resolved the original issue for the user. I do not have enough knowledge about the config here I am afraid.

**Comment by oddlittlebird** [comment]
@DanCech, is this something you can help @grafana/docs-squad address?
