### ISSUE TITLE
Unable to install 2.0.1-1.x86_64 on RedHat5

### ISSUE THREAD

**Issue by croydondias** [grafana/grafana#1839]
Downloaded the rpm from https://grafanarel.s3.amazonaws.com/builds/grafana-2.0.1-1.x86_64.rpm

### When installing, I get the following error:
    # sudo rpm -Uvh grafana-2.0.1-1.x86_64.rpm
    error: grafana-2.0.1-1.x86_64.rpm: Header V4 RSA/SHA1 signature: BAD, key ID 3dd18bdd
    error: grafana-2.0.1-1.x86_64.rpm cannot be installed

This can be fixed by following [this](http://www.stankowic-development.net/?p=5807&lang=en) blog article and resigning the rpm.

### Enviornment details:
    # uname -a
    Linux vm-0d08-1208 2.6.18-348.25.1.el5 #1 SMP Thu Apr 10 06:32:45 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by torkelo** [comment]
redhat 5 is not supported, I suggest building from source. 
http://docs.grafana.org/project/building_from_source/

**Comment by croydondias** [comment]
The beta worked fine though, so I'm not sure why the release doesn't.

On Tuesday, April 21, 2015, Torkel Ödegaard <notifications@github.com>
wrote:

> redhat 5 is not supported, I suggest building from source.
> http://docs.grafana.org/project/building_from_source/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/1839#issuecomment-94902675>.
>


-- 
Sent from mobile. Please excuse brevity.

Regards,
Croydon Dias

**Comment by torkelo** [comment]
@croydondias because the rpms are signed. 

You can create unsigned rpms using "go run build.go build package"

**Comment by croydondias** [comment]
Thanks Torkel, I shall try that.

On Tuesday, April 21, 2015, Torkel Ödegaard <notifications@github.com>
wrote:

> @croydondias <https://github.com/croydondias> because the rpms are
> signed.
>
> You can create unsigned rpms using "go run build.go build package"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/1839#issuecomment-94904568>.
>


-- 
Sent from mobile. Please excuse brevity.

Regards,
Croydon Dias

**Comment by torkelo** [comment]
I can fix by changing to so that rpms are signed with v3 GPG signature, but I never succeeded in overriding that macro in rpmmacros, it never was applied :(
