### ISSUE TITLE
My goal is to login using the command line. After do it I'm expecting to go through the browser and be automatically log as admin. I Don't want to see the login page when I'm doing http://localhost:3000. Is it possible?

### ISSUE THREAD

**Issue by githubMukesh** [grafana/grafana#18404]
STOP -- PLEASE READ!

GitHub is not the right place for questions and support requests.

Please ask questions on our community site: [https://community.grafana.com/](https://community.grafana.com/)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
