### ISSUE TITLE
Login: "Forgot password" text is too close to form border 

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#18405]
The placeholder text in the inputs appears slightly inset in relation to the virtual form border. In comparison, the  "Forgot password" text looks like it has no margins to the right. Can/should we tweak this?

<img width="359" alt="Screenshot 2019-08-06 at 12 16 29" src="https://user-images.githubusercontent.com/859729/62532355-7adb7380-b844-11e9-83f7-b0e3ee759df6.png">

**Comment by sarlinska** [comment]
No, it's actually ok – it should stay as it is.
