### ISSUE TITLE
Using base64 source image in html text panel doesn't display the image

### ISSUE THREAD

**Issue by bennysan** [grafana/grafana#18403]
Hi,

I create a html text panel on my home dashboard to just display an image. I use a base64 src in the img tag.
It works perfectly with Grafana 5.x.

But starting Grafana 6.x the image is not display anymore without any errors.

Here the HTML code I'm using :

```
<div class="text-center dashboard-header">
  <span>My Dashboards</span>
  <br/>
  <br/>
  <img src="data:image/gif;base64,..." />
</div>
```

**What happened**:
The image is not display

**What you expected to happen**:
Displaying the image

**How to reproduce it (as minimally and precisely as possible)**:
Create a html text panel with an img tag using a base64 src

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: OpenTSDB 2.4, MySQL 5.x, Elasticsearch 7.x
- OS Grafana is installed on: Redhat 6.10
- User OS & Browser: Windows 7 with Chrome & Firefox (latest version of each browsers)
- Grafana plugins: none
- Others: -

Regards.

**Comment by torkelo** [comment]
you will have to disable this security setting to allow full html in text panel:
https://grafana.com/docs/installation/configuration/#disable-sanitize-html
