### ISSUE TITLE
SQL Server Data Source Templated Table Name

### ISSUE THREAD

**Issue by ajaywazir** [grafana/grafana#18419]
Hi
I want to open a different table based on a selected variable.
This results in error:
actual SQL needed
select a,b,c from a_table

panel datasource query
select a,b,c from $variable.

Selected variable name is 2nd_table from drop down

evaluated SQL statement in the panel datasource
select a,b,c from '2nd_table'

This quote marks on table name results in error.
The evaluated SQL statement should be 
select a,b,c from 2nd_table

The table name 2nd_table should be unquoted

The variable is a manually entered values  first_table,2nd_table,3rd_table   etc

Any mistakes I am doing
Grafana 6.2.5 beta

Ajay

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Try and use the `${variable:raw}` or `${variable:csv}`. See https://grafana.com/docs/reference/templating/#advanced-formatting-options for further information.
