### ISSUE TITLE
Graph not scaling Y properly

### ISSUE THREAD

**Issue by Xavier59** [grafana/grafana#18415]
**What happened**:

The Y auto scaling feature doesn't work properly. It does scale fine on big interval but doesn't on smaller one. It seems that it's mostly because it is scaling based on previous on future unshown value.

Example : 

![image](https://user-images.githubusercontent.com/10245003/62548960-f13d9d00-b867-11e9-8378-31dc748d3a80.png)

Expected scale to be 0 - $5M

![image](https://user-images.githubusercontent.com/10245003/62549113-39f55600-b868-11e9-9d1a-b2fe8b6ae944.png)

Expected scale to be $11k - $13k

**What you expected to happen**:

Auto scaling Y works fine on small interval. It doesn't scale depending of previous and future unshown value but only based on what's displayed on that interval

**How to reproduce it (as minimally and precisely as possible)**:

Have datas with a wild range of values but grouped into small range on different intervals

**Environment**:
- Grafana version: version 6.3.0-beta4
- Data source type & version: postgresql
- OS Grafana is installed on: Windows
- User OS & Browser: Google Chrome
- Grafana plugins: None

**Comment by torkelo** [comment]
What does your query show? Do you have a time filter in your query? It looks like your query is returning data outside the time window.

**Comment by torkelo** [comment]
Closing for now will open if you show what your query returns (check query inspector) along with the graph

**Comment by Xavier59** [comment]
Indeed, my query was returning data outside the time window. I thought it would autoscale independently. It's now fixed, thank you !
