### ISSUE TITLE
Latest Grafana-2.0.1 tar pkg does not have the grafana binary

### ISSUE THREAD

**Issue by shangeo** [grafana/grafana#1841]
I just downloaded the latest tar pkg from: https://grafanarel.s3.amazonaws.com/builds/grafana-latest.linux-x64.tar.gz
Upon untaring the pkg, I am not seeing the grafana binary in the ./grafana-2.0.1 directory. The directory only has the following:
drwxr-xr-x.  2 root root 4096 Apr 21 12:34 bin
drwxr-xr-x.  2 root root 4096 Apr 21 12:34 conf
drwxr-xr-x. 10 root root 4096 Apr 21 12:34 public
drwxr-xr-x.  3 root root 4096 Apr 21 12:34 vendor
The grafana binary was present in your earlier builds (for eg: grafana-2.0.0-beta1). The README only run says run by ./grafana web.

**Comment by torkelo** [comment]
the binary is in the bin folder
