### ISSUE TITLE
Stacking is not correct in 2.0.1

### ISSUE THREAD

**Issue by mxk1235** [grafana/grafana#1842]
![stacked_bug 1](https://cloud.githubusercontent.com/assets/354518/7262277/1c5599b2-e82d-11e4-80ec-039c86bf2b8d.png)

this query goes to OpenTsdb and uses a tag with the host name.  the graph shows a period of time during which i took out one of the hosts out of the LB.  it looks like stacking works fine if all series returned are always non-zero.  however, if one of the timeseries drops off, the stacking isn't done, and the two bars overlay each other instead.

**Comment by torkelo** [comment]
Sorry, this is something many encounter, probably ~10 identical issues like this already. This behavior has always been in grafana,  the stacking mode cannot stack null values, you need to set "null point mode" to null as zero, I am not sure if I OpenTSDB returns nulls for missing data points however. you can try "connected" as null point mode as well.

**Comment by mxk1235** [comment]
sorry.  are you saying that if I select "Null as zero", it should stack correctly?  because it appears that it still doesn't do this.

![stacking-null-as-zero](https://cloud.githubusercontent.com/assets/354518/7282143/cf31737a-e8e2-11e4-954a-e2d85ee8d459.png)

**Comment by torkelo** [comment]
It depends on whether you time series database returns nulls for missing data points, I think OpenTSDB doesn't, Graphite does do that automatically,  Influxdb has a fill(0) feature where it can inset nulls or zeros for missing periods (depending on group by time)

**Comment by mxk1235** [comment]
interesting.  i'll try to debug and see exactly what opentsdb returns.  still, it seems absence of a timeseries for a particular time probably shouldn't affect stacking of other timeseries.

**Comment by mxk1235** [comment]
yes you are right, this is an instance of opentsdb returning fewer datapoints for one of the timeseries.  you can clearly see the second metric carry only 2 datapoints, while the first and third carry 3.

i can try to approach it a couple of different ways.  i could try to patch opentsdb to return nulls, or i could try to patch grafana to handle missing datapoints more gracefully.  what would you suggest?

```
[
  {
    "metric": "metric.name",
    "tags": {
      "http_method": "POST",
      "type": "t",
      "server_host": "server02"
    },
    "aggregateTags": [
      "http_status",
      "geoip-subdivision",
      "geoip-country"
    ],
    "dps": {
      "1429639200": 62669,
      "1429642800": 56879,
      "1429646400": 33840
    }
  },
  {
    "metric": "metric.name",
    "tags": {
      "http_status": "200",
      "http_method": "POST",
      "type": "t",
      "server_host": "server01"
    },
    "aggregateTags": [
      "geoip-subdivision",
      "geoip-country"
    ],
    "dps": {
      "1429639200": 15105,
      "1429646400": 24488
    }
  },
  {
    "metric": "metric.name",
    "tags": {
      "http_method": "POST",
      "type": "t",
      "server_host": "server03"
    },
    "aggregateTags": [
      "http_status",
      "geoip-subdivision",
      "geoip-country"
    ],
    "dps": {
      "1429639200": 61679,
      "1429642800": 55782,
      "1429646400": 31614
    }
  }
]
```
