### ISSUE TITLE
Support more than 32 series in Graph tooltip

### ISSUE THREAD

**Issue by comicfans** [grafana/grafana#18425]
**What happened**:

I have 37 metric from postgres to show , all metric names shown in legend (series_01 ~ series_37), but mouse hover tooltip only shows first 32 metric (series_01 ~ series_32) .  I've set Hover tooltip mode to 'All series' . 

![image](https://user-images.githubusercontent.com/4547108/62589090-b0db2f00-b8fa-11e9-8240-7ba70333b208.png)

If I select missed metric from legend (series_33), series will shown in graph and tooltip, this missing problem only happened to series that is more than 32.

![image](https://user-images.githubusercontent.com/4547108/62589275-4c6c9f80-b8fb-11e9-885c-89a2dbe0ac16.png)

**What you expected to happen**:

all metric in legend should also appears in hover tooltip

**How to reproduce it (as minimally and precisely as possible)**:

create a sql table with 3 columns (metric, time, value), fill them by more than 32 metric,
and show them in grafana

**Anything else we need to know?**:

**Environment**:
- Grafana version:  6.1.6-1
- Data source type & version:  postgresql 11.2
- OS Grafana is installed on: 
- User OS & Browser:  archlinux 64bit , chrome 74 64bit  and firefox 67 64bit
- Grafana plugins: no plugins other than default installation.
- Others:

**Comment by torkelo** [comment]
Think this is due to the tooltip max height

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
