### ISSUE TITLE
[Alert] Get a false positive from alert notification triggers

### ISSUE THREAD

**Issue by leezhmwty** [grafana/grafana#18426]
Alert configuration is as follows:
![捕获1](https://user-images.githubusercontent.com/26474116/62592912-82178580-b907-11e9-93c4-91e418fcbbe1.PNG)

**What happened**:
![捕获3](https://user-images.githubusercontent.com/26474116/62593159-5648cf80-b908-11e9-996a-2af490bb3570.PNG)
As the picture shows, an alarm notification occurred at 9:54, but there was only one error record at 9:54, and the rule was configured to alarm when the error record was greater than 3.

**What you expected to happen**:
 No alarm notification  when there is an error record in one minute, and an alarm when more than 3 times.
I don't know if this problem is caused by my configuration problem, If there is a problem with the configuration, please point out the problem.

**How to reproduce it (as minimally and precisely as possible)**:
Not every time there is an error record, the alarm will be triggered, so I think this is an occasional phenomenon.You can try the above configuration to reproduce this problem.
**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.0.2 (3f4c2e7)
- Data source type & version: Elasticsearch 5.5.3
- OS Grafana is installed on: 
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
> No alarm notification when there is an error record in one minute, and an alarm when more than 3 times.

Think you've misunderstood the concepts. Your rule will be evaluated each 1 minute and if the count is above 3 the alert rule will trigger and notification sent. Please use the `For` if you want the alert rule not to trigger a notification directly and instead trigger a notification if the alert rule condition is true over X amount of time. See https://grafana.com/docs/alerting/rules/#rule-config for further reference.

**Comment by leezhmwty** [comment]
> > No alarm notification when there is an error record in one minute, and an alarm when more than 3 times.
> 
> Think you've misunderstood the concepts. Your rule will be evaluated each 1 minute and if the count is above 3 the alert rule will trigger and notification sent. Please use the `For` if you want the alert rule not to trigger a notification directly and instead trigger a notification if the alert rule condition is true over X amount of time. See https://grafana.com/docs/alerting/rules/#rule-config for further reference.

My problem is not that I don't want to trigger notifications directly. I also know the meaning and usage of  For.
The problem I have is that the notification is triggered by the condition that the value of query() is above 3, but when the value of query() is equal to 1, the alarm is also triggered. So, is this situation a false positive? Or is there any way to improve the accuracy of the alarm?

**Comment by marefr** [comment]
The alert says the count is 1201 so I don't see why you say count is 1 without seeing what query you're using and what the graph looks like.

**Comment by leezhmwty** [comment]
> The alert says the count is 1201 so I don't see why you say count is 1 without seeing what query you're using and what the graph looks like.

Query and graph are as fellow:
![捕获4](https://user-images.githubusercontent.com/26474116/62669516-73da6f80-b9c2-11e9-93de-1650243e019c.PNG)

And why is the count of each alert 1201? However, the count in this time range will not be 1201 through the ES query.
![捕获5](https://user-images.githubusercontent.com/26474116/62669734-4cd06d80-b9c3-11e9-8b6d-9eab16269b8d.PNG)

**Comment by marefr** [comment]
Please change X-Axis Mode to time and change dashboard time range to last 1 minute, then you get the same behavior as when alert rule is evaluated. What does the graph looks like then?

**Comment by stefdaems** [comment]
I've exactly the same issue. Alert is fired messaging 1201 while no results can be found by the query.

**Comment by chrisbro** [comment]
Hitting the exact same thing in v6.2.5 - graph source is an ElasticSearch query. Query returns 0 results in ES and in the drawn graph. Alert is set up to fire on any count() above 0. Alert, however, thinks it has 1201 results and fires.

Oddly specific number to keep popping up from multiple people.

To get around it, I was able to set it to fire if the max() was above 0 for the timeframe.

**Comment by nkrrkn** [comment]
Ahh, this isn't a bug.

A `count` alert is for the number of data points in the query, rather than the value, corresponding to this 1201 value depending on your intervals.

Using `max` alert actually uses the values.
