### ISSUE TITLE
Grafana 6.3 - Windows - Pie Charts Broken

### ISSUE THREAD

**Issue by timlharrison** [grafana/grafana#18423]
**What happened**:
Pie charts broke when updating from Grafana Windows 6.2.5 to 6.3.0

![image](https://user-images.githubusercontent.com/33101253/62566411-e4fd1400-b856-11e9-8014-d96d517943ce.png)

**What you expected to happen**:
Pie charts to remain unbroken.

**How to reproduce it (as minimally and precisely as possible)**:
Build a dashboard with pie chart on Grafana Windows 6.2.5 and update to 6.3.0

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.0
- Data source type & version: Prometheus 2.11.1
- OS Grafana is installed on: Windows 2016
- User OS & Browser: Windows 10 + Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
update your pie chart plugin :)

**Comment by timlharrison** [comment]
Thanks - shouldn't something like this be listed as a breaking change? Especially given that the plugin is a Grafana official plugin?

**Comment by torkelo** [comment]
for external plugins, we usually do not list this, as updating plugins should be part of an upgrade (something we should document)
