### ISSUE TITLE
Explore query field layout in spilt view is broken in Safari

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#18436]
**What happened**: Went to explore and turned on the split view.

**Anything else we need to know?**: 
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/15225624/62615462-95c5ea80-b90d-11e9-85ca-cc2aae7add6b.png">

**Environment**:
- Grafana version: master
- User OS & Browser: Safari

**Comment by hugohaggmark** [comment]
Can't reproduce, cache issue perhaps @sarlinska?

**Comment by marefr** [comment]
@hugohaggmark Tom seems to have reproduced in #18487

**Comment by hugohaggmark** [comment]
@marefr not sure that is the same thing, in Toms case it crashes and this seems to be an CSS caching prob or what have you found?

**Comment by marefr** [comment]
@hugohaggmark sorry, thought it was the same. Weill reopen the other issue.
