### ISSUE TITLE
Login with user not present in Grafana orgnization returns error 500 instead of 4xx 

### ISSUE THREAD

**Issue by deshmukh-abhay** [grafana/grafana#18439]
**What happened**: When a user not present in organization tries to first time login. Grafana throws 500 (internal server error)

**What you expected to happen**:  Grafana should throw 404 not found error.

**How to reproduce it (as minimally and precisely as possible)**: 
Use separate authentication other than Grafana and try to login with user not present in organization

**Anything else we need to know?**:
We are not using Grafana authentication. we are using our own mechanism such google authentication. When that user tries to access Grafana on 5.4.3 Grafana returns 404 error now 
in Grafana 6.2.5 it is returning 500 error.

**Environment**:
- Grafana version: Grafana 6.25
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Amazon Linux
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Could you please include the Grafana server log when this error happens?

**Comment by deshmukh-abhay** [comment]
t=2019-08-12T04:50:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:50:01+0000 lvl=info msg=Rendering logger=rendering path="d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30"
t=2019-08-12T04:50:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30&render=1&refresh=1m"
t=2019-08-12T04:50:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:50:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:50:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=64 name="Panel Title alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:50:15+0000 lvl=info msg=Rendering logger=rendering path="d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2"
t=2019-08-12T04:50:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=62 name=TestQGateAlert error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: ef0c0964-a492-48ee-b0df-18f1d5c7567c A <nil> [] []}" changing state to=alerting
t=2019-08-12T04:50:15+0000 lvl=info msg=Rendering logger=rendering path="d-solo/1_KQCaMZz/testqgatealert?orgId=22&panelId=4"
t=2019-08-12T04:50:17+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2&render=1"
t=2019-08-12T04:50:17+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=POST path=/api/tsdb/query status=400 remote_addr=127.0.0.1 time_ms=94 size=375 referer="http://localhost:3001/d-solo/1_KQCaMZz/testqgatealert?orgId=22&panelId=4&render=1"
t=2019-08-12T04:50:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=63 name="Panel Title alert" error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: e48bd9de-ddc7-4b76-8a95-43ead120408c A <nil> [] []}" changing state to=keep_state
t=2019-08-12T04:50:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:50:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:51:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:51:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:51:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:51:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=62 name=TestQGateAlert error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 9c077831-f9fa-4a46-8a95-995f0321ea00 A <nil> [] []}" changing state to=alerting
t=2019-08-12T04:51:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=63 name="Panel Title alert" error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 6e92dde7-d910-44a1-ac40-5cd4feb02442 A <nil> [] []}" changing state to=keep_state
t=2019-08-12T04:51:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:51:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:51:45+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=64 name="Panel Title alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:51:45+0000 lvl=info msg=Rendering logger=rendering path="d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2"
t=2019-08-12T04:51:46+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2&render=1"
t=2019-08-12T04:52:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:52:01+0000 lvl=info msg=Rendering logger=rendering path="d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30"
t=2019-08-12T04:52:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30&render=1&refresh=1m"
t=2019-08-12T04:52:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:52:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:52:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=62 name=TestQGateAlert error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: ce41b7a4-d353-4f54-b640-639b5c1e630b A <nil> [] []}" changing state to=alerting
t=2019-08-12T04:52:15+0000 lvl=info msg=Rendering logger=rendering path="d-solo/1_KQCaMZz/testqgatealert?orgId=22&panelId=4"
t=2019-08-12T04:52:16+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=POST path=/api/tsdb/query status=400 remote_addr=127.0.0.1 time_ms=72 size=375 referer="http://localhost:3001/d-solo/1_KQCaMZz/testqgatealert?orgId=22&panelId=4&render=1"
t=2019-08-12T04:52:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=64 name="Panel Title alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:52:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=63 name="Panel Title alert" error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 3ebdb99f-7ca6-4e56-bca0-9f0d6f97893b A <nil> [] []}" changing state to=keep_state
t=2019-08-12T04:52:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:52:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:53:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:53:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:53:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:53:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=64 name="Panel Title alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:53:15+0000 lvl=info msg=Rendering logger=rendering path="d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2"
t=2019-08-12T04:53:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=62 name=TestQGateAlert error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 916f4073-9623-4827-880a-61cdc836e45d A <nil> [] []}" changing state to=alerting
t=2019-08-12T04:53:16+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2&render=1"
t=2019-08-12T04:53:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=63 name="Panel Title alert" error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 434f2c18-636d-45b4-975c-385afe126f59 A <nil> [] []}" changing state to=keep_state
t=2019-08-12T04:53:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:53:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:54:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:54:01+0000 lvl=info msg=Rendering logger=rendering path="d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30"
t=2019-08-12T04:54:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30&render=1&refresh=1m"
t=2019-08-12T04:54:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:54:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:54:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=62 name=TestQGateAlert error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 772f98d8-9997-4c14-8a59-0774d12a3fac A <nil> [] []}" changing state to=alerting
t=2019-08-12T04:54:15+0000 lvl=info msg=Rendering logger=rendering path="d-solo/1_KQCaMZz/testqgatealert?orgId=22&panelId=4"
t=2019-08-12T04:54:16+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=POST path=/api/tsdb/query status=400 remote_addr=127.0.0.1 time_ms=71 size=375 referer="http://localhost:3001/d-solo/1_KQCaMZz/testqgatealert?orgId=22&panelId=4&render=1"
t=2019-08-12T04:54:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=63 name="Panel Title alert" error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: d11b16ef-533d-470b-9f00-a4a79f570f68 A <nil> [] []}" changing state to=keep_state
t=2019-08-12T04:54:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:54:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:54:45+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=22 uname=grafanaadmin method=GET path=/api/users/lookup status=404 remote_addr=10.10.4.105 time_ms=36 size=28 referer=
t=2019-08-12T04:54:45+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=64 name="Panel Title alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:54:45+0000 lvl=info msg=Rendering logger=rendering path="d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2"
t=2019-08-12T04:54:46+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/VkAG644Wk/test_mail?orgId=22&panelId=2&render=1"
t=2019-08-12T04:55:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:55:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:55:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:55:15+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=62 name=TestQGateAlert error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 78dd6b54-193f-4931-801a-756f8aac009c A <nil> [] []}" changing state to=alerting
t=2019-08-12T04:55:16+0000 lvl=eror msg="auth proxy: failed to get signed in user" logger=context message="User not found" error=nil
t=2019-08-12T04:55:16+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=500 remote_addr="121.241.69.194, 10.10.3.247" time_ms=3 size=1719 referer=
t=2019-08-12T04:55:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=64 name="Panel Title alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:55:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=63 name="Panel Title alert" error="tsdb.HandleRequest() response error &{InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 32dd1b54-6098-4f50-a6f1-fa336d4c913b A <nil> [] []}" changing state to=keep_state
t=2019-08-12T04:55:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:55:37+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=
t=2019-08-12T04:56:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=52 name="CPU Usage alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting
t=2019-08-12T04:56:01+0000 lvl=info msg=Rendering logger=rendering path="d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30"
t=2019-08-12T04:56:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=22 uname= method=GET path=/api/datasources/proxy/21/api/v1/query_range status=503 remote_addr=127.0.0.1 time_ms=2 size=178 referer="http://localhost:3001/d-solo/P_alert/prometheus-alert-dashboard?orgId=22&panelId=30&render=1&refresh=1m"
t=2019-08-12T04:56:03+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.4.156 time_ms=0 size=29 referer=
t=2019-08-12T04:56:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.3.4 time_ms=0 size=29 referer=

**Comment by markelog** [comment]
Looking at the 5.4.3 version of the [code](https://github.com/grafana/grafana/blob/v5.4.3/pkg/middleware/auth_proxy.go) I'm not sure it can return something other then 500 in your use case. Couldn't reproduce it on my instance of 5.4.3 too, hm. Probably missing something.

But looking at the HTTP [spec](https://tools.ietf.org/html/rfc2616) it seems indeed more appropriate to return `407` status code then anything else - https://github.com/grafana/grafana/pull/18584

**Comment by deshmukh-abhay** [comment]
It was 404 in version 5.4.3.
I have test on Grafana 6.2 it is returning 404.
Issue is for Grafana 6.2.5.
I have also found out that first time when use was not present in organization.
that time it gives error 404. 
And user is added successfully.
When we are deleting that user form organization and then try to add user in organization then 500 error is thrown. also If we are adding user through Grafana api.
If we try to add user after we get  500 error for user not present in Grafana.
I have use api "POST /api/org/users" then Grafana is not adding user.
it is  throwing error "user not found error" .

**Comment by markelog** [comment]
We have a pull for this - https://github.com/grafana/grafana/pull/18584, if you have the opportunity to install the grafana from this branch and check against your use case that would be super helpful!
