### ISSUE TITLE
Import from elasticsearch only captures 100 dashboards

### ISSUE THREAD

**Issue by mbradshaw93** [grafana/grafana#1843]
Hello,
  I'm trying to import from elasticsearch as indicated in the migration guide from 1.x.  This is working great, however I'm missing dashboards, as the import only captures 100 dashboards, and we have more than that in our Grafana 1.x instance.  Is there a config option I'm missing to be able to adjust this?
Please let me know if I can provide more details.
Thanks
Michael

**Comment by bruce-lyft** [comment]
This appears still to be broken, even with the diff applied.

**Comment by torkelo** [comment]
sure? do you have more than 1000 dashboards?

**Comment by bruce-lyft** [comment]
I have 150 dashboards, but only the first 100 are imported.  I can see the 10000 in the code, but it does not appear to work.

**Comment by torkelo** [comment]
@bruce-lyft strange, not sure what could be the cause, if you check the elasticsearch query in chrome dev tools does it look ok? how many does it return?

**Comment by bruce-lyft** [comment]
In chrome tools, the response comes back with 146 dashboards:

{"took":16,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":146,"max_score":null,"hits":[{"_index":"grafana-dash","_type":"dashboard","_id":"ATS","_score":null,"_source":{"dashboard": "{\n \"annotations\": {\n  \"enable\": true, \n  \"list\": [\n   {\n    \"enable\": false, \n    \"iconColor\": \"#C0C6BE\", \n    \"iconSize\": 13, \n    \"lineColor\": \"rgba(255, 96, 96, 0.592157)\", \n    \"name\": \"heroku\", \n    \"showLine\": true, \n    \"tags\": \"heroku\", \n

**Comment by bruce-lyft** [comment]
$ grep size /usr/share/grafana/public/app/plugins/datasource/elasticsearch/datasource.js
... size:1e4

That's the proper code, right?

**Comment by torkelo** [comment]
so if elasticsearch returns 146 dashboard, but you only see 100 dashboards being imported. Strange

**Comment by bruce-lyft** [comment]
That's correct.

**Comment by torkelo** [comment]
That is strange, as there is no limit on the import code.

**Comment by mbradshaw93** [comment]
I can confirm that I am also still seeing this limit at 100 dashboards being imported with 2.0.2.

**Comment by kicmuc** [comment]
I can also confirm this is still existing in the latest 2.1.0-pre1 tar.gz version I have downloaded one hour ago. In ./public/app/plugins/datasource/elasticsearch/datasource.js size is configured to be 1e4 - but imports always stop after 100 dashboards.

**Comment by falkenbt** [comment]
I looked a bit closer into this and saw that the __query__ still contains size=100: 
```javascript{
	"query" : {
		"query_string" : {
			"query" : "title:*"
		}
	},
	"facets" : {
		"tags" : {
			"terms" : {
				"field" : "tags",
				"order" : "term",
				"size" : 50
			}
		}
	},
	"size" : 100,
	"sort" : ["_uid"]
}
```

While ES returns the number of hits as a meta information in the __response__...

```
"hits" : {
		"total" : 360, 
...
```
the number of actual elements of hits.hits is __100__. 

So I assume the fix did wasn't put in the right place, the query still limits the result size to 100.

**Comment by torkelo** [comment]
Fixed correctly this time :) Sorry for the wrong fix!
