### ISSUE TITLE
Add fill gradient option to series override line fill

### ISSUE THREAD

**Issue by Khord** [grafana/grafana#18445]
**What would you like to be added**:
Add fill gradient setting to series overrides

**Why is this needed**:
It would be nice to be able to use the fill gradient feature (#17528) on multi query graphs where one query is an average of all the series in the other query, using a series override to only fill below the average line

https://github.com/grafana/grafana/pull/17528#issuecomment-518989346

![image](https://user-images.githubusercontent.com/21085666/62643959-1a693680-b917-11e9-8de5-63dbc1d8d86e.png)

**Comment by marefr** [comment]
Are you referring to using a gradient when using the fill below to override?

**Comment by Khord** [comment]
If I'm understanding you correctly, yes. I think it would make sense to allow the series override to have the option to use a gradient on the fill below, just as it would be possible if the query behind the series override were on a separate graph panel.

**Comment by marefr** [comment]
I've updated the title to reflect this.

**Comment by i5okie** [comment]
I don't think its specific to 'fill below'. I think just having the fill-gradient option in that dropdown would be great. period.
i've got 9 overrides, and would be nice to be able to set their individual gradients
![image](https://user-images.githubusercontent.com/2119240/63049938-b56d8d80-be8e-11e9-958b-117f4db5592d.png)

**Comment by Khord** [comment]
Agreed, I misread. I was talking about having this "Fill Gradient" setting available to apply to the regular "line fill" in the series override (as in the fill to bottom)
![image](https://user-images.githubusercontent.com/21085666/63051360-1b680e00-beab-11e9-8c58-f357d122e242.png)

**Comment by hendrikvh** [comment]
I agree @Khord, @i5okie and everyone else: Individually overriding gradients would be very handy. I have made the change and submitted it for review. 🎉 

This `1` - `10` option might be changed to a `true` or `false` value in #20294. I think that will be a good change and I don't feel that it will affect the functionality. I find that my use case for this override is mainly to enable or disable the gradient.
