### ISSUE TITLE
Regression: Gauge / BarGauge panels cannot handle empty query response

### ISSUE THREAD

**Issue by tarekbecker** [grafana/grafana#18440]
Hi,

the bug #18351 still occurs for streaming clients.

**What happened**:
Error: `Cannot read property 'color' of undefined`

**What you expected to happen**:
no error
**How to reproduce it (as minimally and precisely as possible)**:
1. docker run --rm --name=grafana -p 3000:3000 grafana/grafana:6.3.0-beta4
1. create dashboard
1. choose TestDatabase and Streaming Client
1. choose Bar Gauge as visualization

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.0-beta4
- Data source type & version: TestDatabase Streaming Client
- OS Grafana is installed on:  docker (on mac)
- User OS & Browser: chrome
- Grafana plugins: none
- Others:

**Comment by marefr** [comment]
Should be fixed in Grafana v6.3 stable (6.3.2 recommended)
