### ISSUE TITLE
Plugins: Support accessing react-redux from plugins 

### ISSUE THREAD

**Issue by adrianromanko** [grafana/grafana#18443]
systemjs fails to dynamically load imported modules such as react-redux, material-ui, etc.

Example React panel that imports Provider
import { Provider } from 'react-redux';

![Screen Shot 2019-08-07 at 11 33 39 AM](https://user-images.githubusercontent.com/3165356/62636357-63b18a00-b907-11e9-8505-c79e5724c24e.png)

A possible fix is to add plugin-babel to the SystemJS.config or to allow merging custom webpack configs the grafana-toolkit cli build command.
plugin_loader.js:
grafanaRuntime.SystemJS.config({
  …
  map: {
    …
    'plugin-babel': 'vendor/systemjs-plugin-babel/plugin-babel.js',
  }

See also #15341

**Comment by torkelo** [comment]
we currently do not expose the react redux to plugins

**Comment by ryantxu** [comment]
Is there a reason not to?  That seems like a library we will keep for a long time

**Comment by dprokop** [comment]
@ryantxu exposing react-redux and having multiple redux stores seems flaky to me. What we could do instead is to make sure extensions have access to our store and a possibility to connect to it. I suggest exposing it via grafana-runtime and only the react-redux's  `connect` function.

**Comment by adrianromanko** [comment]
i'm using multiple stores with plugins and it's working great. I think it's the right use case for multiple stores because each plugin is holding a different domain of data despite the strongly principled and intended Redux pattern to have only a single store.

I originally titled the issue as @grafana/toolkit because the issue is with the @grafana/toolkit webpack configuration which breaks while importing certain SystemJS imports/ES6 modules.

Example with material UI
Works:
`import Button from '@material-ui/core/Button';`
Issue:
`import Button from '@material-ui/core';`


I used a custom webpack config before switching over to building with @grafana/toolkit
Here's what worked...
`
...
{
          test: /\.(j|t)sx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env',
                '@babel/preset-typescript',
                '@babel/preset-react',
              ],
              plugins: [
                ['@babel/plugin-proposal-decorators', { legacy: true }],
                ['@babel/plugin-proposal-class-properties', { loose: true }],
                '@babel/plugin-syntax-dynamic-import',
                '@babel/plugin-transform-modules-commonjs',
                'react-hot-loader/babel',
              ],
            },
          },
        },
...
`

**Comment by torkelo** [comment]
> What we could do instead is to make sure extensions have access to our store and a possibility to connect to it 

Having plugins access to the core store & types feel very fragile.

**Comment by ryantxu** [comment]
My litmus for this is thinking about how we could implement Explore as a plugin app.  It needs access to react/redux -- what is the best way to do that?   If we expose the library (but not the store) can it just create its own independent store, but reuse the existing library?  

Alternatively, each app/plugin could embed its own copy of redux, but that seems less than ideal

**Comment by torkelo** [comment]
We can definitely expose the library I see major problem with that

**Comment by ryantxu** [comment]
@dprokop -- do you see any problem with: https://github.com/grafana/grafana/pull/18501

My assumption is that plugins could use their isolated redux store for whatever they need.  I agree we need to be careful about how/where we expose the internal grafana redux store (though I don't know enough about this to know what I am talking about!)

**Comment by dprokop** [comment]
@torkelo @ryantxu did some read-up on nesting providers. My gut feeling was that having multiple Providers being nested will result in problems when resolving data from redux store. Apparently this is not an issue so let's proceed with #18501
