### ISSUE TITLE
Annotation Query Failed Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by andriisoldatenko** [grafana/grafana#18441]
**What happened**:
I see popup with message: `Annotation Query Failed Cannot read property 'data' of undefined`
![image](https://user-images.githubusercontent.com/1374633/62630610-f8cc7700-b937-11e9-9c8c-7f0a2166b87d.png)

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Console error:
```
event_editor.ts:1 AnnotationSrv.query error TypeError: Cannot read property 'data' of undefined
    at datasource.ts:611
    at angular.js:17051
    at angular.js:17095
    at l.$digest (angular.js:18232)
    at l.$apply (angular.js:18531)
    at angular.js:18832
    at h (angular.js:6362)
    at angular.js:6642
```

If i run `curl`:

```
curl 'https://grafana/api/datasources/proxy/1/api/v1/query_range?query=sum(changes(prometheus_config_last_reload_success_timestamp_seconds%7Binstance%3D~%22localhost%3A9090%22%7D%5B10m%5D))%20by%20(instance)&start=1565185800&end=1565187600&step=300' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://grafana.andrii-dev.datarouter.ai/d/H7LAVDJik/prometheus' -H 'X-Grafana-Org-Id: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' --compressed
```
it works and return json:

```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"instance":"localhost:9090"},"values":[[1565187300,"0"],[1565187600,"0"],[1565187900,"0"]]}]}}
```
**Environment**:
- Grafana version: v6.3.2 (4832460)
- Data source type & version: prometheus:v2.10.0
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome/OSX
- Grafana plugins:
- Others:

**Comment by andriisoldatenko** [comment]
Annotations used in project:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      },
      {
        "datasource": "Prometheus",
        "enable": true,
        "expr": "sum(changes(prometheus_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}[10m])) by (instance)",
        "hide": false,
        "iconColor": "rgb(0, 96, 19)",
        "limit": 100,
        "name": "Reloads",
        "showIn": 0,
        "step": "5m",
        "type": "alert"
      },
```

**Comment by marefr** [comment]
> If i run curl:

If you use chrome developer network tab or similar, do you get the same request/response when Grafana does the annotations request?

**Comment by andriisoldatenko** [comment]
@marefr nope, i see request `canceled`:
![image](https://user-images.githubusercontent.com/1374633/62635269-0d147200-b940-11e9-90a2-2886a56452cb.png)

![image](https://user-images.githubusercontent.com/1374633/62635289-14d41680-b940-11e9-9daa-8bc0d1bf3ecb.png)

**Comment by danieldabate** [comment]
We are seeing the same issue since we updated to 6.3.2. It's quite random, sometimes the annotations load well and sometimes they don't.

**Comment by marefr** [comment]
I can reproduce it the refresh interval of dashboard is faster than the annotation query completes, but that's to me is how it should behave.

**Comment by danieldabate** [comment]
Sounds like that's the root cause of the error messages. Great catch. Maybe this race condition happened in previous versions but no error message was being shown. Is this possible?

I would expect this error to be handled in background or to show a softer warning message. The problem with the current behavior is that at first sight it alerts people and make them think that something critical is happening.

**Comment by andriisoldatenko** [comment]
+1 
works great on 6.0.0 and doesn't 6.3.2.

Also grafana UI cancels query in `5ms`, refresh interval is `5s`.

**Comment by marefr** [comment]
Thanks. 5ms sounds definitely wrong, any screenshot showing this behavior?

**Comment by dprokop** [comment]
git bisect results in fb39831df243386377d9188eedeb951c3e1c3698 being the first commit making troubles. Investigating

**Comment by andriisoldatenko** [comment]
https://github.com/grafana/grafana/issues/18441#issuecomment-519144992

**Comment by andriisoldatenko** [comment]
it works! confirmed! 🌮 @dprokop
