### ISSUE TITLE
v2.0.1 cannot be built

### ISSUE THREAD

**Issue by mxk1235** [grafana/grafana#1844]
This is off the master branch, fresh-cloned.  same behavior for v2.0.1 and v2.0.0-b3.  i had to go back to v2.0.0-b1 to get rid of this error. 

any idea what's wrong?  i suspect it might be an outdated package or go install.

```
mxk@mxk-mbp ~/workspace/go/src/github.com/grafana/grafana (master) $ go build
# github.com/grafana/grafana/pkg/social
pkg/social/social.go:78: cannot use SocialGithub literal (type *SocialGithub) as type SocialConnector in assignment:
	*SocialGithub does not implement SocialConnector (wrong type for Exchange method)
		have Exchange(oauth2.Context, string) (*oauth2.Token, error)
		want Exchange(context.Context, string) (*oauth2.Token, error)
pkg/social/social.go:84: cannot use SocialGoogle literal (type *SocialGoogle) as type SocialConnector in assignment:
	*SocialGoogle does not implement SocialConnector (wrong type for Exchange method)
		have Exchange(oauth2.Context, string) (*oauth2.Token, error)
		want Exchange(context.Context, string) (*oauth2.Token, error)
```

**Comment by torkelo** [comment]
Sure it can. I think you missed the step before go build. 
read the [building from source](http://docs.grafana.org/project/building_from_source/) guide. 

Need to run `godep restore` before go build. But it looks like the oauth2 package grafana uses has changed again (godep restore will make sure that a version of oauth2 that grafana can compile against is fetched)

**Comment by mxk1235** [comment]
that was it.  thanks!
