### ISSUE TITLE
Table Legend option with many series causes graph height to be reduced or not be visible

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#1845]
When using table legend option in 2.0, if there are many series the graph is squished or not visible at all. In v1.9, seems the height was auto adjusted to compensate.

![screen shot 2015-04-21 at 6 51 14 pm](https://cloud.githubusercontent.com/assets/2237523/7264318/5966ee02-e858-11e4-9611-9be01de7a0f7.png)
![screen shot 2015-04-21 at 6 55 37 pm](https://cloud.githubusercontent.com/assets/2237523/7264322/5c7b5542-e858-11e4-83b1-adac49325b01.png)

**Comment by torkelo** [comment]
There are already 3 issues that have reported that problem, and already solved in #1832 (comment)  

Will release a patch release 2.0.2 later today to tomorrow, in the mean time there are nightly builds with the fix here: http://grafana.org/download/builds (version is the 2.0.2-pre1)
