### ISSUE TITLE
Prometheus: Queries with label_replace remove the $1 match when loading query editor (dashboard & explore) 

### ISSUE THREAD

**Issue by ahurtaud** [grafana/grafana#18455]
**What happened**:
When clicking on the "explore" link from a panel I already have (which contains a label_replace query), the explore view is correctly opened but the query remove the "$1" character in the args of label_replace function.
It makes the query impossible to copy/paste to the prometheus UI.

what is displayed in Explore UI:
```
label_replace(http_request_seconds),"pod", "", "pod_name","(.*)")
```

**What you expected to happen**:
The prometheus query should keep displaying the $1 character.
what should be displayed in Explore UI:
```
label_replace(http_request_seconds),"pod", "$1", "pod_name","(.*)")
```

**Environment**:
- Grafana version: all from 6.x to 6.3.2
- Data source type & version: prometheus v2.11
- OS Grafana is installed on: official docker image
- User OS & Browser: Mac OS High Sierra, Safari 12.1.2
- Grafana plugins: None

**Comment by davkal** [comment]
I was checking why we havent seen this issue at Grafana, we're using `${1}` instead of `$1`. But I realized just now that alternative syntax is not even documented in Prometheus.
