### ISSUE TITLE
OAuth: Store generated code server side

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#18456]
**What would you like to be added**:
OAuth generated code should be stored server side.

**Why is this needed**:
When authenticating with OAuth, a generated code is stored in a cookie before you're being redirected to OAuth provider. When the OAuth provider redirects back to Grafana there's a validation step to make sure that the code provided in response is the same as stored in the cookie, otherwise login is not allowed.

Since a cookie is in use and the [SameSite](https://grafana.com/docs/installation/configuration/#cookie-samesite) cookie attribute setting applies to all cookies in Grafana it may requires that Grafana instances cannot use the SameSite cookie attribute and by that making Grafana less secure.

Ref #17925

**Comment by marefr** [comment]
Chrome version 80 will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure SameSite cookie attribute, see #19847 for detailed report of the problem.

**Comment by papagian** [comment]
Closing this since with the remote cache solution even if we get a request with state (that is saved in the cache) we cannot be sure that it was initiated from the same user.
