### ISSUE TITLE
React version of info popover

### ISSUE THREAD

**Issue by dehrax** [grafana/grafana#18452]
**What would you like to be added**:
A React version of info popover
https://github.com/grafana/grafana/blob/6c7224c74db5dc2e929bc71a4066b3197b86ef03/public/app/core/components/info_popover.ts

**Why is this needed**:
When Angular components are converted to React, use the React version of infoPopover instead.

Implementation wise it's just `<i class="fa fa-info-circle"></i>` wrapped in a tooltip.

**Comment by torkelo** [comment]
We already have this in https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Tooltip/Tooltip.tsx 

maybe it needs a more high level component that includes the info icon & position as well.

**Comment by dehrax** [comment]
Is it possible to use it by just passing down a prop, or how would I go about it?

```typescript
<InfoTooltip>
This is the content of the tooltip
</InfoTooltip>
```
Wold be a nice way to use it.
