### ISSUE TITLE
[BUG] YYYY-MM-DD formatter is off-by-one day?

### ISSUE THREAD

**Issue by diamondo25** [grafana/grafana#18458]
**What happened**:
I am using a column with a date output in the format YYYY-MM-DD. Somewhere in the parsing of this field using formatter YYYY-MM-DD makes it go down by a single day.

**What you expected to happen**:
No formatting applied, or at least the same value, not a day off.

**How to reproduce it (as minimally and precisely as possible)**:
<img width="645" alt="Schermafbeelding 2019-08-08 om 13 47 35" src="https://user-images.githubusercontent.com/39577/62700929-62ee2600-b9e3-11e9-8b1a-16b5d617f94b.png">
<img width="1094" alt="Schermafbeelding 2019-08-08 om 13 47 23" src="https://user-images.githubusercontent.com/39577/62700933-65e91680-b9e3-11e9-98fa-845afdee59f3.png">

If you change 2018-08-08 to 2018-08-01, you'll see it wrap to 2018-07-31

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Postgres 10
- OS Grafana is installed on: Debian 
- User OS & Browser: Mac OS X 10.14.5 with Chrome 75

**Comment by marefr** [comment]
Any difference if you change dashboard timezone to UTC?

**Comment by diamondo25** [comment]
> Any difference if you change dashboard timezone to UTC?

<img width="1321" alt="Schermafbeelding 2019-08-08 om 14 07 46" src="https://user-images.githubusercontent.com/39577/62702009-ff192c80-b9e5-11e9-95fe-8ed49adb73d8.png">
<img width="1136" alt="Schermafbeelding 2019-08-08 om 14 08 12" src="https://user-images.githubusercontent.com/39577/62702021-02141d00-b9e6-11e9-8ff4-c1a655ffb6fe.png">

**Comment by marefr** [comment]
If you use the query inspector, what is the response? Please include it here

**Comment by diamondo25** [comment]
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1565579481792",
      "to": "1565601081792",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 30000,
          "maxDataPoints": 670,
          "datasourceId": 3,
          "rawSql": "SELECT '2018-08-08' AS \"Time\", '2018-08-08' AS \"Time as text\"",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 1,
          "sql": "SELECT '2018-08-08' AS \"Time\", '2018-08-08' AS \"Time as text\""
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "Time",
                "sort": true,
                "desc": true,
                "title": "Time",
                "style": {
                  "type": "date",
                  "pattern": "Time",
                  "alias": "Time",
                  "dateFormat": "YYYY-MM-DD HH:mm:ss",
                  "$$hashKey": "object:11244"
                },
                "hidden": false,
                "$$hashKey": "object:11293"
              },
              {
                "text": "Time as text",
                "title": "Time as text",
                "style": {
                  "unit": "short",
                  "type": "number",
                  "alias": "",
                  "decimals": 2,
                  "colors": [
                    "rgba(245, 54, 54, 0.9)",
                    "rgba(237, 129, 40, 0.89)",
                    "rgba(50, 172, 45, 0.97)"
                  ],
                  "colorMode": null,
                  "pattern": "/.*/",
                  "thresholds": [],
                  "$$hashKey": "object:11245"
                },
                "hidden": false,
                "$$hashKey": "object:11294"
              }
            ],
            "rows": [
              [
                "2018-08-08",
                "2018-08-08"
              ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "rowCount": 1,
              "sql": "SELECT '2018-08-08' AS \"Time\", '2018-08-08' AS \"Time as text\""
            }
          }
        ]
      }
    }
  }
}
```

**Comment by marefr** [comment]
You'll need to make sure to return a data formatted as date in utc for Grafana UI to work correctly. Closing this. Will consider reopen if you cannot get it to work when utc timestamp is returned.
