### ISSUE TITLE
Panel error message difficult to read

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#18451]
**What happened**:
Had an error message on a panel in the light theme

**What you expected to happen**:
I would easily be able to read message instead the text is dark on red background.

<img width="947" alt="Screenshot 2019-08-08 at 10 49 58" src="https://user-images.githubusercontent.com/23470681/62689378-fd8e3b00-b9ca-11e9-9854-724727a38575.png">

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/18783
