### ISSUE TITLE
Alert for InfluxDB datasource has no data

### ISSUE THREAD

**Issue by Supershark88** [grafana/grafana#18463]
**What happened**:
I'm pretty new to Grafana and have been tasked with setting up alerts on our current implementation. I've set up a notification channel to send out emails and have been testing it with Influxdb's collectd database (collects system information). I created a query that plots the data-transfer rate for my internet connection, which appears to be working just as intended in the graph and data points. However my issue occurs when trying to create an alert for high data usage, and the alert repeatedly states that there is no data when I can clearly see it in the graph. 

First I tried to change the query time frame to be 15m, now-10m in order to avoid getting null data, but that made no difference. I then tried to see what would happen if I made the alert trigger with no values and it immediately sent an email alert. Curiously the image shown didn't contain any data even though that same time frame showed data on Grafana itself. I even checked the log files and the only messages were from when my computer was turned off and the server wasn't receiving data.

I've attached some images below to better describe the issue I'm in and the settings in the query and rule.

**What you expected to happen**:
I expected the alert to see the same data that was being displayed in the graph.

**How to reproduce it (as minimally and precisely as possible)**:
- Set up an InfluxDB database with collectd data
- Install Grafana on another server
- Create datasource with collectd database
- Create query to get data-transfer rate
- Set up alert and notification

**Anything else we need to know?**:
Grafana is running on a different machine than the one I am using.
InfluxDB is also on my machine.

**Environment**:
- Grafana version:
Grafana v6.2.5

- Data source type & version: 
Influxdb v1.7.7

- OS Grafana is installed on: 
Ubuntu 18.04.2 LTS

- User OS & Browser: 
Ubuntu 18.04.3 LTS

- Grafana plugins:
- Others:

![grafana_data](https://user-images.githubusercontent.com/12102735/62715870-49db7a00-b9cf-11e9-8a03-24d91854a71d.png)
Settings for my datasource.

![grafana_query](https://user-images.githubusercontent.com/12102735/62711246-aab28480-b9c6-11e9-8264-9714b5273768.png)
Query I used shows up properly on the graph.

![grafana_alert](https://user-images.githubusercontent.com/12102735/62711244-aa19ee00-b9c6-11e9-9263-e7f1d3bb23d6.png)
How I set up my alert.

![grafana_test_rule](https://user-images.githubusercontent.com/12102735/62711245-aa19ee00-b9c6-11e9-8c6a-07d953b2780f.png)
Test rule.

![grafana_alert_email](https://user-images.githubusercontent.com/12102735/62711247-aab28480-b9c6-11e9-979b-d53391e23bf4.png)
Email image is shown as empty.

**Comment by hugohaggmark** [comment]
Thanks @Supershark88 for reporting this, we'll look into this.

**Comment by marefr** [comment]
@Supershark88 you have set Access=Browser, please change that to Access=Server.
