### ISSUE TITLE
stale datasource in case of "Could not find plugin definition for data source:"

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#18466]
**What happened**:
* Grafana log is full with errors `lvl=eror msg="Could not find plugin definition for data source: Prometheus"`
* the GUI data source page say "plugin not found, no installed plugin with that id"

**What you expected to happen**:
* i expected to have the ability to remove the malfunction datasource via the GUI.

**How to reproduce it (as minimally and precisely as possible)**:
* don't know.

**Anything else we need to know?**:
* i don't remember playing with plugins, just upgrading all the time from 5.4.x up to 6.2.5. 
* the only way to get rid from the error was by cleaning the line in the sqlite db as suggested here https://community.grafana.com/t/grafana-logs-giving-incorrect-information-about-a-plugin-that-has-been-removed-successfully/4822
* i think that Grafana should allow to remove DataSources from the GUI in such cases.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: prometheus
- OS Grafana is installed on: RHEL 7
- User OS & Browser:
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/6409857/62722344-e5dca400-ba16-11e9-829f-94af5f03d2cc.png)

**Comment by marefr** [comment]
The link you're referring to doesn't seem exactly the same since you can list the datasource in the UI which implies that there are also a row for this datasource in the datasource table. What was the content of the row you deleted from the plugin_setting table? Without that or idea of how this have happened I'm afraid we cannot do anything to handle this in the UI.

**Comment by yarix** [comment]
hi,
here is the data_source table. the problematic line is the second, with "id=2".



id | org_id | version | type | name | access | url | password | user | database | basic_auth | basic_auth_user | basic_auth_password | is_default | json_data | created | updated | with_credentials | secure_json_data | read_only
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 2 | prometheus | prometheus-main | proxy | http://localhost:9020 |   |   |   | 0 |   |   | 1 | {"httpMethod":"GET","keepCookies":[]} | 05/08/2018 13:10 | 08/08/2019 16:13 | 0 | {} | 0
2 | 1 | 1 | Prometheus | Prometheus | proxy | http://vm-qa:9090 |   |   |   | 0 |   |   | 0 | {"graphiteVersion":"1.1","tlsAuth":true,"tlsAuthWithCACert":true} | 20/11/2018 15:11 | 07/01/2019 9:13 | 0 | {"tlsCACert":"someString","tlsClientCert":"someString","tlsClientKey":"someString"} | 1
4 | 1 | 2 | camptocamp-prometheus-alertmanager-datasource | alert-manager-main | proxy | http://localhost:9023/alertmgr/ |   |   |   | 0 |   |   | 0 | {"keepCookies":[],"severity_critical":"4","severity_high":"3","severity_info":"1","severity_warning":"2","timeInterval":"15s"} | 14/02/2019 12:49 | 08/08/2019 16:13 | 0 | {} | 0

**Comment by marefr** [comment]
There's wrong type, should be lowercase prometheus. Have no idea how you managed to create that, maybe through api/provisioning?

**Comment by yarix** [comment]
while i do understand that the issue result from wrong type, it represent a buggy behavior of Grafana.  

It's reasonable that someone will have a typo in the provisioning / api calls. The problem (bug) is that there is no way to easily fix the typo or remove the datasource. The only way is by deleting the line from the DB.... not something that normal user (editor or even admin) should do.

suggestion to fix:
1. when clicking "bad" datasource, grafana should load it and allow user to edit or delete it.
OR:
2. add delete button next to each data-source when showing the list of available datasouces,
