### ISSUE TITLE
Selecting multiple series from graph legend

### ISSUE THREAD

**Issue by Etzku** [grafana/grafana#18477]
**What would you like to be added**:
An option to enable selecting multiple series from a graph's legend.
So if I select one series from the legend the view would be as it is now...
![image](https://user-images.githubusercontent.com/50619212/62763925-5c1feb80-ba95-11e9-8566-b67ec72b47d6.png)
...and if I were to click another, that series would be displayed as well. Clicking a series again would undo the selection.

**Why is this needed**:
This would make it easier to compare certain series against each other. 

Currently if you have a lot of different series that you'd potentially want to compare, you seem to have two options: Make a with all of those series, or make a lot of graphs with only a select view of those series. The first option gets confusing quickly as the number of series increase. With the second option different possible combinations for required graphs rises exponentially as the number of series increase.

One can sort of achieve this with variables, but those get hidden in view mode.

**Comment by torkelo** [comment]
You can hold shift while clicking to do this

**Comment by 8nich** [comment]
Can this nice behaviour also be achieved on mobile devices?

**Comment by maxim-kukushkin** [comment]
This is a valid question. Any reply to this?

**Comment by mayouzi** [comment]
> You can hold shift while clicking to do this

great

**Comment by patrickgohier** [comment]
> Can this nice behaviour also be achieved on mobile devices?

+1 (I currently have 3 different users asking for this in our environment)

**Comment by anlct** [comment]
Same

**Comment by vguna** [comment]
Same @ mobile.

**Comment by s3ta** [comment]
+1 for a possibility to select multiple values in legend on touch devices

**Comment by WEIZIBIN** [comment]
same
