### ISSUE TITLE
React Graph: Make onSelectionChanged work

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#18476]
**What would you like to be added**:
When solving #17302 we introduced the ability to select in the React Graph. That was only "hooked" up in the Explore part and not for GraphPanel. During this we should also explore the possibility make this prop more generic as suggested here: https://github.com/grafana/grafana/pull/18475#discussion_r312927518

**Why is this needed**:

**Comment by torkelo** [comment]
TODO

* Rename Graph prop onSelectionChanged -> OnHorizontalRegionSelected 
* Make it a bit more data agnostic (fromX toX) and not assume time x axis
