### ISSUE TITLE
Elasticsearch support

### ISSUE THREAD

**Issue by carlosvega** [grafana/grafana#1847]
It would be nice to be able of getting data from elasticsearch, like, mixing data sources. InfluxDB is perfect for timeseries but supporting both would be awesome. Are you planning this?

**Comment by torkelo** [comment]
at some point yes, maybe this year, depends on time and priorities or if a good PR comes a long :)

will close this as there already is an issue for this. 
https://github.com/grafana/grafana/issues/1034
