### ISSUE TITLE
Panel timeshift without relative time override

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#1848]
Timeshift doesn't seem to work when selecting Singlestat - the error message is "Invalid Timeshift"

**Comment by torkelo** [comment]
Works great: 
http://play.grafana.org/dashboard/db/timeshift-singlestat?panelId=18&fullscreen&edit

must end with `h`, `m`,  `d`, etc  (valid time period

**Comment by agaon** [comment]
Thanks. Guess i'm rusty with the logic of the timeshift - I though (for singlestat) that you can just add the timeshift without adding the "override relative time".

**Comment by torkelo** [comment]
Hm.. strange, did not test that. You should not have to select relative time override
