### ISSUE TITLE
Chore: Rename everything related to Popper

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18484]
We are using a tooltip component named popper but somehow that has leaked into a bunch of public type & component names. 

I would like us to rename these and make sure there nothing Popper specific (in name or implementation) that is leaking to users of the tooltip components (to our code or plugins that use @grafana/ui) 

Worst offender is PopperContent 
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Tooltip/PopperController.tsx#L10

**Comment by dehrax** [comment]
Any suggestion on what it might be called other than `Popper`? Just call it `Tooltip` instead?

**Comment by dehrax** [comment]
`Popper.tsx` seems to only be used in `Tooltip.tsx`, so we probably shouldn't export it via `index.ts`

**Comment by dehrax** [comment]
https://github.com/grafana/grafana/blob/63f47fd8e2911a9106acae1c5ecd3526dd31db6f/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx#L12

Is `<Tootltip/>` a better option here?
