### ISSUE TITLE
Alternative for $__range variable when relative time used

### ISSUE THREAD

**Issue by StupidScience** [grafana/grafana#18485]
**What would you like to be added**:
I think that in Grafana should be variable same as $__range but for cases when you use panel relative time.

**Why is this needed**:
When you create a panel with relative time $__range variable still depends on time in the timepicker. So there is no way to use it. So as I can see there are two ways:
- make it dependent on panel relative time
- introduce a new variable

**Comment by torkelo** [comment]
What data source do you use? $__range should always be pane time specific so if you have a time range override in the panel the __range should change

**Comment by StupidScience** [comment]
Hi @torkelo, I was trying to use it with Prometheus.

Oh, sorry. Looks like after update to 6.3.2 it works as you described.
Problem was on 6.2.1
