### ISSUE TITLE
data is in consistent

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1849]
Hi Torkel:

Using graphite functions, 

I am trying to create hourly summary and 95th percentile. I am noticing that 95th percentile is a lot higher than max. Any ideas why that may be?
![img](https://cloud.githubusercontent.com/assets/3009225/7276823/75e085d4-e8da-11e4-8709-838ad67fb31b.png)

**Comment by torkelo** [comment]
not sure, what is the time range? 1 month, 1 week?  Try adding consolidateBy(max) graphite function to change the point consolidation to max (it defaults to avg in graphite). 

Why do you have white borders around the query rows?

**Comment by gsaray101** [comment]
I wanted to hide the server names. I applied consolicateBy(Max) as below, nothing changed:
![img1](https://cloud.githubusercontent.com/assets/3009225/7277060/b4610918-e8db-11e4-8f3b-b818cd2a1c8d.png)

**Comment by gsaray101** [comment]
it is 3 weeks of data, I am trying to summarize it hourly.

**Comment by torkelo** [comment]
did you try with consolidate by on both the nPercentile series and the regular?

![image](https://cloud.githubusercontent.com/assets/10999/7277245/3c2397ac-e90f-11e4-9e6e-8070a6ae32d1.png)

Works for me, with consolidateBy(max), the non percentile max i always higher than the p95 max

**Comment by torkelo** [comment]
remember you always need to apply consolidateBy(max) max to be correct,  same is true for min & sum

**Comment by gsaray101** [comment]
Torkel:

I need to put traffic -in and out on the same chart. In above xaxis and out below xaxis. I was trying to use scale(-1) to place traffic out below axis. I think that is making the calculation wrong. Any other way I can try to place traffic out below xaxis. Here is my query.
![img2](https://cloud.githubusercontent.com/assets/3009225/7277611/f25ff9f6-e8de-11e4-9e39-011a80d3dc30.png)

**Comment by torkelo** [comment]
No, scale -1 is the way currently, but of course that effects max

**Comment by gsaray101** [comment]
this looks like a bug to me?

**Comment by torkelo** [comment]
in what way? 10 > -10 last time I checked :)

**Comment by torkelo** [comment]
or -200 KiB > -10MiB

**Comment by gsaray101** [comment]
I see what you saying. So any ideas how would be show values below xaxis?

**Comment by torkelo** [comment]
a new series override display style I think, and a chart series transformation

**Comment by torkelo** [comment]
that is it would have to be a new feature, and take some time to implement
