### ISSUE TITLE
multiple LDAP is not working

### ISSUE THREAD

**Issue by vpapas** [grafana/grafana#18491]
Hello,

After upgrading to the latest version (grafana-6.3.2-1) using muliple ldap servers for authentication is not working. 
It seems that it uses only the first LDAP server in ldap.toml file. 

We are running Grafana on Centos 7.6.
We have 2 LDAP servers on ldap.toml. I can login successfully when i login using LDAP server A, but i can not login using LDAP Server B. Only when i removed Server A i could login using Server B. 
 
Can you, please, check it?

Thanks.

**Comment by markelog** [comment]
Hi there.

Confirmed! Thank you for the report

**Comment by mooneym17** [comment]
do we have any update on this?
