### ISSUE TITLE
Infinite loop in PanelQueryState

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#18499]
I'm trying to develop a panel plugin and while figuring the proper data format, 
I stumbled upon this loop where it loops infinitely when `results` is object, eg. `{}`. 

https://github.com/grafana/grafana/blob/5f4b5dfecdd412ab7d2555abac62f2acd2ea8be2/public/app/features/dashboard/state/PanelQueryState.ts#L358-L362

The code get transpiled into something like 

```js
    try {
        for (var results_1 = tslib__WEBPACK_IMPORTED_MODULE_0__["__values"](results), results_1_1 = results_1.next(); !results_1_1.done; results_1_1 = results_1.next()) {
            var r = results_1_1.value;
            if (r) {
                series.push(Object(_grafana_ui_src_utils__WEBPACK_IMPORTED_MODULE_5__["guessFieldTypes"])(Object(_grafana_ui_src_utils__WEBPACK_IMPORTED_MODULE_5__["toSeriesData"])(r)));
            }
        }
    }
    catch (e_3_1) { e_3 = { error: e_3_1 }; }
    finally {
        try {
            if (results_1_1 && !results_1_1.done && (_a = results_1.return)) _a.call(results_1);
        }
        finally { if (e_3) throw e_3.error; }
    }
``` 

and loops infinitely.

I still haven't figure out how to proceed through this with my new panel plugin so it's hard to further elaborate. Type for `results` is `any[]` so passing `{}` is obviously wrong but I managed to do that through my datasource. IMO should be handled before the infinite loops is triggered.

**Comment by ryantxu** [comment]
How are you sending the data?  This gets called from the response { data:[...] }

are you sending: { data:{ your object } }?

**Comment by simPod** [comment]
@ryantxu yes, just an object

**Comment by ryantxu** [comment]
ok, it needs to be an array, and we should throw an error if it is not :)

**Comment by simPod** [comment]
I'll try to send PR. 

❤️ typings are finally in Grafana btw
