### ISSUE TITLE
Make singlestat multi-series friendly like gauge

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#18495]
In https://github.com/grafana/grafana/issues/15244 there are improvements to the Gauge panel to help it behave correctly when presented with multiple series (e.g multiple disk volumes per host with a collection of hosts.) It would be good if similar support could be added to Single Stat.

**Comment by hugohaggmark** [comment]
Thanks for your contribution @yellowpattern! It seems like we'll be migrating it to Gauge moving forward here #14554. I'll close this issue because of that but we can reopen it when needed.
Thanks
Sort of duplicate of #14554
