### ISSUE TITLE
Table value rendered link added protocol and domain in the URL while absolute URL is supplied

### ISSUE THREAD

**Issue by e88z4** [grafana/grafana#18494]
**What happened**:
When using rendering value as a link in table panel, the link URL added an extra "localhost:8080" when constant variable is used. The constant has an absolute URL such as "http://mydomain.com:1234". It seems grafana treats the link url value as a relative path.

**What you expected to happen**:
When the constant variable is used, the link URL should be rendered as it is when the constant contains absolute URL.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create constant variable value such as "http://mydomain.com:1234"
2. Select new panel
3. Select table panel as visualization
4. Select render value as link in column style. 
5. Fill the link URL value with "$myconstanst/${__cell:raw}

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Influx 1.7.6
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: Table panel plugin

**Comment by hugohaggmark** [comment]
Thanks for contributing @e88z4! If you change your URL value to `${myconstants:raw}/${__cell:raw}` does it work then?

**Comment by e88z4** [comment]
Hi @hugohaggmark ,

Adding :raw attribute works. Thank you very much for your direction.

**Comment by e88z4** [comment]
Hi @hugohaggmark ,

Sorry, adding :raw attribute didn't work (I forgot to hit the save button previously). Is this a bug or the expected behavior?

**Comment by hugohaggmark** [comment]
That's really odd I got it to work with this: `${google:raw}/search?q=${__cell:raw}` where google is a constant variable that contains this:
![image](https://user-images.githubusercontent.com/562238/62866681-b927d580-bd11-11e9-99c0-d0ca7dc5c13a.png)

![image](https://user-images.githubusercontent.com/562238/62866710-cb097880-bd11-11e9-9519-cc1114591b49.png)

As you can see in the bottom of the last picture the url is correct. Could you please try again?

**Comment by e88z4** [comment]
Hi @hugohaggmark ,

I had a spelling mistake in my variable name. It is working as expected. Sorry for the trouble. Closing this issue.
