### ISSUE TITLE
Elasticsearch: Making metric field dropdown support nested sub menus for deep object fields

### ISSUE THREAD

**Issue by barakakoun** [grafana/grafana#18496]
Today on elasticsearch, the dropdown of the metric field isn't practical enough.
If you want to find a specific fileld you need to scroll through the endless dropdown.

It'd be great if the dropdown of the metrics fields be nested, with sub-dropdowns, so it will be faster and easier to find the field you're looking for.

**Comment by davkal** [comment]
Could use our cascader component for this.

**Comment by davkal** [comment]
Will revisit this in general overhaul of Elastic.
