### ISSUE TITLE
Public snapshots: Not able to see data points in snapshots

### ISSUE THREAD

**Issue by santakd** [grafana/grafana#18490]
**What happened**:
**Snapshots show no data points**

**What you expected to happen**:
**Expected to see the data points in the snapshot**

**How to reproduce it (as minimally and precisely as possible)**:
**Create a snapshot**

**Anything else we need to know?**:
**It was working fine for 6.2.5**

**Environment**:
- Grafana version: 6.3.0
- Data source type & version: InfluxDB 1.7.7
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac OS Mojave , FF and Chrome
- Grafana plugins:
- Others: sample snapshot
 https://snapshot.raintank.io/dashboard/snapshot/YPLVhsXGZhunPXkTugeXPQ2roviyC9cB

**Comment by marefr** [comment]
@torkelo why is this in general backend, need to upgrade Grafana snapshot instance?

**Comment by torkelo** [comment]
yes need to update it

**Comment by santakd** [comment]
Did upgrade to 6.3.5 and seeing the issue
Please can someone update this ticket with the build when this will be fixed

Thanks

**Comment by santakd** [comment]
Environment:

    Grafana version: 6.3.5
    Data source type & version: InfluxDB 1.7.8
    OS Grafana is installed on: Ubuntu
    User OS & Browser: Mac OS Mojave , FF and Chrome
    Grafana plugins:
    Others: sample snapshot
    https://snapshot.raintank.io/dashboard/snapshot/YPLVhsXGZhunPXkTugeXPQ2roviyC9cB

**Comment by lbsou** [comment]
Same problem here when updating from 6.2.5 to 6.3+

**Comment by howardjohn** [comment]
Is there any plans to fix this? I used this a lot on older grafana and have been missing it since upgrading

**Comment by lbsou** [comment]
Hi guys!  We need this functionnality working before upgrading. 

@torkelo @marefr  :  Is this bug assigned? We see it as "removed from Inbox in Backend Squad" on 27 sept.

Thanks for your great work!

**Comment by marefr** [comment]
We've had some issues upgrading the public snapshots server due to problem with database migration and it needs more time and work than we initially thought. We're planning to fix this, but we need to figure out how to solve it and assign someone to do the work. Sorry for the inconvenience this may cause.

**Comment by Golempl** [comment]
Any chance to make it working ? I see no data point on exported snapshots to raintank

**Comment by marefr** [comment]
Public snapshot server now runs Grafana v6.5.2 so closing this.

**Comment by lbsou** [comment]
Thanks!
