### ISSUE TITLE
Support Redis SSL for Remote Cache and Ensure it works with Azure Redis

### ISSUE THREAD

**Issue by chelnak** [grafana/grafana#18498]
**What happened**:
We current lyhave an Azure Redis instance handling caching.. however it appears the connection string format is no longer supported.

After upgrading to 6.2.3 from 6.2.2 we errors when grafana tries to initialize the remote_cache.

E.g:

```
t=2019-08-09T20:29:02+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: incorrect redis connection string format detected for 'xxxxx.cache.windows.net:6380', format is key=value,key=value"
```

The above issue can be solved by adding **app=** at the beginning of the connection string. This was never a hard requirement before 6.2.3.

Also the switch statement that handles the parse does not support the **ssl** or **abortConnect** parameter so once the error above is fixed it still fails when it cannot match them.

```
		default:
			return nil, fmt.Errorf("unrecorgnized option '%v' in redis connection string", connVal)
		}
```

**What you expected to happen**:
The configuration should successfully parse as per 6.2.2

**How to reproduce it (as minimally and precisely as possible)**:
Use an Azure Redis connection string for remote_cache in Grafana 6.2.3.

**Anything else we need to know?**:
It changed here: 
https://github.com/grafana/grafana/commit/c09fe3c3b492836290b0b1868acb0883997e88e0#diff-7fcdc3fcca7d4a9afb2bc975cc548b2b

**Current Azure Redis connection string format:**
```
xxxxxx.windows.net:6380,password=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=,ssl=True,abortConnect=False
```

**Environment**:
- Grafana version: 6.2.3+
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this @chelnak! We'll look into this.

**Comment by torkelo** [comment]
Are you sure you did not upgrade to 6.3.2 ? 

Think it's due to this change: https://github.com/grafana/grafana/pull/18204

**Comment by chelnak** [comment]
@torkelo This was broken as of this PR: https://github.com/grafana/grafana/pull/17483

https://github.com/grafana/grafana/pull/18204 Fixed a different issue with the connection string.

**Comment by kylebrandt** [comment]
@chelnak I don't think SSL would have been working before based on what I see in the code? What did you use for your setting before the change? (with password obscured of course)?

Adding ssl shouldn't be a problem, but I don't see anything for `abortConnect` in our go redis library.

**Comment by chelnak** [comment]
It's currently set to this:

```
[remote_cache]
connstr = xxxxxx.cache.windows.net:6380,password=xxxx=,ssl=true,abortConnect=false
```

It looks to like the code previously just passed the connection string to the library:

```
Addr:    opts.ConnStr,
```

I've only skimmed the library documents but maybe it was clever enough to handle SSL and also disregard any parameters that it didn't know about gracefully?

**Comment by kylebrandt** [comment]
It seems v5 is the first version of the lib to add TLS. So will need to update to 5 or 6 for ssl.

**Comment by chelnak** [comment]
Interesting. So maybe redis never worked as we expected.

**Comment by kylebrandt** [comment]
@chelnak Based on two issues reported in https://github.com/grafana/grafana/issues/17377 that led to this change - I'm assuming that is the case for now since I can't see how it would have worked. 

Seems like a better use to time just to add SSL support at this point.

**Comment by chelnak** [comment]
Indeed! Do you think it’s worth while adding graceful handling of unknown
parameters rather than raising an exception?

I’d be interested to know if other Azure users have encountered problems
too!

Thanks for replying so quickly!
