### ISSUE TITLE
grafana/toolkit: Introduce scaffolding task

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#18506]
`grafana-toolkit plugin:create` - to bootstrap minimal version of Grafana extension

- [ ] Setups dir structure
- [ ] Creates package.json with basic deps and scripts
- [ ] Creates basic configs (tsconfig, lint, prettier etc.)

**Comment by ryantxu** [comment]
We would need three versions:
* react panel: https://github.com/grafana/simple-react-panel
* angular panel: https://github.com/grafana/simple-angular-panel
* datasource.  Not sure the best example yet

I want to make sure the 'source' files are a functioning repositories.  maybe `plugin:create` could ask:
1. ask questions: type, name, org, etc
2. download from a template repository
3. run a script to update any values and rename some files

**Comment by torkelo** [comment]
> I want to make sure the 'source' files are a functioning repositories.

What do you mean? 

The source files will be templated so wont work as functioning plugin (I think) 

> download from a template repository

Think the templated files should be part of the toolkit, or I assume that is how react-create-app and others do.

**Comment by dprokop** [comment]
> Think the templated files should be part of the toolkit, or I assume that is how react-create-app and others do. But downloading might work as well.

create-rect-app has the template shipped with the code. Cloning from github has an advantage that we don't need to publish toolkit when the template changes. I'm gonna try it out.

**Comment by dprokop** [comment]
@ryantxu not sure this is that big of task. We can support react/angular panel scaffolding first and add datasource plugin template later on. We don't have to prioritise that for 6.4 but if we have time it woudld be good to have complete set of tasks available.
