### ISSUE TITLE
Docs feedback: features/datasources/testdata.md

### ISSUE THREAD

**Issue by educfn** [grafana/grafana#18500]
It seens this plugin was discontinued. Please do confirm if it´s really the cause.

**Comment by hugohaggmark** [comment]
Hi @educfn and thanks for contributing! I use this plugin daily so it hasn't been discontinued and is part of the internal Grafana plugins, but you do have to add the datasource yourself from datasources list.
I'll close this for now but we can always reopen it if needed.

![image](https://user-images.githubusercontent.com/562238/62851655-1a867f00-bce7-11e9-8cb0-b98dbd3fd9e1.png)
