### ISSUE TITLE
Refactor: refactor usages of React's deprecated lifecycle methods

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#18503]
We are about to bump react to 16.9.0. Is's time to fix the usages of unsafe lifecycle methods: https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods

**Comment by dehrax** [comment]
Did a search and it seems like #18526 covers all of them

**Comment by dprokop** [comment]
@dehrax yeah, but we wanna get rid of those methods. So remove the UNSAFE_xxx usages at all

**Comment by boyskila** [comment]
Hi! If no one is working on this I can take a look.

**Comment by davkal** [comment]
Sure! I suggest the following plan, ideally in 3 separate PRs for easy rollback:

- [ ] upgrade React to 16.12
- [ ] refactor UNSAFE_ methods in query fields
- [ ] refactor UNSAFE_ methods everywhere else

**Comment by boyskila** [comment]
Awesome! Thanks!

**Comment by boyskila** [comment]
> * upgrade React to 16.12

@davkal are we going to target all future minor and patches versions or to hardcode it to 16.12.0?

**Comment by dprokop** [comment]
> @davkal are we going to target all future minor and patches versions or to hardcode it to 16.12.0?

@boyskila we use fixed versioning
