### ISSUE TITLE
$__unixEpochGroup() doesn't handle timestamps

### ISSUE THREAD

**Issue by lacksfish** [grafana/grafana#18507]
**What happened**:

While setting a query, I noticed some odd behaviour of the $__unixEpochGroup function regarding timestamps.b The timestamp I want to use is a timestamp without timezone, but the same error happens for timestamps with timezones.
 
**What you expected to happen**:

The query should work as is.

**How to reproduce it (as minimally and precisely as possible)**:

This query is the problem:

```
SELECT
  $__unixEpochGroup("timestamp", $interval) AS "time",
  i.name AS metric,
  sum(c.notional_usd) AS notional_usd
FROM candles AS c
INNER JOIN instruments AS i ON c.instrument_id = i.id
WHERE i.kind = 'future' AND i.active = True
AND timestamp >= $__from AND timestamp <= $__to
GROUP BY i.name, time
ORDER BY time
```

Results in this error:
```
pq: operator does not exist: timestamp without time zone / integer
```

I even tried things like:
```
SELECT
  $__unixEpochGroup(CAST(EXTRACT(EPOCH FROM "timestamp") AS INTEGER), $interval) AS "time",
...
```

which results only in:
```
macro __unixEpochGroup needs time column and interval and optional fill value
```

**Anything else we need to know?**:

**Environment**: Dockerized
- Grafana version: 6.3.2 (commit: 4832460)
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins: None
- Others: ---

Any help on how to actually work with timestamps on these macros would be highly appreciated.

Thanks

**Comment by marefr** [comment]
Use `timeGroup` if your column is not epoch format, see https://grafana.com/docs/features/datasources/postgres/#macros

**Comment by lacksfish** [comment]
The timestamp column is of the type `TIMESTAMP`, shouldn't this work with $__unixEpochGroup.

It'd simply be nice to use `TIMESTAMP` data type, right now I am forced to use `BIGINT`.

**Comment by lacksfish** [comment]
$__unixEpochGroup(dateColumn,‘5m’, [fillmode]) | Same as $__timeGroup, but for times stored as unix timestamp (only available in Grafana 5.3+).
-- | --


Seems it should work with `TIMESTAMP` data type in PostgreSQL, but I'm telling you it doesn't.

**Comment by lacksfish** [comment]
Give it a swirl, maybe it works for you.

Thanks anyways for closing the ticket prematurely.

**Comment by marefr** [comment]
> Seems it should work with TIMESTAMP data type in PostgreSQL, but I'm telling you it doesn't.

It says "times stored as unix timestamp" which means that they should be stored as integers (seconds since 1970)

**Comment by lacksfish** [comment]
Maybe I am misunderstanding the purpose of `$__unixEpochGroup()`, but I would've used it based on intuition together with standard PostgreSQL TIMESTAMP data, but maybe of course this is considered misuse of the function.

All I'm saying, maybe there isn't too much difference between TIMESTAMP and what should be considered an "epoch"... anyways, I'll use BIGINTs for now to appease the provided grafana function.

**Comment by lacksfish** [comment]
Perhaps @torkelo or @bergquist could drop some more info on this?

I'm basically just trying to say fixing this will make usage of TIMESTAMPs nicer ... And I'd argue it should work with `$__unixEpochGroup()`

**Comment by marefr** [comment]
You can see implementation of `__timeGroup` macro here: https://github.com/grafana/grafana/blob/master/pkg/tsdb/postgres/macros.go#L114-L118

And `__unixEpochGroup` here: https://github.com/grafana/grafana/blob/master/pkg/tsdb/postgres/macros.go#L153

If you have suggestion how these two macros can use the same implementation supporting both timestamps and epocs your welcome to open a PR.
