### ISSUE TITLE
Toolkit: export e2e test scaffolds and plugin reports

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18513]
The toolkit contains classes that are used internally, but also used in other projects.

**e2e** 
https://github.com/grafana/grafana/tree/master/packages/grafana-toolkit/src/e2e
is imported here:
https://github.com/grafana/grafana/blob/master/public/e2e-test/scenarios/smoke.test.ts#L3

**plugins**
https://github.com/grafana/grafana/tree/master/packages/grafana-toolkit/src/plugins
is imported by:
https://github.com/grafana/plugin-ci-app  (private repo)

To get this to work, I hacked this:
https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/cli/tasks/toolkit.build.ts#L121

this is obviously not the right way to do this :)

Ideally these could each be in their own namespace.  Perhaps:
```
import { ... } from '@grafana/toolkit/e2e`
```
```
import { ... } from '@grafana/toolkit/plugins`
```

**Comment by dprokop** [comment]
Trying to be quite pragmatic here. I think we should consider grafana-toolkit (from external contributor POV) as CLI only. This means:
1. Use case for "plugin" context described above is not a natural thing for the toolkit. For such cases I would suggest importing using full path of the file `import { ... } from '@grafana/toolkit/plugins'` - you already can do that
2. Use case for e2e tests is internal and I don't think it's a problem to import it in the core app like this: `import { ... } from @grafana/toolkit/src/e2e`

So I would get rid of toolkit/src/index.ts file at all and remove https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/cli/tasks/toolkit.build.ts#L121
