### ISSUE TITLE
Unable to add influxdb as datasource

### ISSUE THREAD

**Issue by phaoost** [grafana/grafana#18510]
**What happened**:

I am trying to add influxdb datasource. It's not accepting datasource url. I was trying:
/run/influxdb/influxdb.sock
unix:/run/influxdb/influxdb.sock
unix://run/influxdb/influxdb.sock
unix:///run/influxdb/influxdb.sock

I verified /run/influxdb/influxdb.sock has 0666 permissions

The datasource url field remaining red at all times, when I try to add I get 502 error message and url gets blank

**What you expected to happen**:

I expected datasource will be added.

**How to reproduce it (as minimally and precisely as possible)**:

Try to add datasource socket path.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: influxdb 1.7.7-1
- OS Grafana is installed on: Devuan Beowulf
- User OS & Browser: Chromium

**Comment by marefr** [comment]
Duplicate of #8991
