### ISSUE TITLE
Explore/Query Field: Error when deleting all text and blurring component

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#18518]
**What happened**:
Selected all text in a query field and remove it, then an error occurred when clicking off the query field.

**What you expected to happen**:
For an error not to occur.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to Explore, choose Prometheus as data source
- Enter some text in the query field
- Press Ctrl+a / mod+a and then backspace/delete to remove all text
- Click off the query field
- Notice the error

**Environment**:
- Grafana version: Grafana v6.4.0-pre (commit: ab17015794)
- Data source type & version: Prometheus, master
- OS Grafana is installed on: macOS High Sierra
- User OS & Browser: macOS High Sierra, Mozilla Firefox 68.0.1

**Comment by aocenas** [comment]
Hey @kaydelaney do you mean this warning under the text field?
<img width="521" alt="Screenshot 2019-08-28 at 10 37 28" src="https://user-images.githubusercontent.com/1014802/63839637-edd99500-c97f-11e9-90fa-85a53047ce77.png">
Otherwise I do not get any error.

**Comment by kaydelaney** [comment]
@aocenas it was causing a hard error, like a crash, but I think it's since been fixed by https://github.com/grafana/grafana/pull/18599, so I'm fine with closing this issue.
