### ISSUE TITLE
Share: Direct link rendered image returns 404

### ISSUE THREAD

**Issue by Dinoshauer** [grafana/grafana#1851]
Hello!

I'm using the stable version of grafana 2 (this happened in beta3 as well though), and I'd like to share a rendered image but when I click the link it seems like it's rendering from the logs and then it returns a 404 when it's done.

I have an ELB infront of a couple of nginx'es and then there's the grafana backend behind it

Let me know if you need any more info from me.

**Comment by torkelo** [comment]
what os and what package did you use to install grafana?

**Comment by Dinoshauer** [comment]
I'm on ubuntu 14.04 on EC2 and installed it with https://grafanarel.s3.amazonaws.com/builds/grafana_2.0.1_amd64.deb

**Comment by torkelo** [comment]
can you show me the grafana log output for the time when you get the 404?  Also go into /usr/share/grafana/vendor/phantomjs/   and try executing the phanomtjs binary there (see if you get any errors)

**Comment by Dinoshauer** [comment]
Here's the log output

```
2015/04/23 07:05:47 [I] PhantomRenderer::renderToPng url https://my-grafana-site.com/dashboard/solo/db/my-dashboard?panelId=3&fullscreen&from=now-1h&to=now&width=1000&height=500
2015/04/23 07:05:57 [I] Completed /render/dashboard/solo/db/my-dashboard 404 Not Found in 10.002433987s
```

And here's the output from phantomjs. Looks like something's up here

```
/usr/share/grafana/vendor/phantomjs$ . phantomjs                                                                                                                    
-bash: .: phantomjs: cannot execute binary file
```

**Comment by torkelo** [comment]
strange, cannot execute binary file? no one has reported that yet :) I run the same binary on ubuntu 14, 

Try download phantomjs and replacing that binary, see if you can get it to work that way. Not sure what is going on

**Comment by Dinoshauer** [comment]
Any specific version? Do you know if there's a direct link to the binary somewhere?

**Comment by torkelo** [comment]
https://code.google.com/p/phantomjs/downloads/detail?name=phantomjs-1.9.2-linux-x86_64.tar.bz2&can=2&q=

**Comment by Dinoshauer** [comment]
Same error with the above binary

```
~/phantomjs-1.9.2-linux-x86_64$ . bin/phantomjs 
-bash: .: bin/phantomjs: cannot execute binary file
```

**Comment by torkelo** [comment]
sure you are on 64bit linux?

**Comment by Dinoshauer** [comment]
Pretty sure

```
$ uname -a
Linux hostname 3.13.0-49-generic #81-Ubuntu SMP Tue Mar 24 19:29:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by torkelo** [comment]
something very wrong, that binary works fine for me

Linux TloUbuDesk 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linu

**Comment by Dinoshauer** [comment]
Ah, hang on. Was executing the binary wrong :no_good: 
This is successful.

```
/usr/share/grafana/vendor/phantomjs$ ./phantomjs                                                                                                                    
phantomjs>
```

**Comment by torkelo** [comment]
ok, great, and if you do "wget https://my-grafana-site.com/dashboard/solo/db/my-dashboard?panelId=3&fullscreen&from=now-1h&to=now&width=1000&height=500"   on the box does it return a html page?

**Comment by torkelo** [comment]
my-grafana-site.com should be what was really in the log you pasted in the comment above
```
015/04/23 07:05:47 [I] PhantomRenderer::renderToPng url https://my-grafana-site.com/dashboard/solo/db/my-dashboard?panelId=3&fullscreen&from=now-1h&to=now&width=1000&height=500
```

**Comment by Dinoshauer** [comment]
Can I specify some login details in the request? I'm using oauth with google, but I do have the admin user for regular auth

**Comment by torkelo** [comment]
the authentication for the render request is handled by grafana (it will pass the originl request cookie to phantomjs)

**Comment by kazkuris** [comment]
we are facing same issue as @Dinoshauer and as well as hoe does we are using 3rd party for authentication.
relevant part of config:
[auth.anonymous]
enabled = true
org_name = ORG

[auth.basic]
enabled = false

[auth.proxy]
enabled = true
header_name = X-Auth-Params-Email
header_property = email

any suggestions how to make it working?

**Comment by kazkuris** [comment]
that was this: https://github.com/grafana/grafana/issues/2568
