### ISSUE TITLE
Template Vars not Rendered in JSON Datasource Additional JSON Data

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#18517]
**Datasource Setup**: I created a datasource which acts as an intermediary to a MSSQL instance.  The datasource takes, as metrics, the DB name, and the query is specified under "Additional JSON Data".

**What happened**: The mssql string specified in "query" field of additional JSON data was passed through raw, without parsing template variables and time ranges.

**What you expected to happen**: Template variables and time ranges to be replaced, as in normal datasource.

**How to reproduce it (as minimally and precisely as possible)**: Create a JSON data source, try to pass template variables.

**Anything else we need to know?**: Trying to pass a variable into another key directly, without quotes, results in "unexpected character at position error":
```Unexpected token $ in JSON at position 505```
This should work, per the documentation: https://grafana.com/grafana/plugins/simpod-json-datasource

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: JSON 0.1.4
- OS Grafana is installed on: Windows
- User OS & Browser: Windows / Chrome
- Grafana plugins: JSON
- Others:

**Comment by hugohaggmark** [comment]
Hi again @BrandonQDixon and thanks for contributing! Could you supply more details about the the whole JSON been passed to the datasource. You can use the QueryInspector for this. Thanks

**Comment by torkelo** [comment]
please open issues with this plugin directly to the plugin repo / author: https://github.com/simPod/grafana-json-datasource
