### ISSUE TITLE
JSON datasource proxy returns timeseries

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#18521]
**EDIT:** this is actually an issue with my datasource server, please disregard.

**What happened**: When Grafana JSON proxy fetches timeseries data, it wraps entire response in array, preventing visualization from rendering.

**What you expected to happen**: Data should be returned from proxy to client exactly as it is returned from datasource to proxy.

**How to reproduce it (as minimally and precisely as possible)**: Setup a json data source which will return the following type of response:
```
[{
	"target": "2019-08-09",
	"datapoints": [
		[244, 1565308800000]
	]
}, {
	"target": "2019-08-07",
	"datapoints": [
		[226, 1565136000000]
	]
}, {
	"target": "2019-08-04",
	"datapoints": [
		[261, 1564876800000]
	]
}]
```
The output in Chrome debugger will show the entire thing wrapped in an array, and this entire thing will be the only element.

**Anything else we need to know?**: This does not affect data when type = table.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Windows + JSON
- OS Grafana is installed on: Windows
- User OS & Browser: Windows + Chrome
- Grafana plugins: JSON
- Others:

**Comment by hugohaggmark** [comment]
Hi @BrandonQDixon, do I understand you correctly that this issue should be closed as stated in **EDIT:** this...
