### ISSUE TITLE
Stopping grafana-server on CentOS does not end web client session

### ISSUE THREAD

**Issue by drsprite** [grafana/grafana#1852]
Not sure if this is by design or not, but I would have expected that if I stopped the grafana-server process on CentOS, that the clients connected via web would have stopped receiving updates and/or received a time-out error?

However, when testing today with anonymous access, if I have an anonymous client connected, and I stop the service, the client continues to receive real-time updates through automatic refresh, even though the grafana server is not running.

Thoughts?

**Comment by torkelo** [comment]
depends on how they get metrics,  if you data source access option is configured as "direct" then the browser will fetch metrics directly from you time series server, so dashboards that are auto refresh metrics data will not be affected by a grafana server shutdown

**Comment by torkelo** [comment]
If you change data source access option to proxy, then your browse will start to complain when you shut down the server
