### ISSUE TITLE
Explore: Store DataFrame in state instead of separate graph, table and logsresult

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#18528]
When TimeSeries was replaced GraphSeriesXY we discovered this line https://github.com/grafana/grafana/blob/b3a75cee680d90dd51cd8bc41ebade51a10636f5/public/app/features/explore/QueryRow.tsx#L220 which means that in Explore we query a datasource => convert result to DataFrame => convert series to graphseries and store in graphresult => convert back to DataFrame which is not optimal.

I suggest that we store `PanelData` in the Explore state instead after each query execution (`PanelData` has a series prop that is of type `DataFrame`) and then the different components like Graph, Table and Logs can convert this `PanelData` in state to TableResult, GraphSeriesXY and so forth using the `ResultProcessor` when needed.

An extra bonus with this is that PanelData also includes the following props:
```ts
  state: LoadingState;
  request?: DataQueryRequest;
  error?: DataQueryError;
``` 
that are stored as separate props in the ExploreItemState today.

**Comment by ryantxu** [comment]
I think this is super important... but lets tackle it after #18391
