### ISSUE TITLE
Canvas: Implementing a business intelligence solution

### ISSUE THREAD

**Issue by monolithed** [grafana/grafana#18523]
Hi, is there any plans to implement something like Canvas in Kibana?
Possibly there were active discussions, but I did not find similar issues.
Thanks.

**Comment by hugohaggmark** [comment]
Hi @monolithed, GitHub is mainly used for tracking bugs and feature requests so you have to ask this question on the [community site](https://community.grafana.com/) instead or use the #grafana-dev channel on `grafana.slack.com`.

**Comment by monolithed** [comment]
@hugohaggmark, thanks for your answer, but my question looks like a feature request as well :)
