### ISSUE TITLE
alert shows no data

### ISSUE THREAD

**Issue by seal61** [grafana/grafana#18538]
**What happened**:
alert shows "no data"

**What you expected to happen**:
alert should say "ok" / show no alert

**How to reproduce it (as minimally and precisely as possible)**:
created a health-check for my node with metric 
`up{instance=~"$node:$port",job=~"$job"}`
returns 0 for host down and 1 for host up
graph shows the correct state 
alert configured to evaluate every 1m for 5m
when last() of query(A, 10m, now-5min) below 1 
(also tested other values in query())
no data & error handling is set to:
no data / null --> set state to keep last state
error / timeout --> alerting

**Anything else we need to know?**:
looks like bug 13172 [1] but cant find the setting described.

[1] https://github.com/grafana/grafana/issues/13172

**Environment**:
- Grafana version:
Grafana v6.3.2 (commit: 4832460) 
- Data source type & version:
Prometheus 2.11.1
- OS Grafana is installed on:
Debian 9
- User OS & Browser:
WIndows 10 \ latest firefox
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this @seal61 but it seems your query is using template variables which is [not possible for alerting](https://grafana.com/docs/alerting/rules/#query-condition-example). 

> The query used in an alert rule cannot contain any template variables. 

If that doesn't solve it for you I would suggest reading the [Troubleshooting section](https://grafana.com/docs/alerting/rules/#troubleshooting) as we currently don't have any other reports of this.
