### ISSUE TITLE
SingleStat does not work with DataFrame

### ISSUE THREAD

**Issue by tarekbecker** [grafana/grafana#18536]
If a datasource plugin returns a DataFrame, the "stat" option (avg, min, max) for single stats is missing.

This coding seems related to the issue:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L130-L138

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/editor.html#L6-L17

<img width="530" alt="Screenshot 2019-08-13 at 15 28 16" src="https://user-images.githubusercontent.com/5320817/62945830-c9a68180-bddf-11e9-9c67-6ea71ecdeb70.png">

**Environment**:
- Grafana version: docker run --rm --name=grafana -p 3000:3000 grafana/grafana:master
- Data source type & version: TestDatasource streaming client
- OS Grafana is installed on: mac
- User OS & Browser: chrome
- Grafana plugins: singlestat

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by ryantxu** [comment]
@tarekbecker -- what data source are you using?

I would like to fix this for 6.4 after #18391 -- @torkelo, do you think we need a 6.3 solution?

**Comment by torkelo** [comment]
Any other data sources that returns DataFrame ? If it's only test data source then I think a patch is not critical

**Comment by ryantxu** [comment]
In the builtin plugins, it is only Input Datasource (alpha) and the streaming example in test data.

The splunk streaming may also return DataFrame

**Comment by tarekbecker** [comment]
We use a custom datasource which returns DataFrames. I don't know whether public datasources are affected by this.
