### ISSUE TITLE
Redact Database password for Session:provider_config

### ISSUE THREAD

**Issue by tmonk42** [grafana/grafana#1853]
grafana-2.0.1-1.x86_64
CentOS release 6.6 (Final)

On the admin setting page (/admin/settings) I see that client_secret is redacted for GitHub/Google auth, the password for the Database section, and Admin password and secret_key in the Security section.

In the "Session" section, we should also redact the password for provider config if we're using MySQL as the session provider.

Per the config docs, the provider_config line should be like this if using MySQL: "user:password@tcp(127.0.0.1)/database_name"

**Comment by torkelo** [comment]
Your right, will fix

**Comment by tmonk42** [comment]
Looks like that connection string is making it into the logs as well...
2015/04/22 22:23:23 [I] Database: mysql, ConnectionString: user:passwd@tcp(host:port)/grafana?charset=utf8

**Comment by alvaromorales** [comment]
Was this fixed? I'm running 2.1 and seeing the connection string in the logs, with the unredacted DB username and password.

**Comment by torkelo** [comment]
@alvaromorales the issue only mentioned the admin settings page, did not notice the comment about the logs. Opened a new issue for this.
