### ISSUE TITLE
Can't add datasource Cloudwatch

### ISSUE THREAD

**Issue by prakashraaj046** [grafana/grafana#18530]
i can't add datasource Cloudwatch neither by IAM roles nor by credentials(accesskeys and secret access keys). Everytime i try to click save and test, it throws HTTP internal server error

**Comment by hugohaggmark** [comment]
Hi @prakashraaj046 and thanks for reporting this! Could you please supply a bit more information like the following:
Environment:
Grafana version: 
Data source type & version: 
OS Grafana is installed on: 
User OS & Browser:
Grafana plugins:
Others: none

Thanks

**Comment by prakashraaj046** [comment]
Environment: AWS Amazon ECS Cluster (Deployed as EC2 Instance)
Grafana version: 6.3.2
Data source type & version: Cloudwatch 5.0.0
OS Grafana is installed on: Amazon Linux AMI
User OS & Browser: Windows 10 Enterprise &Chrome Browser
Grafana plugins: Cloudwatch

**Comment by hugohaggmark** [comment]
Thanks @prakashraaj046 can you also supply any logs and/or Chrome console logs?

**Comment by prakashraaj046** [comment]
yeah sure

**Comment by prakashraaj046** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by prakashraaj046** [comment]
@hugohaggmark that is the log i received when i input my access credentials

**Comment by hugohaggmark** [comment]
For that version of docker build I can't repro your issue. Have you followed the instructions [here](https://grafana.com/docs/features/datasources/cloudwatch/#iam-policies)?

**Comment by prakashraaj046** [comment]
yeah @hugohaggmark i followed the documentation. i deployed as said  in the documentation

**Comment by hugohaggmark** [comment]
Are you using IAM user? Then please go ahead and double check that you have set the correct policies.

**Comment by prakashraaj046** [comment]
I'm IAM user with full access across all resources in the AWS console

**Comment by hugohaggmark** [comment]
Ok, so that's exactly what I tried and I had no problem adding the CloudWatch datasource. Also I haven't seen any other reports about this. Could probably be something in your particular setup/configuration that is not working. Try to run the same docker image locally from your desktop with the same credentials and see if the same problem occurs.

I'm closing this issue for now but it can be reopened if needed.
Thanks
