### ISSUE TITLE
Orphan Hover tooltip created when changing time range while mouse hovering over dashboards 

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#18533]
**What happened**:
Change time range while hovering mouse over dashboard, some of the hovered tiptool are left to screen when time range change.

**What you expected to happen**:
No orphan Hover tooltip left to screen.

**How to reproduce it (as minimally and precisely as possible)**:
Dashboard has to be relative complex. Complex means tens of template variables which takes few second to populate. Also shown dashboard need to be complex for example drawing 100 repeating graph. Dashboards need to have Hover tooltips enabled (descending in my case).
Then simply change time range from pull down menu or by selecting area with mouse.
If there is dashboard below when time range selection is done and hover tooltip is shown (hovering stay visible) or you move the mouse so that Hovering is activated when "time range change" is in progress the tooltip will be left orphan with high probability. In my case probability is > 50%. In normal usage the Dashboard get corrupted after few time range change (zooming).

![image](https://user-images.githubusercontent.com/19704268/62933824-c2757880-bdcb-11e9-97d7-923b9b613d72.png)

Once Hover tooltip is left Orphan the Dashboard becomes unusable, and new Grafana instance needs to be started.

**Anything else we need to know?**:
If Dashboard is simple like repeating only 1 graph then issue is not seen.

**Environment**:
- Grafana version: 6.32
- Data source type & version: Prometheus
- OS Grafana is installed on: RedHat
- User OS & Browser: Windows 7, Chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks again @jtorkkel for contributing, we're gonna take a look at this and see if we can reproduce it.

**Comment by jtorkkel** [comment]
I managed to reproduce it with simplified dashboard attached.

Repro Dashboard has two template variables, which are reloaded on "time range change".  Time Range Change trigger the issue. We need to use Time Range Change in some to populate some hidden template variables for "alerts".
If template variables are not reloaded then issues cannot be reproduced

Repro Dashboard has one repeating dashboard, which shows http_server_requests_seconds_count metrics with method, status and uri. In our Prometheus we have +10000 different timeseries resulting ~150 repeating dashboards each having having few graph for different method, status uri combination.

You can use any queries instead of http_server_requests_seconds_count as long as the number of time series is large enough resulting template variable reload and/or dashboards refresh to take few seconds and enough repeating panels.

Using longer time range like last 30 days and switch to N days through mouse range selection is easiest way to reproduce the issue.

[Repro_Grafana_errors-1565700922864.zip](https://github.com/grafana/grafana/files/3496991/Repro_Grafana_errors-1565700922864.zip)

**Comment by jtorkkel** [comment]
Any update on this, easy to reproduce and very annoying restarting Grafana every few minutes.

**Comment by dprokop** [comment]
@jtorkkel I have just managed to reproduce this issue, thanks for the detailed repro scenario. I'll let you know when it's fixed.
