### ISSUE TITLE
UI: ButtonSelect dropdown doesn't close on blur in Firefox

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#18531]
**What happened**:
Blurring an open `ButtonSelect` component in Firefox does not close the dropdown on blur.

**What you expected to happen**:
I would expect the dropdown to close as it does in Chrome.

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to Explore
2. Click the dropdown next to the refresh button in the Explore toolbar.
3. Click anywhere else.

**Environment**:
- Grafana version: Grafana v6.4.0-pre (commit: 8a9e23bc2a)
- Data source type & version: N/A
- OS Grafana is installed on: macOS
- User OS & Browser: macOS, Firefox 68.0.1

**Comment by torkelo** [comment]
Strange, unable to replicate this on linux in firefox
