### ISSUE TITLE
Template multi datasource does not apply to Query in Queries tab

### ISSUE THREAD

**Issue by CMahesh** [grafana/grafana#18542]
1. Create a template Datasource variable (name: ds) with multi-value selection in the dashboard.
2. Select multi values in the dropdown (ds1,ds2)
2. Add a panel
3. Goto the Edit panel
4. Select the Queries tab 
5. The option of the $ds is not present.

If the template Datasource is of single value  it is present

Why it is needed:
I want to run the same query in the multi datasource and the result shown in the same panel. Instead of different panel per datasource selected using the repeating rows/panel.

**Comment by hugohaggmark** [comment]
Hi @CMahesh, I'm sorry to say that this feature request will not be taken into consideration so I'll close it for now. We can always reopen this later if needed.

**Comment by hugohaggmark** [comment]
More information in #16542 and #16543
