### ISSUE TITLE
Group by - "Filter" throws "cannot read property 'key' of undefined" error for Elasticsearch 5.6 datasource

### ISSUE THREAD

**Issue by DMB-danis** [grafana/grafana#18548]
**What happened**:

I was configuring a singlestat panel with a "unique count" query using a Elasticsearch 5.6 datasource. I wanted to add a filter to the query using a "filter" aggregation. I used the "Group by" section of the query definition for this.

However, right after completing the "Group by" section of the query, a warning message is displayed on the panel saying: 

> Cannot read property 'key' of undefined

.

**What you expected to happen**:

I expected to receive the response from Elasticsearch. The "group by" section would have generated a single bucket of documents I would compute the unique count aggretation. The result would be a single number, which is appropriate for a singlestat panel.

**How to reproduce it (as minimally and precisely as possible)**:

Here is the query definition in Grafana:

![image](https://user-images.githubusercontent.com/35145428/63019199-f53a7200-be9a-11e9-832e-f5ecd7fba63b.png)

**Anything else we need to know?**:

Using the query inspector, I copied the query and replicate the same on Elasticsearch. It worked, so it seems to be some sort or parsing done by Grafana.

Here is the query:

![image](https://user-images.githubusercontent.com/35145428/63019355-595d3600-be9b-11e9-8ba2-cf82c553fad7.png)

And the response:

![image](https://user-images.githubusercontent.com/35145428/63019369-6712bb80-be9b-11e9-95a9-a0bdccdfb51a.png)

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Elasticsearch 5.6
- OS Grafana is installed on: docker
- User OS & Browser: Windows10, Chrome
- Grafana plugins: none
- Others: none

**Comment by hugohaggmark** [comment]
Thanks for reporting this @DMB-danis, we're looking in to it.

**Comment by marefr** [comment]
@DMB-danis you'll need to group by date histogram after the group by filter
