### ISSUE TITLE
SingleStat current stats, confusing name when utilizing predicted data

### ISSUE THREAD

**Issue by ritualz** [grafana/grafana#18546]
As described by the docs the current stats value is: 

> The last value in the series. If the series ends on null the previous value will be used.
[https://grafana.com/docs/features/panels/singlestat/](https://grafana.com/docs/features/panels/singlestat/)

**What would you like to be added**:
When dealing with predicted data, this will become confusing and not intuitive for the end users. A better choice of wording would be last-null-value.  A added bonus would be the ability to have a proper current, where the current time is utilized to pick the correct value, instead of using the last value in the series.

**Comment by hugohaggmark** [comment]
Hi @ritualz and thanks for reporting this! Could you be more specific in what change your looking for here. Is this a change to the Docs only or is this a feature request? A bit more information would be awesome.

All the best

**Comment by torkelo** [comment]
We know this naming is not ideal, and for new panels we have changed it and introduced some new ones as well to make this clear. 

In the new panels we have Last & Last (non-null) as separate choices 

![image](https://user-images.githubusercontent.com/10999/63018276-b99ea880-be98-11e9-9292-a275cf54f579.png)
