### ISSUE TITLE
CSV Export data not readable in excel

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#1855]
The currently used format for the exported csv is not in the excel dialect (it uses ; instead of ,). Furthermore the iso time format used in the export is not recognised by excel. Both issues make it hard to post treat the data with the most common tool to process csv files. 
Lastly the file name when downloading is always grafane_export.csv,which makes it hard to distiniush.  Is it possible to use the dashborad title?

**Comment by torkelo** [comment]
Its readable, using the cvs import I can view it fine, and the time format is also works if you specify things correctly in excel. I do not have excel right now to show you (in linux for the moment). But no one else has complained about this.

**Comment by writ3it** [comment]
Excel requires BOM in first bytes of CSV, that's the problem.

**Comment by anthraxn8b** [comment]
Sorry, folks, but we are using grafana in a business landscape.
I am not a fan of Windows and Excel but my users were using the function to export CSV in "Excel dialect" very often.

Just telling us that you removed the feature and give us the workaround to import the CSV data "correctly" into Excel on thei own is not a solution.

Is there a chance to get the feature back?

**Comment by manosv** [comment]
The export to csv is a huge deal breaker for me also, how can we get it back please?

**Comment by dan-leo** [comment]
What happened to export via CSV?
