### ISSUE TITLE
 Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by ddfelts** [grafana/grafana#18558]
I get this when adding a influx data source.  It is the same data source already added to the project in another org on this same server and it works as expected.  It pops up a login screen as well asking for creds, i put in creds then it keeps asking. Grafana v6.3.2 (4832460)

**Comment by hugohaggmark** [comment]
Thanks for reporting this @ddfelts but we need more information like
**Environment:**

Grafana version: 
Data source type & version: 
OS Grafana is installed on:
User OS & Browser: 
Grafana plugins:
Others:

Any logs you can provide both grafana logs and any console logs from your browser.
All the best

**Comment by ddfelts** [comment]
Grafana Version: Grafana v6.3.2 (4832460)
Influxdb: Influxdb-Version: 1.7.7
Ubuntu 18.04 LTS
Plugins:
![image](https://user-images.githubusercontent.com/546153/63113847-106bb700-bf59-11e9-8ac8-113839a1be2c.png)

The only logs from yesterday are below:

t=2019-08-13T13:43:32+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=47.221.235.127 time_ms=0 size=29 referer=

t=2019-08-13T13:43:42+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost

t=2019-08-13T14:29:20+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=82.221.105.6 time_ms=0 size=29 referer=

t=2019-08-13T14:29:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=404 remote_addr=82.221.105.6 time_ms=1 size=32285 referer=

t=2019-08-13T17:18:17+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/4/query status=400 remote_addr=47.221.235.127 time_ms=48 size=68 referer="http://35.239.139.191:3000/d/2sL5eUDWk/labepo?panelId=8&edit&fullscreen&orgId=1&from=now-5m&to=now&var-eposervers=EPO-Server"

**Comment by hugohaggmark** [comment]
Thank you, could you add the logs from your browser console as well?

**Comment by papagian** [comment]
Closing due to lack of response.
