### ISSUE TITLE
Show external auth entries & remove them from user admin view

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#18551]
**What happened**:
Disabled LDAP/GitLab auth bit it still says that users are LDAP/GitLab
**What you expected to happen**:
Icons should be removed and be "normal" users
**How to reproduce it (as minimally and precisely as possible)**:
?
**Anything else we need to know?**:
This two users that is saying they are LDAP/GitLab was normal users first, then I added one as LDAP and a second user as GitLab, I change those user around 2019 Feb-March, don't remember version of Grafana but we update within a week when a new version is available
**Environment**:
- Grafana version: 6.3.2
- Data source type & version: InfluxDB 1.7.6
- OS Grafana is installed on: Debian
- User OS & Browser: Windows/Chrome
- Grafana plugins:
- Others:
Using built-in database(mysqlite)

I like the small icon next to the user that are not user from Grafana.

**Comment by hugohaggmark** [comment]
Thanks for reporting this @flopp999, we'll take a look at this.

**Comment by torkelo** [comment]
> Disabled LDAP/GitLab auth bit it still says that users are LDAP/GitLab 

They were created from this integration and hence get that label. So in order to remove that label you will have to remove and & readd the user. Not ideal. We may be able to remove these external auth entries in the future from the user admin view.

**Comment by Livingthrume** [comment]
I can not believe how smart you guys are! I am blown away.
