### ISSUE TITLE
Prometheus queries drop $1 from query

### ISSUE THREAD

**Issue by jylitalo** [grafana/grafana#18553]
**What happened**:

In grafana 6.2.5, I don't have any problems with queries like:
`label_replace(ecs_age_average, "account", "$1", "container_name", "prom-cloudwatch-exp-(.*)-foobar")` in graph panels.

In grafana 6.3.2, I can put the same query in and it works, but if I press 'Duplicate query' button, it puts `label_replace(ecs_age_average, "account", "", "container_name", "prom-cloudwatch-exp-(.*)-foobar")` as a new query (note that it has `""` instead of `"$1"`).

Same thing (`"$1"` been replaced by `""`) happens, if I go from `Queries` to `Visualization` and back.

**What you expected to happen**:

In case of 'duplicate query', I expected query to be real duplicate (so that `"$1"` would remain as `"$1"` instead of being replaced with `""`).

**How to reproduce it (as minimally and precisely as possible)**:

1) Press `New Dashboard`
2) Press `Add Query`
3) Change DataSource to Prometheus
4) Insert `label_replace(ecs_age_average, "account", "$1", "container_name", "prom-cloudwatch-exp-(.*)-foobar")` into `Enter PromQL query`
5) Press `Duplicate query`

Query gets duplicated, but new query doesn't have `$1` in it.

**Environment**:
- Grafana version: v6.3.2 (commit: 4832460)
- Data source type & version: Prometheus (that is builtin)
- OS Grafana is installed on: grafana/grafana container from dockerhub.com
- User OS & Browser: MacOS 10.14.6 & Chrome Version 76.0.3809.100

**Comment by torkelo** [comment]
this is fixed in nightly builds and upcoming 6.3.3 patch release (hopefully released today) 
https://github.com/grafana/grafana/issues/18455
