### ISSUE TITLE
[FeatureRequest] - InfluxDB: Support the built-in variables __from & __to in backend / alerting queries

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18562]
Data sources that use a string-based query language can use these variables in the query but they do not work with backend / alerting queries. 

https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query.go#L34 

Should update the interpolation code to use the same regex replace as frontend so ${__from} also is supported.

**Comment by gabor** [comment]
notes for implementation:
- it's not just `$__from`. it is also things like `${__from:date}`
- i could not find any datasource yet that does this in the go-code

**Comment by gabor** [comment]
after some more thinking.. because `$__from` can have forms like `${__from:date}` , this would require to have the whole template-formatting functionality available in *golang* for alerting-use-cases. @grafana/backend-platform any ideas/opinions about this?

**Comment by gabor** [comment]
also pinging @grafana/alerting-squad about the comment above ^

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
