### ISSUE TITLE
Azure Monitor - support workspace for dashboard variables

### ISSUE THREAD

**Issue by FYYKX** [grafana/grafana#18561]
**What would you like to be added**:
support Workspaces(aSubscription) for dashboard variable

**Why is this needed**:
we can select workspace dynamically based on the selected subscription

**Comment by hugohaggmark** [comment]
Thanks for contributing @FYYKX, I would like to know more details about this feature request and I hope you can explain a bit more what you're aiming for.

All the best

**Comment by FYYKX** [comment]
![](https://grafana.com/docs/img/docs/v60/azuremonitor-service-variables.png)
I need a Workspaces(aSubscription) definition for list all workspaces under the subscription id
then I can use this workspace in the azure log analytics

**Comment by maxilampert** [comment]
Any news on adding these variable? We have a use case were we target different workspaces with different datasources but because using a template variable to switch between datasources is not changing the actual workspace this would allow us at the cost of an extra variable to change the workspace?
