### ISSUE TITLE
Prometheus legend don't refresh automatically

### ISSUE THREAD

**Issue by StupidScience** [grafana/grafana#18567]
**What happened**:
When I change legend for Prometheus graph it don't refresh automatically as before. It show new legend only when I click "Refresh dashboard"

**What you expected to happen**:
Legend in graph should refresh after change

**How to reproduce it (as minimally and precisely as possible)**:
* Change legend on Graph with Prometheus datasource;
* Profit;

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: Prometheus 2.9.1
- OS Grafana is installed on: official dockerfile
- User OS & Browser: MacOS Mojave 10.14.6, Google Chrome Version 76.0.3809.100, Safari Version 12.1.2
- Grafana plugins:
  * Worldmap panel;
  * Statusmap;
  * Pie Chart;
- Others:

**Comment by torkelo** [comment]
thanks for reporting this! 

It's a super easy fix here: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/components/PromQueryEditor.tsx#L85 

Missing the , this.onRunQuery); that the other handlers have

**Comment by StupidScience** [comment]
Hi, @torkelo.
I was trying to make this fix but looks like it is already fixed in master branch by this PR #18147 
Anyway thanks for quick response.

**Comment by torkelo** [comment]
No that PR does not fix it for the legend input

**Comment by StupidScience** [comment]
In this [commit](https://github.com/grafana/grafana/commit/4cf804c8b6d60c237a9b1634a6517160aaf98803#diff-c9aeb32c73b021b20c5cf83495e8f4a7R126) fixed behaviour that i reported.
Also look at these comments [1](https://github.com/grafana/grafana/pull/18147#pullrequestreview-273157158) and [2](https://github.com/grafana/grafana/pull/18147#issuecomment-520501295).

**Comment by torkelo** [comment]
ah, your right
