### ISSUE TITLE
Docs feedback: features/panels/singlestat.md

### ISSUE THREAD

**Issue by ChristianSteiner** [grafana/grafana#18568]
In the description of Spark Lines the Y-Axis settings are mentioned:
    3. Y-Min: The minimum Y value. (default auto)
    4. Y-Max: The maximum Y value. (default auto)
But in the panel itself this function is not available (which is also shown in the screenshot next to the description)

Can this section be changed to reflect the actual state of this plugin?

**Comment by torkelo** [comment]
It is available in v6.3+

**Comment by ChristianSteiner** [comment]
Sorry, my bad, missed the Version.
Can the screenshot be updatet to the 6.3 version?
