### ISSUE TITLE
[Feat] View Loki log entries as Annotations

### ISSUE THREAD

**Issue by lorenwest** [grafana/grafana#18579]
**What would you like to be added**:
I'd like to view tagged Loki log entries as dashboard annotations

**Why is this needed**:
Loki stores valuable event information, and I'd like to associate it with my panels as annotations

**Comment by lorenwest** [comment]
This may be a dup of #17762 - not enough information in that thread to know if it's a dup or if this is a different request.

**Comment by lorenwest** [comment]
Related to #18578

**Comment by hugohaggmark** [comment]
Duplicate of #17762
