### ISSUE TITLE
[Feat] Graphite events explorer

### ISSUE THREAD

**Issue by lorenwest** [grafana/grafana#18578]
**What would you like to be added**:
The ability to view Graphite events in the Explorer tab

**Why is this needed**:
We use Graphite events to store system generated annotations that users can't edit when viewed as an annotation. It would be great to view these in the Explorer tab, to see our tagged events in a list view. Currently we use the Graphite events viewer, but it's not as user friendly as the Grafana Explorer tab.

**Comment by lorenwest** [comment]
Alternately, we could store the events into Loki, but we'd need to see them as annotations on a dashboard - I'll add that as a different feature request. (alternately, we could add system events using the Annotations API if we had a way to prevent users from modifying/deleting them)

**Comment by lorenwest** [comment]
Related to #18579

**Comment by hugohaggmark** [comment]
Thanks for contributing @lorenwest but I don't know if we'll add annotations to Explore any time soon. Leaving this open to see if it gets any upvotes.

**Comment by lorenwest** [comment]
Not necessary if I can use Loki to store system generated annotations #17762

**Comment by hugohaggmark** [comment]
Thanks for clarifying, closing this issue then but we can reopen it if needed.

**Comment by davkal** [comment]
@lorenwest Hi! I'm working on Explore and would like to understand your use case a bit better. If you're interested we could set up a video call and you can show me what you're trying to do.
I'm available at david@grafana.com
