### ISSUE TITLE
CSS does not use root_url and can't ping behind re-written proxy

### ISSUE THREAD

**Issue by axelabs** [grafana/grafana#1857]
I'm using grafana 2.0.1 from the deb package.  It is proxied [behind nginx with a /grafana prefix as noted here](http://serverfault.com/a/684710).  It works but there is a bug when invalid users try to login.  It seems that your JS has url:"/api/login/ping" hardcoded and does not use the updated root_url.  See JS console for details:

![grafana-no-ping](https://cloud.githubusercontent.com/assets/1413585/7285286/10e982fa-e909-11e4-83f8-4afa43e8450b.png)

Changing the url in app.6b375424.js to "/grafana/api/login/ping" resolves the issue.  It would be nice to have it recognize the prefix automatically instead.

**Comment by torkelo** [comment]
thanks for reporting this, fixed! 

You can get daily builds for the patch release here: http://grafana.org/download/builds  
look for build 2.0.3-pre1

**Comment by davidak** [comment]
we use grafana behind an apache reverse proxy and get a similar error from time to time:

![bildschirmfoto 2015-05-21 um 12 19 55](https://cloud.githubusercontent.com/assets/91113/7746600/02630ab4-ffb4-11e4-954e-7a63723385d3.png)

Response:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /api/login/ping was not found on this server.</p> <hr> <address>Apache/2.4.7 (Ubuntu) Server at ********** Port 443</address> </body></html>
```

when will 2.0.3 get released?

**Comment by torkelo** [comment]
@davidak not sure when it will be released. You can download a build of the 2.0.x branch here http://grafana.org/download/builds.html  (label 2.0.3-pre1)
