### ISSUE TITLE
Provisioning: Link to source dashboard

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18570]
If you want to fix or improve a provisioned dashboard you get this modal: 

![image](https://user-images.githubusercontent.com/10999/63085033-d1cfff80-bf4c-11e9-811c-e142b38756db.png)

Problem is this dashboard json file is probably in a git repo somewhere or might be generated from a ksonnet file (that has a different name). 

Would be very useful if we can add a source meta block to dashboard json that can include how the dashboard was generated & where the source file is. 

```json
{
  "title": "My generated dashboard",

  "source": {
     "url:" "https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/scheduler.libsonnet",
     "type": "ksonnet" 
  }
}
```

Need to investigate how easy it would be to output something like this in the result json file using ksonnet. 

Then the feature would be to show this link under or above the file path in the above image

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
