### ISSUE TITLE
Why import JSON file does not have same format on my localhost

### ISSUE THREAD

**Issue by wzf1943** [grafana/grafana#18583]
**What happened**:
Hi I have a question about Grafana JSON file. I create our system's dashboard in on my local machine and then I want to deploy it to our production linux server by importing the JSON file.

I got the dashboard on production. But the format is totally different and each graph does not show right value. 

**What you expected to happen**:
When I use JSON create by my localhost it can migrate to other environment

**How to reproduce it (as minimally and precisely as possible)**:
Always

**Anything else we need to know?**:

**Environment**:
- Grafana version: Latest
- Data source type & version: Prometheus 
- OS Grafana is installed on: Mac OS and Ubuntu
- User OS & Browser: Safari and Firefox
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @wzf1943 and thanks for reporting this. Can it be that you're have different data sources in the different environments? It would help if you could specify how the format is different by attaching an example of exported JSON vs imported JSON.

All the best

**Comment by wzf1943** [comment]
Both dashboard are using same data source. I just create dashboard on my local machine and then deployed that JSON file to our production environment. I got the dashboard. But the shape, color of new dashboard are different than my local machine. I also try this in my local VM linux. It also has same issue. So I don't know what is problem.

**Comment by hugohaggmark** [comment]
Thanks for the quick response, can you please attach an exported example JSON and how it looks when you import?

**Comment by wzf1943** [comment]
Sure

```json
"targets": [
        {
          "expr": "rate(ddn_prod_jetstreamd_storage_muxer_groupcacheCacheHits[5m])/rate(ddn_prod_jetstreamd_storage_muxer_groupcacheGets[5m])",
          "refId": "A"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Groupcache Hit rate",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "percentunit",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "aliasColors": {},
      "bars": false,
      "cacheTimeout": null,
      "dashLength": 10,
      "dashes": false,
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 10
      },
      "id": 42,
      "legend": {
        "avg": false,
        "current": false,
        "max": true,
        "min": true,
        "show": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "percentage": false,
      "pluginVersion": "6.3.2",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
```

<img width="795" alt="Screen Shot 2019-08-15 at 10 50 03 PM" src="https://user-images.githubusercontent.com/2915794/63146556-2789c380-bfb0-11e9-800e-04701ae3f43f.png">

<img width="607" alt="Screen Shot 2019-08-15 at 10 58 28 PM" src="https://user-images.githubusercontent.com/2915794/63146583-3ec8b100-bfb0-11e9-988e-985f4bd2dd79.png">


Previous one is what I want to

**Comment by hugohaggmark** [comment]
Seems like the second one is using the TestData datasource. Maybe the default datasource differs between your environments. But we could really use the complete JSON after export and after import if that's possible?
