### ISSUE TITLE
SingleStat: migrate gauge to the gauge panel

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18581]
In 6.4, I propose we take a step towards removing the Gauge panel from SingleStat.

I think we should:
1. keep any existing panel config working as is
2. remove the option to configure gauge options from editor.html
3. If an panel is already configured with a gauge, we can add a big CTA button that would migrate the panel to Gauge

The one thing that would be lost in this migration is the sparkline overlay.

**Comment by torkelo** [comment]
There is an issue for this already: https://github.com/grafana/grafana/issues/14554

Updated the main description with your comment above and also added more info on what would currently be breaking.
