### ISSUE TITLE
Calculating average and its relation to min/max

### ISSUE THREAD

**Issue by kenzodeluxe** [grafana/grafana#1858]
I want a graph to only show values > 1 which I can do easily by setting the "min" to 1. However, at the same time the calculation of the averages doesn't change (two dots, one at 0, one at 10, average is always 5 even when 0 is not shown anymore).
This might be working as designed, if so I'd ask for a "flag" that you can enable (like "Use actual values shown in graph" for averages).

**Comment by torkelo** [comment]
Setting Grid min does not change any of the values in the series (used to calculate avg), For this you need to use graphite function to filter out values below a certain value, or if you do not use InfluxDB I think you can filter out values there as well

**Comment by kenzodeluxe** [comment]
And that's the thing: I want to be able to see where they would be (cause the existence of those make sense to me), however I would want to get rid of them for the calculation. Makes sense however that this might be a rare use case.

**Comment by torkelo** [comment]
yea, and its better handled in the metrics query
