### ISSUE TITLE
improve "Time duration (s)" unit

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#18589]
**What would you like to be added**:

the graph axis unit "Time duration (s)" does not appear to scale to certain units (e.g. doesn't cover microseconds), and uses verbose labels like "milliseconds" instead of "ms".

![Screen Shot 2019-08-16 at 11 31 46 AM](https://user-images.githubusercontent.com/1708631/63139710-373df200-c01a-11e9-84c8-0793b77962ef.png)

**Why is this needed**:

improve readability of graphs, better use of screen real estate

**Comment by hugohaggmark** [comment]
Hi @belm0 can you please supply the following:

**Environment:**

Grafana version:
Data source type & version: 
OS Grafana is installed on: 
User OS & Browser: 
Grafana plugins:
Others:

**Comment by belm0** [comment]
Grafana version: v6.0.0
Data source type & version:  Prometheus histogram metric / version unknown
OS Grafana is installed on:  unknown
User OS & Browser: n/a
Grafana plugins: none

**Comment by hugohaggmark** [comment]
Not sure why you're having that issue on 6.0.0. Using a docker image with the same version and Chrome I get the following:

**Created a dashboard using TestData and click with the following series**
![image](https://user-images.githubusercontent.com/562238/63152050-35206700-c00b-11e9-9f63-acddfaa236a5.png)

**Settings for axis**
![image](https://user-images.githubusercontent.com/562238/63152108-51bc9f00-c00b-11e9-8475-527978f1de0f.png)

**All series**
![image](https://user-images.githubusercontent.com/562238/63152146-6731c900-c00b-11e9-9c61-884cc918c47b.png)

**A-series**
![image](https://user-images.githubusercontent.com/562238/63152173-77e23f00-c00b-11e9-9f28-40368e2113e6.png)

**B-series**
![image](https://user-images.githubusercontent.com/562238/63152185-83ce0100-c00b-11e9-9185-84d04f1d913d.png)

**C-series**
![image](https://user-images.githubusercontent.com/562238/63152199-8defff80-c00b-11e9-984e-1d09ac22407a.png)

**D-series**
![image](https://user-images.githubusercontent.com/562238/63152215-95afa400-c00b-11e9-9c07-a332798230d2.png)

In my environment it never shows up with `milliseconds` as in your screenshot. Anything else I might be missing as I can't seem to reproduce your issue? Are you sure about the version?

**Comment by torkelo** [comment]
the unit your using is not designed for the graph, but the singlestat panels. Use the normal time units (ms, seconds, etc)

**Comment by belm0** [comment]
Thank you.  I was definitely thrown off by autocompleting on "duration".

Is there some hint in the UI that a unit is compatible with a certain visualization?  And is it expected that the difference between "Time duration (s)" and "Time seconds (s)" be obvious to the user?

**Comment by torkelo** [comment]
There is no difference between "Time duration (s)" and "Time seconds (s)" 

There is a difference between ""Time duration (s)" and "seconds (s)"

All the ones with the Time duration prefix print a friendly duration name instead of small unit.
