### ISSUE TITLE
HTTP response code 500 on adding graphite data source

### ISSUE THREAD

**Issue by 5x3** [grafana/grafana#18598]
on https://127.0.0.1/datasources/edit/1/
add graphite data source and get:
HTTP Error Internal Server Error
on save & test button.
this is for grafana=6.3.3 (current stable)
when I downgrade to grafana=4.5.2 - all works OK.

I use empy VE with debian  8.4.
what is installed:

```
ii  grafana                               6.3.3                                amd64        Grafana
ii  graphite-carbon                       0.9.12-3                             all          backend data caching and persistence daemon for Graphite
ii  graphite-web                          0.9.12+debian-6                      all          Enterprise Scalable Realtime Graphing
ii  libapache2-mod-dnssd                  0.6-3.1                              amd64        Zeroconf support for Apache 2 via avahi
ii  libapache2-mod-wsgi                   4.3.0-1                              amd64        Python WSGI adapter module for Apache
ii  libgraphite2-3:amd64                  1.3.10-1~deb8u1                      amd64        Font rendering engine for Complex Scripts -- library

```

the problem request is:
> POST /render HTTP/1.1
> Host: 127.0.0.1:81
> User-Agent: Grafana/6.3.3
> Content-Length: 73
> Accept: application/json, text/plain, */*
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.5
> Authorization: Basic cm9....wOQ==
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> X-Forwarded-For: 127.0.0.1, 127.0.0.1
> X-Grafana-Nocache: true
> X-Grafana-Org-Id: 1
> X-Panel-Id: 3
> X-Xsrf-Token: oTfNTXJ2GY6Q....kh7LU1T5vO34
> 
> target=constantLine(100)&from=-1h&until=now&format=json&maxDataPoints=300

I convert it to curl and change POST to GET and got image with 'no data' message.

**Comment by hugohaggmark** [comment]
Thanks for reporting this @5x3, we're going to take a look at it.

**Comment by torkelo** [comment]
You will have to update to a new version of Graphite version. Strange, Graphite has supported POST in the render API for 5-6 years or so. Not sure why your Graphite server is not liking that request. 

Grafana has used POST to the /render method since v1.9, 4.5.2 also uses POST
