### ISSUE TITLE
Explore: Error when switching from Prometheus to Loki data sources

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#18596]
**What happened**:
Chose Prometheus data source in explore, then chose Loki data source, which caused an error.

**What you expected to happen**:
To switch to the loki data source without an error occurring.

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to Explore
2. Choose Prometheus as a data source
3. Choose Loki as a data source.
4. Notice the error

**Environment**:
- Grafana version: Grafana v6.4.0-pre (commit: 5a41e8b119)
- Data source type & version: Prometheus, master
- OS Grafana is installed on: macOS
- User OS & Browser: macOS, Firefox 68.0.2

**Comment by vonhng** [comment]
The same to you.
Grafana version: Grafana v6.3.3
Data source type & version: Prometheus, v2.5.0
OS Grafana is installed on: redhat 7.4
User OS & Browser: macOS, Chrome 76.0.3809.100
Please tell me  a usable version.

**Comment by kaydelaney** [comment]
@vonhng Going back to version v6.3.2 should solve this issue
