### ISSUE TITLE
Panel: Going to Explore from mixed panel does not work

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#18597]
**What happened**:
If you go to explore via a panel with mixed data sources, rather than the first data source being selected and the relevant queries being there, you get a page with empty query rows and no data source selected.

![Screen Shot 2019-08-16 at 11 09 56](https://user-images.githubusercontent.com/45561153/63160854-b16c7780-c016-11e9-8164-a08d28d6bfce.png)

**What you expected to happen**:
To be sent to explore with the panel's first data source selected and the relevant queries populated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel with a mixed data source.
2. Add a query. (Data source doesn't matter)
3. Go to explore via the panel

**Environment**:
- Grafana version: Grafana v6.4.0-pre (commit: 5a41e8b119)
- Data source type & version: Prometheus, master
- OS Grafana is installed on: macOS
- User OS & Browser: macOS, Firefox 68.0.2

**Comment by ryantxu** [comment]
Is explore expected to work with mixed queries?  From within explore you can not create mixed queries

**Comment by kaydelaney** [comment]
@ryantxu The behavior for mixed data sources seems to be to take the first query whose data source is supported in Explore https://github.com/grafana/grafana/blob/master/public/app/core/utils/explore.ts#L81
