### ISSUE TITLE
canSave, canEdit, canShare, canStar meta attributes can't be passed when initializing dashboard

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#1859]
the DashboardModel._initMeta() function initializes the canSave, canEdit, canShare, canStar meta attributes to true.

Shouldn't these only be initialized if they are not already set?

ie.
```
_.defaults(meta, {canShare: true, canSave: true, canEdit: true, canStar: true});
```

**Comment by woodsaj** [comment]
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashboardSrv.js#L53

**Comment by torkelo** [comment]
Fixed. (:
