### ISSUE TITLE
Prometheus: Cannot use Tab, Shift-Tab to indent in multi-line queries

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#18608]
**What happened**:

In a regression that happened by merging the Prometheus editor from Explore, the indenting of lines with Tab and Shift-Tab was lost

**What you expected to happen**:

Press Shift-Tab to dedent the highlighted lines:

![image](https://user-images.githubusercontent.com/345210/63223070-64bca400-c1b0-11e9-8527-e0eae753b70a.png)

**How to reproduce it (as minimally and precisely as possible)**:

```
sum by (label_project) (
  rate(
    container_network_receive_bytes_total[$interval]
  )
  * on(pod) group_left(label_project)
            kube_pod_labels{
              namespace = "$namespace",
              label_environment = "$environment"
            }      
)
```
select indented text, press Shift-Tab

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus 2.11.x
- User OS & Browser: Chromium 77 on Linux

**Comment by davkal** [comment]
This is fixed in 6.4.
