### ISSUE TITLE
Edit your user causes 502 Bad Gateway starting with 6.3.0

### ISSUE THREAD

**Issue by bfaivre** [grafana/grafana#18606]
**What happened**: When I select edit for the user I'm logged in as I get a 502 Bad Gateway.

**What you expected to happen**: Not receive a 502 Bad Gateway.

**How to reproduce it (as minimally and precisely as possible)**: Edit the user you are logged in as.

**Anything else we need to know?**: Editing users other than myself does not cause this issue. However, if I create a new user, login as that user and try to edit my user, I get the same error. I don't have this issue on my Windows 10 installation. In Linux, my syslog has the following:

```
Aug 18 04:46:15 grafana-server[5454]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x16248]
Aug 18 04:46:15 grafana-server[5454]: goroutine 142 [running]:
Aug 18 04:46:15 grafana-server[5454]: github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).ParseOs(0x453dbc0, 0x48b5b80, 0x73, 0x7315c)
Aug 18 04:46:15 grafana-server[5454]: #011/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:284 +0xb8
Aug 18 04:46:15 grafana-server[5454]: github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse.func2(0x48f2030, 0x453dbc0, 0x48b5b80, 0x73, 0x4bd8490)
Aug 18 04:46:15 grafana-server[5454]: #011/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:233 +0x68
Aug 18 04:46:15 grafana-server[5454]: created by github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse
Aug 18 04:46:15 grafana-server[5454]: #011/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:230 +0x13c
Aug 18 04:46:15 systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 04:46:15 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
```

**Environment**:
- Grafana version: 6.3.0_armfh and 6.3.3_armfh
- Data source type & version: MySQL (MariaDB 10.3.15)
- OS Grafana is installed on: Raspbian Buster Lite 2019-07-10
- User OS & Browser: Windows 10, Edge & Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by bfaivre** [comment]
Screenshot of the error:

![2019-08-17_21-41-01](https://user-images.githubusercontent.com/27573356/63220354-26849d80-c13a-11e9-9681-ef19c9c20a8d.png)

**Comment by torkelo** [comment]
same underlying issue as https://github.com/grafana/grafana/issues/18524
