### ISSUE TITLE
Panel override relative time for repeated panels

### ISSUE THREAD

**Issue by SwathiMuppalla** [grafana/grafana#18602]
Is it possible to override time for repeated panels?
Now its like if i edit relative time for source panel all the repeated panels show the same time override. Is it possible to change the relative time for every repeated panel so that whenever the panels are repeated their respective time overrides are shown in display.
![Screenshot (16)](https://user-images.githubusercontent.com/22199547/63179785-e4b10580-c01a-11e9-8a6f-21678240ea89.png)
Something like this. Currently I am manually changing for every repeated panel. The scenario is i have to compare the build wise data of every server(i.e Server-1 build started 1 month ago, Server-2 build started 2 months ago) @torkelo  
Thanks,

**Comment by torkelo** [comment]
No not really possible as all properties from the source panel are used

**Comment by torkelo** [comment]
you can create a custom variable with 1M, 2M, 4M etc and have panels repeat based on that.

**Comment by SwathiMuppalla** [comment]
@torkelo Thank you
