### ISSUE TITLE
Prometheus: Awkward matching paren insertion

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#18609]
**What happened**:

The Prometheus editor regressed badly after it was replaced with the Explore editor.

In this case there are stray closing parens being inserted (sometimes) far way from where the opening paren is typed in. 

**What you expected to happen**:

Insert closing parens only if it is helpful, not when it let's the user hunt for stray closing parens.

![Peek 2019-08-18 13-36](https://user-images.githubusercontent.com/345210/63223959-ab64cb00-c1bd-11e9-9510-de3f20b78c80.gif)

**How to reproduce it (as minimally and precisely as possible)**:

In a PromQL query insert opening parens or brackets in all those places where they are allowed. Observe insertion positions of closing parens or brackets.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus 2.11.x
- User OS & Browser: Chromium 77 on Linux

**Comment by towolf** [comment]
Here's another real example. Note the two parens at the end.

![image](https://user-images.githubusercontent.com/345210/63229581-32d42d80-c202-11e9-8ed0-06a39c82b090.png)

**Comment by davkal** [comment]
Fixed in 6.4
