### ISSUE TITLE
Failed to get LDAP config - Windows Server

### ISSUE THREAD

**Issue by ThePieMonster** [grafana/grafana#18613]
**What happened**:
LDAP can not seem to find the ldap.toml file.

`t=2019-08-18T18:42:59-0700 lvl=info msg="LDAP enabled, reading config file" logger=ldap file=/etc/grafana/ldap.toml`
`t=2019-08-18T18:42:59-0700 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="Failed to get LDAP config: Failed to load LDAP config file: open /etc/grafana/ldap.toml: The system cannot find the path specified."`
`t=2019-08-18T18:42:59-0700 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr="x.x.x.x:xxxxx" time_ms=1 size=53 referer=https://website.com/login`
**What you expected to happen**:
LDAP would read the configuration file.
**How to reproduce it (as minimally and precisely as possible)**:
Fresh install of Grafana
Edit "C:\Program Files\GrafanaLabs\grafana\conf\defaults.ini" to enable LDAP
Edit "C:\Program Files\GrafanaLabs\grafana\conf\ldap.toml" to enter config info

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: NA
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: None

**Comment by torkelo** [comment]
Specify the correct path to the ldap config file. Your path is still the default `/etc/grafana/ldap.toml`

**Comment by ThePieMonster** [comment]
Ok thanks for the response. I am getting a error about invalid username and password with ldap. I double checked the password and its correct. Is there anything obvious that may be missing? The user was just created in the "Users" folder in AD, nothing else was done to the user account. Is there any special permissions that may be missing?

`t=2019-08-19T16:04:43-0700 lvl=eror msg="Cannot authentificate admin user in LDAP" logger=ldap error="Invalid Username or Password"`
`t=2019-08-19T16:04:43-0700 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"`


```
# Search user bind dn
bind_dn = "grafana@domain.local"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = 'password'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(sAMAccountName=%s)"

# An array of base dns to search through
search_base_dns = ["dc=corp,dc=domain,dc=local"]


```
