### ISSUE TITLE
Grafana graph show wrong data when stacking has been checked

### ISSUE THREAD

**Issue by ikingnet** [grafana/grafana#18614]
**What happened**:
graph show wrong data
query sql:
```sql
SELECT
  $__time(snapshot_time),
  IFNULL(azkaban_jobname,'OTHER') as jobname,SUM(allocatedMB) as allocatedMB
FROM apps_snapshot
WHERE
  $__timeFilter(snapshot_time) and  azkaban_jobname IN ('a_job','b_job')
GROUP BY snapshot_time,jobname
ORDER BY snapshot_time,jobname
```
graph (before stacking):
![grafana_bug1](https://user-images.githubusercontent.com/3273119/63238754-7d918c00-c27a-11e9-9151-524dd27ebe88.png)

graph (after stacking):
![grafana_bug2](https://user-images.githubusercontent.com/3273119/63238763-85e9c700-c27a-11e9-8a17-d93711a3ac4f.png)

**What you expected to happen**:
display the correct data like before stacking

**Environment**:
- Grafana version: 5.4.2 and 6.3.3
- Data source type & version: mysql
- OS Grafana is installed on: CentOS 7.1
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by ikingnet** [comment]
this sql can simulate data
```sql
select 1566154740 as time_sec, 'a_job' as jobname, 15360 as mb union all
select 1566154800 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566154800 as time_sec, 'b_job' as jobname, 408576 as mb union all
select 1566154860 as time_sec, 'a_job' as jobname, 46080 as mb union all
select 1566154920 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566154980 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155040 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155100 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155160 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155220 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155280 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155340 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155400 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155460 as time_sec, 'a_job' as jobname, 6144 as mb union all
select 1566155520 as time_sec, 'a_job' as jobname, 15360 as mb union all
select 1566158400 as time_sec, 'b_job' as jobname, 181248 as mb
```

**Comment by torkelo** [comment]
For stacking it's important that your data is uniform (every series have values for every time point) otherwise Grafana tries to interpolate & insert data points to make the stacking possible which is error prone. 


You can use the $__timeGroup(dateColumn,‘5m’, 0) macro to group by 5m buckets and insert 0 for missing values for example.
