### ISSUE TITLE
Previous week sets wrong start day

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#18621]
**What happened**:
When i choose Previous Week it start on Sunday
**What you expected to happen**:
Start week on Monday
**How to reproduce it (as minimally and precisely as possible)**:
Select time range to Previous Week
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: InfluxDb 1.7.6
- OS Grafana is installed on: Debian
- User OS & Browser: Windows, 10 Chrome

My PC is set to GMT +1 time zone
In sweden the week starts on Monday

**Comment by torkelo** [comment]
Make sure in your chrome browser language settings have your local language first in the chain, Grafana uses the Accept-Language header to set locale

**Comment by flopp999** [comment]
> Make sure in your chrome browser language settings have your local language first in the chain, Grafana uses the Accept-Language header to set locale

This worked very well. I had english as primary language. After changed to Swedish it worked as expected.
