### ISSUE TITLE
Table sorts string columns according to value prior to 'Value Mapping'

### ISSUE THREAD

**Issue by anisbi** [grafana/grafana#18626]
**What happened**:
Created a table with String value as one of the columns, Mapped a string on this column to another value. When using dashboard to sort this column, the sort function takes into account the value of the String *prior* to the Value Mapping.

**What you expected to happen**:
I expect the sort of the table column to be by the value that is visually displayed (after the mapping was done)

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a Table widget with a 'String' column
2) Add a Rule to this Column and set the 'Value Mappings' of one of the values.
3) Save and go back to dashboard, sort aforementioned column
4) Column gets sorted by value prior to 'Value Mappings', so you might get `B*` before `A*`

**Environment**: (Not DevOps, so will try to answer, although I am not confident - although pretty sure a Front End bug)
- Grafana version: Grafana v6.2.1 (9e40b07)
- Data source type & version: Kibana? Version: 6.3.2
- User OS & Browser: Chrome

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
