### ISSUE TITLE
Advanced Formatting Options tag or any append/prepend option

### ISSUE THREAD

**Issue by lomithrani** [grafana/grafana#18624]
**What would you like to be added**:
I would like to be able to append/prepend value to the default options on variables with multiple value or  to have a new option tag  : ${variable:tag} =>  $tag_variable[0],$tag_variable[1]....

**Why is this needed**:
There are scenarios where you don't know the aliases name upfront and you and that would be great to be able to tweak a bit the default formating options   ${variable:csv:prepend:test-:append:-!}  could result in test-variable[0]-!, ... for instance

![image](https://user-images.githubusercontent.com/900881/63268224-f9e49900-c293-11e9-82e7-4fa8941bd52d.png)

As you can see the default option gives me all the intel I want but it's not really pleasant to read
![image](https://user-images.githubusercontent.com/900881/63268303-28627400-c294-11e9-933c-b990b69a77ea.png)

**Comment by torkelo** [comment]
Not sure this will be possible / feasible without a overcomplicated system to process alias expressions
