### ISSUE TITLE
Fill gradient inversion with negative-Y attribute

### ISSUE THREAD

**Issue by DRailleur** [grafana/grafana#18620]
Hi,

When using the new "Fill Gradient" option of Grafana 6.3.x, the gradient direction is not inverted when using the "Transform: negative-Y" attribute on a value.

With negative-Y selected, the gradient should spread from top/blackish to bottom/color.
So the "least colored" area will always be centered around the zero value.

Thanks

![image](https://user-images.githubusercontent.com/2602216/63251904-04406c00-c26f-11e9-97a7-30e510e37901.png)

**Comment by flopp999** [comment]
I agree with you, it look much nicer if the gradient was inverted when negative. Today the gradient goes from chosen color to white.
![white](https://user-images.githubusercontent.com/21694965/75016593-a0039c80-548b-11ea-82ee-83cb3a556f42.png)
I have some other ideas:
Possibility to choose from and to colors
![colors](https://user-images.githubusercontent.com/21694965/75016587-9f6b0600-548b-11ea-9590-07f00a408b78.png)
Possibility to choose positive and negative color
![different](https://user-images.githubusercontent.com/21694965/75016812-199b8a80-548c-11ea-8ceb-fe68e222c20f.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
