### ISSUE TITLE
Filtering on ifAlias not working

### ISSUE THREAD

**Issue by sjthespian** [grafana/grafana#18630]
**What happened**:
As described in https://community.grafana.com/t/ifalias-tag-filter-issue/13184/2, when I create new graphs in grafana 6.3.3 that filter on ifAlias (network metrics via. SNMP and telegraf), they don't populate. However, if I open the Query Inspector, the graphs suddenly populate with data.

**What you expected to happen**:
Graphs to populate with data when they are first created

**How to reproduce it (as minimally and precisely as possible)**:
* Create a new graph
* select SNMP data from ifXTable or ifTable, filtered by hostname and ifAlias
* If you hit this issue, the graph will not populate
* remove the ifAlias filter and see the graph populate with data for all interfaces
* restore the ifAlias filter and the graph will go blank
* open the Query Inspector and the graph will populate with data and stay that way

**Anything else we need to know?**:
Here is the info from my community post:
I’m seeing this in Grafana v6.3.3 (commit: 84d0a71) and InfluxDB 1.7.7. Both InfluxDB and grafana are running in containers from docker hub.

This query in grafana is returning no data:
```
SELECT derivative(mean("ifHCInOctets"), 1s) * 8 AS "Out", derivative(mean("ifHCOutOctets"), 1s) * -8 AS "In" FROM "ifXTable" WHERE ("hostname" = 'sw-cameras' AND "ifAlias" = 'Blue Iris') AND $timeFilter GROUP BY time($interval) fill(null)
```
However, if I remove the ifAlias condition I do get data.

The same query (manually entering the timestamps) does return data in influx itself:
```
> SELECT derivative(mean("ifHCInOctets"), 1s) * 8 AS "Out", derivative(mean("ifHCOutOctets"), 1s) * -8 AS "In" FROM "ifXTable" WHERE ("hostname" = 'sw-cameras' AND "ifAlias" = 'Blue Iris') AND time > now() - 15m GROUP BY time(5m) fill(null)
name: ifXTable
time                Out               In
----                ---               --
1566174600000000000 632266.92740743   -24692001.45777669
1566174900000000000 933974.9765925598 -36541166.32355794
1566175200000000000 764653.6639999899 -30257548.543997396
1566175500000000000 613105.5875555929 -24357553.581334636
```
Anyone have any idea why this could be happening? Have @jarryds and I hit some really obscure bug? The only thing I can think if is that hostname is a tag and ifAlias is a field, but I’m not sure why that should make a difference on the select.

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: InfluxDB 1.7.7
- OS Grafana is installed on: Ubuntu 18.04 (in docker)
- User OS & Browser: Mac OSX 10.14.5 / Chrome 75.0.3770.142
- Grafana plugins: None
- Others: Both Grafana and InfluxDB are running in containers from the "official" images on DockerHub

**Comment by torkelo** [comment]
instead of opening query inspector can you have chrome dev tools network tab open and replicate the "no data" case, what request is sent to InfluxDB and what is the response (as shown in the chrome network tab)

**Comment by papagian** [comment]
Closing due to the lack of response.
