### ISSUE TITLE
Include a Signal Generator datasource

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18632]
**What would you like to be added**:
It would be great to have a datasource would return complex and predictable signals.  Something comparable to a benchtop [Signal Generator](https://en.wikipedia.org/wiki/Signal_generator).  The datasource should produce standard signals like:
- constant
- sine waves, 
- sawtooth, 
- pulse (step or square),
- triangular
- noise

It should also generate signals/patterns relevant for testing monitoring systems
- random wallk
- periodic anomalies

This is similar to the TestData datasource, but the results must be consistent.  That is as you change the time window for the query, the results should be the same.

Any random behavior should have a consistent seed and accept `seed` as a request parameter.

**Why is this needed**:
The current TestData source is often hard to use for regression tests because the values can change.  Rather than adding more scenarios to TestData, lets create a new one with clear semantics and requirements.

Is this only useful for testing?  no...  having a predictable signal generator can be useful in may live systems.  perhaps we want to compare real data to an expected wave.  Perhaps alerting rules have some wave as part of their condition.

This is also a good data source to work out backend streaming support.

![gen](https://user-images.githubusercontent.com/705951/63289344-ba0db980-c273-11e9-9821-aa9a047e34f2.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
