### ISSUE TITLE
Grafana 2.0.x Dashboard data size

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#1863]
I ran into a problem with data size of a dashboard (stored in mysql).

If you add a template that is quite large it's very easy to exceed the max size of the data column in the database, thus totaly corrupting that dashboard. (max size 64k)

I "solved" that by doing the following. "alter table dashboard modify data mediumtext not null;"
But I havn't checked if that affects something else.. it looks like it works though.

echo "select * from dashboard where id=23;" | mysql -u <user> --password=<pass> grafana | wc
      2      80  112406

**Comment by torkelo** [comment]
thanks for reporting this!  changed the type, and added a sql migration step that will change the type on next server startup (will not do anything for your db as you have already changed the data type)
