### ISSUE TITLE
Selected(x) from list, strange behavior

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#18637]
**What happened**:
When I select more than one item the checkbox disappears.
**What you expected to happen**:
Checkbox should still be visible
**How to reproduce it (as minimally and precisely as possible)**:
Select more than one item in the list
**Anything else we need to know?**:
in earlier version of Grafana, when you clicked on Selected(x) it unchecked all items, this was very usefull because if the list includes 50+ items, you didn't need to scroll down to find selected items, in this version when you click on Selected(x) it will select all, next time you click it will deselect all. There is a All checkbox, so it seems to have almost same function. Maybe Selected(x) should be renamed to Deselect(x), if the function is to deselect, otherwise I don't understand the function with Select(x)
**Environment**:
- Grafana version: 6.3.2
- Data source type & version: InfxluDB, 1.7.6
- OS Grafana is installed on: Debian
- User OS & Browser: Windows 10, Chrome

**Comment by torkelo** [comment]
Strange, unable to replicate this: https://play.grafana.org/d/000000015/elasticsearch-templated?orgId=1&var-source=backend&var-source=site&var-host=server%2020&var-host=server3

**Comment by torkelo** [comment]
when I hit the Selected(x) it unselects all

**Comment by torkelo** [comment]
Can record a video, or try a different browser or OS? I tested it on Chrome on OSX and Windows 10

**Comment by flopp999** [comment]
I notice this only happens when you have white background

**Comment by flopp999** [comment]
And select more than one item in the list, as soon as I select item 2, checkbox for Select(x) disappear
