### ISSUE TITLE
PromQL editor doesn't handle linebreaks as of 6.3

### ISSUE THREAD

**Issue by k-meister** [grafana/grafana#18642]
**What happened**:
In many cases, PromQL expressions that I use on Prometheus datasource take 3 to 6 rows and contain a mix of curly, square and common brackets.
To make it readable, I used line-breaking extensively prior to version 6.3
In 6.3, when I hit "enter", nothing happens.

**What you expected to happen**:
Line-breaking works, or there is an option that enables manual PromQL formatting

**How to reproduce it (as minimally and precisely as possible)**:
Go to promQL metric expression editor, hit "Enter"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOs 7.4
- User OS & Browser: MacOs Mojave 10.14.6
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
Try using shift + enter key, it might now work every time as we have some open bugs relating to this.  We have many reports on issues like this with new editor and we are working on fixing them.
