### ISSUE TITLE
Panel zoomable based on relative time 

### ISSUE THREAD

**Issue by SwathiMuppalla** [grafana/grafana#18650]
Hi,
Is it possible to zoom the panel based on relative time.

![Screenshot (28)](https://user-images.githubusercontent.com/22199547/63381723-4220bb80-c367-11e9-8e8c-4bec925f4b14.png)

In the above example i have given relative time as 9M but in the panel i see there is a gap in the beginning of graph…I know that when I zoom or change the Dashboard time to a custom absolute time range, all panel overrides will be disabled. **But Is there an option where the panel zooms based on relative time 9M?**  It is difficult to zoom in every panel based on different absolute time. If I override relative time it would be helpful that each panel zooms in @torkelo @matschaffer

**Comment by torkelo** [comment]
Not sure what your asking for or what your scenario is. 

>  But Is there an option where the panel zooms based on relative time 9M

What does this mean??  you can only mark a region (select region) you want to zoom. And then that time region will be used.

**Comment by SwathiMuppalla** [comment]
Ok sorry, I guess made it confused. Is it possible the panel zooms based on relative time specified means? Rather than selecting the time region, I want to zoom, because the time region I want to zoom is the time region I have specified in relative time and I see a gap at the beginning of the graph which I don't want.. Basically, I want it to be time-independent.   If I zoom in for one panel all other panels time region is changed too which I don't want it to happen.

**Comment by ryantxu** [comment]
Do you mean something like the range selector here:
http://dygraphs.com/gallery/#g/range-selector

zooming into the already selected data? or do you want to query only one panel with more resolution?

**Comment by SwathiMuppalla** [comment]
@ryantxu Yes it more like range selector. I want to query only one panel with more resolution.

**Comment by torkelo** [comment]
Still not sure what your asking, the panel your showing that lacks is missing data, how is this relating to zoom without single panel only?
