### ISSUE TITLE
access to Material UI from plugins

### ISSUE THREAD

**Issue by Jamen-Huang** [grafana/grafana#18655]
systemjs fails to dynamically load imported modules like material-ui...

here's what I tried to import, most of them works but the one call 'TablePagination' doesn't
![image](https://user-images.githubusercontent.com/46877804/63408720-05ba9180-c433-11e9-8c0e-69881fdc07e3.png)

**Actual Result**:
most of what I imported works but the one call 'TablePagination' doesn't
and throws
![image](https://user-images.githubusercontent.com/46877804/63408846-43b7b580-c433-11e9-8504-f3e466dc442d.png)

**Expected Result**
everything is working

**Environment**:
- Grafana version: v6.3.1
- Data source type & version: influx
- User OS & Browser: Chrome on Mac
- Others: in a docker container

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

I responded to your existing question on the community site.
