### ISSUE TITLE
Add custom/multiple colors to show different status to table plugin

### ISSUE THREAD

**Issue by syedsfayaz** [grafana/grafana#18651]
**Have more than 3 status for the table (Currently we have only 3)**:
Can we add custom Css class to add more styling to the table cells or rows.

** I am currently tracking multiple status "success/failed/aborted/inprogress/pending"**:
 I want to show different colors for different status. Unfortunately We can only show 3 colors now. Apart from that I want to show a blinking color for Inprogress status. This can be achieved if I am able to add a CSS class for a status.

**Comment by torkelo** [comment]
> Can we add custom Css class to add more styling to the table cells or rows.

Sorry no this is not possible (and will not)

**Comment by torkelo** [comment]
>  want to show different colors for different status. Unfortunately We can only show 3 colors now. Apart from that I want to show a blinking color for Inprogress status. This can be achieved if I am able to add a CSS class for a status.

In the new table panel we hope to introduce in the coming months this should be possible (at least more than 3 colors, blinking not so much)

**Comment by syedsfayaz** [comment]
@torkelo Thank you.

**Comment by nmingotti** [comment]
@torkelo, I am interested in this feature too, i would need at least one color more. 

When the feature will be available could you update us here please ?
