### ISSUE TITLE
constant variable (hidden) has been updated,but still worked with the old value

### ISSUE THREAD

**Issue by hobo212** [grafana/grafana#18658]
constant variable (hidden) has been updated,but still worked with the old value;
new value only worked in edit view ,but in recenty view,it  still worked with the old value;
grafana version:6.4.2
![image](https://user-images.githubusercontent.com/9428346/63426685-014ba400-c446-11e9-8eea-873991b6e45c.png)

**Comment by torkelo** [comment]
Be sure to check the checkbox "save current variables" when you save:
![image](https://user-images.githubusercontent.com/10999/63426943-49ea6980-c414-11e9-8a5b-d293df7ee92a.png)

**Comment by hobo212** [comment]
3q, reply this question so quickly.
it is very strange.
1.if the variable type is contant:
  1.1 if the variable use in the General-description,even if i don't choose "save current variable", it can work with new variable;
  1.2 if the variable use in the opentsdb filter ,event if i choose "save current variable", it still  work with old variable;
2.if the variable type is Text box:
  2.1if the variable use in the opentsdb filter ,even if i don't choose "save current variable", it can work with new variable;
