### ISSUE TITLE
Cannot compile https://github.com/grafana/simple-json-backend-datasource

### ISSUE THREAD

**Issue by anantmf** [grafana/grafana#18652]
Hi,

I am trying to follow https://github.com/grafana/grafana/blob/master/docs/sources/plugins/developing/backend-plugins-guide.md
And I faced some issue compiling simple-json-backend-datasource.
https://github.com/grafana/simple-json-backend-datasource
 First I faced error with cannot find package, after doing `go get` that got resolved, however, now it errors out with following error :

`pkg/plugin.go:25:4: cannot use &datasource.DatasourcePluginImpl literal (type *datasource.DatasourcePluginImpl) as type "github.com/hashicorp/go-plugin".Plugin in map value:
	*datasource.DatasourcePluginImpl does not implement "github.com/hashicorp/go-plugin".Plugin (wrong type for Client method)
		have Client(*"github.com/grafana/grafana_plugin_model/vendor/github.com/hashicorp/go-plugin".MuxBroker, *rpc.Client) (interface {}, error)
		want Client(*"github.com/hashicorp/go-plugin".MuxBroker, *rpc.Client) (interface {}, error)
`

Can someone please guide me in correct direction?

**Comment by torkelo** [comment]
> First I faced error with cannot find package

find what package?

**Comment by anantmf** [comment]
it was complaining about github.com/grafana/grafana-plugin-model.
I got it resolved by following 
`go mod init github.com/grafana/grafana-plugin-model`

however, when I used `go get`, I was getting above error.
