### ISSUE TITLE
auto decimals for 2.22235 shows 2

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18662]
**What would you like to be added**:
```
getDecimalsForValue(2.22235)
```
shows 2.  It should show more precision.   Maybe 2.22

I think we could change the `auto` rule to always show at least 3 numbers without trailing zeros?
```
2.22222 => 2.22
22.2222 => 22.2
222.222 => 222
```

**Why is this needed**:
The auto format should show a reasonable looking value with some significant digits

**Comment by torkelo** [comment]
think I have quick fix for this, recently solved this issue for the graph panel https://github.com/grafana/grafana/pull/18370
