### ISSUE TITLE
Bar Gauge - show only tag values

### ISSUE THREAD

**Issue by vinsguru** [grafana/grafana#18669]
First of all, Thank you so much for what you guys do! Grafana is an awesome tool.

The bar gauge looks stunning.  However I feel it is missing a basic feature.

I created a bar gauge grouping by country. 

```
sample-test.sum {country: CA}
sample-test.sum {country: US}
sample-test.sum {country: UK}
```
Is there anyway to show only the grouped by field! In this case, country values like CA,US, UK instead of  sample-test.sum {country: CA} etc

![Screenshot from 2019-08-21 16-00-48](https://user-images.githubusercontent.com/6864530/63468205-e3257a00-c42c-11e9-9bb6-8aa10b4cd5cd.png)

**Comment by torkelo** [comment]
Do this in the query using Alias/Legend field  (depends on your query)

**Comment by vinsguru** [comment]
@torkelo , I already knew about alias. In the approach, you are suggesting, it would make 3 different calls for each country. Not an efficient approach I guess. It would be great if we could introduce some variable like `$__tag_name`

**Comment by torkelo** [comment]
Most data sources support query alias patterns like that, which datasource are you using?

**Comment by vinsguru** [comment]
@torkelo 
Sorry..I should have mentioned earlier. It is InfluxDB 2

My data is approximately like this. Now `SELECT "value" FROM "measurement" WHERE $timeFilter GROUP BY "country"`

Timestamp  country   value
10:00:00       US          1
10:00:01       US          2
10:00:02       UK          2
10:00:03       CA          5

Now if you see I get all the data using single query. 
The workaround is - doing something like this and use alias. But it is bad.

 `SELECT "value" FROM "measurement" WHERE ("country"="US") $timeFilter`

 `SELECT "value" FROM "measurement" WHERE ("country"="UK") $timeFilter`

 `SELECT "value" FROM "measurement" WHERE ("country"="CA") $timeFilter`
