### ISSUE TITLE
Cursor jumps to the end of field when I try to edit DataSource's Name

### ISSUE THREAD

**Issue by johnatannvmd** [grafana/grafana#18660]
**What happened**:
Can properly edit DataSource name. Cursor constantly sets to the end. When I begin to edit Name, URL became empty.

GIF (169 KB):
https://1drv.ms/u/s!AlUSOETTpCEOpoRAJWpkbapxXW4aMg

**What you expected to happen**:
The cursor should work as expected. URL or other fields should not become empty.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create new DataSource.
2) Set the URL
3) Enter new name
4) URL becomes empty
5) Set cursor in the name field to the beginning
6) Type a letter
7) Cursor jumps to the end

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.3.2 (4832460)
- Data source type & version: Influx Datasource
- User OS & Browser: Firefox 69.0b15 (64-bit)

**Comment by flopp999** [comment]
Confirm this.
I also found when editing name and hit HOME first character gets in the front, but then it jumps to the end.
Grafana version: Grafana v6.3.2
Data source type & version: Influx Datasource
User OS & Browser: Windows 10, Chrome

**Comment by torkelo** [comment]
thanks for reporting this! we will try to fix soon!
