### ISSUE TITLE
Link to official helm chart in documentation

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#18665]
Helm provides an official chart for Grafana which makes it easy for helm users to get up and running with Grafana on kubernetes.

We should add a section to the documentation describing how to use helm to run Grafana and linking to the helm chart.

https://github.com/helm/charts/tree/master/stable/grafana

**Comment by hairyhenderson** [comment]
In addition to adding something in the docs about the chart, it'd probably be useful to fork that chart into this repo, or into another repo in the Grafana organization, because the github.com/helm/charts repo has entered a deprecation timeline:

https://github.com/helm/charts#status-of-the-project

**Comment by oddlittlebird** [comment]
I can add a link, but I don't know how to fork the chart. Can someone help with this?

**Comment by oddlittlebird** [comment]
@DanCech or @robbymilo , can one of you help me with this?

**Comment by aureq** [comment]
The Helm chart deadline has been set to November 2020. Beyond this date, users won't be able to receive Grafana updates through this deployment method. It would be great if the Grafana team could look into this.

Thanks

**Comment by scottrigby** [comment]
@oddlittlebird @aureq Would you like some help with this? We've been helping orgs adopt stable charts that install their apps. The new helm repo 

1. Retain git history from stable 
1. Use helm GitHub actions for CI (chart testing) and CD (releasing chart artifacts so the GitHub repo becomes a helm repo)

Happy to do help this week, as long as there's an admin of this repo that can do the necessary things (mostly by creating an empty gh-pages branch).

**Comment by scottrigby** [comment]
Alternatively, we could have a new git repo at github.com/grafana/helm-charts and move both Loki and Grafana charts there, so CI/CD and chart repo info for end users is all in one place. It's also a bit simpler to grant access to community members to help maintain the chart(s) without access to the rest of the application codebase. If you want to go this route I could get started creating the charts in a temporary repo for you and once it's ready and you approve we could just transfer that repo to your org. This is what we've done for orgs like prometheus-community and jenkinsci.

**Comment by torstenwalter** [comment]
I could also help with this.

**Comment by scottrigby** [comment]
It appears this is _partially_ done - see https://github.com/helm/charts/pull/23662. However, I think there needs to be some changes, which I've commented on https://github.com/helm/charts/pull/23662#issuecomment-685085598 and https://github.com/helm/charts/pull/23662#issuecomment-685896059.

**Comment by torstenwalter** [comment]
The chart is now completely migrated to https://github.com/grafana/helm-charts

It's also listed in [artifacthub](https://artifacthub.io/packages/helm/grafana/grafana).

**Comment by oddlittlebird** [comment]
Is this issue still valid?

**Comment by oddlittlebird** [comment]
Looks like this is no longer valid.
