### ISSUE TITLE
Datemath: support math on ms and interval strings

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#18679]
In https://github.com/grafana/grafana/pull/18636 we are introducing ability to specify a window around specified timestamp to be translated into custom time range. This window is symetricall now.

It could possibly be good to allow custom time range based on `__value_time` built in variable, i.e. in data links to specify `?from=${__value_time}&to=${__value_time}+5s`. To enable that we need to extend datemath helpers to allow math operations on ms and string intervals.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
