### ISSUE TITLE
The data I got using elasticsearch is wrong.

### ISSUE THREAD

**Issue by lovelly** [grafana/grafana#18678]
### grafana Request Payload 
`
{
	"search_type": "query_then_fetch",
	"ignore_unavailable": true,
	"index": "app_info2"
} {
	"size": 0,
	"query": {
		"bool": {
			"filter": [{
				"range": {
					"c_time": {
						"gte": "1565855541893",
						"lte": "1566460341893",
						"format": "epoch_millis"
					}
				}
			}, {
				"query_string": {
					"analyze_wildcard": true,
					"query": "*"
				}
			}]
		}
	},
	"aggs": {
		"5": {
			"terms": {
				"field": "tags.keyword",
				"size": 10,
				"order": {
					"1": "desc"
				},
				"min_doc_count": 1
			},
			"aggs": {
				"1": {
					"sum": {
						"field": "start_count"
					}
				},
				"3": {
					"date_histogram": {
						"interval": "100d",
						"field": "c_time",
						"min_doc_count": 0,
						"extended_bounds": {
							"min": "1565855541893",
							"max": "1566460341893"
						},
						"format": "epoch_millis"
					},
					"aggs": {
						"1": {
							"sum": {
								"field": "start_count"
							}
						}
					}
				}
			}
		}
	}
}`

####  get response 

![image](https://user-images.githubusercontent.com/13118848/63497327-1a139280-c4f6-11e9-87ae-6cf5393e2eff.png)

#### I copied 'grafana Request Payload'  to postman and got  
![image](https://user-images.githubusercontent.com/13118848/63497566-9908cb00-c4f6-11e9-949a-122bfdc048a7.png)

**Comment by torkelo** [comment]
Nothing, the backend just proxies the request and response, does not modify either. Must be something with your query or browser or elastic search setup that causes different results. 

Could be due to the queries not being executed at the same time or maybe targeting different elasticsearch servers in a cluster? The doc count results are different to clearly elasticsearch is processing a different set of documents in the results you pasted.

**Comment by lovelly** [comment]
> Nothing, the backend just proxies the request and response, does not modify either. Must be something with your query or browser or elastic search setup that causes different results.
> 
> Could be due to the queries not being executed at the same time or maybe targeting different elasticsearch servers in a cluster? The doc count results are different to clearly elasticsearch is processing a different set of documents in the results you pasted.

#### It doesn't matter with time.  
It doesn't matter with time. The number of documents is fixed. I copied the grafana Request. Time is also static.

**Comment by torkelo** [comment]
ok, then something in your elasticsearch server or browser, or postman is making causing a difference or (grafana backend). Maybe some http header / elasticsearch auth? is the url your request to the exact same as in Grafana?
