### ISSUE TITLE
viewers_can_edit in grafana.ini not overriding defaults

### ISSUE THREAD

**Issue by mtanatwine** [grafana/grafana#18682]
**What happened**:
 The value of viewers_can_edit in grafana.ini seems to be being ignored and the one from defaults.ini is being used instead. The line I've added to grafana.ini is "viewers_can_edit = true" and there is no semi-colon preceding it. The settings pane still shows it as false, even after a restart, and users are unable to access the Explore feature.

**What you expected to happen**:
Users should be able to access the Explore feature, according to the code in public/app/core/services/context_srv.ts. The settings pane should also reflect this change.

**How to reproduce it (as minimally and precisely as possible)**:
Merely set "viewers_can_edit = true" in grafana.ini and leave the one in defaults.
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.3.3 (commit: 84d0a71)
- Data source type & version: MariaDB 10.1.26 on AWS as an RDS instance
- OS Grafana is installed on: CentOS Linux release 7.4.1708 (Core)
- User OS & Browser: Chrome 76
- Grafana plugins: N/A
- Others:

I know that grafana.ini is being read and used, because other options like "disable_signout_menu = true" is being used, as well as all the other connection strings and such.

**Comment by torkelo** [comment]
are you sure the option is uncommented?

**Comment by mtanatwine** [comment]
Absolutely:

[root@xxxxxx grafana]# grep viewers_can_edit grafana.ini
viewers_can_edit = true

**Comment by torkelo** [comment]
and you restarted grafana-server after change? works for me and here https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

**Comment by mtanatwine** [comment]
Yep:

[root@xxxxxx grafana]# grep viewers_can_edit grafana.ini
viewers_can_edit = true
[root@xxxxxx grafana]# ls -lrt grafana.ini
-rw------- 1 grafana grafana 12830 Aug 22 11:22 grafana.ini
[root@xxxxxx grafana]# ps -ef | grep grafana-server | grep -v grep | grep -v dhcp
grafana   8028     1  1 11:24 ?        00:01:42 /usr/sbin/grafana-server --pidfile=/var/run/grafana/grafana-server --config=/etc/grafana/grafana.ini cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins

**Comment by torkelo** [comment]
Not sure what could be wrong, anonymous enabled,  viewers_can_edit = true,  I can access explore via sidemenu

**Comment by mtanatwine** [comment]
The problem was less that they can't access the explore, and more that the setting doesn't seem to be taking effect. I'll keep poking about and trying things.

**Comment by torkelo** [comment]
very strange

**Comment by kovetskiy** [comment]
We had the same issue, turns out we put `viewers_can_edit` into an incorrect section for this field. We put it to `[server]` while it should be in `[users]`.
