### ISSUE TITLE
Align interval parsing (and input validation) between frontend and backend 

### ISSUE THREAD

**Issue by anderswillersrud** [grafana/grafana#18684]
**What happened**:
The input field Min time interval in the Postgresql data source does not support 'ms' as input. The config (grafana/public/app/plugins/datasource/postgres/partials/config.html) has the input pattern ` ng-pattern="/^\d+[Mwdhmsy]$/"`, which is missing the ms.

**What you expected to happen**:
Being able to set the `Min time interval` to `10ms`, supporting sub-second data.

**How to reproduce it (as minimally and precisely as possible)**:
Add a new Postgresql data source and input the `Min time interval`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Postgresql 10
- OS Grafana is installed on: Ubuntu 18.04/Docker
- User OS & Browser: Windows 10 and Chrome (Version 76.0.3809.100)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
there is a pattern in the backend, https://github.com/grafana/grafana/blob/master/pkg/components/gtime/gtime.go#L9

the frontend regex looks like this:
https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.ts#L158 

and that one supports decimals as well so you could type 0.2s but that looks not be supported in backend

**Comment by dprokop** [comment]
@torkelo ms input in SQL datasources was is not supported, adding support for that in #18719

**Comment by ying-jeanne** [comment]
tested with minimul interval + __timegroup macro, works fine. bug fixed.
