### ISSUE TITLE
Bug: when constant variable was updated it not work in filter

### ISSUE THREAD

**Issue by hobo212** [grafana/grafana#18680]
it is very strange in grafana version:6.2.1;

1. variable type is contant:
1.1 if the variable use in the General-description,even if i don't choose "save current variable", it can work with new variable;
1.2 if the variable use in the opentsdb filter ,event if i choose "save current variable", it still work with old variable;

2. variable type is Text box:
2.1 if the variable use in the opentsdb filter ,even if i don't choose "save current variable", it can work with new variable;

**Comment by davkal** [comment]
Related #28428 ?

**Comment by torkelo** [comment]
Tested this in v7.3 and looks fixed
