### ISSUE TITLE
BarGauge: Use horizontal space more efficently when bar title is to the left 

### ISSUE THREAD

**Issue by kdorsel** [grafana/grafana#18689]
**What happened**:
![image](https://user-images.githubusercontent.com/2569415/63546980-0d446e00-c4f9-11e9-8422-979dfe4042a5.png)

![image](https://user-images.githubusercontent.com/2569415/63547175-92c81e00-c4f9-11e9-8cf5-3b696d8b88dc.png)

As can be seen here when there are enough series the field title goes to the left, but leaves a huge amount of extra space (red arrows).

When there are a smaller amount of series the left padding is gone, but the padding on the right still exists. I have set the maximum values of the axis to be the same as the max presented value as such the longest bar is at its max length.

**What you expected to happen**:
Less padding.

**How to reproduce it (as minimally and precisely as possible)**:
Any horizontal bar gauge with sufficient series based on its height.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version:
6.3.2
- Data source type & version:
postgres 11.4
- OS Grafana is installed on:
Windows server 2016
- User OS & Browser:
Chrome 76 on windows 10
- Grafana plugins:
None
- Others:
N/A

**Comment by torkelo** [comment]
this is implemented in v6.6 (master)
