### ISSUE TITLE
List dashboards in graphite data source renders incorrect URL

### ISSUE THREAD

**Issue by gf-atebbe** [grafana/grafana#1868]
When I try to add a new Graphite data source and click on the List Dashboards (under Dashboards -> Import) button nothing seems to happen and eventually I get the error "Failed to load dashboard list from graphite".  When I inspect the graphite-web logs I see that it looks the like the URL being used to list the dashboards is incorrect.  

The route in the log is the following:
/dashboard/find?query=

I think the correct route should be:
/dashboard/find/?query=

I'm running this on Debian, using the following package to install grafana:
https://grafanarel.s3.amazonaws.com/builds/grafana-2.0.2.linux-x64.tar.gz

I'm running this in a docker container (grafana and graphite in separate containers), and the URL I set in the data source is:
http://172.17.42.1:8000

When I curl http://172.17.42.1:8000/dashboard/find/?query= within the grafana container I get the expected output.

I tried both direct and proxy access but both produce the same result.

**Comment by torkelo** [comment]
thanks for reporting such a detailed issue, I had noticed that when proxing graphite the dashboard find query did not work, when using direct it did work, could not find the difference in the query, thanks for spotting it. Must be something in the golang http reverse proxy

**Comment by xtang** [comment]
@torkelo It seems dashboard find query should be in POST instead of GET

**Comment by garyrule** [comment]
Just curious if there is any update on this or a manual work-around? I'm seeing the same issue.

**Comment by torkelo** [comment]
the work around is to use direct access in the data source settings for the import to work

**Comment by gf-atebbe** [comment]
I'm still not having any luck with this using a direct connection as you suggested @torkelo .  When I edit the data source and click the Test Connection button I get an unknown error and see nothing in the logs.  I do see the following line in my graphite-web log file:

[pid: 19|app: 0|req: 703/703] 10.0.70.118 () {44 vars in 814 bytes} [Thu Aug 20 13:58:02 2015] OPTIONS /metrics/find/?query=* => generated 205 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 170 bytes (1 switches on core 0)

Grafana just displays "Unknown error" in the test results box.

The following command works without issue from within my Grafana container.  This is the same URL I am using to configure my data source in Grafana (http://graphite.service.dc1.consul:8000).

curl -X OPTIONS http://graphite.service.dc1.consul:8000/metrics/find/?query=*

I also used -X GET which produces the same output.

**Comment by torkelo** [comment]
for direct access you must add CORS headers to graphite

**Comment by dpost** [comment]
Did you find a workaround for this? Proxy isn't working for me and I'm stuck on the Access-Control-Allow-Origin error

**Comment by nokster1001** [comment]
with apache and still configured as proxy, adding this to grafana's virtual host tab worked for me:
ProxyPassMatch    "/dashboard/find(.*)" "http://127.0.0.1:3500/dashboard/find/(.*)"
where 127.0.0.1:3500 is the graphite instance.

**Comment by torkelo** [comment]
the dashboard import feature was removed a while back so closing this
