### ISSUE TITLE
4 Digit Value To Text Not Working

### ISSUE THREAD

**Issue by tgregory86** [grafana/grafana#18699]
If a value to text mapping has 4 digits, the value doesn't map to the text in the single stat panel. However if the value is 3 digits or less then the mapping works fine. 

![Grafana](https://user-images.githubusercontent.com/45361664/63600233-2b5dad00-c591-11e9-903a-943487035dcf.PNG)

Running: 
Grafana v6.3.3 (commit: 84d0a71)

**Comment by torkelo** [comment]
Can you show the raw response from your query? check query inspector

**Comment by ryantxu** [comment]
Without looking deeper, this is likely already fixed in master.  The new code makes sure the the mapping values are checked against the text value that will be displayed, not against the raw value

**Comment by tgregory86** [comment]
Heres the raw response:

**Comment by tgregory86** [comment]
Object
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/3/query"
params:Object
db:"speedtests"
q:"SELECT last("server") FROM "speed_test_results" WHERE time >= now() - 3h GROUP BY time(30m) fill(none)"
epoch:"ms"
data:null
precision:"ms"
response:Object
results:Array[1]
0:Object
statement_id:0
series:Array[1]
0:Object
name:"speed_test_results"
columns:Array[2]
0:"time"
1:"last"
values:Array[6]
0:Array[1566815400000,5591]
1:Array[1566817200000,5591]
2:Array[1566819000000,5591]
3:Array[1566820800000,14480]
4:Array[1566822600000,5561]
5:Array[1566824400000,5591]

**Comment by hugohaggmark** [comment]
Can't repro this on `master` or `6.4 beta 2` so closing this issue for now.
