### ISSUE TITLE
Alias not detected in Gauge Bar

### ISSUE THREAD

**Issue by DanielGonzalezPerez** [grafana/grafana#18692]
**What happened**:
When you have a query grouped by Terms the alias is not detected but if is grouped by Date histogram the alias appear as I show in the screenshot:
![image](https://user-images.githubusercontent.com/37359233/63575632-d0c15280-c58a-11e9-9f77-f2e7ab0cc7a4.png)

**What you expected to happen**:
Show alias name when a query its grouped by Terms.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: Elasticsearch 7.x
- OS Grafana is installed on: Centos 7
- User OS & Browser: Admin Google Chrome
- Grafana plugins:
- Others:

**Comment by ryantxu** [comment]
What do you have set to the title?  is it auto?  The fact your second object is labeled OK is interesting

![image](https://user-images.githubusercontent.com/705951/63641472-e48cb780-c663-11e9-9d66-d5b1eae3fe9e.png)

I tried to reproduce... at least with the testdata object is is OK:
![image](https://user-images.githubusercontent.com/705951/63641466-cd4dca00-c663-11e9-999b-8f7d61b44974.png)

maybe something different about elastic

**Comment by torkelo** [comment]
This is because one series is returning time series the other a table , the alias field is not used for table results

**Comment by DanielGonzalezPerez** [comment]
> This is because one series is returning time series the other a table , the alias field is not used for table results

Thanks @torkelo 

Then Cant I set a different title for each query (Bar) when is returning a table?
Because what I want to do is count the different protocols, something that looks like this:
![image](https://user-images.githubusercontent.com/37359233/63671012-b97aa300-c7de-11e9-8fb1-281b521f8fd5.png)
(Im using the field Title to set the protocols names)
![image](https://user-images.githubusercontent.com/37359233/63671447-c4820300-c7df-11e9-81ed-bca3db6265f0.png)
But this are three Bar gauges and looks ugly I wolud like to have all together but if do it I cant identify wich protocols are:
![image](https://user-images.githubusercontent.com/37359233/63671348-97cdeb80-c7df-11e9-93ec-2f1b229a397a.png)

**Comment by torkelo** [comment]
You can, the problem is your first Terms query could return multiple fields (as it's a group by) and the alias would just make them all the same (or is unclear how to apply). 

You can fix it by adding a Date Histogram with a very long interval (1y) (have it on both queries). That way both return time series with a single value.

**Comment by DanielGonzalezPerez** [comment]
> You can, the problem is your first Terms query could return multiple fields (as it's a group by) and the alias would just make them all the same (or is unclear how to apply).
> 
> You can fix it by adding a Date Histogram with a very long interval (1y) (have it on both queries). That way both return time series with a single value.

Ok it works, Thank you @torkelo :)

**Comment by dprokop** [comment]
Closing as from the comments I understand the issue is solved.
