### ISSUE TITLE
Immediate logout after successful login

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#18690]
**What happened**:
Immediately following successful login with local admin credentials (green login successful box in upper right), Grafana fails to load home dashboard gets 401 Unauthorized and am redirected to login page.

**What you expected to happen**:
Successful load of home dashboard following successful authentication

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to log in with local admin account (no external auth enabled)

**Anything else we need to know?**:
Relevant log snippet (in debug mode):
```
t=2019-08-22T19:20:34-0500 lvl=dbug msg="user auth token created" logger=auth tokenId=53 userId=1 clientIP=10.1.10.28 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15" authToken=d1f8e6e0c2a7cc022773268b914c18fe8d0a8a246481e3991c75616459804311
t=2019-08-22T19:20:34-0500 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2019-08-22T19:20:34-0500 lvl=dbug msg="seen token" logger=auth tokenId=53 userId=1 clientIP=10.1.10.28 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15" authToken=d1f8e6e0c2a7cc022773268b914c18fe8d0a8a246481e3991c75616459804311
t=2019-08-22T19:20:34-0500 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/dashboards/home status=401 remote_addr=10.1.10.28 time_ms=0 size=26 referer=https://influxdb-grafana/
t=2019-08-22T19:20:34-0500 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=10.1.10.28 time_ms=0 size=26 referer=https://influxdb-grafana/
t=2019-08-22T19:20:34-0500 lvl=dbug msg="user auth token revoked" logger=auth tokenId=53 userId=1 clientIP=10.1.10.28 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"
t=2019-08-22T19:20:34-0500 lvl=info msg="Successful Logout" logger=http.server User=admin@localhost
t=2019-08-22T19:20:34-0500 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/logout status=302 remote_addr=10.1.10.28 time_ms=2 size=29 referer=https://influxdb-grafana/
```
Link to Video of issue:
https://imgur.com/VDZzSoP

Grafana is still working fine with Chrome and Firefox on MacOS Mojave, but Safari v 12.1.2 is having the issue

**Environment**:
- Grafana version: v6.3.3 (but goes farther back, saw on v6.2.5)
- Data source type & version: InfluxDB v 1.7.7
- OS Grafana is installed on: CentOS 7.6
- User OS & Browser: Mac OS Mojave & Safari, iOS12.4 (Safari and Chrome)
- Grafana plugins: Pie Chart
- Others:

**Comment by davidmccaffrey** [comment]
I have a user encountering the same Failure, also using Safari, when attempting to log into either of 2 different Grafanas that we have.  One is running v6.0.2 (commit: 3f4c2e7), the other is v6.2.4 (commit: ee01897).
However:
  The issue is when using their own LDAP login credentials, not the Admin login.  
  The user was able to successfully log in using Firefox from their iOS system.
  We also found that using the dotted numeric IP instead of the FQDN in their URL, they were able to login from Safari.

**Comment by torkelo** [comment]
what is your grafana.ini settings? (the server settings) and auth settings.

**Comment by dprokop** [comment]
@jdmaloney @davidmccaffrey could you please try modifying your `cookie_samesite` setting to `none`:

``` 
cookie_samesite = none
```

and upgrading Grafana to 6.3.3?

**Comment by marefr** [comment]
@jdmaloney would need you to provide more information using developer tools in Safari. 

I'm using Chrome developer tools, but think Safari developer tools should have similar features.
1. Logout and navigate to login page
2. Open Safari developer tools
3. Find the network tab where network requests can be recorded and check "preserve log" or simular:
![image](https://user-images.githubusercontent.com/1668778/63750250-66235600-c8ad-11e9-8f58-556b054e7a5f.png)
4. Login and extract information from request/response of the POST to /login url and include screenshot here. Here's an example from my local machine:
![image](https://user-images.githubusercontent.com/1668778/63750412-b1d5ff80-c8ad-11e9-8fef-dd919859de14.png)
5. If you can see details about cookies that would also be interesting to include screenshot of. Here's an example from my local machine:
![image](https://user-images.githubusercontent.com/1668778/63750551-f366aa80-c8ad-11e9-83ab-d799d5bb2698.png)

Last thing I can think of verifying is what Safari Privacy setting you're using, see https://support.apple.com/en-ph/guide/safari/sfri11471/mac for reference.

**Comment by marefr** [comment]
One more question, do you have a valid SSL certificate for using https for influxdb-grafana? Maybe Safari don't allow cookies of domain with no top-level domain? Or you'll need to enable secure cookies since you're running https, see https://grafana.com/docs/installation/configuration/#cookie-secure for reference.

**Comment by rlindner** [comment]
I have been experiencing the same behavior with Mobile Safari on my iPad lately, when accessing Grafana running on my iMac (http://iMac:3000/login). I've then tried to login with Safari on my iMac via http://localhost:3000/login which was working. So I tried to login on my iMac via http://iMac:3000/login and then I've had the same problem as on the iPad on my iMac. So this might be a hostname related issue in any way.

**Comment by marefr** [comment]
@jdmaloney based on your last two screenshots it seems like you haven't configured `cookie_samesite = none`

**Comment by jdmaloney** [comment]
This is the entire chunk of my session config, I think I have it set properly
```
#################################### Session ####################################
[session]
# Either "memory", "file", "redis", "mysql", "postgres", default is "file"
;provider = file

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
# postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
;provider_config = sessions

# Session cookie name
cookie_name = none

# If you use session in https only, default is false
cookie_secure = true

# Session life time, default is 86400
;session_life_time = 86400

cookie_samesite = none
```
Also I'm now running v6.3.4, just as a heads up

**Comment by marefr** [comment]
@jdmaloney Oh I see the problem now. 

First, session storage was removed in Grafana v6.2, see https://grafana.com/docs/installation/configuration/#session. You can also read about it in the upgrade notes which is always a good thing to do before upgrading: https://grafana.com/docs/installation/upgrading/#session-storage-is-no-longer-used

Second, `cookie_secure` and `cookie_samesite` should be configured in the `[security]` section. Example:

```ini
[security]
cookie_secure = true
cookie_samesite = none
```

**Comment by jdmaloney** [comment]
@marefr Still no luck, below is my security section and what I'm seeing now with Developer tools, there are some differences now in what I see in Developer tools when I attempt to log in.  Same symptom though.  All parts of the session config are now commented out.

```
#################################### Security ####################################
[security]
# default admin user, created on startup
;admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
;admin_password = admin

# used for signing
;secret_key = ~Sensored, not sure if this is safe to paste publicly~

# Auto-login remember days
;login_remember_days = 7
;cookie_username = grafana_user
;cookie_remember_name = grafana_remember

# disable gravatar profile images
;disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port separated by spaces)
;data_source_proxy_whitelist =

[snapshots]
# snapshot sharing options
;external_enabled = true
;external_snapshot_url = https://snapshots-origin.raintank.io
;external_snapshot_name = Publish to snapshot.raintank.io

# remove expired snapshot
;snapshot_remove_expired = true

# remove snapshots after 90 days
;snapshot_TTL_days = 90

cookie_secure = true
cookie_samesite = none
```
<img width="2510" alt="Screen Shot 2019-08-30 at 3 57 22 PM" src="https://user-images.githubusercontent.com/16138910/64050989-4e630080-cb3f-11e9-9717-37171e3fa388.png">
<img width="2515" alt="Screen Shot 2019-08-30 at 3 57 37 PM" src="https://user-images.githubusercontent.com/16138910/64050990-4e630080-cb3f-11e9-8507-174901888c19.png">

**Comment by Argon-** [comment]
Just to confirm: this is also happening to me on a new installation of 6.3.3 with unchanged default config*.
Seeing the suggestions here I'm quite surprised that a default config apparently doesn't work for all widely used clients out of the box anymore? This might warrant a warning in the installation/set-up documentation.
Will test the fixes proposed here tomorrow.

* I successfully had 5.x running before but wiped the device.

**Comment by marefr** [comment]
@jdmaloney you've still not got the configuration right. You have a `[snapshots]` section before your cookie setting, please change config to this:

```ini
#################################### Security ####################################
[security]
# default admin user, created on startup
;admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
;admin_password = admin

# used for signing
;secret_key = ~Sensored, not sure if this is safe to paste publicly~

# Auto-login remember days
;login_remember_days = 7
;cookie_username = grafana_user
;cookie_remember_name = grafana_remember

# disable gravatar profile images
;disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port separated by spaces)
;data_source_proxy_whitelist =

cookie_secure = true
cookie_samesite = none

[snapshots]
# snapshot sharing options
;external_enabled = true
;external_snapshot_url = https://snapshots-origin.raintank.io
;external_snapshot_name = Publish to snapshot.raintank.io

# remove expired snapshot
;snapshot_remove_expired = true

# remove snapshots after 90 days
;snapshot_TTL_days = 90
```

**Comment by marefr** [comment]
@Argon- what browser and version are you using?

**Comment by Argon-** [comment]
Safari on iOS 12.4 was the problematic browser.

**Comment by jdmaloney** [comment]
@marefr That took care of it things are working fine now.  Sorry for that over-site on placement, was too rushed apparently when trying it out before I left for holiday that I missed that section heading.  All is working for me now with Safari.  

If it’s ok I’ll go ahead and close this issue, though I agree with @Argon since those two settings are now required to make Safari work with a very vanilla config of Grafana it’d be nice that they get changed to the default configuration of service out of the box in future releases.

**Comment by davidmccaffrey** [comment]
Unfortunately we are still having the problem here. We have made the changes in our environment, careful to set them in the [security] section, and restarted the service. But Mac users with Safari are still having the same failure.  All using Safari 12.1.2 (14607.3.9) with The Grafana v6.2.4 (ee01897) on Centos 7.6.1810
`#################################### Security ####################################
[security]
# default admin user, created on startup
;admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
;admin_password = admin

# used for signing
;secret_key = [sterile]

# Auto-login remember days
;login_remember_days = 7
;cookie_username = grafana_user
;cookie_remember_name = grafana_remember

# disable gravatar profile images
;disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port separated by spaces)
;data_source_proxy_whitelist =

# disable protection against brute force login attempts
;disable_brute_force_login_protection = false

cookie_secure = true
cookie_samesite = none

#################################### Snapshots ###########################
[snapshots]
# snapshot sharing options
;external_enabled = true
;external_snapshot_url = https://snapshots-origin.raintank.io
;external_snapshot_name = Publish to snapshot.raintank.io

# remove expired snapshot
;snapshot_remove_expired = true`

**Comment by marefr** [comment]
@davidmccaffrey please upgrade to at least Grafana v6.3.3 where the `cookie_samesite = none` is not setting any SameSite attribute on the cookie and by that don't make Safari render SameSite = Lax in cookie.

**Comment by marefr** [comment]
@Argon- 

> Seeing the suggestions here I'm quite surprised that a default config apparently doesn't work for all widely used clients out of the box anymore? This might warrant a warning in the installation/set-up documentation.

We want Grafana to be safe by default from a security perspective and unfortunately Safari has a bug and doesn't handle the cookie attribite SameSite=none according to spec. With that said, I'll add a note to the [v6.0 upgrade notes](https://grafana.com/docs/installation/upgrading/#upgrading-to-v6-0) regarding this.

**Comment by redm123** [comment]
I know I'm late to the party... but for the record, in case somebody else hits that, too.

Using Safari 12.1.2 and Grafana 6.7.3.

It's a nice hint that I should should use secure cookies, but unfortunately enabling HTTPS for a private domain is not really a useful option, nor necessary.
The only way (except switching the browser) to allow logging in again was to set `cookie_samesite = disabled`.

**Comment by nikolaev-rd** [comment]
For all, who find this issue: the same problem with Grafana 6.7.3 and Chrome 57.x-60.x
Updating Chrome to the latest version fix the problem.

**Comment by viktorkho** [comment]
The problem after some time on
Grafana v6.7.1 (ca6d08d5cb)
Chromium 80.0.3987.132
Firefox 68.6.0esr

```
cookie_secure = true
cookie_samesite = none
```

Still no solution.
