### ISSUE TITLE
QueryEditor - toggleEditorMode not a function

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#18704]
https://github.com/grafana/datadog-datasource/issues/73

**Comment by torkelo** [comment]
Not sure what could be the reason. 

We check if the QueryCtrl implements this function here:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/panel_editor/QueryEditorRow.tsx#L86

**Comment by shavonn** [comment]
Supposedly solved with https://github.com/grafana/grafana/pull/18705

**Comment by marefr** [comment]
@shavonn can you verify if fixed and then we can close this. Thanks

**Comment by shavonn** [comment]
Eldin confirmed fixed.
