### ISSUE TITLE
32 bits?

### ISSUE THREAD

**Issue by mortias** [grafana/grafana#1870]
Hello,

I'm new to grafana, so probably it's a stupid question, 
but why can't i find versions (rpm's) supporting 32 bits? 
.. 

tx

**Comment by torkelo** [comment]
The reason is time :) Trying to spend my time as best as possible and make packages for the most used platforms. 

you will have to build those yourself using the http://docs.grafana.org/project/building_from_source/

**Comment by mortias** [comment]
ok, but what makes it 64bits dependant? can we still run the 2.0 version on nginx and nodejs like in this ansible playbook ? https://github.com/bobrik/ansible-grafana

**Comment by torkelo** [comment]
nothing is 64bit dependant

**Comment by torkelo** [comment]
that playbook is not updated to Grafana 2.0

**Comment by mortias** [comment]
So why can"t i install the rpm then on a 32 bit vm..?


Verzonden vanaf mijn Samsung Galaxy smartphone.


-------- Oorspronkelijk bericht --------
Van: Torkel Ödegaard <notifications@github.com> 
Datum:28-04-2015  10:39  (GMT+01:00) 
Aan: grafana/grafana <grafana@noreply.github.com> 
Cc: Mortier Andries <mortier@telenet.be> 
Onderwerp: Re: [grafana] 32 bits? (#1870) 

nothing is 64bit dependant

**Comment by torkelo** [comment]
@mortias because it contains a compiled 64bit binary, and the package is marked 64bit
