### ISSUE TITLE
Mixed datasource: query inspector only shows result for datasource of first query

### ISSUE THREAD

**Issue by andig** [grafana/grafana#18712]
On 6.3.3, any queries for datasources other than the one of the first query, are not visible in the query inspector:

<img width="1280" alt="Screenshot 2019-08-25 at 13 30 32" src="https://user-images.githubusercontent.com/184815/63649337-98fa0c80-c73c-11e9-9bd3-655925435806.png">

**Comment by torkelo** [comment]
Yes, it's a problem with how the query inspector works and the mixed data source works. Query inspector basically can only interact and show one http request(and most datasources batch and send all in one http request). That is obviously not possible for a mixed datasource. 

We might have a better feature in the future that can show raw data and request & response for multiple different http requests
