### ISSUE TITLE
Table panel: Column header overrides are ignored

### ISSUE THREAD

**Issue by andig** [grafana/grafana#18711]
On 6.3.3. it is not possible to override column headers when using the table panel.

This query should show `Erzeugung` and `Bezug` as column headers:

<img width="1254" alt="Screenshot 2019-08-25 at 13 18 38" src="https://user-images.githubusercontent.com/184815/63649201-086efc80-c73b-11e9-94fc-f6ddd93ad516.png">

**Comment by torkelo** [comment]
Make sure you do not have any column style higher up (above) that also match. The first column style that match is used. The UI is pretty terrible here, you have to remove the rule above and re add it below

**Comment by andig** [comment]
> Make sure you do not have any column style higher up (above) that also match. 

The only other column is "Time", so that's not the case. Might be due to selection of "Timeseries to columns"? These "columns" should also match?

Please reopen.

**Comment by andig** [comment]
ping @torkelo cause is probably `Timeseries to columns` which are then disregarded. Reopen?
