### ISSUE TITLE
metricFindQuery does not get the type information

### ISSUE THREAD

**Issue by wernerdaehn** [grafana/grafana#18713]
We had a discussion in a datasource plugin and found that Grafana does not pass the metric type to the metricFindQuery() call.

If you want to create a timeseries query, what metrics do you expect to get back? Single measures like CPU_UTILIZATION.
If you want to create a table query, what elements do you want to choose from? Table names of course, like the table HISTORICAL_RESOURCE_CONSUMPTION with many measures in it.

So the metricFindQuery() would return different objects for timeseries and table, hence requires the information what kind of query the user performs.

Agreed?

**Comment by torkelo** [comment]
This is easy to add for every datasource and does not require any changes to Grafana or the plugin interfaces. The query editor knows what type the query is and can modify the query and options it send metricFindQuery

**Comment by wernerdaehn** [comment]
Well, I can't find the information in the metricFindQuery(). The query parameter is a single string and empty at start.
![image](https://user-images.githubusercontent.com/13607767/63649517-e6777900-c73e-11e9-8969-124c351cb1ec.png)


But I assume you suggest to modify the QueryCtrl object as it knows the current type value? Do you have some hints, e.g. using the SimpleJson datasource, what code segments need to be added?

Thanks in advance!

**Comment by wernerdaehn** [comment]
I believe I understand now what you are saying: In the QueryCtrl

    getOptions(query) {
      return this.datasource.metricFindQuery(query || '');
    }

change that to something like 

    getOptions(query) {
      return this.datasource.metricFindQuery({ "type": target.type, "searchstring": query || ''});
    }

Am I on the right track?

**Comment by torkelo** [comment]
Yes!
