### ISSUE TITLE
exporting explore view table data to spreadsheet doesn't work nicely

### ISSUE THREAD

**Issue by cstyan** [grafana/grafana#18718]
**What would you like to be added**:

a nice way to turn the table data into csv

**Why is this needed**:

copy and pasting the table data from the explore view into a google sheet doesn't paste with format nicely, you have to rearrange the values post pasting

cc @tomwilkie

**Comment by hutchiko** [comment]
This greatly reduces the usefulness of the explore view for ad-hoc analysis. 

The reason copy paste does now work is that most spreadsheets (including Excel and Google sheets) expect tables to be pasted in as HTML using the table primitives `<table> <td> <tr>` etc. The table views in Grafana do not use these. They are based solely on styled `<div>` elements. 

As a work around I suggest to my analysts to use a personal "workbook" Dashboard where they can create a Table visualization which does allow them to export to CVS.

**Comment by ivanahuckova** [comment]
This has been recently implemented in https://github.com/grafana/grafana/pull/32005 and https://github.com/grafana/grafana/pull/32161 and it is part of Grafana 7.5.0 release. So closing this issue.
