### ISSUE TITLE
Search text not visible in Firefox/IE when searching dashboards

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#1872]
When I search for dashboards in drop-down menu, I can't see the text that I input. Search is working though.
I notices that it doesn't work in Firefox version 37.0.1(haven't tried other versions) and IE11, but it is working in chrome 41.0.2272.76. 

![grafana-search](https://cloud.githubusercontent.com/assets/4689252/7313942/71ec3ed8-ea5f-11e4-9a1d-7fd469f6b20e.png)
Here I entered 'lo' and search is clearly working.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!

**Comment by taylordowns2000** [comment]
@torkelo , I'm so sorry for the random question, but my open-source project is having the exact same issue. Search text just isn't showing up (though it's there... invisible!) in Firefox. Can I ask how you fixed this? Thank you so much!

Taylor

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/commit/7064d871068a37863f6d4aed17bc0c9503b8260c

**Comment by taylordowns2000** [comment]
Thank you!
