### ISSUE TITLE
How to use grafana api to get metirc data points?

### ISSUE THREAD

**Issue by AnyuanLuo** [grafana/grafana#18720]
I am using grafana to show the data collected by prometheus , then I want to get the metrics processed by grafana. Is there a kind of api, it can return a json data which is a graph's datapoints.
For example, grafana shows a figure of CPU Percentage Utilization Rate, then I use a kind of api, it return me a json file:  {  timestamp1:0.002,  timestamp2:0.001,  timestamp3:0.0025 ....}

**Comment by dprokop** [comment]
Duplicate of https://github.com/grafana/grafana/issues/11989

**Comment by AnyuanLuo** [comment]
Thank you for your answer!
