### ISSUE TITLE
Show warning when InfluxDB returns partial data

### ISSUE THREAD

**Issue by Esity** [grafana/grafana#18725]
This is in reference to #7380
When InfluxDB hits its max-row-limit, it will add in "partial":true. Grafana should show a warning symbol on the dashboard in the corner so that users understand they are getting back partial data. Currently, the only way would be to look at the query inspector and look for the partial flag in the JSON

**Comment by Esity** [comment]
This is something we should prioritize and is a great first step for https://github.com/grafana/grafana/issues/18725

**Comment by mikeskali** [comment]
I think it should be a generic feature, not limited to InfluxDB. Additional backends (for instance m3db) can also return partial data.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by Esity** [comment]
This is not a feature request, I would say this is more on the tech debt/bug side. The user isn't informed that it is partial data so it makes both grafana and the data source look bad to the end user
@pkolyvas

**Comment by gabor** [comment]
@Esity does `max-row-limit` exist in influxdb2? i can see it exist in influxdb1 ( https://docs.influxdata.com/influxdb/v1.8/administration/config/#max-row-limit--0 ),

but there is no such config option in influxdb2 ( https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#configuration-options )

and when looking at the how-to-migrate-config-options-from-1-to-2 there is nothing offered ( https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/manual-upgrade/#migrate-custom-configuration-settings )  ( open the "view configuration option parity" thing, and in the list you can find `max-row-limit` with no influxdb2-equivalent setting offered)
