### ISSUE TITLE
Missing data points.  Clicking variable textbox in the dashboard settings shows data points.

### ISSUE THREAD

**Issue by cgs-admin** [grafana/grafana#18726]
![grafana-1](https://user-images.githubusercontent.com/49324777/63710536-3b25fd00-c7ee-11e9-85fd-704c7a8d7c10.png)

**What happened**:
Data points randomly don't show up.

**What you expected to happen**:
Data points to always show up.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know, just seems to happen randomly.

**Anything else we need to know?**:
Seems when I click the variable hostname input box or query input box the data points appear.

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus 2.11.2
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox 68.  Possibly a browser issue, will try chrome when the issue appears again.
- Grafana plugins: Boom Table 1.0.0, StatusMap 0.1.1
- Others:

**Comment by torkelo** [comment]
Can you open chrome dev tools and inspect the query requests and responses especially the request that is returning missing data, is there data missing in that response? record a video of what your describing?

**Comment by cgs-admin** [comment]
Once the issue shows again I will do what you ask.  It might be a few days or some weeks as I don’t live in Grafana.

Regards,


David Haggard

CG Systems, Inc.<http://www.californiaaccesscontrol.com/>

1470 N Hundley St. | Anaheim, CA 92806
Office: (714) 632-8882 | david.haggard@CGSystemsinc.com<mailto:david.haggard@CGSystemsinc.com>
California Gate<http://www.californiagate.com/> | California Camera Security<http://californiacamerasecurity.com/> | California Access Control<http://www.californiaaccesscontrol.com/>

Please help us efficiently help you by sending all service and warranty requests to service@CGSystemsinc.com<mailto:service@CGSystemsinc.com> so our CSR Team Members can immediately process your request. Thank You!

**Comment by hugohaggmark** [comment]
Closing this issue as it doesn't seem to be opened. We can always reopen this issue if the need should arise.
