### ISSUE TITLE
Incremental Backoff for Alerting

### ISSUE THREAD

**Issue by clarkent86** [grafana/grafana#18734]
**What would you like to be added**:
Right now we have the option to change the amount of retries we have when alerts fire. We would like to be able to configure an incremental backoff.

**Why is this needed**:
Our alerting pipelines are not always reliable. We had a customer this morning miss an alert due to a piece of our pipeline that Grafana triggers alerts to being temporarily unavailable. If we had an incremental backoff we could keep the load off of the pipeline from trying to retry too many times but also be able to retry reliably over time.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
