### ISSUE TITLE
Always show legend in single graph mode

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#1873]
Since 'row height' now works as it should, I had to disable legends on some of my graphs on dashboards, since they were too big. But I would like to always have a legend when I'm in single graph view mode, since there is no height limit.

What do you think?

Matej

**Comment by srodrig0209** [comment]
+1 :)

**Comment by torkelo** [comment]
you can toggle legend on/off using panel menu > hamburger > toggle legend
