### ISSUE TITLE
Query metrics from each environment variable

### ISSUE THREAD

**Issue by FizzyGalacticus** [grafana/grafana#18737]
I'm really hoping that I'm just an idiot and this feature already exists.

**What would you like to be added**:
The ability to create dynamic metric queries using possible values from environment variables.

**Why is this needed**:
I have several metrics in CloudWatch that share the exact same format, but with different names depending on the situation:
* `metric_one-success`
* `metric_two-success`
* ...etc

I also have each type of metric defined as options for a single environment variable.

When creating a line chart that displays an overall view of all of the different metric types, I currently have to manually add a metric query for each possible value, where it would be really handy to use a template that basically loops through each possible variable and create a metric query.

**Comment by torkelo** [comment]
The cloudwatch api does not support wildcards for muli valued metric name expressions. 

https://github.com/grafana/grafana/issues/17949

All other data sources support this so this and adding these query loops to the frontend seems like a bad solution to something that should be supported in the CloudWatch query api
