### ISSUE TITLE
159h vs 160h breaks override relative time in time range of table

### ISSUE THREAD

**Issue by CPL512** [grafana/grafana#18732]
This is on Grafana version 5.4.2, using Prometheus, and running on Red Hat

I have scrape data in Prometheus every hour around the 43 minute mark for the past around 5 days. I would like to display the hourly scrape events from the past week in a table. In the table, when I set the Override relative time option in Time range to 6 days, the table properly displays all my hourly data, since I only have 5 days of data. However, when I set the override to 7 days, it only shows me data from the first day, and not even all the data from that day.

I tried narrowing the override down, and found that the threshold is 159h vs 160h. When it's 159h, the table works as expected, but when it's 160h, suddenly the table breaks. Why does increasing the time range by 1 hour cause the table to break, especially considering no additional data is even being considered?

**Comment by torkelo** [comment]
I assume this is related to how Prometheus process queries. Can you show the prometheus raw requests (using query inspector). 

Might be related to step parameter. Another thing to consider is that a time range like 7d does not mean it will align time range on exact 00:00:00 days. It just means 7 days ago from now, so will include half of the first day etc.

**Comment by torkelo** [comment]
the query look ok, so might be a prometheus query processing issue
