### ISSUE TITLE
Have the option to try an alternative alert rule if the primary is unavailable

### ISSUE THREAD

**Issue by clarkent86** [grafana/grafana#18735]
**What would you like to be added**:
Sometimes a pipeline will be down and an alert will fail to send from Grafana. We'd like the ability for example to choose to post to a slack room instead and if the primary alert rule fails.

**Why is this needed**:
Realistically we'd like to rely on our primary alerting pipeline but it's unfortunately not always available due to any number of variables.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
