### ISSUE TITLE
Allow alerting on Datadog and New Relic metrics

### ISSUE THREAD

**Issue by tsully193** [grafana/grafana#18731]
**What would you like to be added**:
Right now we use Grafana as a single pane of glass unifying multiple tools we use in our environment. Being able to easily set thresholds and alert on these various tools directly from Grafana would be hugely beneficial. 

**Why is this needed**:
Right now only some of the datasources we use allow alerting providing us with an incomplete alerting platform. 

Thanks!

**Comment by daniellee** [comment]
This has been implemented for both Datadog and New Relic data sources.
