### ISSUE TITLE
Color picker cropped when side menu is out

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#1874]
If you have side menu 'on' and want to choose a metrics color via color picket, it gets cropped in half. If I disable side menu, it works OK.

It happens in Firefox and Chrome, but it works in IE11.

![grafana-colorpicker](https://cloud.githubusercontent.com/assets/4689252/7314162/e3abb600-ea61-11e4-8648-3a82a56cfc50.png)

**Comment by torkelo** [comment]
fixed in v5
