### ISSUE TITLE
Unit "Work Day"

### ISSUE THREAD

**Issue by Poil** [grafana/grafana#18741]
Hi,

**What would you like to be added**:

It would be nice to add a "work day unit"
By example 8h = 1 work day
5 work day = 1 week

**Why is this needed**:
This is useful for some reporting of work load (by example when getting stats from a project-manager or sonarqube ...)

Best regards,

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
