### ISSUE TITLE
Removal of dashboard results in alert errors

### ISSUE THREAD

**Issue by blade1989** [grafana/grafana#18742]
**What happened**:

We removed the dashboard of a server that was no longer in use, deleted. No errors, everything went fine. However, after reviewing the logs, they are filled with said removed server:

> t=2019-08-27T11:46:02+0200 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=250 name="server.fqdn.tld CPU > 90%" error="tsdb.HandleRequest() error Request failed status: 500 INTERNAL SERVER ERROR" changing state to=keep_state

**What you expected to happen**:

Deletion of the dashboard and its alerts. 

**How to reproduce it (as minimally and precisely as possible)**:

Remove server with CollectD, delete dashboard, review the grafana logs with entries about the said removed server.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.2.5
- Data source type & version: CollectD 5.9.0
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
@blade1989 do you have the same problem after restarting Grafana? Any Grafana server logs from the time of deleting the dashboard? Do you have a copy of the dashboard.json that was deleted? How did you delete things and in what order?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
