### ISSUE TITLE
Unique Panel ID's that allow updates to be reflected across dashboards

### ISSUE THREAD

**Issue by tsully193** [grafana/grafana#18748]
**What would you like to be added**:
Have panels have unique ID's across all dashboards allowing panels to be placed on multiple dashboards. This way any updates to a panel on one dashboard would be reflected on the other.

**Why is this needed**:
Currently if you copy a panel from one dashboard to another, you need to make any changes to the panel on both dashboards.

**Comment by dprokop** [comment]
Duplicate of https://github.com/grafana/grafana/issues/1803
