### ISSUE TITLE
Show number of visits on grafana dashboard for particular duration.

### ISSUE THREAD

**Issue by anrav** [grafana/grafana#18743]
**What would you like to be added**:
Request to show number of visits on grafana dashboard for particular duration.
Also add same information in Grafana internal metrics.
Please add based on users/Teams - Dashboard access count.
**Why is this needed**:
This gives which grafana dashboard(Page) is highly accessed.

**Comment by anrav** [comment]
This feature would help in following way

- Gives priority of dashboard to focus!

- In case of operations team, it helps which dashboards receiving more hits and confirms that information in the dashboard helping to troubleshoot or take actions and more useful info to those dashboard.

- It helps to optimize and build better dashboards for operations to use by understanding why dashboards are not used for less hit dashboards. Either it is not helping engineers to troubleshoot or dashboard are not loading well or other reasons.

- It really help to force metric driven culture by looking at who is using the dashboard most. Take appropriate training /actions to drive the culture.

**Comment by dprokop** [comment]
@anrav thanks for your contribution! I have labeled this issue with `awaiting-more-evidence` to see what is the community response around this feature request. We also plan to implement improvements to the internal analytics soon, so keep you eyes on our Github and [blog](https://grafana.com/blog/) for updates.

**Comment by anrav** [comment]
Thank you @dprokop .

**Comment by andrecp** [comment]
I would like to see this as well, is there anything at all to track page views by dashboard at the moment?

**Comment by vanugrah** [comment]
This would be awesome!!

**Comment by karishmasaikia** [comment]
I too want to see this. Points raised by @anrav are spot on! It would be great to focus on top viewing dashboards and also track users by dashboard usage.

**Comment by karishmasaikia** [comment]
@dprokop Hi, is there any possibility to make these changes soon?

**Comment by mihaitodor** [comment]
Any update on this? It would be awesome to have such metrics in the community version.

**Comment by joshianant34** [comment]
Is this feature available in the community version?
