### ISSUE TITLE
SQL Query Group By issue

### ISSUE THREAD

**Issue by bhagujava** [grafana/grafana#18744]
**What happened**:
pq: SQLParseException: 'ap_mac_address' must appear in the GROUP BY clause or be used in an aggregation function. Perhaps you grouped by an alias that clashes with a column in the relations

**What you expected to happen**:
It should execute the query and show the table

**How to reproduce it (as minimally and precisely as possible)**:
Connect PostgreSQL and create query with type table   

**Anything else we need to know?**:

![Screenshot from 2019-08-27 16-07-03](https://user-images.githubusercontent.com/25981184/63764594-cc779b00-c8e4-11e9-8766-013dd68cba03.png)

**Environment**:
- Grafana version: Latest docker
- Data source type & version: PostgreSQL 9.5+
- OS Grafana is installed on: Ubuntu 18.04 LTS
- User OS & Browser: Chrome latest
- Grafana plugins: PostgreSQL
- Others:

**Comment by dprokop** [comment]
@bhagujava could you please provide us with the query inspector result?

**Comment by bhagujava** [comment]
@dprokop dont know the reason but query get executed but data is not plotting into the table 



![Screenshot from 2019-08-27 18-59-56](https://user-images.githubusercontent.com/25981184/63775527-25532d80-c8fd-11e9-8e52-3c13d9939763.png)

**Comment by dprokop** [comment]
@bhagujava you need to change your visualization type to Table

**Comment by bhagujava** [comment]
Then i would not able to send alert

**Comment by bhagujava** [comment]
But somehow i am able to convert same query with chart but getting error while sending alert

````
t=2019-08-27T13:38:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=1 name="Connections alert" changing state to=no_data
t=2019-08-27T13:38:20+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=2 name="Node Health alert" error="tsdb.HandleRequest() response error &{Found no column named time  A 0xc0005d8100 [] []}" changing state to=alerting
````

And query is

````
SELECT  count(*) as counts , ap_mac_address, created_date as time FROM raystatistic.ray_node_health  where cpu_usage > 1 and created_date > (CURRENT_TIMESTAMP - 555555000) group by ap_mac_address,time

````

**Comment by dprokop** [comment]
Can you please take a look at this thread on our community site: https://community.grafana.com/t/postgres-timegroup-macro-returns-found-no-column-named-time/8050 ?

**Comment by bhagujava** [comment]
I did, It was double quote issue.
