### ISSUE TITLE
Graphite encountered an unexpected error while handling your request

### ISSUE THREAD

**Issue by blade1989** [grafana/grafana#18746]
**What happened**:
Unclear - the full errror:

`t=2019-08-27T11:56:02+0200 lvl=info msg="Request failed" logger=tsdb.graphite status="500 INTERNAL SERVER ERROR" body="<body style=\"background-color: #666666; color: black;\">\n<center>\n<h2 style='font-family: \"Arial\"'>\n<p>Graphite encountered an unexpected error while handling your request.</p>\n<p>Please contact your site administrator if the problem persists.</p>\n</h2>\n<br/>\n<div style=\"width: 50%; text-align: center; font-family: monospace; background-color: black; font-weight: bold; color: #ff4422;\">\n\n</div>\n\n<div style=\"width: 70%; text-align: left; background-color: black; color: #44ff22; border: thin solid gray;\">\n<pre>\nTraceback (most recent call last):\n  File &quot;/usr/lib/python2.7/dist-packages/django/core/handlers/base.py&quot;, line 132, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File &quot;/usr/lib/python2.7/dist-packages/graphite/render/views.py&quot;, line 56, in renderView\n    (graphOptions, requestOptions) = parseOptions(request)\n  File &quot;/usr/lib/python2.7/dist-packages/graphite/render/views.py&quot;, line 312, in parseOptions\n    untilTime = parseATTime(queryParams[&#39;until&#39;], tzinfo, now)\n  File &quot;/usr/lib/python2.7/dist-packages/graphite/render/attime.py&quot;, line 48, in parseATTime\n    return tzinfo.normalize(parseTimeReference(ref).astimezone(tzinfo) + parseTimeOffset(offset))\n  File &quot;/usr/lib/python2.7/dist-packages/graphite/render/attime.py&quot;, line 121, in parseTimeReference\n    raise Exception, &quot;Unknown day reference&quot;\nException: Unknown day reference\n\n</pre>\n</div>\n\n</center>\n"
`

The Python error looked like this:

> 	Traceback (most recent call last):
> 	  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
> 	    response 
> = wrapped_callback(request, *callback_args, **callback_kwargs)
> 	  File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 56, in renderView
> 	    (graphOptions, requestOptions) 
> = parseOptions(request)
> 	  File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 312, in parseOptions
> 	    untilTime 
> = parseATTime(queryParams[&#39;until&#39;], tzinfo, now)
> 	  File "/usr/lib/python2.7/dist-packages/graphite/render/attime.py", line 48, in parseATTime
> 	    return tzinfo.normalize(parseTimeReference(ref).astimezone(tzinfo) + parseTimeOffset(offset))
> 	  File "/usr/lib/python2.7/dist-packages/graphite/render/attime.py", line 121, in parseTimeReference
> 	    raise Exception, "Unknown day reference"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v6.2.5
- Data source type & version:
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
This seems like a potential problem with Graphite, ref https://github.com/graphite-project/graphite-web/issues/263

Can you provide us with more information, like Graphite version, the request u sent etc?

**Comment by xlson** [comment]
Closing this due to a lack of details.
