### ISSUE TITLE
Issues grafana alerting when there are no data points

### ISSUE THREAD

**Issue by msoni2805** [grafana/grafana#18758]
I am trying to set up an alert that will get triggered when there are no data points, for example in cases where the system goes down and stops sending metrics.

![image](https://user-images.githubusercontent.com/54628259/63855475-1cc22c00-c9bd-11e9-8191-aa04432da8ed.png)

I expect the alert to get triggered when there are no data points but it doesn't seem to be getting triggered.

![image](https://user-images.githubusercontent.com/54628259/63855527-3bc0be00-c9bd-11e9-8159-2168dedde53b.png)

As I am using slack as a notification channel in grafana v6.3.3 and data source MySQL
As this issue was faced on the previous version can any help me out on this

Why can't alert triggered on slack while we don't have any data on the graph after 5 minutes?

This is a really serious issue I am facing and needs to resolve. 

May i know is this kind of issue is a bug or not?

I expect the alert to get triggered when there are no data points but it doesn't seem to be getting triggered.

**Comment by torkelo** [comment]
* CAn you run the test rule button? and check the result? 
* What version of Grafana are you running?

**Comment by msoni2805** [comment]
@torkelo thanks for your revert
I will share an attachment for state history.

[logs_alerts.txt](https://github.com/grafana/grafana/files/3555069/logs_alerts.txt)

First will tell you the proper scenario what I am doing.
As previously mentioned I am using Grafana latest version v6.3.3 and the data source which is been used is MySQL and for the notification, channel using slack webhook.
The graph which is been plot it is using the table data as I have configured
Duplicate of #d the alerts for rest of the graph panel I received the alert as per the threshold for every 3 mins but for another graph panel since 5mins there is no data inserted on the table and on the graph it is showing "DATA POINTS OUTSIDE TIME RANGE"

![image](https://user-images.githubusercontent.com/54628259/63932449-d203eb00-ca74-11e9-9d1f-d650e9121905.png)

Also on the Alert section for NO Data & Error Handling, I have set the state to "Alerting" if no data or all values are null it is not triggered to send the notification on the slack channel.
Hope you understand my scenario please help me on this

**Comment by msoni2805** [comment]
@torkelo 

You can relate this issue https://github.com/grafana/grafana/issues/17780

In simple words, when there is no data in the response from database, Grafana sets a grey line in graph and don`t receive any kind of notification on slack  with subject [No Data] ..... and a graph., I want a notification on slack where if there is NO DATA or all values are null also when the response does have data again I need notification on a slack back with [OK].

**Comment by msoni2805** [comment]
Hi Team,

What is the status really need help and it would be grateful to solve this issue.

**Comment by marefr** [comment]
What does your queries look like, can you include a screenshot?

**Comment by msoni2805** [comment]
I have already provided on the above comments. Could please check and let me know is it available to you or not if not then too also I m sending you back again 

![image](https://user-images.githubusercontent.com/54628259/64024923-1f598880-cb59-11e9-9c11-52fb058eea61.png)

**Comment by flopp999** [comment]
> I have already provided on the above comments. Could please check and let me know is it available to you or not if not then too also I m sending you back again
> 
> ![image](https://user-images.githubusercontent.com/54628259/64024923-1f598880-cb59-11e9-9c11-52fb058eea61.png)

The query is not in the above text.

**Comment by msoni2805** [comment]
@flopp999 
which query are you talking about ??

**Comment by flopp999** [comment]
> @flopp999
> which query are you talking about ??

What is there query that you use when it doesn't work?

**Comment by msoni2805** [comment]
@flopp999 
SELECT
  $__timeGroupAlias(Timestamp,1s),
  CPU,hostname  
FROM total_cpu_mem_apps
where hostname like 'HODOR'
GROUP BY 1
ORDER BY 1 ASC;

this is the above query I am using

**Comment by msoni2805** [comment]
Hi,

Anyone can help me out appreciate your efforts.

**Comment by marefr** [comment]
@msoni2805 you need/should filter by time using `$__timeFilter(Timestamp)` in the where clause. Closing this since it looks like a user error/problem. Will consider reopen if that's a wrong conception.

**Comment by msoni2805** [comment]
@marefr 
what kind of filtration do I need to do could you please help it out as I am not using $__timeFilter(Timestamp) in where clause

**Comment by marefr** [comment]
`where $__timeFilter(Timestamp) AND hostname like 'HODOR'`

**Comment by marefr** [comment]
How often are the metrics written. I'm asking since you're using `1s` as interval and only group by time. Could you include result of `SELECT * FROM total_cpu_mem_apps WHERE hostname like 'HODOR' ORDER BY Timestamp DESC LIMIT 10`?
