### ISSUE TITLE
cloudwatch  me-south-1 region -->403

### ISSUE THREAD

**Issue by clhlc** [grafana/grafana#18755]
**What happened**:

I use grafana latest vesion; and I add cloudwach source.
but on me-south-1 region ,I meet 403 ,other regions is ok.

![image](https://user-images.githubusercontent.com/10704095/63837453-17111a00-c9ae-11e9-824b-aaeb6c726ff1.png)

me-south-1:
![image](https://user-images.githubusercontent.com/10704095/63837514-3445e880-c9ae-11e9-8eaa-a7905b70937c.png)

grafana log:

message:"InvalidClientTokenId: The security token included in the request is invalid status code: 403, request id: 692704e6-a73a-46d6-9d6a-8d8bec87789a"

**What you expected to happen**:
like others regions List source

**Environment**:
- Grafana version: 
6.3.3

- Data source type & version:
 cloudwatch in grafana

- OS Grafana is installed on: 
grafana in docker base on ubuntu 14.04

- User OS & Browser: 
chrome

**Comment by torkelo** [comment]
Any errors in the Grafana server log?

**Comment by clhlc** [comment]
@torkelo 

```shell
lvl=eror msg="Metric request error" logger=context userId=125 orgId=1 uname=test error="Failed to call cloudwatch:ListMetrics, InvalidClientTokenId: The security token included in the request is invalid\n\tstatus code: 403, request id: e40e1a01-d32f-4a82-b56f-48930b2abe93"

lvl=eror msg="Request Completed" logger=context userId=125 orgId=1 uname=test method=POST path=/api/tsdb/query status=500 remote_addr=172.16.1.149 time_ms=266 size=34 
```

some  infomations:

1. grafana in k8s cluster
2. use kube2iam  get iam role

**Comment by torkelo** [comment]
Closing this as it looks like it's a cloudwatch api issue not a grafana bug
