### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by roszie** [grafana/grafana#18754]
**What happened**:
set up SMTP for sending alert to email
And alert window shown 'The datasource does not support alerting queries'

**What you expected to happen**:
I try to send test, but it cannot do.

**Anything else we need to know?**:
My data source is Bigquery

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Bigquery v.1.0.1
- OS Grafana is installed on: Compute engine
- Grafana plugins: Bigquery

**Comment by torkelo** [comment]
Big query data sources does not support alerting, only data sources that are implemented as backend plugins do that
