### ISSUE TITLE
feature request: Change title size

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#1875]
Would it be possible to change the Title font size on a graph or Singlestat?

**Comment by torkelo** [comment]
Can you describe the reason scenario? I guess you want to increase the font size?

**Comment by agaon** [comment]
Exactly, we display our grafana dashboards on our wallboard (6x2 50' screens) and changing the font size of the title would really help to make the graphs more easy to read and understand..

**Comment by djnym** [comment]
I'd second this for the same reason, increasing the font size for a single stat would be awesome.  Also, I think that the font size increase for text panels with text mode is broken as well in that it doesn't set the size as far as I can tell.

**Comment by torkelo** [comment]
You can change the font size for single stats panels

**Comment by kentsurrey** [comment]
Are there any plans to add this feature on graphs as well? We have the same scenario as agaon described where the titles and numbers on the axes are really hard to read from most places in our office.

Thank you for creating this project by the way, it's been great for getting everyone in our company to look at our key metrics.

**Comment by huhongbo** [comment]
+1 want to change the panel text title font size

**Comment by yagilm** [comment]
+1 being able to change the title font size

**Comment by trahma** [comment]
+1 more, anyone that has a group of tvs gets hindered by not being able to change the title size.  We're using grafana a multiple packs of monitors (6x2 and 5x2) and this has been the biggest grafana complaint.

**Comment by the-real-PaGeY** [comment]
+ ME ME ME ME, only reason we want it is for large screen ops monitoring, no font adjust-ability is a deal breaker

**Comment by jrbeilke** [comment]
+1 - we've hacked in a text panel with CSS to font size of the row/panel titles for now but would be nice to adjust this within Grafana per item

**Comment by rahulghanate** [comment]
A good to have to use the space consumed by them

**Comment by cruiser607** [comment]
+1 want to change the panel text title font size

**Comment by leesimmonsflying** [comment]
+1 using a 4k screen to monitor and the graph titles are too small to read even from a couple of meters away.

**Comment by qmex-mp** [comment]
+1 To be readable from a few meters

**Comment by edsrj** [comment]
+1!

**Comment by ninagittle** [comment]
+1 Change **Title** font size on singlestat/graph

**Comment by elenigen** [comment]
+1

**Comment by anisimovsergey** [comment]
+1

**Comment by yangshenhuai** [comment]
+1

**Comment by Poil** [comment]
+1

**Comment by dcrawkstar** [comment]
+1

**Comment by giner** [comment]
+1

**Comment by Riccardo192** [comment]
+1

**Comment by Eloo** [comment]
+1

**Comment by critikaster** [comment]
+1

**Comment by irateadmin** [comment]
+1

**Comment by Yaiba782** [comment]
+1

**Comment by kegfru** [comment]
+1

**Comment by ShironB** [comment]
+1

**Comment by sindrej** [comment]
+1

**Comment by sacasumo** [comment]
+1

**Comment by frennkie** [comment]
Is this on the Roadmap? We would really liked to  have this possiblity.

**Comment by daniellee** [comment]
@frennkie see answer here: https://github.com/grafana/grafana/pull/8681#issuecomment-310209121

**Comment by not24get** [comment]
+1

**Comment by funrockadmin** [comment]
+1

**Comment by tibbing** [comment]
+1

**Comment by andreloc** [comment]
+1

**Comment by silvarafael** [comment]
+1

**Comment by anmiles** [comment]
+1

**Comment by mikich** [comment]
Here is my solution;
1) Add at the bottom of the dashboard "text panel" in a smallest hight "1px" and turn on a transparent background. 
2) Open the Options tab and switch to a HTML mode
3) Paste next CSS code:
```
<style>
.panel-title-container {
    font-size: **x-large**;
}
</style>
```
font-size value could be: medium|xx-small|x-small|small|large|x-large|xx-large|smaller|larger|length|initial|inherit;

**Comment by anmiles** [comment]
@mikich Thank you a lot! Working like a charm.
Moreover we can specify any CSS value, for example font-size: 1.5em was enough for my board.

**Comment by plittlefield** [comment]
Thanks! You star!

**Comment by alanwds** [comment]
+1

**Comment by iliyarYi** [comment]
+1

**Comment by blacar** [comment]
+1

**Comment by sherif84** [comment]
+1

**Comment by adamzoltan** [comment]
+1

**Comment by IstvanPeter** [comment]
+1

**Comment by etlweather** [comment]
Following @mikich idea, if you don't want to blow up the panel's menu, and only change the title text:

```
<style>
.panel-title-text {
 font-size: large;
}
</style>
```

**Comment by Hbroering** [comment]
@etlweather thanks! 
The only thing that is not perfect yet is that if you change the title size the whole panel changes size:
![image](https://user-images.githubusercontent.com/38422102/42439962-967e8926-8364-11e8-8f14-f45ce8dc91a1.png)

Did anyone come across a solution for this?

**Comment by Etelereth** [comment]
@Hbroering  
My solution:

`<style>`
`.panel-title-text {`
 `font-size: 40px;`
`}`
`.panel-container {`
`  height: 100%;`
`}`
`</style>`

**Comment by sglajchEG** [comment]
I added even more code to get the title, data label and axis labels all bigger in [this post](https://github.com/grafana/grafana/issues/12227#issuecomment-444982123) in case it helps someone

**Comment by svet-b** [comment]
FYI since Grafana v6.0 the text panel workaround doesn't work out of the box, due to HTML sanitization. Check https://github.com/grafana/grafana/blob/v6.0.0/CHANGELOG.md#breaking-changes-1 for info on the config change required to enable this.

**Comment by gustonator** [comment]
the font size really drive me nuts. please, put back the one from grafana 6.
![font-size](https://user-images.githubusercontent.com/43645090/84594562-7663ec00-ae53-11ea-9960-9af345e8975b.gif)

**Comment by faxm0dem** [comment]
I'd like to change the font of the annotation output.
The reason for this is simple : we have an annotation that displays the output of the `top` command, and columns are misaligned due to the proportional font

**Comment by faxm0dem** [comment]
> I'd like to change the font of the annotation output. The reason for this is simple : we have an annotation that displays the output of the `top` command, and columns are misaligned due to the proportional font

FTR this is possible as the contents of the field is interpreted as html.
I added a `<pre>` tag to the data and now it displays correctly.

**Comment by kinzhi** [comment]
I made this modification in the grafana 9.x version and it worked:
1.Add at the bottom of the dashboard "text panel" and turn on a transparent background.
2.Open the Options tab and switch to a HTML mode
3.Paste next CSS code:
`<style>
.panel-title h2{
font-size: 1.5rem;
}
</style>`

**Comment by Rudorufu-san** [comment]
This work for me. Grafana 9
**"I stand on the shoulders of titans. Thanks guys!"**
1.Modify the grafana configuration file (grafana.ini)
uncomment (delete ";")

>                                  [panels]
>                                  disable_sanitize_html = true

2.Add at the bottom of the dashboard "text panel" and turn on a transparent background.
3.Open the Options tab and switch to a HTML mode
4.Paste next CSS code:
```
<style>
.panel-title h2{
font-size: 50px;
font-weight: 700;
}
.panel-title {
height: 60px;
line-height: 60px;
}
</style>
```

**Comment by ryantxu** [comment]
the stat panel allows explicit sizing now (see size options).  Changing the panel wrapper title size via css may work, but also likely to make many things look bad

**Comment by cdaringe** [comment]
The above claims are true for the `stat` panel. My use case is `timeseries` panels, which still do not allow customizations 1st-class.

In the latest grafana (11.x?), class names are now prefixed with random chars. Here's an updated CSS snippet for a text panel `<style />` block:

```css
div[class$="panel-title"] h2{
  font-size: 50px;
  font-weight: 700;
}
div [class$="panel-title"] {
  height: 60px;
  line-height: 60px;
}
```

Obviously, adjust to your liking.
