### ISSUE TITLE
can not install front end dependency 

### ISSUE THREAD

**Issue by dongwangdw** [grafana/grafana#18760]
When I try to build from source, installing front end dependency as readme states, ```yarn install--pure-lockfile```. 

https://github.com/SemkoDev/field.cli/issues/2
This option is not available for yarn and actually yarn does not have install option.
So I wonder how will i install this front end deps? Or if I missed anything?

**Comment by torkelo** [comment]
strange, what version of yarn do you have?

this option is there in latest yarn docs at least, https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-pure-lockfile 

and works when I try to run this

**Comment by dongwangdw** [comment]
No. After more investigation, I think the doc should be improved.
There is another yarn in cmdtest package in ubuntu version above 16.x, which is different from the yarn used in grafana.

So you can not install yarn in OS above 16.x. some more work needs to be done. 
And the nodejs version accordingly should be at least 10.x.
https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

**Comment by torkelo** [comment]
The dependency on node LTS version should already be in the readme dev guide and docs building from source guide

**Comment by dheeruymv** [comment]
Yes @dongwangdw : This is bit confusing, i have ended up installing different yarn which is in ubuntu and even i got the same error "Unsupported option name".

dheeraj@P:~/dheeraj_workdir/grafana/grafana$ yarn install --pure-lockfile
Unknown Syntax Error: Unsupported option name ("--pure-lockfile").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]


@torkelo : May be, there is need to improve docs, can you please give a thought over this?

Thanks.
