### ISSUE TITLE
Time range variable $__from and $__to should report epoch time as seconds instead of milliseconds

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#18763]
Currently epoch time is shown as millisecond  resulting a mismatch when panel links are used to launch other tools which mandate time range as seconds or seconds.milliseconds format. (1566971076499 --> 1566971076.499 or 1566971076, 'Wed Aug 28 08:44:36 2019' )

My understanding is that "standard" use seconds and optional decimal milliseconds depending on representation.

Due mismatch custom redirecting converting proxy would be required to divide epoch values with 1000

Extract from documentation
Time range variables
Grafana has two built in time range variables in $__from and $__to. They are currently always interpolated as epoch milliseconds. These variables are only available in Grafana v6.0 and above.

Possible options:
- change to $__from and $__to from milliseconds to second.millisecond decimal format, would still represent milliseconds
- change $__from and $__to seconds and add $__from_ms and $__to_ms to provide millisecond granularity
- keep $__from and $__to as milliseconds and add seconds representation $__from_s and $__to_s

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows and Linux
- User OS & Browser: Chrome

**Comment by retzkek** [comment]
I'd definitely like to see other time formats supported for the range variables, ISO8601 being another important one. Maybe [variable format options](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/) could be used for that? Otherwise a standard naming scheme like `$__from_{format}` sounds reasonable for me, e.g. `$__from_s`, `$__from_iso`, etc.

**Comment by retzkek** [comment]
I think this can be closed now, what do you say @jtorkkel

**Comment by jtorkkel** [comment]
yes, [26466](https://github.com/grafana/grafana/pull/26466) fix it
