### ISSUE TITLE
Improve OpenTSDB query to series matching using new OpenTSDB 2.2 show_query feature

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#1876]
When you use pipe to specify more than one possible value for tags in openTSDB backend, the Alias feature breaks. It seens grafana is no longe able to match queries with it's results.

For example, you add a tag "host"  = "host1|host2". This will result in 2 timeseries, but the Alias you specify will not be applied. It does work when using a single value or *

**Comment by torkelo** [comment]
What's the response from OpenTSDB when using a pipe? that could be the problem

**Comment by vitorboschi** [comment]
The response is exactly the same as when you use *, except that instead of providing time series for all possible tag values, it only provides series matching the values you specified.

Example (captured from Grafana with Chrome developer tools):
Query: http://pastebin.com/FGrFc6hM
Response: http://pastebin.com/ABdHUhN0

**Comment by vitorboschi** [comment]
I guess the problem is that Grafana don't know how to interpret the pipe, so it thinks "host1|host2" is a single value, so no timeseries matches with the request

**Comment by torkelo** [comment]
yea, OpenTSDB does not give any way for matching query to returned series, think there is an open issue for that with OpenTSB

**Comment by torkelo** [comment]
Seems like OpenTSDB just implemented the feature that is needed to solve this, https://github.com/OpenTSDB/opentsdb/issues/438,

**Comment by hkousha** [comment]
Is there an estimate on when this issue will be resolved?

**Comment by torkelo** [comment]
well OpenTSDB 2.2 is now in RC1 so this could be fixed anytime.

**Comment by utkarshcmu** [comment]
PR #3243 submitted for this issue.

**Comment by utkarshcmu** [comment]
We need to wait more now to get this issue fixed. Unit Opentsdb 2.3.x is released.
Mentioned in the following Issue:
https://github.com/OpenTSDB/opentsdb/issues/646

**Comment by IzakMarais** [comment]
Also waiting for this fix.

**Comment by utkarshcmu** [comment]
Asked for a release candidate so that we can make change in Grafana https://github.com/OpenTSDB/opentsdb/issues/680 :)

**Comment by amalshah** [comment]
Is there any update on this?

**Comment by torkelo** [comment]
Has it been implemented in OpenTSDB yet

**Comment by utkarshcmu** [comment]
Show_query feature has been implemented in opentsdb's next branch which hasn't released yet. So, still waiting for 2.3.0RC1 which will come out of Opentsdb's next branch.

**Comment by utkarshcmu** [comment]
Now that 2.3 RC1 is released, we can fix this issue. PR will be on its way ASAP. :)

**Comment by utkarshcmu** [comment]
I am not sure whether this should make to 3.0.0 or not, that depends on @torkelo . But this bug has existed since more than a year now. If merging #4910 is not a big code change, then this prolonged issue can be resolved. :)

**Comment by amalshah** [comment]
Did this change make it into 3.0.0? Would appreciate if it can be merged in.

**Comment by utkarshcmu** [comment]
No
