### ISSUE TITLE
MS SQL macro parsing should allow functions as arguments

### ISSUE THREAD

**Issue by TobbenTM** [grafana/grafana#18765]
**What would you like to be added**:

Ability for the MS SQL macro parsing to correctly parse functions or complex queries.

As seen in the source:
https://github.com/grafana/grafana/blob/a0bb01103eebfa7e0d94201db5536b295c4f4529/pkg/tsdb/mssql/macros.go#L33

The current implementation will fail when given a function. Example:
```sql
SELECT 
  $__timeGroup(DATEADD(second, DATEDIFF(second, GETDATE(), GETUTCDATE()), Date)), '10m', 0) AS time
FROM Log
```

With the current implementation, the parser would send "`DATEDIFF(second`" as the second argument to the query evaluator, which isn't a valid interval (expecting '10m').

Preferably this macro parser would take scope into account.

**Why is this needed**:

Because there is no other way I see to enable the timeseries fill without using a macro with fill value. Very often we need to convert from local TZ to UTC, and by not being able to do it inside the macro, we need to complicate all queries with an inner select. See example above.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
