### ISSUE TITLE
Explore: error message/hint when switching to Prometheus

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#18769]
**What happened**:
Switched to Prometheus in Explore by selecting in the data source selector and got the following error before I started typing a query:

![image](https://user-images.githubusercontent.com/434655/63925751-f4810e80-ca4a-11e9-90f1-646e3e97ef97.png)

**What you expected to happen**:

Not to have any errors before I start typing a query. I haven't chosen a counter yet so this hint/error message doesn't make sense.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Explore
2. Switch to a Prometheus data source in the data source dropdown

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest master
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 16.04 and Chrome/Firefox
- Grafana plugins:
- Others:

**Comment by davkal** [comment]
No longer an issue
