### ISSUE TITLE
Explore: query field hints are not cleared

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#18779]
0. Explore with prometheus
1. Run a query that shows a query hint (usually a metric ending in `_total`)
2. Click Clear All in the toolbar

Result: query is cleared, but the hint it not disappearing.

![Screenshot 2019-08-29 at 12 52 37](https://user-images.githubusercontent.com/859729/63939476-ae867380-ca67-11e9-8e56-11539fe2292b.png)

**Comment by torkelo** [comment]
Looks to be related to logic here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/components/PromQueryField.tsx#L157 

But could also be a side effect of how queryResponse updates are sent

**Comment by hugohaggmark** [comment]
I can repro this exact behaviour running `docker run -d -p 3003:3000 grafana/grafana:6.3.0` so this seems to have been in master for a while.

**Comment by hugohaggmark** [comment]
Can't repro this any longer on master, closing issue for now
