### ISSUE TITLE
Graph panel is not hiding values with zeros (Prometheus)

### ISSUE THREAD

**Issue by xpuska513** [grafana/grafana#18776]
**What happened**: When enabling "Hide with only zeros" in legend options it's not hiding the values with zeros

**What you expected to happen**: The values in vector with 0 will be hidden after enabling the option

**How to reproduce it (as minimally and precisely as possible)**: Create new dashboard, add graph panel, use any metric where a 0 value appears and enable "Hide with only zeros" option in Legend configuration of Visualization

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6 and  6.2.5
- Data source type & version: Prometheus 2.12.0
- OS Grafana is installed on: official grafana docker image running in Istio
- User OS & Browser: Windows 10 1903 & Google Chrome 76.0.3809.132
- Grafana plugins: -
- Others: -

**Comment by dprokop** [comment]
@xpuska513 thanks for reporting this. Unfortunately, I wasn't able to reproduce described issue. Can you please share your query response with us?

Also, please note that `Hide with only zeros` setting applies to the Legend, and only to the series which has **all** of the values equal 0.

**Comment by dprokop** [comment]
Closing due to the lack of response.
