### ISSUE TITLE
Explore: ElapsedTime doesn't work for Prometheus

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#18777]
While converting epics to thunks and using PanelQueryState in Explore all Prometheus request now run through the "Streaming path" and so `latency` is set to 0 [here](https://github.com/grafana/grafana/blob/6402391638d2dedb3be24e38f5ebb1e389124621/public/app/features/explore/state/actions.ts#L542). 

We should use `request.endTime - request.startTime` instead

**Comment by davkal** [comment]
Related: #18778

**Comment by ivanahuckova** [comment]
@davkal This issue has been solved. Timer for query latency is not shown until a query has run. And  after running query, it shows actual query latency. 

![image](https://user-images.githubusercontent.com/30407135/64330976-44734e80-cfd2-11e9-8a39-1238ffb36b79.png)
![image](https://user-images.githubusercontent.com/30407135/64331066-6bca1b80-cfd2-11e9-9d48-f01c60721a6e.png)

**Comment by davkal** [comment]
Fixed in #18791
