### ISSUE TITLE
Explore: Loading indicators keeps showing after query returned

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#18773]
0. Explore with Prometheus
1. Issue a query
2. See the line indicator flash across and the run button spins, then the graph gets drawn.

Result: The indicators does not go away, even though all requests have returned.

![Screenshot 2019-08-29 at 12 52 14](https://user-images.githubusercontent.com/859729/63935799-87777400-ca5e-11e9-89eb-caa6b0e8ce08.png)
![Screenshot 2019-08-29 at 12 52 37](https://user-images.githubusercontent.com/859729/63935809-8e05eb80-ca5e-11e9-8cd2-c4b45cd6959b.png)

**Comment by torkelo** [comment]
this should be fixed after the query processing PR was merged
