### ISSUE TITLE
Bar Gauge: do not display rows if there is no data

### ISSUE THREAD

**Issue by pitr** [grafana/grafana#18785]
**What happened**:
For stats that have no data points, Bar Gauge shows full bar. Even using "Last (not null)" reducer (introduced in #17911) doesn't change it:

![Screen Shot 2019-08-29 at 15 13 03](https://user-images.githubusercontent.com/102791/63943249-87cc3b00-ca6f-11e9-9423-006fe2a03d9b.png)

**What you expected to happen**:
Stats that have no data points should either be set to 0 (?) or, better, not be present in the graph.

**How to reproduce it (as minimally and precisely as possible)**:
1. Graph something that once existed that no longer exists (eg. CPU usage of servers which have been shut down)
2. Use Bar Gauge visualization, grouping by server, with Calc set to "Last (not null)"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: kairosdb
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS/Chrome
- Grafana plugins: -
- Others:

**Comment by torkelo** [comment]
Is there no way to filter them out in the query? 

But yea, I agree. Should be a way to hide null values.

**Comment by ryantxu** [comment]
FieldConfig has `nullValueMode`:
```
export enum NullValueMode {
  Null = 'null',
  Ignore = 'connected',
  AsZero = 'null as zero',
}
```

Perhaps we should expose that in the UI and if it is set as `Ignore` and the value is null, then skip the item?

**Comment by torkelo** [comment]
Fixed by filter transform
