### ISSUE TITLE
support DATABASE_URL env variable

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#1878]
To help grafana more easily be deployed in services like Heroku, support the DATABASE_URL env variable.

Example:
DATABASE_URL=postgres://db_user:db_pass@hostname:35054/database_name

This env variable is commonly used.

**Comment by torkelo** [comment]
ok, interesting. Can you not specify another ENV variable for the database? Does it have to be DATABASE_URL? Because all config options in grafana can be specified using ENV vars.

**Comment by blysik** [comment]
Unfortunately the way Heroku works, is those variable names (DATABASE_URL for example) are pre-set.

What I've done is created a script that I source before starting grafana-server.  This is a decent work around.

Essentially my Procfile looks like this:

web: source env_vars.sh && bin/grafana-server

In that bash script I use a regex to parse DATABASE_URL, and set the individual grafana env vars:

regex="^postgres://([a-zA-Z_-]*):([a-zA-Z]*)@([a-z\-]*):([[:digit:]]*)/([a-zA-Z_-]*)$"
[[ $DATABASE_URL =~ $regex ]]
export GF_DATABASE_HOST=${BASH_REMATCH[3]}:${BASH_REMATCH[4]}
export GF_DATABASE_NAME=${BASH_REMATCH[5]}
export GF_DATABASE_USER=${BASH_REMATCH[1]}
export GF_DATABASE_PASSWORD=${BASH_REMATCH[2]}

This approach is working.

**Comment by torkelo** [comment]
ok, I see, maybe a config option to use DATABASE_URL

**Comment by torkelo** [comment]
Adding this script to docs for running on heroku would be enough.

**Comment by adamlwgriffiths** [comment]
Just a comment regarding the regular expression above incase anyone else tries to use it.

The regular expression you posted is not correct, each option `[...]` needs to be followed with a `+`.
The captures can also be simplified by just matching to the first unwanted character.
Ie capture until the next `:` is `([^:]+):`.

`^postgres://([^:]+):([^@]+)@([^:]+):([^/]+)/(.*)$`
