### ISSUE TITLE
Docker image grafana/grafana:latest is broken on Arm

### ISSUE THREAD

**Issue by toastedcornflakes** [grafana/grafana#18798]
**What happened**: I had an image based on `grafana/grafana:latest` that worked, from a few days ago. I just rebuilt my image that does `FROM: grafana/grafana:latest`. 

docker logs shows `standard_init_linux.go:211: exec user process caused "exec format error"`.

**How to reproduce it (as minimally and precisely as possible)**: On a raspberry pi with Raspbian 9 (stretch), `docker run -it grafana/grafana:latest`

**Anything else we need to know?**: Probably linked to #18792

**Environment**:
- Grafana version: The image was updated on August 29, 2019 11:43 AM according to [this](https://hub.docker.com/r/grafana/grafana/tags)

**Comment by mikea** [comment]
just a note that `docker run -it grafana/grafana:6.3.4` continues to work.

**Comment by marefr** [comment]
Thanks for reporting. We need to investigate why this is. 

If you try and base your image on grafana/grafana-arm32v7-linux:latest, does that work? As @mikea suggests base your image on grafana/grafana:6.3.4, does that work?

**Comment by xlson** [comment]
@toastedcornflakes could you run `docker inspect grafana/grafana:latest` on your raspberry pi and post the result here? I would like to see which image the manifest is giving you.

**Comment by dagavi** [comment]
I have the same problem. And it says that architecture is "amd64": https://pastebin.com/rdCpdh0U

**Comment by xlson** [comment]
@dagavi what happens if you try to run `grafana/grafana:6.3.4` instead? Is it still trying to run the amd64 image?

To solve the issue temporarily you could refer directly to our arm images:
- `grafana/grafana-arm32v7-linux`
- `grafana/grafana-arm64v8-linux`

**Comment by mc303** [comment]
When I run the `grafana/grafana:6.3.4` image it wil run the arm64v8 image.

The `grafana/grafana-arm64v8-linux` is working for me.

**Comment by toastedcornflakes** [comment]
I get the same output as @mc303 on `grafana/grafana:latest`. `grafana/grafana:6.3.4` works as well.

**Comment by toastedcornflakes** [comment]
Looking at [`packaging/docker/build.sh`](https://github.com/grafana/grafana/blob/13f55bc5e82db80f782b277d08fbe62190bcd7af/packaging/docker/build.sh) my only gess is that it was run with `--fast`, which doesn't tag arm releases.

**Comment by xlson** [comment]
@toastedcornflakes Grafana 6.3.5 has been released which updated the manifests for latest. Could you see if you get the right image when building against latest now?

**Comment by mc303** [comment]
I just tested `grafana/grafana:latest` and for me it is working.

**Comment by xlson** [comment]
@mc303 thank you

**Comment by marefr** [comment]
Closing this since it seemed to have been resolved.
