### ISSUE TITLE
Explore: Logs bar graph stacking is changing randomly 

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#18796]
**What happened**:
When repeating the same query in explore the ordering of the log levels is random and this affects how the bars are stacked, which seems to oscillate between 3 states in which 2 I think are totally wrong:
<img width="1012" alt="Screenshot 2019-08-29 at 21 24 14" src="https://user-images.githubusercontent.com/1014802/63970175-ced42380-caa3-11e9-9784-39f59be66f89.png">
<img width="1010" alt="Screenshot 2019-08-29 at 21 24 20" src="https://user-images.githubusercontent.com/1014802/63970176-ced42380-caa3-11e9-967d-4e50b6d4c6e2.png">
<img width="1013" alt="Screenshot 2019-08-29 at 21 24 26" src="https://user-images.githubusercontent.com/1014802/63970177-cf6cba00-caa3-11e9-85a5-8b0487fba9f9.png">

**What you expected to happen**:
The stacking and color to be consistent.

**How to reproduce it (as minimally and precisely as possible)**:
Using devenv Loki docker container and using query `{job="varlogs"}` seems to do the trick.

**Anything else we need to know?**:
Seems to be related to this in some way https://github.com/grafana/grafana/issues/14247.

**Environment**:
- Grafana version: Grafana v6.4.0-pre (3aa6fdf55)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by akoutmos** [comment]
I have noticed something similar. While I have a stress test going to generate a constant stream of logs, bars will appear and disappear. I can create a gif or post the code if that helps.

**Comment by aocenas** [comment]
@akoutmos If you have a gif and can post it that would be great. At least to make sure it is not some other similar issue and if so that we fix them both.

**Comment by torkelo** [comment]
Maybe we are not sorting the list or somehow the ordering of the levels (series) is non-deterministic?

**Comment by aocenas** [comment]
@torkelo probably, though the first case with gray - blue - gray seem like there may be some additional thing to it.

**Comment by akoutmos** [comment]
Hopefully the animation below makes sense. But what I have setup is a docker compose stack with fluentd and loki and a app that I am stress testing at a regular rate. I would expect the bars to move down the timeline as time goes on, but what it seems is happening is the bars are getting stacked and shuffled around. I sped up the gif to see the effect more clearly:

![loki_animation](https://user-images.githubusercontent.com/4753634/64126248-12b47a80-cd7b-11e9-81f8-fe0a92a997ed.gif)

**Comment by aocenas** [comment]
@akoutmos your case is kinda known (though not ideal) current behaviour. The issue is we show only 1000 lines of logs at a time and from those we create the graph. So the graph also shows only latest 1000 logs and thats why you see the older bars getting smaller and disappearing as time goes on. We definitely wan't to improve that but it's a bit different issue than the one with bars stacking randomly for the same set of logs.

**Comment by akoutmos** [comment]
Thanks for the clarification @aocenas. Appreciate it!
