### ISSUE TITLE
Region annotations with timeEnd not known at creation time, to use the most recent datetime from time picker

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#18797]
**What would you like to be added**:
When an annotation is created and the timeEnd is not known, we can use a special value for the timeEnd or set another field to true in order to have the annotation appeared on graphs with ending time the end time of the time picker.

**Why is this needed**:
In the case where annotations are used to represent alerts (we don't know the timeEnd at the annotation creation since we don't know when the alert will be ceased), then when the annotation appears on graphs it should use the end time of time picker in order to depict that the event represented from the region annotation is still active.

**Comment by ryantxu** [comment]
Interesting idea... as something that would work immediately and not require special logic, could you just set the endTime to some time far in the future?  and then replace it with the real one when the event ends?

**Comment by tpispirigkos** [comment]
@ryantxu yes as a workaround this works too!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
