### ISSUE TITLE
Import Dashboards no longers prompts for datasource syncing

### ISSUE THREAD

**Issue by StephenSDaily** [grafana/grafana#18794]
I don't know when this feature was lost because just did a rather long upgrade.

When transfering dashboards between organizations, whenever you imported the dashboard in a new org, it would prompt you to "sync" up the datasources which made transferring easy. Now when you import, it doesn't give you that option. So if the org that you're coming from has any difference in the datasource (names, databases, etc) the graphs do not work unless you manually change them. 

Please bring this feature back. It's incredibly useful.

**Comment by torkelo** [comment]
make sure you check the checkbox when you export "Export for sharing externally"
