### ISSUE TITLE
The grafana/grafana:5.4.5 image on Docker hub runs Grafana 6.3.4

### ISSUE THREAD

**Issue by patrickf55places** [grafana/grafana#18792]
**What happened**:
- I upgraded my Grafana install by updating the image version from 5.4.3 to 5.4.5.
- Instead of 5.4.5 running, version 6.3.4 is running (based on the version ID in the help menu)

**What you expected to happen**:
- Grafana 5.4.5 would be running.

**How to reproduce it (as minimally and precisely as possible)**:
- Launch the `grafana/grafana:5.4.5` docker image (`sha256:b550d65e085bee4687b44d0ae0c5e3d7daae053dd9d2c90d02c7f4948dd3e228`)

**Anything else we need to know?**:
I probably cannot rollback to the actual 5.4.5 due to migrations running. Can maintainers confirm this?

**Environment**:
- Grafana version: `5.4.5`
- Data source type & version: N/A
- OS Grafana is installed on: Linux/Docker
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
dammit, thanks for reporting this. Will fix asap.

**Comment by xlson** [comment]
Thanks again for reporting this. All images have been updated.

Sorry for any trouble this has caused you. Downgrading from 6.3.4 to 5.4.5 would probably not be very easy to achieve. I can take a look tomorrow to make sure.

**Comment by patrickf55places** [comment]
We didn't experience any issues in upgrading to 6.3.4, so we won't be looking to downgrade.

**Comment by marefr** [comment]
@patrickf55places sorry for the inconvenience. Glad  6.3.4 worked out for you. If you haven't already, I suggest you update your referenced image version to 6.3.4 since we have pushed a new image for 5.4.5.
