### ISSUE TITLE
Cloudwatch Datasource: enable the querying of multiple aws accounts

### ISSUE THREAD

**Issue by lfroment0** [grafana/grafana#18805]
**What would you like to be added**:
an input field / dropdown in the cloudwatch plugin's frontend panel, to select the aws account to query for metrics

**Why is this needed**:
in case multiple accounts have to be monitored, it is not possible with the current implementation.

I'd be glad to open a PR for this feature

**Comment by sirfanmkm** [comment]
+1 for this feature request.

**Comment by sunker** [comment]
@lfroment0 this chould be achieved using a [mixed data source](https://grafana.com/docs/grafana/latest/features/datasources/mixed/#mixed-data-source).

**Comment by rajatparida86** [comment]
@sunker Could you please elaborate on your solution a bit more? Specifically:
- How can I get multiple AWS accounts to query in a mixed data source? As far as I understand the use of a `mixed` data source, we can only specify multiple data sources and not multiple AWS accounts to query to?
- How do you think the authentication from the AWS account (where grafana server is running) to other AWS accounts (to which we want to make the Cloudwatch query) will work? As far as I understand the outgoing query will have to be attached with a valid IAM role which the target AWS account can say okay to. With the current Grafana setup, this IAM role can not be dynamically attached to a query. Or how can a `mixed` data source help in setting up this authentication in the background?

**Comment by snobear** [comment]
Hi @rajatparida86, I had the same need to query across AWS accounts. The `Mixed` data source option works, you just need to click the `Add Query` button and it will let you select a different data source for the new query. Existing queries default to what the data source that was already set. The downside is each metric shows in the legend, even if there are no data showing up, but thats just an aesthetics problem.

Not sure how auth/access works as someone else had already set that up.

I'm on Grafana 6.3.6 fyi. HTH.
