### ISSUE TITLE
Grafana loses data if you use grouping for text fields

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#18808]
**What happened**:
I'm trying to group data by text field to get a summary of the number of events

I see that part of the data just disappears. At the same time, I know that they are in my index.
In the screenshot below, the panel in the left center groups by quantity, the bottom panel simply displays the raw document:
![image](https://user-images.githubusercontent.com/50422107/64018305-24a8da00-cb3d-11e9-9cb1-175136c2852f.png)
At the same time, grouping by fields with few characters grouping works fine - this is the panel on the right in the center:
![image](https://user-images.githubusercontent.com/50422107/64018871-aa795500-cb3e-11e9-93f2-79d3f9f52bcd.png)

**What you expected to happen**:
I will get a table with grouped data with a counter of their number

**Anything else we need to know?**:
This works fine with short lines, but the longer the line, the higher the chance of losing it

query parametres:
![image](https://user-images.githubusercontent.com/50422107/64017769-80726380-cb3b-11e9-8795-a08b9833e01b.png)

Filed parametres:

        "Short" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }

        "LevelCount" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Elasticsearch 7.0.1
- OS Grafana is installed on: docker container from hub

**Comment by torkelo** [comment]
The panel that shows no data, can you use query inspector and inspect data returned by Elasticsearch?

**Comment by M0rdecay** [comment]
Sure.

Query from right panel:
`{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1/_msearch?max_concurrent_shard_requests=256",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"LogEventTime\":{\"gte\":\"1557987596689\",\"lte\":\"1557987610967\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"ServiceName:NOMAD AND ClientCompany:Computer AND Message:\\\"\\\" AND additionalInfo:\\\"\\\"\"}}],\"must\":[{\"match_phrase\":{\"LevelCount.keyword\":{\"query\":\"4\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"LevelCount.keyword\",\"size\":500,\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1},\"aggs\":{}}}}\n"
  },
  "response": {
    "took": 1,
    "responses": [
      {
        "took": 1,
        "timed_out": false,
        "_shards": {
          "total": 12,
          "successful": 12,
          "skipped": 0,
          "failed": 0
        },
        "hits": {
          "total": {
            "value": 2,
            "relation": "eq"
          },
          "max_score": null,
          "hits": []
        },
        "aggregations": {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "4",
                "doc_count": 2
              }
            ]
          }
        },
        "status": 200
      }
    ],
    "$$config": {
      "method": "POST",
      "url": "api/datasources/proxy/1/_msearch?max_concurrent_shard_requests=256",
      "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"LogEventTime\":{\"gte\":\"1557987596689\",\"lte\":\"1557987610967\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"ServiceName:NOMAD AND ClientCompany:Computer AND Message:\\\"\\\" AND additionalInfo:\\\"\\\"\"}}],\"must\":[{\"match_phrase\":{\"LevelCount.keyword\":{\"query\":\"4\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"LevelCount.keyword\",\"size\":500,\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1},\"aggs\":{}}}}\n"
    }
  }
}`

And from left panel, with no data:
`{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1/_msearch?max_concurrent_shard_requests=256",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"LogEventTime\":{\"gte\":\"1557987596689\",\"lte\":\"1557987610967\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"ServiceName:NOMAD AND ClientCompany:Computer AND Message:\\\"\\\" AND additionalInfo:\\\"\\\"\"}}],\"must\":[{\"match_phrase\":{\"LevelCount.keyword\":{\"query\":\"4\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"Short.keyword\",\"size\":500,\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1},\"aggs\":{}}}}\n"
  },
  "response": {
    "took": 1,
    "responses": [
      {
        "took": 1,
        "timed_out": false,
        "_shards": {
          "total": 12,
          "successful": 12,
          "skipped": 0,
          "failed": 0
        },
        "hits": {
          "total": {
            "value": 2,
            "relation": "eq"
          },
          "max_score": null,
          "hits": []
        },
        "aggregations": {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
          }
        },
        "status": 200
      }
    ],
    "$$config": {
      "method": "POST",
      "url": "api/datasources/proxy/1/_msearch?max_concurrent_shard_requests=256",
      "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"LogEventTime\":{\"gte\":\"1557987596689\",\"lte\":\"1557987610967\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"ServiceName:NOMAD AND ClientCompany:Computer AND Message:\\\"\\\" AND additionalInfo:\\\"\\\"\"}}],\"must\":[{\"match_phrase\":{\"LevelCount.keyword\":{\"query\":\"4\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"Short.keyword\",\"size\":500,\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1},\"aggs\":{}}}}\n"
    }
  }
}`

The query result is really empty. Why could this happen?

**Comment by M0rdecay** [comment]
I apologize for the concern. The reason for the situation described above was the low value of [ignore_above](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html) in my template.
