### ISSUE TITLE
MixedDatasource: Handle hidden queries internally 

### ISSUE THREAD

**Issue by hoang-a** [grafana/grafana#18801]
**What happened**: Following upgrade from v6.1.6 to 6.3.3 a query that sums disabled queries has stopped working on mixed datasource graphs.

**What you expected to happen**: The sum should be visible as Query C even when Query A/B are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
Mixed Datasource graph:
Query A - Data from Graphite (Disabled)
Query B - Data from Graphite (Disabled)
Query C - sumSeries(#A, #B)
Query D - Data from Prometheus

In v6.1.6 this would give a graph which displays the values of Query C and Query D, in v6.3.3 this graph only displays Query D, unless Query A/B are enabled, which would then give Query C the sum of the enabled queries.

When this is performed on a single Datasource graph on v6.3.3 the functionality still exists and the value of Query C will be displayed even when Query A/B are disabled.

**Anything else we need to know?**: Possibly related to https://github.com/grafana/grafana/pull/16409 ?

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Mixed Graphite/Prometheus
- OS Grafana is installed on: CentOS7
- User OS & Browser: macOS Mojave, Vivaldi
- Grafana plugins: Graph, Graphite, Prometheus
- Others: n/a

**Comment by torkelo** [comment]
thanks for reporting this, it's due to hidden queries are not being sent to the mixed data source. Need to enable this (it's a setting in the plugin.json), and then filter out hidden queries inside the mixed data source.

**Comment by hoang-a** [comment]
Thanks for the quick response, I have tried setting `"hiddenQueries": true,` in `/usr/share/grafana/public/app/plugins/datasource/mixed/plugin.json` but the issue is still the same.

**Comment by ryantxu** [comment]
Mixed datasource also filters hidden:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mixed/datasource.ts#L20

We can/should remove that and add `"hiddenQueries": true` to plugin.json
