### ISSUE TITLE
Filter or time change is not applied if you perform an action from the expanded panel

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#18809]
**What happened**:
I expand the panel, apply a filter, minimize the panel. The filter is not applied. A similar situation is observed if you expand the histogram panel and change the time period:
![image](https://user-images.githubusercontent.com/50422107/64019225-a00b8b00-cb3f-11e9-9315-568d608b1e7e.png)
Pay attention to the displayed time on the timeline of both panels.

One more example:
![image](https://user-images.githubusercontent.com/50422107/64019340-ef51bb80-cb3f-11e9-8c7f-8945a850cd99.png)

**What you expected to happen**:
Filter will be applied

**How to reproduce it (as minimally and precisely as possible)**:
You can repeat it here - https://play.grafana.org/d/000000012/grafana-play-home?orgId=1. You need to expand any panel, change the time period and minimize the panel.
Or here - https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1. Expand the table, apply a filter, minimize the table.

**Environment**:
- Grafana version: 6.3.3

**Comment by torkelo** [comment]
you have hit refresh after being in edit mode to update the whole dashboard
