### ISSUE TITLE
mysql query for alter dashboard_snapshot.data to mediumtext migration invalid

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#1880]
this is not a valid mysql command.
Mysql("ALTER TABLE dashboard_snapshot.data MODIFY data MEDIUMTEXT;"))

should be

Mysql("ALTER TABLE dashboard_snapshot MODIFY data MEDIUMTEXT;"))

**Comment by woodsaj** [comment]
on second review, it just looks like this mirgation statement shouldnt be there are the dashboard_snapshot table does not have a data column.

**Comment by torkelo** [comment]
thanks for spotting that, the column name is dashboard in the snapshot table :)
