### ISSUE TITLE
Disable user from editing user profile

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#18819]
**What would you like to be added**:
Possibility to disabling a user from edit his/her User Profile.

**Why is this needed**:
Otherwise a user can “give” the account to a user without knowledge to the server owner.

**Comment by torkelo** [comment]
> Otherwise a user can “give” the account to a user without the knowledge to the server owner.

what do you mean?

**Comment by flopp999** [comment]
If the logged in user change all the information about his/her it can be a new user that the system owner doesn't know.
I can change name, email and username, this is want to be able to disable for a user.

**Comment by torkelo** [comment]
You can disable this if you enable oauth, and then disable the normal login form:
https://grafana.com/docs/auth/overview/#disable-login-form

**Comment by roidelapluie** [comment]
Is this a duplicate of https://github.com/grafana/grafana/issues/19964 ?

**Comment by nicolas17** [comment]
> Is this a duplicate of #19964 ?

I don't think so. That one is about disabling existing Grafana-local passwords when switching to another auth provider, this is about profile editing.

But this one does sound like a duplicate of #7810.

**Comment by grumpazoid** [comment]
I found this issue while searching how to resolve the same problem. I want to make a dashboard available online and require the user to login with name and password. They should not have the facility as a viewer to change their name and/or password unless granted permission.
