### ISSUE TITLE
half of top menu is cut off when viewing loki 

### ISSUE THREAD

**Issue by Morriz** [grafana/grafana#18817]
Safari consistently pulls up the screen after successful initial page load showing full menu, resulting in the top menu to be visible for 50%. See screenshot (top is the edge of the browser view port):

https://www.dropbox.com/s/tq40wxl7eyei11f/Screenshot%202019-08-30%2019.41.51.png?dl=0

I have tried both 6.3.3 and 6.3.4

**Comment by torkelo** [comment]
Fixed and will be in next patch early next week https://github.com/grafana/grafana/pull/18654

**Comment by Morriz** [comment]
That fix is for another cosmetic problem though...will it also fix this?
