### ISSUE TITLE
Unable to see Grafana dashboard if user doesn't have permission on folder, but has permission for particular dashboard

### ISSUE THREAD

**Issue by Rajendra08** [grafana/grafana#18816]
**What happened**:
1. I have two users in my grafana.
       Admin
       DevUser.
2. I have a folder "healthmontior" in grafana and all dashboards are kept inside.

HealthMonitor has total 4 graphs.
Requirement here is Admin should be able to see all graphs. But "DevUser" can be able to see only two graphs.

So on folder I gave permission only to Admins. But dashboard level for two dashboard i gave permission to "DevUser".

I have logged in as "DevUser".
Clicked on "Dashboards -> Manage". Here I can't see anything now.

If I search for particular graph which has permission, then i would be able to see.  
But If i don't remember graph name, then it is not possible to check available graphs.

We don't want to create separate folder and assign permissions. We would like to control permissions inside the folder.

**What you expected to happen**:

"Dashboards -> Manage" should show all the graphs which user has permission.

**How to reproduce it (as minimally and precisely as possible)**:

Steps explained in "What Happened" section.
**Anything else we need to know?**:

**Environment**:
- Grafana version:
Grafana v6.2.5 (commit: 6082d19)
- Data source type & version:
- OS Grafana is installed on:
Linux
- User OS & Browser:
MAC & Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This use case is not supported, folders that you do not have access to will not be visible in the dashboard tree. 

closing this (there already is an open issue for this)
