### ISSUE TITLE
re-organization of panel indicators (spinner and error indicator), as state machine?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#18829]
right now a chart panel has:
* a loading indicator top right
* an error indicator top left

these two seem to be implemented as separate concepts.
I have run into bugs (e.g. #18169), and was wondering if perhaps this concept/piece of the code could be refactored using a state machine. if we are more explicit about the various states, e.g.
* waiting
* returned-with-error
* returned-without-error
* loaded successfully

.... then I think both the code could be more robust, and the UI would make more sense. a single place to describe the current state.

this would perhaps also allow us to introduce new states such as:

* returned-with-warning (could be used for soft failures such as we have data but it is incomplete or pre-aggregated data)
* loaded but potentially out of date (for queries that requested data until now or until the future, such that the response couldn't cover the entire timeframe)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
