### ISSUE TITLE
PageDuty test not working correctly

### ISSUE THREAD

**Issue by palamccc** [grafana/grafana#18820]
**What happened**: PagerDuty "send test" button is not working as expected

**What you expected to happen**: When i type wrong key, i expect to see some error message

**How to reproduce it (as minimally and precisely as possible)**:
create a new pagerduty channel
type wrong key
click on "send test"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version:
- OS Grafana is installed on: docker image grafana/grafana:6.2.5
- User OS & Browser:
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/202276/64071147-3a2f1880-cc91-11e9-902c-9ec4306d6869.png)

**Comment by torkelo** [comment]
Thanks for reporting this!
