### ISSUE TITLE
DataFrame filenames & organization

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18822]
Today we have

* utils/dataFrameHelper.ts (contains FieldCache & MutableDataFrame)
* utils/dataFrameHelper.test.ts 
* utils/dataFrameView.ts  (DataFrameView)
* utils/dataFrameView.test.ts  (DataFrameView)
* utils/processDataFrame.ts 
 
Think we should move FieldCache & tests to its own file and rename files to match their primary export (except maybe processDataFrame). 

It's a bit tricky to only change letter casing in file names like utils/dataFrameView -> utils/DataFrameView

So one option would be to move all of the data frame related stuff to a top level dir /dataframe or /DataFrame (not sure which I prefer, tricky with casing and consistency) . Now everything in data package is under utils. Maybe transformers and matchers should be top level dirs? 

thoughts @ryantxu ?

**Comment by ryantxu** [comment]
Away for a while... So no real reply yet.   Yes needs cleanup and more clear naming conventions/capitalization/style

I also wonder about exporting some folders with shared namespace rather than global everything.

What about the vector class implementations?

**Comment by dprokop** [comment]
Core things like data frame/matchers&transfomers/datetime utils deserve their own directories.
I think following structure for organising code in grafana-data could work:

```
grafana-data
├── src
│   ├── types
│   ├── utils
│   ├── dataframe
|   |    └── // data frame code, field cache, dataframe utils
|   ├── transformations
|   |    └── // matchers&transformers
|   ├── datetime
|   |     ├── moment_wrapper.ts
|   |     ├── rangeutlis.ts
|   |     ├── datemath.ts
|   |     └── // probably more to come
|   ├── text
|   |      └── // text & string operatiosn
|   |
```

Not sure what to do with things like valueMappings, registry, fieldReducers etc... Think those could just stay in the utils directory or just be placed without any directory under `src` folder.

@ryantxu I think vectors could be split into several files and place under `vector` dir.

When it comes to naming convention I think directory names should stay in lowercase as they represent area and not particular type of code being exported. And the file name should reflect the role of the primarish export. i.e. dataFrameView.ts would be DataFrameView.ts while file names exporting utility functions would be named  with lowercase first character.

**Comment by torkelo** [comment]
very good proposal!
