### ISSUE TITLE
ECS/ContainerInsights MemoryUtilized should return percent, not MiB

### ISSUE THREAD

**Issue by sandangel** [grafana/grafana#18823]
**What happened**: Querying for MemoryUtilized of ECS Service/ECS Cluster returning MiB

**What you expected to happen**: It should return Percentage instead as we see at CloudWatch console

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/22189661/64078850-187a7380-cd1b-11e9-8db2-530cbe9d2533.png">

**How to reproduce it (as minimally and precisely as possible)**:

```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1567266116262",
      "to": "1567352516262",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 1265,
          "datasourceId": 2,
          "type": "timeSeriesQuery",
          "alias": "{{ServiceName}}",
          "dimensions": {
            "ClusterName": "z-ecs-qa1",
            "ServiceName": "z-worker-qa1"
          },
          "expression": "",
          "highResolution": false,
          "id": "",
          "metricName": "MemoryUtilized",
          "namespace": "ECS/ContainerInsights",
          "period": "60",
          "region": "ap-northeast-1",
          "returnData": true,
          "statistics": [
            "Average"
          ],
          "datasource": "CloudWatch"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "unit": "mbytes"
        },
        "series": [
          {
            "name": "z-worker-qa1",
            "points": [
              [
                199,
                1567266060000
              ],
              [
                199,
                1567266120000
              ],
              [
                199,
                1567266180000
              ],
              [
                199,
                1567266240000
              ]
            ],
            "tags": {
              "ClusterName": "z-ecs-qa1",
              "ServiceName": "z-worker-qa1"
            }
          }
        ],
        "tables": null
      }
    }
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.4
- Data source type & version: CloudWatch
- OS Grafana is installed on: docker grafana/grafana
- User OS & Browser: Mac, Firefox
- Grafana plugins: CloudWatch
- Others:

**Comment by marefr** [comment]
@sandangel I don't understand how you're using container insights in Grafana since we have an open PR #18971 to add support for container insights. 

Please provide more information.

**Comment by sandangel** [comment]
hi @marefr , thanks for your response. My issue is Grafana is returning the wrong unit and value for MemoryUtilized metrics. When I query using CloudWatch dashboard, it returns Percentage, while in Grafana, it returns MiB. When I register data source in Grafana, I used custom namespace and added ECS/ContainerInsights.

**Comment by marefr** [comment]
When looking at CloudWatch documentation, https://docs.amazonaws.cn/en_us/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html, it doesn't mention percentage so looks like CloudWatch API don't support returning percentage.
