### ISSUE TITLE
Mapping variables

### ISSUE THREAD

**Issue by merryjane** [grafana/grafana#18832]
**What would you like to be added**:
In "Variable types" https://grafana.com/docs/reference/templating/ will be great to add new type "Map".
It could look like two columns. In headers of columns we add names of variables. In rows we add values.
Value in second column depends on values of variables specified in the first column.
Special value "default" in first column could be use for assignment default value to our target variable.

**Why is this needed**:
It will be very useful when we want create a logic based on exist variables without change metrics sending to storage.

**Comment by torkelo** [comment]
You mean you want to define many variables from a table result?

**Comment by torkelo** [comment]
Think you need to describe more

**Comment by merryjane** [comment]
For example I have many environments for services. Metrics from services in different environments keep in different instances of prometheus. Moreover amount of environments not equal amount of prometheus' instances.
I want to make a map: environment - datasource (prometheus's instance):
testing - prometheus-testing,
dev - prometheus-testing,
stage - prometheus-testing,
prod - prometheus-prod,
prestable - prometheus-prod.
After that I want to add toggle to dashboard with environment only. Now I should have two toggles with environment and datasource. 
Additionally need opportunity to add variable of this type to Query in Queries' setting.

**Comment by torkelo** [comment]
similar to this https://github.com/grafana/grafana/issues/5206 

you can create a custom variable $env = dev,testing,stage,prod

then a datasource variable with a regex filter using  /$env/

this will filter the datasource list using the regex based on the value in $env
