### ISSUE TITLE
[feature request] Add support for new google analytics codes

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#18844]
**What would you like to be added**:

Google obsoletes (now called legacy) analytics codes `UA-XXXXXXXXX-Y`, and switched to a new approach. Seems like only old `UA-...` codes [are supported](https://grafana.com/docs/installation/configuration/#google-analytics-ua-id)

**Why is this needed**:

Google recommends updating from Legacy ga.js to universal analytics [here](https://developers.google.com/analytics/devguides/collection/upgrade/)

**Comment by torkelo** [comment]
we are not using ga.js we are using analytics.js and initializing it same was as latest docs recommend 
https://github.com/grafana/grafana/blob/master/public/app/core/services/analytics.ts#L22

**Comment by lukaszgryglicki** [comment]
Oh so variable name `google_analytics_ua_id ` confused me. So just to clarify, if I use legacy code there `UA-XXXXX` will it also work, or it *only* supports new universal approach now?
Maybe worth explicitly saying that both work or only new approach work in the docs?
