### ISSUE TITLE
Replace racially charged language "whitelist/blacklist"

### ISSUE THREAD

**Issue by naomijub** [grafana/grafana#18841]
**What would you like to be added**:
I'd like to deprecate the "whitelist/blacklist" language in Grafana, replacing them with "safelist/blocklist" or "allowlist/denylist" (This has been done in many places like [Graphite](https://github.com/graphite-project/graphite-web/issues/1569) )

**Why is this needed**:
This is important to help Grafana become more inclusive.

**Comment by torkelo** [comment]
Ah, good feedback! never thought about the origin of these words!

**Comment by daniellee** [comment]
We don't have any blacklists except for tslints rules - as that is an external lib that would be hard to change. Unless I am missing something?

We use whitelist in three places: 
- whitelisted cookies for datasource config 
- `data_source_proxy_whitelist` [configuration setting](https://grafana.com/docs/installation/configuration/#data-source-proxy-whitelist).
- In the [docs for Azure Monitor](https://grafana.com/docs/features/datasources/azuremonitor/#azure-monitor-metrics-whitelist)

**Comment by naomijub** [comment]
@daniellee  The idea is to replace any references to `whitelist` to something like `allowlist` and `blacklist` to something like `denylist`. So `data_source_proxy_whitelist` would become `data_source_proxy_allowlist` and in the Azure Monito:

> Azure Monitor Metrics **Allowlist**
> Not all metrics returned by the Azure Monitor API have values. The Grafana data source has a **allowlist** to only return metric names if it is possible they might have values. This **allowlist** is updated regularly as new services and metrics are added to the Azure cloud. You can find the current **allowlist** here.

I can open an issue in Tslint as well for their `blacklist`

**Comment by kylebrandt** [comment]
Also the auth proxy  https://grafana.com/docs/grafana/latest/auth/auth-proxy/
