### ISSUE TITLE
Add OrgID/folderid fields in the annotation creation through API

### ISSUE THREAD

**Issue by tpispirigkos** [grafana/grafana#18851]
**What would you like to be added**:

Use organization id field and folder id in the annotation creation. If the fields are ommited then the annotation should be made global. 

**Why is this needed**:

Currently annotations can be filtered through the fields dashboardid and panelid.  When new dashboards are added (after annotations are created) then user must replicate the existing annotations in order to be available on the new dashboards.
 
By adding the organization id and fodler id the current schema will be more flexible since annotations will be grouped with more ways.

**Comment by torkelo** [comment]
No sadly creating things that will be available cross orgs is a big no no, orgs are completely isolated. 

if you give you annotation tags they will be usable on any dashboard (in that org)

**Comment by tpispirigkos** [comment]
> No sadly creating things that will be available cross orgs is a big no no,

Any chance for the folder id ?
