### ISSUE TITLE
Explore: UX/UI improvements for pausing and resuming of live tailing

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#18850]
UX/UI feedback and improvements for [#18836](https://github.com/grafana/grafana/pull/18836).

implementation to-dos:
- [x] margins of buttons, logs list and logs headline within the logs box are all over the place. should look more consistent
- [x] live logging font and line spacing different than the non-live
- [ ] show which rows are new, needs nicer design than gray
- [x] change stop button text to "Exit live mode"

design to-dos:
- [x] show which rows are new, needs nicer design than gray
- [x] find a place to show meta labels:
  - [x] when playing show rate of messages  (`3 lines/s`)
  - [x] when paused, show number of rendered lines 
- [x] need better feedback of what state you are in
  - [x] add a little diode (either in button or next to it) showing state (playing, paused, error) with the paused state pulsing
  - [x] "Last line received" should move to hover title of the diode
- how to enter live? should we have a separate button to enter live? or have a split Run/Live button? 
- [x] exiting live should print the last seen lines in the normal mode (perhaps have to execute query again with range from live view)
  - [x] show a hint that last lines are shown, and that to get recent lines for time range, query has to be run

Postponed:
- deal with consistent order as a user setting
- in non-live mode we do not have the scrollable area for the logs but the entire screen is scrollable. wouldn't it make more sense to have a sticky bar with buttons and Last line received label in the bottom of the screen and take the list out of the box/make the entire screen scrollable?
an example for scrollable full screen live logging can be found here: https://logz.io/blog/logzio-live-tail/

**Comment by jessover9000** [comment]
@aocenas For the appearance of new lines in live tailing: I got inspired by the mint colored button with the label "This button … is cool" [here](https://css-tricks.com/using-multi-step-animations-transitions/). I like how the button text softly moves to the left. maybe we could have the log lines appear like that, but moving up + fading in into the view from the bottom (and maybe much faster but with a smaller movement)?
once they change from "fresh" to "normal lines" their background color could fade out to white/transparent. I think 0.3 – 0.5 seconds of fading time should be enough (we can test this). please change the background color of fresh lines to #d8e7ff (light blue).

for margins and paddings, I'll experiment a bit and send you a screenshot :)

**Comment by aocenas** [comment]
@jessover9000 Definitely like the animation though not really sure about the implications (not heavy animation creator myself). I can imagine it in case of line by line but not sure what it would look like in case multiple lines got added or the whole view got replaced by new lines (staggering would be best looking probably but not feasible due to non fixed time). Also no idea whether it would be problematic for performance or not. Adding the sense of movement could help with understanding how fast the stream is going, at the same time though could edge case on blurry screen of text where you really can't glimpse anything. @kaydelaney was working on some transitions here and there maybe she will have better insight into that.

> once they change from "fresh" to "normal lines" their background color could fade out to 
Fading should be easier to do and I think would make it look a lot better.

**Comment by jessover9000** [comment]
For paddings:
![Screenshot 2019-09-04 at 15 04 42](https://user-images.githubusercontent.com/53754871/64257363-872b1d00-cf25-11e9-9fe3-d6fee423fa56.png)
I would propose this kind of padding unification (went for 8px almost everywhere). The "logs" headline has too much padding on the left in non-live mode too, maybe we can change both :) Also there is an element called collapse-loader, not sure whether it serves any purpose or is just a spacer, but as long as there is nothing there except additional spacing, we can completely remove that.

**Comment by ivanahuckova** [comment]
@aocenas I am going to start to work on this issue. If/when you start to work on issue, please let me know and we can sync on what have I completed/what needs to be done. 🙂
@jessover9000 Thank you for detailed information. If I have any questions, I will definitely let you know and get back to you!

**Comment by ivanahuckova** [comment]
> please change the background color of fresh lines to #d8e7ff (light blue).

I just want to check, before we introduce a new color, if we couldn't use colors that are already in grafana. Do you think that any of these colors for[ dark theme](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/themes/dark.ts#L4) and[ light theme](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/themes/light.ts) wold work? Also @Ijin08, I would like to check, if we are using this [color palette](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/namedColorsPalette.ts#L124 )?

> I would propose this kind of padding unification (went for 8px almost everywhere). The "logs" headline has too much padding on the left in non-live mode too, maybe we can change both :)

Yes, heading has padding 8px 16px 0. It is unified with the graph's padding in Explore (see below). So I think that we should either change both of them, or keep it unified. What do you think?
![image](https://user-images.githubusercontent.com/30407135/64338164-54465f00-cfe1-11e9-903e-f5277e0729ea.png)

> Also there is an element called collapse-loader, not sure whether it serves any purpose or is just a spacer, but as long as there is nothing there except additional spacing, we can completely remove that.

Collapse__loader is used as a some kind of placeholder for collapse__loader-active (which is a spinner/loader, that is used when the query is slow). If it wasn't there, every time when query is slow, it would jump couple of pixels. Therefore we should keep it there.

**Comment by jessover9000** [comment]
@ivanahuckova the blue I chose is lighter than the lightest blue in the color picker. so it is true that it's not in our current palette. The lightest blue of the palette felt to me like it was still too dark to work as a background color in this case (tested it in the browser). But @Ijin08 feel free to give some advice here :)

About the padding of the headline, well the Graphs headline has a caret icon though, in that case the extra padding seems okay. oh well, I guess let's leave it for now and maybe go over all the headlines in a general typography overhaul.

**Comment by Ijin08** [comment]
I think the new blue is fine. The lightest one in color picker would probably be a bit too much.
As for dark them try #1250B0. But I think we might need to go darker. The faint-blue that we have is probably to dark but could be worth testing. The faint blues are used for selecting visualisation. Check them out there. Could try it out in light theme as well.

**Comment by ivanahuckova** [comment]
> About the padding of the headline, well the Graphs headline has a caret icon though, in that case the extra padding seems okay. oh well, I guess let's leave it for now and maybe go over all the headlines in a general typography overhaul.

Does it mean, that I can check out following task? Do we need to fix any other margins/paddings? 
[ ] margins of buttons, logs list and logs headline within the logs box are all over the place. should look more consistent

**Comment by jessover9000** [comment]
> @jessover9000 Does it mean, that I can check out following task? Do we need to fix any other margins/paddings?

Checked it now, sorry for the delay. I'm not entirely happy with how the "collapse-loader" element adds unnecessary whitespace between the "Logs" headline and the actual logs area, but I guess it can't be helped?
One last other thing, the div with the pause and exit button has a padding-bottom and the logs div also has padding, so in the bottom of the pause and exit button div there's double padding now. So as soon as you remove padding-bottom for div.css-46c46h (if that's the correct name?), you can check it out ;)

**Comment by ivanahuckova** [comment]
> One last other thing, the div with the pause and exit button has a padding-bottom and the logs div also has padding, so in the bottom of the pause and exit button div there's double padding now. So as soon as you remove padding-bottom for div.css-46c46h (if that's the correct name?), you can check it out ;)

fixed 🙂
