### ISSUE TITLE
grafana 2.0 ldap

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1885]
Hi Torkel,

I saw your cast about login and rights etc. Will there be an ldap integration? People usually prefer ldap since they dont have to login to to different sites with with different accounts, single sign-on with ldap makes more sense.

**Comment by torkelo** [comment]
yes, there are plans for LDAP, not sure about SSO, that is something else, LDAP auth will enable you to use your domain/company credentials to login to grafana, SSO will require something else
