### ISSUE TITLE
Everything 404s after upgrade to 2.0.2

### ISSUE THREAD

**Issue by shish** [grafana/grafana#1886]
Using the debian packages; installed 2.0.1 and configured to my tastes, everything worked great. Then upgrading to 2.0.2 via 'apt-get upgrade' when that was released, 

```
# curl -I http://localhost:3000/
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Set-Cookie: grafana_sess=f23ddf176c17714f; Path=/; HttpOnly
Date: Sun, 26 Apr 2015 10:52:59 GMT
[...]
```

**Comment by torkelo** [comment]
did you restart grafana-server after upgrade? strange, not sure what could be going on here, what distro and version are you on?

**Comment by shish** [comment]
Restart fixed it; I'm accustomed to packages restarting themselves on upgrade by default so didn't think to do that >_<

**Comment by torkelo** [comment]
You can enable restart on upgrade in /etc/default/grafana-server

**Comment by shish** [comment]
If a restart is necessary because things are broken without one, why is "don't do a restart" the default? :S

**Comment by torkelo** [comment]
@shish good point, maybe the RESTART_ON_UPGRADE should be true by default
