### ISSUE TITLE
Data link time range modification

### ISSUE THREAD

**Issue by lightbody** [grafana/grafana#18867]
**What would you like to be added**:

More control over the start/end time in _data links_ URL templates.

**Why is this needed**:

I'm trying to set up a data link so that I can quickly jump over to my logs system (in this case CloudWatch Logs -- we haven't moved over to Loki yet). This could almost work perfectly if only I could have more control over the start/end time parameters. In CloudWatch Logs Insights, the URL parameters look like this:

`https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logs-insights:queryDetail=~(end~'2019-09-03T15*3a57*3a12.000Z~start~'2019-09-03T07*3a00*3a00.999Z~timeType~'ABSOLUTE~tz~'Local~editorString~'...`

And of course the `__url_time_range` is in the format `?from=now-6h&to=now`. It would be wonderful if there was a way to convert the start/end times into other common formats, such as this one. 

Thanks for considering!

**Comment by lightbody** [comment]
FYI - I also requested to the CloudWatch Logs team that they support your time range format. I'll let you know if they respond :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
