### ISSUE TITLE
Dashboard: Autocomplete not working Firefox/Edge

### ISSUE THREAD

**Issue by rmunoz10** [grafana/grafana#18863]
Hi - Autocomplete is not working on Firefox/Edge (I did not test other browsers)

To reproduce I created a dashboard with a single variable with over 1000 values coming from Postgres.  Unfortunately, autocomplete does not work as expected.

I have attached the json file to reproduce.

Thanks

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: Postgres 11
- OS Grafana is installed on: Centos 7
- User OS & Browser: ubuntu 18.04 LTS
- Grafana plugins: ajax v0.0.6; bubble chart v1.1.0; clock v1.3.6; radar graph v1.4.4; worldmap panel v0.2.0; simplejson v1.4.0
- Others:

[autocompletetest.tar.gz](https://github.com/grafana/grafana/files/3570279/autocompletetest.tar.gz)

**Comment by torkelo** [comment]
Does it work in Chrome?

**Comment by torkelo** [comment]
works for me in Firefox here: https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&var-app=country&var-server=All&var-interval=1h

**Comment by rmunoz10** [comment]
For me it breaks with this value: '+MD'
If I filter out '+MD' from my result set the autocomplete works

**Comment by torkelo** [comment]
Added +MD to a dropdown and search still works. Not sure what else to try
