### ISSUE TITLE
[Feature Request] - Allow anchoring of variables to the top of the dashboard

### ISSUE THREAD

**Issue by n1nj4888** [grafana/grafana#18873]
**What would you like to be added**:
Please can you add an option to allow the anchoring of defined variables to the top of the dashboard - In the same way that the Dashboard Name and settings anchor to the top of the dashboard and are still visible (and accessible) even if the user scrolls down the dashboard?

**Why is this needed**:
Currently, when a dashboard has variables defined they are displayed in the dashboard under the name of the dashboard. However, when scrolling down the dashboard, the variables are also scrolled out of view of the user - If the user wishes to view a panel half way down the dashboard but also wants to toggle the variables at the top, the user has to constantly scroll up to the top of the dashboard, change the variable(s) and then scroll back down to the panel they want to view... 

Therefore it would be great if the variables (example highlighted in red in screenshot below) would be anchored to the top of the dashboard in the similar way that the Dashboard name and settings (example highlighted in green in screenshot below) are - Or at least it would be good to have a configurable setting for each dashboard to allow the anchoring of variables or not...

![image](https://user-images.githubusercontent.com/29934446/64224269-81274300-cf09-11e9-94c8-7efb00bd56f9.png)

**Comment by xlson** [comment]
Duplicate #12790
