### ISSUE TITLE
Upgrade go to 1.13.1

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#18878]
Go 1.13 have been released: https://golang.org/doc/go1.13

- [x] Fix so go 1.13.1 can be used to build Grafana
- [x] Update CircleCI/build scripts to use go 1.13.1

**Comment by agaengel** [comment]
I tried to open a pull request building grafana with 1.13 but unfortunatly the builder is build by script in the grafana repo https://github.com/grafana/grafana/tree/master/scripts/build/ci-build

Therefor the pull request fails https://github.com/grafana/grafana/pull/19009

should I open a pull request to update the builder docker image first?

Regards
Alex
