### ISSUE TITLE
now-24h does not respect UTC timezone setting

### ISSUE THREAD

**Issue by mmx1960** [grafana/grafana#18876]
If a dashboard is set to UTC mode, some time range mode such as 'Last 30 minutes' , 'Last 12 hours' (actually it's querystring like 'now-30m','now-12h') still starts at the current time in the browser's local timezone, as opposed to the current time in UTC.

I read some source code in grafana and find : in model 'dateMath'(datemath.js) , it return the 'utc datetime' when the querystring prefix 'now' and the timezone is equals to 'utc'  (type based on mement.js). then  use 'add'  or 'subtract' method to operate datetime,it's still holds the timestamp in the browser's local timezone.It's different from 'startOf' or 'endOf' method.because the moment.js's utc mode says 

> It is important to note that though the displays differ above, they are both the same moment in time.

I hope clearly described the infomation about this 'bug',if you have any question,please comment below，thanks.

- Grafana version:5.2.3
- Data source type & version: Elasticsearch
- OS Grafana is installed on: centos
- User OS & Browser: chrome

**Comment by torkelo** [comment]
Unable to replicate any of this. 

The UTC option only changes how time is displayed. 

Last 30m will be querying for the same data no matter the timezone option. 

same for now-24h, will query for last 24 hours of data, a range that is completely timezone independent. 

for an absolute range the UTC option will have an impact on the time range sent in the query. 
as timezone will change how "2019-09-10 10:00:00" is interpolated / sent in query.

**Comment by mmx1960** [comment]
thanks for your reply, make me have a new comprehension on timezone.
