### ISSUE TITLE
About minimum session timeout

### ISSUE THREAD

**Issue by maoyuanh** [grafana/grafana#18885]
As we know,  from grafana v6.2, some options has been removed.
https://grafana.com/docs/installation/configuration/#session
For example, session_life_time
we had this configured previously to 10 minutes:
session:
  session_life_time: 600

We would like to have similar setting also now. 1 day is too long for us.
Could this be somehow archived still with new Grafana?

**Comment by xlson** [comment]
Duplicate of #17554
