### ISSUE TITLE
Datasource defaults on imported Dashboards

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#18888]
**What happened**:

I wanted to move a Dashboard from organization A to organization B. Since I am not aware of another option I exported and imported the Dashboard like this:
1. Open Dashboard
2. Click share button at the top
3. Click Export Tab
4. Enable "Export sharing for externally" (because I knew I want to use a different datasource), copy the JSON content into the clipboard
5. Switch Org
6. Import dashboard by hovering the Dashboard icon on the main menu -> Manage -> import.
7. In the next screen I was able to choose my Datasource as expected. I choose the right prometheus instance

The dashboard was imported as expected however all dashboards use the default datasource (instead of the selected datasource in step 7). If I don't have a default datasource at all it will show sample data (A-Series) in all panels.

**What you expected to happen**:

I expected that it would take my selected datasoruce from step 7 for all my panels in the imported dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

Create a single dashboard, export and import as described above and check whether the panels use the desired Datasource as selected during the import.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: Prometheus / Cortex
- OS Grafana is installed on: Standard docker image
- User OS & Browser: Max OS / Chrome

Edit:

I published three dashboards for two prometheus exporters I built and apparently this is issue occurs there. Users have reported that this is because there's no `datasource` property in the dashboard panels and they have manually edited the JSON by adding that property to all panels. Then the desired datasource (instead of the default one) is actually being used. The published dashboards:

https://grafana.com/grafana/dashboards/9871
https://grafana.com/grafana/dashboards/10083

**Comment by weeco** [comment]
@torkelo Can I provide any further information which would help to figure out the problem? I can reliably reproduce the issue on my Grafana instance/dashboard.

**Comment by torkelo** [comment]
It's related to these PanelModels defaults are removed when saving / exporting dashboard.
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/PanelModel.ts#L74

**Comment by torkelo** [comment]
that needs to be re-exported
