### ISSUE TITLE
Stackdriver: Add support for filtering, grouping and alias by on metadata labels

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#18887]
As of now, the Stackdriver datasource supports filtering, grouping and using alias by on resource labels and metric labels. However the [stackdriver metrics API](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries) also includes `metadata` which is an object that also includes labels - `user_labels` and `system_labels`. These labels might be useful in many cases, particularly when using agent metrics since they don't include instance_name as a metric label. 

It should be possible to use`metadata.user_labels` and `metadata.system_labels` for filtering, grouping and alias by. This will involve both backend and frontend work in the stackdriver datasource. 

Fixes #15552 
Fixes #18750

**Comment by igorpeshansky** [comment]
Keep in mind that only the labels that appear in the grpup-by section of the query will be returned. The user has to explicitly specify them.
It may be possible to hard-code a list of common system labels for each resource type (like `metadata.system_labels.name`) to allow users to select them from a pulldown, and add the group-by into the resulting API query.

**Comment by sunker** [comment]
Yes. Hard coding them would be one way forward.

At the moment we query the stackdriver API every time the metric type is changed in order to retrieve the labels available for that specific metric type. I was thinking we could fire off one more query and include group by aggregation for metadata.system_labels.name and metadata.user_labels.name. That way they would be fully dynamic. Or am I missing something here?

**Comment by igorpeshansky** [comment]
Unfortunately, as of today there's no way to query for the list of labels — any label in the `metadata` part of the response has to be explicitly present in the query. I'll open a feature request in the public issue tracker to allow getting the labels programmatically (and follow up here with a link), but it may be a while.

On a separate note, `metadata.user_labels.*` in the case of GCE instances are all basically user-supplied instance tags (well, key/value labels, but the conflated terminology is a bit confusing). So, unlike `metadata.system_labels.name`, `metadata.user_labels.name` would only be present if the user set the `name` tag on their instance — it's not there by default.

**Comment by sunker** [comment]
Okay. What do you suggest we do for now? Hard code `metadata.system_labels.name` and `metadata.user_labels.name` and make it possible to use for group bys and alias by?

**Comment by sunker** [comment]
@igorpeshansky what do you think about this. I make sure that if metadata labels, system_labels or user_labels, are being used in the query then these labels will work with alias by. 

Since there's no way of retrieving metadata labels programmatically from the public api right now we hard code a few system_labels and put them in the group by dropdown. In this case I need help to create of list commonly used system labels.

**Comment by igorpeshansky** [comment]
As I said [above](https://github.com/grafana/grafana/issues/18887#issuecomment-527906987), `metadata.user_labels.name` depends on user settings, and is probably pretty useless overall.

`metadata.system_labels.*` and `metadata.user_labels.*` must appear in the group-by clause in the API query for you to be able to filter on them. You should be able to hard-code the following `metadata.system_labels` names for each of the commonly used monitored resource types. Sadly, there is no way to retrieve the available `metadata.user_labels` names, so you may have to give the users some free-form input for those in addition to the pull-down for the hard-coded ones.

`gce_instance`:
- `cloud_account`
- `name`
- `region`
- `state` (`ACTIVE`/`INACTIVE`)
- `instance_group`

`k8s_container`:
- `name` (same as the `container_name` resource label)
- `node_name`
- `service_name`
- `top_level_controller_type`
- `top_level_controller_name`
- `state` (`ACTIVE`/`INACTIVE`)
- `container_image`

`k8s_node`:
- `name` (same as the `node_name` resource label)
- `state` (`ACTIVE`/`INACTIVE`)

Let me know if you plan to support more monitored resource types, and I'll gather the lists of metadata system labels for those resources.

**Comment by jwlee98** [comment]
@sunker is there any status update about this issue ?

**Comment by cbandy** [comment]
Please consider that drop-down menus are a low priority for me and a few others from #15552.

I know my custom labels and how to type/spell them for Grafana's benefit. Having those labels show on the graph is the critical part.

**Comment by jwlee98** [comment]
Is there any status update?

**Comment by jwlee98** [comment]
I didn't get any response for a long time. is there any good way to bump this issue up again ?

**Comment by sunker** [comment]
Have not had the time to work on this unfortunately, but I hopefully I will get some time next month.

**Comment by jwlee98** [comment]
@sunker 
thank you for your support. I got it...please check this issue again if you have a time next month if possible. 

Thanks,

**Comment by sunker** [comment]
I have created a [draft PR](#21373) that aims to fix this. Any chance you can help me out review and test this before merging @igorpeshansky?

**Comment by igorpeshansky** [comment]
@sunker, I'm not really equipped to test that change, but I'm happy to offer some review comments. I'll also tag one of my teammates who is more proficient in Go.

**Comment by mark-cts** [comment]
Excited to see where this goes as a very appreciated request, especially for kubernetes labels out of stackdriver. 

I'm not sure if this will be part of this PR or not but is it possible to ensure these are added appropriately (or just a free-form box) to the variables selection for K:V pairs out of SD metrics? Currently im only able to use resource labels in there due to autocomplete not taking the metrics appropriately or will this PR fix it?

Thanks and appreciate the work being put in to this!

**Comment by sunker** [comment]
@mark-cts, the group by field will have a [hard coded list](https://github.com/grafana/grafana/issues/18887#issuecomment-528526695) of SystemLabels at the very bottom of the dropdown. It will also be possible to enter a custom value in the group by field. As long as the metric that is selected supports the label in the group by field, it will be possible to filter on that label and also do alias by on that label. Was that an answer to you question? 

You can test the feature by pulling [this branch](https://github.com/grafana/grafana/tree/stackdriver-meta-labels) if you feel like.

**Comment by kabam-srayner** [comment]
Did this fix include filtering on both `user_labels` and `system_labels` also does grouping work on `user_labels` 

I ask this specifically because I don't believe either of the above work and I thought I would ask before opening an issue.

**Comment by sunker** [comment]
Yes @kabam-srayner, it should work in grafana 6.6. 

In order to be able to filter on user_labels or system_labels, you need to first group on that label. There's no api to retrieve the meta data labels, so there's no way for grafana to know what kind of label you have. However, we do suggest a couple of common system labels. If none of them are suitable, or if you'd like to use a user label, you need to specify it manually in the group by field. If that label then existed in the query result, you should be able to filter on it in the response.

**Comment by TimShilov** [comment]
Is using `user_labels` still possible? I'm on Grafana v8.1.3 and want to group metrics by custom label but Group By field not letting me enter anything, I can only choose from hard-coded items.

**Comment by joshk0** [comment]
@igorpeshansky Hello! Reviving this thread.

Regarding your post,

> Unfortunately, as of today, there's no way to query for the list of metadata labels — any label in the metadata part of the response has to be explicitly present in the query. I'll open a feature request in the public issue tracker to allow getting the labels programmatically (and follow up here with a link), but it may be a while.

First of all, is this still the case? If that's true, then could you please provide the link in Google's public issue tracker so we can follow? If this has been revised, can you provide some documentation for the new API?

Thank you so much!
