### ISSUE TITLE
Gravatar http user agent references old chrome version

### ISSUE THREAD

**Issue by IceEyz** [grafana/grafana#18889]
**What happened**:
Grafana connects to secure.gravatar.com with a HTTP User Agent referencing a very old version of Chrome.

**What you expected to happen**:
Grafana uses a distinct HTTP User Agent referring to Grafana as the user.

**How to reproduce it (as minimally and precisely as possible)**:
Enable Gravatar. Use Grafana.

**Anything else we need to know?**:
See https://github.com/grafana/grafana/blob/master/pkg/api/avatar/avatar.go#L234

Furthermore, the avatar.go module seems old. It does not allow HTTPS for using gravatar, which was fixed in a newer upstream version.

**Environment**:
- Grafana version: any
- Data source type & version: N/A
- OS Grafana is installed on: any
- User OS & Browser: any
- Grafana plugins: N/A
- Others: any

**Comment by xlson** [comment]
Not sure I see the problem of using an out of date User Agent. Have you had an problems with it? That said, we should upgrade the gravatar dependency.
