### ISSUE TITLE
Multiple depedant variables in repeated panel titles

### ISSUE THREAD

**Issue by KnpA** [grafana/grafana#18898]
**What would you like to be added**: Having multiple variables in repeated panel titles that are recalculated/depedant of the repeated variable value.

My example :
![image](https://user-images.githubusercontent.com/6367927/64270674-3ffc5680-cf3c-11e9-9141-4c1c18013468.png)

My users want to see all interfaces informations from a specific equipment (here in/out traffic)
For that, they can choose with variables the hostname and [one, multiple or all] interface descriptions.
We create with repeated panels one panel per interface description.
In our database (we use ElasticSearch), we have other fields that contains other informations (ex: interface name, operational state, etc...) and we would like to see these informations in the titles of the repeated panels but it doesn't work.
Actually, it repeats the panel and adapt the query to each interfaceDesc but other variables aren't recalculated/filtered by this value so we have All - All in each panel.
 
**Why is this needed**: It will give us the opportunity to improve our user experience by giving them more information about each graph. 

If it's not clear I can give you a complete example with detailed queries.

**Comment by torkelo** [comment]
We have no plans to do this in any near future (1-2) years, most likely never due to the complexity involved. We hope a new form of scripted dashboards could solve use cases like this.
