### ISSUE TITLE
Support the South African Rand

### ISSUE THREAD

**Issue by jeteon** [grafana/grafana#18892]
**What would you like to be added**:

I would like the South African Rand (ZAR) to be supported as a currency unit. 

**Why is this needed**:

There are Grafana dashboards I'm working on which we are using to track monetary values. Right now, we simply leave off units or use formatting to approximate displaying the units with prefixes and suffixes etc. but it's a workaround. We would like this use case to be supported in much the same way the other currencies are.

**Comment by xlson** [comment]
Thanks for contributing to Grafana.
