### ISSUE TITLE
Docs: Create redirect alias for old keyboard shortcuts docs location

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#18895]
https://grafana.com/docs/reference/keyboard_shortcuts/ is still there

https://grafana.com/docs/features/shortcuts/ should have that as an alias in the frontmatter toml

**Comment by oddlittlebird** [comment]
@torkelo , is this complete?

**Comment by oddlittlebird** [comment]
@DanCech, could you take a look at this?

**Comment by DanCech** [comment]
This issue seems to be out of date.
