### ISSUE TITLE
View Other Website in a Panel

### ISSUE THREAD

**Issue by oryagel** [grafana/grafana#1889]
Hi,

Is there a way to view another website in a panel?
Something like an iframe...
Maybe it's possible with a Text panel?

If it's not possible, I think it can be a great feature.
You can view other relevant websites that reflect the status of a service, or if the dashboard is for a website, it can even show the website itself.

Thanks

**Comment by torkelo** [comment]
The text panel supports html :)

**Comment by oryagel** [comment]
Cool, thanks.
Can I use variables inside the html text?

**Comment by torkelo** [comment]
Think so, [[varname]], and $varname   should work

**Comment by oryagel** [comment]
Thanks!
Waiting for the SaaS version :)

**Comment by torkelo** [comment]
Its coming a long :)

**Comment by ashishgopal1414** [comment]
iframes, link, and stylesheets tags are showing as plain text and not as html tags
eg.


<h2>Wind Dashboard!
<img src="https://66.media.tumblr.com/ac6a704231f6099e45790f628a175dbc/tumblr_onfa39Z64g1t2kke2o1_r1_400.gif" alt="" height="100" width="100">
<h3>Wind Analysis</h3></h2>
<iframe  width="1280" height="800"  src="http://localhost:5006/wind_dash"></iframe>


here the iframe tag shows as plain text, but if i normally save the same text as .html, i can see the plot in browser.

Am i missing something??

![grafana html](https://user-images.githubusercontent.com/36658472/65351021-aa7fe880-dc04-11e9-8751-2e4b066e9d0e.PNG)

**Comment by marefr** [comment]
@ashishgopal1414 Grafana per default doesn't allow script tags in text panels. You can change that using this [setting](https://grafana.com/docs/installation/configuration/#disable-sanitize-html) but please note that it have security implications.
