### ISSUE TITLE
Make Backend SQL Migration More Robust 

### ISSUE THREAD

**Issue by lm123** [grafana/grafana#18906]
**What happened**:

During Grafana startup, data migration might meet the following race condition:
- ALTER TABLE `dashboard_provisioning` RENAME TO `dashboard_provisioning_tmp_qwerty succeeds 
- But writing the log entry into migration_log (66|Rename table dashboard_provisioning to dashboard_provisioning_tmp_qwerty - v1|ALTER TABLE `dashboard_provisioning` RENAME TO `dashboard_provisioning_tmp_qwerty`|1||xxx) is not successful

When Grafana restarts, Grafana cannot proceed because of failure when redoing the above migration.

Grafana shall provide one graceful recovery mechanism to cover the above rainy scenario.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: MariaDB
- OS Grafana is installed on: CentOS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
@torkelo  We already have an issue for improving database migrations #11090
