### ISSUE TITLE
Incorrect time range in request on browser incorrect time

### ISSUE THREAD

**Issue by pinguini** [grafana/grafana#18907]
current_time=14:00
browser_time=13:30
alert_time=13:58

time range in grafana dashboard set to "Last 15 min"
grafana will request range from 13:15  to 13:30
grafana will not display ALERT (from prometheus or another backend)
grafana will not display any really last metrics (from prometheus or another backend)

Expected on request "Last 5min" ( all "Last .*") got answer with grafana's server time/

Reproduce:
Shift time on local machine.

On dashboard loading set any variable like server_time and synchronize it with browser local.

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: prometheus 2.3.2
- OS Grafana is installed on: Linux official docker
- User OS & Browser: Fedora linux & firefox

**Comment by torkelo** [comment]
This is super strange, you will have to provide detailed request logs (use query inspector) to show time range filters

**Comment by torkelo** [comment]
Just tested this and Grafana is sending the correct time range in UTC. So Last 5m time range is always sent in UTC and will always get the latest data from Prometheus. 

Check time settings on your prometheus server?

**Comment by pinguini** [comment]
1) server time 1567669221000 "Чт сен  5 10:40:21 MSK 2019"
2) local time 1567668746000 "Чт сен  5 10:32:26 MSK 2019"
3) grafana dashboard time range set to "Last 5 min"
4) grafana request parameters is from=1567668452599&to=1567668752599


for eye-friendly - remove first 156766. 
so : 

1) server time 9221000
2) local time 8746000
4) from 8452599 to 8752599 

server time is synchronized with NTP and perfectly
local PC time is in past 9221000-8746000=475000 ms (7.9 min)
grafana request from  8452599  to 8752599, but 
server time - grafana_TO_time : 9221000 - 8752599 = 468401 (7.8 minut)
 
Grafana request metrics from past time and present it as last 5 min.

**Comment by pinguini** [comment]
![изображение](https://user-images.githubusercontent.com/5128663/64331090-5e298b80-cffc-11e9-8b18-be19292f6b31.png)
Prometheus alert me if local PC and browser has wrong time.

**Comment by pinguini** [comment]
still need more details ?

**Comment by torkelo** [comment]
Sounds like your PC (browser) has wrong time configured :)  

Do you want Grafana to add a similar alert to what Prometheus has?

**Comment by pinguini** [comment]
Yes need to inform users that local PC time is wrong configured.

**Comment by rthamrin** [comment]
happen to me, I have no idea what to do. i do install NTP , change the timezone
