### ISSUE TITLE
Google: OAuth2 is not working

### ISSUE THREAD

**Issue by mmogylenko** [grafana/grafana#1890]
**Summary:**
After Permissions Request confirmation (on Google side), Google API redirects to domain.com/login page without any authentication. Redirect URL set to domain.com/login/google as per [Documentation](http://docs.grafana.org/installation/configuration/).

*Configuration File:*
```
# This file is managed by Puppet, any changes will be overwritten

app_mode = development

[server]
http_port = 8080
domain = grafana.somedomain.com
root_url = %(protocol)s://%(domain)s/
router_logging = true
[database]
type = sqlite3
#host = 127.0.0.1:3306
name = grafana
#path=/var/lib/grafana/grafana.db
#user = root
#password =

[users]
allow_sign_up = false
#auto_assign_org = true

[auth.anonymous]
enabled = true
org_name = Test

[auth.google]
enabled = true
client_id = *******
client_secret = *******
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
#api_url = https://www.googleapis.com/oauth2/v1/userinfo
allowed_domains =
#allowed_domains = somedomain.com
#allow_sign_up = false

[log]
mode = console, file
level = Trace


[log.file]
level = Trace
```
*Logs:*
```
2015/04/27 12:11:56 [I] Starting Grafana
2015/04/27 12:11:56 [I] Version: 2.0.3-pre1, Commit: v2.0.2+3-g2c52224, Build date: 2015-04-23 06:24:30 +0000 UTC
2015/04/27 12:11:56 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/04/27 12:11:56 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/04/27 12:11:56 [I] Migrator: Starting DB migration
2015/04/27 12:11:56 [I] Listen: http://0.0.0.0:8080
2015/04/27 12:12:10 [I] Completed /login/google 302 Found in 2.071938ms
2015/04/27 12:12:19 [T] login.OAuthLogin(Got token)
2015/04/27 12:12:25 [T] login.OAuthLogin(social login): &{109442592791975073330 Mykola Mogylenko mmogylenko@gmail.com  }
2015/04/27 12:12:25 [I] Completed /login/google 302 Found in 11.786883025s
```

**Steps to Reproduce:**
1. Install Grafana 2.0.x
2. Configure Project/Credentials in [Google Developer Console](https://console.developers.google.com), with correct Redirect URIs
3. Try to login with Google Account (both variants, with domain restriction and without).

**Versions affected:** 2.0.1, 2.0.2, 2.0.3-pre1

**Comment by torkelo** [comment]
It works on http://play.grafana.org and my local machine. Bust be something wrong with your [server] domain setting or your [server] root_url setting

domain = grafana.somedomain.com
root_url = %(protocol)s://%(domain)s/

This will generate a request to googe to redirect to http://grafana.somedomain.com/login/google  

When you browse to your grafana weberser do you use http://grafana.somedomain.com ? (or equivalent , guess you have some other domain and did not want to write the real one here) 

You have specified port 8080 but that is not in the roo_url, do you have an nginx infront?

**Comment by mmogylenko** [comment]
1. Yes, Apache2 is proxying to 8080 port
2. I've removed port from root_url since it sends it in request header to Google API, which leads to **redirect_uri_mismatch**
3. The same for *domain*. If you're not specifying domain in */etc/grafana/grafana.ini* it takes it from */usr/share/grafana/conf/defaults.ini* and also causing **redirect_uri_mismatch** Error.

Just tried with different Google accounts to login to play.grafana.org and got the same situation. (checked in Firefox and Chrome).

Thanks.

**Comment by torkelo** [comment]
So what happens after you try to login (or after google redirects you back to grafana)?

**Comment by torkelo** [comment]
Have you disabled cookies?

**Comment by torkelo** [comment]
Think I know the issue here, you have allow_sign_up = false  (default value is false, I thought this was true). It seems to be the issue with play.grafana.org as well

**Comment by mmogylenko** [comment]
Right after confirming permissions and redirect, I'm seeing again login page. Cookies enabled. 
Several people tried to login to play.grafana.org and got the exactly the same (returned back to grafana login page).

**Comment by mmogylenko** [comment]
Confirming,

adding *allow_sign_up = true* in section **[auth.google]** solved problem.

Thanks @torkelo
