### ISSUE TITLE
Templates in repeating rows

### ISSUE THREAD

**Issue by evfool** [grafana/grafana#18908]
**What would you like to be added**:
When using the Repeat row for VARIABLE feature, it would be nice to be able to use templates with variables (only the variable selected in the "Repeat for" combo) in the row name.

E.g. having a variable *node* with a multiple selections (e.g. 10 possible values), with a Repeating row entitled with *Quick view* it can be confusing to have 10 Quick view rows.

**Why is this needed**:
To be able to quickly check which values the repeating row you are looking at stands for. Of couse, you can always check the labels inside the chart inside the row to see it, but it would be easier and better to have it in the title instead of having the same hard-coded title repeat N times.

**Comment by torkelo** [comment]
just use the repeat for variable in the row title. 

example: https://play.grafana.org/d/000000153/repeat-rows?orgId=1&var-app=backend&var-app=fakesite&var-server=backend_01&var-server=backend_03&var-server=backend_04&var-interval=$__auto_interval_interval

**Comment by evfool** [comment]
Thanks for the information, not sure howcome I didn't find that option.
