### ISSUE TITLE
Provisioning dashboard with rawsql failes

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#18905]
I've exported a dashboard from my local grafana and added it to a docker grafana `grafana/grafana:latest` (6.3.3) using provisioning.

When starting up grafana I get the following error:
`lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name="provider" file=/etc/grafana/provisioning/dashboards/dashboard_1.json error="invalid character '\\n' in string literal"`

The newline character is found in `rawSql` field of the exported dashboard, ex:
`"rawSql": "SELECT\n  count(id) AS \"idc\"\nFROM table",`

Exported dashboard json should be compatible with provisioning importing.

**Comment by torkelo** [comment]
Can you include your full json file?

**Comment by cdalexndr** [comment]
Actually the issue is from build resource processing.
Applying gradle copy task with expand tranforms "\n" into newlines resulting in an invalid json.
Opened [gradle issue](https://github.com/gradle/gradle/issues/10458)
