### ISSUE TITLE
Constant Variable Should Never Be in Current

### ISSUE THREAD

**Issue by kustodian** [grafana/grafana#18916]
**What happened**:
If you create a constant variable its value is still saved in current variable values (or hower are those called), so when you change the constant value, that value isn't changed in current var values after a save if `Save current variables` isn't selected. It's not intuitive that constants are saved in current and just complicates things. The "fix" of selecting `Save current variables` when saving a dashboard is far from intuitive as well.
Constants shouldn't have current variable values and they should always use the value that is specified in the variable itself.

**What you expected to happen**:
When I change the value of a constant it should instantly change and work after saving a dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Create a constant, set some value and save the dashboard selecting `Save current variables`. Use that variable somewhere that you can see it on the dashboard, e.g. in a title of a graph. Now change the value of that constant and save the dashboard again without selecting `Save current variables`. Refresh the dashboard from a browser (F5) and the variable value which is saved in the var won't be used, but the value saved in current.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: N/A
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Linux/Firefox
- Grafana plugins:
- Others:

**Comment by kustodian** [comment]
Yes. It's still relevant.

**Comment by hugohaggmark** [comment]
@kustodian thank you for taking the time to write this excellent issue.
