### ISSUE TITLE
Same Query and Different Results - Bug

### ISSUE THREAD

**Issue by Shreepal07** [grafana/grafana#18911]
I'm using grafana with elasticsearch data source. Query is kind of same but I get different results.

Query 1.) 
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"itops_skyhigh_incidents_compliancepercentage"}		{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"itops_skyhigh_incidents_compliancepercentage"}
{"size":0,"query":{"bool":{"filter":[{"range":{"Registered Time":{"gte":"1567641600000","lte":"1567727999999","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"xxxx AND (yyyy)"}}]}},"aggs":{"3":{"terms":{"field":"Status.keyword","size":500,"order":{"_term":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"1d","field":"Registered Time","min_doc_count":1,"extended_bounds":{"min":"1567641600000","max":"1567727999999"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"Percentage"}}}}}}}}

Query 2.) 
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"itops_skyhigh_incidents_compliancepercentage"}
{"size":0,"query":{"bool":{"filter":[{"range":{"Registered Time":{"gte":"1567641600000","lte":"1567727999999","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"xxxx AND yyyy"}}]}},"aggs":{"3":{"terms":{"field":"Status.keyword","size":500,"order":{"_term":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"1d","field":"Registered Time","min_doc_count":1,"extended_bounds":{"min":"1567641600000","max":"1567727999999"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"Percentage"}}}}}}}}

Both queries is auto generated by Grafana and gives different results.

Is there any difference in both the queries or is it some issue with Grafana?

**Comment by torkelo** [comment]
<img width="1100" alt="Screen Shot 2019-09-06 at 10 02 10" src="https://user-images.githubusercontent.com/10999/64411437-70073f00-d08d-11e9-8476-c77cf1ab07e6.png">

your Lucene query is different, maybe Elasticseach handles them differently?
