### ISSUE TITLE
IPv6 Truncation

### ISSUE THREAD

**Issue by 62726164** [grafana/grafana#18924]
Bug: 

Grafana truncates one doctet from IPv6 addresses in the Profile -> Sessions view.

What do you expect: 

I expect to see the full IPv6 address, not just the first seven doctets.

How to reproduce the bug:

1. Login to Grafana as a normal user using an IPv6 address.
2. View https://your.grafana.url:3000/profile to see the missing doctet.

Pictures of the bug:

![ipv6](https://user-images.githubusercontent.com/9010108/64347281-a2e40100-cfc1-11e9-8837-b9d51e1b122e.png)
![ipv6-2](https://user-images.githubusercontent.com/9010108/64347543-1dad1c00-cfc2-11e9-9b3b-976438058f47.png)

Misc:

- Grafana version: Grafana v6.3.5 (commit: 67bad72)
- Data source type & version: N/A
- OS Grafana is installed on: Debian Linux 9
- User OS & Browser: Ubuntu/Debian FireFox and Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment]
IP address is parsed here when creating a new token: https://github.com/grafana/grafana/blob/0ec83038783ba73d410fda74bd34c642906bb1a7/pkg/services/auth/auth_token.go#L58

Parsing of IP address is done here: https://github.com/grafana/grafana/blob/master/pkg/util/ip_address.go
