### ISSUE TITLE
[FeatureRequest] DashboardLinks: Support Template variables

### ISSUE THREAD

**Issue by pacEPMS** [grafana/grafana#18928]
How can I use template variables in dashboard link (tag field) ?
Example: dashboard variable $Area to select via combobox.

dashboard link tag field -> var-Area

Thanks for help.

**Comment by apexskier** [comment]
I'm looking for this as well. Here's a screenshot, for clarity:

<img width="393" alt="Screen Shot 2020-04-10 at 08 31 05" src="https://user-images.githubusercontent.com/329222/78968825-d19cf980-7b05-11ea-8fad-b00081b8ece7.png">

Similar to #23303

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
