### ISSUE TITLE
Prevent Viewer from seeing plugins list

### ISSUE THREAD

**Issue by pcsegal** [grafana/grafana#18927]
**What would you like to be added**:

When I log in as a user that only has Viewer permissions, it's possible to access the Plugins list from the Configuration menu to the left. I'd like it to be possible to hide the Plugins list from Viewer users.

**Why is this needed**:

When the user is only a viewer, the plugins list is not useful for them, and its presence can be confusing.

**Comment by enotanet** [comment]
This is not feature but obvious BUG. Information disclosure for unauthorized user.

**Comment by supportdesk-si** [comment]
This is a huge issue.  We are releasing dashboards to a group of users who should not see at any point in time.  100% agree with @enotanet

**Comment by rmunoz10** [comment]
+1

**Comment by logiserv** [comment]
Viewers should not access Configuration-Plugins and Share Dashboard

**Comment by aciccioli** [comment]
Hello.
Any workarround about this issue ??

**Comment by enotanet** [comment]
Seems like dead project or they are working for corp users.

**Comment by torkelo** [comment]
Why would not Corp user care about this?

**Comment by enotanet** [comment]
No money - no attention. Nobody what to care for sake other for free.

**Comment by rheddi02** [comment]
Any news about this bug?

**Comment by torkelo** [comment]
Hope to fix this soon

**Comment by rheddi02** [comment]
For the moment I have this alternative. If ever needed some temporal solution.

![plugin](https://user-images.githubusercontent.com/52489010/73590651-e797a800-451f-11ea-8c74-f71cfdfaa3c6.png)

**Comment by dprokop** [comment]
> Seems like dead project or they are working for corp users.
> No money - no attention. Nobody what to care for sake other for free.

@enotanet sorry to hear such opinion. We gonna take care of this issue soon. Also, please remember that Grafana is an open source project and we always welcome external contributions with open hands :)

**Comment by maufc** [comment]
> For the moment I have this alternative. If ever needed some temporal solution.
> 
> ![plugin](https://user-images.githubusercontent.com/52489010/73590651-e797a800-451f-11ea-8c74-f71cfdfaa3c6.png)



> For the moment I have this alternative. If ever needed some temporal solution.
> 
> ![plugin](https://user-images.githubusercontent.com/52489010/73590651-e797a800-451f-11ea-8c74-f71cfdfaa3c6.png)

@rheddi02 what is the file you are editing and what is the route to it?
Thansk!
