### ISSUE TITLE
Alert panel resent state changes not display when timerange is “today”

### ISSUE THREAD

**Issue by pacEPMS** [grafana/grafana#18929]
**What happened**:

Problem:
I placed an alert panel on a dashboard and set the dashboard timerange to “today”.
There were no resent alert changes displayed in the panel.
If I set the dashboard timerange to "02.09.2019 00.00.00 to 02.09.2019 23:59:59"
ordr "last 24h", resent alert changes items are displayed.
I think the timerange “today” filter doesn’t works.

**What you expected to happen**:
display resent alert changes items

**How to reproduce it (as minimally and precisely as possible)**:
Set the dashboard timerange to "02.09.2019 00.00.00 to 02.09.2019 23:59:59"
ordr "last 24h"

**Anything else we need to know?**:
no

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: ARMV7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
unable to replicate https://play.grafana.org/d/000000074/alerting?orgId=1&from=now%2Fd&to=now%2Fd

shows alert annotation events in the graph in the lower right. 

Can you include network traffic (requests) ?

**Comment by pacEPMS** [comment]
see attached screenshots.
I had alerts today 08:00pm and yesterday.
Timerange "Last 2 day" -> alerts today and yesterday are listed
Timerange "Today" -> no alerts are listed

Why ?
![AlertList Setting](https://user-images.githubusercontent.com/52577036/64414348-78fb0f00-d093-11e9-95f3-d177be93dcaa.png)
![Alerts Last 2 day](https://user-images.githubusercontent.com/52577036/64414349-78fb0f00-d093-11e9-9f09-9ab6277cd4ba.png)
![Alerts Today](https://user-images.githubusercontent.com/52577036/64414350-78fb0f00-d093-11e9-87ac-00599c02a243.png)

**Comment by MalickBurger** [comment]
I believe there is a misunderstanding regarding this, I am experiencing the same as the author and when I attempt to replicate the issue on the Grafana playground https://play.grafana.org/d/000000074/alerting?orgId=1&from=now%2Fd&to=now%2Fd I experience the same problem. @torkelo If you set the alert panel in the top right to display "Recent State Changes" And you set the time-picker to "Today" (which is default when i follow the link) then you will see that no recent changes show in the alert panel, but if you change the time-picker to display a different range such as "Today so far" then the recent changes show up in the panel.

![image](https://user-images.githubusercontent.com/30129042/65686019-aff58c80-e063-11e9-8112-1554114a374a.png)

![image](https://user-images.githubusercontent.com/30129042/65686032-b6840400-e063-11e9-9aa4-4baa352f8113.png)
