### ISSUE TITLE
Display data based on string pattern matching on template variable dropdown in table panel

### ISSUE THREAD

**Issue by SwathiMuppalla** [grafana/grafana#18925]
Grafana Version: 6.2.5
Elastic search
I have logs data with pattern `ERR`,`INFO`,`DEBUG`
Example `data_ERR_notconnected`, `sys_INFO_connected`, `sys_DEBUG_network`
I am trying to create template variable for ‘marker’ with variable dropdown as ERROR,INFO,DEBUG. So when ERR is clicked from dropdown only error based data is displayed in table format panel. The data i have is huge and i have index name marker with all the data.
![Screenshot (38)](https://user-images.githubusercontent.com/22199547/64268068-723e9180-cf05-11e9-9e2f-80ec6b87017e.png)
![Screenshot (41)_LI](https://user-images.githubusercontent.com/22199547/64268105-7e2a5380-cf05-11e9-8285-f33d43d25567.jpg)

I am using regex as `/.*(ERR|INFO|SH)/` but i dont see any change in response. Any idea would be helpful? @torkel @daniellee @marefr

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Not sure what the problem is, is it the regex itself or using the resulting variable in query in panel?
