### ISSUE TITLE
Loading custom metrics (telegraf) for azure monitor

### ISSUE THREAD

**Issue by iisayboom** [grafana/grafana#18939]
**What happened**: 
No 'metric namespace' dropdown appearing

**What you expected to happen**: 
When adding azure monitor as a datasource, the 'metric namespace' option should be available regarding to PR -> https://github.com/grafana/grafana/pull/17282

**How to reproduce it (as minimally and precisely as possible)**:
- Set up a azure virtual machine (Ubuntu 16.04) -> other specs don't really matter
- Create azure service principal for RBAC control -> az ad sp create-for-rbac --name yourServicePrincipalName
- Give 'Contributor' role for testing to the Service principal towards the subscription it is running on -> az role assignment create --scope "/subscriptions/subscription_id" --assignee "appID" --role "Contributor"
- Install telegraf on the vm -> https://docs.microsoft.com/en-us/azure/azure-monitor/platform/collect-custom-metrics-linux-telegraf
- Install grafana on the vm -> https://grafana.com/docs/installation/debian/

**Anything else we need to know?**: There is no security issue as far as I know since we are able to get the metrics of the vm directly. We just can't get any custom defined metrics with telegraf while the telegraf metrics are shown in azure monitor.

**Environment**:
- Grafana version: Grafana v6.3.5
- Data source type & version: Azure monitor
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOs, Chrome
- Grafana plugins:  Azure monitor
- Others:

**Comment by papagian** [comment]
There is a fix for this available in nightly version and will be included in the next beta this/next week.
