### ISSUE TITLE
Templating: Clicking Selected should deselect all if 1 or more are already selected 

### ISSUE THREAD

**Issue by heyrod** [grafana/grafana#18938]
**What happened**:
When I click 'Selected', all variables are selected in a dropdown list. 
![issue](https://user-images.githubusercontent.com/39294778/64412962-4227f780-d099-11e9-8016-ca7da26adc57.png)

**What you expected to happen**:
In earlier versions of Grafana, 'Selected' was used only to clear selection to '0' items. And it was possible to allow one-click selection of all items in the list by adding 'All' option in a variable settings. 

**How to reproduce it (as minimally and precisely as possible)**:
In a dropdown list for any variable click 'Selected'.

**Anything else we need to know?**:
I consider this a serious issue because selecting (by accident or intentionally) a huge amount of items in a query to a data source can kill it. In our instance of Grafana, we enable 'All' option only for safe variables (for example, hosts, groups, etc.). That way we were able to protect data source from actions that could cause its performance degradation or even a crash.
 
**Environment**:
- Grafana version: 6.3.4
- Data source type & version: any
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 Pro, Chrome  76.0.3809.132 (Official Build) (64-bit)
- Grafana plugins: Zabbix plugin
- Others:

**Comment by torkelo** [comment]
Unable to replicate. 

If I have anything selected already this option will clear all selections. 

https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&var-app=backend&var-server=backend_01&var-server=backend_02&var-interval=1h

**Comment by heyrod** [comment]
Hi,
It works the following way:

- If there is 1 item selected, clicking 'Selected' will select all.
- If there are more than 1 item selected, clicking 'Selected' will clear selection to '0'.
- If there are '0' items selected, clicking 'Selected' will select all.

If necessary, I can provide a video capture to confirm it.

**Comment by torkelo** [comment]
Ok, if only 1 selected it should still clear

**Comment by heyrod** [comment]
Could you confirm that it's a bug? I need to send a heads-up message for end users.

**Comment by torkelo** [comment]
yea, it's a bug
