### ISSUE TITLE
Multiple left y axes with different scales

### ISSUE THREAD

**Issue by ebereketoglu** [grafana/grafana#1893]
Is there any option to add multiple left y axes with different scales to graph?

![flot_multiple_y](https://cloud.githubusercontent.com/assets/10550625/7350988/c10380e6-ecbf-11e4-9893-313f6e68abe1.PNG)

**Comment by torkelo** [comment]
no, one left and one right y axis is supported

**Comment by sgarg7** [comment]
@torkelo 
Can we have this as a feature, pretty please? Sometimes, we need to plot 3 different units on a chart. With only one left and one right axis, this is not possible.

**Comment by cicciopizza** [comment]
It would be a good feature

**Comment by codeaholics** [comment]
+1

**Comment by adrian-dinu** [comment]
+1

**Comment by Dill0r** [comment]
show stopper that this is missing +1

**Comment by Abromeit** [comment]
+1

**Comment by hbh7** [comment]
+1

**Comment by DaveFV91** [comment]
+1

**Comment by schiphol100** [comment]
Same here ... it happens really often to plot multiple variables within different axis. Hope it can soon be implemented!

**Comment by tmulzer** [comment]
At me it doesn’t happen often, but if it happens... +1!
4 of 4 other graphing solutions, I use do support multiple axes.

**Comment by GlobularSet** [comment]
I also have multiple use cases for more than 2 axes at different scales, would really appreciate this feature.

**Comment by DutchmanNL** [comment]
Same Here +1

**Comment by PackElend** [comment]
same here. That it a reason why my company decided against it and goes now with a commercial product

**Comment by junhui** [comment]
same here +1

**Comment by Orfait** [comment]
same for me +1

**Comment by Aqueum** [comment]
+1

**Comment by ratiomatic** [comment]
+1

**Comment by Vedeneb** [comment]
+1

**Comment by wollud1969** [comment]
+1

**Comment by EvgenyG1** [comment]
+1

**Comment by schnoellm** [comment]
+1

**Comment by dwm66** [comment]
+1

**Comment by your0mind** [comment]
+1

**Comment by Technoguyfication** [comment]
Would love this feature

**Comment by Crashtein** [comment]
> Would love this feature

Me too! I wonder why it is still not implemented! I would truly appreciate this option.

**Comment by veesahni** [comment]
+1

We have many services, each with their own dedicated dashboards.  It would be nice for our "Home" dashboard to have 1 chart per service, graphing a handful of key metrics each with their own scale.   The goal here is to provide a quick visual that a human could use to say "something is not right on this one" and use that as a starting point to dig deeper.

**Comment by Puude** [comment]
Here the same.

**Comment by towingie** [comment]
+1, number of cases where need more than 2

**Comment by ashaffer** [comment]
+1 on this

**Comment by fraxinas** [comment]
+1

**Comment by sergiodegrazia** [comment]
+1

**Comment by frogale** [comment]
+10 it is a must..

**Comment by bob454522** [comment]
same , would love this as we use PRTG which supports several Y-Axis.  thanks, love grafana!!

**Comment by sandonet13** [comment]
+1

**Comment by Moosetracks555** [comment]
+1 I really need this!

**Comment by louloizides** [comment]
+1, would be extremely helpful

**Comment by PackElend** [comment]
there is an alternative but UI is still missing. 

You could use `3D.js` as described in [Learn Grafana: How to build a scatter plot plugin in Grafana 7.0 | Grafana Labs](https://grafana.com/blog/2020/06/24/learn-grafana-how-to-build-a-scatter-plot-plugin-in-grafana-7.0/ ) there is another tutorial, see [Build a panel plugin with D3.js | Grafana Labs](https://grafana.com/tutorials/build-a-panel-plugin-with-d3/#1) but that might be still buggy, see [Build a panel plugin with D3.js not working - Development - Grafana Community](https://community.grafana.com/t/build-a-panel-plugin-with-d3-js-not-working/29692).

You may also use `three.js`, see [grafanaplus/grafana-3d-panel: three-js base](https://github.com/grafanaplus/grafana-3d-panel)

**Comment by JayVee2** [comment]
+1
Used to show an on/off status with a background color. If the scale of the right y-axis is known I can easily solve this by scaling my values accordingly. But with autoscale?

**Comment by Matthias-O** [comment]
+1, multiple (not limited) y-axis would be extremely helpful!

**Comment by vincent1890** [comment]
+1 for multiple axes Y

**Comment by leeoniya** [comment]
https://github.com/grafana/grafana/issues/7397#issuecomment-732386544

**Comment by andi98** [comment]
+1

**Comment by king-brave-github** [comment]
+1 multiple axes Y

**Comment by leeoniya** [comment]
this is now available in 7.4+ in the new Time series panel.

**Comment by tmulzer** [comment]
Sounds great! ;)

Kind regards
Tasso

Am 22.02.2021 um 17:54 schrieb Leon Sorokin <notifications@github.com>:

﻿

this is now available in 7.4+ in the new Time series panel.
