### ISSUE TITLE
Click on nested dashboard should show siblings

### ISSUE THREAD

**Issue by patrickjuchli** [grafana/grafana#18935]
**What would you like to be added**:

There is a breadcrumb-style navigation at the top left. It shows me what dashboard I'm looking at and I can use it to navigate as well. If I'm currently at a dashboard that is within a folder, this might look as follows: MyFolder > MyDashboard.

Current behavior: When I click on "MyDashboard", I see the navigation window showing all dashboards and folders that exist. When clicking on "MyFolder" I get the navigation window showing only dashboards of this folder.

I'm confused by this, I would have expected it to be the other way around. "MyDashboard" is one layer deeper than "MyFolder". Clicking on it should show its siblings: Other dashboards on this level. Clicking on "MyFolder" should also show its siblings: Other folders/dashboards/anything on this higher level. I'm not sure what the thinking is behind showing all dashboards when clicking on a nested one.

**Why is this needed**:

In my use case, folders represent whole micro-grid systems that are fairly unique from one another. Within such a folder we have multiple dashboards describing the system. When I click on such a detail/dashboard title of a system in the navigation, I expect to stay within the system and see other available details/dashboards for it. When I click on the name of the system (=the folder) I expect to see other systems (=other folders, or just everything).

**Comment by torkelo** [comment]
Agree this is backward, it was changed after receiving feedback that only showing siblings as the default was not what you usually wanted (maybe you wanted to access recent or started) .

But I think the current solution is backwards. Maybe if we added recently & starred to the "folder:current" filter as well.  we could change it .
