### ISSUE TITLE
missing point on charts

### ISSUE THREAD

**Issue by greggyNapalm** [grafana/grafana#1894]
Hi All, thx for for Your job. I have a problem with 2.0.0-beta1, some points, which I can access via graphite API, missing on charts. For example, request copied from browser dev tools:
```sh
$ curl 'https://graphite.domain/render' -H 'Origin: https://grafana.domain' -H 'Accept-Encoding: deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://grafana.domain/dashboard/db/sandbox' -H 'Connection: keep-alive' --data $'target=alias(search.sessions.total_cnt%2C%20\'total%20session%20count\')&target=alias(search.sessions.total_cnt_null%2C%20\'success%20sessions%20count\')&from=1428935089&until=1430144809&format=json&maxDataPoints=1912' | python -mjson.tool | grep '616\.0'
```
returns:
```json
            [
                616.0,
                1430109180
            ],
```
so, graphite returns data as well, but I can't fond this point on the chart(see screenshot)
![2015-04-27 21-02-52 skitch](https://cloud.githubusercontent.com/assets/1364775/7354026/ca8f1d44-ed20-11e4-9716-48fdb1dcd064.png)

Prev and next hour displays well, without any problem.
Any ideas or suggestions. may be I'm doing something wrong?

**Comment by torkelo** [comment]
whats the maxDataPoints parameter that Grafana sends? Can you see the point in chrome dev tools in the response from graphite?

**Comment by torkelo** [comment]
also try disabling the other series (makes troubleshooting easier, and enable Points in display style)

**Comment by greggyNapalm** [comment]
maxDataPoints=1912 in the form-data of HTTP POST req. Yes I can found my point in JSON resp body.
![2015-04-27 21-34-17 skitch](https://cloud.githubusercontent.com/assets/1364775/7354609/30cecbe6-ed25-11e4-83ce-a307b933036c.png)

Enabling points on chart helps to debug, thanks for advice.

**Comment by torkelo** [comment]
Can you show the json response in chrome dev tools and not from curl? and only one series? (could be that the other series is null for that point if you have stacking enabled). What is your null point mode option (in display styles tab)

**Comment by greggyNapalm** [comment]
I'm sorry, that was bug in my graphite client, point present but in other time slot.
