### ISSUE TITLE
Alerting: Notification should be sent when state changed from no_data -> pending -> ok 

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#18940]
**What happened**:
We need to support the scenario described [here](https://github.com/grafana/grafana/issues/17780#issuecomment-509554611) when the `no_data` state will never cleared by an ok-message when For is used.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert rule that passes from the following states: `no_data` -> `pending` -> `ok` similar to the following scenario. An OK notification should be sent but it is not.
<img width="1166" alt="Screenshot 2019-09-06 at 13 51 27" src="https://user-images.githubusercontent.com/1632407/64429652-20416b80-d0bf-11e9-8e19-89d13cca3dfe.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
Not sure issues exist for these, but related - Keep State (either error, or no data) with Pending has the potential to stay stuck in pending I think:

https://gist.github.com/kylebrandt/3074065e35489f783fe3b0928fef06f4

Basically Rows 38 and 44 (If I modeled this correctly, tests snippets in gist seem to suggest such):

![image](https://user-images.githubusercontent.com/1692624/108124091-c6dfb900-7074-11eb-9199-63f808e92604.png)
