### ISSUE TITLE
JSON Model Documentation

### ISSUE THREAD

**Issue by Mrngilles** [grafana/grafana#18946]
**What would you like to be added**: Documentation for the different versions of the JSON model.

**Why is this needed**: This would help people developing dashboards generators (ex: grafanalib) keep their libraries up to date. 

I can start working on documenting the latest model. I see that there is a part of it at https://grafana.com/docs/reference/dashboard/ but it seems incomplete to me.

**Comment by Mrngilles** [comment]
Do you guys want me to get started on this documentation ?

**Comment by torkelo** [comment]
Yes! Improvements to the docs are greatly appreciated !!

**Comment by oddlittlebird** [comment]
What is the status of this project?

@marcusolsson , is this related to what you are doing?

**Comment by Mrngilles** [comment]
Sorry, I did not take the time to work on this, and I don't really know when I will.

You can close the issue if you want to cleanup, and I'll open it up again if I get some documentation written.
