### ISSUE TITLE
Time range selector doesn't work in IE

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#18952]
**What happened**:

In Grafana version 6.3.5 the selector for the time range was changed - it is now like a dropdown listbox. This does not work on IE - clicking the control clears the screen and nothing can be selected. This problem exists only in IE - the selector works fine in all other browsers, including Edge.

**What you expected to happen**:

I expect the selector to be functional.

**How to reproduce it (as minimally and precisely as possible)**:

Open any dashboard and try to change the time range (e.g., to "last 24 hours" or anything else).

**Anything else we need to know?**:

Not sure if related, but the list of installed plug-ins is not scrollable in IE, either - only the first screenful of them can be seen. Is IE supported at all?

**Environment**:
- Grafana version: v6.3.5 (67bad72)
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu Linux 16.04
- User OS & Browser: Win7 Pro 64-bit, IE 11.0.9600.19080
- Grafana plugins: Several, hard to list, not relevant
- Others:

**Comment by torkelo** [comment]
Adding this to our IE11 support issue (IE11 is not supported right now) 
https://github.com/grafana/grafana/issues/15754
