### ISSUE TITLE
Support for logging in JSON format

### ISSUE THREAD

**Issue by omerlh** [grafana/grafana#18957]
**What would you like to be added**:
Write grafan logs in JSON format instead of strings.

**Why is this needed**:
Make it easier to parse them by tools like fluentd, allowing features like filtering logs (collecting only errors/warnings) and monitoring (e.g. alert if there are too many error logs.

**Comment by torkelo** [comment]
Already supported:

from example config:

```ini
# For "file" mode only
[log.file]
# log line format, valid options are text, console and json
format = text
```

just uncommend format line and change to json

**Comment by omerlh** [comment]
Is there something similar for stdout logs? Not sure fluentd on k8s can collect logs from files

**Comment by marefr** [comment]
@omerlh See https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L486 

You can use format `json` for `[log.console]`

**Comment by omerlh** [comment]
thanks!
