### ISSUE TITLE
On Grafana alertmanager dashboard, severity value is shown as "-" 

### ISSUE THREAD

**Issue by jiantaoz** [grafana/grafana#18965]
**What happened**:
On prometheus alertmanager, there are alerts, severity values are "MINOR".
On Grafana, set datasource is prometheus alertmanager, create a dashboard to show alerts got from alertmanager. Alerts are shown, but severity values are "-".

**What you expected to happen**:
On Grafana, in alerts table, severity values are the same with those on alertmanager, not "-".

**How to reproduce it (as minimally and precisely as possible)**:
1. On Prometheus, there are pre-defined rules, including "severity: MINOR", "severity: MAJOR", "severity: CRITICAL".
2. Triger alerts, there are alerts shown on alertmanager.
3. On Grafana, set datasource is prometheus alertmanager, create a dashboard to show alerts got from alertmanager. Alerts are shown, but severity values are "-".

**Anything else we need to know?**:
I also modified Prometheus pre-defined rules  severity value to number, such as "3".
Triger alerts, on Grafana, Alerts are shown, severity values are "3". That's correct.
So, I guess severity values only support number, not support string, need to enhance.

**Environment**:
- Grafana version: v6.2.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: prometheus alertmanager v0.0.7
- Others:

**Comment by papagian** [comment]
Do you use [grafana-prometheus-alertmanager-datasource](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource)?
If yes, maybe the issue should be opened there and close this one.

**Comment by jiantaoz** [comment]
papagian,
Yes, I used prometheus-alertmanager as Grafana datasource.
I opened issue there, and closed this one.
Thank you very much!
