### ISSUE TITLE
Legend aggregations may show incorrect values

### ISSUE THREAD

**Issue by nagisa** [grafana/grafana#18969]
**What happened**:

Legend aggregations may show incorrect data for the selected time period. For example see the "total" time for these two graphs. This is the 24-hour graph:

![24 hour graph showing 7 seconds in total sum](https://user-images.githubusercontent.com/679122/64535139-486edb80-d306-11e9-8807-e6d4bdaf939b.png)

and this is the past 2 days one:

![Past 2 days graph showing 7 seconds in total sum](https://user-images.githubusercontent.com/679122/64535202-61778c80-d306-11e9-9ba9-81b55d84a7a6.png)

Note how the total sum aggregate is higher in the 24 hour graph compared to the past 2 days one.

**What you expected to happen**:

In absence of negative values, I would expect sum aggregate of a time series to not decrease as the period is increased. In my specific instance I would expect the graph for "past 2 days" to show a higher "total" value than the graph for "past 24 hours" one.

**How to reproduce it (as minimally and precisely as possible)**:

Presuming an non-decreasing time-series `X` with for some gauge metric in prometheus, write a query like this:

```
irate(X[30s])
```

And in legend configuration specify to show the "total" (sum) values.

Then change the period of the graph from shorter to a longer one.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: v6.3.4
- Data source type & version: Prometheus 2.12
- OS Grafana is installed on: Not applicable
- User OS & Browser: Firefox
- Grafana plugins: None that I know of
- Others: Not applicable

**Comment by nagisa** [comment]
I suspect the reason why this happens is that when changing the period, grafana queries prometheus with an increasing step (24-hours query has a step of 60 (seconds?) whereas the 2-days query has a step of 120 (seconds?)) and then calculates the sum/maximum/average/etc locally.

I had expected this to result in a separate prometheus query with an appropriate aggregation function instead.

**Comment by torkelo** [comment]
The legend values are calculated client side, so min & max cannot be correct at the same time (same for total and avg for example). They all depend on what aggregation you have in your query.

**Comment by nagisa** [comment]
Would it be possible to somehow provide custom queries (or query templates or whatever) for these legends without making a separate table widget?

**Comment by torkelo** [comment]
not sure, maybe.
