### ISSUE TITLE
Start of week to be platform or per dashboard setting, not user-specific

### ISSUE THREAD

**Issue by stefanhoth** [grafana/grafana#18968]
As already reported in #3003 users outside of US/Canada/Japan expect the week to start on Monday, instead of Sunday. This is now somewhat addressed via #5517, however this solution is deferred to the user.

**What would you like to be added**:

I'd like to request to have the "start of week" definition not derived from the user's locale or timezone setting but instead make it either a "per installation" setting or have it configurable per dashboard.

**Why is this needed**:

As the start of the week is relevant to calculations with dashboards looking at "previous week" the results will differ for users with a US locale (often just listed as English in the browser) vs. people with other locale settings.

It's confusing and unintuitive when colleagues of different locations try to work together on last weeks results as some of these would be shifted by a day.

**Comment by rg9066** [comment]
Ideally per dashboard where you specify start of week day and time in UTC so its the same no matter where you are.

**Comment by Fux2** [comment]
+1

**Comment by roalonso** [comment]
Another use case would be having dashboards/panels by isoweeks, which start on Monday no matter which in country it's being viewed.

**Comment by fmuell2** [comment]
+1
