### ISSUE TITLE
Proposal: Create a proposal process

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#18966]
# Abstract

Define a process for proposing non-trivial changes. This would increase the chance of proposed changes receiving a fair and timely evaluation with a clear outcome. Contributors will be able to receive early feedback on their proposed changes, to avoid time-consuming rewrites, and to increase the chance of an accepted pull request.

# Background

Every now and then, contributors submit pull requests with non-trivial impact, e.g. user facing APIs, or the overall architecture of Grafana. While they can bring about great improvements, they can also be difficult to review. They might interfere with other changes being made, and end up taking a long time before they get accepted, if at all.

# Proposal

Encourage contributors who want to make non-trivial changes to write a proposal for the feature they intend to implement. A proposal would not be mandatory, but can be requested by maintainers whenever more details are needed to make a decision.

Create a _review group_ that would consists of maintainers with the authority to accept or decline proposals. In the event where consensus can't be reached, an _arbiter_ reviews the discussion and decides the next steps.

*Review group:* @marefr, @dprokop, @ryantxu, @davkal

*Arbiter:* @torkelo

## Example

1. Contributor communicates their intent for the change they want to make on a public community channel, e.g. [Grafana Slack](http://slack.raintank.io/), or [Grafana Community](https://community.grafana.com/).
2. Contributor is encouraged to write a proposal for the change.
3. Contributor posts a Github issue using a proposal template.
4. Contributor updates the proposal based on feedback given by the community.
5. Review group reviews the proposal, and assigns a Github label to mark the proposal as accepted.

# Rationale

A proposal would be different from the current _Enhancement request_ issue type, as it would likely be written by the person that intends to implement the change. It would therefore have more details on _how_ the change should be implemented, to help maintainers make a decision on whether it fits with the overall vision for the project.

Other open-source projects makes the distinction between proposals and _design documents_, where a design document is an expanded form of a proposal with more explanation and motivation. At this stage, I don’t believe we need to make such a distinction.

# Implementation

- Create an issue template `.github/ISSUE_TEMPLATE/5-proposal.md` with the sections outlined in this issue. The template should have sufficient documentation for each section so that even first-time contributors are able to understand the structure.
- Create `type/proposal`, `type/proposal-accepted` and `type/proposal-declined` Github labels to be assigned whenever a decision has been made.
- Document the proposal process in [Contribution Guidelines](https://github.com/grafana/grafana/blob/master/CONTRIBUTING.md)

# Related issues

None

**Comment by davkal** [comment]
Looks really good and comprehensive. I find it important to map out the stages a proposal can go through, and have labels for those. IMO those states should be prefixed with `proposal/...`, while the `type/proposal` can remain, to separate it from other issue types.

Some more states I can image are:

- `proposal/new`
- `proposal/needs-review-group`
- `proposal/needs-mockups`
- `proposal/incomplete`
- `proposal/stale`
- `proposal/accepted`
- `proposal/rejected`

**Comment by torkelo** [comment]
I like this initiative, could encourage more substantial contributions & meaningful engagements with 
 contributors!

**Comment by marcusolsson** [comment]
@davkal I think it sounds like good addition.

Wouldn't `incomplete` cover the case of `needs-mockups`? By mockups, do you mean examples in general, or specifically say UX mockups?

Can I also suggest using `proposal/declined` instead of `proposal/rejected`, for a more friendlier tone?

**Comment by xlson** [comment]
I think this is a great idea. Not much to add from my end tbh.

**Comment by marcusolsson** [comment]
I've updated the review group to @marefr, @dprokop, @ryantxu, @davkal. I think this should be team leads within Grafana. Let me know if you'd prefer not to be part of the review group.

**Comment by marcusolsson** [comment]
Due to the general consensus, I'm marking this proposal as accepted. I'll post a pull request for a new issue template we can collaborate on.
