### ISSUE TITLE
A way to query data source for aggregations in legends should exist

### ISSUE THREAD

**Issue by nagisa** [grafana/grafana#18975]
**What would you like to be added**:

Ability to query the data source when displaying aggregates in legends. This will likely end up as an query producing a single (instant) result or something of the sort.

**Why is this needed**:

Currently the aggregations use whatever data that Grafana happens to use to draw the plot, which does not make sense for various aggregations such as min, max and especially total. See https://github.com/grafana/grafana/issues/18969 for an example.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
