### ISSUE TITLE
Grafana crashes due to high memory usage from High Cardinality Data

### ISSUE THREAD

**Issue by Nuadvocate** [grafana/grafana#18972]
**What happened**: When pulling high resolution, high cardinality data (ie. Kubernetes and container metrics), Grafana UI becomes sluggish and eventually crashed due to high memory usage. 

**What you expected to happen**:  Dashboard loads all data without issues.

**How to reproduce it (as minimally and precisely as possible)**:  Requires pulling Kubernetes metrics, with multiple unique series, up to 2000+ per panel. 

**Anything else we need to know?**: This is likely due to not using multiple lower resolutions rollups, but this was never an issue until unique-series increased by multi-fold.

**Environment**:
- Grafana version: v6.3
- Data source type & version: Graphite -> Metrictank
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Reproducible on both Chrome and Firefox
- Grafana plugins: Dashboards uses defaults, no custom plugins.
- Others:

**Comment by torkelo** [comment]
Can you describe more when this occurs? Is it as your creating the query? or simply rendering the graph? 

What is your query response? How many series and how many data points per series?

**Comment by torkelo** [comment]
I would suggest not returning 2000 series but use Graphite functions to limit the number of series (like highestMax )

**Comment by Nuadvocate** [comment]
No worries, I just need confirmation from Grafana that such best practices should be used.

**Comment by Nuadvocate** [comment]
This occurs when rendering the graph at a 24 hour period at 1-minute resolutions, only for those with large series, and sumSeries functions.  Datapoint count varies since this is an accumulation of containers (around 100+) created every other 10-30minutes. Chrome crashes when memory usage reaches 2.5GB. Firefox becomes sluggish, slow, unusable but doesn't crash until all available memory is used (12GB). Metrictank has no issue returning this type of queries, just Grafana via clientside becomes sluggish and stops loading due to memory usage. I would like to stay anonymous, so if there's any heap, memory profile needed I prefer to upload them elsewhere.  One of the reasons I'm opening this issue is to confirm that such best practices should be used when querying such data. Many end-users are using queries that cause UI to slow down and such issue are blamed on the underlying hardware. I need some type of backings to push more best practices on queries for multiple series, and I think its best to start here.

**Comment by torkelo** [comment]
very strange, what is your maxDataPoint parameter sent in requests? How many series and how many data points? are you on a 4K monitor? 

Grafana client-side graphs usually render in milliseconds even with many series & panels. If you have 50+ series I suggest hiding the legend in graphs it can be quite expensive to render.

**Comment by Nuadvocate** [comment]
All panels are using default auto for maxDataPoint. Currently using a laptop at 1080P.  Metrictank stats shows that its about 1100 series, with 7.8 million data points per requests.  There are 20 panels with similar requests for the dashboard with this issue. I tried hiding all legend, there are improvements but Grafana still crashes.  This issue was noticed when we were doing a load test on our Kubernetes cluster where multiple pods are created. The more unique series the more sluggish it got.  As of current there are no issues with the graphs unless I select the custom range to the day of the load test.

**Comment by torkelo** [comment]
your returning with 7.8 million data points per requests. ? not that strange that your crashing your browser, something wrong with the metricTank not respecting maxDataPoints?

**Comment by Nuadvocate** [comment]
Well, I'm assuming maxDatapoints for metrictank is per series and not requests. Each series will return at most 768 when using the default. Per Metrictank regarding consolidation and maxDatapoints "find the highest-resolution option that will yield a pointCount <= maxDataPoints.
If no such option exists (e.g. all series are too high resolution for the given request) we pick the lowest resolution archive and turn on runtime consolidation."  Our lowest resolution is 5min, which I assume is the reason for the high datapoint return count. I've taken over a project that did not take storage-schema as a priority, thus running into these issues. Please close this issue, if this is expected.

**Comment by Nuadvocate** [comment]
Apologized, so its 1800 series, 1.48mil datapoint total per requests. I was looking at charts where the query node was summed for that timeframe. 1800*768 will equal to 1382400, so a little off from 1.48mil but close.

**Comment by Nuadvocate** [comment]
We also use a Top-3 Cloud SAAS company, with similar metrics and was not able to handle these queries also. The only differences are, their UI has a limit so the UI doesn't crash. It will only render 100 series out of 2000 in a single plot, and give a warning to the user that metrics was limited. Is this something Grafana can implement? For example, allow the admin to limit the number of series a chart can plot and then warn the users that it is has been limited? This way users can utilize best practice with their queries?

**Comment by torkelo** [comment]
WHat is the point of returning so many series? The graphs must be unreadable?

**Comment by Nuadvocate** [comment]
There's no point of returning this much series, and I understand that. The only concern is that as more company moved to container based services, or to cloud environments, the need to support high cardinality data has been a huge factor. As of current end-users tends to use wildcard and dont rely on top or highest* functions etc. We have over 400 users, and not all are educated in such best practices. Many SaaS company puts global limitation to ensure users aren't requesting too many data to avoid this issue. If this is something Grafana can implement in the near future that would be great. Other than that, thanks for the help.

**Comment by torkelo** [comment]
I agree that there should be best practices and guidance. In this case it’s hard for Grafana to anything as Grafana cannot impose these limits or know the cardinality in-advance of making a query that will return thousands of series. MetricTank maybe has some query limits already? 

@Dieterbe do you know if there are ways to limit number of series returned form a query?

**Comment by Nuadvocate** [comment]
Metrictank does have limits for series etc but it will only rejects the request instead of downsampling it. Also, for this use case, I dont think its necessary for Grafana to know series counts in-advance, but more of a data validation to prevent the crash. Lets  say a request return x amount of series, have Grafana validate the series count and only plot allowable series or downsample  from the request and show a warning display that the request has exceeded allowable series and has been downsample. Again this is just food for thoughts, and its likely unnecessary. But eventually someone will run into this issue, as they move from bare metal to container services that generate different pod names every deployments etc.
