### ISSUE TITLE
Docs feedback: plugins/developing/backend-plugins-guide.md

### ISSUE THREAD

**Issue by ChadNedzlek** [grafana/grafana#18978]
The documentation on this page and the referenced sample don't agree. The documentation says to implement something that accepts a "tsdb.Query", the sample takes a "datasource.DatasourceRequest".  I can't reconcile which of them is correct, since the sample doesn't build.

If I try what the documentation does (and what the "plugins" in the main grafana repository do), then I can't register them using the plugin.Serve method, since that part of the main method is missing from the documentation, and the signature of the Query method in the document doesn't match what the sample does.

If I try what the sample says, I can't do auth, since it requires a tsdb.Datasource, and I only have a datasource.Datasource, and the sample doesn't do anything with authentication.

**Comment by marcusolsson** [comment]
I believe this is the Go interface to implement, as seen in [here](https://github.com/grafana/grafana-plugin-model/blob/00e18e72110ac2fb113ff11bd0a63ca240926faa/go/datasource/service.go#L10-L12):

```
type DatasourcePlugin interface {
	Query(ctx context.Context, req *DatasourceRequest) (*DatasourceResponse, error)
}
```

I don't see the purpose of the `TsdbQueryEndpoint` snippet here, and it should probably be dropped, or change to the one above.

**Comment by ChadNedzlek** [comment]
I think the existing snippet is the format that _internal_ plugins use (the ones in the grafana/grafana repository undter tsdb/ folder)

**Comment by oddlittlebird** [comment]
@shavonn, relevant to your review of the docs.

**Comment by oddlittlebird** [comment]
@ChadNedzlek , @marcusolsson , can we close this?
