### ISSUE TITLE
ContainerInsights support for Cloudwatch Logs

### ISSUE THREAD

**Issue by francopeapea** [grafana/grafana#18970]
**What would you like to be added**:
Submitted PR for this feature: 
https://github.com/grafana/grafana/pull/18971

**Why is this needed**:
This is needed for https://docs.amazonaws.cn/en_us/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html

**Comment by francopeapea** [comment]
@papagian any updates on this?

**Comment by papagian** [comment]
@francopeapea Please check my comment [here](https://github.com/grafana/grafana/pull/18971#pullrequestreview-290443462).
