### ISSUE TITLE
Data source filtering

### ISSUE THREAD

**Issue by CyBeRoni** [grafana/grafana#1897]
I'm not sure if it's possible, but it'd be nice if Grafana could have a filter set on, for example, Graphite data sources such that I could say 'org1 can read org1.\*', 'org2 can read org2.\*' and 'orgadmin can read \*'.

Thus allowing a single instance of Graphite to be used to support multiple tenants, without them being able to access other data.

**Comment by torkelo** [comment]
This cannot be implemented in Grafana, it has to be implemented in Graphite. As a grafana as no way to filter a query like alias(*.*.secret.metric.count, 'haha')

**Comment by torkelo** [comment]
updated the query part above so you see the wildcards: `alias(*.*.secret.metric.count, 'haha')`, 

I hope you understand the problem, if you have a solution for how this can be implemented in grafana leet me know. But basically I think Graphite needs to support some kind "allow" glob expression so grafana can tell Graphite what series are allowed in the query.
