### ISSUE TITLE
AzureMonitor: Implement Application Insights Log support

### ISSUE THREAD

**Issue by briangann** [grafana/grafana#18987]
Currently we support Log Analytics, and need to extend support to AI Logs.

The API is similar to LA logs, and much of the codebase can be reused.

https://dev.applicationinsights.io/reference/get-events

Background for sending/generating logs: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-trace-logs

**Comment by silencev** [comment]
does it mean logs can be searched in Explorer?

**Comment by briangann** [comment]
no, this is just for the datasource query editor. explore support would be a separate feature once this is working.

**Comment by daniellee** [comment]
This is already implemented in this [PR](https://github.com/grafana/azure-monitor-datasource/pull/51) - just needs a lot of UX love.
