### ISSUE TITLE
Meaning of "ops" unit is too confusing

### ISSUE THREAD

**Issue by nyh** [grafana/grafana#18983]
Starting in commit b678daa744ea78cf4b3928a11080b8fd86aeb30e, Grafana has the "ops" unit, meaning "operations per second". However, the name "ops" is super confusing and ambiguous, because most English speakers use the word "ops", both in speech and in writing, as shorthand for the word "operations" - so that they instinctively read "ops" as "operations", NOT as "operations per second".

An astute user will be able to tell a cumulative "operations" graph from an "operations per second" graph - but this nevertheless adds confusion, ambiguity, and unnecessary cognitive burden on users. 

Amusingly, this commit itself falls into this same confusion, check it out:
```
           {text: 'ops/sec (ops)',       value: 'ops' }, 
```
Note how the documentation string explains that "ops" is... "ops/sec"!

**Comment by nyh** [comment]
It seems to me this issue is as relevant as it always was... Maybe isn't super-popular, but still relevant as far as I can tell.

**Comment by phemmer** [comment]
See also #7250
