### ISSUE TITLE
nonNegativeDerivative values are null in alarming

### ISSUE THREAD

**Issue by Guyverix** [grafana/grafana#18989]
Problem:
I have a graph that is displaying properly using nonNegativeDerivative and sumSeries.  It is not finding values for alarming when using a nonNegativeDerivative and attempting to fire an alarm.  All the values are null according to the debug output.  When testing without nonNegativeDerivative or sumSeries, the alarm works.  It also works with just sumSeries.

Expected result:
Alarm would fire.

Graphite Query used:
sumSeries(nonNegativeDerivative(haproxy.*.metric01.BACKEND.stot))
Or: 
nonNegativeDerivative(sumSeries(haproxy.*.metric01.BACKEND.stot))
Last raw values from graphite directly:
-SNIP-,9.0,17.0,6.0,10.0,22.0,22.0

This is a new alarm that I am attempting to create, so I cant say that this used to work before and suddenly stopped.  My other "normal" alarms work properly.  Just the nonNegativeDerivitive is failing for me.

**Environment**:
- Grafana version: 
Grafana v6.3.5 (commit: 67bad72)
- Data source type & version: 
Graphite carbon-1.0.2-py2.7.egg-info *docker image
- OS Grafana is installed on: 
Ubuntu 16.04.6 LTS
- User OS & Browser: 
Linux Firefox
- Grafana plugins:
Many?  Just using the default graphite DS for this
- Others:
![Selection_001](https://user-images.githubusercontent.com/1209259/64633012-2a10ea80-d3af-11e9-95df-097d75b9091a.png)
[alarm_test_rule.txt](https://github.com/grafana/grafana/files/3596829/alarm_test_rule.txt)

**Comment by torkelo** [comment]
probably related to your alert query time range. Please try to increase it or shift it back,
