### ISSUE TITLE
change user role from WebUI

### ISSUE THREAD

**Issue by timurb** [grafana/grafana#1899]
It looks like there is no way to change the user's role via WebUI.
It gets assigned when the user is registered and I could not find any links for changing it.

**Comment by torkelo** [comment]
You can go into Organization -> Users and remove and readd the user org role 

Will fix this in 2.1 so that you can change user role (without removing and re-adding the user). Oh, and you can change the default org role that new users get in the grafana ini config file.

**Comment by torkelo** [comment]
Just to help make it clear, the Organization User (that has the role) is just a link, a link that ties a User to a specific organization with a specific Role, so when you go to organization users you see all the user links to this org, when you remove and re-add user you only remove and re-add this link not an whole user account.

**Comment by timurb** [comment]
Thanks for support! Works fine for me.
This should be made more explicit in docs as I think this is not described yet.
