### ISSUE TITLE
Building from source shows incorrect Grafana version and commit in UI

### ISSUE THREAD

**Issue by Vijay757943** [grafana/grafana#18996]
**What happened**:

I am trying to build grafana from source (v6.1.6) by checking out to commit id - cf9cb45
Tried this in both windows and ubuntu.

**What you expected to happen**:
Build and version to be shown as 6.1.6 in UI.

**How to reproduce it (as minimally and precisely as possible)**:

Checkout repo and switch to the commitid cf9cb45 then build the source.

- **In windows i am able to successfully build the v6.1.6 version** but when i bring up the server in UI it shows **Grafana v5.0.0(commit: NA)**

- **Ubuntu i am not able build the backend server because of following error :** 

[root@ip-178-16-1-107 grafana]# make deps-go
go run build.go setup
Version: 6.1.6, Linux Version: 6.1.6, Package Iteration: 1568180303
go get -v github.com/golang/dep
go install -v ./pkg/cmd/grafana-server
pkg/cmd/grafana-server/server.go:15:2: cannot find package "github.com/grafana/grafana/pkg/api" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/api (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/api (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/api (from $GOPATH)
pkg/cmd/grafana-server/server.go:16:2: cannot find package "github.com/grafana/grafana/pkg/api/routing" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/api/routing (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/api/routing (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/api/routing (from $GOPATH)
pkg/cmd/grafana-server/server.go:17:2: cannot find package "github.com/grafana/grafana/pkg/bus" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/bus (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/bus (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/bus (from $GOPATH)
pkg/cmd/grafana-server/main.go:16:2: cannot find package "github.com/grafana/grafana/pkg/extensions" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/extensions (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/extensions (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/extensions (from $GOPATH)
pkg/cmd/grafana-server/main.go:17:2: cannot find package "github.com/grafana/grafana/pkg/infra/metrics" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/infra/metrics (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/infra/metrics (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/infra/metrics (from $GOPATH)
pkg/cmd/grafana-server/server.go:32:2: cannot find package "github.com/grafana/grafana/pkg/infra/remotecache" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/infra/remotecache (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/infra/remotecache (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/infra/remotecache (from $GOPATH)
pkg/cmd/grafana-server/server.go:33:2: cannot find package "github.com/grafana/grafana/pkg/infra/serverlock" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/infra/serverlock (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/infra/serverlock (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/infra/serverlock (from $GOPATH)
pkg/cmd/grafana-server/server.go:34:2: cannot find package "github.com/grafana/grafana/pkg/infra/tracing" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/infra/tracing (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/infra/tracing (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/infra/tracing (from $GOPATH)
pkg/cmd/grafana-server/server.go:35:2: cannot find package "github.com/grafana/grafana/pkg/infra/usagestats" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/infra/usagestats (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/infra/usagestats (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/infra/usagestats (from $GOPATH)
pkg/cmd/grafana-server/main.go:18:2: cannot find package "github.com/grafana/grafana/pkg/log" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/log (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/log (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/log (from $GOPATH)
pkg/cmd/grafana-server/server.go:18:2: cannot find package "github.com/grafana/grafana/pkg/login" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/login (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/login (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/login (from $GOPATH)
pkg/cmd/grafana-server/server.go:19:2: cannot find package "github.com/grafana/grafana/pkg/login/social" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/login/social (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/login/social (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/login/social (from $GOPATH)
pkg/cmd/grafana-server/server.go:20:2: cannot find package "github.com/grafana/grafana/pkg/middleware" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/middleware (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/middleware (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/middleware (from $GOPATH)
pkg/cmd/grafana-server/server.go:36:2: cannot find package "github.com/grafana/grafana/pkg/plugins" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/plugins (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/plugins (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/plugins (from $GOPATH)
pkg/cmd/grafana-server/server.go:21:2: cannot find package "github.com/grafana/grafana/pkg/registry" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/registry (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/registry (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/registry (from $GOPATH)
pkg/cmd/grafana-server/server.go:37:2: cannot find package "github.com/grafana/grafana/pkg/services/alerting" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/alerting (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/alerting (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/alerting (from $GOPATH)
pkg/cmd/grafana-server/main.go:19:2: cannot find package "github.com/grafana/grafana/pkg/services/alerting/conditions" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/alerting/conditions (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/alerting/conditions (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/alerting/conditions (from $GOPATH)
pkg/cmd/grafana-server/main.go:20:2: cannot find package "github.com/grafana/grafana/pkg/services/alerting/notifiers" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/alerting/notifiers (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/alerting/notifiers (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/alerting/notifiers (from $GOPATH)
pkg/cmd/grafana-server/server.go:38:2: cannot find package "github.com/grafana/grafana/pkg/services/auth" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/auth (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/auth (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/auth (from $GOPATH)
pkg/cmd/grafana-server/server.go:26:2: cannot find package "github.com/grafana/grafana/pkg/services/cache" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/cache (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/cache (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/cache (from $GOPATH)
pkg/cmd/grafana-server/server.go:39:2: cannot find package "github.com/grafana/grafana/pkg/services/cleanup" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/cleanup (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/cleanup (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/cleanup (from $GOPATH)
pkg/cmd/grafana-server/server.go:40:2: cannot find package "github.com/grafana/grafana/pkg/services/notifications" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/notifications (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/notifications (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/notifications (from $GOPATH)
pkg/cmd/grafana-server/server.go:41:2: cannot find package "github.com/grafana/grafana/pkg/services/provisioning" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/provisioning (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/provisioning (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/provisioning (from $GOPATH)
pkg/cmd/grafana-server/server.go:42:2: cannot find package "github.com/grafana/grafana/pkg/services/rendering" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/rendering (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/rendering (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/rendering (from $GOPATH)
pkg/cmd/grafana-server/server.go:43:2: cannot find package "github.com/grafana/grafana/pkg/services/search" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/search (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/search (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/search (from $GOPATH)
pkg/cmd/grafana-server/server.go:44:2: cannot find package "github.com/grafana/grafana/pkg/services/sqlstore" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/services/sqlstore (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/services/sqlstore (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/services/sqlstore (from $GOPATH)
pkg/cmd/grafana-server/main.go:21:2: cannot find package "github.com/grafana/grafana/pkg/setting" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/setting (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/setting (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/setting (from $GOPATH)
pkg/cmd/grafana-server/main.go:22:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/azuremonitor" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/azuremonitor (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/azuremonitor (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/azuremonitor (from $GOPATH)
pkg/cmd/grafana-server/main.go:23:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/cloudwatch" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/cloudwatch (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch (from $GOPATH)
pkg/cmd/grafana-server/main.go:24:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/elasticsearch" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/elasticsearch (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/elasticsearch (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/elasticsearch (from $GOPATH)
pkg/cmd/grafana-server/main.go:25:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/graphite" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/graphite (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/graphite (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/graphite (from $GOPATH)
pkg/cmd/grafana-server/main.go:26:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/influxdb" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/influxdb (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/influxdb (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/influxdb (from $GOPATH)
pkg/cmd/grafana-server/main.go:27:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/mysql" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/mysql (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/mysql (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/mysql (from $GOPATH)
pkg/cmd/grafana-server/main.go:28:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/opentsdb" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/opentsdb (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/opentsdb (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/opentsdb (from $GOPATH)
pkg/cmd/grafana-server/main.go:29:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/postgres" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/postgres (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/postgres (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/postgres (from $GOPATH)
pkg/cmd/grafana-server/main.go:30:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/prometheus" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/prometheus (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/prometheus (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/prometheus (from $GOPATH)
pkg/cmd/grafana-server/main.go:31:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/stackdriver" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/stackdriver (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/stackdriver (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/stackdriver (from $GOPATH)
pkg/cmd/grafana-server/main.go:32:2: cannot find package "github.com/grafana/grafana/pkg/tsdb/testdata" in any of:
        /root/go/src/github.com/grafana/vendor/github.com/grafana/grafana/pkg/tsdb/testdata (vendor tree)
        /usr/local/go/src/github.com/grafana/grafana/pkg/tsdb/testdata (from $GOROOT)
        /root/go/src/github.com/grafana/grafana/pkg/tsdb/testdata (from $GOPATH)
exit status 1
exit status 1
make: *** [deps-go] Error 1

**Anything else we need to know?**:
 
I see some checks are failed for this tag(**Merge branch 'cp_6.1.6' into v6.1.x**) in repo 

**Environment**:
- Grafana version: v6.1.6
- Data source type & version:
- OS Grafana is installed on: ubuntu and windows
- User OS & Browser: Windows & chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you only get that if you build a release package. "go run build package" , think "go run build build" might also work if you only want to build the binary and not a full release package

**Comment by Vijay757943** [comment]
Not working in both ubuntu and windows with above commands. Facing below error .
package build: cannot find package "build" in any of:
        /usr/local/go/src/build (from $GOROOT)
        /root/go/src/build (from $GOPATH)

Also to re-iterate i am building v6.1.6 by checking out to last commit in that release.
