### ISSUE TITLE
Graph unconnected points

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#18993]
I have setup the following graph panel, by adding a new panel and changing the query only, using **Average** metric:
![Metricbeat_graph](https://user-images.githubusercontent.com/22418250/64649492-a6deab80-d425-11e9-86b1-737afeb5b8bd.png)
Same problem with **Min** and **Max** Metric.

Changing to **Sum** or **Count** results in connected points:
![Metricbeat_graph2](https://user-images.githubusercontent.com/22418250/64649641-f02efb00-d425-11e9-9c85-e64b3f8fc38b.png)

The Draw mode is set to Lines, so the points should be connected also for the first case.

----------------------------
Grafana v6.3.3 (commit: 84d0a71)

**Comment by cdalexndr** [comment]
Changing **Interval** from **auto** to other value resolves this issue.
Shouldn't the points be connected also with auto interval?

**Comment by ryantxu** [comment]
Have you messed with the "stacking and null values" option in Graph?
![image](https://user-images.githubusercontent.com/705951/64652748-6c4f2180-d3d9-11e9-8670-45e9c5843037.png)

**Comment by cdalexndr** [comment]
@ryantxu nope, the values are default, like in your image.

It seems that when the **interval** is lower than the metricbeat collector interval, the points are unconnected, as if there are empty points between them because there is no data there.

**Comment by ryantxu** [comment]
If the null value setting does not change your results, your issue is with the ***query*** not the graph settings

**Comment by cdalexndr** [comment]
Setting **Null value: connected** resolved my issue.
