### ISSUE TITLE
Login page bypass

### ISSUE THREAD

**Issue by spectroman** [grafana/grafana#19003]
As I was investigating how to monitor my Grafana installation I stumble on this "feature" to bypass the login page without authenticating.

This is obviously wrong and need to be fixed.

When getting to the login page of the Grafana, simply add "%2F" at the end of the URL and you will bypass the login screen going inside the regular installation without authentication.

As in: https://grafana.whateverdomain.com/%2F

The catch is that you will get 401 in pretty much everything, but that doesn't mean that, if investigated properly there are "secrets" to be revealed under the hood. I cannot spend a lot of time poking around this, but I think the developers should know.

- Grafana version: 6.3.5
- Data source type & version: RPM -- grafana-6.3.5-1.x86_64.rpm
- OS Grafana is installed on: CentOS 7.6.1810
- User OS & Browser: Linux / Firefox and Chromium
- Grafana plugins: not relevant (I think)
- Others: tested with rev proxy

**Comment by torkelo** [comment]
there are no secrets just non-functional html templates with no api access. 

Strange that %2F messes up the angular router.

**Comment by spectroman** [comment]
When I mean "secrets" it is more related with the application itself, after all he is actually entering onto and downloading a lot of stuff from the application (not actual user data)... it simply shouldn't happen and it may create other possibilities...

Anyway, I think it should be reported. And probably it is easy to fix.

**Comment by spectroman** [comment]
btw, some colleague tested against version 6.0.2 and the problem seems not present there.
