### ISSUE TITLE
Use regex and variables for aliasColors

### ISSUE THREAD

**Issue by drajen** [grafana/grafana#1900]
It would be very useful to allow regular expressions and variables in the aliasColors keys. Colors seem to get selected by the fully qualified key name and it completely breaks templating with explicit colors.

**Comment by torkelo** [comment]
Yea, would love have this. Maybe I will have time in v2.1 or v2.2 :)

Will close, as there is already an issue for this: https://github.com/grafana/grafana/issues/590

**Comment by drajen** [comment]
For anyone else who find their way here, this is solvable with using aliases with variables that point to common positions in the key:

`/data.stream.$hostname.cpu.*.foo/`

With the alias 'core $5' will save the key as "core 2" for example in aliasColors and that way templates work across different hostnames. 

So, this was part of the basic functionality all along. :-)

**Comment by torkelo** [comment]
@drajen nice solution :)

**Comment by ddavydenko** [comment]
I am trying to use this functionality with PieChart panel, and there doesn't seem to be a way to control aliasColors with the power of regex'es. Graph panel supports SeriesOverride, but PieChart panel doesn't seem to... I am on Grafana v6.7.4.

I tried to just copy paste seriesOverride from Graph panel to PieChart panel as is but it doesn't seem to have an effect. If I try to put regex into aliasColors property - it seems to be ignored by the panel and colors are rendered by Grafana choice, not mine. I wonder if there is a way to use regex to control colors of series in PieChart panel?

**Comment by Normand-Nadon** [comment]
> I am trying to use this functionality with PieChart panel, and there doesn't seem to be a way to control aliasColors with the power of regex'es. Graph panel supports SeriesOverride, but PieChart panel doesn't seem to... I am on Grafana v6.7.4.
> 
> I tried to just copy paste seriesOverride from Graph panel to PieChart panel as is but it doesn't seem to have an effect. If I try to put regex into aliasColors property - it seems to be ignored by the panel and colors are rendered by Grafana choice, not mine. I wonder if there is a way to use regex to control colors of series in PieChart panel?

Did you ever find an answer to this? it is driving me nuts that I cannot use Regex in grafana-pieChart-panel
