### ISSUE TITLE
Adhoc filter values incorrectly populate range selector ${__range_s} in addition to instant selectors

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#19008]
We are using ${__range_s}  in SingleStat range selector dashboards to query number of changes in timerange. When Adhoc filters are used to filter the query the resulting query is incorrectly generated. You can check the outcome using Prometheus link or Query inspector.
For example set time range to last 1h.

Original query:
sum(rate(http_server_requests_seconds_count{}[${__range_s}s]))
generates query 
?query=sum(rate(http_server_requests_seconds_count{}[3600s]))

Adding Adhoc filter status="200" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200"}[${status="200"}s]))

Adding Adhoc filter status="200" and method="GET" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200", method="GET"}[${status="200", method="GET"}s]))

Query using [[__range_s]]s is not working at all (without Adhoc):
sum(rate(http_server_requests_seconds_count{}[[[__range_s]]s]))

Expected outcome:
Adding Adhoc filter status="200" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200"}[3600s]))

Adding Adhoc filter status="200" and method="GET" generates query
?query= sum(rate(http_server_requests_seconds_count{status="200", method="GET"}[3600s]))

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows, Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
I'm unable to reproduce it either in 6.3.3 or the master branch. Are you sure that the adhoc filters are correct?

**Comment by marefr** [comment]
Reproduced on v6.3.4. [Demo dashboard](https://play.grafana.org/d/74hWd-cWz/issue-19008-prometheus-adhoc-filters?orgId=1). Add adhoc filter `address = 1e:e3:5f:98:53:2c`.

**Comment by secustor** [comment]
I ran in this issue too if using variables combined with adhoc filters.

table query: `ALERTS{severity=~".*",alertstate=~"firing"}`    
adhoc filter: `alertname!="DeploymentInProgress"`    

expected result: `ALERTS{severity=~".*",alertstate=~"firing",alertname!="DeploymentInProgress"}`
query produced by Grafana: `ALERTS{severity=~"${alertname!="DeploymentInProgress"}",alertstate=~"${alertname!="DeploymentInProgress"}`

**Comment by aocenas** [comment]
@papagian @marefr taking this to Observability backlog as this needs to be solved in the plugin code I think.

**Comment by aocenas** [comment]
Sort of related to https://github.com/grafana/grafana/issues/14802 so probably good idea to fix it together.

**Comment by jtorkkel** [comment]
I managed to workaround this using **[$__range]** instead of **[${__range_s}s]**

Prometheus documentation should be updated to use [$__range] format because it works also with adhoc filters

https://grafana.com/docs/grafana/latest/panels/queries/#query-syntax
```
PromQL
query_result(max_over_time(<metric>[${__range_s}s]) != <state>)
```

https://grafana.com/docs/grafana/latest/features/datasources/prometheus/#using-interval-and-range-variables
```
Query: query_result(max_over_time(<metric>[${__range_s}s]) != <state>)
Regex:
```

**Comment by belm0** [comment]
The bug isn't related to range selector specifically-- please revise the issue title.  Adhoc substitution is broken for any `${}` variable access in the query, as well as Prometheus subquery syntax `[foo:bar]`.

original query:
```
avg(rate((my_metric{instance=~"${foo}-bar"} > 0)[3h:])) by (device)
```

query after substitution with adhoc filter `goversion="go1.13.8"`:
```
avg(rate((my_metric{instance=~"${goversion="go1.13.8"} > 0)[3h{goversion="go1.13.8"}:])) by (device)"
```
