### ISSUE TITLE
Telegram inline images not working

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#19019]
Image upload doesn't work in Grafana v6.3.3 (commit: 84d0a71).
The option **Upload Image** is ON in the notification channel settings.
In Telegram I received the following text with no image:
```
[Alerting] Errors / container alert
State: Errors / container alert
Message: Found errors
URL: http://todo:3000/d/17hihJ5Zk/docker-metrics?fullscreen&edit&tab=alert&panelId=10&orgId=1

Metrics:
web: 0.001
logstash: 0.003
filebeat: 0.017
```

Similar: https://github.com/grafana/grafana/issues/10631

**Comment by mohsenasm** [comment]
-1 ☹️

**Comment by aknuds1** [comment]
@cdalexndr Have you looked for any errors in your Grafana server logs?

**Comment by mohsenasm** [comment]
Hi @aknuds1,
In Grafana 6.4.4 there was some error about sending messages to Telegram and those errors was related to inline images. But I haven't those errors now because I downgrade Grafana to version 6.3.3 (that was working before) and my issue resolved.
However if you can't reproduce this error, I can upgrade my Grafana and send you those errors.

**Comment by marefr** [comment]
Closing this due to lack of response from original author. Let us know if you still experience problem and we'll reopen.

**Comment by oriondvd** [comment]
Hello, I have the same problem. I`m using Grafana Cloud free plan.
When I try to send test message - I receive this:
```
[Alerting] Test notification
State: Test notification
Message: Someone is testing the alert notification within Grafana.
URL: https://oriondvd5.grafana.net/
Image: https://grafana.com/assets/img/blog/mixed_styles.png

Metrics:
High value: 100.000
Higher Value: 200.000
```
And there is no any inline images, only url.
Is this a restriction of a free plan or a bug?
