### ISSUE TITLE
AWS Cloudwatch Alarms in Grafana

### ISSUE THREAD

**Issue by prakashraaj046** [grafana/grafana#19013]
Can AWS cloudwatch alarms be displayed in grafana if i have provided full access in cloudwatch policies?

**Comment by prakashraaj046** [comment]
Is there anuine out there to help with this ??

**Comment by papagian** [comment]
I don't think there is support for Cloudwatch Alarms.

**Comment by sunker** [comment]
As @papagian pointed out, this is already possible to do. Closing this issue.
