### ISSUE TITLE
Copying full field name not possible if the name is too long

### ISSUE THREAD

**Issue by barakakoun** [grafana/grafana#19010]
**What would you like to be added**:
I'd like that by right clicking a field name input it will select the whole name and not only part of it, because if the field name is too long then the user can't select it for copying.

**Why is this needed**:
Today, if the field name is too long then there is no way to copy it.

for example:
<img width="757" alt="Screen Shot 2019-09-11 at 14 25 39 copy" src="https://user-images.githubusercontent.com/15690241/64693988-3e351480-d4a1-11e9-90a9-05e285c8cbb3.png">
Here I'd like to copy the whole field name but I can only copy part of it.

Note that manual selecting the text with click-and-drag isn't possible since the click triggers input to fill and the value disappears (and if the field name is too long for the box then it's impossible to select the hidden part anyway).

**Comment by torkelo** [comment]
not sure what the best solution is (sorry for closing your PR). But I think there could be another solution to be found. 

If you click on the field and select the same field again you stay in textbox mode and can select  everything
