### ISSUE TITLE
Date conversion inputs are in milliseconds

### ISSUE THREAD

**Issue by wbl** [grafana/grafana#19025]
**What happened**:
I had to multiply by 1000 to get things to work.

**What you expected to happen**:
I had a count in seconds since the unix epoch I wanted to convert to human readable time units/a time interval in seconds. So I reached for From Now

**How to reproduce it (as minimally and precisely as possible)**:
Take a metric with a time in it. use From now to display it.

**Anything else we need to know?**:
This probably is going to be hard to fix and break a lot of existing things.

**Comment by torkelo** [comment]
Yep it expects a millisecond epoch (default for dates in the browser)
