### ISSUE TITLE
Grafana 6.3.5  metric_table does not exist

### ISSUE THREAD

**Issue by nano2K** [grafana/grafana#19020]
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "244.141ms",
  "error": "tsdb.HandleRequest() response error &{pq: relation \"metric_table\" does not exist  A 0x3498070 [] []}",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1568227071679,
        "queries": [
          {
            "refId": "A",
            "model": {
              "format": "time_series",
              "group": [],
              "metricColumn": "none",
              "rawQuery": false,
              "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "temp"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "table": "chili",
              "timeColumn": "created_at",
              "where": []
            },
            "datasource": {
              "id": 1,
              "name": "PostgreSQL"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1568227371679
      }
    }
  ]
}

I was trying to test Telegram notifications with PostgreSQL

**Comment by torkelo** [comment]
Check that your metrics DB has this table

**Comment by richardARPANET** [comment]
@torkelo What if there is no DB called `metrics`? And Grafana didn't create a `metrics_table` within the Postgres data source?

How is all of this meant to be created? 

Thanks
