### ISSUE TITLE
grafana-cli fails to install plugin on Windows

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#19022]
**What happened**:
Installing plugin on Windows using grafana-cli fails with an error:

![image](https://user-images.githubusercontent.com/1668778/64727081-5aa07380-d4d8-11e9-8ac3-3561da323310.png)

**What you expected to happen**:
Plugin to be installed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
- Tried to install grafana-piechart-panel, but that throws the same error.
- Verified that manually downloading zip file and extracting it into plugin folder and restarts Grafana works as expected. 

**Environment**:
- Grafana version: v6.4.0-pre (fa00742)
- OS Grafana is installed on: Windows

**Comment by marefr** [comment]
Can be related to front-slash here instead of backslash: https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-cli/commands/install_command.go#L190

**Comment by tushar315** [comment]
"Verified that manually downloading zip file and extracting it into plugin folder and restarts Grafana works as expected."
followed the same step but on running the command grafana-server restart i get panic: runtime error: invalid memory address or nil pointer dereference

**Comment by marefr** [comment]
@tushar315 This is a rather old issue. Can you please open a new issue using the bug template and fill in all the details?

**Comment by tushar315** [comment]
> @tushar315 This is a rather old issue. Can you please open a new issue using the bug template and fill in all the details?
#24212 added
