### ISSUE TITLE
Incorrect "Dimensions" values for CloudWatch namespace AWS/Kafka

### ISSUE THREAD

**Issue by davidrosson** [grafana/grafana#19032]
**What happened**:
The default "Dimensions" values provided by Grafana for the AWS CloudWatch namespace `AWS/Kafka` are incorrect.

The when creating a variable, the query `dimension_keys(AWS/Kafka)` returns:
- `Broker`
- `Cluster`
- `Topic`

These same incorrect values are provided when using the query builder's "Dimensions" dropdown. Selecting these pre-populated values for use in a query returns no results. The correct "Dimensions" values must be typed in manually.

**What you expected to happen**:
The valid "Dimensions" for the AWS CloudWatch namespace `AWS/Kafka` are:
- `Broker ID`
- `Cluster Name`
- `Topic`

(The spaces in the above values are intentional, since this how AWS has defined these "Dimension" names.)

These are the values that should be returned by the query `dimension_keys(AWS/Kafka)` and any pre-populated "Dimensions" dropdown.

**How to reproduce it (as minimally and precisely as possible)**:
1. Connect to a CloudWatch data source
1. Create a new dashboard
1. For that dashboard, create a new variable
    1. Set `Data source` to the CloudWatch data source
    1. Set `Query` to `dimension_keys(AWS/Kafka)`
    1. Notice that `Preview of values` shows:
        - `Broker`
        - `Cluster`
        - `Topic`

Alternately:
1. Connect to a CloudWatch data source
1. Create a new dashboard
1. For that dashboard, add a new panel
    1. Add a `Query` using the CloudWatch data source
    1. Set `Metric: select namespace` to `AWS/Kafka`
    1. Click the `Dimensions` dropdown `+`
    1. Notice that the available options are:
        - `Broker`
        - `Cluster`
        - `Topic`

**Anything else we need to know?**:
It seems that Amazon's "Dimension" naming scheme for the CloudWatch metrics for its managed Kafka (MSK) service is one of the few (and possibly the only) to use a space in the "Dimension" key.

**Environment**:
- Grafana version: v6.3.4 (a557646)
- Data source type & version: Built-in CloudWatch
- OS Grafana is installed on: Deployed from `grafana/grafana:6.3.4` on Kubernetes
- User OS & Browser: MacOS 10.14.3 (18D109); Brave and Chrome
- Grafana plugins: Only defaults
- Others: N/A

**Comment by cjtravis** [comment]
Looking forward to a resolution on this soon!  Eager to use Grafana to surface metrics from our AWS MSK instance!

**Comment by skuxy** [comment]
Same here! When a dimension field contains whitespaces (I'm baffled who in CloudWatch thought it was even remotely okay-ish idea), Grafana  picks up only first word and ignores the rest. Also, sometimes for "Broker ID", value from dropdown isn't okay, but I have to insert broker manually (erase variable and type in "1")

**Comment by marefr** [comment]
Changes are needed here 
https://github.com/grafana/grafana/blob/de5038441fc40f86c63d646bf633591e2021bc0d/pkg/tsdb/cloudwatch/metric_find_query.go#L165

**Comment by skuxy** [comment]
Hey @marefr , awfully sorry to bother you, I've submitted tiny fix to this issue which is referenced above, hope it's okay :)

**Comment by marefr** [comment]
@skuxy sorry totally missed that PR. Weill make sure that someone review that asap.

**Comment by kunsalvi** [comment]
Is there a workaround to create matrices in grafana?
Need this visualization for customer use.

Grafana version: 6.3.3
