### ISSUE TITLE
React Plugins lack access to TemplateSrv

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#19058]
More of an incomplete feature rather than a bug. And one that I imagine will eventually be addressed since the Table panel requires it for the +/- cell ad-hoc filtering support. However, I am writing it here to have the need on record, and hoping the access is already there and I've just missed it.

The plugin I am building (like many angular plugins I have built in the past) needs to allow the user to click on an item as a way to add filters to the dashboard.

I imagine the path through would look similar to the one used to provide React plugins to variable replacement with replaceVariables.

**Comment by rubaeros** [comment]
Hi @ryantxu 

I already import getLocationSrv() from @grafana/runtime
But, how do you extend the "class MyPanel extends PureComponent<PanelProps<MyPanelOptions>>" to access the function getLocationSrv()

Thanks!

**Comment by seanlaff** [comment]
One place that the urlParams fails is grabbing a list of available variables (i.e to populate them as extra options in a query builder)

A hack that has been working for me in the meantime
```ts
export function getTemplateSrv() {
  return angular
    .element(document)
    .injector()
    .get('templateSrv');
}
```

**Comment by makai-linden** [comment]
I am having a similar issue while writing a datasource plugin in **React**. Everything is working well except in the case of interpolating the dashboard variables in the datasource request.
`getLocationSrv().update()` seems to be more about changing the grafana dashboard URL. Is there another way to get the dashboard variables from the datasource or even the QueryEditor? 

I'd be happy to implement my own method, but frankly, the `templateSrv.replace()` method would work like a charm if I could access it legitimately (`templatSrv` is a private member of `DataSourceSrv`).

I'd love a `getTemplateSrv()` method, even if all it provided was the variables and/or interpolation method.

**Comment by mubeta06** [comment]
@ohmakai did you end up coming up with a workaround for this? `templateSrv.replace()` appears to be what I am after also but it is beyond my grasp from within my React datasource plugin.

**Comment by ryantxu** [comment]
in master (pre grafana 7) via `@grafana/runtime` you can run:

```
getTemplateSrv().getVariables()
```

for replace... you should still use the [replaceVariables](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/panel.ts#L67) property
