### ISSUE TITLE
Alerts without include image

### ISSUE THREAD

**Issue by gmorales254** [grafana/grafana#19053]
**What happened**:

Actually we have configured the option 
"include image" on the alerts for Hangout

![errorgrafana2](https://user-images.githubusercontent.com/55248854/64800043-3c7c5700-d55c-11e9-86d3-aef96ad9f158.PNG)

and when we send a test that function works as you see in the next screenshot:

![errorgrafana4](https://user-images.githubusercontent.com/55248854/64799960-15258a00-d55c-11e9-9c39-bb8f41399963.PNG)

but i have an alert without include image:

![errorgrafana3](https://user-images.githubusercontent.com/55248854/64800003-29698700-d55c-11e9-9ff5-d77dd54a8c9a.PNG)

I have two queries in the same dashboard without variables.
 
**What you expected to happen**:

I expected an alert with include image like this:
![errorgrafana4](https://user-images.githubusercontent.com/55248854/64800247-9da42a80-d55c-11e9-9786-82b5c82189c3.PNG)

**How to reproduce it (as minimally and precisely as possible)**:
 I explain that on the firts point of this issue.

**Anything else we need to know?**:

Nothing else.
Thanks for all!

**Environment**:
- Grafana version: 6.3.4
- Data source type & version: InfluxDB 1.7.7
- OS Grafana is installed on: Ubuntu server 16.04 
- User OS & Browser: Admin  - Chrome 
- Grafana plugins: No plugins for this dashboard
- Others:

**Comment by papagian** [comment]
`Google Hangouts Chat` notifier for enabling images in notifications [requires](https://grafana.com/docs/alerting/notifications/#google-hangouts-chat) that this image be publicly accessible. Therefore you should configure an external image uploaded. Check also [the documentation](https://grafana.com/docs/alerting/notifications/#external-image-store).

**Comment by gmorales254** [comment]
@papagian I can't use the plugin with my local server:

[external_image_storage.local]
;path = ../data/storage
;public_path = public/img/attachments


¿Can you help me?

**Comment by papagian** [comment]
@gmorales254 You cannot use this notifier with a local storage. As it is suggested in the [notifier table](https://grafana.com/docs/alerting/notifications/#google-hangouts-chat) the `Google Hangouts Chat` notifier supports `external only` images meaning that the image should be publicly accessible.  Grafana can upload the image to an image store (Amazon S3, Webdav, Google Cloud Storage and Azure Blob Storage) and this is where the `external_image_storage` configuration is used for.

**Comment by gmorales254** [comment]
@papagian, first, i so greatefull with your response, then..
I understood what you said, but, can you provide me the exactly configuration i need to use the Google Cloud Storage? Cause my instance with grafana is on GCP actually..

Thanks for all,
Regads, 
Gaston Morales.

**Comment by papagian** [comment]
@gmorales254 In the case of Google Cloud Storage you need to have a Service Account with "Storage Object Writer" role and a bucket with the access control model of "Set object-level and bucket-level permissions". 
In your grafana configuration the `provider` under `external_image_storage` should be `gcs` and the values under the `external_image_storage.gcs` section should be set appropriately as described [here](https://grafana.com/docs/installation/configuration/#external-image-storage-gcs).
Let me know if you need additional help.

**Comment by gmorales254** [comment]
@papagian 

Could you contact me on skype?
**gmorales@integraccs.com**

Thanks,
Regards!!

**Comment by daniellee** [comment]
@gmorales254 just so you know - if you have a semicolon at the start of a line in an ini file then the whole line is commented out. So the ini snippet you posted earlier is commented out and will have no effect:

```ini
[external_image_storage.local]
;path = ../data/storage
;public_path = public/img/attachments
```
