### ISSUE TITLE
Do not delete graph visualization thresholds

### ISSUE THREAD

**Issue by patricktokeeffe** [grafana/grafana#19064]
**What happened**:

Visualization thresholds are deleted when alert is deleted.

**What you expected to happen**:

Thresholds should be re-enabled after deleting alert, per UI hint:
> ... To re-enable thresholds, the alert rule must be deleted from this panel.

![image](https://user-images.githubusercontent.com/1348834/64820325-fe376580-d564-11e9-8f63-f2ab514172f3.png)

**How to reproduce it (as minimally and precisely as possible)**:

Introduced by the resolution to #9681 (baeea98)?

**Anything else we need to know?**:

Because graph edits cannot be undone, there should be as few side effects as possible. Deleting an alert shouldn't have anything to do with deleting visual thresholds. 

**Environment**:
- Grafana version: 6.3.3 (84d0a71)
- Data source type & version: MySQL (built-in)
- OS Grafana is installed on: Windows 7 x64
- User OS & Browser: Windows 7 x64 + Chrome 76
- Grafana plugins: Carpet plot, Multistat, WindRose, DarkSky, GoogleCalendar, Sun and Moon
- Others:

**Comment by peterholmberg** [comment]
This is still relevant, 7.4.0pre

**Comment by torkelo** [comment]
Since alerting rules are getting their own separate UI we can close this
