### ISSUE TITLE
Some backend tests fail on Windows

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#19062]
**What happened**:
Ran backend tests and some are failing.

**What you expected to happen**:
All tests to pass.

**How to reproduce it (as minimally and precisely as possible)**:
Run `go test ./pkg/...` on Windows

**Environment**:
- Grafana version: latest master

**Comment by bergquist** [comment]
@aknuds1 Something to consider for the drone work? I don't expect you to fix all the tests but would be interesting to consider this going forward. Running all tests on windows would help us catch bugs

**Comment by bergquist** [comment]
@AgnesToulet since your working on windows. Is still issue still valid?

**Comment by aknuds1** [comment]
I can try this @bergquist. I'm not a Windows user, but I do have a VM.
