### ISSUE TITLE
Cannot change data source on imported dashboard

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#19065]
**What happened**: Imported dashboard from another grafana server, saw errors about data sources not existing but could not change the datasources

**What you expected to happen**: grafana to prompt me for which data sources to use in a dashboard when the data sources in the imported dashboard cannot be found

**How to reproduce it (as minimally and precisely as possible)**: Open up imported dashboard

**Environment**:
- Grafana version: 6.3
- Data source type & version: Influxdb 1.7.5
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS X, chrome
- Grafana plugins: yesoreyeram-yesoreyeram-boomtable-panel-3c1ad62

**Comment by papagian** [comment]
Strange, I'm not able to reproduce it neither in 6.3 nor 6.4.0-pre.
In my case `Import` button is disabled if I do not select a datasource or/and there is no such a datasource available.
<img width="1276" alt="Screenshot 2019-09-13 at 12 51 14" src="https://user-images.githubusercontent.com/1632407/64854284-f095e480-d625-11e9-915e-458e7593e003.png">
Do you upload a file or do you paste a JSON?

**Comment by papagian** [comment]
Changing datasource is only supported if exporting for sharing externally. Check also this [note](https://grafana.com/docs/reference/export_import/#note).
