### ISSUE TITLE
Singlestat Panel documentation does not match current release

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19068]
Singlestat panel documentation here: https://grafana.com/docs/features/panels/singlestat/

Does not match the UI demo here: https://play.grafana.org/d/000000110/business-metrics?tab=visualization&orgId=1&fullscreen&edit&panelId=4

Need to update documentation to match the current Grafana release.

(Adding this to help us keep straight what is being worked on. Please comment when you start updating the documentation.)

**Comment by bharjala** [comment]
I'm working on this. Added Prefix/Postfix under the options for the Coloring section. This definition is missing in the docs, so I've added TBD next to Prefix/Postfix under Coloring.

**Comment by oddlittlebird** [comment]
@bharjala - The screenshot for the colors also does not match, circles vs. squares. I suggest taking a thorough walk through that portion of the UI to see what has changed since the update.

Also, one major gap I see here is this: how do I access the Singlestat panel/visualization?

Second big one is: how do I get from the default view to the example shown in the first screenshot? 

When ready, don't forget to tag your pull request with #19068 so that it gets linked to this issue.

**Comment by oddlittlebird** [comment]
Issue for tracking.
