### ISSUE TITLE
Singlestat range mappings bug

### ISSUE THREAD

**Issue by ajnurjukan** [grafana/grafana#19060]
**What happened**:

I wanted to set some text when value is between 0 and 500. In every other visualization when I set that value it loads the text immediately but not in the singlestat visualization. I have to open query page, or some other visualization and then when I return it has loaded the text. I want that to be applied immediately like in all other visualizations.

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: Simple JSON datasource
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: 
![Screenshot from 2019-09-12 21-06-12](https://user-images.githubusercontent.com/37128135/64813235-365c9980-d5a1-11e9-91d3-007e23fb03d0.png)
Google Chrome

**Comment by flopp999** [comment]
I also noticed that I cannot use space anymore
I want it to be empty if the value is between two ranges, it worked before.

**Comment by peterholmberg** [comment]
Singlestat has been deprecated and replaced by stat panel where this works.
