### ISSUE TITLE
Update Dashboard List visualization documentation

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19075]
Compare current documentation: https://grafana.com/docs/features/panels/dashlist/

To current UI: https://play.grafana.org/d/000000110/business-metrics?tab=visualization&orgId=1&fullscreen&edit&panelId=4

They do not match.

Update the documentation to match the current Grafana release.

(Maintainer note: Adding this issue to help keep straight who is working on what.)
(Contributor: Please comment when you start working on this issue.)

**Comment by bharjala** [comment]
I've started working on this issue. The Dashboard List panel has a list of options (ex. Starred, Recently Viewed, Tags). The list is missing the Folder option. I've edited it to include the Folder option, with the content TBD.

**Comment by oddlittlebird** [comment]
Cool. Besides testing to make sure all the extant options still work as explained and there are no gaps, this topic also lacks the answer to: "How do I get here?"

When ready, be sure to tag your pull request with #19075.

**Comment by oddlittlebird** [comment]
Issue for tracking.
