### ISSUE TITLE
Update Text visualization documentation

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19072]
Compare current documentation: https://grafana.com/docs/features/panels/text/

To current UI: https://play.grafana.org/d/000000110/business-metrics?tab=visualization&orgId=1&fullscreen&edit&panelId=4

They do not match.

Update the documentation to match the current Grafana release.

(Maintainer note: Adding this issue to help keep strait who is working on what.)
(Contributor: Please comment when you start working on this issue.)

**Comment by bharjala** [comment]
I've started working on this issue. The Text panel says that there are three modes you can write in: markdown, HTML, or text. Text is not a selectable mode, so I've removed mentions of it.

**Comment by oddlittlebird** [comment]
Sounds good. Don't forget to update screenshots and give instructions for the user on how to access this panel.

Also, bonus points if you rewrite the first paragraph to get rid of the "etc."

One other thing that seems to be missing is an example of what the results of using this panel look like. It says you can make descriptions for dashboards, but what does it look like after one does that? As a new user, I am having trouble understanding what the benefit to me would be.

As always, be sure to include this issue number in your pull request so that the PR is linked here. Thanks!

**Comment by oddlittlebird** [comment]
Issue for tracking.
