### ISSUE TITLE
Heroku support and/or instructions

### ISSUE THREAD

**Issue by khalibloo** [grafana/grafana#19088]
**What would you like to be added**:
I'd like to see Heroku supported out of the box or at least, explained in the docs. Deploying Grafana on Heroku has a lot of pitfalls. So far, I've run into difficulties with port binding, buildpack configuration, https certificate, among others. And surprisingly, there is not even a mention of Heroku or any of these issues in the docs.

**Why is this needed**:
Heroku is an extremely popular hosting option. In our case, we just need to evaluate Grafana quickly without having to manage complex servers.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
