### ISSUE TITLE
Explore: When zooming in the logs graph, the table has entries but graph doesn't

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#19086]
**What happened**:
When zooming in the logs graph in Explore, the table has entries but graph doesn't. 
![image](https://user-images.githubusercontent.com/30407135/64849633-1619f280-d614-11e9-96f5-19b65bf6734d.png)

**What you expected to happen**:
See entries that are in the table in graph.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to Explore and choose Loki as a data source
- Run query e.g. `{job="varlogs"}`
- Zoom in to graph where graph bar is not displayed

You will see logs in the table, but not in graph

**Anything else we need to know?**:
Probably related to interval variable which I think does not change when zooming and is something like 15s by default. In dashboard this is computed automatically from graph width so maybe that part is missing in explore.

**Comment by torkelo** [comment]
I think in some of the refactorings / rewrites during 6.4 the update of queryIntervals has gotten lost, can't find where. 

My first thought is that it was lost in this PR https://github.com/grafana/grafana/pull/18694/ but can't find it being updated there either.
