### ISSUE TITLE
Custom calendar loses last minute of the day in time range by default

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#19094]
**What would you like to be added**:
While operating with timepicker calendar (custom time range) and clicking on some day it would be better to set "To" input field to 23:59:59.999 instead of 23:59:00

**Why is this needed**:
When you use Custom time range and pick "To" value with Calendar, Grafana automaticaly sets time part to 23:59:00. So the time range will not include the last minute of the last day in the chosen range. Yes, you can always manually tune up the time in the input field. But there are two problems with it:
1. (The most impotent!)) Most buisness users will not do such "difficult" manipulations but will worry their technical team why data differs from expected
2. Under the hood javascript uses time in milliseconds. So even manually setting time to 23:59:59 you will lose last second of the day

**Comment by torkelo** [comment]
Fixed in master, coming in 6.4
