### ISSUE TITLE
Incorrect day on calendar when server is UTC but local timezone is +X

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#19091]
**What happened**:
![GrafanaEndTimezone](https://user-images.githubusercontent.com/1506512/64854640-c690f200-d626-11e9-8c28-e5be4d1ae0f9.png)
I tried to set "To" part of time range on calendar. Pressed 12 June 2019. Input field had changed to correct value but calendar widget highlighted 13 June

**What you expected to happen**:
Calendar highlighted 12 June

**How to reproduce it (as minimally and precisely as possible)**:
1. Set dashboard timezone to UTC
2. Set your local browser timezone to +X (+3 for example)
3. Open custom time range widget
4. Try to set "To" field with calendar

**Anything else we need to know?**:
The reason of such behaviour is the Calendar component (from grafana-calendar package) does not support timezones at all (and its developer team does not want to support it: https://github.com/wojtekmaj/react-calendar/issues/135)
Calendar uses expressions like "new Date(year, monthIndex, daysInMonth)" to set dates. So when you set time part of current "To" date to 23:59, Calendar adds timezone shift and displays next day.
One of the possible solutions to this problem is to use original "moment" method utcOffset() with parameter keepLocalTime set to true (your DateTime wrapper does not support this parameter)
```javascript
const utcOffset = dateTime().utcOffset();
localToUtc(value) {
    return dateTime(value).utcOffset(0, true);
}
utcToLocal(value) {
    return dateTime(value).utcOffset(utcOffset, true);
}
```

**Environment**:
- Grafana version: 6.3.5
- Data source type & version:
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mckn** [comment]
Fixed when introducing the new TimePicker and also fixed when adding this PR #23586
