### ISSUE TITLE
Time range from & to as template variables

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1909]
Provide from & to time range as template variables. Useful when generating links in text panels.

**Comment by gilgamezh** [comment]
+1

**Comment by pilgrimkst** [comment]
+1

**Comment by mtanda** [comment]
+1

**Comment by mtanda** [comment]
@torkelo Do you think this feature still be useful?
I really want to this feature now, If I implement this feature, the PR is acceptable?

**Comment by torkelo** [comment]
should be, depends on the complexity of the implementation :)

**Comment by mtanda** [comment]
@torkelo Before start working, I want to confirm the feature spec.
Grafana support three date format for share link.
g1. 20160201T000000
g2. now-6h
g3. 1454284800000

And Kibana support two date format for share link. (parsed at https://github.com/elastic/kibana/blob/08fa20a858bc4b479ce6f975cdb3b72e5075e04f/src/ui/public/timefilter/timefilter.js#L96-L101)
k1. 2016-02-01T00:00:00.000Z
k2. now-6h

I want to support the k1 date format for Kibana user. (I don't use Kibana, but someone want to generate link from Grafana to Kibana) 
So, I think it is good idea to add templating editor for time range, and add date format option. (for k1 format, specify like "YYYY-MM-DDTHH:mm:ss.SSS[Z]")

![grafana_date_templating](https://cloud.githubusercontent.com/assets/224552/12773423/d26efe4e-ca7e-11e5-8ff4-39a99c89b57d.png)

It might increase the code, and become little complex.
But, without templating editor, user can't specify template variable name for the current time range.
So templating editor might be required.

If it is undesirable change, I'll use hard coded template variable name (like "$time_range_from", "$time_range_to"), and only support g3 date format.

How do you think? Which one is better for you?

**Comment by mtanda** [comment]
might be related, https://github.com/grafana/grafana/issues/4026

**Comment by pbooth** [comment]
Dunno if this helps, the use case for me is building things a like a dashboardf that has two rows of five graphs, each showing the same time range for mon,tue,wed,thu,fri for two weeks.
So if I could select from a list of 1d,2d,3d,4d,5d,6d,7d,8d,9d,10d,11d,... and use each as a time range - shift amount it would help me enormously.

**Comment by timeu** [comment]
Is there any solution for this issue ? 
Specifically it would be nice to access the current time range when using embedding a kibana dashboard as an iframe in order to pass in from and to to the iframe src url so that the same time range is displayed.

**Comment by mtanda** [comment]
@timeu If you really want this feature, apply this PR to your Grafana, and build Grafana yourself. (Sorry, I give up to merge the PR.)
https://github.com/grafana/grafana/pull/4348

**Comment by linar-jether** [comment]
Any hope this will be merged/supported?

**Comment by source-ram** [comment]
+1

**Comment by daire-byrne** [comment]
+1

**Comment by erowan** [comment]
+1

**Comment by DSTOLF** [comment]
@linar-jether could you please explain where exactly you used that angular directive to get the date?

**Comment by linar-jether** [comment]
Yes, used inside an HTML panel to show an iframe from a webservice for the current time range.

```html
<script type="text/javascript">
function dynamic_iframe(id,content, width, height)
{
    var timeRange = angular.element('grafana-app').injector().get('timeSrv').timeRange();

    document.getElementById(id).innerHTML = "<iframe width='" + width + "' height='" + height + "' frameborder='0' src=" + content + "?from=" + (timeRange.from / 1000) + "&to=" + (timeRange.to / 1000) + "><\/iframe>";
}
</script>
<div  style="text-align:center;" >
<div id="container" ></div>
<br/>
<a href="javascript: void(0)" onclick="dynamic_iframe('container', 'http://example.com/path/to/url', 640, 700); ">Show</a>
```

**Comment by DSTOLF** [comment]
@linar-jether thanks for the tip, I've managed to get a Kibana iframe working inside a Grafana dashboard using the dashboard's time range.

In case anyone gets here looking for a way to make a Kibana iFrame use Grafana dashboard's time range, here's the workaround. Everytime you change the time range or a template variable, you need to click the refresh link. I know it's not very neat, but it's the best I could do.

Regards.

```javascript
<script type="text/javascript">
function dynamic_iframe(id, width, height)
{
    // get timezone offset
    var offset = (new Date().getTimezoneOffset()*60*1000);  
    // get Grafana's time range
    var timeRange = angular.element('grafana-app').injector().get('timeSrv').timeRange();
    // convert Grafana's unix timestamp to a readable time format and add browser timezone offset
    var temp_date_from = new Date(timeRange.from+offset);
    var temp_date_to = new Date(timeRange.to+offset);
    // now convert time range to the same format used by kibana
    var date_from = temp_date_from.getFullYear()+'-'+('0'+(temp_date_from.getMonth()+1)).slice(-2)+'-'+('0'+temp_date_from.getDate()).slice(-2)+'T'+('0'+temp_date_from.getHours()).slice(-2)+':'+('0'+temp_date_from.getMinutes()).slice(-2)+':'+('0'+temp_date_from.getSeconds()).slice(-2)+'.000Z';
    
    var date_to = temp_date_to.getFullYear()+'-'+('0'+(temp_date_to.getMonth()+1)).slice(-2)+'-'+('0'+temp_date_to.getDate()).slice(-2)+'T'+('0'+temp_date_to.getHours()).slice(-2)+':'+('0'+temp_date_to.getMinutes()).slice(-2)+':'+('0'+temp_date_to.getSeconds()).slice(-2)+'.000Z';

    // insert kibana iframe here
    // remember to change 'from' and 'to' time range to use your own time variables
    // you can also use template variables inside the query clause 
    // column:$templatevar
    document.getElementById(id).innerHTML = "<iframe src=\"http://yourkibana.domainl/app/kibana#/visualize/create?embed=true&type=table&indexPattern=oracle-database&_g=(refreshInterval:(display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:'" + date_from + "',mode:absolute,to:'" + date_to + "'))&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'*')),uiState:(),vis:(aggs:!((id:'1',params:(),schema:metric,type:count),(id:'2',params:(filters:!((input:(query:(query_string:(analyze_wildcard:!t,query:'column:$templatevar'))),label:'')),row:!t),schema:split,type:filters)),listeners:(),params:(perPage:10,showMeticsAtAllLevels:!f,showPartialRows:!f),title:'New%20Visualization',type:table))\" height='"+height+"' width='"+width+"'><\/iframe>";
}
</script>
<div  style="text-align:center;" >
<div id="container" ></div>
<br/>
<a href="javascript: void(0)" onclick="dynamic_iframe('container', 900, 600); ">Refresh</a>
```

**Comment by linar-jether** [comment]
Note that i used the link to load the iframe just for my specific use case(want the request made only on demand)..
you could hook into the angular refresh event and automatically refresh your frame using something like this  https://github.com/grafana/grafana/issues/1816#issuecomment-137827966

**Comment by DSTOLF** [comment]
@linar-jether thanks for the tip, I'll test it later.

**Comment by janceChun** [comment]
+1

**Comment by aghid** [comment]
@DSTOLF, @linar-jether , thanks guys for posting the code, it really helped me with embedding kibana.
@DSTOLF, I am unable to use template vars inside the iframe code, it always shows the actual str ($templatevar) and not the value. What am I missing? 
Also, what panel did you use to create your custom panel? I would like to make a generic kibana embedding panel that accepts iframe code (or part of it) as input.
@linar-jether, is there a way to get the time range in the "quick" format ("now-1d")?

**Comment by linar-jether** [comment]
@aghid just use this instead: 
```javascript
angular.element('grafana-app').injector().get('timeSrv').timeRangeForUrl()
```

**Comment by aghid** [comment]
Thank you @linar-jether 
It works

**Comment by GVHitHub** [comment]
Is this feature done? It will be useful as it is not that flexible to use with only $timeFilter.. At least $timeFrom and $timeTo is required...

**Comment by Niflou** [comment]
+1 would be very useful

**Comment by 1stdemon** [comment]
+1

**Comment by LukeK1887** [comment]
+1 would be realy great having this feature.

**Comment by jaune-rouge** [comment]
+1

**Comment by davbizz** [comment]
+1

**Comment by oleg-glushak** [comment]
+1

**Comment by d-ulyanov** [comment]
+1
timestamp format in seconds pls

**Comment by ingenuity2k** [comment]
+1
from & to as unix timestamps and time range in seconds or ms please.

**Comment by xiequanqin** [comment]
+1

**Comment by xiequanqin** [comment]
$__timeFrom() didn't work in generating links

**Comment by freko247** [comment]
+1

**Comment by iShift** [comment]
+100500

**Comment by sudheeral** [comment]
+1

**Comment by PoulpiFr** [comment]
+1

**Comment by jchanam** [comment]
+1

**Comment by sunilkukde** [comment]
+1

**Comment by konlux** [comment]
+1 pls

**Comment by Wander1024** [comment]
+1

**Comment by roffe** [comment]
+1

**Comment by tdrisdelle** [comment]
+1

**Comment by tejaskale** [comment]
+1

**Comment by kawmarco** [comment]
+1

**Comment by nayeemnayyu** [comment]
+1

**Comment by lisbakke** [comment]
+1

**Comment by myhau** [comment]
+1

**Comment by zegerhoogeboom** [comment]
I'm also in need of this, if anyone is interested, I implemented this for InfluxDB. See [this change](https://github.com/zegerhoogeboom/grafana/commit/e1bb6e16c9d60c5b239ce9e5700a945d196d0003#diff-59526bea47ed4559f9527e5d1fc3c541) on my fork, it allows for querying e.g. `WHERE time >= $timeFrom - 12h ...`.

**Comment by phlenoir** [comment]
+1

**Comment by 1ennier** [comment]
+1

**Comment by 1ennier** [comment]
Any workaround for passing time range between dashboards?

**Comment by mjtrangoni** [comment]
+1

**Comment by Dchamard** [comment]
+1

**Comment by luongvo209** [comment]
+1

**Comment by liuchunhui** [comment]
+1

**Comment by DanielChristow** [comment]
+1

**Comment by jcajkovic** [comment]
+1

**Comment by ss6s** [comment]
+1

**Comment by cgoswami** [comment]
+1

**Comment by maxreb** [comment]
I think I got it. With this snippet the html will refresh as the user press on the refresh button in grafana or changes the time. It's quite hacky, but works like a charm here with grafana 5.1.1:

```
<script type="text/javascript">
  refreshGeoMap();
    
  angular.element('grafana-app').injector().get('timeSrv').$rootScope.$on('refresh', function(event, data) { refreshGeoMap(); });
  function refreshGeoMap( )
  {
    var timeRange = angular.element('grafana-app').injector().get('timeSrv').timeRange();
    document.getElementById("demo").innerHTML =  "&channel=$channel&gatewayids=$gatewayid&from=" +timeRange.from + "&to=" + timeRange.to;
  }
</script>
<p id="demo"></p>
```

greetz,
Max

**Comment by datbayev** [comment]
Isn't this implemented:
http://docs.grafana.org/reference/templating/#the-timefilter-or-timefilter-variable

**Comment by lostapathy** [comment]
@datbayev Not as far as I can tell.  What you linked seems to only work in queries - and cannot be used in the output of a dashboard, such that one dashboard can link to another and persist the time range between the two.

This would be super useful.

**Comment by cby016** [comment]
+1 for this feature. I'm in need of a [range variable](http://docs.grafana.org/reference/templating/#the-range-variable) for other datasources besides Prometheus.

**Comment by demospace** [comment]
+1 

This feature will save many users many clicks. Moving between dashboards and having to change the time_from and time_to continually to match the current investigation is a huge waste of time.

Is there a reason PR #4348 wasn't accepted? That looks like it provides exactly what we need for this...?

**Comment by acolliot** [comment]
Grafana is now part of our analysis process with several tools 'linked' together using http links containing time range.

Easy to create links to Grafana passing &from=XXXto=XXX parameters but no way to easily create this kind of links into Grafana dashboard to other tools with such time range parameters.

Definitively need, at least, these $__time_to & $_time_from variables in epoch format.

Then, a new type of variable (date/time) could be created with : 
- Different formatting options : epoch, Iso, user defined ...
- Values : $__time_XXXX variables, calculated dates, user selected dates via Calendar style UI

**Comment by philippreston** [comment]
+1 or some other way to pass time ranges between dashboards

**Comment by torkelo** [comment]
An initial basic version of this has been implemented and merged to master and will be available in v6. 

$__from and $__to  is now two new built-in variables. Currently, they will only be interpolated to millisecond epochs, no other format is yet supported. We can add new formats in new issues depending on need for specific date formats.

**Comment by shavetasidana** [comment]
i used $__from variable in mysql query like this:
select from_unixtime(($__from/1000),"%Y-%m-%d") as "startdate" from DUAL;
But the date is converting to 1 day before. I suspect __from variable is returning incorrect value. I have set my dashboard timezone as UTC. I have to add my GMT  time difference to get the correct date.
Date range on my dashboard is Previous week i.e from(2019-04-21 00:00:00 to 2019-04-27 23:59:59).
grafana version is 6.0.2
My query is returning date as 2019-04-20 whereas It should be 2019-04-21.
Could you please check?

 I have configured my dashboard to consider UTC time so I think $__from variable should also consider UTC time only.

**Comment by suikast42** [comment]
> An initial basic version of this has been implemented and merged to master and will be available in v6.
> 
> $__from and $__to is now two new built-in variables. Currently, they will only be interpolated to millisecond epochs, no other format is yet supported. We can add new formats in new issues depending on need for specific date formats.

I want to link a grafana dashboard to a kibana dashboard. But the timestamp format is not accepted by kibana.  Timegormats can be very useful ;-)

**Comment by Shubhamnegi** [comment]
> > An initial basic version of this has been implemented and merged to master and will be available in v6.
> > $__from and $__to is now two new built-in variables. Currently, they will only be interpolated to millisecond epochs, no other format is yet supported. We can add new formats in new issues depending on need for specific date formats.
> 
> I want to link a grafana dashboard to a kibana dashboard. But the timestamp format is not accepted by kibana. Timeformats can be very useful ;-)

+1 for this. Need date in iso format to link grafana and graylog

**Comment by Theoooooo** [comment]
Also why are we able to use both of the variables outside of the query editor but not all the others variables like $__interval or $__dashboard ?

**Comment by sta-szek** [comment]
@torkelo is there ticket to add more variables with time (different formats) or provide formatting option for `$__from` and `$__to` so we can format it to ISO8061 and finally make valid kibana URL?
