### ISSUE TITLE
Improve guide descriptions on docs start page

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#19109]
Descriptions for the Guides on the documentation [start page](https://grafana.com/docs/) has some redundancies, and inconsistent style. This is the first page you see as a new user of Grafana, so I think it deserves some extra attention. First I'll highlight a couple of issues, then a suggestion on how to improve the descriptions.

### Redundant information

Example:

> Getting Started
> A guide that walks you through the basics of using Grafana

_guide_ here is redundant since it's under a heading that says "Guides".

### Inconsistent punctuation

Some descriptions end with punctuations, some don't.

### Improvement proposal

I believe that instead of describing what the guide _is_, I think it'll be clearer if presented in a format that makes it clearer what I will gain/learn as a reader.

Some suggestions:

Getting Started
> Learn the basics of using Grafana

Provisioning
> Learn how to automate your Grafana configuration

What's new in v6.3
> Explore the features and enhancements in the latest release

**Comment by bharjala** [comment]
I don't believe anyone's worked on this one yet. I'm on it!
