### ISSUE TITLE
Add new grafana theme

### ISSUE THREAD

**Issue by Unrealnew** [grafana/grafana#19106]
I need to create a new grafana theme in addition to the default one dark/light (no new  page or functionality only new color theme). Thanks to the information obtained here: 

- https://grafana.com/docs/project/building_from_source
- https://www.neteye-blog.com/2017/12/how-to-customize-your-grafana-theme/

I am now able to change the dark and light themes but not to add new ones that can be chosen in grafana preferences or ini configuration file (example "red" theme.)
Unfortunately I did not find very useful the information found here:

- https://github.com/grafana/grafana/blob/master/style_guides/themes.md

What are the necessary steps to get the final result?
Your help in this matter was much appreciated.

**Comment by papagian** [comment]
Adding custom themes is not supported.
