### ISSUE TITLE
Increase the efficiency of DB requests by only querying for new data within a range of time

### ISSUE THREAD

**Issue by pushshift** [grafana/grafana#19105]
For this example, I'll use InfluxDB. Currently, Grafana will make a request to InfluxDB for the entire range of time shown on the chart. For instance, if the chart shows the previous six hours, each time the chart updates, Grafana queries for the previous six hours. This can cause performance issues, especially if there are many graphs accessing InfluxDB.

My proposal is to have an option where Grafana first makes a request for the entire timeline range of data (6 hours) to first populate the graph. On subsequent requests, provide an option so that Grafana only queries the most recent data and uses the data from the initial call as a cache.

Here's an outline:

1) Grafana makes a call to the DB for the previous six hours of data.
2) Grafana populates the chart and caches each time segment in memory.
3) When the next update cycle occurs, Grafana only requests the range of data during the time elapsed between the last call plus a configurable multiplier (in the event the user believes data could change further back in time from when the last request was made.
4) Grafana then uses the cached data from the previous call and combines it with the new call to redraw the chart.

If the update interval was 5 seconds, Grafana would fetch perhaps the last 5 minutes of data instead of requesting the entire 6 hour chunk. This would greatly reduce load on the backend while still providing full functionality on the front-end.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
