### ISSUE TITLE
Change datasource to data source in documentation

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#19111]
We should update any occurrences of "datasource" to "data source" in the documentation. Identifiers such as URLs or code should should not be included when fixing this issue.

Find occurrences by running `grep`:

```
cd ./docs
grep -R "datasource" *
```

**Comment by bharjala** [comment]
I'm currently working on this issue. I'm committing my changes with each folder, instead of all at once. They all have this comment: Docs: Replace "datasources" with "data sources" (#19111)

**Comment by marcusolsson** [comment]
Closed by https://github.com/grafana/grafana/pull/19238
