### ISSUE TITLE
URL should be uppercased in documentation

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#19110]
URL is an acronym and should be uppercased. There are so many occurrences to list in this issue, but your can list (some of) them by running `grep` in the docs directory:

```
cd ./docs
grep -R " url " *
grep -R " Url " *
grep -R " urls " *
```

**Comment by MuhtasimTanmoy** [comment]
I would like to work on this. Having a look at [CONTRIBUTING.md](https://github.com/grafana/grafana/blob/master/CONTRIBUTING.md). Is there anything else I need to know?

**Comment by marcusolsson** [comment]
Sounds good! `CONTRIBUTING.md` should cover most things.

We're also currently working on contribution guidelines and style guide for documentation. They aren't merged yet, but they might be of some use.

https://github.com/grafana/grafana/pull/19108
https://github.com/grafana/grafana/pull/19190

**Comment by MuhtasimTanmoy** [comment]
Have a look at here [notifications.md](https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md).

URL should be uppercased in Webhook section?

Example json body:
```json
{
  "title": "My alert",
  "ruleId": 1,
  "ruleName": "Load peaking!",
  "ruleUrl": "http://url.to.grafana/db/dashboard/my_dashboard?panelId=2",
  "state": "alerting",
  "imageUrl": "http://s3.image.url",
  "message": "Load is peaking. Make sure the traffic is real and spin up more webfronts",
  "evalMatches": [
    {
      "metric": "requests",
      "tags": {},
      "value": 122
    }
  ]
}```

**Comment by marcusolsson** [comment]
Code blocks are typically sensitive to these changes. Looks like `imageUrl` is part of the webhook API schema, so we should probably leave this as is.

**Comment by oddlittlebird** [comment]
What is the status of this issue?

**Comment by jeet-parekh** [comment]
I could pick this up... looks pretty simple

**Comment by oddlittlebird** [comment]
Have at it! Thanks!
