### ISSUE TITLE
Graph rendering gaps using InfluxDB 0.8 as backend

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#1912]
I'm running Grafana 2.0.2 w/ InfluxDB 0.8 as the backend.

In some instances, we are seeing rendering gaps when drawing some graphs. The instances are usually when a time span of >1d is selected. If I zoom in on the gap in data, the graph is rendered correctly. When running the query manually in the InfluxDB Data Interface, the results do not show the same gap in data. I've tried both Flot and PNG options, but both return the same gap in data.

Here's an example of the gaps we're seeing:
![screen shot 2015-04-29 at 2 46 40 pm](https://cloud.githubusercontent.com/assets/5559459/7402162/9c7ab2ba-ee7e-11e4-9857-9290603f1668.png)

If I zoom in on the gap, I get the following:
![screen shot 2015-04-29 at 2 47 55 pm](https://cloud.githubusercontent.com/assets/5559459/7402183/cae3de4c-ee7e-11e4-8ebb-49cb9a9fabff.png)

Here is output from the InfluxDB Data Interface, using a sum(value) merge on the series:
![screen shot 2015-04-29 at 2 52 33 pm](https://cloud.githubusercontent.com/assets/5559459/7402281/6e38c7c4-ee7f-11e4-8069-62b788af32f0.png)

Has anyone else observed this (I didn't see anything in the open issues)? Is there a debugging output that I could provide to a developer to repro this issue, and identify the cause?

**Comment by ecables** [comment]
Update: The problem appears to only be on individual series; a 'sum(value) merge(series here)' appears to render correctly while a 'mean(value) /series regular expression here/' reproduces the gaps. I was able to fix the gaps by removing a 'WHERE value > 0' expression in the query.

Any idea why a 'WHERE value > #' expression would cause the gaps shown above?

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/7406672/8387c872-ef07-11e4-9965-56fc4bb7a21c.png)

I think this is the same as an issue that has been reported a number of times, please search before opening a new issue :)

There is even a help section in the influxdb query editor "stacking & fill" that will help you with this. try fill(0) in your query, and specify a minimum group by time the group time field below your queries, like >10s (if you sample data every 10s)

#1102, #1251, #1011, #1282, #705
#721, https://github.com/grafana/grafana/issues/1856

**Comment by ecables** [comment]
Unfortunately we already use fill(0) and group by 60s for this, and other offending queries, but the problem persists until I remove 'value > #' from the query. Do you have any other suggestions?

**Comment by torkelo** [comment]
no, strange, maybe something wrong with influxdb group by with where filter

**Comment by ecables** [comment]
Any suggestions? Can we re-open this issue, as it is not a duplicate of another? I can provide output of influx queries for affected series if that would help diagnose this problem.

As mentioned, the solutions I've found to solve this are to:
- Remove any 'value > #' expressions
- ctrl+click the affected series, removing it from the graph, resulting in data being returned.

Before I ctrl+click:
![screen shot 2015-05-01 at 10 32 57 am](https://cloud.githubusercontent.com/assets/5559459/7434174/7e84cec4-efed-11e4-9230-dc5a8cf8e543.png)

After I ctrl+click on the affected series:
![screen shot 2015-05-01 at 10 33 39 am](https://cloud.githubusercontent.com/assets/5559459/7434178/8fc68a38-efed-11e4-9bc6-89bc7cbdfd82.png)

Removing "value > 0" expression from query:
![screen shot 2015-05-01 at 10 34 31 am](https://cloud.githubusercontent.com/assets/5559459/7434190/b5ecce66-efed-11e4-91bc-795a1e2cd898.png)

I have fill(0) enabled on this query, as previously mentioned.

**Comment by torkelo** [comment]
You can always check the data returned from InfluxDB using chrome dev tools. Somehow it is returning null values when you add the value > 0. 

Are your really having fill(0) in the query? Try different group by times to see if that makes a difference. The only cause for such a graph would be null values in the series, but if you have fill(0) that should not be possible unless you have written null values somehow.

**Comment by ecables** [comment]
I'm seeing this behavior across many different dashboards / queries; here's an example raw query, showing fill(0):
select mean(value) from /ipv4.$POP.as_path.$ASPATH/ where $timeFilter and value > 10000000 group by time($interval) fill(0) order asc

Here's what that query looks like visually, when an affected series is present:
![screen shot 2015-05-01 at 11 24 24 am](https://cloud.githubusercontent.com/assets/5559459/7435035/a9d4ae26-eff4-11e4-8843-f99e0dd0ebb6.png)

**Comment by torkelo** [comment]
what do you mean affected time series, what is special about  the time series, can you zoom in on the region where the series drops, and inspect the data returned by influxdb (chrome dev tools(F12), networks tab)

**Comment by torkelo** [comment]
are you sure "value > 10000000" is not filtering out a bunch of series?

**Comment by ecables** [comment]
The goal /is/ to filter out series that are below a threshold, as some queries would otherwise result in hundreds of series that are of insignificant value to the visualization / goal of the query.

In this particular case I don't want to see series below that value; in other cases I don't want to see series with a value less than 1... it depends on the context of the query.

Here's output before:
![screen shot 2015-05-01 at 2 14 24 pm](https://cloud.githubusercontent.com/assets/5559459/7437475/77b53f56-f00c-11e4-9f60-c2f3dfc252fd.png)

Zoomed in at the point of failure:
![screen shot 2015-05-01 at 2 14 44 pm](https://cloud.githubusercontent.com/assets/5559459/7437476/7c71765e-f00c-11e4-8916-ee1ffefbcb88.png)

**Comment by ecables** [comment]
One comment is that the tooltip values for all returned individual series after the dropoff shows 0, whereas the Total query (separate sum(value) merge(series) query) maintains accurate tooltip values.

**Comment by ecables** [comment]
Here are some point values using chrome dev tools, networks tab:
![screen shot 2015-05-01 at 2 27 28 pm](https://cloud.githubusercontent.com/assets/5559459/7437654/40959438-f00e-11e4-9507-abe5fbe82b16.png)

**Comment by torkelo** [comment]
Ok,  if influx return zeros it's an issue with influx, not a problem with grafana.
