### ISSUE TITLE
Click on "Copy Invite" shows broken layout

### ISSUE THREAD

**Issue by patrickjuchli** [grafana/grafana#19123]
**What happened**:

In Configuration > Users, I switched to "Pending invites" and then clicked on "Copy invite". Then I saw a pretty broken layout. See screenhot.

<img width="1440" alt="Screenshot 2019-09-16 at 13 05 58" src="https://user-images.githubusercontent.com/397839/64953307-ce4cd280-d882-11e9-9782-6f26e2725df8.png">

**What you expected to happen**:

A regular screen.

**How to reproduce it (as minimally and precisely as possible)**:

Follow description above.

**Environment**:
- Grafana version: 6.3.5
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac 10.14.6, Firefox 69

**Comment by torkelo** [comment]
Strange, unable to replicate. Nothing happens for me (other than link being copied to clipboard)

**Comment by aocenas** [comment]
Can reproduce on firefox (only). Seems like the copy is done by creating a text area with text selecting and copying but on firefox the text area is kept in html and focused scrolling the screen to it.
