### ISSUE TITLE
Text panel in HTML mode not applying styles

### ISSUE THREAD

**Issue by artjomzab** [grafana/grafana#19120]
**What happened**:

Added a Text panel to my dashboard.  Selected HTML mode and supplied following HTML:

```
<div style="display: flex; height: 100%;  justify-items: center; align-items: center; ">
  <h2 style='text-align:center; width: 100%;'>Local I/Os</h2>
</div>
```

`justify-items: center; align-items: center;` are not applied.

**What you expected to happen**:

All attributes within style attribute should've been applied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add text panel to dashboard
2. Select HTML mode
3. Paste above HTML
4. Save
5. See that `justify-items: center; align-items: center;` is not applied
6. Open developer console and add justify-items: center; align-items: center; manually to the div to see how it should look like.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: v6.3.3 (84d0a71) 
- User OS & Browser: Chrome 76.0.3809.132

**Comment by aocenas** [comment]
This is due our sanitizing method which by default also sanitizes style attributes according to a whitelist: https://github.com/grafana/grafana/blob/75c29566a619c3334f7045767b8c9ec819b6a45b/public/app/core/utils/text.ts#L92

It is possible to circumvent this right now with `disable_sanitize_html = false` in config but that disables any sanitization which is not recomended.

Need to find out what is the whitelist of css attributes actually preventing before trying to remove it.

**Comment by iyuvalk** [comment]
So.... Is there a way to center text on a text panel in Grafana now?

**Comment by torkelo** [comment]
just add class `text-center`

**Comment by iyuvalk** [comment]
My god you're fast.... I just came back to delete my stupid question... (-:
Thanks for the super fast support.
