### ISSUE TITLE
Datapoints outside time range, of course.

### ISSUE THREAD

**Issue by axelabs** [grafana/grafana#1913]
I'm running grafana 2.0.1 and influxdb 0.8.8 on one server.  When viewing my metric (select * from "foo") and setting the time to last 5m, the chart keeps displaying "Datapoints outside time range" unless I select time range bigger then when I started collecting data.  Its sort of obvious that past datapoints are out of the small range I'm viewing...  How do I disable this warning?

**Comment by axelabs** [comment]
This seems to stem from my miss-understanding of the raw query.  When I chose the series with autocomplete, the message disappeared:
![raw](https://cloud.githubusercontent.com/assets/1413585/7402821/6a8ce374-ee95-11e4-9210-5c967de49c03.png)
![autocomplete](https://cloud.githubusercontent.com/assets/1413585/7402822/6e6c2e8c-ee95-11e4-8d87-7ec6bfab9de4.png)

**Comment by torkelo** [comment]
yepp, rawQuery needs a `where $timeFilter order asc`  (you can see this if you use the editor and then switch to raw query mode
