### ISSUE TITLE
Add documentation style guide

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19134]
The style guide topic should be alongside the documentation contribution topic.

It should start with what the base style guide is (I like Microsoft Style Guide). It will include things like:

- Places where the Grafana style guide differs with MSG (like click vs. tap vs. select).
- Quick reference for word usage, heading guidelines, and so on.

**Comment by torkelo** [comment]
we have style guides (incomplete) here https://github.com/grafana/grafana/tree/master/style_guides

and they are linked to from the contributing doc. But I assume you mean docs styles?

**Comment by oddlittlebird** [comment]
Yes, a documentation style guide. I am working with Marcus Olsson on making
it easier for people to contribute to and maintain the docs.
