### ISSUE TITLE
Default Timepicker Settings 

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#1914]
It appears that as of Grafana 2.0.2, the default row height was changed to 250 px. What is the correct approach to changing this behavior to a different value, say 350 px?

Are there plans to include global default settings in the interface, such as row height and timepicker options?

**Comment by torkelo** [comment]
The default has always been 250px. 

No plans currently to have a config for this.

**Comment by ecables** [comment]
Strange. When I upgraded from 2.0.0-Beta3 -> 2.0.02 the graphs all became "smooshed," as though this changed.

![screen shot 2015-04-30 at 8 26 46 am](https://cloud.githubusercontent.com/assets/5559459/7416218/aca4f544-ef12-11e4-8740-cb07285798ab.png)

Any ideas?

**Comment by torkelo** [comment]
There was a change (or fix) to how graph height and legend height was calculated. In grafan 1.9 the graph legend (in table mode) could push the graph panel to extend beyond its allowed row height. In v2.0 the graph will be reduced in height (up 50%) to accommodate the legend, if the legend needs more than 50% it will push the panel beyond the row height. This fixed panel alignment (so panels are the same height on row), and fixed rendering panels with a legend to images (needs to know the height of the panel + legend before rendering)

**Comment by druchoo** [comment]
@torkelo Does your statement "No plans currently to have a config for this." also apply to the time picker?

**Comment by mkeagar** [comment]
@torkelo I would also like to see the ability to change the Default Timepicker Settings for new dashboards. This would be very useful, even if it were a configuration file option, rather than inside the web-ui. Great work so far.  Really loving what you are doing with Grafana!
