### ISSUE TITLE
Option to select multiple alerts and pause them

### ISSUE THREAD

**Issue by suraganijanakiram** [grafana/grafana#19153]
Hi Team,

A option to select multiple alerts and pause them

This will be use full when we are doing an activity in the data center level  or hosts level.

like i am doing activity on multiple hosts think 30 servers what to select those alerts and pause them.

![image](https://user-images.githubusercontent.com/24495314/65013991-cbadb400-d93a-11e9-997e-c53cc08ea5c1.png)

**Comment by torkelo** [comment]
the plan is to solve this using silence rules https://github.com/grafana/grafana/issues/5856
