### ISSUE TITLE
Option to keep message at condition level instead of Notifications

### ISSUE THREAD

**Issue by suraganijanakiram** [grafana/grafana#19155]
Hi Team ,

First special thanks to every one who is working on this you guys are doing a great job.

A option to put message at the condition level is more useful since we will write multiple conditions 

suppose if you are monitoring the cpu,disk,memory and swap in the same dashboard 

it will be easy to identify which alert we got and also include the threshold in the email alert will be helpfull.
 
Getting like below :

![image](https://user-images.githubusercontent.com/24495314/65014671-f6990780-d93c-11e9-86f1-5b27cebc7628.png)

It should be like below:

![image](https://user-images.githubusercontent.com/24495314/65015515-69a37d80-d93f-11e9-94f7-25fb61a92b8a.png)

And in the condition it should be like below

![image](https://user-images.githubusercontent.com/24495314/65015549-7fb13e00-d93f-11e9-91b2-83e01967949a.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
