### ISSUE TITLE
Expore: Live tail buttons UI improvements

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#19166]
After merging https://github.com/grafana/grafana/pull/19143 there are some improvements that still needs to be done:

- [ ] Meta labels change
- [ ] Change to what is shown after live tail stops
- [x] Animating button state change
- [x] Live tail button margin
- [x] Live tail button paused state flash animation color  (#8e8e8e)
- [x] Run button corners should be round when live
- [x] "in live mode" and "normal mode" transition

**Comment by aocenas** [comment]
@ivanahuckova do you think this can be closed? I think those missing items are either obsolete anyway or you already implemented it.

**Comment by ivanahuckova** [comment]
Yes, I was looking at this issue last week and I was thinking the same. So I am closing it. 🙂
