### ISSUE TITLE
LinkButton does not have property disabled

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#19179]
**What happened**:
I was implementing `<LinkButton />` in a component and according to the storybook it is supposed to have a disabled prop. Adding this Typescript threw an error saying:
 ```
TS2322: Type '{ children: string; size: "xs"; variant: "secondary"; disabled: boolean; href: string; target: string; }' is not assignable to type 'IntrinsicAttributes & LinkButtonProps & { children?: ReactNode; }'.
  Property 'disabled' does not exist on type 'IntrinsicAttributes & LinkButtonProps & { children?: ReactNode; }'. 
```
went to source in grafana/ui and it seems that `<LinkButton />` extend from `CommonButtonProps, AnchorHTMLAttributes<HTMLAnchorElement> {}`. 

**What you expected to happen**:
Expected `<LinkButton />` to have prop `disabled`.

**How to reproduce it (as minimally and precisely as possible)**:
Implement a `<LinkButton />` and add disabled prop

**Comment by torkelo** [comment]
think link (anchor tags) do not have a disabled html attribute so needs to to be added to CommonButtonProps and mapped to class

**Comment by peterholmberg** [comment]
Yes, that is what's happening. However, if I add disabled to `CommonButtonProps` it will conflict in `ButtonProps`

```
TS2320: Interface 'ButtonProps' cannot simultaneously extend types 'CommonButtonProps' and 'ButtonHTMLAttributes<HTMLButtonElement>'.
  Named property 'disabled' of types 'CommonButtonProps' and 'ButtonHTMLAttributes<HTMLButtonElement>' are not identical. Alt+Shift+Enter Alt+Enter
```
so I think it needs to get added to the `LinkButtonProps` interface

**Comment by torkelo** [comment]
ah, your right. has to be added to LinkButtonProps
