### ISSUE TITLE
Problems with render in 6.3.5

### ISSUE THREAD

**Issue by xenon007** [grafana/grafana#19182]
**What happened**:
Unable render panel... Panel have a data but render is empty.
**What you expected to happen**:
Rendered panel image
**How to reproduce it (as minimally and precisely as possible)**:
Share > Direct link rendered image or via curl
**Anything else we need to know?**:
we use a rendered images for sending to mail or chats  downloading them via curl 
in previous version all works fine
**Environment**:
- Grafana version: 6.3.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: SUSE Linux Enterprise Server 12 (x86_64)
- User OS & Browser: Chrome (76.0.3809.100)
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
how long does the query take?

**Comment by xenon007** [comment]
> how long does the query take?

65-66ms

**Comment by torkelo** [comment]
any template variables being used?

**Comment by xenon007** [comment]
nope

**Comment by torkelo** [comment]
Does it work for other graphs?

**Comment by xenon007** [comment]
no

**Comment by torkelo** [comment]
Strange, no other reports like this. Somehow your query is not returning any data when queried from the headless browser running server-side.

Try our new image rendering plugin:
https://grafana.com/grafana/plugins/grafana-image-renderer
