### ISSUE TITLE
Feature request: report on broken dashboards +/- graphs needing remediation

### ISSUE THREAD

**Issue by afelle1** [grafana/grafana#1918]
After we initially build dashboards around different services and concerns, the metrics behind them change or go away leaving us with graphs and whole dashboards that are broken and need to be repaired or deleted.  As this is a very common concern, it would be nice to have a way to report on dashboards that haven't been used in a long time or contain graphs that are broken / fail pulling data from configured time-series backend.

**Comment by torkelo** [comment]
You do see graphs that fail with the red warning triangle in the corner. 

This sounds like a good idea, but there are many many more enhancements that feel more important.

**Comment by torkelo** [comment]
And at some point too many features are a bad thing :)

**Comment by afelle1** [comment]
You're right: dashboards that individuals and teams create will indicate their are problems and they should see the warning and fix accordingly.

I'm coming at this more from a maintenance perspective where we need to identify issues like this broadly across 100s of dashboards where looking at them individually isn't viable.  By identifying old +/- broken dashboards, we can ensure people are seeing current and useful dashboards.find what they're looking for.

**Comment by torkelo** [comment]
yea, one feature I want to add in the future is to be able to sort dashboards by views or popularity (starts or just how frequently they are used)
