### ISSUE TITLE
A centralise bars option on the Bar Gauge visualisation

### ISSUE THREAD

**Issue by rcjcooke** [grafana/grafana#19184]
**What would you like to be added**:
I'd like to see a "centralise bars" option on the Bar Gauge so that I can use them to create "Funnel chart" style visualisations. They look like the kind of charts you show population demographic breakdowns with.

**Why is this needed**:
I can see this being more generally useful, but in this instance I'd like to visualise the Work In Progress of my team in various stages of the value stream at a given moment based on data pulled from a work management tool (JIRA in our case).

**Comment by torkelo** [comment]
can you describe what you mean by centralize?

**Comment by rcjcooke** [comment]
Like you would centralise text rather than left or right align. i.e. the vertical axis is in the centre of the graph rather than on one edge and each bar is symmetrical around the axis. Does that make sense? I'll try and find an appropriate image to attach here as an example.

**Comment by rcjcooke** [comment]
I just knocked this up in Excel as an example:
![Screenshot 2019-09-18 at 09 59 56](https://user-images.githubusercontent.com/18526483/65133767-1e4ea500-d9fb-11e9-80df-f7e495b615f0.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
