### ISSUE TITLE
Prometheus: Recording rule expansion fails with multiple selectors

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#19196]
0. Explore with Prometheus that also has recording rules defined
1. Run a query that uses a recording rule, e.g., `instance:node_load1_per_cpu:ratio{job="default/node-exporter", instance="abc"}` from the node mixin
2. Click on "Expand rules".

Result: The selector is outside the braces, which looks right, but is not a valid query.
```
(node_load1{job="default/node-exporter"} / instance:node_num_cpu:sum{job="default/node-exporter"}){job="default/node-exporter", instance="abc"}
```

Expected:
```
(node_load1{job="default/node-exporter", instance="abc"} / instance:node_num_cpu:sum{job="default/node-exporter", instance="abc"})
```

**Comment by miqh** [comment]
Hi @davkal,

I had a look at this issue out of interest and I think the underlying problem isn't limited to just using multiple selectors on a recording rule.

As an example, I could have a recording rule `level:metric:op` defined as `avg(rate(count[5m])) by (job, service)`. I could then use it in a query such as `level:metric:op{service="foo"}`. If I'm not mistaken, expansion would mean preserving the selector across all metrics, so the target result is `avg(rate(count{service="foo"}[5m])) by (job, service)` to be well-formed. However, the expansion code appears quite basic (i.e. just prepends the selector):

https://github.com/grafana/grafana/blob/fe8d0d27d28bc3d5fd0d86a474185c076ed883fa/public/app/plugins/datasource/prometheus/language_utils.ts#L103-L107

Another example recording rule might have multiple metrics within the expression, in which case the selector applied on the recording rule should apply to all expanded metrics.

The problem gets even more complex if the recording rule not only uses selectors, but functions and other operators too.
