### ISSUE TITLE
Alerting: Add Equals as a alert condition 

### ISSUE THREAD

**Issue by atlasW** [grafana/grafana#19193]
I expect the monitored value to trigger an alarm at 0. So I set the alarm condition of "is within range 0 to 0", but he did not trigger the alarm. So I looked at the code and found that'within range'does not include both sides of the boundary. So if I think it's equal to zero, call the police. How should I set it?

**Comment by torkelo** [comment]
within range and outside range are not inclusive

So right now you would have to do within range -0.01 to 0.01 or something.

**Comment by atlasW** [comment]
> within range and outside range are not inclusive
> 
> So right now you would have to do within range -0.01 to 0.01 or something.

ok.thanks

**Comment by patricktokeeffe** [comment]
> So right now you would have to do within range -0.01 to 0.01 or something

This workaround requires users to have domain-specific knowledge when deciding what small range constitutes 'zero'. 

A 'not equal to" can be achieved using two rules (min is below or max is above), but it is not possible to get a true "equal to" condition. One solution might be:

* change `IS WITHIN RANGE` to inclusive
* but keep `IS OUTSIDE RANGE` exclusive

I think that's more semantically appropriate for the range labels used.

**Comment by bneelon85** [comment]
> within range and outside range are not inclusive
> 
> So right now you would have to do within range -0.01 to 0.01 or something.

May I ask if or where "not inclusive" is documented?  I couldn't find it in the docs and it's not super intuitive, at least for me. May I suggest adding it to the docs and maybe a simple tooltip in the UI when you hover on a selection that indicates this?

Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by Karsonito** [comment]
Please add warning for user in UI if the "IS WITHIN RANGE" threshold chosen with equal values
It's a real problem because of human factor
