### ISSUE TITLE
Elasticsearch: Should not be possible to select pipeline aggs in term order by

### ISSUE THREAD

**Issue by Willshield** [grafana/grafana#19206]
**What happened**:

I made a graph panel with ElasticSearch datasource with the following query:
![image](https://user-images.githubusercontent.com/13013769/65158814-5f62ab80-da33-11e9-8b97-e14a15df236f.png)

As I wanted to select in the group by section to order the results based on the bucket script result, there was an option "Bucket Script select field"

When I checked the query inspector, I saw the following:
![image](https://user-images.githubusercontent.com/13013769/65159251-12cba000-da34-11e9-83a5-6f5e19bf9e67.png)

At the end of the query there's a  `"9":{"bucket_script":{"field":"select field"}}` part, which results in the following error: "Elasticsearch error: Unknown key for a VALUE_STRING in [9]: [field]."

**What you expected to happen**:

When I select the order by field, the appropriate Elasticsearch query should be generated without Elasticsearch error.

**How to reproduce it**:

Create an ES query with bucket script aggregation, and try to order the results by that values.

**Environment**:
- Grafana version:  v6.3.5 
- Data source type & version: Elasticsearch 5.5
- OS Grafana is installed on: Linux
- User OS & Browser: Windows, Chrome

**Comment by Ultraseamus** [comment]
The bug is that Grafana is allowing you to select the Bucket Script as a target for ordering.

The way pipeline aggregations work in ES (run during the reduce phase), it is not possible to use the result for ordering (selection of top or bottom X). Though it would be possible to do a post-aggregation sort with different pipeline agg support.

**Comment by varpenny** [comment]
Is there any solution now?

**Comment by simianhacker** [comment]
@varpenny I've opened a PR to remove pipeline aggregations for the sorting list: #28620
