### ISSUE TITLE
Use negative values for Time range in panels

### ISSUE THREAD

**Issue by pwSteve** [grafana/grafana#19202]
For me and my company who use Grafana, negative values are also needed in the Time range tab, which can be used in all panels with a Metric.

We need this to e.g. display a graph panel with -3 hours because we want to predict data with machine learning and also display this data without having to change the time range in the dashboard.

**Comment by adeverteuil** [comment]
I think this is a duplicate of #10395.

**Comment by LeCodeCo** [comment]
Use 0m+180m to go 3 hours forward.

**Comment by torkelo** [comment]
Closing as duplicate , try: now+1h
