### ISSUE TITLE
Add support for Google Ads

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#19210]
**What would you like to be added**:
It would be nice to see support for Google Ads in Grafana. After the site gets confirmed in Google Ads, there is a need to add "ads.txt" file into your page so it can be accessed like this: domain.com/ads.txt

**Why is this needed**:
It may help some people monetize their websites.

**Comment by marefr** [comment]
Sorry, but I'm not sure I understand what you request here. Are you referring to showing ads in Grafana or what is the purpose of Grafana exposing an ads.txt?

**Comment by szerwi** [comment]
Yes, it is needed to show ads on Grafana page.

**Comment by szerwi** [comment]
It is very similar with robots.txt file. ads.txt and robots.txt files are neccessary for Google bots.

**Comment by ryantxu** [comment]
can't you just put your ads.txt file in the root folder?  If you want to show adds... can you make a panel for your instance?

**Comment by marefr** [comment]
This doesn't sound useful for a lot of users. Should this issue show a lot of interest by upvotes we'll consider reopen it.

**Comment by szerwi** [comment]
@ryantxu Where is Grafana's root folder? I think Grafana won't find new file without changing the code and rebuilding it.

**Comment by szerwi** [comment]
@marefr it seems to be easy to add it, the same way as robots.txt file. I would really appreciate if you add it in one of the future releases :)
