### ISSUE TITLE
Support for Auth Proxy (pass username or email via HTTP Header)

### ISSUE THREAD

**Issue by lexelby** [grafana/grafana#1921]
We'd like to put nginx doing RADIUS auth in front of Grafana 2.0.  We can use the anonymous user settings to work with this, but then users don't get individual preferences and whatnot.  It'd be useful if there were a simple auth module that just took the username from a request header.  It'd be up to the admin, of course, to ensure that the specified header was trusted.

**Comment by torkelo** [comment]
yes, think this is good idea, and should be simple as well.

**Comment by torkelo** [comment]
Is there a standard header name for this? Maybe config for it

like 

[auth.proxy]
enable = true
username_header = X-WEBAUTH-USER

**Comment by lexelby** [comment]
I don't think there's a standard header for this, but yeah, that's exactly what "X-" is for.  Your example looks ideal.

Completely unrelated to this, THANK YOU for making your .deb package not auto-start the service on installation :)  I hate when packages do that.

**Comment by lexelby** [comment]
\o/

**Comment by cbeer** [comment]
:+1:

**Comment by torkelo** [comment]
#################################### Auth Proxy ##########################
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true


header_property can either be `username` or email

**Comment by lexelby** [comment]
Wow, that was incredibly fast.  We haven't even had a chance to test out 2.0 :)  Once we get this running, I'll let you know if we have any trouble with this feature.

**Comment by bluefeet** [comment]
Can't wait for 2.1 and this feature to come with it!  :+1:

**Comment by JeanFred** [comment]
Documenting that here in case anybody would be looking for it: this works perfectly and out-of-the-box with bitly’s [oauth2_proxy](https://github.com/bitly/oauth2_proxy).

```
#################################### Auth Proxy ##########################
[auth.proxy]
enabled = true
header_name = X-Forwarded-Email
header_property = email
auto_sign_up = true
```

Thanks *a lot* for this feature. I had no clue it existed (I started digging it after seeing it in Icingaweb2)

**Comment by TamalSaha** [comment]
@JeanFred , can you point me where this is supported in IcingaWeb2? I can't find anything with Google search. Sorry for asking off topic question.
