### ISSUE TITLE
Support using __name__ in Explore with Prometheus datasource

### ISSUE THREAD

**Issue by yeya24** [grafana/grafana#19214]
**What happened**:
In Grafana explore page, try to query some metrics using `{__name__=~".+"}`
This works in Prometheus UI.
![image](https://user-images.githubusercontent.com/25150124/65183109-c29f0e80-da30-11e9-850b-59e20244bebf.png)

However, cannot get the results in Grafana
![image](https://user-images.githubusercontent.com/25150124/65183133-d34f8480-da30-11e9-9c93-10a5de3256e5.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: docker image latest
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@davkal any ideas why this is?

**Comment by torkelo** [comment]
looks like a Prometheus return error

**Comment by aocenas** [comment]
This is probably issue with cortex which does not return all the metrics here and is not something we can do to fix it apart from giving a nicer error message.

**Comment by ivanahuckova** [comment]
More info: https://github.com/grafana/grafana/issues/24997
