### ISSUE TITLE
Templating: Multi value variable and setting from URL

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1922]
Extending the #1144 multi variable value variable to work with setting multiple values from url.

**Comment by torkelo** [comment]
This now works really well, just specify the template variable twice in the url:

![image](https://cloud.githubusercontent.com/assets/10999/7450501/ef1a7ee0-f245-11e4-9ee1-925ad723d1a5.png)

**Comment by YitongFeng** [comment]
How to do it? How does a graph get the parameters from url？
