### ISSUE TITLE
Service now as a alert notification channel to raise an incident once the alert is generated.

### ISSUE THREAD

**Issue by suraganijanakiram** [grafana/grafana#19227]
Hi Team,

first thanks a lot for accepting my previous Enhancement request.

ticketing tool like (servicenow)  as a alert notification channel 
This should raise an incident once the alert is generated.
also it has to close the incident once the resolve message is sent.

I am not sure if email notification channel works for service now since we are sending the email alert as image.

**Comment by torkelo** [comment]
We have no direct integration with service now, and unless you can hook this up using email notification OK message I am not sure,
