### ISSUE TITLE
Explore: No data text in graph when loading data for new time interval

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#19223]
**What happened**:
In graph, when choosing a new time interval after the previous interval had no data points, new graph layout with updated time range is rendered, but *No data* text stays until new data points are rendered and visualised. This can be confusing, as for slow queries, it might seem like there are no data points for newly selected time interval. 
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/30407135/65235127-4c54e780-dad6-11e9-9ede-245d0dcfb4ed.gif)

**What you expected to happen**:
See empty graph layout with new time interval rendered, but no *No data* text.
OR 
See old graph (with previous time interval and previous data) until we receive new data for selected time interval that could be rendered. 

**How to reproduce it (as minimally and precisely as possible)**:
1. In Explore, select Loki as a datasource
2. Select time interval with no data
3. After that, select time interval with data
4. See the issue

**Anything else we need to know?**:
1. More high level solution would be to not render new graph until we receive new data.  
2. Fastest solution is to pass *loading* prop to Graph.tsx 
 ```const noDataTextToBeDisplayed = series.length === 0 && loading;
    return (
      <div className="graph-panel">
        <div className="graph-panel__chart" ref={e => (this.element = e)} style={{ height }} />
        {noDataTextToBeDisplayed && <div className="datapoints-warning">No data</div>}
      </div>
    );```

**Comment by ivanahuckova** [comment]
@torkelo @hugohaggmark What do you think?

**Comment by torkelo** [comment]
personally I think this is fine, there is no data while loading :)  this is how it's always been for graphs int he dashboard as well.

**Comment by ivanahuckova** [comment]
@davkal As Torkel has mentioned, this is the same pattern as in graphs in dashboards, which I wasn't aware of, at the time of creating this issue. Therefore I suggest to close this issue. 🙂

**Comment by ivanahuckova** [comment]
As this behaviour is consistent with the dashboards, I am closing the issue.
