### ISSUE TITLE
Align Variable with Tag

### ISSUE THREAD

**Issue by kirano99** [grafana/grafana#19232]
Align the variable value with the tag data...

They align when multi-selection is enabled, but for single selection they are out of line. Would be much neater if they were aligned always :-) 

![image](https://user-images.githubusercontent.com/34285686/65251097-a3ff4d00-daee-11e9-808c-c0cd42be3ca1.png)

**Comment by torkelo** [comment]
tags in template variables are an experimental feature that is likely going away. And 99% of their use cases are with multi-select enabled. 

But a PR would be welcome :)
