### ISSUE TITLE
Not all stacked bars are painted

### ISSUE THREAD

**Issue by bsmarcosj** [grafana/grafana#19233]
**What happened**:
There are minutes in where not all stacked bars are painted when the select has _fill(null)_ instead of _fill(0)_.

On the one hand, there is the bellow select (within _fill(0)_) that paints the "communication_error" when its occur:
![image](https://user-images.githubusercontent.com/6134894/65250758-5f77af80-daf6-11e9-9f46-252bb2761023.png)

On the other hand, there is the bellow select (within _fill(null)_) that sometimes doesn't paint the "communication_error" bar:
![image](https://user-images.githubusercontent.com/6134894/65250795-70282580-daf6-11e9-9699-fcff8a12ee4d.png)

I understand that the same graph must be painted with both select. Isn't it?

These are the graph visualization settings:
![image](https://user-images.githubusercontent.com/6134894/65251171-24c24700-daf7-11e9-9c3e-3a4108c26881.png)

**What you expected to happen**:
The same graph as a result of both selects.

**Environment**:
- Grafana version: v6.3.5
- Data source type & version: InfluxDB v1.7.7
- User OS & Browser: Ubuntu 18.04.3 LTS - Chrome

**Comment by torkelo** [comment]
stacking requires there to be values to stack, so fill(0) is required. or fill(null) with graph null value option "null as zero"

**Comment by bsmarcosj** [comment]
Hi @torkelo ,

I think I haven't explained enough... The problem is that there are values that are not painted when the _fill(null)_ is set.

If you check out the attached images you will be able to see that in the first image all the minutes have a BLUE bar painted, instead of in the second image, there are some minutes in where the BLUE bar is not painted in spite of there are values.

**Comment by torkelo** [comment]
Probably because some other series is null below it , set null as zero in the graph options
