### ISSUE TITLE
Graphite: Don't issue empty "select metric" queries 

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#19231]
We have a customer that has an alert that was poorly saved or something.
this causes grafana to send incorrect requests like so:
```
format=json&from=-5min&maxDataPoints=500&target=&until=now
```
this results in errors because the target is empty.
![Screen Shot 2019-09-19 at 15 56 18](https://user-images.githubusercontent.com/20774/65246586-2d168400-daef-11e9-9876-450dad571e44.png)

when this happens, grafana also logs:
```
t=2019-09-19T12:51:02+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=3009462 name="xxxx" error="tsdb.HandleRequest() error Request failed status: 422 Unprocessable Entity" changing state to=alerting
```

really Grafana should not issue bad requests if it has no query.
rather it should log errors that the alert is broken, or something.

**Comment by Dieterbe** [comment]
i realize there can be many ways that grafana may have alerts defined with borken queries (e.g. auto-provisioned dashboards or alerting rules with typo's in them)

**Comment by bergquist** [comment]
Kind of closed by https://github.com/grafana/grafana/pull/22699/files 

In theory, we could validate the query in Grafana but I think that's out of scope for Grafanas alerting.

**Comment by Dieterbe** [comment]
Why "kind of"? If I understand that Pr correctly, Grafana will no longer issue alerting queries with an empty target string.

**Comment by papagian** [comment]
> Why "kind of"? If I understand that Pr correctly, Grafana will no longer issue alerting queries with an empty target string.

I think "kind of" goes to the queries with typos (grafana right now has no way to tell if a query is a valid graphite one and preventing it from being sent)
