### ISSUE TITLE
AzureMonitor: Implement Top N/Bottom N  query for cross-resource method

### ISSUE THREAD

**Issue by briangann** [grafana/grafana#19245]
**What would you like to be added**:

AzureMonitor with cross-resource queries needs to implement an optional Top/Bottom N filter.

**Why is this needed**:

* The ability to retrieve top CPU utilization across all VM's (overutilized)
* In addition, the "bottom" query would show VM's with the least cpu utilization (underutilized)

The limit should be configurable (Limit 10, 20, etc), and a sort order Ascending/Descending.

**Comment by torkelo** [comment]
This should be done in the azure api not in Grafana!
