### ISSUE TITLE
Typo in documentation for configuration file

### ISSUE THREAD

**Issue by milliams** [grafana/grafana#1924]
The documentation page at http://docs.grafana.org/installation/configuration/#user_1 says that there is an INI config section called `user`. However, if I put:

    [user]
    allow_sign_up = false
    allow_org_create = false

in `/etc/grafana/grafana.ini` then I get the error on startup of:

    [E] Unknown config section user defined in /etc/grafana/grafana.ini

It seems that the section is supposed to be called `users` and if I change `grafana.ini` to this then it starts correctly.

To be clear it is the missing "s" from "users" that is wrong.

**Comment by torkelo** [comment]
Fixed
