### ISSUE TITLE
themes.md is missing content

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19243]
Is [themes.md](https://github.com/grafana/grafana/blob/master/style_guides/themes.md) missing content?

The first heading is "Core Changes" and it is a level 2 heading. It reads like it is starting partway through a longer document. Did the first chunk get cut off at some point?

If it didn't, then the title or the file name needs to change and the heading structure needs to get fixed.

**Comment by dprokop** [comment]
@oddlittlebird thanks for noticing this. Fix and update coming in https://github.com/grafana/grafana/pull/19248
