### ISSUE TITLE
Support for avatar URL as a synchronized user attibute in Auth Proxy Authentication "headers" configuration directive

### ISSUE THREAD

**Issue by h1nk** [grafana/grafana#19242]
**What would you like to be added**: [Support](https://github.com/grafana/grafana/blob/0cbbb4322204e9d5990813d9dbcd4e1770c2c507/pkg/middleware/auth_proxy/auth_proxy.go#L36-L37) for an `AvatarURL` field in the `[auth.proxy]/headers` configuration directive:
```ini
headers = AvatarURL:X-WEBAUTH-AVATAR-URL
```
**Why is this needed**: To allow for user's who strictly rely on [Auth Proxy Authentication](https://grafana.com/docs/auth/auth-proxy/#auth-proxy-authentication) to better integrate Grafana with their existing user authentication scheme.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by diamondburned** [comment]
Hi, this feature is still relevant to me. Since feature requests are being moved back to issues, I think this issue should be reopened.
