### ISSUE TITLE
Docs feedback: reference/timerange.md

### ISSUE THREAD

**Issue by abhijithbrao** [grafana/grafana#19241]
Singlestat for latest 6.3.3 grafana version does not have time range option. However, this document has a reference for singlestat time range information

**Comment by oddlittlebird** [comment]
All the panel documentation needs to be reviewed and updated. Still relevant.

**Comment by oddlittlebird** [comment]
Singlestat panel no longer exists. Stat documentation is fully up-to-date with 7.0.
