### ISSUE TITLE
Variable after extract part in query

### ISSUE THREAD

**Issue by duylong** [grafana/grafana#19252]
Hi,

I would like to put a part of a variable in the query for Elasticsearch. Is it possible to add the possibility of doing it?

Example: 
```
Fields:
    country_name_France, country_name_Spain...
After fields extract: 
    France, Spain
Apply in query:
    tag:"country_name_$Country"
```

**Comment by torkelo** [comment]
yes, use ${varname:raw} syntax

**Comment by duylong** [comment]
Great but this syntax returns me a hash when I use multi-value with Elasticsearch.

For exemple, tag:${varname:raw} returns tag:{country_name_Albania,country_name_China} and no tag:("country_name_Albania" OR "country_name_China")

**Comment by torkelo** [comment]
yea, obviously that does work with multi syntax, multi syntax works only for full matches like:

tag:$myvar

which interpolates to `tag:("value1" OR "value2" ... etc)`

**Comment by duylong** [comment]
So, the syntax ${varname: raw} for All and Multi-value does not work with Elasticsearch?

Is it possible to implement it?
