### ISSUE TITLE
DataLinks: UX improvements

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#19257]
DataLinks have few UX issues that would be good to address soon:

#### 1. Suggestions menu has wrong position when input is too short?:
See images below, one character makes a difference!

<img src="https://user-images.githubusercontent.com/2376619/65320496-44627980-dba2-11e9-8284-f3ca715981d8.png" width="400"/>

vs

<img src="https://user-images.githubusercontent.com/2376619/65320519-52b09580-dba2-11e9-85a2-615da855d435.png" width="400"/>

#### 2. Suggestions menu is not repositioned when opened and user types:

![DataLinks2](https://user-images.githubusercontent.com/2376619/65320762-dff3ea00-dba2-11e9-9e8c-d33f6fd4f3dc.gif)

**Comment by torkelo** [comment]
ah, nice. maybe nr 1 was what I discovered as well but could then not replicate.
