### ISSUE TITLE
Github login

### ISSUE THREAD

**Issue by DaveBlooman** [grafana/grafana#1925]
I have configured Github in the config.ini, setup my application, but when I click the the login button, it just redirects back to the login page.  Here is a shot of my application and the logs from when I try to login.

![screenshot-2015-05-01-11 38 43](https://cloud.githubusercontent.com/assets/1492067/7429956/1d489882-f003-11e4-9970-058827959350.jpg)

2015/05/01 12:09:09 [I] Completed /login/github 302 Found in 3.415021ms
2015/05/01 12:09:10 [T] login.OAuthLogin(Got token)
2015/05/01 12:09:11 [T] login.OAuthLogin(social login): &{10000 DaveBlooman   }
2015/05/01 12:09:11 [I] Completed /login/github 302 Found in 880.370405ms

**Comment by torkelo** [comment]
I think this is due to allow_sign_up is false by default

```ini
   [auth.github]
    enabled = true
    client_id = YOUR_GITHUB_APP_CLIENT_ID
    client_secret = YOUR_GITHUB_APP_CLIENT_SECRET
    scopes = user:email
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    allow_sign_up = false
```

See the last option allow_sign_up , I think this option was not pressent (in uncommented form in the sample config file). 

Try adding allow_sign_up=true to the    [auth.github]  section

**Comment by DaveBlooman** [comment]
Thanks, this fixed the issue
