### ISSUE TITLE
Explore: Live Streaming doesn't unsubscribe the WebSocket

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#19255]
1. Make sure you've started devenv Loki 
2. Open the network tab in chromes dev tools
3. Goto Explore
4. Choose the `gdev-loki` datasource
5. Enter an expression like `{job="varlogs"}`
6. Start Live tailing
7. Wait and see that messages appear, otherwise change query so that you get a steady stream of messages
8. Stop Live tailing
9. Expected that no new messages are received in network tab but we're still receiving messages
 
![image](https://user-images.githubusercontent.com/562238/65315875-29d7d280-db99-11e9-9ad1-bb6610dd7819.png)

The same issue happens if you in step 8 above do:
- change datasource
- change query

**Comment by aocenas** [comment]
Interesting was fixing it a while ago and even tried to do a test for it https://github.com/grafana/grafana/blob/991f77cee1da71af12d3e853a152537420eb90d7/public/app/plugins/datasource/loki/live_streams.test.ts#L95

**Comment by aocenas** [comment]
Taking a look right now as it isn't just missed unsubscribe somewhere. Seems like the pipeline keeps subscription somewhere even when unsubscribe is called by explore.
