### ISSUE TITLE
Able to put alerts into folders

### ISSUE THREAD

**Issue by Aaron-Nad** [grafana/grafana#19259]
Would it be possible to get alerts added into a folder type structure. Currently in the company i work for there are well over 30 teams, that all run their own alerts. We have started using Grafana alerting as a day time alert tooling. However on the alert page currently, it just lists all the alerts in one big long line - over 400 configured. We can filter these down to alerting/pending etc. However we would like to see these in relation as to which team owns these.

Adding this makes it easier for a team to see and manage the alerts they own and care for. I think just adding a simple flag in the setup process for the alert field where you can define the team (either from a dropdown, or by entering in text yourself). This creates a folder on the main overview filed and puts the alerts under that folder structure so you can view all the alerts in one place for one specific team.

**Comment by orojina** [comment]
@Aaron-Nad  In case you find this useful, and as a temporary solution,  I created a script to list  alerts with their statuses and the dashboard they belong to. Listing several alerts can be done with:

`grafana-cli alerts | grep -i <your_filter_cliteria>` 

Adding the watch command into the mix will give you and your team an auto-refreshed view of your alerts

https://github.com/orojina/grafana-cli

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
