### ISSUE TITLE
Data source plugin does not export any Query Editor component on Mixed Queries

### ISSUE THREAD

**Issue by Napfton** [grafana/grafana#19276]
**What happened**:
I get "Data source plugin does not export any Query Editor component" when I want to setup a mixed data source querie to 2 influx DBs (one by one they work)

**What you expected to happen**:
A query editor is shown to define a mixed data source query.

**How to reproduce it (as minimally and precisely as possible)**:
Create 2 influx db data sources, add dashboard, add panel, select "mixed" for "Queries to" dropdown, then add Query and also "mixed"

**Anything else:**
When I try the above the panel (the preview of the graph) does not render data any more but shows a red error on the top left corner with this message: "[$q:norslvr] Expected resolverFn, got '[]' http://errors.angularjs.org/1.6.6/$q/norslvr?p0=%5B%5D"

**Environment**:
- Grafana version: Version 6.1.6 (commit: cf9cb45)
- Data source type & version: InfluxDB 1.7.6
- OS Grafana is installed on: Raspbian GNU/Linux 9 (stretch)
- User OS & Browser: Debian 10, tried with latest Chrome and Firefox
- Grafana plugins: none
- Others: none

**Comment by torkelo** [comment]
Please try latest version of Grafana

**Comment by Napfton** [comment]
Wow, what a constructive feedback... Well I just updated to 6.3.6 and (what a surprise...) the exact same error occurrs. 

Anybody else?
