### ISSUE TITLE
PostgreSQL as a Backend Database server

### ISSUE THREAD

**Issue by Dual-Boot** [grafana/grafana#1927]
Hello,

 I just have installed Grafana 2.0.2 from debian repository. There is no problem using the default database backend.
So I tried to set up a PostgreSQL server to replace the default one. I could create new user with admin properties but the user is unable to create a new domain or dashboard. He is only a viewer.
With FireBug I haver a response from the API which is a Permission denied.

My configuration : 
- Linux Ubuntu 14.04 up to date
- Grafana 2.0.2
- a remote PostgreSQL server running on Ubuntu 14.04 too

  Any idea ?
 Regards,

**Comment by torkelo** [comment]
Login as the first admin user (that grafana) created and go to organization users and change your role. 

Another good option is to view the screencast episode on adding users and organisations (check docs.grafana.org  under guides ) sorry for short reply. on mobile now

**Comment by Dual-Boot** [comment]
Seems to be a mistake from me.
I drop the PostgreSQL database and recreate it.
Now It works. As far I can remember, the first time, I have created a new user admin and then delete the default admin account.

 Thank you.
