### ISSUE TITLE
Remove incorrect bolding

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19271]
Keyboard keys should not be bold. This includes Ctrl, Shift, and combinations such as Ctrl+S.

Keyboard keys should be written in sentence case.

Review all usage within documentation and make consistent.

Reference: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts

**Comment by linusg** [comment]
I'll take this one.

There are inconsistencies in the way multiple keystrokes are expressed as well:

- ´+´ or ´-´ ? i.e. Ctrl+S or Ctrl-S
- with or without spaces between? i.e. Ctrl + S or Ctrl+S

Please let me know what should be preferred.

**Comment by oddlittlebird** [comment]
Follow the Microsoft Style guidelines:
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts

Plus sign, no spaces. Ctrl+S
