### ISSUE TITLE
config vs. configuration

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19270]
Currently the terms "config" and "configuration" are used interchangeably. This is confusing for readers.

Decide on what the rules for one vs. the other should be, then add them to the Documentation style guide and create an issue to apply them.

My suggestion:
Only use "config" when you are specifically referring to a config file, and then use the actual name and file extension. In all other cases, use "configuration."

**Comment by oddlittlebird** [comment]
Issue for tracking.

**Comment by ndeevy** [comment]
Hello @oddlittlebird  Could I possibly try to address this issue?

**Comment by oddlittlebird** [comment]
Yes, please do. If possible, please update the [Documentation style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md) as well.

**Comment by ndeevy** [comment]
Ok, I'll do my best. Thanks @oddlittlebird !
