### ISSUE TITLE
Docs: Move style rules from docs contribution guide to actual style guide

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#19281]
**What would you like to be added**:

Move the style rules from the [documentation guide](https://github.com/grafana/grafana/blob/master/docs/sources/contribute/documentation.md) to the recently created [style guide](https://github.com/grafana/grafana/blob/master/style_guides/documentation-style-guide.md).

**Comment by bobertlo** [comment]
Oh, I didn't see this and did this already in #19487

**Comment by bobertlo** [comment]
I will make a separate PR with changes to actually remove them from this page and replace the section with a link to the new style guide if that is okay.

**Comment by marcusolsson** [comment]
@bobertlo Sounds like a great idea!
