### ISSUE TITLE
Add Contribution Quickstart for devs

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19284]
Review Ivana Huckova's article and see if the process she outlines can and should be adapted to a quick start topic or tutorial for new code contributors.

https://medium.com/@ivanahuckova/how-to-contribute-to-grafana-as-junior-dev-c01fe3064502

**Comment by jeremy010203** [comment]
Hey! I tried to configure my dev env yesterday and I had some issues to understand the devenv instructions as a new comer. So glad I found this issue/article thanks :) I will try to follow the instructions in the article and give you a feedback!

**Comment by jeremy010203** [comment]
I have tried to `make run` the project but have the following error on ubuntu 18.04

```
➜  grafana git:(master) ✗ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
➜  grafana git:(master) ✗ go version
go version go1.13 linux/amd64
➜  grafana git:(master) ✗ make run
go: github.com/golangci/golangci-lint@v1.17.1 requires
	github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: invalid pseudo-version: does not match version-control timestamp (2019-05-26T07:48:19Z)
Makefile:75: recipe for target 'scripts/go/bin/bra' failed
make: *** [scripts/go/bin/bra] Error 1
```

**Comment by jeremy010203** [comment]
Tried to reinstall go with another version and it seems to work with stable version of go 1.12.9

**Comment by oddlittlebird** [comment]
@ivanahuckova  and @marcusolsson , are you following along? Is this a bug that needs fixing?

**Comment by marefr** [comment]
Grafana does not support Go 1.13 yet. There's an open issue #18878

**Comment by jeremy010203** [comment]
Ok so maybe it could be useful to add that information to the article and/or readme until the issue is fixed? (the article mention Go (Latest Stable) which can be 1.12.9 or 1.13 if you go to [https://golang.org/dl/](url) )

**Comment by marefr** [comment]
@jeremy010203 we want to keep go latest stable in docs since we're aiming to that Grafana always can be built using that and to not have to remember to update docs each time Grafana updates go version for CI/release builds. Normally there's no issue, but with go 1.13 we need to fix a dependency and after that is done you can build grafana locally using go latest stable 1.13.

**Comment by ivanahuckova** [comment]
@jeremy010203 I have updated this information in the article and I will keep it there until this issue is gone. Thanks so much for your input. Much appreciated! 🙌

**Comment by oddlittlebird** [comment]
Updating the article is good, but since it is not connected to anything
officially Grafana, I am concerned people will not know to refer to it.

Is there a place in the Grafana Community forums for information like this?

**Comment by ivanahuckova** [comment]
@marefr I agree with @oddlittlebird. I think it would be good if we would update the documentation until Go 1.13 fix is done. And in the meantime, add to the https://github.com/grafana/grafana/issues/18878 another checkbox to not forget to update documentation when the issue is solved. 🙂

**Comment by oddlittlebird** [comment]
Great idea, Ivana.

**Comment by oddlittlebird** [comment]
@marcusolsson , has your work fixed this?

**Comment by oddlittlebird** [comment]
@marcusolsson and @ivanahuckova , does this issue still need work?

**Comment by ivanahuckova** [comment]
The issue with the latest stable Go has been fixed. Therefore, I think this issue can be closed. 🙂
