### ISSUE TITLE
Docs: HTTP is an acronym, and should be uppercased

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#19286]
**What would you like to be added**:

When used in text, HTTP should always be uppercased.

`cd docs/sources && grep -R "http " *` currently finds 13 occurrences
 
**Why is this needed**:

To comply with the [style guide](https://github.com/grafana/grafana/blob/master/style_guides/documentation-style-guide.md).

**Comment by jeremy010203** [comment]
Hi! I would like to work on this one please :)

**Comment by marcusolsson** [comment]
Great! Let us know if you need any help on this!

For more information about contributing docs: [Guide to contributing docs](https://github.com/grafana/grafana/blob/master/docs/sources/contribute/documentation.md)

**Comment by jeremy010203** [comment]
I left one occurence of http in lowercase because it is in a commit message in the "what's new in v4.6" page!
Hope it is ok it is my first contribution :smile:
