### ISSUE TITLE
API: Get dashboard returns main JSON element named 'model' instead of 'dashboard'

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1928]
I observed using the get dashboard API that the main JSON element is named 'model' instead of 'dashboard' [as stated in the documentation and expected by the post API].

**Comment by torkelo** [comment]
thanks for reporting this, docs fixed

**Comment by maddenca** [comment]
It seems strange to me that the dashboard json format is different for a get (model) and and a post (dashboard).  If you want to export/import between different Grafana instances small differences like this require some fix-ups.  Can I ask why this is a doc bug and not a code bug?

**Comment by torkelo** [comment]
It is not a bug, when you read from the api you get the model as well as some meta data (is this dashboard starred by the requesting user, and other meta data). 

I can understand that it can complicate some things, but not much as the "model" property is exactly the same model used to save a dashboard (in the post), exactly the same as the object int he "export to json".

**Comment by torkelo** [comment]
So there is no complicated fixup really, just use the model property in the GET request, and pipe that into the POST.

**Comment by maddenca** [comment]
I'm still confused here.  

API:
When you use GET the dashboard data is within the model property.  When you POST the dashboard data must be within a dashboard property.  So you have to rewrite this property name.

GUI:
When you export from the GUI there is no model or dashboard property, and no meta property or data; the structure is just at the top level.  When you import from the GUI it requires the same.

So these formats aren't interchangeable.  If you just stay within API you have to rewrite.  If you cross between GUI and API you have to rewrite.  If you stay within GUI only you are ok.  I can see it being more difficult to share dashboards (on internet forums and blogs for example) because you have to know what format it's in to make use of it.

**Comment by torkelo** [comment]
@maddenca yea, I agree the the GET request should also name the the dashboard property dashboard instead of `model`, that is a mistake. To fix it will introduce a breaking api change. Might not be that a big a deal this early on. 

Regarding difference between GET and POST, this is very common, Read models are not the same as Write models. Read models correspond to what should be visible (view model basically), while the write model should only be what is actually persisted/updated.

**Comment by torkelo** [comment]
@maddenca renamed `model` -> `dashboard` for get request
