### ISSUE TITLE
Reduce Docker image size by removing JavaScript source map

### ISSUE THREAD

**Issue by Fabian-Schmidt** [grafana/grafana#19299]
**What would you like to be added**:
The JavaScript source map files `*.map` are only for debug purposes and can be removed from the production Docker image.

**Why is this needed**:
Reduce Docker image size by ~20MB.
The following files can be removed:
```
/usr/share/grafana/public/build$ ls -lah *.map
-rw-rw-r-- 1 root root 5.0M Sep  2 09:58 app.75ccb77dbb4b5e3c9285.js.map
-rw-rw-r-- 1 root root 4.5K Sep  2 09:58 dark.75ccb77dbb4b5e3c9285.js.map
-rw-rw-r-- 1 root root 208K Sep  2 09:58 explore.75ccb77dbb4b5e3c9285.js.map
-rw-rw-r-- 1 root root 4.5K Sep  2 09:58 light.75ccb77dbb4b5e3c9285.js.map
-rw-rw-r-- 1 root root  14M Sep  2 09:58 vendor.75ccb77dbb4b5e3c9285.js.map
```

**Comment by torkelo** [comment]
The source maps are very important for troubleshooting production errors & bug reports. If you need a smaller docker image you will have to make a custom docker image with them removed

**Comment by hunshcn** [comment]
I created a tool to remove sourcemap. https://github.com/hunshcn/grafana-sourcemap-less
