### ISSUE TITLE
Remove ampersands from docs

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19294]
Anywhere an ampersand is used as an abbreviation for "and", remove it.

However, *do not* remove the ampersand if it appears in UI text. Always match the UI.

**Comment by brew-install-buzzwords** [comment]
Can you give an example of where an ampersand should not be removed?

**Comment by oddlittlebird** [comment]
If the ampersand is in a field name in the Grafana UI, then do not change it. It looks like there are few to none of those, but I like to cover my bases. 

Example: If there was a button called **Save & Close**, and the instruction said "Click **Save & Close**," then you would not change it.

If someone just wrote, "When finished, save & close," then you would change that ampersand to "and".

**Comment by brew-install-buzzwords** [comment]
Thanks for the clarification. I'll work on this assuming it's still available.

**Comment by oddlittlebird** [comment]
No one else has claimed it, so have at it. Thanks!

**Comment by oddlittlebird** [comment]
Feel free to post in #docs in Grafana Slack if you have questions or want
to discuss further.
