### ISSUE TITLE
Changing root_url breaks Grafana 2.0.2

### ISSUE THREAD

**Issue by LionelCons** [grafana/grafana#1930]
I have tried to change root_url to relocate Grafana. I use:

    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana2/

This seems to break Grafana as I get 404 errors:

    2015/05/04 10:41:30 [I] Completed /grafana2/img/fav32.png 404 Not Found in 617.537µs

Indeed, /grafana2/img/fav32.png returns 404 while /img/fav32.png does return the icon.

**Comment by torkelo** [comment]
Adding a subpath to root_url works great, but you need to use it in conjuction with a reverse proxy that adds the path. 

Like nginx
```
location /grafana2/ {
    proxy_pass                 http://127.0.0.1:3000;
}
```

**Comment by LionelCons** [comment]
Indeed, it works with a web proxy.

However, the documentation does not says that a proxy must be used when changing root_url. I would suggest making it clear in the documentation.

**Comment by torkelo** [comment]
There is a big "notice" under this config that mentions this specifically:
![image](https://cloud.githubusercontent.com/assets/10999/7452744/e8a8a192-f261-11e4-914c-c131884f849a.png)

**Comment by LionelCons** [comment]
Indeed but "This setting is also important if you have a reverse proxy infront of Grafana" is not the same as "you must use a proxy if you change the subpath".

**Comment by torkelo** [comment]
well it is implied as otherwise it would you would get a doubled subpath )

**Comment by torkelo** [comment]
And it does not say that a subpath is allowed/suported in any other scenario

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
