### ISSUE TITLE
Templating variables only from current timespan

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#1931]
When using query template, all values are fetched. It would be nice to filter only ones that fall into current time filter.

Use-case: running tasks with unique ID and using this ID as an optional template variable. After deploying 100 tasks 100 times you would have 10000 items in the drop-down, even though in the last 15 minutes (timpicker value) only 100 recent tasks are present.

In my test case only 3 tasks are currently running, but 9 are available from the dropdown.

![image](https://cloud.githubusercontent.com/assets/89186/7451932/721453f2-f25f-11e4-9d53-0fcfee58c905.png)

**Comment by torkelo** [comment]
This feature is not suppoted in Graphite 0.9.12 nor in the upcoming Graphite 0.9.13 (out in release candidate). It is supported in graphite-web master and in graphite-api. 

But I am afraid I will wait to implement this until there is better support in Graphite (in a released version). 

In the meantime you can write scripts that move the old metric files.

**Comment by bobrik** [comment]
Can't you try to use functionality from master and fall back to all values gracefully? I don't see a reason to close the issue if you are going to implement this in the future anyway.

**Comment by torkelo** [comment]
your right should not have closed it

**Comment by mtanda** [comment]
might be same, https://github.com/grafana/grafana/issues/986

**Comment by smbyrne** [comment]
I have a similar issue getting templates from InfluxDB. I use hostname as a template variable. The hosts are EC2 instances and Docker containers, so they come and go. My graphs repeat a panel for each host, so I get lots of panels for hosts that have been gone for a long time.

It would be nice if under "Query" in "Query Options" there was a "Validation Query" that would be executed for each value from the Query, and the template value would be excluded if the validation query returns zero rows. For example, I could do:

Query: SHOW TAG VALUES FROM "os.systemLoadAverage" WITH KEY = "host"
Validation Query: SELECT * FROM "os.systemLoadAverage" WHERE host = '$HOST' AND time > now() - $interval LIMIT 1

This could be done all in the query if InfluxDB supported using time in the WHERE clause of SHOW TAG VALUES, but it does not: https://github.com/influxdata/influxdb/issues/3040.

**Comment by mtanda** [comment]
For Prometheus, there is a feature request for supporting this use case.
https://github.com/prometheus/prometheus/issues/1542

And, I make a PR for supporting this by another approach.
https://github.com/grafana/grafana/pull/4828

I don't know well about InfluxDB, but Validation Query seems to be not efficient. (if SHOW TAG VALUES return too many values.)
If InfluxDB datasource plugin can support like query_result() of Prometheus, it is easier to satisfy requirements.

**Comment by torkelo** [comment]
this was done a while a go (set refresh to On Time Range Change)

**Comment by robermorales** [comment]
No, this is not done. New values arrive when time range change (if you select the option) but old values never get out. InfluxDB does not support this but could be great for templating, as lot of people say.

**Comment by ionutmilea** [comment]
Hello, anything new on this? Thanks!

**Comment by s196-shubham** [comment]
> this was done a while a go (set refresh to On Time Range Change)

no actually i am facing the same issue as @robermorales  mentioned above.
