### ISSUE TITLE
Data not being updated in Grafana dashboard even though sqlite db has the latest data.

### ISSUE THREAD

**Issue by VinayDanda** [grafana/grafana#19319]
Inspite of data being in the sqlite db, its not being shown in the Grafana dashboard.
Found this info in Grafana logs: "Database table locked, sleeping then retrying"
Please help.

**Comment by torkelo** [comment]
did you reload the page / dashboard? 

What is the API returning? 

Please ask questions on the community site https://community.grafana.com

**Comment by torkelo** [comment]
Sorry for closing, if you have more information I will re-open. 

"Database table locked, sleeping then retrying"

is a generic error that happens from time to time with sqlite
