### ISSUE TITLE
grafana should not use a default admin password

### ISSUE THREAD

**Issue by anarcat** [grafana/grafana#19322]
**What happened**:

Grafana, on first install, picked "admin/admin" as a default password.

**What you expected to happen**:

Grafana should setup a random password instead or at least allow me to pick a random one, without having to write it on disk.

**How to reproduce it (as minimally and precisely as possible)**:

 1. install Grafana through the [Puppet module](https://forge.puppet.com/puppet/grafana), [referenced here](https://grafana.com/docs/administration/provisioning/#configuration-management-tools)

Even if the password is set in the config file pre-emptively, the Puppet module writes the configuration file after the package is installed, which makes the "default" setting ineffective.

One could argue the Puppet module should write the configuration files before the code is installed, but that's besides the point: the Puppet module assumes it needs first to install grafana so that directories like `/etc/grafana` exist before modifying them. And that's just one example: there are numerous cases of people installing grafana before realizing it's too late to change the default admin password.

**Anything else we need to know?**:

Last year, [California passed a law making it illegal for consumer electronics to ship with default passwords like this](https://techcrunch.com/2018/10/05/california-passes-law-that-bans-default-passwords-in-connected-devices/) which could arguably make such practices illegal in the state of California. Of course, Grafana labs themselves seem to be located in New York, which might make this legislation ineffective (not to mention that it is mostly targeting hardware), but I thought it might still be relevant to the discussion.

More broadly, I believe strongly that any software that ships with such a default password is severely broken and is exposing itself to serious security issues.

At least:

 * [ ] documentation should be clearer that the admin password is set on first start and that the config file parameter (`security.admin_password`) is ineffective after first start
 * [ ] the `admin_password` from the documentation should be able to override the admin password used in the configuration, even after first startup
 * [ ] hashed passwords should be used in the configuration file (#18869)

Thank you for your work.

**Comment by torkelo** [comment]
Agree to some extent. 

However the first time you login with default admin password we show change password view. 

We will add option to disable creating default admin, https://github.com/grafana/grafana/issues/19038 

and then make creating the user & password part of the initial login instead. 

Thanks for your feedback!

**Comment by anarcat** [comment]
so i see that admin user creation was (optionally, enabled by default) removed in #19038. this means grafana will still create an admin/admin user by default, which i still think is a security problem.

and anyways, with admin auto-creation disabled, how do we create an admin account?
