### ISSUE TITLE
Single PC not able to view last 5 minutes of data

### ISSUE THREAD

**Issue by Gizzo** [grafana/grafana#19325]
**What happened**:
Unable to see any data graphed when trying to view the last 5 minute time window (now-5m). This only occurs on a single Windows 10 PC. Query was working on PC in question up till about 24 hours ago. The issue occurs on PC in question regardless of browser used. Data still appears in the query inspector. Everything appears to render correctly from any other PC that I've tested on. What's even stranger is that the same issue occurs in two environments. Both test and production.

**What you expected to happen**:
See data graphed when trying to view the last 5 minute time window (now-5m).

**How to reproduce it (as minimally and precisely as possible)**:
On specified PC open any browser and navigate to Grafana site. Select specific dashboard that's configured to display last 5 minutes of data and update every 5 seconds. 

**Anything else we need to know?**:

**Environment**:
Grafana v6.3.5
InfluxDB v1.7.8
Ubuntu 18.04 (DigitalOcean VPS)
Windows 10 - Chrome, Edge, Firefox
No Grafana Plugins in use

**Comment by torkelo** [comment]
Investigate network requests and response (with query inspector)

**Comment by Gizzo** [comment]
The interesting this about this issue is that it was resolved by moving the system off of a specific network. This has happened before and should it happen again I'll take a look at the query inspector.
Thank You
