### ISSUE TITLE
Pull the created date for a user via the API

### ISSUE THREAD

**Issue by dconrique01** [grafana/grafana#19329]
**What would you like to be added**:
I'd like to be able to get the created date for a user in Grafana via the API. Currently the created date field is in the user database table, but it is not exposed via the API

**Why is this needed**:
It would help for auditing purposes to have the user's created date exposed via the API along with the other fields already exposed via the API.

**Comment by cored** [comment]
I would like to give this a try @marefr

**Comment by marefr** [comment]
@cored sure. Let us know if you'll need any pointers in the code. Otherwise open a PR as early as possible and we can help you out/review that way.
