### ISSUE TITLE
app.js warning in Grafana 2.0.2

### ISSUE THREAD

**Issue by LionelCons** [grafana/grafana#1932]
When using Grafana 2.0.2 via Chrome, the JS console gets:

    The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers. app.6e379bdb.js:6

**Comment by torkelo** [comment]
when do you see this? Some specific page, dashoard, after some specific action?

**Comment by LionelCons** [comment]
I get it at least on the top page (url=/).

**Comment by torkelo** [comment]
what version of chrome and what os?

**Comment by torkelo** [comment]
Do not see any warning on http://play.grafana.org/ with chrome on linux.

**Comment by LionelCons** [comment]
I do see the warning on http://play.grafana.org/.

I use Chrome 42.0.2311.90 on Linux.

**Comment by torkelo** [comment]
ok, running 40, will upgrade and test :)

**Comment by torkelo** [comment]
hm.. seems to be an issue with jquery 2.1, will try to upgrade jquery
