### ISSUE TITLE
Grafana upgrade from 6.0.0 to grafana-6.4.0-beta1 broke Datatable Panel plugin

### ISSUE THREAD

**Issue by satishdotpatel** [grafana/grafana#19323]
Life was wondering with 6.0.0 and my Datatable Panel plugin was working great with MySQL db backend until i upgrade 6.4.0-beta1

Now everything working except Datatables Panel Plugin, as soon as i load dashboard i see this error page, If i use built in “Table” Plugin that it works i can see data in table but i want DataTable Pannel so i can do search ect…

If its not supported then i would like to go back to 6.0.0

I have asked same question here with screenshot because Github not allowing to upload pic: https://community.grafana.com/t/grafana-upgrade-from-6-0-0-to-grafana-6-4-0-beta1-broke-datatable-panel-plugin/21297

**Comment by satishdotpatel** [comment]
After more investigation i found "Datatable panel" doesn't support Format as: Table anymore (This is my requirement ) 

I don't want Format as: Time series  (because its throwing error saying data type need integer) 

How do i fix this issue?

**Comment by satishdotpatel** [comment]
I have downgraded grafana back to 6.0.0 and my datatable panel started working with Format as: Table 

I am not going to upgrade now until someone fix it in newer version.

**Comment by marefr** [comment]
I see that you've opened an issue in https://github.com/briangann/grafana-datatable-panel/issues/72 so I'll close this.
