### ISSUE TITLE
From: and To: fields don't retain millisecond information

### ISSUE THREAD

**Issue by abezgam** [grafana/grafana#19326]
**What happened**:
The From and To fields in my dashboard are rounding the time to nearest second (floor) and not retaining the milli second information. I am using Grafana to display information of a time-series where the precision of timestamp is in micro-seconds. When I set the From and To time stamps to:
From: 2019-07-01 17:27:41.027
To: 2019-07-01 17:27:41.582

Grafana just rounds the values as:
From: 2019-07-01 17:27:41
To: 2019-07-01 17:27:41

and doesn't show any data.

**What you expected to happen**:
I expect the From and To fields to retain the millisecond precision in the timestamps.

**How to reproduce it (as minimally and precisely as possible)**:
Add time stamps with millisecond information in the From and To fields and click Apply. 

**Anything else we need to know?**:
It would be awesome if the time stamps can hold micro-second information.

**Environment**:
- Grafana version: grafana:6.2.5
- Data source type & version: postgres:11.4
- OS Grafana is installed on: Catalina (10.15)
- User OS & Browser: macOS and Safari
- Grafana plugins: NA
- Others: NA

**Comment by ryantxu** [comment]
Are you talking about the custom time range picker?
![image](https://user-images.githubusercontent.com/705951/65468522-294d6f00-de19-11e9-9b5c-0d667082f6d2.png)

**Comment by abezgam** [comment]
Yes Ryan. It is for the custom time range picker.
