### ISSUE TITLE
Application Insights: UI is broken, many of the "Azure Monitor" controls remain on the page

### ISSUE THREAD

**Issue by ChadNedzlek** [grafana/grafana#19330]
**What happened**:
Add an Azure Monitor datasource with Application Insights
Attempt to create a panel using the App Insights data
The UI contains fragments of the Monitor UI (the "Metrics Namespace", there are 2 TimeGrain fields)

**What you expected to happen**:
Working UI

**How to reproduce it (as minimally and precisely as possible)**:
Add an Azure Monitor datasource with Application Insights
Attempt to create a panel using the App Insights data

**Anything else we need to know?**:

**Environment**:
- Grafana version: master 4c1bc5988
- Data source type & version: Azure Monitor (Application Insights)
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10/Firefox
- Grafana plugins: None
- Others:

Attached screenshot:
![image](https://user-images.githubusercontent.com/11790765/65469842-b2ff3b80-de1d-11e9-9e16-b33e7fae8bc8.png)

**Comment by ChadNedzlek** [comment]
I tried to fix this, but I can't tell which div's are supposed to show in which cases. The azureMonitor.queryMode checks don't line up, and there is an extra `</div>` somewhere on the page (they are mismatched), but I can't tell which one. :-(

This is blocking my work on https://github.com/grafana/grafana/issues/15153

**Comment by torkelo** [comment]
@sunker can you investigate?

**Comment by ChadNedzlek** [comment]
I believe this was fixed by https://github.com/grafana/grafana/pull/19115. I no longer see the weird double UI.

**Comment by sunker** [comment]
@ChadNedzlek #19115 did not make it to master in the end. 

Is this issue still relevant?

**Comment by ChadNedzlek** [comment]
As I mentioned on Sept 25th, I believe this was fixed by #19115, but I don't have the ability to close issues.
