### ISSUE TITLE
Override relative time for starting at a specific date?

### ISSUE THREAD

**Issue by drsprite** [grafana/grafana#1934]
Is it possible to Override relative time for a graph begin at a certain timestamp? Instead of last `1300d`, I could specify starting time of `1325307600000`?

This way on refreshes, the graph will continue to start at `1325307600000` instead of roll through the 1300d mark. 

Does that make sense?

Thanks

**Comment by torkelo** [comment]
no, the time overrides are only relative to the dashboard time range at this point :(

**Comment by drsprite** [comment]
Ah bummer. Is that something that could be programmed in the future? 

Call this a feature request?
