### ISSUE TITLE
grafana render image has garbled text

### ISSUE THREAD

**Issue by maoyuanh** [grafana/grafana#19344]
We are trying to download images from a dashboard, using the /render/d-solo path, but when it does so, the text in the images are coming out garbled. 
our url is like:
https://XXXX:32000/render/d-solo/rN1_wCdWz/_?from=now-5m&panelId=10&to=now
See the attached image. All of the text is garbled.
What do we need to do to fix this garbled output?
![garbled](https://user-images.githubusercontent.com/39478165/65484253-670dce80-ded1-11e9-80e9-4ddc1f5f2c6f.PNG)

**Comment by flopp999** [comment]
I am using version 6.3.5 and I do not see any garbled text.

I think you need to give more details about your installation/setup

**Comment by maoyuanh** [comment]
We are using grafana v5.2.4

**Comment by marefr** [comment]
@maoyuanh are you using Grafana official docker image or building your own? Make sure that libfontconfig dependency is installed.

**Comment by maoyuanh** [comment]
@marefr  We build image by our own and fontconfig installed
below dependency installed:
fontconfig
ca-certificates
shadow-utils

**Comment by torkelo** [comment]
Closing this for now as it seems like it's an issue with a custom build and not an official grafana image
