### ISSUE TITLE
Fix Release Notes link

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19343]
In the Grafana help, in the [Upgrading Grafana](https://grafana.com/docs/installation/upgrading/) topic, the Release Notes link does not link to the appropriate help topic. Instead, it links to the Community Release Notes page.

It should link to the What's New in Grafana topic. Add some text to this topic so that there is something in that container topic to link to and then fix all links to Release Notes throughout the help content.

**Comment by flopp999** [comment]
this link I think you mean?
https://community.grafana.com/t/release-notes-v6-3-x/19202

**Comment by flopp999** [comment]
It could be that the link in upgrade is always same, otherwise someone needs to change the link every time there is a new version

**Comment by oddlittlebird** [comment]
Correct, but I think the link should be the container topic "What's New in Grafana." Since there is no content in it, you cannot link to it. However, I suspect that if you add content and do a build, that when you click the link in the help TOC, the text will appear. 

Can you do me a favor? Add the following after the front matter in the whatsnew > index.md. Then do a build and see if the behavior of that section of the TOC changes. 

# What's new in Grafana?

Read the release notes to find out what has changed in the most recent Grafana releases.

**Comment by oddlittlebird** [comment]
If it works like I hope, then we will be able to link to that topic once there is content in it.

**Comment by torkelo** [comment]
This link is correct in my view

**Comment by torkelo** [comment]
Our release notes (detailed change log per release) are more important that what’s new for upgrading. And linking to the list of release notes seems fine
