### ISSUE TITLE
Change gerunds to verbs in Playlist and fix formatting

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19341]
In the Playlist topic: https://grafana.com/docs/reference/playlist/

* Change the gerund headings to verb headings. For example, instead of "Creating a playlist," it should be "Create a playlist."
* Also, field names and button names should be bold, not indicated with quotation marks.
* Change an ampersands being used as an abbreviation for "and" to "and."

**Comment by bharjala** [comment]
I'm taking this one on today. Thanks!
