### ISSUE TITLE
Custom graphs

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#1935]
Hi Torkel:

When I try to create a text panel, I have an option to inject a custom html into grafana panel. If I want to use some other graphing libraries like highcharts, would I be able to source the highcharts library and create custom charts?

**Comment by torkelo** [comment]
sure, but you need to also include ALL the code that does the metric requests and process results and init high charts with series. You will basically have to implement it from scratch (so reusing of grafana components in a scenario like this). But you can include any javascript and html you like in a text panel that uses html, so everything is possible, but sounds like a lot of work, unless you have a simple request to an app you want to make and graph a simple graph in highcharts.

What are you trying to do?

**Comment by gsaray101** [comment]
Yes, I just tried it works, wow. I am trying to integrate R programming and graph the output using highcharts for longer term, forcasting analysis. Very nice!!

**Comment by torkelo** [comment]
@gsaray101 just remember that highcharts is a lot slower than flotcharts when dealing with high resolution metics (graphs with many series and points)
