### ISSUE TITLE
Explore: Logs need line wrap options

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#19355]
This came from @pstibrany:

When scanning logs, sometimes it's more efficient to see one line per log message. 
We could achieve this by adding a switch to the log panel options toolbar to enable/disable line wrapping (default: enabled).

The unwrapped setting would result in horizontal scrolling. (alternative: use ellipsis text rendering). 

This option should be added to 

- [ ] Explore's logs panel
- [ ] Dashboard logs panel
- but is not needed in live view.

**Comment by pstibrany** [comment]
> (alternative: use ellipsis text rendering).

Please no.

I'm coming from searching logs with `grep` and `less`. This request is equivalent to `less -S` option to not wrap lines.
