### ISSUE TITLE
Explore: Selected mode not preserved on refresh

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#19357]
**What happened**:

When logs mode is selected with datasource that supports both metrics and logs, this selection is not preserved when screen is refreshed.

![Kapture 2019-09-24 at 11 41 52](https://user-images.githubusercontent.com/1014802/65501184-d202d980-dec0-11e9-8d6c-cb47b962f2c2.gif)

**What you expected to happen**:

That URL contains mode selection and that after refresh that selection is preserved.

**How to reproduce it (as minimally and precisely as possible)**:
- go to explore
- select elastic as datasource
- switch to logs
- refresh screen

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.0-pre (b0d6ac5f42)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
@davkal I think this is a reasonable expectation based on how we preserve most things in url, so I labeled it as bug. If this is by design though for some reason and should be labeled differently let me know.

**Comment by davkal** [comment]
Definitely an oversight, so bug classification seems reasonable.

**Comment by ivanahuckova** [comment]
I have tested this issue and it has been fixed - mode selection is preserved when screen is refreshed as mode has been added to url. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30407135/69077141-411a2b80-0a35-11ea-8460-f0cea61a0a09.gif)
