### ISSUE TITLE
Anonymous user information access fix still not released

### ISSUE THREAD

**Issue by baniocarpentercode42** [grafana/grafana#19368]
**What happened**:
As a user with the viewer role you can still see user information via /api/org/users

**What you expected to happen**:
The fix from Aug 12 to be included in one of the releases since then.

This was reported here: https://github.com/grafana/grafana/issues/17318
This was fixed here: https://github.com/grafana/grafana/pull/18422
However it doesn't seem to have been incorporated in any release since then. The pull request number "18422" doesn't show up in the release notes for any 6.3.x version: https://community.grafana.com/t/release-notes-v6-3-x/19202

**How to reproduce it (as minimally and precisely as possible)**:
Sign in as a user with the viewer role and go to /api/org/users 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: cloudwatch
- OS Grafana is installed on: official grafana docker image
- User OS & Browser: Linux, Mac, Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
the milestone under PR https://github.com/grafana/grafana/pull/18422 

6.4-beta1 so it's included in next stable (next week)

**Comment by baniocarpentercode42** [comment]
I see this fix mentioned here: https://github.com/grafana/grafana/milestone/134?closed=1
But I don't see it mentioned in the Release Notes v.6.4.x: https://community.grafana.com/t/release-notes-v-6-4-x/21088
Is this in v6.4.x?

**Comment by marefr** [comment]
@baniocarpentercode42 yes it's in v6.4.x. We must have missed to add it to the changelog.
