### ISSUE TITLE
Refactor and unify usage of maxDataPoints

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#19365]
Right now there is ambiguity around [maxDataPoints](https://github.com/grafana/grafana/blob/bbf2bd18fd44b2f09a8a5e730b2145aa72fdcd01/packages/grafana-ui/src/types/datasource.ts#L451). In general it is used to limit number of data points to some sensible number so the data does not need to be sampled for display. For example in Graph it is set no the width of the graph in pixels.

For Logs we reuse the same attribute to say what number of logs we want to be returned but that means it is much more arbitrary. In this [fix](https://github.com/grafana/grafana/pull/19235) we removed hardcoded limit in explore, which means that it should use `Maximum lines` setting in Loki datasource config. At the same time `maxDataPoints` is non optional so this breaks typing.

Also other data source like Elastic and Influx do not have such setting on datasource level so the number of logs they return is hardcoded inside the datasource itself.

Some datasources have a setting in query editor to set the `maxDataPoints` on query level or have some specific way to do it (in case of Elastic this is `size` attribute on query). This though usually isn't translated to Explore query editor which can be different than standard query editor.

**Comment by ryantxu** [comment]
Also check #18999, and related #16479

there is ambiguity around "maxDataPoints" as LIMIT X vs a way to influence the interval, vs the streaming buffer size.

**Comment by davkal** [comment]
Recently fixed by @aocenas
