### ISSUE TITLE
Build from Master stuck at yarn start

### ISSUE THREAD

**Issue by rmunoz10** [grafana/grafana#19363]
**What happened**:
`yarn start` is stuck at this step

MiB                          vendors~app  [emitted]  vendors~app
[Webpack]                         vendors~app.eb8fbe010909ca8b0bc2.js.map   7.46 MiB                          vendors~app  [emitted]  vendors~app
[Webpack] Entrypoint app = runtime.eb8fbe010909ca8b0bc2.js runtime.eb8fbe010909ca8b0bc2.js.map angular~app.eb8fbe010909ca8b0bc2.js angular~app.eb8fbe010909ca8b0bc2.js.map moment~app.eb8fbe010909ca8b0bc2.js moment~app.eb8fbe010909ca8b0bc2.js.map vendors~app.eb8fbe010909ca8b0bc2.js vendors~app.eb8fbe010909ca8b0bc2.js.map default~app.eb8fbe010909ca8b0bc2.js default~app.f03f32670a14c86e5ee2.hot-update.js default~app.eb8fbe010909ca8b0bc2.js.map default~app.f03f32670a14c86e5ee2.hot-update.js.map app.eb8fbe010909ca8b0bc2.js app.eb8fbe010909ca8b0bc2.js.map
[Webpack] Entrypoint dark = runtime.eb8fbe010909ca8b0bc2.js runtime.eb8fbe010909ca8b0bc2.js.map grafana.dark.eb8fbe010909ca8b0bc2.css dark.eb8fbe010909ca8b0bc2.js dark.f03f32670a14c86e5ee2.hot-update.js grafana.dark.eb8fbe010909ca8b0bc2.css.map dark.eb8fbe010909ca8b0bc2.js.map dark.f03f32670a14c86e5ee2.hot-update.js.map
[Webpack] Entrypoint light = runtime.eb8fbe010909ca8b0bc2.js runtime.eb8fbe010909ca8b0bc2.js.map grafana.light.eb8fbe010909ca8b0bc2.css light.eb8fbe010909ca8b0bc2.js light.f03f32670a14c86e5ee2.hot-update.js grafana.light.eb8fbe010909ca8b0bc2.css.map light.eb8fbe010909ca8b0bc2.js.map light.f03f32670a14c86e5ee2.hot-update.js.map
[Webpack] [./public/sass/grafana.dark.scss] 39 bytes {dark} [built]
[Webpack] [./public/sass/grafana.light.scss] 39 bytes {light} [built]
[Webpack]     + 3106 hidden modules

**What you expected to happen**:
yarn start complete

**How to reproduce it (as minimally and precisely as possible)**:
1. Fresh install of centos 7
2. Build Grafana from source
https://github.com/grafana/grafana/blob/master/docs/sources/project/building_from_source.md
3. When at Build the Frontend Assets 'yarn start' gets stuck

**Anything else we need to know?**:

**Environment**:
centos7, node v10.16.3, go1.12.9 
- Grafana version:
master
- Data source type & version:
none
- OS Grafana is installed on:
centos 7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Does Grafana load when you go to localhost:3000? Does webpack rebuild when you modify any of the front-end files?

**Comment by rmunoz10** [comment]
Grafana loads on localhost:3000. webpack does not rebuild automatically after I change a *.scss file.

**Comment by dprokop** [comment]
@rmunoz10 build on SASS file changes are super quick. Have you verified in Grafana that the styles haven't changed?

**Comment by rmunoz10** [comment]
I changed _login.scss and changes were not reflected.

**Comment by rmunoz10** [comment]
I also made a simple change in Footer.tsx (line 20: from Docs to DocsX) for testing... changes were not reflected.  Anything I'm missing?

**Comment by smijolovic** [comment]
Same on CentOS 8 with nodejs 10.16.3-2 and go 1.13.1

Just stuck on Webpack + 3096 hidden modules.

Never exits and a "node" process keeps running. No changes were made to the frontend source code, so it doesn't make sense why it doesn't complete.

**Comment by torkelo** [comment]
yarn start does not complete it launches webpack in watch mode. 

Are you running Grafana binary in dev mode? needed for it to find the new frontend assets
https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#configure-grafana-for-development

**Comment by wujb13** [comment]
change   fs.inotify.max_user_watches=524288
