### ISSUE TITLE
Table: Number Column Style for Infinity and Infinity-

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#19375]
**What would you like to be added**:
For the table view, when using the Number column style the output of `Infinity` and `Infinity-` are `NA`. Instead I think these should be `Inf+` and `Inf-` (or whatever consistent representation the author likes).

Other "funny" values seem to behave reasonably:

* `NaN` is `NaN`
* null is a hyphen: `-`

**Why is this needed**:
For consistency, not a high priority. Raw values can be viewed by removing the Number style.

**Comment by kylebrandt** [comment]
I didn't describe my scenario completely :-/ I was using Number column style with `short`. After this change, `short` still shows NA.  

When using `none` with number before it was showing `Infinity.00`
`-Infinity.00` so this is better in the `none` case now. But it would be nice if `short` also showed Inf since it is the default when selecting a table visualization.

**Comment by ryantxu** [comment]
@marefr -- this is minor, but not really required for 6.4 (ok if it is included, but not required)

**Comment by marefr** [comment]
The #19376 PR is in 6.4-beta2 so thought this was needed for 6.4 stable. Sorry. Please remove milestone or move to 6.5.
