### ISSUE TITLE
Fix inconsistent permissions in Debian package postinst for /etc/grafana

### ISSUE THREAD

**Issue by rda0** [grafana/grafana#19372]
**What would you like to be added**:

I would like permissions to be applied with `chown` in the same fashion (using `find`) as with `chmod` in the [Debian postinst script](https://github.com/grafana/grafana/blob/master/packaging/deb/control/postinst):

```
diff --git a/packaging/deb/control/postinst b/packaging/deb/control/postinst
index 957f8aef3..a1a2a22fc 100755
--- a/packaging/deb/control/postinst
+++ b/packaging/deb/control/postinst
@@ -43,7 +43,7 @@ case "$1" in
   fi
 
 	# configuration files should not be modifiable by grafana user, as this can be a security issue
-	chown -Rh root:$GRAFANA_GROUP /etc/grafana/*
+	find /etc/grafana ! -path /etc/grafana -exec chown -h root:$GRAFANA_GROUP {} ';'
 	chmod 755 /etc/grafana
 	find /etc/grafana -type f -exec chmod 640 {} ';'
 	find /etc/grafana -type d -exec chmod 755 {} ';'

```

**Why is this needed**:

The current `postinst` script applies the file mode `640` to all files (including hidden dotfiles) inside the directory `/etc/grafana`, but it does not change ownership to `root:$GRAFANA_GROUP` on hidden dotfiles.

We use to create a git repositories in configuration directories to track configuration changes and our monitoring system keeps an eye open for any dirty git repositories. If a commit is done as `root`, git creates some files in `/etc/grafana/.git` and after a grafana package update, those files are not accessible anymore to the monitoring user, which is a member of the `$GRAFANA_GROUP` group.

While a workaround for our setup should be trivial and a no problems exist with the default `/etc/grafana` directory structure, I still kindly ask for a solution at the source.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
