### ISSUE TITLE
Grafana 2.0 login problems

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#1937]
After running grafana 2.0 for more than a week it was no longer possible to save dashboards, even if logged in as admin:admin. This was confirmed from two different client hosts. [auth.anonymous] had been enabled (the only change to grafana.ini). It seems that logging in as admin still left grafana in the Viewer only mode (associated with the anonymous user).

After restarting the service, and logging in as admin the save icon reappeared.

I couldn't find any porblems in /var/log/grafana or in the browser debug console (although perhaps I did not look in the right places in the debug console)

After 5 minutes the same problem reappeared. After changing back [auth.anonymous] to false and restarting the server, I get a browser error GET http://<grafana-IP>:3000/ net::ERR_TOO_MANY_REDIRECTS. It is redirecting between between :3000 and :3000/login.
Next I cleared all grafana cookies and tried again. Now I get the login screen. After logging in as admin:admin I get the too many redirects again.

**Comment by torkelo** [comment]
Very strange, I have been using auth.anonymous enabled on http://play.grafana.org since the first alpha release without ever any such an issue. Do not really understand what could cause it. 

What version of grafana are you using? (v2.0.2 or v2.0.1 or one of the beta releases?)

**Comment by IzakMarais** [comment]
I am running v2.0.1 (grafana-2.0.1-1.x86_64.rpm).

**Comment by torkelo** [comment]
And what configuration do you have? Do you use any reverse proxy infront of grafana? What session store do you use?

**Comment by IzakMarais** [comment]
It looks like the disk under grafana is out of space. (Which also explains why there was nothing new getting added to the log files). Starting form the command line and logging to stdout gives:

`[Macaron] PANIC: session(release): write /var/lib/grafana/sessions/c/3/c303476a3a416c9f: no space left on device`

This would probably explain the situation. I will reconfigure the server and confirm once everything is running again.

**Comment by torkelo** [comment]
ok, good that you found the problem.
