### ISSUE TITLE
Text in rendered png consists of unknown characters

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#1938]
When using the share panel to get a link to a rendered png image, all characters in the resulting images are "missing character" boxes:
![rendered_image_unknown_chars](https://cloud.githubusercontent.com/assets/3284111/7471704/7cc46e88-f32a-11e4-9198-df505c655760.png)

This is Grafana 2.0.2 on stock CentOS 6.6. Do I need to install additional fonts?

**Comment by torkelo** [comment]
Install font pages, what os and version are you using? Try googing on what font pages phantomjs requires for your distro, the rpm and deb packages have defined font packages dependencies but if you installed from tar file you need to install those manually. And depending on distro and version you might need other font pages.

**Comment by torkelo** [comment]
Sorry for asking about os and version, did not read past the image :)

**Comment by jessetan** [comment]
I installed grafana using yum, so all dependencies should be there right? According to `repoquery --requires grafana` it only depends on sh, fontconfig and initscripts, not phantomjs, which may be why the dependencies are not properly installed.

Anyway, installing additional fonts using `yum install urw-fonts` resolved the issue.

**Comment by calebcall** [comment]
Had this same problem, same setup (CentOS 6) and installing the urw-fonts also fixed it for me.
