### ISSUE TITLE
Locking Grafana Dashboards

### ISSUE THREAD

**Issue by emdahl** [grafana/grafana#19391]
**The request is for the function of "locking" a dashboard such that only the creator of the dashboard can edit it. However, other users (within the same Grafana account, but login through AzureAD) can duplicate the dashboard and edit the duplicated dashboards as their own**:

**This has been requested from the company leaders so that they can share dashboards and build on each others dashboards, without having other users tamper with unfinished dashboards**:

**Comment by marefr** [comment]
You should be able to do this using folders and permissions. Most of the users could have viewer permission on org level, then a user with org role editor/admin can create a new dashboard in general folder or a new folder with proper permissions. 

You may need to enable [viewers_can_edit](https://grafana.com/docs/installation/configuration/#viewers-can-edit) setting which means that a viewer is able to edit a dashboard, but they cannot save it. Example here (https://play.grafana.org/d/000000012/grafana-play-home?orgId=1). Possibly also [editors_can_admin](https://grafana.com/docs/installation/configuration/#editors-can-admin) may be interesting.
