### ISSUE TITLE
Incorrect color scale when using a heatmap with log-scale

### ISSUE THREAD

**Issue by tomdug** [grafana/grafana#19393]
**What happened**:
Grafana incorrectly assigns color to buckets when using a logarithmic scale. The legend indicates a maximum value of 4, although the bucket contains 6 values and has a color that represents a value of 2. This seems to be related to the way 0s are handled when using a log scale.

![Screenshot_20190925_101132](https://user-images.githubusercontent.com/19854606/65582030-dbea1280-df7c-11e9-9342-f7e3d70e9494.png)

Also, this toggle does not seem to work
![Screenshot_20190925_102053](https://user-images.githubusercontent.com/19854606/65582696-2e77fe80-df7e-11e9-9888-90de1b8a662f.png)

**How to reproduce it (as minimally and precisely as possible)**:
Here is demo of the bug:
https://snapshot.raintank.io/dashboard/snapshot/YfSMnwgvL4lEU1rDGjK61oTrjznIpeQE

> To reproduce the issue, consider the following dataset with 7 values : [2, 1, 1, 0, 0, 0, 0] (with the same timestamp)
> 
> - The **linear** scale splits the data in 3 buckets as you would expect: **0** (4 values), **1** (2 values), **2** (1 value) and the legend goes from 0 to 4 (maximum).
>  
> - The **log** scale splits the data in 2 buckets, one for **0**s and **1**s (6 values) and one for **2** (1 value). However the color seems to indicate a value of 2 for the first bucket instead of 6
> 
> **-> The bucket with 0s and 1s contains 6 values, has a color that indicates 2, and a legend with a maximum value of 4**
> 
> **Possible explaination**: It seems that under the hood, **0**s are put into a special bucket (see [here](https://github.com/grafana/grafana/blob/2474511d03def2b1d31fb723d7b12bd0cad8dbb9/public/app/plugins/panel/heatmap/heatmap_data_converter.ts#L124))
> that is merged with the bucket with **1**s when displayed. However, this special bucket is still taken into account for the computation of the color scale (that is why the maximum is 4) but only **1**s are considered when computing the color of the bucket (2) 
> 

**Environment**:
- Grafana version: 3.6.5
- Data source type & version: TestData Db
- OS Grafana is installed on: Grafana cloud
- User OS & Browser: Ubuntu 18.10, Chrome
- Grafana plugins: -

**Comment by marefr** [comment]
@tomdug Can you show me how you have configured grafana testdata query in your panel? Trying to reproduce this on current master, but don't get the same result as you.

**Comment by tomdug** [comment]
![Screenshot_20190925_125717](https://user-images.githubusercontent.com/19854606/65595037-26c35480-df94-11e9-9d58-460fe68e8873.png)
![Screenshot_20190925_125753](https://user-images.githubusercontent.com/19854606/65595014-1a3efc00-df94-11e9-908c-58f510411805.png)

**Comment by marefr** [comment]
Confirmed bug on master (c60882b)

**Comment by leeoniya** [comment]
this should be fixed in the new heatmap panel. the color scale is not related to the linear or log bucket (the y axis/scale), but to the count/value within the buckets.
