### ISSUE TITLE
feature request: Option to display a panel only if a certain metric exists 

### ISSUE THREAD

**Issue by jasonrosy** [grafana/grafana#1940]
Hi Torkelo

Thanks for all the great work on Grafana.  

How feasible would it be to add an option to only display a panel if a certain metric exists?  I am fully aware this could be handled by a scripted dashboard but would like to avoid this route for now.

Before the panel renders as visible it will perform a query against graphite to check if it exists.  If it exists then render the panel.  This would come in handy when i want to display an extra panel for a server that contain additional metrics when most of the subset of servers don't have the specific metric and would render a blank graph.

Jason

**Comment by torkelo** [comment]
might be solved by https://github.com/grafana/grafana/issues/1888 

Do not think this will be covered by regular grafana dashboards. But at some point this year or next year I will really make scripted dashboards more powerful and easy to build.
