### ISSUE TITLE
Grafana dosn't validate e-mail when inviting users

### ISSUE THREAD

**Issue by xelite** [grafana/grafana#19406]
**What happened**:

When invite new users and select „Send invite email” grafana dosnt validate email address and when it is incorrect show green notify „Created invite for <USERNAME>”. When e-mail was sent i see green notify „Sent invite \<USERNAME>”

**What you expected to happen**:

Red notice that email was not sent or is incorrect

**How to reproduce it (as minimally and precisely as possible)**:

Paste incorrect e-mail eg. `login@email.com_`

**Comment by torkelo** [comment]
it's either username or email (as not all users have an email)

we have some designs for improving this workflow  https://github.com/grafana/grafana/issues/10237
