### ISSUE TITLE
Alert render image not correct time range

### ISSUE THREAD

**Issue by huynhsamha** [grafana/grafana#19401]
**What happened**:
Image rendered when an alert is triggered is not in time range it happened.

**What you expected to happen**:
Image rendered when alert is triggered

**How to reproduce it (as minimally and precisely as possible)**:
Let an alert with interval 30s, for 10s. Then we trigger the alert by insert a record which make the condition true, an image is rendered but it is not in the time range.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: 6.5.0
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 16.04
- Grafana plugins: grafana-image-render or PhantomJS
- Others: I set timezone in PostgreSQL and TimescaleDB is UTC. I also try Grafana Dashboard Timezone with Browser Timezone and UTC, but both not working.

In my screenshots, image is rendered in next 1 hour.

![img1](https://user-images.githubusercontent.com/24195776/65593061-f9899d00-dfb9-11e9-8d79-b3be831e8b97.png)

![img2](https://user-images.githubusercontent.com/24195776/65593060-f9899d00-dfb9-11e9-99bb-9d066c5250b7.jpg)

**Comment by marefr** [comment]
@huynhsamha do you have time override in panel?

**Comment by huynhsamha** [comment]
I've just fixed my bug by override the time range in dashboard (check `Save current time range` button on saving dashboard)

![img4](https://user-images.githubusercontent.com/24195776/65594363-c98fc900-dfbc-11e9-9f6f-e7501b181393.png)

Because I'd thought image will be rendered at the trigger appeared.

How to have time override in panel? Can you explain to me?

**Comment by marefr** [comment]
Thanks. Time override is not recommended in combination with alerting. But here's the docs https://grafana.com/docs/reference/timerange/#panel-time-overrides-timeshift
