### ISSUE TITLE
Prometheus label_values does not return empty string value

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#19408]
**What happened**:
Say I have a Prometheus database that counts how many people enter my shop and what sort of car they arrived with.

```
persons_entered_shop_total{car = "Audi"} 5
persons_entered_shop_total{car = "Volkswagen"} 4
persons_entered_shop_total{car = ""} 8
```

Empty string indicates they did not come by car. Perfectly valid data set as far as Prometheus is concerned.

Now I try to make a variable query to filter by type of car.

`label_values(persons_entered_shop_total, car)`

So far so good. But what's that? This is the result:

* Audi
* Volkswagen

But where did my empty string value go?! It vanished!

**What you expected to happen**:

I expect empty string to be present in the label_values list if empty string is a label value used in Prometheus database.

**How to reproduce it (as minimally and precisely as possible)**:

Create Prometheus data set above and a variable with the query shown above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.6
- Data source type & version: Prometheus 2.12.0
- OS Grafana is installed on: Ubuntu (container)
- User OS & Browser: Firefox 69 on Windows 10
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Is Prometheus returning an empty value? 

Currently empty template variable values are not supported https://github.com/grafana/grafana/issues/5970

**Comment by sandersaares** [comment]
> Is Prometheus returning an empty value?

Aha, good question. Indeed, it looks like Prometheus is already not returning this value in its "series" API call.
