### ISSUE TITLE
Adapt refresh value when time range changes

### ISSUE THREAD

**Issue by arcenik** [grafana/grafana#19403]
**What would you like to be added**:

The refresh is manually selected and is independent from the time range. But it does not make any sens to keep a quick refresh rate with a large time range.

For example, you start with a refresh rate of 5s on last 12 hours. If you decide to display last 6 months, the refresh rate stay the same. As it take more time to retrieve  6 months of data, it is possible than the graph are being refreshed before getting displayed.

**Why is this needed**:

The refresh rate should be adapted to the time range, with a minimal value of $__interval for example.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
