### ISSUE TITLE
Automatically push grafana docker image to Docker hub registry

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1941]
I think currently pushing a new grafana image to the docker registry is a manual task, since the image is last updated 1 week, 5 days ago (https://registry.hub.docker.com/u/grafana/grafana/).

This is probably cumbersome for you guys to have to manually do this and also not the best experience for the users who have to wait quite some time to get the new docker image.

Would it be possible to improve this workflow by automating it? Something like adding a post step in the build system to automatically publish the grafana image to docker hub?

**Comment by torkelo** [comment]
yea, would really like this, havent had time to fix that yet.

**Comment by costimuraru** [comment]
Can we do a manual update for the time being? Current last update is 2 weeks, 4 days ago.

**Comment by haf** [comment]
It's 3 weeks now. InfluxDB 0.9 w/ `latest` Grafana isn't that stable.

Here are the docs on how to auto-build for the Docker Hub; basically;

 1. Sign in to Docker Hub
 2. OAuth-orize with github
 3. Give Limited access to this repo/account
 4. Set a service hook
 5. Place a Dockerfile in the root of this repo.

from https://docs.docker.com/docker-hub/builds/

**Comment by flangelier** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by daniellee** [comment]
Finally finished!

There are new images on [Docker Hub](https://hub.docker.com/r/grafana/grafana/tags/). The last release build is 2.6.0 and the "latest" build is also 2.6.0. The new master build is based on the Grafana master branch.

Everything is built automatically. It looks like this:
1. CircleCI build for Grafana's master branch is triggered by a commit
2. If successful it triggers the CircleCI grafana packer build.
3. This copies the debian package etc to AWS
4. If successful it triggers the CircleCI Grafana Docker build
5. The Grafana Docker build, builds the docker image based on the debian package from step 3.
6. If successful it does a docker push to Docker Hub with a build tagged as "master"

I will be keeping an eye on this until I feel sure that the whole chain is stable and works reliably every time. I will probably need to put in a few retries for some steps and cache some stuff for CircleCI to improve the build times.
