### ISSUE TITLE
After save, data in panel plugin not in the same order for arrays

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#19426]
**What happened**:
Hi,
I am the author of plugin Flowcharting, I have an issue in my project reported here
https://github.com/algenty/grafana-flowcharting/issues/38#issuecomment-534918433

In flowcharting, I have a json with a array (the rules name)
A, B C
After save and reload, the json return the array but not in the same order in Grafana 6.3
B, A, C

On grafana 5.4.3, the array stays in the same : 
A, B, C

**What you expected to happen**:
Json/data stay the same order on reload

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Windows /linux
- Grafana version: 6.2.5, 6.3.5
- Data source type & version: no datasource needed
- OS Grafana is installed on: Cent OS, windows 10
- User OS & Browser: Crhome
- Grafana plugins: Flowcharting
- Others: NA

BR
Arnaud

**Comment by torkelo** [comment]
can you show the panel json before and after save?

**Comment by torkelo** [comment]
closing due to lack of update
