### ISSUE TITLE
Data source plugin does not export any Query Editor component on Mixed Queries

### ISSUE THREAD

**Issue by Napfton** [grafana/grafana#19420]
**What happened**:
I get "Data source plugin does not export any Query Editor component" when I want to setup a mixed data source querie to 2 influx DBs (one by one they work)

**What you expected to happen**:
A query editor is shown to define a mixed data source query.

**How to reproduce it (as minimally and precisely as possible)**:
Create 2 influx db data sources, add dashboard, add panel, select "mixed" for "Queries to" dropdown, then add Query and also "mixed"

**Environment**:
- Grafana version: Version 6.3.6 (commit: fdd2117)
- Data source type & version: InfluxDB 1.7.6
- OS Grafana is installed on: Raspbian GNU/Linux 9 (stretch)
- User OS & Browser: Debian 10, tried with latest Chrome and Firefox
- Grafana plugins: none
- Others: none

**Comment by hugohaggmark** [comment]
Thank you for reporting this @Napfton! We'll have a look at this. I don't think you should be able to add a `Mixed` query to a `Mixed datasource` or wdyt @torkelo?

**Comment by torkelo** [comment]
Yea, no point in adding a mixed data query when primary datasource is already set mixed

**Comment by Napfton** [comment]
I am at a loss here: How can I add/define a single query to 2 different data sources? I was told that this is possible...

**Comment by hugohaggmark** [comment]
When you add query instead of selecting `mixed` add one of your Influx datasources.
![image](https://user-images.githubusercontent.com/562238/66032785-516a5b80-e506-11e9-92ac-45a1fff29f9a.png)

**Comment by hugohaggmark** [comment]
Did that last information help you?

**Comment by Napfton** [comment]
@hugohaggmark sadly not :( I do get a new query panel below the existing one when I do select one of my influx db data sources instead of mixed, but I cannot select from the other data source then. Only from that one I selected. Lets say I want: SELECT * FROM db1.table1 t1, db2.table2 t2 WHERE t1.id = t2.id; 

Is that even possible? Because what I read in your docs and been told by other people, it should, but I dont know how :(

**Comment by hugohaggmark** [comment]
Could you try adding another Query pointing to your other (t2) Influx datasource?

**Comment by Napfton** [comment]
Seperate queries (per DB/measurement) are possible. I have read a bit more now and apparently neither grafana nor influxdb support cross database/datasource queries.

**Comment by MediaMaquina** [comment]
So to clarify because i'm a noob and i've been trying all day.
i have 2 servers running prometheus. I can't display the current outgoing bandwidth on the same panel? Correct? If i choose "mixed" i think it's mixing both bandwidth into a single line.
If i don't chose mixed i can't add a query for the 2nd server.
So 1 panel = 1 server? Unless you want to "mix" all the data which is not the same as showing all data separately in a panel?

**Comment by hugohaggmark** [comment]
Hi @MediaMaquina, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best

**Comment by MediaMaquina** [comment]
Ok np!
