### ISSUE TITLE
FormStyles: FormFieldNew

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#19428]
Basic idea: 
Just a container element that provides the label & description placement. children are any input element. If child is a checkbox should adjust layout to place input to left. 

<img width="897" alt="Screen Shot 2019-09-26 at 09 06 33" src="https://user-images.githubusercontent.com/10999/65665984-00a5bf00-e03d-11e9-90dc-b2ab9a5a6fd1.png">

**Comment by dprokop** [comment]
Closing this in favour of https://github.com/grafana/grafana/issues/19855 epic
