### ISSUE TITLE
Grafana auth.proxy issue in 6.0

### ISSUE THREAD

**Issue by rammohan647** [grafana/grafana#19421]
After configuring auth.proxy with below configs using apache user can authenticate and login but when user click logout and again user login automatically.

It's not allowing users to logout.

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = false
ldap_sync_ttl = 60

Please see below logs  when user clicks on logout it prints "Successful Logout" and immediately relogin's automatically. 

**logs:**

t=2019-09-25T18:58:50+0000 lvl=info msg="Successful Logout" logger=http.server User=XXXX
  | t=2019-09-25T18:58:50+0000 lvl=info msg="Request Completed" logger=context userId=4 orgId=1 uname=XXXX method=GET path=/logout status=302 remote_addr=XX.XX.XX.XXX time_ms=40 size=43 referer="https://XXXX.com/grafana/?orgId=1 "
  | t=2019-09-25T18:58:51+0000 lvl=info msg="Request Completed" logger=context userId=4 orgId=1 uname=XXXX method=GET path=/login status=302 remote_addr=XX.XX.XX.XXX time_ms=24 size=38 referer="https://XXXX.com/grafana/?orgId=1 "

Is this a known bug?

**Comment by marefr** [comment]
Well, you have to handle the signout in apache since that's where the X-WEBAUTH-USER is set.

**Comment by rammohan647** [comment]
When we are using grafana 5.4.3 auth.proxy was working perfectly fine after we upgraded to grafana 6.0 since then users were not able to logout from grafana.

**Comment by marefr** [comment]
Please refer to #17316 which maybe is the feature request that will solve your problem.

**Comment by dkuroki** [comment]
As workaround I find a solution with nginx
`
on nginx configuration:

    location /grafana {
    	auth_basic  "grafana";
    	auth_basic_user_file /etc/nginx/grafana_htpasswd; 
    	proxy_set_header X-WEBAUTH-USER $remote_user;
         proxy_pass http://localhost:3000/grafana;
    }
   location /logout {
    return 401;
   }

   error_page 401 /errors/401.html;

  location /errors {
    auth_basic off;
    ssi        on;
    ssi_types  text/html;
    alias /var/www/html/errors;
  }
`
on 

`
<!DOCTYPE html>
    <div>Ud se ha deslogueado .Redireccionando al home...</div>

<script>
    var XHR = new XMLHttpRequest();
    XHR.open("GET", "/grafana", true, "no user", "no password");
    XHR.send();

    setTimeout(function () {
        window.location.href = "/grafana";
    }, 3000);
</script>
`

on grafana.ini
`
signout_redirect_url =http://XXXXX/logout

`
