### ISSUE TITLE
Legend with auto decimals can have confusing metric prefix

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#1942]
Please change the title of this issue to something more descriptive if needed.

I have a graph displaying a legend; a typical value is in range 200-400, a typical total value is 8000 to 10000. To save space, the total is shortened to e.g. 9K if decimals are explicitly set to 0.
If I set the decimals to auto, the total looks like this:
![metric-prefix](https://cloud.githubusercontent.com/assets/3284111/7473528/2d7ff06a-f33c-11e4-9c91-4cc8bc8638e6.png)
The metric prefix "K" combined with the large number of decimals does not help make the total readable. I would have preferred 9.306K or 9306.43.

Unfortunately, setting decimals to 0 or 3 is not a usable workaround, since 0 provides too little precision for the total, while 3 provides too much for the current value.

**Comment by torkelo** [comment]
Yea. I know, auto decimal precision is one of the more complex areas in Grafana. And some time it does not work auto optimially. 

you are left with two options auto or override and set value. If not even you can set a value that is good in all scenarios then neither can grafana make an optimal solution. 

When auto (or no override), the decimals depend on the max/min for the entire graph (using some complex math to calculated minium decimals for each y-axis tick interval). This auto decimal precision code also takes into account how decimals should be added when scaling units (like 1000 -> 1K) or 1224 -> 1.2s 

The auto decimal precision code is very complex. If you can improve on the current algorithms, here are the test cases for most scenarios:
https://github.com/grafana/grafana/blob/master/public/test/specs/kbn-format-specs.js#L19


The auto decimal precision code is mostly in jquery flot (with some grafana additions)
``javascript
 // estimate number of ticks
            var noTicks;
            if (typeof opts.ticks == "number" && opts.ticks > 0)
                noTicks = opts.ticks;
            else
                // heuristic based on the model a*sqrt(x) fitted to
                // some data points that seemed reasonable
                noTicks = 0.3 * Math.sqrt(axis.direction == "x" ? surface.width : surface.height);

            var delta = (axis.max - axis.min) / noTicks,
                dec = -Math.floor(Math.log(delta) / Math.LN10),
                maxDec = opts.tickDecimals;

            if (maxDec != null && dec > maxDec) {
                dec = maxDec;
            }

            var magn = Math.pow(10, -dec),
                norm = delta / magn, // norm is between 1.0 and 10.0
                size;

            if (norm < 1.5) {
                size = 1;
            } else if (norm < 3) {
                size = 2;
                // special case for 2.5, requires an extra decimal
                if (norm > 2.25 && (maxDec == null || dec + 1 <= maxDec)) {
                    size = 2.5;
                    ++dec;
                }
            } else if (norm < 7.5) {
                size = 5;
            } else {
                size = 10;
            }

            size *= magn;

            if (opts.minTickSize != null && size < opts.minTickSize) {
                size = opts.minTickSize;
            }

            axis.delta = delta;
            axis.tickDecimals = Math.max(0, maxDec != null ? maxDec : dec);
            axis.tickSize = opts.tickSize || size;
            // grafana addition
            axis.scaledDecimals = axis.tickDecimals - Math.floor(Math.log(axis.tickSize) / Math.LN10);
```

**Comment by VitaliyDemchuk** [comment]
How disable auto-prefix for total legend?
