### ISSUE TITLE
Can't (un)select filters

### ISSUE THREAD

**Issue by duylong** [grafana/grafana#19434]
**What happened**:

Filters no show when we click on "Filter on value" button (Table panel). Moreover, panels are not auto reload after selection.

The error:
```
TypeError: e.replace is not a function
    at e.escapeDelimiter (plugin_component.ts:25)
    at plugin_component.ts:18
    at Array.map (<anonymous>)
    at plugin_component.ts:17
    at Array.map (<anonymous>)
    at e.getValueForUrl (plugin_component.ts:15)
    at react2angular.ts:1
    at qt (lodash.js:516)
    at Function.Ua (lodash.js:9343)
    at e.fillVariableValuesForUrl (url.ts:85) "Possibly unhandled rejection: {}"
```

Query example:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["plop-2019.09.25""],"max_concurrent_shard_requests":256} {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1569448310205","lte":"1569491510209","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"program:\"squid\""}}],"must":[{"match_phrase":{"http.response":{"query":200}}}]}},"aggs":{"4":{"terms":{"field":"http.response","size":10,"order":{"_count":"desc"},"min_doc_count":1},"aggs":{}}}}
```

**Environment**: 
- Grafana version: Grafana v6.3.5
- Data source type & version: Elasticsearch 6.x
- OS Grafana is installed on: RHEL7
- User OS & Browser: Windows/Firefox

**Comment by torkelo** [comment]
Works here:
https://play.grafana.org/d/000000014/elasticsearch-metrics 

What does the table query return? what is the value your trying to filter on?

**Comment by duylong** [comment]
Works for me too with your example. The only difference is the version.

It's strange, in my dashboard, all tables give this problem. 

For example, I have a table which returns HTTP response code, the table is loaded correctly. But, when I select one value, I get this error and the "Filters" variable is not set, I see only "Filters +" and no "Filters http.response = 200". All panels refresh only when I refresh manualy the dashboard. No problem when I set manualy the filter.

**Comment by duylong** [comment]
It seems that the problem comes from the fields with the integer type in Elasticsearch...

Mapping example:
```
"properties" : {
 "port" : {
     "type" : "long"
 },
```

**Comment by torkelo** [comment]
ah, then related to this I think https://github.com/grafana/grafana/issues/12209
