### ISSUE TITLE
Default notifier on alert is hard to understand/misleading since it cannot be removed

### ISSUE THREAD

**Issue by AEzzatA** [grafana/grafana#19431]
**What happened**:
When you configured Email and/or Slack to send alerts to, there is no way to remove the email option and keep only Slack or nothing for that matter. the only way to solve this is to Add a Email one more time, delete it, then both of them are gone

**What you expected to happen**:

You should be able to remove send to alert mediums

**How to reproduce it (as minimally and precisely as possible)**:

Create an alert, set sending to an email then try to remove it. there won't be the option to do so

**Anything else we need to know?**:
Nothing

**Environment**: 
- Grafana version:  v6.3.5 (67bad72)
- Data source type & version: any
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04 / Chrome and FF
- Grafana plugins: N/A
- Others:

**Comment by marefr** [comment]
Not sure I understand. Think you can include a screenshot which underlines the problem? Thanks

**Comment by marefr** [comment]
That because your first email notifier is configured to be the default for all alerts.

**Comment by AEzzatA** [comment]
I know, yet its very misleading to have an option, save on it, and then refresh to find something else!

**Comment by marefr** [comment]
Reopened and change the title to reflect that this is a UX problem.

**Comment by AlexHeylin** [comment]
I also found this issue.  The default notification rule can be removed, but you have to add it (in addition to the one already there), then remove it which will either remove both versions of it - or sometimes remove ALL notifications. 

I feel like a "default" notification is not the same as the pseudo-mandatory notification that is currently what happens. 
If the intention is to make this a mandatory notification, then the name needs clarification and the workaround that allows its removal needs to be blocked. If the intention is that it is a default notification, then it should be removable directly without requiring a workaround to get it to go.

Also, removing one notification should never remove all notifications, which I have seen happen many times.
