### ISSUE TITLE
Add "goals" to time series charts

### ISSUE THREAD

**Issue by okor** [grafana/grafana#1943]
I would love to have a "goal" or "target" line at a fixed location on charts. Very rough example below. 

![goal](https://cloud.githubusercontent.com/assets/142910/7475912/5a52336a-f318-11e4-87a2-f41f33d100c2.jpg)

If it's already somehow possible let me know but I didn't see a way to do that.

**Comment by torkelo** [comment]
could add a threshold in line mode (added in undes axes and grid tab)

**Comment by okor** [comment]
Yeah, I missed that. Having some sort of label would be very helpful as well. For now I'll just add the goal to the title. Thanks!
