### ISSUE TITLE
[FeatureRequest] Graph: Add drill down links on for individual series

### ISSUE THREAD

**Issue by robert8103** [grafana/grafana#19440]
**What would you like to be added**:
It would be great to add the ability to use drill downlinks in graph charts using X-Axis Mode "Series / Histogram". The link could be accassable by clicking the legend, datapoint(pillar) or description.
![Bildschirmfoto von 2019-09-26 13-17-01](https://user-images.githubusercontent.com/9132973/65685243-d87c8700-e061-11e9-90fc-0e42a5ac237f.png)
**Why is this needed**:
It would be very Helpful for drilling down data or adding external links based on chart data.

**Comment by sadoMasupilami** [comment]
I just wanted to open the same request regarding Data Links for X Axis Series Mode.
Thank you for opening!

**Comment by ernstp** [comment]
I hope this is planned! They said "In future versions of Grafana, we plan to enable Data links in visualizations other than line graphs, add Data links to the visualization legend, and make more series-specific variables available via Data link variables (i.e. tags/labels for data sources that support those)."

**Comment by Ch4nKyy** [comment]
This would be so valuable.

**Comment by belm0** [comment]
Do I understand this issue correctly as "add series data link access to the legend"?

If so, it should not be labeled "awaiting more evidence" because, as mentioned, this was a feature promised in the data link feature announcement.

> In future versions of Grafana, we plan to [...] add Data links to the visualization legend

https://grafana.com/blog/2019/08/27/new-in-grafana-6.3-easy-to-use-data-links/

**Comment by robert8103** [comment]
Hi @belm0, yes you understood it correctly.
Thanks!
