### ISSUE TITLE
Gauge visual bug

### ISSUE THREAD

**Issue by bathrobehero** [grafana/grafana#19444]
**What happened**:
Some gauges have graphical glitches and text smearing on multiple machines and browsers.
It happens with every type of data, the plugin doesn't seem to refresh and redraw the text neither when the numbers are changing or when I resize the gauge.

**Anything else we need to know?**:
[https://i.imgur.com/DWW3GJs.png](https://i.imgur.com/DWW3GJs.png)

[https://i.imgur.com/3FohVTE.png](https://i.imgur.com/3FohVTE.png)

**Environment**:
- Grafana version: 6.3.6
- OS Grafana is installed on: Windows 8.1
- User OS & Browser: Chrome, Mozilla Firefox
- Grafana plugins: none

**Comment by torkelo** [comment]
We have thus far been unable to replicate this (but we have other reports). 

What versions of Chrome or firefox do you get this in?

**Comment by bathrobehero** [comment]
Latest Firefox, latest Chrome and an older Chrome on another machine.

The issue is unique to Grafana's locally hosted site (play.grafana.com works fine) and it also may have only started today (started with Grafana yesterday but it was working fine as far as I remember). Tried making new dashboards, restarting clients, cleaning cookies, etc. none helped.

**Comment by bathrobehero** [comment]
Using the Singlestat Math plugin's Gauge option is working perfectly.

**Comment by torkelo** [comment]
dupe  of https://github.com/grafana/grafana/issues/17939
