### ISSUE TITLE
Question: Trying to do some math with series.

### ISSUE THREAD

**Issue by oprietop** [grafana/grafana#1945]
I'm trying to graph the % disk usage using snmp and no transfomations on the polling side without any luck:

The series are:
snmp.$host.disk_usage.*.{size,used}

I'm trying to do (used*100)/size but can't get it to work. 

First I tried:

A [snmp][$host][disk_usage][*][size]
B [snmp][$host][disk_usage][*][used][scale(100)]
C [divideSeries(#B, #A)]

But it will complain with 'ValueError: divideSeries second argument must reference exactly 1 series'.

After revising the functions i went with:

A [snmp][$host][disk_usage][*][size]
B [snmp][$host][disk_usage][*][used][scale(100)]
C [group(#A, #B)][mapSeries(3)][reduceSeries(divideSeries, 4 , used, size)]

But it will complain with 'TypeError: divideSeries() takes exactly 3 arguments (2 given)'

Funnily if i remove the scale function on B the asPercent and diffSeries functions inside reduceSeries will work but divideSeries won't.

Any pointer would be appreciated, thanks!

**Comment by torkelo** [comment]
Better ask in graphite mailing list or irc channel. If you have a working graphite query I could show how to split it up into separate (linked) grafana queries.
