### ISSUE TITLE
Send Test notification(email), low prio

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#19458]
**What happened**:
It pop up two green messages
**What you expected to happen**:
only on green messages should pop up
**How to reproduce it (as minimally and precisely as possible)**:
send a test mail

**Environment**:
- Grafana version: 6.3.6
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian
- User OS & Browser: Windows, Chrome

**Comment by marefr** [comment]
Cannot reproduce on master (1b5e7ce). Should be fixed for 6.4 stable if there been any problem.
