### ISSUE TITLE
New admin user page for user logged in using LDAP is wrong / does not list current info

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#19459]
![image](https://user-images.githubusercontent.com/10999/65750590-0668d680-e109-11e9-848a-cab459004dad.png)

It it not showing current information:

The above user had server admin (in DB), it belongs to more organizations and teams then listed there (teams is always empty).

**Comment by torkelo** [comment]
Normal admin view: 
![image](https://user-images.githubusercontent.com/10999/65751895-f69ec180-e10b-11e9-9d63-0e2817f8bf7c.png)

**Comment by alexanderzobnin** [comment]
Yes, confirmed, if you change user permissions (isGrafanaAdmin), then ldap user page doesn't show it.

**Comment by alexanderzobnin** [comment]
I suggest moving this issue into the next release (just to make sure new page works OK)
