### ISSUE TITLE
GF_DATABASE_URL

### ISSUE THREAD

**Issue by kkruzich** [grafana/grafana#19455]
**What happened**:
GF_DATABASE_URL is not being read by grafana. 

**What you expected to happen**:
The value of GF_DATABASE_URL to be read by grafana as indicated here https://grafana.com/docs/installation/configuration/#using-environment-variables

**How to reproduce it (as minimally and precisely as possible)**:
export GF_DATABASE_URL="mysql://grafana:PASSWORD@mydatabase.example.com:3306/grafana"
systemctl start grafana-server
grep -i sql grafana.log
t=2019-09-26T20:50:52+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2019-09-26T20:50:52+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2019-09-26T20:50:53+0000 lvl=info msg="Created default admin" logger=sqlstore user=admin

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana-6.2
- Data source type & version:
- OS Grafana is installed on: linux 4.14.138-114.102.amzn2.x86_64
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
You should use an environment file, see [docs](https://grafana.com/docs/installation/debian/#environment-file).
