### ISSUE TITLE
How long are angularjs panels in Grafana V6 supported?

### ISSUE THREAD

**Issue by pwSteve** [grafana/grafana#19460]
We are an industrial company that has been using Grafana for visualization of metrics from industrial machines for several years now and we also developed our own panels in AngularJS. Different panels are very complex and have a lot of features. How long will these AngularJS panels be supported in future Grafana versions? Will there be a time (and if yes: when?) where we have to migrate all panels to REACTJS in order to use the newest Grafana version? Is Grafana planning to support only ReactJS?

**Comment by torkelo** [comment]
We will support angular panels for at least another 1-2 major versions (years)
