### ISSUE TITLE
Enable S3 as persistence

### ISSUE THREAD

**Issue by adriangalera** [grafana/grafana#19466]
It would be nice if Grafana configuration files could be stored in S3 bucket.

We are planning to run Grafana from Docker image and we are not allowed to use EBS to provide persistent changes. Therefore I think S3 would be the preferred way in this scenario.

**Comment by danieldabate** [comment]
In case you didn't know, Grafana also supports MySQL and PostgreSQL:
https://grafana.com/docs/installation/requirements/#database

Non of those require persistent storage. We have a similar limitation and MySQL has been our solution.

**Comment by marefr** [comment]
@adriangalera are you referring to grafana configuration file like .ini file?

**Comment by adriangalera** [comment]
I al refering mostly yo .ini files and dashboards, datasource configurations

**Comment by marefr** [comment]
For .ini files you can use environment variables instead.

**Comment by torkelo** [comment]
This is not possible, Grafana needs a SQL data source
