### ISSUE TITLE
v6.4.0-beta2: deduplicate variable autocompleter in graph data links

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#19478]
**What happened**:

Trying data links variable autocomplete, many duplicated results are shown.

**What you expected to happen**:

Deduplicate identical suggestions

**How to reproduce it (as minimally and precisely as possible)**:

Plot a few series e.g. `rate(node_network_receive_bytes_total[5m])` and try to autocomplete in data links URL field:

![2019-09-27-234756_303x594_scrot](https://user-images.githubusercontent.com/93906/65804358-efb29600-e181-11e9-8365-b37a1e2c9e4a.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.4.0-beta2
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thank you for reporting this @filippog!

**Comment by torkelo** [comment]
Already fixed in https://github.com/grafana/grafana/pull/19396 (will be included in stable)
