### ISSUE TITLE
Adding InfluxDB 0.9 tags/fields as annotations - possible?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#1947]
I'm trying to get my head around the [Annotations](http://docs.grafana.org/reference/annotations/) feature in Grafana.

I will be using InfluxDB 0.9 as a data-source. InfluxDB 0.9 introduced a new "tags" feature, where you can add tags to each data-point. This is on top of InfluxDB 0.8 and before, where you could still have multiple fields. Below is an sample of a schema I might use:

```
 "points": [
         {
            "name": "cpu_load",
            "tags": {
                "host": "server01",
                "core": "0".
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.45,
                "foo": 0.5,
            }
        },
        {
            "name": "iostat_util",
            "tags": {
                "host": "server01",
                "core": "1"
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 1.56,
                "foo": 0.5,
            }
        },
         {
            "name": "db_queued_reads",
            "tags": {
                "host": "server01",
                "database": "singapore",
                "collection": "rare_species"
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.72,
                "foo": 0.5,
            }
        }
    ]
```

My question is - how do I go about adding the `tags` and `fields` above as annotations in Grafana?

So for example, I might want a line graph of the values in `db_queued_reads`, where x-axis was time, and y-axis was `fields.value`. However, when I hover (or click) on each point, I want to see a text-box with say `<host> <database> <collection> <fields.foo>`.

Is something like this possible with Grafana?

(I do understand from #1525 that InfluxDB 0.9 support is still being ironed out - also interested in how you think things will work, and what's on the roadmap).

**Comment by torkelo** [comment]
InfluxDB 0.9 support is still at alpha level, https://github.com/grafana/grafana/issues/1525 
Hope to complete it for Grafana v2.1 or v2.2 release

**Comment by victorhooi** [comment]
Thanks for the quick reply.

Just to clarify, are you saying the previous (adding tags and fields as annotations) is on the roadmap and will be possible around Grafana 2.1 or 2.2, but is not possible right now?

**Comment by torkelo** [comment]
yes

**Comment by torkelo** [comment]
it is on the roadmap for the influxdb 0.9 support
