### ISSUE TITLE
grafana-cli: cannot install anymore plugin with specific version

### ISSUE THREAD

**Issue by olivierlemasle** [grafana/grafana#19489]
**What happened**:

`grafana-cli plugins install <plugin-id> <version>` is broken (fails with error "Version you want is not supported on your architecture and os").

`grafana-cli plugins install <plugin-id>` (without version) still works.

It seems to be a regression from #17551.

**What you expected to happen**:

I would exepect the plugin to be installed with the version specified.

**How to reproduce it (as minimally and precisely as possible)**:

On latest Grafana (`6.4.0-beta2` or `master`), enter:

    grafana-cli plugins install grafana-clock-panel 1.0.3

You'll have the following error:

```
Error: ✗ Version you want is not supported on your architecture and os. Latest suitable version is 1.0.3

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
```

The same error has been reproduced with other plugins and other versions. The error occurs even if the specified version is the latest suitable version of the plugin.

Everything works when no version is specified:

```
grafana-cli plugins install grafana-clock-panel
installing grafana-clock-panel @ 1.0.3
from: https://grafana.com/api/plugins/grafana-clock-panel/versions/1.0.3/download
into: /var/lib/grafana/plugins

✔ Installed grafana-clock-panel successfully 

Restart grafana after installing plugins . <service grafana-server restart>
```

**Anything else we need to know?**:

It did work in Grafana 6.3.6; the regression seems to be in commit 8c49d27705.

**Environment**:
- Grafana version: `6.4.0-beta2` or `master`
- Data source type & version: SQLite
- OS Grafana is installed on: Alpine (Docker image)
- User OS & Browser: N/A
- Grafana plugins: No plugin
- Others:

**Comment by hugohaggmark** [comment]
Thank you for taking the time to report this @olivierlemasle. we'll have a look at this!
