### ISSUE TITLE
Grafana not displaying images in alert notification emails

### ISSUE THREAD

**Issue by m-peko** [grafana/grafana#19480]
**What happened**:
After upgrading Grafana from version 5.2.4 to version 6.3.5, images / graphs are not displayed in alert notification emails.

**What you expected to happen**:
I expect images / graphs are displayed in alert notification emails in the same way as they are displayed in the test notification email.

**How to reproduce it (as minimally and precisely as possible)**:
I am running Grafana version 6.3.5 in Docker Alpine environment with no memory limits.

**Anything else we need to know?**:
I tried installing `freetype`, `freetype-dev` and `fontconfig` packages but that didn't help.

Traces:
```
t=2019-09-28T12:58:02+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="exit status 127",
t=2019-09-28T12:58:02+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="exit status 127"
```

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: Alpine Linux
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: None

**Comment by hugohaggmark** [comment]
Thank you for taking the time to report this @m-peko, can you supply some more information about your env like which [image provider](https://grafana.com/docs/installation/configuration/#provider) and [renderer](https://grafana.com/docs/administration/image_rendering/) you're using?

**Comment by m-peko** [comment]
Hi @hugohaggmark,
Thanks for replying.

I don't have `external_image_storage` provider specified in my `grafana.ini` file. I tried setting it to `local` but that didn't fix the issue.

Furthermore, since I am on Alpine Linux, PhantomJS is being used. I am installing following packages
```
apk add --no-cache freetype freetype-dev fontconfig
apk add --no-cache su-exec ca-certificates openssl
apk add --no-cache --virtual .build-deps fontconfig
```
but that also didn't help.

**Comment by m-peko** [comment]
Please note that I had this feature of having images rendered in alert emails in version 5.2.4.

**Comment by marefr** [comment]
@m-peko Grafana in Docker based on Alpine Linux is not supported for v6.3.5. Please upgrade to 6.4-beta2 or nightly if you want to use official Alpine Linux image by Grafana.

**Comment by marefr** [comment]
Please have a lock in 6.4-pre Dockerfile https://github.com/grafana/grafana/blob/master/packaging/docker/Dockerfile

**Comment by m-peko** [comment]
What is the last Grafana alpha version that is supported for Alpine Linux?

**Comment by marefr** [comment]
Docker tag 6.4.0-beta2 or master

**Comment by m-peko** [comment]
But how did it worked then with v5.2.4?

**Comment by marefr** [comment]
@m-peko hard for me to know if you've used alpine on 5.2.4 as well. Maybe there are a problem with PhantomJS? Can you add this configuration and see if you get any other detailed info in Grafana server log?

.ini:
```
[log]
filters = rendering:debug
```

**Comment by m-peko** [comment]
This is what I get:
```
t=2019-09-30T08:32:08+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1082 newState=alerting prev state=unknown,
t=2019-09-30T08:32:08+0000 lvl=info msg=Rendering logger=rendering path="d-solo/messaging/messaging-import-and-broker?orgId=1&panelId=5",
t=2019-09-30T08:32:08+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/messaging/messaging-import-and-broker?orgId=1&panelId=5&render=1 width=1000 height=500 png=/grafana/data/png/AVPGnkS9HK7bZqLOE2wr.png domain=localhost timeout=30 renderKey=r9L0fEm5c7e4QKOqKvUORcQ53hCNKJNy]" timezone=,
t=2019-09-30T08:32:08+0000 lvl=dbug msg="Phantomjs output" logger=rendering out=,
t=2019-09-30T08:32:08+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="exit status 127",
t=2019-09-30T08:32:08+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="exit status 127",
t=2019-09-30T08:32:08+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="exit status 127"
```

**Comment by m-peko** [comment]
Seems like `/grafana/data/png/` directory is always empty. Do you know what could be the reason for that?

**Comment by marefr** [comment]
Are you sure you have phantomjs located in `/grafana/tools/phantomjs/phantomjs`? The exit status 127 sounds like you don't given for example this topic: https://stackoverflow.com/questions/1763156/127-return-code-from

FYI Grafana v6.4 is released now. Please try it out and let us know the outcome.

**Comment by m-peko** [comment]
@marefr  Did Grafana v6.4 drop PhantomJS?

**Comment by marefr** [comment]
@m-peko no, just deprecated it. It's still there.

**Comment by m-peko** [comment]
So, to replace PhantomJS I just need to install `grafana-image-renderer` plugin, right?

**Comment by m-peko** [comment]
Solution is to update Grafana to version 6.4.0, install `grafana-image-renderer` plugin from source and start it to listen on whatever port you want. Also, it is required to add `[rendering]` section to Grafana configuration file.
Thanks

**Comment by hugohaggmark** [comment]
Glad to hear that worked out for you @m-peko!

**Comment by harishkunta** [comment]
> Solution is to update Grafana to version 6.4.0, install `grafana-image-renderer` plugin from source and start it to listen on whatever port you want. Also, it is required to add `[rendering]` section to Grafana configuration file.
> Thanks

**Comment by harishkunta** [comment]
> Solution is to update Grafana to version 6.4.0, install `grafana-image-renderer` plugin from source and start it to listen on whatever port you want. Also, it is required to add `[rendering]` section to Grafana configuration file.
> Thanks

**Comment by harishkunta** [comment]
Hi @m-peko 
You said that it is required to add [rendering] section to grafana configuration file, can you share that configuration here

**Comment by msikka93** [comment]
Hi @m-peko ,

Does grafana support images in Alert Notification Emails for verion v6.0.2?
As of now images are not rendered for the alert notifications.
I have grafana-image-renderer plugin installed on my grafana server.

Can you suggest what could be wrng!

**Comment by m-peko** [comment]
Hi @msikka93, I worked with this long time ago now but I think you should have images in alert notification emails. You could check grafana logs. There should be some valuable information!
