### ISSUE TITLE
PageTitle: Option to change page title prefix 

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#19486]
**What would you like to be added**:
It would be nice to be able to change browser tab title or at least disable " - Grafana" postfix.

**Comment by hugohaggmark** [comment]
Hi @szerwi and thank you for contributing. I don't really understand the use case for this? Could you elaborate more about where and why you need this?

**Comment by szerwi** [comment]
@hugohaggmark I'd like to change tab title that is displayed in browser and search engines.
I want to have it the same as dashboard name, without "Grafana" postfix.
![Bez tytułu](https://user-images.githubusercontent.com/19311511/65904404-ab600980-e3be-11e9-94b4-6f577e105a36.png)

**Comment by hugohaggmark** [comment]
Thanks @szerwi, I understand this but I asked you if you could describe the use case for this and how you think this brings value to Grafana?

**Comment by szerwi** [comment]
@hugohaggmark just to make it more personalized. Most people probably don't want or don't need Grafana postfix in the title.

The most difference is in search engines, title without postifx looks better.

**Comment by hugohaggmark** [comment]
@szerwi I don't think we'll support this in a near future, have you looked at [this](https://community.grafana.com/t/how-to-change-title-of-website-grafana/500/21)

**Comment by smyru** [comment]
I can imagine having the page title configurable, ie. a configurable page title for a dashboard view would default to: `$dashboard_name - $grafana`, but it would be possible to set it to be ie. `$organisation \ $folder \ $dashboard_name` or `$dashboard_name $time_range`

**Comment by n27051538** [comment]
I also need such setting for web page title as @smyru   wrote,  `$organisation \ $folder \ $dashboard_name`, is it possible to make this without building from sources?

**Comment by moskyb** [comment]
To chime in with another use case here: My team has separate Grafana instances for staging and production environments, so it'd be handy to be able to quickly distinguish between the two Grafanae in my tab bar - `$dashboard_name - Staging Grafana` and `$dashboard_name - Prod Grafana` would be pretty handy.

**Comment by szerwi** [comment]
Any new plans for implementing that feature? ;)

**Comment by hugohaggmark** [comment]
> Any new plans for implementing that feature?

As far as I know, there are no plans to implement this right now, but that could of course change and we still accept PR for this feature.
