### ISSUE TITLE
per-datacenter metric colors

### ISSUE THREAD

**Issue by dwatzke** [grafana/grafana#1948]
Hi, it would be nice if there was a possibility to automatically use different shades of the same color for metrics from servers in the same datacenter (please see the attached example - this is what I mean).

This could be implemented by creating something like a "groupColor" function to which you would pass some regular expression as an argument (such as "^(...)" to match the first three characters of the server name when used with the aliasByNode function) and each time it would match the same substring, the same color (with slightly modified brightness) would be used for that metric.

Unfortunately, I'm not able to implement this myself but it would be helpful if you could point me to the grafana code that decides which color is to be used for a metric so that I can check if I can come up with a quick 'n' dirty solution before somebody implements it properly (if ever).

Thanks!

![graph](https://cloud.githubusercontent.com/assets/15475/7487913/70c96376-f3c1-11e4-943f-44439b24f26a.png)

**Comment by torkelo** [comment]
Should be fixed when this issue is implemented https://github.com/grafana/grafana/issues/590
