### ISSUE TITLE
Support proxy protocol

### ISSUE THREAD

**Issue by cambierr** [grafana/grafana#19497]
**What would you like to be added**:

Support for proxy protocol

**Why is this needed**:

We run grafana behind a haproxy cluster doing SSL passthrough and because of this, we see our HA ips as client ips instead of actual user ones.

I know we could mess with local ssl terminations using nginx for instance, or event rewrite the source ip, but support of the proxy protocol would be much nicer and user-friendly.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
