### ISSUE TITLE
Docs feedback: auth/generic-oauth.md

### ISSUE THREAD

**Issue by Oechiih** [grafana/grafana#19495]
Hi guys

I've been setting up OAuth with Azure AD and I think the documentation should mention which API permissions the app regsitration used for authenticating needs. It needs the delegated permissions for the 'openid' scope.
![image](https://user-images.githubusercontent.com/10827844/65860367-732edb80-e36a-11e9-88e6-08c3ccadfc37.png)

Also I changed the scope in the configuration to just 'openid', removing 'email' and 'name'.

>Note : https://github.com/BlueGhostLabs/grafana-container-on-azure/pull/1

Cheers
Oechiih

**Comment by Oechiih** [comment]
Seems like there's an issue on my side.
https://twitter.com/stefanroth_net/status/1186988174784028673
Will investigate further.

**Comment by oddlittlebird** [comment]
What came of this investigation? 

If the docs need to change, feel free to file a PR.

**Comment by Oechiih** [comment]
Hi @oddlittlebird 
I'm sorry I haven't gotten around to check further yet.
Cheers
Oechiih

**Comment by achatterjee-grafana** [comment]
Hi @Oechiih and @oddlittlebird, this issue is over a year old. If we have not had any discussion on this, I am closing the issue. If you feel, there should be further investigation, we can re-open this or create a new issue. Let me know if you have objections. Thanks!!

**Comment by Oechiih** [comment]
Oh man, I'm sorry. I've actually rebuilt this about 4 months ago and apparently forgot to update this issue🤦🏼‍♂️.
It's all fine the documentation is absolutely correct mentioning "openid profile email" as the scopes.
