### ISSUE TITLE
aliasByMetric does not work with consolidateBy

### ISSUE THREAD

**Issue by gebi** [grafana/grafana#1949]
Hi,

If one want's to consolidateBy(max) and also want to have some nice looking legends one would normally use aliasByMetric, but it does not work together with consolidateBy in grafana.

eg.
Graphite query: `aliasByMetric(consolidateBy(collectd.$S.interface-eth0.if_octets.*, 'max'))`
produced labels: `rx, 'max')` and `tx, 'max')`
desired labels: `rx` and `tx`

Software used:
grafana 2.0.2
graphite-web 0.9.12+debian-7 (this debian version includes the maxdatapoints patch as backport from 0.9.13, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775783)

Screenshot:
![grafana_consolidate_by_lable_problem](https://cloud.githubusercontent.com/assets/659/7490826/22236686-f3e4-11e4-975b-77f6276ea6f4.png)

**Comment by torkelo** [comment]
This is graphite bug

**Comment by torkelo** [comment]
The bug is in aliasByMetric think it is fixed in graphite 0.9.13

**Comment by toni-moreno** [comment]
Hi @gebi.

if you use last graphite release, you will never get the metric name with aliasBy if you use consolidateBy(XXX) .

you will see  that instead:

![image](https://cloud.githubusercontent.com/assets/5883405/7492818/0cf20fde-f3fc-11e4-810f-0d69cde84a84.png)

The only way to remove the consolidateBy() name is with aliasSub() in that way.

![image](https://cloud.githubusercontent.com/assets/5883405/7492849/399ea74a-f3fc-11e4-84b8-49aa393dcf20.png)

Another way is merging a PR I did  myself some month ago , to configure each metric with its most suitable consolidation mode , and not accepte by @torkelo.

https://github.com/grafana/grafana/pull/931

![image](https://cloud.githubusercontent.com/assets/5883405/4623864/62f6a26e-5357-11e4-91f5-a0a3f056671c.png)

**Comment by gebi** [comment]
@torkelo thx for the quick answer!
you where right, it's already fixed upstream with https://github.com/graphite-project/graphite-web/pull/885, I opened a debian bugreport for this (https://bugs.debian.org/784441)

@toni-moreno with the above patch already applied to graphite-web and tested localy it works without problems. Proper labels through aliasByMetric which include consolidateBy(max).

![grafana_consolidate_by_lable_working](https://cloud.githubusercontent.com/assets/659/7502478/9a75e372-f43c-11e4-9923-4bfdaaeae9bb.png)
