### ISSUE TITLE
Alerting : Want to get alerted when their is a drop in between a mention range

### ISSUE THREAD

**Issue by sandysan2114** [grafana/grafana#19491]
HI, 

Am having difficulty to setup alerting for my graph,

Please find below example
![image](https://user-images.githubusercontent.com/55964612/65842808-5b396680-e32e-11e9-8efd-a669cfa58ff1.png)

So with regard to the above example ive pasted, i would like to get an alert when we have a small or big drop as you can see in the picture.

How will it be possible for me to setup the same alert.

Right now i can do a min and a max which will alert for example if the graph goes below 20 or above 190, but for those in between drops i dont know how i can setup same.

Thanks to help

**Comment by hugohaggmark** [comment]
Hi @sandysan2114, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
