### ISSUE TITLE
Series Override Custom Color Picker does not update text field.

### ISSUE THREAD

**Issue by CockatooV1** [grafana/grafana#19493]
What Grafana version are you using?
Grafana v6.4.0-beta2

What datasource are you using?
Graphite

What did you do?
Used the series override color picker palette on a graph panel to change the color of the lines. 

What was the expected result?
For the text input box to update to the selected color in the palette.

What happened instead?
the text box remains as "#000000"

![Screenshot from 2019-09-30 13-14-00](https://user-images.githubusercontent.com/54488456/65848648-68843e80-e38a-11e9-95fc-c55dae305549.png)

Others -
I've noticed that other color pickers do update this text field when a new color is selected in the palette.

**Comment by hugohaggmark** [comment]
Thank you @CockatooV1 for reporting this, we'll try to solve this before stable.
