### ISSUE TITLE
BUG: Status Panels not reflecting correct value for repeated panels with variable 

### ISSUE THREAD

**Issue by pratap-madhavan** [grafana/grafana#19490]
Please include this information:

What Grafana version are you using?
Grafana v6.2.0

What datasource are you using?
graphite

What did you do?
1. Created a New dashboard with Status Panel to display multiple Metrics from servers.
2. In query, Server names sourced via variable.
3. Created multiple Panels for different servers with repeat - horizontal and variable 

What was the expected result?
Should have multiple panels for the different servers, with distinct values and alerts

What happened instead?
None of the Panels showing the display value and display alert. All Green 

Others -
1. Changing variable in query to "server name" displays the metric alias, display alias (critical) and  display value (Red panels)
2. The query inspector response is pass and the data points show exceeded metric value.

**Comment by hugohaggmark** [comment]
Hi @pratap-madhavan, are you using this [plugin](https://grafana.com/grafana/plugins/vonage-status-panel)? If so this is an external plugin with it's own repo, could you please report this issue there?
Closing this issue for now as this seems to be an issue with an external plugin, we can reopen this issue if new information point to it.

**Comment by pratap-madhavan** [comment]
Thank you @hugohaggmark
