### ISSUE TITLE
Display the user' default organization on the top of org switcher list

### ISSUE THREAD

**Issue by tdabasinskas** [grafana/grafana#19494]
**What would you like to be added**:
A configuration flag, which would allow to display the `Main org.` (or `auto_assign_org_id`) on the top of the organization switcher list.

**Why is this needed**:
In large, multi-tenant Grafana setups, it's possible to have quite a few organizations. Having the default org. (`auto_assign_org_id`) on the top of the list would allow to make it more visible.

I can do a PR if the request makes sense.

**Comment by hugohaggmark** [comment]
Hi @tdabasinskas I've added this to our backlog.
Could be done as part of this #16824

**Comment by dprokop** [comment]
Closing this issue as it's already referenced in #16824 and that one is a more general request to rethink org switcher
