### ISSUE TITLE
Tracing: Other Tracer implementation than Jaeger

### ISSUE THREAD

**Issue by ledor473** [grafana/grafana#19492]
**What would you like to be added**:
I'm wondering how open would you be to have support for multiple tracer implementations and not only Jaeger.

**Why is this needed**:
Different users could want out-of-the-box support for other distributed tracing platform like LightStep, Honeycomb, DataDog, etc. And not only Jaeger.

**Possible implementation**:
It feels like the configuration file was build to support different tracing implementation because all Jaeger configuration exists under `tracing.jaeger`: https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L618-L637

Similarly to Envoy, support for different tracer could be bundled in the application and depending on the configuration, a single one would be used: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/trace/v2/trace.proto#config-trace-v2-tracing-http

**Alternative**:
The OpenCensus Service could be used to transform the Jaeger data generated by Grafana to something else, but it would require another moving part to make that work. 
It would be far from ideal from an end-user perspective (it's like if we would ask everyone to use [statsd_exporter](https://github.com/prometheus/statsd_exporter) instead of building direct support for Prometheus in Grafana), but considering the current transition from OpenTracing/OpenCensus to OpenTelemetry, it might make sense to wait.

**Comment by hugohaggmark** [comment]
Hi @ledor473, don't really know how far we've come with this. Maybe @davkal knows more about this?

**Comment by bergquist** [comment]
We support zipkin via the Jaeger client https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L634

**Comment by bergquist** [comment]
> but considering the current transition from OpenTracing/OpenCensus to OpenTelemetry, it might make sense to wait.

Yes ;)

Seems like there are multiple other options for getting jaeger traces into SAAS services.

https://lightstep.com/blog/now-playing-your-jaeger-traces-in-lightstep/
https://github.com/honeycombio/honeycomb-opentracing-proxy

**Comment by inigohu** [comment]
> but considering the current transition from OpenTracing/OpenCensus to OpenTelemetry, it might make sense to wait.

OpenTelemetry is already in beta. Is OpenTelemetry in the roadmap?

**Comment by aocenas** [comment]
Changing the labels as this is about how to use tracing to monitor Grafana itself not about viewing tracing data inside Grafana.

**Comment by alecxvs** [comment]
Since https://github.com/grafana/grafana/issues/41968 is a thing, but Jaeger specific, my suggestion would be to add support for other OpenTelemetry exporters, or at the very least OTLP. Most formats can be sent to an OpenTelemetry collector and exported to any other format (Jaeger, DataDog, etc.) but I assume OTLP would be the most 1:1. Plus any services that have OTLP support will also work directly without a collector (such as New Relic).

I don't know what the OpenTelemetry implementation is going to look like in Grafana but if it works like the OpenTelemetry collector, setting up other exporters is hopefully trivial.
