### ISSUE TITLE
Provisioning documentation default values

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#19501]
**What would you like to be added**:
Please add default field values used in provisioning configuration [documentation](https://grafana.com/docs/administration/provisioning/#example-datasource-config-file)

**Why is this needed**:
When configuring provisioning, instead of adding all fields to the required value, a user can omit some and rely on their default values.

**Comment by hugohaggmark** [comment]
Thank @cdalexndr for taking the time to create this issue!

**Comment by mattiasb** [comment]
For now, just pointing to where these defaults are set in the code base in this issue would be very useful!
