### ISSUE TITLE
Table bug - column is set to "current", but sometimes it displays max value

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#19500]
**What happened**:
Column is set to "current", but it displays max value after changing a time range.
![image](https://user-images.githubusercontent.com/1700286/65869166-8c438680-e382-11e9-830a-ea2dbc8c5936.png)
![image](https://user-images.githubusercontent.com/1700286/65869204-a8dfbe80-e382-11e9-9536-f56412d1c966.png)
![image](https://user-images.githubusercontent.com/1700286/65869250-bf861580-e382-11e9-8e4d-3c89a91a71a5.png)

**What you expected to happen**:
Current value can't be changed just because I change time range.
If current value is "14" (see shots above), It must be 14 with any range.

**How to reproduce it (as minimally and precisely as possible)**:
Create table with current value column and collect some data. 
After that, compare current value with different ranges.

**Environment**:
- Grafana version: Grafana v6.3.2 (commit: 4832460)
- Data source type & version: Zabbix Plugin 3.10.2
- OS Grafana is installed on:  Centos 7

**Comment by hugohaggmark** [comment]
@torkelo it seems like this might be a bug but could also be something I don't understand about the `current` aggregation. Before I start investigation maybe you can take a quick look?

**Comment by torkelo** [comment]
Current can of course change if you change time range (due to rollup or aggregation)

Check what zabbix returns using query inspector
