### ISSUE TITLE
Feature Request: Add minutes as duration unit

### ISSUE THREAD

**Issue by rootdev-cd** [grafana/grafana#1950]
I'm pulling cumulative job times from an HPC cluster where the time-scales can be in days, weeks or years.

Having seconds as the maximum selectable duration unit results in inconsistencies in the units displayed at the lower end - ie 300s instead of 5 minutes. Having minutes as a selectable unit would add some uniformity here.

**Comment by knep** [comment]
+1

**Comment by utkarshcmu** [comment]
@torkelo Why is this issue still open?
