### ISSUE TITLE
CloudWatch ec2_instance_attribute can't get LaunchTime: Metric request error

### ISSUE THREAD

**Issue by y-batsianouski** [grafana/grafana#19514]
**What happened**:
When I try to use template variable for CloudWatch with next query: `ec2_instance_attribute(eu-west-1, LaunchTime, { "tag:billing:component": [ "view-cache" ], "tag:billing:environment": [ "prod" ] })` I get error `Template variables could not be initialized: metric request error`

**What you expected to happen**:
I get LaunchTime of the instances

**How to reproduce it (as minimally and precisely as possible)**:
Just try to use `ec2_instance_attribute(eu-west-1, LaunchTime, { })` for variable query with CloudWatch datasource

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: CloudWatch
- OS Grafana is installed on: official docker image
- User OS & Browser: Ubuntu 19.04, Chrome
- Grafana plugins: -
- Others: -

**Comment by y-batsianouski** [comment]
![image](https://user-images.githubusercontent.com/26086873/65915789-cd688480-e3dc-11e9-93c4-205c03945409.png)

**Comment by hugohaggmark** [comment]
Thank you @y-batsianouski for taking the time to report this, we'll have a look at this!

**Comment by mudit1804** [comment]
@hugohaggmark Any update on this? I am also facing same issue.

**Comment by sunker** [comment]
Apparently this template variable function only handles attributes that has a return value of type string. LaunchTime is of type time.Time so it doesn't work. Should be that hard to implement. Hopefully we'll be able to get this into the next release, but I'm not sure yet.

**Comment by marefr** [comment]
Fixed by #20237
