### ISSUE TITLE
Playlist with alarm dependend rotation 

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#19522]
**What would you like to be added**:
The playlist rotation should be triggered by an dashboard alarm (additional option)
Only dashboards with alarms should be shown if an alarm occurs in one or more
dashboards of a playlist. Dashboards with no alarms in a playlist should be hidden.
If only one dashboard of a playlist has an alarm than only that dashboard should be shown
and the rotation stopps until the alarm has gone.

**Why is this needed**:
You have more focus on important dashboards in a playlist.

**Comment by hugohaggmark** [comment]
Hi @mhollstein and thank you for taking the time to create this request. I added this to our backlog and we'll see what we can do.

**Comment by foofoo-2** [comment]
Basically, we are having a similar issue/requirement here: we are currently displaying a single dashboard on a TV screen that summarise the state of all our "environments". It would be nice we we could use the "Playlist" feature to dynamically add/remove dashboards to the playlist based on the state of each environment, like for example:

* Everything green: only display the "Summary" dashboard
* Some issue on DEV environment: add the "Details DEV" dashboard to the playlist
* Recovery of DEV environment: remove the "Details DEV" dashboard from the playlist
* Some issue on DEV and INT environment: add the "Details DEV" and "Details INT" dashboard to the playlist
* And so on...

Thank you very much in advance for taking these requirements in account.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
