### ISSUE TITLE
BarGauge: Auto min / max based on data

### ISSUE THREAD

**Issue by sadoMasupilami** [grafana/grafana#19527]
**What would you like to be added**: Bar Gauges should dynamically decide the maximum if not set (curretnly 100 is default)

**Why is this needed**:
The scenario is using bar gauges to show the most common error in an error log (mysql). As 1h or 1y could be selected setting a static maximum does not work for this scenario.

**Comment by hugohaggmark** [comment]
Thanks for taking the time to create this feature request @sadoMasupilami. I added this to our backlog and we'll have a look.

**Comment by gabzim** [comment]
In the `table` graph, when you override a column to look like a gradient gauge, unless you set a `max`, you don't see any bars. Can we transport this fix somehow to that component as well?
