### ISSUE TITLE
Grafana 2.0.2 deb init.d false start error

### ISSUE THREAD

**Issue by abravorus** [grafana/grafana#1952]
Hello,

Grafana 2.0.2 was installed as deb package on debian wheezy.

When starting the server I see an error message:

 >service grafana-server start
 [FAIL] Starting Grafana Server: failed!

But actually server works

 >ps ax | grep graf
14846 ?        Sl     0:00 /usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana

and I can connect to it from browser, add data sources (graphite), create dashboards, add queries, see plots, etc.

I do not see any error messages in the grafana log file.

What could be the reason for the false error server start message - something wrong in configuration (I changed only a few parameters from defaults - http_addr, allow_org_create and reporting_enabled) or that's a bug?

Thanks,
Alexandr

**Comment by torkelo** [comment]
Not sure, no one else has reported this. Can you replicate it?

**Comment by torkelo** [comment]
Did a few tests, and failed to replicate this. not sure what could case it. Maybe something went wrong with checking the pid file & process. But cannot replicate on debian wheezy

**Comment by abravorus** [comment]
I will try to replicate it tomorrow and report the results.

Thanks!

**Comment by abravorus** [comment]
Good morning.

Failed to replicate that as well... After stoping the server and starting it again everything was correct:

> service grafana-server stop
[ ok ] Stopping Grafana Server:.
> service grafana-server start
[ ok ] Starting Grafana Server:.

My only guess that the problem was during the very first start of the grafana server because of creating user, sqlite database, etc and something was checked not in time.

In any case many thanks!
Question could be closed.

Alexandr
