### ISSUE TITLE
build issue using window 10.

### ISSUE THREAD

**Issue by ngjack2** [grafana/grafana#19521]
**What happened**: command run "go run build.go build" return error.
![image](https://user-images.githubusercontent.com/50260319/65947468-f6cff180-e46a-11e9-816e-72b4ec882f95.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: Repeat the same command, the same error appear. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: window 10
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @ngjack2 , could you try using go version 1.12.10 instead.

**Comment by ngjack2** [comment]
hi @hugohaggmark i able to solve this issue by **go get -u golang.org/x/xerrors**. Now it another problem rise up when i tried to **yarn install --pure-lockfile**. It seem due to python version, but the instruction mention the build able to support 3.7. The version i have is 3.7.4.
![image](https://user-images.githubusercontent.com/50260319/66027388-5e4e7580-e52d-11e9-96e8-01449455f320.png)

**Comment by hugohaggmark** [comment]
Could you kindly ask this in the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/) instead. I'll close this issue for now but we can always reopen it if needed.

All the best
