### ISSUE TITLE
Log Panel: Selecting Live doesn't trigger a preview.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19530]
**What happened**:

When you create a new log panel, set up the LogQL hit enter, you get a preview of the logs.
But when you activate Live options:

<img width="795" alt="loki log panel" src="https://user-images.githubusercontent.com/1053421/65966399-0715ab80-e42e-11e9-9d56-471ea717036d.png">

It doesn't open a tail directly, nothing changes. However if you hit `ENTER` in the query, the preview start tailing.

Moreover while it seems that if you uncheck `Live` it stops updating the UI, the websocket stays open and keeps sending data.

Now if you try to activate `Live` again, still nothing, but if you hit `ENTER` you get a websocket opening, but this time the UI doesn't refresh

**What you expected to happen**:

Switching from `Live`on to off should open/close the websocket and refresh the ui correctly.

**How to reproduce it (as minimally and precisely as possible)**:

1 - Create a new log panel with a LogQL query
2 - Activate `Live` nothing happens
3- Hit `ENTER` on the LogQL input text, the panel will start tailing.
4- Deactivate `Live` the panel stop updating the UI but the websocket is still open
5 - Retry 2 and 3, UI doesn't refresh anymore but keeps opening websocket connection.

**Environment**:
- Grafana version: Grafana v6.5.0-pre (ed03338)
- Data source type & version: Loki
- User OS & Browser: Chrome

/cc @davkal

**Comment by hugohaggmark** [comment]
Thank you @cyriltovena

**Comment by lijingmaybel** [comment]
my datasource is elasticsearch,when i use log panel,there is nothing.i want to know how to use log panel

**Comment by aocenas** [comment]
We got rid of live feature in dashboards so going to close this.
