### ISSUE TITLE
Parsing Error when loading Graphite Events

### ISSUE THREAD

**Issue by pazoozooCH** [grafana/grafana#1953]
I have events in Graphite that contain e-Mail addresses enclosed in <> in the data field (as they are used in Git logs for instance). When trying to load them in Grafana, an **Annotation error** is displayed and the event cannot be loaded. Example with **data=<abc@xyz.com>**:

* JSON Result from get_data: ```[{"data": "<abc@xyz.com>", "what": "test", "when": 1430945563.0, "id": 25, "tags": "master test"}]```
* Error on GUI: ```[$sanitize:badparse] The sanitizer was unable to parse the following block of html: http://errors.angularjs.org/1.3.4/$sanitize/badparse?p0=%3Cabc%40xyz.com%3E```

I've noticed that any text with a non-letter within the brackets will result in an error (like <a.>, <a,>, ...)

**Comment by torkelo** [comment]
Solved in Grafana 2.5/2.6
