### ISSUE TITLE
Loki Explore: Autocompletion for label values is not working when typing

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19534]
**What happened**:

When adding a label matcher, the label name is suggested but not the label value anymore see:

![Screen Recording 2019-10-01 at 10 12 02 AM (1)](https://user-images.githubusercontent.com/1053421/65970955-72af4700-e435-11e9-9dc1-cb7b2c391441.gif)

 

**What you expected to happen**:

Label value to be correctly suggested when typing. 

**How to reproduce it (as minimally and precisely as possible)**:

see video above.

**Environment**:
- Grafana version: Grafana version: Grafana v6.5.0-pre (ed03338)
- Data source type & version: Loki
- User OS & Browser: Chrome/MacOS

/cc @davkal

**Comment by hugohaggmark** [comment]
Thank you for reporting this @cyriltovena
