### ISSUE TITLE
Explore: Connect null/zero values.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19536]
**What would you like to be added**:

It would be great if we could allow the same options `Null Value: Connected/Zero` from graph panel into Explore metrics.

When I'm looking at this : 

![image](https://user-images.githubusercontent.com/1053421/65977534-1867b380-e440-11e9-8a25-fba1a3535e7b.png)

That is less interesting than:
![image](https://user-images.githubusercontent.com/1053421/65977732-76949680-e440-11e9-98e9-b38d9af54be4.png)

**Why is this needed**:

For better Explore visualization.

**Comment by hugohaggmark** [comment]
Thank you again @cyriltovena

**Comment by freeseacher** [comment]
up

**Comment by Elfo404** [comment]
We need to come up with a more generic and scalable solution to allow panels customization in Explore. cc. @grafana/observability-experience-squad

**Comment by gelicia** [comment]
The explore team would like to discuss this feature alongside many other similar type of features, so we are moving this to that discussion:  https://github.com/grafana/grafana/discussions/54158
