### ISSUE TITLE
Grafana 6.4/6.3 snapshot to raintank displays empty panels

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#19535]
**What happened**:
After upgrading to Grafana 6.4.0, I can no longer export snapshots to raintank. See one example: https://snapshot.raintank.io/dashboard/snapshot/m8UASph32CWB6KZAOPocSxyCYwy3j308?orgId=2

All the panels are there but all info is missing.

On grafana 6.1.6: https://snapshot.raintank.io/dashboard/snapshot/0y4pnjMjwraP7TCsEhoF14jgxGYOjGy7?orgId=2 (works)
On grafana 6.2.5: https://snapshot.raintank.io/dashboard/snapshot/qabKB1V765R8bCLp14MGGBmg5AalPsKF?orgId=2 (works)
On grafana 6.3.6: https://snapshot.raintank.io/dashboard/snapshot/FpbKcLYUljWLi6A1mUBIP24ayylTaSiX?orgId=2 (broken)
On grafana 6.4.0: https://snapshot.raintank.io/dashboard/snapshot/Ir7XlW1L3bv2uoswtLyIWDoBUYNGWUDw?orgId=2 (broken)

**What you expected to happen**:
6.4.0/6.3 can export dashboards like previous versions

**How to reproduce it (as minimally and precisely as possible)**:

I can reproduce it on my grafana deployment, not sure if this is universally broken though or if I have something weird in my dashboard? If any more info is needed I can upgrade and capture more info.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.x.x
- Data source type & version: Prometheus 
- OS Grafana is installed on: Kubernetes

**Comment by flopp999** [comment]
same as #18490 ?

**Comment by howardjohn** [comment]
Yes looks like it, thanks for the reference. Is the raintank snapshot generally not something that is considered high priority/well supported? Just curious if I should transition over to local snapshots?
