### ISSUE TITLE
Cloudwatch datasource : Sagemaker no datapoint 

### ISSUE THREAD

**Issue by cyrilbkr** [grafana/grafana#19538]
Hi, 

I m trying to use the Cloudwatch Datasource for catching Sagemaker metrics. 

The Cloudwatch datasource auto discover my endpoint name correctly, but i can't visualize any data points. 

Can you help me please ? I try with 2 differents versions of Grafana. 
Did i miss something ? 

<img width="1096" alt="toto" src="https://user-images.githubusercontent.com/31832102/65978997-e6bd0f80-e474-11e9-9239-e3ffbda0cb6b.png">

- Grafana version: 6.1.1 & 6.2.5
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Docker official img

**Comment by hugohaggmark** [comment]
Hi @cyrilbkr, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
