### ISSUE TITLE
Explore: List of logs not updating accordingly

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19540]
**What happened**:

When you have a query that returns logs such as `{job=~"prod/.*",level="error"}` but then switch to a query with no logs using a dump query like `{job=~"prod/.*",level="foo"}`, all logs from the previous query are still showing however the histogram and counts are showing latest values.

**What you expected to happen**:

Query with empty result should wipe the log list.

**How to reproduce it (as minimally and precisely as possible)**:

1 - Setup a query that returns result:  `{job=~"prod/.*",level="error"}`
2 - Switch to a dummy query `{job=~"prod/.*",level="foo"}`
3 - logs from the first query are still showing.

**Environment**:
- Grafana version: prod
- Data source type & version: Loki
- User OS & Browser: Chrome/MacOS

/cc @davkal @hugohaggmark

**Comment by aocenas** [comment]
I was able to reproduce it briefly but then it went away and right now I am unable to reproduce for some time. Not sure what the problem is but does not seem easy to simulate, either it was something really transient, or some edge case with some front end caching that goes away after reload and is not that easy to get again.

**Comment by davkal** [comment]
Can't repro either.

**Comment by cyriltovena** [comment]
I was able to reproduce this right now. Looks for logs that exist then use the arrow to move to another timeframe where those logs doesn't exists.

**Comment by cyriltovena** [comment]
Proof:

![image](https://user-images.githubusercontent.com/1053421/68881955-274ab280-06dc-11ea-99ec-cbf821473ed8.png)

**Comment by ivanahuckova** [comment]
Hi @cyriltovena, I was also trying to reproduce this bug (locally/in ops-tools/with slow network/with slow CPU/different browsers/filter expressions/using arrows for timeframe change/...), but I wasn't able to. Could you please confirm, that you can still reproduce this bug?  Thank you!

**Comment by cyriltovena** [comment]
Wasn't able to reproduce no.  Let's close I'll reopen if necessary.
