### ISSUE TITLE
More than one graph do not show Dynamic

### ISSUE THREAD

**Issue by mkdel** [grafana/grafana#19542]
**What happened**: when I select more that one graph to show it draw straight lines.

**What you expected to happen**: expect to see dynamic 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.4.0 (c3b3ad4)
- Data source type & version: Prometheus 2.12.0
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 7.7 (Maipo)
- User OS & Browser: any browser
- Grafana plugins: nothing additional
- Others:

this is good:
![image](https://user-images.githubusercontent.com/55700023/65985517-a8324f80-e48a-11e9-9569-575eb43d07e6.png)

When I press CTRL and choose another one to show - Bad straight thing :( no dynamics any more:
![image](https://user-images.githubusercontent.com/55700023/65985356-4245c800-e48a-11e9-8b7a-2e83e829342f.png)

Have I done something wrong?

**Comment by mkdel** [comment]
Also installed  on CentOS Linux release 7.6.1810 with the same result.  Grafana v6.3.3 (84d0a71)

**Comment by torkelo** [comment]
this is not a bug, the variation is super small in the first series, so when add the second series then it becomes a line when drawn using same scale.

**Comment by mkdel** [comment]
oh, silly me, thank you so much!
