### ISSUE TITLE
Docker: Add back curl to docker image

### ISSUE THREAD

**Issue by nightah** [grafana/grafana#19549]
**What happened**: Grafana 6.4.0 switched from a ubuntu base image to alpine now the curl package is missing.

**What you expected to happen**: curl to be present in the distributed docker image for Grafana.

**How to reproduce it (as minimally and precisely as possible)**: Install Grafana via docker, attempt to use curl within container.

**Anything else we need to know?**: I recall this occurring once before and being addressed via https://github.com/grafana/grafana/pull/13794.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: There's no notes of the change for the Docker image in the changelog.
I'll submit PR shortly which looks to add curl back into the docker image.

**Comment by DanCech** [comment]
Is there a reason you need curl in the image? Part of the reason behind moving to alpine was to reduce the size and attack surface of the image.  If you really need curl it's trivial to create a Dockerfile based on the official image with curl and any other utilities, plugins, etc added.

**Comment by nightah** [comment]
I understand it's trivial to do so, I would have thought that dropping it would have been socialised with issues and alternatives discussed.

It's used to provision data sources and dashboards in dockprom.

I tried swapping to the provisioning system instead of the old documented method with curl and found an issue, primarily with the fact that you cannot change any dashboard that's been provisioned as such via the Grafana dashboard.

If that's changed then I can change over too but I haven't seen anything to imply it has.

**Comment by nightah** [comment]
So the `wget` in alpine is the BusyBox variant not GNU, which means you cannot send a HTTP POST with this version, I'll look at what else can be achieved with what's in the base alpine image, I think BusyBox `nc` is available.

Having said that is curl really going to have that large of an impact from a size standpoint?
From the alpine packages page itself:
```
Size | 113.17 kB
Installed Size | 220 kB
```
Is 220kB really going to be an issue for a ~37-73MB container depending on the architecture?

I'm just hoping to understand if this is a hard stance from the team to not include the package back in the docker image?

**Comment by nightah** [comment]
Could we alternatively replace BusyBox `wget` wiith GNU `wget`?

```
Size | 215.21 kB
Installed Size | 464 kB
```

This will result with a larger image than if we just included `curl` though.
Not sure of the security implications considering BusyBox vs GNU `wget`

**Comment by marefr** [comment]
Thanks for the feedback. We've decided to build and publish an additional Ubuntu-based image for those having problems with using Alpine, see #20178. We should probably consider adding back curl in that one.

**Comment by nightah** [comment]
@marefr just to clarify, will only the Ubuntu-based image include curl?
So there is no plan to include it in the Alpine variant?

**Comment by marefr** [comment]
@nightah yeah that's the current idea

**Comment by nightah** [comment]
While this could still potentially be a problem for others and is due to be addressed by the Ubuntu based image, PR https://github.com/grafana/grafana/pull/19820 solves my problem and will allow me to utilise the provisioning system.
