### ISSUE TITLE
Automated decimal precision on graphs broken since 6.4.0

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#19541]
![afe2b6833bc4](https://user-images.githubusercontent.com/2349496/65979309-57fcc280-e475-11e9-825e-fc5868a87d38.png)

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: InfluxDB 1.7.8
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: Linux / Chrome
- Grafana plugins: standard plugins
- Others:

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by pacive** [comment]
I have a similar issue, but the other way around, seeing no decimals where there need to be.
![_20191007_073413](https://user-images.githubusercontent.com/30875102/66287198-0e790100-e8d5-11e9-85fc-04866f59c02c.JPG)
Decimals is set to auto, selected unit is "mbar". If I change to 3 decimals the values displayed in "bar" shows correct, but there are three zeroes added to the values in "mbar". 
(Grafana 6.4.1)

**Comment by torkelo** [comment]
Fixed in master and coming 6.4.2 patch
