### ISSUE TITLE
Custom time range text input can't parse millisecond durations

### ISSUE THREAD

**Issue by cody271** [grafana/grafana#19553]
`now-1s` works fine, but `now-100ms` isn't recognized as valid.

![grafana_ms_duration](https://user-images.githubusercontent.com/11763424/66018530-4d055a80-e494-11e9-9246-6eb1c1c699c0.png)

**Comment by hugohaggmark** [comment]
Hi @cody271 and thank you for creating this feature request, I'll add it to our backlog but this could be a big change so not sure if we're taking this on in any near future.
