### ISSUE TITLE
Feature request - Way to assign units to metrics based on template value

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#1955]
I am enjoying the functionality of #1888, great idea. :)  One thing I am noticing while repeating rows is it would be wonderful if I could repeat rows based off of a metric and keep the correct unit of seconds, bytes, percent.  This would allow users to select multiple metrics that would dynamically create rows of pools of servers that contains the proper metric assigned to the unit for investigation.

While looking at the json, possibly there could be extra meta-data within templating -> list -> [0] -> options.  Possibly in addition to 'text', 'value', 'selected', a 'unit' could be added. Or if desiring something more generic, an object that could override any setting if used within the graph, but that may be more complicated or too much work.  Mostly interested in unit in terms of #1888.

Thanks, change the title as desired, not sure of the best way to ask for a feature.

**Comment by torkelo** [comment]
The repeat functionally is meant to repeat the same data but from different sources.

**Comment by gerrickw** [comment]
Is there a work around for this behavior or someway I could get this working?  It doesn't necessarily need to apply to template variables, but possibly something within graphite/influxdb that grafana could reference to get the unit type.

Thanks for your help,
Gerrick W

**Comment by Corbyn** [comment]
Would it be possible to implement some kind of unit recognition, if the unit was provided as field value in a measurment?
For example the measurement "disk_usage" contains a field key "unit" that has always a string value of "GiB". Perhaps Grafana could compare the "unit"-field's value with the units known to Grafana and if it matches it could automatically apply it?
