### ISSUE TITLE
login.OAuthLogin(missing saved state) - Community version of grafana with OKTA integration 

### ISSUE THREAD

**Issue by goravsingal** [grafana/grafana#19556]
I’m trying to configure Community edition Grafana(official docker image:5.4.3) with Okta integration.

After doing Okta configuration, Okta authenticates and redirect request to grafana, where I hosted it, But, it shows following error:

login.OAuthLogin(missing saved state)
I’m not using any database for storing sessions. I want to save it on local file only.
In container, I can see sessions folder created: /var/lib/grafana/sessions/ and some files are created.

Few of the configurations I’m setting:
GF_AUTH_ANONYMOUS_ENABLED: “false”
GF_SERVER_ROOT_URL: “https://”
GF_AUTH_OAUTH_AUTO_LOGIN: “true”
GF_AUTH_GENERIC_OAUTH_NAME: “Okta”
GF_AUTH_GENERIC_OAUTH_ENABLED: “true”
GF_AUTH_GENERIC_OAUTH_SCOPES: “groups”
GF_AUTH_GENERIC_OAUTH_CLIENT_ID: “my_client_id”
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: “some_secret”
GF_AUTH_GENERIC_OAUTH_AUTH_URL: “url”
GF_AUTH_GENERIC_OAUTH_TOKEN_URL: “url”
GF_AUTH_GENERIC_OAUTH_API_URL: “url”
GF_SESSION_COOKIE_SECURE: “true”

Please suggest.

**Comment by hugohaggmark** [comment]
Hi @goravsingal, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
