### ISSUE TITLE
Ignore keys in $Filters

### ISSUE THREAD

**Issue by duylong** [grafana/grafana#19561]
Hi,

In Elasticsearch, we can to have 2 same fields with "type": "keyword" and "type": "text". Except that in $Filters, we have all the fields in the selection. Is it possible to add the possibility of ignoring some fields?

**Comment by torkelo** [comment]
not sure I understand, ignore how / where? Filters are optional you can remove them in ad hoc way (which is why they are called ad-hoc filters)

**Comment by torkelo** [comment]
ah, you want to filter out entries in the the dropdown

**Comment by duylong** [comment]
Sorry, I went quickly in the presentation. This is the entries in the dropdown ;) Currently I have duplicates, fields with the type "keywords" (raw values) and others with the type "text".
