### ISSUE TITLE
Singlestat $__name in postfix/prefix is not working anymore

### ISSUE THREAD

**Issue by atartareanu** [grafana/grafana#19567]
**What happened**: After upgrade from grafana 6.2.0 to 6.4.0 the $__name variable for prefix and postfix are not working anymore for the singlestat panel
I have verified with grafana 6.3.6 and this was still working.
**How to reproduce it (as minimally and precisely as possible)**: the panel will display $__name instead of the value

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: influxDB
- OS Grafana is installed on: Windows 2016
- User OS & Browser: Chrome

![image](https://user-images.githubusercontent.com/22320901/66037997-8d5aec00-e519-11e9-99fb-2a02aa8f6ede.png)

![image](https://user-images.githubusercontent.com/22320901/66038196-15d98c80-e51a-11e9-9194-c551f5660f2d.png)

Thank you.

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by torkelo** [comment]
If anyone wants to fix this: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L260 

that line should be:

 data.scopedVars['__name'] = { value: name }

**Comment by torkelo** [comment]
Needs to done in the next 12~ hours or so so can include it in tomorrows release :)
