### ISSUE TITLE
Mobile navigation isn't showing hover tooltip 

### ISSUE THREAD

**Issue by amilcarbra** [grafana/grafana#19560]
**What happened**: When navigating on a panel on a mobile device, the hover tooltip is hidden by a create annotation form whenever you click on a panel point with your fingers. It looks like a bug, because the tooltip is presented for less than a second before the modal annotation form takes place in the screen

**What you expected to happen**: In older grafana versions the annotation form was not presented. I prefer the old way, because the hoover tooltip is very important on mobile devices to better read the value of the point in analysis.

**How to reproduce it (as minimally and precisely as possible)**: just navigate to http://play.grafana.org using a mobile device (IOS or Android) and try to see a hover tooltip.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.5
- Data source type & version: influxdb
- OS Grafana is installed on: docker/hassio
- User OS & Browser: Google Chrome/IOS

**Comment by hugohaggmark** [comment]
Thanks for adding this @amilcarbra, added this to our backlog.

**Comment by amilcarbra** [comment]
Duplicate of #18519

**Comment by linar-jether** [comment]
Why is this closed? still broken as of 6.5

**Comment by hugohaggmark** [comment]
@linar-jether because it's a duplicate.

**Comment by linar-jether** [comment]
@hugohaggmark But it is not a duplicate, see the referenced issue, it's a cyclic reference. 
both issues reference each other, and both are closed...

**Comment by hugohaggmark** [comment]
@linar-jether #18519 is opened, is that ok?

**Comment by amilcarbra** [comment]
@hugohaggmark , any predictions on that? Tks!
