### ISSUE TITLE
[bug] local format problem

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#19564]
Please see the numbers on Legengs that not formatted to local format:

![image](https://user-images.githubusercontent.com/2911588/66033566-d3a74f80-e507-11e9-8633-c5530c6a994c.png)

(My local format is 1 000 000, HU/Hungary.)

It has a problem with formatting of numbers that less than 1 000 000.

The test query:

![image](https://user-images.githubusercontent.com/2911588/66033922-88417100-e508-11e9-9320-5ca48cd45403.png)

Setting of the Axis of Left y:

![image](https://user-images.githubusercontent.com/2911588/66033952-98f1e700-e508-11e9-950a-bffdb70ae990.png)

... and Legends:

![image](https://user-images.githubusercontent.com/2911588/66033969-a3ac7c00-e508-11e9-8638-9798702c6237.png)

Similar problem with Table:

![image](https://user-images.githubusercontent.com/2911588/66034097-d9e9fb80-e508-11e9-8f42-29f1b1293ee4.png)

Settings of the Table:

![image](https://user-images.githubusercontent.com/2911588/66034128-e8381780-e508-11e9-998b-316110110c2a.png)

**Comment by torkelo** [comment]
this is what the browser is is doing, the locale format is using browser built-in local formating

**Comment by sanchomuzax** [comment]
> this is what the browser is is doing, the locale format is using browser built-in local formating

I think you didn't watch the mistake. 😢 

The local format is indicated by Grafana if the digit is above 1 000 000. If it is less than 1 000 000, it will be corrupted and not show in local format.

Please don't close the task. This feature was good before Grafana 6.4.

**Comment by torkelo** [comment]
if you use locale unit grafana will always let browser format value, there is no limit, maybe the browser changed how it formats values?
