### ISSUE TITLE
Gauge: Data (from query) driven min, max & thresholds 

### ISSUE THREAD

**Issue by diegocanton** [grafana/grafana#19570]
**It would be very useful if we could control the Gauge "Min" and "Max" values through a query.

Imagine using a Query X with LimitThresholdMin alias and Query Y with LimitThresholdMax alias, now we use these variables in the Gauge Threshold "Min" and "Max" field making it dynamic.**:

**Utility example: We have a Dash that keeps the number of employees available for maintenance in different cities, when there is idleness in one city some employees are relocated to others, this process is very dynamic and lasts an average of 1 day, which makes management this complex and flawless Dash.

If we could set this value through a variable with a query in the datasource we would have more accurate with less rework, today we already have the number of employees available in the system table and when relocating it from one location to another this counter is incremented.

There may be situations similar to this where a limit cannot be set and would be solved with a function like this.**:

**Comment by ryantxu** [comment]
fixed in 6.6 (beta)
