### ISSUE TITLE
share query (Dashboard datasource) not working when rows exist in dashboard

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#19583]
**What happened**: After select "--dashboard--" as data source, instead of listing panels, it throw out error:
"Unable to find application file

Grafana has likely been updated. Please try reloading the page.

Reload
Details
TypeError: Cannot read property 'info' of undefined

    in t
    in div
    in r
    in l
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in div
    in e
    in DraggableCore
    in e
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in e
    in div
    in div
    in div
    in t
    in t
    in div
    in div
    in e
    in Connect(e)
    in Suspense
    in t
    in Unknown
    in d
    in Unknown
    in Unknown
    in t
    in t
    in a"

**What you expected to happen**: List panels in current dashboard

**How to reproduce it (as minimally and precisely as possible)**: See above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.0, 6.4.1
- Data source type & version:
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: MacOS Mojave/Chrome Version 77.0.3865.90
- Grafana plugins:
- Others:

**Comment by fyang13** [comment]
Update: This seems only happen to some dashboards

**Comment by torkelo** [comment]
strange, been unable to replicate. what data source is the panel you are trying to reuse query results from using?

**Comment by kcgthb** [comment]
I can confirm the same behavior.
The original data source for us is Graphite (set as default).

**Comment by Pedrat** [comment]
We're having the same problem, with the original data source being Influx
If we do recreate the panels from scratch there's no problem with it, only if we use the panels that were created in previous versions of Grafana

**Comment by Pedrat** [comment]
Update: Even on brand new panels, sometimes when you go to edit the panel that is reusing the results it gives the error

**Comment by Pedrat** [comment]
I think i got it, this error happens whenever i add a row and i try to edit the panel that is reusing the results (if i try to edit the one that is providing the results there is no problem at all)

So, steps to recreate this error:

1. Create a dashboard
2. Create a panel that queries the data source
3. Create a panel that reuses that results
4. Add a row to the dashboard
5. Try to edit the table that is reusing the results
6. Boom! Error

**Comment by BrunaDaniel** [comment]
I'm having the same problem, but I don't add a row to the dashboard. I'm using SQL Server. I added the database and when I try to add query to a dashboard or even when I click on Explore, I get the same error message.

**Comment by zimmertr** [comment]
Also happening to me.

**Comment by valentinrueeck** [comment]
Also happening on windows server 2012 r2 with grafana 6.4.2, while trying to create a new Dashboard, new Panel and add a Query to this Panel. Datasource is Prometheus

**Comment by juniorsaldanha** [comment]
This is also happening to me, there is something what could i do to solve this problem? im using grafana 6.4.3 on production Zabbix. Pls i need a solution.

**Comment by DefinitelyNotRoot** [comment]
I'm getting same error:
![obraz](https://user-images.githubusercontent.com/9088462/67861436-862afc00-fb20-11e9-9312-406002e84bc4.png)

**Comment by 0xliam** [comment]
Also getting a similar issue using a Microsoft SQL backend - only when we run certain queries using a combination of variables, and only appears when we click Query Inspector - not sure if this is related to this original issue so happy to open another if you think it is a bug.

I assume the way Grafana is handling the SQL query with templates isn't valid, but didn't expect it to crash.

OpenTSDB graphs seem to be unaffected.

Grafana v6.4.1 (4ba8388) running in Docker.

In Chrome console:
```
react-dom.production.min.js:198 TypeError: Cannot read property 'indexOf' of undefined
    at g (namedColorsPalette.ts:108)
    at e.getColorForValue (renderer.ts:148)
    at e.setColorState (renderer.ts:301)
    at Array.<anonymous> (renderer.ts:265)
    at e.formatColumnValue (renderer.ts:317)
    at e.renderCell (renderer.ts:321)
    at e.render (module.ts:38)
    at TablePanelEditor.tsx:3
    at s (TablePanelEditor.tsx:3)
    at u.<anonymous> (TablePanel.tsx:24)
```

Grafana error:

```
Unable to find application file

Grafana has likely been updated. Please try reloading the page.


TypeError: Cannot read property 'indexOf' of undefined

    in t
    in div
    in div
    in r
    in l
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in div
    in e
    in DraggableCore
    in e
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in e
    in div
    in div
    in div
    in t
    in t
    in div
    in div
    in e
    in Connect(e)
    in Suspense
    in t
    in Unknown
    in d
    in Unknown
    in Unknown
    in t
    in t
    in a
```

**Comment by xxsumsxx** [comment]
Just restart:

root@apliaciones4:/home/johan# sudo service grafana-server restart
 * Stopping Grafana Server                                                                                                                             [ OK ]
 * Starting Grafana Server

**Comment by LPIMS** [comment]
I installed Grafana 6.4 and was able to create datasource. got Database connection OK message when I tested DB connection. When I tried to create New dashbaord/Add query I get the following error- Any feedback would be appreciated...Thanks in advance..

![image](https://user-images.githubusercontent.com/58040787/69350634-e86eac80-0c47-11ea-8ccd-98bca602e9d0.png)

**Comment by DirkFries** [comment]
Had the same issue yesterday. In my case the Browser was unsupported (IE 11).
See https://github.com/grafana/grafana/issues/20518

**Comment by zimmertr** [comment]
>IE 11

You poor soul.
