### ISSUE TITLE
[Feature Request] - Add metrics for Grafana database interactions

### ISSUE THREAD

**Issue by azhiltsov** [grafana/grafana#19586]
**What would you like to be added**:
All interactions between grafana-server and underlying DB with dashboards, users, etc (MySQL, PostgreSQL, sqlite3) are currently not instrumented. In case If underlying storage is misbehaving (slow response, flapping connections, etc) or grafana is creating more connections due to spike of requests or some of them are being slow or locking by their nature, there is no way to detect and alert. 
Author of this request is aware of log_queries parameter, however for bigger installations metrics are preferred over a log parsing. 
**Why is this needed**:
Increase visibility on underlying DB behavior, be able to alert in certain situations.

**Comment by hugohaggmark** [comment]
Hi @azhiltsov thanks for creating this feature request, we already have a metrics endpoint that could maybe be extended to include this as well.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
