### ISSUE TITLE
Gigabits/sec and Terabits/sec have the same id

### ISSUE THREAD

**Issue by andreaslangnevyjel** [grafana/grafana#19593]
**One cannot select Gigabits/sec as axis unit**

It seams that Gigabits/sec and Terabits/sec have the same ID, therefore Gigabits/sec get mapped to Terabits/sec (very annoying).

A quick fix is to change the ID of terabits/sec from "Gbits" to "Tbits" (in public/build/app.317cab0c5862d6c99844.js)

**Environment**:
- Grafana version: 6.4.1
- User OS & Browser: Leap15.1, Chromium 77.0.3865.90
- Grafana plugins: none

**Comment by hugohaggmark** [comment]
Hi @andreaslangnevyjel, can you give us some more details by running the query inspector and pasting it here?

**Comment by hugohaggmark** [comment]
Also a way to reproduce this bug would be awesome!

**Comment by andreaslangnevyjel** [comment]
Reproducing the bug is quite easy (just select Gigabits/sec as axis unit, will change to Terabits/sec). I have created a pull request to fix this issue.

**Comment by hugohaggmark** [comment]
Thanks for creating the PR, we'll have a look!
