### ISSUE TITLE
grafana email sending via smtp not working

### ISSUE THREAD

**Issue by abhijaink** [grafana/grafana#19599]
Below are the configuration which I have done in my grafana but still it is not able to send the emails for alert notifications and for even forgotten passwords.

[smtp]
enabled = true
host = smtp.XXXX.ZZ:25
user = XXXX@XXXX.ZZ

;password =
;cert_file =
;key_file =
skip_verify = true
from_address = XXXX@XXXX.ZZ
from_name = XXXXXX

;ehlo_identity = dashboard.example.com

Below is the exception which we have received 

t=2019-10-03T14:46:36+0300 lvl=eror msg="Async sent email 0 succeed, not send emails: XXXXXX@XXX.XX err: dial tcp: i/o timeout" logger=notifications

It is not even showing my smtp ipaddress or server details in the error messages. I have read through couple of Grafana errors related to this issue but none of them were helpful. 

smtp server is working fine and accessible from the server as I am able to send the message via command line successfully

echo "This is the message body and contains the message" | mailx -v \
 -r "xxxxxx@xxxxx" \
 -s "Test subject" \
 -S smtp="smtp.XXX.ZZ:25" \
 -S ssl-verify=ignore \
 XXXX@xx.zz

**Comment by kylebrandt** [comment]
What version of Grafana are you using?

**Comment by abhijaink** [comment]
We are using v5.3.2

**Comment by abhijaink** [comment]
@kylebrandt I am using v5.3.2

**Comment by kylebrandt** [comment]
Is this an existing install, and email used to work and stopped working? Or is this a new setup? 

If it is new setup, would you be able to try a more recent version?

**Comment by abhijaink** [comment]
I did the setup last December and forgot to check the email functionality thing as were in process of migrating our dashboards to this new version. All my dashboards are working over here. 

It will take some time for me to get it upgraded but I tried to check the debug logs as well but it wasn't much helpful.... can this be somehow fixed ?

**Comment by abhijaink** [comment]
@kylebrandt 
I did the setup last December and forgot to check the email functionality thing as were in process of migrating our dashboards to this new version. All my dashboards are working over here.

It will take some time for me to get it upgraded but I tried to check the debug logs as well but it wasn't much helpful.... can this be somehow fixed ?

**Comment by abhijaink** [comment]
is it possible that it can be an issue because of my nat redirect in iptables like below :
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http redir ports 3000
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 3000

**Comment by kylebrandt** [comment]
I don't see why those would impact outbound emails. Any chance to capture a tcpdump maybe from Grafana host, or logs for your mail server to see if it even sees an attempt from Grafana?

**Comment by kylebrandt** [comment]
Reference issue that may be related: https://github.com/grafana/grafana/issues/13358

**Comment by 3811015** [comment]
I ran into the same problem.

Remove the Port from ```instance_name = "IP:Port"```

What happened in the Background sending SMTP, you can easily see it by tcpdumping it:

```
EHLO IP:Port
```

This resultet in an io-timeout. Why? IP:Port ist interpreted as Hostname. He could not resolve this akward hostname within 2 sec, so timeout.

I'd strongly suggest not using ```instance_name``` in the SMTP.

**Comment by amit10may** [comment]
I am facing same issue with grafana v7.2.1 (72a6c64532)
