### ISSUE TITLE
Explore: Move context from each target to DataQueryRequest level instead

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#19598]
**Why need this**
Right now we add `context` to all targets in Explore for Prometheus queries 
https://github.com/grafana/grafana/blob/dafc955338aef05af259ec361bbf1ac29454ec3a/public/app/plugins/datasource/prometheus/components/PromQueryField.tsx#L232
so that the Prometheus datasource can determine if the target is called from Explore or a Panel.
https://github.com/grafana/grafana/blob/dafc955338aef05af259ec361bbf1ac29454ec3a/public/app/plugins/datasource/prometheus/datasource.ts#L189

Torkel has suggested we move it from the `target` level to the `DataQueryRequest` level instead to simplify the code.

See discussion here: https://github.com/grafana/grafana/pull/19597#pullrequestreview-296815073

**Comment by 97amarnathk** [comment]
Hey, Can I work on this issue?
