### ISSUE TITLE
Docs: Add Markdown style guide

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#19592]
**What would you like to be added**:

A style guide for Markdown content. Here are some things I think would be helpful to start with:

# Markdown style guide

## Styling

- To make text **bold**, use double asterisks, e.g. `**Bold**`.
- To _emphasize_ text, use single underscores, e.g. `_Emphasized_`.
- Punctuation should follow the same styling as the text, e.g. `**TODO:**`, not `**TODO**:`.

### Numbered lists

To avoid inconsistent list numbering, use _lazy list numbering_:

```
1. First
1. Second
1. Third
```

The list above will display as:

```
1. First
2. Second
3. Third
```

**Why is this needed**:

To make documentation and READMEs more consistent and maintainable.

**Comment by marcusolsson** [comment]
## Formatting

- Don't hard wrap lines
- Headings must be followed by a blank line, e.g.

```
## Heading

Some text
```

not

```
## Heading
Some text
```

**Comment by RobinJoe** [comment]
Hi @marcusolsson I'm interested in taking on this issue, and building up a guide. I expect it will take a few commits to close the issue, with room to invite other doc writers in. 

I will set up the Markdown Style Guide alongside the other style guides located here --> https://github.com/grafana/grafana/tree/master/contribute/style-guides

**Comment by oddlittlebird** [comment]
@RobinJoe , are you still working on this, or can someone else take over?

**Comment by RobinJoe** [comment]
@oddlittlebird, sorry for the delay, I have included a PR, I think it needs a rebase after review.
