### ISSUE TITLE
Templated timeshift

### ISSUE THREAD

**Issue by danievanzyl** [grafana/grafana#1960]
Version: 2.0.2
I'm trying to use a template variable with timeshifting and it won't allow the variable name in the input box. Is the expected behaviour?

**Comment by torkelo** [comment]
yea, that is not something that is support in current version. It has to be implemented first.

**Comment by digrich** [comment]
This will be a good feature to have. It will help us to compare the current data series with the historical series.

+1

@torkelo : Do you have any priority for this?

**Comment by pbooth** [comment]
Ahg - I was hoping for this one too. Also, in a related vein - any plans for templated percentiles, so that a chart could show, say, 50%,90%,99% values that are multiselectable?

**Comment by pbooth** [comment]
And another - have the ability to define repeate dpanels where each takes a different value of an inteval varable used for the "group by" clause of an influxdb query, so that we can show the dramatic impact of choosing the right bucketing size.

**Comment by danievanzyl** [comment]
any update on this request?

**Comment by gtonello** [comment]
+1 to this feature.

**Comment by bergquist** [comment]
closed by #4063
