### ISSUE TITLE
Query inspector stuck waiting to show results after update to newest version

### ISSUE THREAD

**Issue by Jekkyll** [grafana/grafana#19604]
This was just closed and I don't know how to respond to that particular request but I've already spoke with the vendor and they mentioned they are unable to help with anything which is why I went this route. I see a similar post from April (https://github.com/grafana/grafana/issues/16512) claiming it was fixed but its still breaking. You mention you have no other reports so maybe this is the first? Is there anything from the image that stands out? If you have other recommendations on where to go for assistance outside of the vendor then I'm more than happy to go there.

What happened:
I updated to the newest Adrem Netcrunch version (10.7.0.4785) and all our graphs broke in Grafana. It sits and spins on the Query inspector. I then thought since we were far behind in our Grafana version I would update that to 6.3.6 (newest version). The problem still persisted afterwards.

I am very new when it comes to Grafana so I'm not sure why it no longer pulls data when the data source shows that it is connecting successfully to our netcrunch database.

![image](https://user-images.githubusercontent.com/56122797/66136413-0b260280-e5c1-11e9-8d55-7c083bc16266.png)

Environment:

Grafana version: 6.3.6
Data source type & version:
OS Grafana is installed on: Windows 2012 R2
User OS & Browser:
Grafana plugins:
Others:

**Comment by hugohaggmark** [comment]
@Jekkyll could you look in the network tab and see what kind of response you get?

**Comment by torkelo** [comment]
I think you need to reach out to Adrem netrcunch for this, we have no other report on failed data sources in 6.3
