### ISSUE TITLE
'From date' different in json file.

### ISSUE THREAD

**Issue by onicniepytaj** [grafana/grafana#19606]
**What happened**: I have date table which contains just days in format YYYY-MM-DD. I want to use `$__timeFilter(date)` and adjust to this month only. If I pick date from to be 2019-10-01 00:00:00 here's what I have in json: 2019-09-30T23:00:00.000Z. Because of that it returns all events from last day of previous month. Similar analogy when I set it up to This Month So Far, which I need to use

**What you expected to happen**: Instead of 2019-09-30T23:00:00.000Z in Json I'd like to see 2019-10-01T00:00:00.000Z to mach the time filter.

**How to reproduce it (as minimally and precisely as possible)**: See in here: [play.grafana](https://play.grafana.org/d/000000012/grafana-play-home?editview=dashboard_json&orgId=1&from=1569884400000&to=1572566399000)

**Anything else we need to know?**: **To** date is alright. It's exactly the same as I set it up in the filter.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: PostgreSQL 9.5
- OS Grafana is installed on: Ubuntu 14.04.4
- User OS & Browser: Debian GNU/Linux 9.11 (stretch) | Opera
- Grafana plugins: table
- Others:

**Comment by hugohaggmark** [comment]
@onicniepytaj which timezone are you using `browser`or `utc`, because that would explain the diff.
