### ISSUE TITLE
Elasticsearch query "and" is case sensitive

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#19605]
**What happened**:
Joining multiple conditions in query with **and** keyword not working if **and** is lowercase.

**What you expected to happen**:
I was expecting **and** keyword to be case insensitive.

**How to reproduce it (as minimally and precisely as possible)**:
Tje the following query
`service.type:docker and docker.container.labels.app:web`
gives the same results as this query:
`service.type:docker`
Changing **and** to **AND**, resolves this issue:
`service.type:docker AND docker.container.labels.app:web`

**Anything else we need to know?**:
Using this query with lowercase **and** in Kibana gives the correct results.

**Environment**:
- Grafana version: v6.3.6 (commit: fdd2117)
- Data source type & version: elasticsearch 7.0+
- OS Grafana is installed on: docker image grafana/grafana
- User OS & Browser: win10, 69.0.1 (64-bit
- Grafana plugins: default
- Others: -

**Comment by torkelo** [comment]
this is handled by Elasticsearch's Lucene parser and is not something Grafana handles

**Comment by cdalexndr** [comment]
Kibana (competitor with Grafan) doesn't have this issue.
This is troubling because it silently ignores query parts, leading to invalid results.

Grafana could pre-parse the query to fix it, or inspire from Kibana code how they do it.
I can think of a possible workaround using a regex to make operators upercase.

**Comment by vertebarbe** [comment]
Hello, I encountered this problem recently. I think there should be a mention about this behavior in the documentation here: https://grafana.com/docs/grafana/latest/datasources/elasticsearch/query-editor/

I'm sure many would copy the queries straight out of Kibana, or are used writing queries like this... This probably resulted in many broken panels already.
