### ISSUE TITLE
Query inspector stuck waiting to show results after update to newest version

### ISSUE THREAD

**Issue by Jekkyll** [grafana/grafana#19603]
**What happened**:
I updated to the newest Adrem Netcrunch version (10.7.0.4785) and all our graphs broke in Grafana. It sits and spins on the Query inspector. I then thought since we were far behind in our Grafana version I would update that to 6.3.6 (newest version). The problem still persisted afterwards.

I am very new when it comes to Grafana so I'm not sure why it no longer pulls data when the data source shows that it is connecting successfully to our netcrunch database.

![image](https://user-images.githubusercontent.com/56122797/66135471-a1592900-e5bf-11e9-8167-0d0811e6fb3d.png)

**Environment**:
- Grafana version: 6.3.6
- Data source type & version:
- OS Grafana is installed on: Windows 2012 R2
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Think you need to contact Netcrunch and have them investigate it, we have no other reports of breaking data source plugins in v6.3
