### ISSUE TITLE
Graphite: Add graphite functions: changed, invert

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#1961]
Any plans to add missing graphite functions such as changed, invert, etc?

**Comment by torkelo** [comment]
no, but super easy to add :)

**Comment by druchoo** [comment]
If possible, please add all functions from graphite-web (0.9.13)/graphite-api that work with Grafana.

**Comment by torkelo** [comment]
Will not add invert, only in available in graphite master (not in 0.9.13), have no way to only show functions that are supported, so do not want to add unreleased functions. The error you get from graphtie when using functions that do not exist is also generic so no good way to show what is wrong to the user.

**Comment by druchoo** [comment]
@torkelo I understand your logic but would like to note some things.

* 0.9.13 is referenced on http://docs.grafana.org/installation/performance/. Therefore, I was under the impression that .13 was the preferred version to use with Grafana.

* graphite-api also provides functions only available in 0.9.13. Although, I must admit, I do not know if it is provided in latest stable version or dev.

* You note there is no way to only show supported functions. Perhaps, add an option in "Data Sources" to specify graphite-web/api version and use that to show certain functions? Or do some auto detect. Or provide a method of enabling certain functions via a setting/option.

In any case thanks for the getting back to me and adding the other functions to 2.1 milestone.

**Comment by torkelo** [comment]
True, a version property when you add the data source is a great idea. Yea 0.9.13 is preferred, but the invert function was not in that release

**Comment by druchoo** [comment]
Oops didn't realize https://graphite.readthedocs.org/en/latest/functions.html#module-graphite.render.functions wasn't for 0.9.13.
