### ISSUE TITLE
Expand Alerts

### ISSUE THREAD

**Issue by SelComputas** [grafana/grafana#19622]
**What would you like to be added**:
I would like to see functionality allowing me to set up an alert for the Diagram plugin visualization (https://grafana.com/grafana/plugins/jdbranham-diagram-panel). As I understand the UI it is only possible to set up an alert for the Graph visualization, because that is the only visualization in which the Alert button is present in the side menu.

**Why is this needed**:
This is needed because Alerts are relevant for all types of visualization, in my case the Diagram plugin, not just the Graph visualization.

**Comment by hugohaggmark** [comment]
@SelComputas I think in some near future the Alerts will not be tied to a specific visualization and we're working on that already so I'm gonna close this for now.
