### ISSUE TITLE
Pressing ctrl+l functionality

### ISSUE THREAD

**Issue by cristizafiu** [grafana/grafana#1962]
Hello

In grafana frontend pressing ctrl + l doesn't take you to the address bar like for other websites. Is there another feature implemented for this key combination? If so: Which? If not: Could you please fix this for the next release.

Thanks

**Comment by torkelo** [comment]
there is no keyboard shortcut for this but seems like the keybindings that do exist cause this. Will try find time to investigate this

**Comment by cristizafiu** [comment]
I've found this piece of code in the keybindings.js file:
keyboardManager.bind('ctrl+l', function() {
        scope.$broadcast('toggle-all-legends');
      }, { inputDisabled: true });

So it seems there is an action associated to ctr+l combination. Fixed it by using a custom directive that unbinds this key combination from the keyboard manager:
directive('addressBar', function(keyboardManager) {        
            return function (scope, element, attrs) {
                element.bind("keydown keyup", function (event) {
                    if(event.which === 76) {
                        keyboardManager.unbind('ctrl+l');
                    }
                });
            };
        });
