### ISSUE TITLE
[Broken] Annotation popin un graph view not fully displayed.

### ISSUE THREAD

**Issue by guillaume-u** [grafana/grafana#19631]
**What happened**:
Graph module in version >= grafana-bin-6.3.4 (and maybe prior - but I can't test) is displaying annotation popin (on click) in right even if there is not enough space to see it on the right (see attached picture) 

**What you expected to happen**:
The popin should be displayed at the left when there is not enough space to display it on the right.
 
**How to reproduce it (as minimally and precisely as possible)**:
On Graph plugin, click on the right of the line.

**Anything else we need to know?**:
Same thing happens on phone view.

**Environment**:
- Grafana version: grafana-bin-6.3.6
- Data source type & version: influxdb
- OS Grafana is installed on: Linux Gentoo
- User OS & Browser: Firefox on Linux / Firefox/Chrome browsers on android
- Grafana plugins: Graphs
- Others:

**Screenshot**:
![image](https://user-images.githubusercontent.com/469104/66228547-40207b00-e6cf-11e9-9819-90bbfd473cc2.png)

**Comment by torkelo** [comment]
to fix this we need to take viewport into account here: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/ContextMenu/WithContextMenu.tsx#L18

**Comment by krvajal** [comment]
I am gonna give it a try tomorrow morning.

**Comment by krvajal** [comment]
Quick update. I managed to get a dev environment up and running very quickly. And I was also able to reproduce the bug.
