### ISSUE TITLE
More configurable alerting on "no data"

### ISSUE THREAD

**Issue by bljordan** [grafana/grafana#19632]
**What would you like to be added**:
Currently, alerts immediately trigger on "no data" and do not respect the "For" field (https://grafana.com/docs/alerting/rules/#for). What is the rationale for this behavior?

The feature request is for Grafana to be able to respect the "For" field and be able to delay the alert. Even better, have a separate "For" field just for "no data" situations.

**Why is this needed**:
We are using Thanos to roll up metrics from many clusters running their own Prometheus instance. All metrics and alerts are off of the Thanos data source. Intermittently, we are seeing Grafana alert on "no data", but shortly after resolve on its own and the data is actually present for that time period.

**Comment by kylebrandt** [comment]
Duplicate (FOR for no_data (same time or different) has some state complications): https://github.com/grafana/grafana/issues/18215
