### ISSUE TITLE
Grafana 5 No data point visualization 

### ISSUE THREAD

**Issue by raphaeljuwe** [grafana/grafana#19643]
Environmemt : Linux Ubuntu

Grafana version : 5

I selected  AWS cloudwatch as my data source. 

I cannot read any data point.

Had read : https://github.com/grafana/grafana/pull/9856

https://github.com/grafana/grafana/issues/9852

Issue still persist

and

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
