### ISSUE TITLE
Azure Monitor Data Source should support Managed Service Identity when running on Azure

### ISSUE THREAD

**Issue by cschertz** [grafana/grafana#19641]
**What would you like to be added**:
Azure Monitor Data Source should support Managed Service Identity when running on Azure
**Why is this needed**:
Means that Azure users dont have to deal with SP cred management.   Leads to a more secure product

**Comment by kyschouv** [comment]
Any idea if/when this might happen? It'd be very helpful in our setups.

**Comment by joshhunt** [comment]
Azure Monitor now supports managed identity since Grafana 8.0! See [Configuring Managed Identity](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#configuring-using-managed-identity) for more details.
