### ISSUE TITLE
Singlestat: Treat no data data as null so it can be mapped to text (regression in v6.4)

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#19645]
**What happened**:
After update to version 6.4.1, when there is no data in database in selected time range, singlestat panel shows "No Data" instead of applying value mappings settings
![1](https://user-images.githubusercontent.com/19311511/66269899-66b8f000-e84e-11e9-900b-f9ff31060b62.jpg)

![2](https://user-images.githubusercontent.com/19311511/66269901-69b3e080-e84e-11e9-828c-ceea9aa35ffb.jpg)

**What you expected to happen**:
It should use value mapping. It should convert "null" to "-" text.

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Influxdb 1.6.4
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: -
- Others: -

**Comment by szerwi** [comment]
@torkelo I saw in the latest update that you have solved the issue, but unfortunately it is still not working for me. I still have "No Data" in singlestat panel.

**Comment by darioef** [comment]
It's not working here too. Today's upgrade didn't solve the issue. Still having "No Data" in Singlestats with null result queries.
