### ISSUE TITLE
ConstantLine(0) function only draws the line half way across the graph

### ISSUE THREAD

**Issue by paulatskoutdotcom** [grafana/grafana#1964]
Grafana version: 2.0.2  

ConstantLine(0) only draws half way across the graph.   Draws the line all the way in graphite composer.  See attached. 
![screen shot 2015-05-07 at 12 01 54 pm](https://cloud.githubusercontent.com/assets/7470648/7523531/30e57f92-f4b1-11e4-8999-933297da6a74.png)
![screen shot 2015-05-07 at 12 03 55 pm](https://cloud.githubusercontent.com/assets/7470648/7523538/3654a6b0-f4b1-11e4-9ad9-bfb8c5301095.png)

**Comment by torkelo** [comment]
strange, can you show me the response from graphite? it probably does not return data points for the complete line, not sure constantLine is fully supported by the json rendering. You can use a threshold line instead (configured in grafana axes and grid tab)
