### ISSUE TITLE
Singlestat panel value is shown over tool tooltips

### ISSUE THREAD

**Issue by ulikl** [grafana/grafana#19655]
**What happened**:

When SingleStat value is displayed alone (no gauge), it has a z-index of 1.
So this will be always shown on top. This should not be the case:

For example see
https://github.com/grafana/grafana-polystat-panel/issues/61#issuecomment-526222631 

**What you expected to happen**:

That tooltips can be fully seen over the single stat value.

**How to reproduce it (as minimally and precisely as possible)**:

See https://github.com/grafana/grafana-polystat-panel/issues/61#issuecomment-526222631  

**Anything else we need to know?**:
- 

**Environment**:

    Grafana version: 6.2.2

    Data source type & version:
    reproduced with Prometheus and InfluxDB (preinstalled plugin from Grafana version )

    OS Grafana is installed on:
    Grafana docker image grafana/grafana:6.2.2

    User OS & Browser:
    Firefox 67.0.1
    Windows 10

    Grafana plugins:
    Polystat 1.0.16
    SingleStat preinstalled from grafana 6.2.2 (no version number shown)

    Others:
    None.

**Comment by torkelo** [comment]
think this is fixed in v6.3, if not it might have to be fixed in polystat
