### ISSUE TITLE
RPM init script leaves stderr open

### ISSUE THREAD

**Issue by benheilman** [grafana/grafana#1965]
https://github.com/grafana/grafana/blob/master/packaging/rpm/init.d/grafana-server#L85

use of nohup creates a "nohup: redirecting stderr to stdout" message that in turn leaves stderr open.  This is a problem when restarting the service with something like saltstack

**Comment by torkelo** [comment]
ok, do you know a way to fix it?

**Comment by benheilman** [comment]
One way is to add 2> /dev/null after the su.  It doesn't make me feel good, but...
Ideally, to Linux admin in me, the grafana-server could detach itself.

**Comment by benheilman** [comment]
ex: https://github.com/grafana/grafana/pull/1967

**Comment by torkelo** [comment]
yea, the reason that the grafana-server doesnt support a proper background daemon mode, is because it isnt supported/easy to do in Go yet.
