### ISSUE TITLE
1.9.1 :  "Combine" shows  functions that are not available in the graphite web app render functions module.

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#1966]
I'm running Graphite web app 0.9.12 which does not have the "reduceSeries" function, however Grafana shows that function as available and applicable. Of course Grafana gets an error from Graphite if that function is applied.
I'm moving to 2.0 within the next 2 weeks so I'll test again at that time.

**Comment by torkelo** [comment]
is this a big problem? Just dont use the functions :) There is no api yet to get the current functions from graphite

**Comment by jaimegago** [comment]
@torkelo I don't know about "big" but it is *definitively* a problem from an end user perspective, so I wouldn't close this. Took me a little of digging to find out the reduceSeries and mapSeries functions were not available in the Graphite we run and I have full access (meaning I looked at the functions module code). Something needs to be done upstream to protect Grafana users that can't access graphite web app code from wasting time trying to find out why function foo is not working for them. It's just not acceptable to tell "my" Grafana user "don't use function foo,bar and baz even if you see and can select them". I'm fine doing the work to hide the ones that are not available until there is an API and it's prolly what I'll end up doing "by hand". IMHO until there is an API it would make sense to have the Graphite functions exposed in Grafana as configuration values, thus I'll open an issue for that.
