### ISSUE TITLE
Move go plugin sdk code into Grafana Repository

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#19666]
**What would you like to be added**:

Move the https://github.com/grafana/grafana-plugin-sdk-go repo into this code base.

**Why is this needed**:

 - We need to investigate whether we can use a separate go module for the plugin sdk code
 - Need to decide if this is versioned with, our independently of Grafana's version.

To fill out: @marefr / @marcusolsson

**Comment by marefr** [comment]
Decided to keep the sdk in separate repo for now due to go modules problems.
