### ISSUE TITLE
Graph random stacking order

### ISSUE THREAD

**Issue by TimoL** [grafana/grafana#19665]
**What happened**:
* Updated Grafana 6.3.1 to 6.4.1
* stacked values in graph started to have random order on each dashboard reload

**What you expected to happen**:
* stacked values are always rendered in the same (bottom to top) order

**How to reproduce it (as minimally and precisely as possible)**:
* Have a graph with 2 values (Prometheus queries in my case)
* enable stacking of values
* reload dashboard several times

**Anything else we need to know?**:
* Seems to be the same issue as described here: https://community.grafana.com/t/stack-order-lost-between-5-0-and-6-4/21669
* rollback to 6.3.5 seems to fix it, so I assume it was introduced in the 6.4.x release

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Prometheus, included in Grafana docker image
- OS Grafana is installed on: Linux host, upstream Grafana docker image, running in OpenShift
- User OS & Browser: OSX, Chrome
- Grafana plugins: default from grafana docker image
- Others:

**Comment by arcenik** [comment]
I have the same problem with Grafana 6.4.1.
For example, on a graph displaying node memory metrics, the order of the metrics is not reflected on the graph.
The make the graph difficult to read as metrics colors and order are changing and cannot be fixed.

**Comment by torkelo** [comment]
Fixed in master (reported a couple of times now), fixed in tomorrows 6.4.2 patch, https://github.com/grafana/grafana/pull/19597

**Comment by TimoL** [comment]
thx @torkelo
