### ISSUE TITLE
Docker container built with fast build on linux/amd64 cannot be ran because of a libc6/GLIBC version.

### ISSUE THREAD

**Issue by Estrax** [grafana/grafana#19671]
**What happened**:

Docker container built with fast build on linux/amd64 cannot be ran because of a libc6/GLIBC version. Reproduced on Debian 9 (libc2.24), Ubuntu 18.04 (libc 2.27), Ubuntu 19.04 (libc6 2.29).

```
> docker run --rm -p 3000:3000 grafana/grafana:dev
grafana-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by grafana-server)
```

**What you expected to happen**:

Docker container after build can be ran with no issues.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use a fresh install of Ubuntu 18.04 or 19.04 (or actually anything different than Debian 10 or Ubuntu 18.10).
2. Set up your OS for grafana development.
3. Build the frontend with `go run build.go build-frontend`.
4. Build the docker image with `make build-docker-dev`.
5. Run `docker run --rm -p 3000:3000 grafana/grafana:dev`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.1
- OS Grafana is installed on: Ubuntu 19.04 (linux/amd64), Ubuntu 18.04 (linux/amd64)

**Comment by antiquechrono** [comment]
This means that the container that built the grafana-server executable compiled it against libc 2.28 and the container that's trying to run it has a lower version installed. 

Get into your broken container with the following
* docker run -it --rm --entrypoint="/bin/bash" your_container_name

Then run this and you should see which libc version is installed
* ls /lib/x86_64-linux-gnu/ | grep libc

I'm betting you are going to see 2.27 there whereas you need 2.28. You can either figure out how to upgrade libc or switch out the alpine container with one that already has 2.28 installed.

**Comment by marefr** [comment]
This issue haven't had a lot of activity so will close this. Let us know if this still causes problems for you and we'll reopen.
