### ISSUE TITLE
Bar Gauge upredictable rows order

### ISSUE THREAD

**Issue by svzhl** [grafana/grafana#19672]
**What happened**:
Order of data shown is unpredictable

**What you expected to happen**:
Values are shown in order the queries are defined

**How to reproduce it (as minimally and precisely as possible)**:
Define multiple queries
![изображение](https://user-images.githubusercontent.com/33315430/66313734-82d69300-e91b-11e9-9fca-ab7b93f46b9f.png)

The data appears in correct order
![изображение](https://user-images.githubusercontent.com/33315430/66313503-296e6400-e91b-11e9-8b15-528b67bcd8be.png)

But after auto-refresh the order is unpredictable
![изображение](https://user-images.githubusercontent.com/33315430/66313581-473bc900-e91b-11e9-9113-b9fb1ea402ee.png)

Manual refresh seems fixing the issue but next auto-refresh will cause columns/rows shuffling

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: v6.4.1
- Data source type & version: Prometheus 
- OS Grafana is installed on: CentOS Linux release 7.5
- User OS & Browser: Windows 10 Firefox 69
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed in master (reported a couple of times now), fixed in tomorrows 6.4.2 patch, #19597
