### ISSUE TITLE
No built package for i386 architecture

### ISSUE THREAD

**Issue by adamehirsch** [grafana/grafana#1968]
I've got a handful of i386 instances on which I'd like to run grafana -- any chance we could get a .deb package or instructions on building it for such?

**Comment by torkelo** [comment]
http://docs.grafana.org/project/building_from_source/

**Comment by torkelo** [comment]
There is so little demand for it currently so I opted to only include x64 packages to save time when doing new releases (and when building the build scripts and build server setups)

**Comment by wrzasa** [comment]
Sad. Just wanted it on my older 32bit instance...

**Comment by wrzasa** [comment]
For anyone with this problem, I found older Debian binary here: https://packages.debian.org/sid/grafana for now it will have to do...

**Comment by bobemoe** [comment]
All the links here are broken. I'm looking to run on i38r, happy to build from source but cant find any download links :/
