### ISSUE TITLE
Grafana pop-up annotations instead of values on iPad when I touch a graph

### ISSUE THREAD

**Issue by orcunbaslak** [grafana/grafana#19681]
**What happened**:
I'm trying to use Grafana on my iPad however when I touch a graph, I cannot see the values. Values show instantly for a sec then "annotation" bar pops-up. 

**What you expected to happen**:
I expect grafana to show the values when I touch on a graph.

**How to reproduce it (as minimally and precisely as possible)**:
Go to a grafana bar on an iPad and touch a graph.

**Anything else we need to know?**:
Could that be a CSS issue?

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Influxdb
- OS Grafana is installed on: Debian 9
- User OS & Browser: Safari + iPad iOS13
- Grafana plugins: No additional plugins.
- Others:

**Comment by daldoyle** [comment]
I was going to open an issue on similar when I saw this. I believe the annotation popup used to be a right click function but was moved to click at some point. This has confused some of our users. It would be great to have this back on right click or alternatively have a way to turn it off entirely.

Additionally, the annotation pops up even when the user has the "Viewer" role and cannot add an annotation. Attempting to add results in "Access denied to this dashboard" error. This seems like an oversight to me - probably shouldn't show it at all in that case?

**Comment by cby016** [comment]
This is affecting me also. Now on mobile it's not possible to see the values of graphs by clicking. Is there anyway to disable the annotations popover on mobile?

**Comment by Knallochse** [comment]
It would be great if it gets fixed. the service on the ipad is very bad in the current state

**Comment by mabnz** [comment]
I’ve been struggling with this for ages and thought it was just me. Happens on Firefox and chrome also (on mobile).

Also have a probably unrelated issue where panels will completely disappear if I touch them.

**Comment by schoerg** [comment]
This is still broken for mobile browsers.
Chrome mobile: a single tap will bring up the annotations menu, a long tap will show the value. The other way around would be much better.

**Comment by mabnz** [comment]
Having a choice to disable annotations entirely would be great.
