### ISSUE TITLE
Text panel: Template variables can't be used with alternate formats in URLs in Markdown mode

### ISSUE THREAD

**Issue by wfraser** [grafana/grafana#19690]
**What happened**:
In a markdown text panel, variables in URLs can't be specified with alternate formats using the `${var:fmt}` or `[[var:fmt]]` syntax.

Because Markdown formatting happens before variable expansion, this syntax gets percent-encoded and then the templating doesn't recognize that it's a variable at all. See https://github.com/grafana/grafana/blob/fd21e0ba14dac32ae703dd6c73d93c84eeb881e2/public/app/plugins/panel/text/module.ts#L84-L98

This should be done in the reverse order, in my opinion (i.e. expand variables and THEN do markdown formatting).

**What you expected to happen**:

The variable should get expanded just like anywhere else in Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

Let's say you have a variable $foo with value "Hello World". If you have a Text panel, with the mode set to markdown, and you make a link where you want to pass the variable in the URL, so you want to `percentencode` it like this:

```
A link: [link](https://example.com/?foo=${foo:percentencode})
```

This gets expanded to:

```
A link: <a href="https://example.com/?foo=$%7Bfoo:percentencode%7D">link</a>
```

instead of the desired:

```
A link: <a href="https://example.com/?foo=Hello%20World">link</a>
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: current master, v6.5.0-pre (5202770bdc)
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox
- Grafana plugins: none
- Others:

**Comment by hugohaggmark** [comment]
We've upgraded the Text Panel since we created this issue, so I'm closing this issue as I can't repro it on Grafana v7.4.0-pre (db637a3630). 

Thank You to you for taking the time to create this issue!
