### ISSUE TITLE
Grafana 6.4.1 armhf Docker Image does not start

### ISSUE THREAD

**Issue by siegfriedhoellrigl** [grafana/grafana#19709]
Raspberry PI (arm 32 Bit System) - Was working perfectly with Version 6.3.6.

docker run -ti --rm grafana/grafana:6.4.1
 gives :
/run.sh: line 80: /usr/share/grafana/bin/grafana-server: No such file or directory

6.4.0 seems to have the same issue.

**Comment by xlson** [comment]
Duplicate of #19585
