### ISSUE TITLE
Expose Graphite functions available as Grafana configuration keys

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#1970]
Since there is no API for Grafana to grab which Graphite functions are available they must be hard coded.Because different versions of Graphite don't have all the same functions available (e.g. "reduceSeries") this results in potential discrepancies between the Graphite functions that are actually available and what Grafana shows to the users.
In order to protect the Grafana users from trying to use functions that are not available the Grafana/Graphite operator/admin has to determine which ones are not available and then comment them out in Grafana source code; or just go with telling the users "don't use function foo it doesn't work" which is not acceptable IMHO.
Until there is an API I propose to make this a little less painful while exposing the mapping of Graphite to Grafana functions as a Grafana configuration as one can then use CM automation. It'd also be easyto expose this issue better by adding comments describing which functions comes with which Graphite version. 

This is a "child" of https://github.com/grafana/grafana/issues/1966

**Comment by DanCech** [comment]
see #10139

**Comment by jaimegago** [comment]
@DanCech cool, I'll close this one when it gets merged, do you think we should have a note somewhere for legacy Graphite versions users wrt discrepancies between available Graphite functions vs functions available in Grafana? I'm fairly certain there are plenty of Graphite 0.9.x users out there with this common issue.

**Comment by DanCech** [comment]
@jaimegago actually in the time since you opened this issue a `"version"` attribute has been added to the function definitions that are included in Grafana, so it would be a matter of someone going through and tagging each function with the Graphite version that it was added in.

**Comment by jaimegago** [comment]
@DanCech Is the graphite version tag of a grafana function dynamically evaluated against the graphite web version to make a decision on Grafana availability of the function or is it more about internal documentation for developers? Happy to take a stab at the  graphite version tagging if you can point me in the right direction *and* if that version is evaluated within Grafana.

**Comment by DanCech** [comment]
All the functions are defined in https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/gfunc.ts and you can see that some of them have a `version` attribute. That is evaluated against the version of the graphite server when assembling the list of functions to present to the user.  There are quite a few changes to that file in #10139 but if you were to go through and add the `version` attribute to any functions that you've noticed shouldn't be shown to older graphite versions, I'm sure that I could resolve any conflicts that came up.

**Comment by jaimegago** [comment]
@DanCech  Before I get started and since it's kinda documentation work I'd like to make sure we're on the same page.
How should I evaluate this:
> add the version attribute to any functions that you've noticed shouldn't be shown to older graphite versions 

In particular  what is tl be considered  "older graphite"?

Considering a bunch of functions already are tagged with a version >= 1.0, I would only add version tags to functions that don't already have one?

**Comment by aocenas** [comment]
Seems like this is already handled by the versioning if there are any specific functions that are wrongly versioned please open a separate issue for that.
