### ISSUE TITLE
Yarn frontend tests can fail due to millisecond differences

### ISSUE THREAD

**Issue by bLiGM** [grafana/grafana#19710]
**What happened**:

I ran `yarn test` on master `9904e14f8ecafbba20c446fd26c0f0d1accfc005`

One of the tests failed due to a millisecond difference in Epoch time:

```
 Summary of all failing tests
>> FAIL public/app/features/dashboard/state/runRequest.test.ts
>>   ● runRequest › If time range is not relative › should add the correct timeRange property and the request range should not be mutated
>> 
>>     expect(received).toBe(expected) // Object.is equality
>> 
>>     Expected: 1570546636127
>>     Received: 1570546636128
>> 
>>       223 |     it('should add the correct timeRange property and the request range should not be mutated', () => {
>>       224 |       expect(ctx.results[0].timeRange).toBeDefined();
>>     > 225 |       expect(ctx.results[0].timeRange.to.valueOf()).toBe(ctx.toStartTime.valueOf());
>>           |                                                     ^
>>       226 |       expect(ctx.results[0].timeRange.to.valueOf()).toBe(ctx.results[0].request.range.to.valueOf());
>>       227 | 
>>       228 |       expectThatRangeHasNotMutated(ctx);
>> 
>>       at Object.<anonymous> (public/app/features/dashboard/state/runRequest.test.ts:225:53)

```

On re-running `yarn test` the test succeeded.

**What you expected to happen**:

`yarn test` succeeds every time.

**How to reproduce it (as minimally and precisely as possible)**:

Run `yarn test` (on a slow system?)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Master (Pre-6.5)
- Data source type & version: N/A
- OS Grafana is installed on: Centos 7 
3.10.0-862.14.4.el7.x86_64
- User OS & Browser: N/A
- Grafana plugins: None
- Others: None

**Comment by ivanahuckova** [comment]
Thanks for reporting this! We will look further into this issue.
