### ISSUE TITLE
How to use grafana template for different dashboards

### ISSUE THREAD

**Issue by aather** [grafana/grafana#1971]
I have multiple dashboards and using grafana templating to provide list of cluster name and list of instances within that clusters:
I am using "Clusters" and "Instances" variables to list all clusters names and instance id.  This generic list works fine if all clusters have similar metrics. However, I have application clusters with different dashboards with their unique metrics, for e.g: cassandra, kafka, elasticsearch etc..

Question: How can I use templating to filter cluster names in the application specific dashboards. Is there a way to have separate template for each dashboard so that I can filter names? Any other way to perform this task?

Thanks,
Amer.

**Comment by oprietop** [comment]
I'm having the same grudge with snmp dashboards. As i'm using the same template for different hardware i got tons of graphs that won't show any data making the dashboard kinda cluttered.

I think having a dashboard global option to just hide empty graphs and rows would be neat to make those dashboards more appealing. That option could have a tooltip or something to tell you if the current dashboard has any empty graph so you can uncheck the option and give it a look.

**Comment by torkelo** [comment]
@oprietop how do grafana know when a metric does not exist it needs to perform the queries, sure it could hide the graphs if there was no data. But would be very messy and graphs and panels would blink in and out of existance. 

Please come up with a better solution :)

**Comment by torkelo** [comment]
@aather I do not understand your question. " Is there a way to have separate template for each dashboard so that I can filter names" Template variables are specific to each dashboard already.

**Comment by oprietop** [comment]
Maybe only showing the graph after it got any datapoints.
I'll give it a try myself to see how the dashboard creation logic behaves then propose a pull If i can come up with something relevant.

**Comment by aather** [comment]
There may be a ways to do it with template variables using pattern search, but I need help in writing a correct pattern. 
 In our environment, cluster names start with: cass_xxx, kafka_xxx.. I have created dashboards for each cluster type: cass_xxx, kafka_xxx. Since, I am using global pattern search/filter option, I see all clusters listed in each dashboard. I want to use a pattern that allows me to list  only clusters that match the dashboard, cass_xxx clusters for cassandra dashboards; kafka_xxx clusters for kafka dashboard ..

There are not many examples available. Please let me know how to use pattern search to achieve desired results.

![template](https://cloud.githubusercontent.com/assets/5282686/7541154/dceece2c-f567-11e4-97b0-66382c47042c.png)

![cluster-edit](https://cloud.githubusercontent.com/assets/5282686/7541128/a9c35252-f567-11e4-8d33-cf886806200e.png)

![instance-edit](https://cloud.githubusercontent.com/assets/5282686/7541132/b1438286-f567-11e4-9b81-6be0a02adf24.png)


Thanks,
Amer.

**Comment by torkelo** [comment]
@aather try this: `cluster.cass_*`  

You can have wildcard in the middle of node segments to only get graphite nodes that start with `cass`
