### ISSUE TITLE
Parent-Child Variable Issue

### ISSUE THREAD

**Issue by toleds** [grafana/grafana#19728]
**Grafana version 6.4.0**
**Datasource : MySQL**

I have created 2 query variables namely $continent and $country

**$continent query** 

> select id as __value, name as __text from ( 	select 1 as id, 'Africa' as name  	union  	select 2 as id, 'Antarctica'  as name 	union 	select 3 as id, 'Asia'  as name 	union 	select 4 as id, 'Australia/Oceania'  as name 	union	 	select 5 as id, 'Europe'  as name 	union 	select 6 as id, 'North America'  as name 	union 	select 7 as id, 'South America'  as name ) a

**$country query**

> select id as __value, name as __text from ( select * from ( 	select 1 as cont, 1 as id, 'Africa 1' as name 	union select 1 as cont, 1 as id, 'Africa 2' as name 	union 	select 3 as cont, 1 as id, 'Singapore' as name 	union 	select 3 as cont, 1 as id, 'Malaysia' as name	 ) a where a.cont = $continent ) a

**Expectation** 

When selecting  a continent, it should filter the countries in that particular continent.

**What is Happening?**

It is only listing the first record in the child list.

![image](https://user-images.githubusercontent.com/25734236/66477323-6fb5f580-eaca-11e9-932b-481dc9384b1f.png)

**Comment by torkelo** [comment]
Can you open chrome dev tools and look at the network request when you change the continent? What is that query and what does it return? can you see anything wrong in the SQL Grafana sends in the query (when you change continent)

**Comment by toleds** [comment]
**Here is the result, hope this helps,  apparently the return data is correct, only the display is wrong** 

![image](https://user-images.githubusercontent.com/25734236/66534794-f362f700-eb49-11e9-8d0b-0dadd694202d.png)


**the query statement is**

> sql: "select id as __value, name as __text from ( select * from ( 	select 1 as cont, 1 as id, 'Africa 1' as name 	union select 1 as cont, 1 as id, 'Africa 2' as name 	union 	select 3 as cont, 1 as id, 'Singapore' as name 	union 	select 3 as cont, 1 as id, 'Malaysia' as name	 ) a where a.cont = '3' ) a"

**Comment by toleds** [comment]
This issue is my mistake.  grafana variables filtering runs perfectly.

Issue was the same id was put on both records.

Thanks for the help.
