### ISSUE TITLE
Embedded iframe of grafana panel does not load on firefox

### ISSUE THREAD

**Issue by austin-barrington** [grafana/grafana#19729]
**What happened**:
Using the iframe shared option to embed an iframe panel, the graphs loads on chrome & safari. However it does not on firefox. It just loads a blank even though it returns a 200, and loads when going direct.

**What you expected to happen**:
 Load on firefox as other browsers load.

**How to reproduce it (as minimally and precisely as possible)**:
 load grafana panel  in an Iframe on firefox and it does not work

**Anything else we need to know?**:

```
# set to true if you host Grafana behind HTTPS. default is false.
cookie_secure = true

# set cookie SameSite attribute. defaults to `lax`. can be set to "lax", "strict" and "none"
cookie_samesite = none

# set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
allow_embedding = true
```

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: influxdb
- OS Grafana is installed on: debian 10
- User OS & Browser: Mac, linux, windows & firefox
- Grafana plugins: none
- Others:

**Comment by austin-barrington** [comment]
Nginx proxy with a header added for X-Frame-Options' 'allow-from: https://<sitename>' will solve this.

You MUST put this under the main domain and not a subdomain without an additional port.

Chrome does not like `SAMEDOMAIN` and Firefox does not like `allow-from *`

**Comment by cdupont** [comment]
Is it possible to create an embedded iframe using the Cloud free-tier of Grafana?
Is it possible to test it locally (e.g. a simple HTML file in my laptop)?

**Comment by yilmaznaslan** [comment]
I am having the same issue by using the cloud free-tier. Is there any solution suggestion ?
