### ISSUE TITLE
CPU Utilization

### ISSUE THREAD

**Issue by syd05** [grafana/grafana#1973]
Hi,
I would like to create a dashboard to graph CPU Utilization. The scenario I'm looking to work with is that collectd send cpu states metrics for a multicore server. I need to aggregate the values of a single servers for all cpu cores & all cpu states likes user,system, wait etc... except idle & would have multiple servers as such. So the legend name should be the nodes' hostname also

To summarize, I need cpu utilization as 100% - idle % of all cores either using diff or trying to add up the sum of the other CPU states except idle. So in case I have two servers, I would have two lines in a single graph  & the legend name as the hostname

I've tried various options to the best of my understand but have not been able to achieve the desired graph. Assistance appreciated

--Syd

**Comment by torkelo** [comment]
Please use the mailing list for pure questions
https://groups.io/org/groupsio/grafana

Also important to specify what data source you are using and the layout of your metrics.
