### ISSUE TITLE
Improvements to Grafana builds

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#19737]
As @xlson, @marefr and I discussed today, we need to make some changes to our build processes. Basically, we are building and distributing two types of artifacts: Independent binaries and Docker images. The underlying cause of the discussion was that our Docker images for the ARM architecture are broken, since the contained Grafana binary dynamically links to glibc while Alpine only has musl.

## Independent Binaries
The Linux binaries we build for different architectures are dynamically linked, to glibc, and we might either want to link them statically (with musl?) for maximum portability or add variants dynamically linking to musl for compatibility with Alpine.

We don't know for sure if our binaries might currently link to other dependencies than glibc. If we do link to other dependencies, or foresee we might in the future, we should probably switch to static linking.

## Docker Images
Our Alpine based Docker images are currently built by copying in pre-built binaries corresponding to the architecture in question (AMD64/ARM). This works for AMD64, presumably because we install glibc in conjunction with PhantomJS. It's broken for ARM however, since Grafana links to glibc dynamically and Alpine doesn't have it.

Our plan is to fix the ARM images in the short term by installing glibc. In the long term, we foresee two alternatives:

1. Build extra binary variants that dynamically link to musl (i.e. Alpine compatible) and copy them into the Docker images.
2. Build the binaries directly inside Docker to ensure they are Alpine compatible.

**Comment by xlson** [comment]
Thanks for summarising this into an issue.

**Comment by aknuds1** [comment]
No worries @xlson, I'm currently working on this as well.

**Comment by aknuds1** [comment]
This one should be fixed.
