### ISSUE TITLE
Request URI Too Long 414 when "All" option is selected

### ISSUE THREAD

**Issue by pcroc** [grafana/grafana#19731]
**What happened**:
I added a WHERE clause to my widget query, based on a dashboard variable with a very large number of options. When the variable is set to the "All" option, the widget fails to load with "Network Error: Request URI Too Long(414)".

When I inspect the browser console, I can see the URL being fetched by the widget query contains all possible options in the query string, therefore making the URL too long.

**What you expected to happen**:

When "All" is selected, the widget still loads. Grafana doesn't attempt to put every known value into the query string.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a variable that has thousands of options
2. Create a widget that uses this variable in the WHERE clause

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.2.5 (6082d19)
- Data source type & version: InfluxDB
- OS Grafana is installed on: Unknown
- User OS & Browser: Windows 10 Chrome
- Grafana plugins: Unknown
- Others:

**Comment by cbonte** [comment]
As a workaround, I usually set the **Custom all value** to `.*`

**Comment by torkelo** [comment]
You can set custom value, or change request method to POST in the data source settings.

**Comment by tarik56** [comment]
For anyone not finding the data source settings.

1. Go to Grafana Homepage 
2. Hover over Settings icon left menu
3. Click on Data Sources 
4. Click data source ( eg prometheus )
5. Scroll to Custom HTTP Headers
6. Change HTTP Method to POST

**Comment by bfc5288** [comment]
(Just in case anyone else is deciding which solution to use)

I encountered this issue with Grafana v6.4.0. I tried both methods, but only one worked properly:
* Setting `Custom All` to `.*` solved the 414 Error, but this caused inaccurate queries when using `All` for a variable.
* Changing the HTTP Method as described above also solved the 414 Error and didn't cause inaccurate queries.
