### ISSUE TITLE
tsdb.HandleRequest() error Get https://

### ISSUE THREAD

**Issue by noomtw** [grafana/grafana#19735]
error:"tsdb.HandleRequest() error Get https://xx.xx.xx.xx/prometheus/api/v1/: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs"

how can i fix this 

thank

**Comment by torkelo** [comment]
not sure, looks like a problem with the certificate? Have you specified a custom certificate?

**Comment by noomtw** [comment]
how to do that ?

**Comment by noomtw** [comment]
hello how can i do that ???

**Comment by torkelo** [comment]
Grafana could not validate the certificate on your prometheus server, maybe you need to add a certificate root to your server CA path. or it's using a strange format that is not supported, not sure. 

This error is a generic TLS certificate error that is not really something Grafana is involved in. 
https://serverfault.com/questions/611120/failed-tls-handshake-does-not-contain-any-ip-sans
