### ISSUE TITLE
Implement an option to define the colors of table headers or hide table headers

### ISSUE THREAD

**Issue by Fischer96** [grafana/grafana#19745]
**What would you like to be added**:

It would be a nice to have feature to change the color of a header in the table panel. Could be implemented like the color picker for SingleStat. Another good option would be hiding the header bar completely for a table.

**Why is this needed**:

We are currently using tables with only one row and column to set dynamic html text. To save some space we get rid of the table title and use the column name as a title. Would be great to get rid of the blue color to make it look better.

**Comment by torkelo** [comment]
Don't think we will have color options for header, but hiding header sounds reasonable:

https://github.com/grafana/grafana/issues/3783
