### ISSUE TITLE
Grafana does not exclude values that are not displayed from calcuations from min, max, avg

### ISSUE THREAD

**Issue by cwolfinger** [grafana/grafana#1974]
As shown at the bottom of this thread:  https://groups.io/org/groupsio/grafana/thread/avg_min_max_vs_graph/64478?threado=0  the client side calculation of min, max, and avg includes values that are before or after the min / max values on the X axis.  This is due to the fact the grafana query always subtracts 1 minute from the min and adds 1 minute to the max.  For example if in zooming in we show 2 minutes of a stats (12 points) - then 24 data points are returned from graphite but only 12 are shown.  The avg, total, min, max etc all are calculated on the 24 data points.

**Comment by torkelo** [comment]
not sure how to fix this so closing this.
