### ISSUE TITLE
Singlestat  : value mapping 

### ISSUE THREAD

**Issue by rguptarg** [grafana/grafana#19740]
Hi Team,

We are using Singlestat 
![Old_grafana](https://user-images.githubusercontent.com/49057178/66563074-9cc1e100-eb7a-11e9-83ff-e6944b784379.JPG)
![New_Grafana](https://user-images.githubusercontent.com/49057178/66563075-9d5a7780-eb7a-11e9-91f2-ca5fd89902e9.JPG)

plugin and want to mapped value if there is no output in query.

In old version of grafana, we did easily but in new version it's showing "No Data".

Please help :- if there is no output, value should be 0.

**Comment by torkelo** [comment]
Dupe of https://github.com/grafana/grafana/issues/19645
