### ISSUE TITLE
'cookie_secure' has no impact on 'redirect_to' cookie

### ISSUE THREAD

**Issue by jeffdesc** [grafana/grafana#19744]
**What happened**: After a security scan we noticed the cookies were not secure. We enabled it through `cookie_secure` and all Grafana cookies are secure now. 

However one cookie `redirect_to` is still not secure.

**What you expected to happen**: After enabling `cookie_secure` the `redirect_to` cookie should be secure as well.

**How to reproduce it (as minimally and precisely as possible)**:
- Enable HTTPS
- Configure SSL certificate and key
- set `cookie_secure` on `true`
- Perform a cURL to the Grafana server:
```
$ curl -I https://GRAFANA-URL/
HTTP/1.1 302 Found
Location: /login
Set-Cookie: grafana_sess=XXXXXXXXX; Path=/; HttpOnly; Secure
Set-Cookie: redirect_to=%252F; Path=/; HttpOnly
Date: Thu, 10 Oct 2019 12:11:32 GMT
Content-Type: text/plain; charset=utf-8
```

**Anything else we need to know?**: The `redirect_to` cookie should be secure as well if `cookie_secure` is enabled.

**Environment**:
- Grafana version: production 5.0.4, tested it on 6.4.2 as well
- Data source type & version: Influx
- OS Grafana is installed on: Debian 9
- User OS & Browser: Mac OS X / Chrome
- Grafana plugins: PieChart
- Others: n/a

**Comment by torkelo** [comment]
agree. Cookie is set here: 
https://github.com/grafana/grafana/blob/master/pkg/api/login.go#L66

**Comment by cored** [comment]
@torkelo @jeffdesc I would like to work on this

**Comment by jeffdesc** [comment]
@torkelo I've setup the development environment to test it and it seems like that the issue is here in my case: https://github.com/grafana/grafana/blob/master/pkg/middleware/auth.go#L50.

If I make adjustments in login.go (the one you said) it does not reflect in the cURL above, where is the redirect_to cookie injected in the login.go (which URLs)?

@cored I actually have the fix ready already, it's a simple adjustment in the auth.go file. Awaiting feedbac from @torkelo to push the PR.
