### ISSUE TITLE
grafana alerting method in others visualization modes

### ISSUE THREAD

**Issue by fredbcode** [grafana/grafana#19751]
Hello 
I'm using bar gauge with grafana 6.4.2 and all works well
Unfortunately there is no Alerting menu, this is something planned ?

To reproduce just switch Visualization: Graph to Gauge  

Thank you

**Comment by torkelo** [comment]
No, not planned, we are planing to move alerting out of panels into their own thing.

**Comment by fredbcode** [comment]
Thanks, a long term change or sooner?

**Comment by torkelo** [comment]
early next year I hope

**Comment by TurkerTunali** [comment]
We usually create another dashboard just for alerts.

**Comment by fredbcode** [comment]
Yes I will create a special dashboard, but this is strange, it's like something very important is missing

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
