### ISSUE TITLE
[Feature request] add SI prefix caps

### ISSUE THREAD

**Issue by lobeck** [grafana/grafana#19758]
**What would you like to be added**:

There should be a set of units that will be capped at a certain prefix on the SI scale. 

For example: Prometheus recommends using meters as unit of distance measurement. When selecting the meters unit in Grafana it will convert large values like 5128179 into 5 Mm which is technically correct but often not helpful. In this case this should represent a distance in Kilometers, so it would be preferable to cap the unit scaling at "K" and not apply any additional SI steps.

**Why is this needed**:

This will preserve values in human readable formats and eases UX.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
