### ISSUE TITLE
Redirect after sign up

### ISSUE THREAD

**Issue by shay117** [grafana/grafana#19753]
Not sure if this IS a bug or I just missed something.
**What happened**:

I have a Grafana instance that allows users to sign up, which is running in a Docker container with port 3001 mapped to 3000. There are 2 dashboards in the main org, where one is set as the default home. If I give a user a link to the second dashboard, http://IP:3001/otherdashboard, it redirects them to the login page and if they don't have an account they click the sign-up. After they sign-up, it takes them to the home dashboard instead of redirecting them to the provided link. However, if they already have an account and just log in, it will redirect them to http://IP:3001/otherdashboard as expected. 

My grafana.ini changes:
[users]
allow_sign_up = true
auto_assign_org = true

[auth]
login_cookie_name = charts_session

**What you expected to happen**:

User to be redirected to non-home dashboard, http://IP:3001/otherdashboard, after signing up. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version:
- OS Grafana is installed on: Docker container using grafana/grafana image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
