### ISSUE TITLE
Drag-zoom into small enough time-range generates a bad (float duration) InfluxDB 0.9 query

### ISSUE THREAD

**Issue by jbweeks** [grafana/grafana#1975]
At some point, the drag-zoom queries generate a floating point duration instead of an integer, which causes InfluxDB 0.9 to barf (i.e. the time range duration in the GROUP BY below):

SELECT mean(value) FROM "riemann server tcp 127.0.0.1:5555 in rate" WHERE time > 1431118833s and time < 1431118856s GROUP BY time(0.1s) ORDER BY asc

Grafana v 2.0.2
InfluxDB v 0.9

I can successfully drill down from, e.g. past 7 days to a 4 hour range, but at some point, Grafana generates a floating point duration for the GROUP BY which fails.

(Arguably, could also file an issue on InfluxDB API to accept floats, as JSON-native numerical type)

**Comment by jbweeks** [comment]
One more note -- one acceptable path would be to simply change the units -- e.g. 100ms is a valid InfluxDB duration in the query above.

**Comment by torkelo** [comment]
Fixed in https://github.com/grafana/grafana/commit/8f0269de768f343f6ac9a766b7d816b3123a422c
