### ISSUE TITLE
Alerting: All notification channels should send even if one fails to send

### ISSUE THREAD

**Issue by stephendoherty101** [grafana/grafana#19768]
**What happened:**
A Grafana alert was configured with the following notifications in the sequence below:

Slack
Alerta
Email

From the logs we can see the Slack notification sent, then we can see the Alerta notification failed (a "500 Server Error" from the webhook). No email notification was ever attempted.

Error received
```
t=2019-10-09T04:13:05+0100 lvl=dbug msg="Webhook failed" logger=notifications statuscode="500 INTERNAL SERVER ERROR" body="{\"code\":500,\"errors\":null,\"messa
ge\":\"Logstash TCP connection error: [Errno 111] Connection refused\",\"requestId\":\"Root=1-5d9d5041-b8ca91f6917a8d05909bb2bc\",\"status\":\"error\"}\n"
```
After receiving the error no attempt was made to send the email alert.

**What you expected to happen:**
After the failed Alerta notification I expected the email alert to fire. 

**Environment:**
- Grafana version: v6.4.1 (4ba8388)
- Data source type & version:
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: macOS Mojave 10.14.6

**Comment by torkelo** [comment]
@marefr do you know how this is supposed to work? On a notification error should it continue with the next one?

**Comment by marefr** [comment]
Seems to have been introduced by this #18967 included in v6.4.0.

**Comment by marefr** [comment]
**Changes needed to resolve this:** 
This error 
https://github.com/lzdw/grafana/blob/b0bf2ea09f4fa4f73c5a1021e8b5bc41d79a0ade/pkg/services/alerting/notifier.go#L112
should only be returned if `evalContext.IsTestRun` is true, otherwise `nil`.

**Comment by jan25** [comment]
I'll give this a shot if no ones already working on it
