### ISSUE TITLE
Panel: text panel shows query editor as default

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#19762]
**What happened**:

When I click edit on a text panel or getting started panel or dashboard list panel, then I see a query editor for the default datasource. There is no navigation for it on the left hand side.

![image](https://user-images.githubusercontent.com/434655/66635468-9af62d00-ec0f-11e9-81e9-429b8f46b700.png)

**What you expected to happen**:

I expected that the visualization options to be shown as default and did not expect the query editor to be shown as it makes no sense for these types of panels.

**How to reproduce it (as minimally and precisely as possible)**:

1. Navigate to https://play.grafana.org
2. Edit one of the dashboard lists on the home dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4
- Data source type & version:
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu, Chrome and Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
To fix this: 
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/panel_editor/PanelEditor.tsx#L112

This needs to default to first tab in state.panelEditor.tabs[0].id

Keep in mind that the state.panelEditor.tabs defaults to empty so needs a check for empty
