### ISSUE TITLE
CloudWatch dimension "Service class" not working

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#19761]
**What happened**:
Using the Cloudwatch data source the dimension "Service class" the dimension values are not populated. 
![image](https://user-images.githubusercontent.com/49911675/66633013-68165e00-ec3c-11e9-8b5c-0e9b0e5dc1f8.png)

This can be solved by manually by typing "service class" (all lower case) as a dimension, so the issue is the capital **S** in the Grafana dimension. 

**Environment**:
- Grafana version:
- Data source type & version: cloudwatch
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Based on documentation [here](https://docs.aws.amazon.com/redshift/latest/mgmt/metrics-listing.html) the dimensions `Service class` and `Stage` here 
https://github.com/grafana/grafana/blob/a427ff7f8d20a5e5ec275aa07896698479e25fad/pkg/tsdb/cloudwatch/metric_find_query.go#L183
Needs to be updated to `service class` and `stage`.

**Comment by cored** [comment]
@marefr can I work on this?

**Comment by gotjosh** [comment]
Assigned it to you @cored.
