### ISSUE TITLE
Datasource is not correctly updated when using basic auth

### ISSUE THREAD

**Issue by Horkyze** [grafana/grafana#19764]
Data source is not correctly updated in Grafana Web UI

I setup Prometheus data-source with basic auth, but the connection to it always failed. When I inspec the datasource with API call i get:

```
GET /api/datasources/4
{
    "id": 4,
    "orgId": 1,
    "name": "Prometheus",
    "type": "prometheus",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "https://loki.example.com/loki",
    "password": "",
    "user": "",
    "database": "",
    "basicAuth": true,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": false,
    "jsonData": {
        "httpMethod": "GET",
        "keepCookies": [],
        "oauthPassThru": false,
        "tlsAuth": false,
        "tlsAuthWithCACert": false
    },
    "secureJsonFields": {
        "basicAuthPassword": true
    },
    "version": 67,
    "readOnly": false
}
```

I expext that the `basicAuthUser` and `basicAuthPassword` would be set.

![image](https://user-images.githubusercontent.com/1040383/66639244-cc262b80-ec16-11e9-8fc5-63fa770c8176.png)

Then I updated the data-source with `PUT` API call, and it worked (presed the Save & Test button in UI)

**Environment**:
- Grafana version:  Grafana v6.4.2 (443a0ba)
- Data source type & version: grafana / loki : master-364b5bc
- OS Grafana is installed on: Debian 9, Docker
- User OS & Browser: macOS Mojave 10.14.6 (18G103), Firefox 70.0b13 (64-bit)

Perhaps related to: https://github.com/grafana/loki/issues/985

**Comment by torkelo** [comment]
The docs are incorrect (old), you need to set password via the secureJsonData.basicAuthPassword property

**Comment by Horkyze** [comment]
Docs? I did not take a look at docs, it looks like the UI is not correctly making calls to the API.

**Comment by torkelo** [comment]
It is, but the basic auth password is set only when you reset it and is otherwise nothing you can read from the api, as it is encrypted internally and never exposed via api
