### ISSUE TITLE
Snapshot: Show confirmation before navigating back to original URL

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#19767]
**What would you like to be added**:
A confirmation before navigating back to original dashboard URL from a snapshot.

**Why is this needed**:
If a snapshot have an original dashboard url defined the following button is shown when rendering snapshot:
![image](https://user-images.githubusercontent.com/1668778/66648599-35fd0000-ec2c-11e9-843f-c71e703b68aa.png)

If snapshot is stored in an external Grafana instance it's good to make the user aware of what the original link of the dashboard is before opening the link.

**Comment by dprokop** [comment]
@marefr would an idea be to open such dashboard in a new tab?

**Comment by marefr** [comment]
Maybe. But need a modal or similar to make user aware of navigating away to another site/domain than the one currently in use and what that full url is. Tried to find a screenshot from Google docs but couldn't find any now. Or do you mean that we open a new tab but let Grafana server render a page with the confirmation above?

**Comment by marefr** [comment]
Found what I was looking for:
![image](https://user-images.githubusercontent.com/1668778/79974419-99989d80-8499-11ea-8ba1-5a611472b115.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
