### ISSUE TITLE
Attempting to use new KairosDB plugin, cannot downsample data

### ISSUE THREAD

**Issue by sumomandrews** [grafana/grafana#1976]
Hi,

I know that the new KairosDB plugin for Grafana v2 is a WIP, but I did just find the following:

When attempting to downsample data I get the error:

"Property 'align_start_time' was specified for object 'avg' but no matching setter was found on 'class org.kairosdb.core.aggregator.Avg.Aggregator'"

![image](https://cloud.githubusercontent.com/assets/10818699/7548282/68005482-f5b7-11e4-8888-5bdcc4237775.png)

I was obviously trying an "Average" downsample, but this occurs for all other downsample types as well.  I'm going to look into it further on Monday, but just wanted to enter this issue in case.

This KairosDB plugin is perfectly timed... we're using it for prototyping a project right now!

~ Michael

PS: The KairosDB branch is incorrectly named as "kariosdb".  Took me a little while to clone the branch (until I noticed the typo)!  :P

**Comment by torkelo** [comment]
ping @masaori335  

I think I have seen this before, what version of KairosDB are you using?

**Comment by masaori335** [comment]
Hi, guys

I'm working in KairosDB Plugin with `kairosdb-0.9.4-6` and I can't reproduce the error.
We need more details.

BTW, thanks for trying KairosDB Plugin.
Yes, the branch name is confused.

**Comment by sumomandrews** [comment]
Hi guys,

Here are the versions:

grafana.x86_64                             2.0.2-1                     @grafana
kairosdb.noarch                            0.9.3-2                     @/kairosdb-0.9.3-2

I'll try updating KairosDB now, didn't know there was a newer version out.  Will update when finished.

Thanks for the quick response!

**Comment by sumomandrews** [comment]
Gentlemen,

Upgrading KairosDB to 0.9.4 fixed the issue.  Don't know how we installed the old version since we just started playing with this less than a week ago.

Again, thanks a lot!
