### ISSUE TITLE
Dashboards saved with numeric IDs for alert notifications are not triggering notifications

### ISSUE THREAD

**Issue by aSapien** [grafana/grafana#19771]
**What happened**:
Dashboards created via API that point to alert notification channels via numeric IDs are not triggering these notification channels.
 
These dashboards are saved successfully, notification channels showing up in alert configs but are never triggered.

**What you expected to happen**:  

One of:  

- 
  1. For numeric IDs to be supported and trigger the notification channels
- 
  1. To get an error when saving dashboard with numeric IDs for alert notifications channels
  2. For the alert notification with numeric ID to not show up in the UI after save

**How to reproduce it (as minimally and precisely as possible)**:  
- Create a new webhook alert notification channel (any url that logs requests will do)
- Copy the alert numeric ID from the URL: `grafana.instance/alerting/notification/$NUMERIC_ID/edit`. 
- Create new dashboard and a panel with any metric and add any alert condition
- Open `Dashboard Settings -> JSON Model` and add `{ "id": $NUMERIC_ID }` into `panels[0].alert.notifications` array.
- Save the dashboard
- Edit panel alert and verify that the new notification channel is appearing in the list
- Trigger the alert (e.g. by editing the condition and saving)

**Expected**:
For the alert to be sent to the webhook URL

**Actual**:
The alert is not sent to the webhook URL

**Anything else we need to know?**:
Not sure when this breaking change was introduced

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: irrelevant
- OS Grafana is installed on: Debian 3.16.36
- User OS & Browser: irrelevant 
- Grafana plugins: irrelevant
- Others:

**Comment by aSapien** [comment]
@kogent do you know in which version was this breaking change introduced? This is causing silent failures :(

**Comment by vbichov** [comment]
I think that refusing a dashboard POST request with some descriptive error would be a valid solution. At current state, the dashboard is generated but alerts are not triggered
