### ISSUE TITLE
Grafana won't render OpenTSDB timeseries starting with a NaN

### ISSUE THREAD

**Issue by eswdd** [grafana/grafana#19770]
**What happened**:

Chart line failed to render when a NaN was found at the start of the response from OpenTSDB. Chart renders fine when there are NaNs in the data, but not at the start.

**What you expected to happen**:

No difference between responses starting and just containing NaN.

**How to reproduce it (as minimally and precisely as possible)**:

Construct a query which returns NaN at the start of the returned data. See attachments for example query inspector captures.
[startsData.json.txt](https://github.com/grafana/grafana/files/3718227/startsData.json.txt)
[startsNaN.json.txt](https://github.com/grafana/grafana/files/3718229/startsNaN.json.txt)

**Anything else we need to know?**:
I don't think so.

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: OpenTSDB - awaiting version
- OS Grafana is installed on:
  Linux - awaiting version
- User OS & Browser: 
  Chrome 75.0.3770.100 (Official Build) (64-bit) 
  Windows 10 OS Version 1803 (Build 17134.984)
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
I haven't done a trace, but I would guess that we eventually hit `guessFieldTypeFromValue`. `"NaN"` is a string, so the [`NUMBER` regex in `dataframe/processDataFrame.ts`](https://github.com/grafana/grafana/blob/0ad2242fb89ee74e31430dd541871f02d5f39275/packages/grafana-data/src/dataframe/processDataFrame.ts#L159) `/^\s*-?(\d*\.?\d+|\d+\.?\d*)(e[-+]?\d+)?\s*$/i` is used which doesn't match match `NaN`.

**Comment by ryantxu** [comment]
@eswdd -- can you check if this is fixed in master?
