### ISSUE TITLE
Ability to clear filters in query builder before query resolves

### ISSUE THREAD

**Issue by jordanpurinton** [grafana/grafana#19779]
**What would you like to be added**: 
The ability to clear a filter without waiting for the query to resolve.

**Why is this needed**:
We have users that have complained about not being able to build dashboards and panels quick enough due to the fact that they have to wait for the query to resolve when all they want to do is remove it from the list.

**Comment by torkelo** [comment]
Please provide more detail, what data source, what is the user flow where this feature is needed? Can you describe the steps the user takes and what the user would like to be able to do.

**Comment by jordanpurinton** [comment]
Any update here @torkelo ?

**Comment by gabor** [comment]
the current approach here is to fix this problem slightly differently (put the remove-this-filter functionality somewhere else, not in the list-of-options dropdown), but there are no specific plans yet.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
