### ISSUE TITLE
Grafana spawns timeout threads which stay defunct

### ISSUE THREAD

**Issue by torlenor** [grafana/grafana#19783]
**What happened**:
Every few hours our Grafana instance will start to spawn, but not kill, threads with the name "timeout" which will go defunct. This continues until the point that no more threads can be spawned on the server. The only way to recover is to restart Grafana. It also happens when there are no users actively using Grafana.

I include the recent log file and the thread count plots of our server.

**What you expected to happen**:
Not to spawn thousands of threads

**How to reproduce it (as minimally and precisely as possible)**:
Sadly, so far we cannot give clear instructions how to reproduce it

**Anything else we need to know?**:

- ps aux output (snippet):

> 472      22255  0.0  0.0      0     0 ?        Zs   Oct11   0:00 [timeout] <defunct>
> 472      22338  0.0  0.0      0     0 ?        Zs   04:29   0:00 [timeout] <defunct>
> 472      22358  0.0  0.0      0     0 ?        Zs   07:15   0:00 [timeout] <defunct>
> 472      22386  0.0  0.0      0     0 ?        Zs   03:50   0:00 [timeout] <defunct>
> 472      22403  0.0  0.0      0     0 ?        Zs   Oct11   0:00 [timeout] <defunct>

- pstree output (snippet):

>         |-dockerd(2493)-+-containerd(2722)-+ ...
>         |               |                  |
>         ...
>         |               |                  |-containerd-shim(9500)---grafana-server(9527)-+-timeout(304)
>         |               |                  |                                              |-timeout(333)
>         |               |                  |                                              |-timeout(334)
>         |               |                  |                                              |-timeout(392)
>         |               |                  |                                              |-timeout(399)
>         |               |                  |                                              |-timeout(435)
>         |               |                  |                                              |-timeout(549)
>         |               |                  |                                              |-timeout(570)
>                                                                                           | ...

**Environment**:
- Grafana version: 6.4.2 (also happened with 6.4.1)
- Data source type & version: prometheus 2.13.0. influxdb 1.7.8
- OS Grafana is installed on: Dockerized (Docker version 19.03.2) with official image on Alpine 3.8.4
- User OS & Browser: Linux, Windows, Chrome (latest), Firefox (latest).
- Grafana plugins: No external ones
- Others:

[grafana.log](https://github.com/grafana/grafana/files/3720367/grafana.log)

![thread_count_24hours](https://user-images.githubusercontent.com/14080364/66697925-09072680-ecda-11e9-9641-d81dc4a6916e.png)

![thread_count_week](https://user-images.githubusercontent.com/14080364/66697926-0b698080-ecda-11e9-8a46-607e334651a0.png)

**Comment by torkelo** [comment]
Can you provide more info on your setup? ini settings, provisioning? Alert rules? DB?

**Comment by torlenor** [comment]
We deployed it in a Docker Swarm using the official Grafana Docker image from Docker Hub.

The yml file for the stack is:
[docker_swarm_stack.txt](https://github.com/grafana/grafana/files/3722135/docker_swarm_stack.txt)

The ini file is mostly unchanged and defaults are used for everything except smtp:
[grafana.txt](https://github.com/grafana/grafana/files/3722137/grafana.txt)

No special settings have been made, no alert settings have been set (that I know of). As we are currently still using the default db settings, it is a sqlite3 database.

It started with the upgrade to 6.4.1, sadly I cannot say for sure what version was deployed before, probably a 6.3.x.

**Comment by torkelo** [comment]
Make sure you do not have duplicate files in provisioning with same uid or in different folders.

**Comment by marefr** [comment]
Would suggest enable [profiling and/or tracing](https://grafana.com/docs/grafana/latest/installation/troubleshooting/) and either inspect them yourself or upload them here.
