### ISSUE TITLE
LogsPanel: Elastic query does not work in dashbaords

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#19789]
Logs panel seems to expect special kind of response which for Elastic is implemented as explicit switch with `isLogsQuery` in request https://github.com/grafana/grafana/blob/90b095362052a3d2b1c92767f99a07769cfe77d0/public/app/plugins/datasource/elasticsearch/datasource.ts#L340. In dashboards though there is no way to set it (as far as I know) as `queryRunner.run` is called independent of the visualisation.

What I see as possible solutions:
- Do not do special queries. Not sure if feasible but maybe we could just say, that for this particular visualisation you need a specific query and parse single response in each visualisation.
- Allow visualisation to affect the request in some way. Something like `visualisation.modifyRequest()` that would be called before the request is run so visualisation can alter the query in some way.
- Have a preferred query editor per visualisation. The `isLogsQuery` is set in LogsQueryEditor which is one used in Explore when querying logs.

The preferred query editor solution seems to me like the best one. It is in a sense in sync with how Explore works right now, seems less invasive and keeps better separation. In the future we could allow special editor for more usecases (logs/metrics/single value/raw) selecting the best for current usecase.

**Comment by aocenas** [comment]
The preferred query editor could be also interesting in context of Loki metric queries. We could use the same editor component just with different settings so that it could give you specific hints or autocomplete consistently in both explore and dashboards. cc @kaydelaney

**Comment by DandyDeveloper** [comment]
I'm new but I've tried to follow this as best I can. 

> Have a preferred query editor per visualisation. The isLogsQuery is set in LogsQueryEditor which is one used in Explore when querying logs.

This to me looks like the better option in terms of clarity. It only seems applicable for the logs visualization right now, so it would be the change with the least overhead. 

> Allow visualisation to affect the request in some way. Something like visualisation.modifyRequest() that would be called before the request is run so visualisation can alter the query in some way.

This will likely add more confusion, although might be easier to programmatically work with for people if new visualizations are created that request these modification.

**Comment by ryantxu** [comment]
I think the solution is to convert to DataFrame...   then if a string field exists we can use logs, and if a numeric field exists, it can use graphs.

**Comment by ryantxu** [comment]
The issue with elastic datasource is that there are many options and structures that are very rarely used (docs) that are implemented both on the frontend and on the backend.

**Comment by aocenas** [comment]
@ryantxu 
> I think the solution is to convert to DataFrame... then if a string field exists we can use logs, and if a numeric field exists, it can use graphs.

Not sure what you mean by this. The flow is you can create a panel by first choosing visualisation and then going to query editor. The query editor itself can be hardcoded to do logs or metrics query (elastic case). So you are not able to glean anything from the response data because you either do not have it yet or the query editor already affects the query result.

**Comment by Theoooooo** [comment]
Changes got approved, hope to see this one fixed in 6.5 (:
