### ISSUE TITLE
First-time-user documentation missing how to actually add a graph

### ISSUE THREAD

**Issue by FauxFaux** [grafana/grafana#1978]
Neither the [getting started page](http://docs.grafana.org/guides/gettingstarted/) or the [add datasource page](http://docs.grafana.org/datasources/graphite/) explain clearly how to actually add the first graph, which I found confusing and stressful.

After adding a data source, you in fact need to:

1. Go back to the Dashboards page
2. Click the "Home" button at the top
3. Find the small "new" button at the bottom
4. Find the tiny green thing that isn't a button on the left (which is kind of explained by the getting started page, if you read it carefully enough)
5. Add panel
6. New graph
7. Click the title (admittedly labeled "click me")
8. Click Edit

I managed to work this out eventually, but I would rather it had been covered in the quickstart.

**Comment by torkelo** [comment]
I agree, the getting started docs & experience needs to be improved. There is also a beginners guide to building dashboards: https://www.youtube.com/watch?list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2&v=sKNZMtoSHN4
