### ISSUE TITLE
Can't update time range with HTTP API

### ISSUE THREAD

**Issue by danielhuang1991** [grafana/grafana#19786]
**What happened**:
Can't update time range with HTTP API

**What you expected to happen**:
I wish to update the default dashboard time range with a pair of 'from' and 'to' variables (like  2019-09-07T11:50:26.046Z) without having to manually pick it on the right top corner menu
![image](https://user-images.githubusercontent.com/43122012/66709476-df2a2000-ed2a-11e9-889e-604a9d57b5af.png)  or zoom it several times to my targeted range

**How to reproduce it (as minimally and precisely as possible)**:
This is one fo the JSON data I posted to 'IP:3000/api/dashboards/db' and it got "status: success" as a response.
But there is nothing happened with the time range, most likely it will stay at 'last 6 hours'
`{
  "dashboard": {
    "id": 9,
    "uid": "sAg1PgTZz",
    "title": "myTest",
    "tags": "templated1",
    "timezone": "browser",
    "schemaVersion": 19,
    "version": 12
  },
    "time": {
    "from": "2019-09-07T11:50:26.046Z",
    "to": "2019-09-07T11:54:24.774Z"
  },
	"folderId": 0,
	"overwrite": true
	}
`
**Anything else we need to know?**:
Why do I need this feature?  I need to frequently change the data sources ( different 'databases' but all MySQL) and the data need to be visuialized is in different time, for example A is last 6 hours , B might be 31 days ago.... 
I already made it available to change the data source but without the time range, it would most likely showing ' data points outside time range' 
![image](https://user-images.githubusercontent.com/43122012/66709794-0ab00900-ed31-11e9-8644-21c85ae1c1a9.png)

**Environment**:
- Grafana version: v6.3.2
- Data source type & version: MySQL 5.5.59
- OS Grafana is installed on:  Ubuntu 14.04
- User OS & Browser: Windows7 FF & Chrome
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
the UI uses the same API so you can clearly update the dashboard default time range using the API. 

Make sure your query is using the time filter macro, and compare the API request the UI makes to what you are trying to do yourself.

**Comment by danielhuang1991** [comment]
Hi Torkelo,
Thanks for replying

which API are we talking about here ? the following one?
`POST /api/dashboards/db HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
  },
  "folderId": 0,
  "overwrite": false
}`

I am switching among the databases using the API to update the data sources and I don't see any way to update the time range https://grafana.com/docs/http_api/data_source/ 

Could we please specify it a little bit more? Appreciated.

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/66739950-35ee4180-ee72-11e9-9776-0b1395516f9d.png)


Just include the time property in the dashboard json. Then reload the dashboard (in the browser)

**Comment by danielhuang1991** [comment]
@torkelo 
But this is change is still on the UI page side, right?
I found it in 'Dashboards/Settings/JSON Model'
Is there an API I could POST to change these features?

**Comment by torkelo** [comment]
yes. 
POST /api/dashboards/db
