### ISSUE TITLE
Pie Chart is not Working for grafana 6.4.2

### ISSUE THREAD

**Issue by ukkathva** [grafana/grafana#19791]
**What happened**: Upgraded from 6.2.5  to 6.4.2  and pie Piechart started appearing as blank tables

**What you expected to happen**:   to load pie chart load normally to previous versions 

**How to reproduce it (as minimally and precisely as possible)**:   

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.4.2 
- Data source type & version: PostgreSQL 11
- OS Grafana is installed on: ubuntu 18.4  with Dokcer
- User OS & Browser:  Windows 10 /Chrome / Firefox / Edge
- Grafana plugins: Pie Chart 1.3.6
- Others:
![Capture](https://user-images.githubusercontent.com/56521708/66723557-dba3af80-ee76-11e9-93eb-16eada8f0a6a.PNG)

**Comment by papagian** [comment]
You need to update the pie chart plugin.

**Comment by torkelo** [comment]
Yes, update to latest version of pie chart plugin

**Comment by ukkathva** [comment]
Update fixed the issue  💯  , Thanks for the Swift response,
