### ISSUE TITLE
Explore: unrecognized uppercase log level

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#19797]
**What happened**:

The explore section with Loki data source doesn't recognize log levels if they're upper case. For example, a log entry with the label `level="info"` is correctly categorized as `info` while `level="INFO"` is categorized as `unknown`.

**What you expected to happen**:

I would expect log levels to be case insensitive (ie. internally force the `level` to lowercase).

**How to reproduce it (as minimally and precisely as possible)**:

1. Ingest two log entries into Loki, one with `level="info"` label and the other one with `level="INFO"`
2. Open the explore section and search by `{level=~"info|INFO"}`

**Environment**:
- Grafana version: `6.4.2`
- Data source type & version: Loki `master`
- OS Grafana is installed on: Linux
- User OS & Browser: OSX / Chrome 77.0

**Comment by ivanahuckova** [comment]
Fixed in https://github.com/grafana/grafana/pull/21646
