### ISSUE TITLE
Component responsiveness solutions

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#19792]
Right now most of our responsive approach relies on media queries but those only target viewport width. With more complex layout like split panes in Explore, or resizable panels this does not work very well.

In Explore there is a [ResponsiveButton](https://github.com/grafana/grafana/blob/4bd00491bd4b8c7f8ad1e865df758dc32b1b8044/public/app/features/explore/ResponsiveButton.tsx#L36) which needs explicit `split` prop in addition to media queries to decide on layout but this still does not tell you how much space there is. In dashboards [some panels](https://github.com/grafana/grafana/blob/81dd57524d79813bd94c4570e61cef63d9f1248b/packages/grafana-ui/src/components/BigValue/BigValue.tsx#L40) compute layout based on explicit `width` prop.

In ideal world we could use [container queries](https://wicg.github.io/container-queries/) but as they are not supported there are some JS based solution that could achieve similar results. Good summary of the general approach is [here](https://philipwalton.com/articles/responsive-components-a-solution-to-the-container-queries-problem/) example of [react HOC](https://github.com/d6u/react-container-query)

**Comment by Estrax** [comment]
Great idea. Support for [Resize Observer](https://caniuse.com/#feat=resizeobserver) is a little bit better now on desktop, though the biggest issue is mobile, where only Chrome on Android and Android system browser supports that.
