### ISSUE TITLE
Date / time convert

### ISSUE THREAD

**Issue by rguptarg** [grafana/grafana#19801]
HI Team,

I have date in startdate (int, seconds) format, startdate=1544467481i.

We need to convert this into Date format (DD-MM-YYYY) IST format under Table Panel.

Grafana - V6.4.1
Source - InfluxDB/Telegraf

**Comment by papagian** [comment]
Can you share the response of the InfluxDB/Telegraf? Thanks!

**Comment by rguptarg** [comment]
startdate (int, seconds) =1544467481i.

**Comment by rguptarg** [comment]
x509_cert,IP=10.3.168.103,application_name=UNOC_Mycom,common_name=prod-master04.shift.enoc-airtel.com,host=prod-master04.shift.enoc-airtel.com,source=/etc/etcd/peer.crt age=26671077i,enddate=1702147481i,expiry=131008922i,startdate=1544467481i 1571138559000000000

**Comment by rguptarg** [comment]
issue is resolved by multiplied by 1000

"startdate" *1000

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
