### ISSUE TITLE
Alert: Trigger alert when there is no data for source.

### ISSUE THREAD

**Issue by dream4r1** [grafana/grafana#19806]
**What happened**:
Alert did not trigger.
**What you expected to happen**:
It should have triggered atleast a alert even though it might not clear.

**How to reproduce it (as minimally and precisely as possible)**:
`Failing alert query => cassandra_cache_hitrate{job=~".*cassandra"}`
vs
`Successful alert query => cassandra_cache_hitrate {job=~".*cassandra",host="node1"}
`
The difference between the above query is the 1st one display output for alot of hosts and second only for a host.

Alert Critieria
![image](https://user-images.githubusercontent.com/24828762/66778209-13235380-ee99-11e9-941e-9d4dce7cf652.png)

**Environment**: 
- Grafana version: 5.2.4. And the issue exist on latest version as well tested it.
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

**Comment by marefr** [comment]
Please change your dashboard time range to last 5 minutes (given `query (D, 5m, now`) and use the query inspector for the Query D and include request and response here.

**Comment by dream4r1** [comment]
@marefr - Is this information sufficient ?

**Comment by marefr** [comment]
@dream4r1 no I don't think so. The query used in the information you provided is for `count(mysql_flush_commands) by (host,job)` and not `cassandra_cache_hitrate{job=~".*cassandra"}` or `cassandra_cache_hitrate {job=~".*cassandra",host="node1"}`. 

Maybe a bug that query inspector doesn't show the right result. Can you use the eye-icon and disable each query besides the `D` one? 

Thanks

**Comment by dream4r1** [comment]
@marefr - Its just the metrics name change but the behavior is the same it does not work for any metrics. I did used mysql_flush_commands because cassandra one was outputing more hosts which I need to scramble before uploading here.

**Comment by dream4r1** [comment]
[query_ins.zip](https://github.com/grafana/grafana/files/3757073/query_ins.zip)
Anyway uploaded for the same metrics.

**Comment by torkelo** [comment]
could not find any series the with no values in the result
