### ISSUE TITLE
plugin not found when using auth proxy

### ISSUE THREAD

**Issue by laundmo** [grafana/grafana#19811]
**What happened**:
When using Auth Proxy with HTTP basic auth, grafana fails to load plugins that are avaliabe when accessing grafana without the auth proxy.

**What you expected to happen**:
Plugins should be avaliable with any authentication method.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up auth proxy according to https://grafana.com/docs/auth/auth-proxy/
2. Install a plugin and use it in a dashboard (seems to be the case with any panel plugin)
3. Acces the dashboard through the auth proxy with http basic authentication

**Anything else we need to know?**:
Im using a iframe to embed a kiosk dashboard, so far everything works without problems except plugins.
**Environment**:
- Grafana version: Grafana v6.3.6 (fdd2117)
- Data source type & version: Does Not Apply
- OS Grafana is installed on: Raspbian Lite 10 (Buster)
- User OS & Browser: Windows 10, Firefox 69.0.1
- Grafana plugins: grafana-clock-panel, agenty-flowcharting-panel (these are the ones i tested)
- Others:  Apache server: Apache/2.4.33 (Linux/SUSE)

**Comment by papagian** [comment]
I'm unable to reproduce it with nginx and the clock panel.
Which auth proxy do you use? Could you share the configuration?
Thank you

**Comment by laundmo** [comment]
@papagian following is the relevant apache config, domains/ips have been redacted/changed.

```
# redirect to https
<Virtualhost *:80>
  ServerName grafanaserver.domain
  RedirectPermanent / https://grafanaserver.domain
</Virtualhost>

<Virtualhost *:443>
  ServerName grafanaserver.domain

  SSLEngine On
  SSLCertificateFile REDACTED
  SSLCertificateKeyFile REDACTED

# Always set these headers.
  Header always set Access-Control-Allow-Origin "REDACTED"
  Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
  Header always set Access-Control-Max-Age "1000"
  Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client
  # Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request.
  RewriteEngine On
  RewriteCond %{REQUEST_METHOD} OPTIONS
  RewriteRule ^(.*)$ $1 [R=200,L]

    <Proxy *>
        AuthType Basic
        AuthName GrafanaAuthProxy
        AuthBasicProvider file
        AuthUserFile /etc/apache2/grafana_htpasswd
        Require valid-user

        RewriteEngine On
        RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
        RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"
    </Proxy>

    RequestHeader unset Authorization

    ProxyRequests Off
    ProxyPass / http://192.168.0.2:3000/
    ProxyPassReverse / http://192.168.0.2:3000/

</Virtualhost>
```

i hope this helps

**Comment by torkelo** [comment]
You need to exclude grafana's /public dir from basic auth so it can load content files (loaded without auth header (browser standard behavior)
