### ISSUE TITLE
How to select values today from influx?

### ISSUE THREAD

**Issue by sc0rp10** [grafana/grafana#1981]
Hi.
I need ge values today with query like "select sum(value) from series_name where time > '2015-05-10'". How can i get this with Grafana 2.0?
Thanks.

**Comment by torkelo** [comment]
put in series name in the series_name filed. select sum from the influxdb function selection, select last day from time range selector at the top or select custom to enter a fixed time range (or select last 2 days and use the mouse to select the range). 

The query that the Grafana query editor will generate looks like this:
`select sum(value) from series_name where $timeFilter order asc`
