### ISSUE TITLE
No cross button to remove Functions in Queries

### ISSUE THREAD

**Issue by Q-nu** [grafana/grafana#19817]
**What happened**:
Further update of Grafana, I noted that the cross button to remove functions in queries is not available. I cannot remove the functions... It's annoying...

**What you expected to happen**:
I expect that it woks as before :)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![2019-10-15 11-44-11](https://user-images.githubusercontent.com/36386156/66821715-2be84380-ef43-11e9-858a-d5c02ffd0d23.png)

Try with several browsers like : Brave, Chrome, Firefox 
**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Zabbix 4.0.5
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Firefox, Chrome, Brave
- Grafana plugins: Zabbix
- Others:

**Comment by papagian** [comment]
This issue is fixed [here](https://github.com/alexanderzobnin/grafana-zabbix/issues/810) and it will be included in the next version of the Zabbix plugin.
