### ISSUE TITLE
Loki template variable query not working

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19826]
**What happened**:

When using a Loki datasource for a template variable query I'm getting an error. 

eg: `label_names()` or `label_values(level)`.

**What you expected to happen**:

Loki support label names and values queries so we should be able to support Loki datasource for template variable query.

see :
- https://github.com/grafana/loki/blob/master/docs/api.md#get-lokiapiv1label
- https://github.com/grafana/loki/blob/master/docs/api.md#get-lokiapiv1labelnamevalues

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/1053421/66839621-b4abb300-ef34-11e9-947c-44108452249d.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.0-pre (14cf2a3)
- Data source type & version: Loki

/cc @aocenas @davkal

**Comment by aocenas** [comment]
`metricFindQuery` is [optional method](https://github.com/grafana/grafana/blob/bbf2bd18fd44b2f09a8a5e730b2145aa72fdcd01/packages/grafana-ui/src/types/datasource.ts#L223) that is not implemented for Loki yet.
