### ISSUE TITLE
FR: using a timeshift override for custom absolute time ranges

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#19828]
**What would you like to be added**:

Allow using the panel relative time override for a custom absolute time range.
Now it's working with relative time ranges only.

![Screenshot_20191015_175745](https://user-images.githubusercontent.com/25184101/66843360-55ba5e00-ef75-11e9-8bf8-a74d2e76c14c.png)

**Why is this needed**:
It would allow to analyze a period smaller than what is set for a dashboard.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/15829
