### ISSUE TITLE
stack by sign

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#19827]
**Why is this needed**:

I'm graphing deltas of memory used over a given period of time which results on having positive or negative values.

As it's a volume I choose to display it with bars and stack it.

Unfortunately when there are negative values the stacking produces unexpected results.

<img width="1656" alt="k8s-pods-2-thanos_-_Grafana" src="https://user-images.githubusercontent.com/153052/66843594-40413600-ef6d-11e9-907e-83d29a0cc17f.png">

**What would you like to be added**:

I would like a stack option that would stack values by sign to mitigate graphing deltas that can be either positive or negative.

**Comment by Eraac** [comment]
The problem also occurs when you've a series overrides with `transform: negative-Y`

without stack
![image](https://user-images.githubusercontent.com/5497623/88040447-33c7ba80-cb49-11ea-9e5f-50b615dc30d8.png)

with stack
![image](https://user-images.githubusercontent.com/5497623/88040457-388c6e80-cb49-11ea-8cec-2a8b817a885f.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
