### ISSUE TITLE
Snapshots API does not keep data regardless of expires parameter

### ISSUE THREAD

**Issue by Lennac** [grafana/grafana#19831]
On my Grafana dashboard  all data is stored and remains viewable for 7 days unless a Snapshot of the time frame is created via the Share Dashboard and Snapshot tool. The hope was to create a script that automatically creates snapshots using the API instead. However, they still "expire" after 7 days. Rather, the snapshot URL still works, but the graphs are now empty as the data is no longer there.

I'm wondering what the specific differences are between manually creating a snapshot through the Grafana UI from the dashboard, and creating a snapshot through the API and what needs to be added or changed so that the data that populates the Grafana snapshot is stored, rather than just pulling the data from the liver Grafana board and then giving me the time frame of the snapshot.

When investigating how a local snapshot is created, the data is made through POST requests to the datasource API. However, I'm unable to find a way to manually inject the response of these datasource calls from the API into the snapshot using on the APIs.

**Comment by papagian** [comment]
Thank you for reporting this.
Could you provide some additional information.
- Which datasource you are using?
- What do you mean by "expiring"? Cannot you see the data if you switch in a time range more than 7 days back?
- Could you send the request for creating the snapshot using the API and also the output of [this](https://grafana.com/docs/http_api/snapshot/#get-snapshot-by-key) API call for the snapshot after it has been created?

Ideally we would like you to include also the following information:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:

**Comment by torkelo** [comment]
To create snapshots via API you need to manually add the snapshotData to every panel in the dashboard json. 

Creating snapshot with data is not possible via api as the snapshot creation logic is done in the browser where all panels embedd their data into their model before the snapshot is stored.

**Comment by Lennac** [comment]
That's what I assumed, but I wanted to confirm that I wasn't missing anything. Thank you for the replies.

**Comment by sahithiy** [comment]
Hi @torkelo 

I started looking into creating snapshot using API and found this workaround - https://github.com/grafana/grafana/issues/3713

However I am able to create snapshot with all metric data without adding snapshot data to every panel. 

1. I queried for base schema using `/api/dashboards/uid/123`
2. In the output json i changed time range to required from and to values
```        "time": {
            "from": "now-3h",
            "to": "now"
        }```
3. I made a POST request to `/api/snapshots` with this input body
4. I opened the snapshot url in browser, and it has all the metric data loaded in it. 

I am confused. Can you please explain what I am missing.

**Comment by wen-zheng** [comment]
It is 2025， and this problem still exists.
