### ISSUE TITLE
Make it possible to provision users

### ISSUE THREAD

**Issue by Anonymous-Coward** [grafana/grafana#19848]
**What would you like to be added**:

Add a possibility to provision orgs and users with passwords and permissions, not just the super-admin, via configuration.

**Why is this needed**:

In this deployment context:
- grafana deployed from a continuous integration pipeline
- grafana setup spanning multiple organizations
- grafana deployed behind an authentication/authorization proxy

It is labor intensive and error prone to replicate all the org and user management performed in whatever directory system the auth(n|z) proxy uses in grafana.

Simplest thing to do is to be able to provision a structure of orgs and users inside grafana with one user provided with desired combinations of permissions, by org, have the proxy add a corresponding basic auth header to proxied requests, and have grafana only ever know about these provisioned orgs and users.

In such a scenario, everything in grafana will be read-only, since the CI pipeline should be the one controlling everything that gets deployed, including dashboards and data sources, so there is no point in using specific users for access to track changes - there simply won't be any changes.

Right now, the only way to do this is by having the CI pipeline configure everything via the HTTP API, after grafana was redeployed and started. This is cumbersome.

**Comment by wyxa** [comment]
https://grafana.com/docs/grafana/latest/http_api/user/
Here I don't see any endpoint for creating users.
Can we actually create users via the HTTP API?
or is there any other way to do it automatically after a deployment?

**Comment by wyxa** [comment]
Sorry, just found it here:
https://grafana.com/docs/grafana/latest/http_api/admin/#global-users

**Comment by bergquist** [comment]
We decided to close this issue. Grafana already supports multiple authentication providers which we consider a better way to manage users rather than managing this via provisioning.

Each feature adds to the maintenance burden of Grafana. Too much maintenance means we don't have time to develop any new features or properly maintain the current features. While I understand that you find this frustrating, I hope that you understand our decision.

If you have a specific reason why you want to provision users rather then using the auth providers I would appreciate the feedback in this issue.

**Comment by Anonymous-Coward** [comment]
How do you manage grafana-specific groups in directories you don't control?

**Comment by Hronom** [comment]
> If you have a specific reason why you want to provision users rather then using the auth providers I would appreciate the feedback in this issue.

For example to use Crossplane `provider-grafana` to connect to the self managed grafana instance and use credentials of provisioned user to create RuleGroup, Dashboards, ContactPoint, NotificationPolicy etc.

Of if this provider will have a possibility to use service account - then we need provisioning of service account.
