### ISSUE TITLE
grafana/toolkit: Allow to strip console.log when building 

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#19841]
**What would you like to be added**:
when building the final plugin artifact, I can run `yarn build --strip-console` (or something like that) to strip out the console log statements.

**Why is this needed**:
It is good to have console log during dev time so more insights about what is happening, but in production extraneous log pollute the console. I want to keep my console log statements in the code while not seeing them when compile with webpack production set to true.

**Comment by grantlouisherman** [comment]
hey @dprokop @fredwangwang hey could I look at this?

**Comment by jpmcb** [comment]
Hey @fredwangwang just stumbled onto this - Is this something you still need? I have time and would be able to work on this! @dprokop

**Comment by fredwangwang** [comment]
I still think it is nice to have -- though I am not developing any plugins
at the moment, someone else might find it useful in the future. So if you
are interested, go for it 😀

**Comment by thedeveloperr** [comment]
Assigned to anyone ?

**Comment by ryantxu** [comment]
patches are always welcome :)  Not assigned to anyone and likely will not be unless someone steps up to do it

**Comment by surya-id** [comment]
help me
