### ISSUE TITLE
Missing Grafana oauth cookie

### ISSUE THREAD

**Issue by FStefanni** [grafana/grafana#19844]
**What happened**:

Deal all,

I have a strange behavior with Grafana and oauth (Keycloak), similar to other questions seen around. I have also posted to the forum, but I got no answer.

I have managed successfully to configure Grafana with oauth for Keycloak.
So when I try to access Grafana directly, it redirects me to Keycloak login, and after login, I am redirected correctly to Grafana.
During this process, some cookies are created, and the relevant one is named “oauth_state” (there is also a “grafana_session” cookie, I do not know if it is relevant).

I also have embedded some Grafana panels via iframe into a website, which uses the same oauth login.
The strange behavior is the following.

If, before going to the website, I visit Grafana and do login, the cookie is created, and when I go to my website I am able to see the panels (without re-login to the site, due to SSO).
Conversely, if i go directly to my website and do the login (to the site), when I access the page with the iframes, I cannot see the Grafana panels, since the cookie is missing. The error I have is “login.OAuthLogin(missing saved state)” as in the other similar posts.

I have also tried to embed the whole Grafana in the website (just for testing), but the behavior is the same.

So I wonder if:

1. Is this a Grafana bug? Or am I missing something?
2. If this is an unsupported scenario/missing feature, is it possible to implement a workaround?

Btw, I am using Grafana 6.4.0 (as docker container).
Thank you

**What you expected to happen**:

I am expecting oauth to work also for grafana embedded into iframes: for the whole grafana, but also for single panels or dashboards.

**How to reproduce it (as minimally and precisely as possible)**:

As described before, it is possible to configure Keycloak and Grafana for oauth/SSO, but also a website embedding Grafana is required. During Grafana configuration, remember to add options as coockie_samesite and cookie_secure, as described in other Grafana issues and in Grafana forum.

**Anything else we need to know?**:
Here there is the link to my question in the forum:
https://community.grafana.com/t/missing-grafana-oauth-cookie/21899

**Environment**:
- Grafana version: 6.4.0 
- Data source type & version: docker
- OS Grafana is installed on: docker on ubuntu 18.04
- User OS & Browser: both Liniux and Windows. Firefox
- Grafana plugins: none
- Others: none

**Comment by marefr** [comment]
Closing this since it's a question and Github are mainly for feature requests and bug reports.

**Comment by Krishnakanth94** [comment]
issue seems to be from grafana side.

**Comment by NingPekin** [comment]
I have the same issue. Can we reopen the ticket?

**Comment by marefr** [comment]
@NingPekin please open a new bug report if you have proof this is a Grafana problem.
