### ISSUE TITLE
Snapshot list

### ISSUE THREAD

**Issue by dvenza** [grafana/grafana#1984]
I would like to have a snapshot list where I could look at the available snapshots, delete them or change the expiration time. The user should also be able to retrieve the link for sharing from such list.

Snapshots are very useful for training or for comparing different experiments done at different points in time, but without a list the user is forced to copy and paste the link in some wiki or something to keep track of the snapshots.

See also: #1985

**Comment by shoonoise** [comment]
:+1:

**Comment by Alarmfifa** [comment]
+1 
it would be great, if snapshot has a title or some description.

**Comment by christianchristensen** [comment]
:+1:

**Comment by utkarshcmu** [comment]
+1

**Comment by utkarshcmu** [comment]
@torkelo / @bergquist Is a PR welcome for showing saved Snapshots as shown below?

<img width="586" alt="screen shot 2016-01-17 at 3 35 07 am" src="https://cloud.githubusercontent.com/assets/1019609/12377242/71e5cdfc-bccb-11e5-8364-8e12f2854081.png">

**Comment by torkelo** [comment]
Yes!

**Comment by axos88** [comment]
+1

**Comment by utkarshcmu** [comment]
@axos88 already implemented this feature in #3792 , waiting for the PR to get merged now. Hopefully this makes in 3.0.

**Comment by mtanda** [comment]
The PR is merged. can be closed this issue.
