### ISSUE TITLE
grafana 6.4.X do not work datasource clickhouse 

### ISSUE THREAD

**Issue by wadomon** [grafana/grafana#19856]
grafana 6.4.X do not work datasource clickhouse 

error
Error: ace is not defined Evaluating http://grafana.adsrv.wtf/public/plugins/vertamedia-clickhouse-datasource/module.js Loading plugins/vertamedia-clickhouse-datasource/module

OS Ubuntu 16.04.6, 18.04.3

**Comment by papagian** [comment]
There is [an open pull request](https://github.com/grafana/grafana-plugin-repository/pull/496) addressing this kind of compatibility issues in 6.4.x
