### ISSUE TITLE
Explore: Long log line triggers an error when scrolling down.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19869]
**What happened**:
If Loki contains a huge log line, when scrolling down, the whole log panel disappears and shows a red error as below:

![image](https://user-images.githubusercontent.com/1053421/66947198-7c819e80-f020-11e9-80b8-98f1db82581c.png)

The message at the end read:`RegExp too big`

**What you expected to happen**:
I should still be able to cro

**How to reproduce it (as minimally and precisely as possible)**:

I've shared a link where this happens.

**Anything else we need to know?**:

It seems to be triggered by the scroll event, if I don't move everything looks fine :)

**Environment**:
- Grafana version: Grafana v6.5.0-pre (55d7fbf)

**Comment by aocenas** [comment]
We do some regex parsing for highlighting and also to parse individual fields, we should probably skip this for too big lines.
