### ISSUE TITLE
DataLinks: in 6.4.3, the url field still doesn't release focus despite #19804

### ISSUE THREAD

**Issue by siebenmann** [grafana/grafana#19868]
**What happened**:

I was creating a datalink (well, trying to create) in 6.4.3 and after I started entering the URL, I could only add one character to the Title field before focus switched to the URL field. This is despite pull #19804 theoretically fixing this issue.

**What you expected to happen**:

After starting to enter the URL, I could switch back to the Title field and enter (and update) a title there.

**How to reproduce it (as minimally and precisely as possible)**:

Start adding a data link. Enter text in the Title field; it works fine. Switch focus to the URL field and type one character. Now switch focus back to the Title field and try to type more characters.

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Prometheus 2.13.0
- OS Grafana is installed on: Ubuntu 18.04 (64-bit)
- User OS & Browser: Fedora Linux 30 (64-bit), Official Mozilla.org Firefox 69.0.3 
- Grafana plugins: flant-statusmap-panel  natel-discrete-panel

**Comment by MacroPower** [comment]
I would like to add that the Bar Gauge also does not work with https://github.com/grafana/grafana/pull/18918

Which should have been added in 6.4.0-beta1

I can reference labels (and do ctrl+space suggestions) in all other panels but this one.

Not sure if this is related or not, but it seems like the the data links on this panel are behaving in line with pre 6.4 builds.
