### ISSUE TITLE
`allowed_domains` OAuth setting doesn't make sense for GitHub

### ISSUE THREAD

**Issue by mastahyeti** [grafana/grafana#1986]
GitHub does not force email validation. This configuration setting might mislead users into thinking that they can restrict access to Grafana by requiring `@mycompany.com` email addresses when using GitHub as an OAuth provider.

**Comment by erikankrom** [comment]
Github does not "force" email validation?  
![screen shot 2015-05-14 at 4 33 56 pm](https://cloud.githubusercontent.com/assets/69351/7642511/32dcf216-fa57-11e4-9512-56dfd6c45ea9.png)

I haven't tested against OAuth, but the screenshot above would seem to indicate email validation exists in some manner.  Are you saying it shows unvalidated emails when trying to authenticate with OAuth?

**Comment by mastahyeti** [comment]
Yeah, the API returns email addresses, regardless of whether they have been verified. People shouldn't rely on these email addresses actually belonging to the owner of the GitHub account.
