### ISSUE TITLE
Multi-select template variable not generating the correct logQL in Log Panels

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#19864]
**What happened**:

- Created a variable drop-down, where I can select 1+ value. For example: web_app_1 and web_app_3. This will generate the following 

{service=~"{web_app_1,web_app_3}"}

and this is not valid LogQL

**What you expected to happen**:

That it generated {service=~"{web_app_1|web_app_3}"}

**How to reproduce it (as minimally and precisely as possible)**:

- create a service variable drop down with multiple labels, and select a few of the options. \
- have a log panel with loki as a datasource with a logQL query like: {service=~"[[service]]"}
- no results show, but will show invalid logQL exceptions in red alert boxes.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
master
- Data source type & version:
loki, lastest
- OS Grafana is installed on:
OSX
- User OS & Browser:
Safari
- Grafana plugins:
- Others:

**Comment by negbie** [comment]
Take a look at Advanced Formatting Options here
https://grafana.com/docs/reference/templating/

You should try something like {service=~"${service:pipe}"}

**Comment by torkelo** [comment]
Loki needs to use the same template interpolation handling as Prometheus, looks like that was missed. Ping @davkal
