### ISSUE TITLE
Improve bar gauge / gauge naming for table data (where name is seperate column)

### ISSUE THREAD

**Issue by tsavasci** [grafana/grafana#19860]
How can I name the bar gauge series in query?

> SELECT xxx as "bbb"
> FROM Database
> WHERE code='xxxxx'

**Comment by torkelo** [comment]
Currently it's a bit tricky, you can refer to other columns as the name of the series using ${_cell_x}

x is the column number

**Comment by tsavasci** [comment]
Grafana v6.4.2 (commit: 443a0ba)
Microsoft SQL Server

**Comment by tsavasci** [comment]
its ok....


![image](https://user-images.githubusercontent.com/24454634/66928233-bdd27800-f039-11e9-97d6-a8104e1aed11.png)



Title must be

` ${__field.name} `

 and query must be

```
SELECT xxxxxxx as 'Stok' FROM xxxxxxxxx WHERE xxxxxx=xxxx
```
