### ISSUE TITLE
Logs panel: Explore shortcut `x` is not an item in panel menu

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#19865]
**What would you like to be added**:
**Why is this needed**:

Jumping to explore shortcut `x` is awesome, but it's not present as a panel menu item (like view/edit/share/etc.. in the 6.5.0-pre build. Adding this option, will improve the discoverability of this feature.

**Comment by davkal** [comment]
At first glance this needs to be added to https://github.com/grafana/grafana/blob/c674fa1d794c2b3ef7b9ba51b977c581237f3cc6/public/app/features/dashboard/utils/getPanelMenu.ts#L9

A couple of problems:

- it's a function that no longer has access to `timeSrv` and `datasourceSrv`
- the new `PanelMenuItem` no longer supports hrefs, to we can't have the desired flow of opening explore in a new tab
- only some panels should be able to inject the link, how do we create a positive list that is allowed? One heuristic could be to check for the existence of `panel.targets` which would imply query rows.

Any guidance @torkelo @dprokop ?

**Comment by dprokop** [comment]
> it's a function that no longer has access to timeSrv and datasourceSrv which are both needed to produce a proper Explore URL

`DatasourceSrv` is available as a singleton instance from `grafana-runtime` so can be used in a function that creates explore's URL. `TimeSrv` is also available as a singleton instance (`import { getTimeSrv, TimeSrv } from 'app/features/dashboard/services/TimeSrv';`)

> the new PanelMenuItem no longer supports hrefs, to we can't have the desired flow of opening explore in a new tab
Two options, either implement support for `href` in `PanelHeaderMenuItem` or implement cmd+click in Explore's item `onClick` handler. Personally i would probably go for `href` support. If `onClick` is present in item's model then it would take precedence.

**Comment by hugohaggmark** [comment]
First iteration to get this into 6.5 will be without changing `PanelHeaderMenuItem` and using existing `onClick` handler.
