### ISSUE TITLE
Incorrect Lines in graph

### ISSUE THREAD

**Issue by VasilyPechersky** [grafana/grafana#19872]
Lines between dots in query from MsSql not going correctly.

Resulting output of query in table is correct.
![Grafana3](https://user-images.githubusercontent.com/35377787/66988903-ffabfe80-f0cb-11e9-933d-c2c2112a1a46.png)

When Draw mode is dots - data looks as expected.
![Grafana1](https://user-images.githubusercontent.com/35377787/66988773-bcea2680-f0cb-11e9-842e-c747617f8b74.png)
When you trigger lines - random connections between dots.
![Grafana2](https://user-images.githubusercontent.com/35377787/66988886-f4f16980-f0cb-11e9-885c-cd885242afd6.png)

**Environment**:
- Grafana version: Grafana v6.4.3 (commit: 3a2bfb7)
- Data source type & version: mssql 2008
- OS Grafana is installed on: Ubuntu 16.04.6
- User OS & Browser: Ubuntu 14.04 / chrome 73, win 10 chrome 77/edge 44.176637710/ explorer 11.8
- Grafana plugins:

- Others:

**Comment by torkelo** [comment]
make sure you sort your data by time asc
