### ISSUE TITLE
~ symbol is not their in Single stat graphs so its not showing the graph

### ISSUE THREAD

**Issue by Yashwantbokadia** [grafana/grafana#19873]
In Normal graphs ~ symbol is there in front of the IP and the job name automatically in the query, but in the singlestat it is not their so that graphs are not working. 
Grafana is of Latest version
Datasource is Prometheus
for reproducing transfer the IP in the singlestat it will not work, if you type manually ~ sign before the double quotes it will work.

My query:
{instance=~"172\\.20\\.0\\.14:9500",job="node_exporter"} ----> it will work
{instance="172\\.20\\.0\\.14:9500",job="node_exporter"} ----> it will not work

**Comment by marefr** [comment]
Not sure I understand what you mean. Is the query working when you not use it in a singlestat panel, but works in graph panel for example? The `~` symbol denotes you're using a regular expression. Does `{instance="172.20.0.14:9500",job="node_exporter"}` work?

**Comment by Yashwantbokadia** [comment]
In singlestat without ~ symbol it's not working but in simple graphs, it's working.

**Comment by marefr** [comment]
Please use the query inspector and include request/response here of the working query and the non-working query.

**Comment by torkelo** [comment]
closing due to lack of update
