### ISSUE TITLE
How to resize Loki Log label panel in Grafana Explore

### ISSUE THREAD

**Issue by Alexvianet** [grafana/grafana#19877]
I have added hostip as the label in promtail and get:
![Screenshot from 2019-10-17 10-45-26](https://user-images.githubusercontent.com/17483589/66988493-49e0b000-f0cb-11e9-8e1e-80274188ffe6.png)

How to resize panel to see full IP address, just for making it pretty.
Thanks

**Comment by davkal** [comment]
@Alexvianet we're getting rid of the labels column in 6.5 in favor of an expandable row that has all labels in detail.

**Comment by davkal** [comment]
See #17501 and #17831

**Comment by Alexvianet** [comment]
Thanks, waiting for 6.5
