### ISSUE TITLE
Passing template variable names as var_<variable_name>=<value> instead of var-<variable_name>=<value>

### ISSUE THREAD

**Issue by europa502** [grafana/grafana#19871]
Why it is needed-
While adding template variables in a scripted JS dashboard var-<variable_name> cannot be accessed from ARGS object. Instead if var_<variable_name> is used it would be much more convenient as the other url parameters as well as the template variables can be accessed in the same way

**Comment by torkelo** [comment]
Scripted dashboards is kind of a deprecated feature that we want to reimagine some in the future so making changes because of it is not likely.

And this sounds like a bug / issue that can be easily fixed (see not reason why scripted dashboards don’t  have access to all url Params)

**Comment by europa502** [comment]
How else can I access the template variable var-<variable_name> in my JS if not from ARGS? I went through https://community.grafana.com/t/async-dashboards-access-to-templating-variables/6037 , #1078 , #1308 , https://grafana.com/docs/reference/scripting/ and nowhere has it properly mentioned how to access the template variables. As mentioned in #1308 i tried working with ajax but it was a no go.
