### ISSUE TITLE
Alerting: support queries that reference other queries

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#19886]
In cloudwatch if you alert on a query with an expression that references a different query, it does not execute properly.

![1_query_b](https://user-images.githubusercontent.com/705951/67025850-90c6a980-f0bb-11e9-85d6-0bf166aabd54.png)
![2_alert_b](https://user-images.githubusercontent.com/705951/67025848-902e1300-f0bb-11e9-81ca-c74d7c747ca0.png)

**Comment by marefr** [comment]
Is this for CloudWatch or in general?

**Comment by torkelo** [comment]
This would require a bit of a complicated change, so it would be best if we could hold off on this as we are about to start on alerting v2 in Q1

**Comment by Nessworthy** [comment]
👋 Has there been any progress for the alerting v2 work? Couldn't see it on the project or roadmap tickets.

**Comment by bkbwese** [comment]
Took me a while to find this issue, I want to help others find it. For ease of finding this issue via a search engine, the current help text noting the query reference caveat (from the expression field info in the query builder): "Please note that if a math expression that is referencing other queries is being used, it will not be possible to create an alert rule based on this query"

**Comment by droidraja** [comment]
Any update on this ? It is messy to have some alerts in grafana and some in AWS Cloudwatch alerting.

**Comment by crackedupcorson** [comment]
Is this feature available in Grafana v8? We're running V7 in a few locations and I'd like to use this in conjuction with some cloudwatch synthetics.

**Comment by tinder-terrychu** [comment]
Curious about this too. Any updates on the development of this feature?

**Comment by davidmparrott** [comment]
Grafana 8 alerting now allows you to reference other queries when creating alerting rules. I think the best detail is available in the [docs for expressions](https://grafana.com/docs/grafana/latest/panels/expressions/), which also contains a link to the grafana 8 alerting docs.

**Comment by santihernandezc** [comment]
@ryantxu here at the alerting team we're thinking this is an issue for the datasources team. We're redirecting this to them.

**Comment by andresmgot** [comment]
I don't think this is an issue with Unified Alerting. I am able to reference other queries and create an alert:

![Screenshot from 2022-02-08 13-03-05](https://user-images.githubusercontent.com/4025665/152983603-3d6e69ca-fe78-4ef4-976a-9306fd0e807b.png)
![Screenshot from 2022-02-08 13-03-12](https://user-images.githubusercontent.com/4025665/152983598-852ce949-0f67-4268-9ebb-3d902008b1d4.png)
![Screenshot from 2022-02-08 13-03-21](https://user-images.githubusercontent.com/4025665/152983597-fa7a49be-8613-4451-a383-ece1300c1643.png)
![Screenshot from 2022-02-08 13-03-32](https://user-images.githubusercontent.com/4025665/152983596-4d848536-691d-4557-b682-1d91ad9bd0e2.png)
![Screenshot from 2022-02-08 13-03-40](https://user-images.githubusercontent.com/4025665/152983589-cffc3462-267a-47d6-b73f-a811d0af051f.png)

Please, reopen it with more details if you still think this is an issue.
