### ISSUE TITLE
Grafana doesn't run on MacOS 10.5 Catalina

### ISSUE THREAD

**Issue by krolingo** [grafana/grafana#19887]
**What happened**:

Upgraded to Catalina, afterwards grafana fails to run. It was installed with brew. 
upgraded brew, compiled grafana from source, still fails to load.

/usr/local/opt/grafana/bin/grafana-server: /usr/local/opt/grafana/bin/grafana-server: cannot execute binary file 

**What you expected to happen**:
working grafana

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana with Mac brew 
then try to load localhost:3000

**Anything else we need to know?**:

- removed grafana, reinstalled precompiled binary with brew.
- removed again compiled with brew

**Environment**:

- Grafana version: grafana 6.4.2 
- Data source type & version:
- OS Grafana is installed on: macOS Catalina 10.5
- User OS & Browser: Safari
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
strange, maybe something with Golang and this new OS version?

**Comment by ajspera** [comment]
Just getting familiar with this project's stack so not sure if it's relevant, but Catalina dropped 32 bit support.

**Comment by pgdh** [comment]
Having read ...

https://grafana.com/grafana/download?platform=mac

I did the following ...

$ brew update
$ brew reinstall grafana

At which point I had the same problem as krolingo ...

$ file /usr/local/opt/grafana/bin/grafana-server
/usr/local/opt/grafana/bin/grafana-server: data
$

So I extracted the grafana-cli and grafana-server binaries via ...

$ wget https://dl.grafana.com/oss/release/grafana-6.4.3.darwin-amd64.tar.gz
$ tar -zxvf grafana-6.4.3.darwin-amd64.tar.gz

I then copied them into /usr/local/opt/grafana/bin/ (i.e. over the two brew-installed binaries), and I'm up and running again.

**Comment by robertmircea** [comment]
The same behaviour as described occurs on my macos Catalina as well. I've used @pgdh's workaround to make it work again.

**Comment by ankushblue** [comment]
I am installing grafana for the first time on my macbook air. And my OS already updated to macOS 10.15 and i was stuck with exec format error whenever i started grafana.

Localhost:3000 also nothing showed up.

i installed homebrew first
then i installed brew wget
then i did brew update
then i did brew install grafana
then i followed pgdh's process and viola, it now works!

**Comment by natellium** [comment]
Hey there, thanks for the report. We're closing this issue due to it being linked to an old version of Grafana and the lack of activity. If this is still a problem let us know. 👋
