### ISSUE TITLE
Allow key/value in template variables

### ISSUE THREAD

**Issue by victornet** [grafana/grafana#1988]
I would like to use a value list for a graphite query to group hosts. 

Example: 
Template Variable: $clusterhosts 
Value: cluster_a = {host1,host2}, cluster_b = {host[23]}

So i can use this variable in graphite query: 
sys.$clusterhosts.foo.bar

which could be resolved to:
sys.{host1,host2}.foo.bar

and via graphite api to metrics for:
sys.host1.foo.bar
sys.host2.foo.bar

**Comment by Akeru** [comment]
Please also consider allowing multiple select from the variables dropdown in addition of the single / all options.

**Comment by Screatch** [comment]
I completely agree.

In my case, I need to view Cloudwatch Opsworks logs by choosing explicitly opsworks layer id, and I would much rather use some human readable layer name (Such as API) and make it search by predefined value.

Unfortunately long ids such as `7528dc49-5ec0-7c6f-a30e-g9fa6bhf497a` are not intuitive at all in templates. Would love to see that added to Grafana soon.

**Comment by directionless** [comment]
I'm also looking for this. My specific use, is about aggregating metrics. An example... 
I have `servers.$host.cpu` and I have a separate mapping from host to datacenter. I'd like to make a graph that aggregates cpu by datacenter. 

I can create graphtite entries along the lines of `lookup.$datacenter.$host`, but I don't see how to use that.

**Comment by reedboat** [comment]
It has been more than 3 years since the issue is  created, and not been solved yet.

**Comment by farzadpanahi** [comment]
Much needed feature. Is this feature in the road map?
