### ISSUE TITLE
Add dashboard column in Alert Rules

### ISSUE THREAD

**Issue by auntieyi** [grafana/grafana#19891]
**What would you like to be added**:
Add dashboard column in Alert Rules

**Why is this needed**:
We have many dashboards for different projects, add dashboard column is more clear to know the rule that belongs to.

![image](https://user-images.githubusercontent.com/1725966/67058721-a5bd3e80-f188-11e9-83d0-4ef9ebd3ebe8.png)

**Comment by peterholmberg** [comment]
We will be redoing alerting in Grafana for v7.4 (beta and behind feature flag) and v8.0 where alerts won't be tied to a panel or dashboard anymore. So this will not be relevant by then.

**Comment by smyru** [comment]
What is the ticket to watch - the one that supersedes this and likely others?
