### ISSUE TITLE
Datasource for Jamf 

### ISSUE THREAD

**Issue by M1k12** [grafana/grafana#19898]
Is it possible to add a datasource for Jamf?

Jamf is a great product for all Apple users and since a lot people use Apple products for there work it would be nice to also monitor it with Grafana(what works great) . 

https://www.jamf.com

**Comment by papagian** [comment]
It is unlikely that the Grafana team will build a datasource for Jamf in the early future. Maybe you could ask also in the [community](https://community.grafana.com) site for someone to build a plugin for it.
An alternative would be to write an exporter for Prometheus to scrape data from the Jamf API.
Also, [here](https://www.jamf.com/jamf-nation/discussions/28044/dashboard-url) it is an example dashboard that someone has done something similar by saving to Graphite using powershell.
