### ISSUE TITLE
Github Authentication not working

### ISSUE THREAD

**Issue by mgravlin** [grafana/grafana#1989]
I am trying to get Github authentication working, but cannot get it to work.Running version 2.0.2. I setup my github application, entered the client ID and client secret in the config and used http://grafana.example.com:80/login/github as the callback url. I am running Grafana on port 80 by binary permission.

Config:
#################################### Github Auth ##########################
[auth.github]
enabled = true
client_id = fakef85240ab4b24fake
client_secret = fakecc979f5245eec3c78c94d1a2eaecc3bbfake
;scopes = user:email
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
;api_url = https://api.github.com/user
; allowed_domains = mycompany.com othercompany.com
allow_sign_up = true

Every time I try to authenticate or signup with Github I get a redirect loop:
https://github.com/login/oauth/authorize?access_type=online&client_id=fakef85dd0ab4b54fake&redirect_uri=http%3A%2F%2Fgrafana.example.com%3A80%2Flogin%2Fgithub&response_type=code&scope=user%3Aemail

I also see the following error with a trace, but the registered callback in Github correct:
http://<my_grafana_server_name_or_ip>:<grafana_server_port>/login/github

http://grafana.example.com/login/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

The grafana log reports 31 messages that look like:
[I] Completed /login/github 302 Found in 480.378Âµs

Please help!

**Comment by torkelo** [comment]
looks like your redirect uri is not matching what you registered. Is you grafana root_url correct? It needs to match the url you use for grafana in the browser. It is used when sending the redirect uri to github

**Comment by no3am** [comment]
Is there a step-by-step manual or instructions how to enable github authentication for grafana?
this is the first time I'm touching grafana, I haven't heard of it before today, I have a task to enable authentication via github.
Our grafana is deployed on kubernetes, so I guess I would have to edit the deployment file, but I'm not sure what exactly should I do there at the moment.. will keep looking - any tips would be most appreciated.

**Comment by torkelo** [comment]
Please use community site for questions

**Comment by jylin** [comment]
I got bit by this as well. Perhaps the documentation could add some clarification in the "auth.github" section about needing to correctly set root_url. Alternatively, would it be possible to just detect the current page's domain and just send that in the OAuth request?

**Comment by foreversmart** [comment]
@jylin thx, that works for me. the note about "root_url" should also located at "auth.github" section.

**Comment by JohhnyP** [comment]
@foreversmart why is that?
You added a root_url = http://${url}:${port} line and it's working?

**Comment by Mikulas** [comment]
I'm on `gcr.io/google_containers/heapster-grafana-amd64:v4.4.3` and even after adding the `root_url` into both `[server]` and `[auth.github]` sections, it still does not build the callback url properly, but sends relative `/login/github`.

**Comment by jpds** [comment]
> looks like your redirect uri is not matching what you registered. Is you grafana root_url correct? It needs to match the url you use for grafana in the browser. It is used when sending the redirect uri to github

The documentation at http://docs.grafana.org/auth/github/ needs to be updated to reflect this.

**Comment by jpds** [comment]
Filed #13340.
