### ISSUE TITLE
Visualize threshold violations

### ISSUE THREAD

**Issue by falkenbt** [grafana/grafana#199]
First of all thanks for the great work!
My feature request: 
If you have a big screen with lots of (small) graphs it can be hard to spot threshold violations. 
It would be great if the graphs could in this case be marked with different background colors or a frame indicating that something needs attention (different colors for warning/critical).  
This should be an option per graph.

**Comment by daniellee** [comment]
This is partially resolved with the [Singlestat panel](http://docs.grafana.org/reference/singlestat/) that uses thresholds to show different colors for the background or value. There is a [good example on the Grafana play site](http://play.grafana.org/dashboard/db/new-features-in-v1-9).

The other part of the this feature request will be resolved by the alerting feature being built. See here #2209.

**Comment by kaos** [comment]
This was implemented way back, but never merged, for 1.x though, so may not apply any longer in 2.x (will update our fixes w. regard to this once we upgrade our installs to 2.x).
https://github.com/grafana/grafana/pull/1019#issuecomment-63047897
