### ISSUE TITLE
service grafana-server start says FAILED but it is actually running

### ISSUE THREAD

**Issue by asuuma** [grafana/grafana#1990]
I installed `https://grafanarel.s3.amazonaws.com/builds/grafana-2.0.2-1.x86_64.rpm` by yum on centos 6.6.
Then I try `service grafana-server start` to start daemon, but it says FAILED.
And then if I do `service grafana-server status`, it says RUNNING.

I think the problem is,
https://github.com/grafana/grafana/blob/master/packaging/rpm/init.d/grafana-server#L85-L94
after starting grafana with nohup, the script only wait for 1 sec to check pid file.
But grafana seems to write pid file after init.
https://github.com/grafana/grafana/blob/master/main.go#L52-L53
My machine has no power to complete first initialization of grafana with sqltie3 in 1 sec.

grafana.log:
```
2015/05/13 11:39:28 [I] Starting Grafana
2015/05/13 11:39:28 [I] Version: 2.0.2, Commit: v2.0.2, Build date: 2015-04-22 15:51:50 +0000 UTC
2015/05/13 11:39:28 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/05/13 11:39:28 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/05/13 11:39:28 [I] Migrator: Starting DB migration
2015/05/13 11:39:28 [I] Migrator: exec migration id: create migration_log table
2015/05/13 11:39:28 [I] Migrator: exec migration id: create user table
2015/05/13 11:39:28 [I] Migrator: exec migration id: add unique index user.login
2015/05/13 11:39:28 [I] Migrator: exec migration id: add unique index user.email
2015/05/13 11:39:28 [I] Migrator: exec migration id: drop index UQE_user_login - v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: drop index UQE_user_email - v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: Rename table user to user_v1 - v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: create user table v2
2015/05/13 11:39:28 [I] Migrator: exec migration id: create index UQE_user_login - v2
2015/05/13 11:39:28 [I] Migrator: exec migration id: create index UQE_user_email - v2
2015/05/13 11:39:28 [I] Migrator: exec migration id: copy data_source v1 to v2
2015/05/13 11:39:28 [I] Migrator: exec migration id: Drop old table user_v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: create star table
2015/05/13 11:39:28 [I] Migrator: exec migration id: add unique index star.user_id_dashboard_id
2015/05/13 11:39:28 [I] Migrator: exec migration id: create org table v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: create index UQE_org_name - v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: create org_user table v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: create index IDX_org_user_org_id - v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: create index UQE_org_user_org_id_user_id - v1
2015/05/13 11:39:28 [I] Migrator: exec migration id: copy data account to org
2015/05/13 11:39:28 [I] Migrator: skipping migration id: copy data account to org, condition not fulfilled
2015/05/13 11:39:28 [I] Migrator: exec migration id: copy data account_user to org_user
2015/05/13 11:39:28 [I] Migrator: skipping migration id: copy data account_user to org_user, condition not fulfilled
2015/05/13 11:39:28 [I] Migrator: exec migration id: Drop old table account
2015/05/13 11:39:28 [I] Migrator: exec migration id: Drop old table account_user
2015/05/13 11:39:28 [I] Migrator: exec migration id: create dashboard table
2015/05/13 11:39:28 [I] Migrator: exec migration id: add index dashboard.account_id
2015/05/13 11:39:28 [I] Migrator: exec migration id: add unique index dashboard_account_id_slug
2015/05/13 11:39:29 [I] Migrator: exec migration id: create dashboard_tag table
2015/05/13 11:39:29 [I] Migrator: exec migration id: add unique index dashboard_tag.dasboard_id_term
2015/05/13 11:39:29 [I] Migrator: exec migration id: drop index UQE_dashboard_tag_dashboard_id_term - v1
2015/05/13 11:39:29 [I] Migrator: exec migration id: Rename table dashboard to dashboard_v1 - v1
2015/05/13 11:39:29 [I] Migrator: exec migration id: create dashboard v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: create index IDX_dashboard_org_id - v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: create index UQE_dashboard_org_id_slug - v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: copy dashboard v1 to v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: drop table dashboard_v1
2015/05/13 11:39:29 [I] Migrator: exec migration id: create data_source table
2015/05/13 11:39:29 [I] Migrator: exec migration id: add index data_source.account_id
2015/05/13 11:39:29 [I] Migrator: exec migration id: add unique index data_source.account_id_name
2015/05/13 11:39:29 [I] Migrator: exec migration id: drop index IDX_data_source_account_id - v1
2015/05/13 11:39:29 [I] Migrator: exec migration id: drop index UQE_data_source_account_id_name - v1
2015/05/13 11:39:29 [I] Migrator: exec migration id: Rename table data_source to data_source_v1 - v1
2015/05/13 11:39:29 [I] Migrator: exec migration id: create data_source table v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: create index IDX_data_source_org_id - v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: create index UQE_data_source_org_id_name - v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: copy data_source v1 to v2
2015/05/13 11:39:29 [I] Migrator: exec migration id: Drop old table data_source_v1 #2
2015/05/13 11:39:29 [I] Migrator: exec migration id: create api_key table
2015/05/13 11:39:29 [I] Migrator: exec migration id: add index api_key.account_id
2015/05/13 11:39:29 [I] Migrator: exec migration id: add index api_key.key
2015/05/13 11:39:29 [I] Migrator: exec migration id: add index api_key.account_id_name
2015/05/13 11:39:29 [I] Migrator: exec migration id: drop index IDX_api_key_account_id - v1
2015/05/13 11:39:30 [I] Migrator: exec migration id: drop index UQE_api_key_key - v1
2015/05/13 11:39:30 [I] Migrator: exec migration id: drop index UQE_api_key_account_id_name - v1
2015/05/13 11:39:30 [I] Migrator: exec migration id: Rename table api_key to api_key_v1 - v1
2015/05/13 11:39:30 [I] Migrator: exec migration id: create api_key table v2
2015/05/13 11:39:30 [I] Migrator: exec migration id: create index IDX_api_key_org_id - v2
2015/05/13 11:39:30 [I] Migrator: exec migration id: create index UQE_api_key_key - v2
2015/05/13 11:39:30 [I] Migrator: exec migration id: create index UQE_api_key_org_id_name - v2
2015/05/13 11:39:30 [I] Migrator: exec migration id: copy api_key v1 to v2
2015/05/13 11:39:30 [I] Migrator: exec migration id: Drop old table api_key_v1
2015/05/13 11:39:30 [I] Migrator: exec migration id: create dashboard_snapshot table v4
2015/05/13 11:39:30 [I] Migrator: exec migration id: drop table dashboard_snapshot_v4 #1
2015/05/13 11:39:30 [I] Migrator: exec migration id: create dashboard_snapshot table v5 #2
2015/05/13 11:39:30 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v5
2015/05/13 11:39:30 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5
2015/05/13 11:39:30 [I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5
2015/05/13 11:39:30 [I] Created default admin user: admin
2015/05/13 11:39:30 [I] Listen: http://0.0.0.0:3000
```

Can you fix this?

**Comment by torkelo** [comment]
Think it only the first time you start it. Someone else reported this, I have failed to replicate it, seems to only happen some times, maybe a timing issue.

**Comment by torkelo** [comment]
Can you replicate this?

**Comment by asuuma** [comment]
> Think it only the first time you start it.

Yes, that's right.

I could easily replicate this by deleting /var/lib/grafana/grafana.db and restart grafana-server.
This problem is critical for me because I'm installing to many machine of t2.micro on AWS (which is least power in AWS) with Ansible, and Ansible always failing to start grafana-server due to `exit 3`.

**Comment by augustin149** [comment]
I got the same error , @torkelo will this issue be resolved in release 2.0.3?

**Comment by torkelo** [comment]
Yes,  in 2.1 released soon

**Comment by augustin149** [comment]
Cool. thank you

**Comment by george-marcel** [comment]
I upgraded grafana 2.1 to 2.6. I used sudo yum install https://grafanarel.s3.amazonaws.com/builds/grafana-2.6.0-1.x86_64.rpm command and I did not see any error on the console. 

Then I tried to start service using "sudo service grafana-server start"

Getting the following error
Starting Grafana Server: .... FAILED

Please help

**Comment by torkelo** [comment]
Check log file

**Comment by george-marcel** [comment]
I did cat on /var/log/grafana/grafana.log and this is all that it printed 

2016/02/19 00:48:36 [T] Sending anonymous usage stats to stats.grafana.org
2016/02/19 02:21:54 [I] Completed /favicon.ico 404 Not Found in 1.537018ms
2016/02/19 04:10:09 [I] Completed /api/dashboards/db/ 401 Unauthorized in 640.883µs
2016/02/19 04:10:15 [I] Completed /api/dashboards/db/ 412 Precondition Failed in 2.517884999s
2016/02/19 13:04:56 [I] Completed /login 302 Found in 1.296217ms
2016/02/19 13:05:08 [I] Completed /login 302 Found in 6.899738ms
2016/02/19 13:05:08 [I] Completed /login 302 Found in 1.374262ms
2016/02/19 13:48:29 [I] Completed /public/app/panels/timepicker/module.html 404 Not Found in 1.611579ms
2016/02/19 13:48:34 [I] Completed /login 302 Found in 1.321168ms
2016/02/19 13:48:39 [I] Completed /public/app/panels/timepicker/module.html 404 Not Found in 1.434895ms
2016/02/19 13:48:41 [I] Completed /login 302 Found in 6.280806ms
2016/02/19 13:48:42 [I] Completed /public/app/panels/timepicker/module.html 404 Not Found in 1.517077ms
2016/02/19 14:11:30 [I] Completed /app/app.bd986dd5.js 404 Not Found in 1.588974ms
2016/02/19 14:11:30 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 1.811995ms
2016/02/19 14:11:33 [I] Completed /app/app.bd986dd5.js 404 Not Found in 1.791722ms
2016/02/19 14:11:33 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 2.119822ms
2016/02/19 14:11:39 [I] Completed /app/app.bd986dd5.js 404 Not Found in 8.567415ms
2016/02/19 14:11:39 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 56.955024ms
2016/02/19 14:11:47 [I] Completed /app/app.bd986dd5.js 404 Not Found in 1.599538ms
2016/02/19 14:11:47 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 1.804752ms
2016/02/19 14:12:11 [I] Completed /app/app.bd986dd5.js 404 Not Found in 1.440177ms
2016/02/19 14:12:11 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 2.43452ms
2016/02/19 14:12:17 [I] Completed /app/app.bd986dd5.js 404 Not Found in 1.312843ms
2016/02/19 14:12:17 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 1.579595ms
2016/02/19 14:12:25 [I] Completed /app/app.bd986dd5.js 404 Not Found in 12.488538ms
2016/02/19 14:12:25 [I] Completed /css/grafana.dark.min.4adfdad8.css 404 Not Found in 67.972578ms
