### ISSUE TITLE
Notifications no longer work against latest version of Sensu Go

### ISSUE THREAD

**Issue by adammcdonagh** [grafana/grafana#19908]
Since moving to Sensu Go and repointing Grafana, the alerting mechanism to Sensu no longer works. 

Looking into it a little more, it seems that some of the fields that Sensu is expecting have changed slightly, causing it to (I think) ignore the API call due to it being malformed.

**What happened**:

Alert did not get recognised by Sensu

**What you expected to happen**:

Sensu should handle the alert

**How to reproduce it (as minimally and precisely as possible)**:

Point Grafana at Sensu Go backend.
Configure the notification config and click Send Test

**Anything else we need to know?**:

Ideally there should be 2 notification channels for Sensu. One for Sensu Core (the no longer maintained version), and another for Sensu Go (which is the new platform).

At a minimum I think these following values are required in the JSON:

```
check.proxy_entity_name
check.metadata.name
check.output
check.interval
check.issued
check.executed
check.status
check.handlers
```

**Environment**:
- Grafana version: Latest
- Data source type & version: N/A
- OS Grafana is installed on: RHEL 7
- User OS & Browser: MacOS & Chrome
- Grafana plugins: N/A

**Comment by mrh666** [comment]
+1!!

**Comment by aknuds1** [comment]
Labeling this as a feature request, since it's a question of supporting the new Sensu Go product.

**Comment by rgarcia89** [comment]
+1
