### ISSUE TITLE
Elasticsearch Explore tab shows all logs at time 2019-01-01 00:00:00

### ISSUE THREAD

**Issue by AdmiralGT** [grafana/grafana#19909]
**What happened**:
Viewing logs in the Explore tab for Elasticsearch v6.0+, all logs display with a time of "2019-01-01 00:00:00".
[Screenshot](https://imgur.com/a/HlQLIth)

**What you expected to happen**:
Logs to be displayed with the correct timestamp.

**Environment**:
- Grafana version: v6.4.2
- Data source type & version: Elasticsearch v6.0+, Time field name = ts. (Running against a v6.1.2 Elasticsearch cluster)
- OS Grafana is installed on: Docker container running as Kubernetes pod
- User OS & Browser: Windows 10, Chrome (also repros in Firefox)

**Comment by wardbekker** [comment]
+1

**Comment by torkelo** [comment]
@davkal can you add this to Observability todo?

**Comment by denissduan** [comment]
the same issue

**Comment by Konpon96** [comment]
Having the same issue when using Grafana both in 6.4.3 and 6.5.0-pre (Docker image grafana/grafana:master) with ES 7.4.1. On Grafana 6.3.6 there is no issue and the correct timestamps are displayed.
