### ISSUE TITLE
Environment variable GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS is ignored

### ISSUE THREAD

**Issue by fcanovai** [grafana/grafana#19907]
**What happened**:

`GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS` is ignored. As an example, running `GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS='example.com' GF_AUTH_GENERIC_OAUTH_ENABLED='true' bin/darwin-amd64/grafana-server` only the second env variable overrides the value, as is shown in the logs:
```
INFO[10-18|15:54:24] Starting Grafana                         logger=server version=6.5.0-pre commit=31735422ef branch=master compiled=2019-10-18T14:39:38+0200
INFO[10-18|15:54:24] Config loaded from                       logger=settings file=/Users/fcanovai/prj/src/github.com/grafana/grafana/conf/defaults.ini
INFO[10-18|15:54:24] Config overridden from Environment variable logger=settings var="GF_AUTH_GENERIC_OAUTH_ENABLED=true"
INFO[10-18|15:54:24] Path Home                                logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana
INFO[10-18|15:54:24] Path Data                                logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/data
INFO[10-18|15:54:24] Path Logs                                logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/data/log
INFO[10-18|15:54:24] Path Plugins                             logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/data/plugins
INFO[10-18|15:54:24] Path Provisioning                        logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/conf/provisioning
INFO[10-18|15:54:24] Starting Grafana                         logger=server version=6.5.0-pre commit=31735422ef branch=master compiled=2019-10-18T14:39:38+0200
INFO[10-18|15:54:24] Config loaded from                       logger=settings file=/Users/fcanovai/prj/src/github.com/grafana/grafana/conf/defaults.ini
INFO[10-18|15:54:24] Config overridden from Environment variable logger=settings var="GF_AUTH_GENERIC_OAUTH_ENABLED=true"
INFO[10-18|15:54:24] Path Home                                logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana
INFO[10-18|15:54:24] Path Data                                logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/data
INFO[10-18|15:54:24] Path Logs                                logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/data/log
INFO[10-18|15:54:24] Path Plugins                             logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/data/plugins
INFO[10-18|15:54:24] Path Provisioning                        logger=settings path=/Users/fcanovai/prj/src/github.com/grafana/grafana/conf/provisioning
```

**What you expected to happen**:

 I expected the `allowed_domains` in the `auth.generic_oauth` section to be set.

**How to reproduce it (as minimally and precisely as possible)**:

Try to run the code compiled from sources or the Docker image setting the `GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS` env variable

**Anything else we need to know?**:

Seems to me the issue is related to the `allowed_domains` missing from the default conf. If I add `allowed_domains =` to the `auth.generic_oauth` section the setting is overridden. I think this setting could be added to the default config, as it is for the `auth.google` section.
 
**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Prometheus
- OS Grafana is installed on: OSX and the Docker Image
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This option is missing in the defaults.ini file, needs to be there for ENV variables to work:

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L319

**Comment by fcanovai** [comment]
Would there be any side effect adding `allowed_domains=` to the defaults? I don't see a particular reason to exclude it, and I believe that having settings which are directly overridable via env vars and others that are not can be confusing and can add unnecessary complexity to a docker setup.

**Comment by papagian** [comment]
@fcanovai there is no harm adding this to the defaults.ini.
Would you like to make this modification?
