### ISSUE TITLE
Pareto Chart plugin request

### ISSUE THREAD

**Issue by jmliu1983** [grafana/grafana#19905]
Pareto chart is widely used in production area, is there plan for Pareto Chart develop?
**What would you like to be added**:
Pareto Chart request
About Pareto Chart:
- Normally Pareto chart has 2 serials
- one serial is Bars shows data
- the other serial is a line which shows each bar's percentage accumulate.
**Why is this needed**:
Pareto chart is widely used in production area.

Thanks
![pareto sample](https://user-images.githubusercontent.com/50853043/67100161-c79edb80-f1f1-11e9-9304-1cdcabef0c8c.png)

**Comment by isaozlerfm** [comment]
@jmliu1983, don't assume you're still waiting but 🤷🏻‍♂️  we needed one too, so... maybe it helps you or others

https://github.com/isaozler/pareto-chart/tree/releases/latest

Also created a grafana-repo https://github.com/grafana/grafana-plugin-repository/pull/735 for this

**Comment by isaozlerfm** [comment]
Plugin available https://grafana.com/grafana/plugins/isaozler-paretochart-panel

**Comment by zoltanbedi** [comment]
Thank you @isaozlerfm
