### ISSUE TITLE
Docker images for 6.3.x do not build correctly

### ISSUE THREAD

**Issue by antiquechrono** [grafana/grafana#19914]
**What happened**:
Docker image builds but can't run because it can't find libc 2.28

**What you expected to happen**:
Docker image to run

**How to reproduce it (as minimally and precisely as possible)**:
Just build the image

**Anything else we need to know?**:
This is happening because the golang:1.12.9 container is built on libc 2.28 whereas the container being used to run grafana is ubuntu:18.04 which is built against libc 2.27, upgrading to ubuntu 18.10 will fix the issue. This seems to be a pretty serious oversight, multiple broken docker builds shouldn't be making it into release branches.

**Environment**:
- Grafana version: confirmed on v6.3.5, v6.3.6 has the same dockerfile so it's bound to be broke there too.

**Comment by torkelo** [comment]
this was just for the local custom dev build, not any official build or offical docker images. 

Fixed in master. 

The production docker container is here:
https://github.com/grafana/grafana/tree/master/packaging/docker
