### ISSUE TITLE
A common panel can be selected and inserted into current dashboard

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#19917]
**What would you like to be added**:
A common panel can be selected and inserted in current dashboard
**Why is this needed**:
Sometimes when created series of relative dashboards there is always some same panels in every dashboard. Update one means update it in each of them. So I'm thinking a common one that one place change updates all.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/1803
