### ISSUE TITLE
Data disappears when backdating

### ISSUE THREAD

**Issue by adamlhumphreys** [grafana/grafana#19921]
**What happened**:
I'm currently working with a fixed data set which is a few days old just so I can set up grafana. When I select that particular range in the past in which I have data, (either through dragging or via the range dialog), I get "No data," but I know the data is there, I was just looking at it and it's pulled form a local database form the same machine. In order to see all the data in my dataset, I must include the last second of the current day in my range, otherwise, if I begin shrink my end-range selection, the end of my dataset will also begin to shrink despite still being well within range.

This stood out most prominent when I was working with it, the end-range was set to the last second of Oct. 18. All of a sudden, I got "No data" on everything. As it turns out, the clock struck 12, it was now the 19th. To get it back, I had to select the latest day time period. To get back to work, (and actually be able to see the data at closer scale), I decided to just updated all the dates in my one table to the current day.

*Video of how the data truncates:* https://www.dropbox.com/s/c95fulio8v0bbed/grafana%20issue%20with%20backdating.mp4?dl=0 

**What you expected to happen**:
To select a time range in the past and see all the data within that time range, thus at a closer scale.

**How to reproduce it (as minimally and precisely as possible)**:
N/A, as it always occurs. Now, if it doesn't occur on Linux for some esoteric reason, I do plan to eventually set this up on a Raspberry Pi. 😃

**Anything else we need to know?**:
As a first time user of grafana, at first I thought I was doing something wrong.

**Environment**:
- Grafana version: Grafana 6.4.1.windows-amd64
- Data source type & version: MySQL 5.7.19
- OS Grafana is installed on: Windows 10 Pro v1903
- User OS & Browser: Windows 10 Pro v1903, Firefox Quantum 69.0.3 (64-bit)/Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Grafana plugins: (I haven't gotten that far yet.)
- Others: If this has already been reported, or a solution to this has already been posted, my apologies, as I did a little bit of checking and searching but may have missed something.

**Comment by torkelo** [comment]
make sure you have a WHERE $__timeFilter(dateColumn) in your query 

When you look at historical data use query inspector to inspect the query sent and the result of your query

**Comment by adamlhumphreys** [comment]
I did, and that was the problem, and not a new one apparently: https://github.com/grafana/grafana/issues/13769#issuecomment-434745600

SELECT FROM_UNIXTIME(0) should return 1970-01-01 00:00:00 100% of the time in my opinion, but not so with a MySQL database with a SYSTEM time zone that isn't UTC. It will read that value as UTC and return the human readable form relative to their time zone.

So the generated query using WHERE $__timeFilter(dateColumn) looks great until it's determined that's not the range MySQL is actually returning. Given my table structure, the easiest solution was to set MySQL to UTC:

> [mysqld]
> (...other variable(s)...)
> default_time_zone = '+00:00'

...and use this query, (which I admit is practically the same as what's in the referenced thread apart from the way the data is stored):

> WHERE TIMESTAMP(date,time) BETWEEN
> 	FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())

Hopefully this helps someone new to grafana and/or MySQL.
