### ISSUE TITLE
Graph: add option to make curve relative to its start

### ISSUE THREAD

**Issue by denisidoro** [grafana/grafana#19923]
**What would you like to be added**:
To add an option to the default graph plug-in so that the value displayed for a curve y at time t is `y(t)/y(t0)` or `(y(t)-y(t0))/y(t0)`, where t0 is the start time of observation. Such as:
![Screenshot_20191019-074503_1](https://user-images.githubusercontent.com/3226564/67143776-4f620580-f245-11e9-83bc-3b20cd795c98.jpg)

**Why is this needed**:
This would make investment dashboards easier to reason about

**Comment by denisidoro** [comment]
Is this possible with the recent "Transformations" feature? I tried coming up with something but to no avail.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
