### ISSUE TITLE
Editing trigger failed

### ISSUE THREAD

**Issue by vyidanov** [grafana/grafana#19929]
**What happened**:
when i start editing a previously saved or newly created zabbix trigger list, an error occurs as on the screen:

**How to reproduce it (as minimally and precisely as possible)**:
create trigger list , then  edit it.

**Environment**:
- Grafana version:  v6.4.3 (commit: 3a2bfb7)
- Data source type & version:  zabbix  3.10.4
- OS Grafana is installed on: oracle linux
- User OS & Browser: chrome 77.x.x
- Grafana plugins: zabbix 3.10.4

![err1](https://user-images.githubusercontent.com/31054236/67180800-3c9a2d00-f40d-11e9-82de-1f56c0053977.png)
![err2](https://user-images.githubusercontent.com/31054236/67180806-402db400-f40d-11e9-9efa-2a30db3d165b.png)

**Comment by marefr** [comment]
Please open a bug report in the [zabbix plugin repository](https://github.com/alexanderzobnin/grafana-zabbix).
