### ISSUE TITLE
constant variable can't replace in string with '_' like '$A_b1_c2'

### ISSUE THREAD

**Issue by flyzb618** [grafana/grafana#19920]
**What happened**:
I define a constant variable A with value '01'.There is an string '01_b1_c2', and I change to  '$A_b1_c2' with constant variable A . But in my dashboard, it does not run . But I test '$A.b1.c2' , it can replace well.

**What you expected to happen**:
I want the  '01_b1_c2'.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:  
- Grafana version: 6.3.6
- Data source type & version:
- OS Grafana is installed on: windows 8 ,windows 2012
- User OS & Browser:  chrome
- Grafana plugins: imageit
- Others:

**Comment by torkelo** [comment]
use ${A} syntazx
