### ISSUE TITLE
Grafana v1.9.1 is not available via yum

### ISSUE THREAD

**Issue by grepwood** [grafana/grafana#1993]
Some projects still depend on configuring config.js in grafana. Can someone please add grafana 1.9.1 into the yum repository so that it can be nicely installed and hopefully, upgraded on the system when projects catch up with the lack of config.js?

**Comment by torkelo** [comment]
Grafana 1.9.1 has no rpm or deb packages, so no no packages can be added to a yum repo. 

Writing deb and rpm packages takes a long time and adding this this old version would take away valuable time from improving Grafana 2.0

**Comment by torkelo** [comment]
And I am not sure what you mean "upgraded on the system when projects catch up with the lack of config.js?" Do you expect me to write NEW rpm packages for this old version and release new packages for Grafana 2.0 that does the migration automatically? There 1.9.1 version will not get any more updates (unless some series security issue is discovered). 

 There is migration path from 1.x to 2.0 , http://docs.grafana.org/installation/migrating_to2/ 
Takes about 5-10min  ,  but a completely automatic yum update is a little too much to expect for an upgrade like this :)

**Comment by torkelo** [comment]
Why would you want to install 1.9.1 using yum when there already is rpm packages for 2.0?

**Comment by grepwood** [comment]
I'm following a certain guide that assumes we're starting with Grafana 1.x. Right now I can't afford the time to experiment with 2.0, I need graphs asap :) After that I can come back to this.
The reason why I'd like to install it via yum is that I'm writing a script for RHEL that among many things, will install grafana. It's very desirable to keep grafana up to date, but the project's dependency on config.js is blocking this update. And if you like I can make the .rpm myself, even adjust the .spec for Grafana 1.9.1 specifically.

**Comment by torkelo** [comment]
sure, you can make an rpm have it integrate with the current build and signing scripts and handle upgrades to 2.0 :)
