### ISSUE TITLE
Slack alert message mentions not highlighting or being detected

### ISSUE THREAD

**Issue by elsmorian** [grafana/grafana#19938]
**What happened**:
Adding a Slack username in the mentions box only includes the raw text in the Slack message, and doesn't act as a proper mention (Username is not highlighted, no notification is sent by Slack)

**What you expected to happen**:
Usernames are treated as proper mentions which highlight them and trigger Slack notifications to those users

**How to reproduce it (as minimally and precisely as possible)**:
Add a username to the Mention field in a Slack notification channel, send a test alert, observe the lack of highlighting in Slack

**Anything else we need to know?**:
<img width="316" alt="Screenshot 2019-10-21 at 16 55 30" src="https://user-images.githubusercontent.com/64268/67221655-bb9a6000-f423-11e9-814d-6271e8c28816.png">
<img width="452" alt="Screenshot 2019-10-21 at 16 58 24" src="https://user-images.githubusercontent.com/64268/67221819-0320ec00-f424-11e9-88e2-967cb635c224.png">

Mentioned on the Grafana community too. https://community.grafana.com/t/slack-mentions-not-working/22030

Might be related to https://github.com/grafana/grafana/issues/10450 but thats pretty old..

**Environment**:
- Grafana version: Grafana v6.4.3 (commit: 3a2bfb7)
- Data source type & version: Graphite 
- OS Grafana is installed on: grafana/grafana:6.4.3 Docker image 
- User OS & Browser: MacOS 10.14.6   Safari 13.0.2 
- Grafana plugins: None
- Others:

**Comment by elsmorian** [comment]
let me know if we can test or supply any more information regarding this - it seems unlikely that we are the only ones hitting this, however I can't see anything particularly rare about our setup!

**Comment by aknuds1** [comment]
Sorry for the long wait, but I will have a look at this :)

**Comment by elsmorian** [comment]
@aknuds1 No worries, thanks! Part of me is still questioning if we can really be the only ones having this issue, let me know if we can do anything our end :)

**Comment by aknuds1** [comment]
I'm going to see if I can replicate it first.

**Comment by aknuds1** [comment]
It looks as if you need to [obtain the user ID](https://api.slack.com/reference/surfaces/formatting#mentioning-users) before you can insert a mention, just using the Slack handle won't work.

**Comment by aknuds1** [comment]
Are you familiar with the above requirement @elsmorian?

**Comment by elsmorian** [comment]
@aknuds1 ah, hmm I think we did try that but I will double check

**Comment by aknuds1** [comment]
@elsmorian We also need to format the inclusion of the user ID properly in the message, so it's not something you can solve on the user side :)

**Comment by elsmorian** [comment]
Aha, yes If I remember correctly we tried using the Slack user ID and couldn't get that to work and have just double checked, and indeed it comes through as the raw Slack I rather than a @user mention

**Comment by aknuds1** [comment]
@elsmorian After seeing that it's apparently quite tricky to translate a user handle to the corresponding ID, potentially involving several paginated calls to [users.list](https://api.slack.com/methods/users.list), I'm wondering if it's best to force the mention to refer to a user ID? It should make for less complexity, and less room for error (as translation calls to Slack API could fail). What do you think?

**Comment by aknuds1** [comment]
@elsmorian I made [a PR](https://github.com/grafana/grafana/pull/21734) to fix this bug, by introducing the settings "Mention User" and "Mention Group", that take a user ID and a group ID respectively. It was necessary to distinguish between users and groups, since you need different syntax for mentioning one or the other.

**Comment by elsmorian** [comment]
@aknuds1 That sounds excellent yeah! If there could be a little link maybe to the Slack docs to show how to get a User ID from the users profile that would be perfect, but yeah using the user ID sounds good to me!

**Comment by elsmorian** [comment]
Is the group ID the ID of the channel? or the name of the slack organisation?

**Comment by aknuds1** [comment]
@elsmorian I only learnt about Slack groups now, they are also called sub-teams. They seem to be teams within the workspace

**Comment by elsmorian** [comment]
@aknuds1 This looks great, thanks for looking into and fixing this! Will it be out in the next Grafana release?

**Comment by aknuds1** [comment]
@elsmorian you're welcome 🙂 Yes, it will be in 6.7.

**Comment by NikhilShaw** [comment]
<@MemberID> in summary works for me. make sure there's no new line in summary. MemberID you can get from slack profile section
