### ISSUE TITLE
Auth Proxy: Set org via header

### ISSUE THREAD

**Issue by jameskirsop** [grafana/grafana#19943]
**What would you like to be added**:

Like #3471 (for LDAP) and a number of other requests (for other auth mechanisms), it would be great if setting an organisation via Auth Proxy for a new user would be added.

I'd imagine that, the intermediate module would receive the header and apply the org at login.

**Why is this needed**:
We would like to provide our tenants/customers the ability to have their own auth provider in front of Grafana - and using an Auth Proxy with Apache seems like a reasonable way of doing this.

Adding this functionality would allow us to define the organisation passed to Grafana based on the (client side) authentication end point used in our Apache configuration. This would allow Grafana to place the user coming via a given auth mechanism in the correct organisation.

**Comment by lyndon160** [comment]
+1 is there any update on this?

**Comment by UXabre** [comment]
Hi, I'd like to present my solution to this problem as a patch under review:
https://github.com/grafana/grafana/pull/33162

Please let me know what you think :-)

**Comment by Jguer** [comment]
The header is `X-Grafana-Org-Id`
