### ISSUE TITLE
User Session without external databases

### ISSUE THREAD

**Issue by clausa20** [grafana/grafana#19940]
Hello,
we are trying to start using grafana without maintaining an external database where saving dashboards and datasources.

For that we are starting using some solutions like helm stable/grafana which uses kubernetes configmaps to store dashbaord and datasources, and then a sidecar container stores those configmaps inside the grafana pod automatically.

The problem we are having now is when I set for example 3 grafana replicas with a Kubernetes service in front (LoadBalancer), then I login in grafana dashbaord, but the login session is lost during browsing and redirection, that is because the session is not kept between different replicas.

I see that since grafana version 6.2, session configuration were removed and external database is needed to maintain the session (redis, memcache, etc).

I would like grafana to support a dbless solution for sessions so we don't have to setup an extra database solely to keep sessions, we want to eliminate databases to maintain and with kubernetes configmaps we almost get that goal, except for sessions.

Thanks.

**Comment by torkelo** [comment]
Grafana requires a remote SQL DB (mysql or postgres) for HA setups with a load balancer.

That will very likely not change. 

> I would like grafana to support a dbless solution for sessions so we don't have to setup an extra database solely to keep sessions, we want to eliminate databases to maintain and with kubernetes configmaps we almost get that goal, except for sessions.

There is no secure way to do this.

**Comment by adrianmoisey** [comment]
According to the docs, redos is supported for session storage. Is this no longer correct?
https://grafana.com/docs/grafana/latest/tutorials/ha_setup/#stateless-sessions

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by efasel** [comment]
moved to [Enable high availability setup without database · Discussion #37227 · grafana/grafana](https://github.com/grafana/grafana/discussions/37227)

**Comment by aslafy-z** [comment]
Following https://github.com/grafana/grafana/discussions/37227#discussioncomment-8470949, can this issue be reopened? Thank you
