### ISSUE TITLE
Hide Label on multiple gauges

### ISSUE THREAD

**Issue by haldi4803** [grafana/grafana#19957]
Hello, I use Grafana to show some Temperature Sensors via influxDB and would like to display the Current Temperature in a Gauge beside the graphs.

Previously i had 3 Seperate Elements... but sadly that completly fucks up the Mobile Layout on the phone. So i tried to use one Element with 3 Gauges. But in that case i cannot autoHide the Name for each.

![grafik](https://user-images.githubusercontent.com/17104473/67324500-304cc780-f514-11e9-9d5c-391090e8ecd9.png)

P.S Sidequestion, to show the current Temperature (Last Value not null) should i select a Time Series or a Table?

because i have the Gauges directly beside the graph i don't really need any labeling on them.

![grafik](https://user-images.githubusercontent.com/17104473/67325586-af8ecb00-f515-11e9-9a68-085873e2ea46.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
