### ISSUE TITLE
Explore: After live-tailing stops, logs from pre-selected time range are not displayed

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#19954]
**What happened**:
In Explore, after live-tailing stops, logs from selected time range are not displayed. Instead of that, last logs that were displayed in live-tailing are shown. TimePicker and displayed logs are not synced. 
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/30407135/67301217-675cb200-f4ef-11e9-9d84-cc4269cb6757.gif)

**What you expected to happen**:
See either logs for my selected time range OR change the time range according displayed logs. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Open Loki in Explore
2. Select Yesterday in TimePicker
3. Run live tailing
4. Stop live tailing
5. See that logs that are displayed don't correspond with time range Yesterday.

**Anything else we need to know?**:
Live-tailing is initialised with runQueries function. When user stop live-tailing, we display last values from the live-tailing. We don't run new runQueries function with range from time picker OR we don't change time picker based on logs.

**Environment**:
- Grafana version: 6.4.
- Data source type & version: Loki

**Comment by pstibrany** [comment]
I think Live Tailing can be completely disabled, if time range doesn't include "now" (like from the video above, where it was just "Yesterday"). Then this is not a problem anymore.

When time range includes "now", live tailing will expand the range. If old log entries that fall out of the time window were removed, that would also be fair game in my opinion.
