### ISSUE TITLE
Time Picker not working on Internet Explorer 11 

### ISSUE THREAD

**Issue by jlaudenbach** [grafana/grafana#19953]
**What happened**:
When using the Time Picker for  Grafana Version > 6.2 under Internet Explorer 11, the site crashes.
This can also be checked on Grafana Demo Version (v6.4):
`https://play.grafana.org/d/000000012/grafana-play-home?orgId=1`

**What you expected to happen**:
It is possible to use Time Picker for Version > 6.2 also on Internet Explorer 11

**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana Demo Version on Internet Explorer 11 (not Edge):
`https://play.grafana.org/d/000000012/grafana-play-home?orgId=1`
Click on Time Picker

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Linux
- User OS & Browser: Internet Explorer 11
- Grafana plugins: Yes
- Others:

**Comment by torkelo** [comment]
Please add to this issue we we collect IE11 issues: https://github.com/grafana/grafana/issues/15754

IE11 is not currently fully supported and we have no plans to add back IE11 support

**Comment by jlaudenbach** [comment]
Thank you for your answer and explanation.

I have one more question:
Is it in general possible to get a fixes for IE11 for Enterprise customers?

Best regards
