### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by k0st1an** [grafana/grafana#19950]
**What happened**:

Sorting does not work

<img width="64" alt="image" src="https://user-images.githubusercontent.com/426513/67275675-cad4e880-f4cb-11e9-918b-7deed90947c2.png">

**What you expected to happen**:

Sort should be from larger to smaller.

**How to reproduce it (as minimally and precisely as possible)**:

Apparently this requires ClickHouse DB and data. Field from SQL query:
`uniqIf(bid_id, type = 'click') clicks,`

**Anything else we need to know?**:

Initially updated from v5.4.3 to v6.4.0. But the plugin for ClickHouse (v1.9.0) did not work. I went down to version v6.3.6 but sorting did not work in it. Rolled back to the old version v5.4.3. Released plug-in version v1.9.3, updated to grafana v6.4.3 sorting does not work. Returned to graphan v5.4.3 (ClickHouse v1.9.0 plugin) - sorting does not work. Left the version v6.4.3/v1.9.3.

Type assignment does not help:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/426513/67277780-45076c00-f4d0-11e9-848c-f30112c69e97.png">

**Environment**:
- Grafana version: v6.4.3 (3a2bfb7)
- Data source type & version: ClickHouse datasource for Grafana 4.6+ v1.9.3
- OS Grafana is installed on: no
- User OS & Browser: macos
- Grafana plugins:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/426513/67276247-ef7d9000-f4cc-11e9-94dc-be6f5d77b4ab.png">

- Others:

**Comment by torkelo** [comment]
what is the raw query results for this column?

**Comment by k0st1an** [comment]
UInt64

**Comment by torkelo** [comment]
show response from query inspector?

**Comment by k0st1an** [comment]
<img width="139" alt="image" src="https://user-images.githubusercontent.com/426513/67282041-746ea680-f4d9-11e9-965e-9ea555467338.png">

**Comment by k0st1an** [comment]
And
<img width="96" alt="image" src="https://user-images.githubusercontent.com/426513/67282097-99fbb000-f4d9-11e9-916a-fdabbb80555f.png">

**Comment by torkelo** [comment]
looks like a string to me

**Comment by k0st1an** [comment]
yes, now it’s clear
