### ISSUE TITLE
[Feature Request] Add a ${__field.Title} and/or ${__cell_0} to the Bar Gauge to make Data links context sensitive

### ISSUE THREAD

**Issue by euanmacinnes** [grafana/grafana#19961]
**What would you like to be added**:

To add a ${__field.Title} variable to the Data Links for the Bar Gauge. either that or add a ${__cell_0}, ${__cell_1} etc.. capability to allow the data link to pass to the reference dashboard which bar the user clicked on.

**Why is this needed**:

The ${__field.Name} only returns the column heading, there's currently no way to specify the value used in the Field Title, so when drilling down into a specific bar, I have no way of knowing which specific bar the user actually clicked on.

For example:

![Bar Gauge Capture](https://user-images.githubusercontent.com/54568886/67347607-345d0180-f575-11e9-939b-3a383229ed05.JPG)

In this image, I have no way to know, in the drill down from the Data Link, which "reaction" the user clicked on, and two of them have the same Value.

I think that adding the ${__cell_{X}} logic here would be more useful to Data Links in general, rather than ${__field.Title} as that would apply to all chart types, but I'm not sure how easy / hard that would be to pull off in the inner workings.

**Comment by torkelo** [comment]
What is the result of your query? Is the name of the bar in another field/column?

**Comment by euanmacinnes** [comment]
The result of the query is :

Title   |     Value
----‐--------------------
Bar A |         0.5
Bar B |         0.6
Bar C |         0.8

Or am I supposed to pivot the results?

**Comment by hugohaggmark** [comment]
@euanmacinnes we've done a lot of work with Data Links and I think we solve this with the use of __`${__data.fields.<name of the field>}`__. I'm going to close this issue because I can't repro it on Grafana v7.4.0-pre (db637a3630) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
