### ISSUE TITLE
AzureMonitor: Use common QueryField abstraction

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#19962]
There is an incredible amount of duplication in the Azure monitor query field that we need to refactor to use the shared QueryField. Looks like it copies a lot of code from the Explore QueryField (that is being used Loki, Prometheus, and Elasticsearch), wonder if we could have used that instead and why this was simply copied when doing the Azure logs query editor. 

This explore query field (Slate abstraction) is soon available from from @grafana/ui  #19678 

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana-azure-monitor-datasource/editor/query_field.tsx

After https://github.com/grafana/grafana/pull/19678 is merged this should be of high prio.

**Comment by torkelo** [comment]
related to https://github.com/grafana/grafana/issues/19959 also

**Comment by alexanderzobnin** [comment]
That was copied initially because Azure Monitor was an external plugin. Now it really looks unnecessary.

**Comment by vickyyyyyyy** [comment]
We have switched to Monaco Editor, which should resolve this @joshhunt
