### ISSUE TITLE
Histogram values outside of range

### ISSUE THREAD

**Issue by Lectem** [grafana/grafana#19966]
**What would you like to be added**:

I would like for values outised of the displayed buckets to be regrouped into 2 additional buckets, one "< min bucket" and one "> max bucket". 

Currently this is what I get:

![image](https://user-images.githubusercontent.com/6024225/67375956-a2a8c080-f583-11e9-9617-0b19657fdc9c.png)

And this is what I would like to have:

![image](https://user-images.githubusercontent.com/6024225/67376185-fe734980-f583-11e9-92fc-0a33c29ac2ce.png)

**Why is this needed**:

It sometimes happen that we have extreme values, but we still want to focus mainly around a certain given range. The current behavior is a deceptive as it simply does not take into account values outside of the buckets range.
While for the screenshots I was able to obtain similar results by clamping the values, I would like to be able to reuse requests instead of doing twice the same request but with one clamping the values.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
