### ISSUE TITLE
[Feature Request] - Singlestat panel colour via colour code returned from data source

### ISSUE THREAD

**Issue by n1nj4888** [grafana/grafana#19960]
**What would you like to be added**:
Add ability to change singlestat panel background/text colour based on a RGB/Hex code returned directly from an data source query. 

**Why is this needed**:
Although the background/text colour of a singlestat panel can be changed to 3 static colours based on a threshold range of values, I can’t find a way currently to change the colour of the background/text on the singlestat panel based on a colour hex code returned from an InfluxDB query. 

For example, I have an InfluxDB data source which contains some colour LED bulbs, their status and colour (in Hex, for example Blue = RGB 0,0,255 = Hex #0000ff) and it would be good to colour a singlestat panel showing the current colours. 

Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
