### ISSUE TITLE
An unexpected error happened Error: `Point.createProperties` only accepts objects or points, but you passed it

### ISSUE THREAD

**Issue by mritou** [grafana/grafana#19974]
Hello,
Just after a new grafana 6.4 (docker version) installation i receive the following error while trying to create a query in a new dashboard :

An unexpected error happened
Error: `Point.createProperties` only accepts objects or points, but you passed it: 80

Could you let me know what's my problem is please ?
Thank's in advance for your help

**Comment by torkelo** [comment]
Are you using any plugins on the dashboard? 
Can you include your dashboard json?

**Comment by mritou** [comment]
Hello, no i don't only a recent installation nothing more, and a prometheus datasource.
Downgrading to 5.4 no problem

**Comment by torkelo** [comment]
please include your dashboard json

We have no other reports like  this so something strange is going on

**Comment by mritou** [comment]
Hello,
I reinstall a new docker after a pull of the latest grafana version
Here is the result

**Comment by mritou** [comment]
Here is the link : https://gph.is/g/ZdoWA92

**Comment by mritou** [comment]
I also try to import grafana dashboard but i have a no data, and when i try to edit a query : same problem

**Comment by mritou** [comment]
How i start my container :
bjoseph@bjoseph-VDIBJOSEPH:~$ sudo docker pull grafana/grafana
Using default tag: latest
latest: Pulling from grafana/grafana
9d48c3bd43c5: Pull complete 
df58635243b1: Pull complete 
09b2e1de003c: Pull complete 
f21b6d64aaf0: Pull complete 
719d3f6b4656: Pull complete 
d18fca935678: Pull complete 
7c7f1ccbce63: Pull complete 
Digest: sha256:a10521576058f40427306fcb5be48138c77ea7c55ede24327381211e653f478a
Status: Downloaded newer image for grafana/grafana:latest
bjoseph@bjoseph-VDIBJOSEPH:~$ sudo docker run -d -p 9090:9090 -v /home/bjoseph/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml --name=prometheus prom/prometheus
c601b628d3e5a033caa16c5d526d1d0b6e61724b905b030cf0d35f5dbce1fa2e
bjoseph@bjoseph-VDIBJOSEPH:~$ sudo docker run -d -p 3000:3000 --name=grafana grafana/grafana
9b91f89e76f1c713e27911e9fd163664a17fb40fcc3bac59a62433d3440e507a
bjoseph@bjoseph-VDIBJOSEPH:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
9b91f89e76f1        grafana/grafana     "/run.sh"                5 seconds ago       Up 4 seconds        0.0.0.0:3000->3000/tcp   grafana
c601b628d3e5        prom/prometheus     "/bin/prometheus -..."   6 seconds ago       Up 5 seconds        0.0.0.0:9090->9090/tcp   prometheus

**Comment by mritou** [comment]
any idea ?

**Comment by torkelo** [comment]
What browser are you using?

**Comment by mritou** [comment]
Hello,

I'm using Firefox 60.9.0esr (64 bits)

**Comment by torkelo** [comment]
That is an old version, can you upgrade?

**Comment by mritou** [comment]
I try to upgrade to : 69.0 (64 bits) same problem :(

**Comment by torkelo** [comment]
Do you have the same problem on https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&fullscreen&edit&panelId=2 ?

**Comment by mritou** [comment]
Nope, here i can edit without any trouble via firefox

**Comment by torkelo** [comment]
ok, closing this not sure what can be wrong with your instance. Try re-installing grafana

**Comment by mritou** [comment]
I already try to start a new installation : same problem, anyway...
