### ISSUE TITLE
Explore: Times shown in local timezone rather than UTC

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#19978]
**What happened**: Explore mode panel shows times in local time, even though user has configured UTC and datetime picker says UTC

![tzlocal](https://user-images.githubusercontent.com/814226/67410214-c7a03200-f589-11e9-9698-8e578b4e63b7.png)

**What you expected to happen**: Panel shows times in UTC

**How to reproduce it (as minimally and precisely as possible)**:

1. Set timezone to UTC in Preferences
2. Use explore mode, see times in local timezone and not UTC

**Anything else we need to know?**: Seems to have been fixed in 6.2 (#12812) but still occurring in 6.4.2

**Environment**:
- Grafana version: v6.4.2 (443a0ba)
- Data source type & version: custom internal datasource plugin
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Safari 13.0.2, macOS Catalina 10.15
- Grafana plugins:
- Others:

**Comment by davkal** [comment]
Hmm, I have trouble getting Explore into UTC in the first place. Looks like a bug.
