### ISSUE TITLE
Zabbix Problems Visualization plugin bug

### ISSUE THREAD

**Issue by MACZ83** [grafana/grafana#19975]
**What happened**:
I was creating a new dashboard using the zabbix problems, I am able to create the panel and configure initially but after i am done creating the panel and selecting what to display as the problem (group, host, etc) and go to the dashboard. I am no longer able to edit the panel. When I select edit to make changes to the panel, it errors out with the message below

**Unable to find application file

Grafana has likely been updated. Please try reloading the page.

Reload
Details
TypeError: n.targets.map is not a function

    in t
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in div
    in e
    in DraggableCore
    in e
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in e
    in div
    in div
    in div
    in t
    in t
    in div
    in div
    in e
    in Connect(e)
    in Suspense
    in t
    in Unknown
    in d
    in Unknown
    in Unknown
    in t
    in t
    in a**
![image](https://user-images.githubusercontent.com/56927658/67406841-3d9d9c80-f57c-11e9-9e8f-9156225daa46.png)

**What you expected to happen**:
able to select edit and modify the zabbix problems panel
**How to reproduce it (as minimally and precisely as possible)**:
add new panel, and go back to dashboard and select edit. it happens with or without queries on it and all dashboard I currently have.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.4.3 (3a2bfb7)

- Data source type & version: zabbix 4.4.0
- OS Grafana is installed on: docker container

Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

 

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:56:46 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 
- User OS & Browser: it happens on any browser but I used chrome and firefox
- Grafana plugins:
- Others:

**Comment by MACZ83** [comment]
Thats correct, it happens only when I try to edit the zabbix problems panel.

**Comment by clover1983** [comment]
Hi I got same issue as MACZ83. Could you help to check why? Maybe because I upgrade grafana? I recently upgrade grafana from version 6.1.2 to 6.4.1. Thanks.

**Comment by MACZ83** [comment]
> Does this only happen when you try to edit a zabbix panel? (So not any core Grafana panel)?

Hi torkelo, that is correct. It only happens with the zabbix panel

**Comment by torkelo** [comment]
Make sure you running latest version of zabbix pluggin

If issue still persists open issue here: 
https://github.com/alexanderzobnin/grafana-zabbix
