### ISSUE TITLE
Feature Request - Data Source test button

### ISSUE THREAD

**Issue by enric-sinh** [grafana/grafana#1997]
It would be really useful if there was a button on the Data Sources menu which allowed to test the datasource connections in order to get quick feedback.

It could be implemented as a single button per datasource, or as an indicator besides each datasource, which gets checked in the background and set if the datasource is properly configured.

**Comment by phrend** [comment]
I agree - this would be a useful feature for me as well.

**Comment by torkelo** [comment]
I also agree, I really wanted something like this when I implemented that view. Hope to have time to do it someday

**Comment by nicocesar** [comment]
+1  ... please!
