### ISSUE TITLE
Stackdriver: add new provisioning method that follows google conventions

### ISSUE THREAD

**Issue by RmStorm** [grafana/grafana#19970]
**What would you like to be added**:
I would like the stackdriver datasource to use a service account secret in a similar fashion as other google cloud libraries. The workflow for these libraries is to create a service account and store that account in a secret and than mount it in the containers where it is to be used [like explained here](https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform#step_5_configure_the_application_with_the_secret).

As explained [here](https://grafana.com/docs/features/datasources/stackdriver/#configure-the-data-source-with-provisioning) the stackdriver datasource cannot use a service account from google as downloaded from the cloud, I need to manually extract 3 specific fields from the service_account:
clientEmail, defaultProject and privateKey
These are called different in a service account when exported from google cloud! There they are called:
client_email, project_id and private_key

I would like to be able to do something like this:
```json
apiVersion: 1

datasources:
  - name: Stackdriver
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: from_token
      token: /var/secrets/google/token.json
```
And then I just supply the serviceaccount to the container and it picks it up. I think it should be fairly straightforward since manually configuring the stackdriver datasource does actually allow you to use a regular token! It is only when provisioning that I need to jump through hoops.

**Why is this needed**:
Make it easier to provision grafana with a stackdriver datasource by following Google's conventions when using the service account.

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can’t see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
