### ISSUE TITLE
Grafana: Bug showing All series in a Graph

### ISSUE THREAD

**Issue by Hyruma** [grafana/grafana#19989]
Hello,

I’m using Simple Json as datasource for visualize a simple graph with 2 series. This is my query from Query Inspector:

![query](https://user-images.githubusercontent.com/12028752/67484369-e7098e80-f65f-11e9-860d-9cec08dbda8e.png)

And this is the graph that I retrieve (after few customizations)

![graphGood](https://user-images.githubusercontent.com/12028752/67484409-fc7eb880-f65f-11e9-88f8-5a548aad1f92.png)

As you can see I think there is a visualisation bug with the option “All series”. In fact, if I move hover a point near the middle (like in the picture), the graph shows the values associated at the last point. Furthermore, If I move hover a point to the right of the middle, the graph shows the values of the first point.

**Environment**:
- Grafana version: v6.4.3
- Data source type & version: SimpleJson 1.4.0
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04 Chrome
- Grafana plugins: SimpleJson 1.4.0

**Comment by torkelo** [comment]
Make sure your data sources sorts the values in time asc order

**Comment by Hyruma** [comment]
Thank you very much! It works
