### ISSUE TITLE
Grafana 2 non root url?

### ISSUE THREAD

**Issue by damm** [grafana/grafana#1998]
Hi,

Trying to deploy Grafana2 where it's not the root path; it's under /grafana2 in this case.  Updating the ini to make root_url match helps but I am getting 404's on the css/js.

```
2015/05/15 00:07:12 [I] Completed /grafana2/img/fav32.png 404 Not Found in 3.44056ms
2015/05/15 00:07:12 [I] Completed /grafana2/img/fav32.png 404 Not Found in 1.730161ms
```

Browsing to port 3000/grafana2 is pretty blank gets lots of asset failures; reverting the root_path helps but that's not really a solution.

Am I missing another configuration option here? 

P.S. I'm using a Debian package.

**Comment by torkelo** [comment]
If you adding a subpath you need nginx or apache  in front to reverse proxy requests for this subpath to grafana root

**Comment by damm** [comment]
nginx is in front of it; very simple

```
location /grafana2 {
proxy_pass http://localhost:4000
}
```

I've got this working on the root domain just not subpaths.  Leaving it default / works; everything renders; modifying it to /grafana2/ and with ^^ I get 404's.

Really doesn't make sense; i'll play around with try_files and try and get nginx to serve the assets instead of the go app.

**Comment by torkelo** [comment]
This works great, I use, nd others use this it a lot. must be some config issue. 

What is your root_url ? I know nginx can be touchy about ending forward slashes. Will look up my config later

**Comment by damm** [comment]
`root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana2/`

I've tried adding a extra slash at the end; and without.  Seems simple and likely is

**Comment by torkelo** [comment]
according to the grafana logs nginx is not reverse proxying correctly, try adding a trailing slash to the nginx location line

**Comment by damm** [comment]
Indeed you were right; it was a trailing slash in the proxy_pass line that fixed it.  I previously had the slash in the location block with no change.

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
