### ISSUE TITLE
Grafana 6.4.x breaks datasources using ace editor

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#19982]
**What happened**:
Updating from Grafana 6.3.x to 6.4.x leads to unusable custom datasource which uses the ace editor. The following error message is shown when opening a dashboard with at least one panel/template variable which uses this datasource.

![ace-problem](https://user-images.githubusercontent.com/11644606/67461091-d72c8300-f63c-11e9-8b46-02850ded1c15.png)

**What you expected to happen**:
This minor Grafana version update should not have broken our custom datasouce.

**How to reproduce it (as minimally and precisely as possible)**:
This is quite difficult because the problematic datasouce is a custom one.
Nevertheless, I've found that the Clickhouse datasource had the exact same problem (see [issue 19856](https://github.com/grafana/grafana/issues/19856)). [This commit](https://github.com/Vertamedia/clickhouse-grafana/commit/a321ce7f10084e3389c97b4b6823eb07eb98a690) solved the problem for this datasource.

**Anything else we need to know?**:
I was able to apply the following code change to the _mode.js_ file which actually solves the problem with my custom datasource:
```
export default function() {

    if (!window['ace']) {
        "use strict";
        return false;
    }
    
    /* complete, unmodified former code here */
    [...]
    
    return true;
}
```
By wrapping the former code like this, everything works again. 

I've found a couple of issues and PR's ( [15231](https://github.com/grafana/grafana/issues/15231), [15359](https://github.com/grafana/grafana/pull/15359)... ) mentioning the replacement of ace/brace 
with ace-builds and possibly slate.
-> I'd like to be able to follow this development more easily instead of specifically searching the github issues. There *are* users who are using custom plugins/datasources and most definitely are interested in these kind of changes to grafana.
@torkelo commented the PR [15359](https://github.com/grafana/grafana/pull/15359#issuecomment-470853784) with 

> Closing this, think what the next step here is instead to use slate in the code-editor angular directive. Then we can remove brace. Will be breaking change for some external plugins that use code-editor and custom syntax highlighting but think we can live with that

I also think everybody can live with that, but _please_ prepare plugin developers for this change so we've got some time to modify our plugins.
Any help regarding this up-coming migration will be much appreciated.

**Environment**:
- Grafana version: 6.4.x
- Data source type & version: custom datasource
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Ubuntu 16.04 lts & Firefox/Chrome latest stable release
- Grafana plugins: -
- Others: -

**Comment by miton18** [comment]
> Yes, sorry about this. Since the change to loading ace async required no change to internal data sources we did not check external ones.
> 
> We are working on improving E2E testing of external plugins to better test and detect breaking changes like this

So, how can we access `ace ` var when it's loaded ?
