### ISSUE TITLE
Not able to get alert message on high cpu on slack channel - I am using Grafana + Prometheus

### ISSUE THREAD

**Issue by pawansinha0612** [grafana/grafana#19985]
STOP -- PLEASE READ!

GitHub is not the right place for questions and support requests.

Please ask questions on our community site: [https://community.grafana.com/](https://community.grafana.com/)

**Comment by pawansinha0612** [comment]
I have setup slack notification channel successfully. I got the notification first time while setup. After that, Once the alert on high cpu is happenieng then i can only see alerting but notification is not coming to slack

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

See https://grafana.com/docs/alerting/rules/#troubleshooting and check the grafana server log for details.
