### ISSUE TITLE
Is the value of the y coordinate the same, is this normal?

### ISSUE THREAD

**Issue by wuzhihui1123** [grafana/grafana#19981]
**What happened**:
![image](https://user-images.githubusercontent.com/4246626/67448874-f6321180-f64a-11e9-86c7-71cb7fb2d0a9.png)

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome

**Comment by torkelo** [comment]
It's the auto y decimals logic that is very complicated when paired with units that simplify (shorten) values. 

This should be fixed in 6.4
