### ISSUE TITLE
Feature Request - Images in single stat panels

### ISSUE THREAD

**Issue by afflick** [grafana/grafana#1999]
It would be great to be able to add images to the single stat panels. 
The options already implemented for prefix and postfix text (position before and after, and size as a percentage) would be ideal. 

![untitled](https://cloud.githubusercontent.com/assets/5926324/7647049/39e37dea-fb11-11e4-82b7-178d1fe172d0.png)

**Comment by kibwashere** [comment]
You can dissociate your image and your data this way : 
Add a text panel next to your singlestat panel, and add in html format
`<img src="img/your_img.png" alt="error" />`
or with a hosted image :
`<img src="http://bit.ly/1rX5ooS" alt="error" />`

**Comment by afflick** [comment]
Thanks @kibwashere, I will try to alter the singlestat panel or create a custom panel for a more elegant solution.

**Comment by afflick** [comment]
Anyone looking for this feature see - #2008

**Comment by marknoe1** [comment]
+1!

**Comment by utkarshcmu** [comment]
+1

**Comment by scr512** [comment]
Have you looked at the "Rogue" dashboard over on play.grafana.org? The
single stat dashboard objects look like what you're wanting to do.

http://play.grafana.org/dashboard/db/rogue

**Comment by afflick** [comment]
Thanks @scr512 - This looks like a great workaround solution as my feature hasn't been merged.

**Comment by iMbaundso** [comment]
Hi all, what ist the workaround here? The Rogue Dashboard seems to be not available anymore

**Comment by r4yfx** [comment]
Hi, 

Has there been any further movement on this? I think its a good idea. Possibly, as a plugin if this is something in which its raising questions about having further options within the dashboard. 

Thanks

**Comment by MatthewCroughan** [comment]
I'd love this to be implemented for cryptocurrency tickers.

**Comment by finkr** [comment]
I use unicode / utf8 symbols as a prefix.
It isn't a custom image, there's a lot of images/emoji, like:

☀ ☁ ☂ ⚠ ⚡ ✷ ✸ ✓ ✔ ✕ ✖ ✗ ✘ ❶ ❷ ❸ ❹ ❺ ⬛ ⬜ 🡄 🡆 🡅 🡇 ⬀ ⬁ ⬂ ⬃ 🢄 🢅 🢆 🢇
👍 👎 ✊ 💣 💥🔥 ✆ 📟📌 🖈 📍💹 📈 📉 📊 🗠🌎🌍

There are even some color emoji nowadays (browser and computer dependent)

**Comment by finkr** [comment]
Actually, there is a very easy solution : SVG !

Simply paste some svg, drawing in the prefix/suffix or Value Mapping, that's it !

Yes, literally paste the svg file content in the input box (`<svg> ... </svg>`)

![rss](https://user-images.githubusercontent.com/13090680/42713762-e0dd54d6-86f0-11e8-8a1c-4decbfddea6d.png)

(exemple svg file from https://commons.wikimedia.org/wiki/File:Generic_Feed-icon.svg )

**Comment by nanicpc** [comment]
thanks @finkr your tip save my life 😁

**Comment by k-str50** [comment]
Hi

**Comment by finkr** [comment]
@k-str50, Unicode symbols are like regular character. There are the basic Latin character, the Arabic character, the Cyrillic, the Chinese, Japanese, and Korean... But there are also some character with graphical symbols (shown above).

You can google for "unicode Character sun" (or "utf8 sun"). Some page will show some graphical .JPG file, but some website also provide the actual "text" version, that you can copy-paste in a text box.

**Comment by finkr** [comment]
@k-str50, Unicode symbols are like regular character. There are the basic Latin character, the Arabic character, the Cyrillic, the Chinese, Japanese, and Korean... But there are also some character with graphical symbols (shown above).

You can google for "unicode Character sun" (or "utf8 sun"). Some page will show some graphical .JPG file, but some website also provide the actual "text" version, that you can copy-paste in a text box.

**Comment by k-str50** [comment]
@finkr, thanks a lot for your answer.
Yes I will tryiit .
