### ISSUE TITLE
Row auto-fold when scrolling or hovered

### ISSUE THREAD

**Issue by quanhongnguyen** [grafana/grafana#19993]
Hi guys,

As far as I known, queries of panels in a row will not be triggered if that row is folded.
So I think it would be more efficient if we can support auto-fold for row. 
So If I have 20 rows and at a time I can only see 3 of them, because all of the others are out of the viewport, then all of the others should be folded up to prevent the queries to be triggered.

If the system I have has more than 1000 components and let's say I want to build an overview dashboard to quickly look at them by scrolling up and down. I would use repeated row for this purpose, but then with 1000 rows it will be supper slow. 
I think this is because it has to query a lot's from servers. But at one time I can only see at most 6 of them.

How do you think?
Cheers
Quan

**Comment by torkelo** [comment]
Panels out of view are not having their queries executed until they are scrolled into view

**Comment by torkelo** [comment]
Added in 6.2 I think
