### ISSUE TITLE
Selector for variables is behaving in a strange way

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#19991]
**What happened**:
The behaviour of the selector is somewhat strange and can be misleading.
1. When you select ALL it should automatically check all the boxes on the list, also when you uncheck ALL it should automatically uncheck all the boxes on the list.
2. If you selected ALL the number next to "Selected" should give the total number of all selected items on the list – now it says 1 (probably counting only checkbox ALL)
<img width="678" alt="select1" src="https://user-images.githubusercontent.com/15225624/67487962-2c818800-f66f-11e9-9c59-68ef2a3f8ac4.png">

3. ALL checkbox should also clearly specify whether you're selecting everything or just filtered items on the list.

4. SELECTED behaves like ALL when you click on it a couple of times. 

5. The bar on the selector should be slightly wider to make it easier to grab.

The behaviour of this selector should be reviewed.

**How to reproduce it (as minimally and precisely as possible)**
Easy to check here: https://play.grafana.org/d/rUpVRdamz/dashboard-links-with-variables?orgId=1&var-app=country&var-server=US&var-server=ZA&var-interval=12h

**Comment by hugohaggmark** [comment]
Extends #17381

**Comment by sarlinska** [comment]
@VesnaDean this is a fix you could tackle in upcoming weeks. cc @lukasztyrala

**Comment by hugohaggmark** [comment]
Extends #17943
