### ISSUE TITLE
Alerts fail when using Prometheus as a datasource 

### ISSUE THREAD

**Issue by Throckmortra** [grafana/grafana#19997]
**What happened**:
When testing alerting with a Prometheus datasource, alerts fail to fire and do not resolve. 

**What you expected to happen**:
A slack message sent

**How to reproduce it (as minimally and precisely as possible)**:
Use prometheus as a datasource, browser mode. Set up an alert, attempt to test rule or trigger an alert.

**Anything else we need to know?**:
![error with redacted link](https://i.ibb.co/MZt75n8/Screen-Shot-2019-10-24-at-11-02-03-AM.png)

error in logs:
```
t=2019-10-23T18:17:58+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=0 name="Memory Available alert" error="tsdb.HandleRequest() error Get https://redactedlink.2019-10-23T18%3A12%3A28.322366629Z&step=15.000: dial tcp redacted:443: i/o timeout" changing state to=alerting
```

I am not using templated variables. Works fine with Cloudwatch datasource. 

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: Prometheus, 2.12.0
- OS Grafana is installed on: Docker, Official image
- User OS & Browser: Chrome, MacOS
- Grafana plugins: Prometheus

**Comment by marefr** [comment]
You cannot use browser access mode with alerting since the alerting engine executes in the Grafana backend would need server access mode.

**Comment by Throckmortra** [comment]
Hey @marefr is this documented somewhere? I couldn't find this in the Alerting documentation nor the Prometheus datasource docs.

**Comment by marefr** [comment]
@Throckmortra sort of in datasource configration, but does not mention alerting.

![image](https://user-images.githubusercontent.com/1668778/67555745-34decf00-f712-11e9-93e5-c4bf037c99ff.png)
