### ISSUE TITLE
Docs: Wrong payload for HTTP API for updating user password

### ISSUE THREAD

**Issue by fioletowasowa** [grafana/grafana#19995]
**What happened**:
curl -X PUT -H "Content-Type: application/json" -d '{"oldPassword":"oldpass","newPassword":"newpass","confirmNew":"something"}' http://admin:admin@localhost:3000/api/user/password returns 200 User password changed

**What you expected to happen**:
400 Status code with message: Passwords do not match

**How to reproduce it (as minimally and precisely as possible)**:
Try to change user password and put different values in "newPassword" and "confirmNew" fields

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 6.2.2

**Comment by bbarski** [comment]
same from GUI
Grafana v6.4.3 (3a2bfb7)

**Comment by marefr** [comment]
@fioletowasowa that API resource doesn't support `confirmNew` in the payload.

**Comment by fioletowasowa** [comment]
Then maybe change it on your website... https://grafana.com/docs/http_api/user/#change-password

**Comment by marefr** [comment]
Sorry didn't notice that.
