### ISSUE TITLE
Support for configuring timezone used for the grafana explore tab

### ISSUE THREAD

**Issue by nbellowe** [grafana/grafana#19999]
**What would you like to be added**:
As a administrator of grafana, I would like to be able to configure the timezone used in the explore tab of grafana for the entire organization by default. As a user of grafana, I would also like to be able to configure the timezone used in the explore tab.  (Both organization wide and user-level control would be ideal, but particularly needed is the "global" default) 

**Why is this needed**:
My company operates exclusively off of UTC, and we can configure this to be used in grafana dashes on an organization level. But we cannot configure the explore tab to do so, which causes confusion, and makes the otherwise neat feature much less useful for us.

**Comment by nbellowe** [comment]
Hmm, I found https://github.com/grafana/grafana/issues/19978 is related, this may be a duplicate.

**Comment by torkelo** [comment]
This used to work, you can set default timezone on org or profile level. 

Closing this as we already have #19978
