### ISSUE TITLE
LibreNMS alerts using API Transport 

### ISSUE THREAD

**Issue by baenaeduardo** [grafana/grafana#19998]
Is it possible to use the LibreNMS API transport to create / view a dashboard for alerts ? 
Using the API key created on grafana I can successfully test the the api connection from LibreNMS on the transport section . 
That's as far as I can get unfortunately . 

On LibreNMS these are the paramaeters to fill for the API transport. 

Transport name:
Transport type:
Default Alert:
API Method:
API URL:
Options:
Auth Username:
Auth Password:

Thanks in advance for any help provided .

**Comment by aocenas** [comment]
Hey, @baenaeduardo sorry not sure if I can directly help you with this. Also Github issues are mainly Bugs and Feature requests so this kind of question is probably better suited for https://community.grafana.com/. Feel free to reopen if you think this is a bug or new feature.
