### ISSUE TITLE
Variables in Dashboards - examples?

### ISSUE THREAD

**Issue by falkenbt** [grafana/grafana#200]
Apart from the scripted dashboard feature, is there also a way to use URL parameters in "regular" dashboards and store them in elasticsearch? In my case I would like to have the graphite backend as a parameter so I can easily reuse dashboards across different backends. 
I guess I could also achieve this with a scripted dashboard (https://github.com/torkelo/grafana/wiki/Scripted-dashboards) but I can't store it in ES, correct? And an example for this case would be great as well.

**Comment by torkelo** [comment]
closed in favor of https://github.com/grafana/grafana/issues/816
