### ISSUE TITLE
Only show a Grafana panel if certain variable values are selected

### ISSUE THREAD

**Issue by motoko89** [grafana/grafana#20005]
**What would you like to be added**:
Control a panel visibility through dashboard variable values
**Why is this needed**:
For example, if I have a drop-down of Daily, Weekly, Monthly value. I have a panel called Weekly volume and don't have Daily volume or Monthly valume. I only want to show this panel when Weekly is selected in drop down. How do I achieve this?

**Comment by torkelo** [comment]
There is no way to do this currently, we hope to solve use cases like this using a new form of scripted dashboard (no ETA)
