### ISSUE TITLE
Grafana and Influxdb Performance Issues

### ISSUE THREAD

**Issue by gitvegas** [grafana/grafana#2000]
I just have 15000 rows with 10 columns of data, so small and my Grafana 2.0.2 has become extremely slow! Wait 10sec between doing anything, zoom or edit or refresh view etc. Running on linux redhat with 4gb ram on a 4cpu 64bit machine with 200GB space available. Please suggest what can i do if its starts choking at such small levels, i was hoping for millions and billions of row data inserts. Is it Influx issue or Grafana issue? Influx and Grafana are all running on same box

**Comment by torkelo** [comment]
You first need to check if it is an InfluxDB issue or Grafana issue? 

Check chrome dev tools (F12) network tab to see how long queries take. Grafana is usually really fast (around 12-30ms to render a graph, becomes more slow if there are many data points or many series but still 10 series with 1000 data points each usually renders within 100ms). 

What can slow Grafana down is if you do not have a group by time (aggregate data in influxdb). Also keep in mind that you should almost always only have one column in InfluxDB, you should not filter on column values as these are very expensive in InfluxDB (no indexes on columns)

**Comment by gitvegas** [comment]
I have two simple queries, each calling just one attribute. So F12 shows one query is taking 1.8sec and the other is taking over 21sec always i refresh this graph page. Yes, i have a time column but in my query im leaving everything default and just select X attribute per query.

I did not understand what you meant by "Also keep in mind that you should almost always only have one column in InfluxDB, you should not filter on column values as these are very expensive in InfluxDB (no indexes on columns)".  Do you mean out of my 10 columns i should have 1 column i should not filter? But i have 8 columns doing nothing? Sorry not clear on this

**Comment by torkelo** [comment]
@gitvegas what I mean is that you should split your metrics into many series, if you only select one column then only have one column per series. InfluxDB gets very slow if you have multiple columns because all columns are read from disk (even when only one column is selected). 

Anyway I direct  you to the influxdb mailing list, they should be able to help you speed up your influxdb queries.

**Comment by gitvegas** [comment]
Thanks for your answers and support, will try splitting the columns and see how it goes, cheers

**Comment by gitvegas** [comment]
One last question, some times you want to query column X based on column Y condition (where Y > 100 or where city in ('NY') etc). So how would i do that if i have each column in a different table/series? After your answer i will sure go to influx guys if i have more questions, cheers

**Comment by torkelo** [comment]
@gitvegas what you want to do is not really what influxdb is great at, for queries like that you want SQL or elasticsearch.  InfluxDB 0.8 is really slow when filtering based on columns (no column indexes). In InfluxDB 0.9 which is a complete rewrite you can only have one value column. The rest will be tags.
