### ISSUE TITLE
Zendesk alerting support

### ISSUE THREAD

**Issue by edernucci** [grafana/grafana#20003]
**What would you like to be added**:
Add support for Zendesk alerting.

**Why is this needed**:
Here at [Greenpass](https://www.greenpass.com.br) we use Zendesk platform for customer relations and the entire company uses Grafana to get insights about our systems health. Sometimes our users want to send this insights directly to Zendesk instead of using other platforms.

I just want to know if this can be accepted, if yes I'll send a PR in the next few days.

Regards,

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
