### ISSUE TITLE
Bar Guage - thresholds keep resetting.

### ISSUE THREAD

**Issue by adampbrush** [grafana/grafana#20007]
Hi,

I love the new Bar Guage option. I run it with All Values, Retro LCD and remove one of the default threshold options leaving in only Base in Green. I save the dashboard then exit out of it and load it back up, an additional threshold then appears with default value of 80 in Red.

![image](https://user-images.githubusercontent.com/30800227/67555668-a7977c80-f709-11e9-840e-0731b1f6ade4.png)

Grafana v6.2.5 (6082d19)

**Comment by mpwillia** [comment]
I also experience the same issue even with a provisioned dashboard.

**Comment by sinkari-kassim** [comment]
also seeing a similar issue

**Comment by torkelo** [comment]
as a temp workaround specify a really high value for the red second threshold!

**Comment by adampbrush** [comment]
> as a temp workaround specify a really high value for the red second threshold!

That appears to work. Many thanks.
