### ISSUE TITLE
support for google kms to store oauth secrets

### ISSUE THREAD

**Issue by davidsiefert** [grafana/grafana#20001]
My organization has a requirement to securely store the oauth client id and client secret in Google KMS and decrypt in-process (so the secret does not leak into environment and/or filesystem). I'm capable of adding this to grafana and submitting a PR, but would like to discuss the approach and whether or not it would be accepted.

For approach, thinking of having a config attribute in the `auth.<provider>` section called `gcloud_kms_enabled` when set to true will then use additional attributes `gcloud_kms_project_id`, `gcloud_kms_location`, `gcloud_kms_keyring`, `gcloud_kms_key`, `gcloud_kms_key_version` to use when decrypting the `client_id` and `client_secret`. I would add a new function that would be conditionally called out to do this decryption as needed in https://github.com/grafana/grafana/blob/master/pkg/login/social/social.go#L61

Google KMS docs for symmetric use case: https://cloud.google.com/kms/docs/encrypt-decrypt and asymmetric use case: https://cloud.google.com/kms/docs/encrypt-decrypt-rsa
The `NewOAuthService` function does no error handling, so I'm wondering if this should be changed, or if it should use the same error handling style of `os.Exit` as in `loadConfiguration` here: https://github.com/grafana/grafana/blob/fc08c260254bffbd6ecf3ad571a035d8eda614da/pkg/cmd/grafana-server/server.go#L244

**Comment by aocenas** [comment]
@davidsiefert thanks for reaching out with this.
@marefr can you take a look at this one?

**Comment by marefr** [comment]
I thought we already had one issue for supporting Hashicorp Vault, but we don't. Feature request make sense, but lets keep it open and see what the interest of this is.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
