### ISSUE TITLE
Saving dashboards does not work well when editing panels with keyboard

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20017]
**What happened**:
Grafana requires you to click in another field after you've edited, or your change doesn't hold if you press "Escape" or another key to navigate back.

**What you expect to happen**
This requires more investigation when it comes to navigating with keyboard.

**Anything else we need to know?**:
Original discussion: https://news.ycombinator.com/item?id=21344459

**Comment by aocenas** [comment]
@sarlinska Should this be assigned to some project? I assume this is going to be a bit long term but probably good to add as a part of the new form design and unification of their behaviour.

**Comment by sarlinska** [comment]
I think we can treat this as a part of new form design. @torkelo what do you think?

**Comment by torkelo** [comment]
This was fixed in 6.4 https://github.com/grafana/grafana/pull/19320  

now when you hit escape and input has focus it will blur instead of existing panel edit mode
