### ISSUE TITLE
Drilldown links with ${__value.time} do not work for single test results

### ISSUE THREAD

**Issue by dweineha** [grafana/grafana#20019]
We've got some nice drilldown links for all our testruns, and in most cases it works. But whenever we either add a new testcase, add a new machine, or a pick such a short date range that there's only one result, the Datalinks fail to work as intended.

The trouble seems to be ${__value.time}. Whenever there's only one datapoint for a particular series ${__value.time} is passed literally to the Datalink instead of the expected timestamp.

Trivial SQL query to visualise the problem:

SELECT
  UNIX_TIMESTAMP("2019-10-24 11:12:23") AS time,
  1 AS value,
  "result: " AS "metric"

Now add a Datalink with, say, http://localhost/${__value.time} as URL, with Details as title.

Expected behaviour: clicking Details will open the URL http://localhost/1571904743
Actual behaviour: the URL will instead open the URL http://localhost/${__value.time}

**Comment by torkelo** [comment]
i have tried to replicate this, so far without success. 

Setup 2 data links, and a query that only returned 1 datapoint. 

![image](https://user-images.githubusercontent.com/10999/72595310-d5a3eb80-3909-11ea-9711-9ac91c15b0c7.png)

Can you use query inspector and detail the exact query response?

**Comment by simonc6372** [comment]
This can be reproduced on play.grafana.org. 
Edit the "memory/CPU" graph. 
Under visualization, add a data link. 
![image](https://user-images.githubusercontent.com/8004654/72597079-ebfb7880-3904-11ea-8987-a4b4529cd25c.png)

Now, the memory graph should have annotations at every data point,
click on the first one, and hover over the title "foo" and you should see a link with ${__value.time} in there. 
Hover over the next one, and you see an actual timestamp. 

![image (6)](https://user-images.githubusercontent.com/8004654/72597247-3e3c9980-3905-11ea-8e58-6307bc7db5f6.png)
![image (7)](https://user-images.githubusercontent.com/8004654/72597250-40065d00-3905-11ea-9373-fd3f106051c1.png)

**Comment by torkelo** [comment]
Was able to replicate against 6.5.x branch but not master, so something in master has fixed this. 

So 6.6 beta is next week and stable soon after!
