### ISSUE TITLE
Loki: Overlapping label stats

### ISSUE THREAD

**Issue by codesome** [grafana/grafana#20010]
**What happened**:
![Screenshot from 2019-10-25 11-08-05](https://user-images.githubusercontent.com/15064823/67559247-d8cb7900-f718-11e9-8609-f54878c32a5e.png)

The stats of the labels overlap when clicked on different labels. The overlap stays similar irrespective of order of labels clicked. So if I click on the label which is displayed in the front first and the label which is covered second, the second label stats will appear behind the first.

**What you expected to happen**:
The old stats to collapse and only the clicked stats to display.

**How to reproduce it (as minimally and precisely as possible)**:
Click on stats of 2 or more labels without closing any.

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Loki
- OS Grafana is installed on: Linux 5.0.0-32-generic 18.04.2-Ubuntu, using docker image.
- User OS & Browser: Linux 5.0.0-32-generic 18.04.2-Ubuntu, Chrome 78.0.3904.70 (64-bit)

**Comment by aocenas** [comment]
There is an ongoing work to make this UI a different https://github.com/grafana/grafana/pull/20034 so this will go away once that is merged.

@davkal added it to our backlog to track it and close it once the new UI is merged.

**Comment by ivanahuckova** [comment]
https://github.com/grafana/grafana/pull/20034 fixes this issue.
