### ISSUE TITLE
Public / anonymous access to dashboards

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20022]
**What would you like to be added**:
Currently, there's no way to access dashboards unless you have an account on Grafana. There's no way to share dashboards with the public. Now it applies to all dashboards, all or nothing. I need something that can be assigned per dashboard

**Why is this needed**:
Original discussion: https://news.ycombinator.com/item?id=21346294

**Comment by davidxianggao** [comment]
the anonymous access is restricted to a specific organization. maybe can group the public dashboards into a specific organization called "public". True, it sounds lots of overhead in duplicating the datasouces in the new "public" organization.

**Comment by torkelo** [comment]
Grafana has always supported anonymous access so that you do not need to login to access any dashboard. 

Example: https://play.grafana.org
