### ISSUE TITLE
Support horizontal graph crosshair 

### ISSUE THREAD

**Issue by dweineha** [grafana/grafana#20021]
Our old system for visualising test results had a cursor with both horizontal and vertical support lines from the cursor when hovering over graphs; Grafana (by default) only shows a vertical support line, and at least so far I've been unable to find a configuration option that allows changing the behaviour.

Digging around in the source code I noticed that simply by changing crosshair:{mode:"x" to mode:"xy" will give us the behaviour that we want. Manually changing the code whenever a new version of Grafana is released is a bit frustrating though.

Feature request: add a configuration option that allows for selecting the preferred crosshair mode.

**Comment by MarvinGS** [comment]
I also edit the "xy" into the code manually and additionally change the color to something with more contrast a few lines up. Should i ask for the color-setting in another issue or can this be a common feature request?

**Comment by monkz** [comment]
Hi,
@dweineha 

where did you change it? I'm searching for this too.

**Comment by dweineha** [comment]
Open /usr/share/grafana/public/build/app.*.js
Search for crosshair:{mode:"x
with: crosshair:{mode:"xy"

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by error401de** [comment]
For future Google users: The file to be edited changed, find more info here: https://community.grafana.com/t/horizontal-crosshair/54719/3
