### ISSUE TITLE
Allow the context menu for values in graphs to be populated through an SQL query

### ISSUE THREAD

**Issue by dweineha** [grafana/grafana#20028]
Each value in our graphs is typically the median of multiple values. As long as the behaviour is stable the individual datapoints don't matter much; we track for regressions or improvements. But if there's a lot of variance from value to value it's nice to know whether the variance is due to oscillation between two sets of results, or if the whole set of measurements are consistent.

For this reason it'd be nice to be able to do an SQL query that'll be used to populate the context menu (to be able to have the necessary information to quickly drill down to the correct data it's necessary to be able to pass extra data along with value/time/metric, such as a table ID; hence I've filed a separate ER about that).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
