### ISSUE TITLE
Variables in alert metrics

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20024]
**What would you like to be added**:
It would be good to be able to use variables in alert metrics. Currently, dashboards are coupled to alerts, it's very frustrating not to be able to define alerts on a templated dashboard.

**Why is this needed**:
Original comment: https://news.ycombinator.com/item?id=21343745

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/6557
