### ISSUE TITLE
Please allow passing anxilliary information along with values

### ISSUE THREAD

**Issue by dweineha** [grafana/grafana#20026]
Before the introduction of the context menu for values it wasn't really meaningful to include extra data in your SQL queries, but now that there's a context menu there's great potential for improvement.

We're making use of the Datalink feature to get to a drilldown page, but we have to have an intermediate database query to do a lookup by combining date, testcase name, etc, since the date alone may not be unique (with lots of machines producing data there's always a chance that two values have the same timestamp).

Being able to pass along extra data along with time, value, and metric would solve this; if we, for instance, could pass id directly we wouldn't need the intermediate query. There's at least one more use case, but it requires yet another enhancement that I'll file a separate ER for...

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
