### ISSUE TITLE
The "Fahrenheit" unit is misspelled

### ISSUE THREAD

**Issue by HeyBanditoz** [grafana/grafana#20039]
**What happened**:
The "Fahrenheit" unit is misspelled. It is instead spelled "Farenheit" which I believe is incorrect.

**What you expected to happen**:
Correct spelling.

**How to reproduce it (as minimally and precisely as possible)**:
Under visualization when editing a visualization, under the y axis, find "Farenheit (°F)" notice the incorrect spelling.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Elasticsearch 7.4.0
- OS Grafana is installed on: Ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tedpearson** [comment]
I mean this is great and all, but when trying to import a dashboard from an old grafana version, new grafana is all confused about this "farenheit" unit. 😭

**Comment by martinacat** [comment]
Sorry for the inconvenience. This has been addressed in #21249 thanks to @ryantxu.
