### ISSUE TITLE
The engine “node” is incompatible with this module. Expected version “>=10 <11”. Got “12.13.0”

### ISSUE THREAD

**Issue by Kingbadger3d** [grafana/grafana#20041]
Hi Guys, Having some problems.

Im trying to build grafana from source on Ubuntu 16.04.

Ive followed the build from source instructions on the Grafana website but when I get to:

yarn install --pure-lockfile

I get the following console errors:

root@james-MS-7C02:~/grafana# yarn install --pure-lockfile
yarn install v1.19.1
[1/5] Validating package.json…
error grafana@6.5.0-pre: The engine “node” is incompatible with this module. Expected version “>=10 <11”. Got “12.13.0”
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

How do I fix this? Cheers James

**Comment by torkelo** [comment]
please use node LTS

**Comment by eleijonmarck** [comment]
One need to use node 10+ < 11 as of current installation.

Try checking
```
nvm ls-remote
```
