### ISSUE TITLE
unable to visualize null (no data)

### ISSUE THREAD

**Issue by test1432** [grafana/grafana#20049]
I am trying to visualize my kafka connector status as down using table visualization and range filter applying to specific column.

Whenever the connector is down, it wont give me any data(no data) at that time, I want to visualize that as Down. However if I write range as "null" to "null" as down it is not working.

- Grafana version: Grafana v5.2.4 (0bbac5c)
- Data source type & version: Prometheus 2.4.2
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10, chrome latest

**Comment by torkelo** [comment]
dont use the range mapping, use the value to text mapping.

And make sure your query returns null.
