### ISSUE TITLE
Active OrgId as dashboard template variable

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#20043]
**What would you like to be added**: A particular panel to be able to retrieve the id of the currently active organization via a variable in the query.

**Why is this needed**: In cases of multi-tenant deployments where organizations share a dashboard template, doing so would be useful to avoid hardcoding or manually editing queries while provisioning dashboards.

**Comment by torkelo** [comment]
Does your backend validate the orgId using in the query? Anyone could fake it

**Comment by anirudh-ramesh** [comment]
I've done a test using the PostgreSQL database I use, and over there, there are a few special considerations:
1. Every Grafana user has a separate pg username, which means each Grafana user has a separate datasource.
2. Row-Security (RS) has been enabled in the tables being accessed by Grafana. This exposes the Grafana user to only those rows the corresponding pg user has access to.

The Grafana user could technically maliciously edit the OrgId variable, but that would not show him/her data he/she does not originally have access to since the pg user corresponding to that Grafana user can't access any other rows.

This feature add would help in only one case - allowing the Grafana server admin to replicate the dashboard (I use wizzy) across different orgs, while having to manually create the datasource for each org.

**Comment by torkelo** [comment]
added in 6.7
