### ISSUE TITLE
Cloudwatch: use GetMetricData for all time series requests

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#20057]
We should use the GetMetricData api instead of GetMetricStatistics for all time series requests since it's [best practice](https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-getmetricdata-api/). Also it does support search expressions, which will allow us to build dynamic queries.

### Current implementation
Initially the Grafana Cloudwatch datasource was only using the GetMetricStatistics API. That API allowed for multiple stats to be added to one single query, hence the possibility of adding more than one stat in the Grafana Query editor. About a year ago, support for expressions were added so two new fields were put in the query editor - Id and Expression. Expressions are not supported by the GetMetricStatistics API, so in the case the Id field, the expression field or both of them had a value, the query would be sent to the GetMetricData API. All queries that did not have values for these two fields would be sent to the GetMetricStatistics API. Since more than one stat is not allowed in the GetMetricData API, the ID field and the Expression field become hidden once more than one stat is added in the Grafana Query editor. 

### GetMetricData limitations
A maximum of 100 MetricDataQueries can added into one single GetMetricData request. Out of these 100 queries, a maximum of 5 can be search expressions.

#### Queries with multiple stats
Grafana Queries that have more than one stat should generate one MetricDataQuery for each stat, and this needs to be done in the backend in order to not break any existing alerting rules. 

The initial idea was to issue multiple GMD requests in the case there's either more than 5 search expressions or more than 100 metric stats queries. After careful investigations, we came to the conclusion that Grafana should reflect 100% with the API that it consumer, i.e if for example more than 5 search expressions are being used, the error that is being returned by the cloudwatch API should be displayed in the grafana GUI. That way we won't need to make changes in Grafana in the occasion limits are being changes in the cloudwatch api.

All MetricDataQueries must have an ID. In the case the user has specified an ID in the query editor we should use that as long as it's unique. If not, we should generate an ID using the following pattern: 
`query[RefId]`
If the query had more than one stat, we need to generate two MetricDataQueries from that query. In the case, the ID should follow this pattern: 
`query[RefId]_stat` e.g queryD_Average
The reason for the query prefix is that a MetricDataQuery cannot start with capital letters. 

Inferring timeseries unit and for the graph panel will not be supported since the unit is not being returned by the GetMetricData api.

**Comment by mtanda** [comment]
Thanks for your great work!
I'm looking forward to use new CloudWatch datasource feature.

But, I need to mention about one pitfalls when CloudWatch datasource use GetMetricData.

According to limitation document, allowed GetMetricData TPS is 1/8 of GetMetricStatistics.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

* GetMetricData
  * 50 transactions per second (TPS). The maximum number of operation requests you can make per second without being throttled.
* GetMetricStatistics
  * 400 transactions per second (TPS). The maximum number of operation requests you can make per second without being throttled. 

If the Grafana user has too much Alert rule, the user may hit the limit.
So, the change should be mention about throttling in CHANGELOG or Release note.

I added metrics for measureing GetMetricData API call, `grafana_aws_cloudwatch_get_metric_data_total`.
It could help to investigate throttling issue when user hits limit.

**Comment by sunker** [comment]
Thanks @mtanda! 

Yes that's true. I agree, we should definitely put that in the release notes and/or changelog. It should also be stated in the docs that if necessary, a rate limit increase can be requested at amazon using the form [here](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_cloudwatch)

**Comment by sunker** [comment]
@mtanda next release will also include a rewrite of the query editor to react. That, replacing GMS with GMD and dynamic queries are all in [this](https://github.com/grafana/grafana/tree/feature/cloudwatch) branch. If you feel like and have the time, it would be great if you could test it out so that I can get you feedback.

**Comment by mtanda** [comment]
@sunker Of course, I'll take time to test it :-)

**Comment by mtanda** [comment]
@sunker Sorry for late feedback.
I tested, and found a bug.

Please check this issue.
https://github.com/grafana/grafana/issues/20436
