### ISSUE TITLE
Color picker disappears right after it's opened

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#20050]
Behaviour can be easily reproduced by clicking on color picker trigger, i.e. in thresholds editor: https://drive.google.com/file/d/1BnCUzZX0Jqer-8rSVUDiVesksOGtYelD/view

Haven't found a fix yet, but seems like color picker trigger's `onMouseLeave` handlers are called when the color picker popover is opened.

**Comment by Theoooooo** [comment]
Humm i also see this issue happened around the 6.4.0 update. dunno what changes in the code trigger this but i can confirm it is happening since multiples version

**Comment by peterholmberg** [comment]
I'm not really sure where to go with this. I've been investigating the different `onMouseLeave` and `onMouseEnter` events that are specified on different components `<ColorPicker />`, `<ColorPickerTrigger />`, `<Popover />`, and I can get it to not close as soon as you click the trigger but with the side effect that the color palette does not close when the mouse is leaving it.

Another thing we discussed was to use `<ClickOutsideWrapper />` and wrap the Popover and Trigger. This did not solve the issue, the popover flickers (opens and closes).

**Comment by peterholmberg** [comment]
When doing isolated tests in storybook in `<ColorPicker />`, `<ThresholdsEditor />` the ColorPicker works just fine. The only time this bug happens is when the ColorPicker is implemented as a child in the `<EditorTabBody />`. Which leads me to believe there's something fishy going on there.

**Comment by RedShift1** [comment]
Can confirm this is happening on Chrome 78.0.3904.87. Color picker does not dissappear on Firefox 68.0.1.
