### ISSUE TITLE
Connecting grafana to influxdb fails on raspberry with docker-compose

### ISSUE THREAD

**Issue by tengelmeier** [grafana/grafana#20054]
**What happened**:

Adding an InfluxDB datasource in an docker-compose environment as http://influxdb:8086 to grafana always fails with "Network Error: undefined(undefined)"

**What you expected to happen**:

Successfully connected InfluxDB datasource

**How to reproduce it (as minimally and precisely as possible)**:

Start an docker compose environment from 

```

version: '2'
    services:
      # Define an InfluxDB service
      influxdb:
        image: influxdb:1.7.8
        volumes:
          - ./data/influxdb:/var/lib/influxdb
        ports:
          - "8083:8083"
          - "8086:8086"
          - "8090:8090"
        restart: always
        network_mode: "host"

      grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
          - "3000:3000"
        env_file:
          - './grafana/env.grafana'
        links:
          - influxdb
        restart: always
        volumes:
        # sudo chown 472:472 data/grafana/
          - ./grafana-provisioning/:/etc/grafana/provisioning
          - ./data/grafana:/var/lib/grafana
```

**Anything else we need to know?**:

Connecting to a InfluxDB on another host as  http://192.168.8.8:8086 works fine

**Environment**:
- Grafana version:
6.3.5

- Data source type & version:
influxdb: 1.7.8

- OS Grafana is installed on:
Rasperry PI / Jessie 
Docker-compose: 1.8.0-2 (also upgraded to 1.18)
docker: 19.03.3

- User OS & Browser:
macOS 10.14, Safari

- Grafana plugins:
N/A

- Others:

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

This seems like a docker networking question not a Grafana bug
