### ISSUE TITLE
Cloudwatch: Support dynamic queries using dimension wildcards

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#20058]
Depends on #20057

In the current version of the datasource, we have support for search expressions using the expression field. However, that field has no intellisense and also using search expressions has a learning curve. Therefore, we should provide and easy-to-use way of building dynamic queries using the dropdown menus that are already present in the query editor along with wildcards.

In the case a dimension values contains either a multi-template variable or an asterix (*), Grafana will consider it a dynamic query and generate a search expression which will be execute it in the GetMetricData api. The search expression must be interpreted in the backend in order to not break any existing alerting rules. 

Queries that are not considered dynamic will be build using either expression (if actively defined in the expression field by the user) or [metric stat](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#MetricStat)

### Wildcard support in dimension values
It should be possible to monitor not only one specific value of a given dimension key, but all of its values. In this example, this query allows customers to monitor the memory usage for EC2 instances based on a specific ImageId. If new instances get created due to an autoscaling event, or terminated due to a down scaling event, the panel would only show those metrics that actually have data points available in the selected time range.
![image](https://user-images.githubusercontent.com/2388950/67662454-c1340080-f963-11e9-892f-8da7d525113b.png)

#### Exact/not exact match of dimension names
We should introduce a new boolean switch in the GUI named `Parse Exact` or something similar. In the case this switch is tipped, we should only return metrics that exactly match all the dimension names that was specified. In the example above, the metric must have ImageId and InstanceId. If the case Parse Exact is not tipped, we should return not only the ones specified but also other dimension names. 
Parse exact: `SEARCH('{<namespace>,<dim1name>,<dim2name>,...} MetricName="<metricName>" <dim1Name>="<dim1Value>"  <dim2Name>="<dim2Value> ..."', 'Maximum', 300)`

Parse exact not tipped: `SEARCH('Namespace="<namespace>" MetricName="<metricName>" <dim1NameIfValueKnown>="<dim1Value>"  "<dim2NameIfValueNotKnown>"', 'Maximum', 300)`

More details about this will be provided later on. 

### Multi-value template variables in dimension values
In the current version we have partial support for multi template variables in dimensions, i.e it works when you have a maximum of one template variable. However that support was implemented in a very unconventional way. Each value in the multi template variable would, under the hood in the frontend, generate one new query. The way this partial support for template variables was implemented has proved to be very prone to errors, causing numerous issues. 

However, implementing support for multi template variables can be done using search expressions. e.g: 
![image](https://user-images.githubusercontent.com/2388950/67668595-884e5880-f970-11e9-81ac-7e5e76a1e4cb.png)
Would generate the following search expression: 
`SEARCH('{AWS/EC2,InstanceId} MetricName="CPUUtilization" "InstanceId"=("i-037148bbe1af6f593" OR "i-05298619f68572091" OR "i-0b4ec1f86c31a4ce3" OR "i-0bb060dabf506ef5c")', 'Sum', 600)`

**Comment by mtanda** [comment]
@sunker 
Leave comment about `Multi-value template variables in dimension values`.

We need to care about SEARCH expression maximum length.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html
> The maximum search expression query size is 1024 characters. You can have as many as five search expressions on one graph. A graph can display as many as 100 time series. 

The length of instance id string is `"i-037148bbe1af6f593".length == 19`.
19 + 2 (double quote x 2) + 4 (` OR `) = 25
1024 / 25 = 40.96

So, SEARCH expression can handle only 40 (or less) instance id at once.
Current implementation can handle 100 instance id.
To support 100 instance id, CloudWatch datasource split instance ids to fit maximum length, and call API three times or more.

**Comment by sunker** [comment]
Correct @mtanda. At the moment expressions are limited to 1024 char, however there's indications that api limit will be increased in the future. 
I'll make sure this is pointed out clearly in docs and release notes. Also I think in most cases where you have something like 100 instances in a multi template variable, you'd be better off with a wildcard instead. 

![Skärmavbild 2019-11-08 kl  14 34 25](https://user-images.githubusercontent.com/2388950/68480358-e4e52980-0234-11ea-8f37-b4a2ac7f4383.png)

**Comment by Eraac** [comment]
Can this work with a prefix (ex. `prefix_*`), actually i want to monitor loki table in dynamodb (with autoscaling), so i can't predict name and don't want to change my dashboard every week. 

Does I miss something (filters maybe?) or is just impossible actually?

**Comment by rehevkor5** [comment]
@Eraac It appears to be possible if you do it within the `Expression` field, but you must not add double-quotes around your value that includes the asterisk. But sometimes the legend doesn't show the value of the Dimension, only the name of the metric, for some reason.

**Comment by justinTM** [comment]
hi @rehevkor5 how would you use `Expression` field? would it be `Math` dropdown option? or `Classic condition`?
