### ISSUE TITLE
Grafana 6.3.5 update to 6.4.3 - Unable to find application file

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [grafana/grafana#20064]
Hello 

I just upgraded **grafana:amd64** package on **Debian 9.11** (**Stretch**) from version **6.3.5** to version **6.4.3** 
And after the update, EDIT mode of all my dashboards stopped working
I use **Graphite** as a data source (for Icinga visualization).

Now, even if I try to create a new dashboard and add a panel to it, I always get an error (in different browsers)

> Unable to find application file
> Grafana has likely been updated. Please try reloading the page.
> Reload
> Error: Неопределенная ошибка.
> 
>     in div
>     in div
>     in t
>     in t
>     in div
>     in t
>     in t
>     in div
>     in div
>     in t
>     in Connect(t)
>     in div
>     in t
>     in div
>     in e
>     in DraggableCore
>     in e
>     in div
>     in ReactGridLayout
>     in Unknown
>     in SizeMeReferenceWrapper
>     in SizeMeRenderer(Component)
>     in SizeMe(Component)
>     in e
>     in div
>     in div
>     in div
>     in t
>     in t
>     in div
>     in div
>     in e
>     in Connect(e)
>     in Suspense
>     in t
>     in Unknown
>     in Unknown
>     in Unknown
>     in Unknown
>     in t
>     in t
>     in a

Before the update, editing all the panels worked successfully.
Can you tell me what could be the problem?

**Comment by torkelo** [comment]
Strange, no similar reports. 

What browser version are you using? What plugins installed? Please share dashboard json.

**Comment by Aleksey-Maksimov** [comment]
Thanks for the quick response. 
I did not install any plugins separately.

```
# grafana-cli plugins ls

Restart grafana after installing plugins . <service grafana-server restart>
```



I just tried to create a new blank dashboard. 
Here is json:

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 20,
  "links": [],
  "panels": [],
  "schemaVersion": 20,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "New dashboard",
  "uid": "_YN-Yc0Zk",
  "version": 1
}

```

**Comment by Aleksey-Maksimov** [comment]
Maybe there are not enough files in the package for Debian 9? How can I verify the completeness of the installation of Grafana?

The grafana-server service starts successfully. 
There are no obvious errors in the log.
```

# systemctl status grafana-server.service

● grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-10-28 22:24:46 MSK; 13min ago
     Docs: http://docs.grafana.org
 Main PID: 44117 (grafana-server)
    Tasks: 13 (limit: 9830)
   CGroup: /system.slice/grafana-server.service
           └─44117 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid --packaging=deb cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.

Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing SearchService" logger=server
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing TracingService" logger=server
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing UsageStatsService" logger=server
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing CleanUpService" logger=server
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing NotificationService" logger=server
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing provisioningServiceImpl" logger=server
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Backend rendering via phantomJS" logger=rendering
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin.
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="Initializing Stream Manager"
Oct 28 22:24:47 MON20 grafana-server[44117]: t=2019-10-28T22:24:47+0300 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

All dashboards that were created in the previous version of Grafana successfully work in view mode and show graphs. 
But if I try to edit any dashboard, I get an error.

**Comment by Aleksey-Maksimov** [comment]
Oops .. There seems to be a problem in the browser.

Internet Explorer 11 - there is a problem
Chrome 64 - no issue
Firefox ESR 68 - no issue

I think the question can be considered closed. 
Thank.
