### ISSUE TITLE
Sort notification channels alphabetically 

### ISSUE THREAD

**Issue by themoffatt** [grafana/grafana#20067]
**What would you like to be added**:
On the `/alerting/notifications` page, the ability to sort that list by notification name would be awesome. Filtering by type would be great too.

**Why is this needed**:
We're loading up a lot of new notification channels for various alerts and it would be really helpful to sort them or filter them while managing the list.

**Comment by aocenas** [comment]
@dprokop @sarlinska seems like in this case we do not sort in any meaningful way and just render it the way DB sent it to us. I think mostly we just either sort by time created or not at all. Ideally I think we should probably have the basic table component be sortable at least. Is there any effort in that direction?

**Comment by sarlinska** [comment]
UX wise it's nothing fancy – it should be a quick mockup for us. @dprokop it's probably a bigger workload on your side.

**Comment by jstangroome** [comment]
Ideally the "Send to" selector drop-down in a Panel's Alert tab would also be sorted.

Not sure if this should be raised as a separate issue.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
