### ISSUE TITLE
Docs feedback: alerting/rules.md

### ISSUE THREAD

**Issue by nikoalch** [grafana/grafana#20065]
Add all supported datasources for alerting

**Comment by aocenas** [comment]
Hey @nikoalch, I assume you mean the list in https://grafana.com/docs/alerting/rules/#execution? Do you know which ones are missing?

**Comment by oddlittlebird** [comment]
@ryantxu, what is the official stance on where to list Enterprise plugins?

**Comment by keremgocen** [comment]
I'm looking for an issue to contribute, is this a good one @oddlittlebird ?

**Comment by oddlittlebird** [comment]
@keremgocen , not until @ryantxu makes a call.

**Comment by oddlittlebird** [comment]
@mjseaman or @09jvilla, any thoughts on this?

**Comment by achatterjee-grafana** [comment]
Closing, old issue with no movement.
