### ISSUE TITLE
PHP deleting user from database error

### ISSUE THREAD

**Issue by hunainhafeez2016** [grafana/grafana#20069]
Hi i am hunain!
I want to delete user from database using mysqli.
I have created this method but it didn't work please help me.
`if (isset($_POST['yes'])) {
        if ($mysqli) {
            $id = $_SESSION["uId"];
            $sql = "DELETE FROM signedup_users WHERE id='$id'";
            $result = mysqli_num_rows($sql);
            if ($mysqli->query($result) === TRUE) {
                header("Location: logout?accdel=Account deleted successfully! <br> Come back again");
                exit();
            }else{
                header("Location: accounts?error=There is something went wrong!");
                exit();
            }
        }else{
            mysqli_connect_error("COULD NOT CONNECTED TO THE DATABASE!");
        }`
Thanks in advanced

**Comment by torkelo** [comment]
Grafana does not use PHP,

**Comment by torkelo** [comment]
Where/how did you run it?

**Comment by hunainhafeez2016** [comment]
I am running it in my PC at localhost server i have checked many websites
To fix this bug but i can't find it.
Help me please
