### ISSUE TITLE
Lines do not display with client side rendering on Raspberry Pi

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#2006]
Using Raspberry Pi v2, Grafana 2.0.2, Graphite Web 0.9.13 and lines to do display with Flot. Many different browsers (Epiphany, Chromium, etc) and OSes (Raspian, Pidora, etc) were tried with same results. Is this a known issue? If not, any idea on possible causes, work arounds, etc?

**Comment by torkelo** [comment]
@druchoo are you sure it is not an issue rendering? Can you show the render request to graphite (it returns json). Check chrome dev tools (f12) and network tab. Does it return data? I know many use raspberry pi v1 and v2

**Comment by torkelo** [comment]
Updated the above fist sentence, it was mangled :)

**Comment by druchoo** [comment]
Sorry for sparse details. I'm not at the office and don't have access to the device. I will get more info tomorrow. Note that PNG works fine. So anything off the top of your head that would allow PNG to work but prevent Flot?

**Comment by torkelo** [comment]
no not really, try opening chrome dev tool and looks for JS errors, test changing display to points instead of lines (just to see if you see anything). Change time range

**Comment by druchoo** [comment]
Issue was due to incorrect time on the Pi!
