### ISSUE TITLE
Grafana with HDInsights

### ISSUE THREAD

**Issue by bdurgaprasad** [grafana/grafana#20074]
Hi,

I have grafana integrated with HDInsights Hadoop cluster, the problem is with few metrics shows no datapoints error, and few components are displaying metrics

**Comment by aocenas** [comment]
Hey @bdurgaprasad can you provide some more details? Things like Grafana version, datasource configuration and error message or screenshot would help.

**Comment by bdurgaprasad** [comment]
Sorry for the delay, i am attaching the screenshots of the issue
![1](https://user-images.githubusercontent.com/27336365/68183044-43a26d00-ffc1-11e9-91ec-754986bfeb67.jpg)

![2](https://user-images.githubusercontent.com/27336365/68183073-50bf5c00-ffc1-11e9-8a2f-826716a3a777.jpg)

**Comment by bdurgaprasad** [comment]
As you can see some metrics are not visible

**Comment by torkelo** [comment]
you will have to ask for help with the HD Insights plugin authors
