### ISSUE TITLE
When creating notification channel with non-unique uid or name should not return HTTP status 500

### ISSUE THREAD

**Issue by lmuhlha** [grafana/grafana#20089]
**What happened**:
We have a service that creates programmatic dashboards and alerts in Grafana. One step is to check if a notification channel with a certain uid (same as the email address) exists. If it does not exist, the service will try to create it. 
A handful of times, we have run into the service returning a 500 despite the unique uid and the notification channel not existing if you try to look it up with that uid. 
If you then check for a notification channel with the same name (different uid) and delete that, then try making the channel again with the email address as the uid it will work. Then the service we have can find the notification channel as expected.

**What you expected to happen**:
If a notification channel has the same name but a unique UID, the api should be able to create the new notification channel. 

**How to reproduce it (as minimally and precisely as possible)**:
Have an email notification channel that exists with the name you're going to use.

First check if a notification channel exists with the uid you want:
curl -H "Authorization: Bearer" http://grafana/api/alert-notifications/uid/team+alerts@company.com
{"message":"Alert notification not found"}%

Run an API call to create a new notification channel with the same name but a unique uid (uid is the email address in this case):
curl -H "Content-Type: application/json" -H "Authorization: Bearer" -d @alert.json -X POST http://grafana/api/alert-notifications
{"message":"Failed to create alert notification"}%

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.5
- Data source type & version:
- OS Grafana is installed on: linux, ubuntu
- User OS & Browser: mac & chrome
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
Seems like we have a check for both UID and name uniqueness https://github.com/grafana/grafana/blob/2a78d2a61cf05df68360614cd9f020570fd7993b/pkg/services/sqlstore/alert_notification.go#L235. @marefr can you take a look? I also had an impression that only UID should be unique but maybe I am mistaken.

Also I think these should be 400 errors not 500.

**Comment by marefr** [comment]
@aocenas To me seems like an error is returned from some sql query why a 500 is returned. @lmuhlha can you please inspect the Grafana server log when this happens to see the actual error and include it here. Thanks

**Comment by aocenas** [comment]
@marefr we are doing explicit check for whether the name already exists, I linked the line where we are doing it in the previous comment. So the question is more whether this is expected and whether this should be closed or whether this should be changed so that only UID needs to be unique.

**Comment by marefr** [comment]
@aocenas tracked back the PR introducing UID for notication channels and found this https://github.com/grafana/grafana/pull/14229#discussion_r240487723. Based on this it's expected that both uid and name is unique.

**Comment by marefr** [comment]
So what's left would be to return 400 instead of 500 status. Updating the title to reflect this.

**Comment by lmuhlha** [comment]
Thanks for looking into this and confirming that this is the expected behavior. Returning a 400 would make more sense 👍

**Comment by marefr** [comment]
Suggestions for fixing this:
- Add a couple new errors, `ErrAlertNotificationWithSameUIDExists` and `ErrAlertNotificationWithSameNameExists` [here](https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/models/alert_notifications.go#L11-L18).
- Return `ErrAlertNotificationWithSameUIDExists` from [here](https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/services/sqlstore/alert_notification.go#L302). 
- Return `ErrAlertNotificationWithSameNameExists` from [here](https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/services/sqlstore/alert_notification.go#L312).
- Add a check [here](https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/api/alerting.go#L276) to see if returned error is any of above and if so return 400 HTTP status instead of 500.

**Comment by jgulick48** [comment]
Would it make more sense to return a 409 (Conflict) rather than a generic 400 (bad request)?

**Comment by marefr** [comment]
@jgulick48 probably make sense :+1:
