### ISSUE TITLE
Add ref option to Input component similar to FilterInput

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#20083]
Would like the ability to add ref to Input component the way that we can add to FilterInput (specifically to focus like this).

```
        <FilterInput
          ref={element => element && element.focus()}
        />
```

**Comment by DislayPS** [comment]
I would like to use the React hook useRef for the Input grafana ui component please.
useRef documentation: https://reactjs.org/docs/hooks-reference.html#useref

I would like to use it like this:
const refInput = useRef<HTMLInputElement>(null);
<Input ref={refInput}  />
