### ISSUE TITLE
make it simpler to query tagged graphite data

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20087]
One annoyance (IMHO, though i'm not sure what's the current opinion of @DanCech) with graphite tags, is that querying the data is non-obvious.
The Graphite query editor shows a metric name autocompleter, so it makes sense trying to use it, but it only works for hierarchical, non-tag based metrics.

For tag based metrics, you [have to use the seriesByTag function](https://graphite.readthedocs.io/en/latest/tags.html#querying). In Grafana this is hidden deep inside all the processing functions, so it's hard to find. I've seen plenty of people struggle with this.

I would like for Grafana to steer people more in the right direction to query for tagged series.
I would also like graphite to eventually adopt a syntax in which tag lookups are part of the metric pattern (expression), rather than requiring a function. And perhaps we'll get there at some point. So something to keep in mind as we design a new UI.

**Comment by DanCech** [comment]
The Graphite query editor in Grafana offers all tags in the top-level dropdown when selecting a series, in the same place that you select the first "node" for hierarchical metrics.  Once you choose a tag, the UI provides auto-complete inputs for selecting a value and additional tags (with contextual filtering based on the stored series).

**Comment by Dieterbe** [comment]
hmm you're right. tested it in one of our instances and it seems to work well.
i'm working on a customer issue right now where these don't show up, but that seems more likely a graphite or metrictank problem then.

**Comment by DanCech** [comment]
If this isn't working, the first thing to check would be that the version setting in the datasource is correct, if that is set to 0.9.x then some of the advanced functionality will be disabled.

**Comment by tmm1** [comment]
> The Graphite query editor in Grafana offers all tags in the top-level dropdown when selecting a series, in the same place that you select the first "node" for hierarchical metrics.

I have a Grafana cloud instance (which was pre-configured with the hosted graphite source and version set to `1.1.x`) and I'm not seeing the tags listed in the query editor.

I had to use `seriesByTag` instead, and when I do that it's no longer possible to switch to the non-text view. The javascript console on grafana.net shows an error message when I try to click the switcher:

<img width="833" alt="Screen Shot 2020-02-18 at 5 29 03 PM" src="https://user-images.githubusercontent.com/2567/74793104-3bbac000-5274-11ea-8849-7fa37b0b412e.png">
