### ISSUE TITLE
Explore: Add search highlight for all datasources

### ISSUE THREAD

**Issue by denissduan** [grafana/grafana#20098]
**What happened**:
when i search log using keyword at explore,the result keyword can't display hightlight
**What you expected to happen**:
when i search log using keyword at explore,the search result keyword can display with hightlight
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
Hey @denissduan Can you also provide your Grafana version and if you can a screenshot to better understand the issue?

**Comment by denissduan** [comment]
Hi @aocenas 
for example:
if i type keyword at the search bar:
![image](https://user-images.githubusercontent.com/8587100/68000294-7a634500-fc9a-11e9-9831-c214580fef0b.png)

it can display the resul with background highlight custom color like this:
![image](https://user-images.githubusercontent.com/8587100/68000321-9666e680-fc9a-11e9-9a05-1993cafc1813.png)

**Comment by Estrax** [comment]
Seems to be working properly with Loki. We don't have an implementation of highlight within Elasticsearch datasource.

**Comment by Estrax** [comment]
Fixed in #25057.

**Comment by davkal** [comment]
You could use the browser search, that should highlight all matches as you scroll down.
