### ISSUE TITLE
`api_url` in `[auth.github]` is quite confusing!

### ISSUE THREAD

**Issue by tbrand** [grafana/grafana#20093]
**What would you like to be added**:

The name of `api_url` should be changed in grafana.ini or `/user` suffix should be defined in the codes.

**Why is this needed**:

I tried to authenticate with GitHub Enterprise server. Then I'd faced an error below.
```
lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="Error getting user teams: Error getting team member
ships: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.xxx/v3\"}"
```

It's raised by here.
https://github.com/grafana/grafana/blob/master/pkg/login/social/github_oauth.go#L122

It's now solved since I've noticed that `api_url` needs `/user` suffix!!! (as [documented](https://grafana.com/docs/auth/github/))
It means...
```
wrong   : https://my-enterprise-server.com/api/v3
correct : https://my-enterprise-server.com/api/v3/user
```

It's quite confusing! The name of `api_url` should be changed or `/user` suffix should be defined in the codes!

Any comments welcome anyway :)

**Comment by torkelo** [comment]
The defaults have /user and the docs have it. Not sure what else we can do (without a breaking change)

**Comment by tbrand** [comment]
I think grafana team should add an emphasized note about the suffix on the document.

**Comment by torkelo** [comment]
Which document? the docs?

**Comment by tbrand** [comment]
Yup, on this page. https://grafana.com/docs/auth/github/

**Comment by achatterjee-grafana** [comment]
Checking the https://grafana.com/docs/grafana/latest/auth/github/ topic and the code has `/user` suffix defined in the codes. Closing the issue, as the request has been addressed.
