### ISSUE TITLE
DataLinks cannot reference labels when using an Instant Query

### ISSUE THREAD

**Issue by MacroPower** [grafana/grafana#20090]
**What happened**:

I have been using the feature added in https://github.com/grafana/grafana/pull/18918 which allows me to directly reference labels inside DataLinks.

For instance, say I have a label, called `label_name` with the value `foobar`. Normally, I can add a data link `http://${__series.labels.label_name}/`, and upon clicking a metric, be directed to `http://foobar/`.

However, if I use a Prometheus Instant query, it will link me to `http://${__series.labels.label_name}/`. Other data links still work here, such as `${__field.name}`, but trying to reference any labels results in the value in the URL being returned 100% literally.

**What you expected to happen**:

I would expect the behaviour of DataLinks to be consistent across Instant and Non-instant queries.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a graph.
2. Add a query that groups on a label, e.g. `sum by (label_name) (metric)`.
3. Add a legend that adds some additional info, e.g. `foo {{ label_name }} bar`.
4. Add a DataLink with a URL `http://${__series.labels.label_name}/`.
5. Observe that by toggling `Instant`, you can break and fix the DataLinks
a. Instant = off -> DataLink = `http://foobar/`
b. Instant = on -> DataLink = `http://${__series.labels.label_name}/`

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Prometheus 2.13.1
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: Windows 10, Google Chrome

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/result_transformer.ts#L144 

think that should set tags property instead of labels.
