### ISSUE TITLE
Create Dashboard from API based on another dashboard

### ISSUE THREAD

**Issue by oryagel** [grafana/grafana#2010]
Hi,
I want to create some dashboards from code.
The dashboards I want to create are based on an existing dashboard.
So basically, I want to copy an existing dashboard, change the dashboard name and variable values.

How can I do that from API?

Thanks

**Comment by torkelo** [comment]
yes, http://docs.grafana.org/reference/http_api/

**Comment by oryagel** [comment]
Thanks

So it says that I should use `"id": null` in order to create a new dashboard.
But how do I create a new dashboard based on another dashboard?

**Comment by torkelo** [comment]
You read it with a GET request, like `GET http://play.grafana.org/api/dashboards/db/graph-styles`
