### ISSUE TITLE
Singlestat Timestamp in localtime when dashboard set to UTC

### ISSUE THREAD

**Issue by capabilis** [grafana/grafana#20101]
**What happened**:

The dashboard are configured in UTC mode.

I use a panel which show records in a table. In this table, date are shown as UTC
I use a second panel with simplestat which use the first one as datasource, and shown the date of first record. This date are print in local zone

**What you expected to happen**:

The date in simplestat should print in UTC mode

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: simple Json 1.4
- OS Grafana is installed on: centos
- User OS & Browser: windows and chrome
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Unable to replicate, the singlestat panel with "Time of last point" and unit: Time & Date: YYYY.... 

Shows the time in UTC
https://play.grafana.org/d/n8QbNg7Zk/utc?orgId=1&from=now-1h&to=now

**Comment by capabilis** [comment]
hello

It works for the last point but not for the first

Best regards

Luc bregeault


Envoyé de mon iPhone

**Comment by capabilis** [comment]
In the dashboard example, change graph to table. 
Modify the first panel to connect directly to table
The time of last point will give the last point in the table.

Now change the first panel to show the first element. It will not show the time of first element.

This function works if you choose local time for this dashboard
