### ISSUE TITLE
Add Support for Nested Teams

### ISSUE THREAD

**Issue by BenB196** [grafana/grafana#20108]
**What would you like to be added**: I would like to have the ability to have nested teams.

Example:

Team A:
- User X

Team B:
- User Y

Team C:
- Team A
- Team B
- User Z

**Why is this needed**: This functionality would be nice to have as it would allow for easier managing of different sub/super teams. A more realistic example of the above is if I have a networking team and a systems team. It would be nice to have them as separate teams, then have a third team for operations which merges the networking and systems teams. 

Currently if I want this setup I need to add all of the networking and system team members to the operations teams. This requires additional configuration, and means that if someone ever joins of leaves either team, two changes are required instead of a single change.

**Comment by torkelo** [comment]
I find it very unlikely that we will do ever do this, but leaving it open as a feature request for now :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
