### ISSUE TITLE
Error when creating two users with empty email

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#2011]
Due to a unique constraint (using the default sqlite database), user creation will fail if the email field is left empty: [admin_users.go:64 AdminCreateUser()] [E] failed to create user: UNIQUE constraint failed: user.email

Maybe set it to NULL ?

**Comment by torkelo** [comment]
wont help, NULL is a value as well

**Comment by torkelo** [comment]
or maybe it will, at least in sqlite3, need to read up on how postgres and mysql handle unique constraints and null values

**Comment by Akeru** [comment]
It will. NULL is not a value (as in NULL != NULL, this is why IS NULL exists). Having a lot of NULL values on an indexed cols is really bad for performances, but that's another story.

**Comment by torkelo** [comment]
well, it loosk like in SQL Server (the windows variant), nulls are treated as a value in the case of uniqueness. So maybe another option save it with a fake email like username@localhost

**Comment by Akeru** [comment]
Hmmm, according to the ANSI standards SQL:92, SQL:1999, and SQL:2003, a UNIQUE constraint should disallow duplicate non-NULL values, but allow multiple NULL values.

Postgres is definitely working (doc : http://www.postgresql.org/docs/9.4/static/indexes-unique.html), and MySQL too (http://dev.mysql.com/doc/refman/5.0/en/create-index.html).
