### ISSUE TITLE
alert query not using available rows

### ISSUE THREAD

**Issue by mmao** [grafana/grafana#20129]
I've posted this to https://community.grafana.com/t/unexpected-empty-result-set-for-alert/22335
but have not gotten any traction with it.

**What happened**:
I've constructed an alert that doesn't seem to be able to pull in results.

**What you expected to happen**:
An alert condition that looks over the past 240h should pick up some rows from the graph query, which outputs the following rows:
```
          time          | ct  
------------------------+-----
 2019-10-21 00:00:00+00 |   9
 2019-10-28 00:00:00+00 |  55
 2019-11-04 00:00:00+00 |  96
 2019-11-11 00:00:00+00 | 141
 2019-11-18 00:00:00+00 | 274
 2019-11-25 00:00:00+00 |  31
 infinity               |   3
                        |   3
```
But the rule test is indicating null series results:
https://i.imgur.com/awdYZOV.png
Note that the rowCount reported here is 8.

I attempted to tweak my query to ditch the infinity and null dates to no effect.

**How to reproduce it (as minimally and precisely as possible)**:
Construct a query that returns a count by dates spaced apart weekly.
Create an alert condition like:
`query (A, 240h, now)` 

See if the Test Rule action reports null results.

**Anything else we need to know?**:
I'm not sure what time range the alerting rules are supposed to operate on. Time range being the “query(A, start, end)” part of the conditions.
Is it the clock timestamps when alerting checks are performed?
Or is it the time variable constructed by the query itself? I had assumed it was the latter, but I’m not sure with this new alert I’m trying to construct.

Here's a similar working alert's test output:
https://i.imgur.com/XfOzPuil.png
There’s an array for the series output, and interestingly, rowCount = 0 for the sql output.

**Environment**:
- Grafana version: Grafana v6.4.0 (c3b3ad4)
- Data source type & version: Postgres 10.3
- OS Grafana is installed on: Ubuntu on Google Compute Cloud
- User OS & Browser: Ubuntu 18.04.3 LTS, Chrome 78
- Grafana plugins: BigQuery
- Others:

**Comment by torkelo** [comment]
please include your query as well and to troubleshoot further you can enable debug logging and set app in dev mode to get full tsdb logs during alert execution

**Comment by mmao** [comment]
This is the query that doesn't work:
```select $__time(time), count from (select date_trunc('week', valuntil) as time, count(*) from pg_user group by 1 order by 1) z order by 1;
```

**Comment by mmao** [comment]
@torkelo is that query helpful at all? 
Can you point to how to configure the service for this part?:
> enable debug logging and set app in dev mode to get full tsdb logs during alert execution

**Comment by torkelo** [comment]
the query does not use a time filter
