### ISSUE TITLE
Lock panels when accessing Grafana dashboard from mobile device

### ISSUE THREAD

**Issue by Ekimik** [grafana/grafana#20120]
**What would you like to be added**:
Some lock button, which will temporarily disable panels drag and drop features.

**Why is this needed**:
In our team we have dasboard for monitoring our app. But when using mobile device to look at mentioned dashboard, it's easy to drag some panel by mistake instead of scrolling down in dashboard.

**Comment by torkelo** [comment]
think we can solve this when fixing this issue: https://github.com/grafana/grafana/issues/17768
