### ISSUE TITLE
Explore: Slow table processing

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#20135]
When doing queries in Explore that are not properly bounded the react-table takes lot of time just processing the data, even though it shows only 25 rows per page. This is flame graph for Elastic query with 3k results:

<img width="999" alt="Screenshot 2019-10-31 at 22 51 05" src="https://user-images.githubusercontent.com/1014802/67988789-49025f00-fc31-11e9-94e9-2b3899910067.png">

Where react-table spent 6s just processing the data before rendering anything (while also blocking any user input).

**Comment by aocenas** [comment]
Seems though that the issue may be that the query that it is running here is somehow weird. The issue exists only when going to logs tab in explore and then reloading. Because the metric/logs tab is not in the url you go to metrics tab but with logs url and this seems to be the only time this happens. There is issue for that https://github.com/grafana/grafana/issues/19357 so maybe afterwards this will be non issue.

**Comment by ivanahuckova** [comment]
> Seems though that the issue may be that the query that it is running here is somehow weird. The issue exists only when going to logs tab in explore and then reloading. Because the metric/logs tab is not in the url you go to metrics tab but with logs url and this seems to be the only time this happens. 

✅ This issue has been fixed (#19357 has been closed as well)

I have also tried various queries/switches between logs and metrics, but couldn't replicate the issue. Table processing was blazing fast. Therefore I am closing the issue
