### ISSUE TITLE
Dashboard: Option to disable/hide timepicker

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#2013]
Sorry if I'm too blind to spot it, but is disabling the timepicker in any given dashboard support gone ?

**Comment by torkelo** [comment]
yepp

**Comment by Akeru** [comment]
Any plan to get it back ? :smile:

**Comment by torkelo** [comment]
not really. Unless many complain, you are the first who have noticed. Can you describe the use case?

**Comment by Akeru** [comment]
Sure. 

We have a dashboard containing only single stats panel of our most important values. Since they are "instant" value, the timepicker (and zoom) has no real use. 

We also have a "note" dashboard with only text data (and sometimes links), no actual graphs. Again the timepicker has no use.

On a side note, you can also set the auto-refresh values to "" and still get the menu displaying "Every (nothing)"

**Comment by torkelo** [comment]
but why have auto refresh enabled in that case?

**Comment by Akeru** [comment]
Not sure I understand. Auto refresh on the instant value is need since we are using these values as monitoring. On the "notes" dashboard, nothing time related is needed.

**Comment by bacheson** [comment]
I'm in the same boat. The timepicker is confusing in certain dashboards where it's irrelevant.

**Comment by blysik** [comment]
Same here.  I made a dashboard which unfortunately required hard coded values pinned to a week of data points.  I would like to be able to remove the time picker, since all the graphs override its setting to last 7 days anyways.

**Comment by tuannvm** [comment]
+1

**Comment by varturas** [comment]
+1, I need to remove time picker. We have a landing page that serves as a fixed dashboard and we need to disable ability to change/modify time picker on this landing page.

**Comment by golddiga** [comment]
+1 We are showing non time related data (missing resources within an html request) and they are not time based. Would be nice to be able to remove the filter on those dashboards.

**Comment by hrochniak** [comment]
+1

**Comment by cjander** [comment]
+1

**Comment by thibodux** [comment]
+1

**Comment by torkelo** [comment]
implemented in master!
