### ISSUE TITLE
Azure Monitor data source test result message is difficult to understand

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#20133]
**Steps to reproduce**:

1. Add an **Azure Monitor** data source.
2. Set an Application Insight API key and Application ID.
3. Click **Save and test**.

**Actual Result**:

We see this error message:

![screenshot 2019-10-25 1359](https://user-images.githubusercontent.com/3270755/67987092-f3af5900-fc02-11e9-9775-d91a46551ec8.png)

Reformatted as text:

    1. Successfully queried the Application Insights service.
    2. Azure Log Analytics: Bad Gateway: […]

**Expected Result**

A success message for Application Insights, followed by an error message for Azure Log Analytics.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by aocenas** [comment]
@briangann Do you know who is working on Azure Monitor or whether there is an appropriate abcklog for this?

**Comment by sarahzinger** [comment]
Trying to go through and clean up old issues. I believe that our auth configuration page has been updated since this issue was created so going to close this for now.
