### ISSUE TITLE
disable default annotation

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#20146]
**What would you like to be added**:
Disable default annotation by default, through not marking enabled checkbox or remove it completely.
**Why is this needed**:
High frequency refresh sometimes makes dashboard reporting api/annotation data error, coz of default annotation set and enabled there. Besides this behavior does not make any sense if no customized annotation created.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
