### ISSUE TITLE
Prometheus Data Source Behind Reverse Proxy - Direct Graph Link

### ISSUE THREAD

**Issue by hdinthkld** [grafana/grafana#20149]
**What would you like to be added**:
(a) An option to hide the "Link to Graph in Prometheus" button when editing a graph
(b) Option to specify alternative URL to be used for the link

**Why is this needed**:
When editing a graph for a Prometheus datasource the "Link to Graph in Prometheus" button directly references the URL defined in the datasource and there is no current way to provide alternative URL/path and/or port number.

For instance, if Grafana and Prometheus are on the same host you may use http://localhost:9090 as the datasource URL but when accessed publically Grafana may be on https://grafana.example.com and prometheus on https://prometheus.example.com. 

It would be easy enough to just change it so that Grafana uses the same public FQDN (possibly with a simple host file edit to override any DNS result) but this does not resolve the issue of having to have the public access also on TCP 9090 rather than a more user friendly HTTPS (TCP 443) port.

As Prometheus does not provide any built-in authentication/encryption capabilities is it necessary to provide these service via an external reverse proxy and/or load balancer when on a public network.

This issue appears only to be related to the Prometheus datasource as others (such as InfluxDB) do not provide this option, making the option available to "hide" the button would avoid user confusion.

**Workaround:**
As a workaround I'm currently looking at implementing an internal reverse proxy so that depending on where the request comes in from (either the "grafana" host or "unknown" IP) they will redirected to the appropriate public URL (which provide encryption/authentication) but does seem a bit of a hack/over complicated solution.

**Comment by lleszczu** [comment]
I believe this is valid for other datasources as well.

**Comment by itsmylife** [comment]
@grafana/observability-metrics does not currently have the bandwidth to prioritize development on this issue. If members of the community want to take this issue we will help review any submitted PRs. Please upvote or comment to help us re-prioritize this issue in the future!
