### ISSUE TITLE
Field select not including tags in query

### ISSUE THREAD

**Issue by kjetilmjos** [grafana/grafana#20142]
**What happened**: Field picking list does not use include tags when querying influxdb.

**What you expected to happen**: If you first pick tags, they should be included in the query to influx and only fields matching the set of tags should be returned.

**How to reproduce it (as minimally and precisely as possible)**: Make 2 measurements in the same database with different fields and tags. Open query inspector and use Grafanas field picker. Look at the query. After picking tags -> measurement, click 'select field' the tag keys dissapears from the query.

**Anything else we need to know?**: Screen recording showing the error can be found here: https://files.gapit.io/s/TnK6GimM8CWbgnQ

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: InfluxDB 1.7.8
- OS Grafana is installed on: Ubuntu server + Docker
- User OS & Browser: Ubuntu 19.10 + Chrome 78.0.3904.70
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
hi @kjetilmjos , unfortunately there is no such API available in influxdb. we use the `SHOW FIELD KEYS` query to ask for fields, and there is no way to specify tags in that query.
i found a closed github-issue about adding such a possibility to influxdb here https://github.com/influxdata/influxdb/issues/8363

**Comment by kjetilmjos** [comment]
Ahh I understand. Thanks for replying. I guess using a query like this SHOW TAG VALUES WITH KEY = "Building" WHERE "Location" = 'norway'
Would not work

**Comment by gabor** [comment]
hmm.. sorry, i'm not sure i understand the idea with the `SHOW TAG KEYS`. maybe we have a misunderstanding, so i will describe how things are right now, and then we can go on from there:
consider this screenshot:
<img width="446" alt="editor" src="https://user-images.githubusercontent.com/51989/119465937-713a3d00-bd44-11eb-81cc-b70428bb8daf.png">

- when you click on [1], we ask influxdb to give all measurements where the WHERE section applies.
- when you click on [2], we ask influxdb to give all tag keys where the [1] and the WHERE section applies.
- when you click on [3], we ask influxdb to give all tag values where the [1] and the WHERE section applies.
- when you click on [4], we ask influxdb to give all fields where [1] applies


my understanding was that you'd like to modify the situation when clicking on [4], to also have the WHERE section apply. unfortunately that's not possible with the current influxdb API.

did i misunderstand it somehow maybe?

**Comment by kjetilmjos** [comment]
Your summary is correct. The ideal thing would be as you write, that when clicking [4] it would have all the WHERE statements applied. As it is now, after selecting a lot of WHERE statements when pressing 4 it will still show all entries even if the WHERE statement is not tagged on that specific field.

But I understand this an InfluxDB problem and not Grafana. Maybe InfluxDB 2.x has some way of handling this.
