### ISSUE TITLE
Administration: Server admin should be able to switch to any organization (or add himself to org)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2014]

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/7700138/ce4933fe-fe1c-11e4-8b21-df2c94f2abeb.png)

**Comment by robertjakub** [comment]
maybe admin could be able to change "current" organisation for the user ("missing org" when removes user from the current/selected organisation)
