### ISSUE TITLE
Telegram notifier incorrectly handles missing image

### ISSUE THREAD

**Issue by agmance** [grafana/grafana#20156]
**What happened**: The alerts stop working after update Grafana to v6.5.0-pre (372c290).
They work if I deactivate "Include image" option  on all my notifications channels
If one of them has still active that option, I don't receive any notification from any channel.

**What you expected to happen**: That the alerts would still working after update.

**How to reproduce it (as minimally and precisely as possible)**: 
Activate "Include image" in one of your notification channels, force an alert, check the logs for "eror" messages.

**Anything else we need to know?**:
If I try to send a "test message" from Notification channels, it works (I even receive the dummy image)
If I deactivate  the option "Include image", in all my channels, works as expected.

**Environment**:
- Grafana version:v6.5.0-pre (372c290)
- Data source type & version: 
- OS Grafana is installed on: Ubuntu Server 18.04, Docker version 19.03.1
- User OS & Browser: os x / arch & chromium 
- Grafana plugins: piechart
- Others: Two Notifications Channels configured: Telegram and Slack.

Logs: 
`lvl=info msg="Rendering timed out" logger=rendering`

`lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"`
`lvl=eror msg="Could not close Telegram inline image." logger=alerting.notifier.telegram err="invalid argument"`
`lvl=eror msg="Could not generate Telegram message with inline image." logger=alerting.notifier.telegram err="open : no such file or directory"`

`lvl=info msg="Sending telegram notification" logger=alerting.notifier.telegram chat_id=<some-id> bot_token=<private> apiAction=sendMessage`

`lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="context deadline exceeded" webhook=Telegram_notifications`
`lvl=eror msg="failed to send notification" logger=alerting.notifier uid=7Aicn6OWz error="context deadline exceeded"`
`lvl=eror msg="failed to send notification" logger=alerting.notifier uid=7Aicn6OWz error="context deadline exceeded"`

`lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=14 notification=Slack-Grafana_alerts`

`lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook=Slack-Grafana_alerts`
`lvl=eror msg="failed to send notification" logger=alerting.notifier uid=gRL2qbdWk error="context deadline exceeded"`
`lvl=eror msg="failed to send notification" logger=alerting.notifier uid=gRL2qbdWk error="context deadline exceeded"`

`lvl=warn msg="Error adding avatar to cache: Item 46d229b033af06a191ff2267bca9ae56 already exists"`

`lvl=info msg="New state change" logger=alerting.resultHandler ruleId=64 newState=pending prev state=unknown`
`lvl=warn msg="Error adding avatar to cache: Item 46d229b033af06a191ff2267bca9ae56 already exists"`
`lvl=info msg="New state change" logger=alerting.resultHandler ruleId=64 newState=alerting prev state=pending`
`lvl=info msg=Rendering logger=rendering path="d-solo/WpuwK8vZz/server-status?orgId=1&panelId=189"`

**Comment by marefr** [comment]
@agmance You seem to have a problem with PhantomJS. Please try latest nightly. Seems to be an issue in telegram notifier as well when there are no image available.

**Comment by kotchuprik** [comment]
I have the same problem with telegram + discord after upgrading from 6.2 to 6.4.4.

**Comment by mator** [comment]
getting the same message on 6.5.1 :

```
# yum info grafana
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Installed Packages
Name        : grafana
Arch        : x86_64
Version     : 6.5.1
Release     : 1
Size        : 168 M
Repo        : installed
From repo   : grafana
Summary     : Grafana
URL         : https://grafana.com
License     : "Apache 2.0"
Description : Grafana

# journalctl -u grafana-server -f
Dec 04 20:37:12 srv1 grafana-server[4979]: t=2019-12-04T20:37:12+0000 lvl=info msg=Rendering logger=rendering path="d-solo/h1zH4V-Wk/mt-wsback?orgId=1&panelId=3"
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=info msg="Rendering timed out" logger=rendering
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=eror msg="Could not generate Telegram message with inline image." logger=alerting.notifier.telegram err="open : no such file or directory"
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=info msg="Sending telegram notification" logger=alerting.notifier.telegram chat_id=zzz bot_token=xxx apiAction=sendMessage
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="context deadline exceeded" webhook=telegram-send
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=b0BAT4-Zz error="context deadline exceeded"
Dec 04 20:37:42 srv1 grafana-server[4979]: t=2019-12-04T20:37:42+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=b0BAT4-Zz error="context deadline exceeded"
```

**Comment by marefr** [comment]
@mator you have an issue with image rendering, please disable include image or try the new [image rendering plugin](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin).
