### ISSUE TITLE
grafana/toolkit: Add LESS support

### ISSUE THREAD

**Issue by lunaticusgreen** [grafana/grafana#20150]
**What would you like to be added**:
Possibility of using not only **css** and **sass** but also **less**, it seems like we only need to add less-loader to webpack config

**Why is this needed**:
It can be used for the theme customization, for example, when you are using antd, themes can only be applied with **less** https://ant.design/docs/react/customize-theme

**Comment by marefr** [comment]
@dprokop can you have a look at this one?

**Comment by dprokop** [comment]
@lunaticusgreen thanks for this feature request. 

Yes, this is fairly simple to do. We haven't thought about supporting LESS, but we will take that into consideration when working on toolkit improvements soon. Let me keep you updated on this one.

**Comment by lunaticusgreen** [comment]
@dprokop Thanks for you answer, if i can speed it up - just tell, and I'll create PR with this changes quick

**Comment by algenty** [comment]
Hi Dominik (@dprokop)
I don't know if it is the same problem. I notice that css isn't copied into dist directory after build. 
then classes are not applied on DOM

BR

**Comment by dprokop** [comment]
@lunaticusgreen sure, feel free to open a PR for that!

**Comment by lunaticusgreen** [comment]
@dprokop Hi, I probably missed notification from github, created PR
