### ISSUE TITLE
Cloudwatch: Convert go convey tests to standard test library

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#20157]
At the moment, all CloudWatch datasource backend tests are implemented using Go Convey. They should be rewritten using the go standard testing library. See https://github.com/grafana/grafana/blob/master/contribute/style-guides/backend.md#testing for more information.

**Comment by papagian** [comment]
For an example of such a conversion check 2996041791bf52de67a985ee62d4dcf8166f340b
