### ISSUE TITLE
Reorganise grafana/* packages to enable namespace/path imports

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#20151]
Currently grafana/* packages are huge buckets for everything we put and export from them. User need to import directly from the package and go through endless list of possible imports to pick the right one.

What we want to introduce is namespacing/path imports. Instead of doing:

`import { Input } from '@grafana/ui'` user would do `import { Input } from '@grafana/ui/forms'`

Some input about possible approaches: https://github.com/microsoft/TypeScript/issues/8305

**Comment by torkelo** [comment]
After testing this we discovered it did not have the pay-off we where hoping for, so deciding on a single export namespace
