### ISSUE TITLE
Add "the" to license reference in README.md

### ISSUE THREAD

**Issue by VilhelmPrytz** [grafana/grafana#20162]
**What would you like to be added**:
In the README under the section "License", it says

```
Grafana is distributed under Apache 2.0 License.
```

I might be wrong, but I believe there is a `the` missing between `under` and `Apache`. The full sentence would be:

```
Grafana is distributed under the Apache 2.0 License.
```

**Why is this needed**:

I just thought it sounded better. If it's something you agree with I'd be more than happy to create a pull request :smile:.

Cheers

**Comment by marcusolsson** [comment]
I think you're right :) We'd be happy to accept a pull request for this.

**Comment by VilhelmPrytz** [comment]
Thanks! I have now created a pull request for this https://github.com/grafana/grafana/pull/20167 :smile:
