### ISSUE TITLE
Log Panel: Add Show context feature

### ISSUE THREAD

**Issue by benmarsden** [grafana/grafana#20166]
**What would you like to be added**:
The "Show context" button within logs of a Log Panel (see screenshot) should behave as it does within Explore (akin to grep -C 10, implemented from  issue #15140, PR #17097).

<img width="962" alt="grafana-show-context-log-panel" src="https://user-images.githubusercontent.com/9026668/68149901-5a0be280-ff47-11e9-8da9-29b194e71675.png">

Currently, this button seems to be unresponsive.

**Why is this needed**:

It would provide a better debugging flow for (as an example) investigating errors/failures within a log if the user is able to gain quick insights directly within the panel, rather than go move away from the Dashboard to Explore.

**Comment by roidelapluie** [comment]
![ctx](https://user-images.githubusercontent.com/291750/69067198-f8f20d80-0a22-11ea-8510-0834ef1ac0a0.png)
 I confirm that the context is not shown

**Comment by rgarrigue** [comment]
Same here

![image](https://user-images.githubusercontent.com/1872031/82014934-ec6f0a80-967d-11ea-83cf-9016713bdb15.png)

Grafana 6.7.3 (commit: a04ef6cefc, branch: HEAD)
Firefox 76.0.1 or Chromium 81.0.4044.138 snap (over Ubuntu 19.10)

**Comment by chipsmaster** [comment]
Hello
Same here, i also tried with recent version (loki 1.6.1, grafana 7.2)

There is also a 400 bad request error if the search looks like a number `{job="xx"} |= "123"` ; the message is like "parse error at line 1, col 17: syntax error: unexpected NUMBER"

**Comment by ivanahuckova** [comment]
@chipsmaster I think that your issue is happening in Explore and not in Dashboard's Logs panel, as LogsPanel doesn't provide option to show context. Therefore if you have a problem with context in Explore, could you please open a new issue.

**Comment by ivanahuckova** [comment]
I have changed the label to `type/feature-request`, as we don't have show context functionality in logs panel and couple months ago we have removed the `show context` button, as it wasn't doing anything and it was probably confusing for users. Let's have a discussion if we would like to generally provide interactivity in LogsPanel (show context, logs details, toggle parsed fields) or keep it only in Explore. +cc @zoltanbedi

**Comment by mihalby** [comment]
> 
> 
> I have changed the label to `type/feature-request`, as we don't have show context functionality in logs panel and couple months ago we have removed the `show context` button, as it wasn't doing anything and it was probably confusing for users. Let's have a discussion if we would like to generally provide interactivity in LogsPanel (show context, logs details, toggle parsed fields) or keep it only in Explore. +cc @zoltanbedi

Please, add this feature to Log panel. Many people would like this. Thx.

**Comment by yangvipguang** [comment]
> I have changed the label to `type/feature-request`, as we don't have show context functionality in logs panel and couple months ago we have removed the `show context` button, as it wasn't doing anything and it was probably confusing for users. Let's have a discussion if we would like to generally provide interactivity in LogsPanel (show context, logs details, toggle parsed fields) or keep it only in Explore. +cc @zoltanbedi

It‘s very useful adding context in log pannel。For example, most of the time we see logs   in the log panel, if there is no context, you have to go to  explore  to see log  every time。
Please add it Thx。

**Comment by yangvipguang** [comment]
@ivanahuckova   If a user with viewer role ,then may be  he do't have the access to explore . Then How can he query the log context.

**Comment by ivanahuckova** [comment]
@yangvipguang something that you could do right now is to use the [viewers_can_edit](https://grafana.com/docs/grafana/latest/permissions/organization_roles/#viewer-role) setting. If you set this setting to **true**, then users with the Viewer role can also access Explore. This is also used for example in our [grafana play](https://play.grafana.org/) .

**Comment by yangvipguang** [comment]
@ivanahuckova  I know, But  I think the best practice is adding context in log pannel.

**Comment by singhr6** [comment]
I would like to see context in log panel, it just too much work if we need to keep checking in explore..for context.

**Comment by sandstrom** [comment]
It would be neat if clicking on any label or "calculated label" for Loki logs would quickly bring up all the logs with that filter value that are before and after the current line (e.g. +/- 10 lines, and a "more" button with which one could expand further).

Similar to the [context viewer](https://grafana.com/blog/2019/08/14/new-in-grafana-v6.3-introducing-lokis-log-row-context-viewer/), but more intelligent. 

This would make it easy to e.g. "expand" a request id and see all log lines for that request id. Makes sense if you are using e.g. [Canonical Log Lines](https://brandur.org/canonical-log-lines).

**Comment by johncadengo** [comment]
Just curious if anyone has found a way to view the context in the log panel? Is the current solution to use explore to see the context of the log?

**Comment by baerrach** [comment]
You can click on the title of the Dashboard to select "Explore" from the drop down menu,
but what's really needed is to do that direct from any line within the dashboard as that's the place that already has all the context

**Comment by johnstile** [comment]
I would love to see "show context" in the log panel.

**Comment by svennergr** [comment]
Hi all,
with the merge of https://github.com/grafana/grafana/pull/80403 the "log context" feature is available for dashboard panels now as well.

We are happy to hear your feedback in this issue, though I'll close it for now.
