### ISSUE TITLE
Clean up star and dashboard tags when deleting user or dashboard

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#2016]
After a lot off adding/removing datasources, organizations, users, tags, stars and such I ended up with a lot of dead references (user_id, org_id, dashboard_id...). 

Could you add some foreign keys to these references ? It might make such operations fail more often but that would make clear when linked data still exists.

**Comment by torkelo** [comment]
what did you do? did you use the http api?

**Comment by Akeru** [comment]
Nope, just from the UI

**Comment by torkelo** [comment]
yea, I can see dead stars, and dead tags and entries in org_user . Might need to think about this :) Foreign keys can be a hassle when migrating schema and doing other DB refactorings and they have some differences in behavior between the database types that Grafana support so I opted not to use them. Might need to to use them or have something else that handles cascading deletings / cleanup

**Comment by Akeru** [comment]
:+1:
