### ISSUE TITLE
After updating from 5.x.x to 6.4.3 overall performance downgraded...

### ISSUE THREAD

**Issue by anisimovyuriy** [grafana/grafana#20168]
**What would you like to be added**:
Performance improvement as it was in recent version of 5.x.x
After updating from 5.x.x to 6.4.3 overall performance downgraded...

**Why is this needed**:
To improve user experience

**Comment by torkelo** [comment]
You have to be more specific than that. Include your data source type, queries, how much data they return, show a dashboard. What panels are used and what are their options. In what way is the performance worse? Does it take longer for panels to render or does Grafana feel slower & more browser cpu usage? 

We have no other reports over the last 8 months that performance when down in 6.x so we need some more info.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
