### ISSUE TITLE
Docker: Build and publish an additional Ubuntu based docker image

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20178]
**What would you like to be added:**
Build and publish an additional Ubuntu based docker image to docker hub. 

**Why is this needed:**
- Some reported DNS issues using Grafana alpine-based docker image
- Some identified issues with Grafana backend plugins
- Users that extended the earlier Grafana Ubuntu image got problems with tooling

**Additional information:**
- [x] Add an additional Dockerfile based on Ubuntu (18.10 if possible) for building and pushing to Docker Hub. See old Ubuntu dockerfile [here](https://github.com/grafana/grafana/blob/v6.3.x/packaging/docker/Dockerfile).
- [x] Add an additional Dockerfile for building Grafana/docker image from source based on Ubuntu (18.10 if possible). See old Ubuntu dockerfile [here](https://github.com/grafana/grafana/blob/v6.3.x/Dockerfile).
- [x] Docker: Add back curl to docker image #19549

**Comment by DanCech** [comment]
Sounds good
