### ISSUE TITLE
grafana/toolkit: Add examples for e2e-testing of plugins

### ISSUE THREAD

**Issue by sebimarkgraf** [grafana/grafana#20177]
**What would you like to be added**:
* Example Implementation of e2e test for panel or datasource plugin
* Add documentation on location of e2e testing of plugins

**Why is this needed**:
* While grafana/toolkit seems to provide the possibility of e2e-testing it is unclear in how to use it
* The example plugins do not utilize the e2e-testing approach
* E2E is important to make sure that the integration in Grafana works

**Comment by oddlittlebird** [comment]
@marcusolsson , would this be appropriate to add to the `contribute` docs?

**Comment by oddlittlebird** [comment]
@sebimarkgraf , would the examples in the [E2E style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/e2e.md) meet your needs?

**Comment by marcusolsson** [comment]
I believe this is relevant for all plugin developers, and not just people working on the Grafana project so the `contribute` docs doesn't feel right to me.

Maybe a guide in the plugin docs, or add an example in https://github.com/grafana/grafana-plugin-examples?

**Comment by GrafanaWriter** [comment]
@marcusolsson - Will we be able to develop this content? The issue is quite stale, so I'd like to confirm our plan.

**Comment by GrafanaWriter** [comment]
Given the age of this issue, and the lack of activity, I will close. Please reopen if the issue is still valid.
