### ISSUE TITLE
allow_sign_up not working?

### ISSUE THREAD

**Issue by airtoxin** [grafana/grafana#2017]
I edit config file on `/etc/grafana/grafana.ini`

```
[users]
# disable user signup / registration
;allow_sign_up = false
```

and restart grafana-server `service grafana-server restart`.
but still sign up form available on `mygrafana:3000/login`.
and admin settings `mygrafana:3000/admin/settings` also shows allow_sign_up=true

grafana 2.0.2
CentOS 6.5 x86_64

**Comment by torkelo** [comment]
You need to uncomment the config option. You do this by removing the semicolon at the start of the line (;)
