### ISSUE TITLE
Show template variables in kiosk mode 

### ISSUE THREAD

**Issue by fredbcode** [grafana/grafana#20176]
Hello all,

I have a dashboard with many devices (node) all works well, but I need to share this dashboard with some users and usually I just send a link in kiosk mode

Unfortunately in kiosk mode the select device menu is hidden, all they can see is only one device 

In this case a parameter to just hide the left panel could be very useful or (better ?) an option to show the device menu in kiosk mode      

Thank you

**Comment by maxdosme** [comment]
You can change the div style"display: none => block,"

**Comment by franshamk** [comment]
+1

**Comment by Valdanitooooo** [comment]
I looked at the source code and tried to change the value of `kiosk` to `full`  to solve this problem
```
http://xxxxx?orgId=1&kiosk=full
```

**Comment by bob454522** [comment]
> I looked at the source code and tried to change the value of `kiosk` to `full` to solve this problem
> 
> ```
> http://xxxxx?orgId=1&kiosk=full
> ```

unfortatenly this no longer works after v8.5,  please see:
https://github.com/grafana/grafana/issues/15546#issuecomment-1113972969

(what we ideally need is a setting / url argument for : Kiosk mode + variable dropdown menus)
LOVE GRAFANA

**Comment by iamyeka** [comment]
+1

**Comment by genervta** [comment]
pls. waiting since years(?), still waiting, and again with a new dashboard requirment - WE NEED kiosk=full BACK!

or in other words: we need an option to "Show template variables in kiosk mode"

**Comment by NWYLZW** [comment]
In grafana 8.4.10, you can use the configuration item, the `kiosk !== null` feature to hide the left navigation bar. **The effect reflected in the url is that any value assigned to the kiosk can hide the left navigation bar.**
So you can assign a value other than `'tv' | '1' | 'true'` to the kiosk, so as to only hide the left navigation bar without affecting
https://github.com/grafana/grafana/blob/v8.4.10/public/app/core/components/NavBar/NavBar.tsx#L63-L65

In grafana 9.5.2, this part of the logic has been adjusted, and the shielding of the left navigation bar has been converted to, and it will be hidden only if it is judged to be a specified value or a special case
https://github.com/grafana/grafana/blob/v9.5.2/public/app/core/components/NavBar/NavBar.tsx#L179-L192

If the official agrees to add a configuration, I would be happy to provide some work to support this simple requirement.

Link: grafana/grafana#15546

----

在 grafana 8.4.10 中可以利用配置项，`kiosk !== null` 的特性去隐藏左侧导航条，**体现在 url 上的效果就是，给 kiosk 赋值了任意值，均可隐藏掉左侧导航条。**
所以可以为 kiosk 赋值非 `'tv | '1' | 'true'` 的值，从而实现仅隐藏左侧导航条，而不去影响
https://github.com/grafana/grafana/blob/v8.4.10/public/app/core/components/NavBar/NavBar.tsx#L63-L65

而在 grafana 9.5.2 中该部分逻辑有所调整，有关左侧导航条的屏蔽转化为了，判断为指定值或者特殊情况，才会将其隐藏
https://github.com/grafana/grafana/blob/v9.5.2/public/app/core/components/NavBar/NavBar.tsx#L179-L192

如果官方同意增加一个配置，我很乐意为这个简单的需求，提供一些工作用于支持它。

相关：grafana/grafana#15546

**Comment by NWYLZW** [comment]
> @NWYLZW Hello,Do you have some temporary solution to display variables while kiosk is in use,thanks.

You can make it work by modifying some judgment logic in later versions. I will submit a Pull Request later, maybe you can refer to it?

**Comment by NWYLZW** [comment]
https://github.com/NWYLZW/grafana/commits/feature/control-nav

You can take a look at my branch
@JiiAndddy

**Comment by dc-orz** [comment]
I add a configuration kiosk=full-var. see: https://github.com/dc-orz/grafana/commit/bb51f1103a7dc705e3f6cf6307f34b7240a4437a

**Comment by NWYLZW** [comment]
> I add a configuration kiosk=full-var. see: [dc-orz@bb51f11](https://github.com/dc-orz/grafana/commit/bb51f1103a7dc705e3f6cf6307f34b7240a4437a)

It seems that what you and I are dealing with are no different, and you do not follow grafana's code style, and the changes are a bit too big.

**Comment by dingdingzhouaaaa** [comment]
> https://github.com/NWYLZW/grafana/commits/feature/control-nav
> 
> You can take a look at my branch @JiiAndddy
how to change this file in v9.5.2 version
https://github.com/grafana/grafana/blob/v9.5.2/public/app/core/components/NavBar/NavBar.tsx#L179-L192

**Comment by dingdingzhouaaaa** [comment]
> I add a configuration kiosk=full-var. see: [dc-orz@bb51f11](https://github.com/dc-orz/grafana/commit/bb51f1103a7dc705e3f6cf6307f34b7240a4437a)
> 
> ![image](https://user-images.githubusercontent.com/30795765/283437816-c3d1ce2b-c698-48ed-8948-6232d9c6cd58.png)

what's the version you are using 
It's not work well with 9.3.1

**Comment by mdvictor** [comment]
This will be resolved with the new upcoming architecture changes, so I will close this issue. Feel free to reopen if there is any other problem.

Thank you for opening this issue!

**Comment by wingyiu** [comment]
full-var not work in grafana v10
