### ISSUE TITLE
More than 27 series are badly supported for tables

### ISSUE THREAD

**Issue by nagisa** [grafana/grafana#20184]
**What happened**:

![Grafana table](https://user-images.githubusercontent.com/679122/68240192-568a6100-0004-11ea-8944-f2ec44729692.png)

**What you expected to happen**:

More rows would get added after the Z. Instead table collapses all the subsequent series into the `Value #undefined` row as those rows do not get a label assigned.

**How to reproduce it (as minimally and precisely as possible)**:

Try to display more than 27 series in a table with the `Table` table transform.

**Anything else we need to know?**:

Perhaps a good solution would be to allow custom names/labels for series?

**Environment**:
- Grafana version: v6.0.0, but happens on versions as recent as v6.4.3 as well.
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
The table panel supports an infinite number of columns (but has problem with column overflow when they do not fit): https://github.com/grafana/grafana/issues/4157

But sounds like your conflating queries with series, a single query can return 100 series. And
Grafana has a limit of 26 queries per panel: 

Feature request to support more than 26 queries for a single panel: https://github.com/grafana/grafana/issues/4978

**Comment by wallacebrf** [comment]
i am trying to use flowcharting and if i can do what i was planning i would need well over 100 queries. i am trying to make a network status diagram with over a dozen switches, showing the status of the ports (up/down), port VLAN ids, switch temps, switch fan speeds etc. per switch this will equate to around 30 queries each.

for the flowcharting in particular we need a much higher query limit
