### ISSUE TITLE
Feature request - Add retention policy select to InfluxDB query editor 

### ISSUE THREAD

**Issue by zidekmat** [grafana/grafana#2018]
Please add feature to select retention policy in InfluxDB 0.9. Something like there is now for selecting metrics and tags.

**Comment by robinroestenburg** [comment]
+1, right now it is a bit of a pain to query from measurements in a different retention policy

**Comment by markuspatrick** [comment]
+1 would be create to have it in editor not only in raw query mode....

**Comment by RupprechJo** [comment]
+1 One of the most important features of grafana is the easy editor, even non IT persons can use it after a short introduction. But the missing retention policy selection destroys that completely, because you have to fall back to the raw query string

**Comment by markuspatrick** [comment]
+1

**Comment by RobWin** [comment]
+1

**Comment by lydon42** [comment]
+1

I think this could be best implemented as a new line in the query editor (perhaps between FROM and SELECT) or a function like addition to select (but this is not that intuitive, because the retention needs to go in front of the metric). So I would prefer the extra line.

You currently can't just add the retention to the FROM argument, because influx expects something like "RETENTION".METRIC and grafana will quote the whole string. So you either get ""RET".metric" (double quoted) or "RET.metric" (wrong quotes for influx to understand).

**Comment by syepes** [comment]
+1

**Comment by torkelo** [comment]
Could this be a good start? 

![influxdb_policy_selector](https://cloud.githubusercontent.com/assets/10999/12398135/f5aca614-be11-11e5-933b-7878fac766cb.gif)

I would love to have more smarts in grafana to automatically pick the correct policy based on time range and a standard layout of metrics and naming of rollup policies. For this to work you can only have one field per measurement and generic rollup rules for each period and rollup function. 

```sql
CREATE CONTINUOUS QUERY "1m_avg"
                ON site
                BEGIN
                SELECT mean(value) as value
                INTO "1m_avg".:measurement
                FROM /\.avg/
                GROUP BY time(1m), *
```

```sql
CREATE CONTINUOUS QUERY "1m_sum"
                ON site
                BEGIN
                SELECT sum(value) as value
                INTO "1m_avg".:measurement
                FROM /\.count$/
                GROUP BY time(1m), *
```

**Comment by mvadu** [comment]
@torkelo Please do not add the "Smart" part that you mentioned. That puts lot of assumptions on naming patterns. Rather stop at your current model of providing an option to chose the retention policy to the user.

**Comment by steverweber** [comment]
I think the "smarts" should be added to the upstream project.
