### ISSUE TITLE
adding organisation to user, suggestion doesn't work

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#20197]
**What happened**: While trying to add an organisation to a user (in admin menu) the organisation suggestion doesn't show the org I'm looking for.

**What you expected to happen**: Find my org in the list

**How to reproduce it (as minimally and precisely as possible)**: you need to have more than 1000 org. Go to the page of a user and try to add an org which is not in the first 1000 org (alphabetical order)

**Anything else we need to know?**: when you open the dev console you can see that the call get to mathcing org are done with an empty "query" params.

Example : 
I'm looking to add the org "ZE_ORG" to a user.
![grafana-org-bug-1](https://user-images.githubusercontent.com/27487887/68289500-80846780-0086-11ea-8653-96785c18fad1.JPG)

But the call made by grafana is just 
![image](https://user-images.githubusercontent.com/27487887/68289533-93973780-0086-11ea-96cc-86fc3509fd91.png)

**Environment**:
- Grafana version: 6.4.3
- OS Grafana is installed on: centos7
- User OS & Browser: chrome

**Comment by torkelo** [comment]
Unable to replicate, works fine here. Any errors in the browser console? Can you open chrome dev tools network tab. Do you see any requests when you type in the input field?

**Comment by deathwarrior60** [comment]
Hello,

There is no error in the browser console. 
In the network table there is a call being made on I start typing on the input field but the "query" params is left empty.
example : 
`http://localhost:8090/api/orgs?query=`

Note :
I tested on the 6.4.4 the bug was also present.
I have the bug with firefox and chrome.

The bug only appears if you was a lot of org (3500 in my case) and you are looking for an org that isn't in the first 1000 returned by default by grafana.

**Comment by deathwarrior60** [comment]
I've never done go and angularjs but from what I saw in the source, the correction could be either :
 - in https://github.com/grafana/grafana/blob/master/public/app/features/admin/AdminEditUserCtrl.ts#L137 remove the orgsSearchCache and do I right call to the backend with "query" params filled.

or
- in https://github.com/grafana/grafana/blob/master/pkg/api/org.go#L162 remove the limit of 1000

Hope it help.

**Comment by marefr** [comment]
It's clearly supported to filter in the [api/backend](https://github.com/grafana/grafana/blob/master/pkg/api/org.go#L164) so don't understand why this cache solution is being used. Definitely a bug.

**Comment by dprokop** [comment]
This seems not to be an issue anymore with Grafana 7.
