### ISSUE TITLE
Saved custom time ranges

### ISSUE THREAD

**Issue by adrianmih** [grafana/grafana#20193]
**What would you like to be added**:
I'd like to be able to configure and save custom time ranges in the time picker as  an addition to the quick ranges.

**Why is this needed**:

Enhancement of user experience for those who are using same intervals every other day which are not available in the time range picker.

**Comment by marcusolsson** [comment]
Setting custom time ranges is already possible. 

<img width="576" alt="Screen Shot 2019-11-06 at 10 42 02" src="https://user-images.githubusercontent.com/8396880/68286880-1ec1fe80-0082-11ea-99e5-16d6703c459c.png">

Do you mean adding custom quick ranges?

**Comment by adrianmih** [comment]
No, I meant to config my own range and then be able to save it to the list of ranges.

My vision is something like:

![image](https://user-images.githubusercontent.com/56756005/68291062-f4bc0c80-0080-11ea-8799-8637623ba2fe.png)

Ability to save the range you've set, maybe a couple of operations on it too (trunc current day etc)

![image](https://user-images.githubusercontent.com/56756005/68291175-377de480-0081-11ea-82ea-4dbe747a4f8f.png)

Once you've saved it with the desired labelling, you'd be able to select it from the list.

**Comment by torkelo** [comment]
duplicate there already is an issue for this https://github.com/grafana/grafana/issues/2417
