### ISSUE TITLE
Search Graphics on current Dashboard

### ISSUE THREAD

**Issue by stormnight** [grafana/grafana#2019]
Hello,

There are some way to search graphics in current dashboard by title or description?

You are assigning shortcut the "CTRL-F" shortcut for Dashboards Search, but with this, you block/cancel the default browser search shortcut.

It's useful when you have dashboards with > 30 graphics and want to search by title. The only option now, is to scroll-down around the page to find it.

Thanks,

**Comment by torkelo** [comment]
yea, can see that in some cases using CTRL+F for dashboard search is not ideal :(

**Comment by stormnight** [comment]
There are some way to disable the default CTRL-F shortcut ? even touching the code manually?
That would help us temporarily!

Thanks

**Comment by torkelo** [comment]
This is fixed in master.
"Ctrl + F" is change to just "F".
