### ISSUE TITLE
Grafana v6.5 Release Plan

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20206]
# Grafana v6.5
Release Coordinator: @marefr 

## 1. Branch of to a release branch

**Preconditions:**
- [x] Approved by release coordinator

**When:** Preliminary Thursday November 7th 2019
**What:** 
 - [x] Checkout new release branch, *`v6.5.x`*, from head of origin/master
 - [x] Update versions to the next version to be released
 - [x] Create community site release note topic
 - [x] Update [/scripts/build/publish.sh](https://github.com/grafana/grafana/blob/master/scripts/build/publish.sh) to contain the new “what's new” and “release note” links.
 - [x] Commit everything and push release branch
 - [x] Checkout master branch and branch of to a new branch
 - [x] Update version in package.json to point to the next pre-release, i.e. v6.6.0-pre and commit
 - [x] Open a PR

**Who:** @aknuds1 and @marefr 

### 1.1. Test and verification

**Preconditions:**
- [x] 1. Branch of to a release branch

**When:** Preliminary Thursday November 7th 2019
**What:** For now we don’t have a lot of automated processes for UI tests so it’s suggested to start with manual test and verification to improve the quality of the release. The test and verification is done on the release branch.
**Who:** Primarily maintainers

**Areas/features to test:**
- [x] Plugins
  - [x] Core panel plugins
    - [x] Graph
    - [x] Singlestat
    - [x] Gauge
    - [x] Table
    - [x] Bar Gauge
  - [x] Core datasource plugins
    - [x] Graphite
    - [x] Prometheus
    - [x] Loki
    - [x] InfluxDB
    - [x] Elasticsearch
    - [x] SQL
    - [x] AWS CloudWatch
    - [x] Azure Monitor
    - [x] Google Stackdriver
  - [x] Premium plugins
  - [x] (community plugins depending on changes made)
- [x] Dashboard
  - [x] Settings
  - [x] Playlist
  - [x] Snapshot
  - [x] Share
  - [x] Annotations
  - [x] Image rendering
- [x] Explore
- [x] Alerting
- [x] Configuration area (org)
- [x] Server Admin area
- [x] Authentication
  - [x] Grafana auth
  - [x] OAuth
  - [x] Auth proxy
  - [x] LDAP
- [x] Reverse proxy + using subpath (nginx/apache)
- [x] Provisioning
- [x] Grafana CLI, install plugins and reset admin password etc
- [x] Enterprise

### 1.2. Publish What's new in Grafana draft article

**When:** Preliminary Monday 11th November 2019
**What:** 
 - [x] Create Google doc and share with maintainers (Release coordinator)
 - [x] Write draft article (Maintainers)
 - [x] Open a PR (Release coordinator)

**Who:** Release coordinator and maintainers

## 2. Beta 1 Release

**Preconditions:**
- [x] 1.1. Test and verification
- [x] 1.2. Publish What's new in Grafana draft article

**When:** Preliminary Monday 11th November 2019
**What:** 
 - [x] Cherry pick bug fixes into release branch (important for the beta 1 release)
 - [x] Create and push beta release tag and do the actual release

**Who:** @kylebrandt and @aknuds1 

## 3. Create Release Blog Post

**Preconditions:**
- [x] 1.2. Publish What's new in Grafana draft article

**When:** TBD
**What:** 
 - [x] Create Google doc and share with maintainers (Release coordinator)
 - [x] Write draft article (Maintainers)
 - [x] Open a PR (Release coordinator)
 - [x] Publish to staging

**Who:** Release coordinator and maintainers

## 4. Stable Release

**Preconditions:**
- [x] Beta released and no critical bugs left to fix for the stable release
- [x] 3. Create Release Blog Post

**When:** TBD
**What:** 
 - [x] Cherry pick bug fixes into release branch (important for the stable release)
 - [x] Create and push stable release tag and do the actual release

**Who:** TBD

## 5. Publish Release blog post
**Preconditions:**
- [x] 3. Create Release Blog Post
- [x] 4. Stable Release

**When:** TBD
**What:** 
 - [x] Publish blog post

**Who:** Release coordinator

**Comment by dprokop** [comment]
This is great @marefr!

**Comment by torkelo** [comment]
Nice! Great 👍

**Comment by marefr** [comment]
It's out! https://grafana.com/blog/2019/11/25/grafana-v6.5-released/
