### ISSUE TITLE
Provisioning: Cannot save provisioned dashboard

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20211]
**What happened**:
Starting grafana in development mode and see this error message each time provisioning running. 
```
DBUG[11-06|16:30:17] Start walking disk                       logger=provisioning.dashboard type=file name="gdev dashboards" path=devenv/dev-dashboards
DBUG[11-06|16:30:17] saving new dashboard                     logger=provisioning.dashboard type=file name="gdev dashboards" provisioner="gdev dashboards" file=/home/marcus/go/src/github.com/grafana/grafana/devenv/dev-dashboards/panel-polystat/polystat_test.json folderId=1985
EROR[11-06|16:30:17] failed to save dashboard                 logger=provisioning.dashboard type=file name="gdev dashboards" error="Cannot save provisioned dashboard"
```

**What you expected to happen**:
Provisioned dashboard to be saved.

**How to reproduce it (as minimally and precisely as possible)**:
This is an existing provisioned dashboard (1 year old).

dashboard_provisioning row:
```
id | dashboard_id | name | external_id | updated | check_sum -- | -- | -- | -- | -- | --
2562 | 2502 | gdev dashboards | /home/marcus/go/src/github.com/grafana/grafana/devenv/dev-dashboards/panel-polystat/polystat_test.json | 1573035122 | 977b8f242142d17578a4fe5098d64839
```

dashboard row:
```
id | version | slug | title | org_id | created | updated | updated_by | created_by | folder_id | uid -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2502 | 5 | panel-tests-polystat | Panel Tests - Polystat | 1 | 2019-05-27 16:32:47 | 2019-11-06 10:12:02 | -1 | -1 | 1985 | Kp9Z0hTik
```

**Anything else we need to know?**:
Shouldn't validate argument always be false when provisioning saves dashboard? Now code looks like [this](https://github.com/grafana/grafana/blob/master/pkg/services/dashboards/dashboard_service.go#L192) and probably why it fails since allowUiUpdate for devenv provisioned dashboard in grafana repo don't have this flag set to true?

**Environment**:
- Grafana version: master

**Comment by raul1991** [comment]
For me this still does not work.

I copy the exported dashboards to the /etc/grafana/provisioning and when I send out a curl command with the exported json. I get an error "cannot save provisioned dashboard".

Also, I have the allowUIUpdates = true in the config.ini file which I transfer from the docker as well.


# Docker file

```FROM grafana/grafana:6.3.0

ADD ./provisioning /etc/grafana/provisioning

ADD ./config.ini /etc/grafana/config.ini

COPY ./dashboards conf/provisioning/dashboards```

# config file

[paths]
provisioning = /etc/grafana/provisioning

**Comment by jongyllen** [comment]
@raul1991 Just to double check - the `allowUIUpdates` should be set in the conf/provisioning/dashboards .yaml config (where you also configure the folder name and path etc)
https://grafana.com/docs/administration/provisioning/#dashboards
Is that where you set it? 
Also : what version of Grafana are you trying it on?

**Comment by raul1991** [comment]
My grafana version is  6.3.0
and I added the flag under the datasources. I'll give it a try by adding this flag in the dashboard.yml

**Comment by jongyllen** [comment]
The feature itself is introduced in the Grafana 6.5 realease and can be tested in the latest beta.
https://community.grafana.com/t/release-notes-v6-5-x/22704

**Comment by raul1991** [comment]
My bad. I'll upgrade.

**Comment by raul1991** [comment]
@jongyllen I still face the same error after upgrading the image to grafana:6.5.0-beta1

**Comment by jongyllen** [comment]
Hmm, if you run 6.5.0-beta1 and allowUIUpdates: true is in the yaml file inside your directory that you use for provisioning it should work. 

This looks a bit strange to me: `COPY ./dashboards conf/provisioning/dashboards`, maybe a pasting error?

Just to make sure your provisioning config also gets to the correct place - can you share your entire dockerfile and describe what is inside your ./provisioning and ./dashboards folders?

**Comment by raul1991** [comment]
I am not infront of my laptop as of now so I cant share the exact files. However, the folders dashboards and provisioning contain dashboard json files (exported from graphana) and two datasources in a provisioning.yml file.


And, the content pasted above is infact my whole dockerfile.

Important:
In case this helps.

I can update the dashboard with /api/dashboards/db endpoint but can't save it through the gui.

**Comment by jongyllen** [comment]
Please try changing `allowUIUpdates` to `allowUiUpdates`

**Comment by justpresident** [comment]
Another note for future generation:
If you see this error while trying to import dashboard and replace the one provisioned before with the same id it will not work. But you can achieve exactly the same by going to dashboard settings -> Json Model. Paste your new json there and click "Save changes".
While replacing provisioned dashboards by importing was allowed in 5.0.x version of grafana it is not allowed in newer versions.
