### ISSUE TITLE
Can not edit dashboard which is downed from grafana 

### ISSUE THREAD

**Issue by HelenaZheng** [grafana/grafana#20225]
I have download a dashboard from the https://grafana.com/grafana/dashboards. Then I import this dashboard, and found no data in each dashboard. So I see the json inclouding several variables
, but I have no permission to see these variables. 

where can I add the permission to admin user?

**Comment by torkelo** [comment]
permissions? Did you use the Dashboard / import page when you imported? 

Do have the same data source and data collector as the dashboard is targeting?
