### ISSUE TITLE
Regression: Grafana 6.4.4 breaks MySQL login

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [grafana/grafana#20228]
**What happened**:
After updating to Grafana 6.4.4 on Ubuntu, MySQL login with username and password doesn't work any more.

Log line:
`t=2019-11-07T05:46:20+0100 lvl=eror msg="query error" logger=tsdb.mysql err="Error 1045: Access denied for user 'grafana'@'localhost' (using password: YES)"`

**What you expected to happen**:
Login should work (as in Grafana 6.4.3)

**How to reproduce it (as minimally and precisely as possible)**:
- set up Grafana 6.4.3 with MySQL data source
- update to Grafana 6.4.4

**Anything else we need to know?**:
Might be related to special characters in the password?

**Environment**:
- Grafana version: 6.4.4 (grafana_6.4.4_amd64.deb from https://packages.grafana.com/oss/deb)
- Data source type & version: MySQL, Grafana v6.4.3 (commit: 3a2bfb7), mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
- OS Grafana is installed on: Ubuntu 18.04.3 LTS Linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Grafana plugins: default install
- Others:

**Comment by torkelo** [comment]
is your mysql username grafana@localhost ?

**Comment by torkelo** [comment]
What special characters does your password contain?

**Comment by ihatemicrosoft-was-already-taken** [comment]
The username contains a `2` and a `_` in the middle.
The password contains special characters like `@` and `!`. One of the `!` also is the last character of the password.

**Comment by zlzlzlstone** [comment]
Update to 6.6.4 from 6.2 beta found the same error.

**Comment by Zhankin** [comment]
Same error with password contains @

**Comment by djrodek** [comment]
Same error with password contains @

**Comment by ortizleo** [comment]
Same error here.
