### ISSUE TITLE
[BUG] User removed from organization is still marked as in it

### ISSUE THREAD

**Issue by Sytten** [grafana/grafana#20224]
**What happened**:
If you remove a user from all organizations in the system, the call to `/api/users/:id` will still return the field `orgId` as its last known organization.

**What you expected to happen**:
Return `null` in the field.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a user
2. Remove it from all organizations (probably via the API)
3. Call `/api/users/:id`

**Environment**:
- Grafana version: 6.4.3
- OS Grafana is installed on: Linux
- Others: Postgres Database

**Comment by devdil** [comment]
@torkelo can i pick this up?

**Comment by torkelo** [comment]
Yes ❤️

**Comment by devdil** [comment]
@torkelo 
I could reproduce this issue 
I see that for a user belonging to multiple orgs http://localhost:3000/api/users/2

the response is 
`{
id: 2,
email: "test1@gmail.com",
name: "test1",
login: "test1",
theme: "",
orgId: 2,
isGrafanaAdmin: false,
isDisabled: false,
isExternal: false,
authLabels: [ ],
updatedAt: "2020-01-26T22:19:43+05:30",
createdAt: "2020-01-26T22:19:43+05:30",
avatarUrl: "/avatar/245cf079454dc9a3374a7c076de247cc"
}`

What does this orgId field indicate for a user belonging to multiple orgs, last added orgId or shouldn't this be orgs?

Moreover the other api http://localhost:3000/api/users/2/orgs returns [] which is expected. 

Let me know your thoughts

**Comment by marefr** [comment]
@devdil 
> What does this orgId field indicate for a user belonging to multiple orgs, last added orgId or shouldn't this be orgs?

The currently active organization of the user. When switching org in UI the user will be updated to reflect this.

Just tried creating a user and then removing the only org it had. This user is not Grafana server admin. But I can still login with this user and on the homepage I see the side menu with access to Dashboards (Home, Manage, Playlists, Snapshots) and Configuration (Plugins), however I cannot see any dashboards, folders, playlists, snapshots, only the list of plugins:
![image](https://user-images.githubusercontent.com/1668778/73377894-10b9fd80-42c0-11ea-99d5-9ef237ade1c6.png)

Really confusing. But that's another possible issue.

Regarding your suggested fixes. The org_id column in the user table in database cannot be `null`. Tried to change it to `0`, but same behavior calling http://localhost:3000/api/users/2. 

Probably a good idea to set org_id to zero if possible. Your suggestion of changes in  "handlerFunction of removeOrgUser" may not be needed, but instead in the sqlstore package which the handlerFunction calls. If I'm thinking straight adding an else condition to this:
https://github.com/grafana/grafana/blob/c15ddc295cc10560bb94fe4567a9b33f61ab8496/pkg/services/sqlstore/org_users.go#L185-L207

And then set org id to zero using
https://github.com/grafana/grafana/blob/c15ddc295cc10560bb94fe4567a9b33f61ab8496/pkg/services/sqlstore/org_users.go#L195-L198

The regarding UserProfileQuery, the only thing you have to change I think is to add `omitempty` to `OrgId`, like
```go
  OrgId          int64     `json:"orgId,omitempty"`
```
at https://github.com/grafana/grafana/blob/c15ddc295cc10560bb94fe4567a9b33f61ab8496/pkg/models/user.go#L217-L231

Let me know if you have any questions/thoughts.

**Comment by devdil** [comment]
@marefr makes sense...

**Comment by idafurjes** [comment]
still valid on version 8
