### ISSUE TITLE
Improve panel edit-experience

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20231]
Flesh out a new panel edit layout (based on visualization setting to the right in a single column). 

- [x] Test the initial idea with users
- [x] Finish the first version
- [x] Run usability tests
- [x] Make final improvements

**Comment by MacNale** [comment]
I tried 7.0 beta. I have been using Grafana 6.5.3. As I am used to the query control and the option on the left hand side, I did not feel good about the right hand side vertical layout of the options.  Lets see, after few days if my experience changes.

**Comment by sarlinska** [comment]
@MacNale thank you for your feedback. Could you say a bit more on why the right hand side doesn't feel good for you?

**Comment by MacNale** [comment]
I am getting familiar with the new way of working in v7. My opinion is changing :). I will provide feedback once I spend enough time. 
Initial reaction - 
1) Having Panel Title/Description etc under one options panel is good improvement. Options are easily accessible now.
2) Some of the options requires horizontal scrolling to reach out. e.g Axes options.

**Comment by sarlinska** [comment]
@MacNale  2 & 4  are improved already in beta2

**Comment by MacNale** [comment]
There must good reason to move the panel options as vertical bar on the right hand side. I tried 7-beta3.  I think, the previous 6.7 layout of the options was neat and clean. It feels like, I need to train my users now to locate the options. I intend to give my opinion here, not to criticize the work. I love grafana.

**Comment by rmunoz10** [comment]
Regarding "Add Panel -> Text Panel -> Edit the Markdown/HTML" the content area is also too small (only 10 lines). Is there a way to resize it?

BTW, I also prefer v6.6 layout

**Comment by torkelo** [comment]
Thanks for the feedback. We will work with plugin authors to update so use the new option & override model. It should make panels more similar and easy for users (and plugin authors). That is the hope, we will keep collecting feedback and polishing and tweaking this new edit UI
