### ISSUE TITLE
Allow POST /admin/users to create users without predefining password

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#20232]
**What would you like to be added**:
Possibility to create new users via  API without defining user password

To allow user creation without predefined password the grafana settings of account creation notification must be enabled in grafana.ini , then user will get an email where he/she will click the link that will activate the account when user has entered its password and saved  the new account configuration. 

**Why is this needed**:
1. From the security point of view , current requirement supports a case where admins will :
a) define default password for all users  and ask to change it  but in reality most users wont change it and it is simple  to get access others accounts if you notice that everyone has same default password .
b) will create random hash password ( which is also plain text password ) and must send this via email or is possible sms can be used but still the user creation process leaves too many places where the password of users may be visible for others ( ansible logs if no_log is not defined and so on )
2. Let users decide how they like to manage their passwords. Simpler for them to remember it.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
