### ISSUE TITLE
GEL: data doesn't always render in graph

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#20242]
**What happened**:
Using master, when in the query editor and on the queries tab, hitting refresh will cause data to disappear from the graph. Repeated refreshes do not show the data. If I switch to the visualization tab and hit refresh, the data appears again.

Before Refresh:

![image](https://user-images.githubusercontent.com/1692624/68395079-0f53bb80-013d-11ea-998b-4562758a8215.png)

After Refresh:

![image](https://user-images.githubusercontent.com/1692624/68395086-124eac00-013d-11ea-898e-5e9b9abbb645.png)

**Environment**:
- Grafana version: master
- Data source type & version: GEL and Testdata
- OS Grafana is installed on: Linux
- User OS & Browser: Linux Chrome
- Grafana plugins: GEL
- Others:

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/20247 

all graphs where empty in edit mode :(

**Comment by kylebrandt** [comment]
Confirm fixed for me, thank you!
