### ISSUE TITLE
OAuth role mapping from id token doesn't work

### ISSUE THREAD

**Issue by andrsp** [grafana/grafana#20243]
**What happened**:
Grafana + Keycloak openid-connect = no user roles
Especially because of https://github.com/grafana/grafana/blob/master/pkg/login/social/generic_oauth.go#L220
`s.extractToken` returns true, so `rawUserInfoResponse` (which is used as data source in calls to `extractEmail` and `extractRole`) remains empty because HttpGet only executed if `s.extractToken` returns false.

**What you expected to happen**:
Grafana picks up user role based on `role_attribute_path` expression in grafana.ini config

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure oauth client in keycloak for grafana
2. Check that keycloak/.../userinfo endpoint returns data with user roles
3. Set grafana oauth config to use keycloak's openid-connect endpoints
4. Set `role_attribute_path` option to extract user role from userinfo

**Anything else we need to know?**:
Issue related to https://github.com/grafana/grafana/pull/17149
I was able to fix this issue by changing `if` expression in https://github.com/grafana/grafana/blob/master/pkg/login/social/generic_oauth.go#L220 from negative to positive, but I'm not sure if it's right =( (probably not)

**Environment**:
- Grafana version: 6.5.0-pre (from master)
- Data source type & version: (n/a)
- OS Grafana is installed on: (official docker image)
- User OS & Browser: (n/a)
- Grafana plugins: default
- Others: nope

**Comment by Hokwang** [comment]
will this fix in 6.6 not 6.5.x ?

**Comment by sxd** [comment]
@marefr so this will be the official issue related to this right? but I don't see a pull request here, sorry if I miss something

**Comment by marefr** [comment]
@sxd It's referenced in the activity above `seanson linked a pull request that will close this issue 24 days ago`  #20300

@Hokwang probably 6.6.

**Comment by pkvel01** [comment]
Do we have any workaround till we get this fix in 6.6?

**Comment by sxd** [comment]
@pkvel01 I haven't found any workaround and I've tried on keycloak and grafana side =(

**Comment by sfro** [comment]
This would be great to fix! We are also running into this issue with OneLogin.

**Comment by DikshaTomar101** [comment]
how can we integrate graphana with keycloak and what changes to make in keycloak
