### ISSUE TITLE
Loki: Derived field changes not saved in same cases

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#20252]
With new derived fields feature https://github.com/grafana/grafana/pull/20060 when you have focus in the url input and then click directly on `Save and test` last changes are not saved. I assume that is because we propagate changes on blur there (it is a slate component) while the save is handled by angular so I assume the new state is not being propagated in time.

**Comment by aocenas** [comment]
@ivanahuckova to let you know about this as you should be doing QA on that.
@dprokop do you know how this is mitigated in panel settings?

**Comment by aocenas** [comment]
@marefr added this to 6.5 milestone but as I do not have quick fix now it is probably ok to do as part of beta.

**Comment by ivanahuckova** [comment]
@aocenas Saving, even when I have focus in the url input works for me.

**Comment by aocenas** [comment]
@ivanahuckova This is what happens to me:
- edit field
- keep focus in the url input
- click save
- reload

![Kapture 2019-11-07 at 18 10 27](https://user-images.githubusercontent.com/1014802/68411000-f7eeef80-0189-11ea-85d0-114273587e6c.gif)

**Comment by ivanahuckova** [comment]
My experience - not buggy at all:
![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/30407135/68411741-4d77cc00-018b-11ea-9a84-29dbb383f22b.gif)

**Comment by marefr** [comment]
@aocenas 

> added this to 6.5 milestone but as I do not have quick fix now it is probably ok to do as part of beta.

Yes absolutely

**Comment by marefr** [comment]
@aocenas is this work in progress or can I move it to 6.6 milestone?

**Comment by davkal** [comment]
Hmm, can't repro in Chrome 78.0.3904.108 nor Firefox 70

**Comment by aocenas** [comment]
@davkal yeah no idea what is the problem, I still see the issue but seems like right now there are more people without it. I may take more look at that but I assume for now this has low priority as it may be something just on my side.

**Comment by marefr** [comment]
Removed the milestone for now. Please add to a milestone if this is still a valid fix.
