### ISSUE TITLE
Show a "Save As" button on dashboard if normal saving is disabled (scripted/provisioned dashboards)

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#20250]
Certain dashboards don't support saving (Provisioned/Scripted dashboards), however users can still "Save As"/fork these dashboards by going into the settings menu for the dashboard. This is non-obvious though because the "Save" button isn't displayed on the dashboard itself.

For scripted dashboards, the Save button is no longer on the dashboard despite the user having the ability to Save As it from the settings page

![Screen Shot 2019-11-07 at 10 39 10 AM](https://user-images.githubusercontent.com/3194832/68403388-dae6fc00-014a-11ea-815c-484f69d99892.png)

For provisioned dashboards, the UX is a little better. The save icon is there and the user is presented with a modal explaining it can't be overwritten, however it doesn't provide a "Save As" button in the modal which means the user has to copy and paste the json by hand into a new report

![Screen Shot 2019-11-07 at 10 40 33 AM](https://user-images.githubusercontent.com/3194832/68403520-0ec22180-014b-11ea-91f1-9a7c39afe0b4.png)

In either of these cases, the user is given a "Save As" button but its hidden inside the dashboard settings menu 

![Screen Shot 2019-11-07 at 10 36 49 AM](https://user-images.githubusercontent.com/3194832/68403195-8d6a8f00-014a-11ea-8e4c-0d8f8bcd151d.png)

----

Not sure what the right UX is. We could change the Save button to turn into a dropdown of "Save" and "Save As" (and we could ghost out "Save" in these scenarios), however for someone saving a normal dashboard, we've added an unnecessary click.

Another idea would be to copy the Provisioned Dashboard overwrite modal and design a similar one for scripted dashboards, (while also adding a new "Save As" button in both modals).

Thoughts?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
