### ISSUE TITLE
CloudWatch should have min_interval option

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#20259]
**Why is this needed**:
Related to https://github.com/grafana/grafana/issues/20262 .
Most of CloudWatch minimum Period is 60 seconds.
When query range is 15 min (or short period), the `$__interval_s`  becomes shorter than 60 seconds.

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can't see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
