### ISSUE TITLE
Transformers: filter results by refId

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#20251]
**What would you like to be added**:
The ability to filter to the results of a specific query (or queries ideally) when using the Dashboard datasource for a shared query.

**Why is this needed**:
So I the internal Demo of GEL next week is better - very urgent. If I have a long GEL pipeline, I would like to have a dashboard that shows different visuals of different parts of that pipeline.

So for example with something like:

![image](https://user-images.githubusercontent.com/1692624/68408248-01a93080-0153-11ea-8e25-fdf59dfc4d1c.png)

I currently see the following using the Dashboard (Shared Query) Datasource:

![image](https://user-images.githubusercontent.com/1692624/68408740-e2f76980-0153-11ea-8e25-a9ba209711ad.png)

What I would like to be able to do is have one panel Show A and B, another show C, D, etc. Those panels might use different visualizations.

**Comment by kylebrandt** [comment]
@ryantxu pretty please?

**Comment by ryantxu** [comment]
what you are describing is exactly why frontend transformations exist ;)

Add the feature flag for `transformations`... I have:
```
[feature_toggles]
enable = transformations, expressions, inspect
``

And you should see:
![image](https://user-images.githubusercontent.com/705951/68432768-ec8bcc00-0169-11ea-9f3a-d3521b047838.png)

so... I think what you are really asking for is a transformer that picks stuff by refId?

Note that the panel does not really know what query the DataFrame came from *unless* the refId is attached to it

**Comment by kylebrandt** [comment]
> what you are describing is exactly why frontend transformations exist ;)
> 
> Add the feature flag for `transformations`... I have:
> 
> ```

> so... I think what you are really asking for is a transformer that picks stuff by refId?
> 
> Note that the panel does not really know what query the DataFrame came from _unless_ the refId is attached to it

Yes, that sounds like what I am after

**Comment by ryantxu** [comment]
I changed the title to reflect where this needs to happen
