### ISSUE TITLE
Dashboard Rows should always have it's panels nested in JSON Model not only when collapsed

### ISSUE THREAD

**Issue by hexedpackets** [grafana/grafana#20253]
**What happened**:
Collapsing a row in the UI causes panels within that row to disappear from the top-level panels array in the dashboard JSON. This happens in both the "JSON Model" from the dashboard setting and the `/api/dashboards/uid/{UID}` endpoint. The panels instead move to the nested `panels` array under the row panel, which is empty when the row is not collapsed.

**What you expected to happen**:
Panels within a row should either always show up in the dashboard `panels` key, or never show up and always be nested under the row. The inconsistent response based on the collapsed status makes it difficult to parse the API results.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a dashboard
- Add a row
- Add a panel within the row
- View the JSON, the panel will be under `{"dashboard": {"panels": [...]}}` and the row panel will have an empty array for its nested panels
- Collapse the row
- View the JSON, the panel will be moved to the nested row panel's panels

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The grid component does support nested grids sadly (and it becomes very messy faking it). So this was sort of a compromise in order to still support the legacy row concept from Grafana prior to v5 (when rows were needed for layout).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
