### ISSUE TITLE
Grafana 6.5.0-pre : $rootScope.onAppEvent is undefined

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#20255]
Hello,

In FlowCharting with Grafana 6.5, $rootScope.onAppEvent is undefined

...
  /** @ngInject **/
  constructor($scope, $injector, $rootScope, templateSrv) {
       console.log("$rootScope",$rootScope);
...

Best regards
Arnaud

**Comment by torkelo** [comment]
Unable to replicate: 
![image](https://user-images.githubusercontent.com/10999/68579625-df762200-0474-11ea-96cb-e87cf14d6fe4.png)

**Comment by torkelo** [comment]
The latest published plugin version loads fine for me.

**Comment by algenty** [comment]
Hi,
Thx for your investigation, i'll try again
With Rayn and Dominik, i'll try to convert plugin in ts with grafana-tooltip
BR

**Comment by algenty** [comment]
Hi @torkelo,

I have 2 issue for the version 6.5.
https://github.com/algenty/grafana-flowcharting/issues/88
https://github.com/algenty/grafana-flowcharting/issues/89

I confirm, root is undefined in the version.
I found a solution with version 0.6.0 of flowcharting but i need more time before release it.
Tookit migration take me many times.
Perhaps, other plugins didn't work with this version.

BR
Arnaud
