### ISSUE TITLE
Max legend value doesn't work properly for negative values.

### ISSUE THREAD

**Issue by oprietop** [grafana/grafana#2025]
That's a network graph using grafana 2.0.2, i'm using scaleToSeconds(-8) on the outbound traffic.

http://i.imgur.com/bmXuLRM.png

"gi0_10 | bits out" is actually hitting -74.8 Mib at the tooltip while the legend is showing -3.9 Mib.
The current legend value is showing the right values.

**Comment by torkelo** [comment]
last time I checked -3.9 > -74.8 

So yea, the legend values do know know that you have inverted a series. It could be normal series that  have some negative values. max means highest number, not the highest number of absolute value. 

For this to work I the way you expect I think grafana needs to invert the series (and in a display only way, not in a turn all values to negative way)

**Comment by oprietop** [comment]
Yeah, maybe a invert "Series specific overrides" option or similar could do the trick, that would also simplify things creating the graphs if you are involving filtering functions.

**Comment by torkelo** [comment]
yea, I think a series override "invert" makes sense
