### ISSUE TITLE
Support tree shaking in blobUrl loader

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#20269]
Webpack optimized for tree shaking es6 import/exports, so I suggest to use es6 exports in loaders

**What would you like to be added**:

https://github.com/grafana/grafana/blob/master/scripts/webpack/loaders/blobUrl.js#L5

replace `module.exports = ` on `export default`

**Why is this needed**:

enable [tree shaking](https://webpack.js.org/guides/tree-shaking/)

UPD: looks like custom loaders does not use anymore

**Comment by torkelo** [comment]
Can you describe this issue more? Not sure that blobUrl loader is ever used

**Comment by vankop** [comment]
> Can you describe this issue more? 

I am creating grafana plugin using https://github.com/grafana/simple-react-panel, so I decided to take a look on sources and found out this loader

> Not sure that blobUrl loader is ever used

Yes it does not using anymore.

I think we can close issue

**Comment by vankop** [comment]
@torkelo Sorry for offtop, can I somewhere share plugin development feedback?
