### ISSUE TITLE
[Suggestion] Make metrics share a color based on node path.

### ISSUE THREAD

**Issue by oprietop** [grafana/grafana#2026]
I'm currently digging a lot into network graphs and one of the things i could really find useful is being able to use the same color for the same interface because it's visually intuitive. 

Imagine that kind of metrics:
snmp.switch1.traffic.eth12.bits_in
snmp.switch1.traffic.eth12.bits_out

I don't know if there can be a better approach but a "Display Style" option or a kind of shareColorByNode(3) function could do it.

**Comment by torkelo** [comment]
not makes sense to me. you want bits_in and bits_out to be the same color?

**Comment by oprietop** [comment]
Yeah, in -this- case i would want to have both metrics in the same color but i can see how it can be useful to group in other circunstances.

For example take into account the next graph, it belongs to router and is showing network traffic for only 3 interfaces:

http://i.imgur.com/nlYcwT0.png

As you see here we have 6 metrics, 3 on each axis. Due to the nature of the information the graph isn't that useful because 

Instead if we are able to correlate both negative and positive values of the Y Axis to the same color for every interface we actually make the graph useful because:

-Now we can diferenciate interfaces at first glance, we don't even need the legend.
-We are using half the colors in that to show the same metrics, less bloat.

http://i.imgur.com/htzbp2d.png

Color doesn't matter If you are graphing a single network traffic, disk IO, swap in/out... etc. But if you want to show at once more that one kind of data that needs that kind of correlation on a same graph it becomes messy and unusable.

To do this on the pre-grafana era i just used to hardcore the colors on the metric queries on the collector side, it was really ugly but at the end it really made those kind of graphs more useful.

**Comment by torkelo** [comment]
The main issue here is that node indexes are not returned from graphite. So it has be based on the series names.
