### ISSUE TITLE
AdHocFilter: Filter not shown

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#20270]
1. Create a new Dashboard
2. Create a Table Panel with a filterable query
3. Click on `Filter for Value`
4. Ad Hoc Filter component should appear in Dashboard menu but doesn't (Not OK)
5. Click on Dashboard Settings, or choose View/Edit Panel
6. Ad Hoc Filter component appears in Dashboard menu (OK)

Able to repro this on Play https://play.grafana.org/d/zRuC9I1Wz/issue-with-adhoc-variables

![adhocfilters](https://user-images.githubusercontent.com/562238/68471722-118e4680-021f-11ea-9794-719a4def0904.gif)

**Comment by marefr** [comment]
@hugohaggmark works for me at play when adding a new ad hoc query variable for datasource Robust perception. So not sure this is a bug?

**Comment by torkelo** [comment]
I can replicate it.
