### ISSUE TITLE
Add support for getting the secureJsonFields values from the HTTP API /api/datasources/{id}

### ISSUE THREAD

**Issue by HemendraSingh** [grafana/grafana#20274]
**What would you like to be added**:

Add support for getting the secureJsonFields values from the HTTP API /api/datasources/{id}.

**Why is this needed**:
I am developing an application which uses Grafana HTTP API to get data source details.
And i am not able to read secureJsonFields value.
Currently i am getting "grafana-azure-monitor-datasource" jsonData without the client secret.

**Comment by marefr** [comment]
Thanks for suggestion. However, due to security reasons we don't want to expose this sensitive information thru the API.

**Comment by m0dular** [comment]
Would there be any chance of implementing this?  The issue we're seeing is that we can't accurately get the state of `grafana_datasource` resources using the [Grafana Puppet module](https://forge.puppet.com/modules/puppet/grafana).  I would expect to be able to get the state of datasources if I have the right credentials.

**Comment by alexjfisher** [comment]
@marefr How about returning some cryptographic hash of the data instead?  That would allow us to tell if the value we had for a secret matched what was already stored in grafana.
