### ISSUE TITLE
Docs: Option disable_brute_force_login_protection missing in config docs

### ISSUE THREAD

**Issue by raulluzon** [grafana/grafana#20287]
In grafana v6.4.x the property GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION is not used, is there a substitution for this property or it is definitely obsolete?

**Comment by torkelo** [comment]
this is working fine. 

export GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=true

started grafana-server , see setting set to true

**Comment by raulluzon** [comment]
thanks @torkelo , I did not see that parameter in the documentation

**Comment by vikkyomkar** [comment]
Hello @torkelo, i would like to work on this issue..pls assign it to me

**Comment by torkelo** [comment]
👍

**Comment by flopp999** [comment]
Is this a setting that you activate in Grafana.ini?
I would like to enable this to my running Grafana.

**Comment by marefr** [comment]
@flopp999 it's enabled per default

**Comment by flopp999** [comment]
> @flopp999 it's enabled per default

When the document is ready for this maybe my question is answered.

I tried to login to my account about 30 times with wrong password and it doesn’t seems to do anything?

Should it lock my IP it what should happen?

**Comment by marefr** [comment]
@flopp999 you have to login with a username of an existing user with wrong password. There's an existing feature request to expand feature to cover IP address as well #12836
