### ISSUE TITLE
Allow to have more than 3 colors threshold in singlestat and table panel

### ISSUE THREAD

**Issue by dcastanier** [grafana/grafana#20285]
**What would you like to be added**:
Currently, number of colors threshold in singlestat and table panel is hard coded at 3.
It's could be nice to allow to choose more colors threshold.

**Why is this needed**:
I need to reproduce with Grafana an existing dashboard that use 10 colors threshold to reflect a level of quality.

**Comment by torkelo** [comment]
This will come when we launch the new singlestat and table panels, will use same threshold editor as gauge and bar gauge.

**Comment by dcastanier** [comment]
Thanks for your response !
An idea of when this new panel will be available ?
