### ISSUE TITLE
how to do auto incremnet in world map panel

### ISSUE THREAD

**Issue by aqieez** [grafana/grafana#20295]
Hi all, i am new to grafana and i have installed world map plugin. i am using postgresql as my database. in my database i have a table cycle. cycle contains up to 1 millions rows. each row has time and latitude and longitude values. 
SELECT $__timeGroupAlias("time",1s),
  avg(lat) AS "lat",
  avg(lon) AS "lon"
FROM cycle
WHERE
  $__timeFilter("time") AND
  entityid = 352753092424447
GROUP BY 1
ORDER BY 1
LIMIT 1
i want to update point on map after evey one second so it would look like live data. how can i do that i really have no idea please help.

**Comment by torkelo** [comment]
set dashboard auto refresh (next to timepicker), it will cause all panels to re-excecute the query and re-render
