### ISSUE TITLE
grafana is saving existing dashboard again and again and creating its new id in database

### ISSUE THREAD

**Issue by Deepak1100** [grafana/grafana#20296]
**What happened**:
i am seeing frequent 404 in slected dashboard on search and on dashboard load. So if i refresh dashboard it will give me 404 some time and sometimes it works.
after running it in debug mode i got to know thats its saving those dashboards again and again and in database it's creating new ids for those dashboard.

```
t=2019-11-11T07:57:21+0000 lvl=dbug msg="saving new dashboard" logger=provisioning.dashboard type=file name=0 provisioner=0 file=/grafana-dashboard-definitions/0/k8s-resources-cluster/k8s-resources-cluster.json folderId=0
t=2019-11-11T07:57:21+0000 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=0
t=2019-11-11T07:57:21+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=1 uname= dashId=0 action=Edit
t=2019-11-11T07:57:21+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=1 uname= dashId=978692 action=Edit
t=2019-11-11T07:57:21+0000 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=0
t=2019-11-11T07:57:21+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=4
```

in database i am seeeing entry like this(while the dashboard those working fine have id from 1-80). 
<img width="986" alt="Screen Shot 2019-11-11 at 1 32 12 PM" src="https://user-images.githubusercontent.com/13719412/68570944-cdea4580-0487-11ea-9169-e39ed05efcde.png">

and their ids is changing, again and again, i.e its getting deleted and created back. and hence i am getting 404

i have tried updating it to latest version but its not working.

**What you expected to happen**:
its should load those dashboards only once and its never save them again unless there are changes.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.1 and 6.4.4
- Data source type & version: prometheus
- OS Grafana is installed on:  official grafana docker image
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Please include dashboard provisioning config and one of the dashboards that keeps getting saved over and over again. Please remove sensitive information, if any,

**Comment by Deepak1100** [comment]
@marefr  i have found the issue. actually we have 2 different grafana deployment using the same database and as wee are using file based dashboard the other one didnot have those specfic dashboards. and so the 2nd deployment was removing them from database and 1st deployment was keep adding them.
