### ISSUE TITLE
Add "combine" option to repeating template variables

### ISSUE THREAD

**Issue by TryTryAgain** [grafana/grafana#20292]
**What would you like to be added**:

What I feel is reasonable:
I can imagine a "Combine" option being added to repeating template variables, in addition to Horizontal/Vertical (repeating panels), it would be incredible to have the power and ability to repeat into the panel itself; simply add up.

Possibly a pipedream?:
It would be even more powerful and useful if you could then append/prepend/regex the Alias for the metrics based on the source metric, automatically based on the variable name, or something more flexible. For example, if you were to choose the "Direction": Self, Internal, Combine, _whatever_ for the repeating template variable, rather than "Max per row" like for the Horizontal/Vertical options, when choosing the hypothetical "Combine" option you'd be presented with the ability to manipulate Alias and possibly other options related to the template variable source?

**Why is this needed**:

Although I have come across the need before and I've read related issues where others are looking to achieve similar results, my current use case is the need to combine/add up multiple CloudWatch metrics across hundreds of accounts.

For example, say I have:
1500 CloudWatch datasources/accounts. 500 of them for Company A, Company B, and Company C. Right now I can display all of these just fine in a single dashboard using repeating panels based on variables and regex filters to display each datasource's metrics within collapsable rows per Company and with multi-value and all options enabled as well, but for some of the metrics (seemingly more often nowadays), I'm looking for totals across all variables. 

My actual use case:
I have variables: $CompanyA, $CompanyB, $CompanyC (CloudWatch datasource variables) that get all CloudWatch datasources based on a regex filter and they're set up for multi-value and all options. I have a dashboard with Rows for Company A, Company B, and Company C. Within each row is a single panel configured to display AWS/TrustedAdvisor metrics. That single panel is a repeating panel that reacts to the single, multi-value, and all options selected... as expected.

But, I would really see value in being able to sum up all of the metrics from all datasources. At the scale I'm dealing with being able to display and browse 500 panels is cool and useful but I can really see the need for being able to get totals across datasources as well as other variable types.

I hope that's easy enough to follow and something that can be considered. I understand my description may make it seem like an edge case but I wouldn't be surprised if this is a much sought after feature ;)

**Comment by TryTryAgain** [comment]
I'm assuming some of this will be resolved with 7.0 release and transformations, but I haven't figured it out for my scenario above or for others I'd hoped would be solved by transformations :-|

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
