### ISSUE TITLE
UI Improvement: left bar

### ISSUE THREAD

**Issue by cemo** [grafana/grafana#2029]
@torkelo One of my colleague find adding a datasource into his experimental setup today. He was completely new to grafana and I believe that he has enough competence for web applications but he could not find left bar. The grafana icon seems to him a little bid non intuitive and I had to inform him to click it. An UI improvement regarding it might be nice. Maybe an arrow at the left side indicating a closable panel? 

( I remember that there were some related discussions but could not find them. )

**Comment by mattttt** [comment]
Cemo,

Excellent feedback. We were just chatting about this the other day as well, and think there is certainly room for improvement. 

I want to work on a couple new versions that try and make that a lot clearer. In this case, sacrificing a bit of screen real estate for a more intuitive trigger would be well worth it.

**Comment by vchekan** [comment]
One more related thing: I took me and my colleague a while to understand how to quit from "Grafana Admin" page. Using a menu item on the left bar to exit from dialog is highly unusual.

**Comment by torkelo** [comment]
@vchekan what dialog?

**Comment by vchekan** [comment]
@torkelo "Grafana Admin"

**Comment by torkelo** [comment]
Moved to https://github.com/grafana/grafana/issues/3687
