### ISSUE TITLE
Grafana LDAP / AD nested group access from trusted domains

### ISSUE THREAD

**Issue by RichardHicklin** [grafana/grafana#20291]
in a scenario that you have 2 windows domains, 1 on prem that host all internal user accounts and another domain in the cloud, used for Role based access to cloud tooling. how do you configure the ldao.toml

users from the local domain are placed into groups in the cloud domain. i can nogt located the group membership for the users.

**Comment by torkelo** [comment]
This is not supported, your ldap groups need to be located in the same ldap server as your users

**Comment by RichardHicklin** [comment]
Might be a good idea to update the documentation as its not clear. i can see this becoming a pain point for other who have to try and integrate with a trusted domain model. The guide eludes to an approach of nested group referral, if its only within the same then stating that would clear things up. 

Kind Regards Richard

**Comment by RichardHicklin** [comment]
> This is not supported, your ldap groups need to be located in the same ldap server as your users

Might be a good idea to update the documentation as its not clear. i can see this becoming a pain point for other who have to try and integrate with a trusted domain model. The guide eludes to an approach of nested group referral, if its only within the same then stating that would clear things up.

Kind Regards Richard
