### ISSUE TITLE
Variable + Repeat not working with NewRelic plugin

### ISSUE THREAD

**Issue by krinklesaurus** [grafana/grafana#20303]
**What happened**:
I created a custom variable `apps` with values `App1` and `App2` and then use this variable for a charts panel with Application `$apps`. I also set `$apps` as the title for the panel and set Repeating for the panel to `$apps`. When I select both Apps in the variable drop down, the panel appears twice, one panel has title `App1`, the other has title `App2`. The query to NewRelic however is done using a list of `App1,App2`:

Web developer console shows: `/api/datasources/proxy/25/v2/applications/%7BApp1,App2%7D/metrics/data.json?from=2019-11-11T08:31:00.212Z&names=Apdex&period=30&to=2019-11-11T14:31:00.212Z&values=score`

Of course the App `App1,App2` is not found and no Apdex shown. I double checked with DataDog plugin and there it is working without an issue. 

**What you expected to happen**:
The first panel should show the Apdex for `App1`, the other panel the Apdex for `App2`

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.1
- Data source type & version: NewRelic 1.1.0
- OS Grafana is installed on: Runs on AWS ECS Fargate in Docker container 6.1.1
- User OS & Browser: macOS Mojave 10.14.6
- Grafana plugins: NewRelic
- Others: -

**Comment by torkelo** [comment]
Confirmed this, opened a bug to track this in our internal new-relic ds repo. 

but leaving this open until it is fixed.
