### ISSUE TITLE
Prometheus: Query hint in explore show on all rows

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#20305]
0. Explore with Prometheus
1. Run two queries: `go_goroutines` and `alertmanager_alerts_received_total`

Result: both query fields get the "rate()" hint from the `...total` metric (`go_goroutines` is a gauge).

<img width="435" alt="Screenshot 2019-11-11 at 16 44 46" src="https://user-images.githubusercontent.com/859729/68601045-dcdef100-04a3-11ea-8821-f50aa87cdca2.png">

Note: This behavior does not happen in #20275 in panels, which removed some request tracking. But still broken in Explore.

**Comment by torkelo** [comment]
Should try to share this function between explore & dashboard:
filterPanelDataToQuery  think it's missing in Explore QueryRow: 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/panel_editor/QueryEditorRow.tsx#L310

**Comment by aocenas** [comment]
Should be fixed already
