### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#20319]
**Outcomes**
- [ ] Understanding of requirements from important customers with big installations (e.g., Bloomberg, Uber)
- [ ] Tested knowledge of ways to search for dashboards with terms other than the title of the dashboard (e.g., query metrics)
- [ ] List of most important requirements and use cases.
- [ ] List of most crucial pain points.
- [ ] Recommendations and mockups of how improved search could look like.

**Comment by daniellee** [comment]
Searching for metrics is one of our oldest feature requests: #264
