### ISSUE TITLE
unable to use loki's metrics endpoint as a Query datasource for variables

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#20311]
**What happened**:

Using Loki's metrics endpoint as a Query datasource for variables, but getting error (see image)

![image](https://user-images.githubusercontent.com/35603/68611012-68af4800-04b9-11ea-9aa8-9a627947f2af.png)

**What you expected to happen**:

Getting label values from Loki's metrics endpoint

**How to reproduce it (as minimally and precisely as possible)**:

- Create Prometheus datasource with Loki as endpoint (e.g. http://loki:3100:/loki).
- Define a variable using a metric query on that datasource
- notice error (see screenshot)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Master (11/11/2019)
- Data source type & version: Loki Metrics datasource
- OS Grafana is installed on: OSX
- User OS & Browser: Safari v13
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
Should be investigated if the this behavior is present with Loki datasource as we should already support the same things as with prometheus datasource. Second thing is that for this usecase we may need to implement see https://github.com/grafana/grafana/issues/25205

**Comment by ivanahuckova** [comment]
I have tested this out an it is working as expected - you can create template variables for Loki using it as Prom datasource. 
![image](https://user-images.githubusercontent.com/30407135/95365506-82782b80-08d2-11eb-9d08-b999c61d5160.png)
