### ISSUE TITLE
autocomplete for influxdb 0.8 unusable when series list is long

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2031]
In the series input, grafana calls `list series` when ever I input one char. This produces problems when series list is long.

See below: 

![2015-05-21 11 16 00](https://cloud.githubusercontent.com/assets/2576762/7740912/cec7c16c-ffaa-11e4-82d8-f0b8702563e2.png)

The page freezes and becomes unusable. Grafana may provide an option to only autocomplete when I input `enter` or something else to trigger the autocomplete. This can help because there will be much less series when I finishes input.

**Comment by torkelo** [comment]
Wow, that is some really slow InfluxDB queries. Will try to fix.

**Comment by torkelo** [comment]
This seems like a bug in influxdb 0.8 list series api wich makes it increadibly slow, seems to have been an issue for a long time. Seems to be fixed in 0.9

**Comment by liyichao** [comment]
The problem is not that the request is slow, but that grafana `freezes` when the returned list is long. Grafana sends too many requests, each request gets millions of series back, and then chrome refuses to response to user interaction.

**Comment by torkelo** [comment]
ah, sorry, only though the issue was the 50 second request times for the series list request

**Comment by liyichao** [comment]
After migrating my influxdb 0.8 to a new instance. The time ranges from 20s to 1s now, where 20s represents getting a list of all series. If grafana can delay the request until I input more text into the series name, the request can complete.

In the current implementation, it seems whenever I input one char, the grafana sends a request. Because  our series list is long (millions of series). I encounter a timing in which the request stalled for 17s and downloading  the contents takes 27.94s, the content is 13 MB. While the request when I finished input completes in 1s. But the former request makes chrome freeze and delay the display the last response.

I also found that if the result of autocomplete exceeds certain number, the grafana refuses displaying them, the scroll just can not go down as far as the last item.

**Comment by torkelo** [comment]
@liyichao you are welcome to try to fix this, I would love to find the time. But since InfluxDB 0.9 is a total rewrite and I am working on support for that. InfluxDB 0.8 support will continue but not see further development, except patches for things like this.
