### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#20315]
Purpose is to have a consistent Design System, that can serve both as an educational material for designers and building blocks for rapid work on mockups.

Outcome
- [ ] MVP Design System build in Figma as components.
- [ ] Guideline and rules for creating new elements/components.
- [ ] Defined next steps in Design System evolution.

**Comment by pranay01** [comment]
Hi, where can I see current design files being used for building grafana? Preferably figma/ sketch files
