### ISSUE TITLE
Use process.env.PORT rather than 3000?

### ISSUE THREAD

**Issue by danassetms** [grafana/grafana#20313]
**What happened**:
Trying to use Grafana as a docker image in Azure Web Apps you don't get to choose the port that Grafana can have as a backend port because the VNet intgration feture screws the -port of docker run up for you.  https://github.com/Azure/app-service-linux-docs/blob/master/app_service_linux_vnet_integration.md

I get this in my logs as the docker run comand: docker run -d -p 58411:58411 --name xxx-grafana_0_c90d8fdc -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=xxx-grafana -e WEBSITE_AUTH_ENABLED=False -e PORT=58411 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=xxxx.azurewebsites.net -e WEBSITE_INSTANCE_ID=a52805fc68780a8334d5950553724e37277df1fff7acdaa52c954d65771aba45 xxxx.azurecr.io/xxxx-grafana:latest

I have no control over the run command that Azure provide

**What you expected to happen**:
Grafana should be allowed to be configured with process.env.PORT in a dockerfile so that the image just consumes the port that it's given 

**How to reproduce it (as minimally and precisely as possible)**:
Create a docker image and then run it in a Linux Web App with a Standard App Service plan so you can enable VNet integration.  Then activate the VNet integration and run the container

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version:
- OS Grafana is installed on: linux / Azure web app
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
I don't have that much experience with Azure and I'm not exactly sure what kind of service you're using, Azure Web App? You're the first one asking of this and sounds weird that you cannot configure either a static port or either provide additional configuration flags to docker container. 

Is [this](https://docs.microsoft.com/bs-latn-ba/azure/app-service/containers/configure-custom-container#configure-port-number) related to Azure Web App?

**Comment by danassetms** [comment]
If managed to sort this myself - the Azure WebApp VNet functionality is in beta so it passes the assigned port as an environment variable.  You can then make use of that in the grafana.ini file like this:
		
[server]
http_port = ${PORT}
		
You also need to include the variable in the dockerfile like this:

EXPOSE $PORT

**Comment by danassetms** [comment]
For reference for using Grafana within an Azure WebApp as a docker container you can use the following setup:

docker-compose.yml
/src
 - grafana.ini
 - dockerfile
 - /dashboards
 - /datasources
 - /notifiers

Docker-Compose.yml
`version: "2.1"

services:
  grafana:
    build:
        context: ./src
        dockerfile: Dockerfile `

DockerFile
`FROM grafana/grafana:latest

EXPOSE $PORT

ENV GF_INSTALL_PLUGINS "grafana-clock-panel"

COPY ./grafana.ini /etc/grafana/
COPY ./dashboards/*.* /etc/grafana/provisioning/dashboards/
COPY ./datasources/*.* /etc/grafana/provisioning/datasources/
COPY ./notifiers/*.* /etc/grafana/provisioning/notifiers/
CMD ["GF_SERVER_HTTP_PORT=$PORT /run.sh"]`

Grafana.ini
`[users]
allow_sign_up = false
	
[smtp]
enabled = true

[server]
http_port = ${PORT}`

Then you can run it locally:
 docker-compose  -f "grafana.dockercompose.yml" up   

Build it:
docker-compose  -f "grafana.dockercompose.yml" build --no-cache --force-rm --pull

And run it:
docker run -d -p 58411:58411 -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=xxxxx-grafana -e WEBSITE_AUTH_ENABLED=False -e PORT=58411 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=xxxxx-grafana.azurewebsites.net 

You can then use Azure Devops to build and push to a container registry and then use the 'Container Settings' blade in the Web-App page to select the version from the container registry.

Hope this helps someone
