### ISSUE TITLE
Ubuntu service startup status is failure

### ISSUE THREAD

**Issue by kumarnmanoj** [grafana/grafana#2032]
While starting the grafana server for the first time, the command
sudo service grafana-server start says
* Starting Grafana Server  [fail]

But while checking the logs, grafana server runs migration for the new database. After that it starts the server.

The status reflected whlie starting the server is misleading.

Grafana version - 2.0.2
OS - Ubuntu 14.04.2 LTS

**Comment by torkelo** [comment]
this is fixed in master, happened rarely on first start (if disk was slow) due to the fact that pidfile was created after SQL migration.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1990
