### ISSUE TITLE
dataframe: move backend dataframe processing into grafana/data (or something)

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#20328]
**What would you like to be added**:

Currently `gelResponseToDataFrames` is part of expressions https://github.com/grafana/grafana/blob/master/public/app/features/expressions/util.ts. Since v2 backend plugins will return the same b64 encoded arrow data frames, this needs to available to plugin developers. So I imagine this goes to `grafana/data` or runtime.

I believe Ryan mentioned there was something to figure out here with arrow and was going to talk to Dominik (iirc).

**Comment by kylebrandt** [comment]
@ryantxu Just a heads up that this is coming up again for meta-analytics - Gramytics ;-) .  So when this is solved @jongyllen will want to know.

**Comment by torkelo** [comment]
@ryantxu is it ok to just move this util function or is there another way?

**Comment by kylebrandt** [comment]
I seem to have trouble importing this. I changed my `package.json` to get `"canary"` and ran yarn install. However, with `import { resultsToDataFrames } from '@grafana/data/dataframe/arrow/ArrowDataFrame'` yarn dev returns:

```
 Compilation failed!
  ./DataSource.ts
  Module not found: Can't resolve '@grafana/data/dataframe/arrow/ArrowDataFrame' in '/home/kbrandt/go/github.com/grafana/test-datasource/src'
```

The file does seem to be there in my `node_modules`:

```
$ ll node_modules/@grafana/data/dataframe/arrow
total 4.0K
-rw-r--r-- 1 kbrandt kbrandt 367 Dec  5 07:48 ArrowDataFrame.d.ts
```

**Comment by torkelo** [comment]
@dprokop regarding importing functions/utils directly from their path (without using src dir) is not something we have solved yet (in published npm packages)

**Comment by torkelo** [comment]
do we need to do more here in v6.6 or can this be closed?

**Comment by ryantxu** [comment]
still need to find a solution.  Currently any backend plugin (metaanalytics etc) copy the code and dependencies :(

Maybe:  https://github.com/grafana/grafana/pull/21408

and/or maybe a scoped export from `@grafana/data` that can be loaded async.

The change that breaks e2e tests on phantomjs is:https://github.com/grafana/grafana/commit/1aa52f259c96ef5837e9894639a292a4a7679e59

**Comment by kylebrandt** [comment]
@ryantxu / @dprokop Was this fixed via https://github.com/grafana/grafana/pull/21408 ? The only comment that makes me unsure is " and a minor change in it means it does not work with GEL", but not sure if that is actually true by the time it was merged?

**Comment by dprokop** [comment]
Yeah, not sure neither @kylebrandt, but the apache-arrow issue described by Ryan should be gone with this PR https://github.com/grafana/grafana/pull/21677

**Comment by dprokop** [comment]
@ryantxu I think this can be closed, right?
