### ISSUE TITLE
external Database Definition with secureJsonData.basicAuthPassword dosen't work only with basicAuthPassword field what is Deprecated

### ISSUE THREAD

**Issue by schoofsc** [grafana/grafana#20324]
**What happened**:
The field "datasources.secureJsonData.basicAuthPassword" is not used for the external data source definition. The field "datasources.basicAuthPassword" works. However, this field is Deprecated. The documentation can be found at the following address https://grafana.com/docs/administration/provisioning/.

**What you expected to happen**:
The field "datasources.secureJsonData.basicAuthPassword" should be included in the database definition. If the field "datasources.basicAuthPassword" is Deprecated.

**How to reproduce it (as minimally and precisely as possible)**:
Create two external data source definitions incl. Basic authentication that access a data source with Basic authentication. For one definition use the field "datasources.secureJsonData.basicAuthPassword" for the password and for the other the field "datasources.basicAuthPassword".  Then you will see that the field "datasources.secureJsonData.basicAuthPassword" is not transferred to the data source in the interface and therefore does not work. Furthermore you can see in the log that the field "datasources.basicAuthPassword" is Deprecated.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.4.3
- Data source type & version: elasticsearch & prometheus
- OS Grafana is installed on: docker image with helm chart on K8s
- User OS & Browser: MacOs & Chrome
- Grafana plugins:   
  - grafana-piechart-panel v1.3.9
  - grafana-clock-panel v1.0.3
  - vonage-status-panel v1.0.9
- Others:

**Comment by marefr** [comment]
Please include your datasource provisioning configuration. Thanks

**Comment by schoofsc** [comment]
@marefr this is the database configuration

'datasources[datasources.yaml].datasources[0].name': prometheus with basicAuthUser (works)
'datasources[datasources.yaml].datasources[0].type': prometheus
'datasources[datasources.yaml].datasources[0].access': proxy
'datasources[datasources.yaml].datasources[0].basicAuth': true
'datasources[datasources.yaml].datasources[0].basicAuthPassword': "PROMETHEUS_PASSWORD"
'datasources[datasources.yaml].datasources[0].basicAuthUser': "prometheus"
'datasources[datasources.yaml].datasources[0].orgId': 1
'datasources[datasources.yaml].datasources[0].url': https://prometheus.schoofsc.de/
'datasources[datasources.yaml].datasources[0].isDefault': true
'datasources[datasources.yaml].datasources[0].version': 1
'datasources[datasources.yaml].datasources[0].editable': false

'datasources[datasources.yaml].datasources[1].name': prometheus with secureJsonData.basicAuthPassword
'datasources[datasources.yaml].datasources[1].type': prometheus
'datasources[datasources.yaml].datasources[1].access': proxy
'datasources[datasources.yaml].datasources[1].basicAuth': true
'datasources[datasources.yaml].datasources[1].basicAuthPassword': "PROMETHEUS_PASSWORD"
'datasources[datasources.yaml].datasources[1].secureJsonData.basicAuthUser': "prometheus"
'datasources[datasources.yaml].datasources[1].orgId': 1
'datasources[datasources.yaml].datasources[1].url': https://prometheus.schoofsc.de/
'datasources[datasources.yaml].datasources[1].isDefault': false
'datasources[datasources.yaml].datasources[1].version': 1
'datasources[datasources.yaml].datasources[1].editable': false

'datasources[datasources.yaml].datasources[2].name': Elasticsearch with basicAuthUser (works)
'datasources[datasources.yaml].datasources[2].type': elasticsearch
'datasources[datasources.yaml].datasources[2].access': proxy
'datasources[datasources.yaml].datasources[2].basicAuth': true
'datasources[datasources.yaml].datasources[2].basicAuthUser': "grafana"
'datasources[datasources.yaml].datasources[2].basicAuthPassword': "GRAFANA_ELASTICSEARCH_PASSWORD"
'datasources[datasources.yaml].datasources[2].orgId': 1
'datasources[datasources.yaml].datasources[2].url': https://elasticsearch.schoofsc.de/
'datasources[datasources.yaml].datasources[2].isDefault': false
'datasources[datasources.yaml].datasources[2].version': 1
'datasources[datasources.yaml].datasources[2].editable': false
'datasources[datasources.yaml].datasources[2].database': "testt*"
'datasources[datasources.yaml].datasources[2].jsonData.timeInterval': 1ms
'datasources[datasources.yaml].datasources[2].jsonData.esVersion': 70
'datasources[datasources.yaml].datasources[2].jsonData.timeField': "@timestamp"


'datasources[datasources.yaml].datasources[3].name': Elasticsearch with secureJsonData.basicAuthPassword
'datasources[datasources.yaml].datasources[3].type': elasticsearch
'datasources[datasources.yaml].datasources[3].access': proxy
'datasources[datasources.yaml].datasources[3].basicAuth': true
'datasources[datasources.yaml].datasources[3].basicAuthUser': "grafana"
'datasources[datasources.yaml].datasources[3].basicAuthPassword': "GRAFANA_ELASTICSEARCH_PASSWORD"
'datasources[datasources.yaml].datasources[3].orgId': 1
'datasources[datasources.yaml].datasources[3].url': https://elasticsearch.schoofsc.de/
'datasources[datasources.yaml].datasources[3].isDefault': false
'datasources[datasources.yaml].datasources[3].version': 1
'datasources[datasources.yaml].datasources[3].editable': false
'datasources[datasources.yaml].datasources[3].database': "test*"
'datasources[datasources.yaml].datasources[3].jsonData.timeInterval': 1ms
'datasources[datasources.yaml].datasources[3].jsonData.esVersion': 70
'datasources[datasources.yaml].datasources[3].jsonData.timeField': "@timestamp"

**Comment by marefr** [comment]
Would had been easier to understand if you had included the actual yaml config file. You should use `"secureJsonData.basicAuthPassword": "<pass>"`, but now you're using `"secureJsonData.basicAuthUser": "<user>"`. Closing this, let me know if I misunderstood and I'll reopen.

**Comment by prbakhsh** [comment]
I used this template:
datasources:
- name: TEST
  url: http://localhost:PORT
  user: <USER>
  secureJsonData:
    password: <PASSWORD>

**Comment by sarwank** [comment]
Need little formatting: Better to use this one below:

```
    datasources: 
    - name: cdmsMySQL
      type: mysql
      access: proxy
      url: mysql-service.cdms.svc:3306
      version: 1
      database: cdmsusers
      user: youruser
      isDefault: false
      jsonData:
        tlsSkipVerify: true
      secureJsonData:
        password: yourpassword
```
