### ISSUE TITLE
Multiples Organizations with Anonymous access

### ISSUE THREAD

**Issue by maauso** [grafana/grafana#2033]
Possibility to add multiples org in [auth.anonymous]  section, for exemple. 

org_role = Viewer
org_name = Org1, Org2

**Comment by torkelo** [comment]
A user cannot view as two orgs at the same time. Could possibly be done with organization selection in the sidebar.

**Comment by maauso** [comment]
Yes, I meant that

**Comment by torkelo** [comment]
What is the reason

**Comment by torkelo** [comment]
What is the reason for creating separate Organizations, yet have them all accessible to anyone?

**Comment by maauso** [comment]
we are using new Grafana in production, so we have 3 departaments (org), rsa, developer, dba,  we want the all company can view all dashboards, but only the owners can edit and administrate, if we have 1500 employments it's more difficult give  access to role view with user and password that we have organization with  view access without user and password.

**Comment by torkelo** [comment]
Would  dashboards grouped into folders (coupled with permission and user groups) not be more appropriate? 

Using multiple orgs like you describe does not seems not ideal as dashboard search will only cover one organization so both anonymous users and signed in users will have to switch org all the time when wanting to view a dashboard from another department. org != department :)

**Comment by maauso** [comment]
Do you mean operating system permissions? I don't find who can create folders in grafana and give permission
In this case I use mysql (for dashboards and sessions), because I have differents Grafana servers.
It's true the user can't find dashboards between ORG, but the situation is.

I have org1, they have Graphite, in this Graphite they have hardware metrics
Org2 have other Graphite with other kind of metrics.
Org1 only want that her department can modify the dashboards
Org2 only want that her department can modify the dashboards. (this is the main problem)

Also, it's necessary that Org2 can access to graphite Org1 and vice versa  (I can solve this by adding the Datasources)

Some people want see the Org1 and Org2 dashboards (Not necessarily both at the same time) , so for me it's easy if I can give anonymous access to two Org.

**Comment by rlueckl** [comment]
+1 for this feature. We have 3 organizations, each with their specific Editors and Read-Only Editor. We would like to use the anonymous user for viewing all 3 orgs. This would be great for product managers to get an overview of the whole system while the users in the 3 orgs. don't necessarily need view permissions on each others dashboards.

**Comment by shoonoise** [comment]
:+1: 

We want to have ability to allow any user view dashboards in some orgs.
I guess that simplest way to implement it is create some list of default orgs and adding each user to these orgs.

**Comment by shoonoise** [comment]
@torkelo what you think about [such](https://github.com/grafana/grafana/issues/2033#issuecomment-160929226) implementation? I can do this, if you approve my approach.

**Comment by torkelo** [comment]
I think this is best solve ödegaard with dashboard groups and group permissions

**Comment by shoonoise** [comment]
> I think this is best solved with dashboard groups and group permissions

So is it implemented yet?

**Comment by torkelo** [comment]
no not yet

**Comment by torkelo** [comment]
closed in favor of https://github.com/grafana/grafana/issues/1611 and https://github.com/grafana/grafana/issues/1128

**Comment by GowthamShanmugam** [comment]
is that possible to give multiple org as anonomous, if yes how?

**Comment by torkelo** [comment]
its not very likely we will support multiple domains at once. But not impossible if we get a really amazing contribution :)

**Comment by chicco785** [comment]
@torkelo any feedback on the above plan?
thx

**Comment by rjfv** [comment]
@torkelo the idea presented by @chicco785 seems quite good, do you have any feedback on that?

**Comment by versatildefuy** [comment]
Any news about the idea presented by @chicco785 . We find it really interesting and helpful to extend the grafana functionality.
