### ISSUE TITLE
Notifications: Support Microsoft Teams preferred webhooks format

### ISSUE THREAD

**Issue by Zhenye-Na** [grafana/grafana#20334]
Hi developing team @ grafana,

**What would you like to be added**:

Add MS Teams preferred webhooks json format.

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using

https://grafana.com/docs/alerting/notifications/#webhook

**Why is this needed**:

Because currently the json data schema for grafana webhook cannot be consumed by MS Teams directly. I cannot send test message to Teams either. One solution for our usage is to create a "middleware-like" service which first consumes grafana response and then send the json data to MS Teams. But we really look forward to integrating this feature in Grafana.

I am interested and would like to help contribute to this feature. Please consider adding this feature to our grafana product.

Thanks!

**Comment by Zhenye-Na** [comment]
Hi @torkelo , is there anything I can help contributing to this feature?

Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
