### ISSUE TITLE
Azure Monitor VM Guest Metric

### ISSUE THREAD

**Issue by jeaneduardo** [grafana/grafana#20330]
Hello

I'm trying to create graphs with the Guest OS metrics, but it doesn't return any informality.

I read in the documentation is the metric Namespace is Microsoft.compute / virtualmachines / guest, but when I add it manually it returns the following error

Detect invalid value: Microsoft.compute / virtualmachines / guest for query parameter: 'metricnamespace', the value must be: Microsoft.Compute / virtualMachines if the query parameter is provided, you can also skip this optional query parameter.

Is it possible to add Guest OS metrics?
If not possible is it in the roadmap or why?

**Comment by marefr** [comment]
I'm not sure but think last time I heard about it it wasn't supported. For reference there are an open issue here https://github.com/grafana/azure-monitor-datasource/issues/71 which was the repository of the azure monitor datasorce before azure monitor was included in core Grafana. Will try and find someoine who knows more.

**Comment by Rzpeg** [comment]
@marefr So is there a way to see guest metrics with 6.5 + without round-tripping to Log Analytics ?

**Comment by marefr** [comment]
This still doesn't seem to be supported in Azure Monitor. The only information I find is this https://docs.microsoft.com/en-us/azure/azure-monitor/insights/monitor-vm-azure#guest-operating-system. Closing this for now, but will consider reopen if Azure Monitor start supporting this and Grafana needs update to handle it.
