### ISSUE TITLE
PanelPlugin is not a constructor

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#20338]
I'm creating custom plugin. This is my module.tsx:

```ts
import { PanelPlugin } from '@grafana/ui';
import { Plugin } from './plugin';

export const plugin = new PanelPlugin(Plugin);
```

However, I'm getting 

> Error loading panel plugin: simpod-sankey-diagram-panel TypeError: _grafana_ui__WEBPACK_IMPORTED_MODULE_0__.PanelPlugin is not a constructor

It worked with Grafana 6.3, now it's not. I checked the docs and it all seems to comply 🤔 

**Environment**:
- Grafana version: 6.4
- OS Grafana is installed on: macos
- `"@grafana/toolkit": "^6.4.0-beta.2",`

**Comment by ryantxu** [comment]
I am not sure what is happening -- in 6.5 (master/beta) you should be able to import from either grafana/ui or grafana/data
```
import { PanelPlugin } from '@grafana/ui';
  OR
import { PanelPlugin } from '@grafana/data';
```

is this a plugin that was built earlier, and is now not working?  are you able to compile it against 6.4 or master?

**Comment by simPod** [comment]
Changing this helped, thanks

```diff
+ // @ts-ignore
+ import { PanelPlugin } from '@grafana/data';
- import { PanelPlugin } from '@grafana/ui';
```

But importing from `@grafana/ui` used to work properly 🤔 Also PanelPlugin export is not typed in `@grafana/data`

**Comment by ryantxu** [comment]
In 6.5+ it is moved to '@grafana/data' -- until 7.0, it will *also* be exported at runtime to panels under `@grafana/ui`.  See this semi-hack https://github.com/grafana/grafana/blob/master/public/app/features/plugins/plugin_loader.ts#L42

**Comment by ryantxu** [comment]
I'll close this -- and think it works (with back compatibility) in 6.5+  

reopen if there is something you think we can change moving forward (besides having a stable API!!!)

**Comment by WaleedNaveed** [comment]
@simPod how did you manage to run it with Grafana 6.3 ? I am working on Grafana 6.3.5 and facing issue with react plugin.

**Comment by simPod** [comment]
@WaleedNaveed sorry, I don't remember. I always use bleeding edge and Grafana 6.3 is old so I guess I have not tried.
