### ISSUE TITLE
Can't query the metrics from Azure Monitor in China

### ISSUE THREAD

**Issue by davliu82** [grafana/grafana#20343]
**What happened**:
When I created a query under a data source for Azure Monitor in Azure China, the error popped up shown in the following screen:
![image](https://user-images.githubusercontent.com/8144963/68742689-c6fc3800-062b-11ea-8ffe-5fd5ebb6cd46.png)

**What you expected to happen**:
Successfully query and show the metric results from Azure Monitor in China.

**How to reproduce it (as minimally and precisely as possible)**:
1. Registry an application in Azure China AAD. 
2. Grant the application as Monitor Contributor role to access one subscription.
3. Create a data source and input the application information to connect with Azure Monitor in China. 
4. Create a query under the data source, to query a metric of a Azure resource. 

**Anything else we need to know?**:
N/A 

**Environment**:
- Grafana version:
v6.6.0-pre 
- Data source type & version:
- OS Grafana is installed on:
Windows 2016
- User OS & Browser:
Chrome
- Grafana plugins:
Azure Monitor plugin
- Others:

**Comment by torkelo** [comment]
Think you need to raise your issue with Microsoft Azure support, as it seems to be an API level permission issue

**Comment by davliu82** [comment]
@torkelo I don’t think it is about permission. I followed the same steps for public Azure and it can work. In addition, you can see the service principal I used can read out the subscription in screen.
