### ISSUE TITLE
A boolean in a metric name breaks toggle edit mode

### ISSUE THREAD

**Issue by patkovskyi** [grafana/grafana#20349]
@itsmylife update September 20, 2022
Description: In Graphite datasource, when you have true/false as metric you cannot toggle between editor mode and visual mode.
Acceptance Criteria: Even if you have metrics with name false/true both editors should keep working. Toggling between editors should be working.
Status:
It is kind of a feature request to me. [The parser](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/parser.ts) is responsible for parsing the query. I believe on line [#71](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/parser.ts#L71) we can add `|| this.match('bool')` and it will work. But there must be some changes for the visual editor to show false/true as segments. Which is being handled here: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/state/helpers.ts#L32-L42
Also, the assignee of this task should consider the outcome of this change and also investigate why in the first place this wasn't added.

---

**What happened**:
When a segment of a metric name is a boolean `true` or `false`, toggle edit mode does not work (in the direction from unstructured to structured query). No network queries or JS errors when this happens. 
See video repro: https://www.dropbox.com/s/jndtdhfsiv9vn14/Grafana-bug.mp4?dl=0

**What you expected to happen**:
Having a boolean as part of a metric name would not affect anything.

**How to reproduce it (as minimally and precisely as possible)**:
Try to render an existing Graphite metric `metric.test.false`. Try toggling edit mode back and forth.

**Anything else we need to know?**:
Nope.

**Environment**:
- Grafana version: `v6.3.4 (a557646)`
- Data source type & version: `Graphite, included in Grafana image`
- OS Grafana is installed on: `official Docker image grafana/grafana:6.3.4`
- User OS & Browser: `MacOS 10.14.6 (18G103), Chrome Version 78.0.3904.97 (Official Build) (64-bit)`
- Grafana plugins: `grafana-piechart-panel`

**Comment by Rezanop** [comment]
Hello, 

I tried to investigate to see if I can help fixing this bug. I reached the source of the problem in the graphite's lexer:

The method that scans for identifiers also [produces Boolean literals](https://github.com/grafana/grafana/blob/6c2375e495a2987c674fa5a11ac44d99d527f275/public/app/plugins/datasource/graphite/lexer.ts#L1146) , which raises an error in the graphite's [parser](https://github.com/grafana/grafana/blob/6c2375e495a2987c674fa5a11ac44d99d527f275/public/app/plugins/datasource/graphite/parser.ts#L124) that expects a string as an identifier.

When this error get caught in the [graphite query](https://github.com/grafana/grafana/blob/6c2375e495a2987c674fa5a11ac44d99d527f275/public/app/plugins/datasource/graphite/graphite_query.ts#L48), it defaults to "textEditor = true", resulting in the behavior described.

I don't have any knowledge of graphite and its queries, so I don't know if the boolean parsing is an intended behavior and only the defaulting of 'textEditor' to true that should be changed or this needs deeper refactoring ?

**Comment by gtk-grafana** [comment]
In `graphite_query.ts` we parse the query string into an AST with `this.parseTargetRecursive(astNode, null);`, and it throws pretty nice errors (e.g. `Expected metric identifier instead found bool at position: 7`) that we format and put on the `GraphiteQuery` class. Showing these errors could be a potential resolution of this issue, as it would provide some feedback as to what the user needs to fix to get the query back into a parseable state.

I haven't found a way to expose this error prop to our react application yet, hoping that it's already available somewhere, and we just need to pipe this into the error component.

**Comment by obetomuniz** [comment]
@grafana/observability-metrics will revisit this to evaluate if the issue still is happening. Updating the priority to "good first issue" since it is a low prio.
