### ISSUE TITLE
Explore Table view: resizing broken when content is bigger than initial column width

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#20344]
**What happened**:
The table view on the Explore page goes a bit wonky when working with the column width and sorting.

**What you expected to happen**:
I expect to be able to resize the column to the custom size and the headers to adjust accordingly.
I expect the sorting to keep working.

**How to reproduce it (as minimally and precisely as possible)**:
 If the first column content is wider than the initial width, you can resize the column, this will widen the column to fit the content, it doesn't resize the header and it seems to break per-column sorting feature too.

![explore_table](https://user-images.githubusercontent.com/3349855/68749086-f09e6a80-05fd-11ea-9b6e-4985ba447f78.gif)

**Anything else we need to know?**:
Observed on Firefox and Chrome, likely a 3rd party library causing this. Tagging @davkal as he would like to look into this.

**Environment**:
- Grafana version: Grafana v6.6.0-pre (b8029dc)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (ops-tools1)
- User OS & Browser: MacOS + Firefox 70.0.1
- Grafana plugins: a bunch (ops-tools1)
- Others: Also observed on Chrome by @kylebrandt

**Comment by aocenas** [comment]
Should be fixed with new React table component.
