### ISSUE TITLE
groupByNodes query editor issues (extra comma results in broken query, fires off query before done editing)

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20345]
Grafana v6.4.4 (092e514)

See https://youtu.be/o6XfP4w8Qno

**Comment by Dieterbe** [comment]
this issue really annoys me a lot. I use groupByNodes quite frequently.
Hopefully we can this in 6.6 ! Thanks @dprokop :)

**Comment by torkelo** [comment]
Testing this in master (v6.6) this looks fixed, not by what commit. 

Can you test if this is working in v6.6 (stable tomorrow). The second param should get a default value (which you can select and change)  

Duplicate / same as https://github.com/grafana/grafana/issues/16961
