### ISSUE TITLE
How can I set minXStep=0 from grafana ?

### ISSUE THREAD

**Issue by kamalakarv** [grafana/grafana#2035]
I want to set minxstep=0 for all render api requests going from grafana. Is this possible ? if so how can I achieve this. 

minxstep:
http://graphite.readthedocs.org/en/latest/render_api.html#minxstep

Your help appreciated.

Regards
KV

**Comment by torkelo** [comment]
No, it is not possible. You can increase the maxDataPoints. But getting more data points than there are pixels in the graph do not make much sense. You can also change point consolidation by using graphite function consolidateBy. 

Also a feature like that would enable Graphite to return way to many data points and hang the browser.
