### ISSUE TITLE
No API Keys in Drop Down

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#2036]
I am logging in via Google auth. I am both an admin on the main org and a global admin. The only drop down option from "main" is Create Org, which I get a permission denied when trying to do.

![image](https://cloud.githubusercontent.com/assets/1692624/7752004/23b1b7f0-ffab-11e4-920a-70b611faf8c3.png)

```
sqlite> select * from org_user WHERE user_id = 3;
4|1|3|ADMIN|2015-03-23 19:18:11|2015-03-23 19:18:11
sqlite> select * from user WHERE id = 3;
3|0|kyle@myDomain.com|kyle@myDomain.com|SeemsSecrent||1|1|0|light|2015-03-23 19:15:45|2015-05-21 14:48:59
```

How do I generate an API key in 2.0.2? Directly insert something into the following table maybe?

```
sqlite> .schema api_key
CREATE TABLE `api_key` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `org_id` INTEGER NOT NULL
, `name` TEXT NOT NULL
, `key` TEXT NOT NULL
, `role` TEXT NOT NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
);
CREATE INDEX `IDX_api_key_org_id` ON `api_key` (`org_id`);
CREATE UNIQUE INDEX `UQE_api_key_key` ON `api_key` (`key`);
CREATE UNIQUE INDEX `UQE_api_key_org_id_name` ON `api_key` (`org_id`,`name`);
```

Thanks,
Kyle

**Comment by torkelo** [comment]
You need to be organization admin to an add api  (or other organisation users).

**Comment by torkelo** [comment]
Login with the admin specified in grafana.ini and change the organisation role for you oauth user

**Comment by kylebrandt** [comment]
@torkelo Doesn't my sqlite query show that I am an admin?

**Comment by kylebrandt** [comment]
The GUI reflects this as well:

![image](https://cloud.githubusercontent.com/assets/1692624/7753465/9e8e3bc6-ffb3-11e4-9b92-616f2671c5cf.png)

**Comment by kylebrandt** [comment]
Also get a 401 when trying to create a new org: 
```2015/05/21 16:21:56 [I] Completed /api/org/ 401 Unauthorized in 1.020647ms
2015/05/21 16:21:56 [I] Completed /api/org/ 401 Unauthorized in 767.04µs```

**Comment by kylebrandt** [comment]
Close, oh sorry I set it to ADMIN instead of Admin. Works now.
