### ISSUE TITLE
Grafana graph display time incorrectly

### ISSUE THREAD

**Issue by Zhenye-Na** [grafana/grafana#20366]
Hi

I found out that the timestamp in grafana chart (x-axis) is not the same as the timestamp I stored in InfluxDB. I stored timestamp using local time (LA time) and timezone I selected in grafana is `Default` and I think I should not change it since there are other dashboards already there.

I am wondering if I should change the timezone I used to store timestamp in InfluxDB to `UTC` or stick to `Local Time`?

Thanks!

**Comment by Zhenye-Na** [comment]
It seems I solved this by only changing the timezone of this dashboard to `UTC`. But I think I stored the timestamp in InfluxDB as local time, but in grafana I have to use `UTC` to display the time correctly. Is this a expected scenario?

**Comment by markusr** [comment]
Apart from the grafana issue. You need to store InfluxDB  values in [UTC](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary#timestamp) and not in localtime.

**Comment by Zhenye-Na** [comment]
Thanks @markusr !

problem solved! close issue now.
