### ISSUE TITLE
Prometheus Datasource not using supplied URI path

### ISSUE THREAD

**Issue by asc-adean** [grafana/grafana#20369]
**What happened**:
I can't use any dashboards utilizing the rabbitmq_exporter (https://github.com/kbudde/rabbitmq_exporter) because the Prometheus datasource doesn't appear to be using the correct endpoint, even though I am explicitly setting it:

![r1](https://user-images.githubusercontent.com/43385343/68798026-43d2e600-061b-11ea-8ba5-03ec7242db38.png)

Example of what the Query Inspector returns:
`Object
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/3/api/v1/query_range?query=rabbitmq_running%7Bnode%3D%22%22%7D&start=1573672920&end=1573672950&step=30"
response:"<html> <head><title>RabbitMQ Exporter</title></head> <body> <h1>RabbitMQ Exporter</h1> <p><a href='/metrics'>Metrics</a></p> </body> </html>"`

Which does correspond if I go to that URL via cURL if I don't add the `/metrics` in the URI path:

`<html>
             <head><title>RabbitMQ Exporter</title></head>
             <body>
             <h1>RabbitMQ Exporter</h1>
             <p><a href='/metrics'>Metrics</a></p>
             </body>
             </html>`

Adding `/metrics` to my cURL shows prometheus data.

Is this a Prometheus datasource bug/issue that it doesn't take in URI paths or should I be configuring the rabbitmq_exporter to export Prometheus at `/` rather than at `/metrics` ?

**What you expected to happen**:

Grafana returns values scraped from the rabbitmq_exporter Prometheus endpoint

**How to reproduce it (as minimally and precisely as possible)**:
Install RabbitMQ with monitoring enabled and rabbitmq_exporter scraping the API
Install Grafana and create a Prometheus datasource pointing at the rabbitmq_exporter IP:Port and /metrics endpoint (ex. http://rmq-exporter:9419/metrics)

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/6.6.2
- Data source type & version: Prometheus (whatever version comes default with)
- OS Grafana is installed on: Docker image
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
You'll need to install [Prometheus](https://prometheus.io/) and configure scrape targets in Prometheus for RabbitMQ, e.g. http://rmq-exporter:9419/metrics. Then in Grafana you configure the URLl to your Prometheus server.
