### ISSUE TITLE
Datasource: Circuit breaker support

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20362]
**What would you like to be added**:
Grafana should have circuit breaker support for data sources in the data proxy and for backend plugins.

**Why is this needed**:
1. To protect Grafana from queuing up a lot of requests due to a downstream data source experiencing problems.
1. To protect a downstream data source from damage by getting overloaded with requests from Grafana which potentially could lead to latency issues and eventually downtime. 

**Additional thoughts:**
- Needs to investigate what kind of failures to track and how/when to open/close the circuit and whether it's possible to find sane defaults for all possible datasources?
- Circuit breaker per configured data source or not?
  - If so, needs to be able to handle concurrency in a "lock-free" manner
- Circuit breaker can be manually enabled/disabled for a data source at a time as a first step to possibly lower the scope of a first iteration?
 - When Grafana runs in HA mode is there anything specific to take into consideration?
 - https://martinfowler.com/bliki/CircuitBreaker.html
 - https://medium.com/netflix-techblog/fault-tolerance-in-a-high-volume-distributed-system-91ab4faae74a

**Comment by mukteshkrmishra** [comment]
+1 to this.
