### ISSUE TITLE
Apply the minimum time interval configuration as a required factor for the calculated time interval

### ISSUE THREAD

**Issue by dewetburger430** [grafana/grafana#20370]
**What would you like to be added**:
Currently a configuration field is available to specify the minimum time interval for a InfluxDB datasource/panel. This allows the user to set control the resolution when zooming in on a graph.

The minimum time interval should also be a factor of the calculated time interval when zooming out.

**Why is this needed**:

It is possible to get situation where the calculated time interval does not have a period which is a multiple of the sampling time of the data. This can cause data that is actually smooth to look noisy.

For example:
- A datasource represents a counter that increments at a rate of 1 per second.
- The counter is sampled every 10 seconds.
- The minimum time interval is set at 10 seconds.
- The query on the data is: max(value) group by $interval

If the user zooms in on the graph, the minimum time interval of 10 seconds is applies, and the graph will show a straight line:
0___0
10__10  +10
20__20  +10
30__30  +10

If the user zooms out (3h in my case) the time interval is calculated to be 15 seconds. The graph will not show a straight line:
0___0
15__20  +20
30__30  +10
45__50  +20
60__60  +10

**Comment by torkelo** [comment]
interesting idea, think your right, this makes some sense.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
