### ISSUE TITLE
"Unable to find application file" error

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#20379]
**What happened**:
"Unable to find application file" error when I try to change query format from "Time series" to "Table"

**What you expected to happen**:
May be _soft_ warning near "Format As" field, without redirecting to error page. Something like that:
![image](https://user-images.githubusercontent.com/1700286/68849589-67f9fa00-06e3-11ea-983d-dcc180e40490.png)

This is problem, because If you already have Table widget with many queries, you can't switch their format.

**How to reproduce it (as minimally and precisely as possible)**:
Create table widget and add 2 queries (Zabbix source, if it is important).
And change "Format As"  for one of queries:
![image](https://user-images.githubusercontent.com/1700286/68848899-2452c080-06e2-11ea-8bf3-5db98fb0a0bb.png)
You will redirect to error page.
The same behavior when different format query is disabled and you make it enabled:
![image](https://user-images.githubusercontent.com/1700286/68849262-cd99b680-06e2-11ea-891a-cf2e84faa90c.png)

**Anything else we need to know?**:
Error page contains:

```
Unable to find application file
Grafana has likely been updated. Please try reloading the page.

Reload

TypeError: Cannot read property 'forEach' of undefined

    in t
    in div
    in div
    in r
    in l
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in div
    in e
    in DraggableCore
    in e
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in e
    in div
    in div
    in div
    in t
    in t
    in div
    in div
    in e
    in Connect(e)
    in Suspense
    in t
    in Unknown
    in d
    in Unknown
    in Unknown
    in t
    in t
    in a
```

**Environment**:
- Grafana version: Grafana v6.4.4 (commit: 092e514)
- Data source type & version: Zabbix latest

**Comment by torkelo** [comment]
This is fixed in 6.5 (casued by exception when mixing table and time series responses)
