### ISSUE TITLE
Link also to Ubuntu based Docker images

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#20387]
**What would you like to be added**:
Link to Ubuntu based Docker images as well as Alpine based ones on [6.5.0-beta1 download page](https://grafana.com/grafana/download/6.5.0-beta1?platform=docker).

**Why is this needed**:
We recently added Ubuntu based Docker images.

**Comment by marefr** [comment]
Think we may need to update something in grafana.com download page as well. Can you give some pointers @DanCech ?

**Comment by marefr** [comment]
Opened issue here instead https://github.com/raintank/grafana-net/issues/1041 so closing this.

**Comment by aknuds1** [comment]
> Opened issue here instead [raintank/grafana-net#1041](https://github.com/raintank/grafana-net/issues/1041) so closing this.

@marefr Thanks!
