### ISSUE TITLE
stacked results sometimes don't get displayed

### ISSUE THREAD

**Issue by imreACTmd** [grafana/grafana#2039]
I have 40 counters, showing numbers between 1 and 8, stacked, in a 15 minute period.

I have tried 2.0pre, 2.0.2, 2.1.0-pre1, and there is no rhyme or reason, but frequently the graph is missing most of the data from it. When I turn of stacked, all data shows up correctly.

Grid max is set to auto as per default.

Here is a comparison screenshot for the same graph with stacking enabled and disabled:

![stacked](https://cloud.githubusercontent.com/assets/7140037/7759702/accec2a4-ffe1-11e4-95a8-2dad6d16e04e.png)

![non-stacked](https://cloud.githubusercontent.com/assets/7140037/7759707/b051aec8-ffe1-11e4-837d-ffb53110518c.png)

**Comment by imreACTmd** [comment]
update: lines seem to be the problem. bars and points stack correctly.

**Comment by torkelo** [comment]
This issue has been reported a number of times, please search before opening a new issue  :) 
It is a common issue that many run into, its a limitation in the stack plugin to flotcharts, it requires values for each data point. So if you use graphite, you need to set "null as zero". 

If you use InfluxDB help section in the influxdb query editor "stacking & fill" that will help you with this. try fill(0) in your query, and specify a minimum group by time the group time field below your queries, like >10s  (if you sample data every 10s)

You can also review the same issue reported before
https://github.com/grafana/grafana/issues/1102, https://github.com/grafana/grafana/issues/1251, https://github.com/grafana/grafana/issues/1011, https://github.com/grafana/grafana/issues/1282, https://github.com/grafana/grafana/issues/705
https://github.com/grafana/grafana/issues/721
