### ISSUE TITLE
Explore: query duration displayed over the custom time range picker

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#20402]
**What happened**:

Look at the following screenshot. The query duration (`0.4s`) is displayed over the custom time range picker (at the bottom right of the "To" input field).

![Screen Shot 2019-11-15 at 08 30 34](https://user-images.githubusercontent.com/1701904/68925120-a692c180-0782-11ea-8acd-62d734736d1c.png)

**What you expected to happen**:

The query duration should not be displayed over the custom time range picker.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open "Explore"
2. Run query (to have the duration displayed)
3. Open the custom time range picker

**Environment**:
- Grafana version: `v6.6.0-pre (e60f7d0)`
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: OSX / Chrome 78.0.3904.97
- Grafana plugins: N/A
- Others: N/A

**Comment by ivanahuckova** [comment]
@Estrax this is probably not going to be an issue after the redesign of query row that you are working on. I couldn't find the open PR for it, but we could reference this issue there. 🙂

**Comment by aocenas** [comment]
@ivanahuckova is this still an issue or can we close it?

**Comment by ivanahuckova** [comment]
@Estrax  is this still an issue or can we close it? 🙂If it is an issue, can you link it to the PR.

**Comment by ivanahuckova** [comment]
This issue has been fixed by #20522

![image](https://user-images.githubusercontent.com/30407135/71895588-b8c12880-3151-11ea-954d-5a5d12309beb.png)

![image](https://user-images.githubusercontent.com/30407135/71895600-c1196380-3151-11ea-92af-2a6543428fa2.png)
