### ISSUE TITLE
Elasticsearch logs explore  non-English language issue

### ISSUE THREAD

**Issue by missyoyo** [grafana/grafana#20406]
**What happened**: We have some logs in elasticsearch 7.x with Chinese character，We can explore logs,but can not  calculate how many rows have that label if label name is Chinese character.

**What you expected to happen**:Please kindly refer attached screenshots

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.3.5
- Data source type & version:elasticsearch 7.4
- OS Grafana is installed on:ubuntu LTS 16.04
- User OS & Browser: Firefox 60
- Grafana plugins:
- Others:
![englosh labels work1](https://user-images.githubusercontent.com/19371588/68931081-c2ba5100-07ca-11ea-87b4-d646cf1723b7.png)
![englosh labels work2](https://user-images.githubusercontent.com/19371588/68931082-c352e780-07ca-11ea-8eb0-cb39d208118a.png)
![non-english label not work1](https://user-images.githubusercontent.com/19371588/68931083-c352e780-07ca-11ea-9da2-f916cbff66ad.png)
![non-english label not work2](https://user-images.githubusercontent.com/19371588/68931084-c3eb7e00-07ca-11ea-8490-1697249dbf6f.png)

**Comment by aocenas** [comment]
@missyoyo We did a new UI for the row details and fields so can you please check if this is still a problem and if it is reopen the issue?
