### ISSUE TITLE
Explore: Prometheus labels autocompletion conflicting with press enter to "Run query"

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#20403]
**What happened**:

This following gif shows an example, but this UX pattern hits me frequently. Generally speaking, I'm used to edit the Prometheus query in the Explore panel and press enter (while the cursor is in the middle of the query) to execute it.

A common use case is editing the label matching operator (ie. from `=` to `=~`). Whenever I do it, the labels autocompletion trigger (even if there's already a label set) and the subsequent "enter" key press triggers the autocompletion instead of the query execution.

![2019-11-15 08 47 02](https://user-images.githubusercontent.com/1701904/68925986-aa274800-0784-11ea-9208-c98c7797bc58.gif)

**What you expected to happen**:

To not trigger autocompletion while editing a label matcher if the value already exist. It's OK keeping the autocompletion while editing the label value if the cursor is not at the end of the label value.

**How to reproduce it (as minimally and precisely as possible)**:

_See attached gif_

**Environment**:
- Grafana version: both `v6.2.5 (6082d19)` and `v6.6.0-pre (e60f7d0)`
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: OSX / Chrome 78.0.3904.97
- Grafana plugins: N/A
- Others: N/A

**Comment by hugohaggmark** [comment]
Thanks for reporting this @pracucci
