### ISSUE TITLE
Unexpected error while loading subscriptions

### ISSUE THREAD

**Issue by e9169** [grafana/grafana#20414]
**What happened**:

We were having issues with azure monitor in our pre production environments while trying to setup a new datasource and we tried the latest version of grafana in docker just to make sure it wasn't our infrastructure. In Grafana we filled all the fields required to connect to Azure and whenever we try to load subscriptions we get an unexpected error message without further details. On the logs (we enabled debug level) the request is completed successfully and there are no errors.

Any idea what can be wrong? We are using exactly the same tenant id, client id, secret, etc, from an older version of Grafana (5.x).

**What you expected to happen**:
The azure monitor to load subscription information successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a new Azure Monitor datasource and try to fill the data (works well with Grafana 5.X)

**Environment**:
- Grafana version: 6.2.1
- Data source type & version: Azure Monitor 0.3
- OS Grafana is installed on: Both Docker on Kubernetes and Docker on local computer
- User OS & Browser: Linux - Firefox
- Grafana plugins: Azure Monitor
- Others:

**Comment by shavonn** [comment]
The selected cloud was being saved as an object instead of a string causing the URL to be malformed. This is fixed in 6.5 by https://github.com/grafana/grafana/pull/20183.

**Comment by sosoriov** [comment]
@shavonn I've just deployed Grafana 6.6.1 and still got issues.

![image](https://user-images.githubusercontent.com/6907952/74669462-7571c500-51a7-11ea-9366-98fc51614fac.png)

**Comment by shavonn** [comment]
@sosoriov Hey, did you try re-entering the datasource credentials? And would you mind creating another and testing to see if that works?

**Comment by sosoriov** [comment]
It works! thanks @shavonn
