### ISSUE TITLE
Dashboard using default data source breaks when default data source is changed

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2041]
When I switch the default data source to influxdb-0.8 from graphite, those dashboards using graphite (or default, I do not know what the database stores) breaks because their datasources are influxdb-0.8 now. And when I manually select their datasources back to graphite, they work again.

**Comment by torkelo** [comment]
Yepp, If panels use the default datasource and you later change the default datasource all those panels are going to use the new default datasource (no matter what type of datasource). If this is not desired you need to update the panels.
