### ISSUE TITLE
Explore UI table view only shows instance query from now

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#20412]
Prometheus UI allows us to do instance queries at a specific time; I don't think we do in Grafana Explore.  This makes it hard to use for PMs.

**Comment by torkelo** [comment]
Can't you change the time range using the time picker?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by marefr** [comment]
Oops didn't notice @lukaszgryglicki was assigned. Are you working on this one? Please remove need more details label in that case.

**Comment by Estrax** [comment]
@tomwilkie can you share more details on this one? I think the timepicker should work at this case, though I'm down to implement another options there as well.

**Comment by Estrax** [comment]
Time can be changed by the time picker, but I don't know if that's what we are looking for. cc @davkal @aocenas

**Comment by Estrax** [comment]
Time can be changed by the time picker, but I don't know if that's what we are looking for. cc @davkal @aocenas
If yes, we can close this issue.

**Comment by davkal** [comment]
Yes, if the time in the table result is the same as the To-time of the timepicker, then it works as expected and is no longer an issue.

**Comment by Estrax** [comment]
Checked it again and it really is, so closing this one.
