### ISSUE TITLE
grafana/toolkit: console.log in dev mode throws lint error

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#20425]
Hi Dominik,

I understand that console.log is not allowed in build mode but in dev mode, it's more easy use it to debug

$ yarn dev
yarn run v1.19.1
$ grafana-toolkit plugin:dev
√ Prettier check
- Linting

  ERROR: /plugin.ts[318:6]: Calls to 'console.info' are not allowed.

BR,
Arnaud

**Comment by dprokop** [comment]
Let me take a look at this tomorrow. I'm pretty sure we allow console logs in dev. Can't remember now but maybe we blacklist other console methods. I'll get back to you when I have access to my computer

**Comment by ryantxu** [comment]
Try `yarn watch` that is the most lenient on everything.

**Comment by algenty** [comment]
yep,
In watch mode, it works

**Comment by dprokop** [comment]
@algenty checked it and we are blacklisting all but `log` console methods. Since you were using `info` the problem popped out. I'm gonna put that into our backlog for fix. 

For now the suggested way is either use `console.log` only or use `dev` task in watch mode.

**Comment by evalsocket** [comment]
@dprokop Would like to work on this. Can this be assigned to me.

**Comment by wz2b** [comment]
@algenty  why are you blacklisting console.info(), console.warn(), etc.?  Just curious what's the reasoning behind this.

**Comment by tskarhed** [comment]
@evalsocket Have you done any work on this?

**Comment by evalsocket** [comment]
@tskarhed I am not working on this. You can pick it up
