### ISSUE TITLE
Cannot find dashboard.uid in Grafana v4.6.1 (commit: cac8b97) 

### ISSUE THREAD

**Issue by Zhenye-Na** [grafana/grafana#20427]
Hi,

I have followed the documentation and use the rest api call to create an new test dashboard according to the documentation and I manually changed the `uid` field in `dashboard`.

```
POST /api/dashboards/db HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer apiKey_here

{
  "dashboard": {
    "id": null,
    "uid": "testuidhere",
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
  },
  "folderId": 0,
  "overwrite": false
}
```

After that, I received a successful response:

```
{
    "slug": "production-overview",
    "status": "success",
    "version": 1
}
```

When I changed to this dashboard and have a look at the `json data`, there is no `uid` in the json. Does the grafana v4.6.1 support creating `dashboard.uid` still?

Thanks

**Comment by Zhenye-Na** [comment]
Just gave another trial with `null` in `dashboard.uid` field

```
{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "REST API Test",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
  },
  "folderId": 0,
  "overwrite": false
}
```

Still cannot find `dashboard.uid` in the json data, but according to the documentation https://grafana.com/docs/http_api/dashboard/#create-update-dashboard

> JSON Body schema:
> 
> - dashboard – The complete dashboard model, id = null to create a new dashboard.
> - dashboard.id – id = null to create a new dashboard.
> - dashboard.uid – Optional unique identifier when creating a `dashboard.uid = null` **will generate a new `uid`**.
> - folderId – The id of the folder to save the dashboard in.
> - overwrite – Set to true if you want to overwrite existing dashboard with newer version, same dashboard title in folder or same dashboard uid.
> - message - Set a commit message for the version history.


Is there anything I can do with it? The reason we want `dashboard.uid` is that we would like to utilize this [project](https://github.com/Isma399/grafana_mail) which depends on the `dashboard.uid`

```
  -D DASHBOARD, --dashboard DASHBOARD
                        Tuple of Grafana `dashboardID,dashboardName` or simply
                        the ID (autodetects dashboardName). If provided,
                        `panel_list` should just be a list string of integer
                        PanelIDs ex `1 3 4 7` (default: None)
```

**Comment by marefr** [comment]
Please upgrade. It was added in Grafana v5.0.
