### ISSUE TITLE
Show an error when different provisioning providers have the same name

### ISSUE THREAD

**Issue by gjulianm** [grafana/grafana#20421]
**What would you like to be added**: A check when loading providers for dashboard provisioners that enforces unique names, as [specified in the documentation](https://grafana.com/docs/administration/provisioning/#dashboards).

**Why is this needed**: If someone does not pay much attention to the documentation and does not see that the provisioning provider names must be unique, a weird problem can appear: some dashboards are randomly not found. They might not appear in the interface, or it might show a "dashboard not found" error.

I believe what's happening is that Grafana must be overwriting the provider settings, the paths for provisioning are overwritten too and it makes Grafana delete dashboards when it does not find them in one of the paths, and then add them again when it finds them in the other one.

I think this is very low priority as the unique provider name is documented, but it would be nice to have something in the logs that tells us we made a mistake. I'm also posting this issue in case someone has the same problem as me (for example, I stumbled upon #14929 and #16016 which can be related).

**Comment by marefr** [comment]
@gjulianm thanks. Agree this is something that should be fixed.

For anyone that's interested in working with this: Changes needed in both of these functions to validate unique name and return error:
https://github.com/grafana/grafana/blob/dfa2f3d2fbd04c5cd5e88fefbd13baaf25e566a2/pkg/services/provisioning/dashboards/types.go#L76-L116

**Comment by osokaru** [comment]
I would like to solve this issue. Thank you! 😊☕

**Comment by osokaru** [comment]
I would like to solve this issue. Thank you! 😊☕

**Comment by sakjur** [comment]
@osokaru Sounds great! 😄 You can ping me either with questions or on pull requests and I can try to get your fixes merged 🙂

**Comment by thedeveloperr** [comment]
Couldn't find a PR so wanted to ask if anyone still working on this ? Can I work on it if someone is not or have left ?
@sakjur  @osokaru

**Comment by osokaru** [comment]
Hi @thedeveloperr, yeah its assigned to me I'm planning to work on that on february. Its my first issue so I do not know if it can be more than one person working on that. Regards.

**Comment by youshy** [comment]
Hey guys, I've made a draft pull request for this issue, happy to work with someone on that!
