### ISSUE TITLE
IOPS and bytes/sec units display incorrectly

### ISSUE THREAD

**Issue by matthewsheerin** [grafana/grafana#20423]
**What happened**: I configured units of "I/O ops/sec (iops)" on one graph and "bytes/sec" on another, and saw the units display as "iops" and "Bs" respectively.

**What you expected to happen**: Units to display as "IOPS" and "B/s" respectively.

**How to reproduce it (as minimally and precisely as possible)**: Select the above units on a graph with suitable input data.

**Anything else we need to know?**: Custom units would be nice to avoid having to raise an issue for these sorts of problems.

**Environment**:
- Grafana version: v6.4.2
- Data source type & version: N/A
- OS Grafana is installed on: Centos
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment]
Definition of units is here: https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts

**Comment by brian-brazil** [comment]
More specifically https://github.com/grafana/grafana/blob/d7c76dacad0b5b867acc53d476bdb5664327e26b/packages/grafana-data/src/valueFormats/categories.ts#L148

Byte seconds is very different from bytes per second.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
