### ISSUE TITLE
Elasticsearch: Backend query auto alias handling does not respect terms ordering 

### ISSUE THREAD

**Issue by ck003** [grafana/grafana#20435]
> **What happened**:
> I test the alert rule , but I found that the order of each item in the metric is not the same..
> 
> **What you expected to happen**:
> I hope that the order of each metric is the same.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
![image](https://user-images.githubusercontent.com/19967081/69026767-41033700-0a07-11ea-9969-3d46f42c966d.png)

**Comment by hugohaggmark** [comment]
Hi @ck003 and thanks for taking the time to report this, can you give us more information about this issue so we can have a chance to repro it? The following information would be greatly appreciated:

**How to reproduce it (as minimally and precisely as possible):**

**Environment:**

Grafana version: 
Data source type & version:
OS Grafana is installed on:
User OS & Browser:
Grafana plugins:
Others:

**Comment by ck003** [comment]
Thanks very much.

> **Environment:**
> 
> Grafana version:  v5.4.3
> Data source type & version: Elasticsearch 5.x
> OS Grafana is installed on: Docker
> User OS & Browser: Win10 Chrome
> Grafana plugins:
> Others:

**Comment by torkelo** [comment]
Have you provided a query alias pattern? Can you please show the raw response from elasticsearch from your query (using query inspector)

**Comment by ck003** [comment]
@torkelo 
![image](https://user-images.githubusercontent.com/19967081/69034185-90ebf900-0a1b-11ea-96a7-967bb7c4c66f.png)
![image](https://user-images.githubusercontent.com/19967081/69034254-c1cc2e00-0a1b-11ea-8694-1ce75f095590.png)

**Comment by ck003** [comment]
@torkelo 
The order seems to be random
![image](https://user-images.githubusercontent.com/19967081/69034576-84b46b80-0a1c-11ea-975e-edb2c9036a0f.png)

**Comment by torkelo** [comment]
you can workaround the issue by specifying a manual alias pattern `{{log_json.requestClass.keyword}} .... `
for all fields in your preferred order. 

Think this is related to the backend go code not preserving the order of the terms in elastic's response.

**Comment by ck003** [comment]
@torkelo It seems work, thanks very much~~!
