### ISSUE TITLE
grafana/toolkit:  Prettier/lint performed on old version of the same file

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#20433]
Hi Ryan, Hi Dominik
With toolkit, Prettrier seems to generate a new source (some times empty) but linting are executed on old, then on the first build, no linting error.
but at the second buid, linting generates error on the file generated at the first build.

BR
Arnaud

**Comment by dprokop** [comment]
@algenty what task are you using? Is it `plugin:dev`?

**Comment by algenty** [comment]
yes dev

**Comment by ryantxu** [comment]
I have had issues when the file in vscode is not saved, then you run `plugin:dev` -- is that what happened?  or are you sure all files are saved first?

**Comment by algenty** [comment]
I think that all files are saved before build, but the error is human

**Comment by dprokop** [comment]
This should be fixed by https://github.com/grafana/grafana/pull/22278
