### ISSUE TITLE
Add 'smallint', 'boolean' and 'numeric in postgres datasource query builder when choosing column name.

### ISSUE THREAD

**Issue by techstein111** [grafana/grafana#20437]
Right now, when choosing column name in the dropdown, only 'bigint', 'integer', 'double precision', 'real' are selectable, all columns with other types are filtered out.

I see no reason to filter out 'smallint', 'boolean' (converted to 0/1) and 'numeric' data types. We are currently using 'smallint' in order to reduce data size, and 'numeric' in order to store uint64, so there is no way to create query including such columns with builder unless you type the query yourself.

**Comment by hugohaggmark** [comment]
Thanks for reporting this feature request @techstein111! We'll see if this is something we can take a look at.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by nick-bowman** [comment]
Is it possible to re-open this issue? I have made a fix that addresses this issue (after coming across the issue ourselves with not being able to use the query builder dropdown to build queries that referenced NUMERIC type columns) and would like to make a PR. I read the contributor guide and it says that all PRs must close an issue – would it be preferable to re-open this issue and have the PR address it or to create a new issue that basically duplicates this?

**Comment by nick-bowman** [comment]
I know feature requests now go through discussions – there is also an exactly related discussion here: https://github.com/grafana/grafana/discussions/37009

It even has the line of targeted code that needs to be updated (should be a one line fix).
