### ISSUE TITLE
Graph tooltip placement should not overflow top of page

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#20439]
To replicate the graph panel needs to be a bit further down (not at the top). The tooltip switches to always show it upward

<img width="449" alt="Screen Shot 2019-11-18 at 14 42 51" src="https://user-images.githubusercontent.com/10999/69057244-cd1a5c00-0a11-11ea-9a37-5c5c79447fcd.png">

**Comment by ushuz** [comment]
Dup of #14134
