### ISSUE TITLE
Allow for thresholds to be expressed with y-axis unit syntax

### ISSUE THREAD

**Issue by jbradleynh** [grafana/grafana#20432]
**What would you like to be added**:

The ability to specify a unit suffix to a threshold line based on what the unit value of the selected axis

e.g: assuming left y-axis set to use unit Data (IEC), you should be able to set a threshold line with a value of `100GiB` vs `107374182400`

**Why is this needed**:
It would improve the ability to quickly set thresholds using native unit suffixes

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/8679
