### ISSUE TITLE
grafana/toolkit : Linting *.ts files make them blank

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#20430]
Hi Domink @dprokop,

Some time, with a toolkit:dev, the ts file is emptied, since i save all ts file before to build.
 
    "@grafana/data": "^6.6.0-pre-e0a2d4beac",
    "@grafana/runtime": "^6.6.0-pre-e0a2d4beac",
    "@grafana/toolkit": "^6.6.0-pre-e0a2d4beac",

An example here, ts is empty after : 
- Linting

  ERROR: /rulesHandler.ts[41:23]: != should be !==
  ERROR: /rulesHandler.ts[17:0]: jsdoc is not formatted correctly on this line
  ERROR: /rulesHandler.ts[103:0]: jsdoc is not formatted correctly on this line
  ERROR: /rulesHandler.ts[155:0]: jsdoc is not formatted correctly on this line

  Trace: Error: 4 linting errors found in 1 files
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\@grafana\toolkit\src\cli\tasks\plugin.build.js:172:23
      at step (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:136:27)
      at Object.next (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:117:57)
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:106:16)
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\@grafana\toolkit\src\cli\tasks\plugin.build.js:139:20
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\@grafana\toolkit\src\cli\utils\useSpinner.js:17:42
      at step (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:136:27)
      at Object.next (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:117:57)
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:106:16)
      at Object.lintPlugin (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\@grafana\toolkit\src\cli\utils\useSpinner.js:7:48)
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\@grafana\toolkit\src\cli\tasks\plugin.dev.js:76:53
      at step (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:136:27)
      at Console.trace (internal/console/constructor.js:336:11)
      at D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\@grafana\toolkit\src\cli\utils\useSpinner.js:24:29
      at step (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:136:27)
      at Object.throw (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:117:57)
      at rejected (D:\Dev\workspace\grafana\plugin\grafana-flowcharting\node_modules\tslib\tslib.js:108:69)
× 4 linting errors found in 1 files
error Command failed with exit code 1.

**Comment by dprokop** [comment]
@algenty thanks for reporting this. Can you share the problematic file with us?

**Comment by algenty** [comment]
@dprokop dprokop ,
it's random, good luck !

![image](https://user-images.githubusercontent.com/47012725/69014894-14abd400-098f-11ea-8683-b3e329f405e5.png)
5 times today on different files
I have restored file and created a branch for you
https://github.com/algenty/grafana-flowcharting/tree/toolkit_emptyfile

Full output : 
✘  ~/workspace/grafana-flowcharting   0.6.0_08_typescript_5 ●  yarn dev
yarn run v1.19.1
$ grafana-toolkit plugin:dev
✔ Prettier check
✔ Linting
⠙ Bundling plugin in dev mode  Fixed: /home/arnaud/workspace/grafana-flowcharting/src/graph_class.ts
⠦ Bundling plugin in dev mode  [tsl] ERROR in /home/arnaud/workspace/grafana-flowcharting/src/flowchartHandler.ts(172,43)
        TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
    Type 'null' is not assignable to type 'string'.
  [tsl] ERROR in /home/arnaud/workspace/grafana-flowcharting/src/flowchart_class.ts(279,21)
        TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
    Type 'null' is not assignable to type 'string'.
  
   Hash: 990ca5ffbd62fe1a6eea
  Version: webpack 4.35.0
  Time: 29196ms
  Built at: 11/17/2019 10:59:02 PM
                                                       Asset       Size  Chunks                    Chunk Names
                                                     LICENSE   11.1 KiB          [emitted]         
                                                   README.md     11 KiB          [emitted]         
                                 img/agenty-flowcharting.png   1.68 KiB          [emitted]         
                                 img/agenty-flowcharting.svg   2.18 KiB          [emitted]         
                                        libs/Graph_custom.js    3.7 KiB          [emitted]         
                     libs/drawio/shapes/bpmn/mxBpmnShape2.js   19.3 KiB          [emitted]         
                               libs/drawio/shapes/er/mxER.js   50.9 KiB          [emitted]         
                         libs/drawio/shapes/ios7/mxIOS7Ui.js   48.9 KiB          [emitted]         
                libs/drawio/shapes/mockup/mxMockupButtons.js     31 KiB          [emitted]         
             libs/drawio/shapes/mockup/mxMockupContainers.js   66.8 KiB          [emitted]         
                  libs/drawio/shapes/mockup/mxMockupForms.js   73.7 KiB          [emitted]         
               libs/drawio/shapes/mockup/mxMockupGraphics.js   35.1 KiB          [emitted]         
                 libs/drawio/shapes/mockup/mxMockupMarkup.js   6.06 KiB          [emitted]         
                   libs/drawio/shapes/mockup/mxMockupMisc.js   49.2 KiB          [emitted]         
             libs/drawio/shapes/mockup/mxMockupNavigation.js   24.5 KiB          [emitted]         
                   libs/drawio/shapes/mockup/mxMockupText.js   25.8 KiB          [emitted]         
                    libs/drawio/shapes/mockup/mxMockupiOS.js    199 KiB          [emitted]         
                               libs/drawio/shapes/mxAWS3D.js    262 KiB          [emitted]  [big]  
                                libs/drawio/shapes/mxAWS4.js   10.2 KiB          [emitted]         
                             libs/drawio/shapes/mxAndroid.js   42.3 KiB          [emitted]         
                           libs/drawio/shapes/mxArchiMate.js     35 KiB          [emitted]         
                          libs/drawio/shapes/mxArchiMate3.js   84.9 KiB          [emitted]         
                              libs/drawio/shapes/mxArrows.js    122 KiB          [emitted]         
                           libs/drawio/shapes/mxAtlassian.js   7.58 KiB          [emitted]         
                               libs/drawio/shapes/mxBasic.js    160 KiB          [emitted]         
                           libs/drawio/shapes/mxBootstrap.js   27.4 KiB          [emitted]         
                            libs/drawio/shapes/mxCabinets.js   6.32 KiB          [emitted]         
                                 libs/drawio/shapes/mxDFD.js   13.9 KiB          [emitted]         
                                 libs/drawio/shapes/mxEip.js   16.2 KiB          [emitted]         
                          libs/drawio/shapes/mxElectrical.js   46.2 KiB          [emitted]         
                           libs/drawio/shapes/mxFloorplan.js   18.9 KiB          [emitted]         
                           libs/drawio/shapes/mxFlowchart.js   2.76 KiB          [emitted]         
                                libs/drawio/shapes/mxGCP2.js   16.3 KiB          [emitted]         
                                libs/drawio/shapes/mxGmdl.js   27.5 KiB          [emitted]         
                         libs/drawio/shapes/mxInfographic.js   93.9 KiB          [emitted]         
                             libs/drawio/shapes/mxLeanMap.js   77.9 KiB          [emitted]         
                            libs/drawio/shapes/mxNetworks.js   3.32 KiB          [emitted]         
                               libs/drawio/shapes/mxSysML.js   95.1 KiB          [emitted]         
                 libs/drawio/shapes/pid2/mxPidInstruments.js   19.8 KiB          [emitted]         
                        libs/drawio/shapes/pid2/mxPidMisc.js   11.4 KiB          [emitted]         
                      libs/drawio/shapes/pid2/mxPidValves.js     30 KiB          [emitted]         
                           libs/drawio/shapes/rack/mxRack.js     32 KiB          [emitted]         
                    libs/drawio/stencils/android/android.xml   61.8 KiB          [emitted]         
                             libs/drawio/stencils/arrows.xml   27.8 KiB          [emitted]         
                          libs/drawio/stencils/atlassian.xml   31.3 KiB          [emitted]         
                        libs/drawio/stencils/aws/compute.xml   23.7 KiB          [emitted]         
               libs/drawio/stencils/aws/content_delivery.xml   11.5 KiB          [emitted]         
                       libs/drawio/stencils/aws/database.xml   48.9 KiB          [emitted]         
          libs/drawio/stencils/aws/deployment_management.xml   10.6 KiB          [emitted]         
                         libs/drawio/stencils/aws/groups.xml   63.6 KiB          [emitted]         
                      libs/drawio/stencils/aws/messaging.xml     22 KiB          [emitted]         
                           libs/drawio/stencils/aws/misc.xml   9.49 KiB          [emitted]         
                     libs/drawio/stencils/aws/networking.xml   30.9 KiB          [emitted]         
           libs/drawio/stencils/aws/non_service_specific.xml   25.9 KiB          [emitted]         
            libs/drawio/stencils/aws/on_demand_workforce.xml   13.1 KiB          [emitted]         
                        libs/drawio/stencils/aws/storage.xml   12.1 KiB          [emitted]         
   libs/drawio/stencils/aws2/administration_and_security.xml   10.6 KiB          [emitted]         
                     libs/drawio/stencils/aws2/analytics.xml   46.7 KiB          [emitted]         
                  libs/drawio/stencils/aws2/app_services.xml   82.8 KiB          [emitted]         
        libs/drawio/stencils/aws2/compute_and_networking.xml    251 KiB          [emitted]  [big]  
                      libs/drawio/stencils/aws2/database.xml    277 KiB          [emitted]  [big]  
     libs/drawio/stencils/aws2/deployment_and_management.xml    116 KiB          [emitted]         
               libs/drawio/stencils/aws2/developer_tools.xml    8.7 KiB          [emitted]         
       libs/drawio/stencils/aws2/enterprise_applications.xml   8.76 KiB          [emitted]         
              libs/drawio/stencils/aws2/game_development.xml   3.51 KiB          [emitted]         
            libs/drawio/stencils/aws2/internet_of_things.xml    195 KiB          [emitted]         
              libs/drawio/stencils/aws2/management_tools.xml   6.06 KiB          [emitted]         
               libs/drawio/stencils/aws2/mobile_services.xml   38.3 KiB          [emitted]         
                    libs/drawio/stencils/aws2/networking.xml   9.55 KiB          [emitted]         
          libs/drawio/stencils/aws2/non-service_specific.xml    112 KiB          [emitted]         
           libs/drawio/stencils/aws2/on-demand_workforce.xml   34.8 KiB          [emitted]         
                          libs/drawio/stencils/aws2/sdks.xml   44.1 KiB          [emitted]         
         libs/drawio/stencils/aws2/security_and_identity.xml   22.3 KiB          [emitted]         
  libs/drawio/stencils/aws2/storage_and_content_delivery.xml    106 KiB          [emitted]         
                               libs/drawio/stencils/aws3.xml    1.4 MiB          [emitted]  [big]  
                              libs/drawio/stencils/aws3d.xml   30.9 KiB          [emitted]         
                               libs/drawio/stencils/aws4.xml      3 MiB          [emitted]  [big]  
                              libs/drawio/stencils/azure.xml    278 KiB          [emitted]  [big]  
                              libs/drawio/stencils/basic.xml   26.2 KiB          [emitted]         
                          libs/drawio/stencils/bootstrap.xml   3.79 KiB          [emitted]         
                               libs/drawio/stencils/bpmn.xml   42.6 KiB          [emitted]         
                           libs/drawio/stencils/cabinets.xml   75.1 KiB          [emitted]         
                    libs/drawio/stencils/cisco/buildings.xml     34 KiB          [emitted]         
    libs/drawio/stencils/cisco/computers_and_peripherals.xml   63.9 KiB          [emitted]         
      libs/drawio/stencils/cisco/controllers_and_modules.xml   31.7 KiB          [emitted]         
                    libs/drawio/stencils/cisco/directors.xml   14.3 KiB          [emitted]         
            libs/drawio/stencils/cisco/hubs_and_gateways.xml   20.7 KiB          [emitted]         
                         libs/drawio/stencils/cisco/misc.xml    439 KiB          [emitted]  [big]  
            libs/drawio/stencils/cisco/modems_and_phones.xml     67 KiB          [emitted]         
                       libs/drawio/stencils/cisco/people.xml     87 KiB          [emitted]         
                      libs/drawio/stencils/cisco/routers.xml     83 KiB          [emitted]         
                     libs/drawio/stencils/cisco/security.xml   24.7 KiB          [emitted]         
                      libs/drawio/stencils/cisco/servers.xml   44.4 KiB          [emitted]         
                      libs/drawio/stencils/cisco/storage.xml   49.6 KiB          [emitted]         
                     libs/drawio/stencils/cisco/switches.xml   83.2 KiB          [emitted]         
                     libs/drawio/stencils/cisco/wireless.xml   36.1 KiB          [emitted]         
            libs/drawio/stencils/cisco_safe/architecture.xml    290 KiB          [emitted]  [big]  
              libs/drawio/stencils/cisco_safe/capability.xml    552 KiB          [emitted]  [big]  
                  libs/drawio/stencils/cisco_safe/design.xml    442 KiB          [emitted]  [big]  
                  libs/drawio/stencils/cisco_safe/threat.xml    649 KiB          [emitted]  [big]  
                             libs/drawio/stencils/citrix.xml    927 KiB          [emitted]  [big]  
               libs/drawio/stencils/clipart/Gear_128x128.png   10.4 KiB          [emitted]         
                                libs/drawio/stencils/eip.xml   74.5 KiB          [emitted]         
                libs/drawio/stencils/electrical/abstract.xml     19 KiB          [emitted]         
              libs/drawio/stencils/electrical/capacitors.xml   12.1 KiB          [emitted]         
                  libs/drawio/stencils/electrical/diodes.xml   8.37 KiB          [emitted]         
      libs/drawio/stencils/electrical/electro-mechanical.xml     56 KiB          [emitted]         
                  libs/drawio/stencils/electrical/iec417.xml   32.2 KiB          [emitted]         
         libs/drawio/stencils/electrical/iec_logic_gates.xml   3.42 KiB          [emitted]         
               libs/drawio/stencils/electrical/inductors.xml   43.9 KiB          [emitted]         
             libs/drawio/stencils/electrical/instruments.xml    4.8 KiB          [emitted]         
             libs/drawio/stencils/electrical/logic_gates.xml   20.4 KiB          [emitted]         
           libs/drawio/stencils/electrical/miscellaneous.xml   56.2 KiB          [emitted]         
                libs/drawio/stencils/electrical/mosfets1.xml   20.5 KiB          [emitted]         
                libs/drawio/stencils/electrical/mosfets2.xml   14.4 KiB          [emitted]         
                 libs/drawio/stencils/electrical/op_amps.xml     11 KiB          [emitted]         
        libs/drawio/stencils/electrical/opto_electronics.xml   20.8 KiB          [emitted]         
              libs/drawio/stencils/electrical/plc_ladder.xml   3.42 KiB          [emitted]         
    libs/drawio/stencils/electrical/power_semiconductors.xml     19 KiB          [emitted]         
                   libs/drawio/stencils/electrical/radio.xml   8.19 KiB          [emitted]         
               libs/drawio/stencils/electrical/resistors.xml   19.5 KiB          [emitted]         
                libs/drawio/stencils/electrical/rot_mech.xml   10.9 KiB          [emitted]         
          libs/drawio/stencils/electrical/signal_sources.xml   13.2 KiB          [emitted]         
      libs/drawio/stencils/electrical/thermionic_devices.xml   7.93 KiB          [emitted]         
             libs/drawio/stencils/electrical/transistors.xml   14.5 KiB          [emitted]         
            libs/drawio/stencils/electrical/transmission.xml   10.8 KiB          [emitted]         
               libs/drawio/stencils/electrical/waveforms.xml   8.11 KiB          [emitted]         
                          libs/drawio/stencils/floorplan.xml     81 KiB          [emitted]         
                          libs/drawio/stencils/flowchart.xml   30.8 KiB          [emitted]         
                       libs/drawio/stencils/gcp/big_data.xml   35.8 KiB          [emitted]         
                        libs/drawio/stencils/gcp/compute.xml   33.1 KiB          [emitted]         
                libs/drawio/stencils/gcp/developer_tools.xml     15 KiB          [emitted]         
                         libs/drawio/stencils/gcp/extras.xml     38 KiB          [emitted]         
          libs/drawio/stencils/gcp/identity_and_security.xml   37.6 KiB          [emitted]         
               libs/drawio/stencils/gcp/machine_learning.xml     26 KiB          [emitted]         
               libs/drawio/stencils/gcp/management_tools.xml   31.9 KiB          [emitted]         
                     libs/drawio/stencils/gcp/networking.xml   40.5 KiB          [emitted]         
                  libs/drawio/stencils/gcp/product_cards.xml   3.85 KiB          [emitted]         
              libs/drawio/stencils/gcp/storage_databases.xml   28.2 KiB          [emitted]         
                               libs/drawio/stencils/gcp2.xml   1.08 MiB          [emitted]  [big]  
                               libs/drawio/stencils/gmdl.xml    116 KiB          [emitted]         
                         libs/drawio/stencils/ios7/icons.xml     84 KiB          [emitted]         
                          libs/drawio/stencils/ios7/misc.xml   89.2 KiB          [emitted]         
                       libs/drawio/stencils/lean_mapping.xml   13.8 KiB          [emitted]         
                 libs/drawio/stencils/mockup/advertising.xml   9.33 KiB          [emitted]         
                   libs/drawio/stencils/mockup/calendars.xml   69.6 KiB          [emitted]         
                    libs/drawio/stencils/mockup/carousel.xml   22.9 KiB          [emitted]         
           libs/drawio/stencils/mockup/charts_and_tables.xml   24.8 KiB          [emitted]         
                    libs/drawio/stencils/mockup/controls.xml   23.1 KiB          [emitted]         
               libs/drawio/stencils/mockup/form_elements.xml   15.1 KiB          [emitted]         
           libs/drawio/stencils/mockup/menus_and_buttons.xml     32 KiB          [emitted]         
                        libs/drawio/stencils/mockup/misc.xml   96.1 KiB          [emitted]         
                        libs/drawio/stencils/mockup/tabs.xml   6.76 KiB          [emitted]         
                        libs/drawio/stencils/mscae/cloud.xml    539 KiB          [emitted]  [big]  
                   libs/drawio/stencils/mscae/deprecated.xml   47.6 KiB          [emitted]         
                   libs/drawio/stencils/mscae/enterprise.xml    257 KiB          [emitted]  [big]  
                      libs/drawio/stencils/mscae/general.xml   64.3 KiB          [emitted]         
              libs/drawio/stencils/mscae/general_symbols.xml   25.6 KiB          [emitted]         
                       libs/drawio/stencils/mscae/intune.xml    187 KiB          [emitted]         
                          libs/drawio/stencils/mscae/oms.xml   64.1 KiB          [emitted]         
                   libs/drawio/stencils/mscae/opsmanager.xml    121 KiB          [emitted]         
                        libs/drawio/stencils/mscae/other.xml   65.2 KiB          [emitted]         
                libs/drawio/stencils/mscae/system_center.xml   35.3 KiB          [emitted]         
                           libs/drawio/stencils/mscae/vm.xml   90.4 KiB          [emitted]         
                           libs/drawio/stencils/networks.xml    187 KiB          [emitted]         
                      libs/drawio/stencils/office/clouds.xml   62.8 KiB          [emitted]         
              libs/drawio/stencils/office/communications.xml    396 KiB          [emitted]  [big]  
                    libs/drawio/stencils/office/concepts.xml    311 KiB          [emitted]  [big]  
                   libs/drawio/stencils/office/databases.xml   80.9 KiB          [emitted]         
                     libs/drawio/stencils/office/devices.xml    156 KiB          [emitted]         
                    libs/drawio/stencils/office/security.xml    114 KiB          [emitted]         
                     libs/drawio/stencils/office/servers.xml    405 KiB          [emitted]  [big]  
                    libs/drawio/stencils/office/services.xml    174 KiB          [emitted]         
                       libs/drawio/stencils/office/sites.xml   81.8 KiB          [emitted]         
                       libs/drawio/stencils/office/users.xml    129 KiB          [emitted]         
                      libs/drawio/stencils/pid/agitators.xml   5.77 KiB          [emitted]         
             libs/drawio/stencils/pid/apparatus_elements.xml   2.49 KiB          [emitted]         
                    libs/drawio/stencils/pid/centrifuges.xml   7.22 KiB          [emitted]         
                    libs/drawio/stencils/pid/compressors.xml   13.9 KiB          [emitted]         
                libs/drawio/stencils/pid/compressors_iso.xml    9.6 KiB          [emitted]         
              libs/drawio/stencils/pid/crushers_grinding.xml     11 KiB          [emitted]         
                         libs/drawio/stencils/pid/driers.xml   7.26 KiB          [emitted]         
                        libs/drawio/stencils/pid/engines.xml   4.87 KiB          [emitted]         
                        libs/drawio/stencils/pid/feeders.xml   3.31 KiB          [emitted]         
                        libs/drawio/stencils/pid/filters.xml   13.3 KiB          [emitted]         
                       libs/drawio/stencils/pid/fittings.xml     19 KiB          [emitted]         
                   libs/drawio/stencils/pid/flow_sensors.xml   10.7 KiB          [emitted]         
                libs/drawio/stencils/pid/heat_exchangers.xml   27.3 KiB          [emitted]         
                    libs/drawio/stencils/pid/instruments.xml   19.1 KiB          [emitted]         
                           libs/drawio/stencils/pid/misc.xml   66.1 KiB          [emitted]         
                         libs/drawio/stencils/pid/mixers.xml   3.01 KiB          [emitted]         
                         libs/drawio/stencils/pid/piping.xml   22.9 KiB          [emitted]         
                          libs/drawio/stencils/pid/pumps.xml   22.6 KiB          [emitted]         
                      libs/drawio/stencils/pid/pumps_din.xml   6.89 KiB          [emitted]         
                      libs/drawio/stencils/pid/pumps_iso.xml   6.38 KiB          [emitted]         
                     libs/drawio/stencils/pid/separators.xml   13.2 KiB          [emitted]         
               libs/drawio/stencils/pid/shaping_machines.xml   5.63 KiB          [emitted]         
                         libs/drawio/stencils/pid/valves.xml   27.4 KiB          [emitted]         
                        libs/drawio/stencils/pid/vessels.xml   60.3 KiB          [emitted]         
                           libs/drawio/stencils/rack/apc.xml   9.68 KiB          [emitted]         
                         libs/drawio/stencils/rack/cisco.xml    535 KiB          [emitted]  [big]  
                          libs/drawio/stencils/rack/dell.xml    193 KiB          [emitted]         
                            libs/drawio/stencils/rack/f5.xml    282 KiB          [emitted]  [big]  
                       libs/drawio/stencils/rack/general.xml    135 KiB          [emitted]         
                            libs/drawio/stencils/rack/hp.xml   63.4 KiB          [emitted]         
                           libs/drawio/stencils/rack/ibm.xml   80.9 KiB          [emitted]         
                        libs/drawio/stencils/rack/oracle.xml    171 KiB          [emitted]         
                      libs/drawio/stencils/signs/animals.xml   73.7 KiB          [emitted]         
                         libs/drawio/stencils/signs/food.xml     23 KiB          [emitted]         
                   libs/drawio/stencils/signs/healthcare.xml    241 KiB          [emitted]         
                       libs/drawio/stencils/signs/nature.xml   35.2 KiB          [emitted]         
                       libs/drawio/stencils/signs/people.xml   58.6 KiB          [emitted]         
                       libs/drawio/stencils/signs/safety.xml     66 KiB          [emitted]         
                      libs/drawio/stencils/signs/science.xml   18.2 KiB          [emitted]         
                       libs/drawio/stencils/signs/sports.xml    264 KiB          [emitted]  [big]  
                         libs/drawio/stencils/signs/tech.xml   50.3 KiB          [emitted]         
               libs/drawio/stencils/signs/transportation.xml    262 KiB          [emitted]  [big]  
                       libs/drawio/stencils/signs/travel.xml    132 KiB          [emitted]         
                            libs/drawio/stencils/sitemap.xml    187 KiB          [emitted]         
                           libs/drawio/stencils/veeam/2d.xml    510 KiB          [emitted]  [big]  
                           libs/drawio/stencils/veeam/3d.xml    438 KiB          [emitted]  [big]  
                        libs/drawio/stencils/veeam/veeam.xml    567 KiB          [emitted]  [big]  
                                libs/drawio/stencils/vvd.xml    633 KiB          [emitted]  [big]  
                           libs/drawio/stencils/webicons.xml    832 KiB          [emitted]  [big]  
                           libs/drawio/stencils/weblogos.xml    664 KiB          [emitted]  [big]  
                 libs/mxgraph/javascript/dist/css/common.css   4.32 KiB          [emitted]         
               libs/mxgraph/javascript/dist/css/explorer.css  495 bytes          [emitted]         
                libs/mxgraph/javascript/dist/images/grid.gif   64 bytes          [emitted]         
             libs/mxgraph/javascript/dist/images/warning.gif  276 bytes          [emitted]         
            libs/mxgraph/javascript/dist/resources/graph.txt  340 bytes          [emitted]         
             libs/mxgraph/javascript/dist/styles/default.xml   3.29 KiB          [emitted]         
                                       libs/sanitizer.min.js   47.9 KiB          [emitted]         
                                          libs/shapes.min.js   1.13 MiB          [emitted]  [big]  
                                        libs/stencils.min.js   4.93 MiB          [emitted]  [big]  
                                          libs/viewer.min.js   1.69 MiB          [emitted]  [big]  
                                                   module.js   2.74 MiB  module  [emitted]  [big]  module
                                               module.js.map   3.51 MiB  module  [emitted]         module
                             partials/flowchart_options.html   11.2 KiB          [emitted]         
                               partials/inspect_options.html   7.58 KiB          [emitted]         
                               partials/mapping_options.html   42.2 KiB          [emitted]         
                                        partials/module.html   1.07 KiB          [emitted]         
                                                 plugin.json   1.18 KiB          [emitted]         
  Entrypoint module [big] = module.js module.js.map
  [./flowchartHandler.ts] 20.2 KiB {module} [built] [1 error]
  [./flowchart_class.ts] 14.1 KiB {module} [built] [1 error]
  [./flowchart_ctrl.js] 9.17 KiB {module} [built]
  [./flowchart_options.js] 2.4 KiB {module} [built]
  [./inspect_options.js] 3.64 KiB {module} [built]
  [./mapping_options.js] 7.39 KiB {module} [built]
  [./module.js] 302 bytes {module} [built]
  [./plugin.json] 1.18 KiB {module} [built]
  [./plugin.ts] 7.25 KiB {module} [built]
  [./rule_class.ts] 26.7 KiB {module} [built]
  [./rulesHandler.ts] 4.38 KiB {module} [built]
  [./utils.js] 6.71 KiB {module} [built]
  [grafana/app/core/time_series2] external "app/core/time_series2" 42 bytes {module} [built]
  [grafana/app/core/utils/kbn] external "app/core/utils/kbn" 42 bytes {module} [built]
  [grafana/app/plugins/sdk] external "app/plugins/sdk" 42 bytes {module} [built]
      + 39 hidden modules
  
  ERROR in /home/arnaud/workspace/grafana-flowcharting/src/flowchartHandler.ts
  ./flowchartHandler.ts
  [tsl] ERROR in /home/arnaud/workspace/grafana-flowcharting/src/flowchartHandler.ts(172,43)
        TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
    Type 'null' is not assignable to type 'string'.
  
  ERROR in /home/arnaud/workspace/grafana-flowcharting/src/flowchart_class.ts
  ./flowchart_class.ts
  [tsl] ERROR in /home/arnaud/workspace/grafana-flowcharting/src/flowchart_class.ts(279,21)
        TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
    Type 'null' is not assignable to type 'string'. 
  
  Trace: Build failed
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:108:69)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
✖ Build failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ✘  ~/workspace/grafana-flowcharting   0.6.0_08_typescript_5 ●  yarn dev
yarn run v1.19.1
$ grafana-toolkit plugin:dev
✔ Prettier check
⠋ Linting  
  
  ERROR: /graph_class.ts[925:27]: == should be ===
  ERROR: /graph_class.ts[965:48]: == should be ===
  
  
  Trace: Error: 2 linting errors found in 1 files
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:172:23
      at step (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:136:27)
      at Object.next (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:117:57)
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:106:16)
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:139:20
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:17:42
      at step (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:136:27)
      at Object.next (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:117:57)
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:106:16)
      at Object.lintPlugin (/home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:7:48)
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/tasks/plugin.dev.js:76:53
      at step (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:136:27)
      at /home/arnaud/workspace/grafana-flowcharting/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/arnaud/workspace/grafana-flowcharting/node_modules/tslib/tslib.js:108:69)
      at <anonymous>
✖ 2 linting errors found in 1 files
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ✘  ~/workspace/grafana-flowcharting   0.6.0_08_typescript_5 ● 

**Comment by algenty** [comment]
J'ai l'impression when 2 files are modified, prettier empties one.
again 3 times today but i save before build :) now
