### ISSUE TITLE
Graph data points are not plotted in correct vertical position

### ISSUE THREAD

**Issue by magnublo** [grafana/grafana#20452]
**What happened**:
Time series data points in line graph are not plotted with vertical position proportional to their value.

**What you expected to happen**:
Data points should have a vertical position that is proportional to their value.

**How to reproduce it (as minimally and precisely as possible)**:
Encountered this behavior when plotting time series from my MySQL database. Can be reproduced by rendering a panel from the JSON below. Can also visit my ready-made snapshot. https://admin.darknet.graphics/dashboard/snapshot/xbb4JOEqSYulIjuphCAov85rJvhqBB6t?orgId=0

`{
  "datasource": "MySQL-AWS-slave",
  "aliasColors": {},
  "bars": false,
  "cacheTimeout": null,
  "dashLength": 10,
  "dashes": false,
  "description": "Data gathered from  reviews published on darknet marketplaces.",
  "fill": 0,
  "fillGradient": 0,
  "gridPos": {
    "h": 20,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "hideTimeOverride": true,
  "id": 40,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": true,
    "values": true
  },
  "lines": true,
  "linewidth": 6,
  "links": [],
  "nullPointMode": "null",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pluginVersion": "6.4.4",
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "snapshotData": [
    {
      "fields": [
        {
          "config": {},
          "name": "Empire market heroin revenue",
          "type": "number",
          "values": [
            637.5,
            1912.5,
            4250,
            637.5,
            4250,
            637.5,
            1050,
            1275,
            637.5,
            2885,
            3612.5,
            7225,
            2885,
            1687.5,
            2247.5,
            1050,
            637.5,
            637.5,
            2975,
            1912.5,
            637.5,
            637.5,
            637.5,
            637.5,
            1687.5,
            637.5,
            3093,
            637.5,
            3935,
            1687.5,
            2325,
            3225,
            690,
            666.6799850463867,
            2484.5599365234375,
            26016.040042877197,
            79013.95006370544,
            140434.26031303406,
            237830.46000289917,
            404484.0898399353,
            546010.0999517441,
            496375.8519477844,
            736717.4716172218,
            695902.0093345642,
            701542.6686406136,
            737262.4783437252,
            884521.0291936398,
            778898.8113508224,
            799722.4000635147,
            708112.8516101837,
            901947.6300077438,
            915970.4072189331,
            890073.4289016724,
            1043095.8690242767,
            1116523.8618774414,
            1142153.5085420609,
            1240858.3385515213,
            1235964.6708641052,
            1399859.1306438446,
            1428461.731716156,
            1477813.3598279953,
            1696811.508113861,
            1863969.169845581,
            1874143.4376029968,
            1907940.50096035,
            1856168.6513786316,
            1690053.9031600952,
            1775781.0502843857,
            872554.3806619644
          ]
        },
        {
          "config": {
            "unit": "dateTimeAsIso"
          },
          "name": "Time",
          "type": "time",
          "values": [
            1524096000000,
            1525910400000,
            1527120000000,
            1527724800000,
            1528329600000,
            1528934400000,
            1529539200000,
            1530748800000,
            1531353600000,
            1531958400000,
            1532563200000,
            1533168000000,
            1533772800000,
            1534377600000,
            1534982400000,
            1536192000000,
            1536796800000,
            1538006400000,
            1538611200000,
            1542240000000,
            1542844800000,
            1543449600000,
            1544659200000,
            1545264000000,
            1546473600000,
            1547683200000,
            1548288000000,
            1548892800000,
            1549497600000,
            1550102400000,
            1550707200000,
            1551312000000,
            1551916800000,
            1552521600000,
            1553126400000,
            1553731200000,
            1554336000000,
            1554940800000,
            1555545600000,
            1556150400000,
            1556755200000,
            1557360000000,
            1557964800000,
            1558569600000,
            1559174400000,
            1559779200000,
            1560384000000,
            1560988800000,
            1561593600000,
            1562198400000,
            1562803200000,
            1563408000000,
            1564012800000,
            1564617600000,
            1565222400000,
            1565827200000,
            1566432000000,
            1567036800000,
            1567641600000,
            1568246400000,
            1568851200000,
            1569456000000,
            1570060800000,
            1570665600000,
            1571270400000,
            1571875200000,
            1572480000000,
            1573084800000,
            1573689600000
          ]
        }
      ],
      "meta": {
        "rowCount": 0,
        "sql": "SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price) as \"Empire market heroin revenue\" FROM feedback\nLEFT JOIN listing_observation ON feedback.product_url = listing_observation.url\nLEFT JOIN listing_observation_category ON listing_observation.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 1\nAND feedback.market = \"EMPIRE_MARKET\"\nGROUP BY time\nORDER BY time ASC;"
      },
      "name": "Empire market heroin revenue",
      "refId": "A"
    },
    {
      "fields": [
        {
          "config": {},
          "name": "Empire market cannabis",
          "type": "number",
          "values": [
            1148.0399780273438,
            1156.3199615478516,
            12.059999942779541,
            2579.2799377441406,
            4870.320068359375,
            12.059999942779541,
            10536,
            7763.419954776764,
            9480.559997558594,
            4847.599914550781,
            21197.999954223633,
            13192.800003051758,
            7833.620025634766,
            31728.28018951416,
            43632.15995788574,
            29722.400100708008,
            31613.560009002686,
            21144.68002319336,
            8946.500015258789,
            20813.119997024536,
            21117.150062561035,
            25553.969955444336,
            14527.47999382019,
            10831.559997558594,
            26643.32000732422,
            20744.780029296875,
            13047.720016479492,
            24860.14989089966,
            29557,
            9875.019973754883,
            16314.239990234375,
            43329.799587249756,
            27939.320011138916,
            35660.90015411377,
            32045.759719848633,
            17169.45004272461,
            19520.600025177002,
            33284.43998336792,
            18167.459884643555,
            32041.5,
            29260.74001789093,
            53602.459968566895,
            32530.230220794678,
            18640.789903640747,
            27168.509922027588,
            65385.16979598999,
            46956.77967834473,
            75020.34003829956,
            55147.66015625,
            56965.12001800537,
            63074.09998703003,
            123203.17930603027,
            398121.6299753189,
            685709.160777092,
            566677.6202228069,
            1848062.2509741783,
            1846614.2398576736,
            2588932.445256412,
            4744920.845057249,
            4947628.846001148,
            6338160.168472648,
            6410277.153577201,
            6746437.96508614,
            6015087.4498541355,
            5718176.798365116,
            5766301.230035327,
            7250598.336406488,
            8388689.14273493,
            7798220.762090683,
            10471173.024626017,
            10720943.981916904,
            11782412.138229728,
            9943273.755694032,
            11779863.954603653,
            11365905.675862951,
            13347187.154372022,
            13237879.117810486,
            12555154.97709303,
            12348777.198027166,
            12095184.075720957,
            12321587.079969293,
            12653446.916960828,
            11723276.92963331,
            11670124.982123777,
            6824641.389764696
          ]
        },
        {
          "config": {
            "unit": "dateTimeAsIso"
          },
          "name": "Time",
          "type": "time",
          "values": [
            1521072000000,
            1521676800000,
            1522886400000,
            1523491200000,
            1525305600000,
            1525910400000,
            1526515200000,
            1527120000000,
            1527724800000,
            1528329600000,
            1528934400000,
            1529539200000,
            1530144000000,
            1530748800000,
            1531353600000,
            1531958400000,
            1532563200000,
            1533168000000,
            1533772800000,
            1534377600000,
            1534982400000,
            1535587200000,
            1536192000000,
            1536796800000,
            1537401600000,
            1538006400000,
            1538611200000,
            1539216000000,
            1539820800000,
            1540425600000,
            1541030400000,
            1541635200000,
            1542240000000,
            1542844800000,
            1543449600000,
            1544054400000,
            1544659200000,
            1545264000000,
            1545868800000,
            1546473600000,
            1547078400000,
            1547683200000,
            1548288000000,
            1548892800000,
            1549497600000,
            1550102400000,
            1550707200000,
            1551312000000,
            1551916800000,
            1552521600000,
            1553126400000,
            1553731200000,
            1554336000000,
            1554940800000,
            1555545600000,
            1556150400000,
            1556755200000,
            1557360000000,
            1557964800000,
            1558569600000,
            1559174400000,
            1559779200000,
            1560384000000,
            1560988800000,
            1561593600000,
            1562198400000,
            1562803200000,
            1563408000000,
            1564012800000,
            1564617600000,
            1565222400000,
            1565827200000,
            1566432000000,
            1567036800000,
            1567641600000,
            1568246400000,
            1568851200000,
            1569456000000,
            1570060800000,
            1570665600000,
            1571270400000,
            1571875200000,
            1572480000000,
            1573084800000,
            1573689600000
          ]
        }
      ],
      "meta": {
        "rowCount": 0,
        "sql": "SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price) as \"Empire market cannabis\" FROM feedback\nLEFT JOIN listing_observation ON feedback.product_url = listing_observation.url\nLEFT JOIN listing_observation_category ON listing_observation.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 2\nAND feedback.market = \"EMPIRE_MARKET\"\nGROUP BY time\nORDER BY time ASC;"
      },
      "name": "Empire market cannabis",
      "refId": "B"
    },
    {
      "fields": [
        {
          "config": {},
          "name": "Cryptonia heroin revenue",
          "type": "number",
          "values": [
            16592.805573523106,
            45296.432843145536,
            61839.46288179895,
            61735.995893409905,
            39286.99321061868,
            86294.19110951682,
            1392.1722891452673,
            40910.215285931736,
            56897.38206235615,
            131012.40879699211,
            88618.80644538719,
            137629.91056828236,
            134686.60619484913,
            113967.38377716552,
            135668.2344278482,
            161158.79726343218,
            241043.73205402633,
            138813.63516385126,
            168409.59821277298,
            214431.00652490393,
            253508.65565816904,
            238376.92007311256,
            189061.01073733476,
            197606.71045539647,
            215089.6890341694,
            356153.6961479015,
            256695.71733609523,
            351259.4870302234,
            366678.9515679038,
            545817.3620990237,
            153286.18577381616
          ]
        },
        {
          "config": {
            "unit": "dateTimeAsIso"
          },
          "name": "Time",
          "type": "time",
          "values": [
            1555545600000,
            1556150400000,
            1556755200000,
            1557360000000,
            1557964800000,
            1558569600000,
            1559174400000,
            1559779200000,
            1560384000000,
            1560988800000,
            1561593600000,
            1562198400000,
            1562803200000,
            1563408000000,
            1564012800000,
            1564617600000,
            1565222400000,
            1565827200000,
            1566432000000,
            1567036800000,
            1567641600000,
            1568246400000,
            1568851200000,
            1569456000000,
            1570060800000,
            1570665600000,
            1571270400000,
            1571875200000,
            1572480000000,
            1573084800000,
            1573689600000
          ]
        }
      ],
      "meta": {
        "rowCount": 0,
        "sql": "SELECT time, SUM(revenue) as \"Cryptonia heroin revenue\" FROM ((\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM btc_usd WHERE btc_usd.`timestamp` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 1\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"BTC\"\nGROUP BY time\n)\nUNION ALL \n(\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM xmr_usd WHERE xmr_usd.`Date` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 1\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"XMR\"\nGROUP BY time\n)) as agg\nGROUP BY time\nORDER BY time ASC;"
      },
      "name": "Cryptonia heroin revenue",
      "refId": "C"
    },
    {
      "fields": [
        {
          "config": {},
          "name": "Cryptonia cannabis revenue",
          "type": "number",
          "values": [
            2365.081970370953,
            7292.8740664687475,
            17471.691763875453,
            109399.5377373476,
            108340.32371570411,
            49778.42980214397,
            119440.49495542495,
            197859.32260873835,
            376276.08815866447,
            1986986.933092012,
            462178.5835441503,
            492043.45569344185,
            393737.2627155287,
            532398.0134720415,
            529764.2645036605,
            686609.187883043,
            886899.9407513601,
            1008924.3437482865,
            1352848.6246830937,
            1005773.7511573108,
            1150555.5981014618,
            1340712.3002365609,
            1321680.851629994,
            1869129.2291589417,
            1527286.0903455003,
            1669347.9582023893,
            1659603.2600644156,
            1305378.7349989081,
            1891087.6497784376,
            2388156.2000354095,
            3010620.6329210144,
            3042395.333229553,
            1568723.6867144979
          ]
        },
        {
          "config": {
            "unit": "dateTimeAsIso"
          },
          "name": "Time",
          "type": "time",
          "values": [
            1554336000000,
            1554940800000,
            1555545600000,
            1556150400000,
            1556755200000,
            1557360000000,
            1557964800000,
            1558569600000,
            1559174400000,
            1559779200000,
            1560384000000,
            1560988800000,
            1561593600000,
            1562198400000,
            1562803200000,
            1563408000000,
            1564012800000,
            1564617600000,
            1565222400000,
            1565827200000,
            1566432000000,
            1567036800000,
            1567641600000,
            1568246400000,
            1568851200000,
            1569456000000,
            1570060800000,
            1570665600000,
            1571270400000,
            1571875200000,
            1572480000000,
            1573084800000,
            1573689600000
          ]
        }
      ],
      "meta": {
        "rowCount": 0,
        "sql": "SELECT time, SUM(revenue) as \"Cryptonia cannabis revenue\" FROM ((\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM btc_usd WHERE btc_usd.`timestamp` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 2\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"BTC\"\nGROUP BY time\n)\nUNION ALL \n(\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM xmr_usd WHERE xmr_usd.`Date` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 2\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"XMR\"\nGROUP BY time\n)) as agg\nGROUP BY time\nORDER BY time ASC;"
      },
      "name": "Cryptonia cannabis revenue",
      "refId": "D"
    }
  ],
  "spaceLength": 10,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "format": "time_series",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price) as \"Empire market heroin revenue\" FROM feedback\nLEFT JOIN listing_observation ON feedback.product_url = listing_observation.url\nLEFT JOIN listing_observation_category ON listing_observation.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 1\nAND feedback.market = \"EMPIRE_MARKET\"\nGROUP BY time\nORDER BY time ASC;",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "bulk_price",
      "timeColumn": "created_date",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "format": "time_series",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price) as \"Empire market cannabis\" FROM feedback\nLEFT JOIN listing_observation ON feedback.product_url = listing_observation.url\nLEFT JOIN listing_observation_category ON listing_observation.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 2\nAND feedback.market = \"EMPIRE_MARKET\"\nGROUP BY time\nORDER BY time ASC;",
      "refId": "B",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "bulk_price",
      "timeColumn": "created_date",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "format": "time_series",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT time, SUM(revenue) as \"Cryptonia heroin revenue\" FROM ((\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM btc_usd WHERE btc_usd.`timestamp` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 1\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"BTC\"\nGROUP BY time\n)\nUNION ALL \n(\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM xmr_usd WHERE xmr_usd.`Date` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 1\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"XMR\"\nGROUP BY time\n)) as agg\nGROUP BY time\nORDER BY time ASC;",
      "refId": "C",
      "select": [
        [
          {
            "params": [
              "Volume"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "btc_usd",
      "timeColumn": "Date",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "format": "time_series",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT time, SUM(revenue) as \"Cryptonia cannabis revenue\" FROM ((\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM btc_usd WHERE btc_usd.`timestamp` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 2\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"BTC\"\nGROUP BY time\n)\nUNION ALL \n(\nSELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600*7))\n                      * (24*3600*7)) AS time, SUM(feedback.price * (SELECT `close` FROM xmr_usd WHERE xmr_usd.`Date` = FLOOR(UNIX_TIMESTAMP(feedback.date_published) / (24*3600)) * (24*3600))) as revenue FROM feedback\nLEFT JOIN (SELECT title, seller_id, l.id FROM listing_observation as l LEFT JOIN seller ON l.seller_id = seller.id) as l_s ON feedback.product_title = l_s.title AND feedback.seller_id = l_s.seller_id\nLEFT JOIN listing_observation_category ON l_s.id = listing_observation_category.listing_observation_id\nLEFT JOIN listing_category ON listing_observation_category.category_id = listing_category.id\nLEFT JOIN real_category_listing_category ON listing_category.id = real_category_listing_category.listing_category_id\nLEFT JOIN real_category ON real_category_listing_category.real_category_id = real_category.id\nWHERE real_category.id = 2\nAND feedback.market = \"CRYPTONIA_MARKET\"\nAND feedback.currency = \"XMR\"\nGROUP BY time\n)) as agg\nGROUP BY time\nORDER BY time ASC;",
      "refId": "D",
      "select": [
        [
          {
            "params": [
              "Volume"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "btc_usd",
      "timeColumn": "Date",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ],
  "thresholds": [],
  "timeFrom": "1y",
  "timeRegions": [],
  "timeShift": "12d",
  "title": "Combined lower bound on drug revenue across Empire Market and Cryptonia Market",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "transparent": true,
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": "USD",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "decimals": null,
      "format": "short",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}`

**Anything else we need to know?**:

**Environment**:
- Grafana version: Version 6.4.4 (commit: 092e514, branch: HEAD)
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04, Google Chrome 77.0.3865.90

**Comment by hugohaggmark** [comment]
Hi @magnublo and thanks for reporting this. Before digging deeper into this issue I would like to understand more about the problem. Could you explain in more detail which values are not printed proportionally and maybe give examples what you expect them to be instead?

**Comment by magnublo** [comment]
Take for example the '2019-07-04 02:00:00' date on the horizontal axis in my snapshot. The 'Cryptonia heroin revenue' series has a numerical value of 138k at that point (value when I hover my mouse over), but it has a vertical position on the graph that would indicate a value of ~6.5 million. Three of the series seem wrong, while one is correct.

![image](https://user-images.githubusercontent.com/17289903/69181116-d1786f00-0b0e-11ea-9a9c-4400b0862be8.png)

**Comment by hugohaggmark** [comment]
@torkelo any ideas?

**Comment by torkelo** [comment]
What does the graph look like if you disable stacking? (Or enable more y axis decimals) 

Are you ordering data points in asc order? Could be caused by stacking with datapoints out of order maybe?

**Comment by magnublo** [comment]
> What does the graph look like if you disable stacking? (Or enable more y axis decimals)
> 
> Are you ordering data points in asc order? Could be caused by stacking with datapoints out of order maybe?

The graph was stacked, and that was why it did not plot the way I expected it to. Sorry for wasting your time with support-like tickets like this.
