### ISSUE TITLE
HTTP 403 error while accessing various parts of docs

### ISSUE THREAD

**Issue by greenstatic** [grafana/grafana#20454]
I don't know if this is the right place to report this, but here goes.

**What happened**:
While accessing various parts of the [docs](https://grafana.com/docs/) I get a 403 for certain pages:
- [Auth/GitHub](https://grafana.com/docs/auth/github/)
- [Auth/LDAP](https://grafana.com/docs/auth/enhanced_ldap/)

but not for [Auth/Generic Oauth](https://grafana.com/docs/auth/generic-oauth/).

The response in the body is:
```
    Code: AllAccessDisabled
    Message: All access to this object has been disabled
    RequestId: F4C8817FA0224BBB
    HostId: <// REDACTED //>
```

Seems to me like a miss configured web server / object storage.

**Comment by whg517** [comment]
My guess is that the URL path is officially adjusted.

Yesterday I googled the document and it was still accessible. But some of the pages are not accessible today.

And given website home page document links 'Lear '= >' Documentation ', click on the URL for ` https://grafana.com/docs `, jump after the current can access the address should be correct in a slash ` https://grafana.com/docs/ ` after it.

In the left navigation bar of the document page, the first-level navigation is basically accessible, the second-level navigation is accessible, and the third-level navigation is mostly inaccessible.

Hope to adjust as soon as possible, the document as the first guide, or very important.

thank you

**Comment by Willis0826** [comment]
Temporarily, I go to `docs` folder to get what I want as a workaround.

Ex. CloudWatch datasource document is here
https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/cloudwatch.md

**Comment by hugohaggmark** [comment]
Thanks @greenstatic for reporting this, we're aware of this and working on it. I'll let you know more when I get info.
