### ISSUE TITLE
Grafana toolkit invalid command

### ISSUE THREAD

**Issue by SimonChaumet** [grafana/grafana#20465]
**What happened**:
After installation of all the required elements, when running 'yarn start' I get an error from Grafana toolkit :
`D:\projects\go\src\github.com\grafana\grafana>yarn start
yarn run v1.19.1
$ grafana-toolkit core:start --watchTheme
Invalid command: core:start
See --help for a list of available commands.
error Command failed with exit code 1.`

**What you expected to happen**:
The server start normally.

**How to reproduce it (as minimally and precisely as possible)**:
Installed go 1.12.5 on windows
Installed node 10.17.0
Installed python 2.7
Run all the setup commands from readme (go setup and build)
Run yarn start (I tried with npm too)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser: Windows
- Grafana plugins: none
- Others:

**Comment by hugohaggmark** [comment]
Thanks for finding this @SimonChaumet, we'll have a look at it.

**Comment by hugohaggmark** [comment]
@SimonChaumet have you installed `grafana-toolkit` globally?

**Comment by SimonChaumet** [comment]
@hugohaggmark I tried after seeing it on npm but I saw that the version on npm is not the right one so I uninstalled it.

**Comment by hugohaggmark** [comment]
@SimonChaumet I've tried your description on a completely clean Windows 10 virtual image and I can't seem to repro this issue. Could you try to refetch the source code?

**Comment by SimonChaumet** [comment]
@hugohaggmark With go get ?

**Comment by hugohaggmark** [comment]
> @hugohaggmark With go get ?

If you could just to try it out, temporarily change your GOPATH and do another `go get` to a clean folder. Maybe the `D:\projects\go\src\github.com\grafana\grafana` has some limited rights?

**Comment by SimonChaumet** [comment]
After investigation I found that since I imported the source code from another git without "go get", the "go installation" was missing. I think the problme was due to that.
