### ISSUE TITLE
Add a y-axis transform

### ISSUE THREAD

**Issue by jregovic** [grafana/grafana#2046]
it would be nice to be able to apply a y-axis transform to data points, to convert a decimal to a percent, or normalize data. If I collect CPU load via SNMP, that number is reported as the real value * 100. I'd like to be able to divide the datapoint by 100 to display the true value.

**Comment by torkelo** [comment]
cant you do that with your datastore? Graphite and InfluxDB can do value transformations

**Comment by jregovic** [comment]
It just seems like it would be convenient to be able to use a single paradigm to apply functions across different data stores. Assuming that a datastore has a given function available is a bit of a folly. Ultimately, I'd love to use Grafana for visualization and just let my datastore hold the data.

**Comment by torkelo** [comment]
@jregovic I kind of agree with your. In time grafana will get more features like metric transformations and functions like graphites. But in the mean time I think pushing some responsibility to the time series store is appropriate to share the development burden.

**Comment by isj4** [comment]
I have a similar situation. I have datapoints with temperatures in celsius. And some users want that shown in fahrenheit. I'm using OpenTSDB which cannot do transformation on its own, so the only option I have is to write the datapoints both as celsius and fahrenheit, doubling the data size. Similar issue with watts which some users may want shown as kilowatts.

I can imagine other trivial transformations:
  - fahrenheit to celsius
  - millibars to inches (air pressure)
  - millimeter to liter/m^2 and vice versa (rainfall)

I'm already normalizing the data I write to OpenTSDB into sane SI units, but the units some users are familiar with can be different.
