### ISSUE TITLE
Syntax error：  q.Interval.Milliseconds undefined

### ISSUE THREAD

**Issue by lhh-hub** [grafana/grafana#20462]
Build the local grafana environment in the secondary development, execute go run build.go setup, and then report an error.
(https://user-images.githubusercontent.com/49900972/69131906-fad4d300-0aed-11ea-97c3-c185a5f6a711.png)
Please！

**Comment by hugohaggmark** [comment]
Thanks @lhh-hub, we'll have a look.

**Comment by aknuds1** [comment]
Which version of Go are you building Grafana with? We require version 1.13.

**Comment by lhh-hub** [comment]
> Which version of Go are you building Grafana with? We require version 1.13.

I'm using 1.12.5 now. I'll try 1.13. Thank you

**Comment by aknuds1** [comment]
Great, please let us know if that solves your problem.

**Comment by seanlaff** [comment]
Had this issue on 1.12 as well, moving to 1.13 fixed it for me
