### ISSUE TITLE
Explore: No data is at the same place as X axis

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20464]
**What happened**:

![nodata](https://user-images.githubusercontent.com/291750/69135246-1bcf0100-0ab9-11ea-964c-c389296f1b43.png)

**What you expected to happen**:

When there is no data the graph background is now shown

**How to reproduce it (as minimally and precisely as possible)**:

Logql with no data returned

**Environment**:
- Grafana version: 6.4.4

**Comment by hugohaggmark** [comment]
Hi again @roidelapluie can you tell me which browser/OS you're using? Can't repro this in Chrome on MacOS
![image](https://user-images.githubusercontent.com/562238/69136586-681b4080-0abb-11ea-9f0c-f9e56f68a042.png)

**Comment by torkelo** [comment]
That is as should (ie show empty graph), but the graph height looks a bit off in your screenshot

**Comment by roidelapluie** [comment]
Firefox 65 on Linux

**Comment by roidelapluie** [comment]
More details on the empty space:

![vv](https://user-images.githubusercontent.com/291750/69137146-71f17380-0abc-11ea-981b-f6660be697bf.png)

**Comment by hugohaggmark** [comment]
Still can't repro this on MacOS and FireFox 70
![image](https://user-images.githubusercontent.com/562238/69138362-cd246580-0abe-11ea-844f-600289c7b211.png)

Can you test in an newer browser version @roidelapluie?

**Comment by hugohaggmark** [comment]
@roidelapluie have you tried it out in a newer browser version?

**Comment by hugohaggmark** [comment]
ping @roidelapluie

**Comment by roidelapluie** [comment]
I hope to find the time today

Le lun. 25 nov. 2019 à 06:26, Hugo Häggmark <notifications@github.com> a
écrit :

**Comment by roidelapluie** [comment]
Reproduced with 70.0.1

![gra1](https://user-images.githubusercontent.com/291750/69539036-f7c16300-0f83-11ea-8342-3c92fa17acbe.png)

**Comment by roidelapluie** [comment]
![gra2](https://user-images.githubusercontent.com/291750/69539188-47a02a00-0f84-11ea-89f9-f4336a2a4098.png)
![gra3](https://user-images.githubusercontent.com/291750/69539189-47a02a00-0f84-11ea-9590-640aaccf2436.png)
![gra4](https://user-images.githubusercontent.com/291750/69539190-47a02a00-0f84-11ea-9d32-0231c20cc49b.png)
![gra5](https://user-images.githubusercontent.com/291750/69539192-4838c080-0f84-11ea-8563-40e1eae283bb.png)
![gra6](https://user-images.githubusercontent.com/291750/69539195-48d15700-0f84-11ea-8a92-b56638ccae45.png)

**Comment by roidelapluie** [comment]
When I remove overflow: scroll it gets better

**Comment by roidelapluie** [comment]
> Still can't repro this on MacOS and FireFox 70
> ![image](https://user-images.githubusercontent.com/562238/69138362-cd246580-0abe-11ea-844f-600289c7b211.png)
> 
> Can you test in an newer browser version @roidelapluie?

Yes you can reproduce it. Look at the huge space below the graph

**Comment by hugohaggmark** [comment]
Aha, you're talking about the gap between x-axis and filter. That's not what your original issue was about. Please create a new issue for this specific gap between x-axis and filters. I'll close this issue for now as I haven't seen anyone reproduce the `No data` label on the same place as the X axis.

All the best

**Comment by roidelapluie** [comment]
This gap is the cause for the issue I see.
