### ISSUE TITLE
Grafana - Graph - Time Region - is it possible to have non-weekly time regions ?

### ISSUE THREAD

**Issue by mattsee** [grafana/grafana#20478]
**What would you like to be added**:

Grafana - Graph - Time Region - is it possible to have non-weekly time regions ? i.e. a way to have a specific day or days out of office ( e.g. team holidays and/or  multi-day maintenance periods and/or configurable national holidays where the holiday may occur for 1 or more days and be considered effectively as a weekend - eg. christmas / new years day / easter / etc. )

**Why is this needed**:
Sometimes the time regions need to be more customisable than regular weekly occurences.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
