### ISSUE TITLE
Can not add query when I use grafana on my virtual machine

### ISSUE THREAD

**Issue by lwlei** [grafana/grafana#20475]
**What happened**: I installed grafana on my redhat virtual machine by using the following instructions：1. wget https://dl.grafana.com/oss/release/grafana-6.4.4.linux-amd64.tar.gz；2. tar -zxvf grafana-6.4.4.linux-amd64.tar.gz；3.  ./grafana-6.4.4/bin/grafana-server web &. And then, I tried to open my browser and go to http://localhost:3000/ on my virtual machine. When I clicked to add pinel, there was no default query "A" and even I got nothing when I clicked add query. However, when I visited ip:3000 in my PC(win 10), it worked well and I could add any query I need.
![image](https://user-images.githubusercontent.com/49778699/69151947-9a0dc080-0b16-11ea-9e08-402df614bc33.png)
![image](https://user-images.githubusercontent.com/49778699/69152068-c295ba80-0b16-11ea-8fad-d09f22a5d3b2.png)

**What you expected to happen**:  I want to figure out how to add query using grafana  on my virtual machine normally like on my PC.

**How to reproduce it (as minimally and precisely as possible)**: I did nothing. I just installed it on my virtual machine and run it. I even did not modify its cinfig file.

**Anything else we need to know?**: no

**Environment**:
- Grafana version: grafana-6.4.4.linux-amd64
- Data source type & version: opentsdb 2.3
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 7.5 
- User OS & Browser: win 10 and Red Hat Enterprise Linux Server release 7.5
- Grafana plugins: no
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this @lwlei we'll have a look, what browsers are you using and in the Linux window can you look if there is any console errors in browsers devtools?

**Comment by lwlei** [comment]
Thanks for your reply.
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Everytime I click "add query" button, it will appear "Error in parsing value for ‘transform’.  Declaration dropped." AND since I log on to the website， it constantly console various kinds of errors, such as "Error in parsing value for ‘background’.  Declaration dropped.", "Unknown property ‘overflow-anchor’.  Declaration dropped.", "Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.", "Error in parsing value for ‘min-height’.  Declaration dropped.  new" and so on.

**Comment by lwlei** [comment]
> Thanks for reporting this @lwlei we'll have a look, what browsers are you using and in the Linux window can you look if there is any console errors in browsers devtools?
Thanks for your reply.
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Everytime I click "add query" button, it will appear "Error in parsing value for ‘transform’. Declaration dropped." AND since I log on to the website， it constantly console various kinds of errors, such as "Error in parsing value for ‘background’. Declaration dropped.", "Unknown property ‘overflow-anchor’. Declaration dropped.", "Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’. Ruleset ignored due to bad selector.", "Error in parsing value for ‘min-height’. Declaration dropped. new" and so on.

**Comment by lwlei** [comment]
![image](https://user-images.githubusercontent.com/49778699/69222926-6635a800-0bb5-11ea-9047-9f27f1e30a60.png)

**Comment by torkelo** [comment]
Need to update the firefox version to a more up to date version (> Firefox 61 I think) latest firefox LTS will work for example
