### ISSUE TITLE
Allow overriding defaults for new dashboard with empty.json

### ISSUE THREAD

**Issue by mivok** [grafana/grafana#2047]
At some point, the template for a new dashboard became hardcoded in the NewDashboardCtrl controller rather than being loaded from empty.json.

It would be nice to have support for new dashboards being created based on a template again, which would allow configuring defaults for new dashboards. Some examples of things I'd like to be able to set for new dashboards are: timezone, shared crosshair, and some default panels such as a description at the top.

**Comment by toni-moreno** [comment]
+1

**Comment by damm** [comment]
Wouldn't it be nice if it was a new Dashboard wizard that would ask you a few simple questions and create it.

(Quick popup would be great)
Asking for Name, how many rows? how many Dashboards on the first row and how wide?

**Comment by yinchuan** [comment]
+1
I have the same use case with @mivok. And I found [this wiki](https://github.com/grafana/grafana/wiki/Customizing-default-settings-for-new-dashboards), but obvisouly it's not working only more.

Add support for empy.json or add support to config using a stored dashboard would both be very good.

**Comment by torkelo** [comment]
implemented and merged to master, 

![image](https://cloud.githubusercontent.com/assets/10999/14232934/0f3ac5ce-f96e-11e5-9af5-f6058f482f2c.png)

![image](https://cloud.githubusercontent.com/assets/10999/14232936/140b19f0-f96e-11e5-8606-3a35cb91439e.png)

**Comment by FliegenKLATSCH** [comment]
This doesn't fix the issue? How can one set the defaults e.g. for the auto-refresh intervals?

**Comment by pitr** [comment]
bumping this. Would be great if default could be configurable by grafana admin (eg. remove `5s,10s` intervals)
