### ISSUE TITLE
Support JSON to DataFrame conversion

### ISSUE THREAD

**Issue by Alex67-grb** [grafana/grafana#20471]
I check this file
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/dataframe/processDataFrame.ts
and looks like it is possible to work only with timeseries and table data formats.
 
Is there a way to work with custom (like raw json) data format?

**What would you like to be added**:
Support raw data format (or json), what will be sent from server to panel plugin without formatting on grafana sode (works like a proxy)

**Why is this needed**:
Heavy enterprise dashborads contain not only timeseries and table data :\
We are spent a lot of time to convert domain models to timeseries (table) data format on server side and convert back to domain model from timeseries (table) on frontend (panel plugin)

**Comment by kylebrandt** [comment]
@ryantxu and I have talked about this briefly. We realize that the Dataframe's columnar (table) model doesn't work well for objects (json).

One idea was to put the raw json on in a dataframe cell. Not very elegant but would probably work. We will think about this more, but we are aware that the columnar dataframe object is an awkward fit for objects / nested / schemaless data and will need a good story for these type of datasources.

**Comment by ryantxu** [comment]
We need some agreed way that arbitrary JSON would get transformed into a DataFrame.  I think a good place to start is to have a set of example input files and agree on what an expected DataFrame would look like.  If you really really need arbitrary JSON, then you are likely making a panel that should query for data directly rather than using the DataSource infrastructure.

Some possible inputs:

Simple JSON object:
```
{
  "title": "Sample Konfabulator Widget",
  "name": "main_window",
  "width": 640,
  "height": 480
}
```

Could become:
```
{
  fields:[
    {
      name:"title",
      type:"string",
      values:[ "Sample Konfabulator Widget"]
    },
    {
      name:"name",
      type:"string",
      values:[ "main_window"]
    },
    {
      name:"width",
      type:"number",
      values:[ 640]
    },
    {
      name:"height",
      type:"number",
      values:[ 480]
    }
  ]
}
```

With an array, perhaps
```
[ {
  "title": "aaa",
  "width": 11
},{
  "title": "bbb",
  "width": 22,
  "height": 200,
}]
```
would become:

```
{
  fields:[
    {
      name:"title",
      type:"string",
      values:[ "aaa", "bbb"]
    },
    {
      name:"width",
      type:"number",
      values:[ 11,22]
    },
    {
      name:"height",
      type:"number",
      values:[ null, 200]
    }
  ]
}
```

What about:
```
{ results: [ {
  "title": "aaa",
  "width": 11
},{
  "title": "bbb",
  "width": 22,
  "height": 200,
}] }
```

**Comment by ryantxu** [comment]
@Alex67-grb -- for implementation, check [MutableDataFrame](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/dataframe/MutableDataFrame.ts)

With the [add( ... )](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/dataframe/MutableDataFrame.ts#L219) function this may be pretty close to already done!
