### ISSUE TITLE
single-click way to switch to absolute times for current view

### ISSUE THREAD

**Issue by cdanis** [grafana/grafana#20479]
**What would you like to be added**:
It would be really great if there was some way to switch your view from using relative times to use the 'same' absolute times.

**Why is this needed**:
When writing incident postmortem documentation, or even just posting links to graphs in an email that someone will read later, it's very common to want to link to a dashboard at an absolute, fixed time range.  With the timepicker in Grafana 6.x it's not at all obvious how to do this.

**Comment by hugohaggmark** [comment]
Hi @cdanis and thanks for taking the time to contribute, isn't the default for sharing a graph a link with absolute timeranges? Wouldn't that suffice?

**Comment by cdanis** [comment]
Ah, you are right, it is the default.  Sorry, I'm very used to copying the URL by hand.  Thanks!
