### ISSUE TITLE
Annotations: Region Events - Infinite end

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/grafana#20487]
**What happened**:
Whole graph area is beig colored using the Annotions color.

**What you expected to happen**:
Only right half of the graph - starting from the annotion start **time** field value is being colored using the Annotations color.

**How to reproduce it (as minimally and precisely as possible)**:
Add a region Event using HTTP API (json datasource plugin) with following time range:
- **time** = middle of the displayed timerange in Grafana
- **timeEnd** = 253402273421000 (this represents 9999-12-31)

**Anything else we need to know?**:
I would expect to have an open ended event that has started, but not ended / not resolved yet. 

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: JSON datasource
- OS Grafana is installed on: windows 10
- User OS & Browser: Edge
- Grafana plugins: no
- Others:

**Comment by hugohaggmark** [comment]
Hi @KrisztianKaszas I'm trying to repro this but this is what I see with your use-case. Can't really see what is missing?
![image](https://user-images.githubusercontent.com/562238/69246693-78a9e480-0ba9-11ea-9c16-577b1f7c3805.png)

**Comment by KrisztianKaszas** [comment]
Environment see #20488 

Annotation Request 1:
```
POST http://localhost:3001/api/datasources/proxy/2/annotations HTTP/1.1
Host: localhost:3001
Connection: keep-alive
Content-Length: 615
Accept: application/json, text/plain, */*
Origin: http://localhost:3001
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Content-Type: application/json
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:3001/d/4br6JIxZz/annotation-test-dashboard?orgId=1&from=1579129200000&to=1579301999000
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: grafana_session=39a7b8d80d47efadf3a49c7a89304ddb

{"annotation":{"query":"{\"timeseries\":\"VERBUND_RFI_PERF_0\",\"attribute\":{\"name\":\"AttributeA\",\"value\":\"Afternoon Event\",\"isRegion\":true}}","name":"Region Test","datasource":"JSON_DOCKER_POSGRE","enable":true,"iconColor":"rgba(255, 96, 96, 1)"},"range":{"from":"2020-01-15T23:00:00.000Z","to":"2020-01-17T22:59:59.000Z","raw":{"from":"2020-01-15T23:00:00.000Z","to":"2020-01-17T22:59:59.000Z"}},"rangeRaw":{"from":"2020-01-15T23:00:00.000Z","to":"2020-01-17T22:59:59.000Z"},"variables":{"__from":{"text":"1579129200000","value":"1579129200000"},"__to":{"text":"1579301999000","value":"1579301999000"}}}
```

Annotation Response 1:
```
HTTP/1.1 200 OK
Content-Type: application/json; api-version=3.8.2; indented=false; charset=utf-8
Date: Wed, 20 Nov 2019 16:53:10 GMT
Server: Microsoft-HTTPAPI/2.0
X-Frame-Options: deny
Content-Length: 252

[{"text":"Afternoon Event","title":"Region Test","isRegion":true,"time":1579107600000.0,"timeEnd":1579129200000.0,"tags":null},{"text":"Afternoon Event","title":"Region Test","isRegion":true,"time":1579194000000.0,"timeEnd":253023699599.0,"tags":null}]
```
Result:
![image](https://user-images.githubusercontent.com/48984814/69260110-a26e0600-0bbf-11ea-889b-3d342d5be57a.png)

Note the Annotation display is completely offset. It is shown prior to 17:25 but actually according to the text box it starts at 18:00

Annotation Request 2:
```
POST http://localhost:3001/api/datasources/proxy/2/annotations HTTP/1.1
Host: localhost:3001
Connection: keep-alive
Content-Length: 615
Accept: application/json, text/plain, */*
Origin: http://localhost:3001
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Content-Type: application/json
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:3001/d/4br6JIxZz/annotation-test-dashboard?orgId=1&from=1579042800500&to=1579215599500
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: grafana_session=39a7b8d80d47efadf3a49c7a89304ddb

{"annotation":{"query":"{\"timeseries\":\"VERBUND_RFI_PERF_0\",\"attribute\":{\"name\":\"AttributeA\",\"value\":\"Afternoon Event\",\"isRegion\":true}}","name":"Region Test","datasource":"JSON_DOCKER_POSGRE","enable":true,"iconColor":"rgba(255, 96, 96, 1)"},"range":{"from":"2020-01-14T23:00:00.500Z","to":"2020-01-16T22:59:59.500Z","raw":{"from":"2020-01-14T23:00:00.500Z","to":"2020-01-16T22:59:59.500Z"}},"rangeRaw":{"from":"2020-01-14T23:00:00.500Z","to":"2020-01-16T22:59:59.500Z"},"variables":{"__from":{"text":"1579042800500","value":"1579042800500"},"__to":{"text":"1579215599500","value":"1579215599500"}}}
```
Annotations Response 2:
```
HTTP/1.1 200 OK
Content-Type: application/json; api-version=3.8.2; indented=false; charset=utf-8
Date: Wed, 20 Nov 2019 16:55:34 GMT
Server: Microsoft-HTTPAPI/2.0
X-Frame-Options: deny
Content-Length: 252

[{"text":"Afternoon Event","title":"Region Test","isRegion":true,"time":1579107600000.0,"timeEnd":1579129200000.0,"tags":null},{"text":"Afternoon Event","title":"Region Test","isRegion":true,"time":1579194000000.0,"timeEnd":253023699599.0,"tags":null}]
```
Result 2:

![image](https://user-images.githubusercontent.com/48984814/69259907-4c00c780-0bbf-11ea-8c9f-d046dc456299.png)

Note the Annotation is being displayed complet off the correct time range. The Annotation Info Box correctly shows the begin date for 18 o'clock, but the graphic shows it ending at 17:55 o'clock

**Comment by hugohaggmark** [comment]
@KrisztianKaszas there is so much new information in your last comment that I can't relate to this issue. The issue states startTime that is middle of the current displayed TimeRange and an endTime that is 253402273421000. I can't reproduce this behaviour using my JSON datasource. Can you please clarify your comment above?

**Comment by KrisztianKaszas** [comment]
Hi @hugohaggmark 
This is strange.
So let's try to reproduce the second one with shorter description:

Set Dashboard Range:
- from: 2020-01-14T23:00:00.500Z
- to: 2020-01-16T22:59:59.500Z

Add Annotation:
[{"text":"Afternoon Event","title":"Region Test","isRegion":true,"time":1579107600000.0,"timeEnd":1579129200000.0,"tags":null},{"text":"Afternoon Event","title":"Region Test","isRegion":true,"time":1579194000000.0,"timeEnd":253023699599.0,"tags":null}]

The above shown graphical interference will be the result.

Thank you!

**Comment by secustor** [comment]
@hugohaggmark Can you point to where the rendering is handled in the code? 
I have looked in the panel as well as the datasource but could only find references where the data model is updated. 

Thanks!
