### ISSUE TITLE
Segment component displays Value rather than Label

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#20483]
https://github.com/grafana/grafana/blob/ca3dff99e81cecbfa1332112c6c16309788d17dd/packages/grafana-ui/src/components/Segment/Segment.tsx#L21

The label being rendered is the underlying value of the select, not the label that appears in the dropdown itself.

![Screen Shot 2019-11-19 at 10 50 22 AM](https://user-images.githubusercontent.com/3194832/69162315-761c9180-0aba-11ea-8483-eac8408f55e9.png)
![Screen Shot 2019-11-19 at 10 50 25 AM](https://user-images.githubusercontent.com/3194832/69162323-787eeb80-0aba-11ea-855d-5dcc8ccf23fe.png)

**Comment by torkelo** [comment]
@sunker can you investigate this?

**Comment by sunker** [comment]
Yes, this could be done easily for the Segment component doing something like this
```const selectedOption = options.find(({ value }) => value === value);
  const label = selectedOption ? selectedOption.label : value;
  if (!expanded) {
    return <Label Component={Component || <a className={cx('gf-form-label', 'query-part', className)}>{label}</a>} />;
  }```

But that will not work for the SegmentAsync component since it doesn't know about its options when the label is being rendered. So I think the only option here is to change type of SegmentProps.value from `T`to `SelectableValue<T>`. That is a breaking change though. What do you think @torkelo?

**Comment by seanlaff** [comment]
For the async segment another idea could be to show a loading spinner as the label while the fetching is going on- if you wanted to keep the contract the same

**Comment by sunker** [comment]
No the SegmentAsync component is lazy. So the spinner would go on until the segment was clicked.

**Comment by knoguchi** [comment]
@seanlaff did you get it working?  I know the widget itself works but it's difficult to use as a whole.  I posted my question to the[ community site ](https://community.grafana.com/t/datasource-plugin-show-label-instead-of-value-in-the-ui-and-store-value-only/28589).  I appreciate if someone could give me tips.
