### ISSUE TITLE
Cannot save dashboard

### ISSUE THREAD

**Issue by kurtharriger** [grafana/grafana#2049]
Using current master branch (https://github.com/grafana/grafana/commit/57bacb339ce0c8748d56855a97fc06606b76ae65) on influxdb 0.9.

I am able to create a dashboard, but as soon as I save it its gone.  Perhaps is user error, I recorded a quick video to demonstrate:

https://www.youtube.com/watch?v=83vEL9i5Xdg&feature=youtu.be

**Comment by torkelo** [comment]
Will investigate ok Monday,  thanks for reporting this!

**Comment by torkelo** [comment]
Cant replicate this, tried saving new dashboards, importing dashboards, and save as, all work as expected. Did you use a build from the grafana builds page or did you build yourself? Make sure you have rebuilt the css (grunt css, not needed if you do a build with grunt release). 

Seems to be something strange going on when you save the imported dashboard. it tries to load it but it just comes back empty. Can you have chrome dev tools open (f12) and inspect the Grafana api requests / responses? maybe able to spot something there. 

Also if you can post the json dashboard you try to import here and I can try with the same dashboard.

**Comment by kurtharriger** [comment]
It seems I was mistaken the issue is not in saving the dashboard, but populating the UI with the previously saved dashboards. The save returns success and so does the search call with a couple properties about the dashboards that I have saved, but there is a js error accessing a property 'url' after the search call. 

I did build this from source as the server I had with the previous release installed on it but was not able to query influx 0.9 using.  It appeared to be adding extra quotes around the measurement name.    Master appeared to work, but I was focused on creating a graph didn't even attempt to save it when testing it locally.  

Here is an updated video showing the JS error on load.  I don't have the source on my local machine and the workstation I initially did the building and packaging on is at the office and the vpn isn't working today. But hopefully this provides enough context that it should be easy to identify, if not I can try and rebuild the source in unminified form so I can add breakpoints and inspect the objects. 

https://youtu.be/g2dakYVkNJI

**Comment by svetomir** [comment]
Hi, I have got the same error few times.

I got this error every time I added several (not sure of the right number, but more than 5) default graphs to the dashboard - generic grafana graphs that are created when new graph is added. I added few of them to the same dashboard before editing any of them, and the error occurred.

I am not sure if it is related, but might be helpful with recreation of the issue. I am using InfluxDB 0.9rc31 and last build from the master branch of the grafana 2.1.

**Comment by kurtharriger** [comment]
So I checked this on my office workstation running OS X and I can save and load dashboards fine, but it does not work on centos after I deployed it.  

Not sure what is different here, but I did have quite a bit of problems getting this installed on centos. 
I ultimately used docker centos to build a new release tarball.  I still had some issues getting phantomjs to install so I had commented that out. I was able to build a tarball but the rpm build failed for some reason so I just used the tarball.  

Would you mind perhaps publishing another rpm for the current master which I could try?

**Comment by damm** [comment]
CentOS 5 could be a problem; but hopefully we are talking newer.  I use MySQL w/out this issue

P.S. what's in /var/log/grafana/ logs?

**Comment by torkelo** [comment]
Yes, logs. Will push out new builds today
