### ISSUE TITLE
[secondary development][front end]  Unable to read "./node_modules/phantomjs-prebuilt/lib/location.js" file

### ISSUE THREAD

**Issue by lhh-hub** [grafana/grafana#20495]
When I execute NPM run build, an error message is reported  
**Unable to read "./node_modules/phantomjs-prebuilt/lib/location.js" file**
(https://user-images.githubusercontent.com/49900972/69219158-3682a200-0bad-11ea-88cf-fcc26242c5d8.png)
Then the location.js found in GitHub still reports an error
**Warning: Cannot read property '1' of null Use --force to continue.**
(https://user-images.githubusercontent.com/49900972/69219219-57e38e00-0bad-11ea-868d-71a6fd790e73.png)
(https://user-images.githubusercontent.com/49900972/69219209-51edad00-0bad-11ea-9734-c89e8dd24839.png)

Local environment：
node version :12.13.0
npm version:6.12.0
yarn version:1.19.1

**Comment by aknuds1** [comment]
Why are you using npm instead of yarn? The [documentation](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#frontend) says to use yarn.

**Comment by lhh-hub** [comment]
> Why are you using npm instead of yarn? The [documentation](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#frontend) says to use yarn.

I'm sorry to see a problem with a tutorial. I'm not familiar with the front-end. This will execute yarn start. Now it says:**'grafana toolkit' is not an internal or external command, or a runnable program or batch file.**

**Comment by aknuds1** [comment]
I just cloned a clean Grafana repo and did the following:

1. `yarn install --pure-lockfile`
2. `yarn build`

Can you try the above steps and see if it works?

**Comment by lhh-hub** [comment]
> I just cloned a clean Grafana repo and did the following:
> 
> 1. `yarn install --pure-lockfile`
> 2. `yarn run build`
> 
> Can you try the above steps and see if it works?

 Step 1 has been completed, and error will still be reported in step 2
(https://user-images.githubusercontent.com/49900972/69225951-4ce32a80-0bba-11ea-93f7-7251869de682.png)

**Comment by aknuds1** [comment]
What's your operating system?

**Comment by lhh-hub** [comment]
> What's your operating system?
windows10
I did these steps again, and it worked, and I'm sorry for that ,Thank you
