### ISSUE TITLE
CloudWatch: migrate to IMDSv2

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#20508]
**What would you like to be added**:
https://aws.amazon.com/jp/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
Upgrade aws-sdk-go to use IMDSv2.

**Why is this needed**:
Protect from SSRF.

**Comment by marefr** [comment]
Guess this is related to https://grafana.com/docs/installation/security/#data-source-proxy-and-protecting-internal-services

**Comment by sunker** [comment]
Do you want to give this a try @mtanda?

**Comment by mtanda** [comment]
If Grafana doesn't allow access to `169.254.169.254` by setting white list, Grafana should be safe from SSRF.

Grafana itself could be safe, but if Grafana still use IMDSv1, the instance need to enable IMDSv1.
When all process in the instance are migrated to IMDSv2, user can disable IMDSv1.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#configuring-instance-metadata-options
> For existing instances, you can opt in to require that IMDSv2 is used when requesting instance metadata. Use the modify-instance-metadata-options CLI command and set the http-tokens parameter to required.

**Comment by mtanda** [comment]
The latest aws-sdk-go use IMDSv2, we can migrate to IMDSv2 by upgrading aws-sdk-go.
https://github.com/aws/aws-sdk-go/pull/2958/files

I think there is no bad effect by migrating IMDSv2.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/20510
