### ISSUE TITLE
Running Grafana from S3 bucket

### ISSUE THREAD

**Issue by aather** [grafana/grafana#2050]
I uploaded grafana assets on S3 bucket enabled for static web hosting and made few changes to config.js file to update graphite server and Elasticsearch server hostname and ports. 

Browser able to access grafana index.html hosted on S3 bucket and was also able to save the dummy dashboard on to elasticsearch. However, grafana failed to get metrics from graphite carbon server. Browser just keep spinning waiting for metrics from graphite server. If I run grafana on the same server with graphite and apache then it works fine.

It seems apache server setup may be causing this issue. Do I need apache server, even when static contents are served from S3? 
[ With the working setup, apache server has grafana.conf in the sites-enabled directory. grafana.conf is a symbolic link to grafana directory with grafana config.js and other grafana assets.
/etc/apache2/sites-enabled# cat grafana.conf 
alias /grafana /usr/share/grafana ]

config.js
....
      datasources: {
        graphite: {
          type: 'graphite',
          url: "http://xxx.domainname.net:7405",
        },
        elasticsearch: {
          type: 'elasticsearch',
          url: "http://xxx.domainname.net:7410",
          index: 'grafana-dash',
          grafanaDB: true,
        }
      },

**Comment by torkelo** [comment]
Is your graphite server configure to allow CORS?
I know some who used s3 to host grafana 1.x , should be fine. But I recommend against it as grafana 2.x and future releases requires the grafana backend
