### ISSUE TITLE
Rendering of panels does not work if behind apache reverse proxy 

### ISSUE THREAD

**Issue by fetzerch** [grafana/grafana#2051]
I'm using grafana 2.1.0-pre1 configured to run behind an apache 2.4 reverse proxy on path /grafana. This setup is working fairly well, but I cannot render panel images any more. Could this be a bug in the PhantomJS renderer? Let me know if you need more info in order to debug this issue.

Rendered image:
![grafana](https://cloud.githubusercontent.com/assets/1133994/7783885/b0150e56-0152-11e5-966b-702d226974f7.png)

Grafana log:
~~~
2015/05/23 13:42:56 [I] PhantomRenderer::renderToPng url http://localhost:3000/grafana/dashboard-solo/db/atmeteo?theme=light&panelId=9&fullscreen&from=now-7d&to=now&width=1000&height=500
2015/05/23 13:42:56 [I] Completed /grafana/dashboard-solo/db/atmeteo 404 Not Found in 3.578544ms
2015/05/23 13:42:56 [I] Completed /grafana/css/grafana.light.min.7c1031ee.css 404 Not Found in 2.605139ms
2015/05/23 13:42:56 [I] Completed /grafana/app/app.ea54b179.js 404 Not Found in 5.543212ms
~~~

Grafana config:
~~~
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
~~~

Apache reverse proxy configuration:
~~~
RewriteRule ^/grafana$ grafana/ [R]                                             
ProxyPass /grafana/ http://localhost:3000/                                      
ProxyPassReverse /grafana/ http://localhost:3000/
~~~

**Comment by torkelo** [comment]
You need to set root_url to the public facing url (with the port used for apache)

If port 80 remove the port part
`` 
[server]
root_url = %(protocol)s://%(domain)s/grafana/
```

**Comment by fetzerch** [comment]
Indeed, works fine. Sorry for the false alarm.
