### ISSUE TITLE
Error Message "Unable to find application file" when using IE 11 to change time interval

### ISSUE THREAD

**Issue by DirkFries** [grafana/grafana#20518]
Hi @all,

we are using Grafana 6.4.0 at the moment. Everything works fine with Firefox, but there is an issue with IE 11 (Version: 11.0.9600.19399, Updateversion: 11.0.135).

As soon as someone clicks in a Dashboard on the time range menue in the upper right corner the following error message is displayed:

```
Unable to find application file


Grafana has likely been updated. Please try reloading the page.


Reload
Error: Unbekannter Fehler.

    in div
    in div
    in t
    in t
    in div
    in Unknown
    in Unknown
    in t
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in div
    in Unknown
    in t
    in n
    in div
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in Connect(t)
    in div
    in e
    in Connect(e)
    in Suspense
    in t
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in a
```

This happens in all Dashboards. Data Source is always Prometheus. Grafana is installed on SUSE Linux Enterprise Server 12 SP4.

**What you expected to happen**:
No error message, but option to change time range

**How to reproduce it (as minimally and precisely as possible)**:
Use IE 11 (Version: 11.0.9600.19399, Updateversion: 11.0.135) with Grafana 6.4.0 and click in a Dasbhoard on the menue to change the time range in the upper right corner

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: Prometheus 
- OS Grafana is installed on: SUSE Linux Enterprise Server 12 SP4
- User OS & Browser: Windows Server 2008 IE 11 (Version: 11.0.9600.19399, Updateversion: 11.0.135)

Bye, Dirk

**Comment by hugohaggmark** [comment]
Hi @DirkFries unfortunately we don't support IE11 for Grafana >v6 as you can read about [here](https://github.com/grafana/grafana/blob/85b371a02ab6b9e9b9ea9121eb148c3d02ba90a3/docs/sources/installation/requirements.md#supported-web-browsers)
