### ISSUE TITLE
Add new global built-in variables

### ISSUE THREAD

**Issue by dcastanier** [grafana/grafana#20523]
**What would you like to be added**:
${__dashbord.name} : the dashboard name
${__org.name}: the current organization name
${__from.text}: the from variable in string format
${__to.text}: the to variable in string format

**Why is this needed**:
I need to add a title panel on each dashboard to understand on printed page what is visible.
I would like this: 
Overview : Nile (2019-11-19 13:30:40 to 2019-11-20 13:30:42)
With a Text panel with this:
`${__dashbord.name} : ${__org.name} (${__from.text} to ${__to.text})`

**Comment by hugohaggmark** [comment]
@dcastanier how would that work with page breaks when printing?

**Comment by dcastanier** [comment]
Dashboard is design to fit correctly on printed page.
The objective is to be able to add visual information (time and org are only visible in tool tip)
