### ISSUE TITLE
explore: "Scan for other logs" should be actionnable

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20528]
**What happened**:

![scan](https://user-images.githubusercontent.com/291750/69252516-63d24e80-0bb3-11ea-9ce0-e6ba33d57aab.png)

**What you expected to happen**:

Scan for other log in another color, in a button, or underline, so we know we can click on it.

**How to reproduce it (as minimally and precisely as possible)**:
go to explore, run a query without result.

**Environment**:
- Grafana version: 6.4.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks again @roidelapluie
