### ISSUE TITLE
Can not get labels when data is instant vector

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#20527]
**What happened**:

I am writing plugin for grouped by label grid https://github.com/ozonru/data-grid-grafana-plugin for Prometheus datasource, so to render row in grid I need all labels from API result, but when I turn on `Instant` switch I am getting `labels: undefined` as series data. Via network tab in devtools I can confirm that labels exist

**What you expected to happen**:

labels must be provided as key value map

**How to reproduce it (as minimally and precisely as possible)**:

Using grafana playground for panel https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=5m&fullscreen&edit&panelId=1 
If turn on `instant` in any react panel plugin, all series with instant vector in `data` prop will be without labels.

**Anything else we need to know?**:

Looks like difference is in transformation result:
https://github.com/grafana/grafana/blob/e0a2d4beacc379def0878655b3a3f7cceffbf3fc/public/app/plugins/datasource/prometheus/result_transformer.ts#L32

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: thanos v0.8.1
- Grafana plugins: https://github.com/ozonru/data-grid-grafana-plugin

**Comment by hugohaggmark** [comment]
Thanks @vankop for taking the time to add this. @davkal is there a reason we haven't done this?

**Comment by vankop** [comment]
@hugohaggmark also will be great, if `refId` will be filled in for all series, right now it is set to `undefined` explicitly

I can create separate PR if you want to

**Comment by hugohaggmark** [comment]
You're always welcome to contribute with an PR, thanks @vankop

**Comment by vankop** [comment]
@hugohaggmark As I see for `master` build - `labels` are reworked for `DataFrame` and now presented for each `field`, works fine with Instant vector. `refId` also presented now 👍

I will check this for `6.4.x` branch later.

Also I have a question about how to extract labels for each serie in "non breaking" way aka
```typescript
function getLabels(frame: DataFrame) {}
```

Right now I do just `frame.labels` in my code, but it will be broken in next releases (since labels now presented for each field)

**Comment by hugohaggmark** [comment]
@ryantxu can you help out with @vankop question above?

**Comment by davkal** [comment]
The instant query produces a table model, which does not have the concept of tags/labels.
since the table model is being used as input to the dataframe converter, the table model would need to be extended to support labels.

**Comment by aocenas** [comment]
As we have plans to refactor the prometheus datasource to return dataframes instead of the table model, that refactor would probably also solve this issue.

**Comment by ivanahuckova** [comment]
I believe that this should be fixed by refactor of prometheus results to data frame  (https://github.com/grafana/grafana/pull/27737/files) and should be part of 7.3 release
