### ISSUE TITLE
graphite version auto-negotiation/discovery

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20529]
currently, users manually configure a version in their graphite datasource settings.
this:
* may be incorrect when users select a non-optimal value
* may become incorrect when graphite is upgraded. 
* is clunky
* doesn't make a whole lot of sense for metrictank users:
   - metrictank has a version (depending on which metrictank version you have you get support for functionality such as additional query metadata. currently it's assumed all MT versions have this. and also, in the future we may introduce more special features at certain versions
   - metrictank is typically deployed in conjunction with a graphite server (for now). graphite has its own version...

clearly, this is not a good approach.
much better would be automatic discovery, combined with a periodic background refresh (+forceable refresh) in case graphite is upgraded.
Both Graphite and Metrictank expose their version. Grafana can trivially query for this. If it makes things easier, we can probably add however graphite exposes it, to metrictank

This way, users can upgrade their graphite/metrictank (or downgrade), or switch graphite for metrictank, or whatever, and everything would just work, and they would get the latest features automatically as soon as Grafana gets support for them.

I haven't really thought this fully through yet. Need to think a bit more about breaking api changes, version negotiation, etc.

**Comment by hugohaggmark** [comment]
Thanks @Dieterbe for adding this!

**Comment by davkal** [comment]
We're doing this soon for elasticsearch, could look there for a pattern.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
