### ISSUE TITLE
Tags obstruct dashboard name in search

### ISSUE THREAD

**Issue by lmuhlha** [grafana/grafana#20539]
**What would you like to be added**:

In the Grafana search view when searching for dashboards, some have so many tags that it overlaps with the dashboard name 

Would be nice if the dashboard name was always visible and perhaps collapse the tags or display them in a different row.

![image](https://user-images.githubusercontent.com/16561599/69281463-282c8a00-0b9d-11ea-8a67-d9c068f9c5a8.png)

**Why is this needed**:

It is impossible to read the dashboard titles when there are too many tags.

**Comment by hugohaggmark** [comment]
Hi @lmuhlha and thanks for adding this. We're currently looking at the bigger picture regarding dashboard search so this could be part of that I think.

Could be part of #15257

**Comment by Clarity-89** [comment]
Fixed in the 7.x with the search refactor.
