### ISSUE TITLE
explore: alter labels vs replacing them

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20530]
**What would you like to be added**:

In explore, when we click to get a label, we can only overwrite the full query.
![env](https://user-images.githubusercontent.com/291750/69255989-06d99700-0bb9-11ea-98bf-b806a320cd3f.png)

I think we should have multiple options (not sure how to display them):

- Add label and run query
- Add label
- Change current labels with selected label and run query
- Change current labels with selected label

some inspiration can be found in wireshark:
![2](https://user-images.githubusercontent.com/291750/69256224-7059a580-0bb9-11ea-95f7-f393631d6b25.png)
![1](https://user-images.githubusercontent.com/291750/69256225-70f23c00-0bb9-11ea-9f4a-e5fa714be684.png)

**Why is this needed**:

**Comment by hugohaggmark** [comment]
Thanks so much for contributing @roidelapluie

**Comment by aocenas** [comment]
Just FYI we have some plans to do a visual query editor for loki/prometheus sometime in the future so maybe that would be better way to solve this and keep the text input editor as it is.

**Comment by aocenas** [comment]
@roidelapluie We have a totally new UI for this so please check that out: https://grafana.com/docs/grafana/latest/datasources/loki/#log-browser

**Comment by roidelapluie** [comment]
Does it apply to prometheus as well?

**Comment by aocenas** [comment]
@roidelapluie there is plan to do similar thing for prometheus but don't think we have eta at this moment. We may wait for some feedback on this UI with Loki first.
