### ISSUE TITLE
Unable to build grafana from source on linux (go version issue)

### ISSUE THREAD

**Issue by sglajchEG** [grafana/grafana#20537]
**What happened**:
`make run` returned an error
> make run
can't load package: package github.com/unknwon/bra: cannot find package "github.com/unknwon/bra" in any of:
	/usr/lib/go-1.10/src/github.com/unknwon/bra (from $GOROOT)
	/home/scott/sources/gosources/src/github.com/unknwon/bra (from $GOPATH)
Makefile:49: recipe for target 'scripts/go/bin/bra' failed
make: *** [scripts/go/bin/bra] Error 1

If I attempted to install bra manually, I got the following:
> go get github.com/Unknwon/bra
# github.com/unknwon/bra/cmd
src/github.com/unknwon/bra/cmd/sync.go:38:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)

I eventually (somehow) tracked this down to be a go version dependency issues (I think), but there should be some prereqs defined in the dev guide.

**What you expected to happen**:
`make run` should have built the software

**How to reproduce it (as minimally and precisely as possible)**:
There's no dependencies section for linux, only for mac/brew.
As a result of this, I tried building with the go version I had from the package manager (Ubuntu in this case).  I had go 1.10 installed (from the last time I successfully built grafana, at around version 5.4 of grafana).

I did eventually get grafana to compile by installing a different go version using "snap"
sudo snap install go --classic
This provided go:
go version go1.13.4 linux/amd64

Then "make run" worked.

**Anything else we need to know?**:
There should be a linux dependency setup section, and regardless of OS, you should call out the minimal go version required to build the product.

Also in trying to build the frontend, I couldn't, because I had node 11 installed.  I had to downgrade to node 10 (which won't be viable for me long term).  This is because the package.json requires node >=10 and node < 11.  This is not a restriction you want to make unless you're working around a node bug temporarily.  I'd request you either figure out why you can't have a later node version, or if you can build with a later node version, remove the "< 11" part of the dependency check.

**Environment**:
- Grafana version: master branch as of 11/20/2019
- Data source type & version: N/A
- OS Grafana is installed on: Linux Mint 18.1 XFCE (which is based off Ubuntu 16.04 Xenial repos)
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:
golang 1.10 from the package manager

Let me know if you need any more information.

**Comment by aknuds1** [comment]
You need Go 1.13.

**Comment by sglajchEG** [comment]
Seems like a quick requirement to slap into the developer-guide.md then?  "Go (1.13 or higher)" as the text rather than "Go"?

**Comment by aknuds1** [comment]
Yeah, we should probably document the requirement. Making a note of it.

**Comment by imdadul** [comment]
Having simillar issue now.
<img width="580" alt="image" src="https://github.com/grafana/grafana/assets/5765767/896ca0e6-edd2-44d7-a2e5-b8ba1e5cf005">
