### ISSUE TITLE
 Time / date title for Bar Gauge Visualization 

### ISSUE THREAD

**Issue by clifforddw** [grafana/grafana#20538]
It would be great to be able to format the time field from Influx to display an RFC based date and not the UNIX ns time stamp in the  Bar Gauge Visualization. 

Plotting data grouped by time or other tags is often time based and being able to format the time / date title would be great. 

Attached is a shot of the current cell selection. 

![image](https://user-images.githubusercontent.com/25323662/69276769-b6c5f900-0be7-11ea-855d-41a45eeefa52.png)

**Comment by hugohaggmark** [comment]
Thanks for contributing @clifforddw

**Comment by lominskyi-perfectial** [comment]
Hello, @hugohaggmark! Any chance we get this done?

**Comment by torkelo** [comment]
The bar gauge panel is not designed to format the "name" of the bar as a unit / time

**Comment by torkelo** [comment]
This needs to be handled in a graph / bar chart panel
