### ISSUE TITLE
Make search more prominent

### ISSUE THREAD

**Issue by lmuhlha** [grafana/grafana#20540]
**What would you like to be added**:

Grafana search is challenging to find and not in an obvious place. Also unexpected when clicking on the title of a dashboard in the dashboard view. 

Perhaps it would be better suited on the default landing page, searching (or the manage view) should be the entry point.

**Why is this needed**:

It would improve the overall user experience and ease of use when trying to search in Grafana.

**Comment by hugohaggmark** [comment]
Thank you @lmuhlha for taking the time to create this feature request.

**Comment by Clarity-89** [comment]
There's now a separate search menu in the sidenav, additinally dashboard search can be triggered from any view via `F` button shortcut.
![Screenshot 2020-06-02 at 15 10 53](https://user-images.githubusercontent.com/8878045/83518561-44619a00-a4e3-11ea-9999-9be674c8ae93.png)
