### ISSUE TITLE
"sort"  disabled option is not worked as expected in the query option of variable

### ISSUE THREAD

**Issue by gavincaiz** [grafana/grafana#20542]
**What happened**:
"sort"  disabled option is not worked as expected in the query option of variable, the bug will change the list order even i select the disabled.

**What you expected to happen**:
the variable drop down list show as data source return.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I install the newest grafana and test with influx as datasource , the bug  still exist.

**Environment**:
- Grafana version: 5.2.x, 6.4.x,  i guest all version
- Data source type & version: influx 1.7.7
- OS Grafana is installed on: centos 7.x
- User OS & Browser: chrome
- Grafana plugins:
- Others:

bug replay:

1.create varialbe and disable sort     
<img width="948" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/58017267/69300583-94b39180-0c4e-11ea-8d31-46eb1f0bb5d2.png">

2.it should return like list
￼<img width="850" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/58017267/69300600-a9902500-0c4e-11ea-882d-0d5f2ab2c3ee.png">

3.but show in drop down list
￼
<img width="199" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/58017267/69300623-b7de4100-0c4e-11ea-892c-7057bdea1bab.png">

thank you.

**Comment by hugohaggmark** [comment]
Hi @gavincaiz , I'm trying to repro this without success.

How does the variable look like when you edit it? My preview values are exactly as they appear in the dropdown. 
![image](https://user-images.githubusercontent.com/562238/69338407-6db38a80-0c63-11ea-9203-54046e548781.png)

Could you try to click on the `Multi Value` switch on and off and see if the preview values are updated? 

And when you do this can you please check what you see in the network tab in Chromes devtools.
![image](https://user-images.githubusercontent.com/562238/69338601-d569d580-0c63-11ea-9b27-e828159d4949.png)

**Comment by gavincaiz** [comment]
![image](https://user-images.githubusercontent.com/58017267/69388505-fc77e400-0d03-11ea-93a5-96eb7cdcb138.png)
thanks for your quick reply. I just tried as you describe, the problem existed. the network returns data in descending order, but the control shows data in  ascending order。
-- | --

**Comment by gavincaiz** [comment]
another example:
![image](https://user-images.githubusercontent.com/58017267/69389569-62199f80-0d07-11ea-98de-f5bccac7774e.png)

**Comment by gavincaiz** [comment]
another example:
![image](https://user-images.githubusercontent.com/58017267/69390659-f89b9000-0d0a-11ea-885b-416857d30348.png)

**Comment by gavincaiz** [comment]
here updated:  
User OS & Browser: mac & chrome ,  safari also test.

**Comment by hugohaggmark** [comment]
What happens if you change to `On Dashboard Load` in the Refresh select?

**Comment by gavincaiz** [comment]
I had already tried this.  no effect.

**Comment by gavincaiz** [comment]
![image](https://user-images.githubusercontent.com/58017267/69395793-30aacf00-0d1b-11ea-9bee-2233a8e667c7.png)

**Comment by gavincaiz** [comment]
![image](https://user-images.githubusercontent.com/58017267/69395812-46b88f80-0d1b-11ea-97cf-7415d74ce9ec.png)

**Comment by gavincaiz** [comment]
I find the problem. you reproduce  with float number, so the result is ok. but when the data is not float(even the type is float), the order show not as expected

**Comment by gavincaiz** [comment]
the problem is still existed, why close? I just find the clue to you.  not mean I soloved the problem.  haha

**Comment by gavincaiz** [comment]
I find the trick way "just multiply by decimal point such as result*1.01" to  circumvent the problem. the bug may in the js code only support float type when parse json result.
