### ISSUE TITLE
Tooltip component returned unexpected error

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#20548]
**What happened**:
While using the 'Explore' view, 'suddenly' an unexpected error happened.
<img width="1957" alt="Screenshot 2019-11-21 10 23 57" src="https://user-images.githubusercontent.com/3349855/69326104-8748d800-0c4b-11ea-882f-603fd7b32f62.png">

**What you expected to happen**:
Nothing. I was looking at the graph and table.

**How to reproduce it (as minimally and precisely as possible)**:
1. Query on admin-ops-tools1 Grafana:
```
(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes)) / node_memory_MemTotal_bytes > 0.9
```
2. Time window: Last 2 days
3. Explore the graph and table

**Anything else we need to know?**:
Discussed on Slack with @dprokop and @peterholmberg. Seems related to the new Tooltip component.

**Environment**:
- Grafana version: Grafana v6.6.0-pre (d630ac4b68)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux - ops-tools1
- User OS & Browser: macOS 10.14 / Firefox 70.0.1
- Grafana plugins: loads of 'em
- Others: -

**Comment by dprokop** [comment]
@Duologic is this sth that you can reproduce?
