### ISSUE TITLE
Feature Request - Ability to display non-numeric data in Single Stat or Text panel

### ISSUE THREAD

**Issue by Duncx** [grafana/grafana#2054]
Grafana 2.0/InfluxDB 0.8

InfluxDB is able to take alphanumeric timestamped data which can be very useful eg for storing application version information.

It would be fancy to be able to pull this info so that I could show the current version in a panel. 

Obviously major versions (2.0) work fine but when its version 1.2.123 it fails to parse.

Kind regards

D

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/1380

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/issues/2203

**Comment by Duncx** [comment]
@torkelo Thanks Torkel, I have this implemented and is working nicely.
