### ISSUE TITLE
Explore: Handle Multiline properly

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20545]
![xxx](https://user-images.githubusercontent.com/291750/69324007-02a88a80-0c48-11ea-8cff-59ff58703a89.png)

**What would you like to be added**:

We are sending Multi Line logs to Loki, embedded in a JSON with multiple keys.

It would be great if we could have the option to just view that parsed (non-indexed) "message" field in Loki and to have loki split the newlines `\n` into multiple lines on screen (+ on the "fields" details).

**Why is this needed**:

Makes it really more easy to read long messages like stacktraces.

**Comment by hugohaggmark** [comment]
Duplicate of #17584

**Comment by roidelapluie** [comment]
Sorry! I looked before posting but somehow missed it
