### ISSUE TITLE
Mixed Datasource: Order of results depend on when queries finish (regression in 6.4) 

### ISSUE THREAD

**Issue by skypalombav** [grafana/grafana#20555]
**What happened**:
With grafana update 6.4.4,in table with mixed datasource (different, but all elasticsearch datasource), we cannot reorder columns, in fact between dashboard refreshes the column ordering change. Below a table panel with the problem between three clicks of the refresh:

![refresh1](https://user-images.githubusercontent.com/56594006/69336501-efed8000-0c5e-11ea-9183-4181763090bf.JPG)

![refresh2](https://user-images.githubusercontent.com/56594006/69336530-fd0a6f00-0c5e-11ea-8a1f-6a8379545483.JPG)

![refresh3](https://user-images.githubusercontent.com/56594006/69336534-00055f80-0c5f-11ea-8848-521ac2c8416f.JPG)

**What you expected to happen**:
In dashboard refreshes the column ordering not change
**How to reproduce it (as minimally and precisely as possible)**:
With refresh of a table with mixed datasource
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v 6.4.4
- Data source type & version: Mixed Elasticsearch datasource
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 7, Mozilla Firefox & Chrome
- Grafana plugins: Table Panel (Native Plugin)
- Others:

**Comment by hugohaggmark** [comment]
Hi @skypalombav, I can't repro this using TablePanel with a mixed data source. Can you supply output from the network tab in Chrome devtools so we can disregard any ds specific issues?

**Comment by skypalombav** [comment]
Hi @hugohaggmark, thanks for your response. 
Below the output of the network tab:
![refresh_details1](https://user-images.githubusercontent.com/56594006/69344185-3ba82580-0c6f-11ea-820c-123b8ff51722.JPG)
![refresh_details2](https://user-images.githubusercontent.com/56594006/69344186-3ba82580-0c6f-11ea-9dd2-8b0d42a1c101.JPG)
![refresh_details3](https://user-images.githubusercontent.com/56594006/69344188-3c40bc00-0c6f-11ea-85f6-06c0071501ef.JPG)

**Comment by hugohaggmark** [comment]
@marefr any ideas?

**Comment by marefr** [comment]
@hugohaggmark not sure. Sounds familiar. Didn't we fix similar problem for Prometheus, like this #19597? Doesn't feel like it is a problem with Elasticsearch datasource, more dataframe/mixed ds maybe? @torkelo something you recognized?

**Comment by torkelo** [comment]
think the root cause here is the same as what we had with prometheus after we switched to RxJS observable. Ie the order in witch queries finishes changes order of series returned

**Comment by hugohaggmark** [comment]
Should this be in `stable` or `beta2`?

**Comment by torkelo** [comment]
@hugohaggmark it's not super critical for either (since this has been a bug in 6.4), but would be something we want to fix for 6.5.x patch release at the latest.
