### ISSUE TITLE
Grafana Influx db export import data problem

### ISSUE THREAD

**Issue by Aycayilmz** [grafana/grafana#20559]
With Influxdb I store my data on the server, but I can't move my data to another server. Is there a tool developed for this? I'd appreciate it if you helped. (Grafana and Influxdb are working on Docker.)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by marefr** [comment]
Maybe have better luck at the Influx community, https://community.influxdata.com/
