### ISSUE TITLE
Explore: Selecting labels in log row detail removes logql filter

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20553]
**What happened**:

![xxxy](https://user-images.githubusercontent.com/291750/69333148-6e92ef00-0c58-11ea-9894-6661dccac235.png)
![xxxy2](https://user-images.githubusercontent.com/291750/69333149-6e92ef00-0c58-11ea-82a2-8980552d42f5.png)
![xxxy3](https://user-images.githubusercontent.com/291750/69333150-6e92ef00-0c58-11ea-925e-f642e1dcce06.png)

**What you expected to happen**:

The changed log line still contains my filter != "ERROR"

**How to reproduce it (as minimally and precisely as possible)**:

see screenshot

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.6.0-pre (6a4ad136dc)
- Data source type & version: loki 1.0.0

**Comment by hugohaggmark** [comment]
Thanks again @roidelapluie
