### ISSUE TITLE
Feature Request - Add graph series default activation status option

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#2055]
Hi, 
It would be great to have a possibility to save the default activation/deactivation series status for the selected graphs or dashboards so that other users start viewing them with the default view first.
For instance the following CPU Load graph has only shortterm, and longterm series activated and this view is loaded as default:
![grafana](https://cloud.githubusercontent.com/assets/12551929/7796814/d70a1294-02e3-11e5-819b-c2e1d6d1e48c.jpg)

**Comment by mtanda** [comment]
same as https://github.com/grafana/grafana/issues/644

**Comment by torkelo** [comment]
closing this as this is same as #644 and that was closed. 

I am open to considering this, maybe as part of https://github.com/grafana/grafana/issues/11684
