### ISSUE TITLE
Reevalute all variables within a repeating row

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#20561]
**What would you like to be added**:
When using repeating rows, it'd be nice to have any template variables that reference the variable being repeated off of to be evaluated with the row. For example:

I have a variable, `service`, that is a list of all services in selected namespaces.
```
label_values(kube_service_info{namespace=~"$namespace"}, service)
```
I want to have repeating rows off of this variable. Both the `namespace` and the `service` variable is multivalue/select all and so this could return all services in cluster if selected. I then have another hidden variable called `service_ns`:

```
label_values(kube_service_info{service=~"$service"}, namespace)
```

Ideally, within each repeating row, this would be evaluated separately in each row to render the namespace that service is in. However, it will merely select the namespace from the first service in the row. For example,

if the `service` variable returns:

svcA
svcB
svcC

I want the `service_ns` variable in such a way where within each row, it returns:

nsA
nsB
nsC

It currently returns:

nsA
nsA
nsA

**Why is this needed**:

To allow for more dynamic repeating rows where the variables are evaluted within the row scope.

**Comment by hugohaggmark** [comment]
Thanks @whitlekx for contributing with this

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
