### ISSUE TITLE
Open-ended and editable dates for annotations

### ISSUE THREAD

**Issue by dweineha** [grafana/grafana#20564]
When we add annotations it's usually to explain observed regressions or improvements. When doing so we'd like the option to have the annotation to last "until further notice".

This is needed because when the annotation is added to explain a regression we're not prescient; we don't know when the issue will be fixed and thus cannot set an end date. Once we know when an issue has been fixed (either in software or hardware) we'll be able to add the end date. This also requires the end date to be editable. Ideally the start date should be editable too; having to redo annotations just because you got it wrong when creating it is a bit annoying.

**Comment by hugohaggmark** [comment]
Thanks @dweineha for taking the time to add this

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
