### ISSUE TITLE
wrong values while stacking with percent

### ISSUE THREAD

**Issue by svetomir** [grafana/grafana#2056]
Numbers shown while stacking with percent are actual values not percents.

Please consider changing this to percents:

![capture](https://cloud.githubusercontent.com/assets/6276860/7801636/36cd0e22-0328-11e5-991d-ac9f70fa7f51.JPG)

Grafana Version: 2.1
Datasource: InfluxDB 0.9rc31

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/896
