### ISSUE TITLE
Improve how to turn on and configure pprof profiling and tracing 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20576]
**What would you like to be added**:
Support turning on pprof profiling and tracing separately. Also turning on pprof profiling and tracing should be possible using environment variable.

**Why is this needed**:
- Turning on tracing may have bigger impact since it generates a trace file which can be quite big so good to only be able to turn on pprof profiling without tracing. 
- To make it easier to turn these on when running Grafana in Docker container or deb/rpm is highly valuable.

**Addition requirements:**
- `profile` should be configurable by environment variable.
- `profile-port` should be configurable by environment variable.
- 'tracing' should be configurable by grafana-server flag and environment variable.
- 'tracing-out' should be configurable by grafana-server flag and environment variable.

Environment variables should probably be prefixed with `GF` to follow [this convention](https://grafana.com/docs/installation/configuration/#using-environment-variables). But needs to be carefully selected to not collide with Grafana settings, maybe `GF_PROCESS` or `GF_STARTUP` etc.

Code is here: https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-server/main.go#L59-L79

**Comment by DanCech** [comment]
I'd also like to see writing the trace be configurable separately from enabling profiling, and ideally support specifying the file to write the trace to.

**Comment by marefr** [comment]
I'm creating a separate issue for that :+1:

**Comment by marefr** [comment]
Updated issue description.
