### ISSUE TITLE
React Graph: Data series with no data points can cause tooltip to show ErrorBoundary

### ISSUE THREAD

**Issue by garrettheel** [grafana/grafana#20573]
**What happened**:

The following stack-trace was encountered in the Explore view:

```
An unexpected error happened
Details
TypeError: Cannot read property 'values' of undefined

    in SingleModeGraphTooltip (created by GraphTooltip)
    in GraphTooltip (created by Graph)
    in div (created by TooltipContainer)
    in TooltipContainer (created by ChartTooltip)
    in Portal (created by ChartTooltip)
    in ChartTooltip (created by GraphSeriesToggler)
    in div (created by Graph)
    in Graph (created by GraphWithLegend)
    in div (created by GraphWithLegend)
    in div (created by GraphWithLegend)
    in GraphWithLegend (created by GraphSeriesToggler)
    in GraphSeriesToggler (created by UnThemedExploreGraphPanel)
    in div (created by Collapse)
    in div (created by Collapse)
    in Collapse (created by UnThemedExploreGraphPanel)
    in UnThemedExploreGraphPanel (created by Context.Consumer)
    in ExploreGraphPanel (created by AutoSizer)
    in ErrorBoundary (created by ErrorBoundaryAlert)
    in ErrorBoundaryAlert (created by AutoSizer)
    in main (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by Explore)
    in div (created by Explore)
    in div (created by Explore)
    in Explore (created by ConnectFunction)
    in ConnectFunction (created by HotExportedConnect(Explore))
    in AppContainer (created by HotExportedConnect(Explore))
    in HotExportedConnect(Explore) (created by Wrapper)
    in ErrorBoundary (created by ErrorBoundaryAlert)
    in ErrorBoundaryAlert (created by Wrapper)
    in div (created by Wrapper)
    in div (created by Scrollbars)
    in div (created by Scrollbars)
    in Scrollbars (created by CustomScrollbar)
    in CustomScrollbar (created by Wrapper)
    in div (created by Wrapper)
    in Wrapper (created by ConnectFunction)
    in ConnectFunction (created by HotExportedConnect(Wrapper))
    in AppContainer (created by HotExportedConnect(Wrapper))
    in HotExportedConnect(Wrapper) (created by LoadableComponent)
    in LoadableComponent (created by Component)
    in Component (created by Component)
    in ThemeProvider (created by Component)
    in Component (created by ConfigProvider)
    in ConfigProvider
    in ErrorBoundary (created by ErrorBoundaryAlert)
    in ErrorBoundaryAlert
    in Provider
```

This replaces the chart view with a giant red error box containing that message.

Additional context from the js console:

```
Uncaught TypeError: Cannot read property 'values' of undefined
    at getValueFromDimension (dimensions.ts:32)
    at SingleModeGraphTooltip (SingleModeGraphTooltip.tsx:16)
    at SingleModeGraphTooltip (react-hot-loader.development.js:757)
    at renderWithHooks (react-dom.development.js:12938)
    at mountIndeterminateComponent (react-dom.development.js:15020)
    at beginWork (react-dom.development.js:15625)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
```

**What you expected to happen**:

Expected the chart to remain visible and render a tooltip for the series being hovered on.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to the "Explore" view and enter a query resulting in more than 10 series (in my case 12; I can't reproduce with a smaller number of series).
2. The chart will appear and look correct
2. Move your cursor over the series and the error will occur. Sometimes the error wasn't immediate, but dragging the cursor over all of the series always causes it.

**Anything else we need to know?**:

From some logging that I added, it seems that the `seriesIndex` corresponding to the `activeSeries` is out of bounds. e.g I would see  `activeItem.series == 14` despite `series.length == 12` [here](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Graph/Graph.tsx#L143)

**Environment**:
- Grafana version: Verified against 11304b14 on master today.
- Data source type & version: Wavefront / 2.0.0
- OS Grafana is installed on: Linux
- User OS & Browser: OSX; reproduced in Chrome and Firefox
- Grafana plugins: none
- Others:

**Comment by hugohaggmark** [comment]
Hi @garrettheel  and thanks for the report, I'm not able to repro this but I'm using prometheus as a datasource. Can you replicate it using an other datasource?
![tooltip-explore-bug](https://user-images.githubusercontent.com/562238/69396940-58cb0b80-0ce4-11ea-8c3b-4fb0baceef9b.gif)

**Comment by garrettheel** [comment]
@hugohaggmark thanks for taking a look! I tried using the devenv influxdb and was unable to reproduce.

I poked around with the Wavefront datasource and noticed that my query generates some series containing no datapoints. Upon filtering those out (i.e `_.filter(resultSeries, (d: any) => {return d.datapoints.length > 0});`), I cannot reproduce the issue any longer.

Is this a bug in the datasource, or with `Explore`? It's worth noting that I don't see this issue when using dashboards.

**Comment by hugohaggmark** [comment]
If you want to try and reproduce it in a dashboard be sure to use the new React Graph, but yes this might be a WaveFront specific issue.

I think I will close this issue for now but we can always reopen it if new evidence points to an issue in Grafanas React graph.

**Comment by garrettheel** [comment]
@hugohaggmark a couple of questions:

 1. How can I ensure that I'm using the new "React Graph" for a dashboard panel?
 1. Is it valid for a datasource to return a series containing no datapoints?

**Comment by garrettheel** [comment]
@hugohaggmark I figured out how to test this, by adding the following to my config file:

```
[panels]
enable_alpha = true
```

I am able to easily reproduce this on a dashboard using the same query and a graph2 panel, so I believe this to be a general issue with the new React graph. Please let me know if I can provide any additional information, otherwise hopefully the information I've already provided will allow you to reproduce.

**Comment by hugohaggmark** [comment]
@garrettheel can you reproduce it with any of the other data sources?

**Comment by garrettheel** [comment]
@hugohaggmark I can try to do that, but I think it might be easier to answer the question: "is it valid for a datasource to return a series with no points?". Is there any way we can answer this?

Either way, there seems to be a regression in the React graph, though I could understand not documenting and not fixing it if the datasource was misbehaving.

**Comment by hugohaggmark** [comment]
@garrettheel you're right all data sources can return no points so we'll have a look. If you can it would be awesome if you could provide screenshots from the network tab in your browsers devtool for the data being fetched.

**Comment by garrettheel** [comment]
@hugohaggmark here are some screenshots. I've blurred out some semi-sensitive things, so let me know if there are specifics things you want to see that aren't represented here:

![image](https://user-images.githubusercontent.com/637005/69687209-1c0a6600-1090-11ea-8ce2-fd35adc6019b.png)

![image](https://user-images.githubusercontent.com/637005/69687300-6a1f6980-1090-11ea-9086-7372af02f01a.png)

**Comment by marefr** [comment]
@hugohaggmark this still needs more details or what's the status?

**Comment by hugohaggmark** [comment]
@marefr I've labeled this as a bug, don't know when we're looking into a solution.

**Comment by torkelo** [comment]
Closing this, no other reports and we will soon replace this graph component with our new one
