### ISSUE TITLE
Allow anonymous access only from specific IPs

### ISSUE THREAD

**Issue by oryagel** [grafana/grafana#2057]
Hi,

I want to allow anonymous access in order to make Grafana more user friendly.
The thing is that I don't want to allow anonymous access from everywhere, just from specific IPs.
Can it be done?

Another option, is to create two instances of Grafana that use the same DB.
Each will run on different port and I will filter access by IP with firewall.
Will it work?

Thanks

**Comment by torkelo** [comment]
Yes, you can can do this with any firewall software

**Comment by oryagel** [comment]
Hi,
So I'm trying to open use the same sqlite DB with two different Grafana instances.
How can I set an absolute path for the DB?
I don't want it to be relative to the data_path, because, the second Grafana instance will run from a different path with different custom.ini

BTW, I'm on Windows :(

**Comment by torkelo** [comment]
you cant use the same db from two grafana instances running at the same time.
