### ISSUE TITLE
Grafana 6.4.4 and elastic bug with entry "-" 

### ISSUE THREAD

**Issue by fredbcode** [grafana/grafana#20571]
Hello,
I'm seeing a wrong interpretation of "-" With grafana and elastic 
In query I'm using Terms and hostname, if the hostname contains "-" like "my-server", the legend is cut in two       

Current
- my 0
- server 0 

![elastic1](https://user-images.githubusercontent.com/5287473/69363679-36f46900-0c91-11ea-8f06-37dd62e84dd0.png)

**Comment by marefr** [comment]
Please include 
**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by fredbcode** [comment]
Hum I saw that Elastic cluster version is 4.4, sorry ...

Next week I will test the same entries with a 7.4.2 to confirm (or not) that this behaviour is only with a deprecated version 

- Grafana 6.4.4
- Elastic
- Docker/Ubuntu
- Firefox 70.0.1

**Comment by fredbcode** [comment]
I confirm bug with 4.4 only
