### ISSUE TITLE
Fixate Query to top of Explore view

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#20586]
**What would you like to be added**:
In the Explore view, I'd like to have the query field fixed to the top of my screen. This may be a toggle instead of an always-on.

**Why is this needed**:
It happens regularly that I'm exploring the table of some query and notice some data that I would like to inject into my query.  Now I have to scroll up and start changing the query, while I am doing that it looks like I need more information and have to scroll down again and hope to find it back.

**Comment by hugohaggmark** [comment]
Thanks @Duologic for contributing with this, just out of curiosity do you know that you should be able to filter the query (depends on datasource I think) directly by clicking cells in table?

**Comment by Duologic** [comment]
I did not know that, interesting.

I believe that my request still stands, however I need to find another usecase as an example. 🤔

**Comment by gelicia** [comment]
We are not planning on changing the explore layout at this time. If we would like to continue talking about this, let's create a [discussion](https://github.com/grafana/grafana/discussions) about it so we can prioritize it with our other work.
