### ISSUE TITLE
link param different than before

### ISSUE THREAD

**Issue by welyss** [grafana/grafana#20585]
**What happened**:
param which passed in to new dashboard is different than before, for example: `'` will become to `&#39;`
**What you expected to happen**:
param same as before
**How to reproduce it (as minimally and precisely as possible)**:
using `${__cell}` in Table Panel and the cell contains `'`, my case is:
url:
`d/7hd1PFbZz/mysql-slowlog-copy?var-sqltext=${__cell}`
and current cell is:
`select S_INFO_WINDCODE securityCode, S_INFO_NAME securityName, substring_index(S_INFO_WINDCODE, '.', -1) exchange from cbonddescription where (B_INFO_DELISTDATE is null or B_INFO_DELISTDATE >= sysdate()) order by S_INFO_WINDCODE`
because new dashboard var received as
`select S_INFO_WINDCODE securityCode, S_INFO_NAME securityName, substring_index(S_INFO_WINDCODE, &#39;.&#39;, -1) exchange from cbonddescription where (B_INFO_DELISTDATE is null or B_INFO_DELISTDATE >= sysdate()) order by S_INFO_WINDCODE`
then my es query can't work correctly
**Anything else we need to know?**:
I'm using table panel to display mysqlslow log, and datasource from elasticsearch, and link into a detail full sqltext dashboard table panel with raw json format from a sqltext shortcut in cell, if there are any other way to implement, it will be helpful!!! thanks very much

**Environment**:
- Grafana version: v5.2.2
- Data source type & version: elasticsearch v5.6
- OS Grafana is installed on: centos6
- User OS & Browser:
- Grafana plugins: table
- Others:

**Comment by hugohaggmark** [comment]
Would this help?  https://grafana.com/docs/reference/templating/#percentencode

**Comment by welyss** [comment]
thank for help!it works!but percentencode not work, glob works.

**Comment by welyss** [comment]
Sorry, I try another sql, then error again.

**Comment by hugohaggmark** [comment]
@welyss can you please show the complete console error in Chrome devtools also the error sql text is that something new, doesn't seem like the original sql posted in this issue?

**Comment by welyss** [comment]
Hi, @hugohaggmark
Thanks for reply
there is no error in Chrome devtools. for browser, it is ok.
yes, first time i try the original sql with `${__cell}`, and sql text contains `'` not works.
second time i try the original sql with `${__cell:glob}`, and sql text contains `'` works.
third time i try the new sql with `${__cell:glob}`, and new sql text contains `%Y-%m-%d`, then new dashboard which using parsed value of variable can't show correctly.
Sorry, i don't know how to check the value of variable which passed to new dashboard, is there any way to check what the real value of variable `${__cell}` was passed to the new dashboard.
I guess the reason is `%` maybe parsed to any other character

**Comment by hugohaggmark** [comment]
@welyss  for questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/). I'm gonna close this for now but we can reopen this issue if need arises.

All the best

**Comment by welyss** [comment]
ok
