### ISSUE TITLE
Graph: Support 'Fill below'  when using log scale

### ISSUE THREAD

**Issue by amadeuszkryze** [grafana/grafana#20594]
**What happened**:
Chart 'graph' is not showing lines properly in log2 view while lines are in 'Fill below' mode to each other.

**What you expected to happen**:
Chart looks perfectly fine as in linear mode.

**How to reproduce it (as minimally and precisely as possible)**:
Have one simple metrics: `node_load1` and two queries on it:
- `max(node_load1{})` as 'MAX 1m'
- `min(node_load1{})` as 'MIN 1m'
then in 'Visualization' tab create 'series override' with related to 'MAX 1m':
- Fill below to: MIN 1m
Global 'mode options' in Visualization:
- Fill: 0
- Line Width: 0

And finally if 'MIN 1m' goes to `0` value, line is being drawn in the middle of chart:
![image](https://user-images.githubusercontent.com/37712172/69427363-b46eb680-0d2f-11ea-9735-9f00fe55640f.png)
or goes to `1` value:
![image](https://user-images.githubusercontent.com/37712172/69427972-77ef8a80-0d30-11ea-984a-330481eb2e4d.png)

**Anything else we need to know?**:
None.

**Environment**:
- Grafana version: Grafana v6.4.4 (092e514)
- Data source type & version: Builtin Prometheus
- OS Grafana is installed on: Docker image (official)
- User OS & Browser: MacOS & Windows / Chrome & Firefox & Safari
- Grafana plugins: None related.
- Others: None.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
