### ISSUE TITLE
Azure Monitor - $__contains macro not handling 'All' as documented

### ISSUE THREAD

**Issue by afscrome** [grafana/grafana#20596]
**What happened**:

When using the `$__contains(...)` macro with Azure Log Analytics, the resultant query is not handling a variable set to `All` as documented.  The help says

>` $__contains(aColumn, $myTemplateVar) -> aColumn in ($myTemplateVar)`
>If using the All option, then check the Include All Option checkbox and in the Custom all value field type in: all. **If All is chosen -> 1 == 1**

However it appears that `All` just expands all possible values - i.e. `aColumn in ('A','B','C', ... 'N')`

**What you expected to happen**:

When a variable has value 'All', the macro should resolve to `1 == 1` as described in the documentation.  (or for the documentation should be updated to correctly describe the behaviour)

**How to reproduce it (as minimally and precisely as possible)**:

Sample Query:
```
datatable(FirstName:string, Demise:string) [
	"Catherine", "Divorced",
	"Anne", "Beheaded",
	"Jane", "Died",
	"Anne", "Divorced",
	"Catherine", "Beheaded",
	"Catherine", "Survived"
] | where $__contains(Demise, $Demise)
```

Variable setup:
![image](https://user-images.githubusercontent.com/289860/69429101-b71add00-0d2a-11ea-92f8-532e51f0d6ac.png)

Results:
![image](https://user-images.githubusercontent.com/289860/69429193-edf0f300-0d2a-11ea-8983-d5e2b57ed09c.png)

**Environment**:
- Grafana v6.4.3 (3a2bfb7)
- Azure Monitor 0.3.0

**Comment by papagian** [comment]
In Variables -> Edit page you need also to set `Custom all value` to `all`
