### ISSUE TITLE
[InfluxDB] Full query support?

### ISSUE THREAD

**Issue by renan-** [grafana/grafana#2059]
Hi,

I'm currently working on a project involving Grafana and InfluxDB 0.9
I want to retrieve series holding same measurements but with different retention policies. As stated in InfluxDB 0.9 doc,

A query in InfluxDB can have multiple statements separated by semicolons. For example:
```
SELECT mean(value) from cpu
WHERE time > now() - 1d
GROUP BY time(10m);
SELECT mean from "hour_summaries".cpu
WHERE time > now() - 7d
```

Unfortunately, Grafana doesn't seem to have the same definition of a query. In fact it is not possible to have a query with several statements because $timeFilter and $interval are only replaced once.
Is there a way to accomplish what I'm trying to do in another way ?

Thanks for your time

**Comment by torkelo** [comment]
You have a button named "Add query" to the right where you can add another query

**Comment by renan-** [comment]
Thank you for the tip but I'm not a blind nor a fool and moreover that's not what I'm trying to achieve.
I do not want to have multiple lines because the measurements, even if these are held in different shards (recently renamed to retention policies), are the same (e.g. mean response time for last week, last month, last year, and so on). I guess it's not possible then. I hope you will read InfluxDB docs and understand what a query is. Thanks for your work on Grafana anyways.
