### ISSUE TITLE
Explore: Appending (?i) to logQL query when adding filtering

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#20591]
**What happened**:
When entering query `{app="myapp"} debug` and adding filter trough log row labels, char `(?i)` is appended before `chunk` which looks weird, resulting in `{app="myapp",myfilter="some filter value"} (?i)debug` 

**What you expected to happen**:
Resulting query should be without `(?i)` -> `{app="myapp",myfilter="some filter value"} chunk` 

**How to reproduce it (as minimally and precisely as possible)**:
1. In Explore, enter a query like {app="myapp"} debug
2. Add a filter from log row details
3. Resulting in `{app="myapp",myfilter="some filter value"} (?i)debug` 

**Anything else we need to know?**:
I have looked into it, and it seems that adding of (i) was created on purpose [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/query_utils.ts#L16) . Removing of `${caseSensitive}`in `if (!regexp.startsWith(caseInsensitive)) { regexp = '${caseInsensitive}${regexp}'; }` solves the problem. However, I am not sure what is the purpose of this and if removing would  result in any errors/bugs.

**Comment by davkal** [comment]
This needs Loki pre-1.0 to repro.
