### ISSUE TITLE
Alert value does not get updated in the gui unlike the api payload

### ISSUE THREAD

**Issue by raul1991** [grafana/grafana#20599]
**What happened**:
Even though the dashboard api shows the updated alert evaluator param, the gui still shows the older value.

**What you expected to happen**: The gui reflects the new alert value.

**How to reproduce it (as minimally and precisely as possible)**:
- Set X as evaluator param in the alert.
- Update the dashboard using /api/dashboard/db with newer threshold value.
- Now go to the alert menu of a panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1-beta
- Data source type & version: prometheus
- OS Grafana is installed on: docker/ubuntu 18
- User OS & Browser: firefox latest
- Grafana plugins: 
- Others:

**Comment by papagian** [comment]
Updating alert rules via the dashboard API call is not supported.

**Comment by raul1991** [comment]
Is there a way to accomplish this ?

**Comment by papagian** [comment]
You can update the threshold value and save the dashboard using the GUI.
