### ISSUE TITLE
Docker version latest points to old version (6.3.7) instead of 6.4.4

### ISSUE THREAD

**Issue by Rumbelstilzchen** [grafana/grafana#20606]
After updating from docker image latest (6.4.2) grafana reported as 6.3.7

Docker version latest points to old version (6.3.7) instead of 6.4.4
![grafik](https://user-images.githubusercontent.com/8233580/69459157-6d091a00-0d71-11ea-8f6a-a9a0859f0893.png)

**Comment by aknuds1** [comment]
Thanks for reporting this, we will look into it.

**Comment by aknuds1** [comment]
It's been fixed. Thanks again!

**Comment by marefr** [comment]
We should fix this for arm images as well

**Comment by aknuds1** [comment]
@marefr I rectified the latest tag for the ARM images, can you confirm?

**Comment by marefr** [comment]
Yeah works for now, but manifest in grafana/grafana is not updated so you cannot do `docker pull grafana/grafana:latest` from ARM and get correct image. But we'll fix that by releasing 6.4.5 soon followed by 6.5.0 so closing this for now.
