### ISSUE TITLE
graph sharing: replace "now" with absolute time references

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#2060]
On the graph sharing panel, the generated link should have absolute time references instead of references to "now" in the from/to parameters (or this behavior should be configurable). For example, if the link is posted to a chat channel, then a relative time reference means the link will show different data depending on when in the future a person accesses the link in the chat log. The person sharing the link to a chat channel likely wants to share what the graph currently looks like, not what it will look like in the future.

To reproduce: Share a graph with relative time references and reload it every few minutes, the graph will change.

**Comment by tdyas** [comment]
Or is this use case what the "Snapshot Sharing" feature is for?

**Comment by torkelo** [comment]
@tdyas maybe you are right, the share link should always turn the relative time  range into absolute from/to

**Comment by tdyas** [comment]
Thanks!
