### ISSUE TITLE
Application Insights error "Unknown macro timeFilter" on 6.5.0-beta1

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#20608]
**What happened**:
Application Insights query failing after upgrade to 6.5.0-beta1 with an "invalid time value" message.

Browser console error:
`angular.js:12845 POST https://xxxxxxxxx/grafana/api/tsdb/query 400 (Bad Request)`

Query Inspector:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1574464598490",
      "to": "1574468198491",
      "queries": [
        {
          "type": "timeSeriesQuery",
          "raw": false,
          "appInsights": {
            "rawQuery": true,
            "rawQueryString": "exceptions\r\n| where $__timeFilter() | where client_Type == \"PC\" | summarize count() by problemId, outerMessage",
            "timeColumn": "count_",
            "valueColumn": "outerMessage",
            "segmentColumn": "problemId"
          },
          "refId": "B",
          "intervalMs": 5000,
          "datasourceId": 6,
          "queryType": "Application Insights"
        }
      ]
    }
  },
  "response": {
    "results": {
      "B": {
        "error": "invalid time value",
        "refId": "B",
        "meta": {
          "columns": [
            "problemId",
            "outerMessage",
            "count_"
          ]
        },
        "series": null,
        "tables": null,
        "dataframes": null
      }
    },
    "message": "invalid time value"
  }
}
```

Grafana.log:
```
t=2019-11-23T00:15:41+0000 lvl=eror msg="Metric request error" logger=context userId=2 orgId=1 uname=xxxx@xxxx.com error="Unknown macro timeFilter"
```

**What you expected to happen**:
Return a table of exceptions from Azure App Insights

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/1184220/69468792-7b613100-0d85-11ea-9f1a-ac18c4374678.png)

**Anything else we need to know?**:

**Environment**:
Grafana version: 6.5.0-beta1
Data source type & version: ElasticSearch
OS Grafana is installed on: Ubuntu 18.04
User OS & Browser: Win10 Chrome
Grafana plugins:
agenty-flowcharting-panel @ 0.5.0
blackmirror1-singlestat-math-panel @ 1.1.7
briangann-datatable-panel @ 0.0.9
btplc-trend-box-panel @ 0.1.9
flant-statusmap-panel @ 0.1.1
goshposh-metaqueries-datasource @ 0.0.3
grafana-clock-panel @ 1.0.3
grafana-piechart-panel @ 1.3.9
grafana-worldmap-panel @ 0.2.1
jdbranham-diagram-panel @ 1.6.1
michaeldmoore-multistat-panel @ 1.2.5
natel-influx-admin-panel @ 0.0.5
natel-plotly-panel @ 0.0.6
sankey-panel @ 1.1
savantly-heatmap-panel @ 0.2.0
vonage-status-panel @ 1.0.9
yesoreyeram-boomtable-panel @ 1.3.0

**Comment by marefr** [comment]
Works as expected for me. Seems like you're trying to use `_count` as `timeColumn`. If using timestamp as timeColumn it works for me:
![image](https://user-images.githubusercontent.com/1668778/69661708-2b36e700-1083-11ea-8bcb-7e6e6b5df9b9.png)

**Comment by marefr** [comment]
Maybe was too fast to close. You're trying to get tabular data and display in table panel? Going to verify if this works in 6-4.5.

**Comment by marefr** [comment]
Works in 6.4.5:
![image](https://user-images.githubusercontent.com/1668778/69662856-6c2ffb00-1085-11ea-9be2-5750c2b85f67.png)

![image](https://user-images.githubusercontent.com/1668778/69662863-6fc38200-1085-11ea-9911-2930b4238dd1.png)

**Comment by bhozar** [comment]
@marefr Previously is was returning results as a table with problemId, outerMessage and a count. This allowed me to see a more log-like view of the App Insights exceptions and it was working in earlier versions.

If I use the Azure AI interface the following query works with no issue to output a table:
```
exceptions
| where timestamp > ago(3h)  | where client_Type == "PC" | summarize count() by problemId, outerMessage
```

Panel type and settings:
![image](https://user-images.githubusercontent.com/1184220/69740302-1749be80-1131-11ea-850f-a6d662273d72.png)

Here's the panel JSON:
```
{
  "datasource": "$datasource",
  "columns": [],
  "fontSize": "100%",
  "gridPos": {
    "h": 10,
    "w": 24,
    "x": 0,
    "y": 34
  },
  "id": 27,
  "links": [],
  "options": {},
  "pageSize": 100,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "alias": "ProblemID",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "mappingType": 1,
      "pattern": "Metric",
      "thresholds": [],
      "type": "string",
      "unit": "short"
    },
    {
      "alias": "Count",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 0,
      "mappingType": 1,
      "pattern": "Time",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    },
    {
      "alias": "Message",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "mappingType": 1,
      "pattern": "Value",
      "preserveFormat": false,
      "sanitize": false,
      "thresholds": [],
      "type": "string",
      "unit": "short"
    },
    {
      "alias": "",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "decimals": 0,
      "pattern": "/.*/",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "appInsights": {
        "aggOptions": [
          "sum"
        ],
        "aggregation": "sum",
        "alias": "{{metric}} {{groupbyvalue}}",
        "metricName": "requests/failed",
        "rawQuery": true,
        "rawQueryString": "exceptions\r\n| where $__timeFilter() | where client_Type == \"PC\" | summarize count() by problemId, outerMessage",
        "timeGrainType": "auto",
        "dimension": "request/name",
        "timeGrain": "auto",
        "timeColumn": "count_",
        "valueColumn": "outerMessage",
        "segmentColumn": "problemId",
        "dimensions": [
          "request/source",
          "request/name",
          "request/urlHost",
          "request/urlPath",
          "request/success",
          "request/resultCode",
          "request/performanceBucket",
          "operation/name",
          "operation/synthetic",
          "operation/syntheticSource",
          "user/authenticated",
          "application/version",
          "client/type",
          "client/model",
          "client/os",
          "client/city",
          "client/stateOrProvince",
          "client/countryOrRegion",
          "client/browser",
          "cloud/roleName",
          "cloud/roleInstance",
          "customDimensions/{OriginalFormat}",
          "customDimensions/Category",
          "customDimensions/LogLevel",
          "customDimensions/TriggerReason",
          "customDimensions/FullName",
          "customDimensions/Succeeded",
          "customDimensions/EndTime"
        ]
      },
      "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\nUsage                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": ""
      },
      "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "metricNamespace": "select",
        "top": "10",
        "aggOptions": [],
        "timeGrains": []
      },
      "hide": false,
      "queryType": "Application Insights",
      "refId": "B"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Server Exception Log",
  "transform": "timeseries_to_rows",
  "type": "table",
  "scopedVars": {
    "datasource": {
      "text": "AppInsightsDS",
      "value": "AppInsightsDS",
      "selected": true
    }
  }
}
```

**Comment by bhozar** [comment]
> Works in 6.4.5:
> ![image](https://user-images.githubusercontent.com/1668778/69662856-6c2ffb00-1085-11ea-9be2-5750c2b85f67.png)
> 
> ![image](https://user-images.githubusercontent.com/1668778/69662863-6fc38200-1085-11ea-9911-2930b4238dd1.png)
> 
> There's a timeseries query being made so not sure the existing support in 6.4.5 makes sense selecting a non-timestamp field as x-axis.
> 
> How do you use the result @bhozar like panel type and settings?

@marefr I just tried to replicate your exact query that you show as working in 6.4.5, but I am using 6.5.x.

```
exceptions 
| where timestamp > ago(1d)
| summarize count() by severityLevel 
```
or
```
exceptions 
| where $__timeFilter()
| summarize count() by severityLevel 
```

I get the same "Invalid time value" error.

**Comment by marefr** [comment]
@ChadNedzlek you implemented #19381. Have any idea what code wasn't converted to the backend that supported above?

**Comment by ChadNedzlek** [comment]
I didn't think the previous code supported tables... none of the code I deleted from the typescript appeared to be returning tables, so I didn't make the backend support them either. Especially since "timeColumn" was a required value.

And none of the existing tests tested for table data either (since I didn't break any of them when I made my change)

It's possible table returns... accidentally worked before, where the typescript thought it was returning a timeseries, but some other part actually rendered it as a table.  It's hard to tell, because the typescript uses "any" everywhere, so there is no way to actually follow where code is going or what pieces of code expect to be getting which values.

I'm sorry that I broke this, but I definitely didn't make the go backend return table data. It's a very different format of returns from the backend data provider.

**Comment by BLWood** [comment]
I seem to be having a similar issue when using the join operator with equality by value (`$left.LeftColumn == $right.RightColumn`). The logs say `Unknown macro left`.

**Comment by Projectsolo** [comment]
Hi, I was informed there was a github post so I'm posting what I put in the Grafanaforum here:
_Hi there!
Last Monday I created a dashboard that worked great. However, after the last update you guys pushed it stopped working and Grafana is now trying to parse the browser names as dates despite me setting the value as “String” and not “Date”.

The source I’m using is Application Insights and the query works perfectly in Azure Portal, but like I said, stopped working after Monday update last week._

So, I have a bunch of tables that stopped working after this version, that worked previously.
I get error messages such as "parsing time "Chrome 77.0" as INSERT TIMESTAMP: Cannot parse "Chrome 77.0" as 2006"

**Comment by sunker** [comment]
We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics). I'm closing this issue now, but feel free to reopen if you feel the need to.
