### ISSUE TITLE
Grafana Elastic Search Regex query doesn't work

### ISSUE THREAD

**Issue by iamdempa** [grafana/grafana#20605]
Hi,

I am getting logs from `Elasticsearch` and I need to filter out only specific logs using **Grafana regex commands**.

This below is a part of of how my logs looks like:

`https://beta-qa.pearson.com/iie-api/courses/5daa3022e4b0ef7dce37acec/assignments`

`https://beta-qa.pearson.com/iie-api/courses/5daa3022e4b0ef7dce37acec/assignments/984fa00d-d002-4826-80f4-76d1267e3aaa`

What I want is to only get the string that ends with assignment

regex I am using is: egex pattern: data.URL:"*/.[assignments]/"

**PROBLEM**: This regex doesn’t wrk properly as it outputs logs ends with `/assignments` and ends with `assignments/<some-id>`

What I want is:

**1. Regex pattern to get logs only ends with assignments (i.e. /assignments)**
**2. Regex pattern to get logs that ends with assignments followed by some id (i.e. /assignments/1qa3feaa**

Can someone please provide a solution for this?

**Comment by iamdempa** [comment]
@aknuds1 can you please look into this?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Seems like you should look for lucene syntax in elasticsearch documentation.
