### ISSUE TITLE
grafana should not appear in data source list

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2061]

**Comment by torkelo** [comment]
which one?

**Comment by liyichao** [comment]
This is just a test data source that generates random walk series. If this is your only data source open the left side menu and navigate to the data sources admin screen and add your data sources (you need to be logged in to do this). You can change data source using the button to the left of the Add query button.

**Comment by torkelo** [comment]
I meant which data source list, the panel dropdown or when you add a panel? hm.. not sure if this is worth it right now,

**Comment by liyichao** [comment]
In the graph edit, there is a data source dropdown.

**Comment by rolandovillca** [comment]
I am using 2.1.3 version, and i cannot add more data source..... following annoying message is displayed only:

This is just a test data source that generates random walk series. If this is your only data source open the left side menu and navigate to the data sources admin screen and add your data sources (you need to be logged in to do this). You can change data source using the button to the left of the Add query button.
