### ISSUE TITLE
Grafana dashboards automatically signs out 

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#20612]
STOP -- PLEASE READ!

GitHub is not the right place for questions and support requests.

Please ask questions on our community site: [https://community.grafana.com/](https://community.grafana.com/)

Every few minutes or under load when more users are signed-in using the same credentials - grafana keeps signing out all the users with a popup to (cancel or leave) -- and shows ERROR message -- unauthorized or related to authentication,.... 

Version 6.x

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Maybe related to #15316
