### ISSUE TITLE
How to get Alerts in Azure Monitor to Grafana

### ISSUE THREAD

**Issue by prakashraaj046** [grafana/grafana#20611]
I’ve Grafana installed in Azure VM and have connected it to Azure monitor data source, I was able to get metrics and query from log analytics workspace and Application insights.
How do i get the alert details?

![image](https://user-images.githubusercontent.com/54060781/69482577-37346600-0e43-11ea-96ba-5c2b29952e7c.png)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
