### ISSUE TITLE
Change of any value in any panel results in Unsaved Changes prompt. : 6.5.0 b1

### ISSUE THREAD

**Issue by EorEquis** [grafana/grafana#20610]
**What happened**:

As soon as any value, in any panel, on any dashboard changes, attempting to navigate away from that dashboard prompts the user to save his/her changes to the dashboard, even though no changes were made.

**What you expected to happen**:

Not to be prompted to save changes.

**How to reproduce it (as minimally and precisely as possible)**:

Log in as a user with permission to change dashboards. Open any dashboard. Wait for the autorefresh period to expire, and any value in any panel of any type to change. Attempt to navigate away from the dashboard to any other dashboard or menu item.

**Anything else we need to know?**:

I’ve tested this on dashboards containing graphs, both D3 and default gauges, ImageIt, and single stat panels. All seem to trigger the behaviour.

**Environment**:
- Grafana version: 6.5.0 beta 1
- Data source type & version: MySQL 8.0.18
- OS Grafana is installed on: Windows 10 Home
- User OS & Browser: Windows 10 Home, Chrome 78.0.3904.97
- Grafana plugins: Default plus D3 Gauge, ImageIt

**Comment by marefr** [comment]
Please save the dashboard. Probably due to Grafana schema version change. After you visit a saved dashboard are you still getting unsaved changes prompt?

**Comment by EorEquis** [comment]
Yes.  It continues to happen despite trying the following things 

- Saving the dashboard, and returning to it
- Saving the dashboard manually, and then waiting for next data refresh
- Logging out and back in
- Hard browser refresh
- Restarting grafana service
- Rebooting client and server computer
- Completely deleting the dashboard and all panels, and recreating from scratch.

**Comment by marefr** [comment]
@EorEquis Hopefully something fixed in master/upcoming 6.5 stable. If you check dashboard versions and compare latest and version before, what's the difference? If you can include your dashboard json that could also help. Thanks

**Comment by EorEquis** [comment]
Was previously 6.4.4, don't recall seeing the issue there (but admittedly, I was even more of a newb then than I am now).  I changed to 6.5.0 b1 because of #20379.

I've placed dashboard json from one of my dashboards on pastebin [here](https://pastebin.com/xV1mUFMn), but can tell you it's happening on all 5 dashboards I've built, and 2 I've added from grafana (my2 mysql monitoring)

**Comment by marefr** [comment]
Are you using the ierosavi-imageit-panel plugin in all of your dashboards? Could be related.

As I wrote earlier, would be interesting to see what difference you get when comparing two dashboard versions after you've saved it. For example see my test output:
![image](https://user-images.githubusercontent.com/1668778/69502145-2b60a680-0f0c-11ea-8695-9ad1df80418c.png)

**Comment by EorEquis** [comment]
> Are you using the ierosavi-imageit-panel plugin in all of your dashboards? Could be related.

Bingo, that was it.  Out of laziness, I was using it to display some manufacturer logos since it handles sizing so easily. 

Checking versions as you suggested demonstrated a change of "value" and "uncache" in that panel.

Disabled those, problem solved.

Sorry to clutter up the bug reports with what turned out not to be a bug...just hadn't had any input on the community pages or grafana subreddit, was at my wits' end.

Thanks for the help!
