### ISSUE TITLE
Explore: Expanding LogRow after Live session doesn't show labels correctly

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#20628]
**What happened**:
Expanding LogRow after Live session doesn't show the details for that log row correctly.

**What you expected to happen**:
Expanding LogRow after a Live session should show the same labels as before Live session.

**How to reproduce it (as minimally and precisely as possible)**:
1. Goto Explore in Grafana
2. Enter any Loki query for a Loki data source that supports streaming, preferably a query that will return results during Live session.
3. Expand any LogRow and notice the labels in the expanded section.
4. Turn on Live session.
5. Wait for a result.
6. Turn off Live session.
7. Expand any LogRow and notice that the labels in the expanded section are no longer the same as before Live session. 👎 
![image](https://user-images.githubusercontent.com/562238/69537566-af547600-0f80-11ea-8f59-61b46738fc06.png)
8. Hit the `Run Query` button
9. Expand any LogRow and notice that the labels in the expanded section are the same as before Live session. 🆗 

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.5.0-beta1
- Data source type & version: Loki
- OS Grafana is installed on: docker
- User OS & Browser: Chrome
- Grafana plugins: none
- Others:

**Comment by ivanahuckova** [comment]
This is probably going to be fixed, by fixing: https://github.com/grafana/grafana/issues/19954.
