### ISSUE TITLE
Log panel: elasticsearch - multiselect variable Interpolation incorrect

### ISSUE THREAD

**Issue by raiviskrumins** [grafana/grafana#20621]
**What happened**:
When using log panel with elasticsearch data source and multivalue variable, it is interpolated incorrectly.
instead of this result: https://grafana.com/docs/reference/templating/#lucene
i see this result: https://grafana.com/docs/reference/templating/#glob

**What you expected to happen**:
Multiple value variable should be interpolated in this format: https://grafana.com/docs/reference/templating/#lucene

**How to reproduce it (as minimally and precisely as possible)**:
Create a new log panel
Use elasticsearch  as data source
Add some multi value variable
use this variable in your query
try to select multiple values for variable

**Anything else we need to know?**:
![Screenshot from 2019-11-25 09-35-31](https://user-images.githubusercontent.com/2749851/69521716-4b25b800-0f68-11ea-8e63-790e427bcca0.png)

**Environment**:
- Grafana version: v6.5.0-beta1 (commit: ab9c0da)
- Data source type & version: elasticsearch 7.4
- OS Grafana is installed on: Docker image: grafana/grafana:6.5.0-beta1
- User OS & Browser: Linux & Chrome
- Grafana plugins: GF_INSTALL_PLUGINS: grafana-piechart-panel

**Comment by torkelo** [comment]
that is super strange

the same querystring interpolation code (exact same line) is used for normal metric queries and that interpolates correctly. 
https://play.grafana.org/d/000000015/elasticsearch-templated?orgId=1&fullscreen&edit&panelId=1&var-source=All&var-host=server%2221&var-host=server-5

**Comment by torkelo** [comment]
Problem is here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/query_builder.ts#L401

that should use querystring being passed in as function arg!
