### ISSUE TITLE
Error with Debian apt repository

### ISSUE THREAD

**Issue by Pelt10** [grafana/grafana#20626]
**What happened**:
When I launch "apt update" command, I get some errors, let's check :  
![image](https://user-images.githubusercontent.com/7582586/69535441-3a7f3d00-0f7c-11ea-845e-f470ff301930.png)
I navigate to : https://packages.grafana.com/oss/deb, from firefox, I get this response : 
![image](https://user-images.githubusercontent.com/7582586/69535555-803c0580-0f7c-11ea-89eb-ef549933ef6e.png)

**Environment**:
- Grafana version: 6.4.4
- OS Grafana is installed on: Debian Stetch
- User OS & Browser: Debian Buster and Firefox 69

Thank's for your help

**Comment by xlson** [comment]
Thanks for reporting this issue. We had some issues with the cache for our apt repository on Monday. Could you try updating again?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
