### ISSUE TITLE
Unlabeled icons in Explorer view

### ISSUE THREAD

**Issue by pstibrany** [grafana/grafana#20623]
There is no description or labels on some icons in Explorer view in new 6.5.0-beta1.

<img width="1806" alt="Screenshot 2019-11-25 at 10 51 36" src="https://user-images.githubusercontent.com/895919/69530205-f129f000-0f71-11ea-8c66-35818c7178f4.png">

It would also be nice if escape button could close this.

**Comment by marefr** [comment]
Fixed by #20485 included in 6.5 stable.
