### ISSUE TITLE
config file should reflect current options

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20622]
I confirmed with docker grafana/grafana:master (15ba745d8cf3) that the grafana config file is out of sync with the grafana binary.

IMHO it's a best practice that for any version of the binary, it comes with the config file to match.
IOW, for any revision of the git repo, whatever the code says that the binary will support, and whatever it will use as defaults, the config file in the git repo should match that.

We do this with metrictank. Every time we add or change a config flag or setting, its description or its default value in the source code, we update the default/sample config file to match it.

Grafana doesn't seem to do this.  For example I know I could add a "[feature_toggles]" and that it has certain values, but I don't know where I can add this section to the config file, and what the various options are I could provide.

Why is assuring constitency useful?:

* have an accurate view of what all the available options are, what they do (assuming proper comments) and what the defaults are
* when updating packages, most linux distributions have a tool to manage the config file update. if the config file for a new grafana version is properly synced, this is a good way to learn about new settings that may be useful for the deployment.
* consistency when people share config files: by having all options already in the file by default, if people enable certain options, you know you can find those options in a certain spot (otherwise they might add it at the end, etc, and diffs become needlessly convoluted)

**Comment by marefr** [comment]
I think it's just `feature_toggles` section missing from sample.ini. We always try to keep defaults.ini and sample.ini in sync.
