### ISSUE TITLE
Not Able to set default initial Values for yAxis

### ISSUE THREAD

**Issue by shaileshswapnil** [grafana/grafana#2062]
Our requirement is to set the yAxis label to default value, let's say 0 which should be the minimum. Value should not go below 0, to negative. How to achieve that? It is okay that the line of graph should be on bottom, if the data points are 0.

**Comment by torkelo** [comment]
I do not understand you. Could elaborate? You seem to talk about grid min/max (which there are options), and label? And defaults? Do you want to create default graph options that should be set when adding new graphs?

**Comment by shaileshswapnil** [comment]
yes exactly, I need to define the default values for grid min and max, while creating new graph using the script available or from the default dashboard while adding new graph in the row.

**Comment by shaileshswapnil** [comment]
yes exactly, I need to define the default values for grid min and max, while creating new graph using the script available or from the default dashboard while adding new graph in the row.

**Comment by torkelo** [comment]
ok, it not something you can do now. But a feature that allowed to to create panel templates (with default settings set) could be good. no idea when there will be time to implement that feature though.

**Comment by shaileshswapnil** [comment]
yes, it would be good if this feature will be available directly through the script. But at the same time I have fund another way to do the same thing using JSON. We already have the JSON for the dashboard including for the graph. So in the JSON we can modify "rightMin" and "leftMin" inside "grid" identifier. So once the graph is generated we can change its settings by modifying the JSON, before we could display it.

**Comment by torkelo** [comment]
for now this can be done through http API I think
