### ISSUE TITLE
Template Var e.metricsFindQuery is Not a Function

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#20636]
**What happened**: When I imported a dashboard, the template var gives _e.metricsFindQuery_ is not a function.  The data is not loaded, and the request to the server is never actually sent.  Note, this is not a problem in the dashboard I originally imported from.

**What you expected to happen**: Query would load as normal

**How to reproduce it (as minimally and precisely as possible)**: Create a basic dashboard with JSON datasource.  Then, create new installation of Grafana elsewhere, copy Grafana database, and load dashboard.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version:  JSON Datasource – a generic backend datasource 0.1.5
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows, Chrome
- Grafana plugins: JSON Datasource – a generic backend datasource
- Others: Note that this does work on original dashboard (before importing)

EDIT: I should also mention, this seems to only affect dashboard parameters, not the panels themselves.

**Comment by torkelo** [comment]
Make sure you have a datasource with the same name in the new instance

**Comment by BrandonQDixon** [comment]
I do

**Comment by torkelo** [comment]
Can you show the dashboard json?

**Comment by BrandonQDixon** [comment]
Yes, here is the dashboard json.  I've removed the panels and the query itself from the template var definition to protect private data, but what you need should still be here.  Note, MSSQLQuery is a JSON datasource I've created
`{
	"annotations": {
		"list": [{
			"builtIn": 1,
			"datasource": "-- Grafana --",
			"enable": true,
			"hide": true,
			"iconColor": "rgba(0, 211, 255, 1)",
			"name": "Annotations & Alerts",
			"type": "dashboard"
		}]
	},
	"editable": true,
	"gnetId": null,
	"graphTooltip": 0,
	"id": 42,
	"iteration": 1574692903955,
	"links": [],
	"panels": [],
	"schemaVersion": 18,
	"style": "dark",
	"tags": ["primary", "imported_enhanced"],
	"templating": {
		"list": [{
			"allValue": null,
			"current": {
				"selected": true,
				"text": "2019-11-13",
				"value": "2019-11-13"
			},
			"datasource": "MSSQLQuery",
			"definition": "",
			"hide": 0,
			"includeAll": false,
			"label": "Date",
			"multi": false,
			"name": "date",
			"options": [],
			"query": "",
			"refresh": 1,
			"regex": "",
			"skipUrlSync": false,
			"sort": 0,
			"tagValuesQuery": "",
			"tags": [],
			"tagsQuery": "",
			"type": "query",
			"useTags": false
		}]
	},
	"time": {
		"from": "now-1s",
		"to": "now"
	},
	"timepicker": {
		"refresh_intervals": ["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"],
		"time_options": ["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"]
	},
	"timezone": "",
	"title": "Coverage Dashboard",
	"uid": "pG2yIg4Wz",
	"version": 50
}`

**Comment by BrandonQDixon** [comment]
Any updates on this issue?

**Comment by marefr** [comment]
https://grafana.com/grafana/plugins/simpod-json-datasource is a community plugin. Please report your problem at https://github.com/simPod/grafana-json-datasource or try and upgrade Grafana to later version.
