### ISSUE TITLE
A triggered alert stays triggered

### ISSUE THREAD

**Issue by RefusesNames** [grafana/grafana#20634]
**What happened**:
I have alarms on several graphs. They stay in 'alert' state even though the data changed to a valid state, even though the rule test yields a positive result. This affects multiple different graphs over a period of over a month.

**What you expected to happen**:
Graph alerts reach a healthy state once the data is okay again.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start the attached docker images using docker compose. [grafana_bug.zip](https://github.com/grafana/grafana/files/3887024/grafana_bug.zip)
2. Login via "admin" and "pass"
3. Bring get an alert to trigger (I already prepare one that triggers for me)
4. Change the alert threhold to not trigger anymore.

**Anything else we need to know?**:
This might be related to [this issue](https://github.com/grafana/grafana/issues/13527).

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Prometheus 2.13.0
- OS Grafana is installed on: Docker, using `grafana/grafana:latest`
- User OS & Browser: Windows 10, Chrome (also appears in Edge)
- Grafana plugins: None
- Others:

**Comment by xlson** [comment]
I wasn't able to reproduce this using your example. I followed your guide and then updated the dashboard.json to change the threshold which changed the alert state. Maybe I'm missing something from your repro guide? When using provisioning it isn't possible to modify the threshold in grafana itself, do you by any chance copy the dashboard before changing it?

**Comment by RefusesNames** [comment]
I meant not to change the threshold in the dashboard.json, but rather edit the alert inside of Grafana UI.
>When using provisioning it isn't possible to modify the threshold in grafana itself, do you by any chance copy the dashboard before changing it?
I did not know that. You are correct, with this example I fail to reproduce the problem. I guess I will have to come back to this when I can create a minimal reproducable example.

**Comment by xlson** [comment]
@RefusesNames Please let us know if you can reproduce this issue. Alternatively, create a new issue with all the details of your setup, and we will try to identify the problem.
