### ISSUE TITLE
[Explore] UI bug when selecting dedupe option

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#20646]
![image](https://user-images.githubusercontent.com/1053421/69565545-2f7bdb00-0f83-11ea-9f0b-2a67d6168cc9.png)

**What happened**:
When selecting a dedupe option one row seems to have an issue see screenshot.

**Environment**:
- Grafana version: Grafana v6.6.0-pre (fc3be40bc0)

**Comment by aocenas** [comment]
@cyriltovena is this something that happen often? Can't seem to reproduce this so wonder if this was some temporary glitch in browser layout or something else.

**Comment by cyriltovena** [comment]
Could be I refreshed my cache and can’t repro anymore. I’ll reopen if needed.
