### ISSUE TITLE
Read configuration from external datasource

### ISSUE THREAD

**Issue by yannickkirschen** [grafana/grafana#20640]
Hello everybody,

I would love Grafana to allow reading any configuration from an external datasource (e.g. MySQL, file server, etc.).
To give an example: I regulary calculate the thresholds for several metrics in an openTSDB by using a Spark Job and write them to an external database, since I need these thresholds also in other systems. But every time the thresholds change, I have to manually update them in Grafana.

I would love my Spark Jobs to write the thresholds (and maybe other configuration) into some kind of external datasource, so that Grafana automatically reads the new values from that source.

**Comment by papagian** [comment]
@yannickkirschen 
I'm not sure that I fully understand your use case but do you think that by [provisioning datasources](https://grafana.com/docs/administration/provisioning/#datasources) would achieve what you want?
An example configuration of MySQL datasource using provisioning can be found [here](https://grafana.com/docs/features/datasources/mysql/#configure-the-data-source-with-provisioning).

**Comment by yannickkirschen** [comment]
@papagian 
Sorry that I expressed myself inaccurately.

My special use-case is the following: I have a spark job that regularly calculates the min/max value and the thresholds based on a series of data. Right now, I manually update the results of this calculation in Grafana (the red circled values on the image).

It would be cool when my spark job writes the results to *some* kind of database and Grafana automatically updates the values. I would also be satisfied when I could directly send the values to an interface provided by Grafana, if that's possible.

![sc](https://user-images.githubusercontent.com/27555431/69969794-66229a00-151d-11ea-9078-22d3a5cd2150.jpg)

The links you sent my look quite nice for other use-cases I have, but I'm not sure if they help me out with my particular issue.

I hope this is an understandable explanation of my issue :)

**Comment by torkelo** [comment]
We will allow these to be data-driven in the future

**Comment by papagian** [comment]
@yannickkirschen 
Thank you for clarifying this. Currently it is possible to define a [query variable](https://grafana.com/docs/reference/templating/#query-options) that queries a datasource and populates the variable options with the results. But unfortunately variables cannot be used for setting `min`, `max` and `thresholds` Gauge options.

An alternative would be to define a provision dashboard having a gauge panel similar to this [one](https://github.com/grafana/grafana/blob/master/devenv/dev-dashboards/datasource-testdata/new_features_in_v62.json#L364) and for `min`, `max` and `threshold` values pass [environmental variables](https://grafana.com/docs/administration/provisioning/#using-environment-variables).

**Comment by yannickkirschen** [comment]
Thank you for your support! 👍 

I have just come up with the idea that a REST interface to adjust the settings of individual metrics would be pretty cool ...
