### ISSUE TITLE
Unit is shown as "ns" in singlestat panel when choose unit as "second(s)"

### ISSUE THREAD

**Issue by zaghost** [grafana/grafana#20653]
**What happened**:
Unit is shown as "**ns**" in singlestat panel when choose unit as "second(s)"
**What you expected to happen**:
Unit is shown as "**s**"
**How to reproduce it (as minimally and precisely as possible)**:
1.create a singlestat panel
2.set Visualization->Value->unit as Time->seconds(s)
3.simplely set Query->Metrics as 0
4."0 ns" is shown in singlestat panel
**Anything else we need to know?**:
The following is OK:
When choose Time->milliseconds(ms), it shows as "0 ms"
When choose Time->nanoseconds(ns), it shows as "0 ns"
When choose Time->minutes(m), it shows as "0 min"

**Environment**:
- Grafana version: 
Grafana v6.4.4 (092e514)
hub.docker.com  grafana/grafana:6.4.4
- Data source type & version:
Prometheus 2.14.0
hub.docker.com  prom/prometheus:v2.14.0
- OS Grafana is installed on:
docker 17.04 in SLES 12
- User OS & Browser:
Windows 10, Firefox 70.0.1 (64 bit)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
unable to replicate this in 6.5, think this has been fixed
