### ISSUE TITLE
Metrictank dashboard(s) in graphite datasource

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20658]
Can we include https://grafana.com/grafana/dashboards/279 in the graphite datatosource dashboard tab?
We have a few other dashboards also that we can clean up a bit, upload to grafana.com and distribute via the datasource plugin. I suppose once we see a PR to add one dashboard, from then one we will be able to file future PR's with more dashboards and/or dashboard updates.

BTW how does this work? does it pull the dashboard from grafana.com, or does the plugin have a local copy such that it doesn't require internet connectivity to install the dashboard?

**Comment by marefr** [comment]
Sure, here's a recent PR that added dashboards for the CloudWatch datasource https://github.com/grafana/grafana/pull/20486/files

If you want to give it a go.
