### ISSUE TITLE
Having been password reset user is redirected to page with error

### ISSUE THREAD

**Issue by mifarse** [grafana/grafana#20663]
**What happened**:
Having reset password user is redirected to the page where error occurs. [Screenshot](https://imgur.com/a/zdFqCzr)

**What you expected to happen**:
User should be redirected to login page.

**How to reproduce it (as minimally and precisely as possible)**:
We figured out that the error appears exactly after Grafana v.6.4.2. v.6.4.1 doesn't reproduce this kind of error.

**Anything else we need to know?**:
It doesn't depend on browser.

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: -
- OS Grafana is installed on: Ubuntu 18.04.3
- User OS & Browser: Windows 10, Firefox 70.0.1
- Grafana plugins: 
- Others:

**Comment by marefr** [comment]
Confirmed bug in current master (514f2be)

Also only new password/confirm password fields should be seen and not the user field:
![image](https://user-images.githubusercontent.com/1668778/69652705-5f55dc00-1072-11ea-8ebe-94fe633226d7.png)
