### ISSUE TITLE
Grafana doesn't obey root_url settings when redirecting after a successfull login.

### ISSUE THREAD

**Issue by zerthimon** [grafana/grafana#2066]
It redirects to a '/' instead of what is configured in the 'root_url'

**Comment by torkelo** [comment]
@zerthimon are you sure you have configured nginx or apache reverse proxy correctly? Are you using version 2.0.2? a lot of poeple have put grafana behind reverse proxy and added sub url to root_url so its strange that no one has reported it before

**Comment by zerthimon** [comment]
@torkelo Yep, I'm using grafana 2.0.2

My Nginx is configured this way:
```
    location /grafana/ {
        proxy_set_header Host $host;
        rewrite ^/grafana/(.*) /$1 break;
        proxy_pass http://localhost:3000;
    }
```

And the root_url is:
```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
```

I'm seeing this issue after signing out and logging into grafana. Everything else works fine (i just have to fix the uri in browser from '/' to '/grafana/' after logging in).

Here are the access log (see the "GET /" in the last line):
```
zzz.zzz.zzz.zzz - graphite [28/May/2015:16:22:28 +0300] "GET /grafana/login HTTP/1.1" 200 997 "https:/xxx.xxx.xxx/grafana/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
zzz.zzz.zzz.zzz - graphite [28/May/2015:16:22:44 +0300] "POST /grafana/login HTTP/1.1" 200 41 "https://xxx.xxx.xxx/grafana/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
zzz.zzz.zzz.zzz - graphite [28/May/2015:16:22:44 +0300] "GET / HTTP/1.1" 200 542 "https://xxx.xxx.xxx/grafana/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
```

**Comment by torkelo** [comment]
@zerthimon not sure about the rewrite rule, this works for me:

location /grafana2/ {
proxy_pass http://localhost:3000
}

**Comment by zerthimon** [comment]
What do you have in the root_url ?
When I have:
```
    location /grafana/ {
        proxy_pass http://localhost:3000;
    }
```
I'm getting only this:
```
{{alert.title}}
```
and a bunch of 404's in /var/log/grafana/grafana.log
```
2015/05/28 17:36:03 [I] ESC[1;31mCompleted /grafana/ 404 Not Found in 7.841934msESC[0m
2015/05/28 17:36:03 [I] ESC[1;31mCompleted /grafana/css/grafana.dark.min.5aa0b879.css 404 Not Found in 1.044431msESC[0m
2015/05/28 17:36:03 [I] ESC[1;31mCompleted /grafana/app/app.6e379bdb.js 404 Not Found in 1.025579msESC[0m
2015/05/28 17:36:12 [I] ESC[1;31mCompleted /grafana/ 404 Not Found in 3.022672msESC[0m
2015/05/28 17:36:12 [I] ESC[1;31mCompleted /grafana/app/app.6e379bdb.js 404 Not Found in 3.327384msESC[0m
2015/05/28 17:36:12 [I] ESC[1;31mCompleted /grafana/css/grafana.dark.min.5aa0b879.css 404 Not Found in 3.290403msESC[0m
```

**Comment by torkelo** [comment]
root url is default value but with `granfana/` added to the end

**Comment by torkelo** [comment]
Just tested this and login works fine. 

nginx:
```  
location /grafana/ {
    proxy_pass                 http://127.0.0.1:3000/;
```

grafana ini:
```
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
```

**Comment by zerthimon** [comment]
The trailing slash in http://127.0.0.1:3000/; made it work for me.

But the redirect after login still sends my browser to "/"

**Comment by torkelo** [comment]
strange, must be something wrong with your nginx version?

**Comment by torkelo** [comment]
@zerthimon did you change root_url that ends in grafana/ and did you restart the grafana backend?

**Comment by zerthimon** [comment]
@torkelo here is the current config
```
# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
```

```
    location /grafana/ {
        proxy_pass http://localhost:3000/;
    }
```

**Comment by zerthimon** [comment]
@torkelo restarted the grafana backend and nginx ...
I'm gonna analyze the traffic and report back

**Comment by zerthimon** [comment]
Checked with other browsers - no problems found.
Cleaned cache and cookies and that solved the problem.
Mozilla must have cached the wrong redirect, when I played with configuration.

@torkelo Thanks for assist, grafana is great!

**Comment by torkelo** [comment]
@zerthimon ah, great that you solved it

**Comment by artkrz** [comment]
/etc/init.d/grafana-server restart solved this issue for me

**Comment by areebahmushtaq** [comment]
@torkelo I am new to nginx and grafana both.
I installed nginx and grafana. Grafana works great with its default settings but when I tried doing the above, unfortunately i then dint get access to grafana, it says {{alert.title}}. And if i revert back the changes, grafana works. 
 Can you please guide me where to write this location directive 
 location /grafana/ {
        proxy_pass http://localhost:3000/;
    }
inside a new server block in nginx.conf and outside http block? or can you please show me the nginx.conf file. Am i missing something else as well?

**Comment by torkelo** [comment]
@areebahmushtaq 

this should work
in grafana.ini 
```
root_url = http://your_nginx_and_port/grafana/
```

Your nginx confiug
```
    location /grafana/ {
        proxy_pass http://localhost:3000/;
    }
``

**Comment by torkelo** [comment]
for the nginx config, it should go inside a server block

**Comment by areebahmushtaq** [comment]
and that server block should be outside the http block or inside it? Are there any other settings other than these two lines? 
This would sound silly but my nginx  is the IP of my server? and shall i make a block for this new server in the main context like this?
server{
location /grafana/ {
        proxy_pass http://localhost:3000/;
    }
}

**Comment by Oneirag** [comment]
Hi all
I have the same problem with the login page. I also have the nginx configuration as recommended:
 
```
location /grafana/ {
        proxy_pass http://localhost:3000/;
    }

```
And the variable root_url = http://mydomainname/grafana/

I don't see any issue on that configuration so I checked the js of the login page of grafana. After loging the response of the grafana server is 
`"{"message":"Logged in","redirectUrl":"/"}"`
So that "redirectUrl" parameter the web browser redirects to the root of my server instead of the location /grafana/
After this, I surf back to the /grafana/ location of the server and I'm logged in due to the session cookie so everything works fine 
Did I miss any other configuration parameter that affects this redirectUrl of the response of the login page?
Thanks in advance for your help

**Comment by torkelo** [comment]
The redirectUrl i handled in the frontend and before reloading that page the app sub url is appended. 
https://github.com/grafana/grafana/blob/master/public/app/core/controllers/login_ctrl.js#L84

**Comment by torkelo** [comment]
or wait, that does not look right. hmm.. might be a bug there

**Comment by torkelo** [comment]
Seems to work for me, you should not get redirectUrl unless you have a redirect cookie (tried accessing a page before logging in and you will get one). 

So try clearing any cookies you have

**Comment by karanp24** [comment]
Login works fine but when you try to add datasource the URL is not directed.

**Comment by torkelo** [comment]
The url is not directed? What do you mean?

**Comment by karanp24** [comment]
So I configured the root url and nginx config as in the grafana documentation. And that works fine for login, admin, dashboard, alerting options in grafana. But, when I try to add datasource from UI the page does not show up there and same thing happens for when installing plugins. Following are the latest logs of grafana when I tried to add datasource.
Also my nginx config is :
location /grafana/ {
   proxy_pass http://grafana:3000/;
LOGS--------
t=2016-12-28T03:09:02+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=/grafana
t=2016-12-28T03:09:05+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/datasources status=302 remote_addr=10.0.0.18 time_ms=0s size=37

**Comment by torkelo** [comment]
@karanp24 very strange, cannot replicate and no similar reports :(

**Comment by karanp24** [comment]
@torkelo thanks for the followup. I resolved the issue it was related with nginx. I have /kibana suburl in nginx as well and thats the reason nginx was confused and the kibana urls were getting higher preference. 
so the updated nginx conf is : 
location ^~ /grafana/ {
proxy_pass http://grafana:3000/;

**Comment by sungiri88** [comment]
@torkelo Where you able to do proxy settings in ha proxy? I am using ha proxy instead nginx.

**Comment by lambdaq** [comment]
Hi, I have a similar problem with static files:

Nginx:

    location / grafana {
        proxy_pass http://server_ip:3000
    }

in `grafana.ini`:

    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

But open Chrome navigate to `http://server_ip:3000` will report 

> (index):11 /grafana/public/css/fonts.min.css 404
> (index):14 GET /grafana/public/css/grafana.dark.min.c7b017c5.css 
> (index):79 GET /grafana/public/app/boot.85c49108.js

**Comment by patrickleet** [comment]
@lambdaq ever make any progress with that - getting the same errors with haproxy

**Comment by bergquist** [comment]
@lambdaq that location settings seems starnge. I would expect it to be `/grafana` rather then `/ grafana` ?

http://docs.grafana.org/installation/behind_proxy

**Comment by lambdaq** [comment]
@bergquist Sorry It's a typo. It should be `/grafana`

**Comment by lambdaq** [comment]
@patrickleet I ended up adding a `rewrite` like this:

    location /grafana {
        rewrite ^/grafana/(.*) /$1 break;
        proxy_pass http://internal_server_ip:3000
    }

It's working OK.

**Comment by dpetersen** [comment]
I've spent more time today fighting this than I'd care to admit. All I can say is that Grafana seems extremely touchy mounted at a subpath. I ended up falling back to proxying Grafana without the subpath; it just wouldn't work.

I *think* my proxy server ([bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy)) is forcing a trailing slash, and Grafana refuses to deal with it, but I can't be sure. At a subpath, all I can get is a 404 page that is clearly from Grafana.

**Comment by torkelo** [comment]
@dpetersen strange, never heart of an issue before with putting grafana behind nginx, apache or oauth2 proxy in subpath, that is used by a lot of users.

**Comment by patrickleet** [comment]
The assets were not served at the subpath, although the application was, therefore the assets could not be found. Not sure about `nginx` but I experienced this in `haproxy`. The trick to get it working was to rewrite the subpath to /

Here's relevant config

```
frontend services
    #...

    acl url_metrics_grafana3000 path_beg /grafana/ path_beg /grafana/public path_beg /grafana/api
    use_backend metrics_grafana-be3000 if url_metrics_grafana3000

backend metrics_grafana-be3000
    mode http
    http-request set-path %[path,regsub(/grafana/,/)]
    server metrics_grafana metrics_grafana:3000
```

**Comment by s4s0l** [comment]
@patrickleet how does your root_url looks like? Also can you go to metrics_grafana:3000 directly?

**Comment by gsethu** [comment]
I started Grafana as below. 

# docker run -d  -p 3000:3000 --name=grafana -e "GF_SERVER_ROOT_URL=http://<server-ip>/grafana"  -e "GF_SECURITY_ADMIN_PASSWORD=secret" grafana/grafana

Accessing Grafana via http://<server-ip:3000>/grafana throws 

{{alert.title}} error. 

Am I missing anything in the configuration or setup ? 

From the log message:

msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=/grafana

**Comment by torkelo** [comment]
You specifed http://grafana as root url, so that is what Grafana expects as the url used on browser. 

For putting grafana under suburl /grafana you need a reverse proxy like nginx

**Comment by gsethu** [comment]
Thanks for your reply. I tried adding the host behind AWS ALB (path based routing) and added /grafana as the path. But still the same issue exists. Is that anything need to be configured for accessing Grafana using AWS ALB i.e AWS-ALB-Name/grafana throws the above error.

But if I start with default root_url (no sub_urls), I am able to access it via AWS ALB with the corresponding port number i.e. AWS-ALB-Name:3000 works fine.

**Comment by torkelo** [comment]
Not sure how AWS ALB subpath reverse proxy works, I know that it works with
apache and nginx.

**Comment by linusguan** [comment]
@gsethu @torkelo The ALB path based routing does not do path manipulation so the request Grafana got is `http://someip:3000/grafana`. I think there has to be a reverse proxy in the middle to strip out `/grafana` because there is no way to configure Grafana to serve a sub path directly.

**Comment by dereulenspiegel** [comment]
@dpetersen Sorry for digging up this issue although it is closed. But I am also trying to run grafana behind oauth2_proxy from bitly. Other applications are working quite well like this, but with grafana all I get are 404s. Did you ever got the combination of oauth2_proxy and grafana working?

**Comment by dpetersen** [comment]
@dereulenspiegel I only got it working at the root, not at a subpath, and we settled for that. If you're OK with running it at the root and are having problems, shoot me an email at the address in my Github profile, and I can dig up my configs for you.

**Comment by Emmanux** [comment]
Deleting everything cached and cookies did the trick.

**Comment by aceslup** [comment]
this configuration，nginx is work。but，direct access will be reported，like this：http://grafana_server:3000/grafana/。return {{alert.title}}。Is it the same?

**Comment by Emmanux** [comment]
@aceslup You're still having problems with the paths. But it could be that the problem is in your client side (browser), even when everything works OK on the server side. Make you sure that you're always using a fresh browser profile, or delete cache and cookies.

**Comment by fogfish** [comment]
There are no easy way to run grafana behind AWS ALB. You need to setup nginx + grafana. It would be nice if subUrl is configurable directly within grafana.

**Comment by iggyzap** [comment]
Why is this ticket closed ?

**Comment by JulianGindi** [comment]
I'm running into this issue as well. I'm testing without a load-balancer/proxy set up by running Grafana directly on port 80 as Root (for testing only). I run into the same redirect issue with /login. Not sure how to debug this further. I have taken the suggestions into account from this thread.

**Comment by bbbenji** [comment]
I had the same problem. Commenting out the following in my NGINX config resolved the issue.

    location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
      expires 7d;
      access_log off;
    }

**Comment by aggieben** [comment]
I also am having problems with this.  I'm using traefik, and running both as docker containers.  My docker-compose looks like this:

```yaml
version: '3'
services:
  traefik:
    image: traefik
    restart: always
    ports:
     - 80:80
     - 443:443
     - 8080:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/ben/traefik.toml:/etc/traefik/traefik.toml
     - /etc/letsencrypt/live/mydomain/fullchain.pem:/mydomain_fullchain.pem
     - /etc/letsencrypt/live/mydomain/privkey.pem:/mydomain_privkey.pem
  grafana:
    image: grafana/grafana
    restart: always
    ports:
     - 3000:3000
    volumes:
     - /srv/grafana:/var/lib/grafana
    environment:
     - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
    labels:
     - traefik.enable=true
     - 'traefik.frontend.rule=Host:metrics.mydomain;PathPrefix:/grafana;'
     - 'traefik.frontend.redirect.entryPoint=https'
```

I get the same 404 response (with content) from grafana.  What's doubly confusing is that I have `/grafana` set up as the subUrl (via `server.root_url`), but the grafana logs show requests coming in that look proper (to me) and still getting the 404 response (log truncated):

```
method=GET path=/grafana/public/build/app.a4b7f5a163ea89ff6420.js status=404 remote_addr=192.168.0.1
method=GET path=/grafana/public/build/grafana.dark.css status=404 remote_addr=192.168.0.1
```

It seems from this that 
 - Grafana is expecting to serve requests at `/grafana`
 - Traefik is proxying requests from `https://metrics.mydomain/grafana` => `http://localhost:3000/grafana` correctly
 - Grafana is still giving me the finger

**Comment by onedr0p** [comment]
@aggieben your solution in that SO question helped me. I also have Prometheus with a base url too!

> I was able to fix this by using PathPrefixStrip instead of PathPrefix

**Comment by KugelschreiberY** [comment]
I am also getting the message {{alert.title}} when calling grafana through nginx. 
Both is running on an openshift cluster in two different pods, with the following nginx.conf:

`upstream grafana_nginx {
       server grafana:3000;
   }
   server
   {
       listen 8080 ssl;
       ssl_certificate /etc/nginx/ssl/admin-cert.pem;
       ssl_certificate_key /etc/nginx/ssl/admin-key.pem;

       ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;

       proxy_ssl_server_name on;
       server_name nginx.local;

       location /grafana {
            proxy_pass http://grafana_nginx;
            rewrite  ^/grafana/(.*)  /$1 break;
            proxy_set_header Host $host;
       }
}`

Note that grafana in the upstream config is the name of the grafana service.
Would be great if someone has an idea how to solve this issue or some tips. Thanks in advance!

**Comment by proskehy** [comment]
Has anyone figured this out? I use nginx-ingress config where I specify the path and rewrite:
```
nginx.ingress.kubernetes.io/rewrite-target: /
...
- path: /grafana
``` 
Accessing `/grafana` sends me to `/login`, resulting in 404. Accessing /grafana/login results with the {{alert.title}} page. I tried specifying `root_url` and `static_root_path` for grafana, but that didn't seem to do anything.

**Comment by torkelo** [comment]
what did you set root_url to?

**Comment by proskehy** [comment]
I think that I've tried `/grafana` and `http://domain/grafana`

**Comment by proskehy** [comment]
Ah, silly me, I was passing it as an env variable and it apparently wasn't getting picked up. Putting it directly into grafana.ini did the trick!

**Comment by ateixeira-pt** [comment]
_Working Config_ 
**grafana.vhost**
```
	# Handle Grafana Path
	location /grafana {

		# Send To Proxy
		proxy_pass http://grafana_server:3000;

		# Rewrite Rule
		rewrite ^/grafana/(.*)$ /$1 break;
	}
```
**Grafana Docker**
```
    image: grafana/grafana:5.2.1
    environment:
      GF_SERVER_ROOT_URL: https://your.domain.com/grafana
      GF_SERVER_DOMAIN:your.domain.com

```

**Comment by consult-kk** [comment]
@ateixeira-pt -- 
This did not work for me :(
This is what I have 

nginx.conf : 
`location /grafana {`
`                # Send To Proxy`
 `               proxy_pass http://localdocker:3000;`
`
  `              # Rewrite Rule`
    `            rewrite ^/grafana/(.*)$ /$1 break;`
 `  }`

docker-compose.yml :
grafana:
   container_name: grafana
   environment:
   - GF_SERVER_ROOT_URL=http://mydev-domain/grafana
   - GF_SERVER_DOMAIN=mydev-domain
   extra_hosts:
   - localdocker:$LOCALDOCKER_HOSTNAME
   image: grafana:latest
   ports:
   - 3000:3000

**Comment by kfferrando** [comment]
OS: RHEL 7.5
Nginx: 1.12.2-2
Grafana: 5.2.2

I had the same issue with initial redirect from <hostname>/grafana/ to <hostname>/login resulting in a failure to reach the application. I tried all the variations of configuration and the only thing that eventually fixed this was adding the following environment variables to /etc/sysconfig/grafana-server:

# replace <hostname> with your FQDN
GF_SERVER_ROOT_URL=http://<hostname>/grafana
GF_SERVER_DOMAIN=<hostname>

/etc/grafana/grafana.ini
root_url had zero effect and I have left it commented out in the configuration and everything is still working.

/etc/nginx/conf.d/grafana.conf

server {
 ...
  location /grafana/ {
    proxy_pass http://localhost:3000/;
  }
}

Restart grafana/nginx and redirect began to work properly for all endpoints/assets.

**Comment by gajus** [comment]
If you are using Helm Grafana chart, then you need to configure nginx rewrite to make the static resources load:

```yaml
persistence:
  enabled: true
  size: '32Gi'
  accessModes:
    - ReadWriteOnce
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: '/monitoring/grafana/'
  hosts:
    - applaudience.com
grafana.ini:
  server:
    root_url: https://applaudience.com/monitoring/grafana/

```

Related issues:

* https://github.com/helm/charts/issues/7089
* https://github.com/helm/charts/issues/6264

That said, this is an issue with Grafana and the issue should be open.

**Comment by jenting** [comment]
> If you are using Helm Grafana chart, then you need to configure nginx rewrite to make the static resources load:
> 
> ```yaml
> persistence:
>   enabled: true
>   size: '32Gi'
>   accessModes:
>     - ReadWriteOnce
> ingress:
>   enabled: true
>   annotations:
>     kubernetes.io/ingress.class: nginx
>     nginx.ingress.kubernetes.io/rewrite-target: /
>   path: '/monitoring/grafana/'
>   hosts:
>     - applaudience.com
> grafana.ini:
>   server:
>     root_url: https://applaudience.com/monitoring/grafana/
> ```
> 
> Related issues:
> 
> * [helm/charts#7089](https://github.com/helm/charts/issues/7089)
> * [helm/charts#6264](https://github.com/helm/charts/issues/6264)
> 
> That said, this is an issue with Grafana and the issue should be open.

Thanks, It solves my problem!!! I have waste a lot time on it.

**Comment by asychev** [comment]
For those, who use nginx-ingress >= **0.22.0** - check release notes:

- https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.22.0
- https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

and fix configuration like  this:

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  path: '/monitoring/grafana/'
  hosts:
    - host.com
grafana.ini:
  server:
    root_url: https://host.com/monitoring/grafana/?(.*)
```

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048

**Comment by kylegordon** [comment]
> Future versions of Grafana will "just work" without this requirement for a rewrite rule. #17048

Great news! Thank you :+1:

**Comment by robododge** [comment]
I just spent the better part of two hours debugging this problem and got it working. Turns out I had a nginx 'location' matching rule that was short circuiting the proxy_pass and trying to server the *.js and *.css files from the local nginx not from the proxy_pass directive

NGINX: 1.16
Grafana: 6.3.5

**Step1**:  Add the settings in Grafna
```
 GF_SERVER_ROOT_URL= http://gf.example.com/grafana
 GF_SERVER_DOMAIN= gf.example.com
```

**Step2:** Add settings in Nginx config
```
upstream grafana-upstream {
  server gf.example.com;
}
#This config is close, but still doesn't work, needs re-write rule
    proxy_pass http://grafana-upstream/;
 
```

Now - grafana logs will complain about the URL //login with double slash being requested.  Fix this by adding the rewrite rule to Nginx config

**Step 3** - add re-write rule
```
upstream grafana-upstream {
  server gf.example.com;
}

location /grafana {
   #Fixes the problem with of requesting double slash on the grafana server i.e. - //login
    rewrite ^/grafana/(.*) /$1 break;
    proxy_pass http://grafana-upstream/;
  }
```
**Step 4**:
Lastly - my browser is getting 404 trying to request the grafana javascript and css from files like `/grafana/public/build/vendor-blah-blah.js` .   I turns out, I had conflicting NGINX  prefix matching location rules elsewhere in my Nginx config.  

Rules like this were taking precedence to the proxy_pass /grafana rule : 
```
location ~* \.(?:css|js)
{try_files $uri =404;
  expires 1d;
  access_log off;
```

****FIX** - removed conflicting rules**  (but, the conflicting rules were doing things like setting expiry headers, now I have to figure out how to add those rule back without conflict. :grimacing:)

**Comment by gredezcici** [comment]
i tried all suggestion mentioned above, none of them worked for me.
at last i changed this line "serve_from_sub_path = true".

**Comment by Dowster64** [comment]
I know this is a closed issue.  However, I am running grafana behind haproxy and I have this problem too.  I seem to think it was only recently that it was an issue (ie later versions of grafana for me.  There is one thing that might be useful and that is that it depends which icon you use to get to the login screen. There are two images attached.  I also have these lines in my grafana.ini and I also recently added a trailing fwd slash to 'fix' this (didn't seem to work)
Note that fiabpi/grafana used to work fine anyway
root_url = https://fiabpi.local/grafana/
serve_from_sub_path = true

I have now attached images.  The url for the door icon (lower left) when you hover over it is:
https://fiabpi/?orgId=1&forceLogin=true
However if you however over the Grafana logo icon on the top left, the url is:
https://fiabpi/grafana/login

![grafana upper icon login Screenshot 2023-02-24 172627](https://user-images.githubusercontent.com/13059464/221113366-fc5fc523-1234-4f64-a8b3-a590d9c0f238.png)
![grafana lower icon login Screenshot 2023-02-24 172429](https://user-images.githubusercontent.com/13059464/221113390-be2c809e-82bb-40d9-a577-1de06fb95e84.png)
