### ISSUE TITLE
Option to disable auto-migration of dashboard when viewing

### ISSUE THREAD

**Issue by garrettheel** [grafana/grafana#20665]
**What would you like to be added**:

When browsing a dashboard created with an old schemaVersion (6, in this case) as an `Editor`, the dashboard seems to be transparently migrated to a new schema version and marked "dirty". This means you're prompted to save if you leave the page.

The dashboards I'm using are managed externally and it'll take quite some time to move them over to the new schema (mostly on account of the rows => panels layout changes introduced in Grafana 5.0). It would be great to have an option to switch off this "auto-migrate" feature in the meantime.

**Why is this needed**:

Without this option, I'm constantly prompted to "save" changes to dashboards that I haven't changed just by viewing them. This makes for a confusing and annoying user experience.

**Comment by marefr** [comment]
We cannot switch that off because then Grafana would serve broken dashboards. This is the mechanism Grafana uses to be backward/forward compatible.

**Comment by garrettheel** [comment]
@marefr Is it possible to trigger the migration on the POST to `/api/dashboards/db` instead?

**Comment by marefr** [comment]
@garrettheel no the migration happens in the browser

**Comment by garrettheel** [comment]
Somewhat relatedly, I'm seeing that the dashboard is put in a dirty state even when it's already on the latest schema and someone toggles an annotation at the top. Is that intended?

I would've expected some of the interactive components not to trigger a dirty state unless you explicitly enter an "Edit" mode. It looks like it might already be this way for variables, but not for annotations.

Please let me know if I'm not explaining the use-case sufficiently and you need more information. Perhaps we're using grafana a little differently to how most others do.

**Comment by torkelo** [comment]
You can see all that we ignore here: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/services/ChangeTracker.ts#L109
