### ISSUE TITLE
Grafana fails to start with "bind: address already in use" in `protocol = socket` mode

### ISSUE THREAD

**Issue by tobast** [grafana/grafana#20672]
**What happened**: After upgrade from 6.4.2 to 6.5.0, my Grafana instance fails to start with 
```
failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: address already in use
```

The port 3000 is indeed used on this machine, but this should not be a problem since my configuration also specifies

```
protocol = socket
socket = /run/grafana/grafana.sock
```

Setting `http_port` to some random (valid, unbound) value allows Grafana to start. After starting, it will duly listen on the provided socket and `netstat -antp  | grep LISTEN | grep 14482` returns nothing. This command duly returns `grafana-server` when setting `protocol` to `http`.

**What you expected to happen**: the server should start normally, independently of the bound state of port 3000

**How to reproduce it (as minimally and precisely as possible)**: make any program listen on port 3000, and configure grafana with
```
protocol = socket
```

then try to start `grafana-server`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: N/A
- OS Grafana is installed on:  Debian buster, ARM platform
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by marefr** [comment]
@tobast thanks. Seems like a regression from #19644

**Comment by aknuds1** [comment]
Thanks for reporting, looking into this.

**Comment by Harshit161998** [comment]
I am also facing this issue and i am installing prometheus for first time
