### ISSUE TITLE
regex for tag values query

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#20671]
**What would you like to be added**:
I'd like a regex applied to the result of "Tag values query" of value groups/tags, similar to the regex which is applied to the main query.

**Why is this needed**:
Since I have a regex applied to the main query, I need one on the output of the tag values query as well.  I can't find a way to do it.

**Comment by torkelo** [comment]
Tag values feature is likely to go away in the future, it's an experimental feature that we hope we can remove.
