### ISSUE TITLE
Pushover: context deadline exceeded

### ISSUE THREAD

**Issue by cyoder4400** [grafana/grafana#20678]
**What happened**:
Alerts for Pushover fail with images enabled with the below logs. When disabling images, alert works in Pushover. Adjusting the timeout doesn't seem to help at all.
t=2019-11-26T14:46:30-0500 lvl=info msg=Rendering logger=rendering path="d-solo/000000031/server-up-time?orgId=1&panelId=2"
t=2019-11-26T14:47:00-0500 lvl=info msg="Rendering timed out" logger=rendering
t=2019-11-26T14:47:00-0500 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url p
arameter"
t=2019-11-26T14:47:01-0500 lvl=eror msg="Failed to send pushover notification" logger=alerting.notifier.pushover error="context deadline exceeded" webhook="Pushover High"
t=2019-11-26T14:47:01-0500 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000003 error="context deadline exceeded"
t=2019-11-26T14:47:01-0500 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000003 error="context deadline exceeded"

**What you expected to happen**:
Pushover alert to be sent

**How to reproduce it (as minimally and precisely as possible)**:
Trigger any alert to Pushover

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5
- Data source type & version: Any
- OS Grafana is installed on: Debian 8.6
- User OS & Browser: Windows/Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
If you navigate to the panel where alert is defined and do Panel menu -> Share -> Direct link rendered image. Does it work? If not, suggest trying out [Grafana Image Renderer plugin](https://grafana.com/docs/administration/image_rendering/#grafana-image-renderer-plugin)

**Comment by kkrampa** [comment]
I have the same issue but with slack notification. I checked image rendering and it doesn't work. Rolling back to `6.4.5` fixed the issue.

**Comment by cyoder4400** [comment]
Sorry for not replying sooner, power was out and couldn't test. Installing the grafana-image-renderer plugin along with doing an install if all the known package dependencies, it started working. I will say though image render still seems to be very slow. Following the steps above to test rendering can take up to 20 seconds to render. But this issue can be closed.
