### ISSUE TITLE
Improve dashboard provisioning docs

### ISSUE THREAD

**Issue by mattiasb** [grafana/grafana#20676]
**What would you like to be added**:

More explicit documentation for the `editable` field of the provider objects in `/etc/grafana/provisioning/dashboards/dashboards.yml`.

From the docs I get this:
```yaml
  # <bool> enable dashboard editing
  editable: true
```
… which sounds like it would disable editing of dashboards from the UI, but then further down this variable is defined:
```yaml
  # <bool> allow updating provisioned dashboards from the UI
  allowUiUpdates: false
```
… which further down is described like this:

> If allowUiUpdates is configured to false, you are not able to make changes to a provisioned   
> dashboard. When you click Save, Grafana brings up a Cannot save provisioned dashboard 
> dialog. 

So `allowUiUpdates` makes it possible to disable editing of dashboards. Then what does the `editable` field do?

**Why is this needed**:

I want to be able to set my configuration in an informed way. :)

**Comment by Hipska** [comment]
I also would like to have more documentation of this feature.

**Comment by mattiasb** [comment]
I stumbled upon the code where I set the `editable` field to false for our Grafana instance together with the comment "Find out what this does". Could anyone knowledgeable answer this question? :)

**Comment by GrafanaWriter** [comment]
Reviewing https://grafana.com/docs/grafana/latest/administration/provisioning/, this issue still exists. We should resolve in the next phase of work on the Admin content @gguillotte-grafana.

**Comment by GrafanaWriter** [comment]
Given the age of this issue, and the lack of activity, I will close. Please reopen if the issue is still valid.
