### ISSUE TITLE
Users are counted more than once in admin/stats if the user is part of more than one org

### ISSUE THREAD

**Issue by dconrique01** [grafana/grafana#20681]
**What happened**:
Admins are reporting that if a user is part of more than one org, they are counted more than once in the admin > stats page. E.g. if a user is part of 10 orgs, they get counted 10 times in the active users stats. 

The issue might have been introduced in this PR: https://github.com/grafana/grafana/pull/19178 

**What you expected to happen**:
Only distinct users are counted in the admin > stats. E.g. if a user is part of 10 orgs and they log in, they are only counted once in the stats. 

**How to reproduce it (as minimally and precisely as possible)**:
Note the number of current active users. Add a user to more than one org. Log in as the user. Note that the active user count went up by more than 1. 

**Environment**:
- Grafana version: 6.4.3 (presumably 6.4.0+)

**Comment by DanCech** [comment]
This can likely be fixed by changing `COUNT(*)` to `COUNT(DISTINCT u.id)` in the queries modified in #19178

**Comment by marefr** [comment]
Guess it depends on what we want since roles are defined per organization?

**Comment by DanCech** [comment]
Well, there was no mention of a behavior change in #19178 so at this point I'd consider the 6.4.0+ behavior a bug.  If we do want to change it there should be a discussion about it.

**Comment by xlson** [comment]
I agree, changing this behavior without any kind of warning seems like a bug. I think we have a separate problem, which is that it's pretty unclear what the stats are supposed to be. Neither version of the stat really makes perfect sense in a multi-org installation of Grafana. We should probably take a another look at the stats and see if there is anything we should change to make them more easily understandable and useful. A good start would be more detailed descriptions on the stats page in Grafana.

**Comment by marefr** [comment]
Ohh it was introduced in #19178 . Then it's definitely a bug and should be fixed! Agree with Leo that we probably should discuss stats in general.
