### ISSUE TITLE
Support to select repeating as opional checkbox

### ISSUE THREAD

**Issue by SnDsound** [grafana/grafana#20683]
Hi,

Maybe would be great, to add option repeating as variable, to select repeating as opional.
Right now this must be configured "as designed" by dashboard owner. But in some cases to visualize the same set of data is better to watch them with or without repeating graphs.

For example, we have data for CPU usage (cpu number 1,2,3,4) on four hosts.
And sometime I'd like to have 4 CPUs on one graph repeated for every host, but sometimes I'd like to compare one CPU number 3 on four hosts, and then option without repeating will be beter.

Right now I need to change graph option everytime or duplicate dashboards

Regards,
SnDsound

**Comment by torkelo** [comment]
Do not think we will add a dashboard level toggle/option for this. Hope to solve use cases like this using a new form of scripted / dynamic dashboards.
