### ISSUE TITLE
Error occured while migrating Grafana (5.4.2) maria db to azure db for mariadb.

### ISSUE THREAD

**Issue by restlessankyyy** [grafana/grafana#20682]
I am trying to migrate grafana db from existing maria db to azure db for mariadb.
However i am getting this below error.

![image](https://user-images.githubusercontent.com/23651587/69680921-ba0c2980-10ac-11ea-9378-6735695ed8eb.png)

Please help me with this..

**Comment by marefr** [comment]
The error `9999` is returned from azure so not a Grafana problem and I'll close this.

Found a similar [issue](https://github.com/formulahendry/vscode-mysql/issues/111), but not same error code so you'll have to search for help elsewhere or contact azure support.
