### ISSUE TITLE
Logging to grafana with user not present in Grafana is not Throwing any error 

### ISSUE THREAD

**Issue by Pushpa79** [grafana/grafana#20686]
When i tried to click on forgot password it is redirecting me to the page Reset password, there if i give a new email which was not user of the grafana but still it is accepting and giving a message as Reset email sent . It Should display as " User doesnot exist".

**Comment by Pushpa79** [comment]
Grafana Version :6.4.3

![image](https://user-images.githubusercontent.com/58244704/69695314-ed2cd800-1101-11ea-865d-9614cdd01a23.png)

After clicking on the ResetPassword in above image it is displaying like below:
![image](https://user-images.githubusercontent.com/58244704/69695593-e6529500-1102-11ea-977c-3ce79ea242d0.png)

**Comment by marefr** [comment]
In general it's a security risk exposing whether a user exists or not when resetting password etc so this is not something we'll add.
