### ISSUE TITLE
Unable to use elasticsearch fields starting with underscore in Grafana

### ISSUE THREAD

**Issue by prkadalb** [grafana/grafana#20692]
**What happened**: I tried to use the elasticsearch datasource in Grafana and it cannot detect my timestamp field as it starts with (two) underscores. 

**What you expected to happen**: Grafana should allow fields starting with one or more underscores

**How to reproduce it (as minimally and precisely as possible)**: Use `__timestamp` instead of `@timestamp` as the name of the date field in your mapping 

**Anything else we need to know?**: A large number of my fields start with an underscore. The system is large and old with multiple writers and consumers, which makes it very difficult to change all these fields to not start with an underscore.

**Environment**:
- Grafana version: v6.3.5 (67bad72)
- Data source type & version: elasticsearch 6.4
- OS Grafana is installed on: Linux
- User OS & Browser: macOS Mojave, Chrome
- Grafana plugins: elasticsearch
- Others:

**Comment by prkadalb** [comment]
It looks like this line is causing the problem:

https://github.com/grafana/grafana/blob/9b7748ec133cb2ce4b092e523cb6d70a7b89de83/public/app/plugins/datasource/elasticsearch/datasource.ts#L394

**Comment by vsergeyev** [comment]
Hello @prkadalb 

It looks it was done by a purpose to hide meta fields in elastic:

`https://github.com/grafana/grafana/blob/9b7748ec133cb2ce4b092e523cb6d70a7b89de83/public/app/plugins/datasource/elasticsearch/datasource.ts#L429`

It may be a chance it is good to add an option in elastic datasource to allow to use such fields.

**Comment by davkal** [comment]
Could add a second condition when second char is underscore as well (or use a regex).

**Comment by dry4ng** [comment]
Just run into this issue. I have ES cluster managed by different team, and they have multiple variables starting with underscore. Grafana doesn't see them.
