### ISSUE TITLE
500 Internal Server Error when accessing Graphite data source over HTTPS

### ISSUE THREAD

**Issue by bigunyak** [grafana/grafana#2069]
Hello,

First of all thank you for your work, Grafana is awesome! :)
I'm very new to the project and can't figure out the cause of the problem I'm facing, maybe you can help.
I'm trying to configure Graphite data source to be used with `proxy` access type and getting 500 Internal Server Error. The problem occurs only over HTTPS and only with `proxy` access type, `direct` access over HTTPS works fine and `proxy` works over HTTP.
I was trying to dig into the problem but it's difficult as the only thing I see in the log is:
```
[I] Completed /render 500 Internal Server Error in 4.389911ms
```
I was not able to find any bug reports describing a similar problem so I presume this could be a result of misconfiguration somewhere.
One more thing to mention is that my ssl certificate is self-signed. Grafana version is 2.0.2

**Comment by torkelo** [comment]
ok, need to test, could be the self-signed thing that is causing the issue.
