### ISSUE TITLE
Panel 'render value as link' should have option to include path from "root_url" and "serve_from_sub_path"

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [grafana/grafana#20695]
**What would you like to be added**:
Relative links used in panels on a dashboard should have an option to automatically include the sub-path that Grafana is being served on, as defined in the config variables 'serve_from_sub_path' (GF_SERVER_SERVE_FROM_SUB_PATH) and 'root_url' (GF_SERVER_ROOT_URL).

**Why is this needed**:
I have a development and production environment which serve Grafana on different sub-paths: dev environment uses standard root ('/'), the production environment is served on a sub path (e.g. '/project-name/dashboard/'). When I test my dashboards and panels or push to production, any panels that have data rendered as links either works for the test environment or production environment, not both at the same time (as the sub path being served on is not included on relative links).

I could manually change the sub-path being served on, but there could be other reasons that this would be important. If the sub-path had to change in production (name change, migration, URL condensing, etc, etc), I would have to find all panels with links rendered an update each individually. Updating sub-path in config once is better than numerous times across many panels/dashboards.

Thanks for the consideration.

**Comment by marefr** [comment]
Not sure this is something we can or want to support. Would suggest using /dev and/prod or two different domains/servers to workaround this.
