### ISSUE TITLE
Grafana not failing gracefully when log directory is unaccessible and gives wrong error message

### ISSUE THREAD

**Issue by severn-everett** [grafana/grafana#20699]
**What happened**:
Grafana 6.5.0 segfaults when it's configured to use a log directory that cannot be accessed. Furthermore, the error output claims that Grafana could not find the configuration defaults, even though the configuration settings for `-homepath` and `-config` were accepted by previous Grafana versions without any issue.

**What you expected to happen**:
Grafana reports that it cannot reach the configured log directory.

**How to reproduce it (as minimally and precisely as possible)**:
- Modify [paths][logs] in the default configuration to point to a directory that the user does not have write access to.
- Attempt to start Grafana using the modified configuration.

**Anything else we need to know?**:
This is a new behavior that didn't occur in Grafana versions <6.5.0.

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: N/A
- OS Grafana is installed on: CentOS 7.7.1908
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: Output from `/var/log/messages` [here](https://github.com/grafana/grafana/files/3896761/grafana_6_5_0.txt).

**Comment by aknuds1** [comment]
Thanks for reporting this, looking into it.

**Comment by aknuds1** [comment]
I could reproduce this.
