### ISSUE TITLE
Wrong time range on Samung TV (now() returns incorrect date)

### ISSUE THREAD

**Issue by toniiiik** [grafana/grafana#20690]
on Samsung TV default browser range picker now is incorrect. The value is 1970-01-01 instead of 2019-11-27. Time part is wrong as well.

**What happened**:
dashboard on Samsung TV default browser
![image](https://user-images.githubusercontent.com/32296236/69704811-83f29800-10f4-11ea-9d52-043a97a659df.png)

**What you expected to happen**:
dashboard on safari browser
![image](https://user-images.githubusercontent.com/32296236/69704276-6113b400-10f3-11ea-8a10-eb6788fdbc37.png)

**How to reproduce it (as minimally and precisely as possible)**:
navigate to grafana on Samusng TV with default browser.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.6 (fdd2117)
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker (prometheus-operator)
- User OS & Browser: TV SAMSUNG 55" UHD Smart TV UE55RU7172 (2019)
- Grafana plugins: polystat (v1.0.16), Boom Table (v1.3.0)
- Others:

**Comment by marefr** [comment]
Not sure that's a [supported browser](https://grafana.com/docs/installation/requirements/#supported-web-browsers). What browser is that and what version?

**Comment by toniiiik** [comment]
my bad... I do not correctly check supported browser section. 

Browser is TizenBrowser v2.2.0.0722040. I am Closing issue.

PS: please can you provide me source to component where the time range is handling?

**Comment by marefr** [comment]
Think it's this one https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/TimePicker/TimePicker.tsx
