### ISSUE TITLE
6.5.0 CloudWatch query escaping parentheses causing query to return zero results 

### ISSUE THREAD

**Issue by jveldboom** [grafana/grafana#20704]
**What happened**:
Added a query to pull in API Gateway metrics. Most of our API Gateway API names have the environment in parentheses "My API (production)". Grafana is trying to escape those parentheses by adding backticks to all of them.

```
REMOVE_EMPTY(SEARCH('{AWS/ApiGateway,ApiName,Method,Resource,Stage} MetricName="Latency" "ApiName"="My API API \(production\)" "Stage"="v4"', 'p90', 300))
```

Pasting that query into CloudWatch returns zero results so assumes to be Grafana escaping characters and passed it to CloudWatch. Removing those backticks in CloudWatch causes it to return the expected data.

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Alpine Docker container
- User OS & Browser: Chrome

**Comment by sunker** [comment]
Thanks for reporting this @jveldboom! 

Just to be clear, are you manually adding the search expression in the expression field in the editor, or is that expression generated by grafana? Grafana will generate a search expression automatically for you when you're using a wildcard, when you have a multi-valued template variable or when `Match Exact` is turned off.

**Comment by jveldboom** [comment]
Thanks for the quick response. I tried these two things:
- Picked each metric and dimension by hand without any wildcards or variables. And could see the backslashes.
- Chose some dimensions like `ApiName` and then used wildcards on `Method` and `Resource`. Also could see the backslashes here.

We also have some dashboards that use variables for all the dimensions above. Those were returning zero results without any errors. I do not get a chance to look at the CloudWatch query though. We quickly reverted back to 6.4.2 as most of our dashboards were no longer rendering. But happy to spin up another instance and provide any information to help.

**Comment by sunker** [comment]
Thanks! Could you please share your query? Do that by clicking `Query Inspector` on the top right of the query editor, and the select `Copy to clipboard`. That would be a huge help.

**Comment by jveldboom** [comment]
Sorry I was mistaken. It does seem to work when I add each dimension by hand. But I am seeing the error when using a wildcard `*`.

Here's the json from the query inspector.

```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1574870710092",
      "to": "1574871610092",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 1000,
          "maxDataPoints": 779,
          "datasourceId": 2,
          "type": "timeSeriesQuery",
          "namespace": "AWS/ApiGateway",
          "metricName": "Latency",
          "expression": "",
          "dimensions": {
            "ApiName": [
              "My API (production)"
            ],
            "Stage": [
              "v4"
            ],
            "Method": [
              "*"
            ],
            "Resource": [
              "/recipe_box/card"
            ]
          },
          "region": "us-east-1",
          "id": "",
          "alias": "",
          "statistics": [
            "p90"
          ],
          "matchExact": true,
          "datasource": "fott",
          "period": "60"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "gmdMeta": [
            {
              "Expression": "REMOVE_EMPTY(SEARCH('{AWS/ApiGateway,ApiName,Method,Resource,Stage} MetricName=\"Latency\" \"ApiName\"=\"My API \\(production\\)\" \"Resource\"=\"/recipe_box/card\" \"Stage\"=\"v4\"', 'p90', 60))",
              "ID": "queryA"
            }
          ]
        },
        "series": [
          {
            "name": "queryA",
            "points": [],
            "tags": {
              "ApiName": "My API (production)",
              "Method": "queryA",
              "Resource": "/recipe_box/card",
              "Stage": "v4"
            }
          }
        ],
        "tables": null,
        "dataframes": null
      }
    }
  }
}
```

**Comment by sunker** [comment]
This is weird. According to the [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html#search-expression-syntax-characters), the following characters must be escaped with a backslash `" \ ( )`. So whenever Grafana generates a search expression, we'll simply insert a backslash before the illegal character. 

So either we have misunderstood the api docs or escaping is not necessary. Maybe you can help me test that by entering the following search expressions in the expression field in the query editor: 
`REMOVE_EMPTY(SEARCH('{AWS/ApiGateway,ApiName,Method,Resource,Stage} MetricName="Latency" "ApiName"="My API API (production)" "Stage"="v4"', 'p90', 300))`
and 
`REMOVE_EMPTY(SEARCH('{AWS/ApiGateway,ApiName,Method,Resource,Stage} MetricName="Latency" "ApiName"="My API API \(production\)" "Stage"="v4"', 'p90', 300))`
Please let me know which one of those queries that works.

**Comment by jveldboom** [comment]
Only the one without the escaped characters returned data. 

Also, from the AWS console, the query below returns data but adding the backslashes does not.
`SEARCH('"My API (production)"', 'Average', 300)`

**Comment by sunker** [comment]
Okay, thanks again for reporting this @jveldboom 

I've talked to cloudwatch engineers - we should only escape double quotes when generating expressions in grafana. Fix will come in next release, hopefully next week.
