### ISSUE TITLE
"Bar Gauge" Visualization - value mapping

### ISSUE THREAD

**Issue by rguptarg** [grafana/grafana#20706]
Hi Team,

We are using "Bar Gauge" Visualization on Grafana v6.4.4 (092e514)

Here we are trying to mapped null value with zero, 

Kindly suggest if any changes required.

Data source  == InfluxDB
![1](https://user-images.githubusercontent.com/49057178/69732550-d4e4a980-1151-11ea-912a-892f1d703e0b.JPG)

**Comment by mckn** [comment]
@torkelo I might need some input from you regarding this issue. I have a solution but it depends a bit on what kind of input we are trying to feed this visualization with.

We have support for mapping the `null` type but there are a scenario in the [displayProcessor.ts#L92](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/displayProcessor.ts#L92) that looks like we are sending in the `string` representation of the value. 

I am guessing `"null"` but can't say for sure without more information about the source data that we are trying to visualize here. 

So I would love to hear your thoughts on this.

**Comment by torkelo** [comment]
I think we need to use the function getMappedValue(mappings, null), 
here:
 https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldDisplay.ts#L198 

when there is no data (and treat no data as null, so it can be mapped to something else)

**Comment by mckn** [comment]
Ah, ok ok..so I totally misunderstood the issue here. I thought we had trouble mapping `null` data to `0`. But it is the label that we want to be able to change. Got it! Thanks!

**Comment by torkelo** [comment]
think mapping null works, but mapping "no data" (empty data array), to a value does not work. Would be good to treat no data as null so it can be mapped to a custom text or value
