### ISSUE TITLE
Add user timings for data processing and rendering 

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#20708]
From @Dieterbe:

> do we have a good grasp on how long it takes on the grafana side to decode json responses from graphite vs rendering them etc.

We should add [user timings](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) so these values can be seen easily in dev tools.

**Comment by torkelo** [comment]
This could also go into the new inspect drawer feature: 
https://github.com/grafana/grafana/issues/20710
