### ISSUE TITLE
Template Variable save UX

### ISSUE THREAD

**Issue by nikoalch** [grafana/grafana#20703]
When I add a variable query and it returns data, it pushes the “add” button off the screen and I forget to scroll down and click it.  The scrollbar is very faint.  There is no warning when you navigate away etc.
Could the save be moved up top right, similar to dashboards? or perhaps a modal alerting you that you did not save?

**Comment by torkelo** [comment]
@hugohaggmark we discussed this as well . Think one solution is to create the variable (with a generated name) when you hit the new button. So for new variables, you do not have to remember to hit the add button

**Comment by hugohaggmark** [comment]
@torkelo yes!

**Comment by RichiH** [comment]
Auto-creating and auto-saving might not match user expectations. Principle of least surprise would be best met with a modal, I think.

**Comment by sarlinska** [comment]
I agree with @RichiH it should be a modal saying: 

_You are about to leave the page without saving the variable_
Button: **Save variable**
Button: **Leave without saving** 
Button: **Go back to editing**

**Comment by hugohaggmark** [comment]
I think we need to talk about this @sarlinska together with @torkelo, I don't think we all have the same picture/expectations here.

**Comment by dprokop** [comment]
@hugohaggmark not sure if we have fixed this already or not?

**Comment by hugohaggmark** [comment]
@dprokop no we have not (yet). I think we need to get newVariables into master for a while before taking this on.
