### ISSUE TITLE
select as expression

### ISSUE THREAD

**Issue by kurtharriger** [grafana/grafana#2070]
We would like the ability to do something like select mean(value)/10, but this doesn't seem to be possible via the query builder.  It does work in raw query but gets lost when toggling back to the editor view.  
In most cases you could probably do mean of value/10 instead, but this does not (currently) work with influx 0.9.

**Comment by torkelo** [comment]
Ok, will try to think about this,  please put feedback for InfluxDB 09 support in #1525 as it a feature that is still undergoing basic work and revisions
