### ISSUE TITLE
Confusing "label" verbiage for Loki explore page

### ISSUE THREAD

**Issue by fitzoh** [grafana/grafana#20715]
**What would you like to be added**:
I would like the "row stats" box that pops up when you click a key/value pair on the loki explore screen to not use the word `label`.

<img width="504" alt="Screen Shot 2019-11-27 at 3 05 35 PM" src="https://user-images.githubusercontent.com/131809/69756226-fa5cbd80-1127-11ea-87bf-87f7c86079cf.png">

**Why is this needed**:

As a new Loki user, it is confusing that this is referred to as a label, yet I am not able to search by it as a log label. 

The screen shot above leads me to believe that I can use the query`{thread_name="main"}`, yet it yields no results.

**Comment by davkal** [comment]
Hi @fitzoh if the labels "thread_name" with value "main" appears in the "Log Labels" section of an expanded log row for Loki, you should absolutely get results for a query like `{thread_name="main"}`.

Could there be another issue, e.g. the query does not return?
Could you also try to simply click on the magnifying glass next to "thread_name" in the log row details? That should add this label to the existing selector in the query.

**Comment by fitzoh** [comment]
Closing, looks like this is no longer valid as of Grafana 6.5
(Initial screenshot was before the row display reformat)
