### ISSUE TITLE
Login Credentials Shown in Browser URL in plaintext when repeatedly attempting to login

### ISSUE THREAD

**Issue by andrewmaksymowsky** [grafana/grafana#20719]
**What happened**:
On the login screen for grafana I rapidly clicked the Log In button (using firefox 70.0.1+build1-0ubuntu0.19.10.1 as my browser) I noticed that my login credentials appear in plaintext in the address bar's url. Since the traffic is over https they are not sent in plaintext over the network. However it seems to me bad practice to show login credentials in plaintext in the url.

**What you expected to happen**:
I would expect not to see the login credentials in plaintext in my browser's address bar.

**How to reproduce it (as minimally and precisely as possible)**:
On Grafana login screen (with local user account, no backend auth system). Repeatedly click the login button while watching the browser's address bar.

**Anything else we need to know?**:

**Environment**: Ubuntu 16.04.4 LTS Server
- Grafana version: Grafana v6.4.4 (commit: 092e514)
- Data source type & version: Graphite
- OS Grafana is installed on:Ubuntu 16.04.4 LTS Server
- User OS & Browser: Ubuntu 19.10 and firefox 70.0.1+build1-0ubuntu0.19.10.1
- Grafana plugins: NA
- Others: NA

**Comment by torkelo** [comment]
eh, that sounds super strange. Nowhere do we update the url with the password. 

Maybe a browser extensions your using? Try in incognito mode? Do you get this in other browsers then firefox?

**Comment by andrewmaksymowsky** [comment]
Thanks for following up. I don't get the same behavior in a private window or with different browsers. Unfortunately I don't have any extensions installed. That being said I was able to reproduce it until clearing my browser's cache so I'm guessing it was something with the browser rather than with grafana. Please feel free to mark this as closed and thanks again for your help !

**Comment by torkelo** [comment]
could replicate on  https://play.grafana.org/login

super strange, will investigate

**Comment by andrewmaksymowsky** [comment]
Interesting, then perhaps it wasn't the browser cache. Thanks for looking into this !

**Comment by daniellee** [comment]
It is due to the form being submitted with the HTTP GET verb instead of POST.
