### ISSUE TITLE
Percentage of multiple series for simple json datasource.

### ISSUE THREAD

**Issue by chetan-mehta707** [grafana/grafana#20712]
Is there a way by which we can plot the percentage values of a series.
I can see the feature is supported for elastic search, is there anything similar supported for JSON data source.

So, to describe the use case we are using multiple panel queries for getting Success and Total, which are absolute values, but while plotting it on time series graph we want to plot the percentage of success out of total rather than the absolute value.
Can someone suggest a way to achieve this?

**Comment by chetan-mehta707** [comment]
@torkelo

**Comment by torkelo** [comment]
closing this as it's not supported by the json data source 

We are adding a transformation step (that will work with any data source), it will be able to handle use cases like this
