### ISSUE TITLE
Tags in alert webhook payload not as specified in Alert configuration

### ISSUE THREAD

**Issue by davecampbell** [grafana/grafana#20714]
**What happened**:
i specified some tags in an alert using the 'Tags' section in the notification.
then i triggered the alert.
then i looked at the tags in the body.EvalMatches[].tags.

**What you expected to happen**:

i expected to see the tags that i specified in the alert configuration.

**How to reproduce it (as minimally and precisely as possible)**:
make an alert.
enter tags.
trigger alert.
inspect tags in webhook payload.

**Anything else we need to know?**:

the metrics are from cloudwatch.
Dimensions from the cloudwatch metrics did show up as tags in the payload.

can find the unanswered question in community here:
https://community.grafana.com/t/tags-in-alert-webhook-payload-not-as-specified-in-alert-configuration/23282

**Environment**:
- Grafana version: Grafana v6.3.2 (4832460)
- Data source type & version: cloudwatch
- OS Grafana is installed on: hmm...not sure.  probably linux.
- User OS & Browser:
mac high sierra 10.13.6 (17G9016)
chrome Version 78.0.3904.108
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
#18233 fixed and release in 6.4.0

**Comment by davecampbell** [comment]
thanks - will look into update.  sorry i didn't research further.
