### ISSUE TITLE
Loki explore page stats button overflow

### ISSUE THREAD

**Issue by fitzoh** [grafana/grafana#20716]
**What happened**:

I hovered over a log entry near the edge of an explore page, and the stats button showed up on the next line.

When I attempt to move the cursor to the button, it goes away.

**What you expected to happen**:

To be able to click the stats button (preferably without resizing the window).

**How to reproduce it (as minimally and precisely as possible)**:

![2019-11-27 15 18 01](https://user-images.githubusercontent.com/131809/69756829-6a1f7800-1129-11ea-87f0-46678fee1c76.gif)
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: Loki

- OS Grafana is installed on: OSX
- User OS & Browser: OSX + Chrome
- Grafana plugins: None
- Others:

**Comment by papagian** [comment]
In Grafana [6.5](https://grafana.com/docs/guides/whats-new-in-v6-5/#explore-logs-log-row-details) it is simplified the way log row labels/fields are displayed.

**Comment by fitzoh** [comment]
Awesome, new version is a big improvement :)
