### ISSUE TITLE
Alert in Grafana with Loki as datasource is not working

### ISSUE THREAD

**Issue by danieldabate** [grafana/grafana#20717]
We are using Loki's new feature and creating graphs in Grafana based on our logs. But when we try to create an alert for one of those graphs Loki returns an error with code 400 for the alert queries.

1. Create a graph in Grafana (6.5.0) with Loki as a datasource
2. Set an alert for that graph
3. Press the "Test Rule" button
4. This error is returned in Grafana: _tsdb.HandleRequest() error bad_response: invalid character 'r' looking for beginning of value_

**Environment:**
- Grafana: 6.5.0
- Loki: 1.0.0

**Request and Response**
`400 "GET /loki/api/v1/query_range?end=2019-11-27T17%3A57%3A08.882382003Z&query=rate%28%28%7Bnamespace%3D%22platform%22%7D+%7C~+%22Thread+.%2A+has+been+blocked%22%29%5B1m%5D%29&start=2019-11-27T17%3A56%3A58.882382003Z&step=15.000 HTTP/1.1" 82 "-" "Go-http-client/1.1" "-"`

_Disclaimer: I'm not sure if this is an issue in Loki or in Grafana. Please let me know if I should report this to the Grafana team._

**Comment by danieldabate** [comment]
I queried Loki directly with the exact same query and this is the response:
`rpc error: code = Code(400) desc = strconv.Atoi: parsing "15.000": invalid syntax`

**Comment by danieldabate** [comment]
@cyriltovena according to the Prometheus docs the `step` variable should be a float. Shouldn't Loki be using `Atof` instead of `Atoi` to parse the string?

`step=<duration | float>: Query resolution step width in duration format or float number of seconds.`
https://prometheus.io/docs/prometheus/latest/querying/api/

**Comment by cyriltovena** [comment]
Yes it should we have an issue for it. It should be fixed soon. https://github.com/grafana/loki/issues/1209 I'll will do it if there is no movement.

**Comment by danieldabate** [comment]
That seems to be the issue then. I will close this and follow https://github.com/grafana/loki/issues/1209.

**Comment by marefr** [comment]
Grafana doesn't have a backend implementation for Loki why Grafana alerting is currently not supported.

**Comment by danieldabate** [comment]
But Loki now supports metric queries with the same API than Prometheus. I would think no extra implementation should be done if Loki is set up as a Prometheus datasource. Am I missing something?

**Comment by cyriltovena** [comment]
@marefr Loki has the same API for metrics as Prometheus does, except that little issue here  grafana/loki#1209.

**Comment by marefr** [comment]
Oh yeah that's right. Didn't consider that one :+1:

**Comment by danieldabate** [comment]
FYI: This is fixed in Loki 1.1.0

**Comment by hervenicol** [comment]
I tried creating an alert with Grafana 6.6 and Loki 1.3.0; when I want to set an alert I get "The datasource does not support alerting queries". :(

**Comment by danieldabate** [comment]
You have to set up Loki as a Prometheus datasource to have alerts from
logs. I believe you can find more info on how to make the queries in Loki's
docs. It's very similar to querying Prometheus.

It's not possible to have alerts from Loki as a Loki datasource, which
returns text instead of metrics.

**Comment by hervenicol** [comment]
Thanks for the tip !
I've had difficulties finding the info (/loki for the prometheus API), but now it works.

I'm a bit confused that I can run the same query via either the prometheus or the Loki API, have the same results, but not the same functionalities.
By the way, it fixed my legend variables as well.

**Comment by agordeev** [comment]
@hervenicol did you find the docs?

**Comment by hervenicol** [comment]
https://github.com/grafana/loki/blob/v1.5.0/docs/api.md
> The API endpoints starting with /loki/ are Prometheus API-compatible and the result formats can be used interchangeably.

If your Grafana config for the Loki datasource is `http://loki:3100`, you can create a Prometheus datasource with URL `http://loki:3100/loki`.

**Comment by service-circleci** [comment]
thank you @hervenicol that's exactly what I needed!

**Comment by leepatrick-goop** [comment]
Thank you @hervenicol this is exactly what I needed!
