### ISSUE TITLE
Grafana 6.5.0 breaking FlowCharting plugin

### ISSUE THREAD

**Issue by cbtsgithub** [grafana/grafana#20713]
Grafana breaks network map panel 0.5.0 plugin.
[Network Map Panel-1574881077182.zip](https://github.com/grafana/grafana/files/3898418/Network.Map.Panel-1574881077182.zip)

**Comment by cbtsgithub** [comment]
Not network map panel, but panel created with FlowCharting plugin.
Sorry for confusion.
Panel attached in previous mail.

**Comment by dprokop** [comment]
@cbtsgithub Thanks for reporting this. Can you please check and share with us what is the actual error? You can check it out in the console.

**Comment by cbtsgithub** [comment]
Hello,
in fact the screen is totally blakc. Nothing appears (i mean no panel with Flowcharting plugin).
I attached the panel which doesn't work with 6.50 but that worked whith 6.45.
Regards
Chris

**Comment by cbtsgithub** [comment]
Hello,
the bug disappeared with 6.5.1 version.
Thanks.
Chris

**Comment by dprokop** [comment]
@cbtsgithub that's great news. The problem was most probably related to https://github.com/grafana/grafana/pull/20696

**Comment by algenty** [comment]
yes i've already noted that in issue https://github.com/grafana/grafana/issues/20255
Hi @dprokop,
i need to replace by /**@ngInject*/ in my code ?
