### ISSUE TITLE
Templated dimension value not working in alias field in v6.5.0 and v6.5.2

### ISSUE THREAD

**Issue by eddgrant** [grafana/grafana#20729]
**What happened**:

I have a Dashboard widget which utilises 2 CloudWatch queries. 

**Query 1:**
![image](https://user-images.githubusercontent.com/604861/69790938-545a9300-11bb-11ea-87e4-bb68b7fd7a61.png)

Query Preview: Grafana doesn't show a query preview for this query for some reason:

![image](https://user-images.githubusercontent.com/604861/69791289-17db6700-11bc-11ea-877e-1e451b4f0161.png)

**Query 2:**

![image](https://user-images.githubusercontent.com/604861/69790988-72c08e80-11bb-11ea-9079-224e449d4668.png)

Query Preview:

    REMOVE_EMPTY(SEARCH('{AWS/ApplicationELB,AvailabilityZone,LoadBalancer,TargetGroup} MetricName="RequestCount" "AvailabilityZone"=("eu-west-2a" OR "eu-west-2b" OR "eu-west-2c") "LoadBalancer"="app/my-alb-public-0/6bbf16dee1973503" "TargetGroup"="targetgroup/my-p-Targe-1E42IS8X9CCDR/3f97bdfac4f53fb6"', 'Sum', 60))

When I upgraded to Grafana v6.5.0 the expansion of `{{AvailabilityZone}}` dimension, used in the `alias` field of the 2nd query has stopped working. It now seems to be considered as a literal string in the display of the graph:

![image](https://user-images.githubusercontent.com/604861/69791420-6852c480-11bc-11ea-9bd2-ae2784570de1.png)

**What you expected to happen**:

I expect the `alias` value of `request-count-{{AvailabilityZone}}` in the 2nd query to be expanded to represent each of the selected availability zone's e.g.

* request-count-eu-west-2a
* request-count-eu-west-2b
* etc...

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

I have discovered that this _does_ work in the following circumstances:

1. If I disable query 1, then the expansion of `{{AvailabilityZone}}` in the 2nd query starts working correctly:

![image](https://user-images.githubusercontent.com/604861/69791629-cf707900-11bc-11ea-8361-a9bf6b5b02ea.png)

2. With query 1 enabled, the expansion of `{{AvailabilityZone}}` in query 2 _does_ work _if I select just a single Availability Zone_:

![image](https://user-images.githubusercontent.com/604861/69791703-faf36380-11bc-11ea-8f30-df3d3cb7e3cf.png)

**Environment**:
- Grafana version: Grafana v6.5.0 (24a5d2f)
- Data source type & version: CloudWatch
- OS Grafana is installed on: Ubuntu Server
- User OS & Browser: Ubuntu 19.10 running Chrome
- Grafana plugins: CloudWatch
- Others:

Hope I have articulated the problem clearly enough, please don't hesitate to give me a shout if you need any further information to understand the issue.

**Comment by eddgrant** [comment]
Here's an export of the dashboard to exhibit the problem. I have had to heavily sanitise variable values etc so you'll see a lot of contrived values such as "my-ecs-cluster" etc.

[dashboard-export.zip](https://github.com/grafana/grafana/files/3900868/dashboard-export.zip)

**Comment by sunker** [comment]
Thanks for reporting this @eddgrant! 

I cannot reproduce this. Don't have any data in ApplicationELB, but I guess it shouldn't matter what namespace is being used. 

> Query Preview: Grafana doesn't show a query preview for this query for some reason:
Grafana will only generate expressions in case you use a wildcard (`*`), a multi-valued template variable or if the match exact toggle is false. 

I know it's not necessarily the same thing, but if you replace the `$availabilityZone` variable with a `*`, would it work then?

**Comment by eddgrant** [comment]
Hi @sunker ,

Sorry for the delay in getting back to you, replacing `$availabilityZone` with `*` does indeed cause the aliases to be generated correctly.

As you mention though, it's not quite the same thing, particularly in my case as I'm using a multi valued variable to select which AZ's to display in the widget and using `*` causes the widget to display _all_ the AZs rather than just the selected ones.

![image](https://user-images.githubusercontent.com/604861/71076173-2c889a80-217d-11ea-8e0b-2b29e7c1e001.png)

Also, thought it might be worth confirming that I've tried this on `6.5.2 (742d165)` this morning and it behaves in the same way as v6.5.0.

Hope that helps, let me know if there's anything more I can provide to help figure this one out.

**Comment by jveldboom** [comment]
We're experiencing a similar issue but wanted to give another example which I believe is easy to replicate. We're trying to use the alias `{{Method}} {{Resource}}` to display something like `GET /endpoint` which previously worked. But now we're seeing this:

![image](https://user-images.githubusercontent.com/303202/71259675-fb3bd600-2306-11ea-958b-b7e8742808a9.png)

Seems to give you same results no matter what dimension name you add:

![image](https://user-images.githubusercontent.com/303202/71259840-55d53200-2307-11ea-8603-5b892611640f.png)

**Comment by sunker** [comment]
@eddgrant @jveldboom does it work if you replace dimension name within brackets with label? 
eg: `request-count-{{AvailabilityZone}}` --> request-count-{{label}}

**Comment by jveldboom** [comment]
Yes, that does kind of work but just not as it did before where you can specify the each dimension names individually. I'm assuming this is related to using the different CloudWatch API.

For example using just `{{label}}`:
![image](https://user-images.githubusercontent.com/303202/72451138-75863b80-3789-11ea-87ab-5998d9da9f60.png)

And another one using `{{label}} -- {{Stage}}` seems to duplicate `{{label}}`:
![image](https://user-images.githubusercontent.com/303202/72451402-dd3c8680-3789-11ea-98d7-4087cf07c9c0.png)

Also, here's a small snippet of the JSON from the query inspector which might help explain why those variables are not being set:

```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1579084031545",
      "to": "1579105631545",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 30000,
          "maxDataPoints": 794,
          "datasourceId": 1,
          "type": "timeSeriesQuery",
          "alias": "{{label}} -- {{Stage}}",
          "dimensions": {
            "ApiName": [
              "Content Finder Api (production)"
            ],
            "Method": [
              "*"
            ],
            "Resource": [
              "*"
            ],
            "Stage": [
              "*"
            ]
          },
          "expression": "",
          "id": "",
          "matchExact": true,
          "metricName": "Count",
          "namespace": "AWS/ApiGateway",
          "region": "us-east-1",
          "statistics": [
            "Sum"
          ],
          "datasource": "fott",
          "period": "60"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "gmdMeta": [
            {
              "Expression": "REMOVE_EMPTY(SEARCH('{AWS/ApiGateway,ApiName,Method,Resource,Stage} MetricName=\"Count\" \"ApiName\"=\"Content Finder Api (production)\"', 'Sum', 60))",
              "ID": "queryA"
            }
          ]
        },
        "series": [
          {
            "name": "POST /v1/graphql -- POST /v1/graphql",
            "points": [
              [
                1,
                1579099620000
              ]
            ],
            "tags": {
              "ApiName": "Content Finder Api (production)",
              "Method": "POST /v1/graphql",
              "Resource": "POST /v1/graphql",
              "Stage": "POST /v1/graphql"
            }
          }
        ],
        "tables": null,
        "dataframes": null
      }
    }
  }
}
```

**Comment by sunker** [comment]
I've found the problem now. Same issue as in #20927. 

See suggested solution [here](https://github.com/grafana/grafana/pull/21541). Would be great if someone could test and verify that it works @eddgrant  @jveldboom

**Comment by eddgrant** [comment]
Sorry for the delay in replying, have tested on `6.5.3` and can confirm that using `{{label}}` _does_ indeed resolve the issue for us.

![image](https://user-images.githubusercontent.com/604861/72533258-c4f16800-386c-11ea-8c51-bf15874b0330.png)

**Comment by eddgrant** [comment]
Aah, just seen https://github.com/grafana/grafana/issues/20729#issuecomment-575154013, will see if I can verify this.

**Comment by eddgrant** [comment]
Have just realised that in order to test this I think I'll need to build your Grafana branch @sunker? If that's the case, is there by any chance a pre-built Docker image in a public registry somewhere that I can pull to test your change? Thanks!

**Comment by sunker** [comment]
Sure! `docker pull grafana/grafana:master`

**Comment by eddgrant** [comment]
Finally had a chance to test this in v6.6.0 (sorry for the delay). I can confirm that the dimension values are now being correctly expanded for us :+1: . The only thing I'm not 100% certain about is that when the selected time period doesn't yield any data for a data series we still get the literal alias printed on the legend.

Here's an example of a 100% stacked graph which shows the split of 2/3/4/5xx HTTP requests. In the configured time period we can see that there were 2xx requests in `eu-west-2c` and 3xx requests in `eu-west-2a` and `eu-west-2c`, the aliases for these are correctly expanded.

However we can also see that there were no 4xx or 5xx requests in the configured time period, these aliases are written as literals so display as `4xx-{{AvailabilityZone}}` and `5xx-{{AvailabilityZone}}` respectively.

![image](https://user-images.githubusercontent.com/604861/73750668-79d4c180-4755-11ea-8753-85266c37e1f7.png)

This might be existing behaviour but thought I'd mention it in case it was a new nuance in behaviour.

Thanks for the work in resolving the issue! :pray:

**Comment by eddgrant** [comment]
Hi @sunker,

I was curious about the above behaviour so loaded the same dashboard in v6.4.5. I can confirm that this does correctly expand the templated variables when there is no data for the configured time period, this is shown in the image below:

![image](https://user-images.githubusercontent.com/604861/73757894-cde5a300-4761-11ea-989a-008c1b5de436.png)
 
This suggests to me that there is still some regression in the 6.5.x release behaviour in this regard. Would be grateful to get your thoughts on this. If you agree we could re-open this issue or raise it as a new issue. Let me know what you think is best?

Many thanks!

**Comment by craigedmunds** [comment]
I have the genesis of a fix now - the issue appears to be the precedence given to the cloudwatch resultset when generating series, rather than the query. When the resultset doesn't have any data matching part of the query, no series is generated for it, and there are issues with alias expansion.

![image](https://user-images.githubusercontent.com/1453591/73944880-4035bf00-48eb-11ea-8bd1-202e8ec0b830.png)
