### ISSUE TITLE
Table Panel in loading state till I interact with the page

### ISSUE THREAD

**Issue by GuruCharan94** [grafana/grafana#20724]
**What happened**
When using the table panel, it stays in loading until I interact with the page by starring the dashboard, resizing/moving other panels or interacting with a textbox variable etc. I assume the data is already loaded because the table shows the total number of pages wherever pagination is configured. *Also, please note that this behaviour is not consistent. Sometimes the panel loads just fine.* 

**What you expected to happen**: I expected the table to show the data without a need for me oto interact and not be stuck in loading state.

**How to reproduce it (as minimally and precisely as possible)**: Create a table panel and use Azure Data Source and run a log analytics query.

**Anything else we need to know?**: 
Here is a [small video recording](https://www.loom.com/share/4aa58b35ec184285bf9d2c4c99c44872) of the bug.

**Environment**:
- Grafana version: The latest Docker Image of grafana:master - Grafana v6.5.0 (24a5d2f)
- Data source type & version: Azure Monitor Data Source
- OS Grafana is installed on: Running on Azure Web App for Containers
- User OS & Browser: Windows 7, Chrome 78
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
thanks for reporting this.
