### ISSUE TITLE
Explorer grafana 6.4.4 url parameters mode logs

### ISSUE THREAD

**Issue by fredbcode** [grafana/grafana#20731]
Hello,

With explorer url parameter {"mode":"logs"} is not working and when you switch to this mode the Lucene query disappear 

Steps to reproduce:

1 - made a request to explorer and switch to logs (the query disappear ...)
2 - re-type the query and copy the url to another tab
3 - paste the url, now explorer is in metrics mode 

Adding {"mode":"logs"} is not enough 

So we can't share an url in logs mode (eg by mail) 

Thanks

**Comment by papagian** [comment]
I have verified that the lucene query disappears even in the play site (6.5.1 version)

**Comment by marefr** [comment]
Not sure if it's a bug or a feature. Will have the Observability squad have a look at it.

**Comment by ivanahuckova** [comment]
This issue is fixed on current master (see video below). I think it was fixed by @kaydelaney in one of her recent PRs. 🙂
![ezgif com-video-to-gif (17)](https://user-images.githubusercontent.com/30407135/72070417-d6c19100-32e9-11ea-8e0d-88460397fcc7.gif)

**Comment by fredbcode** [comment]
Great !

**Comment by ivanahuckova** [comment]
Following PR closes this issue #20890.
