### ISSUE TITLE
TablePanel: Support multi valued variables in table cell links 

### ISSUE THREAD

**Issue by JonasDeGendt** [grafana/grafana#20733]
**What happened**:
I extensively use things such as panel links to direct people from one dashboards to the other. E.g., a panel on a cluster level displaying memory usage per Kubernetes namespace, that redirects to a namespace deep dive dashboard. Really liking the new updated way of creating links that was released recently, using `${__all_variables}` to render the URL makes it all too easy.

However, table links do not have the same behavior as panel links. As `${__all_variables}` doesn't seem to be available in table links, you have to define your variable yourself, which breaks the destination dashboard if you have multiple options selected.

Take for example a dashboard with a multi-select namespace variable:

A panel link using `${__all_variables}` with a multi-select option for the namespace translates to `&var-namespace=a-namespace&var-namespace=a-second-namespace` in the URL. Each selected option is added as an additional variable to the query string. The destination dashboard ticks the right boxes correctly.

`${__all_variables}` is not available in a table link, no problem, I'll just manually add the variable to the link as `var-namespace=$namespace`, which renders to `&var-namespace=a-namespace,a-second-namespace` in the URL, breaking the destination dashboard variable.

**What you expected to happen**:

Using multi-select variables in a link to render as separate variables, instead of a list. 

**How to reproduce it (as minimally and precisely as possible)**:

Try the above :) 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: OSX/Firefox
- Grafana plugins: None
- Others: None

**Comment by hugohaggmark** [comment]
Closing this issue as I can't repro it on Grafana v7.4.0-pre (db637a3630) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
