### ISSUE TITLE
Table panel pagination highlighting needs better accessibility

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#20739]
**Steps to reproduce**:
If I remove all color, the highlighting of the table panel pagination is hard to see. So might be a problem for people with color blindness. You can use the Spectrum browser extension in Achromatopsia mode to reproduce the problem.
<img width="597" alt="Screenshot 2019-11-28 at 12 40 41" src="https://user-images.githubusercontent.com/53754871/69803993-df4c8500-11dd-11ea-98bd-ea73abfcde8d.png">

**How to improve**:
I would recommend using not only text color to highlight the active page but also adding a background highlight. The hover state of the active page has a background box, maybe that box could be the regular state and on hover the link text could get an underline.

**Environment**:
- Grafana version: 6.5
- Data source type & version: gdev test data

**Comment by mckn** [comment]
@jessover9000 I did a review of the #30957 PR and just wanted to check that this issue still is aligned with the current design system roadmap.

**Comment by zoltanbedi** [comment]
I'm going to close this issue as we are using new table panel with new pagination.
