### ISSUE TITLE
User input on dashboard?

### ISSUE THREAD

**Issue by niclask** [grafana/grafana#2074]
Hi,
I have used grafana to display data collected by a small embedded system. The data is collected via MQTT and stored in influxdb.

I have the possibility to get/set properties on the embedded system using MQTT. I would be nice if it was possible to add some widgets (input field, checkboxes, drop down menu, etc) to a dashboard. Using the widgets I would be able to modify the properties on my device. I guess a plug in for datasource (datasink?) MQTT is needed to handle the communication.

Thanks for a great app!
Niclas

**Comment by torkelo** [comment]
grafana is open source so you can do anything of you want custom protocols and and panels :)
