### ISSUE TITLE
React Query Editor no access to Data when streaming

### ISSUE THREAD

**Issue by Sintifo** [grafana/grafana#20749]
**What happened**:
When writing a datasource plugin using the new React approach and the datasource uses Streaming Queries the data prop is always undefined. This makes it impossible to access
the panelId which is important to distinguish queries all the time.

**What you expected to happen**:
Data prop is defined with state: STREAMING and request.

**How to reproduce it (as minimally and precisely as possible)**:
Probably Loki is the easiest to reproduce, since I am stilling waiting for a LICENSE to open source my work. 
And a minimal working example of streaming is hard.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version: custom datasource
- OS Grafana is installed on: Linux | Docker
- User OS & Browser: Chrome | Firefox
- Grafana plugins: only custom datasource
- Others:

**Comment by torkelo** [comment]
The streaming data you return, does it contain a refId (source query refId) , then it should be piped to the Query Editor

**Comment by Sintifo** [comment]
Thanks for your answer!

No I'm only returning a key
```
return {
          data,
          key: `stomp-streaming-${target.refId}`,
          state: LoadingState.Streaming
        };
```
due to the ``DataQueryResponse`` only specifying a key to distinguish the different targets
```
export interface DataQueryResponse {
    /**
     * The response data.  When streaming, this may be empty
     * or a partial result set
     */
    data: DataQueryResponseData[];
    /**
     * When returning multiple partial responses or streams
     * Use this key to inform Grafana how to combine the partial responses
     * Multiple responses with same key are replaced (latest used)
     */
    key?: string;
    /**
     * Optionally include error info along with the response data
     */
    error?: DataQueryError;
    /**
     * Use this to control which state the response should have
     * Defaults to LoadingState.Done if state is not defined
     */
    state?: LoadingState;
}
```
I have `@grafana/data`  version 6.5.1 installed.

**Comment by torkelo** [comment]
You need to return a refId so Grafana knows which query the data is associated with  (refId is the A, B, C) that is on every query (target) model

**Comment by Sintifo** [comment]
Thanks for your help!

I got it working now. The comments on the interface are removed because they are only inline comments.

I will send a PR on monday making them doc comments and referencing the QueryResultBase, to prevent others from making the same mistake.
