### ISSUE TITLE
Keyboard-only usability needs improvement: Highlighting in left-hand navigation

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#20742]
**Steps to reproduce**:
Tabbing through a Grafana view, I can only see that my tab presses are triggering actions thanks to the URL preview in the browser window – Grafana itself doesn't give me visual feedback for the left-hand navigation at all. The visual feedback only starts once I'm in the toolbar.

**Actual Result**:
No highlighting or focus state for the left-hand navigation.

**Expected Result**
The navigation icons could light up/darken depending on selected theme, maybe there could also be a change in background color to highlight the currently active navigation point.

**Environment**:
- Grafana version: 6.5

**Comment by tskarhed** [comment]
Fixed when global link focus styles were added.
