### ISSUE TITLE
Access to multi-value variable items 

### ISSUE THREAD

**Issue by rfcard** [grafana/grafana#20744]
Hi,

I'm having trouble accessing multi-value variable items.
I think multi-value variables are like arrays:

Multi-value variable name: $varTest
Multi-value variable items:
[0], __selected: True, __text: "Label 01", __value: "code01"
[1], __selected: False, __text: "Label 02", __value: "code02"
[2], __selected: False, __text: "Label 03", __value: "code03"
[3], __selected: True, __text: "Label 04", __value: "code04"
[4], __selected: True, __text: "Label 05", __value: "code05"

I want to access a item value like: $varTest[2].__text (expected value: "Label 03")
I desire to use this value in alias of TimeSeries query.

**Comment by xlson** [comment]
Not sure that is possible. What data source are you using, what does the query look like and what version of Grafana are you using?

**Comment by rfcard** [comment]
We are using MySQL datasource to create a multi-value variable with __text property.
The data is queried in InfluxDB datasource. The result is ok, but the names of obteined TimeSeries is not good to users. So I desire to use in the alias of TimeSerie the same __text showed to user in the html select box.

**Comment by torkelo** [comment]
access like this is not supported (not very likely to be added either)
