### ISSUE TITLE
reset email link,previous credentials not working

### ISSUE THREAD

**Issue by ziaul916** [grafana/grafana#20745]
Steps are-Install grafana.login.Again uninstall
                 Install again.Now login with same credentials or try to reset passord

Issue-On clicking on reset password,no email link is send to registered email
          If login with same previously defined credentials,invalid username,password coming

**Comment by xlson** [comment]
Have you configured an email server for Grafana to use? See https://grafana.com/docs/installation/configuration/#smtp

**Comment by ziaul916** [comment]
Hi,

Its still not working.Is there any process to  set default password admin
as it was at first tine installation.

Warm regards,
Arfeen

**Comment by ziaul916** [comment]
Can you please rest my password and user to admin?

**Comment by xlson** [comment]
@ziaul916 You can use the grafana cli to change the admin password of Grafana (https://grafana.com/docs/administration/cli/#reset-admin-password]).
