### ISSUE TITLE
String 'watch' in alias broke the graph

### ISSUE THREAD

**Issue by luisdalves** [grafana/grafana#2075]
Hi All,

When you use 'watch'  string for an alias, the line in the graph dissapear.

Example of error:
alias(servers.$instance.zookeeper.watch, 'watch')

I saw some DOM errors when this happens but I'm not sure if this have relation:
Expected color but found 'function'. from DOM

Regards

**Comment by torkelo** [comment]
sure it is not a graphite issue? I tried to use watch as an alias on a bunch of graphite queries without issue, what graphite version do you use?

**Comment by luisdalves** [comment]
Hi Torkelo,

I'm using the following versions:
graphite-carbon                  0.9.12-3
graphite-web                      0.9.12+debian-3
grafana                               2.0.2

I didn't find any error on graphite log when this happens, just this:
rendering.log:Sat May 30 14:55:29 2015 :: Retrieval of alias(servers.flowics-birdman02.zookeeper.watch, 'watch') took 0.004962

So graphite appears to be working fine.

Let me know if you need more information.

**Comment by torkelo** [comment]
do you get this on all queries or just this? Can you replicate it on play.grafana.org?

**Comment by luisdalves** [comment]
I'm obtaining this on all queries when I used 'watch' alias. I couldn't replicate this on play.grafana.org :(

**Comment by torkelo** [comment]
Must be something wrong with graphite then for it seems like it is returning an error in your case. Not sure what's going on.

**Comment by damm** [comment]
Grafana can handle the alias's built in; Its been a long time I used graphite but I saw some buggy behavior when I used the alias knob.

There's no point in using alias as Grafana can rename/make friendly names (alias's) if you need to.
