### ISSUE TITLE
Azure Monitor datasource support for Application Insights in Government Cloud

### ISSUE THREAD

**Issue by AndrewTamm** [grafana/grafana#20759]
As of May 2, 2019, Application Insights is available in Azure Government Cloud, see: https://azure.microsoft.com/en-us/updates/application-insights-available-in-usgov-virginia/

Azure Monitor data source plugin however only attempts to access the standard endpoints, so application ids in the government region fail. 

There should be a way to select the proper region in the UI to support this addition.

**Comment by daniellee** [comment]
@AndrewTamm we noticed that support for Application Insights also got added to [Azure China](https://azure.microsoft.com/en-gb/updates/application-insights-availability-in-china-east-2/) recently. 

This is not planned for the upcoming 6.6 release but something we definitely should support. 

We have a lack of documentation when it comes to implementing this feature request so some research and experimenting will need to be done first. 

Application Insights can be queried in 3 different ways:
1. the old REST API (which uses a HTTP header for authentication)
2. through the Azure Monitor REST API
3. through the Application Insights Analytics API (using the Kusto SQL query language). 

I couldn't find any documentation for how to use the old REST API on different clouds. Option 2 is documented for Azure Monitor but not Application Insights (discovered that it works through experimentation) but we could figure this out I think. Option 3 is what is linked to in the announcement and while undocumented should be similar to option 2.

**Comment by sunker** [comment]
We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics). I'm closing this issue now, but feel free to reopen if you feel the need to.
