### ISSUE TITLE
Alert threshold can't be dragged to fractional value

### ISSUE THREAD

**Issue by Arcturuss** [grafana/grafana#20756]
**What happened**:
I have a graph with Y axis between 0 and 1, unit configured as "percent (0.0-1.0)". I want to set an alarm to 80% (0.8), but drag-n-drop threshold marker can be only set to 1.0 or 0.0.
Input field for threshold value works fine.

**What you expected to happen**:
I should be able to set alarm threshold to any reasonable value between the max and min values of graph.

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph with Y-min = 0 and Y-max = 1. Add an alarm. Try to drag the threshold marker to any point between 0 and 1.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0 (docker)
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10, Chrome 78.0.3904.108
- Grafana plugins: default
- Others:

**Comment by zuchka** [comment]
I think we can close this now that legacy alerting is deprecated 👍
