### ISSUE TITLE
Build Grafana from Source in Windows don't work for Grafana 6

### ISSUE THREAD

**Issue by pwSteve** [grafana/grafana#20768]
Hello,

I downloaded the last version of Grafana 6 source files to build from source. Now, always when i want execute `go run build.go setup` or `go run build.go build`, than i become this message:

`go: github.com/BurntSushi/toml@v0.3.1: Get https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod: Not Implemented`

I made the same thing before with Grafana 5 and that worked very fine, without problems.

I also didn't find a documentation for windows, only the documentation for macOs.

**Comment by torkelo** [comment]
what version of Go are you using?

**Comment by pwSteve** [comment]
I want build Grafana 6.5.1
My Go version is `go1.13.4 windows/amd64`. I have Windows 10.

**Comment by marefr** [comment]
@pwSteve you've checked out the `v6.5.x` branch or `v6.5.1` tag? Then try `go run -mod=vendor build.go build`.

**Comment by pwSteve** [comment]
@marefr thank you, that worked.
