### ISSUE TITLE
[Bug] Gauge and Bar Gauge crash when they meet high percentage 

### ISSUE THREAD

**Issue by hohozhao** [grafana/grafana#20764]
**What happened**:
When I use Grafana to pull memory utilization (percentage 0-100), one of my servers is about 30% and the plotting works well, but another server is about 98% and plotting crashes. 100% reproducible, both in the lastest Chome and Firefox.

**What you expected to happen**:
No crashes.

**How to reproduce it (as minimally and precisely as possible)**:
Gauge, units -> percentage, 0-100. The metric > 95 (I guess).

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest 6.5.1
- Data source type & version: latest Zabbix 4.4
- OS Grafana is installed on: RHEL7.6
- User OS & Browser: latest Chrome and Firefox
- Grafana plugins: Zabbix 3.10.4
- Others:

**Comment by hohozhao** [comment]
This was seen *after* it crashes.
<img width="1422" alt="Screen Shot 2019-11-29 at 10 35 12 AM" src="https://user-images.githubusercontent.com/22469290/69840237-c30c1f00-1295-11ea-9178-a2d79fb07e2c.png">

**Comment by dprokop** [comment]
@hohozhao thanks for reporting this. I have tried reproducing this problem but unfortunately without success yet. What other panels do you have on your dashboard?

**Comment by torkelo** [comment]
This is related to a zabbix issue, https://github.com/alexanderzobnin/grafana-zabbix/issues/823

**Comment by maxlehot1234** [comment]
@torkelo Any news for the next 3.11 version of the zabbix plugin for grafana?

More than a month without anything from alexander :(
