### ISSUE TITLE
Loki: Sync log time accross panels

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20761]
**What would you like to be added**:

The ability to see logs that happens at the same time side to side (at the same position)

Currently it is hard to correlate messages by time:
![comp](https://user-images.githubusercontent.com/291750/69831759-29a82300-122b-11ea-83e1-b9c0525c08b8.png)

**Why is this needed**:

Easy comparison of logs that come from different sources

**Comment by aocenas** [comment]
@roidelapluie can you give more details what would you like to be added/changed here? Or if this is still relevant?

**Comment by torkelo** [comment]
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.
