### ISSUE TITLE
Empty metric name in explore is replaced by the query

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#20762]
**What happened**:
Not sure if this is an issue but I was confused at first if you send a query in Loki Explore like this
![image](https://user-images.githubusercontent.com/1053421/69831991-e2556e80-11f9-11ea-8fb2-72b1369ab9dd.png)

`sum(rate({job="loki-dev/querier"}[5m])) by (level)` The json result contains :
```json
{
	"status": "success",
	"data": {
		"resultType": "matrix",
		"result": [{
			"metric": {},
			"values": [
			..
			]
		}, {
			"metric": {
				"level": "debug"
			},
			"values": [
				..
			]
		}, {
			"metric": {
				"level": "error"
			},
			"values": [
		..
			]
		}, {
			"metric": {
				"level": "info"
			},
			"values": [
				..
			]
		}]
	}
}
```

As you can see one of the stream returned is `{}` which contains the result for when log lines did not have a `level` label, can also be considered as `{level=""}`.

**What you expected to happen**:

I think we should show  `{}` instead of the actual LogQL query, not sure why this means actually.

Might also apply to prometheus datasource.

**Environment**:
- Grafana version: Grafana v6.6.0-pre (c53ed5bbac)
- Data source type & version: Loki 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

/cc @aocenas WDYT ?

**Comment by aocenas** [comment]
@kaydelaney can you check this one. Seems like we do not expect to have zero labels in `by` expression result.

**Comment by kaydelaney** [comment]
@aocenas will look into this now

**Comment by kaydelaney** [comment]
Seems like the logic is here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts#L287
