### ISSUE TITLE
Loki: Completion items type dependant on store state 

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#20769]
We check the mode in the store to decide what kind of completion type we are going to provide https://github.com/grafana/grafana/blob/e0a2d4beacc379def0878655b3a3f7cceffbf3fc/public/app/plugins/datasource/loki/language_provider.ts#L116.

Not sure what this does when we are not in explore and also only checks the left side of the split so probably broken for right side split. Also in general creates dependancy between datasource and redux store which should not be there.

**Comment by aocenas** [comment]
@kaydelaney Can we just merge the two? We won't know what context we are in in dashboards anyway so I think providing all the completion makes most sense at the moment.

**Comment by kaydelaney** [comment]
The original thinking was that when in logs mode we don't want autocompletion for functions, etc. but you're right about it being broken for the right side split and the datasource/redux store dependency it introduces, so yeah it should be fine to just use the metrics autocomplete, especially considering I'll be working on unifying logs/metrics mode, at least for Loki, in the near future.
