### ISSUE TITLE
Unable to select time range on graph (latest build)

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#2076]
In the latest build I'm unable to select time range by mouse clicking on the graph - it marks the area but doesn't refresh the page. I think it was working properly in the build from 21.05 which is no longer available on the download page. Can you confirm this?

**Comment by torkelo** [comment]
yea, this was fixed two days ago, pushing out new build now.

**Comment by RowZay** [comment]
Also having the same problem from the latest build.
