### ISSUE TITLE
Date format switches days and months

### ISSUE THREAD

**Issue by RefusesNames** [grafana/grafana#20773]
**What happened**:
I tried to visualize dates and uses "DD/MM/YYYY h:mm:ss" as unit, but it uses "MM/DD/YYYY h:mm:ss" as format.
![grafana_date_unit_switched](https://user-images.githubusercontent.com/823148/69868743-f86f3780-12aa-11ea-9dcc-04c4eeb74d22.png)

**What you expected to happen**:
Selected and used format should match (I don't care which of these formats I use, but it should be consistent).

**Anything else we need to know:**
The other date format (I think it's ISO 8601) works fine.

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Prometheus (should not really matter)
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins: None

**Comment by torkelo** [comment]
that format is only for showing date values in panels like singlestat. 

Currently you cannot change the date format in graphs (will come soon)
