### ISSUE TITLE
Feature request: memcache as a session store

### ISSUE THREAD

**Issue by zerthimon** [grafana/grafana#2077]
I have grafana installed on the same server as graphite, which uses memcache for it's backend. It would be nice if I could use that memcache instance for storing grafana sessions as well.

**Comment by tmonk42** [comment]
+1

**Comment by damm** [comment]
or memory store? doesn't have to be memcache does it?

**Comment by zerthimon** [comment]
@damm when using a memory store you're risking losing your sessions if you restart the grafana daemon.

**Comment by damm** [comment]
@zerthimon ahh I don't typically deploy Grafana2 in a situation where I care about the sessions; lucky me.

**Comment by torkelo** [comment]
Solved by https://github.com/grafana/grafana/pull/3458
