### ISSUE TITLE
Error: Cannot read property 'trustAsHtml' of undefined  plugin: Boom table 

### ISSUE THREAD

**Issue by csempe91** [grafana/grafana#20771]
![image](https://user-images.githubusercontent.com/58329370/69863764-d8854700-129d-11ea-9f6a-36c2186cb812.png)
![image](https://user-images.githubusercontent.com/58329370/69863786-e89d2680-129d-11ea-9310-af55839f6627.png)

Hello, 

I am trying to use the plugin yesoreyeram-boomtable-panel to build a table with multiple columns from a Graphite source. 
And I ran unto this problem when trying to build it: Cannot read property 'trustAsHtml' of undefined (pic 1).. When inspecting the error (pic 2), there is a comment that that section of the code would only work with IE9. Has anyone ran into this error before? Or knows how to fix it?

Thank you!!!

**Comment by torkelo** [comment]
you will have to reach out to the plugin authors of this plugin

**Comment by marefr** [comment]
Maybe fixed by #20696 included in 6.5.1?

**Comment by torkelo** [comment]
yes, think so
