### ISSUE TITLE
Can't Add Plugins for Alerting, No Generic TSDB Alerting System

### ISSUE THREAD

**Issue by OptrixAU** [grafana/grafana#20787]
**What happened**: I'm allowed to create my own Data Source plugins, but there is no mechanism for making Alert plugins, and no generic handler to generate alerts from a 'standard' TSDB. This is an odd omission, and has been for several years.

**What you expected to happen**: I expected to either a) Be able to create an alert plugin, or b) for there to be an existing 'generic' framework that simply regularly calls the underlying TSDB with a regular query to see if the alert condition is still active.

**How to reproduce it (as minimally and precisely as possible)**: Add the Simple JSON Data Source. There is no way to create an alert based on any trends.

**Anything else we need to know?**: Yes, this is covered partly by #6841 - but since progress on adding alert support has been very slow, a generic framework to use in the mean-time sounds like a very good idea. 

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Any
- OS Grafana is installed on: Windows
- User OS & Browser: Windows / Chrome
- Grafana plugins: ARDI (Custom)
- Others: -

**Comment by torkelo** [comment]
they can if they are written as a backend plugin: https://grafana.com/docs/plugins/developing/backend-plugins-guide/#backend-plugins
