### ISSUE TITLE
How Grafana calculates average?

### ISSUE THREAD

**Issue by escaldon** [grafana/grafana#20784]
Hi,

I'm facing some issues trying to calculate average in Grafana. The thing is that the average differs depending on the interval's zoom. So, when I set the interval to 1m, that value is different to the one that I get when I set to 15m. I've selected a one hour time range. Trying to understand this behavior I've zoomed in to 1m interval, and then to 2m. Below there is screen shot of both panels: 

2m interval
<img width="504" alt="image" src="https://user-images.githubusercontent.com/19529791/69911996-c0d7cb00-1423-11ea-9843-50a5301321af.png">

1m interval
<img width="541" alt="image" src="https://user-images.githubusercontent.com/19529791/69912029-52473d00-1424-11ea-970c-239a7336057a.png">

Do you know how the range between 00:26 - 00:27 is being calculated to get the 7226 when I zoom out to 2m?

Many thanks!

**Comment by torkelo** [comment]
it depends on your database and query, Grafana does not calculate the average (unless it's a graph legend value or a singlestat type panel given many values)

**Comment by escaldon** [comment]
Thanks, Torkelo, I understand that point.  However, graphs also calculates same value, 7226, when I zoom to 2m. But, when I zoom in to 1m, it's correct, 5022.

2m interval
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/19529791/69912736-c6d2a980-142d-11ea-9c3e-a93a52ca42a2.png">

1m
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/19529791/69912756-f2ee2a80-142d-11ea-8ea5-cce25ece1e49.png">

Any idea? Thanks!

**Comment by torkelo** [comment]
Make sure your query uses average aggregation

**Comment by torkelo** [comment]
The graph has only one datapoint, so the average of that is the same as the value
