### ISSUE TITLE
Overlapping Charts

### ISSUE THREAD

**Issue by OptrixAU** [grafana/grafana#20788]
**What would you like to be added**:

I would like the ability (perhaps using a 'Mixer' plugin) to overlay one panel over another (or alternatively, to create a single panel that contains two charts with _different_ visualisations. 

**Why is this needed**:

There is a very specific use-case in heavy industry applications where you have an array of sensor data over time (resulting in a heat-map), plus one or two mobile devices that move across that array. To correctly show this, I need to draw a heatmap with a line diagram on top.

**Comment by torkelo** [comment]
We already have a heatmap panel. We might add ways to overlay time series data ontop later, but until then I would suggest developing a custom plugin

**Comment by OptrixAU** [comment]
This function would also help with the inability to show information from more than one source on a single panel - in some cases, I might want to show lines from two different information sources relative to one-another, and overlaying two cards would be a simplistic solution (although care would have to be taken to ensure that they both share the same ranges / scales).

**Comment by torkelo** [comment]
You can query different data source in the same panel (use -- Mixed --) data souce
