### ISSUE TITLE
Area charts with negative values

### ISSUE THREAD

**Issue by domoritz** [grafana/grafana#20785]
**What happened**:

<img width="1106" alt="Screen Shot 2019-12-01 at 11 24 45" src="https://user-images.githubusercontent.com/589034/69919005-43b15380-142d-11ea-87e7-3cea37293303.png">

The area does not extend to the bottom of the chart. 

**What you expected to happen**:

I expected the area to extend to the bottom of the chart. (Yes, I know it would be better to use a line chart but I still think this could be a bug).

**How to reproduce it (as minimally and precisely as possible)**:

Create an area chart with negative values.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.5.1 (1763a0f)

**Comment by torkelo** [comment]
not sure this makes sense, area charts are always terminated at y 0.  (you can have a negative area if the value is negative the fill will stretch below 0 

Will have to be a done a in a custom plugin I think.
