### ISSUE TITLE
Grafana showing weird encoding in measurment selection dropdown

### ISSUE THREAD

**Issue by thorian93** [grafana/grafana#20791]
**What happened**:
Apparently after an upgrade from version `6.4.3` to `6.4.4` Grafana shows weird encodings in the measurement drop down in the query editor.

![grafana-encoding](https://user-images.githubusercontent.com/12239876/69939144-6ac85d80-14df-11ea-9e1b-73bfadcdbdb5.png)

**What you expected to happen**:
Proper encoding after an upgrade obviously.

**How to reproduce it (as minimally and precisely as possible)**:
As I suspect this could be due to a upgrade and I am on a production system I can not reproduce the problem currently.

**Anything else we need to know?**:
I am not entirely sure from where the issue arises but currently the only change I see is the version upgrade some days ago.

**Environment**:
- Grafana version: 6.4.4 (commit: 092e514, branch: HEAD)
- Data source type & version: InfluxDB 1.7.9
- OS Grafana is installed on: Debian 10.2
- User OS & Browser: Windows 10, Firefox 70.0.1 (64bit)
- Grafana plugins: PieChart, Statusmap, Status Panel

**Comment by papagian** [comment]
Thank you for reporting this @thorian93 
Could you please supply the output from the network tab in Chrome developer tools so as to be able to tell whether the problem originates from the backend or it is a frontend issue.

**Comment by thorian93** [comment]
Hi @papagian (I like that name. 😄) and thanks for the quick response! I am using Firefox and though I know how to open the diagnostics here using `F12` I am not sure what information you need exactly.

**Comment by papagian** [comment]
@thorian93 
In Tools -> Web developer -> Network tab there should be a request to:
`https://play.grafana.org/api/datasources/proxy/<datasource id>/query?db=site&q=SHOW%20MEASUREMENTS%20LIMIT%20100&epoch=ms`
Could you please provide the response?

**Comment by thorian93** [comment]
Alright, now I got it:

```
HTTP/1.1 400 Bad Request
Content-Length: 100
Content-Type: application/json
Date: Mon, 02 Dec 2019 10:17:58 GMT
Request-Id: 032d2e8c-14ed-11ea-92ef-005056bf6f15
X-Frame-Options: deny
X-Influxdb-Build: OSS
X-Influxdb-Error: error parsing query: found 0&ï¿½ï¿½, expected identifier at line 1, char 36
X-Influxdb-Version: 1.7.9
X-Request-Id: 032d2e8c-14ed-11ea-92ef-005056bf6f15
```

**Comment by torkelo** [comment]
That is not it, need the response from the request with the options

**Comment by thorian93** [comment]
Okay, I found something but there is customer data in it. Does the following shortened snippet help? As far as I understand, this is the response part for the request before formatted in json.

`{"results":[{"statement_id":0,"series":[{"name":"measurements","columns":["name"],"values":[["\u0001\u0000\ufffd\ufffd\u0000\u0000\ufffd\ufffd\u0006\ufffd\ufffd\u0000\u0000foo.bar.com"],["\u0002\u0000\ufffd\ufffd\u0000\u0000\u0000\u0011\ufffd\ufffd\u0000\u0000tname=hostname.test.local"],["\u0003\u0000\ufffd\ufffd\u0000\u0000\u0000\u0003\u0000\ufffd\ufffd\u0000\u0000t"],["\u0003\r\ufffd\ufffd\u0000\u0000P\ufffd\u0001\ufffd\ufffd\u0000\u0000t"],["\u0003\ufffd\ufffd\u0000\u0000test.foobar"], [...] ,"mode":"application/json"}}}`

**Comment by torkelo** [comment]
Looks like a proxy or something is causing it, maybe you have written data like this to InfluxDB?

**Comment by thorian93** [comment]
Hi @torkelo: That is unlikely, as we did not change anything towards the InfluxDB input. Also in existing Dashboards and Dashlets the drop down looks just fine, only new ones show above behaviour.

**Comment by torkelo** [comment]
ok, strange, wonder what could cause influxdb to return strange characters then

**Comment by thorian93** [comment]
If anyone stumbles upon this: The guys over at [InfluxDB](https://github.com/influxdata/influxdb/issues/16135) heped sort it out.

**Comment by marefr** [comment]
@thorian93 so do you know what they did to resolve it?

**Comment by thorian93** [comment]
@marefr: That's why I linked to the issue in my comment. Simply put: They showed me the correct command to clean my InfluxDB from the scrambled measurements. Check out the issue over there for on point information.
