### ISSUE TITLE
mixed query not showing up from grafana 6.5

### ISSUE THREAD

**Issue by Gauravshah** [grafana/grafana#20793]
**What happened**:
Earlier versions of grafana show `--Mixed Queries` on the `Query` Tab
It no longer shows.

**What you expected to happen**:
Expected to see `Mixed` in `Query` tab list like earlier

**How to reproduce it (as minimally and precisely as possible)**:
create a new dashboard with grafana 6.3 & 6.5, and drop down list will no longer show it

**Anything else we need to know?**:
This is not a big deal for `Mixed` queries but there are other grafana plugins that are of type mixed and no longer show up on the list.
https://github.com/GoshPosh/grafana-meta-queries/issues/84

**Environment**:
- Grafana version: 6.5.1
- Data source type & version:
`Mixed` & `Grafana-meta-queries`
- OS Grafana is installed on:
Ubuntu
- User OS & Browser:
Brave/Chrome/Safari
- Grafana plugins:
https://github.com/GoshPosh/grafana-meta-queries

Please find attached screen shot
earlier grafana:
<img width="1559" alt="Screenshot 2019-12-02 at 12 58 01 AM" src="https://user-images.githubusercontent.com/620559/69945855-4b114500-149f-11ea-8c8f-484ea81257bf.png">
grafana 6.5.1
<img width="1637" alt="Screenshot 2019-12-02 at 1 01 49 AM" src="https://user-images.githubusercontent.com/620559/69945891-5bc1bb00-149f-11ea-8783-704ca82628ad.png">

**Comment by torkelo** [comment]
you add a mixed query, you have already selected -- Mixed -- data source :)

**Comment by Gauravshah** [comment]
@torkelo yes it makes sense for `--Mixed--` not to appear, but `grafana-meta-queries` falls under the same `mixed` bucket. We do want it to show down in drop down to do arithmetic query

**Comment by torkelo** [comment]
if you select it from the first data source dropdown?

**Comment by Gauravshah** [comment]
for arithmentic queries we need to do following:
set data source to `meta queries` and then add a query of type `meta queries`
Screenshots:
<img width="1568" alt="Screenshot 2019-12-02 at 3 38 41 AM" src="https://user-images.githubusercontent.com/620559/69956634-5a02f200-14b5-11ea-9b51-7cc22c9362f0.png">
<img width="1566" alt="Screenshot 2019-12-02 at 3 38 48 AM" src="https://user-images.githubusercontent.com/620559/69956636-5c654c00-14b5-11ea-899f-72708cd1eacf.png">

**Comment by torkelo** [comment]
@ryantxu I guess we cannot filter the add mixed query dropdown like this.
