### ISSUE TITLE
Templated Var Question

### ISSUE THREAD

**Issue by wstiern** [grafana/grafana#2079]
Hi there,

I love Grafana!

Is it possible to call a Grafana dashboard URL that implements a templated variable such that it displays the data for the variable specified in the URL? e.g. http://grafana.domain.com/dashboard/db/server-health?server=server_01 or something similar?

**Comment by oswell** [comment]
I can't recall with the 1.x versions, but with 2.x you can add a query parameter in the form of var-{variable}={value}.

From your example, it would be:
http://grafana.domain.com/dashboard/db/server-health?var-server=server_01

**Comment by damm** [comment]
@oswell that is also true with 1.x

**Comment by wstiern** [comment]
Brilliant. This app never ceases to amaze me. Thanks for your help @oswell !
