### ISSUE TITLE
Explore: Graph tooltip does not always highlight closest line

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#20803]
As seen during a recent postmortem:

> mouseovers on graphs don’t always highlight the closest line -- not sure how selection is determined. Seems to happen on line graphs with shaded areas underneath.

CC @cyriltovena @gouthamve @slim-bean

**Comment by davkal** [comment]
Any idea @dprokop ?

**Comment by torkelo** [comment]
> Seems to happen on line graphs with shaded areas underneath.

shaded areas? The explore graph has no shaded areas?

**Comment by dprokop** [comment]
@davkal is this line graph in Explore? Or the histogram?

**Comment by davkal** [comment]
I'll ask the loki team today.
