### ISSUE TITLE
Templating: Variable value groups/Tags

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2080]
This feature allows you to combine two related variables into one, letting the "parent" become something like tags/filter for another variable. 

![new_multi_select](https://cloud.githubusercontent.com/assets/10999/7896112/b1cf7a0e-06ae-11e5-9f2b-9e2cb8bc5a15.gif)

Templating settings
![image](https://cloud.githubusercontent.com/assets/10999/7896114/c6a7d426-06ae-11e5-9edb-c537c48d8b36.png)

When enabled this feature will allow you to specify an tags query and a tags value query for a template variable.

**Comment by kpweiler** [comment]
Looks pretty cool. Is this in one of the public branches? I can give it a spin if it is.

**Comment by torkelo** [comment]
its in master now

**Comment by bigunyak** [comment]
I was just about to post a feature request for something like that. :)
Great stuff! :+1:

**Comment by pavleec** [comment]
Might be very usefull. Thanks! :+1:

**Comment by timgriffiths** [comment]
This looks awesome! I pulled down the latest nightly build but i having trouble working out how to use the feature with influxdb 0.9.*  could you provide some guidance?

**Comment by timgriffiths** [comment]
Never mind i worked it out for others knowledge, and works as i expect based on description above

Value Query will look like 
SHOW TAG VALUES FROM mymeasurment WITH KEY = mykey

Then the group "Tag query"
SHOW TAG VALUES FROM mymeasurment WITH KEY = mykey2

And the important bit (not documented on the influxdb website) you can use Where with a show tag query, so the "Tag values query" is
SHOW TAG VALUES FROM mymeasurment WITH KEY = mykey WHERE mykey2 = '$tag'

love this new feature keep them coming @torkelo

**Comment by benh57** [comment]
This is pretty cool though i'm using graphite, and i don't necessarily have the information i need to query tags + values with in the graphite database. 

If i could just assign arbitrary sets of variables arbitrary tags in the GUI that'd be great for my use case, without having to create fake 'metrics' in the graphite database.

**Comment by benh57** [comment]
Ah, just realized i could select a different datasource for the template variable.. will try that. Still, might be nice to be able to assign in the grafana GUI, since it's really a presentation layer thing.

**Comment by bigunyak** [comment]
Finally got to try this feature and it's not quite what I expected... I rather thought about what @benh57 was saying, just pick up a few different values, say that this is now a group and give it a name.
Here is a very simple use case.
I have some system metrics collected from different hosts with the following name template:
`$project.$environment.$datacenter.$host`
Where `$host` accumulates underneath all different hosts: 4 database servers, 4 fronend servers, 6 backend servers. Now, I want to group them, and see "Load average" for backend servers only for example, or "Memory free" graph for database servers only and so on. Don't understand how do I do this with the current implementation...

**Comment by jimpriest** [comment]
Would love to see more examples of how to use this with Graphite, etc.

**Comment by Keleir** [comment]
How can I guery tags from datasource of Open-Falcon ?

**Comment by Gauravshah** [comment]
is there a way we can use it on "Custom" too ?
I am looking to provide drop down list of values e.g "Order, Listing Likes, Comments" but set two variables `$verb = { 'book','like','post'}` & `$direct_object = { 'order','listing', 'comment' }`

**Comment by aayushkum** [comment]
@torkelo - Unable to create variables for value groups/tags and maps servers in Grafana v6.3.4
