### ISSUE TITLE
Code style (lint) improvements

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#20816]
Some of this will apply to the entire project, while some is isolated to the GitHub-labelled areas.

**What would you like to be added**:
1. [`require-await`](https://eslint.org/docs/rules/require-await) and [`no-return-await`](https://eslint.org/docs/rules/no-return-await) ESLint rules. This will need #16053.
2. Replace synchronous [`fs`](https://nodejs.org/api/fs.html) use with asynchronous.
3. Use `console.error()` for errors and `console.warn()` for warnings.

**Why is this needed**:
1. To avoid instances of `async () => await fn()`, which should be simplified to `() => fn()`.
2. Better (and consistent) code quality and the possibility of concurrency.
3. The right tool for the job, and coloured logging.

**Comment by torkelo** [comment]
here is the main tslint file: https://github.com/grafana/grafana/blob/master/tslint.json
