### ISSUE TITLE
Docs feedback: installation/rpm.md

### ISSUE THREAD

**Issue by rangerdth** [grafana/grafana#20818]
The yum repos (baseurls listed on: https://grafana.com/docs/installation/rpm/) appear to be nonexistent.

When trying to pull from: https://packages.grafana.com/oss/rpm

Error:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: grafana-repo/oss/rpm</Details>
</Error>

**Comment by torkelo** [comment]
yea, we have no landing html pages there. The repo still works. 

we have another issue for this
