### ISSUE TITLE
TeamPicker: Increase size limit from 10 to 100 

### ISSUE THREAD

**Issue by whaike** [grafana/grafana#20824]
![image](https://user-images.githubusercontent.com/17683739/70021868-17343d80-15cd-11ea-9314-6ff9365f6a1b.png)

When I "Add Permission For" My Darshbord,I can not choose my team . The UI only returned 10 teams.

I have 16 Teams .

Grafana v6.2.1
 Same to Grafana v6.5.1

**Comment by torkelo** [comment]
you have to search to find more. We should increase the search limit

**Comment by torkelo** [comment]
Update to perpage=100
https://github.com/grafana/grafana/blob/master/public/app/core/components/Select/TeamPicker.tsx#L45

**Comment by whaike** [comment]
> Update to perpage=100
> https://github.com/grafana/grafana/blob/master/public/app/core/components/Select/TeamPicker.tsx#L45

Thanks , I found this but no time to build again, I use proxy  Intercepted and changed request to fix my problem.
waiting for update

**Comment by whaike** [comment]
> Update to perpage=100
> https://github.com/grafana/grafana/blob/master/public/app/core/components/Select/TeamPicker.tsx#L45

The same as "/api/org/users/lookup?query=&limit=10" at public/app/core/components/Select$ vim UserPicker.tsx
