### ISSUE TITLE
Feature Request: Basic Comma Separation Unit type in Single-Stat Panel

### ISSUE THREAD

**Issue by wstiern** [grafana/grafana#2082]
Hi there!

There are some really clever unit types available for single stat panels, but I've not been able to find anything that will do a basic comma-separating-three-digits type thing. Also handy would be dollars or currency. I'm able to work around this by plopping a $ in the big prefix, but it would format much cleaner with something native. Sorry if this is a redundant issue, feel free to drop a knowledge bomb on my head.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/1910
