### ISSUE TITLE
Template check in alert tab is incorrect

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#20821]
**What happened**:

in a panel, i have two query A and B.
A is a template query, and B is a normal query
when i add an alert with two condition, one is about query A, and another one is about query B
it's should warning alert do not support template variables, but not

**What you expected to happen**:

warning warning alert do not support template variables

**How to reproduce it (as minimally and precisely as possible)**:

add a panel with query A, B. A is template query and B is normal query.
add alert for panel with condition 1 about query A, and condition 2 about query B.
warning will appear when have only condition 1, after add condtion 2, warning disappeared

**Anything else we need to know?**:

it's seem like in `public/app/features/alerting/AlertTabCtrl.ts` loop condition check logic is incorrect

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
I don't think this is actually an issue.
You still get the warning if you try to use in the condition the template query.

**Comment by okhowang** [comment]
> I don't think this is actually an issue.
> You still get the warning if you try to use in the condition the template query.

warning will disapear when second condition‘s query is not template query,
but first condition's query is still template query now.

**Comment by papagian** [comment]
Maybe I don't get something but if I change the condition from `query(B,, 5m, now)` to `query(A, 5m, now)` where A is the templated query I get this warning

![Screenshot 2019-12-03 at 11 08 12](https://user-images.githubusercontent.com/1632407/70037983-3082bd00-15c0-11ea-887f-8e578beb1bc7.png)

**Comment by okhowang** [comment]
but when add a more condition with query B which is not template query, warning will disapear
![image](https://user-images.githubusercontent.com/3352585/70038934-0814b600-15f4-11ea-8c72-d15ff37d7d34.png)
and delete second condition with query B, warning will appear
![image](https://user-images.githubusercontent.com/3352585/70039009-211d6700-15f4-11ea-9b92-31fa4875d5f8.png)

**Comment by papagian** [comment]
Ok, I see the problem now, thanks

**Comment by crackersophia** [comment]
> Maybe I don't get something but if I change the condition from `query(B, 5m, now)` to `query(A, 5m, now)` where A is the templated query I get this warning
> 
> ![Screenshot 2019-12-03 at 11 08 12](https://user-images.githubusercontent.com/1632407/70037983-3082bd00-15c0-11ea-887f-8e578beb1bc7.png)

It looks like the backend service only checks whether **the last query** is a template variable query, there may some logic error in loop condition.
