### ISSUE TITLE
Text panel with HTML contents from template variable stopped working

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#20823]
**What happened**:
Grafana's 6.5.1 Visualization text (HTML mode) doesn't support full HTML stored in the template variable, see:
Contents of `docs` variable is an HTML documentation data, all I put in the HTML text is `[[docs]]` to refer to the template variable:
![Screenshot 2019-12-03 at 04 53 13](https://user-images.githubusercontent.com/2469783/70019257-f77b2600-1588-11ea-9c50-149f00729356.png)
When I copy-paste this manually into the HTML text without using a variable I'll get the correct visualization, see:
![Screenshot 2019-12-03 at 04 55 58](https://user-images.githubusercontent.com/2469783/70019338-36a97700-1589-11ea-87be-04c13369925e.png)

**What you expected to happen**:
The same works OK in the previous version of Grafana, 6.4.4 for example:
![Screenshot 2019-12-03 at 04 56 51](https://user-images.githubusercontent.com/2469783/70019377-5b055380-1589-11ea-949a-69ba63118af7.png)

It was always OK until now, I'll just use the previous version of Grafana for now.

**How to reproduce it (as minimally and precisely as possible)**:
Create a template variable storing HTML, then create a dashboard having text panel that users `[[variable_name]]` as HTML content.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1 is broken, 6.4.4 and older work OK.
- Data source type & version: postgres
- OS Grafana is installed on: ubuntu 18.04 lts
- User OS & Browser: macOS + safari
- Grafana plugins: not related to plugin, uses built-in plugin. A lot of plugins installed.
- Others:

**Comment by torkelo** [comment]
use ${variable:raw} syntax to disable default html escaping of template variable value

**Comment by lukaszgryglicki** [comment]
Ohhh OK will try, is it something new in 5.X ?

**Comment by lukaszgryglicki** [comment]
@torkelo anyway, updated Grafana to 6.5.1 everywhere, thanks for the fix.

**Comment by torkelo** [comment]
no, default html escaping is of template variables in text panel is new in 6.5

**Comment by lukaszgryglicki** [comment]
OK, thanks.

**Comment by lukaszgryglicki** [comment]
Still not idea, even when using `${var:raw}` we can see that only part of the HTML is showing correctly now (it ignores `<head>` part and shows it as a text, so I can't apply CSS styles for example).
This is 6.4.4 using `[[var]]` (other instance):
![Screenshot 2019-12-04 at 14 26 24](https://user-images.githubusercontent.com/2469783/70146557-b8d98e80-16a2-11ea-8b43-d410571748d6.png)
This is 6.5.1 using `${var:raw}` which works for simple HTML cases but not for this complex table:
![Screenshot 2019-12-04 at 14 26 32](https://user-images.githubusercontent.com/2469783/70146596-d0b11280-16a2-11ea-9378-8eaba48700f9.png)
This is EXACTLY the same variable using `${var:raw}` in 6.4.4 (specially downgraded Grafana in K8s cluster to show it):
![Screenshot 2019-12-04 at 14 33 44](https://user-images.githubusercontent.com/2469783/70146773-2dacc880-16a3-11ea-8216-73c673af6d1f.png)

cc @torkelo

**Comment by torkelo** [comment]
have you disabled html sanitization:
https://grafana.com/docs/installation/configuration/#disable-sanitize-html

**Comment by lukaszgryglicki** [comment]
No, It wasn't needed before, is it in `grafana.ini`:
```
[panels]
disable_sanitize_html=1
```

**Comment by lukaszgryglicki** [comment]
I'll try that tomorrow

**Comment by torkelo** [comment]
It was required before , but template interpretation happens after sanitizing, which was fixed in 6.5 (so that interpolation happens before)

**Comment by lukaszgryglicki** [comment]
Setting `disable_sanitize_html = true` under `[panels]` in `grafana.ini` does the trick. Thanks!
