### ISSUE TITLE
Backend: Most (all) objects/entities should have unique identifiers (uid)

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20830]
**What would you like to be added**:
Most objects (database tables) should have unique identifiers (uid).

**Why is this needed**:
`Uid` was added to folders and dashboards in Grafana 5 to solve having unchangeable permalinks to folders and dashboards. After this `uid` have also been added for alert notification channels. In hindsight `uid` has shown to be a handy thing for Grafana objects to have since it makes it a lot easier to integrate with Grafana given you have different Grafana organization/instances/environment.

In addition, some of Grafana's configuration is based on hard-coded integers and titles, for example `orgId` and `orgName`, and would be good to be able to use `uid` instead.

Currently, the following objects lacks `uid` and should probably have it:
- Organization (database table org)
- DataSource (database table data_source)
- Playlist (database table playlist)

**Comment by hairyhenderson** [comment]
Closing as stale - some of this will have already been done, and the @grafana/app-platform-wg folks are likely to handle this anyway...
