### ISSUE TITLE
"CloudWatch templating error" false positive message

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#20839]
**What happened**:
Keep getting the ERROR message popup
```
CloudWatch templating error
Multi template variables are not supported for expression
```
when diplaying panels where variable with multi-value enabled exist AND the graph panel has "Repeating" enabled.
The message keeps poping but everything works as expected.

**What you expected to happen**:
The message not to appear as altough multi template variables are being used, with "Repeating" enabled in the graph visualization it will render one graph per multi-variable value.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a new variable (e.g. `$multi_val`) with `Multi-value` enabled and use it in a CloudWatch expression (e.g. `SEARCH('$multi_val {AWS/ApplicationELB,LoadBalancer} MetricName="RequestCount"','Sum',300)`). In the panel's "General" settings set `Repeating -> Repeat = multi_val`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser: Windows, Chrome 78
- Grafana plugins: -
- Others: -

**Comment by sunker** [comment]
Thanks for reporting this @salavessa. 

You're right, that error message should not be displayed for expressions. I'll remove it.
