### ISSUE TITLE
How can I integrated the grafana into kibana4.0.1 ?

### ISSUE THREAD

**Issue by lwd426** [grafana/grafana#2084]
Because I want to use them together.Does Grafana can be integrated into kibana?

**Comment by torkelo** [comment]
You can integrate grafana into any web application using iframe panel feature. http://docs.grafana.org/guides/whats-new-in-v2/#panel-iframe-embedding  Not sure what integrations kibana has though.

**Comment by lwd426** [comment]
Thanks.I 'll have a try. @torkelo
