### ISSUE TITLE
Reduce visible columns when in zoom mode

### ISSUE THREAD

**Issue by schnobbl** [grafana/grafana#20844]
Hi,

we have a central overview dashboard with a lots of status panels (~ 30) on it. Each panel has a text label giving information about the affected system. 

When the users browser is in 100% zoom mode (default) all the texts are readable without problems. Some users working in 150% zoom mode are having problems with texts getting cut off:

https://i.paste.pics/378104875b4f62be112a29beb1526f69.png

Is there a way to reduce the amount of columns when zoomlevel increases? Only when zoom level comes to 300 % the layout switches to onecolumn (mobile). 

Thanks for your help!
Regards,
Norbert

**Steps to reproduce**:

- Create a dashboard with a lots of status panels with text label on it (https://grafana.com/grafana/plugins/vonage-status-panel)
- Increase zoom level up to 150%

**Actual Result**:
Some texts getting cut off

**Expected Result**
Nearly all texts are readable

**Relevant WCAG Criteria:** [1.4.4 WCAG Criterion](link to https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html

**Environment**:
- Grafana version: 5.2.1
- Data source type & version:
- User OS & Browser: windows / firefox
- Others:

**Comment by papagian** [comment]
I'm unable to reproduce it the cutting off with the current Grafana version. The version you are using is very old and a lot of front end modifications have happened since then.

**Comment by schnobbl** [comment]
Hi, we also tested this issue on Grafana Version 6.3.4, with following result:

https://i.paste.pics/8ca441cac7788cd0590b6d145efe4734.png

The problem still exists: Texts are getting cut off.
@papagian could you please reopen this issue? thanks!

**Comment by papagian** [comment]
@schnobbl 
Could you share an example dashboard json?

**Comment by papagian** [comment]
@schnobbl 
ignore my last comment, I was able to reproduced it myself.

**Comment by schnobbl** [comment]
@papagian I forgot to mention that in the new screenshot from grafana 6.3.4 we replaced the external statuspanel plugin with the default "single stat" panel, which produces the same error.

**Comment by schnobbl** [comment]
@papagian could you please reopen this issues as the problem still exists, thx

**Comment by papagian** [comment]
@schnobbl 
In Grafana version 6.6 there will be a new stat panel that handles font sizing as well. You can see a demo [here](https://twitter.com/torkelo/status/1202327313960128513).
