### ISSUE TITLE
grafana-cli reports false positive when failing to re-install plugin while running

### ISSUE THREAD

**Issue by sakjur** [grafana/grafana#20841]
**What happened**:
When trying to upgrade the installed grafana-image-renderer plugin with `grafana-cli` and a custom pluginUrl (unsure if the latter part is relevant) while running Grafana with a previous version of the same plugin, the installation fails due to file being busy but reports successful installation.

**What you expected to happen**:
Either the plugin is successfully installed in the background and applied on next restart of Grafana or the installation is correctly marked as a failure.

**How to reproduce it (as minimally and precisely as possible)**:
On a fresh installation of Grafana 6.5.1 on Ubuntu 19.10 (installed via the repo as per the instructions on https://grafana.com/docs/installation/debian/ ),  I ran this in the command-line:

1. Install plugin
```
root@grafana-lb-test:~# systemctl start grafana-server
root@grafana-lb-test:~# grafana-cli --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip plugins install grafana-image-renderer
installing grafana-image-renderer @
from: https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip
into: /var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>
root@grafana-lb-test:~# systemctl restart grafana-server
```

2. Re-install plugin live (failure + false positive)
```
root@grafana-lb-test:~# grafana-cli --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip plugins install grafana-image-renderer
installing grafana-image-renderer @
from: https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip
into: /var/lib/grafana/plugins

Failed to extract file: Failed to open file: open /var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64: text file busy
✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>
```

The fourth line to the end indicates a failure, but the third line to the end claims successful installation. Stopping Grafana and then installing seems to fix the problem:

**Workaround**:

3. Re-install plugin while stopped (successful)
```
root@grafana-lb-test:~# systemctl stop grafana-server
root@grafana-lb-test:~# grafana-cli --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip plugins install grafana-image-renderer
installing grafana-image-renderer @
from: https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc.zip
into: /var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>
```

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 19.10
- User OS & Browser: N/A
- Grafana plugins: grafana-image-renderer
- Others: N/A

**Comment by peteeckel** [comment]
For the record: It does **not** only happen with a custom URL, I could involuntarily reproduce it while testing remedies for #19842.

**Comment by peteeckel** [comment]
`grafana-cli plugins ls` also incorrectly shows the version that I tried to install but whose installation failed without notice:

```
[root@master1 grafana]# grafana-cli plugins ls 
installed plugins:
grafana-image-renderer @ 1.0.7 

Restart grafana after installing plugins . <service grafana-server restart>
```
