### ISSUE TITLE
Alert not working

### ISSUE THREAD

**Issue by abhargav7** [grafana/grafana#20848]
I am seeing this error while trying to configure high CPU usage alert, for example when Cpu usage is more than 90%. After creating the alert when I TEST I get below error.
error:"tsdb.HandleRequest() error client_error: client error: 401"

**Comment by papagian** [comment]
401 error generally implies that there was an authentication error when the client tries to connect to the datasource.
Have you used this datasource in a query (not alert) and you were able to get back any metrics?
Unfortunately, we cannot investigate it more unless you provided us with the required information:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
Can you also check your browser's developer tools in the network tab and send us the specific response?

**Comment by abhargav7** [comment]
![image](https://user-images.githubusercontent.com/25340668/70137283-9c921d80-16b3-11ea-993e-c67481eb0654.png)
1. Have you used this datasource in a query (not alert) and you were able to get back any metrics?
yes, see the image
2.  Grafana v6.3.2 (4832460)
3. Data Sources Type: Prometheus
![image](https://user-images.githubusercontent.com/25340668/70137478-fdb9f100-16b3-11ea-8bf3-c154a7d320d2.png)
4. Browser: Chrome
5. Alert list, Prometheus, plugin list, Azuremonitor. bar guage, cloud watch, dasboard list, Elastic search, guage, Graph, Graphite, heat map,


```
{
  "firing": true,
  "state": "",
  "conditionEvals": " = true",
  "timeMs": "0.815ms",
  "error": "tsdb.HandleRequest() error client_error: client error: 401",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1575457890173,
        "queries": [
          {
            "refId": "A",
            "model": {
              "expr": "(1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"ourIP:9796\"}[5m])) by (instance))) * 100",
              "hide": false,
              "refId": "A"
            },
            "datasource": {
              "id": 1,
              "name": "RANCHER_MONITORING"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1575457900173
      }
    }
  ]
}

```

developer tools:-
`store updating angular $location.url /d/icjpCppik/cluster?orgId=1
filters.ts:9 store updating angular $location.url /dashboard/new?orgId=1
filters.ts:9 store updating angular $location.url /?orgId=1
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?orgId=1
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?tab=visualization&orgId=1&fullscreen&edit&panelId=2
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?tab=queries&orgId=1&fullscreen&edit&panelId=2
PanelQueryState.ts:269 No queries, so return early
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?tab=advanced&orgId=1&fullscreen&edit&panelId=2
StateHistory.tsx:22 panel.render()
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?tab=alert&orgId=1&fullscreen&edit&panelId=2
logs.ts:16 Trying to execute query while last one has yet to complete, returning same promise
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?orgId=1&from=1575444216398&to=1575444218032
filters.ts:9 store updating angular $location.url /?orgId=1
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?orgId=1
filters.ts:9 store updating angular $location.url /d/dwNcZvaWk/new-dashboard-copy?tab=alert&orgId=1&fullscreen&edit&panelId=2`

``
![image](https://user-images.githubusercontent.com/25340668/70138068-6a81bb00-16b5-11ea-864d-4f0a18a9d405.png)

**Comment by papagian** [comment]
@abhargav7 
what is the response of the test (/api/alerts/request) request?
also which Prometheus version are you using?
thank you

**Comment by abhargav7** [comment]
@papagian 
1. I donot see normally any Network call for /api/alerts/request, but when I manually do
https://demo.com:8443/k8s/clusters/c-c4fp4/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/api/alerts/request in chorome I get this 
{"message":"Alert not found"}
But can I definitely see my alert in alert list Tab
/k8s/clusters/c-c4fp4/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/alerting/list
2. prometheus:v2.11.1

**Comment by papagian** [comment]
@abhargav7 
My fault: I meant `/api/alerts/test`, sorry

**Comment by abhargav7** [comment]
{"firing":true,"state":"","conditionEvals":" = true","timeMs":"0.799ms","error":"tsdb.HandleRequest() error client_error: client error: 401","logs":[{"message":"Condition[0]: Query","data":{"from":1575466742027,"queries":[{"refId":"A","model":{"expr":"(1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"myip:9796\"}[5m])) by (instance))) * 100","hide":false,"refId":"A"},"datasource":{"id":1,"name":"RANCHER_MONITORING"},"maxDataPoints":0,"intervalMs":0}],"to":1575466752027}}]}

**Comment by abhargav7** [comment]
If it is actually 401 Authentication issue, I wouldn't have seen data points on graphs.
Is this a known issue with this version? Shall we try switching versions?

**Comment by papagian** [comment]
If you could try it with a newer version it would be great.

**Comment by abhargav7** [comment]
I did went to upgrade the Prometheus and Grafana to rancher/grafana-grafana:6.3.6
still same error while evaluating rule `error:"tsdb.HandleRequest() error client_error: client error: 401"`
any insight would be very helpful, @papagian Thanks!

**Comment by abhargav7** [comment]
I also think why the error shows **tsdb** in error:"tsdb.HandleRequest(), while my data sources is only Data Sources / RANCHER_MONITORING Type: Prometheus

![image](https://user-images.githubusercontent.com/25340668/70306320-94a9b900-182c-11ea-9e3e-8a0db675d662.png)

**Comment by papagian** [comment]
`tsdb` is the a grafana package that contains the implementations of the several data sources .

However, `rancher/grafana-grafana` is not a non-official docker image. Unfortunately,  we cannot investigate it further unless you use the official grafana images.

**Comment by OriHoch** [comment]
@abhargav7 I'm getting the same error, also with Rancher, did you manage to fix it?

**Comment by OriHoch** [comment]
fixed it by adding a new datasource to Prometheus which uses the following URL: http://access-prometheus.cattle-prometheus

this points to a different service which exposes prometheus on port 80.. not sure why this works

**Comment by CharlieMiRD** [comment]
> fixed it by adding a new datasource to Prometheus which uses the following URL: http://access-prometheus.cattle-prometheus
> 
> this points to a different service which exposes prometheus on port 80.. not sure why this works

Thank you! Same problem for me with Rancher. This solved it for me.
