### ISSUE TITLE
Columns of a table from queries with an aggregation operator.

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#20847]
**What would you like to be added**:
Would it be possible to generate columns of a table from a PromQL query with an aggregation operator (e.g. `sum by (<label list>)(<vector expression>)`) from the `(<label list>)`?

**Why is this needed**:
1. There should not be a need to hide unwanted columns / labels here then.
2. I expect I'll be able 'to join' more smoothly results from more queries into one table.

And finally, speaking of joining more queries into one table - is it possible to order this table on a column? (I mean all results from all queries)

NB I'm aware of a possibility to use recording rules...

**Comment by papagian** [comment]
You can already do that:
![Screenshot 2019-12-04 at 12 26 29](https://user-images.githubusercontent.com/1632407/70134963-c4708980-1691-11ea-9d53-ff5c0403c367.png)

Also you can sort the table by a specific column by clicking on the column's title.
Also, in the future please use the community [site](https://community.grafana.com/) for questions.

**Comment by hawran** [comment]
No, I cannot.
When I set up a `Format: Table , Instant: Y` for a query there are two problems here:
1. I need to 'hide' all other columns / labels outside the 'grouping sets'.
2. When I have more queries - each of them with the same 'calculated' value - these values are not 'joined' into one column but each query generates results to its own column:
![Screenshot_2019-12-04_15-45-12 grafana grouped-columns](https://user-images.githubusercontent.com/25924718/70152728-06a7c400-16ae-11ea-850f-0705fead576e.png)
