### ISSUE TITLE
losing admin login when helm upgrade

### ISSUE THREAD

**Issue by wuestkamp** [grafana/grafana#20852]
Whenever I try to upgrade to another grafana version using

```
helm3 repo update

helm3 upgrade --install grafana stable/grafana -n grafana --set persistence.enabled=true --set persistence.size=1Gi --set persistence.storageClassName=retain --set resources.requests.cpu=100m --set resources.requests.memory=100Mi --set resources.limits.cpu=200m --set resources.limits.memory=300Mi
```

All works fine, but I cannot login even with the new admin password provided via the secret. I have to completely helm-remove and helm3-install grafana again, which results in me loosing all settings which is annoying to setup again.

Is there a proper way for upgrading without losing the admin login?

Thanks,
Kim

**Comment by papagian** [comment]
You need to open this issue in the [helm](https://github.com/helm/charts/tree/master/stable/grafana) repository.

**Comment by wuestkamp** [comment]
There is already an issue regarding this: https://github.com/helm/charts/issues/7891

This solution worked for me after helm upgrade

```
kubectl -n grafana get secret grafana -o jsonpath='{.data.admin-password}' \
| base64 --decode \
| xargs -I {} kubectl -n grafana exec -it grafana-6f9bd94d5d-k225s -- grafana-cli --homepath /usr/share/grafana admin reset-admin-password {}
```

Where grafana-6f9bd94d5d-k225s is a pod of the grafana deployment
