### ISSUE TITLE
Testdata values range

### ISSUE THREAD

**Issue by ianmoone** [grafana/grafana#20859]
**What would you like to be added**:
When using TestData datasource, it would be really useful to be able to specify a range with min and max values to set limits in the values which are generated.
**Why is this needed**:
This would add some kind of real world touch when you want to assert the usability of your dashboards with the different teams involved.

**Comment by torkelo** [comment]
yea, good idea. Been wanting this myself

**Comment by FireEmerald** [comment]
At least for the **Random Walk** Scenario, min and max values can now be set.
![2020-07-22 10_20_42-Window](https://user-images.githubusercontent.com/1107939/88152975-1bb57100-cc05-11ea-867a-fea00e6f430a.png)

It would be cool to have these options also for other Scenarios, like **Predictable Pulse** or **Predictable CSV Wave**.
