### ISSUE TITLE
Feature Request - Dashboard PNG export

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#2085]
It would be nice to have additional option in "Share Dashboard" window to export all of the selected dashboard graphs into PNG (or PDF) format.

**Comment by SnDsound** [comment]
I agree, will be nice feature

**Comment by torkelo** [comment]
selected? what do you mean selected, there is no such state, you mean in the share dialog you want to a list of all panels, check the ones you want and then have multiple png images ready for download? Can you explain the feature request a bit more?

**Comment by pavleec** [comment]
I meant to export all of the graphs avaialble on active dashbord, but selectable objects option might be additional advantage to that :)

**Comment by torkelo** [comment]
you mean something like this:
http://play.grafana.org/render/dashboard/db/grafana-play-home?width=1800

**Comment by pavleec** [comment]
Exactly

**Comment by 3fr61n** [comment]
Hi

When doing 'http://play.grafana.org/render/dashboard/db/grafana-play-home?width=1800' into a dashboard with multiples rows/charts, etc sometimes the png doesn't contains all the charts, (it seems it doesn't have enough time to load the data).

Is it any workaround or knob in order to wait until all data is loaded in order to generate the png? 

Regards
Efrain

**Comment by IzakMarais** [comment]
We want to generate printable "reports" based on live report dashboards: take all the panels in a dashboard and spread them out over a multi-page *.pdf or *.rtf document. 

Is anyone else interested in this?

I am writing a small web-service that does this using:
* Grafana panel png exporting
* LaTeX
* Grafana external links (with time range), 
The result is a "generate report" link on a dashboard that serves a pdf. 

@torkelo, Is this something that might be useful to integrate into Grafana (in stead of using an external service)? Would you be interested in a PR for it?

**Comment by bergquist** [comment]
I don't think this issue is totally closed.

**Comment by Ruben-E** [comment]
@IzakMarais: You already implemented this? If so, is it open source? I'm dealing with the same requirements for my current project too.

Thanks!

**Comment by utkarshcmu** [comment]
+1
I have a similar requirement in #3895

**Comment by adrianlzt** [comment]
@IzakMarais we are looking for the same functionality

**Comment by Foxeronie** [comment]
+1 most requested from our users

**Comment by stolp** [comment]
+1
I was looking for this functionality today as well.

**Comment by cjbhaines** [comment]
+1 I would find this really useful! Do you have intentions to look at this?

**Comment by dowc** [comment]
+1

**Comment by p4fg** [comment]
+1

**Comment by abadyan-vonage** [comment]
+1
@IzakMarais Have you implemented this functionality? We need this as well.

**Comment by IzakMarais** [comment]
I have a working implementation. I will talk to management about open sourcing it.

**Comment by stekoch** [comment]
+1 for PDF reports! Would be great to have that feature

**Comment by abadyan-vonage** [comment]
If anyone is interested, we ended up using a workaround with phantomJs which just captures the screen into png. We used the render.js from the grafana repo (under vendor/phantomjs):
`phantomjs-2.1.1-macosx/bin/phantomjs render.js 'url=<our server url>' png=<path>.png width=1800 height=1600`

Only customization we did was to add authentication into the render.js file:
`page.customHeaders = {
  "Authorization": "Bearer XXXXXXXXXXX"
};`

**Comment by IzakMarais** [comment]
I got the go-ahead to open source the reporter service. You can access it [here](https://github.com/IzakMarais/reporter).

**Comment by abadyan-vonage** [comment]
@IzakMarais awesome, thanks for that.
Can you please add some more detailed instructions as to what to put inside the link settings?
I figured most of it from the gif but it's kind of hard to read and after defining http://<ip address>:8686/api/report/<dashboard name> I get a report but only the date is displayed, all else is empty.

**Comment by IzakMarais** [comment]
Pleasure. I updated the readme with usage instructions for the link settings. 

Any other requests/questions should probably go on the issues page for the reporter.

**Comment by klaffke** [comment]
+1

**Comment by IldarMinaev** [comment]
See my pull request: https://github.com/grafana/grafana/pull/6028
It is support pdf output for render function of grafana. And support full dashboard export.
So you can get PDF by url like this: /render/pdf/dashboard/db/dashboard_name?theme=light&timeout=120&width=1600

**Comment by thechile** [comment]
Hi, i can't see any mention of #2085 in the CHANGELOG ? Can anyone confirm that is feature is going to make it into 4.1 or 4.2 ? Thank you.

**Comment by torkelo** [comment]
that was merged into 4.1 release

**Comment by thechile** [comment]
ok thank you , tested in 4.1.1 and works. I was looking in UI "Share Dashboard =>Link" popup for a "Direct link rendered image" option that you get on panel share.

**Comment by mvadu** [comment]
@amuraru @torkelo Could you please guide me on how to get an entire row with repeated panels (via template variable) in a single PNG? If I follow [docs for sharing](http://docs.grafana.org/reference/sharing/) it asks me to click on panel header, which in my use case will give only one panel in the row to export. I am looking for what @torkelo did in his [example](https://github.com/grafana/grafana/issues/2085#issuecomment-107410489) above.

**Comment by SlodeSoft** [comment]
+1

**Comment by akant74** [comment]
+1 !!

**Comment by manuelbcd** [comment]
+1

**Comment by k-tooriyama** [comment]
+1

**Comment by pavankumarkatakam** [comment]
+1

**Comment by zhuzhigao** [comment]
+1 !

**Comment by GerasDraugas** [comment]
+1

**Comment by MatGit5** [comment]
+1

**Comment by mywkaa** [comment]
+1

**Comment by akalongman** [comment]
+1

**Comment by devdil** [comment]
I use this
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({ width: 1920, height: 8000 });
  await page.goto('http://10.41.25.43:3000/d/UZmojXBiz/cluster-light-house?orgId=1&var-cluster_name=esx-pf1-c1.eng.nutanix.com&var-version=5.11', {"waitUntil" : "networkidle0", timeout: 0});
  await page.screenshot({path: 'example.png',  fullPage: true});
  await browser.close();
})();

**Comment by 3h4x** [comment]
I use 
https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl/reviews?hl=en-US

works like a charm

**Comment by devdil** [comment]
@3h4x is there a way to automate this process?
