### ISSUE TITLE
Elasticsearch: Allow aggregations using scripted fields without selecting a field

### ISSUE THREAD

**Issue by johnskopis** [grafana/grafana#20866]
**What happened**:
Aggregations on scripted fields do not work.

**What you expected to happen**:
Aggregations using scripted fields should work.

**How to reproduce it (as minimally and precisely as possible)**:

Index this:
```
{"index":{"_index":"test","_type":"doc"}}                                        
{"array": ["apples", "oranges"] }                                                
{"index":{"_index":"test","_type":"doc"}}                                        
{"array": ["carrots", "peas", "apples"] }       
```

Try running an aggregation for the script `return doc['array'].length;`

The agg query generated by Grafana sets `field` in the request ,e.g.:
```
    "aggs": {
        "2": {
            "date_histogram": {
              ...
            },
            "aggs": {
                "5": {
                    "stats": {
                        "field": "select field",
                        "script": {
                          "inline": "return doc['array'].length;"
                        }
                    }
                }
            }
        }
    }
```
vs (this works)

```
    "aggs": {
        "2": {
            "date_histogram": {
              ...
            },
            "aggs": {
                "5": {
                    "stats": {
                        "script": {
                          "inline": "return doc['array'].length;"
                        }
                    }
                }
            }
        }
    }
```

Grafana should omit the `field` parameter entirely if the field is not present in the mapping.

One way to do this might be to allow any value to be input in the field selector and remove the `field` parameter when the provided field is not present in the field mappings.

**Anything else we need to know?**:
**Environment**:
- Grafana version: v6.3.4
- Data source type & version: Elasticsearch (tried 5,6,7 versions same issue)
- OS Grafana is installed on: Linux
- User OS & Browser: any
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Field selection is currently required that's why I label this as a feature request even though you may see this as a bug. There's an easy workaround for this and that is to select a field.

**Comment by johnskopis** [comment]
I had originally selected a feature but changed to a bug.

With our elastic search version at least when the field is sent in the
request there are no results for the agg from the server. Omitting `field`
in the request produces the correct result.

It's possible that when a numeric field is selected the are results
returned. My index has only text fields though so I can't verify that.

When you selected a field using the field selector did you select a text or
numeric field?

**Comment by marefr** [comment]
@johnskopis numeric field

**Comment by johnskopis** [comment]
As a workaround (my index doesn't have any numeric fields) I am able to use `@timestamp`. It feels strange though as the aggregation has nothing to do with `@timestamp`.

It would be much more natural to have an option to omit the `field` param in the request, i.e. when using a purely scripted field, as described above.

Thanks!

**Comment by davkal** [comment]
We could add a `none` field to make this clearer.

**Comment by aocenas** [comment]
Could be already fixed after the query editor refactor needs to be checked.

**Comment by Elfo404** [comment]
after the react migration there's no hardcoded `"select field"` value for that field

<img width="968" alt="Screenshot 2021-03-29 at 11 34 49" src="https://user-images.githubusercontent.com/1170767/112824705-c7f80300-9082-11eb-942e-4883cdc497c7.png">

```json
{"2":{"avg":{"script":"return doc[\"@value\"].length"}}}
```

so this should work. The only remaining issue is with the `SegmentAsync` component that doesn't allow to clear its value (AFAIK), so the only way to achieve this is to create a new metric aggregation without selecting the field. Once a field is selected is not currently possible to unselect it.

Keeping this open to investigate on how to work around this `SegmentAsync` component limitation
