### ISSUE TITLE
Point out that 'group_search_base_dns' is necessary for group search feature!

### ISSUE THREAD

**Issue by bb-Ricardo** [grafana/grafana#20862]
**What happened**:
I tried to configure nested ldap groups in AD according to this:
https://github.com/grafana/grafana/blob/master/docs/sources/auth/ldap.md#nestedrecursive-group-membership

**What you expected to happen**:
I expected the nested groups to return as configured in our AD.

**How to reproduce it (as minimally and precisely as possible)**:
Configure as descripted in the docs with a Microsift AD.

**How to fix it**
The problem was that `group_search_base_dns` was **NOT** set and then the query is **not executed**

Two suggestions:
  * Update the documentation accordingly and point out that `group_search_base_dns` is necessary! https://github.com/grafana/grafana/blob/b20a258b72d3130747118c6f3c535fc5d1b3a15f/pkg/services/ldap/ldap.go#L481
  * add a fallback that if `GroupSearchBaseDNs` is *nil* but `GroupSearchFilter` is set then use `SearchBaseDNs`

Also this Config seems to work out of the "box" (without adding own OUs)
```
group_search_filter = "(member:1.2.840.113556.1.4.1941:=%s)"
group_search_base_dns = ["DC=mycorp,DC=mytld"]
group_search_filter_user_attribute = "dn"
```
**Anything else we need to know?**:
I love Grafana!

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS 7.7
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by oddlittlebird** [comment]
Please update the documentation in the PR that updates the code and addresses this issue.

**Comment by bb-Ricardo** [comment]
Hi, just wondering. Are you referring to me or someone else. I could do a PR if you like.

**Comment by oddlittlebird** [comment]
Yes, please do.
