### ISSUE TITLE
Processing symbol \n

### ISSUE THREAD

**Issue by the5dot45x39** [grafana/grafana#20865]
Hello!

Grafana does not display multiline output in an interface. We pass the symbol  '\n' in the string, it processes and hides the symbol, but displays the text in one line.

- Grafana 6.5.1 in Docker
- User browser Google Chrome for Windows

**Comment by alexmayerlab** [comment]
It may never have worked, but this is definitely the wrong behavior.

I would also like control characters to be processed normally!

**Comment by helsq** [comment]
I have same problem

**Comment by lestadd1988** [comment]
Fix please

**Comment by bokinet** [comment]
have same problem

**Comment by torkelo** [comment]
Please include where in the interface you want this

**Comment by the5dot45x39** [comment]
Ideal - universal support

I encountered a problem in "Explorer", the "Logs" field

**Comment by olivierboudet** [comment]
> Please include where in the interface you want this

IMO, we need it at least in "Explorer" view (with Loki datasource), and in logs panel.
