### ISSUE TITLE
Alert Image Coming as blank- Even when accessed the Direct Link Rendered Image

### ISSUE THREAD

**Issue by ajiteshk** [grafana/grafana#20860]
My Alert email contains images which is black and has no graphs. I read one of the earlier issues "https://github.com/grafana/grafana/issues/18378" and followed the same process. 
When i clicked on Direct Link Rendered Image then also it comes as blank  black Image and in the logs it says -Dec 04 03:01:20 lushrzc122.gl.avaya.com grafana-server[19400]: t=2019-12-04T03:01:20-0700 lvl=info msg=Rendering logger=rendering path="d-solo/4cT8UOaWz/cpu_alert?orgId=1&from=1575443682463&to=1575450882

I expect a proper Image to come with graphs

Create an alert rule for High CPU usage and sent it to email

**Environment**:
- Grafana version:6.5.1
- Data source type & version::prometheus-2.14.0
- OS Grafana is installed on:RHEL 7.x
- User OS & Browser: Windows and Chrome
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/19226494/70133417-0f979600-16ac-11ea-8c39-670846dba5f2.png)

**Comment by papagian** [comment]
Which renderer do you use?
If you haven't already done this, can you try installing the [Image Render Plugin](https://grafana.com/grafana/plugins/grafana-image-renderer) and try again?

**Comment by ajiteshk** [comment]
Thanks, But now i am getting the below error after installing the plugin

Dec 05 03:54:46 lushrzc122.gl.avaya.com grafana-server[3763]: t=2019-12-05T03:54:46-0700 lvl=info msg="New state change" logger=alert
Dec 05 03:54:46 lushrzc122.gl.avaya.com grafana-server[3763]: t=2019-12-05T03:54:46-0700 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="rpc error: code =  Unavailable desc = all SubConns are in TransientFailure, latest connectionerror: connection error: desc = \"transport: error while dialing: dial tcp 127.0.0.1:50059: connect: connection refused\""

**Comment by papagian** [comment]
@ajiteshk 
could you please restart grafana server and send the logs after the restart?

**Comment by ajiteshk** [comment]
@papagian 

Please find the logs after restart 

Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: Stopping Grafana instance...
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped UsageStatsService" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped PluginManager" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped Stream Manager"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped NotificationService" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped CleanUpService" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped InternalMetricsService" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped UserAuthTokenService" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped RemoteCache" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped provisioningServiceImpl" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[22790]: t=2019-12-05T09:41:01-0700 lvl=info msg="Stopped AlertEngine" logger=server reason="context canceled"
Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: grafana-server.service: main process exited, code=exited, status=1/FAILURE
Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: Stopped Grafana instance.
Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: Unit grafana-server.service entered failed state.
Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: grafana-server.service failed.
Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: Starting Grafana instance...
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Starting Grafana" logger=server version=6.5.1 commit=1763a0f branch=HEAD compiled=2019-11-28T00:43:49-0700
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="App mode production" logger=settings
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=23003
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing SqlStore" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Starting DB migration" logger=migrator
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing HTTPServer" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing OSSLicensingService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing SearchService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing RemoteCache" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing QuotaService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing ServerLockService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing UserAuthTokenService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing PluginManager" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Starting plugin search" logger=plugins
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Registering plugin" logger=plugins name="Grafana Image Renderer"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing RenderingService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing AlertEngine" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing DatasourceCacheService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing HooksService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing LoginService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing InternalMetricsService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing TracingService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing UsageStatsService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing CleanUpService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing NotificationService" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing provisioningServiceImpl" logger=server
Dec 05 09:41:01 lushrzc122.gl.avaya.com systemd[1]: Started Grafana instance.
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Initializing Stream Manager"
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Renderer plugin found, starting" logger=rendering cmd=plugin_start_linux_amd64
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
Dec 05 09:41:01 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:41:01-0700 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ignoreHTTPSErrors=false timestamp=0001-01-01T00:00:00.000Z




Dec 05 09:43:53 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:43:53-0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=ok prev state=unknown
Dec 05 09:43:57 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:43:57-0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=pending prev state=ok
Dec 05 09:44:07 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:44:07-0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=alerting prev state=pending
Dec 05 09:44:07 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:44:07-0700 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: error while dialing: dial tcp 127.0.0.1:50059: connect: connection refused\""
Dec 05 09:44:07 lushrzc122.gl.avaya.com grafana-server[23003]: t=2019-12-05T09:44:07-0700 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[ajiteshk@####.com hsaifee@###.com]"

**Comment by marefr** [comment]
Maybe related to https://github.com/grpc/grpc-go/issues/2636

When Grafana is running what's the output of 
```bash
lsof -i :50059
```

**Comment by ajiteshk** [comment]
@marefr its coming as blank

[root@lushrzc122 ~]# lsof -i :50059
[root@lushrzc122 ~]#

**Comment by marefr** [comment]
@ajiteshk any difference if you try the different command in this article? https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Security_Guide/s1-server-ports.html

**Comment by ajiteshk** [comment]
@marefr I tried and below is my output -

[root@lushrzc122 ~]# nmap -sT -O localhost

Starting Nmap 6.40 ( http://nmap.org ) at 2019-12-09 03:30 MST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00012s latency).
Other addresses for localhost (not scanned): 127.0.0.1
Not shown: 991 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
25/tcp   open  smtp
111/tcp  open  rpcbind
631/tcp  open  ipp
3000/tcp open  ppp
5901/tcp open  vnc-1
6001/tcp open  X11:1
9090/tcp open  zeus-admin
9100/tcp open  jetdirect
Device type: general purpose
Running: Linux 3.X
OS CPE: cpe:/o:linux:linux_kernel:3
OS details: Linux 3.7 - 3.9
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at http://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 6.69 




For Lsof command i did grep and it returned nothing

**Comment by marefr** [comment]
@ajiteshk thanks. 
- `Not shown: 991 closed ports` looks interesting - Can you look if you find 50059 in those? 
- Do you have ipv6 disabled, see https://github.com/grafana/grafana-image-renderer/issues/48? 
- Do you have any firewall rule blocking you to use port 50059?
- Have you installed the plugin using some other user account than you're using to run Grafana?

**Comment by jinleileiking** [comment]
I think this should added to the README with faq. Many cloud instance does not have ipv6

**Comment by marefr** [comment]
The IPv6 limiation/problem have been resolved since Image Renderer v2.0.0 so closing this.
