### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#20879]
**What happened**:
Got data type
**What you expected to happen**:
Get Field keys
**How to reproduce it (as minimally and precisely as possible)**:
create a Variable, Type=Query, as query set "SHOW FIELD KEYS", you will get the keys, put a space between FIELD and KEYS and you will get Data types.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: InfluxDB 1.7.9
- OS Grafana is installed on: Debian
- User OS & Browser: WIN 10, Chrome

**Comment by torkelo** [comment]
That query is processed by the influxdb backend, so maybe a bug in InfluxDB
