### ISSUE TITLE
Can't redirect to the grafana from oAuth application

### ISSUE THREAD

**Issue by mohamednizar** [grafana/grafana#20870]
**What happened**:
When I'm trying to authenticate users using my custom oAuth application it's looping over a basic auth popup.

**What you expected to happen**:
Need to redirect to Grafana after successful authentication.

**How to reproduce it (as minimally and precisely as possible)**:
Configured a `generic_oauth` and tried to authenticate using it.  used [laravel/passport](https://github.com/laravel/passport/issues) as oAuth

**Anything else we need to know?**:

Found the location url in the header `http://localhost:3002/oauth/authorize?access_type=online&client_id=2&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Ausername%20email&state=A6yXAUoq3N5s3hEgtViuNqnpPF7dEYd0ZDU0bHiuk8A%3D`

and my grafana.ini
```
[auth.generic_oauth]
name = SIS
enabled = true
allow_sign_up = true
response_type = code
scopes = user:username email
grant_type = state
client_id = '2'
client_secret = MkH5mvEvVwHpTjfATRKtjucDM25LaiSiYaNW44N7
client_passsword = MkH5mvEvVwHpTjfATRKtjucDM25LaiSiYaNW44N7
#email_attribute_name = email:primary
#email_attribute_path =
auth_url =  http://localhost:3002/oauth/authorize
token_url = http://localhost:3002/oauth/token
api_url = http://localhost:3002/api/user
team_ids =
#allowed_organizations = 1
tls_skip_verify_insecure = false
#tls_client_cert =
#tls_client_key =
#tls_client_ca =
send_client_credentials_via_post = false
```

**Environment**:
- Grafana version: v6.5.1 
- Data source type & version:Mysql 5.7
- OS Grafana is installed on: docker
- User OS & Browser: Linux , Chrome

**Comment by papagian** [comment]
@mohamednizar 
Could you please share your server's log?

**Comment by mohamednizar** [comment]
The following log only related to the oAuth.
`grafana-dashbord_1  | t=2019-12-04T18:24:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/login/generic_oauth status=302 remote_addr=172.18.0.1 time_ms=0 size=269 referer="http://localhost:3000/login?redirect=%2F%3ForgId%3D1"`

I'm relay supersized on this behavior.

**Comment by papagian** [comment]
Can you [enable](https://grafana.com/docs/grafana/latest/installation/configuration/#level) `debug` logging and include all the logs? It would be useful for checking the sequence of the requests.

**Comment by marefr** [comment]
This feels more like a question to me and related to your OAuth provider configuration/setup. Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
