### ISSUE TITLE
Explore: Going to explore and back messes up queries

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20873]
Grafana v6.5.1 (1763a0f)
Chromium on Linux

see demo video. going from panel editor to explore mode messes up the UI. even going back to editor leaves the mess up in place
https://www.youtube.com/watch?v=VzGQEHRuEOg

**Comment by torkelo** [comment]
This is due to the template variable with hundreds of long guids. When going to Explore we interpolate that (Explore does not support template variables). So each query now has hundreds of long guids. 

Not sure how we can solve this other than adding template variable support to Explore.

**Comment by torkelo** [comment]
But there is a clear bug here, going back to explore and back dashboard (using browser back button) should not modify the queries in the dashboard. 

Very strange that the queries are modified when you go back. 

@kaydelaney any ideas why the queries are modified when you just navigate back using the brwoser back key? 

We interpolate template variables when we go to explore and then using browser back I would not expect that jump to explore and back to modify my dashboard unless I used the special explore menu action we have.

**Comment by kaydelaney** [comment]
@torkelo will look into this tomorrow morning

**Comment by Dieterbe** [comment]
> Not sure how we can solve this other than adding template variable support to Explore

Maybe we can fix the UI to accommodate large text? Grow the widgets so the overlap problem goes away ?
