### ISSUE TITLE
Docs feedback: /guides/basic_concepts.md

### ISSUE THREAD

**Issue by GideonWolfe** [grafana/grafana#20877]
> For more details on the user model for Grafana, please refer to Admin

`https://grafana.com/reference/admin` and  `https://grafana.com/reference/http_api#users` give `404`s.

**Comment by papagian** [comment]
thank you for reporting this

**Comment by oddlittlebird** [comment]
@robbymilo - There are multiple broken links on this page. I am unclear if it is a content issue or a build issue. Would you please take a look?

**Comment by robbymilo** [comment]
Content issue. These are links pointing to pages that don't exist.

**Comment by oddlittlebird** [comment]
Thanks, @robbymilo. I will take care of it.
