### ISSUE TITLE
spinner keeps spinning after graphite render query has already returned

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20876]
Grafana v6.5.1 (1763a0f)

title says it all, but here's a video to demonstrate:
https://youtu.be/tcTgcG7EoTE

I would also like to add that this seemingly innocuous UI detail actually has more UX impact than one might expect.
it happens often that we refresh dashboards and it's very hard to track which panels have refreshed and which are still loading. if you stare at a few panels (or inspect all the x-axis), you can usually spot which panels are reloaded, but if your dashboard has many panels, this becomes impractical very quickly. The other problem here is it makes people think the data source (metrictank in this case) is slow.

Furthermore, I note that I have reported many similar bugs in the past: #18828, #18169 , and others have as well for related issues #18773 , #11687 , it makes me wonder if this particular code is just very fragile. Which leads me to the suggestion I've made in the past to give it an overhaul as an extensible state machine :
#18829

**Comment by torkelo** [comment]
ah, great that you opened an issue for this! I have also seen this, it's a strange timing issue. Only happens in edit mode for me for some reason. 

Think same issue as reported here https://github.com/grafana/grafana/issues/20724 as well. 

Will investigate.

**Comment by torkelo** [comment]
> it makes me wonder if this particular code is just very fragile. Which leads me to the suggestion I've made in the past to give it an overhaul as an extensible state machine 

It's not the state machine that is fragile, it's mostly related to angular dirty checking that is very fragile (which is one of many reasons why we are migrating away from angular). This bug is only showing for old panels

**Comment by torkelo** [comment]
Dam can't replicate this at all now :( will try on my mac tomorrow could replicate it there
