### ISSUE TITLE
More than 1000 Teams under a single Org, breaks Team Searches

### ISSUE THREAD

**Issue by BenB196** [grafana/grafana#20880]
**What happened**:

Added more than 1000 teams to a single org. Went to search teams under than org, could only search the first 1000 teams returned.

**What you expected to happen**:

Search all teams under the org. I would expect team search to work like users does under admin, where paging and adaptive search for more than 1000 users.

**How to reproduce it (as minimally and precisely as possible)**:

Add more than 1000 teams to an org and search for something outside of the first 1000 teams.

**Anything else we need to know?**:

Using MySQL as backend DB.

**Environment**:
- Grafana version: v6.5.1
- Data source type & version: N/A
- OS Grafana is installed on: Docker + Alpine
- User OS & Browser: Windows + Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
strange, there is nothing in the SQL query / api that would limit search. if you search for a team name you cannot find it unless it's the top 1000? strange.

**Comment by devdil** [comment]
@torkelo can i pick this up?

**Comment by torkelo** [comment]
Yes ❤️

**Comment by devdil** [comment]
@torkelo awesome

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
