### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by freedomwarrior** [grafana/grafana#20887]
**What happened**: grafana rendering timed out
**What you expected to happen**: successful render image
**How to reproduce it (as minimally and precisely as possible)**: share some graph with direct link
**Anything else we need to know?**: got one successful render on 'Alert list'  after 20 seconds of wait
```t=2019-12-05T07:39:08+0000 lvl=info msg=Rendering logger=rendering path="d-solo/_siqrK-Zz/transport?orgId=1&from=1575509947118&to=1575531547119&panelId=6&width=1000&height=500&tz=Europe%2FKiev"
t=2019-12-05T07:40:10+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-12-05T07:40:10+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=4 orgId=1 uname=roma error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-12-05T07:40:10+0000 lvl=eror msg="Request Completed" logger=context userId=4 orgId=1 uname=roma method=GET path=/render/d-solo/_siqrK-Zz/transport status=500 remote_addr=195.78.38.190 time_ms=62023 size=1782 referer="https://grafana.gtu.net.ua/d/_siqrK-Zz/transport?orgId=1"
```

**Environment**:
- Grafana version: current version 6.6.0, also try 6.5.0 and 6.5.1 - same result
- Data source type & version: Prometheus 2.14.0-rc.0
- OS Grafana is installed on: Ubuntu 18.04.3 LTS
- User OS & Browser: Linux Mint 19.1 Tessa / Chrome / Firefox/
- Grafana plugins: - 
- Others: -

**Comment by papagian** [comment]
Which renderer do you use?
If you haven't already done this, can you try installing the [Image Render Plugin]( https://grafana.com/grafana/plugins/grafana-image-renderer) and try again?

**Comment by freedomwarrior** [comment]
> Which renderer do you use?
> If you haven't already done this, can you try installing the [Image Render Plugin](https://grafana.com/grafana/plugins/grafana-image-renderer) and try again?

this works good.
