### ISSUE TITLE
notifications channel with "Include Image" checked doesn't alert to slack

### ISSUE THREAD

**Issue by fp-dshim** [grafana/grafana#20883]
**What happened**:
notifications channel with "Include Image" checked doesn't alert to slack.  When it's unchecked, notifications to slack works again.

**What you expected to happen**:
Get grafana alerts to slack channels

**How to reproduce it (as minimally and precisely as possible)**:
From grafana 6.5.0 or 6.5.1, setup notification channel with "Include Image" checked.
Trigger an alert, and you don't get a notification in the slack channel.
When you uncheck "Include Image" and trigger the alert again, we get the notification in the slack channel.

**Anything else we need to know?**:
We are not using image to appear in the slack notification. (no slack bot, nor external image source)
Grafana is running from GKE.  Alerts used to work when running Grafana 6.0.0
Built grafana from source using Dockerfile.ubuntu for both grafana 6.0.0 and grafana 6.5.1
We need to do this so that we can add internal CA cert in the image.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Prometheus 2.9.2
- OS Grafana is installed on: GKE
- User OS & Browser: Mac OS X & Chrome

- Grafana plugins:
Cloudflare Grafana App
Bubble Chart
Clock
Pie Chart
Plotly
Statusmap
Worldmap Panel
Google BigQuery

**Comment by papagian** [comment]
@fp-dshim 
Could you please [enable](https://grafana.com/docs/grafana/latest/installation/configuration/#level) debug logging and send your server logs? Also, have you configured [external image destination](https://grafana.com/docs/grafana/latest/installation/configuration/#external-image-storage)? Can you share your configuration?
I suspect that there should be an error during trying to send the notification because according to the [docs](https://grafana.com/docs/grafana/latest/alerting/notifications/#slack):

> If you want to include screenshots of the firing alerts in the Slack messages you have to configure either the external image destination in Grafana, or a bot integration via Slack Apps.

**Comment by fp-dshim** [comment]
`external image destination` is not configured, and it was never configured for 6.0.0 either, even though the notification channels had "Include image" checked for 6.0.0 as well.

**Comment by un000** [comment]
The same, but disabling image sending doesn't help.

```
Dec 05 23:23:07 **** grafana-server[30776]: t=2019-12-05T18:23:07-0500 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook=alerts-channel
```

But sending test alert works.

**Comment by papagian** [comment]
You get a timeout while trying to upload the image; try to increase [`evaluation_timeout_seconds`](https://grafana.com/docs/grafana/latest/installation/configuration/#evaluation-timeout-seconds).

Also which renderer do you use? Does using [`grafana-image-renderer`](https://grafana.com/grafana/plugins/grafana-image-renderer) help?

**Comment by un000** [comment]
We use default renderer(empty config for it).
evaluation_timeout_seconds doens't help.

```
$ /usr/share/grafana/tools/phantomjs/phantomjs --ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url="http://127.0.0.1:2000/d-solo/oRSRDPfik/jaeger?orgId=1&panelId=2&render=1" width=1000 height=500 png=/var/lib/grafana/png/h7VoegawyYiO0fABRTGh.png domain=127.0.0.1 timeout=60 renderKey=GBBAkA6pntyrfw5a
Loading a web page: http://127.0.0.1:2000/d-solo/oRSRDPfik/jaeger?orgId=1&panelId=2&render=1 status: success 60000



ERROR: TypeError: undefined is not an object (evaluating 'container[0].getBoundingClientRect')
TRACE:
 -> undefined: 6
 -> : 7

  phantomjs://code/render.js:48 in onError
TypeError: null is not an object (evaluating 'bb.width')

  phantomjs://code/render.js:68 in checkIsReady
```

With debug logs look like that plugin-component not found:
```
2019-12-06T11:50:01 [DEBUG] WebPage - evaluateJavaScript result QVariant(bool, false)
2019-12-06T11:50:01 [DEBUG] WebPage - evaluateJavaScript "(function() { return (function () {\n          var panelCount = document.querySelectorAll('plugin-component').length;\n          return window.panelsRendered >= panelCount;\n        })(); })()"
```

**Comment by aknuds1** [comment]
@un000 I've also seen this error with the PhantomJS renderer. Could you try the [image rendering plugin](https://grafana.com/grafana/plugins/grafana-image-renderer) and see if that helps?

**Comment by un000** [comment]
Yep, it works! So if phantom is deprecated, we will use rendering plugin. Ty!

**Comment by aknuds1** [comment]
@un000 Great!

**Comment by thomasf** [comment]
I have disabled include images but it seems like grafana still tries to render an image and the webhook fails.

**Comment by un000** [comment]
Yep, disabling include image still causes screenshoting.

**Comment by apple77y** [comment]
I used previous version 5.x.
Rendering image feature had worked very well just before I upgrade the version to 6.x.
But I install the plugin that mentioned above, finally it works!

**Comment by wuestkamp** [comment]
I have the same issue with grafana-4.1.3, alerts were working but no notification sent. Had to disable the "include image" option under the notification settings.

**Comment by apple77y** [comment]
@wuestkamp 
Like I mentioned above, installing plugin may will help to resolve the situation.
