### ISSUE TITLE
Slack notification doesn't include image

### ISSUE THREAD

**Issue by xluffy** [grafana/grafana#20885]
**What happened**:
I follow Slack docs and try to use Slack apps for intergrating. So I created a Slack app for notification. I can send alert to slack channel, but this alert doesn't include image. 

> Instead, we suggest that you read about their replacement - Slack apps. Slack apps can be built just for your own workspace or distributed through the App Directory, and they can use the latest and greatest APIs and UI features. 
> https://api.slack.com/custom-integrations

If I try to use old incoming-webhook version of Slack https://slack.com/apps/A0F7XDUAZ-incoming-webhooks, everything is ok. I can send alert with image.

I setuped `external_image_storage.s3`, rendering image is ok, uploading image to s3 bucket is ok (checked in s3 bucket + open s3 url in browser) 

**What you expected to happen**:

- Want to use Slack apps for notification. I think Slack will remove old version in feature.

**How to reproduce it (as minimally and precisely as possible)**:
Slack:

- Create a slack apps
- Enable incoming-webhook
- Get bot token

Grafana:
- Setup `external_image_storage.s3`. Eg:
```
[external_image_storage]
provider = s3
[external_image_storage.s3]
bucket = grafana-bucket
region = us-west-2
path = dashboard
access_key = xxxxxxxxxxxxxx
secret_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
- Setup alerting in Grafana dashboard

![image](https://user-images.githubusercontent.com/1505720/70198731-3d2f1e80-1742-11ea-80aa-ef69082b5672.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version:
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: macosx + firefox
- Grafana plugins: just `grafana-image-renderer` replace phantomjs
- Others:

**Comment by papagian** [comment]
Does your access key has permissions to the S3 bucket for the `s3:PutObject` and `s3:PutObjectAcl` actions?

**Comment by xluffy** [comment]
@papagian: Sure, image is rendered and uploaded to S3 bucket. I can open it in browser.

**Comment by papagian** [comment]
@xluffy 
Can you enable [debug](https://grafana.com/docs/grafana/latest/installation/configuration/#level) logging and share you server's log?

**Comment by xluffy** [comment]
@papagian this is grafana log (note: I censored real bucket and hook url slack)

```
t=2019-12-06T01:22:37-0800 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=6
t=2019-12-06T01:22:40-0800 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="CPU: utilization alert" id=9
t=2019-12-06T01:22:40-0800 lvl=dbug msg="Sending query" logger=tsdb.prometheus start=2019-12-06T01:17:40-0800 end=2019-12-06T01:22:40-0800 step=1m0s query="100 - (avg by (instance_name) (irate(node_cpu_seconds_total{instance_name=~\"gfa-prod-app-.*\", mode=\"idle\"}[5m])) * 100)"
t=2019-12-06T01:22:40-0800 lvl=dbug msg="Render request received" logger=rendering url="http://127.0.0.1:3000/d-solo/kCAWLNvWz/app-mingle2?orgId=2&panelId=12&render=1" timestamp=0001-01-01T00:00:00.000Z
t=2019-12-06T01:22:41-0800 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=2 uname= dashId=1 action=View
t=2019-12-06T01:22:41-0800 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=2 uname= dashId=1 action=Edit
t=2019-12-06T01:22:41-0800 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=2 uname= dashId=1 action=Edit
t=2019-12-06T01:22:41-0800 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=2 uname= dashId=1 action=Admin
t=2019-12-06T01:22:42-0800 lvl=dbug msg="Uploading image to s3. url = https://s3.us-west-2.amazonaws.com/gfa-ops-grafana/dashboard/VQMSAF3uKPsAyM7KOJMZ.png"
t=2019-12-06T01:22:42-0800 lvl=info msg="uploaded screenshot of alert to external image store" logger=alerting.notifier url=https://s3.us-west-2.amazonaws.com/gfa-ops-grafana/dashboard/VQMSAF3uKPsAyM7KOJMZ.png
t=2019-12-06T01:22:42-0800 lvl=dbug msg="Sending notification" logger=alerting.notifier type=slack uid=OAT9CNvZz isDefault=false
t=2019-12-06T01:22:42-0800 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=9 notification=gfa-prod-infra-slack
t=2019-12-06T01:22:42-0800 lvl=dbug msg="Sending webhook" logger=notifications url=https://hooks.slack.com/services/ASDKDKSsd/XGSADASSDJ/xxxxxxxxxxxxxxxxxxxx http method=
t=2019-12-06T01:22:43-0800 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
t=2019-12-06T01:22:43-0800 lvl=dbug msg="Sending webhook" logger=notifications url=https://slack.com/api/files.upload http method=POST
t=2019-12-06T01:22:43-0800 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.960 alertId=9 name="CPU: utilization alert" firing=true attemptID=1
t=2019-12-06T01:22:47-0800 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=6
```

**Comment by marefr** [comment]
@xluffy As per https://grafana.com/docs/grafana/latest/alerting/notifications/#slack you shouldn't configure bot token if you want to use external image storage.

**Comment by xluffy** [comment]
Thank @marefr. I did not read docs carefully. For anybody has same issue, let check Grafana docs:

If use bot token (`xoxb-`), Grafana will upload the generated image **via Slack’s file.upload API** method (mean upload to Slack), not the external image destination.

**Comment by ZealousMacwan** [comment]
Using the "Local" option for external image storage, images are rendered and accessible publicly, (no bot configured, wants to send an image from local storage to slack ), still not getting the image on slack only text is there, no error on log

**Comment by erikpena** [comment]
For anyone reading this and that is trying to get the bot to upload to a private channel, be absolutely sure that you've added the bot to the private channel in order for it to have capabilities to actually upload an image.

**Comment by gpapin** [comment]
On top of wha't been said previously: Make sure that the `Recipient` is filled in with your channel name. Even though the webhook point to a channel already and you can't actually override the notification by filling the recipient for the notification. The image upload doesn't use the webook endpoint and needs a channel defined in order to know where to send the image. Why the logs didn't complain about not knowing where to send the image I don't know, but I was stuck on this for a while...

**Comment by SJrX** [comment]
I also found that when I didn't have an [explicit image provider set to local](https://grafana.com/docs/grafana/latest/administration/configuration/#provider) that the messages were showing up empty.
