### ISSUE TITLE
Cloudwatch schema change

### ISSUE THREAD

**Issue by petetanton** [grafana/grafana#20895]
**What happened**:
When upgrade to Grafana 6.5, the Cloudwatch plugin has a change of schema that is undocumented and does not automatically update. The `Period` field changes from a number to a string which prevents dashboards that have a set a period from just working with Grafana 6.5 without migration

**What you expected to happen**:
Either Grafana should work with both a number or a string or document it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome
- Grafana plugins: Cloudwatch
- Others:

**Comment by petetanton** [comment]
Can be reproduced with this target in the dashboard JSON:
`{
                        "alias": "{{metric}}-{{stat}}",
                        "dimensions": {
                            "AutoScalingGroupName": "StageMsdrAnnotator-ComponentAutoScalingGroup-14B4UTFUNS1OK"
                        },
                        "metricName": "NetworkIn",
                        "namespace": "AWS/EC2",
                        "period": 60,
                        "refId": "A",
                        "region": "eu-west-1",
                        "statistics": [
                            "Sum"
                        ]
                    }`

**Comment by sunker** [comment]
@petetanton which version were you upgrading from? In Grafana 6.4, period was also a string. See [here](https://github.com/grafana/grafana/blob/62b53c3eb7e4b93a4a23e2fdca2b28b28503fac5/public/app/plugins/datasource/cloudwatch/datasource.ts#L52)

**Comment by petetanton** [comment]
Hi @sunker, yes I upgraded from 6.4.
The fix is to edit every graph, clear the period field and then re-enter the value.
I think the dashboard in question has not been edited since we upgraded to 6.4 (it had a schemaVersion 19) so could be an older version of the schema however it was working fine with 6.4

**Comment by sunker** [comment]
I see. Think the period data type was changed a long time ago, so not really related to the 6.5 release. I'll close this issue. Thanks reporting this @petetanton!
