### ISSUE TITLE
Reset Alert notifications from 'Alerting' to 'OK' after email sent.

### ISSUE THREAD

**Issue by sh123-987** [grafana/grafana#20896]
So I have an alert config to evaluate every 5mins for 30mins, and if it reaches above a certain threshold then send an email notification. I get this email, but what I noticed is the state stays at 'Alerting' and I do not receive anymore emails unless I manually go into Grafana and pause/start that specific alert again to change state to 'OK'. It will only reset to 'OK' only if the threshold goes below when it does its next check.

Is it possible to automatically change state from 'Alerting' to 'OK' after email was sent to, so I can keep receiving email notifications if alert state is still bad.

**Comment by papagian** [comment]
You can [enable reminders](https://grafana.com/docs/grafana/latest/alerting/notifications/#send-reminders) to achieve this.
