### ISSUE TITLE
Multiple Cursors in Graph panel

### ISSUE THREAD

**Issue by maldag** [grafana/grafana#20902]
**What would you like to be added**:
I'm looking for the possibility to add multiple cursors in the same graph panel and the possibility to see the difference in time and metrics from both selected times.

**Why is this needed**:
This would significantly increase the useability for analysis of real time electrical data. For our systems we need to define rise and fall times for electrical system and thus we use Matlab or an oscilloscope.

**Comment by marefr** [comment]
Could you please provide a screenshot, if possible, of how you're thinking the end result would look like? @ryantxu feels like something you would be interested in.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by fasmide** [comment]
I too have found my self in need of what digital scopes usually refer to as Cursors - for doing basic time and amplitude measurements... I've attached a few screenshots from a Rigol scope 

![image](https://user-images.githubusercontent.com/1194937/74560290-8e3f6800-4f66-11ea-88f6-b0cf149e1bcf.png)

They typically allow the user to move both cursors at the same time which is really useful when looking for patterns

![image](https://user-images.githubusercontent.com/1194937/74560323-9e574780-4f66-11ea-957a-43dfaac4b75f.png)

**Comment by fasmide** [comment]
@marefr Sorry to bump - I tried to tag you with an Edit of my last message and is now uncertain if you received a notification :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
