### ISSUE TITLE
#345 (reopening)

### ISSUE THREAD

**Issue by davidbreitgand** [grafana/grafana#2090]
@torkelo

The original question here: https://github.com/grafana/grafana/issues/345

I really wanted to avoid asking this question, as apparently you have answered it already and the issue is closed. I apologize for "reopening". However, after spending a lot of time on this POST issue, I still cannot get Grafana to GET instead of POST.

My environment:
graphite0.9.12 (I cannot go up to a higher version at the moment)
grafana1.5.3 (installed from https://github.com/grafana/grafana following the instructions as-is)
I see the random walk series fine when adding a new dashboard->panel->graph

I added render_method: 'GET' to config.js per instructions above.
Then I followed these steps as you wrote above:

1) clone repository
2) download nodejs -- skipped this one as I have this already
3) npm install -g grunt-cli
4) grunt release
So, upon step 4 the tarball grafana-2.1.0-pre1.linux-ia32.tar.gz is created OK. However, the tar does not contain any build scripts. What am I supposed to do with the tarball? Can you please clarify. I am new to Grafana, so maybe this is not a very smart question.

Thank you for the great work. I absolutely love how Grafana dashboards look. I just want to get my graphite metrics visualized thru it already :) The only thing that stops me is that POST vs GET issue.

Really thanks in advance.

**Comment by torkelo** [comment]
See the installation guides and the building from source guide, 
http://docs.grafana.org/

There is also install screencasts. There is no config.js in Grafana 2.0 and no option to set render_method to GET

**Comment by torkelo** [comment]
Its really strange that your graphite install does not accept POST, you should open a graphite issue for that
