### ISSUE TITLE
Control whether users with "edit" permission can save a non-provisioned dashboard.

### ISSUE THREAD

**Issue by kemarsh** [grafana/grafana#20900]
**What would you like to be added**:  
The ability to allow a dashboard (that has not been created via provisioning) to be edited but not saved.

**Why is this needed**:
For our production metrics, most users should not be allowed to modify dashboards and alerts.  It is however quite common for them to want to tweak queries, alter graph settings and do a bunch of things to get exactly what they need out of the dashboard in that moment. 

Using dashboard provisioning we can have it so that a user can 'edit' a dashboard but cannot overwrite the deployed dashboard which is great.  Except that now we need to get our dashboards onto our Grafana server's persistent storage (we're running in Kube).  Grafana already has a great API for deploying dashboards but if we use that then editors can save their edits over the top of our production dashboards.  

So we basically need a way to restrict some editors from being able to save dashboards, without having to use dashboard provisioning.

**Comment by marefr** [comment]
Already available using [viewers_can_edit](https://grafana.com/docs/grafana/latest/installation/configuration/#viewers-can-edit) setting.

**Comment by kemarsh** [comment]
Perfect, thanks!
