### ISSUE TITLE
Use annotation query to represent a time range

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#20911]
**What would you like to be added**:
Use annotation query to represent a time range

Related to #3031. 

**Why is this needed**:
It is a useful feature that we want to see when the deployment is happening by overlay them into the corresponding charts that represent the SLO metrics might affected by the deployment. Currently it is not possible to represent the state of the system over a period of time, only discrete events can be represented using annotation query.

## Proposed impl
Using the same strategy for showing the data on the graph. 
![image](https://user-images.githubusercontent.com/21690857/70279377-9cf1ed80-1773-11ea-9518-f18676a2c969.png)
Instead of `line` and `points`, saying `range` and `discrete`, then the annotation can be overlaid on the graph in a more useful way.

**Comment by papagian** [comment]
@fredwangwang 
It's not clear to me your use case. Do you think that [region annotations in datasources](https://github.com/grafana/grafana/issues/10589) is what you are looking for?

**Comment by fredwangwang** [comment]
I think thats more like what I wanted. Didn't know it is something needs to be supported at data source level. Thanks for pointing to the correct direction!
