### ISSUE TITLE
MSSql: Adds support for region annotations

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [grafana/grafana#20918]
As discussed in other issues like #10589 it would be a really nice enhancement if it is possible to create **_region annotations_** by datasources. As we uses MS SQL as our primary data source it is a highly wanted feature. The feature has already been added for Elasticsearch as a datasource #17602 and the way it is implemented with an optionally _Enddate_ would be much prefered.

**Comment by papagian** [comment]
Duplicate of #10589

**Comment by HenrikRolandHansen** [comment]
is region annotation still not supported for Influxdb?
