### ISSUE TITLE
Tag Order on Dashboard Search View

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2091]
We'd like to have the tags in the dashboard search view consistent, either by:

(1) Respecting the order of the tags in the Dashboard Settings. 
(2) Sorting alphabetically. 

The first is preferable, because it will allow for better organization and consistency beyond just the alphabet, but I dont have an idea how much more complex that is. It also introduces the question of being able to reorder tags within dashboard settings (instead of deleting all and re-typing in the correct order). 

@torkelo Curious to hear your thoughts.

**Comment by torkelo** [comment]
sorted the tags alphabetically
