### ISSUE TITLE
3rd party use : Cannot assign to readonly property constructor

### ISSUE THREAD

**Issue by nitinsurana** [grafana/grafana#20921]
After executing `npm install @grafana/ui` added only the following in my code
`import { TimePicker } from '@grafana/ui';`
and it throws the following error :
```
index.development.js?74bd:formatted:161589 Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<Group>'
    at _inheritsLoose$l (index.development.js?74bd:formatted:161589)
    at eval (index.development.js?74bd:formatted:161598)
    at Object.eval (index.development.js?74bd:formatted:161893)
    at eval (index.development.js?74bd:formatted:214798)
    at Object../node_modules/@grafana/ui/index.development.js (vendors~app.js:2084)
    at __webpack_require__ (app.js:79)
    at eval (index.js?2ee8:6)
    at Object../node_modules/@grafana/ui/index.js (vendors~app.js:2096)
```

Nodejs: v10+
OS: MacOS
Browser: Chrome

**Comment by dprokop** [comment]
@nitinsurana thanks for reporting this. Couple of things:

What version of Grafana are you using?
Can you please check in your node_modules directory what version of grafana-ui was installed ?
Can you share the snippet of the code or the repository that I can reproduce this bug? I've just tried latest version of grafana/ui and I couldn't reproduce it.

**Comment by nitinsurana** [comment]
The version of @grafana/data & @grafana-ui that I'm using is `6.5.1`.
I'm using this in a big project. I'm trying to create a minimal reproducible example.
Meanwhile, I think it might be related to - https://github.com/babel/babel/issues/7447

**Comment by nitinsurana** [comment]
So, I switched to 6.4.5 and that works. :-)

So something has broken recently.

**Comment by dprokop** [comment]
@nitinsurana are you developing a Grafana extension, or you just want to use grafana-ui in some separate project?

**Comment by nitinsurana** [comment]
I'm using grafana-ui in a separate project.

**Comment by dprokop** [comment]
@nitinsurana then the problem is probably there. grafana-ui is intended to be used for developing Grafana extensions. We do not guarantee it's gonna work in projects that do not involve Grafana as a runtime. I'm gonna try to investigate the problem though. Keeping this issue open for a while.

**Comment by hermaproditus** [comment]
the same issue: https://github.com/alibaba/BizCharts/issues/583
btw, [BizCharts](https://github.com/alibaba/BizCharts) is so HUGE!
did your considering use the other visualization libraries?

**Comment by dprokop** [comment]
Update: seems like we bundle the UMD version of BizCharts which is causing the problem. I have tried forcing rollup to resolve the ES6 version of it but this seems to have some problems either. I'm gonna dig some more soon. Any

**Comment by dprokop** [comment]
@nitinsurana can you please test your code against the `next` version of grafana/ui?

**Comment by nitinsurana** [comment]
Tried using the canary version as below:
```
"@grafana/data": "^6.6.0-pre-1aa52f259c",
"@grafana/ui": "^6.6.0-pre-1aa52f259c",
```
 and got the following error : 
```
ERROR in ./node_modules/@grafana/ui/index.development.js
Module not found: Error: Can't resolve '@grafana/data/src/datetime/datemath' in '/Users/coding_idiot/go-workspace/src/bitbucket.org/logiqcloud/redash-fork/node_modules/@grafana/ui'
 @ ./node_modules/@grafana/ui/index.development.js 15:15-61
 @ ./node_modules/@grafana/ui/index.js
```

Without changing `@grafana/ui` version, tried with `"@grafana/data": "^6.5.2",` and `"@grafana/data": "^6.4.5",`, still the same error.

**Comment by dprokop** [comment]
@nitinsurana thanks for reporting. Any chance of providing us with repository we can reproduce the issue?

**Comment by alecxvs** [comment]
I think I'm seeing a similar issue, but only in unit testing; I'm seeing `TypeError: Cannot assign to read only property 'constructor' of object '#<Group>'` when importing @grafana/runtime in a typescript module. It loads @grafana/ui which loads BizCharts etc. etc. and eventually encounters this error.
```
 FAIL  src/datasource-zabbix/specs/datasource.spec.js
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'constructor' of object '#<Group>'

    > 1 | import { loadPluginCss } from '@grafana/runtime';
        | ^
      2 | import { ZabbixDatasource } from './datasource';
      3 | import { ZabbixQueryController } from './query.controller';
      4 | import { ZabbixDSConfigController } from './config.controller';

      at _inheritsLoose (node_modules/@antv/component/lib/axis/grid.js:1:137)
      at node_modules/@antv/component/lib/axis/grid.js:11:3
      at Object.<anonymous> (node_modules/@antv/component/lib/axis/grid.js:301:2)
      at Object.<anonymous> (node_modules/@grafana/ui/index.js:6:20)
      at Object.<anonymous> (node_modules/@grafana/runtime/index.development.js:7:10)
      at Object.<anonymous> (node_modules/@grafana/runtime/index.js:6:20)
      at Object.<anonymous> (src/datasource-zabbix/module.ts:1:1)
      at Object.<anonymous> (src/datasource-zabbix/specs/datasource.spec.js:3:1)
```

This isn't an issue when running in the browser, though. Normally this whole import is mocked by jest because loadPluginCss was throwing an error related to loading css (presumably because it's not actually running in the browser?) but I stumbled across this today while messing with Jest config.

I've tested this on the packages at 6.4.3, 6.4.5, and the latest 6.5.2.

**Comment by alecxvs** [comment]
Prerelease is showing
```
 FAIL  src/datasource-zabbix/specs/datasource.spec.js
  ● Test suite failed to run

    Cannot find module '@grafana/data/src/datetime/datemath' from 'index.development.js'

    However, Jest was able to find:
        '../module.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx', 'json'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/@grafana/ui/index.development.js:13:16)
```

Same results as @nitinsurana.

Not sure this is the same issue at this point but here's some more info

I replaced this in my local index.development.js
```
var data = require('@grafana/data');
...
var datemath = require('@grafana/data/src/datetime/datemath');
```
with
```
var data = require('@grafana/data');
...
var datemath = data.dateMath;
```
and I have no more failures in my Jest tests. Plus I don't have to mock any imports which seems great.

The path seemed suspect and it's being used in a couple places including here:
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/TimePicker/TimePickerContent/mapper.ts#L13

Not sure if this would cause it to compile the JS differently but this could probably use `isMathString` from the dateMath it's already importing.

**Comment by alexanderzobnin** [comment]
@dprokop got the same error when run Jest tests against latest `@grafana/ui` build:
```
Cannot find module '@grafana/data/datetime/datemath' from 'index.development.js'
```
I've found a reason - strange import here
https://github.com/grafana/grafana/blob/43dbbe51f0e05e87e684700c28034d16014d917f/packages/grafana-ui/src/components/TimePicker/TimePickerContent/TimeRangeForm.tsx#L7
