### ISSUE TITLE
A possibility to switch off the "smart" functionality of the PromQL query's editor

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#20929]
**What would you like to be added**:
It would be nice if there is a possibility to switch off (and on later) those "smart" functions of the PromQL query's editor.
(I mean e.g. autocomplete metric names / functions, getting query's result during changes of a query, etc.)

**Why is this needed**:
For more complex or more than one query the editor is not usable and one really must fight with it for expected results.
It is really annoying when you edit something at the end of a query, you pause and before you can continue the cursor jumps at the beginning of the query. Or even to the other query.
And when the query's result is rather big, the editor during changes is not responsive, there are lags between keystrokes and the cursor's movements.
It is really horrible.

NB From my point of view the editor's usability is getting worse, I'd say that there wasn't such issues before...

**Comment by davkal** [comment]
Understood. We're working on a fix to reduce the completion issues and will discuss turning assistance off completely.

**Comment by hawran** [comment]
> Understood. We're working on a fix to reduce the completion issues and will discuss turning assistance off completely.

Thank you very much.

**Comment by davkal** [comment]
If anyone is running a recent `master` and is still experiencing jumpy cursors or non-responsiveness, please post a comment in this issue describing your query and/or size of the prometheus system.

**Comment by hawran** [comment]
> If anyone is running a recent `master` and is still experiencing jumpy cursors or non-responsiveness, please post a comment in this issue describing your query and/or size of the prometheus system.

Hi davkal,
I'd like to report over here that it's really better now. (Grafana v6.5.2 (NA)).
Thanks again.

**Comment by davkal** [comment]
Thanks for reporting back @hawran 
v6.6 will come out in the next couple of weeks. It should have significantly better behavior when editing queries.

**Comment by hawran** [comment]
Hi,
I'm not sure whether I should open a new issue, however I have to say that I'm experiencing similar problems again:
- experiencing jumpy cursors
- non-responsiveness, event with that Firefox's yellow banner about '_some scripts are slowing down your browser_'

All of that even with "Disabled query" option in the query editor.

It's really annoying when one makes a typo within a query and it stops responding for a couple of seconds to show a that list box with words available..
