### ISSUE TITLE
Explore: Support react QueryEditor component in explore

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#20923]
Currently, explore only checks for ExporeQueryField or the angular query editor. It should also check/support the default QueryEditor interface.

**Comment by aocenas** [comment]
@kaydelaney I think this kinda aligns with what you are working on. If we remove the metrics/logs explicit switch I think we can also go with having any query editor work in explore and having specialised editors (like for logs) be just an optional nicety.

**Comment by ivanahuckova** [comment]
Closed by #24593
