### ISSUE TITLE
Different timeshift on same panel

### ISSUE THREAD

**Issue by kureikain** [grafana/grafana#2093]
Hi,

Is there a way we can display different timeshift on same panel? This way I can easily compare current and past metric. Right now, what I do is createing two panels with same metric and set time shift for one of them. Like this:

![screen shot 2015-06-01 at 1 56 28 pm](https://cloud.githubusercontent.com/assets/49754/7923197/1b87fe54-0866-11e5-92e4-506411ecd9ec.png)

Is it possible to combine those into a single panel, like what NewRelic does:

![screen shot 2015-06-01 at 1 59 54 pm](https://cloud.githubusercontent.com/assets/49754/7923275/8f490298-0866-11e5-82d7-ae7fedc9fbb3.png)

Ideally when we do time shift by days, we can display same time range. When we do time shift by hours, we can just hide the time frame. The main ideal is to compare the metric when putting them on same panel. 

Similar feature in Graphite
![tip10-c](https://cloud.githubusercontent.com/assets/49754/7923721/6c51d2de-086a-11e5-9afb-32abdaae8e7c.png)

**Comment by torkelo** [comment]
what time series database do you have? Graphite does this very nicely through timeShift function. I suggest you open an issue with the time series database you have an request this feature. Makes more sense to have this in the query language for the time series store.

**Comment by patjlm** [comment]
Any suggestion on how to do this with an ElasticSearch backend ?
Would it be worth having a timeshift option in the ElasticSearch query panel ?

**Comment by torkelo** [comment]
I looking at ways to create meta queries that can act on any data source query, a meta query could then transform another query, like timeShift(#A, 1d)   (where #A is a reference to query A which is an elasticsearch query). Not sure when this will be available but maybe early next year.

**Comment by patjlm** [comment]
Thanks for the info!
Great work!

**Comment by patjlm** [comment]
Just to add, I saw there is a recent feature about this in ElasticSearch called serial differencing pipeline aggregation:
https://github.com/elastic/elasticsearch/pull/11196
It may be of some help in your upcoming work on this topic

**Comment by SindhujaSoundarapandian** [comment]
Hello,

I have a requirement to display the executions results of successive builds across the weeks in a trend like

Transaction            b1           b2      b3
Login                     xx              yy       zz
Dashboard            aa              bb       cc

we want a trend on login transaction and dashboard transactions across the builds 

I tried with timeshift function but its not working. anyhelp is much appreciated

**Comment by nfw999** [comment]
We use this plugin to solve the problem and hope to help you.

**Comment by nfw999** [comment]
We use this plugin to solve the problem and hope to help you.

**Comment by nfw999** [comment]
We use this plugin to solve the problem and hope to help you.
https://github.com/AutohomeCorp/graph-compare-panel
![Screenshot1](https://raw.githubusercontent.com/AutohomeCorp/graph-compare-panel/master/dist/screenshots/image-1.png)
![Screenshot1](https://raw.githubusercontent.com/AutohomeCorp/graph-compare-panel/master/dist/screenshots/image-2.png)

**Comment by Byteme71** [comment]
@nfw999 my timeshift data is behind by 1 day, is there anyway i can fix this?

**Comment by gesnus** [comment]
Good evening,

I have updated grafana to version v8.1.3 and my compareQueries datasource stopped working. The graph only shows me the data of the main query and does not react to any action. 

Can you please help me? Thank you very much.

![imagen](https://user-images.githubusercontent.com/44234557/133157714-5446c5dc-f2ce-404d-88bf-27cd90c8bf38.png)

**Comment by nfw999** [comment]
![image](https://user-images.githubusercontent.com/33611490/133252255-8ea727c6-e68a-42b3-97ad-cbe2c7d59e22.png)
I upgraded grafana to 8.13 and there is no problem
Is compareQueries  the latest version ？

**Comment by gesnus** [comment]
I have updated to the latest version of the plugin and it already works correctly.

Thank you very much

**Comment by matejanajdanov** [comment]
Is there a way to do this with any signed plugin? Both CompareQueries and metaQueries plugins aren't and there are no updates on these...

**Comment by eFeSist** [comment]
comparison plugins should be signed. this type of panels necessary for monitoring the way of events. is there any voting place for this kind of demands?

**Comment by leoswing** [comment]
> comparison plugins should be signed. this type of panels necessary for monitoring the way of events. is there any voting place for this kind of demands?

@eFeSist @matejanajdanov @gesnus  Hi , the plugin reconstruction with React has now released, it's compatible with Grafana 10 and 11, and signed with public signature, welcome to use the plugin with latest version 2.0.2

Details plugin info as below:

[comparequeries](https://github.com/leoswing/comparequeries-datasource-rc)
[grafana-plugin catelog](https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/)
