### ISSUE TITLE
Explore: Browsing back after switching datasource changes time picker

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#20933]
0. Explore with 2 prometheus datasources
1. Make sure time picker uses a relative time like Last 1h
2. Run a query in first promtheus
3. Run a query in second prometheus
4. Use browser button to go back

Result: Time picker now has an absolute range.
Expected: Time picker should keep relative range.

**Comment by ivanahuckova** [comment]
@davkal I was trying to look at this issue, but I wasn't able to reproduce it on master or on https://play.grafana.org/.  After using browser *back button* , time picker kept the selected relative range.   So I am not sure, if I correctly understand the issue, or if it was already fixed.
