### ISSUE TITLE
One install script that works on multiple distributions. 

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#20939]
While working through the different options for installing Grafana with @oddlittlebird it became apparent that there is a lot of linux/debian/rhel knowledge required to be successful today.

It seems like we could simplify the process a lot for our users if we provide a shell "installer" script that automates the process:
- identify the architecture and os
- configure the apt or yum repo & key(s)
- install the package
- start & enable the service

At least initially I'd suggest focusing on the `.deb` and `.rpm` packages, and my suggestion would be that the script should use the yum/apt repos so that upgrading grafana later on is as simple as possible (and ideally Just Works when the user runs `apt upgrade` or `yum upgrade`).

If we provide this script, then install instructions for debian and rhel-based distros could be as simple  as "download and execute `https://grafana.com/install.sh`"

**Comment by oddlittlebird** [comment]
@daniellee and @marcusolsson , this seems to be right in line with some of our goals for making Grafana more accessible. It would also streamline the installation and getting started instructions immensely.

**Comment by oddlittlebird** [comment]
The installer script should also enable the Grafana service to run on system boot.
