### ISSUE TITLE
Cloudwatch Datasource - Container Insights: Metric name doesn't list available metrics

### ISSUE THREAD

**Issue by madhura93** [grafana/grafana#20935]
**What happened**:
On adding a cloudwatch datasource and selecting container insights dimensions, metric name field displays blank list of metrics
**What you expected to happen**:
on adding cloudwatch datasource and selecting container insights, metric name should display a list of available metrics
**How to reproduce it (as minimally and precisely as possible)**:
Add a cloudwatch datasource, create/use a dashboard, add a query, select containerInsights dimension
**Anything else we need to know?**:
Container Insights is enables on the ECS cluster, role/user has the right permissions to cloudwatch
**Environment**:
- Grafana version: v6.5
- Data source type & version: CloudWatch
- OS Grafana is installed on:Linux
- User OS & Browser:Mac, Chrome
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
@madhura93 
Could you please send the requests/responses to `api/tsdb/query` from your browser's developer tools (Network tab)?
Also, please verify you can see the metrics in AWS CloudWatch console using same time range and dimensions.
Finally, you maybe find [this](https://github.com/grafana/grafana/pull/18971#issuecomment-539529651) comment useful.

**Comment by briancurt** [comment]
I'm running 6.5.1 and have the same issue where the `Metric Name` dropdown is blank.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/16437255/70728652-1ce2ff00-1d02-11ea-9369-6166dc6b0cad.png">

There are the requests/responses to `api/tsdb/query`
Request
```
{
   "from":"1576144894573",
   "to":"1576166494573",
   "queries":[
      {
         "refId":"metricFindQuery",
         "intervalMs":1,
         "maxDataPoints":1,
         "datasourceId":5,
         "type":"metricFindQuery",
         "subtype":"metrics",
         "region":"us-east-1",
         "namespace":"ContainerInsights"
      }
   ]
}
```
Response
```
{
   "JSON":{
      "results":{
         "metricFindQuery":{
            "refId":"metricFindQuery",
            "meta":{
               "rowCount":0
            },
            "series":null,
            "tables":[
               {
                  "columns":[
                     {
                        "text":"text"
                     },
                     {
                        "text":"value"
                     }
                  ],
                  "rows":[

                  ]
               }
            ],
            "dataframes":null
         }
      }
   },
   "Response payload":{
      "EDITOR_CONFIG":{
         "text":"{\"results\":{\"metricFindQuery\":{\"refId\":\"metricFindQuery\",\"meta\":{\"rowCount\":0},\"series\":null,\"tables\":[{\"columns\":[{\"text\":\"text\"},{\"text\":\"value\"}],\"rows\":[]}],\"dataframes\":null}}}",
         "mode":"application/json"
      }
   }
}
```

**Comment by madhura93** [comment]
The metrics are available in cloudwatch for a selected time range and dimension.  **aws cloudwatch list-metrics --namespace ECS/ContainerInsights**  returns a list of metrics that are  available. In Grafana the namespace is ContainerInsights instead of  **ECS/ContainerInsights** , not sure if this is the cause. 

Request:
```{
  "from": "1576153320052",
  "to": "1576174920052",
  "queries": [
    {
      "refId": "metricFindQuery",
      "intervalMs": 1,
      "maxDataPoints": 1,
      "datasourceId": 28,
      "type": "metricFindQuery",
      "subtype": "metrics",
      "region": "us-east-1",
      "namespace": "ContainerInsights"
    }
  ]
}
```
Response:
```
{
  "results": {
    "metricFindQuery": {
      "refId": "metricFindQuery",
      "meta": {
        "rowCount": 0
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "text"
            },
            {
              "text": "value"
            }
          ],
          "rows": []
        }
      ],
      "dataframes": null
    }
  }
}
```

**Comment by papagian** [comment]
@madhura93
It seems that the `ContainerInsights` namespace is for [Amazon EKS and Kubernetes](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html) contrary to the `ECS/ContainerInsights` that is for [Amazon ECS](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html).
Currently only the former is supported in Grafana. The support was introduced by [this](https://github.com/grafana/grafana/pull/18971) change and something similar should be added for the `ECS/ContainerInsights` namespace.

**Comment by marefr** [comment]
For anyone interested in contributing this is the file that needs update of metric and dimensions: https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go

**Comment by briancurt** [comment]
Created https://github.com/grafana/grafana/pull/21125

**Comment by AndrewFarley** [comment]
FYI, I just ran a nightly and it works and pulls these new metrics wonderfully.

For anyone trying this, to save you some time, many of the new ECS Container Insight metrics require multiple dimensions just to return any data.  Eg: ClusterName and ServiceName, or ClusterName and TaskDefinitionFamily.  Just a heads up, so anyone who lands here doesn't get frustrated why their metrics aren't showing up.

**Comment by Aminechakr** [comment]
From version 6.6 working fine for me :white_check_mark:

**Comment by Aminechakr** [comment]
From version 6.7.4 working fine :white_check_mark:

**Comment by danidosreis** [comment]
> FYI, I just ran a nightly and it works and pulls these new metrics wonderfully.
> 
> For anyone trying this, to save you some time, many of the new ECS Container Insight metrics require multiple dimensions just to return any data. Eg: ClusterName and ServiceName, or ClusterName and TaskDefinitionFamily. Just a heads up, so anyone who lands here doesn't get frustrated why their metrics aren't showing up.

Thank youuu!!!!

**Comment by srflaxu40** [comment]
> FYI, I just ran a nightly and it works and pulls these new metrics wonderfully.
> 
> For anyone trying this, to save you some time, many of the new ECS Container Insight metrics require multiple dimensions just to return any data. Eg: ClusterName and ServiceName, or ClusterName and TaskDefinitionFamily. Just a heads up, so anyone who lands here doesn't get frustrated why their metrics aren't showing up.

Someone put this in big, bold red font somewhere lol

**Comment by montumodi** [comment]
> FYI, I just ran a nightly and it works and pulls these new metrics wonderfully.
> 
> For anyone trying this, to save you some time, many of the new ECS Container Insight metrics require multiple dimensions just to return any data. Eg: ClusterName and ServiceName, or ClusterName and TaskDefinitionFamily. Just a heads up, so anyone who lands here doesn't get frustrated why their metrics aren't showing up.

Thank you so much. Saved so much effort. I was scratching my head why nothing was showing.
