### ISSUE TITLE
Default URL should be http://localhost:9200/ but http://localhost:3100/

### ISSUE THREAD

**Issue by t-umeno** [grafana/grafana#20945]
**What happened**:
When add Datasource/Elasticsearch, default URL is http://localhost:3100/
**What you expected to happen**:
Default URL should be http://localhost:9200 when datasource is Elasticsearch
**How to reproduce it (as minimally and precisely as possible)**:
Configuration -> Datasource -> Elasticsearch
**Anything else we need to know?**:
Default URL is http://localhost:9200/  before 6.5.0 (example: 6.4.5)
**Environment**:
- Grafana version: 6.5.0 and 6.5.1
- Data source type & version: Elasticsearch & any version
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: macOS 10.13.6 and firefox 71.0
- Grafana plugins: none
- Others: none

**Comment by papagian** [comment]
Most probably it was introduced during [migration](https://github.com/grafana/grafana/commit/551e24f9f8acc238d42b7d87bf21873f87721ae2) of of Elastic configuration pages to React.
