### ISSUE TITLE
Renaming Dashboard does not update the name in playlist

### ISSUE THREAD

**Issue by vmario89** [grafana/grafana#20943]
Hi,

in all versions of Grafana i know this issue happens: renaming a dashboard does not update the name in of the Dashboard in playlist. To fix it i have to remove the item, select it from search list and the reorder the playlist by using the top/down arrows.

I am running Grafana 6.5.0 on Raspbian Stretch on Raspberry Pi 3 B+.

regards and thanks, Mario

**Comment by papagian** [comment]
Thank you for reporting this.
During dashboard renaming the `title` column of the `playlist_item` table should be updated too.
