### ISSUE TITLE
Ability to hide rows and panels

### ISSUE THREAD

**Issue by keithknott26** [grafana/grafana#20958]
**What would you like to be added**:
It would be great if you could hide rows and panels when there is a "No data" condition. 

**Why is this needed**:
The use case is that I have a dashboard with graphs for multiple types of services (MQ, Webservices, File based, etc) and each type of service is stored in a row.  I have a dropdown (template variable) on top which is controlling which application is viewed. Each application has a service with a "type" of:  MQ, Webservices, File based, etc and I am using one dashboard to view them all.

I've attached a screenshot showing the dashboard, I'd essentially want to hide rows (or panels) when there is "no data" displayed on the graph or panel. This way, only panels and rows that have data will appear in the dashboard, currently alot of screen real estate is taken up by empty graphs.

![image](https://user-images.githubusercontent.com/16966683/70422948-76f17500-1a21-11ea-9e72-8fc713c70179.png)

![image](https://user-images.githubusercontent.com/16966683/70423093-b0c27b80-1a21-11ea-98c2-1d3f9f8414cb.png)

**Comment by torkelo** [comment]
similar to this https://github.com/grafana/grafana/issues/4470 

There is currently no way for Grafana to know what there is no data here, and having hidden panels that issue queries make it impossible to interact / edit them (requires a new edit mode)
