### ISSUE TITLE
Panel plugin with id myorgid-simple-panel could not be found

### ISSUE THREAD

**Issue by efvhi** [grafana/grafana#20954]
**What happened**: after  installed a external plugin  (`simple-react-panel`) into  grafana v6.0.0 version, got error

**What you expected to happen**: the plugin works

**How to reproduce it (as minimally and precisely as possible)**: just reinstall the plugin 

**Anything else we need to know?**:  works on v6.5.0, why ? how can i make it works on v6.0.0?

**Environment**:
- Grafana version: 6.0.0
- Data source type & version: no
- OS Grafana is installed on: yes
- User OS & Browser: centos, safari
- Grafana plugins: https://github.com/grafana/simple-react-panel
- Others:

**Comment by torkelo** [comment]
It's not compatible with 6.0 only 6.5+
