### ISSUE TITLE
Plugin installation fails in Docker with read-only container

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#20950]
**What happened**:
I pulled Grafana 6.5.1 and restarted the Docker container. I'm now greeted with:

```
Dec 08 11:40:26 endor docker[8965]: Error: ✗ Failed to create temporary file: open /tmp/806378690.zip: read-only file system
Dec 08 11:40:26 endor docker[8965]: NAME:
Dec 08 11:40:26 endor docker[8965]:    Grafana cli plugins install - install <plugin id> <plugin version (optional)>
Dec 08 11:40:26 endor docker[8965]: USAGE:
Dec 08 11:40:26 endor docker[8965]:    Grafana cli plugins install [arguments...]
```

This happens b/c the container itself is started as read-only, since it should not be modifying itself at runtime.

**What you expected to happen**:
Everything to start normally.

**How to reproduce it (as minimally and precisely as possible)**:
```
docker run \
                           --name grafana \
                           --read-only \
                           -p 127.0.0.1:3000:3000 \
                           --expose 3000 \
                           -v grafana_data:/var/lib/grafana:rw \
                           --env-file /etc/docker/config/grafana/config.env \
                           grafana/grafana:6.5.1
```

```
GF_INSTALL_PLUGINS=cloudflare-app,grafana-worldmap-panel,grafana-image-renderer
```

**Anything else we need to know?**:

This worked fine on 6.4.x. This appears to be a consequence of #19639, as it now uses the filesystem instead of staying in memory. The release and upgrade notes for 6.5.x fail to capture the consequence of this change. In the case of the Docker image it would be helpful if Grafana CLI would use `/var/lib/grafana` as its staging area, as that's a mounted filesystem: https://github.com/grafana/grafana/blob/master/Dockerfile#L56 or would look at the `paths.data` configuration value.

**Environment**:
- Grafana version: 6.5.1
- OS Grafana is installed on: Ubuntu 18.04 LTS + Docker

**Comment by daenney** [comment]
It really comes down to this line: https://github.com/grafana/grafana/blob/4ad8b6f030273b40ea22ab9486ca8739af7a7b9b/pkg/cmd/grafana-cli/commands/install_command.go#L112

If `ioutil.TempFile()` would be given `paths.data/tmp` or something along those lines as the first argument we wouldn't have this problem. It might be useful to make this configurable, using something like a `paths.temp` config option so people can specify what temporary filesystem path to use.

**Comment by daenney** [comment]
Another option is to document setting `TMPDIR` in the environment as something like `/var/lib/grafana/temp`. Since `ioutil.TempFile()` uses `os.TempDir()` which respects that environment variable that would be another way to get around it.

**Comment by daenney** [comment]
I ended up getting around this using `--mount type=tmpfs,destination=/tmp` as an argument to `docker run`.

**Comment by papagian** [comment]
thank you for reporting this.

**Comment by aknuds1** [comment]
Is it documented anywhere that Grafana shouldn't write anywhere outside of its data directory?

**Comment by daenney** [comment]
I don't expect any of my containers to modify their running image at runtime, which is what happens with the plugin installation defaulting to `/tmp`. Running containers as read-only in production is a fairly standard practice.

If it weren't running in a container this would've been fine. So it's not so much that Grafana shouldn't write outside of `/var/lib/grafana`, but when running from a container the behaviour needs to be controllable at least.

**Comment by aknuds1** [comment]
@daenney Grafana does write to the root filesystem by default though, the only reason it doesn't in your case is that you mount another volume read-write at /var/lib/grafana? If you start a Grafana container in read-only mode without the /var/lib/grafana mount it'll fail.

I think this issue isn't a bug really, but rather a feature request that Grafana doesn't write outside of certain directories (/var/lib/grafana, /var/log/grafana AFAICT). We are discussing this internally.

**Comment by daenney** [comment]
I don't entirely agree with that assessment. The docs make it pretty clear that `paths.data` needs to be writable: https://grafana.com/docs/grafana/latest/installation/configuration/#data. 

As such, anyone running Grafana in a container that doesn't want it to be ephemeral will catch on to that, and mount a filesystem there, regardless of whether they are running the container itself as read-only. The docs also explicitly say "and other data." so it's reasonable to assume that's where it will chose to write things, if it has to write things.

The exception is logs, but since that logs to stdout in the container that's not an issue.

**Comment by aknuds1** [comment]
You can't mount a filesystem in /var/lib/grafana "regardless of whether they are running the container itself as read-only". If you run a Grafana container in read-only mode without mounting an RW volume at /var/lib/grafana, it will fail. I just tested to make sure. Regarding logs, if you enable writing logs to file, Grafana will write to /var/log/grafana by default, so that's another case that can break if running Grafana on a read-only FS.

So, my point stands that I think we need to see this as a feature request for defining where Grafana can write to the filesystem, otherwise we will again break such use cases in the future.
