### ISSUE TITLE
Templating: Multi-select keyboard toggle bug

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#20953]
**Steps to reproduce**:

On a template variable with multi-select:
  1. enter a search which matches one or more items
  2. navigate by keyboard to an item
  3. use space bar to toggle the item

**Actual Result**:
The space bar input is appended or prepended to the search text.

**Expected Result**
The search text should remained unchanged, since focus is on a dropdown item.

**Relevant WCAG Criteria:**
?

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: n/a
- User OS & Browser: Mac OS / Chrome

screen recording of the issue:
![grafana_multi_select_keyboard](https://user-images.githubusercontent.com/1708631/70399213-5814d200-1a65-11ea-9ad3-ee04c251750a.gif)

**Comment by torkelo** [comment]
Think it can be fixed here: 
https://github.com/grafana/grafana/blob/master/public/app/core/directives/value_select_dropdown.ts#L151

**Comment by belm0** [comment]
It looks like the filter text widget does not blur when the dropdown is active.

My angular skills are too rusty to see a fix.

**Comment by belm0** [comment]
another bug, from reading the code:  `highlightIndex` can become arbitrarily negative

1. focus on variable widget
2. press up-arrow N times
3. press down-arrow N+1 times

on down-arrow N+1, the first item in the dropdown will be highlighted

**Comment by belm0** [comment]
accessibility issue:  the special "Selected" item cannot be selected by keyboard nav

**Comment by belm0** [comment]
roughly, to fix the original reported bug:

1. the text input needs to ng-blur when `vm.highlightIndex >= 0`

https://github.com/grafana/grafana/blob/2c2ed8371dfad462a02db4a04cdcc990b7e51f2b/public/app/partials/valueSelectDropdown.html#L17

2. when text input regains focus, set `vm.highlightIndex = -1`

**Comment by belm0** [comment]
another bug:  when an item is clicked by mouse, subsequently pressing space / up-arrow / down-arrow do not work as expected (toggle, previous item, next item)

`vm.highlightIndex` needs to be set to the item selected by mouse

**Comment by belm0** [comment]
another bug, I happened to see this client-side exception on v6.4.3:

```
angular.js:14700 TypeError: this.hide is not a function
    at e.keyDown (value_select_dropdown.ts:140)
    at fn (eval at compile (angular~app.e402a76d33a475eefbc0.js:1), <anonymous>:2:241)
    at i (angular.js:27341)
    at c.$eval (angular.js:18423)
    at c.$apply (angular.js:18523)
    at HTMLInputElement.<anonymous> (angular.js:27346)
    at HTMLInputElement.dispatch (jquery.js:5237)
    at HTMLInputElement.g.handle (jquery.js:5044)
```

**Comment by thedeveloperr** [comment]
@marefr would like to try to fix this one. Might take time as gonna contribute to angular code after a long time.

**Comment by marefr** [comment]
@thedeveloperr please go ahead. Assigning you to the issue

**Comment by LucasRaschek** [comment]
I might be wrong because I am new to this project, but I think the solution may be as easy as a simple `event.preventDefault();`
Adding a preventDefault below the line I linked, solved the problem for me on my local environment.
[Link to File](https://github.com/grafana/grafana/blob/13787294c6b3bbf7e7d797c3048758e13ee6443e/public/app/features/variables/pickers/shared/VariableInput.tsx#L14)

**Comment by belm0** [comment]
there are 2 or 3 other bugs mentioned in this issue which I found while reading the code

**Comment by hugohaggmark** [comment]
@belm0 could you please open separate issues for that? As far as I can see the merged PR fixes the main issue as described in this PR.
