### ISSUE TITLE
Use https to fetch gravatar images by default

### ISSUE THREAD

**Issue by jiajunhuang** [grafana/grafana#20955]
**What would you like to be added**:
Use https to fetch gravatar images by default.
**Why is this needed**:
this weekend I found that my avatar in Grafana does not shown. I found that the HTTP request had been hijacked, because it use HTTP protocol. why not use https by default?
```go
func UpdateGravatarSource() {
	srcCfg := "//secure.gravatar.com/avatar/"

	gravatarSource = srcCfg
	if strings.HasPrefix(gravatarSource, "//") {
		gravatarSource = "http:" + gravatarSource
	} else if !strings.HasPrefix(gravatarSource, "http://") &&
		!strings.HasPrefix(gravatarSource, "https://") {
		gravatarSource = "http://" + gravatarSource
	}
}
```

**Comment by torkelo** [comment]
can you open a PR?

**Comment by jiajunhuang** [comment]
@torkelo hello, it's here: https://github.com/grafana/grafana/pull/20964 please review it, thanks :-)
