### ISSUE TITLE
"CloudWatch templating error" when using Multi template variables in statistics field

### ISSUE THREAD

**Issue by NilsHasenbanck4758** [grafana/grafana#20960]
This problem seems to have the same toor cause like #20839 

I upgraded our Grafana dashboard from 6.4 to 6.5.1 Since then some dashbboards with a cloudwatch datasource are throwing following error as a popup:

```
CloudWatch templating error
Multi template variables are not supported for statistics
```

This seems to be a false error message, since multi-value variables in the statistics field of a cloudwatch data source query are working fine and the dashboard is actually working perfectly and as expected.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: cloudwatch
- OS Grafana is installed on: linux

**Comment by sunker** [comment]
Thanks for reporting this @NilsHasenbanck4758.

Please let me know step by step how I can get this to work. Also please paste your query - QueryInspector > Copy to clipboard.

**Comment by NilsHasenbanck4758** [comment]
1. Create a variable wirth percentiles (p99, p95, p90):
![grafik](https://user-images.githubusercontent.com/39552656/70602160-0d759000-1bf4-11ea-9a54-96d238734411.png)

2. Create a row that uses the variable.
![grafik](https://user-images.githubusercontent.com/39552656/70602202-25e5aa80-1bf4-11ea-816b-364fd7b0e1fb.png)

3. Create a query that uses the percentile.
<img width="889" alt="grafik" src="https://user-images.githubusercontent.com/39552656/70602898-b8d31480-1bf5-11ea-8bde-8c17df097323.png">


```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1575964285196",
      "to": "1576050685196",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 900000,
          "maxDataPoints": 100,
          "datasourceId": 1,
          "type": "timeSeriesQuery",
          "alias": "",
          "dimensions": {
            "metric": "METRICNAME",
            "namespace": "LogMetrics",
            "team": "find"
          },
          "expression": "",
          "highResolution": false,
          "id": "",
          "metricName": "METRICNAME",
          "namespace": "NAMESPACENAME",
          "period": "86400",
          "region": "eu-central-1",
          "returnData": false,
          "statistics": [
            "p99"
          ],
          "datasource": "DATASOURCE"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "unit": "s"
        },
        "series": [
          {
            "name": "METRICNAME_p99",
            "points": [
              [
                XXXXX.XXXX,
                XXXXX.XXXX
              ]
            ],
            "tags": {
              "metric": "METRICNAME",
              "namespace": "LogMetrics",
              "team": "TEAMNAME"
            }
          }
        ],
        "tables": null
      }
    }
  }
}
```

So the problem is really that the error message is thrown by simply using a variable that is defined as multi-value, even though it effectively is used as a single value (because of the row multiplication). So the error should only be thrown, if the query actually contains multiple values in the statistic field and not just by simply beeing the variable defined as a multi-values variable.

**Comment by sunker** [comment]
Sure, but why would you make it a multi-template variable when you only use one value anyway?

**Comment by NilsHasenbanck4758** [comment]
Because I want to use it in another query in the dashboard with multiple values to another datasource.

The error check is not complete (since it's a valid query in this context). So the question is: Why should the program throw an ERROR in this case? Since obviously no error has occured.

**Comment by ddes** [comment]
I have the same issue, by using a multi-values variable with cloudwatch API.
It was working fine on 6.4 but I have now this error message on 6.5.2.

However the graphs are working well as I'm using the Repeat feature on each graphs, so in the end the var is always uniq in the request.

**Comment by chrs-myrs** [comment]
Having an issue with this too, we want to iterate over metrics, so each chart only shows one metric, however it seems to pass the variable to the chart as a multi-value variable with one value, which causes the error specified by the OP

This is itself a workaround to the annoyance that cloudwatch log filters do not support dimensions, but still feels like this should work

**Comment by wjbuys** [comment]
I'm seeing the same issue here. I'm trying to make a graph with Repeating Rows for multiple AWS Regions, so I made a Template Variable with the Regions we're using:

![image](https://user-images.githubusercontent.com/31602/121754974-d1620a80-caca-11eb-90c6-d5f843e05fb2.png)

Then I added a repeating row for `$Region` to the dashboard, and tried to use the `$Region` variable as the `Region` field on the Cloudwatch query for the panels in this row. This works, and correctly displays all the graphs in multiple repeating rows, but unfortunately it always pops up an error message:

![image](https://user-images.githubusercontent.com/31602/121755047-05d5c680-cacb-11eb-912c-11fc2f308791.png)

**Comment by sunker** [comment]
I think this problem will be solved once [this](https://github.com/grafana/grafana/issues/30629) is implemented. Hopefully will get time to work on this sometime soon.

**Comment by dragoangel** [comment]
Hi, any update on the case?

**Comment by wjbuys** [comment]
FYI, this is still an issue for `$Region` variables, so I've opened a new issue: #44733
