### ISSUE TITLE
Elasticsearch datasource: support date_nanos type

### ISSUE THREAD

**Issue by bmerry** [grafana/grafana#20963]
**What would you like to be added**:
Support using an Elasticsearch field with type `date_nanos` (ES 7.x feature for nano-second precision timestamp) as the "Time field name" when configuring an ES datasource.

Note: I'm not asking for Grafana to handle the value with nanosecond precision (which I imagine would be difficult in Javascript since it only has double-precision types).

**Why is this needed**:
In Grafana 6.5.1, trying to use an ES index where `@timestamp` is of type date_nanos just reports `no date field named @timestamp found`.

**Comment by marefr** [comment]
Changes at least needed in this type map:
https://github.com/grafana/grafana/blob/0c89b93ce06dc6fee4e7da3c586d871ce97a4621/public/app/plugins/datasource/elasticsearch/datasource.ts#L382-L392

Not sure if that's enough or if there's logic needed to handle receiving of nanosecond timestamps.
