### ISSUE TITLE
Alerts aren't saved after uploading to the server

### ISSUE THREAD

**Issue by mifarse** [grafana/grafana#20975]
**What happened**:
I generate json dashboards and upload to the server. It saves dashboard and related to it alerts. Alerts appear in alerts list, however it doesn't work as it should.  

[Screenshot. All alerts are in unknown state](https://imgur.com/AGaWVVT)

Afterwards, I open panel with alert, switch to alert section and click "test alert" button. Nothing changes in json structure. I click "save dashboard" and alert works. 

**What you expected to happen**:
Grafana is supposed to save alerts at the first time.

**How to reproduce it (as minimally and precisely as possible)**:
Actually, I don't know how to reproduce it properly, since if you try to build dashboard inside Grafana, save it and then retrieve json file and upload it afterwards it is likely to work.

**Anything else we need to know?**:
Yes. First of all, there is no errors in the alert conditions and queries. I figured out how to fix the bug. I had explored grafana.db file. I've found that the only difference between properly working alert and "unknown" one is the following: working alert has not empty column called "eval_data" in "alerts" table, it contains empty brackets (literally, it contains just "{}"). I tried to run a query in sqilte, like "update alerts set eval_data='{}'" and all dashboard alerts began to work as it should be! 

**Environment**:
- Grafana version: all kind of Grafana, in particular 6.5.0
- Data source type & version: Influx DB 1.7.4
- OS Grafana is installed on: Ubuntu 18.04.3
- User OS & Browser: Firefox 70, but it doesn't matter, it is obviously backend bug.
- Grafana plugins: it uses vanilla grafana tools.
- Others:

**Comment by torkelo** [comment]
how are you provisioning the dashboards / "uploading" them? can you share your dashboard json?

**Comment by mifarse** [comment]
I use [Grafana API](https://grafana.com/docs/grafana/latest/http_api/dashboard/#create-update-dashboard) for uploading. Dashboards generation is based on [Grafanalib](https://github.com/weaveworks/grafanalib) Python library. 

Here are attached two files (both of them are hosted on Github Gist):

1. Dashboard file, which is generated automatically by the script [generated-alert-dashboard.json](https://gist.github.com/mifarse/c33a8402ed232f702b1e91a49625818c)  

2. This is version of the json which was post-processed by Grafana server after it has been uploaded: [grafanas-alert-dashboard.json](https://gist.github.com/mifarse/122ce78145fd168962bce1fe89a99d8b)

**Comment by marefr** [comment]
You have incorrectly used named property `collapse` in row instead of the correct one `collapsed`.
