### ISSUE TITLE
Package certain Grafana back-end plugins

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#20972]
**What would you like to be added**:
We need to implement packaging/distribution/build of certain backend plugins with Grafana (different executables, but “core” Grafana, for example, meta-analytics, GEL, SQL Datasources).

**Comment by ryantxu** [comment]
See also https://github.com/grafana/grafana/pull/20850

**Comment by aknuds1** [comment]
cc: @kylebrandt

**Comment by aknuds1** [comment]
This is done.
