### ISSUE TITLE
Add median to the legend for graph panels

### ISSUE THREAD

**Issue by pbooth** [grafana/grafana#2097]
The legend feature on the graph panel is a very useful way to communicate absolute values of time-series, especially when graphing latencies. But for latencies, the median is a more useful summary than the average. It would be great if the median were added to the list of possible legend values.

**Comment by pbooth** [comment]
See this example where the median value is more representative than the average:

Proposed:

![grafanaproposed](https://cloud.githubusercontent.com/assets/34048/7935843/2448f24a-0902-11e5-88d4-c001fb9122a4.png)

Existing:

![grafanaexisting](https://cloud.githubusercontent.com/assets/34048/7935866/4758d214-0902-11e5-803f-f89d0e104a2b.png)

**Comment by torkelo** [comment]
sure, just be careful showing min, max and avg (or median) on the same graph at the same time. Only ONE of them will be correct  (depending on how many values exist for the time range InfluxDB or Graphite will consolidate the series down to one data point per pixel on the graph). the Legend min, max, avg are calculated client side by grafana AFTER Graphite or InfluxDB consolidates data points (using avg or min, or max, depending on how your query looks). 

So I always point out every time I see someone having min, max and avg on the same graph that it can be very misleading!

**Comment by bergquist** [comment]
The fact that AVG is kinda miss leading is not optimal. But most of us don't trust avg anyway. 

But I don’t want to add more aggregations on the front end. 
Especially not median, which itself is a demand for more correct data.

**Comment by pbooth** [comment]
That's a shame. Median is, in many senses, the best summary number, particularly when
comparing distributions. 

Right now the legend is the best alternative to a Table Panel there is. 
Holy shit ! I see that a tabel panel has appeared in grafana 2.6. ;-)

thanks,

Peter

On Dec 17, 2015, at 09:22 AM, Carl Bergquist <notifications@github.com> wrote:

The fact that AVG is kinda miss leading is not optimal. But most of us don't trust avg anyway.
But I don’t want to add more aggregations on the front end. 
Especially not median, which itself is a demand for more correct data.

**Comment by no-identd** [comment]
🤔
