### ISSUE TITLE
XSS Javascript can run in Panel link URL

### ISSUE THREAD

**Issue by ytturi** [grafana/grafana#20974]
**What happened**: Javascript can be used within the link parameter of panel links (with malicious intentions). 

**What you expected to happen**: Only URL redirection is allowed (Sanitize input before saving (?)).

**How to reproduce it (as minimally and precisely as possible)**: 

1. Edit a panel. 
2. Go to the config tab.
3. Add a panel link.
4. Write javascript in the URL (i.e.: URL=> `alert(document.domain)`). 
5. Save.
6. Click the link from the panel.

**Anything else we need to know?**: The malicious user has to be able to edit a panel.

**Environment**:
- Grafana version: 6.3.5 (Did not check any new version, but I did not see any issue related to this)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A (Default)
- Others: N/A

**Comment by torkelo** [comment]
unable to replicate in v6.5 , please upgrade. 

Panel Links were overhauled in v6.4

**Comment by gilkgit** [comment]
Before sanitizing, can you follow the pattern of Text panel, and first check some config setting to decide whether to sanitize or not?
For me, enabling Javascript in Panel links is really valuable, probably to others too,
especially considering that the datasource I use does not expose the "__series.labels.<LABEL>" variables, so Javascript in links will enable drill-in scenarios for me.

**Comment by torkelo** [comment]
Regression in https://github.com/grafana/grafana/pull/17731/files#diff-acbf79cc238ab2eaba351bba890ab607L281

**Comment by dprokop** [comment]
@ytturi thank you for reporting this. @gilkgit thanks for suggestion, we follow the exact path that you have suggested. This should be fixed now with #21140

**Comment by thockar** [comment]
In my opinion, using 'XSS Javascript in Panel link URL' is a very nice feature - not a bug!
I use it very extensively in my panels to confirm actions, display action results, show popups and advanced information ... and much more.

example:
....
"linkUrl": "javascript:newwin=window.open('$actiondash?orgId=1&var-action=set_sample_good&var-action_value=$__cell',$actionsize); newwin.focus();"
....

After upgrading to the latest 7.1 version, not a single one of my panels is working anymore. For now I stuck on 6.3.7.

If 'disable_sanitize_html = true' is set - this should IMHO work. How ever, if anyone has security concerns, an additional configuration parameter like 'enable_XSS_JavaScript_in_URL = false' (false is default)
can be used to make this feature working again.

**Comment by Ch4nKyy** [comment]
I second this. I want to spawn popups by clicking on data links in tables and this would be the easiest way I think.

**Comment by BarryThrill** [comment]
Has anyone figured out if its still possible to use XSS scripts in grafana 7.5.6?

**Comment by thockar** [comment]
upgrade grafana and run

sed -i s/\(javascript\|data\)/\(xjavascript\|data\)/g /usr/share/grafana/public/build/vendors*.js

The browsers javascript engine will no longer find and replace the "javascript:" protocol tag in the link.
If it does not work, refresh the browser to reload all java scripts.

**Comment by BarryThrill** [comment]
> sed -i s/(javascript|data)/(xjavascript|data)/g /usr/share/grafana/public/build/vendors*.js

Hi! Im debian 10 user and tried to run that syntax but unfortunately this gives me an syntax error:  bash: syntax error near unexpected token `('

**Comment by thockar** [comment]
escape the regex (the backslashes were removed in my post)
``sed -i s/\\(javascript\\|data\\)/\\(xjavascript\\|data\\)/g /usr/share/grafana/public/build/vendors*.js

**Comment by BarryThrill** [comment]
> escape the regex (the backslashes were removed in my post)
> ``sed -i s/\(javascript\|data\)/\(xjavascript\|data\)/g /usr/share/grafana/public/build/vendors*.js

unfortunately that didn't work for me. It did apply the `sed` but after restarting grafana and trying to run:

```
SELECT
  id,
  initcap(filter_type) as "Type",
  keyword as "Keywords",
  '<a href="javascript:DeleteKeywords(2,' || id || ',''popup'',''refresh'')"><img src="public/img/as/trashcan.png" height=15 style="display: block; margin: 0 auto; margin-top: 3px;"/></a>' as trash
FROM keywords
WHERE
1=1
ORDER BY id desc
```

nothing happens at click on javascript:DeleteKeyWords. By nothing I mean that no triggers are being done when we click ont he img which should trigger the javascript.

**Comment by thockar** [comment]
simply check /usr/share/grafana/public/build/vendors*.js
all occurrences of 

(javascript|data)

should be changed to 

(xjavascript|data)

use the dev tools of the browser to check that the javascript is the right one and your links are right (meens are not changed)

useless to say, always have a backup of the original javascipt vendors*.js!
