### ISSUE TITLE
dashboard refresh does not update alert history

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#20988]
Grafana v6.5.1 (1763a0f)

When i have a panel open with alert history for a while, new alert transitions don't appear. Even not after hitting "refresh".
The only way to see the updated history is to close and re-open it.

**Comment by torkelo** [comment]
This view has no refresh feature, only fetches state history when you open it. Need to close and open it again for it to refresh :(

**Comment by mojitaleghani** [comment]
Hi,
The same problem with Grafana v8.0.3. the alert panel will not refresh or work properly after an alert triggered.
I have to reload the page to see the refreshed alert panel.
worth to mention that even on Firefox or Chrome are the same.

**Comment by mojitaleghani** [comment]
Are there any update to solve this issue?
