### ISSUE TITLE
Some Feature Requests

### ISSUE THREAD

**Issue by whisk3y** [grafana/grafana#2099]
I have been using grafana for some time now, and I absolutely love it.  We host over 950 websites and while we are mainly tracking system metrics I am slowly starting to get site metrics into grafana. However, with hosting 950 sites that is also 950 site owners that want to know how there sites are performing. Are there any plans to incorporate generating reports off of dashboards? I have had quite a few instances lately when this would have been extremely helpful and had to resort back to Nagios to generate them. I know I can export PNG's of the panels, but something that aggregates all of that for me may be helpful, as I never have the time to actually sit and compile all the information. I want to get rid of Nagios all together, but there are still a few things that I use I can't find replacements for in the open source market. 

Another thought I had is it would be nice to have something similar to the Nagios Capacity planning. Does someone know how to do this with grafana already?

**Comment by torkelo** [comment]
You can use the api to generate PNGs for panels and from those images generate a web page or PDF
