### ISSUE TITLE
Grafana / Explore didn't update URL in location bar after I run new query

### ISSUE THREAD

**Issue by pstibrany** [grafana/grafana#20992]
**What happened**:
I have used Explorer tab. I've entered wrong query to the field, and got error.

After that, I've fixed the query (replaced ~ with !). Query now worked, but URL in the browser didn't change. When I copied URL and pasted it to slack, opening the URL loaded with the wrong query (still with "~").

<img width="1136" alt="Screenshot 2019-12-10 at 11 13 47" src="https://user-images.githubusercontent.com/895919/70521151-06407a80-1b3f-11ea-80c7-29fc32f4f935.png">

URL: https://admin-ops-tools1.grafana.net/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki-ops%22,%7B%22expr%22:%22%7Bjob%3D!%5C%22loki-prod%2F.*%5C%22%7D%20%7C%3D%20%5C%22339cc5ef64b8a0d8%5C%22%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

<img width="1136" alt="Screenshot 2019-12-10 at 11 15 08" src="https://user-images.githubusercontent.com/895919/70521226-24a67600-1b3f-11ea-8ec4-91b9bb511695.png">

URL is still the same:
https://admin-ops-tools1.grafana.net/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki-ops%22,%7B%22expr%22:%22%7Bjob%3D!%5C%22loki-prod%2F.*%5C%22%7D%20%7C%3D%20%5C%22339cc5ef64b8a0d8%5C%22%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**What you expected to happen**:

I expected URL in the browser location bar to be updated with new query, which can be shared with team members.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.6.0-pre (0c89b93ce0)
- Data source type & version: Loki 1.2.0
- OS Grafana is installed on: Linux, I guess
- User OS & Browser: macOS Catalina, Safari 13.0.3
- Grafana plugins:
- Others:

@davkal @gouthamve

**Comment by aocenas** [comment]
@pstibrany this should be fixed on master at this moment. Going to close it but please reopen if you encounter this again.
