### ISSUE TITLE
Docs: Data Sources does not open the side menu section

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#21007]
**What happened**: Opened a link and it did not expand the side menu as expected.

**What you expected to happen**: Side menu should expand.

**How to reproduce it (as minimally and precisely as possible)**:

1. In a browser, navigate here: https://grafana.com/docs/grafana/latest/features/datasources/
2. Observe the lack of expansion in the side menu.

**Anything else we need to know?**: This is more than a single-topic issue, I have not done a survey to see how many other _index topics contain content.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others: @robbymilo

**Comment by marefr** [comment]
@oddlittlebird not sure this can be fixed in Grafana repo. Maybe have to be moved to website.repo?

**Comment by robbymilo** [comment]
Needs to be in grafana/website.
