### ISSUE TITLE
Grafana shows 404 message frequently

### ISSUE THREAD

**Issue by raysurc** [grafana/grafana#2100]
Hello,

I am using Grafana 2.0.2-1 with InfluxDB 0.8.8-1 and I am seeing a "404 not found - nginx/1.4.7" message pop up very frequently. I have my refresh set to 15 minutes ago with refresh every 2s. It shows the right data at times, but then the graphs get cleared and show a red exclamation mark when I do receive the message, then goes back to normal. 

How can I fix/troubleshoot this?
![404 grafana](https://cloud.githubusercontent.com/assets/972847/7949483/05fae21c-0943-11e5-8003-0af984c85b88.jpg)

**Comment by torkelo** [comment]
what session store do you use? file based? There is a bug in that file bases session store that could be the cause (yet to find the and fix the bug), switching to mysql or postgress session store can help. 

https://github.com/grafana/grafana/issues/2100
