### ISSUE TITLE
Website: Need play.grafana.com redirect

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#21013]
**What happened**: I typed http://play.grafana.com/ into my web browser address and got a "This site can't be reached" message.

**What you expected to happen**: I expected to end up at the Grafana playground (play.grafana.org)

**How to reproduce it (as minimally and precisely as possible)**: Go to play.grafana.com.

**Anything else we need to know?**: 

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Is online now, maybe a very temporary issue? 

#grafana-ops channel great for stuff like this

**Comment by oddlittlebird** [comment]
Nope. Still a problem at this time. I also mentioned it in #grafana-ops. 
![image](https://user-images.githubusercontent.com/52059945/70631516-1d847400-1be2-11ea-8a39-b8438f6d8377.png)

**Comment by torkelo** [comment]
Looks like a flaky DNS issue from west cost / new york

![image](https://user-images.githubusercontent.com/10999/70632959-05d3dc80-1c30-11ea-9633-0a4d97be7a81.png)

**Comment by DanCech** [comment]
There was no record for play.grafana.com, I'm adding it now.

**Comment by DanCech** [comment]
Redirect is now operational.
