### ISSUE TITLE
AWS CloudWatch datasource - AWS/Athena metrics

### ISSUE THREAD

**Issue by YakobovLior** [grafana/grafana#21016]
Hello,
I would like to have the ability to create dashboards with data related to Athena from AWS CloudWatch.
![image](https://user-images.githubusercontent.com/33580144/70601340-811a9b80-1bfa-11ea-98e5-d9f23fc6676a.png)

This is needed in order to monitor the usage of Athena as the metrics give data of which user queries when, amount of queries and data scanned per user and more useful information.

Thanks,
Lior

**Comment by marefr** [comment]
@YakobovLior Are you referring to https://docs.aws.amazon.com/athena/latest/ug/query-metrics-viewing.html?

**Comment by YakobovLior** [comment]
Hey @marefr,
this is exactly what I need, when you enable CloudWatch metrics for Athena it writes to CloudWatch and you can monitor which user (work group) queries Athena and get more usage statistics.

Thanks,
Lior

**Comment by marefr** [comment]
@YakobovLior thanks. As a workaround think you can input custom metrics and dimension in the query editor as a workaround for now.

For anyone interested in contributing this is the file that needs update of metric and dimensions: https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go

**Comment by YakobovLior** [comment]
Hey @marefr,
can you explain again the workaround? I didn't fully understand.

Thank you,
Lior

**Comment by marefr** [comment]
@YakobovLior  In Grafana/CloudWatch datasource query editor and in the namespace drop down you can insert custom namespace like "AWS/Athena" and press enter. Same approach should work for metric name and dimension drop down.

**Comment by YakobovLior** [comment]
Hey @marefr,
I followed your instructions and it works fine,
Thank you,
Lior

**Comment by davidnewhall** [comment]
Relates to #22081 and #22215
