### ISSUE TITLE
Docs feedback: /auth/google.md clarify allow_signup

### ISSUE THREAD

**Issue by Freyert** [grafana/grafana#21026]
In general the documentation needs to clearly explain each configuration parameter as the main body of configuration documentation does.

This setting is particularly confusing as there is `user.allow_signup` which allows anyone to sign up.

I'm assuming I can also set `auth.google.allow_signup` to only allow users within my allowed SSO domains to sign up automatically? 

Similar Issues:
 #18207

**Comment by Freyert** [comment]
I imagine it is allowed its own as it is in the code

https://github.com/grafana/grafana/blob/master/pkg/login/social/google_oauth.go#L13-L19

**Comment by marefr** [comment]
@oddlittlebird FYI

**Comment by marefr** [comment]
Since you can have multiple OAuth providers configured you can use this setting for each provider.
