### ISSUE TITLE
Option to Skip Provisioning during server startup

### ISSUE THREAD

**Issue by vijayakumarbathini** [grafana/grafana#21024]
**What would you like to be added**:
Grafana should provide an option to enable or disable provisioning during server startup. 

**Why is this needed**:
We are managing grafana orgs and dashboards through git hub source code and using provisioning functionality. The same image is used in multiple environments and provisioning of dashboards and datasources is happening automatically on server start up. Which may not required in some environments.

Regards
Vijaya Kumar

**Comment by marefr** [comment]
Image you say, docker image? Then you should be able to override the provisioning files when running container?

**Comment by vijayakumarbathini** [comment]
Yes we are using docker image. So changing the provisioning path is the only option available.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
