### ISSUE TITLE
Loki: Label selector does not update when timepicker changed

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#21030]
The Loki label selector that's next to the query field is initialized with a picker range and only loads labels in that range. When a user changes the timepicker, the label selector might not show the labels that the user expects and knows should be there.

**Comment by aocenas** [comment]
Seems like this works correctly in Loki and we do refresh the labels and values with the correct time range when opening the selector. In prometheus though we do not refresh it so there this can be a problem.

**Comment by aocenas** [comment]
Ok scratch the previous comment, seem like prometheus values API does not take a time range so there isn't need to refresh it after timerange change.
