### ISSUE TITLE
Broken link on Cloudwatch page on grafana.com

### ISSUE THREAD

**Issue by mccollam** [grafana/grafana#21034]
https://grafana.com/grafana/plugins/cloudwatch has a link to 
http://docs.grafana.org/datasources/cloudwatch/ which returns a 404.  I believe this should point to https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/ instead.

**Comment by marefr** [comment]
Update to https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/ needed here https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/README.md.

One thing remain though and that is how we update core plugins on grafana.com. @DanCech can you give some pointers?

**Comment by DanCech** [comment]
There is a dedicated API call to update them, though it looks like the plugin.json and README.md files for the plugins could use some work.

**Comment by marefr** [comment]
@DanCech are you referring to only CloudWatch or other data sources in core grafana? What kind of changes? I know there are a couple of core data sources not published on grafana.com, like Loki and mssql. Also azure monitor is published as a plugin, but have been in core for quite a while.

**Comment by sunker** [comment]
Not possible to reproduce
