### ISSUE TITLE
cloudwatch multivalue variable dimension search does not match on multiple values of a dimension

### ISSUE THREAD

**Issue by rgarcia** [grafana/grafana#21036]
**What happened**:

I have a multi-value variable "$envapp" that corresponds to a AWS Lambda dimension `FunctionName`. I'd like to create a graph of the `Invocations` metric for all values of this variable. I create a dimension with `FunctionName` `=` `$envapp`.

The cloudwatch search expression generated has a single search term on `FunctionName` that lists out values for the variable:

`REMOVE_EMPTY(SEARCH('Namespace="AWS/Lambda" MetricName="Invocations" "FunctionName"="production--kinesis-notifications-lambda-consumer,production--kinesis-cil-event-logs-consumer"', 'Sum', 60))`

This search fails to match any value for `FunctionName` and no metric data is returned.

Here's a screenshot of the behavior:
![image](https://user-images.githubusercontent.com/72655/70636133-05711c80-1c03-11ea-9ead-d6d9a709b67d.png)

**What you expected to happen**:

I'd expect the search expression to `OR` across the values of the variable, e.g.

`REMOVE_EMPTY(SEARCH('Namespace="AWS/Lambda" MetricName="Invocations" "FunctionName"="production--kinesis-cil-event-logs-consumer" OR "FunctionName"="production--kinesis-notifications-lambda-consumer"', 'Sum', 60))`

This would correctly find a metric for each value of the dimension.

**How to reproduce it (as minimally and precisely as possible)**:

The description above describes a repro.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: cloudwatch
- OS Grafana is installed on: hosted grafana
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for reporting this @rgarcia. Can you please post you query? QueryInspector -> Copy to clipboard

**Comment by rgarcia** [comment]
Huh, now that I try this again, it appears to work as expected on 6.5.1 (1763a0f). Sorry for the noise.

**Comment by owenmorgan** [comment]
i'm seeing this same issue in 7.03

**Comment by justinTM** [comment]
@marefr @sunker We are having this issue still as well; multi-value dropdown variables for Dimension values are always using `AND`, but should be using `OR` (or at least the option to use `OR`). Any ideas?

**Comment by sunker** [comment]
Can you elaborate a bit on this one?

Multi-valued dimension variables are indeed `AND`ed together, see [code here](https://github.com/grafana/grafana/blob/34f6873d2daac67cd9c909cc47e277f837106e31/pkg/tsdb/cloudwatch/metric_data_query_builder.go#L83). When testing this locally, it works as expected for me.
