### ISSUE TITLE
Support for external ID in the CloudWatch assume role

### ISSUE THREAD

**Issue by jangaraj** [grafana/grafana#21039]
**What would you like to be added**:
Grafana CloudWatch datasource is able to assume role. But there is also optional `External ID`, which can be used. Doc: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html. External ID should be optional configuration option, when `Auth Provider: ARN` is selected:
![image](https://user-images.githubusercontent.com/1182932/70637772-12f4c980-1c38-11ea-9272-f51c4d4bb38e.png)

**Why is this needed**:
Additional Role security.

**Comment by san-san** [comment]
This would be a nice feature to have

**Comment by Dhananjay-Ghongane** [comment]
Yes, this is nice feature. 
This will increase the security of role by requiring an optional external identifier, which prevents "confused deputy" attacks.
