### ISSUE TITLE
Grafana not rendering Annotation Tags with a Loki Datasource

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#21041]
**What happened**:
I created a dashboard using a Loki query for annotations.  The dashboard can be found here: https://github.com/grafana/loki/blob/master/production/loki-mixin/dashboard-loki-operational.libsonnet
When mousing over the annotation tooltip the tooltip rendered but there were no tags.

![image](https://user-images.githubusercontent.com/2272392/70642969-30ad3900-1c0e-11ea-8464-fae2189b3149.png)

**What you expected to happen**:
I expected the Loki labels to be used as tags as suggested by documentation:
https://grafana.com/docs/grafana/latest/features/datasources/loki/#annotations

**How to reproduce it (as minimally and precisely as possible)**:
- Create a dashboard with one empty graph
- Add a Loki annotation.  Write a query that selects something.
- Note that the annotations are correctly showing, but there are no labels.

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: v6.6.0-pre (75923c43d1)
- Data source type & version:  Loki/Prometheus
- OS Grafana is installed on: Linux/Kubernetes
- User OS & Browser: Ubuntu 18.04/Linux
- Grafana plugins: None

cc @davkal

**Comment by Estrax** [comment]
@joe-elliott is it still a valid issue? seems to be working now for me, but maybe I miss something there.

**Comment by joe-elliott** [comment]
I'm still seeing this issue on the dashboard mentioned above in `v6.6.0-pre (b8b618241e)`

**Comment by Estrax** [comment]
Spent some time trying to replicate that, looks like it works properly on my end. Gonna ping you to do a debugging session together on Tuesday.

**Comment by Estrax** [comment]
Annotation tags seem to be working properly with Loki with the current master (5afcf79c59d3756e643d6c8974508165d90c0845). Closing the issue now. Please reopen if it still doesn't work properly.

**Comment by joe-elliott** [comment]
@Estrax 
I'm still seeing the issue in Grafana v6.7.0-pre (2283ceec09).  I would be glad to sit together and review the details of what we're seeing.  It's quite possible I'm misunderstanding this feature.

**Comment by Estrax** [comment]
@joe-elliott sorry, missed the notification on the comment. Let's sync up to review it. Please ping me on slack when you have some time to do that.

**Comment by Estrax** [comment]
Checked it again - annotation tags seem to be displaying properly with Loki with the current master (3d17d63891c48226e7d18c064c7738373080687f). Closing it now, please reopen if it still doesn't work properly.

**Comment by Estrax** [comment]
Reopening after talking with Joe on slack. After another short investigation I was unable to get any annotations to display tags in ops-tools, no matter what datasource I used - even when trying to annotate things without any dashboard variables. While running exactly the same version of Grafana locally (either on the same computer or on a home lab cluster), it works properly and render tags. My assumption is that when backend tries to fetch tags, it gets an empty response.
cc @davkal @aocenas

**Comment by Estrax** [comment]
Looks like it's not a problem with data fetching, but more of an issue with deduplication. Investigating now.
