### ISSUE TITLE
Function name no longer showing 

### ISSUE THREAD

**Issue by tmroberts-tableau** [grafana/grafana#21043]
I notice that now, when you add a function to a metric (i.e. movingAverage), the name of the function is no longer showing and there is no longer a way to remove the function either.  See attached screen shots.
![2019-12-11_11-30-39](https://user-images.githubusercontent.com/36457170/70653684-cf836680-1c09-11ea-9725-0c385fee28bb.jpeg)
![2019-12-11_11-30-52](https://user-images.githubusercontent.com/36457170/70653686-cf836680-1c09-11ea-8af5-b975579ea980.jpeg)
![2019-12-11_11-31-00](https://user-images.githubusercontent.com/36457170/70653687-cf836680-1c09-11ea-8f5d-b2ac772b64f5.jpeg)
![2019-12-11_11-31-09](https://user-images.githubusercontent.com/36457170/70653688-cf836680-1c09-11ea-9bb6-19c9f37ce665.jpeg)

**Comment by ryantxu** [comment]
what datasource and what version are you running?

**Comment by tmroberts-tableau** [comment]
v6.5.2 and the Zabbix datasource.  This only started after I ran an update in the last 48 hours or so on Grafana.

**Comment by marefr** [comment]
@tmroberts-tableau please include exact Grafana version.

**Comment by tmroberts-tableau** [comment]
its in the previous comment.  6.5.2

**Comment by marefr** [comment]
Would suggest check for same issue here or open a new one: https://github.com/alexanderzobnin/grafana-zabbix
