### ISSUE TITLE
API: Add api/tsdb/query to HTTP API documentation

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#21046]
**What would you like to be added**:
Document api/tsdb/query HTTP API resource.

**Why is this needed**:
HTTP API documentation should fully cover all resources. 

**Additional info:**
- /api/tsdb/query only supports POST verb, see [code](https://github.com/grafana/grafana/blob/master/pkg/api/api.go#L329). 
- This can be used to query a data source in the Grafana backend, i.e. a data source that have a backend/server side implementation, Most of the builtin data sources in Grafana have backend implementations.  
- Suggests for now adding it to the bottom of this [file](https://github.com/grafana/grafana/blob/master/docs/sources/http_api/data_source.md) ([docs page](https://grafana.com/docs/grafana/latest/http_api/data_source/)) instead of introducing a new page for the tsdb api.
- `from`, `to`, `queries` are required in the request.
  - `from` and `to` should be either absolute in epoch timestamps in milliseconds or relative using [Grafana time units](https://grafana.com/docs/grafana/latest/reference/timerange/#time-units), e.g.`now-1h`.
- Each `query` in request must have a `datasourceId` identifying a data source to be queried. 
  - `refId` specifies an identifier of the query. Is optional and default to `"A".
  - `maxDataPoints` species maximum amount of data points that dashboard panel can render. Is optional and default to `100`.
  - `intervalMs` specifies the time interval in milliseconds of time series. Is optional and defaults to `1000`. 
  - besides these properties each data source have their own specific properties, see below for MySQL example.

**Example MySQL time series query request:**
```http
POST /api/tsdb/query HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "from": "1420066800000",
  "to": "1575845999999",
  "queries": [
    {
      "refId": "A",
      "intervalMs": 86400000,
      "maxDataPoints": 1092,
      "datasourceId": 86,
      "rawSql": "SELECT\n  time,\n  sum(opened) AS \"Opened\",\n  sum(closed) AS \"Closed\"\nFROM\n  issues_activity\nWHERE\n  $__unixEpochFilter(time) AND\n  period = 'm' AND\n  repo IN('grafana/grafana') AND\n  opened_by IN('Contributor','Grafana Labs')\nGROUP BY 1\nORDER BY 1\n",
      "format": "time_series"
    }
  ]
}
```

**Example MySQL time series query response:**
```http
HTTP/1.1 200
Content-Type: application/json

{
  "results": {
    "A": {
      "refId": "A",
      "meta": {
        "rowCount": 0,
        "sql": "SELECT\n  time,\n  sum(opened) AS \"Opened\",\n  sum(closed) AS \"Closed\"\nFROM\n  issues_activity\nWHERE\n  time >= 1420066800 AND time <= 1575845999 AND\n  period = 'm' AND\n  repo IN('grafana/grafana') AND\n  opened_by IN('Contributor','Grafana Labs')\nGROUP BY 1\nORDER BY 1\n"
      },
      "series": [
        {
          "name": "Opened",
          "points": [
            [
              109,
              1420070400000
            ],
            [
              122,
              1422748800000
            ]
          ]
        },
        {
          "name": "Closed",
          "points": [
            [
              89,
              1420070400000
            ]
          ]
        }
      ]
    }
  }
}
```

**Example MySQL table query request:**
```http
POST /api/tsdb/query HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "from": "1420066800000",
  "to": "1575845999999",
  "queries": [
    {
      "refId": "A",
      "intervalMs": 86400000,
      "maxDataPoints": 546,
      "datasourceId": 86,
      "rawSql": "SELECT 1 as valueOne, 2 as valueTwo",
      "format": "table"
    }
  ]
}
```

**Example MySQL table query response:**
```http
HTTP/1.1 200
Content-Type: application/json

{
  "results": {
    "A": {
      "refId": "A",
      "meta": {
        "rowCount": 1,
        "sql": "SELECT 1 as valueOne, 2 as valueTwo"
      },
      "tables": [
        {
          "columns": [
            {
              "text": "valueOne"
            },
            {
              "text": "valueTwo"
            }
          ],
          "rows": [
            [
              1,
              2
            ]
          ]
        }
      ]
    }
  }
}
```

**Comment by ffeldmann** [comment]
Upvote for this post from @marefr!

**Comment by achatterjee-grafana** [comment]
Opened PR: https://github.com/grafana/grafana/pull/31337

**Comment by achatterjee-grafana** [comment]
Closing this issue. Documentation to be found at https://grafana.com/docs/grafana/latest/http_api/data_source/.

**Comment by ffeldmann** [comment]
Great! Thank you! :)
