### ISSUE TITLE
Add conditional notification

### ISSUE THREAD

**Issue by apple77y** [grafana/grafana#21054]
**What would you like to be added**:
It would be much better if it could send to different notification channel with different rule at same panel.
Below is the example of what I think.
RULE1: WHEN avg() OF query(A, 30s, now) IS ABOVE 1 `ALERT: A_CHANNEL`
RULE2: WHEN avg() OF query(A, 30s, now) IS ABOVE 2 `ALERT: B_CHANNEL`

**Why is this needed**:
We have managed different notification channels based on the each amount of data.
What we are doing now to solve this problem is to create multiple panels with same query, but different alert rule.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
