### ISSUE TITLE
Support updating template variable filters & refresh in custom React plugin code

### ISSUE THREAD

**Issue by efvhi** [grafana/grafana#21051]
**What would you like to be added**:
Something like below:

```
import { getDashboardSrv } from "@grafana/runtime";

getDashboardSrv().updateFilters({...});
getDashboardSrv().startRefresh();

```
**Why is this needed**:
When people developing their special panel, they want to change other panels'(influxdb data source) query like 'templating variables filters' doing.  This feature can provide developers power to control other panels' data  by their customize plugin panel  and more interactive, flexible. 

Appreciated !

**Comment by ryantxu** [comment]
you can change template variables currently by using `getLocationSrv().update( { ... } )` -- that should kick of a refresh as well.

Exposing dashboardSrv is a bit more complicated and we need to be careful about it -- in particular we should not expose the whole dashboard model since that will likely change.  Pull requests welcome!

**Comment by ryantxu** [comment]
@efvhi -- I'll go ahead and close this.  Feel free to open a PR with suggestions for how to expose `getDashboardSrv` safely

**Comment by efvhi** [comment]
> getLocationSrv().update( { ... } )

Thanks for your response! ryantxu ! I tried `getLocationSrv().update( { ... } )`,  But it only changes the URL, still need to reload the whole page or open a new tab to refresh other panels' data. acceptable but not perfect :(

**Comment by efvhi** [comment]
> @efvhi -- I'll go ahead and close this. Feel free to open a PR with suggestions for how to expose `getDashboardSrv` safely

Well, i will think about it. thanks.
