### ISSUE TITLE
how do you change the title

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2105]
I just installed new latest grafana and I see browser title grafana - home. I need to be able to change this. How?

**Comment by torkelo** [comment]
This is not possible currently

**Comment by changbl** [comment]
Is there any reason why it is impossible to change it?

**Comment by calvinboey** [comment]
You can manually change them in several .js files. First, do a search 
`find /usr/share/grafana/ -type f -exec grep -H 'Grafana -' {} \; | grep window_title_prefix`

You're find all the .js files that contain the following string:
`window_title_prefix:"Grafana - " `

Change them to whatever you like.

**Comment by changbl** [comment]
@calvinboey Thanks. I have tested it and this works for me. Grafana 2.6.0.

**Comment by karanp24** [comment]
Hi guys, need to know if it is now possible to change the title?  I am running grafana in docker. What changes I need to do?
