### ISSUE TITLE
Explore: "Show context" link missing for Loki logs in Explore

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#21067]
**What happened**:

The "Show context" link - for Loki logs in Explore - is not displayed anymore on mouse over the log entry.

**What you expected to happen**:

To display the "Show context" link on mouseover.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Grafana from `master` branch
2. Open the Explore
3. Run any Loki logs query to show at least 1 log
4. Mouse over the log: the "Show context" link is not displayed

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v6.6.0-pre (a187500c0e)`
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: OSX 0.13.6 & Chrome 78.0.3904.108
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment]
@ivanahuckova labeled and added this to your project for triage

**Comment by ivanahuckova** [comment]
Thanks @marefr!

**Comment by pracucci** [comment]
Closing because it was my fault. I didn't realize "Show context" is available only when you use filters. Sorry for the noise.
