### ISSUE TITLE
Local admin can't login when LDAP is configured before first admin login

### ISSUE THREAD

**Issue by joernott** [grafana/grafana#21068]
**What happened**:
I set up a grafana server using a configuration which works fine on another server. However, the admin user can't log in with the password specified in grafana.ini.

**What you expected to happen**:
The admin login should work despite grafana being configured to also use ldap.

**How to reproduce it (as minimally and precisely as possible)**:
Set up grafana using a local postgres database and the following configs:

**grafana.ini**
```
# This file is managed by Puppet, any changes will be overwritten

app_mode = production

[analytics]
check_for_updates = false
reporting_enabled = false

[auth.basic]
enabled = true

[auth.ldap]
config_file = /etc/grafana/ldap.toml
enabled = true

[database]
host = localhost
name = grafana
password = DonTPutPasswordsOnTheInternet
ssl_mode = disable
type = postgres
user = grafana

[paths]
data = /opt/schufa/grafana/data

[security]
admin_password = DonTPutPasswordsOnTheInternet
admin_user = admin
allow_embedding = true
disable_gravatar = true

[server]
domain = mon.local
enforce_domain = false
http_addr = 127.0.0.1
http_port = 3000
root_url = %(protocol)s://%(domain)s:/grafana
serve_from_subpath = true

[user]
login_hint = ldap username
password_hint = ldap password
```
**ldap.toml**
```
[[servers]]
bind_dn = "uid=authbinbduser,cn=redacted"
bind_password = "DonTPutPasswordsOnTheInternet"
host = "ldap1"
port = 636
search_base_dns = ["dc=sf-rz,dc=de"]
search_filter = "(uid=%s)"
ssl_skip_verify = true
use_ssl = true

[servers.attributes]
email = "email"
member_of = "isMemberOf"
name = "givenName"
surname = "sn"
username = "uid"

[[servers.group_mappings]]
grafana_admin = true
group_dn = "cn=admins,cn=redacted"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
```
(and yes, instead of memberOf we use isMemberOf which handles recursive group mappings)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.3.2 (commit: 4832460)
- Data source type & version: none yet
- OS Grafana is installed on: RHEL 7.4
- User OS & Browser: Google Chrome 78.0.3904.108 
- Grafana plugins: none
- Others:

**Comment by joernott** [comment]
Problem still exists in Grafana v6.5.2 (742d165).

I've found a workaround for it though: Logging in with an ldap user having admin privileges and changing the password of the local admin user in the web interface to the one in the config allows for admin logins afterwards.

**Comment by marefr** [comment]
Maybe some special character in admin password causing problem? Can you try with the default admin password?

Please enable [debug logging](https://grafana.com/docs/grafana/latest/installation/configuration/#level) and include Grafana server log (remove sensitive info, if any) that shows when Grafana starts up for the first time and then you try to login with admin user before logging in with LDAP user..

Thanks

**Comment by joernott** [comment]
I will try to repeat the setup on a test vm this week. We have a fairly simple default password on  our dev VM (no special characters, only lower case letters and numbers, limited to 8 chars) but we encountered the problem there as well. I will put the default admin password into the grafana config file when we generate it with puppet and try what happens.

**Comment by torkelo** [comment]
Closing this, unable to replicate and no other reports. If you have more info / more users encounter this we will re-open!

**Comment by daxroc** [comment]
There does seem to be a condition where the password when updated in ENV is not updated in the database. 
To resolve this you'll need to use 
```
grafana-cli --config $GF_PATHS_CONFIG admin reset-admin-password $GF_SECURITY_ADMIN_PASSWORD
```
