### ISSUE TITLE
grafana login too slow when open uri(public/build/vendors~app.0d52b7637e43802b8d00.js)

### ISSUE THREAD

**Issue by geektcp** [grafana/grafana#21074]
When I open grafana with http://x.x.x.x:3000
I found it too slow because of the js file  vendors~app.0d52b7637e43802b8d00.js is too slow .
check the chrome network bar:
app.0d52b7637e43802b8d00.js | 200 | script | login | 1.5 MB | 4.17 s

the url is : http://x.x.x.x:3000/public/build/vendors~app.0d52b7637e43802b8d00.js

but this file(vendors~app.0d52b7637e43802b8d00.js) is too long , 
I cannot know where is the slow http request url !

I think the reason is this file is too big:
$ du -sh grafana/public/build/vendors\~app.0d52b7637e43802b8d00.js
2.7M	vendors~app.0d52b7637e43802b8d00.js

--------------------------------

login | 200 | document |   | 37.4 KB | 176 ms
-- | -- | -- | -- | -- | --
RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2 | 200 | font | login | 14.6 KB | 126 ms
grafana.light.0d52b7637e43802b8d00.css | 200 | stylesheet | login | 339 KB | 574 ms
runtime.0d52b7637e43802b8d00.js | 200 | script | login | 3.3 KB | 45 ms
angular~app.0d52b7637e43802b8d00.js | 200 | script | login | 173 KB | 691 ms
app.0d52b7637e43802b8d00.js | 200 | script | login | 1.5 MB | 4.17 s
moment~app.0d52b7637e43802b8d00.js | 200 | script | login | 260 KB | 549 ms
vendors~app.0d52b7637e43802b8d00.js | 200 | script | login | (disk cache) | 77 ms
data:image/svg+xml,… | 200 | svg+xml | login | (memory cache) | 0 ms
CWB0XYA8bzo0kSThX0UTuA.woff2 | 200 | font | login | 14.5 KB | 139 ms
heatmap_bg_test.svg | 200 | svg+xml | ChangePassword.tsx:98 | 266 KB | 2.40 s
fontawesome-webfont.woff2?v=4.7.0 | 200 | font | ChangePassword.tsx:98 | 75.6 KB | 946 ms
grafana_typelogo.svg | 200 | svg+xml | ChangePassword.tsx:98 | 2.2 KB | 44 ms
grafana_icon.svg | 200 | svg+xml | react-dom.production.min.js:55 | 55.8 KB | 555 ms
icn-dashboard-tiny.svg | 200 | svg+xml | jquery.js:6164 | 2.4 KB | 598 ms

**Comment by marefr** [comment]
Please enable [gzip compression](https://grafana.com/docs/grafana/latest/installation/configuration/#enable-gzip).

**Comment by yalpay** [comment]
I have the same problem. I enabled gzip and it significantly improved the performance, vendors~app.0d52b7637e43802b8d00.js file size reduced from 15.9 mb to 3.4 mb and page load from 70s to 5 6 seconds. However, there should be something else, and I am searching on it!

**Comment by dgonzalezruiz** [comment]
I believe that, since this _seems_ to be a static file, grafana could perform better by allowing browsers to cache it.
I have the impression that this has to do with https://github.com/grafana/grafana/issues/16845 , since it's being served with `cache-control: no-cache` (maybe the no-caching policy is too restrictive and should allow for this kind of exceptions?)
