### ISSUE TITLE
prometheus template variable support __text __value, similar to mysql

### ISSUE THREAD

**Issue by zzyongx** [grafana/grafana#21076]
**What would you like to be added**:
template variable has diplay text and actual value, similar to mysql's text/value

**Why is this needed**:
we use ip when collecting data, but use domain when query metric grapha. we have another metric, which preserves the mapping between domain and ip.

we use ip to collect data because ip is more stable than domain. we may change domain.

**Possible solutions**
label_values(metric, label) add another param label_values(metric, text, value)

**Comment by evandhoffman** [comment]
👍

**Comment by evandhoffman** [comment]
node_exporter includes metrics from lm_sensors/hwmon that have the name of the chip in a separate metric, e.g. 
```
node_hwmon_chip_names{chip="0000:d7:00_0_0000:d8:00_0",chip_name="enp216s0f0np0"} 1
```
The actual metrics reference the chip ID but I'd like to be able to put the chip_name in the dropdown, but it appears this isn't possible with a prometheus data source.

**Comment by gboor** [comment]
I also just ran into this. This is possible with __value and __text, but mapping that in a prometheus query is not.

I think the easiest way to do this is to have another function like label_values that returns 2 label values; 1 for value, 1 for text.
