### ISSUE TITLE
Request to save dashboard in elasticsearch instead of influxdb

### ISSUE THREAD

**Issue by gpestana** [grafana/grafana#2107]
I've been trying to store my dashboards in influxdb and have edited the config.js accordingly: https://gist.github.com/gpestana/4993352bb573be74e92b

Though, for some reason, when I try to save the dashboard, I get an alert saying it was not possible. The browser's console prompts the following error:

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://xxx.xxx.xxx.xxx:9200/grafana-dash/dashboard/falcomon. (Reason: CORS request failed)."

I don't even have anything listening the 9200 port and elasticsearch is certainly not running to answer this request. 

Is there anything wrong in my configs or for some reason grafana should be making request to influxdb and, instead, it keeps trying to store the dashboard data in elasticsearch?

**Comment by torkelo** [comment]
The config looks ok, what version are you using?  In Grafana 2.0 and forward all dashboards, users, settings, etc are stored in a SQL database (default an embedded db, but mysql and postgres is also supported).

**Comment by gpestana** [comment]
Yep, indeed. Sorry, my bad! I installed a really early version of grafana and didn't realize. Thank you @torkelo

**Comment by luisdavim** [comment]
why drop the support to store the dashboards in elasticsearch? For me this is a step back :(

**Comment by torkelo** [comment]
@luisdavim ?? This was done more than a year ago when Grafana introduced it's own backend. Elasticsearch is not a good general purpose database, so it's not appropriate to use it to store users, dashboards, etc. 

Grafana can use an embedded SQL database to store dashboards, or MySQL or Postgres. There is a migration tool to import dashboards
