### ISSUE TITLE
please consider default fill=0

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#21075]
**What would you like to be added**:

I propose that the default `Fill` setting for graphs to be 0.

I suspect the `Fill` default is 1 to make graphs look impressive somehow for Grafana PR, but it would be better if the feature is reserved to have some meaning.

**Why is this needed**:

If every new graph defaults to fill on, it's more difficult for the user to imagine using this visual cue to convey meaning.

For example, at [some humongous tech company], fill is used exclusively with stacked graphs.  When viewing a multiple-series graph, the user knows instantly whether the series are stacked or not.

**Comment by ryantxu** [comment]
I think the most likely path is to allow setting your own defaults for each panel type, or maybe a few options as defaults.

See #16576, or maybe #13888

Changing the global default to 0 is very unlikely since it is just as reasonable as 0, and would widely affect all existing setups.

**Comment by belm0** [comment]
> Changing the global default to 0 is very unlikely since [1 is just as reasonable]

0 is more reasonable, see point above

> and would widely affect all existing setups

I expect the change can be implemented in a way such that it only affects newly created panels.
