### ISSUE TITLE
customizable panel title bar

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#21078]
in graph panel titles we currently only show:
* title string configured on the panel (with possibly template variables expanded)
* information icon with popup that shows static markdown, configured on the panel.

I would like to expand on this, and allow for custom things to be shown, for example:

* number of series plotted
* any data field that came out from metrictank render metadata, such as wether data was rolled up or not (note, this is currently not exposed as a simple bool, and needs to be interpreted based on a few variables, but we can streamline this)
* wether or not the request was entirely handled by MT or needed help from graphite (sometimes metrictank proxies requests to graphite if it doesn't support all the requested processing). (we currently don't expose this as such, but a way to tell is whether there is a meta section at all)

Perhaps we could implement this with a templating language where people can add arbitrary things into the title

related #11700

**Comment by torkelo** [comment]
The main challenge is where is this configured? Not everyone might want this information (not even in the same instance / org or dashboard)

**Comment by hugohaggmark** [comment]
@Dieterbe is this the same as the meta tab (I remember Torkel talking about this, not sure what the name is) in the Panel Inspector added in Grafana 7.0?

**Comment by Dieterbe** [comment]
No. The request is to customize the title displayed in the bar at top of a panel. The whole point is to make certain bits of information directly accessible on different panels **without** having to navigate elsewhere. It's been a year, but I think the use case was that i have a dashboard load and want to know at a glance how well it performs / loads the data.

It could be displayed as a format string that gets expanded. E.g. something like this:
![template](https://user-images.githubusercontent.com/20774/99154076-c7536700-26b5-11eb-9b8b-3541cc2642c3.png)
with a certain set of variables that grafana could automatically expand.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
