### ISSUE TITLE
noUnusedLocals set to false in dev mode

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#21087]
**What would you like to be added**:

 Support plugin compilation with core grafana configs.

**Why is this needed**:

It is usual with new plugins development to use imports such as `import { config } from 'app/core/config';` but it is set true by default in node_modules/@grafana/toolkit/src/config/tsconfig.plugin.json and it generates some compilation errors. In React, use @ts-ignore or @ts-nocheck is not very well supported so it is a problem at all.

**Comment by torkelo** [comment]
why do import config but do not use it?

**Comment by gretamosa** [comment]
Sorry @torkelo, I created this issue thinking that I solved the problem but I was wrong. I am creating a new plugin using [https://github.com/grafana/simple-react-panel](simple react panel) but I've seen differences between piechart alpha panel and this template:

- PanelProps is imported from different places @grafana/ui or @grafana/data isn't it? Have they the same purpose?
- I haven't found a way to import (and compile) config class from 'app/core/config'. Maybe an alternative could be import some classes from @grafana/runtime?

Sorry again for the wrong title issue choice :(

Thanks!

**Comment by torkelo** [comment]
We do not provide config via any package yet, what do you need from config?

**Comment by gretamosa** [comment]
In this initial stage, for config.theme like piechart alpha panel. In my case is for adapting stylesheets dynamically to theme.

I do some research with @grafana/runtime and I think I can retrieve it with dashboardSrv. Is it the right way?

**Comment by dprokop** [comment]
@gretamosa you can retrieve the current theme by using `getTheme` function from @grafana/ui.

Just so you know we support Emotion (emotion.sh) by default so you can style your components using CSS-in-JS approach. See https://github.com/grafana/grafana/blob/master/contribute/style-guides/styling.md#styling-grafana and https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md for more details
