### ISSUE TITLE
Links cause 'General' config editor ('advanced' tab) of panels fail to load

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#21082]
**What happened**: For various types of panels including Singlestat and Table, the 'General' configuration editor ('advanced' tab in the URL) fails to load either when links are enabled in the description or when panel links are enabled, and instead shows a semi-verbose error massage from the Javascript code having the following contents. This also affects the display of the description message in a manner where the icon is present but the contents are empty when hovered on.
`An unexpected error happened`
`TypeError: e is undefined`

**What you expected to happen**: This has been observed when Grafana has been upgraded from 6.3.5 to 6.5.0, and the description message ought to be displayed upon hovering on the icon whether or not links are enabled, and the 'General' configuration editor ought to open without the unexpected error whether or not links are enabled.

**How to reproduce it (as minimally and precisely as possible)**: Create a panel in a dashboard, add its description in the 'General' configuration editor, and enable either panel links or links within the description text.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: v6.5.0 (commit: 24a5d2f) and above
- Data source type & version: PostgreSQL v11
- OS Grafana is installed on: Ubuntu 19.10 [also tested on Ubuntu 18.04]
- User OS & Browser: Ubuntu 19.10 & Mozilla Firefox 70.0.1 (64-bit)
- Grafana plugins: nil
- Others: nil

**Comment by marefr** [comment]
Can you please try 6.5.2, think this have been fixed

**Comment by anirudh-ramesh** [comment]
Hi, @marefr, this issue is present in Grafana v6.5.2 as well - I've mentioned v6.5.0 and above for this reason.

Let us please diagnose once again prior to closing this perhaps so that another user would not open a new issue in the future.

I have isolated the issue to the presence of the following in the panel JSON:
`  "links": [
    {
      "targetBlank": true,
      "title": "This is the title."
    }
  ],`

**Comment by marefr** [comment]
Reopened. Can you please include a dashboard json where this problem is reproducible for you? Thanks

**Comment by anirudh-ramesh** [comment]
Hi, @marefr, thanks for reopening the issue. I am adding a few screenshots of what I am observing.

This is what is displayed when hovering on the info icon on the top-left corner.
![Info Icon _ Observed](https://user-images.githubusercontent.com/8345813/70974953-f7be0a00-20ce-11ea-97e4-d277d513dd6e.png)

This is what shows up in the "general" page when I go to investigate what is wrong with the description of the panel.
![General Page _ Observed](https://user-images.githubusercontent.com/8345813/70975016-18865f80-20cf-11ea-9cfc-1aefe74fd2c3.png)

Finally, this is how the (inactive/incomplete) link looks in the panel JSON - this link was created in Grafana v6.3.5 and no impact was obseved on the description message at the time - and it remained a WIP.
![Panel JSON _ Observed](https://user-images.githubusercontent.com/8345813/70975072-381d8800-20cf-11ea-8844-49e7f7510314.png)

Then, I removed the link when I noticed that other panels' descriptions without links or with links correctly defined, worked as expected.
![Panel JSON _ Corrected](https://user-images.githubusercontent.com/8345813/70975285-a2cec380-20cf-11ea-84a3-618a34f92b54.png)

Immediately, the description text was restored.
![Info Icon _ Corrected](https://user-images.githubusercontent.com/8345813/70975320-b417d000-20cf-11ea-866d-58f6b25ce830.png)

And the "general" page was also working as expected.
![General Page _ Corrected](https://user-images.githubusercontent.com/8345813/70975345-c2fe8280-20cf-11ea-8b34-975683649967.png)

While not many users may be having this issue, we could perhaps resolve this by:

1. Error handling the `"targetBlank": true` condition.
2. Warning upgrades from 6.3.5 (or the last version not having this issue) to 6.5.2 via the upgrading instructions that the `"targetBlank": true` is inappropriate usage of links.

Thanks!

**Comment by anirudh-ramesh** [comment]
While having WIP links be perhaps just a potential issue for a small proportion of users, and those having this issue while upgrading be a tiny proportion, the reason I like to document and resolve this issue is that there is no way to get the description text corrected other than manually editing the panel JSON since the editor is not accessible due to the JavaScript error.

**Comment by marefr** [comment]
Just created a new dashboard with a panel having links with empty url. It works as expected: https://play.grafana.org/d/-uR4E5fWk/21082-panel-links-with-empty-url?orgId=1

Make sure you have `"links": [ { "targetBlank": true, "title": "This is the title.", "url": "" } ],`
