### ISSUE TITLE
gap on panel when new time series appears in a regex query panel

### ISSUE THREAD

**Issue by kureikain** [grafana/grafana#2108]
Hi,

We have a weird issue. We used regex something like `/production.version.*.counter/` to show all version count on a graph. When a new time series appear in system (when a new version is introduced), the graph get cut of right at the point the new time series appeared. 

Last 3 hours:

![screen shot 2015-06-03 at 6 44 33 pm](https://cloud.githubusercontent.com/assets/49754/7975203/a43a87d8-0a20-11e5-8612-a45014919940.png)

Last 1 hours:
![screen shot 2015-06-03 at 6 45 21 pm](https://cloud.githubusercontent.com/assets/49754/7975215/c39e3f3e-0a20-11e5-9092-d561b9a05b1d.png)

The blue and green line are from same time series. The green line should continue to show up in first graph. Its value is very consistent as you can see in 2 graphs. I cannot show the label because of privacy issue. 

If we limit time range so that the new time series appear before the time range starts, the graph looks fine

To illustrate it:

Let's say if we select timerange (T, T-3) (3 hours ago), and the new time series appear at (T-2). The graph will cut off at T-2. If we select time range (T, T-1)(1 hour ago), the graph looks fine without any gap.

We configured Null Point mode connected and Fill(0). 

Also, when we switch from Line to Bars, the issue gone which is weird. The bar chart work properly but line isn't

**Comment by kureikain** [comment]
More update, if we switch from line chart to bars chart, it works properly. Or if we use line chart, but turn off stack, it works properly. So the problem only happen with line charts in stack mode.

**Comment by torkelo** [comment]
dis you read the info about stacking in the query editor? (bellow your queries there is info section).also there is like 20 other issues reporting the same problem :(  

This is a problem related to InfluxDB , you have to use fill (0) for it to return values for missing  measurements. And stack rendering code requires there be values for each point, it won't stack null or missing values on top of each other.

**Comment by kureikain** [comment]
Hi, @torkelo 

Thanks a lot for response.

I read it before and did some search around. and that's why I set fill(0) :(. Even with fill(0) it still won't work.

```
We configured Null Point mode connected and Fill(0).
```
So what do I have to set now?

**Comment by torkelo** [comment]
Maybe check that it is not a Influxdb issue?
