### ISSUE TITLE
Create Temporary (Non-Database) Dashboard via API

### ISSUE THREAD

**Issue by OptrixAU** [grafana/grafana#21083]
**What would you like to be added**:

I'd like to be able to use an API to create a Grafana dashboard in a way very similar to the existing API. But in this case, I want the dashboard to be **temporary** (attached to the user session) and not added to the database permanently.

This means that they would not require administrative access to create. 

**Why is this needed**:

My data source application knows quite a bit about the timeseries data that I can't easily load dynamically in Grafana (for example, the mapping between integer values and strings). My system also holds thousands (or even tens of thousands) of different assets that might need their own Grafana dashboard.

Instead of flooding Grafana with thousands of individual dashboards and try to keep them in-sync with changes to the items on my side, I'd like to simply create them at runtime when the user asks to see them. This way they are always in-sync and functional, and I don't fill the dashboard lists with large volumes of garbage.

**Comment by marefr** [comment]
This request doesn't make sense from Grafana project point of view and seems very specific to your use case so will close it. Will consider reopen if more users shows interest in this.

**Comment by chrishyc** [comment]
i need temporary dashboard to view the graph, my alert application is feishu, which can not know the specific dashboard id
