### ISSUE TITLE
Interactive Grafana Panels

### ISSUE THREAD

**Issue by RuchaBapat** [grafana/grafana#21081]
Hello,

Currently, Grafana panels are not interactive. You need to choose value individually to see data for that value in different panels in a dashboard. 
This is really not user-friendly and confuses the user if a same value is not chosen in all panels.
It would be great to have panels interactive so that choosing/selecting/clicking one value in one panel would reflect the data change for that value in other panels

Thanks.

**Comment by marefr** [comment]
Have you considered using [template variables](https://grafana.com/docs/grafana/latest/reference/templating/#variables)?

**Comment by torkelo** [comment]
what do you mean by: "You need to choose value individually" ?

**Comment by torkelo** [comment]
You can see an example of a dynamic interactive dashboard here: https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1

docs: 
https://grafana.com/docs/grafana/latest/reference/templating/

If you have something else in mind please include details for how it would work, how are queries made dynamic, how would the filtering and interactions work etc

**Comment by roship** [comment]
Also need such feature.

The way I see it:
For example, when i click on a record in the one table then in another linked table the data is displayed with filtering on the selected record, or a graph is built for this selected record.
