### ISSUE TITLE
Dashboard: Now delay now- doesn't apply on dashboard load

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#21085]
**What happened**:
`Now delay now` doesn't work when loading dashboard.
It only work when time range is changed.

**What you expected to happen**:
`Now delay now` work when loading dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Set `Now delay now`, and reload dashboard.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
v6.6.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

/--- original issue ---/

**What would you like to be added**:
Support Live Data hiding what CloudWatch web console support.

![image](https://user-images.githubusercontent.com/224552/70796149-e4682180-1de4-11ea-9a75-af882cc49742.png)

**Why is this needed**:
I want to hide most recent data point which is not yet fully aggregated, because the value is incorrect, and sometimes cause confusion.

For example, CloudWatch return low `RequestCount` value, it cause confusion.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html

**Comment by marefr** [comment]
@mtanda Do you have any idea of how to implement this, is it in CloudWatch api?

**Comment by mtanda** [comment]
CloudWatch API doesn't support it. It is a UI feature.
I guess hiding most recent datapoint is enough for first target.

**Comment by marefr** [comment]
Guess this can be quite advanced if you need to understand how data is aggregated etc. If possible to do something simple we can maybe accept this, otherwise I'm afraid this is something CloudWatch should have support for in their API.

**Comment by mtanda** [comment]
Unfortunately, CloudWatch API doesn't support it and AWS engineer don't have plan.
Same problem is happened on other datasources, if the query aggregate datapoints in same time window.

Prometheus also has the same problem, most recent `sum(rate(http_requests_total[1m]))` result could be wrong until all scraping are done for the most recent time window.
Fixing Prometheus case is difficult, so I don't intend to fix the Prometheus case.

I think adding input box to specify `hide last N minutes datapoints` is good solution for user and Grafana core team.
It is easy to implement, and user can adjust the parameter.

**Comment by mtanda** [comment]
Sorry I didn't notice.
Grafana already has similar feature.

It only work when user change time range. I want to know the reason.
https://github.com/grafana/grafana/blob/v6.6.0/public/app/features/dashboard/components/DashNav/DashNavTimeControls.tsx#L77-L90

![image](https://user-images.githubusercontent.com/224552/73361382-33f8a300-42e8-11ea-8ae0-7944dd31207e.png)

**Comment by marefr** [comment]
@mtanda would suggest you to open a bug report of Now delay now

**Comment by mtanda** [comment]
@marefr I updated issue description, please tag this issue as bug report :-)

**Comment by marefr** [comment]
Was able to reproduce given an existing dashboard showing last 7 days time range. Changed Now delay now- to 1h and went back from dashboard settings to dashboard and the time range still showed Last 7 days. 
Then saving the dashboard and reloading it still shows last 7 days.
Changing the time range to something else, like last 2 days, will properly add a delay of 1h.

**Comment by mtanda** [comment]
Thanks!

**Comment by joshhunt** [comment]
Just checked this out, and it looks like the issue has since been fixed. At least, I can no longer reproduce it.

I set my "Now delay" to `1d`, and when loading the dashboard fresh, with no query string variables, it correctly offsets the current day

![image](https://user-images.githubusercontent.com/46142/140534491-97e55a5f-6ed2-4334-9918-3f30eb3f9bc8.png)

@mtanda I know it's been a while, but if you're still seeing this issue please let us know and we'll reopen.
