### ISSUE TITLE
Elasticsearch: Adhoc filter ignored when using logs panel

### ISSUE THREAD

**Issue by yoke88** [grafana/grafana#21086]
**What happened**:
log panel ignore the adhoc filter, when you add new adhoc filter , other panel use the adhoc filter and show the filtered data, but log panel ignore the adhoc filter.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5
- Data source type & version: Elasticsearch 6.x
- OS Grafana is installed on: centos 7.9
- User OS & Browser: chrome lastest
- Grafana plugins: log panel
- Others:

**Comment by marefr** [comment]
For anyone interested in contributing:

Regular query method used for non-logs queries gets the applied adhoc filters [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L328). Then pass it to query builder [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L353). 

Logs queries need to pass it to logs query builder [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L347). Logs query builder needs to call addAdhocFilters as in [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/query_builder.ts#L206).

Need to make sure that logs queries still works as expected in Explore logs mode.
