### ISSUE TITLE
Displaying Event Based Metrics

### ISSUE THREAD

**Issue by shahamit** [grafana/grafana#2109]
Hello,

I have been using riemann (event processor), graphite (storage) & grafana (dashboards) in our monitoring infrastructure. We send metrics to riemann when certain events occur. For e.g. When the user uploads a file we send the file size as a metric for storage & analysis. These metrics are different from continuous metrics like cpu-usage, memory etc.
What would be the best way to visualize these metrics on a grafana dashboard?

**Comment by torkelo** [comment]
using graphs? It is impossible to answer such a question. depends on a million factors, what do you want to know, how to measure these things, how are they stored in graphite, what are the pre aggregations, and metric organizations etc
