### ISSUE TITLE
Option to disable unit scaling

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#21100]
**What would you like to be added**:
Option to disable unit scaling.
![image](https://user-images.githubusercontent.com/19311511/70837728-420c6600-1e05-11ea-95ba-13e8e4dc7f77.png)

![image](https://user-images.githubusercontent.com/19311511/70837736-4f295500-1e05-11ea-90eb-5fee991242c8.png)

**Why is this needed**:
For example, if I have number 2500 and I choose meter unit, it is automatically scalled to 2.5km.
I know it is possible to solve by disabling unit and entering postfix in singlestat, but postfix is not available in gauge panel.

**Comment by ryantxu** [comment]
you mean if you could just enter:
```
suffix:m
```
And then have it say "2515 m" you would be happy?

**Comment by szerwi** [comment]
@ryantxu Better option would be to disable unit scaling, but enabling the prefix and postfix in Gauge panel will also be ok for me.

**Comment by torkelo** [comment]
great, then that is already implemented, v6.6 will launch with custom support for prefix & suffix (in master/nightly builds)

**Comment by szerwi** [comment]
@torkelo v6.6.0 was released today, but I can't see custom prefix & suffix in Gauge panel.

**Comment by szerwi** [comment]
I found that there are custom units added, but when I type "m" it is changed to day unit. I need to type "m " (with space after) to get it working properly.
