### ISSUE TITLE
Azure Log Analytics not formatting table cells if title includes ( ) characters

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#21106]
**What happened**:
Azure Log Analytics table cells not formatted if they contain ( ) characters. I have underlined the column name in red in the screen shots.

![image](https://user-images.githubusercontent.com/1184220/70854907-3a5ac900-1eba-11ea-9725-76ad2771d6a3.png)

![image](https://user-images.githubusercontent.com/1184220/70854914-5eb6a580-1eba-11ea-9ebd-357d6e4fd109.png)

**What you expected to happen**:
Cell to be formatted based on the Visualization settings above.

**How to reproduce it (as minimally and precisely as possible)**:
See screen shots for example. Add a query to Azure Log Analytics which outputs column names including ( ) characters and set the visualization for the column to color the cells.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Azure Application Insights
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 & Chrome

**Comment by dprokop** [comment]
@bhozar thank you for reporting this. Apparently this is a bug.

As a workaround you can match your column using this regex: `/^Counter \(Failed\)$/`
