### ISSUE TITLE
JSON model "save changes" should take a change description

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#21109]
**What would you like to be added**:
"Save changes" of General / JSON Model should accept a change description, just like any other dashboard save.

**Why is this needed**:
Change descriptions are important, given the difficulty of managing dashboard revisions when multiple people have edit access.

**Comment by belm0** [comment]
The respective backend calls for regular save (with description) and mode save:

https://github.com/grafana/grafana/blob/9ac7263e66968df8b570ba766d735ef3f722c2d6/public/app/features/dashboard/components/SaveDashboard/useDashboardSave.tsx#L14

https://github.com/grafana/grafana/blob/8f78b0e7bc37710b36fbd4dce521ca488d31c4e0/public/app/features/dashboard/components/DashboardSettings/SettingsCtrl.ts#L148

I think both cases should use the same modal save (with complete time, variable, and description options) and make the same backend call.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
