### ISSUE TITLE
Unexpected number of series when grouping by tags listed in a variable

### ISSUE THREAD

**Issue by andrasg** [grafana/grafana#21107]
**What happened**:

Grouping by tag names stored in a dashboard variable produces unexpected additional series appearing. This (these) unexpected additional series show values only for today

<img width="523" alt="image" src="https://user-images.githubusercontent.com/10730249/70864809-311f3a00-1f56-11ea-95ed-685c94ee7b93.png">

**What you expected to happen**:

Only two series showing up instead of 3-4.

**How to reproduce it (as minimally and precisely as possible)**:

This is the query I am running:

`SELECT integral("power",1h) FROM "sonoff" WHERE ("name" =~ /^$selectedsonoff$/) AND $timeFilter GROUP BY "name", time(1d) TZ('Europe/Budapest')`

The `$selectedsonoff$` are defined dashboard level as:

`SHOW SERIES FROM "sonoff"`

This query returns two tags (`Dish_Washer` and `Washing_Machine` in my case).

**Anything else we need to know?**:

**Environment**:
- Grafana version: `Grafana v6.4.4 (092e514)`
- Data source type & version: `InfluxDB shell version: 1.7.9`
- OS Grafana is installed on: `Windows Server 2019`
- User OS & Browser: issue is not OS/Browser specific, have tested on Mac+Safari and Windows+Chrome
- Grafana plugins: `none`
- Others: `none`

**Comment by torkelo** [comment]
Can you include the raw response from InfluxDB? It's probably returning separate series for some reason

**Comment by andrasg** [comment]
This is what I am seeing as a JSON response in the browser developer tools.

Query:
```
db: loxone
q: SELECT integral("power",1h) FROM "sonoff" WHERE ("name" =~ /^(Dish_Washer|Washing_Machine)$/) AND time >= now() - 14d GROUP BY "name", time(1d) TZ('Europe/Budapest')
epoch: ms
```
Response:
```json
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "sonoff",
                    "tags": {
                        "name": "Dish_Washer"
                    },
                    "columns": [
                        "time",
                        "integral"
                    ],
                    "values": [
                        [
                            1576969200000,
                            0.9284611583403376
                        ]
                    ]
                },
                {
                    "name": "sonoff",
                    "tags": {
                        "name": "Washing_Machine"
                    },
                    "columns": [
                        "time",
                        "integral"
                    ],
                    "values": [
                        [
                            1578178800000,
                            425.0556799484027
                        ]
                    ]
                },
                {
                    "name": "sonoff",
                    "tags": {
                        "name": "Dish_Washer"
                    },
                    "columns": [
                        "time",
                        "integral"
                    ],
                    "values": [
                        [
                            1578178800000,
                            1514.1537156504032
                        ]
                    ]
                }
            ]
        }
    ]
}
```

Seems to confirm that the datasource (InfluxDB) is returning the data as separate series.

**Comment by andrasg** [comment]
Opened an issue for InfluxDB: https://github.com/influxdata/influxdb/issues/15907
