### ISSUE TITLE
Help needed on Grafana API  (Datasources)

### ISSUE THREAD

**Issue by trblft** [grafana/grafana#2110]
Hi, as said there https://github.com/grafana/grafana/issues/1112 ,  I just discovered Grafana, I would like to get into the Datasource plugin development code. I saw in another post that you considered building a plugin API? Did I get it wrong?
I would like to know how grafana reaches its datasources? It looks like webservices. Is there a standard webservice query API for all TSDB systems? If so, would Grafana reach any webservice implementing this API? Where can I get info about Grafana dev?
I'm planning to use https://github.com/Lothiraldan/MongoTSDB .
Thanks and congratulations for this awesome piece of work.

**Comment by torkelo** [comment]
There is no help for this, you can implement a custom data source (and write javascript code and html views for the query editors, you can then query any http api any any way). This i how all data sources in Grafana is implemented. You can look at the how the current ones are implemented and create one for your self, there is no docs, so you need to know javascript, angularjs and requirejs 
https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource

**Comment by trblft** [comment]
Perfect, thanks a lot.
