### ISSUE TITLE
Log shows "Filesystem in ReadOnly alert"

### ISSUE THREAD

**Issue by mpavlovicbb** [grafana/grafana#21118]
**What happened**: Grafana logs shows message: 
msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=2 name="Filesystem in ReadOnly alert" error="tsdb.HandleRequest() error bad_data: end timestamp must not be before start time" changing state to=keep_state

**How to reproduce it (as minimally and precisely as possible)**: did not figured out why this is happeningh

**Anything else we need to know?**: dokcer is created together with curl command

**Environment**:
- Grafana version: 6.5.1 and 6.4.3
- Data source type & version: prometheus and influx
- OS Grafana is installed on: ubuntu 18.04

Grafana works well, I am not seeing any performance issues. Just this message is showed in logs every 60 seconds.

**Comment by marefr** [comment]
Seems like an error from Prometheus. You seem to send to time as from and vice versa. Please include dashboard json that shows this is a Grafana problem.
