### ISSUE TITLE
Provisioning: Performance problems when used with hundreds of orgs

### ISSUE THREAD

**Issue by vijayakumarbathini** [grafana/grafana#21113]
**What happened**:
We are running auto provisioning for 600 organisations with each having 50+ dashboards and 10+ datasources data and it is causing  CPU cores to be fully occupied and grafana application is hanging/ responding very slow.

**What you expected to happen**:
Application to run as is for huge data also without slowness of application

**How to reproduce it (as minimally and precisely as possible)**:
Try to run auto provisioning with big data as mentioned above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3
- Data source type & version: Postgres 11
- OS Grafana is installed on: Linux 
- User OS & Browser: OSX and chrome
- Grafana plugins:
- Others:

**Comment by vijayakumarbathini** [comment]
![image](https://user-images.githubusercontent.com/7524183/70906962-a27dec00-202d-11ea-89cb-fe2219c36c57.png)

**Comment by marefr** [comment]
This is definitely not a use case provisioning was built by in mind having over 600 orgs. What's your current `updateIntervalSeconds`? Can you try increasing the `updateIntervalSeconds`? For reference, https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards.

**Comment by vijayakumarbathini** [comment]
We are not providing any updateIntervalSeconds in dashboard.yaml file, and believe it is using default 10 seconds.

**Comment by aknuds1** [comment]
Thanks for bringing this problem to our attention, we're discussing it internally and it looks as if it's an issue that requires some thinking from our side with regards to coming up with a solution.

**Comment by marefr** [comment]
@vijayakumarbathini thanks. You can try and increase the `updateIntervalSeconds` in dashboard provisioning yaml files to `300`?
- Is this happening when you start Grafana, but resolves after initial provisioning are done or are you seeing this all the time from start of Grafana? 
- Are you provisioning same sets of data sources and dashboards to all orgs or different?
- Are the dashboards you provisioning stored in a tree-like hierarchy of directories where you references for example boot root of directory `/` and `/child-dashboards`?
- Can include some sample configuration files?
- Do you have multiple Grafana instances using the same provisioning configuration?

Can you enable debug logging for provisioning and include some logs here to underline what's going on?
```
[log]
filters = provisioning.datasources:debug provisioning.dashboard:debug datasource.permissions:debug
```

**Comment by vijayakumarbathini** [comment]
@marefr The above issue is happening as long as auto provisioning is running in background. 
1. With the data we are having auto-provisioning is taking 20-30 mins for first time and from next restart it is taking around 1 min. Till this time we are not able to access the UI.
2. Yes, we are using same sets of datasources and dashboards for all orgs
3. No, all the dashboards are in same folder /etc/grafana/dashboards and there are no sub directories
4. No, we are using only single instance

FYI: Most of the time in auto provisioning is happing for dashboard insertions into db


[dashboards.txt](https://github.com/grafana/grafana/files/3978403/dashboards.txt)

If the above information is not enough, will try to get debug logs during next restart and provide you the log data
