### ISSUE TITLE
Admin: Org list, add sort order is Id column

### ISSUE THREAD

**Issue by vijayakumarbathini** [grafana/grafana#21119]
**What happened**:
When we are listing organisations the ID order was not sorted
**What you expected to happen**:
Sorted List of Org IDs
**How to reproduce it (as minimally and precisely as possible)**:
Create Few Organisations from HTTP API call and few more from UI directly.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/7524183/70907230-597a6780-202e-11ea-950f-bcfc43b2eb54.png)

**Environment**:
- Grafana version: 6.3
- Data source type & version: Postgres 11
- OS Grafana is installed on: Centos
- User OS & Browser: OSX and Chrome
- Grafana plugins:
- Others:

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
