### ISSUE TITLE
How to Backup?

### ISSUE THREAD

**Issue by oryagel** [grafana/grafana#2111]
Hi,

With the previous version I was backing up with a script I saw here a while ago.

What is the correct way to backup in 2.0?

Thanks

**Comment by torkelo** [comment]
it depends if you use sqlite3 you just backup the sqlite3 db file (by default in /var/lib/grafana/grafana.db), if you use mysql you use the standard ways to backup mysql db, and same goes for postgres

**Comment by oryagel** [comment]
Thanks
