### ISSUE TITLE
Can't set "On Time Range Change" on variable creating dashboard with API

### ISSUE THREAD

**Issue by limo49** [grafana/grafana#21115]
**What happened**:
Using the API, I created a test dashboard defining a variable (in "templating") with "refresh": 2 (On Time Range Change) but the variable was created with "refresh": 1 (On Dashboard Load).

**What you expected to happen**:
Tha variable should use "refresh": 2

**How to reproduce it (as minimally and precisely as possible)**:
Here is the JSON request that received "status":"success":

`{
    "dashboard": {
        "title": "TEST",
        "id": null,
        "uid": null,
        "templating": {
            "list": [
                {
                    "allFormat": "glob",
                    "allValue": null,
                    "current": {},
                    "datasource": "PostgreSQL",
                    "definition": "SELECT 1;",
                    "hide": 2,
                    "includeAll": false,
                    "label": null,
                    "multi": false,
                    "name": "my_variable",
                    "options": [],
                    "query": "SELECT 1;",
                    "refresh": 2,
                    "regex": "",
                    "skipUrlSync": false,
                    "sort": 0,
                    "tagValuesQuery": "",
                    "tags": [],
                    "tagsQuery": "",
                    "type": "query",
                    "useTags": false
                }
            ]
        }
    },
    "folderId": 0,
    "overwrite": false
}`

**Environment**:
Grafana version: 6.5.2

**Comment by dprokop** [comment]
@marefr seems like a bug, reproduced on master

**Comment by marefr** [comment]
@dprokop but is it really something in the backend? Seems to me something has changed in the frontend?

**Comment by torkelo** [comment]
you need to add a   "schemaVersion":  21  to your json, since you have none grafana will try to upgrade the schema, and old dashboards schemas had boolean refresh properties, so ther is a migration for that which updates it
