### ISSUE TITLE
Bug in Prometheus links with --mixed-- data source

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#21129]
## What happened

1. Have 2 Prometheus data sources.
2. Create a panel with `--mixed--` data source.
3. Add 2 queries with different Prometheus data sources.

When viewing the panel in edit mode, the **Link to Graph in Prometheus** of every data source has the domain name of the first data source.

For example:

Query A uses data source `http://prom-1:9090`  
Query B uses data source `http://prom-2:9090`

Link A will be `http://prom-1:9090/graph?g0.expr=query-A`  
Link B will be `http://prom-1:9090/graph?g0.expr=query-B`

Notice only the domain part is wrong. The query expression is correct.

## What you expected to happen

Query A uses data source `http://prom-1:9090`  
Query B uses data source `http://prom-2:9090`

Link A will be `http://prom-1:9090/graph?g0.expr=query-A`  
Link B will be `http://prom-2:9090/graph?g0.expr=query-B`

## How to reproduce it (as minimally and precisely as possible)

I attached a tarball that reproduces the problem in a Docker container.

[prometheus-mixed-datasource-bug.tar.gz](https://github.com/grafana/grafana/files/3970280/prometheus-mixed-datasource-bug.tar.gz)

```
tar tzf prometheus-mixed-datasource-bug.tar.gz 
prometheus-mixed-datasource-bug/
prometheus-mixed-datasource-bug/start.sh
prometheus-mixed-datasource-bug/datasources.yml
prometheus-mixed-datasource-bug/dashboards.yml
prometheus-mixed-datasource-bug/dashboards/
prometheus-mixed-datasource-bug/dashboards/a.json
```

Running `start.sh` runs a Grafana container and provisions two data sources and 1 dashboard.

Open http://localhost:3000/d/ashboard/prometheus-links-in-mixed-data-source?orgId=1&fullscreen&edit&panelId=2 and look at the URLs.

Compare the two Prometheus Graph URLs:

```
http://prom-1:9090/graph?g0.expr=up&g0.range_input=21600s&g0.end_input=2019-12-16%2021%3A41&g0.step_input=30&g0.tab=0
http://prom-1:9090/graph?g0.expr=node_cpu_seconds_total&g0.range_input=21600s&g0.end_input=2019-12-16%2021%3A41&g0.step_input=30&g0.tab=0
```

## Environment
- Grafana version: 6.5.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: Fedora, Firefox
- Grafana plugins:
- Others:

**Comment by stuartnelson3** [comment]
confirmed on v6.6.0

datasource: prometheus
grafana os: debian 10
user os / browser: arch / firefox

**Comment by torkelo** [comment]
This looks easy to fix, https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/components/PromLink.tsx#L38 
The code there takes the data source from request queries (first query), instead using the datasource instance being passed via props
