### ISSUE TITLE
Unable to save/modify any datasource

### ISSUE THREAD

**Issue by craftytrickster** [grafana/grafana#2112]
With the latest from master, if I try to save a datasource I get the following message

```json
[{"fieldNames":["Id"],"classification":"RequiredError","message":"Required"}]
```
New datasources won't have an id yet logically

Likewise, if I try to save an existing datasource, I get this message
```json
{"message":"Not found"}
```

It seems like something has been broken on the go backend

**Comment by torkelo** [comment]
Your frontend js/html partials must be out of date, did some breaking changes to the http api for datasources (the PUT/POST actions where the wrong way arround and fixed another issue).  

This was done in this issue: 
https://github.com/grafana/grafana/issues/1997
