### ISSUE TITLE
Login window after changing Organization name as Anonymous viewer

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#21138]
**What happened**:
1. View Grafana as Anonymous user
1. Change Organization name on /org
1. Observe 'unauthorized' error
1. Navigate to anywhere else in Grafana
1. Get Login window (also other users get Login window when navigating)

**What you expected to happen**:
Organization name doesn't change, anonymous can continue to use Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
*see What happened
Observed on dev-us-central1 cluster.

**Anything else we need to know?**:
Similar issue: https://github.com/grafana/grafana/issues/11174#issuecomment-381506410

The error from the logs:
```
 lvl=eror msg="Anonymous access organization error: 'Main Org.': Organization not found"
```

**Environment**:
- Grafana version:  v6.4.4 (commit: 092e514) and v6.2.5 (commit: 6082d19)
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: macOS / Firefox
- Grafana plugins: n/a
- Others:

**Comment by torkelo** [comment]
Of you change org name for the anonymous org you need to update the grafana.ini config file where the name of the anonymous org is specified
