### ISSUE TITLE
missing metrics in graph

### ISSUE THREAD

**Issue by jstutesman** [grafana/grafana#2113]
I have metrics of the form
metric.\<hostname\>.\<service\>.\<value\>
and a scripted dashboard that takes a parameter for \<hostname\>, and generates a graph per \<value\> with a line per \<service\>.

For the most part this works as desired, but sometimes there are lines missing.  The name shows in the legend, but no line displays on the graph.  If you refresh from the browser or from the button on the page some lines will appear, and others may disappear.  After 10 or so refreshes you may get a page with all the lines on it.

I can't find any errors in any of the logs, and i can't find a way to ensure all the metrics are displayed.

**Comment by torkelo** [comment]
what data source do you use? sounds like a time series db issue, never seen this myself. 

Can you inpect the result from you time series query? See that they contain all the series you expect grafana to draw in the graph? 

Also can you show all your graph options?

**Comment by jstutesman** [comment]
The data source is Graphite.  

You are correct, It does look to be a time series issue, the response is coming back with all null's (and only 60 of them) for the lines that do not appear.  Perhaps something in my graphite setup?  Odd that they appear on some refreshes but not others.

This is the function that sets up all the graph options:
function AddPanel(row, stat, services)
{
	var panel = {
        title: stat,
        type: 'graph',
        span: 6,
        fill: 1,
        linewidth: 2,
        targets: [],
        seriesOverrides: [],
		cacheTimeout: 60,
        tooltip: {
          shared: true
        }
     };
	 
	 for(var i = 0; i< services.length; ++i)
	 {
		 panel.targets.push({ 'target': "aliasByNode(metric." + HostName + "." + services[i] + "." + stat, 2)" });
	 }
	 
	row.panels.push(panel);
	return panel;
};

Thanks

**Comment by torkelo** [comment]
check you storage-schemas.conf file, your retention config might be bad

**Comment by jstutesman** [comment]
If anyone else has this issue, I believe it was because the graphite schema for this data was set to to a higher resolution (1/minute) than the metrics were actually being sent at (1/hour).  So when Graphite aggregated the data down to the points needed on the graph, they all ended up as nulls.

Not sure why it worked on some refreshes but not others, but changing the schema to store 1/hour and repopulating the data resolved the issue for me.

Thanks for the help!
