### ISSUE TITLE
Variables: URL share "Template variables" option not honored

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#21131]
**What happened**:
Disabling "Template variables" option in share link panel is not honored in some cases (e.g. when dashboard was opened with URL having template variables).

**What you expected to happen**:
template variables are removed from share URL

**How to reproduce it (as minimally and precisely as possible)**:
  1. load a grafana dashboard from a URL which includes template variables.
  2. Share dashboard -> Link
  3. disable "Template variables" option

Note that template variables are still in the share URL.

**Environment**:
- Grafana version: v6.4.3
- Data source type & version:  n/a
- OS Grafana is installed on: n/a
- User OS & Browser: OS X / Chrome

**Comment by hugohaggmark** [comment]
I can confirm this is still the case in Grafana v7.3.1 (6668161a88). I wonder if this isn't deliberate, why would you share a Panel that depends on variables without the variables? There is something wrong with the UX here perhaps? 

Maybe we can't know if a panel depends on variables or not? In that case, we should strip away the template variables as this issue states.

**Comment by torkelo** [comment]
Think we will remove the template variable option, created issue for that https://github.com/grafana/grafana/issues/29191
