### ISSUE TITLE
First API request always fails when changing orgId in query

### ISSUE THREAD

**Issue by ForTakEr** [grafana/grafana#21137]
**What happened**: 
First API request always fails when changing the `?orgId=$id` query in the url. All requests after that go through without any problems.
![Screenshot 2019-12-17 at 12 00 32](https://user-images.githubusercontent.com/32396272/70985508-ea9c1d80-20c4-11ea-9550-f83aada05a23.png)

**What you expected to happen**:
Expected to get a response on the first request when changing the `?orgId=$id` query.

**How to reproduce it (as minimally and precisely as possible)**:
`curl http://admin:admin@localhost/api/folders?orgId=$id` - first request against an org fails

**Environment**:
- Grafana version: 6.5.1
- OS Grafana is installed on: Linux (Grafana docker image)

**Comment by yesoreyeram** [comment]
You may need to call switch org api before calling APIs for different orgs and you need to wait for the response. (  That is bit annoying though )

**Comment by torkelo** [comment]
Use Header X-Grafana-Org-Id  to issue api calls for different tenants (orgs)
