### ISSUE TITLE
Repeat field also repeat alert

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#21141]
**What happened**:
after setting alert on a repeating panel,
all repeated panel will have same alert,
and click save will leading backend has duplicate alert which belong to repeat panel

**What you expected to happen**:
repeat panel do not repeat alert

**How to reproduce it (as minimally and precisely as possible)**:
1. add a repeat panel
2. set alert on first repeat panel and save
3. refresh page, and all repeat panel has alert, and save
![image](https://user-images.githubusercontent.com/3352585/70996102-13e09c00-210d-11ea-8560-b32895f61f87.png)
![image](https://user-images.githubusercontent.com/3352585/70996168-2b1f8980-210d-11ea-91b9-53e766281739.png)

4. there are duplicate alert in backend

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
template variables are not supported in alert queries, so this use cases won't work. 

We are planning to make alerts standalone rules you create & maintain separately from dashboards & graphs. So this won't be something we will ever support.
