### ISSUE TITLE
repeat panel should not be editable

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#21142]
Accoarding to [doc](https://grafana.com/docs/grafana/latest/reference/templating/#repeating-panels) only first repeat panel should be edit. other repeat panel (which as repeatPanelId field) shoud not be edit, because it will be override after next dashboard rebuild.
But in UI, there is not any notification or anything else to forbid user to edit child repeat panel,
and no guide or highlight to lead user edit first panel.
some user which is not familar with grafana will edit later repeat panel and save, but after refresh page, their change lossing without any notification. this is make no sense

**Steps to reproduce**:

**Actual Result**:

**Expected Result**

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- User OS & Browser: windows chrome
- Others:

**Comment by okhowang** [comment]
now entry for edit repeated panel has been removed.
is there any plan to add some UI effect to distinguish original panel and repeated panel?
for example, add a gray mask on repeated panel

**Comment by dprokop** [comment]
@okhowang colosing this issue as it's fixed. Please open a feature request if you feel like indicating the repeated panels is important
