### ISSUE TITLE
Azure Monitor - Table View - parsing strings as date

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#21149]
**What happened**:
Since the upgrade to 6.5, the table view is trying to parse data in the first table as date, no matter what data is provided. Changing the data type to "String" doesn't fix the issue. The panel is showing this type of error:

> parsing time "Internet Explorer 11.0" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "Internet Explorer 11.0" as "2006"

This was tested using Azure Monitor datasource and the Application Insights service.

Downgrading Grafana back to version 6.4.5 fixed the issue for now.

**What you expected to happen**:
Table view should show data that is sent there as a string instead of trying to format it as a date.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a table with AI data 
2. Select a value that's not timestamp 
3. Try executing query

**Anything else we need to know?**:
This was tested on Grafana Cloud

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Azure Monitor 0.3.0

![How it should look like](https://user-images.githubusercontent.com/56955081/71006248-55f5e780-20e5-11ea-8ee5-93a585b8b0ca.png)
![Broken](https://user-images.githubusercontent.com/56955081/71006319-78880080-20e5-11ea-82e7-2e0ee7a4efcf.png)
![DataType](https://user-images.githubusercontent.com/56955081/71006267-60b07c80-20e5-11ea-839a-2875bd0b7ffe.png)
![Errormessage](https://user-images.githubusercontent.com/56955081/71006273-627a4000-20e5-11ea-8f07-06b3f70dc29a.png)
![DataType](https://user-images.githubusercontent.com/56955081/71006287-66a65d80-20e5-11ea-8187-3d70c7ee8412.png)
![Query Error](https://user-images.githubusercontent.com/56955081/71006293-68702100-20e5-11ea-9ec5-6126130c323f.png)

**Comment by ChristianS1979** [comment]
Hi,

I was wondering whether there is an update on this issue? Are there any known workarounds, I haven't found any?
Currently I am using Grafana 6.4.3 and this issue prevents us from upgrading to the latest version.

Thank you for any response.

**Comment by stebet** [comment]
Is there an update on this?

**Comment by ChristianS1979** [comment]
Hi,

Last week I was able to fix this for my environment by making use of a log Analytics workspace and performing the Kusto query there via app("$ApplicationInsightsResourceX").requests. There you can choose for the outcome to be a timeseries or a table. When using the table no restrictions.

Example query:
app("$ApplicationInsights_X").requests
| where $__timeFilter(timestamp)
| where success == "False"
| summarize count() by name, tostring(resultCode)
| order by count_ desc

**Comment by stebet** [comment]
> Hi,
> 
> Last week I was able to fix this for my environment by making use of a log Analytics workspace and performing the Kusto query there via app("$ApplicationInsightsResourceX").requests. There you can choose for the outcome to be a timeseries or a table. When using table there are no restrictions on the columns.
> 
> Example query:
> app("$ApplicationInsights_X").requests
> | where $__timeFilter(timestamp) | where success == "False" | summarize count() by name, tostring(resultCode) | order by count_ desc

Did you get this working in Grafana? Because I'm still receiving the datetime parsing errors there.

**Comment by stebet** [comment]
Any movement on this? Rendering Tables for anything that doesn't have time is not really possible now.

**Comment by mariomann** [comment]
Hi @stebet,

I found a workaround, maybe this one is also suitable for you:

In my example I had to add the timestamp to my ApplicationInsights query in the section 'summarize', this will group your result by the timestamp <`bin(timestamp, $__to - $__from)`>:

`customMetrics | where name == "<name>" 
| where $__timeFilter()
 | where customDimensions.result == "failed" | extend exceptionMessage = customDimensions.exceptionMessage, resultValue = customDimensions.result 
| summarize failedCount = countif(value > 0) by tostring(exceptionMessage), bin(timestamp, $__to - $__from)`

Than you need to specify the `timestamp` at `X-axis` your aggregated value at `Y-axis` and `Split on` your text column, in my example it is `exceptionMessage`

<img width="1653" alt="1" src="https://user-images.githubusercontent.com/3458678/79985754-5f37fc00-84ab-11ea-965f-a62a21448192.png">

Than you have to switch to `Visualization` menu in your Grafana table panel and select `Timeseries to rows` for `Table Transform`.

<img width="1636" alt="2" src="https://user-images.githubusercontent.com/3458678/79986110-d4a3cc80-84ab-11ea-8b3e-0eed60b639a3.png">

After this you need to hidden your `Time` column, with column styles:

<img width="1543" alt="3" src="https://user-images.githubusercontent.com/3458678/79986186-f1d89b00-84ab-11ea-9538-a495547ff39e.png">

The metric name is not perfect but it's better than nothing.

<img width="1647" alt="4" src="https://user-images.githubusercontent.com/3458678/79986287-1896d180-84ac-11ea-9bfd-1b733535b508.png">

Hope this will help you.

**Comment by kylebrandt** [comment]
The two analytics services have been re-implemented for 7.1.  In particular, there are no more Axis selectors and the service behaves the same as Log analytics.

The parsing logic of the response has also been changed. So I'm going to assume this is fixed in 7.1.  If it is not, please do reopen the issue and we will investigate closer.
