### ISSUE TITLE
Public Snapshot: Can't be embedded or loaded in an iframe

### ISSUE THREAD

**Issue by pafy6285** [grafana/grafana#21155]
**What happened**: 
Observed this week that snapshots published on snapshot.raintank.io is not being loaded in an iframe (when embedded). Verified that the published snapshots can be loaded when opened in another browser window. Tested this on Chrome, Firefox and MS Edge. Also noticed that in this Grafana documentation regarding sharing a panel, the iframe example is also not being loaded: https://grafana.com/docs/grafana/latest/reference/share_panel/

**What you expected to happen**: 
Able to embed or load snapshots published on snapshot.raintank.io in an iframe.

**How to reproduce it (as minimally and precisely as possible)**:
Publish a Snapshot on snapshot.raintank.io. Embed the snapshot URL in an iframe like in this example: https://grafana.com/docs/grafana/latest/reference/share_panel/

**Anything else we need to know?**:
Embedded snapshots was at least working on November. Just noticed the issue this moth. Not sure if the issue is related to https://github.com/grafana/grafana/issues/18490, since as per that issue's latest update, it seems that the raintank was upgraded recently. So if security settings such as allow_embedding was set to false for example during the upgrade, then that might explain the issue.

**Environment**:
- Grafana version: 6.2.5 (also tested on 6.5.2)
- Data source type & version: InfluxDB 1.7.9
- OS Grafana is installed on:  installed using helm stable/grafana (so I believe it's alpine?)
- User OS & Browser: Windows 10 / FF / Chrome / Edge
- Grafana plugins: 
- Others: just a screenshot from the Grafana documentation not being able to load the iframe example
![image](https://user-images.githubusercontent.com/774234/71050427-64063100-2102-11ea-8200-c66bd2ea0b5a.png)

**Comment by dprokop** [comment]
@torkelo @marefr can you please take a look at this?

**Comment by hpo14** [comment]
Got the same issue.
I simply embed the whole site in iframe, it was working and good with grafana v6.1.4

```<iframe src="http://<my grafana site>/"></iframe>```

After i **ONLY** update grafana to v6.5.2 and without other change, i only got 
```"<my grafana site> refuse to connect"``` string on the page.

**Comment by marefr** [comment]
@torkelo can you [enable embedding](https://grafana.com/docs/grafana/latest/installation/configuration/#allow-embedding) on snapshot instance? Or should we rather remove the embedded content in docs site to make snapshot server more secure? Think we may be able to configure reverse proxy of snapshot instance to allow embedding from grafana.com for example.

**Comment by torkelo** [comment]
I changed 
allow_embedding = true

So it works now

**Comment by smith-scot** [comment]
How do you get to the grafana.ini file to change the value.  I am running grafana in a docker container, and the env variable GF_PATHS_CONFIG is set to /etc/grafana/grafana.ini; however I don't understand how to access the file from the env variable.  Any help would be appreciated

**Comment by torkelo** [comment]
Any option in the ini file can be set using an env variable , check Grafana docs (config section) for how to set any ini option

**Comment by hi-rustin** [comment]
Does it still work? I tried it doesn't seem to allow me to embed it.

![image](https://user-images.githubusercontent.com/29879298/199686111-fe5534e8-99a3-47e3-8991-431c8ea05ede.png)

**Comment by hi-rustin** [comment]
Checked grafana's docs. It also doesn't work.
![image](https://user-images.githubusercontent.com/29879298/199687514-e1c87588-40e0-4ca1-822e-455a7f68f32e.png)

**Comment by hi-rustin** [comment]
@marefr  Could you please take a look? Thanks!

**Comment by marefr** [comment]
@torkelo possible that your change has been reverted?

**Comment by marefr** [comment]
> I changed
> allow_embedding = true
>
> So it works now

@torkelo was referring to that. Sounded to me that you re-configured the snapshot server :smile:

**Comment by torkelo** [comment]
@marefr oh, I thought you where refering to a PR, and that comment of mine was referring to a local config change :) '

I don't have access to this server anymore. Think it's moved from digital ocean to google?

**Comment by marefr** [comment]
@torkelo okay thanks :smile: I'll raise it with those responsible for the public snapshot server

**Comment by jshbrntt** [comment]
Is this a recent regression?

**Comment by hi-rustin** [comment]
At least a month now. Because I found out a month ago that it doesn't work.

**Comment by marefr** [comment]
Great news. It works now https://grafana.com/docs/grafana/latest/dashboards/share-dashboards-panels/
