### ISSUE TITLE
Generic OAuth JMESPath Expression Extension To Support Rejected Authorization

### ISSUE THREAD

**Issue by fifofonix** [grafana/grafana#21153]
**What would you like to be added**:
Extension of the v6.5.1 Generic OAuth JMESPath role mapping feature to allow resolution to rejected authorization with a custom error or re-direct to explain this fact to end users.

**Why is this needed**:
We are using a single OIDC client (Keycloak) that governs access to several services that are part of our wider platform.  Authentication to the OIDC client does not necessarily imply authorization to access Grafana.  Instead authorization should require explicit roles associated with the user per security best practices.

Presently we are able to achieve seamless login/navigation across entitled non-Grafana services, and when accessing Grafana able to correctly assign Admin vs Editor roles using a JMESPath expression.  However, even if we remove Viewer as a default option from the JMESPath expression we find that Grafana resolves to Viewer credentials anyway.

Ideally in the event of unauthorized access it would be possible to specify a custom error explaining to the user what authorization they are missing.  This could be implemented by configuration of a customizable redirect but other solutions are possible.

**Comment by marefr** [comment]
This is something that the OAuth provider should validate and not Grafana.

**Comment by fifofonix** [comment]
You may well be right @marefr but perhaps you can explain how you see this working.

The scenario is that I'm logged into my OAuth provider successfully and my UserInfo point says that I should have access to service A and B for the sake of argument but says nothing about service C (Grafana).  I navigate to Grafana, and it immediately sees that I have an OAuth token, queries my UserInfo and plays through the JMESPath expression.  With current behavior I'm given access as Viewer to Grafana irrespective of the contents of the UserInfo because it assumes I have at least some valid authorization (but I do not).

If we play that exact scenario again but this time my UserInfo says I should additionally have service C access as Grafana Editor access, then everything resolves great with seamless sign-on.  And I can navigate to services A and B whilst remaining logged in.  And back to Grafana.  This latter scenario is what we have working currently.  The only issue is that we can't get a no auth decision when Grafana access is not authorized.

We could implement another OIDC client for Grafana only but then we wouldn't have the seamless navigation between services.  At least as a relative newbie on OAuth and OIDC I think that that is the case.  Any insight you can provide as to how you think this would work appreciated.
