### ISSUE TITLE
Javascript error creating dashboard with API

### ISSUE THREAD

**Issue by limo49** [grafana/grafana#21154]
**What happened**:
After creating a dashboard with the API, I have this error trying to open it in Grafana:

`An unexpected error happened`
`TypeError: Cannot read property 'toString' of undefined`

The first 2 lines in the brower console are:

`TypeError: Cannot read property 'toString' of undefined`
`    at e.buildLayout (DashboardGrid.tsx:122)`
`    at e.render (DashboardGrid.tsx:271)`

**What you expected to happen**:
The dashboard should be shown

**How to reproduce it (as minimally and precisely as possible)**:
I have created a dashboard with a panel in Grafana and copied the JSON to test its creation via API.
I removed id, uid and version from the dashboard and id from the panel:

`{
    "dashboard": {
        "annotations": {
            "list": [{
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
            }]
        },
        "editable": true,
        "gnetId": null,
        "graphTooltip": 0,
        "links": [],
        "panels": [{
            "aliasColors": {},
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": "Prometheus",
            "fill": 1,
            "fillGradient": 0,
            "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
            },
            "hiddenSeries": false,
            "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": true,
                "total": false,
                "values": false
            },
            "lines": true,
            "linewidth": 1,
            "nullPointMode": "null",
            "options": {
                "dataLinks": []
            },
            "percentage": false,
            "pointradius": 2,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": false,
            "targets": [{
                "expr": "icmp:response",
                "refId": "A"
            }],
            "thresholds": [],
            "timeFrom": null,
            "timeRegions": [],
            "timeShift": null,
            "title": "PIng RTT",
            "tooltip": {
                "shared": true,
                "sort": 0,
                "value_type": "individual"
            },
            "type": "graph",
            "xaxis": {
                "buckets": null,
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
            },
            "yaxes": [{
                "format": "s",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
            }, {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
            }],
            "yaxis": {
                "align": false,
                "alignLevel": null
            }
        }],
        "schemaVersion": 21,
        "style": "dark",
        "tags": [],
        "templating": {
            "list": []
        },
        "time": {
            "from": "now-6h",
            "to": "now"
        },
        "timepicker": {
            "refresh_intervals": [
                "5s",
                "10s",
                "30s",
                "1m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "1d"
            ]
        },
        "timezone": "",
        "title": "TEST 2"
    },
    "folderId": 0,
    "overwrite": false
}`

**Anything else we need to know?**:
Removing "schemaVersion" from the JSON, the dashboard is ok and the graph is shown.
I'm using "schemaVersion" because of #21115

**Environment**:
Grafana version: 6.5.2

**Comment by dprokop** [comment]
@limo49 please specify an id (i.e. `"id": 1`) of your panel in the JSON that you send. Remember that if you create dashboard with multiple panels the ids of the panels should be unique.
