### ISSUE TITLE
Explore: parenthesis added by auto completion conflict while typing a straight query

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#21161]
**What happened**:

In the Explore, while typing a straight Prometheus query, auto completion triggers to add closing parenthesis. These added parenthesis conflict with the user just typing a straight query and force the user to use keyboard arrows while typing to move the cursor after the added parenthesis before continuing writing the query.

For example, if I just try to type a valid query `sum(up) by(cluster)` the query will end up be `sum(up) by(cluster)))` (two additional closing parenthesis at the end):
![2019-12-18 10 31 57](https://user-images.githubusercontent.com/1701904/71074729-11b92480-2183-11ea-93ec-570246a90a8d.gif)

**What you expected to happen**:

When typing a closing parenthesis, it should advance the cursor instead of inserting the parenthesis if the parenthesis was added by autocompletion.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Explore and select a Prometheus data source
2. Go straight typing `sum(up) by(cluster`
3. The resulting query is invalid

**Environment**:
- Grafana version: `v6.6.0-pre (e9079c3faa)`
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: OSX 10.13.6 & Chrome 79.0.3945.79
- Grafana plugins: N/A
- Others: N/A

**Comment by aocenas** [comment]
cc @davkal 

That makes sense on the other hand even in IDEs like Goland/Webstorm I sometimes get frustrated with the add parenthesis or skip parenthesis behaviour (maybe only issue with bit more parenthesis nesting). In any case may be worth considering removing auto-adding the closing parenthesis? I could genuinely live without it in any context I can think of.
