### ISSUE TITLE
Duplicated legends for different metrics from influxdb source

### ISSUE THREAD

**Issue by yang-zhang** [grafana/grafana#2116]
Using Influxdb v0.9.

In a graph,

Metrics1:
SELECT Value1 FROM SOME_MEASUREMENT WHERE device_id='$device_id'
Metrics2:
SELECT Value2 FROM SOME_MEASUREMENT WHERE device_id='$device_id'

Instead of "Value1" and "Value2", the legends for both metrics are "SOME_MEASUREMENT".

Is there a way to set distinct legends for different metrics generated from the same influxdb measurement?

**Comment by torkelo** [comment]
Yes, use the alias field

**Comment by torkelo** [comment]
Oh,  see you specified you use influx 0.9 , alias feature was added last week I think. influx 0.9 support is still alpha level, so no all issues should  e reported to the influx 0.9 issue
