### ISSUE TITLE
Docs feedback: /installation/debian.md

### ISSUE THREAD

**Issue by 0xphk** [grafana/grafana#21169]
Hi, the "Next steps" section in https://grafana.com/docs/grafana/latest/installation/debian/ links/refers to the "Getting started" page in https://grafana.com/guides/getting_started/ which gives just a 404/dead link. The correct link should be https://grafana.com/docs/grafana/latest/guides/getting_started/ I think.

**Comment by dprokop** [comment]
@oddlittlebird is this something you can take care of? :)

**Comment by oddlittlebird** [comment]
Good catch, @0xphk ! I will take care of it.
