### ISSUE TITLE
templating for individual rows

### ISSUE THREAD

**Issue by bcmackey** [grafana/grafana#2117]
my use case is that I would like a row in grafana, where I create the graph once with a template variable, and it fills in the rest of the row with a separate graph for each item in the template.

I might have a graphite series like frontend.latency.percentages.{p50, p90, p99}. I'd love to create a template on the 4th variable and have it create three graphs in the row - one for p50, p90 and p99.

**Comment by nopzor1200** [comment]
Hi @bcmackey. Totally agree that this is a very powerful concept that belongs in Grafana. Infact, check out grafana#1888 - work has already begun on such a feature and it's starting to look good. Curious if this meets your use case (I think it should).
