### ISSUE TITLE
Link from Embed -> Embed hangs with "Loading & initializing dashboard"

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#21180]
**What happened**: I used an iframe embed `/d-solo/` in an application with a table that links to another embedded panel.

![d-solo](https://user-images.githubusercontent.com/814226/71118825-d6c8e800-21a6-11ea-996b-504f49ef5744.png)

When clicking the link, the new page hangs indefinitely with "Loading & initializing dashboard"

![d-solo-click](https://user-images.githubusercontent.com/814226/71118875-ef390280-21a6-11ea-8a92-09531edc3aad.png)

**What you expected to happen**: The linked panel opens when clicked

**How to reproduce it (as minimally and precisely as possible)**:

1) Create table with link to another panel Embed
2) Open share link to Embed of this table
3) Click link in table

**Anything else we need to know?**:

Seems to happen on `/d-solo/` -> `/d-solo/` but not `/d-solo` -> `/explore` or `/d/` -> `/d-solo/`. If you subsequently refresh the page it loads correctly, so it's some issue where the link is not actually reloading the page but trying to shortcut.

**Environment**:
- Grafana version: v6.4.2
- Data source type & version: custom in-house datasource
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: macOS Catalina, Safari 13.0.3
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@timpalpant is there anything in the console when you go to this dashboard which hangs?

**Comment by torkelo** [comment]
closing due to lack of details

**Comment by linuxmail** [comment]
Hello,

I have the same issue for a long time. I thought, it's a problem with the [Icingaweb2 Grafana module](https://github.com/Mikesch-mp/icingaweb2-module-grafana) but now I see, I'm not alone. I've checked the logs, but nothing found. It takes around 10-20secs, than the graph appears.

cu denny

**Comment by aledr** [comment]
@linuxmail Did you find a solution for it?
Also running [IcingaWeb2 Grafana](https://github.com/Mikesch-mp/icingaweb2-module-grafana).

influxdb2-2.0.6
grafana-7.5.7
