### ISSUE TITLE
PostgreSQL sessions

### ISSUE THREAD

**Issue by scbunn** [grafana/grafana#2118]
It looks like users and dashboards can be stored in a PostgreSQL instance; however, session information does not appear to support PostgreSQL.

**Comment by scbunn** [comment]
I found the correct provider config to use for PostgreSQL
```
  ProviderConfig: "user=a password=b host=localhost port=5432 dbname=c sslmode=disable"
```

**Comment by torkelo** [comment]
btw, have updated the sample config with an example, and the config docs as wel
