### ISSUE TITLE
Graphic curve does not match actual data!

### ISSUE THREAD

**Issue by vicentwu** [grafana/grafana#21182]
**What happened**:
My back-end data source is zabbix4.0. When I use the Graph plugin, there are multiple data curves, and one of the displayed data values does not match the actual one. When I only choose to view the data curve, the data is normal, but The data value of the line is wrong when displaying multiple lines, and the data value displayed when I mouse over the curve is also correct.

**What you expected to happen**:
![TIM图片20191219105830](https://user-images.githubusercontent.com/36059301/71141296-ac326a00-224e-11ea-8a44-9addef0ab3a6.png)
![TIM图片20191219105923](https://user-images.githubusercontent.com/36059301/71141302-af2d5a80-224e-11ea-8c5b-9ab64719e958.png)
![TIM图片20191219105928](https://user-images.githubusercontent.com/36059301/71141306-b0f71e00-224e-11ea-84b7-6c9dcf5eb254.png)
I think this is BUG?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.5
- Data source type & version: zabbix4.0
- OS Grafana is installed on: centos7.4
- User OS & Browser: chrome79
- Grafana plugins:Graph
- Others:

**Comment by torkelo** [comment]
I think you have enabled stacking

**Comment by vicentwu** [comment]
thank you very much！！
