### ISSUE TITLE
Feature to schedule table dashboard data in csv and send mail

### ISSUE THREAD

**Issue by anandtripathi5** [grafana/grafana#21187]
**What would you like to be added**:

There is feature in Grafana for data table panel we can export it as CSV. I want to export the CSV and send it in the email(can use the existing alerting feature). Additionally, can we schedule this export CSV to email like a CRON or some sort of scheduler?

**Why is this needed**:

**Comment by dprokop** [comment]
@anandtripathi5 can you elaborate more what you would like to be added?

**Comment by anandtripathi5** [comment]
There is feature in Grafana for data table panel we can export it as CSV. I want to export the CSV and send it in the email(can use the existing alerting feature). Additionally, can we schedule this export CSV to email like a CRON or some sort of scheduler?

**Comment by dprokop** [comment]
@anandtripathi5 ok, thanks for making this clear. We don't have plans to implement this feature now, but let's see if this gets any upvotes.

**Comment by bhaveshgohel** [comment]
Hi @anandtripathi5, i have the same requirement as your. Are you able to find any solution for the problem?

**Comment by anandtripathi5** [comment]
Nope, currently not supported by Grafana. For now we are using some other
paid solution.

**Comment by codeincarnate** [comment]
This feature actually [does exist](https://grafana.com/docs/grafana/latest/dashboards/create-reports/), that being said it's part of Grafana Enterprise. That being the case, it's unlikely that this will be a part of the OSS version in the near future. If that changes we can re-open this one 😄.
