### ISSUE TITLE
Alerting: consistently use same conversion 

### ISSUE THREAD

**Issue by sFreezer** [grafana/grafana#21195]
**What would you like to be added**:
currently the values in the alerts are not converted in the same as on the dashboard.

for example: we track delays. these could look like '1363.9377750876' which would translate to 22 minutes 43 seconds. the dashboard would show 22.7 min.

**Why is this needed**:
that would dramatically increase readability and consistency

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
