### ISSUE TITLE
azuremonitor: Allow specifying a Legend Format in Application Insights' Text Edit mode

### ISSUE THREAD

**Issue by christianrondeau** [grafana/grafana#21207]
This has been implemented in https://github.com/grafana/azure-monitor-datasource/issues/2 for Application Insights queries, but the Text edit mode (the small pen icon allowing custom Kusto queries for Application Insights) does not have that field, which makes it impossible to specify custom legends.

This is needed because otherwise, the labels are lengthy and makes the graph harder to read.

**Comment by yesoreyeram** [comment]
Why can't you use use `project` feature of kusto query? The text mode of appinsights should work same way as log analytics. I am curious to understand the use case.

**Comment by christianrondeau** [comment]
That's what I'm doing right now but fields look like this in the graph: `{projectionName=Value}.fieldName` instead of simply `Value`, which would be much easier to ready and smaller. I can do exactly that using the Legend Format field, which is why having it in text edit mode would be useful. Hope that helps!

**Comment by kyschouv** [comment]
We're also experiencing this after updating. It used to just show the value of the "split on" column in the legend, but now it's formatting like @christianrondeau mentions above. Could we please return to the previous behavior?

**Comment by MitchBomcanhao** [comment]
Still an issue - used to work fine, now we've had to rewrite all our queries to have single character names in the values to split and count on, so that our labels look somewhat readable, ie {a=LABEL}.c
it would just show LABEL on a previous version.

**Comment by FortDigital** [comment]
Also having this issue, im using the transforms in 7.0.x (outer Join > Organize Fields) as a workaround but this only works if you have a defined set of values, as soon as theres a new value it formats the 'wrong' way again until someone edits the dashboard.

Default behaviour:
![image](https://user-images.githubusercontent.com/62287745/84896852-96d2b700-b09c-11ea-834e-14d6142854f0.png)

Workaround:
![image](https://user-images.githubusercontent.com/62287745/84896983-d0a3bd80-b09c-11ea-929f-0c4f52aa4ffe.png)

**Comment by andrea-cassioli-maersk** [comment]
Same here, I wonder what is the status. It seems just a bug to me: I would bet that the substitution template does not get expanded but simply printed out.

**Comment by sunker** [comment]
We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics). I'm closing this issue now, but feel free to reopen if you feel the need to.
