### ISSUE TITLE
Azure Log Analytics only supports a single response table

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#21206]
**What happened**:
Azure Log Analytics query from Grafana only returns a single time series data set. Same query in Azure portal returns two data sets.

In this case, new failure rate and existing failure rate should be displayed in Grafana:
![image](https://user-images.githubusercontent.com/1184220/71211669-84bbbb80-22a7-11ea-83c4-8f0dbb8c55ac.png)

Azure:
![image](https://user-images.githubusercontent.com/1184220/71211720-a2892080-22a7-11ea-8cb8-fe25d756cde0.png)

**What you expected to happen**:
Both data sets to be returned and displayed on the Graph Panel.

**How to reproduce it (as minimally and precisely as possible)**:
* Create Grafana Graph Panel
* Azure Monitor (Log Analytics) data source
* Set Service: Azure Log Analytics
* Copy the below query and replace variables in two locations to replicate. Exact same code works in the Azure Portal under Log analytics. 

```
let timeRange = 1d;
let grain = 30m;
let bigWindowTimeRange = 7d;
let existingFailures = app('/subscriptions/$subscriptions/resourceGroups/$resourcegroups/providers/$namespace/$resourcenames').requests
| where timestamp >= ago(bigWindowTimeRange) and timestamp < bin(ago(timeRange), grain)
| where operation_Name in ('*') or '*' in ('*')
| where name in ('*') or '*' in ('*')
| where resultCode in ('*') or '*' in ('*') or iff('@' in ('*'), resultCode startswith '5', false) or iff('#' in ('*'), resultCode startswith '4', false)
| extend Key = strcat(name, '-', resultCode)
| summarize makeset(Key, 10000);
app('/subscriptions/$subscriptions/resourceGroups/$resourcegroups/providers/$namespace/$resourcenames').requests
| where timestamp >= bin(ago(timeRange), grain)
| where operation_Name in ('*') or '*' in ('*')
| where name in ('*') or '*' in ('*')
| extend IncludeInFailures = resultCode in ('*') or '*' in ('*') or iff('@' in ('*'), resultCode startswith '5', false) or iff('#' in ('*'), resultCode startswith '4', false)
| extend Key = strcat(name, '-', resultCode)
| summarize NewFailures = countif(success == false and Key !in (existingFailures) and IncludeInFailures), ExistingFailures = countif(success == false and Key in (existingFailures) and IncludeInFailures), All = count() by bin(timestamp, grain)
| project timestamp, ['New Failure Rate (%)'] = 100.0 * NewFailures / All, ['Existing Failure Rate (%)'] = 100.0 * ExistingFailures / All
| project timestamp, ['New Failure Rate (%)'], ['Existing Failure Rate (%)']
| order by timestamp asc
```

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Azure Log Analytics
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Win10/Chrome

**Comment by bhozar** [comment]
Do you need any additional info on this one?

**Comment by kylebrandt** [comment]
Currently the Azure Kusto style data sources (Log analytics, App Analytics, Data Explorer) only support one table in a response.

There are two workarounds for this:

1. Make two queries from Grafana:

![image](https://user-images.githubusercontent.com/1692624/95355505-a0726b80-0893-11eb-97c9-e2bf5aec28ce.png)

2. Do a join on the two tables, to make one table:

![image](https://user-images.githubusercontent.com/1692624/95355579-b122e180-0893-11eb-8262-478643afe7e5.png)

**Comment by kylebrandt** [comment]
For reference, the code that does this is:

https://github.com/grafana/grafana/blob/98b94d3824dfa084c2f728fdbc7558c0cd058776/pkg/tsdb/azuremonitor/azure-log-analytics-datasource.go#L254-L262

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
