### ISSUE TITLE
importing metrictank dashboard doesn't work

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#21202]
on our internal admin-ops-tools1 grafana (master one), when I go to add a datasource of type graphite, and go to the dashboards tab, i can import the carbon dashboard just fine, but when I hit import for the metrictank dashboard I get the error:

"Failed to import dashboard".

When I look at the grafana logs, I see : 
```
t=2019-12-19T17:32:13+0000 lvl=eror msg="Failed to import dashboard" logger=context userId=0 orgId=1 uname= error="The dashboard has been changed by someone else"
t=2019-12-19T17:32:13+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/dashboards/import status=500 remote_addr=10.15.0.47 time_ms=5 size=40 referer=https://censored/grafana/datasources/edit/9/dashboards
```

The instance does not have any other dashboard called "Metrictank", btw.

So there's several problems here:
1) the import doesn't work
2) the error message is not shown in the UI, i have to dig in the log output
3) the error message is imprecise. "changed by someone else". huh? when importing a dashboard from a datasource?

**Comment by Dieterbe** [comment]
I can reproduce something similar, but with a different error when i run a local docker image:
```
docker run -p 3000:3000 grafana/grafana:master
```
also says "Failed to import dashboard" in the UI for the metrictank dashboard, but the logs say:

```
t=2019-12-19T18:40:40+0000 lvl=eror msg="Failed to import dashboard" logger=context userId=1 orgId=1 uname=admin error="Dashboard not found"
t=2019-12-19T18:40:40+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/import status=500 remote_addr=172.17.0.1 time_ms=6 size=40 referer=http://localhost:32769/datasources/edit/1/dashboards
```

**Comment by ryantxu** [comment]
I can reproduce... and will investigate -- it looks like there are some props that should not be included:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/dashboards/metrictank.json#L36

Do you have a dashboard you think is good?

**Comment by Dieterbe** [comment]
> Do you have a dashboard you think is good?

No. The dashboard should be the same as https://grafana.com/grafana/dashboards/279 which is the same as https://github.com/grafana/metrictank/blob/master/dashboards/main/metrictank.json

Seems like all of them should be fixed. (I can port your fixes back)
