### ISSUE TITLE
Grafana not rendering influxDB

### ISSUE THREAD

**Issue by nicocesar** [grafana/grafana#2120]
I'm using 
Grafana 2.0.2
InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)

I define a graph and test out 2 almost similar queries, one works and the other one doesn't 
WORKS: 
select sum(bytes_free) from "keep" where $timeFilter group by time($interval) order asc
DOESNT WORK:
select sum(bytes_free),hostname from "keep" where $timeFilter group by time($interval),hostname order asc

I can see the network traffic that both get responses ~3kb and 18kb of data.

![grafana_not_rendering_1](https://cloud.githubusercontent.com/assets/425081/8008265/0d174b34-0b6f-11e5-95c4-efc51087b4be.png)
![grafana_not_rendering_2](https://cloud.githubusercontent.com/assets/425081/8008266/0d17c7d0-0b6f-11e5-820b-901129796b98.png)
![grafana_not_rendering_3](https://cloud.githubusercontent.com/assets/425081/8008264/0d172730-0b6f-11e5-8efe-3adf817905f7.png)
![grafana_not_rendering_4](https://cloud.githubusercontent.com/assets/425081/8008267/0d1c1b6e-0b6f-11e5-8a30-c3969d48b97c.png)

Are there any limits on size that I might be bumping into?

**Comment by torkelo** [comment]
looks like `select sum(bytes_free),hostname from "keep" where $timeFilter group by time($interval),hostname order asc` is invalid, should not be possible to group by without having an aggregate for hostname. Anyway you should have hostname in the select clause, each query should only return one value.

**Comment by torkelo** [comment]
Updated the above comment with a NOT before hostname :)

**Comment by nicocesar** [comment]
hi @torkelo, I appreciate the lighting fast response! Great job you're doing here! 

what do you mean by "invalid"? it's a valid influxDB query just like the one below. So I'm assuming you're refering to "it's an invalid Grafana Input". Please correct me if I misunderstood  that statement.

<pre>
select sum(bytes_free) from "keep" where $timeFilter group by time($interval),hostname order asc
</pre>

In the last query I can see the response will include column  ["time", "sum", "hostname"] too. 

Just because it has the extra column "hostname" isn't possible to render? If so, I guess my workaround will be to create a query PER hostname. Correct? 

Thanks again.
