### ISSUE TITLE
InnoDB for use with provider config

### ISSUE THREAD

**Issue by maroda** [grafana/grafana#2121]
I'd like to load balance between multiple grafana front-ends for HA, and am looking at the mysql provider, but noticed the required table uses myisam. The 'data' field is a BLOB so I'm assuming there might be a good reason for that.

But my backend database is a galera cluster, which only supports innodb.

Will provider still work if I make that table innodb? Would there be reduced functionality?

**Comment by torkelo** [comment]
As long as it supports mysql sql connection string and dialect it should work fine

**Comment by maroda** [comment]
Seems to be working with innodb fine, no problems so far. Thanks!
