### ISSUE TITLE
Support send WeCom alert message

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#21211]
**What would you like to be added**:
[WeChat Work](https://work.weixin.qq.com/) is a popular IM in china for working.
We can add an message webhook for it.
**Why is this needed**:
make more friendly to WeChat Work user

**Comment by marefr** [comment]
Duplicate of #12333

**Comment by zengxs** [comment]
I think this is not duplicate, **Wechat Work** and **Wechat** are two different apps.

**Comment by okhowang** [comment]
WeChat Work has been renamed to WeCom

**Comment by davywangsz** [comment]
Yeah， now wechat-work renamed to WeCom, its very very polular in China.
i hope grafana could support it.
