### ISSUE TITLE
Timepicker: add possibility to select time within a day from the calendar

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#21210]
**What would you like to be added**:
To make it easier to select time range during a day we should improve the calendar by adding a time selector. Please see the following examples here: https://material-ui-pickers.dev/demo/datetime-picker

**Why is this needed**:
During the demo of the TimePicker we got feedback that it would have been really good to add the possibility to select a time range. @jessover9000 suggested that we implement pattern linked above.

https://github.com/grafana/grafana/pull/20931#issuecomment-567539275

**Comment by ryantxu** [comment]
Also check:
http://react-component.github.io/calendar/examples/antd-range-calendar.html

**Comment by rntbrgtt** [comment]
Can I please ask to also provide this feature on individual panels within the dashboard ? We have this now as "Panel time overrides and timeshift".

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
