### ISSUE TITLE
Explore: Prometheus metric auto-completion invalid replacement

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#21219]
**What happened**:

Sometimes the metric name auto-completion leaves the metric name composed by a part of the typed metric + the actual metric name, like this:

![2019-12-20 18 21 42](https://user-images.githubusercontent.com/1701904/71277756-11bd4e00-2356-11ea-9ffe-ee093d166de2.gif)

**What you expected to happen**:

To correctly replace the entire metric name.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open the Explore and select a Prometheus data source
2.  Type `container_memory_usage` and then press enter to auto complete with `container_memory_usage_bytes`
3. You will get something like `container_memorcontainer_memory_usage_bytes`

**Environment**:
- Grafana version: `v6.6.0-pre (22ff0eab15)`
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: OSX 10.13.6 & Chrome 79.0.3945.88
- Grafana plugins: N/A
- Others: N/A

**Comment by hugohaggmark** [comment]
Thanks @pracucci
