### ISSUE TITLE
6.5.2 Filters not working for CloudWatch dimension_values

### ISSUE THREAD

**Issue by jveldboom** [grafana/grafana#21215]
**What happened**:
After upgrading from 6.4.2 to 6.5.2, we noticed the filters parameter for `dimension_values()` seems to be ignored and instead returns all the results.

For example, this query will ignore the `FunctionName` filter and return every Lambda function in our account.
```
dimension_values(us-east-1,AWS/Lambda,Invocations,FunctionName, {"FunctionName": "jveldboom"})
```

**What you expected to happen**:
We expected the filter parameter to narrow down the search results.

**Environment**:
- Grafana version: v6.5.2
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome

**Comment by polak785** [comment]
Hello,

Indeed I just figured it out with this post that I have this bug too with the latest version `6.5.2`.

+1 to fix this please.

**Comment by sunker** [comment]
Great that you found this @jveldboom! I just opened a PR to fix this. Hopefully it will go in 6.5.3 
Thanks!
