### ISSUE TITLE
Feature request: Allow selecting plots to view/hide in multi-plot Graph panel

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#21228]
**What would you like to be added**: In cases when multiple parameters are being plotted using the Graph panel, the currently available option to view/hide plots is either view one or view all, while there is no option to select more than one but not all plots to view.

**Why is this needed**: In situations where there are 3 or more plots within a Graph panel and it is necessary to compare 2 plots out of the 3 or more, there is currently no means to do so.

**Comment by hugohaggmark** [comment]
Hi @anirudh-ramesh , have you tried to CTRL/CMD click on graph series in Graph legend? Will that suffice or are you looking for another solution?
![toggle-graph-series](https://user-images.githubusercontent.com/562238/71340948-ae4f3e00-2558-11ea-83b7-5972d4c9285d.gif)

**Comment by anirudh-ramesh** [comment]
Hi, @hugohaggmark, thanks for the tip - this is what I was looking for at the moment, and I had missed the detail in the documentation of the Graph panel.
