### ISSUE TITLE
Dashlist doc link is broker in dashlist panel help section

### ISSUE THREAD

**Issue by vikkyomkar** [grafana/grafana#21229]
**Steps to reproduce**: 
1. Select "dashboard list panel" for visualisation 
2. Click on <**?**> to expand the help section
3. Open on the doc link given at the bottom of it

![image](https://user-images.githubusercontent.com/25223784/71307729-a8524380-2418-11ea-8539-5cb42bfe550e.png)

**Actual Result**: 
Current link is taking me to broken page https://grafana.com/docs/grafana/latest/reference/dashlist/

**Expected Result**
This link should take me to correct dashlist docs page
i.e. https://grafana.com/docs/grafana/latest/features/panels/dashlist/

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: V6.5
- Data source type & version: 
- User OS & Browser: macOS & chrome
- Others:

**Comment by vikkyomkar** [comment]
#21230

**Comment by hugohaggmark** [comment]
Hi @vikkyomkar thanks for taking the time to improve our docs.
