### ISSUE TITLE
Question : Include a graph on an external webiste ?

### ISSUE THREAD

**Issue by Esysteme** [grafana/grafana#2122]
Hello,

I would to know, if it's possible to export a graph to a website ?

Aurélien

**Comment by torkelo** [comment]
you can click on a graph and then the share menu, from there you can either render the graph as PNG image that is easy to include on a website, or you can use the iframe embed feature, where you can embed an interactice graph via an iframe, http://docs.grafana.org/guides/whats-new-in-v2/#panel-iframe-embedding

**Comment by Esysteme** [comment]
I don't want add a static file, I wanna add a dynamic one in JS (without  iframe).

thx for answer

**Comment by torkelo** [comment]
dynamic one without iframe is not possible :( , Grafana is not a js library,  it is a complex application with backend and frontend components

**Comment by Esysteme** [comment]
what lib you use to display graph, or it's totallty own made ?

**Comment by torkelo** [comment]
I use flotcharts

the legend and graph hover tooltip is handled in by grafana code
