### ISSUE TITLE
Grafana plugin can't be installed : grafana-image-renderer

### ISSUE THREAD

**Issue by AsherXian903** [grafana/grafana#21235]
**What happened**: Grafana plugin can't be installed : grafana-image-renderer

**What you expected to happen**: install renderer plugin: grafana-image-renderer

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: can't install grafana-image-renderer with the command: grafana-cli plugins install grafana-image-renderer, can't download from url either(https://grafana.com/api/plugins/grafana-image-renderer/versions/1.0.7/download)

**Environment**:
- Grafana version:6.5.2
- Data source type & version:Prometheus
- OS Grafana is installed on:CentOS
- User OS & Browser:Mac Firefox
- Grafana plugins:grafana-image-renderer
- Others:

**Comment by hugohaggmark** [comment]
Thanks @AsherXian903 for reporting this, we're looking it to it!

**Comment by hugohaggmark** [comment]
Sorry for the inconvenience but we're having some issues with all the  downloads for this plugin. Can you try to downloaded using any of the download links here [https://github.com/grafana/grafana-image-renderer/releases/tag/v1.0.7](https://github.com/grafana/grafana-image-renderer/releases/tag/v1.0.7)?

**Comment by AsherXian903** [comment]
> Sorry for the inconvenience but we're having some issues with all the downloads for this plugin. Can you try to downloaded using any of the download links here https://github.com/grafana/grafana-image-renderer/releases/tag/v1.0.7?

the links you offered work out, thank you so much, still looking forward to the issue to be handled!

**Comment by hugohaggmark** [comment]
Great to hear @AsherXian903, as so many others we also are entering the holiday season so expect solving this issue to be a bit slower. Merry holidays!

**Comment by hugohaggmark** [comment]
@AsherXian903 if you have the time please check if this is working now so that we can close this issue.

All the best

**Comment by AsherXian903** [comment]
> @AsherXian903 if you have the time please check if this is working now so that we can close this issue.
> 
> All the best

the release works perfect, thx!!!

Best Regards
