### ISSUE TITLE
DingTalk may support AtAll feature

### ISSUE THREAD

**Issue by qixiaobo** [grafana/grafana#21236]
We use DingTalk robot for grafana alerting.
But we may found this not include AtAll feature while DIngTalk doc support.
![image](https://user-images.githubusercontent.com/2881751/71338606-82997b80-258b-11ea-88c4-238ee0fd6869.png)
https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq
isAtAll is very useful

**Comment by hugohaggmark** [comment]
Hi @qixiaobo I'm not sure that I follow what you're asking here. We try to use GitHub for issues and feature requests only for questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
