### ISSUE TITLE
Feature Request: "Render value as link" and Contextual Menu

### ISSUE THREAD

**Issue by juaromu** [grafana/grafana#21232]
Would it be possible to define several, different links when the option "Render value as link" is selected and render that as a contextual menu so that more than one dashboard would be available for selection and passing along the variable in the cell field?

Several use cases come to mind, but in general this would allow a quick access to more than one dashboard where the value in the cell could be used as input variable in other visualisations/dashboards.

Thanks!

Juan.

**Comment by hugohaggmark** [comment]
Thanks @juaromu, for this to become a feature request that we'll look into It would be awesome if you can give even more details about the scenarios you're mentioning and maybe some screenshots/mockups of the feature at hand.

**Comment by juaromu** [comment]
Hi Hugo:

Thanks for getting back.

Some scenarios I'm using Grafana for at the moment and where I'd find this feature really useful:

1.- ZEEK/BRO Network Traffic Analysis: Bro breaks down and stores all traffic flows in different log files (conn.log, http.log. ssl.log, etc) where the specifics of each connection type can be found. I have several Dashboards in Grafana following this schema and also a threat intel plugin where, once an IP address has been flagged by the security feed, a link in the rendered value will take you to Cisco Talos for the details on the threat. It'd be nice if more than one option for that link would be available, being able to take you to Talos (as per now) or directly to the relevant Dashboard for Zeek, passing along that IP address as a variable to see the specifics of that potential threat related to the type of connection being made (if it was HTTP, SSL, etc). In this scenario, the option of a context menu quickly came to mind where after clicking the hyperlink a contextual menu would pop up with the different links available for that cell.
So, right now, it looks like this:

![image](https://user-images.githubusercontent.com/31524992/71379205-95a95b80-261e-11ea-818e-86a1f3278cce.png)

The idea would be being able to define more than one link and render that as a context menu after clicking.

2.- In that same deployment I also use Grafana to show my IT inventory (via Open-Audit and the MySQL plugin in Grafana), plus Zabbix to monitor my Infra plus OSQUERY to run audits on system processes, open sockets, etc.). From the inventory visualisation (dashboard) and for each hostname I'd like to being able to jump to my Zabbix dashboard using the hostname as variable or go to the OSQUERY gasboard, again with the same variable. 
Here, again, I find a context menu available after clicking a quick way of achieving this.

Hopefully this will clarify my use cases, but let me know if anything.
Thanks again!

Juan.

**Comment by ryantxu** [comment]
Thanks @juaromu -- check the dev under the new table panel ([table2](https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/table2)).  It will use the same DataLink API to generate links.  

If that is not what you are looking for... add some more details and a possible solution.  Thanks
