### ISSUE TITLE
Alert rule not works with query that have another query referenced on Expression by ID

### ISSUE THREAD

**Issue by augustocadini** [grafana/grafana#21248]
Grafana 6.5.2

**Goal**
Make a alert from query using Graph.

**Scenario**
I've 4 queries (A,B,C and D). The query called 'D' get your value from a Expression using the another 3 queries. So, I want create a alarm based on the D's value.

![screenshot_3](https://user-images.githubusercontent.com/18659348/71375298-7ec22500-259c-11ea-8918-d01dcf171a9b.png)

**Problem**
When I try use  the "Test Rule" on the Alarm screen, get the error: `Error in expression 'rate': ID 'total_count' not found status code: 400`. Not just `total_count`, but the other variables are not found too. So, at this point I can't send a webhook to my endpoint. When the conditions are satisfied the webhook is not sent.

![screenshot_4](https://user-images.githubusercontent.com/18659348/71374802-d8295480-259a-11ea-8e28-6f90be284e2c.png)

**Comment by torkelo** [comment]
this scenario is currently not supported, https://github.com/grafana/grafana/issues/19886
