### ISSUE TITLE
Grafana does not use time range from dashboard for fetching variables

### ISSUE THREAD

**Issue by khrupalyk** [grafana/grafana#21253]
**What happened**: 
Variables which defined as Query type always fetched with 0 time stamp (Mon Jan 19 1970 06:06:20)
**What you expected to happen**:
When I changed time range on dashboard, variables should be fetched by this current range.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create variable with type Query and use Graphite datasource: stats.timers.$Application.*
2. Go to dashboard which use this query and chose some time range. 
3. You will see all values for all times.

**Anything else we need to know?**:

When I'm selecting variable on my dashboard I see that Grafana makes two calls, one for annotations:

`api/annotations?dashboardId=1&from=1577108447653&to=1577108747653`

And one for metrics:

`api/datasources/proxy/1/metrics/find?from=1577108446&until=1577108748`

But for second call Grafana uses always the same time (Mon Jan 19 1970). But should be used time range which I selected on my dashboard.

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Graphite 1.1.5
- OS Grafana is installed on:  Alpine
- User OS & Browser: Mac OS/Google Chrome

**Comment by torkelo** [comment]
Make sure your variable has the refresh option "On Time Range Change" if you want it to be time range dependant

**Comment by khrupalyk** [comment]
Yes, all variables have this option.

**Comment by torkelo** [comment]
Ok, for me i see from=1577108446&until=1577108748 in your metric find (variable query) so it seems to work fine

**Comment by khrupalyk** [comment]
Yes, but I setup current time, let say from=-5m & until=now, but 1577108446 is equal to Mon Jan 19 1970.

**Comment by khrupalyk** [comment]
While query for annotations use the right time.

**Comment by torkelo** [comment]
Graphite uses epochs in seconds not milliseconds

**Comment by khrupalyk** [comment]
Thanks, I will investigate that. Maybe problem with graphite or my metrics.
