### ISSUE TITLE
[dashboard] "Azure Monitor for Containers - Metrics" - 404 errors when using Azure data source

### ISSUE THREAD

**Issue by rhollins** [grafana/grafana#21254]
**What happened**:

The dashboard (https://grafana.com/grafana/dashboards/10956) shows "query error" on every panel.

The Azure data source works fine and also the query which grafana tries to issue works properly when running on log analytics workspace.

To get this to work I had to for every panel click on "Edit" and then just run query manually than when I come back to dashboard error is no longer there, so the problem is when you import dashboard initially.

Seems to be similar to #19722 

```
error:Object
message:"The requested path does not exist"
code:"PathNotFoundError"
status:404
headers:function(n){…}
config:Object
method:"GET"
transformRequest:Array[1]
transformResponse:Array[1]
paramSerializer:function(t){…}
jsonpCallbackParam:"callback"
url:"api/datasources/proxy/1/sameasloganalyticsazure//query?query=%0DKubePodInventory%20%0A%0D%7C%20where%20ClusterId%20%3D%3D%20'%2Fsubscriptions%<SUBSCRIPTION>%2FresourceGroups%2F<RESOURCE_GROUP>%2Fproviders%2FMicrosoft.ContainerService%2FmanagedClusters%2F<CLUSTER_NAME>'%0A%7C%20where%20TimeGenerated%20%3E%3D%20datetime(2019-12-24T07%3A38%3A00.000Z)%0A%7C%20summarize%20count()%20by%20bin(TimeGenerated%2C%201m)%2C%20PodUid%2C%20Namespace%0D%0A%7C%20summarize%20arg_max(TimeGenerated%2C%20*)%20by%20PodUid%2C%20Namespace%0D%0A%7C%20summarize%20namespaceCount%20%3D%20count()%20by%20Namespace%0D%0A%7C%20sort%20by%20namespaceCount%20desc%0A%7C%20project%20namespaceCount%2C%20Namespace%2C%20now()%20"
retry:0
```
I noticed that workspace id is bit that's missing from query above, when I use azure data source and query log analytics directly I can see following url:

```
Object
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/4/sameasloganalyticsazure/<WORKSPACE_ID>/query?query=ContainerInventory%0D%0A%7C%20limit%201"
```

**What you expected to happen**:

All panels in dashboard should show metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Install grafana from helm chart in AKS cluster which has monitoring enabled on log analytics workspace.
Configure Azure data source in grafana and point to AKS log analytics workspace.
Import dasboard json file from https://grafana.com/grafana/dashboards/10956

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Azure 0.3.0
- OS Grafana is installed on: AKS 1.14.8
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks @rhollins for reporting this, we'll have a look at this but as we're in the middle of holiday season progress might be slow.

All the best

**Comment by sunker** [comment]
Thanks for reporting this issue @rhollins and sorry for the late reply! 

I'm assuming the dashboard model has been updated at some point, causing this error in the dashboard. However, we don't maintain the dashboards at grafana.com, and it seems like this is maintained by an external contributor. I'm gonna close this issue now, but feel free to re-open it if you feel the need to. 

Again, sorry for not getting back to you sooner.
