### ISSUE TITLE
Explore: Tooltip display may break when query is too long

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#21266]
**What happened**:

tooltips display abnormal
![image](https://user-images.githubusercontent.com/3352585/71501673-b5eb4b80-28a6-11ea-8cd2-066e2e83f27d.png)
value is disappeared
actually value is push out of div
![image](https://user-images.githubusercontent.com/3352585/71501745-082c6c80-28a7-11ea-8d03-73143c373995.png)

**What you expected to happen**:

display value correctly
![image](https://user-images.githubusercontent.com/3352585/71501694-c4d1fe00-28a6-11ea-8614-b32575dd06bf.png)

**How to reproduce it (as minimally and precisely as possible)**:
make a very long query

**Anything else we need to know?**:
main reason may be `SeriesTable` has no parent `display: table` element
I try add `display: table` for `TooltipContainer` and it's resolved

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: windows
- User OS & Browser: chrome
- Grafana plugins: none
- Others:

**Comment by hugohaggmark** [comment]
Thank you @okhowang for reporting this, I can indeed repro this in 6.5.0 and 6.5.2 but it seems to be fixed in latest master so a fix should be on it's way.

**Comment by okhowang** [comment]
I also test on master, it's remain appear

**Comment by okhowang** [comment]
it's like to be a problem of word-wrap on SeriesTableRow's cell
specific text will be wrap normally and other abnormal

**Comment by okhowang** [comment]
I add `word-break: break-all` on label cell, and it work fine.
but can we accept this modification to use `word-break: break-all`?
![image](https://user-images.githubusercontent.com/3352585/71503066-99531180-28ae-11ea-9585-a8d764378d5e.png)
