### ISSUE TITLE
Ignore case for Value groups/tags functionality

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#21269]
**What happened**:
Trying to use tags to select a group of template variables, in this case VM names. The query to get the list of names from the tag gets all name in upper case, but the query to get all the VM names returns some names in lower cases, and when the cases do not match, the variable are not selected. This leads to the tags not being checked, and its check box becoming unresponsive. 

**What you expected to happen**:
Case is ignored, all the variables are selected, and the tag can be unchecked to unselect variables. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: Azure Monitor v.0.3.0
- OS Grafana is installed on: hosted grafana
- User OS & Browser: reproducible on all
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Should be handled in the data source.
