### ISSUE TITLE
Unable to zoom in time by dragging on the graph with a streaming datasource

### ISSUE THREAD

**Issue by tkurki** [grafana/grafana#21264]
**What happened**:
I am unable to zoom time by dragging on the graph if a streaming datasource is updating frequently enough. The time period is not getting highlighted and no zoom is triggered.

**What you expected to happen**:
Dragging should highlight the dragged period and when released the dragged time period should be selected (zoomed into).

**How to reproduce it**:
```
git clone git@github.com:tkurki/signalk-grafana-datasource.git
git checkout 1b67198947e7c3dbfb7e38af3b4deffd414109ec
yarn
yarn watch
docker run  -p 3001:3000 --name=grafana -e "GF_SECURITY_ADMIN_PASSWORD=foobar" -v `pwd`:/var/lib/grafana/plugins/sk-datasource  grafana/grafana:6.5.2
```
- add a Signal K datasource with hostname `demo.signalk.org`
- add a graph with data configured with path `navigation.speedOverGround`
- set time for last 5 minutes (just to see data coming in)
- try to zoom in time by dragging over the graph
- disable network => zooming works (sort of, no data naturally) when the graph is not redrawing all the time
 
**Anything else we need to know?**:
The data is marine data streaming over a WebSocket connection in [Signal K](http://signalk.org/) format. I just discovered that Grafana supports streaming, which makes it an even more attractive solution for SK applications. 

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: See above
- OS Grafana is installed on: N/A, Docker
- User OS & Browser: MacOS Chrome 79.0.3945.88
- Grafana plugins: See above

**Comment by hugohaggmark** [comment]
Great that you found this @tkurki , I was able to repro this using only the Test Data and Streaming Client.

**Comment by zoltanbedi** [comment]
Zooming in to the new timeseries panel while there are data coming in works fine. Please try to use the new Time series panel.
