### ISSUE TITLE
html/template: "index" is undefined

### ISSUE THREAD

**Issue by RamanPndy** [grafana/grafana#21268]
**What happened**:
Grafana Login Page is not Showing Up.

**What you expected to happen**:
Grafana Server Should show the UI on start up on localhost.

**How to reproduce it (as minimally and precisely as possible)**:
navigate to \grafana\ and do npm install and npm will install all the required front end libraries.
navigate to \grafana\pkg\cmd\grafana-server and execute **dlv debug** and it starts grafana-server in debug mode on localhost:3000
but UI is not showing up.

**Anything else we need to know?**:
I'm trying to setup Grafana Development environment on my local system. I'm able to start grafana-server on localhost:3000 but login page is not showing up instead it's showing following error:
html/template: "index" is undefined

I did npm install also packages got installed successfully.

I'm on Windows Machine 64 Bit.

Please help me to bring up the UI. I need to integrate Prometheus Data Source.

Thanks.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Make sure the repo root is the working dir when you start grafana server.

**Comment by torkelo** [comment]
And do yarn install , and yarn start , to build frontend

**Comment by RamanPndy** [comment]
Yes thanks @torkelo .
on yarn install and yarn build. I'm able to get the UI on developer mode.

I need to create a custom plugin with HighCharts.js for my organnization with custom API which will return the prometheus response in custom format.

Basically HighChart.js needs custom JSON format to draw the graph. so I'm thinking to create a dedicated backend API for that which take prometheus response and convert it to HighChart compatible format. 

so can you please suggest me the better way to do it in Grafana or point me to some resource that would help me to achieve this.

I would really appreciate that.

Thanks.

**Comment by hugohaggmark** [comment]
Hi @RamanPndy, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
