### ISSUE TITLE
Renderer image but not add to Slack

### ISSUE THREAD

**Issue by nscpro** [grafana/grafana#21275]
[https://www.icloud.com/sharedalbum/#B0xGtnIORyGPdw](https://www.icloud.com/sharedalbum/#B0xGtnIORyGPdw)

Log file show everything is okay, but if alert coming and send notification to slack, not show image

**Comment by hugohaggmark** [comment]
Hi @nscpro  in order for us to investigate this further it would be great if you could supply the following:
**Environment:**

Grafana version:
Data source type & version: 
OS Grafana is installed on: 
User OS & Browser: 
Grafana plugins:
Others:

**Comment by marefr** [comment]
Duplicate of #21018
