### ISSUE TITLE
Annotations on all graphs using different data sources

### ISSUE THREAD

**Issue by omame** [grafana/grafana#2127]
I have a dashboard that contains graphs that use different data sources.
When I add some annotations I'd expect them to only appear on the graphs using the same data source. Instead they end up on all the graphs regardless of the data source.
Is there a way to avoid this that I couldn't read in the docs or is this a bug?

**Comment by torkelo** [comment]
no, currently annotations are global for the whole dashboard, that is they appear on all graphs. There are feature requests for allowing per graph annotations, not sure when there will be time to implement that.
