### ISSUE TITLE
Custom unit: mm/u

### ISSUE THREAD

**Issue by EvertJob** [grafana/grafana#21272]
**What would you like to be added**:
Custom unit: mm/u (Millimeter per hour)

**Why is this needed**:
Because I'm measuring the predicted rain fall in mm/u so it would be nice to have this unit for a nice display

**Comment by torkelo** [comment]
In v6.6 (jan) you can add / specify custom units

**Comment by EvertJob** [comment]
I’ve know because I read about it. Only issue is: can’t find where to define i.

The only solution I’ve found is the label option?

**Comment by ryantxu** [comment]
It only exists if you are using an unreleased version of grafana.  It will be included in the next release. 

You just type the unit you want in the field:
![image](https://user-images.githubusercontent.com/705951/71568055-031f1700-2a79-11ea-8a37-6c009267d092.png)
