### ISSUE TITLE
Annotations Data Source after Migration

### ISSUE THREAD

**Issue by oryagel** [grafana/grafana#2128]
Hi,
I migrated to Grafana 2.0.
After the migration the Annotations data source is not configured.
If I select my data source from the drop down it works.
How can I set the data source for Annotations for all dashboards?

Thanks

**Comment by torkelo** [comment]
did you name the data source with the same name as in Grafaan 1.9?

**Comment by oryagel** [comment]
Probably not...
What is the default data source name in 1.9?

**Comment by torkelo** [comment]
@oryagel there no default name, you must specify one in config.js (its the key in the datasources object)
