### ISSUE TITLE
How to transformation my dsl into Variables es datasource query language:【{"find": "terms", "field": "name.keyword","size": 10,"query":{"bool":{"】

### ISSUE THREAD

**Issue by florida-haha** [grafana/grafana#21289]
**What happened**:
 my dsl:
`{
    "size":0,
    "query":{
        "bool":{
            "must":[
                {
                    "range":{
                        "@timestamp":{
                            "gt":"now-60s"
                        }
                    }
                },
                {
                "match":{
                    "topic_id":"xx"
                  }
               } 
            ]
        }
    },
    "aggs":{
        "metric_name_res":{
            "terms":{
                "field":"id.keyword",
                "size" : 50,
                "order": {"sum_test": "desc"} 
            },
            "aggs":{
                "sum_test":{
                    "sum":{
                        "field": "metric_sum"
                    }
                }
            }
        }
    }
}`

**What you expected to happen**:
    my dsl fill into  Variables es datasource :
    `{"find": "terms", "field": "name.keyword","size": 10,"query":{"bool":{"must":[{"range":{"@timestamp":{"gt":"now-60s"}}},{"match":{"topic_id":"xx"}}]},"aggs":{"name_res":{"terms":{"field":"name.keyword","size":10,"order":{"sum_test":"desc"}},"aggs":{"sum_test":{"sum":{"field":"metric_sum"}}}}}}`. but according to the result of my dsl which refering to offical doc, I found the result that show the conditions don't work in the dsl , So I want to ask  whether our grafana support the dsl like this? if I want complex dsl like this , how can I define dsl? thanks!!!!!!!

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.4
- Data source type & version: elasticsearch
- OS Grafana is installed on: centos
- User OS & Browser: google
- Grafana plugins: 
- Others:

**Comment by aocenas** [comment]
Hey @florida-haha, can you give us a bit more details of what is the issue? Things like screenshots or error message also helps a lot.

Grafana does some alteration of the Elasticsearch query so it can show the data in a graph so that is why the query may be different inside Elasticsearch compared to what you insert in Grafana.

**Comment by ArvinDevel** [comment]
I want define the variable by using the es aggs like this `{"aggs":{ "sum_test":{ "sum":{ "field": "metric_sum" } } } } ` but the grafana report error. does grafana support full es dsl? how can I use es aggs ability?

**Comment by aocenas** [comment]
Hey @ArvinDevel, can you show where are you trying the query and how it looks and also what error do you get?

**Comment by ArvinDevel** [comment]
![image](https://user-images.githubusercontent.com/16100052/74495900-0cbeea00-4f14-11ea-8b33-59b14051ca07.png)

like this picture, the error is `Templating
Template variables could not be initialized: Cannot read property 'then' of undefined`

**Comment by ArvinDevel** [comment]
@aocenas As far I know, grafana doesn't support es aggregates when defining template variable. Is it right? How to implement aggregate, for example count ? Thanks.

**Comment by torkelo** [comment]
This s not supported, see here for the supported variable query syntax / options https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#query-variable
