### ISSUE TITLE
Deleting datasource will trigger save and test events

### ISSUE THREAD

**Issue by lzdw** [grafana/grafana#21282]
**What happened**:
    I want to delete data source, but when I click the delete button, the page prompts "Datasource updated" and "Data source is working". Clicking the delete button triggered the save and test events.
![grafana_bug](https://user-images.githubusercontent.com/24379844/71572873-16cf8980-2b1c-11ea-8ae0-a599204be7d4.png)

**What you expected to happen**:
    After clicking the delete button, a delete confirmation box pops up without displaying other prompts.

**How to reproduce it (as minimally and precisely as possible)**:
    1. Add a data source and save it;
    2.click Delete button;

**Anything else we need to know?**:

**Environment**: 
- Grafana version: v6.5.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker 
- User OS & Browser: MacOS && chrome 79.0.3945.88
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting and opening a PR for this @lzdw
