### ISSUE TITLE
Explore: Loki invalid auto-completion on cursor above stream selector

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#21297]
**What happened**:

In the Explore (Loki datasource) when the cursor is above the stream selector (ie. `!=`) the auto-completion triggers but when selected a value, the value is not correctly replaced.

For example:

![2019-12-30 18 00 20](https://user-images.githubusercontent.com/1701904/71592182-9581f200-2b2f-11ea-9702-ff08c58ae4b8.gif)

**What you expected to happen**:

To correctly replace the value or not trigger at all when the cursor is above the stream selector.

**How to reproduce it (as minimally and precisely as possible)**:

_See above video_

**Environment**:
- Grafana version: `master`
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: OSX & Chrome `79.0.3945.88`

**Comment by aocenas** [comment]
cc @kaydelaney @davkal

**Comment by davkal** [comment]
Will get fixed as part of #21332
