### ISSUE TITLE
name of the html page after you login

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2129]
Hi Torkel:

What is the name of the html file right after you login to the grafana?

**Comment by torkelo** [comment]
Not sure what you want to know, that view is composed of many html files (partials)

**Comment by gsaray101** [comment]
there is an image called img/log_transparent_200x.png, I need to make that img bigger.

**Comment by gsaray101** [comment]
is it possible to edit the css or something to make that image bigger?

**Comment by torkelo** [comment]
that image is in text panel defined home.json (under public/dashboards), you can edit the text panels html content in the home.json file
