### ISSUE TITLE
Ensure loki as annotation source has option to set results limit

### ISSUE THREAD

**Issue by nvtkaszpir** [grafana/grafana#21308]
**What would you like to be added**:
Input field in Grafana UI that allows to set max results limit when using loki as annotation source.

**Why is this needed**:
Default grafana annotations source have limit of 100 entries.
When switching to loki as annotation source the limit is non-existent.

This causes that when trying to zoom out the dashboard which uses loki annotations then it tries to render (I think) about 1000 (or more) annotations it can find. Multiply it by number of graphs and web browser tend to become unresponsive.

**Comment by torkelo** [comment]
it should get default 1000 limit, does it get no limit at all for you?

**Comment by nvtkaszpir** [comment]
Not really sure, maybe it gets the 1000 limit, but then AFAIR there is an option to change limit from loki side, which could allow to get even more results (and that would be much more problematic).

I'd like to be able to limit certain dashboards to 20 annotations. without altering loki config.

**Comment by aocenas** [comment]
@Estrax does the additional field in loki query editor that you worked on show in annotations editor? I think it is the same component so maybe we can close this too by implementing that.
