### ISSUE TITLE
Align size of internally repeated visualisations across panels 

### ISSUE THREAD

**Issue by dgttm** [grafana/grafana#21301]
**What would you like to be added**:
When adding repeatable panels (in this case Bar Charts) and when the groups of values have differences in their count (e.g. 10 and 2), the different panels look pretty weird as they are not autoscaling regarding the panel size, but scaling the bars within the same sized panels.

**Why is this needed**:
It would be nice, if the whole panel size differs and if there would be an adjustable height for the bars within the panels, so that all panels look the same regardless how many values they display.

see screeshot below.

thank you and kind regards

![image](https://user-images.githubusercontent.com/13033378/71614909-a3c32300-2bae-11ea-8b65-3b4e59b4646f.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
