### ISSUE TITLE
Delete an Alert Rule inside Panel not delete Rules in the Alert Section

### ISSUE THREAD

**Issue by madmax01** [grafana/grafana#21309]
i tested an Basic Alert. i deleted it afterwards. but it still shows up in the Alert Rules. There are currently no Rules available > as it was deleted. But seems something preserved.  not working good.

**What happened**:

Created an Panel Metric Rule to see Email Alert. i deleted that Rule again to have initial State. But even after bounce Service the "Alert Rules" still shows up in the Main Section.  Inside the Panel Dashboard no Rule there anymore.

**What you expected to happen**:

i would expect an easy Alerting like  nagios is doing.   Condition met = alert,..... and to recovers if green. i would expect nothing preserved and all clean once delete an Panel Metric Rule.

**How to reproduce it (as minimally and precisely as possible)**:

https://grafana.com/grafana/dashboards/8168

i used this Dashboard. i created an Rule for "CPU Utilization Avg %".  Just to see mail arrives.  i saw the Rule Alert as well inside the Main Alert Rules. then i deleted the rule again,.. and inside the Main Alert Rules it still shows up.  i bounced service > still shows up

**Anything else we need to know?**:

**Environment**:
- Grafana version:  6.5.2
- Data source type & version:   Default Installation for Grafana.  and DataSource for Vmware is influxdb (telegraf pushing metrics there) 
- OS Grafana is installed on:
- User OS & Browser:     Centos7  , Browser: Chrome
- Grafana plugins:  
- Others:

**Comment by torkelo** [comment]
What Grafana SQL DB are you using? any ha setup?

**Comment by torkelo** [comment]
We have had one other report like this, https://github.com/grafana/grafana/issues/11224, can you add any info to that existing issue

Are you using provisioning?
