### ISSUE TITLE
Tags/Groups in template query variable not working with Mysql

### ISSUE THREAD

**Issue by geektcp** [grafana/grafana#21313]
**What happened**:
there is 2 bug:
```
1、visited grafana website, but  there is no version of mysql specified anywhere.
pls check this url:
https://grafana.com/docs/grafana/latest/features/datasources/mysql/

2、Enabled tags query when I use mysql datasource , then grafana report error in chrome
```
```
why not provide the version of mysql in office website of grafana?
or all mysql version supported?
```

**What you expected to happen**:
Provide version which grafana supported!
fix the bug follow error

**Anything else we need to know?**:
I enabled the button(Value groups/tags (Experimental feature)) and then error report in chrome:
```Templating
Template variables could not be initialized: Error 1064: 
You have an error in your SQL syntax; check the manual that corresponds 
to your MySQL server version for the right syntax to use near 'infra' at line 1
```

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: mysql-5.6.23
- OS Grafana is installed on: centos7
- User OS & Browser: chrome
- Grafana plugins: MySQL Data Source - Native Plugin
- Others:

**Comment by aocenas** [comment]
Hi, can you share the query you are using and the mysql version? Not sure if there are limitations on Mysql version (should work with most reasonably old version) but your query needs to match the version you are using and this may be a problem of mismatch between your query and the version.

**Comment by geektcp** [comment]
> Hi, can you share the query you are using and the mysql version? Not sure if there are limitations on Mysql version (should work with most reasonably old version) but your query needs to match the version you are using and this may be a problem of mismatch between your query and the version.

Hei, the grafana support my mysql version(5.6.23) , but do not support tag query when enable prometheus mysql datasource

**Comment by aocenas** [comment]
> but do not support tag query when enable prometheus mysql datasource

Sorry not sure I understand this. Do you mean it does not work only if you have both prometheus and mysql datasources set up? Does it work if you have only mysql datasource?

**Comment by torkelo** [comment]
Closing due to lack of details
 
Please ask questions on the community site https://community.grafana.com
