### ISSUE TITLE
Alerts from hidden metrics

### ISSUE THREAD

**Issue by cqcn1991** [grafana/grafana#21312]
**What happened**:
Alert not triggered when the metrics/series is set to hidden (but query is not disabled)

**What you expected to happen**:
Send out alert when metric is hidden

**Anything else we need to know?**:
no 

**Environment**:
- Grafana version: 6.3.2
- db: elasticsearch

**Comment by torkelo** [comment]
this is by design, hidden metrics are not parsed (read), only there to be used in pipeline aggregations
