### ISSUE TITLE
Render API in 6.4.2 ignores the height property

### ISSUE THREAD

**Issue by anthony-myob** [grafana/grafana#21311]
**What happened**:

When calling the Render API, height is now ignored and just scales with the width.

**What you expected to happen**:

As with version 5.4.5, expect the Height property to be honoured.

**How to reproduce it (as minimally and precisely as possible)**:

Call the Render API. An example:

`/render/d/9DqFL0jmk/workflow-de-post-to-hook?to=1577923045124&from=1577318245123&width=2000&height=1600&tz=Australia%252fSydney&timeout=10000`

Produces (in 6.4.2):

![image](https://user-images.githubusercontent.com/45080899/71648099-06a1ef00-2d54-11ea-8998-27a656836554.png)

Used to produce (in v5.4.5)

![image](https://user-images.githubusercontent.com/45080899/71648120-5f718780-2d54-11ea-90be-515838e53f4d.png)

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: N/A
- OS Grafana is installed on: 
  - https://hub.docker.com/r/grafana/grafana/ 
  - `grafana/grafana:6.4.2`
- User OS & Browser: Mac / Chrome
- Grafana plugins: N/A
- Others:

**Comment by aocenas** [comment]
Hey @anthony-myob can you check with version 6.5.0 or later? Seems like this issue was fixed in that release.
