### ISSUE TITLE
Add sender's name on email

### ISSUE THREAD

**Issue by haomingz** [grafana/grafana#2131]
Firstly thanks for you work on #1456, we love this new feature! 
but can you add a option on `grafana.ini`, provide from address name, maybe `from_name`.
If you add this option, there well be very helpful for us!

**Comment by torkelo** [comment]
@haomingz  there is a from_address setting

```ini
#################################### SMTP / Emailing ##########################
[smtp]
;enabled = false
;host = localhost:25
;user =
;password =
;cert_file =
;key_file =
;skip_verify = false
;from_address = admin@grafana.localhost

[emails]
;welcome_email_on_sign_up = false
```

**Comment by haomingz** [comment]
@torkelo sorry for my poor english, i know how to setting `from_address`, but i need `from_name` option, maybe like this
```
from_address = admin@grafana.localhost
from_name = Grafana Admin
```

**Comment by mpchadwick** [comment]
I think this would be useful too.

**Comment by sluchznak** [comment]
Why this issue is closed? Where solution?

**Comment by bergquist** [comment]
@sluchznak Its hard to keep track of all the notifications in a project like this :)

**Comment by jacobbednarz** [comment]
:hand: I'll take a look at this in the coming days.
