### ISSUE TITLE
Can't connect Application Insights on Azure Datasource

### ISSUE THREAD

**Issue by kevinajose20** [grafana/grafana#21316]
**What happened**: Grafana can't connect to the Application Insights API when adding it as part of an Azure Monitor Datasource. 

![App Insights error](https://user-images.githubusercontent.com/29178880/71661261-a37e7f80-2d88-11ea-8517-7c6ced7b07d6.png)

Application ID and Generated API Keys work fine when making a request to [api.applicationinsights.io](https://api.applicationinsights.io)

There are no issues accessing [api.applicationinsights.io](https://api.applicationinsights.io) on the same machine.

I don't know how to debug the requests the grafana server makes to troubleshoot this further. Looking at the grafana logs after saving the keys, I don't see any requests going to [api.applicationinsights.io](https://api.applicationinsights.io) which is weird...

![image](https://user-images.githubusercontent.com/29178880/71662350-1f2dfb80-2d8c-11ea-8a2c-448fb8436a36.png)

**What you expected to happen**: Clicking "Save & Test" should show success in querying the application insights service, along with Azure Monitor and Log Analytics Service

**How to reproduce it (as minimally and precisely as possible)**:
1.) Run a Fresh installation of Grafana. (I used v6.5.2)
2.) Login to Grafana and add an Azure Monitor datasource.
3.) Create an App Registration for Azure Monitor. Also generate a Key for this app.
4.) Assign the App Registration a Role such as _Monitoring Reader_ for the subscription.
4.) Under **Azure Log Analytics API Details**, register the IDs together with the Key
5.) Enable "Same details as Azure Monitor API" under **Azure Log Analytics API Details**
6.) Generate an [**Application Insights API Key** ](https://dev.applicationinsights.io/quickstart)
7.) Under **Application Insights Details**, register the Application IDs together with the Key
8.) Click _"Save & Test"_

**Anything else we need to know?**:
I've had this issue on three machines. 
- My local windows pc running Grafana 6.5.2
- An Azure VM running Grafana 6.4.4 w/ docker
- A local linux pc running Grafana 6.4.4 w/ docker

**Environment**:
- Grafana version: 6.4.4 & 6.5.2
- Data source type & version: Azure Monitor Application Insights
- OS Grafana is installed on: Windows and Linux
- User OS & Browser: Chrome 69
- Grafana plugins: None (All Default)

**Comment by kevinajose20** [comment]
Update: 

Clicking "Save & Test" on my office machine fails with the error.
However, doing the same from my mobile phone or my desktop at home (both are on a different network) are fine and successfully connect to the Application Insights REST API.

Am I correct in assuming that the REST requests are being sent from the client machine and not through the Grafana Server? It seems to be a network issue on my office network. (Our network policy is pretty open though...) 

If it is, any information on what addresses need to be accessed would be appreciated.

**Comment by sunker** [comment]
Thanks for reporting this @kevinajose20, and sorry for the late reply! 

We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics).
Closing this issue.
