### ISSUE TITLE
Azure Monitor: Log Analytics Alerts Not Supported

### ISSUE THREAD

**Issue by pyoungworthnw** [grafana/grafana#21327]
**What happened**:
Error when attempting to setup an alert via Azure Monitor for Log Analytics.
**What you expected to happen**:
Alert to be fired
**How to reproduce it (as minimally and precisely as possible)**:
Setup Azure Monitor.  Setup a query via log analytics in a dashboard.  Attempt to setup an alert for that metric.

The following error will be generated
`{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "2.004ms",
  "error": "tsdb.HandleRequest() error Alerting not supported for Azure Log Analytics",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
 `
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.2 (742d165)
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Windows or Linux (tried both)
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: Azure Monitor
- Others:

**Comment by torkelo** [comment]
Needs https://github.com/grafana/grafana/issues/14943 to be implemented
