### ISSUE TITLE
Hi everyone ! I'am having a problem about prometheus time can't be visualized in days !

### ISSUE THREAD

**Issue by Daly123456** [grafana/grafana#21329]
probe_ssl_earliest_cert_expiry{instance=~"$target"} -time()
 i have this instruction it lets me display ssl expiry time using prometheus as datasources and Multistat as a panel type !
i need to convert time visualised to days ! For exemple 72 days ! 

![commiu](https://user-images.githubusercontent.com/46686877/71732096-b5bef300-2e46-11ea-8efc-95be1b951dde.PNG)

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com
