### ISSUE TITLE
Import dashboard api returns "Internal Server Error" with valid dashboard which works via UI import

### ISSUE THREAD

**Issue by eickeee** [grafana/grafana#21321]
**What happened**:
When importing various AWS dashboards from Monitoring Artist e.g AWS Cloud Front (https://grafana.com/grafana/dashboards/674) via Grafana UI (either via ID/URL or JSON) it successfully imports the dashboard. However, when using the `GRAFANA_URL/api/dashboards/import` endpoint with the same json, Grafana returns `500 - Internal Server Error`. When looking in the logs, I see the following exception:

`t=2020-01-02T13:58:14+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:199 (0x44c5cb)\n/usr/local/go/src/runtime/signal_unix.go:394 (0x44c408)\n/go/src/github.com/grafana/grafana/pkg/models/dashboards.go:129 (0x92071f)\n/go/src/github.com/grafana/grafana/pkg/components/simplejson/simplejson.go:142 (0x920e17)\n/go/src/github.com/grafana/grafana/pkg/models/dashboards.go:130 (0x920765)\n/go/src/github.com/grafana/grafana/pkg/plugins/dashboard_importer.go:55 (0xd3a936)\n/usr/local/go/src/reflect/value.go:460 (0x4978e5)\n/usr/local/go/src/reflect/value.go:321 (0x4970a3)\n/go/src/github.com/grafana/grafana/pkg/bus/bus.go:131 (0xaa8208)\n/go/src/github.com/grafana/grafana/pkg/bus/bus.go:216 (0x1322682)\n/go/src/github.com/grafana/grafana/pkg/api/plugins.go:194 (0x1322689)\n/usr/local/go/src/reflect/value.go:460 (0x4978e5)\n/usr/local/go/src/reflect/value.go:321 (0x4970a3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x826cc9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x826679)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0x133a36d)\n/usr/local/go/src/reflect/value.go:460 (0x4978e5)\n/usr/local/go/src/reflect/value.go:321 (0x4970a3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x826cc9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x826679)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x827c68)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5b2c5)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xc5b2b8)\n/usr/local/go/src/reflect/value.go:460 (0x4978e5)\n/usr/local/go/src/reflect/value.go:321 (0x4970a3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x826cc9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x826679)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x827c68)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5aabc)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xc5aaa7)\n/usr/local/go/src/reflect/value.go:460 (0x4978e5)\n/usr/local/go/src/reflect/value.go:321 (0x4970a3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x826cc9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x826679)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x827c68)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5a9cf)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 (0xc5a9bd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x827b10)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x8269d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x826768)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x827c68)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5821b)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xc58206)\n/usr/local/go/src/reflect/value.go:460 (0x4978e5)\n/usr/local/go/src/reflect/value.go:321 (0x4970a3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x826cc9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x826679)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x827c68)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x838dc6)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:294 (0x83373d)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x82cb5a)\n/usr/local/go/src/net/http/server.go:2802 (0x706823)\n/usr/local/go/src/net/http/server.go:1890 (0x7021c4)\n/usr/local/go/src/runtime/asm_amd64.s:1357 (0x466ce0)\n"
t=2020-01-02T13:58:14+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/import status=500 remote_addr=18.*.*.* time_ms=24 size=122 referer=`

**What you expected to happen**:
The endpoint returns successful.

**How to reproduce it (as minimally and precisely as possible)**:
Download CloudFront dashboard as json: https://grafana.com/api/dashboards/674/revisions/3/download
Send the downloaded json via POST to https://GRAFANA_URL/api/dashboards/import 

**Environment**:
- Grafana version: 6.5.2
- OS Grafana is installed on: official grafana docker image
- User OS & Browser: Windows 10 with Chrome 78.0.3904.108
- Grafana plugins: None (All Default)

**Comment by aknuds1** [comment]
I'm able to reproduce, trying to fix the issue.

**Comment by aknuds1** [comment]
Where is it documented that you can use this API endpoint for importing dashboard JSON documents of this format? AFAICT the reason for the segfault is that you're sending it invalid JSON.

**Comment by eickeee** [comment]
@aknuds1 Which endpoint am I supposed to use instead to get the same functionality as provided by the Import UI? 
I checked the documentation and found `POST GRAFANA_URL/api/dashboards/db`. Though this one requires a dashboard object to be contained which I do not get when downloading the monitoring artist dashboards and which is also not required by the Import UI.

**Comment by aknuds1** [comment]
I'm not 100% sure, but I would think you should use [/api/dashboards/db](https://grafana.com/docs/grafana/latest/http_api/dashboard/#create-update-dashboard). I think the `dashboard` field should be exactly the dashboard JSON document, for example https://grafana.com/api/dashboards/674/revisions/3/download.

For further support on this, I suggest you ask in the [Grafana community](https://community.grafana.com/), since this isn't a bug. Thanks!
