### ISSUE TITLE
Data source permissions 

### ISSUE THREAD

**Issue by jonaz** [grafana/grafana#2132]
I'm glad #1826 is fixed!

I would really like to see per dashboard user permission (or dashboard group as mentioned in #1611 )

My usecase is that i want to make a dashboard per house in my housing cooperative so that each house can see their electric, heating and water usage. I don't want them to see each others data.

**Comment by torkelo** [comment]
ok. It could happen in the future. But it would not prevent anyone who knows http from viewing each others data though (as the time series stores allows all queries).

**Comment by jonaz** [comment]
Thats ok for my usecase. Its not super secret. Just normal users should not be able to browse it. 

Permissions per series could be solved through the data proxy. By for example adding a new proxy query path including which dashboard made the request so we can check permissions.

**Comment by hwinkel** [comment]
Thats would cover our usecase as well, currently we need to export and import JSON to bring dashboard to a different org which then need to have the same datasource. sharing dashboards with users or lets say hide certain dashboards is OK. This user will only have view permissions then.

**Comment by FS1360472174** [comment]
a question about user permission.
a viewer cannot edit the dashboard,this is right.
but the viewer can create a new organization,and switch to new organization,
so he can edit the dashboard now,so what's the meaning of 'viewer'.he still can do what he want?
grafana version 2.1.3.

**Comment by torkelo** [comment]
A role is tied to an organization, so he is a viewer in your org, but he can create an organization himself he is then org admin for that new org. You can disable this in grafana.ini (`allow_org_create`)

**Comment by FS1360472174** [comment]
@torkelo  thanks .
actually I have found answer in  this page https://github.com/grafana/grafana/issues/3832
there are so many issues and some are duplicate,is there any Column about FAQ

**Comment by sgarg7** [comment]
+1 It will be very useful to prevent users overwriting dashboards created by others.

**Comment by failattu** [comment]
+1 it would be nice to do this. Also I would love to limit data sources by groups etc. This would help Grafana to work with different teams and even bring user permissions from different places per dashboard.

**Comment by t-pfaff** [comment]
+1 Would be great to restrict permissions per dashboard

**Comment by JulienChampseix** [comment]
Hi @torkelo,
Any progress on this feature ?

**Comment by torkelo** [comment]
not yet, hope to do dashboard folders with 1-2 months, then user groups & permissions with next 3-6 months

**Comment by ayozemr** [comment]
Waiting for this too! Great work!

**Comment by daniellee** [comment]
Proposal for Dashboard Groups and a Permissions Model: https://github.com/grafana/grafana/issues/1611#issuecomment-287742633

**Comment by 999chris** [comment]
+1 Has there been any progress on this. This is a feature I am anticipating more than any.

**Comment by jbein** [comment]
+1 This feature would be awesome! I hope it will come soon.

**Comment by tsboj17** [comment]
+1 Let's rock guys :)

**Comment by alarmschaben** [comment]
+1 Yes, please! :-)

**Comment by Rakesh539** [comment]
Hi, How can I control users per dashboard. When I add users for particular dashboard that is getting cleared off after 2nd time login. Is there any way to add users per particular dashboard.

**Comment by torkelo** [comment]
Clearer? Add users to dashboard? That feature does not exist. 

We are currently working in dashboard folders, user groups and permissions

**Comment by menon0906** [comment]
I have admin access, is there a way i can create different dashboards for different org?

**Comment by daniellee** [comment]
@menon0906 is this a general question or is it connected to this feature request? If it is a general question, then as an admin you can add yourself to any organization by going to the admin section in the menu and then to global users and then to your own user and then add yourself to the org like shown below: 

![image](https://user-images.githubusercontent.com/434655/27206761-b34599a8-5239-11e7-8b8e-b61aac8dba6c.png)

And then you can switch to that organization:

![image](https://user-images.githubusercontent.com/434655/27206778-e2259b1a-5239-11e7-8df8-45654204be64.png)

**Comment by menon0906** [comment]
Thanks for prompt reply. But my question is for eg. Organisation 'A' wants to view only 'X' named dashboard.
As i have admin privilege, can i create 'X' named dashboard for org 'A'?

**Comment by daniellee** [comment]
@menon0906 this is off topic for this feature request. Can you ask the question on the community site instead: community.grafana.com

**Comment by menon0906** [comment]
yep, tHanks. I have already put the questions forward: 

https://community.grafana.com/t/questions-on-user-org/1387

**Comment by menon0906** [comment]
Can anyone help me to give a query for graphite datasource where i can derive Total count for the Hosts which are down?

For eg. SQL query

select count(*) from tablename;

**Comment by daniellee** [comment]
@menon0906 I replied on the community site but you didn't give any response.

**Comment by menon0906** [comment]
hey i haven't got any reply in community.. can you pass me the link if you don't mind.

**Comment by daniellee** [comment]
@menon0906 eh, check your link again. I replied 3 days ago. https://community.grafana.com/t/questions-on-user-org/1387/2?u=daniellee

**Comment by menon0906** [comment]
Daniel that was a different question....

Now the question is "help me to get a query for graphite datasource where i can derive Total count for the Hosts which are down?" 

Note: I'm using graphite as a datasource.

For eg. SQL query

select count(*) from tablename;

**Comment by JorgeGT** [comment]
Please, could you not spam this issue with a completely unrelated question? Note that for _each_ comment here at least 16 subscribers are receiving a new email in their inboxes.

**Comment by menon0906** [comment]
This is not a spam. Asking for help...Thanks

**Comment by torkelo** [comment]
@menon0906 for new help questions, open a new topic on the community site, never hijack an unrelated GitHub feature request, this will cause spam for all interested in this issue.

**Comment by ayozemr** [comment]
+1 with @JorgeGT . Please @menon0906, do not disturb here if your topic is not related.

**Comment by vamsimarri** [comment]
+1 Waiting for this feature.

**Comment by menon0906** [comment]
@torkelo thanks for the info. Will do as mentioned. 

@ayozemr not disturbing anybody mate, since i was new to it so posted unknowingly.

**Comment by LeDistordu** [comment]
+1 !!!! ;)

**Comment by lephix** [comment]
+1 waiting

**Comment by Wayneoween** [comment]
+1

**Comment by Kurvinox** [comment]
+1

**Comment by carolshark** [comment]
+1

**Comment by covelus** [comment]
+1

**Comment by prasenforu** [comment]
+ 1

**Comment by matthgyver** [comment]
+1

**Comment by sandrolf** [comment]
+1

**Comment by northtree** [comment]
+1

**Comment by doulakis** [comment]
+1

**Comment by calvinboey** [comment]
+1

**Comment by embix** [comment]
How about upvoting / emoji thumps up (and subscribe if interested in updates) instead of commenting "+1"? Don't clutter the comments, don't clutter our timeline, pretty please ;-)

![](https://memegenerator.net/img/instances/500x/80321250/yeah-if-you-could-please-stop-commenting-1-and-upvote-instead-thatd-be-great.jpg)

**Comment by plin2** [comment]
+1 also waiting ... in urgent need  ...

**Comment by torkelo** [comment]
> My usecase is that i want to make a dashboard per house in my housing cooperative so that each house can see their electric, heating and water usage. I don't want them to see each others data.

Having permissions on dashboards would not solve that as the data source is exposed to the whole org and any user can technically issue any query against a org data source.

**Comment by bedrin** [comment]
> Having permissions on dashboards would not solve that as the data source is exposed to the whole org and any user can technically issue any query against a org data source.

Can be solved by allowing execution only of queries existing in the dashboards user is entitled to.

**Comment by torkelo** [comment]
> Can be solved by allowing execution only of queries existing in the dashboards user is entitled to.

Dashboards can contain dynamic queries that change depending on template variables and template variables can have any value. So would be impossible to verify the query is "allowed".

**Comment by torkelo** [comment]
What we can do is to have permissions on data sources, so if you can split your data sources into multiple Grafana data sources (for example separate influxdb databases and users, or different prometheus servers or graphite servers) then you can isolate data that way.

**Comment by bedrin** [comment]
> Dashboards can contain dynamic queries that change depending on template variables and template variables can have any value. So would be impossible to verify the query is "allowed".

If template variable values are escaped (like SQL injection protection) then it is safe. Isn't it?

**Comment by aderumier** [comment]
@torkelo : I'm looking for something similar, shared templated dashboard for all users of same organisation (for example, linux host dashboard with cpu,ram,.. with hostname as templated field, but each user should have permission on a specific datasource)

**Comment by ammpio** [comment]
@torkelo now that user teams and dashboard folders are out in Grafana 5, having the corresponding flexibility in datasource permissions would clearly be a complementary feature. I know there's been some discussion about having it implemented, but not sure if there's a timeline? It doesn't currently appear to be on the [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md).

For us at least, the ability to restrict dashboard access based on group/user permissions becomes far less meaningful in a situation where all users still have access to all datasources (for a given org).

**Comment by svet-b** [comment]
@torkelo now that user teams and dashboard folders are out in Grafana 5, having the corresponding flexibility in datasource permissions would clearly be a complementary feature. I know there's been some discussion about having it implemented, but not sure if there's a timeline? It doesn't currently appear to be on the [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md).

For us at least, the ability to restrict dashboard access based on group/user permissions becomes far less meaningful in a situation where all users still have access to all datasources (for a given org).

**Comment by aurimasplu** [comment]
My use case is to have ability to generate links to live dashboards without user authentication (like snapshots) but always have up to date data. Different departments in our company want to see very specific dashboards for specific nodes and put them on display walls. 
I myself do not know anything about how Grafana is coded, but somehow I do not see why it should be so problematic. This is how I think it should work and please forgive my ignorance:
When you generate a shared URL to dashboard you are given a token, token is written to some table in Grafana database. 
All needed variables for that dashboard should be blinded to that token and never disclosed to public user. Restrict adding any other variable to link to dashboard when you are using token except maybe for timestamps.

**Comment by xurde** [comment]
We really find very interesting some of the approaches here mentioned. Our use-case which is that we have on single Influx DB and we would really need to restrict all charts/queries to contain a WHERE clause which restricts access to only the user's data. Solving this with some QL injection protection like @bedrin pointed would be a conceptually-safe solution both in API/chart level.

Any plans for exploration/implementation here? We are willing to help if there is more workforce/guidance because we are not very familiar to the application code now.

Cheers.

**Comment by svet-b** [comment]
@xurde I would say that it's very unlikely that there is such a thing as reliable data permissions management via query re-writing. Even in a straightforward/restrictive query language like InfluxQL, it would be nearly trivial to circumvent such a measure by altering field or tag names inside the (user-created) query, so as to trick a filter. E.g. if the idea is to select only user X's data based on tag called `user` and a `WHERE user='X'` clause, they could just write a query like
```
SELECT x, y, z, user_fake AS user FROM data;
```
and trick the filter by feeding it another tag or field that the filter gets applied on. This is just scratching the surface, of course. More flexible languages like MySQL will offer an ill-meaning individual a pretty wide array of options for getting around a `WHERE` filter. So any permissions management will really just have to happen at the database engine/datasource level.

For now I'd be delighted if Grafana could implement simple datasource permissions management that incorporates team membership as a criterion (just like dashboards now do). Though I have to admit I'm no longer clear as to what the specific functionality requested by this issue report is.

**Comment by torkelo** [comment]
It will probably disappoint you that his feature is one of the first features we are doing as part of the Grafana Enterprise offering (commercial version of Grafana). We have reached a point where we need to make Grafana Enterprise more appealing other than including support. So the goal is to take a few features that only cater to the really large companies and make those part of the commercial code base. We have been successful in staying 100% OSS for almost 5 years with only a minor open core model with our premium plugins, this is a minor change in that strategy. One we will take step by step and listen to community feedback along the way.

The version of this feature will ship in Grafana v5.4 Enterprise (beta next week).

To read more on Grafana Enterprise: https://grafana.com/enterprise
Docs for the feature: http://docs.grafana.org/permissions/datasource_permissions/#datasource-permissions
