### ISSUE TITLE
Feature Request: Snapshot Sharing with relative Time

### ISSUE THREAD

**Issue by Akulatraxas** [grafana/grafana#2133]
First of all: Great work! Thank you.

I would like to have the "Snapshot Sharing" Feature with a relative time or something comparable:
We would like to give "external" Developers access to Dashboards created for them. But not showing them all of our metric tree or other Dashboards. Like a read-only view.

**Comment by torkelo** [comment]
what do you mean "with relative time"? 

Snapshot sharing captures the visible data and embedds it into the dashboard model and saves that model.

**Comment by Akulatraxas** [comment]
What I want to archive is possibility to give somebody an URL to an dashboard an he only can zoom in and out. But don't look into the metric tree - eg: see other Data.
We have external Developers who are responsible for a specific application - and I want them to view a Dashboard made for them by me.
The Snapshot Feature is really close to what a I want, but it don't show "live" data.

**Comment by torkelo** [comment]
This is not possible to do with live data with any of the current data sources (graphite, influxdb, opentsdb), they do not support per series permissions, so even if we had a "read only" dashboard, an external developer with some http knowledge could easily query for other metrics. 

Your only option is to segregate these apps into a seperate Graphite instance or InfluxDB database if you want total security (external developers should not have any access to other metrics then specific dashboards)
