### ISSUE TITLE
Unpausing a non-paused alert changes status to Unknown

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#21330]
**What happened**:
Unpausing a non-paused Alert changes the state to "unknown", adding an annotation next time the Alert executes.

**What you expected to happen**:
Sending an unpausing API call should trigger only if the Alert is paused. If should be ignored for non-paused alerts.

**How to reproduce it (as minimally and precisely as possible)**:
Send a '"paused": false' to a non-paused Alert and it will change the state to "unknown"

**Environment**:
- Grafana version: 6.5.2
- OS Grafana is installed on: Grafana Cloud

**Comment by vikkyomkar** [comment]
Hi @torkelo I have opened a PR #21375 which will fix this issue.
