### ISSUE TITLE
Panel: Simple time picker per panel with Hour, Day, Week shift options

### ISSUE THREAD

**Issue by m50434** [grafana/grafana#21345]
**What would you like to be added**:
I would appreciate the possibility to get a timeshift for each panel (not for the whole dashboard) with some buttons (so you can shift the time with one click backwards or forwards in a special range, i.e. day hour or month.

**Why is this needed**:
It would be nice to compare i.e. the current day with the day before immediately.
Or just to go through your data quite fast.

Here is an example: There are some buttons. 
![GIF](https://user-images.githubusercontent.com/24473301/71778359-33047800-2fad-11ea-9c07-525fba635b4a.gif)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
