### ISSUE TITLE
Bug: Render Feature: Not all Graphs rendered

### ISSUE THREAD

**Issue by Akulatraxas** [grafana/grafana#2134]
Hi!,

I learned in a Ticket about the dashboard render feature. I tried it, but apparently it only renders one Graph of the Dashboards, the rest remain empty and you can see the spinning circle.
I have grafana-2.0.2-1.
Its completly random which graph appears. Sometimes all render.
http://6al.de/only_one.JPG

**Comment by torkelo** [comment]
dashboard render? you can render a single panel, but there is no feature to capture a whole dashboard

**Comment by Akulatraxas** [comment]
And what is this?
http://play.grafana.org/render/dashboard/db/grafana-play-home

**Comment by torkelo** [comment]
the http panel render api? Use by the panel rendering feature :)

**Comment by torkelo** [comment]
it can be used to render the whole dashboard but the feature was designed to only render a single panel

**Comment by torkelo** [comment]
And there already is a feature request to make the Panel -> PNG work with dashboards
https://github.com/grafana/grafana/issues/2085

**Comment by 3fr61n** [comment]
It's there a chance to include in the as argement for

**Comment by p4fg** [comment]
+1 for timeout parameter

**Comment by openfly** [comment]
+1 for timeout parameter
