### ISSUE TITLE
jquery.flot.pie.js 0 size

### ISSUE THREAD

**Issue by nycterent** [grafana/grafana#21349]
**What happened**:

jquery.flot.pie.js is empty and pie chart panel fails to render pie chart

**What you expected to happen**:

/usr/share/grafana/public/vendor/flot/jquery.flot.pie.js should contain some javascript

**How to reproduce it (as minimally and precisely as possible)**:

any pie chart

**Anything else we need to know?**:

**Environment**:
- Grafana version:

6.5.2
- Data source type & version:
elasticsearch 
- OS Grafana is installed on:
debian9
- User OS & Browser:
os x chrome
- Grafana plugins:
installed plugins:
doitintl-bigquery-datasource @ 1.0.4
goshposh-metaqueries-datasource @ 0.0.3
grafana-clock-panel @ 1.0.3
grafana-influxdb-flux-datasource @ 5.4.1
grafana-piechart-panel @ 1.3.9
grafana-simple-json-datasource @ 1.4.0
grafana-worldmap-panel @ 0.2.1
graph-compare-panel @ 0.0.0

- Others:

**Comment by torkelo** [comment]
strange, works fine form me using latest pie chart plugin. This flot extension is loaded by the plugin itself
 
https://github.com/grafana/piechart-panel/blob/master/src/rendering.ts#L2

**Comment by nycterent** [comment]
looks like pie chart conflicts with graph-compare-panel (
https://github.com/AutohomeCorp/graph-compare-panel/issues/7)
