### ISSUE TITLE
[Feature Request] Per-metric Custom Query Parameters

### ISSUE THREAD

**Issue by 03k64** [grafana/grafana#21354]
**What would you like to be added**:

Per-metric custom query parameters for use with Prometheus data source (and by extension, with Thanos).

**Why is this needed**:

Currently per-datasource custom query parameters are available to allow, for example, `max_source_resolution` to be set as part of requests to Prometheus datasources. (Original feature request for a Thanos datasource in #16574, further discussion about instead adding to Prometheus datasource in #16665, feature added #19121.)

By making this available per-datasource there is a requirement to add multiple datasources targeting the same instance of Thanos in order to use different custom query parameters. If custom query parameters were _also_ available per-metric it would remove the need to maintain multiple datasources to target a single Thanos instance while maintaining that option for those who prefer it.

I thought this seemed similar to #14261 (which led to #16574) but that goes on to talk about enabling downsampling via HTTP headers rather and mentions configuration at the datasource level, rather than continuing to discuss a per-metric solution.

**Comment by aocenas** [comment]
Hey, just to clarify when talking about:
> If custom query parameters were also available per-metric

Do you mean configuring them per query right? Cause as I understand them they can be defined only per query but we always just take the values from datasource config and there is no way to override them in one particular panel for example.

**Comment by torkelo** [comment]
Closing due to lack of details
