### ISSUE TITLE
Alerting: Alerting history should include pause and unpause alert event

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#21355]
**What would you like to be added**:

Alerting history should include pause and unpause alert event.

**Why is this needed**:

There is no way to track when the alert is paused and unpaused. This is problematic when alert is paused when alert is in alerting state.

**Comment by orojina** [comment]
@yesoreyeram 
In case you find this useful I created a script to pause and resume alerts. It accepts arguments to add annotations when pausing/resuming alerts. You can put it in a cron job or a pipeline and manage schedules there. As a temporary solution

![orojina-grafana-cli-low-qty](https://user-images.githubusercontent.com/11845190/108608128-7a54f000-738a-11eb-892d-73b6bfc30949.gif)


https://github.com/orojina/grafana-cli

**Comment by JohnnyQQQQ** [comment]
This is in legacy alerting, right now we do not implement new feature requests for legacy alerting. The concept of paused alerts does not exists in the new alerting system.
