### ISSUE TITLE
Inter dahsboard value transfer

### ISSUE THREAD

**Issue by RuchaBapat** [grafana/grafana#21353]
Hello,

We are trying to connect different dashboards in grafana.
Is this possible in grafana right now? I think we could not find it.
What we want to do is, select/click on some data value in one dashboard and use it in a filter of another dashboard. We also need to take up the other values based on which particular value is caculated. That will take the full context of the calculation from one dashbiard to another.
This will help us to show different types of representations and visulization for particular data value taken from certain dashboard.

Can you add this feature request of inter dashboard interaction with carrying value in your backlog?

We wait for your update.

**Comment by torkelo** [comment]
you can use variables in panel links, or data links. 

You find panel links in the general tab, and some panels like Graph & Gauge have data links that support urls that can reference data & series name values. 

You can link to the other dashboard, and in the URL set template variables defined in that other dashboard.
