### ISSUE TITLE
data source fails to access prometheus

### ISSUE THREAD

**Issue by rajputvishwas** [grafana/grafana#21351]
I have setup prometheus and grafana on OKD(3.11). I am able to access web console for both the applications. I just want to add prometheus metrics to grafana.  I logged in to grafana server

**Steps to reproduce**:
  My prometheus is running at
![image](https://user-images.githubusercontent.com/15668995/71812256-bbae1180-309c-11ea-9aea-5166cb3b5ca3.png)

 On grafana add data source page
![image](https://user-images.githubusercontent.com/15668995/71812575-8524c680-309d-11ea-9ac6-0642a4885cb3.png)

 public URL of prometheus and I have also tried various authentication mechanism
 
 sepcified scrape interval and query time out in second

 

**Actual Result**:

![image](https://user-images.githubusercontent.com/15668995/71812674-ccab5280-309d-11ea-945b-9a90cc403960.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/15668995/71812627-ae455700-309d-11ea-8748-3bdb1a6b4cbc.png)

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 
   Grafana v6.5.2
- Data source type & version:
  Prometheus: 2.14
- User OS & Browser: OKD 3.11 cluster hosted on Ubuntu & Firefox
- Others:

**Comment by torkelo** [comment]
open chrome dev tools to check what the network error is. 

Make sure your grafana server can access your prometheus server (the access is not directly from the browser but via grafana-server)

**Comment by alexandru-roman** [comment]
Hello @torkelo,

I am running Grafana - v6.5.2 (742d165) using Docker and I am facing the same issue as the one mentioned by @rajputvishwas .

Please see below the stack-trace:
`react-dom.production.min.js:21 Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.onChange (PromSettings.tsx:122)
    at n.value (react-select.esm.js:4631)
    at react-select.esm.js:4568
    at e.onChange (react-select.esm.js:2894)
    at e.setValue (react-select.esm.js:2921)
    at e.selectOption (react-select.esm.js:2959)
    at l (react-select.esm.js:4001)
    at Object.<anonymous> (react-dom.production.min.js:14)
    at h (react-dom.production.min.js:15)
    at react-dom.production.min.js:15`

**Comment by torkelo** [comment]
Try specifing property time intervals (that in in s or m) in the scrape or timeout fields, in the screenshot there are no time suffix

**Comment by alexandru-roman** [comment]
The time intervals are already specified, however this stack-trace error appears every-time when I am trying to choose a value from HTTP Method drop-down, without using the Save & Test button.
My feeling is that the selected value is not shown on the interface due to above error.

**Comment by rajputvishwas** [comment]
Hi @alexandru-roman, try to lower version of Grafana (5.3.4),  and set Access field under **HTTP** to **Browser** as displayed in the above image.  With this method you can connect to Prometheus without selecting any Auth methods. This worked for me.
