### ISSUE TITLE
Cloudwatch: Query editor crash when switching from cloudwatch to InfluxDB 

### ISSUE THREAD

**Issue by petetanton** [grafana/grafana#21361]
**What happened**:
Query editor shows "An unexpected error happened" when creating a new panel and switching from a Cloudwatch to an Influx data source
It works if you delete the auto created query and click "Add query"

**What you expected to happen**:
It shows the default query in the query editor

**How to reproduce it (as minimally and precisely as possible)**:
Go to any dashboard and create a new panel, select a Cloudwatch datasource and then select an Influx datasource

**Anything else we need to know?**:
From the console:
`react-dom.production.min.js:198 TypeError: Cannot read property 'length' of undefined
    at t.render (QueryEditor.tsx:124)
    at Ao (react-dom.production.min.js:173)
    at Mo (react-dom.production.min.js:172)
    at Do (react-dom.production.min.js:180)
    at Ga (react-dom.production.min.js:232)
    at Ya (react-dom.production.min.js:233)
    at Au (react-dom.production.min.js:249)
    at Tu (react-dom.production.min.js:248)
    at Nu (react-dom.production.min.js:251)
    at Cn (react-dom.production.min.js:85)`

**Environment**:
- Grafana version: 6.5.1 and 6.5.2
- Data source type & version: tested with Cloudwatch and InfluxDB
- OS Grafana is installed on: Centos 7
- User OS & Browser: Mac OS 10.12.6 and Chrome 79
- Grafana plugins:
- Others:

**Comment by petetanton** [comment]
![Screen Shot 2020-01-06 at 16 13 19](https://user-images.githubusercontent.com/11050440/71830855-8c4cd400-309f-11ea-87dd-d7725f1327c8.png)

**Comment by torkelo** [comment]
Very strange, unable to replicate and no other reports. Do you have any custom plugins installed?

**Comment by petetanton** [comment]
Hi @torkelo - thanks for taking a look at this.
The only plugin we have is grafana-worldmap-panel which is not present on this dashboard.
I have attached a gif which should hopefully provide more clarity.
![grafana](https://user-images.githubusercontent.com/11050440/71887874-e187f480-3136-11ea-91e2-71ed3ee6dbe9.gif)

**Comment by torkelo** [comment]
Ah, I think I know what is going on, cloudwatch query model is somehow interfering with the influxdb query model .

**Comment by LloydW93** [comment]
If it helps, this also happens when switching from CloudWatch to Graphite, so isn't specific to switching to the InfluxDB model.

**Comment by torkelo** [comment]
problem was in cloudwatch editor. PR fix ready :)

**Comment by petetanton** [comment]
Thanks @torkelo - much appreciated!
