### ISSUE TITLE
Discuss: add error to DataFrame, and maybe remove it from panelData

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#21367]
Currently [panelData](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/panel.ts#L17) has an error object.  This means there can be one error for a panel however DataQueryError more accurately maps to a dataFrame.  In the query editor, we try to line up errors with the data:  https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/panel_editor/QueryEditorRow.tsx#L320

We would like backend plugins to be able to easily return error information with the results if necessary -- ideally through arrow metadata, and have errors related to the specific query, not any query in request. 

Should we:
* add DataQueryError to dataFrame (or maybe dataFrame.meta.error?)
* remove it from panelData?  This would require us to create a dummy DataFrame to attach errors to things that did not come from a query -- or where the query exploded.

This change would mean that to check for errors you would have to scan all results and see if any has errors.  The queryRunner could set the panel state to 'error' if *any* dataframe has an error

**Comment by torkelo** [comment]
> This change would mean that to check for errors you would have to scan all results and see if any has errors. The queryRunner could set the panel state to 'error' if any dataframe has an error 

As long as `The queryRunner could set the panel state to 'error' if any dataframe has an error` happens and we dot have to scan the results everywhere. There is also the PanelData.state that has LoadingState.Error
