### ISSUE TITLE
Datasource doc links are broken at Grafana plugin page

### ISSUE THREAD

**Issue by vikkyomkar** [grafana/grafana#21362]
**Steps to reproduce**:
Cloudwatch and elesticsearch doc links are broken at Grafana plugin page
https://grafana.com/grafana/plugins?orderBy=weight&direction=asc&type=datasource
![image](https://user-images.githubusercontent.com/25223784/71831995-fed5a800-30cf-11ea-9030-b7b95eaf3bfc.png)
![image](https://user-images.githubusercontent.com/25223784/71832015-0a28d380-30d0-11ea-954e-09cd55b27478.png)

**Actual Result**:
Doc links are broken

**Expected Result**
Doc links should work properly

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
Grafana version: V6.5
Data source type & version:
User OS & Browser: macOS & chrome
Others:

**Comment by aknuds1** [comment]
From my testing the links aren't broken, they just redirect?
