### ISSUE TITLE
Select: update items container scroll position when navigating with keyboard

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21377]
The Select component, especially the new select, does not reposition custom scrollbar position when navigating with keyboard:

![SelectKeyboard](https://user-images.githubusercontent.com/2376619/71893189-2ddd2f80-314b-11ea-8566-cab3184ce34e.gif)

This means, that for long lists the UX is poor, as the user can not see the currenty highlighted item unless she/he scrolls manually to that list item.

**Comment by boyskila** [comment]
@dprokop is anyone already working on this? I would like to take it if its free

**Comment by dprokop** [comment]
@boyskila no, feel free to pick this one up! 👍

**Comment by tskarhed** [comment]
@boyskila Have you done any work on this?

**Comment by boyskila** [comment]
Yes, I'll try to provide PR soon.

**Comment by boyskila** [comment]
@tskarhed what about when ```Select``` contains ```SelectOptionGroup```? I think it should be expanded once it became a focused item. WDYT?
Also, I can see two ```Select``` components - I guess both should be synced with the ```Scrollbars```, right?
cc @dprokop

**Comment by tskarhed** [comment]
> @tskarhed what about when `Select` contains `SelectOptionGroup`? I think it should be expanded once it became a focused item. WDYT?
> Also, I can see two `Select` components - I guess both should be synced with the `Scrollbars`, right?
> cc @dprokop

I would argue that the use case for groups is covered by the Cascader - maybe we want to remove that feature from SelectBase @dprokop ?

It would be nice to have it fixed in both Select components! Thanks! :)

**Comment by tskarhed** [comment]
Fixed in #22503
