### ISSUE TITLE
Stackdriver Logging datasource

### ISSUE THREAD

**Issue by rdigiorgio** [grafana/grafana#21370]
**What would you like to be added**:

As of now we are able to query and display Stackdriver Metrics into Grafana, I think it would be great to also be able to query and display Stackdriver Logs. I am actually surprised that I was not able to find any issue or pull request about this already.

**Why is this needed**:

This is needed because I want to have my metrics and logs in the same place, making it possible to make dashboards where I could display metrics and logs for a given Stackdriver resource.

**Comment by aocenas** [comment]
Hey @sunker I think you worked on stackdriver a lot recently, do you know if there are plans to do this?

**Comment by sunker** [comment]
No there's no plans to do this at the moment, but I think it's great idea.

**Comment by sunker** [comment]
Questions: 

- Would we want to support both basic and advanced search mode in the query editor? It seems like the basic mode is an abstraction on top of advanced mode (it's using the same api as the advanced mode query), so therefore it would be easier for us to just implement advanced mode.
- In the Logs Viewer it's possible to stream logs. Is there a public api for that? How does it work - polling or web sockets? 
- For Loki there's a feature called [`Show Context `](https://grafana.com/docs/grafana/latest/features/datasources/loki/#log-context), which allows the user to query the surrounding lines of log entry. Would it be possible to do something similar for Stackdriver logs?
- How to link to Stackdriver traces from a log row (can we use the DerivedField feature)?
- Intellisense/suggestions: Is says in the docs: `The suggestions come from both the query language and the set of actual log entries that the Logs Viewer has loaded`. Would it be possible to get access to a query language schema? What parts of a [`LogEntry`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) is part of the query language?

**Comment by stefanforsberg** [comment]
Thank a lot for looking into this, would be great for our dashboards =)

I can't help with any of the interesting question but I'll chip 2c in anyway.

We are only using the advance mode and by your description it seems to make total sense to implement that (first).

When it comes to the new version of Log Viewer seems to be rolled out atm but be available for everyone by March 2nd.

**Comment by sunker** [comment]
Nice, thanks Stefan! Hopefully we can start development within the next couple of weeks. /Erik

**Comment by eli-jordan** [comment]
@sunker We are very interested in this capability too. We are currently planning to export logs to BigQuery then use the BQ plugin. If we could go directly to SD logging that would be great. Is there somewhere I can follow the progress?
