### ISSUE TITLE
[1.9] datasource in scripted dashboard not used

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#2137]
I just tried to create a scripted dashboard that uses a datasource other than the default but this doesn't seem to work. Looking at the panel JSON I can see the correct datasource information filled in but the graph still uses the default one.

**Comment by torkelo** [comment]
Can you show the panel json and config.js?

**Comment by torkelo** [comment]
The panel datasource property must match a key in the datasources config object

**Comment by dennisjac** [comment]
Yes, i provided the datasource object not the name which thinking about it now makes no sense for json data so my mistake. Sorry for the noise.
Using the name works fine.
