### ISSUE TITLE
cant disable sanitizing or multi-value for custom template variable.

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#21386]
**What happened**:

using regex as a custom template variable.
Multi-value  is set off.

```
host =~ /^$host$/
resolves to: "host" =~ /^cpu14\[0-9\]\.math\.\*$/
```

or ...
```
q:"SELECT mean("usage_idle") *-1 + 100 FROM "cpu" WHERE ("host" =~ /^cpu14\[0-9\]\.math\.\*$/ AND "cpu" = 'cpu-total') AND time >= now() - 7d GROUP BY time(10m), "host" fill(none)"
epoch:"ms"
```

This will cause the query to fail.

!! Also note Multi-value is set off but if I add a `,` it will still treat it as a Multi-value... perhaps related to the bug.

**What you expected to happen**:

```
host =~ /^$host$/
resolves to: "host" =~ /^cpu14[0-9].math.*$/
```

**Anything else we need to know?**:

perhaps we need another format like `[[[host]]]` that will skip sanitizing or an option in the template variable screen to disable sanitizing.

... or perhaps a little help message in the template variable screen that talks about sanitizing with the hint I was missing :)

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: influxdb
- OS Grafana is installed on: linux

**Comment by torkelo** [comment]
use `${host:raw}` to disable the regex escaping

**Comment by steverweber** [comment]
thanks!

@torkelo perhaps this issue should be still open until it is more obvious to users to use `:raw`

some help on:
https://grafana.com/docs/grafana/latest/features/datasources/influxdb/#query-variable

and a hit in the UI under the `?`:
would have saved me.

```
Alias patterns

    replaced with measurement name
    $measurement = replaced with measurement name
    $1 - $9 = replaced with part of measurement name (if you separate your measurement name with dots)
    $col = replaced with column name
    $tag_exampletag = replaced with the value of the exampletag tag
    You can also use [[tag_exampletag]] pattern replacement syntax

Stacking and fill

    When stacking is enabled it is important that points align
    If there are missing points for one series it can cause gaps or missing bars
    You must use fill(0), and select a group by time low limit
    Use the group by time option below your queries and specify for example 10s if your metrics are written every 10 seconds
    This will insert zeros for series that are missing measurements and will make stacking work properly

Group by time

    Group by time is important, otherwise the query could return many thousands of datapoints that will slow down Grafana
    Leave the group by time field empty for each query and it will be calculated based on time range and pixel width of the graph
    If you use fill(0) or fill(null) set a low limit for the auto group by time interval
    The low limit can only be set in the group by time option below your queries
    Example: 60s if you write metrics to InfluxDB every 60 seconds

Documentation links:

Grafana's InfluxDB Documentation

Official InfluxDB Documentation

```

**Comment by steverweber** [comment]
created new issue for the multi-value  bug https://github.com/grafana/grafana/issues/21388
