### ISSUE TITLE
custom template variable ignores Multi-value disabled

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#21388]
**What happened**:

custom template variable with a `AA,BB` with Multi-value is set off.

**What you expected to happen**:

value to be `AA,BB` but get `AA` because it splits on the `,`

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: influxdb

**Comment by torkelo** [comment]
use backlash to escape the comma.

**Comment by steverweber** [comment]
@torkelo what purpose does the Multi-value switch provide? .. again perhaps improved on screen help could prevent users like me getting confused.

thanks.

**Comment by torkelo** [comment]
Multi-value switch makes it possible to select multiple values at the same time. You can still define a variable with many possible values (options)

**Comment by steverweber** [comment]
thanks
