### ISSUE TITLE
Embed Scripted dashboard panel into iPanel

### ISSUE THREAD

**Issue by gitRahul** [grafana/grafana#2138]
Embedding a scripted dashboard panel into iFrame yeilds weird results. I've attaching a picture of 2 Iframe.
The graph on the left is an iFrame of a graph from an standard saved dashboard. The graph on the right is the same graph in an iFrame but generated via scripted dashboard.

![grafanascriptedipanel](https://cloud.githubusercontent.com/assets/6994838/8075503/eebb022c-0f0e-11e5-8705-445f7d234b17.png)

< iframe src="http://nykpcr10474n01:3000/dashboard/solo/db/vpn-pog_ldn_prd-on-ldnpsol1022n01?panelId=4&fullscreen&from=now-7d&to=now" width="450" height="200" frameborder="0">< /iframe>
< iframe src="http://nykpcr10474n01:3000/dashboard/script/getDash.js?vpnName=pog_ldn_prd&appliance=ldnpsol1022n01&panelId=4&fullscreen&from=now-6h&to=now" width="450" height="200" frameborder="0">< /iframe>

**Comment by torkelo** [comment]
what is an iPanel? Can you describe what you are doing?

**Comment by gitRahul** [comment]
Sorry, I meant iFrame not iPanel. I am trying embed a single graph in iFrame.

**Comment by torkelo** [comment]
but still confused, embed a grafana graph into grafana?

**Comment by gitRahul** [comment]
Hi Torkel,

I am not sure what you're confused about, not sure why you think i'm embedding grafana graph into grafana, perhaps my writing is not articulate enough, allow me to try again.

I am testing Grafana 2.0 feature of embedding a graph into an iFrame.
http://docs.grafana.org/v2.0/reference/sharing/#embed-panel

The embedding feature doesn't work well when the graph that is being embedded comes from a scripted dashboard. If you look at the picture I posted above, the right graph is an iFrame which embeds a graph from a scripted dashboard into another site.

As always, wonderful job with Grafana.

**Comment by torkelo** [comment]
@gitRahul you write , "The graph on the right is the same graph in an iFrame but generated via scripted dashboard." did you mean left? 

Can you describe in what way the panels differ when in iframe mode? Is it that the annotations are missing or the time range?

**Comment by torkelo** [comment]
oh, now I understand what you are saying. Yea, this is already fixed in master and in the v2.1-pre1 builds (http://grafana.org/download/builds.html)

**Comment by gitRahul** [comment]
Ah, cool, Thanks Torkel, I'll check that out. Sorry for the confusion.
