### ISSUE TITLE
HTTP snapshots API

### ISSUE THREAD

**Issue by gpestana** [grafana/grafana#2139]
In the [github documentation](https://github.com/grafana/grafana/blob/master/docs/sources/reference/http_api.md), the only info about how to create snapshots through the HTTP API is the following:
```
Create new snapshot
POST /api/snapshots

Get Snapshot by Id
GET /api/snapshots/:key
```
I've been looking at the codebase and trying to create snapshots from existing panels but haven't managed so far. 
Would it be possible to be a bit more explicit about how to generate the snapshots through the API and which data do I have to include in the request body? 

Answers for: 
- Is the 'key' the ID of the panel I want to get the snapshot from? 
- How to get the snapshot's URL and create an iframe from that?
 
Would be really helpful to have in the documentation. Once I understand it properly, I will make a pull req to update the documentation.

**Comment by torkelo** [comment]
snapshot API is not probably what you want. The api allows you to create a snapshot. A Snapshot is a dashoard json model with the metric data contained within it. It is used to capture the visible data in a dashboard within the json model to share it externally. 

If you want to use that api you need to post a complete dashboard json with embedded metric data. I am pretty sure that is not what you want? What do you want to do?

**Comment by gpestana** [comment]
Thank you for the prompt answer @torkelo, apreciated!
My main goal is to use some Grafana timeseries graphs in an external webpage and be able to generate the graphs (create dashboards, create the panels and so on..) through the API. The idea is to  make the data push to influxDB and generate+share the plots without using Grafana's interface, only the REST interface.

For example: I got a new timeseries data from a new source, so:
1) I push the data to influxDB as a new series
2) I create a dashboard/panel to represent that data (giving it a uniqueID that I can chose)
3) I get an URL of the correspondent panel where the new data is represented (using REST and both the dashboarID and panelID)

I'd like to have everything automated using only a python script that will be running in the background. 

How do suggest me to do this?

**Comment by torkelo** [comment]
as i said the snapshot api is about storing metric data in dashboard json models so dashboard can be viewed IN Grafana without access to live data sources. 

Sound like you want to render data to PNG images and share images.

**Comment by gpestana** [comment]
@torkelo thank you for the answer!

We changed a bit our specs and will have everything in grafana. But we still need to create dashboards and add rows and panels in an automated way and through the HTTP API.

However, the update dashboard is not working. After make a ``POST /api/dashboards/db`` with the following body:

``
{
    "dashboard": {
        "rows": [
            {}
        ],
        "tags": "",
        "title": "Title-that-already-exists",
        "version": 0,
        "timezone": "browser",
        "schemaVersion": 6,
        "id": 0
    },
    "overwrite": true
}
``

to an existing dashboard, the answer is a ``HTTP 500`` and then I'll have to restart grafana-server, otherwise I can't access any other dashboard in the interface (they're not even listed anymore)

Am I missing anything here?


Thank and nice job :)

**Comment by torkelo** [comment]
if you want to update an existing dashboard you need to specify the id property

**Comment by gpestana** [comment]
With this request:

``POST /api/dashboards/db``
```json
{
    "dashboard": {
        "rows": [
            {}
        ],
        "tags": "",
        "title": "overview",
        "version": 0,
        "timezone": "browser",
        "schemaVersion": 6,
        "id": 8
    },
    "overwrite": true
}
```

I'm getting the same ``500``.

**Comment by torkelo** [comment]
do you get any info in the grafana log for what error is causing the 500 status code?

**Comment by gpestana** [comment]
After making the request:
``2015/06/11 20:33:09 [I] Completed /api/dashboards/db/ 500 Internal Server Error in 78.855677ms``

If I try to make the request again without restart grafana:
``2015/06/11 20:33:17 [I] Completed /api/dashboards/db/overview 404 Not Found in 48.616438ms``

**Comment by torkelo** [comment]
ok, its the tags property that is causing issues. 

Try this: 

```json
{
    "dashboard": {
        "rows": [
            {}
        ],
        "tags": [],
        "title": "overview",
        "version": 0,
        "timezone": "browser",
        "schemaVersion": 6,
        "id": 8
    },
    "overwrite": true
}
```

**Comment by gpestana** [comment]
Alright, it's working now! I'll try to send a pull request on to try to avoid the dashboards to disappear when the request is malformed. It took me some time to realize that I had to restart grafana to get dashboards working again.

One more quick and last question:
When the dahsboard has already many rows and panels. if I want to add a  new panel or row I'll have to:
1) get the dashboard's rows
2) send a POST request as above for overwrite the existing dashboard with the old rows+new row/panel.

Am I right?

I'd suggest a couple of new endpoints on the HTTP API:

```POST /api/dashboards/row``` 
with a new row in the body to add to the dashboard

```POST /api/dashboards/panel```
with a new panel in the body to add to the dashboard.row

What do you think?

**Comment by soelvar** [comment]
Hi Torkel,

Excuse me for stealing this thread, but how do you "render data to PNG images and share images" via API - if possible.

Cheers,
Jesper

**Comment by torkelo** [comment]
@soelvar 
Use the /render/ url action  and then the dashboard and panel id, time range, width / height 
http://play.grafana.org/render/dashboard-solo/db/grafana-play-home?panelId=4&fullscreen&from=1444366815975&to=1444374015975&width=700&height=300

**Comment by soelvar** [comment]
Great - I will give it a try and thanks for the quick reply!

**Comment by soelvar** [comment]
@torkelo 
I tried your example, but the render part returns page not found - would I need to install an extra module or which version of Grafana should i be using (Currently 2.1)?

**Comment by torkelo** [comment]
@soelvar it returns an image for me, or are you taking about using the same feature in your install?

Make sure you have all the needed font pages installed for phantomjs.

**Comment by soelvar** [comment]
@torkelo yes yours work fine:0)...I will have the Ops guy look into it when he has time. Thanks!
