### ISSUE TITLE
grafana docker image name and tag missing

### ISSUE THREAD

**Issue by rajputvishwas** [grafana/grafana#21399]
**What happened**:
I am archiving grafana docker image to a grafana.tar file and later, I am using this tar file and loading the image back to docker.

When I issue docker images command, I am able to see the image but labels and tags are missing.

**What you expected to happen**:
After loading the image, labels and tags should be as per the original image.
grafana/grafana:5.4.3

**How to reproduce it (as minimally and precisely as possible)**:

docker pull grafana/grafana:5.4.3

docker save -o grafana.tar     // save docker image
 
docker load -i grafana.tar    // load docker image

docker images

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.4.3
- OS Grafana is installed on: OKD (3.11)
- User OS & Browser: Ubuntu + Firefox
-

**Comment by aknuds1** [comment]
What is the output you're seeing from `docker images` that differs from what you expect? I followed your procedure, and to me it looks fine:

```
$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
grafana/grafana                                     5.4.3               d0454da13c84        11 months ago       240MB
```

**Comment by rajputvishwas** [comment]
@aknuds1 Yes this is what I expect, but I was getting <none> for REPOSITORY and TAG.

**Comment by rajputvishwas** [comment]
docker load -i grafana.tar
7b4e562e58dc: Loading layer  58.44MB/58.44MB
c61883f6d7a1: Loading layer  3.072kB/3.072kB
f2d8bd23c9c1: Loading layer  28.28MB/28.28MB
63e69b5ec8fb: Loading layer  159.9MB/159.9MB
4a786a04c29c: Loading layer  194.6kB/194.6kB
67796dde2d25: Loading layer   5.12kB/5.12kB
Loaded image ID: sha256:d0454da13c8411af06d6dbd5fa4b291ca30f5de1b53c1d0480c43ab51bdf8071
root@CapstoneNode-Test-new1:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              d0454da13c84        11 months ago       240MB

**Comment by rajputvishwas** [comment]
![image](https://user-images.githubusercontent.com/15668995/71962948-9d711e80-3220-11ea-9e3b-cf9e2885f23e.png)

**Comment by aknuds1** [comment]
Since I could successfully save and load the grafana/grafana:5.4.3 image with Docker on my machine, I can only guess that you have a Docker related problem. I suggest you investigate this with the help of the Docker community. Closing as it doesn't look like a Grafana problem.

There's an error in the `docker save` command you listed FWIW, it should be 
```
$ docker save -o grafana.tar grafana/grafana:5.4.3
````

**Comment by rajputvishwas** [comment]
Thanks @aknuds1
