### ISSUE TITLE
Relative path support for static resources behind reverse proxy with urlrewrite

### ISSUE THREAD

**Issue by simsnow** [grafana/grafana#21400]
**What would you like to be added**:

Could static resources use a relative path, another than html tag `<base href=xxxx>`,
Now: `<base href="/grafana">    <img src="public/images/xxx.png">`
Wanted: `<img src="./public/images/xxx.png">`

**Why is this needed**:

We have many grafana instance running at root_url "/grafana",
http://192.168.3.1/grafana,
http://192.168.3.2/grafana,
http://192.168.3.3/grafana,
They are all running perfectly.

And we have a gateway with route and urlrewrite to serve all the grafana instances:
(Only mean to this, Not real code)
location /grafana/instance1 {
      proxy_pass http://192.168.3.1/grafana;
}
location /grafana/instance2 {
      proxy_pass http://192.168.3.2/grafana;
}
location /grafana/instance3 {
      proxy_pass http://192.168.3.3/grafana;
}
This does not work well, exactly, pages go through, but static resources with wrong url.
For example: 
Page "/grafana/instance1/" have a image `<img src="public/images/xxx.png">`
should have a path "/grafana/instance1/public/images/xxx.png",
but it is "/grafana/public/images/xxx.png" now.

We found that because of the html tag `<base href="/grafana">`, It decided by the root_url, but not support url rewrite. Is there another way instead of `<base href>`?

**Comment by aocenas** [comment]
@marefr do you know if this is solvable? If I understand correctly we use `root_url` for both `base href` and where server listens but here they should have different values.

**Comment by marefr** [comment]
@aocenas don't think it's solvable without code change. It's somewhat related to #6844 and possibly a duplicate since the solution probably would be the same.
