### ISSUE TITLE
Perspective panel plugin

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#21404]
[Perspective](https://perspective.finos.org)

**Comment by ryantxu** [comment]
This should have its own repo in grafana.... not be in the core grafana repo

**Comment by stevenvachon** [comment]
This was created more for the current sprint's project management. Progress is currently at [stevenvachon/grafana-perspective-panel](https://github.com/stevenvachon/grafana-perspective-panel).

**Comment by stevenvachon** [comment]
Moved to https://github.com/grafana/perspective-panel/issues/1.
