### ISSUE TITLE
Allow Azure datasource setup without requiring subscription list access

### ISSUE THREAD

**Issue by burnstreet** [grafana/grafana#21412]
**What would you like to be added**:
Setting up the Azure monitoring datasource by entering the subscription ID manually.

**Why is this needed**:
I want to be able to setup the Azure monitoring datasource without having to grant reader rights on the whole subscription to the application.
After setup, the following Roles seem to suffice for Grafana:
- Subscription Level: Monitoring Reader
- Subscription Level: Log Analytics Reader
- Aplication Insights: Reader
But only to read the subscriptions, as far as I could see, I need to assign the global reader role. Which includes access to user data and as such I do not want to have to grant to a dev tool.

An alternative would be better documentation on how to create a role that includes only the permissions needed for Grafana

**Comment by kylebrandt** [comment]
Perhaps related to https://github.com/grafana/grafana/issues/21868

**Comment by AlskiOnTheWeb** [comment]
We have this same issue. The service principal we use has permissions to access the log analytics data but is not allowed to enumerate anything about the subscriptions for the tenant. This makes it such that no subscription can be entered. Why is it that I can't just manually enter one and am forced to select from a list that can't be provided?

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can't see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
