### ISSUE TITLE
Alert on value change from previous run

### ISSUE THREAD

**Issue by ademxoy** [grafana/grafana#21427]
I want to alert on increasing values.  Is there a way to do it?

So, situation is this:  If errors (discards) are 15kbps 2 minutes ago and errors are 20kbps 1 minute ago, I want fire an alert.  

Condition: 
When avg() of query(A, 2m, now) IS ABOVE avg() of query(A, 1m, now)
instead of second part being a static value. 

I searched online for a while but I could not find an answer.

Thanks,

**Comment by marefr** [comment]
Can't you use diff() instead of avg()?

**Comment by ademxoy** [comment]
> Can't you use diff() instead of avg()?

Figured out the diff() while I was playing around.   Thank you!
