### ISSUE TITLE
Docs feedback: /plugins/developing/snapshot-mode.md

### ISSUE THREAD

**Issue by JosephComputerScience** [grafana/grafana#21425]
Getting plugins to work in snapshot mode is empty.

**Comment by aocenas** [comment]
Seems like there is an issue with the styling as the content is there it is just pushed way down and some is not even visible. When I remove some styles:
<img width="169" alt="Screenshot 2020-01-10 at 11 12 40" src="https://user-images.githubusercontent.com/1014802/72145176-40997380-339a-11ea-9ccb-38025280b693.png">
This shows ok but seems like that styling there is for some reason and it is using `imgbox` custom tag which should be used on other places too.

cc @oddlittlebird @robbymilo

**Comment by oddlittlebird** [comment]
@robbymilo, could you take a look at this?
