### ISSUE TITLE
Dashboad UID does not support dot in the name

### ISSUE THREAD

**Issue by zmlpjuran** [grafana/grafana#21423]
Hi all,
My use case is about using label values from node exporter and create links for individual service dashboards.

From labels you get names of services running in systemd (services=label_values(node_systemd_unit_state,name)).
It includes "postgresql-9.6" value. In dashboard I use repeating panel for services and generate links to detailed dashboards (d/$services). All is fine for all services except ones with dot in the name as dot is not allowed in dashboard UID.
Is there any reason for this? Dot is allowed character in url path.

**Comment by zmlpjuran** [comment]
To be mode precise, the issue is about creating dashboard with dot in UID.

**Comment by torkelo** [comment]
think it's the backend or frontend url router that does not allow it

**Comment by torkelo** [comment]
sorry for closing, but do not think we can support it
