### ISSUE TITLE
Error loading cookies for anonymous user from iframe

### ISSUE THREAD

**Issue by KuvshinovaElena** [grafana/grafana#21420]
**What happened**:
The server version of Grafana v5.3.0 is deployed.
Users can work with him directly using user authentication. Also, one of the graphs is accessed through an iframe on my site using anonymous authentication and a separate organization. After visiting the Grafana page in the same browser, the iframe cookies contain information on this user in grafana_user and an access error occurs to this graph.

**Anything else we need to know?**:
Access to the dashboard is made through the proxy of the apache web server

**Environment**:
- Grafana version: 5.3.0
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome v79.0.3945.117
Requirements:
Internet Explorer version 9 and higher, Mozilla Firefox version 13.0.1 and higher, Google Chrome version 20.0.1132 and higher, Opera version 12.00 and higher

**Comment by aocenas** [comment]
Hey @KuvshinovaElena, can you post a screenshot of the error?

**Comment by KuvshinovaElena** [comment]
Unfortunately, I can’t add a screenshot of the error, because it is limited by the requirements of the company’s security policy.
If you do not log in to the Grafana interface, then the graph is successfully integrated, and everything works fine. But if you log in to the Grafana interface in the same browser as any user, the iframe block contains the message: 

> Web page at https://<ip_host _my _site>/grafana/d-solo/vCNGmH2mz/<name>?panelId=2&orgId=2&from=1578652121088&to=1578655721088&theme=light, may be temporarily unavailable or permanently moved to a new address.

**Comment by aocenas** [comment]
Hmm ok so you do not get something like an access denied error page, the page in the iframe just does not load as if the server was down is that right?

**Comment by aocenas** [comment]
@marefr do you know whether this can be some security setting that logged in users cannot be server through iframe or something like that?

**Comment by marefr** [comment]
@aocenas sounds like the authenticated user does not have access to the anonymous organization?

**Comment by KuvshinovaElena** [comment]
> Hmm ok so you do not get something like an access denied error page, the page in the iframe just does not load as if the server was down is that right?

Yes.
The authenticated user specified in the cookie must not have access to this organization.

**Comment by aocenas** [comment]
Sorry got kind of confused right now.
> The authenticated user specified in the cookie must not have access to this organization.

Is that a requirement you have or is that just a confirmation of the underlying issue?

In any case if you get `might be temporarily down or it may have moved permanently to a new web address.` page when trying to access Grafana then I would assume the issue is outside of Grafana. Maybe some issue with the proxy? Because if it was authentication issue in Grafana I think you would get http response with 403 status or something like that.

Would it be possible for you to test this behaviour without the proxy server?

**Comment by KuvshinovaElena** [comment]
We use Grafana for two different purposes: directly through the Grafana interface and to display a graph in our interface through an iframe. This separation is based on 2 different organizations. This is a requirement.

The problem is in the iframe cookies being sent that contain user data authorized in the Grafana interface. Is there any way to disable these cookies?

**Comment by marefr** [comment]
@KuvshinovaElena please add the user as viewer to the other organization,
