### ISSUE TITLE
Stackdriver timeouts concurrent queries over large time periods with "Client.Timeout exceeded while awaiting headers"

### ISSUE THREAD

**Issue by schaffino** [grafana/grafana#21426]
**What happened**:

We are using the stackdriver datasource to for dashboarding with grafana against some log based metric data sources. It's working well for some dashboards, but we frequently encounter the following error in certain dashboards when increasing the time period they run over.

```
Get https://content-monitoring.googleapis.com/v3/projects/my-gcp-project/timeSeries?my-stackdriver-query&view=FULL: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

One dashboard works perfectly fine for a 12 hr period and under, but as soon as we set it to 24 hours every graph fails to load in batches of 6 with the above error.

We noticed that the failures start coming in after almost exactly 30 seconds until all panels have failed to load. We found issue #15258 discussing a timeout setting on datasources that defaults to 30. We tried modifying the given setting as below to see if this would have any effect.

```
[dataproxy]

timeout = 300
```

We then confirmed that this setting is active by querying the admin API. We are still getting errors after exactly 30 seconds.

We noticed that we could run refreshes on individual graphs and they would complete fine. Guessing that this is some sort of rate limiting on the google side we then pulled some of the queries out of grafana to see how fast they complete on their own .

Taking the queries from the first 6 graphs and running these directly against stackdriver outside of grafana we found ta single query would complete in ~10 seconds, but when running concurrently, all ended up returning after 50 seconds or so.

So we appear to be getting some pretty severe rate limiting from the google side, but the queries **do** complete and return all requested data.

**What you expected to happen**:

Dashboards to eventually load once stackdriver returned all data for each query and dataproxy timeout settings are respected.

**How to reproduce it (as minimally and precisely as possible)**:

Create some log based metrics in stackdriver with a high volume and cardinality. Once you have a couple days data, create a dashboard with several graphs and try and refresh it with a time period over 24 hours.

**Anything else we need to know?**:

The severe  throttling we see only seems to happen with user created metrics. Google provided metrics all return in a fraction of the time. We'd also be able to work around the issue if we could limit the number of panels that are refreshed concurrently.

I'm well versed in GO, but it looks like this pull #15356 sets the timeout so that it's only on the Dial in the transport for the initial connection, and then hardcodes actual timeout for http clients used for a datasource to 30s.

**Environment**:
- Grafana version: Grafana v6.5.0 (24a5d2f)
- Data source type & version: Stackdriver builtin
- OS Grafana is installed on: COS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by schaffino** [comment]
That should say i'm not well versed in GO :)

**Comment by marefr** [comment]
Each stackdriver query/request is running one by one after eachother so not sure Grafana can do anything to resolve this if you get hit by rate limiting?

**Comment by schaffino** [comment]
@marefr 
I think the issue here is that regardless of any rate limiting on the google side, the queries are being cancelled on the grafana side after 30 seconds due to settings of the http client. Running the same queries outside of grafana causes the results to return properly. Given i have modified the datasource settings to a a 10 minute timeout i would expect that to be honored but it doesn't seem to be.

Google support have helped find a solution 99% of the failures we are seeing though, with it only occurring now on a couple of select high volume metrics over very long time periods.

For anyone else facing the same problem, the solution is as follows. Every graph created from stackdriver should have resource.type in the filter. With this change the majority of my dashboards are now loading in a fraction of the time and the 30 second timeout is hardly ever being reached. I have a couple of metrics that return multiple resource.types, which has meant adding a second query to pull them in, as you can only use equality operators for resource.type. But with these changes i'm getting far far better performance and no longer hitting the 30s dataproxy timeout.

**Comment by torkelo** [comment]
ok, glad you found a solution

**Comment by luvpreetsingh** [comment]
adding resource.type is key the here
