### ISSUE TITLE
Table visualization of Annotations is not showing titel and timeend

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [grafana/grafana#21434]
**What happened**:
When using a table to visualize region annotations it is not showing the (new) _timeend_ column.
Also the Title is empty. 

**What you expected to happen**:
All Columns from my annotation should be shown.
The Title Column should show the Name of the Annotation

**How to reproduce it (as minimally and precisely as possible)**:
Add an annotation with a _timeend_ column. 
Add a new visualization as a table.
Set the _Data Table Transform_  to be _Annotation_

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v6.6.0-pre (fe61f6b7a7)
- Data source type & version: SQL server 2017 is used as datasource for the annotations
- OS Grafana is installed on: Windows
- User OS & Browser: Windows 10/Chrome
- Grafana plugins: -
- Others: -

![2020-01-10_10h40_55](https://user-images.githubusercontent.com/26311915/72143078-56a53500-3396-11ea-9594-ab1b89684ea7.png)

**Comment by torkelo** [comment]
Title is something else, deprecated part of an annotation event

**Comment by Jens-H-Eriksen** [comment]
Okay.... but it would be nice if the _Title_ could be the _name_ of the Annotation. In my case I have 3 different kinds of annotations and the _Title_ would then be the way to distinguish between them in the table. At least it should not be there if it is deprecated.
