### ISSUE TITLE
Grafana query builder does not add the mostDeviant function with its values in the right order to work with Graphite

### ISSUE THREAD

**Issue by phrend** [grafana/grafana#2144]
When adding the `mostDeviant` function through the Grafana query builder (clicking the `+`), the way Grafana builds the query does not work. (I tested this on http://play.grafana.org/ and it is broken there as well.)

If I take this base query (that works)

    apps.fakesite.*.counters.requests.count

...then add `mostDeviant` using the `+` function in the query builder, it results in the following query (which does not work)

    mostDeviant(apps.fakesite.*.counters.requests.count, 2)

...but, if I click the `pencil` and modify the query like this, then it works (just changing the order of the values passed to `mostDeviant`)

    mostDeviant(2, apps.fakesite.*.counters.requests.count)

This seems like it's really either a Graphite bug, or the Graphite documentation is wrong, but I'd like the Grafana UI to work with the way Graphite is currently:
http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.mostDeviant

**Comment by torkelo** [comment]
@phrend this is actually a bug in Graphite-web, this is the only function that breaks the convention of having series first then params. 

This is fixed in graphite-web (master branch), https://github.com/graphite-project/graphite-web/pull/279
