### ISSUE TITLE
Alert display assumes threshold is scale compatible with left axis

### ISSUE THREAD

**Issue by tronar** [grafana/grafana#21445]
**What happened**:
Adding a diff() alert creates a red line that is meaningless. 
I guess sum() and count() have the same issue.
Also, the alert uses (always) the left axis, even when the referenced query is right axis assigned.

**What you expected to happen**:
Threshold only drawn for compatible aggregation functions, or made optional.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert based on diff(). The "offset" between first and last values has not the same scale as the values, so the threshold line is meaningless.

**Anything else we need to know?**:
This is aggravated by the current diff() returning abs(diff()) for a temperature rising for too long IOT use case I have.

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Prometheus 2.13.0
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows 7 / Firefox 72.0.1
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
yea, agree! 

we plan to make alert rules standalone (seperate) from graph panel / dashboard. so will try to remember this.

dupe / similar to : https://github.com/grafana/grafana/issues/7258
