### ISSUE TITLE
CloudWatch validation error, generated query exceeding 1024 characters

### ISSUE THREAD

**Issue by alecxvs** [grafana/grafana#21442]
**What happened**:
After upgrading from 6.3 to 6.5, some CloudWatch dashboards are breaking because there are many values in the template variables and it's generating a query expression that is too large.

**What you expected to happen**:
The query should work

**How to reproduce it (as minimally and precisely as possible)**:
Create a template variable with many values (like Lambda function name). Query for metrics by the FunctionName dimension.

**Anything else we need to know?**:
Grafana should be able to split the query into multiple expressions and combine the return data.

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OSX / Chrome

**Comment by dneth** [comment]
> Grafana should be able to split the query into multiple expressions and combine the return data.

It should be possible to do that within the same request to keep costs low.  But even if the implementation were to make separate requests, the cost of the requests is still lower than the engineering cost of redesigning dashboards to work around the new limitation.

**Comment by marefr** [comment]
Please read upgrade notes https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v6-5

This works as intended.

**Comment by sunker** [comment]
Yes, @marefr pointed out, this works as expected. Some users might have this problem, but for most user's the migration to GMD will be a good thing. 

> Grafana should be able to split the query into multiple expressions and combine the return data.

That is technically possible, but will make it much harder to maintain this datasource so we won't do that.
