### ISSUE TITLE
Cog at top-right next to Cycle View mode should be a pencil

### ISSUE THREAD

**Issue by jsoref** [grafana/grafana#21443]
**What happened**:
Load Grafana:
![image](https://user-images.githubusercontent.com/2119212/72183864-0c837a00-33bd-11ea-8adf-d8bbf4814141.png)

There are two cogs, one at the top right, and a second on the left

**What you expected to happen**:
Don't use the same visual indicator for two different actions.

Clicking the top right Cog results in an "editview" task. Edit view tasks in modern UX are generally indicated with a pencil ✎.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- User OS & Browser:
- Grafana plugins: Alert List, Bar Gauge, CloudWatch, Dashboard list, Gauge, Getting Started, Graph, Graphite, Heatmap, InfluxDB, Logs, Loki, Prometheus, Singlestat, Table, TestData DB, Text, ...

---
I'm happy to provide a PR for this.

**Comment by torkelo** [comment]
Not sure I agree, they both go into settings / configuration views, why should one be cog and other pencil and not the other way around. Better to be consistent. Pencil is for launching an edit / modify action. 

But thanks for feedback, will take it up with UX team
