### ISSUE TITLE
504 gateway timeout (Server didn’t respond)

### ISSUE THREAD

**Issue by prathap12** [grafana/grafana#21444]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
We are running Grafana version 6.1.6, running on the Linux server. We are pulling data wmi exporter, which exposes a Prometheus running on an open shift.
on dashboard 10 graph panel are there out of three panels is time out
can anyone help me on this issue

Error: 504 gateway timeout (Server didn’t respond)
how to increase the timeout grafana
please help out where I need to make changes
Thank you

**Comment by torkelo** [comment]
You have a query timeout option in the data source settings view

**Comment by enc** [comment]
@torkelo I search on the internet and nothing useful is being found. Only the same info that does not help. This issue was not solved.

**Comment by rabbitdew** [comment]
Is the 504 Gateway Timeout you're seeing actually coming from Grafana?

I had a similar problem, and am using an Nginx reverse proxy in front of Grafana. 

I was able to resolve it by setting the Nginx proxy_read_timeout to a higher value.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I cannot see this setting in my datasource configuration? has it moved somewhere else? I also get this 504 error for long running queries..
