### ISSUE TITLE
"On Time Range Change" Invalid

### ISSUE THREAD

**Issue by lsj9383** [grafana/grafana#21453]
**What happened**:
"On Time Range Change" Invalid

**What you expected to happen**:
I want to refresh the value of “hostname” every time I change the time range.

However, the “hostname” value is not refreshed after changing the time range.

What else do I need to configure?

![image](https://aws1.discourse-cdn.com/standard14/uploads/grafana/optimized/2X/a/a19a5391b33211d694e19fcabb63105bed76c9ad_2_1380x520.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version:
- OS Grafana is installed on: CentOS 7.x
- User OS & Browser: MacOS & Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
strange, can you have chrome dev tools & network tab open as you change time range?

**Comment by lsj9383** [comment]
Yes, I can.

In my demo, there will be different "hostname" for different time range.
When I select "the last 5 minutes", http request body is:
{"queries":[{"queryType":"query","target":"query","refId":"A","type":"timeserie","datasourceId":1,"query":"*|SELECT server_name GROUP BY server_name"}],"from":"1578763786785","to":"1578850186785"}

Obviously, this time range is not 5 minutes.
1578763786: 2020-01-12 01:29:46 (Beijing)
1578849816: 2020-01-13 01:29:46 (Beijing)

![](https://signalping.oss-cn-beijing.aliyuncs.com/1578850342655.jpg)

but, "host in panle" is right (query expression is the same)

**Comment by lsj9383** [comment]
So, no matter what I choose, the time range of the request is always one day

**Comment by lsj9383** [comment]
> strange, can you have chrome dev tools & network tab open as you change time range?

**Comment by lsj9383** [comment]
> strange, can you have chrome dev tools & network tab open as you change time range?

So, no matter what I choose, the time range of the request is always one day.

And you can access the grafana site to test: http://qa.signalping.com
username & password: guest / guest123

**Comment by torkelo** [comment]
looks like it's a problem with the data source plugin your using

**Comment by lsj9383** [comment]
Why is the time range in the request body related to the data source plugin?
