### ISSUE TITLE
Loki: Automatically switch between metrics or logs based on the query

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#21451]
**What would you like to be added**:

I would like panels to be automatically switched between logs and metrics when writing queries in explore Loki. I don't think it's a good user experience to show an error that could be resolved automatically.

**Why is this needed**:

Who likes to click on a button when it is not required :)

**Comment by owen-d** [comment]
I think this is a fantastic idea!

**Comment by Dieterbe** [comment]
is it always obvious from a response body whether it's metrics or logs? can it be more than one?

**Comment by owen-d** [comment]
@davkal I think you might be interested here

**Comment by davkal** [comment]
@kaydelaney is working on this already.

**Comment by owen-d** [comment]
Yes @Dieterbe loki returns it's data type along with the data itself:
```
const (
	ResultTypeStream = "streams"
	ResultTypeVector = "vector"
	ResultTypeMatrix = "matrix"
)
```

**Comment by kaydelaney** [comment]
Solved by https://github.com/grafana/grafana/pull/25890/
