### ISSUE TITLE
Show daytime bands on graphs

### ISSUE THREAD

**Issue by Neex101** [grafana/grafana#21450]
**What would you like to be added**:
On graphs where the time-base spans more than a day, it would be great to be able to see the start and ends of the day by employing a simple greyscale banding scheme for the graph background. This could be driven with a custom daily start/finish field, or driven by local daylight data.

**Why is this needed**:
The end point of Grafana is about visually communicating data at an exceptional level of quality. Currently long time base graphs take an extra step of visual absorption by needing to inspect the X axis for each graph, or making an effort to understand the relevance of the gridlines. Eliminating this step with a banding system (more relevant than just grid lines) would streamline data absorption in a more intuitive way.

**Comment by marefr** [comment]
You should be able to solve this with time regions feature of the graph panel, see https://grafana.com/docs/grafana/latest/features/panels/graph/#time-regions.

**Comment by Neex101** [comment]
Many thanks

**Comment by tablatronix** [comment]
#35486
