### ISSUE TITLE
Templating: Links and multi valued variables that set variables via URL 

### ISSUE THREAD

**Issue by Schmaetz92** [grafana/grafana#21459]
Hello, 
I'm currently trying to embed defined variables, which can take several or all values, into custom html links of a panel. But the problem is that the available options:

- $var_name
- [[var_name]]
- ${var_name:glob}
- ${var_name:regex}
- ${var_name:pipe}
- ${var_name:csv}
- ${var_name:json}
- ${var_name:distributed}
- ${var_name:lucence}
- ${var_name:percentencode}
- ${var_name:glob}

do not allow correct use. 

The own links of grafana create for example the following link if selected more than once: 
.../?var_name=xy&var_name=yz
However, I cannot illustrate this with the above possibilities. 

Therefore I would like to ask if there is a possibility for it or if something like this can be created. 

The reason not to create links with the integrated possibility is the missing overview of many links. 
Therefore the whole thing should be sorted and displayed clearly using HTML.

With best regards

**Comment by torkelo** [comment]
similar problem to https://github.com/grafana/grafana/issues/20733

**Comment by johnpemberton** [comment]
I _think_ I'm experiencing a similar problem.   I'm trying to enable a multi select for clusters on the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project, but the links are difficult to overcome. 

If I select more than one cluster, then the URL contains `var-cluster=a&var-cluster=b`, but the `$cluster` variable is `a,b` so it seems impossible to pass multiselect variables in dashboard links, unless I'm missing something obvious.

Issue I'm trying to solve for reference: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/444

**Comment by Muraliprasath** [comment]
@torkelo , @dprokop -

This issue can be resolved by creating a customTemplateFormatingfn
Workaround, which will format the URL as to satisfy the requirements,

Code changes: 
File Path : public/app/features/templating/template_srv.ts
In formatValue Funcion, we can create a custom case something similar like distributed, and we will the below formatting fn

CustomTemplateURLFormatter(value: any, variable: any) {
value = _.map(value, (val: any, index: number) => {
if (index !== 0) {
return **'var-'** + variable + '=' + val;
} else {
return val;
}
});
return value.join(**'&'**);
}

Above piece of code, is working fine, while mutli selecting variables.
Kindly share your comments over this.

Regards,
Murali Prasath V
