### ISSUE TITLE
Test plugins for digest issues with new version of backendSrv

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#21460]
Plugins that might be affected by change:

- [x] ~~grafana-piechart-panel~~
- [x] ~~grafana-clock-panel~~
- [x] alexanderzobnin-zabbix-app 
- [x] ~~grafana-worldmap-panel~~
- [x] ~~vonage-status-panel~~
- [x] ~~natel-discrete-panel~~
- [x] ~~grafana-simple-json-datasou...~~	
- [x] ~~briangann-gauge-panel~~
- [x] ~~jdbranham-diagram-panel~~
- [x] raintank-worldping-app	
- [x] ~~natel-plotly-panel~~
- [x] ryantxu-ajax-panel	
- [x] ~~briangann-datatable-panel~~
- [x] ~~camptocamp-prometheus-alert...~~	
- [x] ~~mtanda-histogram-panel~~
- [x] ~~petrslavotinek-carpetplot-p...~~
- [x] ~~yesoreyeram-boomtable-panel~~
- [x] ~~flant-statusmap-panel~~
- [x] ~~grafana-polystat-panel~~
- [x] ~~michaeldmoore-multistat-pan...~~
- [x] ~~savantly-heatmap-panel~~
- [x] ~~michaeldmoore-annunciator-p...~~
- [x] ~~snuids-trafficlights-panel~~
- [x] grafana-kubernetes-app	
- [x] ~~neocat-cal-heatmap-panel~~
- [x] ~~snuids-radar-panel~~
- [x] ~~btplc-trend-box-panel~~
- [x] ~~bessler-pictureit-panel~~
- [x] ~~natel-influx-admin-panel~~
- [x] ~~digrich-bubblechart-panel~~
- [x] ~~btplc-status-dot-~~
- [x] simpod-json-datasource	
- [x] digiapulssi-breadcrumb-pane...	
- [x] ~~farski-blendstat-panel~~
- [x] vertamedia-clickhouse-datas...	
- [x] ~~blackmirror1-singlestat-mat...~~	
- [x] ~~percona-percona-~~
- [x] ~~fatcloud-windrose-~~
- [x] ~~btplc-peak-report-~~
- [x] ~~agenty-flowcharting-~~
- [x] jasonlashua-prtg-
- [x] novalabs-annotations-
- [x] ~~satellogic-3d-globe-~~
- [x] ~~marcuscalidus-svg-~~
- [x] ~~btplc-alarm-box-~~
- [x] ~~pr0ps-trackmap-~~
- [x] ~~corpglory-progresslist-pane~~
- [x] ~~blackmirror1-statusbygroup~~
- [x] ~~goshposh-metaqueries-dataso...~~
- [x] digiapulssi-organisations-p...
- [x] ~~citilogics-geoloop-panel~~
- [x] ~~mtanda-heatmap-epoch-panel~~
- [x] ~~mxswat-separator-panel~~
- [x] ~~yesoreyeram-boomtheme-panel~~
- [x] fetzerch-sunandmoon-datasou...
- [x] ~larona-epict-panel~
- [x] cloudflare-app
- [x] ~~zuburqan-parity-report-pane...~~
- [x] ~~pierosavi-imageit-panel~~
- [x] ntop-ntopng-datasource	
- [x] sni-pnp-datasource	
- [x] ~~smartmakers-trafficlight-pa...~~
- [x] ~~grafana-image-renderer~~
- [x] abhisant-druid-datasource
- [x] ~~fzakaria-simple-annotations...~~
- [x] ~~fastweb-openfalcon-datasour...~~
- [x] ddurieux-glpi-app	
- [x] ~~grafana-influxdb-flux-datas...~~
- [x] ~~scadavis-synoptic-panel~~
- [x] mtanda-google-calendar-data...	
- [x] ~~grafana-influxdb-08-datasou...~~
- [x] ~~andig-darksky-datasource~~
- [x] stagemonitor-elasticsearch-...	
- [x] ~~ayoungprogrammer-finance-da...~~
- [x] ~~praj-ams-datasource~~
- [x] kentik-app	
- [x] ryantxu-annolist-panel
- [x] ~~foursquare-clouderamanager-...~~	
- [x] ~~grafana-kairosdb-datasource~~
- [x] ~~gnocchixyz-gnocchi-datasour...~~
- [x] ~~bosun-datasource~~
- [x] ~~doitintl-bigquery-datasourc...~~
- [x] bosun-app
- [x] ns1-app	
- [x] grafana-azure-monitor-datas...	
- [x] ~~monitoringartist-monitoring...~~
- [x] ~~hawkular-datasource~~
- [x] opennms-helm-app
- [x] raintank-snap-app	
- [x] ~~gretamosa-topology-panel~~
- [x] ~~xginn8-pagerduty-datasource~~
- [x] ~~gridprotectionalliance-osis...~~
- [x] grafana-azure-data-explorer...
- [x] voxter-app	
- [x] sbueringer-consul-datasourc...	
- [x] belugacdn-app	
- [x] ~~monasca-datasource~~
- [x] ~~radensolutions-netxms-datas...~~
- [x] ~~rackerlabs-blueflood-dataso...~~
- [x] instana-datasource
- [x] ~~ibm-apm-datasource~~
- [x] ~~gridprotectionalliance-open...~~
- [x] moogsoft-aiops-app	
- [x] ~~moogsoft-aiops-datasource~~
- [x] ~~udoprog-heroic-datasource~~	
- [x] ~~dalmatinerdb-datasource~~
- [x] ~~linksmart-hds-datasource~~
- [x] ~~sidewinder-datasource~~
- [x] ~~skydive-datasource~~
- [x] grafana-sensu-app
- [x] oci-datasource	
- [x] natel-usgs-datasource	
- [x] ~~devicehive-devicehive-datas...~~
- [x] sni-thruk-datasource
- [x] ~~linksmart-sensorthings-data...~~
- [x] ~~akumuli-datasource~~
- [x] ovh-warp10-datasource	
- [x] devopsprodigy-kubegraf-app	
- [x] ~~alexandra-trackmap-panel~~
- [x] raintank-kubernetes-app
- [x] ~~logzio-datasource~~
- [x] ~~cognitedata-datasource~~
- [x] ~~paytm-kapacitor-datasource~~
- [x] ~~quasardb-~~
- [x] ~~dlopes7-appdynamics-datasou...~~
- [x] ~~macropower-analytics-panel~~
- [x] ~~sraoss-sunburst-panel~~
- [x] ~~grafana-datadog-datasource~~
- [x] ~~grafana-splunk-datasource~~
- [x] ~~grafana-newrelic-datasource~~
- [x] ~~jeanbaptistewatenberg-perce...~~
- [x] ~~sileht-gnocchi-datasource~~
- [x] ~~vertica-grafana-datasource~~
- [x] ~~grafana-oracle-datasource~~
- [x] ~~spotify-heroic-datasource~~
- [x] ~~grafana-dynatrace-datasourc...~~
- [x] ~~grafana-strava-datasource~~
- [x] ~~grafana-stackdriver-datasou...~~
- [x] ~~grafana-servicenow-datasour...~~

------

- [x] Checked and might be affected
- [x] ~~Checked and not affected~~

**Comment by mckn** [comment]
After a first check of the plugins this is the one that we properly need to test:

- [ ] alexanderzobnin-zabbix-app
- [ ] raintank-worldping-app
- [ ] ryantxu-ajax-panel
- [ ] grafana-kubernetes-app		
- [ ] digiapulssi-breadcrumb-pane...	
- [ ] jasonlashua-prtg-
- [ ] novalabs-annotations-
- [ ] digiapulssi-organisations-p...
- [ ] cloudflare-app
- [ ] ddurieux-glpi-app	
- [ ] stagemonitor-elasticsearch-...
- [ ] kentik-app	
- [ ] ryantxu-annolist-panel
- [ ] bosun-app
- [ ] ns1-app	
- [ ] grafana-azure-monitor-datas...
- [ ] opennms-helm-app
- [ ] raintank-snap-app	
- [ ] grafana-azure-data-explorer...
- [ ] voxter-app	
- [ ] sbueringer-consul-datasourc...	
- [ ] belugacdn-app
- [ ] instana-datasource
- [ ] moogsoft-aiops-app	
- [ ] grafana-sensu-app
- [ ] oci-datasource	
- [ ] natel-usgs-datasource	
- [ ] sni-thruk-datasource
- [ ] ovh-warp10-datasource	
- [ ] devopsprodigy-kubegraf-app	
- [ ] raintank-kubernetes-app

**Comment by dprokop** [comment]
@hugohaggmark @mckn I assume we can close this already, right?

**Comment by hugohaggmark** [comment]
I think it could be good to keep it open, so we can add potentially affected plugins to changelog for 6.6
