### ISSUE TITLE
Bug - Elasticsearch annotations doesn't work properly (08.06 build)

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#2147]
Hi,

I've observed that Elasticsearch annotations (in the latest build) work only when using fixed time range from the drop-down menu. When using custom selected time period Grafana sends POST request like:

`...{"timestamp":{"from":"2015-06-11T06:41:01.074Z","to":"2015-06-11T06:59:35.014Z"}}`

with the timestamp format like `'yyyy-MM-dd’T'HH:mm:ss.SSSZZ'` which cannot be properly interpreted by Elasticsearch. Log meessage shows:

`ElasticsearchParseException: failed to parse date field [2015-06-10T02:08:13.947Z], tried both date format [yyyy-MM-dd HH:mm:ss.SSS], a nd timestamp number`

When using fixed period the POST request looks like below:

`...filter":{"bool":{"must":[{"range":{"timestamp":{"from":"now-6h","to":"now"}}}]}}}},"size":10000}`

Moreover the annotation tooltip window is never displayed.

**Comment by torkelo** [comment]
Just tested this, that query works fine for me. What version of elasticsearch do you have? How have you saved the date when you indexed data into elasticsearch?

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/8111954/06a7d9ee-1065-11e5-97f1-d6b6e7491742.png)
