### ISSUE TITLE
Bar graph width doesn't match aggregation period

### ISSUE THREAD

**Issue by tikoflano** [grafana/grafana#21473]
I think that when using aggregated values the bar width should match the aggregation period. When querying data from my MySQL with a 1d aggregation period the bar is about "16hrs wide". I've tested with 1h and gives "40m wide" and with 20m gives "13m wide".

Here is my query
```
SELECT
  $__unixEpochGroupAlias(timestamp, $__interval, 0),
  count(activity_id) AS "new files"
FROM activity
WHERE
  type = "file_created"
GROUP BY $__unixEpochGroup(timestamp, $__interval, 0)
ORDER BY $__unixEpochGroup(timestamp, $__interval, 0)
```
I'm setting th **$__interval** using the **_Min time interval_** option.

![image](https://user-images.githubusercontent.com/6231202/72275743-45b22900-360d-11ea-8d95-623dfe083bb0.png)

Pretty sure that those bars should be "1d" wide, right? Also I've just noticed that the hover tooltip shows the data right. In teh image note that the red line is showing a value of 12 while it is not over the bar (but is over where it is supposed to be).

Or there is something I'm missing that is making the bar show slimmer?

**Using Grafana 6.5.2 running on Docker**

**Comment by torkelo** [comment]
Can you use query inspector and show the raw data points (times) that your query returns? think this is due to the last day, it is not complete (it ends in 16:00) so the shortest time between two data points is less then a day, which is why the bars do not cover a full day. The bar width is calculated to be the same as the shorted distance between two data points.

**Comment by tikoflano** [comment]
This is what the query inspector shows:

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1578331161596",
      "to": "1578935961596",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 86400000,
          "maxDataPoints": 960,
          "datasourceId": 1,
          "rawSql": "SELECT\r\n  $__unixEpochGroupAlias(timestamp,1d,0),\r\n  count(activity_id) AS \"new files\"\r\nFROM activity\r\nWHERE\r\n  type = \"file_created\"\r\nGROUP BY $__unixEpochGroup(timestamp,1d,0)\r\nORDER BY $__unixEpochGroup(timestamp,1d,0)",
          "format": "time_series"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 5,
          "sql": "SELECT\r\n  timestamp DIV 86400 * 86400 AS \"time\",\r\n  count(activity_id) AS \"new files\"\r\nFROM activity\r\nWHERE\r\n  type = \"file_created\"\r\nGROUP BY timestamp DIV 86400 * 86400\r\nORDER BY timestamp DIV 86400 * 86400"
        },
        "series": [
          {
            "name": "new files",
            "points": [
              [
                0,
                1578268800000
              ],
              [
                0,
                1578355200000
              ],
              [
                0,
                1578441600000
              ],
              [
                0,
                1578528000000
              ],
              [
                12,
                1578614400000
              ],
              [
                0,
                1578700800000
              ],
              [
                2,
                1578787200000
              ],
              [
                11,
                1578873600000
              ]
            ]
          }
        ],
        "tables": null,
        "dataframes": null
      }
    }
  }
}
```

**Comment by torkelo** [comment]
Oh, data looks evenly spaced on date interval even for last time point. 

Think the reason the bar is not exactly a day wide is to leave space between bars (the bar size is set to 50% of the distance between data points). 

You can use staircase mode (plus lines) to showcase more accurately the exact distance between data points

**Comment by tikoflano** [comment]
Thanks. That worked. The only problem with that approach is that the last data won't have any width (right graph). It would be better to allow us to modify that min space between bars.

![image](https://user-images.githubusercontent.com/6231202/72290410-e6174600-362b-11ea-86c4-9dc07f497e1c.png)

I managed to force it to have a width (left graph) by artificially adding a record for tomorrow modifying my query as follows:

```
SELECT
  $__unixEpochGroupAlias(timestamp, $__interval, 0),
  COUNT(activity_id) AS "new files"
FROM activity
WHERE
  type = "file_created"
GROUP BY 1
UNION ALL SELECT $__unixEpochTo() + IF('$__interval' LIKE '%m', '$__interval' * 60, IF('$__interval' LIKE '%h', '$__interval' * 3600, IF('$__interval' LIKE '%d', '$__interval' * 86400, '$__interval'))) , 0
ORDER BY 1
```

Thanks for your help!
