### ISSUE TITLE
compiling failed after login_ctrl.ts code revised

### ISSUE THREAD

**Issue by sasaluo** [grafana/grafana#21477]
**What would you like to be added**:
I need to change  request method in login_ctrl.ts for security risk. my way is  using $http alone in login,and using http request in backend_srv after log in. Howeverafter chaning code in login_ctrl, i execute command  npm install -g yarn   yarn install --pure-lockfile npm run build,error occured
 so how can i execute command above success when i add just like console.log('aaa) in login_ctrl.ts

**Why is this needed**:
as far as i know,the framework use cookie to save data like token,when i close the page after log in, i can still open page without log in nest time in the same browser for cookie period is 30 days.

**Comment by ryantxu** [comment]
not sure how to help here... changing the login page/process is not really supported, so your mileage my vary :)
