### ISSUE TITLE
Add cm as a length unit

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [grafana/grafana#21486]
**What would you like to be added**:
'cm' (centimeter) as lenght unit

**Why is this needed**:

![2020-01-14_13h31_35](https://user-images.githubusercontent.com/26311915/72344777-5d071a00-36d2-11ea-8183-1ffe8dced1b3.png)

**Comment by marefr** [comment]
See https://github.com/grafana/grafana/issues/2968#issuecomment-561603133
