### ISSUE TITLE
Grafana do not send rendered image when it was created to slack

### ISSUE THREAD

**Issue by dsuievalov** [grafana/grafana#21485]
**What happened**:
Configured remote image-rendered service according to the doc (https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service) and point Grafana on it with env variables:
```bash
export GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
export GF_RENDERING_CALLBACK_URL=http://grafana/
```

Alert is configured to send images to slack:

![Screenshot 2020-01-14 at 13 04 55](https://user-images.githubusercontent.com/59164447/72339166-80c86100-36ce-11ea-8512-9f96caacb9de.png)

When alert triggers, images are rendered and stored in `/var/lib/grafana/png/`:

```bash
bash-5.0$ ls /var/lib/grafana/png/
4BiI6YK4vXJlvPkyPmEw.png  Hy9RGnm8UEcE9go62WPn.png  S42R90D1UCqi8Hjor0kb.png  fyKzHUs9g9eYZxBXvLF0.png  liv34PFf24HcO4RwoYdT.png  pBRDxIh3bpIhQInZuZfx.png  yma06LBz7Qpuwm8MDv76.png
Hr4XiCyjvAx3Uk6IYrNY.png  KvVZ76wlu05HLCRtXwRZ.png  e04wNp60FnvjqfOC18bc.png  l46UbQHWDEgwo2Swi6nM.png  oRBmgcLzwgPFqZuDoCDE.png  pPWhJLdOqOsPMaaoOAp7.png  z1wUuSUu1rTtT3yoHzQV.png
```

But they are not being sent to slack:

![Screenshot 2020-01-14 at 13 08 14](https://user-images.githubusercontent.com/59164447/72339467-f59b9b00-36ce-11ea-9684-07019040225b.png)

In compare to `Send Test` that works without issue:

![Screenshot 2020-01-14 at 13 09 04](https://user-images.githubusercontent.com/59164447/72339512-0f3ce280-36cf-11ea-9ed0-06b4211277d9.png)

**What you expected to happen**:

Grafana should send images to slack.

**How to reproduce it (as minimally and precisely as possible)**:

- trigger alert in slack
- see that image is not being sent

**Anything else we need to know?**:

Differ from https://github.com/grafana/grafana/issues/21018 since the image is being rendered but not sent.

Built custom grafana image with image renderer preinstalled (https://grafana.com/docs/grafana/latest/installation/docker/#with-grafana-image-renderer-plugin-pre-installed) but the result is the same.

Dashboard json - https://gist.github.com/dsuievalov/2bfa65bab522f9a433f9e7d32c456570#file-render-test-dashboard-json

Grafana rendering image service logs:

```bash
render request recieved for http://grafana/d-solo/QlwtYbPZz/prometheus-2-0-stats-copy?orgId=1&panelId=14&render=1
::ffff:10.36.110.242 - - [14/Jan/2020:11:24:04 +0000] "GET /render?domain=grafana&encoding=&height=500&renderKey=675uMv4ZnNctn8jbUBl2erSwSkw7ic8G&timeout=30&timezone=&url=http%3A%2F%2Fgrafana%2Fd-solo%2FQlwtYbPZz%2Fprometheus-2-0-stats-copy%3ForgId%3D1%26panelId%3D14%26render%3D1&width=1000 HTTP/1.1" 200 77092 "-" "Go-http-client/1.1"
```

Grafana debug logs (GF_LOG_LEVEL=trace && GF_LOG_CONSOLE_LEVEL=trace):

```bash
t=2020-01-14T11:24:04+0000 lvl=dbug msg="Sending notification" logger=alerting.notifier type=slack uid=HxaGtfPWk isDefault=false
t=2020-01-14T11:24:04+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification=test
t=2020-01-14T11:24:04+0000 lvl=dbug msg="Sending webhook" logger=notifications url=https://hooks.slack.com/services/XXX http method=
t=2020-01-14T11:24:04+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=5.838 alertId=1 name="Scrape Duration alert" firing=true attemptID=1
```

Rendered image:

```bash
bash-5.0$ ls /var/lib/grafana/png/
eHrR587xeY09n7iSKIi1.png
```

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Any
- OS Grafana is installed on: Docker/Kubernetes

**Comment by marefr** [comment]
Please read https://grafana.com/docs/grafana/latest/alerting/notifications/#slack and https://grafana.com/docs/grafana/latest/alerting/notifications/#external-image-store carefully. With slack you could either upload the image or send a link to a publicly available image.

**Comment by ZealousMacwan** [comment]
> Please read https://grafana.com/docs/grafana/latest/alerting/notifications/#slack and https://grafana.com/docs/grafana/latest/alerting/notifications/#external-image-store carefully. With slack you could either upload the image or send a link to a publicly available image.

I have rendered images on local storage(by docker external image rendering container), not getting uploaded on slack alert. how to get images on slack?

**Comment by aknuds1** [comment]
@ZealousMacwan Support questions are best asked in our [community forums](https://community.grafana.com/).

**Comment by ZealousMacwan** [comment]
> @ZealousMacwan Support questions are best asked in our [community forums](https://community.grafana.com/).

I know but Its been long no one is replying there

**Comment by marefr** [comment]
@ZealousMacwan if you read the links I provided it should be obvious that you need to configure slack using "bot integration via Slack Apps" when you only have local image storage.

**Comment by ZealousMacwan** [comment]
> @ZealousMacwan if you read the links I provided it should be obvious that you need to configure slack using "bot integration via Slack Apps" when you only have local image storage.

@marefr 
Thanks for the reply, 
**So bot required even these images are accessible via public IP of Grafana Instance?**
If Yes, then this needs to be stated in the document properly, it was not so obvious for me but 
Thanks for helping out.
