### ISSUE TITLE
6.5 cloudwatch changes make large queries impossible

### ISSUE THREAD

**Issue by tehlers320** [grafana/grafana#21496]
**What happened**:
by switching APIs it is no longer possible to build a panel that queries over 100 series.

**What you expected to happen**:
All metrics to load

**How to reproduce it (as minimally and precisely as possible)**:
launch something with 100+ nodes in elasticache
`REMOVE_EMPTY(SEARCH('{AWS/ElastiCache,CacheClusterId} MetricName="CPUUtilization"', 'Average', 60))
`

**Anything else we need to know?**: 
You can work around this by chopping up your panels but this seems like allot of work and not very pleasant to view. I just want to document the problem so its out there for discussion.  

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Docker
- User OS & Browser: Firefox
- Grafana plugins: many
- Others: no

**Comment by tehlers320** [comment]
Another thing that happens is you can not open many graphs at one time. 
<img width="277" alt="Screen Shot 2020-01-16 at 9 09 55 AM" src="https://user-images.githubusercontent.com/16598119/72536506-fc95eb00-383f-11ea-9ea9-fcb2fd99e40d.png">

This takes away much of the functionality of using grafana for cloudwatch.

**Comment by marefr** [comment]
This is already documented in the [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v6-5) so will close this.

**Comment by tehlers320** [comment]
@marefr there is no work around as explained you cannot simply add * and there is no way to key off anything to slim down the query. 

> This is already documented in the [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v6-5) so will close this.

**Comment by tehlers320** [comment]
We have decided that we can never move off of Grafana 6.4.x because of these changes.

**Comment by sunker** [comment]
> by switching APIs it is no longer possible to build a panel that queries over 100 series.

@tehlers320, I'm curious to know what kind of query you would run that return more than 100 time series? To me that seems like an incredibly busy graph, and it will also cause very slow rendering. 

It's not possible to add more than 26 query rows in the Grafana query editor, so I'm assuming your using multi-valued template variables. That's the only way to issue a query for more than 100 instances pre Grafana 6.5. In that case I guess the limit that you're hitting is the 1024 char limit in the search expression. I cannot say for sure, but I think that limit in GMD is about to be increased sometime soon.

**Comment by sunker** [comment]
@tehlers320, CloudWatch has just increased the no of metrics limit per GMD request from 100 to 500. https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html

**Comment by tehlers320** [comment]
@sunker the api change seems to have fixed most issues but in a scenario where you do blue/greens you still cannot use this. 

Dashboard:
Use this dashboard 
https://grafana.com/grafana/dashboards/650
Modify it with a search for your blue/green ELBs with select all/regex
You have a scenario where for example you only need 6 different ELBs and hit a different limiter.

![Screen Shot 2020-01-31 at 9 28 10 AM](https://user-images.githubusercontent.com/16598119/73551762-a06cc280-440c-11ea-9dbd-6e7749e34ddd.png)

![Screen Shot 2020-01-31 at 9 28 24 AM](https://user-images.githubusercontent.com/16598119/73551876-dc078c80-440c-11ea-824b-ff5cc9231711.png)

> dimension_values($region,AWS/ELB,Latency,LoadBalancerName)

![Screen Shot 2020-01-31 at 9 28 36 AM](https://user-images.githubusercontent.com/16598119/73551893-e164d700-440c-11ea-8802-de1a44bc51a3.png)

I rolled 6.6.0 in for the above re-test. 

This does seem allot faster overall

**Comment by sunker** [comment]
@tehlers320, tested the dashboard and it works fine for me. I only have one load balancer in my test environment though. 

Can you please paste your query here? QueryInspector -> Copy to Clipboard

**Comment by tehlers320** [comment]
There are two issues from the old method #1 is something like this where you can no longer add more than 5 queries to a panel.  (actual names edited to a random hash)
[cloudwatch6_6_failed_query.txt](https://github.com/grafana/grafana/files/4199393/cloudwatch6_6_failed_query.txt)

Number 2 is the char limit (i removed actual ELB names and replaced them with random hashes but the length should be the around same).
[cloudwatch6_6_failed_query_blue_green.txt](https://github.com/grafana/grafana/files/4199495/cloudwatch6_6_failed_query_blue_green.txt)

I know this is a weird situation on number 2 because its an odd way to do blue/green making a new ELB and throwing away the old one on each and every release and as you can see it piles up many dead metric streams that hold in-active data which then make a query to getmetrics impossible.

**Comment by sunker** [comment]
Regarding problem 1. Before Grafana 6.5, we issued one new GMD call per query row in the query editor even though the GMD api has support for 100 queries per GMD call, and that is why this was working before. That was wrong for so many reasons - performance, risk of hitting throttling limits and also for the fact that users pay per GMD call. So in case you had a panel with 5 search expressions pre Grafana 6.5, you'd pay for 5 requests, whereas now you'd pay for only one. That is the reason this change will be better for most of our users. 

Regarding problem 2. I can see why you're frustrated about this. I cannot say for certain, but from what I understand this 1024 char limit is about to be increased in the GMD api in the near future. Let's hope so!

**Comment by deduhov** [comment]
@sunker  Could you please look to this question:

https://github.com/grafana/grafana/issues/27517 ?

It's somehow related to current one, but not exactly. Is there any way to remove double quotes from the dimension in query generated by grafana?

Thank you

**Comment by justinTM** [comment]
still an issue. Selecting/deselecting `Exact match` toggle does not change quotation of dimension values in CloudWatch Metric Search queries.
