### ISSUE TITLE
Embed Grafana Panel as src using Iframe in Externally

### ISSUE THREAD

**Issue by arunkumardada** [grafana/grafana#21498]
**What happened**:
I created Angular Web Application,From the Back End Service Call i am getting the Grafana Panel Links. Using <iframe [src]="link"/> i am able to see the grafana panel like this

![image](https://user-images.githubusercontent.com/29578687/72408382-b893df00-3788-11ea-99aa-7e0808cdbe74.png)

**What you expected to happen**:

I am expecting to show the Panels without Scroll bar and to be placed and visible.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:6
- Data source type & version:
- OS Grafana is installed on: Windows 8
- User OS & Browser: Chrome
- Grafana plugins: SingleStat
- Others:

**Comment by marefr** [comment]
Make your iframe bigger? Hard to tell if this is on Grafana side or you that haven't implemented it properly. Would suggest ask on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
