### ISSUE TITLE
Template query filtering

### ISSUE THREAD

**Issue by docwhat** [grafana/grafana#2149]
I'm unsure from reading the docs if this is a bug or feature request...

Given:

* I use Graphite.
* I have data like `diamond.myserver1.httpd.BytesPerSec`

I created a template query variable `$server`:

* "Variable values query": `diamond.*.httpd.*`
* "regex": `^diamond\.([^.]+)\.`

I expected to get a list of hosts that have values for `diamond.*.httpd`.  Instead, I get nothing.

In addition, I'm unsure if I need the `/` characters around the regex.  But the above doesn't work with the `/` either.

I *think* the regex is being applied *after* the "Variable values query" is run and passed through whatever applies the equiv. of `aliasByMetric()` (e.g. takes the last dotted part).

I expected the regex to be applied *before* it is run through `aliasByMetric()`.

The only docs/examples for regex I saw where for InfluxDB.  If regex isn't meant for Graphite sources, then maybe it should be hidden?

**Comment by torkelo** [comment]
the placeholder text is missleading (it only applies to Graphite users), `diamond.*.httpd.*` is not a valid InfluxDB query, it needs to be a valid influxdb query.   

for example something like `list series /diamond.*.httpd.*/`

**Comment by torkelo** [comment]
Sorry, miss read you question (read the regex part, it is 99% used by InfluxDB users). The problem is your regex, graphite will only return the last segment, so no values will match `^diamond\.([^.]+)\.`

**Comment by torkelo** [comment]
The regex is run on the values returned by graphite. It is mainly used by InfluxDB to capture only party of the metric name. For Graphite it can be used to capture part of a node segment.

**Comment by docwhat** [comment]
Can it be changed? It would be really handy for limiting the number of choices when there are a lot of systems? 

Can graphite return the whole path and let Grafana apply the regex and grab the last node segment?

**Comment by torkelo** [comment]
you will have to open a PR for graphite for that

**Comment by docwhat** [comment]
Ah. I see.
