### ISSUE TITLE
Tabs: extra line in datasource config pages

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#21494]
It looks like we now have an extra 1px line in some tabs:
![image](https://user-images.githubusercontent.com/705951/72374525-4b684700-36bf-11ea-8b60-cbb61fc3bc7c.png)

@peterholmberg

**Comment by torkelo** [comment]
can't replicate this, what browser / OS and zoom level are you using?

**Comment by torkelo** [comment]
damit, sorry I can replicate it now. Was on a branch where this was fixed

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/21489
