### ISSUE TITLE
Adding render as table

### ISSUE THREAD

**Issue by avnivamsikrishna** [grafana/grafana#215]
Currently, grafana takes data from graphite and renders them as graphs, I have been wondering if Grafana can also render the data in tabular format.

**Comment by juise** [comment]
+1

**Comment by steverweber** [comment]
+1 it would be nice to display a table of data from an influxdb... I store log our nginx error log strings in there

**Comment by fsauer65** [comment]
this issue has been sitting here for a while now and I guess it's taking a back seat to the go backend right now. Do you have any idea on an ETA for something like this? It would allow me to completely sever a dependency on Elasticsearch/Kibana and store all my stuff in InfluxDB, not just metrics and I'm really itching to do this, especially when InfluxDB 1.9 comes out with their new tag support

**Comment by ssoto** [comment]
:+1: 
There is something that I can't understand about the table panel. When you talk about add it, is it dependent on the datasource? Could be it available only for InfluxDB or OpenTSDB?

**Comment by craftytrickster** [comment]
I am currently working on this functionality, I have branched off of develop, so this is something that would be for the Grafana 2.x series. Because I personally use InfluxDB 0.8x, it is currently only working for that datasource. However, the table is not tightly coupled and should be able to work with other data sources as well. There is still work to be done, but I am including a screenshot of my current progress in case anyone is interested. It is using live data from an InfluxDb instance. 

 
![screen shot 2015-03-30 at 9 24 10 am](https://cloud.githubusercontent.com/assets/10675565/6896997/91ae5f9e-d6be-11e4-8cec-b6fbdc68feb8.png)

**Comment by arganzheng** [comment]
+1. This is very useful for TOP N, and with MIN, MAX, AVG, COUNT

**Comment by maingi4** [comment]
+1

**Comment by shankar-piriya** [comment]
+1 Very useful feature

**Comment by xfmoulet** [comment]
+1 indeed, very useful

**Comment by danievanzyl** [comment]
+1

**Comment by yogu13** [comment]
+1 for the feature...  btw when is this planning to be released ?

**Comment by torkelo** [comment]
not sure, a lot of work remains for it to be ready to merge to master (mostly styling, display issues, display options, etc).

**Comment by kokarn** [comment]
:+1: Just so you know it's still really wanted :)

**Comment by torkelo** [comment]
@craftytrickster Sorry for not give more detailed feedback on this. 

I have tested it from time to time and havent found it working or looking that good (visually). I found that i easily could get into issues with the table going outside the boundaries of the panel or the paging appearing onto of the rows. And the general styling was pretty boring. But overall the code looks great so it just a matter of polishing what is there, and I just have been to swamped with other stuff to take on that work.

**Comment by spectr** [comment]
+1

**Comment by megastef** [comment]
+1 Elasticsearch Datasource in 2.5, but no table view? How to show metric/log related text?

**Comment by torkelo** [comment]
@megastef one step at a time, table panel is top prio for next release (2.6)

**Comment by otisg** [comment]
Awesome, @torkelo!  I want to hook up Grafana and Logsene (hosted Elasticsearch) as an alternative for Logsene+Kibana.

**Comment by alanma** [comment]
:+1: . tabular format for top N data display is critical for our use case. we have to look for other options if grafana could not support this :-(

**Comment by torkelo** [comment]
Been working on a table panel for the last couple of days.

Its still early but things are starting to work. I want the table panel to be very flexible and support many scenarios and data sources (both time series and rich json data for example) as well as detailed styling options and coloring thresholds. 

Time series to columns transform (all series are grouped by time and given its own value column)
![image](https://cloud.githubusercontent.com/assets/10999/11000309/3d3d88ae-84a1-11e5-8cd6-9203cfefecad.png)

JSON data (Elasticsearch data source)
![image](https://cloud.githubusercontent.com/assets/10999/11000324/59b211e4-84a1-11e5-99b9-60f4e0bb179b.png)

Other data -> table transforms are Time series to rows (all series are merged and sorted by time and a single 'series' column is added and a single value column)' 

Annotations - if you pick this Data -> table transform then the data queries for the panel will be ignored and the table will instead get data from any dashboard wide configured annotations. 

Another Data -> Table transform that I wan to add is Time series summarize, will give you a single row per time series and column like Min, Max, Avg, Total etc. 

work is going on in tablepanel2 branch, a lot is still now to be implemented (paging, sorting etc)

**Comment by mtanda** [comment]
+1

**Comment by otisg** [comment]
@torkelo Not sure if this is important to you, but a good JS table is hard to find, so you may want to consider writing this table component so it can be used outside Grafana, too.

**Comment by kokarn** [comment]
This looks really good! 
Nice work, i'm sure a lot of people will appreciate this.

**Comment by spectr** [comment]
Looking good!

**Comment by craftytrickster** [comment]
It looks very nice. I would recommend maybe closing this PR and opening a new one based on that branch, since it will likely be drastically different than what was placed here.

**Comment by alanma** [comment]
@torkelo looks super slick. All the people watching this feature will LOVE it.

**Comment by yehosef** [comment]
+1 Thanks - this is great!

**Comment by IzakMarais** [comment]
> Annotations - if you pick this Data -> table transform then the data queries for the panel will be ignored and the table will instead get data from any dashboard wide configured annotations.

Excellent! Looking great, thanks.

**Comment by kylebrandt** [comment]
I'm looking forward to trying to support this with the bosun plugin. We have two main core datatypes, series sets and number sets. Series sets are tagged time series, but number sets are tag single values.

So for example `avg(..cpu .. ny-web*.., "1h")` will return a table of avg cpu over the last hour for all our ny-web* servers. A lot of use cases for this in dashboards. The shape of the data is lost, but you can get a lot more summary information in a small space.

**Comment by torkelo** [comment]
I opened a [new issue](https://github.com/grafana/grafana/issues/3219) for the new table panel, please try the new panel out in the 2.6 pre release builds or on the new [demo dashboard](http://play.grafana.org/master/dashboard/db/table-panel-showcase)

http://play.grafana.org/master/dashboard/db/table-panel-showcase

http://grafana.org/download/builds.html
https://github.com/grafana/grafana/issues/3219

**Comment by fsauer65** [comment]
It looks fantastic,  excellent!  Thanks !!!

Frank

**Comment by vikashbabu** [comment]
Hey folks 
I have a pie chart consists of multiple submetric.
for e.g
submetric                  value
a                                    300
b                                    200
c                                    400
now i want to get a row in same chart as
total                              900(sum of all submetric value).
Is there any way to do this.
Thanks
