### ISSUE TITLE
test the alert and the data was cut off

### ISSUE THREAD

**Issue by kk5pengke** [grafana/grafana#21500]
**Steps to reproduce**:
I want to test the alert of the grafana, I push the test data continuously, qps = 10. I set the time interval = 1min, so there is about 599 every min.
![image](https://user-images.githubusercontent.com/18496674/72414203-a62b9c80-37ac-11ea-83ae-f7900d6d5067.png)
and set the alert diff as follow:
![image](https://user-images.githubusercontent.com/18496674/72414230-b5aae580-37ac-11ea-89f2-15b2f88b5c56.png)
I test the rule, here is the result
![image](https://user-images.githubusercontent.com/18496674/72414339-ee4abf00-37ac-11ea-96b6-5ba2f473d308.png)

**Actual Result**:
array[now-1m] = array[5] = 162
array[now-5m] = array[0] =437
diff  = 437 - 162 =275
it seems that the data was cut off(162 + 437 = 599) or the time was cut off? I don't know what's wrong with my test or setting

**Expected Result**
array[now-1m] = 599
array[now-5m] = 599
diff  = 599 -599 =0

**Environment**:
- Grafana version: v6.3.5
- Data source type & version:
- User OS & Browser:MacOS 10.14.4/Chrome
- Others:

**Comment by marefr** [comment]
This is probably due to the nature of how influxdb group by time function, see https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#why-do-my-queries-return-no-data-or-partial-data. Would suggest reaching out to influxdb community site for further help.

**Comment by kk5pengke** [comment]
> This is probably due to the nature of how influxdb group by time function, see https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#why-do-my-queries-return-no-data-or-partial-data. Would suggest reaching out to influxdb community site for further help.

If so, I think the diff and percent_diff function is nonsense. The first and the last array are random because of the  partial data. Is there any way or setting to solve the problem? Or I should change the way of pushing data. Thanks.
