### ISSUE TITLE
Uncertain metric counts from Grafana

### ISSUE THREAD

**Issue by RavivarmaDadi** [grafana/grafana#21502]
We are using sumSeries() function to collect the metrics and sum up the results from multiple queries.
**Example:**
#A sumSeries(aliasByNode(exclude(exclude(exclude(*.*.2-2-12.journalValidator-service-296905184-1-314990627.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count, 'mapSize'), 'healthCheck'), 'clusterNodes'), 12))

#B sumSeries(aliasByNode(exclude(exclude(exclude(*.*.2-2-12.journalValidator-service-213256444-1-314990722.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count, 'mapSize'), 'healthCheck'), 'clusterNodes'), 12))

#C sumSeries(#A,#B)

These queries sumSeries() result is giving uncertain counts like large negative integer or positive integers and sometimes current count what we are expecting.

**Note**: We have auto refresh set for 30 secs for dashboard.

**Comment by RavivarmaDadi** [comment]
We want to understand why these queries giving uncertain counts for each refresh of 30 secs.

**Comment by marefr** [comment]
Please use the query inspector and inspect the request/response to verify if this is a Grafana issue or Graphite/query configuration issue on your side.

**Comment by RavivarmaDadi** [comment]
> Please use the query inspector and inspect the request/response to verify if this is a Grafana issue or Graphite/query configuration issue on your side.

Sure will do that.

**Comment by RavivarmaDadi** [comment]
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1/render",
    "data": "target=sumSeries(sumSeries(aliasByNode(exclude(*.*.2-2-12.journalValidator-service-296905184-1-314990627.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count%2C%20'healthCheck')%2C%2012))%2CsumSeries(aliasByNode(exclude(*.*.2-2-12.journalValidator-service-213256444-1-314990722.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count%2C%20'healthCheck')%2C%2012))%2CsumSeries(aliasByNode(exclude(*.*.2-2-12.journalValidator-service-210490606-1-627428327.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count%2C%20'healthCheck')%2C%2012)))&from=-15min&until=now&format=json&maxDataPoints=100"
  },
  "response": [
    {
      "datapoints": [
        [
          566522,
          1579703670000
        ],
        [
          566522,
          1579703700000
        ],
        [
          566547,
          1579703730000
        ],
        [
          566547,
          1579703760000
        ],
        [
          566547,
          1579703790000
        ],
        [
          566547,
          1579703820000
        ],
        [
          566547,
          1579703850000
        ],
        [
          566547,
          1579703880000
        ],
        [
          566547,
          1579703910000
        ],
        [
          566547,
          1579703940000
        ],
        [
          566547,
          1579703970000
        ],
        [
          566547,
          1579704000000
        ],
        [
          566547,
          1579704030000
        ],
        [
          566547,
          1579704060000
        ],
        [
          566547,
          1579704090000
        ],
        [
          566547,
          1579704120000
        ],
        [
          566547,
          1579704150000
        ],
        [
          566547,
          1579704180000
        ],
        [
          566547,
          1579704210000
        ],
        [
          566547,
          1579704240000
        ],
        [
          566547,
          1579704270000
        ],
        [
          566547,
          1579704300000
        ],
        [
          566547,
          1579704330000
        ],
        [
          566547,
          1579704360000
        ],
        [
          566547,
          1579704390000
        ],
        [
          566547,
          1579704420000
        ],
        [
          566547,
          1579704450000
        ],
        [
          566547,
          1579704480000
        ],
        [
          566547,
          1579704510000
        ],
        [
          377786,
          1579704540000
        ]
      ],
      "target": "sumSeries(sumSeries(*.*.2-2-12.journalValidator-service-296905184-1-314990627.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count),sumSeries(*.*.2-2-12.journalValidator-service-213256444-1-314990722.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count),sumSeries(*.*.2-2-12.journalValidator-service-210490606-1-627428327.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count))",
      "tags": {
        "aggregatedBy": "sum",
        "name": "sumSeries(sumSeries(*.*.2-2-12.journalValidator-service-296905184-1-314990627.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count),sumSeries(*.*.2-2-12.journalValidator-service-213256444-1-314990722.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count),sumSeries(*.*.2-2-12.journalValidator-service-210490606-1-627428327.com.walmart.arsenal.finance.journal.validator.controllers.JournalValidatorController.*.count))"
      }
    }
  ]
}


This is what I am getting when doing query inspection. I could see the response but what it is showing in Grafana dashboard is not expected. I will attach the snippet for your reference.
![Capture](https://user-images.githubusercontent.com/18698401/72904976-c4b60880-3d55-11ea-91c6-659050979f1b.JPG)

**Comment by marefr** [comment]
What settings are you using in the singlestat to get out that value?

**Comment by RavivarmaDadi** [comment]
I am attaching a snap to showcase
![Singlestat_setting](https://user-images.githubusercontent.com/18698401/72970852-77d24080-3dee-11ea-963d-53bae3d679ff.JPG)
 our settings

**Comment by marefr** [comment]
What difference are you expecting, difference between last (current) value and first value? Seems like using the Difference Stat will do current value - current-1 value hence the negative result when current-1 value is greater than current value.

**Comment by RavivarmaDadi** [comment]
General settings snap of the dashboard.
![General_Settings](https://user-images.githubusercontent.com/18698401/72971967-99ccc280-3df0-11ea-8894-5a5a74046d08.JPG)

**Comment by RavivarmaDadi** [comment]
> What difference are you expecting, difference between last (current) value and first value? Seems like using the Difference Stat will do current value - current-1 value hence the negative result when current-1 value is greater than current value.

We are expecting the difference of values from given time range.
For Example : last 15 mins 
We have tried "current" option as well but it is giving the current value but not what we are expecting. That's why we went for "difference", It is giving the value we are expecting but on refresh it is giving some negative integer.

**Comment by RavivarmaDadi** [comment]
Snap showing time range and refresh interval of a dashboard.
![Time Range and Refresh interval](https://user-images.githubusercontent.com/18698401/72973282-02b53a00-3df3-11ea-8a25-95fa7cb79586.JPG)

**Comment by RavivarmaDadi** [comment]
@marefr Can you provide any solution or alternate 
The problem here is we are using "difference" for single stat panel and trying to fetch count in specified time range as mentioned above. we are getting expected result but sometimes we are seeing negative integers especially while refreshing as we set refresh interval of 30s for the dashboard.
We have tried "current" as well but it is not giving the expected counts.

**Comment by marefr** [comment]
@RavivarmaDadi think you have to solve this in query to Graphite so that Graphite does the diff instead and then you can use current in Grafana.
