### ISSUE TITLE
Backend plugins: Implement support for checking plugin config health

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#21519]
Implement support for checking backend plugin config health. To be used at least when testing app/plugin from UI after saving a backend app/datasource plugin. Any error/warning should be returned to client. 

Blocked by: grafana/grafana-plugin-sdk-go#38
Epic: #19667

**Comment by ryantxu** [comment]
See also: https://github.com/grafana/grafana-plugin-sdk-go/issues/93
