### ISSUE TITLE
Grafana v6.6 Release Plan

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#21513]
# Grafana v6.6
Release Coordinator: @papagian 

### 1.1. Publish What's new in Grafana draft article
**When:** Preliminary Friday 17th November 2019
**What:**

 - [X] Create Google doc and share with maintainers (Release coordinator)
 - [X] Write draft article (Maintainers)
 - [X] Open a PR (Release coordinator) in grafana repository
 - [X] Open PR in website repository merging `docs-grafana` branch into `master`
 - [X] Examine staging site
 - [X] Publish to grafana.com

**Who:** Release coordinator and maintainers

### 1.2. Beta 1 Release
**Preconditions:**

- [X] 1.1. Publish What's new in Grafana draft article

**When:** Preliminary Monday January 20th 2020
**What:**

 - [X] Checkout new release branch, v6.6.x, from head of origin/master
 - [X] Update versions to the next version to be released
 - [X] Update /scripts/build/publish.sh to contain the new “what's new” and “release note” links.
 - [X] Commit everything and push release branch
 - [X] Checkout master branch and branch of to a new branch
 - [X] Update version in package.json to point to the next pre-release, i.e. v6.7.0-pre and commit
 - [X] Open a PR
 - [X] Checkout release branch, create and push beta release tag and wait for CircleCI release build to finish
 - [X] Run automated verification tests
 - [X] Verify the front-end packages
 - [X] Update the changelog in master
 - [X] Create community site release note topic
 - [X] Create a new release on GitHub
 - [X] Create and upload Hosted Grafana images
 - [X] Update latest.json
 - [X] Close the milestone

**Who:** Enterprise squad

## 2. Test and verification
Preconditions:

- [X] 1.2. Beta 1 Release

**When:** Preliminary Monday January 20th 2020
**What:** For now we don’t have a lot of automated processes for UI tests so it’s suggested to start with manual test and verification to improve the quality of the release. The test and verification is done on the release branch.
**Who:** Primarily maintainers
**Who:** Release coordinator and maintainers

### 3.1 Publish What's new in Grafana final article

**Preconditions:**
 - [X] 1.2 Beta 1 released

**When:** Before stable release
**What:**

 - [X] Create a new Google doc based on What's new in Grafana draft article published and share with maintainers (Release coordinator)
 - [X] Write final article (Maintainers)
 - [X] Open a PR
 - [X] Publish to production (website repo)

**Who:** Release coordinator and maintainers

### 3.2 Create release blog post

**Preconditions:**
 - [X] 3.1 Publish What's new in Grafana final article

**When:** Before stable release
**What:**

 - [X] Use final what's new article as template and create new release blog post
 - [X] Remember to change relative links from What's new article to absolute ones
 - [X] Open a PR in website repo

**Who:** Release coordinator

## 4. Stable Release
**Preconditions:**

 - [X] Beta released and no critical bugs left to fix for the stable release
 - [X] 3. Docs and blog post

**When:** Most probably Monday 27th
**What:**

 - [x] Cherry pick bug fixes into release branch (important for the stable release)
 - [x] Create and push stable release tag and do the actual release

**Who:** Enterprise squad

## 5. Publish Release blog post
**Preconditions:**

- [x] 3.2 Create release blog post
- [x] 4. Stable Release

**When:** TBD
**What:**

 - [x] Publish blog post

**Who:** Release coordinator

**Comment by dprokop** [comment]
@marefr @papagian Love the work you put into this <3
