### ISSUE TITLE
Grafana with graphite-api

### ISSUE THREAD

**Issue by sasansamit** [grafana/grafana#2151]
I am trying to use Grafana with graphite-api and am facing some issues.

* On adding a new graph i get an error mark on the graph's top left corner.
![image](https://cloud.githubusercontent.com/assets/4545673/8113920/495d3412-103f-11e5-83a6-7d7b6e499cb6.png)

Network tab shows
![image](https://cloud.githubusercontent.com/assets/4545673/8113945/69924f42-103f-11e5-835b-022cc1d1a403.png)

![image](https://cloud.githubusercontent.com/assets/4545673/8113965/7d56dac0-103f-11e5-934c-12eea8193035.png)

It seems we are missing a required parameter "target" from the the api call. 
When i make the exact call thru Postman i get the error.

![image](https://cloud.githubusercontent.com/assets/4545673/8114115/5cdd1d9e-1040-11e5-9d19-5e0ecb19f175.png)

Adding target parameter to the call **http://10.0.0.92:8888/render?target=test** succeeds.

**Comment by torkelo** [comment]
did you open the graph in edit mode and specified a graphite query? lots of poeple use graphite-api with grafana, and its strange that you did no show query in grafana :)

**Comment by torkelo** [comment]
you open graph edit by clicking the title / edit
