### ISSUE TITLE
role_attribute_path as environment variable in Dockerfile

### ISSUE THREAD

**Issue by lakshmankumark** [grafana/grafana#21522]
Hi, I am trying to add role_attribute_path in Dockerfile as an Environment Variable. Please suggest appropriate ENV variable name like other variables like GF_AUTH_GENERIC_OAUTH_NAME.

Thanks, Lakshman

**Comment by lassegaardsholt** [comment]
Did you solve this?

**Comment by gioradicci** [comment]
The https://grafana.com/docs/grafana/latest/administration/configuration/ section does not report any section for this variable.
I think at the moment this issue **can't be closed.** 


> Hi, I am trying to add role_attribute_path in Dockerfile as an Environment Variable. Please suggest appropriate ENV variable name like other variables like GF_AUTH_GENERIC_OAUTH_NAME.
> 
> Thanks, Lakshman

**Comment by ndtreviv** [comment]
I also need to set this property from docker without overwriting the config, otherwise how can I extract the correct roles from my ID provider's token?
