### ISSUE TITLE
Allow git as alternative persistent storage for dashboards

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#21528]
**What would you like to be added**:
Allow Grafana to add a git repository to read/store dashboard in a centralized place.

**Why is this needed**:
Given a company has similar infrastructure setup for dev/stage/prod foundations, and the infrastructure setup is actively evolving.
As an operator, I need to keep the grafana dashboard up-to-date to better monitor the health of the foundation. Right now I need to configure the grafana dashboards in three instances (dev/stage/prod). Although export dashboard to json helps to mitigate the pain, it is still a repetitive process.
I would like to have my dashboard updated only once, and automatically rolled out to other instances as well.

Also git repo helps to keep a more _dashboard-as-code approach_. Although grafana has versioning builtin for dashboards, the history:
- is lost when the dashboard is deleted, make it hard to recover
- has the potential to loss during grafana reinstallation

Git is a familiar tool and has intrinsic advantages when comes to keep plain text files versioned in a centralized fashion.

**Things to consider**
Should the git folder structure maps to the folder structure in grafana?
- if yes, how to avoid conflict or merge with existing folders?
- if no, should the dashboard in git all reside in an assigned folder much like dashboard provisioning?

What is the UX to make sure the git dashboards play well with other dashboards?
- allow migrate internal dashboard to/from git dashboards?

**Similar issue and difference**
https://github.com/grafana/grafana/issues/13789

The above issue feels like solving the same problem -- store dashboard in a centralized fashion. But the proposed feature in this issue asks for a more integrated approach than simple read only (one-way-sync) dashboards.

**Comment by marefr** [comment]
Please use [provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/) feature which provision dashboards from local file system. Should be quite easy for you to setup a cron to pull in all dashboards from git into local file system which Grafana would automatically pick up.

**Comment by fredwangwang** [comment]
> the proposed feature in this issue asks for a more integrated approach than simple read only (one-way-sync) dashboards.

We could definitely setup something as you described, but I think there is a potential to integrate tighter with git to make the dashboard management across different (similar) foundations easier.

**Comment by vineethvijay7** [comment]
Curios to hear if there was any interesting development made in this area in recent years?

**Comment by joseph-netog** [comment]
I would like to see the official container support this if its not going to be native.

**Comment by beasteers** [comment]
Building on Grafana's current version history functionality, you could also to version history comparisons and merges across multiple instances (make changes in your dev grafana, then merge them into live). This functionality would be very natural to implement with git (each instance in a different branch).

Currently with provisioning, you can do merges, but it's all through JSON which makes the UX poor and a bit dangerous.
