### ISSUE TITLE
Replace react-size with AutoSizer

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21529]

**Comment by peterholmberg** [comment]
Closed via #21511

**Comment by dprokop** [comment]
@peterholmberg is this really closed? I see react-sizeme being used in DashboardGrid (https://github.com/grafana/grafana/blob/cd07c3e6520a7c1a37cd042b2ad00426d78462bb/public/app/features/dashboard/dashgrid/DashboardGrid.tsx#L7)

**Comment by peterholmberg** [comment]
@dprokop no I accidentally closed it. Should be reopened?

**Comment by torkelo** [comment]
yes
