### ISSUE TITLE
Allow configuring bucket policy for S3 image store

### ISSUE THREAD

**Issue by jaydlowrider** [grafana/grafana#21520]
**What happened**: 
The latest version (v6.5.2 (742d165)) seems to have broken the external_image_storage S3.

**What you expected to happen**:
We use Slack notification for alerts and image is automatically uploaded to S3. our current running production Grafana is at v.5.2.2 and S3 external_image_storage works.

**How to reproduce it (as minimally and precisely as possible)**:
I followed the documentation as stated. https://community.grafana.com/t/s3-image-upload-for-alerts/17083 and https://grafana.com/docs/grafana/latest/installation/configuration/#access-key

and we still get 

`
2020-01-14T05:16:59+0000` lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: 2D70B3CF7BECE67E, host id: MPxo6JkRwHfQEAlzoKRPWAQDBH6W ....
`
I've given the user entire permission and still get that error.

**Anything else we need to know?**:
We verified that we are not getting any Event activity from the user given to Grafana on CloudTrail, at that point we determined that User is NOT being used. To make it work we allowed public writes on the s3 bucket.

**Environment**:
- Grafana version: v6.5.2 (742d165)
- Data source type & version: ElasticSearch 6.7.0
- OS Grafana is installed on: K8s, grafana/grafana:6.5.2
- User OS & Browser: MacOS Mojave 
- Grafana plugins: alexanderzobnin-zabbix-app,grafana-piechart-panel,raintank-worldping-app
- Others:

**Comment by aknuds1** [comment]
Thanks for reporting this, we will look into it.

**Comment by mitchellrj** [comment]
Same here on version 6.6.0.

Using environment variables to give the Grafana process its credentials (working fine for CloudWatch usage). Even setting bucket policy and Grafana policy to allow all permissions on the s3 bucket and its objects does not solve the issue.

**Comment by marefr** [comment]
To be able for slack to render images from s3 it needs to be a bucket that's publicly available, for reference https://grafana.com/docs/grafana/latest/alerting/notifications/#external-image-store. This shouldn't be a new problem.

**Comment by mitchellrj** [comment]
@marefr this concerns a failure to upload in the first place, not an inability to download. Note the error log output in the original report.

**Comment by mitchellrj** [comment]
I think I've figured this out in my case by setting up debug logging for AWS SDK on a custom build. Does your S3 bucket block public ACLs @jaydlowrider?  The upload attempts to set an ACL of `public-read` ([hard-coded](https://github.com/grafana/grafana/blob/42032f6c030fda1d6423cdfdd4589c805eee827f/pkg/components/imguploader/imguploader.go#L60)).

Ideally this hard-coding should be removed, and users should be instructed to set bucket policy according to their needs (as we already have).

Resolved for my use case anyway.

Process for making a test build of Grafana with AWS debugging on on Amazon Linux 2:
```
# install build requirements
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
sudo yum install -y go git nodejs ruby-devel gcc make rpm-build rubygems glibc fontconfig freetype freetype-devel fontconfig-devel bzip2
sudo gem install --no-document fpm
sudo npm install -g yarn

# install phantom
curl -qLo phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
sudo tar -xjf phantomjs.tar.bz2 -C /usr/local/share/
sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/share/grafana/tools/phantomjs/phantomjs

# build
mkdir ~/go
export GOPATH=~/go
go get github.com/grafana/grafana
cd $GOPATH/src/github.com/grafana/grafana
git checkout v6.6.0
mkdir dist
sed -i pkg/components/imguploader/s3uploader.go -E -e 's/&aws.Config/(\&aws.Config/' -e '/Credentials:\s+creds,/{a \                LogLevel:         aws.LogLevel(aws.LogDebugWithEventStreamBody),\
        }).WithLogger(aws.NewDefaultLogger())' -e ';n;d}'
yarn install --pure-lockfile --no-progress
yarn start
go run build.go build
go run build.go -skipDeb package-only
go run build.go latest

# install
sudo yum install -y dist/grafana-latest-1.x86_64.rpm

# configure
sudo vim /etc/grafana/grafana.ini
# edit config to suit your needs

# run
sudo service grafana-server start

# observe
sudo journalctl -fu grafana-server
```

**Comment by marefr** [comment]
@mitchellrj thanks. The hard-coded public-read was introduced by #7058. Labeled this as a feature request and will change the title to reflect need of configuring bucket policy.

**Comment by jaydlowrider** [comment]
@mitchellrj  
> Does your S3 bucket block public ACLs @jaydlowrider?
Thanks for looking at this, and yes, our S3 is block public ACLs on first setup. I recently allowed it for public access.
