### ISSUE TITLE
Dropdown menu for external links at top of dashboard

### ISSUE THREAD

**Issue by michael-doubez** [grafana/grafana#21523]
**What would you like to be added**:

In the same way I can define dropdown menus of dashboards, I would like to be able to define dropdown menus of external links.

In `Dashboard Links > New`, for external links, I would be able to add/delete links from a list instead of a single item. It would be nice also to reorder them.

**Why is this needed**:

I have dashboards with many related resources (playbooks, documentations, ...). Adding them all takes a lot of space and clutters the dashboard and they are really needed only in ops mode.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
