### ISSUE TITLE
Building from the source issue

### ISSUE THREAD

**Issue by RowZay** [grafana/grafana#2153]
Hi,

I am trying to build Grafana from the source on Ubuntu 14.04, but I'm running into a few problems. I've been following the guide found [here](http://docs.grafana.org/project/building_from_source/). When I get to the step "go run build.go setup ", I get the following:

*Version: 2.1.0-pre1, Linux Version: 2.1.0, Package Iteration: pre1
go get -v github.com/tools/godep
go get -v github.com/blang/semver
go get -v github.com/mattn/go-sqlite3
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory
exit status 1
exit status 1*

but I figured that's okay since I only need godep. The next step, "godep restore", gives me:

*cd .; git clone http://gopkgs.com/pool.v1 /home/user/go/src/gopkgs.com/pool.v1
Cloning into '/home/user/go/src/gopkgs.com/pool.v1'...
fatal: repository 'http://gopkgs.com/pool.v1/' not found
package gopkgs.com/pool.v1: exit status 128
godep: restore: exit status 1
 cd .; git clone http://gopkgs.com/pool.v1 /home/user/go/src/gopkgs.com/pool.v1
Cloning into '/home/user/go/src/gopkgs.com/pool.v1'...
fatal: repository 'http://gopkgs.com/pool.v1/' not found
package gopkgs.com/pool.v1: exit status 128
godep: restore: exit status 1
cd .; git clone http://gopkgs.com/pool.v1 /home/user/go/src/gopkgs.com/pool.v1
Cloning into '/home/user/go/src/gopkgs.com/pool.v1'...
fatal: repository 'http://gopkgs.com/pool.v1/' not found
package gopkgs.com/pool.v1: exit status 128
godep: restore: exit status 1*

Then "go build ." yields:

*../../dalu/unidecode/unidecode.go:9:2: cannot find package "gopkgs.com/pool.v1" in any of:
	/usr/src/pkg/gopkgs.com/pool.v1 (from $GOROOT)
	/home/user/go/src/gopkgs.com/pool.v1 (from $GOPATH)*

"go get github.com/Unknown/bra" works, but I get the message : imports encoding: unrecognized import path "encoding"

Finally, "bra run" gives me a command not found error.
I'm not too sure what to do.

**Comment by damm** [comment]
how did you install go?

**Comment by RowZay** [comment]
I just followed these instructions: 
https://golang.org/doc/install

I have go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

**Comment by damm** [comment]
go version returns that? weird

```
$ go version
go version go1.4.2 linux/amd64
```

**Comment by RowZay** [comment]
So, I found this http://stackoverflow.com/questions/29514456/go-is-printing-xgcc-version-but-not-go-installed-version, and followed the advice of doing :
$ sudo apt-get remove gccgo

That allowed "$ go run build.go setup"  to run smoothly, but the other issues still exist.

**Comment by damm** [comment]
@RowZay ahh gopkgs is :( having issues so it's not just you

http://gopkgs.com/popular/

**Comment by damm** [comment]
```
 cd .; git clone http://gopkgs.com/pool.v1 /root/go/src/gopkgs.com/pool.v1
Cloning into '/root/go/src/gopkgs.com/pool.v1'...
fatal: repository 'http://gopkgs.com/pool.v1/' not found
package gopkgs.com/pool.v1: exit status 128
godep: restore: exit status 1
```

and http://gopkgs.com/pool.v1/ is 404

**Comment by RowZay** [comment]
Any suggestions on what I can do?

**Comment by torkelo** [comment]
@RowZay does godep restore fail for you?

**Comment by RowZay** [comment]
Yeah. It outputs what I copied over in the issue.

**Comment by torkelo** [comment]
try with latest master

**Comment by RowZay** [comment]
Works like a charm

**Comment by antjori** [comment]
Hello guys,

I'm trying to customize Grafana, but I'm doing it on Windows 7 (64-bit), using Git's Bash.

Everything runs well until I try to execute bra's commands. Then I get the same error as RowZay.

$ go get github.com/Unknwon/bra
package gopkg.in/fsnotify.v1: unrecognized import path "gopkg.in/fsnotify.v1"

$ bra run
bash: bra: command not found

Below is my "go" version:

$ go version
go version go1.5.1 windows/amd64

Any idea on what it might be?

**Comment by bulletfactory** [comment]
if you echo $GOPATH do you get anything?

**Comment by antjori** [comment]
I do. I get the path defined for the $GOPATH variable:

$ echo $GOPATH/
C:\personal\work\projects\mygrafana/

**Comment by RyanCarrier** [comment]
Your gopath is incorrectly set;
[install doc](https://golang.org/doc/install)

[workspace doc](https://golang.org/doc/code.html)

You need it set this way so the importing can go to the correct places ($GOPATH/src).
 Your GOPATH is not project specific, they should all fall UNDER the GOPATH, as you will see from the second link.

**Comment by gretamosa** [comment]
Sorry for get back on track but I'm having similar problems with current bra version (running into a Ubuntu 14.04.3 LTS 64 bits and with GOPATH in /opt/grafana)

```
go get github.com/Unknwon/bra
# github.com/Unknwon/bra/cmd
src/github.com/Unknwon/bra/cmd/init.go:36: cannot use runInit (type func(*cli.Context) error) as type func(*cli.Context) in field value
src/github.com/Unknwon/bra/cmd/run.go:49: cannot use runRun (type func(*cli.Context) error) as type func(*cli.Context) in field value
src/github.com/Unknwon/bra/cmd/sync.go:36: cannot use runSync (type func(*cli.Context) error) as type func(*cli.Context) in field value
```

Then, I cannot find bra command and thus, I cannot execute bra run

Someone has experienced similar issues and can help?

Thanks in advanced,

**Comment by torkelo** [comment]
@gretamosa what go version do you have?

**Comment by gretamosa** [comment]
@torkelo I download the source code few minutes ago (commit: v3.0.4+194-gced3baf-dirty)

**Comment by torkelo** [comment]
@gretamosa I was asking about what version of the Go compiler you where using, as your gettting compile issues with bra tool

**Comment by gretamosa** [comment]
I used Go compiler version 1.5 as [Grafana Install Documentation] recommend (http://docs.grafana.org/project/building_from_source/)
`go version
go version go1.5 linux/amd64`

**Comment by torkelo** [comment]
looks like bug om github.com/Unknwon/bra that makes it not compile

opened an issue https://github.com/Unknwon/bra/issues/11

you only need bra to automatically recompile the grafana-server backend when you change the go files. You can build and run grafana using "go run build.go build"  then "./bin/grafana-server"

**Comment by gretamosa** [comment]
@torkelo Thanks!

**Comment by beckiDev** [comment]
Hi My go version is go version go1.5.2 darwin/amd64
I also cannot:
go get github.com/Unknwon/bra
# github.com/Unknwon/bra/cmd
src/github.com/Unknwon/bra/cmd/init.go:36: cannot use runInit (type func(*cli.Context) error) as type func(*cli.Context) in field value

I have outdated go get github.com/urfave/cli but still getting the same error

**Comment by yanweiran123** [comment]
Hi my go version is :  go version go1.6.2 darwin/amd64 
I also cannot: go get github.com/Unknwon/bra

Unknwon/bra/cmd/init.go:36: cannot use runInit (type func(*cli.Context) error) as type func(*cli.Context) in field value
Unknwon/bra/cmd/run.go:49: cannot use runRun (type func(*cli.Context) error) as type func(*cli.Context) in field value
Unknwon/bra/cmd/sync.go:36: cannot use runSync (type func(*cli.Context) error) as type func(*cli.Context) in field value

**Comment by yanweiran123** [comment]
@torkelo

**Comment by gretamosa** [comment]
@yanweiran123 @beckiDev You have other alternatives to compile grafana without bra:

1. GO_PATH=[your_path] make (it also update some go_deps)
2. GO_PATH=[your_path] go run build.go build (and then grunt if it is necessary to recompile frontend assets).

**Comment by yanweiran123** [comment]
@gretamosa   Thanks, but I want to is there any influence if I compile grafana without bra?
In fact I can compile my source code, and also run it without bra

**Comment by gretamosa** [comment]
@yanweiran123 AFAIK there is no influence just another way to compile grafana.

**Comment by RyanCarrier** [comment]
Guys, from the other link;
` Hi, your github.com/codegangsta/cli is outdated. `

to update all your packages;
`go get -u all`

**Comment by yanweiran123** [comment]
@RyanCarrier  Are u success?

**Comment by RyanCarrier** [comment]
@yanweiran123 I am success.

**Comment by ydp** [comment]
I had the same problem, tried @yanweiran123 ' method, and It worked!
