### ISSUE TITLE
Errors when using "Today" time range

### ISSUE THREAD

**Issue by nosteine** [grafana/grafana#21530]
I am using Prometheus data source. 
When running rate queries with time range "Today", for some panels I am getting this error after some time:

> 504 Gateway Time-out
> The server didn't respond in time.

However, when querying with "last 24 hours", then it returns just fine.
Also, I have a different query which has a counter with a 5m range in the query.
Here I get "No data" when using "Today".
I suspect this is because "Today" is a behaving differently that other ranges because it includes future time (until EOD), but I am not sure about this,
I would apprecieate your help in this.
I realize this might be a Prometheus thing and not Grafana, but these queries do work on the Prometheus side AFAICT

Thanks

**Comment by marefr** [comment]
Please use query inspector in query tab in Grafana and inspect request/response to see whether this is a Grafana or prometheus issue. You could include request/reponse here.

> but these queries do work on the Prometheus side AFAICT
Are you using today as timerange in prometheus ui or what?

**Comment by torkelo** [comment]
closing due to lack of updates
