### ISSUE TITLE
Add a builtin variable $__timezone containing the timezone

### ISSUE THREAD

**Issue by bgranvea** [grafana/grafana#21542]
**What would you like to be added**:
Expose a $__timezone global built-in variable which contains the timezone used to display the dashboard (either UTC if set in user preferences or the browser timezone).

**Why is this needed**:
I'm using dashboard links to have dashboard renderings. The rendering is not the same as what the user sees in his browser because of the missing timezone information.

**Comment by marefr** [comment]
dashboard renderings - do you mean rendering image of panel? If you do panel -> share -> direct rendered image you should notice that url opened contains `&tz=Europe%2FStockholm` or whatever timezone you're browser is using.

**Comment by bgranvea** [comment]
yes it works for the rendering of panels. I would like to do the same with the rendering of an entire dashboard. For the moment, I'm using a link configured in Dashboard settings > Links:

type: link
url: render/d/my-uid/my-dashboard?width=1000&height=1000
time range: true
variables: true

but the timezone used for the rendering is always UTC (I'm using the grafana-image-renderer in a separate service).

I realize that adding a $__timezone is not enough to solve my use case. I close this issue and open another on the ability to create dashboard rendering links.
