### ISSUE TITLE
Grafana image renderer not available for download

### ISSUE THREAD

**Issue by polycaster** [grafana/grafana#21551]
**What happened**: 
Tried to download the zip for the plugin from the plugins page and was met with the following message:
```
{
  "code": "BadRequest",
  "message": "Version 1.0.7 is not available for undefined-undefined"
}
```
Tried all versions available and the error persisted. Had success installing it using the CLI, however I want to be able to get the hash of the zip instead of dynamically downloading the plugin every time I build my grafana image
**What you expected to happen**:
Expected the zip file with the plugin to be available
**How to reproduce it (as minimally and precisely as possible)**:
Click this, https://grafana.com/api/plugins/grafana-image-renderer/versions/1.0.7/download

**Comment by marefr** [comment]
https://github.com/grafana/grafana-image-renderer/issues/47
