### ISSUE TITLE
GF_AUTH_ANONYMOUS_ENABLED Not being detected

### ISSUE THREAD

**Issue by Slyke** [grafana/grafana#21555]
**What happened**:
Anonymous login is not working

**What you expected to happen**:
Anonymous dashboard view

**How to reproduce it (as minimally and precisely as possible)**:
1. Use base Grafana image.
2. Login and do initial setup.
3. Set `GF_SECURITY_ALLOW_EMBEDDING=true` and `GF_AUTH_ANONYMOUS_ENABLED=true` in environment variables.
4. Restart Grafana

**Anything else we need to know?**:
I'm installing the Grafana image from: https://github.com/gcgarner/IOTstack
I can see that `ALLOW_EMBEDDING` is working, but `AUTH_ANONYMOUS_ENABLED` is not.
I can see that the org exists `Main Org.`
Logs are below.
There are no other config files.

My Grafana Logs:
```
t=2020-01-17T05:12:07+0000 lvl=info msg="Starting Grafana" logger=server version=6.3.6 commit=fdd2117 branch=HEAD compiled=2019-09-23T08:14:34+0000
t=2020-01-17T05:12:07+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-01-17T05:12:07+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
t=2020-01-17T05:12:07+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ALLOW_EMBEDDING=true"
t=2020-01-17T05:12:07+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-01-17T05:12:07+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-01-17T05:12:07+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-01-17T05:12:07+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-01-17T05:12:07+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-01-17T05:12:07+0000 lvl=info msg="App mode production" logger=settings
t=2020-01-17T05:12:07+0000 lvl=info msg="Initializing SqlStore" logger=server
```

**Environment**:
- Grafana version: v6.3.6
- Data source type & version: InfluxDB (But not relevant)
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10/Chrome
- Grafana plugins: None
- Others:

**Comment by marefr** [comment]
Since we don't maintain https://github.com/gcgarner/IOTstack we cannot support it here. Will close this. If you run grafana docker image using `docker run -e GF_AUTH_ANONYMOUS_ENABLED=true  ...` and you can provide information that it doesn't work we'll consider reopen this issue. 

Just looking quickly at that project seems like you have to the environment variables in https://github.com/gcgarner/IOTstack/blob/master/.templates/grafana/grafana.env, but please open an issue in that repo and ask to be sure.

**Comment by Slyke** [comment]
Hey @marefr I know you closed the issue, but thought I'd report my findings here: Wasn't an issue with either code base.

Looks like there was an issue where the env file wasn't being written to disk (somehow?) even though opening it with cat and VIM showed it had saved my env var.

A restart of the system and adding the env back in corrected this.
