### ISSUE TITLE
[FeatureRequest] DashboardLinks: Add link of type "rendering"

### ISSUE THREAD

**Issue by bgranvea** [grafana/grafana#21556]
**What would you like to be added**:
In Dashboard settings > Links, I would like to add a new type of link called "rendering". This would allow to have rendering of the entire dashboard (it already exists only for individual panel). This type of link would have the following properties:

type: rendering
with: ...
height: ...
encoding: png / jpeg / pdf (combo box or free text field?)
other parameters: ... (allow to transmit extra parameters to renderer, see https://github.com/grafana/grafana/pull/21307)
time range: ...
variables: ...

**Why is this needed**:
For the moment it is not very easy to link to a rendering of the entire dashboard. As a workaround, I'm using dashboard link configured like this:

type: link
url: render/d/my-uid/my-dashboard?width=1000&height=1000
time range: true
variables: true

but the timezone of the browser cannot be transmitted, so the rendering is different from what the user sees in his browser.

Together with https://github.com/grafana/grafana-image-renderer/pull/80 it can serve as a way to have PDF rendering of a dashboard and be a first step until a feature like #17794 is implemented.

**Comment by marefr** [comment]
Wouldn't it make more sense to put this in Dashboard -> Share, similar to how it works for panels (Panel -> Share)?

**Comment by bgranvea** [comment]
yes it could be an option. The difference that I see is that Dashboard > Share is intended for the end user (viewer), whereas Dashboard settings > Links is for the designer (editor) of the dashboard.  

In my case, I would prefer to let the dashboard editor configure rendering parameters and let the viewer have a simple link with no options.

What do you think?
