### ISSUE TITLE
Grafana Stuck Logging In

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#21553]
**What happened**:
When trying to log into LDAP backed Grafana instance Log In just hangs and never completes (or note a failure); login splash screen loads normally

**What you expected to happen**:
Normal log in to dashboard

**How to reproduce it (as minimally and precisely as possible)**:
Navigate to grafana URL, enter credentials and hit log in

**Anything else we need to know?**:
I noticed this issue after running yum update on our Grafana servers, which moved Grafana up from v6.4.2 to v6.5.2, after downgrading back to v6.4.2 the problem persists.  I've removed Grafana from behind an apache proxy to make sure the httpd proxy isn't causing the issue, it's error log was noting:
`[Thu Jan 16 11:32:14.376932 2020] [proxy_http:error] [pid 9891] (70007)The timeout specified has expired: [client XXX.XXX.60.24:54308] AH01102: error reading status line from remote server 127.0.0.1:3000, referer: https://set-analytics.ncsa.illinois.edu/login
[Thu Jan 16 11:32:14.376992 2020] [proxy:error] [pid 9891] [client XXX.XXX.60.24:54308] AH00898: Error reading from remote server returned by /login, referer: https://set-analytics.ncsa.illinois.edu/login`

I upped the log level on Grafana to debug and didn't get much that was helpful, other than it looks like the LDAP section of the stack is not the issue as it seems my user auth's successfully but there are a lot of dashboards in this instance and not nearly all of them are listed in the log even after many minutes

`t=2020-01-16T11:33:15-0600 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2020-01-16T11:33:43-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=141.142.60.24 time_ms=0 size=29 referer=
t=2020-01-16T11:33:48-0600 lvl=info msg="LDAP enabled, reading config file" logger=ldap file=/etc/grafana/ldap.toml
t=2020-01-16T11:33:56-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:33:57-0600 lvl=dbug msg="avatar.fetch(fetch new avatar): http://secure.gravatar.com/avatar/1c89e98e263a52cca24edab5356d2f16?d=retro&r=pg&size=200"
t=2020-01-16T11:33:57-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=4 action=View
t=2020-01-16T11:33:57-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=4 action=Edit
t=2020-01-16T11:33:57-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=4 action=Edit
t=2020-01-16T11:33:57-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=4 action=Admin
t=2020-01-16T11:34:12-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=3 action=View
t=2020-01-16T11:34:12-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=3 action=Edit
t=2020-01-16T11:34:12-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=3 action=Edit
t=2020-01-16T11:34:12-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=3 action=Admin
t=2020-01-16T11:34:24-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=7 action=View
t=2020-01-16T11:34:24-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=7 action=Edit
t=2020-01-16T11:34:24-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=7 action=Edit
t=2020-01-16T11:34:24-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=7 action=Admin
t=2020-01-16T11:34:41-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=36 action=View
t=2020-01-16T11:34:41-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=36 action=Edit
t=2020-01-16T11:34:41-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=36 action=Edit
t=2020-01-16T11:34:41-0600 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=6 orgId=1 uname=malone12 dashId=36 action=Admin
t=2020-01-16T11:38:57-0600 lvl=dbug msg="token needs rotation" logger=auth tokenId=71 authTokenSeen=true rotatedAt=2020-01-16T11:28:56-0600
t=2020-01-16T11:38:57-0600 lvl=dbug msg="auth token rotated" logger=auth affected=1 auth_token_id=71 userId=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:38:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:39:13-0600 lvl=dbug msg="seen token" logger=auth tokenId=71 userId=6 clientIP=141.142.60.62 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" authToken=a33500de27ca992effdd47209315ca0587985641e7f984505c45d945ed3206b4
t=2020-01-16T11:43:15-0600 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 kept=0
t=2020-01-16T11:43:15-0600 lvl=dbug msg="Deleted expired snapshots" logger=cleanup rows affected=0
t=2020-01-16T11:43:15-0600 lvl=dbug msg="Deleted old/expired dashboard versions" logger=cleanup rows affected=0
t=2020-01-16T11:43:15-0600 lvl=dbug msg="Deleted expired login attempts" logger=cleanup rows affected=0
t=2020-01-16T11:43:15-0600 lvl=dbug msg="Checking for updates" logger=plugins
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6
t=2020-01-16T11:43:57-0600 lvl=dbug msg="Updating last user_seen_at" logger=context userId=6 orgId=1 uname=malone12 user_id=6`

**Environment**:
- Grafana version: v6.5.3 (also now on v6.4.2)
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS 7.7
- User OS & Browser: Mac OS X; Safari and Chrome tested
- Grafana plugins: Pie Chart,PictureIt,D3 Gauge, World Map, Status Panel
- Others:

**Comment by marefr** [comment]
What was the problem?

**Comment by jdmaloney** [comment]
@marefr This ended up being an LDAP timeout issue so not grafana related.  I didn't initially suspect that since I saw the "user last seen" being updated as well as the account being granted permissions on dashboards.
