### ISSUE TITLE
Graphite: queries can get saved with "select metric" in the metric path

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#21563]
**What happened**:

If there is no data for a Graphite metric and I open a query editor then the last segment of the metric path gets replaced with `select metric`:

![image](https://user-images.githubusercontent.com/434655/72611075-63db9a00-3929-11ea-9150-2ebb38006669.png)

In a large dashboard, with lots of queries it can happen that one or more queries times out. A user can then accidentally save the dashboard with the now invalid query. This regularly breaks dashboards.

This is not a bug and is intentional - see the [CheckOtherSegments](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/query_ctrl.ts#L89-L97) function that is called in [BuildSegments](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/query_ctrl.ts#L61-L62) in the queryCtrl

**What you expected to happen**:

This is used as a way of indicating that the metric doesn't exist - a better way to do this would be #6448. I propose removing this behavior of modifying the query when the query editor is opened for now so that you can see what the metric path should have been:

![image](https://user-images.githubusercontent.com/434655/72611045-4b6b7f80-3929-11ea-8d18-c2d596d69986.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Open a dashboard with Graphite queries that have no data. 
2. Edit a panel and open the query editor

**Comment by Dieterbe** [comment]
It's okay for the query editor to give the user a hint that the query doesn't match anything, and that perhaps they should change the query editor.

It's not okay to destroy the users' actual query under any circumstance. Whether or not the lack of data was temporary.
I believe I've seen Grafana alter the query this way even if the user didn't even go to the editor.
This way you can completely break a dashboard just by saving it.

**Comment by torkelo** [comment]
Grafana will never alter queries outside the query editor
