### ISSUE TITLE
auto_registration fails when used with auth proxy

### ISSUE THREAD

**Issue by kamaradclimber** [grafana/grafana#2156]
Using the feature described on #1921 (from master), it seems that we cannot use more than 1 user with auth_proxy.

The first one, "bob" is created in the database and can accasse grafana.
The second one, "alice" cannot access and we get a server side error: `Failed to create user specified in auth proxy header`.

This is due to the unique constraint on login/email and the fact that users authenticated via proxy are created with either empty email or login.

Relevant config:
```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = email
auto_sign_up = true
```

**Comment by kamaradclimber** [comment]
A very easy workaround is to modify pkg/middleware/auth_proxy.go with the following patch:
```
--- a/pkg/middleware/auth_proxy.go
+++ b/pkg/middleware/auth_proxy.go
@@ -60,8 +60,10 @@ func getCreateUserCommandForProxyAuth(headerVal strin
        cmd := m.CreateUserCommand{}
        if setting.AuthProxyHeaderProperty == "username" {
                cmd.Login = headerVal
+               cmd.Email = headerVal
        } else if setting.AuthProxyHeaderProperty == "email" {
                cmd.Email = headerVal
+               cmd.Login = headerVal
        } else {
                panic("Auth proxy header property invalid")
        }
```

Another way would be to allow null for login and email fields in sql (unique constraint do not apply on null, in sqlite at least).

**Comment by torkelo** [comment]
thanks for reporting this, thanks
