### ISSUE TITLE
Example config string for redis is wrong

### ISSUE THREAD

**Issue by andsens** [grafana/grafana#2157]
In `grafana.ini`:

```
# redis: config like redis server addr, poolSize, password, e.g. `127.0.0.1:6379,100,grafana`
```

However, the actual config string should look like this:
```
provider_config = addr=127.0.0.1:6379,pool_size=100,db=grafana
```

At least, that's what works for me...

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by melvilgit** [comment]
even this is also not working. Can you please check ?
