### ISSUE TITLE
Indicate visually that the returned log limit has been reached (in Explore)

### ISSUE THREAD

**Issue by ldealmei** [grafana/grafana#21576]
**What would you like to be added**:
A visual cue that signifies that the returned logs have reached the set limit. 
This could be as simple as making `Limit:1000 (1000 returned)` appear in bold bright red. Or adding an overlay over the time range that does not return any data (see example image below).

**Why is this needed**:
In the Explore tool, the users associate a green bar to the presence of logs. And conversely, the absence of a green bar means that there are no logs.
However if the log limit is reached, no green bar beyond a certain timestamp does not mean that there are no logs. This has lead my users to start debugging things that did not need debugging because they thought something was wrong with their processes.
Adding a visual cue suggesting that no logs are shown because limit is reached would make it more intuitive

Example:
<img width="1609" alt="Schermafbeelding 2020-01-17 om 15 31 51" src="https://user-images.githubusercontent.com/5574992/72620088-ea4ea680-393e-11ea-960f-7f50af6d66b5.png">

Thanks!

**Comment by aocenas** [comment]
@ldealmei right now the graph for when using loki is computed from the logs themselves so if the limit is 1000 the graph has the same limit. Now that Loki also can do a metric type queries we plan to do a separate query for the log counts which would span the whole time range (this is how Elastic works right now). That should fix this issue.

**Comment by ldealmei** [comment]
Sounds good, thank you

**Comment by aocenas** [comment]
Going to close this as it should be addressed by this issue: https://github.com/grafana/grafana/issues/19949
