### ISSUE TITLE
Migrate ts-loader to babel

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21583]
Work started by @stevenvachon in https://github.com/grafana/grafana/pull/21554 is very promising from performance perspective (https://github.com/grafana/grafana/pull/21554#issuecomment-575577602) and will also enable us to use Emotion 10 `css` property syntax. 

Creating this issue to keep track of  problems to be solved:

- [x] PhantomJS breaks when running bundled code (maybe because of preset env targeting lates 3 versions of browsers)
- [x] Object spread is causing trouble (`Invalid attempt to spread non-iterable instance
    at _nonIterableSpread (navModel.ts:51)`, relevant code fixed by @torkelo : https://github.com/grafana/grafana/commit/5af7b15c1028b6962414a9355e43086519b0c7dd ). We most probably need an apropriate babel plugin to handle that

**Comment by stevenvachon** [comment]
Replace PhantomJS with Chrome/Chromium headless or Puppeteer?

**Comment by dprokop** [comment]
@stevenvachon can't do that until 7.0 - that's when we remove phantomJS in favour of https://github.com/grafana/grafana-image-renderer

**Comment by stevenvachon** [comment]
Whoa.. that sounds like a long wait for many other changes that are waiting on this.

**Comment by dprokop** [comment]
@stevenvachon i think there might be a way of addressing this with babel presets/plugins, not sure yet

**Comment by stevenvachon** [comment]
That will increase the build size and definitely complication with additional shims/polyfills, but you're right that it can be done sooner than 7.0.

**Comment by stevenvachon** [comment]
@dprokop can this be closed now that #21587 has been merged?

**Comment by dprokop** [comment]
Yup! Closing
