### ISSUE TITLE
Status Panel Visualisation does not change when server is critical

### ISSUE THREAD

**Issue by Silas-Asamoah** [grafana/grafana#21584]
**What happened**: Status Panel does not indicate red when server is critical.

**What you expected to happen**: Status panel goes red when server is critical or displays no colour when shutdown.

**How to reproduce it (as minimally and precisely as possible)**:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/query",
    "params": {
      "db": "telegraf",
      "q": "SELECT last(\"result_code\") FROM \"net_response\" WHERE (\"server\" = 'SERVER_ADDRESS' AND \"port\" = 'PORT No.') AND time >= now() - 1m GROUP BY time(500ms) fill(none)",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "net_response",
            "columns": [
              "time",
              "last"
            ],
            "values": [
              [
                1579274615000,
                2
              ],
              [
                1579274625000,
                2
              ],
              [
                1579274635000,
                2
              ],
              [
                1579274645000,
                2
              ],
              [
                1579274655000,
                2
              ]
            ]
          }
        ]
      }
    ]
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.3.4
- Data source type & version: InfluxDB 
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- User OS & Browser: Windows & Chrome
- Grafana plugins: Status Panel https://grafana.com/grafana/plugins/vonage-status-panel
- Others:

**Comment by torkelo** [comment]
please open an issue with the authors of this external (3rd party) plugin: https://github.com/Vonage/Grafana_Status_panel

**Comment by Silas-Asamoah** [comment]
> please open an issue with the authors of this external (3rd party) plugin: https://github.com/Vonage/Grafana_Status_panel

Thanks for the response!
