### ISSUE TITLE
Explore: Adding label matcher from table doesn't work with log metrics query

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#21589]
**What happened**:

When you're doing a metrics query on logs such as `rate({job="default/prometheus"}[5m])`.

The table view show the instant value result. But if I click in one cell to add a new label matcher if actually break the query like this `{job="default/prometheus",level="info"} rate([5m])`

![image](https://user-images.githubusercontent.com/1053421/72645062-ac528200-3940-11ea-8ee5-ab56b61d13fb.png)

**What you expected to happen**:
I would expect the query to be `rate({job="default/prometheus",level="info"}[5m])`

**How to reproduce it (as minimally and precisely as possible)**:

1 - make a metric query `rate({job="default/prometheus"}[5m])`.
2 - On the table result click on a cell to add a label.

**Environment**:
- Grafana version: `rate({job="default/prometheus"}[5m])`.
- Data source type & version: Loki

**Comment by ivanahuckova** [comment]
Yeah @cyriltovena, good catch! Loki has currently a very basic "add a new label matcher" functionality, so it is not going to work with metrics queries. I will look at this issue.
