### ISSUE TITLE
OAuth: Implement Azure AD provider

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#21581]
Currently you have to use Generic OAuth configuration to use Azure AD, but it's a bit limited. Suggest to Implement specific Azure AD OAuth provider.

Related issues: 
- OpenID unique user identifier #17635
- Add support for teams or orgs in Azure AD OAuth #15670
- id_token signature validation #15312

**Comment by dekimsey** [comment]
It should be noted there's a difference between the Azure v1 endpoint and the Azure OAuth 2.0 endpoint. The latter being an actual OIDC provider. PR #20030 just recently switched over to the 2.0 interface, which is great!

Microsoft has a write-up about the difference [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison)
