### ISSUE TITLE
CloudWatch variables not split when using All without Multi-value

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#21592]
**What happened**:

I'm using the cloudwatch plugin. I have a variable setup that pulls instance IDs. I have the variable hidden, and I expect it to default to "all" values. When I use this variable in a very simple query the commas are not removed/split and replaced with `OR`.

![Screen Shot 2020-01-17 at 4 10 28 PM](https://user-images.githubusercontent.com/2402929/72654792-f1c57e00-3945-11ea-813d-562d9aa49fcf.png)

**What you expected to happen**:

Instead of creating a valid query it queried `{i-instance1,i-instance2, etc}`. I expected the variable values to be split and `OR`'d together. 

![Screen Shot 2020-01-17 at 4 16 46 PM](https://user-images.githubusercontent.com/2402929/72654730-a6ab6b00-3945-11ea-938a-fafd7ee11c8c.png)

**How to reproduce it (as minimally and precisely as possible)**:

The two screenshots above should provide ample reproducibility. The kicker is how to workaround the problem. If you edit the variable and enable "multi value" everything begins to work as expected. This took me a long time to figure out, and if nothing else, I hope this issue saves someone else an hour.

Shot of it working after turning on multi value:

![Screen Shot 2020-01-17 at 4 21 08 PM](https://user-images.githubusercontent.com/2402929/72654689-7b288080-3945-11ea-9580-63b3fd53986e.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: CloudWatch (latest w/ 6.5.3)
- OS Grafana is installed on: Docker on Fargate/ECS
- User OS & Browser: Chrome and Safari were tested
- Grafana plugins: Quite a few..... If you want them I can provide them. Everything else is working great.

**Comment by Prashansa-K** [comment]
@sunker @aknuds1 @mtanda Any ETA on this issue?

**Comment by sunker** [comment]
Even though this is not completely intuitive, this is actually expected behavior. For this to work you need to enable the `Multi-value` option when configuring the template variable. Read more about how to use multi-value template variables in the cloudwatch datasource [here](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#multi-value-template-variables)

**Comment by davidnewhall** [comment]
I think the UI could be totally be improved to make this behavior more understood. There are certainly times when you don't want dashboards with a multi-value drop-down menu too, so this still feels like a place we can improve.
