### ISSUE TITLE
Influx DB log Mode in Dashboard

### ISSUE THREAD

**Issue by ziadkiwan** [grafana/grafana#21593]
**What happened**:
I'm trying to pipe some logs from a plain text file to grafana so i can save it as a dashboard and users can view it, i created a script that insert the data into influx DB with the required tags and fields as stated in the tutorials, now i can see the data inside influx DB and i can query them, when i go and create a dashboard and choose influx db i cannot find the button that switch to logs mode so i can show the data in logs format, i tried to put the visualization as "logs", but still i cannot see any data.

What makes me wonder is that when i go to "Explore mode" and choose the logs mode i can see all the data and query them, but i cannot save the explore mode into dashboard too. 

So to summarize, there is no button to switch to logs mode when choosing influx as DB in dashboard not in explore.

**Explore Mode:**
![Capture](https://user-images.githubusercontent.com/7920707/72662697-b59c2700-39f2-11ea-9c64-ab1efcc80754.PNG)

**Dashboard Mode:**
![Capture2](https://user-images.githubusercontent.com/7920707/72662707-f431e180-39f2-11ea-8274-56f423e071e0.PNG)

Thanks.
**What you expected to happen**:
So to summarize, there is no button to switch to logs mode when choosing influx as DB in dashboard not in explore.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Influx DB Version 
- OS Grafana is installed on: Centos 7
- User OS & Browser: Firefox that comes preinstalled with Centos 7
- Grafana plugins: N/A
- Others:

**Comment by jcdauchy** [comment]
I guess Logpanel is not working with influxdb datasource. Would be really nice to be table to save logs to influxdb as a long term log solution whereas short term log could be saved in Loki.

**Comment by aknuds1** [comment]
This looks like a feature request, labeling it as such and assigning it to the observability team.

**Comment by aknuds1** [comment]
Actually, when I test (both latest master and v6.5.3), I find that it is possible to add a logs panel with InfluxDB as data source.

![](file:///home/arve/Downloads/Screen%20Shot%202020-01-20%20at%2016.16.03.png)

Closing issue for now, since it seems to actually work.

**Comment by ziadkiwan** [comment]
Hello Could you please how where you able to do it? a small hint ? because it's not working for me, Thanks!
