### ISSUE TITLE
Explore: Return to the top

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#21590]
**What would you like to be added**:

When I'm using explore, and I'm scrolling down to the bottom, I want to be able to quickly go back to the top and refine my query.

**Why is this needed**:

Hurt my scroll wheel and my finger.

**Comment by zoltanbedi** [comment]
Related to #20586. At the end I think we are going to implement one from these solutions but not both.

**Comment by ivanahuckova** [comment]
Fixed in https://github.com/grafana/grafana/pull/33910. Will be part of Grafana 8.
