### ISSUE TITLE
6.5.2 memory will go up when dashboard page always run

### ISSUE THREAD

**Issue by lujiao87** [grafana/grafana#21601]
What happened:
**memory always rise**
What you expected to happen:
**memory should be smooth**
How to reproduce it (as minimally and precisely as possible):
1. open a dashboard with 50 graph panels.
2. set datasource 
3. use monitor tool to monitor the page process.
4. let this page run 4 days in activation page.

**Anything else we need to know?**:
[50panel.json.txt](https://github.com/grafana/grafana/files/4084034/50panel.json.txt)
we use above panel json，run for 4 days to test its stability，we monitor the dashboard page process, found that this page process always rise.

![50panel-chrome-13884_Mem](https://user-images.githubusercontent.com/53459043/72692887-4eed4980-3b69-11ea-8928-fcbc1e6d1552.png)
![50panel-chrome-13884_CMV](https://user-images.githubusercontent.com/53459043/72692907-66c4cd80-3b69-11ea-806c-51b773c8c8f0.png)

**Environment**:
- Grafana version:  6.5.2
- Data source type & version:  grafana 
- OS Grafana is installed on: win10
- User OS & Browser:win10 chrome
- Grafana plugins: graph 
- Others:

**Comment by aknuds1** [comment]
Thanks for reporting - are you referring to browser memory usage?

**Comment by lujiao87** [comment]
> Thanks for reporting - are you referring to browser memory usage?

Yes.this is browser memory usage
![50panel-chrome-5464_CMV](https://user-images.githubusercontent.com/53459043/72766719-1498b080-3c2c-11ea-9816-2922c3995ce9.png)

![50panel-chrome-5464_Mem](https://user-images.githubusercontent.com/53459043/72766583-8290a800-3c2b-11ea-9dfc-6ba606042071.png)

**Comment by ryantxu** [comment]
Is this with refresh query?  or just sitting there?  How often is your refresh?

**Comment by lujiao87** [comment]
> Is this with refresh query? or just sitting there? How often is your refresh?

yes ,use grafana datasourse , with 5s refresh。

**Comment by torkelo** [comment]
Can you test 7.0 ? should be some memory improvements
