### ISSUE TITLE
Prometheus metric autocompletion/lookup not working

### ISSUE THREAD

**Issue by loomsen** [grafana/grafana#21608]
**What happened**:
Prometheus metrics autocompletion of remote prometheus server is not working.

![Selection_374](https://user-images.githubusercontent.com/302524/72709973-4e9f7f00-3b66-11ea-8909-e449e334b2e2.png)

When I run the query in the explorer or to populate dashboards, everything works as expected. Labels and their values are being completed just fine without running a query first.

![Selection_377](https://user-images.githubusercontent.com/302524/72710011-670f9980-3b66-11ea-996e-46dc72075fff.png)

For the prometheus instance internal to the cluster, the metrics lookup works fine. 

![Selection_379](https://user-images.githubusercontent.com/302524/72710184-ccfc2100-3b66-11ea-8898-1da51135ed8f.png)

Logs don't show any errors or timeouts neither.

**What you expected to happen**:

I expect the metrics lookup and thus autocompletion of metrics names on remote prometheus servers to work, when the Datasource configuration claims everything to be fine.

**How to reproduce it (as minimally and precisely as possible)**:

Add a prometheus datasource in a different kubernetes cluster and try _metric autocompletion_ in explorer (or anywhere in grafana).

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.2 (742d165)
- Data source type & version: prometheus
- OS Grafana is installed on: GKE - container optimized OS
- User OS & Browser: Fedora 31 Linux - Google Chrome
- Grafana plugins: DevOpsProdigy KubeGraf
- Others: some panels, nothing special

**Comment by s-h-a-d-o-w** [comment]
Could you please post a screenshot of the network tab in Chrome's devtools, after doing the following:
- Choosing the problematic data source
- Checking "disable cache"
- Refreshing the page

Maybe we will see something unusual about the metrics request.

**Comment by loomsen** [comment]
Hi @s-h-a-d-o-w,

I just tried to take such a screenshot, but it seems to work now. I don't know what happened, but this Issue can be closed.
