### ISSUE TITLE
feature: Template variables: dependent variables restrict parent.

### ISSUE THREAD

**Issue by kportertx** [grafana/grafana#2160]
I'm using the following variables:

Region, Host, ClusterName

When I select a Region, the child options are updated to only show Host and ClusterName options in that Region.

But if I set ClusterName I am still able to select any Region and graphs pertaining to a Region only still show all regions.

ClusterNames are unique per Region so ideally when I select a ClusterName only the region graphs that cluster exists in are presented.

**Comment by torkelo** [comment]
template variables should only have a parent child relation child, circular dependencies between different template variables is not supported.

**Comment by kportertx** [comment]
This is a parent child relationship. I have selected a child that is in only one parent but the options provided by the parent are not filtered.

**Comment by torkelo** [comment]
As I said the parent cannot be affected.by the child variable, that would cause a circular dependency

**Comment by kportertx** [comment]
Ok, so maybe you could help with my modeling problem?

All of my metrics come in the following form:

    $zone.$host.etc.etc

Some of my hosts are part of clusters and their metrics come in this form:

    $zone.$host.$clusterName.etc.etc

For a particular dashboard dealing with clusters I would like to make $host a child of $clusterName, I would like to define something like:

    $host = /$zone\.(\W+)\.$clusterName/

Is there currently possible? If not I can set an aggregation rule to rename metrics with a cluster to $zone.$clusterName.$host.etc.etc, but was hoping to avoid doing this since the rest of the metrics will be $zone.$host.etc.etc.

**Comment by torkelo** [comment]
as long as you define variables for $zone and $clusterName do not depend on $host, so no circular dependency
