### ISSUE TITLE
Change column name order of table

### ISSUE THREAD

**Issue by steenstra** [grafana/grafana#21609]
**What happened**:
The Column names of a query with a Group By clause are sorted alphabetically by the tag name. 

**What you expected to happen**:
Use the order in which the Group By clauses are stated. 

**How to reproduce it (as minimally and precisely as possible)**:
Use Group By in a query

**Environment**:
Grafana v6.5.2
datasource: InfluxDB

**Comment by torkelo** [comment]
This sounds like either a feature request / issue for InfluxDB or a wish for an option in the table panel to re-arrange columns: https://github.com/grafana/grafana/issues/5082
