### ISSUE TITLE
On page load: same query is fired multiple times.

### ISSUE THREAD

**Issue by scelle** [grafana/grafana#21612]
Hi, 

This is probably not a real bug, more like a different behaviour between versions:

I switched from Grafana 6.3.5 to 6.5.3.  Since then I noticed clearly slower page loading.
After some investigation in the chrome devtools I noticed that the same set of queries are executed up to 12 times after each other.  This obviously explains the slow page loading.

The dashboard has some specific text panels with js code running inside, calling angular elements variableSrv and timeSrv.

```
var varService = angular.element('grafana-app').injector().get('variableSrv');
var timeService = angular.element('grafana-app').injector().get('timeSrv');
...
varService.variableUpdated(varSubId, true);
...
timeService.setTime(timeService.time);
```
So for each update of a templateVariable or of the time range the query is fired again,
It seems logic that in case of a **change**, the query is fired again, but in my case, the query is identical.

So my question is: 

- Is there a change in the code that explains this different behavior?
- How can I avoid this behaviour?  knowing that I would still like to be able to change templatevariables and timeranges in my own html/js "navigation panel" based on a text panel.

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Influxdb
- OS Grafana is installed on: windows 10
- User OS & Browser: windows 10 & Chrome (Version 79.0.3945.117 (Official build) (64-bits))
- Grafana plugins:
- Others:

**Comment by ryantxu** [comment]
Are you using out-of-the-box panels and datasources?  or is this something custom?

> Is there a change in the code that explains this different behavior?

yes, things got moved so we now have a shared query runner for each panel -- that is not controlled by the plugin.  There are some hoops to make it work nicely with the angular MetricPanelCtrl -- but custom panels/execution may do something odd

https://github.com/grafana/grafana/blob/master/public/app/features/panel/metrics_panel_ctrl.ts#L200

**Comment by scelle** [comment]
I use the standard graph panel combined with standard Influxdb datasource.
As a test, I made a simple page, containing 1 graph panel, and 1 textpanel, with only the js code I mentioned.

```
<script>
var varService = angular.element('grafana-app').injector().get('variableSrv');
var timeService = angular.element('grafana-app').injector().get('timeSrv');
onLoad();

function onLoad() {
updateTime();
changeMeasIds()
  }

function updateTime() {
  const currentTime = timeService.time;
  const newTime = {"from":"now-12h","to":"now"};
  timeService.setTime(newTime);
  }

function changeMeasIds(){
  var dMeasId1 = varService.variables.find(v => v.name == 'dMeasId1');
  var dMeasId1New = 1 ;
  dMeasId1.current = {text: Number(dMeasId1New), value: Number(dMeasId1New)};
  varService.variableUpdated(dMeasId1, true);
  }
</script>
```
On loading this grafana page, the same query for the graph panel is called 3 times, 
1 time, normally initiated by the panel, the next 2 times I suppose are initiated by the js lines
timeService.setTime(newTime);
varService.variableUpdated(dMeasId1, true);

As far as this could be usefull, json code of the dashboard attached:
[multipleSameQuery-1579605218663.zip](https://github.com/grafana/grafana/files/4090755/multipleSameQuery-1579605218663.zip)

**Comment by dprokop** [comment]
> the next 2 times I suppose are initiated by the js lines
timeService.setTime(newTime);
varService.variableUpdated(dMeasId1, true);

Yes, that's right. Time range update results in dashboard refresh: https://github.com/grafana/grafana/blob/0f0374544f7d76d8e1fde046a8bb7007b4e8b5ea/public/app/features/templating/variable_srv.ts#L75 as well as variable update https://github.com/grafana/grafana/blob/0f0374544f7d76d8e1fde046a8bb7007b4e8b5ea/public/app/features/templating/variable_srv.ts#L156

**Comment by torkelo** [comment]
Given that custom script there is no suprise there are multiple queries fired. 

1) initial load => queries fired 
2) Custom script changes time range => queries fired 
3) Custom script changes variable => queris fired

**Comment by scelle** [comment]
Ok, I understand, it's up to me to optimize and only call timeserver and varserver on real changes, 

On the other hand, even in the case that I would not use any custom scripts, I have a similar issue with template variables:
Changing one template variable that is used for 1 query in 1 panel, also triggers all xx other queries on my dashboard, not using this template variable.  
I suppose in most cases this will not be noticeable... 
Anyhow, thanks for the support!
