### ISSUE TITLE
New Gauge: Does Not Dynamically Change with Stat

### ISSUE THREAD

**Issue by zacharyhumphrey** [grafana/grafana#21628]
#### Issues:

1. The new gauge does not dynamically adjust to the amount stated in the marking.  For instance, I expect the green in the gauge in the first image to be stopped at the 22ish GB mark... But it is currently full.
![image](https://user-images.githubusercontent.com/49042255/72748316-81547200-3b7c-11ea-9cb8-8aa0faccfcf1.png)

2. Also, we now have the text shown as an override with the color in the chart. How can this change to just be white and NOT dynamic? We do not want the text color to change with the status of the gauge. 

#### Config: Gauge

![image](https://user-images.githubusercontent.com/49042255/72748590-430b8280-3b7d-11ea-8f61-4abfcc233e02.png)

![image](https://user-images.githubusercontent.com/49042255/72748304-7863a080-3b7c-11ea-93ba-472bb68e46af.png)

I'd also like to point out how outdated the documentation related to gauge is as some image STILL show old config values that are not currently available... For example, stat in the image of the image below: 
![image](https://user-images.githubusercontent.com/49042255/72748284-6aae1b00-3b7c-11ea-8aab-7100677ab31d.png)
* Notice the missing 'stat' missing? Also, I would like to point this out as the reference, as this appears to be the most recent version showing gauge markings. Changes since this documentation either haven't been updated to show this field to be as missing and upgrade notes linked are broken on this page as well... As this is returning a 404: https://grafana.com/installation/upgrading/#upgrading-to-v6-0

Edited: to make more sense

**Comment by ryantxu** [comment]
Some of the language has changed.... what used to be "Stat" is now "Calculation" -- in yours you are showing "Last (not null)

Is your view always filled up all the way to maximum?  do other values show something different?   I wonder if this is related to https://github.com/grafana/grafana/issues/17939 

If you have different queries or select a different calculation, are you able to get a different result?

**Comment by zacharyhumphrey** [comment]
Hey @ryantxu, 

I get the same result no matter the config (Last (not null), Last, Mean, Calc, ECT), the color of the remaining storage changes as expected based on the thresholds, but the bar is always green and full... :(

Maybe this is related, but the gauge in #17939 does appear to be working as expected, but the text has issues during scaling and sizing. 

We did get it 'working' but only when we have a scale with a unit based on a percent of 100%. If we try to change from percent to the actual value available (ex. 3gb instead of 10%) on the gauge, the gauge stays full all of the time. 

![image](https://user-images.githubusercontent.com/49042255/72817107-d650c080-3c2e-11ea-9385-6d578c5eb1d1.png)

**Comment by torkelo** [comment]
the thresholds are in absolute values, so if you have bytes and you need a threshold for 20 GB you need to specify 20000000000
