### ISSUE TITLE
Alerting: Better control over alert image timezone 

### ISSUE THREAD

**Issue by orcunbaslak** [grafana/grafana#21630]
**What happened**: 
My data gets into influxdb as UTC. When I browser the dasboard via my browser; the graphs show the correct time but when Grafana sends an Alert to Telegram; rendered images are in UTC, not in UTC+3.

**What you expected to happen**:
The rendered images should be in UTC+3

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
My server is in UTC+3. 
My browser is in UTC+3. 
My data in Influxdb is in UTC.
My grafana docker image is in UTC.
I'm using Grafana Renderer Plugin (Chromium) via docker

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Influxdb 1.7.9
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome
- Grafana plugins: Grafana image renderer
- Others:

**Comment by torkelo** [comment]
Currently alerting images are rendered in backend server timezone, if your using docker and the docker image timezone is UTC, the images will be in UTC

**Comment by marefr** [comment]
@orcunbaslak since v1.0.8 of image renderer plugin you can specify default timezone using an environment variable, see https://github.com/grafana/grafana-image-renderer/#environment-variables

**Comment by marefr** [comment]
Try it out and let us know if it doesn't work and we'll consider reopen this.

**Comment by orcunbaslak** [comment]
> Try it out and let us know if it doesn't work and we'll consider reopen this.

My docker yaml file is like this.

`  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /tig/data/grafana:/var/lib/grafana
      - /tig/log/grafana:/var/log/grafana
      - /tig/conf/grafana/grafana.ini:/etc/grafana/grafana.ini
    links:
      - influxdb
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_RENDERER_PLUGIN_TZ: Europe/Istanbul
      GF_LOG_FILTERS: rendering:debug
    restart: always
  
  renderer:
    container_name: grafana_renderer
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      GF_RENDERER_PLUGIN_TZ: Europe/Istanbul`

yet I still have the issue.

**Comment by marefr** [comment]
@orcunbaslak Sorry thought you had renderer installed as a plugin. Please use the instruction for remote rendering using docker: https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables

**Comment by orcunbaslak** [comment]
> @orcunbaslak Sorry thought you had renderer installed as a plugin. Please use the instruction for remote rendering using docker: https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables

I have GF_RENDERER_PLUGIN_TZ: Europe/Istanbul in my grafana-renderer as environment variable. Am I missing something?

**Comment by marefr** [comment]
@orcunbaslak if you read link i referenced you should use `BROWSER_TZ=Europe/Istanbul` instead.

**Comment by Alik-watalik** [comment]
@marefr i have same issue on k8s, i have utc+6 in my browser in grafana ui, when alerts it sends image with utc, i change rendering_timezone = "Asia/Almaty", but it doesnt help
