### ISSUE TITLE
$__timeGroup doesn't respect dashboard timezone

### ISSUE THREAD

**Issue by aaron-lerner** [grafana/grafana#21632]
**What happened**:
When using `$__timeGroup` to bucket metrics, the timezone of the dashboard is not accounted for even though `$__timeFilter` is appropriately adjusted for the timezone. For example, trying to group metrics on a per-day basis, it buckets them based on the UTC date stored in the database:
<img width="1178" alt="Screen Shot 2020-01-21 at 12 37 19 AM" src="https://user-images.githubusercontent.com/15823984/72788241-628ac580-3be6-11ea-8dbb-ee961cead024.png">

**What you expected to happen**:
It should first convert times to the chosen timezone before bucketing:
<img width="1177" alt="Screen Shot 2020-01-21 at 12 38 05 AM" src="https://user-images.githubusercontent.com/15823984/72788285-76cec280-3be6-11ea-8cbb-ab43a5e70b53.png">

**How to reproduce it (as minimally and precisely as possible)**:
See queries above

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: PostgreSQL 11

**Comment by aknuds1** [comment]
Thanks for reporting this, but related issues have been posted before. At least #18120, so closing this one as a duplicate, sorry.
