### ISSUE TITLE
Show influxdb error messages from HTTP 200 responses

### ISSUE THREAD

**Issue by ulikl** [grafana/grafana#21647]
**What would you like to be added**:

InfluxDB api has some cases where the query call returns HTTP 200 without series, but it includes error messages in the results blocks.
These error messages should be shown as warning/error in the Grafana GUI.

E.g. due to query execution restrictions you can get the following results:
- Query timeout:  
```
{"results":[{"statement_id":0,"error":"query-timeout limit exceeded"}]}
```

- No result due to abort on query limits: e.g.   
```
{"results":[{"statement_id":0,"error":"max-select-buckets limit exceeded: (1081/200)"}]}
```

**Why is this needed**:

On these results the user needs to know, why the data is missing.
Currently this can only be seen in the query inspector via the response object.

Currently only errors with HTTP 400 from Influx are shown in the Grafana Gui.
Here the response message looks different. e.g. 
```
{"error":"error parsing query: found wh, expected ; at line 1, char 59"}
```
But HTTP 400 is only returned on syntax errors.

**Comment by aknuds1** [comment]
Thanks for reporting!
