### ISSUE TITLE
Adding a label to a timeseries duplicates the timeseries viewed on Grafana when using prometheus.

### ISSUE THREAD

**Issue by TonyBoyle** [grafana/grafana#21640]
**What happened**:
Using a prometheus database, I added an arbitrary label to a timeseries. When viewing a timeframe that covers the point at which the label was added, observed that two lines appeared rather than 1, across the entire panel. Hovering over the line showed that there were two lines, and viewing a legend that showed the values also showed this. The lines are complete duplicates of each other. If the point at which the label was added is not in the timeframe, there is only one line. Aggregating all of the lines on a graph (e.g. using sum( ... )) does not add the value twice. This confirms that this is a grafana issue rather than a prometheus issue.
Changing the null settings has no effect.

**What you expected to happen**:
Expected to see the first time series stop when the new label was added and the second time series start at that point. Maybe wouldn't be surprised if there was an overlap, but not for it to persist across the entirety of the graph.

**How to reproduce it (as minimally and precisely as possible)**:
Using a prometheus datasource, modify a timeseries to use a new label after a certain time. View the timeseries in grafana with a timeframe covering the change. Hover over any point on that graph using the mouse.

**Anything else we need to know?**:
This is easiest to see on a "graph" visualisation - however, it also appears on other visualisations and has more catastrophic effects (e.g. single-stat panels break because there are multiple time-series).

**Environment**:
- Grafana version: V6.4.2
- Data source type & version: Prometheus V2.14.0 
- OS Grafana is installed on: Centos
- User OS & Browser: Windows, Google Chrome
- Grafana plugins: N/A
- Others:

**Comment by aknuds1** [comment]
Thanks for reporting this!

**Comment by marefr** [comment]
@TonyBoyle could you please include query inspector request/response here? Also, can you run the same query in Prometheus UI showing graph and verify it only shows one point.

**Comment by torkelo** [comment]
Closing due to lack of updates
