### ISSUE TITLE
Migrate Table panel transformations to Transformers API

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21658]
Current Table panel supports data transformation which are one of the panel configuration options:

![image](https://user-images.githubusercontent.com/2376619/72876896-e54f7580-3cf7-11ea-9536-11b3feba1606.png)

Very soon we will need similar functionality in the [inspect drawer](https://github.com/grafana/grafana/issues/20710) which will allow simple transformations on the data frames:

![image](https://user-images.githubusercontent.com/2376619/72877234-cb626280-3cf8-11ea-8e35-4157c8e3d74b.png)

We need a [transformers](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/transformations/transformers.ts) that will enable transformations currently available in the Table panel

### TODOS:
- [ ] Consider https://github.com/grafana/grafana/pull/19727

**Comment by torkelo** [comment]
not sure this is part of the table panel in any way

**Comment by dprokop** [comment]
@torkelo updated description and title, happy to hear any more feedback about the requirements for the transformations that we want to support

**Comment by dprokop** [comment]
Closing in favour of https://github.com/grafana/grafana/issues/23424
