### ISSUE TITLE
PhantomJs: Prometheus panels can't render

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#21657]
**What happened**:
While investigating PhantomJs issue on master I came across `es-check` tool and could see that the import `LRUCache` breaks es5 compatibility. This means as soon as you try to render a Panel that uses a Prometheus datasource it will fail with a timeout.

**What you expected to happen**:
Panels with Prometheus datasource should render.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new dashboard
2. Create a new Panel using Test Data as datasource
3. Create a new Panel using Prometheus as datasource
4. Share Panel using Test Data as datasource and click on `Direct link rendered image` panel renders 🆗 
5. Share Panel using Prometheus as datasource and click on `Direct link rendered image` panel rendering times out 🚫  

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.beta-1
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Ok, I have found the offender which is 043bb59593cd12b41f609da734a24e34e5d1c936. The most suspicious and probable line is https://github.com/grafana/grafana/commit/043bb59593cd12b41f609da734a24e34e5d1c936#diff-a59431ca1f1f94cdb3ae176c50a585b2R82 which uses [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) which most probably is not available in PhantomJS
