### ISSUE TITLE
Playlist fails for dashboards with floating point gauges

### ISSUE THREAD

**Issue by HaikunWasTaken** [grafana/grafana#21661]
Hello, I have a massive issue with the playlist feature since Monday and I hope you can help me.

**What happened**:  I know this might sound weird, but I extended the gauges on my dashboards to show float numbers (two decimals) and since then the playlist crashes after the first or second iteration. Description of what exactly happens: The first iteration works perfectly fine, it shows dashboard 1 and dashboard 2 right after. Now it's supposed to show dashboard 1 again, but the screen is only showing "Fetching....". Sometimes it takes a while to fetch the information and dashboard 1 shows after many minutes. Other times I land on the login screen. When it manages to load Dashboard 1 for the second time, it usually crashes when loading dashboard 2 for the second time (lots of red error boxes and i land on the login screen again).

**What you expected to happen**: I have two dashboards in a playlist that are shown on a big screen in our office with a time interval of 5 minutes (I already changed that as well to test). This has worked ever since, but when I added decimals to the gauges as described below the playlist no longer worked (which might just be a coincidence as well).

**How to reproduce it (as minimally and precisely as possible)**: Queue the playlist in Kiosk mode + F11 to hide browser. I tested it on two different Win 10 Systems.

**Anything else we need to know?**: The problem was on v6.2.5 i then upgraded Grafana to v6.5.3 hoping it would resolve the problem. I query my information from an Azure MSSQL database.
This is what i query within my gauges:
```
SELECT
  (COUNT(Success) * 100.0/(SELECT COUNT(Success) from TestResults where testCaseName = 'tablename')) as value,
  'Failed' as metric
FROM
TestResults
where Success = 'true' AND testCaseName = 'tablename'
Group by Success
```
I simply changed "* 100" to "* 100.0" to get a float value. 

**Environment**:
- Grafana version: was v6.2.5 upgraded to v6.5.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu VM on Azure
- User OS & Browser: Win 10 & Firefox
- Grafana plugins: none
- Others:
#

**Comment by aknuds1** [comment]
Thanks for reporting this issue!

**Comment by HaikunWasTaken** [comment]
Is there a known solution for this issue?

**Comment by aknuds1** [comment]
I don't know of any.

**Comment by torkelo** [comment]
Can you include browser console logs? sounds like there is either a network error or browser javascript error

**Comment by HaikunWasTaken** [comment]
I'll have a look if there are errors thrown in the console in a minute. I am currently reverting the changes from monday to see if the playlist still crashes without float point gauges.

**Comment by torkelo** [comment]
Can you check network tab for any slow query? Sounds like a template variable query is slow and is preventing dashboard from loading

**Comment by HaikunWasTaken** [comment]
I will do that and keep you updated! Thanks for your help!

**Comment by HaikunWasTaken** [comment]
@torkelo okay so you were right, the requests take for ever. 
![grafik](https://user-images.githubusercontent.com/57464170/73166748-be79b080-40f6-11ea-82e7-8aff4aaa0e3f.png)
Any idea why that suddenly is the case? I wish I could provide more concrete info but I can't really send screenshots of code or queries (without censoring it) because of business secrets. If you need any specific info I'll see what I can do. As long as you don't require any company specific information I should be able to show you more detailed snippets.

**Comment by torkelo** [comment]
What datasource are those queries targeting? We have no other reports on queries taking longer in 6.5

What auth are you using for Grafana and for your datasource?

**Comment by HaikunWasTaken** [comment]
The queries target an Azure MSSQL Database that receives data from an Azure Web Service. My query calls a URL that triggers a backend function and retrieves the requested data from the database. Grafana itself I am hosting on an Azure Virtual Machine with HTTPS Authentication. I hope that answers your questions. If I misunderstood something please let me know.

**Comment by HaikunWasTaken** [comment]
It has been over a week now and my boss is not happy with the fact that we still cannot run a playlist. The dashboards work perfectly fine as long as they are not running in a playlist. As soon as I start the playlist I have issues. Sometimes after the first, sometimes it takes up to the third iteration until it gets stuck on the fetching screen followed by a logout. 
The very same dashboards had no issues two weeks ago. I would be happy if we could find a solution to this issue fairly soon.

Best Regards

**Comment by torkelo** [comment]
Can you show the network trace when you load the dashboard normally? Something is causing your queries to be very slow so they are not finished before the next dashboard loads which are causing further issues. 

We have no similar reports. The only thing I can think of is that you have some queries that get stuck and are causing issues when switching the dashboard. Try investigating network requests as you switch dashboard as well.

**Comment by HaikunWasTaken** [comment]
Okay, I did a minor change to two of my queries removing a % in a String of a LIKE condition hoping that it would make the query faster. While it didn't improve the query time by a lot, it appears as if the playlist is now working again on Firefox and Chrome on my office PC.
Now to next problem: while the playlist is working on my office PC with both browsers, Firefox now crashes on the Monitoring PC (the one that is supposed show the dashboards 24/7) shortly after starting the playlist. Chrome seems to be working perfectly fine. I already emptied the Firefox browser cache hoping to resolve the problem but that did not work. 
For now I am happy that it runs on Chrome, which browser I use does not matter as long as it works, but if someone has a clue why it doesn't work on Firefox please let me know. The error I get is something along the lines of "Firefox has stopped working, a problem caused the program to stop working correctly". Next thing I am going to try is update/downgrade Firefox to see if that fixes the issue.

**Comment by HaikunWasTaken** [comment]
Okay since nobody seems to have an idea why it works on Chrome and not on Firefox, I am going to close the issue. It runs on Chrome, that's not exactly what I wanted but better than nothing. 
Thanks for your help.
