### ISSUE TITLE
backendSrv: (datasource)request interface changed

### ISSUE THREAD

**Issue by Maddin-619** [grafana/grafana#21662]
**What happened**:
With #20999 there where some changes in the datasourceRequest interface. Since that a successfull request returned the whole response (statuscode, header, loctaion, etc.). Now only the data field.
https://github.com/johntdyer/grafana/commit/782074ac0e2fa6f7fdfe51cecb654bd33dbeb512#diff-ee2adfbba2f0547ca6b2c9bc2fde339aR216

**What you expected to happen**:
Many plugins where developed with the old interface using the statuscode and header. For example  parsing the location out of the header in a post request response.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Master 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
@Maddin-619 great that you found this!. Working on a PR that will be merged soon.
