### ISSUE TITLE
Toolkit missing error message when linting fails

### ISSUE THREAD

**Issue by scottlepp** [grafana/grafana#21675]
In 6.5 a message of "please run yarn dev" was provided.  Now just a stack trace.

https://circleci.com/gh/grafana/plugin-ci/717

![image](https://user-images.githubusercontent.com/6108819/72935514-7d1e8500-3d33-11ea-83c8-ab53faea58f8.png)

**Comment by aknuds1** [comment]
Thanks for reporting!

**Comment by dprokop** [comment]
Fixed with https://github.com/grafana/grafana/pull/21849 . Available in the `canary` version, soon to be released as stable with 6.6.1
