### ISSUE TITLE
Alert notifications not working if any datasource in Alert config is down

### ISSUE THREAD

**Issue by marzlarz** [grafana/grafana#21674]
**What happened**:
We noticed lately that when any of our many prometheus data sources are down for patching, that notifications are essentially broken for all data sources used by that particular alert. Event data sent to Webhook ( ALERTA ) is missing key fields

**What you expected to happen**:
DC1 is down for patching, but we should still get alerts in DC2 

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup Graph with 2 data sources ( DC1 / DC2 )
2. Setup Alert on that Graph for both data sources ( last() DC1 > 10   OR  DC2 > 10 )
3. Either shutdown DC1 Prometheus or break the data source config in Grafana

Error from Alert:

tsdb.HandleRequest() error Get http://prometheus-DC1:9090/api/v1/query_range? : dial tcp 10.10.10.10:9090: connect: connection refused"

Data sent to ALERTA from Grafana when data source is down:
{
  "evalMatches": [],
  "message": "Error Message",
  "ruleId": 129,
  "ruleName": "Response Time Check",
  "ruleUrl": "......",
  "state": "alerting",
  "title": "[Alerting] Response Time Check"
}

**Anything else we need to know?**:
Alerta Documentation: https://docs.alerta.io/en/latest/api/alert.html 

The "event" and "resource" fields are mandatory for processing an Alert. Those fields are not sent to the webhook if the datasource is down. 

**Environment**:
- Grafana version:  5.3.3 / 6.3.5 
- Data source type & version:  Prometheus 2.1.0
- OS Grafana is installed on:  CentOS 7.7
- User OS & Browser:  MacOSX / FireFox 72 ,  Fedora 29 / FireFox 62
- Grafana plugins:  Default

**Comment by marefr** [comment]
There's no "event" and "resource" properties sent with the webhook notifier, see https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/services/alerting/notifiers/webhook.go#L78-L108

Closing this, but we consider reopen this if you provide more information that shows that this is a problem with Grafana.
