### ISSUE TITLE
Y axis defaults to bytes instead of bps

### ISSUE THREAD

**Issue by jl98800** [grafana/grafana#21670]
Hi,

When using cloudwatch as a datasource for my query of AWS/NATGateway and the following metrics

BytesInFromSource
BytesInFromDestination
BytesOutFromSource
BytesOutFromDestination

Visualization defaults to Bytes for the Y axis and it can't be changed via the UI or JSON to the data rate of bps.  Please help.

Grafana v6.4.4 (commit: 092e514)

**Comment by sunker** [comment]
Thanks for reporting the @jl98800. In Grafana 6.5 that was released in November last year, we switched from CloudWatch GMS api to GMD api. The GMD api doesn't return data types, so the auto data type detection in the graph does not exist anymore, and I'm afraid we won't be able to do a patch release for 6.4
