### ISSUE TITLE
add "top-n" capabilities

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2167]
when dealing with a lot of metrics (esp. hostname=*,  1000 servers), it'd be nice to be able to say "give me only the top-n entries". 

the graph with 1000 lines below:  (It's crazy~)
![selection_007](https://cloud.githubusercontent.com/assets/8777671/8154963/f7875786-1371-11e5-8a12-fb1aabc000ba.png)

**Comment by nopzor1200** [comment]
Hi @godfreyhe, yeah that graph does look quite crazy :)

Depending on what kind of datasource you're using, it may be possible to limit and sort as part of your query.

For example, in graphite you can something like limit(10) to limit to 10 servers. You can also use something like sortbyTotal() right before that to sort the servers by the sum of datapoint values for the time range that you specify.

Hope this helps

**Comment by godfreyhe** [comment]
hi @nopzor1200, 
my datasource is opentsdb which is not support sortby().

thank you~

**Comment by torkelo** [comment]
@godfreyhe features to limit and sort series (like top 10 series, based on average or max) is supported by graphite and in a limited sense by influx. I suggest you open a PR with OpenTSDB to add this feature into their query api.

**Comment by praveev** [comment]
@torkelo i can now see that opentsdb has added support for graphite style functions in 2.3. http://opentsdb.net/docs/build/html/api_http/query/gexp.html i am also looking to solve this exact use case when using grafana with opentsdb data source

**Comment by RickyLau** [comment]
which version, grafana will support opentsdb gexp function ?

**Comment by qgxiaozhan** [comment]
I think we should open this issure

**Comment by kahing** [comment]
I believe gexp is tracked by https://github.com/grafana/grafana/issues/3805
