### ISSUE TITLE
Allow updating of template variables from within a panel, e.g. clicking a table cell updates a variable

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#21673]
**What would you like to be added**:

I'd like one panel's data to be used to update template variables by user interaction. E.g.: Instead of table cells just being links, allow them to update template variables and trigger redrawing of other panels. Ideally leaving the clicked panel untouched, unless it uses the updated variable.

The closest I can get today is opening a separate dashboard, which isn't really the same.

I suppose #9556 would be a hacky way to achieve parts of this, and if that worked, I'd use it.

**Why is this needed**:

When a user is going through a large amount of data, we need to be able to provide a high-level overview, typically in the form of a table, and provide quick drill-downs *without navigating away from the overview-dashboard*. Use cases: 

- Link utilization - a table shows peak utilization last 1h, 24h, 7d, 31d - click for drill down. Can easily result in 20-30 drill downs.
- Site conditions: Table shows site temperatures across 100s of sites, click for at-a-glance drill down of both location and temperature. Can easily lead to navigating back and forth to compare environmental conditions on sites located in similar regions. 
- Customer-centric overview: Query links relevant for a customer across the network, show metadata, show traffic stats on interaction. Can easily be dozens of locations and hundreds of links, and it's useful to be able to quickly navigate between interfaces to understand traffic flow.
- etc etc

Obviously we can solve "all" of this by having the user just update the variables themselfs, but that's not very intuitive and not ideal.

Having it work for just table panels would mostly do the trick for me.

**Comment by aknuds1** [comment]
Thanks for your request, we'll take it under consideration.

**Comment by torkelo** [comment]
you will be able to do this in v6.6 using cell links, var syntax `var-<varname>=$__cell`

**Comment by KristianLyng** [comment]
I know this is closed, but this is pretty great. Installed beta in dev and so far I can't find any huge flaws :D

**Comment by aknuds1** [comment]
@KristianLyng Great! :)
