### ISSUE TITLE
$__range is excessively rounded (Prometheus)

### ISSUE THREAD

**Issue by bmerry** [grafana/grafana#21689]
**What happened**:

A Prometheus instant query using `[$__range]` on a time range of about 33 hours reported only over 24 hours. The query inspector shows that it was substituting `1d`.

**What you expected to happen**:

`$__range` should expand to the time range selected, to the nearest second.

**How to reproduce it (as minimally and precisely as possible)**:

In a Grafana connected to a Prometheus instance, create a singlestat with a range query using `$__range` e.g. `sum(increase(up[$__range]))`. Set the time range to cover a bit more than a day e.g. 33 hours. Look at the query in the query inspector. It will show a `1d` range.

**Anything else we need to know?**:

This was previously reported at https://community.grafana.com/t/solved-this-week-timerange-strange-behavior-range-with-slow-counter/12782 and in #12882, and was "fixed" by providing a new `$__range_s` which can be used as `${__range_s}s`. While it's nice to have the workaround, `$__range` is still broken (in the worst case, covering only *half* the selected time range).

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Prometheus 2.12
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 18.04, Firefox 72.0.1
- Grafana plugins:
- Others:

**Comment by bmerry** [comment]
Incidentally, the examples for using Prometheus include one that says:

> Populate a variable with the instances having a certain state over the time range shown in the dashboard, using the more precise `$__range_s`

which could be cleaned up if `$__range` is made as precise.

**Comment by aocenas** [comment]
cc @dprokop @torkelo you probably have context for the 2 variables.

**Comment by torkelo** [comment]
no, not really. Not sure exactly the purpose and how this variable should work, unique to Prometheus

**Comment by bmerry** [comment]
I can make a PR showing what I think should happen, but I'm not a Javascript developer and don't know my way around the testing framework so will probably need someone to help with a regression test.

**Comment by aknuds1** [comment]
Moved this issue to the Platform board, after discussing with @aocenas. Feel free to move somewhere else if it's a better fit :)

**Comment by bmerry** [comment]
I made a PR (#21722), but I see it can't be accepted until I agree to the CLA. Since I'm doing this on work time, that means lawyers get involved, which could take months (hopefully quicker now that this is the second time I'm asking for CLA approval). If someone else wants to just do the fix themselves, I believe the change needed is to replace the [current calculation](https://github.com/grafana/grafana/blob/b28eac26263abb24bed18d4de007eb7bdb894dfd/public/app/plugins/datasource/prometheus/datasource.ts#L519) of `__range` by taking the value of `__range_s` and appending an 's' to it.

**Comment by aknuds1** [comment]
Thanks @bmerry, trying to get some feedback on your PR.

**Comment by bmerry** [comment]
> Since I'm doing this on work time, that means lawyers get involved, which could take months (hopefully quicker now that this is the second time I'm asking for CLA approval).

Good news! My manager said we don't need to get lawyers involved, so I've signed the CLA.
