### ISSUE TITLE
Prometheus POST queries to grafana backend are truncated

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#21688]
**What happened**:
We updated grafana to 6.7.0-e861b821pre

our dashboards don't work at all:

![allerr](https://user-images.githubusercontent.com/291750/72980554-1654a680-3ddb-11ea-8c8d-669192f17b9a.png)

**What you expected to happen**:
It works

**How to reproduce it (as minimally and precisely as possible)**:

take grafana master

add a valid prometheus backend with POST method

click save

**Environment**:
- Grafana version: 6.7.0-e861b821pre from the rpm
- Data source type & version: prometheus

**Comment by dprokop** [comment]
@roidelapluie can you provide us with console output? Have you tried 6.6.0-beta.1 to see if this problem exists there?

**Comment by roidelapluie** [comment]
queries to prometheus are truncated
![allerr](https://user-images.githubusercontent.com/291750/72981785-ed81e080-3ddd-11ea-9674-faf765fc2b68.png)

**Comment by roidelapluie** [comment]
reproduced on 2 systems totally different, one centos with rpm and one exherbo with tar.gz

**Comment by roidelapluie** [comment]
6.6. beta works

**Comment by roidelapluie** [comment]
90338c13 - not ok

**Comment by roidelapluie** [comment]
Grafana v6.6.0-pre (7cbf3d8dab) - ok

**Comment by roidelapluie** [comment]
The first  commit with this issue is cf2cc71393 according to my bisect.

cc @kaydelaney @hugohaggmark

**Comment by hugohaggmark** [comment]
@roidelapluie thanks for reporting this, can you give an example of such a range query? I've a pretty comprehensive Prometheus dashboard that works fine using `rate queries` not sure that is the same as you're using. Sorry for my low-level knowledge about prom queries.

**Comment by roidelapluie** [comment]
The default prometheus v2 dashboard

**Comment by hugohaggmark** [comment]
> The default prometheus v2 dashboard

Thank you, do you have a link?

**Comment by roidelapluie** [comment]
In your grafana, go to data source prometheus, tab dashboard, click import

**Comment by hugohaggmark** [comment]
Thank you so much for clarifying all this, I'm looking into this asap.

**Comment by 3llen** [comment]
Hi I still have this error while GET range_query, was that fixed?
