### ISSUE TITLE
Possibility to use Prometheus Explorer by non Admin users

### ISSUE THREAD

**Issue by nkondratyk** [grafana/grafana#21683]
**What would you like to be added**:
Currently only Admin users can use Prometheus Explorer. 
It will be great if read only users can also use this great feature.

**Why is this needed**:
In our company we have more than 1000 developers which are using Grafana and we can`t provide admin access for all of them.

**Comment by torkelo** [comment]
Prometheus Explorer? what is that? 

You mean the Explore mode (compass icon)? You do not need to be admin for that, only Editor. 

You can make Viewers also be able to access Explore if you enable the option "viewers can edit" in the ini file, this setting will allow viewers to make transient edits in dashboards as well (make changes but not save them)

**Comment by nkondratyk** [comment]
It works. Thank you!
