### ISSUE TITLE
Getting template variables for dashboard Id and panel ID while using data links

### ISSUE THREAD

**Issue by RuchaBapat** [grafana/grafana#21682]
Hello,
We are using data links to carry the data from the panel of the one dashboard and put it in the filters of another dashboard.

We create URL for this and specify the dashboard id.
Is it possible to make this URL expandable in a sense that we can use template variables additional to host URL.

Consider this situation-
We have links from dashboard1 to dashboard2, at the moment we hard code the full destination URL of dashboard2 in dashboard1’s configuration.
This link breaks when we:
1) rename dashboard2 as it URI path changes
2) migrate dashboard configuration between grafana deploments as hostname changes
What would solve this if there would be a template variable that expands into the URL
e.g. ${dashboardURL:<dashboardId><panelId>} expands into the full url of that dashboard
With this we could use this to construct the url.

Is is already available in current version? If not can you please add this as a feature request?
It will be very useful to create the data links in generalized manner, and if the name of the dashboard is changed or url changes, it wont break. We look forward for your response.

Thanks.

**Comment by marefr** [comment]
Linking to dashboard including the unique `uid` should solve the problem of uri's changing when renaming a dashboard. In `http://localhost:3000/d/5SdHCadmz/panel-tests-graph` the `uid` part is `5SdHCadmz` and will be stable even if you change the title of the dashboard. See [docs](https://grafana.com/docs/grafana/latest/http_api/dashboard/#identifier-id-vs-unique-identifier-uid) for more information. I'm closing this since I think it works as expected.

**Comment by RuchaBapat** [comment]
Thanks for your reply.
We understand about dashboard id or name, is it also possible for panel id?
does panel id stay the same? Also is it possible to stcik panel id just after dashboard id/name and not after variables in the URL?

**Comment by marefr** [comment]
@RuchaBapat panel id should stay the same as long as you don't change it and or use repeated panels since that could potentially change the panel ids.

You should be able to use url like http://localhost:3000/d/5SdHCadmz/?orgId=1&fullscreen&panelId=5 to link to a panel in fullscreen mode.

**Comment by RuchaBapat** [comment]
It feels then it is not maintainable when we use many datalinks and if we change something regarding panel, we need to change the URL every time. Can you consider this as a feature request to make dashboard id-panel id stable too?

**Comment by marefr** [comment]
@RuchaBapat think this is the feature request issue #11334
