### ISSUE TITLE
gui breaks metric statement when using "Series as Parameter"

### ISSUE THREAD

**Issue by HerrBerg** [grafana/grafana#2169]
Grafana version: debian package `grafana_2.1.0-pre1` build from today `2015-06-15 `

I'd like to add a movingAverage as second graph and I encounter two problems with the gui when referencing the first graph(#A) (using graphite backend)

problem 1:
after entering `#A` in the `select metric` field, the `select metric` extends the `#A` so it results in
`#A.select metric`

after fixing the metric and manually adding the movingAverage function I have
`movingAverage(#A, '5min')` and this works great.

problem 2:
It is not possible to edit this statement without using the pencil icon to manually edit the statement.
E.g. adding the `alias` function results in the series parameter being removed:
`alias(movingAverage('5min'), 'myalias')`

**Comment by torkelo** [comment]
movingAverage should be added directly to the query , (it is not configured to support series references).

And series references are only supported as function arguments  (for function like asPercent, divideSeries).
