### ISSUE TITLE
Self referencing cell links behave strange when template variables are left out

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#21693]
**What happened**:

Testing cell-links, re #9259. 

Two issues, one I can reproduce in a fresh dashboard, one I can't, both similar. The former first:

- Created a dashboard with two panels and two template variables
- Variable 1: parent_ae_name - provided from cell link 
- Variable 2: ifs - computed through parent_ae_name, want default to be "All"
- Panel 1: Table of interface aggregates, with each aggregate having a link to the present dasbhoard, setting var-parent_ae_name=${__cell}
- Panel 2: Uses a select from $ifs to provide stats by interface

A workaround is to always provide var-ifs=All.

Click the cell link results in a blank "var-ifs=", which simply doesn't work. But when the refresh hits, var-ifs will be set to All, and stuff starts working.

I'm assuming this is somehow related to how often $ifs is set to update. I had it to on time range change first, but even at "never", there's just not a consistent behavior here.

Second related, possibly the same issue.

Similar setup to the above, but this was on an existing, considerably more complex dashboard. When I clicked the interface, var-ifs=All was set, as desired, and everything Just Worked. But if I clicked the same link twice in a row, var-ifs got set to blank again - but again, it would recover if the dashboard refreshed. 

Third, possibly worse issue: Loop.

During my testing, I've also managed to make the dashboard enter a refresh loop, with var-ifs= switching between All and blank between each update. Each update would be rapid, not related to update frequency, though I suspect there's some timing issue related to the update frequency of the dashboard.

**What you expected to happen**:

1. No refresh-loops :D
2. Omitting var-ifs= (or other template variables) in the link should give the same result regardless of how many times I click the same url or if I hit refresh.

Ideally I'd like to be able to have cell links where I only need to provide the bare minimum of variables, but it's not a big problem if the rule is that all template variables must be provided. It just means a bit more hassle if we add more variables in the future.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a dashboard with: Two hidden template variables, one should use the result of the other
- E.g. Variable 1: foo, variable 2: bar. Bar is set to "select z from blatti where vfoo = foo". 3. Include All option.
- Create a panel with a table, use cell link to update the first variable
- Create a panel that uses the value of the second variable
- Click the link - should give a borken second panel due to an empty variable
- Hit the refresh-button or wait for auto-refresh. It now works?

**Anything else we need to know?**:

I suppose this might be completely unrelated to cell-links, but that's what's triggering it.

**Environment**:
- Grafana version: 6.6-beta1
- Data source type & version: influx, version seems irrelevant
- OS Grafana is installed on: CentOS, with beta1 RPMs
- User OS & Browser: chromium, debian stable
- Grafana plugins: flux data source - not used in the dashboard, and iframe
- Others:

**Comment by aknuds1** [comment]
Thanks for testing and reporting your findings!

**Comment by torkelo** [comment]
Can you try this setup in 7.1. we have done some big changes to the templating system and I think this will work better, 

But have to wait for https://github.com/grafana/grafana/pull/25192 to be merged
