### ISSUE TITLE
UpdateAnnotation should update field Data too

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#21696]
**What would you like to be added**:
file: grafana/pkg/api/annotations.go
Function PostAnnotation creates new annotation and allows you to set field Data from cmd.Data.
Function UpdateAnnotation do not read this field from cmd. 
Add please the string "Data: cmd.Data" to function UpdateAnnotation (line:164) to have possibilty to update data field in the database

**Why is this needed**:
We store some additional information in the data field while working with annotations. And we want to have possibility to update this information. At present we have to delete and recreate annotation to update data field.

**Comment by aknuds1** [comment]
Thanks for making this request, we'll look into it.

**Comment by marefr** [comment]
Data field is set when creating (post) an annotation: 
https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/api/annotations.go#L73

Data field need to be set when updating (update) an annotation:
https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/api/annotations.go#L157-L165

Need to add data field to this command:
https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/api/dtos/annotations.go#L15

Bonus:
Support updating data fiels when patching (path) an annotations:
https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/api/annotations.go#L189-L196
https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/api/dtos/annotations.go#L23

**Comment by leandro-deveikis** [comment]
@papagian @yangkb09 Are you working on this? If not, I could try to fix it as my first issue :)

**Comment by yangkb09** [comment]
@leandro-deveikis I'm not working on it! I removed my assignment - it's all yours :)
