### ISSUE TITLE
Should not set WWW-Authenticate header while X-Requested-With: XMLHttpRequest set

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#21697]
There is an agreement if server received 'X-Requested-With: XMLHttpRequest' header it shound not send back WWW-Authenticate header

**What happened**:
I send authentification request with header 'X-Requested-With: XMLHttpRequest' and receive 401 status with WWW-Authenticate header set

**What you expected to happen**:
No WWW-Authenticate header set

**How to reproduce it (as minimally and precisely as possible)**:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Basic Auth Logout Helper</title>
</head>
<body>
<script type="text/javascript">
      // Google Chrome & others
      fetch("your_grafana_server.com", {
        credentials: 'include',
        headers: {
          'Authorization': 'Basic ' + btoa('none:none'),
          'X-Requested-With': 'XMLHttpRequest'
        }
      })
    }
  }
</script>
</body>
</html>
```
Open it by google chrome browser and look at response headers in the developer tools

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04, Google Chrome 79.0.3945.88
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
I think this was fixed in #28962 and included in Grafana v7.4. I will close this. Let us know if you believe this still works as expected and we'll consider reopen the issue.
