### ISSUE TITLE
SQL datasources: Query builder is incorrectly displaying un-interpolated variables

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#21691]
**What happened**:
When user wants to get to Explore from dashboard panel, `interpolateVariablesInQueries` is used and it correctly interpolates variable. You can see correct variables in SQL Editor, but the query builder is incorrectly displaying un-interpolated version. When you open Editor and run query, correct results are displayed.
![image](https://user-images.githubusercontent.com/30407135/72990281-2d51c380-3df0-11ea-97ed-5e33c8ce0449.png)
![image](https://user-images.githubusercontent.com/30407135/72990317-3e023980-3df0-11ea-95ab-550e9417fab5.png)

**What you expected to happen**:
Have correctly interpolated variables also in  query builder.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Create panel that visualises data from SQL datasource
2. Create template variables and use them in query
3. Create repeated panels
4. Open one of the repeated panels in Explore
5. You see the bug - template variables weren't correctly interpolated
7. Open Edit SQL - you will see correctly interpolated query
 
![ezgif com-video-to-gif (22)](https://user-images.githubusercontent.com/30407135/72992118-8111dc00-3df3-11ea-9cd2-f909fbee25c5.gif)

**Environment**:
- Grafana version: current master
- Data source type & version: SQL datasources (tested with mysql, mssql, postgres)

**Comment by hugohaggmark** [comment]
@ivanahuckova do you think this issue belongs in the observability squad instead?

**Comment by hugohaggmark** [comment]
Moving this to @grafana/observability-squad after a chat with @ivanahuckova, please move it back if you think it's not a perfect fit.
