### ISSUE TITLE
Make it easier to select Dashboard

### ISSUE THREAD

**Issue by Gromph** [grafana/grafana#217]
Now that I have a few dashboards setup, I'd like to be able to quickly cycle through them to check up on everything. I'd like to see 2 things.

1. Show a popup list of Dashboards when clicking on the name of the Dashboard in the upper left hand corner. This would be just like clicking on a filter

2. Add a left/right arrow button next to the Dashboard name, clicking them would go to the next/previous dashboard in the list.   That way the user could sit back and click one button to cycle through dashboards.

**Comment by torkelo** [comment]
solved by dashboard playlist or dashboard links feature
