### ISSUE TITLE
Remove image_path from Slack alert if empty

### ISSUE THREAD

**Issue by Niki2k1** [grafana/grafana#21709]
**What would you like to be added**:
I want to have the _image_path_ from the slack webhook body json removed if the **include image** option is off or the image is empty

Another option would be to add a own Rocketchat Webhook Type

**Why is this needed**:
I am using the Slack webhook type with rocketchat as they are basically the same. With a new version from Rocketchat there is a new Link validation. As an empty string is not a valid Link its not sending the alert. If you remove the empty _image_path_ from the body JSON it will work again. 

I tested the alerting directly with Slack and its still working even if the _image_path_ is removed.

**Comment by aknuds1** [comment]
Thanks for reporting this, we'll see what we can do!

**Comment by aknuds1** [comment]
Having tested, I think you must mean `image_url`? There's no field `image_url` in the Slack message payload, but rather one called `image_url` instead.
