### ISSUE TITLE
Panel Issue the panel don't show anything and have i failure message!

### ISSUE THREAD

**Issue by pwSteve** [grafana/grafana#21711]
I have my own Graph Panel based on an older version of Grafana Graph Panel. I added many other features. It was all fine, but now i become this issue:

WEBPACK_IMPORTED_MODULE_19_grafana_app_core_utils_kbn_default.a.valueFormats[format] is not a function

I see this notification in Grafana itself in the top left corner of the panel. In the console, i don't have any failure messages.

The panel is in Angular.
The Grafana Version is 6.5.1

In code i have this:
`
function configureAxisMode(axis, format) {
      axis.tickFormatter = function (val, axis) {
          return kbn.valueFormats[format](val, axis.tickDecimals, axis.scaledDecimals);
        };
      }`

I hope this can help.

**Comment by aknuds1** [comment]
Can you please use our standard issue template?

**Comment by pwSteve** [comment]
It's good, i found the issue, but for next time i will use the template.
