### ISSUE TITLE
Set dashboard variable on user login

### ISSUE THREAD

**Issue by avekrivoy** [grafana/grafana#21718]
How can I set dashboard variable dynamically depending on user that is logged in? Assume that it could be done with reverse proxy. I tried to override query parameters with nginx, but this didn't help. Probably because this logic is being executed in browser.
Say I've got variable value, that I need, how can I pass it to grafana? So when user requests https://my.grafana.xyz/dashboard he gets dashboard with injected variable https://my.grafana.xyz/dashboard?var-my_value=TEST

**Comment by aknuds1** [comment]
Please use our [community](https://community.grafana.com/) for support, our issue tracker is for reporting bugs and making feature requests. Thanks!
