### ISSUE TITLE
hyphens in drilldown link fail

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#2171]
In a drilldown, if I make a reference to a dashboard with a hypen in the name such as:

my-dashboard

This gets turned into "mydashboard" and the url of course fails to resolve properly.

By mucking about I found I could instead enter "my dashboard", and the spaces get changed into hyphens.

I tested this on singlestat panels, but assume it's the same code for all types.

**Comment by torkelo** [comment]
should be fixed in https://github.com/grafana/grafana/commit/98a07eff8117495ee219f5d7c9ae3362bbdc776f
