### ISSUE TITLE
Completed /robots.txt 404 Not Found in 554.859µs

### ISSUE THREAD

**Issue by damm** [grafana/grafana#2173]
It seems we don't have a robots.txt supplied by grafana; as I suspect more people are using nginx to proxy_pass back to grafana (or letting grafana run on port 80).

http://www.robotstxt.org/robotstxt.html

As we have search engines crawling us a bit more now.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/2174
