### ISSUE TITLE
Deleted threshold keeps coming back.

### ISSUE THREAD

**Issue by tmroberts-tableau** [grafana/grafana#21732]
**What happened**:
While creating a new panel on a Zabbix dashboard, a threshold keeps getting created, that 1) has no relation to the trigger threshold in Zabbix and 2) can't be deleted.  When I delete the threshold, change the threshold (value, color or any other parameter) either via the GUI or via the JSON (and save it) the original threshold keeps coming back as if I did nothing.

**What you expected to happen**:
I would have expected that a deleted threshold stays deleted.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce this, I would set up a Zabbix dashboard to monitor Zabbix Proxy server processes (by %) and filter the query down to a single process.  I was looking at housekeeper processes.  The threshold should appear on its own.  Delete it and/or change it.  Wait 5-10 seconds and it will come back.

**Anything else we need to know?**:
I have seen this is previous versions of Grafana/Zabbix Plug-in as well, but not just the Zabbix plug-in.

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Zabbix v 4.4
- OS Grafana is installed on: CentOS 7.7
- User OS & Browser: Mac OS and Chrome
- Grafana plugins: Zabbix 

Plugin v3.5.10
- Others:

**Comment by tmroberts-tableau** [comment]
as a follow up, even adding a completely different (and manually added) threshold and deleting the other, doesn't change the fact that it keeps coming back.

**Comment by torkelo** [comment]
please open this issue in the zabbix grafana plugin github repo
