### ISSUE TITLE
Pull-right by default in DashLinks component

### ISSUE THREAD

**Issue by lunaticusgreen** [grafana/grafana#21747]
**What would you like to be added**:
Pull-right by default for all dropdown menus in DashLinks component

**Why is this needed**:
Right now `pull-right` class applies only for the last element in [list](https://github.com/grafana/grafana/blob/ed140346a767d5727dcc8a8172af5aa74dfd9234/public/app/features/dashboard/components/DashLinks/DashLinksContainerCtrl.ts#L86):
<img width="365" alt="image" src="https://user-images.githubusercontent.com/9621964/73134175-a6495900-4044-11ea-8db3-751ae6f6a4fd.png">
But there may be some display issues, when text in not last element submenu is too long:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/9621964/73134189-c8db7200-4044-11ea-844a-1c1451e4c20e.png">

It would be great if you could consider this changes

**Comment by atymchuk** [comment]
When merging #22233 the [following](https://github.com/grafana/grafana/blob/8b067a5fe016d6e14a46907469a1caf3df150de6/public/app/features/dashboard/components/DashLinks/DashLinksContainerCtrl.ts#L86) should have been removed from the same component: 
```
// fix for menus on the far right
if (link.asDropdown && scope.$last) {
  elem.find('.dropdown-menu').addClass('pull-right');
}
```
The class `pull-right` is already added on [L44](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/DashLinks/DashLinksContainerCtrl.ts#L44)
