### ISSUE TITLE
Influxdb: measurement picker does not work

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#21744]
**What happened**:
When trying to search for logs with elastic the measurement picker does not fill in field into the request:

<img width="590" alt="Screenshot 2020-01-25 at 14 29 27" src="https://user-images.githubusercontent.com/1014802/73122667-b0f1e880-3f87-11ea-8b5b-d0d8d5519d40.png">

This creates request like this `SELECT "undefined" FROM "logs" WHERE time >= now() - 1h LIMIT 1000` and no logs in the response.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This seems to be already existing issue in 6.5.3, still persists in 6.6 beta. In master there are some underlying issues making it a bit more broken, but when fixed with https://github.com/grafana/grafana/pull/21743 we will get to this same issue still.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
@aocenas something we want to patch for 6.6 or include in 6.7?

**Comment by aocenas** [comment]
@marefr sorry did not have a patch for this in time for 6.6 so either 6.6.1 or 6.7.

**Comment by marefr** [comment]
6.6.1 if possible, but if it's dependent on a lot of other changes 6.7
