### ISSUE TITLE
Installing Cypress could not be downloaded.

### ISSUE THREAD

**Issue by alevchuk** [grafana/grafana#21746]
**What happened**:
On ed140346a767d5727dcc8a8172af5aa74dfd9234

URL: https://download.cypress.io/desktop/3.7.0?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

yarn install --pure-lockfile

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
@alevchuk What are you trying to do here, building Grafana from source on a 32-bit processors architecture?

**Comment by marefr** [comment]
Ref #21739

**Comment by marefr** [comment]
Related to this? https://github.com/cypress-io/cypress/issues/1554

**Comment by alevchuk** [comment]
Resolved. Thanks!! It was because I was trying to build in a 32-bit environment. Switching to a 64-bit os environment fixed it: https://raspberrypi.stackexchange.com/questions/100926/64-bit-os-on-raspberry-pi-4/101802#101802
