### ISSUE TITLE
Alias doesn't render value of Multi-value with CloudWatch datasource

### ISSUE THREAD

**Issue by tamasar** [grafana/grafana#21750]
**What happened**:
It does not expand Alias ​​values ​​in settings that allow multiple variables to be selected using CloudWatch datasource.
For example, Multi-value=on, Include All option=on here:
![スクリーンショット 2020-01-24 17 08 15](https://user-images.githubusercontent.com/60331919/73145405-ca627400-40f0-11ea-8d89-635c766329d7.png)
![スクリーンショット 2020-01-24 17 08 26](https://user-images.githubusercontent.com/60331919/73145413-d0f0eb80-40f0-11ea-9568-415594b85504.png)

But the value is not expanded.
![スクリーンショット 2020-01-24 17 09 08](https://user-images.githubusercontent.com/60331919/73145417-d4847280-40f0-11ea-9bfb-77ab0144c6bc.png)

**What you expected to happen**:
"InstanceId" are render instead of "Tags.Name"

**How to reproduce it (as minimally and precisely as possible)**:
1. Prepare 2 or more AWS EC2 to display EC2 metrics with AWS CloudWatch
2. Build a Grafana server (AWS EC2、Docker)
3. Assign AWS CloudWatch reference permission to the Grafana server
4. Create a new Dashboard in Grafana
5. Define 2 variables in the new Dashboard:
- Variable for obtaining EC2 tags
- Variable for matching EC2 tags to InstanceIDs
6. Create a graph that references the 2 variables.
For example:

Query setting:
- Region=<Region where EC2 is>
- Namespace=AWS/EC2
- Metric Name=CPUUtilization
- Stats=Average
- Dimensions= InstanceId=$instance_ids
- Alias={{name}}

Visualization Setting
- Show=on
- AsTable=on
- To the right=on
7. Select multiple EC2 tags in the Dashboard list and check the graph drawing.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.0-pre (25e2f1c2dd)
- Data source type & version: CloudWatch
- OS Grafana is installed on: AWS EC2, Docker(grafana/grafana)
- User OS & Browser: 18.04.3 LTS (Bionic Beaver)
- Grafana plugins: n/a
- Others: n/a

**Comment by shavonn** [comment]
@tamasar we have determined that this is not actually a bug. If you take a look at the help tip on the Alias field, it has what variables can be used there. If you were to enter `{{InstanceId}}`, it would work because it is a dimension in your example. However, `{{name}}` is not so this does not work.

**Comment by tamasar** [comment]
Thank you for your support.
I was understand that it is not a bug.
I think {{name}} could be useful, so I’m glad to add it as a new feature next time.

**Comment by akaeme** [comment]
Im trying to apply this to RDS Roles instances using {{Role}} and * on the role field, but grafana renders the metric name instead of the db role(Writer/Reader).
![image](https://user-images.githubusercontent.com/19346976/76349310-a7d39580-6301-11ea-9630-3b4a5066740c.png)
