### ISSUE TITLE
iOS Login Button unresponsive again

### ISSUE THREAD

**Issue by volschin** [grafana/grafana#21751]
**What happened**:
Same behaviour as in #12133 on my iPad using iOS 13.3 with Chrome and grafana 6.4.3 from official docker Image.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Filed again 5 days ago https://bugs.chromium.org/p/chromium/issues/detail?id=1051132

**Comment by marefr** [comment]
@hugohaggmark so I guess this issue shouldn't be part of 6.6.2, rather 6.7 or something?

**Comment by hugohaggmark** [comment]
Not sure @marefr

**Comment by marefr** [comment]
@hugohaggmark but do you think we can do something to fix this without the referenced bug being fixed?

**Comment by hugohaggmark** [comment]
You're right I'll bump it to 6.7

**Comment by torkelo** [comment]
Could not fix this, tried everything, but all made it break on chrome on windows.

**Comment by clwluvw** [comment]
Why there is no ability to login with `return` key from keyboard?

**Comment by ashharrison90** [comment]
hi @volschin 👋 

is this still a problem in grafana 7/8?
