### ISSUE TITLE
Select: Dropdown freezes with no options

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#21757]
When there are no options, the dropdown freezes. 
![Screenshot from 2020-01-24 09-25-35](https://user-images.githubusercontent.com/1438972/73054822-a9e5b000-3e8b-11ea-82d9-714cc776fc8c.png)
There is the bigger issue what causes them to have no data too.

_Originally posted by @tskarhed in https://github.com/grafana/grafana/pull/21638#issuecomment-578037122_

**Comment by dprokop** [comment]
Yeah, not really related to react-select as the template variable components are in angular still. Closing this in favor of https://github.com/grafana/grafana/issues/19896 which covers components migration to React.
