### ISSUE TITLE
Bar gauge showing same size for large values

### ISSUE THREAD

**Issue by dipdeb** [grafana/grafana#21761]
The size of the bar do not change for large values. I am trying to display
the graph in Series mode as the graph is not time-series related.

![bargauge](https://user-images.githubusercontent.com/11044990/73181803-efc99f00-413d-11ea-884d-1ffcffd1ca0a.png)

**Environment**:
- Grafana version: v6.6.0 (5c11bbdfb4)
- Data source type & version: PostgreSQL
- OS Grafana is installed on: CentOS 7
- User OS & Browser: CentOS 7 Chrome
- Grafana plugins: Bar Gauge (the one that comes with the installation)

**Comment by marefr** [comment]
Could you please include request/response from query inspector here? Please redact any sensitive information. Thanks

**Comment by torkelo** [comment]
What is you min and max settings? You find these options in the visualization settings , field box

**Comment by dipdeb** [comment]
> What is you min and max settings? You find these options in the visualization settings , field box

```
Min: 0
Max: 100
```
Setting the Max to the upper limit solves the issue. 

Can it be made "Auto"?

**Comment by dipdeb** [comment]
I just noticed that if Min & Max are not specified then it's set "Auto" by default, which is what I want. This solves my problem.

**Comment by broqueSF** [comment]
This issue is still happening. If you have a chart with small values and larger values then the large values are all the same height in the chart. If I add a max then it works but if I remove the max (back to auto) then the problem happens again.
![Screen Shot 2022-09-09 at 12 17 20 pm](https://user-images.githubusercontent.com/77761458/189258400-10e9126c-c796-46df-93b3-6a00bd292321.png)
![Screen Shot 2022-09-09 at 12 17 45 pm](https://user-images.githubusercontent.com/77761458/189258404-722483a0-e5ef-4e0d-ab08-7b80fd204888.png)

**Comment by chenlujjj** [comment]
Same problem here (Auto settings not work as expected), maybe the issue should be reopened

**Comment by Pioneer1011** [comment]
**Solution:**

This problem mostly shows up when you're trying to visualize several queries in one graph. There is a way around it using this technique. Don't ask me why but it just works.
All you have to do is create an expression like I have done here below and only visualise the expressions in the graph.

![afbeelding](https://user-images.githubusercontent.com/114289993/192094312-17efae29-eb28-4354-afb0-52fdbeab3473.png)

Also set the minimum to 0 or else your minimum will be your lowest value from the data points.

If you still have problems with this reply to this post and I might find a way to solve it.

**Comment by bmgante** [comment]
@TancreBryan When i do this my values in the bar gauge are duplicated. Do you know to to solve that?
