### ISSUE TITLE
Bar Gauge "l is undefined" when no data is returned

### ISSUE THREAD

**Issue by sigmaroot** [grafana/grafana#21766]
**What happened**: If no data is returned, a working bar gauge get's an error "l is undefined":

![grafik](https://user-images.githubusercontent.com/13609443/73185660-bfbed380-411e-11ea-8639-6cb55f635857.png)

If you change the query to something that returns data, the error still persists until the dashboard is reloaded completly.

**What you expected to happen**: It is displayed "No Data" or its value mapping.

**How to reproduce it (as minimally and precisely as possible)**: Select a dashboard with a bar gauge. Show Data in it. Select for example a time interval that does not return any data. See the error. Revert the time interval back to the interval before that error. The error still persists. Reload the dashboard.

**Anything else we need to know?**: No.

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: InfluxDB 1.7.3
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Windows 10 (1809) & Firefox 72.0.2
- Grafana plugins: Default + TrackMap
- Others: -

**Comment by marefr** [comment]
Reproduced here: https://play.grafana.org/d/IseeBPyZz/21766-bar-gauge-undefined-error-when-no-data-is-returned?orgId=1

Not exactly the same error as you @sigmaroot but I think it's the same underlying issue.

**Comment by philbour** [comment]
Also seeing something similar since upgrade to 6.6.0

![image](https://user-images.githubusercontent.com/30046727/73205707-7cbe2980-4139-11ea-811b-8272e618a8ec.png)

**Comment by sigmaroot** [comment]
BTW, with 6.5.0 the same dashboard worked as intended. Maybe this help to figure out what's going on.
