### ISSUE TITLE
Log at a resolution greater than second accuracy

### ISSUE THREAD

**Issue by AdmiralGT** [grafana/grafana#21765]
**What would you like to be added**:
Greater than per-second accuracy on logs.
```
t=2020-01-27T15:01:59+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-01-27T15:01:59+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-01-27T15:01:59+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-01-27T15:01:59+0000 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/plugins
t=2020-01-27T15:01:59+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-01-27T15:01:59+0000 lvl=info msg="App mode production" logger=settings
t=2020-01-27T15:01:59+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2020-01-27T15:01:59+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-01-27T15:01:59+0000 lvl=info msg="Starting DB migration" logger=migrator
```

**Why is this needed**:
When viewing these logs in Kibana + Elasticsearch, the ordering of the logs is lost which can make debugging difficult because the timeline of logs is not maintained.

**Comment by marefr** [comment]
@AdmiralGT please change log format to json. 

```ini
[log.file]
format = json
```

**Comment by AdmiralGT** [comment]
Thanks @marefr . Can we get that documented somewhere? I searched through https://grafana.com/docs/grafana/latest/installation/configuration/ but there's no mention of the `format` field.

**Comment by marefr** [comment]
@AdmiralGT oh you're right. Weird, I'll fix that

**Comment by marefr** [comment]
@AdmiralGT I opened a PR to add this to documentation. But until that is merged and published you can always inspect the defaults.ini or sample.ini which is shipped with Grafana.
