### ISSUE TITLE
Dashboard: Editing a panel with auto-refresh enabled auto-refresh in the edit screen

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#21764]
**What happened**:
If a dashboard has auto-refresh on it, and you edit a panel, then the panel edit screen also has has auto-refresh set.
If one edits the query then, and the panel refreshes while the syntax is incorrect, then when it auto-refreshes it puts an error marker in the top left of the graph, but also moves the cursor to the start of the query again.

**What you expected to happen**:
The edit screen for the panel should not have auto-refresh enabled by default. 

**How to reproduce it (as minimally and precisely as possible)**:
visit https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=30s
edit "network usage" panel
Change irate for random text. 
wait 30 seconds. 

**Anything else we need to know?**:
According to the customer, this started at version 6.3.0 

**Environment**:
- Grafana version:
>=6.3.0

**Comment by dprokop** [comment]
What browser was that you have encountered this @simonc6372 ?

**Comment by jpdstan** [comment]
@dprokop  my team and I see the same thing on our dashboards and have noticed tihs since upgrading from 6.x.x to 7.x.x. We're mostly using Chrome.

**Comment by MichaelSnowden** [comment]
I get this even with auto-refresh disabled

**Comment by hugohaggmark** [comment]
@simonc6372 I'm not able to reproduce this when I type in the query but as soon as I leave the query field the error appears. Video show the above mentioned dashboard with 5s refresh.
https://user-images.githubusercontent.com/562238/118234850-373f8000-b494-11eb-8d89-4b9821cdb00b.mp4

**Comment by simonc6372** [comment]
I can still reproduce this on play editing teh graphite Server Requests. , 5 second refresh, windows & firefox or chrome
Interestingly, I can't reproduce it on the prom demo dashboards.

**Comment by hugohaggmark** [comment]
Aha ok, probably an Angular thing: I'll have a look.
