### ISSUE TITLE
tags within template variables issue?

### ISSUE THREAD

**Issue by nickswope** [grafana/grafana#2177]
I am making templated dashboards for drill down purposes, in conjunction with a master dashboard. I did this using "customer" and "user" tags, and ran into a hiccup with the user tag while getting it to work. Grafana displayed customer just as I wanted, but I had to enclose user in quotes before it would work correctly. It's not a huge issue, as it still works, but I thought I'd point this out as a potential fix.

Additionally, my boss wanted me to mention that the auto-refresh feature doesn't work consistently in IE, but shame on him for using IE. Chrome works great.  

![githubpic](https://cloud.githubusercontent.com/assets/12914187/8192480/10fbe142-1434-11e5-8852-f637d81f9169.png)

**Comment by torkelo** [comment]
I do not understand what you issue is here, tried to read it twice and look at the image, are you complaining about the InfluxDB syntax requiring quotes? 

Can you describe what change in Grafana behavior you would like?

**Comment by nickswope** [comment]
The syntax in the image works, it's just inconsistent. I just thought I'd point it out so that you are aware of it. I'll explain step-by-step my experience.

I wrote the "customer" variable first. It worked perfectly and did not require quotes. I copied the working query and pasted it into the new "user" variable template. It did not work. After I added quotes around the "user" tag name, it worked. In other words, the syntax required quotes for the second variable, but not the first.

I believe the error message that appeared said something to the effect of "expecting string, value, ..." I had to play around with it for a little bit before I figured out that adding quotes would make it work. I'm just pointing it out so that people are spared confusion down the line. Does this make sense?

**Comment by torkelo** [comment]
But I still not get why this is a grafana issue, as it sounds to me related to InfluxDB query parsing? The query is issued to InfluxDB, the error is from influxdb, one query did not require quotes and another did. 

This is just a matter of `user` being a reserved keyword in InfluxDB and requires quotes around it :)

**Comment by nickswope** [comment]
Ah I see. That makes sense. Well thanks anyway!
