### ISSUE TITLE
flat is not a function

### ISSUE THREAD

**Issue by DislayPS** [grafana/grafana#21771]
Hi there,

I'm developing a Datasource plugin, with the current versions:
**Environment:**
Grafana version: 6.6.0
OS Grafana is installed on: MacOS Mojave
User OS & Browser: Chrome 79

I'm using a grafana Spinner from grafana/ui inside my application.
**When I try to do a yarn build, it throws me the following error:**
`yarn run v1.19.1

$ grafana-toolkit plugin:build

⠋ Cleaning  (node:33110) ExperimentalWarning: The fs.promises API is experimental

✔ Cleaning

✔ Preparing

⠋ Prettier check  Trace: TypeError: results.flat is not a function

      at /Users/xxxxx/Documents/work/grafana/plugins/xxxxx/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:76:124
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at /Users/xxxxx/Documents/work/grafana/plugins/xxxxx/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/Users/xxxxx/Documents/work/grafana/plugins/xxxxx/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/Users/xxxxx/Documents/work/grafana/plugins/xxxxx/node_modules/tslib/tslib.js:117:57)
      at rejected (/Users/xxxxx/Documents/work/grafana/plugins/xxxxx/node_modules/tslib/tslib.js:108:69)
      at process._tickCallback (internal/process/next_tick.js:68:7)

✖ results.flat is not a function

error Command failed with exit code 1.`

The actual code it points to is: 
<img width="1958" alt="Screen Shot 2020-01-27 at 2 37 21 PM" src="https://user-images.githubusercontent.com/42358911/73220123-8c764780-4112-11ea-80db-a75e440bc9dd.png">

Can you please help me resolve this issue?
Cheers,
Dislay

**Comment by DislayPS** [comment]
Closing my own issue: You need to use a version of node that is higher to 10 to support the new method flat - I'm using 12.14.1 the latest LTS version.

**Comment by AmyBlankenship** [comment]
> Closing my own issue: You need to use a version of node that is higher to 10 to support the new method flat - I'm using 12.14.1 the latest LTS version.

That's hilarious, since you need to use an older version of node to install grafana.
