### ISSUE TITLE
react-select 3.0.8: Custom scrollbar doesn't work anymore

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21777]
Custom Scrollbar seems not to work in selects after bumping react-select to lates version.

Reproduced in  v6.7.0-pre (1ad569c470d1f3a92e2ed5267b09928aea28836f) (both app and storybook):

Go to Explore, try scrolling through the list of datasources in datasource picker.

**Comment by tskarhed** [comment]
Soltuion only works with the new Select components. If you check Explore it's still there.
