### ISSUE TITLE
OpenTSDB not working in 6.6.0

### ISSUE THREAD

**Issue by langerma** [grafana/grafana#21770]
**What happened**:
Upgrade from 6.4.3 to 6.6.0

**What you expected to happen**:
OpenTSDB Source to work normally

**How to reproduce it (as minimally and precisely as possible)**:
Tried the OpenTSDB datasource which fails with: 
Error: [$injector:unpr] Unknown provider: eProvider <- e http://errors.angularjs.org/1.6.9/$injector/unpr?p0=eProvider%20%3C-%20e

also:
Template variable service failed
undefined is not an object (evaluating 'e.metricFindQuery')
**Environment**:
- Grafana version: 6.6.0
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on: Centos /
- User OS & Browser: Chrome 79

**Comment by marefr** [comment]
Thanks. Seems to have been introduced by #20668.

**Comment by langerma** [comment]
thx very much, if there is anything to test i'd be glad to do so.

**Comment by gdepeyrot** [comment]
Is it possible to apply this fix on an installed Grafana instance?

**Comment by marefr** [comment]
@gdepeyrot v6.6.1 will be released middle next week. Until then you could use a nightly build of Grafana.
