### ISSUE TITLE
Size of Gauge and Graph not remembered after saving

### ISSUE THREAD

**Issue by carroarmato0** [grafana/grafana#21788]
**What happened**:
I customized the sizes of the different Gauges and Graphs to fit nicely to my liking.
But when opening the dashboard in another page, they seem to grow back to a certain size, breaking the layout I initially configured and saved.

**What you expected to happen**:
After saving the dashboard and opening it up in another browser tab, the layout structure should be respected.

**How to reproduce it (as minimally and precisely as possible)**:
Before reloading the page after saving:
![image](https://user-images.githubusercontent.com/1828645/73263685-66fc4300-41d1-11ea-9e36-cac9c23074bb.png)

After reloading (or opening in another tab/browser):
![image](https://user-images.githubusercontent.com/1828645/73263746-914e0080-41d1-11ea-8432-93daaaeda3df.png)

**Anything else we need to know?**:
The Gauges and Graphs are Repeated. They initially were configured as Max 6 per row, but changing that to anything lower or higher results in different effects.
Max 2 per row (both Gauge and Chart):
![image](https://user-images.githubusercontent.com/1828645/73265121-995b6f80-41d4-11ea-837a-808360ca5bfb.png)

Max 24 per row (both Gauge and Chart):
![image](https://user-images.githubusercontent.com/1828645/73265224-c7d94a80-41d4-11ea-88f1-69dca09ab18c.png)

It looks like there's something going on between repeated elements and the WorldMap Panel.

**Environment**:
- Grafana version: Grafana v6.6.0 (5c11bbdfb4)
- Data source type & version: InfluxDB 1.7.9
- OS Grafana is installed on: CentOS Linux release 7.7.1908 (Core) (Docker container)
- User OS & Browser: Ubuntu 19.10 Firefox 72.0.1 (64-bit)
- Grafana plugins: grafana-worldmap-panel
- Others: Docker container: grafana/grafana sha256:199e063bb42289ae417f60bd8a48293a290ea4589098d3c4da9b6741a7eca7b5

**Comment by torkelo** [comment]
can you include your dashboard json? Do you use panel repeat?

**Comment by carroarmato0** [comment]
Yes, I do use repeat on the first Gauge and Chart
[dashboard.txt](https://github.com/grafana/grafana/files/4127494/dashboard.txt)

**Comment by torkelo** [comment]
If your using repeating panels they are designed to only be by themselves on a single row
