### ISSUE TITLE
Iam unable to authenticate using basic auth

### ISSUE THREAD

**Issue by Barsonax** [grafana/grafana#21784]
**What happened**:
Iam unable to authenticate using basic auth even through this is enabled in Grafana:
![image](https://user-images.githubusercontent.com/19387223/73254004-e41dbd00-41bd-11ea-987a-f7828a50e945.png)

**What you expected to happen**:
It authenticates.

**How to reproduce it (as minimally and precisely as possible)**:
Set admin and password as your credentials then try to curl to some url that requires authentication:
```
curl http://admin:password@localhost:3000/api/auth/keys
```
You will get the following error:
```
curl : {"message":"Unauthorized"}
At line:1 char:1
+ curl http://admin:password@localhost:3000/api/auth/keys
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Environment**:
- Grafana version: v6.1.2
- Data source type & version: Influxdb
- OS Grafana is installed on: Linux (inside a docker container)
- User OS & Browser: Windows, None
- Grafana plugins: InfluxDb

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

It works for me, but seems like you're using curl in Powershell not sure that's the problem. Make sure the user you're authenticating with had admin org role.

**Comment by Barsonax** [comment]
I wasn't asking a question I was pointing out this doesn't seem to be working properly but I see you already closed the issue.... According to the docs this should work:
https://grafana.com/docs/grafana/latest/http_api/auth/#basic-auth

However maybe the docs are missing a key point here.

> It works for me, but seems like you're using curl in Powershell not sure that's the problem. Make sure the user you're authenticating with had admin org role.

It doesn't work when doing this through the browser either so it seems grafana is ignoring the username and password in the browser. Normal login works fine. and the user iam using is a Admin.

**Comment by Barsonax** [comment]
Interestingly it does work with postman. It seems that postman is adding a Authorization header if the username and password are present in the url:
![image](https://user-images.githubusercontent.com/19387223/73266665-9f9f1b00-41d7-11ea-89d6-bc2f6730c361.png)

Maybe this is missing with the curl on windows

**Comment by Barsonax** [comment]
@marefr please reopen the issue as it turns out the user:password format in urls is deprecated (might still work for you if you use a old version) but grafana still uses this in the docs

**Comment by aknuds1** [comment]
@Barsonax I've tried with curl v7.68.0 on Linux, and it also works for me. If you use the `-v` option to curl, you should see if it tries basic auth or not.

**Comment by Barsonax** [comment]
The `curl` on windows is nothing more than a alias for Invoke-WebRequest so this option does not work. This is also the reason of the difference in behavior. With Invoke-WebRequest you can however do the following which will work (you need to encode the username and password as base64):
```
Invoke-WebRequest http://localhost:3000/api/auth/keys -Headers @{"Authorization"="Basic YWRtaW46cGFzc3dvcmQ="}
```

However when using `curl.exe` (which actually uses curl instead of Invoke-WebRequest) the url does work as the tool does this for you. Might be worth pointing out this small difference on windows in the docs.

Still since this format is deprecated it might be removed in the future.
