### ISSUE TITLE
Tracing: Trace frontend

### ISSUE THREAD

**Issue by lfroment0** [grafana/grafana#21792]
**What would you like to be added**:
Initialise a Jaeger tracer in the frontend

**Why is this needed**:
Tracing request from the frontend would be part of the effort of having tracing setup in all components.

**Comment by bergquist** [comment]
I think this would be very interesting. I need to check what kind of support there are for tracing in the frontend. 

It would be great if Grafanas backend could pass any parent traceId to the frontend if any headers are set. To avoid breaking the chain for proxies in front of Grafana. 

One tricky piece is the fact that Grafana is a single page application so it would have to generate a new parentless span when navigating to new dashboards.

**Comment by nicolastakashi** [comment]
Hey @bergquist this is a nice feature, any update or something that I can help with that?
