### ISSUE TITLE
Ability to control the interval for rendering data

### ISSUE THREAD

**Issue by BensamV** [grafana/grafana#21793]
**What would you like to be added**:
I'd like to have the ability to control the interval for rendering data

**Why is this needed**:
We have our metrics pushed every 60 seconds to the tsdb and then to grafana. We expect the data to be rendered in the same interval (60 seconds). However we see this interval changing based on the time range we select and we believe that it is affecting our data. We want to give the data/minute but the minute is in question as the rendering frequency is inconsistent.

When we choose 5m time interval, we see the data interval is 1 second. 
When we choose 30m time interval, we see the data interval is 3 seconds. 
When we choose 6h time interval, we see the data interval is 30 seconds. 

![image](https://user-images.githubusercontent.com/28261647/73270381-8b91f400-41ac-11ea-9877-737d2f593e1d.png)

![image](https://user-images.githubusercontent.com/28261647/73270566-ec213100-41ac-11ea-8e13-595153447796.png)

**Comment by torkelo** [comment]
This is how Grafana and Graphite works. You can control the interval in graphite function summarize where you can pass in the aggregation function and time interval. There is still a maxDataPoints parameter that Grafana sends to graphite to control data point count, so when you zoom out there are not hundreds of thousands of data points returned. maxDataPoints is equal to the width of the graph in pixels. Graphite will then consolidate (group) the results to make sure the results are not more results than maxDataPoints. You control the consolidation group by function using the graphite function consolidateBy
