### ISSUE TITLE
Maximum queries "index"

### ISSUE THREAD

**Issue by mitchellpeixer** [grafana/grafana#21802]
Hello friends,

We use a lot of calculation using the own queries rows

more than A to Z would be very nice, something like A1 B1, just like MS Exccel

![image](https://user-images.githubusercontent.com/23042694/73293420-9e272000-41e2-11ea-85dc-40792d658a51.png)

Thank you!

**Comment by alexmontoanelli** [comment]
+1

**Comment by jaderjvr** [comment]
+1

**Comment by cassianotb** [comment]
+1

**Comment by filipereinerts** [comment]
+1

**Comment by lucasdelavrapinto** [comment]
+1

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/4978
