### ISSUE TITLE
Variables: Duplicate button looks like a tag and not a button that you can click

### ISSUE THREAD

**Issue by wraybowling** [grafana/grafana#21807]
![Screen Shot 2020-01-28 at 4 23 20 PM](https://user-images.githubusercontent.com/1120619/73306596-8b184e00-41ea-11ea-9a39-4a4f6737c94d.png)

When viewing a list of variables, each row has an ambiguous element labeled "duplicate." The user may not know if this is a tag or status indicator using "duplicate" as an adjective/noun to describe the variable as having a conflict with something else or the verb form where it is a clickable action that the user could take. Only after clicking is it evident that the text is in fact a button. This is unfortunately a problem with many english synonyms of the word, for instance if the button was labelled "copy" or "clone" those have adjective/noun forms too. Changing the label of the button will not solve the ambiguity. The solution would be to style tags, statuses, and buttons to be more distinctly different from each other and/or to add an icon.

**Reproduce Steps**:
- Navigate to https://play.grafana.org
- Click ⚙︎ Dashboard settings
- Click {x} Variables
- Create a variable

**Environment**:
- Grafana version: Demo
- User OS & Browser: All

**Comment by torkelo** [comment]
What are you talking about? Can you show a screenshot? variable rows with the word duplicate? Never seen that. Please add more info

**Comment by wraybowling** [comment]
Added repro steps

**Comment by wraybowling** [comment]
![Screen Shot 2020-01-28 at 4 23 20 PM](https://user-images.githubusercontent.com/1120619/73306596-8b184e00-41ea-11ea-9a39-4a4f6737c94d.png)

**Comment by torkelo** [comment]
Ah of course , completely forgot this button

**Comment by flopp999** [comment]
If that was a Tag I think it would have an X to be able to delete it?
If you move the mouse over the text you see that it will show a Hand, because it is a button

**Comment by chakradeb** [comment]
I want to help in this issue

**Comment by wraybowling** [comment]
Another thing to consider: most buttons in grafana are brightly colored. This button is dark grey on dark grey. A change to a lighter shade would help it feel like it belongs with other actions too.

**Comment by torkelo** [comment]
It is used in query editor row to duplicate a query
![Screenshot from 2020-05-27 18-36-30](https://user-images.githubusercontent.com/10999/83047689-00851580-a049-11ea-92bc-bdfdc17478eb.png)
