### ISSUE TITLE
Azure Monitor data source still uses wrong authorization uri for Azure China

### ISSUE THREAD

**Issue by mstefa27-ford** [grafana/grafana#21803]
**What happened**:

When attempting to configure a data source in Grafana for Azure Monitor in the Azure China cloud, Grafana reports back two "unexpected error" messages and a message at the bottom:

Azure Monitor: Cannot connect to Azure Monitor REST API. 2. Azure Log Analytics: Cannot connect to Azure Log Analytics REST API.
Upon inspection in the network tab in Chrome's developer console, I can see that the error appears to be caused by a 401 at http://{OUR GRAFANA HOSTNAME}/api/datasources/proxy/5/sameasloganalyticsazure/bf19f9f8-baac-4275-9a9b-546989f7d439/metadata

The www-authenticate header suggests that Grafana is attempting to obtain authentication from login.microsoftonline.com:

Www-Authenticate: Bearer authorization_uri="https://login.microsoftonline.com/common"

**What you expected to happen**:

I would expect Grafana to instead use the Azure China login gateway:

https://login.chinacloudapi.cn/common

**How to reproduce it (as minimally and precisely as possible)**:

Configure a Azure Monitor for the Azure China cloud (portal.azure.cn) with an Azure AD app registration that has the log analytics reader role to the subscription that contains your log analytics instance and the Data.Read permission for the Log Analytics API. Grant the permissions. Then attempt to configure the Log Analytics instances as a Data source within Grafana with the developer tab open to Network on Chrome (issue occurs in all browsers).

Issue occurs when Save & Test is clicked with the proper configuration information above (see screenshot linked in my first comment).

**Anything else we need to know?**:

Originally reported here: https://github.com/grafana/grafana/issues/19545
While that issue was closed, I was not able to verify until 6.6 was released. Now that 6.6 is released, I can confirm this is still not fixed...

Grafana IS able to load the default subscription and workspace lists, but IS NOT able to query the Log Analytics API. Perhaps the way Grafana authenticates to get the subscription and workspace list is different than testing the Log Analytics API?

Confirmed all permissions are correct by calling the Log Analytics API myself with the same credentials via Postman.

**Environment**:
- Grafana version: 6.6
- Data source type & version: Azure Monitor - Azure China 
- OS Grafana is installed on: https://hub.docker.com/r/grafana/grafana/
- User OS & Browser: Chrome
- Grafana plugins: Polystat
- Others:

**Comment by mstefa27-ford** [comment]
And here's a screenshot that explains the issue pretty well:

https://imgur.com/a/we94udv

**Comment by mstefa27-ford** [comment]
We took a look at this and fixed this at least for Azure China and North America Log Analytics. Currently, the codebase doesn't work at all with Azure China. zbbkeepgoing@94bbe06's changes in the previous issue enabled us to access China Azure ONLY. If you wanted to access both a NA and CN Log Analytics workspace, which is the requirement we had, we couldn't do that.

Our solution to make the Azure China and Azure North America work in Log Analytics is attached. There may be a more elegant solution to our issue, but hopefully someone can take this and incorporate it into the master.

 mstefa27-ford@d026bc4f392e9cc0a34abfa7738033aceeb66a61

**Comment by lzzgeo** [comment]
> We took a look at this and fixed this at least for Azure China and North America Log Analytics. Currently, the codebase doesn't work at all with Azure China. [zbbkeepgoing/grafana@94bbe06](https://github.com/zbbkeepgoing/grafana/commit/94bbe06)'s changes in the previous issue enabled us to access China Azure ONLY. If you wanted to access both a NA and CN Log Analytics workspace, which is the requirement we had, we couldn't do that.
> 
> Our solution to make the Azure China and Azure North America work in Log Analytics is attached. There may be a more elegant solution to our issue, but hopefully someone can take this and incorporate it into the master.
> 
> [mstefa27-ford/grafana@d026bc4](https://github.com/mstefa27-ford/grafana/commit/d026bc4f392e9cc0a34abfa7738033aceeb66a61)

I just tried to make it work with both NA and CN log Analytics workspace, even with NA and CN ApplicationInsights. could you help check the PR? Hopefully, this PR will be merged into master ASAP.
