### ISSUE TITLE
b.query is not a function

### ISSUE THREAD

**Issue by ghamed** [grafana/grafana#2180]
Hi,

I just installed 2.0.2 (http://grafana.org/download/) package on Ubuntu 12.0.4 and if i use sqlite3 i have no issues with graphs however as soon as i change the data source to mysql on grafana.ini graphs are not loading and getting an "!" mark next to each graph. and when i click on it i see the following

```
Message:
			b.query is not a function
		
Stack trace:
			TypeError: b.query is not a function
    at issueMetricQuery (http://hostname/app/app.6e379bdb.js:23:30533)
    at l.a.refreshData (http://hostname/app/app.6e379bdb.js:35:12206)
    at http://hostname/app/app.6e379bdb.js:23:28684
    at i (http://hostname/app/app.6e379bdb.js:10:29774)
    at http://hostname/app/app.6e379bdb.js:10:29946
    at l.$eval (http://hostname/app/app.6e379bdb.js:12:5068)
    at l.$digest (http://hostname/app/app.6e379bdb.js:12:3586)
    at l.$apply (http://hostname/app/app.6e379bdb.js:12:5324)
    at http://hostname/app/app.6e379bdb.js:12:12581
    at g (http://hostname/app/app.6e379bdb.js:9:23810)
```

Just to add the other stuff like adding datasources/changing ORG,etc... all working good.

**Comment by ghamed** [comment]
Ok Just to add this only happen when i am using elasticsearch as datasource.

**Comment by ghamed** [comment]
Ok i might know why now. It seems lodash module is missing. i checked ```/usr/share/grafana/public```  and no sign of lodash or anything similar at all. Am i missing something here.

**Comment by torkelo** [comment]
Elasticsearch can only be used as a data source for annotations, it cannot be used for graphs.

**Comment by ghamed** [comment]
Hi,

I understand it but what is that error then. why do i only get it when i set the the storage engine to MySql. I dont have the same issue when the storage engine is set to sqlite3. Is this related to this
https://groups.io/org/groupsio/grafana/thread/54973

**Comment by torkelo** [comment]
No as that is about a sql data source. Not about switching Grafana to use mysql as it's backend db (for uses and dashboards).

I do not know what I happening in you case. You are only switching the grafana backend db, then you add you graphite data sources as usual? No one else h's reported something like this, I use the mysql datasource.  Must be that you configure the graphite or elasticsearch datasource differently when you set up grafana with mysql storage backend

**Comment by ghamed** [comment]
Hi,

To be honest it is a normal setup really. Please let me know what else i can provide you to fix this issue.

**Comment by torkelo** [comment]
I need A LOT more info. :) The stack trace just tells me you are using  a non metric data source as meetric data source. hundreds of users use mysql without this issue,I  have zero chance to help you without more info. what does your dashboard look like? what is the metric query look like? what requests happen?  what is the log from grafana backend, what datasource is the graph panel using, etc

Please give more info

**Comment by torkelo** [comment]
normal setup, hehe the way funny and really helped narrow down your config issue :)

**Comment by ghamed** [comment]
:) i agree with you 100%. Ok mange to find the cause of this. My default datasource was set to Elastic and that is why it was not working. 

Again many thanks.

**Comment by torkelo** [comment]
that is great! should probably validate that the graph data source supports metrics instead of just throwing an error like this :)

**Comment by Bunyod** [comment]
He he  Perfect! ))

**Comment by niclash** [comment]
Is it still true that ElasticSearch 2.5 (2.6?) can't be used as a metrics source??

**Comment by torkelo** [comment]
That is no longer true
