### ISSUE TITLE
show query errors from graphite/metrictank tied to request

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#21804]
Soon, metrictank will be able to return errors (e.g. "invalid parameters") tied to a specific query.
see https://github.com/grafana/metrictank/issues/1600
e.g. if you specify 3 targets and one of them has a bad syntax or invalid request, metrictank currently fails the entire request (http 400) and returns the error as a "global" in the body.

Soon, it can do either of these two:
1) still fail the entire request, with http 400. but provide a list of errors, each error would have the target index (0, 1, 2, ...) it corresponds to.
2) return a "partial response": data for those targets that worked, and errors for those that failed (and again, tied to the target index)

Grafana can then visualize these errors corresponding to the right query.
I would be curious if there's a preference for approach 1 or 2.  I like 2, but it should still be clear that there was a failure on that panel. when going into the panel, the query editor can then show the error right alongside the respective failing queries

**Comment by torkelo** [comment]
think 2 is preferable, @ryantxu might be related to https://github.com/grafana/grafana/pull/21396 ?

**Comment by ifrost** [comment]
+1
