### ISSUE TITLE
Docs: Add instructions to setup Keycloak with generic oauth

### ISSUE THREAD

**Issue by jarrod-lowe** [grafana/grafana#21809]
I've just set this up with Keycloak, using the generic oauth. I suggest adding:

Set up OAuth2 with Keycloak

First set up Grafana as an OpenId “client” in Keycloak. Change it into the “confidential” type. Then set the Base URIs to https://<grafana domain>/ and set the Login redirect URIs to https://<grafana domain>/login/generic_oauth.

You can get the URLs you'll need by going to "OpenID Endpoint Configuration" in your realm settings, in Keycloak. You are looking for "authorization_endpoint", "token_endpoint", and "userinfo_endpoint", respectively.

[auth.generic_oauth]
name = Keycloak
enabled = true
scopes = openid profile email
client_id = <keycloak application Client ID>
client_secret = <keycloak application Client Secret>
auth_url = <authorization_endpoint>
token_url = <token_endpoint>
api_url = <userinfo_endpoint>

**Comment by aknuds1** [comment]
I think this might be better submitted as a PR?

**Comment by marefr** [comment]
Depending how popular Keycloak is as OAuth provider together with Grafana we may or may not want this in Grafana documentation since this is something that needs to be maintained moving forward taking into account that changes in Keycloak may need to be updated in Grafana documentation. Please upvote if you use Keycloak and think this is a good idea.

**Comment by DikshaTomar101** [comment]
@jarrod-lowe can u help me with the instructions you followed in setting up the keycloak and grafana integration like the changes in grafana config and what all steps to follow in keycloak

**Comment by ptman** [comment]
#27443

**Comment by GrafanaWriter** [comment]
This issue hasn't had activity in more than six months. In another week, I will close it.

If you comment or otherwise update it, we'll reset the clock.

**Comment by Jguer** [comment]
Slightly off topic: we have a development environment setup script that's using generic oauth and keycloak : https://github.com/grafana/grafana/tree/main/devenv/docker/blocks/oauth (`make devenv sources="oauth"`) that might be useful for users looking for some pointers

**Comment by Jguer** [comment]
Implemented for Grafana 9.3
