### ISSUE TITLE
Grafana CLI "reset-admin-password" -homepath flag provided but not defined

### ISSUE THREAD

**Issue by OleksandrMykytenko** [grafana/grafana#21811]
**What happened**:
I'm unable to reset Grafana admin password via grafana-cli due to the error saying that `-homepath` flag is provided but not defined. I'm changing password via bash script and it worked for Grafana version `6.2.4`. Today I have deployed Grafana version `6.6.0` and see this error:

```
$ grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" <password>
Incorrect Usage: flag provided but not defined: -homepath

NAME:
   Grafana cli admin reset-admin-password - reset-admin-password <new password>

USAGE:
   Grafana cli admin reset-admin-password [arguments...]
flag provided but not defined: -homepath
```

**What you expected to happen**:
I expect to get admin password changed.
**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana version `6.6.0` and execute the following command:
```
grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" <password>
```

**Anything else we need to know?**:
I just executed reset-admin password within `/usr/share/grafana` where is my Grafana installation located (w/o `homepath` flag) and it worked perfect, admin password has been changed. Seems some issues with arguments parsing. Also, not sure about other commands with this flag passed.
**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: not related to the issue
- Grafana plugins: grafana-piechart-panel, snuids-trafficlights-panel, vonage-status-panel
- Others:

**Comment by aknuds1** [comment]
Thanks for reporting this, will have a look.

**Comment by marefr** [comment]
@OleksandrMykytenko you need to put the `--homepath <path>` after the `grafana-cli` since it's a global options, see [docs](https://grafana.com/docs/grafana/latest/administration/cli/#grafana-cli-command-syntax).

**Comment by OleksandrMykytenko** [comment]
Hello, thank you for clarification, it's clear now. However, I was using exact example from these docs (please refer to https://grafana.com/docs/grafana/latest/administration/cli/#override-homepath-value) . So it might be a mistake or obsolete information in docs.

**Comment by aknuds1** [comment]
@OleksandrMykytenko Thanks for reporting the issue, I've made a PR, #21840.
