### ISSUE TITLE
[influxdb 0.9] Quote regular expression characters in templates variable values

### ISSUE THREAD

**Issue by fromYukki** [grafana/grafana#2181]
Hello

Lets say that I have following query:
`SELECT mean(value) FROM "cpu_load" WHERE host =~ /$host/ AND $timeFilter GROUP BY time($interval) ORDER BY asc`

And following `$host` template:
`SHOW TAG VALUES FROM cpu_load WITH KEY=host`

Everything is nice until you see the `domain/server1` value in the `$host` variable.

Is it possible to quote values some how?
Thank you

**Comment by torkelo** [comment]
tag values like that are not supported with regex matching. And InfluxDB does not support quoting with regex filter. It could be solved by regex escaping the value but that would break other scenarios.
