### ISSUE TITLE
Stat panel: color doesn't apply to string value

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#21810]
**What happened**:
Panel doesn't apply _Base_ color to string values, value is always green.

**What you expected to happen**:
It's not possible to set a threshold for string values, but I think panel should apply _Base_ color to any value that can't be compared to thresholds.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query that return text info (host name, software version, etc)

![Screenshot from 2020-01-29 10-52-50](https://user-images.githubusercontent.com/4932851/73337519-8bb1f280-4285-11ea-8397-993162ddda04.png)

**Environment**:
- Grafana version: 6.6.0
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
think this could be fixed with new threshold / color options where we will have a fixed color mode as well (not color from threshold)

**Comment by alexanderzobnin** [comment]
@torkelo could you point me to that new option?

**Comment by torkelo** [comment]
It’s not available in the UI , need to update the threshold UI

**Comment by marefr** [comment]
This feels like a bug we did fix a while ago, maybe for some other panel like singlestat or bargauge? Cannot find it though searching through issues.

**Comment by torkelo** [comment]
we fixed it for the angular stat panel

**Comment by dprokop** [comment]
Maybe related to #22592

**Comment by tskarhed** [comment]
Issue is here, working on a solution https://github.com/grafana/grafana/blob/cd012bdfb42a607ac9e3d3096e1b3faeb397e92d/packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx#L32

**Comment by tskarhed** [comment]
The color was actually fetched from the base threshold, just not returned all the way to BigValue.
