### ISSUE TITLE
Datepicker is not displayed in "kiosk=tv" mode

### ISSUE THREAD

**Issue by evgbibko** [grafana/grafana#21815]
**What happened**:
Datepicker is not displayed in the `kiosk=tv` mode (grafana v6.6.0):
![grafana_6 6 0](https://user-images.githubusercontent.com/57246017/73347685-9aff6300-42ba-11ea-97e0-5a4ff667fe8e.png)

**What you expected to happen**:
The datepicker button is displayed the same as in the v6.5.3:
![grafana_6 5 3](https://user-images.githubusercontent.com/57246017/73347814-d1d57900-42ba-11ea-92f4-8a4129102cbc.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Open dashboard in `kiosk=tv` mode.

**Anything else we need to know?**:

This bug takes place as the datepicker button has the `navbar-button--zoom` class (instead of `navbar-button--tight`) which makes the element hidden in the mentioned mode.

**Environment**:
- Grafana version: 6.6.0 (5c11bbdfb4)
- OS Grafana is installed on: Ubuntu 18.04

**Comment by torkelo** [comment]
thanks for reporting this!
