### ISSUE TITLE
Graph on the Stat panel not showing properly

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#21818]
**What happened**:
The new Stat panel not showing the graph properly
**What you expected to happen**:
The graph to show on the panel, same as the sparkline on the SingleStat panel.
**How to reproduce it (as minimally and precisely as possible)**:
When you put in a query in the panel, it will select the Graph Visualization. If you switch it to Stat, it will show the graph on it properly. However, if you switch it to Singlestat and then to Stat, the graph on Stat will show only a flat line. This will also happen if you use some old panel that was using the Singlestat visualization and try to convert it to Stat.

It was tested here:
https://play.grafana.org/d/000000011/graphite-carbon-metrics?tab=visualization&orgId=1&fullscreen&edit&panelId=2

This is how it looks like with Graph Visualization:
![Graphite Carbon Metrics - Graph](https://user-images.githubusercontent.com/56955081/73354373-db98b580-4295-11ea-8e3c-c6a4d9ab2223.png)

This is when you switch to Stat:
![Graphite Carbon Metrics - Stat](https://user-images.githubusercontent.com/56955081/73354389-e3f0f080-4295-11ea-8dd8-a8688244ec89.png)

Switch to Singlestat and then back to Stat:
![Graphite Carbon Metrics - Stat2](https://user-images.githubusercontent.com/56955081/73354399-ece1c200-4295-11ea-816d-cf4878c321f9.png)

**Environment**:
- Grafana version: 6.6.0

**Comment by torkelo** [comment]
It seems it gets min:0 and max: 100 after the switch from the singlestat panel, you will have to remove those for the graph to return to auto min/max ?

**Comment by Tomica-G** [comment]
Oh, you are right @torkelo, deleting values from Min/Max does fix the graph. Can we change the Stat panel so it doesn't automatically add Min/Max values when switching from Singlestat to it?
