### ISSUE TITLE
Table panel : Export as csv shows undefined when a field is hidden

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#21825]
**What happened**:

When exporting table panel as csv, if the field is hidden then they are getting downloaded as undefined.

![image](https://user-images.githubusercontent.com/153843/73362454-ca07db80-429e-11ea-8a39-9a104075a71c.png)

**Environment**:
- Grafana version: 6.5.2
- User OS & Browser: Chrome

**Comment by marefr** [comment]
Works as expected in v6.6.0. I did try/verify it here by editing a panel and hiding columns https://play.grafana.org/d/000000031/table-panel-showcase?orgId=1
