### ISSUE TITLE
InfluxDB Plugin user interface remove button doesn't show correctly

### ISSUE THREAD

**Issue by nFrechen** [grafana/grafana#21829]
**What happened**:
When clicking together an InfluxDB query and say you want to remove the `mean()` function this should be the expected behavior:
![Bildschirmfoto 2020-01-29 um 15 20 11](https://user-images.githubusercontent.com/10114741/73364686-42749980-42ab-11ea-86eb-78c1686978fa.png)
When clickeing on `mean()` a remove button is shown.

But instead this happens:
![Bildschirmfoto 2020-01-29 um 15 19 58](https://user-images.githubusercontent.com/10114741/73364685-42749980-42ab-11ea-9612-5fe112c29513.png)
The remove button is barely visible. It has the same width as the real button, but no height. Hence the frame is so small it looks like a line.

Only if you press `mean()` another time (to close the invisible remove button) and then click it again, the remove button appears properly like in the first screenshot.

I tested this on Firefox in Windows and on Mac, also on Opera for Mac.

I am using Grafana version 6.6.0 running in a docker container (compiled with the Dockerfile from this repository).

**Comment by torkelo** [comment]
thanks for reporting this, clicking multiple times seems to show it correctly. think this is related to angular digest issue

**Comment by nFrechen** [comment]
for a new user that doesn't know this button should appear this is very confusing...

**Comment by marefr** [comment]
@nFrechen understand that. We're trying to fix this for upcoming v6.6.1 release.

Reproducible here for reference https://play.grafana.org/d/000000002/influxdb-templated?orgId=1&fullscreen&edit&panelId=1
