### ISSUE TITLE
Inconsistent behavior with relative URLs in SingleStat panel link

### ISSUE THREAD

**Issue by gjulianm** [grafana/grafana#21839]
**What happened**: My Grafana instance is exposed in a subpath, *http://server/grafana*. When setting a Panel link in a SingleStat panel with a URL like */grafana/d/mydashboard*, the link behavior is inconsistent:

-  The link that appears in the top-left corner popup points to *http://server/grafana/d/mydashboard*
- Clicking on the panel redirects to *http://server/grafana/grafana/d/mydashboard* (it adds the base URL configured in Grafana) but only when 'Open in new tab' is not selected. If I select the new tab option, the URL in the new tab is *http://server/grafana/d/mydashboard*.

**What you expected to happen**: Links should behave the same way in all of those cases.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start a Grafana instance in a subpath of a server
2. Add a new dashboard with a SingleStat panel.
3. Add a Panel link in the panel that starts with "/".

**Anything else we need to know?**: It seems that the click() event handler for the SingleStat panel manages URLs differently, with window.open() if it wants to open in a new tab or an absolute URL, and with $location.url for other cases. But that code wasn't changed recently so it seems that it is a change of behavior of the $location service.

**Environment**:
- Grafana version: Version 6.6.0 (commit: 5c11bbdfb4, branch: HEAD)
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 18.04 LTS
- User OS & Browser: macOS, Firefox 73.0b9 and Chrome 79.0
- Grafana plugins: N/A
- Others: N/A

**Comment by gjulianm** [comment]
Hello, did anyone take a look at this issue? :) 

Thanks!

**Comment by siebenmann** [comment]
This is a regression from Grafana 6.5 and before, where it used to work properly. I found that telling our Singlestat panels to open the link in a new tab made their relative links work again when the panel is clicked on.
