### ISSUE TITLE
Sum query on another query with Elasticsearch

### ISSUE THREAD

**Issue by SophiePages** [grafana/grafana#21838]
Hi,
Here are my two queries. With query B, I would like to sum the itemNumberDone of query A. 
I also would also like a query C that sum the itemNumberInError of query A.

![prob_grafana](https://user-images.githubusercontent.com/60466458/73438730-ca5faf80-434e-11ea-88c9-e7856ec62be6.PNG)

![prob_grafana2](https://user-images.githubusercontent.com/60466458/73438731-ca5faf80-434e-11ea-801d-6175dbc72523.PNG)

If what I am asking previously is not possible, I would like that my query A shows me the total of all the itemNumberDone after the group by. The items need to be grouped by and I want the items with the max timestamp like I did in the query. Currently, it doesn't show me a total in the pie chart but many sums.

I use Grafana v6.2.5,
Thank you

**Comment by torkelo** [comment]
We will allow transformations on existing query results in the future (this sounds like you want sum all series from another query), this will be possible some time later this year. 
https://github.com/grafana/grafana/issues/3677

**Comment by SophiePages** [comment]
Ok thank you for the quick reply ! Yes I want to sum some series from another query.
