### ISSUE TITLE
Feature Request: Add NotificationChannel for Rainbow

### ISSUE THREAD

**Issue by dominikbenner** [grafana/grafana#21831]
Hi,

is it possible to add support for Rainbow Messenger for notifications?

API Hub Rainbow: https://hub.openrainbow.com/#/

Best regards

**Comment by marefr** [comment]
We do not currently add any new alert notifier to core Grafana unless it's highly requested/upvoted. But will leave this open to see if there's any interest of it. 

Workaround would be to use the webhook notifier and implement webhook listener that integrates against Rainbow Messenge.
