### ISSUE TITLE
App Plugins: Routing doesn't work as expected, Worldping app doesn't work in Grafana v6.6.0

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#21842]
**What happened**:
Cannot add endpoints/probes in Worldping App plugin. Ref https://github.com/raintank/worldping-app/issues/233

**What you expected to happen**:
Plugin pages to load as expected and being able to create endpoints/probes.

**How to reproduce it (as minimally and precisely as possible)**:
See referenced issue.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.0
- Worldping app version: 1.2.6

**Comment by dprokop** [comment]
Most probably Angular digest issue, identified offender 880fbcb09a5ab1a63f69811db8a94ba76ac7bf0f
