### ISSUE TITLE
Grafana's plugin loader does not support define(()) construction

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#21843]
**What happened**:
If you create a plugin without grafana's sdk calls you will get module.js file with code `define((...))` in production build after minimization. Then if you try to load such plugin you will receive "TypeError: define is not a function" exception from grafana's plugin loader

This situation is primarily possible for application plugins that contain only configuration for other sub plugins and do not require some sdk calls at all. There is no matter old style angular plugin or new style react plugin you are using.

Plugin loader worked correctly before 6.4.+ grafana released

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
[minimizer.zip](https://github.com/grafana/grafana/files/4122938/minimizer.zip)

**Anything else we need to know?**:
Look at my last comment to issue https://github.com/grafana/grafana/issues/21785
This issue is origin point for this bug

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
> If you create a plugin without grafana's sdk calls you will get module.js file with code

Can you describe what you mean? How are you building your plugin? 

We have not updated systemjs (responsible for dynamically loading plugins) since 6.4 so not sure what could cause this change

**Comment by marefr** [comment]
Duplicate #21785

**Comment by marefr** [comment]
Please continue discussions in the issue you've already opened.
