### ISSUE TITLE
Time problem with hassio and mariadb

### ISSUE THREAD

**Issue by sanderlv** [grafana/grafana#21845]
**What happened**:
Time is different in graphs than my time

**What you expected to happen**:
good time diplayed

**How to reproduce it (as minimally and precisely as possible)**:
install hassio, install mariadb, install grafana,

**Anything else we need to know?**:
I tried to set the correct time zones in grafan, but it only lets met set:
![image](https://user-images.githubusercontent.com/16528916/73443912-dd2ab200-4357-11ea-8757-8a11de3ddd33.png)

**Environment**:
- Grafana version: Grafana v6.6.0 (5c11bbdfb4)
- Data source type & version: maria db
- OS Grafana is installed on: hassio hassos
- User OS & Browser: does not matter
- Grafana plugins: none
- Others:

**Comment by marefr** [comment]
You need to make sure that timestamps are returned in UTC from your database. Grafana backend only returns UTC timestamp to Grafana UI.
