### ISSUE TITLE
panel repetition does not share rows

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#21852]
**What happened**:
I enabled multiple selection for a variable (interface) and enabled Single Stat repetition (horizontal) based on interface. grafana then rearranged my display such that rx & tx no longer shared a single row - they had a row each!

**What you expected to happen**:
What I expected to happen was for grafana to pack the four single state panels into the same row.

**How to reproduce it (as minimally and precisely as possible)**:
Enable repitition for a small single state panel using a variable.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: 6.6
- Data source type & version: influxdb 1.7.9
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS, Chrome
- Grafana plugins:
- Others:

<img width="1368" alt="Screen Shot 2020-01-31 at 12 24 38 am" src="https://user-images.githubusercontent.com/24280758/73453651-99b85e00-43c0-11ea-81bf-69b8809c157d.png">
<img width="1362" alt="Screen Shot 2020-01-31 at 12 24 51 am" src="https://user-images.githubusercontent.com/24280758/73453652-99b85e00-43c0-11ea-840f-8b197d4301d3.png">

**Comment by yellowpattern** [comment]
Oh this is worse than I thought. If I arrange it with the two next to each other, "Save" and then reload, I get one per line!

**Comment by marefr** [comment]
What's your max per row setting of the panel you're repeating?

**Comment by yellowpattern** [comment]
I tried it without a max per row value set and also at 12 (I think that is the maximum?) and in both cases the outcome was the same.

**Comment by torkelo** [comment]
unable to replicate, can get repeated panels to share the same row here: https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1 (the button row with panels is repeated)
