### ISSUE TITLE
New row creation mechanism converts the entire page to a single row

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#21853]
**What happened**:
I selected "Convert to row" and the entire set of grafana panels got converted to a single row.

**What you expected to happen**:
I wanted to put two elements in a row, not the entire page. At the very least I wanted to be able to select what got put in a row, but no!

**How to reproduce it (as minimally and precisely as possible)**:
Open a page with multiple elements on it and attempt to put a small number in a row.

**Anything else we need to know?**:
Creating rows needs to be further improved

**Environment**:
- Grafana version: 6.6
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
> I selected "Convert to row" and the entire set of grafana panels got converted to a single row.

Unable to replicate, when I add a new row it adds a new row, nothing gets converted. Rows covers the full width, there is no partial rows. 

> I wanted to put two elements in a row, not the entire page. At the very least I wanted to be able to select what got put in a row, but no!

Add two rows, then move the panels you wish to belong to the second. If you have only one row all panels will belong to that row

**Comment by yellowpattern** [comment]
Let me show you what happens...

Existing dashboard... no rows...

![Screen Shot 2020-01-31 at 2 14 53 am](https://user-images.githubusercontent.com/24280758/73462542-17d03100-43d0-11ea-8361-13e4087007b8.png)

so I want to add something to convert some into rows...

![Screen Shot 2020-01-31 at 2 15 07 am](https://user-images.githubusercontent.com/24280758/73462588-2c142e00-43d0-11ea-864b-9058476fc02f.png)

the row is created...

![Screen Shot 2020-01-31 at 2 15 17 am](https://user-images.githubusercontent.com/24280758/73462623-38988680-43d0-11ea-8865-d11df57d8460.png)

If I then close the row, everything disappears because all of the dashboard's contents have been put into the same row.

![Screen Shot 2020-01-31 at 2 15 27 am](https://user-images.githubusercontent.com/24280758/73462682-4a7a2980-43d0-11ea-8f99-55995db8dabe.png)

**Comment by yellowpattern** [comment]
There's no capability to select which panels go in the row. Everything goes in. I get that row management is a hard UI to get right but I'm not sure that this is the "least surprise" approach.

**Comment by torkelo** [comment]
You need to create 2 rows, then you can just move the panels into what ever row you want. Panels belong to the row above it and down to the next row
