### ISSUE TITLE
server-side rendered chart image legend issues

### ISSUE THREAD

**Issue by jlopp** [grafana/grafana#2185]
If you have a chart and the legend is set to be on the right side rather than underneath, the legend gets rendered on top of the chart if you render it on the server. Example:

http://statoshi.info/render/dashboard/solo/db/messages-received-and-sent?panelId=3&fullscreen&from=now-24h&to=now&width=1000&height=500

**Comment by torkelo** [comment]
Thanks for reporting this, Fixed in master!

**Comment by jlopp** [comment]
Hooray!
