### ISSUE TITLE
Grafana 6.6.0 intergration with Elasticsearch Error

### ISSUE THREAD

**Issue by bardie** [grafana/grafana#21850]
**What happened:**
I cannot be able to access my elasticsearch index. I am getting the error "no such index".
I have tested my Elasticsearch setup with Kibana and i was able to access the index.

**What you expected to happen:**
Index OK. Time field name OK. (Version: 6.4.5)

**How to reproduce it (as minimally and precisely as possible):**
Use the following docker instances:
**Grafana:** grafana/grafana
**Elasticsearch Cluster:** based on docker.elastic.co/elasticsearch/elasticsearch:6.7.2
none
On Grafana, I created a new datasource and added the index as "*", the timestamp is @timestamp

**Other:**
![Screenshot](https://user-images.githubusercontent.com/10991719/73452248-8aaebd00-437a-11ea-8908-c7cbd736c255.png)

On the dashboard i can see data streaming in but i cannot select fields
![image](https://user-images.githubusercontent.com/10991719/73513321-19185280-43fe-11ea-8dcc-eb94185fc4e2.png)

**Environment**
- Grafana version: v6.6.0 - Docker
- Data source type & version: Elasticsearch 6.7.2
- OS Grafana is installed on: Alpine
- User OS & Browser: Linux & Chrome
- Grafana plugins: No plugins installed

**Comment by marefr** [comment]
Works as expected for me in latest master commit (0390b56)

![image](https://user-images.githubusercontent.com/1668778/73535435-d10c2680-4423-11ea-9988-762b848be79c.png)
![image](https://user-images.githubusercontent.com/1668778/73535380-b043d100-4423-11ea-8e28-1ad51df90097.png)

You've probably selected wrong version, should be 7.0+
