### ISSUE TITLE
New Select: input is permanently focused after selecting a value

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21867]
**What happened**:
Seems like after bumping react-select to 3.0.8 there is a regression in the new Select component.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open storybook and go to Basic Select story
2. Choose any of the options from the select
3. Try to blur the input

**Comment by tskarhed** [comment]
Reference to #21638

**Comment by tskarhed** [comment]
Going to make a fix that support multi value too. Current fix does not focus mutli, looking into it.
