### ISSUE TITLE
grafana/toolkit: Unable to run react plugin on linux but does work on windows

### ISSUE THREAD

**Issue by WaleedNaveed** [grafana/grafana#21864]
I am developing a Grafana plugin. I am using 6.3.5 version of grafana. I cloned this code from github and build the grafana using

go run build.go setup
go run build.go setup

I cloned the simple-react-panel code from github. And placed it in the plugin folder and build the plugin using yarn build. After that i start the grafana server and plugin works fine. I have done this on the windows machine.

Now i have to run it on linux machine. I have a grafana 6.3.5 installed on a VM. I cloned the same simple-react-panel plugin in the plugins folder of grafana. After that i build the plugin using yarn build. plugin does get build. Now when i start the grafana server, i can see my plugin but when i click on the plugin i get the error Panel plugin not found: myorgid-simple-panel. In the console i have the error

Error loading panel plugin TypeError: r.PanelPlugin is not a constructor
at Module.eval (module.js:1)
at n (module.js:1)
at eval (module.js:1)
at eval (module.js:1)
at o (system.js:4)
at system.js:4
at system.js:4
at S (system.js:4)
at E (system.js:4)
at system.js:4
Issue is that same plugin works fine with grafana on windows system but does not work on linux system. Grafana does show this plugin as installed when i get the list of installed plugin through grafana-cli.

**Comment by dprokop** [comment]
@WaleedNaveed what version of @grafana/toolkit are you using? Since you are targeting Grafana 6.3.5 you can try toolkit 6.3.2 or 6.4.0. There were a lot of breaking changes since 6.3.5 and that was early days of toolkit too.

**Comment by WaleedNaveed** [comment]
I installed grafana toolkit from [](https://www.npmjs.com/package/@grafana/toolkit). This does work on windows, it is only causing issue on linux (ubuntu) machine

**Comment by dprokop** [comment]
@WaleedNaveed what browser are you using on Ubuntu?

**Comment by WaleedNaveed** [comment]
Ubuntu is on a VM. I access the grafana on windows system by the URL on google chrome. Actually i have not set up development environment on VM. Grafana 6.3.5 is installed on my VM, i just placed the plugin code in the plugins folder and restarted the grafana server.

**Comment by peterholmberg** [comment]
@WaleedNaveed did you run yarn build in your plugin?

**Comment by WaleedNaveed** [comment]
@peterholmberg yes, i did. Actully, i have been able to resolved the issue by using following versions:

grafana/toolkit : 6.4.4
grafana/ui : 6.3.2

May be as i am working with grafana version 6.3.5 so that's why i have to use the older versions of grafana/toolkit and grafana/ui.
