### ISSUE TITLE
Show sum of sums after group by - Grafana Elasticsearch

### ISSUE THREAD

**Issue by SophiePages** [grafana/grafana#21865]
Hello,

I would like that Grafana shows me a sum (or a total) of all the sums that are created after the group by. Is that possible? I wanted to do that with another query but it is not implemented yet. Maybe there is a another way.

Here is my Grafana dashboard with my query:

![prob_grafana_v2_0](https://user-images.githubusercontent.com/60466458/73522680-546c4e80-4409-11ea-89df-305686d45b19.PNG)

Thank you

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Create a separate query without grouping by terms and you'll get the total.

**Comment by SophiePages** [comment]
Thank you. I must do the grouping by terms. My data will not be accurate if I don't. I need to get the last version of each document and the groups by do just that. I will ask my question on your community site.

**Comment by torkelo** [comment]
That is not possible right now, we hope to make it possible later this year with math on existing queries

**Comment by SophiePages** [comment]
Thank you for this information 👍 !
