### ISSUE TITLE
6.6.0 Azure Monitordata source / log analytics authentication error

### ISSUE THREAD

**Issue by chelnak** [grafana/grafana#21868]
**What happened**:
It would appear that there is a regression in how the authentication request to log analytics is being created.

The data source now gives the following error:

```
www-authenticate: Bearer authorization_uri="https://login.windows.net/3aacc835-4b83-483d-841d-cd787f6f1486", error="invalid_token", error_description="The authentication failed because of missing 'Authorization' header."
```

Mitigation was to rollback to 6.5.1

**What you expected to happen**:
Log Analytics queries should work as per 6.5.x

**How to reproduce it (as minimally and precisely as possible)**:
* Upgrade to 6.6.0
* Visit any existing dashboard with log analytics graphs, they will be broken
* Go to data source config, press f12, click test, ensure that you have the log analytics section populated.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Azure Montior
- OS Grafana is installed on: Docker (non ubuntu)
- User OS & Browser: Win 10/ Chrome
- Grafana plugins:
- Others:

**Comment by stevenXarios** [comment]
I came across the same issue after upgrading my Docker containers (I have not seen the issue on my Windows PC).

The solution I came across yesterday was to toggle "Same details as Azure Monitor API" to off. Enter the duplicate details and then save and test

![image](https://user-images.githubusercontent.com/47744931/73534800-eb410700-4419-11ea-8f9a-7b72e783265b.png)

I was then able to toggle this back to on and it continued to work.

**Comment by chelnak** [comment]
@stevenXarios Thanks for your reply. We use provisioning for our datasources so I don't think this would be an appropriate work around.  i'll do some investigation though.

**Comment by chelnak** [comment]
I’ve done some debugging locally and have fixed the issue. The recent changes by @shavonn dont seem to be backwards compatible with azure monitor data sources configured with provisioning. The fix was to re instate the routing logic that was removed.

While working on this issue I also came across a second bug.

When you enter a previously configured data source, it fails to load the subscriptions and workspace. If you watch the traffic flow you can see that the backend server is displaying an error page. It looks like this is because the logic in the ConfigEditor is not populating the URL property in init.. and therefore missing out the proxy/id portion of the request url.

I spent a few hours on this and couldn’t work it out for the life of me. The code flow hits all of the right parts but the props object just doesn’t update.

I’ll submit a PR for the first issue and am happy to include a fix for the second but might need a few pointers.

**Comment by chelnak** [comment]
Done some more digging and am non-the-wiser.

I've pushed a commit here to start some discussion: https://github.com/grafana/grafana/pull/22035/commits/70804c3df1144601c2695d528df10bec8be0c1ca

When you enter a datasource the `getSubscriptions` fails because `props.options.url` is not populated in the constructor. I've tried a few different approaches here and can't get it to update.

In the commit above, I override the url used to grab the subscriptions in `loadSubscriptions`. This works. At this point `props.options.url` is still empty.

However, if you click Load Subscriptions in the UI, it triggers `onLoadSubscriptions` -> `getSubscriptions` -> `loadSubscriptions`. After this chain, `props.options.url` is populated.

In addition, clicking Load Subscriptions will reset the datasources `readOnly` property to false enabling editing/deleting via the UI. This is not what you would want with provisioned datasources.

Maybe I've gone made an am missing something obvious here 🐔

**Comment by shavonn** [comment]
@chelnak I have tested extensively and have not been ale to reproduce this issue. Have you attempted recreating the datasource? I have found that someone having a similar issue after a bug fix was able to resolve the issue by re-entering their credentials or recreating the datasource.

**Comment by chelnak** [comment]
The impacted data source was created with provisioning. It’s used in
multiple graphs so recreating it is going to be the last choice for us.

The datasource is also read-only.

After upgrading to 6.6.x it breaks with the issue I have described.

Have you tested this scenario?

v6.5.3 - configure datasource with provisioning, use same creds for log
analytics & set up a basic graph.

Upgrade to v6.6.x - go to the datasource and click test. Also visit the
graph created in the above step.

Thanks,
Craig

**Comment by yesoreyeram** [comment]
@chelnak - does the error specific to any type of graphs? Like graph, table, third party plugins?

**Comment by chelnak** [comment]
We only really use the built in graphs. So Graph  is as good as any to test
with.

You can also observe this when you hit Test datasource button on the config
page. By looking at the network trace you can see that the back end url
isn’t being built properly.

**Comment by HemendraSingh** [comment]
@marefr This is a major bug in the Azure Monitor data source and affects all those places where we have used Log Analytics.

When can the fix be release?

**Comment by chelnak** [comment]
It is. Glad to see someone else is seeing the same as us!

We are actually stuck on an older version due to another bug that was fixed
in 6.6 but can’t upgrade because of this issue 👎

As I’ve said, if I can I’m more than happy to offer my limited skills to
help push this through if needed.

**Comment by bherrsk** [comment]
I've been following this as I was also impacted. The fix for me was to generate a new secret via the app service principal in AAD and input it in all the data sources. Even then I had to mash the load subscriptions button 5 - 6 times after this until it finally listed them. After that, was no longer a problem.

I had this issue consistently across 3 different environments. 2 running with the application installed directly on guest (Ubuntu 18.04....3 LTS) as well as Grafana running in a container.

**Comment by chelnak** [comment]
Has there been any more investigation in to this?

**Comment by fl-max** [comment]
The workaround linked [here](https://community.grafana.com/t/azure-log-analytics-issue-v6-6-0/25292/2) worked for me.

**Comment by chelnak** [comment]
The workaround in that link has allowed us to upgrade which is good. The UI of the datasource is till bugged though.

Default subscription and Default workspace fields show `No options`.

At last it works now

**Comment by joshhunt** [comment]
@chelnak We've touched a lot of Azure Auth in the 8.0 release and haven't seen any issues in testing regarding this one.

If something pops up, please feel free to reopen or create a new issue!
