### ISSUE TITLE
What does "grafana" mean?

### ISSUE THREAD

**Issue by cheyang** [grafana/grafana#2186]
I was not able to find its meaning in translation tool. It doesn't looks like an English word. What does it mean? :)

**Comment by torkelo** [comment]
It does not mean anything. Its a made up word. Grafana started with some code from the Kibana project (Kibana does mean something), and to honer that heritage I named it Grafana as mix between Graph and Kibana (Graph is spelled Graf in swedish)

**Comment by cheyang** [comment]
thanks very much.

**Comment by mahab339** [comment]
Could you please elaborate more on, or refer to links of Kibana meaning?
@torkelo

**Comment by yamatatsu** [comment]
I found the origin of KIBANA　naming. It's really interesting.
https://discuss.elastic.co/t/the-meaning-of-kibana/89828/2
