### ISSUE TITLE
$__from and $__to don't work in Application Insights datasource

### ISSUE THREAD

**Issue by ChadNedzlek** [grafana/grafana#21860]
**What happened**:
Using a query that uses $__from or $__to used to result in an application insights query that said something like `datetime(2020-01-30T20:00:00Z)`, now it's just a number.  However, that number is meaningless in application insights, and the backend code here https://github.com/grafana/grafana/blob/20faef8de5fbdaa2395d5097e6d3f862b143f5d1/pkg/tsdb/azuremonitor/macros.go still seems to try to do the datetime replacement.

this query `results | where timesamp>$__from | summarize count() by bin(timestamp, 1m)` returns a "metrics request error" because the number being sent by $__from has no context in AI.

**What you expected to happen**:
The query should return fine, with a pretty boring time series.

**How to reproduce it (as minimally and precisely as possible)**:
Create an Azure Monitor data source pointing to an App Insights instance, change to raw query, and paste  `results | where timesamp>$__from | summarize count() by bin(timestamp, 1m)`

**Anything else we need to know?**:
This appears to have been a change in 6.0, since I'm pretty sure this worked before.  This change is highly suspect: https://github.com/grafana/grafana/issues/1909.

Several queries need the __from and __to, especially if they are using (make-series).  $__timeFilter() wasn't broken, but the make-series command needs the from and to values individually.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Azure Monitor - built in
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None

**Comment by marefr** [comment]
@ChadNedzlek please use `$__timeFrom` and `$__timeTo`, see [docs](https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/#azure-log-analytics-macros) for reference. We had to change this since `$__from` or `$__to` clashed with Grafana's [global built-in variables](https://grafana.com/docs/grafana/latest/reference/templating/#time-range-variables)

**Comment by ChadNedzlek** [comment]
That doesn't work, I get "Metrics Request Error". The code I linked doesn't accept those values.  The App Insights source is badly broken.

**Comment by ChadNedzlek** [comment]
![image](https://user-images.githubusercontent.com/11790765/73563657-c1381680-4412-11ea-959d-b870d6b03817.png)

**Comment by ChadNedzlek** [comment]
Right now I have to do some weird calculations like this:
```
let r = requests | where $__timeFilter();
let f = toscalar(r | summarize min(timestamp));
let t = toscalar(r | summarize max(timestamp));
```

But even that's not 100% correct, since it won't fill out past whatever the most recent value is or before the earliest, leading to graphs with weird dangling lines that don't represent reality (if something dies and stops accepting requests, we'll never get a "zero" value)

**Comment by ChadNedzlek** [comment]
I made a PR... the fix should be pretty simple... just accept the two new fields in that file and I'll be unblocked.

**Comment by ChadNedzlek** [comment]
This is a really crippling problem for a lot of our scenarios, and I think the fix is pretty simple... Is there something more I can do to help nudge this along?
