### ISSUE TITLE
New Select: Can't do backspace when item is selected

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#21872]
**What happened**:
Nothing

**What you expected to happen**:
Either for the entire option to disappear or one letter

**How to reproduce it (as minimally and precisely as possible)**:
Go to Storybook and Forms/Select and use the create custom value version
1. Create custom value and make sure it is select (try to blur the select etc.)
2. Click the select input and try to press backspace

**Comment by tskarhed** [comment]
This is true for any kind of selected item. What's the expected behaviour on backspace?

**Comment by peterholmberg** [comment]
There's a prop `isClearable` that we set as false by default. If you change this to true in your component it will clear the selected value if you hit backspace.

**Comment by tskarhed** [comment]
The internal state for Select has `focusedValue: null` regardless of what happens for some reason. Which makes it not remove the value.
https://github.com/JedWatson/react-select/blob/3c7de0de52826fe74d303a01475c43fe88256156/packages/react-select/src/Select.js#L1181

**Comment by tskarhed** [comment]
Closing this after a couple of discussions, as this is the expected behaviour
