### ISSUE TITLE
Advanced query builder with conditionals expressions.

### ISSUE THREAD

**Issue by fabionaspolini** [grafana/grafana#21878]
**What would you like to be added**:

I would like to increase query builder engine syntax.

**Why is this needed**:

When use multi-selection variables don't is possible to build a performative query, because the query builder include all items into string interpolated.
Even with the "Custom all value" feature don't resolve my problem.

In the fictitious example bellow, I need retrieve all cities from states:

![image](https://user-images.githubusercontent.com/8163004/73562262-85647780-4439-11ea-9cec-713877c48226.png)

Current Grafana metric sql:

```sql
select *
from city
where stateid in ($states)
order by name;
```

Generated SQL when select all:

```sql
select *
from city
where stateid in ('AL','KS','RJ','SC','SP','TX')
order by name;
```

I would like to have the ability to manipulate generation command text query removing the "where" clause, generating this output query:

```sql
select *
from city
order by name;
```

But continue to include options when selecting 1 or N-1 values.

```sql
select *
from city
where stateid in ('AL','KS')
order by name;
```

**Proposed implementation**

Interop query parser with JS syntax, example:

```sql
select *
from city
${ states.allSelected ? "" : "where stateid in ($states)" }
order by name;
```

This example I use a simple ternary expression wich makers query generation much more powerful and flexible.

Execution pipeline must execute JS expression to transform
...${ states.allSelected ? "" : "where stateid in ($states)" }...
in
...where stateid in ($states)"...

and send new output to current string interpolation processor, to transform in:
...where stateId in ('AL','KS')...

Idea is use another functions for JS language, like switch or more complex block.

```js
select *
from city
where stateId = ${ switch(states[0]) {
                     case "AL": return 1;
                     case "KS": return 2;
                     default: return ""; } }


${
  if (states.length === 0) return;
  var firstState = states[0];
  if (a === "AL") return "and stateName = 'Alabama'";
  return "and stateName <> 'Alabama'";
}
order by name;
```

In my real use cases, this will greatly increase performance and result in a great experience for my users with dashboards.

Notes: At another Issue #21856 I requested a change that will need to move the builder from querying to the backend.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
