### ISSUE TITLE
Failed to start renderer plugin: Unrecognized remote plugin message

### ISSUE THREAD

**Issue by eloo** [grafana/grafana#21874]
**What happened**:
Hello,

we have currently an issue with image rendering for alerts.
It started that we are getting timeouts while rendering the images for the alerts. 
The error message was like this:
```
Failed to render and upload alert panel image." logger=alerting.notifier ruleId=9 error="Timeout error. You can set timeout in seconds with &timeout url parameter"
```

After a short research i have seen that its recommended to switch to the image renderer plugin.
So i've tested this also but im now running in the following error:
```
Stopped RenderingService" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
```

This looks like there is major problem with the plugin in our setup. More details for the setup are noted below

**What you expected to happen**:
That my alert graphs are renderer properly and are attached to my notification

**How to reproduce it (as minimally and precisely as possible)**:
Not sure if this is reproducible on generic systems

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Prometheus 2.11.1
- OS Grafana is installed on: CloudFoundry using the binary directly
- User OS & Browser: n/a
- Grafana plugins: grafana-piechart-panel, grafana-clock-panel, grafana-image-renderer
- Others: 
  - We are using only env variables for configuration. 
  - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=local

I hope i've stated my issue properly and we can find a solution.
Thanks

**Comment by marefr** [comment]
What version of image render plugin?

**Comment by eloo** [comment]
Should be the latest version (1.0.9) because i was installing it during deployment (using the env variable)

**Comment by marefr** [comment]
@eloo related to https://github.com/grafana/grafana-image-renderer/#known-issue-having-ipv6-disabled?

**Comment by eloo** [comment]
Yes this could may be the reason.
It looks like our platform is not supporting IPv6, yes. 
With the debug option enabled i see the same error 👍 
I'm looking to get this fixed. ATM we are unable to get rendered images because we are also affected by #9196 :(

**Comment by marefr** [comment]
Closing this. Please continue the discussion in https://github.com/grafana/grafana-image-renderer/issues/48 regarding IPv6. You may be able to use https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service?
