### ISSUE TITLE
Variable in dashboard duplicate via "Save as ..." keep value from previous dashboard

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#21870]
**What happened**: Variable in dashboard duplicated keep value from the previous dashboard (even after change/save)

**What you expected to happen**: Variable should be change if a update them

**How to reproduce it (as minimally and precisely as possible)**:

1. Create dashboard named "**dashboard-1**"
2. Add variable "**test**" (type constant) with value "**dashboard-1**"
3. Create panel "Text" with title "**$test**" and content "**$test**" (panel should display "**dashboard-1**"
4. Save "**dashboard-1**"
5. Use "Save as ..." feature and create "**dashboard-2**" from "**dashboard-1**"
6. Set "**dashboard-2**" to variable "**test**" in "**dashboard-2**" (refresh dashboard, panel should display "**dashboard-2**")
7. Save "**dashboard-2**" 
8. Go back to "**dashboard-1**" (panel should display "**dashboard-1**")
9. Go back to "**dashboard-2**" (panel display "**dashboard-1**" -> 💥 )

**Environment**:
- Grafana version: v6.5.2 (commit: 742d165)
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS / Chrome 79

**Comment by marefr** [comment]
Works as expected for me on v6.6.0. Tested with:
https://play.grafana.org/d/ELwa5gUZz/21870-dashboard-1?orgId=1
https://play.grafana.org/d/KumEcg8Zk/21870-dashboard-2?orgId=1

Please remember to save current variables when saving dashboard-2 after changed test constant for dashboard 2. 
![image](https://user-images.githubusercontent.com/1668778/73534805-4e369c00-4422-11ea-8697-e45fe5d8a483.png)

**Comment by Eraac** [comment]
100% my fault, but UI is confusing, if you go to variable (in dashboard-02), the preview display "dashboard-02", or the text panel display "dashboard-01"
![image](https://user-images.githubusercontent.com/5497623/73725394-93faa980-472d-11ea-821a-83544f2381fc.png)
