### ISSUE TITLE
negative transform not working as expected

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#21887]
**What happened**:
I used the Visualisation override to apply a "negative y" transformation. The graph changed but nothing was visible in negative y. If I also add "y-axis 2" then it works as expected.

**What you expected to happen**:
To see disk rates show up as -5 MBs

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6
- Data source type & version: Influxdb 1.7.9
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS & Chrome
- Grafana plugins:
- Others:

**Comment by yellowpattern** [comment]
<img width="1420" alt="Screen Shot 2020-02-02 at 2 14 35 pm" src="https://user-images.githubusercontent.com/24280758/73602460-52042300-45c8-11ea-9b15-239af7d59348.png">
<img width="1417" alt="Screen Shot 2020-02-02 at 2 15 23 pm" src="https://user-images.githubusercontent.com/24280758/73602461-52042300-45c8-11ea-97be-5c0bc6c72800.png">
<img width="1415" alt="Screen Shot 2020-02-02 at 2 14 51 pm" src="https://user-images.githubusercontent.com/24280758/73602462-52042300-45c8-11ea-8b97-9a9b51bd682d.png">
<img width="1419" alt="Screen Shot 2020-02-02 at 2 27 47 pm" src="https://user-images.githubusercontent.com/24280758/73602463-53cde680-45c8-11ea-9bd4-67fcb7cc3599.png">

**Comment by torkelo** [comment]
Cannot replicate this. 

I expect that you have a left Y min value set to 0, but not on the right Y

**Comment by yellowpattern** [comment]
This bug has been fixed (maybe not directly) as I can no longer reproduce this problem with 6.6.2.
