### ISSUE TITLE
Allow disabling GettingStarted panel for new users

### ISSUE THREAD

**Issue by dpotapov** [grafana/grafana#21881]
**What would you like to be added**:

A setting in Grafana to disable GettingStarted panel for new users.

**Why is this needed**:

I'm dynamically creating orgs, dashboards and users (with Admin permissions) in Grafana. In my scenario new users are not supposed to perform any of the tasks that GettingStarted panel advises to do: datasources, dashboards, apps and plugins are already pre-defined, users are coming from LDAP.

Also in my case I have a custom home dashboard and I do not want the GettingStarted panel to mess with it (the way how it dynamically inserts into a dashboard breaks the panel layout).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
