### ISSUE TITLE
Docs feedback: /reference/timerange.md

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#21886]
This page is showing the old time range selector

**Comment by RobinJoe** [comment]
The time range [docs for the dashboard](https://grafana.com/docs/grafana/latest/reference/timerange/) screencaps do look like they show an older interface. It looks like the most recent UI developments can be found in this PR https://github.com/grafana/grafana/issues/2417 

Documentation changes for Grafana 7 might bring a fix to this issue.

**Comment by oddlittlebird** [comment]
They will. I am going to try and rewrite this whole thing tomorrow, but at the very least it needs to be updated before 7.0.
