### ISSUE TITLE
left y-axis shows negative values when only right should

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#21888]
**What happened**:
When I enable "Stacking", the left axis gets negative y values when only the right should

**What you expected to happen**:
For the left y-axis to be untouched and for the stacked values to only impact the right y-axis.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6
- Data source type & version: influxdb 1.7.9
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS, Chrome
- Grafana plugins:
- Others:

**Comment by yellowpattern** [comment]
<img width="1417" alt="Screen Shot 2020-02-02 at 4 05 40 pm" src="https://user-images.githubusercontent.com/24280758/73603406-4c153e80-45d6-11ea-8131-294a8ba1c5c9.png">
<img width="1426" alt="Screen Shot 2020-02-02 at 4 05 53 pm" src="https://user-images.githubusercontent.com/24280758/73603407-4c153e80-45d6-11ea-8e4e-3db8c1b9185d.png">

**Comment by torkelo** [comment]
if you have stack enabled you need to also change the stack group for the Y-axis 2 series (you can do this in the style overrides section, hit plus button and change stack group)

**Comment by yellowpattern** [comment]
Using this is not always necessary as I have others where it works correctly. Why is the behaviour inconsistent between different graphs?
