### ISSUE TITLE
external templating query source

### ISSUE THREAD

**Issue by williamjoy** [grafana/grafana#2188]
Hi @torkelo , 
Is it feasible that grafana can configure a HTTP call to query templating results from external http server?

Like
```
http://extenal-inventory.example.com/?query=datacenter=$datacenter&role=$role
```

Grafana query from external system and parse the result, of course it should support cascading templating 

Thanks :)

**Comment by nickman** [comment]
I can safely say yes. I use grafana 2 and OpenTSDB/Bosun and I wanted
cascading self populating templating drop downs. A simple java bridge
mimics the Graphite API but resolves the transformed queries against Bosun.

Works nicely.

**Comment by mtanda** [comment]
+1

**Comment by mtanda** [comment]
I create datasource plugin for this issue.
https://github.com/mtanda/datasource-plugin-templating_json

And, there is generic datasource plugin.
https://github.com/grafana/datasource-plugin-genericdatasource

By external datasource plugin support, anyone can create datasource for their requirement, and easily integrate it to Grafana.

**Comment by mtanda** [comment]
@torkelo I think this issue can be closed.
