### ISSUE TITLE
dial tcp: lookup smtp.google.de on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by Maxinger15** [grafana/grafana#21885]
**What happened**:
Grafana can't resolve smtp.gmail.com
If I want to send a test alert email I get this error:

lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Failed to send notification to email addresses: ....@gmail.com: dial tcp: lookup smtp.google.de on 127.0.0.11:53: no such host"

I don't know why he want to use 127.0.0.11 as a dns server. 
Does anyone know how I can fix this?

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Prometheus 2.0
- OS Grafana is installed on: Docker on Ubuntu Server

My yaml:
`version: "2"

networks:
  webv2:
    external:
      name: webv2
  #prom_intern:
    #internal:
      #name: prom_intern
      
services:
  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - /home/max/prometheus/monitor/:/etc/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9091:9090
    networks:
     #- prom_intern
     - webv2
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      #- --collector.filesystem.ignored-mount-points
      #- "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
     - "9100:9100"
    networks:
     #- prom_intern
     - webv2
#    network_mode: host
  grafana:
    image: grafana/grafana
    networks:
     #- prom_intern
     - webv2
    #environment:
     #- GF_PATHS_CONFIG=/etc/conf/grafana.ini
    volumes:
      - /home/max/dockerData/grafana/grafana_data:/var/lib/grafana
      - /home/max/dockerData/grafana/provisioning/:/etc/grafana/provisioning/
      - /home/max/dockerData/grafana/config/custom.ini:/etc/grafana/grafana.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`....`)"
      - "traefik.http.routers.grafana.entrypoints=web-insecure"
      - "traefik.http.routers.grafana.middlewares=redirect@file"
      - "traefik.http.routers.grafana-secured.rule=Host(`....`)"
      - "traefik.http.routers.grafana-secured.tls=true"
      - "traefik.http.routers.grafana-secured.tls.certResolver=main"
      - "traefik.http.routers.grafana-secured.entrypoints=web-secure"
      - "traefik.docker.network=webv2"
      - "traefik.http.services.grafana.loadBalancer.server.port=3000"
    depends_on:
      - prom
      
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8000:8080
    networks:
      #- prom_intern
      - webv2
    restart: always
    
  alertmanager:
    image: prom/alertmanager
    volumes:
      - /home/max/dockerData/alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093
    networks:
      #- prom_intern
      - webv2
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'`

**Comment by peterholmberg** [comment]
This does not look like an issue with Grafana but rather something that's up with your config. 
```
I don't know why he want to use 127.0.0.11 as a dns server.
Does anyone know how I can fix this?
```
could this be part of the problem?

For future reference, when you have a question about configuration or anything else related to grafana. Please post these on community.grafana.com.

**Comment by aascedu** [comment]
How did you fix alertmanager to be able to talk somewhere else than on 127.0.0.11:53 ??? I have the same issue
