### ISSUE TITLE
Visualize Encoded Chars in Strings

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#21899]
I'm using Grafana to display some data stored in InfluxDB, I've got a sting with some encoded characters, line tabs (\t) and New Line (\n).

This is the field value (note \n and \t)
```
INSERT INTO @sys_info ( cpu_count, server_memory, sku, engine_edition, hardware_type, total_storage_mb, available_storage_mb, uptime )\n\tSELECT\tcpu_count,\n\t\t\t(SELECT total_physical_memory_kb FROM sys.dm_os_sys_memory) AS server_memory,\n\t\t\tCAST(SERVERPROPERTY('Edition') AS NVARCHAR(64)) as sku,\n\t\t\tCAST(SERVERPROPERTY('EngineEdition') as smallint) as engine_edition,\n\t\t\tCASE virtual_machine_type_desc\n\t\t\t\tWHEN 'NONE' THEN 'PHYSICAL Machine'\n\t\t\t\tELSE virtual_machine_type_desc\n\t\t\tEND AS hardware_type,\n\t\t\tNULL,\n\t\t\tNULL,\n\t\t\t DATEDIFF(MINUTE,sqlserver_start_time,GETDATE())\n\tFROM\tsys.dm_os_sys_inf
```

This is my desired output (a properly formatted text)
```
INSERT INTO @sys_info ( cpu_count, server_memory, sku, engine_edition, hardware_type, total_storage_mb, available_storage_mb, uptime )
	SELECT  cpu_count,
			(SELECT total_physical_memory_kb FROM sys.dm_os_sys_memory) AS server_memory,
			CAST(SERVERPROPERTY('Edition') AS NVARCHAR(64)) as sku,
			CAST(SERVERPROPERTY('EngineEdition') as smallint) as engine_edition,
			CASE virtual_machine_type_desc
				WHEN 'NONE' THEN 'PHYSICAL Machine'
				ELSE virtual_machine_type_desc
			END AS hardware_type,
			NULL,
			NULL,
			 DATEDIFF(MINUTE,sqlserver_start_time,GETDATE())
	FROM  sys.dm_os_sys_inf
```

I'm currently showing this kind of value inside a table panel, with a max of one value selected and with all the columns hidden except for the one that contains this text)

I've looked around for custom visuals or workaround to this kind of problem but didn't find anything so far, if something exists I'm willing to try it.

**What would you like to be added**:
I would like to have a visual (a new one, or an additional option in an existing one), that can interpret the escaped chars and show them properly.
Otherwise, a replace function which accepts special chars will achieve a similar result

**Why is this needed**:
I will allow Grafana to properly display encoded text.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
