### ISSUE TITLE
f.getRuleSeverity is not a function

### ISSUE THREAD

**Issue by WaleedNaveed** [grafana/grafana#21897]
I have following version:

Grafana : 6.3.5
Grafana ToolKit : 6.4.4
Grafana UI: 6.3.2

I am working on a linux (ubuntu) machine. I got the react plugin from github. I have managed to compile it and is running fine on grafana. Now, i have to use syncFusion library in my plugin, i have obtained the library from https://ej2.syncfusion.com/react/documentation/smithchart/getting-started/. Now when i compile the plugin using "yarn build" i get the following error

yarn run v1.21.1
$ grafana-toolkit plugin:build
✔ Cleaning
✔ Preparing
✔ Prettier check
⠋ Linting

  Trace: TypeError: f.getRuleSeverity is not a function
      at /aedata/ae/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:179:44
      at Array.forEach (<anonymous>)
      at /aedata/ae/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:177:34
      at step (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:136:27)
      at Object.next (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:117:57)
      at fulfilled (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:107:62)
      at /aedata/ae/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:117:57)
      at rejected (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:108:69)
✖ f.getRuleSeverity is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The plugin was compiling before using syncFusion library. What can be the possible issue ? I have to use the syncFusion library because need smithChart in my plugin and i am using smithChart from syncFusion library.

**Comment by peterholmberg** [comment]
Hi @WaleedNaveed ! Do you mind sharing a link to your repository if possible?

**Comment by ryantxu** [comment]
I think this is fixed in master and will be included in the next point release

**Comment by marefr** [comment]
Related to #21785?

**Comment by WaleedNaveed** [comment]
Thanks for your help. I got it resolve my using canary version of grafana/toolkit. 
https://www.npmjs.com/package/@grafana/toolkit/v/6.7.0-pre-c140d110c6
