### ISSUE TITLE
Always Loading Bar on Top After Adding to Home Screen iOS

### ISSUE THREAD

**Issue by orcunbaslak** [grafana/grafana#21905]
**What happened**: I use grafana on iPhone and iPad mostly. When I click the "Add to Home Screen" button, an icon appears. When I click it; grafana shows as usual however there's always a loading bar at the top. Since there is a loading bar; it also displays the URL which under normal circumstances it doesn't so Grafana doesnt fit properly.
![Sample_Grafana](https://user-images.githubusercontent.com/12577988/73700197-ed93b180-46f6-11ea-8acc-153139cd9c52.png)

**What you expected to happen**: Grafana should fit to screen perfectly without a loading bar and URL at the top.

**How to reproduce it (as minimally and precisely as possible)**:
Well, you can try your own grafana installation. I'm not sure if this happens only on mine. Don't know any other grafana instances to check.

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.6.0
- Data source type & version: InfluxDb
- OS Grafana is installed on: Debian Docker
- User OS & Browser: iOS Safari
- Grafana plugins: None
- Others:

**Comment by orcunbaslak** [comment]
I came across the following blog post.
https://forums.developer.apple.com/thread/123486

I think the issue is related to iOS13 and Grafana needs a .webmanifest file to work properly on iOS13.

Thanks,

**Comment by dprokop** [comment]
@orcunbaslak thanks for reporting this. Unfortunately Grafana is not a PWA hence you are experiencing this issue. We currently don't have plans to make Grafana a PWA so I'm gonna leave this issue open and see if there is some more interest from the community.

**Comment by orcunbaslak** [comment]
I’m not a developer but I’m not sure we have to be defining Grafa as a PWA to implement such issue.

https://medium.com/dev-channel/how-to-add-a-web-app-manifest-and-mobile-proof-your-site-450e6e485638

This how-to here tells that in order to add a web manifest we just need a head tag in html and a manifest.json

I’d like to test it out my myself but I don’t know how can I edit the code to add a new header tag. I’m using nginx as a proxy so I can redirect manifest.json to a file on my disk.

Can you tell me what file should I edit to add the header tag required?

Best,

**Comment by orcunbaslak** [comment]
I actually tried nginx's ngx_http_sub_filter module to alter the html code for <link rel="manifest" href="manifest.json" /> and created an alias for manifes.json file. 

It worked! No more top bar!

**Comment by marefr** [comment]
@orcunbaslak you want to update this [file](https://github.com/grafana/grafana/blob/master/public/views/index-template.html). If you're interested to work on it you may open a PR and we can review/discuss it further to see if this is something we can accept.

**Comment by Park0** [comment]
I created a simple PR that has the bare minimum.

**Comment by Park0** [comment]
@marefr Any comment on my PR?

**Comment by dugite-code** [comment]
> I actually tried nginx's ngx_http_sub_filter module to alter the html code for and created an alias for manifes.json file.
> 
> It worked! No more top bar!

For the sanity of future searches, for my Android phone I did the following changes to Grafana

Nginx config
```
sub_filter </head>
  '</head><link rel="manifest" href="/public/manifest.json">';
sub_filter_once on;
```

Then I added a volume to docker compose
```
    volumes:
      - ./volumes/manifest.json:/usr/share/grafana/public/manifest.json:ro
```

manifest.json
```
{
  "name": "Grafana",
  "short_name": "Grafana",
  "description": "Graphs for everyone everywhere anyhow",
  "start_url": "/",
  "background_color": "#000000",
  "theme_color": "#0f4a73",
  "display":"standalone",
  "icons": [{
    "src": "public/img/fav32.png",
    "sizes": "32x32",
    "type": "image/png"
  }]
}
```
