### ISSUE TITLE
[BUG][6.6.0] - Alert Images not working on slack notifications.

### ISSUE THREAD

**Issue by gkope** [grafana/grafana#21904]
**What happened**:

Alert Notifications Image are not working when upgrading to `6.6.0`.

You can see in this image that the alerts are appearing without images:
![image](https://user-images.githubusercontent.com/3788237/73692679-8d2f5080-46b3-11ea-9feb-afebf3041ff6.png)

My notification screen configuration:
![image](https://user-images.githubusercontent.com/3788237/73692740-b18b2d00-46b3-11ea-91af-b4554ecaa55b.png)

My env variables:
```
GF_EXTERNAL_IMAGE_STORAGE_PROVIDER: s3
GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET: <bucket_name>
GF_EXTERNAL_IMAGE_STORAGE_S3_PATH: prod/
GF_EXTERNAL_IMAGE_STORAGE_S3_REGION: us-east-1
```

**What you expected to happen**:

Images appearing on the slack notification channel

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade to version 6.6.0 and see your alerts images stop working.

**Anything else we need to know?**:

**Environment**: Production
- Grafana version: 6.6.0
- Data source type & version: Prometheus / 2.15.1
- OS Grafana is installed on: CoreOS + Kubernetes
- User OS & Browser: MAC + Chrome
- Grafana plugins: 
- Others:

**Comment by xandr2** [comment]
I have the same issue but it doesn't work only when datasource are Prometheus or Victoriametrics. When graph uses other DS type it works good.

**Comment by naumfujimori** [comment]
Hey guys same issue reported by me using docker 6.6.1 and 6.7pre
https://github.com/grafana/grafana/issues/21993

Also I collected the webhook info and grafa os not adding the image url to send to slack API...:(

**Comment by anthosz** [comment]
Hi,

More/less related issue on my side also with the last version as this day.

When we use slack, the image sent is alway a sample image instead to the correct image of the alert.

**Comment by gkope** [comment]
We started using Grafana Image Renderer with Grafana 7.0.x and now everything works fine ;)
