### ISSUE TITLE
[BUG][6.6.0] Bar Gauge > ERROR: Cannot read property 'dataFrame' of undefined

### ISSUE THREAD

**Issue by baur** [grafana/grafana#21911]
**What happened**:
Bar Gauge - error *Cannot read property 'dataFrame' of undefined* 
![image](https://user-images.githubusercontent.com/2898361/73733336-fd96aa00-4765-11ea-8c0c-6a5e5655ce27.png)

Error not gone out and data not rendered even if SQL Query returns data with another variable or by edit query string

Error  gone out if refresh page by F5

**What you expected to happen**:
Just empty Bar Gauge (no error) and Bar Gauge with data when was selected another variable which returns some data without refresh (F5)

**How to reproduce it (as minimally and precisely as possible)**:
SQL Query with empty data (by edit query or by select variable)

**Anything else we need to know?**:
this errror not gone while refersh page

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: SQL Server
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Bar Gauge
- Others:

**Comment by dprokop** [comment]
@mckn isn't this similar to https://github.com/grafana/grafana/pull/21791

**Comment by mckn** [comment]
> @mckn isn't this similar to #21791 ?

Yupp - sounds like it :)

**Comment by mckn** [comment]
This is fixed in the version that is in master. It will be released in the `6.6.1` version. Thanks for reporting it.
