### ISSUE TITLE
KairosDB Support

### ISSUE THREAD

**Issue by masaori335** [grafana/grafana#2191]
KairosDB Datasource Plugin is in [kariosdb](https://github.com/grafana/grafana/tree/kariosdb) branch.
It supports templating feature now. What do we need to get it into master branch? 
( Related to issue #1276 )

**Comment by torkelo** [comment]
@masaori335 think it is close. Maybe some docs?

**Comment by torkelo** [comment]
merged kairosdb branch

**Comment by masaori335** [comment]
Thanks!
