### ISSUE TITLE
[BUG][6.6.0] making dashboard editable leads to 404 page

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#21910]
**What happened**:
We recently updated from Grafana 6.5.1 to 6.6.0 and since then are experiencing this bug:
Dashboard editors are routed to an invalid url when they make a dashboard editable. The invalid url contains the subpath */grafana* two times, which ist wrong.
They see this page after they set the dashboard to "editable" and click "save" to make it happen:
![07](https://user-images.githubusercontent.com/11644606/73733798-e2fc0b00-473c-11ea-99a8-dde09930f2a0.png)
Downgrading to Grafana 6.5.1 eliminated the problem, so something is broken in 6.6.0.
Please see the step-by-step description and images in **how to reproduce**.

**What you expected to happen**:
Dashboard editors should be routed to the correct url containing the subpath */grafana* only once, so they can seamlessly start editing the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Please take a look at the following screenshots which I took while trying to make a simple dashboard editable again.
At the start, the dashboard is not editable (Marker **1** onscreen):
![01](https://user-images.githubusercontent.com/11644606/73734279-ada3ed00-473d-11ea-8ad0-4d33031584f2.png)
![02](https://user-images.githubusercontent.com/11644606/73734288-b1377400-473d-11ea-848d-bb34767ad0e1.png)
![03](https://user-images.githubusercontent.com/11644606/73734300-b399ce00-473d-11ea-9b09-800782ac9443.png)
![04](https://user-images.githubusercontent.com/11644606/73734303-b5fc2800-473d-11ea-883c-a582d96c0079.png)
After setting "editable" to true and entering a commit message, this happens:
![05](https://user-images.githubusercontent.com/11644606/73734308-b7c5eb80-473d-11ea-82fa-368d1d579ad7.png)
The editor is being routed to a url which starts with */grafana/grafana* all of a sudden which is wrong (Marker **2** onscreen).
Manually removing this duplicate subpath, you can see the dashboard indeed is editable (Marker **3** onscreen):
![06](https://user-images.githubusercontent.com/11644606/73734312-b98faf00-473d-11ea-9b73-7e9e0627e332.png)

**Anything else we need to know?**:
The logfile contains the api call to the *dashboards* resource that was made upon clicking on "save":
`t=2020-02-04T10:05:24+0100 lvl=info msg="Request Completed" logger=context userId=5 orgId=1 uname=[REMOVED for github issue] method=POST path=/api/dashboards/db/ status=200 remote_addr=[REMOVED for github issue] time_ms=7 size=127 referer="https://[REMOVED for github issue]/grafana/d/RZ2MoO8Wz/6-6-0-bug?editview=settings&orgId=1"`

Strangely, everything is working the other way around (disabling the "editable" setting and saving the dashboard).

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: -
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Ubuntu (Firefox & Chrome)
- Grafana plugins: -
- Others:
  - 2 Grafana instances behind reverse proxy (apache httpd)
  - OAuth Keycloak, therefore "root_url" is set including */grafana* subpath
  - setting *serve_from_sub_path* to true did not change anything

**Comment by baur** [comment]
It happens when use *root_url* in custom.ini

**Comment by sspieker** [comment]
Hi @baur , indeed I've set this to *https://xxx/grafana*
There is no problem before version 6.6.0, that's what's bugging me. As we use Keycloak OAuth, I needed to set this in order to create a valid callback.

**Comment by sspieker** [comment]
Maybe this is related to #21652 ? I don't experience problems logging in, but that may be because of configurations on our side (Keycloak OAuth).

**Comment by dprokop** [comment]
@sspieker thank's for reporting this issue. I have just reproduced it and looking into it
