### ISSUE TITLE
Do not enforce regex escaping for variables in variable queries

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#21919]
So one has influx DB server with thousands of servers. E.g.:
```
server1.example.com
server2.example.com
server3.example.com
server4.example.com
```

So you create a variable like this:
![image](https://user-images.githubusercontent.com/5955795/73754671-66355500-476d-11ea-8370-a9871ea2da53.png)

And now `$host` can be used in different queries. Let's create another variable for interface while reusing `$host` variable in variable's query:
![image](https://user-images.githubusercontent.com/5955795/73755207-5c602180-476e-11ea-80b1-b2da8953433e.png)

And this pop-up greets you:
![image](https://user-images.githubusercontent.com/5955795/73755393-9f21f980-476e-11ea-8f53-dc3db007f4f6.png)

If you look closely at network request in browser, and decode URL query from Grafana, you will notice that this variable is being automatically escaped for regex into `server1\.example\.com`.

So none of these works:
```
$host
'$host'
"$host"
```
and this is the only approach that works:
```
/^$host$/
```
Can this be somehow not enforced? Regex is always slower than simple comparison, so why forcing regex in this case? Note that this issue is not relevant to InfluxDB queries in dashboard panels.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
