### ISSUE TITLE
Annotations fail validation when step field is removed

### ISSUE THREAD

**Issue by mickael-carl** [grafana/grafana#21914]
**What happened**:
When upgrading from 6.3.0 to 6.6.0, in an annotation using a Prometheus datasource type, removing an existing value for the query step result in a broken annotation with the following error:
```
Annotation Query Failed
Invalid interval string, expecting a number followed by one of "Mwdhmsy"
```

**What you expected to happen**:
The annotation step should just use the default value of 60s

**How to reproduce it (as minimally and precisely as possible)**:
On an empty dashboard, create an annotation with Prometheus type datasource.
Set the query to anything really (`up` works)
Set the step value to 5m and save
Re-edit the annotation, remove the step value, leaving the field empty (which should default to 60s) and save
Create a panel -> error

**Anything else we need to know?**:
The error seems to stem from the json model: a step field is added when filling in `5m` and then set to `""` when the value is removed, which is then indeed invalid because not a timeframe.
Removing said field from the json and saving fixes the annotation

**Environment**:
- Grafana version: Grafana v6.6.0 (5c11bbdfb4)
- Data source type & version: Prometheus v2.15.2
- OS Grafana is installed on: Docker in RHEL
- User OS & Browser: Firefox 73.0b6 on MacOS
- Grafana plugins: -
- Others:

**Comment by peterholmberg** [comment]
@mickael-carl which panel are you using here?

**Comment by mickael-carl** [comment]
@peterholmberg a graph (technically, I hit the `Add Query` button which adds a graph panel by default).
