### ISSUE TITLE
[Feature request] [Playlists] Add parent folder in dashboard selection

### ISSUE THREAD

**Issue by BasvanH** [grafana/grafana#21928]
Hello,

When creating/editting a playlist, you see a list of availeble dashboards. We have same dashboard names in different folders for different purposses. This makes it hard to select the correct dashboard. We are using tags for this, but still it would help if the parent folder is visually added to the view.

So it will look like something like this:
![image](https://user-images.githubusercontent.com/1708136/73823552-c8876780-47f8-11ea-839f-88026d3d83b6.png)

Thanks!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by BasvanH** [comment]
Created a discussion: https://github.com/grafana/grafana/discussions/37674
