### ISSUE TITLE
Image rendering: Doesn't work when using serve_from_sub_path

### ISSUE THREAD

**Issue by holiiveira** [grafana/grafana#21925]
**What happened**:

The image sent by e-mail is not the graphic that is alerted. Example:

![grafana-01](https://user-images.githubusercontent.com/4368491/73777730-beb62380-4768-11ea-9e28-0c1c5ecac2ae.png)

**What you expected to happen**:

The image sent should be from the graphic with alert.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Occurs after update, as follows:

```
Start-Date: 2020-02-03  09:03:40
Commandline: apt install grafana
Upgrade: grafana:amd64 (6.5.2, 6.6.0)
End-Date: 2020-02-03  09:03:44
```

In the email notification channel, you are selected to include the image. A log summary:

```
t=2020-02-04T15:48:01-0300 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=5 newState=pending prev state=ok
t=2020-02-04T15:50:07-0300 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=5 newState=alerting prev state=pending
t=2020-02-04T15:50:07-0300 lvl=info msg=Rendering logger=rendering renderer=phantomJS path="d-solo/n41K9ndZk/xxxxx-application-server?orgId=1&panelId=10"
t=2020-02-04T15:50:13-0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/datasources/proxy/8/_msearch status=502 remote_addr=127.0.0.1 time_ms=128 size=0 referer="http://127.0.0.1:3000/grafana/d/eY2it3vZk/centro-de-inicio?orgId=1&refresh=5s"
t=2020-02-04T15:50:13-0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/datasources/proxy/8/_msearch status=502 remote_addr=127.0.0.1 time_ms=129 size=0 referer="http://127.0.0.1:3000/grafana/d/eY2it3vZk/centro-de-inicio?orgId=1&refresh=5s"
t=2020-02-04T15:50:13-0300 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[xxxx@xxxx.com.br yyyy@yyyy.com.br]" singleEmail=true

```
Could this Request 502 be the reason?

**EDIT:**

I looked that [PhantomJS is depreciated](https://grafana.com/docs/grafana/latest/administration/image_rendering/#phantomjs), I will test [Grafana Image Renderer](https://grafana.com/grafana/plugins/grafana-image-renderer) to see if the problem continues.

**Environment**:
- Grafana version:  v6.6.0 (5c11bbdfb4)
- Data source type & version: Elasticsearch v7.3.1 (4749ba6)
- OS Grafana is installed on: Debian GNU/Linux 10 (buster)

**Comment by aknuds1** [comment]
Please let us know if this works with the Image Renderer plugin.

**Comment by holiiveira** [comment]
The problem continues, even using the Grafana Image Renderer plugin:

```
t=2020-02-05T08:55:09-0300 lvl=dbug msg="Rendering alert panel image" logger=alerting.notifier ruleId=10 urlPath="d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5"
t=2020-02-05T08:55:09-0300 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5"
t=2020-02-05T08:55:09-0300 lvl=dbug msg="calling renderer plugin" logger=rendering renderer=plugin req="url:\"http://127.0.0.1:3000/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1\" width:1000 height:500 timeout:15 filePath:\"/var/lib/gr
afana/png/VkyviElFe2MS6OiJd9Js.png\" renderKey:\"oRtVNr0XwwTuS9FI2ArdZbFiFTFkutiQ\" domain:\"127.0.0.1\" "
t=2020-02-05T08:55:09-0300 lvl=dbug msg="Render request received" logger=plugins.backend pluginId=grafana-image-renderer url="http://127.0.0.1:3000/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1"


t=2020-02-05T08:55:16-0300 lvl=dbug msg="Rendered alert panel image" logger=alerting.notifier ruleId=10 path=/var/lib/grafana/png/VkyviElFe2MS6OiJd9Js.png took=6.49107635s
t=2020-02-05T08:55:16-0300 lvl=dbug msg="Uploading alert panel image to external image store" logger=alerting.notifier ruleId=10 path=/var/lib/grafana/png/VkyviElFe2MS6OiJd9Js.png
t=2020-02-05T08:55:16-0300 lvl=dbug msg="Uploaded alert panel image to external image store" logger=alerting.notifier ruleId=10 url=https://xxxx.yyyy.com.br/grafana/5fbydvzZVeKlCdGGq1ZS.png took=243.858835ms
t=2020-02-05T08:55:16-0300 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email uid=38QdxnOZk isDefault=false
t=2020-02-05T08:55:16-0300 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xxxx@yyyy.com.br] singleEmail=false

```

From the log, the URL `d-solo/SHLSG4dWk/uniface-background?orgId=1&panelId=5&render=1` represents the correct graph, but the image recorded in ```/var/lib/grafana/png/VkyviElFe2MS6OiJd9Js.png``` is different.

**Comment by holiiveira** [comment]
I use a reverse proxy for access, as below:

```
# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://noc.xxxx.com.br/grafana/

# Serves Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = true
```
However, the url used by the render does not use the settings above. Could this be the problem?

What would be the correct URL for the render:

- Current: http://127.0.0.1:3000/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1
- With sub path: http://127.0.0.1:3000/grafana/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1
- Root url: https://noc.xxxx.com.br/grafana/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1

**Comment by jgs0344** [comment]
I'm experiencing the same problem.
I tested three versions 
- grafana-6.5.1-1.x86_64.rpm : works fine
- grafana-6.5.3-1.x86_64.rpm : no
- grafana-6.6.1-1.x86_64.rpm : no 
You can also have the same experience in "Direct Link Rendered Image".

**Comment by holiiveira** [comment]
@peterholmberg Any more details that I can share to help resolve this issue?

**Comment by holiiveira** [comment]
?

**Comment by marefr** [comment]
@holiiveira seems like a problem with image rendering? Have you tried direct link rendered image of the panel of the alert in question? Please try latest stable Grafana version.

**Comment by holiiveira** [comment]
> @aknuds1 The problem continues, even using the Grafana Image Renderer plugin:
> 
> ```
> t=2020-02-05T08:55:09-0300 lvl=dbug msg="Rendering alert panel image" logger=alerting.notifier ruleId=10 urlPath="d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5"
> t=2020-02-05T08:55:09-0300 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5"
> t=2020-02-05T08:55:09-0300 lvl=dbug msg="calling renderer plugin" logger=rendering renderer=plugin req="url:\"http://127.0.0.1:3000/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1\" width:1000 height:500 timeout:15 filePath:\"/var/lib/gr
> afana/png/VkyviElFe2MS6OiJd9Js.png\" renderKey:\"oRtVNr0XwwTuS9FI2ArdZbFiFTFkutiQ\" domain:\"127.0.0.1\" "
> t=2020-02-05T08:55:09-0300 lvl=dbug msg="Render request received" logger=plugins.backend pluginId=grafana-image-renderer url="http://127.0.0.1:3000/d-solo/SHLSG4dWk/xxxx-background?orgId=1&panelId=5&render=1"
> 
> 
> t=2020-02-05T08:55:16-0300 lvl=dbug msg="Rendered alert panel image" logger=alerting.notifier ruleId=10 path=/var/lib/grafana/png/VkyviElFe2MS6OiJd9Js.png took=6.49107635s
> t=2020-02-05T08:55:16-0300 lvl=dbug msg="Uploading alert panel image to external image store" logger=alerting.notifier ruleId=10 path=/var/lib/grafana/png/VkyviElFe2MS6OiJd9Js.png
> t=2020-02-05T08:55:16-0300 lvl=dbug msg="Uploaded alert panel image to external image store" logger=alerting.notifier ruleId=10 url=https://xxxx.yyyy.com.br/grafana/5fbydvzZVeKlCdGGq1ZS.png took=243.858835ms
> t=2020-02-05T08:55:16-0300 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email uid=38QdxnOZk isDefault=false
> t=2020-02-05T08:55:16-0300 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xxxx@yyyy.com.br] singleEmail=false
> ```
> 
> From the log, the URL `d-solo/SHLSG4dWk/uniface-background?orgId=1&panelId=5&render=1` represents the correct graph, but the image recorded in `/var/lib/grafana/png/VkyviElFe2MS6OiJd9Js.png` is different.

I believe it is a problem in rendering. I tested in version v6.7.2 (423a25fc32), the problem continues.

As you can see above, the link points to the correct panel, but the recorded image is different.

**Comment by marefr** [comment]
@holiiveira please try the latest version of Image Renderer Plugin and enable verbose logging, see https://github.com/grafana/grafana-image-renderer#environment-variables

Then provide debug output here. 

Could be a problem when using `serve_from_sub_path`. But debug output should show this. Since you already have a proxy in front of Grafana I would suggest skipping `serve_from_sub_path` and configure proxy to proxy request of /grafana to `http://<grafana instance>:3000` to verify if using `serve_from_sub_path` is the problem.

**Comment by jgs0344** [comment]
@holiiveira please try the `serve_from_sub_path` to false.
The problem was solved after I changed that setting.
Thanks @marefr  :)
grafana-server : 6.7.2
grafana-image-renderer : 1.0.12

**Comment by holiiveira** [comment]
It worked here too.
Thanks to those involved.

**Comment by marefr** [comment]
Thanks for confirming. This is clearly a bug then so will reopen.
