### ISSUE TITLE
TablePanel: pagination should be persistent across panel refresh

### ISSUE THREAD

**Issue by cstyan** [grafana/grafana#21923]
**What happened**:
On a dashboard that's configured to refresh every 10s, with a table panel, if you move to another page in the panel the refresh will move you back to page 1.

**What you expected to happen**:
When a refresh happens, the panel display stays on the same page of the results but results may be reordered if there's new/less series in the more recent query

**How to reproduce it (as minimally and precisely as possible)**:
create a dashboard that has a table panel with at least 2 pages of results in the table, turn on the auto refresh for some interval, move to page 2, wait for the refresh

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.7.0-pre (78b1ab8360)
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: linux/chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Duplicate #14780
