### ISSUE TITLE
Spaces deleted from generated panel links

### ISSUE THREAD

**Issue by barakakoun** [grafana/grafana#21936]
Since panel links (drilldown links) ui change on 6.3, it's impossible to use spaces inside the link (they removed). CHECK OUT EXAMPLES BELOW
In our migration process, all spaces appear on our defined drilldown links get deleted (when opening the link, not in the defined input).
Asking customers to use `%20` instead of spaces is ugly yet acceptable, but it still doesn't solve the migration issue.

Before version 6.3 (this is version 6.2.5):
<img width="776" alt="Screen Shot 2020-02-05 at 12 26 19" src="https://user-images.githubusercontent.com/15690241/73833480-b7e3eb00-4812-11ea-8189-518ef4adf2ff.png">
the generated link is: `www.google.com?query=some%20query`

From 6.3 (this is version 6.5):
<img width="1537" alt="Screen Shot 2020-02-05 at 12 24 54" src="https://user-images.githubusercontent.com/15690241/73833350-85d28900-4812-11ea-94c0-6e69aed31fb4.png">
the generated link is: `www.google.com?query=somequery` the space is deleted!

**Environment**:
- Grafana version: 6.3 and up (Since changing panel links ui)

**Comment by barakakoun** [comment]
Also, if you can help me find the place in the code who in charge of the space deletion, so I can edit it in our project, it would be great.

**Comment by peterholmberg** [comment]
It seems we're running inputs through `Plain.serialize`, been going through the docs for `slate-plain-serialized` to see if they do any trimming. It _could_ have something to do with that.

https://github.com/grafana/grafana/blob/90d415861d283d21326038279c9a93e0787aaf07/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx#L118

**Comment by barakakoun** [comment]
@peterholmberg actually found the place:
https://github.com/grafana/grafana/blob/90d415861d283d21326038279c9a93e0787aaf07/public/app/features/panel/panellinks/link_srv.ts#L269
it removes whitespace and line-feed characters. 
why would you remove whitespaces though?

**Comment by peterholmberg** [comment]
@barakakoun nice find!
