### ISSUE TITLE
Explore: Measurement field undefined in explore logs

### ISSUE THREAD

**Issue by richard-lawrence** [grafana/grafana#21932]
**What happened**:

When selecting a measurement in explore logs, no sub menu is shown to select the log message field, you can only select the measurement and its field remains undefined. Hence no log messages can be displayed.

<img width="625" alt="Screenshot 2020-02-05 at 09 52 34" src="https://user-images.githubusercontent.com/56631278/73832607-66cafb80-4800-11ea-8fbf-238248aea383.png">

**What you expected to happen**:

When adding a measurement in Explore logs, a drop down appears to select the measurement, then a sub menu should appear to allow you to select the log message field. This sub menu fails to appear and after selecting the measurement the field is undefined.

**How to reproduce it (as minimally and precisely as possible)**:

Every time.

**Anything else we need to know?**:

First time I have tried this, don't know if it worked or not with previous versions.

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: InfluxDB 1.7.9
- OS Grafana is installed on: MacOS 10.14.5
- User OS & Browser: MacOS 10.14.5, Safari 12.1.1
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
This should be already fixed be https://github.com/grafana/grafana/pull/21787 in 6.6.1.
