### ISSUE TITLE
Editor: Hint to use rate() for counters should allow Prometheus' increase()

### ISSUE THREAD

**Issue by theneva** [grafana/grafana#21938]
Hi! :wave:

**What happened**:

I want to graph the increase of a Prometheus counter. As per the Prometheus docs, I use [the `increase` function](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase).

Grafana shows a hint that looks like a warning telling me I should use `rate`:

![image](https://user-images.githubusercontent.com/1404650/73834271-b236d700-480b-11ea-9d4e-ff57bc98c362.png)

I see the hint because I hit this code path:

https://github.com/grafana/grafana/blob/28230bbf523d3c333299eb99934393d4715d6e5c/public/app/plugins/datasource/prometheus/query_hints.ts#L30-L31

I believe that when using the Prometheus data source, `increase` is perfectly fine to use for counters.

**What you expected to happen**:

I should not see the warning/hint.

**How to reproduce it (as minimally and precisely as possible)**:

Write a Prometheus query for a counter using `increase` instead of `rate` using any type of visualisation.

**Anything else we need to know?**:

I don't think so.

**Environment**:
- Grafana version: Grafana v6.6.0 (5c11bbdfb4)
- Data source type & version: Built in Prometheus
- OS Grafana is installed on: Alpine Linux 3.10.4 (Docker)
- User OS & Browser: macOS Mojave 10.14.5 & Chrome 79.0.3945.130 (Official Build) (64-bit)
- Grafana plugins: Shouldn't be relevant
- Others: N/A

**Comment by marefr** [comment]
Fixed by #21955
