### ISSUE TITLE
Table / Singlestat panel crashed after unlock dashboard

### ISSUE THREAD

**Issue by willyhutw** [grafana/grafana#21939]
**What happened**:
In an uneditable dashboard. If you make it editable then back to dashboard and scroll the dashboard, you will see singlestat and table panels all crashed.

The error message from panel:
Table: `Cannot read property 'setTable' of undefined`
Singlestat: `Cannot read property 'prefix' of undefined`

**What you expected to happen**:
Should be normal just like other panels (graph, stat, gauge, bar-gauge, heatmap)

**How to reproduce it (as minimally and precisely as possible)**:
1. Make sure your dashboard contain table or singlestat panel and height enough to be able to scroll.
2. Make sure the setting of the dahsboard `editable` is false.
3. Toggle editable switch button to true in the dahsboard setting page.
4. Back to dashboard by clicking `Go back (Esc)`
5. Scroll the dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Grafana
- OS Grafana is installed on: docker
- User OS & Browser: MacOS & Chrome / Firefox
- Grafana plugins: none
- Others:

**Comment by bigunyak** [comment]
Facing the same issue.

**Comment by mckn** [comment]
Fixed in the upcoming 6.7 release.

**Comment by torkelo** [comment]
@mckn cannot see a reference to a PR or commit

**Comment by dprokop** [comment]
@torkelo sorry my bad, said not to backtrace to the fix commit :/

**Comment by mckn** [comment]
@torkelo I'm not sure what changed fixed the issue but I can reproduce it in the 6.6.2 version but it is fixed in the current version of master. So I did not investigate it further. I can see if I can see what changed actually fixed this.

**Comment by SpokeyWheeler** [comment]
Definitely something to do with filters! I have 6.7.3 and switching editable on or off did nothing, but deleting the filter suddenly made everything work.
