### ISSUE TITLE
Cell linking resets time settings

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#21941]
**What happened**:

Using a table to list interfaces, I use cell links to modify template variables and thus update a graph to show traffic for the relevant interface when you click the interface/table/cell.

Similar to #21693, the time-variables are reset.  So:

1. Have a dashboard with cell links updating a template variable on the same dashboard
2. Change the time zoom/period
3. Click a link.
4. Time zoom/period is now reset to the default.

**What you expected to happen**:

Time zoom/period should not change when it is not supplied.

**How to reproduce it (as minimally and precisely as possible)**:

See first point.

**Anything else we need to know?**:

I can "work around" this by setting to=$__to etc. This is OK for longer time periods, but for "live" dashboards, this isn't good, since it will switch from relative time ("to=now, from=now-1h") to absolute time ("to=1580905746, from=1580902163"), which isn't very obvious to the user. 

**Environment**:
- Grafana version: Grafana 6.6.0
- Data source type & version: Influxdb 1.7
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chromium
- Grafana plugins: Standard/none
- Others:

**Comment by torkelo** [comment]
There is currently no way to dynamically add time variables to the cell links in the old angular table panel.

But the new table panel  (coming in 7.0) supports DataLinks and data links support adding current time to url
