### ISSUE TITLE
Minor: Improve UI/UX of "Switch Organization" modal

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#21948]
**What would you like to be added and why is this needed**:

We use a Grafana instance which heavily uses the concept of Organizations in Grafana. We ended up with tens of organizations. Kinda frequently our users ask us how they can switch to organization X or Y, which is indeed accessible for them but not in the visible field of view. The problem is that they are not aware that the organizations list is scrollable as the scrollbar only appears if you hover it (at the very right side of the modal).

Probably only very few Grafana users are affected by this because I assume many users do not have many organizations, but at the same time the fix (for instance always showing a scrollbar in that modal) might be very easy to implement

I am on Mac OS using Chrome.

**Comment by peterholmberg** [comment]
Could be done as part of https://github.com/grafana/grafana/issues/16824

**Comment by dprokop** [comment]
Closing this issue as it's already referenced in #16824 and that one is a more general request to rethink org switcher
