### ISSUE TITLE
Time picker: Permanently add time range navigation buttons

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#21957]
Source of this request is user feedback from grafana public slack: 

One thing that I forget every time: the "time range navigation buttons" are visible only when not using one of the "quick ranges" like "Last 24 hours", so I keep looking around for the buttons when i want to scroll a bit further into the past without changing the "visible duration" (ie. 24h) until I remember this and then have to "zoom in" using one of the graph panels by "dragging across" the entire range to make it change into the mode with the arrows, and then click to navigate back in time

![image](https://user-images.githubusercontent.com/53754871/73918917-d3a6ca00-48c2-11ea-9070-9ef36e7b3eb0.png)

Did a quick sketch of the design in Figma: https://www.figma.com/file/gXypOQEb8yU21RzlxXy2QW/Time-picker?node-id=448%3A5377

**Comment by torkelo** [comment]
This is a compromise to save space / reduce clutter.

**Comment by jessover9000** [comment]
> This is a compromise to save space / reduce clutter.

I do get that, but it's kind of weird that when the time range is the largest and most cluttery, the buttons appear, don't you agree? I think from a user friendliness perspective the buttons are helpful and I did a quick design where I thought it's not too bad. https://www.figma.com/file/gXypOQEb8yU21RzlxXy2QW/Time-picker?node-id=448%3A5377

**Comment by bboreham** [comment]
I often wish there was a button to convert the current relative range (e.g. now-1h to now) to an absolute range.
If this existed, then you would get the navigation buttons as a second step.

**Comment by wkruse** [comment]
@bboreham, @jessover9000: You can do that with the `t + a` shortcut. Use `h` or `?` to show all keyboard shortcuts.

**Comment by bboreham** [comment]
Well TIL.  Thank you.

That is possibly the least discoverable thing since "how to quit vi".

**Comment by wkruse** [comment]
Could someone explain the reasoning, why when the interval is `24h` and the time range is absolute, when moving left, the `From` and `To` move in `12h` steps (so basically `interval/2`), e.g.:

- Start with `From: 2022-07-26 00:00:00` and `To: 2022-07-27 00:00:00`
- Click `<`
- See new `From: 2022-07-25 12:00:00` and `To: 2022-07-26 12:00:00` (**Expected**: `From: 2022-07-25 00:00:00` and `To: 2022-07-26 00:00:00`)

Bonus points, if you could point me to the code, where it happens.

**Comment by DOCaCola** [comment]
Personally i am navigating the graphs all the time and have to set a absolute timeframe every time to make them appear first. It is an inconvenience. An option to show these buttons permanently would be helpful.

**Comment by jeme** [comment]
@wkruse I think this happens regardless of the range, be that 24h, 12h, 6h... Navigating with start from 2023-07-05T12:00 to 2023-07-05T13:00 the period will jump in 30 minute intervals.

I can see the reasoning for this as it allows a piece of the "previous" slice to be viewed along the new "slice", I can see how some would find this useful while others would rather have it skip the full range. So I would guess this was a deliberate choice.

Making it an option/configuration would ofc. be great.
