### ISSUE TITLE
Using dashboards on mobile, users move panels around by accident

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#21959]
**What happened**:
quote from Grafana public slack: "trying to use a dashboard on mobile I keep moving panels around by accident.... I suppose disabling edit will help, but I'd rather not. Also: It isn't even obvious that that's what I'm doing, it just feels like I'm unable to scroll until I go "oh... OH!"." – https://grafana.slack.com/archives/CSKQV9Y5B/p1579795788004900

**Anything else we need to know?**:
has happened for several users

**Environment**:
has occurred on iPhone XR/iOS 13.3 in Brave browser as well as Android 10 with Chrome, so seems like a general issue

**Comment by peterholmberg** [comment]
Which version are they running? Should be fixed by https://github.com/grafana/grafana/pull/20629
