### ISSUE TITLE
Add user/password authentication method to Application Insights API in Azure Monitor data source

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#21952]
Currently, the Azure Monitor plugin only support API Key authentication.

https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/

![screenshot 2020-02-05 1519](https://user-images.githubusercontent.com/3270755/73880178-e5895e00-482b-11ea-91cd-9db3aaac3341.png)

**What would you like to be added**:

The Azure Monitor API supports both API Key and user authentication.

https://dev.applicationinsights.io/documentation/Authorization

**Why is this needed**:

Some large corporate environments have strict control over creating API tokens for cloud apps and user/password is a much more practical authentication method.

**Comment by sunker** [comment]
We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics).
Closing this issue.
