### ISSUE TITLE
Feature request: Template variables in thresholds

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#21961]
**What would you like to be added**:

Dynamic thresholds in graph panels, based on template variables.

**Why is this needed**:

Example: Network interfaces can have varying speeds, and policy might dictate different thresholds for what is acceptable fill grade. E.g.: If traffic regularly exceeds 50% of capacity, an upgrade is planned.

**Comment by liamdiprose** [comment]
Possible duplicate with #4929?

**Comment by marefr** [comment]
Duplicate of #922
