### ISSUE TITLE
Access Method textfield not visible when setting up a datasource

### ISSUE THREAD

**Issue by Steffoh** [grafana/grafana#21966]
When setting up a new datasource (Prometheus) the access method is not choosable:
<img width="1353" alt="Bildschirmfoto 2020-02-06 um 12 51 39" src="https://user-images.githubusercontent.com/9406302/73934808-808f4000-48df-11ea-8ed8-8044e93145b8.png">

**Comment by peterholmberg** [comment]
fixed via https://github.com/grafana/grafana/pull/21833
