### ISSUE TITLE
[Alerting] Notification channel form "Send Test" button looks weird

### ISSUE THREAD

**Issue by theneva** [grafana/grafana#21960]
**What happened**:

The button's label breaks strangely, regardless of zoom level or window width:

![image](https://user-images.githubusercontent.com/1404650/73920632-13bb7c00-48c6-11ea-87ab-4fb3142b8d6d.png)

**What you expected to happen**:

The "Send Test" button should contain its label.

**How to reproduce it (as minimally and precisely as possible)**:

Visit the notification channel editing form (for example, visit https://your.grafana.instance/alerting/notification/1/edit)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.0 (5c11bbdfb4)
- Data source type & version: N/A
- OS Grafana is installed on: Alpine Linux (but it doesn't matter)
- User OS & Browser: macOS Mojave 10.14.5 (18F203) & Chrome 79.0.3945.130 (Official Build) (64-bit)
- Grafana plugins: N/A
- Others: N/A

**Comment by peterholmberg** [comment]
Thanks for reporting this, it's an issue caused by our next generation form styles which will be replacing these form styles (buttons, inputs etc).
