### ISSUE TITLE
Regression: Legend sorting is always alphabetically when table mode is disabled

### ISSUE THREAD

**Issue by vonox7** [grafana/grafana#21962]
In Grafana you can sort the series in a legend ascending/descending based on e.g. current value, total value and so on by enabling table mode and clicking on a headline.
In Grafana 6.2.1 you could then **disable table mode, but still the series were sorted**. In Grafana 6.5.3 this is no longer the case, when switching back to no-table mode the sorting is alphabetically again.

### Why would someone use that feature?
Consider the following graph:

![image](https://user-images.githubusercontent.com/621501/73922274-284d4380-48c9-11ea-94e4-8145f9f8b51d.png)

There are more than 50 series in that graph, most of them at 100% or near 100%. But one series (the yellow one) has dropped to 50% - so it would be interesting what the name of the series is to debug the issue.

Browser: Chrome on Desktop and Chrome on iOS (note that on mobile viewing the hover tooltip with more than 30 series is broken so on mobile it is even harder to learn about the name of the outlier).

### What is wanted?
An ability to sort the values also not in table mode (because probably there is not enough space for table mode), e.g. by preserving the sort order that was in table mode.

**Comment by torkelo** [comment]
duplicate of #21962

**Comment by electrofloat** [comment]
https://github.com/grafana/grafana/issues/20165 - issues are duplicate of each other... jesus christ! 😠

**Comment by nmarrs** [comment]
Re-opening this issue 😅 as the underlying request has not yet been addressed and has come up twice in two separate issues
