### ISSUE TITLE
[Feature request] Dashboard variable uneditable

### ISSUE THREAD

**Issue by arturohu** [grafana/grafana#21978]
**What would you like to be added**:
 I would like an Admin user would write different values of dashboard variable and a Viewer couldn't write any value at variable (on dashboard or URL), I want the Viewer only could select preselected values by Admin user.

**Why is this needed**:
I need it because my SQL request has these dashboard variables and I need that Viewers to only can get information specified by Admins on each dashboard. Each user will have different values in that variable so that each user can access the data that corresponds to him.

![var-dashboard](https://user-images.githubusercontent.com/41362321/73948622-8003a300-48f9-11ea-9bdb-66082860c7d1.png)
I'd like to be able to turn off this edition by Viewers. Thank you :)

**Comment by sakjur** [comment]
:wave:

This looks similar to #18157, I'll close this feature request in favor of that one. That PR also contains some explanations of why it's not certain that doing this change will be quite sufficient to get the result you're looking for.
