### ISSUE TITLE
admin info page confusion

### ISSUE THREAD

**Issue by jlopp** [grafana/grafana#2197]
On that admin page under the google auth and github auth sections there are lines that say "allow_sign_up	false" even though I have "enabled = true" in the ini - I'm guessing these should be removed and don't correspond to actual settings.

**Comment by torkelo** [comment]
Not sure what you mean, allow_sign_up is a setting separate from enabled, allow_sign_up specifies if people can sign up (get a grafana account) with google or github oauth

**Comment by jlopp** [comment]
My point is that "allow_sign_up" exists 3 times on the admin info page, but two of them appear to be fake / incorrect.

I have "allow_sign_up = true" in my grafana.ini, and on the admin info page under the 'users' section it displays as true.

However, "allow_sign_up" exists under both the "auth.github" section and the "auth.google" section on the admin page and display as "false" regardless of the ini setting. I'm guessing that this is extraneous data being displayed on the info page.

![screen shot 2015-06-19 at 4 35 30 pm](https://cloud.githubusercontent.com/assets/288011/8262581/4b7ad2be-16a1-11e5-9ad4-460b7fe1787c.png)
![screen shot 2015-06-19 at 4 35 36 pm](https://cloud.githubusercontent.com/assets/288011/8262582/4b7c8bfe-16a1-11e5-8eda-bb65d5daac86.png)
![screen shot 2015-06-19 at 4 35 45 pm](https://cloud.githubusercontent.com/assets/288011/8262585/4fc1e8f8-16a1-11e5-98d2-36e91d1321e6.png)

**Comment by torkelo** [comment]
Yea, the allow_sign_up setting under auth.google and auth.github are for those authentication options. It allows you to disable general sign up (using the username / password sign up form) while allow sign up with google oauth. So the setting under [users] is different from the one under auth.google and auth.github. 

In your case users will not be able to sign up with auth.github or auth.google but they will be able to create an account using the sign up form.

**Comment by jlopp** [comment]
OK, so I think the bug is that the "allow_sign_up" flag is being ignored. I successfully configured both my github and google auth sections and they are both working after only setting "enabled = true" in the .ini - feel free to check them yourself at https://statoshi.info/login

Long story short, a valid google or github auth enables them even if allow_sign_up is set to false

**Comment by torkelo** [comment]
Not sure what bug you mean,  you mean you can sign up with Google oauth when auth.google allow_sign_up is false?

**Comment by jlopp** [comment]
Yes, that's exactly what I'm saying. It's working even though allow_sign_up is set to false.

**Comment by torkelo** [comment]
@jlopp you are wrong, just tried to sign up (= Create new Grafana account) and it is not allowed on your grafana instance, as the config suggest. So seems to be working to me. 

If the account (email) is already registered the login will work but in my case (just tried google oauth) it did not allow me to login with google oauth as that would imply that an account would need to be created with my google email and since you have disabled that option it just redirected me back to the login page.

**Comment by jlopp** [comment]
Ohhhhh OK, that must be my problem - my Grafana admin account is tied to the same email account as my google and github accounts. Maybe it's worth documenting this edge case somewhere?
