### ISSUE TITLE
Out of resource (net::ERR_INSUFFICIENT_RESOURCES)

### ISSUE THREAD

**Issue by Phinitris** [grafana/grafana#2199]
Hey,
after several minutes of using grafana, it cannot load graphs anymore.

Network log says: POST http://monitoring01/api/datasources/proxy/1/render net::ERR_INSUFFICIENT_RESOURCES

**Comment by torkelo** [comment]
this is strange. Something else on your system that is using up all sockets? some metric agents can be bad ad closing connections to carbon.  No one else has reported this about grafana. Can you check how many open handles/sockets the Grafana process has?

**Comment by Phinitris** [comment]
Hey,
seems like a temporary issue. Flushed cache and now it's working. Also I had 4 graphs which are graphing the 5 top talkers of 20.000 IPs. Maybe that caused the issue. Graphite process(wsgi/apache2) also spiked at 80% from 12 Cores and stucked loading. I now removed these graphs. Maybe it's a bit overkill. Thanks for looking into this anyway.
