### ISSUE TITLE
Time picker: Make tooltip smart

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#21998]
The tooltip for the time range always shows absolute time ranges. In on-site user research I've gotten the feedback that especially when you have a "last x hours" timerange selected, this is hard to read and not always necessary and maybe a more easily-readable format would be better. 

So I propose that we change the tooltip text so that it
- switches out the date for "Today/Yesterday" in recent time ranges
- drops the seconds for relative ranges longer than 5 minutes
- shows absolute ranges in other cases
?

I've also thought about whether it makes sense to use "now" but I guess unless people are in refresh mode or using very short time ranges it doesn't make much sense.

A quick design example: https://www.figma.com/file/gXypOQEb8yU21RzlxXy2QW/Time-picker?node-id=448%3A5377

**Comment by torkelo** [comment]
good improvements! 👍
