### ISSUE TITLE
Dashboard settings navigation: Make currently active menu option clickable

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#21999]
**What happened**:
When users are changing dashboard settings, e.g. entering variables or adding links, as soon as they are on the editing/adding screen, they have trouble finding the back link to the overview list. The navigation option in the left sidebar is still a link but clicking it doesn't do anything. 

![image](https://user-images.githubusercontent.com/53754871/74026655-f14d5f80-49a6-11ea-825e-2cf4d597fc63.png)

Source of this feedback is the grafana public slack: 
"A very confusing part of grafana is editing of variables. When I have a list of variables, and select one that I want to edit (or add a new), the link back to the site is not where I (and many of my colleagues) would think it was. 
One of them is actually not a link in that context. So people often end up clicking "Back to dashboard" arrow in top left corner instead."
https://grafana.slack.com/archives/CSKQV9Y5B/p1579177914014600

**Comment by sarlinska** [comment]
@lukasztyrala can we close this? You'll probably tackle this during new navigation project, right?

**Comment by lukasztyrala** [comment]
Seems like something to tackle along the way of the new navigation project, but we need to put it in the context of other improvements and work (I think we can do that soon, during one of the new nav syncs in the following days).

**Comment by tskarhed** [comment]
Closing in favor of  #37961
