### ISSUE TITLE
Feature Enhancement - Panel Links 

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2200]
The panel link feature should be extended to match some of the new options introduced in the Dashboard links section. 

So the below interface should be able to also pass along time range and variables (as the 2nd snippet illustrates)
![screenshot 2015-06-20 19 06 00](https://cloud.githubusercontent.com/assets/2886187/8269614/9c19ee1a-177f-11e5-85a0-c8a94e6f91a7.png)

![screenshot 2015-06-20 19 07 11](https://cloud.githubusercontent.com/assets/2886187/8269616/c66b4f92-177f-11e5-8112-b59cf367831a.png)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/8285863/7a184ffe-1906-11e5-8f60-b63474468415.png)
