### ISSUE TITLE
Hide IP address of Data Source server on error message

### ISSUE THREAD

**Issue by baur** [grafana/grafana#22000]
**What would you like to be added**:

![image](https://user-images.githubusercontent.com/2898361/74026862-48682a00-49d1-11ea-8c91-6c85dd55daa6.png)

Is it possible to hide IP address of Data Source server on error message?

**Why is this needed**:

for security reason

**Comment by torkelo** [comment]
What data source are you using?

**Comment by baur** [comment]
PostgeSQL

**Comment by marefr** [comment]
If anyone interested in contributing changes needed here:
https://github.com/grafana/grafana/blob/1e88e508220159cddb846e5934af3fe3ae39bef9/pkg/tsdb/postgres/postgres.go#L136-L138

Changes similar to the MySQL data source, but needs checking for postgres specific errors:
https://github.com/grafana/grafana/blob/1e88e508220159cddb846e5934af3fe3ae39bef9/pkg/tsdb/mysql/mysql.go#L142-L151
