### ISSUE TITLE
Log panel error "cannot read property 'toLowerCase' from null"

### ISSUE THREAD

**Issue by apetzo** [grafana/grafana#22023]
We've updated our pre-production grafana instance to 6.6.1 from 6.5.3 and our Log panels have stopped working.
The log panels are fed by an elastic data source and since the update they show the error

`Cannot read property 'toLowerCase' from null`

From what I can tell via the query inspector, the query to the elastic data source works fine.
Any ideas how to debug this?

**Comment by sakjur** [comment]
Can you update your post to adhere to the bug report template? https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md

Please include information about any messages in your JavaScript console log and the output from the query inspector. If you try to create a new panel with the same query as one of the non-functional ones, does that panel work?

**Comment by icebob** [comment]
Same issue with 6.6.1 I see the entries in Explore but I've got the same error message on dashboard.

**Comment by cblims** [comment]
Got this as well.

**What happened**:
e.toLowerCase()
**What you expected to happen**:
Logs to appear
**How to reproduce it (as minimally and precisely as possible)**:
Create new dashboard, query elasticsearch (any lucene query), metric logs annd visualize with logs.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Elasticsearch 5.5
- OS Grafana is installed on: official docker container
- User OS & Browser: MacOS/Chrome
- Grafana plugins: no extras
- Others:
![image](https://user-images.githubusercontent.com/29525570/74433950-b85b3200-4e61-11ea-882a-78669ea28594.png)

**Comment by sakjur** [comment]
I'm having some problems reproducing this in my test environment, but it definitely sounds like something is broken.

@icebob @cblims Is this happening to you when creating new panels as well or just for log panels which were present before upgrading to 6.6.1?

@icebob @apetzo What version of ElasticSearch are you using?

**Comment by icebob** [comment]
@sakjur Elasticsearch version is 7.5.2
At me, I've created a new dashboard & a new panel. I had no logs panel beforehand.

**Comment by marefr** [comment]
Tested with elasticsearch 7 and the logs panel and was able to reproduce: Maybe related to when level field name have been configured, but needs to be investigated. I was able to reproduce using a datasource configured with Level field name=`fields.level`.

```
logs.ts:36 Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at getLogLevelFromKey (logs.ts:36)
    at logSeriesToLogsModel (logs_model.ts:316)
    at dataFrameToLogsModel (logs_model.ts:197)
    at LogsPanel (LogsPanel.tsx:24)
    at LogsPanel (react-hot-loader.development.js:757)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
```

**Comment by sakjur** [comment]
Ah, that seems to be the culprit. I was able to reproduce when I set `fields.level` on the datasource as well. Thank you 🙂
