### ISSUE TITLE
Template query type regex order

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#2202]
Is it possible to change the order of results when using a regex extraction for a query type? Currently, it seems the order is determined by the original results and not that of the values returned by the regex.

**Comment by torkelo** [comment]
What do you mean, ".. original results and not that of the values returned by the regex"? Last time I checked you could not specify sorting in regex :) 

The order is determined by the original results, the original results is piped through the regex to extract or filter out unwanted parts or whole items.

**Comment by druchoo** [comment]
Hey Torkel,

I think you nailed what I was asking but here are pics of an obfuscated example. I would like like the ability to sort the 'Values returned by the regex' alphabetically. Is this currently possible? If not please consider this a feature request. Reason is that with many results, it is difficult to visually scan the list for a specific item. One would usually have to click on the variable drop down list and type a string to filter, then finally click an item.

Original results:
![original_results](https://cloud.githubusercontent.com/assets/2237523/8272063/fc6fe822-1802-11e5-9a52-4c76d7663df8.png)


Values returned by the regex:
![regex_values](https://cloud.githubusercontent.com/assets/2237523/8272056/bcde2386-1802-11e5-83bd-c1749ca16b68.png)

**Comment by torkelo** [comment]
I think in Grafana 2.1 the variable value list will always be sorted alphabetically

**Comment by druchoo** [comment]
Ok sounds good. Please check when you get a chance. And if they aren't sorted, please add to 2.1 if possible.

-Thanks
