### ISSUE TITLE
Singlestat: Support string values

### ISSUE THREAD

**Issue by xkrt** [grafana/grafana#2203]
Hi,

I have some string metric (which is actually string representation of date) and want just show last value of it on dashboard. So I use 'Single stat' graph with query:
```sql
SELECT last(value) FROM "my_serie"
```

Grafana always shows just "0", but if I run these query in InfluxDB web interface I got my result:
```
time                    last
1970-01-01T00:00:00Z    2015-06-20
```

InfluxDB ver 0.9
Grafana latest ~11 June

**Comment by torkelo** [comment]
Singlestat does not support string values yet. Wil try to fix before 2.1 release
