### ISSUE TITLE
Scale type logarithmic in grafana v1.9

### ISSUE THREAD

**Issue by cristizafiu** [grafana/grafana#2204]
Hello

My company uses grafana v1.9 for a statistics project. We currently have this deployed on several machines and upgrading to v2.0 isn't a viable solution. 

Can we have the logarithmic y-scale in grafana v1.9? 

Thanks!

**Comment by torkelo** [comment]
No, sorry this is only available in 2.0. Only critical bug fixes will be added to 1.9.x branch. 

Can you describe why upgrading is not viable?

**Comment by cristizafiu** [comment]
As I've said, we already have the project deployed on several production machines and we have several custom menus and plugins added to the v1.9 grafana UI. Integrating these menus and plugins to the new UI would mean a lot of re-work and testing from our side, time that we don't currently have.
