### ISSUE TITLE
Repeating Stat panel - Data Links 

### ISSUE THREAD

**Issue by ranalk** [grafana/grafana#22043]
While using repeating **stat panel** based on variable value the value on data link of that variable will extract the whole array instead of just the the value on that stat panel.
Since each stat panel is being rendered by single value we would expect that we can you this single value further instead of passing all values.
![image](https://user-images.githubusercontent.com/20575744/74102671-66a76480-4b4e-11ea-8795-5f160f7b1998.png)
![image](https://user-images.githubusercontent.com/20575744/74102674-6909be80-4b4e-11ea-9356-281144cdd985.png)

**Comment by ryantxu** [comment]
Try using template variables in the editor...  essentially type `$` in the text editor and you should see some suggestions
