### ISSUE TITLE
Hubot package for Grafana

### ISSUE THREAD

**Issue by stephenyeargin** [grafana/grafana#2206]
I've written this based on what I found in the notes in [this file](https://github.com/grafana/grafana/blob/master/vendor/grafana.coffee).

- https://github.com/stephenyeargin/hubot-grafana
- https://www.npmjs.com/package/hubot-grafana

Based on what I've read in the API, this may be the only practical commands for it quite yet. I tested it out with the `play.grafana.org` site and it worked fine.

```
user1>> hubot grafana dashboard graphite-carbon-metrics
hubot>> Graphite Carbon Metrics: http://play.grafana.org/render/dashboard/solo/graphite-carbon-metrics/?panelId=1&width=1000&height=500&from=now-6h - http://play.grafana.org/dashboard/db/graphite-carbon-metrics/?panelId=1&fullscreen&from=now-6h
```

**Comment by torkelo** [comment]
great, can`t see where you specify panel id though?

**Comment by stephenyeargin** [comment]
So, right now it will return _all_ panels (queries the API to get a list of available ones in a given Dashboard). I could see using an optional format like `hubot grafana dashboard <slug>:3` to get only panel 3.

**Comment by torkelo** [comment]
yes, maybe even skip dashboard:
`hubot grafana dashboard slug:3  now-1h now`
I would also love to be able to do aliases
`hubot grafana alias:logins = dashboard webapp-overview:3 now-1h now`
`hubot grafana alias:logins`
`hubot grafana alias list`

Or something like that

**Comment by stephenyeargin** [comment]
Knocked out two of the three for `v1.0.0`. I'll have to dust off the `robot.brain` manual to remember how to the the `alias` bit.

**Comment by torkelo** [comment]
@stephenyeargin that is great news. Will try it out soon
