### ISSUE TITLE
Navigation Issue in Grafana version 6.6.x

### ISSUE THREAD

**Issue by AjitVV** [grafana/grafana#22068]
**What happened**:
The navigation between dashboards seems to be not working properly sometimes, that is, while going from one dashboard to next one, the variable drop down selection seems to be reset to default.

**What you expected to happen**:
Grafana should persist the variable values while navigating between dashboards.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install/Upgrade Grafana to version 6.6.x
2. Create 3 dashboards.
3. Create some navigation - select "share variables" while creating links
    i. Navigation link from dashboard 1 to dashboard 2.
   ii. Navigation from dashboard 2 to dashboard 3.
  iii. Navigation from dashboard 3 back to dashboard 1.
4. Add same variables in all three dashboards.
5. Navigate between dashboards.

Navigation fails few times, resetting the variable values to default.

**Environment**:
- Grafana version: 6.6.x
- Data source type & version: InfluxDB
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 and Chrome 79.0.3945.130
- Grafana plugins: None
- Others: NA

**Comment by sakjur** [comment]
1. Did you link the dashboards by URL or by using tags? (I tried both [with Prometheus instead of Influx, afaik it should work similarly] and they're seemingly working for me — I even tried setting the variable in the URL manually and that just gave me a multi-value variable with both options selected)
2. Can you verify that "Variable values" is checked for all three links?

**Comment by AjitVV** [comment]
The link to dashboard is by using tags and I have checked the "Variable Values" for all the three links. The navigation works correctly here.

But, navigating from one dashboard panel(clicking on panel value) to another dashboard (to and fro) repeatedly ( 5+ times) results in wrong variables passed to the next dashboard in URL. I can also see that the URL is getting updated automatically.

**Comment by AjitVV** [comment]
Same issue as mentioned here.
https://github.com/grafana/grafana/issues/21895

**Comment by tskarhed** [comment]
Closing this in favor of #21895
