### ISSUE TITLE
The series override menu has discoverability issues

### ISSUE THREAD

**Issue by mem** [grafana/grafana#22069]
**What would you like to be added**:

A different organization for the series override menu, or at least hints that it extends beyond the visible display area.

**Why is this needed**:

![series_override](https://user-images.githubusercontent.com/189701/74156801-b16fbd80-4bdc-11ea-8195-eef52ac37104.png)

Consider the above screenshot. After clicking "add series override", a new row is added with the selector for the series and a list of values to be overriden. Each input field on the right corresponds to one override. It displays a menu that extends down, beyond the visible display area. As there are no hints that this is the case, you have to scroll down to figure out that there are more options in that menu.

I was looking for a particular entry (use second y axis) and I was confused this particular setting couldn't be overriden, until I accidentally scrolled down.

@sarlinska tells me this is an issue with menus in general.

**Comment by torkelo** [comment]
This is going to be replaced with field overrides (for new react panels), so we better spend time on the new panel editor UX than address this.

**Comment by sarlinska** [comment]
@torkelo should we close this issue?

**Comment by torkelo** [comment]
yes
