### ISSUE TITLE
Docs: more info about start_tls for LDAP

### ISSUE THREAD

**Issue by AJDurant** [grafana/grafana#22060]
**What would you like to be added**: 
Documentation clarifying `use_ssl` is required for `start_tls` to work. Or to not require both options set.

**Why is this needed**:
When setting up Grafana to use LDAP login it took me a while to work out I needed both the `use_ssl` option and the `start_tls` option set to true. I only worked it out by looking at the code: https://github.com/grafana/grafana/blob/master/pkg/services/ldap/ldap.go#L114-L123
Almost all applications I have come across separate these options as STARTTLS works differently to LDAPS.

**Comment by sakjur** [comment]
Thanks for the feedback! I'm asking myself if there is a nice way for us to change this so that we aligned more with what other vendors are doing here without breaking anyone's configuration, but in lieu of that clarifying this in the docs would make sense.

**Comment by oddlittlebird** [comment]
@sakjur , can you provide content for this change?

**Comment by sakjur** [comment]
@oddlittlebird It's quite a bit away from anything I've worked with, but I wrote #29964 to have _something_ that mentions this.
