### ISSUE TITLE
Log panel shows incorrect level indicator

### ISSUE THREAD

**Issue by richard-lawrence** [grafana/grafana#22075]
**What happened**:

The log panel indictor on left hand side shows this log message as critical even though warning is specified at the beginning of the log message, looks like it's picking up critical from further down the log message which actually says "Non-critical".

<img width="1294" alt="Screenshot 2020-02-10 at 10 23 19" src="https://user-images.githubusercontent.com/56631278/74170659-2b2b9980-4c25-11ea-8dd0-fb48bfd3a30e.png">

**What you expected to happen**:

Log level indicator should use first occurrence of log level in the log message.

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: InfluxDB 1.7.9
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
Looks like a bug in the function below where it tests for the different log levels by falling order of severity. There is a test that makes sure `warn` is not overridden by a later occurrence of `debug`, so it handles lower priorities correctly, but not higher priorities.
 https://github.com/grafana/grafana/blob/ffdbe60da0132dba5f93aed822821ee4048e2f61/packages/grafana-data/src/utils/logs.ts#L19-L33

**Comment by jcdauchy** [comment]
Would it be possible to add a tag or field to define logLevel instead of parsing the message field ?
So that we don't need to add the level in the message.

Thanks

**Comment by sakjur** [comment]
@jcdauchy That's already supported by the log panel. Not sure if it's supported by all datasources. It's also a bit off-topic for the bug since it's a somewhat tangential feature which wouldn't solve the bug. If the feature is missing in your datasource please open a separate feature request for that 🙂
