### ISSUE TITLE
News panel should follow redirects

### ISSUE THREAD

**Issue by acobaugh** [grafana/grafana#22079]
**What happened**:

Entered a URL into a News panel. Panel reports `Error Loading News`

URL entered: `https://psu.box.com/public/static/jf36ohodxnw7oemghsau1t7qb0w4y708.rss`

This URL returns a 301 with a Location response header. Following that returns a 302 with a Location response header containing the final url, which I suspect is subject to change.

**What you expected to happen**:

RSS feed should be displayed

**How to reproduce it (as minimally and precisely as possible)**:

Provide a URL that returns a 301 or 302.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Enterprise v6.6.1
- Data source type & version: n/a
- OS Grafana is installed on: public grafana-enterprise docker image
- User OS & Browser: Chrome  79.0.3945.130 on Linux
- Grafana plugins: n/a
- Others: n/a

**Comment by sakjur** [comment]
When I set up a 301->302->200 chain and tries it with Safari 13.0.4 and Chrome 80.0.3987.87 on MacOS it follows the redirects and shows the feed correctly. However when I try with the feed that you're using I'm getting a CORS error.

If you open the F12 developer tools in Chrome and press then `Console` tab, do you see an error message like the following?

> Access to fetch at 'https://psu.box.com/public/static/jf36ohodxnw7oemghsau1t7qb0w4y708.rss' from origin 'https://plot.94.is' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by acobaugh** [comment]
Yep, you're right! I suppose this can be closed, as using a CORS proxy works. Sorry for the noise!
