### ISSUE TITLE
Show long labels in Explore table

### ISSUE THREAD

**Issue by avarsava** [grafana/grafana#22073]
**What would you like to be added**:
I have some very long labels. Tables in the Explore pane always cut them off. Please show the whole label. I am using Loki metrics.

![image](https://user-images.githubusercontent.com/17747491/74168235-67e09c00-4bf7-11ea-83c6-766980bab2fb.png)

**Why is this needed**:
The value I am calculating with my query is without context if I do not know what the label holds.

**Comment by dprokop** [comment]
Fixed with https://github.com/grafana/grafana/pull/27669
