### ISSUE TITLE
Alert sampling interval does not respect minimum time interval

### ISSUE THREAD

**Issue by icy-arctic-fox** [grafana/grafana#22082]
**What happened**:
An alert isn't working as expected. We want an alert to be triggered when the number of documents matching the search criteria exceeds the specified amount. For instance, more than 3 errors in a minute.
The query used to test the alert rule has an interval of 200 ms. This is far too granular for our sampling interval. The minimum time interval for the data source is 30s. The minimum time interval of the graph is 1m. The alert does not get triggered because of this. The interval used by the graph doesn't match the one used by the alert.

**What you expected to happen**:
The alert is triggered based on the minimum time interval. Typically this would be the maximum of the minimums. For example: the data source is 30s and the graph is 1m - the alert should use a query with a 1m interval. The interval for the alert should match the graph's interval.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a data source with a minimum time interval (30s).
* Create a graph panel.
  * The metric should be count or unique count.
  * Set the graph's minimum interval to 1m.
* Create an alert for the panel.
  * The rule should be something like `WHEN max() OF query(A,5m,now) IS ABOVE 3`
  * Test the rule. Inspect the request, which shows an interval of 200ms.

**Anything else we need to know?**:
This can be worked around by setting the interval of the date histogram to something other than auto. However, this is undesirable, since we can no longer change the dashboard time range and have a graph that isn't packed with sub-pixel bars.

The data source:
![image](https://user-images.githubusercontent.com/16712558/74191484-ee55a780-4c10-11ea-9701-2dbad98bd2f6.png)

The metric:
![image](https://user-images.githubusercontent.com/16712558/74190873-47710b80-4c10-11ea-84a7-20944747fa16.png)

The alert:
![image](https://user-images.githubusercontent.com/16712558/74190905-55bf2780-4c10-11ea-980e-2f34c47febe1.png)

Request query (from Test Rule output):
```
...
"date_histogram":{"field":"@timestamp","interval":"200ms","min_doc_count":0,"extended_bounds":{"min":"1581369398357","max":"1581369698357"},"format":"epoch_millis"}}}
...
```

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: Elasticsearch 7.5.2
- OS Grafana is installed on: Official Docker (Alpine) image
- User OS & Browser: Linux Mint 19 w/ Firefox 72
- Grafana plugins: grafana-worldmap-panel, grafana-clock-panel, grafana-piechart-panel, farski-blendstat-panel, jdbranham-diagram-panel, agenty-flowcharting-panel, goshposh-metaqueries-datasource, grafana-polystat-panel, snuids-radar-panel, grafana-simple-json-datasource, vonage-status-panel, flant-statusmap-panel, snuids-trafficlights-panel, fatcloud-windrose-panel
- Others: -

**Comment by sakjur** [comment]
Hello!

Thank you for the very good bug report. I was able to reproduce your scenario exactly and got the same problem (I used `count` as the basis of my alerts, which for 1m gave me 72 and for 200ms gave me a max of 12 with my test data set).

P.S. Your username is great 🙂 I really like arctic foxes

**Comment by simianhacker** [comment]
Looks like there is a bug in the Go code where the `auto` is replaced with `$__interval` then when the request is being processed it calculates the auto interval but doesn't check to see if it's larger than the minimum interval set by the datasource. It appears the minimum interval value is not available in the part of the code where the string replace is happening.

**Comment by simianhacker** [comment]
I believe I found a way forward now that I have some experience with working on the Golang parts of the Elasticsearch datasource. I should have a PR in a few days.
