### ISSUE TITLE
Add annotations from within Grafana (graphite events back end)

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#2208]
Grafana Annotations + Graphite Events are really an awesome combo, I think it'd be even more awesome if users could create annotations/graphite events from within Grafana graphs. I imagine clicking on a time showing in the (x) axis and a popup menu would show "add event", I click on it I'm taken to a basic form (time set to the time I clicked on) that I fill (e.g. That's when Murphy unplugged rack 104), validate and voila I go back to my graph and my annotation is automagically there!

**Comment by pdf** [comment]
Dupe of #1286?

**Comment by jaimegago** [comment]
yup, closing
