### ISSUE TITLE
Include all AWS/DocDB Metric Dimensions 

### ISSUE THREAD

**Issue by brad-plumewifi** [grafana/grafana#22081]
**What would you like to be added**:
Per: https://docs.aws.amazon.com/documentdb/latest/developerguide/cloud-watch.html#metrics-dimensions there are metrics available for DBInstanceIdentifier and Role.  These dimensions do not appear to be available with Grafana's AWS/DocDB CloudWatch integration -- only DBClusterIdentifier seems to be available as of Grafana 6.6.1 

**Why is this needed**:
The DBClusterIdentifier dimension averages all metrics across an entire cluster.   We need to be able to view metrics specific to a Reader vs. a Writer (Role) for things like MaxConnectionCounts, read vs. write latency, etc.  This is also useful for pinpointing application anomalies (latency, errors, etc) that may be cause by a specific DocumentDB Instance within the cluster (DBInstanceIdentifier)

**Comment by brad-plumewifi** [comment]
<img width="313" alt="awsdocdb" src="https://user-images.githubusercontent.com/29928973/74189692-b8f78c80-4c05-11ea-88d6-2b0507f7a659.png">

**Comment by sakjur** [comment]
Looks like the additional options needs to be added here:

https://github.com/grafana/grafana/blob/ffdbe60da0132dba5f93aed822821ee4048e2f61/pkg/tsdb/cloudwatch/metric_find_query.go#L142

This is something that someone in the community could do and submit as a pull request if they want this to happen faster 🙂

**Comment by marefr** [comment]
@brad-plumewifi as a workaround you should be able to input custom dimension by writing it, for example `DBInstanceIdentifier`.

**Comment by vikkyomkar** [comment]
@sakjur I will make this change and create a PR soon.

**Comment by brad-plumewifi** [comment]
@marefr - Thanks for the workaround!

**Comment by brad-plumewifi** [comment]
Not sure if this needs a separate issue/enhancement, but, it doesn't look like I can query by more than 4 values/ dimensions when trying to turn this into a Template Variable Query either

Query: dimension_values(us-west-2, AWS/DocDB, CPUUtilization, DBClusterIdentifier, Role) returns a

"Templating: Template variables could not be initialized: JSON.parse: unexpected character at line 1 column 1 of the JSON data" error.  

Doesn't look like it's letting me add more than 4 fields.
