### ISSUE TITLE
Datasource: Error deleting corrupt datasource from UI

### ISSUE THREAD

**Issue by pkesso** [grafana/grafana#22090]
**What happened**:
After installing faulty datasource it is impossible to delete it via web ui, but possible via api.
Error message: Missing valid datasource

**What you expected to happen**:
Deletion of datasource.

**How to reproduce it (as minimally and precisely as possible)**:
- install grafana-json-datasource 0.1.7 plugin
- add datasource "Json" (with error: Unexpected token < Evaluating <grafana>/public/plugins/simpod-json-datasource/module.js Loading plugins/simpod-json-datasource/module
Data Source Error)
UPD: here I should notice, that I installed plugin the wrong way, which caused problem with datasource - it is not a bug. Bug is an impossibility to delete bad datasource.
- try to delete it by pressing "Delete button", get error "Missing valid datasource id"
- delete it by ID via api call:  curl -X DELETE <grafana>/api/datasources/38
{"message":"Data source deleted"}

**Anything else we need to know?**:

**Environment**:
- Grafana version: Version 6.6.1 (commit: 21bf8b71bc, branch: HEAD)
- Data source type & version: grafana-json-datasource 0.1.7 (https://github.com/simPod/grafana-json-datasource)
- OS Grafana is installed on: Oracle Linux Server release 7.6
- User OS & Browser: Fedora, Vivaldi (chromium)
- Grafana plugins: grafana-json-datasource 0.1.7 (https://github.com/simPod/grafana-json-datasource)
- Others:

**Comment by sakjur** [comment]
Hello, I seem to be unable to reproduce your second step.

How did you install the plugin? (You mention it was installed in the wrong way, what does that mean?)

**Comment by pkesso** [comment]
@sakjur download not 0.1.7 release, but master: https://github.com/simPod/grafana-json-datasource/archive/master.zip

**Comment by sakjur** [comment]
Thank you, now I was able to reproduce your problem
