### ISSUE TITLE
Select with allowCustomValue not allowing custom values

### ISSUE THREAD

**Issue by scottlepp** [grafana/grafana#22099]
**What happened**:
setting allowCustomValue on a Select component doesn't allow entering custom values

**What you expected to happen**:
allowed to enter custom values which are added to the select list

**How to reproduce it (as minimally and precisely as possible)**:
Test it in StoryBook:
![image](https://user-images.githubusercontent.com/6108819/74249954-edc41c00-4cb7-11ea-8530-52c20ae9add7.png)

**Environment**:
- Grafana version: 6.6.1
- OS Grafana is installed on:  macOS
- User OS & Browser:  macOS Chrome

**Comment by torkelo** [comment]
think this was recently fixed in master. Can you try against lastest @grafana/ui canary

**Comment by torkelo** [comment]
Testing this in 6.6.1 seems to also work, so think this bug was only in @grafana/ui canary for a while

**Comment by dprokop** [comment]
Yes, this is fixed by @tskarhed
