### ISSUE TITLE
CloudWatch metric names with spaces causing queries to fail

### ISSUE THREAD

**Issue by jveldboom** [grafana/grafana#22104]
**What happened**:
When using the metric picker to display metrics for AWS Managed Streaming Kafka (MSK) service, none of the dimensions work (`Broker ID`, `Cluster Name`). The UI displays a message at the top saying:

```
ValidationError: Invalid SEARCH parameter: {AWS/Kafka,Broker ID,Cluster Name} MetricName="CpuUser" "Cluster Name"="service-prod" status code: 400, request id: 7878b7aa-55eb-4fa4-9297-19d62482eafe
```

After copying the query into CloudWatch, the issue appears to be due to the dimensions have a space in them and not being wrapped in double-quotes.

For example, within CloudWatch this returns values:
```
SEARCH('{AWS/Kafka,"Broker ID","Cluster Name"} MetricName="CpuUser" "Cluster Name"="service-prod"', 'Average', 300)
```

But this does not. Actually causes the page to display `There was an error while trying to get graph data.`
```
SEARCH('{AWS/Kafka,Broker ID,Cluster Name} MetricName="CpuUser" "Cluster Name"="service-prod"', 'Average', 300)
```

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

**Comment by sakjur** [comment]
Thank you for the report.

The bug is that we're not surrounding the dimension with `"` when there's a space in the dimension name? Definitely sounds like something we should fix. If someone from the community would like to beat us to fixing it, the approach I would try would be to make sure that any value in the `dimensionValues` slice in the `*CloudWatchExecutor.handleGetDimensions` method (see code snippet below) that contains a space is surrounded by `"`.
 https://github.com/grafana/grafana/blob/df1d43167af035c6819923ecce135056f37c79c2/pkg/tsdb/cloudwatch/metric_find_query.go#L388

There is a possible workaround: If you manually type the dimension with quotes it should work, can you confirm that? (i.e. instead of picking Broker ID from the dropdown list, write `"Broker ID"` and hit enter).

**Comment by sunker** [comment]
I assume the problem occurs when Grafana is generating a search expression based on the selections that is made in the query editor. I agree that it's a bug and that it's fairly easy to fix. However the fix should not be done in `metric_find_query.go`, but in `metric_data_query_builder.go`. That's where the search expressions is generated. It would be great if someone from the community could take a stab at this. If not, we'll take a look at this this spring.

**Comment by jeet-parekh** [comment]
Can I pick this up?

**Comment by jeet-parekh** [comment]
Tried to study the code. I'm a bit confused where to fix it. There are two suggestions right now, but not decided yet.

1. `*CloudWatchExecutor.handleGetDimensions` inside `metric_find_query.go`
2. `metric_data_query_builder.go` - I guess it would be the function `buildSearchExpression`... right?

I guess adding double quotes directly to `dimensionsMap` inside `metric_find_query.go` could also work?

https://github.com/grafana/grafana/blob/df1d43167af035c6819923ecce135056f37c79c2/pkg/tsdb/cloudwatch/metric_find_query.go#L125

Which of these would be a proper fix?

**Comment by sakjur** [comment]
@sunker is part of the team that manages this code and knows much more about it than I do, so following his suggestion of adding it to the `_builder` file would be the preferred option.

Directly modifying the dimensionMap would have the disadvantage of being opaque and volatile. There would be no guarantee that the next time someone adds a dimension name with a space in that it would be handled correctly and we would have to resort to comments to explain why we’re deviating from CloudWatch’s naming. It would also look weird in the query editor (the name is `dimension name` not `”dimension name”` despite us having to escape it as the latter.

So out of your three options, 2 would be preferred.
