### ISSUE TITLE
[Feature request] keyboard shortcuts for switching between panel-editing tabs

### ISSUE THREAD

**Issue by petemyron** [grafana/grafana#22103]
It's quite tedious to manually edit a bunch of panels for the same purpose (for example, change the style on each, edit the query, etc.). It would be much easier if we could switch between the different tabs when editing a panel with a keyboard shortcut.

For instance, hovering over a panel I want to edit, I hit 'e' (this exists already), then I want to go to the Query tab from whatever it's remembered so I hit '1' to go to that tab, '2' to go Visualization, etc.

Obviously, this still requires you to not be focused on a text input field, but would make editing more efficient.

**Comment by dprokop** [comment]
@petemyron Hi, thank's for this feature request! We are currently in a process of redesigning the editor experience, and will take this request into consideration! But the problem you are describing here might not be an issue anymore with the new panel editor, as there will be no tabs for switching between queries and visualisation setting, and both of theses will be available at the same time,
