### ISSUE TITLE
Handling of dashboards with no pre-selected varibale

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2210]
Is it possible for Grafana to have better handling for template variables that arent pre-filled? My expectation is that it would just select the first item in the list, but currently it just is null. 

![grafana-load-endpoint](https://cloud.githubusercontent.com/assets/2886187/8294421/896736ec-190a-11e5-8f55-81a1b0d5853b.gif)

**Comment by torkelo** [comment]
wil fix, this worked in 2.0 but have rewritten a lot of this to handle multi value selection (and tags)

**Comment by torkelo** [comment]
Cant replicate this @mattttt , can you show me the json for the dashboard?

**Comment by torkelo** [comment]
The json has a small bug in it. 

```json
 "templating": {
    "list": [
      {
        "allFormat": "glob",
        "current": {},
        "datasource": null,
        "includeAll": false,
        "label": "Endpoint",
        "multi": false,
        "multiFormat": "glob",
        "name": "endpoint",
        "options": [
```
remove the empty  "current": {},  line
