### ISSUE TITLE
how to config "Message field name" in datasource to get multiple filed by elasticsearch

### ISSUE THREAD

**Issue by missyoyo** [grafana/grafana#22116]
**What happened**: When config one filed in "Message field name",get correctly log view, But we need get multiple filed in elasticsearch,We just get "NULL",We know  elasticsearch support this by _source filter eg:{"_source": ["code","host"]},How did we config "Message field name" to support this?

**What you expected to happen**:I have test by firefox develp tools, default qury by grafana is :
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"knot"}
{"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1581496038356","lte":"1581499638357","format":"epoch_millis"}}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"aggs":{"2":{"date_histogram":{"interval":"1s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1581496038356","max":"1581499638357"},"format":"epoch_millis"},"aggs":{}}}}
I have add {"_source": ["code","host"]} and resend query to elk like this:
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"knot"}
{ **"_source": ["code","host"]**,"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1581478916264","lte":"1581500516264","format":"epoch_millis"}}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"aggs":{"2":{"date_histogram":{"interval":"15s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1581478916264","max":"1581500516264"},"format":"epoch_millis"},"aggs":{}}}}

I get only two filed:code and host, So how can we config "Message field name" to get corrently two filed?
**How to reproduce it (as minimally and precisely as possible)**:

![图片](https://user-images.githubusercontent.com/19371588/74323567-ad03fa00-4dc0-11ea-800f-b6c7278418e4.png)
![图片](https://user-images.githubusercontent.com/19371588/74323594-b68d6200-4dc0-11ea-938d-b42670b94af4.png)
![图片](https://user-images.githubusercontent.com/19371588/74323604-bc834300-4dc0-11ea-8165-b884b0ea71f2.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.6.1
- Data source type & version:elasticsearch 7.5.2
- OS Grafana is installed on:ubuntu18.04
- User OS & Browser: firefox 71
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
Hello, this looks like a question, which are best asked on https://community.grafana.com . GitHub issues are specifically used for bugs and feature requests rather than questions on Grafana 🙂
