### ISSUE TITLE
Using a unix socket for postgres data source (invalid URL escape 2F (/))

### ISSUE THREAD

**Issue by elansys-kc** [grafana/grafana#22119]
Grafana 5.4.3 on OpenBSD 
Issues #12644 #2818 #4030 and #11055 may be related.

When setting up a datasource for postgresql and using /tmp as host for unix socket use, a metric request error is reported.

The logs show invalid URL escape \"%2F\".

Perhaps a socket check box could insert a grayed out / in the host field, if security is a concern?

**Comment by sakjur** [comment]
Hello, Grafana 5.4.3 is more than a year old, is it possible for you to upgrade your Grafana version and see if it works on 6.6.1?

Following the template on https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md makes it easier for us to correctly reproduce and classify the issue you're reporting.

**Comment by elansys-kc** [comment]
I shall look into 6.6.1. I even looked for a template in the new issue interface! Maybe github needs some tips from Grafana ;-)

**Comment by elansys-kc** [comment]
Had to update the port but can confirm that the issue is present on 6.6.1.

**Comment by davehayes** [comment]
I'll confirm this issue is present on 6.6.2, using FreeBSD. 

Using unix domain sockets instead of loopback interfaces is a security upgrade. That's why we are doing this. :)

**Comment by phemmer** [comment]
Also ran into this issue.
@sakjur Is there any other information needed as it seems like the requested info was provided a few months ago, but this still has the "needs more detail" tag.

**Comment by aknuds1** [comment]
@phemmer I think it's mostly a question of finding the time, as we have been very busy with finishing version 7 lately. We also have a large backlog of issues to tend to :)

**Comment by elansys-kc** [comment]
On 18/05/2020 16:14, Arve Knudsen wrote:
> @phemmer <https://github.com/phemmer> I think it's mostly a question of finding the time, as we have
> been very busy with finishing version 7 lately. We also have a large backlog of issues to tend to :)

I believe it is a http form sanitization filter issue. The underlying golang postgres library works
with /tmp as host. I expect a workaround of host setup by config file would work and possibly even
configuration by http API, rather than html form. Depending on your scenario; This may or may not
help. I was using the form just for an initial test setup and will likely try the http api.

**Comment by mjerabek** [comment]
I have run into this too. I checked `grafana.db` and the entry in table `data_source` contains the correct unescaped path. Thus I do not think using API will help. (using v6.3.5)

**Comment by aknuds1** [comment]
@elansys-kc Do you mind specifying explicitly in the issue description how to reproduce the issue?

**Comment by aknuds1** [comment]
I can reproduce the error, but not sure yet from where it originates.

**Comment by aknuds1** [comment]
I have a PR that should fix this: https://github.com/grafana/grafana/pull/25778.
