### ISSUE TITLE
Generic_oauth role_attribute_path doesn't support == comparator

### ISSUE THREAD

**Issue by gmerciel** [grafana/grafana#22111]
**What happened**:
When using == comparator in _role_attribute_path_ insde _auth.generic_oauth_ it always returns false. So, having a userinfo like `{ "role": "admin", "sub": "admin" }` and _role_attribute_path_ `role == 'admin' && 'Admin' || 'Editor'` leads to _Editor_ role being assign.

I also tried `"""role == 'admin' && 'Admin' || 'Viewer'"""` with the same result.

**What you expected to happen**:
With this configuration the role should be assigned as _Admin_. Testing the [JMESPath](http://jmespath.org/) gives the correct result.

**How to reproduce it (as minimally and precisely as possible)**:
Use a == comparator on the _role_attribute_path_ configuration.

**Anything else we need to know?**:
You could workaround this issue using the _contains_ function like this: `contains(role, 'admin') && 'Admin' || 'Viewer'` but it would also match other roles that have the word _admin_ on its name.

**Environment**:
- Grafana version: 6.6.1
- OS Grafana is installed on: docker
- User OS & Browser: Windows 10 - Chrome

**Comment by sakjur** [comment]
I copied your `role_attribute_path` to my configuration file and that worked for me (both on master and 6.6.1). If you don't want your workaround to match say 'notadmin' you can use `contains([role], 'admin') && 'Admin' || 'Viewer'` instead.

What settings do you have which differs from the default?

**Comment by gmerciel** [comment]
Now it seems to be working, I dind't change anything else, I don't know what happened, I'm really sorry for bothering you guys, I honestly just wanted to get documented the problem I had for other people reference. Thanks for taking the time!

**Comment by sakjur** [comment]
Great that it started working 😄 It's always good for us to know what parts our users are bothered by, so rather one issue about something which isn't a bug than a bug with no issue 🐛
