### ISSUE TITLE
ElasticSearch filter variable stored and prevents further filtering

### ISSUE THREAD

**Issue by michael-doubez** [grafana/grafana#22114]
**What happened**:

In the process of designing a dashboard using a ElaticSearch backend, I filtered a field using the (+/-) selector in a Table panel. Then I saved the panel `Save current variables` disabled. When I reload the panel, there is an empty `Filter` display and I can no longer select a filter by clicking on the (+/-) selector in the Table panel.

**What you expected to happen**:

I expected that the filter would be reset or at least that I could continue to use it without bothering about it.

The workaround I have found is to go in the dashboard settings and remove the variable by hand before saving the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a Table panel pulling data from ElasticSearch
2. Filter on a value from a cell value - using the +/- selector
3. Save the panel without `Save current variables`
4. Reload the panel
5. Try to filter again - doesn't work
6. Remove the filter variable in Settings
6. Try to filter again - it works

Looking into the console of Chrome I get

```
angular.js:14800 TypeError: Cannot read property 'replace' of undefined
    at e.escapeDelimiter (plugin_page_ctrl.ts:24)
    at plugin_page_ctrl.ts:18
    at Array.map (<anonymous>)
    at plugin_page_ctrl.ts:18
    at Array.map (<anonymous>)
    at e.getValueForUrl (plugin_page_ctrl.ts:17)
    at template_srv.ts:364
    at Ye (lodash.js:516)
    at Function.qa (lodash.js:9341)
    at e.fillVariableValuesForUrl (template_srv.ts:354) "Possibly unhandled rejection: {}"
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: ES 7.2.0
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: Not related
- Others: A/A

**Comment by sakjur** [comment]
Hello,

Would it be possible for you to share screenshots of the key steps?

**Comment by michael-doubez** [comment]
Sorry. I definitely had the issue but I don't seem to be able to reproduce it anymore.
Maybe a file kept in cache of my browser.

**Comment by michael-doubez** [comment]
I will re-open if needed

**Comment by IzekChen** [comment]
+1 have the same issue

**Comment by IzekChen** [comment]
@sakjur 
The way to reproduce it is that try to add and remove the ad-hoc filter.
while you have the filter, try to change the drop down variable, then the error will pop up.
And the URL will remain the same, not bring the option you choose as a parameter to the url
