### ISSUE TITLE
Time picker closes if a month or year is chosen (rather than a calendar date)

### ISSUE THREAD

**Issue by csimon-psiphon** [grafana/grafana#22110]
**What happened**: When trying to enter an absolute time range for the time picker
 (located under the clock widget on the home page), I tried to select an earlier date by first looking at all the months and then selecting the one I wanted. After selecting the month, the time picker closes.

**What you expected to happen**: I expected the time picker to show me the all calendar days (1-31) of the month I selected.

**How to reproduce it (as minimally and precisely as possible)**:
1. go to grafana's create dashboard home page
2. open the time picker (clock widget drops down the time picker)
3.  click on 'Absolute time range > from' input box (calendar opens)
4. click the month (February 2020)
* all the months should display in the calendar with February highlighted
5. click January => time picker closes after clicking

**Anything else we need to know?**: this also happens with years.

**Environment**:
- Grafana version: 6.6.1 release
- Data source type & version: n/a
- OS Grafana is installed on: macOS Catalina (v10.15.3)
- User OS & Browser: macOS Catalina (v10.15.3) on Chrome 78.0.3904.108
- Grafana plugins: n/a
- Others:

**Comment by sakjur** [comment]
@mckn Related to, but does not appear to be exactly same as, #21981.

**Comment by mckn** [comment]
Thanks for reporting this, will be fixed in next release 🙌
