### ISSUE TITLE
Alert rules page: Jumps to top of page when (un)pausing

### ISSUE THREAD

**Issue by e2-jakob** [grafana/grafana#22127]
**What happened**:
In version 6.5.3, when pausing or un-pausing an alert on the alert rules page (/alerting/list), the browser jumps to the top of the page.

This is really annoying when pausing several alerts in one go, having to scroll down again for each.

**What you expected to happen**:
In an older version, the browser stayed where it was on the page.

**Environment**:
- Grafana version: 6.5.3
- User OS & Browser: Ubuntu, Opera 66

**Comment by sakjur** [comment]
Thank you for your bug report. I've confirmed that this happens in my local copy (near master) on Safari 13.0.4.

**Comment by orojina** [comment]
@e2-jakob  In case you find this useful, and as a temporary solution,  I created a script to pause and resume alerts. Pausing several alerts can be done with:

`grafana-cli alerts pause <alerts_to_be_paused`

https://github.com/orojina/grafana-cli
