### ISSUE TITLE
Have cancelled HTTP Request Cancel Corresponding Database Queries

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#22123]
**What would you like to be added**:
When an HTTP request to Grafana-server is cancelled, if there are corresponding queries to Grafana's SQL database, those should also be cancelled. In particular, in the case of a timeout.

**Why is this needed**:
We are concerned that if queries are timing out against SQL because of the database system being too busy, SQL queries will continue to run and build up in the database system as more HTTP requests come in, even though the results of that SQL query will not be used.

More investigation is needed:

- Can we do this, does Go SQL support it, and do our supported database drivers support it?
- Are there certain queries (write) that we wouldn't want to cancel/rollback?

**Comment by ethirolle** [comment]
For Postgres: I believe we are using the `pq` library (per https://github.com/grafana/grafana/blob/master/go.mod#L58). 

This old `pq` PR seems to add the capability to cancel running queries from the client side:
https://github.com/lib/pq/pull/535

A couple of notes from the writer of that PR:

>A cancelled context will prevent new queries and halt currently running
queries.

>No, it does indeed cancel queries on the server. See the conn.Cancel function in conn.go. It opens a new connection instructing the server to cancel the original connection. See https://www.postgresql.org/docs/current/static/protocol-flow.html#AEN112861

Can we take advantage of that?

(The same thing may not be possible in MySQL, not sure.)

**Comment by mdvictor** [comment]
I introduced a PR that fixes this issue for the SQL based datasources, since they all use the same ORM. The `xorm` package used on the grafana backend has a method which deals with this exact situation and only needs the request context passed to it. 
When a client cancels a request from the browser, the ORM knows to also cancel it on the SQL server.
Fix is in this PR: https://github.com/grafana/grafana/pull/43890

**Comment by mdvictor** [comment]
I think this can also be closed with #43890 being merged to main.
