### ISSUE TITLE
viper configuration system

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2212]
i recently came across this https://github.com/spf13/viper

it's a config system that supports quite a variety of config mechanism and has a precendece system:
in this order:
```

    explicit call to Set
    flag
    env
    config
    key/value store
    default
```

maybe useful for grafana, maybe not. just thought you might want to have a look.

**Comment by torkelo** [comment]
looks interesting, but does support ini config file format that grafana use now. Do now want to release an new version of Grafana with new config syntax. 

On top of the ini config reader I have added the ability to override any option via command line, set defaults via command line, and via environment 

so the chain goes like this
defaults read from defaults.ini
default overrides read from command line
(init logging)
load specified config file (/etc/grafana/grafana.ini or conf/custom.ini)
apply environment setting overrides 
apply command line setting overrides
eval config values (config values can contain ENV variable expressions)
