### ISSUE TITLE
@grafana/toolkit:canary leaves behind .d.ts files

### ISSUE THREAD

**Issue by srclosson** [grafana/grafana#22134]
**What happened**: The toolkit build process leaves .d.ts files in the source directory

**What you expected to happen**: The source directory should be clean

**How to reproduce it (as minimally and precisely as possible)**: Use canary of @grafana/toolkit
Run `yarn build` or `yarn dev`, both will leave files behind.

**Comment by stevenvachon** [comment]
I believe that this was fixed by #22228. @ryantxu
