### ISSUE TITLE
Error on anonymous access to grafana

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2213]
While waiting for LDAP Auth , I will setup on production a Grafana 2.X , but I need this can run as closest as possible to Grafana 1.X . ( but user should only view -- not modify -- dashboards).

I've configured security and access as follows.

```

[security]

admin_user = admin
admin_password = XXXX

[users]
allow_sign_up = false

[auth.anonymous]
enabled = true
org_name = MyORG
org_role = Viewer
```

But when trying to access as non admin user as
```
user: anonymous
pass: <any_password>
```

 I got this error.

```
2015/06/23 12:07:20 [login.go:94 LoginPost()] [E] Invalid username or password: User not found
2015/06/23 12:07:20 [I] Completed /login 401 Unauthorized in 1.334ms
2015/06/23 12:07:20 [login.go:94 LoginPost()] [E] Invalid username or password: User not found
2015/06/23 12:07:20 [I] Completed /login 401 Unauthorized in 881Âµs
2015/06/23 12:07:35 [login.go:94 LoginPost()] [E] Invalid username or password: User not found
2015/06/23 12:07:35 [I] Completed /login 401 Unauthorized in 1.398ms
2015/06/23 12:07:35 [login.go:94 LoginPost()] [E] Invalid username or password: User not found
2015/06/23 12:07:35 [I] Completed /login 401 Unauthorized in 882Âµs
```

Should I create a anonymous user?
Can I create an anonymous user without password?

**Comment by torkelo** [comment]
yes, if anonymous is enabled and org_name matches a real organization then you should be able to view dashboard without logging in (do not go the login page, go to ŕoot url)

**Comment by toni-moreno** [comment]
Thank you very much @torkelo , running ok now!
