### ISSUE TITLE
CloudWatch: Upgrade AWS Go SDK to prevent memory leak

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#22138]
**What happened**:

We migrated our grafana server from instances in EC2 to a Fargate ECS setup in a different account. In doing so, we copied many cloudwatch data sources from the old system to the new system. Unfortunately, not all of these data sources have the proper access policy in the remote account so the STS calls return errors. That's all fine and dandy, but this situation is combined with a bug in the aws-go-sdk and it's causing my ECS containers to exhaust all their memory on a daily basis. They crash and my Grafana service availability takes a dive.

**Here's the bug fix:** https://github.com/aws/aws-sdk-go/pull/3127

The recommend action is to upgrade the aws-sdk-go library to 1.29.1.
ie. this should solve the problem: 
```
go get -u github.com/aws/aws-sdk-go@v1.29.1
```

**What you expected to happen**:

The STS calls should return errors and Grafana should operate normally. Instead it's piling up go routines until the memory is exhausted.

**How to reproduce it (as minimally and precisely as possible)**:

I don't have a great story around how someone outside of my situation can reproduce this.

This will likely do it: 
- Create a dashboard full of CloudWatch metrics graphs from another account.
- Delete the policy from the other account that allows grafana access to the metrics.
- Reload the "now broken" dashboard until the service crashes.

**Anything else we need to know?**:

This SDK bug has been breaking apps all over the place. :(

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: CloudWatch (latest)
- OS Grafana is installed on: ECS Fargate using slightly modified grafana docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by davidnewhall** [comment]
Would you like a PR? This seems so trivial, I just figured someone would stick it into another PR. I can make one if it would help. Thanks!

**Comment by ryantxu** [comment]
Yes, a PR is super helpful :)

**Comment by marefr** [comment]
@davidnewhall is this still an issue?

**Comment by davidnewhall** [comment]
Of course. The bug still exists in all prior versions of the AWS Go SDK. I haven't had time to tackle this yet.

**Comment by Zophar78** [comment]
Is that so simple?

**Comment by davidnewhall** [comment]
Resolved with #23566.
