### ISSUE TITLE
Ability to create parent/child relationships between templating variables

### ISSUE THREAD

**Issue by craftytrickster** [grafana/grafana#2214]
Imagine the following two variable dropdowns, for *Vehicle Type* and *Vehicle* with the following queries

1. $VehicleType - `SELECT * FROM vehicle_type`
2. $Vehicle - `SELECT * FROM vehicle WHERE type = $VehicleType`

Vehicle Type  |  | Vehicle
--------- | --------- | ---------
Automobile  | | **Airbus**
Train  | | Boeing
**Airplane** | |
 
 
In our ideal fantasy world scenario, when the user clicks on Airplane, the Vehicle bucket would update its query results by updating the WHERE clause to search where type = airplane.
 
However, that would require a directed graph, where variables are explicitly derived from other variables. Grafana would have to know that Vehicle is explicitly derived from Vehicle Type.
 
Currently, that is not how Grafana works. Grafana considers variables as completely isolated from one another. However, we are forcing our variables to be linked by basically the variables’ query results on the values of other variables. That is why when we update a “base” variable like Vehicle Type, the child variables’ options (in this case, Vehicle) do not get updated correctly.
 
I think it would be very valuable to be able to explicitly create some kind of parent -> children chain. That way, when a parent variable is updated, all of its children can update their results based on the new selected parent value.

If anyone agrees or has any thoughts, please explain.

**Comment by torkelo** [comment]
parent child relationships between variables has existed in Grafana since version 1.6 (or 1.7c can remember). 

The only requirement is that parents needs to be defined first in the list of template variables. 
http://play.grafana.org/dashboard/db/templated-graphs-nested

**Comment by torkelo** [comment]
or this dashboard for a an example of nested template variables that use influxdb
http://play.grafana.org/dashboard/db/influxdb-templated-queries

**Comment by craftytrickster** [comment]
I had taken several attempts but they did not seem to work, which is why I opened the ticket. I will try again, sorry for the unnecessary ticket.

**Comment by torkelo** [comment]
@craftytrickster let me know if you have any issues (maybe something related to InfluxDB), show your queries and the influxdb response   (and how the queries are interpolated before being sent to influxdb)

**Comment by craftytrickster** [comment]
I noticed that the sample apps are using the template variable in the series body
`list series /apps.$app.*/`

Whereas I am using the variable outside of a series body (in a where clause)
`show tag values from "application.random.statistic" with key=application where host='$host'`

Is it possible that the template only works in a series body name? If so, is it by design?

*Not sure if this is related, but the queries in the samples seem to be using an older templating variable module than what is currently in master.*

**Comment by torkelo** [comment]
It does not matter where you use the template variable , it is just string substitution. Check the query being issued to InfluxDB

**Comment by torkelo** [comment]
Yes, templating as been given a big update on 2.1 to support multi value variables (and value group/tags)

**Comment by craftytrickster** [comment]
If I can find actual conclusive evidence to what is causing the problem, I will let you know. For now it makes sense to keep the ticket closed.

**Comment by craftytrickster** [comment]
It turns out that this issue has been solved by the following two items:

[Added fix for template variables when no options are available to select](https://github.com/grafana/grafana/pull/2243)

[Bug: New template variable select dropdown and cascading update](https://github.com/grafana/grafana/issues/2215)

**Comment by marpita** [comment]
How I can create parent/child relationships between templating variables using Neo4j as a datasource ?
This query doesn't work:

$Team -->  MATCH (n:RALLYTASK) where n.Iteration is not null and n.Project is not null RETURN distinct n.Project

$Sprint --> MATCH (n:RALLYTASK) where n.Iteration is not null and n.Project in $Team RETURN distinct n.Iteration
