### ISSUE TITLE
Panel as a datasource

### ISSUE THREAD

**Issue by kolobaev** [grafana/grafana#22154]
Hello!
In one of the previous releases, we rolled out a feature: the panel is like a datasource, but this thing only works within one Board, and in my case it is completely useless. Are there any initiatives to expand this feature to other boards?

I have 100 dashboards with business metrics of different services of the same business vertical. top managers want to get a summary dashboard for the main metrics and these 100. Now it is very difficult to do this, and it is almost impossible to support it. The panel as a datasource would be very helpful.

Very relevant!

**Comment by torkelo** [comment]
Not sure what your looking for, a shared set of queries across many dashbards, or a shared panel that can be updated in one location. 
If it's the later we already have feature request for that (and hope to implement it sometime later this year)

**Comment by torkelo** [comment]
closing due to lack of update
