### ISSUE TITLE
Decimal precision is wrong in tooltip

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#22157]
**What happened**: The value in tooltip use the wrong decimal precision

**What you expected to happen**: The value in tooltip should use the decimal precision specified in settings

**How to reproduce it (as minimally and precisely as possible)**:

1. Display a decimal value (with at least 3 numbers)
2. Set 2 in decimal precision
3. Look the value in tooltip

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/5497623/74412445-bc755880-4e3d-11ea-9ceb-5ccfe97d91a0.png)

**Environment**:
- Grafana version: 6.6.1
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
the decimals setting here is only for the y axis.  The reasoning here is that you likely want more precision in tooltip/legend then y axis tick labels. 

To control the decimals in legend & tooltip set decimals in the legend section

**Comment by Eraac** [comment]
@torkelo ok, legit but why when I update in Y axis section, that change the value too?

If a set 1 -> value display 2 decimal
If a set 2 -> value display 3 decimal
...

**Comment by torkelo** [comment]
by default the tooltip will show one more decimal than the y axis ticks
