### ISSUE TITLE
Fuzzy search on metric names in the Explore view.

### ISSUE THREAD

**Issue by jzandbergen** [grafana/grafana#22164]
Hi all,

First of, grafana is awesome and nothing compares to it. But there is this one thing that would make the Explore view much better imho:

**What would you like to be added**:
I would like to be able to do a sort of fuzzy search in the Explore view on metric names. 

**example**:
We just had an issue where we noticed an unusual amount of high bandwidth usage. So quickly we wanted to know what was using this bandwitdh. I didn't know the exact metric but i did know the metricname contains the words `node` and `transmit`.

I went to the explore view and entered `node` and `transmit` in the `Enter a PromQL query` hoping to find the actual metric needed called `node_network_transmit_bytes_total` but the search found zero results. 

It seems that the metric search functionality in the Explore view only matches on metrics that begin with the text entered. So instead of scrolling through a looooong list of `node_*` I resorted to the prometheus web interface where i entered `node` and `transmit` and lo and behold... there was the needle in the haystack `node_network_transmit_bytes_total` that led us to cause of the issue.

**Why is this needed**:
To quickly find a needed metric name to get to the bottom of things.

Thanks for your time and consideration.

**Comment by sakjur** [comment]
:wave:

Thank you for the kind words and for the feature request 😄

That sounds like a nice feature. There is already some support for filtering out variable names anywhere in the name (so writing `transmit` should give you `node_network_transmit_bytes_total` in the list), so adding fuzzy matching to that sounds like a great way of improving UX.

**Comment by wonko** [comment]
Can I somehow upvote this request? After upgrading to v7, the Explore and Dashboard creation/adaption became a lot less pleasant.

**Comment by janmartijn** [comment]
I'd like to upvote this too. Thx.
