### ISSUE TITLE
Unhandled Dashboard Creation UI Exceptions on Error

### ISSUE THREAD

**Issue by tranceitionalMynd** [grafana/grafana#22167]
- What Grafana version are you using?
Grafana - 6.6.1
- What datasource are you using?
Python Prometheus client prometheus-client==0.7.1  connected via grafana backend proxy.
- What OS are you running grafana on?
CentOS 7.6
- What did you do?
Create and test an example Prometheus data source in the add data source dialogue, then attempt to create a dashboard with the data source.
- What was the expected result?
I'm expecting to receive useful error messages about anything that went wrong during dashboard creation.  
- What happened instead?
Since I don't have helpful error messages from the server-side journald logs and UI I am stuck and don't know what to do
![image](https://user-images.githubusercontent.com/13026009/74433929-ff780180-4e26-11ea-8e84-e5f76fc69415.png)

![image](https://user-images.githubusercontent.com/13026009/74434018-29312880-4e27-11ea-95ed-13d7ada36247.png)

```
Query Inspector output:
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/3/api/v1/query_range?query=*&start=1581573940&end=1581595540&step=20"
  },
  "response": "# HELP process_virtual_memory_bytes Virtual memory size in bytes.\n# TYPE process_virtual_memory_bytes gauge\nprocess_virtual_memory_bytes 3.88800512e+08\n# HELP process_resident_memory_bytes Resident memory size in bytes.\n# TYPE process_resident_memory_bytes gauge\nprocess_resident_memory_bytes 1.2894208e+07\n# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.\n# TYPE process_start_time_seconds gauge\nprocess_start_time_seconds 1.58159180755e+09\n# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.\n# TYPE process_cpu_seconds_total counter\nprocess_cpu_seconds_total 0.9099999999999999\n# HELP process_open_fds Number of open file descriptors.\n# TYPE process_open_fds gauge\nprocess_open_fds 7.0\n# HELP process_max_fds Maximum number of open file descriptors.\n# TYPE process_max_fds gauge\nprocess_max_fds 1024.0\n# HELP request_processing_seconds Time spent processing request\n# TYPE request_processing_seconds summary\nrequest_processing_seconds_count 7487.0\nrequest_processing_seconds_sum 3733.8360970020294\n# TYPE request_processing_seconds_created gauge\nrequest_processing_seconds_created 1.581591808555018e+09\n# HELP python_info Python platform information\n# TYPE python_info gauge\npython_info{implementation=\"CPython\",major=\"2\",minor=\"7\",patchlevel=\"5\",version=\"2.7.5\"} 1.0\n"
}
```
Raw Json
```
Object
state:"Error"
series:Array[0]
request:Object
app:"dashboard"
requestId:"Q107"
timezone:"browser"
panelId:2
dashboardId:null
range:Object
timeInfo:""
interval:"20s"
intervalMs:20000
targets:Array[1]
maxDataPoints:911
scopedVars:Object
cacheTimeout:undefined
startTime:1581595539962
rangeRaw:Object
timeRange:Object
from:p
to:p
raw:Object
error:TypeError
```
UI Traceback
```
PromLink.tsx:22 Uncaught (in promise) TypeError: Cannot read property 'request' of undefined
    at t.<anonymous> (PromLink.tsx:22)
    at tslib.es6.js:99
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at l (tslib.es6.js:69)
    at t.componentDidUpdate (PromLink.tsx:21)
    at react-dom.production.min.js:251
    at e.unstable_runWithPriority (scheduler.production.min.js:18)
    at Gi (react-dom.production.min.js:120)
```
UI source
```
export default class PromLink extends Component<Props, State> {
  state: State = { href: null };
  async componentDidUpdate(prevProps: Props) {
    if (prevProps.panelData !== this.props.panelData && this.props.panelData.request) {
      const href = await this.getExternalLink();
      this.setState({ href });
    }
  }
```
It looks like the Prometheus functions for the different visualization types are all missing undefined property guards.
I get this console error for gauges:
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
```
From
```
    if (prevProps.panelData !== this.props.panelData && this.props.panelData.request) {
```
And this console error for a graph
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
```
From
```
    this.lookupsDisabled = this.metrics.length > this.lookupMetricsThreshold;
```
What I'm hoping for as a user is to know if I have any server side config, UI user errors, or Prometheus compatibility issues so I can address them, but I'm not sure what's happening or how to proceed.

**Comment by torkelo** [comment]
Your Prometheus server is not returning valid responses, are you using a standard prometheus server? What version? If not make sure your fake Prometheus server behaves 100% the same as a prometheus server

**Comment by tranceitionalMynd** [comment]
> Your Prometheus server is not returning valid responses, are you using a standard prometheus server? What version? If not make sure your fake Prometheus server behaves 100% the same as a prometheus server

Hi @torkelo, I'm getting started with both Prometheus and Grafana.  While it might seem silly, unhandled UI exceptions will just add to user confusion.  I'm not requesting that you teach me about Prometheus, but address the unhandled exceptions and user experience with your UI so you will get less tickets from user confusion.

**Comment by torkelo** [comment]
if you hover over the error in the panel corner what does it say?

**Comment by torkelo** [comment]
There is no unhandled error that I can see (unhandled as in the UI crashes), There is an error in the query editor link component (with an error logged to console) (which we will fix, but unrelated to your query error). 

The error is with your prometheus server, returning very strange text strings. not sure what could be the cause.

**Comment by tranceitionalMynd** [comment]
Hi @torkelo It was something similar to the console error "Cannot read property 'length' of undefined".  For reference, I was using a Prometheus client (not the server) as the data source.  It was confusing that I could add the Prometheus client and "test" it in the add Data Source page just fine, and the query inspector wasn't reporting errors (I don't think that's the purpose now that I think about it).  Anyways, I don't think it's reasonable to code around every user issue, however my first time use was a bit confusing without some form of human readable feedback from the UI about my mistakes.

**Comment by torkelo** [comment]
So when we added the datasource you get a test success? Strange
