### ISSUE TITLE
Feature Request - checking more than 1 datasource at the same time

### ISSUE THREAD

**Issue by leoleovich** [grafana/grafana#2216]
Would be nice if I do not have to specify which datasource for graph Grafana should use.
For example I have 2 graphite hosts with standard web interface (graphite-web) and with sharded metrics on it (like test.test1 on 1 host and test.test2 on another).

We want to set test.* and see both.

Thank you.

**Comment by torkelo** [comment]
this feature exist in graphite-web  (you can cluster graphite-web instances so they query each other)

**Comment by leoleovich** [comment]
Yes, but then Grafana will ask graphile, which will ask another graphite.
It is kinda slow.

**Comment by torkelo** [comment]
it will not be notably fast if grafana implemented this feature, the network calls happen in parallel
