### ISSUE TITLE
Form Input: size param should only affect padding, height & font-size

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#22161]
Our current Forms.Input size param has sm, md, lg options. Same values as for Button size. component size option with these names to me means that the component will be sized differently and in similar ways. 

So for our input this should mean more padding, height & font-size. Currently, this size option only controls width. Something that I think for input should be controlled using another prop width (grid width number (multiple of 8px), or auto if unset). 

Think we could have a use case for large inputs (like new panel edit title, login screen, etc) 

Think we should rename ButtonSize to ComponentSize

**Comment by mckn** [comment]
I would suggest to change so the size property works the same way as you explain that it does for the Button. 

Also - I think it would be worth setting some guidelines on what the component should be responsible for and what the context of the component should be responsible for. I think a good idea in this case would be to set the width of the component to 100% and then let the context you put it in to decide it width. 

This will make it reusable in lots if different scenarios without the need of overriding the components stylesheet.

**Comment by dprokop** [comment]
> Also - I think it would be worth setting some guidelines on what the component should be responsible for and what the context of the component should be responsible for. I think a good idea in this case would be to set the width of the component to 100% and then let the context you put it in to decide it width.

@mckn very good comment! Agree with this, that the size could be controlled by the container.

Ref you comment @torkelo I think having different sizes makes sense, but not sure what other cases we have to support that other than the PanelTItle inline edit? Maybe @jessover9000 has some input on this.

Currently the input should have 100% width by default which is set here: https://github.com/grafana/grafana/blob/630f75d3ef2b6b1275e75f77b94ee0c3325569cd/packages/grafana-ui/src/components/Forms/Input/Input.tsx#L58

**Comment by torkelo** [comment]
> Currently the input should have 100% width by default which is set here: 

@dprokop  that is on the wrapper not the input element, I could not get the input size to increase when setting it to size to auto

**Comment by torkelo** [comment]
Closing this as the new forms input do not have size now, so we can fix this when we new/add a size prop
