### ISSUE TITLE
Opentsdb : can't specify datasource access (server or browser) anymore

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#22169]
In grafana 6.6.1 you can't specify if you want to access an opentsdb datasource in browser or server mode anymore.
![image](https://user-images.githubusercontent.com/27487887/74437895-3ec74200-4e69-11ea-84aa-af9ef2183fa5.png)

But it's still in the doc :
![image](https://user-images.githubusercontent.com/27487887/74437939-556d9900-4e69-11ea-84dd-6e1fbfebb7fd.png)
https://grafana.com/docs/grafana/latest/features/datasources/opentsdb/#using-opentsdb-in-grafana

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: opentsdb

**Comment by dprokop** [comment]
@oddlittlebird would you mind takin a look at this? :)
