### ISSUE TITLE
how do you do regex with opentsdb queries?

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2217]
Hi Torkel,

Is it possible to query opentsdb with regex? I have bunch of metrics like this server1.cpu. Need to be able to put one query to create graphs. I know this is doable in graphite but opentsdb is a lot faster.

**Comment by torkelo** [comment]
I will have to redirect to you the OpenTSDB project on github, https://github.com/OpenTSDB/opentsdb  :)

**Comment by torkelo** [comment]
OpenTSDB is faster? find it A LOT slower (at querying at least)
