### ISSUE TITLE
Docs: Annotation Documentation needs use case and limits

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#22170]
**What would you like to be added**:
Intended use cases and load should be added to the [Native Annotations Documentation](https://grafana.com/docs/grafana/latest/reference/annotations/#native-annotations).

**Why is this needed**:
The Native annotation store (which goes into SQL) was designed for relatively sparse events (something on the order of a average of hundreds a day). Since the documentation doesn't indicate this, people can overload their Grafana instance with annotations (since they are stored in SQL, the SQL table grows to big).

The documentation should also link to alternative annotation stores (loki / elastic) that can better handle this case. If the total number of annotations is exported as a metric by grafana, we should link to that. The HTTP API endpoitnt should cross-reference this information. 

Related, creating a clean up job for older annotations https://github.com/grafana/grafana/issues/8224 .

**Comment by oddlittlebird** [comment]
Could someone just add this? Or perhaps send the content to me so I can add it? @jessabe?

**Comment by achatterjee-grafana** [comment]
Followed up with @kylebrandt. Closing the issue based on his recommendation.
