### ISSUE TITLE
app plugin and react pages

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [grafana/grafana#22178]
Grafana 6.6

React App Pages are failed to load from left side navigation. Without this feature, it is impossible to use Grafana to extend app plugins using React technologies. app-plugin works for AngularJS pages, considering retiring AngularJS, migration to React,   fix the issue in the Grafana framework. 

https://github.com/grafana/simple-app-plugin

Refer below issue.

https://github.com/grafana/simple-app-plugin/issues/2

**Comment by sakjur** [comment]
It's possible to add apps built in React to the navbar, here's an example of a plugin.json used by my team to do exactly that:

```json
{
  "type": "app",
  "name": "<AppName>",
  "id": "<AppID>",
  "routes": [],
  "info": {
    "description": "<AppDescription>",
    "author": {
      "name": "<AuthorName>",
      "url": "<AuthorURL>"
    },
    "logos": {
      "small": "<LogoURLS>",
      "large": "<LogoURLL>"
    },
    "links": [],
    "version": "%VERSION%",
    "updated": "%TODAY%"
  },
  "includes": [
    {
      "type": "dashboard",
      "name": "<dashboard>",
      "path": "<dashboard>",
      "addToNav": true,
      "defaultNav" : true
    },
    {
      "type": "datasource",
      "name": "<datasource>"
    }
  ],
  "dependencies": {
    "grafanaVersion": "6.6.x"
  }
}
```

If you follow the [bug reporting](https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md) or [feature request](https://github.com/grafana/grafana/issues/new?labels=type%3A+feature+request&template=2-feature_request.md) template it's easier for us to follow along with your request and it might be possible for you to get a better answer faster 🙂
