### ISSUE TITLE
Azure Monitor multiple subscription requests triggered per query / panel

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#22172]
**What happened**:

When editing panel with Azure monitor plugin, multiple **Azure Subscription** calls observed. Refer screenshot. This applicable to new panel and also happening while editing existing panel. This is causing too many calls to the server and unnecessary round trips.

**What you expected to happen**: 

There should be single subscription query possibly reused across the current dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a dashboard
* Add a new panel & Select azure monitor as data source
* Watch the network panel

**Anything else we need to know?**:

* Same behavior observed when duplicating the query in the query editor and adding new query to the same panel. 

**Environment**:
- Grafana version: 6.5.x
- User OS & Browser: Windows & Chrome 80

![image](https://user-images.githubusercontent.com/153843/74438840-ebea8c00-4e62-11ea-970a-646aef7e7795.png)

**Comment by sakjur** [comment]
This is something we want to improve long-term. Progress can be tracked in #7360.

**Comment by yesoreyeram** [comment]
@sakjur - I feel that #7360 and this are completely different issues. 

This is not about duplicate calls from two different sources. It is about duplicate calls for a single query. ( New panel, just one graph and just one query but three azure subscription calls )

Let me know if you need more details.

**Comment by sakjur** [comment]
Ah, I understand. I'll ask the people working with Azure to take a look at this then 🙂

**Comment by sunker** [comment]
The problem still exist after the QueryEditor has been migrated to react. I think we should cache not only this request, but all client side requests, on the frontend.

**Comment by sarahzinger** [comment]
Just triaging some older issues and found this one. I took a look to see what we're currently doing with this.

- I don't see us making multiple subscriptions request when editing an existing query anymore
- I do see us making multiple subscriptions requests when we add multiple queries per panel

So I believe this to be partially fixed. I think for the sake of cleaning up our old issues I'm going to close this for now but if it is actively causing anyone issues we can reopen!
