### ISSUE TITLE
Frontend: Admin UI accessible for regular users

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#22171]
**What happened**:
If role = admin, then the admin areas of the GUI are visible, such as exporting the dashboard json. 

**What you expected to happen**:
Changing the headers to be detected.
Not exposing the admin GUI elements to regular users.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login as a user with VIEWER role 
2. Use a http header modifying tool to change headers and submit request (Screenshot 2)
3. Browse dashboard settings

**Anything else we need to know?**:
This is really just a GUI problem. No new data is exposed. 

**Environment**:
- Grafana version: 6.6
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by sakjur** [comment]
1. Were the screenshots successfully attached?
2. Preventing this from happening would still rely on logic in the frontend, so the question is whether or not it's worthwhile, like you say all validation is done in the backend. What would be the reasons for making it harder for a user to access the "hidden" parts of the UI?
