### ISSUE TITLE
Add support for AWS/Route53Resolver to Cloudwatch datasource

### ISSUE THREAD

**Issue by stahs** [grafana/grafana#22184]
Hi,

It looks like some new metrics are now available via Cloudwatch for Route53Resolver, but the cloudwatch datasource doesn't support them yet. Can this be added please?

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/monitoring-resolver-with-cloudwatch.html

I can access these via AWS cli, but I can't see AWS/Route53Resolver namespace in my Grafana. 

```
> aws cloudwatch list-metrics --namespace AWS/Route53Resolver | grep MetricName
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "OutboundQueryVolume",
            "MetricName": "InboundQueryVolume",
            "MetricName": "OutboundQueryAggregateVolume",
```

Thanks

**Comment by sakjur** [comment]
Thank you for the update, this is something that should be added.

Until it's added, it is possible to work around the lack of this metric manually type the namespace, metric name and dimension and hit return.

In case someone in the community would want this to happen faster than we're able to add it, you're welcome to update the CloudWatch plugin with the new namespace and metrics 😄

**Comment by vikkyomkar** [comment]
@sakjur I will raise a PR for this issue
