### ISSUE TITLE
Add basic auth authentication support 

### ISSUE THREAD

**Issue by pabelanger** [grafana/grafana#2218]
Currently, grafana exposes the admin_user and admin_password in the .ini file; this is convenient. As such, I'm requesting we also expose and admin_api_key via the .ini file.

The purpose of this is to help with automated depolyments of grafana.  There is no method exposed currently that allows for an initial api_key to be provisioned.  Current steps require logging into GUI as admin user and manually adding it.

**Comment by torkelo** [comment]
yea, I have definitely seen this pain. One other solution that I would like to do is to allow api authentication with username/pass

**Comment by pabelanger** [comment]
Yup, I could see that working too

**Comment by pabelanger** [comment]
Another thought would be to expose the hash / salt function to an external CLI tool.  Then we can manually move the hash into the database

**Comment by torkelo** [comment]
@pabelanger was thinking along similar lines

**Comment by torkelo** [comment]
would be nice to not have a plain text password in the automation script

**Comment by 3fr61n** [comment]
It would be great to have the api authentication with username/pass, it would solve automation deployments

**Comment by torkelo** [comment]
You can now use the api with username password using a standard basic auth header (integrated into most http client libs) 

```shell
❯curl -u admin http://localhost:3000/api/org
Enter host password for user 'admin':
{"id":1,"name":"Main Org."}
```

**Comment by torkelo** [comment]
this also works, 
```
curl http://admin:admin@localhost:3000/api/org
```

**Comment by 3fr61n** [comment]
Thank!!!!

**Comment by mwdandr** [comment]
so can I add a dashboard like this 

POST /api/dashboards/db HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer admin:admin


?
