### ISSUE TITLE
Graph Points not connecting for a week day

### ISSUE THREAD

**Issue by RamanPndy** [grafana/grafana#22180]
**What happened**:
I'm using Prometheus as the data source and having data points for weekday i.e. for each day I'm having data points. data points are showing for each day but the graph is not connecting from the lines. it's showing scattered graph for one-week data.
**What you expected to happen**:
The graph should be connected through the lines for week data.
**How to reproduce it (as minimally and precisely as possible)**:
create weekly data metric in Prometheus and try to render it in Graph Panel by selecting time range as the last 7 days. The graph will show the scattered points for each day in a week.
**Anything else we need to know?**:
The graph is looking like as shown in the image for the weekly data.
![image](https://user-images.githubusercontent.com/10138989/74457089-cc2c8580-4ead-11ea-93de-f3338f009c9f.png)

**Environment**:
- Grafana version: latest grafana docker image
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: User OS is windows and Browser is Chrome
- Grafana plugins: Standard Graph Plugin
- Others:

**Comment by torkelo** [comment]
What is your scrape interval ? Looks like there is no data between the values (null) so you will need to set graph option to ignore null values (display option) then gaps in the data will be ignore and the line will connect

**Comment by RamanPndy** [comment]
@torkelo Thank you so much for the suggestion and it worked for the Graph panel.
But the same I'm trying for the Multibar Graph Panel for side by side bar graphs but all the values are aligned in one bar.
https://github.com/CorpGlory/grafana-multibar-graph-panel/issues/47

Can you please help me with this issue ??
I'm having trouble to understand what went wrong for the bar graph.

![image](https://user-images.githubusercontent.com/10138989/74501502-5f96a280-4f10-11ea-9e76-2f9639a9fcea.png)

**Comment by torkelo** [comment]
You will have to open an issue with that community panel plugin
