### ISSUE TITLE
"test datasource" uses settings of last save, not of current

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2219]
with a datasource that is only accessible directly, not via proxy.
i added it with direct mode and saved, test works. I get
```
Success
Data source is working
```

when i change to proxy and hit test again, it still works. but saving and retrying, test now fails.

same other way around. changing back to direct and testing again fails, but after save and retry test it works.

this is confusing, test should use the currently selected settings

**Comment by torkelo** [comment]
I noticed this once when implementing the feature but could not later replicate it. Some strange timing issue. Will investigate
