### ISSUE TITLE
Azure Log Analytics: TypeError: e is undefined

### ISSUE THREAD

**Issue by Oleexo** [grafana/grafana#22199]
**What happened**:
All queries with Azure Log Analytics returns the same error **TypeError: e is undefined**. This queries used to work before upgrade to 6.6.x version.

**What you expected to happen**:
Run the query normally and get results. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a query with Azure Log Analytics. Take a working query on log analytics and try to run it into Grafana.

**Anything else we need to know?**:
When I try to load the Query Inspector, the error message change to **TypeError: this.results[r].result is undefined**

When I try to **Save and test** my datasource Azure Monitor:

> 1. Successfully queried the Azure Monitor service. 2. Azure Log Analytics: Cannot connect to Azure Log Analytics REST API. 

**Environment**:
- Grafana version: Grafana v6.6.1 (21bf8b71bc)
- Data source type & version: Azure Monitor => Azure Log Analytics (built-in)
- OS Grafana is installed on: Docker grafana/grafana:latest
- User OS & Browser: Linux/Windows Chrome/Firefox
- Grafana plugins: yesoreyeram-boomtable-panel,zuburqan-parity-report-panel,grafana-piechart-panel

**Comment by shadow9911** [comment]
I'm having the same problem as well. Version 6.6.1 (21bf8b71bc)

**Comment by Oleexo** [comment]
I have updating to v6.6.2 (3fa63cfc34), still have the same issue.

**Comment by e-saiz** [comment]
me too same issue

**Comment by ultrafastneal** [comment]
Also having this problem w/version v6.6.2 (3fa63cf) Last version that worked was 6.5

**Comment by secustor** [comment]
Can confirm on v6.5.2 with provisioned datasources, but not on ones created using GUI

**Comment by kylebrandt** [comment]
The Azure Log Analytics datasource has been reworked in 7.1 and later. So I think this may be fixed in latest versions. If this is not the case please reopen the issue.
