### ISSUE TITLE
Control+V pastes text into previous cursor location instead of overwriting current selection

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#22207]
**What happened**:

1. I copy-pasted the text `lapd_transmitter_bytes_out_total`.
2. I did some further edits in a query textbox.
3. I doubleclicked to select some existing text.
4. I pressed Control+V.
5. I saw `lapd_transmitter_bytes_out_total` appear in the cursor location that was active **before** I selected the currently selected text

![image](https://user-images.githubusercontent.com/9914262/74527753-2b7eaa00-4f2f-11ea-9367-34e27a444c84.png)

Video evidence: https://imgur.com/vUBitUv

**What you expected to happen**:

I expected the selected text to be overwritten by the pasted text.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (container)
- User OS & Browser: Firefox 73 on Windows 10
- Grafana plugins: Zabbix
- Others:

**Comment by ivanahuckova** [comment]
Hello @sandersaares! I wasn't able to replicate the issue on Grafana 6.6.1 (and neither on Grafana 7.0-beta1) with Firefox 73 (and I tried Chrome as well). However, I have found [this resource](https://support.mozilla.org/en-US/questions/1280654) that mentions that Firefox73 + Windows 10 have buggy keyboard shortcuts. Could you please test, if upgrading to Firefox74 or 75 wouldn't solve the issue?

**Comment by ivanahuckova** [comment]
As this is probably a Firefox bug, I am going to close this issue for now. However, if it occurs after you update Firefox and verify that it is not a browser problem, we can definitely reopen it. I can really imagine how unpleasant and frustrating this could be! 🙁
