### ISSUE TITLE
Following up on issue #22200 Following up on #20729

### ISSUE THREAD

**Issue by craigedmunds** [grafana/grafana#22203]
Not sure why sakjur closed 22200 - the issue in 20729 is not resolved. It did appear to be fixed but on further examination the behaviour is still different to that expected (comparing the behaviour in 6.5.x to that on 6.4). This change in behaviour is preventing us from upgrading.

Suggest re-opening 20729 and dealing with the remaining issue there?

**Comment by sakjur** [comment]
Answered in #22200 + new bug #22204 created to resolve the bug :+1:
