### ISSUE TITLE
Following up on issue #20729

### ISSUE THREAD

**Issue by craigedmunds** [grafana/grafana#22200]
We've been feeding back on #20729, but haven't received a response - assume it's because the ticket is closed? Can it be re-opened?

**Comment by sakjur** [comment]
Hello Craig,

I took a look at the issue linked and it seems as if the person who opened that agreed that the original issue was solved, but with another bug appearing. If that's the case could you open a new issue for this new bug to avoid us ending up with a very wide and hard-to-follow issue? (and mention that this new bug has been discussed in #20729)

**Comment by craigedmunds** [comment]
That is not the case - it appeared to be fixed but on further examination the behaviour is still different to that expected (based on 6.4)

**Comment by sakjur** [comment]
Based on my understanding: The original issue was that expansion of variables stopped working altogether and the current problem is that it doesn't work when there is no matching data?

If that is correct it's two different behaviors, and trying to handle both of them in the same issue risks confusion.

**Comment by craigedmunds** [comment]
Ok, i've created https://github.com/grafana/grafana/issues/22204
