### ISSUE TITLE
some bugs about the tooltip

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2220]
To my understanding the value of the tooltip title is the mouse hover  timestamp. However, when some lines are broken, the timestamp and the tooltip-list-items are not correct.

there are 3 lines in the below graphs:
![1](https://cloud.githubusercontent.com/assets/8777671/8330356/696882a6-1ab3-11e5-9e64-66b717f98232.png)
the mouse is only hover on  line1 and line2 at '2015-06-24 03:26:00', so  the tooltip-list-items should not contain the hover info of line3.

![2](https://cloud.githubusercontent.com/assets/8777671/8330382/970bd398-1ab3-11e5-9009-e01342256058.png)
the timestamp of the tooltip is not correct here.

thank you~

**Comment by torkelo** [comment]
you will have to insert null or zero values missing points in your series as they are not connected, this is done by graphite automatically, and influxdb can do it by fill(null) or fill(0). 

OpenTSDB is returning non connected series in this case and the shared tooltip will show strange results if your series end abruptly or are non continous compared to other series on the same chart. You can disable shared tooltip and only the the tooltip over each point you hover over if you find the shared tooltip too misleading in your case.
