### ISSUE TITLE
Singlestat with a graph of a different metric?

### ISSUE THREAD

**Issue by k3lwin** [grafana/grafana#22208]
Hello everyone. I'm using Grafana in one-time projects to track progress of different processes like DRBD replication. I'd like to have a single Singlestat panel for each resource which display progress percentage with a big number and a copy speed graph underneath. For now, Stat and Singlestat only allow to plot a sparkline of the same metric as in text, and Graph panel lacks an option to display a big number over the graph. I couldn't find any plugins that would implement this.
**Why is this needed**:
Stat panel with graph of a different metric would improve at-a-glance readability for dashboards with a lot of typical trackers and allow packing more information into the same screen space.

**Comment by torkelo** [comment]
Dont think we will ever implement this, maybe a custom community plugin will

**Comment by torkelo** [comment]
Sorry for closing, just think this requirement is very unique
