### ISSUE TITLE
Deploy all images for grafana/grafana-dev

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#22217]
**What would you like to be added**:

Deploy arm, ubuntu and alpine images when pushing master tags to grafana/grafana-dev instead of just alpine images

**Why is this needed**:

**Comment by aknuds1** [comment]
Thanks!

**Comment by aknuds1** [comment]
Might this be solved by now?

**Comment by dsotirakis** [comment]
Closed as discussed with Leonard, images are now being deployed on `grafana/grafana-dev`
