### ISSUE TITLE
AWS CloudWatch: Custom Metrics namespaces cannot be used to add missing AWS Namespaces

### ISSUE THREAD

**Issue by passing** [grafana/grafana#22215]
AWS Namespaces & their dimensions for the Cloudwatch Datasource are hardcoded here:
https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L42
https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L125

There's a gap right now and some Namespaces are not defined, e.g..
- AWS/Athena
- AWS/Cassandra
- AWS/DataSync
- AWS/ElastiCache
- AWS/FSx
- AWS/QLDB
- AWS/Robomaker
- AWS/SDKMetrics
- AWS/ServiceCatalog
- AWS/SSM-RunCommand
- AWS/Transfer
- AWS/WorkMail

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html

When I tried to include some of these using the "Custom Metrics namespace" setting of the Datasource, it turned out that any AWS Namespace configured there is not usable due to this function:
```
func isCustomMetrics(namespace string) bool {
	return strings.Index(namespace, "AWS/") != 0
}
```
https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L838-L840
when it returns `true`, the Metrics & Dimensions won't be fetched from AWS, but will just be looked up in the `metricsMap` / `dimensionsMap`
I suggest the `isCustomMetrics` function should always return `true` when the namespace does not exist in the `metricsMap` / `dimensionsMap`

Right now in the end, you can select the custom AWS Namespace in Grafana, but the Metric dropdown will stay empty.

(This is related to https://github.com/grafana/grafana/pull/22179)

**Comment by davidnewhall** [comment]
Probably relates to or duplicates #22184

**Comment by daniellee** [comment]
I checked through all of these and most of these have been added

- [x] AWS/Athena
- [x]  AWS/Cassandra
- [x] AWS/DataSync
- [x] AWS/ElastiCache
- [x] AWS/FSx
- [] AWS/QLDB
- [] AWS/Robomaker
- [x] AWS/SDKMetrics
- [x] AWS/ServiceCatalog
- [] AWS/SSM-RunCommand
- [] AWS/Transfer
- [] AWS/WorkMail

Good point about the isCustom check and that is something we should change. If a new AWS service starts exposing metrics then there will also be a lag before it is supported in Grafana.

**Comment by waqark3389** [comment]
@daniellee Which version of Grafana release will these be in. I am looking at FSx and when I execute 
dimension_keys(AWS/FSx)

I cant see any values
