### ISSUE TITLE
Global Default Data Sources

### ISSUE THREAD

**Issue by jlopp** [grafana/grafana#2221]
It would be great if there was a way for Grafana admins to configure global default data sources so that when a user creates a new organization, it already has the data sources configured.

**Comment by toni-moreno** [comment]
+1

And also global default dashboards !!

**Comment by AlexAkulov** [comment]
+1

**Comment by danielladd** [comment]
+1

**Comment by sanjaynambiar** [comment]
:+1:

**Comment by jameseck** [comment]
+1

**Comment by jcmcken** [comment]
+1

**Comment by xyntrix** [comment]
I would love to not have to create the same data source across all orgs.  Looks like I may have to hack in something to says if datasource org id = -1, then make it globally accessible?

**Comment by torkelo** [comment]
We are adding user groups and permission ACLs on dashboards (and later data sources). 

So that should make this feature obsolete (as using orgs for grouping users will no longer be needed)

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1611#issuecomment-287742633
