### ISSUE TITLE
Explore with Loki datasource has empty dashboard

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#22214]
**What happened**: The graph under explore tab (with datasource Loki) is empty, even when you have logs

**What you expected to happen**: See a beautiful graph

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/5497623/74541111-52de7280-4f41-11ea-99e4-52b6800e2a2b.png)

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Loki 
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS - Chrome

**Comment by colin-lee** [comment]
i have the same problem

**Comment by squad1534** [comment]
me too

**Comment by Eraac** [comment]
From Grafana Slack, I don't tried the 6.6.2 yet, but i'm confidence that must be fix now
![image](https://user-images.githubusercontent.com/5497623/75021079-24f2b400-5494-11ea-8d08-70ea9be4e4c8.png)
