### ISSUE TITLE
Scale "log" loses negativ part

### ISSUE THREAD

**Issue by volschin** [grafana/grafana#22226]
**What happened**:
I have a graph with a linear scale for upload/download with a series overwrite for upload with 
`Transform: negative-Y` 
I tried to change the scale of Y-axis to log (base 10)
**What you expected to happen**:
The negative Part with the upload graph is not shown anymore
**How to reproduce it (as minimally and precisely as possible)**:
see above
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: InfluxDB 1.7
- OS Grafana is installed on: Docker ARM64 official Image
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by daenney** [comment]
It's probably that the transformation is applied before the scale, not after.

* log2 10: 3.3219
* log2 -10: 3.3219+4.532i

The imaginary part is discarded, so you end up with the same number.

If the Transform were to be applied after the scaling, then things ought to work.

**Comment by papagian** [comment]
@volschin 
Could you please share the results returned from the query?

**Comment by volschin** [comment]
![log_scale](https://user-images.githubusercontent.com/6284421/75289833-6f22bf00-581f-11ea-90d7-33626ab26e8a.jpg)
![linear scale](https://user-images.githubusercontent.com/6284421/75289837-7053ec00-581f-11ea-8169-f63c71f0fe60.jpg)

**Comment by papagian** [comment]
@volschin 
Sorry for not been clear, I meant to send the influxDB response for the specific query from the Network tab of your browser's developer tools.

**Comment by volschin** [comment]
@papagian Hope this is what you asked for.
[down_upsteam.txt](https://github.com/grafana/grafana/files/4254695/down_upsteam.txt)

**Comment by torkelo** [comment]
this is an old feature request (still open): https://github.com/grafana/grafana/issues/7627
