### ISSUE TITLE
Importing Graphite graphs with Thresholds doesn't work

### ISSUE THREAD

**Issue by rafalyesware** [grafana/grafana#2222]
It looks like Graphite (at least the version I'm using, which might be somewhat out of date), defines a 'Threshold' function to allow you to draw thresholds for various series, like so:

`threshold(1, "Goal 98th (1 minute)", "red")`

However, when I import a graph like that into Grafana, I get a broken graph (with an error that looks a lot like a series data retrieval error... but without anything useful in the error explorer).

Marking the threshold as disabled (by clicking the 'eye' icon), makes the graph correctly render again.

This is with Grafana 2.0.2

**Comment by torkelo** [comment]
The error is from graphite, what is the response from graphite for the request? You can open chrome dev tools network tab to inspect the response from graphite. (look for the POST /render request). 

threshold is a graphite function that does not work well with the json api, as the json api cannot return colors. Please use the Grafana threshold feature instead (found in axis and grid tab)

http://play.grafana.org/dashboard/db/temp-dashboard-graphite-threshold-func?panelId=1&fullscreen&edit

**Comment by rafalyesware** [comment]
Oh, you're right that this is a graphite rendering error.  I see a completely detail-free '500'  from the 'POST /render' request.

However, what I'm really complaining about is that Grafana imports an existing Graphite dashboard into a broken-out-of-the-box state; if there's a Grafana specific threshold feature, those `threshold` series should be turned into that on import, no?

**Comment by rafalyesware** [comment]
Also, how is it that it works in your play example and not for me? Different API? (it looks like your play example doesn't use the thresholds in Axis/Grid config).

**Comment by torkelo** [comment]
@rafalyesware there are some graphite  functions that do not work with the json api. These functions are not detected and removed and turned into grafana graph settings as that feature is rather complicated and no one has taken the time to implement it :(  

Not sure why the function is not working for you. I just created that dashboard to show that the error was probably something specific to your graphite install. I do not use that function when I want to set thresholds

**Comment by rafalyesware** [comment]
@torkelo Thanks for the added detail -- I was initially confused since you said "it doesn't work via the JSON API" but your example dashboard showed it working.  Confusion now cleared up, and I agree that it makes little sense to account for broken Graphite installs by converting functions to native Grafana interfaces.

**Comment by rafalyesware** [comment]
Just for the record, the Graphite server is running 0.9.10 and this commit in the Graphite repo fixes the issue: https://github.com/graphite-project/graphite-web/commit/60706b8a53092f08cd8b411aa04bf51004af307e (though that doesn't apply to 0.9.10, manually making the same change does fix the issue).

See also https://github.com/grafana/grafana/issues/1475; this is the same issue.
