### ISSUE TITLE
Values not loading when many panels and short refresh rate

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#22230]
**What happened**:
When there are many panels visible on the screen and refresh rate is short (10 seconds), some of the values are not loading.
After scrolling down to these panels some of the values are loaded immediately, some are loaded after a few seconds and some won't get loaded until I change refresh rate to higher value like 1 minute. These panels are set to display max/min value and time of it without any time range, so the database have to search through a few milions of records, but some of them are loaded immediately so I don't think it is problem with Influxdb.

One of possible solutions will be to add option to set refresh rate per panel.

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Influxdb 1.7.9
- OS Grafana is installed on: Debian 4.9.82
- User OS & Browser: Windows 10 Google Chrome
- Grafana plugins: -
- Others: -

**Comment by papagian** [comment]
Duplicate #12755
