### ISSUE TITLE
Removing rule in table plugin is not refreshing plugin 

### ISSUE THREAD

**Issue by Kranthi-grafana-user** [grafana/grafana#22247]
**What happened**: While removing the rules in table plugin from visualization, the table is not refreshed

**What you expected to happen**: When a user deletes rule/column style the data, table should get refreshed and should show the column styles related to removed rules

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a dashboard
2) Choose table plugin
3)Choose data source 
4) Add a column style
5) Add some style to the rule, May be add thresholds, change cell colors, add cell as link option, other styles which are possible
6) You can observe the styles added in rule are shown on table/ table data
6) Remove the rule
7) Observe that the styles are still shown on the table, even after removing the rule

**Anything else we need to know?**: NA

**Environment**: Windows
- Grafana version: v6.6.1
- Data source type & version: Elastic search
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins:  Table plugins
- Others: NA

**Comment by papagian** [comment]
This is reproducible also using the gdev-testdata datasource.

**Comment by Kranthi-grafana-user** [comment]
Yes, this is also reproducible using test data source

**Comment by dprokop** [comment]
@Kranthi-grafana-user thanks for reporting this issue! Temporary solution is to refresh the dashboard(not page refresh but built in Grafana refresh). In Grafana 7.0 (coming in May) we will introduce new Table panel with more advanced column styles and we will make sure this bug won't be there :)
