### ISSUE TITLE
Add "local instance" to datasource URL for accesss via browser

### ISSUE THREAD

**Issue by florianwgnr** [grafana/grafana#22249]
**What would you like to be added**:

A variable that replaces the current hostname/IP used to access the instance to simplify the provisioning process for datasource accesss via browser.

**Why is this needed**:

Assuming that in most (smaller) cases Grafana runs on the same server as the database.

When using "data source access via browser" instead of grafana's proxy (e.g. to reduce short-lived tcp connections), the database host must be entered manually (makes sense).
In order to simplify the provisioning process, it would be useful to set a variable/flag that replaces with the current hostname/IP the client is using to access Grafana.

**What should happen / example**

![grafik](https://user-images.githubusercontent.com/39341393/74655767-33d42080-518d-11ea-85a7-89aeff0cacde.png)

- when opening Grafana with "grafana.server.com", CURRENT_SERVER is replaced with "grafana.server.com" resulting in the data source url "http://grafana.server.com:8086" without the need to change it, if the hostname changes or a local domain/IP is used.

**Comment by dprokop** [comment]
Hi @florianwgnr and thank you for opening this issue! We do not plan to implement this feature in near future and we also do not see any evidence this is a popular future request.
