### ISSUE TITLE
Stat Panel: show thresholds

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#22240]
**What would you like to be added**:

I'd like a way to see the thresholds defined on a Stat panel.

**Why is this needed**:

Lets assume we have a temperature Stat with thresholds at -10: dark blue, 0: light blue, 5: light green, 15: dark green, 25: orange, 30: red. At any point in time looking at the Stat you will only see the current color, say dark green b/c it's currently 21 degrees. This is useful, but you can't put it into context. We can assume dark green is good, since green is generally the color for "everything's fine". 

What we don't know is what other options there may be and how our dark green relates to it. Being able to see that there is a orange, red, and two shades of blue, and that dark green is picked for values between 15-25 degrees, whereas red means stuff is getting seriously toasty, provides useful context.

This stands in contrast to a Gauge, where b/c you can see all the thresholds you get a better sense of how the current value relates to the whole.

I would propose something like a thin column on the right hand side of the Stat panel, like the stacked column you get when actually configuring thresholds on a Stat or Gauge, with a tool tip that shows up when you hover over one of them telling you the range of values. Essentially a legend of sorts for Stat. Probably nice if people can decide to turn it on/off.

**Comment by dprokop** [comment]
@daenney thanks for opening this. We don't see much interest in such a feature, and we do plan to introduce it anytime soon in the future, so I'm closing this one.

**Comment by daenney** [comment]
I don't quite get the sentence: We don't see interest, we do plan on introducing it, closing the issue?
