### ISSUE TITLE
Storybook: Forms.Select page is broken

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#22244]
**What happened**:
![Screenshot 2020-02-14 at 16 58 16](https://user-images.githubusercontent.com/8878045/74640458-3ed08600-5178-11ea-8e7b-a2a052f65126.png)

**How to reproduce it (as minimally and precisely as possible)**:
Go to Forms/Select page 
**Anything else we need to know?**:
When returning empty array from [generateOptions](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Forms/Select/Select.story.tsx#L19) the page is loaded normally. 

Might be related to the react-select bump #21638

**Comment by tskarhed** [comment]
This breaks when you navigate to docs, so it fails in the generate options story.

**Comment by Clarity-89** [comment]
@tskarhed seems like this has been fixed, so maybe the issue should be closed?
