### ISSUE TITLE
 how to monitor server side response time in grafana 2.X ?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2225]
Hi . 

I'm working on monitoring grafana status and performance for grafana 1.X  I used collectd with a self made plugin  (https://github.com/toni-moreno/collectd-apachelog-plugin) to parse apache access.log to get server response time ( with  LogFormat containing %D.)

But now with grafana 2.X I'm not able to get this information from grafana logs.

I have configured grafana log as follows

```
router_logging = true

[log]
mode = file
level = Info

[log.file]
log_rotate = true
max_lines = 1000000
daily_rotate = true
```

But nothing found on the generated log.

```
2015/06/25 14:38:24 [I] Starting Grafana
2015/06/25 14:38:24 [I] Version: 2.1.0-pre1, Commit: v2.0.2+359-gcfeba99, Build date: 2015-06-19 19:04:21 +0200 CEST
2015/06/25 14:38:24 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/tsdb/grafana
  [1]: default.paths.logs=/logs/apps/grafana
Paths:
  home: /usr/share/grafana
  data: /tsdb/grafana
  logs: /logs/apps/grafana

2015/06/25 14:38:24 [I] Database: sqlite3, ConnectionString: file:/tsdb/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/06/25 14:38:24 [I] Migrator: Starting DB migration
2015/06/25 14:38:24 [I] Listen: http://X.X.X.X:XX
2015/06/25 14:39:50 [I] Completed / 404 Not Found in 2.687ms
2015/06/25 14:40:09 [I] Completed / 404 Not Found in 2.524ms
2015/06/25 14:40:14 [I] Completed / 404 Not Found in 3.592ms
2015/06/25 14:41:59 [I] Completed / 404 Not Found in 2.453ms
2015/06/25 14:45:34 [I] Completed / 404 Not Found in 3.022ms
2015/06/25 15:01:38 [I] Starting Grafana
2015/06/25 15:01:38 [I] Version: 2.1.0-pre1, Commit: v2.0.2+359-gcfeba99, Build date: 2015-06-19 19:04:21 +0200 CEST
2015/06/25 15:01:38 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/tsdb/grafana
  [1]: default.paths.logs=/logs/apps/grafana
Paths:
  home: /usr/share/grafana
  data: /tsdb/grafana
  logs: /logs/apps/grafana

2015/06/25 15:01:38 [I] Database: sqlite3, ConnectionString: file:/tsdb/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/06/25 15:01:38 [I] Migrator: Starting DB migration
2015/06/25 15:01:38 [I] Listen: http://X.X.X.X:XX
```

__how can I configure grafana to get something similar to access.log with http response time?__

**Comment by torkelo** [comment]
Sorry, not implemented yet :( 

You will have to put an nginx proxy infront if you want a a stanard access.log

**Comment by toni-moreno** [comment]
Hi @torkelo there is documentation anywhere talking  on how to configure grafana with apache as proxy? 

Anyway I would like to create a new [Feature Request] if you agree.

As a performance engineer I don't like to add a proxy behind grafana adding  (at least) 30 ms on each request only to get response time.

When do you think could be this new feature added?

**Comment by torkelo** [comment]
@toni-moreno , 30ms for a nginx reverse proxy, that sounds a lot. 

But I agree, there should be a good web log option in grafana. This feature is not on any backlog right now. So it will probably have to wait until a PR comes a long. 

What is on the backlog is integrating more metrics and telemetry in grafana that can be (optionally turned on) and sent o statsd or graphite directly.
