### ISSUE TITLE
@grafana/ui – jquery.plot is not a function

### ISSUE THREAD

**Issue by dpetrov** [grafana/grafana#22257]
**What happened**:

I am not sure if that could be considered Grafana bug, but I am currently having a small internal React that, that pulls internal stats and I wanted to graph those using the @grafana/ui React components. Trying to use any of the react components, throws an exception:

```
Graph rendering error TypeError: jquery.plot is not a function
    at Graph.push.dL12.Graph.draw (Graph.js:259)
```

**What you expected to happen**:

To Draw a sample graph using the @grafana/ui React component. Expected to see a rendered graph with No data, as series is just an empty array.

**How to reproduce it (as minimally and precisely as possible)**:

Start a simple react app and configure webpack and ts-loader. Example App.tsx is provided below:

```
// App.tsx
import * as React from "react";

import { Graph } from "@grafana/ui";
import { dateTime } from "@grafana/data";

class App extends React.Component {
  render() {
    return (
      <div>
        <h1>Grafana Graph</h1>
        <Graph
          height={300}
          width={600}
          series={[]}
          timeRange={{
            from: dateTime(1546372800000),
            to: dateTime(1546380000000),
            raw: {
              from: dateTime(1546372800000),
              to: dateTime(1546380000000)
            }
          }}
          timeZone="browser"
        />
      </div>
    );
  }
}

export default App;
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: N/A
- OS Grafana is installed on: Mac OS
- User OS & Browser:  Mac OS & 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
- Grafana plugins: N/A
- Others:
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "expose-loader": "^0.7.5",
    "html-webpack-plugin": "^3.2.0",
    "source-map-loader": "^0.2.4",
    "ts-loader": "^6.2.1",
    "typescript": "^3.7.5",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3",

**Comment by torkelo** [comment]
In your app you need to vendor / bundle a few libd like jquery and flot.

Grafana/ui lib is not designed to be used for outside Grafana so we provide no support for his use case
