### ISSUE TITLE
Unnecessary call of updateLazyLoadedOptions in commitChanges?

### ISSUE THREAD

**Issue by PepperJo** [grafana/grafana#22254]
**What happened**:
When a query has a search filter its value is updated two times on selection. Which triggers every dependent variable to be updated two times. If that varibale has a search filter as well all dependent variables are updated 4 times and so on.

**What you expected to happen**:
Update only once.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query variable that has a search filter and another query variable that depends on it. Check how often the 2nd variable is executed e.g. via 'Network' in Chrome debugger.

**Anything else we need to know?**:
I tracked it down to this location in the code https://github.com/grafana/grafana/blob/21bf8b71bcbb8c4d097025a4ad90d281a9daab78/public/app/core/directives/value_select_dropdown.ts#L248
Why do the options have to be updated again? I see them being updated while typing, so no need to update them again. Or am I missing something?

**Environment**:
- Grafana version: v6.6.1.
- Data source type & version: Postgres
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome, Linux
- Grafana plugins: -
- Others:

**Comment by hugohaggmark** [comment]
Thank you @PepperJo for reporting this we're in the progress of moving query variables to React/Redux in this PR #21873 so hopefully this behaviour will go away. It's hard to say when this change will make it to `master` though.

**Comment by PepperJo** [comment]
Ok, thanks for the info I will be tracking this PR!

**Comment by dprokop** [comment]
Closed as this is now tracked in #22564
