### ISSUE TITLE
Datasource having issues when migrating from 2.6.0 to 6.6.1

### ISSUE THREAD

**Issue by satish-chef** [grafana/grafana#22261]
**What happened**: UI throws error when i try to add new data source or try to edit existing datasource.

**What you expected to happen**: UI should allow me to freely add new data source or edit an existing datasource.

**How to reproduce it (as minimally and precisely as possible)**:  I am migrating Grafana from version 2.6.0 to 6.6.1.  The backend is sqllite on the existing EC2 instance whereas the backed is MySQL on the new EC2 instance.  I converted the sqlite database to sql using the website https://www.rebasedata.com/convert-sqlite-to-mysql-online.  When i restored it and restarted grafana-server, i am able to browse dashboard just fine.  But when i try to create new data source or edit existing one, the UI throws error "Loader import method must be passed a module key string".  Its not giving error when i try to edit AWS cloudwatch datasource.
The MySQL installed on the new instance is the Percona Mysql.  The list of packages and its versions are below:
Percona-Server-shared-56-5.6.47-rel87.0.1.el7.x86_64
Percona-Server-client-56-5.6.47-rel87.0.1.el7.x86_64
Percona-Server-server-56-5.6.44-rel86.0.el7.x86_64

**Anything else we need to know?**:  I am facing error when i try to restore Mysql dump of Production Grafana on this EC2 instance as well.  I will create separate issue for it and reference this issue in the new one.

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Graphite(Whisper - 0.9.12)
- OS Grafana is installed on: CentOS Linux release 7.5.1804 (Core)
- User OS & Browser: Mac OS X EL Capitan 10.11.6, Chrome Version 79.0.3945.130
- Grafana plugins: NA
- Others: NA

![image](https://user-images.githubusercontent.com/9479581/74731849-eaf49880-526e-11ea-8e7a-1b4492502947.png)

**Comment by torkelo** [comment]
I would recommend migrating to version 4, then 5, then 6.  (ie install then start, db migrations run at startup). and then migrate to mysql  (or migrate to mysql first, then then do the upgrades in order.

**Comment by torkelo** [comment]
sorry for closing but you already had an issue open: https://github.com/grafana/grafana/issues/22262 , and helping you in that one already.
