### ISSUE TITLE
Error on monitoring  grafana HTTP status code  with curl  

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2226]
Hi . I'm working on monitoring grafana status and performance, for this reason I'm  working in a script to get OK if grafana is running and ok better than only checking the pid existence.

For this reason I would like to get the HTTP response code and the client side response time with curl

with the browser http://mygrafana.myorg.com is running ok, but getting from localhost the HTTP response code it got code 404.

```
root: > curl -s -I http://mygrafana.myorg.com
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Set-Cookie: grafana_sess=c939ab4970300112; Path=/; HttpOnly
Date: Thu, 25 Jun 2015 12:45:34 GMT
```

__What url could  I test with curl to get a valid  HTTP response code if grafana is up and running?.__

**Comment by torkelo** [comment]
that is because curl -I executes a HEAD http operation, which are not wired up (pretty unusual to do this for a web application)

Try this:
`curl -s -I -X GET http://mygrafana.myorg.com`
