### ISSUE TITLE
Default message & level ES fields are duplicated in log tables

### ISSUE THREAD

**Issue by dgonzalezruiz** [grafana/grafana#22264]
**What happened**: `message` and `level` fields are shown as duplicated when representing ES log data as a table; these are the fields configured as default in the related datasource. These default datasource field settings had to be removed in order to stop seeing these fields as duplicated.

**What you expected to happen**: These fields shouldn't have been duplicated on tables.

**How to reproduce it (as minimally and precisely as possible)**: Just configure an ES datasource with some default `message` & `level` fields, and represent logging data inside as a log panel, with `Table` as chosen visualisation. Fields chosen as logging defaults seem to be duplicated.

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Elasticsearch 7.6.0

**Comment by torkelo** [comment]
> and represent logging data inside as a log panel, with Table as chosen visualisation. Fields chosen as logging defaults seem to be duplicated.

log panel as table? not sure what your using? Are you in a dashboard, or explore? Can you show a screenshot?

**Comment by dgonzalezruiz** [comment]
Let me illustrate this:

<img width="1427" alt="Screenshot 2020-02-20 at 16 04 07" src="https://user-images.githubusercontent.com/20339155/74953048-70a84d80-5401-11ea-8229-b85fe9ac99db.png">

The above duplication is caused by `level` / `message` elasticsearch dastasource options. After stopping to specify these, duplication goes away:

<img width="1418" alt="Screenshot 2020-02-20 at 16 03 28" src="https://user-images.githubusercontent.com/20339155/74953093-7f8f0000-5401-11ea-8d99-0a8abab2bf9b.png">

**Comment by Elfo404** [comment]
I'm closing this issue as I wasn't able to reproduce locally on master, please feel free to comment again if this still happens for you.
