### ISSUE TITLE
Dashboard and datasource does not load after migrating from 2.6.0 to 6.6.1

### ISSUE THREAD

**Issue by satish-chef** [grafana/grafana#22262]
**What happened**:  This is in reference with the issue https://github.com/grafana/grafana/issues/22261.  On the same EC2 instance, i restored the MySQL dump of Production Grafana instance which has backend as MySQL since beginning.  After doing that, the dashboard does not load and give the error mentioned in Snapshot 1.  When I try to open the Graphite(Whisper) datasource, it gives error mentioned in Snapshot 2.
As mentioned in the issue 22261, i have used the same percona packages in this case:
Percona-Server-shared-56-5.6.47-rel87.0.1.el7.x86_64
Percona-Server-client-56-5.6.47-rel87.0.1.el7.x86_64
Percona-Server-server-56-5.6.44-rel86.0.el7.x86_64

The MySQL rpm's currently being used in Grafana production(which has Grafana version 2.6.0) are:
mysql-devel-5.5.40-1.el6.remi.x86_64
mysql-5.5.40-1.el6.remi.x86_64
mysql-server-5.5.40-1.el6.remi.x86_64
mysql-libs-5.5.40-1.el6.remi.x86_64
MySQL-shared-compat-5.6.13-1.el6.x86_64

**What you expected to happen**:  The dashboard should load properly, also i should be able to open/edit the existing datasources.

**How to reproduce it (as minimally and precisely as possible)**:  I restored production MySQL dump and I have mentioned above the issue that i am facing.

**Anything else we need to know?**:  Migrating from version 2.6.0 to 6.6.1.  EC2 instance hosting the Grafana version 2.6.0 has the OS version "CentOS release 6.6 (Final)".

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Graphite(Whisper - 0.9.12)
- OS Grafana is installed on: CentOS Linux release 7.5.1804 (Core)
- User OS & Browser: Mac OS X EL Capitan 10.11.6, Chrome Version 79.0.3945.130
- Grafana plugins: NA
- Others: NA

Snapshot 1:
![image](https://user-images.githubusercontent.com/9479581/74732682-cc8f9c80-5270-11ea-854e-d63c1c8fc4aa.png)

Snapshot 2:
![image](https://user-images.githubusercontent.com/9479581/74732696-d74a3180-5270-11ea-9d3a-9436fd8aea48.png)

**Comment by torkelo** [comment]
Can you go into your datasource settings and hit Save & test?

**Comment by satish-chef** [comment]
Hi @torkelo , thanks for your response.
I went to the production Grafana dashboard, hit save multiple times on all datasources, took its MySQL backup and restored it on the QA instance but still it is showing the same issue.
Also I would appreciate if you could help me with the issue https://github.com/grafana/grafana/issues/22261.

**Comment by torkelo** [comment]
Open the graphite one and change graphite version , the. Change it back , then save

**Comment by satish-chef** [comment]
Hi @torkelo , the snapshot that i pasted in my earlier comment was from the upgraded Grafana version 6.6.1
I do not see any option in the drop down the specify Graphite version in version 2.6.0.

![image](https://user-images.githubusercontent.com/9479581/74814563-8d6b5500-531d-11ea-8cbf-0fa01425d082.png)

**Comment by satish-chef** [comment]
Hi @torkelo , i was able to resolve this issue by deleting both graphite datasources from the "data_source" table and then recreating them from the UI.
It would be very much helpful if you could help me with the issue I am facing when i am trying to migrate my QA Grafana instance - https://github.com/grafana/grafana/issues/22261

**Comment by torkelo** [comment]
I was talking about instructions that related to version 6.6 , we do not support v2 still.
