### ISSUE TITLE
Table transforms: When merging multiple tables allow to exclude columns in merge logic 

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#22260]
After searching, trying and reading the docs, I still haven't found an explanation for this, but maybe is just an inattention in the docs.

**What happened**:
I've got an InfluxDB data source, with two queries that share the same tag names, but not necessarily the same time, the query computes something (mean, max, last) for the whole time selection, so there is no group by time.
If I hide the time column, I expect them to merge, because hidden "columns" should not be considered in the Join but no... that does not happen.
**What you expected to happen**:
I expect to be able to merge the queries results if the Time column is hidden since it should not be considered in the join
**How to reproduce it (as minimally and precisely as possible)**:
1. The issue can be replicated in the Grafana playground, here is the link to a Pastebin with the JSON of the dashboard: (the link will expire in 6 months)
[Pastebin](https://pastebin.com/CMB9yhab)

2. Another way is to edit an existing example in the Grafana playground, the [table merge one](https://play.grafana.org/d/Zzlfq17mk/influx-table-merge?orgId=1&from=now-15m&to=now&fullscreen&edit&panelId=2)
    - Remove the "GROUP BY time(1m)" in both queries
    - Add again (it will be removed by the previous step) the aggregation function "mean" (or whatever you wish) on both queries fields
    - check the table...

**Anything else we need to know?**:
The Table panel [docs](https://grafana.com/docs/grafana/latest/features/panels/table_panel/#merge-multiple-queries-per-table) states that:
> You can still merge both of the above cases by changing the conflicting column’s Type to hidden in the Column Styles.

Therefore I expect to be able to exclude the "Time" column from the join.

**Environment**:
(Note that this can be replicated also in the Grafana playground)
- Grafana version: 6.6.1
- Data source type & version: InfluxDB (v 1.7.1)
- OS Grafana is installed on: Windows Server 2016 Standard
- User OS & Browser: Windows 10 | Google Chrome
- Grafana plugins: Table Panel
- Others:

**Comment by torkelo** [comment]
You correct, think the docs is wrong here. Hidden columns is part of column styles and they are not considered when merging table results.

**Comment by mdvictor** [comment]
I think this can be closed. From my understanding, a fix for this, using the new Table panel, would be by using the `Filter by name` transform to hide the timestamp and then the `Merge` transform to unify the 2 queries. Please reopen if there if anything unclear.
