### ISSUE TITLE
Anonymous  users (role viewer)  can create organizations !

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2227]
I'm accessing as anonymous user 

```
[users]
allow_sign_up = false

[auth.anonymous]
enabled = true
org_name = myORG
org_role = Viewer
```

with this role I'm able to create new organizations as image shows.

![image](https://cloud.githubusercontent.com/assets/5883405/8355453/aea5f816-1b4f-11e5-8471-dcccd84dccd4.png)

I'm working with downloaded rpm from grafana site.

(Version: 2.1.0-pre1, Commit: v2.0.2+359-gcfeba99, Build date: 2015-06-19 19:04:21 +0200 CEST)

**Comment by toni-moreno** [comment]
I'm also trying to remove this created organization and I don't know how to do it?  is there any way to remove these 2 test organizations ?

**Comment by torkelo** [comment]
no, there is currently no way to completely remove organization. Will be added soon. 

You can remove yourself from organizations (if you are org admin)

**Comment by torkelo** [comment]
thanks for reporting this, fixed !
