### ISSUE TITLE
CloudWatch Datasource: floating bars in graph when stacking is enabled

### ISSUE THREAD

**Issue by passing** [grafana/grafana#22270]
We are using a CloudWatch datasource with a multi-value variable for one dimension:
The single query results in 3 series for that graph:
![image](https://user-images.githubusercontent.com/8142186/74746195-53d71300-5265-11ea-9c8b-f72c3a534e39.png)
As you see in the screenshot, the bar of the last series is floating.

Enabling Lines shows that the bar is actually placed/stacked on top of the line between the other bars:
![image](https://user-images.githubusercontent.com/8142186/74746239-66514c80-5265-11ea-91c8-01dcb5237391.png)

We have already set "Null value" = "null as zero" which should in general prevent this from happening. The problem seems to be that the CloudWatch datasource does not return a null for the intervals where no data is available. 

**Environment**:
- Grafana version: Grafana 6.6.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: CentOS / Docker
- User OS & Browser: Firefox

**Comment by torkelo** [comment]
@sunker Cloudwatch used to insert null values if there was no data between periods (I think), do you think this could have been lost in the rewrite last year?

**Comment by sunker** [comment]
Seems so. Might be possible to solve using expressions. I'll have to investigate this.

**Comment by sunker** [comment]
@mtanda could this be related to #22331?

**Comment by mtanda** [comment]
@sunker CloudWatch insert one null value datapoint per one gap, it seems to work after rewrite. (I tested it at Grafana v6.6.1)
It is expected result when I implemented it.

![image](https://user-images.githubusercontent.com/224552/77868784-53279880-7277-11ea-9fcb-dfd5fc5ce782.png)
![image](https://user-images.githubusercontent.com/224552/77868749-3be8ab00-7277-11ea-8942-e6bc1709b4d6.png)
![image](https://user-images.githubusercontent.com/224552/77868853-908c2600-7277-11ea-906f-832b45e16bf4.png)

**Comment by daniellee** [comment]
Closing as no response from @passing. Can reopen if this is still a problem.
