### ISSUE TITLE
Grafana Show Graphs Securely

### ISSUE THREAD

**Issue by RamanPndy** [grafana/grafana#22276]
**What happened**:
I need help to secure grafana access.
I’m running grafana behind an Nginx Reverse Proxy and Anonymous login has been enabled at Grafana side and all graphs can be accessible through path reverseproxy.example.com/grafana and showing graphs through iframes which is working fine.
But now my problem is how can I make grafana secure so that iframed graph URL can not be accessed outside the application??

like for example, this is one graph iframe URL: http://reverseproxy.example.com/grafana/d-solo/Amivlr8Wk/trends?orgId=1&from=1582044927347&to=1582045227347&panelId=2

which is working fine but I want that this URL can only be accessed through my other custom application not publicly.

can anyone please suggest a better approach to handle this ??

I can’t use Auth Proxy because I do not want to create a user in Grafana. for that, I’ve another mechanism to authenticate the users.
**What you expected to happen**:
I want to understand to secure grafana shareable links not to view publicly but only through the other custom application. Like this Url: http://reverseproxy.example.com/grafana/d-solo/Amivlr8Wk/trends?orgId=1&from=1582044927347&to=1582045227347&panelId=2 show the graph in an iframe in my application but if I try to open it directly to the browser it should redirect to the login page.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Docker Latest
- Data source type & version:
- OS Grafana is installed on: Ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
There is no way to do this currently (and no great ideas how to).

> I can’t use Auth Proxy because I do not want to create a user in Grafana. for that, I’ve another mechanism to authenticate the users.

Your only option is to use auth proxy, so if you want to embed Grafana in your custom application, you can allow users to login to your custom application, then have an auth proxy that validates they are logged into your application, and then sets proxy headers that authenticate the user to Grafana. You can set this to a static user so only a single user would be created on the grafana side. But important that your auth proxy first authenticates the user. 

 The other option is to use snapshots and only share static snapshots of dashboards / graphs. 

Another thing to keep in mind that Grafana dashboards execute queries in a very dynamic way, so if you give the anonymous user a viewer permissions to a single dashboard they can still issue any possible query. 

Related issue: https://github.com/grafana/grafana/issues/3752

**Comment by tmm1** [comment]
> Another thing to keep in mind that Grafana dashboards execute queries in a very dynamic way, so if you give the anonymous user a viewer permissions to a single dashboard they can still issue any possible query.

This makes it pretty hard to secure things. In the future it would be nice if dashboards didn't access the datasource api directly with queries, but rather went through a dashboard specific endpoint which could perform additional authorization.
