### ISSUE TITLE
Log panel: support details view

### ISSUE THREAD

**Issue by corford** [grafana/grafana#22271]
**What would you like to be added**:
It would be very useful if the Log panel had a details view toggle (as found in Explore). It would look and behave in exactly the same way (though I guess _without_ the +/- filter buttons)

**Why is this needed**:
We use Loki and our logs are in JSON. We find the explore details view very useful & intuitive for extra context. It would be great to have the same benefit directly accessible from the Log panel of a dashboard (this is quite common in other logging UIs e.g. when browsing AWS CloudWatch Events).

**Comment by torkelo** [comment]
@aocenas does not the log panel use the same component as explore, so the details view should also be available there?

**Comment by aocenas** [comment]
@torkelo Yes but there is a switch to enable/disable log details and it is disabled for dashboard panels. The reasoning is that the detail view is not very responsive friendly and so the UX is not great in a smaller panel and there was some discussion about using some other pattern like modal (with some dashboard provided API to allow showing modals) to display some detail info. There was not much time to push that further though so it was left as it is.

**Comment by torkelo** [comment]
Ah, ok, thanks for the explanation

**Comment by ThePants999** [comment]
We currently use Grafana for viewing metrics data and Kibana for viewing logs. We'd really like to start exclusively using Grafana for everything, but the main blocker is that in Grafana, only the Explore interface provides adequate usability for viewing logs. The critical issue in dashboards is that we have a choice between a Table panel, in which case we have a usable interface but only for a pre-defined subset of the data and no way to get to the raw log to see the rest of it, or the Logs panel, in which case we have all the data but in a nigh-on unusable format (which is why I'm commenting on this issue, as Details view in the log panel would go a long way towards fixing this).

The Kibana equivalent is a table view by default, but with a row expandable to show either the parsed contents or the raw log. (Where the raw log is JSON, as ours are, it's pretty-printed in the latter case.)
![image](https://user-images.githubusercontent.com/2923823/75256277-1fba9f80-57db-11ea-99ff-88d481eeaf38.png)

**Comment by aocenas** [comment]
cc @david @jessover9000 ^

**Comment by olivierboudet** [comment]
it would be also very useful to choose which columns (ie. which parsed fields) we want to have in the table (in log panel and in explore view).
Today, the explore and logs panel are displaying my logs directly in json, which is pretty unreadable.

**Comment by M0rdecay** [comment]
+1 here. We were very surprised when we saw that the log panel behaves differently in the query explorer and in the dashboard panel.

A custom key list would also be very helpful.

We using Elasticsearch 7.7.

**Comment by fiddeen** [comment]
+1 here

**Comment by PPACI** [comment]
+1
This would also enable people with only **reader** role to be able to view details, since they can't access explorer view.

**Comment by FrankAnk** [comment]
We also put our logs out in JSON format to avoid getting multiple log records when these contain line feeds. The applications are mostly Java Spring applications, sometimes errors produce stacktraces which we would like to view in the logs. Until now we have been using Elasticsearch and Kibana for this, which both work well but we would rather have just one Oberservabilty tool and want to view the logs in Grafana. Some users don´t have access to the "Explore" view in Grafana but need to be able to see these log details.

It would be absolutly great if we could open up the details in the log panel.

**Comment by genebean** [comment]
I'd love to see this in the details in the log panel too. I have had multiple instances of wanting this personally and have been asked about it by internal customers. I'd also settle for a way to drill down on a log that sent me over to explore.

**Comment by M0rdecay** [comment]
Still need this to make the final transition to Grafana
Any updates here?

**Comment by syh-rapha** [comment]
One workaround that improved our visualization was to use `line_format` to show only specific fields on the panel. Something like: `{app="foo", level="error"} | json | line_format "{{.Message}}"`

**Comment by seism0saurus** [comment]
@syh-rapha Could you explain your workaround a little bit more? Where do I have to enter the line_format?

**Comment by syh-rapha** [comment]
> @syh-rapha Could you explain your workaround a little bit more? Where do I have to enter the line_format?

@seism0saurus the idea is that if you are using the Logs Panel you can add the line_format on your query so it will show only the specified field, like `line_format "{{.RequestPath}} - {{.Message}}"`. You might wanna check the LogQL docs on this function and experiment a little on the Explore tab.

**Comment by gillg** [comment]
> @syh-rapha Could you explain your workaround a little bit more? Where do I have to enter the line_format?

I use it also, it's very helpful to have a clean a  readable log panel. You can do almost everything to parse your logs as json or other format.
**But** when you find an interesting line it's extremely frustrating to not be able to view details with all fields ! I thought to a datalink pointing to explorer, but it's not really possible :
* Explorer is not available for viewer users (for security reasons and avoid perf killing queries I think)
* I have no idea to pre-fill a new query to find exactly the log line where I clicked.

So yes it seems very useful to have an expendable or poppin view for a log line (maybe related to a kind of "data query" with ability to create a custom query for a result ?)

**Comment by souravsharma6633** [comment]
The show context button is also not available in logs panel but is there in explore. That button is of great utility.
