### ISSUE TITLE
Add series override for the new Stat panel 

### ISSUE THREAD

**Issue by nunks** [grafana/grafana#22272]
**What would you like to be added**: A *series override* option for the new stat panel.

**Why is this needed**: I'd like to be able to **hide** some series from showing in the stat panel while still being able to use them with other panels without needing to copy my query around (I try to use the dashboard "pseudo-datasource" as much as I can to take it easy on the database).

***

Thanks for all the work done on Grafana! Every new release is always a treasure trove of cool features =D

**Comment by torkelo** [comment]
We are working on this as part of the new panel edit mode coming in v7, all new panels (stat, guage, bar gauge, new table panel) will share the same field override option UI
