### ISSUE TITLE
Feature Request: Separate color selection for Background and Value in Singlestat 

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#2228]
When working on Singlestat it is impossible to use both background and value coloring together since they use the same color scheme. It would be very helpful if we could select different colors for the background and the value.

**Comment by torkelo** [comment]
color is bound to the thresholds, so the idea is an either or (value or background)

**Comment by torkelo** [comment]
Sorry

**Comment by agaon** [comment]
I understand that the color is bound to threshold, but having two colors per threshold (one for value and one for background) will allow to create more visually appealing dashboards - quick example: when the threshold is "green" the only the text is green, but when the threshold changes to "yellow" the background becomes yellow hence amplifying the visual alert.

**Comment by qindj** [comment]
+1

**Comment by torkelo** [comment]
closing this for lack of interest
