### ISSUE TITLE
Data Links: Repeat Panel Variables are not being correctly replaced

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#22286]
**How to reproduce it (as minimally and precisely as possible)**: Create a data Link in "Repeated Panel" and reference the repeated template in the link.

**What you expected to happen**: I expected the Data Link URL to be created with the Tamplate options used to render that panel.

**What happened**: Instead, a list of all selected options for the template was inserted, which breaks the link.

I know that information lives in the "options.scopedVars" object that is passed to the datasource's "query" function. But it is not being passed to the "Data Link" object. Which also means the time interval is currently unavailable, as well as a time range that reflects the current panel's time overrides.

**Environment**:
- Grafana version: 6.6
- Data source type & version: ES

**Comment by torkelo** [comment]
Could replicate.  here is the dashboard: https://gist.github.com/torkelo/a16611210f9e07e421b1cc9fda7f8b06 

It looks a bit tricky to solve this as scopedVars is not directly passed to react panels, and the data links are using templateSrv.replace

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/26147
