### ISSUE TITLE
Opening up folder content from frontpage is unclear

### ISSUE THREAD

**Issue by JensRantil** [grafana/grafana#22299]
Folders are nice to organise things in Grafana. However, accessing a full folder content from the frontpage is really unclear. I just today learnt that I need to click the cogwheel symbol for that. Cogwheel is generally for settings, not listing a directory. I propose changing the symbol to something more clear, but there might be other approaches to quickly access full folder content listing.

This is a discussion at my work's Slack about this:

![image](https://user-images.githubusercontent.com/730342/74823659-5ab66200-5307-11ea-903c-5d4c5a1a0a50.png)

**Comment by torkelo** [comment]
I know, we struggled a lot with figuring out a UX fo that and where not happy with what we ended up with.

**Comment by JensRantil** [comment]
Switching from a cog wheel to a folder (📂) icon might be a small change that would improve the UX a lot. I understand it's probably not optimal, but I would never click on a cog wheel and expect listing the dashboard.
