### ISSUE TITLE
alias patterns with grafana (2.1.0 pre) 

### ISSUE THREAD

**Issue by tecbea** [grafana/grafana#2230]
Hi
is alias patterns working with influxdb (0.9) ?

i put on alias pattern $1 or $2 , and does not work;
on legend it appeats $1

**Comment by torkelo** [comment]
influxdb 0.9 only supports $measurement  and $tag_<tagname>    as infuxdb 0.9 is tag based

**Comment by tecbea** [comment]
hi,
thanks for reply, 

but how can we do a series alias ? 
is in roadmap to have a fixed alias array ? 

for instance as you have templates, you can have global alias ; 
than you can change a a series name for a more readable string.

**Comment by torkelo** [comment]
@tecbea no there is nothing on the roadmap. I do not understand you can put in anything in the alias field and that will be used as the series name. the "$1", or "$2"  was for influxdb 0.8 as everything is in the series name. But that stuff should be in tags for influxdb 0.9. 

Can you show me how your measurements and tag layout looks and what series names you want to generate?

**Comment by tecbea** [comment]
hi,
well i still use names series names even on 0.9, not for hosts or regions;

imagine a series like number of sensors on time;
sensors.counter.typ.0
sensors.counter.typ.1

i've a chart for /sensors.counter.typ.*/

the thing is how i get alias for this kind of series

**Comment by torkelo** [comment]
might have to have segment alias as well, will try to add in sometime in the coming weeks

**Comment by jlyheden** [comment]
I'm also interested in this, we use collectd to push metrics to influxdb and afaik collectd does not support the concept of tags. Thus we still need the old positional series name style aliasing as used in influx 0.8

**Comment by torkelo** [comment]
Can you not use Graphite instead if you want segment based metrics aliasing? Then you will get all the aliasing you want plus an amazing set of transformation functions :)  InfluxDB 0.9 is tag based, which comes with its own set of pros and cons. 

But I will try to add back segmented aliasing, sooner if more request it :)

**Comment by jlyheden** [comment]
Apparently using templates in the Influx graphite listener to extract tags based on patterns in the serie name passed from Collectd seem to be the way to go in 0.9 as documented here https://github.com/influxdb/influxdb/blob/master/services/graphite/README.md so will try that route for now. Thanks
