### ISSUE TITLE
Grafana sending alerts that do not show up in /var/log/grafana.log*

### ISSUE THREAD

**Issue by krkahn** [grafana/grafana#22307]
**What happened**:
We are getting alerts via Grafana that should not be thrown. The alerts are 'no data' but we've changed `Set State To: Keep Last State`. As such, we are still getting alerts. The logs however do not reflect any of these alerts after the Set State change was made. 

TLDR: We're getting new alerts (pages) from Grafana that are not reflected in the server's grafana logs.

**What you expected to happen**:
When there is no data present we don't expect to be alerted. 

**How to reproduce it (as minimally and precisely as possible)**:
This has been getting thrown at 0030 every day (possibly more of an endpoint issue) but it's helped us pin down that the alert is still being thrown.  

**Anything else we need to know?**:

**Environment**:
- Grafana version:
Grafana v6.5.2
- Data source type & version:
Mixed Prometheus Query - Prom 2.9.2
- OS Grafana is installed on:
Ubuntu 16.04.5 LTS (Xenial Xerus) 
- User OS & Browser:
Fedora 30 & Firefox
- Grafana plugins:
- Others:

`grafana.log.2020-02-13.001:t=2020-02-12T00:31:18-0500 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=482 name="redacted alert name" changing state to=no_data
grafana.log.2020-02-14.001:t=2020-02-13T00:31:09-0500 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=482 name="redacted alert name" changing state to=no_data
grafana.log.2020-02-15.001:t=2020-02-14T00:31:29-0500 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=482 name="redacted alert name" changing state to=no_data
grafana.log.2020-02-15.001:t=2020-02-14T12:52:32-0500 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=0 name="redacted alert name" error="tsdb.HandleRequest() error bad_data: parse error at char 1: no expression found in input" changing state to=alerting`

Last shown alert was the 14th, but we've been still getting them every day since then, including today.

**Comment by papagian** [comment]
Can you share the query? It seems that you get the error because the query fails with:
` error bad_data: parse error at char 1: no expression found in input`.
Have you set ` If no data or all values are null ` or ` If execution error or timeout `  to `Set State To: Keep Last State`?

**Comment by krkahn** [comment]
Hi @papagian: 
`label_replace({__name__=~"node_(.*)_redacteddomain_local(.*)"}, "__name__", "$1-$2", "__name__", "(node)_(.*)_(redacteddomain)_(local)(.*)")`

It is a label replaced query on Prometheus. If there's any other details I can provide just let me know.

**Comment by papagian** [comment]
The reason you are getting the alert is that you have configured:
`If execution error or timeout` to `Set State To: Alerting`. You need to change it to `State To: Keep Last State` if you don't want to get notified every time that the rule is evaluated and the query fails.
It remains to find out what's wrong with the specific query.

**Comment by papagian** [comment]
@krkahn 
Can you try the query directly in Prometheus?
Also there can be an invisible character in the beginning. Can you try deleting completely the input and entering it again?

**Comment by torkelo** [comment]
Looks like a query error returned by prometheus? `tsdb.HandleRequest() error bad_data: parse error at char 1: no expression found in input`
