### ISSUE TITLE
Loki: Data source setting to specify a Loki label containing the error severity level

### ISSUE THREAD

**Issue by corford** [grafana/grafana#22308]
**What would you like to be added**:
Would love a setting for ~~Log panels that use Loki~~ Loki datasources to specify the label that contains the error level (ERROR, WARNING, INFO etc.)

**Why is this needed**:
At the moment we have no reliable visual clue as to the severity of the error because Grafana seems to just randomly guess the log level indicator for each line in our Log panel (our log lines are JSON).

For more context see: https://github.com/grafana/grafana/issues/22075#issuecomment-586166497

**Comment by torkelo** [comment]
should this not be a loki data source setting?

**Comment by cyriltovena** [comment]
> should this not be a loki data source setting?

Definitively. I think we should be able provide a regex to extract the value for each log, and some values mapping, error/err/fatal => red, etc.....

This would be great to work in log panel too.

It would be great in the meantime to document how it currently pick up the log level.

**Comment by davkal** [comment]
This can be done with [pipelines](https://github.com/grafana/loki/blob/master/docs/clients/promtail/pipelines.md) in when configuring promtail

**Comment by cyriltovena** [comment]
You don’t necessarily want to add a label and even though the coloring might not work.

**Comment by corford** [comment]
@davkal We don't use promtail....

**Comment by aocenas** [comment]
@corford To understand this, do you already have a label in your logs that specify the severity? Right now we use label named `level` for this which is hardcoded, otherwise we use some regex parsing logic on the log message itself.

So if you can change you log processing so that log level label is called `level` this should work for you. If you specifically want to use different label name for this and setup it in grafana let me know and we can reopen this.

**Comment by corford** [comment]
@aocenas We have a label called "levelname" (following the standard Python way of doing things). Our logs go out of a python codebase into fluent-bit, which in turns sends them to Loki.

What we would like is way in Grafana to explicitly set "levelname" as the field on the Loki datasource it should use for determining severity (and thus how it colours loglines in the explorer etc.)

**Comment by aocenas** [comment]
@corford so grafana uses either a `level` label or some regex heuristic. So if you could rename `levelname` => `level` then it should work fine. If you cannot change it than yeah we would need to add some config for the label name where to get this info from so you could configure it to `levelname`.

**Comment by corford** [comment]
I think the option to tell grafana where to look is important (rather than having to alter logging code - which is fed to other systems in addition to just loki - to match what grafana wants).

But yes, as a workaround we can change it on our end.

**Comment by cyriltovena** [comment]
Datasource setting ?

**Comment by corford** [comment]
Would work for us.

**Comment by ivanahuckova** [comment]
@ventris I have added documentation #28975 to make it more clear how do we extract and determine log level. I hope it helps - so you can adjust logs in a way that Grafana will be able to determine its log level/adjust level. There is already also an issue regarding supporting custom log levels #25585 - so if you think something like this would be helpful, please feel free to upvote it and share your usecase.

**Comment by corford** [comment]
Nice that there's now documentation to work around the limitation but would have been cool if the limitation itself was removed.
