### ISSUE TITLE
Azure Monitor - Application Insight query not returning values

### ISSUE THREAD

**Issue by kjeldlau-3shape** [grafana/grafana#22319]
[query.txt](https://github.com/grafana/grafana/files/4226589/query.txt)

[6.4.4 - query inspector.txt](https://github.com/grafana/grafana/files/4226590/6.4.4.-.query.inspector.txt)
[6.6.1 - query inspector.txt](https://github.com/grafana/grafana/files/4226591/6.6.1.-.query.inspector.txt)

**What happened**:
A query is not returning values. I have the same query running in Grafana v 6.4.4

**What you expected to happen**:
Values returned

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Azure Monitor data source - including the Application Insights
2. enter the query (see attachment)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Azure Monitor - Application Insights
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, Google Chrome
- Grafana plugins: Graph
- Others:

**Comment by kjeldlau-3shape** [comment]
Hi - do you need more information?
I upgraded to 6.6.2 just now, and it seems to have the same problem - though I have not investigated it much.

**Comment by kylebrandt** [comment]
The azure services code has been reworked for the upcoming 7.1 release. The editor is slightly different in that  it is like Log Analytics now. There query seems to work in this upcoming release - so assuming this is fixed.

Please reopen if you find there is still a problem in version 7.1 or later.

![image](https://user-images.githubusercontent.com/1692624/87176130-a7470d80-c2a7-11ea-9c4d-be4ca3956a85.png)
