### ISSUE TITLE
Requests performed several times when changing variable value

### ISSUE THREAD

**Issue by bgranvea** [grafana/grafana#22310]
**What happened**:
With attached dashboard, when one of the variable value is changed from 'all' to any other value, I can see with Fiddler or browser developer tools that panel query is executed twice.

[New dashboard Copy-1582119183465.txt](https://github.com/grafana/grafana/files/4225309/New.dashboard.Copy-1582119183465.txt)

**What you expected to happen**:
Panel query should be executed only once as it can be be very costly.

**How to reproduce it (as minimally and precisely as possible)**:
- create a Clickhouse datasource
- import provided dashboard
- open chrome developer tools and monitor network
- change variable value

**Anything else we need to know?**:
This works ok in 6.5.3

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Clickhouse 1.9.3
- OS Grafana is installed on: official Docker image
- User OS & Browser: Windows 10, Chrome 79
- Grafana plugins: Clickhouse
- Others:

**Comment by papagian** [comment]
Thank you for reporting this.

I have noticed that you have selected to refresh the template variables `on Time Range Change`?
Is that necessary? These values are always change?

Also according to this [comment](https://github.com/grafana/grafana/issues/22254#issuecomment-587322602) query variables are under major refactoring so hopefully this behaviour will go away.

**Comment by bgranvea** [comment]
Thank you for your help. 'on time range change' is not needed here but it is in my real dashboard.
