### ISSUE TITLE
Repeatable Variable is not used in Data Link

### ISSUE THREAD

**Issue by arikfre** [grafana/grafana#22326]
**What happened**:
I added a Data Link to a panel and attempted to send the Repeatable Variable, the same way
I send other template variables in the link.
The whole array of the repeatable variable is sent

**What you expected to happen**:
the variable in the link should be replaced with the relevant value (the one in the that panel).

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with a repeatable variable
in one of the panels create a data link and send the repeatable variable as part of the link

**Anything else we need to know?**:
This is how the link looks like: https://grafana.xx.com/my_dashboard?orgId=1$var-cluster=${cluster}
cluster is a template variable on both source and destination dashboard.
It is repeated in the source variable

**Environment**:
- Grafana version: v6.5
- Data source type & version: Elasticsearch 7
- OS Grafana is installed on: Centos
- User OS & Browser: Mac & Chrome

**Comment by torkelo** [comment]
diuplicate of https://github.com/grafana/grafana/issues/22286
