### ISSUE TITLE
More table color thresholds

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#22320]
**What would you like to be added**:
It would be nice to add more coloring options to thresholds in the table. 
**Why is this needed**:
Now there are 3 of them, but I need more for creating color toned values.

**Comment by torkelo** [comment]
This is coming in the new table panel :)

**Comment by torkelo** [comment]
in v7.0

**Comment by radimkohout** [comment]
I cannot find it, but OK. 👍

**Comment by torkelo** [comment]
Wait for beta release in April

**Comment by radimkohout** [comment]
Ok, thanks.
