### ISSUE TITLE
Custom Datasource not able to be Selected in Dashboard Panel

### ISSUE THREAD

**Issue by Scott8440** [grafana/grafana#22322]
**What happened**:
Custom datasource, once created, does not appear as an option in drop-down datasource selector in dashboard panel editor.

**What you expected to happen**:
Once a custom datasource has been created, it should be available for dashboards to use.

**How to reproduce it (as minimally and precisely as possible)**:
* Use Dockerfile found here: https://github.com/facebookincubator/magma/tree/master/orc8r/cloud/docker/user-grafana
* Build container and run with a port open to 3000.
* Create a datasource using the "Orchestrator Datasource" type
* Go to "Create Dashboard"
* See that the custom datasource is not available to be selected
**Anything else we need to know?**:
* The datasource is created and saved successfully. It appears when you return to the datasources page.
* The "Add datasource" icon on the homepage is still highlighted after this datasource has been created
* The datasource is actually usable in a dashboard if no other datasources have been defined.
  * It is named "-- Grafana --" and queries the datasource correctly as expected
  * If you change the datasource and then return to "-- Grafana --" it becomes the sample ds with random walk data

**Environment**:
- Grafana version: master, but this occurs on 6.x.x
- Data source type & version: Custom
- OS Grafana is installed on: alpine:3.11
- User OS & Browser: macOS Mojave 10.14.6, Chrome
- Grafana plugins: Custom datasource
- Others:

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/74906689-087e4b00-53b2-11ea-9672-27cf194b3b74.png)

Unable to replicate, the data source is there and can be selected, is also marked as default as it's the first data source. And it's different from the built in Grafana test datasource. 

After creating the data source be sure to update the http settings and hit save and test
