### ISSUE TITLE
Importing dashboards by API with "\n" inside body fails

### ISSUE THREAD

**Issue by Shini31** [grafana/grafana#22334]
**What happened**:
When I want to import a dashboard with `\n` character inside a query ou a description, there is a failed message (Ansible output):
```
failed: [grafana-k8s -> 127.0.0.1] (item={'src': u'/tmp/grafana_dashboard/manifests/grafana/dashboards/Istio/Jaeger - Overview-1581002102899.json', 'group': u'mcinquin', 'uid': 1000, 'state': 'file', 'gid': 1000, 'mode': '0644', 'mtime': 1582124826.0, 'owner': 'mcinquin', 'path': u'Istio/Jaeger - Overview-1581002102899.json', 'size': 41490, 'root': u'/tmp/grafana_dashboard/manifests/grafana/dashboards', 'ctime': 1582191860.9817057}) => {"alt_svc": "clear", "ansible_loop_var": "item", "cache_control": "no-cache", "changed": false, "connection": "close", "content": "[{\"classification\":\"DeserializationError\",\"message\":\"invalid character '\\\\n' in string literal\"}]", "content_length": "97", "content_type": "application/json; charset=utf-8", "date": "Thu, 20 Feb 2020 09:44:24 GMT", "elapsed": 0, "expires": "-1", "item": {"ctime": 1582191860.9817057, "gid": 1000, "group": "mcinquin", "mode": "0644", "mtime": 1582124826.0, "owner": "mcinquin", "path": "Istio/Jaeger - Overview-1581002102899.json", "root": "/tmp/grafana_dashboard/manifests/grafana/dashboards", "size": 41490, "src": "/tmp/grafana_dashboard/manifests/grafana/dashboards/Istio/Jaeger - Overview-1581002102899.json", "state": "file", "uid": 1000}, "json": [{"classification": "DeserializationError", "message": "invalid character '\\n' in string literal"}], "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "pragma": "no-cache", "redirected": false, "status": 400, "url": "https://sdp-dashboard-sandbox.sigfox.com/api/folders", "via": "1.1 google", "x_frame_options": "deny"}

```
The dashboard has been initially imported by WebUI and Grafana.com Dashboard ID, then exported as JSON file.

If I import manually the dashboard with the WebUI, there is no issue.

**What you expected to happen**:
The dashboard could be imported without error

**How to reproduce it (as minimally and precisely as possible)**:
I use an ansible task to import the dashboard
```
- name: Import Grafana dashboard
  vars:
    k8s_manifests_temp_dir: /tmp/grafana_dashboard
  uri:
    url: "{{ grafana_dashboard_url }}/api/dashboard/db"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ grafana_dashboard_apikey }}"
    body: >
      {
        "dashboard": "{{ lookup('file', item.src) }}",
        "folderId": "{{ item.src | dirname | basename }}",
        "overwrite": "true",
        "message": "Updated by Ansible - {{ lookup('pipe','date +%d-%m-%Y-%H-%M-%S') }}"
      }
  with_filetree: "{{ k8s_manifests_temp_dir }}/manifests/grafana/dashboards"
  when: item.state == 'file' and item.src is regex('^.*.json$')
```

The dashboard used is the 1001 (https://grafana.com/grafana/dashboards/10001)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Prometheus
- OS Grafana is installed on: K8S Deployment
- User OS & Browser: Ubuntu/Brave

**Comment by aknuds1** [comment]
I don't know Ansible, but it looks as if you're trying to post the dashboard to the API endpoint /api/folders. This endpoint is for [creating a folder](https://grafana.com/docs/grafana/latest/http_api/folder/#create-folder), why are you trying to use it to import a dashboard?

**Comment by aknuds1** [comment]
Closing this for the time being, since I don't think it's a bug in Grafana.

**Comment by Shini31** [comment]
With the right api endpoint, the issue is still present

**Comment by aknuds1** [comment]
@Shini31 Please update the issue with how to reproduce with an HTTP POST request, i.e. not requiring Ansible.

**Comment by Shini31** [comment]
Hi,

I solved my issue. The behavior of importing a dashboard is completely different between the API and the UI. The required fields are not the same and not in the same place.

It's more than confusing and not very logical...
