### ISSUE TITLE
feature request: timepicker - today, month-to-date, year-to-date options

### ISSUE THREAD

**Issue by ccutrer** [grafana/grafana#2233]
it would be nice to have today (is that even what it would be called?), month-to-date, and year-to-date options. In my use case of solar energy production, the graph is typically a nice parabola - as long as you're aligned on day boundaries. a relative value of 24 hours will catch the tail of yesterday, and make it difficult to see how well I'm doing _just_ today. 12 hours is too short - at the beginning of the day is still catches yesterdays tail, and at the end of the day it misses today's beginning.

if x-to-date is too difficult due to the changing size of the window, just "today", "this month", and "this year" would be acceptable - there will be lots of empty space in the graphs to the right, but it will still get me the information I want.

**Comment by ccutrer** [comment]
This somewhat duplicates #1186 which is done.

**Comment by sdoering** [comment]
I am totally into this feature. It would really benefit the ability to have a fast overview of sales performance for the current timeframe (day, week, month, quarter, year). 

Thanks a lot in advance.

**Comment by daniellee** [comment]
In 4.2.3, (see 540ee3539397f58d4cbc0b93190b9e412ecc55fa) two new ranges were added "This month so far" and "This year so far". And "Today so far" has already been added so I think this feature request is completed.
