### ISSUE TITLE
Match HELP and TYPE for complex metrics

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#22337]
**What happened**:

No HELP and TYPE displayed for a sub metric of a complex metric. 

**What you expected to happen**:

HElP and TYPE are displayed for the given metric.

**How to reproduce it (as minimally and precisely as possible)**:

Create a summary, define a HELP. Only the base metric will have the information but the `sum` and `count` won't.

Base metric

![Screenshot 2020-02-20 at 12 40 16](https://user-images.githubusercontent.com/231583/74934516-4ee99f00-53de-11ea-8498-18989ddd8a33.png)

Sub metric

![Screenshot 2020-02-20 at 12 40 20](https://user-images.githubusercontent.com/231583/74934544-5dd05180-53de-11ea-9fa2-44534595d9b0.png)

**Anything else we need to know?**:
I believe this happens because we only match on the exact metric name:

https://github.com/grafana/grafana/blob/4f9b6c55c03462277a62be5084865723ba2e743c/public/app/plugins/datasource/prometheus/language_provider.ts#L45-L52

We would also need to match even if it includes the following suffices: 
- `_bucket`
- `_sum`
- `_count`
- `_total`

**Environment**:
- Grafana version: Lastest
- Data source type & version: Prometheus / Latest

**Comment by davkal** [comment]
I would argue that's an API issue. If Prom offers metrics and has a metadata API for metrics types, as an API consumer I expect the metadata to be complete, i.e., it should return metadata on all metrics that it has. "Submetric" seems to be a prometheus implementation detail.

**Comment by gotjosh** [comment]
Rounding up the conversation I had with @davkal offline. While I 100% agree with his thinking - it is unlikely to get this implemented into Prometheus.

Metadata for Prometheus is not associated with a metric but instead with a Target (e.g. if a target is gone we lose all metadata of it despite holding the metrics from it in the TSDB). 

This API endpoint is an oversimplification of the metadata of metrics. Which is kept completely separate from the actual metrics the system holds. We would be pretty much doing the same thing proposed but in the backend - and I imagine it could have plenty of resistance to get in the Prometheus codebase.

I can always go ahead and try to get it in, but if we can practical in this scenario it would be much quicker and not much different.
