### ISSUE TITLE
alexanderzobnin-zabbix-app version: 3.10.5 not working with Grafana 6.6.1

### ISSUE THREAD

**Issue by deepaksharma17** [grafana/grafana#22333]
**What happened**: I had recently upgraded my grafana instance to latest version and since then my old zabbix dashboards are not working. And when I open my saved datasources it says zabbix plugin is not present.

**What you expected to happen**: Upgrade should not impact existing plugins, unless there is a change.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: My grafana plugins details for reference

[root@grafana ~]# cat /etc/grafana/grafana.ini | grep plugin
plugins = /var/lib/grafana/plugins
[root@grafana ~]# ll /var/lib/grafana/plugins | grep zabbix
drwx------ 8 root    root         4096 Feb 20 09:36 alexanderzobnin-zabbix-app
drwx------ 8 grafana grafana      4096 Jan 30 12:00 alexanderzobnin-zabbix-app.old
drwxrwxrwx 3 grafana grafana        34 Jan 24  2018 grafana-zabbix-master

**Environment**:
- Grafana version:	6.6.1
- Data source type & version:	Zabbix & 3.10.5
- OS Grafana is installed on:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
- User OS & Browser:	Microsoft Edge/Chrome
- Grafana plugins:	alexanderzobnin-zabbix-app
- Others:	The error message is "Plugin not found, no installed plugin with that id"

**Comment by torkelo** [comment]
try upgrading or reinstalling the plugin,

**Comment by deepaksharma17** [comment]
Hi...I had tried reinstalling plugin but it didn't worked. Any other solution?
