### ISSUE TITLE
Dashboard Folder Picker: empty value instead of General leads to strange behavior

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/grafana#22339]
**What happened**:
After saving a new dashboard in the General folder, the Dashboard settings page shows it as if it was in an empty folder and I need to save it again and overwrites it to manage permissions on this dashboard.
Plus, I'm able to save a dashboard in a folder with an empty name that leads to strange behavior on the Dashboard management page.

**What you expected to happen**:
The Dashboard Settings page should initializes with the right folder.
It should be impossible to save a dashboard in a folder with an empty name.

**How to reproduce it (as minimally and precisely as possible)**:
When I create a new dashboard and click on "Save Dashboard", the "Folder" field is empty:
![image](https://user-images.githubusercontent.com/35176601/74935077-e7d0e800-53e7-11ea-9945-8f1513ba1e25.png)
Then first strange behavior: if I click on Save without selecting any dashboard, dashboard is saved in General folder.

Then I go to Dashboards > Manage and click on my newly created dashboard.
I click on "Dashboard Settings" and once again, the Folder field is empty:
![image](https://user-images.githubusercontent.com/35176601/74935282-44cc9e00-53e8-11ea-87db-2a94a6d5aa8f.png)
And if I go to "Permissions", I can't set permissions:
![image](https://user-images.githubusercontent.com/35176601/74935348-63cb3000-53e8-11ea-93c8-152ac07edf53.png)
Then, second strange behavior: if I click on Save and Save without selecting any Folder, my dashboard is duplicated in an empty folder and I can't see it anymore on the Dashboard Management page without searching for it:
![image](https://user-images.githubusercontent.com/35176601/74935502-a2f98100-53e8-11ea-9dba-0ffe4f6a6ad6.png)

It's pretty hard to manage Dashboard permissions with this behavior.

**Anything else we need to know?**:
It happens only with the General folder, if I create a folder and save dashboards in this folder, the Folder field works as expected.

**Environment**:
- Grafana version: master
- Data source type & version: N/A
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Firefox / Chrome (same behavior on both)
- Grafana plugins: N/A

**Comment by dprokop** [comment]
Fixed with #22395
