### ISSUE TITLE
Grafana UI: Forms.TextArea missing forwardRef

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#22330]
**What happened**:
`Forms.TextArea` is missing `forwardRef` wrapper, which makes it impossible to pass `register` ref from the new `Forms.Form` component.
**What you expected to happen**:
`Forms.TextArea` should be wrapped into `React.forwardRef` to allow passing refs down to the underlying `teaxtarea`, similar to the way it's done for the `Forms.Input`. 

**How to reproduce it (as minimally and precisely as possible)**:
Use something like `<Forms.TextArea name="name" ref={register} />` inside `Forms.Form` and then look for the `name` property in the form's `onSubmit` form data argument, which is missing. Also there's a warning about missing `forwardRef` in the browser console.

**Comment by torkelo** [comment]
Yea, your right this should be done. Is something you would like to do?

**Comment by krvajal** [comment]
I would like to do it if possible

**Comment by Clarity-89** [comment]
@torkelo I remember @dprokop was saying he was going to work on it, but if not I can take this since it's needed for another PR I'm working on.
