### ISSUE TITLE
Root level Dockerfiles won't build due to TS linting errors

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#22336]
**What happened**:
Dockerfile and Dockerfile.ubuntu won't build due to TypeScript linting errors (see attached log).

**What you expected to happen**:
To be able to build Docker images using Dockerfile and Dockerfile.ubuntu

**How to reproduce it (as minimally and precisely as possible)**:
In Grafana repo: `docker build .`

**Anything else we need to know?**:

**Environment**:
- Grafana version: Revision 4f9b6c55c03462277a62be5084865723ba2e743c
- Data source type & version:

[Build log](https://github.com/grafana/grafana/files/4239103/logs.txt)

**Comment by hugohaggmark** [comment]
@stevenvachon I can see that we've removed `singleQuote` and `printWidth` from the main grafana package.json [here](https://github.com/grafana/grafana/commit/f48169633ce9a9387d468081140b1b1a6e2c5ad6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R203) could that be one of the causes of the lint errors described here? Any advice on how we should fix this?

**Comment by stevenvachon** [comment]
@hugohaggmark those rules are now handled by prettier, which is integrated with eslint. How/where are dokerfiles linted?

**Comment by aknuds1** [comment]
@stevenvachon It should happen via [`grunt`](https://github.com/grafana/grafana/blob/master/Dockerfile#L44).

**Comment by stevenvachon** [comment]
Hmm, the "build" grunt task runs webpack, which is configured to use eslint and prettier. Running `docker build .` locally on my machine doesn't have any linting issues, but I am running out of memory right now, heh. Does removing `node_modules/` and `yarn.lock` followed by running `yarn install` fix the issue for you?

**Comment by aknuds1** [comment]
@stevenvachon Is it possible that some required configuration files aren't copied in by the Dockerfile? I tried again now, after deleting node_modules/ and yarn.lock as you suggested, but it fails in the same way. To me it looks as if some configuration isn't copied into the the Docker image build.

**Comment by stevenvachon** [comment]
Hmm, this looks correct to me:
```dockerfile
COPY Gruntfile.js tsconfig.json .eslintrc .browserslistrc ./
```

**Comment by aknuds1** [comment]
> Hmm, this looks correct to me:
> 
> ```dockerfile
> COPY Gruntfile.js tsconfig.json .eslintrc .browserslistrc ./
> ```

Yeah, I couldn't figure out what makes the configuration differ either, but there has to be something wrong.

**Comment by shankerwangmiao** [comment]
> @stevenvachon It should happen via [`grunt`](https://github.com/grafana/grafana/blob/master/Dockerfile#L44). My guess is just that configuration files governing these lint rules are not copied in during the Docker build (as scripted in Dockerfile and Dockerfile.ubuntu). I need help in determining _which_ files aren't copied in though.

I can confirm by applying the following patch and getting the docker image built successfully.

```
diff --git a/Dockerfile b/Dockerfile
index d51ec4fa5d..697446eae2 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -30,16 +30,10 @@ RUN apk add --no-cache curl &&\
 
 WORKDIR /usr/src/app/
 
-COPY package.json yarn.lock ./
-COPY packages packages
+COPY . ./
 
 RUN yarn install --pure-lockfile --no-progress
 
-COPY Gruntfile.js tsconfig.json .eslintrc .browserslistrc ./
-COPY public public
-COPY scripts scripts
-COPY emails emails
-
 ENV NODE_ENV production
 RUN ./node_modules/.bin/grunt build
 ```

**Comment by stevenvachon** [comment]
Does it also work correctly if you instead add this to the root package.json file's `devDependencies`?:
```json
"@grafana/eslint-config": "1.0.0-rc1",
"@grafana/tsconfig": "1.0.0-rc1",
```

**Comment by shankerwangmiao** [comment]
> Does it also work correctly if you instead add this to the root package.json file's `devDependencies`?:
> 
> ```json
> "@grafana/eslint-config": "1.0.0-rc1",
> "@grafana/tsconfig": "1.0.0-rc1",
> ```

With the following patch, linting errors still happen.

``` patch
diff --git a/package.json b/package.json
index 46f9099014..2a76df1d3e 100644
--- a/package.json
+++ b/package.json
@@ -18,6 +18,8 @@
     "@babel/preset-typescript": "7.8.3",
     "@emotion/core": "10.0.10",
     "@grafana/api-documenter": "0.9.3",
+    "@grafana/eslint-config": "1.0.0-rc1",
+    "@grafana/tsconfig": "1.0.0-rc1",
     "@microsoft/api-extractor": "7.7.8",
     "@rtsao/plugin-proposal-class-properties": "7.0.1-patch.1",
     "@testing-library/react-hooks": "^3.2.1",
```

**Comment by aknuds1** [comment]
Thanks for testing this @shankerwangmiao!

**Comment by aknuds1** [comment]
The patch doesn't work for me either.

**Comment by stevenvachon** [comment]
Maybe all it needs is to include `.editorconfig` in the `COPY`.

**Comment by shankerwangmiao** [comment]
> Maybe all it needs is to include `.editorconfig` in the `COPY`.

I can confirm it works with the following patch applied.

``` patch
diff --git a/Dockerfile b/Dockerfile
index d51ec4fa5d..d0e823afe5 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -35,7 +35,7 @@ COPY packages packages
 
 RUN yarn install --pure-lockfile --no-progress
 
-COPY Gruntfile.js tsconfig.json .eslintrc .browserslistrc ./
+COPY Gruntfile.js tsconfig.json .eslintrc .browserslistrc .editorconfig ./
 COPY public public
 COPY scripts scripts
 COPY emails emails
```

**Comment by hugohaggmark** [comment]
Just out of curiosity, why do we rely on `.editorconfig` for this? Is it because `.editorconfig` props will work for any editor and language?

**Comment by aknuds1** [comment]
Wow, I never thought .editorconfig would have an effect on linting.

**Comment by stevenvachon** [comment]
Less redundancy. Since `.editorconfig` contains options like `indent_size`, `indent_style` and `quote_type`, prettier loads it if it exists.
