### ISSUE TITLE
Users list on server admin page is not alphabetically ordered

### ISSUE THREAD

**Issue by vikkyomkar** [grafana/grafana#22348]
**What happened**:
Users list is not alphabetically ordered by username.

**What you expected to happen**:
Users list should be alphabetically ordered by username

**How to reproduce it (as minimally and precisely as possible)**:
Goto:
Server Admin->Users

**Environment**:
- Grafana version: Latest
- Data source type & version: latest
- OS Grafana is installed on: MacOS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The org user list is queried here:  https://github.com/grafana/grafana/blob/49c86d011f8b9dc8cf558bc2051206d39bcc9dcb/pkg/services/sqlstore/org_users.go#L132

**Comment by aknuds1** [comment]
Thanks @torkelo.

**Comment by aknuds1** [comment]
@torkelo Does that mean we can close the issue, since the user list is evidently already ordered?

**Comment by aknuds1** [comment]
@vikkyomkar Are you OK with the user list being ordered by email first, rather than username first?

**Comment by vikkyomkar** [comment]
@aknuds1 ...my bad, Its under SERVER ADMIN -> USERS

**Comment by aknuds1** [comment]
For reference the ordering is carried out at https://github.com/grafana/grafana/blob/53007e07e31d7752b12c9ef2e7c1c326ea57eaa8/pkg/services/sqlstore/user.go#L457.
