### ISSUE TITLE
User admin :  user information say "synced by ldap" but do not use ldap

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#22343]
**What happened**:
When a go on an user on the administration, the "user information" says "synced by ldap"

![image](https://user-images.githubusercontent.com/27487887/74955304-be728500-5404-11ea-971c-51e14dedeaaa.png)

but I'm not connected to any ldap.

**Environment**:
- Grafana version: 6.6.1

**Comment by dprokop** [comment]
Can't replicate. @alexanderzobnin would you mind taking a look at this?

**Comment by alexanderzobnin** [comment]
Duplicates #23471
