### ISSUE TITLE
Be able to start only alerting engine

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#22344]
**What would you like to be added**:
Be able to start only the alerting engine of grafana without starting the whole things.
Maybe do something like it is done with the render plugin (by default grafana can render the images but you can choose to run the renderer plugin alone somewhere else)

**Why is this needed**:
For security and networking reasons I would like the place the alerting module safely behind our firewall and as close as possible from the datasource.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
