### ISSUE TITLE
API Request is not working for grafana cloud

### ISSUE THREAD

**Issue by Guruhbk** [grafana/grafana#22350]
**What happened**:
 I’m trying to access the grafana URL through API call, but all I got was **{“message”: “Invalid username or password”}.** Even though it is a valid credential. 
**What you expected to happen**:
Expected output: **{"id":1,"name":"Main Org."}**
**How to reproduce it (as minimally and precisely as possible)**:
Create a grafana host server from grafana cloud. Use the login credentials and try accessing it in  
curl
**curl https://admin:admin@test.grafana.net/api/org/**
**Anything else we need to know?**:
1. API call works fine with a normal grafana package. I'm facing issue only with grafana cloud.
2. I'm facing issues if I use a username and password for authentication. Instead, if I use API keys, it's working fine. 
**Environment**: 
- Grafana version: 6.6.2
- Data source type & version: Elasticsearch v7.4.0
- OS Grafana is installed on: Grafana cloud
- User OS & Browser: ubuntu 18.04 & google-chrome
- Grafana plugins: - 
- Others:

**Comment by aknuds1** [comment]
Hi - please rewrite your issue according to the standard issue template. Otherwise it's tricky for us to interpret your problem.

**Comment by Guruhbk** [comment]
@aknuds1 Hi - Thanks for response. I updated it as per your request.

**Comment by Guruhbk** [comment]
@aknuds1 Any update?

**Comment by torkelo** [comment]
Use an api key (created inside Grafana) to access API programmatically

**Comment by Guruhbk** [comment]
@torkelo Hi, I know that works. But we need to use only username & password. We are restricting access based on the user credentials.

**Comment by torkelo** [comment]
What authentication method are you using? (ie how are do users sign in to your hosted Grafana instance). 

Is it a paid or free hosted Grafana instance? If paid please contact support
