### ISSUE TITLE
Ability to hide sidebar

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#22354]
**What would you like to be added**:
Ability to hide sidebar and option to make it hidden by default after opening the page.

**Why is this needed**:
Hiding feature was available in some previous versions. It was possible to hide sidemenu by clicking Grafana logo in the top left corner.
Hiding sidebar makes the page more readable.

**Comment by torkelo** [comment]
You can still do this, just it tv button on the dashboard

**Comment by szerwi** [comment]
@torkelo In TV/kiosk mode there are no "i" icons with panel description which I'd like to keep.

**Comment by DonatoD** [comment]
And mode, unfortunately in TV/Kiosk mode all the dashboard links are not visible any more :-(
Googling, I can see that these are two great features more than welcome to the users, moreover these features were once available

**Comment by pedroetb** [comment]
Also, in TV or Kiosk mode, users can still press Esc key and get sidebar back. Hiding sidebar permanently would be a nice feature for embedding full dashboards with no grafana navigation at all.

**Comment by syncware-ai** [comment]
> And more, unfortunately in TV/Kiosk mode all the dashboard links are not visible any more :-( As well as the time controls Googling, I can see that these are two great features more than welcome to the users, moreover these features were once available.
> 
> * the possibility of hide the left side bar,
> * the possibility of having dashboard, variable links  and time controls witin tv/kiosk mode

+1 here
