### ISSUE TITLE
Explore logs stuck running query

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#22357]
**What happened**:
Explore logs stuck running query

**What you expected to happen**:
Display logs.

**How to reproduce it (as minimally and precisely as possible)**:
Click "Explore", display shows Metrics from a log source (graph working and table shows mangled text).
Switch to "Logs", app hangs running query (circle spinning in top right "Run Query" button + line moving horizontally inside "Logs" panel).

**Anything else we need to know?**:
Datasource has **Index name** = `log-*` that matches multiple indexes.
Similar datasource from apm with index `apm-*` works.

**Environment**:
- Grafana version:  v6.6.1 (21bf8b71bc)
- Data source type & version: elasticsearch 7.6.0
- OS Grafana is installed on: docker container "grafana/grafana"
- User OS & Browser: Win10, Firefox 73.0.1
- Grafana plugins:
- Others:

**Comment by cdalexndr** [comment]
After playing around with different settings, it seems that the culprit is **Level field name** setting.
Leaving it blank, logs are displayed correctly.
Changing it to `log.level` causes query to hang. 
Note that part of documents matched by datasource index pattern don't have this log level field (ex: nginx access logs).

Replicated same behavior with another working datasource `apm-*`. Changing the level field name hangs query.

**Comment by aocenas** [comment]
@ivanahuckova I think you were fixing this issue, can you check and close this in that case?

**Comment by ivanahuckova** [comment]
@cdalexndr I will close this issue for now, but we can reopen the issue again, if providing of string log level or updating Grafana won't fix your problem.
