### ISSUE TITLE
Min/max/etc are not recalculated in snapshots

### ISSUE THREAD

**Issue by hasso** [grafana/grafana#22356]
**What happened**:

If you zoom in to snapshots, calculated values in the legend (min/max/avg/current/total) of the graph remain the same and seem to reflect the whole snapshot data.  Users don't understand why live graphs and snapshots behave differently.

**What you expected to happen**:

I'd expect calculated values in the legend to reflect data currently present in the graph.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a dashboard with a graph and switch on calculated values of the legend (min/max/avg/current/total).
- Create snapshot of the graph.
- Zoom in/out in the snapshot – calculated values in the legend remains the same regardless of the zoom. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus 2.15.2
- OS Grafana is installed on: Linux
- User OS & Browser: MacOSX, Firefox 73.0.1
- Grafana plugins: none

**Comment by strgrb** [comment]
I've met the same problem with version 7.5.1
