### ISSUE TITLE
Explore with Loki wrong returned results

### ISSUE THREAD

**Issue by orangr1989** [grafana/grafana#22352]
**What happened**:  
After run query from Loki datasource, the maximum returned number of results is different from the configured limit: 1380 instead of 2000.

**What you expected to happen**: 
Get maximum number of returned results as i configured, 2000. 

**How to reproduce it (as minimally and precisely as possible)**:
Run query in loki explorer, with return results hit the limit.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/17577807/74972873-30f65b80-542b-11ea-8642-855db7996a9b.png)

**Environment**:
- Grafana version: v6.6.2
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS - Chrome

**Comment by papagian** [comment]
Are there more than 1380 results?

**Comment by orangr1989** [comment]
Sure,

It worked in the previous versions..

**Comment by wilsonhipolito** [comment]
Hey @orangr1989 , have you tried to reduce the zoom before running the query?

I know it seems silly, but when I try to query Loki using Chrome at "100% zoom", I always get around 1800 results:
![Screenshot from 2020-02-24 18-18-28](https://user-images.githubusercontent.com/15637984/75175286-57214180-5732-11ea-8211-0643b560a501.png)

and when I change the zoom to 75%, I get more results:
![Screenshot from 2020-02-24 18-19-22](https://user-images.githubusercontent.com/15637984/75175318-630d0380-5732-11ea-80d5-3a1d74fb2d28.png)

Super weird, but somehow the request sent to Loki from Grafana changes according to your current window size/zoom :thinking:

**Comment by orangr1989** [comment]
hi, @wilsonhipolito 
its also happened to me (i must say that in the previous versions all worked perfectly):

in 100%:
![image](https://user-images.githubusercontent.com/17577807/75177850-9dc96880-573f-11ea-94d2-db0fdf978edc.png)

in 75%
![image](https://user-images.githubusercontent.com/17577807/75177981-d701d880-573f-11ea-9ad2-92f2033c2db2.png)

in 50% (finally 2000/2000)
![image](https://user-images.githubusercontent.com/17577807/75178066-06184a00-5740-11ea-8dc5-0259d46f826e.png)

indeed,
super weird

**Comment by thomasdraebing** [comment]
I've also observed this and noticed that the request being sent to Loki contains a limit-parameter setting this limit. So Grafana somehow actively limits the results to this number, ignoring the configured line limit.

**Comment by oshamin** [comment]
I can also confirm the issue. The query inspector shows, that Grafana adds limit argument. Why?
![Annotation 2020-03-12 004542](https://user-images.githubusercontent.com/4929317/76474149-0466ab80-63fb-11ea-9d65-b8627e2aa40b.png)

And here is result in the Grafana explorer.
![Annotation 2020-03-12 004303](https://user-images.githubusercontent.com/4929317/76474132-f1ec7200-63fa-11ea-9a0b-5498355fdb9c.png)

current setup:
```
grafana/grafana     6.6.2               a8aa0688fd3a        2 weeks ago         233MB
grafana/promtail    v1.3.0              b17d3966b002        6 weeks ago         134MB
grafana/loki        v1.3.0              2ac02602ebc2        6 weeks ago         46.6MB
```

Please fix it.

**Comment by oshamin** [comment]
When are you going to address the issue?

**Comment by thomasdraebing** [comment]
As far as I can see, this is fixed with Grafana 6.7.1. There is now a field called 'Line Limit' next to the query form. By default it is set to 'auto', which is the old behaviour, but you can set it to any number smaller than the max number configured for the datasource and then that limit is used. A large number of log lines however might still take a long time to load in your browser, since there is now pagination so far.

**Comment by aocenas** [comment]
@ivanahuckova or @Estrax I think we were fixing this issue, do you remember that or can you check if this is still an issue?

**Comment by Estrax** [comment]
@aocenas I think it is already solved (though for other datasources than Loki there's still a limit based on `containerWidth`).

**Comment by ivanahuckova** [comment]
Yes, this issue was fixed in https://github.com/grafana/grafana/pull/22877 which was part of Grafana 6.7.1 release. Closing issue. 🙂
