### ISSUE TITLE
FieldOverrides: Generic component for displaying variables suggestions

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#22359]
For i.e. Title field in field config it's possible to use variables for the title to be interpolated. We need a component, similar to data link input` that given a suggestions list will allow picking up variable from a suggestions list dropdown.

**Comment by torkelo** [comment]
a very general typeahead input would be useful for QueryEditors as well

**Comment by torkelo** [comment]
A simple autocomplete input component maybe?
