### ISSUE TITLE
request url too long cause response error because request method is get

### ISSUE THREAD

**Issue by emilie9** [grafana/grafana#22363]
**What happened**:
api/datasources/proxy/1/api/v1/query_range?
query=irate(http_server_requests_seconds_sum%7Binstance%3D~%2210%5C%5C.244%5C%5C.37%5C%5C.107%3A8080%7C10%5C%5C.244%5C%5C.41%5C%5C.65%3A8080%7C10%5C%5C.244%5C%5C.42%5C%5C.139%3A8080%7C10%5C%5C.244%5C%5C.6%5C%5C.240%3A8080%7C10%5C%5C.244%5C%5C.7%5C%5C.9%3A8080%7C10%5C%5C.244%5C%5C.8%5C%5C.224%3A8080%22%2C%20application%3D%22ECIntranet%22%2C%20exception%3D%22None%22%2C%20uri!~%22.*actuator.*%22%7D%5B5m%5D)%20%2F%20irate(http_server_requests_seconds_count%7Binstance%3D~%2210%5C%5C.244%5C%5C.37%5C%5C.107%3A8080%7C10%5C%5C.244%5C%5C.41%5C%5C.65%3A8080%7C10%5C%5C.244%5C%5C.42%5C%5C.139%3A8080%7C10%5C%5C.244%5C%5C.6%5C%5C.240%3A8080%7C10%5C%5C.244%5C%5C.7%5C%5C.9%3A8080%7C10%5C%5C.244%5C%5C.8%5C%5C.224%3A8080%22%2C%20application%3D%22ECIntranet%22%2C%20exception%3D%22None%22%2C%20uri!~%22.*actuator.*%22%7D%5B5m%5D)&start=1581672000&end=1582276800&step=1200

I get this request url  from grafana webui,the response of this request is right,but if the query is too large, the status of this request is error.
the response error message is :
"query processing would load too many samples into memory in query execution"
you can see the attaches blow.

![request](https://user-images.githubusercontent.com/44674722/75023422-bf71e800-54d2-11ea-9aac-a15b52945ed5.png)
![response](https://user-images.githubusercontent.com/44674722/75023429-c3056f00-54d2-11ea-9f14-608ebe9f1c5e.png)

**What you expected to happen**:
i want get right response if the url is too large
**How to reproduce it (as minimally and precisely as possible)**:
change this request method from GET to POST 
**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.5.2
- Data source type & version:premethus 
- OS Grafana is installed on:true
- User OS & Browser:windows7 & google
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you can change method to POST in data source options

**Comment by emilie9** [comment]
thanks，i use regex to shorten the para ,and get right response
