### ISSUE TITLE
Contrast of a Notification Button in Graph Alerting Tab

### ISSUE THREAD

**Issue by MaximKipot** [grafana/grafana#22367]
Hello,

having created a notification channel allows one to use it in graphs for various notifications. The background color used is not accessible and is fixed in code and is not part of a theme. The dark theme has a marginally accessible color contrast of 4.48, the light theme has a color contrast of 1.19 with #52545c as font color and #00678b as background.

**Steps to reproduce**:

- create a notification channel
- setup a graph
- open alert panel while editing a graph

**Actual Result**:
<img width="493" alt="Screenshot 2020-02-21 at 12 17 15" src="https://user-images.githubusercontent.com/1902515/75026389-9129e380-54a5-11ea-8e5c-7e9c70543d89.png">
<img width="440" alt="Screenshot 2020-02-21 at 12 16 49" src="https://user-images.githubusercontent.com/1902515/75027294-f7fbcc80-54a6-11ea-9778-2483ef9b5fe4.png">

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion]
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html 
&
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast

**Environment**:
- Grafana version: 6.7.0-pre
- Data source type & version: TestData DB coming with Simple dummy streaming example
- User OS & Browser: MacOS Mojave, Mozilla and Chrome

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by krvajal** [comment]
Working on a fix.

**Comment by tskarhed** [comment]
@krvajal How is it going with the fix?

**Comment by krvajal** [comment]
I finished it but forgot to submit the PR. I will send it today.

**Comment by krvajal** [comment]
I can not reproduce the issue any longer in master.
