### ISSUE TITLE
Signal that a graph is stacked

### ISSUE THREAD

**Issue by JensRantil** [grafana/grafana#22366]
Background: Stacked graphs are great when the total sum of all graphs is relevant, but I've seen over and over again where it's hard to interpret a graph correctly because a viewer doesn't know it's stacked. We just had a case this morning where the numbers (Y axis magnitude) simply didn't match the hover legend. It was close that one of our engineers made an incorrect decision based on the Y axis without knowing that the graph was stacked:

![image](https://user-images.githubusercontent.com/730342/75025453-85392400-549b-11ea-8cfe-7dc4dd0923c5.png)

Feature request: See if it somehow be signaled to a viewer that a graph is stacked.

Ideas: Could a stacked graph always enable "Fill" and "Fill gradient" to signal it's stacked as soon as one enables "Stack: true"? Other ways of signalling that it's stacked?

Workaround: Add "(stacked)" in the title manually in every graph to signal to the viewer what they are looking at. That's what I do these days. However, it's hard to align all our >130 engineers to do the same (unless there's some Grafana plugin that could do this for me/us).

**Comment by torkelo** [comment]
duplicate & similar to https://github.com/grafana/grafana/issues/3907
