### ISSUE TITLE
Graph: Distinguish real data from future approximation

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#22365]
**What would you like to be added**:
We need the possibilty to make different future part of the graph
Example:
![GrafanaDotGraphExample](https://user-images.githubusercontent.com/1506512/75021792-0695b400-54a6-11ea-89b9-fb72f043774d.png)

The graph is drawn with solid line up to the current moment. The future anticipation drawn with dot line

This feature should be switchable through panel options because many graphs do not require this feature

**Why is this needed**:
For example we have per month graphs. Than the graph for the current month will contain the real data up to the current day and the future approximation. The user should visually distinguish this types of data. This is needed to protect him from a heart attack

**Comment by ryantxu** [comment]
Do you really have real and predicted data in a single series?

Can it be two series that you color differnetly?  (that is how i have seem many people support this)
