### ISSUE TITLE
Explore doesn't honour Prometheus step

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#22362]
In this explore panel, we can see the http request using step 15 even though I've put both in at 60.

<img width="1392" alt="Screenshot 2020-02-21 at 09 49 18" src="https://user-images.githubusercontent.com/444037/75023320-83696380-548f-11ea-9b85-7f9165b73fb7.png">

**Comment by s-h-a-d-o-w** [comment]
This happened because no unit was provided for the step value. I just discussed this with @davkal and he suggested that if no unit is provided, we should fall back to seconds.

**Comment by s-h-a-d-o-w** [comment]
Presumably, the behavior should be the same for "Min. step" in the dashboard, where the same problem occurs.

But the function where the conversion from this string to a number happens is used not only used by prometheus but also cloudwatch. Does it make sense to address it there and use this fallback for cloudwatch too?

**Comment by davkal** [comment]
Solving this centrally (i.e., interpreting `15` as `15s`) sounds good, if @torkelo agrees. On wrong input, the error `Invalid interval string, expecting a number followed by one of "Mwdhmsy"` is only logged to the console, and it might be frustrating to users to see that nothing happens. 
If we don't want to solve this centrally, then I suggest we only do it for that particular step input field.

**Comment by torkelo** [comment]
Yes, sounds like a good fallback
