### ISSUE TITLE
Proxying through Grafana gives sporadic error 500

### ISSUE THREAD

**Issue by Tenzer** [grafana/grafana#2236]
I have recently upgraded from Grafana 1.9 to 2.0.2 and switched to using proxying of the calls to Graphite in order to avoid having that endpoint publicly accessible. Since then I have seen sporadic cases where a dashboard doesn't load all the panels upon auto refresh, only for the panel to load correctly the next time it's updated, but possibly with other panels not loading.

The error on the red tab on the panel is "Timeseries data request error" and by looking at the browser console the call to `/api/datasources/proxy/1/render` get a "500 Internal Server Error" response. Looking at the Grafana log its only mention of it is "Completed /render 500 Internal Server Error in 6.129878ms".

It doesn't seem to be related to the amount of data requested from Graphite, it happens just as much if I request a 5 minute time range as with a week. The requests are also returned from Grafana as fast as the other requests to the same endpoint for the other panels, so it doesn't seem to be a matter of timeouts. The server is 95+% idle, so I don't think load is the issue here.

In an attempt to debug this problem I did some package sniffing of requests to http://127.0.0.1:8080/ (Graphite) on the `lo` interface, and then did some refreshes of a dashboard with 9 panels on it. If there was no panels that failed loading when I did a refresh, I restarted the package capture in order to get a clean file with only the single refresh inside. When I did see a panel that failed to load I investigated the dump and only saw 8 requests to `/render` on the Graphite API, and also only 8 SYN packages, telling me Grafana doesn't even make a connection to Graphite.

I have tried to update Grafana to the latest nightly build as of yesterday, but that didn't improve anything.

During some local testing I managed to get some more error messages which seemingly are printed to stderr. They vary between the following:
* "http: proxy error: EOF"
* "http: proxy error: use of closed network connection"
* "http: proxy error: http: can't write HTTP request on broken connection"
* "http: proxy error: net/http: transport closed before response was received"

I have tried to both disable keep-alive and the timeout specified in [dataproxy.go](https://github.com/grafana/grafana/blob/master/pkg/api/dataproxy.go) and change them to be 3 minutes instead of 30 seconds. Neither had any effect.

I also implement caching of the `httputil.ReverseProxy` instances for each data source, but even though the cache seemed to work by itself, it didn't solve the problem either (I can make a PR for this but it doesn't handle updates to data sources right now).

Do you have any other suggestions on what could cause this?

**Comment by torkelo** [comment]
I havent seen this myself, or maybe not sure. How often can you replicate this? 

Great job on the issue btw, thanks for taking the time to investigate it before opening the issue!

**Comment by Tenzer** [comment]
I can replicate it pretty consistently. From a quick benchmark I refreshed the dashboard with 9 panels on it 10 times, and a total of 4 panels failed to load. It's not a breaking issue as such, it's just more annoying that panels randomly fail to load and makes me think the stats server isn't working correctly or is overloaded.

**Comment by Tenzer** [comment]
I just tried to refresh a bunch of times on http://play.grafana.org/dashboard/db/graph-styles (the dashboard with the most panels on I could find on the site), and it didn't give any problems. I guess it could be an operating system dependent thing? I am running Grafana and Graphite on an Ubuntu 14.04 machine and during testing of code changes I used the same Graphite server through SSH tunneling but with Grafana on my local Arch Linux box.

**Comment by torkelo** [comment]
play.grafana.org uses ubuntu 14.04 I think as well

**Comment by Tenzer** [comment]
As a test I just tried to point the data source in Grafana at the Nginx I have running in front of it all, and then pointed Nginx at Graphite, so basically just adding Nginx in between Grafana and Graphite. After I've done that I am no longer able to replicate the issue, so I guess may be due to how we are running Graphite?

Do you have anything between Grafana and Graphite in your setup, or is that a direct connection?

I'll continue to dig further on this.

**Comment by torkelo** [comment]
I have an nginx infront of graphite

**Comment by Tenzer** [comment]
I haven't been able to reproduce the problem by simply bursting calls with curl against Graphite, so I guess it's possibly some interaction between Go and Graphite. I'll probably just leave Nginx in between the two and consider the problem solved for now, due to the amount of time I have used to debug this already.

Is there any good place to add some documentation or hint about this, or should we just leave it at this issue?

**Comment by torkelo** [comment]
dont, know, can see if others report it as well

**Comment by anarcher** [comment]
I have same issue. and graphite`s response codes are  200. 

```
2015/07/08 07:02:23 http: proxy error: EOF
2015/07/08 07:02:23 [I] Completed /render 500 Internal Server Error in 2.823029ms
2015/07/08 07:02:26 http: proxy error: EOF
2015/07/08 07:02:26 [I] Completed /render 500 Internal Server Error in 1.967683ms
```

**Comment by anarcher** [comment]
I am not sure that this issue is related to https://github.com/golang/go/issues/9122. 
But I built it with`DisableKeepAlives: true` and tested it. I can't see `proxy error: EOF` and `[I] Completed /render 500 Internal Server Error` in grafana's log anymore.
What do you think about it? 

```
diff --git a/pkg/api/dataproxy.go b/pkg/api/dataproxy.go
index 1107529..185c64c 100644
--- a/pkg/api/dataproxy.go
+++ b/pkg/api/dataproxy.go
@@ -21,6 +21,7 @@ var dataProxyTransport = &http.Transport{
                Timeout:   30 * time.Second,
                KeepAlive: 30 * time.Second,
        }).Dial,
+       DisableKeepAlives:   true,
        TLSHandshakeTimeout: 10 * time.Second,
 }
```

**Comment by Tenzer** [comment]
Ah, nice find @anarcher! I guess it would be good as a work around for people using Graphite, which apparently has problems with keep alive then. I wonder if a setting to disable keep alive for a data source could be added?

**Comment by Tenzer** [comment]
Just a bit more information for this issue. I recently reinstalled our stats server and switched from running Graphite-Web with uWSGI to Gunicorn. Out of curiosity I tried to point Grafana directly at Graphite-Web instead of going through Nginx, and I haven't seen this problem on the new server. It could seem like this only is a problem if you run Graphite-Web with uWSGI.

**Comment by petecheslock** [comment]
FWIW I ran into this exact same issue with graphite-web when running it via uWSGI, i deployed graphite-api instead and this issue is no longer happening for me.

**Comment by sveinse** [comment]
I'm running grafana on Ubuntu 15.04, using vanilla Ubuntu packages for grafana (2.6.0) and graphite-web (0.9.12+debian+7) over Apache wsgi. I see the "http: proxy error: EOF" Internal error. all the time, that is only a few seconds apart.

Is there anything I can do to prevent this issue?

(FYI This is a production server, so I'd hoped to avoid custom installation. And I hoped that I could use Apache, as Apache is already deployed on the server.)

**Comment by torkelo** [comment]
Try upgrading graphite, you are running a very old version that has a number of http bugs that can cause things like this. Also 0.9.12 has a crippling performance problem with its json rendering

**Comment by sveinse** [comment]
OK I will. I see that graphite is not available in any newer version in Ubuntu 15.04. Ubuntu 16.04 is soon to be released and it carries graphite 0.9.15. I'll live with the errors now and wait for the release (as the server shall be upgraded anyways).

**Comment by sstorie** [comment]
I've had similar problems using the latest docker image as part of a prometheus installation. When I switch the prometheus data source to use direct communication (instead of proxying) these issues seem to go away.

**Comment by andrewthad** [comment]
Why was this issue closed? It is still affecting users, myself included.

**Comment by thibaut-fagart** [comment]
i seem to have the same issue.
I'm running Graphana & Graphite in separate dockers on the same AWS EC2 instance.
I'm using  Grafana v3.1.1 (commit: a4d2708) .
I'm not sure what Graphite version is included in the image (ennexa/graphite) but it's probably 0.9.15

**Comment by andrewthad** [comment]
I was able to resolve this issue by pointing Grafana  at graphite-web instead of graphite-api.  I had originally not realized that graphite-web  also provides the API.

**Comment by vishalth** [comment]
I am new to grafana dashboard .I see the error "http: proxy error: dial  tcp ipaddress:port connect: cannot assign requested address"  in my grafana logs , the datasource is tsdb. When i restart the tsdb or grafana , the error goes away and after while like 2 hrs it comes back , and I see the dashboards failing .The current versio of grafana we are using in 4.0 . Any kind guidence or advice to fix the issue is greatly appreciated .

**Comment by vishalth** [comment]
can someone please reply to the above comment . Thanks.

**Comment by Tenzer** [comment]
I'm afraid that asking your question on a two year old, closed, unrelated issue isn't the best way for you to get an answer. I would suggest you to either create your own issue, or perhaps post it the community site: https://community.grafana.com.

**Comment by narsing1984** [comment]
How to resolve proxy error when connecting Elasticsearch DB to Grafana

**Comment by daniellee** [comment]
@narsing1984 can you ask that question on the community site: https://community.grafana.com/ and provide some more detail (error message in GUI and check Grafana server log for errors) in your question.
