### ISSUE TITLE
series style override, flux

### ISSUE THREAD

**Issue by ext452** [grafana/grafana#22361]
Hi everyone. Have some trouble with series override when using Flux plugin - override do not work.
For example, i have some query like this:
```
from(bucket: "bucket/")
  |> range($range)
  |> filter(fn:(r) => r.tag == "some_tag")
  |> window(every: 1h)
  |> first()
  |> map(fn: (r) => ({
                    _time: r._time,            
                    _value: math.round(x: r._value),
                    _field: "field_name"
                }))  
  |> group()
  |> difference()
```

When i create series override, field name is appear, but when i customize style - nothing is working.
Does Grafana support series style override? (Grafana v6.5.1, Flux plugin v5.4.1)

**Comment by torkelo** [comment]
yes, make sure the series override matches the series name you see in the legend
