### ISSUE TITLE
graphite query editor: support function api to display function information

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#22374]
Graphite has an api that provides information about functions, which arguments it accepts, etc.
see https://graphite.readthedocs.io/en/latest/functions.html#function-api

would be nice to expose this in grafana query editor

**Comment by Dieterbe** [comment]
cc @DanCech

**Comment by ifrost** [comment]
This functionality had been added in https://github.com/grafana/grafana/pull/10505 but got broken in Graphite 1.1.7, and never fixed in Graphite project. We added a workaround for this issue in Grafana in https://github.com/grafana/grafana/pull/32305
