### ISSUE TITLE
Users list on org->User page is case sensitive 

### ISSUE THREAD

**Issue by vikkyomkar** [grafana/grafana#22371]
**What happened**:

Usernames/emails starting with Upper case letter are listed at the top followed by usernames/emails starting with lower case letters 

http://localhost:3000/org/users

![image](https://user-images.githubusercontent.com/25223784/75040073-ff8b9780-54df-11ea-8af0-47daf1c59e7b.png)

**What you expected to happen**:

User list should be case insensitive 
![image](https://user-images.githubusercontent.com/25223784/75040108-1336fe00-54e0-11ea-8710-807f0091ca2c.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create users with upper and lower case letters

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
@torkelo @daniellee @bergquist Do you agree that this is a problem and should be changed?

**Comment by torkelo** [comment]
yes,

**Comment by torkelo** [comment]
added help wanted label

**Comment by aknuds1** [comment]
@torkelo Does it make sense to order in the way that vikkyomkar does in the PR: `sess.OrderBy("LOWER(u.email),u.email")`?

**Comment by vikkyomkar** [comment]
I can raise a PR for this change once all agrees

**Comment by vikkyomkar** [comment]
@aknuds1 @torkelo Shall I make below change a raise a PR to fix this bug?
`sess.OrderBy("LOWER(u.email),u.email")`

**Comment by torkelo** [comment]
should be login first as that is the first column

**Comment by vikkyomkar** [comment]
> should be login first as that is the first column

Then below one should serve the need
`sess.OrderBy("LOWER(u.login),u.login,LOWER(u.email),u.email")`

**Comment by torkelo** [comment]
yes

**Comment by aknuds1** [comment]
@vikkyomkar Can you first of all make a PR for this issue, since your fix is agreed on?

**Comment by vikkyomkar** [comment]
Sure @aknuds1

**Comment by aknuds1** [comment]
It seems we have to solve this issue only after we've converted usernames to be case insensitive, for the reason that ordering by first LOWER(username) and then username will have too much of an impact on query performance. At least that's the conclusion we came to through our internal analysis.

**Comment by thisisobate** [comment]
@aknuds1 any progress on this?
