### ISSUE TITLE
Explore: changing date interval results in "Unkown elastic error response"

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#22377]
**What happened**:
Using explore to visualize logs works fine for `last 1 hour` interval.
Changing this interval to a greater time period results in `Unkown elastic error response`.

**What you expected to happen**:
No error.

**How to reproduce it (as minimally and precisely as possible)**:
Elasticsearch datasource with a `log-*` pattern matching multiple indices.
Increase "Explore" interval to "last 6 hours".
Error occurs.

**Anything else we need to know?**:
ES logs shows:
```
{
  "type": "deprecation",
  "timestamp": "2020-02-21T15:39:40,163Z",
  "level": "WARN",
  "component": "o.e.d.s.a.b.h.DateHistogramAggregationBuilder",
  "cluster.name": "docker-cluster",
  "node.name": "8b48b9e3207d",
  "message": "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future.",
  "cluster.uuid": "JVe-ceETQ9iVMKEYEGmZ5A",
  "node.id": "apuPpdWTRmekrmmoTbE1Pg"
}
```
Note that the same warning is shown even when using the working interval `last 1 hour`.

**Environment**:
- Grafana version:  v6.6.1 (21bf8b71bc)
- Data source type & version: elasticsearhc 7.6.0
- OS Grafana is installed on: docker container `grafana/grafana`
- User OS & Browser: Win10, Firefox 73.0.1
- Grafana plugins: none
- Others:

**Comment by cdalexndr** [comment]
If pressing **Time range zoom out** for **last 2 hours** interval it works, but pressing again for **last 4 hours** results in error.

**Comment by papagian** [comment]
I'm unable to trigger this error, but it seems to do with this [deprecation](https://github.com/grafana/grafana/issues/17991#issuecomment-509547853).

**Comment by ivanahuckova** [comment]
Hello @cdalexndr. It seems that this issue is the same as https://github.com/grafana/grafana/issues/17327 which was fixed by https://github.com/grafana/grafana/pull/21937 in 6.6.2 release. So upgrading to (at least) Grafana 6.6.2 should solve your problem. If upgrading to 6.6.2 won't work, please let us know and we can reopen the issue.
