### ISSUE TITLE
Docs feedback: /administration/provisioning.md

### ISSUE THREAD

**Issue by Hipska** [grafana/grafana#22378]
The link behind  `provisioning/dashboards` under [Dashboards](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) is pointing to a non existing page. (https://grafana.com/installation/configuration#provisioning)

**Comment by RobinJoe** [comment]
Looks like the link is also broken on the following page: https://grafana.com/docs/grafana/latest/guides/whats-new-in-v5/#dashboards under the [dashboards](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v5/#dashboards) heading. 

I can investigate where the page has gone and update the URL.

**Comment by oddlittlebird** [comment]
@robbymilo, please take a look.

**Comment by oddlittlebird** [comment]
@RobinJoe , it looks like the `relref` links were not applied in these cases. Do you want to take a stab at  it?

More information about `relref` and testing docs locally is here: https://github.com/grafana/grafana/blob/master/docs/README.md

**Comment by RobinJoe** [comment]
Thanks @oddlittlebird , the README with the docker instructions was the missing piece I needed. I was reading about the ``relref`` links in the Hugo docs, so will give this a try to make the fix. Will send a Slack message if I run into a blocker.
