### ISSUE TITLE
manage.py not found error while installing graphite in open suse 13.1 

### ISSUE THREAD

**Issue by krajesh112** [grafana/grafana#2238]
My Installation steps:
 Install with yast:
 python-2.7 (or higher)
 python-django
 python-ldap
 python-python-memcached
 python-pysqlite
 sqlite3
 sqlite2
 python-setuptools-git
 python-cairo
 python-pip
 python-Twisted
 git
 apache2-mod_wsgi

install with easy_install:
 easy_install txamqp
 easy_install django-tagging

Get Git packs:
 cd
 git clone https://github.com/graphite-project/graphite-web.git
 cd graphite-web
 git checkout 0.9.x
 cd ..
 git clone https://github.com/graphite-project/carbon.git
 cd carbon
 git checkout 0.9.x
 cd ..
 git clone https://github.com/graphite-project/whisper.git
 cd whisper
 git checkout 0.9.x
 cd ..

install whisper/carbon:
 pushd whisper
 sudo python setup.py install
 popd
 pushd carbon
 python setup.py install
 popd

konfigurate carbon:
 pushd /opt/graphite/conf
 cp carbon.conf.example carbon.conf
 cp storage-schemas.conf.example storage-schemas.conf
 storageschema edit:
 #[default_1min_for_1day]
 #pattern = .*
 #retentions = 60s:1d

[default_1MinFor2Months_1hFor13Months]
 pattern = .*
 retentions = 60:89280,3600:9672

install webapp:
 cd
 pushd graphite-web
 python check-dependencies.py # < All Okay :)
 popd
 mkdir /srv/www/run
 chmod 777 /srv/www/run
 pushd graphite-web
 python setup.py install
 popd
 chgrp -R www /opt/graphite/webapp

#here i edit apache vhost conf, but i dont post it :)

wsgi script:
 cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/conf/graphite.wsgi
 chgrp www /opt/graphite/conf/graphite.wsgi

create DB:
 cd /opt/graphite/
 PYTHONPATH=`pwd`/webapp:`pwd`/whisper python ./webapp/graphite/manage.py syncdb

Here Iam getting manage.py is not found..

**Comment by torkelo** [comment]
think you opened this issue in the wrong repo :) 

https://github.com/graphite-project/graphite-web
