### ISSUE TITLE
Graph panel: Numeric colums of Table type metrics not shown when first value is NaN

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/grafana#22389]
**What happened**:
Numeric colums of a Table type metric is not shown in *Graph panel* when the first value is a Double.NaN value. But are shown, if the first value is a numeric value, followed by Double.NaN values.

**What you expected to happen**:
I expect, that all colums with column type *number* are shown in Graph panel. Even if the column does not contain any numeric values at all and it was wrongly defined as type *number*.

**How to reproduce it (as minimally and precisely as possible)**:
Add one table with for example one *time* and two *number* colums.

Add 1,NaN,3,4 as values to the first numeric column and 
Add NaN,2,3,4 to the second numeric column.
Visualize the table in Graph Panel.
Observe that the second column is not shown.

Thank you!

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: Simpod Json Datasource 0.1.7
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Graph panel
- Others:

**Comment by dprokop** [comment]
@KrisztianKaszas are there any particular errors in browser's console?

**Comment by KrisztianKaszas** [comment]
Hi, there are no errors in Chrome console. 
![image](https://user-images.githubusercontent.com/48984814/75168663-9007e900-5727-11ea-939c-6c8c352525c2.png)
This screenshot shows the same data as timeseries in graph panel (top), as table in graph panel (middle) and as table in a table panel (bottom):
![image](https://user-images.githubusercontent.com/48984814/75169001-17555c80-5728-11ea-8f8e-9eb6cc9eeb45.png)

**Comment by torkelo** [comment]
sounds like a feature request, and a tricky one

**Comment by torkelo** [comment]
Think this can be fixed if the data source plugin your using updated to our new data format DataFrame and specified the field type to numeric
