### ISSUE TITLE
SQL data sources (postgres mysql mssql): New option to whitelist ip access , similar to data_source_proxy_whitelist

### ISSUE THREAD

**Issue by m-a-leclercq** [grafana/grafana#22392]
**What happened**: Pgsql datasource url/IP and port is not part of an already existing list of data_source_proxy_whitelist. Connection to the datasource still succeeds.

**What you expected to happen**: Datasource connection should fail with an error message stating that the datasource is not part of the whitelist

**How to reproduce it (as minimally and precisely as possible)**: 
* Start Grafana with a `data_source_proxy_whitelist` in `grafana.ini` with a placeholder URL/IP:port combination that does not resolve to anything. 
* Create a PGSQL Datasource to a real PGSQL instance running and try to connect with a valid user/password.
* Connection test succeeds.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 6.3.6
- Data source type & version: PGSQL 9 or10 
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Chrome
- Grafana plugins: None relevant to bug

I can confirm the property works correctly for an elasticsearch datasource and I do get an error message in the network tab in chrome stating that the url is not part of the whitelist.

**Comment by torkelo** [comment]
postgres data source does not go through our http data source proxy. 

For limiting this you will need to use some firewall settings.

**Comment by m-a-leclercq** [comment]
Thank you for your reply Torkelo, may I suggest a clarification in the [documentation](https://grafana.com/docs/grafana/latest/installation/configuration/#data-source-proxy-whitelist) to specify it is not currently available for these types of datasources?

Thank you.
