### ISSUE TITLE
Offset in Elasticsearch query doesn't work

### ISSUE THREAD

**Issue by KEVISONG** [grafana/grafana#22391]
**What happened**: I have two identical query with same elasticsearch datasource, one with offset of 1h and one without. Both query appeared identical on the graph.
![grafana-offset](https://user-images.githubusercontent.com/39701004/75139410-841c2700-5727-11ea-8dcf-89265f331d62.jpg)

**What you expected to happen**: The graph of the offset one should be shifted but it doesn't. How to make it work?

**How to reproduce it (as minimally and precisely as possible)**: shown in the picture

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.4.5
- Data source type & version: Elasticsearch v6
- OS Grafana is installed on: CentOS7
- User OS & Browser: Windows
- Grafana plugins: no
- Others: no

**Comment by dprokop** [comment]
Confirmed on master that it does not work too.

**Comment by torkelo** [comment]
Question what is sent to Elasticsearch? Can you use query inspector and check that the offset is sent correctly in the query?

**Comment by dprokop** [comment]
```
{
  "search_type":"query_then_fetch",
  "ignore_unavailable":true,
  "index":"",
  "max_concurrent_shard_requests":256
}{
  "size":0,
  "query":{
    "bool":{
      "filter":[
        {
          "range":{
            "@timestamp":{
              "gte":1582594991795,
              "lte":1582616591796,
              "format":"epoch_millis"
            }
          }
        },
        {
          "query_string":{
            "analyze_wildcard":true,
            "query":"*"
          }
        }
      ]
    }
  },
  "aggs":{
    "2":{
      "date_histogram":{
        "interval":"20s",
        "field":"@timestamp",
        "min_doc_count":0,
        "extended_bounds":{
          "min":1582594991795,
          "max":1582616591796
        },
        "format":"epoch_millis"
      },
      "aggs":{

      }
    }
  }
}{
  "search_type":"query_then_fetch",
  "ignore_unavailable":true,
  "index":"",
  "max_concurrent_shard_requests":256
}{
  "size":0,
  "query":{
    "bool":{
      "filter":[
        {
          "range":{
            "@timestamp":{
              "gte":1582594991795,
              "lte":1582616591796,
              "format":"epoch_millis"
            }
          }
        },
        {
          "query_string":{
            "analyze_wildcard":true,
            "query":"*"
          }
        }
      ]
    }
  },
  "aggs":{
    "2":{
      "date_histogram":{
        "interval":"20s",
        "field":"@timestamp",
        "min_doc_count":0,
        "extended_bounds":{
          "min":1582594991795,
          "max":1582616591796
        },
        "format":"epoch_millis",
        "offset":"+1h"
      },
      "aggs":{

      }
    }
  }
}```

**Comment by torkelo** [comment]
ok, looks like we send it correctly: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#search-aggregations-bucket-datehistogram-offset

**Comment by KEVISONG** [comment]
Hi Torkelo

I looked at the query inspector and got different results from elasticsearch when I turn on offset.

Below are the results for the two different queries. one with offset and one without. They are different but on grafana they are still overlapping one another. Could this be a front end bug?

![image](https://user-images.githubusercontent.com/39701004/75236837-5bfcf880-57f9-11ea-8950-99c4944af611.png)
![image](https://user-images.githubusercontent.com/39701004/75236870-67502400-57f9-11ea-890c-be97635efddf.png)

**Comment by torkelo** [comment]
Can you enable stacking? or click on the second series to see it does it look different? When I try +1h in offset I get the same result, the two responses are the same so they overlap on the graph

**Comment by KEVISONG** [comment]
@torkelo Yeah. I enabled stacking and they "appears" to be the same on the graph. But the query inspector shows two different response from elasticsearch which confuses me.

**Comment by marefr** [comment]
@KEVISONG if you read https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#search-aggregations-bucket-datehistogram-offset you'll understand that the offset can be useful in situations where you use a daily interval and Elasticsearch starts the interval at 00:00. With the offset setting you can change so that buckets instead are started earlier or later. But please note offset cannot be used for time shift capabilities per query if that's what you're looking for?

**Comment by KEVISONG** [comment]
Hi @marefr,
Understood. Offset only modifies the time of each bucket. Thanks for the link.

**Comment by nojakub** [comment]
@KEVISONG did you find any other solution for timeshifting selected query?

**Comment by KEVISONG** [comment]
> @KEVISONG did you find any other solution for timeshifting selected query?

@nojakub This plugin supports time shift https://github.com/GoshPosh/grafana-meta-queries

But it has some compatibility issue with Grafana v8

This is a good alternative: https://github.com/AutohomeCorp/autohome-compareQueries-datasource

**Comment by leoswing** [comment]
> > @kevisong did you find any other solution for timeshifting selected query?
> 
> @nojakub This plugin supports time shift https://github.com/GoshPosh/grafana-meta-queries
> 
> But it has some compatibility issue with Grafana v8
> 
> This is a good alternative: https://github.com/AutohomeCorp/autohome-compareQueries-datasource

But autohome-compareQueries-datasource has some compatibility issue with Grafana 10, how can we solve this issue?

**Comment by leoswing** [comment]
> @kevisong did you find any other solution for timeshifting selected query?

@nojakub @kevisong   Hi all, sorry to interrupt you.  You can use the latest plugin 2.0.1 with React framework support, and it's totally compatible with Grafana 11 and also with public sinature level, signed in Grafana plugins market. welcome to use the plugin and star ~

https://github.com/leoswing/comparequeries-datasource-rc

Details of plugin in Grafana can refer to https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource
