### ISSUE TITLE
No annotation popup is shown, only a small black box (InfluxDB)

### ISSUE THREAD

**Issue by johankcarlsson** [grafana/grafana#2239]
No annotation popup is shown, only a small black box down at the left side.
It has been the same for several 2.1-pre. 
Currently testing on 2.1.0-pre1, commit: v2.0.2+374-gec98f91, build date: 2015-06-23 20:09:17.

annotation definition:
select text from events WHERE $timeFilter AND type='release'

i have also tested with:
select * from events WHERE $timeFilter AND type='release'

DB query returns:
--data-urlencode "q=SELECT * FROM events WHERE type='release'"
{"results":[{"series":[{"name":"events","tags":{"type":"release"},"columns":["time","status","subject","text"],"values":[["2015-06-14T17:00:00Z","start","June release","deployed systems CIA, WIKI,PSFT, XXX"],["2015-06-14T23:00:00Z","stop","June release",""],["2015-06-26T12:02:19Z","start","INC12345","CIA main stopped due to out of memory"]]}]}]}

InfluxDB is version 0.9.0.
![image](https://cloud.githubusercontent.com/assets/13064341/8377087/7358b1e4-1c0e-11e5-9519-1bf2163c38f6.png)

**Comment by torkelo** [comment]
thanks for reporting this, fixed master, will push out new builds now

**Comment by johankcarlsson** [comment]
Thank you for very quick response and fix.
It now works as a charm.

Also very much thank you for a great application.
I really like the combination Grafana and InfluxDB (it also works very good with OpenTSDB).

**Comment by torkelo** [comment]
@johankcarlsson thanks
