### ISSUE TITLE
Graph: Show series in tooltip only not in graph

### ISSUE THREAD

**Issue by pzhuk** [grafana/grafana#22394]
I am using grafana Version 6.6.2, and so I have bunch of metrics coming from Postgres Datasource which has to be put on a graph plot

Datasource query briefly looks like
SELECT Time, Total, Critical, Major, Minior from ALERTS

My scope is to show only Total metric on the graph, while others (Critical, Major, Minor, etc) - should be shown only in a tooltip

I tried to do so by  "Series override" feature, using following options

1) Hidden Series = True  -- this will hide series from both graph and tooltip
2) Hidden Series = True  AND Hide in Tooltip = False  -- same result as in (1) , series are hidden in both graph and tooltip 

(2) looks like a bug to me, actually

So is there any way keep tooltip and hide series ?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
