### ISSUE TITLE
Specify font size for Graphite PNG renderer

### ISSUE THREAD

**Issue by Zirafarafa** [grafana/grafana#224]
I have a need to set the font size on labels and axes.  Is this possible?

**Comment by torkelo** [comment]
closing for lack of interest, Graphite PNG rendering is not used by many anymore

**Comment by DonRichie** [comment]
I just needed that to export some pictures in good resolution without getting a tiny legend :(

**Comment by bobemoe** [comment]
Looking for this too. Just starting to embed renders in our new app. If this isnt used much any more what is the alternative? We do use Grafana but that is no good for quick embedding of simple images. What are people using these days?
