### ISSUE TITLE
Explore Table sort numeric value

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#22403]
**What would you like to be added**:

When you're trying to visualize an histogram by it's count per bucket and you try to sort bucket `le` this happens:

![image](https://user-images.githubusercontent.com/1053421/75176681-9a63bc00-5702-11ea-9c09-463ec90eb98d.png)

I think they are sorted by string value but not numeric value which would be awesome here.

**Why is this needed**:

I this would help understand better histogram metrics.

**Comment by aocenas** [comment]
Still does not work for queries like `sum(rate(prometheus_tsdb_compaction_chunk_size_bytes_bucket[5m])) by (le)`. The `le` column which represents the bucket in the histogram seems to be still formatted as string and so the sort does not work but also it contains `+inf` text so this needs some considerations.

**Comment by NichUK** [comment]
This applies to more than just tables... Being able to sort a series graph numerically would be revolutionary since Prometheus doesn't support ordering data by labels.
