### ISSUE TITLE
Grafana UI: Enable using new form styles in Select-based components

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#22404]
**What would you like to be added**:
Add `useNewForms` prop to `DashboardPicker` and `TimeZonePicker` in order to enable using new form styles. 
**Why is this needed**:
In order to introduce new form styles without creating new components, a temporary solution is to add `useNewForms` prop to some components to enable toggling between old and new styles. This is particularly important for components based on `Select`, as there are a few places where old styles still need to be used and we don't want to create separate new components that would use new `Forms.Select`.

**Comment by torkelo** [comment]
I do not think we need it for TimeZonePicker as it's only used in the report edit view

**Comment by Clarity-89** [comment]
@torkelo My reasoning for adding this temporary prop was that the old and new components have some small incompatibilities as well as different styles. This means that the PR changing these components and the one in enterprise repo, where the components are used, would need to be synchronised. I guess it's not a big thing but I just wanted to make sure that the PR addressing this issue won't break anything until the forms are updated in other parts of the code.

Also I was thinking that at some point maybe it would make sense to replace `DashboardPicker` and `TimeZonePicker` with custom hooks, which would handle the logic, specific to the components, while leaving the UI details to the consuming component. 
The benefit of this approach is more flexibility when using these components in forms (easier to switch to controlled/uncontrolled, customise style/props) and avoiding extra code, which is mostly a generic select element with custom logic for displaying/fetching options. 
A disadvantage here is that those hooks will be able to be used only in class components.

**Comment by torkelo** [comment]
>This means that the PR changing these components and the one in enterprise repo, where the components are used, would need to be synchronised. 

That is not a big deal, that is common for enterprise / OSS changes 

> Also I was thinking that at some point maybe it would make sense to replace DashboardPicker and TimeZonePicker with custom hooks, which would handle the logic, specific to the components, while leaving the UI details to the consuming component.
The benefit of this approach is more flexibility when using these components in forms (easier to switch to controlled/uncontrolled, customise style/props) and avoiding extra code, which is mostly a generic select element with custom logic for displaying/fetching options.
A disadvantage here is that those hooks will be able to be used only in class components.

Not sure what your suggesting, these components already are high-level components that already re-use our low level form (select) components. We do not want the consumer to change the styling we want that to be consistent across Grafana and plugins usage.

**Comment by Clarity-89** [comment]
> We do not want the consumer to change the styling we want that to be consistent across Grafana and plugins usage.

Ok, yeah, it probably makes more sense then to keep these components as they are.
