### ISSUE TITLE
Explore link from panels do not have the right subpath prefix

### ISSUE THREAD

**Issue by olivierlemasle** [grafana/grafana#22405]
**What happened**:

When serving Grafana from a subpath (using server.root_url), the "Explore" link within a dashboard's panel (cf screenshot below) links to "/explore?..." and is not "relativized".

![image](https://user-images.githubusercontent.com/628140/75182863-8a1f0180-5741-11ea-80cf-4fa390ad9895.png)

**What you expected to happen**: the "Explore" link should be have a path starting with the Grafana subpath.

**How to reproduce it (as minimally and precisely as possible)**:

Set `server.root_url` to `%(protocol)s://%(domain)s/grafana/`. Grafana is then accessible on `/grafana`, and all internal links start by `/grafana`.
Then check the Explore link in any dashboard's panel.

**Anything else we need to know?**:

This worked perfectly in Grafana 6.6.1; the bug was introduced with 6.6.2.

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker image 6.6.1
- User OS & Browser: Fedora 31, Firefox 73
- Grafana plugins: N/A
- Others:

**Comment by dprokop** [comment]
This should be fixed by https://github.com/grafana/grafana/pull/21956. Can you please share you config?

**Comment by olivierlemasle** [comment]
Ah, yes, I did not find this issue and PR.
I confirm it works on master.
