### ISSUE TITLE
Trying to render es logs in LogsPanel yields an error

### ISSUE THREAD

**Issue by Docjones** [grafana/grafana#22409]
**What happened**:
While trying to render log entries from my es instance, i get an Error "e.ToLowerCase is not a function"

**What you expected to happen**:
Show me them logs!

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: es 6.6.1 (funny, same as grafana!)
- OS Grafana is installed on: docker container on ubuntu
- User OS & Browser: win10 & firefox
- Grafana plugins: various

Screenshot:
![grafik](https://user-images.githubusercontent.com/561429/75221202-8b801680-57a1-11ea-8ef4-c3442fa9e0a0.png)

Edit: found the StackTrace in the Firefox-Console (Don't know if that helps...):
![grafik](https://user-images.githubusercontent.com/561429/75222390-71940300-57a4-11ea-9a62-42bf8010802e.png)

**Comment by torkelo** [comment]
Can you expand the response part of the query inspector so we can see exactly what elasticsearch is returning?

**Comment by Docjones** [comment]
Of course, here is the copy:

![grafik](https://user-images.githubusercontent.com/561429/75226130-1fef7680-57ac-11ea-84bb-bd1c2bc363a5.png)

Attached the complete extracted answer as well:
[exctract.txt](https://github.com/grafana/grafana/files/4248702/exctract.txt)

**Comment by canab** [comment]
The same error in Explore->logs
v6.6.2 (3fa63cfc34)

**Comment by Docjones** [comment]
@canab - renaming the level field name worked! thanks :)

**Comment by ivanahuckova** [comment]
@Docjones @canab  The problem happens [here](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/utils/logs.ts#L41). We expect level to be a string, but in your case it is number `"level": 6` therefore it can't use .toLowerCase() and it throws an error. Therefore renaming of the field level solved this issue.
