### ISSUE TITLE
Playlist is not working for current master?

### ISSUE THREAD

**Issue by deniszh** [grafana/grafana#2240]
I have a problem similar to https://github.com/grafana/grafana/issues/1589
Please see image below: 
![screen shot 2015-06-26 at 16 39 53](https://cloud.githubusercontent.com/assets/1227222/8379699/029e3e88-1c22-11e5-867e-11ea754d8ca2.png)
Search request return some results, but playlist panel still saying "No dashboard found" and I get "dash is undefined" when press Start button. It's in latest Firefox release.
Tried also Chrome - exactly same behaviour.

**Comment by torkelo** [comment]
will investigate

**Comment by torkelo** [comment]
thanks for reporting this, fixed now
