### ISSUE TITLE
Feature Request:  Single Stat as Pie Chart

### ISSUE THREAD

**Issue by andrewmeyer** [grafana/grafana#2241]
I have a use case where, instead of a percentage people would like to see a visual representation of this percentage.  This could take the form of a pie chart representing the percentage, or some other form of ring that corresponds to one value as a percentage of another.

This would be very useful for depicting a current disk usage, for example.  It could also be used for any metric that has an expected maximum value.

**Comment by torkelo** [comment]
in what way is a pie chart better than a percentage number ?? :) 

https://www.stevefenton.co.uk/Content/Pie-Charts-Are-Bad/

**Comment by andrewmeyer** [comment]
Personally I like the percentage number, but others want a visual, graphical representation.  It would be a nice option, but I agree, percentages work.  I suppose that I shouldn't have said Pie Chart either, but rather a circular graph which visually shows percentage.   What I envisioned was the percentage with the graph behind it, not unlike how the Spark Lines are displayed now.

**Comment by torkelo** [comment]
What I would like is a vertical bar chart like thing that can represent a percentage. 

Sort of like this:
![image](https://cloud.githubusercontent.com/assets/10999/8382468/091d24b6-1c33-11e5-865b-9fa254a95716.png)

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/129
