### ISSUE TITLE
String from MySQL source not shown in Singlestat panel if value is not numerical

### ISSUE THREAD

**Issue by victorclaessen** [grafana/grafana#22417]
**What happened**:
If I select a string from MySQL as value to show in a Singlestat panel, then grafana shows "No data". 

**What you expected to happen**:
I expect that grafana shows the string value in the Singlestat panel.

**How to reproduce it (as minimally and precisely as possible)**:
Make a singlestat panel (format as table) with a MySQL source, using the following SQL query:
`SELECT "string" as value` -> Grafana will show **No data** in the panel. 

**Anything else we need to know?**:
If the value is of type string but numerical in contents, then Grafana will show the numerical string. Example SQL:
`SELECT "1.2" as value` -> Grafana will show **1.2** in the panel.

**Environment**:
- Grafana version: v6.6.2 (3fa63cfc34)
- Data source type & version: MariaDB 5.5.62
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 10, Firefox 73
- Grafana plugins: Stat / Singlestat Panel - Native Plugin
- Others:

**Comment by victorclaessen** [comment]
Funny observation, if I use display options "Show: Calculation, Calc: Last (not null)", and the following MySQL query, it works!!!

`SELECT 1 UNION ALL SELECT "string"` -> shows **string**
`SELECT "string"` -> shows **No data**

**Comment by dprokop** [comment]
Well, single stat and stat panels are meant to display numeric values, hence I'm not sure why it should display strings per se. There's definitely a difference in stat vs single stat - stat handles numeric strings correctly, while single stat does not. Same with the calculations, those should treat numeric strings as number IMO, sam as Last/First calculation does

**Comment by victorclaessen** [comment]
Something similar [has been asked before](https://community.grafana.com/t/grafana-single-stat-displaying-just-a-string/10238), so I assumed it was possible. If the type of the column is string, and you can't parse the value numerically, why not just display the string value?

**Comment by torkelo** [comment]
Closing this, opened a new issue to track string support in the new Stat panel: https://github.com/grafana/grafana/issues/23880
