### ISSUE TITLE
grafana/ui: Make entire Forms.Label clickable

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#22419]
**What happened**:
If I want to use the htmlFor attribute on the Forms.Label component and also have a styling with some padding (let's say the styles of a button). This applies the styling to the outer div of the Label component. However this means that only the text in what now looks like a button is clickable.

**What you expected to happen**:
Entire element to be clickable

**How to reproduce it (as minimally and precisely as possible)**:
```
<input type="file" id="upload" />
<Forms.Label
  htmlFor="upload"
  className={Forms.getFormStyles(theme, { variant: 'primary', invalid: false, size: 'md' }).button.button}
>
  Click the input
</Forms.Label>
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version: n/a
- OS Grafana is installed on:
- User OS & Browser: ubuntu linux 18.04 and Chrome v. 80.0.3987.116
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Hmm, that's interesting. The connection between input and label is covered but Forms.Field component. I think you can achieve the same thing by styling the file upload input with this approach https://css-tricks.com/snippets/css/custom-file-input-styling-webkitblink/ and wrapping it in the Forms.Field component.

```tsx
<Forms.Field>
  <StyledFileUploadFIeld id="XXX" />
</Forms.Field>
```
