### ISSUE TITLE
Cleanup the icons.scss 

### ISSUE THREAD

**Issue by jackyq2015** [grafana/grafana#22426]
**What happened**:
[icons.scss ](https://github.com/grafana/grafana/blob/5b40b267446ca7d14da0b3292d9e2d1a79a70d3d/public/sass/base/_icons.scss) include few unused styles. some of them cause issue where they override the style from the plugin components. In my case, it is ".mini".

**What you expected to happen**:
Remove the unused styles or name them in a unique way to avoid name space clash. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a plugin which use antd and create a table. The pagination picks the "mini" from grafana and mess up the layout 

**Anything else we need to know?**:
NA

**Environment**:
- Grafana version: Current master
- Data source type & version: NA
- OS Grafana is installed on: Ubuntu 
- User OS & Browser: Chrome
- Grafana plugins: Custom
- Others: NA

**Comment by ryantxu** [comment]
Interesting - is this really the only thing breaking for antd?  I tried a while ago and it looked like namespacing all of antd was the only option... But I never finished.  If you have it almost working (except for the mini icon) can you post somewhere?

**Comment by dprokop** [comment]
@jackyq2015 do you mind opening a PR with removing unused code?

**Comment by jackyq2015** [comment]
@ryantxu For some reason, mini is used in antd but it is not defined somehow(also an issue for them). But it incidentally picks up the style from grafana. I removed the mini manually and the table works well.

@dprokop I can put a fix on this. But need some time to figure out which ones are used and which ones are not. Do you know if there is any tool or way to do it?

**Comment by ryantxu** [comment]
@jackyq2015 -- you may just need trial and error to find the issues

Do you have a plugin repo we can look at that uses antd?  I would love to see your approach

**Comment by jackyq2015** [comment]
@ryantxu Finally the repo was pushed.
https://github.com/jackyq2015/grafana-antd

there is some garbage in the package.json. But I prefer to leave it as is for your research.  I also updated the readme. I think it's combination of the package-lock.json and tsconfig.json make the difference.

**Comment by axelavargas** [comment]
Hello 😄 , I am closing this issue because it seems the issue was fixed and merged ([PR that contained the Fix](https://github.com/grafana/grafana/pull/22458))
