### ISSUE TITLE
Migration guide for plugins

### ISSUE THREAD

**Issue by SanketCTSI** [grafana/grafana#22427]
Hi Team ,

I am reading the document for the developing the graphan plugin but I could see the documentation is not proper meaning that no detail information is provided . can you please add some more documentation on how the folder structure, which are files important , what each file does ..etc then how to build the plugin , what are the classes required .. and if possible with good examples .. I still didn't get the starting point after reading this documentation.

Thanks
Sanket

**Comment by SanketCTSI** [comment]
Hi @dprokop 

can you please help me on the react documentation 

Thanks
Sanket

**Comment by SanketCTSI** [comment]
@dprokop 

I need to migrate my current neo4j datasource plugin from angularjs to reactjs as there is no documentation available can you please help me out in this .

Thanks
Sanket

**Comment by dprokop** [comment]
@SanketCTSI Thanks for reporting this issue. We currently don't have a migration guide for AngularJS plugins. As a starting point I suggest taking a look at grafana-toolkit https://www.npmjs.com/package/@grafana/toolkit) and these tutorials that our docs team is working on (https://storage.googleapis.com/grafana-tutorials/index.html). These tutorials are work in progress but hope they will be somehow helpful.

Also, please feel free to reach out to me on our public Slack for help.

**Comment by SanketCTSI** [comment]
Thanks Dominik for the quick response ,

can you please give me your slack id.

Thanks 
Sanket

**Comment by SanketCTSI** [comment]
@dprokop ,

Please message me your slack id so that i can reach you

**Comment by Chris-Tophski** [comment]
@SanketCTSI The public Slack seems to be found at the main page (https://github.com/grafana/grafana) at the bottom under "Get involved" (I don't have Slack, so I don't really know if this helps).

Regarding your Neo4j plugin: Are you going to publish it? I'd be glad to help you with this, as I'm looking for a Neo4j plugin since my first contact with Grafana and meanwhile I'm about to enter plugin development in order to finally get an opportunity to read Neo4j data. I must admit, I'm not in too deep in Grafana plugin development, yet, but I have experience in a lot of programming languages and especially in Neo4j. So, if you're interested, let me know.

**Comment by oddlittlebird** [comment]
@marcusolsson, please review

**Comment by marcusolsson** [comment]
Hi @SanketCTSI, great to hear you're looking to convert your plugin to React! Unfortunately, like @dprokop mentioned, there's no migration guide yet. Although there's no officially recommended way to migrate, many seem to follow the tutorials and then copy the old code over to the new plugin.

If you'd like to request a migration guide, please submit another issue, e.g. "Add plugin migration guide", explaining what you'd like to see in such a guide.

**Comment by marcusolsson** [comment]
Actually, I'll go ahead and rename this issue instead, to keep the dicussion.

**Comment by dprokop** [comment]
Actually having a comprehensive migration guide is not something we will probably have in the near future. There is no 1-1 way to migrate the plugin from Angular to React. What we could to though is to drop a migration guide on:
1. The API update (from Angular's module.ts panel and controller exports to `PanelPlugin`, same with datasource plugins)
2. Panel editors migration example (basically a tutorial on using Declarative Options API vs the Angular's `addEditorTab`)

@SanketCTSI would such guides be useful to you?

**Comment by yesoreyeram** [comment]
Also it will be helpful if helpful if we provide migration guide from legacy data formats (timeseries, table) to dataframe.
