### ISSUE TITLE
Variable Refresh on Dashboard Load Causes Unexpected Behaviour

### ISSUE THREAD

**Issue by dp106** [grafana/grafana#22420]
**What happened**:
I have two dashboards. Main dashboard has a variable that filters its results.  One of the cells has a generated link that passes through the variable and the cell value to a secondary dashboard.  When clicking the link it has unexpected results.  The seconday dashboard may go in to what looks like a loop constantly reloading. It often displays one or more incorrect variables. Clicking the back button often shows the secondary dashboard with the correct variables before having to click again to show the main dashboard.

**What you expected to happen**:
The main dashboard link should open the secondary dashboard filtered by the passed through variable and cell value.

**How to reproduce it (as minimally and precisely as possible)**:
Create two dashboards.  Main dashboard should have a variable that filters its results. One of the cells should have a generated URL that links to a secondary dashboard passing through the variable and cell value.  A second dashboard should be created that is filtered by these two values.

**Anything else we need to know?**:
On further investigation I believe this behaviour is being caused by the option to refresh the variable when the dashboard loads.  It seems that it is refreshing the variable after the dashboard has been loaded.  So it effectively loads the dashboard with the variables that have been passed through and then updates them causing the dashboard to reload and lose the variables passed through. (But not always!). This probably explains how it sometimes gets in to an endless loop.

If you load the dashboard directly rather than using a link to it there is no such behaviour.

While I can turn off the variable refresh on dashboard load this is not acceptable as the variable will not pick up any new values.

*The variables are SQL queries to a database hence their values will change over time.

**Environment**:
- Grafana version: 6.6.1 and 6.6.2 both display same behaviour. 6.5.3 working ok
- Data source type & version: Microsoft SQL Server
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Pie chart
- Others:

**Comment by dprokop** [comment]
@dp106 thanks for reporting this. It looks similar as https://github.com/grafana/grafana/issues/21895

**Comment by dp106** [comment]
Hi thanks for that yes it does look similar. Sorry I tried looking to see if it had been raised but couldn't find anything. The one thing I would say is it seems like it's been assumed this is only if the two dashboards have different queries however in my case they are the same so it still seems like a big to me
