### ISSUE TITLE
Playlists authorizing permissions are not documented

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#22423]
**What would you like to be added**:

Documentation that explains what permissions are required to allow someone to create a playlist.

**Why is this needed**:

I'm looking at this page https://grafana.com/docs/grafana/latest/permissions/organization_roles/ (and the other permissions-related pages in the side bar). None of these mention playlists. My Grafana users all have viewer permissions, get added to a team and the team has admin permissions on that team's assigned folder. None of my users can create playlists. Without documentation that describes the permissions required to do so, I have no idea how to work around this. 

Please update the docs to explain how permissions affect playlist creation.

**Comment by davidnewhall** [comment]
I'd be tickled pink if someone could just tell me here, what is required to create Playlists. Org Editor? Does Org Editor allow the creation of notification channels? Thanks!

**Comment by davidnewhall** [comment]
Same question for `Explorer`. What permissions grant access? Viewer + Folder Admin don't cut it.

**Comment by oddlittlebird** [comment]
@marefr, who can answer this? I would like to add this to the docs.

**Comment by marefr** [comment]
@oddlittlebird 
- at least editor org role is needed for create, update, delete playlists. 
- at least editor org role is needed for create, update, delete notification channels.
- at least editor org role is needed to access explore unless [viewers_can_edit](https://grafana.com/docs/grafana/latest/administration/configuration/#viewers-can-edit) is enabled then viewer org role is enough.

**Comment by davidnewhall** [comment]
- This response makes me want to ask for a new feature to allow granular permissions and control of these features. 
- It seems like a viewer should be able to use Explore since that feature doesn't actually edit anything.

**Comment by oddlittlebird** [comment]
What we really need is a table of some sort to indicate what each role can do.
