### ISSUE TITLE
Docs: Dashboards / Overview page 404

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#22431]
The dashboards overview page (first under features / dashboard) in the menu is not found. Maybe a problem with the menu.yaml file. 

https://grafana.com/docs/grafana/latest/features/dashboard/dashboards/

I remember it working locally or on docs site (not sure) few days ago when I worked on the stat panel docs. I also remember this page was super outdated (in terms of images and text)

**Comment by torkelo** [comment]
@oddlittlebird hi, when you have time can you investigate why this page / link is not working? my guess is a problem with menu.yaml

**Comment by oddlittlebird** [comment]
This will be fixed by PR #22422

**Comment by torkelo** [comment]
great!
