### ISSUE TITLE
Dashboard: template variable save option is not respected

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#22432]
**What happened**:
If you have a dashboard with template variables. Go into settings and do some changes to them and saves the dashboard. Regardless of the value selected in the "save current variables" the template variables will be saved. 

![screen](http://i.imgur.com/rvmsnua.png)

**What you expected to happen**:
The template variabels should only be saved when you have enabled the "save current variables".

**How to reproduce it (as minimally and precisely as possible)**:
1. Open/create a dashboard with template variables.
1. Save the dashboard with the "save current variables" enabled.
1. Change any of the template variable values.
1. Save the dashboard with the "save current variables" disabled.

**Environment**:
- Grafana version: 6.7.0-pre
- Data source type & version: n/a
- OS Grafana is installed on: OSX
- User OS & Browser: OSX / Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by dprokop** [comment]
Similar to #21131

**Comment by dprokop** [comment]
@mckn just tested this agains master and it seems that we it works as it should now :)
