### ISSUE TITLE
Docs: investigate if we can use compile instead of build when generating reference sdk docs.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#22433]
**What would you like to be added**:
Currently when we are generating the packages api docs we are using the `yarn packages:build` command to build all the packages. The build command does a couple of steps specified here:

https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/cli/tasks/package.build.ts#L93

All of those steps might be unnecessary since we only need the `*.d.ts` files to generate the actual documentation. So investigate if it is enough to only compile the packages and then generate the docs. This will speed up the build a lot since we will not do the rollup for example.

**Why is this needed**:
To make the packages docs run faster, less error prone and simplify the flow a bit.

**Comment by hugohaggmark** [comment]
Is this issue still actual @mckn and if so do we still need the __needs investigation__ label?

**Comment by mckn** [comment]
hmm, yes - I think we can improve the docs generation by just doing the compile but I'm not sure if it has any other side effects.

**Comment by hugohaggmark** [comment]
So do I keep the needs investigation label that is mainly used for bugs?

**Comment by mckn** [comment]
Aha, I guess we then can remove that one 👍

**Comment by hugohaggmark** [comment]
Thank you @mckn

**Comment by oddlittlebird** [comment]
@mckn, did you address this issue when you made that docs compilation change a while back?

**Comment by mckn** [comment]
> @mckn, did you address this issue when you made that docs compilation change a while back?

hmm, no - but we are not building the docs prior to generating them but instead we are using the existing build in the CI pipeline so I think we can close this one. Thanks for reminding me about this issue.
