### ISSUE TITLE
support template variables  in datasource select

### ISSUE THREAD

**Issue by cocotyty** [grafana/grafana#22443]
**What would you like to be added**:
![深度截图_选择区域_20200226230206](https://user-images.githubusercontent.com/2241753/75357436-56cca600-58ec-11ea-80cf-407de5ac9988.png)
Support template datasource inputs like:
prom-${idc}
graphite-${idc}
**Why is this needed**:
 Panels in one dashboard use different type datasources.

**Comment by cocotyty** [comment]
My company uses a multi-IDC architecture. Each IDC has two time series data systems, Promethues and Graphite.
The Dashboard we configured needs to switch IDCs through variables to view the performance indicators of each application in different IDCs.

**Comment by ryantxu** [comment]
There is already datasource template variables:
![image](https://user-images.githubusercontent.com/705951/75403305-2a993100-58bc-11ea-8254-150eae4bbbfb.png)

that likely gets you what you need.  I don't see how you can switch between different datasource types (prometheus & graphite) since they would need different queries too!

**Comment by cocotyty** [comment]
> There is already datasource template variables:
> ![image](https://user-images.githubusercontent.com/705951/75403305-2a993100-58bc-11ea-8254-150eae4bbbfb.png)
> 
> that likely gets you what you need. I don't see how you can switch between different datasource types (prometheus & graphite) since they would need different queries too!

In fact, we don't switch datasource types on one query.
It is possible for multiple panels in one dashboard to use multiple different datasource types. 
This method in your screenshot does not meet this need.
