### ISSUE TITLE
Invalid CloudWatch query for partial match

### ISSUE THREAD

**Issue by inikolaev** [grafana/grafana#22440]
**What happened**:
I'm trying to create a query with partial match and Grafana generates incorrect CloudWatch query when **Exact Match** is disabled.

**What you expected to happen**:
Correct CloudWatch query generated.

**How to reproduce it (as minimally and precisely as possible)**:

I want to collect metrics from all database instances which have a common substring in their identifiers. Grafana generates the following query when I have **Exact Match** disabled (note the double quotes around `some-db`):

```
REMOVE_EMPTY(SEARCH('Namespace="AWS/RDS" MetricName="CPUUtilization" "DBInstanceIdentifier"="some-db"', 'Average', 60))
```

According to [documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html#search-expression-partial-match) double quotes around search terms force exact match:

> You can define a search to find only exact matches of your search term by using double quotes around the part of the search term that requires an exact match. These double-quotes are enclosed in the single-quotes used around the entire search term.

After that I changed query by removing double quotes around `some-db` and query started working:

```
REMOVE_EMPTY(SEARCH('Namespace="AWS/RDS" MetricName="CPUUtilization" "DBInstanceIdentifier"=some-db', 'Maximum', 60))
```

Let me know if I can provide any additional details if needed.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: CloudWatch
- User OS & Browser: macOS 10.15.3, Safari 13.0.5

**Comment by sunker** [comment]
@inikolaev, the `MatchExact` toggle in Grafana should not be confused with the [partial match](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html#search-expression-partial-match) feature in ClouWatch. What MatchExact in Grafana does is to only show metrics that exactly match all defined dimension names - it does not have to do with substring matches. 

The only way to achieve this in Grafana would be to use the expression field and define the whole expression there using a dimension value without double quotes as you suggested.

**Comment by inikolaev** [comment]
That is not really obvious from UI that they are not related, but ok.

**Comment by sunker** [comment]
I kind of agree with you on that. Might need to think of a better name...

**Comment by hastarin** [comment]
I was looking to lodge a similar ticket before I found this one!

It would be great to have the ability to do this without resorting to using the Expression.

At the least noting something in the documentation about how to perform a partial match would be handy.

In my case it was simply wanting to filter Lambda metrics which I would have thought would be a pretty common use case.

`REMOVE_EMPTY(SEARCH('Namespace="AWS/Lambda" MetricName="Duration" FunctionName=prod-api', 'Average', 60))`
