### ISSUE TITLE
Cannot deselect in Multi-Value Query Variable

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/grafana#22442]
**What happened**:
Deselect in Multi-Value Query variable does not deselect. 
- When I click on selected(1), the selection will be cleared, however, after losing focus from the control, it automatically selects the first available value in the list.
- When I click on any selected item again, to deselect it, the control closes and changes the selection to the first available item in the list.

**What you expected to happen**:
I expect that I can manually deselect all selected items, or use the clear selection (selected(1)) entry, to clear all selected items.
**How to reproduce it (as minimally and precisely as possible)**:
Add Query Variable with a JSON datasource (simpod), select any item and try to deselect that item or use selected(1).
1: click on selected(1)
![image](https://user-images.githubusercontent.com/48984814/75356422-3da60400-58b0-11ea-8f19-715b3c329ae5.png)
2: note that the selection disappears
![image](https://user-images.githubusercontent.com/48984814/75356532-5c0bff80-58b0-11ea-8de5-7f27da7412f8.png)
3: Click anywhere else and note that the list selects the first available item:
![image](https://user-images.githubusercontent.com/48984814/75356595-73e38380-58b0-11ea-8ede-9ba05b95da74.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: JSON datasource (simpod)
- OS Grafana is installed on: Windwos 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Hi! 

Sadly variables do not support "empty / no" values, https://github.com/grafana/grafana/issues/5970
