### ISSUE TITLE
versions_to_keep configuration don't work.

### ISSUE THREAD

**Issue by pwSteve** [grafana/grafana#22444]
**What happened**:
I configured "versions_to_keep" in the config file to f.ex. 5, but in the database i can see more than this 5 versions.

**What you expected to happen**:
I want that Grafana keep only the last 5 Versions of each Dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Very simple to reproduce, configure a little number as "versions_to_keep" in the config file, restart Grafana, create a new dashboard, save the dashboard with little changes and watch the entries of the database. 

**Environment**:
- Grafana version: 6.6.1
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Others: Grafana run as Windows Service

**Comment by aknuds1** [comment]
Please rewrite the issue using our issue template - thanks!

**Comment by pwSteve** [comment]
@aknuds1 I used the bug template, i deleted only the headings from the template, but i can rewrite it with the headings.

**Comment by aknuds1** [comment]
Please keep the headings, yeah.

**Comment by pwSteve** [comment]
@aknuds1 I added now the headings.

**Comment by torkelo** [comment]
you have to wait 10 minutes, the clean up is only executed every 10min.

If it still to many versions please re-open
