### ISSUE TITLE
Global Alias Overrides

### ISSUE THREAD

**Issue by Jhors2** [grafana/grafana#2245]
Having a global alias override would be very helpful now that color selections are possible.

Ideally I would like all servers matching a hostname regex to have the same color on every single potential graph I could create in any dashboard.  Obviously you also want a specific override that you can do on a per graph basis.  The graph specific regex override should override a global override.

**Comment by ecables** [comment]
+1

Managing overrides for every graph is not ideal.

**Comment by languitar** [comment]
:+1:

**Comment by ecables** [comment]
Can I +1 something twice? :-) 

The goal is to have certain locations, services, servers, etc., identified by a regex pattern, always be a certain color -- across all dashboards and graphs. Having to go through each graph, in every dashboard, is very time consuming. A global override for regex color overrides would be extremely useful.

example:
```
"globalOverrides": [
{
  "alias": "/.*site01.*/",
  "color": "#8F005C"
},
{
  "alias": "/.*site02.*/",
  "color": "#8F113E"
},
{
  "alias": "/.*site03.*/",
  "color": "#8F224D"
}
]
```

**Comment by mtanda** [comment]
+1

**Comment by vonox7** [comment]
+1

**Comment by vonox7** [comment]
@IevaVasiljeva: Are you sure that https://github.com/grafana/grafana/pull/41561 fixes in fact this issue and not the issue with id 2245 on the grafana-enterprise repo? I have no access to the enterprise repo, but based on the change in https://github.com/grafana/grafana/pull/41561 it seems that "allow configuring global alias colors" and "Allow using targetOrgId parameter to set organisation ID for a request" seems to be a pretty different use-case.

**Comment by IevaVasiljeva** [comment]
> @IevaVasiljeva: Are you sure that #41561 fixes in fact this issue and not the linked issue with id 2245 on the grafana-enterprise repo? I have no access to the enterprise repo, but based on the change in #41561 it seems that "allow configuring global alias colors" and "Allow using targetOrgId parameter to set organisation ID for a request" seems to be a pretty different use-case.

Oh, apologies. You are right, I accidentally linked the wrong issue from the PR. Thanks for pointing it out!

**Comment by woutkonings** [comment]
Is there any update on this issue?

**Comment by ewoolsey** [comment]
Bump!

**Comment by mdvictor** [comment]
This feature request has been open for a long time with not a lot of received upvotes or comments, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!
