### ISSUE TITLE
Workflow or process or procedure support for dashboards of business data 

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#22454]
**What would you like to be added**:
Similar with drawer.io, and processon or simply visio, make it possible for users to draw, through click and drag, like quiet easily to add a panel, a business flow having a varieties of data chosen and shown generated by customized SQL or query langues Grafana supports. Not background image or svg that requires code.
**Why is this needed**:
Users no longer need to code, cut the cost of making a process flow. Grafana has data(datasources), then also show it by a business flow.

**Comment by dprokop** [comment]
@evandeng2009 thanks for opening this issue! This is an interesting idea that I think @ryantxu and @torkelo might have some more thoughts on. 

Can you also elaborate more what is your use case that you need such feature?

**Comment by evandeng2009** [comment]
@dprokop,  thanks for quick response. Well, this feature is so valuable that we can get a birds-eye view of business in real time as Grafana has direct access to kinds of Datasources, this is what I called data. The business flow, consists of many nodes defined by user by click and drag and get them connected with arrows, which present the entire process of business activities in high level. For instance, Amazon is celebrating Black Friday, marketing manager or even CFO wanna see how many orders, so far, have been submitted and how those orders are processed in each step(nodes as above) like warehouse, preparing, configuration, distribution and package arrival. 

I earlier also did some research like GoJS or SVG but they are not the right choices as not friendly coz of coding. Attention should be paid on business and given to business colleague to customize their own flows.

**Comment by evandeng2009** [comment]
@dprokop @aknuds1 
What's the status please?  I also have a picture to demonstrate the idea above. 
![pic](https://user-images.githubusercontent.com/11970778/88662252-47a48b00-d10c-11ea-8115-0d3e050828dc.PNG)

**Comment by evandeng2009** [comment]
Guess I've found one like that. 
https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel
[https://raw.githubusercontent.com/NovatecConsulting/novatec-service-dependency-graph-panel](https://raw.githubusercontent.com/NovatecConsulting/novatec-service-dependency-graph-panel/master/src/img/screenshot-showcase.png)

**Comment by jessover9000** [comment]
Hello @evandeng2009 , did this panel solve your issue, were you mainly looking for a data flow style visualisation?

**Comment by evandeng2009** [comment]
Hi @jessover9000 , data flow, yes. The panel above seems ok for me, so far.

**Comment by melgawad** [comment]
@evandeng2009 Hello in this case is there any update to archives this flows?
