### ISSUE TITLE
Encrypt datasource password instead of plain text

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#22452]
**What would you like to be added**:
Passwords of datasources are encrypt in database, rather than plain text right now. Further more provide an API for encryption for better integration.
**Why is this needed**:
Security

**Comment by dprokop** [comment]
@evandeng2009 you can encrypt datasource passwords with grafana-cli. Please take a look here https://grafana.com/docs/grafana/latest/administration/cli/#migrate-data-and-encrypt-passwords
