### ISSUE TITLE
Loki logs panel should support resolution

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#22456]
**What would you like to be added**:

When creating a histogram graph panel with Loki I want to be able to select a better resolution or step.

![image](https://user-images.githubusercontent.com/1053421/75404670-3d6e2e80-58d9-11ea-9320-990bb43978b8.png)

Loki support this but the config is only visible when using Prometheus datasource.

**Why is this needed**:

Without being able to tweak the step each bar looks really tiny and almost invisible. While when I can change the resolution and step using Prometheus datasource with Loki it looks better.

![image](https://user-images.githubusercontent.com/1053421/75404772-8b833200-58d9-11ea-9436-d08e689793fb.png)

**Comment by olbo98** [comment]
Do you only want the ability to specify the minimum step or something in likeness to this PR #36125?
