### ISSUE TITLE
HTTP Dashboard API outdated or does not apply to grafana.com

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#22457]
**What happened**:
I want to upload a dashboard to grafana.com using some API. I tried to follow the docs at https://grafana.com/docs/grafana/latest/http_api/dashboard/#dashboard-api, but I am fairly sure they are either outdated or do not apply to grafana.com, as none of the requests behave as described.

References around the web are also stale/invalid: https://community.grafana.com/t/is-there-an-equivalent-http-api-to-import-a-dashboard-from-grafana-com/9581/3

https://grafana.com/docs/grafana/latest/tutorials/api_org_token_howto/ is not relevant as it only works for internal instances.

I ended up having to go through the UI, use firefox network inspect and parse out the API calls, which was quite a flustering experience.

This is what I ended up with:
```
# Create a new dashboard
curl -H "Authorization: ..." -XPOST -H "Accept: application/json" -F 'json=@dashboard.json' https://grafana.com/api/dashboards -v
# Update an existing dashboard
curl -H "Authorization: ..." -XPOST -H "Accept: application/json" -F 'json=@dashboard.json' https://grafana.com/api/dashboards/DASHBOARD_ID/revisions -v
```

But I am not quite sure if this is the right way to do this

**What you expected to happen**: 
Some documentation on how to do this would be useful. 

**Anything else we need to know?**:
The context here is we want to release our dashboards as part of our existing CI driven release process

**Comment by bergquist** [comment]
The https://grafana.com/docs/grafana/latest/http_api/dashboard/#dashboard-api api is for grafana instances. 

we currently don't support uploading dashboards to grafana.com using the API. (you can ofc do this by emulating a browser, but that's not something we support)

**Comment by howardjohn** [comment]
It would be very useful to have an API. We want to release dashboards as part of our CI pipeline. I had to reverse engineer from the browser which was not fun
