### ISSUE TITLE
2.1.0-pre1 Template Dashboard Slowness

### ISSUE THREAD

**Issue by Jhors2** [grafana/grafana#2246]
I am currently testing 2.1.0-pre1.  In previous grafana versions I had instances where a single template variable query could return 20,000 + results from the database.  This didn't really equate to a performance impact in the browser.  Since working with 2.1.0 it appears that any template variable displayed on a dashboard, if it has greater than 5,000 entries all aspects of the dashboard become prohibitively slow.

Please let me know if you need anything to recreate the issue.

**Comment by torkelo** [comment]
Not a great solution for this, but might be ok. The dropdown will only render the top 1000 results, you can still search through all values.
