### ISSUE TITLE
on Grafana version 6.5.3: "Login Failed Invalid redirect_to cookie value"

### ISSUE THREAD

**Issue by VinayDanda** [grafana/grafana#22467]
On Grafana 6.5.3 version, 
1. Successful Login to the grafana instance.
2. Opening another tab & try the same url, then the page is not opened and shows below message on login screen:
"Login Failed Invalid redirect_to cookie value"

Attached the screenshot for reference.
![Capture](https://user-images.githubusercontent.com/33858700/75442483-985d5f80-5985-11ea-826a-7604afdde589.JPG)

Seeing this issue only in this version, didn't face in earlier versions till 6.2.0

**Comment by bergquist** [comment]
Should be fixed in 6.7 beta by https://github.com/grafana/grafana/pull/22677
