### ISSUE TITLE
cloudwatch credentials cache not invalidated when the datasource config is updated

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#22468]
**What happened**:
If a cloudwatch datasource is configured with valid credentials, then you update the config to use authType=arn , datasource requests will continue to use cached credentials without assuming the specified ARN.

**What you expected to happen**:
When updating a datasource config cached credentials should be invalidated.

**Anything else we need to know?**:
The issue is that cloudwatch credentials are cached for 5minutes: https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/credentials.go#L86
When fetching items from the cache, no consideration is made for whether the DS config has changed since the credentials were cached.

**Comment by woodsaj** [comment]
There are 2 issues leading to this bug.

1) when the DS config is updated from authType=ARN to authType=credentials , the jsonData.assumeRoleArn is not cleared.
2) the cache key used for credentials only uses the accessKey and AssumeRoleArn fields from the jsonData and the "database" field from the datasource model.

So if you create a DS and configure it to use ARN the jsonData is set to
```
assumeRoleArn: "arn:aws:iam:XXXXX"
authType: "arn"
```
leading to the cache key to be `::arn:aws:iam:XXXXX`

if you change the DS config to use Credentials file, the jsondata becomes
```
assumeRoleArn: "arn:aws:iam:XXXXX"
authType: "credentials"
```
leading to the same cacheKey.

We should fix both issues.  ie
1) in the frontend, when changing the authType from ARN to something else, the assumeRoleArn field should be removed from jsonData
2) the cacheKey should be updated to include the authType  eg
```
cacheKey := dsInfo.AccessKey + ":" + dsInfo.Profile + ":" + dsInfo.AssumeRoleArn + ":" + dsInfo.AuthType
```

**Comment by torkelo** [comment]
thanks for the detailed investigation, should be a quick fix.

**Comment by torkelo** [comment]
@sunker is this something you can look at?

**Comment by sunker** [comment]
Sure! Yes, thanks for very detailed description of the problem.
