### ISSUE TITLE
grafana/ui: Add examples on custom validation in Forms story/documentation

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#22464]
**What would you like to be added**:
The only information regarding custom validation in Forms is this:

`validate: v => { // custom validation rule }`

However, void functions are not assignable to this rule but no mention about that in the docs or code. 

**Why is this needed**:
Validate does not currently mention what it expects which makes this super frustrating to use.

**Comment by Clarity-89** [comment]
Good point about void functions. I was just using custom validation in the forms, so I can add some docs and a few examples.

**Comment by Clarity-89** [comment]
@dprokop @peterholmberg seems like this task is done, should it be closed?

**Comment by peterholmberg** [comment]
@Clarity-89 yes!
