### ISSUE TITLE
Datasources: Update dashboard examples

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/grafana#22463]
**What would you like to be added**:
Some datasources dashboards JSON still contain old format data like "rows" and it would be better to upgrade them.

Old dashboards:
- prometheus_stats (Prometheus)
- prometheus_2_stats (Prometheus)
- grafana_stats (Prometheus)
- carbon_metrics (Graphite)

**Why is this needed**:
It can cause trouble if used as is (for example, the reporting feature is not working if we don't save them to upgrade them)

**Comment by marefr** [comment]
Good updating these, but still feels you're not backwards compatible in report feature given that anyone could have other dashboards with the same "old format" that you can't control.

**Comment by AgnesToulet** [comment]
I agree but it should be very rare because if you save your dashboard it will be updated automatically. I updated these because I think Grafana should not provide old dashboards but if users come with old dashboards, we can say them that this format is not supported anymore and that they have to save their dashboards at least once before using the reporting feature.
@xlson What do you think about this?

**Comment by torkelo** [comment]
Yea, maybe agree. If we detect these old schema we should just return an error explaining it

**Comment by xlson** [comment]
Yes that's a good point.
