### ISSUE TITLE
grafana theme plug-ins 

### ISSUE THREAD

**Issue by mail6562** [grafana/grafana#22462]
grafana  default them  duck and light ,too  few.
**What would you like to be added**:
how to extend more thems plug-ins.
or get more thems.
**Why is this needed**:
More plug-ins will enhance the user experience and expand user use。

**Comment by torkelo** [comment]
This is not likely anytime soon, maybe after all styling is moved to dynamic js based (emotion) styling, https://github.com/grafana/grafana/issues/10495
