### ISSUE TITLE
value to text mapping - greater and less than

### ISSUE THREAD

**Issue by fmakawa** [grafana/grafana#22469]
**What would you like to be added**:
The current implementation from my understanding needs you to expressly state a lower and upper limit. When we state let's say: from 500 to <blank> the text mapping for that is not triggered because it expecting an upper limit value. It would be great if we got true greater than and less than functionality for when we don't have an end limit to what we are monitoring but still want to map those value
**Why is this needed**:
Some times you have only one threshold for a value and it go above or below that by an amount that is not determined and dynamic so you simply need a condition of for example: value > 500 map to text "warning". The allows us to have dynamic mapping rather than forcing us to created random and arbitrary upper and lower limits which might still be exceeded

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
