### ISSUE TITLE
Google auth not working (2.0.2 - docker)

### ISSUE THREAD

**Issue by jtblin** [grafana/grafana#2247]
Hi,
first thanks for the awesome project! 

I'm using the docker image for grafana, set up the config to use Google Auth, created an app in the Google developer console, set the origin and redirect urls properly and the client_id and client secret in Grafana. When I sign in with Google, the google auth dance works fine and I'm redirected to Grafana `/login/google` page successfully by Google, but then it redirects me to the `/login` page without any message or anything.

Here are the Grafana logs (redacted some info):

```
2015/06/27 00:12:12 [I] Completed / 302 Found in 1.196357ms
2015/06/27 00:12:17 [I] Completed /login/google 302 Found in 775.576µs
2015/06/27 00:12:21 [T] login.OAuthLogin(Got token)
2015/06/27 00:12:21 [T] login.OAuthLogin(social login): &{112153474785315590 Redacted Name redacted@redacted.com  }
2015/06/27 00:12:21 [I] Completed /login/google 302 Found in 674.53822ms
```

This shows that the login is successful (i.e. Google sent back the token and user info). I can't see Javascript error in the console. I am able to login as admin without problem.

Thanks
Jerome

**Comment by jtblin** [comment]
Same issue as #1890. Adding `allow_sign_up = true` in `[auth.google]` solved the problem. It isn't documented anywhere so perhaps update the docs and `grafana.ini`?

**Comment by torkelo** [comment]
grafana.ini contains allow_sign_up in the google auth section (in master, it was missing in 2.0.2 release), 

But the docs mention it: 
http://docs.grafana.org/installation/configuration/#authgoogle con tain

**Comment by jtblin** [comment]
Ok thanks.

**Comment by gmistick** [comment]
I can say that this is still not working in latest helm chart. 
If i don't allow sign-ups i can't use Google Auth ?

**Comment by marefr** [comment]
@gmistick if not enabled you have to create users manually in Grafana before they can auth with google and login.
