### ISSUE TITLE
feature: update dashboard imported from grafana.com

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#22479]
**What would you like to be added**:
Currently we can easily import dashboards from grafana.com (https://grafana.com/docs/grafana/latest/reference/export_import/). However, once those have been updated, there is no way to pick up new revisions (as far as I can tell) without going through the full import + overwrite. It would be useful to have a single click (possibly in the "Versions" page of the dashboard settings), where it would pull down the latest revision.

**Why is this needed**:
We ship grafana dashboards as part of our product. When we release new versions, we want users to update grafana dashboards as well to make sure they get any improvements/necessary changes. Right now we are not publishing to grafana.com, but would like to, and this would make it easier for folks to stay in sync if we do chose this deployment model.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
