### ISSUE TITLE
Renderer: Support rendering panels into images in different scales

### ISSUE THREAD

**Issue by shankerwangmiao** [grafana/grafana#22472]
**What would you like to be added**:

Grafana is able to receive an additional parameter named `scale` in its `/render` API and provide images in higher resolutions. For example, a call to `/render` API with `width=100&height=80&scale=2` will generate an image 200x160 in size. Also note that it is different from one generated with `width=200&height=160`, because the text is large on the former one.

**Why is this needed**:

The resulting images can be used for different device pixel ratios.

**Comment by marefr** [comment]
> The resulting images can be used for different device pixel ratios.

@shankerwangmiao And what's the use case of this?

**Comment by shankerwangmiao** [comment]
> > The resulting images can be used for different device pixel ratios.
> 
> @shankerwangmiao And what's the use case of this?

For example, the rendered images can be displayed on a web page and it will be better if we can have those in different scales.

**Comment by marefr** [comment]
Fixed by #23625

Will require Grafana v7.0 and Image Renderer plugin new version to be released.
