### ISSUE TITLE
Text mapping to include value

### ISSUE THREAD

**Issue by fmakawa** [grafana/grafana#22470]
**What would you like to be added**:
I am aware that we can use prefixes and suffixes of text on value but this doesn't not allow for dynamic text and value combinations. It would be ideal if in value to text mapping if we were able to also include the value in the mapping. For example:
from 500 to 1000: "Warning. Requests at: {{ $value }}"
**Why is this needed**:
This allows us to have text mapping that also preserves the value. Currently, once you use text mapping you can no longer see the original value which in many cases could still be useful.

**Comment by bergquist** [comment]
Hm it's not a bad idea but I'm not sure its worth implementing. 
Can you solve your problem by selecting the value twice? Then you could have Warning/Error in one column and one column for showing the value. It should take up as much space as your suggestion. 

If we implement this I think it should be implemented in the dataframes.

**Comment by fmakawa** [comment]
@bergquist That unfortunately isn't an option since this isn't a table. Using single stat or gauge etc means we can't choose multiple times. In those cases then a having text mapping that allows a  value variable or something akin to it to preserve the value for use as in my request is needed

**Comment by dprokop** [comment]
Thanks @fmakawa for opening this issue. We do not see much interest in this feature request so I will close it for now.
