### ISSUE TITLE
Prometheus Proxied queries failing since 6.6.1 => 6.6.2 upgrade

### ISSUE THREAD

**Issue by butlerx** [grafana/grafana#22489]
**What happened**:
Following an upgrade from grafana 6.6.1 too 6.6.2 queries of 15s incremented metrics over an hour to Prometheus that is proxied with grafana are failing. 
producing the following error
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>502 Proxy Error</title> </head><body> <h1>Proxy Error</h1> <p>The proxy server received an invalid response from an upstream server.<br /> The proxy server could not handle the request <em><a href="/api/datasources/proxy/59/api/v1/query_range">GET&nbsp;/api/datasources/proxy/59/api/v1/query_range</a></em>.<p> Reason: <strong>Error reading from remote server</strong></p></p> </body></html> 
```
Adjusting the resolution to 1/4 allows the query to go through, but this is aggregating away the required data.

**What you expected to happen**:
I expect queries to Prometheus to resolve successfully 

**How to reproduce it (as minimally and precisely as possible)**:#
- Add Prometheus data source with a 15-second interval, and access proxy
- query for 1 hour of data

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Prometheus
- OS Grafana is installed on: centos7
- User OS & Browser: linux & firefox and osx & chrome
- Grafana plugins:
- Others:

**Comment by fingon** [comment]
I'm seeing something similar even with earlier versions too; step=30 works, but step=15 pretends there is no data while manual PromQL query works fine.

**Comment by Estrax** [comment]
Reproduced the error with 6.6.1 & 6.6.2 and confirmed it working on 7.0b1, but didn't find an exact reason why it stopped working between 6.6.1 and 6.6.2 as the significant changes around that were already put in 6.6.0.

**Comment by Estrax** [comment]
Confirmed to be working properly in 7.0. Closing this issue.
