### ISSUE TITLE
[Bug] Any value accepted for refresh query param, even if it's not in refresh_intervals list

### ISSUE THREAD

**Issue by cpmoore** [grafana/grafana#22485]
It appears that you can enter any value in the url for the refresh query param, even if that value is not in the `refresh_intervals` list for the dashboard.

This could be considered an issue as there may be some dashboards you want to prevent very low auto refreshes for.

**Comment by marefr** [comment]
We just merged #19416 that will be included in Grafana v6.7 so closing this as using that should resolve this.
