### ISSUE TITLE
Missing CSS on OS X (built from src)

### ISSUE THREAD

**Issue by csyvenky** [grafana/grafana#2249]
Hello,

This morning I followed the documentation instructions for building from source on OS X (10.9.5) and the build succeeded and I can run grafana. However, when I try to render the UI it's very clear that something is missing. When requests for grafana admin pages are made, the console will display the following:

2015/06/28 11:04:55 [I] Completed /css/grafana.light.min.css 404 Not Found in 2.410186ms
(or dark CSS if that theme is chosen).

The command used to retrieve the source was: go get github.com/grafana/grafana; I'm assuming this will pull the latest.

**Comment by torkelo** [comment]
did you generate css? default grunt task or "grunt css" will do it. Its in the build from source guide :)
