### ISSUE TITLE
Feature request: Support for ARM v5

### ISSUE THREAD

**Issue by tobi-tobsen** [grafana/grafana#22501]
None of the ARM packages [here ](https://grafana.com/grafana/download?platform=arm) are working for me on a Synology DiskStation DS212+. Granted, that is old hardware, but since the armv5 Package of influxdb works flawlessly, I wanted to ask if you could provide a compiled version for armv5 (I am not a Go developer myself, so basically clueless).

According to [GoArm](https://github.com/golang/go/wiki/GoArm) Go should be able to compile for armv5. 

There was once a similar bug #15695 (armv6 for raspi zero) and one user switched to chronograf instead (which is not working for me either - and frankly, I'd love to use the eyecandy grafana offers).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
