### ISSUE TITLE
Missing general metrics timerange (entire tab)

### ISSUE THREAD

**Issue by saijyothi369** [grafana/grafana#22508]
Hi I am new to grafana.I have installed grafana,influxdb and telegraf.But when I start grafana foe creating dashboard report i completely miss the entire General tab where we have "general metrics,options,value mappings and time range ".Please help .

**Comment by aocenas** [comment]
Hey @saijyothi369 can you post a picture of what you are looking at and where the tab is missing?

**Comment by saijyothi369** [comment]
Hi ,Hereby I am attaching the pic.

Above query ,I am completely missing the general,metrics etc... ......tab.



Regards,
Jyothi

**Comment by torkelo** [comment]
The options are in queries tab below your queries, sorry need to update docs

**Comment by saijyothi369** [comment]
I didn't get what you are saying...

Where is metrics tab??

Please respond...

Regards,
Jyothi

**Comment by torkelo** [comment]
I did not say metrics, queries tab, the first one & top where you define your queries. Look at the bottom of this pane
