### ISSUE TITLE
Flexible/Customized timeshift with Grafana Compare Queries

### ISSUE THREAD

**Issue by sukhjeets** [grafana/grafana#22505]
**What would you like to be added**:
I would like to have some sort of flexibility or customization while comparing the graphs for different time periods.

**Why is this needed**:
We have a requirement to project daily graph comparing the data from Elastic Search with last month. However, it should not consider weekends while comparing weekdays. For Example, if today is 3rd Friday of the current month then it should compare the data with 3rd Friday of the last month. If for any particular month we have more weekdays than the last month, it should consider the prior week's day for the last month. For Instance, compare 5th Thursday with 4th Thursday of last month if there is no 5th Thursday.

Is it possible to achieve in Grafana? Or can it be accommodated if not currently available?

**Comment by aocenas** [comment]
So I assume [panels timeshift](https://grafana.com/docs/grafana/latest/reference/timerange/#panel-time-overrides-and-timeshift) did not work for you? Not 100% sure right now but I think if you specify timeshift as `1M` that should mean calendar month.

**Comment by sukhjeets** [comment]
Yes that is correct and is not the behavior we want specifically while doing 1 month comparison.

**Comment by torkelo** [comment]
> For Example, if today is 3rd Friday of the current month then it should compare the data with 3rd Friday of the last month. If for any particular month we have more weekdays than the last month, it should consider the prior week's day for the last month. For Instance, compare 5th Thursday with 4th Thursday of last month if there is no 5th Thursday. 

Not sure we can support that in a maintainable way, unless it's an Elasticsearch query feature
