### ISSUE TITLE
Arithmetic operation on Zabbix items

### ISSUE THREAD

**Issue by zhagyilig** [grafana/grafana#22504]
Hi, we are using Grafana with Zabbix plugin as datasource.
In order to monitor cpu usage. Unfortunally, Zabbix item is cpu idle-time, so we need to convert it this way: <CPU_IDLE_TIME> *-1 + 100. When this is done by a query in database (in the case we are acquiring metrics from other tools), we just embed this calculation into the query in Grafana. Now using Zabbix plugin, we cannot see how we can do such thing.
For us is very important to normalize the way cpu usage is shown so it is very important to convert idle time to cpu usage.

Thanks in advance.

**Comment by zhagyilig** [comment]
I found a way, 1. zabbix  calculated https://www.zabbix.com/documentation/3.4/zh/manual/config/items/itemtypes/calculated
2. grafana  `scale` and `offset` function
![image](https://user-images.githubusercontent.com/24778921/75645844-7f54f700-5c82-11ea-87f8-b7e4234f0959.png)

**Comment by aocenas** [comment]
Hey @zhagyilig I assume this is no longer issue as you found a solution so going to close this, if that's not the case please reopen.
