### ISSUE TITLE
Gauge bar

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#22507]
**What happened**:
![image](https://user-images.githubusercontent.com/22203368/75657654-faa8af80-5c66-11ea-9296-bcbf5957c6d9.png)
When You resize gauge or just value changes, it bugs and overdraws itself.
**What you expected to happen**:
Of course,  working without these ghosts.
**How to reproduce it (as minimally and precisely as possible)**:
Select something from MySQL to gauge, use last value(sometimes it randomly works)and resize the gauge in the dashboard.
**Anything else we need to know?**:
I don't think so.
**Environment**:
- Grafana version:6.6.0
- Data source type & version:Mysql(MariaDB) 
- OS Grafana is installed on: Linux, Debian 9
- User OS & Browser: Windows, Chrome
- Grafana plugins:Nothing special.
- Others:?

**Comment by torkelo** [comment]
This is a strange old bug that we have yet been able to replicate, super strange. 

Maybe caused by some browser extension? We have yet to figure it out :(

**Comment by radimkohout** [comment]
> This is a strange old bug that we have yet been able to replicate, super strange.
Have or haven't?
>Maybe caused by some browser extension? 
I don't think so, tested in pure MS Edge, the result is the same.

**Comment by torkelo** [comment]
we have not, think most cases have been on windows.

**Comment by radimkohout** [comment]
Tested on Debian 9 Firefox.
