### ISSUE TITLE
Dashboard link titles as dropdown disappear behind sidebar

### ISSUE THREAD

**Issue by MaikoKingma** [grafana/grafana#22513]
**What happened**:
Dashboard link titles as dropdown disappear behind sidebar when pushed to the left of the screen by variables.
![Link dropdown issue](https://user-images.githubusercontent.com/21357422/75676167-01e0b500-5c89-11ea-8027-f1f31be475bf.PNG)

**What you expected to happen**:
Titles should be visible/readable either over the sidebar or not occupy the same space as the sidebar.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with enough variables to reach the right of the screen and a dropdown link where the link title is longer than the dropdown title.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.1 (21bf8b71bc)
- Data source type & version: InfluxDB 1.7.9 (unrelated)
- OS Grafana is installed on: Windows Server 2016 version 1607 (14393.2759)
- User OS & Browser: Windows 10 version 1909 (17763.1039)
- Grafana plugins: 
- Others:

**Comment by hugohaggmark** [comment]
Glorious news: either fixed by #28666 or #28330. Therefore, I'm closing this issue.

Thank You to you for taking the time to create this issue!
