### ISSUE TITLE
Stat title field reloads old value on focus change

### ISSUE THREAD

**Issue by Mitssumi** [grafana/grafana#22510]
**What happened**:
New Stat Visualization Title field resets to old value on focus change in the Field group.
Alter the Title value and change focus to an other field works like intended, only the focus on Title, Unit, Min, Max and Decimals field reloads the current value and overwrite changes.

**What you expected to happen**:
Keep new value after focus change and save.

**How to reproduce it (as minimally and precisely as possible)**:
Alter Stat Title field and change focus to Min field.

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Zabbix plugin 3.10.5
- OS Grafana is installed on: CentOS
- User OS & Browser: Edge (Chromium)

**Comment by torkelo** [comment]
confirmed bug! thanks for reporting this!

**Comment by dprokop** [comment]
Present in Gauge, BarGauge too
