### ISSUE TITLE
TemplateVariables: wrong sorting of value at variable filter with CAPITAL and regular symbol

### ISSUE THREAD

**Issue by andrewtk** [grafana/grafana#22512]
**What happened**: sorting of variables value is wrong.
iZettle follow after Yoco, but supposed to be after Coiney
screenshoot http://prntscr.com/ra9uv6

**What you expected to happen**: sort of value acording alphabet ignore caps letters

**How to reproduce it (as minimally and precisely as possible)**: create variables with value which started on Capital letter and regular letter, tune at Variables section ASC. When on dashboard you try to choose the value - small letters follow after values with Capital, but soppesed to be ignored capital case. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Version 6.6.1 (21bf8b71bc)
- Data source type & version: Mysql 8
- OS Grafana is installed on: linux
- User OS & Browser: windows10 & chrome
- Grafana plugins:
- Others:
![grafana lag](https://user-images.githubusercontent.com/25726236/75673887-a6b0c180-5c8c-11ea-906d-ff365fe8057e.jpg)

**Comment by aocenas** [comment]
Hey @dprokop pushed this to your backlog.

**Comment by ashharrison90** [comment]
hey @andrewtk 👋 

appreciate this issue has been open a really long time, so you've probably forgot all about it. think it got a little lost in our backlog. 😅 

i'm not sure if this was an option at the time or if it was added at a later date, but there is an `Alphabetical (case-insensitive)` option which should give you the behaviour you were after: 
![image](https://user-images.githubusercontent.com/20999846/141796422-251f443f-6c27-41aa-8fdb-a32b8ae22419.png)

again really sorry for the slow feedback on this. i imagine it was fixed a while ago 😬
