### ISSUE TITLE
response error &{error parsing interval

### ISSUE THREAD

**Issue by Moi0033** [grafana/grafana#22514]
Hello everyone,

I have an issue with an alert not sent. When I test the alarm I have this message, it’s impossible to get the alert :

`firing:true

state:""

conditionEvals:" = true"

timeMs:“30.059ms”

error:“tsdb.HandleRequest() response error &{error parsing interval $interval A 0xc00093d740 [] []}”

logs:Array[1]

0:Object

message:“Condition[0]: Query”

data:Object`

Would someone have any idea ? Thanks so much !

**Comment by aknuds1** [comment]
This looks more like a support request than a bug report. Could you please asking for help in the [Grafana community forums](https://community.grafana.com/) instead, as we use GitHub issues for reporting bugs/feature requests?

If you do think you have found a bug, please write it using our provided issue template.
