### ISSUE TITLE
Annotation API timeEnd similar as time

### ISSUE THREAD

**Issue by raphaelmonnard** [grafana/grafana#22518]
**What happened**:
When try to create Annotation with HTTP API, with the example https://grafana.com/docs/grafana/latest/http_api/annotations/#create-annotation:

```
POST /api/annotations HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "dashboardId":468,
  "panelId":1,
  "time":1507037197339,
  "timeEnd":1507180805056,
  "tags":["tag1","tag2"],
  "text":"Annotation Description"
}
```

The timeEnd not correspond to the request:

![image](https://user-images.githubusercontent.com/7360153/75687133-9fde7a80-5c9d-11ea-91f0-ced39667f706.png)

but is equal to the field "time".

**What you expected to happen**:
timeEnd: 1507180805056

**How to reproduce it (as minimally and precisely as possible)**:
Use the example from the doc: https://grafana.com/docs/grafana/latest/http_api/annotations/#create-annotation

**Anything else we need to know?**:
NA

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Grafana
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox
- Grafana plugins: NA
- Others: NA

**Comment by aocenas** [comment]
@marefr can you check this. It also seems like the docs with example response should be updated.

**Comment by marefr** [comment]
@raphaelmonnard it works as expected for me:

```bash
curl -XPOST -H "Accept: application/json" -H "Content-Type: application/json" -d "{
  \"dashboardId\": 2493,
  \"panelId\":5,
  \"time\":1507037197339,
  \"timeEnd\":1507180805056,
  \"tags\":[\"tag1\",\"tag2\"],
  \"text\":\"Annotation Description\"
}" "http://admin:admin@localhost:3000/api/annotations"
# response
{
  "id":4476,
  "message":"Annotation added"
}
```

```bash
> curl -H "Accept: application/json" http://localhost:3000/api/annotations\?from\=1506961543661\&to\=1507262538524\&dashboardId\=2493
# response
[
  {
    "id": 4476,
    "alertId": 0,
    "alertName": "",
    "dashboardId": 2493,
    "panelId": 5,
    "userId": 0,
    "newState": "",
    "prevState": "",
    "created": 1583318988343,
    "updated": 1583318988343,
    "time": 1507037197339,
    "timeEnd": 1507180805056,
    "text": "Annotation Description",
    "tags": [
      "tag1",
      "tag2"
    ],
    "login": "admin",
    "email": "admin@localhost",
    "avatarUrl": "/avatar/46d229b033af06a191ff2267bca9ae56",
    "data": {}
  }
]
```

Closing this.
