### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by akashnimare** [grafana/grafana#2251]
So I was able to setup the grafana and It's working.
I want to show the dashboards to other people but it asks for a authentication.
I have enabled auth_anonymous. Do you have any idea how to do this?

**Comment by torkelo** [comment]
```ini
#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
enabled = true
# specify organization name that should be used for unauthenticated users
org_name = Main Org.
# specify role for unauthenticated users
org_role = Viewer
```

Make sure org_name matched the exact name of the organization you want your `other poeple` to access :)
