### ISSUE TITLE
New forms: update input sizing 

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#22526]
We really need to change how input size property works, having it control width is very confusing :)

_Originally posted by @torkelo in https://github.com/grafana/grafana/pull/22517#issuecomment-593799197_

TODO:
- [ ] Rename `size` property to `width` and make inpiuts 100% width by default
- [ ] Introduce `size` property that implements sizing according to https://www.figma.com/file/LTMA7BJeMLz7xv8E9TJq1J/Form-styles?node-id=167%3A1252

**Comment by torkelo** [comment]
we already have an issue for this https://github.com/grafana/grafana/issues/22161

**Comment by torkelo** [comment]
I would ad that only add the sm, md, lg sizes that align with the same button sizes
