### ISSUE TITLE
Storybook: Native scrollbar is showing

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#22529]
![Screenshot 2020-03-02 at 18 29 59](https://user-images.githubusercontent.com/8878045/75696478-52b9d300-5cb4-11ea-85dc-5fc0f6f43144.png)

The native scrollbar only shows in Storybook, it's custom in Grafana. We should probably do something about that.

_Originally posted by @tskarhed in https://github.com/grafana/grafana/pull/22459#issuecomment-593833511_

**Comment by jackw** [comment]
@tskarhed do you happen to know if this is still an issue? Checking [here](https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-timepickers-timezonepicker--basic) and it seems the design has changed since this issue was first opened.

**Comment by tskarhed** [comment]
This is not an issjue with TimeZonePicker anymore, since it doesn't use Cascader anymore. Chrome on Ubuntu shows this on the Cascader. 
![Screenshot from 2021-08-16 16-40-16](https://user-images.githubusercontent.com/1438972/129581803-3ac376ed-9089-419d-a1b5-affa94421c48.png)
I'm okay with a won't fix for this one though.

**Comment by mckn** [comment]
Closing this one since it only occurs in Storybook.
