### ISSUE TITLE
add a metric search page, not in the dashboard edit page 

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2252]
Sometimes I only need find one metric, and want to search the metric dynamically in the page, which is more convenient than the dashboard. You need 4 steps to query a metric: 1) find the dashboard in the home page,  2) click in,  3) select the title,  4) click 'edit'). If add a search button in the home page, only one step.

**Comment by torkelo** [comment]
Similar to this, https://github.com/grafana/grafana/issues/264
