### ISSUE TITLE
Basic Auth password does not persist in new backend plugins

### ISSUE THREAD

**Issue by scottlepp** [grafana/grafana#22523]
**What happened**:
When setting basic auth on a datasource, the values are not persisted after a restart of grafana.  Though the changes do work until grafana is restarted.

**What you expected to happen**:
Credentials should be persisted.

**How to reproduce it (as minimally and precisely as possible)**:
Setup the Service Now datasource, add basic auth and save.  Then restart grafana.
Contact me to get a service now url and credentials.

**Anything else we need to know?**:

**Environment**:
- Grafana version: running locally from master branch
- Data source type & version: ServiceNow latest
- OS Grafana is installed on:  MacOS 
- User OS & Browser:  MacOS/Chrome
- Grafana plugins:

**Comment by ryantxu** [comment]
For more info... @scottlepp is testing converting the serviceNow plugin to the new plugin framework.  the `decryptedSecureJsonData` contains the password immediatly after saving it... but not after grafana is restarted

**Comment by ryantxu** [comment]
Without digging... my guess is this is a caching issue

**Comment by briangann** [comment]
i tested this with another plugin using the new sdk and the datasource settings do get saved to the database.  i manually configured the datasource, did a save and test, restarted grafana server, and it was still present (and working)

**Comment by scottlepp** [comment]
thanks @briangann for looking into this. 

looking a bit further into this, it's related to having 2 service now datasources.  the credentials are persisted on the first one (no issues there) but not on the second one.  i do see the updated timestamp change in the data_source table for both data sources

**Comment by scottlepp** [comment]
Looks like the json_data is now stored as clear text in the data_source table.  See the last record. Bug?

![image](https://user-images.githubusercontent.com/6108819/75783376-791c5480-5d2e-11ea-804e-5cff8873427a.png)

**Comment by torkelo** [comment]
All my json_data fields look like that, should be json string

**Comment by scottlepp** [comment]
I also see the datasource id changing after a restart (only for the second service now datasource) and the version set to 1.

**Comment by ryantxu** [comment]
Maybe related #22552

**Comment by scottlepp** [comment]
Closing for now.  The issue is happening only for 1 datasource.  Any new ones added work fine.
