### ISSUE TITLE
wrong data in singlestat

### ISSUE THREAD

**Issue by alexander4sc** [grafana/grafana#22533]
Singlestat shows obviously wrong fractured numbers when item type is numeric:
![1](https://user-images.githubusercontent.com/2564266/75764606-28692380-5d4f-11ea-9979-7f2668d1978c.PNG)
source data in zabbix latest data:
![2](https://user-images.githubusercontent.com/2564266/75764629-2d2dd780-5d4f-11ea-9a56-dab6dc8d8719.PNG)
item settings:
![3](https://user-images.githubusercontent.com/2564266/75764638-3028c800-5d4f-11ea-99f4-a0a2228f8591.PNG)
Query Inspector data:
[inspector.txt](https://github.com/grafana/grafana/files/4280645/inspector.txt)

**Environment**:
- Grafana version: 6.4.4 and 6.6.2
- Data source type & version: Type: Zabbix/ Zabbix 4.0.18. © 2001–2020, Zabbix SIA
- OS Grafana is installed on: CentOS Linux release 7.7.1908 (Core)
- User OS & Browser: Win10 Pro chrome 80.0.3987.122 x64
- Grafana plugins:
grafana-cli plugins ls                                                              
installed plugins:
alexanderzobnin-zabbix-app @ 3.10.5 
grafana-clock-panel @ 1.0.3 
grafana-piechart-panel @ 1.4.0 
vonage-status-panel @ 1.0.9

**Comment by torkelo** [comment]
It's probably an issue with the zabbix query / how it turns the response into time series:

https://github.com/alexanderzobnin/grafana-zabbix/issues

**Comment by alexander4sc** [comment]
can you give direct link please?
