### ISSUE TITLE
Reorder graph metrics via drag an and drop

### ISSUE THREAD

**Issue by tuxinaut** [grafana/grafana#2253]
It is not possible to reorder metrics via drag and drop for now. It'd be nice if that were possible.

**Comment by torkelo** [comment]
just be clear, do you want to reorder series in the graph legend, or metric queries in the edit mode `Metrics` tab?

**Comment by tuxinaut** [comment]
I meant the second option.

> metric queries in the edit mode `Metrics` tab

Today I had to reorder lots of metric queries and this was not the first time.

**Comment by vektory79** [comment]
+1

**Comment by sylr** [comment]
I second that request, when you add a new target in the metrics and want to put it on top it's a pain to use "Move up" until it reaches the position you were looking for.

**Comment by Joannou1** [comment]
Would just like to add my vote, this would be quite handy.
It would save up to half an hour of time of tediously clicking "Move up" for a bunch of new data rows on a bunch of new panels.
