### ISSUE TITLE
Admin API issue when auth.proxy is activated

### ISSUE THREAD

**Issue by geoffroya** [grafana/grafana#22540]
**What happened**: 

Grafana is setup to authenticate both via proxy and locally. When using admin API directly (eg /api/orgs) with local account Basic auth, we receive a 403

```bash
# From Grafana server
# Non admin API / Basic Auth => OK
curl -XGET "http://admin:$password@localhost:3000/grafana/api/org" -v -H "Accept: application/json" -H "Content-Type: application/json"
# Admin API / Basic Auth => KO 403
curl -XGET "http://admin:$password@localhost:3000/grafana/api/orgs" -v -H "Accept: application/json" -H "Content-Type: application/json"
# Admin API / Header based auth => OK
curl -XGET "http://localhost:3000/grafana/api/orgs" -v -H "Accept: application/json" -H "Content-Type: application/json" -H "X-WEBAUTH-USER: admin@localhost"
```

**What you expected to happen**: 

I would have expected Grafana Admin API to support all configured authentication methods

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Mysql
- OS Grafana is installed on: Centos 7.7
- User OS & Browser: NA
- Grafana plugins: Piechart, SimpleJson
- Others:

**Comment by torkelo** [comment]
Works when I try it. Make sure the user is a "Grafana Admin" (ie instance admin). 

If you login with this user can you access the server admin section ?
