### ISSUE TITLE
adding a custom function for graphite backend

### ISSUE THREAD

**Issue by robochat** [grafana/grafana#2254]
Hi,
I'd like to add a custom function for the graphite backend. I've already implemented the function in graphite (actually I'm using graphite-api but it all works nonetheless). I can see on github that there is a file gfunc.js which I need to edit but I can find it anywhere in my installation even though everything seems to work fine. I thought that it might be at ` /usr/share/grafana/public/app/plugins/datasource/graphite` but there are no javascript files there. Could someone help me? I'm using graphite 2.0.2.

**Comment by torkelo** [comment]
to modify gfunc.js you need to clone this repository , make the modification and build an optimized built (read building from source on the docs site).

**Comment by robochat** [comment]
Thank you, I managed to rebuild grafana and it all works. I had to install `fpm` and ruby in order to build an rpm but otherwise the instructions are very clear.
