### ISSUE TITLE
No fallback to auth.anonymous when user not found

### ISSUE THREAD

**Issue by geoffroya** [grafana/grafana#22549]
**What happened**:

Anonymous access doesn't work when both auth.proxy and ath.anonymous are activated AND provided user email is not found in local user database

**What you expected to happen**:

User coming with an unkown value in X-WEBAUTH-USER header should be "identified" as anonymous users - when auth.anonymous is activated

**How to reproduce it (as minimally and precisely as possible)**:

  * Activate both proxy and anonymous auth.
  * Create user1 with email user1@foo.org
  * Access to Grafana with header X-WEBAUTH-USER=user1@foo.org => OK
  * Access to Grafana with header X-WEBAUTH-USER=user2@foo.org => KO (should be OK)
  * Deactivate proxy auth and access to Grafana with header X-WEBAUTH-USER=user2@foo.org => OK

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.1
- OS Grafana is installed on: CentOS 7.7
- User OS & Browser: MacOS / Firefox

**Comment by torkelo** [comment]
But they are not anonymous, if coming through auth proxy they are authenticated in away.

**Comment by geoffroya** [comment]
Thank you @torkelo for your, but IMHO, the proxy should be here to **Authenticate**, whereas Grafana user database would provde **Authorization**. That's wite different requirements.

The front proxy doesn't has to make authorization for every application that is behind it

In my case, Grafana is not publicly opened, and I will have thousands of unknown users: they can authenticate but should be treated as anonymous users, browsing dashboards with Viewer role.
In the other hand, I have a small number of admins/editors that are manually registered in Grafana.

Don't you think this use-case make sense?

**Comment by torkelo** [comment]
think a way to set role via auth proxy would solve your need. Thought we supported that but seems like we do not:
https://github.com/grafana/grafana/issues/8816

**Comment by geoffroya** [comment]
Could be an option...if it worked
