### ISSUE TITLE
Empty SecureJsonData values returning true in SecureJsonFields

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#22552]
When you reset or empty a secret/key field and save. The field will be disabled as if there were a value saved. 
An empty string was posted and none is returned which means it understood that no secret was saved- however, the key's value in SecureJsonFields will be set to true.

I was able to produce this in both Azure Monitor and Cloudwatch with all key fields.

<img width="411" alt="Screen Shot 2020-03-03 at 4 32 49 PM" src="https://user-images.githubusercontent.com/3074595/75822125-6d9c4e00-5d6d-11ea-90da-92d848ccee03.png">

<img width="424" alt="Screen Shot 2020-03-03 at 4 33 04 PM" src="https://user-images.githubusercontent.com/3074595/75822131-70973e80-5d6d-11ea-91e8-022f40854d0a.png">

**Comment by aknuds1** [comment]
Could you please include more detailed info on how to reproduce the issue?

**Comment by shavonn** [comment]
1. Enter anything into a key field.
2. Save.
3. Click reset.
4. Empty the field.
5. Save.
@aknuds1

**Comment by ryantxu** [comment]
1. Create a new Azure Monitor datasource.  In the response I see:
![image](https://user-images.githubusercontent.com/705951/78072366-ddddc580-7353-11ea-9590-80d172c38752.png)

2. Edit Application insights details:
![image](https://user-images.githubusercontent.com/705951/78072416-f51cb300-7353-11ea-8685-cd3f689cd2e8.png)
after save and test:
![image](https://user-images.githubusercontent.com/705951/78072457-082f8300-7354-11ea-9dd7-5363a6e053ef.png)

3. Click reset:
![image](https://user-images.githubusercontent.com/705951/78072496-17aecc00-7354-11ea-9543-baeae4cfeaf6.png)

4. Save and test:
PUT request has:
![image](https://user-images.githubusercontent.com/705951/78072620-488f0100-7354-11ea-8686-bb78d75afcec.png)
GET request has:
![image](https://user-images.githubusercontent.com/705951/78072689-652b3900-7354-11ea-90ce-5b4cf45365e4.png)

SOOO... I think the solution will need to be in the frontend component -- looks like it is not sending anything to the backed to say it should clear!

**Comment by andresmgot** [comment]
FTR, this should have been fixed already. Also, you can use the helper [`updateDatasourcePluginResetOption`](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/datasource.ts#L139) exposed in `@grafana/data` to do that.
