### ISSUE TITLE
Why did I check the selected picture in the email alert, but there was no picture in the email I sent

### ISSUE THREAD

**Issue by xuchaozhang** [grafana/grafana#22559]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Please fill in the issue template, otherwise we aren't able to reproduce.

**Comment by xuchaozhang** [comment]
> **What happened**:   Warning picture not received by email
> 
> **What you expected to happen**: 
> 
> **How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/35486209/75862374-cf29ee80-5e39-11ea-92a3-d412192b4957.png)


![image](https://user-images.githubusercontent.com/35486209/75862374-cf29ee80-5e39-11ea-92a3-d412192b4957.png)

> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Grafana version:  6.6.1
> * Data source type & version:
> * OS Grafana is installed on: linux
> * User OS & Browser:
> * Grafana plugins:
> * Others:

**Comment by xuchaozhang** [comment]
![image](https://user-images.githubusercontent.com/35486209/75862640-347ddf80-5e3a-11ea-8177-c8c155a79079.png)

**Comment by aknuds1** [comment]
Does this also happen for you with the latest version, 6.6.2? How are you installing Grafana?

**Comment by xuchaozhang** [comment]
6.6.2 is not installed&nbsp; , &nbsp;in sudo&nbsp;yum install grafana-6.6.1-1.x86_64.rpm
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arve Knudsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 下午5:10
收件人:&nbsp;"grafana/grafana"<grafana@noreply.github.com&gt;;
抄送:&nbsp;"291917111"<291917111@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [grafana/grafana] Why did I check the selected picture in the email alert, but there was no picture in the email I sent (#22559)




Does this also happen for you with the latest version, 6.6.2? How are you installing Grafana?

**Comment by aknuds1** [comment]
Can you try installing [6.6.2](https://dl.grafana.com/oss/release/grafana-6.6.2-1.x86_64.rpm) and see if the bug happens there also?

**Comment by xuchaozhang** [comment]
I'm not sure if 6.6.2 is OK. Can you provide me with a normal version






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arve Knudsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 下午5:18
收件人:&nbsp;"grafana/grafana"<grafana@noreply.github.com&gt;;
抄送:&nbsp;"291917111"<291917111@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [grafana/grafana] Why did I check the selected picture in the email alert, but there was no picture in the email I sent (#22559)




Can you try installing 6.6.2 and see if the bug happens there also?

**Comment by aknuds1** [comment]
Why would 6.6.2 not be OK or normal? It's the latest official release.

**Comment by xuchaozhang** [comment]
I've upgraded version 6.6.2 to work normally, so it should be version 6.6.1. Thank you very much for your help. God bless you
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arve Knudsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 下午5:32
收件人:&nbsp;"grafana/grafana"<grafana@noreply.github.com&gt;;
抄送:&nbsp;"291917111"<291917111@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [grafana/grafana] Why did I check the selected picture in the email alert, but there was no picture in the email I sent (#22559)




Why would 6.6.2 not be OK or normal? It's the latest official release.
