### ISSUE TITLE
Azure Application Insight Query error on 6.6.x

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#22557]
**What happened**:
Working Azure Application Insight queries now fail with an error: 

> Cannot read property 'data' of undefined

Query inspector doesn't load either, so unable to provide output.

**What you expected to happen**:
Table data to be returned.

**How to reproduce it (as minimally and precisely as possible)**:
Setup Azure Log Analytis workspace, set format as 'Table'. Paste the following query into the window and edit the variables to your workspace:
`let data = app('/subscriptions/$subscriptions/resourceGroups/$resourcegroups/providers/$namespace/$resourcenames').requests
| where  $__timeFilter(timestamp)
;
data
| summarize Mean = avg(duration), (Median, p80, p95, p99) = percentiles(duration, 50, 80, 95, 99), Count = count(), Users = dcount(user_Id) by name, appName
| project App = appName, Operation = name, Mean, Median, p80, p95, p99, Count, Users, rank = 2
| union (data
| summarize Mean = avg(duration), (Median, p80, p95, p99) = percentiles(duration, 50, 80, 95, 99), Count = count(), Users = dcount(user_Id)
| project App = '🔸 All Apps', Operation = '🔸 All operations', Mean, Median, p80, p95, p99, Count, Users, rank = 1)
| extend Relevance = Mean * Count
| order by rank asc, Relevance desc
| take 250
| project-away Relevance, rank
| extend Mean = round(Mean, 2), Median = round(Median, 1), p80 = round(p80, 2), p95 = round(p95, 2), p99 = round(p99, 2)
| project App, Operation, Mean,Median,p80,p95,p99,Count,Users`

**Anything else we need to know?**:
Working fine on all 6.5 versions.

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Azure App Insights
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10/Chrome 80

**Comment by torkelo** [comment]
Can you open chrome dev tools and check network tab, track the request when you hit the refresh button, what does the Azure request return?

**Comment by bhozar** [comment]
Which data do you need? Looks like a 401 error:
![image](https://user-images.githubusercontent.com/1184220/75925178-26db5080-5e60-11ea-9c71-bea4fcb4c636.png)

Looking in /var/log/grafana.log I see this:
t=2020-03-04T21:35:15+0000 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="invalid character 'B' looking for beginning of value"

**Comment by bhozar** [comment]
Found the issue, thanks for pointing me in the right direction. I had to re-enter the details for the data source. They looked to be saved but testing them threw an error message. Once re-entered they are now working.

**Comment by y325A** [comment]
@bhozar @torkelo I don't think this issue should be closed.
We've just had the same issue and re-saving the data source has fixed it.

There seems to be some problems with this data source when updating to the latest version.
