### ISSUE TITLE
Bring Back Read Only Editor - granularity to the user, not the entire instance

### ISSUE THREAD

**Issue by drewboswell** [grafana/grafana#22561]
**What would you like to be added**:
Please bring back the user scoped read-only editor.

Two years ago in a move that saddens me, the scope of this setting went from user-level to entire Grafana instance level:  https://github.com/grafana/grafana/commit/35106537f2fbee5fce4e53d7118fc79089902a6d 

**Why is this needed**:
An instance scoped viewers_can_edit is a backtrack in security, and doesn't match operational needs. We should be able to create generic re-usable dashboards, that can be live-tweaked during outages/investigations but not save. This scope should be at the user level, not the instance.

*viewers_can_edit* allows a user to perform and query whatever they wish on any panel, dashboard, organization on an instance. 

Possible ways to add it back: add the full roll back in there, or add the "viewers_can_edit" flag to be applicable to an organization level

**Comment by torkelo** [comment]
We do not want to bring this role back. 

At some point we will have custom roles and full RBAC but enterprise. 

> viewers_can_edit allows a user to perform and query whatever they wish on any panel, dashboard, organization on an instance.

This is true no matter what. A viewer role can always issue any possible query to a datasource (but only in the org they are a member of).

**Comment by drewboswell** [comment]
@torkelo So.. on the conditions of being in one org
* member of the org
* member is Viewer
* datasource exists
* crafted payload sent to grafana datasource proxy service

we can query whatever we want, on whatever time period? Even if the query is different from the ones defined in the panels?

**Comment by torkelo** [comment]
yes. The reason is that queries are not static. They change radically based on template variables or ad-hoc filters. 

This could be made clearer in the UI & docs. https://grafana.com/docs/grafana/latest/permissions/overview/#data-source-permissions

have an issue to make this clearer:
https://github.com/grafana/grafana/issues/20843
