### ISSUE TITLE
Explore: switching off metrics not working for loki

### ISSUE THREAD

**Issue by PavloZabudskyi** [grafana/grafana#22573]
**What happened**:
Setting `"metrics": false` in `public/app/plugins/datasource/loki/plugin.json` has no effect

![image](https://user-images.githubusercontent.com/45065859/75895136-e2d75400-5e3d-11ea-9da7-cb8ca8ff2c1c.png)

**What you expected to happen**:
`Logs` mode becoming default. based at https://github.com/grafana/grafana/pull/16959 overview.

**How to reproduce it (as minimally and precisely as possible)**:
Set  `"metrics": false` in `public/app/plugins/datasource/loki/plugin.json` 

**Anything else we need to know?**:
Seting `"logs": false` works fine. Logs switcher disappers

![image](https://user-images.githubusercontent.com/45065859/75895408-495c7200-5e3e-11ea-9d45-9cf6c8f54677.png)

**Environment**:
- Grafana version: 6.6.0
- Data source type & version: loki, 1.3.0
- OS Grafana is installed on: CoreOS 2303.3.0, container
- User OS & Browser: Windows 10, chrome

**Comment by torkelo** [comment]
modifying this file is not supported (but should work, if you restart grafana-server after)

**Comment by PavloZabudskyi** [comment]
How should I set this values? https://github.com/grafana/grafana/pull/16959
```
supportedModes will include Metrics if datasource has "metrics": true in plugin.json
supportedModes will include Logs if datasource has "logs": true in plugin.json
```
I start grafana-server with this file already modified and it doesn't work.
