### ISSUE TITLE
Access denied creating Datasource

### ISSUE THREAD

**Issue by craigtho** [grafana/grafana#2257]
I am new to both GitHub and Grafana. I have been stuck being unable to create datasources in Grafana 2.0.2 with the following error log:

[datasources.go:93 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name

I am using Graphite-Web, Carbon-Cache and mysql for the db. I can successfully create users and store sessions, but when I try to add a datasource I receive a 500 Internal Server Error in the Chrome console. I have read all of the installation documentation, and am pretty sure I have covered everything, but might have missed a small detail. Any help would be appreciated.

Thanks

**Comment by torkelo** [comment]
Probably means the data source name you specified exists already
