### ISSUE TITLE
BUG: Cannot redefine property: 1

### ISSUE THREAD

**Issue by baur** [grafana/grafana#22574]
**What happened**:
Error: Cannot redefine property: 1

![image](https://user-images.githubusercontent.com/2898361/75899286-8ab44800-5e65-11ea-9bf5-7429e7b4eaa9.png)

![image](https://user-images.githubusercontent.com/2898361/75899426-b3d4d880-5e65-11ea-9990-c7a177d23f2d.png)

**What you expected to happen**:
query result
**How to reproduce it (as minimally and precisely as possible)**:
some queries to MSSQL DB
**Anything else we need to know?**:
Error if choose one of this: BarGauge, Gauge, Stat, SingleStat
**Environment**: 
- Grafana version:  v6.6.1
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Chrome
- Grafana plugins: BarGauge, Gauge, Stat, SingleStat
- Others:

**Comment by torkelo** [comment]
Can you open query inspector and expand the request & response details

**Comment by baur** [comment]
real query result 
---
time | value|metric
--- | --- | ---
2020-03-05  08:03:35.647 | 153 | 1
2020-03-05  08:03:35.647 | 37 |  2


```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1583352481564",
      "to": "1583374081565",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 1888,
          "datasourceId": 1,
          "rawSql": "select time, value, metric\n  from Dashboard.vNaryadByShiftNO\n  where ParentPlantID = 1",
          "format": "time_series"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 0,
          "sql": "select time, value, metric\n  from Dashboard.vNaryadByShiftNO\n  where ParentPlantID = 1"
        },
        "series": [
          {
            "name": "1",
            "points": [
              [
                153,
                1583395681929.9998
              ]
            ]
          },
          {
            "name": "2",
            "points": [
              [
                37,
                1583395681929.9998
              ]
            ]
          }
        ],
        "tables": null,
        "dataframes": null
      }
    }
  }
}
```
with Bar Gauge / Stat / Gauge

![image](https://user-images.githubusercontent.com/2898361/75941083-ee1b9580-5eb8-11ea-93e1-f5248281f48e.png)

with table or graph

![image](https://user-images.githubusercontent.com/2898361/75941254-579ba400-5eb9-11ea-9ffd-03f78f2e11c3.png)

**Comment by baur** [comment]
Not all queries, another query works fine

**Comment by torkelo** [comment]
ok, thanks will investigate

**Comment by torkelo** [comment]
It looks like the metric name is a number, can you convert that to a string in your query?

**Comment by bvdeenen** [comment]
I can confirm the this bug. The metric I receive from Prometheus is:

```
swift_proxy_firstbyte_bucket{env="pro",hostname="storage004",instance="storage004:9102",job="swift",le="0.025",policy="all",status="200",type="container"}
```
And when I try to stick `{{le}}` in the label description, Grafana throws the error. Removing the label keeps the panel in this error state

**Comment by Goosetaculous** [comment]
My query is

`select  
	cast(WEEK(user.created_at,1) as char) as metric,`....

And I'm still getting the error at Grafana 6.7.2

**Comment by torkelo** [comment]
Can you try 7.0 ?
