### ISSUE TITLE
Drilldown / Detail Link: Dashboard picker not finding /file dashboards

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2258]
The dashboard picker in the Drilldown / Detail Link section of a panel does not find JSON dashboards located in /file directories - just /db. 

For example, in dev-portal.raintank.io:

Dashboard picker list:
![screenshot 2015-06-26 13 34 12](https://cloud.githubusercontent.com/assets/2886187/8422312/6582ad20-1e9f-11e5-8c75-7631ccf1243d.png)

Drilldown Dashboard list, with far fewer dashboards available. 
![screenshot 2015-06-26 13 34 03](https://cloud.githubusercontent.com/assets/2886187/8422311/6582aff0-1e9f-11e5-8e56-7dadabf533ac.png)

(This is likely a similar issue to https://github.com/grafana/grafana/issues/960#issuecomment-101643427)

**Comment by torkelo** [comment]
The only thing that I could find was that the json dashboard search was case sensitive, other than that I cannot find any reason why they should appear in search and not in panel links auto complete.

**Comment by mattttt** [comment]
Even when taking case sensitivity into account, it looks like this is still only pulling db dashboards:

![screenshot 2015-07-01 18 57 46](https://cloud.githubusercontent.com/assets/2886187/8466682/396ff1a4-2023-11e5-8916-32e2093ae8d4.png)
