### ISSUE TITLE
in grafana, table panel  , Can table prometheus value be placed in the first column of the table?

### ISSUE THREAD

**Issue by uugit** [grafana/grafana#22589]
**Steps to reproduce**:

prometheus value be placed in the first column of the table panel?

**Actual Result**:

**Expected Result**

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by torkelo** [comment]
No right now, in upcoming new table panel (7.0) you will be able to re-arrange columns

**Comment by uugit** [comment]
thank you !  Does the boom table support?
