### ISSUE TITLE
[FeatureRequest] DataLinks: Add support for adhoc template variables

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#22583]
How to reproduce it (as minimally and precisely as possible): Create a data Link in a dashboard with an adhoc template variable, then attempt to reference that variable directly in the link.

What you expected to happen: I expected the Data Link to allow me to reference that template variable.

What happened: Instead the variable was left unreplaced, and it generated a broken link.

It works fine if you select the option to include all variables. Just not if you try to include only the adhoc variable. Which makes sense. When you include all variables, it simply copies all query parameters. If you try to reference it directly, you come up against the inability to do template replacement on adhoc variables (since that is a feature that would have been more or less useless up until now).

Using the "All Variables" option covers most cases, but we have already run into instances where we need more granular control than that.

Environment:

Grafana version: 6.6
Data source type & version: ES

**Comment by torkelo** [comment]
not sure we will support ad hoc variables here, ad hoc is for queries only. 

How would you want them to be rendered in a data link?

**Comment by Ultraseamus** [comment]
The way we use Data Links is actually just to link to Grafana dashboards. So our only requirement would be for the adhoc variable to be rendered the same way it is when it is included in "Include All Variables".

The trouble is that you don't always want to link out with every template variable. We have many use cases where dashboards are built without a specific template variable for every field that could be interesting, and we use adhoc filters to fill in those gaps.

**Comment by monitoring-aparavi** [comment]
Looks like now it's working, but only with queryparam (subfunction)?
${Filter:queryparam} it works
${Filter:lucene} doesn't work

**Comment by mdvictor** [comment]
It looks like this is working now so I will close this issue. Please reopen and let me know if there is still a problem!
