### ISSUE TITLE
Grafana Table panel Sorting Dates as per custom time range

### ISSUE THREAD

**Issue by RohitBharatai15** [grafana/grafana#22591]
Hi how can I sort dates as per my requirement in the time section?

![image](https://user-images.githubusercontent.com/56105210/75951976-6bec9a80-5ed3-11ea-948c-40135c20b599.png)

as here the I have set the min step as 7d but its not following any format like calender week or starting from 1st day of month etc. is there any way to do that?

Query used : PromQL sum(sum_over_time(metrics [7d]))

What is Needed is if 
1. A custom Time range is selected then the table day should start from that time range 
example Time Range selected : - 1 march - 30 march
Current situation for sum_over_time (metrics[30d])  starts date without following time range selected
Required : the count of metrics should start from the custom time range selected.
![image](https://user-images.githubusercontent.com/56105210/75952959-34332200-5ed6-11ea-9211-4f21e600b20a.png)

As above I have selected time range as 1 feb to 29 feb. but it starts from jan 9

**Comment by torkelo** [comment]
> As above I have selected time range as 1 feb to 29 feb. but it starts from jan 9 

Must be because Prometheus is not returning any data for the days before that. 

Use query inspector to view raw result prometheus is returning

**Comment by torkelo** [comment]
you can sort decending or ascending by clicking the column header, to disable sorting and the your metric query decide the sorting click so that the caret disappears

**Comment by RohitBharatai15** [comment]
> Must be because Prometheus is not returning any data for the days before that.
No Prometheus has data before and after those dates.
> Use query inspector to view raw result prometheus is returning
Query Inspector gave this result
`url:"api/datasources/proxy/2/api/v1/query_range?query=sum(sum_over_time(health_service_up%7Bjob%3D%22jobname%22%7D%5B30d%5D))%2Fsum(count_over_time(health_service_up%7Bjob%3D%22jobname%22%7D%5B30d%5D))*100&start=1578508200&end=1581100200&step=2592000"
`
so this `start=1578508200&end=1581100200&step=2592000"` start and end values are not provided by me its taking by default
I only provided `sum(sum_over_time(health_service_up{job="job name"}[30d]))/sum(count_over_time(health_service_up{job="job name"}[30d]))*100` 
_** with minimum step as 30d**_

**Comment by RohitBharatai15** [comment]
See this for an example I provided the custom time range from 1st feb to 29 feb and gave minimum step as 7d but result starts from 30 jan?
![image](https://user-images.githubusercontent.com/56105210/76056017-55117b00-5f9b-11ea-9f43-0901566b0376.png)
