### ISSUE TITLE
How to enale url enctryption on Grafana portal while diplaying dasbhboard Ask Question

### ISSUE THREAD

**Issue by miteshparmar4u** [grafana/grafana#22598]
**What happened**:
SQL injection on api call.
I want to enable url encryption on grafana in-house portal. When we design any sample payload with lets say influxDb/Mysql as database. On defined interval dashboard data will get refreshed by calling rest call to server in backend mode, while making call to server they have query parameter having sql query which designed for dashboard. Anyone on network payload easily can grab the sql details.

I want to make those rest call to secure or may be encrypted. Do we have any configuration on grafana.
**What you expected to happen**:
url encryption for data call
**How to reproduce it (as minimally and precisely as possible)**:
  open developer tool for network calls
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Influxdb
- OS Grafana is installed on: CentOS7
- User OS & Browser: Crome/firefox
- Grafana plugins:
- Others:

**Comment by davidnewhall** [comment]
What URL did you use for the InfluxDB data source? By default InfluxDB does not provide encrypted connections, but it can be configured to do so, or put behind a proxy that does. If your data source URL begins with `http://` and not `https://` it is going to be unencrypted. This is a configuration in InfluxDB and your Grafana data source settings.

https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/

If I'm misunderstanding your issue, and you actually want to encrypt Grafana's frontend, my personal recommendation is to put it behind a load balancer like nginx. You can also enable SSL/HTTPS in Grafana directly. The configuration directives are documented here: https://grafana.com/docs/grafana/latest/installation/configuration/ (search for `ssl`). You can find several howtos by googling for "ssl grafana."

**Comment by torkelo** [comment]
This is not possible sadly, we have to change and remove dynamic query support (template variables, etc)
