### ISSUE TITLE
Backend plugins: Implement support for collecting plugin config metrics

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#22597]
Implement support for collecting backend plugin config metrics. Allow plugin developer to return custom metric response depending on what plugin config contains. Need to expose new endpoints`/api/plugins/<plugin id>/metrics` and `/api/datasources/<data source id>/metrics`. Later Grafana UI can use these endpoints to request metrics and render the response in UI.

Blocked by: grafana/grafana-plugin-sdk-go#77
Epic: #19667

**Comment by bergquist** [comment]
Closing this since the metrics endpoint should expose all metrics for a plugin and not depend on PluginConfig.
