### ISSUE TITLE
[auth.azuread] failed:  login.OAuthLogin(NewTransportWithCode)

### ISSUE THREAD

**Issue by motoko89** [grafana/grafana#22609]
I'm using `6.7.0-274a4322pre` to test `[auth.azuread]`. From the UI, I see `login.OAuthLogin(NewTransportWithCode)`. In the log:

```
t=2020-03-05T22:47:26+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/azuread status=302 remote_addr=[REDACT] time_ms=10 size=366 referer=https://[REDACT]/login
t=2020-03-05T22:47:29+0000 lvl=info msg="state check" logger=oauth queryState=[REDACT] cookieState=[REDACT]
t=2020-03-05T22:47:29+0000 lvl=eror msg=**login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="invalid character '<' looking for beginning of value"**
t=2020-03-05T22:47:29+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/azuread status=500 remote_addr=[REDACT] time_ms=197 size=1743 referer=https://login.microsoftonline.com/
```

I understand that this means an HTML was returned instead of JSON but how do I find out what's wrong?

Here is my configuration:

```
[auth.azuread]
enabled = true
allow_sign_up = true
client_id = [REDACT]
client_secret = [REDACT]
scopes = openid email profile
auth_url = https://login.microsoftonline.com/[REDACT]/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/[REDACT]/oauth2/v2.0/authorize
api_url = https://login.microsoftonline.com/[REDACT]/openid/userinfo
allowed_domains =
allowed_groups = [REDACT]
```

**Comment by bergquist** [comment]
https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana

I think you want to set `token_url` to `https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token`

For troubleshooting issues like this, please use our community site 
[https://community.grafana.com/](https://community.grafana.com/)

We want issues on github to be about bugs and feature requests.

**Comment by motoko89** [comment]
Hi, my bad. I didn't notice the copy-paste issue. So I honestly thought it was a bug

**Comment by arnaudclerc** [comment]
I'm reopening this issue as i'm getting a similar error message. The problem being that all my configuration file are up and running on a different infrastructure without any issue.

grafana.ini
```
root_url = https://monitoring.[REDACT].shop
[auth.azuread]
name = AAD
enabled = true
allow_sign_up = true
client_id = [REDACT]
client_secret = [REDACT]
scopes = openid email profile
auth_url = https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token
;allowed_domains = [REDACT].fr
allowed_groups = [REDACT]
role_attribute_strict = true
allow_assign_grafana_admin = false
```

the error itself from grafana
`
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2023-01-05T08:18:06.883888493Z level=error msg="Request Completed" method=GET path=/login/azuread status=500 remote_addr=10.255.1.2 time_ms=265 duration=265.614117ms size=1366 referer=https://monitoring.[REDACT].shop/ traceID=00000000000000000000000000000000 handler=/login/:name
`

the remote addr is internal IP of my nginx RVP which serves the grafana container exposed on port 80

on the nginx part this error appears
`
2023/01/04 15:50:41 [error] 3780467#3780467: *199131 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 37.65.25.14, server: monitoring.[REDACT].shop, request: "GET /login/azuread?code=[AZURE_CODE]&session_state=ef2e943b-f394-4ef0-b74f-70132f717f18 HTTP/1.1", upstream: "http://10.47.0.6:80/login/azuread?code=[AZURE_CODE]
`


the really simple nginx conf (same as the one on the other infrastructure)
```
upstream monitoring {
        server JNSVDOKV005.blachere.local;
        keepalive 16;
}

server {
        listen 80;
        server_name monitoring.[REDACT].shop ;
        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;

        server_name monitoring.[REDACT].shop;

        ssl_certificate /etc/letsencrypt/live/outils.[REDACT].shop/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/outils.[REDACT].shop/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        error_log /var/log/nginx/monitor_error.log;
        access_log /var/log/nginx/monitoring.log;

        location / {
                proxy_set_header Host $http_host;
                proxy_pass http://JNSVDOKV005.blachere.local:80;
        }
}
```

i think i must be missing a simple port opening on my firewall, the authentication Microsoft page is showing correctly but once i click on a profile the redirection to grafana loads indefinitly and end up with timeout.

Seems like a easy problem if anyone could help, i think i'm blind.

Thanks in advance
