### ISSUE TITLE
[Feature Request] Add "import defaul as" selector , on importing dashboards from grafana 1.X with datasource=null 

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2260]
Hi @torkelo 

When importing dashboards from Grafana 1.X to grafana 2.X all dashboards with datasources equal to the default datasource are imported as "null" . This imported dashboard will work only if we can maintain the default datasource from both grafana versions.

 Is not my case , I can not maintain the default datasource  in my new platform, this makes dashboards unusable.

Could be interesting if you can add a selector  with "import default datasources as:"  to select the local datasource name to replace all "null" entries.

**Comment by toni-moreno** [comment]
We are now replacing by hand each "null" value , on each JSON panel editor from each Dashboard.

![image](https://cloud.githubusercontent.com/assets/5883405/8426691/197e17ac-1f12-11e5-99bf-4350ea8bb776.png)

We also are trying to do this changes with the global JSON viewer but we can not do it.

![image](https://cloud.githubusercontent.com/assets/5883405/8426719/3f454582-1f12-11e5-9361-6965f54786af.png)

could be also interesting if you can add  update capability to the global JSON viewer.

**Comment by torkelo** [comment]
Why could you not maintain the same default data source?

**Comment by toni-moreno** [comment]
Because we are building another bigger platform with new graphite backends. These new  graphite backends will have different metrics. 

Future dashboards should have these new graphite backends as default datasources, but we need also import old dashboards pointing to the old graphite backends.
