### ISSUE TITLE
SRV records resolution

### ISSUE THREAD

**Issue by Misosooup** [grafana/grafana#22608]
SRV records resolution for Prometheus datasource.

At the moment, it stores the entered URL in the database and query the host by appending the required query parameters and send that off to Prometheus for querying. 

Would it be possible to have a DNS resolution before that? Our stack sits in ECS and we have services discovery turned on so that services and talk to each other. However, when we insert the SRV record url into Grafana, it does not resolve to the right Prometheus DNS.

**Comment by torkelo** [comment]
Make sure the instance has the right DNS records, the resolution will be done from the backend (grafana-server)

**Comment by niklaskhf** [comment]
@Misosooup We are running into the same issue when using the ECS service discovery with SRV records. Were you able to get this to work?

**Comment by Misosooup** [comment]
@niklaskhf  Yeah, I tried whatever @torkelo said but that didn't do anything. I doubt Grafana has a proper DNS resolution thing like Prometheus that could resolve SRV records.

I ended up writing one in myself and launch it as a separate task together with Grafana. Instead of getting Grafana to point to Prometheus, it now points to that custom script which does the SRV resolution. 

It's a little hacky but it works pretty well. We have it in production now for a month now and it still hasn't failed.

**Comment by ben-turner** [comment]
This would be very helpful in any case where backends listen on dynamic ports. The only way around it is to put some kind of loadbalancer/request router in front of the backend

**Comment by Andor** [comment]
> Make sure the instance has the right DNS records, the resolution will be done from the backend (grafana-server)

I don't think you are right.
As far as I know, Grafana doesn't query DNS SRV records ATM at all.

**Comment by SunSparc** [comment]
Digging up this old issue because I too would like to see Grafana be able to do SRV lookups for the Datasource URL.

**Comment by SunSparc** [comment]
SRV record resolution would also be useful for setting up `unified_alerting.ha_peers`.
