### ISSUE TITLE
Back-end plugins: Plugins failing to start should be unregistered

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#22603]
**What happened**:
If the back-end component of a data source plugin fails to start, it's still available from the UI. 

**What you expected to happen**:
For a data source plugin to be unavailable in the UI if the back-end component doesn't start successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Make a data source plugin which lacks its back-end plugin executable, this should simply prevent it from starting, while it still shows up in the UI.

**Comment by ryantxu** [comment]
I'm not sure they should unregister -- but get a flag set that says they are not healthy.

We should also periodically check health and update the flag...

We will also soon need a flag for if it is signed

**Comment by aknuds1** [comment]
@ryantxu Should we involve UX in figuring out how to deal with failing plugins (as described in the issue) in the UI?

**Comment by tolzhabayev** [comment]
we are closing this issue as stale
