### ISSUE TITLE
Docs feedback: /administration/image_rendering.md

### ISSUE THREAD

**Issue by Afrojam** [grafana/grafana#22614]
The link to Notifications (https://grafana.com/docs/grafana/latest/administration/image_rendering/%7B%7B%20%3C%20relref%20%22../alerting/notifications.md%22%20%3E%7D%7D) it is broken.
Same happens for time-data-lifetime (https://grafana.com/docs/grafana/latest/administration/image_rendering/%7B%7B%20%3C%20relref%20%22/installation/configuration/#temp-data-lifetime%22%20%3E%20}})

**Comment by RobinJoe** [comment]
The latest version of the image rendering page seems to be working - https://grafana.com/docs/grafana/latest/administration/image_rendering/ - the two links in the opening paragraphs right?

**Comment by oddlittlebird** [comment]
This has been fixed.
