### ISSUE TITLE
how to Import dashboards from Grafana TESTING to Grafana PRODUCTION ?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2261]
we are developing dashboards from a grafana platform only for testing and design/change dashboards, and I need to deploy this new or modified dashboards to a Grafana Production platform.

 there is no way to import from other grafana  Real platform from the ui.

![image](https://cloud.githubusercontent.com/assets/5883405/8426845/2a6888da-1f13-11e5-93c9-9ebd1ab3c4bb.png)

 and there is not any  cmd tool to "list/import/export" from the grafana db.

how can I do it?

**Comment by torkelo** [comment]
There is currently no inbuilt support for this.


Try this tool: https://github.com/m110/grafcli

**Comment by toni-moreno** [comment]
Hi @torkelo I've reviewed the grafcli and seems a good project but it needs python 3 and we have  python 2.6  in our production servers.

We also need  cli tools to import/export/create/remove users/organizations, and this tool doesn't seem to be able to do this work. 

do you have any opened issues to talk about these CLI tools for grafana? we would like to contribute to this discussion.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1570
