### ISSUE TITLE
Grafana v6.7 Release Plan

### ISSUE THREAD

**Issue by jongyllen** [grafana/grafana#22616]
# Grafana v6.7
Release Coordinator: @xlson @jongyllen  

### 1.1. Publish What's new in Grafana draft article
**When:** Preliminary Wednesday 11th March 2020
**What:**

 - [x] Create Google doc and share with maintainers (Release coordinator)
 - [x] Write draft article (Maintainers)
 - [x] Open a PR (Release coordinator) in grafana repository
 - [x] Open PR in website repository merging `docs-grafana` branch into `master`
 - [x] Examine staging site
 - [x] Publish to grafana.com

**Who:** Release coordinator and maintainers

### 1.2. Beta 1 Release
**Preconditions:**

- [x] 1.1. Publish What's new in Grafana draft article

**When:** Preliminary Wednesday 11th March 2020
**What:**

 - [x] Checkout new release branch, v6.7.x, from head of origin/master
 - [x] Update versions to the next version to be released
 - [x] Update /scripts/build/publish.sh to contain the new “what's new” and “release note” links.
 - [x] Commit everything and push release branch
 - [x] Checkout master branch and branch of to a new branch
 - [x] Update version in package.json to point to the next pre-release, i.e. v7.0.0-pre and commit
 - [x] Open a PR
 - [x] Checkout release branch, create and push beta release tag and wait for CircleCI release build to finish
 - [x] Run automated verification tests
 - [x] Verify the front-end packages
 - [x] Update the changelog in master
 - [x] Create community site release note topic
 - [x] Create a new release on GitHub
 - [x] Create and upload Hosted Grafana images
 - [x] Update latest.json
 - [ ] Close the milestone

**Who:** Backend platform squad

## 2. Test and verification
Preconditions:

- [x] 1.2. Beta 1 Release

**When:** Preliminary Thursday 12th March 2020
**What:** For now we don’t have a lot of automated processes for UI tests so it’s suggested to start with manual test and verification to improve the quality of the release. The test and verification is done on the release branch.
**Who:** Primarily maintainers
**Who:** Release coordinator and maintainers

### 3.1 Publish What's new in Grafana final article

**Preconditions:**
 - [x] 1.2 Beta 1 released

**When:** Before stable release
**What:**

 - [x] Create a new Google doc based on What's new in Grafana draft article published and share with maintainers (Release coordinator)
 - [x] Write final article (Maintainers)
 - [x] Open a PR
 - [x] Publish to production (website repo)

**Who:** Release coordinator and maintainers

### 3.2 Create release blog post

**Preconditions:**
 - [x] 3.1 Publish What's new in Grafana final article

**When:** Before stable release
**What:**

 - [x] Use final what's new article as template and create new release blog post
 - [x] Remember to change relative links from What's new article to absolute ones
 - [x] Open a PR in website repo

**Who:** Release coordinator

## 4. Stable Release
**Preconditions:**

 - [ ] Beta released and no critical bugs left to fix for the stable release
 - [ ] 3. Docs and blog post

**When:** Most probably Wednesday 18th March 2020
**What:**

 - [ ] Cherry pick bug fixes into release branch (important for the stable release)
 - [ ] Create and push stable release tag and do the actual release

**Who:** Backend platform squad

## 5. Publish Release blog post
**Preconditions:**

- [ ] 3.2 Create release blog post
- [ ] 4. Stable Release

**When:** TBD
**What:**

 - [ ] Publish blog post

**Who:** Release coordinator

**Comment by torkelo** [comment]
> Open PR in website repository merging docs-grafana branch into master

This is automatic now, just deploy the website after the grafana repo -> website repo sync merge happens

**Comment by daniellee** [comment]
Think we count this as released now :-)
