### ISSUE TITLE
Panel Link generated url from Drilldown links is missing leading /

### ISSUE THREAD

**Issue by VRevol** [grafana/grafana#22617]
**What happened**:
Migrating provisioned 6.1.3 dashboards using Drilldown Links to 6.6.2 grafana version breaks out Panel Links.

**What you expected to happen**:
Generated URL should work out of the box

**How to reproduce it (as minimally and precisely as possible)**:

- Use a drilldown link to another dashboard in same grafana server running version 6.1.3 (not sure which version introduce this panel link change)
- Save template dashboard json
- Provision this dashboard json to a new docker using version 6.6.2
- Look for the url/panel link that is generated - it is only picking the base url of your grafana server
- Add "/" at the beginning of the url and test new url to find out it is correctly leading to the right dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Not related but we are using Cloudwatch
- OS Grafana is installed on: Docker image 6.6.2
- User OS & Browser: Win10 & Chrome 80.0.3987.122
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel
- Others:

Drilldown Links in ver. 6.1.3
![image](https://user-images.githubusercontent.com/49482510/76083781-a7a86280-5fae-11ea-8f8e-9ee6ba921096.png)

Panel Links in ver 6.6.2
![image](https://user-images.githubusercontent.com/49482510/76083823-bf7fe680-5fae-11ea-8cb4-22e33e5ccc67.png)

The only issue is a missing "/" at the beginning of the URL.
Adding the leading "/" fixes the link.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/21956   (so fix coming in 6.7, or nightly build )
