### ISSUE TITLE
Stackdriver: Add support for SLO timeseries

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#22627]
The existing Stackdriver datasource uses the [timeseries.list](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list) rest api to get time series data. The current query builder is completely designed around the idea that the user first specifies service and metric type, and after that group by/filter on the labels that are returned. 

That same endpoint can also be used to return time series for [SLOs](https://cloud.google.com/monitoring/service-monitoring/timeseries-selectors), but these time series can't be retrieved by specifying a metric type, but by specifying a time-series selector in the filter parameter to the timeSeries.list method. 

If we were to implement support for SLO queries, the big challenge will be the UX as the existing query editor was designed for metrics types selection. I can think of three different paths forward: 

1. In the list of services, add an option named `SLO`. If that option is selected, simply hide the metrics picker component. The bad thing with this solution is that it's conceptually wrong - SLO is not a service, but on the other hand it's easy to implement.  

2. At the top of the query builder, add a new dropdown with two options - `metrics` and ´SLOs`, and let metrics be the default value. That way, the two options can render two completely different paths - the metrics path would be exactly like today, whereas the SLO path would get a custom view with its own dropdowns. The downside with that is that it adds more dropdowns to the (already) bloated query builder.

3. Simple make is possible do deselect both service and metric (like it is when you add a new query row and nothing is selected). If no service and no metric is selected, an SLO can be specified in the filter component. 

**Filter component**
Regardless of which path we decide to go with above, the filter component needs to be changed as it currently only has support for the following structure `[OBJECT] [OPERATOR] [VALUE]`. As as first step, I suggest just adding a simple input field where the user can specify the whole expression, using the following format `SELECTOR_NAME(SLO_NAME, LOOKBACK_PERIOD)`. SLO_NAME is composed like this `projects/[PROJECT_ID]/services/[SERVICE_ID]/serviceLevelObjectives/[SLO_ID]`. Read more about SLO filter expressions in the [official docs](https://cloud.google.com/monitoring/service-monitoring/timeseries-selectors). 

As a second step, I think it would be useful if the query editor provided an interactive way of composing the SLO filter expression. Suggestion: When the filter plus button is clicked, all `SELECTOR_NAME`s could be populated in the dropdown. Once one option is selected, three more inputs (project id, service id and slo id) would be rendered and populated with values if possible. 

Questions:
* Are the selectors available in an API?
* Is it possible to get service ids and slo ids from some api? 
* Does it make sense to use aggregation, aligner and alignment period when issuing SLO queries?

**Comment by Dnefedkin** [comment]
> Are the selectors available in an API?

The list of available selectors  is  fixed, think about them as a list of some kind of higher order functions that exist in Stackdriver Monitoring to build complex filtering expressions. For the purpose of  Grafana Stackdriver data source, only selectors with SLO_NAME parameter should be supported. Selectors with 2 parameters: SLO_NAME and LOOKBACK_PERIOD are used in alerting functions.

It should be enough to support just these 3 selectors, at least initially:

- SLI value  - select_slo_health(SLO_NAME)
- SLO Compliance - select_slo_compliance(SLO_NAME)
- SLO error budget remaining - select_slo_budget(SLO_NAME)

**Comment by Dnefedkin** [comment]
>Is it possible to get service ids and slo ids from some api?

Retrieving the list of services for a project - https://cloud.google.com/monitoring/service-monitoring/using-api#service-list
Retrieving the list of SLOs for a service - https://cloud.google.com/monitoring/service-monitoring/using-api#slos-list

**Comment by Dnefedkin** [comment]
> Does it make sense to use aggregation, aligner and alignment period when issuing SLO queries?

Aligner: 

- for select_slo_health: ALIGN_MEAN

- for select_slo_compliance and select_slo_budget:  ALIGN_NEXT_OLDER

Alignment period:  
needs to be specified.  I do know if it's possible in Grafana, but in Stackdriver we apply alignment period on the fly depending on the time span that customer is looking at. E.g. for 1 month time span and for 6 hours time span alignment period will vary significantly

Aggregation: does not make sense, all the aggregations are done my time series selector function itself.

**Comment by sunker** [comment]
Thanks for quick feedback @Dnefedkin! 

> Aligner:
> * for select_slo_health: ALIGN_MEAN
> * for select_slo_compliance and select_slo_budget: ALIGN_NEXT_OLDER
Should I allow the user to change these values (the way it's currently possible in the editor)?

> Alignment period:
> needs to be specified. I do know if it's possible in Grafana, but in Stackdriver we apply alignment period on the fly depending on the time span that customer is looking at. E.g. for 1 month time span and for 6 hours time span alignment period will vary significantly
That's the way it works in the grafana datasource today - you can specify it manually or set it to auto. 

Do you have an opinion when it comes to the three options I'm suggesting above (they are not ordered prioritized)? We are releasing Grafana 6.7 Tuesday next week, so the room for changes is very narrow.

**Comment by Dnefedkin** [comment]
I actually like option #2 the most, as SLOs are not metrics and having a
clear delineation between them is beneficial.

**Comment by daniellee** [comment]
Closed by #22917
