### ISSUE TITLE
[ Feature Request] singlestat name dynamically pulled from a graphite query

### ISSUE THREAD

**Issue by xinity** [grafana/grafana#2262]
we can do graphite queries for singlstats, but i could be awesome if we have the ability to catch the aliasbynode legend to build the title of the singlestat widget.

i.e:
aliasByNode(lowestCurrent(collectd._._.cpu-wait, 5), 1)

this would catch the name of the server with the lowest value and put it as a singlestat title.

**Comment by snc29590** [comment]
it would be great to have this feature that would grab the metric name from the graphite query for single stat panels. This will be very useful while templating dashboards.

**Comment by torkelo** [comment]
you can do this today using $__name in the prefix or suffix fields. 

![image](https://user-images.githubusercontent.com/10999/39084005-894a1fba-456e-11e8-9774-2529485aa02c.png)
