### ISSUE TITLE
Option to disable "Leave site?" pop up when closing browser windows

### ISSUE THREAD

**Issue by max-rocket-internet** [grafana/grafana#22622]
**What would you like to be added**:

An option to disable the "Leave site?" pop up when closing browser windows.

I believe it's implemented with `onunload` `onbeforeunload` events.

**Why is this needed**:

If you are using Grafana regularly then it's simply annoying. I would much rather be responsible for saving (or losing) my own changes than having to click this every time I close a window.

Perhaps it could be a user preference?

**Comment by nguyenlamlll** [comment]
I support this as well. 
My scenario is that I embed Grafana panels into my web app, every time I want to navigate, an alert "Leave site?" goes up. It is pretty annoying, especially when I'm just viewing the panels, not editting.

**Comment by mblaschke** [comment]
This alert should not be shown if user is not logged in or dashbards are in embedded mode

**Comment by adrian-tarau** [comment]
Indeed. Especially when Grafana is embedded, you get these and you do not even know who asks for the work to be saved.
