### ISSUE TITLE
StatPanel: Value mappings not working 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#22624]
Looks like recent Field Config Override work for the new panel editor broke value mappings for all single stat panels (bar gauge, gauge, stat panel)

Think something in this function is stopping mappings from the defaults being returned in the field config 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldOverrides.ts#L127

**Comment by dprokop** [comment]
Problem is the mappings property does not have config in standard fields registry. Adding it now.
