### ISSUE TITLE
Error creating alert on Stackdriver metrics

### ISSUE THREAD

**Issue by lbatteau** [grafana/grafana#22634]
**What happened**: I tried to create an alert based on Stackdriver metrics. When I test the alert, I see an error message: ```tsdb.HandleRequest() response error &{{ "error": { "code": 400, "message": "Field aggregation.perSeriesAligner had an invalid value of \"ALIGN_MEAN\": The aligner cannot be applied to metrics with kind DELTA and value type DISTRIBUTION.", "status": "INVALID_ARGUMENT" } } A 0xc000d68440 [] []}```

**How to reproduce it (as minimally and precisely as possible)**: 
<img width="599" alt="Screenshot 2020-03-07 at 22 18 07" src="https://user-images.githubusercontent.com/478960/76152597-8d12de00-60c1-11ea-8ccd-9af3eb4e2841.png">

<img width="1455" alt="Screenshot 2020-03-07 at 21 48 49" src="https://user-images.githubusercontent.com/478960/76152603-9ac86380-60c1-11ea-9d6e-3111aac8406c.png">

**Anything else we need to know?**: I tried different settings for the aggregation, aligner, etc, but it does not make a difference.

I know the Stackdriver datasource is still in beta in my version, but I can't upgrade since it's part of a [Google Marketplace deployment](https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/k8s/prometheus). I also couldn't find any previous issue reporting this error.

**Environment**:
- Grafana version: 5.3.4
- Data source type & version: Stackdriver

**Comment by bergquist** [comment]
I'm sorry that you cannot upgrade the Grafana version but given that situation, I'm not sure how we can fix this either. For questions regarding what's supported in each version please ask them on the community site. [https://community.grafana.com/](https://community.grafana.com/)

We want issues on github to be about bugs and feature requests.

**Comment by lbatteau** [comment]
Right, but it would be helpful to know if it’s a bug or not. I don’t see it as a fix in later versions.

**Comment by pduchnovsky** [comment]
As a note, we upgraded the version of grafana to 7.3.7, plugin name is now "Google Cloud Monitoring" and we encounter similar error:
`{ "error": { "code": 400, "message": "Field aggregation.perSeriesAligner had an invalid value of \"ALIGN_MEAN\": The aligner cannot be applied to metrics with kind DELTA and value type DISTRIBUTION.", "status": "INVALID_ARGUMENT" } }`
