### ISSUE TITLE
Azure AD RBAC doesn't work as expected

### ISSUE THREAD

**Issue by networkandcode** [grafana/grafana#22633]
- I followed this https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana and I don’t see a link on the Grafana login page to sign in using Azure AD
- I am using stable/grafana Helm chart with Image version 6.6.2, from https://github.com/helm/charts/

**Comment by motoko89** [comment]
I believe `[auth.azuread]` is only available starting 6.7.0

**Comment by networkandcode** [comment]
so the documentation has to be corrected?, when would 6.7.0 be likely available

**Comment by bergquist** [comment]
6.7.0-beta1 will be released this week.
