### ISSUE TITLE
Top Menu "cut off" when expanding in embedded iframe

### ISSUE THREAD

**Issue by CainAbaddon** [grafana/grafana#2263]
Hey all, I'm not sure if this is a bug or just my lack of CSS/HTML experience. I have embedded a graph in an iframe on my page and I'd like to use the top menu's "view" button or something like it in order to take me from the embedded graph to the actual Grafana dashboard. However, the top menu is cut off whenever I try to open it in the iframe.

Before click: 
![screen shot 2015-06-30 at 11 18 26 am](https://cloud.githubusercontent.com/assets/8718245/8437045/c4dcd7b2-1f19-11e5-8174-b7c1739fa1df.png)

After opening menu:
![screen shot 2015-06-30 at 11 15 42 am](https://cloud.githubusercontent.com/assets/8718245/8437004/9034ddca-1f19-11e5-8754-17a2530b2036.png)

Any suggestions on what to do?

Thank you!

**Comment by torkelo** [comment]
if you want to get a dashboard view you will have to iframe a dashboard url, the panel iframe url is a special "solo panel" route and only shows a single panel

**Comment by CainAbaddon** [comment]
I understand that, perhaps I phrased the question wrong. How can I access the top menu popup from an embedded iframe? That's the main thing that is wrong.

**Comment by torkelo** [comment]
you cant, why would want to?

**Comment by CainAbaddon** [comment]
I suppose in order to zoom in and out of the graph. I'll have to create a separate button to take me to the dashboard I guess :)
