### ISSUE TITLE
what variable time series data is attached to in grafana?

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2264]
Hi Torkel,

I need to write a custom python function to forecast the time series data that comes from graphite and then present the data in grafana.

Looking at the chrome network render output, I see the data like this:

[{"target": "average", "datapoints": [[null, 1435688679], [34.870499801635745]]}]

I want to process this data and append my output this series and than chart. So the output will be some thing like this:

[{"target": "average", "datapoints": [[null, 1435688679], [34.870499801635745]]},{"target": "Forecast", "datapoints": [[186.77999925613403, 1435520801], [178.95000147819519, 1435521131]]},{"target": "Upper", "datapoints": [[186.77999925613403, 1435520801], [178.95000147819519, 1435521131]]}]

what do you refer to the data, what is the variable name before you chart, is it called timeseries?

**Comment by gsaray101** [comment]
I think it is called series?

**Comment by torkelo** [comment]
you can take a look at what the graphite data source returns. 

think it is something like this:
```json
{
   data: [
     {
        target: "my series name",
        datapoints: []
     }
    ]
}
