### ISSUE TITLE
IE11 ，legend not display

### ISSUE THREAD

**Issue by zhangschunfeng** [grafana/grafana#22641]
**Legend not displayed in IE11 browser**
  F12 console info:
  [object Error]{description: "未指明的错误。", message: "未指明的错误。", name: "Error", number: -2147467259, stack: "Error: 未指明的...", Symbol()_12.kwi1xmt92q: undefined, Symbol()_13.kwi1xmt92q: undefined, Symbol()_1b.kwi1xmt92q: undefined, Symbol()_1c.kwi1xmt92q: undefined, Symbol()_1d.kwi1xmt92q: undefined, Symbol()_1e.kwi1xmt92q: undefined, Symbol()_1f.kwi1xmt92q: undefined, Symbol()_1g.kwi1xmt92q: undefined, Symbol()_1h.kwi1xmt92q: undefined, Symbol()_1i.kwi1xmt92q: undefined, Symbol(__immutablehash__)_15.kwi1xmt92q: undefined, Symbol(immer-draftable)_1l.kwi1xmt92q: undefined, Symbol(immer-nothing)_1k.kwi1xmt92q: undefined, Symbol(immer-state)_1m.kwi1xmt92q: undefined, Symbol(LEAF)_16.kwi1xmt92q: undefined, Symbol(null)_19.kwi1xmt92q: undefined ...}

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
IE11
- Grafana version:
grafana 6.6.1
- Data source type & version:
influxdb
- OS Grafana is installed on:
centos
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zhangschunfeng** [comment]
`[object Error]{description: "未指明的错误。", message: "未指明的错误。", name: "Error", number: -2147467259, stack: "Error: 未指明的...", Symbol()_12.kwi1xmt92q: undefined, Symbol()_13.kwi1xmt92q: undefined, Symbol()_1b.kwi1xmt92q: undefined, Symbol()_1c.kwi1xmt92q: undefined, Symbol()_1d.kwi1xmt92q: undefined, Symbol()_1e.kwi1xmt92q: undefined, Symbol()_1f.kwi1xmt92q: undefined, Symbol()_1g.kwi1xmt92q: undefined, Symbol()_1h.kwi1xmt92q: undefined, Symbol()_1i.kwi1xmt92q: undefined, Symbol(__immutablehash__)_15.kwi1xmt92q: undefined, Symbol(immer-draftable)_1l.kwi1xmt92q: undefined, Symbol(immer-nothing)_1k.kwi1xmt92q: undefined, Symbol(immer-state)_1m.kwi1xmt92q: undefined, Symbol(LEAF)_16.kwi1xmt92q: undefined, Symbol(null)_19.kwi1xmt92q: undefined ...}`

**Comment by torkelo** [comment]
IE11 is not supported https://github.com/grafana/grafana/issues/15754
