### ISSUE TITLE
Support IS NULL operator in the SQL query builder

### ISSUE THREAD

**Issue by bgalartza** [grafana/grafana#22658]
**What would you like to be added**:
Currently there is no way of writing the "IS NULL" or "IS NOT NULL" operator in the WHERE clause using the query builder. The sentence works correctly if the "Edit SQL" functionality is used. 

Note: " column_name != null", is not valid SQL neither in [postgresql](https://www.postgresql.org/docs/9.1/functions-comparison.html) or [mysql](https://dev.mysql.com/doc/refman/8.0/en/working-with-null.html). 

**Why is this needed**:
Checking for null values is a common SQL operation, and it's not possible to use the query builder.  
Some users don't feel comfortable writing raw SQL, so using the query builder is preferable for them.

For example, if you are casting a column to text in the SELECT clause and there are some null values, the query will give an error.

**Comment by aocenas** [comment]
@dprokop added it your triage pipeline as this is about sql datasources

**Comment by aocenas** [comment]
@marefr should this be assigned to backend squad?

**Comment by marefr** [comment]
Wouldn't assign it to any team until we have more upvotes of this feature.

**Comment by dprokop** [comment]
Thanks @bgalartza for opening this issue. We do not see much interest in this feature request so far so I will close it for now.

**Comment by joostverdoorn** [comment]
would also love to see this implemented!

**Comment by EdelMaciasSofttek** [comment]
I don't see this as a feature, but as a bug fix. +1
