### ISSUE TITLE
Data link ${__value.time} is incorrect when graph has null value set to connected

### ISSUE THREAD

**Issue by Gongreg** [grafana/grafana#22651]
**What happened**:

Trying to get timestamp in data link in a graph that has null values returns incorrect time.

**What you expected to happen**:

Getting timestamp in data link in a graph that has null values returns correct timestamp for specific data link.

**How to reproduce it (as minimally and precisely as possible)**:

Open Grafana Playground: https://play.grafana.org/d/000000012/grafana-play-home?tab=visualization&orgId=1&fullscreen&edit&panelId=2&from=1583758800000&to=1583766000000

1. Add new Data link:

```
Title: Time
URL: http://localhost/${__data.fields[Time]}/${__value.time}
Open in new Tab: true
```

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/3867635/76225875-c6fcf500-6225-11ea-837f-4070fc4e6782.png">

2. Click on data at time: `2020-03-09 16:10:10`

3. `${__data.fields[Time]}` & `${__value.time}` will be set to `2020-03-09 16:08:10` & `1583762890000`.

**Anything else we need to know?**:

* The whole value field (text,numeric etc.) is pointing to the wrong data, not  only the `${__value.time}`.

* If you switch Stacking & null value from connected to null or null as zero it works correctly and returns `2020-03-09 16:10:10` as expected.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/3867635/76226747-f5c79b00-6226-11ea-88c3-798e3b15d963.png">

**Environment**:
- Grafana Playground.
- Grafana version: Grafana v6.6.1 (21bf8b71bc), Also managed to reproduce it on v6.6.2

**Comment by adeverteuil** [comment]
Hi @Gongreg,
Thanks for the problem report. Can you please complete this truncated sentence in your message?
> The whole value field (text,numeric etc.) is pointing to the wrong data, not

**Comment by Gongreg** [comment]
@adeverteuil, sorry, updated the message. I did an example about value.time at first, but then found out that the whole value points to a different value than it should.

**Comment by adeverteuil** [comment]
I was able to reproduce using Test Data DB and fixed CSV values.

## Downloadable dashboard

[github-22651-dashboard.json.gz](https://github.com/grafana/grafana/files/4308367/github-22651-dashboard.json.gz)

## Steps to reproduce the test panel

1. Create a Graph panel.
2. Use the Test Data DB data source.
3. Use the `CSV values` scenario.
4. Enter the values: `0,10,null,20,10,20,10`
5. In the visualization options, set the "Null value" option to `Connected`.
6. Create a data link with URL `http://localhost/${__data.fields[Time]}/${__value.time}`.

## Steps to reproduce the bug

On the graph table to the right, there is a null data point at `00:20:00`.

1. Open the dashboard on time range aligned on a 1 hour period (to easily identify data points by minutes past the hour).  
   `from=1583712000000&to=1583715600000`  
   `2020-03-09 00:00:00` to `2020-03-09 01:00:00`
2. Click on the data point at `00:30:00`.
3. Look at the target of the data link URL.


## What I see

The popup data link has the timestamp "2020-03-09 00:30:00"

The target URL of the data link is:  
`http://localhost/2020-03-08%2020:20:00/1583713200000`

The timestamp substituted for `${__data.fields[Time]}` and `${__value.time}` is the null data point that *precedes* the data point clicked.

## What I expected to see

The popup data link has the timestamp "2020-03-09 00:30:00"

The target URL of the data link is:  
`http://localhost/2020-03-08%2020:30:00/1583713800000`

## Version

Tested on v6.6.2.

## Other observations

The bug only happens with the **Null values** option set to 'Connected'.

## Documentation

https://grafana.com/docs/grafana/latest/reference/datalinks/#variables-to-use-in-your-url
