### ISSUE TITLE
Missing graph building options (v2.0.2)

### ISSUE THREAD

**Issue by gcanales75** [grafana/grafana#2265]
Hello, I'm testing version 2.0.2 but I'm doing something wrong because I cannot find how to combine and make calculations between two series... Here's the menu I see:

![v202](https://cloud.githubusercontent.com/assets/7468422/8442927/cb3a4274-1f47-11e5-844a-8474fa56033e.png)
I've tested v1.8 and I did see a different menu, including letters (#A, #B, etc...) for each series query and a plus sign at the end of the line to add calculations (standard deviations, moving averages, etc...)

Probably it's an easy thing, but I have a while looking for it and cannot find it.

Thanks and congratulations for an amazing application.

**Comment by torkelo** [comment]
The letters and the ability to transform series through a series of functions is only available in Graphite, it is not supported by InfluxDB.
