### ISSUE TITLE
Variables: bigger query result sets produce a "400 Bad Request"

### ISSUE THREAD

**Issue by dgttm** [grafana/grafana#22667]
Dear community,

When I build dashboards for an openstack environment, I'd like to setup some variables, which call themselves for an easier navigation (e.g. first select project or user, once that is selected, the dropdown variables only show the relevant instance ids or instance names etc.).

e.g.
![image](https://user-images.githubusercontent.com/13033378/76291150-dc693200-62ac-11ea-8785-af61816b14ed.png)

But it seems, when the request gets too big with that extrapolation of variable values, it happens to result in a 400 Bad request (e.g. my query was 22kb in size with 3 or 4 variables set)

![image](https://user-images.githubusercontent.com/13033378/76291385-471a6d80-62ad-11ea-8b39-85979ef3fa48.png)

![image](https://user-images.githubusercontent.com/13033378/76291331-2d792600-62ad-11ea-9179-9a4b53db02ee.png)

```
response:"<html><body><h1>400 Bad request</h1> Your browser sent an invalid request. </body></html> "
```

Once I remove a variable from the query, it is working fine, also when I select some values from the dropdown and reduce the query size accordingly. So it seems that just the query length is the problem. 
Can that somehow be tuned? or can I optimize my variables?

thanks a lot

Nicolas

prometheus, version 2.16.0
Grafana v6.6.2 (but tested also with previous versions)

**Comment by torkelo** [comment]
Try changing prometheus method to POST in the prometheus settings. 

Another thing to test is specifying a regex wildcard as a custom all value in the variable options. This is can make queries smaller when you select the All value in a variable
