### ISSUE TITLE
grafana-cli to write errors to stderr

### ISSUE THREAD

**Issue by mleonhard** [grafana/grafana#22661]
**What happened**:
```
$ grafana-cli plugins uninstall nonexistent-plugin >output.txt ; echo $?
1
```
I am writing a script that calls `grafana-cli` to update installed plugins.  The script processes the output of `grafana-cli`.  The user needs to see the output of `grafana-cli` when an error occurs. By convention, unix CLI programs write error messages to `stderr`.  This allows users to see error messages when the regular output of the program is captured or piped into another program.  Since `grafana-cli` writes its errors to `stdout`, my script must include extra code to emit any captured output.  This is unnecessary complexity.

Let's change `grafana-cli` to follow unix conventions and write error messages to `stderr`.

**What you expected to happen**:
```
$ grafana-cli plugins uninstall nonexistent-plugin >output.txt ; echo $?
Error: ✗ Plugin does not exist

NAME:
   Grafana cli plugins uninstall - uninstall <plugin id>

USAGE:
   Grafana cli plugins uninstall [arguments...]
1
```

**How to reproduce it (as minimally and precisely as possible)**:
```
$ docker run --rm --interactive --tty --entrypoint= grafana/grafana:6.6.2 grafana-cli plugins uninstall nonexistent-plugin 1>/dev/null
$
```

**Comment by aknuds1** [comment]
I haven't noticed that grafana-cli writes errors to stdout, but I agree, they should go to stderr.
