### ISSUE TITLE
Docs feedback: Developer Guide configuration step unclear

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#22663]
I was following the Developer Guide and noticed that the [Configure Grafana for development](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#configure-grafana-for-development) section mentions:
>The default configuration, grafana.ini, is located in the conf directory.
>
>To override the default configuration, create a custom.ini file in the conf directory. You only need to add the options you wish to override.

.. but this file doesn't exist (it used to some years ago). Should it refer to "defaults.ini" instead?

I think the docs [here](https://github.com/grafana/grafana/blob/master/docs/sources/installation/configuration.md#configuration) describes the setup more clearly

**Comment by wbrowne** [comment]
@aknuds1 I'm happy to jump in and fix if needs be 😄

**Comment by oddlittlebird** [comment]
This is clarified in the current [Configuration](https://grafana.com/docs/grafana/latest/installation/configuration/#config-file-locations) topic.

@marcusolsson , please review.

**Comment by marcusolsson** [comment]
I think you're right, it should say `defaults.ini` instead of `grafana.ini`. Thanks for pointing this out!

**Comment by oddlittlebird** [comment]
This has been fixed.
