### ISSUE TITLE
GUI representation of bits/bytes (IEC/metric)

### ISSUE THREAD

**Issue by hsolberg** [grafana/grafana#22668]
**Steps to reproduce**:
Set up any graph that use metrics with the unites bits or bytes. Then choose the units for bits or bytes (for IEC and Metric). Both look the same in the GUI after selecting them. See the screenshots below.
![grafana_metric_bytes](https://user-images.githubusercontent.com/22708664/76293185-e42ad580-62b0-11ea-94c3-f2cf74ccd150.png)

![grafana_IEC_bytes](https://user-images.githubusercontent.com/22708664/76293208-ec831080-62b0-11ea-965b-94682fdb9957.png)

![grafana_bytes](https://user-images.githubusercontent.com/22708664/76293219-f0169780-62b0-11ea-8400-ffb8b4b9df88.png)

**Actual Result**:
Both look the same after selecting in the drop-down meny. It just says "bytes" or "bits", there's no way to distinguish the two. When you open the drop-down menu to change the unit it's not marked in the drop-down either what unit was used before.

**Expected Result**
Some indication of what type of data-measurement is used. Add (IEC) behind the unit in the configuration-screen would be a good start to just distinguish the two.

![grafana_bytes](https://user-images.githubusercontent.com/22708664/76293219-f0169780-62b0-11ea-8400-ffb8b4b9df88.png)
In this view it would be nice to show the unit selected as "bytes (IEC)"

Looking at the categories-file you'll see that it's the same there. Not sure if that's where the text comes from, but it seems very likely.

Data (Metric)
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts#L138-L139

Data (IEC)
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts#L126-L127

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: Grafana v6.6.1 (21bf8b71bc)
- Data source type & version: N/A
- User OS & Browser: N/A
- Others: N/A

**Comment by bergquist** [comment]
Thank you for this well-written issue!

**Comment by dprokop** [comment]
Fixed by https://github.com/grafana/grafana/pull/23175
