### ISSUE TITLE
Querying too many data points leads to multiple series for the same metric

### ISSUE THREAD

**Issue by rohilbh** [grafana/grafana#2266]
I have around 300 events per second stored in my influx database and if i use a query in grafana that includes more than a couple minutes of data, grafana generates multiple series (multiple lines with different legend values but all with the same name) for one metric. I also get a datapoints outside time range error. 
![grafana image](https://cloud.githubusercontent.com/assets/3990923/8443492/1371f2aa-1f3c-11e5-9f31-2d7c4e31453d.png)

But if I restrict the query to less than 2 minutes, everything works fine.

**Comment by torkelo** [comment]
can you show the influxdb query and the influxdb response? You can see the response in the chrome dev tool network tab.

**Comment by rohilbh** [comment]
The influxdb queries are 
http://metric0.dev.quantifind.com:3000/api/datasources/proxy/3/query?q=SELECT+counter1+FROM+%22clickLogger_clickMetric2%22++where+time+%3E+now()+-+3m+

and
 
http://metric0.dev.quantifind.com:3000/api/datasources/proxy/3/query?q=SELECT+counter2+FROM+%22clickLogger_clickMetric2%22++where++time+%3E+now()+-+3m+and+time+%3C+now()+-+2m

The first query is the one causing problems. If I change the first query to be time restricted like the second one, everything works fine. 

The response for the first query is

{
	results: [
		{
			series: [
				{
					name: "clickLogger_clickMetric2",
					columns: [
						"time",
						"counter1"
					],
					values: []
				},
				{
					name: "clickLogger_clickMetric2",
					columns: [
						"time",
						"counter1"
					],
					values: [...]
				}
			]
		}
	]
}


Whereas the first response only has one  series. It seems to me that there's some kind of max points in a series so it's splitting it into 2 series with the same name.

**Comment by torkelo** [comment]
@rohilbh yes, influxdb is returning two series. might be an influxdb bug, not aware of one like this though. But you can ask in influxdb mailing list or irc channel
