### ISSUE TITLE
How can I configure the alarm period

### ISSUE THREAD

**Issue by rgonerao** [grafana/grafana#22665]
Hello friend:
       Grafana is good soft，We use her to show the chart，and use her to make alarm notification。 But how can I configure the alarm period。 I dont want her sent alarm notification between 01:00am  06:00am.
       Ths，hope your help.

**Comment by aknuds1** [comment]
Hi, please use the [community forums](https://community.grafana.com/) for support requests, since GitHub issues are for raising issues and feature requests. Thanks!
