### ISSUE TITLE
Implement shared tooltip in Grafana plugin developed using React

### ISSUE THREAD

**Issue by WaleedNaveed** [grafana/grafana#22672]
I am developing a Grafana plugin (Smith Chart) using react. I have used Syncfusion library to implement the plugin. Everything in my plugin is working fine. Grafana launched a new feature (Shared Tooltip) in Grafana version 4.1, [Shared ToolTip](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v4-1/) I have to use this feature in my plugin too, i didn't find any development instructions on grafana website. How can i implement this feature in my own plugin ? This feature is also not working on HeatMap plugin, screen-shot:

![SharedToolTip](https://user-images.githubusercontent.com/35847314/76392533-90dd8380-6393-11ea-9c8d-3ab0f32b4418.PNG)

How can i implement Shared ToolTip for my own plugin and also for HeatMap ? Shared ToolTip is even not working with other plugins like Gauge, Stats, Bar Gauge etc. It is only working with Graph plugin.

My Grafana version is 6.5.3
 

Any help would be much appreciated.

**Comment by dprokop** [comment]
@torkelo I'm not familiar with this feature, do you mind providing some guidance?

**Comment by torkelo** [comment]
We have yet to solve the event communication api to handle issues like shared tooltip / hover info

**Comment by WaleedNaveed** [comment]
Hello @torkelo  @dprokop ,

Any update on this ?

Thanks,
