### ISSUE TITLE
SQL: Grouping by an uuid column doesn't work

### ISSUE THREAD

**Issue by bgalartza** [grafana/grafana#22670]
**What happened**:
If you try to use an column of type UUID in the select and group by clauses, the query builder gives an "column XXXX must appear in the GROUP BY clause or be used in the aggregated function" even if it's there. This happens with postgresql data source, didn't try with other sql engine.
**What you expected to happen**:
The query should work as it was of any other column type (text for example).
**How to reproduce it (as minimally and precisely as possible)**:
Run the following SQL sentences to create some example tables and fill them with data:
```sql
CREATE TABLE table1 (
       group_id TEXT,
       value INTEGER,
       time TIMESTAMP WITHOUT TIME ZONE);

INSERT INTO table1 values('a',1, now());
INSERT INTO table1 values('a',2, now());
INSERT INTO table1 values('b',3, now());
INSERT INTO table1 values('b',4, now());

CREATE TABLE table2 (
       group_id UUID,
       value INTEGER,
       time TIMESTAMP WITHOUT TIME ZONE);

INSERT INTO table2 values('f94db230-9743-46da-82d1-6a7785fb523e',1, now());
INSERT INTO table2 values('f94db230-9743-46da-82d1-6a7785fb523e',2, now());
INSERT INTO table2 values('907def9c-8676-4f91-990e-06ce65e478bc',3, now());
INSERT INTO table2 values('907def9c-8676-4f91-990e-06ce65e478bc',4, now());
```
The two tables are identical, the only difference is that in table2 `uuids` are used for the `group_id` column.
If we try to graph the first table everything will work as expected:
![group-by-text](https://user-images.githubusercontent.com/46933620/76294455-2f45e800-62b3-11ea-8c52-4186246c23b3.png)
If we do the same with table2 the builder will give as an error
![group-by-uuid-1](https://user-images.githubusercontent.com/46933620/76294890-fc502400-62b3-11ea-9980-4d37a3c13990.png)
Alternative, but also giving error:
![group-by-uuid-2](https://user-images.githubusercontent.com/46933620/76294912-03773200-62b4-11ea-8487-6c62713b7733.png)

If we write in the SQL editor directly, everything works:
![group-by-uuid-3](https://user-images.githubusercontent.com/46933620/76294958-1a1d8900-62b4-11ea-9da0-a1d812b1ea89.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Postgresql 12
- OS Grafana is installed on:  Docker version 19.03.7 
- User OS & Browser: Ubuntu 16.04, Firefox 73.0.1
- Grafana plugins: no

**Comment by hugohaggmark** [comment]
Confirmed this is still a bug in 7.1.x

**Comment by hugohaggmark** [comment]
Some alternative solutions add `uuid` to group by data_type filter here: https://github.com/grafana/grafana/blob/cd9a773427ff04ef92ef6d896d8a87d151eb2e5d/public/app/plugins/datasource/postgres/meta_query.ts#L135

Look into why `this.groupAdd.type` isn't `column` here but that will need some debugging in `uiSegmentSrv`which is used by several plugins. https://github.com/grafana/grafana/blob/cd9a773427ff04ef92ef6d896d8a87d151eb2e5d/public/app/plugins/datasource/postgres/query_ctrl.ts#L664
