### ISSUE TITLE
AzureMonitor: Unable to use variables with an all option for resource groups 

### ISSUE THREAD

**Issue by jon-swain-autocab** [grafana/grafana#22679]
**What happened**:

I wanted to use variables on my dashboard with the ALL option enabled. However on trying this with an Azure Monitor data source doesn't work as it shows the following error 

The provided resource group name '{data-host-001-01,data-host-001-02,data-host-002-01,data-host-002-02,data-host-003-01,data-host-003-02}' has a length of '103' which exceeds the maximum length of '90'.

This is an error message form the Azure REST API as grafana is trying to call the endpoint but it is putting "{data-host-001-01,data-host-001-02,data-host-002-01,data-host-002-02,data-host-003-01,data-host-003-02}" as the resource group in the URL instead of iterating through the resource groups and calling the URL for each separate resource group.

I also believe this error will occour with other azure endpoints when retireving the following however i can't confirm that as i can't get past the first error

Namespaces, Resource Names, Metric Namespaces, Metrics

**How to reproduce it (as minimally and precisely as possible)**:

Set up a Azure Monitor data source which has several resource groups in it containing at least on VM each.
Set up a new dashboard with a new variable which uses the ResourceGroups() method to get the list of resource groups and has the include All option switched on.
On the new dashboard add a new graph panel, edit it and select your azure monitor data source and subscription. 
In the Resource Group dropdown enter your variable name i.e. $DataHosts (you might have to enter it then select it from the list which i think is another bug)
Then try to select a namespace from the drop down and you will see the error. 

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Azure Monitor (Built In)
- OS Grafana is installed on: Unbuntu
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

Attached are some images of the dashboard showing the error and the variable i had set up for the resource groups.

![Dashboard](https://user-images.githubusercontent.com/7262701/76312513-295c0100-62cb-11ea-9e3d-ae2c222b09df.PNG)
![DataHosts-Variable](https://user-images.githubusercontent.com/7262701/76312515-29f49780-62cb-11ea-9139-7329ed300923.PNG)

**Comment by jon-swain-autocab** [comment]
As an aside to this i have built Grafana myself and made some modifications to it to fix this issue.

However i am not confident in typescript or go so i'm not sure if i have done it the right way.

Attached are the two source files i have changed if this helps at all

[grafana-issue-22679-changes.zip](https://github.com/grafana/grafana/files/4318114/grafana-issue-22679-changes.zip)

**Comment by daniellee** [comment]
We are not going to fix this. Iterating through a list of resource groups and calling each separately will cause performance problems. We tried this with cross-resource queries: #19115 and had to revert it: #19346

The Azure Monitor API should instead support wildcards so that you can get metrics for multiple resource groups with one query,
