### ISSUE TITLE
MS SQL Plugin and unixtimestamps with seconds

### ISSUE THREAD

**Issue by lateralas** [grafana/grafana#22682]
**What would you like to be added**:
It would be great if a macro could be integrated so that timevalues in unixtimestamp with seconds can be used without calculation.

**Why is this needed**:
I am currently trying to display an MS SQL table in Explorer.
My problem is that the time column contains unixtimestamp values like this: 1583825182768. And the MSSQL plugin only understands values like this: 1583825182 ($ __ unixEpochFilter) or like this: 1583825182768000000 ($ __ unixEpochNanoFilter).
As a temporary solution, I have now set up my query as follows:
SELECT
   timecolumn AS "time",
   Value1 as value,
   Label1 as metric
FROM
   Testtable
WHERE
   **$ __ unixEpochNanoFilter (timecolumn * 1000000)**
ORDER BY
   timecolumn ASC

Is there currently a way to do the query without recalculating every timestamp?

Grafana - Grafana v6.6.0
Data source - MSSQL

anyway, thanks for this great tool 👍 

Lateralas

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
