### ISSUE TITLE
Use a supported release of MkDocs

### ISSUE THREAD

**Issue by d0ugal** [grafana/grafana#2268]
It looks like you are using an old, forked version of MkDocs that docker originally started. I am basing this assumption on the comments in #1571

I am wondering if there is a way we can get you onto a stable release and what blockers are stopping this transition? There are a bunch of released features you are missing and new ones coming.

I'd be very happy to help!

**Comment by d0ugal** [comment]
To give you some idea of the changes etc. I don't think you have anything from this page as you are based on a version older than 0.10.0.

http://www.mkdocs.org/about/release-notes/

**Comment by d0ugal** [comment]
I maybe should have opened the issue on https://github.com/grafana/docs-base?

**Comment by torkelo** [comment]
@d0ugal seems like docker switched to hugo

**Comment by d0ugal** [comment]
@torkelo Yup, that is correct. Unfortunately they forked MkDocs early on and added features specific to them. From a quick look at your docs, you are not using anything that we don't have in MkDocs official now.
