### ISSUE TITLE
"can't read dashboard provisioning files from directory "  with  grafana:6.6.2

### ISSUE THREAD

**Issue by Adhders** [grafana/grafana#22686]
Environment:
- Grafana version:  grafana:6.6.2
- Data source type & version: nfs
- OS Grafana is installed on: k8s 
- Grafana plugins: "grafana-kubernetes-app"

After create the pods on k8s, the logs show that:
"
t=2020-03-10T14:21:51+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/etc/grafana/provisioning/dashboards error="open /etc/grafana/provisioning/dashboards: no such file or directory"

t=2020-03-10T14:21:51+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin." logger=rendering renderer=phantomJS

**Comment by bergquist** [comment]
Hi

I'm not really sure I understand this issue.

Your Grafana instance is configured to read dashboards from `/etc/grafana/provisioning/dashboards`  but the folder doesn't exist. So it won't be able to provision any dashboards. If you dont want to provision any dashboards you should update the dashboard provisioning config https://grafana.com/docs/grafana/latest/administration/provisioning/#config-file

**Comment by Adhders** [comment]
> Hi
> 
> I'm not really sure I understand this issue.
> 
> Your Grafana instance is configured to read dashboards from `/etc/grafana/provisioning/dashboards` but the folder doesn't exist. So it won't be able to provision any dashboards. If you dont want to provision any dashboards you should update the dashboard provisioning config https://grafana.com/docs/grafana/latest/administration/provisioning/#config-fil

> Hi
> 
> I'm not really sure I understand this issue.
> 
> Your Grafana instance is configured to read dashboards from `/etc/grafana/provisioning/dashboards` but the folder doesn't exist. So it won't be able to provision any dashboards. If you dont want to provision any dashboards you should update the dashboard provisioning config https://grafana.com/docs/grafana/latest/administration/provisioning/#config-file

thanks for your timely reply, I don't want to read dashboards from /etc/grafana/provisioning/dashboards,  because I have store the dashbords file in persistentVolume. so how can I disable it
