### ISSUE TITLE
Docs feedback: /features/panels/logs.md

### ISSUE THREAD

**Issue by therearesomewhocallmetim** [grafana/grafana#22691]
Please add a link to the log filtering language. Currently, the section "Querying Data" only mentions the fact that one can query log entries, however, there is no description of how it can be done.

**Comment by bergquist** [comment]
Hi

Any chance you want to open an PR? 
On the https://grafana.com/docs/grafana/latest/features/panels/logs/ there is a link in the top right corner "Edit this page" where you can create a pull request on github.

**Comment by oddlittlebird** [comment]
It looks like this is still valid post-7.0, but the Logs panel is documented here: https://grafana.com/docs/grafana/latest/panels/visualizations/logs-panel/
