### ISSUE TITLE
Problems when importing dashboards with different data sources.

### ISSUE THREAD

**Issue by tau0** [grafana/grafana#2269]
For example there are a lot of graphs which use different databases. I need to create every data source for each database and then set them manually in each graph. And import didn't create data sources automatically or help me.

**Comment by torkelo** [comment]
yes, you need to create the datasources and name them the same as you named them in Grafana 1.x , this is in the docs :)

**Comment by tau0** [comment]
Thank you!

**Comment by tau0** [comment]
I've created the datasources and name them the same as I named them in config.js. but some of them imported with data source named graphite. But I've never had this data source before, only influxdb, but some of them imported correctly.

**Comment by torkelo** [comment]
that is strange

**Comment by tau0** [comment]
When I look on exported json (in old Grafana UI) I can see graphite in datasource field, and this is strange because there is no this datasource in config.js. And there is a different datasource used in every graph on this dashboard. I can attach screenshots if you need one. So I think the problem is somewhere in previous versions. Or maybe I'm doing something wrong. Any ideas?
