### ISSUE TITLE
Unable to map Azure AD group with Grafana Org

### ISSUE THREAD

**Issue by uvaisibrahim** [grafana/grafana#22711]
I have integrated Azure AD with Grafana for authentication. In the Grafana documentation, I am not seeing the relevant information to map a particular AD group with a particular Grafana org(https://grafana.com/docs/grafana/latest/auth/azuread/). Is this supports in Grafana(6.6.2) or is this something new feature to be implemented?

Currently, while I am logging, grafana takes me into a default `Main Org (org_id = 1)`.

**Comment by bergquist** [comment]
Azure AD requires 6.7
6.7-beta1 will be released this week. 

https://github.com/grafana/grafana/pull/22692

**Comment by uvaisibrahim** [comment]
Hi @bergquist ,
Still, the documentation do not cover up on how to map the Grafana Org with particular AD group as we can do with LDAP. In LDAP, for this purpose, we do have a separate `ldap.toml` file and in that we can map Particular CN with Particular org_id as given below.

```
[[servers.group_mappings]]
group_dn = "CN=r_grafana_admin,OU=Roles,OU=Security,OU=Groups,DC=corporate,DC=t-test,DC=com"
org_role = "Admin"
org_id = 32
```
I need to do the same thing with Grafana-Azure AD combination also, but unfortunately, the Grafana documentation does not cover up that part. I am referring to the below link.

https://grafana.com/docs/grafana/latest/auth/generic-oauth/
