### ISSUE TITLE
Kiosk mode allows creating annotations

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#22735]
**What happened**:

I opened a playlist on play.grafana.org (https://play.grafana.org/d/000000003/big-dashboard-small?orgId=1) in kiosk mode.
when i click on a chart, i can create an annotation that is persisted and visible to other people looking at the same dashboard

**What you expected to happen**:

not be able to create annotations in kiosk mode

**Comment by bergquist** [comment]
Not sure this is a frequent enough problem that it's worth solving. Forwarding to frontend platform and they can make a decision

**Comment by dprokop** [comment]
Agree with @bergquist. If we get some more evidence on this we will reconsider fixing.

**Comment by Dieterbe** [comment]
what more evidence do you need? 
you can literally go to play.grafana.org, start a playlist in kiosk mode, and add as many annotations as you like.

**Comment by torkelo** [comment]
More evidence that this is a problem, you have to hold in Ctrl to create annotations, so it’s not like it’s accidental

**Comment by Dieterbe** [comment]
seems like a security issue to me. when people who are supposed to be "viewers" at a kiosk/information display, can actively add stuff into your data.
