### ISSUE TITLE
302 redirection toward login page even if password is correct

### ISSUE THREAD

**Issue by DariusMR** [grafana/grafana#22731]
**What happened**: after some time I can't login to grafana anymore I'm redirected to the login page every time

**What you expected to happen**: to be loggued in

**How to reproduce it (as minimally and precisely as possible)**: Don't know how but I've seen this problem with both reverse proxy (nginx) and direct access

**Anything else we need to know?**: I've downgraded to 6.5.3 and now login is working

**Environment**:
- Grafana version: 6.6.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by bergquist** [comment]
Hi!

Should be fixed by https://github.com/grafana/grafana/pull/22285
6.7.0 beta will be released this week. Please try it out and ping me if it doesn't so I can reopen this issue.

**Comment by DariusMR** [comment]
Hi,
I've tested lots of different version of grafana. I'm in v7.1.1 (3039f9c3bd) and sale problem which occcurs randomly.. working with edge but not with chrome anymore at the moment. Even in private mode I really dont understand why

**Comment by DariusMR** [comment]
here is the first log I saw
t=2020-07-31T10:56:31+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2020-07-31T10:56:31+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=172.29.0.1 time_ms=0 size=29 referer=https://grafana.demo.****/login

**Comment by deanlennox** [comment]
Having the same problem:
Grafana v7.1.3 on Ubuntu 20.04.1 LTS
cookie_samesite = disabled (None wont work on chrome)
allow_embedding = true
Not sure if HTTPS required? Only able to run as http

**Comment by oester** [comment]
I have this same issue on my docker container, local access, no proxy, not https.

I was running 7.1.5, updated to 7.2 and now I get redirected back to the login page after successful login. This happens ONLY on Chrome - I tried it from Safari and Firefox, and it works correctly. I also tried it from a brand new chrome instance (no leftover cache/cookies/extensions) and it fails as well.

302 error in grafana.log:

t=2020-09-24T14:56:22+0000 lvl=info msg=“Successful Login” logger=http.server User=root@localhost
t=2020-09-24T14:56:22+0000 lvl=info msg=“Request Completed” logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=192.168.25.68 time_ms=0 size=29 referer=http://192.168.25.195:3003/login

**Comment by DariusMR** [comment]
Hi
did you tried "GF_SECURITY_COOKIE_SAMESITE=disabled" ?

**Comment by oester** [comment]
Hah, you beat me to it - I just tried this and it fixed the issue!

**Comment by safejob** [comment]
> Hi did you tried "GF_SECURITY_COOKIE_SAMESITE=disabled" ?

do well
