### ISSUE TITLE
Limit datasource connection/query number

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#22743]
**What would you like to be added**:
Add a feture to set or limit connections or queries concurrency number for a datasource like MySQL 
**Why is this needed**:
Grafana dashboards are used for real-time data show, and sometimes refresh with high frequency. Dashboard consists of many pannels which connect to datasources, and those datasources usually are production. While too many user open a same dashboard, the datasource will be under high pressure.

**Comment by bergquist** [comment]
Hi 

That's possible since 5.4.0

https://github.com/grafana/grafana/blob/master/CHANGELOG.md#new-features-3
