### ISSUE TITLE
Grafana add to org dropdown is not showing all elements in json

### ISSUE THREAD

**Issue by Dileep-Dora** [grafana/grafana#22749]
**What happened**:
In grafana admin page while adding a user to an organization the dropdown it's not showing all list returned in the JSON.
**What you expected to happen**:
It has to show all elements returned in the JSON.
**How to reproduce it (as minimally and precisely as possible)**:
grafana admin -> users -> select user -> add organization, scroll bar actually going out of div
**Anything else we need to know?**:
<img width="634" alt="Screenshot 2020-03-12 at 4 33 23 PM" src="https://user-images.githubusercontent.com/19973796/76515951-864ce800-6480-11ea-938a-75998dd47d72.png">

**Environment**:
- Grafana version: 6.6.2
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

**Comment by vvvprabhakar** [comment]
+1
