### ISSUE TITLE
timeSrv needed in Grafana runtime

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#22740]
Unable to access timeSrv in external plugins in React.

**Comment by ryantxu** [comment]
what part is needed?  can change the time using locationSrv?

**Comment by shavonn** [comment]
@ryantxu In splunk, it's used to get a time range

**Comment by ryantxu** [comment]
lets look... but should be passed via panel props

**Comment by ryantxu** [comment]
For now we can set the time with `locationSrv` and get the time from panel data -- rather than exposing timeSrv, we should likely expo
