### ISSUE TITLE
v6.7.0-beta1 (eaaca91f25) incorrectly sets application/json in Content-Type header when querying InfluxDB using HTTP POST

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#22756]
**What happened**: Grafana queries InfluxDB using a `application/json, application/x-www-form-urlencoded` Content-Type header instead of `application/x-www-form-urlencoded` when using the HTTP POST method.

**What you expected to happen**: Should use `application/x-www-form-urlencoded` instead

**How to reproduce it (as minimally and precisely as possible)**: Configure Grafana to query using HTTP POST from InfluxDB, `Save & Test` button fails with `InfluxDB Error: missing required parameter "q"`

**Anything else we need to know?**: I believe that the bug was introduced with https://github.com/grafana/grafana/commit/0390b5601ea741e261b281b019011f6cc0651ac4 and https://github.com/grafana/grafana/commit/f95c8b785c322cfe60c8c30b57b0383513470e47 adding a `Content-Type` header of `application/json`

**Environment**:
- Grafana version: `v6.7.0-beta1 (eaaca91f25)`
- Data source type & version: InfluxDB 1.7.10
- OS Grafana is installed on: Docker
- User OS & Browser: Windows, Chrome
- Grafana plugins:
- Others:

**Comment by prashanthjbabu** [comment]
I'm seeing this issue as well!

**Comment by aknuds1** [comment]
Thanks for reporting the issue, we're looking into it.
