### ISSUE TITLE
How to define the time range if client and server time are not sync

### ISSUE THREAD

**Issue by chongyuanyin** [grafana/grafana#22750]
**What happened**:
The browser on client side sometimes has different time with the server. In our scenario, we want to confine the "to" part in time range to the current time of the server, which changes constantly as time passes. To avoid frequent update on the "to" parameter, we set it to "now" instead of a specific time. However, it turns out that when uses "now", Grafana does query influxdb using now() function to get the current time of the server, however,  the report shown on the client's browser uses the client's "now" timestamp as the ending time, and client side cannot see the full report.

**What you expected to happen**:
When using "now", either using server's now time to do query and show to user, or, using client's now time to do both things. Better be consistent.

**How to reproduce it (as minimally and precisely as possible)**:
Change the time on the browser side to a different time from server side's. Then set from=now-10m, to=now. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.0.0
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment]
Hi, thanks for submitting this issue. In general, it is recommended to keep the same time on the server and the client. Also if possible to use the latest version of Grafana. Maybe you can also use NTP?

A workaround that would work for Influx would probably be to set the time-range to now/s (in time range picker) as that will force client time in the query.
