### ISSUE TITLE
Backend Plugins/Toolkit: yarn build overwrites plugin executable

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#22752]
When using `yarn build` with our backend plugins, it clears the dist folder, erasing the backend executables.

This can be worked around by running the backend build second, or using yarn dev.

However, I think it would be better if yarn build didn't erase corresponding executables. So I guess that is either a change to toolkit, or we start putting the executables somewhere else.

**Comment by ryantxu** [comment]
already changed in 6.7
