### ISSUE TITLE
BarGauge: Warning in console related to field configs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#22760]
When viewing The bar gauge I get a ton these warnings

![image](https://user-images.githubusercontent.com/10999/76535583-6535c880-647b-11ea-8195-21bf90e5d9e7.png)

probably related to recent field config changes. Can't see any visual bug just these log warnings

**Comment by dprokop** [comment]
@torkelo what are the steps to repro these warnings? Just tried on master and can't see any related to overrides.

**Comment by torkelo** [comment]
strange I get it  on http://localhost:3000/d/O6f11TZWk/panel-tests-bar-gauge?orgId=1  on master right now
