### ISSUE TITLE
Add range to the legend for graph panel

### ISSUE THREAD

**Issue by fennm** [grafana/grafana#2277]
Graphs with a long time scale are often used for communicating growth of some quantity over time.  It would be great if the graph legend included an option for range (max - min) to communicate the growth of a metric over time.

**Comment by torkelo** [comment]
Currently max and min are calculated client side by grafana after the time series store performs aggregation (using avg, or min, or max function) so when you look at a long time range the min and max I the grafana legend are not both accurate, only one can be (depending on your query)
