### ISSUE TITLE
Storybook deployment

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#22774]
https://github.com/grafana/grafana/pull/22006

- [x] CircleCI for release and master merge
- [x] Github Workflows for opened PRs

__GCP settings__
- [x] Set MainPageSuffix to index.html in GCP, or setup nginx for it
- [x] Get a domain 
- [x] Document Storybook deployment versioning 
  - master deployment -> `canary` https://storage.googleapis.com/grafana-storybook/canary/index.html
  - ~beta deployment -> `next` https://storage.googleapis.com/grafana-storybook/next/index.html~ (Refer to canary instead)
  - stable release deployment -> `latest` (https://storage.googleapis.com/grafana-storybook/latest/index.html)

**Comment by dprokop** [comment]
@tskarhed is there anything else here you want do to or should we consider this done? 🥳

**Comment by tskarhed** [comment]
Just gotta make sure that the new bucket is public and that the MainPageSuffix works correctly.

**Comment by dprokop** [comment]
Cool, merged your bucker PR few minutes ago

**Comment by tskarhed** [comment]
Everything looks good now! We just need to verify the release.
https://developers.grafana.com/ui/canary/index.html
