### ISSUE TITLE
Feature to add comment to a dashboard or enable show of update history like git

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#22793]
**What would you like to be added**:
Give Grafana some kind of social network features to gather comments from users. Look like a version of App communicated by dashboards similar with Instagram by pictures but the key difference is that dashboards are for business data show not social activities only. Comments is used for a public and open site to collect user requirements and optimizations. This will bring much more functionalities, comment spamfor instance, to be considered and perhaps this is not a mature idea and I just put it here for further thinking and talking.
**Why is this needed**:
Dashboard comment or enable show of update history log like git to code

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
