### ISSUE TITLE
Explore: Loki limits is randomly changing

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#22791]
**What happened**:

From one request to another the limit seems to be changing.

**What you expected to happen**:

1k limit all the time.

**How to reproduce it (as minimally and precisely as possible)**:

Send multiple loki request in explore and check the limit sent.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/1053421/76665030-bec1f400-655c-11ea-994b-1ab7d8615006.png)

**Environment**:
- Grafana version: Grafana v6.7.0-04918709pre (6b61c65b58)
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins
- Others:

/cc @davkal seems like a bad one.

**Comment by cyriltovena** [comment]
Adding more info as @Estrax suggested.

When testing on a new browser like Safari it doesn't happens. However clearing cache and full reload doesn't help on Chrome.

I'm on MacOS boo !

**Comment by aocenas** [comment]
@cyriltovena and did you change the line limit in the UI somewhere at some point or are those numbers random? I wonder if there could be some code that keeps old values of the limit around somewhere after you change it.

**Comment by cyriltovena** [comment]
They are random, somehow I just refreshed and got another number.

**Comment by Estrax** [comment]
Tried to replicate that yesterday under linux, but at the end it all worked properly. Asked @ivanahuckova (thanks for your help!) to check it under macOS and also tried it today with a clean install of macOS 10.15 (Catalina) and Chrome 80.0.3987.132, but both of these tries also ended up with everything working well. I guess it's something unrelated to Grafana.

@cyriltovena don't hesitate to ping me anytime you notice it. We'll try to debug it then again.
Anyway, let's try one more thing. Can you please remove Chrome completely from your OS, then install it again and check if it still happens?

**Comment by cyriltovena** [comment]
I debugged that code a bit

https://github.com/grafana/grafana/blob/b51e28bc157041c4e0ba6015379763c4e748eb94/public/app/plugins/datasource/loki/datasource.ts#L280

options.maxDataPoints is random here and cause it to be used as limit. I couldn't trace back who set this.

![image](https://user-images.githubusercontent.com/1053421/76983781-584e2480-6914-11ea-9570-fc87f1f359ca.png)

**Comment by cyriltovena** [comment]
I'm actually getting the width of the window falling into this case:

```
      maxDataPoints: mode === ExploreMode.Logs && datasourceInstance.name === 'Loki' ? undefined : containerWidth,

```

here 
https://github.com/grafana/grafana/blob/master/public/app/features/explore/state/actions.ts#L448

**Comment by cyriltovena** [comment]
What is this `datasourceInstance.name === 'Loki'` ? That doesn't seem right.

**Comment by cyriltovena** [comment]
Alright sending a PR. I see what's going on there.
