### ISSUE TITLE
When will the official version of 6.7.0 be released?

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#22798]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Closing since this is not an issue, please post such questions in our community [forums](https://community.grafana.com/) or [Slack](http://slack.raintank.io/).
