### ISSUE TITLE
Number of Total Characters in Tags used for Dashboard

### ISSUE THREAD

**Issue by MaximKipot** [grafana/grafana#22804]
Good day,
total number of characters through all tags used for one dashboard is limited in the way that it creates undesired readability issues.

**What happened**:
there is no usable way to have a freedom of creating any number of tags for a dashboard.

**What you expected to happen**:
I expect to be able to create several tags with a combination of longer words (especially in German language words are combined together and create a longer character chain) and not to worry that within dashboard search area they will be all visible and the dashboard name would be readable.

**How to reproduce it (as minimally and precisely as possible)**:
Enter a long name for a dashboard (around 30 chars) and add 5-7 Tags to it averaging with about 10 chars each.
<img width="901" alt="Screenshot 2020-03-16 at 13 06 38" src="https://user-images.githubusercontent.com/1902515/76757099-4b4ffa80-6787-11ea-9c90-d36f3b74a2f0.png">

**Expected Result**
<img width="783" alt="Screenshot 2020-03-16 at 13 06 10" src="https://user-images.githubusercontent.com/1902515/76757148-6458ab80-6787-11ea-9a53-39d907f86686.png">

**Anything else we need to know?**:
These changes to code make it happen:
```
.search-item {
  align-items: center;
  height: auto;
  min-height: 37px;
  white-space: initial;
}

.search-item__tags {
  display: flex;
  flex: 1 1 auto;
  flex-wrap: wrap;
  justify-content: flex-end;
  margin-top: -2px;
}

.search-results-container .label-tag {
  margin-top: 2px;
}
```

**Environment**:
- Grafana version: 6.7.0-pre
- Data source type & version: Simple Streaming Example demo 
- OS Grafana is installed on: MAC OS
- User OS & Browser: Chrome, Firefox

**Comment by dprokop** [comment]
@MaximKipot thanks for reporting this, do you mind opening a PR with proposed changes?
