### ISSUE TITLE
Strange behaviour of `increase` function: "wave" signal instead of constant line.

### ISSUE THREAD

**Issue by r00ta** [grafana/grafana#22801]
**What happened**: I'm using a prometheus counter + grafana, and after collecting some minutes of data I've stopped increasing the counter and I've left it as it was for some minutes. With the following query (stat panel): 
```
sum(increase(api_http_response_code{endpoint="world"}[1d]))
```
and the counter: 
```
api_http_response_code{endpoint="world",identifier="200",} 1055.0
```
there are some strange "waves" on the graph. I expected to see just a constant line, because my counter is not changing value. See below the screenshot: 

![Screenshot from 2020-03-16 11-51-18](https://user-images.githubusercontent.com/18282531/76749294-96184500-677c-11ea-8d6d-40c8622515c0.png)

**What you expected to happen**: Constant line, and not a wave because the metric has not changed

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a prometheus counter like `api_http_response_code{endpoint="world",identifier="200",} 1055.0`
2. Create a simple stat with the query: `sum(increase(api_http_response_code{endpoint="world"}[1d]))`
3. After some minutes the constant line turns into a wave.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus 2.8.0
- OS Grafana is installed on: grafana container `grafana/grafana:6.6.1`
- User OS & Browser: RHEL 8.0, Chrome 80.0.3987.122 (Official Build) (64-bit)
- Grafana plugins: None
- Others:

**Comment by hugohaggmark** [comment]
@r00ta very late on the game here but are you still experiencing this issue. If you do can I please bother you to share the Query Inspector data? panel -> inspect -> query
![image](https://user-images.githubusercontent.com/562238/97404854-08e2c480-18f7-11eb-9478-2ac5a7e28c96.png)

**Comment by zoltanbedi** [comment]
I've tried to reproduce it but couldn't also there are no new answers so I'm going to close this. If this is still an issue we can reopen this.
