### ISSUE TITLE
Auth Proxy protect root url

### ISSUE THREAD

**Issue by RamanPndy** [grafana/grafana#22807]
**What happened**:
I've enabled auth proxy in grafana and running grafana behind Nginx. One dashboard I've created which I'm embedding in HTML. I've also created one user which is being authenticated at the Nginx side. below in my Nginx Config:
worker_processes 1;

events { worker_connections 20000; }

http {
log_format compression '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $upstream_addr '
        '"$http_referer" "$http_user_agent" "$gzip_ratio"';
resolver       8.8.8.8 8.8.4.4 ;
server {
    listen 80 ;
    large_client_header_buffers 4 64k;

    location  ~ ^/grafana/(d|d-solo)/(.*){
       auth_request      /validatetoken;

       proxy_set_header  X-Real-IP $remote_addr;
       proxy_set_header  X-Forwarded-Proto http;

       proxy_pass http://grafana.cloud.test.com;
       proxy_set_header Authorization "";
    }

    location = /validatetoken {
        internal;
        set $token '';
        if ($request_uri ~* "([^&]*$)" ) {
          set  $token  $1;
        }
        proxy_pass        http://backendapp.cloud.test.com/validatetoken?$token;
        proxy_pass_request_body off;
        proxy_set_header X-Original-URI $request_uri;
    }

    location  /grafana {
        set $grafana_user "raman";
        proxy_pass         http://grafana.cloud.test.com/;
        proxy_set_header   X-WEBAUTH-USER $grafana_user;
        proxy_set_header   Authorization "";
     }
  }
}

below is grafana config:
#################################### Server ##############################
[server]
# Protocol (http, https, h2, socket)
protocol = http

# The public facing domain name used to access grafana from a browser
domain = reverseproxy.cloud.pcftest.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false

# The full public facing url
root_url = http://reverseproxy.cloud.test.com/grafana

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = false

# Log web requests
router_logging = ture

# the path relative working path
static_root_path = public

# enable gzip
enable_gzip = true

# https certs & key file
cert_file =
cert_key =

# Unix socket path
socket = /tmp/grafana.sock
#################################### Anonymous Auth ######################
[auth.anonymous]
# enable anonymous access
enabled = false

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

# specify role for unauthenticated users
org_role = Viewer

#################################### Basic Auth ##########################
[auth.basic]
enabled = true

#################################### Auth Proxy ##########################
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = false
# Deprecated, use sync_ttl instead
ldap_sync_ttl = 60
sync_ttl = 60
whitelist =
headers =
enable_login_token = true

I'm accessing my dashboard with url:
http://reverseproxy.cloud.test.com/grafana/d/QfbI3XUZk/sample-dashboard?orgId=1&var-orgid=00776ca5-2ef8-14dc19cebcc3&theme=light&kiosk&from=now-7d&to=now&token=MTU4NDM1OTEzNTo2YWQ3YzQ2YmNkY2I3NDllYzE0MWVlYzQ3MjYwZjA2Ng==

which is working fine and I'm able to view dashboard in Grafana.

but I want to block the URL http://reverseproxy.cloud.pcftest.com/grafana

so that on this one user should see Grafana login page.

**What you expected to happen**:
Grafana login page should be opened on direct access of  http://reverseproxy.cloud.pcftest.com/grafana instead of Grafana Home Dashboard with the logged in User. I want to access dashboard only through iframe.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Is this something you could implement through Nginx configuration instead? It sounds that way to me.

**Comment by torkelo** [comment]
Yes, this is nginx config issue.

Be aware that if you can access grafana both via auth proxy and directly it's a big security hole as anyone can spoof the headers. Use the whitelist to specify the nginx IP. 

Be also aware that if you expose Just a single dashboard your still exposing your data sources. A single dashboard can still access all data sources in an org and issue any query. Even a user with Viewer role can issue any posssible query (as dashboards and queries are very dynamic)

**Comment by RamanPndy** [comment]
@torkelo  Thank you for your suggestion.

can you please suggest what modifications I need to do in Nginx configuration to make it secure??

**Comment by aknuds1** [comment]
It'd probably be better to ask for help with that in an nginx forum.
