### ISSUE TITLE
Graph Not loading all Data even when available

### ISSUE THREAD

**Issue by parth2014** [grafana/grafana#22816]
I have MSSQL data source for a time-series graph. Upon loading data in Grafana via time series query, it only portion of data and last 8 hours of data does not get loaded. My grafana server and DB are in PST.
![image](https://user-images.githubusercontent.com/11760533/76785378-914e9380-6772-11ea-9d14-c80c36a2c979.png)
![image](https://user-images.githubusercontent.com/11760533/76785395-9a3f6500-6772-11ea-8cfb-3e7b1b023878.png)

**Comment by torkelo** [comment]
make sure the data your reading is in UTC, if not convert it to UTC 

Try using the different macros: https://grafana.com/docs/grafana/latest/features/datasources/mssql/#macros

**Comment by parth2014** [comment]
I convert it to UTC but did not work
