### ISSUE TITLE
Only first 25 metrics returned in OpenTSDB template

### ISSUE THREAD

**Issue by gcormier9** [grafana/grafana#2281]
If using metrics() in an OpenTSDB template, only the first 25 metrics are returned.
http://opentsdb.net/docs/build/html/api_http/suggest.html

Not sure how this can be fixed. I am thinking to either add the "max" parameter to the OpenTSDB query to increase the number or to add typeahead functionality to the textbox used to select the variable value (once it is created).

**Comment by torkelo** [comment]
interesting, maybe set max to to 1000 ?

**Comment by gcormier9** [comment]
That would work for me!
