### ISSUE TITLE
Accessibility: Drag handle accessibility and usability

### ISSUE THREAD

**Issue by MaximKipot** [grafana/grafana#22817]
A drag handle on a grid item which appears on hover is visible and accessible in terms of contrast colors only if a corresponding bg color of a grid item is provided.

**Steps to reproduce**:
hover with a mouse over any grid item / panel in the main area of the interface.

**Actual Result**:
<img width="195" alt="Screenshot 2020-03-16 at 19 36 12" src="https://user-images.githubusercontent.com/1902515/76789904-1dd27380-67be-11ea-813e-bf4179ed87c6.png">
<img width="173" alt="Screenshot 2020-03-16 at 15 59 56" src="https://user-images.githubusercontent.com/1902515/76789908-1f03a080-67be-11ea-9ee4-f30803f7be71.png">

**Expected Result**
<img width="179" alt="Screenshot 2020-03-16 at 19 37 51" src="https://user-images.githubusercontent.com/1902515/76789933-288d0880-67be-11ea-8478-51fcd022cdf3.png">
<img width="134" alt="Screenshot 2020-03-16 at 19 37 25" src="https://user-images.githubusercontent.com/1902515/76789935-29259f00-67be-11ea-8352-9d1e28f0ab84.png">
<img width="219" alt="Screenshot 2020-03-16 at 19 37 02" src="https://user-images.githubusercontent.com/1902515/76789938-29be3580-67be-11ea-9268-5adc6ac22e0f.png">

The implementation would look like:

```
.theme-dark {
  .react-grid-item > .react-resizable-handle::after {
    border-right-color: #989898;
    border-bottom-color: #989898;
    width: 10px;
    height: 10px;
  }
  .react-grid-item > .react-resizable-handle {
    width: 24px;
    height: 24px;
    background: linear-gradient(
        to bottom right,
        transparent 0%,
        transparent 50%,
        lighten($panel-corner, 6%) 50%,
        lighten($panel-corner, 6%) 100%
    );
  }
}

```

**Relevant WCAG Criteria:** 
[1.4.3 WCAG Criterion](link to https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast)

**Environment**:
- Grafana version: 6.7.0-pre
- Data source type & version: TestData DB coming with Simple dummy streaming example
- User OS & Browser: MacOS Mojave, Mozilla and Chrome

**Comment by torkelo** [comment]
good suggestion!

**Comment by MaximKipot** [comment]
Same goes for light theme:

```
.theme-light {
  .react-grid-item > .react-resizable-handle::after {
    border-right-color: #606268;
    border-bottom-color: #606268;
  }
  .react-grid-item > .react-resizable-handle {
    background: linear-gradient(
      to bottom right,
      transparent 0%,
      transparent 50%,
      lighten($panel-corner, 6%) 50%,
      lighten($panel-corner, 6%) 100%
    );
  }
}
```

Colors used to depict a handle triangle are having enough contrast to be accessible
