### ISSUE TITLE
Check availability of data source before adding it

### ISSUE THREAD

**Issue by maticmeznar** [grafana/grafana#2282]
As far as I can tell, Grafana doesn't check/try to connect to a data source when a user adds it. There is no way of knowing whether the entered data source details are correct and working. Perhaps there could be an indicator on the list of data sources showing whether a data source is available (connectable) or not. It could save people are of time when they enter incorrect data source details or when a data source is unavailable.

**Comment by torkelo** [comment]
A "Test connection" button is added in master already :) 
https://github.com/grafana/grafana/issues/1997

**Comment by maticmeznar** [comment]
Awesome, thanks! :)
