### ISSUE TITLE
Graph: fill previous not null

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#22834]
**What would you like to be added**:
Option for the graph to fill previous not null. If the last value is older than selected timerange, the graph fills with 0 (null).

![image](https://user-images.githubusercontent.com/19311511/76844055-08505e80-683d-11ea-8c89-ae8be58f6940.png)
In this situation I send status once every 24h at midnight. The graph is ok after midnight, but before midnight it shows 0 even though last value was 1 (this value was sent to database more than 24h ago, so it is older than selected timerange)

**Why is this needed**:
In my view better option will be to fill with the last value even if it is older than the selected timerange.

**Comment by xlson** [comment]
Thanks for suggesting this feature. While I understand the problem, I don't think we can easily solve this in Grafana as it would mean asking for more data in the past to be able to figure out the last set value. For us to be able to support this it would probably have to be a feature in your data source.
