### ISSUE TITLE
Pseudo-variable that sets multiple hidden variable values

### ISSUE THREAD

**Issue by pcroc** [grafana/grafana#22835]
**What would you like to be added**:

I'd like to be able to have a variable drop-down on a dashboard which, when selected, sets the values of multiple "hidden" variables. For example, I could create a variable called Environment with values Development, Staging, Production, when chosen this would set the values of hidden variables $rabbitmq_host, $ecs_cluster_name, $account_prefix, etc.

**Why is this needed**:

This would allows me, with a single selection, view data from multiple sources which use completely different tagging/naming schemes, without needing to select (and understand) the different variables used in each part of the system.

**Comment by dhohengassner** [comment]
was searching for the exact same feature - is it planned to add that?  
Thanks!

**Comment by philomory** [comment]
If you have an InfluxDB data source you can already do this with Flux; you'd create a query variable named `rabbitmq_host` and give it a query like
```
import "experimental/array"
host = if "${Environment}" == "Development" then "host1"
           else if "${Environment}" == "Staging" then "host2"
           else "host3"
array.from(rows: [{_value: host}])
```
Then you hide the new dependent variable.

Mind this is tedious to set up, results in unnecessary round-trips to the datasource, and only works for InfluxDB 2 (or any other datasource with a similarly capable query language). But, it at least gives an idea of what it might look like.
