### ISSUE TITLE
Can't save some dashboards

### ISSUE THREAD

**Issue by deric** [grafana/grafana#2284]
I'm using 2.1-pre1 (`"buildstamp":1435929186,"commit":"v2.0.2+460-gfc81cda","version":"2.1.0-pre1"`) and some dashboards can't be updated, the POST request just timeouts and return an "Unexpected error".

I wasn't able to find any relevant information in the backend log. I'm not sure if the log level settings does apply, with `Trace` debug level there not much information in the log.

I can send the whole request if it could be helpful. It does not apply for all dashboards.

**Comment by torkelo** [comment]
that is strange, what database to do you use? Sqlite3? Can you replicate it consistently? Please put the whole request in a gist or something similar and I will try to replicate it.
