### ISSUE TITLE
Improve error message when saving a dashboard with an alert tag value longer than 100 characters

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#22853]
# Summary

1. Use a Grafana instance with a mysql or postgresql backend database type (the bug doesn't happen on sqlite3).
1. Import the dashboard [alert-tag-value-100-characters-length-limit.json](https://github.com/grafana/grafana/files/4344629/alert-tag-value-100-characters-length-limit.zip) (zipped).
1. Select the TestData DB data source.
1. Save the dashboard again.

Frontend displays Failed to save dashboard.

![screenshot 2020-03-17 1251](https://user-images.githubusercontent.com/3270755/76880463-1490e780-684e-11ea-844a-9b7d2952af0f.png)

On the server, got this error message:

> t=2020-03-17T16:51:18+0000 lvl=eror msg="Request Completed" logger=context userId=8 orgId=1 uname=adeverteuil method=POST path=/api/dashboards/db/ **status=500** remote_addr=107.159.102.235 time_ms=49 size=38 referer="https://alex4lyfe.grafana.net/d/WGHvAHuWk/alert-tag-value-100-characters-length-limit?orgId=1"	
> t=2020-03-17T16:51:18+0000 lvl=eror msg="Failed to save dashboard" logger=context userId=8 orgId=1 uname=adeverteuil **error="Error 1406: Data too long for column 'value' at row 1"** 

# Research

It looks like a database validation error. It seems to be coming from MySQL. I tested with a local instance of Grafana with the Sqlite3 database and I couldn't reproduce the issue.

I opened the Sqlite3 database and looked at all the table schemas. Only the tag table has a 'value' column (other tables use 'data', or some other name, but not 'value').
It seems to be storing alert tags.

This is the definition of the tag model in Go:
https://github.com/grafana/grafana/blob/master/pkg/models/tags.go
There's an ORM (object-relational mapper) in Grafana, so:
https://github.com/grafana/grafana/tree/master/vendor/github.com/go-xorm/xorm ← ORM library we use
https://github.com/go-sql-driver/mysql/blob/master/fields.go ← data type conversions in the MySQL driver

Looks like strings get stored in BINARY or CHAR, which have a length fixed in the table schema.

Found the database migration code that tells the ORM how to create the tag table:
https://github.com/grafana/grafana/blob/7b70e7db2d4059efb89ce6e9b5429360ddcef3f8/pkg/services/sqlstore/migrations/tag_mig.go

The column length is 100. I was able to reproduce the issue with the dashboard model attached. It has 1 panel and 1 alert with a tag value that is 101 characters long.

The SQLite3 documentation explains why the problem doesn't happen with SQLite: https://www.sqlite.org/datatype3.html

> SQLite does not impose any length restrictions (other than the large global SQLITE_MAX_LENGTH limit) on the length of strings, BLOBs or numeric values.

# Steps to reproduce the problem

The sample dashboard I provided above has an alert with a tag with a value that is 101 characters long.

![screenshot 2020-03-17 1257](https://user-images.githubusercontent.com/3270755/76881077-00011f00-684f-11ea-8995-a54e2f7d7015.png)

```
…
  "panels": [
    {
      "alert": {
        "alertRuleTags": {
          "test": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        },
        "conditions": [
…
```

# What you expected to happen

a) A more helpful error message on the frontend and in the logs.
b) Support for longer tag values if the use-case described in the next section makes sense.

# Anything else we need to know?

This bug was reported to Grafana Labs support from a Grafana Enterprise customer.

> I was hoping to put in URLs for the labels to add more flavor to the alert. I’ll just add them into the alert body.  

One of their URLs was more than 100 characters long and tripped the database validation.

# Environment
- Grafana version: 6.6.2
- Data source type & version: n/a
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser:
- Grafana plugins:
- Others: MySQL database

**Comment by marefr** [comment]
Think adding some validation of this in the backend could be a quick fix.

**Comment by marefr** [comment]
Code wise I'm not sure where this should go, but the following are potential places to start looking:
https://github.com/grafana/grafana/blob/6e5d349ae801fb4adf119e0a1452f6bd4e1dfcd1/pkg/services/alerting/extractor.go#L243
https://github.com/grafana/grafana/blob/6e5d349ae801fb4adf119e0a1452f6bd4e1dfcd1/pkg/models/alert.go#L91-L93

Potentially returning an error from this one could also be interesting to investigate:
https://github.com/grafana/grafana/blob/6e5d349ae801fb4adf119e0a1452f6bd4e1dfcd1/pkg/models/alert.go#L115-L128

**Comment by idafurjes** [comment]
Couldn't reproduce the issue on version 8.
