### ISSUE TITLE
Reopen #9852: Unable to get data for CWAgent even when specifying all dimensions

### ISSUE THREAD

**Issue by jpfreeley** [grafana/grafana#22855]
**What happened**: Tried to add CWAgent disk_used_percent metric

**What you expected to happen**: Data in graph

**How to reproduce it (as minimally and precisely as possible)**: Add custom metric namespace, CWAgent, add metric disk_used_percent, add all dimensions from list-metrics cli output

**Anything else we need to know?**: Works fine from command line, other AWS/* graphs are loading fine. 

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: MacOS Firefox 74
- Grafana plugins:
- Others: Issue Ref: #9852, #9856, #19643

**Comment by aknuds1** [comment]
Does this happen with the latest version, i.e. 6.6.2?

**Comment by jpfreeley** [comment]
6.6.2 seems to have refined this significantly and I can now get my CWAgent data and proper pulldown values. Thanks!
