### ISSUE TITLE
Template Variable values and text

### ISSUE THREAD

**Issue by balakaushik** [grafana/grafana#2285]
Would appreciate if you can add something like the following to support user defined text for the tempalte variables with different value corresponding to the text rather than deriving the value from the text.  In file public/app/features/templating/templateValueSrv.js in the _updateNonQueryVariable function:
      // if the options are specified then use it
      if (variable.options) {
          if (variable.includeAll) {
              self.addAllOption(variable);
          }
          return variable.options;
      } else {
          // extract options in comma seperated string
          variable.options = _.map(variable.query.split(/[,]+/), function (text) {
              return { text: text.trim(), value: text.trim() };
          });
      }

**Comment by torkelo** [comment]
Maybe for the `custom` variable type.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1032
