### ISSUE TITLE
"Origin" header missing on direct requests

### ISSUE THREAD

**Issue by garrettheel** [grafana/grafana#22869]
**What happened**:

Upgrading to a [recent version](https://github.com/grafana/grafana/tree/2bed1bc2e71212fe0357ecb13a8060d6ac6cd4d5) caused issues with one of our plugins, since we rely on the `Origin` header being sent on HTTP requests to set the appropriate CORS headers. The plugin is making a GET request via `backendSrv.datasourceRequest(...` 

**What you expected to happen**:

I expect the `Origin` header to be present on these requests when the datasource access is configured as "direct" (browser makes the request).

**How to reproduce it (as minimally and precisely as possible)**:

Use `backendSrv.datasourceRequest()` to make a GET request with a datasource configured to be direct

- Grafana version: 2bed1bc
- Old working version: bcac76f5d

**Comment by aknuds1** [comment]
Thanks for reporting this issue, we're looking into it.

**Comment by hugohaggmark** [comment]
@garrettheel thanks for reporting this but I will need more information about the plugin you're running? Could you please supply details in the format below:
Environment:

Grafana version:
Data source type & version:
OS Grafana is installed on:
User OS & Browser:
Grafana plugins:

**Comment by hugohaggmark** [comment]
So I've looked into this. There some major changes done to backend_srv but I really can't find any Origin header related changes. Without more information about the plugin used, I tried:

1. I downloaded, installed and ran https://github.com/bergquist/fake-simple-json-datasource and made sure that I console.log the request headers.
2. Created a dashboard that using https://github.com/grafana/simple-json-datasource as the data source and configured it to use `Browser` (direct) and pointed it to my localhost:3333 running https://github.com/bergquist/fake-simple-json-datasource

These are the console.log outputs from various git commits:

**`e0a2d4beacc379def0878655b3a3f7cceffbf3fc`**
{
  host: 'localhost:3333',
  connection: 'keep-alive',
  'content-length': '484',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  accept: 'application/json, text/plain, */*',
  'sec-fetch-dest': 'empty',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 ' +
    'Safari/537.36',
  'content-type': 'application/json',
  origin: 'http://localhost:3000',
  'sec-fetch-site': 'same-site',
  'sec-fetch-mode': 'cors',
  referer: 'http://localhost:3000/d/4k_SOXuWz/22869?orgId=1',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'sv,en-GB;q=0.9,en-US;q=0.8,en;q=0.7'
}

**`bcac76f5d4685aa8710d4e8e1fecb577b7760a71`**
{
  host: 'localhost:3333',
  connection: 'keep-alive',
  'content-length': '502',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  accept: 'application/json, text/plain, */*',
  'sec-fetch-dest': 'empty',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 ' +
    'Safari/537.36',
  'content-type': 'application/json',
  origin: 'http://localhost:3000',
  'sec-fetch-site': 'same-site',
  'sec-fetch-mode': 'cors',
  referer: 'http://localhost:3000/d/4k_SOXuWz/22869?orgId=1',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'sv,en-GB;q=0.9,en-US;q=0.8,en;q=0.7'
}

**`2bed1bc2e71212fe0357ecb13a8060d6ac6cd4d5`**
{
  host: 'localhost:3333',
  connection: 'keep-alive',
  'content-length': '516',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  accept: 'application/json, text/plain, */*',
  'sec-fetch-dest': 'empty',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 ' +
    'Safari/537.36',
  'content-type': 'application/json',
  origin: 'http://localhost:3000',
  'sec-fetch-site': 'same-site',
  'sec-fetch-mode': 'cors',
  referer: 'http://localhost:3000/d/4k_SOXuWz/22869?orgId=1',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'sv,en-GB;q=0.9,en-US;q=0.8,en;q=0.7'
}

Unfortunately I can't see that the Origin header is missing in any of these outputs, so I'm probably doing something wrong. @garrettheel  any help investigating this further would be very appreciated.

**Comment by hugohaggmark** [comment]
I forgot to mention that I'm using Chrome on MacOs and Grafana is installed on the same machine.

**Comment by hugohaggmark** [comment]
After rereading the issue, I can see that the issue is with `GET` requests, so I'm looking into this again now.

**Comment by hugohaggmark** [comment]
So I tried the same setup as above but I used `test data source` function on the data source settings page to use a `GET` request instead. I still get an `Origin` header in the request:
```
GET / HTTP/1.1
Host: localhost:3333
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
accept: application/json, text/plain, */*
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
content-type: application/json
Origin: http://localhost:3000
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: http://localhost:3000/datasources/edit/29/
Accept-Encoding: gzip, deflate, br
Accept-Language: sv,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
```

It could relate to the notice here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin which states that Origin header isn't set on `fetch` requests without cors set. We're using `fetch` now because we are migrating away from Angular. 
![image](https://user-images.githubusercontent.com/562238/77040492-4faf2a00-69b8-11ea-9a4a-eaa34afab2ef.png)

More information here: 
https://github.com/whatwg/fetch/issues/871
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Syntax
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
https://bugzilla.mozilla.org/show_bug.cgi?id=1508661

Does your plugin set `cors`?

**Comment by garrettheel** [comment]
@hugohaggmark thanks for looking into this so far.

> are you running Grafana directly from master or are you using released versions?

I'm testing with builds from the specific commits that I mentioned in the original issue.

> Could you please supply details in the format below:

Grafana version: 2bed1bc
Data source type & version: This is a custom plugin that is not publicly available
OS Grafana is installed on: Linux 5.5.8-100.fc30.x86_64
User OS & Browser: OSX 10.14 / Chrome 80.0.3987.149
Grafana plugins: Just the custom plugin

---

The main difference I could see is that my test is making a GET request to a different hostname. Thanks for sharing the change to use `fetch`, I'll do some more investigation on my side around that.

**Comment by garrettheel** [comment]
I did some playing around, and I think it's because `Content-Type: application/json` is now being added as a header.

```javascript
// works - origin header is included
fetch(new Request('https://myhost/blah?foo=bar', {method: 'GET'));

// does not work - no origin
fetch(new Request('https://myhost/blah?foo=bar', {method: 'GET', headers: {'content-type': 'application/json'}));
```

**Comment by marefr** [comment]
@garrettheel thanks. 

@hugohaggmark this doesn't make sense for GET-requests https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L605

**Comment by hugohaggmark** [comment]
> @garrettheel thanks.
> 
> @hugohaggmark this doesn't make sense for GET-requests https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L605

@garrettheel  thanks for taking the time to help out investigating this. @marefr you're right, will have a look.

**Comment by garrettheel** [comment]
Thanks everyone, confirming that this fixed my issue!

**Comment by hugohaggmark** [comment]
> Thanks everyone, confirming that this fixed my issue!

I'm very glad that helped you @garrettheel !
