### ISSUE TITLE
Annotations with Relative time

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#22860]
**What happened**:
When using Relative time set to 14d in a Graph and Time Range is set to 6h the annotation that was inserted 5 days ago is not showing up.
**What you expected to happen**:
To see annotation
**How to reproduce it (as minimally and precisely as possible)**:
Create a graph, set Relative time to 14d and set Time range to 14d, create an annotation in the dgraph that has date as 5 days ago, now change time range to less then 5 days eg. 2d, the annotation is not showing up.
**Anything else we need to know?**:
It seems to be that annotation is using Time Range instead of Relative time
**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Influx latest version
- OS Grafana is installed on: Debian 10
- User OS & Browser: Chrome, windows 10

**Comment by jongyllen** [comment]
Hi, Currently annotations are global for the whole dashboard so only use the dashboard time range.

There is an [existing](https://github.com/grafana/grafana/issues/10805) feature request to support this.
