### ISSUE TITLE
News Panel: Add Ability to Restrict Description Length

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#22878]
**What would you like to be added**:
The ability to ellipsize the article description in the news panel after some length e.g. in lines.

**Why is this needed**:
Many RSS feeds put a lot of text into the description. Since the news panel strips formatting such as newlines, this ends up as a huge illegible blob of text that hides other content.

**Comment by rakeshraih** [comment]
Can I take this one?

**Comment by pkolyvas** [comment]
Issue is still up for grabs!
