### ISSUE TITLE
Timezone Mixup

### ISSUE THREAD

**Issue by Ravenmujitsuno** [grafana/grafana#22888]
What Grafana version are you using?
6.6.2

What datasource are you using?
PostgreSQL

What OS are you running grafana on?
windows 10

What did you do?
I just want to see the last xx hours correctly. In my Dashboard I have a Graph which should show me the information from a PostgreSQL Database. 

What was the expected result?
Corect information on the correct timeline within the last 1 hour.

What happened instead?
At first it showed the values correctly in the graph but the x axis but an hour late (I am in UTC+1). Then I changed the browser to use UTC. Now I am getting the correct values in the correct time. But now I can't see the missing last hour becuase the last hour is now -2 hours to -1 hours.

It's an default query: 
SELECT
  timedate AS "time",
  "Value"
FROM sp_temp
WHERE
  $__timeFilter(timedate)
ORDER BY 1

After searching for an answer I found out that the software which is adding data to the PostgreSQL Database is completly programmed wrong. They are using the date and time incl the timezone (in this example its now 10am incl UTC+1) and they write it into the column timedate which is a datatyp "timestamp wthout time zone". So the database has now the information it's 10am without UTC+1.

Any idea how change the query, so that it asks for UTC Values but shows it as UTC+1 incl. the last 1 hour information (and not the information between -2 to -1)?

**Comment by aknuds1** [comment]
Hi - please rewrite the issue using our standard issue template, thanks!

**Comment by Ravenmujitsuno** [comment]
After founding the standard issue template, it seems to be the wrong place for my issue, because I don't think it's an grafana bug. It's more a 3rd party software which is filling a postgre database in a wrong way. I'll try it in the forum of gravana.
