### ISSUE TITLE
Transforms: Transforms strings to numbers so that they can be sorted as numbers & thresholds applied  

### ISSUE THREAD

**Issue by bryanyork** [grafana/grafana#22887]
**What would you like to be added**:
Would be great to be able to convert label values from Strings to Numerical values to allow to sort by numbers.
**Why is this needed**:
When I use the table panel and sort by numbers they are not sorted numerically as they are treated as strings.

Can be solved using the new transforms feature added in 7.0. Using a new transform to parse field values and turn them into numbers.

**Comment by bryanyork** [comment]
![image](https://user-images.githubusercontent.com/1418151/77049845-0a720480-6986-11ea-849a-77d494460fae.png)

**Comment by jongyllen** [comment]
Hi, thanks for submitting this.

A question: Have you set the column type to "number" in Visualisation -> Column styles as per https://grafana.com/docs/grafana/latest/features/panels/table_panel/#column-styles ?

**Comment by bryanyork** [comment]
Hi @jongyllen unfortunately that does not fix the issue for me:

![image](https://user-images.githubusercontent.com/1418151/77985261-d32a1e80-72c8-11ea-8b14-bfd2baea4f83.png)

**Comment by jongyllen** [comment]
Hi, just a question - from the screenshot it looks like the "Channel" column is sorted numerically, is it messed up further down? Maybe you can screenshot where the actual out of ordering happens?

**Comment by bryanyork** [comment]
Another example:
![image](https://user-images.githubusercontent.com/1418151/79058328-7a8c4700-7c21-11ea-881b-d045c7382c52.png)

**Comment by nileshdt2000** [comment]
This will be a good feature to have in Grafana.Is there any plan to take this on Priority ?

**Comment by bmerry** [comment]
> Below workaround is available for converting strings to numbers and sort them. First do "Add field from Calculations." for your string column. You can convert it into number by doing "* by 1". Then do "Add Transformation and select " Organize Fields" and then you can hide Original Column.(String)

The latest versions of Grafana have a "Convert field type" transformation that can be used instead of this workaround.

**Comment by bryanyork** [comment]
Yes I believe the latest version has this feature now

**Comment by jdmarshall** [comment]
Convert Field type doesn't allow you to pick a label, it just lists all of the results from your query.  I've no idea what this is intended to accomplish.
