### ISSUE TITLE
More granular "Explore" permissions

### ISSUE THREAD

**Issue by jcmcken** [grafana/grafana#22896]
**What would you like to be added**:

The ability to enable or disable Explore based on user permissions.

Or, at the least, the ability to hide Explore for non-administrators only instead of for all users. (Similar to [this](https://community.grafana.com/t/how-do-i-hide-the-explore-and-configuration-tabs/21568))

**Why is this needed**:

Most of the consumers of our Grafana dashboards only have a 'view' role, and they don't necessarily have the technical knowledge to use "Explore" appropriately. We disable "Explore" to dissuade them from trying to customize queries (although it's not a security issue if they were to figure out how to do this). In particular, we don't want users to try to use 'Explore' and end up executing full table scans or other expensive queries accidentally.

At the same time, it's very convenient for dashboard developers or admins to have 'Explore' to more easily develop their queries or troubleshoot particular panels. So it's a shame that we have to disable it globally. The workflow of creating a panel first to explore a query is a little bit cumbersome in comparison.

**Comment by jcmcken** [comment]
Actually, looking at the code, I see that this setting actually doesn't disable Explore, it just removes it from the navbar. I guess a workaround is to just go to the /explore endpoint manually

**Comment by jongyllen** [comment]
Hi! It sound like you want explore to be available to only Admins and Editors, is that correct? 

This is the default behaviour in later versions of Grafana as far as I know. There is also a setting, https://grafana.com/docs/grafana/latest/installation/configuration/#viewers-can-edit to allow/disallow users to edit.

**Comment by jcmcken** [comment]
Thanks, I'm satisfied then. Going to close
