### ISSUE TITLE
View raw query sent over the wire?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2289]
It would be great if you could view the actual raw query being sent over the wire to InfluxDB (including any templates/variables etc.) for a given dashboard.

This would be useful when troubleshooting some issues (e.g. https://github.com/grafana/grafana/issues/2278#issuecomment-118691564)

**Comment by bergquist** [comment]
Available with http://docs.grafana.org/installation/troubleshooting/
and https://github.com/grafana/grafana/issues/7395
