### ISSUE TITLE
Unable to do Grafana Org Authorization using Azure AD

### ISSUE THREAD

**Issue by uvaisibrahim** [grafana/grafana#22897]
I am not able to MAP the Azure AD groups with Grafana Orgs with specific roles. I am using the latest Grafana version, which is 6.7.0-beta1. In LDAP, for this purpose, we do have a separate ldap.toml file and in that we can map Particular CN with Particular org_id as given below.

```
[[servers.group_mappings]]
group_dn = "CN=r_grafana_admin,OU=Roles,OU=Security,OU=Groups,DC=corporate,DC=t-test,DC=com"
org_role = "Admin"
org_id = 32
```
I need to do the same thing with Grafana-Azure AD combination also, but unfortunately, the Grafana documentation does not cover up that part. I am referring to the below link.

https://grafana.com/docs/grafana/latest/auth/generic-oauth/

**Comment by aknuds1** [comment]
If this is a support question please direct it to our community [forum](https://community.grafana.com) or [Slack](http://slack.raintank.io/). If you are reporting an issue on the other hand, please post an issue using our standard template.
