### ISSUE TITLE
Additional database tables lacking indices when deleting a dashboard

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#22890]
In relation to #22799, two additional tables are lacking indices when deleting a dashboard:
- `delete from alert_notification_state where alert_id = ?`
- `delete from alert_rule_tag where alert_id = ?`

**Comment by marefr** [comment]
Here's an example adding a new unique index for the `alert_notification_state` table:
https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/services/sqlstore/migrations/alert_mig.go#L147-L148

To fix this we need to add two new non-unique indices at the end of above file so that the database migrations are executed after all of the existing migrations.
 - New non-unique index for the `alert_notification_state` table and the column `alert_id`
 - New non-unique index for the `alert_rule_tag` table and the column `alert_id`

Example of defining a non-unique index can be seen here:
https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/services/sqlstore/migrations/alert_mig.go#L120

**Comment by KarineValenca** [comment]
Can I take this up?

**Comment by aknuds1** [comment]
@KarineValenca Sure, go ahead.
