### ISSUE TITLE
Timezone options other than browser and UTC?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2290]
Grafana has a cool feature that lets you select the timezone:

![screenshot 2015-07-06 18 09 29](https://cloud.githubusercontent.com/assets/243499/8518089/363aeaa8-240a-11e5-849a-5c793ddae57f.png)

However, the only two options are browser and UTC - would be neat if there were some other options - e.g. either some common timezones, or if that's not scalable, even a text-input field, for example.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/558
