### ISSUE TITLE
Explore: Loki in live mode is not working since 6.6.0

### ISSUE THREAD

**Issue by danieldabate** [grafana/grafana#22905]
**What happened**:
Beginning from Grafana 6.6.0 we started seeing this issue where activating Loki in live mode explodes with a generic parsing error.

`An unexpected error happened
Details
TypeError: Cannot read property 'slice' of null`

Tracing the issue we found that Loki is throwing this message: 
`msg="Error in upgrading websocket" err="websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"`

**What you expected to happen**:
Grafana working correctly with Loki in live mode

**How to reproduce it (as minimally and precisely as possible)**:
There's no particular way to reproduce the issue. Just using the Live mode for Loki with Grafana v6.6.0 or later.

**Anything else we need to know?**:
We are stuck in version 6.5.3 and have not found anything in our configuration that could fix this issue. We have an nginx correctly setup between Grafana and Loki and it has been working great until now.

Any help would be very appreciated. 

**Environment**:
- Grafana version: 6.6.0 - 6.7.0
- Data source type & version: Loki 1.2.0
- OS Grafana is installed on: K8S
- User OS & Browser: Mac in all browsers
- Grafana plugins: None
- Others: None

**Comment by aknuds1** [comment]
Do you mind rewriting the issue to abide by our standard issue template?

**Comment by danieldabate** [comment]
I used the issue template, I just deleted some of the parts that I don't think that apply to this issue. But I will add them. Thanks for the help.

**Comment by quanterion** [comment]
Have the same error.
Call stack is:

> react-dom.production.min.js:196 TypeError: Cannot read property 'slice' of null
>     at t.n.rowsToRender (LiveLogs.tsx:132)
>     at t.value (LiveLogs.tsx:151)
>     at Ka (react-dom.production.min.js:181)
>     at Xa (react-dom.production.min.js:180)
>     at Ou (react-dom.production.min.js:261)
>     at vs (react-dom.production.min.js:230)
>     at ps (react-dom.production.min.js:229)
>     at os (react-dom.production.min.js:223)
>     at react-dom.production.min.js:121
>     at e.unstable_runWithPriority (scheduler.production.min.js:18)

**Comment by cordula-grau** [comment]
Same issue here, grafana 6.7.1 and loki 1.3, logcli is running fine in tail mode

**Comment by Sp0rN** [comment]
Same issue:
Grafana 6.6.2
Loki 1.3

**Comment by jongyllen** [comment]
Hi, when I try this with Grafana 6.7.2 the live logs for Loki works for me. Has this been resolved maybe?

**Comment by danieldabate** [comment]
I just tested 6.7.2 but the issue is still happening. From what I know it does not happen to everyone.

**Comment by torkelo** [comment]
Maybe you have proxy in front of Grafana that does not support websockets?

**Comment by danieldabate** [comment]
I found the issue!! It was an endpoint change like I said in the previous message. 

Now Grafana is requesting this Loki's endpoint:
`/loki/api/v1/tail`
instead of the older:
`/api/prom/tail`

So any setup in the proxies related to the older version, like a `proxy_set_header Upgrade`, would not be applied from Grafana 6.6.0

**Comment by ivanahuckova** [comment]
Hello @danieldabate! I am glad that you were able to solve the problem. 🚀 I am going to close this issue as in the next release we are are going to stop supporting legacy Loki endpoints (before v1). As it is a breaking change, it is going to be communicated in the release notes.

**Comment by chusiang** [comment]
Thanks @danieldabate, you saved my some time.

**Comment by A-styler** [comment]
@ivanahuckova 7.0.0-beta3 still this issue 

nginx-proxy
loki 1.4.1

**Comment by s5unty** [comment]
Live mode requires websocket.
If nginx is used, websocket support is required
https://www.nginx.com/blog/websocket-nginx/

**Comment by A-styler** [comment]
@s5unty
Thank you, your link helped

**Comment by jslay88** [comment]
Just to help those coming here from a fresh Grafana and Loki deployment, when you add Loki to your Data Sources, you need to add two customer headers
* Connection: Upgrade
* Upgrade: websocket

**Comment by Binyamse** [comment]
I am having this issue no proxy in the middle (between grafan and loki) added the two custom headers the issue persists.

**Comment by saikatharryc** [comment]
I'm using ambassador Mappings, doing [this](https://www.getambassador.io/docs/edge-stack/latest/howtos/websockets/) worked for me, which means. for those not working, try allowing WebSocket connection upgrade. to their controllers/servers.

**Comment by gurre** [comment]
Custom headers didn't solve it for me but here is the config:
```
datasources:
  - name: Loki
    type: loki
    url: "http://loki.local:3100"
    access: proxy
    version: 1
    org_id: 1
    isDefault: false
    jsonData:
      timeInterval: 15s
      httpHeaderName1: Connection
      httpHeaderName2: Upgrade
    secureJsonData:
      httpHeaderValue1: Upgrade
      httpHeaderValue2: websocket
```

I'm getting `parse error : syntax error: unexpected $end` from `GET /api/datasources/proxy/95/loki/api/v1/query_range` and `WebSocketSubject.js:96 WebSocket connection to 'wss://loki.local/api/datasources/proxy/95/loki/api/v1/tail?query=%7Bjob%3D%22systemd-journal%22%7D' failed: `

**Comment by oleksii-boiko-ua** [comment]
we are having exact same issues when X-Scope-OrgID header contains more than 1 tenant id.
Grafana v9.5.3
Loki v2.8.2

**Comment by jslay88** [comment]
> Custom headers didn't solve it for me but here is the config:
> 
> ```
> datasources:
>   - name: Loki
>     type: loki
>     url: "http://loki.local:3100"
>     access: proxy
>     version: 1
>     org_id: 1
>     isDefault: false
>     jsonData:
>       timeInterval: 15s
>       httpHeaderName1: Connection
>       httpHeaderName2: Upgrade
>     secureJsonData:
>       httpHeaderValue1: Upgrade
>       httpHeaderValue2: websocket
> ```
> 
> I'm getting `parse error : syntax error: unexpected $end` from `GET /api/datasources/proxy/95/loki/api/v1/query_range` and `WebSocketSubject.js:96 WebSocket connection to 'wss://loki.local/api/datasources/proxy/95/loki/api/v1/tail?query=%7Bjob%3D%22systemd-journal%22%7D' failed: `

This is a completely different error than what the custom headers are supposed to solve. 

Custom headers only solve the issue when the error states that it is a Connection or Upgrade header issue.

**Comment by Jeremy-Boyle** [comment]
I was able to fix this by enabling `WebSocket` on the Grafana side along with the following

```bash
httpHeaderName1: Connection
httpHeaderName2: Upgrade
httpHeaderValue1: Upgrade
httpHeaderValue2: websocket
```

For what its worth, my grafana instance is behind HTTPProxy with Contour.

Here's for nginx (https://www.civo.com/learn/using-websockets-with-ingress-controller)
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: web-socket
 annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  nginx.ingress.kubernetes.io/server-snippets: |
   location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $http_upgrade;
    }
...
```

My HTTPProxy is as follows.
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: grafana
spec:
  virtualhost:
    fqdn: private.com
    tls:
      secretName: cert-tls
  routes:
  - services:
    - name: grafana-operator-grafana-service
      port: 3000
    enableWebsockets: true
```

**Comment by devops-encipher** [comment]
I'm also getting the same error. I'm using Azure Managed Grafana, and I have installed Loki via Helm. Loki is connected to an Azure Storage Account. if anyone using the same setup, can you suggest the solution.
