### ISSUE TITLE
Dashboard is showing same series multiple times in legend, and in multiple colours?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2291]
I have a dashboard with three queries on it:

![screenshot 2015-07-06 18 14 38](https://cloud.githubusercontent.com/assets/243499/8518165/e1e5118a-240a-11e5-9ba5-cb31ddf3c07b.png)
However, for some odd reason, the graph is showing the same series multiple times in the legend, and also in multiple colours:

![screenshot 2015-07-06 18 12 59](https://cloud.githubusercontent.com/assets/243499/8518150/ce01ff84-240a-11e5-9e6e-c321eae28e19.png)

![screenshot 2015-07-06 18 15 47](https://cloud.githubusercontent.com/assets/243499/8518189/16de1198-240b-11e5-9f3e-42c7c8ea79d2.png)

I can't seem to discern any pattern to the transitions points, or what causes the colours to change, or a new "series" to be created.

**Comment by torkelo** [comment]
@victorhooi I think this is an InfluxDB bug, same as this user encountered https://github.com/grafana/grafana/issues/2266
