### ISSUE TITLE
Refactor core backend datasources to return dataframes

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#22918]
All datasources in `/pkg/tsdb/` should be refactored to use dataframes instead of `[]*TimeSeries`

- [x] Azure monitor
- [x] Cloudwatch
- [x] Cloud Monitoring
- [x] Elasticsearch
- [x] Graphite @ifrost 
- [x] Influxdb
- [x] MSSQL
- [x] MySql
- [x] OpenTSDB
- [x] Postgres
- [x] Prometheus
- [x] Testdatasource

**Comment by markfarnan** [comment]
+1 for PostgreSQL

**Comment by marefr** [comment]
Closing this as finally fixed by merging #35887
