### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#22911]
https://community.grafana.com/t/edit-playlist-not-all-dashboards-are-displayed/1440

I read all information that exist on the Playlist page and could not find anything about the 20 dashboard limit, so I spent 1 hour on google to find the above community topic.

I suggest to add a few words in the text at the top so the user at least understand that the page only shows 20 dashboard and you have to search for the other.

Also make some space between Search-field and the list for 20 dashboards.

I will create a PR and link to this

**Comment by torkelo** [comment]
thanks!

**Comment by flopp999** [comment]
I found look of different search fields so I will create a new issue about that
