### ISSUE TITLE
Cannot change user role to Editor

### ISSUE THREAD

**Issue by bunghi** [grafana/grafana#22920]
**What happened**:
After logging in the user's role changes from Editor to Viewer

**What you expected to happen**:
Keep Editor role after login

**How to reproduce it (as minimally and precisely as possible)**:
1. Server Admin - Users - Modify existing user
![image](https://user-images.githubusercontent.com/31234197/77158108-510d4f00-6aab-11ea-8ec5-ba850f425b2c.png)

2. Add user to organization -> Select organisation and set role to Editor
![image](https://user-images.githubusercontent.com/31234197/77158155-65e9e280-6aab-11ea-9d8f-9c3bbfdaf8fe.png)
![image](https://user-images.githubusercontent.com/31234197/77158212-80bc5700-6aab-11ea-8305-26f939320b48.png)

3. Login with the user in a a different browser 

4. Check from Server Admin the user roles, it changed to Viewer
![image](https://user-images.githubusercontent.com/31234197/77158283-b19c8c00-6aab-11ea-958b-7e4afb43a4dc.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.7.0
- Data source type & version: 
- OS Grafana is installed on: Debian 9
- User OS & Browser: Windows 10, Chrome, IE
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
You using ldap, so roles are synced with your ldap config every time you login. To control roles from Grafana you need to remove all group mappings from your ldap config: https://github.com/grafana/grafana/blob/master/conf/ldap.toml#L49
