### ISSUE TITLE
Graphite: Toggle text edit mode stopped working in 6.7.0

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grafana/grafana#22927]
**What happened**:

An unexpected error happened

Details
```
TypeError: t is undefined
    in t
    in div
    in div
    in t
    in p
    in div
    in t
    in div
    in div
    in t
    in p
    in t
    in t
    in div
    in div
    in div
    in e
    in t
    in div
    in t
    in p
    in n
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in h
```

**What you expected to happen**:

Explore/Panel edit to switch to text input mode for graphite datasource.

**How to reproduce it (as minimally and precisely as possible)**:

With a graphite datasource, click the toggle text edit mode button.

**Anything else we need to know?**:

Consider this a regression.

**Environment**:
- Grafana version: 6.7.0
- Data source type & version: Graphite
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
Unable to replicate: https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&fullscreen&edit&panelId=1 

Can you include your query?

**Comment by iain-buclaw-sociomantic** [comment]
@torkelo - There is no query, and I can replicate on play.grafana.org.

**Comment by dorroddorrod** [comment]
We are experiencing the same issue
Version 6.7.1
