### ISSUE TITLE
Add support for text and boolean properties in single stat panel

### ISSUE THREAD

**Issue by jeremyVignelles** [grafana/grafana#2292]
Hi,
I have an influxDB 0.9.1 database, in which I can store texts and booleans, corresponding to a version number and an "enabled" status.
These values doesn't change very often, but they are sent in my database's record with other status, such as "temparature" and "voltage".

I would like to have a dashboard with a single stat panel which indicates the current version and the status enabled/disabled, but it looks like it is not supported in grafana 2.0.2, which displays "NaN", "1.0" or "NaN.nfinity" depending on the value.

Could you please support this feature?

**Comment by torkelo** [comment]
this is already implemented in master, (and 2.1 pre release builds)
https://github.com/grafana/grafana/issues/2203
