### ISSUE TITLE
Image renderer plugin: Shouldn't show panel link icon

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#22936]
**What happened**:
Direct link rendered image of a panel, but includes icon in upper left corner since the panel have a panel link:
![image](https://user-images.githubusercontent.com/1668778/77188982-2638f000-6ad7-11ea-80eb-e6d755777bd5.png)

**What you expected to happen**:
No icon displayed - clean panel title.

**How to reproduce it (as minimally and precisely as possible)**:
1. Direct link rendered image of a panel that have a panel link defined.

**Environment**:
- Grafana version: master (bdb5659)
- Grafana plugins: grafana-image-renderer 1.0.10

**Comment by marefr** [comment]
@torkelo is this something we need to take into consideration fro the new rollup indicators (#22738)?

**Comment by ryantxu** [comment]
I am agnostic on the link icon -- is it a change in behavior?

For rollup indicators, I think they should be included in the image.  They will often indicate error/warning states.  *maybe* we should hide the "info" state

**Comment by marefr** [comment]
This doesn't feel super important any longer. So will close this for now
