### ISSUE TITLE
Grafana missing dependency on chkconfig

### ISSUE THREAD

**Issue by tfishr** [grafana/grafana#22935]
**What happened**: If you try to run `systemctl enable grafana-server` on Fedora you get error `Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory`

**How to reproduce it**: Install Fedora Server or Workstation then install grafana, then try to run `systemctl enable grafana-server`.

**Anything else we need to know?**: If you run `dnf install chkconfig` first, then enable grafana, that works.

**Environment**:
- Grafana version: 6.6+
- OS Grafana is installed on: Fedora

Grafana uses chkconfig, but does not have a dependency on it. Fedora does not include chkconfig by default because all of its packages use systemd not sysv. Grafana uses sysv, which requires chkconfig to work.

Ref: https://unix.stackexchange.com/questions/534463/cant-enable-grafana-on-boot-in-fedora-because-systemd-sysv-install-missing

**Comment by aknuds1** [comment]
Thanks for reporting the issue - I've been able to reproduce it, and we are considering adding chkconfig as an RPM dependency.

**Comment by aknuds1** [comment]
I merged a fix for this, our RPM packages from 7.0 on should depend on chkconfig.
