### ISSUE TITLE
Scripted dashboard with templated vars referencing $__timeFilter not refreshing on timepicker change

### ISSUE THREAD

**Issue by mattd79** [grafana/grafana#22938]
**What happened**: I have a scripted dashboard with a dashboard.templating var that has a query referencing the $__timeFilter variable and refresh set to 2. Changing the timepicker does not refresh the value

**What you expected to happen**: Value should change relative to the time range specified in the time picker

**How to reproduce it (as minimally and precisely as possible)**: Scripted dashboard with one template variable refrencing the $__timeFilter variable and refresh set to 2. The variable can be rendered in a single value panel. Changing the time range specified in the time picker will not refresh the value

**Anything else we need to know?**: Even though in the script refresh is set to 2, if I look at the Json Model after the dashboard has rendered Refresh is set to 1. If I change Refresh to 2 in the Json Model and go back to the dashboard, changing the time picker DOES refresh the value. However if I refresh to page to reload the script Refresh sets back to 1.

**Environment**: 
- Grafana version: 6.6.1
- Data source type & version: MySql 5
- OS Grafana is installed on: Windows Server 2012
- User OS & Browser: Windows 10 Pro/Firefox 74.0
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you include the json your script is returning ?

**Comment by torkelo** [comment]
Does it work if you create the variable manually in the UI ? save and reload ?

**Comment by mattd79** [comment]
> 
> 
> Can you include the json your script is returning ?

This is a scaled down version of my script that replicates the issue.

[refresh_test_script.txt](https://github.com/grafana/grafana/files/4368794/refresh_test_script.txt)

**Comment by mattd79** [comment]
> 
> 
> Does it work if you create the variable manually in the UI ? save and reload ?

The variables are generated dynaically in the script and the dashboard is generated from a skeleton so I cannot save the variable through the UI. If I edit the generated JSON Model and set Refresh to 2 it works, but if I reload the page it sets back to 1, which makes sense as it is all script driven.

**Comment by torkelo** [comment]
Please try 7.0,  closing this as scripted dashboards is not supported anymore (deprecated)
