### ISSUE TITLE
Azure Application Insights: feature for sorting the series in groupby

### ISSUE THREAD

**Issue by espenrl** [grafana/grafana#22937]
**Why is this needed**:

- Grafana version: 6.7.0
- Datasource: Application Insights

Hi. I will start of with a screenshot showing three metrics in each their own graph, all grouped by `cloud/roleName`. Role name is a set of six different executables in our solution. Pay attention to the order of the series.

![image](https://user-images.githubusercontent.com/4621581/77188176-e4f41080-6ad5-11ea-95ce-509504dfd918.png)

![image](https://user-images.githubusercontent.com/4621581/77187461-cfcab200-6ad4-11ea-82dd-a2e8cc230f53.png)

There is no correlation of series ordering and coloring between the graphs/data tables. It is quite hard for the human brain to accurately comprehend the information.

**What would you like to be added**:
There is no way to alter the behavior in Application Insights itself without resolving to query mode, which would be a tradeoff to larger delays in the delivery of the metrics as well as being more complex to define. Adding a sorting option will resolve this in a nice and clean way.

**Comment by aknuds1** [comment]
Hi, do you mind rewriting this using the standard template (is this a feature request?)?Thanks!

**Comment by kylebrandt** [comment]
Once grafana/grafana-plugin-sdk-go#198 is merged, and then Grafana is using that, this should be fixed.

The change will sort the data in the backend, and the sort order is what determines the coloring/order of series in the Graph panel.

This does _not_ fix all instances of the same series getting rendered differently after a refresh. In particular, the case where series have been added or removed from the response. But in that case I believe series overrides would need to be used. This will at least fix the same set of series from shifting around (as shown in this issue).
