### ISSUE TITLE
Toolkit: recent changes won't build plugins

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#22945]
Some dependency has changed and now plugins don't build.  They fail with:
![image](https://user-images.githubusercontent.com/705951/77240119-82674700-6b9f-11ea-8830-6d79a6c76a13.png)

See: 
https://github.com/grafana/google-sheets-datasource/pull/62/files

I can get the same error on any plugin by using `next` and then running:
```
rm yarn.lock
yarn install
yarn dev
```

I suspect the error is unrelated to the actual problem :(

**Comment by ryantxu** [comment]
Any ideas @dprokop @stevenvachon

**Comment by dprokop** [comment]
@ryantxu I'm on it, gonna investigate today

**Comment by stevenvachon** [comment]
It's an issue with Babel somehow, seemingly fixed in `7.9.0`.
