### ISSUE TITLE
grafana-cli: command not found

### ISSUE THREAD

**Issue by solick** [grafana/grafana#22943]
**What happened**:
updated from 6.0.1 to latest

**What you expected to happen**:
after removing container and building new container grafana should start and run

**How to reproduce it (as minimally and precisely as possible)**:
pull an start container

**Anything else we need to know?**:
I switched forth and back between the versions, the error still occurs:

grafana      | /run.sh: line 75: grafana-cli: command not found

It worked with 6.0.1 before updating.

I host this via docker on a synology NAS.

**Comment by aknuds1** [comment]
Please write a clearer description of:

1. What happened
2. How to reproduce it (as minimally and precisely as possible)

Otherwise we can't reproduce your issue.

**Comment by solick** [comment]
Found it our on my own. Forwarding the usr/share/grafana outside docker cause the problem. Removing it from my docker-compose file fix the problem.
