### ISSUE TITLE
michaeldmoore-multistat-panel can not use  for any more!!!

### ISSUE THREAD

**Issue by yujianwei1984** [grafana/grafana#22946]
**What happened**:
michaeldmoore-multistat-panel can not use  for any more!!!
**What you expected to happen**:
use michaeldmoore-multistat-panel to display multi kpi 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: mysql 5.7
- OS Grafana is installed on:   Centos 6.5
- User OS & Browser: firefox
- Grafana plugins: michaeldmoore-multistat-panel 
- Others: no

**Comment by ryantxu** [comment]
Can you open a ticket here:
https://github.com/michaeldmoore/michaeldmoore-multistat-panel/issues

If there is something more specific we need to look at, open another ticket here (with more info)
