### ISSUE TITLE
PRTG plugin broken after upgrade to 6.7.1

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#22956]
**What happened**:
We can see data returned, sometimes, but there is nothing displayed in the graphs above

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: Happened right after the upgrade

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by michaeldmoore** [comment]
This is yet another panel broken - I assume by the change to the DOM hosting the panels, that broke my multistat panel.

Two things are needed  

1. A clear announcement or warning to panel developers to test and resolve any problems this release of Grafana creates
2. An accelerated effort to rapidly approve new versions of panels that fix these problems this release has caused.

I'm not complaining, or suggesting that the changes weren't necessary - you'll be the judge of that. 
But the panel approval pipeline seems to be blocked again, with nothing having moved for the past month or two, as far as I can see from the repo issues list.
Respectfully,
Michael Moore

**Comment by wargamez** [comment]
Same with Status Panel, ref:
https://github.com/Vonage/Grafana_Status_panel/issues/159

**Comment by hugohaggmark** [comment]
Reading through comments and the PRTG plugin's own issues this seems to have been fixed in 6.7.2 but there are more issues afteer Grafana 7.0 release. I'm going to close this for now as the fix seems to be to upgrade to Grafan 6.7.2.
