### ISSUE TITLE
@grafana/tookit 6.7.1 cant build

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#22950]
Hi, 

Since i updated grafana toolkit with 6.71, i can't build with a spacename in index.d.ts : 
  /home/arnaud/workspace/grafana-flowcharting/src/index.d.ts
    5:11  error  Parsing error: Unexpected token, expected ";"
  
    3 | type mxMouseEvent = any;
    4 | 
  > 5 | namespace gf {
      |           ^
    6 |   interface TSelectString {
    7 |     text: string;
    8 |     value: string;
  
  ✖ 1 problem (1 error, 0 warnings)

How to resolve it

**Comment by ryantxu** [comment]
What was the previous version?  I am seeing errors in 6.7.1... but different #22945

Perhaps related... grafana switched from tslint to eslint -- if you have custom tslint files they may be ingnored now

**Comment by algenty** [comment]
Hi Ryan, Hi Dominik
My previous version : 
    "@grafana/runtime": "^6.6.0-pre-047abc87c2",
    "@grafana/toolkit": "^6.6.0-pre-047abc87c2",
    "@grafana/ui": "^6.6.0-pre-047abc87c2",

**Comment by dprokop** [comment]
Hi @algenty! Thanks for reporting this. As @ryantxu mentioned, we have migrated TSLint to ESLint and wour .eslintrc.json should be updated. I suggest starting with extending @grafana/eslint-config in your eslint config (`"extends": ["@grafana/eslint-config"]`). Mind, that we don't allow namespaces in our config and you should refactor your index.d.ts file to something like this: https://gist.github.com/dprokop/0da6bb6e5925c7bc81fefa31bb5b3117 (btw this works with your current config but we strongly encourage you to extend default grafana eslint config)

**Comment by algenty** [comment]
Hi,
Thx for your answer, why do you not allow namespace ? it's very usefull to identy custom types.

**Comment by torkelo** [comment]
They are a deprecated typescript feature

**Comment by dprokop** [comment]
@algenty please see https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-namespace.md for detailed overview

**Comment by algenty** [comment]
Ok,
Thx @dprokop, as I said before, i am not a developper, just an hobbyist.
When you write "extend", it's in  .eslintrc.json, 
like this : 
{
    "parser": "babel-eslint",
    "extends": ["@grafana/eslint-config"],
    "env": {
...

With this config, I have a new error on 'moment' : 
  /home/arnaud/workspace/grafana-flowcharting/src/rule_class.ts
    1:1  error  'moment' import is restricted from being used  no-restricted-imports

How can i resolve it ?

Br
Arnaud

**Comment by dprokop** [comment]
> Thx @dprokop, as I said before, i am not a developper, just an hobbyist.

No worries. So the error you are getting is caused by the fact that we ban importing `moment` directyle. Instead, you should use `dateTime` wrapper we expose from @grafana/data .

**Comment by algenty** [comment]
Migration works but without dataTime and extends
How to find js docs from @grafana/data ?

Br
Arnaud
