### ISSUE TITLE
Enable any plugin to be disabled/enabled.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#22962]
It should be possible to disable/enable all plugins in Grafana. During plugin initialization, Grafana should check if the plugin exists in `plugin_settings` if not it should be added. When plugins are enabled/disabled from the plugin. Unsigned plugins should not be enabled by default. 

One problem here is to figure out how to deal with multiple orgs since.

Grafanas backend also need to expose endpoints for enabling/disabling a plugin since that is not available today.

**Comment by ryantxu** [comment]
@bergquist -- I updated this to make sure it is clear this should happen for all plugins, not just backend plugins.

Enable/disable is already supported for apps

**Comment by bergquist** [comment]
> Unsigned plugins should not be enabled by default.

This will be hard when running Grafana statelessly (All driven by config. All users are viewers only). As some teams do internally.
