### ISSUE TITLE
SimpleJson Datasource - Not working with version 

### ISSUE THREAD

**Issue by G31st** [grafana/grafana#22967]
**What happened**: No Data in Panel Title. 

**What you expected to happen**: There to be a data table displayed with the column from the query. 

**How to reproduce it (as minimally and precisely as possible)**: Install simple Json data source, run the sample fake data source,   https://github.com/bergquist/fake-simple-json-datasource, Add this as a datasource. Create a new dashboard. Select "table" as A with upper_25 

**Anything else we need to know?**: Explorer feature also does not show any data tables when querying this datasource. However it does show the timeseries data. When using the query inspector it does all the data in the query is there. 

**Environment**: DEV
- Grafana version: v6.7.1 
- Data source type & version: Simple JSON Datasource 1.4.0
- OS Grafana is installed on:linux
- User OS & Browser:Edge & Chrome
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Can you please rewrite the issue using the standard issue template? Thanks!

**Comment by aknuds1** [comment]
The Grafana version is also very old, can you try the latest one, i.e. 6.7.1?

**Comment by G31st** [comment]
**What happened**: No Data in Panel Title. 

**What you expected to happen**: There to be a data table displayed with the column from the query. 

**How to reproduce it (as minimally and precisely as possible)**: Install simple Json data source, run the sample fake data source,   https://github.com/bergquist/fake-simple-json-datasource, Add this as a datasource. Create a new dashboard. Select "table" as A with upper_25 

**Anything else we need to know?**: Explorer feature also does not show any data tables when querying this datasource. 

**Environment**: DEV
- Grafana version: v6.7.0-beta1 
- Data source type & version: Simple JSON Datasource 1.4.0
- OS Grafana is installed on:linux
- User OS & Browser:Edge & Chrome
- Grafana plugins:
- Others:

**Comment by G31st** [comment]
![image](https://user-images.githubusercontent.com/52254120/77326950-36dda600-6d23-11ea-8ffa-09bbdc9c7852.png)

**Comment by aknuds1** [comment]
> **What happened**: No Data in Panel Title.
> 
> **What you expected to happen**: There to be a data table displayed with the column from the query.
> 
> **How to reproduce it (as minimally and precisely as possible)**: Install simple Json data source, run the sample fake data source, https://github.com/bergquist/fake-simple-json-datasource, Add this as a datasource. Create a new dashboard. Select "table" as A with upper_25
> 
> **Anything else we need to know?**: Explorer feature also does not show any data tables when querying this datasource.
> 
> **Environment**: DEV
> 
>     * Grafana version: v6.7.0-beta1
> 
>     * Data source type & version: Simple JSON Datasource 1.4.0
> 
>     * OS Grafana is installed on:linux
> 
>     * User OS & Browser:Edge & Chrome
> 
>     * Grafana plugins:
> 
>     * Others:

@G31st Please edit the issue and move the above there, since it should be in the issue description.

**Comment by jongyllen** [comment]
I think this is the same problem as https://github.com/grafana/grafana/issues/23024 Closing this issue so we keep it in one only.
