### ISSUE TITLE
Plugins: dateMath typescript namespace is causing issues for external plugins

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#22969]
The use of a typescript namespace here: 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/datetime/datemath.ts#L8

Is causing issues when we try expose it via systemjs:
https://github.com/grafana/grafana/blob/master/public/app/features/plugins/plugin_loader.ts

External plugin importing it is getting dateMath.parse is not a function
https://github.com/neuralfraud/grafana-prtg/blob/6da21ded9bdb5ca67e0c152fbf094d5679780d45/jasonlashua-prtg-datasource/src/datasource.js#L2

I think if we replace the typescript namespace with functions and export them as before 
`import * as dateMath from './dateMath`; 
export [ dateMath };

It should work again

**Comment by mckn** [comment]
Good catch, didn't even know about the grafana-packages being exposed that way. Will see if I can revert the namespace changes.
