### ISSUE TITLE
Error on passing "ALL" values to other Dashboard in links using templattings

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#2297]
Hi, I have a dashboard (*DB1*) with templatting and the properties _"All"_ and multiple selection enabled.

I created a link to another Dashboard (*DB2*), passing the DB1 values:

It works fine with single or multiple selection vars (ie, passing backend1+backend2:
`var-host=backend1&var-host=backend2`

But when im trying to pass with "All" variable, it's passing as:
`var-host=%7Bbackend1,backend2%7D`

So the DB2 doesn't recognize the input vars.

There is a problem with the formatting on "All" values?

Thanks

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master now
