### ISSUE TITLE
Transparency stopped working

### ISSUE THREAD

**Issue by GideonWolfe** [grafana/grafana#22985]
**What happened**:

![DeepinScreenshot_select-area_20200323143026](https://user-images.githubusercontent.com/32942052/77365164-e0686b80-6d12-11ea-8066-3689d44c2973.png)

**What you expected to happen**:

![](https://gideonwolfe.com/img/sysadmin/TIG/dockerstats.png)

**How to reproduce it (as minimally and precisely as possible)**:

I believe this was triggered by an update. I style my dashboards with a Boom theme which simply applies a pitch black background using a link to a black image.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.7.1 (ca6d08d5cb)
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu + Docker-Compose
- User OS & Browser: Arch Linux + Firefox
- Grafana plugins: Boom theme is the relevant one.

**Comment by peterholmberg** [comment]
This is an issue with the boom theme plugin, 
https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel I'd suggest opening an issue there.
