### ISSUE TITLE
JSON keys with ':' character don't work in role_attribute_path

### ISSUE THREAD

**Issue by cmanzi** [grafana/grafana#22986]
**What happened**:
Trying to provide a JSON key to the role_attribute_path (`contains(custom:groups, 'foo') && 'Admin' || 'Editor'`) of the OIDC settings which contains a ':' character produces the following error: 
```
Invalid Token tColon
```
I made several attempts to properly escape the colon character. The following removed the error, but the Auth still failed and defaulted the role to 'Editor':
```
role_attribute_path  = contains(`"custom:groups"`, 'foo') && 'Admin' || 'Editor'
```
```
role_attribute_path  = contains('custom:groups', 'foo') && 'Admin' || 'Editor'
```
The `custom:groups` attribute it present in the userInfo response JSON, I can verify that. It is a string attribute, so my understanding is that `contains` should fund this substring and return true.

**What you expected to happen**:
role_attribute_path is able to properly find a substring in my attribute which contains a ':' and assign the role appropriately.

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana 6.7 with an OIDC provider

**Anything else we need to know?**:
I am using AWS Cognito for my OIDC provider.

**Environment**:
- Grafana version: 6.7.1-ubuntu
- Data source type & version: N/A
- OS Grafana is installed on: Kubernetes
- User OS & Browser: MacOS Chrome
- Grafana plugins: N/A
- Others:

**Comment by marefr** [comment]
@cmanzi looking at this again. Using the following at https://jmespath.org/ it works for me:
```
"custom:groups" | contains([*], 'foo') && 'Admin' || 'Editor'
```

Payload:
```json
{
  "custom:groups": [
    "foo"
  ]
}
```

**Comment by marefr** [comment]
So I think we can close this

**Comment by marefr** [comment]
Closing this since there's a workaround

**Comment by sherifkayad** [comment]
@marefr I can't seem to set the value right when installing Grafana using Helm. I tried:
```yaml
role_attribute_path: >
      "custom:azure_groups" | contains([*], 'my-group') && 'Admin' || 'Viewer'
```
Got an error: `Failed to extract role" error="failed to search user info JSON response with provided path: \"\\\"custom:azure_groups\\\" | contains([*], 'my-group') && 'Admin' || 'Viewer'\": Invalid type for: <nil>, expected: []jmespath.jpType{\"array\", \"string\"}"`

**Comment by sherifkayad** [comment]
@marefr update: turned out my claim was sent as a string and not an array of strings! .. Sorry for bothering.
