### ISSUE TITLE
Automatic metric definition 

### ISSUE THREAD

**Issue by mboussaa** [grafana/grafana#2298]
Hello, 

I am using a docker-compose.yml to start 3 containers simultaneously (cadvisor, influxDB and Grafana). This works well when I docker compose up (I got stats through grafana) However, to fully automate this process, I also need to request automatically grafana through SQL queries when all containers start. I don't know if we can define metrics (SQL queries) in the same YAML file. Is there a way to do that initially when starting grafana so that when going to grafana web UI I can find graphs.

Thanks in advance

**Comment by torkelo** [comment]
> I also need to request automatically grafana through SQL queries when all containers start. 

What?? Not sure I understand what you want. You can use the Grafana HTTP API to automate everything from creating dashboards, accounts and data sources.

**Comment by mboussaa** [comment]
I mean when starting grafana like this:
docker run -p 80:80  -e HTTP_USER=root   -e HTTP_PASS=root    -e INFLUXDB_HOST=10.0.2.15    -e INFLUXDB_PORT=8086 -e INFLUXDB_NAME=cadvisorDB -e INFLUXDB_USER=root -e INFLUXDB_PASS=root  tutum/grafana

I would define and execute the SQL request while starting the container.
And later when I go to grafana web UI I can find the graph of the corresponding metric

**Comment by torkelo** [comment]
@mboussaa I have no idea what you are talking about :(

SQL request? corresponding metric? metric for what? what SQL request? 

Here is a guide for how to build dashboards and graphs:
https://www.youtube.com/watch?list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2&v=sKNZMtoSHN4
