### ISSUE TITLE
Docs feedback: /tutorials/iis.md

### ISSUE THREAD

**Issue by mw-solutions** [grafana/grafana#23013]
One important point is missing: the IIS module **Application Request Routing** has to be installed to get URL Rewrite working!
The Application Request Routing module will automatically be configured to set proxy mode when adding a rule in URL Rewrite. So nothing has to be configured manually.
Please add this information. Thank you!

**Comment by oddlittlebird** [comment]
@marcusolsson , is this still valid?

**Comment by marcusolsson** [comment]
I think this was fixed in https://github.com/grafana/tutorials/pull/49

**Comment by oddlittlebird** [comment]
Okay, closing this.
