### ISSUE TITLE
Stackdriver based alerting does not work with TemplateVariable

### ISSUE THREAD

**Issue by peterhaaf** [grafana/grafana#23014]
I have defined a query against Stackdriver with a templatevariable (podname) , which is working fine All Graphs are available. Now i tried to create an alert based on that query, which fails, because the templatevariable is not being evaluated.

**What happened**:
rawQuery:"aggregation.alignmentPeriod=%2B60s&aggregation.crossSeriesReducer=REDUCE_NONE&aggregation.groupByFields=metric.label.volume_name&aggregation.perSeriesAligner=ALIGN_MAX&filter=metric.type%3D%22kubernetes.io%2Fpod%2Fvolume%2Futilization%22+metadata.user_labels.app%3D%22**%24podname**%22+metric.label.volume_name%21%3Dmonitoring.regex.full_match%28%22jaas-jenkins-.%2A%22%29&interval.endTime=2020-03-24T07%3A59%3A42Z&interval.startTime=2020-03-24T07%3A54%3A42Z&view=FULL"
**What you expected to happen**:
rawQuery:"aggregation.alignmentPeriod=%2B60s&aggregation.crossSeriesReducer=REDUCE_NONE&aggregation.groupByFields=metric.label.volume_name&aggregation.perSeriesAligner=ALIGN_MAX&filter=metric.type%3D%22kubernetes.io%2Fpod%2Fvolume%2Futilization%22+metadata.user_labels.app%3D%22**forpeter**%22+metric.label.volume_name%21%3Dmonitoring.regex.full_match%28%22jaas-jenkins-.%2A%22%29&interval.endTime=2020-03-24T08%3A04%3A40Z&interval.startTime=2020-03-24T07%3A59%3A40Z&view=FULL"
**How to reproduce it (as minimally and precisely as possible)**:
define a query using a template variable and create an alert
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Stackdriver
- OS Grafana is installed on: docker image
- User OS & Browser:
- Grafana plugins: Graph, Stackdriver
- Others:

**Comment by peterhaaf** [comment]
\**%24podname** should be bold font for %24podname ( first rawQuery)

**Comment by sunker** [comment]
It's not possible to create alerts based on queries that use template variables, unfortunately 
https://grafana.com/docs/grafana/latest/alerting/rules/
