### ISSUE TITLE
Rich History: Data source select width bug

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#23022]
Not sure if the width should have a limit here, and that what causes it. Can someone else reproduce this?
![Screenshot from 2020-03-24 12-13-47](https://user-images.githubusercontent.com/1438972/77419699-1f58f880-6dc9-11ea-81c3-32a7d53f26d9.png)

**Comment by torkelo** [comment]
yea, noticed this as well. maybe set a max-width on that one.
