### ISSUE TITLE
Enable ESM instead of CommonJS-only

### ISSUE THREAD

**Issue by JPeer264** [grafana/grafana#23029]
**What would you like to be added**:
rollup should export ESM and CommonJS as final build. Currently we are using some `@grafana/ui` components but tree-shaking is not possible with the CommonJS produced code.

So that is why rollup should also produce ESM modules.

**Why is this needed**:

1. rollup should also include ESM modules
2. Tell the `package.json` where the ESM produced code is stored: `"module": "./grafana-ui.esm.js",`

**Comment by torkelo** [comment]
tree shaking is not really relevant here as the @grafana/* packages are externalized in the plugin build (they are loaded from the Grafana instance the plugin is running in)

**Comment by JPeer264** [comment]
Exactly that is what I thought and totally understand this decision. Would you still accept PRs regarding this to support both?

**Comment by dprokop** [comment]
Yes, we would. @JPeer264 are you using @grafana/ui outside Grafana plugin context?

**Comment by JPeer264** [comment]
Not sure why this got closed, as you accept PRs to fix/improve this. But yes, we are just using specific components from `@grafana/ui` and `@grafana/data`, outside of the Grafana plugin context

**Comment by breeswish** [comment]
Hi, we are facing similar problems. We use some components in @grafana/ui. An ESM build would be awesome!
