### ISSUE TITLE
Chore: Use official binary of golangci-lint from Makefile

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#23020]
**What happened**:
We should use the official golangci-lint binary from the Makefile, as we do for CircleCI. After testing, we found that the official binary is much better performing (speedier, uses less memory), versus building it ourselves. Based on said findings, we changed our CircleCI logic to use the official binary.

The one difficulty I foresee is figuring out how to install golangci-lint on developers' machines. We can use the official installer, if we trust that.

**Comment by papagian** [comment]
resolved by #51048 using bingo
