### ISSUE TITLE
RAW SQL Query not quoting string value (variable interpolation) 

### ISSUE THREAD

**Issue by gavmckee80** [grafana/grafana#23039]
**What happened**:

I create a dashboard variable named ifindex .  I want to send a query to PGSQL to return the SNMP interface index based on two other variables .  The first two variables take their values from an Influx datasource and work fine.  

![image](https://user-images.githubusercontent.com/17826993/77473542-dc038780-6dd2-11ea-90c8-ab5b20de73e0.png)

I add the ifindex variable with the query 
SELECT index FROM live.interfaces_status WHERE hostname IN ($hostname) and interface IN ($interface)

I get the following exception in the chrome console .

```
angular.js:14800 Possibly unhandled rejection: {"data":{"results":{"ifindex":{"error":"pq: syntax error at or near \"mtv\"","refId":"ifindex","meta":{"sql":"SELECT index FROM live.interfaces_status WHERE hostname IN (900mtv-corp-fw-01a) and interface IN (ethernet1/15)"},"series":null,"tables":null,"dataframes":null}},"message":"pq: syntax error at or near \"mtv\""},"status":400,"config":{"method":"POST","url":"api/tsdb/query","data":{"queries":[{"refId":"ifindex","datasourceId":4,"rawSql":"SELECT index FROM live.interfaces_status WHERE hostname IN (900mtv-corp-fw-01a) and interface IN (ethernet1/15)","format":"table"}],"from":"1585080366053","to":"1585081266053"}},"statusText":"Bad Request","xhrStatus":"complete"}
```

When I take the raw SQL and quote the variables the index value I am querying for returns fine.

**What you expected to happen**:
From the documentation I would expect that the variable values would be quoted appropriately.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.6.2 (3fa63cfc34)
- Data source type & version: PGSQL 10
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

**Comment by jongyllen** [comment]
Hi, it seems like your values from your initial queries that you use to format the SQL statement are not quoted (which explains why your query is not working). I cannot see anything in the docs claiming they will be automatically quoted, that would break numbers working instead I guess.

I would expect formatting that using something like [this](https://grafana.com/docs/grafana/latest/reference/templating/#singlequote) would work for this but I cannot get that to work locally. This might be a bug, we will look into it.

**Comment by hugohaggmark** [comment]
@gavmckee80 we don't quote string variables automatically as @jongyllen said above. [Use advanced formatting options to get the format your query language needs](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/), in this case `${hostname:singlequote}` might work better.

**Comment by hugohaggmark** [comment]
I'm going to close this issue for now, but we can always reopen it later if the need arises.

All the best
