### ISSUE TITLE
Repeating panel over a multi-value grafana variable shows "All" when variable query returns empty-set

### ISSUE THREAD

**Issue by ellisda** [grafana/grafana#23036]
**What happened**:

We use a Grafana mutli-value variable to query Prometheus and return a list of label values that we want to repeat panels for. While our query usually returns a few items, there are cases where it correctly returns zero values and in those cases we see a single repeated panel displayed with scoped variable value "All". It's displayed as "None" if the variable doesn't include the "All option."

Our users get confused by the panel titled "Custom ... - All"

**What you expected to happen**:

We expected the panel to be repeated zero times (i.e. be hidden and not perform any queries), since we're repeating over an empty set. Alternatively, if we could control the scoped value of the variable and have it display "N/A - no items; ignore me" then our users might understand that this is expected behavior and not a bug in our dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

1. goto https://play.grafana.org/d/000000036/prometheus-repeat?orgId=1&refresh=5m&var-node=demo.robustperception.io&var-filesystem_mountpoint=All&var-job=foo (noticing that URL is providing an non-existant value, "foo", which we'll fix this in step 3)
1. Open the dashboard settings (cog) > Variables > "job" and replace the query with `label_values(go_memstats_alloc_bytes, job2)` (changing the label name from `job` to `job2` will cause it to return empty set)
1. Click Update at bottom, and then press ESC key to go back to dashboard
1. Verify that there appears a singlestat panel at bottom of dashbaord that is repeated once, and has a title "All" reflecting the currently scoped value of the $job variable
  1. if you also unchecked the "Include All" option on the variable, then you'll see panel title "None" instead of "All"

NOTE - in our real use case, our query looks more like `label_values(custom_metrics{app="$app"}, sli)` where `app` is an upstream grafana variable that the user has selected to view details of a particular app.

**Anything else we need to know?**:

Unlike the related issues below, we want to hide the panel *before* running the panel query. If the variable is empty-set, we don't need to run the panel query at all. To bring the panel back into view and make it editable with UI, we can just update our variable selections so that it's not returning empty set (we could even type in a value into the dropdown if needed).

**related issue [20958](https://github.com/grafana/grafana/issues/20958)** - "Ability to hide rows and panels" (when No Data returned)
 --> mentions that having invisible panels that perform queries is bad

**related issue [4470](https://github.com/grafana/grafana/issues/4470)** - "[Feature Request] Suppress empty repeated panels" - opened 2016, much discussion

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: Prometheus 2.16.0-rc.0
- OS Grafana is installed on: alpine (docker grafana/grafana:6.5.0)
- User OS & Browser: Ubuntu / Chrome
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
This is not supported, repeated panels needs at least one value, hiding panels would make editing them again impossible (or understanding that there is something hidden there). 

Related to these feature requests: 

https://github.com/grafana/grafana/issues/5970
https://github.com/grafana/grafana/issues/4470

**Comment by ellisda** [comment]
I hoped that the user's ability to adjust the variable would avoid the "hidden panel / can't edit" concern, but I understand the sanctity of the UX. I made PR #23080 to attempt to document this.

It would really helpful if we could get a way to customize this "All" / "None" scoped variable value to make our end users less confused if we can't hide the panel.

Thanks for the lightning quick review.
