### ISSUE TITLE
Need MetricSegment component in React

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#23040]
Metric segment is currently only available in Angular. This is needed for the conversion of datasource plugin query editors, etc to react. 

https://github.com/grafana/grafana/blob/e0b760e08e1d83805c1286f4ea2b4b7bf263a375/public/app/core/directives/metric_segment.ts

**Comment by torkelo** [comment]
We have Segment and SegmentAsync in @grafana/ui 

What are we missing ?

**Comment by sunker** [comment]
See example [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/components/Stats.tsx) @shavonn

**Comment by shavonn** [comment]
@sunker thank you !! @torkelo Erik gave me what I needed.
