### ISSUE TITLE
Hide Login-Button for Anonymous Users

### ISSUE THREAD

**Issue by oeiber** [grafana/grafana#23049]
**What would you like to be added**:
A variable to hide the login button for anonymous users

**Why is this needed**:
Authentication for known users is done on nginx via proxy auth

**Comment by peterholmberg** [comment]
It is possible to this with https://grafana.com/docs/grafana/latest/auth/overview/#anonymous-authentication

**Comment by torkelo** [comment]
> Authentication for known users is done on nginx via proxy auth 

If so you should use the auth proxy feature, and disable the anonymous users . Then the sign in link will be hidden

**Comment by oeiber** [comment]
> > Authentication for known users is done on nginx via proxy auth
> 
> If so you should use the auth proxy feature, and disable the anonymous access. Then the sign in link will be hidden

I have a combination of auth proxy feature an anonymous access: Known users where authenticated using proxy auth, the others use anonymous access.

**Comment by oeiber** [comment]
> It is possible to this with https://grafana.com/docs/grafana/latest/auth/overview/#anonymous-authentication

And how is it done? I have already enabled anonymous access. But there's no option to hide the login button?

**Comment by Rohlik** [comment]
Similar issue here, anonymous access works like a charm, but there is still "_Sign in_" option visible in right up corner.

**Comment by sis032** [comment]
I used F12 and found button and remove button in /usr/share/grafana/public/build/ directory
![image](https://github.com/grafana/grafana/assets/107427589/caa5ff41-c451-429f-9dd3-7c8e72e675be)
