### ISSUE TITLE
Display message for unsupported browser

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#23046]
**What would you like to be added**:
Grafana displays warning message on the screen that the user's browser is not supported.

**Why is this needed**:
Now, for example in IE11, Grafana just breaks sometimes without a clear error message for the user, while an incompatible browser is at the basis of the problem. It would be good if some check is added on the client that displays that the browser is unsupported. 

We noticed this issue with some enterprise customers. IE11 is still default there and as they don't get a clear error, it is not clear to them that the browser is causing the issue.

**Comment by dprokop** [comment]
What Grafana version are you using? We have added this notifications in 6.5 (https://github.com/grafana/grafana/pull/19904)

**Comment by coussej** [comment]
That's probably it then! Thank you!
