### ISSUE TITLE
grafana explore log-labels dropdown is rendered incorrectly in firefox

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#23041]
**What happened**:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/1272954/77489059-6668dd00-6e0d-11ea-863e-4ca22fa50cce.png">

In firefox 74.0 the log labels dropdown in Explore mode is rendered at fixed width and cuts off the label names. It also shows a `_name` field that has no entries and doesn't appear when I use chrome.
**What you expected to happen**:
Dropdown should expand to the width of the label names, as seen in Chrome
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Loki 1.3.0
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Mac OSX (Catalina), Firefox 74.0
- Grafana plugins: n/a
- Others:

**Comment by hhromic** [comment]
I'm having a similar problem also with **Chrome** in latest Grafana `6.7.3`.
The panel width is fine but the `__name__` label is also showing:

![image](https://user-images.githubusercontent.com/5802993/80695278-91f67b80-8acd-11ea-9cc3-9b87f1e674a1.png)

**Comment by torkelo** [comment]
Looks to be working in 77
