### ISSUE TITLE
Can't save new dashboard when using save-button in settings dialog

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#23044]
**What happened**:
After creating a new dashboard and clicking the green save button in the settings page of the dashboard, the dashboard is not saved and I'm not able to save the dashboard anymore with any of the save buttons, whether  on the settings page nor on the main page in the top bar. grafana stays on the */dashboard/new* page.

**What you expected to happen**:
I expect grafana to save the dashboard and redirect to the newly created dashboard page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Login
2. Create -> New Dashboard
3. Click on Dashboard-Settings
4. Change something like title,  select a folder folder etc.
5. Use the green save button

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: tried without any, graphite, prometheus - doesn't matter
- OS Grafana is installed on: debian buster
- User OS & Browser: tried on Ubuntu 18.04 / Chrome 80 and Windows 10 / Chrome 80 and Firefix 73
- Grafana plugins: grafana-piechart-panel @ 1.4.0, grafana-polystat-panel @ 1.1.0, vonage-status-panel @ 1.0.9

**Comment by aknuds1** [comment]
I just tried to reproduce using the [v6.7.1 Linux binary](https://dl.grafana.com/oss/release/grafana-6.7.1.linux-amd64.tar.gz), and following your steps listed above, it works just fine. I'm on Arch Linux, although I can't see that making any difference.

Can you see any errors in the server logs or in the JavaScript console of your browser?

**Comment by rsommer** [comment]
No, there are no errors visible. We reproduced the exact behaviour from three different workstations, using three different users, with Windows and Ubuntu. If you cannot reproduce the behaviour it seems to depend on our grafana setup. We use LDAP-Authentication and  postgresql as database if that information is important.

**Comment by rsommer** [comment]
Ok, i just downloaded https://dl.grafana.com/oss/release/grafana_6.7.1_amd64.deb, installed it and started it on a completely work-unrelated Ubuntu  18.04 workstation.
1. Logged in as admin/admin
2. Changed password
3. Clicked Create -> Dashboard
4. Clicked Settings-Icon in new dashboards top-bar
5. Clicked on the grren save-button
Result:
grafana is not saving, i can just go back and any click on any save-button does not perform an actual saving of the dashboard.

**Comment by aknuds1** [comment]
I think my colleague @dprokop will have a look.

**Comment by rsommer** [comment]
I just discovered the following behaviour: if i skip step 5. (changing the title), saving actually seems to work.

**Comment by dprokop** [comment]
@rsommer @aknuds1 I've just tried this and could reproduce easily. Will come with the fix soon

**Comment by aknuds1** [comment]
Thanks @dprokop :)

**Comment by faelnpaiva** [comment]
I'm having the same problem using grafana 6.7.3

**Comment by faelnpaiva** [comment]
I changed the helm chart to get grafana 6.7.2 and I can save now
