### ISSUE TITLE
Determining unit while using row repeat on a metric

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#2304]
This is more of a question than a ticket, but not sure if a better location to ask.  

Love the change on #1888, but trying to figure out a way to use the functionality of row repeat on a metric which will have different units.  Is there a way through a scripted dashboard, change of timeseries tags/data, or other method within the dashboard that I could assign cpu total as percent, latency as ns, eth traffic as bytes, etc?

Note: Using graphite at the moment.

Quick idea I am thinking

-------------------------------------------------------------------------------
| pool: websites + DBs.....metric: cpuTotal + latency + ethin....|
|.............................................cpuTotal.....................................|
|...| DBs showing cpuTotal|..| websites showing cpuTotal |......|
|.............................................latency.......................................|
|...| DBs showing latency.....| websites showing latency |.........|

Thanks for any ideas or tips you can provide,
Gerrick W

**Comment by torkelo** [comment]
no, the repeat is only for identical (config wise) rows or panels, repeating graphs or panels but then wanting to have different config for them kind of defeats the intended usage of repeating a single panel or row
