### ISSUE TITLE
Error on title collapsing row with templating vars

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#2305]
Hi, I am using templating feature on my dashboard with some rows on it.

IE: $host = {backend1}

When I put the name of the template var on the title and expand row:
`Title: [[host]]` or `Title: $host` it appears correctly as `backend1`

But when I collapse the row, the var doesn't change, and it appears as the var name: `$host`

Thanks

**Comment by torkelo** [comment]
thanks for reporting this, fix asap
