### ISSUE TITLE
Forms/Select is missing option description & img

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23054]
The new grafana/ui Select component (under /Forms) is not rendering option description like the one under root (the old form style one).

Permissions dropdown
![image](https://user-images.githubusercontent.com/10999/77526049-43c8d980-6e8a-11ea-82ef-cdf8112c39c8.png)

User picker: 
![image](https://user-images.githubusercontent.com/10999/77526125-63600200-6e8a-11ea-9b35-f0b4d65fabe3.png)

Old Select Option:
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Select/SelectOption.tsx

New Select Option:
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx#L40

**Comment by dprokop** [comment]
Damn. Good catch!
