### ISSUE TITLE
React Graph component - lineWidth typo

### ISSUE THREAD

**Issue by vsergeyev** [grafana/grafana#23056]
**What happened**:

 * In Graph component lineWidth option do not change a way line is drawn.

**What you expected to happen**:

 * Setting lineWidth should result in less/more bold line on graph.

**How to reproduce it (as minimally and precisely as possible)**:

 * use Graph component in graph2 panel plugin
 * in panel config set Line Width > 1

**Anything else we need to know?**:

This looks to be related to typo in 
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Graph/Graph.tsx#L307
`linewidth: lineWidth`
should be
`lineWidth: lineWidth`

**Environment**:
- Grafana version: master from github

**Comment by flopp999** [comment]
can you link to this plugin? or explain in more detail how you did

**Comment by vsergeyev** [comment]
Hello @flopp999 ,
This is react based Graph2 plugin:
https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/graph2

Regards,
V.

**Comment by dprokop** [comment]
@vsergeyev do you mind openenig a PR with a fix?

**Comment by vsergeyev** [comment]
@dprokop don't mind, have opened a PR. Just wondering this don't make me to write a lot of tests :)
