### ISSUE TITLE
make devenv failed for graphite - ImportError: No module named django.core.management

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [grafana/grafana#23065]
**What happened**:
I just tried to run `make devenv sources=graphite` (master, no local changes) and it failed with:
```
Step 21/30 : run cd /opt/graphite/webapp/graphite && python manage.py syncdb --noinput
 ---> Running in e5b826a6da84
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
ERROR: Service 'graphite09' failed to build: The command '/bin/sh -c cd /opt/graphite/webapp/graphite && python manage.py syncdb --noinput' returned a non-zero code: 1
Makefile:144: recipe for target 'devenv' failed
make: *** [devenv] Error 1
```

**What you expected to happen**:
Building to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
```
make devenv sources=graphite
```

**Environment**:
- Grafana version: Current master
- Data source type & version: graphite
- OS Grafana is installed on: KDE neon 5.18 (based on Ubuntu LTS)

**Comment by domasx2** [comment]
encountered this as well when setting up devenv as part of onboarding.
Root cause is, graphite-web 9.1 does not specify version for sphinx, and latest one only works with python 3.
https://github.com/graphite-project/graphite-web/blob/0.9.x/requirements.txt#L39

**Comment by FZambia** [comment]
This fixed all problems during installation for me:
```diff
+run pip install twisted==13.2.0 && pip install sphinx==1.5.2 && pip install cairocffi==0.9.0
 run cd /usr/local/src/whisper && git checkout master && python setup.py install
-run cd /usr/local/src/carbon && git checkout 0.9.x && pip install -r requirements.txt; python setup.py install
-run cd /usr/local/src/graphite-web && git checkout 0.9.x && pip install -r requirements.txt; python check-dependencies.py; python setup.py install
+run cd /usr/local/src/carbon && git checkout 0.9.x && pip install -r requirements.txt && python setup.py install
+run cd /usr/local/src/graphite-web && git checkout 0.9.x && pip install -r requirements.txt && python check-dependencies.py && python setup.py install
```

I.e. explicitly installing versions that work with Python 2, also currently Docker image build does not exit with an error while installing dependencies (also fixed).

Though I don't see this graphite in datasources - is this non actual anymore?
