### ISSUE TITLE
Configurable Homelink Panel

### ISSUE THREAD

**Issue by ontari** [grafana/grafana#23062]
**What would you like to be added**:
Please make Homelink Panel configurable
https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/homelinks

**Why is this needed**:
We use grafana in our company and we want to use this panel with custom links and title

**Comment by dprokop** [comment]
@torkelo why is the homelinks panel not available for customisation?

**Comment by torkelo** [comment]
There was no time , was done last minute in 6.6

**Comment by dprokop** [comment]
@ontari homelinks panel will be removed in 7.4
