### ISSUE TITLE
Generic OAuth: Creating multiple user auth rows for the same user and provider 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#23077]
**What happened**:
Noticed in the `user_auth` database table that there were multiple rows for my user with `auth_module=oauth_generic_oauth`. On top of that, each time I login all the rows for my user and auth_models is updated which seems strange. 

| id | user_id | auth_module         | auth_id             | created        | o_auth_access_token | o_auth_refresh_token | o_auth_token_type   | o_auth_expiry | 
|----|---------|---------------------|---------------------|----------------|---------------------|----------------------|---------------------|---------------| 
| 20 | 24     | oauth_generic_oauth | | 2020-03-25 15:41:03 | `<access token>` | `<refresh token>`     | `<token type>`          | 2020-03-26 15:41:03 |               | 
| 21 | 24      | oauth_generic_oauth | | 2020-03-25 15:41:03 | `<access token>` | `<refresh token>`     | `<token type>`          | 2020-03-26 15:41:03 |               | 
| 22 | 24      | oauth_generic_oauth | | 2020-03-25 15:41:03 | `<access token>` | `<refresh token>`     | `<token type>`         | 2020-03-26 15:41:03 |               | 

**What you expected to happen**:
Only one row for the combination of `user_id`, `auth_module` and `auth_id`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login with a Generic OAuth provider. 
1. Logout
1. Login with same Generic OAuth provider in step 1.
1. Inspect `user_auth` database table. 

**Anything else we need to know?**:
This resolves to `false` in Generic OAuth use case: https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/sqlstore/user_auth.go#L31

Further down below this happens which at the end insert a new row in `user_auth` table:
https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/sqlstore/user_auth.go#L72-L113

Then later, all user_auth rows for that user and `auth_module` are updated if auth provider returned an OAuth token:  
https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/login/login.go#L85-L90

All in all, I find this very weird and wonder why [this](https://github.com/grafana/grafana/blob/4c2b191a8332aa66a671944908bd5d12947cf44a/pkg/services/sqlstore/user_auth.go#L31) logic exists. The only thing I can think of is supporting multiple Generic OAuth provider, but that's not something we do anyway. This is something we should fix.

In addition, we also need to think about if or how we need a migration to remove all duplicate rows. Had a customer reporting having 35000 rows for a single Generic OAuth user!

On another note, the `user_auth` table is in need of some refactoring/love. Only have a created column, no updated column. The created column is updated when a row is updated as explained above. This table also holds OAuth tokens and is related to another feature/problem #20515

Also related to #12131

**Environment**:
- Grafana version: master (bdb5659)

**Comment by marefr** [comment]
Seems like [this](https://github.com/grafana/grafana/commit/5a59cdf0ef4dbd1e0719fbdc469919f75b9b99cc#diff-0c749a6d44ed91483ae9fb5548899d2cR54) was the change introducing storing (duplicate) rows of Generic OAuth logins.

Previously the `user_auth` table was only used to track whether there was an external account with an id, but when it was changed to be used to track the tokens that check was removed.

The logic needs to be updated so that if it does find a user via user id, email or login lookup and there was no authquery result that it then looks up the user_auth record based on user.Id and query.Authmodule

**Comment by marcoboffi** [comment]
_The logic needs to be updated so that if it does find a user via user id, email or login lookup and there was no authquery result that it then looks up the user_auth record based on user.Id and query.Authmodule_

Now with Grafana 7.0.3 with Generic OAuth enabled, when a user login **for first time** after I have created it manually inside Grafana, it is duplicated inside user list (no match on email or username).
I would ask if with logic describe from @marefr should resolve this problem.
I would register users before their first login and pre-assign manually OrgID.

**Comment by marefr** [comment]
For anyone looking for a workaround/script to clean up/remove duplicates in the `user_auth` table using MySQL 5.6 or later.

1. Initial data
```bash
mysql> SELECT id, user_id, auth_id, created FROM user_auth WHERE auth_module = 'oauth_generic_oauth';
+----+---------+---------+---------------------+
| id | user_id | auth_id | created             |
+----+---------+---------+---------------------+
|  2 |       3 |         | 2020-09-23 16:31:54 |
|  3 |       3 |         | 2020-09-23 16:31:54 |
|  5 |       3 |         | 2020-09-23 16:31:54 |
|  7 |       4 |         | 2020-09-23 16:31:54 |
|  8 |       4 |         | 2020-09-23 16:31:54 |
| 10 |       4 |         | 2020-09-23 16:31:54 |
| 14 |       5 |         | 2020-09-23 16:31:54 |
| 15 |       5 |         | 2020-09-23 16:31:54 |
| 17 |       5 |         | 2020-09-23 16:31:54 |
| 19 |       5 |         | 2020-09-23 16:31:54 |
| 20 |       5 |         | 2020-09-23 16:31:54 |
| 22 |       5 |         | 2020-09-23 16:31:54 |
+----+---------+---------+---------------------+
12 rows in set (0.00 sec)
```
2. Query number of duplicates per user
This should return all rows that have duplicates grouped by user. In addition, a row number is generated for 
each user (partition) to be used later for filtering out latest row per user.
```bash
mysql> SET @row_number := 0; 
SELECT 
  @row_number := CASE WHEN @user_id = ua.user_id THEN @row_number + 1 ELSE 1 END AS num,
  ua.id,
  @user_id := ua.user_id AS user_id,
  duplicate_rows
FROM
(
  SELECT
    user_id,
    auth_module,
    count(*) as duplicate_rows
  FROM 
    user_auth   
  WHERE 
    auth_module = 'oauth_generic_oauth'
  GROUP BY
    user_id, auth_module
  HAVING 
    count(*) > 1
) as dt 
  INNER JOIN user_auth AS ua ON 
  ua.user_id = dt.user_id AND 
  ua.auth_module = dt.auth_module;
+------+----+---------+----------------+
| num  | id | user_id | duplicate_rows |
+------+----+---------+----------------+
|    1 |  2 |       3 |              3 |
|    2 |  3 |       3 |              3 |
|    3 |  5 |       3 |              3 |
|    1 |  7 |       4 |              3 |
|    2 |  8 |       4 |              3 |
|    3 | 10 |       4 |              3 |
|    1 | 14 |       5 |              6 |
|    2 | 15 |       5 |              6 |
|    3 | 17 |       5 |              6 |
|    4 | 19 |       5 |              6 |
|    5 | 20 |       5 |              6 |
|    6 | 22 |       5 |              6 |
+------+----+---------+----------------+
12 rows in set (0.01 sec)
```
3. Filter out all duplicates except last row for each user
Based on data in step 2 we can see that it filters out all rows except rows with the id of 5, 10 and 22, i.e. the latest 
created row for each user.
```bash
mysql> SET @row_number := 0; 
SELECT 
  *
FROM
(
  SELECT 
    @row_number := CASE WHEN @user_id = ua.user_id THEN @row_number + 1 ELSE 1 END AS num,
    ua.id,
    @user_id := ua.user_id AS user_id,
    duplicate_rows
  FROM
  (
    SELECT
      user_id,
      auth_module,
      count(*) as duplicate_rows
    FROM 
      user_auth   
    WHERE 
      auth_module = 'oauth_generic_oauth'
    GROUP BY
      user_id, auth_module
    HAVING 
      count(*) > 1
  ) as dt 
    INNER JOIN user_auth AS ua ON 
    ua.user_id = dt.user_id AND 
    ua.auth_module = dt.auth_module
) AS dt2
WHERE 
  dt2.num < dt2.duplicate_rows;
+------+----+---------+----------------+
| num  | id | user_id | duplicate_rows |
+------+----+---------+----------------+
|    1 |  2 |       3 |              3 |
|    2 |  3 |       3 |              3 |
|    1 |  7 |       4 |              3 |
|    2 |  8 |       4 |              3 |
|    1 | 14 |       5 |              6 |
|    2 | 15 |       5 |              6 |
|    3 | 17 |       5 |              6 |
|    4 | 19 |       5 |              6 |
|    5 | 20 |       5 |              6 |
+------+----+---------+----------------+
9 rows in set (0.00 sec)
```
4. Delete duplicates
Based on query in step 3 we only select the id column to get the actual rows to delete and use that as input for the delete statement.
```bash
mysql> SET @row_number := 0; 
DELETE FROM user_auth 
WHERE id IN(
  SELECT
    dt2.id
  FROM
  (
    SELECT 
      @row_number := CASE WHEN @user_id = ua.user_id THEN @row_number + 1 ELSE 1 END AS num,
      ua.id,
      @user_id := ua.user_id AS user_id,
      duplicate_rows
    FROM
    (
      SELECT
        user_id,
        auth_module,
        count(*) as duplicate_rows
      FROM 
        user_auth   
      WHERE 
        auth_module = 'oauth_generic_oauth'
      GROUP BY
        user_id, auth_module
      HAVING 
        count(*) > 1
    ) as dt 
      INNER JOIN user_auth AS ua ON 
      ua.user_id = dt.user_id AND 
      ua.auth_module = dt.auth_module
  ) AS dt2
  WHERE 
    dt2.num < dt2.duplicate_rows
);
Query OK, 9 rows affected (0.01 sec)
```
5. Verify delete was successful
```bash
mysql> SELECT id, user_id, auth_id, created FROM user_auth WHERE auth_module = 'oauth_generic_oauth';
+----+---------+---------+---------------------+
| id | user_id | auth_id | created             |
+----+---------+---------+---------------------+
|  5 |       3 |         | 2020-09-23 16:31:54 |
| 10 |       4 |         | 2020-09-23 16:31:54 |
| 22 |       5 |         | 2020-09-23 16:31:54 |
+----+---------+---------+---------------------+
3 rows in set (0.00 sec)

mysql> SELECT
  user_id
FROM 
  user_auth   
WHERE 
  auth_module = 'oauth_generic_oauth'
GROUP BY
  user_id
HAVING 
  count(*) > 1;
Empty set (0.00 sec)
```

**Comment by grzkv** [comment]
We at Booking.com were strongly impacted by this issue. We had almost 100k of rows for a single `user_id`. Grafana tried to update all of them when doing an update for that `user_id`. This created a positive feedback loop that caused DB overload.

It would be nice if this was prioritized!

**Comment by jangaraj** [comment]
@grzkv I have also Grafana instance, where provided "maintenance SQL" must be executed once per month, otherwise it will kill DB replication. IMHO it is user edge case only: it is caused by monitoring in my case, because monitoring user opens new session for each monitoring check. So it would be nice to have it, but I can live with it.

**Comment by marefr** [comment]
With #32286 fixing that multiple user auth rows are created for the same user and generic OAuth provider we have solved that problem. However, still TBD if we can or want to do anything in regards to removing duplicates. It could be tricky to solve using a database migration like workaround script above since we need to support 3 sqlite, mysql and postgres. Perhaps possible using a code migration, but if users had several thousands (100k) rows for a single user the migration might have performance issues. 

Another alternative could be to implement a grafana-cli task for removing duplicates and that can be run on demand.
Another alternative could be to just explain in [upgrade docs](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrade-grafana) how to manually remove duplicates referencing above scripts.

@dsotirakis thoughts?

**Comment by dsotirakis** [comment]
@marefr 

I'd say a combination of those:

>Another alternative could be to implement a grafana-cli task for removing duplicates and that can be run on demand.
Another alternative could be to just explain in upgrade docs how to manually remove duplicates referencing above scripts.
