### ISSUE TITLE
graphite query engine adds 'select metric' to query

### ISSUE THREAD

**Issue by robochat** [grafana/grafana#2307]
I have a small issue with the graphite query engine when my queries return a mixture of leaves and branches. I'm using grafana 2.1.0-pre1 that I compiled yesterday.

When I use a glob, grafana adds a 'select metric' button but also adds that phrase to the query itself and so the query fails. I can edit the query manually and it then works but it seems like a bug.

ie.
I'm getting

    traffic.filtered.new.*.select metric

but I want

    traffic.filtered.new.*

**Comment by Dieterbe** [comment]
+1 saw this a lot at Vimeo. Never figured out if something was wrong with graphite-api, graphite-influxdb or grafana.

**Comment by torkelo** [comment]
Its not really possible to solve this without messing up other scenarios (where you want a select metric), so to solve this case I made the text editor mode (using pen icon) persisted property (sets textEditor: true on the query, the parse will and query validator will not run)
