### ISSUE TITLE
Adding dashboard and panel name as a comment in backend query

### ISSUE THREAD

**Issue by irumman** [grafana/grafana#23085]
Hi,

We are using Grafana with Postgresql backend.
Is it possible to add the dashboard name and panel name as a comment in sql query?

For example:

> Dashboard Name: "Test Dashboard"
> Panel Name: "Test Panel"

Sql:
`SELECT time, name, value FROM table1 WHERE $__timeFilter("time")
`
In database logs, we want to see like:
```
-- Test Dashboard: Test Panel
SELECT time, name, value FROM table1 WHERE time BETWEEN '2020-02-20 00:00:00' AND ''2020-02-20 01:00:00'
```

Thanks.

**Comment by aknuds1** [comment]
Please direct questions to our community [forums](https://community.grafana.com/) or [Slack](http://slack.raintank.io/). We use GitHub issues for bugs or feature requests.
