### ISSUE TITLE
Contributor License Agreement link broken

### ISSUE THREAD

**Issue by retzkek** [grafana/grafana#23082]
The [link to the CLA](https://grafana.com/docs/contribute/cla/) from the [contributing guide]( https://github.com/grafana/grafana/blob/master/CONTRIBUTING.md) is being redirected to https://grafana.com/docs/grafana/latest/contribute/cla/ which is returning a 404.

Maybe the link should just point straight to the [CLA Assistant](https://cla-assistant.io/grafana/grafana) page?

**Comment by torkelo** [comment]
Introduced by markdown file rename here: 
https://github.com/grafana/grafana/pull/21806
