### ISSUE TITLE
InfluxDB: numbers-as-strings do not work in alerting

### ISSUE THREAD

**Issue by mripv6** [grafana/grafana#23081]
**What happened**:

Unable to retrieve data for an alert. Using influxDB and a simple measurement. The query from the grafana log file looks like this:

curl -G 'http://localhost:8086/query?db=temps&epoch=s&q=SELECT+%22value%22+FROM+%22rackTemp%22+WHERE+time+%3E+now%28%29+-+5m'

{"results":[{"statement_id":0,"series":[{"name":"rackTemp","columns":["time","value"],"values":[[1585162363,"74"],[1585162483,"74"],[1585162603,"72"]]}]}]}

Note the order of the time/value is [time,value]. 

However, when I test the Alert Rule, the query results within Grafana shows this:

message:"Condition[0]: Query Result"
data:Object
series:Array[1]
0:Object
name:"rackTemp.value"
points:Array[3]
0:Array[null,1585162363]
1:Array[null,1585162483]
2:Array[null,1585162603]
2:Object
message:"Condition[0]: Eval: false, Metric: rackTemp.value, Value: null"
data:null

Note - these are two different queries in time, but the results is always the same. The returned results shows an array with [null, time] I'm also running grafana and influxdb in docker containers. rackTemp.value is not a template variable. 

**What you expected to happen**:

I expected the Alert Rule Test to return values for rackTemp as [time,value]. The query inspector returns values correctly ordered.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure how to be minimal! I created an influx db with a single measurement. (rackTemp). A Node-Red flow writes to the database about once a minute. I created a datasource (rptTemps) in grafana and then I created a dashboard to graph the temp using a simple query as follows:

SELECT "value" FROM "rackTemp" WHERE $timeFilter

The query inspector returns an array with many [time,value] objects, as expected and the data are plotted in the graph.
 
Then, I created a simple alert rule to evaluate every 1m for 5m. The condition is "when avg() of query(A,5m,now) is above 50". The temp values are above 50. In the log, I can see the URL used to query the influxDB, which is shown above. When I use curl to query the DB, I get results as expected as shown above.

However - when I test the alert rule, this is the result. (sorry for the length, I waned to show the entire results.) The returned point values are shown as [null,time]. I expected them to be [time,value] as returned by the query inspector. It's because of this that the result is no (null) data.

{
  "firing": false,
  "state": "no_data",
  "conditionEvals": "false = false",
  "timeMs": "1.890ms",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1585230966697,
        "queries": [
          {
            "refId": "A",
            "model": {
              "groupBy": [],
              "measurement": "rackTemp",
              "orderByTime": "ASC",
              "policy": "default",
              "query": "SELECT \"value\" FROM \"rackTemp\" WHERE $timeFilter",
              "rawQuery": true,
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "field"
                  }
                ]
              ],
              "tags": []
            },
            "datasource": {
              "id": 2,
              "name": "rptTemps"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1585231266697
      }
    },
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "series": [
          {
            "name": "rackTemp.value",
            **"points": [
              [
                null,
                1585231045
              ],
              [
                null,
                1585231165
              ]**
            ]
          }
        ]
      }
    },
    {
      "message": "Condition[0]: Eval: false, Metric: rackTemp.value, Value: null",
      "data": null
    }
  ]
}
![Screenshot at 2020-03-26 10-01-42](https://user-images.githubusercontent.com/16615892/77656529-615d7800-6f4a-11ea-9311-6ffece0abf13.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: influxdb 1.7.10
- OS Grafana is installed on: Linux Mint using docker-compose
- User OS & Browser: Firefox
- Grafana plugins: None
- Others:

**Comment by flopp999** [comment]
If you have a screenshot of the query in Grafana I think it is easier to understand if there is an error

**Comment by aknuds1** [comment]
Please fill in the _How to reproduce it (as minimally and precisely as possible):_ section.

**Comment by mripv6** [comment]
Sure - I edited the OP to include more detail. I hope this is sufficient without being too long! Thanks for looking at this.

**Comment by aknuds1** [comment]
What do you mean by "A nodered process"?

**Comment by mripv6** [comment]
I have a nodered flow that connects to a MQTT broker, processes the data (converts from degrees C to degrees F) and writes the data to the influxDB. A sample of the data in the influxDB is listed below. It's a single measurement.

> select * from rackTemp where time > now() - 15m
name: rackTemp
time                value
----                -----
1585231645496502936 64
1585231765556712053 64
1585231885629802406 64
1585232005701477238 64
1585232125776094944 64
1585232245853933043 64
1585232365925137132 64
1585232485978396866 64

**Comment by aknuds1** [comment]
By "nodered" you mean [Node-RED](https://nodered.org/)?

**Comment by mripv6** [comment]
Yes.

**Comment by aknuds1** [comment]
OK, first time I ever heard of it.

**Comment by gabor** [comment]
@mripv6 nevermind, i can reproduce it now, probably...

how to do it:
- store numeric values as strings in influxdb
- if you draw it into a graph, then it those numbers-in-strings get automatically converted to numbers, and all is good
- alerting does not do this conversion, so for alerting it seems there are no values available.

**Comment by gabor** [comment]
with thinking more about this problem, i think we will consider using numbers-in-strings unsupported. i don't recommend relying on the fact that it is currently possible to graph such data. this might change in the future.

i recommend converting that data to real numbers.

one possible workaround could be to access the data using the flux language, where it is possible to convert strings to numbers for example with this function https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/type-conversions/tofloat/
