### ISSUE TITLE
Panel menu's submenu is not visible when panel is on the right side of the screen

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#23095]
**What happened**: If a Table's on the right side of the screen, the sub-contents of the "More..." menu cannot be accessed.

**How to reproduce it (as minimally and precisely as possible)**: Create a narrow Table to the right side of the screen and try to export to CSV. 

**Environment**:
- Grafana version: v6.7.1 (ca6d08d5cb)
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome 80.0.3987.100 (64 bit)

![image](https://user-images.githubusercontent.com/2911588/77623069-bcd63880-6f3f-11ea-9418-9d9e58f4f056.png)

**Comment by aknuds1** [comment]
Hello, can you please rewrite the description of the issue according to the standard template?
