### ISSUE TITLE
Minimum refresh interval blocks dashboard from copying 

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#23099]
**What happened**:

settings `GF_DASHBOARDS_MIN_REFRESH_INTERVAL=30s` blocks copying dashboards from external grafana (e.g. grafana playground) 

**What you expected to happen**:

setting minimum refresh interval to 30s

**How to reproduce it (as minimally and precisely as possible)**:

run docker image with grafana 2.7 locally with `GF_DASHBOARDS_MIN_REFRESH_INTERVAL=30s`, try to copy dashboard from grafana playground with less interval or with refresh interval = off

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment]
Hi, thanks for submitting this. I could verify this behaviour.
The blocking of a lesser interval could be debated if it is a feature request and how it should behave.
But no interval should always be imported (in my opinion) so I classified this a s a bug

**Comment by jongyllen** [comment]
A workaround for this until fixed s to copy the json and set the refresh interval in the json to your minimum. That allows you to import the dashboard. You can then set it to off manually if you wish
