### ISSUE TITLE
Wrong Unit for Total value of data rates

### ISSUE THREAD

**Issue by HackHerz** [grafana/grafana#23096]
**What happened**:
The Grafana Graph has the unit configured as bits/sec, a data rate. The __Total__ Value of the Legend uses the same Unit. Screenshot below.

![2020-03-26_084231_window](https://user-images.githubusercontent.com/2885148/77622722-0f632500-6f3f-11ea-9c91-4739a07a4b0d.png)

**What you expected to happen**:
As the Total value of the Legend is the integral of the graph over time the Unit has to drop the per second part. I expect the Unit to be _bits_.

**How to reproduce it (as minimally and precisely as possible)**:
* Set Unit to bits/sec
* Activate Total Values for the Legend

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Prometheus 2.16.0
- OS Grafana is installed on: I am running the latest Docker container
- User OS & Browser: Arch Linux, Firefox 74.0

**Comment by torkelo** [comment]
No the total is just the sum of all the values your query returned, (so showing the total and avg can be very inaccurate depending on what aggregation your query is doing on the backend)
