### ISSUE TITLE
Docs feedback: /auth/azuread.md

### ISSUE THREAD

**Issue by swordfischer** [grafana/grafana#23094]
> Every role has to have a unique id. On Linux this can be created with `uuidgen` for instance.

with Windows it can be created through PowerShell with `New-Guid` :)

**Comment by RobinJoe** [comment]
I am working on this issue. Proposed change: Add the line on generating a uuid with Windows PowerShell, and adjusting the word choice of Step Nine to clarify that it is important to create specific user  role based on the view, edit, and administrate actions. I will also check the azuread.md file with the [Style Guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md).

**Comment by achatterjee-grafana** [comment]
Hi @RobinJoe, do you know when you will be able to finish PR https://github.com/grafana/grafana/pull/27323. Thanks for any updates.
