### ISSUE TITLE
Viewer users can export/view Dashboards?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2309]
Hi. I'm working as a Viewer user and I can export/view dashboard json. 

![image](https://cloud.githubusercontent.com/assets/5883405/8570749/e13e0ca4-2582-11e5-9496-8252a3cf3095.png)

IMHO Viewer users shouldn't be able to view metric names/paths/functions if not explicitly explained somewhere by the dashboard editor user

Export and View JSON is a useful tool for editor users but not for viewer users.

**Comment by torkelo** [comment]
I agree

**Comment by utkarshcmu** [comment]
This will be the view for a viewer, without the "Manage dashboard" button.

<img width="541" alt="screen shot 2015-10-26 at 11 33 52 pm" src="https://cloud.githubusercontent.com/assets/1019609/10751091/26ccf114-7c3a-11e5-9424-891ae98c638d.png">

**Comment by torkelo** [comment]
but view json and export (same as view json basically) are view operations

**Comment by utkarshcmu** [comment]
I read the above comments made by @toni-moreno and you, and both agreed that export JSON / View JSON is more useful to the editors and not to the viewers, which IMO make sense too as what will a viewer do except seeing the graphs/panels with properly marked labels and legends. I am not sure whether a viewer should be allowed to see the metrics and other dashboard details via View JSON. 

But if you think that keeping these options for the viewer is the vision for Grafana, then viewers can have these options to play with.

**Comment by torkelo** [comment]
@utkarshcmu I can see that having he cog icon and these menu options are not really that useful for viewers, but all the info (the complete dashboard json) is available to anyone who opens chrome dev tools and looks at the network traffic. Hiding these menu options is no way hiding the metric names or queries to anyone who want to see them. The reason I asked was to just get a picture of your reason for wanting the options hidden for viewers. 

I mean it could be scenarios where a viewer want to export the dashbord json and import it to their organization (where they have editor access) and its another data source but same metric structure. So there could be limited use cases for viewers wanting to export dashboard json.

**Comment by balda** [comment]
When a `viewer user` click on the burger menu of a panel, then on `Panel JSON`, the `Update` button is still here, and works. So a `viewer user` can change panels. Maybe you just can hide this button for viewers?

**Comment by utkarshcmu** [comment]
@balda The fix is ready to merge: #3051 :)

**Comment by balda** [comment]
@utkarshcmu thanks! :)

**Comment by utkarshcmu** [comment]
@torkelo Any decisions on this feature yet?
