### ISSUE TITLE
Datasource provisioning from environment variable is not working

### ISSUE THREAD

**Issue by RamanPndy** [grafana/grafana#23097]
**What happened**:
I've provisioned the Prometheus data source and trying to read the value from the environment variable when the docker container runs. but it's not taking the variable from the environment.

Please suggest what I'm missing here.

**What you expected to happen**:
Provisioned datasource should take value from the environment variable.
as per the doc : https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables
**How to reproduce it (as minimally and precisely as possible)**:
below is the datasource provisioned yml file:
datasources:
- name: 'customprometheus'
  type: 'prometheus'
  access: 'proxy'
  org_id: 1
  url: "$DATASOURCE"
  is_default: true
  version: 1
  editable: true

and following environment variables I defined and none of them it's taking when grafana starts.
ENV_VAR_DATASOURCE: https://customprometheus.test.com
DS_DATASOURCE: https://customprometheus.test.com
DATASOURCE: https://customprometheus.test.com

when grafana starts, I can see the datasource there but instead of URL i'm seeing the variable
$DATSOURCE.

Please suggest how i can resolve this ??
**Anything else we need to know?**:

**Environment**:
- Grafana version: latest docker image
- Data source type & version: prometheus
- OS Grafana is installed on: ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment]
Hi, Have you tried removing the quotes around `"$DATASOURCE"` in your yaml file? Looks like they should not be there in the documentation?

**Comment by SergeySmile** [comment]
Check your grafana version. Had a same issue with old version of grafana. It works on 6.7.2 for me, support [added in 6.2](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-2/) (not sure)

**Comment by GuilhermeMontemovo** [comment]
Hi, please add 
`apiVersion: 1`
to the top of your datasource provisioned yml file

**Comment by marefr** [comment]
This feels like configuration error so closing this.

**Comment by manarth** [comment]
Note for future visitors: `systemd` uses a specific EnvironmentFile for Grafana: `/etc/sysconfig/grafana-server`.
The values in `/etc/environment` (or Docker-configured environment variables) don't appear to be used by systemd.

**Comment by ermate** [comment]
@GuilhermeMontemovo suggested the right idea... I had the same problem. For some reason variables don't get parsed if you don't define `apiVersion` explicitly.
