### ISSUE TITLE
No indication of same folder name and dashboard name

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#23103]
**What happened**:
I tried to save a dashboard named "Strava" in the folder "Strava". It turns out this is not possible. However, there was no indication in the UI that the dashboard had not been saved. The save modal just kept appearing.

**What you expected to happen**:
I expected some information that there was an error saving the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a folder "test".
2. In that folder create a new dashboard.
3. Go to the dashboard settings and change the title to "test".
4. Hit save dashboard. 
5. Navigate away from the dashboard, you will be prompted to save or discard your changes.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version: n/a
- OS Grafana is installed on: ubuntu lts
- User OS & Browser:ubuntu lts/ chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@peterholmberg is this a regression introduced with work aruond dashboard save and folder picker?
Also feels like a #22966 is a duplicate

**Comment by peterholmberg** [comment]
@dprokop yes it's a duplicate
