### ISSUE TITLE
Docs: mention how logging in the docker container is configured

### ISSUE THREAD

**Issue by abualy** [grafana/grafana#23102]
Information
**What Grafana version are you using?**
v6.5.2
**What datasource are you using?**
/
**What OS/platform are you running grafana on?**
kubernetes cluster
**What did you do?**
tried to access grafana log file `/var.log/grafana/grafana.log`
```bash
kubectl exec -it GRAFANA_POD -- ls -lsa /var/log/grafana
```
have default config from regarding logs (which is for log.mode= console file) as stated in https://grafana.com/docs/grafana/v6.5/installation/configuration/

**What happened instead?**
no grafana log file existent, which means that for default config file for docker image have log.mode= console
**Change request**
make it explicitly stated in the docs somewhere that default in docker image of grafana is only console for log.mode 

Thank you!

**Comment by oddlittlebird** [comment]
@xlson, can you look into this?

**Comment by xlson** [comment]
You're correct, the default for the docker image is console, since most dockerized environments allow you to get access to the console log from the process. We'll update the docs.
