### ISSUE TITLE
Document AzureMonitor provisioning example

### ISSUE THREAD

**Issue by secustor** [grafana/grafana#23109]
**What would you like to be added**:
An example of the AzureMonitor datasource model should be added to the docs to improve the onboarding of new users. 
Such an example exists already for [Cloudwatch](https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#configure-the-data-source-with-provisioning), but not for AzureMonitor. 

**Why is this needed**:
If you come fresh to provisioning, an user has to rely on reverse engineering or very old [issues](https://github.com/grafana/grafana/issues/18849) which have been created before the datasource has become a core feature Grafana.

**Comment by daniellee** [comment]
There is a section for this in the docs already: https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/#configure-the-data-source-with-provisioning
