### ISSUE TITLE
InfluxDB 0.9 enhancement, support field lookup and other field names than value, also support multiple fields in query

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2311]
InfluxDB 0.9 enhancement, support field lookup and other field names than value, also support multiple fields in query

**Comment by cemo** [comment]
:tada:

**Comment by torkelo** [comment]
![field_and_funcs](https://cloud.githubusercontent.com/assets/10999/8599069/9d08362c-265e-11e5-8318-0caad1996bcf.gif)

**Comment by philipspigelmire** [comment]
Looks good, thank you!
