### ISSUE TITLE
[Feature Request] Better edit mode for multiple editors

### ISSUE THREAD

**Issue by jregovic** [grafana/grafana#23116]
**What would you like to be added**:
An edit mode for dashboards to prevent concurrent edits from overwriting one another.

**Why is this needed**:
When using a shared dashboard, multiple users can all edit the same dashboard at one time, with the last saved edit taking precedence. This can result in lost edits, alerts, or confusing updates. 

A mode where a single user can acquire a lock for editing would be useful. The lock could then be used to notify users that the dashboard is being edited and prevent simultaneous edits.

**Comment by torkelo** [comment]
You can a clear warning that you will be overwriting someone else change if two makes changes at the same time
