### ISSUE TITLE
Should use field name, not metric name, for labels (InfluxDB 0.9 data source)

### ISSUE THREAD

**Issue by fxkr** [grafana/grafana#2312]
<img src="http://paste.fxkr.net/chaimaib4ooc/screenshot-grafana.png" />

Grafana chooses to name the series by the metric name, which is useless when you're displaying multiple fields from one metric. The field name should be used instead. (You also can't rename the metric with something like `FROM port_stats AS rx_packets` because InfluxDB only allows `AS` for fields.)

**Comment by torkelo** [comment]
what version are you using?

**Comment by fxkr** [comment]
Sorry, my fault. Development version uses "metric.field" as label, which is ok.

(I was in the wrong directory, I had accidentially run the stable version all the time when I thought I had the development version. Oopsie.)
