### ISSUE TITLE
Some custom namespaces missing from namespaces() query

### ISSUE THREAD

**Issue by chrs-myrs** [grafana/grafana#23134]
**What happened**:
When I add available query for namespaces, it does not always return the namespace I want.  It does not return custom namespaces created by a log group filters.  Other custom namespaces (e.g. those from cloudwatch agent) are available.
Since I want to auto-select the namespace based on the AWS account, my account-switching dashboards won't work without this.

**What you expected to happen**:
I'd expect all the namespaces listed in the cloudwatch metrics console page to be returned by the `namespace()` query.  These namespaces are returned by a console call to `aws cloudwatch list-metrics`.  This did previously work, but has stopped working, perhaps with a Grafana upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
Create a metric with a custom namespace using a log group filter, ensure there is some data in it and that the metric is returned by `aws cloudwatch list-metrics |: grep namespace`.  Link to grafana and create a variable using the `namespaces()` query, it does not return the new namespace.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.6.0 (5c11bbdfb4)
- Data source type & version: Cloudwatch
- OS Grafana is installed on: CentOs
- User OS & Browser: Ubuntu FireFox
- Grafana plugins: All standard + AWS Athena Plugin
- Others:

**Comment by mmazek** [comment]
We also have the same issue, where custom namespaces are not returned by `namespaces()` function. Can someone look into that?

**Comment by daniellee** [comment]
@chrs-myrs sorry for the long delay. But I don't think this has ever worked automatically (I checked back to 2018).

The data source has always used a hardcoded list of allowed metrics combined with a manual list of custom namespaces (that are defined in the config page). I'll investigate if it is possible to do something more user friendly.

**Comment by markuman** [comment]
I agree, Custom Metrics must be names manuelly in the data source.  
but what does not work anymore since 7.2 is, that it fetchs automatically available metric names. that does not work anymore

**Comment by chrs-myrs** [comment]
I realise you can't call a list of namespaces direct from CW, but a reckon they could easily be pulled from a get-metrics call.  I wonder if this response data could be cached internally and refreshed periodically so that namespaces and metrics were easily accessible

**Comment by chrs-myrs** [comment]
> The Cloudwatch data source is largely unusable for custom namespaces, there are so many bugs I can't unpick them. Wildcards don't work in dimension values, exact match doesn't return data when it should, and turning off exact match returns too much data. Also the dimension value labels in the series name don't work at all.

This has gotten a lot better now, thanks for all the deliberate and coincidential work put in here to improve things.  It would be helpful to solve this specific issue, as it's a pain to manage the custom namespaces across our 11 data sources.  It's manageable though.

**Comment by sunker** [comment]
It's possible to get namespaces for the [getmetrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html) api, but it has a few limitations. For example, it will only return those metrics that have reported data over that last two weeks. It would be great if we could get rid of the hard coded list of metrics/namespaces, but I don't think that possible at the moment. I think the best solution will be to call getMetrics and merge the result with the hard coded list, as suggested [here](https://github.com/grafana/grafana/issues/28382#issuecomment-712511622).

> > The Cloudwatch data source is largely unusable for custom namespaces, there are so many bugs I can't unpick them. Wildcards don't work in dimension values, exact match doesn't return data when it should, and turning off exact match returns too much data. Also the dimension value labels in the series name don't work at all.

> This has gotten a lot better now, thanks for all the deliberate and coincidential work put in here to improve things. It would be helpful to solve this specific issue, as it's a pain to manage the custom namespaces across our 11 data sources. It's manageable though.

Please create new issues for the problems that you encounter!

**Comment by vickyyyyyyy** [comment]
I'm afraid this will be hard to solve without an API change - please see this issue for further details: https://github.com/grafana/grafana/issues/30977 Feel free to re-open if you have any further suggestions on how to solve this. Thanks!
