### ISSUE TITLE
Alerting on Azure Log Analytics

### ISSUE THREAD

**Issue by ssrb89** [grafana/grafana#23136]
Unable to create alerts on metrics collected from Azure Log Analytics.
Error: *tsdb.HandleRequest() error Alerting not supported for Azure Log Analytics*

 Grafana Version: 6.6.2

**Comment by jongyllen** [comment]
Hi, thanks for submitting this. Can you please provide a bit more details on how to reproduce this and use our standard template for submitting issues?

**Comment by kylebrandt** [comment]
As per documentation (or at least current documentation) Alerting for Log analytics was added / only available in 7.0+ 

https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/#azure-log-analytics-alerting

(Note 7.1 is being released soon, and changes Azure implementation some, so probably best to go straight for 7.1 for Log Analytics alerting.)
