### ISSUE TITLE
some issue with google authentication using oauth

### ISSUE THREAD

**Issue by vadirajks** [grafana/grafana#23146]
Hi All,
sorry i don't have knowledge on oauth, need help to change this redirect url http://localhost:3000/login/google which i see nowhere defined in the conf and I am unable to figure out how to authenticate with google.
++++++++++++++++
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:3000/login/google, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/337589215400-ghqacl5h03et1abral5srl48d3bj0vkd.apps.googleusercontent.com?project=337589215400
+++++++++++++++++++

https://accounts.google.com/o/oauth2/auth?access_type=online
&client_id=337589215400-ghqacl5h03et1abral5srl48d3bj0vkd.apps.googleusercontent.com
&hd=test.io
&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgoogle&response_type=code
&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
&state=3VLZXtFBXN6k2oXbq47GBakMQnuMbqtnYi7R1jsw8S8%3D

By change the localhost with the hostname used in google oauth i see below error but i am able to authenticate:

![image](https://user-images.githubusercontent.com/2026134/77758467-06667680-7059-11ea-95c8-7451cd9a1d50.png)

I see same error with diff version of grafana and I guess something wrong with my conf file. 
Please let me know.
Thanks

**Comment by aknuds1** [comment]
Sorry, please go to our community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io/) for support. GitHub issues are for bug reports and feature requests.
