### ISSUE TITLE
Admin: restoring to older version appears to display modal behind dashboard settings page

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#23148]
**What happened**:
Please have a look at the following image:

![bug](https://media.giphy.com/media/dyd7ASqzr6YtzPZLi4/giphy.gif)

**What you expected to happen**:
The modal asking the user to confirm the restore should appear on top of the settings view.

**How to reproduce it (as minimally and precisely as possible)**:
See video

**Anything else we need to know?**:
Don't think so

**Environment**:
- Grafana version: 6.7.1
- User OS & Browser: Chrome 80.0.3987.149

**Comment by torkelo** [comment]
I do not think you are on 6.7.1 but on latest master/nightly build of 7.0 

But still a bug, will fix asap. Thanks for reporting !
