### ISSUE TITLE
Keyboard Input in PromQL Query broken in Firefox Dev Edition

### ISSUE THREAD

**Issue by benaryorg** [grafana/grafana#23154]
**What happened**: while in the PromQL query field with a query present in the middle of the query I started holding backspace, the UI did delete characters both left and right of the cursor

**What you expected to happen**: characters on the left side of the cursor being deleted until there are no more characters, right part remaining unchanged

**How to reproduce it (as minimally and precisely as possible)**:

1. head over to any [PromQL Query on play.grafana.org](https://play.grafana.org/explore?orgId=1&left=%5B%22now-2h%22,%22now%22,%22Robust%20perception%22,%7B%22expr%22:%22rate(process_cpu_seconds_total%5B5m%5D)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
2. click somewhere in the middle of the query in the textfield
3. hold backspace

**Anything else we need to know?**: (unrelated but in general: do not override cursor, scroll, or keyboard shortcut behaviour (like Ctrl+L), that's browser domain, not yours)

**Environment**:
- Grafana version: Grafana v6.7.1 (ca6d08d5cb) (at time of writing)
- Data source type & version: (no idea how to find out from play.grafana.org)
- OS Grafana is installed on: (no idea how to find out from play.grafana.org)
- User OS & Browser: macOS High Sierra, Firefox Aurora/Developer Edition 75.0b8, does not seem to affect Chrome on the same OS
- Grafana plugins: likely a great deal (see play.grafana.org)

**Comment by Estrax** [comment]
@benaryorg Thanks for reporting. That was most likely a problem with a given build of Firefox Developer Edition. Works flawlessly under all beta builds of Firefox Aurora 76.0. Closing that issue.
