### ISSUE TITLE
Toolkit should better support ES6 imports 

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#23156]
In a plugin, we imported the ES6 module [countries-and-timezones](https://www.npmjs.com/package/countries-and-timezones)

This works fine on modern browsers, but old verions of Edge fail to load.

Toolkit should either:
* warn/fail saying you can't use ES6 module
* use babel to convert to ES5

**Comment by ryantxu** [comment]
Any thoughts on this @stevenvachon @dprokop ?  this has caused a pretty frantic morning with an enterprise customer

**Comment by stevenvachon** [comment]
That library still [uses CommonJS modules](https://github.com/manuelmhtr/countries-and-timezones/blob/master/src/index.js#L56), but it does use some ES2015 features, such as `const`. The toolkit uses [@babel/preset-env](https://npmjs.com/@babel/preset-env) which, via its default configuration, is currently transpiling to support the ["last two versions" of popular browsers](https://github.com/browserslist/browserslist#full-list).

The main problem, is that we are not transpiling dependencies, which is a common best practice to avoid even longer build times.

I'd recommend creating a PR for that dependency to have ES5 code published, either via a Babel build or by changing the source code.

**Comment by stevenvachon** [comment]
Fixed in https://github.com/manuelmhtr/countries-and-timezones/pull/15

**Comment by ryantxu** [comment]
this is pretty old
