### ISSUE TITLE
Prometheus histogram series all have same label

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#23163]
0. Prometheus datasource in Explore
1. Run query `histogram_quantile(0.95, sum(prometheus_http_request_duration_seconds_bucket) by (le,handler))`

Result: all queries have same name.
Expected: series names different, based on `metric` field in response matrix.

![Screenshot 2020-03-28 at 20 08 19](https://user-images.githubusercontent.com/859729/77831514-e81f7a00-712f-11ea-927e-ee689d9645c1.png)

**Comment by s-h-a-d-o-w** [comment]
This may have been addressed already:

![Screenshot from 2020-04-29 14-29-50](https://user-images.githubusercontent.com/16936908/80596010-f6f69680-8a25-11ea-97a1-d30b605506d5.png)

**Comment by ivanahuckova** [comment]
Yeah, I also checked it and the issue has been fixed. It is already fixed on [play](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Robust%20perception%22,%7B%22expr%22:%22histogram_quantile(0.95,%20sum(prometheus_http_request_duration_seconds_bucket)%20by%20(le,handler))%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) as well. Closing the issue.
