### ISSUE TITLE
Data source proxy and required signed certificates 

### ISSUE THREAD

**Issue by sandramadhu** [grafana/grafana#2316]
I am trying to configure graphite as a datasource in grafana. But to access my graphite endpoint it needs a signed certificate. 

For eg: If I do this in curl by providing the cert and key, it works.
curl -v --key my.key --cert my.pem "https://graphite-api.mycompany.com/dashboard/find/?query="

How can I do the same thing in grafana?

**Comment by sandramadhu** [comment]
Looks like if there is a way to set the cert and key when we create the tls connection usinf function LoadX509KeyPair(..) in file dataproxy.go might work?

**Comment by torkelo** [comment]
the data source proxy does not support this yet :(

**Comment by sandramadhu** [comment]
can this be made a new feature request? possible to get this in the next version?

**Comment by torkelo** [comment]
@sandramadhu maybe if a PR is made, since you are the first to request this it will have very low prio (unless more need this)

**Comment by ebradham** [comment]
+1

**Comment by daniellee** [comment]
Fixed by #6692
