### ISSUE TITLE
Transparent panels in Dark Mode 

### ISSUE THREAD

**Issue by ortizleo** [grafana/grafana#23169]
Hello.

Transparent panels are not totally transparent using Dark theme in grafana 6.7.1.
Background is not "full dark" making panels not transparent.
Confirmed with Chrome and Firefox in different workstations.
Grafana 6.7.1 in Centos 7.7.

Example attached.

To reproduce, create a panel using "Text", then check "Transparent" and go to kiosk.

![grafana dark](https://user-images.githubusercontent.com/17042298/77835585-ee602700-712c-11ea-8811-81a25d690efd.png)
![grafana dark1](https://user-images.githubusercontent.com/17042298/77835721-3fbce600-712e-11ea-802d-8dae75dfb47a.png)

**Comment by dprokop** [comment]
@ortizleo thanks for reporting this. We do not plan to fix this particular issue before 7.0. Please be patient - in 7.0 we plan to introduce some look and feel updates that will address this issue.
