### ISSUE TITLE
Graph legend is not cleared in Explore

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#23165]
0. Explore with Prometheus
1. Run query `histogram_quantile(0.95, sum(prometheus_http_request_duration_seconds_bucket) by (le,handler))`
2. Run query `histogram_quantile(0.95, sum(alertmanager_http_request_duration_seconds_bucket) by (le))`

Result: legend from first query is still shown.

![Screenshot 2020-03-28 at 20 12 54](https://user-images.githubusercontent.com/859729/77831639-b529b600-7130-11ea-898a-473fa8f6e327.png)

**Comment by torkelo** [comment]
Strange, updating for me (both on master & on ops-tool1)

**Comment by ivanahuckova** [comment]
I wasn't able to replicate this on the new Time Series panel that we use in Explore. So closing the issue.
