### ISSUE TITLE
Grafana Chart‘s value not equal the value of metrics

### ISSUE THREAD

**Issue by woodliu** [grafana/grafana#23184]
**What happened**:
I use grafana show a metrics fumula `node:node_memory_utilisation:ratio`，but it shows the wrong value. When i use prometheus get the value ,it returns the right value.
**What you expected to happen**:
Grafana should show the right value as prometheus
**How to reproduce it (as minimally and precisely as possible)**:
Always, i can reproduce it.
**Anything else we need to know?**:

**Environment**:
- Grafana version:6.7.1
- Data source type & version:
- OS Grafana is installed on:radhat 7.6(container version)
- User OS & Browser:Chrom
- Grafana plugins:None
- Others:
Here is the partial value when i use Prometheus，all the value are no more than **0.2**
![image](https://user-images.githubusercontent.com/9976943/77881689-14530c00-7292-11ea-948c-7cb31d2a5ba7.png)
When i use grafana show the metrics `node:node_memory_utilisation:ratio`, it likes:
![image](https://user-images.githubusercontent.com/9976943/77882743-28980880-7294-11ea-8de9-0736a3d61dc4.png)
And when i show the actual value like below , as you can see ,some value is more than 3, it didn't show the value as it gets. Could someone help? Thank you!
![image](https://user-images.githubusercontent.com/9976943/77883397-a3adee80-7295-11ea-8670-0439c2c6ad1d.png)

**Comment by torkelo** [comment]
You must have stacking enabled
