### ISSUE TITLE
Feature: scroll graphs left and right with a mouse

### ISSUE THREAD

**Issue by zerthimon** [grafana/grafana#2318]
I would be nice to have possibility to scroll graphs in time left and right (after picking a desired time period)

**Comment by philipspigelmire** [comment]
Up and down on the y axis would be nice too.  Really useful when you don't use auto for the range.

**Comment by vektory79** [comment]
+1

**Comment by PRI-mcallen** [comment]
+1.  This goes with https://github.com/grafana/grafana/issues/1565 I think.

**Comment by torkelo** [comment]
The time picker allows this so closing this. 
![image](https://user-images.githubusercontent.com/10999/39083967-0e3ffdd0-456e-11e8-8754-00a219f57ab5.png)
