### ISSUE TITLE
SeriesOverrides: Make delete button click area bigger

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#23188]
**What would you like to be added**:
A bigger "activation" area for the delete button on series override. AFAICT only the thrash icon itself is clickable. Since the icon itself is quite small it'd be nice to be able to have the whole label clickable. There's likely other places where this is the case too!

![2020-03-30-100643_123x109_scrot](https://user-images.githubusercontent.com/93906/77889702-8a457c00-726e-11ea-9cfa-206f69ea1bde.png)

**Why is this needed**:
Easier to manipulate series overrides

**Comment by torkelo** [comment]
This will not be relevant in the future with new override system
