### ISSUE TITLE
Docs feedback: /enterprise/reporting.md

### ISSUE THREAD

**Issue by SebastianThorn** [grafana/grafana#23185]
and this page https://grafana.com/docs/grafana/latest/enterprise/export-pdf/
might wanna include an example of what a report might look like.

**Comment by jongyllen** [comment]
Hi, great suggestion! We will put it on the backlog.

**Comment by SebastianThorn** [comment]
was there anything done here?

**Comment by oddlittlebird** [comment]
@jongyllen, is this on your list?

**Comment by jongyllen** [comment]
We will rework the docs for reporting for the 7.0 release and this will be a part of it

**Comment by SebastianThorn** [comment]
sound great!
