### ISSUE TITLE
Missing icon image on plugin list

### ISSUE THREAD

**Issue by mjtrangoni** [grafana/grafana#23189]
**What happened**:

I had to install **grafana-image-renderer** manually, because of grafana/grafana-image-renderer#112 .

Visiting this URL,
https://GRAFANA_URL/plugins/grafana-image-renderer/

The website icon is pointing to `<img class="page-header__img" src="img/icon.png">` which is a wrong path.

![image](https://user-images.githubusercontent.com/261502/77825187-01143500-7108-11ea-80ab-6ca96d28dcd3.png)

See,
```html
<div ng-view="" class="scroll-canvas"><react-container><div class="page-scrollbar-wrapper"><div class="custom-scrollbar custom-scrollbar--page" style="position: relative; overflow: hidden; width: 100%; height: auto; min-height: 100%; max-height: 100%;"><div class="view" style="position: relative; overflow: scroll; margin-right: -8px; margin-bottom: -8px; min-height: calc(100% + 8px); max-height: calc(100% + 8px);"><div class="page-scrollbar-content"><div class="page-header-canvas"><div class="page-container"><div class="page-header"><div class="page-header__inner"><span class="page-header__logo"><img class="page-header__img" src="img/icon.png"></span><div class="page-header__info-block"><h1 class="page-header__title"><a class="text-link" href="plugins">Plugins</a><span> / Grafana Image Renderer</span></h1><div class="page-header__sub-title">Grafana Labs</div></div></div><nav><div class="gf-form-select-wrapper width-20 page-header__select-nav"><label class="gf-form-select-icon fa fa-fw fa-file-text-o" for="page-header-select-nav"></label><select class="gf-select-nav gf-form-input" id="page-header-select-nav"><option value="/plugins/grafana-image-renderer/?page=readme">Readme</option></select></div><div class="page-header__tabs"><ul class="css-13jkosq"><li class="css-b418eg"><i class="fa fa-fw fa-file-text-o"></i>Readme</li></ul></div></nav></div></div></div><div class="page-container page-body"><div class="sidebar-container"><div class="sidebar-content"><div class="markdown-html"><p>A Grafana backend plugin that handles rendering panels and dashboards to PNGs using headless Chrome.</p>
```
**What you expected to happen**:

Like other plugins do, for example prometheus, this is a reachable path,
```html
<img class="page-header__img" src="public/app/plugins/datasource/prometheus/img/prometheus_logo.svg">
```

**How to reproduce it (as minimally and precisely as possible)**:

Install the plugin manually,
1. Unzip the release on `/var/lib/grafana/plugins/`
1. Restart the **grafana-server** service
1. Everything is right, except the plugin icon which is pointing to a not-found image.

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: 1.0.11
- Grafana version: 6.7.1
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on: CentOS8.1
- User OS & Browser: Chrome on Windows
- Others:

**Comment by JDBKC** [comment]
Install the plugin manually.
So where is this plugin?
