### ISSUE TITLE
Can't build docker image from v6.7.0 onwards

### ISSUE THREAD

**Issue by alanbccoe** [grafana/grafana#23199]
**What happened**: Grunt dies with an OOM error, killing the container build

**What you expected to happen**: A container would be built

**How to reproduce it (as minimally and precisely as possible)**:
Clone repo, checkout v6.7.0, then `docker build .`

**Anything else we need to know?**: v6.6.2 is the last version that builds

**Environment**:
- Grafana version: 6.7.0 and above
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment]
Hi, have you tried: ``` Note: If you are using Docker for macOS, be sure to set the memory limit to be larger than 2 GiB. Otherwise, grunt build may fail. The memory limit settings are available under Docker Desktop -> Preferences -> Advanced.```
as per https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#build-a-docker-image

**Comment by jongyllen** [comment]
Actually I had to increase it to 4Gb on my laptop to get the grunt build through

**Comment by jongyllen** [comment]
Closing this one as the proposed solution seems to work.
