### ISSUE TITLE
Multiple template parameters menu (separate template parameters)

### ISSUE THREAD

**Issue by Enternalcode** [grafana/grafana#23191]
**What would you like to be added**:

**Why is this needed**:
------------------------------------------------------------------------------------

Hello, dear developers!

What and Why:
I want the template parameters to be separated so that the page would be cleaner and easier to use.

My little thought:
In some cases, some conditions (template parameters) will render multiple dimensions, so it is not convenient to put all the conditions together.
So I was wondering if I could separate the conditions by creating and extra set of conditions, or simply by drawing a line in the middle of some conditions.
I have seen many similar questions in the grafana community and Stackoverflow with no answers.
I've tried to implement this myself, but I am not familiar with the front-end technology and have failed serveral times.

Sincere appreciation.

**Comment by dprokop** [comment]
@Enternalcode thanks for opening this issue. Not sure I understand what you mean. Can you please provide us with some sketches of your idea?

**Comment by dprokop** [comment]
@Enternalcode any update on this?

**Comment by torkelo** [comment]
closing due to lack of update
