### ISSUE TITLE
RadioButtonGroup: Conflict when two different button groups have the same value on the same page

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#23205]
Reproduced in https://github.com/grafana/grafana/pull/23110#issuecomment-606052699
I think it has to do with conflicting id's https://github.com/grafana/grafana/blob/aacdfcd1a057b4ef49e115642a793fb0420fd4b0/packages/grafana-ui/src/components/Forms/RadioButtonGroup/RadioButtonGroup.tsx#L78

**Comment by torkelo** [comment]
yea, think I have noticed this as well!

**Comment by tskarhed** [comment]
I have a fix for it in the User edit PR
