### ISSUE TITLE
Auth: Support for restricting access if certain criteria aren't met

### ISSUE THREAD

**Issue by burakksglu** [grafana/grafana#23218]
**What would you like to be added**:  
I'd like to see this PR added in the upcoming releases: grafana/grafana/pull/22383

This PR adds a 'login restriction by role' functionality for Generic Auth role mapping. This way if "required_role" is enabled from config, we can allow login only for 'Admin', 'Editor' and 'Viewer' roles. If it is disabled "auto_assign_org_role" is still active and works.

**Why is this needed**:

This PR fixes the issue of the entry of those who do not have a role. For example, if a user from Keycloak has no role for Grafana client and he tries to login the client anyway, he can still login with some role. What we want is in that situation he shouldn't be able to login that Grafana client.

Therefore this feature adds a functionality for those who wants to restrict login by role for Generic Auth.

**Please include your OAuth provider and possible version**:

We have used and tested with Keycloak v9.0.0.

**Why is there a problem with someone in your organization getting Viewer access to Grafana?**:

We've lots of Grafana instances in a docker environment. In Keycloak you create users under realms. Then you can create clients (applications) under this realm, give access to these clients to users under this realm again. So let's say I gave a role to user for Grafana_1 but not on the Grafana_2. That user, without any role from Keycloak, can still login to Grafana_2. This is what we tried to restrict. Because these are different instances, not related to each other and shouldn't be seen by another user from other instance.

 **Have you considered disable allow_sign_up and adding users manually in Grafana? If so, why is that solution not optimal for you given restricting access for certain users is a big problem for you?**:

Yes we tried that. It was not manageable in our use case. We have different teams in our organizations, different instances for different sites etc. Managing and organizing 30+ or 50+ Grafana instances by hand is very time consuming. In Keycloak we add those user just by once. We create only clients with roles with them in Keycloak and give access to specific team or user.

**Comment by aknuds1** [comment]
Thanks for making the feature request :)

**Comment by levkar** [comment]
We are looking forward for this feature.

**Comment by marefr** [comment]
Please take @aknuds1 https://github.com/grafana/grafana/pull/22383#issuecomment-606071605 into account. 

FYI just writing you want this feature without going into details of what the underlying use case is we wont get any useful information and cannot prioritize/accept/make a decision about this.

- Please include your OAuth provider and possible version. 
- Why is there a problem with someone in your organization getting Viewer access to Grafana? 
- Have you considered disable `allow_sign_up` and adding users manually in Grafana? If so, why is that solution not optimal for you given restricting access for certain users is a big problem for you?

**Comment by burakksglu** [comment]
> Please take @aknuds1 [#22383 (comment)](https://github.com/grafana/grafana/pull/22383#issuecomment-606071605) into account.
> 
> FYI just writing you want this feature without going into details of what the underlying use case is we wont get any useful information and cannot prioritize/accept/make a decision about this.
> 
>     * Please include your OAuth provider and possible version.
> 
>     * Why is there a problem with someone in your organization getting Viewer access to Grafana?
> 
>     * Have you considered disable `allow_sign_up` and adding users manually in Grafana? If so, why is that solution not optimal for you given restricting access for certain users is a big problem for you?

* Please include your OAuth provider and possible version.

We have used and tested with Keycloak v9.0.0.

 * Why is there a problem with someone in your organization getting Viewer access to Grafana?

We've lots of Grafana instances in a docker environment. In Keycloak you create users under realms. Then you can create clients (applications) under this realm, give access to these clients to users under this realm again. So let's say I gave a role to user for Grafana_1 but not on the Grafana_2. That user, without any role from Keycloak, can still login to Grafana_2. This is what we tried to restrict. Because these are different instances, not related to each other and shouldn't be seen by another user from other instance.

* Have you considered disable `allow_sign_up` and adding users manually in Grafana? If so, why is that solution not optimal for you given restricting access for certain users is a big problem for you?

Yes we tried that. It was not manageable in our use case. We have different teams in our organizations, different instances for different sites etc. Managing and organizing 30+ or 50+ Grafana instances by hand is very time consuming. In Keycloak we add those user just by once. We create only clients with roles with them in Keycloak and give access to specific team or user.

**Comment by samnimri** [comment]
When a user signs in with oauth, it is possible to set grafana role with role path but if you don't set any role it gets a default role. As a result, if a user signs in with oauth, he can login even if he doesn't have a role.  Requested feature is an option to require a valid user role (or deny login).

Currently: 
If user has no valid role -> can login 

Requested feature:
If user has no valid role -> deny login

**Comment by marefr** [comment]
Thanks. 

@burakksglu managing 30-50+ Grafana instances seems not like the ordinary use case, more advanced. You write "We create only clients with roles with them in Keycloak and give access to specific team or user.". The whole point with using external auth is to move the management from applications to the auth provider, right. 

@samnimri what OAuth provider and possible version?

FYI this [SO topic](https://stackoverflow.com/a/60872131) had an update recently with a new extension. You sure this suggestions doesn't work for you?

**Comment by mr-yaky** [comment]
In our use case we have SSO for different apps and we have some users which should login only to some of them. As example only if a user has the role for Grafana then should login. But now with providing this default `Viewer` permission for all Keycloak users it's a pain.

If this:
>FYI this SO topic had an update recently with a new extension. You sure this suggestions doesn't work for you?

can solve our problem in theory then I'll try for sure.

**Comment by mr-yaky** [comment]
>Have you considered disable allow_sign_up and adding users manually in Grafana? If so, why is that solution not optimal for you given restricting access for certain users is a big problem for you?

The main problem that people who are managing Keycloak users and Grafana users are not the same team and because that for all new users it's always the pain.

I understand you guys as Grafana developers that may be we are asking about some part of functionality which was covered by Enterprise version. But exactly this feature request needs small changes which will solve the problem for many people. So, I hope finally this will be in upstream version because compiling all the time the custom Grafana version with some PR it's also not a good idea. 

Thank you in advance.

**Comment by dabelenda** [comment]
> Thanks.
> 
> @burakksglu managing 30-50+ Grafana instances seems not like the ordinary use case, more advanced. You write "We create only clients with roles with them in Keycloak and give access to specific team or user.". The whole point with using external auth is to move the management from applications to the auth provider, right.
> 
> @samnimri what OAuth provider and possible version?
> 
> FYI this [SO topic](https://stackoverflow.com/a/60872131) had an update recently with a new extension. You sure this suggestions doesn't work for you?

I already tried that, the main issue here, is that the Authentication Scripts are only run during when the user validates his password in the keycloak interface... Which means no Single Sign On possible.

**Comment by levkar** [comment]
This is not an optional feature request. This is a single sign-on blocking problem, a necessity.

**Comment by dabelenda** [comment]
It is a necessity, proof of that, is that a very similar request was made for AzureAD provider: https://github.com/grafana/grafana/issues/22741

**Comment by Nurdankolay** [comment]
What's your projection about this feature? We'd like to have this in Grafana v7.0.

**Comment by gboor** [comment]
I am on Grafana 7 now and it still defaults to Viewer if no role is set. I would like to see this too. Managing this on the keycloak side is a bit of a pain.

**Comment by levkar** [comment]
I believe they refuse to do it to force enterprise version since they refused to accept a working PR without a proper reason and get this issue created here to see if there is enough people demanding this feature. Now it is backed by 13 people (to this date) in the community and there's still nothing about it.

**Comment by gboor** [comment]
@levkar I guess it makes sense if they want to keep their commercial product viable.

I ended up fixing it on the keycloak side using the method outlined here to create a new flow;

https://stackoverflow.com/questions/54305880/how-can-i-restrict-client-access-to-only-one-group-of-users-in-keycloak

Instead of the script posted there, I created one that just checks if the user has ANY role for this client;

```
AuthenticationFlowError = Java.type("org.keycloak.authentication.AuthenticationFlowError");

function authenticate(context) {
    var client = session.getContext().getClient();

    LOG.debug("Checking access to authentication for client '" + client.getName() + "' for user '" + user.username + "'");

    var roles = user.getClientRoleMappings(client);
    if(roles.size() === 0) {
        LOG.info("Denied access for user '" + user.username + "'. User has no roles for client '" + client.getName() + "'.")
        return context.failure(AuthenticationFlowError.CLIENT_DISABLED);
    }

    return context.success();
}
```

Works fine. Hopefully this is useful to someone else as well.

**Comment by burakksglu** [comment]
> @levkar I guess it makes sense if they want to keep their commercial product viable.
> 
> I ended up fixing it on the keycloak side using the method outlined here to create a new flow;
> 
> https://stackoverflow.com/questions/54305880/how-can-i-restrict-client-access-to-only-one-group-of-users-in-keycloak
> 
> Instead of the script posted there, I created one that just checks if the user has ANY role for this client;
> 
> ```
> AuthenticationFlowError = Java.type("org.keycloak.authentication.AuthenticationFlowError");
> 
> function authenticate(context) {
>     var client = session.getContext().getClient();
> 
>     LOG.debug("Checking access to authentication for client '" + client.getName() + "' for user '" + user.username + "'");
> 
>     var roles = user.getClientRoleMappings(client);
>     if(roles.size() === 0) {
>         LOG.info("Denied access for user '" + user.username + "'. User has no roles for client '" + client.getName() + "'.")
>         return context.failure(AuthenticationFlowError.CLIENT_DISABLED);
>     }
> 
>     return context.success();
> }
> ```
> 
> Works fine. Hopefully this is useful to someone else as well.

Sorry to bump this but which version are you using on Keycloak? Because variable user returns null on 9.0.3 when we try to login to Grafana.

**Comment by gboor** [comment]
@burakksglu we are on Keycloak 9 as well. I ran into the same issue; the main thing is to make sure that the auth flow has the browser part set to required before going into the script, otherwise there is no user;

![Capture](https://user-images.githubusercontent.com/7305315/85117432-22745100-b21f-11ea-9426-e8fb4e0b9c58.PNG)

**Comment by burakksglu** [comment]
Ah, ok will try that thank you! I made a copy of browser flow but that part didn't exist before actually.

**Comment by gboor** [comment]
The whole browser flow needs to become a required sub-flow before the role check. I have not found a way to copy an entire existing flow into a new sub-flow, so I re-created the browserflow by hand with all the elements inside it. Takes a minute or so; they're all standard components.

**Comment by burakksglu** [comment]
> The whole browser flow needs to become a required sub-flow before the role check. I have not found a way to copy an entire existing flow into a new sub-flow, so I re-created the browserflow by hand with all the elements inside it. Takes a minute or so; they're all standard components.

Thanks that did the trick for user. I can see the user in debug logs. But client returns null now. I'll try to figure that out also. Thanks.

**Comment by lucwillems** [comment]
We are not using Keycloak   OAUTH server but internal oauth server integrated for our plaform. we see same issue that when users login which do not have AUTHORIZATION , meaning having a specific role assigned to them , still get VIEWER roles.

i tried using "Deny"  role as default but this is ignored.  it seems to me a part of the authorization , you know AAA , that if no valid authorization comes out of the role_attribute_path expression , NO access should be allowed , or atleast configure de behaviour to alllow/disallow  invalid responses from role_attribute_path expression

**Comment by burakksglu** [comment]
> We are not using Keycloak OAUTH server but internal oauth server integrated for our plaform. we see same issue that when users login which do not have AUTHORIZATION , meaning having a specific role assigned to them , still get VIEWER role in the context of grafana.
> 
> i tried using "Deny" role as default but this is ignored. it seems to me a part of the authorization , you know AAA , that if no valid authorization comes out of the role_attribute_path expression , NO access should be allowed , or atleast configure de behaviour to alllow/disallow invalid responses from role_attribute_path expression

That's exactly what we've tried with this PR; unfortunately, didn't accepted.

**Comment by Yoso89** [comment]
I believe role and group based access limitation to clients should be natively supported by Keycloak!
This workaround solution works well, however there are two cosmetic "cons" which comes with that:

- When a not logged in user tries to connect to a client which access gets denied by the authenticator script the whole authentication flow is considered failure. This means the user doesn't get logged in into Keycloak despite the fact they provided the correct credentials
- When a logged in user tries to connect to a client which access gets denied by the authenticator script a blank Keycloak login page is shown (and no the one which gives an error message) which is deceptive as the user can have the false feeling they are not logged in

I was using Keycloak version 11.0.3 when i got this results

**Comment by umarkhan17** [comment]
> session

How to apply this script in keycloak.

inside mappers i added a mapper of script mapper and pasted this script. then inside authentication workflow i copied browser workflow made the browser flow required and added an execution. what am i missing? @gboor @burakksglu

**Comment by mnaser** [comment]
For those arriving here from Google, looks like the needed is:

`role_attribute_strict`

See docs: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/

🫡
