### ISSUE TITLE
Templating: remove legacy code and :confetti_ball:

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23219]
:confetti_ball: :confetti_ball: :confetti_ball:

**Comment by dprokop** [comment]
@hugohaggmark think we can close this now, shall we?

**Comment by hugohaggmark** [comment]
@dprokop not sure, I read this as we need to remove all the old Angular code before it's closed. We haven't done that yet :)

**Comment by dprokop** [comment]
moving to 7.0 milestone
