### ISSUE TITLE
bar gauge is crashing if prometeus returns empty result. 

### ISSUE THREAD

**Issue by yaroslavNikolaev** [grafana/grafana#23212]
**What happened**:
 There are 2 issues with bar gauge. 
 - I have query with variables. When prometeus response returns nothing [empty result], bar gauge is crashing. And when i switch back to request with non empty result .. bar gauge is not able to restore itself. Only way to restore it, change to chart and change back to bar gauge. 
In the same time, Chart works totally fine with empty response.  
 - when result is single time serias , bar gauge doesn't show name

**What you expected to happen**:
 either show notihing either show error but show right values after query update. 
**How to reproduce it (as minimally and precisely as possible)**:
any simple request to prometeus:
- e.g python_gc_collections_total>30000  -> in order to rid off all values
- e.g python_gc_collections_total>200  -> in order to keep only 1 value

**Anything else we need to know?**:

**Environment**:
- Grafana version:
      v6.6.0 (5c11bbdfb4)
- Data source type & version:
   Prometeus v2.16.0
- OS Grafana is installed on:
  Ubuntu 19.04
- User OS & Browser:
    Ubuntu 19.04 + firefox
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Unable to replicate in 6.7.1 

![image](https://user-images.githubusercontent.com/10999/78003832-8f233200-7339-11ea-8424-4e32482a76a1.png)

Can you try to upgrade to 6.7 ?

**Comment by yaroslavNikolaev** [comment]
@torkelo 
you are right, 6.7 works fine for 1st issue with empty data set. 
but 2nd issue is still exist (sorry that i've raised 1 ticket for 2 issues). 

I mean issue, with single result... bar gauge doesn't show name in the same time when number of result > 1 , grafana display names properly. 

Thanks in advance.

**Comment by torkelo** [comment]
That is by design if there is only one series the bar title is hidden, you can use the title field in display settings to show title even when there is only one bar
