### ISSUE TITLE
Enhancement: Unified Color Picker

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2322]
Currently, there are two different ways to select color in the system.
1. The pre-set color swatch, available in panel legends.
2. The color picker, available in the panel config for singlestat panels.

![image](https://cloud.githubusercontent.com/assets/2886187/8606689/603fb894-265b-11e5-85ef-d6a8b7615cc7.png)

This is currently suboptimal, because it prevents the user from maintaining color consistency across singlestat panels and graph panels. Further, as the interface does not accept RGB values for the color picker, it's near impossible to match colors without editing & re-uploading the JSON.

Since all of these end up as JSON values anyway, I propose we extend all color selection to a more robust interface that will address both issues. 
- Defaulting the menu to the pre-set color swatch encourages the user to first use these colors - which have been optimized to work on both light and dark themes. 
- But extending the color picker to accept rgba values allows the more savvy user to use consistent color across multiple panels. 

Quick and dirty Invision Prototype: http://invis.io/PV3ITSB7H

![screenshot 2015-07-09 16 50 49](https://cloud.githubusercontent.com/assets/2886187/8606665/310ffcbe-265b-11e5-8915-59b7de764abb.png)
![screenshot 2015-07-09 16 50 54](https://cloud.githubusercontent.com/assets/2886187/8606666/3137dca2-265b-11e5-8ccf-e104ec886d5d.png)

**Comment by Dieterbe** [comment]
Make sure the rgb values are easily copy pasteable

**Comment by mattttt** [comment]
@Dieterbe Yes! Great point. Will revise.

**Comment by Dieterbe** [comment]
will be manually styling a color picker to this extent though? there's a bunch of open source colorpicker libraries out there. if we find a good one that blends in we could just go with however it's layed out.

**Comment by mattttt** [comment]
Yep, the actualcolorpicker we use (open source vs build ourselves) isnt really important to me, as long as we can create consistency across the different places people can pick colors.

**Comment by ecables** [comment]
+1

**Comment by bwinterseg** [comment]
+1
I am color blind so it is even harder for me to pick out even remotely consistent colors across graphs, let alone dashboards.  This would be a great usability improvement.

**Comment by bobstrecansky** [comment]
This would be really fantastic.  It would be awesome to keep a consistent color scheme.

**Comment by fxstein** [comment]
Any updates on this? This has been an issue for a while and the more dashboards I build the more this gets annoying.

**Comment by gvohra** [comment]
+1

**Comment by yeezyseason** [comment]
+2

**Comment by evanbreznyik** [comment]
Two thoughts:
1.  Why not allow the color picker for selecting the custom color for a metric NOT in a single stat?  (Why limit us to those few preset colors?)
2.  Why not let the fill factor be defined as the result of an alpha (by using rgba() or similar) in the color picker?

**Comment by evanbreznyik** [comment]
:+1:

**Comment by dkerwin** [comment]
:+1:

**Comment by evanbreznyik** [comment]
:+1: So long as there's still a way to manually enter values for rgba/hsla

The solution should answer the question of how to make colors absolutely uniform between graphs and metrics -- as well as allowing useful presets for those who want to move more quickly.

**Comment by rgelobterFH** [comment]
:+1: for this. I just went through a bunch of dashboards changing colors with the series specific overrides and it was the biggest PITA. I should have been able to just copy the hex or rgb color code instead of having to memorize which shade was where.

**Comment by vfxGer** [comment]
+1

**Comment by misccold** [comment]
+1

**Comment by xelite** [comment]
+1

**Comment by rgelobterFH** [comment]
Looks like something of this sort is being merged soon. https://github.com/grafana/grafana/pull/5439

**Comment by Gelob** [comment]
#5439 was not pulled as it was only for the thresholds page and thats being re-worked with alerting.

**Comment by sikr** [comment]
+1

My thoughts:

I just moved from 2.6 to 3.1 and found that the metrics color picker doesn't mark the currently selected color anymore (in 2.6 the selected color was displayed as "unfilled circle" whereas the others were filled). That's a pity.

The "color picker" for single stats thresholds is really challenging. How can I pick the same color(s) for other single stats again? Something like proposed by mattttt would be fine and as already mentioned, the rgba value(s) should be easy to copy+paste.

**Comment by pecmapm** [comment]
+1

**Comment by sunnos9** [comment]
We have the same problem as colors across several panels/dashboard single-stats cannot easily be made consistent (Editing the json for each panel across several dashboards is the only way out, but I think thats a sub-optimal approach), an RGB input should be a compromise
+1

**Comment by sunnos9** [comment]
@torkelo what is your preferred solution for this? we can make the changes and contribute

**Comment by torkelo** [comment]
Not sure, maybe combine them? @mattttt

**Comment by sunnos9** [comment]
@torkelo we can on something similar to the suggested approach in #4242 as that should cover all cases by using the input fields.

**Comment by torkelo** [comment]
@sunnos9 not sure I follow? not seeing a combined approach in #4242 , need a predefined palette and a custom option.

**Comment by TeamCustomer** [comment]
+1

**Comment by patrickcunningham** [comment]
+1

**Comment by paulomachadojr** [comment]
+1
