### ISSUE TITLE
Delete user from Org.

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#23238]
**What would you like to be added**:
Add what Org. you are deleting the user from.

**Why is this needed**:
If you have multiple orgs. it is very easy to not remember what org you are in. Also the text can be misunderstood, that you will delete the use totally from Grafana

![image](https://user-images.githubusercontent.com/21694965/78104984-6a3dc600-73f0-11ea-91f7-81b4e6e001a8.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
