### ISSUE TITLE
Annotation query failed: can't convert undefined to object

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#23245]
**What happened**:

I have imported some of the Monitoring Artists dashboard into Grafana 6.6.1 via provisioning. One example where this happens is https://grafana.com/grafana/dashboards/593. On reload and scrolling I am seeing a lot of the following error messages:

```
Annotation Query Failed
can't convert undefined to object
```

With the following stacktrace.

```
AnnotationSrv.query error TypeError: "can't convert undefined to object"
    convertDimensionFormat datasource.ts:557
    annotationQuery datasource.ts:470
    u annotations_srv.ts:184
```

**What you expected to happen**:

No error message

**How to reproduce it (as minimally and precisely as possible)**:

Import the dashboard into Grafana 6.6.1 with a working cloudwatch data source using provisioning.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: https://grafana.com/grafana/dashboards/593 revision 11
- OS Grafana is installed on: Kubernetes POD using the Helm Chart
- User OS & Browser: Linux, Firefox
- Grafana plugins: pie-chart-plugin

**Comment by languitar** [comment]
Also happens v6.7.1.

The errors only appear of the dashboards are loaded via the chart's loading capabilities but not when using the import in the UI based on the dashboard ID.

**Comment by languitar** [comment]
Ok, the root cause s this upstream issue: https://github.com/helm/charts/issues/21541. However, even if a data source is configured incorrectly, a more graceful error message would be nice.

**Comment by torkelo** [comment]
ok, thanks for reporting this. Will try to improve error message
