### ISSUE TITLE
Reusing queries, managing queries in one place, gitops for queries

### ISSUE THREAD

**Issue by doronha** [grafana/grafana#23240]
**What would you like to be added**:
Option to edit query in one place, save and consume from selected data source, use in any panel.

**Why is this needed**:
Currently queries are managed inside panels, very often there are many panels with same queries that probably differentiated by the panel types and the variables values. 
By the nature of queries they become more complex over time and managing them through the current query editor is not good enough.
Indeed in v6.6 there is an option to view history, mark as favorite and to reuse (I still did not found how to reuse in panel). this is good direction but should take further and have option to export to a file, save to data source and more ....

In my project I save the queries in elasticsearch, load them through hidden variables in each dashboard and use this vars in the query fields. it solved this issue for me although it has many challenges - for example : the query are part of the page URL.

Thanks 
Doron Haskel

**Comment by hugohaggmark** [comment]
I'm going to close this issue as this is elegantly solved with the dashboard data source https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v6-4/#share-query-results-between-panels that I think solves most parts of this issue.

Thank You to you for taking the time to create this issue!

**Comment by torkelo** [comment]
Think this is not about sharing query results but definitions
