### ISSUE TITLE
Render Text Field Sent to Slack or Don't Use Markup

### ISSUE THREAD

**Issue by jimmybrancaccio** [grafana/grafana#23252]
**What happened**:

Slack notifications now include some text which looks like it should be rendered but is not. It ends up looking a bit odd, It looks like it was added here:

https://github.com/grafana/grafana/pull/21734

https://github.com/grafana/grafana/blob/a0d9851cb955872d91358585ed461e5eafacadb3/pkg/services/alerting/notifiers/slack.go#L294

![2baabaa00838c7a0d14a0c6310d89f458eef44f3](https://user-images.githubusercontent.com/405585/78131112-2216a780-73e0-11ea-96f4-a52969f0fff0.jpeg)

This new inclusion of the text field does not seem to be user editable either.

**What you expected to happen**:

I would expect the text field is rendered via Slack's markup processor if markup is going to be used in the field or markup not be used in the text field.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a Grafana instance using version 6.7.1.
2. Setup a Slack notification.
3. Use the test notification button and see the notification in your Slack channel.
4. Note that it now has this extra (and unrendered) text above the Slack attachment.

**Anything else we need to know?**:

N/A

**Environment**:

- Grafana version: 6.7.1
- Data source type & version: InfluxDB 1.7.10
- OS Grafana is installed on: CentOS 7
- User OS & Browser: macOS / Chrome
- Grafana plugins: None except the default.
- Others: N/A

**Comment by aknuds1** [comment]
If I recall correctly, the text part of the message is included because the Slack API docs warn that attachments won't necessarily be shown on all devices. Is it really a problem to you that there's an extra line of text above the attachment?

**Comment by jimmybrancaccio** [comment]
@aknuds1 No, not an issue if it's there, but I would fix it so it renders properly, or just don't use the Markdown.

https://api.slack.com/messaging/composing/formatting

**Comment by aknuds1** [comment]
What do you mean by it being unrendered exactly? If the problem is not the text being there, can you please update the issue description with the real issue you're seeing?

**Comment by jimmybrancaccio** [comment]
If passed through Slack's Markdown parser, the following would show as a link:

`<http://backup.siteocity.com|backup.siteocity.com>`

However since it's not it's being sent as literal. I updated the title of the issue.

**Comment by aknuds1** [comment]
Please update the actual description of the issue, since it's misleading. I.e.

> **What you expected to happen:**
> I would expect that it behaved as it did previously, without this extra text above the Slack attachment.

**Comment by jimmybrancaccio** [comment]
@aknuds1 Done.

**Comment by aknuds1** [comment]
Thanks.

**Comment by yeo-yeo** [comment]
I agree that this functionality would be really helpful.  As mentioned in the closed/duplicate #35417 I think it could just be a one-line change

**Comment by jimmybrancaccio** [comment]
Hey @idafurjes was this actually fixed, or?

**Comment by idafurjes** [comment]
@jimmybrancaccio can you duplicate the issue on the newer version of Grafana?

**Comment by jimmybrancaccio** [comment]
@idafurjes I feel like a complete idiot. For whatever reason my Ubuntu 20.04.4 system never updated from 8.0.4 and I couldn't even manually get it to update using `apt -y update && apt -y upgrade`. Even running `apt install grafana-enterprise` told me I was already on the latest version (8.0.4).

```
# apt install grafana-enterprise
Reading package lists... Done
Building dependency tree       
Reading state information... Done
grafana-enterprise is already the newest version (8.0.4).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

Running `apt -y install grafana-enterprise=8.4.3` got it to update. Very weird. Anyways, once I was updated to 8.4.3 messages to Slack started showing up as I would expect!

Apologies again for not realizing I wasn't on the latest version of Grafana!
