### ISSUE TITLE
Use same colors for two queries

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#2325]
I have a graph with two separate (graphite) wildcard queries. The first query displays the main metrics per host (the wildcard) and the second query some additional information related to the series from the first query. In order to make the association understandable for viewers, I'd like to reuse the colors from the first query for the second one so that information from the same host gets the same color.

So I'd like to request a feature to control the coloring for separate queries. Something like "restart coloring" would be ok for my purpose since I can sort queries correctly. More useful, however, would probably a regex that matches consistent naming parts in the series to find associations.

**Comment by torkelo** [comment]
in Grafana 2.1  (master) you can color by regex, 
https://github.com/grafana/grafana/issues/590#issuecomment-102000114

**Comment by torkelo** [comment]
![color_by_regex2](https://cloud.githubusercontent.com/assets/10999/7630456/683d071e-fa36-11e4-9da5-0e7aae5ed8ab.gif)

**Comment by languitar** [comment]
I've seen that, but this doesn't help in my case. The amount of displayed graphs is dynamic (hosts are added and removed constantly) and every host should have its own color. This doesn't seem to be possible without prior knowledge about the existing hosts. Or am I missing something?

**Comment by jacobweber** [comment]
This would be useful to me too. Maybe it would be possible to have Grafana select the colors using a hash based on some field or variable. That way the same hostname would have the same color on each graph, but you wouldn't need to specify colors for each hostname.

**Comment by rsmets** [comment]
+1 for dynamic coloring.

**Comment by waltertross** [comment]
For my use case (displaying different percentiles in same color for same server, where server names are not known beforehand) it would suffice to reuse the palette for each wildcard series.

**Comment by BBQigniter** [comment]
this would clearly arrange some of my graphs :)

**Comment by sandersaares** [comment]
Hash-based coloring would indeed be ideal for my use case - all I need is consistency between charts. Where is this functionality implemented in Grafana? Perhaps I can contribute a PR if it is not too complex.

**Comment by torkelo** [comment]
@sandersaares we (and others via PRs) have tried hashed based colors, but it creates terrible contrasts, as there is no way to control that series on a graph gets different colors. The only way to get consistent colors would to wait for all panels to complete the query, then render.

**Comment by sandersaares** [comment]
I see. Well, I can imagine myself being willing to give up always having distinct colors if it gave me consistent colors.

**Comment by torkelo** [comment]
but you could end up with a graph with 5 green colors (with identical or similar shades), or very ugly colors. But your welcomed to try.

**Comment by bric3** [comment]
I'm interested too, I have a graph for log levels of various dynamic hosts. 
I'd like to give a _tone_ to the log level (like red for errors, yellow for warn, etc), and that grafana calculate color variations of this _tone_ for each hosts.

**Comment by connelloG** [comment]
Hi All this thread seems to be 17+ months old so wondering if there is any solution since. Would like to lock colors to achieve consistency of counter/metrics coloring across graphs?

**Comment by connelloG** [comment]
Thank you our team have just found the answer we need :-)

**Comment by vickychijwani** [comment]
@connelloG would you mind sharing your solution/workaround? :wink:

**Comment by mysteryDave** [comment]
Converting the series name to a colour using some hashing would be ideal. Has anyone seen any progress on this?

**Comment by dailyherold** [comment]
Also wanting to do something like this, @connelloG share the secret sauce you and your team came up with!

**Comment by ryantxu** [comment]
Using some combination of field overrides and color options all this is possible.

**Comment by epochstamp** [comment]
I would be greatly interested over that feature.

@ryantxu This is true if you know exactly what series will be returned, but you can't use the same color *palette* for two queries with a dynamic number of results at the moment.

My suggestion is to add an option "Custom palette" where you can add your own colors in the order you want  (possibly with the classic palette by default), that can be looped if the number of time series > number of colors in the palette
