### ISSUE TITLE
Grafana Singlestat panel's "current" to work similarly as Stat panel's "Last (not-null)"

### ISSUE THREAD

**Issue by eeren323** [grafana/grafana#23251]
**What happened**:
Using Prometheus with Grafana, the counter metric doesn't always return the last highest value on Grafana when the time frame changes. Using SingleStat panelI have set value to "Current" but still it doesn't work. This is related to https://github.com/grafana/grafana/issues/17829. However, looking at Stat panel's Calculation "Last", it works just fine. 

**What you expected to happen**:
I expect SingleStat panel to have a value similar to Stat panel's "Last" 

**How to reproduce it (as minimally and precisely as possible)**:
Grafana, Prometheus, Increment a prometheus counter, change timeframe. Current doesn't show consistent value.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0
- Prometheus: 2.15.2
- OS Grafana is installed on: Ubuntu
- User OS & Browser: 
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
The singlestat panel will be deprecated in 7.0 with manual migration,  and later in the year forced migrated to stat panel
