### ISSUE TITLE
RadioButtonGroup: Bleeding background color

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#23255]
The background bleeds from the RadioButtonGroup. It's weird, because I can't find a place where the background is set. Changing to `transparent` doesn't work, but it's possible to see the change when using any other color.

Component can be found here https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Forms/RadioButtonGroup/RadioButtonGroup.tsx

![image](https://user-images.githubusercontent.com/2376619/77952418-ea1e4000-72cb-11ea-8187-7129acb3e13a.png)
![image](https://user-images.githubusercontent.com/2376619/77952477-0326f100-72cc-11ea-9c69-b6c8e690a40a.png)

_Originally posted by @dprokop in https://github.com/grafana/grafana/pull/23110#issuecomment-606188905_

**Comment by torkelo** [comment]
unable to replicate this with latest build, 
![Screenshot from 2020-05-20 09-53-38](https://user-images.githubusercontent.com/10999/82420289-d303ff00-9a7f-11ea-8a93-61b560e9c125.png)
