### ISSUE TITLE
Add AWS/Cassandra to CloudWatch in metric_find_query

### ISSUE THREAD

**Issue by ilyastoli** [grafana/grafana#23260]
**What would you like to be added**:
Please add AWS/Cassandra namespace and metrics to https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go 

**Why is this needed**:
It's going to easier to create AWS Cassandra graphs

<img width="746" alt="Screen Shot 2020-04-01 at 19 15 57" src="https://user-images.githubusercontent.com/52413756/78161537-4315e180-744e-11ea-9ee5-9050abaef3af.png">

**Comment by vikkyomkar** [comment]
I will raise a PR for this ASAP

**Comment by daniellee** [comment]
fixed by https://github.com/grafana/grafana/pull/23299
