### ISSUE TITLE
SQL Server Datasource

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#23275]
We are using the SQL Plugin. When trying to run a query with a Group By Interval of 1Month (‘1M’) I get the following error: error parsing interval 1M

But in the [documentation](/https://grafana.com/docs/grafana/latest/features/datasources/mssql) it states: 
![Month](https://user-images.githubusercontent.com/1325158/78221683-8020b900-74cc-11ea-8105-d39dd88f0a20.png)

Is this a bug?

**Comment by jongyllen** [comment]
Hi, thanks for submitting this. 

Could you please provide a bit more information, using the template provided when opening a bug report?

It is important to know what database are you using, what version of the database, what version / environment of Grafana etc.

**Comment by reuvygroovy** [comment]
Grafana 6.6.2 on CENTOS Linux
Browser is Chrome

**Comment by jongyllen** [comment]
Thanks, a bit more info is needed do verify / debug this though.
"SQL Plugin" - What database are you using?

There is a great template when you create a bug report [here](https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md)!

If it is a pure question, check out the [community forums](https://community.grafana.com/).

**Comment by reuvygroovy** [comment]
**What happened**:
I ran the following query:
_SELECT $__timeGroup(Start, '1M' ) as time,count(*)   FROM [dbo].[table]
GROUP BY $__timeGroup(Start, '1M' )_

**What you expected to happen**: It would group the time/date column by **month**. If I group using '1h' or '1m' (hour/minute) it works. I cannot group by Month.

**How to reproduce it (as minimally and precisely as possible)**:
Try to run the above query on your datasource.

**Anything else we need to know?**:
I don't think so. Pretty straight forward.

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: SQL Server Datasource (not sure how to get the version)
- OS Grafana is installed on: Centos 7
- User OS & Browser: Win10, Chrome
- Grafana plugins: Graph
- Others:

**Comment by jongyllen** [comment]
Hi, Thanks for submitting this issue.
It has been fixed in PR #23120 master and will be a part of next release
