### ISSUE TITLE
Version Auto picukp from elastic search 

### ISSUE THREAD

**Issue by ksathyaraj** [grafana/grafana#23276]
I am facing an issue to auto pick the version under datasource tab, In datasource yaml file I had mention to pickup 7.0 from elk but after deployment I need to go datasource and choose the version

Is there any steps to add in datasource yaml to auto pick the elk version while deployment itself ?

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Elastic Search 7.6.1
- User OS & Browser: windows & chrome

All deployment are running under linux setup

**Comment by aknuds1** [comment]
To me this looks like a question that should be directed to either the community [forum](https://community.grafana.com) or [Slack](https://raintank-corp.slack.com/). GitHub issues are for bug reports and feature request.
