### ISSUE TITLE
Allow overriding Prometheus URL in query editor link

### ISSUE THREAD

**Issue by tbregolin** [grafana/grafana#23287]
**What would you like to be added**:
An option to the Prometheus datasource plugin to allow overriding the URL used in the "Link to Graph in Prometheus" button in the query editor.
**Why is this needed**:
The Prometheus endpoints used by services such as Grafana, and other user-agents, such as a person with a browser, often use different forms of authentication. One use-case, for instance, is running the query endpoint and Grafana in the same Kubernetes namespace, and using the local services address as the datasource URL for Prometheus, but having a separate, authenticated endpoint for direct access to Prometheus through the Kubernetes ingress.

**Comment by roidelapluie** [comment]
We could use the Prometheus API to get the Prometheus external URI, there is no need for a user option, I think.

**Comment by tbregolin** [comment]
> We could use the Prometheus API to get the Prometheus external URI, there is no need for a user option, I think.
That would work, too.

**Comment by gtk-grafana** [comment]
This was closed in https://github.com/grafana/grafana/issues/46944.
