### ISSUE TITLE
For elasticsearch datasource, search results can be highlight

### ISSUE THREAD

**Issue by Donghui0** [grafana/grafana#23283]
For the elasticsearch datasource type, search results can be highlighted when using the explore function. like kibana search results highlights.

**Steps to reproduce**:
query:  o.s.w.s.DispatcherServlet

**Actual Result**:
No highlighting
![image](https://user-images.githubusercontent.com/7134928/78238355-11b11a80-750f-11ea-999c-0a1857a23567.png)

**Expected Result**
highlighted
![image](https://user-images.githubusercontent.com/7134928/78238125-cc8ce880-750e-11ea-9a5b-9aa75715c245.png)

**Environment**: 
- Grafana version: 6.7
- Data source type & version: elasticsearch  6.0+
- User OS & Browser: chrome
- Others:

**Comment by stevekatsaras** [comment]
Any ETA for this? This is actually a really good feature and Kibana is awesome for being able to highlight your terms in your search results.

**Comment by simianhacker** [comment]
I started working on this today, PR should be forthcoming in the next few days.
