### ISSUE TITLE
Fix caching issues with packages.grafana.com

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#23282]
**What would you like to be added**:

Make sure that new packages are visible in our Debian and RPM repositories right after release. 

Possible solutions:
- update cache rules in Fastly to set very short cache times to the listing files
- add a cache purge to CI

**Why is this needed**:

New packages are not visible after release.

**Comment by xlson** [comment]
The default cache setting was 1 hour and that hit our configuration files and is most likely why we have been having problems with deploys. I set the default cache time to 1 minute which should hopefully solve the issue. rpm/deb are still set to 7 days.

**Comment by xlson** [comment]
@aknuds1 has the package cache behaved in the last few releases after I changed the cache setting?

**Comment by aknuds1** [comment]
@xlson Yes :) Haven't noticed any problems at all.

**Comment by xlson** [comment]
Great! <3
