### ISSUE TITLE
Graphite series editor messes up series in case it does not exist yet

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#2328]
In our setup certain series are sparse, so they might not exist at the point in time the dashboard is created but will eventually appear. The current series editor for graphite cannot handle this case correctly because it will either replace parts of the dotted series name with `select metric`  or append this string at the end, which renders the dashboard unusable if the editor is accidentally opened. It would be nice if the UI did not destroy the manually created query in case the series does not exist.

**Comment by torkelo** [comment]
Its not really possible to solve this without messing up other scenarios (where you want a select metric), so to solve this case I made the text editor mode (using pen icon) a persisted property (sets textEditor: true on the query, the parser and query validator will not run)

**Comment by languitar** [comment]
Sounds like a good solution. Thanks
