### ISSUE TITLE
Unexpected changing dashboard after saving JSON Model

### ISSUE THREAD

**Issue by mikhno-s** [grafana/grafana#23294]
Dashboard after saving JSON model unexpected moves to General folder (started from v6.7.2)

Expexted: Saving dashboard model w/o changing folder where this dash saved

Steps:
- Open any dashboard in non General folder
- Make changes in Json model and save

Tested on previous version - it works as expected.

**Environment**:
- Grafana version: v6.7.2
- Data source type & version: -
- OS Grafana is installed on: docker&debian
- User OS & Browser: os x Chrome
- Grafana plugins: -
- Others: -

**Comment by jongyllen** [comment]
Hi, This seems like a regression. Thanks for reporting it!

**Comment by dprokop** [comment]
@jongyllen yes, frontend platform can investigate as we were making updates to dashboard save
