### ISSUE TITLE
Redirect on OAuth login brings me to a 404 page

### ISSUE THREAD

**Issue by olafurw** [grafana/grafana#23293]
**What happened**:
Grafana hosted on a domain, let's call it example.com
Using OAuth to login on example.com/login, authentication succeeds and we are directed back to example.com/login/generic_oauth

We are then directed to a page that isn't found.

/login/public/build/grafana.dark.71af4420a0fca6a7ffc6.css
I can still click on home and continue using the page, but the initial landing page is wrong.
I see the redirect_to cookie is set to %2Flogin%2Fpublic%2Fbuild%2Fgrafana.dark.71af4420a0fca6a7ffc6.css

![image](https://user-images.githubusercontent.com/103783/78253843-5039db80-74f5-11ea-84ac-a54277f9791a.png)

**What you expected to happen**:
Being sent to the normal dashboard home page.

**How to reproduce it (as minimally and precisely as possible)**:
6.7.2 being run in docker.
Follow OAuth guide. https://grafana.com/docs/grafana/latest/auth/generic-oauth/
GF_SERVER_ROOT_URL=https://example.com/

**Environment**:
- Grafana version: 6.7.2 (also tried 6.7.1)
- OS Grafana is installed on: AWS Linux 2, Docker
- User OS & Browser: Chrome / Windows 10
- Grafana plugins: None

**Comment by olafurw** [comment]
Also tried 6.6.1 and 6.5.2, since those releases (or the ones after them) talk about fixes for redirect. Same issue.

**Comment by aknuds1** [comment]
Thanks for reporting this, trying to reproduce.

**Comment by papagian** [comment]
@olafurw 
thank you for reporting this. Have you configured a proxy or are you using a subpath?
Could you please share your configuration?

**Comment by marefr** [comment]
@olafurw can you try using Chrome developer tools and open network tab and check `Preserve log`. Then reproduce your scenario. Then check requests that return 302 and what the value of Response header Location is.

My own example:
![image](https://user-images.githubusercontent.com/1668778/78257848-b37a3c80-74fa-11ea-9e90-410b441bc615.png)

Then, looking at response after authenticating at oauth provider: 
![image](https://user-images.githubusercontent.com/1668778/78258081-fe944f80-74fa-11ea-8bf2-2869674043ff.png)

Then, looking at response for redirecting to Grafana home page:
![image](https://user-images.githubusercontent.com/1668778/78258212-2d122a80-74fb-11ea-9cae-3729945d5e7e.png)

**Comment by olafurw** [comment]
I think it has something to do with my browser. Tried Edge and it works perfectly.

How would a thing like this propagate for so long, even after clearing cookies and application information.

Trying what you showed gives me the wrong url.

![image](https://user-images.githubusercontent.com/103783/78258708-ea048700-74fb-11ea-9f9a-662217e035ad.png)

**Comment by olafurw** [comment]
Works in Chrome after a restart. Probably a misconfiguration on my end when setting up the oauth caused this redirect value to somehow stick, and then when things were correct, it kept thinking I wanted that location.

**Comment by aknuds1** [comment]
Thanks for resolving it @olafurw :)

**Comment by Estrax** [comment]
The same problem exists when you run Chrome on Linux (Chrome on Windows and macOS seems to work well) and your cookie expires (it doesn't matter whether you logged in via oauth or just using credentials) - exactly the same case, login process takes you to this odd address. Browser restart doesn't help.

**Comment by aknuds1** [comment]
@Estrax can you provoke that by logging out instead of letting the cookie expire?

**Comment by Estrax** [comment]
Yes, though the weird thing is that it happens completely randomly. would say about 1.5-2% of logins are affected by that issue in my case. All under devenv.

**Comment by aknuds1** [comment]
@Estrax Ah so it only happens for a fraction of your logins?

**Comment by Estrax** [comment]
Yes, usually on devenv that runs 12+ hours and has several hours of inactivity (e.g. when I leave it for an entire night). Also yes, only a fraction of logins.

**Comment by aknuds1** [comment]
Weird.
