### ISSUE TITLE
Support for value widgets

### ISSUE THREAD

**Issue by syepes** [grafana/grafana#233]
It would we nice to have some sort of row widget that shows the value of a query+functions from the past X time and with the trend (Up or Down) of the past Y minutes.

Possible setting:
 Query: alias(sumSeries(carbon.agents.*.updateOperations),'Updates')
 Trend look back time frame: Past 10min

http://shopify.github.io/dashing/#widgets
![widget1](https://f.cloud.github.com/assets/333081/2518657/fbd0f5f6-b466-11e3-8410-fa1def48b5b5.png)

What do you guys think?

**Comment by bergquist** [comment]
Closing this. Singlestat panel can now support all requested features.
