### ISSUE TITLE
Sharing rendered images does not work

### ISSUE THREAD

**Issue by leoleovich** [grafana/grafana#2330]
Hey.
I have graph and I have tried to render it to png.
I have made:
1) Graph title
2) share
3) Direct link rendered image

![2015-07-10 17 08 14 2](https://cloud.githubusercontent.com/assets/4749052/8621603/d27eefd0-2726-11e5-8b75-3100a8786214.png)

On screen already rendered image. Anonymous is disables.  
Here is nginx conf:
```
server {
        listen 443;
        server_name lalala;
        ssl on;
        ssl_certificate_key /etc/ssl/private/lalala.key;
        ssl_certificate     /etc/ssl/private/lalala.pem;
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/graphite.access.log;
        error_log /var/log/nginx/graphite.error.log;

        # Grafana part
        location / {
                proxy_pass http://127.0.0.1:3000;
        }

}
```

Here is grafana.ini
```
[paths]
logs = /var/log/grafana
[server]
http_addr = 127.0.0.1
router_logging = true
root_url = http://127.0.0.1:3000/
[database]
type = mysql
host = 127.0.0.1:3306
name = grafana
user = grafana
password = pass
[session]
provider = mysql
provider_config = grafana:pass@tcp(127.0.0.1:3306)/grafana?charset=utf8
[analytics]
[security]
login_remember_days = 30
[users]
[auth.anonymous]
[auth.github]
[auth.google]
[log]
mode = console, file
buffer_len = 10000
level = Debug
[log.console]
level = Debug
[log.file]
level = Debug
log_rotate = true
max_lines = 1000000
max_lines_shift = 28
daily_rotate = true
max_days = 7
[event_publisher]
```

**Comment by leoleovich** [comment]
I have checked it again, since you have disabled anonymous and you are logged in, you will have png, which is not graph, but login screen.

**Comment by torkelo** [comment]
root_url should be the public facing url (the one use in the browser)

**Comment by leoleovich** [comment]
It does not help. 
Since I have disabled anonymous, it shows me only login screen.

grafana.ini
```
...
root_url = http://site.example.com:80/
...
[auth.anonymous]
enabled = false
...
```
nginx.conf
```
server {
        listen 80;
        location / {
                proxy_pass http://127.0.0.1:3000;
        }
}
```

**Comment by leoleovich** [comment]
And also I have the same cookie for Graphite-web behind of Grafana. And If I enable anonymous at the end graphite will not allow to get json with metrics.
So looks like cookie support for render completely does not work.

**Comment by torkelo** [comment]
it should, works for everyone else so far (all though some have had similar issues to you but solves once the config was right). 

root_url = http://site.example.com:80/

try remove port 80 from it, it should be exactly what you use from the browser
