### ISSUE TITLE
Clock background, grafana 6.7

### ISSUE THREAD

**Issue by duysmil** [grafana/grafana#23306]
**What happened**:

Grafana clock plugin background stop working after update grafana to version 6.7

**What you expected to happen**:

When choosing from the palette the color of the watch was to be changed.

**How to reproduce it (as minimally and precisely as possible)**:

Simply try changing the color

**Anything else we need to know?**:

Nothing

**Environment**:   
- Grafana version: Version 6.7.1
- Data source type & version: Zabbix 4.2
- OS Grafana is installed on: CentOS Linux 7 (Core)
- User OS & Browser:  Any, but it use more Chrome
- Grafana plugins: Defaults, but this problems related to Clock Plugin
- Others: Nothing

**Comment by aknuds1** [comment]
Please rewrite the issue using our standard bug template.

**Comment by duysmil** [comment]
> Please rewrite the issue using our standard bug template.

Updated

**Comment by aknuds1** [comment]
It would be great if you could write more in the "How to reproduce it (as minimally and precisely as possible)" section:

1. Which plugin to install
2. Exact step required to reproduce the error you're seeing

Now I at least don't know how to reproduce your issue.

**Comment by therealcodlord** [comment]
This still seems to be an issue with v7

**How to reproduce it (as minimally and precisely as possible):**
- Add new panel to dashboard.
- Choose Grafana standard **Clock** panel
- Under **Options** click on **Bg Color**
- Select a color.

**What happened?**
The selected color is shown in the **Bg Color** setting but the panel background does not change.

**What you expected to happen:**
That the background color of the clock would change to the selected color.

**Comment by ryantxu** [comment]
Fixed in the 7 with clock panel 1.1+

**Comment by therealcodlord** [comment]
How do you update to clock panel 1.1+?

I followed v7 instructions and did a `sudo grafana-cli plugins update-all` which did not update the clock panel. And doing a manual remove/install still downloads and installs v1.0.3:

`sudo grafana-cli plugins install grafana-clock-panel`
`installing grafana-clock-panel @ 1.0.3`
`from: https://grafana.com/api/plugins/grafana-clock-panel/versions/1.0.3/download into: /var/lib/grafana/plugins`

`✔ Installed grafana-clock-panel successfully`

I realise I can do a manual download/unpack/install but is there something wrong with the grafana-cli process here?

Thanks

**Comment by duysmil** [comment]
Thanks All
