### ISSUE TITLE
After Grafana Login, it enters a different page than Home, which gives 404 error

### ISSUE THREAD

**Issue by calin112** [grafana/grafana#23316]
**What happened**:

When I login with any account, it enters http://[Grafana's IP]:3000/img/icons_dark_theme/icon_dashboard.svg, which shows the following page:

![image](https://user-images.githubusercontent.com/40755926/78351010-681d6800-75a6-11ea-960a-ae20d1c2df19.png)

**What you expected to happen**:
I expected that after login the page that showed up would be http://[Grafana's IP]:3000/?orgId=1 and this page would show up:

![image](https://user-images.githubusercontent.com/40755926/78351330-e712a080-75a6-11ea-83f0-7e0330468e25.png)

**How to reproduce it (as minimally and precisely as possible)**:
Reproduced above

**Anything else we need to know?**:
LDAP Login is enabled and is working fine. Grafana has been installed with Docker.

**Environment**:
- Grafana version: 6.7.1
- Data source type & version:
- OS Grafana is installed on: RHEL 7.7
- User OS & Browser: Windows, Chrome
- Grafana plugins: None
- Others:

**Comment by jongyllen** [comment]
Hi, this sounds strange. I cannot reproduce it. Could you please clear all you cookies and / or go into private browsing mode in your browser and try?

**Comment by calin112** [comment]
Hi Jon,
I've tried cleaning the cookies and it worked out! Thank you for the help, and sorry for the inconvenience.
Best regards,
Calin
