### ISSUE TITLE
HOW TO GET INSTANCE NAMES INSTEAD OF INSTANCE ID IN GRAFANA IAM UISNG CLOUDWATCH DATA SOURCE

### ISSUE THREAD

**Issue by sreekanath** [grafana/grafana#23320]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment]
Hi, please use our [community forum](https://community.grafana.com/) or [slack](https://http://grafana.slack.com/) for questions.

Please make sure to structure your question according to the recommendations, and keep in mind that using all capital letters could be perceived as spam.
