### ISSUE TITLE
Datasources using backendSrv (e.g. Elasticsearch and Prometheus) no longer respect `withCredentials` auth option

### ISSUE THREAD

**Issue by hvtuananh** [grafana/grafana#23338]
**What happened**:
Datasources using backendSrv (e.g. Elasticsearch and Prometheus) no longer respect `withCredentials` auth option. It does not matter if I check `withCredentials` or not, no auth info (cookie, Kerberos header, ...) is sent on the XHR request.

**What you expected to happen**:
If an Elasticsearch or Prometheus data source is configured with `withCredentials` option, Grafana should include auth info (cookie, Kerberos header, ...) when making XHR requests.

**How to reproduce it (as minimally and precisely as possible)**:
 * Stand up a standalone Grafana server process
* Add an Elasticsearch or Prometheus that requires authentication
* No auth info (cookie, Kerberos header, ...) is sent on the XHR request when click Test on the data source page, no matter whether withCredentials is checked or unchecked.

**Anything else we need to know?**:
I only tested with Elasticsearch and Prometheus.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Elasticsearch and Prometheus comes with 6.7.2
- OS Grafana is installed on: Debian 9
- User OS & Browser: Mac OSX Catalina & Chrome
- Grafana plugins:
- Others:

**Comment by hvtuananh** [comment]
The fix for this bug is straightforward, so I went ahead and submit a PR. Comments and suggestions are appreciated as this is my first time contributing to the Grafana project.

**Comment by hvtuananh** [comment]
@mckn I see this issue has been included in the 6.7.3 milestone. Do you have ETA when 6.7.3 is released? I'm looking forward to it!

**Comment by mckn** [comment]
@hvtuananh it should be released now :)

**Comment by hvtuananh** [comment]
@mckn sweet, thank you!
