### ISSUE TITLE
Bad tooltip color in light theme

### ISSUE THREAD

**Issue by rtrompier** [grafana/grafana#23331]
**Steps to reproduce**:
Add an help tooltip on a widget.
Check with Dark Theme
Change to Light Theme
Check with Light Theme

**Actual Result**:
With Dark Theme
![image](https://user-images.githubusercontent.com/2504924/78379072-23a7c180-75d2-11ea-9755-0294c8111d58.png)

With Light Theme
![image](https://user-images.githubusercontent.com/2504924/78379092-2a363900-75d2-11ea-81fe-9fa10bba93a2.png)

**Expected Result**

Color should be dark.
![image](https://user-images.githubusercontent.com/2504924/78379322-771a0f80-75d2-11ea-8447-95534641c721.png)

**Environment**:
- Grafana version: latest
- User OS & Browser: Chrome Mac OSx

**Comment by torkelo** [comment]
What version are you running? Can update to latest nightly? This is fixed a couple of days ago

**Comment by rtrompier** [comment]
Yes fixed in grafana/grafana:6.7.2 !
Thank you ! ;)
