### ISSUE TITLE
Show context doesn't escape labels values when firing request.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#23337]
**What happened**:

When querying a stream that contains windows style path such as `{filename="E:\\Logs\\try\\test\\test.log"} |= "foo"` This query works perfectly as the \ is escaped.

However when using the show context feature it will send a request using this : `{filename="E:\Logs\try\test\test.log"}` and this time \ are not escaped and will result into a 404

**What you expected to happen**:

Show context queries should escape \.

**How to reproduce it (as minimally and precisely as possible)**:

It's not easy to reproduce since you need windows style path.

**Environment**:
- Grafana version: Grafana v7.0.0-47498119pre (a1157b1744)

- Data source type & version: Loki

**Comment by aocenas** [comment]
Could be linked to https://github.com/grafana/grafana/issues/24478
