### ISSUE TITLE
Templating: Global variable __orgName has wrong value

### ISSUE THREAD

**Issue by DanielGnzlzVll** [grafana/grafana#23340]
**What happened**:
The new global variable __org is interpolate to user id
**What you expected to happen**:
The variable is interpolated to de org ir
**How to reproduce it (as minimally and precisely as possible)**:
every query that uses $__org
**Anything else we need to know?**:
https://github.com/grafana/grafana/blob/816b611eb9d294a2aa768987388ca5aae16a1f20/public/app/features/templating/variable_srv.ts#L65-L71
**Environment**:
- Grafana version: 6.7

**Comment by torkelo** [comment]
yea, that looks wrong! thanks for reporting this!

**Comment by vikkyomkar** [comment]
I will look into it
