### ISSUE TITLE
Role mapping issue with AzureAD.

### ISSUE THREAD

**Issue by salihzett** [grafana/grafana#23358]
So maybe it is not an issue for you, but i tried everything to i am pretty sure it is an issue:

**What happened**:
I want to use AzureAD for role mapping with `role_attribute_path`, but this setting has obviously no effect to my login.

**What you expected to happen**:
I would have 2 groups, better 3 for mapping roles like admin, editor, and viewer. 
Wenn I log in with my credentials (which is assigned in AzureAD `Users & Groups` to Admin) then I expected to have also Admin permissions. But this is not happening.

**How to reproduce it (as minimally and precisely as possible)**:
I check [this](https://grafana.com/docs/grafana/latest/auth/generic-oauth/) page from grafana, [this](https://community.grafana.com/t/role-is-not-attached-to-user-when-using-role-attribute-path-for-generic-oauth/25689) from grafana forum and [this](https://stackoverflow.com/questions/58952293/grafana-role-assignment-using-azure-ad-oauth) from StackOverflow.
All the settings didnt work.
`role_attribute_path:` contains(info.groups[*], 'Admin') && 'Admin' || 'Editor' also lowercase
`role_attribute_path: contains(groups[*], 'Admin') && 'Admin' || 'Editor'` also lowercase 
`role_attribute_path: contains(info.groups[*], '/Grafana/Admin') && 'Admin' || 'Editor'` also lowercase
Of course also with the settings for Viewer, This also didnt work.
I also used the object ID from the group. Not working. Still as same. No effect. I have always Viewer permissions.

**Anything else we need to know?**:
For now, i have enabled:
```
auto_assign_org_role: Editor
editors_can_admin: true
```
Of course, I have disabled this, for testing role_attribute_path because I thought it overwrites any settings maybe. No effect.

**Environment**:
- Grafana version: v6.6.2 (3fa63cfc34)
- OS Grafana is installed on: AWS instance
- User OS & Browser: macOS / Chrome

**Comment by m4c3** [comment]
it doesn't work for me too.

```
[auth.azuread]
enabled = true
allow_sign_up = true
client_id = 11111111-1111-1111-1111-111111111111
client_secret = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
scopes = openid email profile
auth_url = https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/authorize
token_url = https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/token
allowed_domains = domain.com
allowed_groups = 00000000-0000-0000-0000-000000000000
role_attribute_path = contains(info.groups[*], 'Admin') && 'Admin' || contains(info.groups[*], 'Editor') && 'Editor' || 'Viewer'
```
also tried:
```
#role_attribute_path = contains(info.groups[*], 'Grafana Admin') && 'Admin' || contains(info.groups[*], 'Grafana Editor') && 'Editor' || 'Viewer'
#role_attribute_path = contains(roles[*], 'Admin') && 'Admin' || contains(roles[*], 'Editor') && 'Editor' || 'Viewer'
#role_attribute_path = contains(roles[*], 'Grafana Admin') && 'Admin' || contains(roles[*], 'Grafana Editor') && 'Editor' || 'Viewer'
```
The manifest in azure looks like the example

**Environment**:
- Grafana version: 6.7.2 (423a25fc32)
- OS Grafana is installed on: Oracle Linux Server 7.7
- User OS & Browser: Win10 / Chrome & Firefox

**Comment by alexanderzobnin** [comment]
Hi! After moving Azure AD to the separate OAuth provider, `role_attribute_path` doesn't work anymore. The reason is that Azure returns roles in token claims attribute which is always `roles`. You should [configure your application manifest](https://grafana.com/docs/grafana/latest/auth/azuread/#create-the-azure-ad-application) to return proper Grafana roles.

However, it's still possible to configure Azure AD as a generic OAuth provider and use `role_attribute_path` option to map roles from non-standard claims.

**Comment by salihzett** [comment]
I configured the manifest in azureAD, otherwise, it is not possible to assign these roles to the groups in azureAD as well.
But as I understood, i need to set up `role_attribute_path` as well for telling grafana which Role from azureAD has which role in granafa, isnt it?

**Comment by salihzett** [comment]
i read your links. did also [enabled group attributes](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#configure-the-azure-ad-application-registration-for-group-attributes) . I can also see `"groupMembershipClaims": "ApplicationGroup"` in my manifest and i removed `role_attributh_path.
I add 
```
allowed_domains =
allowed_groups =
```
and put also my group object ID and my company domain. 

Still not working. same result.

**Comment by salihzett** [comment]
I create a new application in azureAD and copy paste everthing new as well.
When i visit https://domain/login/azuread i got these error message:
`No OAuth with name azuread configured`
But it is configured:
```
auth.azuread:
      name: Azure AD
      enabled: true
      allow_sign_up: true
...
```
of course also when i use my root_url same as the redirect url.
when i use the default root_url , so just the grafana webpage, the button for azure ad is not there anymore.
when i enter `auth.generic_oauth` the button appears. and i can log in. but still the same issue, roles are not working.

@m4c3 maybe u can try the same thing, to see if this will help for u. and so we can be sure it is not a user-side-issue. thx

**Comment by m4c3** [comment]
@salihzett `auth.azuread` is available since grafana 6.7.0-beta1
you wrote above that you run 6.6.2 - can you confirm?

**Comment by salihzett** [comment]
true, I updated to 6.7.2 now. New logo, but still the same issue.
```
    users:
      auto_assign_org_role: Editor
      editors_can_admin: true
```
is not working anymore so everyone is Viewer. unlovely.
I guess there is still a problem with the role configuration.
`allowed_groups` is not working. I put one group object ID where i am inside and i get an error message:
`User not a member of one of the required groups`

I did everything like in the docu for azureAD. The group in azure is assigned to Admin and groupMembershipClaims is set. No clue now.

@m4c3 : edit your auth_url and token_url.  add v2.0 after [oauth](https://grafana.com/docs/grafana/latest/auth/azuread/#create-the-azure-ad-application) in your links. And i guess `role_attribute_path` is not necessary for this config. Maybe it works for u.

**Comment by m4c3** [comment]
good catch! but it didnt help either..

**Comment by salihzett** [comment]
But good to know. Means similar issue.
Is `allowed_groups` working for you?

**Comment by m4c3** [comment]
yes `allowed_groups` are working

**Comment by salihzett** [comment]
strange, with `auth.generic_oauth` it ignores the access rules from azure ad and also the `allowed_groups`. I have still access, but with default permissions. 
With `auth.azuread` `allowed_groups` it can't find me as a user in the group object id, don't know why.
without `allowed_groups` i can log in, but only as Viewer.

btw: in `auth.azuread` this has no effect.
```
auto_assign_org_role: Editor
editors_can_admin: true
```
It is only working with `auth.generic_oauth` i guess. 
And for @m4c3 allowed_groups are working, also not clear for me why. I checked every line from the docu more than 3 times. Can't find any reason.

**Comment by alexanderzobnin** [comment]
It's not possible to configure arbitrary mapping for Azure AD. In order to make role mapping working, you should configure app manifest to return valid Grafana roles: `Editor`, `Admin` or `Viewer`.

If you want to map roles from attribute other than `roles`, use generic OAuth provider, but it doesn't support `allowed_groups`.

**Comment by alexanderzobnin** [comment]
>And for @m4c3 allowed_groups are working, also not clear for me why. I checked every line from the docu more than 3 times. Can't find any reason.

Generic OAuth does not support `allowed_groups`.
Azure AD does not support `role_attribute_path`.
That's quite clear in the docs.

**Comment by salihzett** [comment]
@alexanderzobnin 
`allowed_groups` is **not** working in azureAD. the group ID is inside, i am inside the group, but i got the error message above.

Sorry but when did i write that i  used arbitary role names? the values in the manifest are still Editor, Admin and Viewer.

**Comment by alexanderzobnin** [comment]
@salihzett Sorry, you mentioned 
>role_attribute_path: contains(info.groups[*], '/Grafana/Admin') && 'Admin' || 'Editor'

So I thought you want to map `groups` attribute to roles.

Regarding `allowed_groups`, could you enable debug logging and take a look at the logs - what does Azure return in user info?

**Comment by alexanderzobnin** [comment]
It should return something like
```
DBUG[04-08|11:06:58] OAuthLogin got user info                 logger=oauth userInfo="&{Id:56f669c9-36e1-416b-b7d1-0b4ec7d2d033 Name:Alexander Zobnin Email:azobnin@grafana.com Login:azobnin@grafana.com Company: Role:Editor Groups:[4bab1e86-8fca-44e5-9089-1d1c80ec267d 887fe6dd-fcb7-40fe-83ac-1363712c7922]}"
```

Also, you can decode ID token from response with https://jwt.ms/ tool:
```
DBUG[04-08|11:06:58] OAuthLogin Got token                     logger=oauth token="&{AccessToken:eyJ0eX... raw:map[access_token:eyJ0e... expires_in:3599 ext_expires_in:3599 id_token:eyJ0eX...
```
Result:
```
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "XXXX"
}.{
  "aud": "a541c679-5be8-4421-9600-XXXX",
  "iss": "https://login.microsoftonline.com/XXXX-XXXX-XXXX/v2.0",
  "iat": 1586332917,
  "nbf": 1586332917,
  "exp": 1586336817,
  "groups": [
    "4bab1e86-8fca-44e5-9089-XXXX",
    "887fe6dd-fcb7-40fe-83ac-XXXX"
  ],
  "name": "Alexander Zobnin",
  "oid": "56f669c9-XXXX",
  "preferred_username": "azobnin@grafana.com",
  "roles": [
    "Editor"
  ],
  "sub": "pD1OPXXX",
  "tid": "39307a09-XXX",
  "uti": "9-XXX",
  "ver": "2.0"
}.[Signature]
```

**Comment by salihzett** [comment]
thx to @m4c3 , we had a video session and resolved our both problems.
in azureAD -> token configuration -> Add groups claim, u need to choose: at least Security groups and Groups assigned to the application. And for ID, Access, SAML - Group ID. This was not very clear in the docu also not in the docu with refer to microsoft. I will add this info.

**Comment by pihai** [comment]
> thx to @m4c3 , we had a video session and resolved our both problems.
> in azureAD -> token configuration -> Add groups claim, u need to choose: at least Security groups and Groups assigned to the application. And for ID, Access, SAML - Group ID. This was not very clear in the docu also not in the docu with refer to microsoft. I will add this info.

I think a simpler solution is to change the `groupMembershipClaims` to:

```
"groupMembershipClaims": "ApplicationGroup, SecurityGroup"
```

This seems to work for me.

**Comment by yashwanth-l** [comment]
@m4c3 @salihzett @pihai - Can you please check why on doing on the 2 tasks I still see the issue of `user not a member of one of the required groups` in the trace logs while in UI it is `login.OAuthLogin(get info from azuread)`

1. App Manifest has `appRoles` ==>` Viewer` and `Admin` config
2. App Manifest has `"groupMembershipClaims": "ApplicationGroup, SecurityGroup"`
3. Adding the Group Claim in Token Config of the Azure App.

What am I still missing here?

**Comment by AurimasNav** [comment]
> [@m4c3](https://github.com/m4c3) [@salihzett](https://github.com/salihzett) [@pihai](https://github.com/pihai) - Can you please check why on doing on the 2 tasks I still see the issue of `user not a member of one of the required groups` in the trace logs while in UI it is `login.OAuthLogin(get info from azuread)`
> 
> 1. App Manifest has `appRoles` ==> ` Viewer` and `Admin` config
> 2. App Manifest has `"groupMembershipClaims": "ApplicationGroup, SecurityGroup"`
> 3. Adding the Group Claim in Token Config of the Azure App.
> 
> What am I still missing here?
> 
> grafana.ini file is as follows:
> 
> ```
> auth.azuread:
>       name: "Azure AD"
>       enabled: true
>       allow_sign_up: false
>       client_id: "${aad_client_id}"
>       client_secret: "${aad_client_secret}"
>       scopes: "openid email profile"
>       auth_url:  https://login.microsoftonline.com/${tenant_id}/oauth2/v2.0/authorize
>       token_url: https://login.microsoftonline.com/${tenant_id}/oauth2/v2.0/token
>       signout_redirect_url: https://login.microsoftonline.com/${tenant_id}/oauth2/logout?post_logout_redirect_uri=https://${grafana_fqdn}
>       allowed_domains: ${tenant_domain}
>       allowed_groups: "${aad_groups}"
> ```

In my case the problem was that I was using nested groups, once I added my user directly to the group assigned to app role I got the correct role mapped in grafana.
