### ISSUE TITLE
Rounding enable/disable

### ISSUE THREAD

**Issue by robouden** [grafana/grafana#23351]
**What would you like to be added**:
I would like to be able to disable the rounding of decimals on floats to actually reflect the data on hovers.

**Why is this needed**:
To see the detailed detail easily and clearly.

**Comment by robouden** [comment]
Sample screenshots of rounding.
![Screenshot from 2020-04-05 18-08-20](https://user-images.githubusercontent.com/1387190/78471036-01947780-7769-11ea-9b6b-98dce9c643c8.png)
![Screenshot from 2020-04-05 18-08-11](https://user-images.githubusercontent.com/1387190/78471039-05c09500-7769-11ea-98a9-7c06f8340be6.png)

**Comment by robouden** [comment]
Sample of rounding.

![Screenshot from 2020-04-05 18-13-46](https://user-images.githubusercontent.com/1387190/78471088-71a2fd80-7769-11ea-99c1-dd78b778933c.png)
![Screenshot from 2020-04-05 18-08-20](https://user-images.githubusercontent.com/1387190/78471090-74055780-7769-11ea-8dc1-84b81f4b52ea.png)

**Comment by dprokop** [comment]
@robouden you can actually do that by specifying the number of decimals you want to show in the legend. See the Decimals option in Graph's Legend options section:
![image](https://user-images.githubusercontent.com/2376619/78930911-2e1bfc80-7aa5-11ea-8eb3-5992606dba13.png)

**Comment by robouden** [comment]
The issue is solved. It was not even Garafana. Elastic search did not get the right type data to send and it was guessing.

**Comment by AGPisland** [comment]
Hello,
did you have to configure something in Elastic?
Can you give some detail of how it reaches its conclusion
I can't clearly understand why the Elastic answer in Grafana omits numbers in the decimals.
![image](https://user-images.githubusercontent.com/30250890/89854060-e693a300-db60-11ea-95df-72c6773d9b81.png)
![image](https://user-images.githubusercontent.com/30250890/89854097-ff03bd80-db60-11ea-9554-4bd00b5b10b6.png)

**Comment by cdtoews** [comment]
I found that in order to get data to 2 decimal points, I had to change the chart to show 2 decimal points, but I also had to specifically round the my values to 2 decimal points, even though they only had 2 decimal points to begin with.
My query that worked:
SELECT timestamp as datetime, round(reading,1) as "Room 1" FROM "IOTSensors" WHERE  sensor = "rh" and devicename = "room1"
