### ISSUE TITLE
Disable Authentication

### ISSUE THREAD

**Issue by pgraluk** [grafana/grafana#2335]
I would like to start grafana without the login part with user and password. What sould be change in the configuration in order to be able to acces grafana-2.0.2 directly, without authentication?

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/configuration/#enabled

**Comment by pgraluk** [comment]
Thanks, but I have both auth.google and auth.github set to false and the login part still automatically appears when I open it in a web browser.

**Comment by torkelo** [comment]
Those was not the config option I linked to :) 

Here is a better link (but points to the same place in the config docs)
http://docs.grafana.org/installation/configuration/#authanonymous

**Comment by pgraluk** [comment]
Yes. It works that way. Thank you so much!

**Comment by pgraluk** [comment]
Another thing..once I start grafana there is no authentication but when I try to create a dashboard it requires user login. There is a way I can disable that too?

**Comment by torkelo** [comment]
Just change org_role (under [auth.anoymous]) to Editor
http://docs.grafana.org/installation/configuration/#org_role

**Comment by pgraluk** [comment]
It worked. That's all. Thanks!

**Comment by pgraluk** [comment]
Hi again, is the a way in grafana 2.0.2 to set default Data sources like here: http://docs.grafana.org/installation/installation/#datasources? These things have to be configured in config.sample.js and config.js but they no longer exist for this version? Please advice!

**Comment by torkelo** [comment]
There is a check box in the edit / add data source view which you can check to set default data source. 

your right config.js is no more. Data sources are added via the UI or via the http api

**Comment by bbhandari** [comment]
[auth.anonymous]
# enable anonymous access
;enabled = true

# specify organization name that should be used for unauthenticated users
;org_name = dashboard

# specify role for unauthenticated users
;org_role = Viewer

I created the organization name dashboard in guid from admin account. but its asking for credentials everytimee. Even the log file doesn't have much info.

**Comment by TommyLike** [comment]
@bbhandari I have the same problem. how could them fix it by set auth.anonymous?
by the way my grafana version is:3.0.4

**Comment by joemillerr** [comment]
I can't seem to suppress the login page no matter what I try.  I'm running Grafana 3.1.1

**Comment by TommyLike** [comment]
@joemillerr. a little tip, please make sure you have modified the correct config files of grafana,that's what I 
trapped in before~

**Comment by joemillerr** [comment]
@TommyLike so not grafana.ini?  Changes I make in that file seem to work for other settings (i.e. port)...

**Comment by TommyLike** [comment]
@joemillerr please recheck the documentation  [website](http://docs.grafana.org/installation/configuration/),There are several config **.ini** files depended on your installment type,wish this help~

**Comment by joemillerr** [comment]
@TommyLike The only other grafana INI I have on the machine is "defaults.ini" in "/usr/share/grafana/conf" but changes to the auth settings in there don't seem to have an effect either.

**Comment by a2batic** [comment]
Hey, any update on this issue? I am using Grafana 4.4.1

**Comment by torkelo** [comment]
@a2batic update on what? grafana has had anonymous access option from the start

**Comment by a2batic** [comment]
@torkelo, I am editing /etc/grafana/grafana.ini
I have done the following change:-

[auth.anonymous]
# enable anonymous access
;enabled = true

# specify organization name that should be used for unauthenticated users
;org_name = ORGANIZATION

# specify role for unauthenticated users
;org_role = Viewer

Still, when I open localhost:3000, it shows me grafana login page

**Comment by torkelo** [comment]
Try uncommenting the config options :) (removing the semicolon)

```ini
[auth.anonymous]
enabled = true
org_name = YourOrgName
org_role = Viewer
```

**Comment by a2batic** [comment]
oh, I totally ignored them, Thanks @torkelo :)

**Comment by bwulff** [comment]
I using the official Docker image. Grafana sits behind the jwilder nginx proxy, the proxy is configured to do basic auth. I pass the following ENV variables to the container:

      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Acme
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_USERS_ALLOW_SIGN_UP=false

However, when I navigate to the virtual host, I still see the login page and have to login with user 'admin' and password 'admin'. 

The log reveals that Grafana detected the presence of the environment variables:

	Environment variables used:
  [0]: GF_AUTH_ANONYMOUS_ENABLED=true
  [1]: GF_AUTH_ANONYMOUS_ORG_NAME=SlideWiki
  [2]: GF_AUTH_BASIC_ENABLED=false
  [3]: GF_AUTH_PROXY_ENABLED=false

...but it doesn't seem to act accordingly. Any ideas?

**Comment by torkelo** [comment]
Make sure anonymous org name exist, grafana will do a lockup to find the org by name. The default org is named: Main Org.

**Comment by hsch0** [comment]
thank you @joemiller 
I spent the last two hours changing the wrong config file. Be sure it is the first one, at least on my system. What is the purpose of the second config file?
```
/usr/share/grafana/conf/defaults.ini
/etc/grafana/grafana.ini
```

**Comment by mohanraj1939** [comment]
Hi @torkelo 
   Is it possible to have multiple organization in auth.anonymous. If so kindly suggest how.

**Comment by torkelo** [comment]
nope :(

**Comment by mohanraj1939** [comment]
Hi @torkelo ,

I'm using Grafana 5.0.4 here i disabled login form & enabled github authorization but when i try to login it asks me for login page. I don't need anonymous auth, is there any way to enable login with github without login page.

**Comment by torkelo** [comment]
no, there is no way to completely disable the login page.

**Comment by cstockton** [comment]
@torkelo Is there no way to disable it at all even if you don't want any to allow registered users? I bring up a localhost prometheus & grafana in my docker-compose files for several projects to test my application instrumentation and tweak my dashboards locally.  I tried exploring ways to disable it before but gave up since it's only a minor inconvenience having to type admin & admin to login every time I bring the system up / down. However recently it was updated to also ask me to change the admin username & password with a tiny "skip" button directly after which just further slows my workflow.

I work in infosec so I love these solid defaults, but I don't think there is harm in providing ways to disable them as long as the implications are made clear. Would you be willing to accept a pull request that does just that?

**Comment by jazoom** [comment]
This seems to be a popular request. I would also like that. Grafana is secured behind an OAuth server. I'm the only one who has access to it. It makes absolutely no sense for me to go to a login screen.

**Comment by sabrehagen** [comment]
When user management is done at the service mesh level e.g. with Kong, Grafana's login system becomes redundant. Not being able to disable authentication is a real hinderance.

**Comment by torkelo** [comment]
if you enable auth proxy you don't get redirected to login page

**Comment by cdalexndr** [comment]
Managed to setup a working configuration with nginx auth proxy following this thread: https://community.grafana.com/t/how-to-use-auth-proxy-with-nginx/2257/3

Basically, in nginx config you need to add "X-WEBAUTH-USER" header with the remote user, reset "Authorization" header to disable http authentication and finally, in grafana config enable "[auth.proxy] enabled=true" (or env var GF_AUTH_PROXY_ENABLED=true)

**Comment by palash2594** [comment]
Hello,

I am trying to set up grafana on kubernetes. I there a way to disable authentication there too?

**Comment by steve-todorov** [comment]
Hope this saves somebody time. This is how you'd do it with env vars in a `docker-compose.yaml`:
```
      # Disable authentication
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
```
