### ISSUE TITLE
Build: Update Go to 1.14.1

### ISSUE THREAD

**Issue by mjtrangoni** [grafana/grafana#23352]
Hi @marefr,

Is there any reason why grafana is still built with **go1.13.4**? The last update was done here #20405.

Would you mind updating to **1.13.9** or even better **go1.14.1** if possible?

The grafana-plugin-ci environment has already **go1.14**, see #22790 

## TODO: 

- [x] Figure out if we can remove the `-mod=vendor` flag
- [x] Look into any incompatibilities due to the change that [json.Number](https://golang.org/doc/go1.14#encoding/json) no longer accepts invalid numbers (does this affect Influx?)

**Comment by marefr** [comment]
@mjtrangoni we always try to be on pair with latest Go releases, but have fallen behind recently since we have had a lot of other things to focus on. We'll try to get this done soon.

**Comment by bergquist** [comment]
> Number no longer accepts invalid numbers, to follow the documented behavior more closely. If a program needs to accept invalid numbers like the empty string, consider wrapping the type with Unmarshaler.

I think we need to verify that this doesn't break any data sources in `/pkg/tsdb`.

**Comment by marefr** [comment]
https://github.com/golang/go/issues/37308
https://github.com/golang/go/issues/37515
