### ISSUE TITLE
Add an option to hide Y axes individually

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#2336]
I would like to be able to hide only the right Y axis. An option for this would be nice.

**Comment by torkelo** [comment]
you mean you have series that are shown on the right y-axis and left y-axis, and you only want to show left y axis?

**Comment by languitar** [comment]
Right. There is already an option to hide both Y axes, but I just want to hide the right one.

**Comment by shamasis** [comment]
+1 this feature is useful.

I am plotting a primary line (which is very prominent and filtered from the total index). Now, in order to show how much the value is within the total, I am drawing a very light area of the negation of this filter behind the line. (this is for indicative purpose only) and is put in right y axis. I do not need its values.

**Comment by bbczeuz** [comment]
Toke just closed my Feature request. I'm looking for an option to display/hide the y-axes individually (if there is no second y-axis used, the right y-axis is not displayed per default)

I propose: In Graph->Edit->Axes & Grid->Show Axis, replace checkboxes by:
```[ ] X-Axis [ ] left Y-Axis [ ] right Y-Axis```

**Comment by shamasis** [comment]
+1.

**Comment by benrubson** [comment]
This would be perfect yes :+1:

This would allow all graphs to have the same plotted width, without having vertically misaligned last timestamp between graphs.

Perhaps we could also think about having the possibility to put the scale of the right y-axis to the left of the axis ? With some transparency and / or with only 2 marks (one at the top of the axis, the other in the middle of the axis), this should be OK. Then everything would be perfectly aligned, without missing the scale.

Thank you :+1: 

![scale](https://cloud.githubusercontent.com/assets/6764151/13549982/feed11c0-e312-11e5-92d1-51271e9eb32f.png)

**Comment by benrubson** [comment]
See #4264 :+1: 

![ok](https://cloud.githubusercontent.com/assets/6764151/13550438/e77e5188-e31d-11e5-948c-3fdb760358b5.png)

**Comment by benrubson** [comment]
@torkelo, could we think about merging the proposed PR for this issue to 3.0-beta1 please ?
Thank you very much :+1: 
Ben

**Comment by torkelo** [comment]
this was implemented yesterday in conjunction with Graph Axes forms redesign. 


![image](https://cloud.githubusercontent.com/assets/10999/14157020/294f4c0c-f67e-11e5-9a60-61ceb0f57b82.png)

**Comment by benrubson** [comment]
Excellent, thank you :+1:
