### ISSUE TITLE
Title is not coming for Stat panel with single series

### ISSUE THREAD

**Issue by rajur7** [grafana/grafana#23369]
**What would you like to be added**:
We found that the `title` is not coming for single value for a metric in `stat` panel (which is introduced in `v6.6`)

You can see title names in the following picture
<img width="1428" alt="Stat Panel with Title" src="https://user-images.githubusercontent.com/19422642/78559296-c8740a00-7831-11ea-8668-1bc21ebd37dc.png">

You can't see title name in the following picture
<img width="1428" alt="Stat Panel without Title" src="https://user-images.githubusercontent.com/19422642/78559320-d033ae80-7831-11ea-9b27-07e99eb34c03.png">

**Why is this needed**:
When we use `stat` to show panel for dynamic data, we will encounter different data values starts from single value to multiple values for same dimension. We want to see the same title information irrespective of number of values for the same metric.

**Comment by torkelo** [comment]
title is automatically hidden for single series results. 
To always have title use `${__series.name}` in the title field

**Comment by rajur7** [comment]
We want the title from a dimension value which is automatically shown when there are multiple values for a metric but we can't see for a single metric value

**Comment by rajur7** [comment]
Why `Backend-ops-01` is not coming for a single series count as shown in the image. `${__series.name}` is giving different name(`A-series`) than `Backend-ops-01`

**Comment by RajuReddy7777** [comment]
^^ @torkelo
