### ISSUE TITLE
Table results are automatically sorted (not respecting the sort order from for example a SQL query)

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#23361]
**What happened**:
The content was not sorted

**What you expected to happen**:
expected it to default sort to the value specified by my query

**How to reproduce it (as minimally and precisely as possible)**:
We are using the SQL Plugin to query data from an SQL Server table. For example, a sample query:
SELECT field1,field2,field3 from TABLENAME ORDER BY field2

What happens is that the ORDER BY (sort) does nothing within the query, but the table/gui is sorted according to which column header I clicked on to sort the data (by default it's the first column).

I have tested this by configuration the dashboard on one PC, and then opening it on another PC or even opening it on the same PC with a different browser.

**Anything else we need to know?**:
Maybe there should be a field option to sort the field by default somehow instead of being built-in to the query.

**Environment**: 
- Grafana version: 6.6
- Data source type & version: SQL Server 2016
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Win10, Chrome
- Grafana plugins: SQL Server
- Others:

**Comment by torkelo** [comment]
Should be fixed in 7.0 new table
