### ISSUE TITLE
Stat Panel adds %EF%BB%BF characters around the variable in the link

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#23360]
**What happened**:
After updating from 6.6.2 to 6.7.2, links in stat panels stopped working correctly.

**What you expected to happen**:
In 6.6.2
![image](https://user-images.githubusercontent.com/50422107/78551894-26432a80-780f-11ea-8aaf-205073eae3d2.png)
opened as:
![image](https://user-images.githubusercontent.com/50422107/78552021-673b3f00-780f-11ea-9bdf-203327b85302.png)

But in 6.7.2 it looks like:
![image](https://user-images.githubusercontent.com/50422107/78552153-a4073600-780f-11ea-9898-ffa781e8238c.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I came across this situation after updating according to the scheme:
Upload dashboards to JSON -> upload dashboards to new grafana via HTTP API

I will add that if you load JSON in 6.6.2, then the links work correctly

**Environment**:
- Grafana version:  6.7.2
- Data source type & version:
- OS Grafana is installed on: container from image grafana/grafana:6.7.2
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by M0rdecay** [comment]
I'm not sure that the problem is in Grafana, because I can’t reproduce the situation on play.grafana.org. I ask you to suggest what could be the reason if you have ideas.

JSON encoding with dashboards is UTF-8 without BOM, so I don’t understand where these characters came from.

**Comment by jongyllen** [comment]
Hi, those url encoded characters are ï (%EF), » (%BB) and ¿ (%BF). So don't think it has anything to do with template variable interpolation.
Can you share the dashboard json - before he passed it through the api and after when it has been imported to Grafana. Guess it is something to do with encoding (BOM or UTF-8 or UTF-16)

**Comment by M0rdecay** [comment]
Rechecked files, indeed, this is the \uFEFF character.
Thanks!
