### ISSUE TITLE
Docs: Cascader

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#23368]
Storybook documentation for the Cascader component.
Related to #25513

You can find information of usage  [here](https://docs.google.com/spreadsheets/d/1Poywc4FiAhA8szmSZDHAGNiRjgS_SXaJFf_6vay4Zi4/edit#gid=0).
How to write documentation and general best practices can be found [here](https://github.com/grafana/grafana/blob/master/contribute/style-guides/storybook.md#writing-mdx-documentation). Feedback on this document would be super! I'm currently working on a scaled down version with focus on just mdx, so more people are able to contribute.

**Comment by oddlittlebird** [comment]
What is this issue for?

**Comment by tskarhed** [comment]
Storybook documentation for the Cascader component.

**Comment by oddlittlebird** [comment]
That is not at all clear from the issue description. Please clarify.
