### ISSUE TITLE
Relative URL's in text panel with markdown rendered with empty HREF

### ISSUE THREAD

**Issue by brunobastosg** [grafana/grafana#23370]
**What happened**:

I have a text panel with some markdown content, including links to other dashboards. The links are relative. For example:

```markdown
- [Link to Dashboard 1](d/XaLQRbGWk "Dashboard 1")
```

However, the generated HTML link is as follows (notice the empty `href`):

```html
<a href="" title="Dashboard 1">Link to Dashboard 1</a>
```

It worked properly up to version 5.4. Starting from Grafana 6, it stopped working.

**What you expected to happen**:

The generated HTML link should have the correct `href` attribute, as below:

```html
<a href="d/XaLQRbGWk" title="Dashboard 1">Link to Dashboard 1</a>
```

**How to reproduce it (as minimally and precisely as possible)**:

Using Grafana 6 and above, create a text panel with markdown text and add a relative link to it.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Not applicable
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10 Home Edition / Firefox 74
- Grafana plugins: None
- Others:

**Comment by jongyllen** [comment]
Hi, thanks for submitting this issue. I could replicate this and I also verified that it worked in earlier versions.

**Comment by dprokop** [comment]
This is due to the URL sanitisation. You can either update your URLs to be absolute path references (prefixed with /) or disable HTML sanitisation in your Grafana config (`disable_sanitize_html`)

**Comment by peay** [comment]
@dprokop is there any way relative links could be supported without having to disable HTML sanitization? This would be especially useful when Grafana is not deployed at the root of a domain, but we also don't want to open up to too much risk of XSS.
