### ISSUE TITLE
Docs: HTTP Api for creating Organizations

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2337]
Hi @Torkelo I'm looking for a way to automatize organization /dashboards and user edition. But none about this in the public documentation.

http://docs.grafana.org/reference/http_api/

There is any issue or PR where can we look for more api reference ?

Thank you  very much for this great tool again.

**Comment by torkelo** [comment]
The v2.1-dev docs are published but not linked to,   http://docs.grafana.org/v2.1/reference/http_api/

**Comment by toni-moreno** [comment]
Hi @Torkelo thank you very much.

- there is any way to create/remove organizations ?

**Comment by torkelo** [comment]
create yes, remove not currently has not been implemented yet :(

**Comment by toni-moreno** [comment]
But there is not info about creating organizations or query existence of organizarions on your new 2.1 http api documentation.

**Comment by torkelo** [comment]
you right creating org is missing, its a POST to /api/orgs  (you can create an org from UI and inspect the request).

Will add it to the docs later
http://docs.grafana.org/v2.1/reference/http_api/#search-all-organisations

**Comment by sbengo** [comment]
Hi @torkelo, just asking if you are going to update the web with the pull request I submitted with completed docs! #2384 

Thank you again!

**Comment by torkelo** [comment]
I am on vacation right now, will update as soon as I can

**Comment by ORANGE-XFM** [comment]
AFAIK the doc hasn't been updated yet.

**Comment by torkelo** [comment]
it takes a while for cloudfront to purge its cdn cache, should be updated within 10min

**Comment by chaica** [comment]
Hi,

I'm looking for the way to create an new organization using the API in the documentation. Am I missing something in the doc ?

**Comment by torkelo** [comment]
maybe, 

its 
POST http://localhost/grafana/api/orgs/
{name: "My other new org"}


You can always check what api call the frontend uses by opening chrome dev tools and check network tab
