### ISSUE TITLE
Config file format

### ISSUE THREAD

**Issue by jtyr** [grafana/grafana#2338]
Grafana is currently using JSON format for dashboard configuration and INI format for daemon configuration. Unfortunately INI format is kind of limiting and doesn't allow to use advanced setting (see #1450).

Proposed solution is to change the configuration format to YAML. The question is: Do we want to change the configuration format?

**Comment by damm** [comment]
I rather like TOML but it's difficult in spots; but who says 1 configuration file has to rule them all.

LDAP authentication typically holds a 'secret' passphrase that should not be read by the world anyway so 2nd files can always happen?

**Comment by torkelo** [comment]
I will probably continue to use the ini format for the main config, even though it does not allow for array/repeats of sections I have built a system round it where every option can be overriden via command line (either the default or the custom value can be overriden), or via ENV variables (useful for docker deploys). 

But for LDAP config I will probably opt to put that in a separate toml file
