### ISSUE TITLE
migrator can generate errorous SQL queries

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2339]
```
  5 func addAlertSchedulerMigration(mg *Migrator) {
  6 
  7   var alertSchedV1 = Table{
  8     Name: "alert_scheduler",
  9     Columns: []*Column{
 10       {Name: "key", Type: DB_NVarchar, IsPrimaryKey: true},
 11       {Name: "value", Type: DB_NVarchar, Nullable: false},
 12     },
 13   } 
 14   mg.AddMigration("create alert_scheduler table v1", NewAddTableMigration(alertSchedV1))
 15 
 16 }  
```

results in: 

```
2015/07/13 21:13:06 [migrator.go:134 func·001()] [E] Migrator: exec FAILED migration id: create alert_scheduler table v1, err: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY KEY NOT NULL
, `value` VARCHAR NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET ' at line 2
2015/07/13 21:13:06 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY KEY NOT NULL
, `value` VARCHAR NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET ' at line 2
```

**Comment by torkelo** [comment]
Arent you missing a Nullable: false on the primary key?

**Comment by Dieterbe** [comment]
false is default value for that field right? note it says `PRIMARY KEY NOT NULL` in the sql query.

what ended up working is this:
```
	var alertSchedV1 = Table{
		Name: "alert_scheduler_value",
		Columns: []*Column{
			{Name: "id", Type: DB_Varchar, Length: 255, IsPrimaryKey: true},
			{Name: "value", Type: DB_Varchar, Length: 255, Nullable: false},
		},
	}
```
honestly i don't know what DB_Varchar and DB_NVarchar are, i was looking through the code but couldn't find docs or anything. so i was just basing myself on what i saw elsewhere.
docs aside, the issue i wanted to highlight is that the statement 
`mg.AddMigration("create alert_scheduler_value table v1", NewAddTableMigration(alertSchedV1))`
doesn't cause a nice error saying what the actual problem is. instead it slips through to mysql which shows a snippet of the query (and only a snippet cause that's what mysql does :( )  and i have no idea what i did wrong. I know this might be out of scope or not important enough to worry about now, but it would be nice if for example `addMigration` or even better, functions like `newAddTableMigration` could return an error if i'm doing something stupid and tell me what.

**Comment by torkelo** [comment]
addMigration just adds the migration to a list, it is not executed directly (why it is not returning any error).

And the error prints the migration id so you know exactly what migration failed right? 

NVar char = unicode
Var char = ascii / non unicode

**Comment by Dieterbe** [comment]
> addMigration just adds the migration to a list, it is not executed directly (why it is not returning any error)

sure, but in this step it could validate it (before executing)

> And the error prints the migration id so you know exactly what migration failed right? 

yes

**Comment by daniellee** [comment]
Closing this - it's old and I'm not sure if there is an outstanding issue here.
