### ISSUE TITLE
Graph2 component missing fill / gradient options

### ISSUE THREAD

**Issue by vsergeyev** [grafana/grafana#23396]
**What happened**:
Fill and Fill Gradient options are present in Graph visualization. However it is not available in new react Graph2 component. 

**What you expected to happen**:

Expected to have **Mode Options** with
 * Fill
 * Fill Gradient

**How to reproduce it (as minimally and precisely as possible)**:

Use Graph2 component for visualization.
https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/graph2

**Comment by torkelo** [comment]
This is a work in progress alpha panel , we know it’s missing a lot :)
