### ISSUE TITLE
Function transformNull() not working

### ISSUE THREAD

**Issue by Mitssumi** [grafana/grafana#23393]
**What happened**:
Getting null data from item through Zabbix plugin query and the transformNull(0) is not transforming the null object into integer 0 on Stat visualisation. Value mapping still reacts to value "null" instead of 0.

**What you expected to happen**:
Wanted to use this to colour the background red when no data (instead of 0) is received from query.

**Environment**:
- Grafana version: v6.6.2
- Data source type & version: Zabbix plugin
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chromium

**Comment by torkelo** [comment]
This looks like a zabbix issue not a Grafana issue
