### ISSUE TITLE
News Panel is empty

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#23390]
**What happened**: News Panel with a custom feed url is empty

**What you expected to happen**: List news from my feed

**How to reproduce it (as minimally and precisely as possible)**:
1. create "News Panel" with feed url: `https://cors-anywhere.herokuapp.com/https://cloud.google.com/feeds/kubernetes-engine-regular-channel-release-notes.xml`

**Anything else we need to know?**: From network tab, XML is here and full
![image](https://user-images.githubusercontent.com/5497623/78661509-30c4f900-78cf-11ea-9ac1-204c6dd6cb82.png)

**Environment**:
- Grafana version: 6.7.2
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS & chrome

**Comment by jongyllen** [comment]
Hi, the News panel only supports "RSS" and not "Atom" currently.
Maybe you can find that feed as RSS somewhere? 

Otherwise you would have to open a feature request or pull request for supporting Atom.

**Comment by Eraac** [comment]
If someone need Atom, some converter exist online, doing the job https://feedmix.novaclic.com/atom2rss.php
