### ISSUE TITLE
Grouping stacked requests

### ISSUE THREAD

**Issue by stefan-messagebird** [grafana/grafana#23395]
**What would you like to be added**:
Would like to have stacked metrics grouped.

**Why is this needed**:
Example use cases:
- when stacking negative values separate from positive values (currently stacks get mixed)
- when stacking different groups (e.g. queue/process groups)

e.g. with stack disabled for negative values:
<img width="373" alt="Screenshot 2020-04-07 at 15 01 22" src="https://user-images.githubusercontent.com/54811041/78672303-c1580500-78e0-11ea-9867-51541ffe6cc2.png">

If stacked is enabled for negative values you get:
<img width="511" alt="Screenshot 2020-04-07 at 15 03 49" src="https://user-images.githubusercontent.com/54811041/78672540-1267f900-78e1-11ea-833c-31cd06816ac2.png">

A possible fix would be to allow to group values as a **series override**.

**Comment by stefan-messagebird** [comment]
Would have classed it as a bug, but as it's not necessarily documented use, thought it's better placed as feature request.

**Comment by torkelo** [comment]
You can use series overrides to assign different stack groups
