### ISSUE TITLE
Stat panel graph disappears on Field decimals change

### ISSUE THREAD

**Issue by balonchiks** [grafana/grafana#23394]
**What happened**:

When changing the Field decimals value in a Single stat panel to anything from the default (empty - auto in my case) the graph panel disappears.

**Before**:
![image](https://user-images.githubusercontent.com/31212478/78670216-b64fa580-78dd-11ea-9e5b-bc951235a983.png)

**After**:
![image](https://user-images.githubusercontent.com/31212478/78670244-bf407700-78dd-11ea-9bfc-65a9c3d5aed3.png)

**What you expected to happen**:

Ideally it should just change the decimals without affecting the graph

**How to reproduce it (as minimally and precisely as possible)**:

Go [here](https://play.grafana.org/d/Fbp5uPsZk/1-new-features-in-v6-6?tab=visualization&panelId=4&edit&fullscreen&orgId=1) and change the Decimals to anything from 2 (3 or 1 should be ok to see the issue).

I suppose it is not the expected behavior? Or am I missing something very obvious? Thank you.

**Comment by iamspector** [comment]
Can confirm this also happens with Stat panel. 

When panel is just created graph is showed correctly:
![изображение](https://user-images.githubusercontent.com/48680256/93787433-2ad29280-fc39-11ea-87d2-00dc21c7aad7.png)

After setting decimal number to any number graph dissapears: 
![изображение](https://user-images.githubusercontent.com/48680256/93788261-7127f180-fc39-11ea-9eae-eda77b4c0459.png)

**Comment by torkelo** [comment]
This has been fixed in later versions v7.x
