### ISSUE TITLE
api/folders undocumented default limit of 1000

### ISSUE THREAD

**Issue by sjoeboo** [grafana/grafana#23407]
The `all folders` API has a default limit of `1000` however this is not documented.

**What happened**:
curl http://grafana:3000/api/folders
**What you expected to happen**:
Get all folders.
**How to reproduce it (as minimally and precisely as possible)**:
curl http://grafana:3000/api/folders?limit=<more than 1000>
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5
- Data source type & version: Heroic 
- OS Grafana is installed on: Debian
- User OS & Browser: MacOS Curl
- Grafana plugins:N/A
- Others:

**Comment by aknuds1** [comment]
Thanks for making us aware of this. As far as I can tell the default limit is set [here](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/search_builder.go#L33).
