### ISSUE TITLE
Migrate manage dashboards view to React

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#23423]
**What would you like to be added**:
Migrate the manage dashboards view at `/dashboards` to React.

**Why is this needed**:
Part of Search migration epic.

**Comment by dprokop** [comment]
Some work already started here https://github.com/grafana/grafana/pull/13397 some time ago. Not sure how easy it is to pick this up and continue @Clarity-89

**Comment by Clarity-89** [comment]
@dprokop yeah, I'm using that PR as a reference but trying to keep the scope if changes smaller, so it's easier to merge and review.
