### ISSUE TITLE
[Microsoft Edge only] OAuth redirect issue when using subpath

### ISSUE THREAD

**Issue by adberger** [grafana/grafana#23422]
**What happened**:
Using _Microsoft Edge_ for login to Grafana via OAuth (Keycloak) ist not possible.

1. Navigate to https://grafana.sample.com/metrics/grafana/
2. Click _Sign in with SSO GRAFANA_
3. Redirect to OAuth provider
4. Enter credentials and Click _Login_
5. Redirect back to Grafana (https://grafana.sample.com/metrics/grafana/)
6. Call https://grafana.sample.com/metrics/grafana/api/dashboards/home and https://grafana.sample.com/metrics/grafana/api/login/ping fails with HTTP 401
7. Automatic logout from Grafana

In the network panel of the browser we see, that in Microsoft Edge the **grafana_session** cookie is missing on step 6.

**What you expected to happen**:
Login via OAuth should work like in Google Chrome (Version 79.0.3945.130 (Official Build) (64-bit)), Mozilla Firefox (Version 68.4.2) & even the not supported Internet Explorer 11

**How to reproduce it (as minimally and precisely as possible)**:
```
  grafana.ini: |
    [auth]
    disable_login_form = false
    signout_redirect_url = https://keycloak.sample.com/auth/realms/testing/protocol/openid-connect/logout
    [auth.generic_oauth]
    allow_sign_up = true
    api_url = https://keycloak.sample.com/auth/realms/testing/protocol/openid-connect/userinfo
    auth_url = https://keycloak.sample.com/auth/realms/testing/protocol/openid-connect/auth
    client_id = grafana
    client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxx
    enabled = true
    name = SSO GRAFANA
    scopes = openid
    token_url = https://keycloak.sample.com/auth/realms/testing/protocol/openid-connect/token
    [server]
    domain = grafana.sample.com
    root_url = %(protocol)s://%(domain)s/metrics/grafana/
```

**Anything else we need to know?**:
We use SSL Offloading in front of grafana.

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: -
- OS Grafana is installed on: Alpine (default Docker image)
- User OS & Browser: Windows 10, Microsoft Edge (41.16299.1480.0)
- Grafana plugins: -
- Others: **SSL Offloading in front of grafana**

**Comment by adberger** [comment]
Anyone has a clue?

**Comment by marefr** [comment]
Maybe need to set this to true since you use https? https://grafana.com/docs/grafana/latest/installation/configuration/#cookie-secure

**Comment by adberger** [comment]
Unfortunately this option didn't solve the problem..
Is there any way I can provide more information about the issue?
Or are there other possible solutions?

**Comment by marefr** [comment]
Please check the requests being made starting at Grafana, to auth provider and back to Grafana. You should see that `Set-Cookie` request header being set after redirected back to Grafana from auth provider and Grafana redirects to home page. Using developer tools in the browser you should be able to capture all the details.

**Comment by adberger** [comment]
Okei, I gathered some information.

1. The problem doesn't exist in grafana 6.6.2

2. The following message can be seen for a short time after login (after redirect back from OAuth):
![error_after_login](https://user-images.githubusercontent.com/43774417/82893974-28de1880-9f52-11ea-966c-a9f7c4660c67.png)

3. Chrome
   * request of /grafana/
![chrome_grafana_](https://user-images.githubusercontent.com/43774417/82893977-2976af00-9f52-11ea-8609-2382fc89138f.png)

   * request of /grafana/api/dashboards/home:
![chrome_grafana_api_dashboards_home](https://user-images.githubusercontent.com/43774417/82893980-2a0f4580-9f52-11ea-9f9b-c0145cad9681.png)

4. Edge
   * request of /grafana/:
![edge_grafana_](https://user-images.githubusercontent.com/43774417/82893981-2a0f4580-9f52-11ea-9b7d-1317301c1ecb.png)

   * request of /grafana/api/dashboards/home:
![edge_grafana_api_dashboards_home](https://user-images.githubusercontent.com/43774417/82893982-2aa7dc00-9f52-11ea-9a07-bd37692b03df.png)

5. Log (debug) from the unsuccessful request via Edge:
[grafana-debug.log](https://github.com/grafana/grafana/files/4681738/grafana-debug.log)

**Comment by adberger** [comment]
Maybe the new behaviour (bug) is from https://github.com/grafana/grafana/pull/22285?

**Comment by marefr** [comment]
Thanks. A bit weird that you call `https://grafana.sample.com/metrics/grafana/api/dashboards/home` directly after step 5. What happens if you navigate in UI after step 5 and you're logged in to Grafana?

**Comment by adberger** [comment]
No, there are a big amounts of requests in between.
I just posted the first request after coming back from the OAuth and the first HTTP 401 request.
(All requests are called automatically)

**Comment by marefr** [comment]
@adberger have you tried with any other browser? Microsoft Edge (41.16299.1480.0) seems really old?

**Comment by adberger** [comment]
@marefr Our customer will update to a newer version soon. I will update this topic afterwards, thanks.

**Comment by adberger** [comment]
Problem solved with newer version of Edge
