### ISSUE TITLE
Bar Gauge labels do not show correctly with PostgreSQL

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#23431]
**What happened**:

After updating from grafana 6.5.3 to 6.7.2 labels does not show correctly 

6.5.3 result 
<img width="1396" alt="Снимок экрана 2020-04-08 в 12 51 10" src="https://user-images.githubusercontent.com/10380560/78782051-08f69380-79aa-11ea-8215-3d581ccfa056.png">

6.7.2 result
<img width="1391" alt="Снимок экрана 2020-04-08 в 12 50 46" src="https://user-images.githubusercontent.com/10380560/78782059-0b58ed80-79aa-11ea-9d4e-baae8bacbb46.png">

**What you expected to happen**:

each bar gets its label

**How to reproduce it (as minimally and precisely as possible)**:

Unfortunately, I did not find any PostgreSQL datasource in grafana playground to create repro.

So steps will be something like:
 - create Bar Gauge with default settings
 - add PostgreSQL datasource with query like
```sql
select
    count( case
               when p.status_id = 300 then p.batch_id
               else null
           end ) as "Передан в подбор"
  , count( case
               when p.status_id = 400 then p.batch_id
               else null
           end ) as "Консолидируется"
  , count( case
               when p.status_id = 500 then p.batch_id
               else null
           end ) as "Ожидает сортировки"
  , count( case
               when p.status_id = 600 then p.batch_id
               else null
           end ) as "Передан на сортировку"
  , count( case
               when p.status_id = 700 then p.batch_id
               else null
           end ) as "Готов к упаковке"
from (
     select *
     from grafana.posting_batch_in_process p
     where p.status_id in (300, 400, 500)
     union all
     select *
     from grafana.posting_batch_in_process p
     where p.status_id in (600, 700)
       and p.cell_id is not null
     ) p
```
with format=table

API result looks like 
```json
{
  "results": {
    "A": {
      "refId": "A",
      "meta": {
        "rowCount": 1,
        "sql": "<sql here>"
      },
      "series": null,
      "tables": [
        {
          "columns": [
            {
              "text": "Передан в подбор"
            },
            {
              "text": "Консолидируется"
            },
            {
              "text": "Ожидает сортировки"
            },
            {
              "text": "Передан на сортировку"
            },
            {
              "text": "Готов к упаковке"
            }
          ],
          "rows": [
            [
              18,
              18,
              7,
              0,
              0
            ]
          ]
        }
      ],
      "dataframes": null
    }
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: PostgreSQL
- OS Grafana is installed on: docker image `grafana/grafana:6.7.2`
- User OS & Browser: Chrome latest
- Grafana plugins: Bar Gauge
- Others:

**Comment by dprokop** [comment]
@vankop thanks for reporting. Not sure I understand your issue correctly. Do you expect the value not to be right aligned? If so, can you try *Unfilled* option in BarGauge's Display options:

![image](https://user-images.githubusercontent.com/2376619/78932342-97047400-7aa7-11ea-960b-e88460d105d7.png)

**Comment by vankop** [comment]
in 6.5.3 there are 5 different labels (`tables.columns. text` are different values). in 6.7.2 last label is shown for all rows.

**Comment by alexandrovas** [comment]
Same problem for SQL Server datasource after upgrade Grafana to version 6.7.2 from 6.6.2.

**Comment by melvsparks** [comment]
I'm having the same issue as well. Table shows up correctly, but then all the rows have the same label

**Comment by ashtez** [comment]
Same issue with InfluxDB. Each row takes the alias of the last one. Before each row had it's own alias.

**Comment by bugybq** [comment]
Same issue with MS SQL Server and Grafana 6.7.3. 
With the query below, bar gauge has the same label "Target" for all bars.
```
SELECT sum([application]) as Application
      ,sum([approved_application]) AS [Approved Application]
      ,sum([Disbursed_Contract]) as [Disbursed Contract]
      ,sum([target]) as Target
  FROM [accipiens_monitor].[dbo].[v_sales_target]
where brand in ($BrandList)
```

**Comment by ashtez** [comment]
@dprokop any news ?

**Comment by torkelo** [comment]
Unable to replicate in 7.0, tested with a few different data sources 

![Screenshot from 2020-05-28 16-45-54](https://user-images.githubusercontent.com/10999/83156457-b95b5b00-a102-11ea-9136-1fe14951a380.png)

**Comment by ashtez** [comment]
Confirmed. Works as expected on v7.0.1 (ef5b586d7d)

**Comment by torkelo** [comment]
Awesome!
