### ISSUE TITLE
Unable to add Prometheus datasource if it is behind identity aware proxy

### ISSUE THREAD

**Issue by gowrisankar22** [grafana/grafana#23432]
**What happened**:
I am using Identity aware proxy from GCP to configure basic auth for my Prometheus. 
After configuring this, I am not able to configure Prometheus as data source even after passing Identity aware proxy client id and secret.
```
Access to XMLHttpRequest at 'https://accounts.google.com/o/oauth2/v2/auth?client_id=385359287636-xxxxxxxxx
 (redirected from 'https://grafana/api/datasources/proxy/219/api/v1/query?query=1%2B1&time=1586156495.575&timeout=60s?query=1%2B1&time=1586156495.575&timeout=60s') from origin 'https://grafana' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**What you expected to happen**:
I should able to add a data source.
**How to reproduce it (as minimally and precisely as possible)**:
1. Setup GKE
2. Run prometheus-operator using helm install
3. use GCP https load balancer as ingress resource
4. enable IAP using. https://cloud.google.com/iap/docs/enabling-kubernetes-howto
5. verify when you hit the url it redirects to google idp
6. now try to add the Prometheus Datasource to grafana ingress url.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.2 (742d165)
- Data source type & version: Prometheus all the versions
- OS Grafana is installed on:
- User OS & Browser: Linux and chrome

@sakjur has asked me to open this issue. Please help me out on this issue.

**Comment by bergquist** [comment]
I'm not sure this is related to Grafana but rather about the prometheus-operator and GCP IAP.
[Prometheus itself does not enforce any CORS check](https://prometheus.io/docs/operating/security/#authentication-authorization-and-encryption) but maybe IAP does and that's outside our control. Maybe you can remove it from the GCP IAP configuration? I dont know :)

Perhaps you can use proxy mode access when configuring the Prometheus datasource in Grafana and access the Prometheus server from Grafana inside your private network?

I'm closing this issue since it's not regarding Grafana itself but the environment it runs in. If you find anything that we can do to make this easier please poke me in this issue and I will reopen it.

**Comment by aradyuk** [comment]
> **What happened**:
> I am using Identity aware proxy from GCP to configure basic auth for my Prometheus.
> After configuring this, I am not able to configure Prometheus as data source even after passing Identity aware proxy client id and secret.
> 
> ```
> Access to XMLHttpRequest at 'https://accounts.google.com/o/oauth2/v2/auth?client_id=385359287636-xxxxxxxxx
>  (redirected from 'https://grafana/api/datasources/proxy/219/api/v1/query?query=1%2B1&time=1586156495.575&timeout=60s?query=1%2B1&time=1586156495.575&timeout=60s') from origin 'https://grafana' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> ```
> 
> **What you expected to happen**:
> I should able to add a data source.
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Setup GKE
> 2. Run prometheus-operator using helm install
> 3. use GCP https load balancer as ingress resource
> 4. enable IAP using. https://cloud.google.com/iap/docs/enabling-kubernetes-howto
> 5. verify when you hit the url it redirects to google idp
> 6. now try to add the Prometheus Datasource to grafana ingress url.
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Grafana version: Grafana v6.5.2 ([742d165](https://github.com/grafana/grafana/commit/742d165968817f37ce35c203de7f5356fc0396f9))
> * Data source type & version: Prometheus all the versions
> * OS Grafana is installed on:
> * User OS & Browser: Linux and chrome
> 
> @sakjur has asked me to open this issue. Please help me out on this issue.

Are you succeeded by adding prometheus behind IAP to a Grafana?
