### ISSUE TITLE
Prometheus datasource doesn't format multi values correctly in queries 

### ISSUE THREAD

**Issue by maxstepanov** [grafana/grafana#23434]
According to [Grafana Templating Docs](https://grafana.com/docs/grafana/latest/reference/templating/#formatting-multiple-values) 

>  ... if the current variable value was host1, host2 and host3. 
Prometheus uses regex expressions, so the same variable would be interpolated as (host1|host2|host3).

Instead `host1|host2|host3` string is produced. Round brackets aren't added.
https://github.com/grafana/grafana/blob/05ea1590828489f24ea147588bbee995bc50c08d/public/app/plugins/datasource/prometheus/datasource.ts#L172-L173
This works fine for the simplest cases like `host =~ "host1|host2|host3"` but that's about it.
`host=~"$service-$host"` not gonna produce the expected result.
So we have to resort to workarounds like `host =~ "$service-($host)"`.

**How to reproduce it (as minimally and precisely as possible)**:

See the query generated in dashboard here:
https://play.grafana.org/d/000000063/prometheus-templating?panelId=6&edit&fullscreen&orgId=1

**Comment by marefr** [comment]
Not sure we can do anything to help you here to automatically understand that parenthesizes should be inserted. You provide the solution. We try to only keep issues open that are relevant so will close this. 

Please let me know if I misunderstood something.

**Comment by maxstepanov** [comment]
[Grafana templating](https://grafana.com/docs/grafana/latest/reference/templating/#formatting-multiple-values) documentation explains how it is done:

>Grafana tries to solve this by allowing each data source plugin to inform the templating interpolation engine what format to use for multiple values.

InfluxDB plugin and other datasources do this correctly. There no reason Prometheus datasource can't do this. So either documentation is wrong, which i doubt because it makes complete sense, or there is a bug. What i provided is a workaround which make life harder than necessary for Prometheus users.

Consider the following example:
`$type` is a multi-value variable: `blue,green`
Having the following query defined in grafana `kube_cronjob_status_active{cronjob=~"mljob-$type"}`.
This will be interpolated into actual Prometheus query like so `kube_cronjob_status_active{cronjob=~"mljob-blue|green"}` instead of expected `kube_cronjob_status_active{cronjob=~"mljob-(blue|green)"}`

The actual expected composition probably would be  `(blue)|(green)` but the difference seems to be superficial in this case because it will be interpreted as `((blue)|(green))`.
https://github.com/google/re2/wiki/Syntax

Since multi-value template in Prometheus plugin doesn't define the boundary of the composition with parentheses it is left to the user to handle. So we have to define the boundary ourselves by wrapping multi-value variables in parentheses like so `kube_cronjob_status_active{cronjob=~"mljob-($type)"}`.
The same problem with "All" option but you can avoid it by specifying custom value `.*` usually .

Both "All" and multi-value should use parenthesis.

Queries are hard enough already and i think Prometheus users deserve the same quality of life as other data sources do.

I think this needs to be reopened and composition boundary added. Be that what documentation prescribes: `(blue|green)` or Prometheus interpretation: `(blue)|(green)`

The change requested seems to be backwards compatible as well.

**Comment by maxstepanov** [comment]
Another pro: with this change implemented i can just go and change grafana variable to multi-value and all Prometheus queries that have anything more than composition just work. Instead all grafana multi-value variable now need to be wrapped with parenthesis for queries to continue working.

**Comment by marefr** [comment]
Thanks. Didn't know other data sources like [influx](https://play.grafana.org/d/000000002/influxdb-templated?orgId=1) handled this. Seems like what enables this behavior for influx is: 
https://github.com/grafana/grafana/blob/692a73875b9d534537a16379baa16b177197d39c/public/app/plugins/datasource/influxdb/influx_query_model.ts#L205

Looking at Prometheus seems like this is where similar logic as influx could be added:
https://github.com/grafana/grafana/blob/692a73875b9d534537a16379baa16b177197d39c/public/app/plugins/datasource/prometheus/datasource.ts#L173

If anyone interested in contributing let us know and/or open a PR and we'll take it from there.
