### ISSUE TITLE
Loki Log entries with Unix Nano Timestamp not sorted correctly

### ISSUE THREAD

**Issue by denniskniep** [grafana/grafana#23457]
Hello,

**What happened**:
I read logs via promtail and use a Unix Nano Timestamp for the date:

```
- json:
    expressions:
      timestamp_nano: 'TIMESTAMP_NANO'
- timestamp:
    source: "timestamp_nano"
    format: "UnixNs"
```

The logs are sent to loki. 

If I view the Logs via grafana the Logs are only sorted by millisecond precision and not by nanosecond precision.

**How to reproduce it (as minimally and precisely as possible)**:
I created a Repository where you can reproduce this behaviour:

1. Clone Repository https://github.com/denniskniep/GrafanaIssueDemo01
2. docker-compose up
3. Go to http://localhost:3000/ (Credentials are admin:admin)
4. Go to Explore > Choose "loki" > Set loki query to `{app="myApp"}` and change time range to "2020-04-09"
5. Hit "Run Query" Button many times

**What you expected to happen**:

Expected behavoiur is that the log messages are in the order:
C
B
A

But the observed behaviour is that it is after many refreshes as expected, but sometimes it is not sorted correctly. It is like this:
B
A
C

**Anything else we need to know?**:
Used Versions are explicitly defined in docker-compose.yml
https://github.com/denniskniep/GrafanaIssueDemo01/blob/master/docker-compose.yml

**Comment by denniskniep** [comment]
Correct Order:
/home/dkniep/development/grafanaIssue01/screenshots/grafana_correctOrder.png
![image](https://user-images.githubusercontent.com/3629463/78875501-490f5200-7a4e-11ea-9810-8cb4f77f07dc.png)

Incorrect Order after serveral "Run Query" Button Clicks
![image](https://user-images.githubusercontent.com/3629463/78875571-62b09980-7a4e-11ea-8592-a2cc1d80224a.png)

**Comment by jongyllen** [comment]
This might be the same as #23408

**Comment by NickPak** [comment]
So far, this problem has not been fixed??
