### ISSUE TITLE
Improve plugin documentation for offline server operations

### ISSUE THREAD

**Issue by air-olic** [grafana/grafana#23466]
The [plugin documentation](https://grafana.com/docs/grafana/latest/plugins/installation/) mention a method to install plugin on an offline server, but nothing about plugin update.
Could you improve the documentation with a method to update a plugin ?

**Comment by marefr** [comment]
It's the same procedure for updating, i.e. just install a new version and the old version will be replaced. I think the existing documentation is enough.
