### ISSUE TITLE
UI - Bars in Graph getting dull when time range is long.

### ISSUE THREAD

**Issue by unique94** [grafana/grafana#23469]
As described in the title. Not sure whether it is a bug. 
![image](https://user-images.githubusercontent.com/13745442/78901952-a5548f00-7aab-11ea-885d-457cecddf382.png)
As shown above, bars in the graph cannot be obversed clearly. When the time range gets smaller, from 30 days to 7 days, everything seems good.
![image](https://user-images.githubusercontent.com/13745442/78902386-4e9b8500-7aac-11ea-89f0-df23d691cc0a.png)
 
Another interesting story is that when I get to another 30 days period graph, everything seems good again.
![image](https://user-images.githubusercontent.com/13745442/78902642-9f12e280-7aac-11ea-8ad3-e06fd7e01304.png)
 
The two dashboards use similar data. Do anyone have related experience?

**Comment by torkelo** [comment]
Need to include exactly what data your query return for the different time ranges , and your panel json (settings)
