### ISSUE TITLE
Unknown config key team_ids defined in section auth.github

### ISSUE THREAD

**Issue by NeckBeardPrince** [grafana/grafana#2346]
[auth.github]
enabled = true
client_id = <removed>
client_secret = <removed>
scopes = user:email
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
team_ids = 7480,812266

**Comment by torkelo** [comment]
what version of grafana are you running? This is a 2.1 feature
