### ISSUE TITLE
tagline on github project still says "Dashboard & Graph Editor for Graphite & InfluxDB"

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2347]
github.com/grafana says: "Dashboard & Graph Editor for Graphite & InfluxDB"
should it not be "(...) for Graphite, InfluxDB & OpenTSDB." ?
github.com/grafana/grafana says "Grafana - A Graphite & InfluxDB Dashboard and Graph Editor"
same?

**Comment by torkelo** [comment]
oh, your right! will change

**Comment by torkelo** [comment]
Changed to "Gorgeous metric viz, dashboards & editors for Graphite, InfluxDB & OpenTSDB"
