### ISSUE TITLE
Metrictank: rollup information tweaks

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#23485]
* the display of the lineage information (where the series came from, how it was generated, etc) should be called "Lineage". I want this to have a clearly distinguishable name that we can use to call out the functionality in marketing materials etc, and ryan and I thought Lineage makes perfect sense.
* it should display the count of how many series were part of each lineage profile.

**Comment by torkelo** [comment]
PR up https://github.com/grafana/grafana/pull/23848

**Comment by Dieterbe** [comment]
thanks @torkelo !!
