### ISSUE TITLE
Be nice to control the name of custom template values 

### ISSUE THREAD

**Issue by timgriffiths** [grafana/grafana#2348]
I can see when you export the dashboard you store custom values as key value hash. It would be great if i could set the name and value independently in the gui

eg so you could define the values like (so key value pairs) 
abc=134,dbc=9238,yehd=3928

And in the drop down in the dashboard it would display abc, dbc, yehd but would pass in 134,9238,3928 to your queries

I currently change the exported json to do this then re-import the dashboard but it would nice if i could do this without this step.

**Comment by torkelo** [comment]
duplicate or https://github.com/grafana/grafana/issues/1032
