### ISSUE TITLE
division of two series with influxDB ? 

### ISSUE THREAD

**Issue by xfmoulet** [grafana/grafana#2349]
Hi, relating to #1295 -but using influxDB by example- , I'd like to know if it's possible to divide one serie by another one to have a percent that I can show, or have coloring on. Example : 404 vs 200 ratio, or getting time divided by sum of queries to get an average.

Is this possible ? can it be done on the client-side or maybe it must be done on the db ?

**Comment by torkelo** [comment]
This for now has to be implemented in InfluxDB (a feature it is missing). But I might add a feature in Grafana in the future where you can perform functions on series from any time series db

**Comment by migibert** [comment]
I'd love to see this feature, is there any plans about this ?

**Comment by torkelo** [comment]
ask the influxdb project , but we have plans for general meta queries (operations on query results) 
search for meta queries and you will find the github issue

**Comment by migibert** [comment]
It is an open feature request in influxdb project so... I'll have to wait.

Thank you for pointing me to the right project!

**Comment by chudov-clickadu** [comment]
Any news?
