### ISSUE TITLE
influxdb 0.9 data source should not contain db name

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2350]
Data source should only specify host:port，namely the influxdb instance.

DB name and retention policy should specified as part of measurement name like this:

"db"."retention policy name".measurement

https://github.com/grafana/grafana/issues/2018 can also be addressed using influxdb 0.9's this feature.

**Comment by torkelo** [comment]
would be good to get some more people to comment on this, how they see this being configured and available in metric editor. defaults? 

As soon as InfluxDB 0.9 supports some generic way to create roll ups (like roll up every series matching `/.*count/ using sum() function into new series with same tags. Some way to do that with few continuous queries and then have grafana automatically select right db or retention policy based on current time range. That way InfluxDB users finally can have fast queries no matter what time range they look at.

**Comment by Dieterbe** [comment]
keep in mind you may have different logins for different databases, and login is tied to datasource.

**Comment by timgriffiths** [comment]
Well that's only true when authentication is enabled, and you could set it up so you have the same read only user across all your databases, so it would be nice have the option, where we could change the database in the metric editor (from the default configured in the connection)

**Comment by zp-markusp** [comment]
For us this would be a must have feature as we have data distributed across different influxdb databases but need graphs from different databases on one dashboard. 
It's up to each user to ensure to have a generic read only user for all relevant databases. 
It might be an option to set a default database on grafana level which can be changed if required for a single metric if required

**Comment by zp-markusp** [comment]
@torkelo do you this this feature will make it into grafana? As we are switching to influxdb it would be great to know if we have freedom to organise our metrics into different databases or if we are forced to stick to a single database. 

Regards, Markus

**Comment by torkelo** [comment]
Since there has been lite demand for this during the development of influxdb 0.9 support in grafana 2.1 and during feedback from testing 2.1 pre release builds I think this will have to wait for 2.2 or later depending on feedback from more influxdb users.

**Comment by mobarre** [comment]
A little more feedback: we're currently migrating from graphite to grafana + influxdb. we get data from statsd, collectd, shinken and others. Each with (or without) their naming convention, types and such.
Basically, a namespace hell that wasn't really a problem with graphite, but does become a real one with influxdb. Using multiple databases is one of the solutions we have.
if each DB is a datasource, we're stuck because you cannot seem to mix different datasources on the same graph. Having the datasource be database agnostic is one way to solve the issue. Another is to mix datasources in a graph.
my 2 cents :)

**Comment by torkelo** [comment]
@mobarre why are you moving away from graphite? Just interested to know what the reasons are. 

If all influxdb databases use the same username and password I guess there could theoretically be a selector in the editor. But I think this issue will need many +1 votes for this to be an issue.

**Comment by mobarre** [comment]
@torkelo Our platforms generated around 3000 metrics per seconds. Carbon really can't handle that much. Also, we've been watching grafana for a while as we quite like Kibana so the transition makes sense especially with influxdb support (and elasticsearch which we use too).

**Comment by torkelo** [comment]
3000 per second is easy to do with carbon, I have seen single machines do 100 K per second with multiple carbons agents and a good SSD

**Comment by obfuscurity** [comment]
What @torkelo said. A single Carbon/Whisper instance is easily capable of well over what you're currently handling with Influx.

**Comment by liyichao** [comment]
@mobarre Yeah, before influxdb 1.0, you should stick to graphite. Influxdb has lots of issues and its function is not that powerful as graphite.

**Comment by lexh** [comment]
This is how I would want this to work, which is different from the original request. 

You leave the datasource configuration as it is. As was mentioned above, different users have different access levels to different databases, so this information should be configured alongside the database name [(docs)](https://influxdb.com/docs/v0.9/administration/administration.html). The change would instead be allowing to select the datasource on a per query basis.

This isn't critical for me personally, but it would have come in handy in a couple edge cases I've come across.

**Comment by torkelo** [comment]
Then we can close this as a new and implemented featue in mater is a mixed datasource where you can have a unique datasource (and datasource type) per query
