### ISSUE TITLE
v2.1.0 (20150706 nightly) - Repeat Panel doesn't work with URL vars

### ISSUE THREAD

**Issue by Inisfair** [grafana/grafana#2351]
I've set up a dashboard using a single template multi-value variable configured to repeat the panels based on the selected value(s).  When working with this dashboard interactively it works as expected, but when trying to use the share feature to load the dashboard with the var pre-set to some value the var parameters are ignored and the default option is rendered instead.

It appears that when a dashboard is saved using the repeat panel option, a section of data called scopedVars is saved with the panel definition and this prevents the dashboard from using the incoming URL parameters.

A secondary side effect of this is that if the repeat panel option is removed, the scopedVars section is retained which renders the panel static regardless of the template value selected even interactively.

Manually removing the scopedVars from the panel JSON and re-saving the dashboard appears to work around the issue as long as no other edits are made to the panels subsequently - as the scopedVars are re-saved at that time.  However doing so seems to disable the repeating panel capability and instead it tries to treat the incoming variable as a glob of values.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master!
