### ISSUE TITLE
Logs panel show entries in different order as they are in the files

### ISSUE THREAD

**Issue by pbuentam** [grafana/grafana#23528]
**What happened**: When the timestamp has a precission of seconds the log entries are shown in a different order than in the logs

**What you expected to happen**: Show logs in the same order as they are in the files

**How to reproduce it (as minimally and precisely as possible)**: Get a log without fraction of seconds and many entries every second

**Anything else we need to know?**:
I have checked the query created on Grafana and on Kibana, Kibana orders the entries query using the timestamp AND uses _doc as a tiebreaker by default, Grafana doesn't.

From Grafana:
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"sgt-filebeat"} {"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1555145843036","lte":"1586768243036","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"product.name:QLIKVIEW_SERVICES AND env:CERT AND host.name:(\"isbwvdqlfsc0001\") AND log.file.path:\"(\"E\\:\\\\logs\\\\Services\\\\20171025.txt\")\""}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"docvalue_fields":["@timestamp"],"aggs":{"2":{"date_histogram":{"interval":"6h","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1555145843036","max":"1586768243036"},"format":"epoch_millis"},"aggs":{}}}} 

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Elasticsearch
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Firefox, Chrome
- Grafana plugins: many
- Others:

**Comment by aknuds1** [comment]
Can you please try the latest Grafana version (6.7.2) and see if you have the same issue?

**Comment by pbuentam** [comment]
I have checked on 6.7.2 and it has the same issue. I have also checked on kibana.
Kibana has a configuration option to define the field used for tiebrake, they suggest _doc. In my oppinion log.offset is better if you intend to see just one file, _doc may be better if you inted to see several logs at the same time. 

Whe you use _doc and you are filtering only one file the lines will be shown in an altered order. Beats send log lines as bulk requests and nothing guarantees that they will be indexed in the same order. But when you use logs.offset you see them in the correct order. In the other hand if you inted to see several log files the log.offset is quite irrelevant as one file can have thousand of lines and another just a few.

The perfect option would be to add a propertie to the panel so the tiebrake field could be defined, the second best option would be to define it at datasource level.

Kind regards

**Comment by pbuentam** [comment]
I have checked the code and it's pretty easy to fix the datasource just adding a line in public\app\plugins\datasource\elasticsearch\query_builder.ts to hardcode de second sort.
The problem is that then you have to change the sorting methods in public\app\core\utils\explore.ts to take into account the new field and that implies modifying LogRowModel so it stores the offset and all this is transversal to all log datasource types. 
With elasticsearch a posibility can be reversing the array instead of sorting it, because all querys are sorted in descending order, but I don't know how it may affect the other datasources.

Kind regards

**Comment by Elfo404** [comment]
This was implemented in https://github.com/grafana/grafana/pull/28764 and released in 7.4, although we don't currently provide a way to configure the tiebreaker field, which as @pbuentam described might not work for all use cases. 

I'm closing this, feel free to open a feature request if there's still a need to configure the tiebreaker field
