### ISSUE TITLE
Grafana gets unresponsive with ad hoc filter type influxdb

### ISSUE THREAD

**Issue by moix** [grafana/grafana#23526]
**What happened**:
Grafana gets completely stuck and unresponsive when using an ad hoc filter of type influxdb

**What you expected to happen**:
Custom ad hoc filter applied to every component in dashboard properly and filter influxdb query 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create new dashboard
2. create a custom ad hoc filter type influxdb
3. create a custom ad hoc filter type influxdb
4. create any panel type using as datasource same influxdb ds selected in the ad hoc filter
5. try adding a filter
![Screenshot from 2020-04-13 07-32-04](https://user-images.githubusercontent.com/569132/79095070-baeee080-7d59-11ea-854c-dfd2c9441289.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.7.2 (423a25fc32)
- Data source type & version: influxdb
- OS Grafana is installed on: CentOS 7.7
- User OS & Browser: Fedora, reproduced in chrome and firefox

**Comment by hugohaggmark** [comment]
Hi @moix and thanks for reporting this, I tried this on a clean image and I couldn't repro this. Do you have any other plugins installed?
