### ISSUE TITLE
Cloning a panel results in error

### ISSUE THREAD

**Issue by AgrPriyank** [grafana/grafana#23537]
Observed behavior:
Cloning of a panel and putting the folder inside grafana/data/plugins folder results in error.
The new panel shows up in the list but whenever is selected, results in error.
The chrome inspect shows this,
Error loading panel plugin: graphExtended SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at lt (system.js:4)
    at system.js:4
    at system.js:4
    at O (system.js:4)
    at S (system.js:4)
    at system.js:4 

Since this is an exact copy of graph panel with a changed panelId, I figure it should work fine when put as an external plugin. However, it results in error.

Expected behavior:
The new panel should show up in the list and should work exactly like Graph panel.

Steps to reproduce:
1. Copy the contents of graph panel present inside public/apps/plugins/panel/graph and place it inside data/plugins folder.
2. Modify panelId and name inside plugin.json.
3. Restart the server.
4. Select the new panel in grafana UI.

Other comments:
I tried a different solutions available online which were reported bugs but all of that already seemed resolved in version 6.6.2. Upgrading the version to 6.7.2 did not work.

Environment:
- Grafana version: 6.6.2 or 6.7.2
- Data source type & version: Postgres
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Chrome
- Grafana plugins: Custom plugin

**Comment by torkelo** [comment]
copying internal panels like this is not supported 
but our sdk & ui package has a graph component you can reuse https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-graph-graph--with-custom-tooltip
