### ISSUE TITLE
Feature Request - Ability to use font awesome icons

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#23538]
**What would you like to be added**:
Ability to use font awesome icons in panel/plugin titles, series, legends etc.
The Boom Table plugin allows it by using strings like 
`_fa-arrow-up_`
With lots of options for colours etc.
https://grafana.com/grafana/plugins/yesoreyeram-boomtable-panel

I realise icons can be used in a few plugins which have the "Sanitize HTML" option by outputing the HTML, but native support everywhere would be a nice feature.

**Why is this needed**:
Icons would be useful to improve the readability/usability of dashboards. 

For example, I have a panel which monitors many different network devices. It would be useful to have icons next to each device name showing what type of device it was (router, switch, access point, camera, nvr or whatever).

Other examples on the boomtable plugin page as per the URL above.

**Comment by torkelo** [comment]
you will be able to use icons exposed via our grafana/ui Icon component https://developers.grafana.com/ui/latest/index.html?path=/story/general-icon--simple

**Comment by therealcodlord** [comment]
Not sure I understand your reply, but my feature request was meant as a feature for Grafana users to be able to reference and display icons on any/all panel types as easily as any text.

I was not speaking as a developer or asking for a feature for plugin developers etc? Does that make sense?

Thanks

**Comment by ryantxu** [comment]
you can already put whatever emoji/characters you want in the responses (ie 🦥) 

font_awesome is a pretty specific developer library.

**Comment by therealcodlord** [comment]
> you can already put whatever emoji/characters you want in the responses (ie sloth)
> 
> font_awesome is a pretty specific developer library.

o.k. thanks I didn't know that, so that works for static text/titles etc.

But not sure how to get emoji in data outputs etc.
So for example, at the moment my data returns labels such as {device_name} and {device_type}.
Can I have a label containing an emoji so that I can reference that label and the emoji displays? I tried in from my (Prometheus) data source and it didn't seem to work.
or
Can I have a different emojji being shown depending on the value of my {device_type} label? Not sure if that's do-able?

Thanks
