### ISSUE TITLE
Table Aggregation Distinct shows same timestamp value

### ISSUE THREAD

**Issue by haldi4803** [grafana/grafana#23535]
Hello,

I've used a Table to show current Battery Voltage.
![grafik](https://user-images.githubusercontent.com/17104473/79130685-a5a0a300-7da7-11ea-9376-cacf694ee8b5.png)

Now i tought it would be pretty cool to only show Timestamps when the voltage actually changed.
So i set Aggregations Distinct, to only show Unique values. But the Timestamp now only shows the newest timestamp on ALL vlaues.

![grafik](https://user-images.githubusercontent.com/17104473/79130786-d7196e80-7da7-11ea-8334-b4dfe1197668.png)

I can understand that it doesn't know wheter to take the first or last time the value shows up and take this timestamp.... but why would it take the same for all values?

Running Grafana v6.4.3 (3a2bfb7) in Docker.
Source: InfluxDB

**Comment by hugohaggmark** [comment]
Hi @haldi4803 , we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/).

All the best
