### ISSUE TITLE
Tooltips close when dashboard is automatically refreshing

### ISSUE THREAD

**Issue by h1nk** [grafana/grafana#23536]
**What happened**:
When viewing a tooltip such as the one for the Legend format while the dashboard automatically refreshes the tooltip closes while you're reading it.

**What you expected to happen**:
The tooltip to remain open as the dashboard UI refreshes.

**How to reproduce it (as minimally and precisely as possible)**:
Set a dashboard to automatically refresh every few seconds and view the Legend format tooltip while editing a panel.

**Environment**:
- **Grafana version:** `hub.docker.com/r/grafana/grafana:master`
- **Data source type & version:** Prometheus 2.17.1
- **OS Grafana is installed on:** Ubuntu 18.04.4 LTS within Docker CE 19.03.8
- **User OS & Browser:** Firefox Quantum 75.0 (64-bit) on Ubuntu 18.04.4 LTS
- **Grafana plugins:**

**Comment by hugohaggmark** [comment]
Hi @h1nk , not sure I understand what you mean. Can you please provide a screenshot to clarify as I can't repro this.

**Comment by h1nk** [comment]
@hugohaggmark, while viewing this tooltip in a dashboard that is set to automatically refresh every few second the tooltip will close while you're reading it.
![image](https://user-images.githubusercontent.com/12993584/79337487-1dd8a700-7f15-11ea-9fbc-2c7b99596dee.png)

**Comment by h1nk** [comment]
@hugohaggmark, I accidentally clicked close on this and the project card got moved to Done, can you move this back? Sorry about that...
