### ISSUE TITLE
Enhancement: New User Onboarding

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2353]
![newuser-userflow](https://cloud.githubusercontent.com/assets/2886187/8711106/0fe72a64-2b1d-11e5-9acd-781b059e8d77.png)

This workflow accommodates the following scenarios:

- Grafana Org admin invites users to an existing Org.
  - Newly invited user receives invite via email.
  - Newly invited user received invite via copy/paste.
- Self-service model
  - New user signs up on "Sign Up" tab of Grafana Login screen. 
  - New raintank user signs up on raintank website

**Comment by mattttt** [comment]
Here are some wireframes of the interface.

Org Admins: Invite User(s)
![orgadmin-newusermodal](https://cloud.githubusercontent.com/assets/2886187/8711254/5326803a-2b1e-11e5-9175-a224825b36a4.png)

Org Admins: Pending Invitations
![orgadmin-pendinginvitations](https://cloud.githubusercontent.com/assets/2886187/8711263/5ee17bdc-2b1e-11e5-9f8e-70bc96410c48.png)

Email Invitation: 
![emailinviteexample](https://cloud.githubusercontent.com/assets/2886187/8711270/6d9bafb2-2b1e-11e5-8182-41073f41cd65.png)

New User: Complete Signup (Existing Org)
![completesignup-existingorg-prefilled](https://cloud.githubusercontent.com/assets/2886187/8711276/757efa22-2b1e-11e5-94bf-6c80bb4d4104.png)

New User: Complete Signup (New Org)
![completesignup-neworg](https://cloud.githubusercontent.com/assets/2886187/8711285/7e4db4cc-2b1e-11e5-9070-b42918054676.png)

**Comment by mattttt** [comment]
Here is an invision prototype of the Pending Invitations show/hide functionality.

http://invis.io/PU3KB5XKM

**Comment by torkelo** [comment]
really nice work matt! Will start now!

**Comment by torkelo** [comment]
One thing we can think about is terminology. The page name is "Organization Users", this is also the term used in the code for an org "membership" .  The tab in your pic is also named "Users". But the button and modal call them "Members". 

Its tricky as a user account in grafana is called a "User". A org membership is as I said above just a org user. Not sure what the best naming is here

**Comment by mattttt** [comment]
Agreed, need to agree on consistently demonology.

**Comment by torkelo** [comment]
I am trying to get the first step of this into a workable state (the add user to org part). 

The problem I am having is how the dialog and button should work for already existing users, and how to add an existing user via username. 

An existing user will just be added directly, so no invite will be created (we can still send a email notice about the user being added). 

But the dialog and naming of buttons is strange in this case, as there wont be a pending invite created. 

Tried to rectify this but not sure I like it:
![image](https://cloud.githubusercontent.com/assets/10999/8952066/effdf28e-35d3-11e5-9527-8254708157b6.png)

![image](https://cloud.githubusercontent.com/assets/10999/8952091/0a9d491e-35d4-11e5-97fe-8ae43db63039.png)

But the the final button is strange to call "Invite Users" in this case. Also would be great to have some kind of auto complete search for existing users (but not show their email address, kind of like how you add users in Trello, but this could wait for another pass at this feature, so maybe keep it simple for now)

**Comment by torkelo** [comment]
Another thing that is weird about this that I cannot set the EmailVerified flag to true as the user could have been sent the link via other channels. One option that I just though of, but is going to complicate the implementation is to have two invite codes, one manual (used i the link we show), and one in the email we send, but then we have the feature that they can change email in the signup form, which will invalidate the email verification.

**Comment by torkelo** [comment]
@mattttt any thoughts?

**Comment by mattttt** [comment]
Still waiting on it to be available on dev-portal, and havent grabbed a build myself. I'll actually have another note to chat on the meeting tomorrow.

**Comment by torkelo** [comment]
@mattttt I think it will not appear on dev-portal any time soon since it is till in testing branch stage in upstream grafana. But it should be very easy for you to test locally, you can use your gmail as a smtp server

**Comment by torkelo** [comment]
@mattttt but before that I think just conceptually we can start brainstorming how the flow should work for usernames, as well as how to handle the fact that none of the current flow will allow is to say the email is verified

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/2353#issuecomment-125869115

**Comment by mattttt** [comment]
Yep, been slammed with other stuff, and have let this slide. Will spend some brain power on it today.

**Comment by mattttt** [comment]
`But the the final button is strange to call "Invite Users" in this case.`
^^ I dont actually think this is strange, because you're still inviting the user to your organization - so even if they're a grafana user, they're still being invited into a new group. 

We could be more specific and say "Invite Users to Org Name" on the button.

**Comment by mattttt** [comment]
Tested this today, a few things to change/update:

- Invitation email needs to be styled/updated.
- `Copy Invite` *to clipboard* not working in Safari. It is working in chome. 
- Created two new classes in grafana.less (long-tag and body-copy-emphasis), so check those out and make sure they're where you'd want them. I was having some specificity issues so just put them at the base level.

**Comment by mattttt** [comment]
@torkelo Submitted my changes in PR https://github.com/grafana/grafana/pull/2437

**Comment by torkelo** [comment]
Accept invite view: 

![image](https://cloud.githubusercontent.com/assets/10999/9575834/f9fd7872-4fd2-11e5-92b6-acd08c2b9961.png)

SignUp step1 view: (only email)
![image](https://cloud.githubusercontent.com/assets/10999/9575858/23a26f98-4fd3-11e5-9574-3de7d6ccf8fa.png)

SignUp step2 view (With backend options `verify_email_enabled=true`, and `auto_assign_org=false`
![image](https://cloud.githubusercontent.com/assets/10999/9575886/63c88cec-4fd3-11e5-83a8-eeca804a1ceb.png)

Above is the final signup form (which when completed actually creates the user), if email verification is enabled an email is sent after step1 and a verification code field is added to step2, if email verification is not enabled this field and email is not sent. 

If `auto_assign_org` is set to the above sign up form will not contain the org name field. 

After completing signup the user will be created and pending invitations to other organizations will be applied. If there were pending invitations you will be taken to this view: 

*Select active org* 
![image](https://cloud.githubusercontent.com/assets/10999/9575941/d3c16226-4fd3-11e5-82fe-0bfdca113392.png)

**Comment by torkelo** [comment]
merged to master
