### ISSUE TITLE
Ad Hoc filters causing an "An unexpected error happened" error

### ISSUE THREAD

**Issue by jericvizmanos** [grafana/grafana#23541]
**What happened**: 
“An unexpected error happened” shows up when trying to a add panel/row after adding ad hoc filters. 

<img width="1055" alt="error" src="https://user-images.githubusercontent.com/58444570/79169271-d4674b00-7da0-11ea-8bbe-c025887b1a79.png">

**What you expected to happen**: 
After clicking “add panel” it should automatically add and open up the panel.

**How to reproduce it (as minimally and precisely as possible)**:
1. From the dashboard’s settings > add variable
2. Choose ad hoc filter as type and choose ElasticSearch (or Prometheus) as the Data Source.

<img width="1153" alt="ad hoc filter" src="https://user-images.githubusercontent.com/58444570/79169161-8c482880-7da0-11ea-82b0-4d1708667fcf.png">

3. Go back to the Dashboard and populate the filter

<img width="1105" alt="add filter" src="https://user-images.githubusercontent.com/58444570/79169351-13959c00-7da1-11ea-92a4-68a7bf6cbef0.png">

4. Click on “Add Query” > See “An unexpected error happened” error.

**Anything else we need to know?**:
This issue was originally brought to our attention using the ElasticSearch datasource. However, I was able to reproduce this on multiple datasources including Prometheus, ElasticSearch and Graphite. 

Issue seems to only be happening on Grafana versions 6.7.x. v6.6.2 seems to be working properly after trying to reproduce the issue.

We were able to reproduce the issue both locally and on Grafana Cloud.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: ElasticSearch, Prometheus, Graphite
- OS Grafana is installed on:
- User OS & Browser: Chromium Version 79.0.3945.79 & 80.0.3987.163 and Firefox 71.0 & 75
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @jericvizmanos and thanks for reporting this, we're looking into this.
Related to #23526
