### ISSUE TITLE
Visualization Graph Display Only Every 5 Minutes Instead Of Every Minute

### ISSUE THREAD

**Issue by ThePieMonster** [grafana/grafana#23544]
**What happened**:
Data is stored in a SQL database, and that data is sent every 5 minutes.

**What you expected to happen**:
The last data point shown on the graph would be extended for each minute until a new data point is present.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a graph with time data every 5 minutes instead of every minute.

**Anything else we need to know?**:
View this forum thread about the issue for screenshots.
https://community.grafana.com/t/visualization-display-every-5-minutes/28476

**Environment**:
- Grafana version: Grafana v6.3.3 (84d0a71)
- Data source type & version: SQL DB
- OS Grafana is installed on: Windows Server
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment]
Not sure what you mean extended? Interpolated? Based on what?

Can you include raw data your query returns and what you expect to see in the graph and how it different from what Grafana renders

**Comment by ThePieMonster** [comment]
@torkelo Made a update to the original post.

**Comment by ThePieMonster** [comment]
Submitted new issue
https://github.com/grafana/grafana/issues/23547
