### ISSUE TITLE
Improve Select behavior in panels

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#23546]
Currently if a panel is at the bottom of the screen, the select will go up:

![image](https://user-images.githubusercontent.com/705951/79194025-a99ce700-7de0-11ea-9e07-266c76c41312.png)

But if the panel is not at the bottom of the page, it will go down... and get hidden:

![image](https://user-images.githubusercontent.com/705951/79194070-c0433e00-7de0-11ea-8cad-b44fc61d74a7.png)

I'm not sure if this is a simple z-index issue or something else.

Found this issue while working on https://github.com/grafana/grafana/pull/23545

**Comment by Clarity-89** [comment]
Seems like an issue with hidden overflow of one or several of the container elements. I had a similar issue in meta-analytics plugin, and tried to fix that in #23499 but I guess there's a different underlying issue.
