### ISSUE TITLE
Visualization Graph Display Only Every 5 Minutes Instead Of Every Minute

### ISSUE THREAD

**Issue by ThePieMonster** [grafana/grafana#23547]
**What happened**:
Data is stored in a SQL database, and that data is sent every 5 minutes.
![image](https://user-images.githubusercontent.com/11359134/79192589-dac7e800-7ddd-11ea-85c8-95265c620b63.png)
![image](https://user-images.githubusercontent.com/11359134/79192616-e87d6d80-7ddd-11ea-80c2-4ba078ea153a.png)

**What you expected to happen**:
The last data point shown on the graph would be extended for each minute until a new data point is present.
![image](https://user-images.githubusercontent.com/11359134/79192671-04810f00-7dde-11ea-8f62-9bb0d165472d.png)

**How to reproduce it (as minimally and precisely as possible)**:
Setup a graph with time data every 5 minutes instead of every minute.

**Anything else we need to know?**:
View this forum thread about the issue for screenshots.
https://community.grafana.com/t/visualization-display-every-5-minutes/28476

**Environment**:
- Grafana version: Grafana v6.3.3 (84d0a71)
- Data source type & version: SQL DB
- OS Grafana is installed on: Windows Server
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: None

**Comment by hugohaggmark** [comment]
Do I understand this correctly @ThePieMonster that you want the Graph to guess/extrapolate future values?

**Comment by ThePieMonster** [comment]
@hugohaggmark 
Not exactly. Lets say that the current time is 1:08 pm. The last data point that was received would have been at 1:05 pm. The graph shows no data for 1:06, 1:07, and 1:08 pm. I wanted to extend the last data point up to the current time.

Also for setting a alert on this type of graph. The alert is showing "no data". I think this is because the last few minutes didn't have any data, but this is correct because data is only gathered every 5 minutes.

Perhaps there is a different setting I need to set in the graph visualization or in the alert or both?

**Comment by hugohaggmark** [comment]
I don't really understand, if you don't have any data at the current moment of time then I think the graph will show nothing.

**Comment by torkelo** [comment]
Closing this, not sure there is anything Grafana can/should do here

**Comment by ThePieMonster** [comment]
@hugohaggmark @torkelo 
How are others setting up their visualizations then? Are they submitting for example CPU utilization data every single minute?

At the very least, how can I get this alert working?
![image](https://user-images.githubusercontent.com/11359134/79380161-dfdb8300-7f14-11ea-86ee-82922406f3e1.png)

**Comment by torkelo** [comment]
You can timeshift the graph so it looks back 5m , for alerts you normally look back also like alert on data 20min from now to 10min from now in your case you give you always 2 data points

**Comment by ThePieMonster** [comment]
@torkelo I'm to sure what you mean. What settings need to be changed?
Setting for Visualization?
Setting for Alert?

**Comment by ThePieMonster** [comment]
@torkelo I'm not to sure what you mean. What settings need to be changed?
Setting for Visualization?
Setting for Alert?

**Comment by ThePieMonster** [comment]
Ah, this just has to be changed to a 10m from a 5m for the alert. I thought this field was populated by the time field above, but you can click on it. Duh! 
![image](https://user-images.githubusercontent.com/11359134/79418581-d9c3c180-7f69-11ea-95a8-f91760c4dfb0.png)
That takes care of the Alert issue.

**Comment by hugohaggmark** [comment]
Closing this issue for now @ThePieMonster. We can always reopen this issue later if the need arises.

All the best
