### ISSUE TITLE
allseries tooltip not working in 2.1.0pre

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2355]
It always shows the latest point, no matter where I point my mouse to.

**Comment by torkelo** [comment]
http://play.grafana.org/  is running latest 2.1 and the all series tooltip seems to working fine. Do you have more info you can provide that can help me replicate the issue?

**Comment by liyichao** [comment]
<img width="1415" alt="2015-07-16 2 49 20" src="https://cloud.githubusercontent.com/assets/2576762/8717078/344d0592-2bca-11e5-99b3-6490fc6493fd.png">

when I switch off allseries, it shows datapoints at the right timestamp, which means there are actually datapoints instead of the latest one.

**Comment by torkelo** [comment]
looks like your query is wrong. are you using influxdb query without "sort asc" ? The data points needs to be sorting by timestamp in asc order by the time series store

**Comment by liyichao** [comment]
Yeah.
