### ISSUE TITLE
Stat/Gauge: Displaying wrong number of decimals for even thousands, millions, billions 

### ISSUE THREAD

**Issue by breeswish** [grafana/grafana#23561]
**What happened**:

Currently `ValueFormatter` is not respecting `scaledDecimals`, producing variable-decimal results:

```js
getValueFormat('short')(1, 0, 1)           // => 1
getValueFormat('short')(1000, 0, 1)        // => 1.0000 K
getValueFormat('short')(1000000, 0, 1)     // => 1.0000000 Mil
getValueFormat('short')(1000000000, 0, 1)  // => 1.0000000000 Bil
```

Consider some integer metrics like "Execution times", displaying with a decimal is not reasonable for such integer metrics when there is no scales: "Executed 10.0 times". However it is fine to keep a resonable decimal when the number is scaled, like "Executed 10.0 K times".

**What you expected to happen**:

```js
getValueFormat('short')(1, 0, 1)           // => 1
getValueFormat('short')(1000, 0, 1)        // => 1.0 K
getValueFormat('short')(1000000, 0, 1)     // => 1.0 Mil
getValueFormat('short')(1000000000, 0, 1)  // => 1.0 Bil
```

**How to reproduce it (as minimally and precisely as possible)**:

The above can be reproduced in [valueFormats.test.ts](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/valueFormats.test.ts)

**Anything else we need to know?**:

https://github.com/grafana/grafana/blob/61460ea3a211ef4655a1ef600da324fa84979102/packages/grafana-data/src/valueFormats/valueFormats.ts#L130

Maybe changing this line to the following can fix this bug:

```js
decimals = scaledDecimals;
```

**Environment**:
- Grafana version: master
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you not setting scaledDecimals correcly. It is working fine:

![Screenshot from 2020-04-14 15-35-34](https://user-images.githubusercontent.com/10999/79230937-a3048300-7e65-11ea-8e05-c44dc6a65b30.png)

Hmm. but I see that it's only graph panel that calculates the scaledDecimals correctly. For stat & gauge I get the same behavior your describing

**Comment by baurine** [comment]
hi @torkelo , how is this issue going, any progress?
