### ISSUE TITLE
Prometheus: browser crashes for big prometheus ds

### ISSUE THREAD

**Issue by moix** [grafana/grafana#23562]
**What happened**:
Users are getting a **proxy error: context canceled** while editing a prometheus query apparently due to huge list of metrics in a big prometheus setup (1 year retention)
Timeout happens after a couple of minutes
google chrome exit with white Aw, Snap! screen:
![Screenshot from 2020-04-14 14-37-52](https://user-images.githubusercontent.com/569132/79226643-00e19c80-7e5f-11ea-9c45-e32f27e9b860.png)

While checking the dev console seems that problem must be related to preload of prometheus metrics available in the ds:
```
https://grafana.myacme.com/api/datasources/proxy/90/api/v1/label/__name__/values
```
This is trying to retrieve all the metrics available in the prometheus, which for a medium-big instance could be a massive list. See screenshot before crash has downloaded up to 26.7MB:
![Screenshot from 2020-04-14 14-50-52](https://user-images.githubusercontent.com/569132/79227340-04c1ee80-7e60-11ea-81b5-ae7f66588ea5.png)

In grafana logs:
```
t=2020-04-14T07:45:07-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=26 orgId=1 uname=user1 path=/api/datasources/proxy/90/api/v1/label/__name__/values remote_addr=10.103.195.238 referer="https://grafana.myacme.com/d/S6Xew9TWk/prometheus-benchmark-2-13-x?orgId=1&refresh=5m&from=now-24h&to=now" error="http: proxy error: context canceled"
t=2020-04-14T07:45:07-0400 lvl=info msg="Request Completed" logger=context userId=26 orgId=1 uname=user1 method=GET path=/api/datasources/proxy/90/api/v1/label/__name__/values status=502 remote_addr=1.2.3.4 time_ms=7007 size=0 ref
erer="https://grafana.myacme.com/d/S6Xew9TWk/prometheus-benchmark-2-13-x?orgId=1&refresh=5m&from=now-24h&to=now"
t=2020-04-14T07:45:07-0400 lvl=eror msg="Request error" logger=context userId=26 orgId=1 uname=user1 error="net/http: abort Handler"
```

**What you expected to happen**:
Limit the amount of metrics retrieved from prometheus and avoid crash of browser.
Another option will be to set the preload of metrics for prometheus optional at datasource definition

**How to reproduce it (as minimally and precisely as possible)**:
create a panel and choose as datasource a prometheus with big amount of metrics

**Anything else we need to know?**:
Note: trying with other smaller prometheus datasources I have available (for example in testing envs) it works as expected but problem is when using a prometheus with huge number of metrics

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: prometheus
- OS Grafana is installed on: CentOS 7.7
- User OS & Browser: Google Chrome Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by hugohaggmark** [comment]
Thanks for reporting this @moix , we'll have a look.

**Comment by s-h-a-d-o-w** [comment]
Thanks for the detailed report @moix!
This problem is already being tracked [here](https://github.com/grafana/grafana/issues/21893) and [here](https://github.com/grafana/grafana/issues/22702).

**Comment by Estrax** [comment]
@s-h-a-d-o-w does it need any additional investigation? If not, can you remove the `need-investigation` label?

**Comment by s-h-a-d-o-w** [comment]
Since this problem is tracked in the other two issues I linked to above, one of which was addressed (there will be an "off switch" in the prometheus data source settings in 7.0), I'm closing this.
