### ISSUE TITLE
Add ability to sort dashboards in to folder/tree structure 

### ISSUE THREAD

**Issue by iDemonix** [grafana/grafana#2356]
We use Grafana to manage a very large and diverse estate, the issue we have is that we have a lot of different dashboards which are not alphabetically sorted and not in any sort of structure. It would be good to be able to have a folder i.e. "Proxy Servers" or "Mail Servers" that can drop down the associated graphs.

**Comment by torkelo** [comment]
Good idea, there is already an issue however :) 

https://github.com/grafana/grafana/issues/1611

**Comment by iDemonix** [comment]
Thanks, sorry - I searched but didn't find anything. Will subscribe to that :)
