### ISSUE TITLE
Help migrating Switch from 6.7 to 7

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#23578]
We have a bunch of forms with components like:

```
            <Switch
              label="Internal fields filtration"
              tooltip="Do not display fields with names starting with '_'"
              checked={ ... }
              onChange={ ... }
              labelClass="width-14"
            />
```

In master, `labelClass` and `tooltip` do not exist on Switch... is that easy to put back?  or what it a reasonable replacement?

**Comment by dprokop** [comment]
@ryantxu for label you would wrap your Switch in Field component, see https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-field--simple for example.

When it comes to tooltips you need to use composition:
```
<Field ...>
  <Tooltip ...>
    <Switch .../>
  </Tooltip>
</Field>
```

**Comment by ryantxu** [comment]
Does that mean this style switch is gone?

![image](https://user-images.githubusercontent.com/705951/79349917-ac383300-7eeb-11ea-979f-5ecd47be0e40.png)

Do we have any path that does not require a full redesign?

**Comment by ryantxu** [comment]
The real answer is to use:
```
import { LegacyForms } from '@grafana/ui';
```

```

            <LegacyForms.Switch
              label="Stream Mode"
              tooltip="Get data as they become available (experimental feature)"
              checked={ ... }
              onChange={ ... }
              labelClass="width-10"
              switchClass="max-width-6"
            />
```
