### ISSUE TITLE
Feature Request: use placeholder text for new dashboards instead of New Dashboard Copy

### ISSUE THREAD

**Issue by cogitaria-admin** [grafana/grafana#23579]
**What happened**:

Save button on new dashboard suggests name **New Dashboard Copy**.  

**What you expected to happen**:

This suggests it's already auto-saved New Dashboard and that Save is going to create another one; namely, a copy.  I've seen several users baffled by this and they will click Back or Manage or what have you.  

**How to reproduce it (as minimally and precisely as possible)**:

Create a new dashboard.

**Anything else we need to know?**:

Display a dimmed (empty) placeholder text _New Dashboard_. Do not fill it in with the confusing _New Dashboard Copy_ text please.  You can easily test this is an issue by getting somebody who's never used the tool to create a dashboard. Confusion will ensue. 

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by AlexHeylin** [comment]
It confused me - and I know Grafana.
