### ISSUE TITLE
auto_sign_up with auth.proxy  Error

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2357]
Hi @torkelo 

I've configured  grafana to get external auth with apache. I configured as shown.

```
[auth.proxy]
header_property = username
auto_sign_up = true
enabled = true
header_name = X-Webauth-User

[users]
allow_sign_up = true

```

But login process fails and  grafana logs are showing me these errors .

```
2015/07/16 11:59:34 [I] Completed /login 302 Found in 3.287831ms
2015/07/16 11:59:44 [middleware.go:151 initContextWithBasicAuth()] [E] Basic auth failed: User not found
```

I've reviewed headers sent and X-Webauth-User have been sent ok.

How can I fix this error?

```
GET / HTTP/1.1
Host: hosttest.domain,com
Cache-Control: max-age=0
Authorization: Basic dTJkczA2ODg6TG1xcGFQajc=
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: es,ca;q=0.8,en;q=0.6,en-US;q=0.4
Cookie: grafana_sess=8bc1cd76ba6021d9
X-Forwarded-For: X.X.X.X, Y.Y.Y.Y
X-BlueCoat-Via: XXXXXXX
X-Webauth-User: USERTEST
X-Forwarded-Host: hosttest.domain,com
X-Forwarded-Server: hosttest .doamin.com
Connection: Keep-Alive
```

**Comment by torkelo** [comment]
if you send basic auth headers to grafana it will try to authenticate using those. Either block the Authorization in apache, or disable basic auth in grafana  (setting is [auth.basic] enabled)

**Comment by toni-moreno** [comment]
You are right @torkelo
after disable  auth.basic  I can do autoSignUp.

But it is assigning to Main Organization( id=1 ) There is any way to auto assign to other Org different than id=1 ?

**Comment by torkelo** [comment]
@toni-moreno not currently :( auto signup only works with the default org (id 1) .

**Comment by Liugart123** [comment]
In the current version, auto singup only works with the default org ?
