### ISSUE TITLE
Runtime: replace the exported SystemJS with a Grafana defined API

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#23581]
While doing the documentation of the @grafana/runtime package APIs. I saw that we are exposing the entire `SystemJS` in the following place:

https://github.com/grafana/grafana/blob/master/packages/grafana-runtime/src/utils/plugin.ts#L11

I think it would be a good idea to replace this export with a better defined API that will support the scenarios that is the reason behind this export. The disadvantages that I see with exporting the `SystemJS` this way are:

- We can't control the API. If a plugin is depending in the current SystemJS and we upgrade to a new version of the `SystemJS` package it might break the plugins.
- By exposing the whole API we give access to the whole SystemJS which could be a security issue.

**Comment by ryantxu** [comment]
Sync with @stevenvachon -- at 7.0 we should be able to use a new version... and that may change how we can expose it to plugins

**Comment by dprokop** [comment]
moving to 7.0 milestone

**Comment by mckn** [comment]
closing this in favor of #23581
