### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Kenterfie** [grafana/grafana#2358]
We use a uwsgi/graphite backend and i try currently to update our "old" grafana setup.
Everything is working great only proxy mode isn't working.

I get many of these errors, but no additional infos. i have trace log enabled, but log is not very detail. Perhaps exist a way to enable better logging, but i can't find something.

2015/07/16 15:14:11 [I] Completed /render 500 Internal Server Error in 79.290588ms
2015/07/16 15:14:11 [I] Completed /render 500 Internal Server Error in 76.166798ms
2015/07/16 15:14:11 [I] Completed /render 500 Internal Server Error in 82.876192ms
2015/07/16 15:14:12 [I] Completed /render 500 Internal Server Error in 3.888857ms
2015/07/16 15:14:12 [I] Completed /render 500 Internal Server Error in 2.116959ms
2015/07/16 15:14:12 [I] Completed /render 500 Internal Server Error in 2.251677ms
2015/07/16 15:14:12 [I] Completed /render 500 Internal Server Error in 2.615842ms
2015/07/16 15:14:12 [I] Completed /render 500 Internal Server Error in 3.880794ms

Is it possible to get more info about the cause of the error.

**Comment by torkelo** [comment]
can you look in chrome dev tools (network tab) if Graphite is returning anything with the /render call? 

Is you graphite using https? I think there is an issue in 2.0.2 and self signed https certs when using proxy mode  (fixed in master and in 2.1 pre release builds)

**Comment by Kenterfie** [comment]
render call is nothing returning. i try if the problem fixed with master build.

**Comment by Kenterfie** [comment]
Thanks. Pre-Build fix the problem successful. Good work
