### ISSUE TITLE
Docs feedback: /alerting/notifications.md

### ISSUE THREAD

**Issue by jmidgren** [grafana/grafana#23584]
The last three sections of this page, listed to the right, are missing in the actual content:
* Enable images in notifications
* Use alert rule tags in notifications
* Configure the link back to Grafana from alert notifications

**Comment by aknuds1** [comment]
Would you mind making a PR? That would be the easiest way to fix it.

**Comment by jmidgren** [comment]
The missing sections seem to be present in the source, but they don't show on https://grafana.com/docs/grafana/latest/alerting/notifications/#configure-the-link-back-to-grafana-from-alert-notifications

latest=6.7 at time of writing.

**Comment by jmidgren** [comment]
> Would you mind making a PR? That would be the easiest way to fix it.

I saw that you assigned my next comment - would it still be helpful if I posted a PR?

**Comment by aknuds1** [comment]
@jmidgren Yes it would be helpful :)
