### ISSUE TITLE
Legend color does not match graph in case of many series

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#2359]
We have a graph with a considerable amount of series. For the graph, I have the impression that the colors are reused at some point in time, but the legend colors do not match these reused colors. The last legend entries are all gray tones.
![legend-color-error](https://cloud.githubusercontent.com/assets/1336287/8725826/c8c11f40-2bd6-11e5-9169-e8f988bc5050.png)

**Comment by torkelo** [comment]
fixed!
