### ISSUE TITLE
DirectInput: can't add or edit existing data source

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#23604]
When trying to add / edit Direct Input:
![image](https://user-images.githubusercontent.com/562238/79420971-351da000-7fba-11ea-9ffe-1db05eb08f75.png)

**Comment by torkelo** [comment]
This is an alpha datasource that was moved the bundle directory and is no longer built as part of grafana webpack.

But still, some things to fix with the bundling.

**Comment by torkelo** [comment]
you can build it now with `yarn plugins:build-bundled`
