### ISSUE TITLE
Graph panel doesn't update upon clicking legends which has similar names 

### ISSUE THREAD

**Issue by Kranthi-grafana-user** [grafana/grafana#23603]
**What happened**: Graph panel has legends which has same names, clicking on one of the legends is not disabling/enabling part of graph

**What you expected to happen**: Graph should highlight the when user clicks on legend

**How to reproduce it (as minimally and precisely as possible)**: Create a dashboard with graph panel 
Use any query so that all the legends will have same names
when we click on any legend graph is not highlighting corresponding portion of graph

**Anything else we need to know?**: NA

**Environment**: APM
- Grafana version: 6.6.1
- Data source type & version: Any datasource
- OS Grafana is installed on: WIndows
- User OS & Browser: Chrome
- Grafana plugins: Hraph
- Others: NA
![Screenshot (28)](https://user-images.githubusercontent.com/60780981/79420638-edf1d800-7fd6-11ea-909f-837324924cef.png)

**Comment by hugohaggmark** [comment]
@Kranthi-grafana-user thank you for reporting this!

**Comment by hugohaggmark** [comment]
Just out of curiosity @Kranthi-grafana-user why would you name all the series with the same name?

**Comment by Kranthi-grafana-user** [comment]
Query is trimming series names to avoid display unwanted/ large texts, which is resulting in returning the series with same name in some scenarios

**Comment by torkelo** [comment]
For the disable / hiding (And manually set colors) Graph panel uses the series name. So try to make them unique :) 

Some times order can change so the graph cannot use order (index) here
