### ISSUE TITLE
Azure Monitor data source still uses wrong uri for Azure China

### ISSUE THREAD

**Issue by mariomann** [grafana/grafana#23613]
**What happened**:
Related to the issue [#21803 ](https://github.com/grafana/grafana/issues/21803) I upated to Grafana version 6.7.2.
The "Save & Test" button at datasource configuration level was successful.

<img width="954" alt="Grafana_azure_datasource_1" src="https://user-images.githubusercontent.com/3458678/79452799-05d25780-7fe9-11ea-891b-f5f52b95225d.png">

But, when I want to request metrics from azure application insight, a "Metric request error" returns.
The request to [http://localhost:3000/api/tsdb/query](http://localhost:3000/api/tsdb/query) returns with HTTP status code 500.

<img width="1658" alt="Grafana_azure_datasource_2" src="https://user-images.githubusercontent.com/3458678/79452831-1387dd00-7fe9-11ea-8623-cde2da1412b3.png">

I could find in the logs, that the query was requested to **applicationinsights.io**, which is not correct, because it's not China. It should be **applicationinsights.azure.cn**

**Logs:**

> t=2020-04-16T11:44:53+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6
t=2020-04-16T11:44:53+0000 lvl=dbug msg=ApplicationInsights logger=tsdb.azuremonitor Request URL="https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6/query?query=customMetrics%0D+%7C+where+%5B%27timestamp%27%5D+%3E%3D+datetime%28%272020-04-16T11%3A14%3A52Z%27%29+and+%5B%27timestamp%27%5D+%3C%3D+datetime%28%272020-04-16T11%3A44%3A52Z%27%29+%0D%7C+where+name+contains+%22VVR_timer_hzOperations%22+%7C+where+isnotnull%28customDimensions.operation%29+%7C+extend+operation+%3D+customDimensions.operation+%7Csummarize+valueAvg+%3D+sumif%28valueCount%2C+value+%3E+0%29+by+bin%28timestamp%2C+1m%29%2C+tostring%28operation%29+%0D+%7C+order+by+timestamp+asc+nulls+last+"
t=2020-04-16T11:44:53+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6
t=2020-04-16T11:44:53+0000 lvl=dbug msg=ApplicationInsights logger=tsdb.azuremonitor Request URL="https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6/query?query=customMetrics+%7C+where+name+%3D%3D+%22VVR_timer_hzOperations%22+%0D%7C+where+%5B%27timestamp%27%5D+%3E%3D+datetime%28%272020-04-16T11%3A14%3A52Z%27%29+and+%5B%27timestamp%27%5D+%3C%3D+datetime%28%272020-04-16T11%3A44%3A52Z%27%29+%0D%7C+where+isnotnull%28customDimensions.result%29+%0D%7C+summarize+maxDuration+%3D+maxif%28value+%2F+valueCount%2C+value+%3E+0%29+by+bin%28timestamp%2C+1m%29%0D+%7C+order+by+timestamp+asc+nulls+last%0D"
t=2020-04-16T11:44:53+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6
t=2020-04-16T11:44:53+0000 lvl=dbug msg=ApplicationInsights logger=tsdb.azuremonitor Request URL="https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6/query?query=customMetrics+%7C+where+name+%3D%3D+%22VVR_timer_hzOperations%22+%0D%7C+where+%5B%27timestamp%27%5D+%3E%3D+datetime%28%272020-04-16T11%3A14%3A52Z%27%29+and+%5B%27timestamp%27%5D+%3C%3D+datetime%28%272020-04-16T11%3A44%3A52Z%27%29%0D+%7C+where+customDimensions.result+%3D%3D+%22failed%22+%7C+extend+exceptionMessage+%3D+customDimensions.exceptionMessage%2C+resultValue+%3D+customDimensions.result+%0D%7C+summarize+failedCount+%3D+countif%28value+%3E+0%29+by+tostring%28exceptionMessage%29"
t=2020-04-16T11:44:53+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6
t=2020-04-16T11:44:53+0000 lvl=dbug msg=ApplicationInsights logger=tsdb.azuremonitor Request URL="https://api.applicationinsights.io/v1/apps/a222e79c-f5a9-4895-adc1-3bbe1607f3d6/query?query=customMetrics+%7C+where+name+%3D%3D+%22VVR_timer_hzOperations%22+%0D%7C+where+%5B%27timestamp%27%5D+%3E%3D+datetime%28%272020-04-16T11%3A14%3A52Z%27%29+and+%5B%27timestamp%27%5D+%3C%3D+datetime%28%272020-04-16T11%3A44%3A52Z%27%29+%7C+where+isnotnull%28customDimensions.result%29%0D+%7C+extend+resultValue+%3D+customDimensions.result%0D+%7C+summarize+resultCount+%3D+sumif%28valueCount%2C+value+%3E+0%29+by+tostring%28resultValue%29%2C+bin%28timestamp%0D%2C+1m%29%7C+order+by+timestamp+asc+nulls+last"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request failed" logger=tsdb.azuremonitor status="404 Not Found" body="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Metric request error" logger=context userId=6 orgId=1 uname=mma error="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}" remote_addr=172.17.0.1
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request Completed" logger=context userId=6 orgId=1 uname=mma method=POST path=/api/tsdb/query status=500 remote_addr=172.17.0.1 time_ms=765 size=34 referer="http://localhost:3000/d/d5tJL1wWz/vvr-hzoperations?orgId=1&var-datasource=MIC-PROD-CN-CHINAEAST2-DEVDAT"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request failed" logger=tsdb.azuremonitor status="404 Not Found" body="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Metric request error" logger=context userId=6 orgId=1 uname=mma error="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}" remote_addr=172.17.0.1
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request Completed" logger=context userId=6 orgId=1 uname=mma method=POST path=/api/tsdb/query status=500 remote_addr=172.17.0.1 time_ms=765 size=34 referer="http://localhost:3000/d/d5tJL1wWz/vvr-hzoperations?orgId=1&var-datasource=MIC-PROD-CN-CHINAEAST2-DEVDAT"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request failed" logger=tsdb.azuremonitor status="404 Not Found" body="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Metric request error" logger=context userId=6 orgId=1 uname=mma error="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}" remote_addr=172.17.0.1
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request Completed" logger=context userId=6 orgId=1 uname=mma method=POST path=/api/tsdb/query status=500 remote_addr=172.17.0.1 time_ms=799 size=34 referer="http://localhost:3000/d/d5tJL1wWz/vvr-hzoperations?orgId=1&var-datasource=MIC-PROD-CN-CHINAEAST2-DEVDAT"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request failed" logger=tsdb.azuremonitor status="404 Not Found" body="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}"
t=2020-04-16T11:44:53+0000 lvl=eror msg="Metric request error" logger=context userId=6 orgId=1 uname=mma error="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}" remote_addr=172.17.0.1
t=2020-04-16T11:44:53+0000 lvl=eror msg="Request Completed" logger=context userId=6 orgId=1 uname=mma method=POST path=/api/tsdb/query status=500 remote_addr=172.17.0.1 time_ms=795 size=34 referer="http://localhost:3000/d/d5tJL1wWz/vvr-hzoperations?orgId=1&var-datasource=MIC-PROD-CN-CHINAEAST2-DEVDAT"
t=2020-04-16T11:44:54+0000 lvl=eror msg="Request failed" logger=tsdb.azuremonitor status="404 Not Found" body="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}"
t=2020-04-16T11:44:54+0000 lvl=eror msg="Metric request error" logger=context userId=6 orgId=1 uname=mma error="{\"error\":{\"message\":\"The application could not be found\",\"code\":\"ApplicationNotFoundError\"}}" remote_addr=172.17.0.1
t=2020-04-16T11:44:54+0000 lvl=eror msg="Request Completed" logger=context userId=6 orgId=1 uname=mma method=POST path=/api/tsdb/query status=500 remote_addr=172.17.0.1 time_ms=1332 size=34 referer="http://localhost:3000/d/d5tJL1wWz/vvr-hzoperations?orgId=1&var-datasource=MIC-PROD-CN-CHINAEAST2-DEVDAT"

**What you expected to happen**:
I expect to get metrics from Azure China.

**How to reproduce it (as minimally and precisely as possible)**:

- Add the Azure Monitor Datasource
- Configure an Azure endpoint for Azure China
- Add a Panel to a dashboard and request any data/metrics.

**Anything else we need to know?**:
I guess you changed it with issue #21803 in the Azure Monitor Datasource but not for the Grafana TSDB-API!?

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OS & Chrome
- Grafana plugins:
- Others:

**Comment by daniellee** [comment]
Confirmed. When we got a PR that added alerting for Application Insights, it did not include logic for switching to Azure China.

https://github.com/grafana/grafana/blob/20faef8de5fbdaa2395d5097e6d3f862b143f5d1/pkg/tsdb/azuremonitor/applicationinsights-datasource.go#L240-L249
