### ISSUE TITLE
Grafana not restored dashboards to folder

### ISSUE THREAD

**Issue by sirisukjinta** [grafana/grafana#23612]
I'm currently using version 6.7.0 but this bug I found for a while since 6.2.x.

I've tried to use CaC but it's not suitable for the task to create new users (it works but when restart all users are gone) so the solution is to use database in parallel (just config [database] in grafana.ini)

When using database even we have dashboards generated to JSON, it seems Grafana image has a script to load JSON to database but the bug is the script doesn't store folderId value to folder_id column in dashboard table (but store folderTitle and  folderUrl).

This issue caused when restart Grafana th dashboards will be restored to only general folder.

Please help to fix it ASAP

**Comment by hugohaggmark** [comment]
Hi @sirisukjinta , in order to help you out I need more information in the form below:
Environment:

Grafana version:
Data source type & version:
OS Grafana is installed on:
User OS & Browser:
Grafana plugins: 
Others 

Also I would help tremendous if you can give us steps to reproduce.

All the best

**Comment by sirisukjinta** [comment]
Hi @hugohaggmark 

The details as requested are below.

Grafana version: 6.7.0
Data source type & version: Postgresql v10
OS Grafana is installed on: Openshift
User OS & Browser: Windows/Chrome
Grafana plugins: N/A
Others: The bug is always happen when redeploy or restart Grafana. The JSON dashboards have been loaded to database without folderId. I think something wrong in the script to load JSON to database.

![image](https://user-images.githubusercontent.com/37993299/79528010-248d2880-8093-11ea-8197-1c7c8bb5aef1.png)
![image](https://user-images.githubusercontent.com/37993299/79528463-358a6980-8094-11ea-8a52-cddbd0e1529a.png)

**Comment by hugohaggmark** [comment]
Thanks for that information @sirisukjinta but can you provide a step by step instruction to repro this?

**Comment by sirisukjinta** [comment]
@hugohaggmark 
Nothing too hard.
Just deploy or terminate to pod and let the Openshift auto recreate, you will find it.

**Comment by hugohaggmark** [comment]
I don't think can help you at this stage with so little information. Try the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/) and see if someone can help you out.

All the best

**Comment by sirisukjinta** [comment]
@hugohaggmark 
Unacceptable closed!!
Have you tried with the information I provided?

Which information do you need more?
What don't you understand?

Can you explain what you understand with the information I provided??

Community cannot help because it's a "BUG" if Grafana image. No one can help only who can fix the image!!
