### ISSUE TITLE
Table link Tooltip outside of visible area

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#23617]
**What happened**:
A `table panel` - `column style` - `render value as link` - `toolip` is not visible, if the column is on the far right side of the table and the text is right aligned (this is the default value), it is cut off completely:

![tooltip](https://user-images.githubusercontent.com/33002073/79469143-17732980-8000-11ea-9b24-b1d3710a0323.png)

**What you expected to happen**:
The tooltip should be visible, it should be show above the table border (with scrollbar)
If it hits the right screen border, it should be moved to the left so it fits.

**How to reproduce it (as minimally and precisely as possible)**:
- Create dashboard, add table panel, select datasource `TestData DB`, select Scenario `Random Walk Table`
- `+ Add column style`, Apply to columns named `/Max|Info/`, Enable `Render value as link`
- `Use Url` = `http://google.com` , `Tooltip` = `DUMMY Tooltip Test for GH Issue`
- Ensure that `Align` = `right`  (this is the default in the default column style)
- View the table, tooltip on column `Max` is fine, `Info` is cut off

![WZXBvXYcMj](https://user-images.githubusercontent.com/33002073/79468028-c0208980-7ffe-11ea-8c3b-3244c44ec8c3.gif)

Can be fixed a little bit by using left alignment, does not help with long text:
![m6aMT2r67o](https://user-images.githubusercontent.com/33002073/79467467-193bed80-7ffe-11ea-8b3d-317d98ee2963.gif)

**Anything else we need to know?**:
- Probably duplicate of #16217, but worse behavior than just "always on the right side" , unfortunately the pull request was not accepted
- Panel JSON:
```json
{
  "datasource": "TestData DB",
  "columns": [],
  "fontSize": "100%",
  "gridPos": {
    "h": 9,
    "w": 13,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "pageSize": null,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "alias": "",
      "align": "right",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "link": true,
      "linkTooltip": "DUMMY Tooltip Test for GH Issue",
      "linkUrl": "http://www.google.at",
      "mappingType": 1,
      "pattern": "/Max|Info/",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "alias": "",
      "refId": "A",
      "scenarioId": "random_walk_table",
      "stringInput": ""
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Panel Title",
  "transform": "table",
  "type": "table"
}
```

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: TestData DB
- OS Grafana is installed on: Windows 10 1909
- User OS & Browser: Windows 10 1909, Firefox 75.0
- Grafana plugins: Table Panel

**Comment by hugohaggmark** [comment]
Thanks for reporting this @Mario-Hofstaetter but as @torkelo mentioned https://github.com/grafana/grafana/pull/18017#issuecomment-533008824 we're creating a brand new Table Panel in React so I don't think we'll fix this in the old Table Panel. 

I'll make sure this we add this to the new Table Panel and close this issue.

All the best
