### ISSUE TITLE
API always return "Dashboard not found" after add new dashboard

### ISSUE THREAD

**Issue by yahliu** [grafana/grafana#23610]
**What happened**:
1. I tried to add grafana dashboard via yaml file 
```
apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: MonitoringDashboard
metadata:
  name: sample-test
spec:
  enabled: true
  data: |-
    {
        "uid": "",
        "title": "smaple testing dashboard",
        "tags": [ "test" ],
        "timezone": "browser",
        "schemaVersion": 16,
        "version": 1
      }
```
2. use API `api/dashboards/uid/xxx` to curl this dashboard, always return "Dashboard not found" in half hour.  
3.  then I switch to grafana web console to check this dashboard if it's shown and this dashboard was added and shown in the grafana web console. 
4. then re-run API in the command line, can be returned this dashboard.

**What you expected to happen**:
use API `api/dashboards/uid/xxx` to get this dashboard
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I checked no conflict uid for this dashboard in my cluster.  seems dashboards sync to db until I  checked dashboard in grafana UI.
**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Prometheus 
- OS Grafana is installed on: openshift env
- User OS & Browser: coreos & chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
> 1. I tried to add grafana dashboard via yaml file
> 
> ```
> apiVersion: monitoringcontroller.cloud.ibm.com/v1
> kind: MonitoringDashboard
> metadata:
>   name: sample-test
> spec:
>   enabled: true
>   data: |-
>     {
>         "uid": "",
>         "title": "smaple testing dashboard",
>         "tags": [ "test" ],
>         "timezone": "browser",
>         "schemaVersion": 16,
>         "version": 1
>       }
> ```

This is not something officially supported by Grafana, seems to be provided by IBM? The only suggestion I can give you is to provide a value for `uid`, for example "abc" and then you should be able to curl `api/dashboards/uid/abc` - at least that's how it works if you create a dashboard via API or [provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/).

Closing this, but consider reopen if you can provide information that shows this is a Grafana problem.
