### ISSUE TITLE
All option of datasource variable shares info between Grafana interfaces.

### ISSUE THREAD

**Issue by lamanchy** [grafana/grafana#23628]
**What happened**:
I have two different instances of both influx and grafana, one installed locally one on the server, they share no data.
I configured a datasource variable called "source" with Include All option selected.
Then there is a variable group and host:
![image](https://user-images.githubusercontent.com/4850265/79479813-99b61a80-800d-11ea-9db7-7a53acddf788.png)
When freshly installing the local grafana and influx, without any data yet, the variable selection is:
![image](https://user-images.githubusercontent.com/4850265/79481408-bce1c980-800f-11ea-9878-d54292bedcf2.png)
therefore you can select hosts, which are present on the "server" influx and grafana. No data are loaded, but still. Works in incgnito mode as well. 

**What you expected to happen**:
Not be able to select any host, since no data are present in the underlining influx.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure what specifically causes that, since for example, the group variable behaves normally. 

Can be easily fixed by disabling the "include all option", but the bug is so weird I had to report it :D

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: inlfux 1.5.3
- OS Grafana is installed on: pc is windows, server is linux, it does not matter i would guess
- User OS & Browser: windows, chrome but edge as well
- Grafana plugins: none extra

**Comment by torkelo** [comment]
Please consult influxdb docs and support as Grafana just shows what influxdb is returning .

But in looks like your template variable is not we to refresh (reload) it’s values on reload.

Go into variable setting and set the refresh option

**Comment by lamanchy** [comment]
Setting refresh option works, but it's really weird, when even on first startup a grafana on localhost:3000 shows unrefreshed variable values from grafana.rnd.local.

To be more exact:
I have a grafana and inlfux running on grafana.rnd.local, full of data, it shows everything correctly.
But when I open separate grafana running on localhost:3000, which is communicating with EMPTY influxdb running on localhost as well, the host variable still shows list of hosts from grafana.rnd.local.
