### ISSUE TITLE
Anonymous template export

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2362]
When using Export on dashboard with variables it would be nice to have an option to remove the values from the generated json file.

**Comment by torkelo** [comment]
why?

**Comment by rschitz** [comment]
Because some company rules are against "sensible" data export like hostname/ip etc...

**Comment by torkelo** [comment]
not sure I see the point of this. The data is there anyway (if you open chrome dev tool and look at the network traffic)

**Comment by rschitz** [comment]
I'm sorry i didnt explained myself correctly.
I'll retry with a use casz.
Thanks
