### ISSUE TITLE
FeatureRequest: Expand Variables in News Panel

### ISSUE THREAD

**Issue by noonker** [grafana/grafana#23639]
**What would you like to be added**:
Currently the News Panel allows you to add feeds to dashboards. It would be very nice if the feed URLs supported variable expansion so you could create parameterized keyword searches like this:
https://news.google.com/rss/search?q=$var

**Why is this needed**:
I can imagine there's quite a few use cases for this. I have a list of malware families I'm tracking as part of my research. Currently I have my dashboard parameterized so I can switch which family I'm monitoring- it would be nice to see news events for each family on the same dashboard.

**Comment by hugohaggmark** [comment]
Thanks for contributing with this feature request @noonker !

**Comment by dprokop** [comment]
@noonker thank you for opening the issue. We do not see much of an interest in this feature so I will close this for now.
