### ISSUE TITLE
Grafana Newbie - Installation Issues on Windows / Importing CSV Files

### ISSUE THREAD

**Issue by crabbylou** [grafana/grafana#2363]
When installing Grafana on Windows, I run grafana-server.exe, but when I pull up the URL http://localhost:3000, the login screen keeps flashing over and over again, and the grafana DOS command window keeps repeating this error:

2015/07/17 15:51:37 [I] Completed /login 200 OK in 7ms
2015/07/17 15:51:38 [I] Completed / 302 Found in 6ms

Am I supposed to edit the custom.ini, or will Grafana work right out of the box?

Another Question - I'm hoping to be able to read CSV files to graph system OS statistics. Can Grafana read CSV files, or will I need to convert to JSON or import the data into a database first?

Any help is appreciated.

Lou

**Comment by crabbylou** [comment]
Actually, it only does the flashing screen in Internet Explorer. Opening Grafana in Firefox works fine.

That leaves me with my second question. I tried opening my CSV through Grafana and it did not like that, so I am assuming I have to convert the CSV to JSON or import into a database.

**Comment by damm** [comment]
Graphite, InfluxDB, and OpenTSDB are supported in 2.0; 2.1 added KairosDB 

Review http://docs.grafana.org/ and look under Data Sources.

**Comment by torkelo** [comment]
CSV import is not supported , and you need a time series database for Grafana to be useful 

The IE 9 problem is known, think there is another issue for it
