### ISSUE TITLE
Ability to alert on terms with 0 event count with elastic datasource

### ISSUE THREAD

**Issue by s1sfa** [grafana/grafana#23636]
When graphing queries from an elastic datasource I am unable to set the min_doc_count to 0 on terms query. The interface always resets this value to 1 when trying to select 0. This allows us to view the terms that have 0 value. From the perspective of alerting, gathering a list of terms for variable or wanting to see the 0 values I think min_doc_count:0 should be an option.

I have two cases where min_doc_count:0 being set could be helpful.
Alerting:
If you have a couple dozen hosts sending syslogs, but you want to alert if one has 0 events for 24h. If there are no events in 24h with min_doc_count > 0 the server wouldn't be listed with a 0 value if it has 0 events for the time range.  The result is that terms with 0 events silently disappear. 

Variables:
I noticed that if I have a short time window set at the top right in grafana, it limits the terms returned to populate a variable.  There isn't really a spot to set min_doc_count here, but was something I realized when thinking of ways I could try to work around this in the graph panel queries.
{“find”: “terms”, “field”: “@hostname”, “size”: 1000} - seems to only return the term values for non 0 terms in grafana time range. 

I've tried setting min_doc_count to 0 in graph panels but it resets back to 1. I can set 0 in the json editor, and it seems to have this desired behaviour for alerting. Editing the graph always tries to set it back to 1 though. 

I think the default used to be 0 at some point, now the default is 1. I don't see any notes about intentionally not allowing 0 value in the commits. Maybe not being able to set min_doc_count to 0 is an unintended consequence. https://github.com/grafana/grafana/issues/8321

Being able to see terms with 0 values can be important too. As @torkelo has commented in the past.
https://github.com/grafana/grafana/issues/6121#issuecomment-249279961

**Comment by hugohaggmark** [comment]
Thanks for reporting this @s1sfa but I get mixed signals about this setting from the provided PR/comments. We need to investigate further.

**Comment by Estrax** [comment]
Good point regarding visualization of terms with `min_doc_count` equal to 0. Addressed it in #24204

**Comment by Inverness** [comment]
@Estrax Is it expected behavior that results are only shown in a table with min_doc_count set to 0 if there is only one term group, but not if there is two or more?
