### ISSUE TITLE
Dashboards with Cloudwatch metrics take hours to load after update from 6.3.3 to 6.6.2

### ISSUE THREAD

**Issue by ddseapy** [grafana/grafana#23644]
**What happened**:

We updated the version of Grafana, with no configuration changes, and any dashboards that have panels with cloudwatch metrics take over an hour to load.  Simply changing the docker image back to 6.3.3 fixes the issue.  Any dashboards that do not rely on cloudwatch load as quickly as they did before the version change.

**What you expected to happen**:

Dashboards using cloudwatch to continue loading in a reasonable amount of time.

**How to reproduce it (as minimally and precisely as possible)**:

Change version of grafana docker from 6.3.3 to 6.6.2 with dashboards that rely on cloudwatch datasource

**Anything else we need to know?**:

We don't see anything in the logs that would indicate what it's hung up on.
We realize that grafana changed the cloudwatch endpoint it uses in 6.5.  Using the aws cli we are able to query the getMetricData api, and since the dashboards eventually load presumably grafana can too?

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Cloudwatch (version is whatever is built into 6.6.2)
- OS Grafana is installed on: Amazon Linux 2 (on kubernetes)
- User OS & Browser: Issue presents on both firefox and chrome
- Grafana plugins:
- Others:

**Comment by ddseapy** [comment]
Also, clicking "Save & Test" in the datasource also takes a very long time (many minutes) to complete successfully on 6.6.2, whereas on 6.3.3 it was less than a second.

**Comment by hugohaggmark** [comment]
Thanks for reporting this @ddseapy , we'll investigate this further.

**Comment by ddseapy** [comment]
Updating to 6.7.2 seems to have resolved the issue.
