### ISSUE TITLE
heatmap: hide zero bucket on y-axis

### ISSUE THREAD

**Issue by BusyJay** [grafana/grafana#23649]
**What would you like to be added**:

When a y-axis bucket doesn't have a non-zero value over the whole time range, hide it from the heatmap. So half of the following graph can be removed and be more readable.

![image](https://user-images.githubusercontent.com/1701473/79572913-4e286d00-80f0-11ea-9149-84d583caeb28.png)

**Why is this needed**:

Histogram buckets can be designed by service provider for generic data. But a particular service may only generate data that fits in some buckets, or a service may only produce data that fit in higher bucket at particular time. So always show up all buckets can make the graph too small to read.

**Comment by marefr** [comment]
There's already an option for hiding zeroes - what are you actually requesting?

**Comment by marefr** [comment]
Btw, what data source are you using?

**Comment by BusyJay** [comment]
> ...what data source are you using?

I'm using Prometheus. 

> ...already an option for hiding zeroes...

Existing option hides color in the graph, I'm asking hiding y-axis ordinates. For example, the graph in the issue description has no color points in buckets >= 512ms over the whole time range. So y-axis can only show ordinates < 512ms.

**Comment by marefr** [comment]
@BusyJay thanks. You can set Y-Min or you can filter out zeroes in your Prometheus query (I think ` > 0`. Isn't that enough?

**Comment by torkelo** [comment]
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.

**Comment by shayanh** [comment]
I have this issue and couldn't figure out a solution. I tried ` > 0` but it doesn't hide any bucket on y-axis.

Related: https://github.com/grafana/grafana/issues/25097

**Comment by shayanh** [comment]
Apparently it's not possible to reopen the issue @torkelo

**Comment by laker-93** [comment]
I'm facing this same problem. @torkelo @shayanh @BusyJay @marefr 

I have a lot of unused buckets. I want Grafana to dynamically filter out any buckets that do not have an increase so the y axis automatically scales with a better resolution.

I have tried the obvious:

increase(latency_bucket[$__rate_interval]) > 0

which has had the desired effect of capping the y axis on the lower limit however larger buckets still exist with spurious values 

How can I have Grafana properly dynamically filter out buckets that do not increase so I can have a y axis that scales appropriately?
