### ISSUE TITLE
InfluxDB non_negative_derivative plot showing duplicate metric lines?

### ISSUE THREAD

**Issue by djace** [grafana/grafana#2365]
Hi,

I've got network speed usage information (octet count) in an InfluxDB. I'm using a non_negative_derivative(value) to plot it, with a fixed 10s group by time interval. Graphs are fine up from "Last 5 Minutes" up to "Last 24 hours" approximately. Beyond that, multiple metrics start appearing in the graph out of nowhere. Am I doing something wrong or is this a bug?

![graph-1_cr](https://cloud.githubusercontent.com/assets/1256026/8765566/40364432-2e12-11e5-8d88-693514e6f6f9.png)
![graph-2_cr](https://cloud.githubusercontent.com/assets/1256026/8765567/43a042c6-2e12-11e5-884a-c7aec0793afd.png)
![graph-3_cr](https://cloud.githubusercontent.com/assets/1256026/8765568/45570f6e-2e12-11e5-843e-5341cccc6455.png)
![grah-setup](https://cloud.githubusercontent.com/assets/1256026/8765569/48eb1a9e-2e12-11e5-9df4-f7a292a376b5.png)

By the way, I'm fixing the "Group By" interval to 10s instead of ">10s" because if I don't, the data is grouped in larger intervals when plotting graphs of > 24h, resulting in incoherent values graphed, such as a 30Mbps network link graph showing speeds of 3Gbps. I'm assuming this related to the values returned by InfluxDB and its just a side effect of using the combination of a derivative function and a time interval that does not match the input data!

**Comment by torkelo** [comment]
This is an InfluxDB bug, https://github.com/influxdb/influxdb/issues/3242 then influxdb returns many data points it gets split into multiple series, also discussed here: https://github.com/grafana/grafana/issues/2266

Since you locked the query to 10s group by time does it not get very slow? As InfluxDB must be returning thousands and thousands of data points per series. You should aggregate the data points in InfluxDB (using average or something that makes sense). Time series queries should be really fast (like 25 - 100ms), they usually are for Graphite no matter what time range you use. Rollups are important if you want to look at different time ranges :)

**Comment by djace** [comment]
Thanks for the update and reference to that InfluxDB bug!

The query does get very slow by locking it to 10s, indeed! I've really got to get a handle on how to aggregate the data points in InfluxDB in a way that makes sense, but I haven't found proper documentation on it! Also, I'm waiting for proper 0.9 support for Continuous Queries before exploring this.

**Comment by dankeder** [comment]
I encountered the same problem with the `derivative()` function and I think I found a workaround. I couldn't find it documented anywhere, so I'll put it here:

I have an InfluxDB query:

    SELECT derivative(value, 1s) FROM "interface_tx" WHERE time > now() - 3d GROUP BY time(1h)

Which returns a large number of values split into several chunks, forcing Grafana to think each chunk is a separate series.

I rewrote it to this:

    SELECT derivative(mean(value), 1s) FROM "interface_tx" WHERE time > now() - 3d GROUP BY time(1h)

This should calculate the "average" of values grouped by hour, and from these average values it calculates the derivative per second.

**Comment by djace** [comment]
Seems interesting! But how do you accommodate for multiple time periods of different scales (hour, day, week, month?) in a query like that?

**Comment by dankeder** [comment]
I actually have `$interval` in the group-by clause, not `1h` (that was just an example I used in influxdb shell). The `$interval` template variable is replaced by the actual time duration by Grafana. So the query in Grafana looks a bit more like this:

    SELECT derivative(mean(value), 1s) FROM "interface_tx" WHERE $timeFilter AND host='$host' AND type='if_octets' AND instance='$iface' GROUP BY time($interval) ORDER BY asc

(I also use templates in my dashboard, `$iface` and `$host` are replaced by actual values at runtime.)

**Comment by djace** [comment]
Superb! I just changed all my interface queries, thanks a lot for documenting this!

Now we only need good Continuous Queries support in both InfluxDB and Grafana to get this whole thing sorted out!
