### ISSUE TITLE
Explore table view doesn't show data

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#23657]
Running a prometheus query, the instance query in explore table view says "returned 0 rows" when it did in fact return rows:

<img width="1392" alt="Screenshot 2020-04-17 at 17 35 55" src="https://user-images.githubusercontent.com/444037/79592485-f7ac3600-80d1-11ea-8118-1944346b60c3.png">

Version: Grafana v7.0.0-254070a2pre (43fc6c3a17)

**Comment by torkelo** [comment]
Must have been something temporary, works for me now. Tested with a query that only returned single series

**Comment by tomwilkie** [comment]
Can confirm, works for me now too.

**Comment by tomwilkie** [comment]
This is happening again:

![image](https://user-images.githubusercontent.com/444037/80025449-95d83b80-84d8-11ea-9bd8-5b7f4b1a49cf.png)

Grafana v7.0.0-67c235cfpre (66d405acab)

Could it be time related?

**Comment by ivanahuckova** [comment]
I have looked into this issue and found following - in [ResultProcessor](https://github.com/grafana/grafana/blob/master/public/app/features/explore/utils/ResultProcessor.ts#L53) when we are creating table results, we filter out all frames that are time series (as you can see in the comment created by @torkelo we are purposely ignoring time series for prometheus for now). And the way how we determine if it is time a series is [by checking if it the dataframe has exactly 2 fields and if the first one is time](https://github.com/grafana/grafana/blob/master/public/app/features/explore/utils/ResultProcessor.ts#L122-L128). And @tomwilkie the response that you have provided exactly matches that - it doesn't have any metrics and therefore its dataframe has only 2 fields and the first one is time. Therefore it is considered time series and it is not shown in the Explore table. 

For example response with metrics results in more than 2 fields and therefore it is displayed in the table: 
![image](https://user-images.githubusercontent.com/30407135/80492676-ab2fe880-8964-11ea-82b6-7e7cec7b3dc6.png)

So couple of  questions resulting from this:
- Should we change processing of instant queries at Grafana side?
- Should we add a quick-fix and show in table timeSeries with length of its values === 1? 
- Is it correct that the response from prometheus doesn't have any metrics for certain instant queries?

**Comment by ivanahuckova** [comment]
I will also move this down in our Backlog bugs priority list as it is affects only very small amount of queries.

**Comment by tomwilkie** [comment]
> Is it correct that the response from prometheus doesn't have any metrics for certain instant queries?

Yes, the metric name is erased when you do aggregation in Prometheus.  Can confirm, when you don't do an aggregation (and the metric name is returned) then the instance view works.

> I will also move this down in our Backlog bugs priority list as it is affects only very small amount of queries.

I'd argue this is a pretty major regression; instance queries and aggregation are two very frequently used features.

**Comment by ivanahuckova** [comment]
> I'd argue this is a pretty major regression; instance queries and aggregation are two very frequently used features.

Thanks for the information! I'll keep in on top and start to work on fix. :)
