### ISSUE TITLE
toolkit issues

### ISSUE THREAD

**Issue by briangann** [grafana/grafana#23662]
maybe the fingerprint should be pulled from a circleci environment variable for the project:

https://github.com/grafana/grafana/blob/4e521a84b43c22b6d7b784b2291474b8cf064d74/packages/grafana-toolkit/config/circleci/config.yml#L6

like this
```YAML
parameters:
  ssh-fingerprint:
    type: string
    default:  ${GITHUB_PUBLISH_KEY}
```

this is pulling a private repo:

https://github.com/grafana/grafana/blob/4e521a84b43c22b6d7b784b2291474b8cf064d74/packages/grafana-toolkit/config/circleci/config.yml#L186

this line hardcodes the google sheets plugin as provisioning:

https://github.com/grafana/grafana/blob/4e521a84b43c22b6d7b784b2291474b8cf064d74/packages/grafana-toolkit/config/circleci/config.yml#L193

Maybe check a project env variable for a provisioning repo and skip if nothing is defined? a panel plugin won't have a datasource to configure during a test.

**Comment by srclosson** [comment]
@ryantxu Good point about the private repo. We could use this only for enterprise plugins.... thoughts?
