### ISSUE TITLE
Make graph panel with large number of series more performant esp for Alerts

### ISSUE THREAD

**Issue by raags** [grafana/grafana#23665]
**What would you like to be added**:
Ability to render a large number of series, without slowing down the dashboard/browser.  This is especially needed for adding alerts to high cardinality metrics. Possible approaches:

1. A "dumbed" down visualisation that is lighter on the browser (something like what Prometheus console does).
2. Provide an ability to turn off the visualization grid, and only keep the legend to show the current thresholds (for alerts mainly). Right now it's possible to turn off the display by toggling all "Display Mode" options, but an empty grid is still visible.

**Why is this needed**:

Adding an alert for a high cardinality metric can slow down the dashboard considerably, for e.g. adding an alert for `node_cpu_seconds_total`. One way this is prevented normally is by using template variables, but it's not possible or desired when adding an alert, as you want it to apply to all instances.

One workaround is to use an `instant` query that just shows the latest data point. Or disable all display modes entirely. And have another panel with template to see the trend (we keep the alert and graph panel separate anyways).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
