### ISSUE TITLE
Multi Value - default "select all values"

### ISSUE THREAD

**Issue by skvaknin** [grafana/grafana#23677]
**I have a multi value variable, that sometimes can show 1 result, and sometimes 5, for instance.
i want to be able to present all of them, always, on one tile.
the problem is, that when there is a 1 value result, all works fine, but when there's a 5 value result i need to manually check the "all" in the variables drop down list on the dashboard it self, in order to show them.
i wish there was a default feature that says something like - "always show all possible values"
**

**it is necessary to avoid switching value results manually**:

**Comment by marefr** [comment]
Check the all values and save the dashboard. Not sure there's something we can do here.

**Comment by marefr** [comment]
Next time please use a proper issue template https://github.com/grafana/grafana/issues/new/choose when submitting an issue. Thanks

**Comment by georgettica** [comment]
if I can ride on this issue

sometimes the variable source is a query and changes every hour, soo selecting all and saving is not a good solution

can there be a "selected regex" field I can play with?

**Comment by LukasK13** [comment]
I think @georgettica has a valid point. When the variable source is a query, the variables values can change over time, so saving does not fix the problem at all.
This issue should be reopened.

**Comment by LukasK13** [comment]
I really like the idea of a select regex field as it not only allows to select all by default but also to select only specified fields by default.

**Comment by cwrau** [comment]
We'd also like this feature
Saving is not really an option, especially when the dashboard is meant for distribution and/or the query can have different results

**Comment by DeathRabbit679** [comment]
Just hit this too, it makes dynamic variables pretty much worthless if they change, like, with any frequency at all.

**Comment by DeathRabbit679** [comment]
I found a way around this, at least for my use case. 
![image](https://user-images.githubusercontent.com/37566060/167212010-49f58136-c2da-48f3-9103-3b3ef5285e07.png)

If you explictly include an "all" option for your multi-value variable, and select that then hit save or use it as your `current` block in your provisioned dashboard or however you're doing things, this will allow you to have query driven multi-value variables that always render all returned values in whatever way you're trying to use them, in my case, I was querying prometheus label values and displaying a repeating panel per label values. I'm on grafana 8.5.2

**Comment by LukasK13** [comment]
I solved this problem by manually adding a selectAll button to Grafana in my fork https://github.com/LukasK13/grafana/tree/8.4.1_selectAll

**Comment by mfurquimdev** [comment]
I'm having the same issue as @vbence.  
I created a hidden variable which I want the value to be *all* values returned by the query.  
However, the default value is the first option instead of all the values.  
Since the variable's label and value are hidden, there is no way to select them all.

**Comment by stijnbernards** [comment]
> I'm having the same issue as @vbence. I created a hidden variable which I want the value to be _all_ values returned by the query. However, the default value is the first option instead of all the values. Since the variable's label and value are hidden, there is no way to select them all.

Same here!

**Comment by kairoslav** [comment]
There is a checkbox for saving variable values by default—I hadn’t noticed it (lol), but it helped.

![Image](https://github.com/user-attachments/assets/b9a04970-9830-4e5b-bb03-736fa93f3251)
