### ISSUE TITLE
Provide "pause" button for alert on the alert configuration tab

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#23676]
**What would you like to be added**:

I would like to be able to pause/unpause an alert from the graph/dashboard itself.

**Why is this needed**:

I have opened a dashboard and saw that we have an alert which is paused. I don't think it should be so I want to unpause it. There is no way to unpause it from the dashboard/graph itself. I need to go to Alerting -> Alert Rules and find it there.

**Comment by marefr** [comment]
Duplicate of #12419
