### ISSUE TITLE
Issue #525 dosn't seem to work any more with influxdb 0.9.*

### ISSUE THREAD

**Issue by timgriffiths** [grafana/grafana#2367]
Currently grafana does a pretty good job of working out the ledged and creates names like value.count {tagname: tagvalue}, I would just like to override it and get it to display tagvalue

So maybe i have missed a ticket or some documentation but can i access tagvalue and put it as a variable inside Alias pattern field

**Comment by torkelo** [comment]
What version of Grafana are you using?

**Comment by timgriffiths** [comment]
A nightly build from a week or 2 ago

**Comment by torkelo** [comment]
then you can provide $tag_tagname  in the alias field to do just that

**Comment by torkelo** [comment]
where tagname is the actual tagname :)

**Comment by timgriffiths** [comment]
Legend thank you
