### ISSUE TITLE
Log scale on y-axis hides 0 values

### ISSUE THREAD

**Issue by feliksik** [grafana/grafana#23674]
**What happened**: I enabled the log10 scale on a y-axis. 

**What you expected to happen**:
0 values would still be visible, just like in linear scale: 

![image](https://user-images.githubusercontent.com/8527652/79671542-26f29e00-81cb-11ea-83b1-e6abb3e51ef0.png)

**How to reproduce it (as minimally and precisely as possible)**:
Graph a metric that has some continuous 0 values, and enable log scale; not the log scale is the only difference with the image above: 

![image](https://user-images.githubusercontent.com/8527652/79671559-51445b80-81cb-11ea-9079-7b9af0d33cfd.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.1.2 (de8f6ac)
- Data source type & version: prometheus 
- OS Grafana is installed on: Linux
- User OS & Browser: MacOSX, Chrome
- Grafana plugins:
- Others:

**Comment by feliksik** [comment]
With `log (base 2)` it does draw it correctly, like in linear.

**Comment by jgehrcke** [comment]
Also see https://github.com/grafana/grafana/issues/24086 (duplicated opened by me) where I try to suggest how to address this.

**Comment by dprokop** [comment]
@feliksik can you try out the new Time series panel? In the meantime I'm gonna close this one as graph panel is no longer supported in favor of Time series panel.

**Comment by shmyer** [comment]
Sorry for reopening, but this issue still persists with the Time series panel. I am on Grafana v8.2.3 (fb85ed6912).
As mentioned by @feliksik, the zero is displayed in linear mode but is hidden in logarithmic mode:
![image](https://user-images.githubusercontent.com/13769889/149553709-2573ad87-8f35-44e7-8d38-e31854dc4063.png)

**Comment by shmyer** [comment]
Sure, I am aware of that. But wouldn't it be possible to apply the log scale only to values above zero and keep zero values as they are?

**Comment by leeoniya** [comment]
> and keep zero values as they are?

they aren't anywhere until you draw them somewhere. so where would you draw them?

please make an image of how you imagine this would look on a log graph.

**Comment by karlstav** [comment]
just stumbled upon this issue myself, the solution as mentioned in the duplicate thread is to add an option to enable [symlog](https://mathworks.com/matlabcentral/fileexchange/57902-symlog).

Then you can set a range (like 0-1) to be plottet lienarly.

The implementation might be out of scope of this aplication, but it would be very nice.

like in this graph when the value drops to 0 the line dissapears:
![bilde](https://user-images.githubusercontent.com/6968928/187151438-cbe60631-1258-47b1-bc9d-a80a10d9d585.png)

but it would not be a problem if 0 to 1 was drawn linearly:
![bilde](https://user-images.githubusercontent.com/6968928/187152735-f8fe7646-6750-47f3-8f68-64a76ff59acf.png)

**Comment by leeoniya** [comment]
see also https://github.com/grafana/grafana/issues/7627#issuecomment-778713077
