### ISSUE TITLE
Prometheus: Metrics picker not working in dashboard panel edit

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23684]
The metrics picker is unresponsive (nothing happens) when used from the dashboard edit mode

**Comment by aocenas** [comment]
@torkelo This seems like an issue in the ButtonCascader styles with z-index being too low:

![Screenshot from 2020-04-20 09-56-25](https://user-images.githubusercontent.com/1014802/79727871-5b5e7b00-82ed-11ea-987e-ca9b4e817dcd.png)

![Screenshot from 2020-04-20 09-56-35](https://user-images.githubusercontent.com/1014802/79727875-5c8fa800-82ed-11ea-9637-205720d86602.png)

Easy to change it to 10000 but seems a bit high, shouldn't it be changed on the panel edit?

**Comment by torkelo** [comment]
Ah, thansk for figuring that out. Yea the cascader dropdown has the wrong z-index,, should use theme.zIndex.dropdown
