### ISSUE TITLE
Traffic light signal does not work with grafana image renderer plugin

### ISSUE THREAD

**Issue by srihari906** [grafana/grafana#23689]
**What happened**:
Grafana Image Renderer, Rendering failed when rendering Traffic light panel.
I am getting following error message.
`{"ignoresHttpsErrors":false,"args":["--no-sandbox"],"dumpio":false,"verboseLogging":false,"level":"info","message":"Browser initiated"}
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
{"msg":"Failed to load resource: the server responded with a status of 403 (Forbidden)","url":"http://localhost:3000/api/datasources/proxy/2/tasQuery","level":"error","message":"Browser console error"}
{"url":"/render?domain=localhost&encoding=&height=500&renderKey=rKaZ17sFy3PUom2syFYc05Xh4RBL27u4%3FImpersonate%3D%23&timeout=60&timezone=Asia%2FCalcutta&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F2i6zXkqZk%2Fnew-dashboard-copy%3Ftab%3Dvisualization%26orgId%3D2%26panelId%3D2%26from%3D1584776486007%26to%3D1587368486008%26width%3D1000%26height%3D500%26tz%3DAsia%252FCalcutta%26render%3D1&width=1000","stack":"TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (C:\\Users\\username\\go\\github.com\\grafana\\grafana\\grafana-image-renderer\\node_modules\\puppeteer\\lib\\DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (C:\\Users\\username\\go\\github.com\\grafana\\grafana\\grafana-image-renderer\\node_modules\\puppeteer\\lib\\DOMWorld.js:454:12)\n    at Frame.waitForFunction (C:\\Users\\username\\go\\github.com\\grafana\\grafana\\grafana-image-renderer\\node_modules\\puppeteer\\lib\\FrameManager.js:657:28)\n    at Page.waitForFunction (C:\\Users\\username\\go\\github.com\\grafana\\grafana\\grafana-image-renderer\\node_modules\\puppeteer\\lib\\Page.js:1144:29)\n    at Browser.<anonymous> (C:\\Users\\username\\go\\github.com\\grafana\\grafana\\grafana-image-renderer\\build\\browser\\browser.js:131:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\username\\go\\github.com\\grafana\\grafana\\grafana-image-renderer\\build\\browser\\browser.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}`

**What you expected to happen**:
No Error, it should be render an image of Traffic light panel.

**How to reproduce it (as minimally and precisely as possible)**:
- Run the grafana in local environment - http://localhost:3000
- Run the grafana-image-renderer server with - node build/app.js server --port=8081
- Create a dashboard panel with traffic light plugin.
- Click on Share menu in Panel Edit popup.
- It will open a Share Panel popup window with an option "Direct link rendered image".
- Once click on this link it will open a new window with rendered image. it is working for other visualization plugins(Graph, Stat, Guage, Polystat, Worldmap, etc..) except traffic light plugin.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Elasticsearch & Latest Version
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Chrome
- Grafana plugins: Traffic Light Plugin
https://grafana.com/grafana/plugins/snuids-trafficlights-panel
- Others:

**Comment by srihari906** [comment]
**For better understand, please check the following screenshots**

<img width="960" alt="traffic-light-panel" src="https://user-images.githubusercontent.com/15091144/79729700-6e814300-830d-11ea-86ca-14559c3453e1.PNG">
<img width="960" alt="traffic-light-share" src="https://user-images.githubusercontent.com/15091144/79729734-77721480-830d-11ea-8abc-3072f9e6f661.PNG">
<img width="960" alt="traffic-light-direct-link" src="https://user-images.githubusercontent.com/15091144/79729751-7d67f580-830d-11ea-952d-43fb535b96c5.PNG">
<img width="960" alt="traffic-light-render-failed" src="https://user-images.githubusercontent.com/15091144/79729770-80fb7c80-830d-11ea-8b98-3c47f739e4ae.PNG">

**Comment by torkelo** [comment]
Could be an issue that this panel is not called the function to signal rendering is complete. Can you open an issue in this plugin’s repo ?

**Comment by marefr** [comment]
Please open an issue in plugin repository: https://github.com/snuids/trafficlights-panel

**Comment by srihari906** [comment]
> Could be an issue that this panel is not called the function to signal rendering is complete. Can you open an issue in this plugin’s repo ?

Sure, Thank you for your replay @torkelo

**Comment by srihari906** [comment]
> Please open an issue in plugin repository: https://github.com/snuids/trafficlights-panel

Sure, Thank You @marefr
