### ISSUE TITLE
TypeError: e.current is undefined

### ISSUE THREAD

**Issue by chench00** [grafana/grafana#23682]
**What happened**:
Error when changing variable and scrolling down the page.

         An unexpected error happened
            details
            TypeError: e.current is undefined
                in t
                in p
                in div
                in t
                in div
                in t
                in div
                in t
                in p
                in div
                in o
                in DraggableCore
                in t
                in div
                in ReactGridLayout
                in Unknown
                in SizeMeReferenceWrapper
                in SizeMeRenderer(Component)
                in SizeMe(Component)
                in t
                in div

**What you expected to happen**:
No error
**How to reproduce it (as minimally and precisely as possible)**:
Change a variable and try and scroll down the page.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Influx + Latest
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox, Chrome and Safari (All latest)
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Can you reproduce this on any dashboard at https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 ?

If not, please include your dashboard json model.

**Comment by chench00** [comment]
>Can you reproduce this on any dashboard at https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 ?

I can reproduce it on play.grafana.org only if I change the variable and try to delete/edit a graph. Here's a video of it happening:

[Error](https://imgur.com/541qXSy)

Notice that after changing the variable, the edit button also doesn't work. 

I can only reproduce what happens in my dashboard if I resize the page almost as if in mobile view. 

[Error (mobile)](https://imgur.com/YdtSIhr)

Hope that helps.

**Comment by friesennerd** [comment]
We have the same problem when changing variables and scrolling down the page.

> Can you reproduce this on any dashboard at https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 ?
> 
> If not, please include your dashboard json model.

I found another way. 

- Use the dashboard InfluxDB Server Monitoring
- Remove host 10.1.100.1
- Add adhoc datacenter
- Remove adhoc datacenter

**Comment by marefr** [comment]
@chench00 thanks, those are useful

**Comment by mckn** [comment]
Fixed in #23580
