### ISSUE TITLE
e is undefined

### ISSUE THREAD

**Issue by lovasoa** [grafana/grafana#23698]
**How to reproduce it (as minimally and precisely as possible)**:
Create an influxdb source with basic auth, providing the wrong BasicAuth credentials.

**What happened**:

`e is undefined` appears

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/552629/79745345-6246b700-8308-11ea-90b6-b73187329d0b.png">

**What you expected to happen**:
Maybe `Invvalid BasicAuth credentials` or another similar error message.

**Environment**:
- Grafana version: Grafana v6.1.4 (fef1733)
- Data source type & version: InfluxDB

**Comment by marefr** [comment]
Please try the latest stable version of Grafana and report back outcome.

**Comment by lovasoa** [comment]
Unfortunately the error occurs on a server on which I cannot update grafana.

**Comment by marefr** [comment]
Would recommend [community site](https://community.grafana.com/) then.
