### ISSUE TITLE
sumseries() inconsistent results

### ISSUE THREAD

**Issue by LunaticZorr** [grafana/grafana#23699]
**What happened**: Trying to get a panel to show the SUM of multiple values/metrics. But the panel keeps updating and showing inconsistent values. If I expect "3", it shows 3 for a while, then goes to "0", "1", "0", "3" again sometimes and so on.

(this is one panel, but I'm having the same issue with all panels using `sumseries()`)

See most right panel on below image:

![buffered_all](https://user-images.githubusercontent.com/19307263/79746566-1a249600-8302-11ea-9480-68fd1daa3e99.JPG)

**What you expected to happen**: The panle should always show a consisent SUM of the values.

**How to reproduce it (as minimally and precisely as possible)**:

Visualization settings:

![buffering_total_query](https://user-images.githubusercontent.com/19307263/79746949-bea6d800-8302-11ea-8a46-d6fe11863ae5.JPG)

Query:

![buffering_stat_visualization](https://user-images.githubusercontent.com/19307263/79746959-c2d2f580-8302-11ea-8af1-315bf289f975.JPG)

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 6.7.2
- Data source type & version: Zabbix (Grafana-Zabbix 3.11)
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10 - Google Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Please open an issue in the zabbix plugin repository https://github.com/alexanderzobnin/grafana-zabbix

**Comment by LunaticZorr** [comment]
> 
> 
> Please open an issue in the zabbix plugin repository https://github.com/alexanderzobnin/grafana-zabbix

Thanks! I've done that :)
