### ISSUE TITLE
Grafana v6.7.2 Explore Function with Zabbix Plugin 3.11.0 Not Working

### ISSUE THREAD

**Issue by lizhisen** [grafana/grafana#23690]
Version: Grafana v6.7.2 with Zabbix Plugin 3.11.0
Zabbix: 4.4.0

Everything works fine (dashboard with zabbix data), but Explore function to query zabbix Metrics is not working.

In chrome，it didn't send "history.get" request, only  "trigger.get" request is sent with following:
request:
{"jsonrpc":"2.0","method":"trigger.get","params":{"output":"extend","itemids":["42155"],"expandDescription":true,"expandData":true,"expandComment":true,"monitored":true,"skipDependent":true,"selectLastEvent":"extend"},"id":1,"auth":"65bd1e2f5073696dfd4d0f1e7fdf2f29"}

respond:
{"jsonrpc":"2.0","result":[],"id":1}

In firefox，both  "history.get" and "trigger.get" request will be found but no graph or tables shows。

Not sure whether this is the key point to this question.

**Comment by marefr** [comment]
Please open issue in zabbix plugin repository https://github.com/alexanderzobnin/grafana-zabbix

**Comment by lizhisen** [comment]
thanks
