### ISSUE TITLE
Variable template cannot be used in another variable with Prometheus as datasource

### ISSUE THREAD

**Issue by Ducatel** [grafana/grafana#2369]
Hi all,
It's impossible to use a variable template inside another variable with Prometheus as datasource.
In use the docker image [luzifer/grafana-prometheus](https://registry.hub.docker.com/u/luzifer/grafana-prometheus/).

So my first variable is
![2015-07-20_11-12-10](https://cloud.githubusercontent.com/assets/1184332/8772890/08b34ed8-2ed0-11e5-80b0-34f739f5854e.png)

And the second 
![2015-07-20_11-13-01](https://cloud.githubusercontent.com/assets/1184332/8772897/2219f660-2ed0-11e5-82af-82c63394c4db.png)

So in the second variable, the variable $host seem not be evaluated.
Do you have any idea about this problem ?

Thanks in advance ;)

**Comment by torkelo** [comment]
This a feature that needs to be enabled in the Prometheus data source plugin (they need to interpolate the metricFind query)

**Comment by Ducatel** [comment]
Ok but how I can enable this feature ?

**Comment by torkelo** [comment]
@Ducatel you need to update the source code for the Prometheus Grafana data source plugin. use the templateSrv.replace function to interpolate the query before issuing it to Prometheus
