### ISSUE TITLE
[Feature Request] No postfix if N/A in singlepanel

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2370]
I'm using singlepanel to display percentage and some of them display N/A because null (this is expexted in the contex) but "N/A%" doesn't make much sense IMHO. Would you consider adding a function to avoid prefix and postfix for null values please?
Thanks.

**Comment by torkelo** [comment]
if you use unit percentage instead of using the postfix this should solve your case

**Comment by rschitz** [comment]
Indeed, thanks.

The only downside is that i can’t change the “%” size now :)
