### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by aurimasplu** [grafana/grafana#23708]
**What happened**:
After upgrade from 6.1.6 to 6.7.2 then clicking around in dashboards (expanding/collapsing rows, changing variables and most common when saving dashboard after changing variable) we are getting error "TypeError: Cannot read property 'value' of undefined"
Strange thing: even we get the error dashboard is saved successfully. 
![image](https://user-images.githubusercontent.com/33485896/79768768-e498a080-8333-11ea-848f-1b595de8a3c7.png)

**What you expected to happen**:
No error
**How to reproduce it (as minimally and precisely as possible)**:
Save dashboard with changed variables
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Elasticsearch 6.8
- OS Grafana is installed on: RHEL 7.7
- User OS & Browser: Win 10; Chrome and Firefox.
- Grafana plugins: Table, Graph ... (default Grafana plugins)
- Others:

**Comment by aurimasplu** [comment]
When changing variable I already this error in background:
![image](https://user-images.githubusercontent.com/33485896/79770034-88368080-8335-11ea-884f-88060dc03197.png)



And after saving I get:
![image](https://user-images.githubusercontent.com/33485896/79770242-d186d000-8335-11ea-8a18-f12926973d82.png)

**Comment by arnedc** [comment]
I'm seeing the same issue with Grafana 6.7.2 with a Prometheus data source 
Environment:

Grafana version: 6.7.2
Data source type & version: Prometheus 2.15.2
OS Grafana is installed on: Ubuntu 18.04
User OS & Browser: Win 10; Chrome
Grafana plugins: Table, Graph ... (default Grafana plugins)
Others:

**Comment by mckn** [comment]
Related to: https://github.com/grafana/grafana/issues/23682

**Comment by mckn** [comment]
Fixed in #23580
