### ISSUE TITLE
Loki Metrics Explore showing wrong stream labels.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#23719]
**What happened**:
When doing metrics queries with Loki in explore. Series names are incorrect showing `status_code` instead of the actual series names.

see below

![image](https://user-images.githubusercontent.com/1053421/79788533-ca03fe80-8316-11ea-8a97-1ede72f9151f.png)

**What you expected to happen**:

Render the actual series names/labels.

**How to reproduce it (as minimally and precisely as possible)**:

Run a query like this `sum(count_over_time({namespace="default"}[5m])) by (job)`

**Anything else we need to know?**:

Yes it works on master, but not on 6.7.

**Environment**:
- Grafana version: 6.7
- Data source type & version: Loki

**Comment by aocenas** [comment]
This should be happening only when you jump from dashboard to explore because legend formatter is preserved in the url link in query target.

**Comment by aocenas** [comment]
Needs to be checked if it is still happening.

**Comment by ivanahuckova** [comment]
I have tested this out and it seems like it is working for both - for just explore and also for explore when jumped from dashboard. 
![Kapture 2020-06-21 at 15 24 42](https://user-images.githubusercontent.com/30407135/85225877-73797600-b3d4-11ea-84cf-76f2733f8164.gif)
