### ISSUE TITLE
Can't scroll when template editor is open

### ISSUE THREAD

**Issue by dhain** [grafana/grafana#2371]
When editing template variables, the dialog is taller than my screen. I can't scroll down to the fields off the page. The only way I can edit them is by hitting tab to focus the next field on the form. Attached a screenshot to show what I mean.

![screen shot 2015-07-20 at 11 03 33 am](https://cloud.githubusercontent.com/assets/51937/8780556/55a5bfec-2ecf-11e5-868c-16a389fcb750.png)

This is with 2.1.0-pre1 built on 7/18.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master
