### ISSUE TITLE
Option for un-converted seconds for Gauges 

### ISSUE THREAD

**Issue by BaconCatBug** [grafana/grafana#23712]
**What would you like to be added**: I want a gauge that is in seconds that does not get converted into minutes or hours.

**Why is this needed**: Because I want to see the value of 90 seconds as 90 seconds and not as 1.5 minutes.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/8781 left some instructions in that issue as well for how to fix it if your up for writing your own PR
