### ISSUE TITLE
Expand template variables in alert rule tags

### ISSUE THREAD

**Issue by jstaffans** [grafana/grafana#23728]
**What would you like to be added**:

Since https://github.com/grafana/grafana/pull/10989 it's possible to add tags to alerts sent via Prometheus Alertmanager. As the values for those tags may be repeated across multiple panels, it would make sense to manage them as template variables instead, which would get expanded if used as a tag value: 

<img width="602" alt="Screenshot 2020-04-21 at 10 27 52" src="https://user-images.githubusercontent.com/1368965/79837873-c9bd3f00-83ba-11ea-80a9-1b603d33c0ed.png">

**Why is this needed**:

To reduce maintenance burden of alert rule tags that are supposed to be the same across multiple panels.

**Comment by torkelo** [comment]
We cannot support variables in alert tags, they are evaluated outside the dashboard / variable context

**Comment by jstaffans** [comment]
@torkelo, I see what you mean. But would it perhaps be possible to implement as a new type of template variable, something like an "Alert tag constant"? It could work the same way a constant does, but be backed by the same store that persists the alert tags.

I'm just looking for a way to reduce duplication, not to evaluate complicated template variables.
