### ISSUE TITLE
Tables without primary key

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#23724]
**What happened**:

There are tables without primary key.

```
| grafana                  | access                                     |
| grafana                  | alert_rule_tag                             |
| grafana                  | annotation_tag 
```

In a cluster environment (such as percona Xdb Cluster) using Galera replication it is STRONGLY advised as replication may get screwed up without it (more so on deletes)
https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html#tables-without-the-primary-key

With the default mode of Enforcing while the table is created no data can be inserted into the table.

**Workaround**:

I just modified the table and added a auto incrementing key to the tables 

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
We do not have a table named `access`

**Comment by marefr** [comment]
Duplicate of #12971
