### ISSUE TITLE
Should be able to use regex operator in InfluxDB 0.9 query editor

### ISSUE THREAD

**Issue by dhain** [grafana/grafana#2374]
As far as I can tell, the only way to get multiple-value selection with templates and InfluxDB 0.9 is using regex. Unfortunately, there is no way to use regex values in WHERE clasues in the query editor. It works ok if I manually specify the query.

![screen shot 2015-07-20 at 11 49 20 am](https://cloud.githubusercontent.com/assets/51937/8781605/abe8aa30-2ed5-11e5-812b-98882dc12cba.png)

![screen shot 2015-07-20 at 11 46 42 am](https://cloud.githubusercontent.com/assets/51937/8781607/b0af161c-2ed5-11e5-9620-fb09bb6004e2.png)

Edit: I am using 2.1.0-pre1 built on 7/18

**Comment by tmonk42** [comment]
if you type in /$mountpoint/ in the value field, the operator will change to =~

**Comment by dhain** [comment]
Ah, so it does. Thanks @tmonk42 ! Is this documented somewhere?

**Comment by torkelo** [comment]
@dhain http://docs.grafana.org/v2.1/datasources/influxdb/#regex-matching
