### ISSUE TITLE
Escaping dots in dots-delimitied InfluxDB measurement names in annotation query

### ISSUE THREAD

**Issue by echernyshev** [grafana/grafana#23748]
When I create query in annotation like
`SELECT error FROM "$rp_metric"."$metric" WHERE "type"='error' AND $timeFilter`
where **metric** - variable with dot-delimited measurement name like **total.confirmed** 

I get an error:
`InfluxDB Error: error parsing query: found \\., expected identifier at line 1, char 37`
because the query is rendered in:
`SELECT error FROM "INFINITE"."total\.confirmed" WHERE "type"='error' AND time >= now() - 6h`

The error occurs because the dot "." was escaped in "\\.".

When I create a similar query in the graph settings block, everything works fine, dot is not escaped. Problem in annotation settings.

**Environment**:
- Grafana version: v6.0.0
- Data source type & version: InfluxDB 1.7.4
- User OS & Browser: Ubuntu 18.04

**Comment by marefr** [comment]
Seems to work on v6.7.2, https://play.grafana.org/d/6JS0fU3Wz/issue-23748-influxdb-annotations?orgId=1. Would suggest upgrade.

You could maybe try `SELECT error FROM "${rp_metric:raw}"."${metric:raw}" WHERE "type"='error' AND $timeFilter` if that makes any difference on v6.0.0.
