### ISSUE TITLE
Derivative operation on influxdb 0.9 crashes InfluxDB server

### ISSUE THREAD

**Issue by j-rock** [grafana/grafana#2375]
I'm running InfluxDB 0.9.1 and Grafana v 2.1.0-pre1-amd64. I created a dashboard with an InfluxDB 0.9 datasource. When I selected derivative(value) as my select statement, my InfluxDB crashed. Now the data is corrupted. Any ideas what's going on here?

**Comment by torkelo** [comment]
not sure, maybe open an issue in the influxdb project, specify the exact query that Grafana sends that is Crashing InfluxDB. I have also experienced some crashes with InfluxDB 0.9, will test derivative function and see if that also makes it crash

**Comment by j-rock** [comment]
I'll get back to it in a bit. For now, it was something to do with not getting an expected an int64/float64. Horrible log spew gist: https://gist.github.com/j-rock/e37ff4c655ce923de7a6

**Comment by torkelo** [comment]
well make sure youlet the influxdb project know about it (and search before to make sure there is no issue already for it)
