### ISSUE TITLE
Define auto-provisioned admin user org id

### ISSUE THREAD

**Issue by tomashejatko** [grafana/grafana#23758]
**What would you like to be added**:
Hi, I would like to let Grafana create admin user with different orgId then I will set as `users.auto_assign_org_id`.

**Why is this needed**:

First, please let me introduce you flow I want to achieve : 

- I will install Grafana via Helm chart ( terrafrom Helm provider) https://github.com/helm/charts/tree/master/stable/grafana
- I will use parameters [adminUser](https://github.com/helm/charts/blob/cfcf87ac254dcbb2d4aa1c866e20dd7e8e55b8e5/stable/grafana/values.yaml#L234) and [adminPassword](https://github.com/helm/charts/blob/cfcf87ac254dcbb2d4aa1c866e20dd7e8e55b8e5/stable/grafana/values.yaml#L235), which then translates to [Kubernetes secret](https://github.com/helm/charts/blob/cfcf87ac254dcbb2d4aa1c866e20dd7e8e55b8e5/stable/grafana/templates/secret.yaml#L1) and then finally gets translated env vars [GF_SECURITY_ADMIN_USER](https://github.com/helm/charts/blob/cfcf87ac254dcbb2d4aa1c866e20dd7e8e55b8e5/stable/grafana/templates/_pod.tpl#L225) and  [GF_SECURITY_ADMIN_PASSWORD](https://github.com/helm/charts/blob/cfcf87ac254dcbb2d4aa1c866e20dd7e8e55b8e5/stable/grafana/templates/_pod.tpl#L232) passed to container.
- I have [auth.google] set up so everyone from company can use Grafana
- I set up `auto_assign_org: true`, `auto_assign_org_id: 2`, `auto_assign_org_role: Viewer`
- I create new organization with https://www.terraform.io/docs/providers/grafana/r/organization.html - I can define our devops team or any other privileged users here as admins and let others fallback to `auto_assign_org_role` setting.

Here is my config : 
```
[analytics]
check_for_updates = true
[auth]
disable_login_form = true
[auth.google]
allow_sign_up = true
allowed_domains = ackee.cz
auth_url = https://accounts.google.com/o/oauth2/auth
client_id = xxx
client_secret = xxx
enabled = true
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
token_url = https://accounts.google.com/o/oauth2/token
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
root_url = https://redacted.url
[users]
auto_assign_org = true
auto_assign_org_id = 2
auto_assign_org_role = Viewer
```
Actually last lines are edited, because in this setup Grafana will not start with this error : 
```
t=2020-04-21T21:06:51+0000 lvl=info msg="Could not create user: organization id %v does not exist" logger=sqlstore LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
t=2020-04-21T21:06:51+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Failed to create admin user: Could not create user: organization id 2 does not exist"
```

If I can override orgId for admin user creation and this will succeed, than all new users will be created in my Terraform provisioned organization with orgId=2.
Or should admin user creation be harcoded with orgId=1 ? Because there is AFAIK no way to create organization before this very first user is created.

Thanks for feedback!

**Comment by jsoref** [comment]
fwiw, #26785 fixed the error reporting.

**Comment by alexanderzobnin** [comment]
@tomashejatko is this still an issue?
