### ISSUE TITLE
ButtonCascader has a bit of a lag after selection

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#23756]
When I make a selection from the cascader menu, it takes a few seconds before the onChange is triggered. Should look into what is causing this.

**Comment by marefr** [comment]
Please add labels to issue. Are you looking into this or expecting someone else to do it? If someone else, please let me know and I try to delegate it to team. Any screenshots/animated gif showing the problem.

**Comment by shavonn** [comment]
> Please add labels to issue. Are you looking into this or expecting someone else to do it? If someone else, please let me know and I try to delegate it to team. Any screenshots/animated gif showing the problem.

@marefr I discussed it with @tskarhed and he said hopefully it would make it into 7 but didn't indicate who or how.

**Comment by torkelo** [comment]
Never seren this, sounds very strange. Don’t get this when I use it

**Comment by hugohaggmark** [comment]
@tskarhed were you able to repro this one, otherwise I think we should close this.

**Comment by tskarhed** [comment]
I'm not able to reproduce it. @shavonn do you have an example on how to reproduce or a short video?

**Comment by hugohaggmark** [comment]
Closing this for now, if @shavonn can add a video or repro steps we could opened this again.
