### ISSUE TITLE
DataFrame & Visualizations support Field labels better / differently 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23769]
Currently toDataFrame sets the field name to the series name instead of keeping the field name `Value`. 

Graphite & Prometheus already generates a series name based on the metric name and series name. this is then transformed using toDataFrame to a DataFrame. In this transform, we are using the series name as the field name for the value. So this is a big problem for the labels to fields transformer as we end up with this: 

![Screenshot from 2020-04-22 09-04-45](https://user-images.githubusercontent.com/10999/79951105-6265c480-8478-11ea-8880-111d9a6f9ee9.png)

@ryantxu, as you mentioned, think we need to rethink a bit how we use labels and how we set field names.

**Comment by dprokop** [comment]
@torkelo can we close this now after https://github.com/grafana/grafana/pull/23828?
