### ISSUE TITLE
UI: sanitizing input values from possibility to inject scripts, markup etc.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#23776]
**What would you like to be added**:
It would be good to add the behavior that the input/textarea etc. values are sanitized as default but that this can be disabled by passing a prop.

**Why is this needed**:
To prevent missing checking input values for potential dangerous values.

**Comment by torkelo** [comment]
Not sure I understand this. 

We should not store sanitize values. React will do this automatically when rendering html. Need to only sanitize URLs in React.

**Comment by mckn** [comment]
Hehe, valid point! Didn't think of that 🙈

But we are not using/rendering any of the input values outside of react?
