### ISSUE TITLE
Unnecessary scroll shows on graph

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#23795]
**What happened**:

Since 6.5. or later verison I have observed that an "extra" (unnecessary) scroll shows on the graphs

**What you expected to happen**:

If there is no need for scroll I would expect now scroll to show. In my example it's only 1 row which should show and it shows fine. However scrolls also show and you can "scroll up" and "scroll down".

**How to reproduce it (as minimally and precisely as possible)**:

Chrome:
![image](https://user-images.githubusercontent.com/8693064/80012853-05512980-84df-11ea-912c-a950d2610f74.png)

Safari:
![image](https://user-images.githubusercontent.com/8693064/80013393-dc7d6400-84df-11ea-948f-9c574853fdbd.png)

It's a very simple dashboard:

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "cacheTimeout": null,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 5,
        "w": 3,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "max": false,
        "min": false,
        "rightSide": false,
        "show": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "paceLength": 10,
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refCount": 0,
          "refId": "A",
          "target": "stats.gauges.ntpreceiver.offset",
          "textEditor": false
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel 1",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "s",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "New dashboard",
  "uid": null,
  "variables": {
    "list": []
  },
  "version": 0
}
```

**Anything else we need to know?**:

The datasource doesn't really make any difference

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Graphite
- OS Grafana is installed on: Docker
- User OS & Browser: 
 * Chrome Version 81.0.4044.113 (Official Build) (64-bit)
 * Safari Version 13.1 (15609.1.20.111.8)
- Grafana plugins: none
- Others: none

**Comment by marefr** [comment]
Tried to reproduce [here](https://play.grafana.org/d/huw3x83Wk/issue-23795-legend-scrollbar?orgId=1) on v6.7.2. I see scrollbar on the first panel using same width and height as you, but that's because the series alias name can't fit into the space. 

Looking at the second panel I can see the scrollbar. Third panel I see no scrollbar. Seems to be related to when height is less than 6.

**Comment by nikobearrr** [comment]
Hi @marefr 

It's good that you can reproduce the issue. I opened the link on the grafana playground and when I try to edit the 1st and 2nd graphs (the one with lower height) I can also see the scrollbar:

![image](https://user-images.githubusercontent.com/8693064/80202575-e5cd1480-8636-11ea-9c7f-e4a7a9a5c12e.png)

This is on Google Chrome and my resolution is 4K
