### ISSUE TITLE
Variable datasources don't update for mixed datasource panels

### ISSUE THREAD

**Issue by Quarry77** [grafana/grafana#23799]
**What happened**:
I selected a Graphite datasource variable as the query datasource for a mixed datasource panel. Then I changed the variable but the query still says it's using the previous value as the datasource. If I leave the panel editor and return, it updates to the new value.

![image](https://user-images.githubusercontent.com/2530742/80024935-a9fa4980-8494-11ea-8bc6-032748674299.png) 
![image](https://user-images.githubusercontent.com/2530742/80024969-bed6dd00-8494-11ea-83a0-cbc7835f3487.png)

**What you expected to happen**:
The query should list either the variable as its datasource or update correctly when the variable changes.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a graphite datasource variable with at least 2 options
- Create a panel with the datasource set to -- MIXED --
- Add a query using the variable as the datasource
- Change the variable

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.5 but I tested v6.7.1 as well
- Data source type & version: Graphite 1.1.0-dev
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None
- Others:

**Comment by marefr** [comment]
Works as expected on v6.7.2, https://play.grafana.org/d/K6ZDL8qZz/issue-23799-ds-query-mixed?orgId=1. Please upgrade.

**Comment by Quarry77** [comment]
That link shows the same problem. To be clear, the data still works and changes but the label is wrong. 

If I click your link and edit the panel, the $ds is gdev-testdata and the label next to A says (gdev-testdata).

If I switch $ds to Grafana TestData, the data changes for A but the label still says (gdev-testdata) which is incorrect. If you leave the panel and come back it will update.

**Comment by marefr** [comment]
Thanks. So this is a minor UI glitch during edit of a panel.

**Comment by Quarry77** [comment]
Correct

**Comment by hugohaggmark** [comment]
Confirmed this is still an issue in Grafana v7.3.2 (b8ad4eaab3).

**Comment by frdve** [comment]
It looks related, but in my case, the mixed datasource with variable datasources doesn't work at all.

**What happened:**

I have a variable datasource '$cloud' for Azure Data Explorer to select the correct environment and want to enrich this with data from another datasource (JSON API).  
![afbeelding](https://user-images.githubusercontent.com/66672043/102975616-a4ac3d80-4500-11eb-93dc-4d5961d15f56.png)
The $cloud variable datasource is parsed correcly in the title of the query field, but for the execution, it gives an error that $cloud is not found.  Also, related to this issue, it is not updated when I change the variable field.

**What you expected to happen:**

The datasource variable should be used by the query

**How to reproduce it (as minimally and precisely as possible):**

    Create a Azure Data Explorer datasource variable with at least 2 options
    Create a panel with the datasource set to -- MIXED --
    Add a query using the variable as the datasource
    Change the variable

**Anything else we need to know?:**

**Environment:**

    Grafana version: Grafana v7.3.6 (ea06633c34)
    Data source type & version: Azure Data Explorer Datasource
    OS Grafana is installed on: Linux
    User OS & Browser: Windows 10, Firefox
    Grafana plugins: Azure Data Explorer Datasource
    Others:
