### ISSUE TITLE
ImageRenderer: New setting to control concurrent api render limit

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23806]
The max concurrent render api calls is currently caped at 30, hardcoded: 

https://github.com/grafana/grafana/blob/master/pkg/api/render.go#L55 

Would be good to add a setting under image renderer plugin section: 
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L697

For concurrent_api_render_limit ? or something like that

**Comment by bergquist** [comment]
Do we really need a setting for this? Sooooooo many settings.
