### ISSUE TITLE
HTTP API Documentation

### ISSUE THREAD

**Issue by samhatchett** [grafana/grafana#2382]
This issue should probably just reopen #1822 - the API docs are not complete with regard to getting/setting data sources, users, orgs, etc. Are these features supported currently through API?

**Comment by torkelo** [comment]
Here are latest 
http://docs.grafana.org/v2.1/reference/http_api/

There are even some new updates here that have not been published
https://github.com/grafana/grafana/blob/master/docs/sources/reference/http_api.md
