### ISSUE TITLE
Migration button for old to new Table panel

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23822]
Todo:

* [ ] Add migration button to old table editor 

Reference:
Singlstat editor
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/editor.html#L9
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L143

Old table edtor: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/editor.html

Add a function to the old table angular controller that calls   this.onPluginTypeChange('table');

Add migration logic here: 
https://github.com/grafana/grafana/blob/c4d91e25966ee39213c7ed7cf06cdc263757b511/public/app/plugins/panel/table/migrations.ts#L29 

Use this old devenv test dashboard to test migration: 
http://localhost:3000/d/pttable/panel-tests-table?orgId=1 

There are a lot of tricky changes between old and new table panel. For example old panel had built-in transformations. Transformations are now an external core feature not linked to a specific panel. 

Old table transforms to new transform feature mapping
* Time series to columns => Outer join transform (but id is seriesToColumns) 

```json
"transformations": [
    {
      "id": "seriesToColumns",
      "options": {}
    }
  ]
```

* Series to rows 
```json
"transformations": [
    {
      "id": "seriesToRows",
      "options": {}
    }
  ],
```

the old table panel.columns should be mapped to new override rule system.

Similar to how this migration https://github.com/grafana/grafana/pull/29599/files added migration from seriesOverrides (in old graph) to new override rules.

**Comment by marefr** [comment]
@dprokop would like some labels here :)

**Comment by dprokop** [comment]
@marefr that's what happens when you create issues ad-hoc ;)
