### ISSUE TITLE
Update devenv blocks without a version to the latest version

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#23847]
**What would you like to be added**:

Currently the `graphite` and `prometheus` devenv blocks refer to outdated version of the software. It would make more sense for those blocks to refer to the latest version.

We have these blocks:
- prometheus (1.8.2)
- prometheus2 (2.7.2)

I propose we replace them with these
- prometheus (2.7.2)
- promehteus1 (1.8.2)

**Comment by xlson** [comment]
@marefr @bergquist thoughts?

**Comment by marefr** [comment]
Could make sense, depends on what we want to optimize for. Having an actual version set gives no surprise and is "tested to work". Whenever you get a new version when latest tag updates it may break things that aren't super clear why that happened or how to resolve it..

**Comment by xlson** [comment]
@marefr Sorry, I was unclear. We should definitely specify the docker image version explicitly. What I'm talking about is the fact that our docker block `prometheus` refers to `prom/prometheus:v1.8.2` instead of `prom/prometheus:v2.7.2`.

We have these `blocks`:
- prometheus (1.8.2)
- prometheus2 (2.7.2)

I propose we replace them with these
- prometheus (2.7.2)
- promehteus1 (1.8.2)

Same goes for graphite and any other images where the same is true. What I'm saying is that we should make it so that users of our devenv should get the latest version of the software when choosing the block that does not have a version number at the end, instead of the other way around.

**Comment by marefr** [comment]
Oh. Yeah absolutely that makes perfect sense :+1: Maybe want to upgrade to [latest](https://github.com/prometheus/prometheus/releases/tag/v2.17.2) at the same time?

**Comment by bergquist** [comment]
`latest` sounds like a good idea considering its devenv. Might help us catch bugs.

**Comment by xlson** [comment]
I'm a bit torn on using `latest` as that can lead to unnecessary breakage. I do think it's important that we keep updating the blocks, but I don't like them just randomly breaking. I'd rather have a way easily check if they are up-to-date or not. While it's fine for the prometheus block to break all of a sudden when I am using it, I don't think it's fine when someone who hasn't worked with devenv experiences that.

If we really want a latest block I think we should make that excplit, something like `prometheus-latest` that somewhat clearly signals that this is bleeding edge.
