### ISSUE TITLE
Global variable loses value upon dashboard refresh

### ISSUE THREAD

**Issue by jericvizmanos** [grafana/grafana#23841]
**What happened**:
Global variable loses its value after refreshing the dashboard.

**What you expected to happen**:
After refreshing the dashboard, the values should also get passed.

**Before:**
<img width="375" alt="Screen Shot 2020-04-23 at 5 11 24 PM" src="https://user-images.githubusercontent.com/58444570/80161540-84993880-8585-11ea-8ef6-79fc53a86834.png">

**After refreshing the dashboard:**
<img width="270" alt="Screen Shot 2020-04-23 at 5 11 31 PM" src="https://user-images.githubusercontent.com/58444570/80161544-8c58dd00-8585-11ea-82f6-e738493c82d8.png">

**How to reproduce it (as minimally and precisely as possible)**:
1. Disable HTML sanitization
2. Create a Dashboard > Choose text as visualization
3. Select HTML and enter "<span style>${__dashboard.name}</span>"
4. Give the dashboard a name so the value gets pulled into the ${__dashboard.name}
5. Refresh the dashboard (upper right of the screen) see that it doesn't pull the value itself and reverts back to "${__dashboard.name}"

Issue is specific to global variables. I tested this out on the dashboard variables and they are working as intended.

**Comment by hugohaggmark** [comment]
@jericvizmanos could you provide the following so our investigation goes smoother:
Environment:
Grafana version:
Data source type & version:
OS Grafana is installed on:
User OS & Browser:
Grafana plugins:
Others:

**Comment by hugohaggmark** [comment]
I took a quick look at this on `master` and it seems global variables like `org` and `dashboard` are cleared every time we call `updateIndex` (when we refresh for instance) in templateSrv here: https://github.com/grafana/grafana/blob/db3f2b90e9254adcc33ba85ba7ed14b9de021fca/public/app/features/templating/template_srv.ts#L78

**Comment by hugohaggmark** [comment]
Related #25359

**Comment by hugohaggmark** [comment]
> Hi @hugohaggmark,
> 
> Sorry to abuse this thread. Just would appreciate a heads-up before going into what will probably be a deep hack to provision a single template of dashboards to Teams (Organizations) and their users.
> 
> Since I did not receive any response to this plea: [#21071 (comment)](https://github.com/grafana/grafana/issues/21071#issuecomment-640908831)
> 
> Is there anything you could suggest that is orthodox in the FOSS Grafana before I cross over to the black magic ;-)
> 
> Many thanks and best wishes,
> Eric

Hi @allomorphy we're looking into providing global/resusable variables for Grafana as first-class citizen. 

I can't say or promise when this work will be done but we've started discussions. As part of the team responsible for migrating the existing variable system to our new platform, my advice to you is that this is one of our most complex areas with lot's of special cases so be patient when entering this magical world :)

All the best

**Comment by allomorphy** [comment]
@hugohaggmark @torkelo 💪 
We would love to help test. ❤️ 
Strangely for a health/wellness non-profit, most of our users are high-flying engineers.

(We will hold off then on our own black magic and look forward to your commits).
