### ISSUE TITLE
documentation issue for postgresql

### ISSUE THREAD

**Issue by doctor-eval** [grafana/grafana#23840]
**What happened**:

[Macro documentation](https://grafana.com/docs/grafana/latest/features/datasources/postgres/#macros) for postgresql is incorrect.

**What you expected to happen**:

Documentation says

    $__timeGroup(dateColumn,‘5m’, 0)

but actual use requires that the interval does not have quotes, i.e.

    $__timeGroup(dateColumn,5m, 0)

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

I haven't tried the other macros but assume it's the same for all of them.

**Environment**:
- Grafana version: grafana/grafana:6.7.2 from docker
- Data source type & version: postgresql as shipped
- OS Grafana is installed on: linux (docker)
- User OS & Browser: safari osx
- Grafana plugins: none
- Others:

**Comment by aknuds1** [comment]
Can you point out where you find this documentation?

**Comment by doctor-eval** [comment]
ARGH sorry - It's here:

https://grafana.com/docs/grafana/latest/features/datasources/postgres/#macros

**Comment by aknuds1** [comment]
@doctor-eval Thanks, will look into it.

**Comment by aknuds1** [comment]
Can you please provide a scenario for reproducing the error you're seeing?

**Comment by doctor-eval** [comment]
Hi, I initially tried to reproduce the problem and couldn't. So I copied and pasted from the documentation... the problem is that the quotes in the HTML are fancy.

So if you copy and paste from the docs it doesn't work, but if you type using programmer-quotes then it works fine with or without quotes..

![image](https://user-images.githubusercontent.com/57946941/80347713-05bb3d00-88b0-11ea-92ca-fb35e61ed14c.png)

**Comment by aknuds1** [comment]
@doctor-eval Gotcha.

**Comment by aknuds1** [comment]
@oddlittlebird Apparently there's a formatting issue in [macro documentation](https://grafana.com/docs/grafana/latest/features/datasources/postgres/#macros), where the examples have the wrong type of quotes: `$__timeGroup(dateColumn,‘5m’)`. Can you look into this?

I tried building docs to see for myself, but `cd docs && make docs` is broken at the moment.
