### ISSUE TITLE
Tooltip series name overflow the values when the name is very long

### ISSUE THREAD

**Issue by dd00f** [grafana/grafana#2385]
When hovering the mouse over a graph, the tooltip shows the series name and the value associated with it.

In my case, the series name can sometimes very long (I graph individual SQL calls, those SQL calls sometimes reach ~500 characters.) When the name is very long, it overflows the tooltip boundaries and bumps the value out of the display.

An easy solution I found was to change the CSS **graph-tooltip-series-name** to add 

max-width: 650px;text-overflow: ellipsis;overflow: hidden;

**Comment by tuxinaut** [comment]
If you suppose you've a solution for that bug. You could also provide a Pull request to accelerate the ticket.

An a nice image from the bug would be also nice :smile: because it's easier to see what you exactly mean.

**Comment by dd00f** [comment]
Here are the pictures before :
![2015-07-23 10_26_09-grafana - jvm dashboard-before](https://cloud.githubusercontent.com/assets/6424071/8852830/7c195956-3125-11e5-8c85-1711aa7e0ceb.png)

And after :
![2015-07-23 10_29_48-grafana - jvm dashboard-after](https://cloud.githubusercontent.com/assets/6424071/8852905/d9517bbc-3125-11e5-8c46-9cc0be765fae.png)

**Comment by TryTryAgain** [comment]
:+1:  for this feature. Also wanted to report adding max-width: 650px;text-overflow: ellipsis;overflow: hidden; in to the graph-tooltip-series-name didn't resolve the issue for me. I'm also seeing it cutoff on the height as well :( I tried different light/dark themes, and made that change in all available css files to no avail.

**Comment by TryTryAgain** [comment]
I take that back, the proposed solution does help fix this...I was missing a ";". Although, I think, for reference, using AliasByNode as seen here: https://github.com/grafana/grafana/issues/464 is the better option, in my opinion.

**Comment by lexx42xxel** [comment]
This still seems to be a problem in bar charts for grafana v 11.1.5 ?
