### ISSUE TITLE
Gauge fuzz

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#23865]
Continuation of [#22507](https://github.com/grafana/grafana/issues/22507)
I have found, that this problem is only in Gauge bar, It looks that the code only places the new number to the top, instead of replacing the current one.
**I would like to help with this, what part of code is responsible for getting the data and drawing it on change?**

**Comment by torkelo** [comment]
An old bug that so far has proved impossible for any on the dev team to replicate: 

Please  add any info on what browser and os and browser plugins you have installed: https://github.com/grafana/grafana/issues/21156

**Comment by radimkohout** [comment]
Grafana version:6.6.0
Data source type & version:Mysql(MariaDB)
OS Grafana is installed on: Linux, Debian 10
User OS & Browser: Windows+Linux, Chrome(adblock, gramally, restman),Firefox(debian), MS Edge
Grafana plugins:Nothing special.
Others:?
