### ISSUE TITLE
option to align 0 between Y-axis

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2386]
Is is possible to add an option to align 0 between Y-axis so it could be possible to have bytes/s and packets/s on the same graph :  https://snapshot.raintank.io/dashboard/snapshot/LOf5532Dx115IdX04XFuAirNM2ZHt4iV
thanks

**Comment by torkelo** [comment]
not currently :(

dupe of https://github.com/grafana/grafana/issues/1271
