### ISSUE TITLE
Question: generic dashboards - how?

### ISSUE THREAD

**Issue by slnowak** [grafana/grafana#2387]
Hi, 

I'm using Influxdb 0.8.x and Grafana 2.1.0-pre1.
I have several metrics named like:
${common-prefix}.host1.${metric1}
${common-prefix}.host2.${metric1}
${common-prefix}.host1.${metric2}
${common-prefix}.host2.${metric2}

So basically, prefix and suffixes are fixed. But hosts are changing dynamically. 
What I need is main dashboard with general statistics for each available host (think of it as ${metric0}).
Also, each 'section' should have link to more detailed dashboard, containing more specific metrics. 
Detailed views have fixed structure.

What's the best way to achieve something like that? I know that there's somethinng like scripted dashboard (http://docs.grafana.org/reference/scripting/) and my detailed view could be done in such way.

But then I've found templated dashboards (http://docs.grafana.org/reference/templating/) and right now, I'm totally confused.

Should I do this using templated or scripted dashboards? Or maybe should I use both approaches?

Thanks,
Slawek

**Comment by torkelo** [comment]
I am not sure, Templating should perhaps solve your case, http://play.grafana.org/dashboard/db/influxdb-templated-queries

Tempating is much in enhanced also in upcoming Grafana 2.1 where you can repeat panels and rows, and there is also dashboard links and singlestat panel links that you can use to link panels to detailed dashboards

**Comment by slnowak** [comment]
Ok, repeating works quite nice, but how can I use passed variable in detailed view?
I will show you what I want to achieve. 
Here's my parent view:
 
![screen shot 2015-07-23 at 10 56 51 am](https://cloud.githubusercontent.com/assets/5739345/8846779/d1570dc4-3129-11e5-8af3-4eed437e9275.png)

And detailed one:
![screen shot 2015-07-23 at 10 58 00 am](https://cloud.githubusercontent.com/assets/5739345/8846788/ddf4b86a-3129-11e5-84b9-61639fd4c396.png)

Now, I would like to access '$queue' variable from parent scope in my 'child' scope but in the way that clicking on link only passes corresponding queue name to child scope. Is it possible with templating? Or maybe should I use scripting for that? Thanks.

**Comment by torkelo** [comment]
It is possible , but you need a queue variable defined in the queue dashboard

**Comment by slnowak** [comment]
Could you provide me some details?
Should I declare it as custom variable in templating options? 
Olso, how to solve the issue with passing multiple queue names?

BTW, thanks for quick response :)
