### ISSUE TITLE
Trace view doesn't render in split view

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#23882]
See video, have to exit split view to get trace to show:

![s7ogUolTSD](https://user-images.githubusercontent.com/444037/80276249-592a6100-86df-11ea-8de1-0a95cfcd3bd2.gif)

Can we not open in split view by default?  I don't find it useful.

**Comment by kaydelaney** [comment]
CC @aocenas

**Comment by aocenas** [comment]
This should be already fixed by https://github.com/grafana/grafana/pull/23973.
