### ISSUE TITLE
StatPanel: Support showing string values

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23880]
The old stat panel supported showing string fields. 

We currently filter out any non number fields when we process values for stat, gauge & bar gauge:
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldDisplay.ts#L120 

The problem is if we remove that is will break for lots of existing panels where queries return time fields or other string fields and rely on that filtering. 

So a bit tricky to support string fields without a breaking change or migration.

**Comment by dprokop** [comment]
moving to 7.0 milestone
