### ISSUE TITLE
An unexpected error happened (Editable Dashboard)

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#23897]
**What happened**:
We lock most of our dashboards for editing. Sometimes, when we want to fix something, we:
1. Make the dashboard editable
2. Go back to the dashboard
3. Try to edit a table, but there appears no option to edit the item/panel

We need to save the dashboard as editable, and then refresh

Other times, we can edit the item, but when we click on edit we get an error:
An unexpected error happened
Details
TypeError: Cannot read property 'setTable' of undefined

    in t
    in div
    in t
    in div
    in r
    in u
    in div
    in div
    in div
    in e
    in t
    in div
    in t
    in t
    in div
    in div
    in t
    in d
    in div
    in t
    in div
    in t
    in DraggableCore
    in t
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in t
    in div
    in div
    in div
    in e
    in t
    in div
    in div
    in t
    in d
    in n
    in Unknown
    in p
    in Unknown
    in Unknown
    in t
    in t
    in d

**What you expected to happen**:
In the first case, allow me to edit the dashboard. In the second case, open the panel properties.

**How to reproduce it (as minimally and precisely as possible)**:
As stated above, that's it.

**Anything else we need to know?**:
We are using a Table Panel, with an embedded SQL query.

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: SQL Server
- OS Grafana is installed on: CentOS 7
- User OS & Browser: I tried and reproduced on IE11 and Chrome 81 on Win10, Also reproduced on Edge/Chromium.

- Grafana plugins:
- Others:

**Comment by papagian** [comment]
Concerning the first, I think I have the opposite problem: after changing dashboard to editable false, I have to save the dashboard for not able editing (hiding Edit from panel menu)

About the 2nd can you be more specific which kind of item you try to edit?

**Comment by reuvygroovy** [comment]
Re: the 2nd, we are trying to edit a table panel.

**Comment by papagian** [comment]
> Re: the 2nd, we are trying to edit a table panel.

you are trying to edit the query or any specific visualisation option?

**Comment by reuvygroovy** [comment]
The second I try to edit the visualization it occurs

**Comment by kramik1** [comment]
I get the same type of error. I switched from using Elasticsearch to InfluxDB to avoid this. It happens on more than one panel type when trying to create new dashboards and panels. It also happened when I was trying to demonstrate Grafana to a VP as a solution. I am using the latest Grafana (6.7.3) and latest versions of Elasticsearch and InfluxDB. I get "## An unexpected error happened TypeError: Cannot read property ‘length’ of undefined" a lot. I put up a forum post to see if anyone else was seeing this but haven't had a response. I was thinking of maybe going back to an older version but I see the original poster is still seeing the same issue with an older version.
![Screenshot from 2020-05-03 10-40-21](https://user-images.githubusercontent.com/5757852/81190217-286ae700-8f7d-11ea-9611-c77445ed3cc5.png)

**Comment by torkelo** [comment]
Tested in 7.0 and seems to be fixed

**Comment by daniellewag** [comment]
Still getting the same issue when using external plugins in Grafana Cloud.

**Comment by danmgs** [comment]
I don't know the reason of this error happening to me when importing dashboard 3662 from Grafana UI.

But to get from initial working UI: 
F12 in my chrome browser, and I clear cache (button "clear site data")
