### ISSUE TITLE
Feature: Drilldown / detail link should support template expansion when using Repeat Panel

### ISSUE THREAD

**Issue by pdf** [grafana/grafana#2389]
When using Repeat Panel it would be desirable to be able to use the panel's template var value as a parameter for drilling down into graphs or external links.  The title appears to support using the panel's template value, would be good to have this applied to drilldown too.

**Comment by slnowak** [comment]
+1
Or maybe is this possible somehow right now? If so, please provide any details.

**Comment by robison** [comment]
+1
Going to take a look tomorrow to see if this is a feasible thing to do; it seems like it should be. I've tried doing some variable substitution tricks but no luck.

**Comment by robison** [comment]
Actually, just updated to 2.1.3, this seems to work just fine now.

**Comment by torkelo** [comment]
yes, this should work

**Comment by robison** [comment]
Thanks for all of your work on this!
