### ISSUE TITLE
Grafana 1.9: How Grafana render the metrics from Graphite depolyed with https and username/password?

### ISSUE THREAD

**Issue by jonesisme** [grafana/grafana#2390]
Hi,

I need to use Grafana 1.9 to render the Graphite metrics deployed with https and username/password enabled. Does Grafana 1.9 or later version support it? What configuration should I do?

Thanks,
Vincent

**Comment by torkelo** [comment]
It depends on what username / password scheme it uses. Basic auth is supported, as is SSL.

**Comment by jonesisme** [comment]
Hi torkelo,

Yes. It is Basic auth. which doc can I refer to?

**Comment by torkelo** [comment]
docs.grafana.org datasources/Graphite

**Comment by jonesisme** [comment]
Hi torkelo,

one more question,  when I point the data source to a ssl enabled graphite, then the grafana gui prompt the "Timeseries data request error" and "Failed to issue metric query". 
But it works after I access the ssl enabled graphite in browser and process the Certificate.
any comment about how to avoid this issue?

thanks

**Comment by torkelo** [comment]
is it valid SSL cert? what is your CORS and grafana setup? nginx? behind same domain name? still using grafana 1.9?

**Comment by jonesisme** [comment]
Now I'm trying grafana 2.0.2. Where should I specify the SSL cert?
Appreciate if you can advise on both 1.9 and 2.0.2.
