### ISSUE TITLE
'Timeseries data request error' and 'failed to issue metric query' with HTTP 200 from graphite

### ISSUE THREAD

**Issue by andycarlsonuk** [grafana/grafana#2391]
I'm having some problems getting Grafana 2.0.2 working with graphite.

I have graphite-web 0.9.10 installed on a VirtualBox Fedora 22 VM hosted on my (Windows 7 Enterprise 64 bit) laptop. As far as I can tell graphite is working correctly and I am able to use the Graphite dashboard to look at my metrics using Firefox (39.0) in Windows-land.

Next I installed Grafana 2.0.2 in Windows-land. It started just fine. I added a (non default) graphite data source using the UI - no problem.

When I try to add a graph panel it shows the random test data just fine.

When I go into 'edit' and change the data source to 'graphite' I get a little red triangle in the corner saying 'Timeseries data request error'. 

On clicking on it, I see that the request is a POST...

POST http://postbridge:80/render
POST data: from=-6h&until=now&format=json&maxDataPoints=1608
The reponse status is 200. The data appears blank on the UI but with Wireshark I can see that it is actually '[]' (without the quotes)

When I click on 'select metric' in the query row, I get a small yellow triangle in the Query row saying 'failed to issue metric query' but clicking on this does not produce any extra info. No metric name appears in the query.

I can see using Wireshark that there was another HTTP exchange with graphite when I click 'select metric':-

 GET http://postbridge:80/metrics/find/?query=*

The response status is 200. The body is...

 [{"leaf": 0, "context": {}, "text": "PRODUCTION", "expandable": 1, "id": "PRODUCTION", "allowChildren": 1}, 
  {"leaf": 0, "context": {}, "text": "carbon", "expandable": 1, "id": "carbon", "allowChildren": 1}, 
  {"leaf": 0, "context": {}, "text": "test", "expandable": 1, "id": "test", "allowChildren": 1}]

(I've split and indented the data here to make it more readable)

The graphite access log also tells the same story that I see in Wireshark...

192.168.2.17 - - [23/Jul/2015:12:26:42 +0100] "POST /render HTTP/1.1" 200 2
192.168.2.17 - - [23/Jul/2015:12:26:49 +0100] "GET /metrics/find/?query=* HTTP/1.1" 200 125

In the graphite error log I see...
 [Thu Jul 23 12:26:42.892988 2015] [wsgi:error] [pid 3747] No handlers could be found for logger "cache"

As far as I can gather this is a known issue with Graphite's logging that does not impact its behaviour.

In the graphite info log I see...
Thu Jul 23 12:17:27 2015 :: [IndexSearcher] performing initial index load
Thu Jul 23 12:17:27 2015 :: [IndexSearcher] reading index data from /opt/graphite/storage/index
Thu Jul 23 12:17:27 2015 :: [IndexSearcher] index reload took 0.000076 seconds (0 entries)
Thu Jul 23 12:26:50 2015 :: find_view query=* local_only=0 matches=3
Thu Jul 23 12:28:44 2015 :: graphite.wsgi - pid 3909 - reloading search index
Thu Jul 23 12:28:44 2015 :: [IndexSearcher] performing initial index load
Thu Jul 23 12:28:44 2015 :: [IndexSearcher] reading index data from /opt/graphite/storage/index
Thu Jul 23 12:28:44 2015 :: [IndexSearcher] index reload took 0.000069 seconds (0 entries)
Thu Jul 23 12:28:51 2015 :: graphite.wsgi - pid 3919 - reloading search index
Thu Jul 23 12:28:51 2015 :: [IndexSearcher] performing initial index load
Thu Jul 23 12:28:51 2015 :: [IndexSearcher] reading index data from /opt/graphite/storage/index
Thu Jul 23 12:28:51 2015 :: [IndexSearcher] index reload took 0.000098 seconds (0 entries)

The Grafana log doesn't indicate any issues either...

2015/07/23 12:11:54 [I] Starting Grafana
2015/07/23 12:11:54 [I] Version: 2.0.2, Commit: v2.0.2, Build date: 2015-04-22 16:51:50 +0100 BST
2015/07/23 12:11:54 [I] Configuration Info
Config files:
  [0]: E:\grafana-2.0.2/conf/defaults.ini
  [1]: E:\grafana-2.0.2\conf\custom.ini
Paths:
  home: E:\grafana-2.0.2
  data: E:\grafana-2.0.2\data
  logs: E:\grafana-2.0.2\data\log

2015/07/23 12:11:54 [I] Database: sqlite3, ConnectionString: file:E:\grafana-2.0.2\data\grafana.db?cache=shared&mode=rwc&_loc=Local
2015/07/23 12:11:54 [I] Migrator: Starting DB migration
2015/07/23 12:11:55 [I] Listen: http://0.0.0.0:3000
2015/07/23 12:12:15 [I] Completed / 200 OK in 31.504ms
2015/07/23 12:12:15 [I] Completed /css/grafana.dark.min.css 304 Not Modified in 78.5099ms
2015/07/23 12:12:15 [I] Completed /app/app.js 304 Not Modified in 145.0184ms
2015/07/23 12:12:15 [I] Completed /img/fav32.png 304 Not Modified in 71.509ms
2015/07/23 12:12:16 [I] Completed /api/dashboards/home 200 OK in 42.0053ms
2015/07/23 12:12:16 [I] Completed /api/search 200 OK in 4.0005ms
2015/07/23 12:12:16 [I] Completed /api/search 200 OK in 10.5013ms
2015/07/23 12:12:16 [I] Completed /img/logo_transparent_200x.png 304 Not Modified in 54.5069ms
2015/07/23 12:12:16 [I] Completed /fonts/fontawesome-webfont.woff 304 Not Modified in 53.5068ms
2015/07/23 12:14:49 [I] Completed /api/search 200 OK in 6.0007ms
2015/07/23 12:14:58 [I] Completed /api/metrics/test 200 OK in 12.0015ms

Having read about similar issues, I've tried looking at what's going on using Firebug but this tells the same story - two HTTP requests that return successfully.

I have also tried installing Grafana in Fedora-land and going through the same steps in case it's a cross-domain problem. The resulting behaviour was the same, just rather slower.

Finally I tried using Firefox within the VM, but again the behaviour was the same (but slower still).

I'm rather stuck regarding what to do next. I can't see anything that indicates that graphite isn't doing the right thing, nor any errors in the Grafana log but for some reason the Grafana UI just doesn't seem to like what it's getting back. 

Thanks for your help.

**Comment by andycarlsonuk** [comment]
My problem is now solved, but I'm still puzzled...

added this to /etc/httpd/conf.d/graphite-vhost.conf

        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, OPTIONS"
        Header set Access-Control-Allow-Headers "origin, authorization, accept"

service httpd reload

... problem solved.

What puzzles me is...

Why did I get the same issue when running Grafana on the same Fedora VM as Apache and Graphite? Perhaps I misunderstood the manual, but my understanding of it is that if these are all on the same machine then that should avoid any CORS problems.

Can you still get a CORS issue when Grafana is on the same machine as Apache and Graphite and the host name of the machine is used to access the Grafana UI (http://postbridge:3000/) and the same hostname used in the data source (http://postbridge:80)?

Is the fact that the URLs have different port numbers enough to cause the CORS issue?

**Comment by torkelo** [comment]
Yes different ports are considered different sites by a browser (and hence require CORS headers). You should be able to work around CORS issues by using the proxy access method

**Comment by torkelo** [comment]
Also please use graphite 0.9.13 or latest release of graphite-api for best performance with Grafana. Grafana 0.9.10 and 0.9.12 is missing a crucial feature that Grafana requires (it works without it but without this feature graphite can return way too many data points which will make Grafana slow)

**Comment by andycarlsonuk** [comment]
Thanks. Maybe the port number thing could be clarified in the docs? Might save some confusion for someone else in future. Other than that one speed bump the Grafana install has been totally smooth for me.

Hope it is not as difficult to upgrade Graphite as it was to get it working in the first place. Smooth is definitely not the word for that process.
