### ISSUE TITLE
Save dashboard does not work from new panel editor

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23910]
Saving dashboard from edit mode works but no changes are saved (as they are not committed yet)

**Comment by torkelo** [comment]
This is fixed , in DashboardModel getSaveClone the panelInEdit is included in the dashboard saved


This was working a few days ago at least

**Comment by torkelo** [comment]
Just tested this and it works fine for me. 

But I did discover one bug and that save and apply does not work from new panel edit if your change sets something to undefined. Like Delete Alert sets panel.alert to undefined. 

Problem is PanelModel.restoreModel is not correct, it does not clear all props on this before setting properties.
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/PanelModel.ts#L162

**Comment by dprokop** [comment]
@torkelo yes, you are right, I wasn't testing against master. Closing

**Comment by torkelo** [comment]
Can you open another issue for that alert issue? As it’s impossible to delete alert rules from graphs currently

**Comment by dprokop** [comment]
yes!

**Comment by dprokop** [comment]
@torkelo reopening this one. Go to panel editor, change viz type, save, refresh dashboard -> changes are not saved :/
