### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by adammenges** [grafana/grafana#2392]
Around the internet I see screenshots like: 

![](https://cloud.githubusercontent.com/assets/5883405/6147343/a59e3a0c-b1f6-11e4-8993-805d1aa9a08e.png)

But when I login as admin and try to edit a dashboard all I see is:

![screen shot 2015-07-23 at 11 21 22 am](https://cloud.githubusercontent.com/assets/817438/8858563/fb88b770-312c-11e5-9728-3f6df2882f3d.png)

How do I change a dashboard's style?

On v2.0.2

**Comment by adammenges** [comment]
Somewhat related: https://github.com/grafana/grafana/issues/304

**Comment by torkelo** [comment]
The theme setting is under user profile
