### ISSUE TITLE
Links: Derived fields with internal links do not work for every datasource

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#23935]
Right now internal link UI specifies single text input as a `Query`. This poses few problem as we need to transform this single string to a meaningful query object.

Right now this works only for tracing datasources (Jaeger and Zipkin) as it is hardcoded to create `{ query: 'query...'}` object. For some datasources this transform is easy as they also expect single string as query but the object still may be a bit different ( `{ expr: 'query...'}` with prometheus for example). Also some have additional option which may or may not be important for the link (limit for Loki or step for Prometheus).

Then there are datasources where the query is much more complex like Elastic. In theory it can be written as a stringified json blob but that probably isn't the ideal user experience.

Few options to solve this:
- Limit the links only to tracing datasources. Definitely not ideal option but I think necessary short term to prevent confusion and bug reports for other datasources.
- Keep the string input and have each datasource implement some kind `queryFromString` API that would parse the string input and create a datasource specific query object. This means though that how the query should look like may not be apparent from the link UI. Also there will be no syntax highlight or autocomplete or any other help with writing the query. Also will probably limit some of the queries to just a subset of the options.
- Provide a queryEditor from the target datasource. This may be nicest from the UI perspective but at the same time there may be subtle non trivial issues, like switching between multiple editors if DS supports multiple modes, how to handle loading autocomplete hints or options from the server, how to handle editor errors etc. Also may not be actually necessary as the second version with simple string input may cover most usecases already.

There is also a general question whether creating any kind of internal link to any kind of target datasource is desirable or we want to limit these options.

Another one is whether this concept of internal links should and will be expanded also to dashboards.

**Comment by aocenas** [comment]
cc @davkal @torkelo

**Comment by Elfo404** [comment]
closing this as it's gonna be tackled by the glue initiative and solved by the use of correlations
