### ISSUE TITLE
heatmaps should allow sparse y-axis labelling

### ISSUE THREAD

**Issue by postwait** [grafana/grafana#23961]
**What would you like to be added**:

Currently, the heatmap view labels all bins on the y-axis.  If you have a lot of bins it becomes unusable.  There should be an option to show only a reasonable number of those bin labels on the y-axis.

**Why is this needed**:

You can't read the graphs Image attached of a an API latency hearmap.

![Heatmap with cluttered y-axis labeling](https://user-images.githubusercontent.com/335748/80403210-42c20800-888d-11ea-9d98-93ec7bcc1c9e.png)

**Comment by papagian** [comment]
Duplicate of #11342
