### ISSUE TITLE
Dataframe: Support Duration type

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#23969]
The backend now supports a duration type (arrow / nanoseconds) in a dataframe.

But with the frontend and our backend plugin test-datasource, I get an error:

```Unrecognized type: "Duration" (18)```

**Comment by ryantxu** [comment]
@kylebrandt -- can you paste the base64 encoded response here?

**Comment by kylebrandt** [comment]
@ryantxu https://gist.github.com/kylebrandt/b9cc47f83fd234b82f472992df1b21d7

**Comment by kylebrandt** [comment]
Arrow issue to support Duration in JS: https://issues.apache.org/jira/browse/ARROW-5356
