### ISSUE TITLE
styling issues with shared graphs when using the light theme

### ISSUE THREAD

**Issue by roobert** [grafana/grafana#2397]
Hi, first: thank you for grafana, it is amazing!

I have what looks like two styling issues with shared graphs.

1) when sharing an interactive iframe, or png image: if the theme is set to 'light' then the graphs have a thick grey boarder at the bottom
2) when the theme is set to light the mouse over graphic is using the dark theme (is this intentional / a limitation?)

![crop](https://cloud.githubusercontent.com/assets/226654/8883021/a071a2ee-3243-11e5-8ff2-ae28324c8183.png)

**Comment by bulletfactory** [comment]
Hi Roobert,
Thanks for submitting this issue - Admittedly, the light theme may not gotten quite as much attention as the dark, as of late. Let me take a look and see if I can make it feel a bit more unified. Appreciate the feedback.

**Comment by roobert** [comment]
:+1:

**Comment by bulletfactory** [comment]
reopening until merge is completed.

**Comment by roobert** [comment]
Awesome, thank you!
