### ISSUE TITLE
Share link of panel view yields the entire dashboard

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#23976]
**What happened**:  Share link of a fullscreen panel view loads the full dashboard view rather than panel view.

**What you expected to happen**:  Generated link should yield the same fullscreen panel view

**How to reproduce it (as minimally and precisely as possible)**:
 1. Go to fullscreen view of a panel
 2. go to Share / Link and copy URL
 3. load the URL

note that the generated URL is missing "&fullscreen" and "&panelId" query params

**Environment**:
- Grafana version:  v6.6.2

**Comment by papagian** [comment]
I'm unable to reproduce it. Can you share more specific to your case guidelines and/or some screenshots?

**Comment by torkelo** [comment]
I can replicate, thanks for reporting this!

**Comment by torkelo** [comment]
To fix we need to update this: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/ShareModal/utils.ts#L33 

So that instead of panelId and fullscreen it is just viewPanel=id 

Maybe should have notice in changelog about this url change
