### ISSUE TITLE
Favicon misalignment

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#23980]
Grafana and Grafana's Storybook does not use the same favicon as grafana.com

![Screenshot from 2020-04-28 10-36-34](https://user-images.githubusercontent.com/1438972/80466166-714aec00-893c-11ea-8389-9353a1e7ba5b.png)

**Comment by peterholmberg** [comment]
which version is the correct one?

**Comment by tskarhed** [comment]
I think the one in the middle - grafana.com

**Comment by abhi0977** [comment]
@peterholmberg @tskarhed can I pick this up?
or any good first issue?

**Comment by tskarhed** [comment]
@abhi0977 Yeah, go ahead! You can always have a look at [these issues](https://github.com/grafana/grafana/issues?q=is%3Aopen+is%3Aissue+label%3A%22beginner+friendly%22+label%3A%22help+wanted%22) if there is something you're interested in 👍

**Comment by abhi0977** [comment]
@tskarhed can you review [this](https://github.com/grafana/grafana/pull/24111)?
