### ISSUE TITLE
Elasticsearch: metric raw document sort

### ISSUE THREAD

**Issue by harrybin815** [grafana/grafana#23991]
**What would you like to be added**:

When using the ES data source, the query "metric=raw document" supports the specified field sort

**Why is this needed**:

While timestamp is a common sort, sorting by specified field should be more common

**Comment by vvvprabhakar** [comment]
Fixed this issue for v6.6.x
https://github.com/grafana/grafana/pull/30029

**Comment by vvvprabhakar** [comment]
Fixed this issue for v7.4.x
#32194

**Comment by matyax** [comment]
Closing this one for now. If this is still valid, please follow up. Thanks!

**Comment by jeremycohensolal-paylead** [comment]
Hello,
is it possible to use it with grafana 8.3.6?  or on the last (9.3.6)?  (I use OSS versions)
