### ISSUE TITLE
Defining a filter that has two segments to it

### ISSUE THREAD

**Issue by petemounce** [grafana/grafana#240]
I have metrics like `stats.gauges.<tenant>.<feature>_<server number>.cpu`.

I'd like to define filters so that I can supply values for tenant, feature, and server number.  I want to be able to get feature\* as well as individual feature servers' stats - so, aggregate CPU across all of a feature's servers as well as each individual one.

I can define the filter for tenant easily enough with `stats.gauges.{all,be,ca,uk}`.

For feature and server number, though, since I have two parts in the same segment, I'm having trouble.  I have tried `stats.gauges.*.{payments,publicweb,backoffice}_*` - but this will then list out
```
payments_001
payments_002
....
payments_006
etc
```

If I use `stats.gauges.*.{payments,publicweb,backoffice}` or `stats.gauges.*.{payments,publicweb,backoffice}*` I get no entries.

I think what I'm asking for is to extract two filter values from a single segment.  I've tried this just now on 6100336b2a5977b2d36f4b6648bc90cd40bc8d20.

**Comment by torkelo** [comment]
this should be solved by using regex to extract the part of the segment you want in the template variable

**Comment by petemounce** [comment]
Thanks!

--
