### ISSUE TITLE
Grafana not being responsive anymore after changing variables

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#24005]
**What happened**:
I'm working with grafana for many months now and i'm starting to get issue while working with it.
This issue may be hard to reproduce, especially because i don't really know what is causing it.

As i add variables to a dashboard, use these variables into panels and added AdHoc filters (all based on a elasticsearch cluster), everything is working fine.
But when i start changing the variables that are available on my dashboard, i can no longer edit a panel or go into the dashboard settings.
The website link at the top is, undeed, changing from the action i'm doing like editing a panel or going into the settings, but the webpage is frozen on the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1 - Get an elasticsearch instance with data inside 
2 - Create multiples variables that allows you to select the data displayed inside the panels (in my case: hostname and level)
3 - Add AdHoc filters to the same datasources
4 - Create multiples panels to display your data on it
5 - Configure the queries inside the panel to change your research when you are choosing others value from your variables
6 - Website froze up but the link in the URL is undeed changing when editing a panel or going into the dashboard settings
7 - To unfrooze the situation, you have to open the dashboard settings (which change the URL but stays on the dashboard physicaly), then tries to edit a panel from your dashboard. This will unfrooze your grafana and send you to the settings.
8 - Exiting the settings allows you again to edit panels until i changed another variable. After that, i'm back at the step 6

I've made a quick video with the issue that is upload on Imgur :
https://imgur.com/a/IrwfVM0
(Sorry, imgur compressing is hard. The quality might not be good)

I'm precising that i specificaly choose variables that do not display any datas in this video.
The bug also appears when data are present into the panels. And it's also not the only dashboard which have this issue

The issue is also present on the last version of Firefox. Edge might not be the issue here.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Elasticsearcg 7.6.2
- OS Grafana is installed on: CentOS 1704
- User OS & Browser: Edge 81.0.416.64 
- Grafana plugins: PieChart 1.4.0 (modified to reduce the donut radius)

**EDIT** : Deleting the ADHoc Filters seems to fix the issue, but it's really usefull to have the ability to apply filters on the fly ...
I don't know what is causing AdHoc to prevent grafana from updating it's display

**Comment by dprokop** [comment]
@Theoooooo thank you for the report. Is there any output in the developer tools console?

**Comment by Theoooooo** [comment]
@dprokop Each time i tried to edit the panel, i'm getting the following error :
![image](https://user-images.githubusercontent.com/33425208/80966203-54b72400-8e14-11ea-835c-8fe4a2996f68.png)

Besides this, my dashboard variables are working properly and i'm not getting any warning message when i tried to update them manually

**Comment by dprokop** [comment]
@Theoooooo thanks for a quick response, we will try to investigate this issue.

**Comment by Theoooooo** [comment]
@dprokop If you need any more informations, let me know; i can reproduce this issue easily

**Comment by mckn** [comment]
@dprokop @Theoooooo  this issue is fixed in version `6.7.3`

**Comment by dprokop** [comment]
Thank you @mckn, indeed fixed by https://github.com/grafana/grafana/pull/23580

**Comment by Theoooooo** [comment]
ew it may be my fault then. I'm updating and testing this right now

**Comment by Theoooooo** [comment]
Yes, it's working now.
Sorry about that

**Comment by dprokop** [comment]
No problem @Theoooooo

**Comment by M0rdecay** [comment]
I have a similar issue with grafana 6.7.4 and InfluxDB
Unfortunately, so far there is no way to check this on 7.x. Is it fixed there?
