### ISSUE TITLE
alert engine: no tracing propagation for alert execution span

### ISSUE THREAD

**Issue by nextus** [grafana/grafana#24004]
**What happened**:

Alert execution doesn't propagate trace id to the data sources (checked with prometheus data source) when jaeger tracing is enabled.
`Uber-Trace-Id` HTTP header is absent when grafana sends query request from alert engine (but in regular requests it presents).

**How to reproduce it (as minimally and precisely as possible)**:

With enabled jaeger tracing in grafana, create an alert and check the span in jaeger ui using «alert execution» operation as a filter.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.4.3 (but I couldn't find any mentions about this bug in changelog and tracker)
- Data source type & version:
Prometheus
- OS Grafana is installed on:
gnu/linux

**Comment by marefr** [comment]
For the Prometheus backend data source code there are a trace created here:
https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/tsdb/prometheus/prometheus.go#L109-L113

As described above, what's seems to be missing is to propagate the trace with the Prometheus api client call. 
An example when propagating the trace for http.Request can be seen here:
https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/tsdb/graphite/graphite.go#L99-L104

Probably have to investigate how to propagate trace ids using the Prometheus Go Client library. Maybe it has to be done using HTTP client middleware, i.e. an additional http.RoundTripper, [here](https://github.com/grafana/grafana/blob/c028d3047cdc6f718532d6d9100bed80ed4f49a9/pkg/tsdb/prometheus/prometheus.go#L66).
