### ISSUE TITLE
Confusing logout option in the Grafana UI

### ISSUE THREAD

**Issue by apurvabhide** [grafana/grafana#24013]
**What would you like to be added**:

- Adding  the **Logout** option in the top right corner similar to other applications (for example Gmail, facebook, twitter, and so on). 

- Currently there are  three different settings/preferences:
left pane, middle: general configuration
left pane, bottom: current user configuration (**Logout** option)
top right: current dashboard settings
Is it possible to keep one setting option at top right corner, which is a combination of options from left pane (bottom) and top right?

Related to [https://github.com/grafana/grafana/pull/23963](https://github.com/grafana/grafana/pull/23963).

**Why is this needed**:
It helps to find this option easily. Keeping it in the bottom of top left pane is difficult for an user to find this option.

**Comment by torkelo** [comment]
The main menu is on the side, the sign in & user profile icon is on the side. So makes sense to have it there (and many apps that have side menu's do the same. 

Top area is unique for each page. But if we consider moving the side menu to the top it makes sense: https://github.com/grafana/grafana/issues/13573
