### ISSUE TITLE
Change CSV export seperator

### ISSUE THREAD

**Issue by andycarlsonuk** [grafana/grafana#2401]
This one was discussed before in https://github.com/grafana/grafana/issues/1855 but closed because only one person raised it.

It's also an issue for me.

As far as I can tell, your experience with this depends on where you live...

In some locales a semicolon separated file will work fine as a CSV file in Excel without any config changes. In others it will not. In my own Excel setup (UK) it opens with all of the fields (and semicolons) appearing in a single column... which is not what most people want.

For sure it is possible to persuade Excel (using "Data/Text to Columns") to split the data into three columns but it's not a very slick user experience. A similar observation applies to dealing with the date/time format.

The rest of Grafana is very slick indeed, so the CSV export could definitely benefit from some further thought. 

I believe that there are at least three questions to consider:-
1. CSV column separator - currently ';' which does not work 'out of the box' in some locales (e.g. UK)
2. Decimal separator - currently '.' which is fine for me here in the UK but it may be worth checking whether it works in countries that use a comma for decimals
3. Date/time format - currently a format which looks like ISO8601

FWIW, here is what Grafana produces on my machine

Series;Time;Value
total throughput;2015-07-26T08:02:00.000Z;4821
total throughput;2015-07-26T08:03:00.000Z;5293
total throughput;2015-07-26T08:04:00.000Z;5347

and here is how I needed to change it to make it display correctly in Excel (2010)

Series,Time,Value
total throughput,2015-07-26 08:02:00,4821
total throughput,2015-07-26 08:03:00,5293
total throughput,2015-07-26 08:04:00,5347

Leaving the decimals in the timestamp doesn't prevent Excel from *interpreting* the value correctly but it does display in a very odd way (minutes:seconds plus a single decimal place) and then requires explicit reformatting in Excel to produce a sensible result on the screen.

I don't honestly know whether there is a 'one size fits all' answer for the time format (probably not) so perhaps it would be possible to make this a configurable option?

Changing the column separator to be a comma would fit with the RFC4180 definition of CSV. If this is a backwards step in other locales then making the separator configurable should suit everyone.

With regard to decimal separator, I don't know whether this causes any issues in countries that use a comma so I can't answer that one. If a comma is used for a decimal separator in the file then the values will most likely need to be quoted.

**Comment by torkelo** [comment]
All excel versions should be able to import the CSV as you can specify the separator when you import the CSV.

**Comment by andycarlsonuk** [comment]
Thanks. Agreed, it is possible to tell Excel which separator character to use but the behaviour (and experience) depends on how the user deals with the file from the web page. 

Only one of the several possibilities causes Excel to automatically ask for the separator and I think that this possibility is one of the less likely ones.

Here is what happens on my machine (Windows 7, Firefox, Excel 2010)...

The browser asks the user what to do when the site responds with the file.

The simplest action is to say 'open' in which case the CSV goes straight to Excel and if the separator is not what Excel is expecting (e.g. a comma in the UK) then it loads without being split into columns.

The other option is to save the file without opening it. If the user saves to a *.csv file (which is the default since grafana names it grafana_data_export.csv) and then opens this in Excel (e.g. by double clicking the file in Explorer) then the result will be the same - no columns.

If the user changes the default name and saves it as '*.txt' and then opens it via the File/Open menu then Excel opens the wizard which asks about separators etc.

If the user saves it as *.txt and opens it by right clicking and then 'Open With...' or drag and drop then Excel assumes a tab separated text file and does not open the wizard so again the semicolons are not recognised as column separators.

Whichever route is used the wizard can be accessed after the file is opened using the Data/Text to Columns menu.

I hope that the change of title for the issue doesn't mean that the timestamp question won't be covered - massaging the timestamp into something that Excel recognises as a date/time column is more difficult than dealing with the column separator character.

**Comment by DavidOhsie** [comment]
I just started using Grafana, and andycarlsonuk is correct.  There is a large user experience difference between clicking on a button and immediately seeing the results in Excel and a 4-5 step process to do an import.  I just switched over from Grafana from ganglia's web interface and and I miss the feature.

The solution could be a couple of settings that would apply to all exports: "delimiter" and "time format".  If you wanted to be fancy, you could make the settings settable per user and/or enable reading the locale to get the default setting.

**Comment by druchoo** [comment]
+1 for some type of enhancement...

* CSV format should probably follow [https://tools.ietf.org/html/rfc4180#page-2](https://tools.ietf.org/html/rfc4180#page-2)
* Decimal separator and time format should use system locale settings if possible

**Comment by plopp** [comment]
@druchoo I recently submitted a pull-request on the CSV format and it was merged. It places the series names in the header etc. Very similar to rfc4180, but the separator is still a semicolon and that is hard coded. See this: https://github.com/grafana/grafana/pull/4041

**Comment by dalesit** [comment]
One solution would be to add an extra first line which has

`sep=;`

This then allows Excel to interpret the ; as the column separator. This should not be a bit change, as it explicitly states in the csv file which value is used as the separator, and thus is independent of regional settings.

**Comment by dalesit** [comment]
I have raised #5325 which I hope will resolve this issue. I don't believe there should be any conflicts for others as I detailed above - it is just explicit about the separator used.
