### ISSUE TITLE
Improve scripted dashboard examples and scripted dashboard documentation

### ISSUE THREAD

**Issue by edgecode** [grafana/grafana#24014]
**What would you like to be added**:
1. Explicitly set the TestDataDB datasource in `scripted.js`
[scripted.js](https://github.com/grafana/grafana/blob/master/public/dashboards/scripted.js) uses _random walk_ in its `panel->targets` definitions.
So, it wants to use Grafana's _TestDataDB_ datasource.
However, `scripted.js` does not set the datasource _TestDataDB_ anywhere.

2. Make clear that the `panels.targets` definition is different for different datasources.
The _TestDataDB_ datasource seems to work with any `panels.targets` definition:
```json
targets: [
  {
    scenarioId: "random_walk"
  },
  { 
  },          
  {
    target: "randomWalk"
  },
  { 
    myCompletelyRandomNonsense: "splunge"      
  }
]
```
All of the four definitions above produce a graph with random data from _TestData DB_.

Other datasources are "pickier".
A minimal valid target for an InfluxDB datasource looks like so:
```json
targets: [
  {
    query: "SELECT myColumn FROM mySeries WHERE foo='bar'",
    rawQuery: true
  }
]
```
The keys `scenarioId` or `target` do not work with an InfluxDB datasource (and probably others).

**Why is this needed**:
1. I get an empty dashboard without a graph when browsing http://localhost:3000/dashboard/script/scripted.js in my Grafana 6.7.3 installation.
Hm, not what a Grafana dashboard usually looks like.
I do not get a warning or error either, although something seems to have gone wrong.
With the datasource explcitly set in `scripted.js` (and in other examples using a datasource) the user gets a warning that the datasource needs to be installed/activated for the example to work.
If _TestDataDB_ is installed the user actually sees graphs.

2. If you are not familiar with using different datasources programatically you might use `scripted.js` as a template and wonder why your datasource does not work with your code.

**Comment by edgecode** [comment]
I would be happy to create a pull request if you think this improvment is actually an improvement.

**Comment by torkelo** [comment]
Scripted dashboards are sadly deprecated as of 7.0: https://github.com/grafana/grafana/issues/24059 

We wont remove the feature until we have something that solves a similar problem. Added a deprecation notice to docs article as well.
