### ISSUE TITLE
Table: Column titles become empty after clearing Title field

### ISSUE THREAD

**Issue by krzysdabro** [grafana/grafana#24022]
**What happened**:
After clearing value in Title field column titles become empty.
![screen](https://user-images.githubusercontent.com/7547604/80540325-624e5300-89a9-11ea-8aca-9fcfbf6c32e1.png)

**What you expected to happen**:
Column titles return to default.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create table panel
2. Go to Fields
3. Type something into Title field
4. Clear field

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0-beta1

**Comment by torkelo** [comment]
Was unable to replicate this in master dev build, maybe only happens in production builds? 

We need to change the title field, it triggers on change (and viz render) on every key press

**Comment by krzysdabro** [comment]
@torkelo It still happens on master. `stringOverrideProcessor` is returing empty string at [here](https://github.com/grafana/grafana/blob/f2254081c2859e141110c0a948195d9dfb5e5a92/packages/grafana-data/src/field/overrides/processors.ts#L78). After adding check for empty string (#24083) columns titles are correctly changing.
