### ISSUE TITLE
Blank PNG on "Direct link rendered image"

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#2403]
Hi, I need to automatize a report of several panels with specific timestamps. To do that I wanted to use the feature granted on every panel: Share -> Link -> Direct link rendered image.

If I use the normal share link I obtain the correct Dashboard view, passing as url:

`http://mygrafana.com/dashboard/db/mydashboard?panelId=1&fullscreen&from=1438047606415&to=1438069086415&var-app=app1&var-backend=bk1`

It loads correctly and takes 1.4 secs.

Clicking on "Direct link rendered image", It grants the url passing on phantom render as:
`http://mygrafana.com/render/dashboard-solo/db/mydashboard?panelId=1&fullscreen&from=1438046704187&to=1438068184187&var-app=app1&var-backend=bk1&width=1000&height=500`

And it grants me a blank html with blank PNG. The `GET` restult is `OK (200)` and its loaded on 10.1 seconds and the logs doesn't grants any exception or problem.

I have been reading on #1933, that could be some problem of the Phantom Render timeout. I'm a Graphite user.

Can you please check it? 
If its the timeout problem, can I change the timeout sever value to get the correct render?

**Comment by diiidiii** [comment]
Same here. Im using Influxdb and also get a black PNG on the direct link for rendering image...

**Comment by torkelo** [comment]
blank as in white or blank as in a graph with no data? the transparent / white PNG can be a phantomjs issue, maybe font package missing, or it could be a problem with root_url config, what URL does the grafana log say it passes to phantomjs, is this correct and accessable on the local machine?

https://github.com/grafana/grafana/issues/1696
https://github.com/grafana/grafana/pull/2053

**Comment by sbengo** [comment]
Hi @torkelo, Im not using SSL and using the lastest master version of Grafana, actually Im using correct root_url config...

As I said, doing the GET I obtain as response a "document" not a "PNG" with the following response:

![image](https://cloud.githubusercontent.com/assets/13196237/8929921/6dbfc798-3529-11e5-8c1f-05b83082ae10.png)

Thanks

**Comment by torkelo** [comment]
something must be wrong with phantomjs in your setup, maybe missing font package or something, all have so far gotten the png rendering to work, the only issue I know of is SSL fixed in master or missing font packages

**Comment by toni-moreno** [comment]
Hi @torkelo , I'm working with @sbengo in the same platform and Issue. We are working with a apache proxy in front of grafana (grafana is listening on http://localhost:8080)

We have solved this issue by setting up root_url to 'http://localhost:8080'

But I'm not sure if this parameter could affect other grafana things.

Thank you very much!

**Comment by torkelo** [comment]
@toni-moreno that could effect other things, like gihub or google oauth, or some of the apis that return DTOs with absolute uris  (they use the root_url)
