### ISSUE TITLE
Clarify backend plugin loading and bundled plugins

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#24049]
**What would you like to be added**:
Clarify backend plugin loading and bundled plugins.

* Make sure Bundled plugins are actually loaded
* Define preference wrt. the different plug-in directories, e.g. if installed plug-ins are preferred over eventual identically named bundled plug-ins

**Why is this needed**

For example, if GEL is bundled, but someone wants to install a newer version of the plugin, what do they do?

I think maybe it errors currently if you had the same plugin?

```
func (pb *PluginBase) registerPlugin(pluginDir string) error {
	if _, exists := Plugins[pb.Id]; exists {
		return fmt.Errorf("Plugin with ID %q already exists", pb.Id)
	}
```

**Comment by aknuds1** [comment]
Thanks @kylebrandt !

**Comment by jessabe** [comment]
Closing after discussion on 2020-07-13 // No longer relevant
