### ISSUE TITLE
Docs: Add SSL CA support in MySQL datasource documentation 

### ISSUE THREAD

**Issue by matthew-muscat** [grafana/grafana#24044]
**What would you like to be added**:
Add the ability for the MySQL datasource to be connected over an SSH tunnel

**Why is this needed**:

Currently, it's possible to connect to a MySQL datasource directly via an IP connection, however, the nature of DB systems would typically require these are either firewalled against public facing traffic or placed behind a SSH jump box.

A number of tools that are used to interact with datasources such as MySQL offer the ability to connect to the source using an SSH-tunnelled connection.

Note: This feature request is for MySQL, however this feature is likely something that could be applied across a number of datasources, ie: PostgesQL, Elasticsearch etc..

**Comment by papagian** [comment]
There is SSL CA [support](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mysql/partials/config.html#L32) for MySQL datasource which is unfortunately undocumented.

**Comment by matthew-muscat** [comment]
Hi @papagian ,

Understanding that there is some SSL CA functionality — however my original request was with regards to adding support for an SSH tunnel based connection, due to a few factors...

1. Database services may not be directly accessible over the internet (ie: AWS Aurora / GCP Cloud SQL)
2. SSL CA, while useful, may not be available in some instances, but SSH access tunnelling is

**Comment by chancez** [comment]
> Hi @papagian ,
> 
> Understanding that there is some SSL CA functionality — however my original request was with regards to adding support for an SSH tunnel based connection, due to a few factors...
> 
> 1. Database services may not be directly accessible over the internet (ie: AWS Aurora / GCP Cloud SQL)
> 2. SSL CA, while useful, may not be available in some instances, but SSH access tunnelling is

I'd imagine you could just run a tunnel on localhost and connect to the tunnel on localhost, where there's no need to configure SSL if thats what you want. No need to have grafana run a tunnel for you.

**Comment by matthew-muscat** [comment]
> I'd imagine you could just run a tunnel on localhost and connect to the tunnel on localhost, where there's no need to configure SSL if thats what you want. No need to have grafana run a tunnel for you.

Yep, this is how we do it currently — with that being said, it's an extra step required to securely connect to a remote resource, one which if offered natively within Grafana would be beneficial

**Comment by marefr** [comment]
Thanks, but very unlikely Grafana will support something like this so will close this. Grafana cannot do everything unfortunately. Closing an issue doesn't mean it can be reopened should there be a lot more interest in this feature.
