### ISSUE TITLE
Deprecate scripted dashboards 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24059]
Scripted dashboards is now deprecated. The feature is not removed but will be in a future release. We hope to address the underlying requirement of dynamic dashboards in a different way.

**Comment by glkz** [comment]
> We hope to address the underlying requirement of dynamic dashboards in a different way.
@torkelo what is the different way you are considering to address dynamic dashboard use cases? It would be great if you can share any docs if available.

**Comment by RedShift1** [comment]
Why are you deprecating this feature when there's no replacement? Can't you at least wait to deprecate things that are a feature and currently work until a suitable replacement is ready?

**Comment by Hipska** [comment]
I think something like Grafonnet support will come then?

**Comment by eagletmt** [comment]
I'm a user of the scripted dashboards feature.
In my use case, the script fetches JSON data from an external API server and puts it to the dashboard directly.
The script is pretty simple and looks like below.

```js
'use strict';

var ARGS;

return async function(callback) {
  const fallback = {
    schemaVersion: 18,
    title: 'Failed to load dashboard from hako-console',
    panels: [
      {
        id: 1,
        type: 'text',
        gridPos: {
          w: 24,
          h: 3,
          x: 0,
          y: 0,
        },
      },
    ],
  };
  try {
    const response = await fetch(`https://hako-console.example.com/grafana_dashboards/${ARGS.app_id}`, { credentials: 'include' });
    if (response.status === 200) {
      const dashboard = await response.json();
      callback(dashboard);
    } else {
      fallback.panels[0].content = `hako-console returned ${response.status} error.`;
      callback(fallback);
    }
  } catch (e) {
    fallback.panels[0].content = `Failed to fetch API response from hako-console: ${e}`;
    callback(fallback);
  }
};
```

(more details in :jp: https://techlife.cookpad.com/entry/2019/07/24/113835)

So it would be great if a new mechanism for dynamic dashboards supports something like "dashbords API server". In my use case, there's no need to run arbitrary JS code.

**Comment by datamuc** [comment]
> We hope to address the underlying requirement of dynamic dashboards in a different way.

Is there a place where this is discussed? Or is there a roadmap or something? This is really really bad news for me.

**Comment by RedShift1** [comment]
Somebody looked at the code and didn't like it, thus it must be removed. Agile.

**Comment by Dmitry1987** [comment]
🤣

**Comment by Dmitry1987** [comment]
someone got bored at work I guess and decides to deprecate a perfectly stable working feature used by thousands of Grafana users and admins

**Comment by abdulgalimov** [comment]
This is very very bad news :( Please tell me if there will be an alternative by the time this opportunity closes? Is there a thread where replacement is discussed? Please give any information, this is very important for our projects. Thanks.

**Comment by Dmitry1987** [comment]
A better solution would be to leave it as a paid feature, if it doesn't
generate any income in a free version.. at least these who depend on it
already, could keep using it in a paid version.

**Comment by swgoldwood** [comment]
A better solution is to not randomly remove it without a replacement

**Comment by Dmitry1987** [comment]
I am so curious to know why it was deprecated, plain curiocity

**Comment by torkelo** [comment]
We won't remove it with out some kind of replacement

**Comment by datamuc** [comment]
> We won't remove it with out some kind of replacement

Hi @torkelo, Is there a place where this replacement is planned/discussed?

**Comment by mrhackcz** [comment]
+1

**Comment by abdulgalimov** [comment]
Developers, why don't you want to give more information about what will be in replacement? But you were in a hurry to say about the closure. The feeling that you have nothing to replace :(

**Comment by mrajashree** [comment]
Hi @torkelo , can you share what the replacement is and if we can try it out?

**Comment by torkelo** [comment]
not built yet :)

**Comment by ofauchon** [comment]
Any news about scripted dashboard's replacement ?

**Comment by cmendez92** [comment]
I understand that the only reason to remove something that works perfectly is to put the same functionality but in the enterprise grafana (payment).

Can you confirm it for me?

**Comment by datamuc** [comment]
> I understand that the only reason to remove something that works perfectly is to put the same functionality but in the enterprise grafana (payment).
> 
> Can you confirm it for me?

In that case I would expect that they still fix bugs, but they don't:

#32800
#41736

**Comment by ofauchon** [comment]
@torkelo : Is there still hope for a replacement solution for dynamic dashboards ?
This discussion started in 2020 :-(

The situation is very disappointing and frustrating.... 
Could you please clarify your position on this feature request ? 

Thx

**Comment by torkelo** [comment]
We have not removed it yet as we have no replacement still

**Comment by ofauchon** [comment]
I suggest you update the documentation "https://grafana.com/docs/grafana/latest/dashboards/scripted-dashboards/"
with more detailed explanation/context..

"Warning: This feature is deprecated and will be removed in a future release." 
-> This sounds like "Don't waste your time with that or you'll get stuck (No idea if we'll replace it or not)"

Thx

**Comment by datamuc** [comment]
I was told that this is the designated replacement: https://grafana.github.io/scenes/

**Comment by torkelo** [comment]
yes, https://grafana.github.io/scenes/  is designed to enable anyone to build really dynamic dashboards apps

**Comment by paubartoli** [comment]
Hi, 

Thank you both ;) I've seen that there are some broken links that shold redirect to the github demo project for scenes.
Is there somewhere where we caan find a demo or an extended documentation?

Thank you in advance

Greetings

**Comment by datamuc** [comment]
> yes, https://grafana.github.io/scenes/ is designed to enable anyone to build really dynamic dashboards apps

At least anyone who understands React. It looks a lot harder to get things done... But I will give it a try.
