### ISSUE TITLE
I get the error "./bin/grafana-server: cannot execute binary file"?

### ISSUE THREAD

**Issue by lwd426** [grafana/grafana#2405]
I build my source by the commond "go run build.go build package" with mac as the mainpage of grafana. Then grafana runs normally. But it can 't run on centos. When I run the ./bin/grafana-server, I get the error "./bin/grafana-server: cannot execute binary file".What shall I do?  Thank you.

**Comment by torkelo** [comment]
build on centos , if you build on mac you create a mac os binary

**Comment by lwd426** [comment]
Thanks
