### ISSUE TITLE
v7.0.0-beta1: Error Loading Third-Party Datatable Plugin

### ISSUE THREAD

**Issue by societymartingale** [grafana/grafana#24065]
**What happened**:
After upgrading Grafana from v6.7.3 to v7.0.0-beta1, the datatable plugin (https://github.com/briangann/grafana-datatable-panel) fails to load. Downgrading Grafana to 6.7.3 fixes the problem. I wasn't sure whether I should post this issue to the datatable or Grafana repo, but since it is related to the v7 beta, I thought I would start here. Here is a screenshot:

![Screen Shot 2020-04-29 at 4 07 43 PM](https://user-images.githubusercontent.com/22607854/80642831-1ea12b00-8a35-11ea-8386-9118bb1487d7.png)

**What you expected to happen**:
Expect datatable to load as usual after upgrading Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
On v7.0.0-beta1 instance of Grafana, try to add a datatable panel, and the error occurs.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.0-beta1 (upgrading from v6.7.3)
- Data source type & version: Postgres
- OS Grafana is installed on: Alpine (Docker)
- User OS & Browser: MacOS, happens on both Firefox and Chrome (screenshot is from Firefox)
- Grafana plugins: https://github.com/briangann/grafana-datatable-panel (version 1.0)

**Comment by papagian** [comment]
Thank you for reporting this.
Closing this in favour of briangann/grafana-datatable-panel#89
