### ISSUE TITLE
How to graph with influxdb and collectd

### ISSUE THREAD

**Issue by caoli5288** [grafana/grafana#2406]
I am so sorry to ask such a stupid question. Some data what collectd collected in influxdb is linear growth. 
How can I graph a per second graphic.

**Comment by torkelo** [comment]
InfluxDB has a derivative function that calculates the diff between two values, but I know many have had issues with that function

**Comment by caoli5288** [comment]
Can grafana offer any calculate func like rrdtools' graph command?

**Comment by caoli5288** [comment]
Such as multiple query result, avg two or more query result..etc

**Comment by torkelo** [comment]
Graphite is amazing at this, has hundreds of transformation functions that you can chain in infinite ways. InfluxDB has some functions but has yet to be as flexible as Graphite when it comes to analytics and transformations. but might come in the future.

**Comment by caoli5288** [comment]
Such as multiple query result, avg two or more query result..etc

**Comment by torkelo** [comment]
Grafana does not provide this, the metric query is handled by the time series database (InfluxDB in your case) , so if you find something missing in the their query language you need to request an enhancement with that project

**Comment by caoli5288** [comment]
Ok, I'll open a issue on influxdb's repo :) THX

**Comment by caoli5288** [comment]
But I still think grafana can provide some simple calculation fuc, which is very cool.
