### ISSUE TITLE
Copying json from provisioned dashboard into new dashboard overwrites provisioned

### ISSUE THREAD

**Issue by johncornish** [grafana/grafana#24067]
**What happened**:
When trying to copy a provisioned dashboard and give the copy a different name, Grafana overwrote the provisioned dashboard instead.

**What you expected to happen**:
I see an entirely new dashboard alongside the provisioned dashboard, with the changed title.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to a provisioned dashboard
- Click save
- Be presented with error message about saving provisioned dashboard
- "Copy JSON"
- Create dashboard
- Click settings gear
- Update JSON Model with copied JSON
- Change the title in the JSON, but do not change anything else or remove UID
- See that the new dashboard has the default "New Dashboard" title and none of the panels you copied over from the provisioned dashboard
- Go back to Dashboards > Manage screen and see that your provisioned dashboard has now been renamed

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac & Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
If you copy a json to a new dashboard you should use the import feature, there you would get notice that the dashboard uid is already being used etc. 

Tested this in 7.0-beta1 and it you will get an error (Cannot save a provisioned dashboard)
