### ISSUE TITLE
Provisioned Dashboard not found - if there is update in dashboard JSON file

### ISSUE THREAD

**Issue by vijayakumarbathini** [grafana/grafana#24072]
**What happened**:
We are getting error when we access dashboard, "Dashboard Not found" if there is any update in JSON files used for provisioning dashboards.

**What you expected to happen**:
Dashboard should be shown

**How to reproduce it (as minimally and precisely as possible)**:

Step 1: Provision dashboards to DB using JSON files
Step 2: Update JSON files with some values
Step 3: Restart server
Step 4: Access any dashboard immediately after server restart
Step 5: You will be seeing dashboard not found error till new dashboards provisioned into db.

**Anything else we need to know?**:
This we have reproduced with 50 org Ids. **Suspecting it might be happening when dashboard provisioning call is running in backend.**

**Environment**:
- Grafana version: 6.6
- Data source type & version: Postgres
- OS Grafana is installed on: Centos
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
I think this might not be an issue anymore so I'm going to close this, if this is not the case please let us know and we can reopen this.
