### ISSUE TITLE
Transforms: Join by field crash

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24078]
Replicate: 

1) Create test data random walk query, set series count to 4
2) Pick table panel
3) Join by field
4) Change join field to any of the time series field names, crash

**Comment by kaydelaney** [comment]
Just for clarity's sake: What is the expected behavior?

**Comment by hugohaggmark** [comment]
> Just for clarity's sake: What is the expected behavior?

There are tests that should explain what the expected results for various inputs should be: https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/transformations/transformers/seriesToColumns.test.ts

**Comment by kaydelaney** [comment]
cheers @hugohaggmark

**Comment by hugohaggmark** [comment]
> cheers @hugohaggmark

I hope it helps

**Comment by torkelo** [comment]
This transformer is currently rewrittten quite heavily in https://github.com/grafana/grafana/pull/24024

**Comment by torkelo** [comment]
looks to be fixed now that the better-labels PR was merged
