### ISSUE TITLE
Need modify the tag legend.

### ISSUE THREAD

**Issue by caoli5288** [grafana/grafana#2407]
Not supported yet.

**Comment by caoli5288** [comment]
![https://img.alicdn.com/imgextra/i1/176977352/TB2qBhSeXXXXXcwXXXXXXXXXXXX-176977352.png](https://img.alicdn.com/imgextra/i1/176977352/TB2qBhSeXXXXXcwXXXXXXXXXXXX-176977352.png)

**Comment by torkelo** [comment]
Might need to give you a medal for worst title and issue description yet. please specify grafana version and data source type and version.  Also show the data source query and response. All data sources have alias features to control series naming so unless you use a custom data source this is already implemented :)

**Comment by caoli5288** [comment]
Sorry. I use grafana 2.0.2 and influxdb 0.9.2. It has no legend alias func support for influxdb in this version but I found it exists in grafana-2.1-pre(Some graph panel fail when I update 2.1-pre from 2.0.2).
Thank you for your great project.
