### ISSUE TITLE
Exporting templated dashboard

### ISSUE THREAD

**Issue by slnowak** [grafana/grafana#2408]
Right now, if i want to export templated dashboard, produced json is a snapshot of that dashboard at a certain point of time.
Now, after reimporting that dashboard I can see repeated panels even for non existing metrics. Not to mention there might be new metric matching template variable query. In such a case, it won't be visible on the screen. 

If templating is used, shouldn't exporting a dashboard produce only some kind of templated, populated again on import?

**Comment by torkelo** [comment]
when importing a dashboard with templating enabled and repeat panels or rows it will look the same as when you exported it. Not sure what you mean for "non exisiting metrics", did you change a variable value or anthing in the json between export and import?

**Comment by slnowak** [comment]
Suppose you have set of metrics:
commonPrefix.metric1.suffix
commonPrefix.metric2.suffix
and so on.

In my case, number of metrics will change int time. 
And now I have templated dashboard, with repeated panels and templating variable written in the way it matches the metric name.

Now, assume before exporting the dashboard you have the following set of metrics: {metric1, metric2, metric3}. But after import it changes to {metric2, metric4}
I expect grafana to automatically refresh metrics set and rebuild repeated panels according to it.

**Comment by newpcraft** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
최중연(choe.jungyeon@naverc...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [grafana] Exporting templated dashboard (#2408)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
최중연(choe.jungyeon@naverc...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-07-30 00:00 ~ 2015-07-30 23:59 GMT +09:00]<br>7/30(목) 휴가 입니다. NDOT/NPOT 문의는 조지원 대리님께 부탁드립니다.
--------------------------------------------

**Comment by torkelo** [comment]
Is the template variable set to refresh on load? what is the value of the template variable? Is it set to All and you export it, then new metrics appear, and then you import it and you do not get the new metrics? 

Can you describe the template variable and how you configured it and what value it has when you export it.

**Comment by slnowak** [comment]
Ok, I think I missed the 'refresh on load' property. So it should do the 
trick, right?

And one more thing: is there any way to pass variable pointing to 
'current' dashboard as parameter to another dashboard?
Suppose your dashboard has variable var = {all, a, b, c, d}.
Now you have a panel with "title": $var and multiple values selected at 
the same time. It works correctly, as title is properly resolved. But if 
I pass $var to another dashboard, then I pass all selected values, where 
as I'm interested in'current' one.

W dniu 29.07.2015 o 18:22, Torkel Ödegaard pisze:

**Comment by torkelo** [comment]
not sure I understand what you you mean 'current', when you link to another dashboard you can include the current selected state of all template variables.

**Comment by slnowak** [comment]
Ok, one last try ;)
Let's say I have variable: queueName and repeated panel for each 
selected queue.
Now, I would like each panel to has link to another dashboard: 
another-dashboard?queueName=$queueName.
But if I have more than one queueName selected at the time, then 
creating such detailed view is impossible. But somehow it works with 
using queueName variable as a dashboard title.


W dniu 29.07.2015 o 21:22, Torkel Ödegaard pisze:

**Comment by torkelo** [comment]
you mean the panel links / drilldown link feature?

**Comment by slnowak** [comment]
Yeah. I was only able to pass all selected options for given variable. But I would like to pass only the one corresponding to repeated panel I'm focused on.

**Comment by torkelo** [comment]
@slnowak I see, opened a new issue for that, and fixed it! 
https://github.com/grafana/grafana/issues/2410

**Comment by slnowak** [comment]
Thanks!
The only way to get latest build is to clone repo and build yourself, right?
Or dose this dockerfile https://github.com/grafana/grafana-docker/blob/master/Dockerfile fetches master?

**Comment by torkelo** [comment]
@slnowak there are now new builds at http://grafana.org/download/builds.html

**Comment by slnowak** [comment]
@torkelo Any chances for .deb package? :) And when grafana_latest_amd64.deb will be updated?

**Comment by torkelo** [comment]
hm.. strange deb package build failed for some reason, will investigate

**Comment by slnowak** [comment]
@torkelo Thanks.
