### ISSUE TITLE
Save dashboard failure and pop up a 403 forbidden alert

### ISSUE THREAD

**Issue by mzxboy** [grafana/grafana#24082]
**What happened**:
Make some changes on dashboard, and click "Save dashboard" button. Then it won't save the changes and pop up an alert show 403 forbidden. Any changes can't be saved.

![image](https://user-images.githubusercontent.com/26425861/80697522-a5c0d280-8b0b-11ea-9419-f16ca65c4d99.png)

![image](https://user-images.githubusercontent.com/26425861/80697984-621a9880-8b0c-11ea-889e-a000d8b5ec67.png)

**What you expected to happen**:
The changes of dashboard would be saved.

**How to reproduce it (as minimally and precisely as possible)**:
Make some changes on dashboard, and click "Save dashboard" button.

**Anything else we need to know?**:
I use chrome web browser to inspect the website, and click the save button. The inspect console showed an error "POST https://mywebsite.com/api/dashboards/db/ 403"

**Environment**:
- Grafana version: 6.2.4
- Data source type & version: Prometheus v2.9.2
- OS Grafana is installed on: ubuntu 18.04 (aws ec2 instance)
- User OS & Browser: MacOS 10.15.4 & Chrome 81.0
- Grafana plugins: yesoreyeram-boomtable-panel
- Others:

**Comment by torkelo** [comment]
Maybe you have some proxy in-front of grafana that returns a html 403 response?

**Comment by mzxboy** [comment]
Hi torkelo, I use docker-compose to run my grafana with prometheus, alert-manager, node-exporter. I didn't run any in-front-proxy for grafana. Is there anything I can do to provide more details? Thanks.

**Comment by papagian** [comment]
You grafana version is really old. Can you try with a newer one?

**Comment by mzxboy** [comment]
[Resolved] Sorry, the error is not from Grafana. The error message "403 Forbidden" I got is responded by AWS WAF because the post body is over-sized. Thank you all for the responses.

**Comment by zimbombo** [comment]
> [Resolved] Sorry, the error is not from Grafana. The error message "403 Forbidden" I got is responded by AWS WAF because the post body is over-sized. Thank you all for the responses.

Hi mzxboy. Im running into the same problem. How did you solve in then?

**Comment by mzxboy** [comment]
Edit the rule of AWS WAL rule to allow the request.

**Comment by zimbombo** [comment]
Sorry Im kinda new to the AWS world. We got it working. Thanks a lot!

**Comment by ashokgadeking** [comment]
@michael-hsieh-tw Did you modify the size constraint or add the path as a waf exception?

**Comment by michael-hsieh-tw** [comment]
Yes, I add the path as waf exception
