### ISSUE TITLE
Table: Ability to hide fields but still reference them in data links

### ISSUE THREAD

**Issue by adriankumpf** [grafana/grafana#24092]
**What would you like to be added**:

I would like the ability to hide fields from the table but still reference them in data links.

**Why is this needed**:

First of all, I really like the new Table component. Thanks for the great work!

While migrating some dashboards from the old table to the new one I noticed that the new table component lacks one feature: When adding a data link via a field override it does not allow referencing filtered fields, for example `http://example.com?foo=${__data.fields.foo}` where `foo` was hidden by the "Filter by name" or "Organize fields" transformation.

I would like the ability to hide fields from the table but still reference them in data links, for example by adding a field override property "Hide" or by having the ability to reference filtered fields.

**Environment:**

  * Grafana version: 7.0.0-beta1

**Comment by dprokop** [comment]
@adriankumpf thank you for your warm words! We have been thinking about the same thing - I'm gonna classify this as a feature request and add to our backlog.

**Comment by nckswt** [comment]
Just came to try to see what was being done about this as well. 

This feature (bug?) is blocking our transition to Grafana 7.0, since we had the same number of visible and hidden columns in many of our tables, but now have to show several garbage columns to get the same link functionality out. 

Hope 7.1 gets released soon, or this is brought in earlier as a bugfix! :crossed_fingers:

**Comment by bhozar** [comment]
This is one of the last two features (the other being multi-line text wrapping) I need to migrate all my table panels to the new table panel.

**Comment by rupankrishnarrk** [comment]
This is a show stopper for us to consume Grafana 7, with out being able to use hidden fields as data link is a way back of Windows 91. Unfortunately all good features in Grafana 7 are hanging fruits in sky, with no way of upgrade for us with current state of garbage data with hidden columns.

**Comment by arifmca09** [comment]
Team,

It is honestly amazing work. Excited to use new features, but loosing the Data Link capability with Hidden fields is blocking me to enjoy this thriller. Please add this back, after all this should not stop the appreciations towards the real hard work been done.

Thanks a lot.

**Comment by loblab** [comment]
Really need this feature. When will it be available? Thanks.

**Comment by joostmelchers** [comment]
For those that will accept a hacky way to solve this problem, you might want to set the column width of the variable you want to hide to 1. You can then reference it and it is not noticable in the panel. (Setting the column width to 0 was not possible unfortunately)

**Comment by DrMichael** [comment]
Good idea, but it leaves still the field with column width of about 55 pixels for me...
![2020-09-01 13_03_17-Window](https://user-images.githubusercontent.com/8087682/91842164-d187cc80-ec53-11ea-9858-58438f34c57e.png)

**Comment by joostmelchers** [comment]
Hmmm, I see. Change the order of the columns such that your hidden columns are at the end. This has been my case and it looked acceptable.

**Comment by pr1malc0de** [comment]
Any ideas when this may make into release? Im running 7.2.0 and i cant hide fields without losing access to the data they hold

**Comment by PavelPikat** [comment]
@pr1malc0de I think there is milestone set for 7.3

**Comment by ilude** [comment]
Could I ask that if you are going to continue to push this back indefinitely that you update the docs to acknowledge this limitation? I just wasted several hours trying to port an old table to the new format.

**Comment by FireEmerald** [comment]
As the milestone 7.3.0-beta1 was assigned and the closed 12 days ago, is this feature already implemented in the beta? It would be a really important feature...

**Comment by davewat** [comment]
Would this be better supported by:
- table panel supports column width=0 -> hidden
- when selecting a column as hidden in Organize Field transform, an override for that field is automatically added, with column width=0
?

Note that the table doesn't appear to support column width=0 ATM.

**Comment by hairyhenderson** [comment]
> As the milestone 7.3.0-beta1 was assigned and closed 12 days ago,

@FireEmerald the milestone was switched to 7.4.0 14 days ago 😅

**Comment by FireEmerald** [comment]
So the issue was first added to milestone 7.1, then to 7.2 moved to 7.3 and now to 7.4. Hopefully the "max-move" count is at 4 🙈

**Comment by jcdauchy-moodys** [comment]
Hope this gets fixed in 7.4, as many of us are waiting for this to be able to use the new 7.x Panels. We are stuck in old panels 👎

**Comment by PavelPikat** [comment]
True. v7 is non-existing for us as well until this feature is re-implemented there

**Comment by DrMichael** [comment]
True, same here.

And, it appears, that you cannot have the table sorted by hidden fields?!?!

**Comment by yoda-koda** [comment]
Just updated to 7.3 today in production. For now using the column width of 1 workaround, but definitely not ideal. Hoping this is functional in 7.4.

**Comment by skrabadiloseidon** [comment]
Hope this is getting fixed, table plugin is useless in current state.

**Comment by jcdauchy-moodys** [comment]
Any chance to get it fixed in the coming release ?

Thanks

**Comment by DrMichael** [comment]
Again asked for in https://community.grafana.com/t/additional-column-only-for-data-links/42197/6

**Comment by DrMichael** [comment]
Wow, does this mean, this is postponed until 8.0.0?!?!? For when is that release planned?

**Comment by kilaviljenn** [comment]
We'd like to have this feature, too. We have quite some tables where we build data links from hidden columns. 
Just showing the columns is no option since this would display so much unneeded data.

**Comment by xepozz** [comment]
Any news?

**Comment by x-merlin-x** [comment]
Still missing in 7.5.1

**Comment by barry-luijten** [comment]
> The draft code has been stale since June. I was wondering if this would be better supported by:
> 
> * add table panel support for column width=0 (resulting in the column being hidden)
> * when selecting a column as hidden in Organize Field transform, an override for that field is automatically added, with column width=0.  This would **actually** hide the field, as expected, rather than remove it.
>   ?
> 
> Note that the table doesn't appear to support column width=0 ATM.

As a workaround, I'm assigning a width of -1 to the columns containing ref-ids, which prevents them from being shown initially, but they are still visible when scrolling to the right. width=0 would be more intuitive and better looking of course ;)

**Comment by DrMichael** [comment]
@dprokop I cannot find it in https://github.com/grafana/grafana/milestone/203?closed=1...

**Comment by dprokop** [comment]
@DrMichael it's not implemented yet. It's been moved to the beta2 milestone. The milestone you are linking is the one that has been released yesterday.

**Comment by DrMichael** [comment]
Ah, I see, it was pushed to beta2... Any chance to have that indeed implemented then?

**Comment by jcdauchy-moodys** [comment]
> Ah, I see, it was pushed to beta2... Any chance to have that indeed implemented then?

I guess it is a MUST for 8.0.0 so it will be included, hopefully.

**Comment by DrMichael** [comment]
Please. It is holding us back from migration to the new table for quite some dashboards...

**Comment by KotovAnton** [comment]
Grafana team, realese it, please!

**Comment by kale1d0code** [comment]
Are there any release channels which have this feature enabled?
Don't mind running some reports on a beta release etc along as I can use this

**Comment by alanreay** [comment]
Does this ⬆️  mean it will releasing soon?  Could really use this feature!  Right now we don't have some columns linked in favor of keeping the table clean.

**Comment by ideasman69** [comment]
I just hit into this too... have an ID number I want to pass as a varible but hidden from table view

**Comment by vemod** [comment]
this affects gauge panel as well. e.g. i need to show current and max values in the gauge. this creates 2 gauges. one with half full and one with max full. since max is auto-calculated i need to hide max query in order to show single gauge with properly max value. cannot override query to hide :(

**Comment by Grrrolf** [comment]
Hello @torkelo, this ticket/issue supposed be a duplicate for issue/ticket #37185 (Allow values of hidden column(s) to be used in data links). Now it seems that it was not an exact duplicate as this ticket (#24092) mentions using an 'override' to hide a column while my ticket mentions transform/organize fields/hide. The result is now that the filed issue (#37185) is not fixed, yet the ticket is closed. 

Should I create a new issue/ticket using the information from ticket #37185 or is it possible that you can re-open the ticket?

**Comment by torkelo** [comment]
@Grrrolf we cannot solve this with the organize fields, it filters out the field so it cannot be used in datalinks. You have to use an override to visually hide it using the new display hide option

**Comment by Grrrolf** [comment]
Thank you @torkelo. If this is the case, then I do not mind if the 'eye' icon to hide a column will be removed from the transform / organize fields menu. This prevents confusion in the future.

Best thing is, we're about to upgrade to 8.3.4 and we can then use hidden columns again for data links! Thank you (and everyone @ Grafana Labs) so much for this.

**Comment by reuvygroovy** [comment]
I'm lost. Has this been fixed? In 8.5 it still seems to be a problem, where when using Organize field and the 'eye' icon is used to hide the field, it doesn't allow you to use a hidden field

**Comment by FireEmerald** [comment]
@reuvygroovy Have you tried [this](https://github.com/grafana/azure-data-explorer-datasource/issues/96#issuecomment-1046227635)?

**Comment by torkelo** [comment]
@reuvygroovy there is an option in table, when you add a field override there is an option called "Hide in table" , this allows you to hide fields while still accessing them in data links 
![Screenshot from 2022-06-15 09-09-42](https://user-images.githubusercontent.com/10999/173765017-03c49def-2488-44a7-b3a3-62fb6c666261.png)

**Comment by ffisc** [comment]
Doesn't seem to work for timeseries plots, right?

**Comment by dannotes** [comment]
Version 10.2.0, 'Hide in table' is not showing in 'Bar Gauge' also I cannot use the hidden column in data links. Any suggestions?

**Comment by mmonaco** [comment]
> Doesn't seem to work for timeseries plots, right?

No, I don't think so, which is disappointing. I have a workaround with a postgresql query:

 - Select **Table** format
 - Include the additional column in SELECT clause
 - Add a **Partition by values** transformation
 - Choose a column (or columns) as the **Field** that you do want to retain as labels
 - Choose **Naming: As label**

**Comment by piotrbo** [comment]
> Version 10.2.0, 'Hide in table' is not showing in 'Bar Gauge' also I cannot use the hidden column in data links. Any suggestions?

The same for 'Status history' visualisation, there is no such option.
 I see 'Hide in area' instead, but then again data link cannot use a hidden field
