### ISSUE TITLE
Dashboard search: search in filter by tag is not working

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/grafana#24098]
**What happened**:
In the `Filter by tag` field, if I type something to search for a tag, it doesn't filter tags on my input.

**What you expected to happen**:
Be able to search for tag in the `Filter by tag` field

**How to reproduce it (as minimally and precisely as possible)**:
Type something in the `Filter by tag` field. The issue is reproducible on the demo environment: https://play.grafana.org/dashboard.

**Environment**:
- Grafana version: 7.0.0-beta1
- User OS & Browser: Windows, tested on Firefox and Chrome

**Comment by Clarity-89** [comment]
Good catch! I'd also add to that the tag list itself isn't filtered when the search query is changing, always showing the initial tags and the amount of results for them.
