### ISSUE TITLE
Bug: Panel links does not scope variables when used in repeated panel (templating) 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2410]

**Comment by slnowak** [comment]
I believe it still doesn't work properly.
Here's my panel:
![screen shot 2015-07-30 at 11 51 30 am](https://cloud.githubusercontent.com/assets/5739345/8980491/66c49cbe-36b1-11e5-8dab-00a8594424b2.png)
I expect url to be queue?var-queue=ns.mailing.deadletter.queue, not queue?var-queue=ns.mailing.deadletter.queue&var-queue=ns.mailing.queue&var-queue=ns.mailing.untraceable.queue&var-queue=ns.mailing.waiting.queue

**Comment by torkelo** [comment]
your right, I only fixed the singlestat panel (which has a special feature that makes the whole panel act as a drilldown link), committed fix now for the panel link dropdown menu

**Comment by slnowak** [comment]
@torkelo Thank you once again. It would be great if you could also deploy tar/deb build :)

**Comment by torkelo** [comment]
still testing a fix for the build container (the builds are done in a centos 6.6 docker container on the build server to get a binary that works on as many linux dist/versions as possible)

**Comment by slnowak** [comment]
So I believe I can't do anything but waiting for it. Thanks.

**Comment by torkelo** [comment]
they should appear on the builds page in a few minutes

**Comment by slnowak** [comment]
And unfortunately, I'm still having the same issue.
Should the template dashboard created before and imported now be compatible with this fix?

**Comment by torkelo** [comment]
should not matter when the dashboard was created, the link is generated on the fly. 

Strange just verified that this works. Did you update to the latest package?

**Comment by slnowak** [comment]
Yes, I used 7/30/2015, 12:22:12 PM build.
I will check it again (maybe docker cached image or whatever) and let you know what happened.

**Comment by slnowak** [comment]
Sorry, that's my fault. I forgot to ad '--no-cache' to build my docker images. I believe it's working now ;)
