### ISSUE TITLE
EditPanel: Transformations dropdown goes up and under tab 

### ISSUE THREAD

**Issue by sakjur** [grafana/grafana#24107]
**What happened**:

When adding transformations with insufficient vertical space below the **+ Add transformations** button (forcing the options to be displayed above the button) some options disappears behind the tabs in the tab bar.

<img width="1152" alt="Screen Shot 2020-04-29 at 15 18 13" src="https://user-images.githubusercontent.com/298945/80720791-b5d1b580-8afd-11ea-9aee-750cba4ce12c.png">

**What you expected to happen**:

The dropdown is rendered above the tab bar/panel and all options are visible + selectable.

**How to reproduce it (as minimally and precisely as possible)**:

For any panel, have a small-ish vertical space for the transform tab in the edit panel view and try to add more transformations until the dropdown changes from being below the **+ Add transformations** button to being above it.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master @ 2e4a8d4d5a0cc28dfaaf38a3ec37e5a6f9ea3929 (2020-04-30T14:18Z)
- Data source type & version: any 
- OS Grafana is installed on: MacOS 10.15
- User OS & Browser: Safari 13.1 and Chrome 81
- Grafana plugins: -
- Others: -

**Comment by dprokop** [comment]
Failed fixing this so far:/
