### ISSUE TITLE
Support external authentication via passed-through headers

### ISSUE THREAD

**Issue by runningman84** [grafana/grafana#2411]
It would be great if we could use nginx/apache in front of grafana and pass the auth to grafana.

I could think of these headers
* X-Auth-User (bob)
* X-Auth-Org
* X-Auth-Level (Admin, Reader, ...)

This would allow us to handle the authentication outside of grafana.

**Comment by torkelo** [comment]
this is already implemented in Grafana 2.1 (upcoming release), 

https://github.com/grafana/grafana/issues/1921
https://github.com/grafana/grafana/issues/1921#issuecomment-98346727

**Comment by runningman84** [comment]
ok but the access level (admin, reader, ...) is not implemented?

**Comment by torkelo** [comment]
no, that is not part of the authentication system per say, the auth proxy part only identifies the user. User permission and org is handled in grafana by a org admin.

**Comment by torkelo** [comment]
But I can certainly see the case for headers for that as well, but trickier to implement that in a performant way (needs some caching, cant sync org and user permission on every request). But not that hard, would welcome a PR. not likely something I will work on unless many request it.
