### ISSUE TITLE
Graphite: Add stddevSeries function to function def list

### ISSUE THREAD

**Issue by vedranf** [grafana/grafana#2412]
Hello,

I can't find the stddevSeries() in the list of functions even though it's supported by the underlying graphite-api. Is it omitted by accident (in which case it should be added) or is the a reason? I'm also not seeing removeBetweenPercentile(), maybe a couple more as well.

Thanks,
Vedran

**Comment by torkelo** [comment]
no, just no one has requested it added it / had use for it.  and removeBetweenPercentile is I think very new, it is not even in the pre release of 0.9.13

**Comment by machadolab** [comment]
I'd like to have stddevSeries too! It would have saved me quite a bit of time had I known this function even existed. Sad, but I've come to rely on grafana to show me what functions are available in graphite.

**Comment by bergquist** [comment]
stddevSeries have been added
