### ISSUE TITLE
stat panel edit mode jumps to top of page

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#24138]
**What happened**:

* Select panel > Edit
* Set panel type to `stat`
* Configure an option in "Display", such as "justify mode"
* Scroll will jump to top of page

**What you expected to happen**:

Position on page does not move when pressing buttons

**How to reproduce it (as minimally and precisely as possible)**:

Following the steps above reliably reproduces for me. If not for others let me know and I can try to get a more consistent reproduction

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0-beta1
- Data source type & version: prometheus
- OS Grafana is installed on: docker image on kubernetes
- User OS & Browser: linux chrome 81
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
thanks for reporting this! Fix incoming
