### ISSUE TITLE
explore: ctrl+z does not undo 

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#24137]
**What happened**:

In "Explore" in the query bar, I typed a word, then deleted it with ctrl+backspace. I then pressed ctrl+z, expecting it to undo the deletion but nothing happened.

**What you expected to happen**:

ctrl+z behaves like most text inputs

**How to reproduce it (as minimally and precisely as possible)**:

Described above. See env below

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0-beta1
- Data source type & version: Prometheus
- OS Grafana is installed on: docker image with tag `7.0.0-beta1` on Kubernetes
- User OS & Browser: Linux Chrome 81
- Grafana plugins:
- Others:

**Comment by Mario-Hofstaetter** [comment]
I was about to create an issue for this. 

Not just `Explore` but `Query`-Editor of Panels to. 

This is a VERY useful feature when editing querys.
@papagian  The behavior has changed from Grafana 6.7, so in my opinion not a `feature-request` but a bug?

## `v6.7.3` 
![wSdsedbv7q](https://user-images.githubusercontent.com/33002073/81502264-3ef6a280-92dd-11ea-9ac8-ca71c6b1596b.gif)

## `v7.0.0-beta3`
![tpKuKiAPa6](https://user-images.githubusercontent.com/33002073/81502301-76654f00-92dd-11ea-8455-7769d67e9ca8.gif)

When viewing the dashboard, `Ctrl+Z` does trigger `Zoom out` , although that is supposed to be `t`+`z`:
![grafik](https://user-images.githubusercontent.com/33002073/81502354-bb898100-92dd-11ea-9a03-87349dfc8ee0.png)

Maybe this cancels the undo action.
