### ISSUE TITLE
Docker: avoid apt-get upgrade and apk upgrade

### ISSUE THREAD

**Issue by J0WI** [grafana/grafana#24132]
**What would you like to be added**:
Upgrading existing packages in a container is an anti pattern, so the instruction should be removed.

https://github.com/grafana/grafana/blob/04ed8801f675780efdd848fe7d8b090525d1281b/packaging/docker/ubuntu.Dockerfile#L31
https://github.com/grafana/grafana/blob/04ed8801f675780efdd848fe7d8b090525d1281b/Dockerfile#L55
https://github.com/grafana/grafana/blob/04ed8801f675780efdd848fe7d8b090525d1281b/Dockerfile.ubuntu#L53
https://github.com/grafana/grafana/blob/04ed8801f675780efdd848fe7d8b090525d1281b/packaging/docker/Dockerfile#L27
https://github.com/grafana/grafana/blob/04ed8801f675780efdd848fe7d8b090525d1281b/packaging/docker/Dockerfile#L31

**Why is this needed**:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
Docker images are based on layers. If an update of a preinstalled package is needed the best practice would be to pull the newest version of the base image and rebuild the image against it. Images from the [docker library](https://github.com/grafana/grafana/issues/12899) are usually updated regularly and rebuild automatically if the base have been updated.

**Comment by wwuck** [comment]
@aknuds1 should this change be reverted?  Docker, OWASP, and hadolint have all recently removed their recommendations against updating packages in Dockerfiles.

https://github.com/hadolint/hadolint/issues/562#issuecomment-806869952
https://github.com/OWASP/CheatSheetSeries/pull/614#issuecomment-806209720
https://github.com/docker/docker.github.io/pull/12571

**Comment by aknuds1** [comment]
@wwuck thanks for the update - do you know if there are canonical sources of advice on the matter?

**Comment by wwuck** [comment]
@aknuds1 I just noticed this when I was reading the [hadolint releases changelog](https://github.com/hadolint/hadolint/releases/tag/v2.2.0).  Not being a docker expert, I guess the most "official" source that I can find would be the [docker pull request](https://github.com/docker/docker.github.io/pull/12571) removing the advice to not do upgrades from their best-practices documentation.  There isn't much discussion on the PR though, but the fact that it was approved and merged should be enough?

**Comment by aknuds1** [comment]
@wwuck thanks, we will look into it. Dockerfile best practices are difficult to determine.

**Comment by wwuck** [comment]
@aknuds1 This article at https://pythonspeed.com/articles/security-updates-in-docker/ also gives some compelling reasons for running upgrade inside the Dockerfile.

**Comment by J0WI** [comment]
If you upgrade an existing package you will end up with both versions in the image if you don't squash the layers

**Comment by wwuck** [comment]
@J0WI Looking at https://github.com/moby/moby/issues/34565 it looks like squash could be removed at some point, and the Docker devs are recommending multi-stage builds instead?
