### ISSUE TITLE
Multiple grafana instances

### ISSUE THREAD

**Issue by cschotke** [grafana/grafana#2414]
Is it possible to install multiple active instances of Grafana which share the same dashboards and configs? This was easy in 1.x because all dashboards were stored centrally in elasticsearch. Are there any options for doing this with 2.x? 

Thanks

**Comment by warmfusion** [comment]
You could do the same and point at a common MySQL/Postgres backend?

**Comment by torkelo** [comment]
yes, configure grafana to use Mysql or Postgres as database
