### ISSUE TITLE
stats panel: edit preview different data format than final format

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#24140]
**What happened**:
I tried to use the stats panel. During the edit preview, the result is different than the final display.

Edit mode:
![2020-30-04_15-58-10](https://user-images.githubusercontent.com/623453/80766954-7e620980-8afb-11ea-816f-91f85ba7439c.png)

Once applied:
![2020-30-04_15-58-20](https://user-images.githubusercontent.com/623453/80766960-81f59080-8afb-11ea-945c-9e794753bf7d.png)

The primary difference here is the conditional coloring is wrong in the preview, and the format is wrong once applied

**What you expected to happen**:
I would expect it to be green and `100%` in both cases, or at least consistent

**How to reproduce it (as minimally and precisely as possible)**:

<details>

```json
{
  "datasource": "Prometheus",
  "cacheTimeout": null,
  "gridPos": {
    "h": 3,
    "w": 6,
    "x": 6,
    "y": 3
  },
  "id": 21,
  "links": [],
  "targets": [
    {
      "expr": "sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"destination\"}[1m]))",
      "format": "time_series",
      "intervalFactor": 1,
      "refId": "A",
      "step": 4
    }
  ],
  "title": "Global Success Rate (non-5xx responses)",
  "type": "stat",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "percentunit",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "rgba(245, 54, 54, 0.9)"
          },
          {
            "value": 95,
            "color": "rgba(237, 129, 40, 0.89)"
          },
          {
            "value": 99,
            "color": "rgba(50, 172, 45, 0.97)"
          }
        ]
      },
      "mappings": [
        {
          "op": "=",
          "text": "N/A",
          "value": "null",
          "id": 0,
          "type": 1
        }
      ],
      "nullValueMode": "connected"
    },
    "overrides": []
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "mean"
      ]
    },
    "orientation": "horizontal",
    "colorMode": "value",
    "graphMode": "area",
    "justifyMode": "auto",
    "fieldOptions": {
      "calcs": [
        "mean"
      ]
    }
  },
  "pluginVersion": "7.0.0-beta1"
}
```

</details>

Apply this panel ^

**Anything else we need to know?**:

**Environment**:

Grafana version: 7.0.0-beta1
Data source type & version: Prometheus
OS Grafana is installed on: docker image with tag 7.0.0-beta1 on Kubernetes
User OS & Browser: Linux Chrome 81
Grafana plugins:
Others:

**Comment by torkelo** [comment]
Thanks for reporting this!
