### ISSUE TITLE
Add "Open in new tab" option to Dashboard List

### ISSUE THREAD

**Issue by solry** [grafana/grafana#24155]
**What would you like to be added**: "Open in new tab" option to Dashboard List

**Why is this needed**: Similar to Navigation Links, it would be really convenient to have this feature as it would improve the user experience for cases when a user wants to open a number of dashboards from a Dashboard List.
This option is supported for Navigation Links: https://grafana.com/docs/grafana/latest/features/dashboard/links/#navigation-links 
But not supported in DashList panel:
https://grafana.com/docs/grafana/latest/features/panels/dashlist/

**Comment by torkelo** [comment]
they are normal links, just ctrl/cmd click :)

**Comment by solry** [comment]
@torkelo Sure they are, as well as Navigation Links. I just thought that maybe it is worth to make functionality more consistent across Navigations Links and Dashboard List.

**Comment by torkelo** [comment]
For navigation links it makes a bit more sense as you can linking to external system with those.
