### ISSUE TITLE
influx 0.9 - when using a regex for a metric name, tag autocompletion fails

### ISSUE THREAD

**Issue by mivok** [grafana/grafana#2415]
This is with the latest build at the time of writing - 2.1.0-pre1 built on 7/21/2015.

If you use a regular expression for a metric name (e.g. `SELECT mean(value) FROM /cpu.*/`), then click on the + next to the WHERE clause, no tag keys or values appear in the dropdown (influx may also throw an error if you have an escaped backslash (`\/`) in the metric name's regex). It appears that the query sent to influxdb includes double quotes (") around the metric name, e.g. `SHOW TAG KEYS FROM "/cpu.*/" ...`. If I query influx manually with the same query without the double quotes, it works fine.

This is possibly related to #2373.

**Comment by torkelo** [comment]
Thanks for reporting this! will fix asap

**Comment by torkelo** [comment]
fixed
