### ISSUE TITLE
Alias Pattern Behavior for InfluxDB 9

### ISSUE THREAD

**Issue by jgerschk** [grafana/grafana#2416]
Could not find details other than how to use these, but I see some strange, correct, maybe incorrect behavior within Grafana when trying to use influx 9.0 and alias patterns.

Take a look at the screenshots.  The "native editor" does not work, won't even register the fact that I have a host tag.

![does_not_work](https://cloud.githubusercontent.com/assets/7864285/9000194/48007f16-3709-11e5-8a17-35a08668be7d.png)

However, if you change to inline editor (raw), it works as I would expect (sort of, adds an extra line to graph something), sure I have to add "host" to the select statement, but that seems like a valid way to address what you are displaying?

![working_tags](https://cloud.githubusercontent.com/assets/7864285/9000205/67aa973e-3709-11e5-8030-39f33a471aae.png)

Thoughts, comments, am I doing something wrong?

**Comment by torkelo** [comment]
If host is a tag it should be in the group by clause if you want it in the series name (not the select clause) the editor select clause only lists field fetched from influxdb

**Comment by torkelo** [comment]
oh and rhe duplicate series is a influxdb bug

**Comment by torkelo** [comment]
let me know if you find anything else strange, but I do not think this is a bug (why I closed it).

**Comment by jgerschk** [comment]
Well, that was the part I was missing, was blind and did not see the + in the group by to add host, thus I could not figure out how that was working.  

You are correct, no bug here -- just silly user driving. :)

Thanks @torkelo!
