### ISSUE TITLE
Elasticsearch: Raw document query render raw JSON documents in each row in the new table panel

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#24163]
**What happened**:
Raw document query render raw JSON documents in each row in the new table panel.

![image](https://user-images.githubusercontent.com/1668778/80816835-89d33480-8bd0-11ea-8884-640fc74d26ff.png)

**What you expected to happen**:
Each property in raw JSON to be displayed as a column as with the "old table panel".

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1&editPanel=5
2. Switch to the "new table panel"
3. Table shows raw JSON documents in each row

**Environment**:
- Grafana version: v7.0.0-beta1
- Data source type & version: Elasticsearch

**Comment by torkelo** [comment]
Wonder if a way to solve this would be to add a new metric option "Document" as a way preserve old Raw document behavior in old panels

**Comment by michael-az** [comment]
Another way of solving this is adding the "Table Transform: JSON Data" from the old table panel as a new transformation (like "Label to fields" but for json instead of labels). The needed colums can then be selected with the "Organize fields" transformation.

![Screenshot](https://user-images.githubusercontent.com/57443891/85581035-88f0d900-b63c-11ea-8580-076932e6022f.png)

**Comment by luipir** [comment]
@marefr is it related only to Elasticsearch? or it's a more generic lack of Transform modifier? I face this issue because I've a table expressed as JSON returned by a query. Is there a workaround to manage this JSON to express table layout and data?

**Comment by luipir** [comment]
well obviously I do not want to activate JS hability in the Text/HTML to create the table basing of the JSON.

**Comment by luipir** [comment]
@ivanahuckova still do not understand why json parsing to dataframe is something related only to ElastincSearch and it des not belong to the DataSource provider base class as pure virtual. A method to parse/map json to dataframe woudl be fine fior every datasource

**Comment by ivanahuckova** [comment]
Hello @luipir, this PR was related just to Elasticsearch. There might be a usecase for more/all data sources and if that would be something useful for you, please feel free to open an [Enhancement request issue](https://github.com/grafana/grafana/issues/new?labels=type%3A+feature+request&template=2-feature_request.md). However, in this case, we have decided to fix this problem this way for 2 reasons:
1. Before 7.0, with the old table panel, this was working just by selecting Raw Document. For 7.0+ we would like to keep the same behaviour, so the user doesn't have to fix/alternate data in additional settings/transformations. To keep it backward compatible, we have considered several options and decided for this. 
2. Elastic is used in Explore where we are not providing table settings/transformations. Therefore fix needed to be applicable for Explore view as well.

**Comment by luipir** [comment]
ok, legitimate decisions, thx for the explanation.

I would open a PR, but, in this moment, I do not have enough global view to be sure to create a coherent feature request.
IMHO seems this a request since time reading community forum.
