### ISSUE TITLE
BarGauge is missing Field and Threshold config in v7.0.0-beta1

### ISSUE THREAD

**Issue by knoguchi** [grafana/grafana#24178]
**What happened**:
I'm testing the BarGauge panel in v7.0.0-beta1.  There is the Display config but the Field and Threshold configs are missing.

**What you expected to happen**:
In Grafana v6.4.4 there are Display, Field and Threshold configs. I expect the same in v7.

**Environment**:
- Grafana version: v7.0.0-beta1 (413aaf26d7)
- OS Grafana is installed on: Ubuntu Linux
- User OS & Browser:  Chrome on Mac
- Grafana plugins: BarGauge

**Comment by ryantxu** [comment]
Are you seeing something different than this? 
![image](https://user-images.githubusercontent.com/705951/80852555-6ca56280-8bde-11ea-9d63-44d320f2450e.png)

Note the field and threshold in the lower right

**Comment by knoguchi** [comment]
Oh thanks! I was able to locate the Field and Overrides in a dropdown.  The tabs in your screenshot is a much better UI.
