### ISSUE TITLE
local access to embedded panels / remote panel times out

### ISSUE THREAD

**Issue by Maddin2000** [grafana/grafana#24173]
**What happened**:
Hey! I can embedd panels on my website and see them while I'm in the network. Out of network the html times out.

**What you expected to happen**:
I just want to see the panel and/or the link to the panel on my website, but it isn't working. 

**How to reproduce it (as minimally and precisely as possible)**:
Changed in grafana.ini: cookie samesite: none / allow embedding true (deleted ; and restarted grafana). The Port forwarding ist working for Port 80 and 3000 (where grafana still is).

the Panel should appear on the index.html:

<!DOCTYPE html>
 <html lang="de">
 <head>
 <title>xxx</title>
 <meta http-equiv="content-type" content="text/html; charset=utf-8" />
 <link rel="stylesheet" href="style.css" type="text/css" />
 </head>
 
 <body>
   
   <P><CENTER>Embed</CENTER>
   <iframe src="http://192.168.1.48:3000/d-solo/AaqAtriRk/luftdb?orgId=1&refresh=1m&from=1588149773417&to=1588322573418&panelId=8" width="800" height="400" frameborder="0"></iframe>
   <HR>   

   <P><CENTER>Snapshot</CENTER>
   <iframe src="http://localhost:3000/dashboard/snapshot/VRxTBq2BK1IMrKTwWunbCbU38UwiMm4l" width="800" height="400" frameborder="0"></iframe>
   <HR>   

   <P><CENTER>link</CENTER>
   <iframe src="http://192.168.1.48:3000/d/AaqAtriRk/luftdb?orgId=1&refresh=1m&from=1588150073053&to=1588322873053&panelId=8&fullscreen" width="800" height="400" frameborder="0"></iframe>
   <HR>   

 </body>
 </html>

**Anything else we need to know?**:
As you probably already think, I'm new here... sorry!

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Apache2, PHP7, mysql 10, phpmyadmin,
- OS Grafana is installed on: Raspberry pi, Raspbian GNU/Linux 10 (buster)
- User OS & Browser: Raspberry pi, firefox, dynDNS with no-IP
- Grafana plugins: -
- Others: Router o2 HomeBox 6441

**Comment by papagian** [comment]
Can you explain more "Out of network the html times out"? Do you mean the embedding is working when your site is running on the same machine with grafana but not when they are running on different?

Also, can you share your grafana server logs?

**Comment by Maddin2000** [comment]
Hey! I see the embedded panel and the link on my Laptop when I'm in my home network, where the raspberry pi with the mysql db and the Grafana is located. When I'm in another network, like at work or the hotspot of my phone, I'll get the time-Out message at the panels location. 
Next I'll send the server logs.

**Comment by Maddin2000** [comment]
t=2020-05-02T05:17:53+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=209.17.96.34 time_ms=1 size=29 referer=
t=2020-05-02T09:31:50+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/label/__name__/values remote_addr=192.168.1.217 referer="http:/$
t=2020-05-02T09:31:50+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/label/__name__/values status=502 remote_addr=192.168.1.217$
t=2020-05-02T09:31:50+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/metadata remote_addr=192.168.1.217 referer="http://192.168.1.48$
t=2020-05-02T09:31:50+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/metadata status=502 remote_addr=192.168.1.217 time_ms=3 si$
t=2020-05-02T10:19:25+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=CONNECT path= status=404 remote_addr=45.13.93.90 time_ms=16 size=26196 referer=
t=2020-05-02T11:48:42+0200 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped UsageStatsService" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped PluginManager" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped CleanUpService" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped NotificationService" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped RemoteCache" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped BackendPluginManager" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped AlertEngine" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped UserAuthTokenService" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped Stream Manager"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped InternalMetricsService" logger=server reason="context canceled"
t=2020-05-02T11:48:42+0200 lvl=info msg="Stopped provisioningServiceImpl" logger=server reason="context canceled"
t=2020-05-02T11:48:59+0200 lvl=info msg="Starting Grafana" logger=server version=6.7.3 commit=a04ef6cefc branch=HEAD compiled=2020-04-23T12:12:53+0200
t=2020-05-02T11:48:59+0200 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-05-02T11:48:59+0200 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-05-02T11:48:59+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2020-05-02T11:48:59+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2020-05-02T11:48:59+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2020-05-02T11:48:59+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2020-05-02T11:48:59+0200 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-05-02T11:48:59+0200 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-05-02T11:48:59+0200 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-05-02T11:48:59+0200 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-05-02T11:48:59+0200 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-05-02T11:48:59+0200 lvl=info msg="App mode production" logger=settings
t=2020-05-02T11:48:59+0200 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=758
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing SqlStore" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-05-02T11:48:59+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing HTTPServer" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing BackendPluginManager" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing PluginManager" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing HooksService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing OSSLicensingService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing RemoteCache" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing RenderingService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing AlertEngine" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing QuotaService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing ServerLockService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing UserAuthTokenService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing DatasourceCacheService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing LoginService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing SearchService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing TracingService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing UsageStatsService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing CleanUpService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing NotificationService" logger=server
t=2020-05-02T11:48:59+0200 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2020-05-02T11:49:00+0200 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
t=2020-05-02T11:49:00+0200 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. Read more at https://graf$
t=2020-05-02T11:49:00+0200 lvl=info msg="Initializing Stream Manager"
t=2020-05-02T11:49:00+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-05-02T14:36:26+0200 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped UsageStatsService" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped PluginManager" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped CleanUpService" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped RemoteCache" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped UserAuthTokenService" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped Stream Manager"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped provisioningServiceImpl" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped NotificationService" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped BackendPluginManager" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped InternalMetricsService" logger=server reason="context canceled"
t=2020-05-02T14:36:26+0200 lvl=info msg="Stopped AlertEngine" logger=server reason="context canceled"
t=2020-05-02T14:36:40+0200 lvl=info msg="Starting Grafana" logger=server version=6.7.3 commit=a04ef6cefc branch=HEAD compiled=2020-04-23T12:12:53+0200
t=2020-05-02T14:36:40+0200 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-05-02T14:36:40+0200 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-05-02T14:36:40+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2020-05-02T14:36:40+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2020-05-02T14:36:40+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2020-05-02T14:36:40+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2020-05-02T14:36:40+0200 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-05-02T14:36:40+0200 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-05-02T14:36:40+0200 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-05-02T14:36:40+0200 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-05-02T14:36:40+0200 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-05-02T14:36:40+0200 lvl=info msg="App mode production" logger=settings
t=2020-05-02T14:36:40+0200 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=689
t=2020-05-02T14:36:40+0200 lvl=info msg="Initializing SqlStore" logger=server
t=2020-05-02T14:36:40+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-05-02T14:36:40+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2020-05-02T14:36:40+0200 lvl=info msg="Initializing HTTPServer" logger=server
t=2020-05-02T14:36:40+0200 lvl=info msg="Initializing BackendPluginManager" logger=server
t=2020-05-02T14:36:40+0200 lvl=info msg="Initializing PluginManager" logger=server
t=2020-05-02T14:36:40+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing HooksService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing OSSLicensingService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing RemoteCache" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing RenderingService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing AlertEngine" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing QuotaService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing ServerLockService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing UserAuthTokenService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing DatasourceCacheService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing LoginService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing SearchService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing TracingService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing UsageStatsService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing CleanUpService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing NotificationService" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2020-05-02T14:36:41+0200 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
t=2020-05-02T14:36:41+0200 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. Read more at https://graf$
t=2020-05-02T14:36:41+0200 lvl=info msg="Initializing Stream Manager"
t=2020-05-02T14:36:41+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=

**Comment by Maddin2000** [comment]
![grafanaini](https://user-images.githubusercontent.com/64660857/80872310-5fa57380-8cb1-11ea-8cfd-bb9ca988914d.jpg)

**Comment by papagian** [comment]
The problem is that you get a `Data proxy error`. Which datasource you use for your panel and how you have configured it?

**Comment by Maddin2000** [comment]
I use mysql on the port 3306. should this port be forwarded as well? This doesn't work, why ever...
The configuration is the default config of grafana.
![Unbenannt](https://user-images.githubusercontent.com/64660857/80955278-4f9baa00-8dff-11ea-952d-883e30e02eb2.PNG)


other environment:
Grafana version: 6.7.3
Data source type & version: Apache2, PHP7, mysql 10, phpmyadmin,
OS Grafana is installed on: Raspberry pi, Raspbian GNU/Linux 10 (buster)
User OS & Browser: Raspberry pi, firefox, dynDNS with no-IP
Grafana plugins: -
Others: Router o2 HomeBox 6441

**Comment by Maddin2000** [comment]
I don't know if you still here me, but I keep trying :)
Thanks for the hint with the data proxy error. I researched a lot, but I don't get behind it. Some people seeme to have the same issue, but the answer don't help me either... Can you tell me what might be missing here? I'm a total newbie, so purhaps something general I forgot?

**Comment by papagian** [comment]
What kind of authentication are you using for grafana? Basic auth or anonymous access? If it's basic can you try to login to grafana first before loading your site.
Also, you can ask for help in our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by jessabe** [comment]
A bit more information that could be helpful; Can you access Grafana directly when trying to access it from outside your home network? Or does it give you the same errors? How are you accessing your home network? Do you have a VPN (Virtual Private Network)? I see external IPs and Internal IPs within the log, and the 502s suggest that there's some bad comms happening within your proxy.

**Comment by Maddin2000** [comment]
@papagian I enabled the anonymous access, but still no change. I'm logged in in Grafana at my home network, but don't get a panel to see from outside the network. Thank for the advice for the Grafana community, I'll try that as well!

@jessabe I can't (yet) access Grafana from outside my network and I have no VPN. Actually I have my Raspberry Pi, where the everything is running, and a laptop to acces the pi remotely. I created a Website via dynDNS with no-ip.

The page is no secret: http://luftmaster.ddns.net/
The website looks in my network like this
![Unbenannt](https://user-images.githubusercontent.com/64660857/82372565-79b6b400-9a1c-11ea-94b9-98442f1c20ff.JPG)

**Comment by jessabe** [comment]
Hi again,

I see in the code that you have set your local IPs as the source. Externally, your networks will not be able to find this, unless you're accessing it via a VPN that is tied to your home network. Private IP distinctions are usually 192.168.*.* on home networks. You might have better help asking or searching the community about how they access their home networks from outside. I'm sure this is a pretty common scenario.

Best of luck!

**Comment by Maddin2000** [comment]
Ok! Thanks so far for your help!!
