### ISSUE TITLE
When create Global Users with POST /api/admin/users, ignores OrgId if supplied

### ISSUE THREAD

**Issue by Tranceh2** [grafana/grafana#24180]
**What happened**:

When I create a new user with the Admin API and supply the OrgId parameter, it is ignored and the new user is added to the Main Org organization that has ID = 1

**What you expected to happen**:

I expected that if I indicate the ID of another Organization in the OrgId parameter, the user will be created with that assigned organization and not the ID = 1.
Documentation indicates the Following: " Note that OrgId is an optional parameter that can be used to assign a new user to a different organization when auto_assign_org is set to true ." https://grafana.com/docs/grafana/latest/http_api/admin/#global-users

**How to reproduce it (as minimally and precisely as possible)**:

Send a POST /api/admin/users request to Grafana, with body: 
```json
{
  "name":"User",
  "email":"user@graf.com",
  "login":"user",
  "password":"userpassword",
  "OrgId": 10
}
```
Where "OrgId = 10" indicates the id of another organization other than the Main Org

**Anything else we need to know?**:

I have the option "auto_assign_org" set to true.

**Environment**:
- Grafana version: 6.7.3
- Data source type & version:
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: -
- Grafana plugins:
  - yesoreyeram-boomtable-panel
  - grafana-piechart-panel
  - simpod-json-datasource
- Others:

**Comment by papagian** [comment]
This is only available since grafana v7.0.0-beta1.
