### ISSUE TITLE
DashboardListPanel: Starred (default setting) items not visible to 'anonymous'

### ISSUE THREAD

**Issue by kkruzich** [grafana/grafana#24183]
**What happened**: 1) Set '[auth.anonymous] enabled = true' in grafana.ini 2) Verify visibility of Grafana without login 3) With admin login, create DashListPanel on Home page, set to show Starred dashboards. 4) Verify admin can see Starred dashboards 5) Verify anonymous can see Starred dashboards in the same DashListPanel.

**What you expected to happen**: Expected anonymous to see Starred dashboards in DashListPanel.

**How to reproduce it (as minimally and precisely as possible)**: With admin login, create DashListPanel on Home page, set to show Starred dashboards. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Reproduced in 6.7.3 and 6.2.5
- Data source type & version: n/a
- OS Grafana is installed on: CentOS 7.6
- User OS & Browser: macOS 10.15.3, Firefox 75, Brave 1.8.86
- Grafana plugins: alexanderzobnin-zabbix-app/  fatcloud-windrose-panel/	      grafana-clock-panel/     mtanda-histogram-panel/	neocat-cal-heatmap-panel/
andig-darksky-datasource/    fetzerch-sunandmoon-datasource/  grafana-piechart-panel/  natel-plotly-panel/	raintank-worldping-app/
- Others: n/a

**Comment by torkelo** [comment]
Started  dashboard is a user specific action (to have user spect favorites )

Not available for anonymous users as there is no user  , same with other user preferences
