### ISSUE TITLE
Alerting: Allow multiple URL of Prometheus alertmanager for high availability setup

### ISSUE THREAD

**Issue by alistarle** [grafana/grafana#24195]
**What would you like to be added**: Allow multiple url of alertmanager instances comma-separated in the notifier settings.

**Why is this needed**: As specified in Prometheus Alermanager documentation for [high-availability](https://prometheus.io/docs/alerting/alertmanager/#high-availability):

> It's important not to load balance traffic between Prometheus and its Alertmanagers, but instead, point Prometheus to a list of all Alertmanagers.

As Grafana act as a client for Alertmanager like prometheus does, Grafana must implement the same logic in the notifier.

Currently, putting a single URL or a load balancer URL for Alertmanager endpoint in grafana notifier config will produce divergence between all alertmanager instances.

**Comment by alecorps** [comment]
Really needful improvement
