### ISSUE TITLE
Getting a double quoted string using a single-valued template variable postgres

### ISSUE THREAD

**Issue by Harsha-vardhan30** [grafana/grafana#24194]
**What happened**:
I was trying to use a single-valued template variable which is one among the generated ones from a query on Postgres. I wanted to use it as a part of a statement like WHERE col_name = $var . But $var was giving me a string surrounded by double quotes instead of single quotes. I looked many issues around this (from the past) and it looked like they had some fixes (am not sure). The postgres docs at https://grafana.com/docs/grafana/latest/features/datasources/postgres/ says "From Grafana 4.7.0, template variable values are only quoted when the template variable is a multi-value" which I find to be incorrect. I also tried disabling the quotes by trying ${var:csv} but I think this is only to be used to remove the quotes for a multi-valued case I guess. Finally it worked when I changed it from single-valued template variable to multi valued template variable and only chose a single value.

**What you expected to happen**:
I was expecting $var to give me wrapped by single quotes in case of a single-valued template variable. (I know this expectation is not justified because in some other query $var might represent a name of the table. So I think in the best scenario it should generate no quotes)  

**Anything else we need to know?**:
When the panel can't fetch data, the log message shown is decapitalised I think. So if the actual data was say 'Value' it shows 'value' doesn't exist with its case changed. I initially thought this was because may be the data fetch was changing the case. I believe that's only a problem in displaying the message on browser and would be great if it can be fixed too.

**Environment**:
- Grafana version: Version 6.7.3 (a04ef6cefc)
- Data source type & version: Postgres
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome

**Comment by papagian** [comment]
The reason that single-value variables are not wrapped in quotes is, as you say, that the variable can potentially be used for column or table selection. So either you have to use a multi-value variable as you do or you can add the quotes in the query yourself.

For example, if I have a single-value variable `host` the query:
````
SELECT
  $__timeGroup("createdAt",'$summarize'),
  avg(value) as "value",
  hostname as "metric"
FROM 
  grafana_metric
WHERE
  $__timeFilter("createdAt") AND
  measurement = 'logins.count' AND
  hostname IN('$host')
GROUP BY time, metric
ORDER BY time
```

will become:

```
SELECT
  floor(extract(epoch from "createdAt")/60)*60 AS "time",
  avg(value) as "value",
  hostname as "metric"
FROM 
  grafana_metric
WHERE
  "createdAt" BETWEEN '2020-05-04T06:33:43.088Z' AND '2020-05-04T07:33:43.088Z' AND
  measurement = 'logins.count' AND
  hostname IN('server1')
GROUP BY time, metric
ORDER BY time
```

which is valid Postgres query
