### ISSUE TITLE
Way to copy a graph's graphite png URL to clipboard, for easy sharing

### ISSUE THREAD

**Issue by petemounce** [grafana/grafana#242]
We share charts all the time during operations.  We use HipChat, which has a feature where if a link is pasted that will render an image, it thumbnails it and embeds it into the chatstream - this is really nice because it gives context to the discussion/investigation.

We do this by right-clicking on the chart, grabbing the image URL, and appending `&format=png` to it, then pasting into chat.

With grafana, this is still possible, but requires 4-5 clicks 
* edit the chart
* display styles
* render as PNG
* right-click
* copy image URL
* append `&format=png`
* paste to chat

It would be great to be able to speed this flow up, in grafana, so we could get the whole URL to paste directly from a dashboard, without needing to edit the chart, and from a chart in edit-mode.

**Comment by torkelo** [comment]
Implemeted in Grafana 2.0 with Grafanas own panel to png rendering
