### ISSUE TITLE
v7.0.0-beta1: Data link stop working in table panel when changed to LCD 

### ISSUE THREAD

**Issue by paregupt** [grafana/grafana#24206]
**What happened**: Data link stop working when visulation changed to LCD in table panel

**What you expected to happen**: LCD should be click-able

**How to reproduce it (as minimally and precisely as possible)**: Add data link to a field. Use auto. The link works. Now change to LCD. Can't be clicked anymore.

**Anything else we need to know?**:

**Environment**:
- Grafana version:v7.0.0-beta1
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: CentOS 7.6
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None
- Others:

Great work, overall on v7.

**Comment by torkelo** [comment]
data links are not supported in table panel for all cell display modes
