### ISSUE TITLE
Fullscreen kiosk mode dashboard?

### ISSUE THREAD

**Issue by wrouesnel** [grafana/grafana#2420]
I have a number of hud monitors around that are booted automatically and load a fullscreen web-browser. 

Ideally I'd like to load to a fullscreen dashboard without the grafana header or any controls, and sized to the monitor size (though I suppose this could be optional) but there doesn't presently seem to be a way to accomplish this via the GUI.

**Comment by nopzor1200** [comment]
Grafana automatically sizes your panel width based on your screen resolution.

Each row has a width of 12 and the row will expand to take up your entire screen resolution. So for example, if you have a panel with a width of 3 it'll take up 1/4 of your browser screen width. If your data source supports MaxDataPoints then you'll use all of the available pixels in the panel (again, dependent on your resolution) to render your metrics. If your screen is (say) 4000+ pixels wide that'll be (almost) 1000+ datapoints per panel. Optimal data density for big screens.

The side bar can be toggled on and off with the Grafana icon on the top left.

Unlike the width of the panel, the vertical size is hard coded in pixels. Is this what you mean? 

You are correct that the top header cannot be turned off currently. In your use case, do you have no need for the date picker or seeing the time range of the dashboard?

In your use case, do you use the playlist feature?

**Comment by wrouesnel** [comment]
The time range is shown by the individual graphs in my use and the monitors themselves are just huds mounted high up so no one is directly interacting with them.

The problem is indeed with the vertical size - I'd like to be able to set the proportions of the graphs and have a single dash expand to consume the vertical screen space (and have as much of it as possible in view).

I haven't experimented with playlist s but in general wouldn't use them for this since the idea is to show important metrics which need to be monitored - if we can afford to not see it, we can afford to alert off it and ignore it otherwise.

**Comment by nopzor1200** [comment]
I just wanted to clarify that you can indeed set the vertical size of each Panel explicitly (in pixels); you can also set the vertical size of each Row (again in pixels).

It's not automatic like the way panel width adjusts, but it should be possible to create the perfect dashboard to "consume the vertical screen space" of your HUD display.

Again, not automatic, but definitely possible and I just wanted to make doubly sure we were on the same page here.

Are you using repeating rows or panels? (that could complicate what I just said..)

**Comment by wrouesnel** [comment]
No repeating rows. But auto-sizing isn't really the central issue - the big one at the moment is you can't use URL params to configure the dashboard before it loads - i.e. I want to be able to pass something like `http://hostname.net/dashboard/db/cloud-hosting-status?fullscreen=1&notitlebar=1` and get a kiosk mode dashboard up.

**Comment by trondvh** [comment]
+1 for kiosk mode.

**Comment by grobie** [comment]
:+1:

**Comment by neurosys-zero** [comment]
+1

**Comment by kokarn** [comment]
:+1:

**Comment by savingschampion** [comment]
+1

**Comment by shoonoise** [comment]
+1

**Comment by mdevaev** [comment]
:+1:

**Comment by hanej** [comment]
+1

**Comment by joyhope** [comment]
+1

**Comment by AkoyaP6618** [comment]
+1

**Comment by verma** [comment]
:+1:

**Comment by poppgs** [comment]
+1

**Comment by ygbr** [comment]
+1

What I did so far for my standalone dashboards was hidding manually the top bar div by injecting CSS like:

```<div ng-include="" src="topNavPartial" class="ng-scope" style="display: none">```

we really could use an option to hide the top bar.

**Comment by evandro-portugal** [comment]
+1

**Comment by tgmpje** [comment]
+1

**Comment by vmtan** [comment]
+1

**Comment by devnore** [comment]
+1

**Comment by dR3b** [comment]
+1

**Comment by lovelaced** [comment]
+1

**Comment by jinfahua** [comment]
+1

**Comment by marcschumacher** [comment]
+1

**Comment by coussej** [comment]
+1

**Comment by jaganz** [comment]
+1

**Comment by seansean11** [comment]
+1

**Comment by ffMathy** [comment]
Any news on this?

**Comment by hiro-su** [comment]
+1

**Comment by moooji** [comment]
+2

**Comment by tompoch** [comment]
+1

**Comment by melliott-sis** [comment]
+infinity

**Comment by bcronrath** [comment]
Are there plans to implement this?  Would love to be able to remove the top bar especially for embedding these graphs on websites.

**Comment by grobie** [comment]
I'd love to be able to remove the annotation boxes in kiosk mode.

**Comment by thomaso-mirodin** [comment]
As a workaround in the meantime, I ended up creating an html text panel at the bottom of my dashboards with this content:

```html
<button>Toggle</button>

<script>
// Hide the navbar on load
$("navbar").hide();

// On button click, toggle navbar visibility
$("button").click(function(){
    $("navbar").toggle();
});
</script>
```

**Comment by tompoch** [comment]
We are actually about to implement an app plugin which will contain single page which will
- just display the dashboard passed as url parameter
- will not display templates
- will also contain the code above so that the navbar will be hidden.

Do you think it is possible to reuse some angular directives or code from the main grafana dashboard page? Thanks

**Comment by cruiser607** [comment]
+1 would love to be able to hide all unnecessary controls (top bar etc) for a kiosk mode.

**Comment by louwandre90** [comment]
+1

**Comment by marccardinal** [comment]
+1 and @thomaso-mirodin 's workaround is great for now!

**Comment by JorritSalverda** [comment]
It would make sense to able to support the following as well for optimal use on big screens without interaction

- refresh as soon as the dashboard config changes
- refresh template variables at a regular interval, so repeated panels show up when the variable changes
- provide unauthenticated hard to guess links to be able to display the dashboard without needing to log in

**Comment by louisdcoulombe** [comment]
+1, would be a great addition for TV projection or read-only projection

**Comment by wociscz** [comment]
navbar.hide is great workaround, but there is another problem after that - you couldn't change time range without top bar :-) because there is no templating support for timerange variables yet (there are some opened issues about this).
You should interact with timerange only with mouse and keyboard - which is not as user-friendly as direct links.

**Comment by discordianfish** [comment]
@torkelo You have specific thoughts on this? This seems pretty straight-forward, right?

**Comment by torkelo** [comment]
kiosk mode (that hides the top nav completely) is implemented in master now via this issue
https://github.com/grafana/grafana/issues/6476 

You toggle the kiosk mode with `d k` (sequence shortcut). There is also a view mode that Grafana switches to automatically after 2 min of user inactivity, the view mode hides some dashboard row & nav controls and the nav background fades out, perfekt for wall screens where you never care about the share, star & save icons, but do care about the dashboard name and dashboard time range. 

https://twitter.com/torkelo/status/794896092026568704/video/1

**Comment by toddwh50** [comment]
I still can't see how to get the Template variables to hide by adding a URL param (like "?hide-variables=true"), going into Kiosk mode, or letting the page time-out into "view mode".

Related tickets are:
#4110 - closed in favor of #2420 which doesn't seem to had the template variables part of the page.
#4395 - closed in favor of #4154 which doesn't seem to accomplish it (it just allows hiding of individual variables, not toggling of the template variables during display)

It seems that the template variables information might still be useful to see in View mode, but it takes a lot of valuable vertical space (especially if the qty of variables is small), maybe an idea is to move the template variables up into the header when in View mode as depicted below:

![image](https://cloud.githubusercontent.com/assets/17885456/20222220/10abfbf4-a7fa-11e6-86c1-ff36027dea5a.png)

**Comment by mattttt** [comment]
Also consider that area is shared by Annotations (next to Template Variables) and Dashboard Links on the right side.

**Comment by toddwh50** [comment]
Ah, two features we're not yet using, so I don't know how/where they would appear.

It would still be nice to get that vertical space back, but I see the issue.

I still wish there was some way to hide that horizontal band (where template variables, annotations, links appear) via a URL param so we had the option of hiding it on our "on-the-wall" dashboards.

**Comment by wardboumans** [comment]
Was really happy when I read kiosk mode was released. But im still struggling with the Template vars. Its just the space I need to make it all fit, I need scroll down the height of the templating bar (every morning).

**Comment by bergquist** [comment]
@wardboumans You could hide the template variable in the dashboard.
![image](https://cloud.githubusercontent.com/assets/618863/21602115/fd537aa8-d190-11e6-8c54-6da8968009c6.png)

**Comment by wardboumans** [comment]
@bergquist Ah nice! But hides them altogether correct? Edit and Kiosk mode.

**Comment by torkelo** [comment]
@wardboumans yes

**Comment by mikich** [comment]
I'd like to have this option as a plugin! Does anyone succeed to create one?
