### ISSUE TITLE
Transforms: transforms do not show all series

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#24209]
1. Create a new dashboard
2. Add new panel
3. Choose Test Data as data source
4. Choose CSV Metric Values and accept default values
5. Copy the above row 3 times
6. Change to Transforms tab
7. Choose Reduce or Filter by Name or Filter by refId or Organize fields, 
8. Expect to see all series but I see only A-series [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80938498-a3939800-8dd9-11ea-839f-082df5cae5d0.png)
![image](https://user-images.githubusercontent.com/562238/80938329-fe78bf80-8dd8-11ea-88e2-0348359e9c70.png)
![image](https://user-images.githubusercontent.com/562238/80938471-89f25080-8dd9-11ea-836e-836e838ed294.png)

**Comment by ryantxu** [comment]
This should be fixed by:
https://github.com/grafana/grafana/pull/24024

(though it is a bit of a long road!)

**Comment by torkelo** [comment]
This is due to copy row does not issue query (which is correct), have to hit refresh to get data results for new queries
