### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sw0x2A** [grafana/grafana#24214]
**What happened**:

An unexpected error happens when searching in /explore for a short string with a big result set like "gc". The datasource is Prometheus.

JS console shows error:

```QueryRow will unmount
react-dom.production.min.js:196 RangeError: Maximum call stack size exceeded
    at typeahead.ts:11
    at Array.reduce (<anonymous>)
    at ie (typeahead.ts:6)
    at t.n.componentDidUpdate (Typeahead.tsx:75)
    at bs (react-dom.production.min.js:251)
    at e.unstable_runWithPriority (scheduler.production.min.js:18)
    at Hi (react-dom.production.min.js:120)
    at ms (react-dom.production.min.js:244)
    at os (react-dom.production.min.js:223)
    at react-dom.production.min.js:121```

**What you expected to happen**:

 See list of time series that match the search pattern.

**How to reproduce it (as minimally and precisely as possible)**:

I guess this depends on the data in your datasource. Try short strings like "gc".

**Anything else we need to know?**:

**Environment**:
- Grafana version: Any 6.7.x is affected, 6.6.x is fine.
- Data source type & version: Prometheus 2.17.x, VictoriaMetrics 1.34.9
- OS Grafana is installed on: Linux, Ubuntu
- User OS & Browser: Mac OS X, Chrome
- Grafana plugins:
- Others:

**Comment by s-h-a-d-o-w** [comment]
We are currently implementing an off switch for autocomplete in the prometheus data source settings which can be used to avoid this and that should be done soon: https://github.com/grafana/grafana/pull/24034

Long-term, we might implement a smarter performance improvement which would possibly allow you to keep autocomplete enabled, although we would truncate metric names if we detect that we receive too many: https://github.com/grafana/grafana/pull/23811

**Comment by s-h-a-d-o-w** [comment]
@sw0x2A In 7.0, [you'll be able to "disable metrics lookup"](https://github.com/grafana/grafana/pull/24034) in the prometheus data source settings.

**Comment by teu** [comment]
Hi.

We add a lot of prometheus data sources (one per client) so we have autocomplete. The problem is that the aformentioned setting is not visible once the data source is added. Would it be possible to disable the lookup just for the import bit ?
