### ISSUE TITLE
Dashboards with alerts can't be saved in Grafana 7.0

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#24219]
**What happened**:

After I've created a dashboard with an alert in one of my panels, and click any icon in the sidebar, I get asked to save the dashboard. After I click Yes, and try to click an icon in the, it asks me to save the dashboard again.

**What you expected to happen**:

I expect the dashboard to be saved as usual.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a graph panel.
1. Add an alert to the panel.
1. Save and leave the dashboard.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0 beta 1
- Data source type & version:
- OS Grafana is installed on: Docker on macOS
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Unable to reproduce this in master.
