### ISSUE TITLE
Transfroms: add field from calculation crash

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#24210]
1. Create a new dashboard
2. Add new panel
3. Choose Test Data as data source
4. Choose CSV Metric Values and accept default values
5. Copy the above row 3 times
6. Change to Transforms tab
7. Click on Refresh dashboard button so all added series show up
8. Click on B-series button, B-series is accentuated in Graph but not really sure what the expected result is here as Graph is the same as before click[MIGTH BE OK]
![image](https://user-images.githubusercontent.com/562238/80938908-1bae8d80-8ddb-11ea-83d3-4db59873b9e1.png)
![image](https://user-images.githubusercontent.com/562238/80938852-ea35c200-8dda-11ea-92cf-beee35fbf41f.png)
9. Change from Total to Last in calculation field select, Panel Editor crashes [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80939001-60d2bf80-8ddb-11ea-8695-46f1e9648b2a.png)

**Comment by torkelo** [comment]
Looks to be fixed by https://github.com/grafana/grafana/pull/23978

**Comment by ryantxu** [comment]
This is fixed by #23978
![image](https://user-images.githubusercontent.com/705951/80999580-c2a22200-8df9-11ea-98e1-5182ed09f59b.png)

The awkward series names should be fixed by:
https://github.com/grafana/grafana/pull/24024
