### ISSUE TITLE
SQL injection in /api/tsdb/query in grafana

### ISSUE THREAD

**Issue by karunchinna** [grafana/grafana#24215]
Hi Team,

In Below example, how can restrict only select query in "rawSql"?
Now i can able to append any Sql query like drop, insert, delete and select.
this is kind of injection. how to make only read (means SELECT)?

?POST /api/tsdb/query HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "from": "1420066800000",
  "to": "1575845999999",
  "queries": [
    {
      "refId": "A",
      "intervalMs": 86400000,
      "maxDataPoints": 1092,
      "datasourceId": 86,
      "rawSql": "SELECT\n  time,\n  sum(opened) AS \"Opened\",\n  sum(closed) AS \"Closed\"\nFROM\n  issues_activity\nWHERE\n  $__unixEpochFilter(time) AND\n  period = 'm' AND\n  repo IN('grafana/grafana') AND\n  opened_by IN('Contributor','Grafana Labs')\nGROUP BY 1\nORDER BY 1\n",
      "format": "time_series"
    }
  ]
}

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

With SQL data sources you have to be careful to only allow user you connect to the database with is only granted select permission. Read docs for [Postgres](https://grafana.com/docs/grafana/latest/features/datasources/postgres/#database-user-permissions-important), [MySQL](https://grafana.com/docs/grafana/latest/features/datasources/mysql/#database-user-permissions-important) and [MSSQL](https://grafana.com/docs/grafana/latest/features/datasources/mssql/#database-user-permissions-important).

**Comment by karunchinna** [comment]
Thanks @marefr .

**Comment by alonek1** [comment]
🤔
Is this a valid sql injection bug !!?
then why it is closed marked as closed without solving the problem?

**Comment by boholder** [comment]
> 🤔 Is this a valid sql injection bug !!? then why it is closed marked as closed without solving the problem?

Yes, it's still a problem. This issue's community question link is:
https://community.grafana.com/t/sql-injection-in-api-tsdb-query-in-grafana/29713/6

And here is some information about "how hacker can do with a read-only DB user" and "sql injection with grafana":
https://stackoverflow.com/questions/1263218/if-my-database-user-is-read-only-why-do-i-need-to-worry-about-sql-injection
https://security.stackexchange.com/questions/86908/does-read-only-access-to-the-database-prevent-sql-injection
https://community.grafana.com/search?context=topic&context_id=24099&q=grafana%20sql%20injection&skip_context=true
