### ISSUE TITLE
Grafana server does not start after plugin installation on windows

### ISSUE THREAD

**Issue by tushar315** [grafana/grafana#24212]
**What happened**:I attempted to install the Pie Chart Panel plugin by following the instructions in the Pie Chart Panel page. I entered grafana-cli plugins install grafana-piechart-panel in the command line.

It gave me this error: Could not create ../data/plugins/grafana-piechart-panel/.circleci. Permission denied. Make sure you have write access to plugindir

So i went for another method
 I downloaded the zip and extracted it(grafana-piechart-panel) in data/plugin folder then the next step was to restart the grafana server but on running the command grafana-server restart i get a panic:runtime error
![image](https://user-images.githubusercontent.com/47667722/80947014-e6bb2e80-8e0c-11ea-961f-f90fad022b0a.png)

**What you expected to happen**:I expected it to work as instruction said and the plugin to be added on grafana

**How to reproduce it (as minimally and precisely as possible)**:same as above

**Anything else we need to know?**:I tried through windows powershell  as adminstrator but no use can you provide proper commands

**Environment**:
- Grafana version:6.5.1
- Data source type & version:Prometheus
- OS Grafana is installed on: Windows 10
- User OS & Browser:Chrome
- Grafana plugins:Pie chart
- Others:

**Comment by aknuds1** [comment]
Can you try this with the latest Grafana version, i.e. 6.7.3? Do you not see any more diagnostic info from the error?

**Comment by marefr** [comment]
Please run command prompt with administrator privileges and then try installing using grafana-cli.

**Comment by tushar315** [comment]
> Please run command prompt with administrator privileges and then try installing using grafana-cli.

It is installing this way but plugin does not appear on the dashboard i tried to restart the server by the command grafana-server restart because 'service grafana-server restart' is not a recognised.
So it gives me this 
[32mINFO[0m[05-05|09:40:37] Starting Grafana                         [32mlogger[0m=server [32mversion[0m=6.5.1 [32mcommit[0m=1763a0f [32mbranch[0m=HEAD [32mcompiled[0m=2019-11-28T13:13:49+0530
[32mINFO[0m[05-05|09:40:37] Config loaded from                       [32mlogger[0m=settings [32mfile[0m="C:\\Program Files\\GrafanaLabs\\grafana/conf/defaults.ini"
[32mINFO[0m[05-05|09:40:37] Path Home                                [32mlogger[0m=settings [32mpath[0m="C:\\Program Files\\GrafanaLabs\\grafana"
[32mINFO[0m[05-05|09:40:37] Path Data                                [32mlogger[0m=settings [32mpath[0m="C:\\Program Files\\GrafanaLabs\\grafana\\data"
[32mINFO[0m[05-05|09:40:37] Path Logs                                [32mlogger[0m=settings [32mpath[0m="C:\\Program Files\\GrafanaLabs\\grafana\\data\\log"
[32mINFO[0m[05-05|09:40:37] Path Plugins                             [32mlogger[0m=settings [32mpath[0m="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins"
[32mINFO[0m[05-05|09:40:37] Path Provisioning                        [32mlogger[0m=settings [32mpath[0m="C:\\Program Files\\GrafanaLabs\\grafana\\conf\\provisioning"
[32mINFO[0m[05-05|09:40:37] App mode production                      [32mlogger[0m=settings
[32mINFO[0m[05-05|09:40:37] Initializing SqlStore                    [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Connecting to DB                         [32mlogger[0m=sqlstore [32mdbtype[0m=sqlite3
[32mINFO[0m[05-05|09:40:37] Starting DB migration                    [32mlogger[0m=migrator
[32mINFO[0m[05-05|09:40:37] Initializing HTTPServer                  [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing OSSLicensingService         [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing SearchService               [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing RemoteCache                 [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing QuotaService                [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing ServerLockService           [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing UserAuthTokenService        [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing PluginManager               [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Starting plugin search                   [32mlogger[0m=plugins
[32mINFO[0m[05-05|09:40:37] Registering plugin                       [32mlogger[0m=plugins [32mname[0m="Pie Chart"
[32mINFO[0m[05-05|09:40:37] Initializing RenderingService            [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing AlertEngine                 [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing DatasourceCacheService      [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing HooksService                [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing LoginService                [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing InternalMetricsService      [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing TracingService              [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing UsageStatsService           [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing CleanUpService              [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing NotificationService         [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Initializing provisioningServiceImpl     [32mlogger[0m=server
[32mINFO[0m[05-05|09:40:37] Backend rendering via phantomJS          [32mlogger[0m=rendering
[33mWARN[0m[05-05|09:40:37] phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. [33mlogger[0m=rendering
[32mINFO[0m[05-05|09:40:37] Initializing Stream Manager
[31mEROR[0m[05-05|09:40:37] Stopped HTTPServer                       [31mlogger[0m=server [31mreason[0m="failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
[32mINFO[0m[05-05|09:40:37] Stopped Stream Manager
[32mINFO[0m[05-05|09:40:37] Stopped InternalMetricsService           [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped UserAuthTokenService             [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped RemoteCache                      [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped CleanUpService                   [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped NotificationService              [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped provisioningServiceImpl          [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped AlertEngine                      [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:37] Stopped UsageStatsService                [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[05-05|09:40:41] Stopped PluginManager                    [32mlogger[0m=server [32mreason[0m="context canceled"
[31mEROR[0m[05-05|09:40:41] A service failed                         [31mlogger[0m=server [31merr[0m="failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
[31mEROR[0m[05-05|09:40:41] Server shutdown                          [31mlogger[0m=server [31mreason[0m="failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

**Comment by aknuds1** [comment]
@tushar315 Your latest error from attempting to restart Grafana appears to be caused by another instance already running, and listening on port 3000. Please make sure no other application (including Grafana) is listening on port 3000 when you start Grafana server again.

**Comment by tushar315** [comment]
> @tushar315 Your latest error from attempting to restart Grafana appears to be caused by another instance already running, and listening on port 3000 ("failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted"). Please make sure no other application (including Grafana) is listening on port 3000 when you start Grafana server again.

yes that's why i mentioned the note ...should i end the grafana-server.exe through task manager? and will there be any loss in doing so?

**Comment by aknuds1** [comment]
I don't use Windows, so can't really advise on how to restart services, but at least rebooting your computer should do the trick. Have you tried this? For more support I would use the [community forums](https://community.grafana.com/).

**Comment by marefr** [comment]
@tushar315 I guess you have installed Grafana using the msi and then Grafana runs as a windows service. Quick Google gives me for example this: https://winaero.com/blog/start-stop-restart-service-windows-10/

**Comment by tushar315** [comment]
thanks but will restarting grafana this way lead to any loss in dashboard or any other field?

**Comment by marefr** [comment]
No

**Comment by adrobson** [comment]
I got this error when I did the install from command prompt but wasn't running the command prompt as an Administrator. To fix I stopped the service in Windows Services and then ran "Grafana-server.exe" from a command prompt as an Administrator and then I didn't get any errors.
