### ISSUE TITLE
Bug: LDAP Group Mappings

### ISSUE THREAD

**Issue by agilgur5** [grafana/grafana#2421]
Taken from #1450, Group Mappings seem to fail for my case.

My full mappings look like:

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"

Verbose logging prints:

    MemberOf: ([]string) (len=1 cap=1) {
      (string) (len=32) "CN=cls,DU=Lam Gps,DC=site,DC=com"
    }

The output and group mappings match (I even copy+pasted the output into my TOML), but I get mapped to Viewer for some reason.

Removing the Viewer group mapping entirely, resulting in a mapping like this:

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

I get an error now when I try to login: `Ldap Auth: user blah does not belong in any of the specified ldap groups`.

Then, when I remove the Admin group mapping, entirely, resulting in a mapping like this:

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

or if I change the ordering in the TOML to:

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

I login fine. So there seems to be two bugs; one that it matches Viewer instead of Editor, and the other that it fails when I have two roles and the first I don't match.

**Comment by torkelo** [comment]
as you verbose logging says the ldap server is only returning one ldap group member 
for this user, and that is not cls-admin

MemberOf: ([]string) (len=1 cap=1) {
  (string) (len=32) "CN=cls,DU=Lam Gps,DC=site,DC=com"
}

it is only a member of cls

`CN=cls,DU=Lam Gps,DC=site,DC=com != CN=cls-admin,DU=Lam Gps,DC=site,DC=com`

But the config where you had admin and editor mapping it should have matched the editor mapping so that error is strange.

**Comment by torkelo** [comment]
strange, i fail to replicate this. found some minor issues in the example config (server instead of servers in one of the mappings), but your config did have this.

**Comment by torkelo** [comment]
could you try this again, maybe with empty db, or with other user?

**Comment by agilgur5** [comment]
Yes, exactly it *should* have matched to the editor mapping but instead gave me that error. Yet changing the order made it work fine. I've replicated it with an empty db :/

I see you added a test for this case, so perhaps the previous fix (only match 1st mapping) resolved this? Could you upload the latest `.deb` package so that I can test that? Only the latest `tar.gz` is in builds

**Comment by torkelo** [comment]
@agilgur5 there is new deb packages now

**Comment by agilgur5** [comment]
Thanks @torkelo. Still having problems unfortunately.

Now, I with this mapping:

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"

I get matched to Viewer.

With this mapping:

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

I get `Ldap Auth: user blah does not belong in any of the specified ldap groups, ldapUser groups: [CN=cls,DU=Lam Gps,DC=site,DC=com]`

With this mapping:

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

I get matched to Viewer..... (What???)

With this mapping:

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

I get matched to Editor properly.

And with this mapping:

    [[servers.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"

I get matched to Editor properly.

This is running: `Version: 2.1.0, Commit: v2.1.0, Build date: 2015-08-04 14:19:48 +0000 UTC`
and each I tested with a fresh db. This bug seems to have gotten even more non-deterministic...

**Comment by torkelo** [comment]
@agilgur5 sorry cannot replicate any of your issues, works perfectly when I try the exact same config setup. 

```
[[servers.group_mappings]]
group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
```

I have ldap return "CN=cls,DU=Lam Gps,DC=site,DC=com",  when i login I get a user with Editor role. If i change to so ldap retuns the cls-admin group I will get matched to an Admin role (I have logout and login again to trigger role sync)

Your problem must lie in some strange ldap return charset or unicode that cant be seen in the log output. Or something else, i have no clue.

**Comment by torkelo** [comment]
you can see my attempt to replicate it here: https://github.com/grafana/grafana/commit/c0d2cad550614aae2657ec279c2490028c48974e

**Comment by agilgur5** [comment]
So I was really confused why you couldn't replicate it and stared pretty hard at my ldap.toml for a while and then realized my config actually looked like:

    [[servers.group_mappings]]
    group_dn = "CN=cls-admin,DU=Lam Gps,DC=site,DC=com"
    org_role = "Admin"

    # the editor role said server instead of servers
    [[server.group_mappings]]
    group_dn = "CN=cls,DU=Lam Gps,DC=site,DC=com"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"

So as not to reveal any information here, I edited the actual group_dns and had been copy+pasting `servers` even though I actually had `server` in my ldap.toml. When I changed the ordering while testing I actually hand-edited them vs. cutting and moving them, which is why the re-order worked.

...SO 6d6c9b7 actually fixed it! Thanks so much @torkelo for sticking it out with me on this one and thoroughly testing it... this was plaguing me for hours! :) 

Closing this out then. I'll send a PR for some docs updates now that I've had some heavy usage of the LDAP feature and everything works properly!

**Comment by torkelo** [comment]
That is great! I did not mention the config examples fix because  I could not see the issue in your examples
