### ISSUE TITLE
SaveDashboard: New dashboard doesn't ask for saving changes

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#24229]
**How to reproduce it (as minimally and precisely as possible)**:

Issues highlighted in **bold** :
1. Create new dashboard
2. Add panel
3. Click Grafana logo
4. Save changes **(user is not redirected to the destination.- home dashboard)**
5. Go back to home dashboard
6. Create new dashboard
7. Add panel
8. Click Grafana logo
9. **No save dashboard confirmation is shown**

**Environment**:
- Grafana version: master

**Comment by torkelo** [comment]
Think this works as it should, if your creating a new dashboard and choose to save it within the "unsaved changes" flow you will be redirected to the new saved dashboard

**Comment by dprokop** [comment]
@torkelo ok, if this is the flow then it's fine. but the second part (steps 5-9) are not working correctly I think.

**Comment by hugohaggmark** [comment]
I did a pass this morning and couldn't repro this. When you write `add panel` do you mean add panel and then immediately press back arrow?

**Comment by peterholmberg** [comment]
Can not reproduce this, reopen if this is still an issue
