### ISSUE TITLE
Select is cropped by the modal window

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#24228]
As seen in the dashboard save modal:

![image](https://user-images.githubusercontent.com/2376619/80962154-c7240600-8e0c-11ea-8c9a-474ca8225b05.png)

**Comment by torkelo** [comment]
should be easy to solve, not sure why modal body has overflow auto, that seems off

**Comment by tskarhed** [comment]
Related to @peterholmberg's issue with the new Getting started panel
![Screenshot from 2020-05-05 16-00-16](https://user-images.githubusercontent.com/1438972/81079758-3b83a580-8ef0-11ea-96ac-cb0d99b98f6e.png)
