### ISSUE TITLE
Radio groups sometimes require two mouse clicks

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#24222]
**What happened**:

When playing around with settings, sometimes the radio button doesn't respond to the mouse click.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a stat panel
1. In the Display section, change the value of any of the radio groups.
1. Seems to happen every at least every 12-14 change, but may happen before.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0 beta 1
- Data source type & version:
- OS Grafana is installed on: Docker on macOS
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Unable to replicate this, tried clicking a lot  (on linux + firefox)

**Comment by torkelo** [comment]
removing this from milestone & board and added awaiting more evidence, let's see if more get this problem

**Comment by marcusolsson** [comment]
Sorry about that. Updated to master, and can't seem to reproduce this anymore. I think this can be closed.
