### ISSUE TITLE
Calculate: add support difference between big counter values

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24233]
**What would you like to be added**:

Please, add difference calculation between current and previous values

![image](https://user-images.githubusercontent.com/2898361/80971367-7b8a5000-8e3e-11ea-8e1f-9ccc18792bc3.png)

**Why is this needed**:

Needs to calculate the difference between big counter values

![image](https://user-images.githubusercontent.com/2898361/80971754-08350e00-8e3f-11ea-8f2d-50c2d676dcb2.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
