### ISSUE TITLE
Elasticsearch alias with template variables not working as expected. 

### ISSUE THREAD

**Issue by cronosnull** [grafana/grafana#24239]
**What happened**:
When using templates variables to select the group by term and using an alias like {{term $variable}}, all the series will have the alias 'undefined'
**What you expected to happen**:
The alias will use the value of the selected group by term. 

**How to reproduce it (as minimally and precisely as possible)**:
On the templated Elasticsearch playground [1], creating a custom variable with the value `@hostname` and using it both in the terms group by and in the alias.
![image](https://user-images.githubusercontent.com/4405564/80979794-16c3fb00-8e28-11ea-943c-d5a3063b472c.png)
NOTE:  The error is only present when the template variable is used in the group by. (if I use @hostname as the term and use the variable in the alias, it works as expected).

**Anything else we need to know?**:

**Environment**:
- Grafana version: tested on 6.7.3 and 7.0.0-beta1
- Data source type & version: Elasticsearch 6.x, 7.x
- OS Grafana is installed on: Centos 7.x
- User OS & Browser: All. 
- Grafana plugins: All. 
[1] https://play.grafana.org/d/000000015/elasticsearch-templated?editPanel=1&orgId=1

**Comment by torkelo** [comment]
This working fine when I test: 
![Screenshot from 2020-05-04 21-23-21](https://user-images.githubusercontent.com/10999/81004968-8698ac80-8e4d-11ea-9dbc-c3095e415d74.png)

**Comment by cronosnull** [comment]
Hi @torkelo, 
Thanks for looking at it. The problem is when using the variable also in the group by terms. I've created a small video[1] showing the steps to reproduce it in the Elasticsearch templated dashboard in the playground. 

[1] https://youtu.be/tats8B2EZkQ

**Comment by janabr** [comment]
I am also facing a similar issue as reported here. Any updates on the investigations?

**Comment by beingyash** [comment]
Facing the same challenge. Any approximate timelines for the fix @Elfo404 ?

**Comment by Elfo404** [comment]
Small update: seems to work nicely with the linked PR, would be nice to do some manual testing around all-things-variables in elasticsearch to make sure nothing else is breaking.

<img width="1250" alt="Screenshot 2021-04-20 at 13 56 14" src="https://user-images.githubusercontent.com/1170767/115400849-a3a2c880-a1e1-11eb-975e-4f0f53cb7302.png">
