### ISSUE TITLE
Folder permissions inheriting to dashboards in it

### ISSUE THREAD

**Issue by Atomicbeast101** [grafana/grafana#24246]
**What happened**:
Setting different permission to a dashboard in a folder still prevents users from seeing the dashboard due to no access to the folder.

**What you expected to happen**:
Ability to see the folder itself and dashboards users should only have access to.

**How to reproduce it (as minimally and precisely as possible)**:
1. Assign a separate permission to a dashboard in a non-General folder.
2. Have user with that permission access Grafana to view list of folders.
3. Will not see the dashboard due to no access to the folder.

**Anything else we need to know?**:
I know this is possible with having different permission-based dashboards in General folder, but this is not feasible if you have a lot of dashboards you want to separate into different folders.

**Environment**:
- Grafana version: v6.7.2
- Data source type & version: Prometheus v2.17.1
- OS Grafana is installed on: Ubuntu v19.04
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: WorldPanel & PieChart along with default ones

**Comment by torkelo** [comment]
Looks like it's fixed in 7.0 / master

Can find a dashboard as a viewer who has no access on the folder but on one child dashboard

![Screenshot from 2020-05-04 20-27-41](https://user-images.githubusercontent.com/10999/80999942-c360a580-8e45-11ea-82f1-6282a0435f87.png)
