### ISSUE TITLE
Field Override Title does not work on Table Time Column

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#24245]
**What happened**:
Added Table Panel Field Override to Column `Time` of Query TestData DB / Random Walk Table,
Override Property `Title` is not a applied to the `Time` column, the other columns work fine.

**What you expected to happen**:
The Title of the `Time` column should als be overridden.

**How to reproduce it**:
- Add `Table` Panel, Use Datasource `TestData DB`, Choose Query `Random Walk Table`
- Add `Override` > `Filter by name` > Choose `Time`
- `Add Override Property` > `Title` > enter something
- The Title of `Time` is not changed, all other columns can be overridden

**Anything else we need to know?**:
See GIF:

![cant-override-time-column-title](https://user-images.githubusercontent.com/33002073/80996013-711c8600-8e3f-11ea-9132-ddcbb00b1c5e.gif)
 

**Environment**:
- Grafana version: `v7.0.0-beta1 (413aaf26d7)`
- Data source type & version: `TestData DB`
- OS Grafana is installed on: Windows 10 1909
- User OS & Browser: Windows 10 1909, Firefox 75
- Grafana plugins: New v7 Table Panel

**Comment by torkelo** [comment]
So easy to fix, we have explicitly made title not operate on time  
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/standardEditors.tsx#L48

Not question is why

**Comment by torkelo** [comment]
Think we can remove this condition: 
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/standardEditors.tsx#L48
