### ISSUE TITLE
Cloudwatch unable to create datasource using credential file

### ISSUE THREAD

**Issue by niraj8241** [grafana/grafana#24256]
**What happened**:
Trying to configure cloudwatch datasource on an on-prem system. Have installed AWS CLI and configure the required configs. I can access the services fine using multiple profiles that I have setup. But when I choose the Grafana's Cloudwatch Datasource and use the "Credential File" option I see that I am unable to get it to work and get the below error in logs:

`Failed to call cloudwatch:ListMetrics, NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"`

**What you expected to happen**:
I was expecting that I can configure cloudwatch on my system and create different datasources based on multiple profiles I have setup on my system.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup Grafana
2. Configure AWS CLI.
3. Configure multiple profiles
4. Choose Credential File Option in Cloudwatch Datasource
5. Specify the profile name to see if it works.

**Anything else we need to know?**:
I am using assume role when I configured AWS CLI. The default profile has a credential associated with it but the resulting profiles are assume roles in AWS. Something like below.

> [profile default]
> output = table
> region = us-east-1

> [profile prod]
> role_arn = arn:aws:iam::xxxxxxxxxx:role/Administrator
> output = json
> region = us-east-1
> source_profile = default

**Environment**: Production
- Grafana version: Grafana v6.7.2 (423a25fc32)
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: NA
- Others: NA

**Comment by dprokop** [comment]
@briangann can you please take a look at this one?

**Comment by bergquist** [comment]
@niraj8241 We fixed a similar issue in 7.0.0. Could you please try upgrading and see if the problem remains?

**Comment by daniellee** [comment]
No response from @niraj8241 so closing this issue. Can reopen if this is still an issue.
