### ISSUE TITLE
Stat view showing wrong titles (Repeating last title for all titles)

### ISSUE THREAD

**Issue by ysguy** [grafana/grafana#24260]
If i do a query like this

```
SELECT (
		Select '10'
		) as 'Ten'
		,(
		  Select  '20'
		) as 'Twenty'
		,(
		Select '30'
		) as 'Thirty'
		,(
			Select  '40'
		) as 'Forty'
		,(
			Select '50'
		) as 'Fifty'
```

It should (and did) make stat view tiles with each column being the title for each tile. In the latest revision, this doesnt work and the title of the last select is used for all the headings. 

FYI - V6.7.3 is the problematic version. was working before the upgrade. 

![image](https://user-images.githubusercontent.com/33327283/81008215-d2c4fc00-8e0f-11ea-821d-3aca9770623c.png)

Same select in table view works properly
![image](https://user-images.githubusercontent.com/33327283/81008396-1cade200-8e10-11ea-9711-c725fadf2356.png)

Bar, Gauge & Stat are all affected by this issue.

**Comment by torkelo** [comment]
It works if your query returns numeric values instead of strings, 

https://github.com/grafana/grafana/issues/23880

**Comment by ysguy** [comment]
I respectfully request this issue be reopened as it is not the same as the issue #23880. I am displaying numeric numbers, however the 'Title' is not correct from the query. casting the numbers to Int's / Decimal doesn't solve the problem. 

I'll provide some more detail.

Changing the query to 

`SELECT (
		Select cast('10'as int)
		) as 'Ten'
		,(
		  Select  cast('20' as int)
		) as 'Twenty'
		,(
		Select cast('30' as int)
		) as 'Thirty'
		,(
			Select  cast('40' as int)
		) as 'Forty'
		,(
			Select cast('50' as int)
		) as 'Fifty'`

Doesn't solve it. 

The same query in SQL looks like this: 

![image](https://user-images.githubusercontent.com/33327283/81083053-53880480-8eb1-11ea-92e0-ec3ff24e8448.png)

If i leave out the column headers, you can see that Grafana is pulling the variable of the last element instead of each. 
`SELECT (
		Select cast('10'as decimal)
		) 
		,(
		  Select  cast('20' as decimal)
		) 
		,(
		Select cast('30' as decimal)
		) 
		,(
			Select  cast('40' as decimal)
		) 
		,(
			Select cast('50' as decimal)
		) `

Resulting in

![image](https://user-images.githubusercontent.com/33327283/81083371-bb3e4f80-8eb1-11ea-8c96-9a248bfdb53b.png)
