### ISSUE TITLE
Gauge Threshold value and color code not set over REST API call

### ISSUE THREAD

**Issue by rahularora89** [grafana/grafana#24269]
**What happened**: If I set this in my gauge panel input for dashboard api while trying to create/update one:
Sample Input:
`{
			"datasource": "Elasticsearch_abc",
			"gridPos": {
				"h": 9,
				"w": 24,
				"x": 0,
				"y": 9
			},
			"height": 9,
			"id": 3,
			"options": {
				"fieldOptions": {
					"calcs": ["mean"],
					"defaults": {
						"max": 100,
						"min": 0,
						"thresholds": [{
							**"color": "red",**
							**"value": null**
						}, {
							**"color": "green",**
							**"value": 40**
						}]
					},
                    "override": {
                    },
                    "values": false
				},
				"orientation": "auto",
				"showThresholdLabels": false,
				"showThresholdMarkers": true
			},`

I still get this as the output response of the panel:
`{
      "datasource": "Elasticsearch_abc",
      "gridPos": {
        "h": 9,
        "w": 24,
        "x": 0,
        "y": 9
      },
      "height": 9,
      "id": 3,
      "options": {
        "fieldOptions": {
          "calcs": [
            "mean"
          ],
          "defaults": {
            "mappings": [],
            "max": 100,
            "min": 0,
            "thresholds": [
              {
                **"color": "green",
                "value": null**
              },
              {
                **"color": "red",
                "value": 80**
              }
            ]
          },
          "override": {},
          "values": false
        },
        "orientation": "auto",
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },`

**What you expected to happen**: The value and color code do not match in the output and input

**How to reproduce it (as minimally and precisely as possible)**: Just setup a request for creating/updating a dashboard with this api: /api/dashboards/db
Both produce the same result, 200 with incorrect values

**Environment**:
- Grafana version: v6.5.2
- Data source type & version: Elastic Search
- OS Grafana is installed on: Mac os
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Please update to a newer version, there have been some fixes related to defaults for thresholds that could help your case
