### ISSUE TITLE
Improve positional search term handling

### ISSUE THREAD

**Issue by lmuhlha** [grafana/grafana#24264]
**What would you like to be added**:

For example:

If there's a dashboard named  "TeamCity master queue metrics" and you search for "teamcity queue", one would expect the dashboard to come up. Instead you get 0 hits.

**Comment by sakjur** [comment]
Thank you for the feature request! Fuzzy search matching is something we've looked at for future releases of Grafana and we refactored search for 7.0 to make it easier for us to improve search with features like this going forward.
