### ISSUE TITLE
Table Panel: Auto scale font size works not enough on Cell display mode

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24270]
**What would you like to be added**:
Auto scale font size works not enough on Cell display mode -> Grandient 
if  Column width < 500

![image](https://user-images.githubusercontent.com/2898361/81033908-23436480-8eb7-11ea-95fa-f2f50cdc9db3.png)

**Why is this needed**:

correct scaling of font size like this:

![image](https://user-images.githubusercontent.com/2898361/81033946-40783300-8eb7-11ea-916d-e46b66593141.png)

**Comment by torkelo** [comment]
This should be fixed in 7.1
