### ISSUE TITLE
Transform/Filter by name throws Cannot read property 'subRows' of null  

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24274]
**What happened**:
![image](https://user-images.githubusercontent.com/2898361/81043154-8c38d580-8ed3-11ea-923f-2364e373e5e1.png)

**How to reproduce it (as minimally and precisely as possible)**:
Possible twice apply of Filter by name

**Environment**:
- Grafana version: 7.0 Beta1
- Data source type & version: SQLServer
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome

**Comment by hugohaggmark** [comment]
Hi @baur , I can't repro this using docker image for Grafana 7.0.0-beta1 and SQL Server datasource. Do you mind using the Panel Inspector to give us obfuscated information about this issue?
![image](https://user-images.githubusercontent.com/562238/81534434-50d15780-9368-11ea-939c-efc5b63e10af.png)

Panel JSON would be nice to get I you can share it:
![image](https://user-images.githubusercontent.com/562238/81534553-85451380-9368-11ea-839b-a657cdbee737.png)

**Comment by hugohaggmark** [comment]
If you don't mind @baur could you try to upgrade to 7.0.0.0-beta3 because it seems like something similar has been fixed?

**Comment by hugohaggmark** [comment]
Hi again @baur , we're trying to wrap up issues before 7.0 stable. Anymore information regarding the data and Panel JSON you can share is very valuable as I can't repro this.

**Comment by baur** [comment]
> Hi again @baur , we're trying to wrap up issues before 7.0 stable. Anymore information regarding the data and Panel JSON you can share is very valuable as I can't repro this.

@hugohaggmark, Ok

**Comment by baur** [comment]
Bug reproduced on beta-3, play [gif](https://s6.gifyu.com/images/some_bug_1.gif)

PS: how to embed gif here

**Comment by baur** [comment]
@hugohaggmark,

Bug reproduced on beta-3, play [gif](https://s6.gifyu.com/images/some_bug_1.gif)

PS: how to embed gif here

**Comment by hugohaggmark** [comment]
@baur outstanding, will look into this ASAP!
