### ISSUE TITLE
GroupByNodes not available when adding Graphite 1.1.x

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#24287]
**What happened**:
GroupByNodes and GroupByTags Graphite functions are not available in Grafana when adding a Graphite datasource, using the Graphite version 1.1.x. Functions show up if the Graphite version in the datasource is changed to any other and then changed back to 1.1.x.

Functions are there right away if you select a Graphite version 1.0.x when adding a datasource.

**What you expected to happen**:
GroupByNodes and GroupByTags functions being available right after adding a datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Add a new Graphite datasource, selecting the version 1.1.x. Start creating a query (in a dashboard or using Explore) and try to find GroupByNode or GroupByTags function in a list of functions. It won't be there.
Go to datasources, open a Graphite datasource, change the Graphite version to 1.0.x, save and then change back to 1.1.x and save. Both functions will be available after that.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.7.3
- Data source type & version:
Hosted Metric Graphite 1.1.x
- OS Grafana is installed on:
Hosted Grafana and local installation on CentOS 7
- User OS & Browser:
N/A
- Grafana plugins:
N/A
- Others:
N/A

**Comment by tonyghita** [comment]
Seems like there may be some strict version checking happening in this function:

https://github.com/grafana/grafana/blob/19d27351e9233a814bc6a512c0a98cc0f47e61d8/public/app/plugins/datasource/graphite/gfunc.ts#L699-L717

I noticed many of these are missing from autocomplete, but are defined in the project (and have been for ~3 years), so I was surprised when I didn't see the autocomplete functionality working.

Worth looking into the version comparison logic?

**Comment by torkelo** [comment]
Problem is here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx#L47 
we set a default version, but we do not support defaults, so this value never get's set until you change it. 

So by default a new graphite data source never get's a version until you change this property to something, which is very misleading as the dropdown will show 1.1.x as the current selected value when it's not saved as such

**Comment by ifrost** [comment]
Fixed by https://github.com/grafana/grafana/pull/31680
