### ISSUE TITLE
Table preview in new panel edit mode

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#24282]
Understanding what is happening with the result set when the transformations are applied is currently tricky when you experiment with other panel than table.

We discussed that with @torkelo @sarlinska and @jessover9000 and we think about introducing a new view mode to the panel editor which is a Table view. 

- It should be available via the radio button group for toggling the panel mode. 
- It should display the transformations result in a Table component (not panel)

**Comment by natellium** [comment]
Released in 8.0
