### ISSUE TITLE
Roles problems with AD

### ISSUE THREAD

**Issue by Shamilen** [grafana/grafana#24289]
**What happened**: Disable administrator role after relogin

**What you expected to happen**: After login have role admin

**How to reproduce it (as minimally and precisely as possible)**:
Give user role Admin or Editor
User relogin in another browser, or change password in AD
User lose role, now only Viewer 

**Anything else we need to know?**:  Problem was on older version of Grafana.

**Environment**:
- Grafana version: 6.60
- OS Grafana is installed on: RedHat 7.6
- User OS & Browser: Windows 10, Firefox, Chrome
- Others: AD authorization is enable.

**Comment by jongyllen** [comment]
Hi, just to verify: are you changing the role for the user in the Grafana UI? The role should be set in the LDAP mapping config (ldap.toml file). Any changes made in Grafana will be overwritten. This is by design.

If you are setting the role from your AD and it is changed then it sounds like a bug.

**Comment by sakjur** [comment]
The LDAP documentation expands a little on what @jongyllen is saying, I'd recommend taking a look at the [LDAP Group Mappings](https://grafana.com/docs/grafana/latest/auth/ldap/#group-mappings) section in particular.

**Comment by Shamilen** [comment]
Thank you.
It wasn't obvious.

**Comment by sakjur** [comment]
:+1: I agree. That would be useful information to get when you're editing the permissions of a user, not something you should have to dig the documentation for.
