### ISSUE TITLE
PanelInspect: allow showing data without transformations and field config applied

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#24285]
Panel inspect Data table now shows the data _with transformations and field configuration applied_. At the same time the CSV downloaded shows the actual raw data.

As discussed with @torkelo, @sarlinska and @jessover9000  It would be good to:
1. Add a possibility to select whether or not transformations should be applied
2. Add a possibility to select whether or not field config should be applied

**Comment by sarlinska** [comment]
The question here is whether options 1&2 for the "download csv" should be separated from the options manipulating the table view or not.
