### ISSUE TITLE
Stat panel does not parse $__cell_N for Field Title

### ISSUE THREAD

**Issue by djryanj** [grafana/grafana#24302]
**What happened**:
When using `$__cell_N` (where N is a number) for a field title in a stat panel, it does not parse correctly and instead shows the literal text `$__cell_N`. This happens with `${__cell_N}` and `$__cell_{N}` as well.
![image](https://user-images.githubusercontent.com/33379396/81093139-e4b1a800-8ebe-11ea-8248-1c94d9652954.png)

![image](https://user-images.githubusercontent.com/33379396/81094057-3444a380-8ec0-11ea-9a1d-a47d3450a08d.png)

Other template variables such as ${__field.name} work as expected.

**What you expected to happen**:
The value of `$__cell_N` from the data should be displayed.

**How to reproduce it (as minimally and precisely as possible)**:
Build a Stat panel from a query that returns multivalued data, place $__cell_N in the Field Title.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.7.3 (a04ef6cefc)
- Data source type & version: Azure Monitor v 0.3.0, Log Analytics source
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10, Firefox 75.0

**Comment by torkelo** [comment]
Can you show (in table view) what your data looks like? what other columns do you have?

**Comment by torkelo** [comment]
could help if you switch from calculation to "show all values"

**Comment by djryanj** [comment]
@torkelo - here's table view:

![image](https://user-images.githubusercontent.com/33379396/81116188-2738ac00-8ee2-11ea-81b5-2242213c0875.png)

I'm trying to display the value of the "VM" column.

Switching to "All Values" and limiting it to 1 does work though:

![image](https://user-images.githubusercontent.com/33379396/81116315-5f3fef00-8ee2-11ea-8c44-3f31ff27e9f8.png)

**Comment by torkelo** [comment]
This looks to be working in 7.0
