### ISSUE TITLE
Problem with template variables containing many values

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#2430]
When using a template variable containing many values, the frontend only displays a fraction of the possible values. The configured template variable requests the possible values from the graphite backend, and the resultset contains all (>6000) entries. In the variable dropdown on the dashboard, i only get ca. 1500 possible values displayed. (grafana 2.0.2 with graphite backend)

**Comment by torkelo** [comment]
yes, you will have enter a partial search string to limit the list and find the value you want
