### ISSUE TITLE
TablePanel: Show truncated cell content in tooltip

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#24304]
The table panel truncates long cell content and it can be hard to get to the full content: 

![Screenshot from 2020-05-05 19-13-11](https://user-images.githubusercontent.com/1014802/81094979-9cb57400-8f04-11ea-80e6-51a02346757d.png)

You can resize the column but that means you need to resize the column, check the value and resize back so you do not have to horizontally scroll. Usually what I see in this case is having the full value on hover so you can semi easily gleam it without resizing the column

**Comment by davkal** [comment]
Yeah, there should be a way to get to your data, e.g., for copying it. If someone still needs this ellipsis view, perhaps it's worth making this a panel setting.

**Comment by torkelo** [comment]
this is mostly fixed with the new hover behavior that extends the cell to show you the full content (has some limitations if the cell content is longer than panel)
