### ISSUE TITLE
Feature: a way to create an api key automatically

### ISSUE THREAD

**Issue by htch** [grafana/grafana#2431]
As of now Grafana *almost* can be deployed fully automatically (with salt, chef, what have you), kudos to you guys for making the api.

However there's one obstacle: to access the api you need the api key and that api key has to be issued by a human in the gui. You could work this around of course by writing the key in the db directly or by authenticating the api with "normal" admin:password credentials via the "human" login page. Both solutions are hacky, if you rely on them your deployment script (or, god forbid, salt formula used by tens of projects) is going to break as soon as the db schema/login page layout changes.

Third option, it could be done more like this: http://sentry.readthedocs.org/en/stable/faq/index.html (ie the user makes his own ad hoc script to create his api key) but given go compiled nature it is going to be PITA for the user to create, maintain and deploy: you can't [very easily] cross-compile go code that depends on c extensions.

I believe this problem should be approached differently: by providing the user with a cli script to manipulate api keys, shipped together with grafana.

Do you guys think this is viable?

**Comment by torkelo** [comment]
In Grafana 2.1 there is a new feature that enabled basic auth support. So you can now use the api with username/password without an api key. Or you can use the basic auth feature to generate an api key using basic auth. 

https://github.com/grafana/grafana/issues/2218#issuecomment-117041541
https://github.com/grafana/grafana/issues/1789

**Comment by htch** [comment]
Awesome! It solves the problem.

**Comment by stevebissett** [comment]
Awesome
