### ISSUE TITLE
AWS/WAFV2 metric support

### ISSUE THREAD

**Issue by rynop** [grafana/grafana#24318]
**What would you like to be added**:
Support for querying `AWS/WAFV2` namespace metrics

**Why is this needed**:
Would be cool to alert when a certain level of blocked requests are hit, to indicate potential DOS.

Here is sample source attached to a CloudFront:

```
{
    "metrics": [
        [ "AWS/WAFV2", "BlockedRequests", "WebACL", "prod-www-acl", "Rule", "ALL" ]
    ],
    "view": "timeSeries",
    "stacked": false,
    "region": "us-east-1",
    "stat": "Sum",
    "period": 60
}
```

I think it would be as easy as duplicatiing `WAF` as `AWS/WAFV2` in 
https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go because I don't think the dimensions or metric names have changed. 

Wanted to get your thoughts before I PR.

FWIW I did try old namespace without luck:
![image](https://user-images.githubusercontent.com/372730/81121633-d2eaf780-8ef4-11ea-92f4-1b4c0ac96404.png)

**Comment by dprokop** [comment]
Duplicate https://github.com/grafana/grafana/issues/22215
