### ISSUE TITLE
Auto update datasources from directory (every interval)

### ISSUE THREAD

**Issue by shay-berman** [grafana/grafana#24312]
**What would you like to be added**:
[Currently](https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources) Grafana load all the datasources from `provisioning/datasources` directory when grafana start up. But it will not reload datasources if something changed in the `provisioning/datasources`. Means you need to restart grafana to reload new datasource coming from the directory.

I would like to have such automatic reload datasource if there is change in the `provisioning/datasources` directory.

**Why is this needed**:
For usability, mainly in kubernetes where its very common to use  [sidecar](https://github.com/kiwigrid/k8s-sidecar) that find configmap and add them as file to the directory. So you only need to create configmap and then the sidecar will automatic find the configmap and map it inside the `provisioning/datasources` directory and then grafana will automatic reload it.

BTW this usability already exist with [dashboards](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) - grafana watch `provisioning/datasources` directory and reload new dashboard automatically. So why not to use the same thing for datasources?

**Comment by bergquist** [comment]
Adding support for reloading datasource configs makes sense. There is no reason except that no one has been working on it.

**Comment by shay-berman** [comment]
I just install prometheus and thanos querier in k8s with promethes operator helm chart but then i figureout that grafana does not take the datasource because i had to define it in advance, which is not really the best practice in k8s to have depandancy order of things.

This is why I raising it here, so it will be simpler to install grafana in k8s.
