### ISSUE TITLE
Explore: Severity parsing

### ISSUE THREAD

**Issue by ventris** [grafana/grafana#24329]
**What happened**: Every log that includes the key error will be classed as an error by the explore view of Loki even though the actual severity might not be an error.

Below is parts of logs from Hashicorp Vault. Most data is redacted but as you can see the last line has the key error with nothing as the value. The value will always be empty if there is no error thrown. So the error key will always be present in all logs from Vault.
No error:
```
{
   "time":"2020-05-06T10:21:38.240503013Z",
   "type":"response",
   "response":{
      "headers":null
   },
   "error":""
}
```

Error thrown:
```

{
   "time":"2020-05-06T09:38:26.630387417Z",
   "type":"response",
   "response":{
      "data":{
         "error":"hmac-sha256:"
      },
      "headers":null
   },
   "error":"1 error occurred:\n\t* permission denied\n\n"
}
--



```

**What you expected to happen**: Not get all logs classified as errors when there is no error.

**How to reproduce it (as minimally and precisely as possible)**: Send an event with the key/value error: "" and it will be classified as error by the explore view.

**Anything else we need to know?**: This seems to be a corner case as most logs don't sends anything with the string error in them if it's not an error.

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Loki 1.4.0
- OS Grafana is installed on: alpine (docker image)
- User OS & Browser: MacOS Catalina
- Grafana plugins: 
- Others:

**Comment by ivanahuckova** [comment]
@ventris I have added documentation #28975 to make it more clear how do we extract and determine log level. I hope it helps - so you can adjust logs in a way that Grafana will be able to determine its log level/adjust level. There is already also an issue regarding supporting custom log levels #25585 - so if you think something like this would be helpful, please feel free to upvote it, as with parsing of log messages, it would be very hard and error-prone to specify all the rules in a way that it would work for everyone.

**Comment by ventris** [comment]
@ivanahuckova If I have an application that I can not change the log format in (Above logs are picked from Hashicorp Vault) is there some way for me to exclude the free text search of keywords?

Or is my only option to reformat all logs so that they have the level field?

#25585 talks about adding support for custom log levels but in this case the logs don't have the level field so you are searching for the error text in the log and picks it up even though there is no error there as the key is named error.

**Comment by ivanahuckova** [comment]
Yes, I agree. Would adding configurable option to remove/keep log parsing to get logLevel solve your issue?

**Comment by ventris** [comment]
That would be a great option.  Keep the level key/value but make it possible to remove the free text search. That would solve any issue that I can think of.
