### ISSUE TITLE
string escape bug when using variable with dot in value on influxdb data source

### ISSUE THREAD

**Issue by nonsenz** [grafana/grafana#2432]
hi,
i'm new to grafana and influxdb and first i want to thank you all for this wonderful piece of software. but i think this one is a bug on grafanas side. when i try to use a variable to filter my dashboard by host and one hostname contains a dot (e.g. foo.bar) the resulting query looks like this:
    
    SELECT mean(value) FROM "load_shortterm" WHERE "host" = 'foo\.bar' AND time > 1438587977s and time < 1438631177s GROUP BY time(1m), "host"

and this results in an influxdb parser error:

    InfluxDB Error Response: error parsing query: found \., expected identifier, string, number, bool at line 1, char 64

if i swap the $host variable in the query with the foo.bar value everything works fine. 

i'm using grafana v 2.1.0-pre1 from last week (don't know where to see the exact build number) and influxdb 0.9.2.

**Comment by torkelo** [comment]
Grafana expects you to use the regex match operator when using a variable in a location like this. put the variable inside /$host/  and grafana will change the operator to regex automatically. This way you can enable the All featue and multi select and the query will still work.

**Comment by nonsenz** [comment]
thx for the quick response. if i change the query string to
    
     "host" =~ /$host/ 

it will work. but i can't do this using the "create query by clicking" method. this results in the query string in my above comment. and if i change from the "edit string" to "edit by click" mode the query will break again, because grafana changes the =~ /.../ part to  "host" = '$host' again.

**Comment by torkelo** [comment]
Nice sure I understand you. Just click the $host part and change it to /$host/ and grafana will change the operator.

**Comment by nonsenz** [comment]
ah, i see :-) i didn't notice that i can write above the dropdown as well. it is kind of counter intuitive to have the $host variable clickable in the dropdown. why have it there in the first place? is it possible to select it in the dropdown without any error?

**Comment by torkelo** [comment]
Your right I think it might be better to suggest /$host/ directly in the auto complete drop down

**Comment by nonsenz** [comment]
yea that would be better :-) ok, thx again for the superb support. i think this issue can be closed now.

**Comment by torkelo** [comment]
@nonsenz changed to the auto complete suggestions contain wrap the variables in `/` by default :)

**Comment by nonsenz** [comment]
great. one more thing i noticed related to this. after correctly writing the /$var/ above the dropdown the = changes as expected to =~ . when i return to the dashboard and reopen the edit interface the =~ changed back to = . the query is still correct just the interface shows 
    
    host = /$var/ 

instead of

    host =~ /$var/
