### ISSUE TITLE
TablePanel: JSON view tooltip position is off 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24322]
Replicate use Elasticsearch in Logs or Raw document mode 

![Screenshot from 2020-05-06 09-38-02](https://user-images.githubusercontent.com/10999/81148859-5a7c4900-8f7d-11ea-97c6-beca852c954e.png)

**Comment by tskarhed** [comment]
Similar issue can be found in Storybook
![Screenshot from 2020-05-06 14-31-10](https://user-images.githubusercontent.com/1438972/81176991-4436b300-8fa6-11ea-8af2-b8166f9f0f00.png)
