### ISSUE TITLE
Stat panel: No sparkline shown for under 6 hours

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#24325]
**What happened**: When creating a sparkline panel, when changing the timepicker to use an interval under 6 hours (we chose 3 hours), the sparklines disappeared. When we chose 6 hours are above they always appear. When we chose any time interval under 6 hours they do not appear.

**What you expected to happen**: We expected the sparklines to appear.

**How to reproduce it (as minimally and precisely as possible)**: Create a panel using sparklines, and change the timepicker as mentioned above.
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 6.7.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome
- Grafana plugins: Stat
- Others:

**Comment by torkelo** [comment]
Check your query group by time interval? and your query result. 

Can you switch to table and view the query result?

**Comment by reuvygroovy** [comment]
Yeah, that works! Awesome!

I also noticed that the sparklines never fill (even when at 100%) more than half the box.  Is that by design or am I doing something wrong?

**Comment by torkelo** [comment]
your query must be returning data that is lagging behind the time range end. 

When I query for influxdb it stretches across the full stat panel

**Comment by reuvygroovy** [comment]
I meant, does it stretch vertically? I figure 100% CPU utilization would consume the entire box, but it seems that it takes up only 50% of the box.

**Comment by torkelo** [comment]
Yes , sparkling is set to 50% Max height

**Comment by reuvygroovy** [comment]
Any way to change it to 100%? The 50% is (a) not known and clear (b) not intuitive for the user to know that the value is 100% since the box is half full. The difference therefore (unless you know already from previous experience and remember) between 50% and 100% isn nill.
