### ISSUE TITLE
Add Postgres 11 and 12 data source version selector 

### ISSUE THREAD

**Issue by GokulSNarayan** [grafana/grafana#24320]
**What would you like to be added**: I tried Grafana version 7 from master branch using docker and when I tried adding a Postgres Datasource V12 ,which I previously used in Grafana Version 6.7.3 (a04ef6cefc), there was no option to add 11 and 12. Is it a bug or is the support for V11 and 12 of postgres officially removed.

**Why is this needed**: My Postgres Database is Version 12 and it is using TimescaleDB and I need this feature to run my postgres datasource in Grafana
![Screenshot from 2020-05-06 10-58-04](https://user-images.githubusercontent.com/44142590/81140865-85b86580-8f88-11ea-9742-a8f191bd46fc.png)

**Comment by torkelo** [comment]
probably need to add it to the list, should still work if you select 10 ?
