### ISSUE TITLE
Only Legends without graph

### ISSUE THREAD

**Issue by Phinitris** [grafana/grafana#2433]
Hey guys,
I would appreciate a new "Panel" where we can only display values without graphing them. Like current network speed per IP as legend.

For example just this, without graph.
![screenshot_10](https://cloud.githubusercontent.com/assets/10375269/9061785/517510a8-3abe-11e5-9e9f-7eefdbbc30bc.png)

**Comment by pavel-odintsov** [comment]
Plus one for me. We need some way to bring data together.

**Comment by torkelo** [comment]
Should be solvable with an upcoming table panel

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/1771
