### ISSUE TITLE
 local snapshots show an error "Templating init failed" for interval variables

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#24342]
**What happened**:
Viewing local snapshots of Dashboards shows an error "Templating init failed".

![Screenshot_20200506_170119](https://user-images.githubusercontent.com/25184101/81186359-596a0c80-8fbb-11ea-88f1-1632503fc836.png)

**How to reproduce it**:
The error is caused by a variable with type "interval". There are no issues if no interval variables are added into a dashboard.

**Environment**:
- Grafana version: 6.7.3-1      
- Data source type & version: Prometheus 2.16.0
- OS Grafana is installed on: CentOS Linux 7 (Core)

**Comment by dprokop** [comment]
@adivinho thanks for reporting. This bug is now fixed in version 7.0. Beta-1 is now available and stable version is about to come soon - maybe you could try updating?
