### ISSUE TITLE
Win64 download for Grafana 2.1 produces XML error

### ISSUE THREAD

**Issue by andycarlsonuk** [grafana/grafana#2434]
Hopefully this will be a very short lived issue.

When clicking on the Win64 binary for Grafana 2.1 I just get this XML instead...

<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>winbuilds/dist/grafana-2.1.0.windows-x64.zip</Key><RequestId>83455AD05A4A5731</RequestId><HostId>IBe3CEpmTYQXyCxOi9rUK9ywCY0oeuBPJR69sV6osNZcq6z+E4N44AT7Jqf0GP8DiGmdbK3kTCc=</HostId></Error>

I'm very much looking forward to getting 2.1. Thanks for your efforts.

**Comment by andycarlsonuk** [comment]
Sorry - forgot to escape the XML...

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>winbuilds/dist/grafana-2.1.0.windows-x64.zip</Key><RequestId>83455AD05A4A5731</RequestId><HostId>IBe3CEpmTYQXyCxOi9rUK9ywCY0oeuBPJR69sV6osNZcq6z+E4N44AT7Jqf0GP8DiGmdbK3kTCc=</HostId></Error>`

**Comment by torkelo** [comment]
fixed

**Comment by andycarlsonuk** [comment]
Thank you. I'm up and running now.
