### ISSUE TITLE
Test Connection button

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#2435]
`Test Connection` button shown only for already added datasources. Is it normal behavior?

![2015-08-04 21-46-26 grafana - grafana-zabbix org - google chrome](https://cloud.githubusercontent.com/assets/4932851/9069711/81ae8d0a-3af3-11e5-8f3f-57b7473be52a.png)
![2015-08-04 21-54-31 grafana - grafana-zabbix org - google chrome](https://cloud.githubusercontent.com/assets/4932851/9069718/89d8e7e6-3af3-11e5-8bb7-0df2048bc351.png)

**Comment by torkelo** [comment]
yes, it has be added, since the test if using the backend and frontend infrastructure and code that expects the data source to be persisted already. Not ideal I know, but was less complex and quicker to implement it that way

**Comment by alexanderzobnin** [comment]
@torkelo Thanks! I have implemented Test connection feature for zabbix datasource and it works fine!
