### ISSUE TITLE
Stat Plugin Returns "Time" instead of Field.Name

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#24356]
**What happened**: After upgrading to 6.7.3. "Stat" panel Field > Title section doesn't work as the way it works before.

```${__field.name}``` returns "Time" as a word instead of the field name.

**Before update:**

![image](https://user-images.githubusercontent.com/43188411/81203021-12d2dd00-8fd0-11ea-9566-5aee66dcf319.png)

**After update:**

![image](https://user-images.githubusercontent.com/43188411/81202852-d7d0a980-8fcf-11ea-8c06-360e1e095f5f.png)

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: InfluxDB 1.7.x
- OS Grafana is installed on: Grafana Alpine Docker Image
- Grafana plugins: Stat

**Comment by dprokop** [comment]
@mertbakir thanks for the report. This should now be fixed in Grafana 7.0. Beta 1 is available and Beta 2 is coming out later today.
