### ISSUE TITLE
Explore (Loki datasource): empty log query request on page load resulting in error

### ISSUE THREAD

**Issue by jstaffans** [grafana/grafana#24357]
**What happened**:

When browsing to the Explore section with a Loki datasource pre-selected but an empty query field, Grafana performs a log query without any query parameters. Loki always returns a HTTP 400.

**What you expected to happen**:

No log query requests should be sent until something has been entered into the query field.

**How to reproduce it (as minimally and precisely as possible)**:

* Go to the Explore section
* Open browser dev tools
* Select a Loki data source
* Observe a request to `/loki/api/v1/query_range` without query params, resulting in a HTTP 400 error

**Environment**:

- Grafana version: 6.7.3
- Data source type & version: Loki 1.4.0

**Comment by davkal** [comment]
I can't reproduce this in master, so it might be fixed already.
