### ISSUE TITLE
[Reopen] Grafana not restored dashboards to folder

### ISSUE THREAD

**Issue by sirisukjinta** [grafana/grafana#24367]
I'm currently using version 6.7.0 but this bug I found for a while since 6.2.x.

I've tried to use CaC but it's not suitable for the task to create new users (it works but when restart all users are gone) so the solution is to use database in parallel (just config [database] in grafana.ini)

When using database even we have dashboards generated to JSON, it seems Grafana image has a script to load JSON to database but the bug is the script doesn't store folderId value to folder_id column in dashboard table (but store folderTitle and folderUrl).

This issue caused when restart Grafana th dashboards will be restored to only general folder.

Grafana version: 6.7.0
Data source type & version: Postgresql v10
OS Grafana is installed on: Openshift
User OS & Browser: Windows/Chrome
Grafana plugins: N/A
Others: The bug is always happen when redeploy or restart Grafana. The JSON dashboards have been loaded to database without folderId. I think something wrong in the script to load JSON to database.

![image](https://user-images.githubusercontent.com/37993299/81252472-33db1280-9050-11ea-9d88-33cf79240601.png)
![image](https://user-images.githubusercontent.com/37993299/81252481-38073000-9050-11ea-9607-659e9c02da73.png)

Steps to reproduce
- Grafana using Postgresql v10
- Create dashboard
- Create folder
- Move the dashboard to the folder
- Deploy Grafana
- After deployment, the dashboard will be under general folder (default), not created folder.

You can see the result after loading JSON dashboard file to database, the value of the folder_id column is always 0 (screenshot) even though the JSON file contains the value (screenshot).

Please help to fix it ASAP

**Comment by torkelo** [comment]
Grafana will it not use folderId from the json. When you provision you have to provision files into different folders defined by the provision yaml config , you basically define folder & the dashboards in separate sections in the provision yaml file

**Comment by sirisukjinta** [comment]
@torkelo 
That's the bug!!
why load everything except folder_id?
I will always create this bug until you fix.

**Comment by torkelo** [comment]
check the dashboard provisioning docs for how to setup folders: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards

**Comment by sirisukjinta** [comment]
@torkelo 
I will take a look.

But please answer my question

Why it could be loaded everything to DB except folder_id?

If you just fix the script to load from JSON to DB together with folder_id, it's done.

I think it's not too hard to do, right?
