### ISSUE TITLE
Cloudwatch/metrics: Support modifying dimensions to metric queries with existing expression

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#24377]
**What would you like to be added**:
Currently dimensions [are hidden](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/components/MetricsQueryFieldsEditor.tsx#L101) if the query has an expression.

As an example consider a panel with the following queries:
```
    "targets": [
    {
      "namespace": "AWS/Lambda",
      "metricName": "Invocations",
      "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\\\"Errors\\\"', 'Sum', 31536000))",
      "dimensions": {
        "FunctionName": "*"
      },
      "region": "default",
      "id": "",
      "alias": "",
      "statistics": [
        "Average"
      ],
      "period": "",
      "matchExact": true,
      "refId": "A"
    },
    {
      "namespace": "AWS/Lambda",
      "metricName": "Invocations",
      "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\\\"Errors\\\"', 'Sum', 36000))",
      "dimensions": {},
      "region": "default",
      "id": "",
      "alias": "",
      "statistics": [
        "Average"
      ],
      "period": "",
      "matchExact": true,
      "refId": "B"
    }
  ],
  ```

**Why is this needed**:
Currently, If by mistake the user does not provide a dimension, the only way to fix it is to delete and re-write the expression (or modify the JSON and save it).
This will be also useful for debugging such queries since if the expression is not empty, dimensions (along with other fields) are not visible.

**Comment by kaydelaney** [comment]
cc @sunker

**Comment by sunker** [comment]
Not sure I understand @papagian. In case a custom search expression is being used, all dimensions (and all other fields except for the region) will be ignored in the query. That's why the dimension field is hidden.

**Comment by papagian** [comment]
I think I have pointed to the wrong dashboard example.
We had a user issue where there were 2 queries like:
```
  "targets": [
    {
      "namespace": "AWS/Lambda",
      "metricName": "Invocations",
      "expression": "",
      "dimensions": {
        "FunctionName": "*"
      },
      "region": "default",
      "id": "",
      "alias": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\\\"Errors\\\"', 'Sum', 31536000))",
      "statistics": [
        "Average"
      ],
      "period": "",
      "matchExact": true,
      "refId": "A"
    },
    {
      "namespace": "AWS/Lambda",
      "metricName": "Invocations",
      "expression": "",
      "dimensions": {},
      "region": "default",
      "id": "",
      "alias": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\\\"Errors\\\"', 'Sum', 3600))",
      "statistics": [
        "Average"
      ],
      "period": "",
      "matchExact": true,
      "refId": "B"
    }
  ],
  ```
  
After some debugging they found out the dimensions were missing from the 2nd query but they couldn't find where to change the dimensions (dimensions were hidden and they didn't know that they had to remove the expression for unhiding them so they had to changed from the JSON.

I will update the issue description appropriately.

**Comment by sunker** [comment]
Okay. In the example above they've put the search expression in the alias field, but maybe that's just a copy paste error or something. 

Anyway I think it's terrible UX that some fields are being hidden as soon as another field is used. Instead we should have mode toggle like in the ADX plugin and for the MQL editor in cloudmonitoring. I'll create a feature request for that.

**Comment by papagian** [comment]
> Okay. In the example above they've put the search expression in the alias field, but maybe that's just a copy paste error or something.
> 
> Anyway I think it's terrible UX that some fields are being hidden as soon as another field is used. Instead we should have mode toggle like in the ADX plugin and for the MQL editor in cloudmonitoring. I'll create a feature request for that.

sorry for that; I've updated the issue description again!
