### ISSUE TITLE
Support search query parameters in dashboard search page

### ISSUE THREAD

**Issue by apexskier** [grafana/grafana#24379]
**What would you like to be added**:

I'd like to be able to link to a pre-filled [dashboard search page](https://grafana.com/docs/grafana/latest/reference/search/) using query parameters similar to the [dashboard search api](https://grafana.com/docs/grafana/latest/http_api/folder_dashboard_search/).

e.g. https://my-grafana/dashboards?tag=service&query=test would show me this page:

<img width="1025" alt="Screen Shot 2020-05-07 at 11 12 52" src="https://user-images.githubusercontent.com/329222/81276738-b913f680-9053-11ea-947a-94a3afffdb33.png">

**Why is this needed**:

This would allow me to bookmark and share searches.

**Comment by Clarity-89** [comment]
This is something we were thinking to add in one of the future releases.
