### ISSUE TITLE
Transforms: CalculateField regex (include options) matches wrong series and problem with byName matcher

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24373]
The calculate field include option does not work correctly. 

having series named A-series A-series1 A-series2 

And selecting only A-series and A-series1 creates a regex: like `A-series|A-series1` by the calculate field editor. which matches on A-series2 as well. 

We need to update this transform to instead store a list of full fields so we can product a correct regex with start and end tags `^{name}$` . The calculate field editor stores the included fields in a string that it parses to generate the current selection state. This also seems problematic. 

Not sure how we want this to work, in UI & behind the scenes (storing the selected fields object keys, array). But storing the regex as we do now seems like a bad idea (will break if any series name contains a regex character). 

Actually I think series names that include a dot (or other regex characters) wont work in any byName matcher as we do not do any regex escaping. 

And looking how the byName matcher works it tries to convert include option to regex but it's using a function that expect a `/asd/` syntax to be interpreted as a regex directly, so it will get wrapped in this 

/^A-series|A-series1$/

That is the expression that actually gets tested when we use a byName matcher in this case. byName wrapper should just check equality, not regex or if the string does not include `/` prefix and suffix just do normal equality, or regex escape value before constructing a regex the default non regex scenario. 

And if a transform or matcher wants to build a regex it needs to regex escape value and include proper termination characters and it needs to be prefix & suffixed with `/`

**Comment by mckn** [comment]
The reason behind this one #24518 is connected to this one. Currently the fieldMatcher.ByName doesn't work because we are missing the `frame` and `allFrames/data` when "calculating" the fieldDisplayName.

So I am currently fixing that one and I might fix this one as well. Because both the caluclate and the filterByName is using the same matcher under the hood.

**Comment by mckn** [comment]
I will probably need the whole day to fix both of these :P
