### ISSUE TITLE
Unable to access more than 2 input sources

### ISSUE THREAD

**Issue by dopey** [grafana/grafana#2438]
I have 3 input sources {grafana, graphite, and influxdb}. The default is set to graphite, but switching to influxdb is made very difficult through the UI. Only the first two input sources are shown as options when I click the `Datasource` dropdown. The third is there, but I need to plug my 13" macbook into a monitor in order for the UI to let me access it.
<img width="391" alt="screen shot 2015-08-04 at 5 49 26 pm" src="https://cloud.githubusercontent.com/assets/1820847/9075991/4e6611a6-3ad1-11e5-80ae-8c07b52f7698.png">

**Comment by torkelo** [comment]
can replicate this, When you hover over the dropdown values you should be able to scroll. I can in chrome on linux at least.

**Comment by dopey** [comment]
Just tried again (with hovering/scrolling) and not working with chrome v44.0.2403.130 (64-bit) or firefox v39.0 on mac OSX 10.10.4.

**Comment by torkelo** [comment]
cant replicate on chrome Version 44.0.2403.130 (64-bit)  on Mac OSX 10.10.3 

When I click the dropdown and hover over the first item I chan scroll down

**Comment by dopey** [comment]
When I do scroll down it's as though only two sources are available (I can scroll past the last element) as in the photo below:
![screen shot 2015-08-05 at 1 42 25 pm](https://cloud.githubusercontent.com/assets/1820847/9097363/1320e66e-3b78-11e5-95bb-b033dc63b4af.png)

But if I lengthen the chrome window just a bit more (need a larger screen for this) the third datasource pops up:
![screen shot 2015-08-05 at 1 42 47 pm](https://cloud.githubusercontent.com/assets/1820847/9097379/2d20b4e0-3b78-11e5-80d0-d9ffd49d8961.png)

Was having the same issue with the nightly builds.

**Comment by torkelo** [comment]
That is just suuuuuuuuper weird that the drop down does not contain the last item if your browser window is not high enough. Tested this on all browsers and different window sizes, do not get this behavior.  Very strange

**Comment by dopey** [comment]
haha, I appreciate you taking a look. Not a big deal as in the mean time full screening my browser allows enough room for all 3 options to be shown.
