### ISSUE TITLE
Validation error, invalid URL on PostgreSQL Data Source creation specifying a port

### ISSUE THREAD

**Issue by vschettino** [grafana/grafana#24387]
**What happened**:
I get this "Validation error, invalid URL" message while trying to specify a different port on PostgreSQL datasource. The inserted value was `192.168.0.1:5433` on `Host` config. 

**What you expected to happen**:
This should be a valid `Host` setting, as it was on `grafana:latest`. I'm trying out 7.0 release. 

**How to reproduce it (as minimally and precisely as possible)**:
Specify an IP (i.e., 127.0.0.1 instead of localhost) and any port for `Host` setting, on PostgreSQL Data Source creation.

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v7.1.0-f3f34ac0pre (d891cc5949)`, reproducible on `7.0 beta1`. It works well on stable `grafana:latest` on docker
- Data source type & version: PostgreSQL

- OS Grafana is installed on: Alpine on docker
- User OS & Browser: Debian
- Grafana plugins: None, fresh install
- Others:

![Captura de tela de 2020-05-07 09-07-14](https://user-images.githubusercontent.com/7289698/81292559-2fa7f880-9042-11ea-8c34-d1b0e14fa91b.png)

**Comment by marefr** [comment]
Sounds like a regression from #23731

**Comment by vschettino** [comment]
> Sounds like a regression from #23731

Yeah, it seems so:
```go
	_, err := url.Parse("192.168.1.1:5433") // err
	_, err := url.Parse("localhost:5433") // no err
	_, err := url.Parse("http://192.168.1.1:5433") // no err
```

I'm not sure which one is the best approach here:
   - Ensure `protocol` is present on url, or at least better error message 
   - Change the "example" on the field to be `http://localhost:5432`, not just `localhost:5432`
   - Do nothing and let the user figure out the protocol should be filled. 

I am not seasoned on this project but I can help with a PR if you guys want.

**Comment by marefr** [comment]
Thanks. We may have to revert part of #23731. Should be resolved for 7.0 stable release.

**Comment by aknuds1** [comment]
I will see if I can solve this.

**Comment by vschettino** [comment]
> Thanks. We may have to revert part of #23731. Should be resolved for 7.0 stable release.

OK. Glad to help :)

**Comment by aknuds1** [comment]
I could reproduce, but I had to specify an IP in the URL instead of 'localhost'. Will see what can be done to fix it.

**Comment by aknuds1** [comment]
@vschettino Can you try https://github.com/grafana/grafana/pull/24497?

**Comment by vschettino** [comment]
> @vschettino Can you try #24497?

Yep, now it works as intended :) This regex solution is cleaner too IMO.

**Comment by aknuds1** [comment]
Thanks for confirming @vschettino! I'm in the process of finalizing the PR (tests++).

**Comment by vschettino** [comment]
My pleasure! Tell me if you need anything else.

**Comment by aknuds1** [comment]
Sure, no worries. Will let you know if anything comes to mind.

**Comment by superclarkk** [comment]
Very new user here. I was having trouble connecting to my local PostgreSQL database, always getting the "Validation error, invalid URL" error. Thankfully I found this ticket.

The hint in the "Host" input field, which says, "localhost:5432" is misleading. Leaving as default (empty) caused the error. Using "127.0.0.1:5432" fixed it.
