### ISSUE TITLE
Global organization variables do not translate to a value in queries

### ISSUE THREAD

**Issue by josemoreno** [grafana/grafana#24390]
**What happened**: 
When using $__org or $__org.name in the queries to Prometheus, neither the organization ID nor the organization name appears in the query. 

Query: 

![query](https://user-images.githubusercontent.com/3711268/81295436-b378d980-9070-11ea-9b74-ce0209c89fb9.png)

Query inspector:

![query_inspector](https://user-images.githubusercontent.com/3711268/81295466-becc0500-9070-11ea-94c4-1d83fc05c03c.png)

Prometheus log:

![prom_log](https://user-images.githubusercontent.com/3711268/81295503-cd1a2100-9070-11ea-9470-01a40ae99bb6.png)

As it can be seen, the variable $__org.name is never substituted by the organization name and arrives as $__org.name to Prometheus. It is also happening with $__org variable. No matter if I use curly braces (${__org.name}), I don't get the value in Prometheus. Besides, it is also happening when trying to define a new dashboard variable using one of the organization variables.

**What you expected to happen**: 
Get the organization name in the query, instead of the name of the variable

**How to reproduce it (as minimally and precisely as possible)**: 
Use $__org or $__org.name in a query

**Anything else we need to know?**: 
Might be related to #23841 

**Environment**:
- Grafana version: v6.7.3 (a04ef6cefc)
- Data source type & version: Prometheus 2.16.0
- OS Grafana is installed on: Ubuntu 18.04.3 LTS 
- User OS & Browser: Windows server 2012, Chrome
- Grafana plugins: None

Thanks!!

**Comment by Estrax** [comment]
@josemoreno thank you for reporting. To get the organization name you have to use `${__org.name}` while you used it without curly braces. I'll leave there a link to the docs: https://grafana.com/docs/grafana/latest/variables/global-variables/#global-variables so you can read more about it (though I am sure you already did!).
As for the problem with variables evaluation itself, it seems to be the same issue as described in #23841, so I'll close this one and then follow up in that issue.

**Comment by josemoreno** [comment]
Hi, 

I might have not explained myself, but even with curly braces I get the same:

![imagen](https://user-images.githubusercontent.com/3711268/82097475-3fd76c00-9703-11ea-8544-632ebca6b6be.png)

And the prometheus log:

![imagen](https://user-images.githubusercontent.com/3711268/82097513-541b6900-9703-11ea-986b-4e22899493ed.png)

This was not a fresh 6.7.3 installation, I upgraded from 6.6 (if I recall correctly). Could be that the issue?

Thanks
