### ISSUE TITLE
Support LDAP  anonymous binding

### ISSUE THREAD

**Issue by youngking** [grafana/grafana#2439]
Bind DN is a must,  which can't be empty, though my ldap server is using anonymous bind .

**Comment by torkelo** [comment]
how do you do an anonymous bind? empty bindDN?

**Comment by youngking** [comment]
Yes , like the gitlab and chef,  leave the bind_dn and bind_password settings blank will be ok.  https://docs.chef.io/server_ldap.html

**Comment by torkelo** [comment]
I have removed the requirement that bindDN cannot be empty, you can try with latest build (2.1.1-pre1) http://grafana.org/download/builds.html , just triggered the build so should appear within 5-6min 

and see if this works

**Comment by liyichao** [comment]
It crashes. 

<img width="449" alt="2015-08-06 11 30 06" src="https://cloud.githubusercontent.com/assets/2576762/9103246/8a2df2a4-3c2e-11e5-865e-e2e17e6d0a72.png">

The log says:

```
2015/08/06 11:26:46 [I] Completed /css/grafana.dark.min.4efc02b6.css 404 Not Found in 3.617466ms
2015/08/06 11:26:46 [I] Completed /app/app.3c38f44f.js 404 Not Found in 5.071203ms
2015/08/06 11:26:49 [I] Completed /css/grafana.dark.min.4efc02b6.css 404 Not Found in 3.347821ms
2015/08/06 11:26:49 [I] Completed /app/app.3c38f44f.js 404 Not Found in 7.273285ms
2015/08/06 11:26:50 [I] Completed /css/grafana.dark.min.4efc02b6.css 404 Not Found in 4.083228ms
2015/08/06 11:26:50 [I] Completed /app/app.3c38f44f.js 404 Not Found in 8.075397ms
2015/08/06 11:27:21 [I] Completed /css/grafana.dark.min.4efc02b6.css 404 Not Found in 4.453871ms
2015/08/06 11:27:21 [I] Completed /app/app.3c38f44f.js 404 Not Found in 9.41008ms
2015/08/06 11:29:25 [I] Completed /app/app.3c38f44f.js 404 Not Found in 3.590197ms
2015/08/06 11:29:25 [I] Completed /css/grafana.dark.min.4efc02b6.css 404 Not Found in 3.87034ms
```

**Comment by torkelo** [comment]
That is not a crash, looks like you have not upgraded grafana properly. missing frontend files.

**Comment by torkelo** [comment]
Did you restart grafana-server after updating?

**Comment by youngking** [comment]
It works for me, thanks

**Comment by baites** [comment]
It works for me as well. I just started to testing grafana and it is great. However, I would be quitting it without LDAP anonymous binding. So I am very lucky that you push this six day ago !!
