### ISSUE TITLE
PanelEdit: Unable to save transparent state 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24391]
1) Create panel, toggle transparent mode in panel settings (under title & description in side pane)
2) Go back to dashboard, save dashboard
3) Go into panel edit, untoggle transparent option
4) Go back via apply or arrow button,  panel still transparent

**Comment by Harkishen-Singh** [comment]
Would like to take this up.

**Comment by torkelo** [comment]
Suspect something goes wrong in PanelModel.restoreModel function
