### ISSUE TITLE
Legend doesn't work in v7.0.0 beta 2

### ISSUE THREAD

**Issue by Atomicbeast101** [grafana/grafana#24404]
**What happened**:
Updating to beta2 from beta1 of v7.0.0 breaks how legends work. It doesn't retrieve the label value from the metric through Legend.
![alt text](https://i.imgur.com/sULXmXq.png "Broken")

**What you expected to happen**:
![alt text](https://i.imgur.com/jK89j4G.png "Expected Output")

**How to reproduce it (as minimally and precisely as possible)**:
Create a table with **Time Series** type data and choose a label to show in **Legend**.

**Anything else we need to know?**:
This was not the case in v7.0.0-beta1 and previous versions.

**Environment**:
- Grafana version: v7.0.0-beta2
- Data source type & version: Prometheus v2.17.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: All default ones

**Comment by torkelo** [comment]
thanks for reporting this, fix incoming!
