### ISSUE TITLE
Graphite annotations are invisible in the demo dashboard

### ISSUE THREAD

**Issue by metametadata** [grafana/grafana#24405]
**What happened**:

Annotations from Graphite source (`updates`) are not shown:

<img width="1552" alt="Screenshot 2020-05-07 21 20 09" src="https://user-images.githubusercontent.com/4689913/81331015-9ca2a900-90a9-11ea-961c-476e3368bda2.png">

**What you expected to happen**:

Annotations from graphite source are shown on the graphs.

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://play.grafana.org/d/000000010/annotations?orgId=1&from=now-1y&to=now. Enable `updates` annotation via a toggle at the top.

**Anything else we need to know?**:

* Other annotations from --Grafana-- source work fine (`deploy`, `outages`).
* Table at the bottom looks suspicious:

<img width="1323" alt="Screenshot 2020-05-07 21 27 11" src="https://user-images.githubusercontent.com/4689913/81330990-91e81400-90a9-11ea-8e77-00e5ecb3eb5f.png">

* Query for `updates` returns some correctly looking data if examined via Explore:

<img width="1354" alt="Screenshot 2020-05-07 21 31 33" src="https://user-images.githubusercontent.com/4689913/81331374-2783a380-90aa-11ea-9034-6d225cb0a02f.png">

**Environment**:
- Grafana version: current demo one (6.7.3 (a04ef6cefc))
- Data source type & version: Graphite
- OS Grafana is installed on: hosted
- User OS & Browser: Chrome, Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
bug is here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/datasource.ts#L228 

Since we changed time field to be first (in 7.0) we forgot to update that line
