### ISSUE TITLE
HTTP API & CORS Headers, backend option to enable CORS & CORS Domain

### ISSUE THREAD

**Issue by HallsHalls** [grafana/grafana#2440]
I want to use  API from remote resource, 

like that
```js
$http.post('http://dwz.cn/create.php',parms, {
        headers: {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
      }).success(function(responseData) {
        console.log(responseData);
});
```
and the chrome will show:

```error
XMLHttpRequest cannot load http://dwz.cn/create.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. 
```
and i found many solutions add Access-Control-Allow-Origin: "*"  in the server conf...but i cant!

**Comment by torkelo** [comment]
There is currently no option in grafana to set CORS headers (to enable api usage from other websites). You can add these headers if you proxy grafana with nginx for now.

**Comment by HallsHalls** [comment]
thank you very much

**Comment by HallsHalls** [comment]
hi, my team leader ask me  why we can't use direct method to access database (we use openTSDB) and the proxy method to access be a only way , and the direct method can't use ?It is bug?or something else?

**Comment by HallsHalls** [comment]
@torkelo

**Comment by torkelo** [comment]
@HallsHalls you can use direct access, but then you need to enable CORS headers in your installation of OpenTSDB
