### ISSUE TITLE
Dashboard links of type 'dashboard' are missing the icons

### ISSUE THREAD

**Issue by earwin** [grafana/grafana#24410]
**What happened**:
<img width="507" alt="Screen Shot 2020-05-08 at 00 31 23" src="https://user-images.githubusercontent.com/299579/81346706-683be680-90c3-11ea-9180-23d88c80412e.png">

**What you expected to happen**:
<img width="482" alt="Screen Shot 2020-05-08 at 00 32 15" src="https://user-images.githubusercontent.com/299579/81346722-6ffb8b00-90c3-11ea-82a2-3d85bc8bcd90.png">

**How to reproduce it (as minimally and precisely as possible)**:
Create a pair of dashboards, tag one, create 'dashboard' type links in another, select by tag.

**Anything else we need to know?**:
Should be `fa-table` instead of `table`
<img width="505" alt="Screen Shot 2020-05-08 at 00 31 44" src="https://user-images.githubusercontent.com/299579/81346772-8bff2c80-90c3-11ea-95bd-a308b0808295.png">

**Environment**:
- Grafana version: v7.0.0-beta1 (413aaf26d7)
- Data source type & version: any
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: MacOS, Firefox 75.0
- Grafana plugins: most of them
- Others:

**Comment by dprokop** [comment]
@peterholmberg can you have a look at this?

**Comment by peterholmberg** [comment]
@earwin Hello! Could you try upgrading to beta-3 and see if this error is still there?

**Comment by dprokop** [comment]
Unfortunately couldn't verify this on beta3 as twe had a bug there preventing from going to links section. But verified on master, and this seems to be fixed now.

**Comment by earwin** [comment]
Sorry, folks, for the late reply. This Grafana installation is behind a really crappy link, so upgrading was an issue.

Anyway, I'm running Grafana 7.0.0 now, and the issue is fixed in a sense that dashboard links are no longer working at all.

If configured like this:
<img width="406" alt="Screen Shot 2020-05-21 at 16 20 55" src="https://user-images.githubusercontent.com/299579/82563140-2a3cc900-9b7f-11ea-9103-90bd7a1ef6c0.png">
I get this result:
<img width="493" alt="Screen Shot 2020-05-21 at 16 19 24" src="https://user-images.githubusercontent.com/299579/82563168-388ae500-9b7f-11ea-8371-f56945623e2e.png">

To be fair, if I enable dropdown mode:
<img width="403" alt="Screen Shot 2020-05-21 at 16 21 06" src="https://user-images.githubusercontent.com/299579/82563215-4e98a580-9b7f-11ea-8339-6b44b2f61e52.png">
It works:
<img width="475" alt="Screen Shot 2020-05-21 at 16 20 35" src="https://user-images.githubusercontent.com/299579/82563244-5ce6c180-9b7f-11ea-9155-6b10a1069fcb.png">
