### ISSUE TITLE
Ability to control order of Stacked filtered values - by Value

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#24418]
**What would you like to be added**:
Please add ability to control order of the stacked values, when using filters  - by Value (AVG, SUM, MIN etc.). For now the values are order alphabetically by Label. Datasource is ElasticSearch 7.6.2.

![image](https://user-images.githubusercontent.com/29247982/81387446-fe4d2c80-9116-11ea-8ffa-6ebfdfca57ea.png)

**Why is this needed**:
This is important because in typical situation the most significant values should be at the top or at the bottom of the stack.

**Comment by torkelo** [comment]
switch to table legend, and include the "current"  value , then click this current table header to sort by it, stacking will then follow the order the items are in the legend:
![Screenshot from 2020-05-08 14-27-41](https://user-images.githubusercontent.com/10999/81405551-2ac57080-9138-11ea-9d4c-e042d9651f57.png)

**Comment by GrzegorzLyp** [comment]
That does not change order of series at all (even at Your screenshot). Even if it would change, the order should by dynamic since the most significant values might be different in different points in time. The following screenshot shows other system that gives the most significant values at the bottom. Will You do something about it ?

![image](https://user-images.githubusercontent.com/29247982/81426128-0f1e9200-9159-11ea-9117-55011e6db545.png)
