### ISSUE TITLE
LDAP auth support StartTLS ?

### ISSUE THREAD

**Issue by williamjoy** [grafana/grafana#2441]
not sure if this is implemented, for my LDAP server, I can use 389 port connection with startTLS encryption.
can you check if this feature is available please ?

thanks :)

**Comment by williamjoy** [comment]
searched starttls from dep lib, 
https://github.com/sgotti/ldap/blob/fixstarttlsv2/conn.go

But I know little about golang :(

**Comment by torkelo** [comment]
It seems to be supported. But cant you just use TLS? set use_ssl = true and it will use TLS

**Comment by williamjoy** [comment]
yes, tried use_ssl with port 636, got certificate error
`2015/08/06 01:35:22 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: LDAP Result Code 200 "": tls: failed to parse certificate from server: x509: RSA modulus is not a positive number
`

did not get any more logs from grafana, and my config is 

```
# Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# Ldap server host

# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if ldap server supports TLS
use_ssl = true
# set to true if you want to skip ssl cert validation
ssl_skip_verify = true
```

**Comment by williamjoy** [comment]
more info:
I can use Apache Directory to manage LDAP using ether StartTLS or LDAPS:// (SSL)

![screen shot 2015-08-06 at 09 45 15](https://cloud.githubusercontent.com/assets/3284451/9101960/e2447670-3c1f-11e5-80f5-b66ecea4b884.png)

**Comment by trehn** [comment]
Just an additional data point: I had only StartTLS configured and enabled LDAPS on port 636 just for Grafana, but not everyone has admin access to their LDAP server. So StartTLS support would be a good thing to have.

Using LDAPS, the connection worked just fine with a trusted certificate and OpenLDAP from Ubuntu 14.04.

**Comment by williamjoy** [comment]
yep , looking forward to the new feature :+1:

**Comment by williamjoy** [comment]
@trehn I don't have a trusted certificate, everything self-signed :(

**Comment by phalenor** [comment]
LDAPS was never really standardized, as it was a hack to add encryption to LDAPv2. LDAPv3 supports StartTLS over port 389. This needs to be supported.

In my testing, I set:
port = 389
use_ssl = true

and I received:
2016/01/14 14:55:58 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: LDAP Result Code 200 "": EOF
2016/01/14 14:55:58 [I] Completed /login 500 Internal Server Error in 3.031748ms


Setting port = 636 and everything works now (my organization's LDAP server supports LDAPS, for now...).

**Comment by phalenor** [comment]
Upon further reading, go-ldap has a StartTLS function. We would want another boolean option, say use_starttls, which is mutually exclusive to use_ssl. Optionally, setting port = 389 and use_ssl = true could simply imply StartTLS, since port 636 is /only/ used for SSL. I've seen other products do this.

The code would, roughly, need to call ldap.Dial(), then invoke StarTLS() on that connection.

**Comment by ccl0326** [comment]
Can anyone push a pr for this?
