### ISSUE TITLE
Custom units

### ISSUE THREAD

**Issue by rlcomte** [grafana/grafana#24427]
as far as I can tell the new unit mechanism of Grafana 6+ does not support custom units (anymore). 

**What would you like to be added**:
A mechanism to specify a custom unit, in which a format expression can be placed. Alternatively it could be a prefix/suffix specification.

**Why is this needed**:
Our customers have specific unit suffixes, that are not supported in the default unit set of Grafana. For example: bottles/minute, or mm/meter. There are of course tons of situations (especially in our manufacturing industry) where custom suffixes are used.

**Comment by torkelo** [comment]
just specify the unit in the unit select dropdown and select "Custom unit: whatever"

![Screenshot from 2020-05-08 14-25-02](https://user-images.githubusercontent.com/10999/81405348-c0accb80-9137-11ea-8648-11b01b5c0bfe.png)

If you need a prefix type "prefix: your prefix"
