### ISSUE TITLE
Using multi-value template variables in a repeated text/html panel

### ISSUE THREAD

**Issue by jahed** [grafana/grafana#2442]
Say I have a template which has the following values: 

```
$region = eu, us, sg
```

If I select all of them and use the variable in a repeated Text Panel like so:

```html
<img src="http://example.com/$region.png" />
```

It will evaluate to 3 panels with:

```html
<img src="http://example.com/{eu,us,sg}.png" />
<img src="http://example.com/{eu,us,sg}.png" />
<img src="http://example.com/{eu,us,sg}.png" />
```

Rather than 3 panels with:

```html
<img src="http://example.com/eu.png" />
<img src="http://example.com/us.png" />
<img src="http://example.com/sg.png" />
```

Is there a way to get the latter output? This is so I can have a header row with relevant images for each column.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master!
