### ISSUE TITLE
Missing ability to hide column in v7.0.0 beta3

### ISSUE THREAD

**Issue by Atomicbeast101** [grafana/grafana#24431]
**What happened**:
New version doesn't contain the ability to hide columns. 

*However, I do not know if Overrides is the replacement for this part. If so, then I don't see the option to hide in that case.*

**What you expected to happen**:
Option to hide columns.

**How to reproduce it (as minimally and precisely as possible)**:
Create a table panel and set the format to Table format. It would show all columns for a metric but no option to hide each column.

**Anything else we need to know?**:
This was not the issue in v6.7.3 and previous versions.

**Environment**:
- Grafana version: v7.0.0-beta3
- Data source type & version: Prometheus v2.17.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: All default ones

**Comment by torkelo** [comment]
Use the Organize fields transform (in transform tab), with it you can hide, change order and rename fields (ie columns for table panel)
