### ISSUE TITLE
Data link doesn't convert ${__cell} to its value in table cell - v7.0.0 beta3

### ISSUE THREAD

**Issue by Atomicbeast101** [grafana/grafana#24440]
**What happened**:

**What you expected to happen**:
I'm expected to see the site id instead of ${__cell} in the URL but instead it shows ${__cell} instead:
![](https://i.imgur.com/Mb0TOVC.png "Table cell to click")
![](https://i.imgur.com/hkErmpb.png "What URL shows when hovering over the cell")

**How to reproduce it (as minimally and precisely as possible)**:
Create an override for a column and set the URL with ${__cell} in it.
![](https://i.imgur.com/ggsGm96.png "Override configuration")

**Anything else we need to know?**:
Worked in v6.7.3 and below.

**Environment**:
- Grafana version: v7.0.0 beta3
- OS Grafana is installed on: Ubuntu v18.04
- User OS & Browser: Windows 10 & Chrome

**Comment by torkelo** [comment]
Use ${__value.numeric}

**Comment by Atomicbeast101** [comment]
Is it done by **${__value.1}** or **${__value.one}**? Both of them don't work for me.

**Comment by torkelo** [comment]
${__value.numeric}  is the value for the current cell

**Comment by Atomicbeast101** [comment]
Also it may be great if there's a description on this by "URL" field name here:
![](https://i.imgur.com/TCSMZuq.png "")

**Comment by Atomicbeast101** [comment]
**${__value.numeric}** returns NaN value. Is this expected?

**Comment by Atomicbeast101** [comment]
Ah that's for integer/double values. This README helped: [https://github.com/grafana/grafana/blob/8c2107cd35ad4846649d783ac76bef2e2607da72/docs/sources/reference/datalinks.md](url)
