### ISSUE TITLE
New Relic support for EU availability zone

### ISSUE THREAD

**Issue by harrykimpel** [grafana/grafana#24445]
**What happened**:
I tried to connect the New Relic Datasource plugin (https://grafana.com/grafana/plugins/grafana-newrelic-datasource) to my New Relic account that is deployed in New Relic's EU region.

**What you expected to happen**:
New Relic datasource plugin tries to pull data from https://insights-api.newrelic.com (= US region) and not from https://insights-api.eu.newrelic.com (= EU region).

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a New Relic account in EU region and try to set-up the Grafana plugin.

**Anything else we need to know?**:

**Environment**:
- Grafana version: any
- Data source type & version: n/a
- OS Grafana is installed on: any
- User OS & Browser: any
- Grafana plugins: New Relic Datasource
- Others: n/a

**Comment by torkelo** [comment]
Opened an issue for this in our private new relic data source repo.  

You should also open support ticket if you want to track the status of this issue.
