### ISSUE TITLE
FR: Show Relative Time in Hover

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#2444]
In Grafana the hover legend shows absolute time:

![screen shot 2015-08-05 at 10 03 13 am 1](https://cloud.githubusercontent.com/assets/1692624/9087566/7c50f954-3b59-11e5-8b78-cbb555802c12.png)

A feature we added to Bosun's graphing page is to also show the relative time, which I have found is helpful in avoiding any brainfarts around time:

![bosun_ _graph](https://cloud.githubusercontent.com/assets/1692624/9087603/c4de6c2e-3b59-11e5-940f-06dc14d03015.png)

I find myself wishing Grafana had the same.

**Comment by torkelo** [comment]
good idea!

**Comment by utkarshcmu** [comment]
@kylebrandt Here is the preview with what I have done in the PR:

<img width="1079" alt="screen shot 2015-10-27 at 10 03 33 pm" src="https://cloud.githubusercontent.com/assets/1019609/10780116/3ef940d6-7cf7-11e5-9b10-3ffec14dd1e6.png">

Now, the question for you and @torkelo is should we show both absolute time and relativeTime or just one of these at a time? IMO, we should show just one of these.

**Comment by utkarshcmu** [comment]
How about this with both absolute and relative timestamp, when the user select "Relative timestamp" checkbox?

<img width="841" alt="screen shot 2015-10-27 at 11 02 09 pm" src="https://cloud.githubusercontent.com/assets/1019609/10780815/f2c76ad2-7cfe-11e5-80cf-b0732e02000a.png">

**Comment by kylebrandt** [comment]
I agree with Utkarsh on showing both. It does block more of the graph, but
it really is convenient. Or allow for both options?

On Wed, Oct 28, 2015 at 2:04 AM, Utkarsh Bhatnagar <notifications@github.com

**Comment by torkelo** [comment]
yea, I think showing both (always, no option) might be ok

**Comment by utkarshcmu** [comment]
OK. Thanks for the feedback guys, will make the change and push another commit to the PR.

**Comment by utkarshcmu** [comment]
Code changed & committed. #3058 is ready now to get merged. Please review.

**Comment by bergquist** [comment]
I really like this idea. 
Makes it easier for me to get a mental model of the data.

closed by https://github.com/grafana/grafana/pull/3058
