### ISSUE TITLE
Grafana does not start on ubuntu 20.04

### ISSUE THREAD

**Issue by cschneider** [grafana/grafana#24464]
**What happened**:

I followed the docs to install grafana:
sudo apt-get install -y apt-transport-https
sudo apt-get install -y software-properties-common wget
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
sudo apt-get update
sudo apt-get install grafana
sudo systemctl daemon-reload
sudo systemctl start grafana-server
sudo systemctl status grafana-server
--
Job for grafana.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status grafana.service" and "journalctl -xe" for details.
--
May 09 09:01:53 odroid64 systemd[1]: grafana.service: Can't open PID file /run/grafana.pid (yet?) after start: Operation not permitted
May 09 09:01:53 odroid64 systemd[1]: grafana.service: Failed with result 'protocol'.

**What you expected to happen**:
Grafana should start

**How to reproduce it (as minimally and precisely as possible)**:
Follow same steps

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.4
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser:
- Grafana plugins:
- Others:
Odroid-C2
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

**Comment by cschneider** [comment]
One interesting observation. In the error I see:
Can't open PID file /run/grafana.pid

but in /etc/init.d/grafana I see:
PID_FILE=/var/run/$NAME.pid

**Comment by torkelo** [comment]
/etc/init.d/grafana  is not used if you have systemd , 

Can you check the systemd spec file? any env variables you have overriden?

**Comment by torkelo** [comment]
closing due to lack of updates
