### ISSUE TITLE
Auto refresh in the dashboard resets the page to 1

### ISSUE THREAD

**Issue by rnmulchandani** [grafana/grafana#24462]
I am using the Grafana version `6.6.2`. I have designed one `Dashboard`. It has `Table` as a panel. This table can contain a number of records. This table uses the pagination to show the records when there are large number of records.
Here, I am facing one problem. Whenever I select the auto refresh interval as `1m` on the dashboard and let's say I am on page number 3 then it automatically redirects me to page number 1.
Is it the default grafana behavior? Is there any way to restrict this?

**Comment by torkelo** [comment]
Fixed in new table panel coming in 7.0, has scroll that remembers position
