### ISSUE TITLE
Grafana 2.1 - Where is the LDAP verbose log?

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#2447]
Can't get LDAP working. Enabled verbose, but don't see anything related to LDAP in /var/log/grafana/grafana.log other than

    2015/08/05 18:11:25 [login.go:98 LoginPost()] [E] Invalid username or password: Invalid Username or Password

**Comment by torkelo** [comment]
LDAP verbose logging will log user info gotten fro LDAP,  seems like the i tial bind does not. What is you LDAP config?

**Comment by druchoo** [comment]
I know i'm doing something wrong but was hoping logging would point me in the right direction. I have LDAP working in apache for a separate app. I just need to translate to you Grafana syntax.

```
# Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# Ldap server host
host = "mycompanyad.mycompany.net"
# Default port is 389 or 636 if use_ssl = true
port = 3268
# Set to true if ldap server supports TLS
use_ssl = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false

# Search user bind dn
bind_dn = "dc=mycompany,dc=net"
# Search user bind password
bind_password = 'password'

# Search filter, for example "(cn=%s)" or "(sAMAccountName=%s)"
search_filter = "(sAMAccountName=%s)"
# An array of base dns to search through
search_base_dns = ["dc=mycompany,dc=net"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=admins,dc=grafana,dc=org"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
group_dn = "cn=users,dc=grafana,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"
```

Working Apache config:

```
  <Location /myapp/>
    Options ExecCGI FollowSymLinks
    AuthBasicProvider ldap
    AuthType Basic
    AuthzLDAPAuthoritative off
    AuthName "LDAP Authentication"
    AuthLDAPURL "ldap://mycompanyad.mycompany.net:3268/dc=mycompany,dc=net?sAMAccountName?sub?(objectClass=*)" NONE
    AuthLDAPBindDN "readonlyuser@mycompany.net"
    AuthLDAPBindPassword "password"
    Require valid-user
  </Location>
```

**Comment by torkelo** [comment]
in apache config you have   AuthLDAPBindDN "readonlyuser@mycompany.net"  but in Grafana ldap config you have bind_dn = "dc=mycompany,dc=net"  

is there a reason for the difference?

**Comment by druchoo** [comment]
*sigh*. And that would be the issue. Thanks.

**Comment by artkrz** [comment]
So how do I know that it actually got to LDAP ? I see same line in the log and I have no idea what the error is as no other line is present in the log :(

**Comment by torkelo** [comment]
@artkrz if there was a connection error that should be visible in the log

**Comment by artkrz** [comment]
What about other errors ?

**Comment by torkelo** [comment]
They should be there too, the only error that is not logged is authentication errora

**Comment by JulienChampseix** [comment]
When enabling verbode mode that will be good to have the query ldap sent to the server & catch the error/success returned by LDAP. Will be really usefull

**Comment by artkrz** [comment]
:+1:

**Comment by sunilpandit** [comment]
Hi ,

I am having issues authenticating user using LDAP . And I do not see any log messages . Here is the log and the ldap.toml . How can I diagnose this issue and get more log info ?

2015/10/07 16:22:27 [I] Starting Grafana
2015/10/07 16:22:27 [I] Version: 2.1.3, Commit: v2.1.3, Build date: 2015-08-24 0
3:02:44 -0500 CDT
2015/10/07 16:22:27 [I] Configuration Info
Config files:
  [0]: C:\grafana-2.1.3/conf/defaults.ini
Paths:
  home: C:\grafana-2.1.3
  data: C:\grafana-2.1.3\data
  logs: C:\grafana-2.1.3\data\log

2015/10/07 16:22:27 [I] Database: sqlite3, ConnectionString: file:C:\grafana-2.1
.3\data\grafana.db?cache=shared&mode=rwc&_loc=Local
2015/10/07 16:22:27 [I] Migrator: Starting DB migration
2015/10/07 16:22:27 [I] Login: Ldap enabled, reading config file: C:\grafana-2.1
.3\etc\grafana\ldap.toml
2015/10/07 16:22:27 [I] Listen: http://0.0.0.0:3000
2015/10/07 16:22:41 [I] Completed /login 200 OK in 14.0014ms
2015/10/07 16:22:52 [login.go:98 LoginPost()] [E] Invalid username or password:
Invalid Username or Password
2015/10/07 16:22:52 [I] Completed /login 401 Unauthorized in 105.0105ms
2015/10/07 16:22:52 [I] Completed /api/login/ping 401 Unauthorized in 5.0005ms


ldap.toml

#Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# LDAP server host
host = "10.173.130.54"
# Usual port is 389, or, if TLS is supported, 636
port = 389
# Set to true if LDAP server supports TLS
use_ssl = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = false

# Search user bind dn
bind_dn = "cn=%s,OU=USA,DC=visa,DC=com"
# Search user bind password
#bind_password = "grafana"

# Search filter, for example "(cn=%s)" or "(sAMAccountName=%s)"
search_filter = "(cn=%s)"
# An array of base dns to search through
search_base_dns = ["OU=USA,DC=visa,DC=com"]

# Map LDAP user attributes to Grafana user attributes
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

# Map LDAP groups to Grafana org roles
[[servers.group_mappings]]
group_dn = "cn=admins,dc=grafana,dc=org"
org_role = "Admin"
# The Grafana organization database id, optional, if left out, the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
group_dn = "cn=users,dc=grafana,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
# If you want to match all (or no LDAP groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"

Thanks
Sunil
