### ISSUE TITLE
Grafana 6.7.3 doesn't support new data source from elasticsearch 7.6.2

### ISSUE THREAD

**Issue by bijaykanshinew** [grafana/grafana#24470]
**i am not able to add elasticsearch as data source in grafana. Grafana throwing error "no data field named @timestamp found" **:

**Environment**:
- Grafana version: 6.7.3
- Elastic search version: 7.6.2

**Comment by fadjar340** [comment]
I use Grafana 6.7.3 with Elasticsearch 7.6.2 without problem.
Could you paste the datasource configuration here?


Regards,
Fadjar Tandabawana

**Comment by Estrax** [comment]
@bijaykanshinew please check your mapping in elasticsearch. Make sure you have a timestamp field called `@timestamp` that uses mapping to a date type (string or long values). If it's called differently, then you have to adjust `Time field name` value in your datasource configuration then.
