### ISSUE TITLE
Templating: Changing label does not trigger unsaved changes warning when moving away from dashboard without saving

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#24477]
**What happened**:
Two small things, should these be in two seperate issues?

**1) Dashboard variable changes are applied without hitting the `Update` button**
**2) After changing the dashboard variable and leaving the dashboard the change is discarded without confirmation**

**What you expected to happen**:

@ 1) Edit should only be saved when hitting `Update` otherwise the button is useless. This is already the case in `v6.7.2`
@ UI Team: The `Update` button is way at the buttom of the page and you have to scroll if there are many label values.
If you create a **new variable** instead it **will be lost without warning** if you do not hit the `Add` button at the bottom and go back to the dashboard. I managed to do that on several occasions..

@ 2) When leaving the dashboard there should be a confirmation before discarding changes. Grafana Version `6.7.2` **does** bring up a popup when leaving the dashboard:

![grafik](https://user-images.githubusercontent.com/33002073/81479494-e1eae600-9223-11ea-9d80-a2e595906d60.png)

**How to reproduce it (as minimally and precisely as possible)**:
- Create a dashboard with a variable, save the dashboard
- Edit the variable, e.g. change `Label` or enable `Multi-value`
- Go back to dashboard **without clicking `Update` button**
- The changes **are applied**
- Hit `F5` or navigate to another dashboard, the variable **change is discarded without confirmation**

**Anything else we need to know?**:
Startcondition, `Label` is "Commit", no `Multi-Value`:
![before](https://user-images.githubusercontent.com/33002073/81479406-448fb200-9223-11ea-89d2-cdfafe0dba90.png)

## Demo:
![CXZOxN3XjK](https://user-images.githubusercontent.com/33002073/81479414-4f4a4700-9223-11ea-8bbc-cafb646425d4.gif)

**Environment**:
- Grafana version: `Grafana v7.0.0-beta3 (2169fc1a3f)`
- Data source type & version: Prometheus
- OS Grafana is installed on: `Windows 10 1909`
- User OS & Browser: `Windows 10 1909` , Firefox 75

**Comment by torkelo** [comment]
The update button is for re-trigger the query options eval, (if it's a query variable). Not super intuitive I know. We will update this UX soon. 

I could not replicate your second problem, If I add a new variable and try to move to another dashboard / page I get unsaved changes warning. 

But if I only change label, I do not get a unsaved changes warning!

**Comment by Mario-Hofstaetter** [comment]
@torkelo  I guess my description was slightly confusing.

> If I add a new variable and try to move to another dashboard / page I get unsaved changes warning.

Yes! What I meant is **during creating a new variable**, any of the following links will discard the variable, even `Save dashboard`.

![new-var](https://user-images.githubusercontent.com/33002073/81501389-639c4b80-92d8-11ea-8b9d-7365b151a75c.png)

Felt pretty stupid after working 10 minutes on a new variable.

> We will update this UX soon.

👍
