### ISSUE TITLE
Azure Log Monitor Query with table join FAILS ($left.col1 = $right.col2)

### ISSUE THREAD

**Issue by s-ahuja** [grafana/grafana#24488]
**Issue:** Query Fails to Execute

**Expected:** Successful Query Execution. Works in Grafana v6.7. Doesnt work in v7.0+.

**Query to reproduce:**

let allocatable = Perf | where ObjectName == "K8SNode" | where CounterName == "memoryCapacityBytes" 
| where $__timeFilter(TimeGenerated) 
| where InstanceName startswith '$clusterid'
| summarize arg_max(TimeGenerated, * ) by Computer
| summarize a=toreal(sum(CounterValue))
| project a, b="abc";

allocatable 
| join kind=inner (
    Perf | where ObjectName == "K8SNode" | where CounterName == "memoryWorkingSetBytes" 
    | where $__timeFilter(TimeGenerated) 
    | where InstanceName startswith '$clusterid'
    | summarize arg_max(TimeGenerated, * ) by Computer
    | summarize x=toreal(sum(CounterValue))
    | project x,y="abc"
) on **$left.b == $right.y** // ERROR IS BECAUSE GRAFANA IS NOT ABLE TO PROCESS THIS LINE - IT WORKS ON v6.7, but doesnt work on v7 Beta 3 or master. It presumes there is a variable but this is a Azure Kusto syntax (and this should be ignored or escaped)
|project now(), (x/a) * 100

**Environment**:
- Grafana version: v7.0
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Azure App Service Container
- User OS & Browser: Chrome
- Grafana plugins: None Extra
- Others:

**Comment by daniellee** [comment]
Thanks for this well-written issue - the query you provided was very useful when fixing the bug.
