### ISSUE TITLE
Stat Panel: Tooltip for title and value (if value is hidden) 

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#24486]
**What would you like to be added**:
Tooltip showing measurement name for stat panel

**Why is this needed**:
I use the stat panel with background colors to show status of sensors. I set the size of the panel to be quite small, so I can see the color/status but the text is too small to be legible. It would be great if a tooltip could be set so I could simply hover over the box to see the measurement name if necessary.

I attempted doing something similar using Data Links, but it didn't seem capable of pulling data from the query.

**Comment by torkelo** [comment]
Yea, interested in an option to hide the title and show it in the tooltip for use cases like this. Even an option to hide the value and only show it in tooltip for really small boxes would be cool
