### ISSUE TITLE
Support for future relative time ranges

### ISSUE THREAD

**Issue by jdbaldry** [grafana/grafana#24498]
**What would you like to be added**:
The ability to configure a relative time range that extends into the future.

**Why is this needed**:
Over the weekend, I put together a Grafana data source using the [building a data source plugin tutorial](https://grafana.com/tutorials/build-a-data-source-plugin) (which is great by the way!). The [data source](https://github.com/departureboard-io/departureboard-io-datasource) uses the https://api.departureboard.io JSON API to draw a table of train schedule boards in Grafana. I was hoping to use the Grafana time picker to control how far into the future to request data (something like now -> now+1h) and use the auto-refresh functionality.

Though I haven't yet tested it, I believe I can use absolute time ranges for queries into the future but since they are absolute, they do not auto-refresh.

**Comment by sakjur** [comment]
You should already be able to select relative time ranges into the future (using `now+1h` should work) when you manually fill in the time range and that should work with auto-refresh. Do you run into some problems when trying?

**Comment by jdbaldry** [comment]
Sorry for the lack of useful information on the original post.

- I'm running `Grafana v7.0.0-beta3 (2169fc1a3f)`

Steps to reproduce:
1. Create a new dashboard
2. Enter an absolute time range of `now` -> `now+1h` in the time picker
3. Set to refresh.every 10s

The dashboard refreshes  every 10s but the time window displayed remains absolute.

Since playing around some more, I've managed to configure a relative future time range using the dashboard JSON but not through interaction with the time picker UI element.

**Comment by sakjur** [comment]
Thank you for the additional information, it seems to have worked the way you (and I 😛) wanted in 6.7 and have changed to this new behavior in 7.0. Tried to dig a little and I'm not sure if it's an intentional change or not so I'll forward this report to the team taking care of the time picker 🙂

**Comment by jdbaldry** [comment]
Awesome! Thanks for the help :) Let me know if there's anything I can do to assist.

**Comment by mckn** [comment]
Thanks for reporting this! It sounds like a bug.

I see what you are trying to do and it is probably an issue introduces when adding the custom time zone support. Will have a look at it during the day and try to open a fix for it asap.
