### ISSUE TITLE
Signing: manifest should allow missing files 

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#24492]
Our current manifest check verifies that everything in the manifest exists, and fails if a file does not exist.  In order to better support platform specific bundles, we should allow removing files from the bundle, but still having the signature work.  For example:

```
{
  "plugin": "grafana-googlesheets-datasource",
  "version": "1.0.0-dev",
  "files": {
    "LICENSE": "7df059597099bb7dcf25d2a9aedfaf4465f72d8d",
    "README.md": "08ec6d704b6115bef57710f6d7e866c050cb50ee",
    "gfx_sheets_darwin_amd64": "1b8ae92c6e80e502bb0bf2d0ae9d7223805993ab",
    "gfx_sheets_linux_amd64": "f39e0cc7344d3186b1052e6d356eecaf54d75b49",
    "gfx_sheets_windows_amd64.exe": "c8825dfec512c1c235244f7998ee95182f9968de",
    "module.js": "aaec6f51a995b7b843b843cd14041925274d960d",
    "module.js.LICENSE.txt": "7f822fe9341af8f82ad1b0c69aba957822a377cf",
    "module.js.map": "c5a524f5c4237f6ed6a016d43cd46938efeadb45",
    "plugin.json": "55556b845e91935cc48fae3aa67baf0f22694c3f"
  },
  "time": 1586817677115,
  "keyId": "7e4d0c6a708866e7"
}
```

Should not need the three binary copies (each 18MB)

This should be a simple change to:
https://github.com/grafana/grafana/blob/2661054fe8009704c55646c551e3bca7ed6ea6fe/pkg/plugins/manifest.go#L105

**Comment by ryantxu** [comment]
@aknuds1 -- can you take a look at this?

**Comment by aknuds1** [comment]
I will try to fix it!

**Comment by aknuds1** [comment]
@ryantxu On second thought, doesn't it make more sense to do the following instead?

1. Create the plugin package that should be distributed (i..e, with only the executable for the platform in question, f.ex. Linux/AMD64)
2. Create the manifest

That would remove the need for lax verification of the manifest, and I don't see why we can't do it this way?

**Comment by ryantxu** [comment]
discussed and decided it is not a good solution
