### ISSUE TITLE
GCP Cloud Monitoring - New Query Language

### ISSUE THREAD

**Issue by eli-jordan** [grafana/grafana#24490]
**What would you like to be added**:

GCP has just released a new language for querying metrics called MQL. The existing stackdriver (aka Cloud Monitoring) datasource obviously doesn’t support this yet, but it would be great if it could :-)

https://cloud.google.com/monitoring/mql

**Why is this needed**:

MQL provides a much more powerful query language than the current filtering options. Having the ability to use it in Grafana, would be very useful since the charting capabilities of stackdriver aren’t so great.

**Comment by daniellee** [comment]
This does sound interesting. I will add it to our roadmap discussions.

**Comment by neemiasjnr** [comment]
This looks very promising. In our current design we send all prometheus metrics to Cloud monitoring and I'd love to use Cloud monitoring as data source on grafana but the current query options are very limited. I'm looking forward to have this, I'm wondering if I can help @mtanda

**Comment by mtanda** [comment]
@neemiasjnr I finished my work for MQL support.
https://github.com/grafana/grafana/pull/26551

If you can build my branch Grafana code, please review/test my code :-)
