### ISSUE TITLE
CloudWatch/Metrics: AWS Shield Support, dimensions not available

### ISSUE THREAD

**Issue by JuH0LEE** [grafana/grafana#24499]
hello
I am using AWS shield advanced service.
 The shield service is "AWS / DDoSProtection" in the
 grafana: {"AllowedRequests", "BlockedRequests", "CountedRequests", "DDoSAttackBitsPerSecond", "DDoSAttackPacketsPerSecond", "DDoSAttackRequestsPerSecond", "DDoSDetected", "PassedRequests" 

But Can't load shield protected resource values.

'shield advanced' and 'AWS/DDoSprotection in Grafana' different services?
![image](https://user-images.githubusercontent.com/48516057/81544078-f4932580-93b1-11ea-9121-55baf614081b.png)

**Comment by aocenas** [comment]
@papagian @bergquist can you take a look, not sure if this can be an issue with the data in the aws account or is something that should be always available.

**Comment by JuH0LEE** [comment]
@aocenas hello can I know how the issue is going on?

**Comment by papagian** [comment]
sorry, I hadn't seen this.

Can you check in the network tab under developer tools what is the request/response of for the query for the dimension_values of `WebACL`?

**Comment by JuH0LEE** [comment]
@papagian  hello thanks to reply 
ok this is first image
![image](https://user-images.githubusercontent.com/48516057/81815801-6b245480-9565-11ea-80ec-d2869de96538.png)

check developer tools network tab 
![image](https://user-images.githubusercontent.com/48516057/81816014-b3437700-9565-11ea-911b-55fe932e55ad.png)

this image is my aws account ddos protection (shield advanced) cloudwatch metric
![image](https://user-images.githubusercontent.com/48516057/81816215-fdc4f380-9565-11ea-9548-bf318179aa03.png)


Please tell me if you need more information

**Comment by papagian** [comment]
I think that in the cloudwatch screenshot you have selected `DDoSAttackRequestsPerSecond` metric as opposed to `DDoSDetected` in the grafana one.

Also, according to the [docs](https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html):
`Shield Advanced posts the DDoSDetected metric with no other dimensions.`

**Comment by JuH0LEE** [comment]
@papagian 

No.
In fact, even with ddosattackrequestspersecond, it is the same thing that cannot be called.

![image](https://user-images.githubusercontent.com/48516057/82394671-9edf0d00-9a84-11ea-8842-4f9a1e77805d.png)

**Comment by papagian** [comment]
I think the problem is that `Region`, `Rule`, `RuleGroup` and `WebACL` dimensions are for the `WAF` namespace whereas for the AWS shield advanced metrics the dimensions [are different](https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html#set-ddos-alarms).

**Comment by JuH0LEE** [comment]
@papagian 
I think so
What should I fix? In grafana

**Comment by papagian** [comment]
@JuH0LEE 
Thanks for offering to fix it!

The dimensions are defined [here](https://github.com/grafana/grafana/blob/8b267c94ec594de3d793dc1605d5a6a0a5591653/pkg/tsdb/cloudwatch/metric_find_query.go#L141).

**Comment by JuH0LEE** [comment]
@papagian 
It does not mean that I modifying the source code.
But I can help you find the problem. I am actually using shield advanced service.

**Comment by JuH0LEE** [comment]
dimensions = AttackVector,ResourceArn
![image](https://user-images.githubusercontent.com/48516057/82550992-5e71b300-9b9a-11ea-82e1-8fb7e488b204.png)

**Comment by papagian** [comment]
thank you for the provided information.
I wil prepare a fix

**Comment by JuH0LEE** [comment]
@papagian · I'm grateful to you for all your help .
