### ISSUE TITLE
Alerting/Slack: notifications duplicating subject/title in channel message

### ISSUE THREAD

**Issue by cotman** [grafana/grafana#24495]
Hi,

We've seen a change in the way that Slack notifications are generated from our Grafana installation - possibly since we upgraded to v6.7.2.

We used to see notifications like this:

![slack_old_notification](https://user-images.githubusercontent.com/2264867/81533834-cdf7cf00-935e-11ea-9230-6f6680c05525.png)

...we now see notifications like this:

![slack_new_notification](https://user-images.githubusercontent.com/2264867/81533855-dc45eb00-935e-11ea-8ecc-9e435f710e33.png)

i.e. the alert subject/title is duplicated.

Not a big deal, but is this something that's configurable?  Couldn't see anything in the Slack setup documentation.

Thanks.

**Comment by odinsy** [comment]
We have the same problem since 6.7.* (now 7.0.0)
![grafana](https://user-images.githubusercontent.com/12398444/82415252-eebbd500-9a80-11ea-81a5-c69c2b27cbc3.png)

**Comment by kumode** [comment]
Same issue, looks very bad in my personal opinion and makes it cluttered for people reacting to the alerts.

**Comment by YakobovLior** [comment]
Any updates regarding this issue?
Thanks
Lior

**Comment by YakobovLior** [comment]
Hello,
any changes with this issue? is it solved on newer versions?

Thanks,
Lior

**Comment by aknuds1** [comment]
@YakobovLior Sorry, no, because we need to make a UX decision and we haven't got around to that yet.

**Comment by marefr** [comment]
@aknuds1 have you talked to UX about this? I feel we should just fix this. Guess reason this problem was introduced was due to slack deprecated their messaging api's?

**Comment by aknuds1** [comment]
@marefr I haven't been able to return to this. I don't remember exactly where we left it, but I think the ball might have been in UX' court. If we want to prioritize this issue, I'm fine with that.

**Comment by SunSparc** [comment]
I am glad I found this issue. I have been digging around trying to find a way to fix this. Glad to see it is not just me and apparently been going on for a year now.

**Comment by wbrowne** [comment]
Hey @codesome, just looping you in here as you have been doing some related work over in https://github.com/grafana/grafana/pull/32675. Was just wondering if you were aware of this and if the ported code might suffer the same problem?

**Comment by aknuds1** [comment]
If we want to work on this, I can reach out to @sarlinska and see if we can develop a new solution based on Slack's Block Kit, which is the non-legacy solution.

**Comment by codesome** [comment]
> Was just wondering if you were aware of this and if the ported code might suffer the same problem?

Haven't faced it in the ported code

**Comment by matsakonis** [comment]
Hi,

There is any new update about this issue? Is still happening with v8.

**Comment by codesome** [comment]
> Is still happening with v8.

Are you using the new alerting in v8?

**Comment by matsakonis** [comment]
I didn't understand. What do you mean by new alerting? 

We didn't change anything on our side and we still receiving duplicate subject/title in Slack channel

**Comment by codesome** [comment]
I was talking about [the unified alerting](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/) that was introduced in v8. But since you have not changed anything, you must be using the [old alerting](https://grafana.com/docs/grafana/latest/alerting/old-alerting/) (which the issue is for).

**Comment by matsakonis** [comment]
Yes, we are using the old alerting. There is any plan to fix this issue soon?

**Comment by codesome** [comment]
No ETA for this. But PRs are welcome :)

**Comment by guilherme-ton-afterverse** [comment]
hello my title is duplicated i upgraded to use the latest version of grafana with render image to have support in slack, but even using the unified alert my title keeps duplicating
<img width="501" alt="Captura de Tela 2022-07-27 às 09 33 36" src="https://user-images.githubusercontent.com/91225432/181255751-7e7f5174-ac25-47d2-99c9-f25608c44b04.png">
