### ISSUE TITLE
grafana/data: Add missing PanelEvents

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#24500]
Hi team, 
Hi @dprokop

I'll try to upgrade Flowcharting plugin to replace deprecated methods but @grafana/data does not have all the necessary declarations : 'template-variable-value-updated' missing from PanelEvents.
Same for  "dataFrameReceived", only in CoreEvent from app.

Using strings as events is deprecated and will be removed in a future version. (template-variable-value-updated)

my package.json : 
    "@grafana/data": "^7.0.0-beta.3",
    "@grafana/eslint-config": "1.0.0-rc1",
    "@grafana/runtime": "^7.0.0-beta.3",
    "@grafana/toolkit": "^7.0.0-beta.3",
    "@grafana/ui": "^7.0.0-beta.3",

BR,
Arnaud

**Comment by torkelo** [comment]
looks like dataFrameReceived is there. 

`template-variable-value-updated` is not a event for plugins
