### ISSUE TITLE
Observability: Cross team testing kitchen sink issue

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#24504]
Please add any found issues here:
- [ ] [Dashboards: cannot move scrollbar in logs panel using Chrome](https://github.com/grafana/grafana/issues/24569)
- [x] CloudWatch Logs: Auto-complete seems a bit broken. Trying to filter gives suggestions of 2 functions, replace and rtrim, instead of fields. Hard to understand if the idea is that when doing `filter <field> = "` should auto-complete available values for that field or not?
  ![explore_cloudwatch_logs_filter](https://user-images.githubusercontent.com/1668778/81668106-6d42c200-9444-11ea-8bdd-28827fd664e2.gif)
(See https://github.com/grafana/grafana/pull/24583)

- [x] CloudWatch Logs: If selecting a sample query including stats why doesn’t it switch to metrics mode automatically? Now, the query returns an error and first until you focus the logs editor and change something you get a message "You are trying to run a stats query in Logs mode. Switch to Metrics mode".
Fixed in https://github.com/grafana/grafana/issues/24333
  ![image](https://user-images.githubusercontent.com/1668778/81667763-f86f8800-9443-11ea-8454-28a03c26f1a1.png)
- [x] CloudWatch Logs: Two sections named `Functions` is very confusing
  ![image](https://user-images.githubusercontent.com/1668778/81667346-70897e00-9443-11ea-9f81-0ad61757a933.png)
  ![image](https://user-images.githubusercontent.com/1668778/81667366-797a4f80-9443-11ea-8cfb-bb79f0ca1c34.png)
(See https://github.com/grafana/grafana/pull/24583)
- [x] CloudWatch Logs: Clicking on auto-completed stream doesn't do anything just keep suggesting `streams` over and over again.
Fixed: https://github.com/grafana/grafana/pull/24581
  ![image](https://user-images.githubusercontent.com/1668778/81667515-a464a380-9443-11ea-8283-17fc540b6f7a.png)

**Comment by kaydelaney** [comment]
> CloudWatch Logs: If selecting a sample query including stats why doesn’t it switch to metrics mode automatically? Now, the query returns an error and first until you focus the logs editor and change something you get a message "You are trying to run a stats query in Logs mode. Switch to Metrics mode".

Should be fixed as of https://github.com/grafana/grafana/pull/24398

**Comment by kaydelaney** [comment]
> CloudWatch Logs: Two sections named Functions is very confusing
Could we get some clarification on this? @marefr I can't see exactly where in the provided screenshot the caret is such that those suggestions are given

**Comment by marefr** [comment]
@kaydelaney if I write `filter @message = ` and then `"` for example.

**Comment by aocenas** [comment]
Closing this as the only outstanding bug has a separate issue
