### ISSUE TITLE
[2.1] admin_user unavailable if you enable proxy auth?

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#2450]
If I use reverse proxy auth, how do I specify Admin users?

Previously I had the admin_user available.  But it seems like if you have proxy auth enabled, you are no longer able to log in as admin_user.

**Comment by torkelo** [comment]
you should be able to login as normal, but if you go through the auth proxy and you are logged in via that (it sends user header) that will override any login state you have in grafana. You either need to logout of your auth proxy or login to grafana directly (not go through auth proxy) or make your auth proxy user a super grafana admin or org admin

**Comment by blysik** [comment]
Understood.  Unfortunatley I'm not able to logout of the auth proxy, or go directly.  Ended up having to change the config temporarily, and make my proxy username an Admin.

Which brought up the problem of:
Making that user an Admin in the Main org doesn't mean that user can then create new orgs.

ie, an Org admin is not the same as an application admin.  Is that correct?

**Comment by blysik** [comment]
It looks like I need a way to make a proxy auth user a 'Grafana administrator'.

**Comment by torkelo** [comment]
Yes,  grafana admin flag is different than org admin role. You can set grafana admin permission in the user edit view in users section under admin

**Comment by michalbachowski** [comment]
I have overcome this issue by setting my username as "admin_user" (with no password) and let Grafana to setup the admin account (which happens only when creating new database I believe). That way when I logged in via auth.proxy I was given "Grafana administrator" rights.
