### ISSUE TITLE
Data source configuration: Saved credentials have a white background

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#24515]
**What happened**:
Create a new mysql data source and my saved credentials for grafana being populated in user and password field with a white background.

![image](https://user-images.githubusercontent.com/1668778/81558008-39589580-938d-11ea-89fe-0f9ddea0db9c.png)

**What you expected to happen**:
Dark background. Shouldn't probably fill in saved credentials for site in those fields in the first place.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login to grafana and save credentials in browser
2. Create a new mysql data source

**Environment**:
- Grafana version: 7.0.0-beta3
- User OS & Browser: Chrome 81

**Comment by AgnesToulet** [comment]
I couldn't reproduce it on beta or master, I think it's saved credential from Chrome and it's the reason why the input are white.
