### ISSUE TITLE
Github allowed_organizations not working as expected

### ISSUE THREAD

**Issue by srodrig0209** [grafana/grafana#2451]
I added
> allowed_organizations = compstak

but I'm getting
>Login Failed
Required Github organization membership not fulfilled

Also, my membership was public before I attempted this, so that's not it either.

**Comment by srodrig0209** [comment]
Nevermind. I had to append `,read:org` to the scopes line.

**Comment by confiq** [comment]
I would like just to add... 
scopes line should be:
```ini
[auth.github]
scopes = 'user:email, read:org'
```

**Comment by seanvree** [comment]
Hate to re-open this issue, but I'm having this issue:

Running Grafana V 4.0.2
OS:  Windows 10E (IIS)

Trying to use Grafana.net for auth:

enabled = true
allow_sign_up = false
client_id = Removed
client_secret = Removed
scopes = 'user:email, read:org'
allowed_organizations = Removed

**Comment by kravchyuriy** [comment]
Hi everyone
Have similar issues with GitHub OAuth and allowed_organizations config parameter. 
Constantly getting error when trying to login using "GitHub login button":

> Login Failed
> User not a member of one of the required organizations

Same error in grafana.log
My membership in required organisation set to public and I also can see that in response from GitHub API using OAuth app credentials.

My Github Auth config:
```
[auth.github]
enabled = true
allow_sign_up = true
client_id = #######################################
client_secret = #######################################
scopes = 'user:email, read:org'
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
;team_ids =
allowed_organizations = myorganization
```
Grafana version = 4.6.3 (commit: 7a06a47)
OS: Debian 8

**Comment by kravchyuriy** [comment]
Issue was solved by making and confirming organization access request at GitHub for Grafana instance: Profile -> Settings -> Applications -> Authorized OAuth Apps -> My Grafana ->Organization access
