### ISSUE TITLE
Broken layout for [Panel Edit → Display → Value] options in drop-down

### ISSUE THREAD

**Issue by lukasztyrala** [grafana/grafana#24513]
**What happened**:The display of options for `Value` (`Panel Edit` → `Display`) select is broken

**What you expected to happen**: Display of Names + descriptions

**How to reproduce it (as minimally and precisely as possible)**: Edit panel and select Value selectbox

**Anything else we need to know?**:

When opening the select for the first time:

<img width="344" alt="Zrzut ekranu 2020-05-11 13 09 49" src="https://user-images.githubusercontent.com/141744/81556096-0791ff80-938a-11ea-9fb7-92fd5e78315a.png">

After typing something, that results in short list, the layout is OK:

<img width="331" alt="Zrzut ekranu 2020-05-11 13 24 32" src="https://user-images.githubusercontent.com/141744/81556562-d403a500-938a-11ea-8083-dd42c151f6cf.png">

Broken for longer lists:

<img width="334" alt="Zrzut ekranu 2020-05-11 13 26 04" src="https://user-images.githubusercontent.com/141744/81556692-0b725180-938b-11ea-8ed6-24c28a4e28a7.png">

Seems like when the list overflows the drop-down window, the layout breaks:

<img width="330" alt="Zrzut ekranu 2020-05-11 13 26 22" src="https://user-images.githubusercontent.com/141744/81556713-14632300-938b-11ea-89ac-e992e18da246.png">

**Environment**:
- Grafana version: Version: 7.1.0-pre, Linux Version: 7.1.0, Package Iteration: 1589191595pr
- Data source type & version: DevEnv
- OS Grafana is installed on: MacOS 10.15.4 (19E287)
- User OS & Browser: Safari 13.1 (15609.1.20.111.8)
- Grafana plugins:
- Others: runnig on localhost (go+yarn)

**Comment by tskarhed** [comment]
This is likely related to Safari.  Can't reproduce since I don't have a Mac :slightly_frowning_face: @sakjur can reproduce.

**Comment by mckn** [comment]
@tskarhed will have a look at it.
