### ISSUE TITLE
Share Panel: Move Direct link rendered image to its own tab

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#24514]
**What would you like to be added**:
Move Direct link rendered image to its own tab in the dashboard share panel modal window.

**Why is this needed**:
Would make it more intuitive and understandable that you can export the panel as an image if there was a tab named `Image` or similar. The current link is very small and at the bottom currently and you'll miss it if you don't know it's there. 

![image](https://user-images.githubusercontent.com/1668778/81556246-47f17d80-938a-11ea-9f64-c6208b038e01.png)

**Comment by sarlinska** [comment]
@marefr I am reassigning this to @lukasztyrala as he's working on unifying modals.
