### ISSUE TITLE
PanelInspect: Download CSV output 

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#24517]
@torkelo @ryantxu as a followup work for PanelInspect I wanted to suggest the CSV output to reflect the actual contents of the table being displayed in the inspect. 

Currently both on master and in https://github.com/grafana/grafana/pull/24314 the downloaded CSV does not reflect the options that user selected (apply transformations and apply field config). The downloaded CSV is just raw data with selected data frame or data frame being a result of the in-panel-inspect transformation. That's because the display processors are executed in the Table component.

What are your thoughts on what the CSV file contents should be? Maybe you @sarlinska have some input based on the user interviews?

**Comment by sarlinska** [comment]
I don't have anything from users. But I can go and ask for some feedback so we can make an informed decision.

**Comment by mstrent** [comment]
@sarlinska @dprokop Hopefully this is relevant, but I had users going to panels and doing More -> Export (or was it "Download"?) CSV prior to upgrading to 7.x and passing those reports around. The time stamps in that export were human-readable.

Now with the 7.x Inspect -> Data -> Download CSV, you see human readable dates on screen, but the CSV contains Unix timestamps, which is pretty challenging for non-technical users to grok.

**Comment by dprokop** [comment]
@mstrent thanks for pointing this out. We are aware of that and will fix this in the upcoming versions, most probably 7.1. 

I have created an issue to followup on this https://github.com/grafana/grafana/issues/24973

**Comment by dprokop** [comment]
Closing this one as it's fixed in 7.1

**Comment by Hipska** [comment]
My users are complaining that the "Series as rows" mode is removed. Should that be a new issue?

Also, it seems that the "Apply field configuration" toggle is not doing any difference.

**Comment by torkelo** [comment]
We hope to add series as rows in 7.1 https://github.com/grafana/grafana/issues/24945

**Comment by Hipska** [comment]
@torkelo Thanks, but I was referring to this mode in the CSV export panel of graph panel. This feature is removed with the panel inspect feature.

And is it known that "Apply field configuration" toggle is not working?

**Comment by torkelo** [comment]
it is working fine

**Comment by torkelo** [comment]
it was just shown for old angular panels, will fix in upcoming patch so its hidden for panels that do not have field config options (old angular panels)

**Comment by hila3000** [comment]
Hi,
@torkelo 
Just wanted to verify if it's the same issue-
When trying to inspect->data of a table panel, it only shows one row. 
Is this known? part of the upcoming fix?

Thanks,
Hila

**Comment by torkelo** [comment]
We have not been able to replicate it so no fix yet

**Comment by qbnronin** [comment]
@torkelo & @dprokop we are still seeing this issue in version 7.1.
Grafana is only giving a few seconds worth of data when we attempt to "Inspect / Data", so of course, when you do Save CSV is only saving whatever is in the new table.  We need to be able able to export all data that is in the panel. 

The table we are using is derived from Prometheus data and it contains a few hundred rows, but when "Inspect / Data" we only get the last 10 seconds (although sometimes we only get 2 seconds)

We need a fix ASAP. Please! :-)
