### ISSUE TITLE
Fields gone missing after applying filter by name transformation 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#24518]
**What happened**:
Added a filter by name transformation and clicked one series/field and fields/series changed to a single one named value.

First:
![image](https://user-images.githubusercontent.com/1668778/81559162-33fc4a80-938f-11ea-9088-95edc86ff8cc.png)

After clicking on 10.0.100.1:
![image](https://user-images.githubusercontent.com/1668778/81559188-4080a300-938f-11ea-8eda-9045c9bf0973.png)

**What you expected to happen**:
The field/series I selected to be selected.

**How to reproduce it (as minimally and precisely as possible)**:
1. `make devenv sources=mysql
2. Open provisioned dashboard: Datasource tests - MySQL
3. Edit "Average logins / $summarize" panel
4. Switch to transformation tab and add "Filter by name" transformation
5. Select on of the series, e.g. 10.0.100.1
6. Fields disappearing 

**Environment**:
- Grafana version: 7.0.0-beta3
- User OS & Browser: Chrome 81

**Comment by torkelo** [comment]
@ryantxu any idea what is going on?

**Comment by mckn** [comment]
Looks like when filtering on one of the series only that series values is displayed. Not sure why but looking into the reason now.
