### ISSUE TITLE
Grafana scripted dashboards set time issue with the from/to (#787)

### ISSUE THREAD

**Issue by terrencezli** [grafana/grafana#2452]
I've noticed that when passing in a parameter to the dashboard time range, there seems to be a bug with what is allowed to be passed in.

For the example:
/dashboard/script/scripted_events.js?tag=hi&tag=bye&tag=hi&graph=abc.def&from=2015-05-01T17:00:00Z&to=2015-07-30T19:00:00.000Z
The ISO string format only works for the time describing to

The API call:
/api/datasources/proxy/3/events/get_data?from=1438275600&to=NaN&tags=hi

![screen shot 2015-08-05 at 3 40 07 pm](https://cloud.githubusercontent.com/assets/6879559/9099761/6e6d52cc-3b88-11e5-959a-40ca614db049.png)

For the example:
/dashboard/script/scripted_events.js?tag=hi&tag=bye&tag=hi&graph=abc.def&from=1438275600000&until=1438282800000
The unix offset format only works for the time describing from

The API call:
/api/datasources/proxy/3/events/get_data?from=2&until=1438282800&tags=hi

![screen shot 2015-08-05 at 3 40 22 pm](https://cloud.githubusercontent.com/assets/6879559/9099765/72898e34-3b88-11e5-860e-c0b6d6ad456d.png)

**Comment by torkelo** [comment]
So set the time range via url, use` from` and `to`

supported formats are:
 - epoch in milliseconds
 - `now`
 - YYYYMMDD
 - YYYYMMDDTHHmmss
