### ISSUE TITLE
JSON editor not shown when trying to save provisioning dashboard

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#24525]
**What happened**:
When trying to save provisioned dashboard I got the "cannot save provisioned dashboard modal", but the JSON content is not shown in the regular JSON editor and includes functions for example which is wrong. Also, clicking  "Copy JSON to clipboad" provide no feedback if the content was copied or not. 
![image](https://user-images.githubusercontent.com/1668778/81571025-ad9d3400-93a1-11ea-8ce7-c613812d190a.png)

Compare with export dashboard / view JSON and copy to clipboard:
![image](https://user-images.githubusercontent.com/1668778/81571185-e5a47700-93a1-11ea-9cec-4eea2d6bbc4f.png)

**What you expected to happen**:
Proper JSON editor that I can select all JSON content from copy manually. Also feedback when selecting "Copy JSON to Clipboard".

**How to reproduce it (as minimally and precisely as possible)**:
Try to save a provisioned dashboard.

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.0.0-beta3

**Comment by torkelo** [comment]
We do not have a json text editor in react, not sure what we have time for here for 7.0.

**Comment by dprokop** [comment]
We decided to show textarea instead
