### ISSUE TITLE
Sign external plugins (GEL) as part of CI

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#24538]
**What happened**:
Sign external bundled plugins (GEL) as part of CI pipelines. cc: @kylebrandt 

The CI build for gel should run the signing tool... likely another target here:
https://github.com/grafana/gel-app/blob/master/Magefile.go#L79

perhaps the `zip` task should also be moved to grabpl?   Should be:
* build
* create manifest
* zip (includes manifest)

**Comment by bergquist** [comment]
Why would we need to zip it? I assume we are zipping the complete package later anyway? Maybe Im missing something :)

**Comment by aknuds1** [comment]
@bergquist I'm also unsure, it's @ryantxu's edit :)

Maybe there's a misunderstanding. The idea of this issue is to generate a signed manifest for GEL when bundling it with Grafana packages, during Grafana's CI pipelines.

**Comment by bergquist** [comment]
I reviwed it and merged it. But I was to lazy to create testfiles like you did. Kudos to you! 

> Maybe there's a misunderstanding. The idea of this issue is to generate a signed manifest for GEL when bundling it with Grafana packages, during Grafana's CI pipelines.

Ah so by "zip (includes manifest)" you mean zipping the full package?
