### ISSUE TITLE
Thresholds in the new Table Panel do not work properly with LCD gauge

### ISSUE THREAD

**Issue by NyanChanMeow** [grafana/grafana#24535]
**What happened**:
I created a new table panel and set the override attribute for a column, where the `cell display mode` is set to `LCD gauge` and `Thresholds` is set to `Green: Base, Yellow: 0.5, Red: 0.9`. Then set `Value Mapping` for it: Range -2 to 2 is mapped to **empty value**. When the value is mapped to empty value, the `LCD gauge` cannot display the color set by Thresholds normally.
**What you expected to happen**:
When the value is mapped to empty value, the `LCD gauge` should display the color set by Thresholds normally.
**How to reproduce it (as minimally and precisely as possible)**:

1. create a new table panel
2. set the override attribute for a column, where the `cell display mode` is set to `LCD gauge` and `Thresholds` should be set normally
3. set `Value Mapping` with range and mapped to empty value
4. the `LCD gauge` should display the color set by Thresholds abnormally if the value is int he range

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/47969524/81690642-28dc1400-948e-11ea-91ca-be94c9840e8f.png)
![image](https://user-images.githubusercontent.com/47969524/81690707-47daa600-948e-11ea-88b5-9d12fe87fbaa.png)

**Environment**:
- Grafana version: 7.0.0 beta3
- Data source type & version: Prometheus 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
- OS Grafana is installed on: Debian buster (SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux)
- User OS & Browser: Windows 10, Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Unable to replicate 

https://play.grafana.org/d/zJKc7vgMk/lcd-gauge-in-table-copy?orgId=1

![Screenshot from 2020-05-13 08-55-28](https://user-images.githubusercontent.com/10999/81780869-86f11180-94f7-11ea-8050-b900967aa9af.png)

**Comment by dprokop** [comment]
@NyanChanMeow are you still experiencing this issue?
