### ISSUE TITLE
Query options overflowing on small screen

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#24531]
**What happened**:
![Screenshot from 2020-05-11 16-51-01](https://user-images.githubusercontent.com/1438972/81575978-f8ba4580-93a7-11ea-8010-d70671266e9b.png)

**What you expected to happen**:
Not that.

**How to reproduce it (as minimally and precisely as possible)**:
Edit panel and resize window accordingly.

**Anything else we need to know?**:
A little bit of thinking might be needed to handle this

**Comment by torkelo** [comment]
That is a very small screen, adding to the long list of mobile support issues :)
