### ISSUE TITLE
LDAP authentication using rfc2307bis schema

### ISSUE THREAD

**Issue by sposs** [grafana/grafana#2454]
Hi,
In the LDAP config file, there is this need to define the 'member_of' attribute. This seems to only be available for Active Directory, not necessarily other implementation. In particular, in my case I use a rfc2307bis schema implementation which does not have anything like that. Is there a work around this limitation? 

Side comment: the LDAP plugin is great, but the documentation is a little weak, in particular regarding the options that are possible and those that are mandatory...

**Comment by torkelo** [comment]
You do not need to use memberOf, but then you can't use the LDAP group to grafana user permission mapping

**Comment by sposs** [comment]
If I remove it I get the following error:
2015/08/06 10:52:50 [I] Login: Ldap enabled, reading config file: /etc/grafana/ldap.toml
2015/08/06 10:52:50 [I] Listen: http://0.0.0.0:3000
2015/08/06 10:52:53 [I] Ldap User Info: (*login.ldapUserInfo)(0xc208268070)({
 DN: (string) (len=41) "uid=user,cn=users,dc=internal,dc=alp",
 FirstName: (string) (len=9) "FirstName",
 LastName: (string) (len=4) "LastName",
 Username: (string) (len=9) "user",
 Email: (string) (len=28) "user@company.com",
 MemberOf: ([]string) {
 }
})

2015/08/06 10:52:53 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: pq: prepared statement "6" already exists

**Comment by torkelo** [comment]
are you using postgres?

**Comment by sposs** [comment]
Yes!

Le ven. 7 août 2015 10:08, Torkel Ödegaard <notifications@github.com> a
écrit :

**Comment by torkelo** [comment]
I tried to replicate this with postgres 9.4.4, did not get any errors. 

What kind of postgres setup do you use? PgBouncer? 
http://stackoverflow.com/questions/7611926/postgres-error-prepared-statement-s-1-already-exists
