### ISSUE TITLE
Unauthorized at first login/pwd change if behind a load balancer

### ISSUE THREAD

**Issue by vargaendre** [grafana/grafana#24548]
**What happened**:
I installed Grafana with docker on an AWS EC2 instance. Set up an Application Load Balancer (ALB) and created a target group for Grafana listening on port 3000. Created a subdomain grafana.mydomain.com and set it up for the load balancer to route to Grafana. The load balancer is responsible for handling HTTPS, having Amazon issued certificates. Grafana is set up with http protocol.
Then I opened https://grafana.mydomain.com got the login screen, logged in first time with admin/admin then changed the password then the dashboard was loading, but suddenly I got a bit error saying "Unauthorized" and redirected back to login. The password change was successful though.

**What you expected to happen**:
Being able to log in and then go to the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
As described above. Key is the load balancer.

**Anything else we need to know?**:
The thing only happens behind the load balancer. If I just type http://myip:3000 into the browser, then it works. Unfortunately it's not an option.
Tried to set secure_cookie = true but it did not help.

**Environment**:
- Grafana version: latest (11th May, 2020)
- Data source type & version: none yet configured
- OS Grafana is installed on: Ami linux and running in docker (alpine)
- User OS & Browser: tried Firefox and Chrome, on MacOS
- Grafana plugins: none
- Others: Failing call is /api/dashboards/home

Please help, what do I need to do to make this work?
I've seen multiple people having this issue, but no real solution so far.

**Comment by torkelo** [comment]
Make sure your using MySQL or Postgres if running Grafana behind a load balancer (if you have multiple grafana servers behind load balancer)

and make sure root_url https://grafana.com/docs/grafana/latest/installation/configuration/#root-url is set to the public browser url of your load balancer

**Comment by vargaendre** [comment]
Thank you for the quick reply. 
I don't have multiple servers, just one, but I think storage is not important now.

I tried what you suggested, but I still have the exact same issue.

Any more ideas what could be wrong?

**Comment by torkelo** [comment]
no, check the http traffic, cookies etc (and cookie path)

**Comment by vargaendre** [comment]
I only found one cookie, with path "/". I don't know what to look at.

Interesting side issue I noticed is that after I created a new user (so I don't need to use admin), I could not log in with any user (even with myip:port address). I ended up recreating the service.
