### ISSUE TITLE
SMS integration

### ISSUE THREAD

**Issue by aashray1495** [grafana/grafana#24546]
Is there anyway that one could forward sms from grafana to user's phone? If there is not an existing solution, what other alternatives are out there? I know that pagerduty could be one.

**Comment by ivanahuckova** [comment]
Hello @aashray1495, here are some answers for this question from our community: 
https://community.grafana.com/t/grafana-alert-via-sms/28408
https://community.grafana.com/t/how-to-implement-a-customize-sms-notification-channel/2478/7

Next time it is better to ask questions like this on our community site. 🙂

**Comment by aashray1495** [comment]
Thank you for pointing me in the right direction, Ivana. Will keep the rest in mind.
