### ISSUE TITLE
grafana 2.1.0 + influxdb 0.9.2 basic auth errors

### ISSUE THREAD

**Issue by nonsenz** [grafana/grafana#2455]
hi,

beeing on the "Edit data source" page: when i try to enable basic auth in the datasource config via checkbox the connection test won't work. but when i add the basic auth directly to the Url above (like "foo:bar@influxdbhost") and disable the checkbox the connection works fine. is there a bug in the basic auth option?

**Comment by torkelo** [comment]
did you use "direct" or proxy access method?

**Comment by nonsenz** [comment]
direct

**Comment by torkelo** [comment]
Check the chrome dev tools, I had some issues getting direct an basic auth to work with InfluxDB 0.9, CORS headers did not allow for authenticated requests from another domain.
