### ISSUE TITLE
Can't access Log Groups that aren't in the scroll down

### ISSUE THREAD

**Issue by eroub** [grafana/grafana#24554]
The feature and therefore bug was introduced #23566 in I believe ` pkg/tsdb/cloudwatch/log_actions_test.go`

**What happened**:
A Log Group I am trying to query is not in the top 50 alphabetically and therefore not in the scroll down menu. Typing in the prefix into the Log Group menu did not return the Log Group. Typing in the Log Group prefix only returns Log Groups that can also be found in the scroll down.

**What you expected to happen**:
Typing in the Log Group to return the requested Log Group.

**How to reproduce it (as minimally and precisely as possible)**:
Connect to a cloudwatch data source with >50 Log Groups and try to access and query a Log Group that falls near the end alphabetically (i.e. not in the top 50 and therefore not listed on the scroll down)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.0-beta3
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Docker 19.03.6
- User OS & Browser: Ubuntu 18.04, Firefox 76.0
- Grafana plugins: n/a
- Others: n/a

**Comment by Sandarbh-Z** [comment]
@eroub I'm still facing this issue. I'm using the following version of Grafana:
```
Version 7.5.11 (commit: 6f8c1d9fe4, branch: HEAD)
```
I'm unable to find the Cloudwatch logs which are not in the first dropdown list which has around 50 groups sorted lexicographically. Can you please help me fix this?

**Comment by guneesh27** [comment]
I am also facing the same issue. Can you please help.

**Comment by quangdovmo** [comment]
I am facing the same issue too. Please help me

**Comment by quangdovmo** [comment]
I have finally resolved this issued by typing full name of logs group instead of typing some characters of its name :D. You can try it and you will get your logs group magically :dancing_men:

**Comment by hanilz** [comment]
I'm also dealing with this issue and can't seem to resolve it. Any help?

**Comment by akshaykrjain** [comment]
This issue still persists.
