### ISSUE TITLE
Grafana 7 Table sorting issues 

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#24557]
**What happened**:
Using a bar gauge inside a Grafana 7 tabel panel, sort does not sort based on percentages (at least with % unit 0.0 - 1.0)

**What you expected to happen**:
Numerical sorting

**How to reproduce it (as minimally and precisely as possible)**:
Add a bar gauge with unit: percent (0.0 - 1.0) and try to sort on this column

**Anything else we need to know?**:
![Screen Shot 2020-05-12 at 14 49 18](https://user-images.githubusercontent.com/4478053/81643185-092df700-9460-11ea-9b9b-35db68fbce0d.png)

**Environment**:
- Grafana version: 7
- Data source type & version: Prometheus
- OS Grafana is installed on: RedHat 7.8
- User OS & Browser: MacOS Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
strange, unable to replicate. Can you disable gauge and the unit, does sort work then? Just unit, does sort work? etc.

**Comment by maemigh** [comment]
It worked after I removed unit, and continued to work after I added unit back. 

However, the column next to it "TX Utilization" continues to fail to sort even after removing "gauge" and "unit" overrides.

**Comment by maemigh** [comment]
I modified the name values from the output, but here is the data structure of the panel:
```
[
  {
    "fields": [
      {
        "name": "ifDescr",
        "type": "string",
        "config": {
          "filterable": true,
          "title": "Interface",
          "custom": {
            "align": "left"
          }
        },
        "state": {
          "title": "Interface",
          "scopedVars": {
            "__series": {
              "text": "Series",
              "value": {
                "name": "Series (0)"
              }
            },
            "__field": {
              "text": "Field",
              "value": {
                "name": "Interface",
                "labels": ""
              }
            }
          }
        }
      },
      {
        "name": "ifAlias",
        "type": "string",
        "config": {
          "filterable": true,
          "title": "Description",
          "custom": {
            "align": "left"
          }
        },
        "labels": {},
        "state": {
          "title": "Description",
          "scopedVars": {
            "__series": {
              "text": "Series",
              "value": {
                "name": "Series (0)"
              }
            },
            "__field": {
              "text": "Field",
              "value": {
                "name": "Description",
                "labels": "",
                "label": {}
              }
            }
          }
        }
      },
      {
        "name": "Value #A",
        "type": "number",
        "config": {
          "title": "RX utilization",
          "custom": {
            "align": "left",
            "displayMode": "gradient-gauge"
          },
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "#EAB839",
                "value": 0.9
              },
              {
                "color": "red",
                "value": 0.95
              }
            ]
          },
          "mappings": [],
          "color": {
            "mode": "thresholds"
          },
          "decimals": 2,
          "noValue": "<0.01%",
          "unit": "percentunit",
          "min": 0,
          "max": 1
        },
        "labels": {},
        "state": {
          "title": "RX utilization",
          "scopedVars": {
            "__series": {
              "text": "Series",
              "value": {
                "name": "Series (0)"
              }
            },
            "__field": {
              "text": "Field",
              "value": {
                "name": "RX utilization",
                "labels": "",
                "label": {}
              }
            }
          }
        }
      },
      {
        "name": "Value #B",
        "type": "number",
        "config": {
          "title": "TX utilization",
          "custom": {
            "align": "left",
            "displayMode": "gradient-gauge"
          },
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "#EAB839",
                "value": 0.9
              },
              {
                "color": "red",
                "value": 0.95
              }
            ]
          },
          "mappings": [],
          "color": {
            "mode": "thresholds"
          },
          "decimals": 2,
          "noValue": "<0.01%",
          "unit": "percentunit",
          "min": 0,
          "max": 1
        },
        "labels": {},
        "state": {
          "title": "TX utilization",
          "scopedVars": {
            "__series": {
              "text": "Series",
              "value": {
                "name": "Series (0)"
              }
            },
            "__field": {
              "text": "Field",
              "value": {
                "name": "TX utilization",
                "labels": "",
                "label": {}
              }
            }
          }
        }
      }
    ],
    "values": {
      "ifDescr": [
        "Vlan1",
        "Vlan2",
        "Vlan3",
        "Vlan4"
      ],
      "Time": [
        1589268240000,
        1589268240000,
        1589268240000,
        1589268240000
      ],
      "ifAlias": [
        "222222",
        "xxxxxxxxxxxxxxxx",
        "",
        null
      ],
      "Value #A": [
        0.00770589712,
        0.04023171505333333,
        0.04057916566666667,
        null
      ],
      "Value #B": [
        0.05351108709333333,
        0.012334448653333335,
        null,
        0.04313851190666667
      ]
    },
    "first": [
      "Vlan1",
      "Vlan2",
      "Vlan3",
      "Vlan4"
    ],
    "length": 4,
    "meta": {
      "transformations": [
        "seriesToColumns",
        "organize"
      ]
    }
  }
]
```

**Comment by garbled1** [comment]
{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1589958843482",
      "to": "1589980443482",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 908,
          "datasourceId": 3,
          "rawSql": "SELECT\n  id AS \"time\",\n  name AS metric,\n  used AS \"used\",\n  weight AS \"weight\",\n  cost AS \"cost\"\nFROM spools\nORDER BY 1,2",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 42,
          "sql": "SELECT\n  id AS \"time\",\n  name AS metric,\n  used AS \"used\",\n  weight AS \"weight\",\n  cost AS \"cost\"\nFROM spools\nORDER BY 1,2",
          "transformations": [
            "calculateField",
            "calculateField",
            "organize",
            "calculateField",
            "calculateField",
            "organize",
            "calculateField",
            "calculateField",
            "organize"
          ]
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "time"
              },
              {
                "text": "metric"
              },
              {
                "text": "used"
              },
              {
                "text": "weight"
              },
              {
                "text": "cost"
              }
            ],
            "rows": [
              [
                1,
                "Brown",
                979.83044,
                1120,
                22.99
              ],
              [
                2,
                "Misc Old Rolls",
                2215.332,
                10000,
                20
              ],
              [
                3,
                "Bright Green",
                483.5612,
                500,
                8.25
              ],
              [
                5,
                "Orange",
                482.8722,
                500,
                8.25
              ],
              [
                6,
                "Black",
                425.72894,
                500,
                8.25
              ],
              [
                7,
                "Yellow",
                441.67252,
                500,
                8.25
              ],
              [
                8,
                "Blue (B)",
                1002.4276,
                1120,
                17.99
              ],
              [
                9,
                "Green",
                306.2329,
                1000,
                27
              ],
              [
                10,
                "Transparent Green",
                409.49832,
                1000,
                20
              ],
              [
                11,
                "Silver",
                998.67175,
                1000,
                22.99
              ],
              [
                12,
                "Black",
                213.27068,
                1000,
                20
              ],
              [
                13,
                "Noble Blue",
                118.620445,
                750,
                40
              ],
              [
                14,
                "Transparent Yellow",
                369.2838,
                1000,
                20
              ],
              [
                15,
                "Blue (A)",
                1116.9877,
                1120,
                22.99
              ],
              [
                17,
                "Blue (C)",
                685.7846,
                1120,
                17.99
              ],
              [
                19,
                "Silver",
                794.6212,
                1120,
                22.99
              ],
              [
                20,
                "Gold",
                249.54552,
                500,
                18
              ],
              [
                21,
                "Mint",
                683.5721,
                1000,
                17.99
              ],
              [
                22,
                "Real Black",
                984.76135,
                1000,
                17.99
              ],
              [
                23,
                "Real Red",
                985.9817,
                1000,
                17.99
              ],
              [
                24,
                "Silver",
                1015.7412,
                1000,
                16
              ],
              [
                25,
                "Silver (B)",
                501.1173,
                1000,
                16
              ],
              [
                26,
                "Pink",
                234.43518,
                500,
                8.25
              ],
              [
                27,
                "White",
                964.6243,
                1000,
                25
              ],
              [
                28,
                "White",
                0,
                1000,
                25
              ],
              [
                29,
                "Yellow",
                720.86066,
                1120,
                22.99
              ],
              [
                30,
                "Orange",
                216.4044,
                1000,
                25
              ],
              [
                31,
                "Real Green",
                995.09033,
                1000,
                17.99
              ],
              [
                32,
                "Purple",
                999.2526,
                1000,
                25
              ],
              [
                33,
                "Real Red B",
                971.25653,
                1000,
                17.99
              ],
              [
                34,
                "Purple (B)",
                0,
                1000,
                25
              ],
              [
                36,
                "Yellow",
                69.428,
                1000,
                25
              ],
              [
                37,
                "Yellow",
                38.90024,
                1000,
                20
              ],
              [
                38,
                "Real Green B",
                611.1942,
                1000,
                17.99
              ],
              [
                39,
                "Transparent Yellow",
                0,
                1000,
                0
              ],
              [
                40,
                "Black",
                952.39294,
                1000,
                0
              ],
              [
                42,
                "White",
                475.6569,
                500,
                0
              ],
              [
                43,
                "Orange B",
                159.24777,
                1120,
                20
              ],
              [
                44,
                "Real Red C",
                369.8669,
                1000,
                17.99
              ],
              [
                45,
                "Brown B",
                960.69354,
                1120,
                24.99
              ],
              [
                46,
                "Cool White",
                366.179,
                1120,
                24.99
              ],
              [
                47,
                "Real Black B",
                348.24106,
                1000,
                17.99
              ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "rowCount": 42,
              "sql": "SELECT\n  id AS \"time\",\n  name AS metric,\n  used AS \"used\",\n  weight AS \"weight\",\n  cost AS \"cost\"\nFROM spools\nORDER BY 1,2",
              "transformations": [
                "calculateField",
                "calculateField",
                "organize",
                "calculateField",
                "calculateField",
                "organize",
                "calculateField",
                "calculateField",
                "organize"
              ]
            }
          }
        ],
        "dataframes": null
      }
    }
  }
}

From #24873

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/25421
