### ISSUE TITLE
Still unable to send emails  

### ISSUE THREAD

**Issue by thameezb** [grafana/grafana#24562]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Seems to be accidentally open when creating #24563.
