### ISSUE TITLE
Templating: TextBox variable not updated from url

### ISSUE THREAD

**Issue by ae3e** [grafana/grafana#24576]
**What happened**:
When I access a dashboard from url including a variable (`var-project=project3`), the default variable value is still used in the text field (_project1_ in the example).
Nevertheless, if I change the variable in the textbox the url is correctly updated.

![image](https://user-images.githubusercontent.com/12472719/81667906-32d92500-9444-11ea-9342-b9056f409598.png)

**What you expected to happen**:
Variables set in the url should update the dashboard accordingly

**Environment**:
- Grafana version: 7.0.0-beta3
- Data source type & version:  Random data
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 - Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Seems to work for query variables:
https://play.grafana.org/d/000000015/elasticsearch-templated?orgId=1&var-source=All&var-host=server%2020

could be a problem with the textbox variable

**Comment by hugohaggmark** [comment]
Thanks for reporting this @ae3e and a fix for this is coming in 7.0. (#24623)
