### ISSUE TITLE
Global Org Settings Page

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2457]
This is a bit old, but can we please implement the Global Org view. It's a bit restrictive to not be able to change Org Names when setting up a new user.

![screenshot 2015-08-06 10 43 23](https://cloud.githubusercontent.com/assets/2886187/9114655/005b7ee8-3c29-11e5-8755-2b519732fb27.png)

This page likely hasnt been spec'd out, but should work in a very similar manner to the Global Users. (List, Edit, Add)

**Comment by torkelo** [comment]
First pass at this, 
![image](https://cloud.githubusercontent.com/assets/10999/9198540/0f2a4bda-403d-11e5-845d-d7d9171de070.png)


![image](https://cloud.githubusercontent.com/assets/10999/9198550/1b598056-403d-11e5-89b6-2667d48d0ad3.png)

**Comment by mattttt** [comment]
So very excited to see this. The only thing I can see as an enhancement is the ability to add users from within the Org Details page (Where you can edit & delete them), but I dont see that as being a requirement for the moment. 

This helps with the management of orgs immensely.
