### ISSUE TITLE
Cloudwatch logs: Log groups are not updated when switching to another cloudwatch datasource

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#24570]
**What happened**:
I have configured two different cloudwatch datasources. If I switch from one to another I have to refresh the page for fetching the log groups of the newly selected cloudwatch datasource.

**What you expected to happen**:
After switching to the new datasource I wouldn't expect to see the log groups of the previously selected datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Register two datasources and in explore switch between them.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
7.0.0-beta3

- Data source type & version:
Cloudwatch

- OS Grafana is installed on:
Mac

- User OS & Browser:
Chrome

- Grafana plugins:
- Others:

**Comment by kaydelaney** [comment]
Seems to be fixed in master as I'm unable to reproduce. Could you please check again?

**Comment by aocenas** [comment]
This is probably a side effect of change that was reverted here https://github.com/grafana/grafana/pull/24444. More query fields were probably affected by that.

**Comment by aocenas** [comment]
This should be fixed on master already
