### ISSUE TITLE
Error running yarn dev command

### ISSUE THREAD

**Issue by iscollab** [grafana/grafana#24582]
**What happened**:
While trying to follow the tutorial do develop a data source plugin, after using the grafana toolkit cli, and running yarn install successfully, when I tried to run yarn dev to build the project I just created I get the following error: 
```
PS E:\Work\my-plugin> yarn dev
yarn run v1.22.4
$ grafana-toolkit plugin:dev
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined       
    at validateString (internal/validators.js:117:11)
    at Object.basename (path.js:671:5)
    at isLinkedMode (E:\Work\my-plugin\node_modules\@grafana\toolkit\bin\grafana-toolkit.js:13:12)     
    at entrypoint (E:\Work\my-plugin\node_modules\@grafana\toolkit\bin\grafana-toolkit.js:29:7)        
    at Object.<anonymous> (E:\Work\my-plugin\node_modules\@grafana\toolkit\bin\grafana-toolkit.js:51:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What you expected to happen**:
I expected that yarn dev created a dist folder that with the plugin successfully built.

**How to reproduce it (as minimally and precisely as possible)**:
On Windows command line or Powershell run:
```
npx "@grafana/toolkit"@next plugin:create my-plugin
```
Select datasource plugin as the plugin type
```
cd my-plugin
yarn install
yarn dev
```

**Anything else we need to know?**:
Running yarn dev in git bash successfully builds the project.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: N/A
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: 
- Others: node v12.16.3; yarn 1.22.4

**Comment by gordonjb** [comment]
I’ve also had this issue on this combination and manually changing
`if (path.basename(pwd) === 'grafana-toolkit') {`
to
`if (pwd && path.basename(pwd) === 'grafana-toolkit') {`
fixes the issue for me. I believe the pwd variable is not set on Powershell: https://github.com/nodejs/help/issues/1881

**Comment by smarkm** [comment]
> I’ve also had this issue on this combination and manually changing
> `if (path.basename(pwd) === 'grafana-toolkit') {`
> to
> `if (pwd && path.basename(pwd) === 'grafana-toolkit') {`
> in `node_modules\@grafana\toolkit\bin\grafana-toolkit.js` fixes the issue for me. I believe the pwd variable is not set on Powershell: [nodejs/help#1881](https://github.com/nodejs/help/issues/1881)

I got the same error, and resolve with a temporary solution to set the PWD on windows 10:
`set PWD={you-plugin-path}`
should be have a better solution

**Comment by gilkgit** [comment]
Happened to me on Windows,
it seems that process.env.PWD is always empty on my Win version.
process.cwd() does work, so I changed the relevant line in grafana-toolkit.js to:

const pwd = process.env.CIRCLE_WORKING_DIRECTORY || process.env.PWD || process.cwd();
