### ISSUE TITLE
Dashboard Legend Selection not  allowing to select one source in certain case.

### ISSUE THREAD

**Issue by nycmitch25** [grafana/grafana#24596]
**What happened**:
Identical queries in dashboard chart causes the option to select one in legend to not work. When I have two databases which are the same and use a Mixed query, unable to select only one of the two. As a test I changed the query on one from mean() to mode() and that resolved the issue. 

**What you expected to happen**:
When I click on the legend I should see the one dataset be displayed.
![image](https://user-images.githubusercontent.com/20663578/81745239-76e31e80-9472-11ea-9d1d-3c2982518b02.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two databases (in Influx) of different names
2. Create the same table name in both, populate
3. Create a dashboard item of "mixed" and display them both.
4. Click on legend and you will see that you can not click and show only one.

**Anything else we need to know?**:
_(I can have a test system made available to you if that helps)_

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
I was able to replicate the issue. In case of mixed datasource, we should probably add datasource to the series label.
![image](https://user-images.githubusercontent.com/30407135/81797188-bcedc000-950e-11ea-87ca-00c5dec7fbaa.png)

**Comment by torkelo** [comment]
If the series are identical you can add custom legend formatting to differentiate them

**Comment by torkelo** [comment]
and for the original issue just add an alias pattern that is different on each query
