### ISSUE TITLE
Grafana crashes after querying a cloudwatch log group

### ISSUE THREAD

**Issue by eroub** [grafana/grafana#24590]
**What happened**:
Querying a log group (from a cloudwatch datasource) crashed grafana and it exited with `code 2`

**What you expected to happen**:
Successful Query

**How to reproduce it (as minimally and precisely as possible)**:
Connect to a cloudwatch datasource. Make a dashboard and try to query a log group.

**Anything else we need to know?**:
Here is the crash log:
````
grafana_1  | t=2020-05-12T17:28:18+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
grafana_1  | panic: interface conversion: *xerrors.wrapError is not awserr.Error: missing method Code
grafana_1  | 
grafana_1  | goroutine 311 [running]:
grafana_1  | github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).handleStopQuery(0xc000c3d900, 0x1f54100, 0xc000c3d940, 0x1f884e0, 0xc0000114a0, 0xc0005e7d10, 0x2f83ce1, 0x1, 0x0)
grafana_1  | 	/root/project/pkg/tsdb/cloudwatch/log_actions.go:246 +0xbd
grafana_1  | github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeLogAction(0xc000c3d900, 0x1f54100, 0xc000c3d940, 0xc000c3d800, 0xc000c3d840, 0x0, 0x0, 0x0)
grafana_1  | 	/root/project/pkg/tsdb/cloudwatch/log_actions.go:80 +0x2c1
grafana_1  | github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeLogActions.func1(0x0, 0x0)
grafana_1  | 	/root/project/pkg/tsdb/cloudwatch/log_actions.go:27 +0x60
grafana_1  | golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000c42000, 0xc000c3d980)
grafana_1  | 	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
grafana_1  | created by golang.org/x/sync/errgroup.(*Group).Go
grafana_1  | 	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
grafana_grafana_1 exited with code 2
````

**Environment**:
- Grafana version: v7.0.0-beta3
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Docker 19.03.6
- User OS & Browser: Ubuntu 18.04, Firefox 76.0
- Grafana plugins: n/a
- Others: n/a

**Comment by kaydelaney** [comment]
Can't reproduce the issue. Has `go mod vendor` been run to pull the latest go dependencies before deploying?

**Comment by marefr** [comment]
@kaydelaney looking in 7.0.x branch this line conversion fails: https://github.com/grafana/grafana/blob/2169fc1a3f3fea0cb81e2ae03f9a0f7108dc6e33/pkg/tsdb/cloudwatch/log_actions.go#L246

Looking in master I see 7 places in https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/log_actions.go that does a typecast to `awserr.Error` without checking if the cast is possibly - something we should try and fix.

**Comment by aknuds1** [comment]
I can work on this.

**Comment by aknuds1** [comment]
@eroub I tried v7.0.0-beta3, and couldn't reproduce. I made a CloudWatch data source, a dashboard with a logs panel querying the data source through a single Logs mode query, and it doesn't crash. I can see how errors from AWS could trigger the bug you're seeing though.

**Comment by aknuds1** [comment]
Although I couldn't reproduce, I've made a PR, #24641, that should fix the issue you're experiencing. Thanks for reporting it!
