### ISSUE TITLE
Add user authorization roles to different dashboards (e.g., admin, client, etc )

### ISSUE THREAD

**Issue by samuraraujo** [grafana/grafana#246]
Would be great if we could save the dashboard disabling editing for specific users .

It would require to develop or integrate an authorization system into grafana. 

Is there anybody working on it?

**Comment by jaimegago** [comment]
@jippi care to explain how you would do per dashboard per user *authorization* (not authentication) on the web server or via a php wrapper with no Grafana back end?

**Comment by torkelo** [comment]
closing this as we are introducing a basic permission model in v5
