### ISSUE TITLE
CloudWatch Logs: Can't use variables in query

### ISSUE THREAD

**Issue by niklaskhf** [grafana/grafana#24603]
**What happened**:
Used following three queries: 
`fields @timestamp, detail.containers.0.name as name | filter name = "$service" | sort @timestamp desc` 
`fields @timestamp, detail.containers.0.name as name | filter name = "{{service}}" | sort @timestamp desc` 
`fields @timestamp, detail.containers.0.name as name | filter name = "example" | sort @timestamp desc` 

with variable service = example 

Only the third query, without variable, returns the intended result. 

Variables in log group name don't get rendered either. Grafana throws regex pattern doesn't match error. 
**What you expected to happen**:
At least two of the queries to return correct results.

**How to reproduce it (as minimally and precisely as possible)**:
Set variable `time` to a set timestamp that exists in the CloudWatch Log group. 
`fields @timestamp | filter timestamp = "$time"`

**Anything else we need to know?**:
Is this a bug, or am I using the wrong syntax for variables in the query? 

**Environment**:
- Grafana version: 7.0.0-beta3
- Data source type & version: CloudWatch
- OS Grafana is installed on: Arch Linux
- User OS & Browser: MacOS / Safari
- Grafana plugins: None
- Others: None

**Comment by TryTryAgain** [comment]
@urbaniak does it work if you change your filter line from:

`| filter kubernetes.pod_name = "$pod"`

to:

`| filter kubernetes.pod_name =~ /$pod/`

**Comment by TryTryAgain** [comment]
Same. For us, it was working...must have stopped when we upgraded, experiencing the same issue now.

**Comment by visit1985** [comment]
#40429 probably related

**Comment by mrliptontea** [comment]
Just found that upgrading to 8.2 broke my CloudWatch Logs dashboard. It works in 8.1.7.
However, `$log_group` is still not interpolated when you go to Explore.

**Comment by aocenas** [comment]
Issue with variable interpolation was an regression that was fixed here https://github.com/grafana/grafana/pull/40899 but was released just recently in 8.2.4 release. So please if anybody still had issues, try updating to that release.

**Comment by visit1985** [comment]
@aocenas Can you update the `appVersion` in the corresponding [helm chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/Chart.yaml)? Thanks!

**Comment by evgenirusev** [comment]
Unfortunatelly I'm stuck with using 8.2.2 due to using a managed version of Grafana. Are there any workarounds to make variables work?

This is not working for me:
`| filter kubernetes.pod_name =~ /$pod/`

**Comment by jinleileiking** [comment]
still on 8.4.4

**Comment by pablolibo** [comment]
I have the same problem with 9.4.13 :(

**Comment by jeduden** [comment]
same issue with Grafana v9.4.7 :(

**Comment by XI3423-aarora** [comment]
This is not working for me:
| filter kubernetes.pod_name =~ /$pod/

Someone have any other solution to filter log insight using dashboard variable.
