### ISSUE TITLE
Transform, Binary operation - Doesn't work

### ISSUE THREAD

**Issue by ilevac** [grafana/grafana#24601]
I tried the new Transformation feature.
Under Add field from calculation, reduce row is working fine, but binary operation doesn't work.
When I add a binary operation, it doesn't add or replace any row.

**Environment**:
- Grafana version: 7.0.0B3
- Data source type & version: influxdb 1.8.0
- OS Grafana is installed on: docker swarm (engine version 19.03.8)
- User OS & Browser: Chrome 81.0.4044.138 and Firefox 76.0.1 on Windows 10 64Bit
- Grafana plugins: grafana-worldmap-panel, yesoreyeram-boomtable-panel, andig-darksky-datasource, grafana-clock-panel, grafana-piechart-panel, percona-percona-app, camptocamp-prometheus-alertmanager-datasource

**Comment by ryantxu** [comment]
Can you post the panel json here?

**Comment by ilevac** [comment]
Here's an example.
I discovered that if I used a serie from reduce row for the binary operation that work.
When the serie used is from a "normal" query that didn't work.

>{
  "datasource": "Telegraf - Standalone",
  "cacheTimeout": null,
  "gridPos": {
    "h": 4,
    "w": 2,
    "x": 12,
    "y": 7
  },
  "hideTimeOverride": true,
  "id": 23763571993,
  "links": [],
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "mean"
      ]
    },
    "orientation": "horizontal",
    "showThresholdLabels": false,
    "showThresholdMarkers": true
  },
  "pluginVersion": "7.0.0-beta3",
  "targets": [
    {
      "alias": "Total",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "apc_pdu2",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Total"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          },
          {
            "params": [
              " * 22"
            ],
            "type": "math"
          }
        ]
      ],
      "tags": []
    }
  ],
  "timeFrom": "20s",
  "timeShift": null,
  "title": "APC - PDU - 2 - Live",
  "type": "gauge",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "watt",
      "min": 0,
      "max": 5200,
      "decimals": 3,
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 4900
          },
          {
            "color": "red",
            "value": 5000
          }
        ]
      },
      "mappings": [
        {
          "$$hashKey": "object:8687",
          "id": 0,
          "op": "=",
          "text": "N/A",
          "type": 1,
          "value": "null"
        }
      ],
      "nullValueMode": "connected"
    },
    "overrides": []
  },
  "transformations": [
    {
      "id": "calculateField",
      "options": {
        "mode": "binary",
        "reduce": {
          "reducer": "sum"
        },
        "binary": {
          "left": "Total",
          "operator": "*",
          "right": "0.09",
          "reducer": "sum"
        },
        "alias": "$ / h (avg)"
      }
    }
  ]
}

**Comment by torkelo** [comment]
could replicate here: https://play.grafana.org/d/000000002/influxdb-templated?tab=transform&editPanel=1&orgId=1
