### ISSUE TITLE
CSV exporter shows "Value" for all columns

### ISSUE THREAD

**Issue by vschettino** [grafana/grafana#24600]
**What happened**:
When exporting csv for multiple values transforming with "join by time" I can see the desired table:
![Captura de tela de 2020-05-12 20-12-15](https://user-images.githubusercontent.com/7289698/81754625-08f82080-948d-11ea-9c7e-40b06abacae4.png)
But when I export the CSV, all column names come as "Value":
```csv
Time,Value,Value,Value,Value
1589324745157.7249,0.6862745098039216,0.6666666666666666,0.6095057458440254,0.5
```

**What you expected to happen**:
The same column names displayed in preview should be exported as the first line in the CSV

**How to reproduce it (as minimally and precisely as possible)**:
- PostgreSQL datasource
- Timeseries
- Graph visualization
- X-axis as `series` and value `total`
- The (modified) query:
```sql
 SELECT
  now() as time,
  c.display_name as metric
  count(id)
FROM reviews r
INNER JOIN company c ON c.id = r.id
WHERE is_active and i.status='published'
GROUP BY 1,2
HAVING count(r.id) > 50
ORDER BY 3 DESC
```

**Anything else we need to know?**:

**Environment**: 
- Grafana version: Grafana v7.1.0-534e211cpre (5feef22034)
- Data source type & version: PostgreSQL latest
- OS Grafana is installed on: Docker
- User OS & Browser: Debian & Firefox
- Grafana plugins: None, fresh install
- Others:

**Comment by torkelo** [comment]
Thanks for reporting this!

This line needs to use getFieldDisplayName function 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/utils/csv.ts#L292

**Comment by vschettino** [comment]
Glad to help!

Tell me if you need anything else :)
