### ISSUE TITLE
The grafana dashboard of different organizations can be synchronized by configuration

### ISSUE THREAD

**Issue by xuanyuanaosheng** [grafana/grafana#24602]
We want to sync the dashboard in different org.

Example:

The dashboard named “linux node status” in Org A (for develop) can be synchronized to dashboard "Node Info"  in Org B (for the boss).

**Comment by torkelo** [comment]
You will have to use the api to sync that. 

Not sure we will build that into grafana, but better done in an external sync tool

**Comment by xuanyuanaosheng** [comment]
@torkelo  Ok
