### ISSUE TITLE
LDAP - Authentication failure if email field returned from ldap/ad empty :- [AD to Grafana 2.1 ]

### ISSUE THREAD

**Issue by shankarramshivram** [grafana/grafana#2461]
I was trying to connect to our AD server for ldap authentication in grafana

The issue i am seeing is  after getting the information from ad server  grafana throws the following error :- 

- Error while trying to authenticate user : Error 1062: Duplicate entry ' ' for key 'UQE_user_email'

Digging deeper i see that  the email field in the information returned from the ldap server is " " (empty).
Is it possible to make the check for email optional or any other workaround for this ?

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by queox** [comment]
Hi,

I'm experiencing a similar issue with ldap authentication on grafana-4.4.3-1.x86_64 on CentOS 7 (installed via grafana repo):
"Error while trying to authenticate user" error="Error 1062: Duplicate entry '' for key 'UQE_user_login'"
Is this issue solved already?

Thanks very much for you help, best regards
Kurt

**Comment by steven-cherry** [comment]
+1
