### ISSUE TITLE
SingleStat Time "FROM NOW"-threshold uses EPOCH-Timestamp instead of duration.

### ISSUE THREAD

**Issue by nkrs44** [grafana/grafana#24618]
**What happened**:
I wanted to display the time since last execution of something, adding a threshold if the duration is over 1d for orange, 3d for red.

**What you expected to happen**:
I could add a time in seconds/ms/ns, at which it should change the color.
I expected the threshhold would be a duration from now, not a fixed date on the unit "FROM NOW".
I expected the units "FROM NOW" would use different units in threshholds then the other two date formats in "Date & Time".

**How to reproduce it (as minimally and precisely as possible)**:
Create a singlestat panel, query anything which yields a result.
Select unit "Date & Time"  -> "From Now" 
For testing i recommend one of the other two timestamp types within the same category. (same result)

By selecting a threshold you will get:
- exact same epoch timestamp in ms: orange, above
- above, -1: green.

**Anything else we need to know?**:
Related to Feature-Request #6710.
bug in pull request #9107.

**Environment**:
- Grafana version: Grafana v6.7.3 (a04ef6cefc)
- Data source type & version: Influxdb, v1.8
- OS Grafana is installed on: CentOs
- User OS & Browser: Windows, Firefox
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment]
Not sure we can support this, maybe there can be new transformation that does a diff on time from now

**Comment by torkelo** [comment]
Closing this as we wont modify the singlestat panel (it's deprecated, replaced by stat panel in 7.0)

**Comment by maemigh** [comment]
@torkelo is this still unsupportable even with the current stat panel?
