### ISSUE TITLE
Bundled plugins are not built

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#24617]
I built Grafana using `make`. However had to build plugins-bundled/internal/input-datasource manually as `make` did not compile it.

**Environment**:
- Grafana version: 03940c847131a58c5ee8cfe67cc958f9401b4cb5

**Comment by torkelo** [comment]
can you add "yarn run plugins:build-bundled"  to the Makefile?`

**Comment by simPod** [comment]
yes

**Comment by safa-topal** [comment]
My build hangs at this particular step. Any idea why?
