### ISSUE TITLE
Graphite edit mode doesn't handle forward slash in metric name

### ISSUE THREAD

**Issue by jonasbleyl** [grafana/grafana#24620]
**What happened**:
Create query to graphite datasource containing "/" and switch query to Edit mode. Switch query editor back to normal mode and you've lost part of the query.

**What you expected to happen**:
Query should only be split on "." and treat "/" as normal character.

**How to reproduce it (as minimally and precisely as possible)**:
In Edit mode:
![grafana-issue-1](https://user-images.githubusercontent.com/12758226/81804602-443c3300-9511-11ea-8484-35e9c6a62ff7.png)

Switch back to Normal mode:
![grafana-issue-2](https://user-images.githubusercontent.com/12758226/81804605-4605f680-9511-11ea-9704-97accc1e5293.png)

**Anything else we need to know?**:
Tested in Grafana 6 and 7.

**Comment by torkelo** [comment]
A  forward slash is not an allowed metric path name in Graphite as far as I know

**Comment by jonasbleyl** [comment]
Hmm, I can't find any resource which tells you which characters are valid/invalid for the Graphite metric name.

We are currently using graphite-web/carbonapi and they handle metrics with / in them correctly as well.

**Comment by ivanahuckova** [comment]
Hello @jonasbleyl! I couldn't find any official resource which tells you which characters are valid/invalid for the Graphite as well, but I have found couple of resources that mention that using / is not recommended and some of them explain why. For example:
https://grafana.com/blog/2016/03/03/25-graphite-grafana-and-statsd-gotchas/#input
https://mingbowan.blogspot.com/2012/08/enable-special-character-support-in.html
https://github.com/graphite-project/carbon/issues/331
https://github.com/graphite-project/carbon/issues/417

I'm sorry I couldn't find an authoritative resource. I think your best bet would be to replace / in your metrics by some other character.

**Comment by jonasbleyl** [comment]
Hi @ivanahuckova. Thanks for looking into this. It seems that Graphite's backend doesn't support special characters very well so it makes little sense to handle these cases via Grafana. Thanks.
