### ISSUE TITLE
$__timeGroup shows time incorrectly

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#24627]
**What happened**:
When I group my data using the function "$__timeGroup", it shows the time incorrectly.
Instead of showing the data as date "00:00" it shows it as date 03:00.
![image](https://user-images.githubusercontent.com/1325158/81811048-b1a98d00-952c-11ea-8544-8995d685b46b.png)

**What you expected to happen**:
I expected it to show the data as browser time 00:00. The data is NOT UTC time as stored in teh DB, but rather the actual time.

**How to reproduce it (as minimally and precisely as possible)**:
The only way to fix it was to have the dashboard use UTC time, instead of local browser time. Changing to Local Browser time or Default on the timezone didn't help.
This happens every time I query a table from sql and receive a datetime value, that it is always 3 hours ahead.

**Anything else we need to know?**:
Not that I know of

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: SQL Server
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome 81
- Grafana plugins: Graph
- Others:

**Comment by torkelo** [comment]
Not sure this is a Grafana problem but how the SQL queries work, there is no rounding ut to even day buckets, it all depends on your time range and intervals

**Comment by reuvygroovy** [comment]
Again, this occurs with InfluxDB data as well. Not only SQL.

**Comment by torkelo** [comment]
well make sure the time range is on full days if you want the group by buckets to happen on full days

**Comment by reuvygroovy** [comment]
It is. This happens for example when I show 2 days

![image](https://user-images.githubusercontent.com/1325158/82997281-d7e02a00-a00e-11ea-914a-f5c60dcf40d2.png)
![image](https://user-images.githubusercontent.com/1325158/82997770-7f5d5c80-a00f-11ea-9d12-c464a6a28651.png)

**Comment by reuvygroovy** [comment]
And here you can see on 7 days:
![image](https://user-images.githubusercontent.com/1325158/82997839-94d28680-a00f-11ea-8c22-c0cb92ec065a.png)

**Comment by farolfo** [comment]
+1 
I experience the same issue as @reuvygroovy
