### ISSUE TITLE
Data Outside Time Range

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#24625]
![DataOutsideTimeRange](https://user-images.githubusercontent.com/1325158/81805393-70f94600-9523-11ea-857f-5a23785bb73d.png)

**What happened**:
We got an error message for one data source "Data Outside Time Range"

**What you expected to happen**:
We expected no data to be shown, including no error

**How to reproduce it (as minimally and precisely as possible)**:
We are running a SQL Query against a SQL Server data source.
I think there is an issue here. This is our query:
_SELECT
$__timeGroup(start_time,$__interval) [time],
   SUM(duration)   [value], 
 user [metric]
FROM DB
WHERE $__timeFilter(start_time)
GROUP BY $__timeGroup(start_time,$__interval), user_

Now, we had to use a **manual** interval time frame of 1d, since we want the data to be grouped by days, so that for example if we select in the timepicker 7 days ago, we will see 7 bars/days only. If we allow the interval to be auto generated, the group by will show us as per hour and such.

When I select a timeframe of 2 days ago, then for one data source i see the above error message. Why? When I showed the epoch time generated for the data using the above query, the date/time is today's date followed by a time of 00:00, but if I open the graph at 8AM, the x axis will not sure two days ago 00:00 but only two days ago 08:00, so the data is out of the displayed range

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: SQL Server
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome
- Grafana plugins: Graph
- Others:

**Comment by reuvygroovy** [comment]
You can see another example here of how this is exhibited:
![MeetingsPerDay](https://user-images.githubusercontent.com/1325158/81817306-37c9d180-9535-11ea-99be-caeb679e753c.png)
See how the value for 5/11 00:00 with a value of 3 appears together in the same lump as 5/12

**Comment by torkelo** [comment]
Not sure this is a grafana problem but how the SQL query works in relation to the time range? if you want the time range to align with perfect days you need to use time ranges like 

<img width="360" alt="Screen Shot 2020-05-27 at 09 55 30" src="https://user-images.githubusercontent.com/10999/82993002-3d78ea00-a000-11ea-8265-6c3b359fb523.png">

If you use those `/d` the from & to will round backword or forward so you get complete days

**Comment by reuvygroovy** [comment]
That didn't help

You can see how even with the /d added I still have the bar spanned over more than 1 day
![image](https://user-images.githubusercontent.com/1325158/82993456-3f937680-a009-11ea-89e0-b2379549424e.png)

I was able to repro with an Influx data source as well. So I don't think this is SQL related per se.
