### ISSUE TITLE
[2.1.0] Browser very slow using templates with lots of $variable results

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#2462]
Backend is InfluxDB 0.9.3

I'm loving 2.1.x; it brings a ton of great features. One problem, however, is that templated dashboards, which have a lot of results in a defined variable, cause my browser (Chrome) to slow to a crawl. Viewing the JSON, I suspect the reason why -- the number of resulting text/value entries in the variable is over 25,000.

Here's an example query to populate the $variable in the templated dashboard:
```
show tag values from servers with key=server_name
Refresh on load: False
type: query
```

Any suggestions to resolve this?

**Comment by torkelo** [comment]
You should try to limit the amount of values to around max count of 1000-5000 that is the limit where I have tested. The list limits the rendering to I think around 500 items at the same time, but you can search for the full list of values. 

Is it possible for you to add another variable (tag values) that can limit the next tag (the one you currently get 25 000 entries for). For example you do you have a region tag or something else that you can use to slice the servers list?

**Comment by ecables** [comment]
Unfortunately the goal of this dashboard is holistic, so I can't regionalize the data. I suppose an entry form for a variable that is purely for text entry, and doesn't try to pre-populate the data, would be one solution. Is that possible?

**Comment by torkelo** [comment]
Yes,  just use a variable of type custom

**Comment by ecables** [comment]
Great, that's better for this particular use case.
