### ISSUE TITLE
"Find more plugins on Grafana.com" should open in new tab

### ISSUE THREAD

**Issue by yurividal** [grafana/grafana#24622]
**What would you like to be added**:
"Find more plugins on Grafana.com" button in "Plugins" section should open in a new tab, since it goes to a separate domain, outside of the user's domain.

**Why is this needed**:
It can get quite confusing when you click a button and you are taken outside of the site you are in, and taken into a totally different site, in a different domain (grafana internet site).

**Comment by torkelo** [comment]
thanks for reporting this, opened PR https://github.com/grafana/grafana/pull/24635

**Comment by yurividal** [comment]
Has this been rejected? Its still not present in 7.1-beta3

**Comment by zoltanbedi** [comment]
Ohh, so the fix is released but it did not actually fix the problem. Let me fix that real quick.
