### ISSUE TITLE
Query History – testing results

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#24630]
Following are issues I found during Query History testing. @jessover9000 @aocenas @ivanahuckova 👇 

- [x] 1. **important**  When switching between different datasource I would expect the list with queries in the Query History drawer to be scrolled to the relevant queries (queries from this datasource). [check animation1 below]
> 👆 Switched default setting to active data source queries

- [ ] 2. **important**  When switching between datsources the list of queries in the drawer seems to be jumping due to change of queries box height (caused by change from "run query" button to "switch datasource and run query" button). Beacuse my gaze is focused on datasource dropdown it took me a while to understand what's going on and I felt something is changing in a way I couldn't understand. My initital thought was that list of queries changed.  [check animation1 below]
It would be good to find a solution which keeps the height the same.
> 👆 Added to design doc, we will be unifying styles and this issue will be fixed then

[animation1]
![datasource_query](https://user-images.githubusercontent.com/15225624/81812254-2f1dcf00-9526-11ea-8407-853b0fb7a775.gif)

- [x] 3. **important** When adding a comment I expected ENTER to submit, that didn't happen [pic1] I understand the logic but it would be good to allow for saving from the keyboard as well, maybe by using SHIFT+ENTER, same would be for CANCEL (ESC). We have a lot of users who navigate via keyboard.
[pic1]
![image](https://user-images.githubusercontent.com/15225624/81813886-4d84ca00-9528-11ea-9829-df2e97ac4fd1.png)

- [x] 4. Given that a query is permanently deleted from the list shouldn't we ask for confirmation?
> 👆 Added confirmation for deleting of starred queries

- [x] 5. **bug** When clicking on a Run Query button the focus is on a completelty different button. [check animation2]
> 👆 This is due to adding a new query to history and . So it was more like an illusion. We are deduplicating logs, so this shouldn't happen. 

- [ ] 6. **important** After clicking on Run Query button I get no visual confirmation that the query was actually run and I keep wondering whether anything happened. [check animation2] It would be good to maybe change Run Query to Current Query afetr you run it. Or anything really that provides clear infromation that query was run.
> 👆 Added to design doc as next task/improvements

[animation2]
![focus](https://user-images.githubusercontent.com/15225624/81814449-16fb7f00-9529-11ea-9746-005b7bc4c3c1.gif)

- [x] 7. **nip tick** Shortening "Filter history between" to "Filter history" can save some space

- [ ] 8. The distinction between querie's description and the actual query is so minimal it's really hard to quickly scan the list of queries. From the user perspective I look for a particular query first and only then (if) I am interested in descirption. We should improve this to make scanning easier, it doesn't have to be a massive change (more gray description can do the trick).
>> 👆 Added to design doc as next task/improvements

![image](https://user-images.githubusercontent.com/15225624/81815395-3515af00-952a-11ea-9a36-4ab1dc6d640d.png)

- [ ] 9. I am not sure it's obvious that these are 2 queries. It would be good to either test with users or create some indication that these are 2 queries.
![image](https://user-images.githubusercontent.com/15225624/81816132-31365c80-952b-11ea-989f-c550bf4fb860.png)
> 👆 Added to design doc as next task/improvements

- [ ] 10. **important** look at the `query count` next to the date in  the drawer `May 13 –– 35 queries`. I am running queries from the History and they are being added to the history as I run them. @aocenas mentioned that 

> seems like it checks only if you run the last query but not if you run query identical to the last one

![Kapture 2020-05-13 at 16 16 37](https://user-images.githubusercontent.com/15225624/81824336-a9a21b00-9535-11ea-928d-40c5e5b24dee.gif)

- [ ] (added by Ivana) 11. I have a lot of queries in my history (600+) and when switching to "all queries tab", I have to wait 5+ seconds. This is really painful. 
> 👆 Added to design doc as next task/improvements

**Comment by ivanahuckova** [comment]
Thanks @sarlinska for super thorough check and feedback❤️! 

I have divided your feedback into following categories:

**Needs discussion with UX team**

>1. important When switching between different datasource I would expect the list with queries in the Query History drawer to be scrolled to the relevant queries (queries from this datasource). 

In Query history settings, you can set up showing of queries of data source that is currently active in Explore. We discussed with @jessover9000 , what should be the default behaviour and we decided to show all queries, but based on the feedback, maybe we could re-visit this again.

>4. Given that a query is permanently deleted from the list shouldn't we ask for confirmation?

@jessover9000 what are your thoughts on this? I am not sure. It is "only a query", so I am not sure if we need confirmation. Can be annoying if you are deleting more queries. But on the other side, if everywhere else in Grafana we ask about this, we should probably be consistent. Maybe we can add "do not ask me again" checkbox in modal.

>6. important After clicking on Run Query button I get no visual confirmation that the query was actually run.

>8. The distinction between querie's description and the actual query is so minimal it's really hard to quickly scan the list of queries.

>9. I am not sure it's obvious that these are 2 queries. It would be good to either test with users or create some indication that these are 2 queries.

> 10. I am running queries from the History and they are being added to the history as I run them. 

Should we not add queries that are run from query history to history? 

**Needs discussion with Observability team and UX team**
> 5. bug When clicking on a Run Query button the focus is on a completelty different button. 

Visual bug.Based on our conversation in this [long thread](https://raintank-corp.slack.com/archives/CPXKS6FB5/p1589375325409700?thread_ts=1589370821.406600&cid=CPXKS6FB5), we should consider:
- add some visualisation when new query is added, so it is clear that everything moved down
- remove running of partial queries in Explore

**Should be fixed right away**

>2. important When switching between datsources the list of queries in the drawer seems to be jumping due to change of queries box height 

>3. Keyboard shortcuts support

> 7. nip tick Shortening "Filter history between" to "Filter history" can save some space

Yes, I totally agree. This should be an easy fix, will look into it asap.

**Comment by sarlinska** [comment]
Always! ;) Some quick comments.

Reg 1. We should always strive to be context sensitive – if I am switching a datasource then probably the queries I am interested in are the ones for the datasource. I would ask developers for feedback to make sure.

Reg 4. I'd ask users.

Reg 10. Well, if that means duplicating the exactly same query then I'd say no. If we run query from a week, then I would move this query to Today but that's it. Otherwise it will be messy with lot's of duplication, it will be hard to find anything.

**Comment by ivanahuckova** [comment]
We have either:
- fixed the above mentioned issues
- added them to design doc as a next tasks/improvements
- started to work on improvements

As all of them are considered and (in some way) being worked on, I am closing this issue so we don't have duplicated tracking of these issues.
