### ISSUE TITLE
JS errors when clicking delete, edit, share etc

### ISSUE THREAD

**Issue by cooper-22** [grafana/grafana#2463]
When I click anything on the pop up menu that you get when clicking the panel name I get various errors:

Clicking x (delete):
```
TypeError: e.modal is not a function
    at app.a176c834.js:18
    at i (app.a176c834.js:12)
    at app.a176c834.js:12
    at n.$eval (app.a176c834.js:12)
    at n.$digest (app.a176c834.js:12)
    at n.$apply (app.a176c834.js:12)
    at HTMLAnchorElement.<anonymous> (app.a176c834.js:14)
    at HTMLAnchorElement._.event.dispatch (app.a176c834.js:7)
    at HTMLAnchorElement.q.handle (app.a176c834.js:6)
```

Clicking edit:
```
Uncaught TypeError: b.children(...).tab is not a function(anonymous function) @ app.a176c834.js:18
```

Clicking share:
```
TypeError: e.modal is not a function
    at app.a176c834.js:18
    at i (app.a176c834.js:12)
    at app.a176c834.js:12
    at n.$eval (app.a176c834.js:12)
    at n.$digest (app.a176c834.js:12)
    at n.$apply (app.a176c834.js:12)
    at HTMLAnchorElement.<anonymous> (app.a176c834.js:14)
    at HTMLAnchorElement._.event.dispatch (app.a176c834.js:7)
    at HTMLAnchorElement.q.handle (app.a176c834.js:6)

```

I have updated to the latest build as of  yesterday:
Grafana version: 2.1.1-pre1, commit: v2.1.0+10-g41e13fa, build date: 2015-08-05 17:42:03

As far as I'm aware I have not changed anything myself, only used the front end.

Do you think a clean reinstall would do the job? If so how would I go about that?

Thank you.

-------

While I am here, is there somewhere where I can ask general questions about Grafana?
I would like to add a custom panel that has access to data and current timespan. An html panel is close but I don't know how to get access to the data and time information so that it may be used in the JS I embed in the html panel.

**Comment by torkelo** [comment]
very strange, and if you use the 2.1.0 release do you get the same problem? Have not had any issue like this reported

**Comment by cooper-22** [comment]
I've just removed 2.1.1-pre1 and installed 2.1.0 and I am having the same problem unfortunately.
I tried the same thing from an existing and a new dashboard.

Is it worth purging my config files with dpkg?
I'm not sure what else persists after a remove, is there anything I should manually delete to ensure a fresh install?

Thanks

**Comment by torkelo** [comment]
What browser and OS? any browser extensions that can cause this? Any other console errors when you refresh grafana or load a dashboard?

**Comment by cooper-22** [comment]
I've found out what is causing it, it's not a bug with grafana.
Sorry, hope I didn't waste too much of your time.

I added some JS to a text/HTML panel to create a Google maps panel.
It  looks like it's fine until I load that dashboard. I'll try and find another way to get a map onto the dashboard. Would really like that as a feature (to get time stamped location data onto a map).

Windows 7, Chrome, no extensions.

If you were curios the map code is below:
```
<div id="map_canvas" style="height: 354px; width:713px;"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&callback=initialize"></script>
<script>
var directionsDisplay,
    directionsService,
    map;

function initialize() {
  var directionsService = new google.maps.DirectionsService();
  directionsDisplay = new google.maps.DirectionsRenderer();
  var chicago = new google.maps.LatLng(41.850033, -87.6500523);
  var mapOptions = { zoom:7, mapTypeId: google.maps.MapTypeId.ROADMAP, center: chicago }
  map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
  directionsDisplay.setMap(map);
}


```

**Comment by cooper-22** [comment]
It was only one of the lines causing the problem:
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

Jquery must already be included in grafana, my bad!
