### ISSUE TITLE
Cloudwatch: flow-logs demo query produces error

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#24637]
Cloudwatch datasource in Explore:

Click on VPC Flow Logs
Average, min, and max byte transfers by source and destination IP addresses
`stats avg(bytes), min(bytes), max(bytes) by srcAddr, dstAddr`
produces error:

```
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

**Comment by aocenas** [comment]
This is actually duplicate of https://github.com/grafana/grafana/issues/24639
