### ISSUE TITLE
7.0.0-beta 3: Table panel "un-sorts" when refreshed

### ISSUE THREAD

**Issue by softwaremike** [grafana/grafana#24645]
**What happened**:
Added a table panel to my dashboard.  Selected a column to sort on.  The ^ shows up correctly, and the table is sorted by that field, as I expect.  I set the dashboard auto-refresh to 5 seconds.  When the dashboard refreshes, the sorting is lost - it now sorts however it sorted when initially adding the panel.  Every time the dashboard refreshes, the sort is lost.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0-beta3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
related to this https://github.com/grafana/grafana/issues/24522
