### ISSUE TITLE
Conditional variable population

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#24642]
**What would you like to be added**:

I've noticed that a non negligible time of dashboard loading comes from the population of variables. The larger the time range the more it becomes obvious.

I've a dashboards that use a lot of variables which are not that often used but really useful when debugging specific things.

Here an examples of variables:
```
- $k8senv:       label_values(prometheus_build_info, env)
- $k8scluster:   label_values(prometheus_build_info{env=~"$k8senv"}, k8s_cluster)
- $k8snode:      label_values(node_uname_info{env=~"$k8senv",k8s_cluster=~"$k8scluster",component="node-exporter"}, nodename)
- $k8snamespace: label_values(kube_namespace_created{env=~"$k8senv",k8s_cluster=~"$k8scluster"}, namespace)
- $k8simage:     label_values(kube_pod_container_info{env=~"$k8senv",k8s_cluster=~"$k8scluster",namespace=~"$k8snamespace"}, image)
- $k8spod:       label_values(kube_pod_container_info{env=~"$k8senv",k8s_cluster=~"$k8scluster",namespace=~"$k8snamespace"}, pod)
- $k8scontainer: label_values(kube_pod_container_info{env=~"$k8senv",k8s_cluster=~"$k8scluster",namespace=~"$k8snamespace",pod=~"$k8spod.*"}, container)`
```

Most of the time drilling down by selecting `$k8snamespace` is enough making the population of following variables a waste of time.

That's why I think it would be very useful if we could condition the population of variables if a defined subset of other variables have values which are not `All`.

In the previous case I would like:
- `$k8simage` to be populated if `$k8snamespace` has a value which is not `All`
- `$k8spod` to be populated if `$k8snamespace` has a value which is not `All`
- `$k8scontainer` to be populated if `$k8spod` has a value which is not `All`

If the condition is not met the variable would be set to `All` (or the All custom value of the variable). 

**Why is this needed**:

- Faster dashboard loading.
- Less queries to the datasources.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
