### ISSUE TITLE
Add support for OpenID Connect RP-Initiated Logout in generic oauth

### ISSUE THREAD

**Issue by heggenu** [grafana/grafana#24643]
**Background.**

I am using a ForgeRock IDP (OpenID Connect) with Grafana. For the signout_redirect_url in Grafana I added the end_session_endpoint of my OpenID Connect IDP.

When trying to logout from Grafana I recieve the message that the id_token_hint is missing in the request to the IDP.

According to the OpenID specs, the id_token_hint is recommended, but my IDP implements this as a mandatory parameter.

https://openid.net/specs/openid-connect-session-1_0.html#RPLogout  
https://backstage.forgerock.com/docs/am/6.5/oidc1-guide/#rest-api-oidc-endsession-endpoint

**What would you like to be added**:

Add support for OpenID Connect id_token_hint when using signout_redirect_url in generic oauth.

**Why is this needed**:

To make the logout function in Grafana work with a OpenID Connect IDP.

**Comment by DanielHons** [comment]
The same holds for [ORY Hydra](https://www.ory.sh/hydra/docs/v1.6/concepts/logout/)

**Comment by ShanChathusanda93** [comment]
The same issue occurred for [WSO2 Identity Server](https://wso2.com/identity-and-access-management/).

**Comment by venkatbvc** [comment]
we are also having same issue with keycloak version 18.0.0 onwards any work around's or solution identified?

**Comment by lc-guy** [comment]
Keycloak is deprecating regular no-hint logouts. This is gonna be a pretty issue moving forward for people rolling their own authentication servers. A fix would be welcome.

**Comment by lc-guy** [comment]
Any updates on this?

**Comment by shubham-vunet** [comment]
+1

Same for IdentityServer4

**Comment by jmiguelbarone** [comment]
+1

Please  :-)

**Comment by shubham-vunet** [comment]
Again +1 For Keycloak also

**Comment by jmiguelbarone** [comment]
we've been for 3 years already ... and i think this feature is more and more important in time.

**Comment by allanian** [comment]
+1

**Comment by kendrickclark** [comment]
+1 for Keycloak

**Comment by venkatbvc** [comment]
I have made changes to support keycloak in our local branch and validated with keycloak. Other IAMs we are not using. Can i send the PR?

**Comment by shubham-vunet** [comment]
@venkatbvc 
It'll be good if you can share the diff somewhere, I was doing same thing but didn't manage to complete it.

**Comment by venkatbvc** [comment]
@shubham-vunet  Following is the function modified to achieve the behavior
`func (hs *HTTPServer) Logout(c *contextmodel.ReqContext) {
	// If SAML is enabled and this is a SAML user use saml logout
	if hs.samlSingleLogoutEnabled() {
		getAuthQuery := loginservice.GetAuthInfoQuery{UserId: c.UserID}
		if authInfo, err := hs.authInfoService.GetAuthInfo(c.Req.Context(), &getAuthQuery); err == nil {
			if authInfo.AuthModule == loginservice.SAMLAuthModule {
				c.Redirect(hs.Cfg.AppSubURL + "/logout/saml")
				return
			}
		}
	}

	name := web.Params(c.Req)[":name"]
	provider := hs.SocialService.GetOAuthInfoProvider(name)
	if provider == nil {
		hs.log.Debug()
		return
	}

    idTokenHint := ""
    POST_LOGOUT_REDIRECT_URI :=  "post_logout_redirect_uri"
    
    // Invalidate the OAuth tokens in case the User logged in with OAuth or the last external AuthEntry is an OAuth one
    if entry, exists, _ := hs.oauthTokenService.HasOAuthEntry(c.Req.Context(), c.SignedInUser); exists {
        token := hs.oauthTokenService.GetCurrentOAuthToken(c.Req.Context(), c.SignedInUser)
        if setting.SignoutRedirectUrl != "" &&  strings.Contains(setting.SignoutRedirectUrl, POST_LOGOUT_REDIRECT_URI) {
            if token.Valid() {
                    idTokenHint = token.Extra("id_token").(string)
                hs.log.Debug("post_logout_redirect_uri is configured. id token configured is", "id_token:", idTokenHint)
            } else {
                hs.log.Warn("Token is not valid")
            }
        }
        if err := hs.oauthTokenService.InvalidateOAuthTokens(c.Req.Context(), entry); err != nil {
            hs.log.Warn("failed to invalidate oauth tokens for user", "userId", c.UserID, "error", err)
        }
    }
	// Invalidate the OAuth tokens in case the User logged in with OAuth or the last external AuthEntry is an OAuth one
	if entry, exists, _ := hs.oauthTokenService.HasOAuthEntry(c.Req.Context(), c.SignedInUser); exists {
		if err := hs.oauthTokenService.InvalidateOAuthTokens(c.Req.Context(), entry); err != nil {
			hs.log.Warn("failed to invalidate oauth tokens for user", "userId", c.UserID, "error", err)
		}
	}

	err := hs.AuthTokenService.RevokeToken(c.Req.Context(), c.UserToken, false)
	if err != nil && !errors.Is(err, auth.ErrUserTokenNotFound) {
		hs.log.Error("failed to revoke auth token", "error", err)
	}

	authn.DeleteSessionCookie(c.Resp, hs.Cfg)

    if setting.SignoutRedirectUrl != "" {
        rdUrl :=  ""
        if  idTokenHint != "" && strings.Contains(setting.SignoutRedirectUrl,POST_LOGOUT_REDIRECT_URI) {
            signOutUrl := strings.Split(setting.SignoutRedirectUrl, "?")
            rdUrl = fmt.Sprintf("%s?id_token_hint=%s&%s", signOutUrl[0],idTokenHint,signOutUrl[1])
        } else {
            rdUrl = setting.SignoutRedirectUrl
        }
        hs.log.Debug("Redirect url would be","signOutUrl", rdUrl)
        c.Redirect(rdUrl)
    } else {
        hs.log.Info("Successful Logout", "User", c.Email)
        c.Redirect(hs.Cfg.AppSubURL + "/login")
    }
}`

**Comment by shubham-vunet** [comment]
@venkatbvc Thanks for sharing the diff, ~Seems like I m on a old branch and it doesn't apply.~

While I was working, I had a `userToken` which was a wrong token.
and I was not able to call `token.Extra('id_token')`
`oauthToken` was accessible through `hs.DataProxy.OAuthTokenService` which I was not aware.

Thanks again for your help.

Are you planning to create a PR.

**Comment by venkatbvc** [comment]
@shubham-vunet  i will push the PR

**Comment by venkatbvc** [comment]
@shubham-vunet  Today i am occupied with some work. I will push the changes tomorrow.

**Comment by scolton99** [comment]
Just want to +1 this one more time -- I see some exciting work on the pull request and it would be super helpful to have this.

**Comment by Jguer** [comment]
Thanks for the patience everyone, we've been evaluating how to best solve this as not having a logout URL per auth integration tightly links this to all auth providers even if it's only used by Grafana. 

The current implementation @venkatbvc seems to work around it enough that after testing it against the supported idPs we might merge it even if we plan to dismember signout_url to a provider specific option in the future

**Comment by venkatbvc** [comment]
@Jguer Thanks.  
I would like to contribute when signout_url move to specific oauth sections.
