### ISSUE TITLE
v7.0.0-beta3 Date/Time Formatting Override in Table not working on date fields

### ISSUE THREAD

**Issue by ultrafastneal** [grafana/grafana#24655]
**What happened**:
Applying Date/Time format to a table column as an override does not format the Date/Time. 

**What you expected to happen**:
The specified date/time format specification should be applied to the cell 

**How to reproduce it (as minimally and precisely as possible)**:
Create new table from query, add override to a datetime field 

**Anything else we need to know?**:
I believe this works if the data is a timestamp but not if it's a pre-formatted date/time. My datasource is  Microsoft Log Analytics with a custom query 

**Environment**:
- Grafana version: Grafana v7.0.0-beta3 (2169fc1a3f)
- Data source type & version: Azure Log Analytics (built-in datasource)
- OS Grafana is installed on: Windows server 2016 (core)
- User OS & Browser: Mac OS running latest Chrome Version 81.0.4044.138  (64-bit)
 - Grafana plugins: None (just core bundled)
- Others:

**Comment by ivanahuckova** [comment]
Thanks so much for reporting this issue @ultrafastneal!🙏

**Comment by torkelo** [comment]
opened PR to try to address this: https://github.com/grafana/grafana/pull/25195
