### ISSUE TITLE
Legend decimal is higher than axis

### ISSUE THREAD

**Issue by ilevac** [grafana/grafana#24651]
If I set axis decimal to let say **x**, while legend decimal is set to **auto**, axis will have **x** decimal and legend will have **x+1** decimal.
When legend is set to auto it's expected to have the same decimal as axis.

**Environment**:
- Grafana version: 7.0.0B3
- Data source type & version: influxdb 1.8.0
- OS Grafana is installed on: docker swarm (engine version 19.03.8)
- User OS & Browser: Chrome 81.0.4044.138
- Grafana plugins: grafana-worldmap-panel, yesoreyeram-boomtable-panel, andig-darksky-datasource, grafana-clock-panel, grafana-piechart-panel, percona-percona-app, camptocamp-prometheus-alertmanager-datasource

Json panel:

> {
  "datasource": "Telegraf - Standalone",
  "alert": {
    "alertRuleTags": {},
    "conditions": [
      {
        "evaluator": {
          "params": [
            16
          ],
          "type": "gt"
        },
        "operator": {
          "type": "and"
        },
        "query": {
          "params": [
            "A",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "last"
        },
        "type": "query"
      },
      {
        "evaluator": {
          "params": [
            16
          ],
          "type": "gt"
        },
        "operator": {
          "type": "and"
        },
        "query": {
          "params": [
            "B",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "last"
        },
        "type": "query"
      },
      {
        "evaluator": {
          "params": [
            22
          ],
          "type": "gt"
        },
        "operator": {
          "type": "and"
        },
        "query": {
          "params": [
            "C",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "last"
        },
        "type": "query"
      }
    ],
    "executionErrorState": "alerting",
    "for": "5m",
    "frequency": "1m",
    "handler": 1,
    "message": "APC - PDU - 2 - Near Overload",
    "name": "APC - PDU - 2 - Near Overload",
    "noDataState": "no_data",
    "notifications": [
      {
        "uid": "g4I5R0CZz"
      }
    ]
  },
  "aliasColors": {
    "B1": "dark-blue",
    "B2": "dark-red",
    "Total": "dark-purple"
  },
  "dashLength": 10,
  "fill": 1,
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 9
  },
  "id": 23763571993,
  "legend": {
    "avg": true,
    "current": true,
    "max": true,
    "min": false,
    "show": true,
    "total": false,
    "values": true,
    "alignAsTable": true,
    "rightSide": true
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "options": {
    "dataLinks": []
  },
  "pointradius": 2,
  "renderer": "flot",
  "seriesOverrides": [
    {
      "$$hashKey": "object:1990",
      "alias": "Total"
    }
  ],
  "spaceLength": 10,
  "targets": [
    {
      "alias": "B1",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "apc_pdu2",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "B1"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          },
          {
            "params": [
              " / 10"
            ],
            "type": "math"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "B2",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "apc_pdu2",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "B2"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          },
          {
            "params": [
              " / 10"
            ],
            "type": "math"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Total",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "apc_pdu2",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Total"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          },
          {
            "params": [
              " / 10"
            ],
            "type": "math"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": [
    {
      "colorMode": "critical",
      "fill": true,
      "line": true,
      "op": "gt",
      "value": 16
    }
  ],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "APC - PDU - 2",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "$$hashKey": "object:561",
      "format": "amp",
      "label": "Load",
      "logBase": 1,
      "max": "25",
      "min": "0",
      "show": true,
      "decimals": 2
    },
    {
      "$$hashKey": "object:562",
      "format": "amp",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": "0",
      "show": false
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  },
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "bars": false,
  "dashes": false,
  "fillGradient": 0,
  "hiddenSeries": false,
  "percentage": false,
  "points": false,
  "stack": false,
  "steppedLine": false
}

**Comment by ivanahuckova** [comment]
Hello @ilevac. By default the tooltip will show one more decimal than the y axis ticks. The reasoning here is that you likely want more precision in tooltip/legend then y axis tick labels.

**Comment by ilevac** [comment]
I didn't recall having that issue with 6.0, but thank you for your fast answer! :)
