### ISSUE TITLE
OpenTSDB: Add support for templating multi value and All value

### ISSUE THREAD

**Issue by mdehus** [grafana/grafana#2465]
Right now the two options for multi-select are glob or regex values, neither of which generate a valid search string for opentsdb.  This is the same case for the all values and it leaves the only option to use the wildcard (*).  I've confirmed via wireshark that the values showing up are incorrect.. for example, with multi-select it sends: {host1,host2} when it should be sending host1|host2.

**Comment by torkelo** [comment]
this would be an awesome addition. Hope someone submits PR for it :)

**Comment by digrich** [comment]
When we are going to have this support for OpenTSDB? This will really help us to compare multiple series at the same time.

**Comment by digrich** [comment]
+1

**Comment by utkarshcmu** [comment]
@mdehus , @digrich - Once @torkelo merges the above pull request, we should be able to have "multi-select" working for Opentsdb Templates.

**Comment by utkarshcmu** [comment]
This is done as #2808 is merged. We can close this issue I think. :)
