### ISSUE TITLE
CloudWatch Repeated Multi-Value Variable

### ISSUE THREAD

**Issue by niklaskhf** [grafana/grafana#24658]
**What happened**:
Using multi-value variables in CloudWatch queries is not allowed. -> Expected
Using multi-value variables within a repeated panel in CloudWatch queries (only one value) returns CloudWatch template error -> Not expected, since variable is repeated and only has one value 

**What you expected to happen**:
Using multi-value variables in CloudWatch queries is not allowed. -> Expected
Using multi-value variables within a repeated panel in CloudWatch queries (only one value) returns CloudWatch template error -> No error

**How to reproduce it (as minimally and precisely as possible)**:
- Create a multi-value variable
- Create a row and repeat on the multi-value variable
- Add a panel inside the row and use the repeated variable in the CloudWatch query

**Anything else we need to know?**:

**Environment**:
- Grafana version: f97d021c587b5fff3db1b2d589ecef7826b1e612
- Data source type & version: CloudWatch 
- OS Grafana is installed on: Arch Linux
- User OS & Browser: MacOS & Safari
- Grafana plugins: None
- Others: None

**Comment by daniellee** [comment]
@niklaskhf can you explain why you are trying to create a repeating panel with a template variable with one value? I don't understand the problem you are trying to solve.

**Comment by niklaskhf** [comment]
This seems to be working as intended now. I'm not sure if anything in Grafana changed since, or if it was user error from my side.
