### ISSUE TITLE
Expand a collapsed row is detected as dashboard change

### ISSUE THREAD

**Issue by scardena** [grafana/grafana#24657]
**What happened**:
Not sure if this is a bug or if this is the intended behaviour. on any dashboard I have tested so far:
* If you collapse an expanded row, Grafana will not identify it as a change.
* If you expand a collapsed row, grafana will identify it as a change, hence prompting you to save or discard changes (which is annoying).
I think this is a bug, because both actions (expanding and collapsing) should have the same behaviour.

**What you expected to happen**:
Have both actions consistent (collapse an expanded row and expand a collapsed row should either both prompt for changes, or none of them should prompt for changes). Ideally I would like to 

**How to reproduce it (as minimally and precisely as possible)**:
Open any dashboard that has Editing enabled, and has a row:
1. If a row is expanded, click on the arrow to collapse, then click on dashboards (four squares button on the left colum). You will change to dashboard view without problems
2. if a row is collapsed, click on the arrow to expand it, then click on dashboards  (four squares button on the left colum). You will be prompted to save your changed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.7.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: ubuntu / chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
added this issue that could solve this: https://github.com/grafana/grafana/issues/24663
