### ISSUE TITLE
Grafana Cannot Get Data from Graphite

### ISSUE THREAD

**Issue by JammyMarshall** [grafana/grafana#2466]
I have installed Graphite, and it worked very well at 80 port. Then I installed Grafana 2.1 in my system, and it also worked very well at port 3000. However, after I log into Grafana and set Database source, it show nothing in home dashboard. 
![1](https://cloud.githubusercontent.com/assets/13697952/9142262/8c093514-3d0c-11e5-8257-84b9c7222e09.png)

Here is my system information:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release: 14.04
Codename: trusty

All configuration finished at /usr/share/grafana/conf/defaults.ini

Thank you very much!

**Comment by torkelo** [comment]
Not sure what you mean show nothing in home dashboard. have you created a new dashboard and added a graph panel? Take time to look at the getting started guide and the building dashboard screencast available on the docs site.

**Comment by JammyMarshall** [comment]
Thank you very much! That is my fault. Sorry for that
