### ISSUE TITLE
Search: add number of dashboards indicator to collapsed folders

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#24662]
It would be good to add `dashboard count` next to folders – right now collapsed folder (gdev dashboards) looks like an empty one 👇 
![image](https://user-images.githubusercontent.com/15225624/81834931-ef64e080-9541-11ea-872d-f3a83977a0d9.png)

_Originally posted by @sarlinska in https://github.com/grafana/grafana/issues/23551#issuecomment-628079647_

**Comment by Clarity-89** [comment]
Good idea! @sarlinska do you have any UI ideas for this or is it just a number next to the folder name?

**Comment by sarlinska** [comment]
@Clarity-89 just a number in brackets, eg. `gdev dashbaords (121)`

**Comment by Clarity-89** [comment]
Looked into this a bit closer and realised we don't have the data about total number of dashboards in a folder when the initial search query is made. @sakjur would it make sense to add an `itemCount` prop to the folder results, to indicate how many dashboards a folder has, on the backend or is it too complicated? I assume it's gonna require an extra database query.

**Comment by dprokop** [comment]
@Clarity-89 FYI when you start working on this there is UI component for displaying the counters already  (`Counter`).

Looks like this:
![image](https://user-images.githubusercontent.com/2376619/82879599-700dde80-9f3d-11ea-9b63-ee8b190c0103.png)

**Comment by sakjur** [comment]
@Clarity-89 🤔 It's easily cacheable for any reasonable number of folders, so we could do it without having to add an extra query (if we were to introduce a second database query for search there are other things we could do, it's a matter of performance/features, imo this is not what we should slow down search with) by having a background job for this, but making those changes is quite a bit of work.

For any accurate count from the backend this is not by any means trivial 🙂

**Comment by sakjur** [comment]
(not saying we shouldn't do it, but it's more work than just exposing a number the backend already has so we'd have to put this into a proper backlog and prioritize it)

**Comment by Clarity-89** [comment]
> so we'd have to put this into a proper backlog and prioritize it
Yeah, let's do that. Didn't realise myself this wasn't a trivial thing to do.

**Comment by hugohaggmark** [comment]
Hi @sakjur do you know who could help us with the count implementation? 

Some context: we're doing a redesign of Folder Management in the Frontend and this count would be an important piece in that work. Is this something someone in the "grafana/backend-platform" or "grafana/backend-enterprise" could help out with?

**Comment by hugohaggmark** [comment]
sorry I forgot to mention, that this would of course need to be prioritised and scheduled, we're not expecting this to be done asap 🙈

**Comment by sakjur** [comment]
I think that the backend platform team are the owners of this and should be asked first 🤔 Otherwise, the Grafana Enterprise Engagement team could possibly be interested in cooping with you on improving the search experience.

I guess it'd help a bit to have that counter be `0-99+` to be able to cheat a little for really big installations.
