### ISSUE TITLE
Information Disclosure - Suspicious Comments

### ISSUE THREAD

**Issue by dongwangdw** [grafana/grafana#24676]
**What happened**:
Got script from api.
**What you expected to happen**:
at least good.
**How to reproduce it (as minimally and precisely as possible)**:
with grafana link, appending the path below one by one you will get the js script.
public/build/59.024ec70f970451034ea6.js
public/build/azureMonitorPlugin.024ec70f970451034ea6.js
public/build/vendors~app.024ec70f970451034ea6.js
public/build/58.024ec70f970451034ea6.js
public/build/UsersListPage.024ec70f970451034ea6.js
public/build/lokiPlugin.024ec70f970451034ea6.js
public/build/postgresPlugin.024ec70f970451034ea6.js
public/build/cloudwatchPlugin.024ec70f970451034ea6.js
public/build/app.024ec70f970451034ea6.js
public/build/TeamPages.024ec70f970451034ea6.js
/public/build/stackdriverPlugin.024ec70f970451034ea6.js
public/build/elasticsearchPlugin.024ec70f970451034ea6.js

and other api in public/build.
**Anything else we need to know?**:

**Environment**:
- Grafana version:
2.15.2 and 5.2.0
- Data source type & version:
prometheus
- OS Grafana is installed on:
redhat
- User OS & Browser:
safari
- Grafana plugins:
No
- Others:

**Comment by ivanahuckova** [comment]
Sorry, but not enough details to look into this. If you would like to reopen the issue, please provide more information.
