### ISSUE TITLE
Alerts not working - when 1 of X nodes go down (even with "no data" -> alert)

### ISSUE THREAD

**Issue by huglester** [grafana/grafana#24673]
**So we have currently alerts work like that**:
![image](https://user-images.githubusercontent.com/150731/81918233-e70eb300-95de-11ea-9999-bfe92c73279f.png)

**All works good, unless host goes down and does not report any data.**

For example one node stop sharing data (node exporter down, host down) - I get no alert. because other 6 hosts are up. 

I dig google and such - but did not found a sollution for this. It must be:
a) something easy/obvious 
b) workaround?

**adding "has no value" also does not trigger alert**:
![image](https://user-images.githubusercontent.com/150731/81919234-3f928000-95e0-11ea-92b1-664dcfc92d9a.png)

Can anyone give insight into this?

**Comment by bergquist** [comment]
I need more details to answer this. What datasource are you using and what does the query look like?
If you expect 7 hosts/targets/servers to be up, maybe you can count the amount and alert if it goes below 7?

**Comment by torkelo** [comment]
the threshold is defined in using wrong syntax, change it to `0.1`
