### ISSUE TITLE
Alias for loki queries on the Grafana Dashboard

### ISSUE THREAD

**Issue by Mitsuder** [grafana/grafana#24679]
For regular queries in the panel of Grafana dashboard (e.g. with InfluxDB source) it is possible to set an alias so that it will be shown under the panel in the legend section.

If I use Loki as a Datasource than it is impossible. Grafana just shows a long line describing what parameters were used to construct this line. I believe it would be really helpful and user-friendly to have a possibility to set these aliases.
![image](https://user-images.githubusercontent.com/17033600/80378724-c1c33a80-88a5-11ea-956b-f666f851cfc0.png)

**Comment by ivanahuckova** [comment]
Hello @markkuit! I have added this feature request to our backlog. Not sure about exact ETA, but you will be able to see it in this issue - it will be moved to _In progress_.
