### ISSUE TITLE
[2.1.0] Log file permissions are too strict

### ISSUE THREAD

**Issue by mbell697** [grafana/grafana#2468]
It seems the default permissions for `grafana.log` are 0640 which is a little more restrictive than needed IMO. In particular it makes it more difficult than it should be to send the logs to a central logging system, i.e. a logstash agent can't read the log without a bunch of shenanigans. 

`xorm.log` uses 0644 by comparison which i think is a better default.

**Comment by torkelo** [comment]
I agree, PR would be great

**Comment by rbroemeling** [comment]
@torkelo Note that the grafana.log file contains database logins and credentials, i.e.

    2015/09/25 19:16:47 [I] Database: mysql, ConnectionString: <USER>:<PASSWORD>@tcp(<HOST>:<PORT>)/<DB>?charset=utf8

If it is going to contain secrets/credentials like that, it most certainly should not be world-readable.  Either all such secrets should be removed/grafana should take care not to log them, or else the permissions on grafana.log should be tightened up again.

**Comment by torkelo** [comment]
That is fixed, the connection string is. no longer written to the log
