### ISSUE TITLE
Could not find plugin definition for data source

### ISSUE THREAD

**Issue by smarkm** [grafana/grafana#24688]
**What happened**:
I'm trying to develop a backend data source use the backend datasource template, but when I trying to add the new datasource I got this message `Could not find plugin definition for data source: ...`, and the datasource did not show on the view
**What you expected to happen**:
I can add the new template datasource
**How to reproduce it (as minimally and precisely as possible)**:

1. `npx "@grafana/toolkit"@next plugin:create  ${datasource name}`
2. `yarn dev`
3. `mage -v buildAll`
4. restart grafana 

**Anything else we need to know?**:
what I missing for build backend datasource ?
**Environment**:
- Grafana version: 7.0.0
- Data source type & version: backend datasource
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: customized develop 

**The project view like this:**
![image](https://user-images.githubusercontent.com/5517120/81941498-7b9f0280-962b-11ea-9e74-1e380d585514.png)

**Comment by bergquist** [comment]
What's the full path to your plugin directory and what's the configured plugin directory in grafana (logged at start-up)?

**Comment by kylebrandt** [comment]
Is there an error about signing earlier up in the log? You may need the following in your Grafana's config.ini file:

`allow_loading_unsigned_plugins = fp-grafana-file-datasource`

**Comment by smarkm** [comment]
> Is there an error about signing earlier up in the log? You may need the following in your Grafana's config.ini file:
> 
> `allow_loading_unsigned_plugins = fp-grafana-file-datasource`
 it's address the issue, thank you @kylebrandt and @bergquist
