### ISSUE TITLE
Azure Monitor Datasource: Success displayed as error when configuring datasource 

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#24689]
**What happened**:
Configured Azure Monitor with With all 3 APIs, get the following response:

![image](https://user-images.githubusercontent.com/1692624/81942141-bff8b700-95c7-11ea-9390-ddf3b5cccc1b.png)

> 1. Successfully queried the Azure Monitor service. 2. Application Insights: Returned http status code 204 3. Successfully queried the Azure Log Analytics service.

**What you expected to happen**:

I am guessing the 204 HTTP status code (No Content) in this case means success. If that is the case, this should be green (with sparkles!) instead of red with a warning icon.

**Environment**:
- Grafana version: v7.1.0-pre (01bbcf4eea)
- Data source type & version: Azure Monitor (Core)

**Comment by kylebrandt** [comment]
nevermind, just a bad configuration for application insights, so the error is correct.

**Comment by kpfaulkner** [comment]
Have just hit the same issue. I've a few other App Insight datasources configured (but did those ages ago with version 6.x of Grafana, this is the first time actually adding a fresh AI datasource freshly into 7.x). Same error as you. But given there are 2 only bits of info required (app ID and app key), I cant see how I'm messing that up. When you said "bad configuration for app insights" were you referring to Grafana end or Azure?
