### ISSUE TITLE
Azure Monitor Plugin: Plugin readme/help is missing

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#24696]
**What happened**:

From Plugins list, click Azure monitor:

> "No plugin help or readme markdown file was found"

![image](https://user-images.githubusercontent.com/1692624/81947052-1b2da800-95ce-11ea-876b-86e71514b8c6.png)

**What you expected to happen**:

I see help in other core datasources, so would expect something here.

**Environment**:
- Grafana version: v7.1.0-pre (01bbcf4eea)
- Data source type & version: Azure Monitor

**Comment by kylebrandt** [comment]
Looks like `public/app/plugins/datasource/grafana-azure-monitor-datasource` needs a README.md.

**Comment by joshhunt** [comment]
Azure Monitor plugin now has a readme that points to the documentation website.
