### ISSUE TITLE
Feature Request :-Allowing  ldap members of group to be the grafana-admin along with the org admin 

### ISSUE THREAD

**Issue by shankarramshivram** [grafana/grafana#2469]
HI,

Currently i am able to make the ldap users only the org admin based on a ldap group

Is it possible to grant  the members of a group grafana-admin role along with the org admin.

Currently i have to login as a local grafana admin user and then manually go to grafana admin panel and check the option against the ldap user for allowing him to become grafana-admin.

Something like a flag inside group mapping saying  - 

[[servers.group_mappings]]
group_dn =  ....
org_role = ...
org_id = ...
"grafana_admin = true"

**Comment by slick666** [comment]
+1 for this feature

**Comment by gummeah** [comment]
+1 that would be very useful. I'm surprised that there is no such option yet.

**Comment by KKeXX** [comment]
+1
I would like to see this feature as well!

**Comment by matthgyver** [comment]
+1 for this feature
Thank you

**Comment by vishksaj** [comment]
+1 for this feature
Thank you

**Comment by rrbarreto** [comment]
+1 for this feature
Thank you

**Comment by casdr** [comment]
Any update on this?

**Comment by dynamik7** [comment]
+1 for this feature
Thank you

**Comment by ikkaro** [comment]
+1

**Comment by vitalvas** [comment]
+1

**Comment by toomasp** [comment]
+1

**Comment by Mohaneshwari** [comment]
+1

**Comment by torkelo** [comment]
implemented by https://github.com/grafana/grafana/pull/12622
