### ISSUE TITLE
Templating: Query variable pick last value 

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#24693]
**What would you like to be added**:

Right now there are several functions that can be used in the query input field for prometheus datasource (e.g. `label_values`) and it is pretty common to use them to populate such values to variable.
Problem is that there is no way to take `last` or `first` value 

**Why is this needed**:

There are a lot of plugins that support templating, e.g. text plugin, and this is also pretty common to use such plugin to show e.g. release version. So setting will look like:
```
<b>Version $version</b>
```
and thats where problem appears with several labels (probably this can happen with big time range) default `replaceVariables` can not handle this smarter..

maybe this can be handled other way (e.g. in template `$version.last`)

**Comment by torkelo** [comment]
not sure this makes sense, template variable only has a current value  (not a last / first)

**Comment by vankop** [comment]
@torkelo Did not get it.. e.g. I have variable $version with metric `label_values(up{}, "version")` with timerange e.g. 1month I can have 2 or more versions, they will be rendered as v1,v2,v3. I suggested to do it smarter => pick latest or make it possible using template string
