### ISSUE TITLE
Error "Dashboard not found" when press "Links" at dashboards settings

### ISSUE THREAD

**Issue by seriych** [grafana/grafana#24706]
**What happened**:
Error "Dashboard not found" when press "Links" at dashboards settings.
![grafana_links2](https://user-images.githubusercontent.com/15708872/81968605-47c0de80-9625-11ea-905e-833712705c8b.png)
![grafana_links](https://user-images.githubusercontent.com/15708872/81968602-468fb180-9625-11ea-8cd8-bdd8623d5c7e.png)

**What you expected to happen**:
Open dashboard links settings

**How to reproduce it (as minimally and precisely as possible)**:
Install v7.0.0-beta3, create any dashboard, oper dashboard settings, press "Links"

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.0-beta3 (2169fc1a3f)
- Data source type & version: PostgreSQL 12.2
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser: Windows 10, Chrome/Vivaldi/Firefox
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
Fixed in nightly / upcoming stable
