### ISSUE TITLE
v7.0.0-beta3: Problem with rendering gauge panel

### ISSUE THREAD

**Issue by A-styler** [grafana/grafana#24700]
**What happened**: Incorrect render in gauge panel

![opera_Qsn3PMko4e](https://user-images.githubusercontent.com/33700018/81960535-c3b52980-9619-11ea-9949-ab8991597bd5.png)

**What you expected to happen**: Every OK is green

![opera_sDVbCL0AbE](https://user-images.githubusercontent.com/33700018/81959577-5c4aaa00-9618-11ea-82eb-2390d0991dc4.png)

**How to reproduce it (as minimally and precisely as possible)**: Any metric with 0/1 values, gauge panel with vertical orientation, basic display mode and green threshold after 1%

**Anything else we need to know?**: Changing timeframe can change rendered dashboard but it still wrong

**Environment**:
- Grafana version: 7.0.0-beta3
- Data source type & version: VictoriaMetrics v1.35.2 and prometheus v2.17.2
- OS Grafana is installed on: official docker image
- User OS & Browser: Windows 10 2004, Chrome 81.0.4044.138 
- Grafana plugins: Alertmanager
- Others: This is my explore: up{job="users", service="node_exporter"}

![opera_hnlv9gQEll](https://user-images.githubusercontent.com/33700018/81959591-5fde3100-9618-11ea-88e7-55a7244c8fc8.png)
Display settings

![opera_L5r9ybgSFN](https://user-images.githubusercontent.com/33700018/81959908-d713c500-9618-11ea-8d51-46dde0a42cb7.png)

**Comment by torkelo** [comment]
Try set the min & max, the auto min & max might not work in your case (as it covers all the series). 

Can you show in the table what your query returns?

**Comment by A-styler** [comment]
> what your query returns?

You can see at screenshot in previous message.

> >Try set the min & max,

If you mean Value in Display option - nothing changed.

Also I guess it happens thro the old values with old timefram wich return 0 and 1. One 0 target 
now is turned off 
![opera_YBW9CGuiB0](https://user-images.githubusercontent.com/33700018/82035525-4be21000-96a8-11ea-8709-b037acfd9705.png)
![8byM0hQUXg](https://user-images.githubusercontent.com/33700018/82036302-6b2d6d00-96a9-11ea-8ef3-1da3267205a8.gif)

**Comment by torkelo** [comment]
This works as expected just make sure you set min & max in Field tab

<img width="363" alt="Screen Shot 2020-05-28 at 18 45 01" src="https://user-images.githubusercontent.com/10999/83169462-5b833f00-a113-11ea-8e31-71415e6cd1ce.png">

**Comment by A-styler** [comment]
With these values it look like ok, thank you
