### ISSUE TITLE
Table panel: Auto fit column width with % to Table width

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24719]
**What would you like to be added**:
Auto fit column width with % to Table width 
For examle
Col1 = 30%
Col2 = 20%
Col3 = 50%
**Why is this needed**:

Monitor1

![image](https://user-images.githubusercontent.com/2898361/82015310-47195e00-96a0-11ea-87ff-c292b64d3f2b.png)

Monitor2

![image](https://user-images.githubusercontent.com/2898361/82015082-c22e4480-969f-11ea-9ff8-cda762fb340a.png)

**Comment by baur** [comment]
also can't find font size as in old version

![image](https://user-images.githubusercontent.com/2898361/82016529-0ff87c00-96a3-11ea-860b-c9c1f7a103e3.png)

**Comment by baur** [comment]
Auto width not works on small width
third column not visible

![image](https://user-images.githubusercontent.com/2898361/82039209-75aa2f80-96c6-11ea-9b26-dcd7fc50b59b.png)

in old version works fine

![image](https://user-images.githubusercontent.com/2898361/82039315-a5593780-96c6-11ea-9e79-1c5281281b41.png)

**Comment by baur** [comment]
related issue with table also #24231 (add support for nested header cells, its very important in order to use transform -> JOIN)

**Comment by zaufi** [comment]
The other options better to have:
* width in symbols -- i.e. I know that my column not longer that 10 symbols...
* max-width in percents or symbols -- meaning that there is no need to extend column wider than a given value
* min-width ...

Yeah, some control as CSS has over tables is highly required.

**Comment by aladrin** [comment]
yeah this is a very annoying UI issue, i hope someone has time to look at it eventually

**Comment by GollaSaiVenkatesh** [comment]
yeah, please look into this

**Comment by baur** [comment]
Min width resolve this issue
