### ISSUE TITLE
Loki Live Tail does not work - Websocket issue

### ISSUE THREAD

**Issue by aarrtteemmuuss** [grafana/grafana#24714]
**What happened**:

Installed Loki + Grafana using Helm in K8S AWS EKS cluster, everything works fine, besides live tail.
When trying to open Live Tail getting this errors in browser: 

`WebSocket connection to 'wss://grafana.mydomain.com/api/datasources/proxy/1/loki/api/v1/tail?query=%7Bapp%3D%22myapp%22%7D' failed: Error during WebSocket handshake: Unexpected response code: 400`

In Loki pod I can see this error: 
`msg="Error in upgrading websocket" err="websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"`

I have tried to add Upgrade header in datasource settings. Did not help. 
I that case I am getting in browser:

`WebSocket connection to 'wss://grafana.mydomain.com/api/datasources/proxy/1/loki/api/v1/tail?query=%7Bapp%3D%22myapp%22%7D' failed: Error during WebSocket handshake: Unexpected response code: 502`

And in Loki:
`level=error ts=2020-05-14T22:46:16.431318905Z caller=http.go:209 msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2020-05-14T22:46:17.954408122Z caller=tailer.go:97 msg="Error writing to tail client" err="rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called"`

What am I doing wrong here? 

**What you expected to happen**:
Expected to receive live stream logs.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Loki and Grafana are deployed behind AWS ALB load balancer which supports websockets by default.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: loki 1.4.1
- OS Grafana is installed on: k8s cluster
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by ivanahuckova** [comment]
Hello @aarrtteemmuuss, can you check if following https://github.com/grafana/grafana/issues/22905#issuecomment-628442315 doesn't solve your problem

**Comment by aarrtteemmuuss** [comment]
@ivanahuckova thank you for your answer. 
When I am adding those headers I am getting errors as I stated above, 502 on browser and unexpected EOF on Loki. Can it be related to AWS ALB that is being used?

**Comment by Estrax** [comment]
@aarrtteemmuuss Thanks for reporting. There are a couple of things that can have an impact on the outcome.
1, Do you use Cloudflare's WAF (Web Application Firewall)? If so, do you have its config set up properly to allow websockets connections?
2. Are your instances behind a proxy? Can you check whether the proxy pass and headers are set up properly?
3. When using Amazon's ALB, maybe enabling sticky sessions is going to help?

**Comment by Estrax** [comment]
Can confirm - live tailing with Loki datasource works properly in Grafana. Must be either a proxy/firewall/AWS ALB sticky sessions issue/misconfiguration.

**Comment by ysaakpr** [comment]
Authentication failed; no valid credentials available, Any hints on how to resolve this, is this because i am using google signing to login to grafana, but loki datasource is set to basic auth only.

**Comment by windware-ono** [comment]
Same error as above for `Authentication failed; no valid credentials available`. I do not have any basic auth against grafana nor loki and followed advices on https://github.com/grafana/grafana/issues/22905 but still getting the error.
