### ISSUE TITLE
Snapshot expiration options

### ISSUE THREAD

**Issue by E2Ecerch** [grafana/grafana#2471]
Hi.  Snapshot expiration default option is NEVER (which is 50 years).  To ensure that the snapshots don't fill up the allocated space, how can we change the default expiration of never to a smaller period? I tried removing/changing the Never value and the logic still creates a blank line in the drop down list (which happens to be 50 years).  Where can I change the 50 year value to say 1 year, 6 months, or etc?  Thanks.

**Comment by torkelo** [comment]
there is no option to set default expiration time currently
