### ISSUE TITLE
Enhance 'Custom' variable behavior to make it more 'Text box' like.

### ISSUE THREAD

**Issue by sknaumov** [grafana/grafana#24717]
**What would you like to be added**:

Add 'noclear' and 'editable' options to Custom variable, fix width of input field.

**Why is this needed**:

Currently custom variable is used mainly to select some value from predefined options. However, it has some serious limitations:

- If user wants to copy content of this variable, for example, he selected UUID of device to debug, and then wants to copy it somewhere else, say, into another dashboard open on another page, he can't do it, as when you click on the custom variable, the text is getting cleared from the input field. The only option then is to find UUID in page URL and copy it from there.
- Custom variable allows to provide some non-predefined values, but there are 2 usability problems:
    -   If user provided some custom value and wants to slightly edit it, he needs to retype everything, as this value is cleared when he clicks on variable to edit it.
    -   If there is a predefined value, and custom value that user wants to type is a prefix of this predefined value, then user won't be able to set this value, as predefined option will always be selected on Enter. Say, if I have a custom variable for syslog filter and have predefined options with most commonly-used filters, say, 'iwevent', to show all wireless driver events, then I can't filter logs just by 'iw'.

This PR (https://github.com/grafana/grafana/pull/24681) provides a way to have best of both worlds of 'Text box' and 'Custom' variables combined - have a predefined list of most commonly used options in drop-down menu, but at the same time have an ability to provide a custom value and easily edit it.

This PR also fixes issue with insufficient size of input field of custom variable. Currently input width is not computed correctly and, moreover, is capped at 80px, which is not enough for a lot of cases. And it makes no sense, as when variable value is entered, input field disappears and current variable value is shown in full length. This PR changes a way of input field width computation and sets sensible min/max limits. For example, max limit is enough to show UUID in a custom variable field.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
