### ISSUE TITLE
Display the number of occurence of each value of a field

### ISSUE THREAD

**Issue by Totalus** [grafana/grafana#24716]
## What would you like to be added ?

A way to display the number of occurrence of each value of a specified field in my data.

Example of data received:
| timestamp | level | message |
| --- | --- | ---
| 100001 | "warning" | "Warning 401"
| 100002 | "error" | "Error 102"
| 100003 | "info" | "Info message 1"
| 100004 | "error" | "Error 100"
| 100005 | "info" | "Info message 2"
| 100006 | "error" | "Error 100"

From that data, I would like to display the following:

| level | count |
| --- | ---
| "error" | 3 |
| "info"  | 2 |
| "warning" | 1 |

## Why is this needed ?

To answer the question **_How many occurrence of each value of this field is there in the data?_**
I haven't find an easy way to display this info (lead me to it if there is one).

## How should we implement that (suggestion)

I see this very suited to be implemented as a simple [Transformation](https://grafana.com/docs/grafana/latest/panels/transformations/), specifying which field name we want to apply it on.

**Comment by torkelo** [comment]
Created an issue for the group by transform: https://github.com/grafana/grafana/issues/25594  and added this feature description to that
