### ISSUE TITLE
Support a better touch experience on Windows touch devices

### ISSUE THREAD

**Issue by andrasg** [grafana/grafana#24725]
I have tried using Grafana v6.7.3 on a Windows 10 touch device in Microsoft Edge (v84) and I constantly end up rearranging panels while all I wanted was just to scroll the page.

Is there anything you can do to make the experience better? E.g.: Instead of starting a draganddrop immediately, only start rearranging the panels after I have keep holding my finger on a panel for a while and otherwise just scroll?

**Comment by zoltanbedi** [comment]
This is a duplicate of https://github.com/grafana/grafana/issues/25360 and probably fixed, if it is not the case we can reopen this.
