### ISSUE TITLE
LDAP search filter needs to accept compound search filters

### ISSUE THREAD

**Issue by shankarramshivram** [grafana/grafana#2472]
I was trying to put in a compound search filter  for searching users by username or email -

search_filter = "(|(mail=%s)(sAMAccountName=%s))"

However this pops up the following error -

2015/08/07 21:17:11 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: LDAP Result Code 201 "": ldap: finished compiling filter with extra at end: )

If i use only sincle search filter it works .

Can we support compound filters the login page says for user login "email or username",

was trying to create the search filter string using this article - https://www.centos.org/docs/5/html/CDS/ag/8.0/Finding_Directory_Entries-LDAP_Search_Filters.html

**Comment by torkelo** [comment]
implemented!

**Comment by ulope** [comment]
This seems to be broken again(?).

Grafana 3.0.3.

ldap.toml
```
search_filter = "(&(objectClass=person) (sAMAccountname=%s))"
```

Log:
```
lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=1 uname= error="LDAP Result Code 201 \"\": ldap: finished compiling filter with extra at end: (sAMAccountname=someuser))"
```

**Comment by torkelo** [comment]
Seem the error is from ldap not grafana

**Comment by ulope** [comment]
We use this exact filter string in other software without problems.

**Comment by danmur** [comment]
This still seems to be an issue. Removing spaces from the query worked for me. I don't think it's a problem with the LDAP server (we also use this query elsewhere), possibly it's getting mangled somewhere before it gets there.

**Comment by dstieglitz** [comment]
This should be re-opened, or re-ticketed, it seems there is something adding parenthesis somewhere in the call chain:

In config:
```
      search_filter = "uid=%(login)s"
```

In log:
```
lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 201 \"Filter Compile Error\": ldap: finished compiling filter with extra at end: id=%(login)s)
```

**Comment by dstieglitz** [comment]
So, for posterity, I'm going to note here that Grafana LDAP only seems to support a subset of filters. For us,

```
search_filter = "(|(cn=%s)(uid=%s))"
```

Works, while

```
search_filter = "(|(cn=%(login)s)(uid=%(login)s))"
```

doesn't. I'm not an expert on LDAP filters, but the latter filter works for us with other applications. YMMV
