### ISSUE TITLE
Update cherry-pick toolkit to ignore not merged pull (closed) requests

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#24728]
**What happened**:
Currently the grafana-toolkit for generating cherry-picks includes also closed (not merged pull requests). These pull requests should not be included.
A similar [check](https://github.com/grafana/grafana/pull/21641) is implemented for changelog generation.

**Comment by papagian** [comment]
This is already fixed.

**Comment by dprokop** [comment]
fixed by https://github.com/grafana/grafana/pull/24402
