### ISSUE TITLE
Chinese letter not shown when shared by Direct link rendered image

### ISSUE THREAD

**Issue by leiwangouc** [grafana/grafana#24729]
Chinese letter not shown when shared by direct link rendered image. 
origin: 
![image](https://user-images.githubusercontent.com/19704741/82041386-a98f5000-96da-11ea-8309-db811f87944e.png)

shared through direct link rendered image:
![image](https://user-images.githubusercontent.com/19704741/82041345-967c8000-96da-11ea-95ac-8c3b19ad7447.png)

**Environment**:
- Grafana version:  6.6.2
- OS Grafana is installed on: CentOS 7
- User OS & Browser: chrome

**Comment by marefr** [comment]
You probably missing some font dependencies on your system.

**Comment by leiwangouc** [comment]
> You probably missing some font dependencies on your system.
I have checked  https://github.com/grafana/grafana/issues/3654#event-508409064  and https://github.com/grafana/grafana/issues/3373 and installed all the packages mentioned.

But still chinese letter not shown.

**Comment by marefr** [comment]
For the Grafana Image Renderer (which we suggest to use) Chinese characters was resolved by installing unifont dependency in alpine docker image: ref https://github.com/grafana/grafana-image-renderer/pull/75

**Comment by leiwangouc** [comment]
I am using CentOS.  Where can i find unifont package?

yum install No package unifont available

**Comment by marefr** [comment]
Search and you should find https://www.google.com/search?safe=off&rlz=1CDGOYI_enSE590SE590&hl=sv&sxsrf=ALeKk03Td4IanBk7b6rtSb0-FcAPOc87RA%3A1589829147394&ei=G97CXpbIF9KwrgSHzY3ABQ&q=centos+7+chinese+font&oq=centos+chinese+font&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAEYAjIGCCMQJxATMgYIABAHEB4yBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAgQHjIGCAAQCBAeOggIABAIEB4QEzoGCAAQDRAeOggIABAIEA0QHlCv4gFY7-YBYMz1AWgAcAB4AIABWogB6wGSAQEzmAEAoAEB&sclient=mobile-gws-wiz-serp

**Comment by leiwangouc** [comment]
Thanks.

yum groupinstall "fonts"  solved my problem

**Comment by zhegexiaohuozi** [comment]
https://help.accusoft.com/PrizmDoc/v12.2/HTML/Installing_Asian_Fonts_on_Red_Hat_and_CentOS.html

# centos6
```
# yum groupinstall "Chinese Support"
# yum groupinstall "Japanese Support"
# yum groupinstall "Korean Support"
# yum groupinstall "Kannada Support"
# yum groupinstall "Hindi Support"
```

# centos7

```
# yum groupinstall Fonts
```
