### ISSUE TITLE
When switching org, redirect to http://localhost:3000/?orgid =, instead of http://myhostip: 3000/?orgid =, result page not found

### ISSUE THREAD

**Issue by summerJiee** [grafana/grafana#24720]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 5.3.4
- Data source type & version: sqlite
- OS Grafana is installed on: centos
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Please upgrade Grafana. You'tr using a really old vesion.
