### ISSUE TITLE
Undo doesn't work in explore with Prometheus

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#24730]
I accidentally typed the wrong thing, and ctrl-z (or cmd-z on a mac) didn't undo it.

Version Grafana v7.1.0-91219227pre (bd42407620)

**Comment by Mario-Hofstaetter** [comment]
Possible duplicate to #24137

**Comment by zoltanbedi** [comment]
Hi Tom, thanks for reporting, it is indeed a duplicate of #24137 as Mario said so I'm closing this now.
