### ISSUE TITLE
Bar Gauge PNG rendering issue

### ISSUE THREAD

**Issue by evbevz** [grafana/grafana#24738]
**What happened**:
Standalone PNG image rendering creates image with markup errors. Labels overleys the graph field.
![channels-stats](https://user-images.githubusercontent.com/8384497/82059231-67601180-96ce-11ea-88e1-23b86cd86aaa.png)

**What you expected to happen**:
PNG image have to be same as graph
![Screenshot 2020-05-15 at 17 02 59](https://user-images.githubusercontent.com/8384497/82059343-8f4f7500-96ce-11ea-9557-e3bc32246f78.png)

**How to reproduce it (as minimally and precisely as possible)**:
create any Bar Gauge graph with horisontal orientation and try to share as Direct link rendered image

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.3 (a04ef6cefc)
- Data source type & version: Prometheus 2.18.1 (ecee9c8abfd118f139014cb1b174b08db3f342cf)
- OS Grafana is installed on: docker on MacOS
- User OS & Browser: MacOS 10.14.4
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Try using 7.0 and the new image rendering plugin  https://grafana.com/grafana/plugins/grafana-image-renderer

**Comment by torkelo** [comment]
or you can use https://grafana.com/grafana/plugins/grafana-image-renderer with 6.7

**Comment by evbevz** [comment]
It works!
