### ISSUE TITLE
Error: null is not an object (evaluating 'window.localStorage[a]')

### ISSUE THREAD

**Issue by michaelgibson** [grafana/grafana#2473]
I'm using a custom browser I built using PyQt4.QtWebKit

I'm not entirely sure of the root cause but the page refuses to load after breaking on a null object.
app/app.3c38f44f.js:11): Error: null is not an object (evaluating 'window.localStorage[a]')

which is coming from here
public/app/components/store.js

I created a quick workaround for my purposes by putting in a try/catch around getBool:
        getBool:function(a,b){
            try {
                return void 0===b||this.exists(a)?"true"===window.localStorage[a]?!0:!1:b
            }
            catch(e) {
                return e;
            }
        },

Seems to resolve my issue but I'm sure it's not the ideal solution.
Not even sure if it's a problem with the code or my browser but thought I would bring it up.

**Comment by torkelo** [comment]
seems your custom browser does not support localStorage
