### ISSUE TITLE
BUG: added 'support' for browser detection generating false positives (of course)

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#24743]
I think you added recently browser detection? I think I saw some red box when trying to log in, and I could not get past the login screen. (nothing in logs also)

You should not be concerning yourself with browser compatibility, because you do not know what someone is going to do on the grafana web interface with this browser. It is comon mistake developers make, start messing up in areas outside of their knowledge.

In my case I have been using this browser a lot and dashboards were fine. I have no doubt it would do, what I wanted it do. So remove your browser detection or change it so it just displays a message. Or hire someone that knows everything from all browers in the world.

grafana-6.7.3-1.x86_64
seamonkey-2.49.5-2.el6.x86_64

**Comment by marefr** [comment]
Very hard to investigate with this little details "think I saw some red box" and we haven't received any other similar reports. Don't think we've added any browser detection mechanism. Please add more details and we'll consider reopen the issue.

- Browser and version?
- What version did you upgrade from?
- Include screenshots, if possible
- Check console/network tab using for example Chrome Developer tools for any errors.
- Make sure you have read and understand the following https://grafana.com/docs/grafana/latest/installation/upgrading/#important-changes-regarding-samesite-cookie-attribute

**Comment by f1-outsourcing** [comment]
- version of the browser is already in the issue, below grafana version
- don't know, but I think it is already at least in the last two versions.
- not possible, is a remote display.
- what error message should this generate? I assume the guys from RedHat know what they are backporting into their packages, and follow standards.

I am getting green box 'Logged in', then red box 'Your browser is not fully supported. A newer browser version is recommended'. And stay on the login page.

I have nothing in the grafana.log maybe there should be a separate issue for this?

**Comment by ikkemaniac** [comment]
@marefr, started getting these too

> Very hard to investigate with this little details "think I saw some red box" and we haven't received any other similar reports. Don't think we've added any browser detection mechanism. Please add more details and we'll consider reopen the issue.
> 
>     * Browser and version?

FF 65.0.1, ofc i do have a variety of plugins running but all are disabled on this site
> 
>     * What version did you upgrade from?

can't remember... upgraded about 21days ago (according to [my commits)](https://github.com/ikkemaniac/grafana/commits/alert-add-switches)

Grafana version: v7.1.0-pre (5b5275b437) this is my personal branch [ikkemaniac:alert-add-switches](https://github.com/ikkemaniac/grafana/commits/alert-add-switches) with minor changes on top of a5deabbe530d55be93e6610a65ebb02252787ede (master)

 
>     * Include screenshots, if possible
![sshot](https://user-images.githubusercontent.com/845292/84548303-d3955b80-acf4-11ea-82f5-86fd9f4fa94b.jpg)

>     * Check console/network tab using for example Chrome Developer tools for any errors.
DOM Console:
```
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:27773
React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work. react-hot-loader.development.js:2432
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: UserProvider react-dom.development.js:12357
PerformanceBackend flushing: 
Object { metrics: (2) […] }
PerformanceBackend.ts:39
``` 

>     * Make sure you have read and understand the following https://grafana.com/docs/grafana/latest/installation/upgrading/#important-changes-regarding-samesite-cookie-attribute

?

**Comment by f1-outsourcing** [comment]
I have now every morning a crashed firefox, because I cannot use seamonkey anymore. Is the idea of a graphing solution, that you can see the charts?

**Comment by ikkemaniac** [comment]
I noticed a huge performance impact going from a shippped deb to my own compiled master. Anytime i hit grafana after a 'while' it takes a considered amount of time to present the dashboard, data retrieval itself is still similar. Once loaded I would say performance is the same as before. So, yes i see graphs but it's a pita every morning. I'm considering reverting to the older versions.
