### ISSUE TITLE
Bug: Graphite parser with asPercent and nested function sumSeries

### ISSUE THREAD

**Issue by tgr** [grafana/grafana#2474]
Steps to reproduce:
1. create metrics `A` and `B`
2. create a metric with `alias(asPercent(#B, sumSeries(#A, #B)), 'foo')`
3. edit the alias name to `bar`

Expected result: `alias(asPercent(#B, sumSeries(#A, #B)), 'bar')`
Actual result: `alias(asPercent(sumSeries(#A, #B), #B), 'bar')`

(Alias is irrelevant, any editing of a metric with `asPercent(#B, sumSeries(#A, #B))` will have the same effect.)

Here is a dashboard exported from play.grafana.org for easy testing: http://pastebin.com/3Xpv4zCP

**Comment by torkelo** [comment]
For a temp work around try to build the query something like this:
![image](https://cloud.githubusercontent.com/assets/10999/9149595/a51c7c00-3db1-11e5-88cc-9088329fe188.png)

**Comment by tgr** [comment]
That works well, thanks @torkelo !

**Comment by tgr** [comment]
Unfortunately the workaround seems to trigger a different bug: #2484

**Comment by daniellee** [comment]
This seems to be fixed. Closing the issue.
