### ISSUE TITLE
Dashboard Edit possible in Kiosk Mode

### ISSUE THREAD

**Issue by cbartetzko** [grafana/grafana#24742]
I've created a Grafana dashboard for my Solar Inverter and would like to show it in a sort of Read-Only-Mode on an Android Wall Tablet. When choosing the Kiosk mode I expected such behaviour. However in this mode it is still possible to (accidently) move panels by drag and drop and even to edit/delete panels on the dashboard. Is there a possibility to get a "real" kiosk (read-Only) mode running ?

**Comment by torkelo** [comment]
you will have to use a user with viewer role
