### ISSUE TITLE
Dashboard Links by tags not working in 7.0

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#24749]
Reported as part of https://github.com/grafana/grafana/issues/24523#issuecomment-629422403

When adding link to dashboards by tag:
![image](https://user-images.githubusercontent.com/705951/82088586-e8a3ae00-96a6-11ea-9eb8-c365485d8e9c.png)

The result shows a link that does not go anywhere:
![image](https://user-images.githubusercontent.com/705951/82088685-0ec94e00-96a7-11ea-8b18-94bb60b2d045.png)

Expected behavior (as seen in 6x) is to have a link in the upper right with the name of the dashobard:
![image](https://user-images.githubusercontent.com/705951/82223838-0dcb3300-98d8-11ea-9437-5d85baed39f3.png)

**Comment by meob** [comment]
As a partial workaround I selected "As dropdown"... but without it doesn't work
