### ISSUE TITLE
Table Panel: Auto width not works on small width

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24759]
**What happened**:
Auto width not works on small width
third column is not visible

![image](https://user-images.githubusercontent.com/2898361/82039209-75aa2f80-96c6-11ea-9b26-dcd7fc50b59b.png)

**What you expected to happen**:

In old version works fine

![image](https://user-images.githubusercontent.com/2898361/82039315-a5593780-96c6-11ea-9e79-1c5281281b41.png)

**How to reproduce it (as minimally and precisely as possible)**:
small width of table panel 

**Anything else we need to know?**:
related issue #24719

**Environment**:
- Grafana version: v7 beta-3
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Currently, this relates to default min column width 150px, maybe this can be more dynamic basic on the width of the panel 

https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/Table.tsx#L23

**Comment by oshamin** [comment]
@torkelo yes, making the column width depended from the width of the whole table will be a good starting point!
As the column right now wastes useful space.
