### ISSUE TITLE
Clicking on the dashboard in the dashboard list does not open the dashboard unless clicked on the name or in the middle of the row

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#24766]
**What happened**:
Searched for the dashboard. Unless I click in the middle of the row, it does not open the dashboard. 
![image](https://user-images.githubusercontent.com/14235758/82132198-d1e28180-97a2-11ea-9745-68892057cab8.png)

**What you expected to happen**:
It is such an annoying experience to keep clicking multiple times to open a dashboard. In v6.7, I do not need to focus hard to open the dashboard. The dashboard selection should happen by clicking anywhere on the dashboard row.

**How to reproduce it (as minimally and precisely as possible)**:
1) Search for any dashboard
2) In the search result, click on the dashboard row. (Do not click on the name of the dashboard, instead try clicking on the upper / lower part of the row anywhere)
3) You have clicked at the right place, dashboard will open in one click.

**Anything else we need to know?**:
v6.7 works fine

**Environment**:
- Grafana version:
![image](https://user-images.githubusercontent.com/14235758/82132263-841a4900-97a3-11ea-9866-5e54f131f1a9.png)
- Data source type & version:
Does not matter
- OS Grafana is installed on:
Docker
- User OS & Browser:
![image](https://user-images.githubusercontent.com/14235758/82132270-985e4600-97a3-11ea-9147-95c3f4b26151.png)

**Comment by torkelo** [comment]
@Clarity-89 Can you take a look at this? I think just adding height: 100% to the anchor seems to solve it for me.
