### ISSUE TITLE
Allow using default datasource in dashboard templating variable

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#24765]
**What would you like to be added**:
Allow using the `default` datasource in dashboard variables of type `Query`.
![grafik](https://user-images.githubusercontent.com/33002073/82131079-c5c1e880-97d1-11ea-8a04-cb74909b4c97.png)

Does already work using a hacky workaround (see below), so it is only missing in the UI.

**Why is this needed**:

If a **datasouce is renamed**, or inconsistent between grafana installations, dashboard variables of type query using this datasource 
**will stop functioning**:

![grafik](https://user-images.githubusercontent.com/33002073/82131016-eb022700-97d0-11ea-97a4-c93a2f625add.png)
![grafik](https://user-images.githubusercontent.com/33002073/82131033-30beef80-97d1-11ea-80de-9bd98237398e.png)

This can be a pain when exporting/importing/provisioning dashboards.

Panel queries do not suffer this fate:

![grafik](https://user-images.githubusercontent.com/33002073/82131049-77144e80-97d1-11ea-9974-c119e9449646.png)

It actually DOES seem to work if one edits the raw `JSON Model` of the dashboard and sets 
```
        "datasource": "default",
```
afterwards it will look like this, but is working fine:
![grafik](https://user-images.githubusercontent.com/33002073/82131131-4b459880-97d2-11ea-9fa5-844576c10b27.png)

Changing the query does get the correct new values. It only complains when hitting `Update` but that button is not strictly necessary:
![grafik](https://user-images.githubusercontent.com/33002073/82131155-83e57200-97d2-11ea-9719-2b5673de357a.png)

The dashboard can be saved an the variable is working.

Tested running `Grafana v7.0.0-beta3 (2169fc1a3f)` on `Windows 10 1909`

Maybe I am missing a reason why this is available in UI.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
