### ISSUE TITLE
Grafana 7 Massively slowdown analytics.js

### ISSUE THREAD

**Issue by MediaMaquina** [grafana/grafana#24768]
**What happened**:
I had grafana  v6.7.3 installed and everything was blazing fast, installed latest 7 and even the login page is extremely slow to load, and doesn't even load with ublock origin addon on chrome (blank page).
**What you expected to happen**:
It should be fast like before.
**How to reproduce it (as minimally and precisely as possible)**:
Install grafana 7
Install ublock origin. 
Try to load login page, it is blank.
Disable ublock origin, the page load but it's very slow compared to older versions.
**Anything else we need to know?**:
I think the cause is analytics.js file, why is this needed? How to remove it ?
![blcoked](https://user-images.githubusercontent.com/8179611/82132776-b186e700-97e3-11ea-945a-fcf34c3a60e5.png)

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: none
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 7 x64
- Grafana plugins: none
- Others: none

**Comment by torkelo** [comment]
How did you install Grafana? Any proxy in between? Looks like something is wrong with your install. 

No other reports like this so very strange. Do you get same behavior in incognito mode?

**Comment by MediaMaquina** [comment]
Hey this is how i install it:

```
sudo wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
sudo apt-get update
sudo apt-get install grafana
sudo systemctl start grafana-server
```

I have already downgraded. I will rent a new vps and try again later on so you can see live.

**Comment by jdblack** [comment]
@MediaMaquina  can you expand on how you fixed this issue? Did you remove  analytics.js from the filesystem?

**Comment by MediaMaquina** [comment]
Did this really happened to you too?
I removed everything and installed grafana 7.
