### ISSUE TITLE
Failed includes for plugins result in cryptic error message.

### ISSUE THREAD

**Issue by acedrew** [grafana/grafana#24764]
**What happened**: 
I included the wrong path for a library in my plugin, the server responded with a 404, but the error message logged to the console just said "Failed to load plugin xxxx unexpected '<'".
**What you expected to happen**:
Provide a failure message that was explicit about the error that had occurred, specifically it should have provided the 404 return code vs only the first character of the response (which was the grafana default 404 page).

**How to reproduce it (as minimally and precisely as possible)**:
Mangle one of the include paths in a plugin and reload a dashboard containing that plugin panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows/Chrome
- Grafana plugins:
- Others:

**Comment by tolzhabayev** [comment]
Closing this issue as stale. We have an Issue to update SystemJS as this is related to it and will revisit if the behaviour is different after the update.
