### ISSUE TITLE
Transform Binary Operation doesnt work in 7.0.0 Beta 3 

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#24775]
I have one query returning TOTAL traffic
I have another query returning ERROR Count

![image](https://user-images.githubusercontent.com/7537289/82157644-6357ff00-9848-11ea-92f6-76c3c023e7ba.png)

Trying to get ERROR % -- not showing %

![image](https://user-images.githubusercontent.com/7537289/82157619-2c81e900-9848-11ea-85a2-d961e4770cfd.png)

Tried even replace all fields - doesnt work with binary - works with the reducer

![image](https://user-images.githubusercontent.com/7537289/82158927-8b4b6080-9850-11ea-8fed-8c8f6a84e821.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by softwareklinic** [comment]
Am i misunderstanding how this works or is there a genuine issue?

**Comment by torkelo** [comment]
This is already fixed in master & coming stable

**Comment by softwareklinic** [comment]
Great - thank you...

**Comment by softwareklinic** [comment]
Is the fix available for download yet --- or would i have to get and build myself?
