### ISSUE TITLE
Unable to use reducer / calculation -- for mixed types of values in query - grafana 7.0 beta 3

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#24777]
It is using the TOTAL for all 3 fields and then im unable to override the AVG RTT to use AVG / MEAN instead of TOTAL 

![image](https://user-images.githubusercontent.com/7537289/82159507-298cf580-9854-11ea-8631-306f5744a358.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The stat panel does not support custom reducers per series. Will have to split it into separate PRs
