### ISSUE TITLE
Repeated requests from panels displaying same metric

### ISSUE THREAD

**Issue by juangburgos** [grafana/grafana#24774]
**What happened**:

I get repeated requests on a dashboard that has a panel displaying one metric in a graph panel (historic), and then displaying the same metric in a stats panel (latest value).

**What you expected to happen**:

I would expect that Grafana will issue one request for all panels that are configured with the same metric to avoid repeated queries on underlying database and unecessary netowrk roundtrips.

**How to reproduce it (as minimally and precisely as possible)**:

Just use the same metric on different panels:

![01](https://user-images.githubusercontent.com/4707341/82142138-7d8ae080-983a-11ea-9df1-0ddd6d3f47f3.PNG)

Then you get multiple same requests:

![02](https://user-images.githubusercontent.com/4707341/82142160-af9c4280-983a-11ea-8430-772b7704f5dd.PNG)

I get the **same request, 3 times**, the only thing that changes is the `requestId` and `panelId`. Everything remains pretty much the same.

**Anything else we need to know?**:

I am using the [grafana-json-datasource](https://github.com/simPod/grafana-json-datasource/issues/87) datasource and implementing my own backend.

I have [reported it](https://github.com/simPod/grafana-json-datasource/issues/87) to the backend developer but it has been claimed the issue is in Grafana.

**Environment**:
- Grafana version: Grafana v6.7.3 (a04ef6cefc)
- Data source type & version: simpod-json-datasource 0.1.7
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: simpod-json-datasource
- Others: Custom HTTP backend

**Comment by torkelo** [comment]
That is not how Grafana works. Every panel has its own queries.

If you select the — Dashboard — , data source you can select to reuse data from another panel.

**Comment by juangburgos** [comment]
Thanks for the answer. I guess one should really be careful when configuring panels, because one can easily DDOS one's own backend. That is not very clear for beginners.
