### ISSUE TITLE
Validation error for the alerts defined for multiple prometheus datasources

### ISSUE THREAD

**Issue by gowrisankar22** [grafana/grafana#24778]
Hi, 
I am getting validation error for the alerts defined for multiple prometheus data sources

```
Alert validation error: Data source used by alert rule not found, alertName=SLI ($period) alert, datasource=$datasource
```
version: 6.5.2

Brs, Gowrisankar

**Comment by marefr** [comment]
Duplicate of #6557

**Comment by ykfq** [comment]
Still not support multple datasource in version of v7.3.6:
![image](https://user-images.githubusercontent.com/20741596/103088768-d5869280-4626-11eb-8c14-d57e72cd04ed.png)

**Comment by cobr123** [comment]
Still not support variable in datasource. Grafana v7.4.1

**Comment by ptolemybarnes1649** [comment]
Seeing this issue on Grafana v8.0.6 too
