### ISSUE TITLE
Docs feedback: /tutorials/stack_guide_graphite.md

### ISSUE THREAD

**Issue by akingscote** [grafana/grafana#24781]
Documentation missing - https://grafana.com/docs/grafana/latest/tutorials/stack_guide_graphite/#sending-metrics-to-statsd

The `sending-metrics-to-statsd` section is missing from this page. Frustratingly its the only piece i need.

**Comment by torkelo** [comment]
This article was never complete & published in full (not linked to anywhere)

**Comment by akingscote** [comment]
@torkelo 
Im confused, if it wasnt published I wouldnt have found and accessed the page.

Its clearly on the public internet and is indexed on search engines.

**Comment by torkelo** [comment]
Yea, must have been published by mistake. Sorry about that. Will fix
