### ISSUE TITLE
/api/ methods should return HTTP code 405 on PUT, not 404

### ISSUE THREAD

**Issue by feliksik** [grafana/grafana#2478]
It seems that the /api/datasources supported PUT in grafana 2.0 but returns HTTP 404 in grafana 2.1. 

I suggest return 405 instead (Method not Allowed), as POST works fine. So a 404 is inappropriate.

**Comment by torkelo** [comment]
Yes,   there was a breaking api change in 2.1 to correct POST and PUT method (they were reversed, and incorrectly used) .

**Comment by feliksik** [comment]
I noticed things broke. This is fine.

What I am suggesting to stay backwards incompatible, but return an appropriate error code: 405 instead of 404. 

Feel free to reject it on whatever grounds you see fit, but please let me know if you understand the suggestion.
