### ISSUE TITLE
Comma Separator in INR format for large numbers. 

### ISSUE THREAD

**Issue by ameysd19** [grafana/grafana#24782]
Hello all,

I have started working Grafana for the last couple of weeks. 
I have noticed that to add comma separator for large numbers we can use "locale format".
But the format gives me the number in millions (E.g 1,123,456.00). Whereas I wanted the number in INR format (Crores)(E.g 11,23,456.00) 

Please can you tell me if there is already any solution available to solve this issue? If not how can it be done?
Ps -  I am not a developer. I can not code as you guys do.

Thank you.

**Comment by daniellee** [comment]
Crores: https://en.wikipedia.org/wiki/Crore (sorry, didn't know about this number system before).

So I'm not sure if the Crores format works with the `locale format` unit but which locale/language is your browser using?

**Comment by ameysd19** [comment]
My browser is using English (India) locale/language.

**Comment by torkelo** [comment]
sounds like a browser locale issue, not a Grafana issue (We use the native browser function)
