### ISSUE TITLE
Transforms: Binary Operation, Drop down doesn't allow Numbers

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#24788]
**What happened**:
Transform :: Binary Operation will not let me enter numbers in the dropdown fields adjacent to the operator drop down field, only series. If I use inspector to set the field value, it does work - so seems just to be a UI form issue:

https://www.youtube.com/watch?v=4LF6Evtyzmk&feature=youtu.be

**What you expected to happen**:
To be able to enter a number, since the hint says "Field or Number"

**Environment**:
- Grafana version: 7.0
- Data source type & version:
- OS Grafana is installed on: Ubuntu Mint 19.3
- User OS & Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/24752
