### ISSUE TITLE
Regarding rate functions

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [grafana/grafana#24790]
When I apply rate function, the panel shows as no data.
When rate function is not applied, I'm getting data
![image](https://user-images.githubusercontent.com/63767821/82220515-5e747780-993c-11ea-89c8-738bc5d29e2a.png)
But when rate function is applied, it shows no data
![image](https://user-images.githubusercontent.com/63767821/82220658-8bc12580-993c-11ea-968e-6a90181becab.png)

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Prometheus 2.14.0
- OS Grafana is installed on: Ubuntu

**Comment by dswarbrick** [comment]
It's quite likely that your scrape interval is 1m, so you will need to make your rate function range duration at least 2x that. Try replacing the `[1m]` with `[2m]`.

**Comment by SpoortiPalakshaiah** [comment]
![image](https://user-images.githubusercontent.com/63767821/82281721-a8e30c00-99af-11ea-8a56-27fd4012c49b.png)
Same issue @dswarbrick
