### ISSUE TITLE
Using derivative, series shows up as double

### ISSUE THREAD

**Issue by linuxbutler** [grafana/grafana#2479]
Hello

I am graphing values, where the metric is always increasing (eg, packets sent through nic). For this, I have to use the derivative function to display the graph correctly. The problem is, when I use derivative, each metric is shown twice: 

![image](https://cloud.githubusercontent.com/assets/8770033/9151844/4cea03d8-3e13-11e5-90ba-f05fccd3ae4f.png)

Also strangely, the last hour of data is generated in a different color.

But, when using say "mean" (which I know is not correct, but just to illustrate the point), suddenly each metric is only shown once on the graph. 

I can replicate the issue with any series that holds ever-increasing types of values. 

Thank you!

**Comment by torkelo** [comment]
This is a bug in InfluxDB,  it's returning duplicate series in some cases. been reported before here on grafana project and I think there is a. Open issue in influxdb for it. On mobile now so do have the link to the influxdb issue.
