### ISSUE TITLE
7.0.0: ARMv7 Ubuntu Docker running 4 months old pre-release Ubuntu base 

### ISSUE THREAD

**Issue by frenck** [grafana/grafana#24806]
**What happened**:

v7.0.0 got released, which upgraded to Ubuntu 20.04. As for ARMv7, the Docker images for Ubuntu 20.04 are broken for about 4 months now, the major Grafana v7.0.0 stable release for ARMv7 is built on that.

Thus, Grafana v7.0.0 is shipped on a testing/alpha/beta version of Ubuntu for this platform.

Latest stable version according to Ubuntu: focal-20200423
Used by Grafana: focal-20200115

This predates the official release of 20.04 with about 3 months.

Reference:

<https://hub.docker.com/r/arm32v7/ubuntu/>

Failing Multiarch CI, Ubuntu 20.04 ARMv7:

<https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/ubuntu/>

**What you expected to happen**:

Grafana to ship stable, tagging explicit Docker versions or SHAs as a best Docker practice, would have prevented this.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.0
- Data source type & version:
- OS Grafana is installed on: Docker, Ubuntu ARMv7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
What is your proposed solution exactly? I can't really tell from the issue description, sorry.

**Comment by frenck** [comment]
As there is no stable release for Ubuntu 20.04 on Docker for ARMv7, the proposed solution is not to use it, until there is.

Furthermore, you guys are using `FROM ubuntu:20.04` however, that does not control the specific version, as now got bitten by, as that tag contains a pre-release for the ARMv7 platform.

In general practice, one should use an SHA tag or a specific tag.

In this case, if `FROM ubuntu:focal-20200423` was used to pin a specific stable version, you builds would have been failing and you guys would have known something is wrong.

Instead, you've now ended up shipping a non-stable Ubuntu version as a base for v7.0.0.

**Comment by aknuds1** [comment]
Thanks, we weren't aware 20.04 had such bad support for ARMv7. We are thinking of ways to solve this in the meantime.

**Comment by OttoWinter** [comment]
@aknuds1 FYI, arm32v7 focal builds are working again as of `focal-20200720`

https://hub.docker.com/r/arm32v7/ubuntu/tags?page=1&name=focal

**Comment by aknuds1** [comment]
Thanks for the update @OttoWinter.

**Comment by malcolmholmes** [comment]
I think we can safely close this issue. Please let us know if any issues remain.
