### ISSUE TITLE
grafana-enterprise 7 rpm obsoletes grafana

### ISSUE THREAD

**Issue by pharaujo** [grafana/grafana#24801]
**What happened**:
grafana-enterprise-7.0.0 was installed when trying to install and earlier version of grafana

**What you expected to happen**:
that the requested version was installed

**How to reproduce it (as minimally and precisely as possible)**:
On centos 7:
```
# yum install grafana-6.6.2
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
Package grafana is obsoleted by grafana-enterprise, trying to install grafana-enterprise-7.0.0-1.x86_64 instead
Resolving Dependencies
--> Running transaction check
---> Package grafana-enterprise.x86_64 0:7.0.0-1 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
========================================================================================
 Package                 Arch        Version       Repository                      Size
========================================================================================
Installing:
 grafana-enterprise      x86_64      7.0.0-1       grafana       47 M

```

**Comment by daniellee** [comment]
Investigating this now.

**Comment by torkelo** [comment]
this is so you can install enterprise over grafana. Think you can override this using  ` --nodeps to override the new obsoletes behavior`

**Comment by torkelo** [comment]
let me know if that works for your

**Comment by torkelo** [comment]
ah, sorry. I miss read the issue. Sounded like you had installed enterprise before

**Comment by RichiH** [comment]
Got external confirmation that this is happening (at least) for:

````
[grafanaofficial]
name=grafanaofficial
baseurl=https://packages.grafana.com/oss/rpm
enabled=1
protect=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
````

**Comment by bastischubert** [comment]
maybe also add a new release for the grafana rpm to superseed the grafana-enterprise rpm as well

**Comment by utopiabound** [comment]
The oss repo has several grafana-enteprise rpms in it that are causing problems.
(From https://packages.grafana.com/oss/rpm/repodata/883ee28dd303eaf098baac6aefc5c159d3decc1da46b3ba6e8c9a7f8625e846c-primary.xml.gz)
```
# grep location 883ee28dd303eaf098baac6aefc5c159d3decc1da46b3ba6e8c9a7f8625e846c-primary.xml
...
<location href="grafana-enterprise-5.4.3-1.x86_64.rpm"/>
<location href="grafana-enterprise-6.7.0-test.aarch64.rpm"/>
<location href="grafana-enterprise-6.7.0-test.armhfp.rpm"/>
<location href="grafana-enterprise-6.7.0-test.x86_64.rpm"/>
<location href="grafana-enterprise-7.0.0-1.aarch64.rpm"/>
<location href="grafana-enterprise-7.0.0-1.armhfp.rpm"/>
<location href="grafana-enterprise-7.0.0-1.x86_64.rpm"/>
<location href="grafana-enterprise-7.0.0-test.aarch64.rpm"/>
<location href="grafana-enterprise-7.0.0-test.armhfp.rpm"/>
<location href="grafana-enterprise-7.0.0-test.x86_64.rpm"/>
```

**Comment by kylebrandt** [comment]
> The oss repo has several grafana-enteprise rpms in it that are causing problems.

Saw this:

```
curl 'https://packages.grafana.com/oss/rpm/repodata/883ee28dd303eaf098baac6aefc5c159d3decc1da46b3ba6e8c9a7f8625e846c-primary.xml.gz' | gunzip | grep obsol  -B30
```

Not sure if happened recently and somehow change the metadata for old packages, or has been around since ~Jan 14th (oldest date I see in the xml file) with the obsolete item in the xml. I think the problem might be older.

**Comment by pharaujo** [comment]
We've been using this repo for a couple of years now, and today was the first time we encountered this issue. Seems a lot of coincidence it matched the grafana 7.0.0 release.

**Comment by torkelo** [comment]
It is fixed now but you will have to run "sudo yum clear all" to clear the local packages cache

**Comment by pharaujo** [comment]
Looks fixed from my end as well. Thanks for the quick response!

**Comment by Zayan1221** [comment]
Hello,
yum install grafana-7.0.3-1.x86_64.rpm
Loaded plugins: fastestmirror
Examining grafana-7.0.3-1.x86_64.rpm: grafana-7.0.3-1.x86_64
Cannot install package grafana-7.0.3-1.x86_64. It is obsoleted by installed package grafana-enterprise-7.0.2-1.x86_64
Error: Nothing to do

**Comment by aknuds1** [comment]
@Zayan1221 thanks, I made an issue to investigate: #25340.
