### ISSUE TITLE
Add search in the variable dropdown

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#24800]
**What would you like to be added**:

Add search in the variable dropdown. 

**Why is this needed**:

When there are a lot entries in the variable dropdown, it is hard to find the entry. Search would be more suitable than manually scroll through a long list variables.

**Comment by torkelo** [comment]
you can search a variable dropdown
![Screenshot from 2020-05-19 09-50-05](https://user-images.githubusercontent.com/10999/82300077-a33cf480-99b6-11ea-97b7-c7b9e3b6452b.png)

**Comment by fredwangwang** [comment]
Ohhh, thanks @torkelo!
