### ISSUE TITLE
Grafana 7 Beta doesnt read plugins folder?

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#24808]
**What happened**:

I tried to install the image renderer plugin under the /grafana/plugins folder but dont see the plugin and any new data source in the 7.0 UI

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by daniellee** [comment]
If it is installed you should see it in the plugins list: http://localhost:3000/plugins/grafana-image-renderer/ (replace localhost:3000 with your Grafana instance url).

If the install worked then it should be in the plugins folder. How did you try to install it? Any errors?

**Comment by softwareklinic** [comment]
./grafana-cli plugins install grafana-image-renderer
installing grafana-image-renderer @ 2.0.0
from: https://grafana.com/api/plugins/grafana-image-renderer/versions/2.0.0/download
into: /usr/local/var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully 

Restart grafana after installing plugins . <service grafana-server restart>

And after installation was complete and restarted grafana-server

Im running 7.0 on localhost

![image](https://user-images.githubusercontent.com/7537289/82246569-8c40c880-990a-11ea-9ae2-f8c04a3de982.png)


![image](https://user-images.githubusercontent.com/7537289/82246576-9236a980-990a-11ea-87aa-5b31f0a80a7c.png)

**Comment by daniellee** [comment]
Can you check that you are using the default plugins path by looking at the settings: http://localhost:3000/admin/settings

Also, any errors in your Grafana server log. Did it fail to load the plugin for some reason?

**Comment by softwareklinic** [comment]
We can close this - figured it out - ty for the pointer

It was pointing to data/plugins and not plugins -- so modified defaults.ini to point to correct folder.
