### ISSUE TITLE
Flux (InfluxDB) Beta plugin can't be uninstalled or configured

### ISSUE THREAD

**Issue by AndyGlaister** [grafana/grafana#24816]
**What happened**:
I added the Flux (InfluxDB) Beta plugin to my account, but now can't open it to see the configuration and can't delete it as the UI says "Plugin not found, no plugin with that ID can be found". From here: https://andy14.grafana.net/datasources

When I try and uninstall / reinstall or even install an old version of the plugin from the configuration site, this also fails: https://grafana.com/orgs/andy14/instances/117757

**What you expected to happen**:
I expect the InFluxDb plugin configuration to match the current InFluxDB configuration requirements, none of the plugins I tried would talk to my AWS cloud instance of InFluxDB, it's quite frustrating. It looks as if your site and InFlux is evolving rapidly, but your are not staying in sync.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Just trying to create a new cloud hosted, free version of InFluxDB and link it to Grafana,

**Comment by daniellee** [comment]
@AndyGlaister which version of Grafana (are you on 6.7.3 or did you get 7.0.0 - you can see it in the footer on most pages) and which version of the Flux plugin did you install?

I tested with Grafana 7.0.0 and version 7.0.0 of the plugin and seems to work for me.

**Comment by daniellee** [comment]
Checked with the api and you are on 6.7.3 (I don't have access to your instance without your permission but I can see some meta data). I can upgrade you to 7.0.0 if that's ok?

**Comment by AndyGlaister** [comment]
Please upgrade me, thanks

**Comment by daniellee** [comment]
@AndyGlaister you have already been upgraded it seems. We roll it out automatically but you were still on 6.7.3 when you opened the issue. If you install a plugin then it gets upgraded immediately.

Does it work now?

**Comment by torkelo** [comment]
Closing this as this is now part of core Influx data source
