### ISSUE TITLE
flag provided but not defined with reset-admin-password

### ISSUE THREAD

**Issue by caleb15** [grafana/grafana#24818]
**What happened**:

`grafana-cli admin reset-admin-password --config "/etc/configuration/" mynewpassword` executed in `/usr/share/grafana` directory resulted in:

```
Incorrect Usage: flag provided but not defined: -config

NAME:
   Grafana CLI admin reset-admin-password - reset-admin-password <new password>

USAGE:
   Grafana CLI admin reset-admin-password [command options] [arguments...]

OPTIONS:
   --help, -h  show help (default: false)
   
Error: ✗ flag provided but not defined: -config

```

**What you expected to happen**:
The command to work. It's exactly the same as what is in the documentation:
https://grafana.com/docs/grafana/latest/administration/cli/#override-config-file

**How to reproduce it (as minimally and precisely as possible)**:
Run command above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 18
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Workaround:**
`grafana-cli --config "/etc/grafana/grafana.ini" admin reset-admin-password mynewpassword`

**Comment by caleb15** [comment]
This might just be a documentation bug

**Comment by zoltanbedi** [comment]
Hi @caleb15,
This looks like a typo in our docs. Would you mind creating a pr with a fix?

**Comment by kvz** [comment]
Found the same issue with setting --homedir as instructed on this page https://grafana.com/docs/grafana/latest/administration/cli/#reset-admin-password. When moving the flag up front it worked.

**Comment by sajjadbaeidi** [comment]
This worked for me, just need to use arguments right after grafana-cli:

**Comment by QGB** [comment]
```
C:\QGB\v2ray-windows-64-v5.0.6>v2ray.exe -c config.json run
flag provided but not defined: -c
Usage of v2ray.exe:

C:\QGB\v2ray-windows-64-v5.0.6>v2ray.exe --config config.json run
flag provided but not defined: -config
Usage of v2ray.exe:

``
