### ISSUE TITLE
Prometheus Alerts do not show proper description

### ISSUE THREAD

**Issue by ganeshdudwadkar** [grafana/grafana#24814]
**Steps to reproduce**:
1. In Grafana, go to Settings -> Annotations -> New
2. Configure name and Data Source as Prometheus
3. Enter Search Expression -> ALERTS{alertname="InstancesDown"} 
4. Text : {{ .Annotations.description }}

**Actual Result**:
In graph, the annotation text is shown as ".Annotations.description" instead of actual description. 

**Expected Result**
It should pull the custom annotation description which was set as part of the alert e.g.

> Instaces A, B and C are down

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Prometheus
- User OS & Browser: Mac and Chrome
- Others:

**Comment by marefr** [comment]
The `ALERTS` metric per default only has alertname, alertstate and job labels. 

> 4. Text : {{ .Annotations.description }}

You should just input the name of the label you have, for example alertstate.
