### ISSUE TITLE
Exporting Dashboards as PDF and EMAIL

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#24812]
**What would you like to be added**:

Just like we are able to send ALERTS to EMAIL - can we also add feature where we can actually periodically export DASHBOARDS as PDF and EMAIL -- this is one of the most required feature across the organization.

Currently we are using puppeteer but it works with some dashboards and doesnt work with others etc...

**Why is this needed**:

**Comment by eamonryan** [comment]
Hi @softwareklinic 

This feature actually already exists and is called "Reporting". However, it is a feature of the Enterprise version of Grafana only.

You can read about its capabilities and requirements here https://grafana.com/docs/grafana/latest/enterprise/reporting/

You can also read about Grafana Enterprise in general here: https://grafana.com/products/enterprise/

Thanks!
Éamon
Solutions Engineer
Grafana Labs

**Comment by dswarbrick** [comment]
Check out https://github.com/IzakMarais/reporter

**Comment by softwareklinic** [comment]
Thank you - also checking out this utility

Puppeteer works for most of our needs -- but for some of the data sources
its not able to interact...

<http://www.verizon.com>

Keyur Shah

Associate Fellow - Enterprise Architecture
2147845203

"Defects & waste slow down the progress" - Identify, measure and eliminate.
