### ISSUE TITLE
Stat value much smaller than Singlestat

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#24815]
**What happened**:
When the panel is 2 units high, the value in new Stat panel is much smaller than in old Singlestat panel.

![image](https://user-images.githubusercontent.com/19311511/82249567-4a377700-994a-11ea-9bb4-6c515ff68e3d.png)

**What you expected to happen**:
It should have the same or very similar size.

**How to reproduce it (as minimally and precisely as possible)**:
Make a panel that is 2 units high (1 is the title and 1 is for value, so it is the minimal height you can set).

**Anything else we need to know?**:
It would be also nice to be able to set maximum and minimum font size, so if the panel is big, the text won't take all the available space.

![image](https://user-images.githubusercontent.com/19311511/82249968-f711f400-994a-11ea-83a3-2f0b99d4f5f7.png)
In this situation the text in Stat panel is too big for me.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Influxdb 1.7.9
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Opera Gx

**Comment by softwareklinic** [comment]
I like the fluidity of the new stats plugin

![image](https://user-images.githubusercontent.com/7537289/82251943-c2367a80-9913-11ea-9257-cd7065c279c8.png)

**Comment by torkelo** [comment]
It cannot be much bigger without going outside the panel border & padding 
![Screenshot from 2020-05-18 22-02-55](https://user-images.githubusercontent.com/10999/82254578-5e33a680-9953-11ea-8ec0-b7746e6f7a5a.png)

**Comment by szerwi** [comment]
@torkelo So maybe could you make "size step" smaller. Currently when I increase panel height by one step, the value gets much bigger. With smaller step it would be more customizable.
![image](https://user-images.githubusercontent.com/19311511/82256139-19f5d580-9956-11ea-9dac-5cbb2d1386bf.png)
