### ISSUE TITLE
Feature Request: Support Graphite fallbackSeries()

### ISSUE THREAD

**Issue by easterhanu** [grafana/grafana#2481]
Hi,

I'd like to have Graphite's fallbackSeries() function or equivalent functionality supported by Grafana. I.e. if the requested time series does not exist, fallback to using a secondary series (or constant) instead of giving an error message about the failed request. This would be especially useful with templated dashboards, when the same template mostly works, but there are some exceptions.

**Comment by torkelo** [comment]
when it is available in the latest stable release :)

**Comment by easterhanu** [comment]
Oh, now I feel silly. I was indeed testing this on a server running old Grafana 1.9.1, not the latest stable one AND running a version Graphite, which wouldn't have the fallbackSeries() function anyway (it's seems to be quite a recent addition, not in 0.9.13-pre1). D'oh!

In my defense, I tried googling, a grafana repo search in GitHub (sort of expected a match in gfunc.js),  and search at docs.grafana.org for "fallbackSeries" with null results before opening this, and incorrectly assumed the functionality wasn't supported. I guess you can just type in the function, but it's not in Grafana's menus?

Anyway, thanks for the quick "fix" and a great piece of software! ;)

**Comment by torkelo** [comment]
this was added in v5
