### ISSUE TITLE
v7.0.0 Error: Invalid interval string

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#24825]
**What happened**:
Receiving "An unexpected error happened" when loading some dashboards. Once the error has occurred all dashboards that were working now display to same message until a hard reload in he browser is done.

**How to reproduce it (as minimally and precisely as possible)**:
I think there is a variable in the dashboard which references a database which is no longer in use as I see the last request in the browser network window as:
/api/datasources/proxy/1/query?db=icinga2&q=SHOW%20TAG%20VALUES%20%20WITH%20KEY%20%3D%20%22service%22%20where%20hostname%20%3D~%20%2F%5E%24%2F&epoch=ms

We do not have any datasources called icinga2, but we used to have one long ago.

**Anything else we need to know?**:
Browser console Error: Invalid interval string, has to be either unit-less or end with one of the following units: "y, M, w, d, h, m, s, ms"
    at Object.describe_interval (kbn.ts:214)
    at Object.interval_to_ms (kbn.ts:229)
    at value (context_srv.ts:64)
    at Array.filter (<anonymous>)
    at e.value (TimeSrv.ts:82)
    at t.value (DashNavTimeControls.tsx:97)
    at Xa (react-dom.production.min.js:181)
    at Ya (react-dom.production.min.js:180)
    at Su (react-dom.production.min.js:261)
    at yc (react-dom.production.min.js:230)

Nothing useful logged into /var/log/grafana.log

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus, InfluxDB, ElasticSearch, MS SQL
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Win10/Chrome
- Grafana plugins: 
- Others:

**Comment by bhozar** [comment]
I downgraded Grafana and removed the unused variables from the dashboard. One was a time interval one. Upgraded again to 7.0.0 but same results.

The dashboard is mostly alert panels, with no variables within it at all.

**Comment by torkelo** [comment]
Can you include your dashboard json? Of the time interval variable?

**Comment by bhozar** [comment]
> Can you include your dashboard json? Of the time interval variable?

I've removed all variables in an attempt to fix it, but no luck. I have the JSON here: [Gist](https://gist.github.com/bhozar/2d23f3c4b5bd0af712f183f8a351a7af)

**Comment by hugohaggmark** [comment]
@bhozar if you remove the `Auto` entry in `refresh_intervals` does that solve it?
https://gist.github.com/bhozar/2d23f3c4b5bd0af712f183f8a351a7af#file-grafbrokendb-L12850

**Comment by hugohaggmark** [comment]
git bisect points to this commit 854085dbc6 but I don't fully grasp the change although it's a one liner :) Any thoughts @marefr @torkelo ?

**Comment by marefr** [comment]
You'll need to replace `"refresh": false,` with ` "refresh": "",`

**Comment by bhozar** [comment]
I changed it to: "refresh": "", by select a refresh interval, then setting it back to none on the main dashboard. Still broken.

Removed "Auto" from refresh_intervals. Now it works.

Thanks guys.

Is there any way to remove that from all dashboards? I have 130 dashboards and we aren't doing them as code yet, so could do with any easier way to fix them all.

**Comment by bhozar** [comment]
I've just gone through all of them manually and every other dashboard loads, so must have just been that one. Thanks for your assistance.

**Comment by hugohaggmark** [comment]
Glad I could help out @bhozar

**Comment by hugohaggmark** [comment]
Anything we should add to dashboard migrations or should we close this @torkelo ?

**Comment by torkelo** [comment]
think we can close this

**Comment by yvespp** [comment]
I have the same problem after upgrading to 7.0.0 with one Dashboard so far:
```
Error: Invalid interval string, has to be either unit-less or end with one of the following units: "y, M, w, d, h, m, s, ms"
```
Can I somehow edit the JSON via Grafana without downgrading it?

**Comment by yvespp** [comment]
Here the dashboard [gist](https://gist.github.com/yvespp/8944b26595bf1c88b5e512e9f60a89a6)

**Comment by yvespp** [comment]
I was able to fix it by getting the json from the browser, remove "off" and the updating it via api: https://grafana.com/docs/grafana/latest/http_api/dashboard/
