### ISSUE TITLE
Legend Decimal places doesn't work

### ISSUE THREAD

**Issue by kustodian** [grafana/grafana#24823]
**What happened**:
Setting the number of decimal places in the legend to a fixed number displays the values with a lot of decimal places.

**What you expected to happen**:
To display the number of decimal places that is set.

**How to reproduce it (as minimally and precisely as possible)**:
Have some values that don't have float values and set decimal places to something like 2.

**Anything else we need to know?**:
If I remove the number of decimal places and leave it to auto, it works very nice and displays only 2 decimal places.

**Environment**: 
- Grafana version: 7.0
- Data source type & version:
- OS Grafana is installed on: CentOS 7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by M0rdecay** [comment]
Same issue with my Grafana 7.0 after migration from 6.7.2:
![image](https://user-images.githubusercontent.com/50422107/82296605-1c8a1680-99ba-11ea-85a4-63a67641381e.png)

**Comment by torkelo** [comment]
It looks like it works, just that there is no re-render on blur , the decimals work if you refresh

**Comment by torkelo** [comment]
ah, no there is something wrong here with decimals override

**Comment by asm19** [comment]
Same problem here, after upgrade...
