### ISSUE TITLE
Stackdriver Tracing datasource 

### ISSUE THREAD

**Issue by inigohu** [grafana/grafana#24839]
**What would you like to be added**:

With the last Grafana version (v7.0.0), now is possible to visualize traces. At this time, only Jaeger and Zipkin datasources are supported. It would be great to add Stackdriver as Grafana Traces datasource also.

**Why is this needed**:

To centralize all observability dashboards in Grafana with metrics and traces (and logs https://github.com/grafana/grafana/issues/21370) using stackdriver as a backend.

**Comment by daniellee** [comment]
Hoping to do this later this year. Think that we will do Stackdriver Logs first though.

Ref: https://github.com/grafana/grafana/pull/23066
