### ISSUE TITLE
Unable to setup SMTP with Env variables 

### ISSUE THREAD

**Issue by Esteidinger** [grafana/grafana#24831]
here is my docker run: 

docker create \
    --name=grafana \
    -p 3000:3000 \
    -e PUID=1000 \
    -e PGID=1000 \
    -e GF_SMTP_ENABLED=true \
    -e GF_SMTP_HOST=smtp.sendgrid.net:25 \
    -e GF_SMTP_USER=apikey \
    -e GF_SMTP_PASSWORD=redacted_API_KEY \
    -v /media/docker/grafana:/var/lib/grafana \
    --restart unless-stopped \
    grafana/grafana

I get a slew of errors like this: 

t=2020-05-19T01:49:13+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SMTP_HOST=smtp.sendgrid.net:25",

And then sending does not work. Any advice?

**Comment by bergquist** [comment]
That's not an error log. That logline tells you that you successfully have overridden the setting with environment variables. Problerby something is that's not working with your configuration.
