### ISSUE TITLE
Grafana plugin update failed with x509: certificate issue

### ISSUE THREAD

**Issue by IzekChen** [grafana/grafana#24830]
**What happened**:

When I prompt the command: grafana-cli plugins update-all
It just shows "Failed to send requesterrorGet "https://grafana.com/api/plugins/repo": x509: certificate signed by unknown authorityError: ✗ Failed to send request: Get "https://grafana.com/api/plugins/repo": x509: certificate signed by unknown authority"

**What you expected to happen**:
update all plugin

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0-1
- Data source type & version:
- OS Grafana is installed on: Redhat7
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by bergquist** [comment]
Hi! 

This is probably due to a lack of certs on your host. 

https://www.sslshopper.com/ssl-checker.html#hostname=www.grafana.com
