### ISSUE TITLE
Panels not loading if query time is longer than refresh rate

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#24847]
**What happened**:
When there are many panels which take long to load and refresh rate is shorter than the time needed to load all the panels, some panels won't load until I manually change refresh rate.
![image](https://user-images.githubusercontent.com/19311511/82305927-a20fc580-99be-11ea-8459-7c525ef838c5.png)

**What you expected to happen**:
It should wait for all queries from previous refresh to finish before starting new refresh.

**How to reproduce it (as minimally and precisely as possible)**:
In my database there are a few milion records so it takes some time to load those panels.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Influxdb 1.7.9
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Opera Gx

**Comment by torkelo** [comment]
Uncompleted queries are canceled if they are not completed when a new refresh is triggered. You need to lower the refresh to a level where queries finish in time
