### ISSUE TITLE
PanelInspector: Hide apply field options in inspector for angular panels

### ISSUE THREAD

**Issue by zoliapjove** [grafana/grafana#24841]
**What happened**: 
Inspect > Data > Data display options > Apply field configuration - does not work, after enabling column style and values formats remain unchanged. Also it could be enabled by default.
![image](https://user-images.githubusercontent.com/24809373/82301850-7fcb7700-99c1-11ea-8dbe-c4a7ad3f904b.png)

**What you expected to happen**:
To change column style and values formats according Column Styles settings.

**Anything else we need to know?**:
Apply field configuration - could be enabled by default.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: MySQL
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Win10, Chrome

**Comment by torkelo** [comment]
The field config option only works if you are using one of the new panels (Table, stat, gauge, bar guage). 

Need to hide this option if your using an old panel

**Comment by hugohaggmark** [comment]
> The field config option only works if you are using one of the new panels (Table, stat, gauge, bar guage).
> 
> Need to hide this option if your using an old panel

@torkelo what's the best way to determine if field config options are supported or not?

**Comment by torkelo** [comment]
PanelPlugin fieldConfigRegistry.isEmpty()
