### ISSUE TITLE
Invalid JSON: Unexpected token { in JSON at position 171

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#24843]
Running elastic query in explore on v7.0.0 (aee1438ff2), got the following error:

> Invalid JSON: Unexpected token { in JSON at position 171

Looks like the query sent to elastic was invalid perhaps?

**Comment by aknuds1** [comment]
Do we perhaps not handle non-JSON error messages from Elastic? Looks like a classical example of that.

**Comment by tomwilkie** [comment]
The query was working in 6.x, so I'm not sure it was an problem handling the error...

**Comment by torkelo** [comment]
Think elastics was done, it's working now https://play.grafana.org/d/000000015/elasticsearch-templated?orgId=1&var-source=All&var-host=server%2020&var-host=server-5&var-test=test2

**Comment by torkelo** [comment]
both in explore & dashboard. Where are you getting the error?

**Comment by Estrax** [comment]
@torkelo It was the stats datasource on play. Probably it was down for a while, but can confirm it all works properly now.

**Comment by aknuds1** [comment]
@Estrax what causes the parsing error? That Grafana tries to parse a non-JSON error message?

**Comment by Estrax** [comment]
@aknuds1 Looks like so - the response Grafana tried to parse at this case was not a valid JSON.

**Comment by aknuds1** [comment]
> @aknuds1 Looks like so - the response Grafana tried to parse at this case was not a valid JSON.

@Estrax Hah, I was right after all :) We need to build in resilience in case the response isn't JSON.

**Comment by Estrax** [comment]
@aknuds1 Yep. Definitely we should.

Closing this issue now.

**Comment by aocenas** [comment]
@Estrax is there existing issue for this already or was this fixed somewhere? Cause we should definitely handle this with a bit better error message.

**Comment by Estrax** [comment]
@aocenas I'll open another issue in a while because it's a slightly bigger thing that's not datasource-specific.
