### ISSUE TITLE
Series Bar Graph dosen't respond when we click on legends

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#24858]
Series Bar Graph doesn't respond when we click on legends. It works fine in Time series but not with a series bar graph. 

When we click on legends it will highlight the plotted bar, this is not happening in a series bar graph. 

Attached is the screenshot that was taken in the play Grafana. 
![image](https://user-images.githubusercontent.com/65600879/82320847-8bcf2d00-99f1-11ea-8c02-485f8fe30b87.png)

**Comment by torkelo** [comment]
Using legend series hiding is currently no supported in series mode. In fact Grafana Graph hides the legend when you enable series mode, you can re-enable it but the hiding logic is not supported
