### ISSUE TITLE
Adding PostgreSQL Query to the panels leads to UNEXPECTED ERROR frequently

### ISSUE THREAD

**Issue by msinphilpk** [grafana/grafana#24854]
**What happened**: 
An unexpected error occurred (Details: TypeError - panelWidth is undefined) 
An unexpected error occurred (Details: TypeError - this.datapoints is undefined) 
These errors occurring frequently.
![Screenshot from 2020-05-19 15-52-57](https://user-images.githubusercontent.com/22269123/82315531-0ba4c980-99e9-11ea-9fd7-09e8d4374862.png)

**What you expected to happen**: Add a panel with a series using PostgreSQL query

**How to reproduce it (as minimally and precisely as possible)**: Simply, tried to add a SVG panel. The error occurred during addition of the PostgreSQL query. Also, tried with another panel STATUS PANEL and TABLE panel. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: PostgreSQL 10
- OS Grafana is installed on: Pop OS (local machine)
- User OS & Browser: Pop OS 20.04 LTS, Firefox browser
- Grafana plugins: SVG Panel by Marcus Calidus, Status Panel Tomer Amir and Table Panel.
- Others: Not tried with other panels

**Comment by Estrax** [comment]
@msinphilpk can you provide us with more details, including the browser version and external plugins versions?

**Comment by Estrax** [comment]
It's not a Grafana issue - that's the problem with an external plugin called `Status Panel`. It's outdated and not actively maintained. When you try to load it, it throws a bunch of errors trying to slice a variable that has the value of undefined.

```js
Uncaught TypeError: Cannot read property 'slice' of undefined
    at StatusPluginCtrl.setTextMaxWidth (status_ctrl.js:175)
    at StatusPluginCtrl.onRender (status_ctrl.js:216)
```

**Comment by msinphilpk** [comment]
Hi,
Thank you for your quick response. But, the issue is persisting whenever I
am trying to use an external panel. The error occured when I used the
panels like HTML and SVG. The external panels are not so stable. Is this an
issue of the maintenance of those external panels? Waiting for your
response.

Thank you,
MOHAMMED SINPHIL.

**Comment by Estrax** [comment]
@msinphilpk Yes, looking at the errors coming from the Status Panel, it's an issue within their codebase - looks like that plugin is not actively maintained. I highly recommend you to open an issue on the Status Panel repository, as we do not maintain third party plugins.

**Comment by msinphilpk** [comment]
Thank you for your help.
