### ISSUE TITLE
How Grafana caculate the value of  Single stat ( max/min/current/.../ )  in value option ?

### ISSUE THREAD

**Issue by GhostComputing** [grafana/grafana#2485]
When I use Sigle stat,  I am confused about the option about the setting of Value, as the following picture shows:
![2015-08-10 2 57 36](https://cloud.githubusercontent.com/assets/1625098/9160806/48fd21e8-3f70-11e5-92a7-6f0305671750.png).

I use Graphite as my data source, when I select one of the metric list and apply the combine function, such as:

`maxSeries($elogic_host.elogic_appkey_stat.publish_duration.*.last)`

I found the value is different by picking the different option of Value (like min/max/current).

I already apply max operation on the metric and how Grafana calculate the other max value ?

**Comment by torkelo** [comment]
maxSeries does not do what you think it does, maxSeries takes a number of series and for each data point for each series it will pick the highest. so it will return ONE series where each data point represents the maxium of all the series (for that time point).

Singlestat needs one number, graphite returns a series, so when you pick min/max/current you pick which one in the series returned by graphite should be used. 

Another thing of note is maxDataPoints, this sets how many data points graphite will return. 

So if you want a single max value for a time range over a number of series you can do this:

`consolidateBy(maxSeries($elogic_host.elogic_appkey_stat.publish_duration.*.last), 'max')`

So first get the max value for each series and data point (will generate one series with all the max values for each time step), then consolidateBy changes the consolidation function to max (default it is avg), so then no matter what maxDataPoints is set to the max value in grafana should be the the same.  (if you pick max in the singlestat value dropdown)
