### ISSUE TITLE
Docs feedback: /panels/transformations.md

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#24865]
Still refers to 7.0 beta

In this section: https://grafana.com/docs/grafana/latest/panels/transformations/#transformation-types-and-options

Only reduce is a hyperlink.  Each of them should be hyperlinked.

**Comment by shalstea** [comment]
The debug transformations could provide a little more detail on what one should look at.  Maybe provide a concrete example of where something went wrong and how you actually debugged it.

**Comment by oddlittlebird** [comment]
Added hyperlinks, but this is still a beta feature, so the text is correct.
