### ISSUE TITLE
Log panel can't copy first line

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#24862]
**What happened**:
When using the log panel, and I want to copy a traceID from the first log line I can't because of the top header bar that shows up.

See those screenshots:
![image](https://user-images.githubusercontent.com/1053421/82329143-de3b2a00-99ae-11ea-8bc9-2f71a787763e.png)
![image](https://user-images.githubusercontent.com/1053421/82329164-e4310b00-99ae-11ea-87ac-64f0d739d42b.png)

**What you expected to happen**:

Being able to copy the first log line.

**How to reproduce it (as minimally and precisely as possible)**:

Try to copy the first line of a log panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0-ac486de9pre (26964b383f)
- Data source type & version: Loki

**Comment by ivanahuckova** [comment]
@cyriltovena quick fix would be to add panel title, that way you can copy the first line 
![image](https://user-images.githubusercontent.com/30407135/83653480-2156e900-a5bc-11ea-9d3d-39e4ce975764.png)

**Comment by ivanahuckova** [comment]
Also, the same problem happens in every panel without the panel title, if you want to copy the value on top. Maybe this would be more @grafana/grafana-frontend-platform relevant - to fix the way we can open panel menu, if we don't have panel title, so it doesn't cover the content?
