### ISSUE TITLE
New Table Panel does not preserve the SORT order of the column

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#24863]
**What happened**:
Used Table Panel to display the data. Used transformation to calculate MEAN, MAX and MIN
![image](https://user-images.githubusercontent.com/14235758/82329679-500f7580-99a7-11ea-8880-2c1364f5b1f9.png)

Sorted the column by "Mean". Used some display options.
![image](https://user-images.githubusercontent.com/14235758/82329800-746b5200-99a7-11ea-8944-99bc068e848f.png)

Saved the dashboard. Reopened the table, the sort order on "Mean" is gone.
![image](https://user-images.githubusercontent.com/14235758/82330034-e6dc3200-99a7-11ea-9870-32d175d5e561.png)

**What you expected to happen**:
Preserve the sort order.  It was being preserved in older Table Panel.

**How to reproduce it (as minimally and precisely as possible)**:
Steps mentioned in the "What Happened" section

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Does not matter.
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins: Table

**Comment by luchaninov** [comment]
Configuring dashboard as json like this also doesn't apply sorting:
```
      "sort": {
        "col": 1,
        "desc": false
      },
```

**Comment by jdmaloney** [comment]
Just ran into this with v7 myself

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/24705
