### ISSUE TITLE
Backend Datasources: Change tsdb.Response Frames to be unencoded

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#24868]
I think having tsdb.Response's Frames property be encoded Frames, and not un-encoded Frames, was probably a mistake. 

Downsides:

 - Alerting ends up taking the encoded frame and decoding (`MarhsallArrow`, `UnmarshalArrow`), so there is encode/decode within Grafana that is not needed when alerting.
 - When authoring an internal datasource, in each datasource one needs to call .MarshalArrow(), which isn't something one should care about for each datasource (encoding it). This should be more like our plugin.

So tsdb.Response should probably have that property changed to unencoded Frames, and then marshalling/encoding happens closer to API when the response is returned. That way, within Grafana, the actual data.Frame structure is what is moved around. One possible downside I see to this change is that errors in encoding due to malformed frames could happen later then what one might naturally test. But I think that just means that there needs to be some Validate() methods.

**Comment by marefr** [comment]
Sounds reasonable. Can you just include link to some code underlying the problem?

**Comment by kylebrandt** [comment]
For example:

```
	dataframe, err := queryResultsToDataframe(getQueryResultsOutput)
	if err != nil {
		return nil, err
	}

	dataframeEnc, err := dataframe.MarshalArrow()
	if err != nil {
		return nil, err
	}

	response := &tsdb.Response{
		Results: make(map[string]*tsdb.QueryResult),
	}

	response.Results["A"] = &tsdb.QueryResult{
		RefId:      "A",
		Dataframes: [][]byte{dataframeEnc},
	}

	return response, nil
```

The in `alerting/conditions/query.go`

```
		// If there are dataframes but no series on the result
		useDataframes := v.Dataframes != nil && (v.Series == nil || len(v.Series) == 0)

		if useDataframes { // convert the dataframes to tsdb.TimeSeries
			frames, err := data.UnmarshalArrowFrames(v.Dataframes)
			if err != nil {
				return nil, errutil.Wrap("tsdb.HandleRequest() failed to unmarshal arrow dataframes from bytes", err)
			}

			for _, frame := range frames {
				ss, err := tsdb.FrameToSeriesSlice(frame)
				if err != nil {
					return nil, errutil.Wrapf(err, `tsdb.HandleRequest() failed to convert dataframe "%v" to tsdb.TimeSeriesSlice`, frame.Name)
				}
				result = append(result, ss...)
			}
		} else {
			result = append(result, v.Series...)
		}
```

**Comment by kylebrandt** [comment]
However, as I think about this more, I think this might be more of a symptom. 

If we are using something like the following in Grafana:

```go
type HandleRequestFunc func(ctx context.Context, dsInfo *models.DataSource, req *TsdbQuery) (*Response, error)

func HandleRequest(ctx context.Context, dsInfo *models.DataSource, req *TsdbQuery) (*Response, error) {
	endpoint, err := getTsdbQueryEndpointFor(dsInfo)
	if err != nil {
		return nil, err
	}

	return endpoint.Query(ctx, dsInfo, req)
}

....

type TsdbQueryEndpoint interface {
	Query(ctx context.Context, ds *models.DataSource, query *TsdbQuery) (*Response, error)
}
```

But, in the SDK it is:

```
type QueryDataHandlerFunc func(ctx context.Context, req *QueryDataRequest) (*QueryDataResponse, error)
``` 

Then things are going be awkward I think.  We won't be able to use stuff like the queryType muxer/router and other stuff we have built I don't think. So likely to repeat ourselves and make mistakes, and the choice of if certain datasources should be bundled or plugins (or bundled plugins) will be more difficult, because the move will have more technical overhead.

**Comment by marefr** [comment]
My 2 cents:
Regarding tsdb.Response should probably have that property changed to unencoded Frames, we probably want to convert to dto [here](https://github.com/grafana/grafana/blob/460847f3edb255ad8662f3f96b776769f165a496/pkg/api/metrics.go#L133) and [here](https://github.com/grafana/grafana/blob/460847f3edb255ad8662f3f96b776769f165a496/pkg/api/metrics.go#L92) and return encoded frames.
