### ISSUE TITLE
Is there any way to use regex to select hostname in opentsdb

### ISSUE THREAD

**Issue by zjian1993** [grafana/grafana#2487]
Now I am use openTSDB in grafana, I want to select a metric named beanstalk.current in several hostname. There are lots hostname have this metric, and I just want get the data from host which hostname start with "mobile", such like mobile-beanstalk01, mobile-beanstalk02. I use the tag and select key as hostname, value as "mobile*", but this warning error. So how can I use regex in tag?

ps : I have found set the tag value as "*" can select all, so I think regex is supported

thanks!

**Comment by torkelo** [comment]
This is handled by OpenTSDB, so I think you need to ask this question in that github repo or mailing list. All I know is that you can use wildcard, not sure if can use part of a tag value then wildcard or full regex.

**Comment by zjian1993** [comment]
now I use value like "mobile-beanstalk01|mobile-beanstalk02|mobile-beanstalk03" and it can show 3 lines, but how should set alias so it can named  "mobile-beanstalk01" not "beanstalk.current{hostname=mobile-beanstalk01}"

**Comment by torkelo** [comment]
try $tag_hostname

**Comment by torkelo** [comment]
in alias field

**Comment by zjian1993** [comment]
it works, thanks
