### ISSUE TITLE
Usability: not possible to cut and paste queries: Switching to query builder may overwrite your raw SQL

### ISSUE THREAD

**Issue by minfrin** [grafana/grafana#24874]
**What happened**:

Was not able to cut and paste a SQL query from one postgres query to another. After a paste and clicking on querybuilder, the following warning appears, and the pasted query is wiped out:

```
Switching to query builder may overwrite your raw SQL.
```

**What you expected to happen**:

After cutting and pasting the query, the query appears in the query builder.

**How to reproduce it (as minimally and precisely as possible)**:

- Cut and paste a sql query form one panel to another.
- Click on querybuilder.
- Warning appears, query is lost if you continue.

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana-6.7.3
- Data source type & version: postgresql
- OS Grafana is installed on: CentOS8
- User OS & Browser: Firefox latest version / MacOS Mojave
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The query builder does not support parsing your full SQL query to construct its model.

So to copy a query using the UI builder use the duplicate query icon button

**Comment by minfrin** [comment]
The duplicate query option doesn't allow to you to create a duplicate in a different panel, or not that I've seen.

It looks like the query builder isn't finished. A cut and paste in theory would use the sql query as the cut-and-pasted data, the "cut" would just create the query, while the "paste" would recreate the builder on the other side (within reason, if the text wasn't valid sql the query builder would do nothing).

This has been one of the biggest pain points so far as a new user, generating the datasources is very time consuming and repetitive.

**Comment by francescor** [comment]
same issue here: unable to cut and paste a query :(
