### ISSUE TITLE
NewsPanel: Support styled html in rss content

### ISSUE THREAD

**Issue by tommywo** [grafana/grafana#24875]
**What happened**:
inside NewsPanel content of `<style type="text/css></style>` tag is written as text,
all html tags are removed including line breaks, tables, etc. 

![Screenshot 2020-05-19 at 17 11 10](https://user-images.githubusercontent.com/11270518/82343998-ccc84100-99f3-11ea-8bde-f542683098d6.png)

**What you expected to happen**:
Content should be rendered properly similar to rss reader or correctly sanitised including formatting of tables etc.

**How to reproduce it (as minimally and precisely as possible)**:
Create a NewsPanel with Display URL set to `https://issues.jenkins-ci.org/sr/jira.issueviews:searchrequest-rss/temp/SearchRequest.xml?jqlQuery=&tempMax=2` and check Use proxy 

**Environment**:
- Grafana version Grafana v7.0.0 (aee1438ff2)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
