### ISSUE TITLE
BUG: TimeRange and $__timeFilter values does not matches

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24871]
**What happened**:

![image](https://user-images.githubusercontent.com/2898361/82339352-c3e56880-9a0f-11ea-8daa-70a875c6959a.png)

**What you expected to happen**:

they must match

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by jangaraj** [comment]
IMHO it isn't bug. Data should be stored in the DB in the UTC, so query must be in the UTC as well and frontend "moves" UTC results to the selected timezone.

**Comment by torkelo** [comment]
Yes looks correct

**Comment by baur** [comment]
Ok, thanks you
