### ISSUE TITLE
Edit Panel - Bar Gauge leaks the chart on the query editor if you have more than 32 times series

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#24889]
**What happened**:
I have more than 32 series in a chart. 
I created a Bar Gauge chart with Horizontal Orientation. The Panel visualization leaked on the query editor.

![image](https://user-images.githubusercontent.com/14235758/82376611-fd09e280-99e7-11ea-88e8-8923510dc846.png)

**What you expected to happen**:
Chart in Query editor should respect the real estate available for bar gauge in horizontal mode.

**How to reproduce it (as minimally and precisely as possible)**:
https://play.grafana.org/d/Fbp5uPsZk/1-new-features-in-v6-6?editPanel=5&orgId=1. Set the Series Count to 32 in Panel Editor.

**Anything else we need to know?**:
When you come out of the panel editor, dashboard shows the chart correctly. .

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Does not matter
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins: Bar Gauge
- Others:

**Comment by tskarhed** [comment]
What should the expected behavior be when the layout doesn't fit anymore?

**Comment by MacNale** [comment]
Scrolling makes most sense.

**Comment by igorzavgorodniy** [comment]
@kaydelaney looks like not fixed ((
![image](https://user-images.githubusercontent.com/64777755/97486553-45003e80-1964-11eb-9471-efe095841566.png)

**Comment by torkelo** [comment]
Are you running 7.3 ?

**Comment by igorzavgorodniy** [comment]
> Are you running 7.3 ?

no. 7.1.5
Does this PR get into 7.3?
