### ISSUE TITLE
Grafana 7.0 - bar gauge weird size distribution

### ISSUE THREAD

**Issue by tatototino** [grafana/grafana#24885]
**What happened**:
The graph is showing a weird bar distribution.

![bug-bar-gauge](https://user-images.githubusercontent.com/10597278/82370307-ba97d400-99ee-11ea-8b3b-6068e9333d1e.PNG)
![bargauge2](https://user-images.githubusercontent.com/10597278/82370336-c2f00f00-99ee-11ea-98b0-d613ea96ca4e.PNG)

**What you expected to happen**:

I expected to have some almost amount size bar for 5 and 6 values.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Grafana version: grafana-7.0.0-1.x86_64 
- Data source type & version: Mysql
- OS Grafana is installed on: Centos 7.8
- User OS & Browser: Firefox 76.0.1 (64-bits)
- Grafana plugins:

**Comment by torkelo** [comment]
Set the min and max in Field tab.

If you do not specify a min and a max Grafana will automatically determine them from your data. And 6 is max and 5 is min, which explains why it’s showing the data like that

**Comment by tatototino** [comment]
Hi Torkelo,

I just  set min and max  and it works. Thanks
