### ISSUE TITLE
Open in new tab for dashboard link doesn't work in Grafana 7.0

### ISSUE THREAD

**Issue by leonsery** [grafana/grafana#24881]
**What happened**:
Open in new tab for dashboard link doesn't work in Grafana 7.0 (upgrade from 6.6.1)

**What you expected to happen**:
When 'Open in new tab' for dashboard link is selected - link opens in new tab

**How to reproduce it (as minimally and precisely as possible)**:
Create two dashboards. In the first one create the link to second one. Select 'Open in new tab' option. Save dashboard. Click on just created link - another dashboard will open in the same tab.

**Anything else we need to know?**:
This bug reproduced for both types of links - links and dashboards.

**Environment**:
- Grafana version: 7.0
- Data source type & version: NA
- OS Grafana is installed on: CentOS
- User OS & Browser:Chrome
- Grafana plugins:NA
- Others: Grafana was upgraded from version 6.6.1 where mentioned behavior was as expected.

**Comment by peterholmberg** [comment]
Fixed by https://github.com/grafana/grafana/pull/24772
