### ISSUE TITLE
Scrolling on mobile not possible when logged in to admin account [v7]

### ISSUE THREAD

**Issue by Pwuts** [grafana/grafana#24892]
**What happened**:
I upgraded Grafana to v7.0 from one of the latest v6.x releases. I open my dashboards (Google Chrome, Android v8.1) and can't scroll in my dashboards anymore *when logged in to my admin account*.

**What you expected to happen**:
Features++ and UX++

**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana on a mobile device, log in to a super admin account, open a dashboard and try to scroll.

**Anything else we need to know?**:
I first had this problem with my super admin account. Then I switched to a normal user account, and I could scroll. Swithing back to the admin account, I couldn't scroll again.
**_Edit:_ Apparently this occurs when the viewport width is >452px and the user is allowed to drag panels.**

**Environment**:
- Grafana version: v7.0.0
- Data source type: InfluxDB
- OS Grafana is installed on: Ubuntu 18.04LTS
- User OS & Browser: Android 8.1.0; latest Google Chrome

**Comment by torkelo** [comment]
Can you show your home dashboard? Does this happen on all dashboards?

**Comment by Pwuts** [comment]
It happens on three dashboards in two organizations on my Grafana instance. I can't scroll when over gauges or graphs, which are the only types of panels I currently have.

![Climate monitoring dashboard](https://user-images.githubusercontent.com/12185583/82443548-fb045a00-9aa1-11ea-97bc-8d730cda9c69.png)
![Energy usage dashboard](https://user-images.githubusercontent.com/12185583/82443621-15d6ce80-9aa2-11ea-92d9-fd5c1455c000.png)

I noticed I can't reproduce this behavior in my browser. Then I borrowed someone else's (Android) phone and there it worked. I noticed the dashboard was differently scaled than on my device, so I changed the display size setting on my Nexus 5X from "Small" back to "Standard" and behold, I could scroll my dashboard. Changing the display size back to "Small" made me unable to scroll again.

**Comment by Pwuts** [comment]
Update: I can now reproduce it in the desktop browser with the responsive layout tools:
![2020-05-20_14-12-36](https://user-images.githubusercontent.com/12185583/82444873-28ea9e00-9aa4-11ea-9b6b-bcf247152df0.gif)

Viewport width = 452px: scrolls fine.  
Viewport width = 454px: no scroll.

**Comment by Pwuts** [comment]
@torkelo is this enough info?

**Comment by crnh** [comment]
I am experiencing exactly the same issue with my Grafana 7.0.2 instance. When testing it with the responsive layout tools in Chrome, scrolling became impossible with a viewport width of >= 453px.

**Comment by torkelo** [comment]
Unable to replicate in 7.1.1 , so looks like it's fixed

**Comment by Pwuts** [comment]
@torkelo upgraded my instance to 7.1.1, cleared caches etc etc, tested, problem persists.

**Comment by torkelo** [comment]
Strange I can scroll fine one for example https://play.grafana.org/d/3SWXxreWk/grafana-dashboard?orgId=1

**Comment by Pwuts** [comment]
What's your viewport width & browser?
