### ISSUE TITLE
Reduce tranformations shows incorrect values

### ISSUE THREAD

**Issue by yuvarajhere** [grafana/grafana#24893]
**What happened**:
When reducing the values using transformation function, it performs the operations selected in  Panel display function.

**What you expected to happen**:
Actual calculated values based on selected function.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add two query with different values [vector(1) and vector(2)]
2. Change the visualization to stat.
3. Click transformation and select reduce. 
4. Select any math function (more than one). It will display the values calculated with default 'Mean' option or selected display function.

Screen capture:

<img width="1438" alt="Screen Shot 2020-05-19 at 6 31 17 PM" src="https://user-images.githubusercontent.com/29648850/82380644-2f730a00-99ff-11ea-81d6-21b3a60a03ac.png">

**Anything else we need to know?**:
If we create one more transformation function, it works as expected.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Mac
- User OS & Browser: Firefox
- Grafana plugins: NA
- Others: NA

**Comment by dprokop** [comment]
Panel options are applied after the transformations. In this case the Max value displayed is chosen from the **result** of the Reduce transformation

Can you share JSON objects from the transformation debug view?

**Comment by torkelo** [comment]
If use reduce across multiple queries/rows you and you want to show all rows you need to switch Show option in the stat panel to "All values"
