### ISSUE TITLE
Edit Panel - Stat panel does not render chart correctly if there are more than 32 series 

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#24890]
**What happened**:
Stat panel does not render the data correctly when the series count is more than 32 in panel editor.

![image](https://user-images.githubusercontent.com/14235758/82378228-6985e100-99ea-11ea-9966-da5c6a43c356.png)

**What you expected to happen**:
Respect the real estate and render accordingly.

**How to reproduce it (as minimally and precisely as possible)**:
Set the series count = 32 and change the visualisation to stat panel with horizontal layout
https://play.grafana.org/d/Fbp5uPsZk/1-new-features-in-v6-6?editPanel=5&orgId=1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Does not matter
- OS Grafana is installed on: Docker
- User OS & Browser: - Chrome
- Grafana plugins: Stat Panel

**Comment by torkelo** [comment]
Chart is automatically hidden if there is no space, try auto layout could make Grafana find a more efficient layout that means there is room for graph

**Comment by MacNale** [comment]
> Chart is automatically hidden if there is no space, try auto layout could make Grafana find a more efficient layout that means there is room for graph

With Auto layout, the panel editor changes the orientation to vertical and shows the chart okay. However, I am looking for horizontal layout.  Once you come out of panel editor, the dashboard displays horizontal stat panel correctly. It is the layout in Panel Editor screws up when horizontal layout is chosen.

I can live with it. It is about avoiding this weird behaviour in panel editor. I dont want to document this behaviour for the dashboard consumers.
