### ISSUE TITLE
A web page is slowing down the browser. What would you like to do?

### ISSUE THREAD

**Issue by minfrin** [grafana/grafana#24895]
**What happened**:

After upgrading to Grafana 7, attempts to use the SQL query builder cause extremely high CPU load in the local machine, and rapid battery drain.

Firefox warns: "A web page is slowing down the browser. What would you like to do?"

**What you expected to happen**:

Grafana worked at the same performance level as Grafana 6.7.

**How to reproduce it (as minimally and precisely as possible)**:

Work with the SQL builder against a PostgreSQL datasource.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Postgresql / Timescaledb
- OS Grafana is installed on: CentOS8
- User OS & Browser: MacOS / Firefox
- Grafana plugins:
- Others:

<img width="1160" alt="slowing-down-the-browser" src="https://user-images.githubusercontent.com/1331788/82383396-fdc56780-9a2d-11ea-90b4-70d1a0190cf4.png">

**Comment by torkelo** [comment]
It's probably caused by way too many data points returned by your query.  Add a group by time to limit data points:

**Comment by minfrin** [comment]
As you can see, the whole UI has frozen up - adding a "group by time" is not possible.

Grafana needs to protect itself from this kind of situation, it can't just crash the browser window every time you add a query, especially when the default behaviour of a new query is to query everything.

Please reopen this.
