### ISSUE TITLE
"Cannot read property 'toFixed' of undefined" on Gauge panel with no data

### ISSUE THREAD

**Issue by corhere** [grafana/grafana#24897]
**What happened**:
The error `Cannot read property 'toFixed' of undefined` appears in the top-left corner of a Gauge panel when the panel's queries return no data.

**What you expected to happen**:
The Gauge renders with the text "No data".

**How to reproduce it (as minimally and precisely as possible)**:
Do one of the following:
- Visit https://play.grafana.org/d/000000012/grafana-play-home?editPanel=7&orgId=1 and change Panel->Visualization to "Gauge", "Bar gauge", or "Table".
- Add a panel to a dashboard. Click the "Add a new panel" button. Leaving everything else at defaults, set Panel->Visualization to "Gauge", "Bar gauge", or "Table". 

Observe a red "!" appear in the top left corner of where the panel is supposed to be, with a hover tooltip of your browser's flavour of `Cannot read property 'toFixed' of undefined`.

**Anything else we need to know?**:
I have also replicated the error on play.grafana.org and on a Docker instance of Grafana 7.0.0, on both Chrome and Safari.

It appears to be necessary to set the following options on the panel's "Field" tab to trigger the bug:
- Min, Max: unset (auto)
- Thresholds mode: Absolute

The choice of data source seems to be irrelevant so long as there are either no queries defined or the queries return no data for the time period.

**Environment**:
- Grafana version: 7.0.0 (Docker image `sha256:4c8a5fede0b0982d4588a77a80aeeb5bc572e333a557615f0753aaed7e6fb901`)
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: macOS 10.15.4, Chrome 81.0.4044.138 and Safari 13.1 (15609.1.20.111.8)
- Grafana plugins: N/A
- Others:

**Comment by phemmer** [comment]
For me, I'm getting this error with gauge, stat, & table, even when there is data.
I have to switch the panel over to a graph, click the button where it says "unable to graph data, switch to table view", then change the panel back to a guage.
The "format as: table" option does not help.

**Comment by isehgu** [comment]
Experiencing the same thing. I am using a custom datasource. When I restart my datasource, the grafana dashboard will break with this error. Then I would have to do the dance of switching it to graph, save, then back to gauge or table.

**Comment by drazul** [comment]
I have the same issue but if I refresh the browser then grafana is able to draw the gauge.

So the problem is not the behaviour when there is no data as the PR https://github.com/grafana/grafana/pull/24938 suggest. The real problem looks like the javascript to render the chart is not waiting for the data .

**Comment by isehgu** [comment]
I can confirm that. Just tried it. Refreshing the page fix the gauge.

**Comment by mckn** [comment]
Super, awesome testing and feedback! Is this happening when the datasource is a bit slow in delivering data? I just want to try to reproduce it.

**Comment by isehgu** [comment]
In my case, yes.

**Comment by mckn** [comment]
> In my case, yes.

OK ok, thanks! Will have a look at that one as well. See if it will be resolved by the merged fix.

**Comment by mckn** [comment]
I tried the bugfix that is merged to master and it seems to solve the issue described when having slow queries as well.

**Comment by isehgu** [comment]
great to hear.

**Comment by mnpenner** [comment]
I'm still seeing this in Grafana v7.3.1 (6668161a88)

**Comment by mckn** [comment]
@mnpenner could you provide us with a way to reproduce it? Maybe a dashboard or panel json.

**Comment by mnpenner** [comment]
Of course, *now* I can't get it to happen. The fix, when I encountered it before, was exactly as phemmer said -- I had to switch from Bar gauge back to Graph and then click on "Switch to table view" and then back to Bar gauge again. But now it doesn't seem to be happening on a fresh panel; so maybe there's a few extra steps needed to break it, not sure. Will let you know if it happens again. Thanks!

**Comment by rockynox** [comment]
I'm also having it in v7.3.1 (6668161a88). I use DataExplorer as datasource. The workaround described above - switch to graph and switch back- doesn't work for me. 
Here is the behaviour:
- When there is no data to render, I get this error on the gauge graph 
- The Gauge graph is thus broken, even if there is new data to render
- The only way of make it work again is to refresh the entire page.

**Comment by just1900** [comment]
Hi, any progress? I'm in the same situation as @rockynox

**Comment by mckn** [comment]
@rockynox @just1900 are you still experience this issue?

**Comment by Maplesoup** [comment]
@mckn I've managed to replicate this issue see console log below

![image](https://user-images.githubusercontent.com/7526769/108734052-f6843a80-7526-11eb-893a-9df0aa72973b.png)

This appears to happen if you don't have the min and max fields set in the fields section, this boolean flag seems to always be true, even if the max and min are null.

![image](https://user-images.githubusercontent.com/7526769/108734278-3a773f80-7527-11eb-8faa-d64aa16bb730.png)

If you set the max and min then change the visualisation to graph then back to Gauge it will start working.

Another bug is that the Visualisation doesn't refresh when the fields section is changed.

**Comment by amperen** [comment]
The issue was fixed for me by updating Grafana from version 7.3.1 to 7.5.7.
