### ISSUE TITLE
v7: Tables no longer merge on matching columns

### ISSUE THREAD

**Issue by jutley** [grafana/grafana#24891]
With Grafana v7, I set up two Prometheus queries, like this:

```
sum by (cluster, region, namespace) (kube_pod_container_resource_requests_cpu_cores)
```

```
sum by (cluster, region, namespace) (kube_pod_container_resource_limits_cpu_cores)
```

In previous versions, results were merged on matching tags, which is what I wanted. Now, we have to be explicit about how data is being merged. I don't mind this, but it's extremely limited. The "outer join" transformation only allows us to join on a single label when I want to join on the three I call out in my query.

I can use `label_join` in my PromQL query to create a new label to join on. This works, but then I get joined data where I have two cluster, region, and namespace. I don't have any way to hide one of the duplicate columns.

In my opinion, this is a significant regression and makes tables unusable. Is there any plan to allow for joining time series on multiple columns?

**Comment by Miller-STGT** [comment]
Similar issue with postgres as datasource.
For example:
Table1 has columns "hostname, host_status" and Table 2 has "hostname, service_status".
If you outer join on hostname the result is "hostname, host_status, host_status, service_status, service_status".

**Comment by derekperkins** [comment]
This is a major blocker for us using the new table

**Comment by jflorencio** [comment]
@mckn @torkelo can we have this issue re-opened? The "merge on time" implemented in PR #25490 request does not merge on multiple columns, just time.

For example, the following (visualized with table-old):
![table-merge-grafana](https://user-images.githubusercontent.com/278027/86297704-dcb97000-bbb0-11ea-8ee9-e02b18fe312d.png)

table-old performs the by join by matching labels in each query, not just time which I hide here. This is not possible in Grafana 7.1.0-beta1 since the new merge in PR #25490 merges based on time, and the outer join transformation only allows one column to be specified.

I think what we need is the ability to specify multiple fields to generate a composite join key in the existing outer join transform - it seems unnecessary to have an entirely new transform.

**Comment by mckn** [comment]
> @mckn @torkelo can we have this issue re-opened? The "merge on time" implemented in PR #25490 request does not merge on multiple columns, just time.
> 
> For example, the following (visualized with table-old):
> ![table-merge-grafana](https://user-images.githubusercontent.com/278027/86297704-dcb97000-bbb0-11ea-8ee9-e02b18fe312d.png)
> 
> table-old performs the by join by matching labels in each query, not just time which I hide here. This is not possible in Grafana 7.1.0-beta1 since the new merge in PR #25490 merges based on time, and the outer join transformation only allows one column to be specified.
> 
> I think what we need is the ability to specify multiple fields to generate a composite join key in the existing outer join transform - it seems unnecessary to have an entirely new transform.

@jflorencio could you post the same example with the new tabel + the merge tansform? Would also be nice to get some example data on what is returned from A and B and how you want it to be visualized.

**Comment by torkelo** [comment]
Here is a dashboard json with old and new table that replicates the issue:

https://gist.github.com/torkelo/f004eaf2c9bd0c4ab382f1a531fd844b


![Screenshot from 2020-07-02 10-03-21](https://user-images.githubusercontent.com/10999/86332959-88af9980-bc4b-11ea-8623-94c43f12b553.png)

**Comment by mckn** [comment]
> Here is a dashboard json with old and new table that replicates the issue:
> 
> https://gist.github.com/torkelo/f004eaf2c9bd0c4ab382f1a531fd844b
> 
> ![Screenshot from 2020-07-02 10-03-21](https://user-images.githubusercontent.com/10999/86332959-88af9980-bc4b-11ea-8623-94c43f12b553.png)

Super, thanks! So this one will be an easy fix (I think). Will have a look at it and try to resolve it asap.

**Comment by torkelo** [comment]
Updated the test dashboard with another use case https://gist.github.com/torkelo/99fe4625df631b60c9a459904c4d0bf2
