### ISSUE TITLE
Bug (v2.1 & 2.1.1), Graphite dashboard import not working

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2490]
When you hit load you get "Not Found" error.

**Comment by martbhell** [comment]
Re-open this to get the fix into next release?

For reference, on CentOS with 2.1.3 I had to manually change first entry of dashboard/import to dashboard-import in /usr/share/grafana/public/app/app.bd986dd5.js to get Loading of graphite dashboard to work.

**Comment by torkelo** [comment]
It is working in master and 2.5 pre release builds
