### ISSUE TITLE
Missing information in the documentation about variable display names.

### ISSUE THREAD

**Issue by MaDOS** [grafana/grafana#24913]
**What would you like to be added**:
I would like the information from this comment https://github.com/grafana/grafana/issues/13210#issuecomment-457358086
to be included in the documentation. 
**Why is this needed**:
This can be very important information for some scenarios and is nowhere documented to be easy to find.

**Comment by torkelo** [comment]
it's documented here: https://grafana.com/docs/grafana/latest/features/datasources/postgres/#query-variable
