### ISSUE TITLE
dynamically create row per apps

### ISSUE THREAD

**Issue by mag009** [grafana/grafana#2491]
Hi  torkelo,

A nice feature to have would be the ability to hide or show a row based on the $apps / metrics 

example : I have $host.$apps 

apps = { mysql, apache, varnish, etc.. }  apps can be multiple(s) I can have apache and mysql on the same host.

so when a metric exist for X host display the row with the mysql metrics only

The idea is to have the default metrics + the apps for a host without having to switch between dashboard.

Thanks!!

cheers,
MAG

**Comment by torkelo** [comment]
In Grafana 2.1 you can repeat rows or panels based on selected state of template variables.
http://play.grafana.org/dashboard/db/new-features-in-v2-1

**Comment by harryshayne** [comment]
how to repeat rows?I can't find that

**Comment by torkelo** [comment]
Open row editor (green icon to the left to open row menu, then select row editor)
