### ISSUE TITLE
add support for password hashing in the config files

### ISSUE THREAD

**Issue by w-bazan** [grafana/grafana#24911]
**What would you like to be added**:

It would be great if grafana supports password hasing in config files (e.g. ldap bind user or for thedb user when notusing sqlite for storing dashboard config). The latter one is of a morw concern as this will be priviliged user. LDAP bind user can be read-only. Alternate would be to allow for the passwords to be set by the command assigned to password fields. Such commands could pull the password from external password encryption systems of preference. 

**Why is this needed**:

Eliminate security concern

**Comment by torkelo** [comment]
how would this work? We cannot authenticate against ldap using a hashed password

**Comment by w-bazan** [comment]
Thank you for responding to my request.

I am not suggesting to send a hash over the web. There could be an executable provided within grafana users could use to encrypt the password. It would return a hash users then enter to the config file. During runtime the hash could be decrypted whenever needed. Encryption key could be created upon installation with use of some server's environmentals (e.g. hostid). If that is too much of a coding effort how about the second option in which password would be evaluated from executable/script user would provide instead of a plain text?

**Comment by torkelo** [comment]
you can use env variables to set any config option, seems like it would provide the same level of security as you propose to have encryption key in env variable
