### ISSUE TITLE
When the "Excel CSV Dialect" option is selected, the exported data is garbled

### ISSUE THREAD

**Issue by karlie93** [grafana/grafana#24910]
**What happened**:
I have the same problem in use,I tried to export the data and select "Excel CSV Dialect" from the table, it exported the data in gibberish,you can see from the attached screenshot, when I did not select the "Excel CSV Dialect", I got values displayed properly, but it only has one column of data，with semicolon dividers.The table contains numbers and Chinese

**What you expected to happen**:
I want to export the data and select "Excel CSV Dialect" from the table,the data in the table can be displayed normally when opened in Excel.Thanks

**How to reproduce it (as minimally and precisely as possible)**:
Can the language format be the same.

**Anything else we need to know?**:
nothing

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: SQL Server
- OS Grafana is installed on: windows 10
- User OS & Browser:Crhome
- Grafana plugins:Standard Table
- Others:

what it looks like in grafana：
![image](https://user-images.githubusercontent.com/54050952/82414782-29863300-9aaa-11ea-9098-b197dbedd86d.png)

select "Excel CSV Dialect"：
![image](https://user-images.githubusercontent.com/54050952/82414922-5f2b1c00-9aaa-11ea-9dab-4a77cb97b3f1.png)

did not select the "Excel CSV Dialect"：
![image](https://user-images.githubusercontent.com/54050952/82415065-8d106080-9aaa-11ea-8740-e577068269cc.png)

**Comment by torkelo** [comment]
The export csv feature has been rewritten in 7.0, Can you try that?

**Comment by yangliuyu** [comment]
@torkelo 7.0 still has same problem, refer to https://github.com/grafana/grafana/issues/24924#issuecomment-654774308
