### ISSUE TITLE
v7: InfluxDB boolean Values not returned

### ISSUE THREAD

**Issue by lephisto** [grafana/grafana#24929]
**What happened**:

When retrieving a boolean value from an InfluxDB with traditional InfluxQL the Panel shows "No data" while the query inspector show the Value is being returned from the DB.,

**What you expected to happen**:

I would expect Grafana to treat the Value as Integer or at least display the textual represenation of the boolean value.

**How to reproduce it (as minimally and precisely as possible)**:

Put a boolean value in a Influx Measurement and query it to a Stat Panel.

**Environment**:
- Grafana version: 7.0
- Data source type & version: 1.0.2
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Linux / FF 76.0.1
- Grafana plugins: Flux, Singlestat math,

**Comment by peterholmberg** [comment]
Potentially fixed via https://github.com/grafana/grafana/pull/24829

**Comment by ryantxu** [comment]
can you reopen if this is still an issue?
