### ISSUE TITLE
Dashboard links no longer work in Grafana 7.0

### ISSUE THREAD

**Issue by disaster123** [grafana/grafana#24925]
**What happened**:
After upgrading from 6.7 to 7.0 dashboard links no longer work. They point to / and are shown as an external link icon.

**What you expected to happen**:

Links should work as they did on 6.7

**How to reproduce it (as minimally and precisely as possible)**:

Add two dashboards each one with a different tag. Add links to each other using tags.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: no matter
- OS Grafana is installed on: grafana docker
- User OS & Browser: Ubuntu + Chromium
- Grafana plugins: InfluxDB

**Comment by dprokop** [comment]
Fixed by https://github.com/grafana/grafana/pull/24773.

**Comment by dprokop** [comment]
Duplicate https://github.com/grafana/grafana/issues/24749
