### ISSUE TITLE
Grafana 7 export CSV， garbled characters appear in Chinese

### ISSUE THREAD

**Issue by karlie93** [grafana/grafana#24924]
What happened:
I upgraded grafana to the 7.0.0 version,I tried to export the data as a csv file,the Chinese characters in the file are still garbled when opened use excel,you can see from the attached screenshot.
I directly open the csv file,I found that the 6.6.2 version is not garbled, while the 7.0.0 version is garbled.

What you expected to happen:
I hope it can support the correct export of Chinese content, and can be used correctly in Excel.Thanks

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:
nothing

Environment:

Grafana version: 7.0.0/6.6.2
Data source type & version: SQL Server
OS Grafana is installed on: linux
User OS & Browser:Chrome
Grafana plugins:Standard Table
Others:

Grafana version: 7.0.0  csv file
![824396c0](https://user-images.githubusercontent.com/54050952/86769910-75a12d00-c082-11ea-825d-1f9b3e487ec7.png)

Grafana version: 7.0.0  use excel
![image](https://user-images.githubusercontent.com/54050952/82439723-b8587700-9acd-11ea-99da-1461acd82fc6.png)

Grafana version: 6.6.2  csv file
![82439770-cc2](https://user-images.githubusercontent.com/54050952/86770075-b5681480-c082-11ea-9986-4a555677bcd8.png)

Grafana version: 6.6.2 use excel
![image](https://user-images.githubusercontent.com/54050952/82439901-09686b00-9ace-11ea-846a-3537fc1d2d19.png)

**Comment by yangliuyu** [comment]
in 6.6.2 the BOM is added in csv file by filefile-saver
only need to change the default column separator
```
--- a/public/app/core/utils/file_export.ts
+++ b/public/app/core/utils/file_export.ts
@@ -7,7 +7,7 @@ const DEFAULT_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm:ssZ';
const POINT_TIME_INDEX = 1;
const POINT_VALUE_INDEX = 0;
-const END_COLUMN = ';';
+const END_COLUMN = ',';
const END_ROW = '\r\n';
const QUOTE = '"';
const EXPORT_FILENAME = 'grafana_data_export.csv';
```

in 7.0.5 the autoBom seems not work:
```
--- public/app/features/dashboard/components/Inspector/InspectDataTab.tsx	(revision efbcbb838b4318eaf04161bc9216c74d0155efba)
+++ public/app/features/dashboard/components/Inspector/InspectDataTab.tsx	(date 1594119199993)
@@ -86,11 +86,11 @@
     const dataFrameCsv = toCSV([dataFrame]);
 
     const blob = new Blob([dataFrameCsv], {
-      type: 'application/csv;charset=utf-8',
+      type: 'text/csv;charset=utf-8',
     });
     const transformation = transformId !== DataTransformerID.noop ? '-as-' + transformId.toLocaleLowerCase() : '';
     const fileName = `${panel.title}-data${transformation}-${dateTimeFormat(new Date())}.csv`;
-    saveAs(blob, fileName);
+    saveAs(blob, fileName, { autoBom: true });
   };
 
   onSelectedFrameChanged = (item: SelectableValue<number>) => {

```
but works with adding hard code 0xFEFF
```
--- public/app/features/dashboard/components/Inspector/InspectDataTab.tsx	(revision efbcbb838b4318eaf04161bc9216c74d0155efba)
+++ public/app/features/dashboard/components/Inspector/InspectDataTab.tsx	(date 1594118068625)
@@ -85,8 +85,8 @@
 
     const dataFrameCsv = toCSV([dataFrame]);
 
-    const blob = new Blob([dataFrameCsv], {
-      type: 'application/csv;charset=utf-8',
+    const blob = new Blob([String.fromCharCode(0xfeff), dataFrameCsv], {
+      type: 'text/csv;charset=utf-8',
     });
     const transformation = transformId !== DataTransformerID.noop ? '-as-' + transformId.toLocaleLowerCase() : '';
     const fileName = `${panel.title}-data${transformation}-${dateTimeFormat(new Date())}.csv`;

```
There is a hint in [FileSaver.js](https://github.com/eligrey/FileSaver.js/blob/5bb701bd6ea05a02836daf8ef88ec350a1dd4d83/src/FileSaver.js#L26)
