### ISSUE TITLE
Dashboard variables problem if Zabbix datasource selected

### ISSUE THREAD

**Issue by mariuskarotkis** [grafana/grafana#24928]
**What happened**:
When select data source zabbix than variable window gone

**How to reproduce it (as minimally and precisely as possible)**:
Dashboard settings --> Variables --> new
Select Data source: zabbix

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: zabbix
- OS Grafana is installed on: ubuntu
- User OS & Browser: chrome
- Grafana plugins: zabbix by Alexander Zobnin

**Comment by dprokop** [comment]
@alexanderzobnin is this something you could take a look at?

**Comment by dprokop** [comment]
@mariuskarotkis was there any output in the console?

**Comment by mariuskarotkis** [comment]
In console get errors:

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Cc (react-dom.production.min.js:273)
    at p (react-dom.production.min.js:143)
    at y (react-dom.production.min.js:146)
    at react-dom.production.min.js:150
    at Na (react-dom.production.min.js:172)
    at Su (react-dom.production.min.js:263)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121

**Comment by dprokop** [comment]
@mariuskarotkis and can you expand this error and the the entire stack trace with us? I've just tried to reproduce the problem, but it seems to work (classic ;)).

**Comment by mariuskarotkis** [comment]
```
Error: Minified React error #130; visit 
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Cc (react-dom.production.min.js:273)
    at p (react-dom.production.min.js:143)
    at y (react-dom.production.min.js:146)
    at react-dom.production.min.js:150
    at Na (react-dom.production.min.js:172)
    at Su (react-dom.production.min.js:263)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
(anonymous) @ app.41bc4b193210d0f899b3.js:2
c @ vendors~app.41bc4b193210d0f899b3.js:2
(anonymous) @ vendors~app.41bc4b193210d0f899b3.js:2
forEach.e.<computed> @ vendors~app.41bc4b193210d0f899b3.js:2
Le @ app.41bc4b193210d0f899b3.js:2
i @ app.41bc4b193210d0f899b3.js:2
Promise.then (async)
Le @ app.41bc4b193210d0f899b3.js:2
i @ app.41bc4b193210d0f899b3.js:2
Promise.then (async)
Le @ app.41bc4b193210d0f899b3.js:2
i @ app.41bc4b193210d0f899b3.js:2
(anonymous) @ app.41bc4b193210d0f899b3.js:2
(anonymous) @ app.41bc4b193210d0f899b3.js:2
(anonymous) @ app.41bc4b193210d0f899b3.js:2
(anonymous) @ vendors~app.41bc4b193210d0f899b3.js:2
(anonymous) @ vendors~app.41bc4b193210d0f899b3.js:2
value @ app.41bc4b193210d0f899b3.js:2
mc @ vendors~app.41bc4b193210d0f899b3.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.41bc4b193210d0f899b3.js:2
Wo @ vendors~app.41bc4b193210d0f899b3.js:2
gc @ vendors~app.41bc4b193210d0f899b3.js:2
ic @ vendors~app.41bc4b193210d0f899b3.js:2
(anonymous) @ vendors~app.41bc4b193210d0f899b3.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.41bc4b193210d0f899b3.js:2
Wo @ vendors~app.41bc4b193210d0f899b3.js:2
Xo @ vendors~app.41bc4b193210d0f899b3.js:2
Yo @ vendors~app.41bc4b193210d0f899b3.js:2
le @ vendors~app.41bc4b193210d0f899b3.js:2
Ar @ vendors~app.41bc4b193210d0f899b3.js:2
Dr @ vendors~app.41bc4b193210d0f899b3.js:2
kr @ vendors~app.41bc4b193210d0f899b3.js:2
ListPicker._handleMouseUp
```

**Comment by dprokop** [comment]
ok, thanks, we gonna investigate this

**Comment by yesoreyeram** [comment]
similar error happens to custom panels / datasources as well

**Comment by dprokop** [comment]
> similar error happens to custom panels / datasources as well

In what circumstances  @yesoreyeram ?

**Comment by yesoreyeram** [comment]
I have couple of custom database plugins https://github.com/yesoreyeram/grafana-azure-datasource and https://github.com/yesoreyeram/grafana-newrelic-datasource . Both plugins works fine with 6.x version. When updated to 7.0 the plugins editor panel throw the above mentioned error.  I have tried adding the `allow_loading_unsigned_plugins` config but still no luck.

Error in the datasource config page 

![image](https://user-images.githubusercontent.com/153843/82448737-0fe0ed80-9aa2-11ea-901d-d1e9a8da1296.png)

Error in the panel editor

![image](https://user-images.githubusercontent.com/153843/82448823-2b4bf880-9aa2-11ea-8dfa-9bfa70dfa366.png)

**Comment by waltenne** [comment]
I have same problem

**Comment by mac133k** [comment]
I have the same problem with Zabbix plugin only. I have Grafana v7.0.0 (aee1438ff2) installed on CentOS 7 and on my Windows laptop - both have the same problem with Zabbix plugin, however the plugin can still be used with panels and data is properly downloaded from Zabbix DB or API. Other plugins do not cause this issue.

**Comment by mac133k** [comment]
This issue seems to be gone after I upgraded Zabbix plugin from v3.11 to 3.12.
