### ISSUE TITLE
users with viewer role can change their usernames and names 

### ISSUE THREAD

**Issue by salehhoushangi** [grafana/grafana#24922]
**What happened**:
users with viewer role can change their usernames and names  from preferences.

**What you expected to happen**:
users with viewer role should not be able to change username and names.

**How to reproduce it (as minimally and precisely as possible)**:
disabling save button for  users with viewer's role.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0 Enterprise
- Data source type & version:
- OS Grafana is installed on: CentOS 8
- User OS & Browser: Windows 10, Chrome and Firefox
- Grafana plugins: Zabbix
- Others:

**Comment by peterholmberg** [comment]
Not a bug

**Comment by torkelo** [comment]
Just because a user is a viewer does not mean they cannot change their username or preferences. 

duplicate of this feature request: https://github.com/grafana/grafana/issues/18819
