### ISSUE TITLE
v7: Bar Gauge panel Field Data link variables no longer working

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#24927]
**What happened**:
On v6.7.2 I was using Data links on the Fields of a Bar Gauge without any problems (Prometheus Data Source) to show labels from my Prometheus config, so I could reference the following variables in BOTH the Title and the URL of the links:
`{__field.name} `
`{__field.labels.<whatever_label_name_I_want>}` e.g. `{__field.labels.location}`

But after upgrading to v7 the variables don’t seem to be resolved correctly.
`{__field.name}` is output as `{__field.name}` if put in the **Title** of the link but IS resolved correctly if put in the **URL**.

But variables such as `{__field.labels.location}` are not resolved in either, they just output as `{__field.labels.location}`

**What you expected to happen**:
Same behaviour as v6.7.2 - variables resolved correctly in both in the **Field** and **URL** parameters of field data links.

**How to reproduce it (as minimally and precisely as possible)**:
Add Grafana **Bar Gauge** panel.
Add Metric `probe_success` .
Go to **Field** tab.
Under **Data links** click on **Add link**.
In the URL field enter **$** and then select any "**Field labels.???**" that is shown.
Copy the value from **URL** into **Title**
Press **Save**
Click on a data item and look at the link **Title** and **URL**.

**Anything else we need to know?**:
The dashboard source is **Time series** and **Instant**:
`probe_success{location="Office"} and {type="Router"}`
Where **location** and **type** are labels defined in my prometheus.yml config.
In the Legend I can specify label variables without any issue with: **{{location}}** so I know the labels are being read from Prometheus by Grafana o.k.
Also if I enter **$** in the **URL** field Grafana shows a list of all the variables which include all the Prometheus labels.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: prometheus v2.7.1 blackbox-exporter v0.13.0
- OS Grafana is installed on: Ubuntu v19.10
- User OS & Browser: Ubuntu v20.04 Firefox v76.0.1
- Grafana plugins: 
- Others:

**Comment by gilkgit** [comment]
Except for the data link, the Display Name is also not interpolated, at least not for Table info query, so in practice, there's no way to change the Display Name for a bar to something meaningful (for a table input).

Repro:
Choose "Test Database" -> "Random Walk Table" for data source.
Choose "Bar Gauge" and set display name to "${__data.fields[Info]}"

the display name literally changes to "${__data.fields[Info]}" instead the values behind it


![image](https://user-images.githubusercontent.com/55378597/82757910-07fbb300-9dec-11ea-9cd9-f6eb0b01de56.png)
