### ISSUE TITLE
Dashboard schema migration should not be lazy

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#24932]
**What happened**:

Upgraded an instance from v6.1.4 to v7.0.0.
Opened a dashboard created on v6.1.4.
Dashboard schema was migrated, but only partially.
When navigating away from the dashboard, Grafana asks "Do you want to save your changes?"
Open the same dashboard, scroll down a little to bring more panels into view.
When navigating away from the dashboard, Grafana asks "Do you want to save your changes?" again.

**What you expected to happen**:

When a dashboard schema is migrated, it should happen all at once.

**How to reproduce it (as minimally and precisely as possible)**:

1. Import Tall Dashboard in Grafana v7.0.0: [Tall dashboard-1589979666772.zip](https://github.com/grafana/grafana/files/4656977/Tall.dashboard-1589979666772.zip)  
  It's just a vertical stack of 20 Graph panel sourcing TestData DB created on Grafana v6.1.4.
2. Navigate away and open it again.
3. Each time you open it, scroll down just a little more to show 1 or 2 more panels.
4. Every time you do this, you will be prompted to save the dashboard.

As long as you never scroll down to the bottom, some panels remain "unmigrated".

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.0
- Data source type & version: TestData DB (data source type is irrelevant)
- OS Grafana is installed on: Tested on Grafana Cloud and from local binary tarball extract.
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Migration is partly done during load and partly done as panels get loaded, panel & panel plugins are loaded async and during panel init the panel schema is upgraded as well, which is why schema is updated as you scroll. 

We plan to change how the ChangeTracker works in 7.1 or 7.2 to address this
https://github.com/grafana/grafana/issues/24663
