### ISSUE TITLE
Feature request: Ability to use time picker text string as a variable.

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#24934]
**What would you like to be added**:
I would like to be able to use the string shown in the **time picker** as a variable, specifically in panel titles. What I mean is the string which says `Last 2 days` or `Last 24 hours` etc.

**Why is this needed**:
If you have a dashboard where **some** panels use the time range but some use a fixed time range it would be nice to be able to title each panel appropriately. 

For example, I have a summary dashboard with various panels:
- Some panels show current (instant) status and are not affected by the time picker. 
- Some panels show the last 100 actions from some database and are not affected by the time picker. 
- Some panels show data for the time picker range.

This can be confusing to some users. I would like to be able to set a title on the panels which DO use the time range something like: `Hits for $TimeRangeText` so it would show as `Hits for Last 2 days` or `Hits for Last 24 hours` or whatever was picked so it is always obvious what data is being shown in every panel.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
