### ISSUE TITLE
Clarify Ability to Access Developer Mailing list

### ISSUE THREAD

**Issue by hdost** [grafana/grafana#24935]
**What would you like to be added**:
Instructions or information on who is allowed into the grafana developer group: https://groups.google.com/forum/#!forum/grafana-developers
* If it's to be open then it would be good to allow people in at least able to read. 

**Why is this needed**:
* It's currently a private mailing list.
* There's currently no way to know if/how you can get into the mailing list.
* It's mentioned as being :public" : https://github.com/grafana/grafana/blob/master/GOVERNANCE.md#voting

**Comment by hdost** [comment]
Still a present issue.

**Comment by RichiH** [comment]
Let me check

**Comment by RichiH** [comment]
Please try again. In the old UI, I was certain that I set it up correctly. In the new UI, I saw a dependency I was not aware of beforehand. Does it work, now?

**Comment by hdost** [comment]
Yes indeed :)
