### ISSUE TITLE
Disable profile editing when authenticated using LDAP

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#2493]
Including password. This is confusing for some of our users. Of course, the UI theme should be kept editable.

**Comment by michalbachowski** [comment]
Same for ``auth.proxy`` or any other auth type that creates accounts. Some indication that account is "external" might help I think.

**Comment by tsn77130** [comment]
Hi, is there something particular to do for using this function ?

I use v4.3.2, I have ldap.enabled = true , but I still have button "Forgot your password?" active, and I have "An email with a reset link as been sent to the email address.  You should receive it shortly." message when I try to reset password.

**Comment by torkelo** [comment]
Ldap can be combined with local grafana auth, no way currently to disable local grafana user / password auth

**Comment by taivorokib** [comment]
Is it possible to add conf parameter - no local users, then it could be disabled, couldn't it?

**Comment by flopp999** [comment]
I found this on github, but it doesn't seems to work in my setup.
Something I need to do in Grafana.ini to activate it?
https://github.com/grafana/grafana/blob/ffec795fab78527e8940e289579c39f88c5f2bd6/public/app/partials/reset_password.html#L8

**Comment by marefr** [comment]
@flopp999 you'll need to run a nightly build. It will be included in Grafana v6.0

**Comment by Jguer** [comment]
This has been implemented as of Grafana 9.x
