### ISSUE TITLE
Add centimeter (cm) length unit

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#24947]
**What would you like to be added**:
A centimeter (cm) suffix for length units.

**Why is this needed**:
centimeter is a commonly used and well known unit of measurement.

Note that this has previously been requested #21486, but was closed claiming that the custom unit functionality addresses this. **It does not**. If you use "cm" as a custom unit, grafana does not convert 100cm into 1m, or 10mm into 1cm. And trying to use `si:cm` gives you units such as `kcm` which is not a valid unit ("kilocentimeters", what?).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by d00m178** [comment]
Grafana 9.3.1 also doesn't have "cm" unit.
for example, data value is 0.27
using si:cm - shows "270 mcm" unit.
![image](https://github.com/grafana/grafana/assets/8877689/c8c17c0a-3935-48c2-b993-dc05b3ce0a1d)
