### ISSUE TITLE
grafana_stat_totals_dashboard also taking account folders

### ISSUE THREAD

**Issue by arnaudlemaignen** [grafana/grafana#24941]
**What happened**:
query the grafana_stat_totals_dashboard metric
it shows 82 dashboards when i have only 63 in reality because this metric is taking into account all type of dashboards with type="dash-db" and type="dash-folder"

**What you expected to happen**:
shows only 63 dashboards, only the ones with type="dash-db"
![image](https://user-images.githubusercontent.com/22667740/82464259-28f79780-9abe-11ea-9a0a-1c0166d6906c.png)

**How to reproduce it (as minimally and precisely as possible)**:
compare the grafana_stat_totals_dashboard value to the list of dashboards in http://<HOST>:<PORT>/api/search?query=% with the type="dash-db"

**Anything else we need to know?**:
Would it be possible to have another metric called grafana_stat_totals_folder which is providing the ones with type="dash-folder" ?
![image](https://user-images.githubusercontent.com/22667740/82463966-c7cfc400-9abd-11ea-8eb2-7fdd7b6ae161.png)

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: prometheus
- Others: grafana internal metrics

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
