### ISSUE TITLE
Username login form placeholder

### ISSUE THREAD

**Issue by Akeru** [grafana/grafana#2494]
Currently it displays "username or email", this is causing issues with the single bind ldap integration where binding is done only on the username (or the email for the matter). Don't know what would be best though : customizable ? empty ?

**Comment by tmonk42** [comment]
I whipped something up because I agree this is a great usability feature. It's not exclusive to LDAP, so I put the config option in the Users section.

**Comment by kdeldycke** [comment]
:+1:
