### ISSUE TITLE
Tech: Improve autocomplete architecture for data source query editors.

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#24959]
In multiple query editors and some other features we use text input field with autocomplete functionality.

This is implemented with [prismjs](https://prismjs.com/) which is library to define syntax highlighting with regex patterns and with custom regex matching. This means autocomplete is very error prone due to complex regex patterns or traversing linear list of tokens provided by prism.

Better approach would be to have full language parser ideally generated from something like an EBNF document that would provide AST and allow to implement more robust and useful suggestions especially for more complex query languages.

We already try to do that to some extent with CloudWatch [here](https://github.com/grafana/grafana/pull/24789)

There are few things to consider:
- query parsing is used also for some other functionality, for example in CloudWatch we are detecting group fields as we have to group the time series after we get them from the server. This means we may need some parsing functionality also on backend to support any alerting needs.
- the general interface for autocomplete should ideally conform to [language server protocol](https://microsoft.github.io/language-server-protocol/) so any implementation on Grafana side could be exchanged for server implementation in the data source.

**Comment by ryantxu** [comment]
Any thoughts on monoco?  This is what influx uses in chronograph:
https://github.com/Microsoft/monaco-editor
https://github.com/react-monaco-editor/react-monaco-editor

**Comment by aocenas** [comment]
@ryantxu as we talked yesterday I will have to take a closer look but I think for most cases the Monaco editor may not help us that much. The thing is with unsupported languages we will probably have to do the implementation of the LSP which still means some sort of grammar -> parser -> AST -> suggestions. For languages supported out of the box with Monaco there may be more benefits.

Other question is general text editing capabilities and keybindings whether they are better in Monaco than what we have now.

If we implement the autocomplete logic via LSP we can approach this separately and still improve the autocomplete experience with current Slate editor and probably switch to Monaco later on if needed.

**Comment by aocenas** [comment]
Closing as there are separate issues for this in progress
