### ISSUE TITLE
Prometheus datasource "Grafana metrics" dashboard uses old grafan_info metric

### ISSUE THREAD

**Issue by kyrias** [grafana/grafana#24952]
**What happened**:
https://github.com/grafana/grafana/commit/75fa1f0207f539c34e2e674ac04bd2c01db278c1 / #18134 removed the `grafana_info` metric, which is still used by the built-in Grafana metrics dashboard: https://github.com/grafana/grafana/blob/8aedf8113371f933b8afcafe7a392641fda69f47/public/app/plugins/datasource/prometheus/dashboards/grafana_stats.json#L442-L452

**What you expected to happen**:
It should use the metric that still exists.

**How to reproduce it (as minimally and precisely as possible)**:
Import the default "Grafana metrics" dashboard that is distributed with the Prometheus datasource.

**Anything else we need to know?**:
https://github.com/grafana/grafana/commit/75fa1f0207f539c34e2e674ac04bd2c01db278c1

**Environment**:
- Grafana version: 7.0.0

**Comment by marefr** [comment]
@kyrias would you be interested in opening a PR to fix this?
