### ISSUE TITLE
 Reduce tranformations shows incorrect values

### ISSUE THREAD

**Issue by yuvarajhere** [grafana/grafana#24950]
Adding more info to issue https://github.com/grafana/grafana/issues/24893

**What happened**:  While transforming the output using reduce function, it performs the operation selected in Panel display function irrespective of option(s) selected in reduce function.

Find the below screen capture (The given outputs are 1 and 0.5).
<img width="1439" alt="Screen Shot 2020-05-20 at 2 21 04 PM" src="https://user-images.githubusercontent.com/29648850/82477440-de6a2100-9aa5-11ea-9e70-44ac802f11bc.png">

**What you expected to happen**:  Actual calculated values based on selected function.

**How to reproduce it (as minimally and precisely as possible)**: 
- Add two query with different values [vector(1) and vector(2)]
- Change the visualization to stat.
- Click transformation and select reduce.
- Select any math function (more than one). It will display the values calculated with default 'Mean' option or selected display function.

**Anything else we need to know?**: It only works when we update the function to same as the selected value.

<img width="1425" alt="Screen Shot 2020-05-20 at 2 18 12 PM" src="https://user-images.githubusercontent.com/29648850/82477629-1a04eb00-9aa6-11ea-8944-f593d6dc4de5.png">

<img width="1438" alt="Screen Shot 2020-05-20 at 3 42 14 PM" src="https://user-images.githubusercontent.com/29648850/82484615-8be23200-9ab0-11ea-887e-e11c8cf816d8.png">

Transformation output data:
`Array[1]
0:Object
name:undefined
refId:"A"
meta:Object
preferredVisualisationType:"graph"
transformations:Array[242]
0:"reduce"
1:"reduce"
2:"reduce"
3:"reduce"
4:"reduce"
5:"reduce"
6:"reduce"
7:"reduce"
8:"reduce"
9:"reduce"
10:"reduce"
11:"reduce"
12:"reduce"
13:"reduce"
14:"reduce"
15:"reduce"
16:"reduce"
17:"reduce"
18:"reduce"
19:"reduce"
20:"reduce"
21:"reduce"
22:"reduce"
23:"reduce"
24:"reduce"
25:"reduce"
26:"reduce"
27:"reduce"
28:"reduce"
29:"reduce"
30:"reduce"
31:"reduce"
32:"reduce"
33:"reduce"
34:"reduce"
35:"reduce"
36:"reduce"
37:"reduce"
38:"reduce"
39:"reduce"
40:"reduce"
41:"reduce"
42:"reduce"
43:"reduce"
44:"reduce"
45:"reduce"
46:"reduce"
47:"reduce"
48:"reduce"
49:"reduce"
50:"reduce"
51:"reduce"
52:"reduce"
53:"reduce"
54:"reduce"
55:"reduce"
56:"reduce"
57:"reduce"
58:"reduce"
59:"reduce"
60:"reduce"
61:"reduce"
62:"reduce"
63:"reduce"
64:"reduce"
65:"reduce"
66:"reduce"
67:"reduce"
68:"reduce"
69:"reduce"
70:"reduce"
71:"reduce"
72:"reduce"
73:"reduce"
74:"reduce"
75:"reduce"
76:"reduce"
77:"reduce"
78:"reduce"
79:"reduce"
80:"reduce"
81:"reduce"
82:"reduce"
83:"reduce"
84:"reduce"
85:"reduce"
86:"reduce"
87:"reduce"
88:"reduce"
89:"reduce"
90:"reduce"
91:"reduce"
92:"reduce"
93:"reduce"
94:"reduce"
95:"reduce"
96:"reduce"
97:"reduce"
98:"reduce"
99:"reduce"
100:"reduce"
101:"reduce"
102:"reduce"
103:"reduce"
104:"reduce"
105:"reduce"
106:"reduce"
107:"reduce"
108:"reduce"
109:"reduce"
110:"reduce"
111:"reduce"
112:"reduce"
113:"reduce"
114:"reduce"
115:"reduce"
116:"reduce"
117:"reduce"
118:"reduce"
119:"reduce"
120:"reduce"
121:"reduce"
122:"reduce"
123:"reduce"
124:"reduce"
125:"reduce"
126:"reduce"
127:"reduce"
128:"reduce"
129:"reduce"
130:"reduce"
131:"reduce"
132:"reduce"
133:"reduce"
134:"reduce"
135:"reduce"
136:"reduce"
137:"reduce"
138:"reduce"
139:"reduce"
140:"reduce"
141:"reduce"
142:"reduce"
143:"reduce"
144:"reduce"
145:"reduce"
146:"reduce"
147:"reduce"
148:"reduce"
149:"reduce"
150:"reduce"
151:"reduce"
152:"reduce"
153:"reduce"
154:"reduce"
155:"reduce"
156:"reduce"
157:"reduce"
158:"reduce"
159:"reduce"
160:"reduce"
161:"reduce"
162:"reduce"
163:"reduce"
164:"reduce"
165:"reduce"
166:"reduce"
167:"reduce"
168:"reduce"
169:"reduce"
170:"reduce"
171:"reduce"
172:"reduce"
173:"reduce"
174:"reduce"
175:"reduce"
176:"reduce"
177:"reduce"
178:"reduce"
179:"reduce"
180:"reduce"
181:"reduce"
182:"reduce"
183:"reduce"
184:"reduce"
185:"reduce"
186:"reduce"
187:"reduce"
188:"reduce"
189:"reduce"
190:"reduce"
191:"reduce"
192:"reduce"
193:"reduce"
194:"reduce"
195:"reduce"
196:"reduce"
197:"reduce"
198:"reduce"
199:"reduce"
200:"reduce"
201:"reduce"
202:"reduce"
203:"reduce"
204:"reduce"
205:"reduce"
206:"reduce"
207:"reduce"
208:"reduce"
209:"reduce"
210:"reduce"
211:"reduce"
212:"reduce"
213:"reduce"
214:"reduce"
215:"reduce"
216:"reduce"
217:"reduce"
218:"reduce"
219:"reduce"
220:"reduce"
221:"reduce"
222:"reduce"
223:"reduce"
224:"reduce"
225:"reduce"
226:"reduce"
227:"reduce"
228:"reduce"
229:"reduce"
230:"reduce"
231:"reduce"
232:"reduce"
233:"reduce"
234:"reduce"
235:"reduce"
236:"reduce"
237:"reduce"
238:"reduce"
239:"reduce"
240:"reduce"
241:"reduce"
fields:Array[2]
0:Object
name:"Field"
type:"string"
values:t
buffer:Array[2]
0:"Value {}"
1:"Value {}"
config:Object
1:Object
name:"max"
type:"number"
values:t
buffer:Array[0.5,1]
config:Object
displayName:"Max"
length:2`

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: NA
- User OS & Browser: MacOS Mojave & Firefox
- Grafana plugins: NA
- Others: NA

**Comment by torkelo** [comment]
Can you show the result of your query with table panel before and after reduce being added?

**Comment by yuvarajhere** [comment]
**BEFORE adding reduce transformation:**

<img width="680" alt="Screen Shot 2020-05-21 at 11 54 26 AM" src="https://user-images.githubusercontent.com/29648850/82574894-251b5200-9b5e-11ea-8430-b81159c9aa1f.png">
<img width="679" alt="Screen Shot 2020-05-21 at 11 54 36 AM" src="https://user-images.githubusercontent.com/29648850/82574902-28164280-9b5e-11ea-8918-7e2808a73181.png">
<img width="679" alt="Screen Shot 2020-05-21 at 11 54 48 AM" src="https://user-images.githubusercontent.com/29648850/82574910-2a789c80-9b5e-11ea-8c77-501e34a87652.png">

**AFTER Reduce in table panel:**
<img width="680" alt="Screen Shot 2020-05-21 at 11 55 10 AM" src="https://user-images.githubusercontent.com/29648850/82574916-2c426000-9b5e-11ea-9d5b-c5736ebf6f15.png">

_So, it reduces the data points of a single query output to one data point and not cumulative of multiple queries?_

**Comment by ryantxu** [comment]
If you add the join transformer before your reduce, is that what you are after?

**Comment by yuvarajhere** [comment]
Yes, that's correct. Please find the below screen captures.

Before:
<img width="1030" alt="Screen Shot 2020-05-21 at 5 01 49 PM" src="https://user-images.githubusercontent.com/29648850/82600838-ecdb3a00-9b84-11ea-821f-0d1f2c7bb634.png">

After:
<img width="1029" alt="Screen Shot 2020-05-21 at 5 02 16 PM" src="https://user-images.githubusercontent.com/29648850/82600843-eea4fd80-9b84-11ea-9266-397fc13da5b6.png">

**Comment by peterholmberg** [comment]
Looks like this is solved? Reopen if not

**Comment by dmarteau** [comment]
This issue appears not to be solved. 

When editing values are ok, but when refreshing the dashboard then all values changes to the raw input values without applying any reduction calculation

Grafana version: 8.3.4
