### ISSUE TITLE
Unable to translate notification id to uid

### ISSUE THREAD

**Issue by treverj** [grafana/grafana#24969]
**What happened**:
When attempting to edit a dashboard (any edit, doesn't have to be alert specific), and then save, we get the following error: 

> Alert validation error: Unable to translate notification id to uid, Alert notification [ id: 46, OrgId:1 ] not found PanelId: 76 DashboardId: 720

![image](https://user-images.githubusercontent.com/20922917/82536414-538a3480-9b40-11ea-829a-88fbd626ef11.png)

**What you expected to happen**:
The dashboard to save successfully

**How to reproduce it (as minimally and precisely as possible)**:
We have recently upgraded from Grafana 6.6.2-Ubuntu to 7.0.0-Ubuntu Docker images (Postgres to store dashboard) and trying to edit and then save any dashboard with alerts throws this error

**Anything else we need to know?**:
Let me know if you need any more details around the dashboard or alerts in the DB

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit  
- OS Grafana is installed on: CentOS 7 using Grafana Ubuntu Docker version 7.0.0
- User OS & Browser: Chrome - Mac and Windows
- Grafana plugins: WorldPing
- Others:

**Comment by kumode** [comment]
In the dashboard JSON try to locate this object:

            "notifications": [
              {
                "id": 46
              },

Remove the { "id": 46 }, and you should be able to save the dashboard. This issue drove me nuts for almost 2 hours.

**Comment by treverj** [comment]
Thanks @kumode, do you know why this is happening? We are seeing this across many dashboards with alerts (We have many and haven't manually checked all 250). Not really looking forward to going and doing this to every dashboard that we have so wondered if there was an automatic solution.

**Comment by kumode** [comment]
I'm unsure whether you have the same problem or not, but we had notifications set up on our old grafana instance, then we migrated to CENTOS and it appears that starting from 7.0.0. this "legacy" bit of notification code started to become a problem.

**Comment by kylebrandt** [comment]
Possibly changes around https://github.com/grafana/grafana/pull/19882 , :eyes:

**Comment by kylebrandt** [comment]
Path:

https://github.com/grafana/grafana/blob/21425f7e26607ecad7690d186c5c30f9f1389041/pkg/services/alerting/rule.go#L138-L144

https://github.com/grafana/grafana/blob/21425f7e26607ecad7690d186c5c30f9f1389041/pkg/services/alerting/rule.go#L175-L183

https://github.com/grafana/grafana/blob/21425f7e26607ecad7690d186c5c30f9f1389041/pkg/services/sqlstore/alert_notification.go#L74-L90

Then, **caching aside** (and maybe a caching logic issue, need to keep investigating):

https://github.com/grafana/grafana/blob/21425f7e26607ecad7690d186c5c30f9f1389041/pkg/services/sqlstore/alert_notification.go#L153-L180

**Comment by treverj** [comment]
Thanks @kylebrandt, let me know if you need any more information or need me to retest a new build etc, happy to help 😃

**Comment by kylebrandt** [comment]
Also noticed a frontend change in notifications list that adds a new type AlertNotification, not sure if that might be related? https://github.com/grafana/grafana/pull/22548/files

**Comment by papagian** [comment]
@treverj 
can you navigate in Alert notifiers page and check the response of the `api/alert-notifications` (in developer tools network tab)?
Is there a notification with with id `46`?

**Comment by treverj** [comment]
Hi Papagian,

Apologies for the late reply, missed your response. 

No, there isn't one with id `46`. 

I think what may be the issue is that there are dashboards referring to notification channels that have now been deleted and the dashboards have not been updated to remove those. Think there is an expectation that if you delete a channel, all dashboard referring to them will be updated or handle this gracefully (which they seem to do historically). When looking at the alerts for a panel, I can see in the JSON data, that there is a reference to 46 but the UI does not show this to be able to delete this manually if this is the expectation.  

Screenshot below:
![image](https://user-images.githubusercontent.com/20922917/83130020-91a1ce00-a0d5-11ea-87bd-308f0382fdbd.png)

This shows id 46 in the panel JSON, but the alerts tab shows 1 alert but doesn't show any channels (as this channel must have been deleted historically)

**Comment by treverj** [comment]
Is there a planned fix for this as currently there isn't a warning when deleting notification channels that are in use so asking the user to go back and potentially tidy up 100s of broken dashboards JSON files seems like an odd solution when there isn't any warning in the first place when deleting the notification channels.

**Comment by papagian** [comment]
@treverj there are fixes for [silencing this error](25302) and [asking for confirmation](https://github.com/grafana/grafana/pull/25303) before deleting notification channels included in grafana version `7.0.3`.

**Comment by treverj** [comment]
That is fantastic. Thanks for sorting 👍
