### ISSUE TITLE
apt will not upgrade from beta to stable

### ISSUE THREAD

**Issue by earwin** [grafana/grafana#24961]
**What happened**:
When using both _beta_ and _stable_ ubuntu (debian) repositories,
Move from 7.0.0-betaN to 7.0.0 is considered a downgrade and would not happen automatically.

**What you expected to happen**:
`apt install grafana` to upgrade from beta to stable

**How to reproduce it (as minimally and precisely as possible)**:
1. Add both _beta_ and _stable_ deb repositories to apt _sources.list_
2. `apt install grafana=7.0.0-beta3`
3. `apt install grafana`

**Anything else we need to know?**:
According to [Debian version rules](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version), `7.0.0-whatever` sorts after `7.0.0`.
What you want to do, is to use `~`, e.g. `7.0.0~beta3`. This will sort after `6.x.x`, but before `7.0.0`

**Comment by aknuds1** [comment]
Thanks for reporting this! I will look into it.

**Comment by aknuds1** [comment]
Looks like you're right, from reading the version comparison specs:

> One common use of ~ is for upstream pre-releases. For example, 1.0~beta1~svn1245 sorts earlier than 1.0~beta1, which sorts earlier than 1.0.

**Comment by earwin** [comment]
An easy way to visualize this, is to look at package version list in aptitude:
<img width="129" alt="Screen Shot 2020-05-21 at 01 46 30" src="https://user-images.githubusercontent.com/299579/82563454-c8c92a00-9b7f-11ea-993a-2145f1079ffa.png">

**Comment by aknuds1** [comment]
I've made a fix for the issue, the current target is v7.1. I'm right in thinking this issue should be resolved with version 7.0.1 right? Thanks again for reporting the problem!

**Comment by earwin** [comment]
@aknuds1 Yup, you are right, `7.0.1` will get installed over `7.0.0-betaN` as intended. Cheers!

**Comment by aknuds1** [comment]
This issue should be fixed, as we now generate Debian packages with `~` as separator for an eventual pre-release component in package names.
