### ISSUE TITLE
How grafana deal with Coordinated Omission ?

### ISSUE THREAD

**Issue by baiwfg2** [grafana/grafana#24964]
**What would you like to be added**:
A way for measuring latency to avoid coordinated omission

**Why is this needed**:
Recently I've learnt latency measurement from Gil Tene's talk. To my surprise,  the methods of many tools for measuring operation latency is not that right. He said many load generators, monitoring tool don't perform a good job for dealing with coordinated omission. Grafana, I don't know, has this problem ? To the following graph, Gil said: it has omitted important information and nearly useless, is that true in grafana ?

![image](https://user-images.githubusercontent.com/5157680/82515541-052e6300-9b4b-11ea-9c70-420cb91e4844.png)

**Comment by jangaraj** [comment]
It depends how user will configure that latency graph. Use MAX function instead of PERCENTIL and you will see also the worst latencies in that graph. 

It isn't real Grafana issue, but user responsibility to understand metrics and represented them in the best way for certain use case.

**Comment by torkelo** [comment]
closing this as it does not seem like a Grafana issue
