### ISSUE TITLE
Defer data loading

### ISSUE THREAD

**Issue by michalbachowski** [grafana/grafana#2496]
In case of really huge dashboards, containing dozens of graphs (which is really easily achievable with row-repeat and panel-repeat), loading all data for all graphs might not be desirable.
Could you provide a way to optionally defer loading of data for panels until user will scroll to actually view those panels.

**Comment by mtanda** [comment]
Intersection Observer is useful for implementing this feature.
http://caniuse.com/#feat=intersectionobserver

**Comment by mtanda** [comment]
resolved by https://github.com/grafana/grafana/pull/7452
