### ISSUE TITLE
The time displayed by jaeger is not normal.

### ISSUE THREAD

**Issue by lut777** [grafana/grafana#24965]
**What happened**:

When I select the TRACING content via the drop-down box, the time shown by the options in the third column drop-down box is not normal. The time units should look like microseconds.

While The time shown in the tracing results below is correct. 

**What you expected to happen**:

The display time should be xxxx microseconds, or xx.xx milliseconds, or can be customized either way.

**How to reproduce it (as minimally and precisely as possible)**:

Import cloud-jaeger, configure the data source, and click the traces button to select traces.

**Anything else we need to know?**:

No.

**Environment**:
- Grafana version:  V7.0
- Data source type & version:  jaeger-1.14.0
- OS Grafana is installed on: Linux
- User OS & Browser: firefox
- Grafana plugins:
- Others:

**Comment by Estrax** [comment]
Can confirm. The duration returned by jaeger is in a microseconds precision. Right now we display that value in our cascader options.

Cascader:
![Screenshot from 2020-05-27 00-43-14](https://user-images.githubusercontent.com/6322797/82957448-455e6d00-9fb3-11ea-8104-cd081d78898a.png)

Result:
![Screenshot from 2020-05-27 00-43-53](https://user-images.githubusercontent.com/6322797/82957452-47c0c700-9fb3-11ea-9ae1-042d36369067.png)
