### ISSUE TITLE
View/Edit Panel: Unable to view / edit panel in collapsed row 

### ISSUE THREAD

**Issue by kumode** [grafana/grafana#24972]
**What happened**: If you attempt to open an alert from Alerting: Alert Rules and the panel is hidden with a closed row it results in an error: Panel with id ## not found (id = numeric value of the panel id).

**What you expected to happen**: The ability to edit the alert rules, panel opens without any issues.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel with alert rule.
2. Place it in a row
3. Close the row
4. Try to access the alert rule from Alerting: Alert Rules
5. Receive error

**Anything else we need to know?**:
If you open the row, you can access the panel without any issues.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus / Elasticsearch
- OS Grafana is installed on: CENTOS
- User OS & Browser: Win10, Chrome latest
- Grafana plugins: -
- Others: -

**Comment by kumode** [comment]
In fact even when using Alert List inside the dashboard, if the panel is hidden in a closed row, error still persists.

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by christophsobel** [comment]
The same problem applies to the "panel->share->link" function.
However the "panel->share->embed" function is working with hidden row still and shows no error.
