### ISSUE TITLE
Transforms & Table Panel: Organize fields does not reorder Reduced fields

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24974]
**What happened**:

![image](https://user-images.githubusercontent.com/2898361/82543086-dcbb5e80-9b74-11ea-96f3-b3bf74da2958.png)

**What you expected to happen**:

Reorganized fields

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Thanks, @baur! This is a bug, indeed. Good catch.
