### ISSUE TITLE
Grafana 7 table doesn't support paging

### ISSUE THREAD

**Issue by karlie93** [grafana/grafana#24971]
**What would you like to be added**:

Table custom paging function

**Why is this needed**:
Grafana 6.6.2 table support paging,it very useful for us,but grafana 7 doesn't support it.
Can you add this feature.Thanks

grafana 6.6.2
The form does not support paging
![image](https://user-images.githubusercontent.com/54050952/82538893-06798300-9b7f-11ea-9f09-e1f74e9a206b.png)

**Comment by dprokop** [comment]
@karlie93 in 7.0 we decided to use infinite scroll instead as it makes it easier to navigate through the data. We do not have plans of bringing back paging.

**Comment by olafschmidt** [comment]
This is really a bad design decision and from UX perspective a nightmare when dealing with large tables. Overall, the new table panel is an example for making good things worse.

**Comment by Shenkey** [comment]
I think this is a needed feature may be as optional. My InfluxDB contains 450k records for 5 days time range selection and when I query it crashes/fails for 5 days.
When I tried to query the InfluxDB data for 5 days from a middleware nodejs app with Simpod-JSON datasource, the app crashes giving below error:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

If we had an option to limit the number of records per page, then we would have been able to query for each page somehow and systems wouldn’t have to keep all those big data buffered in memory or crash.
