### ISSUE TITLE
CloudWatch Logs MalformedQueryException

### ISSUE THREAD

**Issue by markuman** [grafana/grafana#24975]
**What happened**:

`Metric request error` when explore `CloudWatch Logs`.

**What you expected to happen**:

See the cloudwatch logs

**How to reproduce it (as minimally and precisely as possible)**:

Select any CloudWatch Log Group.

**Anything else we need to know?**:

```
t=2020-05-21T10:03:12+0000 lvl=eror msg="Metric request error" logger=context userId=2 orgId=1 uname=myuser error="MalformedQueryException: mismatched input '|' expecting K_STATS (Service: AWSLogs; Status Code: 400; Error Code: MalformedQueryException; Request ID: 278c5dcb-ecdb-4d26-948f-93b1a6e82ff2)\n{\n  Message_: \"mismatched input '|' expecting K_STATS (Service: AWSLogs; Status Code: 400; Error Code: MalformedQueryException; Request ID: 278c5dcb-ecdb-4d26-948f-93b1a6e82ff2)\"\n}" remote_addr=10.103.11.2

```

**Environment**:
- Grafana version: 7.0.0

**Comment by markuman** [comment]
Ok, i figured out that I have to apply at least one filter.

**Comment by triwats** [comment]
I came across this too. Ensure that you are selecting the timeframe again to ensure it does a fresh query. You need a fully structured query for this to work, try this one:

```
fields @timestamp, @message
| sort @timestamp desc
| limit 20```
