### ISSUE TITLE
Auto-refresh does not accept less then 5s 

### ISSUE THREAD

**Issue by suikast42** [grafana/grafana#24982]
![image](https://user-images.githubusercontent.com/5046525/82560979-c7ddcb80-9b72-11ea-811e-9c01fb6f0bdd.png)

![image](https://user-images.githubusercontent.com/5046525/82561006-d75d1480-9b72-11ea-8f40-df60c3c37931.png)

**Environment**:
- Grafana version: 7.0
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Centos/8
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
There is a server setting for min refresh interval, check docs for min refresh interval (written from mobile)

**Comment by byteptr** [comment]
Same issue for Grafana 8.8.3 even if min_refresh_interval on grafana.ini is set to less than 5s
