### ISSUE TITLE
CloudWatch: Configuration page does not show banner about data source being provisioned

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#24985]
When data source is provisioned, we show a banner on top explaining that you cannot alter such data source (though the save button is still there, which is separate issue).
![Screenshot from 2020-05-21 15-41-57](https://user-images.githubusercontent.com/1014802/82565152-3a05de80-9b7a-11ea-891c-a89bc91e3370.png)

In CloudWatch though we do not show this.
![Screenshot from 2020-05-21 15-41-50](https://user-images.githubusercontent.com/1014802/82565184-4853fa80-9b7a-11ea-8092-bbcd3ae9bf19.png)

The banner should be shown consistently for all data sources.

**Comment by marefr** [comment]
@aocenas are you sure `editable: true` is not set for provisioned cloudwatch data source?

**Comment by aocenas** [comment]
@marefr you are right but it still did not allow me to edit it. So maybe this is actually a bug with the editable attribute? I think I saw a report like that somewhere.

**Comment by marefr** [comment]
@aocenas I can edit and save using devenv cloudwatch: https://github.com/grafana/grafana/blob/f98e176d7be9eab14b20529767465eed1534a8f4/devenv/datasources.yaml#L223-L228
