### ISSUE TITLE
Transform: Cannot enter numeric value for binary operation

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#24988]
In 7.0 I am trying to use an "Add field from calculation" transform to scale a value.  What I would like to do is to use a "Binary operation" to multiply a field by 1.04

When I try to enter a numeric value in either of the "Field or number" inputs I get a dropdown saying "No options found" and when the input loses focus it returns to the previous value (either empty or a selected field).

![image](https://user-images.githubusercontent.com/1443603/82567831-eda3aa00-9b4b-11ea-9c60-c2fd3594470b.png)

**Comment by ryantxu** [comment]
Fixed by https://github.com/grafana/grafana/pull/24752
