### ISSUE TITLE
PanelHeader: Support showing menu ontop of absolute positioned menu 

### ISSUE THREAD

**Issue by KamalGalrani** [grafana/grafana#24986]
**What happened**:
When I open the context menu and hover on the item which is on another panel's header, it gets hidden behind header
![image](https://user-images.githubusercontent.com/2345081/82566666-e0151100-9b99-11ea-8540-bc00aaaed605.png)

**Environment**:
- Grafana version: master (commit: 44ca05272a2e70417341825722f5f4e61c388fc1)
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 16.04, Chrome

**Comment by ryantxu** [comment]
This seems fixed in main -- still weird that it keeps the menu open after you open anothr one... but position seems fixed:
![image](https://user-images.githubusercontent.com/705951/120559893-b3075b00-c3b6-11eb-9921-dcb5db12d97b.png)
