### ISSUE TITLE
Create new playlist button shouldn't be visible for user with viewer role on playlists page

### ISSUE THREAD

**Issue by thedeepc** [grafana/grafana#24987]
**What happened**:
We have our **unauthenticated** user set to "Viewer" permission level. Within Grafana, the user is able to navigate into the left-side menu items. Relevant here are the routes `playlists` and `dashboard/snapshots`, where the user may view their respective contents. The issue is that the calls to the server either prevent them from creating a new / manipulating old playlists (for `playlists` route), or present them with an empty list of snapshots (for `dashboards/snapshots` route, even when existing snapshots are purely local snapshots). The `playlists` case is met with a "403 Forbidden" with response data `{message: "Permission denied"}`.
**What you expected to happen**:
Given that the **unauthenticated** user can view these areas, we expected them to be able to see the list of existing snapshots and/or be able to create/manipulate playlists.
**How to reproduce it (as minimally and precisely as possible)**:
Set **unauthenticated** user in custom.ini or default.ini to have the "Viewer" permission level by setting `org_role = Viewer`. Attempt to create a playlist or view existing snapshots from existing dashboards.
**Anything else we need to know?**:
n/a
**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus 2.13.1
- OS Grafana is installed on: Windows Server 2012
- User OS & Browser: Windows Server 2012 & Google Chrome 81.0.4404.122
- Grafana plugins:
- Others:

EDIT: Used the word "unauthorized" rather than "unauthenticated".

**Comment by aknuds1** [comment]
Can you try this with v7.0.0 also and see if it persists?

**Comment by thedeepc** [comment]
@aknuds1 Thanks for the suggestion. I updated to v7.0.0 and the issue persists.

**Comment by aknuds1** [comment]
We'll need to investigate if disallowing viewing of snapshots by the backend is a bug or not.

**Comment by marefr** [comment]
Viewing snapshots and creating playlists should not be allowed. The bug here seems to be that the create new playlist button is visible so will change title to reflect this.

**Comment by thedeepc** [comment]
I'd like to add that the Viewer user is also able to see the available plugin list, which I don't think is correct for that level of permissions.
