### ISSUE TITLE
BUG: added 'support' for browser detection generating false positives (of course)

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#24981]
https://github.com/grafana/grafana/issues/24743#issue-619110199

**Comment by aknuds1** [comment]
Please write a full issue description, using the standard template.

**Comment by f1-outsourcing** [comment]
you have to reopen the other one.

**Comment by aknuds1** [comment]
I suggest you either make a new issue, using the standard issue template (which you failed to do in the other issue).

**Comment by f1-outsourcing** [comment]
I don't think changing the layout will make much difference, especially when 'under qualified' people are handling issues and closing them because it is above their knowledge. All the necessary info is there.
