### ISSUE TITLE
Text Panel: Moving panel options as Right side pane makes it harder to edit Text panel HTML

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#24995]
**What happened**:
I have dashboard with various combinations of Template Variables, ad-hoc filters. I have documented the use of this dashboard using Text Panel with HTML mode. It used to work well earlier. BUT with 7.0.0, right side panel option, it becomes harder to edit the HTML.

![image](https://user-images.githubusercontent.com/14235758/82593265-d5418880-9b67-11ea-9354-712d0b5e9a24.png)

I can not resize the pane, to get the wider space for editing the HTML. The divider is not visible and I can not do any resizing at all.
https://play.grafana.org/d/000000172/text-panel?editPanel=1&orgId=1&var-ABC%5B%5D=Cluster%7C%3D%7CUnited%20States&var-ABC%5B%5D=Server%7C%3D%7CBackend_server20&var-ABC%5B%5D=metrics%7C%3D%7C434934

The editor does not show the entire HTML..
![image](https://user-images.githubusercontent.com/14235758/82593430-1fc30500-9b68-11ea-944b-a7da75554df6.png)

**What you expected to happen**:
Ability to allow resizing of the panel to easy update the HTML for the Text Panel.

**What else we should know**:
Add enough Filters to dashboard, before reproducing the issue.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: NA
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins: Text Panel
- Others:

**Comment by torkelo** [comment]
Thanks for the feedback! 

The text panel input area needs to support line wrapping, will make sure we do that when we update this panel added 
it as a todo here https://github.com/grafana/grafana/issues/25004

We also need to fix the flow logic of variables in edit mode
