### ISSUE TITLE
Explore mode PromQL query must contain metric name

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#24997]
**What happened**:

Trying to get the list of biggest metrics on a Cloud Prometheus instance as described here:
https://www.robustperception.io/which-are-my-biggest-metrics

Using this query: `topk(10, count by (__name__)({__name__=~".+"}))`

It works in Prometheus, but Grafana Explore returns the error message: "query must contain metric name".

**What you expected to happen**:

Getting a list of metric names sorted by cardinality.

**How to reproduce it (as minimally and precisely as possible)**:

Paste this query in Explore mode on any Prometheus data source.

**Anything else we need to know?**:

Workaround is to query the Cortex API directly.

```
login="-u <instance_id>:<grafana.com_API_token>"
url=https://prometheus-us-central1.grafana.net/api/prom

curl -s $login $url/api/v1/label/__name__/values | jq -r ".data[]" \
| while read metric; do
    echo $(curl -s $login $url/api/v1/series -d "match[]=$metric" | jq -r ".data|length") $metric
  done \
| sort -n
```

**Environment**:
- Grafana version: v6.x and v7.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Estrax** [comment]
Strange; wasn't able to reproduce that on 6.7.x and 7.0 - works flawlessly on my end, as well as on play.

**Comment by ivanahuckova** [comment]
I wasn't able to reproduce this as well on Grarana 6.6 and Grafana 7:
![image](https://user-images.githubusercontent.com/30407135/82813202-e30f4a80-9e94-11ea-8644-48ea47140dcd.png)
![image](https://user-images.githubusercontent.com/30407135/82813291-0c2fdb00-9e95-11ea-8391-ac6c0395574e.png)

**Comment by Tomica-G** [comment]
I've tested this today as well and ended up with the same error. I've tested pon the Grafana Cloud and a local instance.
However, it worked when I tested it on play. It looks like it's happening only when querying against the Cortex instance on our end.

**Comment by anelson** [comment]
Hi @Tomica-G I assume you're the same Tomica who is assigned my Grafana Cloud support case related to this issue :wave: 

This is particularly inconvenient in my case because I've gone way over the 3000 active series limit and I don't have a good way to find out what metrics are the worst offenders.

**Comment by ivanahuckova** [comment]
Yeah @Tomica-G, good catch. I get _query must contain metric name_ error only when querying against Cortex as well.

**Comment by Estrax** [comment]
Can confirm after investigation - works flawlessly when querying Prometheus and fails when querying Cortex - not sure if that's really a Grafana issue then.

**Comment by Estrax** [comment]
@Tomica-G @adeverteuil got a confirmation from David - it's not a Grafana issue, but the Cortex protection against expensive queries.

**Comment by anelson** [comment]
@Estrax is that to say this is by design?

**Comment by Estrax** [comment]
@anelson not exactly sure, but probably yes. I'll do a follow-up with a Cortex team and will get back there with a response.

**Comment by gouthamve** [comment]
This is indeed a Cortex limitation that will go away in the future. It is not coming from Grafana.

A workaround is that you can query the recent 5mins (or a time-range in the recent 15mins), or you can do an instant query (close the graph panel in explore mode).

**Comment by unfor19** [comment]
Thanks @gouthamve , closing the graph panel did the trick (I'm using Grafana Cloud)
