### ISSUE TITLE
Variable multi value selection is broken in Grafana 7

### ISSUE THREAD

**Issue by datamuc** [grafana/grafana#24990]
**What happened**: In Grafana 6 it was possible to select multiple values from a variable by searching, clicking, searching another one, and clicking again. But this doesn't work in Grafana 7 anymore, on the second search the previous selected value gets unselected.

**What you expected to happen**: Keep the selected values while searching for a new one

**How to reproduce it (as minimally and precisely as possible)**:

I've attached a dashboard to illustrate the problem, there is a variable with the values server00 to server99 in it. Search for let's say server50 in the search box and click on the resulting entry, and then search for server90 and try to select that without losing server50.

[test.json.txt](https://github.com/grafana/grafana/files/4663166/test.json.txt)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: none
- OS Grafana is installed on: Linux
- User OS & Browser: Brave and Firefox
- Grafana plugins: none
- Others: n/a

**Comment by vldbel** [comment]
+1,
heavily affected, ability to get set of hosts from zabbix is lost.

**Comment by davidbonnici1984** [comment]
+1
I confirm this when getting hosts from Zabbix is lost.
Video recording is here
https://streamable.com/bqanuf

**Comment by datamuc** [comment]
@davidbonnici1984 I'm talking about something completely different. This is what i'm talking about:

https://streamable.com/1tn3vi

I always lose the previous selection once I start typing in the box.

**Comment by vldbel** [comment]
Same issue @datamuc demonstrated in video. Previous selection lost while new search. Tried in FF and Chrome. Colleagues reported for mac/Safari

**Comment by hugohaggmark** [comment]
> +1
> I confirm this when getting hosts from Zabbix is lost.
> Video recording is here
> https://streamable.com/bqanuf

@davidbonnici1984 thank you for taking the time to record that error but that seems unrelated to this issue. Would be great if you could open a separate issue for your Zabbix issue.

**Comment by hugohaggmark** [comment]
@datamuc @vldbel can confirm that this is an unintentional change that we introduced when migrating from Angular to React/Redux.

**Comment by eamodeorubio** [comment]
+1 Also affected by this

**Comment by hugohaggmark** [comment]
@datamuc brilliant catch and I'm glad we could fix it so fast!
