### ISSUE TITLE
Unable to share rendered graph with SSL (self signed)

### ISSUE THREAD

**Issue by hurrycaine** [grafana/grafana#2499]
I do not have a SSL cert from a CA to test but I did name the self signed cert to the name of the fqdn of the machine and added it to my OsX system trusted certs so that it shows up green.

When I click on "Direct Link Rendered Image" with http all works great!
With HTTPS the get comes back with a 200 after 10 seconds and its blank. I tried running it on 443 instead of 3001 as I read somewhere but saw no difference.

```
https://xxxxxx.xxxxxx.com:3001/render/dashboard-solo/db/sensu?panelId=1&fullscreen&from=1439387604829&to=1439391204829&var-application=sensu&width=1000&height=500
```

I am trying to get this to show up in uchiwa and realized the render was not working when I only enabled https. I thought it was an issue with uchiwa but then realized the link does not return when I use https. 

I tried to work around this by using nginx for ssl and using anonymous for http and uchiwa graphs.  I could not get the nginx config (maybe root_url?)  to work right so that it worked properly through nginx. Even if I did get it working it looks like it might would break the http.

Ideally I would like the https to work with the rendering, has anyone got this working?

**Comment by torkelo** [comment]
what version of Grafana are you using? 

If it is the same as this, it is fixed in 2.1
https://github.com/grafana/grafana/pull/2053

**Comment by hurrycaine** [comment]
Sorry I should have said that ... im on 2.1.1 . Tried it this morning with the latest

**Comment by hurrycaine** [comment]
Sorry, you are right this is a duplicate issue, not sure how I missed that but to clarify I am not doing anything via proxy to replicate this issue. I am just changing from http to https to reproduce and I am on 2.1.1. 

```
PhantomRenderer::renderToPng url https://localhost:443/dashboard-solo/db/sensu?panelId=1&fullscreen&from=1439389154866&to=1439392754866&var-application=sensu&width=1000&height=500
```

**Comment by torkelo** [comment]
https://localhost:443 does not look right, root_url should be the public url that you use in the browser

**Comment by hurrycaine** [comment]
I thought the same thing after I pasted that, but it does work with http for some reason. I did change the root_url to the fqdn, same issue. I don't see an error but like in the previous it seems to be a blank image.

https configured takes 10 seconds to do blank render

```
PhantomRenderer::renderToPng url https://xxxxxx.xxxxxx.com:3001/dashboard-solo/db/sensu?panelId=1&fullscreen&from=1439397517787&to=1439401117787&var-application=sensu&width=1000&height=500
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2055
Content-Type: image/png
Last-Modified: Wed, 12 Aug 2015 17:40:47 GMT
Date: Wed, 12 Aug 2015 17:40:47 GMT


```html
<html><head><meta name="viewport" content="width=device-width, minimum-scale=0.1"><title>sensu (1000×500)</title></head>
<body style="margin: 0px;">
<img style="-webkit-user-select: none; cursor: zoom-in;" src="https://xxxxxx.xxxxx.com:3001/render/dashboard-solo/db/sensu?panelId=1&amp;fullscreen&amp;from=1439397517787&amp;to=1439401117787&amp;var-application=sensu&amp;width=1000&amp;height=500" width="358" height="179"></body>
</html>
```
http take sub second to render.
What is interesting is there is an error when it works but not an error when it does not

```
2015/08/12 13:43:18 [I] Listen: http://0.0.0.0:3001
2015/08/12 13:43:54 [I] PhantomRenderer::renderToPng url http://xxxxxx.xxxxxxx.com:3001/dashboard-solo/db/sensu?panelId=1&fullscreen&from=1439397833564&to=1439401433564&var-application=sensu&width=1000&height=500
2015/08/12 13:43:54 [I] ^[[1;31mCompleted /dashboard-solo/db/sensu 404 Not Found in 2.255424ms^[[0m

```
(Content-Length is much larger when it actually returns an image)
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 51464
Content-Type: image/png
Last-Modified: Wed, 12 Aug 2015 17:53:10 GMT
Date: Wed, 12 Aug 2015 17:53:10 GMT


```html
<html><head><meta name="viewport" content="width=device-width, minimum-scale=0.1"><title>sensu (1001×500)</title></head>
<body style="margin: 0px;">
<img style="-webkit-user-select: none; cursor: zoom-in;" src="http://xxxxxx.xxxxxxx.com:3001/render/dashboard-solo/db/sensu?panelId=1&amp;fullscreen&amp;from=1439397833564&amp;to=1439401433564&amp;var-application=sensu&amp;width=1000&amp;height=500" width="358" height="179"></body>
</html>
```

**Comment by hurrycaine** [comment]
Could you please open this ticket up, at least temporarily? This is still an issue for me.

thanks

**Comment by torkelo** [comment]
@hurrycaine you still seem to have a root_url that is incorrect, 

PhantomRenderer::renderToPng url https://xxxxxx.xxxxxx.com:3001 

why port 3001? are you using 3001 as an https port?

**Comment by hurrycaine** [comment]
I am using 3001 as the http or https port.  Running uchiwa on the same server so I had to move one.

Again, all I am doing is flipping from http to https, the site works perfectly fine both ways (http vs https), except with the render issue.

http custom.ini
Works with root_url to localhost or to fqdn
```ini
[server]
#cert_key = /opt/app/grafana/ssl/key.pem
http_port = 3001
#cert_file = /opt/app/grafana/ssl/cert.pem
protocol = http

[auth.anonymous]
enabled = true

[paths]
data = /opt/app/grafana/data
logs = /opt/app/grafana/grafana/logs

[users]
allow_sign_up = false
```

It does not work with localhost or fqdn, I've tried changing the domain parameter, I have hard coded the root_url (again no issues with https)

```ini
[server]
cert_key = /opt/app/grafana/ssl/key.pem
http_port = 3001
cert_file = /opt/app/grafana/ssl/cert.pem
protocol = https
root_url = %(protocol)s:xxxxxx.xxxxx.com:%(http_port)s/

[auth.anonymous]
enabled = true

[paths]
data = /opt/app/grafana/data
logs = /opt/app/grafana/grafana/logs

[users]
allow_sign_up = false
```

**Comment by hurrycaine** [comment]
Hmmm... I think you are on the right track for sure. I can replicate the issue with http by making the root_url bad

So if i use http and put in the root_url incorrectly the same behavior is observed. I'll play around with the root_url some more.

```ini
protocol = http
root_url = %(protocol)s:wrong.wrong.com:%(http_port)s/
```

**Comment by hurrycaine** [comment]
Im running this on my companies internal cloud... let me try this somewhere else. Maybe there is more going on with the network than I am aware of.
