### ISSUE TITLE
New Text Panel (React)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#25004]
We are pretty close to migrate to the new react based text panel: 

* [x] Text editor with line wrapping
* [x] Text editor with syntax highlighting (#25618)
* [x] Deprecate and remove Angular Text Panel from plugins list and visualisation picker (#25504)

**Comment by hugohaggmark** [comment]
@torkelo is the checklist feature complete for 7.1 or are there more details that I need to know more about?

**Comment by ryantxu** [comment]
When we have the Monaco editor merged, this should be ready.

**Comment by hugohaggmark** [comment]
Thanks Ryan, let me know if I can help out with anything.

**Comment by dprokop** [comment]
@hugohaggmark would be great if you could have a look at failing build in @ryantxu PR: https://github.com/grafana/grafana/pull/25251

**Comment by hugohaggmark** [comment]
@dprokop sure, I'll have a look
