### ISSUE TITLE
Template line hidden in view panel when header line doesn't fit on one line

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#2500]
To reproduce have a longish dashboard name and then choose a specific date range (which is also longish) and your header will get wrapped to two lines, which then in panel view causes your template line to be hidden by your panel.

Ok: 
![image](https://cloud.githubusercontent.com/assets/917241/9230666/ea9686f2-4123-11e5-9de7-7b4a4f1adbc3.png)

Not ok:
![image](https://cloud.githubusercontent.com/assets/917241/9230676/f8e28850-4123-11e5-8ae8-86a1bf3b34aa.png)

I also noticed that once you use the multi pick it's easy to get a really long template item and the same issue as above can occur, but this time because the template line is greater than one line high:
![image](https://cloud.githubusercontent.com/assets/917241/9230837/ef09a010-4124-11e5-945a-c2ba47409db3.png)

**Comment by utkarshcmu** [comment]
@maddenca Are you still seeing this issue because I cannot reproduce this here? 

<img width="1409" alt="screen shot 2015-09-24 at 5 56 03 am" src="https://cloud.githubusercontent.com/assets/1019609/10062611/db7b9192-6281-11e5-944b-f4426d1bfc79.png">

**Comment by maddenca** [comment]
I am running 2.1.3 and no change: 
![image](https://cloud.githubusercontent.com/assets/917241/10076422/bd0b2b14-62db-11e5-9ed1-304bfe9ba240.png)

See how the template runs over to a 2nd line (in this case I used mult-pick template and picked a lot of choices) and then in view panel mode it hides it.

**Comment by utkarshcmu** [comment]
I am able to reproduce your issue in 2.1.3, so this is a legitimate bug. Here is my test screenshot:

<img width="1424" alt="screen shot 2015-09-24 at 9 02 43 pm" src="https://cloud.githubusercontent.com/assets/1019609/10077923/1ffbd61e-6300-11e5-847a-9cddac36301f.png">

Now here is the screenshot from the current master branch of the same "View" mode:

<img width="1417" alt="screen shot 2015-09-24 at 9 03 42 pm" src="https://cloud.githubusercontent.com/assets/1019609/10077906/0a98ec62-6300-11e5-9c5b-a08ce8bc2209.png">

I do not know how this bug got fixed but in the master branch it does not exist anymore. @torkelo may have some clue about this fix post 2.1.3.

So, I think this bug should go away in the next release of Grafana.

**Comment by torkelo** [comment]
This was fixed when I changed how full screen mode (panel edit mode) was implemented, it is now longer implemented using css fixed positioning
