### ISSUE TITLE
Filtering logs using Loki in Explore section fails if there is a text filter with a dash

### ISSUE THREAD

**Issue by skgsergio** [grafana/grafana#25010]
**What happened**:
While exploring logs from Loki in Grafana's Explore we've noticed that If you have a text filter containing a dash (`-`) it breaks the query when you filter by clicking a value in a log entry.

For example if you perform this query `{namespace="foo",container="bar"} != "foo-bar"` and then go to a log entry and filter by any field it performs this query `{namespace="foo",container="bar",field_name="value"} != "foo{field_name="value"}-bar"` and gives an error.

On the other hand, if the filter doesn't contain a dash (`-`) it works as expected: `{namespace="foo",container="bar"} != "foobar"` -> `{namespace="foo",container="bar",field_name="value"} != "foobar"`

**What you expected to happen**:
I expected Grafana to perform this query `{namespace="foo",container="bar",field_name="value"} != "foo-bar"`

**How to reproduce it (as minimally and precisely as possible)**:
1.- Perform any Loki log search that contains a text filter with a dash (`-`)
  Example: `{field="value"} != "foo-bar"`
2.- Go to any log entry, expand details and click any of its value to filter
3.- It fails

**Anything else we need to know?**:
![GrafanaLokiBug-Small](https://user-images.githubusercontent.com/186349/82649611-c4e9e600-9c19-11ea-9bc5-b84fb5c32549.gif)

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Loki, built-in version
- OS Grafana is installed on: Official docker image
- User OS & Browser: macOS 10.15 & Google Chrome 83
- Grafana plugins: None
- Others: N/A

**Comment by Estrax** [comment]
Fixed in #25059.
