### ISSUE TITLE
Panel context dropdown menu does not open from title in chrome

### ISSUE THREAD

**Issue by haacs** [grafana/grafana#25018]
**What happened**:
I created a new panel, clicked the title and the caret next to it, but the menu did not appear

**What you expected to happen**:
I expected the menu to appear

**How to reproduce it (as minimally and precisely as possible)**:
click on the title of a panel in chrome

**Anything else we need to know?**:
bug does not appear in firefox 76.0.1 (64-bit)

**Environment**:
- Grafana version: 7.0 (installed via homebrew)
- Data source type & version: prometheus/latest
- OS Grafana is installed on: macOS 10.15.4
- User OS & Browser: macOS 10.15.4, Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
No other similar reports, do you get the same on https://play.grafana.org/  ?

**Comment by haacs** [comment]
Yes, even after restarting the browser an disabling all extensions but google analytics opt-out

**Comment by torkelo** [comment]
Unable to replicate on OSX & Chrome 83

**Comment by haacs** [comment]
I also tried it in a virtual machine on Ubuntu, there everything works fine. Looks like on my machine the title container of the panel is missing two event listeners.

in chrome there only is only click in react-dom.production.min.js:91
![image](https://user-images.githubusercontent.com/11018180/82680465-96d1c980-9c4c-11ea-899a-e57e4c12d9a7.png)

but in firefox I also see onClick and onMouseDown in PanelHeader.tsx:60
![image](https://user-images.githubusercontent.com/11018180/82680529-acdf8a00-9c4c-11ea-986b-a78567075e2a.png)

Thanks for your help, I will continue to investigate and reach out again if I find something.

**Comment by haacs** [comment]
I figured it out: had enabled experimental features in chrome a ling time ago and forgot about chrome://flags, I am sorry. 😢 
Can't say for sure, but probably was this issue with chrome adding double quotes in the value of a new header: https://bugs.chromium.org/p/chromium/issues/detail?id=1081026

**Comment by sporkmonger** [comment]
This also happened for me, same fix as above. Given that there's a good chance the feature being explored leaves experimental mode, this might be an issue worth reopening.

**Comment by danny460** [comment]
just adding to it. this has happened to me too. same fix as above.

**Comment by theunkohlbeck** [comment]
Same here, happended to me yesterday. Before that it worked fine.  Disabling expermental feature fixes it.

**Comment by rednasem** [comment]
Happens to me with Chrome on two different computers and two different Chrome versions.
All Chrome experimetnal flags are disabled. 

OS: Debian Sid
Browsers: Chrome: 87.0.4280.47 and 88.0.4315.5 
Grafana: 7.3.1

Please reopen the issue.

**Comment by pkutaj** [comment]
Same here. 
OS: Win10
Browser: Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Grafana: Version 6.7.3 (a04ef6cefc)

**Comment by jkreileder** [comment]
The problem, at least on MacOS with a touchpad, is that the onMouseDown event has clientX/Y as integers while the onMenuToggle has them as floats:

<img width="829" alt="Screen Shot 2020-12-02 at 15 23 13" src="https://user-images.githubusercontent.com/4390544/100894772-2211fe80-34bd-11eb-8df7-4b77dc5f68d4.png">

This works for me:
```diff
--- a/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx
+++ b/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx
@@ -1,6 +1,5 @@
 import React, { Component } from 'react';
 import classNames from 'classnames';
-import { isEqual } from 'lodash';
 import { DataLink, LoadingState, PanelData, PanelMenuItem, QueryResultMetaNotice, ScopedVars } from '@grafana/data';
 import { AngularComponent, getTemplateSrv } from '@grafana/runtime';
 import { ClickOutsideWrapper, Icon, IconName, Tooltip } from '@grafana/ui';
@@ -61,7 +60,10 @@ export class PanelHeader extends Component<Props, State> {
   };
 
   isClick = (clickCoordinates: ClickCoordinates) => {
-    return isEqual(clickCoordinates, this.clickCoordinates);
+    return (
+      Math.abs(clickCoordinates.x - this.clickCoordinates.x) < 2 &&
+      Math.abs(clickCoordinates.y - this.clickCoordinates.y) < 2
+    );
   };
 
   onMenuToggle = (event: React.MouseEvent<HTMLDivElement>) => {
```

**Comment by S-Mann** [comment]
I disabled all my chrome developer flags.
I am using:

Chrome: Version 89.0.4389.90 (Official Build) (32-bit)
OS: Windows 10 Enterprise, 1909, 18363.1440

When I click on the dropdown icon I don't get any dropdown, I can still edit the panel by clicking the dropdown and then pressing `e` on my keyboard but I can't physically click the edit option in the dropdown as clicking the dropdown does nothing.

**Comment by Maixy** [comment]
Also still seeing this issue on MacOS, Chrome Version 89.0.4389.90 (Official Build) (x86_64), Grafana 7.0.3

@S-Mann 's recommendation around typing `e` worked!

**Comment by zoharfuchs** [comment]
I have the same issue on MacOS, Chrome Version 89.0.4389.114 (Official Build) (x86_64), Grafana v7.2.1 (72a6c64532)

Recommendation around typing e works.

**Comment by gquinones** [comment]
Same as zoharfuchs.

**Comment by pkutaj** [comment]
Same here. For now, I just use [Open in Firefox - Chrome Web Store](https://chrome.google.com/webstore/detail/open-in-firefox/lmeddoobegbaiopohmpmmobpnpjifpii) extension to open the dashboard in firefox instantly and proceed from there.

**Comment by risoms** [comment]
This issue doesn't look like it's fixed for Chrome (Version 89.0.4389.90 (Official Build) (x86_64)). Should a new ticket be opened @torkelo?

**Comment by torkelo** [comment]
@risoms we have an open issue https://github.com/grafana/grafana/issues/31374

**Comment by Naverin89** [comment]
Hello guys! Not sure it will work for you, but in my case different page zoom (CTRL+mouse wheel) seems to solve the problem. Dropdown menu works for different page scale (75%, 100%, 125%).

**Comment by stevenh** [comment]
I can confirm chrome Version 89.0.4389.114 (Official Build) (64-bit) on Windows with no experimental flags on Grafana v6.7.4 is effected
