### ISSUE TITLE
v7: grafana-clock-panel can't seem to update it to v1.1.1

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25016]
**What happened**:
I followed v7 update instructions including afterwards doing a sudo grafana-cli plugins update-all but this did not update the clock panel to v1.1.1. And doing a manual remove/install still downloads and installs v1.0.3

**What you expected to happen**:
That the update would update all panels to the latest versions. Or at least I could manually update to latest version or even remove/re-install the panel to get the latest version. Whatever I do I cannot seem to get it to download/install the latest version. I can see the latest version on the website (1.1.1) and the api url seems to show that version

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Grafana to to v7 and then attempt to use grafana-cli to install latest version yet it downloads the old 1.0.3 version:
`sudo grafana-cli plugins install grafana-clock-panel`
`installing grafana-clock-panel @ 1.0.3 from: https://grafana.com/api/plugins/grafana-clock-panel/versions/1.0.3/download into: /var/lib/grafana/plugins`
`✔ Installed grafana-clock-panel successfully`

**Anything else we need to know?**:
grafana-cli seems to be the new version:
`grafana-cli --version`
`Grafana CLI version 7.0.0`

But it won't show the new version of the panel:
`grafana-cli plugins list-versions grafana-clock-panel`
`1.0.3`
`1.0.2`
`1.0.1`
`1.0.0`
`0.1.0`
`0.0.9`
`0.0.8`
`0.0.7`
`0.0.6`
`0.0.5`
`0.0.3`
`0.0.2`
`0.0.1`

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: prometheus v2.7.1 blackbox-exporter v0.13.0
- OS Grafana is installed on: Ubuntu v19.10
- User OS & Browser: Ubuntu v20.04 Firefox v76.0.1
- Grafana plugins: grafana-clock-panel v1.0.3
- Others:

**Comment by papagian** [comment]
The plugin grafana depedency was was not set properly (it was >7.0.0 instead of >=7.0.0)

It was also reported [here](https://github.com/grafana/grafana/issues/23306#issuecomment-632028340).

**Comment by therealcodlord** [comment]
Thanks, confirmed it shows and updates fine now via `grafana-cli`
