### ISSUE TITLE
API-request generated annotations do not show

### ISSUE THREAD

**Issue by giddyhup** [grafana/grafana#25011]
**What happened**:

Annotations that are submitted to via POST request do not appear 

**What you expected to happen**:

Annotations should be visible

**How to reproduce it (as minimally and precisely as possible)**:

Create syntactically correct annotation via POST request. Look at graph for the time frame where they should appear.

**Anything else we need to know?**:

Result of query for annotations, manually entered annotation 55 appears:

```
[
  {
    "id": 53,
    "alertId": 0,
    "alertName": "",
    "dashboardId": 6,
    "panelId": 2,
    "userId": 0,
    "newState": "",
    "prevState": "",
    "created": 1590135215844,
    "updated": 1590135215844,
    "time": 1590081155,
    "timeEnd": 1590082355,
    "text": "auto 26.2 max",
    "tags": [
      "max"
    ],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {}
  },
  {
    "id": 54,
    "alertId": 0,
    "alertName": "",
    "dashboardId": 6,
    "panelId": 2,
    "userId": 0,
    "newState": "",
    "prevState": "",
    "created": 1590135215861,
    "updated": 1590135215861,
    "time": 1590032088,
    "timeEnd": 1590033288,
    "text": "auto 11.7 min",
    "tags": [
      "min"
    ],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {}
  },
  {
    "id": 55,
    "alertId": 0,
    "alertName": "",
    "dashboardId": 6,
    "panelId": 2,
    "userId": 0,
    "newState": "",
    "prevState": "",
    "created": 1590137567051,
    "updated": 1590137567051,
    "time": 1590075087010,
    "timeEnd": 1590075087010,
    "text": "manual",
    "tags": [
      "min"
    ],
    "login": "admin",
    "email": "admin@localhost",
    "avatarUrl": "/avatar/46d229b033af06a191ff2267bca9ae56",
    "data": {}
  }
]

```

**Environment**:
- Grafana version: 7.0
- Data source type & version: Influxdb 1.7.10
- OS Grafana is installed on: Raspberry Pi 3b+
- User OS & Browser: Windows 10, Raspbian, Firefox, Chrome, Chromium
- Grafana plugins: Graph
- Others:

**Comment by giddyhup** [comment]
I now also tested it with bearer authentication (API token) and basic authentication, with admin and with edit rights. The annotations do not appear on my graph.

**Comment by TimothyBJacobs** [comment]
Related Topic: https://community.grafana.com/t/api-generated-annotations-not-showing/30572

**Comment by TimothyBJacobs** [comment]
As far as I can tell, this happens when passing a "regular" unix timestamp instead of the number of _milliseconds_ since epoch. I've only used Annotations on v7, so I'm not sure if it is a regression or not.

**Comment by giddyhup** [comment]
User (me) didn't read the documentation. Not an issue. Closed.
