### ISSUE TITLE
Support prometheus templating functions in metrics query

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#25029]
**What would you like to be added**:

Add support for the functions of [prometheus query variables](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/#query-variable) in metric querys in Panels.
e.g.:
```
label_values(instance)
```
to get a table of all scraped instances.

**Why is this needed**:

Labels are often used to display important metadata on a metric with value `1`, since there are no string values in prometheus.
e.g.:
```
grafana_build_info{branch="HEAD",edition="oss",goversion="go1.14.1",revision="aee1438ff2",version="7.0.0"} 1
```

As of Grafana `v7` it is hard to display prometheus label values in dashboard panels because the `Singlestat` Panel has been deprecated and [`Stat` panel is unable to](https://github.com/grafana/grafana/issues/24076). 
Only suitable way I found is using `Table` panel which causes more effort and is not as pretty. See also this [slack thread](https://grafana.slack.com/messages/CSKQV9Y5B/p1589571481048300).
So currently waiting for `v7.1` for #24076 . While looking for solutions I realized this missing feature.

One could use `label_values(grafana_build_info, version)` to easily display the grafana version in dashboard.

**Comment by torkelo** [comment]
I am not sure what your asking for 

We will add string values support in stat panel. 

Will also add an option to show name instead of value in stat panel (so you can show label instead of value), https://github.com/grafana/grafana/issues/23880

**Comment by Mario-Hofstaetter** [comment]
I'll try to to be more concise:

### Works:
![grafik](https://user-images.githubusercontent.com/33002073/82732259-681b2800-9d0c-11ea-8c87-123a0a110892.png)

### Does not work:
![grafik](https://user-images.githubusercontent.com/33002073/82732292-9d277a80-9d0c-11ea-96c5-2e692f8eb3b8.png)

Add support for these functions in panel querys:
| Name                             | Description                                                             |
| -------------------------------- | ----------------------------------------------------------------------- |
| _label_\__names()_               | Returns a list of label names.                                          |
| _label_\__values(label)_         | Returns a list of label values for the `label` in every metric.         |
| _label_\__values(metric, label)_ | Returns a list of label values for the `label` in the specified metric. |
| _metrics(metric)_                | Returns a list of metrics matching the specified `metric` regex.        |
| _query_\__result(query)_         | Returns a list of Prometheus query result for the `query`.              |

although `query_result` is not very useful without the additional regex.

**Comment by cyberw** [comment]
@torkelo I know this is really old (perhaps you didnt see the response because it came just after closing), but it is still very relevant (perhaps there is already a solution for it?)
