### ISSUE TITLE
Bar gauge sort

### ISSUE THREAD

**Issue by petoknm** [grafana/grafana#25025]
**What happened**
I created a bar gauge with data from prometheus. Data arrives in undefined order which results in the bars switching places almost every time the dashboard refreshes.
![Screenshot_2020-05-22 Backend - Grafana(1)](https://user-images.githubusercontent.com/5087675/82683948-1dd57080-9c52-11ea-81bc-c22d47551b5c.png)
![Screenshot_2020-05-22 Backend - Grafana](https://user-images.githubusercontent.com/5087675/82683949-1e6e0700-9c52-11ea-91ea-068d87ed1e9e.png)

**What you expected to happen**:
I want to be able to sort the "columns" by their name or value.

**How to reproduce it (as minimally and precisely as possible)**:
Create a bar gauge panel with some data from prometheus.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (official docker image)
- User OS & Browser: Linux, Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by therealcodlord** [comment]
You can already sort by value by using the functions `sort` or `sort_desc` in your query. See here:
[https://prometheus.io/docs/prometheus/latest/querying/functions/#sort](url)

Sorting by name I have not found a way of doing that. I did find a workaround by adding labels to my targets in my prometheus.yml file. It seems to sort alphabetically so I worked out if I put a label titled `aaa` (which would likely always sort first) then the label value of `1.01`, `1.02`, `1.03` etc it will show things in that order.

**Comment by torkelo** [comment]
Sorting is mainly handled in the query, we might add a sort transform
